Kodi Documentation: KODI::GAME::CPhysicalFeature Class Reference
KODI::GAME::CPhysicalFeature Class Reference
Games
#include <PhysicalFeature.h>
Public Member Functions
CPhysicalFeature ()=default
CPhysicalFeature (int labelId)
CPhysicalFeature (const CPhysicalFeature &other)
void Reset (void)
CPhysicalFeature & operator= (const CPhysicalFeature &rhs)
JOYSTICK::FEATURE_TYPE Type (void) const
JOYSTICK::FEATURE_CATEGORY Category (void) const
const std::string & Name (void) const
std::string Label (void) const
int LabelID (void) const
std::string CategoryLabel (void) const
JOYSTICK::INPUT_TYPE InputType (void) const
KEYBOARD::XBMCKey Keycode () const
bool Deserialize (const tinyxml2::XMLElement *pElement, const CController *controller, JOYSTICK::FEATURE_CATEGORY category, int categoryLabelId)
Private Attributes
const CController * m_controller = nullptr
JOYSTICK::FEATURE_TYPE m_type = JOYSTICK::FEATURE_TYPE::UNKNOWN
JOYSTICK::FEATURE_CATEGORY m_category = JOYSTICK::FEATURE_CATEGORY::UNKNOWN
int m_categoryLabelId = -1
std::string m_strName
int m_labelId = -1
JOYSTICK::INPUT_TYPE m_inputType = JOYSTICK::INPUT_TYPE::UNKNOWN
KEYBOARD::XBMCKey m_keycode = KEYBOARD::XBMCKey::XBMCK_UNKNOWN
Constructor & Destructor Documentation
CPhysicalFeature() [1/3]
KODI::GAME::CPhysicalFeature::CPhysicalFeature () default
Referenced by Reset().
CPhysicalFeature() [2/3]
CPhysicalFeature::CPhysicalFeature (int labelId)
References m_labelId, and Reset().
CPhysicalFeature() [3/3]
KODI::GAME::CPhysicalFeature::CPhysicalFeature (const CPhysicalFeature & other) inline
Member Function Documentation
Category()
JOYSTICK::FEATURE_CATEGORY KODI::GAME::CPhysicalFeature::Category (void) const inline
References m_category.
CategoryLabel()
std::string CPhysicalFeature::CategoryLabel (void) const
References g_localizeStrings, CLocalizeStrings::Get(), CLocalizeStrings::GetAddonString(), ADDON::CAddon::ID(), m_categoryLabelId, and m_controller.
Deserialize()
bool CPhysicalFeature::Deserialize (const tinyxml2::XMLElement * pElement, const CController * controller, JOYSTICK::FEATURE_CATEGORY category, int categoryLabelId)
References XMLUtils::GetAttribute(), LAYOUT_XML_ATTR_FEATURE_LABEL, LAYOUT_XML_ATTR_FEATURE_NAME, LAYOUT_XML_ATTR_INPUT_TYPE, LAYOUT_XML_ATTR_KEY_SYMBOL, CLog::Log(), LOGDEBUG, LOGERROR, m_category, m_categoryLabelId, m_controller, m_inputType, m_keycode, m_labelId, m_strName, m_type, Reset(), KODI::GAME::CControllerTranslator::TranslateFeatureType(), KODI::GAME::CControllerTranslator::TranslateInputType(), KODI::KEYBOARD::CKeyboardTranslator::TranslateKeysym(), and XBMCK_UNKNOWN.
Referenced by KODI::GAME::CControllerLayout::Deserialize().
InputType()
JOYSTICK::INPUT_TYPE KODI::GAME::CPhysicalFeature::InputType (void) const inline
References m_inputType.
Referenced by FeatureTypeEqual::operator()().
Keycode()
KEYBOARD::XBMCKey KODI::GAME::CPhysicalFeature::Keycode () const inline
References m_keycode.
Referenced by KODI::GAME::CGUIConfigurationWizard::RegisterKey().
Label()
std::string CPhysicalFeature::Label (void) const
References g_localizeStrings, CLocalizeStrings::Get(), CLocalizeStrings::GetAddonString(), ADDON::CAddon::ID(), label, m_controller, and m_labelId.
Referenced by KODI::GAME::CGUIFeatureButton::CGUIFeatureButton(), KODI::GAME::CGUIFeatureButton::DoPrompt(), KODI::GAME::CGUICardinalFeatureButton::PromptForInput(), KODI::GAME::CGUIScalarFeatureButton::PromptForInput(), KODI::GAME::CGUISelectKeyButton::PromptForInput(), KODI::GAME::CGUIThrottleButton::PromptForInput(), and KODI::GAME::CGUIWheelButton::PromptForInput().
LabelID()
int KODI::GAME::CPhysicalFeature::LabelID (void) const inline
References m_labelId.
Name()
const std::string & KODI::GAME::CPhysicalFeature::Name (void) const inline
References m_strName.
Referenced by KODI::GAME::CGUIConfigurationWizard::MapPrimitive().
operator=()
CPhysicalFeature & CPhysicalFeature::operator= (const CPhysicalFeature & rhs)
References m_category, m_categoryLabelId, m_controller, m_inputType, m_keycode, m_labelId, m_strName, and m_type.
Reset()
void CPhysicalFeature::Reset (void)
References CPhysicalFeature().
Referenced by CPhysicalFeature(), Deserialize(), and KODI::GAME::CGUISelectKeyButton::Reset().
Type()
JOYSTICK::FEATURE_TYPE KODI::GAME::CPhysicalFeature::Type (void) const inline
References m_type.
Referenced by KODI::GAME::CGUIConfigurationWizard::MapPrimitive(), and FeatureTypeEqual::operator()().
Member Data Documentation
m_category
JOYSTICK::FEATURE_CATEGORY KODI::GAME::CPhysicalFeature::m_category = JOYSTICK::FEATURE_CATEGORY::UNKNOWN private
Referenced by Category(), Deserialize(), and operator=().
m_categoryLabelId
int KODI::GAME::CPhysicalFeature::m_categoryLabelId = -1 private
Referenced by CategoryLabel(), Deserialize(), and operator=().
m_controller
const CController* KODI::GAME::CPhysicalFeature::m_controller = nullptr private
Referenced by CategoryLabel(), Deserialize(), Label(), and operator=().
m_inputType
JOYSTICK::INPUT_TYPE KODI::GAME::CPhysicalFeature::m_inputType = JOYSTICK::INPUT_TYPE::UNKNOWN private
Referenced by Deserialize(), InputType(), and operator=().
m_keycode
KEYBOARD::XBMCKey KODI::GAME::CPhysicalFeature::m_keycode = KEYBOARD::XBMCKey::XBMCK_UNKNOWN private
Referenced by Deserialize(), Keycode(), and operator=().
m_labelId
int KODI::GAME::CPhysicalFeature::m_labelId = -1 private
Referenced by CPhysicalFeature(), Deserialize(), Label(), LabelID(), and operator=().
m_strName
std::string KODI::GAME::CPhysicalFeature::m_strName private
Referenced by Deserialize(), Name(), and operator=().
m_type
JOYSTICK::FEATURE_TYPE KODI::GAME::CPhysicalFeature::m_type = JOYSTICK::FEATURE_TYPE::UNKNOWN private
Referenced by Deserialize(), operator=(), and Type().
The documentation for this class was generated from the following files:
PhysicalFeature.h
PhysicalFeature.cpp