Kodi Documentation: kodi::addon::PVRTimerType Class Reference
kodi::addon::PVRTimerType Class Reference
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 6. Timer » class PVRTimerType
#include <Timers.h>
Public Member Functions
void SetId (unsigned int id)
required
This type's identifier. Ids must be > PVR_TIMER_TYPE_NONE.
unsigned int GetId () const
To get with SetAttributes changed values.
void SetAttributes (uint64_t attributes)
required
Defines the attributes for this type (PVR_TIMER_TYPE_* constants).
uint64_t GetAttributes () const
To get with SetAttributes changed values.
void SetDescription (const std::string &description)
optional
A short localized string describing the purpose of the type. (e.g. "Any time at this channel if title matches").
std::string GetDescription () const
To get with SetDescription changed values.
void SetPriorities (const std::vector< PVRTypeIntValue > &priorities, int prioritiesDefault=-1)
optional
Priority value definitions.
std::vector< PVRTypeIntValue > GetPriorities () const
To get with SetPriorities changed values.
void SetPrioritiesDefault (int prioritiesDefault)
optional
The default value for PVRTimer::SetPriority().
int GetPrioritiesDefault () const
To get with SetPrioritiesDefault changed values.
void SetLifetimes (const std::vector< PVRTypeIntValue > &lifetimes, int lifetimesDefault=-1)
optional
Lifetime value definitions.
std::vector< PVRTypeIntValue > GetLifetimes () const
To get with SetLifetimes changed values.
void SetLifetimesDefault (int lifetimesDefault)
optional
The default value for SetLifetimes().
int GetLifetimesDefault () const
To get with SetLifetimesDefault changed values.
void SetPreventDuplicateEpisodes (const std::vector< PVRTypeIntValue > &preventDuplicateEpisodes, int preventDuplicateEpisodesDefault=-1)
optional
Prevent duplicate episodes value definitions.
std::vector< PVRTypeIntValue > GetPreventDuplicateEpisodes () const
To get with SetPreventDuplicateEpisodes changed values.
void SetPreventDuplicateEpisodesDefault (int preventDuplicateEpisodesDefault)
optional
The default value for PVRTimer::SetPreventDuplicateEpisodes().
int GetPreventDuplicateEpisodesDefault () const
To get with SetPreventDuplicateEpisodesDefault changed values.
void SetRecordingGroups (const std::vector< PVRTypeIntValue > &recordingGroup, int recordingGroupDefault=-1)
optional
Array containing the possible values of PVRTimer::SetRecordingGroup()
std::vector< PVRTypeIntValue > GetRecordingGroups () const
To get with SetRecordingGroups changed values.
void SetRecordingGroupDefault (int recordingGroupDefault)
optional
The default value for PVRTimer::SetRecordingGroup().
int GetRecordingGroupDefault () const
To get with SetRecordingGroupDefault changed values.
void SetMaxRecordings (const std::vector< PVRTypeIntValue > &maxRecordings, int maxRecordingsDefault=-1)
optional
Array containing the possible values of PVRTimer::SetMaxRecordings().
std::vector< PVRTypeIntValue > GetMaxRecordings () const
To get with SetMaxRecordings changed values.
void SetMaxRecordingsDefault (int maxRecordingsDefault)
optional
The default value for SetMaxRecordings().
int GetMaxRecordingsDefault () const
To get with SetMaxRecordingsDefault changed values.
void SetCustomSettingDefinitions (const std::vector< PVRSettingDefinition > &defs)
optional
Array containing the possible custom integer setting definitions.
std::vector< PVRSettingDefinition > GetCustomSettingDefinitions () const
To get with SetCustomSettingDefinitions changed values.
Public Member Functions inherited from kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >
DynamicCStructHdl ()
DynamicCStructHdl (const DynamicCStructHdl &cppClass)
DynamicCStructHdl (const PVR_TIMER_TYPE *cStructure)
DynamicCStructHdl (PVR_TIMER_TYPE *cStructure)
const DynamicCStructHdl & operator= (const DynamicCStructHdl &right)
const DynamicCStructHdl & operator= (const PVR_TIMER_TYPE &right)
virtual ~DynamicCStructHdl ()
operator PVR_TIMER_TYPE * ()
operator const PVR_TIMER_TYPE * () const
const PVR_TIMER_TYPE * GetCStructure () const
PVR_TIMER_TYPE * release ()
Static Public Member Functions
static void AllocResources (const PVR_TIMER_TYPE *source, PVR_TIMER_TYPE *target)
static void FreeResources (PVR_TIMER_TYPE *target)
Private Member Functions
PVRTimerType (const PVR_TIMER_TYPE *type)
PVRTimerType (PVR_TIMER_TYPE *type)
Friends
class CInstancePVRClient
Additional Inherited Members
Protected Attributes inherited from kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >
PVR_TIMER_TYPE * m_cStructure
Constructor & Destructor Documentation
PVRTimerType() [1/2]
kodi::addon::PVRTimerType::PVRTimerType (const PVR_TIMER_TYPE * type) inline private
PVRTimerType() [2/2]
kodi::addon::PVRTimerType::PVRTimerType (PVR_TIMER_TYPE * type) inline private
Member Function Documentation
AllocResources()
static void kodi::addon::PVRTimerType::AllocResources (const PVR_TIMER_TYPE * source, PVR_TIMER_TYPE * target) inline static
References kodi::addon::PVRSettingDefinition::AllocAndCopyData(), kodi::addon::PVRTypeIntValue::AllocAndCopyData(), kodi::addon::AllocAndCopyString(), PVR_TIMER_TYPE::customSettingDefs, PVR_TIMER_TYPE::iCustomSettingDefsSize, PVR_TIMER_TYPE::iLifetimesSize, PVR_TIMER_TYPE::iMaxRecordingsSize, PVR_TIMER_TYPE::iPreventDuplicateEpisodesSize, PVR_TIMER_TYPE::iPrioritiesSize, PVR_TIMER_TYPE::iRecordingGroupSize, PVR_TIMER_TYPE::lifetimes, PVR_TIMER_TYPE::maxRecordings, PVR_TIMER_TYPE::preventDuplicateEpisodes, PVR_TIMER_TYPE::priorities, PVR_TIMER_TYPE::recordingGroup, and PVR_TIMER_TYPE::strDescription.
FreeResources()
static void kodi::addon::PVRTimerType::FreeResources (PVR_TIMER_TYPE * target) inline static
References PVR_TIMER_TYPE::customSettingDefs, kodi::addon::PVRTypeIntValue::FreeResources(), kodi::addon::PVRSettingDefinition::FreeResources(), kodi::addon::FreeString(), PVR_TIMER_TYPE::iCustomSettingDefsSize, PVR_TIMER_TYPE::iLifetimesSize, PVR_TIMER_TYPE::iMaxRecordingsSize, PVR_TIMER_TYPE::iPreventDuplicateEpisodesSize, PVR_TIMER_TYPE::iPrioritiesSize, PVR_TIMER_TYPE::iRecordingGroupSize, PVR_TIMER_TYPE::lifetimes, PVR_TIMER_TYPE::maxRecordings, PVR_TIMER_TYPE::preventDuplicateEpisodes, PVR_TIMER_TYPE::priorities, PVR_TIMER_TYPE::recordingGroup, and PVR_TIMER_TYPE::strDescription.
Friends And Related Symbol Documentation
CInstancePVRClient
friend class CInstancePVRClient friend
The documentation for this class was generated from the following file:
Timers.h