Kodi Documentation: KODI::WINDOWING::X11::CWinEventsX11 Class Reference
KODI::WINDOWING::X11::CWinEventsX11 Class Reference
#include <WinEventsX11.h>
Public Member Functions
CWinEventsX11 (CWinSystemX11 &winSystem)
~CWinEventsX11 () override
bool MessagePump () override
bool Init (Display *dpy, Window win)
void Quit ()
bool HasStructureChanged ()
void PendingResize (int width, int height)
void SetXRRFailSafeTimer (std::chrono::milliseconds duration)
Public Member Functions inherited from IWinEvents
virtual ~IWinEvents ()=default
Protected Member Functions
XBMCKey LookupXbmcKeySym (KeySym keysym)
bool ProcessKey (XBMC_Event &event)
Protected Attributes
Display * m_display = nullptr
Window m_window = 0
Atom m_wmDeleteMessage
char * m_keybuf = nullptr
size_t m_keybuf_len = 0
XIM m_xim = nullptr
XIC m_xic = nullptr
std::map< uint32_t, uint32_t > m_symLookupTable
int m_keymodState
bool m_structureChanged
int m_RREventBase
XbmcThreads::EndTime m_xrrFailSafeTimer
bool m_xrrEventPending
CWinSystemX11 & m_winSystem
Constructor & Destructor Documentation
CWinEventsX11()
CWinEventsX11::CWinEventsX11 (CWinSystemX11 & winSystem)
~CWinEventsX11()
CWinEventsX11::~CWinEventsX11 () override
References Quit().
Member Function Documentation
HasStructureChanged()
bool CWinEventsX11::HasStructureChanged ()
References m_display, and m_structureChanged.
Referenced by KODI::WINDOWING::X11::CWinSystemX11::SetWindow().
Init()
bool CWinEventsX11::Init (Display * dpy, Window win)
References CLog::Log(), LOGWARNING, m_display, m_keybuf, m_keybuf_len, m_keymodState, m_RREventBase, m_structureChanged, m_symLookupTable, m_window, m_wmDeleteMessage, m_xic, m_xim, m_xrrEventPending, and SymMappingsX11.
Referenced by KODI::WINDOWING::X11::CWinSystemX11::SetWindow().
LookupXbmcKeySym()
XBMCKey CWinEventsX11::LookupXbmcKeySym (KeySym keysym) protected
References m_symLookupTable.
Referenced by MessagePump().
MessagePump()
bool CWinEventsX11::MessagePump () override virtual
Implements IWinEvents.
References XBMC_MouseButtonEvent::button, XBMC_Event::button, data(), IAE::DeviceChange(), g_application, g_charsetConverter, CServiceBroker::GetActiveAE(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetAppPort(), CServiceBroker::GetGUI(), CServiceBroker::GetInputManager(), CGUIComponent::GetWindowManager(), XBMC_ResizeEvent::h, XBMC_Event::key, XBMC_KeyboardEvent::keysym, CLog::Log(), LOGERROR, LookupXbmcKeySym(), m_display, m_keybuf, m_keybuf_len, m_keymodState, m_RREventBase, m_structureChanged, m_window, m_winSystem, m_wmDeleteMessage, m_xic, m_xrrEventPending, m_xrrFailSafeTimer, CGUIWindowManager::MarkDirty(), XBMC_Event::motion, KODI::WINDOWING::X11::CWinSystemX11::NotifyAppFocusChange(), KODI::WINDOWING::X11::CWinSystemX11::NotifyXRREvent(), ProcessKey(), XBMC_Event::resize, XBMC_keysym::scancode, CInputManager::SetMouseActive(), XBMC_keysym::sym, TMSG_QUIT, XBMC_Event::type, XBMC_keysym::unicode, XBMC_ResizeEvent::w, XBMC_MouseMotionEvent::x, XBMC_MouseButtonEvent::x, XBMC_KEYDOWN, XBMC_KEYUP, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, XBMC_MOUSEMOTION, XBMC_VIDEORESIZE, XBMCK_UNKNOWN, XBMC_MouseMotionEvent::y, and XBMC_MouseButtonEvent::y.
PendingResize()
void KODI::WINDOWING::X11::CWinEventsX11::PendingResize (int width, int height)
ProcessKey()
bool CWinEventsX11::ProcessKey (XBMC_Event & event) protected
References CServiceBroker::GetAppPort(), XBMC_Event::key, XBMC_KeyboardEvent::keysym, m_keymodState, XBMC_keysym::sym, XBMC_Event::type, XBMC_KEYDOWN, XBMC_KEYUP, XBMCK_LALT, XBMCK_LCTRL, XBMCK_LMETA, XBMCK_LSHIFT, XBMCK_MODE, XBMCK_RALT, XBMCK_RCTRL, XBMCK_RMETA, XBMCK_RSHIFT, XBMCKMOD_LALT, XBMCKMOD_LCTRL, XBMCKMOD_LMETA, XBMCKMOD_LSHIFT, XBMCKMOD_MODE, XBMCKMOD_RCTRL, XBMCKMOD_RMETA, and XBMCKMOD_RSHIFT.
Referenced by MessagePump().
Quit()
void CWinEventsX11::Quit ()
References m_display, m_keybuf, m_symLookupTable, m_xic, and m_xim.
Referenced by KODI::WINDOWING::X11::CWinSystemX11::DestroyWindow(), and ~CWinEventsX11().
SetXRRFailSafeTimer()
void CWinEventsX11::SetXRRFailSafeTimer (std::chrono::milliseconds duration)
References m_display, m_xrrEventPending, and m_xrrFailSafeTimer.
Referenced by KODI::WINDOWING::X11::CWinSystemX11::OnLostDevice().
Member Data Documentation
m_display
Display* KODI::WINDOWING::X11::CWinEventsX11::m_display = nullptr protected
Referenced by HasStructureChanged(), Init(), MessagePump(), Quit(), and SetXRRFailSafeTimer().
m_keybuf
char* KODI::WINDOWING::X11::CWinEventsX11::m_keybuf = nullptr protected
Referenced by Init(), MessagePump(), and Quit().
m_keybuf_len
size_t KODI::WINDOWING::X11::CWinEventsX11::m_keybuf_len = 0 protected
Referenced by Init(), and MessagePump().
m_keymodState
int KODI::WINDOWING::X11::CWinEventsX11::m_keymodState protected
Referenced by Init(), MessagePump(), and ProcessKey().
m_RREventBase
int KODI::WINDOWING::X11::CWinEventsX11::m_RREventBase protected
Referenced by Init(), and MessagePump().
m_structureChanged
bool KODI::WINDOWING::X11::CWinEventsX11::m_structureChanged protected
Referenced by HasStructureChanged(), Init(), and MessagePump().
m_symLookupTable
std::map<uint32_t,uint32_t> KODI::WINDOWING::X11::CWinEventsX11::m_symLookupTable protected
Referenced by Init(), LookupXbmcKeySym(), and Quit().
m_window
Window KODI::WINDOWING::X11::CWinEventsX11::m_window = 0 protected
Referenced by Init(), and MessagePump().
m_winSystem
CWinSystemX11& KODI::WINDOWING::X11::CWinEventsX11::m_winSystem protected
Referenced by MessagePump().
m_wmDeleteMessage
Atom KODI::WINDOWING::X11::CWinEventsX11::m_wmDeleteMessage protected
Referenced by Init(), and MessagePump().
m_xic
XIC KODI::WINDOWING::X11::CWinEventsX11::m_xic = nullptr protected
Referenced by Init(), MessagePump(), and Quit().
m_xim
XIM KODI::WINDOWING::X11::CWinEventsX11::m_xim = nullptr protected
Referenced by Init(), and Quit().
m_xrrEventPending
bool KODI::WINDOWING::X11::CWinEventsX11::m_xrrEventPending protected
Referenced by Init(), MessagePump(), and SetXRRFailSafeTimer().
m_xrrFailSafeTimer
XbmcThreads::EndTime KODI::WINDOWING::X11::CWinEventsX11::m_xrrFailSafeTimer protected
Referenced by MessagePump(), and SetXRRFailSafeTimer().
The documentation for this class was generated from the following files:
WinEventsX11.h
WinEventsX11.cpp