Kodi Documentation: KODI::RETRO::CGUIRenderTargetFactory Class Reference
KODI::RETRO::CGUIRenderTargetFactory Class Reference
#include <GUIRenderTargetFactory.h>
Public Member Functions
CGUIRenderTargetFactory (IRenderManager *renderManager)
CGUIRenderTarget * CreateRenderFullScreen (CGameWindowFullScreen &window)
Create a render target for the fullscreen window.
CGUIRenderTarget * CreateRenderControl (CGUIGameControl &gameControl)
Create a render target for a game control.
Private Attributes
IRenderManager * m_renderManager
Constructor & Destructor Documentation
CGUIRenderTargetFactory()
CGUIRenderTargetFactory::CGUIRenderTargetFactory (IRenderManager * renderManager)
Member Function Documentation
CreateRenderControl()
CGUIRenderTarget * CGUIRenderTargetFactory::CreateRenderControl (CGUIGameControl & gameControl)
Create a render target for a game control.
References m_renderManager.
Referenced by KODI::RETRO::CGUIGameRenderManager::CreateRenderTarget(), and KODI::RETRO::CGUIGameRenderManager::RegisterControl().
CreateRenderFullScreen()
CGUIRenderTarget * CGUIRenderTargetFactory::CreateRenderFullScreen (CGameWindowFullScreen & window)
Create a render target for the fullscreen window.
References m_renderManager.
Referenced by KODI::RETRO::CGUIGameRenderManager::CreateRenderTarget(), and KODI::RETRO::CGUIGameRenderManager::RegisterWindow().
Member Data Documentation
m_renderManager
IRenderManager* KODI::RETRO::CGUIRenderTargetFactory::m_renderManager private
Referenced by CreateRenderControl(), and CreateRenderFullScreen().
The documentation for this class was generated from the following files:
GUIRenderTargetFactory.h
GUIRenderTargetFactory.cpp