Kodi Documentation: PVR::CPVRTimersPath Class Reference
PVR::CPVRTimersPath Class Reference
#include <PVRTimersPath.h>
Public Member Functions
CPVRTimersPath (const std::string &strPath)
CPVRTimersPath (const std::string &strPath, int iClientId, int iParentId)
CPVRTimersPath (bool bRadio, bool bTimerRules)
bool IsValid () const
const std::string & GetPath () const
bool IsTimersRoot () const
bool IsTimerRule () const
bool IsRadio () const
bool IsRules () const
int GetClientId () const
int GetParentId () const
Static Public Attributes
static const std::string PATH_ADDTIMER = "pvr://timers/addtimer/"
static const std::string PATH_NEW = "pvr://timers/new/"
static const std::string PATH_TV_TIMERS = "pvr://timers/tv/timers/"
static const std::string PATH_TV_TIMER_RULES = "pvr://timers/tv/rules/"
static const std::string PATH_RADIO_TIMERS = "pvr://timers/radio/timers/"
static const std::string PATH_RADIO_TIMER_RULES = "pvr://timers/radio/rules/"
Private Member Functions
bool Init (const std::string &strPath)
Private Attributes
std::string m_path
bool m_bValid = false
bool m_bRoot = false
bool m_bRadio = false
bool m_bTimerRules = false
int m_iClientId = PVR_CLIENT_INVALID_UID
int m_iParentId = 0
Constructor & Destructor Documentation
CPVRTimersPath() [1/3]
CPVRTimersPath::CPVRTimersPath (const std::string & strPath) explicit
References Init().
CPVRTimersPath() [2/3]
CPVRTimersPath::CPVRTimersPath (const std::string & strPath, int iClientId, int iParentId)
References Init(), m_bRadio, m_bRoot, m_bTimerRules, m_iClientId, m_iParentId, and m_path.
CPVRTimersPath() [3/3]
CPVRTimersPath::CPVRTimersPath (bool bRadio, bool bTimerRules)
Member Function Documentation
GetClientId()
int PVR::CPVRTimersPath::GetClientId () const inline
References m_iClientId.
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersSubDirectory().
GetParentId()
int PVR::CPVRTimersPath::GetParentId () const inline
References m_iParentId.
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersSubDirectory().
GetPath()
const std::string & PVR::CPVRTimersPath::GetPath () const inline
References m_path.
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersRootDirectory(), and anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersSubDirectory().
Init()
bool CPVRTimersPath::Init (const std::string & strPath) private
References m_bRadio, m_bRoot, m_bTimerRules, m_bValid, m_iClientId, m_iParentId, m_path, PVR::PVR_CLIENT_INVALID_UID, URIUtils::RemoveSlashAtEnd(), and URIUtils::SplitPath().
Referenced by CPVRTimersPath(), and CPVRTimersPath().
IsRadio()
bool PVR::CPVRTimersPath::IsRadio () const inline
References m_bRadio.
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersRootDirectory(), and anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersSubDirectory().
IsRules()
bool PVR::CPVRTimersPath::IsRules () const inline
References m_bTimerRules.
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersRootDirectory().
IsTimerRule()
bool PVR::CPVRTimersPath::IsTimerRule () const inline
References IsTimersRoot().
Referenced by PVR::CPVRGUIDirectory::GetTimersDirectory(), PVR::CGUIWindowPVRTimersBase::OnAction(), and PVR::CGUIWindowPVRTimersBase::Update().
IsTimersRoot()
bool PVR::CPVRTimersPath::IsTimersRoot () const inline
References m_bRoot.
Referenced by PVR::CPVRGUIDirectory::GetTimersDirectory(), PVR::CGUIViewStateWindowPVRTimers::HideParentDirItems(), IsTimerRule(), and PVR::CGUIWindowPVRTimersBase::OnPrepareFileItems().
IsValid()
bool PVR::CPVRTimersPath::IsValid () const inline
References m_bValid.
Referenced by PVR::CPVRGUIDirectory::GetTimersDirectory(), PVR::CGUIWindowPVRTimersBase::OnAction(), PVR::CGUIWindowPVRTimersBase::OnPrepareFileItems(), and PVR::CGUIWindowPVRTimersBase::Update().
Member Data Documentation
m_bRadio
bool PVR::CPVRTimersPath::m_bRadio = false private
Referenced by CPVRTimersPath(), Init(), and IsRadio().
m_bRoot
bool PVR::CPVRTimersPath::m_bRoot = false private
Referenced by CPVRTimersPath(), Init(), and IsTimersRoot().
m_bTimerRules
bool PVR::CPVRTimersPath::m_bTimerRules = false private
Referenced by CPVRTimersPath(), Init(), and IsRules().
m_bValid
bool PVR::CPVRTimersPath::m_bValid = false private
Referenced by Init(), and IsValid().
m_iClientId
int PVR::CPVRTimersPath::m_iClientId = PVR_CLIENT_INVALID_UID private
Referenced by CPVRTimersPath(), GetClientId(), and Init().
m_iParentId
int PVR::CPVRTimersPath::m_iParentId = 0 private
Referenced by CPVRTimersPath(), GetParentId(), and Init().
m_path
std::string PVR::CPVRTimersPath::m_path private
Referenced by CPVRTimersPath(), GetPath(), and Init().
PATH_ADDTIMER
const std::string CPVRTimersPath::PATH_ADDTIMER = "pvr://timers/addtimer/" static
Referenced by PVR::CGUIWindowPVRTimersBase::ActionShowTimer(), PVR::CPVRTimerInfoTag::GetStatus(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible(), and PVR::CGUIWindowPVRTimersBase::OnPrepareFileItems().
PATH_NEW
const std::string CPVRTimersPath::PATH_NEW = "pvr://timers/new/" static
Referenced by PVR::CPVRTimerInfoTag::CreateFromDate(), and PVR::CPVRTimerInfoTag::CreateFromEpg().
PATH_RADIO_TIMER_RULES
const std::string CPVRTimersPath::PATH_RADIO_TIMER_RULES = "pvr://timers/radio/rules/" static
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), and PVR::CGUIWindowPVRRadioTimerRules::GetRootPath().
PATH_RADIO_TIMERS
const std::string CPVRTimersPath::PATH_RADIO_TIMERS = "pvr://timers/radio/timers/" static
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), and PVR::CGUIWindowPVRRadioTimers::GetRootPath().
PATH_TV_TIMER_RULES
const std::string CPVRTimersPath::PATH_TV_TIMER_RULES = "pvr://timers/tv/rules/" static
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), and PVR::CGUIWindowPVRTVTimerRules::GetRootPath().
PATH_TV_TIMERS
const std::string CPVRTimersPath::PATH_TV_TIMERS = "pvr://timers/tv/timers/" static
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), and PVR::CGUIWindowPVRTVTimers::GetRootPath().
The documentation for this class was generated from the following files:
PVRTimersPath.h
PVRTimersPath.cpp