Kodi Documentation: XFILE::CSMBDirectory Class Reference
XFILE::CSMBDirectory Class Reference
#include <SMBDirectory.h>
Public Member Functions
CSMBDirectory (void)
~CSMBDirectory (void) override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
DIR_CACHE_TYPE GetCacheType (const CURL &url) const override
How this directory should be cached.
bool Create (const CURL &url) override
Create the directory.
bool Exists (const CURL &url) override
Check for directory existence.
bool Remove (const CURL &url) override
Removes the directory.
int Open (const CURL &url)
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual bool AllowAll () const
Whether to allow all files/folders to be listed.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Private Member Functions
int OpenDir (const CURL &url, std::string &strAuth)
Checks authentication against SAMBA share and prompts for username and password if needed.
Additional Inherited Members
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CSMBDirectory()
CSMBDirectory::CSMBDirectory (void)
References CSMB::AddActiveConnection(), and smb.
~CSMBDirectory()
CSMBDirectory::~CSMBDirectory (void) override
References CSMB::AddIdleConnection(), and smb.
Member Function Documentation
Create()
bool CSMBDirectory::Create (const CURL & url) override virtual
Create the directory.
Parameters
url Directory to create.
Returns
Returns true, if directory is created or if it already exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
References CPasswordManager::AuthenticateURL(), CPasswordManager::GetInstance(), CSMB::GetResolvedUrl(), CSMB::Init(), CLog::Log(), LOGERROR, smb, success, and CSMB::URLEncode().
Exists()
bool CSMBDirectory::Exists (const CURL & url) override virtual
Check for directory existence.
Parameters
url Directory to check.
Returns
Returns true, if directory exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
References CPasswordManager::AuthenticateURL(), CPasswordManager::GetInstance(), CSMB::GetResolvedUrl(), CSMB::Init(), S_ISDIR, smb, and CSMB::URLEncode().
GetCacheType()
DIR_CACHE_TYPE XFILE::CSMBDirectory::GetCacheType (const CURL & url) const inline override virtual
How this directory should be cached.
Parameters
url Directory at hand.
Returns
Returns the cache type.
Reimplemented from XFILE::IDirectory.
References XFILE::DIR_CACHE_ONCE.
GetDirectory()
bool CSMBDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References CFileItemList::Add(), URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), CFileItemList::ClearItems(), XFILE::DIR_FLAG_NO_FILE_INFO, KODI::TIME::FileTimeToLocalFileTime(), CURL::Get(), WSDiscovery::CWSDiscoveryPosix::GetServerList(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWSDiscovery(), CSMB::Init(), int64_t(), CSMB::IsSmbValid(), CLog::Log(), LOGERROR, XFILE::IDirectory::m_flags, CachedDirEntry::name, OpenDir(), S_ISDIR, CURL::SetFileName(), CURL::SetHostName(), CSettings::SETTING_SERVICES_WSDISCOVERY, smb, KODI::TIME::TimeTToFileTime(), CachedDirEntry::type, CSMB::URLEncode(), and value.
Open()
int CSMBDirectory::Open (const CURL & url)
References CSMB::Init(), OpenDir(), and smb.
OpenDir()
int CSMBDirectory::OpenDir (const CURL & url, std::string & strAuth) private
Checks authentication against SAMBA share and prompts for username and password if needed.
Parameters
strAuth The SMB style path
Returns
SMB file descriptor
References CPasswordManager::AuthenticateURL(), XFILE::DIR_FLAG_ALLOW_PROMPT, g_localizeStrings, CLocalizeStrings::Get(), CPasswordManager::GetInstance(), CSMB::GetResolvedUrl(), CSMB::IsSmbValid(), CLog::Log(), LOGDEBUG, LOGERROR, LOGSAMBA, XFILE::IDirectory::m_flags, XFILE::IDirectory::RequireAuthentication(), XFILE::IDirectory::SetErrorDialog(), smb, and CSMB::URLEncode().
Referenced by GetDirectory(), and Open().
Remove()
bool CSMBDirectory::Remove (const CURL & url) override virtual
Removes the directory.
Parameters
url Directory to remove.
Returns
Returns false if not successful
Reimplemented from XFILE::IDirectory.
References CPasswordManager::AuthenticateURL(), CPasswordManager::GetInstance(), CSMB::GetResolvedUrl(), CSMB::Init(), CLog::Log(), LOGERROR, smb, and CSMB::URLEncode().
The documentation for this class was generated from the following files:
SMBDirectory.h
SMBDirectory.cpp