Kodi Documentation: class PVRIntSettingDefinition
class PVRIntSettingDefinition
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General
PVR add-on integer setting definition
Representation of an integer setting definition.
Classes
class kodi::addon::PVRIntSettingDefinition
Functions
kodi::addon::PVRIntSettingDefinition::PVRIntSettingDefinition (const std::vector< PVRTypeIntValue > &settingValues, int defaultValue, int minValue, int step, int maxValue)
Class constructor with integrated values.
void kodi::addon::PVRIntSettingDefinition::SetValues (const std::vector< PVRTypeIntValue > &values, int defaultValue=-1)
optional
value definitions.
std::vector< PVRTypeIntValue > kodi::addon::PVRIntSettingDefinition::GetValues () const
To get with SetValues changed values.
void kodi::addon::PVRIntSettingDefinition::SetDefaultValue (int defaultValue)
optional
The default value for this setting.
int kodi::addon::PVRIntSettingDefinition::GetDefaultValue () const
To get with SetDefaultValue changed values.
void kodi::addon::PVRIntSettingDefinition::SetMinValue (int minValue)
optional
The minimum value for this setting.
int kodi::addon::PVRIntSettingDefinition::GetMinValue () const
To get with SetMinValue changed values.
void kodi::addon::PVRIntSettingDefinition::SetStep (int step)
optional
The amount for increasing the values for this setting from min to max.
int kodi::addon::PVRIntSettingDefinition::GetStep () const
To get with SetStep changed values.
void kodi::addon::PVRIntSettingDefinition::SetMaxValue (int maxValue)
optional
The maximum value for this setting.
int kodi::addon::PVRIntSettingDefinition::GetMaxValue () const
To get with SetMaxValue changed values.
Detailed Description
PVR add-on integer setting definition
Representation of an integer setting definition.
Function Documentation
GetDefaultValue()
int kodi::addon::PVRIntSettingDefinition::GetDefaultValue () const inline
To get with SetDefaultValue changed values.
References PVR_INT_SETTING_DEFINITION::iDefaultValue, and kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >::m_cStructure.
GetMaxValue()
int kodi::addon::PVRIntSettingDefinition::GetMaxValue () const inline
To get with SetMaxValue changed values.
References PVR_INT_SETTING_DEFINITION::iMaxValue, and kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >::m_cStructure.
GetMinValue()
int kodi::addon::PVRIntSettingDefinition::GetMinValue () const inline
To get with SetMinValue changed values.
References PVR_INT_SETTING_DEFINITION::iMinValue, and kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >::m_cStructure.
GetStep()
int kodi::addon::PVRIntSettingDefinition::GetStep () const inline
To get with SetStep changed values.
References PVR_INT_SETTING_DEFINITION::iStep, and kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >::m_cStructure.
GetValues()
std::vector< PVRTypeIntValue > kodi::addon::PVRIntSettingDefinition::GetValues () const inline
To get with SetValues changed values.
References PVR_ATTRIBUTE_INT_VALUE::iValue, PVR_INT_SETTING_DEFINITION::iValuesSize, kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >::m_cStructure, PVR_ATTRIBUTE_INT_VALUE::strDescription, and PVR_INT_SETTING_DEFINITION::values.
PVRIntSettingDefinition()
kodi::addon::PVRIntSettingDefinition::PVRIntSettingDefinition (const std::vector< PVRTypeIntValue > & settingValues, int defaultValue, int minValue, int step, int maxValue) inline
Class constructor with integrated values.
Parameters
[in] settingValues possible setting values
[in] defaultValue default setting value
[in] minValue minimim setting value
[in] step amount to change values from min to max
[in] maxValue maximum setting value
References kodi::addon::PVRIntSettingDefinition::SetDefaultValue(), kodi::addon::PVRIntSettingDefinition::SetMaxValue(), kodi::addon::PVRIntSettingDefinition::SetMinValue(), kodi::addon::PVRIntSettingDefinition::SetStep(), and kodi::addon::PVRIntSettingDefinition::SetValues().
SetDefaultValue()
void kodi::addon::PVRIntSettingDefinition::SetDefaultValue (int defaultValue) inline
optional
The default value for this setting.
References PVR_INT_SETTING_DEFINITION::iDefaultValue, and kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >::m_cStructure.
Referenced by kodi::addon::PVRSettingDefinition::GetIntDefinition(), and kodi::addon::PVRIntSettingDefinition::PVRIntSettingDefinition().
SetMaxValue()
void kodi::addon::PVRIntSettingDefinition::SetMaxValue (int maxValue) inline
optional
The maximum value for this setting.
References PVR_INT_SETTING_DEFINITION::iMaxValue, and kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >::m_cStructure.
Referenced by kodi::addon::PVRSettingDefinition::GetIntDefinition(), and kodi::addon::PVRIntSettingDefinition::PVRIntSettingDefinition().
SetMinValue()
void kodi::addon::PVRIntSettingDefinition::SetMinValue (int minValue) inline
optional
The minimum value for this setting.
References PVR_INT_SETTING_DEFINITION::iMinValue, and kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >::m_cStructure.
Referenced by kodi::addon::PVRSettingDefinition::GetIntDefinition(), and kodi::addon::PVRIntSettingDefinition::PVRIntSettingDefinition().
SetStep()
void kodi::addon::PVRIntSettingDefinition::SetStep (int step) inline
optional
The amount for increasing the values for this setting from min to max.
References PVR_INT_SETTING_DEFINITION::iStep, and kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >::m_cStructure.
Referenced by kodi::addon::PVRSettingDefinition::GetIntDefinition(), and kodi::addon::PVRIntSettingDefinition::PVRIntSettingDefinition().
SetValues()
void kodi::addon::PVRIntSettingDefinition::SetValues (const std::vector< PVRTypeIntValue > & values, int defaultValue = -1) inline
optional
value definitions.
Array containing the possible settings values. If left blank, any int value is accepted.
Parameters
[in] values List of possible values
[in] defaultValue [opt] The default value in list, can also be set by SetDefaultValue()
The following table contains values that can be set with class PVRTypeIntValue :
Name Type Set call Get call
Value int SetValue GetValue
Description std::string SetDescription GetDescription
Remarks
Further can there be used his class constructor to set values.
References PVR_INT_SETTING_DEFINITION::iDefaultValue, PVR_INT_SETTING_DEFINITION::iValuesSize, kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >::m_cStructure, kodi::addon::PVRTypeIntValue::ReallocAndCopyData(), PVR_INT_SETTING_DEFINITION::values, and values.
Referenced by kodi::addon::PVRSettingDefinition::GetIntDefinition(), and kodi::addon::PVRIntSettingDefinition::PVRIntSettingDefinition().