Kodi Documentation: UPNP::ResourcePrioritySort Struct Reference
UPNP::ResourcePrioritySort Struct Reference
Public Member Functions
ResourcePrioritySort (const PLT_MediaObject *entry)
int GetPriority (const PLT_MediaItemResource &res) const
int operator() (const PLT_MediaItemResource &lh, const PLT_MediaItemResource &rh) const
Public Attributes
NPT_String m_content
Constructor & Destructor Documentation
ResourcePrioritySort()
UPNP::ResourcePrioritySort::ResourcePrioritySort (const PLT_MediaObject * entry) inline explicit
References m_content.
Member Function Documentation
GetPriority()
int UPNP::ResourcePrioritySort::GetPriority (const PLT_MediaItemResource & res) const inline
References URIUtils::IsHostOnLAN(), m_content, and ONLY_LOCAL_SUBNET.
Referenced by operator()().
operator()()
int UPNP::ResourcePrioritySort::operator() (const PLT_MediaItemResource & lh, const PLT_MediaItemResource & rh) const inline
References GetPriority().
Member Data Documentation
m_content
NPT_String UPNP::ResourcePrioritySort::m_content
Referenced by GetPriority(), and ResourcePrioritySort().
The documentation for this struct was generated from the following file:
UPnPInternal.cpp