Kodi Documentation: KODI::TIME::anonymous_namespace{XTimeUtils.cpp} Namespace Reference
KODI::TIME::anonymous_namespace{XTimeUtils.cpp} Namespace Reference
Functions
void SystemTimeToKodiTime (const SYSTEMTIME &sst, SystemTime &st)
void KodiTimeToSystemTime (const SystemTime &st, SYSTEMTIME &sst)
Function Documentation
KodiTimeToSystemTime()
void KODI::TIME::anonymous_namespace{XTimeUtils.cpp}::KodiTimeToSystemTime (const SystemTime & st, SYSTEMTIME & sst)
References KODI::TIME::SystemTime::day, KODI::TIME::SystemTime::dayOfWeek, KODI::TIME::SystemTime::hour, KodiTimeToSystemTime(), KODI::TIME::SystemTime::milliseconds, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, KODI::TIME::SystemTime::second, and KODI::TIME::SystemTime::year.
Referenced by KodiTimeToSystemTime().
SystemTimeToKodiTime()
void KODI::TIME::anonymous_namespace{XTimeUtils.cpp}::SystemTimeToKodiTime (const SYSTEMTIME & sst, SystemTime & st)
References KODI::TIME::SystemTime::day, KODI::TIME::SystemTime::dayOfWeek, KODI::TIME::SystemTime::hour, KODI::TIME::SystemTime::milliseconds, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, KODI::TIME::SystemTime::second, SystemTimeToKodiTime(), and KODI::TIME::SystemTime::year.
Referenced by SystemTimeToKodiTime().