Kodi Documentation: XFILE::CFileStreamBuffer Class Reference
XFILE::CFileStreamBuffer Class Reference
#include <File.h>
Public Member Functions
~CFileStreamBuffer () override
CFileStreamBuffer (int backsize=0)
void Attach (IFile *file)
void Detach ()
Private Member Functions
int_type underflow () override
std::streamsize showmanyc () override
pos_type seekoff (off_type, std::ios_base::seekdir, std::ios_base::openmode=std::ios_base::in|std::ios_base::out) override
pos_type seekpos (pos_type, std::ios_base::openmode=std::ios_base::in|std::ios_base::out) override
Private Attributes
IFile * m_file
char * m_buffer
int m_backsize
int m_frontsize = 0
Constructor & Destructor Documentation
~CFileStreamBuffer()
CFileStreamBuffer::~CFileStreamBuffer () override
References Detach().
CFileStreamBuffer()
CFileStreamBuffer::CFileStreamBuffer (int backsize = 0) explicit
Member Function Documentation
Attach()
void CFileStreamBuffer::Attach (IFile * file)
References XFILE::CFile::DetermineChunkSize(), XFILE::IFile::GetChunkSize(), m_backsize, m_buffer, m_file, and m_frontsize.
Referenced by XFILE::CFileStream::Open().
Detach()
void CFileStreamBuffer::Detach ()
References m_buffer.
Referenced by XFILE::CFileStream::Close(), and ~CFileStreamBuffer().
seekoff()
CFileStreamBuffer::pos_type CFileStreamBuffer::seekoff (off_type offset, std::ios_base::seekdir way, std::ios_base::openmode mode = std::ios_base::in | std::ios_base::out) override private
References XFILE::IFile::GetLength(), XFILE::IFile::GetPosition(), int64_t(), m_file, and XFILE::IFile::Seek().
Referenced by seekpos().
seekpos()
CFileStreamBuffer::pos_type CFileStreamBuffer::seekpos (pos_type pos, std::ios_base::openmode mode = std::ios_base::in | std::ios_base::out) override private
References seekoff().
showmanyc()
std::streamsize CFileStreamBuffer::showmanyc () override private
References underflow().
underflow()
CFileStreamBuffer::int_type CFileStreamBuffer::underflow () override private
References LOGWARNING, m_backsize, m_buffer, m_file, m_frontsize, and XFILE::IFile::Read().
Referenced by showmanyc().
Member Data Documentation
m_backsize
int XFILE::CFileStreamBuffer::m_backsize private
Referenced by Attach(), and underflow().
m_buffer
char* XFILE::CFileStreamBuffer::m_buffer private
Referenced by Attach(), Detach(), and underflow().
m_file
IFile* XFILE::CFileStreamBuffer::m_file private
Referenced by Attach(), seekoff(), and underflow().
m_frontsize
int XFILE::CFileStreamBuffer::m_frontsize = 0 private
Referenced by Attach(), and underflow().
The documentation for this class was generated from the following files:
filesystem/File.h
filesystem/File.cpp