Kodi Documentation: KODI::KEYMAP::CKeyHandler Class Reference
KODI::KEYMAP::CKeyHandler Class Reference
#include <KeyHandler.h>
Public Member Functions
CKeyHandler (const std::string &keyName, ACTION::IActionListener *actionHandler, const IKeymap *keymap, IKeymapHandler *keymapHandler)
~CKeyHandler () override=default
bool IsPressed () const override
Return true if the key is "pressed" (has a magnitude greater than 0.5)
bool OnDigitalMotion (bool bPressed, unsigned int holdTimeMs) override
A key mapped to a digital feature has been pressed or released.
bool OnAnalogMotion (float magnitude, unsigned int motionTimeMs) override
Callback for keys mapped to analog features.
Public Member Functions inherited from KODI::KEYMAP::IKeyHandler
virtual ~IKeyHandler ()=default
Private Member Functions
void Reset ()
CAction ProcessActions (std::vector< const KeymapAction * > actions, int windowId, float magnitude, unsigned int holdTimeMs)
Process actions to see if an action should be dispatched.
CAction ProcessRelease (std::vector< const KeymapAction * > actions, int windowId)
Process actions after release event to see if an action should be dispatched.
CAction ProcessAction (const KeymapAction &action, int windowId, float magnitude, unsigned int holdTimeMs)
Process an action to see if it should be dispatched.
bool SendRepeatAction (unsigned int holdTimeMs)
Static Private Member Functions
static bool IsPressed (float magnitude)
Private Attributes
const std::string m_keyName
ACTION::IActionListener *const m_actionHandler
const IKeymap *const m_keymap
IKeymapHandler *const m_keymapHandler
bool m_bHeld
float m_magnitude
unsigned int m_holdStartTimeMs
unsigned int m_lastHoldTimeMs
bool m_bActionSent
unsigned int m_lastActionMs
int m_activeWindowId = -1
CAction m_lastAction
Constructor & Destructor Documentation
CKeyHandler()
CKeyHandler::CKeyHandler (const std::string & keyName, ACTION::IActionListener * actionHandler, const IKeymap * keymap, IKeymapHandler * keymapHandler)
References m_actionHandler, m_keymap, m_keymapHandler, and Reset().
~CKeyHandler()
KODI::KEYMAP::CKeyHandler::~CKeyHandler () override default
Member Function Documentation
IsPressed() [1/2]
bool KODI::KEYMAP::CKeyHandler::IsPressed () const inline override virtual
Return true if the key is "pressed" (has a magnitude greater than 0.5)
Returns
True if the key is "pressed", false otherwise
Implements KODI::KEYMAP::IKeyHandler.
References m_bHeld.
Referenced by OnAnalogMotion(), ProcessAction(), and ProcessActions().
IsPressed() [2/2]
bool CKeyHandler::IsPressed (float magnitude) static private
References DIGITAL_ANALOG_THRESHOLD.
OnAnalogMotion()
bool CKeyHandler::OnAnalogMotion (float magnitude, unsigned int motionTimeMs) override virtual
Callback for keys mapped to analog features.
Parameters
magnitude The amount of the analog action
motionTimeMs The time since the magnitude was 0
Returns
True if the key is mapped to an action, false otherwise
Implements KODI::KEYMAP::IKeyHandler.
References ACTION_NONE, actions, CAction::ClearAmount(), KODI::KEYMAP::IKeymap::GetActions(), CAction::GetAmount(), CAction::GetID(), KODI::ACTION::CActionTranslator::IsAnalog(), IsPressed(), m_actionHandler, m_activeWindowId, m_bHeld, m_holdStartTimeMs, m_keymap, m_keyName, m_lastAction, m_lastHoldTimeMs, m_magnitude, KODI::ACTION::IActionListener::OnAction(), ProcessActions(), Reset(), and KODI::KEYMAP::KeymapActionGroup::windowId.
Referenced by OnDigitalMotion().
OnDigitalMotion()
bool CKeyHandler::OnDigitalMotion (bool bPressed, unsigned int holdTimeMs) override virtual
A key mapped to a digital feature has been pressed or released.
Parameters
bPressed true if the key's button/axis is activated, false if deactivated
holdTimeMs The held time in ms for pressed buttons, or 0 for released
Returns
True if the key is mapped to an action, false otherwise
Implements KODI::KEYMAP::IKeyHandler.
References OnAnalogMotion().
ProcessAction()
CAction CKeyHandler::ProcessAction (const KeymapAction & action, int windowId, float magnitude, unsigned int holdTimeMs) private
Process an action to see if it should be dispatched.
Parameters
action The action chosen to be dispatched
windowId The current window ID
magnitude The magnitude or distance of the feature being handled
holdTimeMs The time which the feature has been past the hold threshold
Returns
The action to dispatch, or action with ID ACTION_NONE if no action should be dispatched
References KODI::ACTION::CActionTranslator::IsAnalog(), IsPressed(), m_activeWindowId, m_bActionSent, m_keymapHandler, m_keyName, m_lastActionMs, KODI::KEYMAP::IKeymapHandler::OnPress(), and SendRepeatAction().
Referenced by ProcessActions(), and ProcessRelease().
ProcessActions()
CAction CKeyHandler::ProcessActions (std::vector< const KeymapAction * > actions, int windowId, float magnitude, unsigned int holdTimeMs) private
Process actions to see if an action should be dispatched.
Parameters
actions All actions from the keymap defined for the current window
windowId The current window ID
magnitude The magnitude or distance of the feature being handled
holdTimeMs The time which the feature has been past the hold threshold
Returns
The action to dispatch, or action with ID ACTION_NONE if no action should be dispatched
References actions, KODI::KEYMAP::KeymapAction::holdTimeMs, IsPressed(), m_bActionSent, m_bHeld, ProcessAction(), and ProcessRelease().
Referenced by OnAnalogMotion().
ProcessRelease()
CAction CKeyHandler::ProcessRelease (std::vector< const KeymapAction * > actions, int windowId) private
Process actions after release event to see if an action should be dispatched.
Parameters
actions All actions from the keymap defined for the current window
windowId The current window ID
Returns
The action to dispatch, or action with ID ACTION_NONE if no action should be dispatched
References actions, m_lastHoldTimeMs, and ProcessAction().
Referenced by ProcessActions().
Reset()
void CKeyHandler::Reset () private
References m_activeWindowId, m_bActionSent, m_bHeld, m_holdStartTimeMs, m_lastAction, m_lastActionMs, m_lastHoldTimeMs, and m_magnitude.
Referenced by CKeyHandler(), and OnAnalogMotion().
SendRepeatAction()
bool CKeyHandler::SendRepeatAction (unsigned int holdTimeMs) private
References KODI::KEYMAP::IKeymapHandler::GetLastPressed(), HOLD_TIMEOUT_MS, m_keymapHandler, m_keyName, m_lastActionMs, and REPEAT_TIMEOUT_MS.
Referenced by ProcessAction().
Member Data Documentation
m_actionHandler
ACTION::IActionListener* const KODI::KEYMAP::CKeyHandler::m_actionHandler private
Referenced by CKeyHandler(), and OnAnalogMotion().
m_activeWindowId
int KODI::KEYMAP::CKeyHandler::m_activeWindowId = -1 private
Referenced by OnAnalogMotion(), ProcessAction(), and Reset().
m_bActionSent
bool KODI::KEYMAP::CKeyHandler::m_bActionSent private
Referenced by ProcessAction(), ProcessActions(), and Reset().
m_bHeld
bool KODI::KEYMAP::CKeyHandler::m_bHeld private
Referenced by IsPressed(), OnAnalogMotion(), ProcessActions(), and Reset().
m_holdStartTimeMs
unsigned int KODI::KEYMAP::CKeyHandler::m_holdStartTimeMs private
Referenced by OnAnalogMotion(), and Reset().
m_keymap
const IKeymap* const KODI::KEYMAP::CKeyHandler::m_keymap private
Referenced by CKeyHandler(), and OnAnalogMotion().
m_keymapHandler
IKeymapHandler* const KODI::KEYMAP::CKeyHandler::m_keymapHandler private
Referenced by CKeyHandler(), ProcessAction(), and SendRepeatAction().
m_keyName
const std::string KODI::KEYMAP::CKeyHandler::m_keyName private
Referenced by OnAnalogMotion(), ProcessAction(), and SendRepeatAction().
m_lastAction
CAction KODI::KEYMAP::CKeyHandler::m_lastAction private
Referenced by OnAnalogMotion(), and Reset().
m_lastActionMs
unsigned int KODI::KEYMAP::CKeyHandler::m_lastActionMs private
Referenced by ProcessAction(), Reset(), and SendRepeatAction().
m_lastHoldTimeMs
unsigned int KODI::KEYMAP::CKeyHandler::m_lastHoldTimeMs private
Referenced by OnAnalogMotion(), ProcessRelease(), and Reset().
m_magnitude
float KODI::KEYMAP::CKeyHandler::m_magnitude private
Referenced by OnAnalogMotion(), and Reset().
The documentation for this class was generated from the following files:
KeyHandler.h
KeyHandler.cpp