Kodi Documentation: CVideoPlayer Class Reference
CVideoPlayer Class Reference
#include <VideoPlayer.h>
Classes
struct SContent
struct SDVDInfo
struct SSpeedState
Public Member Functions
CVideoPlayer (IPlayerCallback &callback)
~CVideoPlayer () override
bool OpenFile (const CFileItem &file, const CPlayerOptions &options) override
bool CloseFile (bool reopen=false) override
bool IsPlaying () const override
void Pause () override
bool HasVideo () const override
bool HasAudio () const override
bool HasRDS () const override
bool HasID3 () const override
bool IsPassthrough () const override
bool CanSeek () const override
void Seek (bool bPlus, bool bLargeStep, bool bChapterOverride) override
bool SeekScene (Direction seekDirection) override
void SeekPercentage (float iPercent) override
float GetCachePercentage () const override
void SetDynamicRangeCompression (long drc) override
bool CanPause () const override
void SetAVDelay (float fValue=0.0f) override
float GetAVDelay () override
bool IsInMenu () const override
MenuType GetSupportedMenuType () const override
Get the supported menu type.
void SetSubTitleDelay (float fValue=0.0f) override
float GetSubTitleDelay () override
int GetSubtitleCount () const override
int GetSubtitle () override
void GetSubtitleStreamInfo (int index, SubtitleStreamInfo &info) const override
void SetSubtitle (int iStream) override
bool GetSubtitleVisible () const override
void SetSubtitleVisible (bool bVisible) override
void SetSubtitleVerticalPosition (const int value, bool save) override
Set the subtitle vertical position, it depends on current screen resolution.
void AddSubtitle (const std::string &strSubPath) override
Adds the subtitle(s) provided by the given file to the available player streams and actives the first of the added stream(s). E.g., vob subs can contain multiple streams.
int GetAudioStreamCount () const override
int GetAudioStream () override
void SetAudioStream (int iStream) override
int GetVideoStream () const override
int GetVideoStreamCount () const override
void GetVideoStreamInfo (int streamId, VideoStreamInfo &info) const override
void SetVideoStream (int iStream) override
int GetPrograms (std::vector< ProgramInfo > &programs) override
void SetProgram (int progId) override
int GetProgramsCount () const override
std::shared_ptr< TextCacheStruct_t > GetTeletextCache () override
bool HasTeletextCache () const override
void LoadPage (int p, int sp, unsigned char *buffer) override
int GetChapterCount () const override
int GetChapter () const override
void GetChapterName (std::string &strChapterName, int chapterIdx=-1) const override
int64_t GetChapterPos (int chapterIdx=-1) const override
int SeekChapter (int iChapter) override
void SeekTime (int64_t iTime) override
bool SeekTimeRelative (int64_t iTime) override
void SetSpeed (float speed) override
void SetTempo (float tempo) override
bool SupportsTempo () const override
void FrameAdvance (int frames) override
bool OnAction (const CAction &action) override
void GetAudioStreamInfo (int index, AudioStreamInfo &info) const override
std::string GetPlayerState () override
bool SetPlayerState (const std::string &state) override
void FrameMove () override
void Render (bool clear, uint32_t alpha=255, bool gui=true) override
hook into render loop of render thread
void FlushRenderer () override
void SetRenderViewMode (int mode, float zoom, float par, float shift, bool stretch) override
float GetRenderAspectRatio () const override
void GetRects (CRect &source, CRect &dest, CRect &view) const override
unsigned int GetOrientation () const override
void TriggerUpdateResolution () override
bool IsRenderingVideo () const override
bool Supports (EINTERLACEMETHOD method) const override
EINTERLACEMETHOD GetDeinterlacingMethodDefault () const override
bool Supports (ESCALINGMETHOD method) const override
bool Supports (ERENDERFEATURE feature) const override
unsigned int RenderCaptureAlloc () override
void RenderCapture (unsigned int captureId, unsigned int width, unsigned int height, int flags) override
void RenderCaptureRelease (unsigned int captureId) override
bool RenderCaptureGetPixels (unsigned int captureId, unsigned int millis, uint8_t *buffer, unsigned int size) override
void OnLostDisplay () override
void OnResetDisplay () override
bool IsCaching () const override
int GetCacheLevel () const override
int OnDiscNavResult (void *pData, int iMessage) override
void GetVideoResolution (unsigned int &width, unsigned int &height) override
CVideoSettings GetVideoSettings () const override
void SetVideoSettings (CVideoSettings &settings) override
void SetUpdateStreamDetails ()
Public Member Functions inherited from IPlayer
IPlayer (IPlayerCallback &callback)
virtual ~IPlayer ()=default
virtual bool Initialize (TiXmlElement *pConfig)
virtual bool QueueNextFile (const CFileItem &file)
virtual void OnNothingToQueueNotify ()
virtual bool HasGame () const
virtual void SetMute (bool bOnOff)
virtual void SetVolume (float volume)
virtual void SetTime (int64_t time)
Sets the current time. This can be used for injecting the current time. This is not to be confused with a seek. It just can be used if endless streams contain multiple tracks in reality (like with airtunes)
virtual void SetTotalTime (int64_t time)
Set the total time in milliseconds this can be used for injecting the duration in case its not available in the underlaying decoder (airtunes for example)
virtual void GetAudioCapabilities (std::vector< IPlayerAudioCaps > &caps) const
Define the audio capabilities of the player.
virtual void GetSubtitleCapabilities (std::vector< IPlayerSubtitleCaps > &caps) const
Define the subtitle capabilities of the player.
virtual bool HasGameAgent () const
Check if any players are playing a game.
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Public Member Functions inherited from IVideoPlayer
virtual ~IVideoPlayer ()=default
Public Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
virtual void OnAppFocusChange (bool focus)
Public Member Functions inherited from IRenderLoop
virtual ~IRenderLoop ()=default
Public Member Functions inherited from IRenderMsg
virtual ~IRenderMsg ()=default
Protected Types
enum ECacheState {
CACHESTATE_DONE = 0 , CACHESTATE_FULL , CACHESTATE_INIT , CACHESTATE_PLAY ,
CACHESTATE_FLUSH
}
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions
void OnStartup () override
void OnExit () override
void Process () override
void VideoParamsChange () override
void GetDebugInfo (std::string &audio, std::string &video, std::string &general) override
void UpdateClockSync (bool enabled) override
void UpdateRenderInfo (CRenderInfo &info) override
void UpdateRenderBuffers (int queued, int discard, int free) override
void UpdateGuiRender (bool gui) override
void UpdateVideoRender (bool video) override
void CreatePlayers ()
void DestroyPlayers ()
void Prepare ()
bool OpenStream (CCurrentStream &current, int64_t demuxerId, int iStream, int source, bool reset=true)
bool OpenAudioStream (CDVDStreamInfo &hint, bool reset=true)
bool OpenVideoStream (CDVDStreamInfo &hint, bool reset=true)
bool OpenSubtitleStream (const CDVDStreamInfo &hint)
bool OpenTeletextStream (CDVDStreamInfo &hint)
bool OpenRadioRDSStream (CDVDStreamInfo &hint)
bool OpenAudioID3Stream (CDVDStreamInfo &hint)
void AdaptForcedSubtitles ()
Switches forced subtitles to forced subtitles matching the language of the current audio track. If these are not available, subtitles are disabled.
bool CloseStream (CCurrentStream &current, bool bWaitForBuffers)
bool CheckIsCurrent (const CCurrentStream &current, CDemuxStream *stream, DemuxPacket *pkg)
void ProcessPacket (CDemuxStream *pStream, DemuxPacket *pPacket)
void ProcessAudioData (CDemuxStream *pStream, DemuxPacket *pPacket)
void ProcessVideoData (CDemuxStream *pStream, DemuxPacket *pPacket)
void ProcessSubData (CDemuxStream *pStream, DemuxPacket *pPacket)
void ProcessTeletextData (CDemuxStream *pStream, DemuxPacket *pPacket)
void ProcessRadioRDSData (CDemuxStream *pStream, DemuxPacket *pPacket)
void ProcessAudioID3Data (CDemuxStream *pStream, DemuxPacket *pPacket)
int AddSubtitleFile (const std::string &filename, const std::string &subfilename="")
void SetEnableStream (CCurrentStream &current, bool isEnabled)
Propagate enable stream callbacks to demuxers.
void SetSubtitleVisibleInternal (bool bVisible)
void SetPlaySpeed (int iSpeed)
void SetCaching (ECacheState state)
double GetQueueTime ()
CacheInfo GetCachingTimes ()
void FlushBuffers (double pts, bool accurate, bool sync)
void HandleMessages ()
void HandlePlaySpeed ()
bool IsInMenuInternal () const
void SynchronizeDemuxer ()
void CheckAutoSceneSkip ()
bool CheckContinuity (CCurrentStream &current, DemuxPacket *pPacket)
bool CheckSceneSkip (const CCurrentStream &current)
bool CheckPlayerInit (CCurrentStream &current)
void UpdateCorrection (DemuxPacket *pkt, double correction)
void UpdateTimestamps (CCurrentStream &current, DemuxPacket *pPacket)
IDVDStreamPlayer * GetStreamPlayer (unsigned int player)
void SendPlayerMessage (std::shared_ptr< CDVDMsg > pMsg, unsigned int target)
bool ReadPacket (DemuxPacket *&packet, CDemuxStream *&stream)
bool IsValidStream (const CCurrentStream &stream)
bool IsBetterStream (const CCurrentStream &current, CDemuxStream *stream)
void CheckBetterStream (CCurrentStream &current, CDemuxStream *stream)
void CheckStreamChanges (CCurrentStream &current, CDemuxStream *stream)
bool OpenInputStream ()
bool OpenDemuxStream ()
void CloseDemuxer ()
void OpenDefaultStreams (bool reset=true)
void UpdatePlayState (double timeout)
void GetGeneralInfo (std::string &strVideoInfo)
int64_t GetUpdatedTime ()
int64_t GetTime ()
float GetPercentage ()
void UpdateContent ()
void UpdateContentState ()
void UpdateFileItemStreamDetails (CFileItem &item)
int GetPreviousChapter ()
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes
bool m_players_created
CFileItem m_item
CPlayerOptions m_playerOptions
bool m_bAbortRequest
bool m_error
bool m_bCloseRequest
ECacheState m_caching
XbmcThreads::EndTime m_cachingTimer
std::unique_ptr< CProcessInfo > m_processInfo
CCurrentStream m_CurrentAudio
CCurrentStream m_CurrentVideo
CCurrentStream m_CurrentSubtitle
CCurrentStream m_CurrentTeletext
CCurrentStream m_CurrentRadioRDS
CCurrentStream m_CurrentAudioID3
CSelectionStreams m_SelectionStreams
std::vector< ProgramInfo > m_programs
struct CVideoPlayer::SContent m_content
int m_playSpeed
int m_streamPlayerSpeed
int m_demuxerSpeed = DVD_PLAYSPEED_NORMAL
struct CVideoPlayer::SSpeedState m_SpeedState
double m_offset_pts
CDVDMessageQueue m_messenger
std::unique_ptr< CJobQueue > m_outboundEvents
IDVDStreamPlayerVideo * m_VideoPlayerVideo
IDVDStreamPlayerAudio * m_VideoPlayerAudio
CVideoPlayerSubtitle * m_VideoPlayerSubtitle
CDVDTeletextData * m_VideoPlayerTeletext
CDVDRadioRDSData * m_VideoPlayerRadioRDS
std::unique_ptr< CVideoPlayerAudioID3 > m_VideoPlayerAudioID3
CDVDClock m_clock
CDVDOverlayContainer m_overlayContainer
std::shared_ptr< CDVDInputStream > m_pInputStream
std::unique_ptr< CDVDDemux > m_pDemuxer
std::shared_ptr< CDVDDemux > m_pSubtitleDemuxer
std::unordered_map< int64_t, std::shared_ptr< CDVDDemux > > m_subtitleDemuxerMap
std::unique_ptr< CDVDDemuxCC > m_pCCDemuxer
CRenderManager m_renderManager
struct CVideoPlayer::SDVDInfo m_dvd
SPlayerState m_State
CCriticalSection m_StateSection
XbmcThreads::EndTime m_syncTimer
CEdl m_Edl
bool m_SkipCommercials
bool m_HasVideo
bool m_HasAudio
bool m_UpdateStreamDetails
std::atomic< bool > m_displayLost
double m_messageQueueTimeSize {0.0}
Protected Attributes inherited from IPlayer
IPlayerCallback & m_callback
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Friends
class CSelectionStreams
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Public Attributes inherited from IPlayer
std::string m_name
std::string m_type
Member Enumeration Documentation
ECacheState
enum CVideoPlayer::ECacheState protected
Enumerator
CACHESTATE_DONE
CACHESTATE_FULL
CACHESTATE_INIT
CACHESTATE_PLAY
CACHESTATE_FLUSH
Constructor & Destructor Documentation
CVideoPlayer()
CVideoPlayer::CVideoPlayer (IPlayerCallback & callback) explicit
References CACHESTATE_DONE, SPlayerState::Clear(), CVideoPlayer::SDVDInfo::Clear(), CProcessInfo::CreateInstance(), CreatePlayers(), DVD_PLAYSPEED_NORMAL, CServiceBroker::GetDataCacheCore(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), m_bAbortRequest, m_bCloseRequest, m_caching, m_displayLost, m_dvd, m_error, m_HasAudio, m_HasVideo, m_messageQueueTimeSize, m_offset_pts, m_players_created, m_playSpeed, m_processInfo, m_SkipCommercials, m_State, m_streamPlayerSpeed, m_UpdateStreamDetails, CWinSystemBase::Register(), and CSettings::SETTING_VIDEOPLAYER_QUEUETIMESIZE.
~CVideoPlayer()
CVideoPlayer::~CVideoPlayer () override
References CloseFile(), DestroyPlayers(), CServiceBroker::GetWinSystem(), m_outboundEvents, CThread::Sleep(), and CWinSystemBase::Unregister().
Member Function Documentation
AdaptForcedSubtitles()
void CVideoPlayer::AdaptForcedSubtitles () protected
Switches forced subtitles to forced subtitles matching the language of the current audio track. If these are not available, subtitles are disabled.
References CLangCodeExpander::CompareISO639Codes(), CCurrentStream::demuxerId, FLAG_FORCED, SelectionStream::flags, g_LangCodeExpander, CSelectionStreams::Get(), GetAudioStream(), GetSubtitle(), SelectionStream::language, m_CurrentSubtitle, m_SelectionStreams, OpenStream(), SetEnableStream(), SetSubtitleVisibleInternal(), STREAM_AUDIO, and STREAM_SUBTITLE.
Referenced by HandleMessages().
AddSubtitle()
void CVideoPlayer::AddSubtitle (const std::string & strSubPath) override virtual
Adds the subtitle(s) provided by the given file to the available player streams and actives the first of the added stream(s). E.g., vob subs can contain multiple streams.
Parameters
[in] strSubPath The full path of the subtitle file.
Reimplemented from IPlayer.
References m_messenger, CDVDMessageQueue::Put(), and CDVDMsg::SUBTITLE_ADDFILE.
AddSubtitleFile()
int CVideoPlayer::AddSubtitleFile (const std::string & filename, const std::string & subfilename = "") protected
References AddSubtitleFile(), CDVDFactoryInputStream::CreateInputStream(), SelectionStream::demuxerId, SelectionStream::filename, FLAG_NONE, SelectionStream::flags, CSelectionStreams::Get(), CFileItem::GetDynPath(), URIUtils::GetExtension(), CUtil::GetExternalStreamDetailsFromFilename(), CUtil::GetVobSubIdxFromSub(), CUtil::GetVobSubSubFromIdx(), SelectionStream::id, index(), SelectionStream::language, m_item, m_SelectionStreams, m_subtitleDemuxerMap, SelectionStream::name, SelectionStream::source, CSelectionStreams::Source(), STREAM_SOURCE_DEMUX_SUB, STREAM_SOURCE_NONE, STREAM_SOURCE_TEXT, STREAM_SUBTITLE, SelectionStream::type, CSelectionStreams::TypeIndexOf(), CSelectionStreams::Update(), and UpdateContent().
Referenced by AddSubtitleFile(), HandleMessages(), and OpenInputStream().
CanPause()
bool CVideoPlayer::CanPause () const override virtual
Reimplemented from IPlayer.
References SPlayerState::canpause, m_State, and m_StateSection.
Referenced by SetSpeed().
CanSeek()
bool CVideoPlayer::CanSeek () const override virtual
Reimplemented from IPlayer.
References SPlayerState::canseek, m_State, and m_StateSection.
Referenced by SetSpeed().
CheckAutoSceneSkip()
void CVideoPlayer::CheckAutoSceneSkip () protected
References CDVDMsgPlayerSeek::CMode::accurate, CDVDMsgPlayerSeek::CMode::backward, EDL::COMM_BREAK, EDL::CUT, end(), CServiceBroker::GetAnnouncementManager(), CEdl::GetLastEditActionType(), CEdl::GetLastEditTime(), GetTime(), CEdl::GetTimeAfterRestoringCuts(), CEdl::HasEdits(), CCurrentStream::id, CEdl::InEdit(), CCurrentStream::inited, CLog::Log(), LOGDEBUG, m_CurrentAudio, m_CurrentVideo, m_Edl, m_messenger, m_playSpeed, m_SkipCommercials, ANNOUNCEMENT::Player, CDVDMessageQueue::Put(), CEdl::ResetLastEditTime(), CDVDMsgPlayerSeek::CMode::restore, CEdl::SetLastEditActionType(), CEdl::SetLastEditTime(), CDVDMsgPlayerSeek::CMode::sync, IDVDStreamPlayer::SYNC_INSYNC, CCurrentStream::syncState, CDVDMsgPlayerSeek::CMode::time, TIME_FORMAT_MM_SS, and CDVDMsgPlayerSeek::CMode::trickplay.
Referenced by Process().
CheckBetterStream()
void CVideoPlayer::CheckBetterStream (CCurrentStream & current, CDemuxStream * stream) protected
References CloseStream(), CDemuxStream::demuxerId, GetStreamPlayer(), IsBetterStream(), IDVDStreamPlayer::IsStalled(), IsValidStream(), OpenStream(), CCurrentStream::player, CDemuxStream::source, and CDemuxStream::uniqueId.
Referenced by Process().
CheckContinuity()
bool CVideoPlayer::CheckContinuity (CCurrentStream & current, DemuxPacket * pPacket) protected
References CCurrentStream::AV_SYNC_CHECK, CCurrentStream::AV_SYNC_CONT, CCurrentStream::avsync, DEMUX_PACKET::dts, CCurrentStream::dts, CCurrentStream::dts_end(), DVD_MSEC_TO_TIME(), DVD_NOPTS_VALUE, DVD_PLAYSPEED_PAUSE, CCurrentStream::id, CCurrentStream::lastdts, CLog::Log(), LOGDEBUG, m_CurrentAudio, m_CurrentVideo, m_offset_pts, m_playSpeed, DEMUX_PACKET::pts, STREAM_AUDIO, CCurrentStream::type, UpdateCorrection(), and UpdateLimits().
Referenced by ProcessAudioData(), and ProcessVideoData().
CheckIsCurrent()
bool CVideoPlayer::CheckIsCurrent (const CCurrentStream & current, CDemuxStream * stream, DemuxPacket * pkg) protected
References CDemuxStream::demuxerId, CCurrentStream::demuxerId, CCurrentStream::id, DEMUX_PACKET::iStreamId, CDemuxStream::source, CCurrentStream::source, CDemuxStream::type, and CCurrentStream::type.
Referenced by Process(), and ProcessPacket().
CheckPlayerInit()
bool CVideoPlayer::CheckPlayerInit (CCurrentStream & current) protected
References CCurrentStream::dts, DVD_NOPTS_VALUE, DVD_SEC_TO_TIME(), CCurrentStream::inited, CLog::Log(), LOGDEBUG, m_CurrentAudio, m_CurrentAudioID3, m_CurrentRadioRDS, m_CurrentSubtitle, m_CurrentTeletext, m_CurrentVideo, CCurrentStream::player, and CCurrentStream::startpts.
Referenced by ProcessAudioData(), ProcessAudioID3Data(), ProcessRadioRDSData(), ProcessSubData(), ProcessTeletextData(), and ProcessVideoData().
CheckSceneSkip()
bool CVideoPlayer::CheckSceneSkip (const CCurrentStream & current) protected
References EDL::CUT, CCurrentStream::dts, DVD_NOPTS_VALUE, CEdl::HasEdits(), CEdl::InEdit(), CCurrentStream::inited, m_Edl, and m_offset_pts.
Referenced by ProcessAudioData(), ProcessAudioID3Data(), ProcessRadioRDSData(), ProcessSubData(), ProcessTeletextData(), and ProcessVideoData().
CheckStreamChanges()
void CVideoPlayer::CheckStreamChanges (CCurrentStream & current, CDemuxStream * stream) protected
References CDemuxStream::changes, CCurrentStream::changes, CSelectionStreams::Clear(), CCurrentStream::hint, m_pDemuxer, m_pInputStream, m_SelectionStreams, OpenDefaultStreams(), CCurrentStream::stream, STREAM_NONE, STREAM_SOURCE_DEMUX, CSelectionStreams::Update(), and UpdateContent().
Referenced by ProcessAudioData(), ProcessAudioID3Data(), ProcessRadioRDSData(), ProcessSubData(), ProcessTeletextData(), and ProcessVideoData().
CloseDemuxer()
void CVideoPlayer::CloseDemuxer () protected
References CSelectionStreams::Clear(), CServiceBroker::GetDataCacheCore(), m_pDemuxer, m_SelectionStreams, CDataCacheCore::SignalAudioInfoChange(), CDataCacheCore::SignalSubtitleInfoChange(), CDataCacheCore::SignalVideoInfoChange(), STREAM_NONE, and STREAM_SOURCE_DEMUX.
Referenced by OpenDemuxStream(), and Process().
CloseFile()
bool CVideoPlayer::CloseFile (bool reopen = false) override virtual
Implements IPlayer.
References CEdl::Clear(), CServiceBroker::GetDataCacheCore(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGINFO, m_bAbortRequest, m_bCloseRequest, m_Edl, m_HasAudio, m_HasVideo, m_pDemuxer, m_pInputStream, m_pSubtitleDemuxer, m_renderManager, CDataCacheCore::Reset(), CThread::StopThread(), and CRenderManager::UnInit().
Referenced by ~CVideoPlayer().
CloseStream()
bool CVideoPlayer::CloseStream (CCurrentStream & current, bool bWaitForBuffers) protected
References CACHESTATE_DONE, CCurrentStream::Clear(), IDVDStreamPlayer::CloseStream(), GetStreamPlayer(), CCurrentStream::id, CLog::Log(), LOGINFO, m_bAbortRequest, CCurrentStream::player, SetCaching(), SetEnableStream(), STREAM_AUDIO, STREAM_VIDEO, IDVDStreamPlayer::SYNC_INSYNC, CCurrentStream::syncState, and CCurrentStream::type.
Referenced by CheckBetterStream(), HandleMessages(), OnExit(), OpenDefaultStreams(), and Process().
CreatePlayers()
void CVideoPlayer::CreatePlayers () protected
References m_clock, m_messageQueueTimeSize, m_messenger, m_overlayContainer, m_players_created, m_processInfo, m_renderManager, m_VideoPlayerAudio, m_VideoPlayerAudioID3, m_VideoPlayerRadioRDS, m_VideoPlayerSubtitle, m_VideoPlayerTeletext, and m_VideoPlayerVideo.
Referenced by CVideoPlayer(), and Prepare().
DestroyPlayers()
void CVideoPlayer::DestroyPlayers () protected
References m_players_created, m_VideoPlayerAudio, m_VideoPlayerAudioID3, m_VideoPlayerRadioRDS, m_VideoPlayerSubtitle, m_VideoPlayerTeletext, and m_VideoPlayerVideo.
Referenced by ~CVideoPlayer().
FlushBuffers()
void CVideoPlayer::FlushBuffers (double pts, bool accurate, bool sync) protected
References CCurrentStream::AV_SYNC_FORCE, CCurrentStream::avsync, CACHESTATE_FLUSH, CDVDClock::Discontinuity(), CCurrentStream::dts, DVD_NOPTS_VALUE, DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, CDVDRadioRDSData::Flush(), CVideoPlayerSubtitle::Flush(), CDVDTeletextData::Flush(), IDVDStreamPlayerVideo::Flush(), IDVDStreamPlayerAudio::Flush(), CDVDMessageQueue::Flush(), CCurrentStream::inited, CLog::Log(), LOGDEBUG, CThread::m_bStop, m_clock, m_CurrentAudio, m_CurrentAudioID3, m_CurrentRadioRDS, m_CurrentSubtitle, m_CurrentTeletext, m_CurrentVideo, m_demuxerSpeed, m_messenger, m_pDemuxer, m_playSpeed, m_processInfo, m_SpeedState, m_VideoPlayerAudio, m_VideoPlayerAudioID3, m_VideoPlayerRadioRDS, m_VideoPlayerSubtitle, m_VideoPlayerTeletext, m_VideoPlayerVideo, CCurrentStream::packets, CDVDMsg::PLAYER_STARTED, CVideoPlayer::SSpeedState::Reset(), IDVDStreamPlayerVideo::SendMessage(), IDVDStreamPlayerAudio::SendMessage(), SetCaching(), CCurrentStream::startpts, CCurrentStream::starttime, IDVDStreamPlayer::SYNC_STARTING, SYNCSOURCE_AUDIO, SYNCSOURCE_VIDEO, CCurrentStream::syncState, and UpdatePlayState().
Referenced by HandleMessages(), HandlePlaySpeed(), OnDiscNavResult(), and Prepare().
FlushRenderer()
void CVideoPlayer::FlushRenderer () override virtual
Reimplemented from IPlayer.
References CRenderManager::Flush(), and m_renderManager.
Referenced by OnLostDisplay().
FrameAdvance()
void CVideoPlayer::FrameAdvance (int frames) override virtual
Reimplemented from IPlayer.
References DVD_PLAYSPEED_PAUSE, m_messenger, m_processInfo, CDVDMsg::PLAYER_FRAME_ADVANCE, and CDVDMessageQueue::Put().
FrameMove()
void CVideoPlayer::FrameMove () override virtual
Implements IRenderLoop.
References CRenderManager::FrameMove(), and m_renderManager.
GetAudioStream()
int CVideoPlayer::GetAudioStream () override virtual
Reimplemented from IPlayer.
References CVideoPlayer::SContent::m_audioIndex, m_content, and CVideoPlayer::SContent::m_section.
Referenced by AdaptForcedSubtitles(), and OpenDefaultStreams().
GetAudioStreamCount()
int CVideoPlayer::GetAudioStreamCount () const override virtual
Reimplemented from IPlayer.
References CSelectionStreams::CountType(), m_content, CVideoPlayer::SContent::m_section, CVideoPlayer::SContent::m_selectionStreams, and STREAM_AUDIO.
Referenced by GetAudioStreamInfo(), and UpdateFileItemStreamDetails().
GetAudioStreamInfo()
void CVideoPlayer::GetAudioStreamInfo (int index, AudioStreamInfo & info) const override virtual
Reimplemented from IPlayer.
References SelectionStream::bitrate, SelectionStream::channels, SelectionStream::codec, SelectionStream::codecDesc, CURRENT_STREAM, SelectionStream::flags, CSelectionStreams::Get(), GetAudioStreamCount(), index(), SelectionStream::language, CVideoPlayer::SContent::m_audioIndex, m_content, CVideoPlayer::SContent::m_section, CVideoPlayer::SContent::m_selectionStreams, SelectionStream::name, STREAM_AUDIO, STREAM_NONE, and SelectionStream::type.
Referenced by UpdateFileItemStreamDetails().
GetAVDelay()
float CVideoPlayer::GetAVDelay () override virtual
Reimplemented from IPlayer.
References CRenderManager::GetDelay(), and m_renderManager.
GetCacheLevel()
int CVideoPlayer::GetCacheLevel () const override virtual
Reimplemented from IPlayer.
References SPlayerState::cache_level, m_State, and m_StateSection.
GetCachePercentage()
float CVideoPlayer::GetCachePercentage () const override virtual
Reimplemented from IPlayer.
References SPlayerState::cache_offset, m_State, and m_StateSection.
GetCachingTimes()
CacheInfo CVideoPlayer::GetCachingTimes () protected
References XFILE::SCacheStatus::currate, DVD_MSEC_TO_TIME(), XFILE::SCacheStatus::forward, GetQueueTime(), int64_t(), CLog::Log(), LOGDEBUG, XFILE::SCacheStatus::lowrate, m_pDemuxer, m_pInputStream, XFILE::SCacheStatus::maxforward, and XFILE::SCacheStatus::maxrate.
Referenced by HandlePlaySpeed(), SetCaching(), and UpdatePlayState().
GetChapter()
int CVideoPlayer::GetChapter () const override virtual
Reimplemented from IPlayer.
References SPlayerState::chapter, m_State, and m_StateSection.
Referenced by GetPreviousChapter(), OnAction(), Seek(), and SeekChapter().
GetChapterCount()
int CVideoPlayer::GetChapterCount () const override virtual
Reimplemented from IPlayer.
References SPlayerState::chapters, m_State, and m_StateSection.
Referenced by OnAction(), Seek(), and SeekChapter().
GetChapterName()
void CVideoPlayer::GetChapterName (std::string & strChapterName, int chapterIdx = -1) const override virtual
Reimplemented from IPlayer.
References SPlayerState::chapter, SPlayerState::chapters, m_State, and m_StateSection.
GetChapterPos()
int64_t CVideoPlayer::GetChapterPos (int chapterIdx = -1) const override virtual
Reimplemented from IPlayer.
References SPlayerState::chapters, m_State, and m_StateSection.
Referenced by GetPreviousChapter().
GetDebugInfo()
void CVideoPlayer::GetDebugInfo (std::string & audio, std::string & video, std::string & general) override protected virtual
Implements IRenderMsg.
References GetGeneralInfo(), IDVDStreamPlayerVideo::GetPlayerInfo(), IDVDStreamPlayerAudio::GetPlayerInfo(), m_VideoPlayerAudio, and m_VideoPlayerVideo.
GetDeinterlacingMethodDefault()
EINTERLACEMETHOD CVideoPlayer::GetDeinterlacingMethodDefault () const override virtual
Reimplemented from IPlayer.
References m_processInfo, and VS_INTERLACEMETHOD_NONE.
GetGeneralInfo()
void CVideoPlayer::GetGeneralInfo (std::string & strVideoInfo) protected
References SPlayerState::cache_bytes, SPlayerState::cache_level, SPlayerState::cache_offset, SPlayerState::cache_time, DVD_NOPTS_VALUE, DVD_TIME_BASE, IDVDStreamPlayerVideo::GetCurrentPts(), IDVDStreamPlayerAudio::GetCurrentPts(), CThread::m_bStop, m_State, m_StateSection, m_VideoPlayerAudio, and m_VideoPlayerVideo.
Referenced by GetDebugInfo().
GetOrientation()
unsigned int CVideoPlayer::GetOrientation () const override virtual
Reimplemented from IPlayer.
References CRenderManager::GetOrientation(), and m_renderManager.
GetPercentage()
float CVideoPlayer::GetPercentage () protected
References GetTime(), int64_t(), and m_processInfo.
Referenced by Seek().
GetPlayerState()
std::string CVideoPlayer::GetPlayerState () override virtual
Reimplemented from IPlayer.
References m_State, m_StateSection, and SPlayerState::player_state.
Referenced by HandleMessages(), and OnExit().
GetPreviousChapter()
int CVideoPlayer::GetPreviousChapter () protected
References GetChapter(), GetChapterPos(), and GetTime().
Referenced by OnAction(), and Seek().
GetPrograms()
int CVideoPlayer::GetPrograms (std::vector< ProgramInfo > & programs) override virtual
Reimplemented from IPlayer.
References m_content, m_programs, and CVideoPlayer::SContent::m_section.
GetProgramsCount()
int CVideoPlayer::GetProgramsCount () const override virtual
Reimplemented from IPlayer.
References m_content, m_programs, and CVideoPlayer::SContent::m_section.
GetQueueTime()
double CVideoPlayer::GetQueueTime () protected
References IDVDStreamPlayerAudio::GetLevel(), m_messageQueueTimeSize, m_processInfo, and m_VideoPlayerAudio.
Referenced by GetCachingTimes(), and UpdatePlayState().
GetRects()
void CVideoPlayer::GetRects (CRect & source, CRect & dest, CRect & view) const override virtual
Reimplemented from IPlayer.
References CRenderManager::GetVideoRect(), and m_renderManager.
GetRenderAspectRatio()
float CVideoPlayer::GetRenderAspectRatio () const override virtual
Reimplemented from IPlayer.
References CRenderManager::GetAspectRatio(), and m_renderManager.
GetStreamPlayer()
IDVDStreamPlayer * CVideoPlayer::GetStreamPlayer (unsigned int player) protected
References m_VideoPlayerAudio, m_VideoPlayerAudioID3, m_VideoPlayerRadioRDS, m_VideoPlayerSubtitle, m_VideoPlayerTeletext, m_VideoPlayerVideo, VideoPlayer_AUDIO, VideoPlayer_ID3, VideoPlayer_RDS, VideoPlayer_SUBTITLE, VideoPlayer_TELETEXT, and VideoPlayer_VIDEO.
Referenced by CheckBetterStream(), CloseStream(), OpenAudioID3Stream(), OpenAudioStream(), OpenRadioRDSStream(), OpenSubtitleStream(), OpenTeletextStream(), OpenVideoStream(), and SendPlayerMessage().
GetSubtitle()
int CVideoPlayer::GetSubtitle () override virtual
Reimplemented from IPlayer.
References m_content, CVideoPlayer::SContent::m_section, and CVideoPlayer::SContent::m_subtitleIndex.
Referenced by AdaptForcedSubtitles().
GetSubtitleCount()
int CVideoPlayer::GetSubtitleCount () const override virtual
Reimplemented from IPlayer.
References CSelectionStreams::CountType(), m_content, CVideoPlayer::SContent::m_section, CVideoPlayer::SContent::m_selectionStreams, and STREAM_SUBTITLE.
Referenced by GetSubtitleStreamInfo(), and UpdateFileItemStreamDetails().
GetSubTitleDelay()
float CVideoPlayer::GetSubTitleDelay () override virtual
Reimplemented from IPlayer.
References DVD_TIME_BASE, IDVDStreamPlayerVideo::GetSubtitleDelay(), and m_VideoPlayerVideo.
GetSubtitleStreamInfo()
void CVideoPlayer::GetSubtitleStreamInfo (int index, SubtitleStreamInfo & info) const override virtual
Reimplemented from IPlayer.
References SelectionStream::codec, CURRENT_STREAM, FLAG_NONE, SelectionStream::flags, CSelectionStreams::Get(), GetSubtitleCount(), index(), SelectionStream::language, m_content, CVideoPlayer::SContent::m_section, CVideoPlayer::SContent::m_selectionStreams, CVideoPlayer::SContent::m_subtitleIndex, SelectionStream::name, SelectionStream::source, STREAM_NONE, STREAM_SOURCE_DEMUX_SUB, STREAM_SOURCE_MASK, STREAM_SOURCE_TEXT, STREAM_SUBTITLE, and SelectionStream::type.
Referenced by UpdateFileItemStreamDetails().
GetSubtitleVisible()
bool CVideoPlayer::GetSubtitleVisible () const override virtual
Reimplemented from IPlayer.
References DVDSTREAM_TYPE_DVD, IDVDStreamPlayerVideo::IsSubtitleEnabled(), m_pInputStream, and m_VideoPlayerVideo.
GetSupportedMenuType()
MenuType CVideoPlayer::GetSupportedMenuType () const override virtual
Get the supported menu type.
Returns
The supported menu type
Reimplemented from IPlayer.
References m_State, m_StateSection, and SPlayerState::menuType.
GetTeletextCache()
std::shared_ptr< TextCacheStruct_t > CVideoPlayer::GetTeletextCache () override virtual
Reimplemented from IPlayer.
References CDVDTeletextData::GetTeletextCache(), CCurrentStream::id, m_CurrentTeletext, and m_VideoPlayerTeletext.
GetTime()
int64_t CVideoPlayer::GetTime () protected
References m_State, m_StateSection, and SPlayerState::time.
Referenced by CheckAutoSceneSkip(), GetPercentage(), GetPreviousChapter(), HandleMessages(), HandlePlaySpeed(), Seek(), SeekScene(), SeekTime(), and SeekTimeRelative().
GetUpdatedTime()
int64_t CVideoPlayer::GetUpdatedTime () protected
References m_State, SPlayerState::time, and UpdatePlayState().
Referenced by HandleMessages(), and HandlePlaySpeed().
GetVideoResolution()
void CVideoPlayer::GetVideoResolution (unsigned int & width, unsigned int & height) override virtual
Implements IVideoPlayer.
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetResInfo(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iHeight, and RESOLUTION_INFO::iWidth.
GetVideoSettings()
CVideoSettings CVideoPlayer::GetVideoSettings () const override virtual
Reimplemented from IPlayer.
References m_processInfo.
GetVideoStream()
int CVideoPlayer::GetVideoStream () const override virtual
Reimplemented from IPlayer.
References m_content, CVideoPlayer::SContent::m_section, and CVideoPlayer::SContent::m_videoIndex.
GetVideoStreamCount()
int CVideoPlayer::GetVideoStreamCount () const override virtual
Reimplemented from IPlayer.
References CSelectionStreams::CountType(), m_content, CVideoPlayer::SContent::m_section, CVideoPlayer::SContent::m_selectionStreams, and STREAM_VIDEO.
Referenced by GetVideoStreamInfo().
GetVideoStreamInfo()
void CVideoPlayer::GetVideoStreamInfo (int streamId, VideoStreamInfo & info) const override virtual
Reimplemented from IPlayer.
References SelectionStream::aspect_ratio, SelectionStream::bitrate, SelectionStream::codec, CURRENT_STREAM, SelectionStream::flags, SelectionStream::fpsRate, SelectionStream::fpsScale, CSelectionStreams::Get(), CRenderManager::GetVideoRect(), GetVideoStreamCount(), SelectionStream::hdrType, SelectionStream::height, SelectionStream::language, m_content, m_renderManager, CVideoPlayer::SContent::m_section, CVideoPlayer::SContent::m_selectionStreams, CVideoPlayer::SContent::m_videoIndex, SelectionStream::name, SelectionStream::stereo_mode, STREAM_VIDEO, and SelectionStream::width.
Referenced by UpdateFileItemStreamDetails().
HandleMessages()
void CVideoPlayer::HandleMessages () protected
Todo:
After demuxer we add an offset to input pts so that displayed time and clock are increasing steadily. For seeking we need to determine the boundaries and offset of the desired segment. With the current approach calculated time may point to nirvana
References CDVDMsgPlayerSeek::CMode::accurate, AdaptForcedSubtitles(), AddSubtitleFile(), CDVDClock::Advance(), CDVDMsgPlayerSeek::CMode::backward, CACHESTATE_DONE, CACHESTATE_FLUSH, SStartMsg::cachetime, CCurrentStream::cachetime, SStartMsg::cachetotal, CCurrentStream::cachetotal, SPlayerState::canseek, CSelectionStreams::Clear(), CloseStream(), CDVDMsg::DEMUXER_RESET, SelectionStream::demuxerId, SPlayerState::dts, DVD_MSEC_TO_TIME(), DVD_NOPTS_VALUE, DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, DVD_TIME_BASE, DVD_TIME_TO_MSEC(), DVDSTATE_NORMAL, DVDSTATE_SEEK, DVDSTREAM_TYPE_DVD, DVDSTREAM_TYPE_PVRMANAGER, CRenderManager::Flush(), FlushBuffers(), CDVDMsg::GENERAL_FLUSH, CDVDMsg::GENERAL_GUI_ACTION, CDVDMsg::GENERAL_SYNCHRONIZE, CDVDMessageQueue::Get(), CSelectionStreams::Get(), CDVDClock::GetAbsoluteClock(), CDVDMsgPlayerSeek::GetAccurate(), CDVDMsgPlayerSeek::GetBackward(), CDVDMsgPlayerSeekChapter::GetChapter(), CDVDClock::GetClock(), IDVDStreamPlayerVideo::GetCurrentPts(), CServiceBroker::GetDataCacheCore(), CDVDMsgOpenFile::GetItem(), CDVDMsgOpenFile::GetOptions(), CDVDMessageQueue::GetPacketCount(), GetPlayerState(), CDVDMsgPlayerSeek::GetRelative(), CDVDMsgPlayerSeek::GetRestore(), CDVDMsgPlayerSeek::GetSync(), CDVDMsgPlayerSeek::GetTime(), GetTime(), CEdl::GetTimeAfterRestoringCuts(), CDVDMsgPlayerSeek::GetTrickPlay(), GetUpdatedTime(), CCurrentStream::id, SelectionStream::id, CVideoPlayer::SDVDInfo::iDVDStillStartTime, CVideoPlayer::SDVDInfo::iDVDStillTime, int64_t(), CVideoPlayer::SDVDInfo::iSelectedAudioStream, CVideoPlayer::SDVDInfo::iSelectedSPUStream, CVideoPlayer::SDVDInfo::iSelectedVideoStream, SPlayerState::lastSeek, CLog::Log(), LOGDEBUG, m_bAbortRequest, m_caching, IPlayer::m_callback, m_clock, m_CurrentAudio, m_CurrentSubtitle, m_CurrentVideo, m_dvd, m_Edl, m_item, m_messenger, IPlayer::m_name, m_outboundEvents, m_pCCDemuxer, m_pDemuxer, m_pInputStream, m_playerOptions, m_playSpeed, m_processInfo, m_pSubtitleDemuxer, m_renderManager, m_SelectionStreams, m_State, m_streamPlayerSpeed, m_subtitleDemuxerMap, m_UpdateStreamDetails, CDVDMsgType< T >::m_value, m_VideoPlayerAudio, m_VideoPlayerVideo, MSGQ_OK, OnAction(), IPlayerCallback::OnAVChange(), IPlayerCallback::OnPlayBackSeekChapter(), IPlayerCallback::OnPlayBackSpeedChanged(), IPlayerCallback::OnPlayBackStarted(), IPlayerCallback::OnPlayerCloseFile(), OpenStream(), SStartMsg::player, SStateMsg::player, CBookmark::player, CDVDMsg::PLAYER_ABORT, CDVDMsg::PLAYER_AVCHANGE, CDVDMsg::PLAYER_FRAME_ADVANCE, CDVDMsg::PLAYER_OPENFILE, CDVDMsg::PLAYER_REPORT_STATE, CDVDMsg::PLAYER_SEEK, CDVDMsg::PLAYER_SEEK_CHAPTER, CDVDMsg::PLAYER_SET_AUDIOSTREAM, CDVDMsg::PLAYER_SET_PROGRAM, CDVDMsg::PLAYER_SET_STATE, CDVDMsg::PLAYER_SET_SUBTITLESTREAM, CDVDMsg::PLAYER_SET_SUBTITLESTREAM_VISIBLE, CDVDMsg::PLAYER_SET_UPDATE_STREAM_DETAILS, CDVDMsg::PLAYER_SET_VIDEOSTREAM, CDVDMsg::PLAYER_SETSPEED, CDVDMsg::PLAYER_STARTED, CBookmark::playerState, Prepare(), CDVDMessageQueue::Put(), CDVDMsgPlayerSeek::CMode::restore, CDVDInputStream::IChapter::SeekChapter(), SetCaching(), SetEnableStream(), SetPlaySpeed(), CDVDClock::SetSpeed(), IDVDStreamPlayerVideo::SetSpeed(), IDVDStreamPlayerAudio::SetSpeed(), SetSubtitle(), SetSubtitleVisibleInternal(), CDataCacheCore::SignalAudioInfoChange(), CDataCacheCore::SignalSubtitleInfoChange(), CDataCacheCore::SignalVideoInfoChange(), SelectionStream::source, SPlayerState::startTime, CCurrentStream::starttime, CVideoPlayer::SDVDInfo::state, IPlayerCallback::StoreVideoSettings(), CCurrentStream::stream, STREAM_AUDIO, STREAM_NONE, STREAM_SOURCE_NAV, STREAM_SOURCE_NONE, STREAM_SUBTITLE, STREAM_VIDEO, CDVDMsg::SUBTITLE_ADDFILE, CDVDMsgPlayerSeek::CMode::sync, IDVDStreamPlayer::SYNC_INSYNC, IDVDStreamPlayer::SYNC_WAITSYNC, SYNCSOURCE_PLAYER, SStateMsg::syncState, CCurrentStream::syncState, CDVDMsgPlayerSeek::CMode::time, SPlayerState::time, SPlayerState::time_offset, CBookmark::timeInSeconds, SPlayerState::timeMax, SStartMsg::timestamp, SPlayerState::timestamp, CBookmark::totalTimeInSeconds, CDVDMsgPlayerSeek::CMode::trickplay, UpdateFileItemStreamDetails(), VideoPlayer_AUDIO, VideoPlayer_VIDEO, and Wait().
Referenced by Process().
HandlePlaySpeed()
void CVideoPlayer::HandlePlaySpeed () protected
References IDVDStreamPlayerVideo::AcceptsData(), IDVDStreamPlayerAudio::AcceptsData(), CDVDMsgPlayerSeek::CMode::accurate, CCurrentStream::AV_SYNC_CONT, CCurrentStream::AV_SYNC_NONE, CCurrentStream::avsync, CDVDMsgPlayerSeek::CMode::backward, CACHESTATE_DONE, CACHESTATE_FULL, CACHESTATE_INIT, CACHESTATE_PLAY, CCurrentStream::cachetime, CCurrentStream::cachetotal, SPlayerState::cantempo, CDVDClock::Discontinuity(), SPlayerState::dts, DVD_MSEC_TO_TIME(), DVD_NOPTS_VALUE, DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, FLAG_STILL_IMAGES, CDVDStreamInfo::flags, FlushBuffers(), CPlayerOptions::fullscreen, CDVDMsg::GENERAL_RESYNC, CDVDClock::GetAbsoluteClock(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppMessenger(), GetCachingTimes(), CDVDClock::GetClock(), IDVDStreamPlayerVideo::GetCurrentPts(), IDVDStreamPlayerAudio::GetLevel(), CDVDClock::GetSpeedAdjust(), GetTime(), GetUpdatedTime(), CCurrentStream::hint, CCurrentStream::id, CCurrentStream::inited, IsInMenuInternal(), IDVDStreamPlayerVideo::IsRewindStalled(), IDVDStreamPlayerVideo::IsStalled(), IDVDStreamPlayerAudio::IsStalled(), CVideoPlayer::SSpeedState::lastabstime, CVideoPlayer::SSpeedState::lastpts, CVideoPlayer::SSpeedState::lastseekpts, CVideoPlayer::SSpeedState::lasttime, CacheInfo::level, CLog::Log(), LOGDEBUG, LOGWARNING, m_caching, m_cachingTimer, IPlayer::m_callback, m_clock, m_CurrentAudio, m_CurrentVideo, m_item, m_messageQueueTimeSize, m_messenger, m_outboundEvents, m_pInputStream, m_playerOptions, m_playSpeed, m_processInfo, m_SpeedState, m_State, m_syncTimer, m_VideoPlayerAudio, m_VideoPlayerVideo, IPlayerCallback::OnAVStarted(), CCurrentStream::packets, ANNOUNCEMENT::Player, CDVDMessageQueue::Put(), CDVDMsgPlayerSeek::CMode::restore, IDVDStreamPlayerVideo::SendMessage(), IDVDStreamPlayerAudio::SendMessage(), SetCaching(), SetPlaySpeed(), CDVDClock::SetSpeedAdjust(), SetTempo(), CCurrentStream::starttime, SPlayerState::streamsReady, CDVDMsgPlayerSeek::CMode::sync, IDVDStreamPlayer::SYNC_INSYNC, IDVDStreamPlayer::SYNC_STARTING, IDVDStreamPlayer::SYNC_WAITSYNC, CCurrentStream::syncState, CDVDMsgPlayerSeek::CMode::time, CacheInfo::time, SPlayerState::time_offset, TMSG_SWITCHTOFULLSCREEN, CDVDMsgPlayerSeek::CMode::trickplay, UpdatePlayState(), and CacheInfo::valid.
Referenced by Process().
HasAudio()
bool CVideoPlayer::HasAudio () const override virtual
Implements IPlayer.
References m_HasAudio.
HasID3()
bool CVideoPlayer::HasID3 () const override virtual
Reimplemented from IPlayer.
References CCurrentStream::id, and m_CurrentAudioID3.
HasRDS()
bool CVideoPlayer::HasRDS () const override virtual
Reimplemented from IPlayer.
References CCurrentStream::id, and m_CurrentRadioRDS.
HasTeletextCache()
bool CVideoPlayer::HasTeletextCache () const override virtual
Reimplemented from IPlayer.
References CCurrentStream::id, and m_CurrentTeletext.
HasVideo()
bool CVideoPlayer::HasVideo () const override virtual
Implements IPlayer.
References m_HasVideo.
IsBetterStream()
bool CVideoPlayer::IsBetterStream (const CCurrentStream & current, CDemuxStream * stream) protected
References CDemuxStream::demuxerId, CCurrentStream::demuxerId, CDemuxStream::disabled, CDemuxStream::dvdNavId, DVDSTREAM_TYPE_BLURAY, DVDSTREAM_TYPE_DVD, CCurrentStream::id, CVideoPlayer::SDVDInfo::iSelectedAudioStream, CVideoPlayer::SDVDInfo::iSelectedSPUStream, m_dvd, m_pInputStream, m_playerOptions, CDemuxStream::source, CCurrentStream::source, STREAM_AUDIO, STREAM_SOURCE_DEMUX, STREAM_SOURCE_MASK, STREAM_SOURCE_NONE, STREAM_SUBTITLE, STREAM_VIDEO, CDemuxStream::type, CCurrentStream::type, CDemuxStream::uniqueId, and CPlayerOptions::videoOnly.
Referenced by CheckBetterStream().
IsCaching()
bool CVideoPlayer::IsCaching () const override virtual
Reimplemented from IPlayer.
References SPlayerState::caching, SPlayerState::isInMenu, m_State, and m_StateSection.
IsInMenu()
bool CVideoPlayer::IsInMenu () const override virtual
Reimplemented from IPlayer.
References SPlayerState::isInMenu, m_State, and m_StateSection.
Referenced by SetSpeed().
IsInMenuInternal()
bool CVideoPlayer::IsInMenuInternal () const protected
References DVDSTATE_STILL, m_dvd, m_pInputStream, and CVideoPlayer::SDVDInfo::state.
Referenced by HandlePlaySpeed(), OnDiscNavResult(), Process(), and UpdatePlayState().
IsPassthrough()
bool CVideoPlayer::IsPassthrough () const override virtual
Reimplemented from IPlayer.
References IDVDStreamPlayerAudio::IsPassthrough(), and m_VideoPlayerAudio.
IsPlaying()
bool CVideoPlayer::IsPlaying () const override virtual
Reimplemented from IPlayer.
References CThread::m_bStop.
Referenced by SetPlaySpeed().
IsRenderingVideo()
bool CVideoPlayer::IsRenderingVideo () const override virtual
Reimplemented from IPlayer.
References CRenderManager::IsConfigured(), and m_renderManager.
IsValidStream()
bool CVideoPlayer::IsValidStream (const CCurrentStream & stream) protected
References CCurrentStream::demuxerId, CDemuxStream::disabled, CDemuxStream::dvdNavId, DVDSTREAM_TYPE_DVD, CCurrentStream::id, CVideoPlayer::SDVDInfo::iSelectedAudioStream, CVideoPlayer::SDVDInfo::iSelectedSPUStream, m_dvd, m_pCCDemuxer, m_pDemuxer, m_pInputStream, m_pSubtitleDemuxer, CCurrentStream::source, STREAM_AUDIO, STREAM_SOURCE_DEMUX, STREAM_SOURCE_DEMUX_SUB, STREAM_SOURCE_MASK, STREAM_SOURCE_TEXT, STREAM_SOURCE_VIDEOMUX, STREAM_SUBTITLE, CDemuxStream::type, and CCurrentStream::type.
Referenced by CheckBetterStream().
LoadPage()
void CVideoPlayer::LoadPage (int p, int sp, unsigned char * buffer) override virtual
Reimplemented from IPlayer.
References CCurrentStream::id, CDVDTeletextData::LoadPage(), m_CurrentTeletext, and m_VideoPlayerTeletext.
OnAction()
bool CVideoPlayer::OnAction (const CAction & action) override virtual
Reimplemented from IPlayer.
References ACTION_MOUSE_LEFT_CLICK, ACTION_MOUSE_MOVE, ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NAV_BACK, ACTION_NEXT_ITEM, ACTION_PLAYER_DEBUG, ACTION_PLAYER_DEBUG_VIDEO, ACTION_PLAYER_PROCESS_INFO, ACTION_PREV_ITEM, ACTION_PREVIOUS_MENU, ACTION_SELECT_ITEM, ACTION_SHOW_VIDEOMENU, ACTION_TOGGLE_COMMSKIP, ACTION_TRIGGER_OSD, BACKWARD, DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, DVDSTATE_STILL, DVDSTREAM_TYPE_DVD, FORWARD, CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppMessenger(), GetChapter(), GetChapterCount(), GetPreviousChapter(), CRenderManager::GetVideoRect(), CRectGen< T >::Height(), CVideoPlayer::SDVDInfo::iDVDStillStartTime, CVideoPlayer::SDVDInfo::iDVDStillTime, LIBDVDNAV_BUTTON_CLICKED, CLog::Log(), LOGDEBUG, IPlayer::m_callback, m_dvd, m_messenger, m_pInputStream, m_playSpeed, m_processInfo, m_renderManager, m_SkipCommercials, m_VideoPlayerSubtitle, IPlayerCallback::OnPlayBackResumed(), ANNOUNCEMENT::Player, CRectGen< T >::PtInRect(), CDVDMessageQueue::Put(), REMOTE_0, REMOTE_1, REMOTE_2, REMOTE_3, REMOTE_4, REMOTE_5, REMOTE_6, REMOTE_7, REMOTE_8, REMOTE_9, SeekScene(), SetPlaySpeed(), CVideoPlayer::SDVDInfo::state, THREAD_ACTION, TMSG_GUI_ACTION, CRenderManager::ToggleDebug(), CRenderManager::ToggleDebugVideo(), CVideoPlayerSubtitle::UpdateOverlayInfo(), CRectGen< T >::Width(), WINDOW_INVALID, CPointGen< T >::x, CRectGen< T >::x1, CPointGen< T >::y, and CRectGen< T >::y1.
Referenced by HandleMessages().
OnDiscNavResult()
int CVideoPlayer::OnDiscNavResult (void * pData, int iMessage) override virtual
Implements IVideoPlayer.
References CDVDStreamInfo::aspect, BD_EVENT_ENC_ERROR, BD_EVENT_MENU_ERROR, BD_EVENT_MENU_OVERLAY, CDVDOverlayContainer::Clear(), CSelectionStreams::Clear(), DVD_NOPTS_VALUE, DVD_TIME_BASE, DVDNAV_AUDIO_STREAM_CHANGE, DVDNAV_CELL_CHANGE, DVDNAV_ERROR, DVDNAV_HIGHLIGHT, DVDNAV_HOP_CHANNEL, DVDNAV_NAV_PACKET, DVDNAV_SPU_CLUT_CHANGE, DVDNAV_SPU_STREAM_CHANGE, DVDNAV_STILL_FRAME, DVDNAV_STOP, DVDNAV_VTS_CHANGE, DVDSTATE_NORMAL, DVDSTATE_SEEK, DVDSTATE_STILL, DVDSTREAM_TYPE_BLURAY, DVDSTREAM_TYPE_DVD, IDVDStreamPlayerVideo::EnableSubtitle(), FlushBuffers(), CDVDMsg::GENERAL_FLUSH, CServiceBroker::GetAnnouncementManager(), IDVDStreamPlayerVideo::GetOutputDelay(), CCurrentStream::hint, CVideoPlayer::SDVDInfo::iDVDStillStartTime, CVideoPlayer::SDVDInfo::iDVDStillTime, CVideoPlayer::SDVDInfo::iSelectedAudioStream, CVideoPlayer::SDVDInfo::iSelectedSPUStream, IDVDStreamPlayerVideo::IsInited(), IsInMenuInternal(), dvdnav_still_event_t::length, LIBDVDNAV_BUTTON_NORMAL, CLog::Log(), LOGDEBUG, m_CurrentAudio, m_CurrentSubtitle, m_CurrentVideo, m_dvd, m_messenger, m_overlayContainer, m_pDemuxer, m_pInputStream, m_SelectionStreams, m_VideoPlayerSubtitle, m_VideoPlayerVideo, NAVRESULT_ERROR, NAVRESULT_HOLD, NAVRESULT_NOP, dvdnav_spu_stream_change_event_t::physical_wide, ANNOUNCEMENT::Player, CDVDOverlayContainer::ProcessAndAddOverlayIfValid(), CDVDMessageQueue::Put(), CVideoPlayerSubtitle::SendMessage(), IDVDStreamPlayerVideo::SendMessage(), SetSubtitleVisibleInternal(), CVideoPlayer::SDVDInfo::state, CCurrentStream::stream, STREAM_NONE, STREAM_SOURCE_NAV, CVideoPlayer::SDVDInfo::syncClock, CSelectionStreams::Update(), UpdateContent(), CVideoPlayerSubtitle::UpdateOverlayInfo(), UpdatePlayState(), and CDVDMsg::VIDEO_SET_ASPECT.
OnExit()
void CVideoPlayer::OnExit () override protected virtual
Reimplemented from CThread.
References CACHESTATE_DONE, CSelectionStreams::Clear(), CFFmpegLog::ClearLogLevel(), CloseStream(), CDVDMessageQueue::End(), CRenderManager::Flush(), GetPlayerState(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGINFO, m_bAbortRequest, m_bCloseRequest, CThread::m_bStop, IPlayer::m_callback, m_CurrentAudio, m_CurrentAudioID3, m_CurrentRadioRDS, m_CurrentSubtitle, m_CurrentTeletext, m_CurrentVideo, m_error, m_item, m_messenger, IPlayer::m_name, m_outboundEvents, m_pCCDemuxer, m_pDemuxer, m_pInputStream, m_processInfo, m_pSubtitleDemuxer, m_renderManager, m_SelectionStreams, m_State, m_subtitleDemuxerMap, IPlayerCallback::OnPlayBackEnded(), IPlayerCallback::OnPlayBackError(), IPlayerCallback::OnPlayBackStopped(), IPlayerCallback::OnPlayerCloseFile(), CBookmark::player, CBookmark::playerState, SetCaching(), SPlayerState::startTime, IPlayerCallback::StoreVideoSettings(), STREAM_NONE, STREAM_SOURCE_NONE, SPlayerState::time, CBookmark::timeInSeconds, SPlayerState::timeMax, CBookmark::totalTimeInSeconds, CWinSystemBase::UnregisterRenderLoop(), and UpdateFileItemStreamDetails().
OnLostDisplay()
void CVideoPlayer::OnLostDisplay () override virtual
Reimplemented from IDispResource.
References FlushRenderer(), CDVDMsg::GENERAL_PAUSE, IDVDStreamPlayerVideo::IsInited(), IDVDStreamPlayerAudio::IsInited(), CLog::Log(), LOGINFO, m_clock, m_displayLost, m_VideoPlayerAudio, m_VideoPlayerVideo, CDVDClock::Pause(), IDVDStreamPlayerVideo::SendMessage(), and IDVDStreamPlayerAudio::SendMessage().
OnResetDisplay()
void CVideoPlayer::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References CDVDMsg::GENERAL_PAUSE, CLog::Log(), LOGINFO, m_clock, m_displayLost, m_VideoPlayerAudio, m_VideoPlayerVideo, CDVDClock::Pause(), CDVDMsg::PLAYER_DISPLAY_RESET, IDVDStreamPlayerVideo::SendMessage(), and IDVDStreamPlayerAudio::SendMessage().
OnStartup()
void CVideoPlayer::OnStartup () override protected virtual
Reimplemented from CThread.
References CCurrentStream::Clear(), KODI::UTILS::FONT::ClearTemporaryFonts(), m_CurrentAudio, m_CurrentAudioID3, m_CurrentRadioRDS, m_CurrentSubtitle, m_CurrentTeletext, and m_CurrentVideo.
OpenAudioID3Stream()
bool CVideoPlayer::OpenAudioID3Stream (CDVDStreamInfo & hint) protected
References GetStreamPlayer(), CCurrentStream::hint, CCurrentStream::id, m_CurrentAudioID3, m_VideoPlayerAudioID3, IDVDStreamPlayer::OpenStream(), and CCurrentStream::player.
Referenced by OpenStream().
OpenAudioStream()
bool CVideoPlayer::OpenAudioStream (CDVDStreamInfo & hint, bool reset = true) protected
References CDVDMsg::GENERAL_PAUSE, CDVDMsg::GENERAL_RESET, GetStreamPlayer(), CCurrentStream::hint, CCurrentStream::id, m_CurrentAudio, m_displayLost, m_HasAudio, m_streamPlayerSpeed, IDVDStreamPlayer::OpenStream(), CCurrentStream::packets, CCurrentStream::player, CDVDMsg::PLAYER_REQUEST_STATE, SendMessage(), IDVDStreamPlayer::SendMessage(), SetSpeed(), IDVDStreamPlayer::SYNC_STARTING, and CCurrentStream::syncState.
Referenced by OpenStream().
OpenDefaultStreams()
void CVideoPlayer::OpenDefaultStreams (bool reset = true) protected
References CloseStream(), CCurrentStream::demuxerId, FLAG_FORCED, CSelectionStreams::Get(), GetAudioStream(), CCurrentStream::id, CVideoPlayer::SDVDInfo::iSelectedAudioStream, CVideoPlayer::SDVDInfo::iSelectedSPUStream, KODI::NETWORK::IsRemote(), SelectionStream::language, m_CurrentAudio, m_CurrentAudioID3, m_CurrentRadioRDS, m_CurrentSubtitle, m_CurrentTeletext, m_CurrentVideo, m_dvd, m_item, m_pDemuxer, m_pInputStream, m_playerOptions, m_processInfo, m_SelectionStreams, CSelectionStreams::m_Streams, OpenStream(), CPlayerOptions::preferStereo, PredicateSubtitlePriority::relevant(), SetEnableStream(), SetSubtitleVisibleInternal(), CCurrentStream::source, CPlayerOptions::state, STREAM_AUDIO, STREAM_AUDIO_ID3, STREAM_RADIO_RDS, STREAM_SOURCE_DEMUX, STREAM_SOURCE_MASK, STREAM_SOURCE_VIDEOMUX, STREAM_SUBTITLE, STREAM_TELETEXT, STREAM_VIDEO, and CPlayerOptions::videoOnly.
Referenced by CheckStreamChanges(), Prepare(), Process(), and ReadPacket().
OpenDemuxStream()
bool CVideoPlayer::OpenDemuxStream () protected
References CSelectionStreams::Clear(), CloseDemuxer(), CDVDFactoryDemuxer::CreateDemuxer(), DVD_PLAYSPEED_NORMAL, DVDSTREAM_TYPE_PVRMANAGER, int64_t(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, CThread::m_bStop, m_demuxerSpeed, m_offset_pts, m_pDemuxer, m_pInputStream, m_processInfo, m_programs, m_SelectionStreams, CDVDInputStream::NEXTSTREAM_NONE, STREAM_NONE, STREAM_SOURCE_DEMUX, STREAM_SOURCE_NAV, CSelectionStreams::Update(), and UpdateContent().
Referenced by Prepare(), and Process().
OpenFile()
bool CVideoPlayer::OpenFile (const CFileItem & file, const CPlayerOptions & options) override virtual
Reimplemented from IPlayer.
References CThread::Create(), CDVDMessageQueue::Init(), CThread::IsRunning(), CLog::Log(), LOGINFO, m_bAbortRequest, m_bCloseRequest, IPlayer::m_callback, m_error, CDVDMsgOpenFile::FileParams::m_item, m_item, m_messenger, CDVDMsgOpenFile::FileParams::m_options, m_playerOptions, m_processInfo, m_renderManager, IPlayerCallback::OnPlayBackStarted(), CRenderManager::PreInit(), CDVDMessageQueue::Put(), and CFileItem::SetMimeTypeForInternetFile().
OpenInputStream()
bool CVideoPlayer::OpenInputStream () protected
References AddSubtitleFile(), CVariant::asBoolean(), CVariant::asString(), CVideoPlayer::SDVDInfo::Clear(), CDVDFactoryInputStream::CreateInputStream(), DVDSTREAM_TYPE_DVD, DVDSTREAM_TYPE_PVRMANAGER, CUtil::FindVobSubPair(), CFileItem::GetDynPath(), CFileItem::GetPath(), CGUIListItem::GetProperty(), URIUtils::HasExtension(), CGUIListItem::HasProperty(), URIUtils::IsUPnP(), CUtil::IsVobSub(), CLog::Log(), LOGERROR, LOGINFO, m_clock, m_dvd, m_item, m_pInputStream, CDVDClock::Reset(), and CUtil::ScanForExternalSubtitles().
Referenced by Prepare(), and Process().
OpenRadioRDSStream()
bool CVideoPlayer::OpenRadioRDSStream (CDVDStreamInfo & hint) protected
References CDVDRadioRDSData::CheckStream(), GetStreamPlayer(), CCurrentStream::hint, CCurrentStream::id, m_CurrentRadioRDS, m_VideoPlayerRadioRDS, IDVDStreamPlayer::OpenStream(), and CCurrentStream::player.
Referenced by OpenStream().
OpenStream()
bool CVideoPlayer::OpenStream (CCurrentStream & current, int64_t demuxerId, int iStream, int source, bool reset = true) protected
References CDVDStreamInfo::Assign(), CCurrentStream::AV_SYNC_CHECK, CCurrentStream::AV_SYNC_FORCE, CCurrentStream::avsync, CDemuxStream::changes, CCurrentStream::changes, CDVDStreamInfo::Clear(), CCurrentStream::demuxerId, CDemuxStream::disabled, CCurrentStream::dts, DVD_NOPTS_VALUE, DVD_TIME_BASE, DVDSTREAM_TYPE_DVD, CDVDStreamInfo::filename, SelectionStream::filename, CDVDStreamInfo::fpsrate, CDVDStreamInfo::fpsscale, CSelectionStreams::Get(), IDVDStreamPlayerVideo::GetCurrentPts(), CServiceBroker::GetDataCacheCore(), CCurrentStream::hint, CCurrentStream::id, index(), CCurrentStream::lastdts, CLog::Log(), LOGDEBUG, LOGINFO, LOGWARNING, m_CurrentVideo, m_offset_pts, m_pCCDemuxer, m_pDemuxer, m_pInputStream, m_pSubtitleDemuxer, m_SelectionStreams, m_subtitleDemuxerMap, m_VideoPlayerVideo, OpenAudioID3Stream(), OpenAudioStream(), OpenRadioRDSStream(), OpenSubtitleStream(), OpenTeletextStream(), OpenVideoStream(), CDataCacheCore::SignalAudioInfoChange(), CDataCacheCore::SignalSubtitleInfoChange(), CDataCacheCore::SignalVideoInfoChange(), CCurrentStream::source, CCurrentStream::stream, STREAM_AUDIO, STREAM_AUDIO_ID3, STREAM_RADIO_RDS, STREAM_SOURCE_DEMUX, STREAM_SOURCE_DEMUX_SUB, STREAM_SOURCE_MASK, STREAM_SOURCE_TEXT, STREAM_SOURCE_VIDEOMUX, STREAM_SUBTITLE, STREAM_TELETEXT, STREAM_VIDEO, CCurrentStream::type, CSelectionStreams::TypeIndexOf(), CDemuxStream::uniqueId, and UpdateContentState().
Referenced by AdaptForcedSubtitles(), CheckBetterStream(), HandleMessages(), and OpenDefaultStreams().
OpenSubtitleStream()
bool CVideoPlayer::OpenSubtitleStream (const CDVDStreamInfo & hint) protected
References GetStreamPlayer(), CCurrentStream::hint, CCurrentStream::id, m_CurrentSubtitle, IDVDStreamPlayer::OpenStream(), and CCurrentStream::player.
Referenced by OpenStream().
OpenTeletextStream()
bool CVideoPlayer::OpenTeletextStream (CDVDStreamInfo & hint) protected
References CDVDTeletextData::CheckStream(), GetStreamPlayer(), CCurrentStream::hint, CCurrentStream::id, m_CurrentTeletext, m_VideoPlayerTeletext, IDVDStreamPlayer::OpenStream(), and CCurrentStream::player.
Referenced by OpenStream().
OpenVideoStream()
bool CVideoPlayer::OpenVideoStream (CDVDStreamInfo & hint, bool reset = true) protected
References ADJUST_REFRESHRATE_OFF, CDVDStreamInfo::aspect, CResolutionUtils::ChooseBestResolution(), CEdl::Clear(), CSelectionStreams::Clear(), CDVDStreamInfo::codec, CStereoscopicsManager::DetectStereoModeByString(), CDVDStreamInfo::dvd, DVD_TIME_BASE, DVDSTREAM_TYPE_DVD, DVDSTREAM_TYPE_PVRMANAGER, CDVDStreamInfo::flags, CDVDStreamInfo::forced_aspect, CDVDStreamInfo::fpsrate, CDVDStreamInfo::fpsscale, CPlayerOptions::fullscreen, CDVDMsg::GENERAL_PAUSE, CDVDMsg::GENERAL_RESET, CEdl::GetCutMarkers(), CServiceBroker::GetDataCacheCore(), CEdl::GetEditList(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CFileItem::GetPath(), CEdl::GetSceneMarkers(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetStereoscopicsManager(), GetStreamPlayer(), CServiceBroker::GetWinSystem(), CDVDStreamInfo::height, CCurrentStream::hint, CCurrentStream::id, CDVDStreamInfo::interlaced, CGraphicContext::IsFullScreenRoot(), m_CurrentVideo, m_displayLost, m_Edl, m_HasVideo, m_item, m_pCCDemuxer, m_pInputStream, m_playerOptions, m_renderManager, m_SelectionStreams, m_streamPlayerSpeed, CDVDCodecUtils::NormalizeFrameduration(), IDVDStreamPlayer::OpenStream(), CCurrentStream::packets, CCurrentStream::player, CDVDMsg::PLAYER_REQUEST_STATE, CEdl::ReadEditDecisionLists(), SendMessage(), IDVDStreamPlayer::SendMessage(), CDataCacheCore::SetCuts(), CDataCacheCore::SetEditList(), CDataCacheCore::SetSceneMarkers(), SetSpeed(), CSettings::SETTING_PVRPLAYBACK_FPS, CSettings::SETTING_VIDEOPLAYER_ADJUSTREFRESHRATE, CGraphicContext::SetVideoResolution(), CDVDStreamInfo::stereo_mode, CDVDStreamInfo::stills, STREAM_NONE, STREAM_SOURCE_VIDEOMUX, IDVDStreamPlayer::SYNC_STARTING, CCurrentStream::syncState, CRenderManager::TriggerUpdateResolution(), and CDVDStreamInfo::width.
Referenced by OpenStream().
Pause()
void CVideoPlayer::Pause () override virtual
Implements IPlayer.
References m_processInfo, and SetSpeed().
Prepare()
void CVideoPlayer::Prepare () protected
References CACHESTATE_FLUSH, CDVDStreamInfo::Clear(), SPlayerState::Clear(), EDL::COMM_BREAK, CreatePlayers(), EDL::CUT, CDVDClock::Discontinuity(), DVD_MSEC_TO_TIME(), DVD_NOPTS_VALUE, DVD_PLAYSPEED_NORMAL, FlushBuffers(), CServiceBroker::GetAnnouncementManager(), CEdl::GetTimeAfterRestoringCuts(), CCurrentStream::hint, CEdl::InEdit(), CCurrentStream::lastdts, CLog::Log(), LOGDEBUG, LOGINFO, m_bAbortRequest, IPlayer::m_callback, m_clock, m_CurrentAudio, m_CurrentAudioID3, m_CurrentRadioRDS, m_CurrentSubtitle, m_CurrentTeletext, m_CurrentVideo, m_Edl, m_error, m_item, m_offset_pts, m_outboundEvents, m_pDemuxer, m_pInputStream, m_playerOptions, m_processInfo, m_pSubtitleDemuxer, m_SkipCommercials, m_SpeedState, m_State, OpenDefaultStreams(), OpenDemuxStream(), OpenInputStream(), ANNOUNCEMENT::Player, IPlayerCallback::RequestVideoSettings(), CVideoPlayer::SSpeedState::Reset(), SetCaching(), CEdl::SetLastEditActionType(), CEdl::SetLastEditTime(), CFFmpegLog::SetLogLevel(), SetPlaySpeed(), CPlayerOptions::startpercent, CPlayerOptions::starttime, CPlayerOptions::state, TIME_FORMAT_MM_SS, and UpdatePlayState().
Referenced by HandleMessages(), and Process().
Process()
void CVideoPlayer::Process (void) override protected virtual
Reimplemented from CThread.
References IDVDStreamPlayerVideo::AcceptsData(), IDVDStreamPlayerAudio::AcceptsData(), CACHESTATE_DONE, CheckAutoSceneSkip(), CheckBetterStream(), CheckIsCurrent(), CCurrentStream::Clear(), CSelectionStreams::Clear(), CloseDemuxer(), CloseStream(), CSelectionStreams::CountTypeOfSource(), CDVDClock::Discontinuity(), DEMUX_PACKET::dts, DVD_NOPTS_VALUE, DVD_PLAYSPEED_PAUSE, DVDSTATE_NORMAL, DVDSTATE_STILL, DVDSTREAM_TYPE_PVRMANAGER, CDVDDemuxUtils::FreeDemuxPacket(), CDVDClock::GetClock(), IDVDStreamPlayerAudio::GetLevel(), CServiceBroker::GetSettingsComponent(), IDVDStreamPlayerVideo::GetSubtitleDelay(), CServiceBroker::GetWinSystem(), HandleMessages(), HandlePlaySpeed(), IDVDStreamPlayerVideo::HasData(), IDVDStreamPlayerAudio::HasData(), CCurrentStream::id, CVideoPlayer::SDVDInfo::iDVDStillStartTime, CVideoPlayer::SDVDInfo::iDVDStillTime, CCurrentStream::inited, IsInMenuInternal(), DEMUX_PACKET::iStreamId, CLog::Log(), LOGINFO, m_bAbortRequest, m_clock, m_CurrentAudio, m_CurrentAudioID3, m_CurrentRadioRDS, m_CurrentSubtitle, m_CurrentTeletext, m_CurrentVideo, m_demuxerSpeed, m_displayLost, m_dvd, m_item, m_pCCDemuxer, m_pDemuxer, m_pInputStream, m_playSpeed, m_processInfo, m_SelectionStreams, m_State, CSelectionStreams::m_Streams, m_VideoPlayerAudio, m_VideoPlayerSubtitle, m_VideoPlayerVideo, CDVDInputStream::NEXTSTREAM_NONE, CDVDInputStream::NEXTSTREAM_OPEN, CDVDInputStream::NEXTSTREAM_RETRY, OpenDefaultStreams(), OpenDemuxStream(), OpenInputStream(), Prepare(), CVideoPlayerSubtitle::Process(), ProcessPacket(), ProcessSubData(), DEMUX_PACKET::pts, ReadPacket(), CWinSystemBase::RegisterRenderLoop(), IDVDStreamPlayerVideo::SendMessage(), SetCaching(), CFileItem::SetMimeTypeForInternetFile(), CSettings::SETTING_SUBTITLES_PARSECAPTIONS, CThread::Sleep(), CCurrentStream::source, CVideoPlayer::SDVDInfo::state, STREAM_SOURCE_VIDEOMUX, STREAM_SUBTITLE, CVideoPlayer::SDVDInfo::syncClock, SPlayerState::time_offset, CSelectionStreams::Update(), UpdateContent(), UpdatePlayState(), and CDVDMsg::VIDEO_DRAIN.
ProcessAudioData()
void CVideoPlayer::ProcessAudioData (CDemuxStream * pStream, DemuxPacket * pPacket) protected
References CCurrentStream::AV_SYNC_CHECK, CCurrentStream::AV_SYNC_NONE, CCurrentStream::avsync, CheckContinuity(), CheckPlayerInit(), CheckSceneSkip(), CheckStreamChanges(), CCurrentStream::dts, DVD_TIME_TO_MSEC(), CEdl::InEdit(), m_CurrentAudio, m_Edl, m_offset_pts, m_VideoPlayerAudio, EDL::MUTE, CCurrentStream::packets, IDVDStreamPlayerAudio::SendMessage(), and UpdateTimestamps().
Referenced by ProcessPacket().
ProcessAudioID3Data()
void CVideoPlayer::ProcessAudioID3Data (CDemuxStream * pStream, DemuxPacket * pPacket) protected
References CheckPlayerInit(), CheckSceneSkip(), CheckStreamChanges(), m_CurrentAudioID3, m_VideoPlayerAudioID3, and UpdateTimestamps().
Referenced by ProcessPacket().
ProcessPacket()
void CVideoPlayer::ProcessPacket (CDemuxStream * pStream, DemuxPacket * pPacket) protected
References CheckIsCurrent(), CDVDDemuxUtils::FreeDemuxPacket(), m_CurrentAudio, m_CurrentAudioID3, m_CurrentRadioRDS, m_CurrentSubtitle, m_CurrentTeletext, m_CurrentVideo, ProcessAudioData(), ProcessAudioID3Data(), ProcessRadioRDSData(), ProcessSubData(), ProcessTeletextData(), and ProcessVideoData().
Referenced by Process().
ProcessRadioRDSData()
void CVideoPlayer::ProcessRadioRDSData (CDemuxStream * pStream, DemuxPacket * pPacket) protected
References CheckPlayerInit(), CheckSceneSkip(), CheckStreamChanges(), m_CurrentRadioRDS, m_VideoPlayerRadioRDS, CDVDRadioRDSData::SendMessage(), and UpdateTimestamps().
Referenced by ProcessPacket().
ProcessSubData()
void CVideoPlayer::ProcessSubData (CDemuxStream * pStream, DemuxPacket * pPacket) protected
References CheckPlayerInit(), CheckSceneSkip(), CheckStreamChanges(), DVDSTREAM_TYPE_DVD, LIBDVDNAV_BUTTON_NORMAL, m_CurrentSubtitle, m_pInputStream, m_VideoPlayerSubtitle, CVideoPlayerSubtitle::SendMessage(), CVideoPlayerSubtitle::UpdateOverlayInfo(), and UpdateTimestamps().
Referenced by Process(), and ProcessPacket().
ProcessTeletextData()
void CVideoPlayer::ProcessTeletextData (CDemuxStream * pStream, DemuxPacket * pPacket) protected
References CheckPlayerInit(), CheckSceneSkip(), CheckStreamChanges(), m_CurrentTeletext, m_VideoPlayerTeletext, CDVDTeletextData::SendMessage(), and UpdateTimestamps().
Referenced by ProcessPacket().
ProcessVideoData()
void CVideoPlayer::ProcessVideoData (CDemuxStream * pStream, DemuxPacket * pPacket) protected
References CCurrentStream::AV_SYNC_CHECK, CCurrentStream::AV_SYNC_NONE, CCurrentStream::avsync, CheckContinuity(), CheckPlayerInit(), CheckSceneSkip(), CheckStreamChanges(), DEMUX_PACKET::iSize, m_CurrentVideo, m_VideoPlayerVideo, CCurrentStream::packets, IDVDStreamPlayerVideo::SendMessage(), and UpdateTimestamps().
Referenced by ProcessPacket().
ReadPacket()
bool CVideoPlayer::ReadPacket (DemuxPacket *& packet, CDemuxStream *& stream) protected
References CVideoPlayerSubtitle::AcceptsData(), CSelectionStreams::Clear(), DEMUX_PACKET::demuxerId, DMX_SPECIALID_STREAMCHANGE, CCurrentStream::id, DEMUX_PACKET::iStreamId, CLog::Log(), LOGERROR, m_CurrentAudio, m_CurrentVideo, m_HasAudio, m_HasVideo, m_offset_pts, m_pDemuxer, m_pInputStream, m_programs, m_pSubtitleDemuxer, m_SelectionStreams, m_VideoPlayerSubtitle, OpenDefaultStreams(), CDemuxStream::source, STREAM_NONE, STREAM_SOURCE_DEMUX, STREAM_SOURCE_DEMUX_SUB, STREAM_SOURCE_NONE, CSelectionStreams::Update(), UpdateContent(), and UpdateCorrection().
Referenced by Process().
Render()
void CVideoPlayer::Render (bool clear, uint32_t alpha = 255, bool gui = true) override virtual
hook into render loop of render thread
Reimplemented from IPlayer.
References m_renderManager, and CRenderManager::Render().
RenderCapture()
void CVideoPlayer::RenderCapture (unsigned int captureId, unsigned int width, unsigned int height, int flags) override virtual
Reimplemented from IPlayer.
References m_renderManager, and CRenderManager::StartRenderCapture().
RenderCaptureAlloc()
unsigned int CVideoPlayer::RenderCaptureAlloc () override virtual
Reimplemented from IPlayer.
References CRenderManager::AllocRenderCapture(), and m_renderManager.
RenderCaptureGetPixels()
bool CVideoPlayer::RenderCaptureGetPixels (unsigned int captureId, unsigned int millis, uint8_t * buffer, unsigned int size) override virtual
Reimplemented from IPlayer.
References m_renderManager, and CRenderManager::RenderCaptureGetPixels().
RenderCaptureRelease()
void CVideoPlayer::RenderCaptureRelease (unsigned int captureId) override virtual
Reimplemented from IPlayer.
References m_renderManager, and CRenderManager::ReleaseRenderCapture().
Seek()
void CVideoPlayer::Seek (bool bPlus, bool bLargeStep, bool bChapterOverride) override virtual
Implements IPlayer.
References CDVDMsgPlayerSeek::CMode::accurate, CDVDMsgPlayerSeek::CMode::backward, SPlayerState::canseek, g_application, GetChapter(), GetChapterCount(), GetPercentage(), GetPreviousChapter(), CServiceBroker::GetSettingsComponent(), GetTime(), int64_t(), IPlayer::m_callback, m_messenger, m_processInfo, m_State, IPlayerCallback::OnPlayBackSeek(), CDVDMessageQueue::Put(), CDVDMsgPlayerSeek::CMode::restore, SeekChapter(), CDVDMsgPlayerSeek::CMode::sync, SynchronizeDemuxer(), CDVDMsgPlayerSeek::CMode::time, and CDVDMsgPlayerSeek::CMode::trickplay.
SeekChapter()
int CVideoPlayer::SeekChapter (int iChapter) override virtual
Reimplemented from IPlayer.
References GetChapter(), GetChapterCount(), m_messenger, CDVDMessageQueue::Put(), and SynchronizeDemuxer().
Referenced by Seek().
SeekPercentage()
void CVideoPlayer::SeekPercentage (float iPercent) override virtual
Reimplemented from IPlayer.
References int64_t(), m_processInfo, and SeekTime().
SeekScene()
bool CVideoPlayer::SeekScene (Direction seekDirection) override virtual
Reimplemented from IPlayer.
References CDVDMsgPlayerSeek::CMode::accurate, BACKWARD, CDVDMsgPlayerSeek::CMode::backward, CEdl::GetNextSceneMarker(), GetTime(), CEdl::HasSceneMarker(), m_Edl, m_messenger, CDVDMessageQueue::Put(), CDVDMsgPlayerSeek::CMode::restore, CDVDMsgPlayerSeek::CMode::sync, SynchronizeDemuxer(), CDVDMsgPlayerSeek::CMode::time, and CDVDMsgPlayerSeek::CMode::trickplay.
Referenced by OnAction().
SeekTime()
void CVideoPlayer::SeekTime (int64_t iTime) override virtual
Reimplemented from IPlayer.
References CDVDMsgPlayerSeek::CMode::accurate, CDVDMsgPlayerSeek::CMode::backward, GetTime(), int64_t(), IPlayer::m_callback, m_messenger, m_processInfo, IPlayerCallback::OnPlayBackSeek(), CDVDMessageQueue::Put(), CDVDMsgPlayerSeek::CMode::sync, SynchronizeDemuxer(), CDVDMsgPlayerSeek::CMode::time, and CDVDMsgPlayerSeek::CMode::trickplay.
Referenced by SeekPercentage(), and SeekTimeRelative().
SeekTimeRelative()
bool CVideoPlayer::SeekTimeRelative (int64_t iTime) override virtual
Reimplemented from IPlayer.
References CDVDMsgPlayerSeek::CMode::accurate, CDVDMsgPlayerSeek::CMode::backward, GetTime(), CEdl::HasCuts(), int64_t(), IPlayer::m_callback, m_Edl, m_messenger, m_processInfo, IPlayerCallback::OnPlayBackSeek(), CDVDMessageQueue::Put(), CDVDMsgPlayerSeek::CMode::relative, SeekTime(), CDVDMsgPlayerSeek::CMode::sync, CDVDMsgPlayerSeek::CMode::time, and CDVDMsgPlayerSeek::CMode::trickplay.
SendPlayerMessage()
void CVideoPlayer::SendPlayerMessage (std::shared_ptr< CDVDMsg > pMsg, unsigned int target) protected
References GetStreamPlayer(), and IDVDStreamPlayer::SendMessage().
SetAudioStream()
void CVideoPlayer::SetAudioStream (int iStream) override virtual
Reimplemented from IPlayer.
References m_messenger, m_processInfo, CDVDMessageQueue::Put(), and SynchronizeDemuxer().
SetAVDelay()
void CVideoPlayer::SetAVDelay (float fValue = 0.0f) override virtual
Reimplemented from IPlayer.
References m_processInfo, m_renderManager, and CRenderManager::SetDelay().
SetCaching()
void CVideoPlayer::SetCaching (ECacheState state) protected
References CACHESTATE_DONE, CACHESTATE_FLUSH, CACHESTATE_FULL, CACHESTATE_INIT, CACHESTATE_PLAY, DVD_PLAYSPEED_PAUSE, GetCachingTimes(), CLog::Log(), LOGDEBUG, m_caching, m_cachingTimer, m_clock, m_playSpeed, m_streamPlayerSpeed, m_VideoPlayerAudio, m_VideoPlayerVideo, CDVDClock::SetSpeed(), IDVDStreamPlayerVideo::SetSpeed(), IDVDStreamPlayerAudio::SetSpeed(), CDVDClock::SetSpeedAdjust(), and CacheInfo::valid.
Referenced by CloseStream(), FlushBuffers(), HandleMessages(), HandlePlaySpeed(), OnExit(), Prepare(), and Process().
SetDynamicRangeCompression()
void CVideoPlayer::SetDynamicRangeCompression (long drc) override virtual
Reimplemented from IPlayer.
References m_processInfo, m_VideoPlayerAudio, and IDVDStreamPlayerAudio::SetDynamicRangeCompression().
SetEnableStream()
void CVideoPlayer::SetEnableStream (CCurrentStream & current, bool isEnabled) protected
Propagate enable stream callbacks to demuxers.
Parameters
current The current stream
isEnabled Set to true to enable the stream, otherwise false
References CCurrentStream::demuxerId, CCurrentStream::id, m_pDemuxer, CCurrentStream::source, STREAM_SOURCE_DEMUX, and STREAM_SOURCE_MASK.
Referenced by AdaptForcedSubtitles(), CloseStream(), HandleMessages(), and OpenDefaultStreams().
SetPlayerState()
bool CVideoPlayer::SetPlayerState (const std::string & state) override virtual
Reimplemented from IPlayer.
References m_messenger, and CDVDMessageQueue::Put().
SetPlaySpeed()
void CVideoPlayer::SetPlaySpeed (int iSpeed) protected
one of the DVD_PLAYSPEED defines
References IsPlaying(), m_messenger, m_playSpeed, m_streamPlayerSpeed, and CDVDMessageQueue::Put().
Referenced by HandleMessages(), HandlePlaySpeed(), OnAction(), Prepare(), and SetSpeed().
SetProgram()
void CVideoPlayer::SetProgram (int progId) override virtual
Reimplemented from IPlayer.
References m_messenger, CDVDMsg::PLAYER_SET_PROGRAM, and CDVDMessageQueue::Put().
SetRenderViewMode()
void CVideoPlayer::SetRenderViewMode (int mode, float zoom, float par, float shift, bool stretch) override virtual
Reimplemented from IPlayer.
References m_processInfo, m_renderManager, CRenderManager::SetVideoSettings(), and CRenderManager::SetViewMode().
SetSpeed()
void CVideoPlayer::SetSpeed (float speed) override virtual
Implements IPlayer.
References CanPause(), CanSeek(), DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, IsInMenu(), IPlayer::m_callback, m_processInfo, IPlayerCallback::OnPlayBackPaused(), IPlayerCallback::OnPlayBackResumed(), SetPlaySpeed(), and SetTempo().
Referenced by OpenAudioStream(), OpenVideoStream(), and Pause().
SetSubtitle()
void CVideoPlayer::SetSubtitle (int iStream) override virtual
Reimplemented from IPlayer.
References m_messenger, m_processInfo, and CDVDMessageQueue::Put().
Referenced by HandleMessages().
SetSubTitleDelay()
void CVideoPlayer::SetSubTitleDelay (float fValue = 0.0f) override virtual
Reimplemented from IPlayer.
References DVD_TIME_BASE, m_processInfo, m_VideoPlayerVideo, and IDVDStreamPlayerVideo::SetSubtitleDelay().
SetSubtitleVerticalPosition()
void CVideoPlayer::SetSubtitleVerticalPosition (const int value, bool save) override virtual
Set the subtitle vertical position, it depends on current screen resolution.
Parameters
value The subtitle position in pixels
save If true, the value will be saved to resolution info
Reimplemented from IPlayer.
References m_processInfo, m_renderManager, CRenderManager::SetSubtitleVerticalPosition(), and value.
SetSubtitleVisible()
void CVideoPlayer::SetSubtitleVisible (bool bVisible) override virtual
Reimplemented from IPlayer.
References m_messenger, m_processInfo, CDVDMsg::PLAYER_SET_SUBTITLESTREAM_VISIBLE, and CDVDMessageQueue::Put().
SetSubtitleVisibleInternal()
void CVideoPlayer::SetSubtitleVisibleInternal (bool bVisible) protected
References DVDSTREAM_TYPE_DVD, IDVDStreamPlayerVideo::EnableSubtitle(), CServiceBroker::GetDataCacheCore(), m_pInputStream, m_VideoPlayerVideo, and CDataCacheCore::SignalSubtitleInfoChange().
Referenced by AdaptForcedSubtitles(), HandleMessages(), OnDiscNavResult(), and OpenDefaultStreams().
SetTempo()
void CVideoPlayer::SetTempo (float tempo) override virtual
Reimplemented from IPlayer.
References DVD_PLAYSPEED_NORMAL, m_messenger, m_processInfo, and CDVDMessageQueue::Put().
Referenced by HandlePlaySpeed(), and SetSpeed().
SetUpdateStreamDetails()
void CVideoPlayer::SetUpdateStreamDetails ()
References m_messenger, CDVDMsg::PLAYER_SET_UPDATE_STREAM_DETAILS, and CDVDMessageQueue::Put().
Referenced by CApplicationPlayer::SetUpdateStreamDetails().
SetVideoSettings()
void CVideoPlayer::SetVideoSettings (CVideoSettings & settings) override virtual
Reimplemented from IPlayer.
References DVD_TIME_BASE, IDVDStreamPlayerVideo::EnableSubtitle(), CVideoSettings::m_AudioDelay, m_processInfo, m_renderManager, CVideoSettings::m_SubtitleDelay, CVideoSettings::m_SubtitleOn, CVideoSettings::m_subtitleVerticalPosition, CVideoSettings::m_subtitleVerticalPositionSave, m_VideoPlayerVideo, CRenderManager::SetDelay(), IDVDStreamPlayerVideo::SetSubtitleDelay(), CRenderManager::SetSubtitleVerticalPosition(), and CRenderManager::SetVideoSettings().
SetVideoStream()
void CVideoPlayer::SetVideoStream (int iStream) override virtual
Reimplemented from IPlayer.
References m_messenger, m_processInfo, CDVDMessageQueue::Put(), and SynchronizeDemuxer().
Supports() [1/3]
bool CVideoPlayer::Supports (EINTERLACEMETHOD method) const override virtual
Reimplemented from IPlayer.
References m_processInfo.
Supports() [2/3]
bool CVideoPlayer::Supports (ERENDERFEATURE feature) const override virtual
Reimplemented from IPlayer.
References m_renderManager, and CRenderManager::Supports().
Supports() [3/3]
bool CVideoPlayer::Supports (ESCALINGMETHOD method) const override virtual
Reimplemented from IPlayer.
References m_renderManager, and CRenderManager::Supports().
SupportsTempo()
bool CVideoPlayer::SupportsTempo () const override virtual
Reimplemented from IPlayer.
References SPlayerState::cantempo, and m_State.
SynchronizeDemuxer()
void CVideoPlayer::SynchronizeDemuxer () protected
References CThread::IsCurrentThread(), CDVDMessageQueue::IsInited(), CThread::m_bStop, m_messenger, CDVDMessageQueue::Put(), and SYNCSOURCE_PLAYER.
Referenced by Seek(), SeekChapter(), SeekScene(), SeekTime(), SetAudioStream(), and SetVideoStream().
TriggerUpdateResolution()
void CVideoPlayer::TriggerUpdateResolution () override virtual
Reimplemented from IPlayer.
References m_renderManager, and CRenderManager::TriggerUpdateResolution().
UpdateClockSync()
void CVideoPlayer::UpdateClockSync (bool enabled) override protected virtual
Implements IRenderMsg.
References m_processInfo.
UpdateContent()
void CVideoPlayer::UpdateContent () protected
References m_content, m_programs, CVideoPlayer::SContent::m_programs, CVideoPlayer::SContent::m_section, m_SelectionStreams, and CVideoPlayer::SContent::m_selectionStreams.
Referenced by AddSubtitleFile(), CheckStreamChanges(), OnDiscNavResult(), OpenDemuxStream(), Process(), and ReadPacket().
UpdateContentState()
void CVideoPlayer::UpdateContentState () protected
References CCurrentStream::demuxerId, DVDSTREAM_TYPE_DVD, CCurrentStream::id, CVideoPlayer::SContent::m_audioIndex, m_content, m_CurrentAudio, m_CurrentSubtitle, m_CurrentVideo, m_pInputStream, CVideoPlayer::SContent::m_section, m_SelectionStreams, CVideoPlayer::SContent::m_subtitleIndex, CVideoPlayer::SContent::m_videoIndex, CCurrentStream::source, STREAM_AUDIO, STREAM_SOURCE_NAV, STREAM_SUBTITLE, STREAM_VIDEO, and CSelectionStreams::TypeIndexOf().
Referenced by OpenStream().
UpdateCorrection()
void CVideoPlayer::UpdateCorrection (DemuxPacket * pkt, double correction) protected
References DEMUX_PACKET::dts, DVD_NOPTS_VALUE, DemuxPacket::m_ptsOffsetCorrection, and DEMUX_PACKET::pts.
Referenced by CheckContinuity(), and ReadPacket().
UpdateFileItemStreamDetails()
void CVideoPlayer::UpdateFileItemStreamDetails (CFileItem & item) protected
References CURRENT_STREAM, GetAudioStreamCount(), GetAudioStreamInfo(), GetSubtitleCount(), GetSubtitleStreamInfo(), CFileItem::GetVideoInfoTag(), GetVideoStreamInfo(), CLog::Log(), LOGDEBUG, m_processInfo, and m_UpdateStreamDetails.
Referenced by HandleMessages(), and OnExit().
UpdateGuiRender()
void CVideoPlayer::UpdateGuiRender (bool gui) override protected virtual
Implements IRenderMsg.
References m_processInfo.
UpdatePlayState()
void CVideoPlayer::UpdatePlayState (double timeout) protected
References SPlayerState::cache_bytes, SPlayerState::cache_level, SPlayerState::cache_offset, SPlayerState::cache_time, CACHESTATE_DONE, CACHESTATE_PLAY, SPlayerState::caching, SPlayerState::canpause, SPlayerState::canseek, SPlayerState::cantempo, SPlayerState::chapter, SPlayerState::chapters, CCurrentStream::dispTime, SPlayerState::dts, CCurrentStream::dts, DVD_MSEC_TO_TIME(), DVD_NOPTS_VALUE, DVD_TIME_BASE, DVDSTATE_STILL, XFILE::SCacheStatus::forward, CDVDClock::GetAbsoluteClock(), GetCachingTimes(), CDVDInputStream::IChapter::GetChapter(), CDVDInputStream::IChapter::GetChapterCount(), CDVDInputStream::IChapter::GetChapterName(), CDVDInputStream::IChapter::GetChapterPos(), CDVDClock::GetClock(), CServiceBroker::GetDataCacheCore(), GetQueueTime(), CServiceBroker::GetSettingsComponent(), CDVDInputStream::IDisplayTime::GetTime(), CDVDInputStream::ITimes::GetTimes(), CEdl::GetTimeWithoutCuts(), CEdl::GetTotalCutTime(), CDVDInputStream::IDisplayTime::GetTotalTime(), CEdl::HasCuts(), CCurrentStream::id, CVideoPlayer::SDVDInfo::iDVDStillStartTime, CVideoPlayer::SDVDInfo::iDVDStillTime, int64_t(), SPlayerState::isInMenu, IsInMenuInternal(), CacheInfo::level, m_caching, m_clock, m_CurrentAudio, m_CurrentVideo, m_dvd, m_Edl, m_messageQueueTimeSize, m_pDemuxer, m_pInputStream, m_processInfo, m_State, m_StateSection, SPlayerState::menuType, name, NONE, CacheInfo::offset, SPlayerState::player_state, CDVDInputStream::ITimes::Times::ptsBegin, CDVDInputStream::ITimes::Times::ptsEnd, CDVDInputStream::ITimes::Times::ptsStart, CDataCacheCore::SetChapters(), CSettings::SETTING_VIDEOPLAYER_USEDISPLAYASCLOCK, CCurrentStream::startpts, CDVDInputStream::ITimes::Times::startTime, SPlayerState::startTime, CVideoPlayer::SDVDInfo::state, SPlayerState::time, CacheInfo::time, SPlayerState::time_offset, SPlayerState::timeMax, SPlayerState::timeMin, SPlayerState::timestamp, and CacheInfo::valid.
Referenced by FlushBuffers(), GetUpdatedTime(), HandlePlaySpeed(), OnDiscNavResult(), Prepare(), and Process().
UpdateRenderBuffers()
void CVideoPlayer::UpdateRenderBuffers (int queued, int discard, int free) override protected virtual
Implements IRenderMsg.
References m_processInfo.
UpdateRenderInfo()
void CVideoPlayer::UpdateRenderInfo (CRenderInfo & info) override protected virtual
Implements IRenderMsg.
References m_processInfo.
UpdateTimestamps()
void CVideoPlayer::UpdateTimestamps (CCurrentStream & current, DemuxPacket * pPacket) protected
References DEMUX_PACKET::dispTime, CCurrentStream::dispTime, DEMUX_PACKET::dts, CCurrentStream::dts, CCurrentStream::dur, DEMUX_PACKET::duration, DVD_NOPTS_VALUE, and DEMUX_PACKET::pts.
Referenced by ProcessAudioData(), ProcessAudioID3Data(), ProcessRadioRDSData(), ProcessSubData(), ProcessTeletextData(), and ProcessVideoData().
UpdateVideoRender()
void CVideoPlayer::UpdateVideoRender (bool video) override protected virtual
Implements IRenderMsg.
References m_processInfo.
VideoParamsChange()
void CVideoPlayer::VideoParamsChange () override protected virtual
Implements IRenderMsg.
References m_messenger, CDVDMsg::PLAYER_AVCHANGE, and CDVDMessageQueue::Put().
Friends And Related Symbol Documentation
CSelectionStreams
friend class CSelectionStreams friend
Member Data Documentation
m_bAbortRequest
bool CVideoPlayer::m_bAbortRequest protected
Referenced by CloseFile(), CloseStream(), CVideoPlayer(), HandleMessages(), OnExit(), OpenFile(), Prepare(), and Process().
m_bCloseRequest
bool CVideoPlayer::m_bCloseRequest protected
Referenced by CloseFile(), CVideoPlayer(), OnExit(), and OpenFile().
m_caching
ECacheState CVideoPlayer::m_caching protected
Referenced by CVideoPlayer(), HandleMessages(), HandlePlaySpeed(), SetCaching(), and UpdatePlayState().
m_cachingTimer
XbmcThreads::EndTime CVideoPlayer::m_cachingTimer protected
Referenced by HandlePlaySpeed(), and SetCaching().
m_clock
CDVDClock CVideoPlayer::m_clock protected
Referenced by CreatePlayers(), FlushBuffers(), HandleMessages(), HandlePlaySpeed(), OnLostDisplay(), OnResetDisplay(), OpenInputStream(), Prepare(), Process(), SetCaching(), and UpdatePlayState().
m_content
struct CVideoPlayer::SContent CVideoPlayer::m_content protected
Referenced by GetAudioStream(), GetAudioStreamCount(), GetAudioStreamInfo(), GetPrograms(), GetProgramsCount(), GetSubtitle(), GetSubtitleCount(), GetSubtitleStreamInfo(), GetVideoStream(), GetVideoStreamCount(), GetVideoStreamInfo(), UpdateContent(), and UpdateContentState().
m_CurrentAudio
CCurrentStream CVideoPlayer::m_CurrentAudio protected
Referenced by CheckAutoSceneSkip(), CheckContinuity(), CheckPlayerInit(), FlushBuffers(), HandleMessages(), HandlePlaySpeed(), OnDiscNavResult(), OnExit(), OnStartup(), OpenAudioStream(), OpenDefaultStreams(), Prepare(), Process(), ProcessAudioData(), ProcessPacket(), ReadPacket(), UpdateContentState(), and UpdatePlayState().
m_CurrentAudioID3
CCurrentStream CVideoPlayer::m_CurrentAudioID3 protected
Referenced by CheckPlayerInit(), FlushBuffers(), HasID3(), OnExit(), OnStartup(), OpenAudioID3Stream(), OpenDefaultStreams(), Prepare(), Process(), ProcessAudioID3Data(), and ProcessPacket().
m_CurrentRadioRDS
CCurrentStream CVideoPlayer::m_CurrentRadioRDS protected
Referenced by CheckPlayerInit(), FlushBuffers(), HasRDS(), OnExit(), OnStartup(), OpenDefaultStreams(), OpenRadioRDSStream(), Prepare(), Process(), ProcessPacket(), and ProcessRadioRDSData().
m_CurrentSubtitle
CCurrentStream CVideoPlayer::m_CurrentSubtitle protected
Referenced by AdaptForcedSubtitles(), CheckPlayerInit(), FlushBuffers(), HandleMessages(), OnDiscNavResult(), OnExit(), OnStartup(), OpenDefaultStreams(), OpenSubtitleStream(), Prepare(), Process(), ProcessPacket(), ProcessSubData(), and UpdateContentState().
m_CurrentTeletext
CCurrentStream CVideoPlayer::m_CurrentTeletext protected
Referenced by CheckPlayerInit(), FlushBuffers(), GetTeletextCache(), HasTeletextCache(), LoadPage(), OnExit(), OnStartup(), OpenDefaultStreams(), OpenTeletextStream(), Prepare(), Process(), ProcessPacket(), and ProcessTeletextData().
m_CurrentVideo
CCurrentStream CVideoPlayer::m_CurrentVideo protected
Referenced by CheckAutoSceneSkip(), CheckContinuity(), CheckPlayerInit(), FlushBuffers(), HandleMessages(), HandlePlaySpeed(), OnDiscNavResult(), OnExit(), OnStartup(), OpenDefaultStreams(), OpenStream(), OpenVideoStream(), Prepare(), Process(), ProcessPacket(), ProcessVideoData(), ReadPacket(), UpdateContentState(), and UpdatePlayState().
m_demuxerSpeed
int CVideoPlayer::m_demuxerSpeed = DVD_PLAYSPEED_NORMAL protected
Referenced by FlushBuffers(), OpenDemuxStream(), and Process().
m_displayLost
std::atomic<bool> CVideoPlayer::m_displayLost protected
Referenced by CVideoPlayer(), OnLostDisplay(), OnResetDisplay(), OpenAudioStream(), OpenVideoStream(), and Process().
m_dvd
struct CVideoPlayer::SDVDInfo CVideoPlayer::m_dvd protected
Referenced by CVideoPlayer(), HandleMessages(), IsBetterStream(), IsInMenuInternal(), IsValidStream(), OnAction(), OnDiscNavResult(), OpenDefaultStreams(), OpenInputStream(), Process(), and UpdatePlayState().
m_Edl
CEdl CVideoPlayer::m_Edl protected
Referenced by CheckAutoSceneSkip(), CheckSceneSkip(), CloseFile(), HandleMessages(), OpenVideoStream(), Prepare(), ProcessAudioData(), SeekScene(), SeekTimeRelative(), and UpdatePlayState().
m_error
bool CVideoPlayer::m_error protected
Referenced by CVideoPlayer(), OnExit(), OpenFile(), and Prepare().
m_HasAudio
bool CVideoPlayer::m_HasAudio protected
Referenced by CloseFile(), CVideoPlayer(), HasAudio(), OpenAudioStream(), and ReadPacket().
m_HasVideo
bool CVideoPlayer::m_HasVideo protected
Referenced by CloseFile(), CVideoPlayer(), HasVideo(), OpenVideoStream(), and ReadPacket().
m_item
CFileItem CVideoPlayer::m_item protected
Referenced by AddSubtitleFile(), HandleMessages(), HandlePlaySpeed(), OnExit(), OpenDefaultStreams(), OpenFile(), OpenInputStream(), OpenVideoStream(), Prepare(), and Process().
m_messageQueueTimeSize
double CVideoPlayer::m_messageQueueTimeSize {0.0} protected
Referenced by CreatePlayers(), CVideoPlayer(), GetQueueTime(), HandlePlaySpeed(), and UpdatePlayState().
m_messenger
CDVDMessageQueue CVideoPlayer::m_messenger protected
Referenced by AddSubtitle(), CheckAutoSceneSkip(), CreatePlayers(), FlushBuffers(), FrameAdvance(), HandleMessages(), HandlePlaySpeed(), OnAction(), OnDiscNavResult(), OnExit(), OpenFile(), Seek(), SeekChapter(), SeekScene(), SeekTime(), SeekTimeRelative(), SetAudioStream(), SetPlayerState(), SetPlaySpeed(), SetProgram(), SetSubtitle(), SetSubtitleVisible(), SetTempo(), SetUpdateStreamDetails(), SetVideoStream(), SynchronizeDemuxer(), and VideoParamsChange().
m_offset_pts
double CVideoPlayer::m_offset_pts protected
Referenced by CheckContinuity(), CheckSceneSkip(), CVideoPlayer(), OpenDemuxStream(), OpenStream(), Prepare(), ProcessAudioData(), and ReadPacket().
m_outboundEvents
std::unique_ptr<CJobQueue> CVideoPlayer::m_outboundEvents protected
Referenced by HandleMessages(), HandlePlaySpeed(), OnExit(), Prepare(), and ~CVideoPlayer().
m_overlayContainer
CDVDOverlayContainer CVideoPlayer::m_overlayContainer protected
Referenced by CreatePlayers(), and OnDiscNavResult().
m_pCCDemuxer
std::unique_ptr<CDVDDemuxCC> CVideoPlayer::m_pCCDemuxer protected
Referenced by HandleMessages(), IsValidStream(), OnExit(), OpenStream(), OpenVideoStream(), and Process().
m_pDemuxer
std::unique_ptr<CDVDDemux> CVideoPlayer::m_pDemuxer protected
Referenced by CheckStreamChanges(), CloseDemuxer(), CloseFile(), FlushBuffers(), GetCachingTimes(), HandleMessages(), IsValidStream(), OnDiscNavResult(), OnExit(), OpenDefaultStreams(), OpenDemuxStream(), OpenStream(), Prepare(), Process(), ReadPacket(), SetEnableStream(), and UpdatePlayState().
m_pInputStream
std::shared_ptr<CDVDInputStream> CVideoPlayer::m_pInputStream protected
Referenced by CheckStreamChanges(), CloseFile(), GetCachingTimes(), GetSubtitleVisible(), HandleMessages(), HandlePlaySpeed(), IsBetterStream(), IsInMenuInternal(), IsValidStream(), OnAction(), OnDiscNavResult(), OnExit(), OpenDefaultStreams(), OpenDemuxStream(), OpenInputStream(), OpenStream(), OpenVideoStream(), Prepare(), Process(), ProcessSubData(), ReadPacket(), SetSubtitleVisibleInternal(), UpdateContentState(), and UpdatePlayState().
m_playerOptions
CPlayerOptions CVideoPlayer::m_playerOptions protected
Referenced by HandleMessages(), HandlePlaySpeed(), IsBetterStream(), OpenDefaultStreams(), OpenFile(), OpenVideoStream(), and Prepare().
m_players_created
bool CVideoPlayer::m_players_created protected
Referenced by CreatePlayers(), CVideoPlayer(), and DestroyPlayers().
m_playSpeed
int CVideoPlayer::m_playSpeed protected
Referenced by CheckAutoSceneSkip(), CheckContinuity(), CVideoPlayer(), FlushBuffers(), HandleMessages(), HandlePlaySpeed(), OnAction(), Process(), SetCaching(), and SetPlaySpeed().
m_processInfo
std::unique_ptr<CProcessInfo> CVideoPlayer::m_processInfo protected
Referenced by CreatePlayers(), CVideoPlayer(), FlushBuffers(), FrameAdvance(), GetDeinterlacingMethodDefault(), GetPercentage(), GetQueueTime(), GetVideoSettings(), HandleMessages(), HandlePlaySpeed(), OnAction(), OnExit(), OpenDefaultStreams(), OpenDemuxStream(), OpenFile(), Pause(), Prepare(), Process(), Seek(), SeekPercentage(), SeekTime(), SeekTimeRelative(), SetAudioStream(), SetAVDelay(), SetDynamicRangeCompression(), SetRenderViewMode(), SetSpeed(), SetSubtitle(), SetSubTitleDelay(), SetSubtitleVerticalPosition(), SetSubtitleVisible(), SetTempo(), SetVideoSettings(), SetVideoStream(), Supports(), UpdateClockSync(), UpdateFileItemStreamDetails(), UpdateGuiRender(), UpdatePlayState(), UpdateRenderBuffers(), UpdateRenderInfo(), and UpdateVideoRender().
m_programs
std::vector<ProgramInfo> CVideoPlayer::m_programs protected
Referenced by GetPrograms(), GetProgramsCount(), OpenDemuxStream(), ReadPacket(), and UpdateContent().
m_pSubtitleDemuxer
std::shared_ptr<CDVDDemux> CVideoPlayer::m_pSubtitleDemuxer protected
Referenced by CloseFile(), HandleMessages(), IsValidStream(), OnExit(), OpenStream(), Prepare(), and ReadPacket().
m_renderManager
CRenderManager CVideoPlayer::m_renderManager protected
Referenced by CloseFile(), CreatePlayers(), FlushRenderer(), FrameMove(), GetAVDelay(), GetOrientation(), GetRects(), GetRenderAspectRatio(), GetVideoStreamInfo(), HandleMessages(), IsRenderingVideo(), OnAction(), OnExit(), OpenFile(), OpenVideoStream(), Render(), RenderCapture(), RenderCaptureAlloc(), RenderCaptureGetPixels(), RenderCaptureRelease(), SetAVDelay(), SetRenderViewMode(), SetSubtitleVerticalPosition(), SetVideoSettings(), Supports(), Supports(), and TriggerUpdateResolution().
m_SelectionStreams
CSelectionStreams CVideoPlayer::m_SelectionStreams protected
Referenced by AdaptForcedSubtitles(), AddSubtitleFile(), CheckStreamChanges(), CloseDemuxer(), HandleMessages(), OnDiscNavResult(), OnExit(), OpenDefaultStreams(), OpenDemuxStream(), OpenStream(), OpenVideoStream(), Process(), ReadPacket(), UpdateContent(), and UpdateContentState().
m_SkipCommercials
bool CVideoPlayer::m_SkipCommercials protected
Referenced by CheckAutoSceneSkip(), CVideoPlayer(), OnAction(), and Prepare().
m_SpeedState
struct CVideoPlayer::SSpeedState CVideoPlayer::m_SpeedState protected
Referenced by FlushBuffers(), HandlePlaySpeed(), and Prepare().
m_State
SPlayerState CVideoPlayer::m_State protected
Referenced by CanPause(), CanSeek(), CVideoPlayer(), GetCacheLevel(), GetCachePercentage(), GetChapter(), GetChapterCount(), GetChapterName(), GetChapterPos(), GetGeneralInfo(), GetPlayerState(), GetSupportedMenuType(), GetTime(), GetUpdatedTime(), HandleMessages(), HandlePlaySpeed(), IsCaching(), IsInMenu(), OnExit(), Prepare(), Process(), Seek(), SupportsTempo(), and UpdatePlayState().
m_StateSection
CCriticalSection CVideoPlayer::m_StateSection mutable protected
Referenced by CanPause(), CanSeek(), GetCacheLevel(), GetCachePercentage(), GetChapter(), GetChapterCount(), GetChapterName(), GetChapterPos(), GetGeneralInfo(), GetPlayerState(), GetSupportedMenuType(), GetTime(), IsCaching(), IsInMenu(), and UpdatePlayState().
m_streamPlayerSpeed
int CVideoPlayer::m_streamPlayerSpeed protected
Referenced by CVideoPlayer(), HandleMessages(), OpenAudioStream(), OpenVideoStream(), SetCaching(), and SetPlaySpeed().
m_subtitleDemuxerMap
std::unordered_map<int64_t, std::shared_ptr<CDVDDemux> > CVideoPlayer::m_subtitleDemuxerMap protected
Referenced by AddSubtitleFile(), HandleMessages(), OnExit(), and OpenStream().
m_syncTimer
XbmcThreads::EndTime CVideoPlayer::m_syncTimer protected
Referenced by HandlePlaySpeed().
m_UpdateStreamDetails
bool CVideoPlayer::m_UpdateStreamDetails protected
Referenced by CVideoPlayer(), HandleMessages(), and UpdateFileItemStreamDetails().
m_VideoPlayerAudio
IDVDStreamPlayerAudio* CVideoPlayer::m_VideoPlayerAudio protected
Referenced by CreatePlayers(), DestroyPlayers(), FlushBuffers(), GetDebugInfo(), GetGeneralInfo(), GetQueueTime(), GetStreamPlayer(), HandleMessages(), HandlePlaySpeed(), IsPassthrough(), OnLostDisplay(), OnResetDisplay(), Process(), ProcessAudioData(), SetCaching(), and SetDynamicRangeCompression().
m_VideoPlayerAudioID3
std::unique_ptr<CVideoPlayerAudioID3> CVideoPlayer::m_VideoPlayerAudioID3 protected
Referenced by CreatePlayers(), DestroyPlayers(), FlushBuffers(), GetStreamPlayer(), OpenAudioID3Stream(), and ProcessAudioID3Data().
m_VideoPlayerRadioRDS
CDVDRadioRDSData* CVideoPlayer::m_VideoPlayerRadioRDS protected
Referenced by CreatePlayers(), DestroyPlayers(), FlushBuffers(), GetStreamPlayer(), OpenRadioRDSStream(), and ProcessRadioRDSData().
m_VideoPlayerSubtitle
CVideoPlayerSubtitle* CVideoPlayer::m_VideoPlayerSubtitle protected
Referenced by CreatePlayers(), DestroyPlayers(), FlushBuffers(), GetStreamPlayer(), OnAction(), OnDiscNavResult(), Process(), ProcessSubData(), and ReadPacket().
m_VideoPlayerTeletext
CDVDTeletextData* CVideoPlayer::m_VideoPlayerTeletext protected
Referenced by CreatePlayers(), DestroyPlayers(), FlushBuffers(), GetStreamPlayer(), GetTeletextCache(), LoadPage(), OpenTeletextStream(), and ProcessTeletextData().
m_VideoPlayerVideo
IDVDStreamPlayerVideo* CVideoPlayer::m_VideoPlayerVideo protected
Referenced by CreatePlayers(), DestroyPlayers(), FlushBuffers(), GetDebugInfo(), GetGeneralInfo(), GetStreamPlayer(), GetSubTitleDelay(), GetSubtitleVisible(), HandleMessages(), HandlePlaySpeed(), OnDiscNavResult(), OnLostDisplay(), OnResetDisplay(), OpenStream(), Process(), ProcessVideoData(), SetCaching(), SetSubTitleDelay(), SetSubtitleVisibleInternal(), and SetVideoSettings().
The documentation for this class was generated from the following files:
VideoPlayer.h
VideoPlayer.cpp