Kodi Documentation: anonymous_namespace{PVRClient.cpp}::CAddonTimer Class Reference
anonymous_namespace{PVRClient.cpp}::CAddonTimer Class Reference
Public Member Functions
CAddonTimer (const CPVRTimerInfoTag &timer)
virtual ~CAddonTimer ()=default
Private Attributes
const std::string m_title
const std::string m_epgSearchString
const std::string m_directory
const std::string m_summary
const std::string m_seriesLink
std::vector< std::string > m_customPropStringValues
std::unique_ptr< PVR_SETTING_KEY_VALUE_PAIR[]> m_customProps
Additional Inherited Members
Public Attributes inherited from PVR_TIMER
unsigned int iClientIndex
unsigned int iParentClientIndex
int iClientChannelUid
time_t startTime
time_t endTime
bool bStartAnyTime
bool bEndAnyTime
enum PVR_TIMER_STATE state
unsigned int iTimerType
const char * strTitle
const char * strEpgSearchString
bool bFullTextEpgSearch
const char * strDirectory
const char * strSummary
int iPriority
int iLifetime
int iMaxRecordings
unsigned int iRecordingGroup
time_t firstDay
unsigned int iWeekdays
unsigned int iPreventDuplicateEpisodes
unsigned int iEpgUid
unsigned int iMarginStart
unsigned int iMarginEnd
int iGenreType
int iGenreSubType
const char * strSeriesLink
unsigned int iCustomPropsSize
struct PVR_SETTING_KEY_VALUE_PAIR * customProps
Constructor & Destructor Documentation
CAddonTimer()
anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer (const CPVRTimerInfoTag & timer) inline explicit
References PVR::CPVRTimerInfoTag::ClientChannelUID(), PVR::CPVRTimerInfoTag::ClientIndex(), end(), PVR::CPVRTimerInfoTag::EndAsUTC(), PVR::CPVRTimerInfoTag::FirstDayAsUTC(), CDateTime::GetAsTime(), PVR::CPVRTimerInfoTag::GetCustomProperties(), PVR::CPVRTimerInfoTag::GetEpgInfoTag(), CServiceBroker::GetSettingsComponent(), PVR::CPVRTimerInfoTag::GetTimerType(), PVR_SETTING_KEY_VALUE_PAIR::iKey, PVR::CPVRTimerInfoTag::IsEndAnyTime(), PVR::CPVRTimerInfoTag::IsFullTextEpgSearch(), PVR::CPVRTimerInfoTag::IsStartAnyTime(), PVR::CPVRTimerInfoTag::Lifetime(), PVR::CPVRTimerInfoTag::MarginEnd(), PVR::CPVRTimerInfoTag::MarginStart(), PVR::CPVRTimerInfoTag::MaxRecordings(), PVR::CPVRTimerInfoTag::ParentClientIndex(), PVR::CPVRTimerInfoTag::PreventDupEpisodesPolicy(), PVR::CPVRTimerInfoTag::Priority(), PVR_TIMER_NO_EPG_UID, PVR::CPVRTimerInfoTag::RecordingGroup(), PVR::CPVRTimerInfoTag::StartAsUTC(), PVR::CPVRTimerInfoTag::State(), and PVR::CPVRTimerInfoTag::WeekDays().
~CAddonTimer()
virtual anonymous_namespace{PVRClient.cpp}::CAddonTimer::~CAddonTimer () virtual default
Member Data Documentation
m_customProps
std::unique_ptr<PVR_SETTING_KEY_VALUE_PAIR[]> anonymous_namespace{PVRClient.cpp}::CAddonTimer::m_customProps private
m_customPropStringValues
std::vector<std::string> anonymous_namespace{PVRClient.cpp}::CAddonTimer::m_customPropStringValues private
m_directory
const std::string anonymous_namespace{PVRClient.cpp}::CAddonTimer::m_directory private
m_epgSearchString
const std::string anonymous_namespace{PVRClient.cpp}::CAddonTimer::m_epgSearchString private
m_seriesLink
const std::string anonymous_namespace{PVRClient.cpp}::CAddonTimer::m_seriesLink private
m_summary
const std::string anonymous_namespace{PVRClient.cpp}::CAddonTimer::m_summary private
m_title
const std::string anonymous_namespace{PVRClient.cpp}::CAddonTimer::m_title private
The documentation for this class was generated from the following file:
PVRClient.cpp