Kodi Documentation: AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress Struct Reference
AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress Struct Reference
#include <extended_progress.h>
Public Attributes
KODI_GUI_HANDLE(* new_dialog)(KODI_HANDLE kodiBase, const char *title)
void(* delete_dialog)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
char *(* get_title)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
void(* set_title)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char *title)
char *(* get_text)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
void(* set_text)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char *text)
bool(* is_finished)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
void(* mark_finished)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
float(* get_percentage)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
void(* set_percentage)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, float percentage)
void(* set_progress)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int currentItem, int itemCount)
Member Data Documentation
delete_dialog
void(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::delete_dialog) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
get_percentage
float(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::get_percentage) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
get_text
char *(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::get_text) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
get_title
char *(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::get_title) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
is_finished
bool(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::is_finished) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
mark_finished
void(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::mark_finished) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
new_dialog
KODI_GUI_HANDLE(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::new_dialog) (KODI_HANDLE kodiBase, const char *title)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
set_percentage
void(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::set_percentage) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, float percentage)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
set_progress
void(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::set_progress) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int currentItem, int itemCount)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
set_text
void(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::set_text) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char *text)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
set_title
void(* AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::set_title) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char *title)
Referenced by ADDON::Interface_GUIDialogExtendedProgress::Init().
The documentation for this struct was generated from the following file:
extended_progress.h