Kodi Documentation: CAAudioUnitSink Class Reference
CAAudioUnitSink Class Reference
Public Member Functions
CAAudioUnitSink ()=default
~CAAudioUnitSink ()
bool open (AudioStreamBasicDescription outputFormat)
bool close ()
bool play (bool mute)
bool mute (bool mute)
bool pause ()
void drain ()
void getDelay (AEDelayStatus &status)
double cacheSize ()
unsigned int write (uint8_t *data, unsigned int byte_count)
unsigned int chunkSize ()
unsigned int getRealisedSampleRate ()
CAAudioUnitSink ()
~CAAudioUnitSink ()
bool open (AudioStreamBasicDescription outputFormat, size_t buffer_size)
bool close ()
bool activate ()
bool deactivate ()
void updatedelay (AEDelayStatus &status)
double buffertime ()
unsigned int sampletrate ()
unsigned int write (uint8_t *data, unsigned int frames, unsigned int framesize)
void drain ()
Static Public Member Functions
static Float64 getCoreAudioRealisedSampleRate ()
Private Member Functions
void setCoreAudioBuffersize ()
bool setCoreAudioInputFormat ()
void setCoreAudioPreferredSampleRate ()
bool setupAudio ()
bool checkAudioRoute ()
bool checkSessionProperties ()
bool activateAudioSession ()
void deactivateAudioSession ()
bool setupAudio ()
Static Private Member Functions
static void sessionPropertyCallback (void *inClientData, AudioSessionPropertyID inID, UInt32 inDataSize, const void *inData)
static OSStatus renderCallback (void *inRefCon, AudioUnitRenderActionFlags *ioActionFlags, const AudioTimeStamp *inTimeStamp, UInt32 inOutputBusNumber, UInt32 inNumberFrames, AudioBufferList *ioData)
static OSStatus renderCallback (void *inRefCon, AudioUnitRenderActionFlags *ioActionFlags, const AudioTimeStamp *inTimeStamp, UInt32 inOutputBusNumber, UInt32 inNumberFrames, AudioBufferList *ioData)
Private Attributes
bool m_setup
bool m_activated = false
AudioUnit m_audioUnit
AudioStreamBasicDescription m_outputFormat
AERingBuffer * m_buffer = nullptr
bool m_mute
Float32 m_outputVolume
Float32 m_outputLatency
Float32 m_bufferDuration
unsigned int m_sampleRate
unsigned int m_frameSize
bool m_playing = false
volatile bool m_started = false
CAESpinSection m_render_section
volatile int64_t m_render_timestamp = 0
volatile uint32_t m_render_frames = 0
Float32 m_totalLatency
Float32 m_inputLatency
std::atomic< bool > m_started
std::atomic< int64_t > m_render_timestamp
Constructor & Destructor Documentation
CAAudioUnitSink() [1/2]
CAAudioUnitSink::CAAudioUnitSink () default
~CAAudioUnitSink() [1/2]
CAAudioUnitSink::~CAAudioUnitSink ()
References close().
CAAudioUnitSink() [2/2]
CAAudioUnitSink::CAAudioUnitSink ()
~CAAudioUnitSink() [2/2]
CAAudioUnitSink::~CAAudioUnitSink ()
Member Function Documentation
activate()
bool CAAudioUnitSink::activate ()
References m_activated, m_audioUnit, and setupAudio().
Referenced by CAESinkDARWINTVOS::Initialize().
activateAudioSession()
bool CAAudioUnitSink::activateAudioSession () private
References checkAudioRoute(), m_activated, and setupAudio().
Referenced by play().
buffertime()
double CAAudioUnitSink::buffertime ()
References buffertime(), AERingBuffer::GetMaxSize(), m_buffer, m_frameSize, and m_sampleRate.
Referenced by buffertime(), and CAESinkDARWINTVOS::GetCacheTotal().
cacheSize()
double CAAudioUnitSink::cacheSize ()
References AERingBuffer::GetMaxSize(), m_buffer, m_frameSize, and m_sampleRate.
Referenced by CAESinkDARWINIOS::GetCacheTotal().
checkAudioRoute()
bool CAAudioUnitSink::checkAudioRoute () private
Referenced by activateAudioSession(), checkSessionProperties(), and sessionPropertyCallback().
checkSessionProperties()
bool CAAudioUnitSink::checkSessionProperties () private
References checkAudioRoute(), CLog::Log(), LOGDEBUG, m_bufferDuration, m_outputLatency, m_outputVolume, and session.
Referenced by sessionPropertyCallback(), and setupAudio().
chunkSize()
unsigned int CAAudioUnitSink::chunkSize () inline
References m_bufferDuration, and m_sampleRate.
Referenced by CAESinkDARWINIOS::Initialize().
close() [1/2]
bool CAAudioUnitSink::close ()
References deactivateAudioSession(), m_buffer, and m_started.
Referenced by ~CAAudioUnitSink().
close() [2/2]
bool CAAudioUnitSink::close ()
deactivate()
bool CAAudioUnitSink::deactivate ()
References m_activated, m_audioUnit, and m_setup.
deactivateAudioSession()
void CAAudioUnitSink::deactivateAudioSession () private
References m_activated, m_audioUnit, m_setup, pause(), and sessionPropertyCallback().
Referenced by close().
drain() [1/2]
void CAAudioUnitSink::drain ()
References condVar, AERingBuffer::GetReadSize(), m_buffer, m_frameSize, m_sampleRate, mutex, and XbmcThreads::ConditionVariable::wait().
Referenced by CAESinkDARWINIOS::Drain(), and CAESinkDARWINTVOS::Drain().
drain() [2/2]
void CAAudioUnitSink::drain ()
getCoreAudioRealisedSampleRate()
Float64 CAAudioUnitSink::getCoreAudioRealisedSampleRate () static
Referenced by CAESinkDARWINIOS::Initialize(), and setupAudio().
getDelay()
void CAAudioUnitSink::getDelay (AEDelayStatus & status)
References AEDelayStatus::delay, AERingBuffer::GetReadSize(), m_buffer, m_bufferDuration, m_frameSize, m_outputLatency, m_render_frames, m_render_section, m_render_timestamp, m_sampleRate, CAESpinLock::retry(), and AEDelayStatus::tick.
Referenced by CAESinkDARWINIOS::GetDelay().
getRealisedSampleRate()
unsigned int CAAudioUnitSink::getRealisedSampleRate () inline
References m_outputFormat.
Referenced by CAESinkDARWINIOS::Initialize().
mute()
bool CAAudioUnitSink::mute (bool mute)
References m_mute, and mute().
Referenced by mute(), and play().
open() [1/2]
bool CAAudioUnitSink::open (AudioStreamBasicDescription outputFormat)
References m_buffer, m_bufferDuration, m_frameSize, m_mute, m_outputFormat, m_outputLatency, m_outputVolume, m_sampleRate, m_setup, and setupAudio().
Referenced by CAESinkDARWINIOS::Initialize(), and CAESinkDARWINTVOS::Initialize().
open() [2/2]
bool CAAudioUnitSink::open (AudioStreamBasicDescription outputFormat, size_t buffer_size)
References m_buffer, m_bufferDuration, m_frameSize, m_outputFormat, m_outputLatency, m_sampleRate, m_setup, and setupAudio().
pause()
bool CAAudioUnitSink::pause ()
References m_audioUnit, and m_playing.
Referenced by deactivateAudioSession().
play()
bool CAAudioUnitSink::play (bool mute)
References activateAudioSession(), m_audioUnit, m_playing, and mute().
Referenced by CAESinkDARWINIOS::Initialize().
renderCallback() [1/2]
OSStatus CAAudioUnitSink::renderCallback (void * inRefCon, AudioUnitRenderActionFlags * ioActionFlags, const AudioTimeStamp * inTimeStamp, UInt32 inOutputBusNumber, UInt32 inNumberFrames, AudioBufferList * ioData) static private
References condVar, CAESpinSection::enter(), AERingBuffer::GetReadSize(), CAESpinSection::leave(), LogLevel(), m_buffer, m_render_frames, m_render_section, m_render_timestamp, m_started, XbmcThreads::ConditionVariable::notifyAll(), and AERingBuffer::Read().
Referenced by setupAudio().
renderCallback() [2/2]
static OSStatus CAAudioUnitSink::renderCallback (void * inRefCon, AudioUnitRenderActionFlags * ioActionFlags, const AudioTimeStamp * inTimeStamp, UInt32 inOutputBusNumber, UInt32 inNumberFrames, AudioBufferList * ioData) static private
sampletrate()
unsigned int CAAudioUnitSink::sampletrate () inline
References m_outputFormat.
Referenced by CAESinkDARWINTVOS::Initialize().
sessionPropertyCallback()
void CAAudioUnitSink::sessionPropertyCallback (void * inClientData, AudioSessionPropertyID inID, UInt32 inDataSize, const void * inData) static private
References checkAudioRoute(), checkSessionProperties(), and m_outputVolume.
Referenced by deactivateAudioSession(), and setupAudio().
setCoreAudioBuffersize()
void CAAudioUnitSink::setCoreAudioBuffersize () private
References LOGINFO, LOGWARNING, m_outputFormat, and session.
Referenced by setupAudio().
setCoreAudioInputFormat()
bool CAAudioUnitSink::setCoreAudioInputFormat () private
References CLog::Log(), LOGERROR, m_audioUnit, and m_outputFormat.
Referenced by setupAudio().
setCoreAudioPreferredSampleRate()
void CAAudioUnitSink::setCoreAudioPreferredSampleRate () private
References LOGINFO, LOGWARNING, m_outputFormat, and session.
Referenced by setupAudio().
setupAudio() [1/2]
bool CAAudioUnitSink::setupAudio () private
References checkSessionProperties(), getCoreAudioRealisedSampleRate(), CLog::Log(), LOGERROR, LOGINFO, m_audioUnit, m_outputFormat, m_setup, renderCallback(), sessionPropertyCallback(), setCoreAudioBuffersize(), setCoreAudioInputFormat(), setCoreAudioPreferredSampleRate(), and StreamDescriptionToString().
Referenced by activate(), activateAudioSession(), open(), and open().
setupAudio() [2/2]
bool CAAudioUnitSink::setupAudio () private
updatedelay()
void CAAudioUnitSink::updatedelay (AEDelayStatus & status)
References AEDelayStatus::delay, AERingBuffer::GetReadSize(), m_buffer, m_frameSize, m_render_section, m_render_timestamp, m_sampleRate, m_totalLatency, CAESpinLock::retry(), and AEDelayStatus::tick.
Referenced by CAESinkDARWINTVOS::GetDelay().
write() [1/2]
unsigned int CAAudioUnitSink::write (uint8_t * data, unsigned int byte_count)
References condVar, data(), AERingBuffer::GetWriteSize(), CLog::Log(), LOGERROR, m_buffer, m_frameSize, m_sampleRate, m_started, mutex, XbmcThreads::ConditionVariable::wait(), and AERingBuffer::Write().
Referenced by CAESinkDARWINIOS::AddPackets(), and CAESinkDARWINTVOS::AddPackets().
write() [2/2]
unsigned int CAAudioUnitSink::write (uint8_t * data, unsigned int frames, unsigned int framesize)
References condVar, data(), AERingBuffer::GetWriteSize(), CLog::Log(), LOGERROR, m_buffer, m_sampleRate, m_started, mutex, XbmcThreads::ConditionVariable::wait(), and AERingBuffer::Write().
Member Data Documentation
m_activated
bool CAAudioUnitSink::m_activated = false private
Referenced by activate(), activateAudioSession(), deactivate(), and deactivateAudioSession().
m_audioUnit
AudioUnit CAAudioUnitSink::m_audioUnit private
Referenced by activate(), deactivate(), deactivateAudioSession(), pause(), play(), setCoreAudioInputFormat(), and setupAudio().
m_buffer
AERingBuffer * CAAudioUnitSink::m_buffer = nullptr private
Referenced by buffertime(), cacheSize(), close(), drain(), getDelay(), open(), open(), renderCallback(), updatedelay(), write(), and write().
m_bufferDuration
Float32 CAAudioUnitSink::m_bufferDuration private
Referenced by checkSessionProperties(), chunkSize(), getDelay(), open(), and open().
m_frameSize
unsigned int CAAudioUnitSink::m_frameSize private
Referenced by buffertime(), cacheSize(), drain(), getDelay(), open(), open(), updatedelay(), and write().
m_inputLatency
Float32 CAAudioUnitSink::m_inputLatency private
m_mute
bool CAAudioUnitSink::m_mute private
Referenced by mute(), and open().
m_outputFormat
AudioStreamBasicDescription CAAudioUnitSink::m_outputFormat private
Referenced by getRealisedSampleRate(), open(), open(), sampletrate(), setCoreAudioBuffersize(), setCoreAudioInputFormat(), setCoreAudioPreferredSampleRate(), and setupAudio().
m_outputLatency
Float32 CAAudioUnitSink::m_outputLatency private
Referenced by checkSessionProperties(), getDelay(), open(), and open().
m_outputVolume
Float32 CAAudioUnitSink::m_outputVolume private
Referenced by checkSessionProperties(), open(), and sessionPropertyCallback().
m_playing
bool CAAudioUnitSink::m_playing = false private
Referenced by pause(), and play().
m_render_frames
volatile uint32_t CAAudioUnitSink::m_render_frames = 0 private
Referenced by getDelay(), and renderCallback().
m_render_section
CAESpinSection CAAudioUnitSink::m_render_section private
Referenced by getDelay(), renderCallback(), and updatedelay().
m_render_timestamp [1/2]
volatile int64_t CAAudioUnitSink::m_render_timestamp = 0 private
Referenced by getDelay(), renderCallback(), and updatedelay().
m_render_timestamp [2/2]
std::atomic<int64_t> CAAudioUnitSink::m_render_timestamp private
m_sampleRate
unsigned int CAAudioUnitSink::m_sampleRate private
Referenced by buffertime(), cacheSize(), chunkSize(), drain(), getDelay(), open(), open(), updatedelay(), write(), and write().
m_setup
bool CAAudioUnitSink::m_setup private
Referenced by deactivate(), deactivateAudioSession(), open(), open(), and setupAudio().
m_started [1/2]
volatile bool CAAudioUnitSink::m_started = false private
Referenced by close(), renderCallback(), write(), and write().
m_started [2/2]
std::atomic<bool> CAAudioUnitSink::m_started private
m_totalLatency
Float32 CAAudioUnitSink::m_totalLatency private
Referenced by updatedelay().
The documentation for this class was generated from the following files:
AESinkDARWINIOS.mm
AESinkDARWINTVOS.mm