Kodi Documentation: CJobManager Class Reference
CJobManager Class Reference final
Asynchronous jobs
Job Manager class for scheduling asynchronous jobs.
#include <JobManager.h>
Classes
class CWorkItem
Public Member Functions
CJobManager ()
unsigned int AddJob (CJob *job, IJobCallback *callback, CJob::PRIORITY priority=CJob::PRIORITY_LOW)
Add a job to the threaded job manager. On completion or abort of the job or in case the job could not be added successfully, the CJob object will be destroyed.
template<typename F >
void Submit (F &&f, CJob::PRIORITY priority=CJob::PRIORITY_LOW)
Add a function f to this job manager for asynchronously execution.
template<typename F >
void Submit (F &&f, IJobCallback *callback, CJob::PRIORITY priority=CJob::PRIORITY_LOW)
Add a function f to this job manager for asynchronously execution.
void CancelJob (unsigned int jobID)
Cancel a job with the given id.
void CancelJobs ()
Cancel all remaining jobs, preparing for shutdown Should be called prior to destroying any objects that may be being used as callbacks.
void Restart ()
Re-start accepting jobs again Called after calling CancelJobs() to allow this manager to accept more jobs.
int IsProcessing (const std::string &type) const
Checks to see if any jobs of a specific type are currently processing.
void PauseJobs ()
Suspends queueing of jobs with priority PRIORITY_LOW_PAUSABLE until unpaused Useful to (for ex) stop queuing thumb jobs during video start/playback. Does not affect currently processing jobs, use IsProcessing to see if any need to be waited on.
void UnPauseJobs ()
Resumes queueing of (previously paused) jobs with priority PRIORITY_LOW_PAUSABLE.
bool IsProcessing (const CJob::PRIORITY &priority) const
Checks to see if any jobs with specific priority are currently processing.
Protected Member Functions
CJob * GetNextJob ()
Get a new job to process. Blocks until a new job is available, or a timeout has occurred.
void OnJobComplete (bool success, CJob *job)
Callback from CJobWorker after a job has completed. Calls IJobCallback::OnJobComplete(), and then destroys job.
bool OnJobProgress (unsigned int progress, unsigned int total, const CJob *job) const
Callback from CJob to report progress and check for cancellation. Checks for cancellation, and calls IJobCallback::OnJobProgress().
Private Types
typedef std::deque< CWorkItem > JobQueue
typedef std::vector< CWorkItem > Processing
typedef std::vector< CJobWorker * > Workers
Private Member Functions
CJobManager (const CJobManager &)=delete
CJobManager const & operator= (CJobManager const &)=delete
CJob * PopJob ()
Pop a job off the job queue and add to the processing queue ready to process.
void StartWorkers (CJob::PRIORITY priority)
void RemoveWorker (const CJobWorker *worker)
Static Private Member Functions
static unsigned int GetMaxWorkers (CJob::PRIORITY priority)
Private Attributes
unsigned int m_jobCounter
JobQueue m_jobQueue [CJob::PRIORITY_DEDICATED+1]
bool m_pauseJobs
Processing m_processing
Workers m_workers
CCriticalSection m_section
CEvent m_jobEvent
bool m_running
Friends
class CJobWorker
class CJob
class CJobQueue
Detailed Description
Job Manager class for scheduling asynchronous jobs.
Controls asynchronous job execution, by allowing clients to add and cancel jobs. Should be accessed via CServiceBroker::GetJobManager(). Jobs are allocated based on priority levels. Lower priority jobs are executed only if there are sufficient spare worker threads free to allow for higher priority jobs that may arise.
See also
CJob and IJobCallback
Member Typedef Documentation
JobQueue
typedef std::deque<CWorkItem> CJobManager::JobQueue private
Processing
typedef std::vector<CWorkItem> CJobManager::Processing private
Workers
typedef std::vector<CJobWorker*> CJobManager::Workers private
Constructor & Destructor Documentation
CJobManager() [1/2]
CJobManager::CJobManager ()
References m_jobCounter, m_pauseJobs, and m_running.
CJobManager() [2/2]
CJobManager::CJobManager (const CJobManager &) private delete
Member Function Documentation
AddJob()
unsigned int CJobManager::AddJob (CJob * job, IJobCallback * callback, CJob::PRIORITY priority = CJob::PRIORITY_LOW)
Add a job to the threaded job manager. On completion or abort of the job or in case the job could not be added successfully, the CJob object will be destroyed.
Parameters
job a pointer to the job to add. The job should be subclassed from CJob
callback a pointer to an IJobCallback instance to receive job progress and completion notices.
priority the priority that this job should run at.
Returns
On success, a unique identifier for this job, to be used with other interaction, 0 otherwise. In case of failure, the passed CJob object will be deleted before returning from this method.
See also
CJob, IJobCallback, CancelJob()
References CJobManager::CWorkItem::m_id, m_jobCounter, m_jobQueue, m_running, m_section, and StartWorkers().
Referenced by Submit(), and Submit().
CancelJob()
void CJobManager::CancelJob (unsigned int jobID)
Cancel a job with the given id.
Parameters
jobID the id of the job to cancel, retrieved previously from AddJob()
See also
AddJob()
References end(), m_jobQueue, m_processing, m_section, CJob::PRIORITY_DEDICATED, and CJob::PRIORITY_LOW_PAUSABLE.
CancelJobs()
void CJobManager::CancelJobs ()
Cancel all remaining jobs, preparing for shutdown Should be called prior to destroying any objects that may be being used as callbacks.
See also
CancelJob(), AddJob()
References end(), CJobManager::CWorkItem::FreeJob(), CJobManager::CWorkItem::m_callback, CJobManager::CWorkItem::m_id, CJobManager::CWorkItem::m_job, m_jobEvent, m_jobQueue, m_processing, m_running, m_section, m_workers, IJobCallback::OnJobAbort(), CJob::PRIORITY_DEDICATED, CJob::PRIORITY_LOW_PAUSABLE, and CEvent::Set().
GetMaxWorkers()
unsigned int CJobManager::GetMaxWorkers (CJob::PRIORITY priority) static private
References CJob::PRIORITY_DEDICATED, and CJob::PRIORITY_HIGH.
Referenced by PopJob(), and StartWorkers().
GetNextJob()
CJob * CJobManager::GetNextJob () protected
Get a new job to process. Blocks until a new job is available, or a timeout has occurred.
See also
CJob
References m_jobEvent, m_running, m_section, PopJob(), and CEvent::Wait().
Referenced by CJobWorker::Process().
IsProcessing() [1/2]
bool CJobManager::IsProcessing (const CJob::PRIORITY & priority) const
Checks to see if any jobs with specific priority are currently processing.
Parameters
priority to search for
Returns
true if processing jobs, else returns false
References m_pauseJobs, m_processing, and m_section.
IsProcessing() [2/2]
int CJobManager::IsProcessing (const std::string & type) const
Checks to see if any jobs of a specific type are currently processing.
Parameters
type Job type to search for
Returns
Number of matching jobs
References m_pauseJobs, m_processing, and m_section.
OnJobComplete()
void CJobManager::OnJobComplete (bool success, CJob * job) protected
Callback from CJobWorker after a job has completed. Calls IJobCallback::OnJobComplete(), and then destroys job.
Parameters
job a pointer to the calling subclassed CJob instance.
success the result from the DoWork call
See also
IJobCallback, CJob
References CJobManager::CWorkItem::FreeJob(), CJob::GetType(), CLog::Log(), LOGERROR, CJobManager::CWorkItem::m_callback, CJobManager::CWorkItem::m_id, CJobManager::CWorkItem::m_job, m_processing, m_section, IJobCallback::OnJobComplete(), and success.
Referenced by CJobWorker::Process().
OnJobProgress()
bool CJobManager::OnJobProgress (unsigned int progress, unsigned int total, const CJob * job) const protected
Callback from CJob to report progress and check for cancellation. Checks for cancellation, and calls IJobCallback::OnJobProgress().
Parameters
progress amount of processing performed to date, out of total.
total total amount of processing.
job pointer to the calling subclassed CJob instance.
Returns
true if the job has been cancelled, else returns false.
See also
IJobCallback, CJob
References CJobManager::CWorkItem::m_callback, CJobManager::CWorkItem::m_id, m_processing, m_section, and IJobCallback::OnJobProgress().
Referenced by CJob::ShouldCancel().
operator=()
CJobManager const & CJobManager::operator= (CJobManager const &) private delete
PauseJobs()
void CJobManager::PauseJobs ()
Suspends queueing of jobs with priority PRIORITY_LOW_PAUSABLE until unpaused Useful to (for ex) stop queuing thumb jobs during video start/playback. Does not affect currently processing jobs, use IsProcessing to see if any need to be waited on.
See also
UnPauseJobs()
References m_pauseJobs, and m_section.
PopJob()
CJob * CJobManager::PopJob () private
Pop a job off the job queue and add to the processing queue ready to process.
Returns
the job to process, NULL if no jobs are available
References GetMaxWorkers(), CJob::m_callback, CJobManager::CWorkItem::m_job, m_jobQueue, m_pauseJobs, m_processing, m_section, CJob::PRIORITY_DEDICATED, and CJob::PRIORITY_LOW_PAUSABLE.
Referenced by GetNextJob().
RemoveWorker()
void CJobManager::RemoveWorker (const CJobWorker * worker) private
References m_section, and m_workers.
Referenced by CJobWorker::~CJobWorker().
Restart()
void CJobManager::Restart ()
Re-start accepting jobs again Called after calling CancelJobs() to allow this manager to accept more jobs.
Exceptions
std::logic_error if the manager was not previously cancelled
See also
CancelJobs()
References m_running, and m_section.
StartWorkers()
void CJobManager::StartWorkers (CJob::PRIORITY priority) private
References CJobWorker, GetMaxWorkers(), m_jobEvent, m_processing, m_section, m_workers, and CEvent::Set().
Referenced by AddJob().
Submit() [1/2]
template<typename F > void CJobManager::Submit (F && f, CJob::PRIORITY priority = CJob::PRIORITY_LOW) inline
Add a function f to this job manager for asynchronously execution.
References AddJob(), and f.
Submit() [2/2]
template<typename F > void CJobManager::Submit (F && f, IJobCallback * callback, CJob::PRIORITY priority = CJob::PRIORITY_LOW) inline
Add a function f to this job manager for asynchronously execution.
References AddJob(), and f.
UnPauseJobs()
void CJobManager::UnPauseJobs ()
Resumes queueing of (previously paused) jobs with priority PRIORITY_LOW_PAUSABLE.
See also
PauseJobs()
References m_pauseJobs, and m_section.
Friends And Related Symbol Documentation
CJob
friend class CJob friend
CJobQueue
friend class CJobQueue friend
CJobWorker
friend class CJobWorker friend
Referenced by StartWorkers().
Member Data Documentation
m_jobCounter
unsigned int CJobManager::m_jobCounter private
Referenced by AddJob(), and CJobManager().
m_jobEvent
CEvent CJobManager::m_jobEvent private
Referenced by CancelJobs(), GetNextJob(), and StartWorkers().
m_jobQueue
JobQueue CJobManager::m_jobQueue[CJob::PRIORITY_DEDICATED+1] private
Referenced by AddJob(), CancelJob(), CancelJobs(), and PopJob().
m_pauseJobs
bool CJobManager::m_pauseJobs private
Referenced by CJobManager(), IsProcessing(), IsProcessing(), PauseJobs(), PopJob(), and UnPauseJobs().
m_processing
Processing CJobManager::m_processing private
Referenced by CancelJob(), CancelJobs(), IsProcessing(), IsProcessing(), OnJobComplete(), OnJobProgress(), PopJob(), and StartWorkers().
m_running
bool CJobManager::m_running private
Referenced by AddJob(), CancelJobs(), CJobManager(), GetNextJob(), and Restart().
m_section
CCriticalSection CJobManager::m_section mutable private
Referenced by AddJob(), CancelJob(), CancelJobs(), GetNextJob(), IsProcessing(), IsProcessing(), OnJobComplete(), OnJobProgress(), PauseJobs(), PopJob(), RemoveWorker(), Restart(), StartWorkers(), and UnPauseJobs().
m_workers
Workers CJobManager::m_workers private
Referenced by CancelJobs(), RemoveWorker(), and StartWorkers().
The documentation for this class was generated from the following files:
JobManager.h
JobManager.cpp