Kodi Documentation: CDVDVideoCodecFFmpeg::CDropControl Struct Reference
CDVDVideoCodecFFmpeg::CDropControl Struct Reference
#include <DVDVideoCodecFFmpeg.h>
Public Types
enum { INIT , VALID }
Public Member Functions
CDropControl ()
void Reset (bool init)
void Process (int64_t pts, bool drop)
Public Attributes
int64_t m_lastPTS
int64_t m_diffPTS
int m_count
enum CDVDVideoCodecFFmpeg::CDropControl:: { ... } m_state
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
INIT
VALID
Constructor & Destructor Documentation
CDropControl()
CDVDVideoCodecFFmpeg::CDropControl::CDropControl ()
References CDVDVideoCodecFFmpeg::Reset().
Member Function Documentation
Process()
void CDVDVideoCodecFFmpeg::CDropControl::Process (int64_t pts, bool drop)
References CLog::Log(), LOGINFO, CDVDVideoCodecFFmpeg::Reset(), and VALID.
Referenced by CDVDVideoCodecFFmpeg::GetPicture().
Reset()
void CDVDVideoCodecFFmpeg::CDropControl::Reset (bool init)
Referenced by CDVDVideoCodecFFmpeg::Open(), and CDVDVideoCodecFFmpeg::Reset().
Member Data Documentation
m_count
int CDVDVideoCodecFFmpeg::CDropControl::m_count
m_diffPTS
int64_t CDVDVideoCodecFFmpeg::CDropControl::m_diffPTS
Referenced by CDVDVideoCodecFFmpeg::GetPicture().
m_lastPTS
int64_t CDVDVideoCodecFFmpeg::CDropControl::m_lastPTS
Referenced by CDVDVideoCodecFFmpeg::GetPicture().
[]
enum { ... } CDVDVideoCodecFFmpeg::CDropControl::m_state
Referenced by CDVDVideoCodecFFmpeg::GetPicture().
The documentation for this struct was generated from the following files:
DVDVideoCodecFFmpeg.h
DVDVideoCodecFFmpeg.cpp