Kodi Documentation: KODI::WINDOWING::X11::CWinSystemX11 Class Reference
KODI::WINDOWING::X11::CWinSystemX11 Class Reference abstract
#include <WinSystemX11.h>
Public Member Functions
CWinSystemX11 ()
~CWinSystemX11 () override
const std::string GetName () override
bool InitWindowSystem () override
bool DestroyWindowSystem () override
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override
bool DestroyWindow () override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
void FinishWindowResize (int newWidth, int newHeight) override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
void UpdateResolutions () override
void ShowOSMouse (bool show) override
void NotifyAppActiveChange (bool bActivated) override
void NotifyAppFocusChange (bool bGaining) override
bool Minimize () override
bool Restore () override
bool Hide () override
bool Show (bool raise=true) override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
bool HasCalibration (const RESOLUTION_INFO &resInfo) override
bool UseLimitedColor () override
std::vector< std::string > GetConnectedOutputs () override
Display * GetDisplay ()
int GetScreen ()
void NotifyXRREvent ()
bool IsCurrentOutput (const std::string &output)
void RecreateWindow ()
int GetCrtc ()
bool MessagePump () override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual CRenderSystemBase * GetRenderSystem ()
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual bool HasCursor ()
virtual bool HasInertialGestures ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual float GetDisplayLatency ()
Get average display latency.
virtual float GetFrameLatencyAdjustment ()
Get time that should be subtracted from the display latency for this frame in milliseconds.
virtual std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock)
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
virtual bool CanDoWindowed ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual std::string GetClipboardText (void)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual bool SetHDR (const VideoPicture *videoPicture)
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
virtual bool IsHDRDisplay ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual CHDRCapabilities GetDisplayHDRCapabilities () const
virtual float GetGuiSdrPeakLuminance () const
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
virtual bool BindTextureUploadContext ()
Binds a shared context to the current thread, in order to upload textures asynchronously.
virtual bool UnbindTextureUploadContext ()
Unbinds the shared context.
virtual bool HasContext ()
Checks if a graphics context is already bound to the current thread.
Protected Member Functions
std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl () override
virtual bool SetWindow (int width, int height, bool fullscreen, const std::string &output, int *winstate=NULL)=0
virtual XVisualInfo * GetVisual ()=0
void OnLostDevice ()
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
Protected Attributes
Window m_glWindow = 0
Window m_mainWindow = 0
int m_screen = 0
Display * m_dpy
Cursor m_invisibleCursor = 0
Pixmap m_icon
bool m_bIsRotated
bool m_bWasFullScreenBeforeMinimize
bool m_minimized
bool m_bIgnoreNextFocusMessage
CCriticalSection m_resourceSection
std::vector< IDispResource * > m_resources
bool m_delayDispReset
XbmcThreads::EndTime m_dispResetTimer
std::string m_currentOutput
std::string m_userOutput
bool m_windowDirty
bool m_bIsInternalXrr
int m_MouseX
int m_MouseY
int m_crtc
CWinEventsX11 * m_winEventsX11
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Private Member Functions
bool IsSuitableVisual (XVisualInfo *vInfo)
bool CreateIconPixmap ()
bool HasWindowManager ()
void UpdateCrtc ()
Static Private Member Functions
static int XErrorHandler (Display *dpy, XErrorEvent *error)
Additional Inherited Members
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Constructor & Destructor Documentation
CWinSystemX11()
CWinSystemX11::CWinSystemX11 ()
References m_bIgnoreNextFocusMessage, m_bIsInternalXrr, m_bWasFullScreenBeforeMinimize, m_delayDispReset, m_dpy, m_minimized, CWinSystemBase::m_winEvents, m_winEventsX11, and XErrorHandler().
~CWinSystemX11()
CWinSystemX11::~CWinSystemX11 () override default
Member Function Documentation
CreateIconPixmap()
bool CWinSystemX11::CreateIconPixmap () private
References CTexture::LoadFromFile(), CLog::Log(), LOGERROR, m_dpy, m_glWindow, and m_icon.
Referenced by SetWindow().
CreateNewWindow()
bool CWinSystemX11::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) override virtual
Implements CWinSystemBase.
Reimplemented in KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
References CWinSystemBase::m_bWindowCreated, and SetFullScreen().
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::CreateNewWindow(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::CreateNewWindow().
DestroyWindow()
bool CWinSystemX11::DestroyWindow () override virtual
Reimplemented from CWinSystemBase.
Reimplemented in KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
References m_dpy, m_glWindow, m_icon, m_invisibleCursor, m_mainWindow, m_winEventsX11, and KODI::WINDOWING::X11::CWinEventsX11::Quit().
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::DestroyWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::DestroyWindow(), and SetWindow().
DestroyWindowSystem()
bool CWinSystemX11::DestroyWindowSystem () override virtual
Reimplemented from CWinSystemBase.
Reimplemented in KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
References RESOLUTION_INFO::fRefreshRate, g_xrandr, CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), XMode::h, XMode::hz, XMode::id, RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, CWinSystemBase::m_bFullScreen, XOutput::name, RES_DESKTOP, CXRandR::SetMode(), RESOLUTION_INFO::strId, RESOLUTION_INFO::strOutput, and XMode::w.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::DestroyWindowSystem(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::DestroyWindowSystem().
FinishWindowResize()
void CWinSystemX11::FinishWindowResize (int newWidth, int newHeight) override virtual
Reimplemented from CWinSystemBase.
Reimplemented in KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
References g_xrandr, CXRandR::GetCurrentMode(), CXRandR::GetModes(), CXRandR::GetOutput(), CServiceBroker::GetSettingsComponent(), XMode::isCurrent, m_currentOutput, m_dpy, m_glWindow, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, m_userOutput, CSettings::SETTING_VIDEOSCREEN_MONITOR, SetWindow(), and UpdateCrtc().
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::FinishWindowResize(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::FinishWindowResize().
GetConnectedOutputs()
std::vector< std::string > CWinSystemX11::GetConnectedOutputs () override virtual
Reimplemented from CWinSystemBase.
References g_xrandr, CXRandR::GetModes(), name, and CXRandR::Query().
GetCrtc()
int KODI::WINDOWING::X11::CWinSystemX11::GetCrtc () inline
References m_crtc.
GetDisplay()
Display * KODI::WINDOWING::X11::CWinSystemX11::GetDisplay () inline
References m_dpy.
Referenced by CX11DPMSSupport::CX11DPMSSupport(), CX11DPMSSupport::DisablePowerSaving(), CX11DPMSSupport::EnablePowerSaving(), and KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext().
GetName()
const std::string KODI::WINDOWING::X11::CWinSystemX11::GetName () inline override virtual
Reimplemented from CWinSystemBase.
GetOSScreenSaverImpl()
std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > CWinSystemX11::GetOSScreenSaverImpl () override protected virtual
Reimplemented from CWinSystemBase.
References m_dpy.
GetScreen()
int KODI::WINDOWING::X11::CWinSystemX11::GetScreen () inline
References m_screen.
Referenced by KODI::WINDOWING::X11::CVideoSyncGLX::Setup().
GetVisual()
virtual XVisualInfo * KODI::WINDOWING::X11::CWinSystemX11::GetVisual () protected pure virtual
Implemented in KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
Referenced by SetWindow().
HasCalibration()
bool CWinSystemX11::HasCalibration (const RESOLUTION_INFO & resInfo) override virtual
Reimplemented from CWinSystemBase.
References OVERSCAN::bottom, RESOLUTION_INFO::fPixelRatio, g_xrandr, CXRandR::GetOutput(), XOutput::hmm, RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, OVERSCAN::left, m_currentOutput, XOutput::name, RESOLUTION_INFO::Overscan, OVERSCAN::right, RESOLUTION_INFO::strOutput, OVERSCAN::top, and XOutput::wmm.
HasWindowManager()
bool CWinSystemX11::HasWindowManager () private
References data(), CLog::Log(), LOGDEBUG, and m_dpy.
Referenced by SetWindow().
Hide()
bool CWinSystemX11::Hide () override virtual
Reimplemented from CWinSystemBase.
References m_dpy, and m_mainWindow.
InitWindowSystem()
bool CWinSystemX11::InitWindowSystem () override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetSettingsComponent(), CWinSystemBase::InitWindowSystem(), CLog::Log(), LOGDEBUG, LOGERROR, m_dpy, and CSettings::SETTING_VIDEOSCREEN_LIMITEDRANGE.
IsCurrentOutput()
bool CWinSystemX11::IsCurrentOutput (const std::string & output)
References m_currentOutput.
IsSuitableVisual()
bool KODI::WINDOWING::X11::CWinSystemX11::IsSuitableVisual (XVisualInfo * vInfo) private
MessagePump()
bool CWinSystemX11::MessagePump () override virtual
Reimplemented from CWinSystemBase.
References CWinSystemBase::m_winEvents.
Minimize()
bool CWinSystemX11::Minimize () override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetAppMessenger(), CWinSystemBase::m_bFullScreen, m_bIgnoreNextFocusMessage, m_bWasFullScreenBeforeMinimize, m_dpy, m_mainWindow, m_minimized, m_screen, and TMSG_TOGGLEFULLSCREEN.
NotifyAppActiveChange()
void CWinSystemX11::NotifyAppActiveChange (bool bActivated) override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetAppMessenger(), CWinSystemBase::m_bFullScreen, m_bWasFullScreenBeforeMinimize, m_minimized, and TMSG_TOGGLEFULLSCREEN.
NotifyAppFocusChange()
void CWinSystemX11::NotifyAppFocusChange (bool bGaining) override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetAppMessenger(), CWinSystemBase::m_bFullScreen, m_bIgnoreNextFocusMessage, m_bWasFullScreenBeforeMinimize, m_minimized, and TMSG_TOGGLEFULLSCREEN.
Referenced by KODI::WINDOWING::X11::CWinEventsX11::MessagePump().
NotifyXRREvent()
void CWinSystemX11::NotifyXRREvent ()
References g_xrandr, CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, LOGERROR, m_bIsInternalXrr, CXRandR::Query(), RecreateWindow(), and UpdateResolutions().
Referenced by KODI::WINDOWING::X11::CWinEventsX11::MessagePump().
OnLostDevice()
void CWinSystemX11::OnLostDevice () protected
References CLog::Log(), LOGDEBUG, m_resources, m_resourceSection, m_winEventsX11, and KODI::WINDOWING::X11::CWinEventsX11::SetXRRFailSafeTimer().
Referenced by SetFullScreen(), and SetWindow().
RecreateWindow()
void CWinSystemX11::RecreateWindow ()
References g_xrandr, CXRandR::GetCurrentMode(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CXRandR::GetOutput(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetWinSystem(), XMode::hz, XMode::id, CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_userOutput, m_windowDirty, XOutput::name, RES_DESKTOP, RES_WINDOW, CDisplaySettings::ResolutionInfoSize(), and CGraphicContext::SetVideoResolution().
Referenced by CX11DPMSSupport::DisablePowerSaving(), and NotifyXRREvent().
Register()
void CWinSystemX11::Register (IDispResource * resource) override virtual
Implements CWinSystemBase.
References m_resources, and m_resourceSection.
ResizeWindow()
bool CWinSystemX11::ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override virtual
Implements CWinSystemBase.
Reimplemented in KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
References g_xrandr, CXRandR::GetCurrentMode(), CXRandR::GetModes(), CXRandR::GetOutput(), CServiceBroker::GetSettingsComponent(), XMode::isCurrent, CWinSystemBase::m_bFullScreen, m_currentOutput, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, m_userOutput, CSettings::SETTING_VIDEOSCREEN_MONITOR, and SetWindow().
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::ResizeWindow(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::ResizeWindow().
Restore()
bool CWinSystemX11::Restore () override virtual
Reimplemented from CWinSystemBase.
SetFullScreen()
bool CWinSystemX11::SetFullScreen (bool fullScreen, RESOLUTION_INFO & res, bool blankOtherDisplays) override virtual
Implements CWinSystemBase.
Reimplemented in KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
References RESOLUTION_INFO::fRefreshRate, g_xrandr, CXRandR::GetCurrentMode(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetSettingsComponent(), XMode::h, XMode::hz, XMode::id, RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, CLog::Log(), LOGINFO, CWinSystemBase::m_bFullScreen, m_bIsInternalXrr, m_bIsRotated, m_currentOutput, m_delayDispReset, m_dispResetTimer, m_dpy, m_mainWindow, m_MouseX, m_MouseY, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, m_userOutput, XMode::name, XOutput::name, OnLostDevice(), RES_DESKTOP, CXRandR::SetMode(), SetWindow(), RESOLUTION_INFO::strId, RESOLUTION_INFO::strOutput, and XMode::w.
Referenced by CreateNewWindow(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetFullScreen(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetFullScreen().
SetWindow()
bool CWinSystemX11::SetWindow (int width, int height, bool fullscreen, const std::string & output, int * winstate = NULL) protected pure virtual
Implemented in KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
References CreateIconPixmap(), DestroyWindow(), g_xrandr, CCompileInfo::GetAppName(), CServiceBroker::GetInputManager(), CXRandR::GetOutput(), GetVisual(), KODI::WINDOWING::X11::CWinEventsX11::HasStructureChanged(), HasWindowManager(), KODI::WINDOWING::X11::CWinEventsX11::Init(), CLog::Log(), LOGERROR, CWinSystemBase::m_bFullScreen, m_bIsInternalXrr, m_currentOutput, m_dpy, m_glWindow, m_icon, m_invisibleCursor, m_mainWindow, m_MouseX, m_MouseY, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, m_screen, m_windowDirty, m_winEventsX11, OnLostDevice(), XOutput::screen, CInputManager::SetMouseActive(), UpdateCrtc(), XOutput::x, and XOutput::y.
Referenced by FinishWindowResize(), ResizeWindow(), SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow().
Show()
bool CWinSystemX11::Show (bool raise = true) override virtual
Reimplemented from CWinSystemBase.
References m_dpy, m_mainWindow, and m_minimized.
ShowOSMouse()
void CWinSystemX11::ShowOSMouse (bool show) override virtual
Reimplemented from CWinSystemBase.
References m_dpy, m_invisibleCursor, and m_mainWindow.
Unregister()
void CWinSystemX11::Unregister (IDispResource * resource) override virtual
Implements CWinSystemBase.
References m_resources, and m_resourceSection.
Referenced by KODI::WINDOWING::X11::CVideoSyncGLX::Cleanup(), and KODI::WINDOWING::X11::CVideoSyncOML::Cleanup().
UpdateCrtc()
void CWinSystemX11::UpdateCrtc () private
References g_xrandr, CXRandR::GetCrtc(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), m_crtc, m_dpy, m_mainWindow, m_screen, and CGraphicContext::SetFPS().
Referenced by FinishWindowResize(), and SetWindow().
UpdateResolutions()
void CWinSystemX11::UpdateResolutions () override virtual
Reimplemented from CWinSystemBase.
References CDisplaySettings::AddResolutionInfo(), CDisplaySettings::ApplyCalibrations(), RESOLUTION_INFO::bFullScreen, CDisplaySettings::ClearCustomResolutions(), D3DPRESENTFLAG_INTERLACED, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fPixelRatio, RESOLUTION_INFO::fRefreshRate, g_xrandr, CXRandR::GetCurrentMode(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CXRandR::GetModes(), CXRandR::GetOutput(), CXRandR::GetPreferredMode(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), XMode::h, XOutput::hmm, XMode::hz, XMode::id, RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, XMode::isCurrent, XOutput::isRotated, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, CLog::Log(), LOGINFO, m_bIsRotated, m_dpy, m_screen, m_userOutput, XOutput::modes, name, XOutput::name, CXRandR::Query(), RES_DESKTOP, CGraphicContext::ResetOverscan(), CXRandR::SetNumScreens(), CSettings::SETTING_VIDEOSCREEN_BLANKDISPLAYS, CSettings::SETTING_VIDEOSCREEN_MONITOR, RESOLUTION_INFO::strId, RESOLUTION_INFO::strMode, RESOLUTION_INFO::strOutput, CXRandR::TurnOffOutput(), CXRandR::TurnOnOutput(), CWinSystemBase::UpdateDesktopResolution(), CWinSystemBase::UpdateResolutions(), XMode::w, and XOutput::wmm.
Referenced by NotifyXRREvent().
UseLimitedColor()
bool CWinSystemX11::UseLimitedColor () override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOSCREEN_LIMITEDRANGE.
XErrorHandler()
int CWinSystemX11::XErrorHandler (Display * dpy, XErrorEvent * error) static private
References CLog::Log(), and LOGERROR.
Referenced by CWinSystemX11().
Member Data Documentation
m_bIgnoreNextFocusMessage
bool KODI::WINDOWING::X11::CWinSystemX11::m_bIgnoreNextFocusMessage protected
Referenced by CWinSystemX11(), Minimize(), and NotifyAppFocusChange().
m_bIsInternalXrr
bool KODI::WINDOWING::X11::CWinSystemX11::m_bIsInternalXrr protected
Referenced by CWinSystemX11(), NotifyXRREvent(), SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), SetWindow(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow().
m_bIsRotated
bool KODI::WINDOWING::X11::CWinSystemX11::m_bIsRotated protected
Referenced by SetFullScreen(), and UpdateResolutions().
m_bWasFullScreenBeforeMinimize
bool KODI::WINDOWING::X11::CWinSystemX11::m_bWasFullScreenBeforeMinimize protected
Referenced by CWinSystemX11(), Minimize(), NotifyAppActiveChange(), and NotifyAppFocusChange().
m_crtc
int KODI::WINDOWING::X11::CWinSystemX11::m_crtc protected
Referenced by GetCrtc(), and UpdateCrtc().
m_currentOutput
std::string KODI::WINDOWING::X11::CWinSystemX11::m_currentOutput protected
Referenced by FinishWindowResize(), HasCalibration(), IsCurrentOutput(), ResizeWindow(), SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), SetWindow(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow().
m_delayDispReset
bool KODI::WINDOWING::X11::CWinSystemX11::m_delayDispReset protected
Referenced by CWinSystemX11(), KODI::WINDOWING::X11::CWinSystemX11GLContext::PresentRenderImpl(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::PresentRenderImpl(), SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow().
m_dispResetTimer
XbmcThreads::EndTime KODI::WINDOWING::X11::CWinSystemX11::m_dispResetTimer protected
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::PresentRenderImpl(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::PresentRenderImpl(), and SetFullScreen().
m_dpy
Display* KODI::WINDOWING::X11::CWinSystemX11::m_dpy protected
Referenced by CreateIconPixmap(), CWinSystemX11(), DestroyWindow(), FinishWindowResize(), GetDisplay(), GetOSScreenSaverImpl(), KODI::WINDOWING::X11::CWinSystemX11GLContext::GetVisual(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::GetVisual(), HasWindowManager(), Hide(), InitWindowSystem(), Minimize(), KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::RefreshGLContext(), SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), SetWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow(), Show(), ShowOSMouse(), UpdateCrtc(), and UpdateResolutions().
m_glWindow
Window KODI::WINDOWING::X11::CWinSystemX11::m_glWindow = 0 protected
Referenced by CreateIconPixmap(), DestroyWindow(), FinishWindowResize(), KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::RefreshGLContext(), and SetWindow().
m_icon
Pixmap KODI::WINDOWING::X11::CWinSystemX11::m_icon protected
Referenced by CreateIconPixmap(), DestroyWindow(), and SetWindow().
m_invisibleCursor
Cursor KODI::WINDOWING::X11::CWinSystemX11::m_invisibleCursor = 0 protected
Referenced by DestroyWindow(), SetWindow(), and ShowOSMouse().
m_mainWindow
Window KODI::WINDOWING::X11::CWinSystemX11::m_mainWindow = 0 protected
Referenced by DestroyWindow(), Hide(), Minimize(), SetFullScreen(), SetWindow(), Show(), ShowOSMouse(), and UpdateCrtc().
m_minimized
bool KODI::WINDOWING::X11::CWinSystemX11::m_minimized protected
Referenced by CWinSystemX11(), Minimize(), NotifyAppActiveChange(), NotifyAppFocusChange(), and Show().
m_MouseX
int KODI::WINDOWING::X11::CWinSystemX11::m_MouseX protected
Referenced by SetFullScreen(), and SetWindow().
m_MouseY
int KODI::WINDOWING::X11::CWinSystemX11::m_MouseY protected
Referenced by SetFullScreen(), and SetWindow().
m_resources
std::vector<IDispResource*> KODI::WINDOWING::X11::CWinSystemX11::m_resources protected
Referenced by OnLostDevice(), KODI::WINDOWING::X11::CWinSystemX11GLContext::PresentRenderImpl(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::PresentRenderImpl(), Register(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow(), and Unregister().
m_resourceSection
CCriticalSection KODI::WINDOWING::X11::CWinSystemX11::m_resourceSection protected
Referenced by OnLostDevice(), KODI::WINDOWING::X11::CWinSystemX11GLContext::PresentRenderImpl(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::PresentRenderImpl(), Register(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow(), and Unregister().
m_screen
int KODI::WINDOWING::X11::CWinSystemX11::m_screen = 0 protected
Referenced by GetScreen(), KODI::WINDOWING::X11::CWinSystemX11GLContext::GetVisual(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::GetVisual(), Minimize(), KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::RefreshGLContext(), SetWindow(), UpdateCrtc(), and UpdateResolutions().
m_userOutput
std::string KODI::WINDOWING::X11::CWinSystemX11::m_userOutput protected
Referenced by FinishWindowResize(), RecreateWindow(), ResizeWindow(), SetFullScreen(), and UpdateResolutions().
m_windowDirty
bool KODI::WINDOWING::X11::CWinSystemX11::m_windowDirty protected
Referenced by RecreateWindow(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), SetWindow(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow().
m_winEventsX11
CWinEventsX11* KODI::WINDOWING::X11::CWinSystemX11::m_winEventsX11 protected
Referenced by CWinSystemX11(), DestroyWindow(), OnLostDevice(), and SetWindow().
The documentation for this class was generated from the following files:
WinSystemX11.h
WinSystemX11.cpp