Kodi Documentation: Variant.h File Reference
Variant.h File Reference
#include <map>
#include <stdint.h>
#include <string>
#include <string_view>
#include <variant>
#include <vector>
#include <wchar.h>
Classes
class CVariant
struct CVariant::Null
struct CVariant::ConstNull
Functions
int64_t str2int64 (std::string_view, int64_t fallback=0)
int64_t str2int64 (std::wstring_view, int64_t fallback=0)
uint64_t str2uint64 (std::string_view, uint64_t fallback=0)
uint64_t str2uint64 (std::wstring_view, uint64_t fallback=0)
double str2double (std::string_view, double fallback=0.0)
double str2double (std::wstring_view, double fallback=0.0)
Function Documentation
str2double() [1/2]
double str2double (std::string_view str, double fallback = 0.0)
References end(), and trim().
str2double() [2/2]
double str2double (std::wstring_view str, double fallback = 0.0)
References end(), and trim().
str2int64() [1/2]
int64_t str2int64 (std::string_view str, int64_t fallback = 0)
References int64_t(), and trim().
Referenced by CVariant::asInteger().
str2int64() [2/2]
int64_t str2int64 (std::wstring_view str, int64_t fallback = 0)
References end(), int64_t(), trim(), and wcstoll.
str2uint64() [1/2]
uint64_t str2uint64 (std::string_view str, uint64_t fallback = 0)
References trim().
Referenced by CVariant::asDouble(), CVariant::asUnsignedInteger(), TestWebServer::CheckRangesTestFileResponse(), CVideoInfoTag::GetDurationFromMinuteString(), and CHttpRanges::Parse().
str2uint64() [2/2]
uint64_t str2uint64 (std::wstring_view str, uint64_t fallback = 0)
References end(), trim(), and wcstoull.