Kodi Documentation: KODI::ADDONS::CVisualization Class Reference
KODI::ADDONS::CVisualization Class Reference
#include <Visualization.h>
Public Member Functions
CVisualization (const ADDON::AddonInfoPtr &addonInfo, float x, float y, float w, float h)
~CVisualization () override
bool Start (int channels, int samplesPerSec, int bitsPerSample, const std::string &songName)
void Stop ()
void AudioData (const float *audioData, int audioDataLength)
bool IsDirty ()
void Render ()
int GetSyncDelay ()
bool NextPreset ()
bool PrevPreset ()
bool LoadPreset (int select)
bool RandomPreset ()
bool LockPreset ()
bool RatePreset (bool plus_minus)
bool UpdateAlbumart (const char *albumart)
bool UpdateTrack (const KODI_ADDON_VISUALIZATION_TRACK *track)
bool HasPresets ()
bool GetPresetList (std::vector< std::string > &vecpresets)
int GetActivePreset ()
std::string GetActivePresetName ()
bool IsLocked ()
void GetProperties (struct KODI_ADDON_VISUALIZATION_PROPS *props)
void TransferPreset (const std::string &preset)
void ClearPresets ()
Public Member Functions inherited from ADDON::IAddonInstanceHandler
IAddonInstanceHandler (ADDON_TYPE type, const AddonInfoPtr &addonInfo, AddonInstanceId instanceId=ADDON_INSTANCE_ID_UNUSED, KODI_HANDLE parentInstance=nullptr, const std::string &uniqueWorkID="")
Class constructor for handling add-on instance processes, allowing an add-on to handle multiple work simultaneously and independently.
virtual ~IAddonInstanceHandler ()
ADDON_TYPE UsedType () const
AddonInstanceId InstanceId () const
const std::string & UniqueWorkID ()
std::string ID () const
AddonInstanceId InstanceID () const
std::string Name () const
std::string Author () const
std::string Icon () const
std::string Path () const
std::string Profile () const
CAddonVersion Version () const
ADDON_STATUS CreateInstance ()
void DestroyInstance ()
const AddonDllPtr & Addon () const
AddonInfoPtr GetAddonInfo () const
virtual void OnPreInstall ()
virtual void OnPostInstall (bool update, bool modal)
virtual void OnPreUnInstall ()
virtual void OnPostUnInstall ()
Private Attributes
const int m_x
const int m_y
const int m_width
const int m_height
std::vector< std::string > m_presets
Additional Inherited Members
Protected Attributes inherited from ADDON::IAddonInstanceHandler
KODI_ADDON_INSTANCE_INFO m_info {}
KODI_ADDON_INSTANCE_STRUCT m_ifc {}
Constructor & Destructor Documentation
CVisualization()
CVisualization::CVisualization (const ADDON::AddonInfoPtr & addonInfo, float x, float y, float w, float h)
References ADDON_STATUS_OK, AddonToKodiFuncTable_Visualization::clear_presets, ADDON::IAddonInstanceHandler::CreateInstance(), KodiToAddonFuncTable_Visualization::get_presets, AddonToKodiFuncTable_Visualization::get_properties, KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::ID(), CLog::Log(), LOGFATAL, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, AddonInstance_Visualization::toKodi, AddonToKodiFuncTable_Visualization::transfer_preset, and KODI_ADDON_INSTANCE_STRUCT::visualization.
~CVisualization()
CVisualization::~CVisualization () override
References ADDON::IAddonInstanceHandler::DestroyInstance(), ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, AddonInstance_Visualization::toKodi, and KODI_ADDON_INSTANCE_STRUCT::visualization.
Member Function Documentation
AudioData()
void CVisualization::AudioData (const float * audioData, int audioDataLength)
References KodiToAddonFuncTable_Visualization::audio_data, KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
ClearPresets()
void CVisualization::ClearPresets ()
References m_presets.
GetActivePreset()
int CVisualization::GetActivePreset ()
References KodiToAddonFuncTable_Visualization::get_active_preset, KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
Referenced by GetActivePresetName().
GetActivePresetName()
std::string CVisualization::GetActivePresetName ()
References GetActivePreset(), and m_presets.
GetPresetList()
bool CVisualization::GetPresetList (std::vector< std::string > & vecpresets)
References m_presets.
GetProperties()
void CVisualization::GetProperties (struct KODI_ADDON_VISUALIZATION_PROPS * props)
References KODI_ADDON_VISUALIZATION_PROPS::device, CServiceBroker::GetWinSystem(), KODI_ADDON_VISUALIZATION_PROPS::height, m_height, m_width, m_x, m_y, KODI_ADDON_VISUALIZATION_PROPS::pixelRatio, KODI_ADDON_VISUALIZATION_PROPS::width, KODI_ADDON_VISUALIZATION_PROPS::x, and KODI_ADDON_VISUALIZATION_PROPS::y.
GetSyncDelay()
int CVisualization::GetSyncDelay ()
References KodiToAddonFuncTable_Visualization::get_sync_delay, KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
HasPresets()
bool CVisualization::HasPresets ()
References m_presets.
IsDirty()
bool CVisualization::IsDirty ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, KodiToAddonFuncTable_Visualization::is_dirty, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
IsLocked()
bool CVisualization::IsLocked ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, KodiToAddonFuncTable_Visualization::is_locked, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
LoadPreset()
bool CVisualization::LoadPreset (int select)
References KODI_ADDON_INSTANCE_STRUCT::hdl, KodiToAddonFuncTable_Visualization::load_preset, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
LockPreset()
bool CVisualization::LockPreset ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, KodiToAddonFuncTable_Visualization::lock_preset, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
NextPreset()
bool CVisualization::NextPreset ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, KodiToAddonFuncTable_Visualization::next_preset, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
PrevPreset()
bool CVisualization::PrevPreset ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, KodiToAddonFuncTable_Visualization::prev_preset, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
RandomPreset()
bool CVisualization::RandomPreset ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, KodiToAddonFuncTable_Visualization::random_preset, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
RatePreset()
bool CVisualization::RatePreset (bool plus_minus)
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, KodiToAddonFuncTable_Visualization::rate_preset, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
Render()
void CVisualization::Render ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, KodiToAddonFuncTable_Visualization::render, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
Start()
bool CVisualization::Start (int channels, int samplesPerSec, int bitsPerSample, const std::string & songName)
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, KodiToAddonFuncTable_Visualization::start, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
Stop()
void CVisualization::Stop ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, KodiToAddonFuncTable_Visualization::stop, AddonInstance_Visualization::toAddon, and KODI_ADDON_INSTANCE_STRUCT::visualization.
TransferPreset()
void CVisualization::TransferPreset (const std::string & preset)
References m_presets.
UpdateAlbumart()
bool CVisualization::UpdateAlbumart (const char * albumart)
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, KodiToAddonFuncTable_Visualization::update_albumart, and KODI_ADDON_INSTANCE_STRUCT::visualization.
UpdateTrack()
bool CVisualization::UpdateTrack (const KODI_ADDON_VISUALIZATION_TRACK * track)
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_Visualization::toAddon, KodiToAddonFuncTable_Visualization::update_track, and KODI_ADDON_INSTANCE_STRUCT::visualization.
Member Data Documentation
m_height
const int KODI::ADDONS::CVisualization::m_height private
Referenced by GetProperties().
m_presets
std::vector<std::string> KODI::ADDONS::CVisualization::m_presets private
cached preset list
Referenced by ClearPresets(), GetActivePresetName(), GetPresetList(), HasPresets(), and TransferPreset().
m_width
const int KODI::ADDONS::CVisualization::m_width private
Referenced by GetProperties().
m_x
const int KODI::ADDONS::CVisualization::m_x private
Referenced by GetProperties().
m_y
const int KODI::ADDONS::CVisualization::m_y private
Referenced by GetProperties().
The documentation for this class was generated from the following files:
Visualization.h
Visualization.cpp