Kodi Documentation: TestKeyboardTranslator.cpp File Reference
TestKeyboardTranslator.cpp File Reference
#include "ServiceBroker.h"
#include "addons/AddonManager.h"
#include "addons/addoninfo/AddonType.h"
#include "games/controllers/Controller.h"
#include "games/controllers/ControllerIDs.h"
#include "games/controllers/input/PhysicalFeature.h"
#include "input/keyboard/KeyboardTranslator.h"
#include <gtest/gtest.h>
Functions
TEST (TestKeyboardTranslator, TranslateKeys)
Function Documentation
TEST()
TEST (TestKeyboardTranslator , TranslateKeys)
References ASSERT_NE(), ADDON::CHOICE_YES, DEFAULT_KEYBOARD_ID, EXPECT_EQ(), EXPECT_NE(), EXPECT_TRUE(), ADDON::GAME_CONTROLLER, ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), KODI::KEYBOARD::CKeyboardTranslator::TranslateKeycode(), and KODI::KEYBOARD::CKeyboardTranslator::TranslateKeysym().