Kodi Documentation: CBufferObjectFactory Class Reference
CBufferObjectFactory Class Reference
Factory that provides CBufferObject registration and creation.
#include <BufferObjectFactory.h>
Static Public Member Functions
static std::unique_ptr< CBufferObject > CreateBufferObject (bool needsCreateBySize)
Create a CBufferObject from the registered BufferObject types. In the future this may include some criteria for selecting a specific CBufferObject derived type. Currently it returns the CBufferObject implementation that was registered last.
static void RegisterBufferObject (const std::function< std::unique_ptr< CBufferObject >()> &)
Registers a CBufferObject class to class to the factory.
static void ClearBufferObjects ()
Clears the list of registered CBufferObject types.
Static Protected Attributes
static std::list< std::function< std::unique_ptr< CBufferObject >()> > m_bufferObjects
Detailed Description
Factory that provides CBufferObject registration and creation.
Member Function Documentation
ClearBufferObjects()
void CBufferObjectFactory::ClearBufferObjects () static
Clears the list of registered CBufferObject types.
References m_bufferObjects.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::InitWindowSystem(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::InitWindowSystem().
CreateBufferObject()
std::unique_ptr< CBufferObject > CBufferObjectFactory::CreateBufferObject (bool needsCreateBySize) static
Create a CBufferObject from the registered BufferObject types. In the future this may include some criteria for selecting a specific CBufferObject derived type. Currently it returns the CBufferObject implementation that was registered last.
Returns
std::unique_ptr<CBufferObject>
References m_bufferObjects.
Referenced by KODI::RETRO::CRendererFactoryDMA::CreateBufferPools(), CBufferObject::GetBufferObject(), and CVideoBufferPoolDMA::Released().
RegisterBufferObject()
void CBufferObjectFactory::RegisterBufferObject (const std::function< std::unique_ptr< CBufferObject >()> & createFunc) static
Registers a CBufferObject class to class to the factory.
References m_bufferObjects.
Referenced by CDMAHeapBufferObject::Register(), CDumbBufferObject::Register(), CGBMBufferObject::Register(), and CUDMABufferObject::Register().
Member Data Documentation
m_bufferObjects
std::list< std::function< std::unique_ptr< CBufferObject >()> > CBufferObjectFactory::m_bufferObjects static protected
Referenced by ClearBufferObjects(), CreateBufferObject(), and RegisterBufferObject().
The documentation for this class was generated from the following files:
BufferObjectFactory.h
BufferObjectFactory.cpp