Kodi Documentation: KODI::GAME::CGameClientJoystick Class Reference
KODI::GAME::CGameClientJoystick Class Reference
Games
Handles game controller events for games.
#include <GameClientJoystick.h>
Public Member Functions
CGameClientJoystick (CGameClient &addon, const std::string &portAddress, const ControllerPtr &controller)
Constructor.
~CGameClientJoystick () override
void RegisterInput (JOYSTICK::IInputProvider *inputProvider)
void UnregisterInput (JOYSTICK::IInputProvider *inputProvider)
std::string ControllerID () const override
The add-on ID of the game controller associated with this input handler.
bool HasFeature (const std::string &feature) const override
Return true if the input handler accepts the given feature.
bool AcceptsInput (const std::string &feature) const override
Return true if the input handler is currently accepting input for the given feature.
bool OnButtonPress (const std::string &feature, bool bPressed) override
A digital button has been pressed or released.
void OnButtonHold (const std::string &feature, unsigned int holdTimeMs) override
A digital button has been pressed for more than one event frame.
bool OnButtonMotion (const std::string &feature, float magnitude, unsigned int motionTimeMs) override
An analog button (trigger or a pressure-sensitive button) has changed state.
bool OnAnalogStickMotion (const std::string &feature, float x, float y, unsigned int motionTimeMs) override
An analog stick has moved.
bool OnAccelerometerMotion (const std::string &feature, float x, float y, float z) override
An accelerometer's state has changed.
bool OnWheelMotion (const std::string &feature, float position, unsigned int motionTimeMs) override
A wheel has changed state.
bool OnThrottleMotion (const std::string &feature, float position, unsigned int motionTimeMs) override
A throttle has changed state.
void OnInputFrame () override
Called at the end of the frame that provided input.
const std::string & GetPortAddress () const
ControllerPtr GetController () const
std::string GetControllerAddress () const
PERIPHERALS::PeripheralPtr GetSource () const
std::string GetSourceLocation () const
float GetActivation () const
void SetSource (PERIPHERALS::PeripheralPtr sourcePeripheral)
void ClearSource ()
bool SetRumble (const std::string &feature, float magnitude)
Public Member Functions inherited from KODI::JOYSTICK::IInputHandler
virtual ~IInputHandler ()=default
void SetInputReceiver (IInputReceiver *receiver)
void ResetInputReceiver (void)
IInputReceiver * InputReceiver (void)
Private Attributes
CGameClient & m_gameClient
const std::string m_portAddress
const ControllerPtr m_controller
std::unique_ptr< CPortInput > m_portInput
PERIPHERALS::PeripheralPtr m_sourcePeripheral
Detailed Description
Handles game controller events for games.
Listens to game controller events and forwards them to the games (as game_input_event).
Constructor & Destructor Documentation
CGameClientJoystick()
CGameClientJoystick::CGameClientJoystick (CGameClient & addon, const std::string & portAddress, const ControllerPtr & controller)
Constructor.
Parameters
addon The game client implementation.
port The port this game controller is associated with.
controller The game controller which is used (for controller mapping).
dllStruct The emulator or game to which the events are sent.
References m_controller.
~CGameClientJoystick()
CGameClientJoystick::~CGameClientJoystick () override default
Member Function Documentation
AcceptsInput()
bool CGameClientJoystick::AcceptsInput (const std::string & feature) const override virtual
Return true if the input handler is currently accepting input for the given feature.
Parameters
feature A feature belonging to the controller specified by ControllerID()
Returns
True if the feature is currently accepting input, false otherwise
This does not prevent the input events from being called, but can return false to indicate that input wasn't handled for the specified feature.
Implements KODI::JOYSTICK::IInputHandler.
References KODI::GAME::CGameClientInput::AcceptsInput(), KODI::GAME::CGameClient::Input(), and m_gameClient.
ClearSource()
void CGameClientJoystick::ClearSource ()
References m_sourcePeripheral.
ControllerID()
std::string CGameClientJoystick::ControllerID () const override virtual
The add-on ID of the game controller associated with this input handler.
Returns
The ID of the add-on extending kodi.game.controller
Implements KODI::JOYSTICK::IInputHandler.
References m_controller.
GetActivation()
float CGameClientJoystick::GetActivation () const
References m_portInput.
GetController()
ControllerPtr KODI::GAME::CGameClientJoystick::GetController () const inline
References m_controller.
GetControllerAddress()
std::string CGameClientJoystick::GetControllerAddress () const
References m_controller, m_portAddress, and KODI::GAME::CGameClientTopology::MakeAddress().
GetPortAddress()
const std::string & KODI::GAME::CGameClientJoystick::GetPortAddress () const inline
References m_portAddress.
GetSource()
PERIPHERALS::PeripheralPtr KODI::GAME::CGameClientJoystick::GetSource () const inline
References m_sourcePeripheral.
GetSourceLocation()
std::string CGameClientJoystick::GetSourceLocation () const
References m_sourcePeripheral.
HasFeature()
bool CGameClientJoystick::HasFeature (const std::string & feature) const override virtual
Return true if the input handler accepts the given feature.
Parameters
feature A feature belonging to the controller specified by ControllerID()
Returns
True if the feature is used for input, false otherwise
Implements KODI::JOYSTICK::IInputHandler.
References KODI::GAME::CGameClientInput::HasFeature(), KODI::GAME::CGameClient::Input(), m_controller, and m_gameClient.
OnAccelerometerMotion()
bool CGameClientJoystick::OnAccelerometerMotion (const std::string & feature, float x, float y, float z) override virtual
An accelerometer's state has changed.
Parameters
feature The accelerometer being accelerated
x The x coordinate in the closed interval [-1, 1]
y The y coordinate in the closed interval [-1, 1]
z The z coordinate in the closed interval [-1, 1]
Returns
True if the event was handled otherwise false
Reimplemented from KODI::JOYSTICK::IInputHandler.
References GAME_INPUT_EVENT_ACCELEROMETER, GAME_PORT_CONTROLLER, KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), m_controller, m_gameClient, m_portAddress, and game_input_event::type.
OnAnalogStickMotion()
bool CGameClientJoystick::OnAnalogStickMotion (const std::string & feature, float x, float y, unsigned int motionTimeMs) override virtual
An analog stick has moved.
Parameters
feature The analog stick being moved
x The x coordinate in the closed interval [-1, 1]
y The y coordinate in the closed interval [-1, 1]
motionTimeMs The time elapsed since this analog stick was centered, or 0 if the analog stick is centered
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References GAME_INPUT_EVENT_ANALOG_STICK, GAME_PORT_CONTROLLER, KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), m_controller, m_gameClient, m_portAddress, and game_input_event::type.
OnButtonHold()
void KODI::GAME::CGameClientJoystick::OnButtonHold (const std::string & feature, unsigned int holdTimeMs) inline override virtual
A digital button has been pressed for more than one event frame.
Parameters
feature The feature being held
holdTimeMs The time elapsed since the initial press (ms)
If OnButtonPress() returns true for the initial press, then this callback is invoked on subsequent frames until the button is released.
Implements KODI::JOYSTICK::IInputHandler.
OnButtonMotion()
bool CGameClientJoystick::OnButtonMotion (const std::string & feature, float magnitude, unsigned int motionTimeMs) override virtual
An analog button (trigger or a pressure-sensitive button) has changed state.
Parameters
feature The feature changing state
magnitude The button pressure or trigger travel distance in the closed interval [0, 1]
motionTimeMs The time elapsed since the magnitude was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References GAME_INPUT_EVENT_ANALOG_BUTTON, GAME_PORT_CONTROLLER, KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), m_controller, m_gameClient, m_portAddress, and game_input_event::type.
OnButtonPress()
bool CGameClientJoystick::OnButtonPress (const std::string & feature, bool bPressed) override virtual
A digital button has been pressed or released.
Parameters
feature The feature being pressed
bPressed True if pressed, false if released
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References GAME_INPUT_EVENT_DIGITAL_BUTTON, GAME_PORT_CONTROLLER, KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), m_controller, m_gameClient, m_portAddress, and game_input_event::type.
OnInputFrame()
void KODI::GAME::CGameClientJoystick::OnInputFrame () inline override virtual
Called at the end of the frame that provided input.
Implements KODI::JOYSTICK::IInputHandler.
OnThrottleMotion()
bool CGameClientJoystick::OnThrottleMotion (const std::string & feature, float position, unsigned int motionTimeMs) override virtual
A throttle has changed state.
Up is positive position, down is negative position.
Parameters
feature The wheel changing state
position The position in the closed interval [-1, 1]
motionTimeMs The time elapsed since the position was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References GAME_INPUT_EVENT_AXIS, GAME_PORT_CONTROLLER, KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), m_controller, m_gameClient, m_portAddress, and game_input_event::type.
OnWheelMotion()
bool CGameClientJoystick::OnWheelMotion (const std::string & feature, float position, unsigned int motionTimeMs) override virtual
A wheel has changed state.
Left is negative position, right is positive position
Parameters
feature The wheel changing state
position The position in the closed interval [-1, 1]
motionTimeMs The time elapsed since the position was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References GAME_INPUT_EVENT_AXIS, GAME_PORT_CONTROLLER, KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), m_controller, m_gameClient, m_portAddress, and game_input_event::type.
RegisterInput()
void CGameClientJoystick::RegisterInput (JOYSTICK::IInputProvider * inputProvider)
References m_portInput.
SetRumble()
bool CGameClientJoystick::SetRumble (const std::string & feature, float magnitude)
References KODI::JOYSTICK::IInputHandler::InputReceiver(), and KODI::JOYSTICK::IInputReceiver::SetRumbleState().
SetSource()
void CGameClientJoystick::SetSource (PERIPHERALS::PeripheralPtr sourcePeripheral)
References m_sourcePeripheral.
UnregisterInput()
void CGameClientJoystick::UnregisterInput (JOYSTICK::IInputProvider * inputProvider)
References m_portInput.
Member Data Documentation
m_controller
const ControllerPtr KODI::GAME::CGameClientJoystick::m_controller private
Referenced by CGameClientJoystick(), ControllerID(), GetController(), GetControllerAddress(), HasFeature(), OnAccelerometerMotion(), OnAnalogStickMotion(), OnButtonMotion(), OnButtonPress(), OnThrottleMotion(), and OnWheelMotion().
m_gameClient
CGameClient& KODI::GAME::CGameClientJoystick::m_gameClient private
Referenced by AcceptsInput(), HasFeature(), OnAccelerometerMotion(), OnAnalogStickMotion(), OnButtonMotion(), OnButtonPress(), OnThrottleMotion(), and OnWheelMotion().
m_portAddress
const std::string KODI::GAME::CGameClientJoystick::m_portAddress private
Referenced by GetControllerAddress(), GetPortAddress(), OnAccelerometerMotion(), OnAnalogStickMotion(), OnButtonMotion(), OnButtonPress(), OnThrottleMotion(), and OnWheelMotion().
m_portInput
std::unique_ptr<CPortInput> KODI::GAME::CGameClientJoystick::m_portInput private
Referenced by GetActivation(), RegisterInput(), and UnregisterInput().
m_sourcePeripheral
PERIPHERALS::PeripheralPtr KODI::GAME::CGameClientJoystick::m_sourcePeripheral private
Referenced by ClearSource(), GetSource(), GetSourceLocation(), and SetSource().
The documentation for this class was generated from the following files:
GameClientJoystick.h
GameClientJoystick.cpp