Kodi Documentation: MUSIC_INFO::CMusicInfoLoader Class Reference
MUSIC_INFO::CMusicInfoLoader Class Reference
#include <MusicInfoLoader.h>
Public Member Functions
CMusicInfoLoader ()
~CMusicInfoLoader () override
void UseCacheOnHD (const std::string &strFileName)
bool LoadItem (CFileItem *pItem) override
bool LoadItemCached (CFileItem *pItem) override
bool LoadItemLookup (CFileItem *pItem) override
Public Member Functions inherited from CBackgroundInfoLoader
CBackgroundInfoLoader ()
~CBackgroundInfoLoader () override
void Load (CFileItemList &items)
bool IsLoading ()
void Run () override
void SetObserver (IBackgroundLoaderObserver *pObserver)
void SetProgressCallback (IProgressCallback *pCallback)
void StopThread ()
void StopAsync ()
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Static Public Member Functions
static bool LoadAdditionalTagInfo (CFileItem *pItem)
Protected Member Functions
void OnLoaderStart () override
void OnLoaderFinish () override
void LoadCache (const std::string &strFileName, CFileItemList &items)
void SaveCache (const std::string &strFileName, CFileItemList &items)
Protected Attributes
std::string m_strCacheFileName
CFileItemList * m_mapFileItems
MAPSONGS m_songsMap
std::string m_strPrevPath
CMusicDatabase m_musicDatabase
unsigned int m_databaseHits = 0
unsigned int m_tagReads = 0
CMusicThumbLoader * m_thumbLoader
Protected Attributes inherited from CBackgroundInfoLoader
CFileItemList * m_pVecItems {nullptr}
std::vector< CFileItemPtr > m_vecItems
CCriticalSection m_lock
volatile bool m_bIsLoading {false}
volatile bool m_bStop {true}
CThread * m_thread {nullptr}
IBackgroundLoaderObserver * m_pObserver {nullptr}
IProgressCallback * m_pProgressCallback {nullptr}
Constructor & Destructor Documentation
CMusicInfoLoader()
CMusicInfoLoader::CMusicInfoLoader ()
References m_mapFileItems, and m_thumbLoader.
~CMusicInfoLoader()
CMusicInfoLoader::~CMusicInfoLoader () override
References m_mapFileItems, m_thumbLoader, and CBackgroundInfoLoader::StopThread().
Member Function Documentation
LoadAdditionalTagInfo()
bool CMusicInfoLoader::LoadAdditionalTagInfo (CFileItem * pItem) static
References CVariant::begin_array(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), CMusicDatabase::GetAlbum(), CMusicDatabase::GetAlbumFromSong(), MUSIC_INFO::CMusicInfoTag::GetAlbumId(), CMusicDatabase::GetArtist(), CMusicDatabase::GetArtistFromSong(), MUSIC_INFO::CMusicInfoTag::GetDatabaseId(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), CGUIListItem::GetProperty(), MUSIC_INFO::CMusicInfoTag::GetType(), MUSIC_INFO::CMusicInfoTag::GetURL(), CFileItem::HasMusicInfoTag(), CGUIListItem::HasProperty(), CVariant::isArray(), KODI::MUSIC::IsAudio(), KODI::NETWORK::IsInternetStream(), CFileItem::IsNFO(), KODI::PLAYLIST::IsPlayList(), CLog::Log(), LOGDEBUG, CGUIListItem::m_bIsFolder, MediaTypeSong, CMusicDatabase::Open(), MUSIC_INFO::CMusicInfoTag::SetLyrics(), CMusicDatabase::SetPropertiesFromAlbum(), CMusicDatabase::SetPropertiesFromArtist(), and CGUIListItem::SetProperty().
Referenced by CGetSongInfoJob::DoWork(), and KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem().
LoadCache()
void CMusicInfoLoader::LoadCache (const std::string & strFileName, CFileItemList & items) protected
References CFileItemList::Add(), CArchive::Close(), CArchive::load, and CFileItemList::SetFastLookup().
Referenced by OnLoaderStart().
LoadItem()
bool CMusicInfoLoader::LoadItem (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References LoadItemCached(), and LoadItemLookup().
LoadItemCached()
bool CMusicInfoLoader::LoadItemCached (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References CFileItem::GetPath(), KODI::MUSIC::IsAudio(), KODI::NETWORK::IsInternetStream(), KODI::MUSIC::IsMusicDb(), CFileItem::IsNFO(), KODI::PLAYLIST::IsPlayList(), KODI::PLAYLIST::IsSmartPlayList(), CMusicThumbLoader::LoadItem(), CGUIListItem::m_bIsFolder, and m_thumbLoader.
Referenced by LoadItem().
LoadItemLookup()
bool CMusicInfoLoader::LoadItemLookup (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References URIUtils::AddSlashAtEnd(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), URIUtils::GetDirectory(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), CMusicDatabase::GetSong(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetSongId(), CMusicDatabase::GetSongsByPath(), CFileItem::HasMusicInfoTag(), KODI::MUSIC::IsAudio(), KODI::MUSIC::IsCDDA(), KODI::NETWORK::IsInternetStream(), KODI::MUSIC::IsMusicDb(), CFileItem::IsNFO(), KODI::PLAYLIST::IsPlayList(), KODI::PLAYLIST::IsSmartPlayList(), MUSIC_INFO::CMusicInfoTag::Loaded(), CGUIListItem::m_bIsFolder, m_databaseHits, CFileItem::m_dateTime, m_musicDatabase, CBackgroundInfoLoader::m_pProgressCallback, m_songsMap, m_strPrevPath, m_tagReads, CGUIListItem::SetArt(), IProgressCallback::SetProgressAdvance(), MUSIC_INFO::CMusicInfoTag::SetSong(), CSettings::SETTING_MUSICFILES_USETAGS, and CSong::strThumb.
Referenced by LoadItem().
OnLoaderFinish()
void CMusicInfoLoader::OnLoaderFinish () override protected virtual
Reimplemented from CBackgroundInfoLoader.
References CFileItemList::Clear(), CDatabase::Close(), CBackgroundInfoLoader::m_bStop, m_databaseHits, m_mapFileItems, m_musicDatabase, CBackgroundInfoLoader::m_pVecItems, m_songsMap, m_strCacheFileName, m_tagReads, m_thumbLoader, CMusicThumbLoader::OnLoaderFinish(), CFileItemList::Save(), and SaveCache().
OnLoaderStart()
void CMusicInfoLoader::OnLoaderStart () override protected virtual
Reimplemented from CBackgroundInfoLoader.
References CFileItemList::GetFileCount(), CFileItem::GetPath(), CFileItemList::Load(), LoadCache(), m_databaseHits, m_mapFileItems, m_musicDatabase, CBackgroundInfoLoader::m_pProgressCallback, CBackgroundInfoLoader::m_pVecItems, m_strCacheFileName, m_strPrevPath, m_tagReads, m_thumbLoader, CMusicThumbLoader::OnLoaderStart(), CMusicDatabase::Open(), CFileItemList::SetFastLookup(), CFileItem::SetPath(), and IProgressCallback::SetProgressMax().
SaveCache()
void CMusicInfoLoader::SaveCache (const std::string & strFileName, CFileItemList & items) protected
References CArchive::Close(), CFileItemList::Size(), and CArchive::store.
Referenced by OnLoaderFinish().
UseCacheOnHD()
void CMusicInfoLoader::UseCacheOnHD (const std::string & strFileName)
References m_strCacheFileName.
Referenced by CGUIWindowMusicPlayList::OnMessage().
Member Data Documentation
m_databaseHits
unsigned int MUSIC_INFO::CMusicInfoLoader::m_databaseHits = 0 protected
Referenced by LoadItemLookup(), OnLoaderFinish(), and OnLoaderStart().
m_mapFileItems
CFileItemList* MUSIC_INFO::CMusicInfoLoader::m_mapFileItems protected
Referenced by CMusicInfoLoader(), OnLoaderFinish(), OnLoaderStart(), and ~CMusicInfoLoader().
m_musicDatabase
CMusicDatabase MUSIC_INFO::CMusicInfoLoader::m_musicDatabase protected
Referenced by LoadItemLookup(), OnLoaderFinish(), and OnLoaderStart().
m_songsMap
MAPSONGS MUSIC_INFO::CMusicInfoLoader::m_songsMap protected
Referenced by LoadItemLookup(), and OnLoaderFinish().
m_strCacheFileName
std::string MUSIC_INFO::CMusicInfoLoader::m_strCacheFileName protected
Referenced by OnLoaderFinish(), OnLoaderStart(), and UseCacheOnHD().
m_strPrevPath
std::string MUSIC_INFO::CMusicInfoLoader::m_strPrevPath protected
Referenced by LoadItemLookup(), and OnLoaderStart().
m_tagReads
unsigned int MUSIC_INFO::CMusicInfoLoader::m_tagReads = 0 protected
Referenced by LoadItemLookup(), OnLoaderFinish(), and OnLoaderStart().
m_thumbLoader
CMusicThumbLoader* MUSIC_INFO::CMusicInfoLoader::m_thumbLoader protected
Referenced by CMusicInfoLoader(), LoadItemCached(), OnLoaderFinish(), OnLoaderStart(), and ~CMusicInfoLoader().
The documentation for this class was generated from the following files:
MusicInfoLoader.h
MusicInfoLoader.cpp