Kodi Documentation: CDVDTeletextData Class Reference
CDVDTeletextData Class Reference
#include <VideoPlayerTeletext.h>
Public Member Functions
CDVDTeletextData (CProcessInfo &processInfo)
~CDVDTeletextData () override
bool CheckStream (CDVDStreamInfo &hints)
bool OpenStream (CDVDStreamInfo hints) override
void CloseStream (bool bWaitForBuffers) override
void Flush ()
void WaitForBuffers ()
bool AcceptsData () const override
void SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority=0) override
void FlushMessages () override
bool IsInited () const override
bool IsStalled () const override
std::shared_ptr< TextCacheStruct_t > GetTeletextCache ()
void LoadPage (int p, int sp, unsigned char *buffer)
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Public Member Functions inherited from IDVDStreamPlayer
IDVDStreamPlayer (CProcessInfo &processInfo)
virtual ~IDVDStreamPlayer ()=default
Protected Member Functions
void OnExit () override
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Member Functions
void ResetTeletextCache ()
void Decode_p2829 (unsigned char *vtxt_row, TextExtData_t **ptExtData)
void SavePage (int p, int sp, unsigned char *buffer)
void ErasePage (int magazine)
void AllocateCache (int magazine)
Private Attributes
int m_speed
std::shared_ptr< TextCacheStruct_t > m_TXTCache = std::make_shared<TextCacheStruct_t>()
CDVDMessageQueue m_messageQueue
Additional Inherited Members
Public Types inherited from IDVDStreamPlayer
enum ESyncState { SYNC_STARTING , SYNC_WAITSYNC , SYNC_INSYNC }
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Protected Attributes inherited from IDVDStreamPlayer
CProcessInfo & m_processInfo
Constructor & Destructor Documentation
CDVDTeletextData()
CDVDTeletextData::CDVDTeletextData (CProcessInfo & processInfo) explicit
References DVD_PLAYSPEED_NORMAL, m_messageQueue, m_speed, m_TXTCache, ResetTeletextCache(), and CDVDMessageQueue::SetMaxDataSize().
~CDVDTeletextData()
CDVDTeletextData::~CDVDTeletextData () override
References ResetTeletextCache(), and CThread::StopThread().
Member Function Documentation
AcceptsData()
bool CDVDTeletextData::AcceptsData () const inline override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::IsFull(), and m_messageQueue.
AllocateCache()
void CDVDTeletextData::AllocateCache (int magazine) private
References ErasePage(), and m_TXTCache.
Referenced by Process().
CheckStream()
bool CDVDTeletextData::CheckStream (CDVDStreamInfo & hints)
References CDVDStreamInfo::codec.
Referenced by CVideoPlayer::OpenTeletextStream().
CloseStream()
void CDVDTeletextData::CloseStream (bool bWaitForBuffers) override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::Abort(), CDVDMessageQueue::End(), CLog::Log(), LOGINFO, m_messageQueue, ResetTeletextCache(), and CThread::StopThread().
Referenced by OpenStream().
Decode_p2829()
void CDVDTeletextData::Decode_p2829 (unsigned char * vtxt_row, TextExtData_t ** ptExtData) private
References CDVDTeletextTools::deh24().
Referenced by Process().
ErasePage()
void CDVDTeletextData::ErasePage (int magazine) private
References TextCachedPage_t::data, m_TXTCache, TextCachedPage_t::p0, and TextCachedPage_t::pageinfo.
Referenced by AllocateCache().
Flush()
void CDVDTeletextData::Flush ()
References CDVDMessageQueue::Flush(), CDVDMsg::GENERAL_FLUSH, CDVDMessageQueue::IsInited(), m_messageQueue, and CDVDMessageQueue::Put().
Referenced by CVideoPlayer::FlushBuffers().
FlushMessages()
void CDVDTeletextData::FlushMessages () inline override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::Flush(), and m_messageQueue.
GetTeletextCache()
std::shared_ptr< TextCacheStruct_t > CDVDTeletextData::GetTeletextCache () inline
References m_TXTCache.
Referenced by CVideoPlayer::GetTeletextCache().
IsInited()
bool CDVDTeletextData::IsInited () const inline override virtual
Implements IDVDStreamPlayer.
IsStalled()
bool CDVDTeletextData::IsStalled () const inline override virtual
Implements IDVDStreamPlayer.
LoadPage()
void CDVDTeletextData::LoadPage (int p, int sp, unsigned char * buffer)
References TextCachedPage_t::data, CLog::Log(), LOGERROR, and m_TXTCache.
Referenced by CVideoPlayer::LoadPage(), and Process().
OnExit()
void CDVDTeletextData::OnExit () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
OpenStream()
bool CDVDTeletextData::OpenStream (CDVDStreamInfo hints) override virtual
Implements IDVDStreamPlayer.
References CloseStream(), CDVDStreamInfo::codec, CThread::Create(), CDVDMessageQueue::Init(), CLog::Log(), LOGINFO, and m_messageQueue.
Process()
void CDVDTeletextData::Process (void) override protected virtual
Todo:
implement
Reimplemented from CThread.
References AllocateCache(), TextPageinfo_t::boxed, CountryConversionTable, Decode_p2829(), CDVDTeletextTools::deh24(), dehamming, CDVDMsg::DEMUXER_PACKET, deparity, Textp27_t::drcs, DVD_PLAYSPEED_PAUSE, TextPageinfo_t::ext, FLOFSIZE, FUNC_DRCS, FUNC_GDRCS, FUNC_GPOP, FUNC_MOT, FUNC_POP, TextPageinfo_t::function, CDVDMsg::GENERAL_FLUSH, CDVDMsg::GENERAL_RESET, CDVDMessageQueue::Get(), IsDec(), DEMUX_PACKET::iSize, Textp27_t::l25, Textp27_t::l35, LoadPage(), Textp27_t::local, CLog::Log(), LOGERROR, LOGINFO, CThread::m_bStop, m_messageQueue, m_speed, m_TXTCache, MSGQ_IS_ERROR, MSGQ_TIMEOUT, NAT_DEFAULT, TextPageinfo_t::national, TextPageinfo_t::nationalvalid, TextPageinfo_t::p24, TextExtData_t::p26, TextExtData_t::p27, Textp27_t::page, DEMUX_PACKET::pData, CDVDMsg::PLAYER_SETSPEED, CDVDMessageQueue::ReceivedAbortRequest(), ResetTeletextCache(), rev_lut, SavePage(), and Textp27_t::subpage.
ResetTeletextCache()
void CDVDTeletextData::ResetTeletextCache () private
References TextPageinfo_t::ext, m_TXTCache, NAT_DEFAULT, TextPageinfo_t::p24, TextExtData_t::p26, and TextExtData_t::p27.
Referenced by CDVDTeletextData(), CloseStream(), Process(), and ~CDVDTeletextData().
SavePage()
void CDVDTeletextData::SavePage (int p, int sp, unsigned char * buffer) private
References TextCachedPage_t::data, CLog::Log(), LOGERROR, and m_TXTCache.
Referenced by Process().
SendMessage()
void CDVDTeletextData::SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority = 0) inline override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::IsInited(), m_messageQueue, and CDVDMessageQueue::Put().
Referenced by CVideoPlayer::ProcessTeletextData().
WaitForBuffers()
void CDVDTeletextData::WaitForBuffers () inline
References m_messageQueue, and CDVDMessageQueue::WaitUntilEmpty().
Member Data Documentation
m_messageQueue
CDVDMessageQueue CDVDTeletextData::m_messageQueue private
Referenced by AcceptsData(), CDVDTeletextData(), CloseStream(), Flush(), FlushMessages(), OpenStream(), Process(), SendMessage(), and WaitForBuffers().
m_speed
int CDVDTeletextData::m_speed private
Referenced by CDVDTeletextData(), and Process().
m_TXTCache
std::shared_ptr<TextCacheStruct_t> CDVDTeletextData::m_TXTCache = std::make_shared<TextCacheStruct_t>() private
Referenced by AllocateCache(), CDVDTeletextData(), ErasePage(), GetTeletextCache(), LoadPage(), Process(), ResetTeletextCache(), and SavePage().
The documentation for this class was generated from the following files:
VideoPlayerTeletext.h
VideoPlayerTeletext.cpp