Kodi Documentation: JSONRPC::CTCPServer::CWebSocketClient Class Reference
JSONRPC::CTCPServer::CWebSocketClient Class Reference
Public Member Functions
CWebSocketClient (CWebSocket *websocket)
CWebSocketClient (const CWebSocketClient &client)
CWebSocketClient (CWebSocket *websocket, const CTCPClient &client)
CWebSocketClient & operator= (const CWebSocketClient &client)
~CWebSocketClient () override
void Send (const char *data, unsigned int size) override
void PushBuffer (CTCPServer *host, const char *buffer, int length) override
void Disconnect () override
bool IsNew () const override
bool Closing () const override
Public Member Functions inherited from JSONRPC::CTCPServer::CTCPClient
CTCPClient ()
CTCPClient (const CTCPClient &client)
CTCPClient & operator= (const CTCPClient &client)
~CTCPClient () override=default
int GetPermissionFlags () override
int GetAnnouncementFlags () override
bool SetAnnouncementFlags (int flags) override
Public Member Functions inherited from JSONRPC::IClient
virtual ~IClient ()=default
Private Attributes
CWebSocket * m_websocket
std::string m_buffer
Additional Inherited Members
Public Attributes inherited from JSONRPC::CTCPServer::CTCPClient
SOCKET m_socket
sockaddr_storage m_cliaddr
socklen_t m_addrlen
CCriticalSection m_critSection
Protected Member Functions inherited from JSONRPC::CTCPServer::CTCPClient
void Copy (const CTCPClient &client)
Constructor & Destructor Documentation
CWebSocketClient() [1/3]
CTCPServer::CWebSocketClient::CWebSocketClient (CWebSocket * websocket) explicit
CWebSocketClient() [2/3]
CTCPServer::CWebSocketClient::CWebSocketClient (const CWebSocketClient & client)
References m_buffer.
CWebSocketClient() [3/3]
CTCPServer::CWebSocketClient::CWebSocketClient (CWebSocket * websocket, const CTCPClient & client)
~CWebSocketClient()
CTCPServer::CWebSocketClient::~CWebSocketClient () override
Member Function Documentation
Closing()
bool JSONRPC::CTCPServer::CWebSocketClient::Closing () const inline override virtual
Reimplemented from JSONRPC::CTCPServer::CTCPClient.
References CWebSocket::GetState(), m_websocket, and WebSocketStateClosed.
Disconnect()
void CTCPServer::CWebSocketClient::Disconnect () override virtual
Reimplemented from JSONRPC::CTCPServer::CTCPClient.
References JSONRPC::CTCPServer::CTCPClient::Disconnect(), CWebSocketFrame::GetFrameData(), CWebSocketFrame::GetFrameLength(), WebSocketStateClosed, and WebSocketStateNotConnected.
IsNew()
bool JSONRPC::CTCPServer::CWebSocketClient::IsNew () const inline override virtual
Reimplemented from JSONRPC::CTCPServer::CTCPClient.
References m_websocket.
operator=()
CTCPServer::CWebSocketClient & CTCPServer::CWebSocketClient::operator= (const CWebSocketClient & client)
References m_buffer, and m_websocket.
PushBuffer()
void CTCPServer::CWebSocketClient::PushBuffer (CTCPServer * host, const char * buffer, int length) override virtual
Reimplemented from JSONRPC::CTCPServer::CTCPClient.
References CWebSocketMessage::GetFrames(), index(), CWebSocketMessage::IsComplete(), CLog::Log(), LOGINFO, JSONRPC::CTCPServer::CTCPClient::PushBuffer(), JSONRPC::CTCPServer::CTCPClient::Send(), and WebSocketStateClosed.
Send()
void CTCPServer::CWebSocketClient::Send (const char * data, unsigned int size) override virtual
Reimplemented from JSONRPC::CTCPServer::CTCPClient.
References data(), CWebSocketMessage::GetFrames(), index(), CWebSocketMessage::IsComplete(), JSONRPC::CTCPServer::CTCPClient::Send(), and WebSocketTextFrame.
Member Data Documentation
m_buffer
std::string JSONRPC::CTCPServer::CWebSocketClient::m_buffer private
Referenced by CWebSocketClient(), and operator=().
m_websocket
CWebSocket* JSONRPC::CTCPServer::CWebSocketClient::m_websocket private
Referenced by Closing(), IsNew(), and operator=().
The documentation for this class was generated from the following files:
TCPServer.h
TCPServer.cpp