Kodi Documentation: CodecFactory Class Reference
CodecFactory Class Reference
#include <CodecFactory.h>
Public Member Functions
CodecFactory ()=default
virtual ~CodecFactory ()=default
Static Public Member Functions
static ICodec * CreateCodec (const CURL &urlFile)
static ICodec * CreateCodecDemux (const CFileItem &file, unsigned int filecache)
Constructor & Destructor Documentation
CodecFactory()
CodecFactory::CodecFactory () default
~CodecFactory()
virtual CodecFactory::~CodecFactory () virtual default
Member Function Documentation
CreateCodec()
ICodec * CodecFactory::CreateCodec (const CURL & urlFile) static
References ADDON::AUDIODECODER, KODI::ADDONS::CExtsMimeSupportList::GetExtensionSupportedAddonInfos(), CServiceBroker::GetExtsMimeSupportList(), and CURL::GetFileType().
Referenced by CreateCodecDemux().
CreateCodecDemux()
ICodec * CodecFactory::CreateCodecDemux (const CFileItem & file, unsigned int filecache) static
References ADDON::AUDIODECODER, CreateCodec(), CServiceBroker::GetExtsMimeSupportList(), KODI::ADDONS::CExtsMimeSupportList::GetMimetypeSupportedAddonInfos(), VideoPlayerCodec::Init(), CURL::IsFileType(), CURL::IsProtocol(), and VideoPlayerCodec::SetContentType().
Referenced by CAudioDecoder::Create().
The documentation for this class was generated from the following files:
CodecFactory.h
CodecFactory.cpp