Kodi Documentation: kodi::addon::PVRTypeIntValue Class Reference
kodi::addon::PVRTypeIntValue Class Reference
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General » class PVRTypeIntValue
#include <General.h>
Public Member Functions
PVRTypeIntValue ()=default
Default class constructor.
PVRTypeIntValue (int value, const std::string &description)
Class constructor with integrated value set.
void SetValue (int value)
To set with the identification value.
int GetValue () const
To get with the identification value.
void SetDescription (const std::string &description)
To set with the description text of the value.
std::string GetDescription () const
To get with the description text of the value.
Public Member Functions inherited from kodi::addon::DynamicCStructHdl< PVRTypeIntValue, PVR_ATTRIBUTE_INT_VALUE >
DynamicCStructHdl ()
DynamicCStructHdl (const DynamicCStructHdl &cppClass)
DynamicCStructHdl (const PVR_ATTRIBUTE_INT_VALUE *cStructure)
DynamicCStructHdl (PVR_ATTRIBUTE_INT_VALUE *cStructure)
const DynamicCStructHdl & operator= (const DynamicCStructHdl &right)
const DynamicCStructHdl & operator= (const PVR_ATTRIBUTE_INT_VALUE &right)
virtual ~DynamicCStructHdl ()
operator PVR_ATTRIBUTE_INT_VALUE * ()
operator const PVR_ATTRIBUTE_INT_VALUE * () const
const PVR_ATTRIBUTE_INT_VALUE * GetCStructure () const
PVR_ATTRIBUTE_INT_VALUE * release ()
Static Public Member Functions
static PVR_ATTRIBUTE_INT_VALUE * AllocAndCopyData (const std::vector< PVRTypeIntValue > &source)
static PVR_ATTRIBUTE_INT_VALUE * AllocAndCopyData (const PVR_ATTRIBUTE_INT_VALUE *source, unsigned int size)
static void AllocResources (const PVR_ATTRIBUTE_INT_VALUE *source, PVR_ATTRIBUTE_INT_VALUE *target)
static void FreeResources (PVR_ATTRIBUTE_INT_VALUE *target)
static void FreeResources (PVR_ATTRIBUTE_INT_VALUE *values, unsigned int size)
static void ReallocAndCopyData (PVR_ATTRIBUTE_INT_VALUE **source, unsigned int *size, const std::vector< PVRTypeIntValue > &values)
Private Member Functions
PVRTypeIntValue (const PVR_ATTRIBUTE_INT_VALUE *data)
PVRTypeIntValue (PVR_ATTRIBUTE_INT_VALUE *data)
Friends
class CInstancePVRClient
Additional Inherited Members
Protected Attributes inherited from kodi::addon::DynamicCStructHdl< PVRTypeIntValue, PVR_ATTRIBUTE_INT_VALUE >
PVR_ATTRIBUTE_INT_VALUE * m_cStructure
Constructor & Destructor Documentation
PVRTypeIntValue() [1/2]
kodi::addon::PVRTypeIntValue::PVRTypeIntValue (const PVR_ATTRIBUTE_INT_VALUE * data) inline private
PVRTypeIntValue() [2/2]
kodi::addon::PVRTypeIntValue::PVRTypeIntValue (PVR_ATTRIBUTE_INT_VALUE * data) inline private
Member Function Documentation
AllocAndCopyData() [1/2]
static PVR_ATTRIBUTE_INT_VALUE * kodi::addon::PVRTypeIntValue::AllocAndCopyData (const PVR_ATTRIBUTE_INT_VALUE * source, unsigned int size) inline static
References AllocResources(), PVR_ATTRIBUTE_INT_VALUE::iValue, and values.
AllocAndCopyData() [2/2]
static PVR_ATTRIBUTE_INT_VALUE * kodi::addon::PVRTypeIntValue::AllocAndCopyData (const std::vector< PVRTypeIntValue > & source) inline static
References AllocResources(), kodi::addon::DynamicCStructHdl< PVRTypeIntValue, PVR_ATTRIBUTE_INT_VALUE >::GetCStructure(), and values.
Referenced by kodi::addon::PVRCapabilities::AllocResources(), kodi::addon::PVRIntSettingDefinition::AllocResources(), kodi::addon::PVRTimerType::AllocResources(), and ReallocAndCopyData().
AllocResources()
static void kodi::addon::PVRTypeIntValue::AllocResources (const PVR_ATTRIBUTE_INT_VALUE * source, PVR_ATTRIBUTE_INT_VALUE * target) inline static
References kodi::addon::AllocAndCopyString(), and PVR_ATTRIBUTE_INT_VALUE::strDescription.
Referenced by AllocAndCopyData(), and AllocAndCopyData().
FreeResources() [1/2]
static void kodi::addon::PVRTypeIntValue::FreeResources (PVR_ATTRIBUTE_INT_VALUE * target) inline static
References kodi::addon::FreeString(), and PVR_ATTRIBUTE_INT_VALUE::strDescription.
Referenced by kodi::addon::PVRCapabilities::FreeResources(), FreeResources(), kodi::addon::PVRIntSettingDefinition::FreeResources(), kodi::addon::PVRTimerType::FreeResources(), and ReallocAndCopyData().
FreeResources() [2/2]
static void kodi::addon::PVRTypeIntValue::FreeResources (PVR_ATTRIBUTE_INT_VALUE * values, unsigned int size) inline static
References FreeResources(), and values.
ReallocAndCopyData()
static void kodi::addon::PVRTypeIntValue::ReallocAndCopyData (PVR_ATTRIBUTE_INT_VALUE ** source, unsigned int * size, const std::vector< PVRTypeIntValue > & values) inline static
References AllocAndCopyData(), FreeResources(), and values.
Referenced by kodi::addon::PVRTimerType::SetLifetimes(), kodi::addon::PVRTimerType::SetMaxRecordings(), kodi::addon::PVRTimerType::SetPreventDuplicateEpisodes(), kodi::addon::PVRTimerType::SetPriorities(), kodi::addon::PVRTimerType::SetRecordingGroups(), kodi::addon::PVRCapabilities::SetRecordingsLifetimeValues(), and kodi::addon::PVRIntSettingDefinition::SetValues().
Friends And Related Symbol Documentation
CInstancePVRClient
friend class CInstancePVRClient friend
The documentation for this class was generated from the following file:
kodi-dev-kit/include/kodi/addon-instance/pvr/General.h