Kodi Documentation: CD3DBuffer Class Reference
CD3DBuffer Class Reference
#include <D3DResource.h>
Public Member Functions
CD3DBuffer ()
virtual ~CD3DBuffer ()
bool Create (D3D11_BIND_FLAG type, UINT count, UINT stride, DXGI_FORMAT format, D3D11_USAGE usage, const void *initData=nullptr)
bool Map (void **resource)
bool Unmap ()
void Release ()
unsigned int GetStride ()
DXGI_FORMAT GetFormat ()
ID3D11Buffer * Get () const
void OnDestroyDevice (bool fatal) override
void OnCreateDevice () override
Public Member Functions inherited from ID3DResource
virtual ~ID3DResource ()
Private Member Functions
bool CreateBuffer (const void *pData)
Private Attributes
BYTE * m_data
UINT m_length
UINT m_stride
UINT m_cpuFlags
DXGI_FORMAT m_format
D3D11_USAGE m_usage
D3D11_BIND_FLAG m_type
Microsoft::WRL::ComPtr< ID3D11Buffer > m_buffer
Additional Inherited Members
Protected Member Functions inherited from ID3DResource
void Register ()
void Unregister ()
Protected Attributes inherited from ID3DResource
bool m_bRegistered = false
Constructor & Destructor Documentation
CD3DBuffer()
CD3DBuffer::CD3DBuffer ()
References m_buffer, m_data, m_format, m_length, m_stride, and m_usage.
~CD3DBuffer()
CD3DBuffer::~CD3DBuffer () virtual
References m_data, and Release().
Member Function Documentation
Create()
bool CD3DBuffer::Create (D3D11_BIND_FLAG type, UINT count, UINT stride, DXGI_FORMAT format, D3D11_USAGE usage, const void * initData = nullptr)
References CD3DHelper::BitsPerPixel(), CreateBuffer(), data(), m_cpuFlags, m_format, m_length, m_stride, m_type, m_usage, ID3DResource::Register(), Release(), and usage.
Referenced by OVERLAY::COverlayQuadsDX::COverlayQuadsDX(), CWinShader::CreateVertexBuffer(), and OVERLAY::COverlayImageDX::Load().
CreateBuffer()
bool CD3DBuffer::CreateBuffer (const void * pData) private
References CreateBuffer(), DX::DeviceResources::Get(), m_buffer, m_cpuFlags, m_length, m_type, and m_usage.
Referenced by Create(), CreateBuffer(), and OnCreateDevice().
Get()
ID3D11Buffer * CD3DBuffer::Get () const inline
References m_buffer.
Referenced by CWinShader::Execute(), CGUIFontTTFDX::LastEnd(), OVERLAY::COverlayQuadsDX::Render(), and OVERLAY::COverlayImageDX::Render().
GetFormat()
DXGI_FORMAT CD3DBuffer::GetFormat () inline
References m_format.
Referenced by CWinShader::Execute().
GetStride()
unsigned int CD3DBuffer::GetStride () inline
References m_stride.
Referenced by CWinShader::Execute(), and OVERLAY::COverlayImageDX::Render().
Map()
bool CD3DBuffer::Map (void ** resource)
References data(), DX::DeviceResources::Get(), m_buffer, and Map().
Referenced by CWinShader::LockVertexBuffer(), and Map().
OnCreateDevice()
void CD3DBuffer::OnCreateDevice (void) override virtual
Implements ID3DResource.
References CreateBuffer(), m_buffer, and m_data.
OnDestroyDevice()
void CD3DBuffer::OnDestroyDevice (bool fatal) override virtual
Implements ID3DResource.
References DX::DeviceResources::Get(), m_buffer, and m_data.
Release()
void CD3DBuffer::Release ()
References m_buffer, and ID3DResource::Unregister().
Referenced by Create(), and ~CD3DBuffer().
Unmap()
bool CD3DBuffer::Unmap ()
References DX::DeviceResources::Get(), and m_buffer.
Referenced by CWinShader::UnlockVertexBuffer().
Member Data Documentation
m_buffer
Microsoft::WRL::ComPtr<ID3D11Buffer> CD3DBuffer::m_buffer private
Referenced by CD3DBuffer(), CreateBuffer(), Get(), Map(), OnCreateDevice(), OnDestroyDevice(), Release(), and Unmap().
m_cpuFlags
UINT CD3DBuffer::m_cpuFlags private
Referenced by Create(), and CreateBuffer().
m_data
BYTE* CD3DBuffer::m_data private
Referenced by CD3DBuffer(), OnCreateDevice(), OnDestroyDevice(), and ~CD3DBuffer().
m_format
DXGI_FORMAT CD3DBuffer::m_format private
Referenced by CD3DBuffer(), Create(), and GetFormat().
m_length
UINT CD3DBuffer::m_length private
Referenced by CD3DBuffer(), Create(), and CreateBuffer().
m_stride
UINT CD3DBuffer::m_stride private
Referenced by CD3DBuffer(), Create(), and GetStride().
m_type
D3D11_BIND_FLAG CD3DBuffer::m_type private
Referenced by Create(), and CreateBuffer().
m_usage
D3D11_USAGE CD3DBuffer::m_usage private
Referenced by CD3DBuffer(), Create(), and CreateBuffer().
The documentation for this class was generated from the following files:
D3DResource.h
D3DResource.cpp