Kodi Documentation: CDatabaseQueryRule Class Reference
CDatabaseQueryRule Class Reference abstract
#include <DatabaseQuery.h>
Public Types
enum SEARCH_OPERATOR {
OPERATOR_START = 0 , OPERATOR_CONTAINS , OPERATOR_DOES_NOT_CONTAIN , OPERATOR_EQUALS ,
OPERATOR_DOES_NOT_EQUAL , OPERATOR_STARTS_WITH , OPERATOR_ENDS_WITH , OPERATOR_GREATER_THAN ,
OPERATOR_LESS_THAN , OPERATOR_AFTER , OPERATOR_BEFORE , OPERATOR_IN_THE_LAST ,
OPERATOR_NOT_IN_THE_LAST , OPERATOR_TRUE , OPERATOR_FALSE , OPERATOR_BETWEEN ,
OPERATOR_END
}
enum FIELD_TYPE {
TEXT_FIELD = 0 , REAL_FIELD , NUMERIC_FIELD , DATE_FIELD ,
PLAYLIST_FIELD , SECONDS_FIELD , BOOLEAN_FIELD , TEXTIN_FIELD
}
Public Member Functions
CDatabaseQueryRule ()
virtual ~CDatabaseQueryRule ()=default
virtual bool Load (const TiXmlNode *node, const std::string &encoding="UTF-8")
virtual bool Load (const CVariant &obj)
virtual bool Save (TiXmlNode *parent) const
virtual bool Save (CVariant &obj) const
std::string GetParameter () const
void SetParameter (const std::string &value)
void SetParameter (const std::vector< std::string > &values)
virtual std::string GetWhereClause (const CDatabase &db, const std::string &strType) const
Static Public Member Functions
static std::string GetLocalizedOperator (SEARCH_OPERATOR oper)
static void GetAvailableOperators (std::vector< std::string > &operatorList)
Public Attributes
int m_field
SEARCH_OPERATOR m_operator
std::vector< std::string > m_parameter
Protected Member Functions
virtual std::string GetField (int field, const std::string &type) const =0
virtual FIELD_TYPE GetFieldType (int field) const =0
virtual int TranslateField (const char *field) const =0
virtual std::string TranslateField (int field) const =0
std::string ValidateParameter (const std::string &parameter) const
virtual std::string FormatParameter (const std::string &negate, const std::string &oper, const CDatabase &db, const std::string &type) const
virtual std::string FormatWhereClause (const std::string &negate, const std::string &oper, const std::string &param, const CDatabase &db, const std::string &type) const
virtual SEARCH_OPERATOR GetOperator (const std::string &type) const
virtual std::string GetOperatorString (SEARCH_OPERATOR op) const
virtual std::string GetBooleanQuery (const std::string &negate, const std::string &strType) const
Static Protected Member Functions
static SEARCH_OPERATOR TranslateOperator (const char *oper)
static std::string TranslateOperator (SEARCH_OPERATOR oper)
Member Enumeration Documentation
FIELD_TYPE
enum CDatabaseQueryRule::FIELD_TYPE
Enumerator
TEXT_FIELD
REAL_FIELD
NUMERIC_FIELD
DATE_FIELD
PLAYLIST_FIELD
SECONDS_FIELD
BOOLEAN_FIELD
TEXTIN_FIELD
SEARCH_OPERATOR
enum CDatabaseQueryRule::SEARCH_OPERATOR
Enumerator
OPERATOR_START
OPERATOR_CONTAINS
OPERATOR_DOES_NOT_CONTAIN
OPERATOR_EQUALS
OPERATOR_DOES_NOT_EQUAL
OPERATOR_STARTS_WITH
OPERATOR_ENDS_WITH
OPERATOR_GREATER_THAN
OPERATOR_LESS_THAN
OPERATOR_AFTER
OPERATOR_BEFORE
OPERATOR_IN_THE_LAST
OPERATOR_NOT_IN_THE_LAST
OPERATOR_TRUE
OPERATOR_FALSE
OPERATOR_BETWEEN
OPERATOR_END
Constructor & Destructor Documentation
CDatabaseQueryRule()
CDatabaseQueryRule::CDatabaseQueryRule ()
References m_field, m_operator, and OPERATOR_CONTAINS.
~CDatabaseQueryRule()
virtual CDatabaseQueryRule::~CDatabaseQueryRule () virtual default
Member Function Documentation
FormatParameter()
std::string CDatabaseQueryRule::FormatParameter (const std::string & negate, const std::string & oper, const CDatabase & db, const std::string & type) const protected virtual
Reimplemented in KODI::PLAYLIST::CSmartPlaylistRule, and CTextureRule.
References DATE_FIELD, CDateTime::GetAsDBDate(), CDateTime::GetCurrentDateTime(), GetFieldType(), m_field, m_operator, OPERATOR_IN_THE_LAST, OPERATOR_NOT_IN_THE_LAST, CDatabase::PrepareSQL(), CDateTimeSpan::SetFromPeriod(), TEXTIN_FIELD, and ValidateParameter().
Referenced by KODI::PLAYLIST::CSmartPlaylistRule::FormatParameter(), CTextureRule::FormatParameter(), and FormatWhereClause().
FormatWhereClause()
std::string CDatabaseQueryRule::FormatWhereClause (const std::string & negate, const std::string & oper, const std::string & param, const CDatabase & db, const std::string & type) const protected virtual
Reimplemented in KODI::PLAYLIST::CSmartPlaylistRule.
References FormatParameter(), GetField(), GetFieldType(), m_field, NUMERIC_FIELD, and SECONDS_FIELD.
Referenced by KODI::PLAYLIST::CSmartPlaylistRule::FormatWhereClause(), and GetWhereClause().
GetAvailableOperators()
void CDatabaseQueryRule::GetAvailableOperators (std::vector< std::string > & operatorList) static
References operators.
Referenced by JSONRPC::CJSONRPC::Initialize().
GetBooleanQuery()
virtual std::string CDatabaseQueryRule::GetBooleanQuery (const std::string & negate, const std::string & strType) const inline protected virtual
Reimplemented in KODI::PLAYLIST::CSmartPlaylistRule.
Referenced by GetWhereClause().
GetField()
virtual std::string CDatabaseQueryRule::GetField (int field, const std::string & type) const protected pure virtual
Implemented in KODI::PLAYLIST::CSmartPlaylistRule, and CTextureRule.
Referenced by FormatWhereClause(), and GetWhereClause().
GetFieldType()
virtual FIELD_TYPE CDatabaseQueryRule::GetFieldType (int field) const protected pure virtual
Implemented in KODI::PLAYLIST::CSmartPlaylistRule, and CTextureRule.
Referenced by FormatParameter(), FormatWhereClause(), GetOperatorString(), GetWhereClause(), and ValidateParameter().
GetLocalizedOperator()
std::string CDatabaseQueryRule::GetLocalizedOperator (SEARCH_OPERATOR oper) static
References g_localizeStrings, CLocalizeStrings::Get(), and operators.
Referenced by KODI::PLAYLIST::CSmartPlaylistRule::GetLocalizedRule().
GetOperator()
virtual SEARCH_OPERATOR CDatabaseQueryRule::GetOperator (const std::string & type) const inline protected virtual
Reimplemented in KODI::PLAYLIST::CSmartPlaylistRule.
References m_operator.
Referenced by KODI::PLAYLIST::CSmartPlaylistRule::GetOperator(), and GetWhereClause().
GetOperatorString()
std::string CDatabaseQueryRule::GetOperatorString (SEARCH_OPERATOR op) const protected virtual
References GetFieldType(), m_field, NUMERIC_FIELD, OPERATOR_AFTER, OPERATOR_BEFORE, OPERATOR_CONTAINS, OPERATOR_DOES_NOT_CONTAIN, OPERATOR_DOES_NOT_EQUAL, OPERATOR_ENDS_WITH, OPERATOR_EQUALS, OPERATOR_FALSE, OPERATOR_GREATER_THAN, OPERATOR_IN_THE_LAST, OPERATOR_LESS_THAN, OPERATOR_NOT_IN_THE_LAST, OPERATOR_STARTS_WITH, OPERATOR_TRUE, REAL_FIELD, SECONDS_FIELD, and TEXTIN_FIELD.
Referenced by GetWhereClause().
GetParameter()
std::string CDatabaseQueryRule::GetParameter () const
References DATABASEQUERY_RULE_VALUE_SEPARATOR, and m_parameter.
Referenced by KODI::PLAYLIST::CSmartPlaylistRule::GetLocalizedRule(), CGUIDialogMediaFilter::InitializeSettings(), CGUIDialogSmartPlaylistRule::OnBrowse(), and CGUIDialogSmartPlaylistRule::UpdateButtons().
GetWhereClause()
std::string CDatabaseQueryRule::GetWhereClause (const CDatabase & db, const std::string & strType) const virtual
References BOOLEAN_FIELD, FormatWhereClause(), GetBooleanQuery(), GetField(), GetFieldType(), GetOperator(), GetOperatorString(), m_field, m_operator, m_parameter, NUMERIC_FIELD, OPERATOR_BETWEEN, OPERATOR_CONTAINS, OPERATOR_DOES_NOT_CONTAIN, OPERATOR_DOES_NOT_EQUAL, OPERATOR_EQUALS, OPERATOR_FALSE, OPERATOR_TRUE, CDatabase::PrepareSQL(), REAL_FIELD, and SECONDS_FIELD.
Load() [1/2]
bool CDatabaseQueryRule::Load (const CVariant & obj) virtual
References CVariant::isArray(), CVariant::isMember(), CVariant::isString(), m_field, m_operator, m_parameter, OPERATOR_FALSE, OPERATOR_TRUE, CVariant::push_back(), TranslateField(), TranslateOperator(), and value.
Load() [2/2]
bool CDatabaseQueryRule::Load (const TiXmlNode * node, const std::string & encoding = "UTF-8") virtual
References g_charsetConverter, m_field, m_operator, m_parameter, node, OPERATOR_FALSE, OPERATOR_TRUE, TranslateField(), TranslateOperator(), and value.
Referenced by KODI::PLAYLIST::CSmartPlaylist::LoadFromXML().
Save() [1/2]
bool CDatabaseQueryRule::Save (CVariant & obj) const virtual
References CVariant::isNull(), m_field, m_operator, m_parameter, OPERATOR_FALSE, OPERATOR_TRUE, TranslateField(), and TranslateOperator().
Save() [2/2]
bool CDatabaseQueryRule::Save (TiXmlNode * parent) const virtual
References m_field, m_operator, m_parameter, OPERATOR_FALSE, OPERATOR_TRUE, text, TranslateField(), TranslateOperator(), and value.
SetParameter() [1/2]
void CDatabaseQueryRule::SetParameter (const std::string & value)
References DATABASEQUERY_RULE_VALUE_SEPARATOR, m_parameter, and value.
Referenced by CGUIDialogSmartPlaylistRule::OnField(), and CGUIDialogSmartPlaylistRule::OnMessage().
SetParameter() [2/2]
void CDatabaseQueryRule::SetParameter (const std::vector< std::string > & values)
References m_parameter, and values.
TranslateField() [1/2]
virtual int CDatabaseQueryRule::TranslateField (const char * field) const protected pure virtual
Implemented in KODI::PLAYLIST::CSmartPlaylistRule, and CTextureRule.
Referenced by Load(), Load(), Save(), and Save().
TranslateField() [2/2]
virtual std::string CDatabaseQueryRule::TranslateField (int field) const protected pure virtual
Implemented in KODI::PLAYLIST::CSmartPlaylistRule, and CTextureRule.
TranslateOperator() [1/2]
CDatabaseQueryRule::SEARCH_OPERATOR CDatabaseQueryRule::TranslateOperator (const char * oper) static protected
References OPERATOR_CONTAINS, and operators.
Referenced by Load(), Load(), Save(), and Save().
TranslateOperator() [2/2]
std::string CDatabaseQueryRule::TranslateOperator (SEARCH_OPERATOR oper) static protected
References operators.
ValidateParameter()
std::string CDatabaseQueryRule::ValidateParameter (const std::string & parameter) const protected
References GetFieldType(), m_field, NUMERIC_FIELD, REAL_FIELD, and SECONDS_FIELD.
Referenced by FormatParameter().
Member Data Documentation
m_field
int CDatabaseQueryRule::m_field
Referenced by CGUIDialogMediaFilter::AddRule(), CDatabaseQueryRule(), FormatParameter(), KODI::PLAYLIST::CSmartPlaylistRule::FormatParameter(), CTextureRule::FormatParameter(), FormatWhereClause(), KODI::PLAYLIST::CSmartPlaylistRule::FormatWhereClause(), KODI::PLAYLIST::CSmartPlaylistRule::GetBooleanQuery(), KODI::PLAYLIST::CSmartPlaylistRule::GetLocalizedRule(), KODI::PLAYLIST::CSmartPlaylistRule::GetOperator(), GetOperatorString(), CGUIDialogSmartPlaylistRule::GetValidOperators(), GetWhereClause(), Load(), Load(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIDialogSmartPlaylistRule::OnField(), Save(), Save(), CGUIDialogSmartPlaylistRule::UpdateButtons(), KODI::PLAYLIST::CSmartPlaylistRule::Validate(), and ValidateParameter().
m_operator
SEARCH_OPERATOR CDatabaseQueryRule::m_operator
Referenced by CGUIDialogMediaFilter::AddRule(), CDatabaseQueryRule(), FormatParameter(), KODI::PLAYLIST::CSmartPlaylistRule::FormatWhereClause(), KODI::PLAYLIST::CSmartPlaylistRule::FormatYearQuery(), KODI::PLAYLIST::CSmartPlaylistRule::GetLocalizedRule(), GetOperator(), KODI::PLAYLIST::CSmartPlaylistRule::GetVideoResolutionQuery(), GetWhereClause(), CGUIDialogMediaFilter::InitializeSettings(), Load(), Load(), CGUIDialogSmartPlaylistRule::OnField(), CGUIDialogSmartPlaylistRule::OnOperator(), CGUIDialogMediaFilter::OnSettingChanged(), Save(), Save(), and CGUIDialogSmartPlaylistRule::UpdateButtons().
m_parameter
std::vector<std::string> CDatabaseQueryRule::m_parameter
Referenced by GetParameter(), GetWhereClause(), CGUIDialogMediaFilter::InitializeSettings(), Load(), Load(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIDialogMediaFilter::OnSettingChanged(), Save(), Save(), SetParameter(), and SetParameter().
The documentation for this class was generated from the following files:
DatabaseQuery.h
DatabaseQuery.cpp