Kodi Documentation: KODI::KEYMAP::CButtonStat Class Reference
KODI::KEYMAP::CButtonStat Class Reference
#include <ButtonStat.h>
Public Member Functions
CButtonStat ()
~CButtonStat ()=default
CKey TranslateKey (const CKey &key) const
Constructor & Destructor Documentation
CButtonStat()
CButtonStat::CButtonStat () default
~CButtonStat()
KODI::KEYMAP::CButtonStat::~CButtonStat () default
Member Function Documentation
TranslateKey()
CKey CButtonStat::TranslateKey (const CKey & key) const
References CKey::GetButtonCode(), CKey::GetHeld(), KODI::KEYBOARD::KEY_HOLD_TRESHOLD, and CKey::MODIFIER_LONG.
Referenced by CInputManager::OnEvent().
The documentation for this class was generated from the following files:
ButtonStat.h
ButtonStat.cpp