Kodi Documentation: KODI::PIPEWIRE::CPipewireNode Class Reference
KODI::PIPEWIRE::CPipewireNode Class Reference
#include <PipewireNode.h>
Classes
struct PipewireNodeInfoDeleter
Public Member Functions
CPipewireNode (CPipewireRegistry &registry, uint32_t id, const char *type)
CPipewireNode ()=delete
~CPipewireNode () override
void EnumerateFormats ()
pw_node_info * GetInfo ()
std::set< spa_audio_format > & GetFormats ()
std::set< spa_audio_channel > & GetChannels ()
std::set< uint32_t > & GetRates ()
std::set< spa_audio_iec958_codec > & GetIEC958Codecs ()
Public Member Functions inherited from KODI::PIPEWIRE::CPipewireProxy
CPipewireProxy ()=delete
virtual ~CPipewireProxy ()
CPipewireRegistry & GetRegistry () const
Private Member Functions
void Parse (uint32_t type, void *body, uint32_t size)
Static Private Member Functions
static void Info (void *userdata, const struct pw_node_info *info)
static void Param (void *userdata, int seq, uint32_t id, uint32_t index, uint32_t next, const struct spa_pod *param)
static pw_node_events CreateNodeEvents ()
Private Attributes
const pw_node_events m_nodeEvents
spa_hook m_objectListener
std::unique_ptr< pw_node_info, PipewireNodeInfoDeleter > m_info
std::set< spa_audio_format > m_formats
std::set< spa_audio_channel > m_channels
std::set< uint32_t > m_rates
std::set< spa_audio_iec958_codec > m_iec958Codecs
Additional Inherited Members
Protected Member Functions inherited from KODI::PIPEWIRE::CPipewireProxy
CPipewireProxy (CPipewireRegistry &registry, uint32_t id, const char *type, uint32_t version)
Protected Attributes inherited from KODI::PIPEWIRE::CPipewireProxy
std::unique_ptr< pw_proxy, PipewireProxyDeleter > m_proxy
Constructor & Destructor Documentation
CPipewireNode() [1/2]
CPipewireNode::CPipewireNode (CPipewireRegistry & registry, uint32_t id, const char * type) explicit
References m_nodeEvents, m_objectListener, and KODI::PIPEWIRE::CPipewireProxy::m_proxy.
CPipewireNode() [2/2]
KODI::PIPEWIRE::CPipewireNode::CPipewireNode () delete
~CPipewireNode()
CPipewireNode::~CPipewireNode () override
References m_objectListener.
Member Function Documentation
CreateNodeEvents()
pw_node_events CPipewireNode::CreateNodeEvents () static private
References Info(), and Param().
EnumerateFormats()
void CPipewireNode::EnumerateFormats ()
References m_info, and KODI::PIPEWIRE::CPipewireProxy::m_proxy.
GetChannels()
std::set< spa_audio_channel > & KODI::PIPEWIRE::CPipewireNode::GetChannels () inline
References m_channels.
GetFormats()
std::set< spa_audio_format > & KODI::PIPEWIRE::CPipewireNode::GetFormats () inline
References m_formats.
GetIEC958Codecs()
std::set< spa_audio_iec958_codec > & KODI::PIPEWIRE::CPipewireNode::GetIEC958Codecs () inline
References m_iec958Codecs.
GetInfo()
pw_node_info * KODI::PIPEWIRE::CPipewireNode::GetInfo () inline
References m_info.
GetRates()
std::set< uint32_t > & KODI::PIPEWIRE::CPipewireNode::GetRates () inline
References m_rates.
Info()
void CPipewireNode::Info (void * userdata, const struct pw_node_info * info) static private
References CLog::Log(), LOGDEBUG, m_info, and node.
Referenced by CreateNodeEvents().
Param()
void CPipewireNode::Param (void * userdata, int seq, uint32_t id, uint32_t index, uint32_t next, const struct spa_pod * param) static private
References KODI::PIPEWIRE::CPipewireCore::GetContext(), KODI::PIPEWIRE::CPipewireRegistry::GetCore(), KODI::PIPEWIRE::CPipewireProxy::GetRegistry(), KODI::PIPEWIRE::CPipewireContext::GetThreadLoop(), node, and KODI::PIPEWIRE::CPipewireThreadLoop::Signal().
Referenced by CreateNodeEvents().
Parse()
void CPipewireNode::Parse (uint32_t type, void * body, uint32_t size) private
References m_channels, m_formats, m_iec958Codecs, and m_rates.
Member Data Documentation
m_channels
std::set<spa_audio_channel> KODI::PIPEWIRE::CPipewireNode::m_channels private
Referenced by GetChannels(), and Parse().
m_formats
std::set<spa_audio_format> KODI::PIPEWIRE::CPipewireNode::m_formats private
Referenced by GetFormats(), and Parse().
m_iec958Codecs
std::set<spa_audio_iec958_codec> KODI::PIPEWIRE::CPipewireNode::m_iec958Codecs private
Referenced by GetIEC958Codecs(), and Parse().
m_info
std::unique_ptr<pw_node_info, PipewireNodeInfoDeleter> KODI::PIPEWIRE::CPipewireNode::m_info private
Referenced by EnumerateFormats(), GetInfo(), and Info().
m_nodeEvents
const pw_node_events KODI::PIPEWIRE::CPipewireNode::m_nodeEvents private
Referenced by CPipewireNode().
m_objectListener
spa_hook KODI::PIPEWIRE::CPipewireNode::m_objectListener private
Referenced by CPipewireNode(), and ~CPipewireNode().
m_rates
std::set<uint32_t> KODI::PIPEWIRE::CPipewireNode::m_rates private
Referenced by GetRates(), and Parse().
The documentation for this class was generated from the following files:
PipewireNode.h
PipewireNode.cpp