Kodi Documentation: class PVRSettingDefinition
class PVRSettingDefinition
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General
PVR add-on setting definition
Representation of a setting definition.
Classes
class kodi::addon::PVRSettingDefinition
Functions
kodi::addon::PVRSettingDefinition::PVRSettingDefinition (unsigned int settingDefId, const std::string &settingDefName, uint64_t readonlyConditions, const PVRIntSettingDefinition &settingDef)
Class constructor with integrated values.
kodi::addon::PVRSettingDefinition::PVRSettingDefinition (unsigned int settingDefId, const std::string &settingDefName, uint64_t readonlyConditions, const PVRStringSettingDefinition &settingDef)
Class constructor with integrated values.
kodi::addon::PVRSettingDefinition::PVRSettingDefinition (unsigned int settingDefId, const std::string &settingDefName, PVR_SETTING_TYPE eType, uint64_t readonlyConditions, const PVRIntSettingDefinition &intSettingDef, const PVRStringSettingDefinition &stringSettingDef)
Class constructor with integrated values.
void kodi::addon::PVRSettingDefinition::SetId (unsigned int defId)
required
This setting definition's identifier.
unsigned int kodi::addon::PVRSettingDefinition::GetId () const
To get with SetId changed values.
void kodi::addon::PVRSettingDefinition::SetName (const std::string &name)
required
A short localized string with the name of the setting.
std::string kodi::addon::PVRSettingDefinition::GetName () const
To get with SetName changed values.
void kodi::addon::PVRSettingDefinition::SetType (PVR_SETTING_TYPE eType)
required
This setting definition's identifier.
PVR_SETTING_TYPE kodi::addon::PVRSettingDefinition::GetType () const
To get with SetType changed values.
void kodi::addon::PVRSettingDefinition::SetReadonlyConditions (uint64_t conditions)
optional
The read-only conditions value for this setting. PVR_SETTING_READONLY_CONDITION_* enum values
uint64_t kodi::addon::PVRSettingDefinition::GetReadonlyConditions () const
To get with SetReadonlyConditions changed values.
void kodi::addon::PVRSettingDefinition::SetIntDefinition (const PVRIntSettingDefinition &def)
optional
PVRIntSettingDefinition kodi::addon::PVRSettingDefinition::GetIntDefinition () const
To get with SetIntDefinition changed values.
void kodi::addon::PVRSettingDefinition::SetStringDefinition (const PVRStringSettingDefinition &def)
optional
PVRStringSettingDefinition kodi::addon::PVRSettingDefinition::GetStringDefinition () const
To get with SetStringDefinition changed values.
Detailed Description
PVR add-on setting definition
Representation of a setting definition.
Function Documentation
GetId()
unsigned int kodi::addon::PVRSettingDefinition::GetId () const inline
To get with SetId changed values.
References PVR_SETTING_DEFINITION::iId, and kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure.
GetIntDefinition()
PVRIntSettingDefinition kodi::addon::PVRSettingDefinition::GetIntDefinition () const inline
To get with SetIntDefinition changed values.
References PVR_INT_SETTING_DEFINITION::iDefaultValue, PVR_INT_SETTING_DEFINITION::iMaxValue, PVR_INT_SETTING_DEFINITION::iMinValue, PVR_SETTING_DEFINITION::intSettingDefinition, PVR_INT_SETTING_DEFINITION::iStep, PVR_ATTRIBUTE_INT_VALUE::iValue, PVR_INT_SETTING_DEFINITION::iValuesSize, kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure, kodi::addon::PVRIntSettingDefinition::SetDefaultValue(), kodi::addon::PVRIntSettingDefinition::SetMaxValue(), kodi::addon::PVRIntSettingDefinition::SetMinValue(), kodi::addon::PVRIntSettingDefinition::SetStep(), kodi::addon::PVRIntSettingDefinition::SetValues(), PVR_ATTRIBUTE_INT_VALUE::strDescription, and PVR_INT_SETTING_DEFINITION::values.
GetName()
std::string kodi::addon::PVRSettingDefinition::GetName () const inline
To get with SetName changed values.
References kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure, and PVR_SETTING_DEFINITION::strName.
GetReadonlyConditions()
uint64_t kodi::addon::PVRSettingDefinition::GetReadonlyConditions () const inline
To get with SetReadonlyConditions changed values.
References PVR_SETTING_DEFINITION::iReadonlyConditions, and kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure.
GetStringDefinition()
PVRStringSettingDefinition kodi::addon::PVRSettingDefinition::GetStringDefinition () const inline
To get with SetStringDefinition changed values.
References PVR_STRING_SETTING_DEFINITION::iValuesSize, kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure, kodi::addon::PVRStringSettingDefinition::SetDefaultValue(), kodi::addon::PVRStringSettingDefinition::SetValues(), PVR_STRING_SETTING_DEFINITION::strDefaultValue, PVR_ATTRIBUTE_STRING_VALUE::strDescription, PVR_SETTING_DEFINITION::stringSettingDefinition, PVR_ATTRIBUTE_STRING_VALUE::strValue, and PVR_STRING_SETTING_DEFINITION::values.
GetType()
PVR_SETTING_TYPE kodi::addon::PVRSettingDefinition::GetType () const inline
To get with SetType changed values.
References PVR_SETTING_DEFINITION::eType, and kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure.
PVRSettingDefinition() [1/3]
kodi::addon::PVRSettingDefinition::PVRSettingDefinition (unsigned int settingDefId, const std::string & settingDefName, PVR_SETTING_TYPE eType, uint64_t readonlyConditions, const PVRIntSettingDefinition & intSettingDef, const PVRStringSettingDefinition & stringSettingDef) inline
Class constructor with integrated values.
Parameters
[in] settingDefId Setting definition identification value
[in] settingDefName Setting definition name
[in] eType Setting type
[in] readonlyConditions readonly conditions value
[in] intSettingDef int setting definition
[in] stringSettingDef string setting definition
References kodi::addon::PVRSettingDefinition::SetId(), kodi::addon::PVRSettingDefinition::SetIntDefinition(), kodi::addon::PVRSettingDefinition::SetName(), kodi::addon::PVRSettingDefinition::SetReadonlyConditions(), kodi::addon::PVRSettingDefinition::SetStringDefinition(), and kodi::addon::PVRSettingDefinition::SetType().
PVRSettingDefinition() [2/3]
kodi::addon::PVRSettingDefinition::PVRSettingDefinition (unsigned int settingDefId, const std::string & settingDefName, uint64_t readonlyConditions, const PVRIntSettingDefinition & settingDef) inline
Class constructor with integrated values.
Parameters
[in] settingDefId Setting definition identification value
[in] settingDefName Setting definition name
[in] readonlyConditions readonly conditions value
[in] settingDef int setting definition
References kodi::addon::PVRSettingDefinition::SetId(), kodi::addon::PVRSettingDefinition::SetIntDefinition(), kodi::addon::PVRSettingDefinition::SetName(), kodi::addon::PVRSettingDefinition::SetReadonlyConditions(), and kodi::addon::PVRSettingDefinition::SetType().
PVRSettingDefinition() [3/3]
kodi::addon::PVRSettingDefinition::PVRSettingDefinition (unsigned int settingDefId, const std::string & settingDefName, uint64_t readonlyConditions, const PVRStringSettingDefinition & settingDef) inline
Class constructor with integrated values.
Parameters
[in] settingDefId Setting definition identification value
[in] settingDefName Setting definition name
[in] readonlyConditions readonly conditions value
[in] settingDef string setting definition
References kodi::addon::PVRSettingDefinition::SetId(), kodi::addon::PVRSettingDefinition::SetName(), kodi::addon::PVRSettingDefinition::SetReadonlyConditions(), kodi::addon::PVRSettingDefinition::SetStringDefinition(), and kodi::addon::PVRSettingDefinition::SetType().
SetId()
void kodi::addon::PVRSettingDefinition::SetId (unsigned int defId) inline
required
This setting definition's identifier.
References PVR_SETTING_DEFINITION::iId, and kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure.
Referenced by kodi::addon::PVRSettingDefinition::PVRSettingDefinition(), kodi::addon::PVRSettingDefinition::PVRSettingDefinition(), and kodi::addon::PVRSettingDefinition::PVRSettingDefinition().
SetIntDefinition()
void kodi::addon::PVRSettingDefinition::SetIntDefinition (const PVRIntSettingDefinition & def) inline
optional
Parameters
[in] def integer setting definition
References PVR_SETTING_DEFINITION::intSettingDefinition, kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure, and kodi::addon::PVRIntSettingDefinition::ReallocAndCopyData().
Referenced by kodi::addon::PVRSettingDefinition::PVRSettingDefinition(), and kodi::addon::PVRSettingDefinition::PVRSettingDefinition().
SetName()
void kodi::addon::PVRSettingDefinition::SetName (const std::string & name) inline
required
A short localized string with the name of the setting.
References kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure, name, kodi::addon::ReallocAndCopyString(), and PVR_SETTING_DEFINITION::strName.
Referenced by kodi::addon::PVRSettingDefinition::PVRSettingDefinition(), kodi::addon::PVRSettingDefinition::PVRSettingDefinition(), and kodi::addon::PVRSettingDefinition::PVRSettingDefinition().
SetReadonlyConditions()
void kodi::addon::PVRSettingDefinition::SetReadonlyConditions (uint64_t conditions) inline
optional
The read-only conditions value for this setting. PVR_SETTING_READONLY_CONDITION_* enum values
References PVR_SETTING_DEFINITION::iReadonlyConditions, and kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure.
Referenced by kodi::addon::PVRSettingDefinition::PVRSettingDefinition(), kodi::addon::PVRSettingDefinition::PVRSettingDefinition(), and kodi::addon::PVRSettingDefinition::PVRSettingDefinition().
SetStringDefinition()
void kodi::addon::PVRSettingDefinition::SetStringDefinition (const PVRStringSettingDefinition & def) inline
optional
Parameters
[in] def string setting definition
References kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure, kodi::addon::PVRStringSettingDefinition::ReallocAndCopyData(), and PVR_SETTING_DEFINITION::stringSettingDefinition.
Referenced by kodi::addon::PVRSettingDefinition::PVRSettingDefinition(), and kodi::addon::PVRSettingDefinition::PVRSettingDefinition().
SetType()
void kodi::addon::PVRSettingDefinition::SetType (PVR_SETTING_TYPE eType) inline
required
This setting definition's identifier.
References PVR_SETTING_DEFINITION::eType, and kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::m_cStructure.
Referenced by kodi::addon::PVRSettingDefinition::PVRSettingDefinition(), kodi::addon::PVRSettingDefinition::PVRSettingDefinition(), and kodi::addon::PVRSettingDefinition::PVRSettingDefinition().