Kodi Documentation: URIUtils.cpp File Reference
URIUtils.cpp File Reference
#include "URIUtils.h"
#include "FileItem.h"
#include "FileItemList.h"
#include "ServiceBroker.h"
#include "StringUtils.h"
#include "URL.h"
#include "filesystem/MultiPathDirectory.h"
#include "filesystem/SpecialProtocol.h"
#include "filesystem/StackDirectory.h"
#include "network/DNSNameCache.h"
#include "network/Network.h"
#include "pvr/channels/PVRChannelsPath.h"
#include "settings/AdvancedSettings.h"
#include "utils/FileExtensionProvider.h"
#include "utils/log.h"
#include <algorithm>
#include <cassert>
#include <netinet/in.h>
#include <arpa/inet.h>
Functions
std::string URLEncodePath (const std::string &strPath)
std::string URLDecodePath (const std::string &strPath)
static bool addr_match (uint32_t addr, const char *target, const char *submask)
Function Documentation
addr_match()
static bool addr_match (uint32_t addr, const char * target, const char * submask) static
Referenced by URIUtils::IsHostOnLAN().
URLDecodePath()
std::string URLDecodePath (const std::string & strPath)
References KODI::UTILS::StringUtils::Join(), and KODI::UTILS::StringUtils::Split().
Referenced by URIUtils::ChangeBasePath().
URLEncodePath()
std::string URLEncodePath (const std::string & strPath)
References KODI::UTILS::StringUtils::Join(), and KODI::UTILS::StringUtils::Split().
Referenced by URIUtils::ChangeBasePath().