Kodi Documentation: CGUIDialog Class Reference
CGUIDialog Class Reference
Guilib classes » Window Reference » Windows and Messages
#include <GUIDialog.h>
Public Member Functions
CGUIDialog (int id, const std::string &xmlFile, DialogModalityType modalityType=DialogModalityType::MODAL)
~CGUIDialog (void) override
bool OnAction (const CAction &action) override
bool OnMessage (CGUIMessage &message) override
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void Open (const std::string &param="")
void Open (bool bProcessRenderLoop, const std::string &param="")
bool OnBack (int actionID) override
bool IsDialogRunning () const override
bool IsDialog () const override
bool IsModalDialog () const override
virtual DialogModalityType GetModalityType () const
void SetAutoClose (unsigned int timeoutMs)
void ResetAutoClose (void)
void CancelAutoClose (void)
bool IsAutoClosed (void) const
void SetSound (bool OnOff)
bool IsSoundEnabled () const override
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
bool OnAction (const CAction &action) override
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool OnMessage (CGUIMessage &message) override
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsMediaWindow () const
virtual bool HasListItems () const
virtual CFileItemPtr GetCurrentListItem (int offset=0)
virtual int GetViewContainerID () const
virtual int GetViewCount () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual CGUIControl * GetFirstFocusableControl (int id)
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
void SetDefaults () override
void OnWindowLoaded () override
virtual void UpdateVisibility ()
virtual void Open_Internal (bool bProcessRenderLoop, const std::string &param="")
void OnDeinitWindow (int nextWindowID) override
void ProcessRenderLoop (bool renderOnly=false)
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void OnWindowUnload ()
virtual void OnInitWindow ()
Called on window open.
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
virtual void SaveControlStates ()
virtual void RestoreControlStates ()
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
bool m_wasRunning
true if we were running during the last DoProcess()
bool m_autoClosing
bool m_enableSound
unsigned int m_showStartTime
unsigned int m_showDuration
bool m_bAutoClosed
DialogModalityType m_modalityType
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIDialog()
CGUIDialog::CGUIDialog (int id, const std::string & xmlFile, DialogModalityType modalityType = DialogModalityType::MODAL)
References m_autoClosing, m_bAutoClosed, m_enableSound, m_modalityType, CGUIWindow::m_renderOrder, m_showDuration, m_showStartTime, m_wasRunning, and RENDER_ORDER_DIALOG.
~CGUIDialog()
CGUIDialog::~CGUIDialog (void) override default
Member Function Documentation
CancelAutoClose()
void CGUIDialog::CancelAutoClose (void)
References m_autoClosing.
Referenced by CGUIDialogVolumeBar::OnAction().
DoProcess()
void CGUIDialog::DoProcess (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIDialogBusy, CGUIDialogBusyNoCancel, and CGUIDialogSettingsBase.
References CGUIWindow::DoProcess(), CGUIWindow::m_active, CGUIControl::m_renderRegion, m_wasRunning, and UpdateVisibility().
Referenced by CGUIDialogBusy::DoProcess(), CGUIDialogBusyNoCancel::DoProcess(), KODI::GAME::CGUIControllerWindow::DoProcess(), and CGUIDialogSettingsBase::DoProcess().
GetModalityType()
virtual DialogModalityType CGUIDialog::GetModalityType () const inline virtual
References m_modalityType.
IsAutoClosed()
bool CGUIDialog::IsAutoClosed (void) const inline
References m_bAutoClosed.
Referenced by CGUIDialogNumeric::ShowAndGetNumber().
IsDialog()
bool CGUIDialog::IsDialog () const inline override virtual
Reimplemented from CGUIWindow.
Reimplemented in CGUIWindowSettingsCategory.
Referenced by CGUIDialogSettingsBase::OnBack().
IsDialogRunning()
bool CGUIDialog::IsDialogRunning () const inline override virtual
Reimplemented from CGUIWindow.
References CGUIWindow::m_active.
Referenced by CGUIDialogCache::CGUIDialogCache(), CGUIDialogCache::Close(), CApplication::FrameMove(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetInt(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), CGUIDialogCache::IsCanceled(), PVR::CGUIWindowPVRGuideBase::OnContextButtonNavigate(), PVR::CGUIWindowPVRGuideBase::OnDeinitWindow(), CApplication::OnMessage(), CGUIDialogVideoOSD::OnMessage(), CGUIDialogCache::Process(), CProgressJob::ShowProgressDialog(), CGUIWindowFullScreen::ToggleOSD(), KODI::RETRO::CGameWindowFullScreen::TriggerOSD(), CGUIWindowFullScreen::TriggerOSD(), CGUIMediaWindow::WaitGetDirectoryItems(), CGUIDialogBusy::WaitOnEvent(), and CGUIDialogCache::~CGUIDialogCache().
IsModalDialog()
bool CGUIDialog::IsModalDialog () const inline override virtual
Reimplemented from CGUIWindow.
References m_modalityType, and MODAL.
IsSoundEnabled()
bool CGUIDialog::IsSoundEnabled () const inline override virtual
Reimplemented from CGUIWindow.
References m_enableSound.
Load()
bool CGUIDialog::Load (TiXmlElement * pRootElement) override protected virtual
Loads the window from the given XML element.
Parameters
pRootElement the XML element
Returns
true if the window is loaded from the given XML otherwise false.
Reimplemented from CGUIWindow.
References CGUIWindow::Load().
OnAction()
bool CGUIDialog::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControlGroup.
Reimplemented in CGUIDialogAddonInfo, CGUIDialogAddonSettings, CGUIDialogContextMenu, CGUIDialogFileBrowser, CGUIDialogGamepad, CGUIDialogKeyboardGeneric, CGUIDialogNumeric, CGUIDialogPlayerProcessInfo, CGUIDialogSlider, CGUIDialogTextViewer, CGUIDialogVolumeBar, CGUIDialogMusicInfo, CGUIDialogMusicOSD, CGUIDialogSongInfo, CGUIDialogPictureInfo, CGUIWindowSlideShow, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRChannelsOSD, PVR::CGUIDialogPVRGroupManager, PVR::CGUIDialogPVRItemsViewBase, CGUIDialogSettingsBase, CGUIWindowSettingsCategory, CGUIDialogFullScreenInfo, CGUIDialogTeletext, CGUIDialogVideoBookmarks, CGUIDialogVideoInfo, CGUIDialogVideoManager, CGUIDialogVideoOSD, and CGUIWindowScreensaver.
References m_autoClosing, m_showDuration, CGUIWindow::OnAction(), and SetAutoClose().
Referenced by CGUIDialogAddonInfo::OnAction(), CGUIDialogContextMenu::OnAction(), CGUIDialogFileBrowser::OnAction(), CGUIDialogGamepad::OnAction(), CGUIDialogKeyboardGeneric::OnAction(), CGUIDialogNumeric::OnAction(), CGUIDialogPlayerProcessInfo::OnAction(), CGUIDialogSlider::OnAction(), CGUIDialogTextViewer::OnAction(), CGUIDialogVolumeBar::OnAction(), KODI::GAME::CDialogGameOSD::OnAction(), CGUIDialogMusicInfo::OnAction(), CGUIDialogMusicOSD::OnAction(), CGUIDialogSongInfo::OnAction(), CGUIDialogPictureInfo::OnAction(), CGUIWindowSlideShow::OnAction(), PVR::CGUIDialogPVRChannelManager::OnAction(), PVR::CGUIDialogPVRGroupManager::OnAction(), PVR::CGUIDialogPVRItemsViewBase::OnAction(), CGUIDialogSettingsBase::OnAction(), CGUIDialogFullScreenInfo::OnAction(), CGUIDialogTeletext::OnAction(), CGUIDialogVideoBookmarks::OnAction(), CGUIDialogVideoInfo::OnAction(), CGUIDialogVideoManager::OnAction(), CGUIDialogVideoOSD::OnAction(), PVR::CGUIDialogPVRChannelManager::OnActionMove(), and PVR::CGUIDialogPVRGroupManager::OnActionMove().
OnBack()
bool CGUIDialog::OnBack (int actionID) override virtual
Reimplemented from CGUIWindow.
Reimplemented in CGUIDialogBusy, CGUIDialogColorPicker, CGUIDialogFileBrowser, CGUIDialogMediaSource, CGUIDialogNumeric, CGUIDialogProgress, CGUIDialogSelect, CGUIDialogSmartPlaylistEditor, CGUIDialogSmartPlaylistRule, CGUIDialogYesNo, CGUIDialogSongInfo, CGUIDialogNetworkSetup, CGUIDialogSettingsBase, CGUIWindowSettingsCategory, CGUIDialogCMSSettings, and CGUIDialogTeletext.
References Close().
OnDeinitWindow()
void CGUIDialog::OnDeinitWindow (int nextWindowID) override protected virtual
Reimplemented from CGUIWindow.
Reimplemented in CGUIDialogBoxBase, CGUIDialogColorPicker, CGUIDialogContextMenu, CGUIDialogKeyboardGeneric, CGUIDialogMediaSource, CGUIDialogNumeric, CGUIDialogSelect, CGUIDialogSmartPlaylistEditor, CGUIDialogSmartPlaylistRule, CGUIDialogTextViewer, KODI::GAME::CGUIPortWindow, CGUIDialogVisualisationPresetList, CGUIDialogNetworkSetup, CGUIDialogPictureInfo, CGUIWindowSlideShow, PVR::CGUIDialogPVRChannelGuide, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRChannelsOSD, PVR::CGUIDialogPVRGroupManager, PVR::CGUIDialogPVRItemsViewBase, CGUIDialogTeletext, and CGUIDialogVideoManager.
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), CGUIWindow::m_active, m_autoClosing, and CGUIWindow::OnDeinitWindow().
Referenced by CGUIDialogBoxBase::OnDeinitWindow(), CGUIDialogContextMenu::OnDeinitWindow(), CGUIDialogKeyboardGeneric::OnDeinitWindow(), CGUIDialogMediaSource::OnDeinitWindow(), CGUIDialogNumeric::OnDeinitWindow(), CGUIDialogSmartPlaylistEditor::OnDeinitWindow(), CGUIDialogSmartPlaylistRule::OnDeinitWindow(), CGUIDialogTextViewer::OnDeinitWindow(), KODI::GAME::CGUIAgentWindow::OnDeinitWindow(), KODI::GAME::CGUIControllerWindow::OnDeinitWindow(), KODI::GAME::CDialogGameOSD::OnDeinitWindow(), KODI::GAME::CDialogGameSaves::OnDeinitWindow(), KODI::GAME::CDialogGameVideoSelect::OnDeinitWindow(), KODI::GAME::CDialogGameVolume::OnDeinitWindow(), KODI::GAME::CGUIPortWindow::OnDeinitWindow(), CGUIDialogNetworkSetup::OnDeinitWindow(), CGUIDialogPictureInfo::OnDeinitWindow(), CGUIWindowSlideShow::OnDeinitWindow(), PVR::CGUIDialogPVRChannelManager::OnDeinitWindow(), PVR::CGUIDialogPVRGroupManager::OnDeinitWindow(), PVR::CGUIDialogPVRItemsViewBase::OnDeinitWindow(), CGUIDialogTeletext::OnDeinitWindow(), and CGUIDialogVideoManager::OnDeinitWindow().
OnMessage()
bool CGUIDialog::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControlGroup.
Reimplemented in CGUIDialogAddonInfo, CGUIDialogAddonSettings, CGUIDialogBoxBase, CGUIDialogButtonMenu, CGUIDialogColorPicker, CGUIDialogContextMenu, CGUIDialogExtendedProgressBar, CGUIDialogFileBrowser, CGUIDialogGamepad, CGUIDialogKaiToast, CGUIDialogKeyboardGeneric, CGUIDialogMediaFilter, CGUIDialogMediaSource, CGUIDialogNumeric, CGUIDialogOK, CGUIDialogPlayEject, CGUIDialogProgress, CGUIDialogSeekBar, CGUIDialogSelect, CGUIDialogSlider, CGUIDialogSmartPlaylistEditor, CGUIDialogSmartPlaylistRule, CGUIDialogSubMenu, CGUIDialogTextViewer, CGUIDialogVolumeBar, CGUIDialogYesNo, KODI::GAME::CGUIPortWindow, CGUIDialogMusicInfo, CGUIDialogMusicOSD, CGUIDialogSongInfo, CGUIDialogVisualisationPresetList, CGUIDialogNetworkSetup, PERIPHERALS::CGUIDialogPeripherals, PERIPHERALS::CGUIDialogPeripheralSettings, CGUIWindowSlideShow, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRChannelsOSD, PVR::CGUIDialogPVRGroupManager, PVR::CGUIDialogPVRGuideInfo, PVR::CGUIDialogPVRGuideSearch, PVR::CGUIDialogPVRRadioRDSInfo, PVR::CGUIDialogPVRRecordingInfo, CGUIDialogLibExportSettings, CGUIDialogSettingsBase, CGUIWindowSettingsCategory, CGUIDialogSubtitles, CGUIDialogSubtitleSettings, CGUIDialogTeletext, CGUIDialogVideoBookmarks, CGUIDialogVideoInfo, CGUIDialogVideoManager, CGUIDialogVideoManagerExtras, CGUIDialogVideoManagerVersions, CGUIDialogVideoOSD, CGUIWindowDebugInfo, and CGUIWindowScreensaver.
References CGUIMessage::GetMessage(), GUI_MSG_WINDOW_DEINIT, GUI_MSG_WINDOW_INIT, m_showStartTime, and CGUIWindow::OnMessage().
Referenced by CGUIDialogPictureInfo::OnDeinitWindow(), KODI::GAME::CDialogGameOSDHelp::OnInitWindow(), CGUIDialogAddonInfo::OnMessage(), CGUIDialogBoxBase::OnMessage(), CGUIDialogButtonMenu::OnMessage(), CGUIDialogContextMenu::OnMessage(), CGUIDialogExtendedProgressBar::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogGamepad::OnMessage(), CGUIDialogKaiToast::OnMessage(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIDialogMediaSource::OnMessage(), CGUIDialogNumeric::OnMessage(), CGUIDialogProgress::OnMessage(), CGUIDialogSeekBar::OnMessage(), CGUIDialogSlider::OnMessage(), CGUIDialogSmartPlaylistEditor::OnMessage(), CGUIDialogSmartPlaylistRule::OnMessage(), CGUIDialogSubMenu::OnMessage(), CGUIDialogTextViewer::OnMessage(), CGUIDialogVolumeBar::OnMessage(), KODI::GAME::CGUIAgentWindow::OnMessage(), KODI::GAME::CGUIControllerWindow::OnMessage(), KODI::GAME::CDialogGameAdvancedSettings::OnMessage(), KODI::GAME::CDialogGameSaves::OnMessage(), KODI::GAME::CDialogGameVideoSelect::OnMessage(), KODI::GAME::CGUIPortWindow::OnMessage(), CGUIDialogMusicInfo::OnMessage(), CGUIDialogMusicOSD::OnMessage(), CGUIDialogSongInfo::OnMessage(), CGUIWindowSlideShow::OnMessage(), PVR::CGUIDialogPVRChannelManager::OnMessage(), PVR::CGUIDialogPVRGroupManager::OnMessage(), PVR::CGUIDialogPVRGuideInfo::OnMessage(), PVR::CGUIDialogPVRGuideSearch::OnMessage(), PVR::CGUIDialogPVRRecordingInfo::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIDialogSubtitles::OnMessage(), CGUIDialogTeletext::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIDialogVideoManager::OnMessage(), CGUIDialogVideoOSD::OnMessage(), CGUIWindowDebugInfo::OnMessage(), Open_Internal(), and CGUIDialogPictureInfo::UpdatePictureInfo().
OnWindowLoaded()
void CGUIDialog::OnWindowLoaded () override protected virtual
Reimplemented from CGUIWindow.
Reimplemented in CGUIDialogColorPicker, CGUIDialogContextMenu, CGUIDialogFileBrowser, CGUIDialogKeyboardGeneric, CGUIDialogMediaFilter, CGUIDialogProgress, CGUIDialogSelect, CGUIDialogSlider, KODI::GAME::CGUIPortWindow, CGUIDialogProfileSettings, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRGroupManager, PVR::CGUIDialogPVRGuideSearch, PVR::CGUIDialogPVRItemsViewBase, CGUIWindowSettingsCategory, CGUIDialogVideoBookmarks, and CGUIWindowPointer.
References CGUIControl::GetWidth(), CGUILabelControl::GetWidth(), CGUIControl::GetXPosition(), CGUIControl::GUICONTROL_LABEL, CGUIControlGroup::m_children, CGUIWindow::OnWindowLoaded(), and CGUILabelControl::SetWidth().
Referenced by CGUIDialogColorPicker::OnWindowLoaded(), CGUIDialogContextMenu::OnWindowLoaded(), CGUIDialogFileBrowser::OnWindowLoaded(), CGUIDialogKeyboardGeneric::OnWindowLoaded(), CGUIDialogMediaFilter::OnWindowLoaded(), CGUIDialogProgress::OnWindowLoaded(), CGUIDialogSelect::OnWindowLoaded(), CGUIDialogSlider::OnWindowLoaded(), KODI::GAME::CGUIAgentWindow::OnWindowLoaded(), KODI::GAME::CDialogGameSaves::OnWindowLoaded(), KODI::GAME::CDialogGameVideoSelect::OnWindowLoaded(), KODI::GAME::CGUIPortWindow::OnWindowLoaded(), CGUIDialogProfileSettings::OnWindowLoaded(), PVR::CGUIDialogPVRChannelManager::OnWindowLoaded(), PVR::CGUIDialogPVRGroupManager::OnWindowLoaded(), PVR::CGUIDialogPVRGuideSearch::OnWindowLoaded(), PVR::CGUIDialogPVRItemsViewBase::OnWindowLoaded(), CGUIWindowSettingsCategory::OnWindowLoaded(), and CGUIDialogVideoBookmarks::OnWindowLoaded().
Open() [1/2]
void CGUIDialog::Open (bool bProcessRenderLoop, const std::string & param = "")
References CServiceBroker::GetAppMessenger(), CServiceBroker::GetWinSystem(), Open_Internal(), and TMSG_GUI_DIALOG_OPEN.
Open() [2/2]
void CGUIDialog::Open (const std::string & param = "")
References m_modalityType, MODELESS, and Open().
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonDeleteGroup(), anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), CGUIViewState::ChooseSortMethod(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::ChooseStackItemPartNumber(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), CVideoDatabase::CleanMediaType(), XBMCAddon::xbmcgui::Dialog::colorpicker(), CGUIComponent::ConfirmDelete(), CMusicDatabase::DeleteCDDBInfo(), CProfileManager::DeleteProfile(), CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), CGUIDialogSlider::Display(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CGUIDialogSmartPlaylistEditor::EditPlaylist(), CGUIDialogSmartPlaylistRule::EditRule(), CApplication::FrameMove(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), CGUIDialogExtendedProgressBar::GetHandle(), CGUIDialogVideoInfo::GetItemsForTag(), CGUIDialogVideoInfo::GetMoviesForSet(), CGUIDialogVideoInfo::GetSetForMovie(), CStereoscopicsManager::GetStereoModeByUserChoice(), KODI::GAME::CGameClientProperties::InstallDependencies(), CGUIDialogVideoInfo::LinkMovieToTvShow(), XBMCAddon::xbmcgui::Dialog::multiselect(), CGUIDialogSmartPlaylistEditor::NewPlaylist(), CGUIWindowSlideShow::OnAction(), CPlayerController::OnAction(), CGUIWindowFullScreen::OnAction(), CGUIWindowManager::OnApplicationMessage(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIControlColorButtonSetting::OnClick(), CGUIControlListSetting::OnClick(), PVR::CGUIDialogPVRChannelManager::OnClickButtonGroupManager(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonPlay(), PVR::CGUIDialogPVRRecordingInfo::OnClickButtonPlay(), PVR::CGUIDialogPVRChannelManager::OnContextButton(), PVR::CGUIWindowPVRGuideBase::OnContextButtonNavigate(), CGUIWindowVideoNav::OnDeleteItem(), CGUIDialogSmartPlaylistRule::OnField(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), CGUIWindowPictures::OnItemInfo(), CGUIDialogSmartPlaylistEditor::OnLimit(), CGUIDialogVideoInfo::OnMessage(), CGUIWindowVisualisation::OnMouseEvent(), CGUIDialogSmartPlaylistRule::OnOperator(), CGUIDialogSmartPlaylistEditor::OnOrder(), CGUIWindowVideoBase::OnSearch(), CGUIDialogVideoInfo::OnSearch(), CGUIDialogVideoInfo::OnSearchItemFound(), CGUIDialogLockSettings::OnSettingAction(), PVR::CPVRGUIActionListener::OnSettingAction(), CGUIDialogContentSettings::OnSettingAction(), CGUIDialogSubtitleSettings::OnSettingAction(), CGUIDialogVideoInfo::OnSetUserrating(), CPowerManager::OnSleep(), CStereoscopicsManager::OnStreamChange(), CGUIDialogSmartPlaylistEditor::OnType(), PVR::CGUIDialogPVRChannelManager::Open(), PVR::CGUIDialogPVRChannelGuide::Open(), KODI::GAME::CDialogGameSaves::Open(), CGUIDialogProgress::Open(), Open(), ADDON::Interface_GUIDialogSelect::open(), ADDON::Interface_GUIDialogTextViewer::open(), ADDON::Interface_GUIDialogSelect::open_multi_select(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), anonymous_namespace{VideoStreamSelectHelper.cpp}::OpenSelectDialog(), CGUIDialogVideoInfo::Play(), CPowerManager::Powerdown(), ADDON::CAddonStatusHandler::Process(), CExternalPlayer::Process(), PVR::CPVRGUIActionsClients::ProcessSettingsMenuHooks(), PVR::CGUIDialogPVRChannelManager::PromptAndSaveList(), CPowerManager::Reboot(), CGUIWindowSettingsScreenCalibration::ResetCalibration(), anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::Select(), anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::Select(), XBMCAddon::xbmcgui::Dialog::select(), CGUIWindowAddonBrowser::SelectAddonID(), SelectBool(), SetColor(), CGUIDialogInfoProviderSettings::Show(), CGUIDialogInfoProviderSettings::Show(), CGUIDialogLibExportSettings::Show(), PERIPHERALS::CGUIDialogPeripherals::Show(), CGUIDialogMediaSource::ShowAndAddMediaSource(), CGUIDialogMediaFilter::ShowAndEditMediaFilter(), CGUIDialogMediaSource::ShowAndEditMediaSource(), CGUIDialogContextMenu::ShowAndGetChoice(), CGUIDialogNumeric::ShowAndGetDate(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFileList(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), CGUIDialogFileBrowser::ShowAndGetImage(), CGUIDialogKeyboardGeneric::ShowAndGetInput(), CGUIDialogKeyboardTouch::ShowAndGetInput(), CGUIDialogOK::ShowAndGetInput(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogOK::ShowAndGetInput(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogOK::ShowAndGetInput(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogSlider::ShowAndGetInput(), CGUIDialogPlayEject::ShowAndGetInput(), CGUIDialogNumeric::ShowAndGetIPAddress(), CGUIDialogLockSettings::ShowAndGetLock(), CGUIDialogNetworkSetup::ShowAndGetNetworkAddress(), CGUIDialogNumeric::ShowAndGetNumber(), CGUIDialogNumeric::ShowAndGetSeconds(), CGUIDialogFileBrowser::ShowAndGetSource(), CGUIDialogNumeric::ShowAndGetTime(), CGUIDialogLockSettings::ShowAndGetUserAndPassword(), CGUIDialogNumeric::ShowAndVerifyInput(), KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), CGUIDialogAddonInfo::ShowDependencyList(), PVR::CPVRGUIActionsEPG::ShowEPGInfo(), CGUIDialogMusicInfo::ShowFor(), CGUIDialogSongInfo::ShowFor(), CGUIDialogTextViewer::ShowForFile(), CGUIDialogAddonInfo::ShowForItem(), CGUIDialogAddonSettings::ShowForMultipleInstances(), CGUIDialogProfileSettings::ShowForProfile(), CGUIDialogAddonSettings::ShowForSingleInstance(), PVR::CGUIWindowPVRChannelsBase::ShowGroupManager(), CGUIWindowVideoBase::ShowInfo(), CGUIDialogSimpleMenu::ShowPlaySelection(), PVR::CPVRGUIActionsRecordings::ShowRecordingInfo(), PVR::CPVRGUIActionsRecordings::ShowRecordingSettings(), MUSIC_UTILS::ShowSelectArtTypeDialog(), MUSIC_UTILS::ShowSelectRatingDialog(), PVR::CPVRGUIActionsTimers::ShowTimerSettings(), CApplicationVolumeHandling::ShowVolumeBar(), PVR::CPVRGUIActionsChannels::StartChannelScan(), XBMCAddon::xbmcgui::Dialog::textviewer(), CGUIWindowFullScreen::ToggleOSD(), KODI::RETRO::CGameWindowFullScreen::TriggerOSD(), CGUIWindowFullScreen::TriggerOSD(), UpdateVisibility(), CGUIWindowDebugInfo::UpdateVisibility(), CGUIWindowPointer::UpdateVisibility(), CGUIWindowScreensaverDim::UpdateVisibility(), CGUIDialogBusy::WaitOnEvent(), and CVideoLibraryRefreshingJob::Work().
Open_Internal()
void CGUIDialog::Open_Internal (bool bProcessRenderLoop, const std::string & param = "") protected virtual
Reimplemented in CGUIDialogBusy, and CGUIDialogBusyNoCancel.
References ANIM_TYPE_WINDOW_CLOSE, Close(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_WINDOW_INIT, CGUIWindow::IsAnimating(), CGUIWindow::m_active, CGUIWindow::m_closing, CGUIWindow::m_windowLoaded, OnMessage(), ProcessRenderLoop(), and CGUIMessage::SetStringParam().
Referenced by Open(), CGUIDialogBusy::Open_Internal(), and CGUIDialogBusyNoCancel::Open_Internal().
ProcessRenderLoop()
void CGUIDialog::ProcessRenderLoop (bool renderOnly = false) protected
References CServiceBroker::GetGUI(), and CGUIComponent::GetWindowManager().
Referenced by Open_Internal(), CGUIDialogProgress::Progress(), and CGUIDialogBusy::WaitOnEvent().
Render()
void CGUIDialog::Render () override virtual
Reimplemented from CGUIControlGroup.
Reimplemented in CGUIDialogBusy, CGUIDialogBusyNoCancel, CGUIWindowSlideShow, CGUIDialogTeletext, CGUIWindowDebugInfo, CGUIWindowScreensaver, and CGUIWindowScreensaverDim.
References CGUIWindow::m_active, and CGUIControl::Render().
Referenced by CGUIDialogBusy::Render(), CGUIDialogBusyNoCancel::Render(), CGUIDialogTeletext::Render(), CGUIWindowScreensaver::Render(), and CGUIWindowScreensaverDim::Render().
ResetAutoClose()
void CGUIDialog::ResetAutoClose (void)
References CTimeUtils::GetFrameTime(), CGUIWindow::m_active, m_autoClosing, and m_showStartTime.
Referenced by CGUIDialogNumeric::OnNumber(), and SetAutoClose().
SetAutoClose()
void CGUIDialog::SetAutoClose (unsigned int timeoutMs)
References m_autoClosing, m_showDuration, and ResetAutoClose().
Referenced by CGUIDialogSlider::Display(), CGUIDialogMusicOSD::FrameMove(), CGUIDialogVideoOSD::FrameMove(), XBMCAddon::xbmcgui::Dialog::multiselect(), CGUIDialogVolumeBar::OnAction(), OnAction(), CGUIWindowVisualisation::OnMouseEvent(), ADDON::Interface_GUIDialogSelect::open(), ADDON::Interface_GUIDialogSelect::open_multi_select(), XBMCAddon::xbmcgui::Dialog::select(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogPlayEject::ShowAndGetInput(), CGUIDialogNumeric::ShowAndGetNumber(), and CGUIWindowFullScreen::TriggerOSD().
SetDefaults()
void CGUIDialog::SetDefaults () override protected virtual
Reimplemented from CGUIWindow.
References CGUIWindow::m_renderOrder, RENDER_ORDER_DIALOG, and CGUIWindow::SetDefaults().
SetSound()
void CGUIDialog::SetSound (bool OnOff) inline
References m_enableSound.
Referenced by CGUIDialogKaiToast::DoWork().
UpdateVisibility()
void CGUIDialog::UpdateVisibility () protected virtual
Reimplemented in CGUIWindowDebugInfo, CGUIWindowPointer, CGUIWindowScreensaver, and CGUIWindowScreensaverDim.
References Close(), INFO::DEFAULT_CONTEXT, CTimeUtils::GetFrameTime(), CGUIControl::HasProcessed(), m_autoClosing, m_bAutoClosed, CGUIWindow::m_closing, m_showDuration, m_showStartTime, CGUIControl::m_visibleCondition, and Open().
Referenced by DoProcess().
Member Data Documentation
m_autoClosing
bool CGUIDialog::m_autoClosing protected
Referenced by CancelAutoClose(), CGUIDialog(), CGUIDialogMusicOSD::FrameMove(), CGUIDialogVideoOSD::FrameMove(), OnAction(), OnDeinitWindow(), ResetAutoClose(), SetAutoClose(), and UpdateVisibility().
m_bAutoClosed
bool CGUIDialog::m_bAutoClosed protected
Referenced by CGUIDialog(), IsAutoClosed(), CGUIDialogYesNo::Reset(), and UpdateVisibility().
m_enableSound
bool CGUIDialog::m_enableSound protected
Referenced by CGUIDialog(), IsSoundEnabled(), and SetSound().
m_modalityType
DialogModalityType CGUIDialog::m_modalityType protected
Referenced by CGUIDialog(), GetModalityType(), IsModalDialog(), Open(), and CGUIDialogSlider::SetModalityType().
m_showDuration
unsigned int CGUIDialog::m_showDuration protected
Referenced by CGUIDialog(), CGUIDialogMusicOSD::FrameMove(), CGUIDialogVideoOSD::FrameMove(), OnAction(), SetAutoClose(), and UpdateVisibility().
m_showStartTime
unsigned int CGUIDialog::m_showStartTime protected
Referenced by CGUIDialog(), OnMessage(), ResetAutoClose(), and UpdateVisibility().
m_wasRunning
bool CGUIDialog::m_wasRunning protected
true if we were running during the last DoProcess()
Referenced by CGUIDialog(), and DoProcess().
The documentation for this class was generated from the following files:
GUIDialog.h
GUIDialog.cpp