Kodi Documentation: KODI::GAME::CGameClientHardware Class Reference
KODI::GAME::CGameClientHardware Class Reference
Games
Handles events for hardware such as reset buttons.
#include <GameClientHardware.h>
Public Member Functions
CGameClientHardware (CGameClient &gameClient)
Constructor.
~CGameClientHardware () override=default
void OnResetButton () override
A hardware reset button has been pressed.
Public Member Functions inherited from KODI::HARDWARE::IHardwareInput
virtual ~IHardwareInput ()=default
Private Attributes
CGameClient & m_gameClient
Detailed Description
Handles events for hardware such as reset buttons.
Constructor & Destructor Documentation
CGameClientHardware()
CGameClientHardware::CGameClientHardware (CGameClient & gameClient) explicit
Constructor.
Parameters
gameClient The game client implementation
~CGameClientHardware()
KODI::GAME::CGameClientHardware::~CGameClientHardware () override default
Member Function Documentation
OnResetButton()
void CGameClientHardware::OnResetButton () override virtual
A hardware reset button has been pressed.
Implements KODI::HARDWARE::IHardwareInput.
References ADDON::CAddon::ID(), CLog::Log(), LOGDEBUG, m_gameClient, and KODI::GAME::CGameClient::Reset().
Member Data Documentation
m_gameClient
CGameClient& KODI::GAME::CGameClientHardware::m_gameClient private
Referenced by OnResetButton().
The documentation for this class was generated from the following files:
GameClientHardware.h
GameClientHardware.cpp