Kodi Documentation: CUdpClient Class Reference
CUdpClient Class Reference
#include <UdpClient.h>
Classes
struct UdpCommand
Public Member Functions
CUdpClient ()
~CUdpClient (void) override
Protected Types
typedef std::vector< UdpCommand >::iterator COMMANDITERATOR
Protected Member Functions
bool Create ()
void Destroy ()
void OnStartup () override
void Process () override
bool Broadcast (int aPort, const std::string &aMessage)
bool Send (const std::string &aIpAddress, int aPort, const std::string &aMessage)
bool Send (struct sockaddr_in aAddress, const std::string &aMessage)
bool Send (struct sockaddr_in aAddress, unsigned char *pMessage, DWORD dwSize)
virtual void OnMessage (struct sockaddr_in &aRemoteAddress, const std::string &aMessage, unsigned char *pMessage, DWORD dwMessageLength)
bool DispatchNextCommand ()
Protected Attributes
SOCKET client_socket
std::vector< UdpCommand > commands
CCriticalSection critical_section
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Member Typedef Documentation
COMMANDITERATOR
typedef std::vector<UdpCommand>::iterator CUdpClient::COMMANDITERATOR protected
Constructor & Destructor Documentation
CUdpClient()
CUdpClient::CUdpClient (void)
~CUdpClient()
CUdpClient::~CUdpClient (void) override default
Member Function Documentation
Broadcast()
bool CUdpClient::Broadcast (int aPort, const std::string & aMessage) protected
References commands, and critical_section.
Create()
bool CUdpClient::Create (void) protected
References client_socket, CThread::Create(), ioctlsocket, CLog::Log(), CThread::m_bStop, SOCKET_ERROR, UDPCLIENT_DEBUG_LEVEL, and value.
Destroy()
void CUdpClient::Destroy () protected
References client_socket, closesocket, and CThread::StopThread().
DispatchNextCommand()
bool CUdpClient::DispatchNextCommand () protected
References CUdpClient::UdpCommand::address, CUdpClient::UdpCommand::binary, CUdpClient::UdpCommand::binarySize, client_socket, commands, critical_section, CLog::Log(), CThread::m_bStop, CUdpClient::UdpCommand::message, and UDPCLIENT_DEBUG_LEVEL.
Referenced by Process().
OnMessage()
virtual void CUdpClient::OnMessage (struct sockaddr_in & aRemoteAddress, const std::string & aMessage, unsigned char * pMessage, DWORD dwMessageLength) inline protected virtual
Referenced by Process().
OnStartup()
void CUdpClient::OnStartup () override protected virtual
Reimplemented from CThread.
References LOWEST, and CThread::SetPriority().
Process()
void CUdpClient::Process (void) override protected virtual
Reimplemented from CThread.
References client_socket, closesocket, DispatchNextCommand(), ioctlsocket, CLog::Log(), LOGERROR, CThread::m_bStop, OnMessage(), CThread::Sleep(), SOCKET_ERROR, UDPCLIENT_DEBUG_LEVEL, and WSAGetLastError.
Send() [1/3]
bool CUdpClient::Send (const std::string & aIpAddress, int aPort, const std::string & aMessage) protected
References commands, and critical_section.
Send() [2/3]
bool CUdpClient::Send (struct sockaddr_in aAddress, const std::string & aMessage) protected
References commands, and critical_section.
Send() [3/3]
bool CUdpClient::Send (struct sockaddr_in aAddress, unsigned char * pMessage, DWORD dwSize) protected
References commands, and critical_section.
Member Data Documentation
client_socket
SOCKET CUdpClient::client_socket protected
Referenced by Create(), Destroy(), DispatchNextCommand(), and Process().
commands
std::vector<UdpCommand> CUdpClient::commands protected
Referenced by Broadcast(), DispatchNextCommand(), Send(), Send(), and Send().
critical_section
CCriticalSection CUdpClient::critical_section protected
Referenced by Broadcast(), DispatchNextCommand(), Send(), Send(), and Send().
The documentation for this class was generated from the following files:
UdpClient.h
UdpClient.cpp