Kodi Documentation: TestBasicEnvironment Class Reference
TestBasicEnvironment Class Reference
#include <TestBasicEnvironment.h>
Public Member Functions
TestBasicEnvironment ()
void SetUp () override
void TearDown () override
Private Member Functions
void SetUpError ()
Private Attributes
std::string m_tempPath
Constructor & Destructor Documentation
TestBasicEnvironment()
TestBasicEnvironment::TestBasicEnvironment () default
Member Function Documentation
SetUp()
void TestBasicEnvironment::SetUp () override
Todo:
Something should be done about all the asserts in GUISettings so that the initialization of these components won't be needed.
Todo:
Make the initialization of the VFS here optional so it can be testable in a test case.
References KODI::PLATFORM::FILESYSTEM::create_temp_directory(), f, g_application, CUtil::GetFrameworksPath(), CServiceBroker::GetSettingsComponent(), CXBMCTestUtils::Instance(), m_tempPath, CServiceBroker::RegisterAppMessenger(), CSpecialProtocol::SetProfilePath(), CSpecialProtocol::SetTempPath(), CXBMCTestUtils::setTestFileFactoryWriteInputFile(), CAppEnvironment::SetUp(), SetUpError(), CSpecialProtocol::SetXBMCFrameworksPath(), TearDown(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_REF_FILE_PATH.
SetUpError()
void TestBasicEnvironment::SetUpError () private
Referenced by SetUp().
TearDown()
void TestBasicEnvironment::TearDown () override
References g_application, m_tempPath, XFILE::CDirectory::RemoveRecursive(), CAppEnvironment::TearDown(), and CServiceBroker::UnregisterAppMessenger().
Referenced by SetUp().
Member Data Documentation
m_tempPath
std::string TestBasicEnvironment::m_tempPath private
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following files:
TestBasicEnvironment.h
TestBasicEnvironment.cpp