Kodi Documentation: ADDON::Interface_GUIDialogExtendedProgress Struct Reference
ADDON::Interface_GUIDialogExtendedProgress Struct Reference
Global gui Add-on to Kodi callback functions.
#include <ExtendedProgressBar.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static KODI_GUI_HANDLE new_dialog (KODI_HANDLE kodiBase, const char *title)
callback functions from add-on to kodi
static void delete_dialog (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
static char * get_title (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
static void set_title (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char *title)
static char * get_text (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
static void set_text (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char *text)
static bool is_finished (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
static void mark_finished (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
static float get_percentage (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
static void set_percentage (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, float percentage)
static void set_progress (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int currentItem, int itemCount)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/dialogs/ExtendedProgress.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIDialogExtendedProgress::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogExtendedProgress, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
delete_dialog()
void ADDON::Interface_GUIDialogExtendedProgress::delete_dialog (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_percentage()
float ADDON::Interface_GUIDialogExtendedProgress::get_percentage (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_text()
char * ADDON::Interface_GUIDialogExtendedProgress::get_text (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_title()
char * ADDON::Interface_GUIDialogExtendedProgress::get_title (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIDialogExtendedProgress::Init (AddonGlobalInterface * addonInterface) static
References delete_dialog(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::delete_dialog, AddonToKodiFuncTable_kodi_gui::dialogExtendedProgress, get_percentage(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::get_percentage, get_text(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::get_text, get_title(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::get_title, is_finished(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::is_finished, AddonToKodiFuncTable_Addon::kodi_gui, mark_finished(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::mark_finished, new_dialog(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::new_dialog, set_percentage(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::set_percentage, set_progress(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::set_progress, set_text(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::set_text, set_title(), AddonToKodiFuncTable_kodi_gui_dialogExtendedProgress::set_title, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
is_finished()
bool ADDON::Interface_GUIDialogExtendedProgress::is_finished (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
mark_finished()
void ADDON::Interface_GUIDialogExtendedProgress::mark_finished (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
new_dialog()
KODI_GUI_HANDLE ADDON::Interface_GUIDialogExtendedProgress::new_dialog (KODI_HANDLE kodiBase, const char * title) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References CServiceBroker::GetGUI(), CGUIDialogExtendedProgressBar::GetHandle(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and WINDOW_DIALOG_EXT_PROGRESS.
Referenced by Init().
set_percentage()
void ADDON::Interface_GUIDialogExtendedProgress::set_percentage (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, float percentage) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
set_progress()
void ADDON::Interface_GUIDialogExtendedProgress::set_progress (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int currentItem, int itemCount) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
set_text()
void ADDON::Interface_GUIDialogExtendedProgress::set_text (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char * text) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and text.
Referenced by Init().
set_title()
void ADDON::Interface_GUIDialogExtendedProgress::set_title (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char * title) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
The documentation for this struct was generated from the following files:
ExtendedProgressBar.h
ExtendedProgressBar.cpp