Kodi Documentation: class Peripheral
class Peripheral
C++ » Interface - kodi::addon » Addon type instances » Peripheral » Definitions, structures and enumerators » 2. Peripheral
Wrapper class providing peripheral information
Classes can extend Peripheral to inherit peripheral properties.
Classes
class kodi::addon::Peripheral
Functions
kodi::addon::Peripheral::Peripheral (PERIPHERAL_TYPE type=PERIPHERAL_TYPE_UNKNOWN, const std::string &strName="")
Constructor.
virtual kodi::addon::Peripheral::~Peripheral (void)=default
Destructor.
bool kodi::addon::Peripheral::operator== (const Peripheral &rhs) const
Comparison operator.
PERIPHERAL_TYPE kodi::addon::Peripheral::Type (void) const
Get peripheral type.
const std::string & kodi::addon::Peripheral::Name (void) const
Get peripheral name.
uint16_t kodi::addon::Peripheral::VendorID (void) const
Get peripheral vendor id.
uint16_t kodi::addon::Peripheral::ProductID (void) const
Get peripheral product id.
unsigned int kodi::addon::Peripheral::Index (void) const
Get peripheral index identifier.
bool kodi::addon::Peripheral::IsVidPidKnown (void) const
Check VID and PID are known.
void kodi::addon::Peripheral::SetType (PERIPHERAL_TYPE type)
Set peripheral type.
void kodi::addon::Peripheral::SetName (const std::string &strName)
Set peripheral name.
void kodi::addon::Peripheral::SetVendorID (uint16_t vendorId)
Set peripheral vendor id.
void kodi::addon::Peripheral::SetProductID (uint16_t productId)
Set peripheral product identifier.
void kodi::addon::Peripheral::SetIndex (unsigned int index)
Set peripheral index.
Detailed Description
Wrapper class providing peripheral information
Classes can extend Peripheral to inherit peripheral properties.
Used on kodi::addon::CInstancePeripheral::PerformDeviceScan().
@ingroup cpp_kodi_addon_peripheral_Defs_Peripheral_Peripheral
The following table contains values that can be set with class Peripheral :
Name Type Set call Get call
Peripheral type PERIPHERAL_TYPE SetType Type
Peripheral name const std::string& SetName Name
Peripheral vendor id uint16_t SetVendorID VendorID
Peripheral product id uint16_t SetProductID ProductID
Peripheral index unsigned int SetIndex Index
Further are following included:
Peripheral(PERIPHERAL_TYPE type = PERIPHERAL_TYPE_UNKNOWN, const std::string& strName = ""): Class constructor.
IsVidPidKnown(): To check VID and PID are known.
Function Documentation
Index()
unsigned int kodi::addon::Peripheral::Index (void) const inline
Get peripheral index identifier.
Returns
Index number
References kodi::addon::Peripheral::m_index.
Referenced by PERIPHERALS::CPeripheralAddon::PerformDeviceScan().
IsVidPidKnown()
bool kodi::addon::Peripheral::IsVidPidKnown (void) const inline
Check VID and PID are known.
Returns
true if VID and PID are not 0
Note
Derived property: VID and PID are 0x0000 if unknown
References kodi::addon::Peripheral::m_productId, and kodi::addon::Peripheral::m_vendorId.
Name()
const std::string & kodi::addon::Peripheral::Name (void) const inline
Get peripheral name.
Returns
Name string of peripheral
References kodi::addon::Peripheral::m_strName.
Referenced by PERIPHERALS::CPeripheralAddon::PerformDeviceScan().
operator==()
bool kodi::addon::Peripheral::operator== (const Peripheral & rhs) const inline
Comparison operator.
Note
The index is not included in the comparison because it is affected by the presence of other peripherals
References kodi::addon::Peripheral::m_productId, kodi::addon::Peripheral::m_strName, kodi::addon::Peripheral::m_type, and kodi::addon::Peripheral::m_vendorId.
Referenced by kodi::addon::Joystick::operator==().
Peripheral()
kodi::addon::Peripheral::Peripheral (PERIPHERAL_TYPE type = PERIPHERAL_TYPE_UNKNOWN, const std::string & strName = "") inline
Constructor.
Parameters
[in] type [optional] Peripheral type, or PERIPHERAL_TYPE_UNKNOWN as default
[in] strName [optional] Name of related peripheral
ProductID()
uint16_t kodi::addon::Peripheral::ProductID (void) const inline
Get peripheral product id.
Returns
Product id
References kodi::addon::Peripheral::m_productId.
Referenced by PERIPHERALS::CPeripheralAddon::PerformDeviceScan().
SetIndex()
void kodi::addon::Peripheral::SetIndex (unsigned int index) inline
Set peripheral index.
Parameters
[in] index Type to set
References index(), and kodi::addon::Peripheral::m_index.
SetName()
void kodi::addon::Peripheral::SetName (const std::string & strName) inline
Set peripheral name.
Parameters
[in] strName Name to set
References kodi::addon::Peripheral::m_strName.
Referenced by PERIPHERALS::CPeripheralAddon::GetJoystickInfo(), and PERIPHERALS::CPeripheralAddon::GetPeripheralInfo().
SetProductID()
void kodi::addon::Peripheral::SetProductID (uint16_t productId) inline
Set peripheral product identifier.
Parameters
[in] productId Type to set
References kodi::addon::Peripheral::m_productId.
Referenced by PERIPHERALS::CPeripheralAddon::GetPeripheralInfo().
SetType()
void kodi::addon::Peripheral::SetType (PERIPHERAL_TYPE type) inline
Set peripheral type.
Parameters
[in] type Type to set
References kodi::addon::Peripheral::m_type.
Referenced by PERIPHERALS::CPeripheralAddon::GetPeripheralInfo().
SetVendorID()
void kodi::addon::Peripheral::SetVendorID (uint16_t vendorId) inline
Set peripheral vendor id.
Parameters
[in] vendorId Type to set
References kodi::addon::Peripheral::m_vendorId.
Referenced by PERIPHERALS::CPeripheralAddon::GetPeripheralInfo().
Type()
PERIPHERAL_TYPE kodi::addon::Peripheral::Type (void) const inline
Get peripheral type.
Returns
Type defined with PERIPHERAL_TYPE
References kodi::addon::Peripheral::m_type.
Referenced by PERIPHERALS::CPeripheralAddon::PerformDeviceScan().
VendorID()
uint16_t kodi::addon::Peripheral::VendorID (void) const inline
Get peripheral vendor id.
Returns
Vendor id
References kodi::addon::Peripheral::m_vendorId.
Referenced by PERIPHERALS::CPeripheralAddon::PerformDeviceScan().
~Peripheral()
virtual kodi::addon::Peripheral::~Peripheral (void) virtual default
Destructor.