Kodi Documentation: CURL Class Reference
CURL Class Reference
#include <URL.h>
Public Member Functions
CURL (std::string strURL)
CURL ()=default
virtual ~CURL (void)
bool operator== (const std::string &url) const
void Reset ()
void Parse (std::string strURL)
void SetFileName (std::string strFileName)
void SetHostName (std::string strHostName)
void SetUserName (std::string strUserName)
void SetDomain (std::string strDomain)
void SetPassword (std::string strPassword)
void SetProtocol (std::string strProtocol)
void SetOptions (std::string strOptions)
void SetProtocolOptions (std::string strOptions)
void SetPort (int port)
bool HasPort () const
int GetPort () const
const std::string & GetHostName () const
const std::string & GetDomain () const
const std::string & GetUserName () const
const std::string & GetPassWord () const
const std::string & GetFileName () const
const std::string & GetProtocol () const
std::string GetTranslatedProtocol () const
const std::string & GetFileType () const
const std::string & GetShareName () const
const std::string & GetOptions () const
const std::string & GetProtocolOptions () const
std::string GetFileNameWithoutPath () const
char GetDirectorySeparator () const
std::string Get () const
std::string GetWithoutOptions () const
std::string GetWithoutUserDetails (bool redact=false) const
std::string GetWithoutFilename () const
std::string GetRedacted () const
bool IsLocal () const
bool IsLocalHost () const
bool IsProtocol (const char *type) const
Check whether a URL is a given URL scheme. Comparison is case-insensitive as per RFC1738.
bool IsFileType (const char *type) const
Check whether a URL is a given filetype. Comparison is effectively case-insensitive as both the parameter and m_strFileType are lower-case.
void GetOptions (std::map< std::string, std::string > &options) const
bool HasOption (const std::string &key) const
bool GetOption (const std::string &key, std::string &value) const
std::string GetOption (const std::string &key) const
void SetOption (const std::string &key, const std::string &value)
void RemoveOption (const std::string &key)
void GetProtocolOptions (std::map< std::string, std::string > &options) const
bool HasProtocolOption (const std::string &key) const
bool GetProtocolOption (const std::string &key, std::string &value) const
std::string GetProtocolOption (const std::string &key) const
void SetProtocolOption (const std::string &key, const std::string &value)
void RemoveProtocolOption (const std::string &key)
Static Public Member Functions
static std::string GetRedacted (std::string path)
static bool IsFileOnly (const std::string &url)
return true if there are no directories in the url.
static bool IsFullPath (const std::string &url)
return true if the url includes the full path
static std::string Decode (std::string_view strURLData)
static std::string Encode (std::string_view strURLData)
static bool IsProtocolEqual (const std::string &protocol, const char *type)
Check whether a URL protocol is a given URL scheme. Both parameters MUST be lower-case. Typically this would be called using the result of TranslateProtocol() which enforces this for protocol.
Protected Attributes
int m_iPort = 0
std::string m_strHostName
std::string m_strShareName
std::string m_strDomain
std::string m_strUserName
std::string m_strPassword
std::string m_strFileName
std::string m_strProtocol
std::string m_strFileType
std::string m_strOptions
std::string m_strProtocolOptions
CUrlOptions m_options
CUrlOptions m_protocolOptions
Constructor & Destructor Documentation
CURL() [1/2]
CURL::CURL (std::string strURL) inline explicit
References Parse().
CURL() [2/2]
CURL::CURL () default
~CURL()
CURL::~CURL (void) virtual default
Member Function Documentation
Decode()
std::string CURL::Decode (std::string_view strURLData) static
References Decode().
Referenced by Decode(), and Parse().
Encode()
std::string CURL::Encode (std::string_view strURLData) static
Todo:
Update it to "-_.~" after Gotham according to RFC3986
References Encode().
Referenced by Encode(), GetWithoutFilename(), GetWithoutUserDetails(), and Parse().
Get()
std::string CURL::Get () const
References Get(), GetWithoutOptions(), m_strDomain, m_strFileName, m_strHostName, m_strOptions, m_strPassword, m_strProtocol, m_strProtocolOptions, and m_strUserName.
Referenced by URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), XFILE::Browse(), XFILE::CTVOSFile::CacheStat(), CFileItem::CFileItem(), CFileItem::CFileItem(), XFILE::CPluginDirectory::CheckExists(), CGUIDialogNetworkSetup::ConstructPath(), XFILE::CAudioBookFileDirectory::ContainsFiles(), XFILE::CMusicFileDirectory::ContainsFiles(), XFILE::CPlaylistFileDirectory::ContainsFiles(), CWIN32Util::ConvertPathToWin32Form(), XFILE::CFile::Copy(), XFILE::CDirectoryFactory::Create(), KODI::PLAYLIST::CPlayListFactory::Create(), XFILE::CNFSDirectory::Create(), XFILE::CPosixDirectory::Create(), XFILE::CWinLibraryDirectory::Create(), XFILE::CWin32Directory::Create(), URIUtils::CreateArchivePath(), CDVDFactoryInputStream::CreateInputStream(), ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::CFile::Delete(), XFILE::CTVOSFile::Delete(), XFILE::Directorize(), dll_findfirst64i32(), dll_opendir(), CSubtitlesJob::DoWork(), CScriptRunner::ExecuteScript(), XFILE::CFile::Exists(), XFILE::CFileCache::Exists(), XFILE::CFTPDirectory::Exists(), XFILE::CImageFile::Exists(), XFILE::CMultiPathFile::Exists(), XFILE::CNFSDirectory::Exists(), XFILE::CPipeFile::Exists(), XFILE::CFileAndroidApp::Exists(), XFILE::CTVOSFile::Exists(), XFILE::CPosixDirectory::Exists(), XFILE::CWin32Directory::Exists(), XFILE::CDirectory::Exists(), XFILE::CShoutcastFile::ExtractTagInfo(), CMediaSource::FromNameAndPaths(), XFILE::CAddonsDirectory::GenerateAddonListing(), XFILE::GenerateGameListing(), XFILE::GenerateMainCategoryListing(), XFILE::GenerateTypeListing(), Get(), CScraperUrl::Get(), CFileItem::GetBlurayPath(), PVR::CPVRGUIDirectory::GetDirectory(), XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CAddonsDirectory::GetDirectory(), XFILE::CAudioBookFileDirectory::GetDirectory(), XFILE::CCDDADirectory::GetDirectory(), XFILE::CFTPDirectory::GetDirectory(), XFILE::CISO9660Directory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMusicFileDirectory::GetDirectory(), XFILE::CNFSDirectory::GetDirectory(), XFILE::CPlaylistFileDirectory::GetDirectory(), XFILE::CPluginDirectory::GetDirectory(), XFILE::CResourceDirectory::GetDirectory(), XFILE::CRSSDirectory::GetDirectory(), XFILE::CSpecialProtocolDirectory::GetDirectory(), XFILE::CStackDirectory::GetDirectory(), XFILE::CUDFDirectory::GetDirectory(), XFILE::CUPnPDirectory::GetDirectory(), XFILE::CZeroconfDirectory::GetDirectory(), XFILE::CAndroidAppDirectory::GetDirectory(), XFILE::CPosixDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), XFILE::CWinLibraryDirectory::GetDirectory(), XFILE::CWin32Directory::GetDirectory(), XFILE::CVirtualDirectory::GetDirectory(), XFILE::CDirectory::GetDirectory(), GetDirectoryFromTxtRecords(), ADDON::CScraper::GetEpisodeList(), CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput(), CDVDInputStream::GetFileName(), CDVDInputStreamFFmpeg::GetFileName(), XFILE::CUPnPDirectory::GetFriendlyName(), ADDON::CImageResource::GetFullPath(), KODI::GAME::CGameUtils::GetGameClients(), CPasswordManager::GetLookupPath(), XFILE::CWin32SMBDirectory::GetNetworkResources(), URIUtils::GetParentPath(), CGUIDialogMediaSource::GetPaths(), XFILE::CMultiPathDirectory::GetPaths(), URIUtils::GetRealPath(), XFILE::CBlurayDirectory::GetRoot(), XFILE::CAddonsDirectory::GetScriptsAndPlugins(), XFILE::CAddonsDirectory::GetSearchResults(), CRenderSystemGL::GetShaderPath(), CRenderSystemGLES::GetShaderPath(), XFILE::CWinLibraryDirectory::GetStoragePath(), KODI::ART::GetTBNFile(), XFILE::CBlurayDirectory::GetTitle(), CUtil::GetTitleFromPath(), XFILE::CWinLibraryFile::GetTokenFromList(), XFILE::CFileCDDA::GetTrackNum(), XFILE::CVideoDatabaseFile::GetType(), XFILE::CVideoDatabaseFile::GetVideoTag(), CUtil::GetVobSubSubFromIdx(), XFILE::CWinLibraryFile::IsInAccessList(), URIUtils::IsInternetStream(), CFileItem::IsURL(), XFILE::CFileCDDA::IsValidFile(), CPreflightHandler::MigrateUserdataXMLToNSUserDefaults(), XFILE::CXbtManager::NormalizePath(), CApplication::OnApplicationMessage(), CGUIWindowPictures::OnClick(), CGUIWindowFileManager::OnClick(), CGUIMediaWindow::OnFilterItems(), CApplication::OnMessage(), CXBMCApp::onNewIntent(), CGUIWindowVideoBase::OnSearchItemFound(), XFILE::CFile::Open(), XFILE::CFileCache::Open(), XFILE::CImageFile::Open(), XFILE::CMultiPathFile::Open(), XFILE::CPipeFile::Open(), XFILE::CFileAndroidApp::Open(), XFILE::CTVOSFile::Open(), CDVDDemuxFFmpeg::Open(), KODI::GAME::CGameClient::OpenFile(), XFILE::CFile::OpenForWrite(), XFILE::CPipeFile::OpenForWrite(), XFILE::CTVOSFile::OpenForWrite(), XFILE::CWinLibraryFile::OpenIntenal(), CSubtitlesJob::operator==(), operator==(), CMusicDbUrl::parse(), CVideoDbUrl::parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), CExternalPlayer::Process(), CPictureThumbLoader::ProcessFoldersAndArchives(), XFILE::CTVOSFile::Read(), KODI::PLAYLIST::CSmartPlaylist::readNameFromPath(), XFILE::CWin32SMBDirectory::RealCreate(), XFILE::CDirectory::Remove(), XFILE::CNFSDirectory::Remove(), XFILE::CPosixDirectory::Remove(), XFILE::CWinLibraryDirectory::Remove(), XFILE::CWin32Directory::Remove(), URIUtils::RemoveExtension(), CGUIMediaWindow::RemoveParameterFromPath(), XFILE::CDirectory::RemoveRecursive(), XFILE::CPosixDirectory::RemoveRecursive(), XFILE::CWin32Directory::RemoveRecursive(), URIUtils::RemoveSlashAtEnd(), XFILE::CFile::Rename(), XFILE::CTVOSFile::Rename(), URIUtils::ReplaceExtension(), XFILE::IDirectory::RequireAuthentication(), CPasswordManager::SaveAuthenticatedURL(), CFileItem::SetDynURL(), SetFile(), CGUIMediaWindow::SetHistoryForPath(), KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions(), CFileItem::SetURL(), CGUIDialogSimpleMenu::ShowPlaySelection(), XFILE::CFileCache::Stat(), XFILE::CImageFile::Stat(), XFILE::CMultiPathFile::Stat(), URIUtils::SubstitutePath(), TEST_F(), TEST_P(), CDbUrl::ToString(), IMAGE_FILES::CImageFileURL::ToString(), CLegacyPathTranslation::TranslateMusicDbPath(), CSpecialProtocol::TranslatePath(), XFILE::CMultiPathFile::TranslatePath(), XFILE::CPluginFile::TranslatePath(), XFILE::CVideoDatabaseFile::TranslatePath(), XFILE::CResourceFile::TranslatePath(), XFILE::CMusicDatabaseFile::TranslateUrl(), CLegacyPathTranslation::TranslateVideoDbPath(), CFilesystemInstaller::UnpackArchive(), CGUIMediaWindow::UpdateFilterPath(), URIUtils::UpdateUrlEncoding(), XFILE::UserInstalledAddons(), CWakeOnAccess::WakeUpHost(), XFILE::CTVOSFile::WantsFile(), and XFILE::CTVOSFile::Write().
GetDirectorySeparator()
char CURL::GetDirectorySeparator () const
References GetDirectorySeparator(), and m_strProtocol.
Referenced by GetDirectorySeparator(), SetFileName(), and URIUtils::SplitPath().
GetDomain()
const std::string & CURL::GetDomain () const inline
References m_strDomain.
Referenced by CPasswordManager::AuthenticateURL(), XFILE::CWin32SMBDirectory::ConnectAndAuthenticate(), ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::CDirectory::GetDirectory(), CPasswordManager::PromptToAuthenticateURL(), CGUIDialogNetworkSetup::SetPath(), and CSMB::URLEncode().
GetFileName()
const std::string & CURL::GetFileName () const inline
References m_strFileName.
Referenced by URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), CDbUrl::AppendPath(), XFILE::Browse(), XFILE::CNFSFile::Close(), CWIN32Util::ConvertPathToWin32Form(), XFILE::CFile::Copy(), ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::Directorize(), dll_findfirst64i32(), PVR::CPVRGUIDirectory::Exists(), XFILE::CCurlFile::Exists(), XFILE::CSMBFile::Exists(), DllLoaderContainer::FindModule(), XFILE::GenerateCategoryListing(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), PVR::CPVRGUIDirectory::GetDirectory(), XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CAddonsDirectory::GetDirectory(), XFILE::CBlurayDirectory::GetDirectory(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CFTPDirectory::GetDirectory(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CISO9660Directory::GetDirectory(), XFILE::CSourcesDirectory::GetDirectory(), XFILE::CUDFDirectory::GetDirectory(), XFILE::CAndroidAppDirectory::GetDirectory(), XFILE::CAPKDirectory::GetDirectory(), URIUtils::GetExtension(), URIUtils::GetExtension(), XFILE::CWinLibraryFile::GetFile(), CUtil::GetFileAndProtocol(), getFilename(), URIUtils::GetFileName(), URIUtils::GetFileName(), XFILE::CWinLibraryDirectory::GetFolder(), CFreeTypeLibrary::GetFont(), XFILE::CLibraryDirectory::GetNode(), URIUtils::GetParentPath(), XFILE::CXbtFile::GetReaderAndFile(), URIUtils::GetRealPath(), XFILE::CUPnPDirectory::GetResource(), XFILE::CBlurayDirectory::GetRoot(), XFILE::CAddonsDirectory::GetSearchResults(), CUtil::GetSkinThemes(), KODI::ART::GetTBNFile(), XFILE::CBlurayDirectory::GetUnderlyingCURL(), CZipManager::GetZipEntry(), CGUIWindowFileManager::GoParentFolder(), URIUtils::HasExtension(), URIUtils::HasExtension(), URIUtils::HasExtension(), URIUtils::HasSlashAtEnd(), UPNP::CMediaBrowser::InvokeUpdateObject(), URIUtils::IsInAPK(), URIUtils::IsInArchive(), URIUtils::IsInRAR(), URIUtils::IsInZIP(), XFILE::CPluginDirectory::IsMediaLibraryScanningAllowed(), XFILE::CWinLibraryFile::IsValid(), CDVDInputStreamBluray::Open(), XFILE::CISO9660File::Open(), XFILE::CNFSFile::Open(), XFILE::CUDFFile::Open(), XFILE::CAPKFile::Open(), XFILE::CSMBFile::Open(), XFILE::CNFSFile::OpenForWrite(), XFILE::CSMBFile::OpenForWrite(), XFILE::CWinLibraryFile::OpenIntenal(), CMusicDbUrl::parse(), CVideoDbUrl::parse(), CExecString::Parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), ParseItemSVT(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), prepareWin32SMBDirectoryName(), CExternalPlayer::Process(), XFILE::CWin32SMBDirectory::RealCreate(), XFILE::CWin32SMBDirectory::RealExists(), URIUtils::RemoveExtension(), URIUtils::RemoveSlashAtEnd(), URIUtils::ReplaceExtension(), CGUIDialogNetworkSetup::SetPath(), URIUtils::SplitPath(), CNfsConnection::splitUrlIntoExportAndPath(), XFILE::CCurlFile::Stat(), XFILE::CNFSFile::Stat(), XFILE::CXbtFile::Stat(), XFILE::CZipFile::Stat(), XFILE::CAPKFile::Stat(), XFILE::CWinLibraryFile::Stat(), PVR::CPVRGUIDirectory::SupportsWriteFileOperations(), CSpecialProtocol::TranslatePath(), XFILE::CBlurayFile::TranslatePath(), XFILE::CResourceFile::TranslatePath(), CSMB::URLEncode(), XFILE::UserInstalledAddons(), and XFILE::CNFSFile::Write().
GetFileNameWithoutPath()
std::string CURL::GetFileNameWithoutPath () const
References URIUtils::GetFileName(), GetFileNameWithoutPath(), IsProtocol(), m_strFileName, m_strHostName, and URIUtils::RemoveSlashAtEnd().
Referenced by ByFile(), XFILE::CWinLibraryDirectory::Create(), CFileOperationJob::CFileOperation::ExecuteOperation(), GetFileNameWithoutPath(), KODI::GAME::CGameUtils::HasGameExtension(), XFILE::CWinLibraryFile::OpenIntenal(), and XFILE::CTVOSFile::WantsFile().
GetFileType()
const std::string & CURL::GetFileType () const inline
References m_strFileType.
Referenced by CodecFactory::CreateCodec(), ImageFactory::CreateLoader(), CMime::GetMimeType(), CPlayerSelectionRule::GetPlayers(), CInputStreamAddon::Supports(), and XFILE::CTVOSFile::WantsFile().
GetHostName()
const std::string & CURL::GetHostName () const inline
References m_strHostName.
Referenced by AddHostsFromMediaSource(), XFILE::Browse(), UPNP::CUPnPServer::BuildSafeResourceUri(), CFileOperationJob::CanBeRenamed(), CFavouritesURL::CFavouritesURL(), CGUIViewStateFromItems::CGUIViewStateFromItems(), CHTTPImageTransformationHandler::CHTTPImageTransformationHandler(), IMAGE_FILES::CImageFileURL::CImageFileURL(), CVideoDatabase::CleanDatabase(), CNfsConnection::Connect(), XFILE::CWin32SMBDirectory::ConnectAndAuthenticate(), CWIN32Util::ConvertPathToWin32Form(), ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::CDAVFile::Execute(), XFILE::CCurlFile::Exists(), XFILE::CImageFile::Exists(), CVideoTagLoaderNFO::FindNFO(), CFileItem::GetBaseMoviePath(), CFileItem::GetBlurayPath(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), XFILE::CCurlFile::GetCookies(), XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CAddonsDirectory::GetDirectory(), XFILE::CBlurayDirectory::GetDirectory(), XFILE::CEventsDirectory::GetDirectory(), XFILE::CISO9660Directory::GetDirectory(), XFILE::CMusicSearchDirectory::GetDirectory(), XFILE::CNFSDirectory::GetDirectory(), XFILE::CUDFDirectory::GetDirectory(), XFILE::CAndroidAppDirectory::GetDirectory(), XFILE::CAPKDirectory::GetDirectory(), CGUIMediaWindow::GetDirectory(), KODI::ART::GetFolderThumb(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), CPasswordManager::GetLookupPath(), CUtil::GetMatchingSource(), CFileUtils::GetModificationDate(), XFILE::CWin32SMBDirectory::GetNetworkResources(), XFILE::CLibraryDirectory::GetNode(), URIUtils::GetParentPath(), URIUtils::GetRealPath(), CSMB::GetResolvedUrl(), XFILE::CUPnPDirectory::GetResource(), XFILE::CWinLibraryDirectory::GetRootFolder(), CPasswordManager::GetServerLookup(), CUtil::GetSkinThemes(), CUtil::GetTitleFromPath(), XFILE::CBlurayDirectory::GetUnderlyingCURL(), XFILE::CBlurayDirectory::GetUserPlaylists(), CUtil::GetVideoBasePathAndFileName(), CZipManager::GetZipEntry(), CZipManager::GetZipList(), UPNP::CMediaBrowser::InvokeUpdateObject(), URIUtils::IsDAV(), URIUtils::IsFTP(), URIUtils::IsHD(), URIUtils::IsHTTP(), URIUtils::IsInRAR(), URIUtils::IsInZIP(), XFILE::CPluginDirectory::IsMediaLibraryScanningAllowed(), URIUtils::IsNfs(), URIUtils::IsOnLAN(), URIUtils::IsRemote(), XFILE::CAddonsDirectory::IsRepoDirectory(), URIUtils::IsSmb(), XFILE::CWinLibraryDirectory::IsValid(), XBMCAddon::xbmcvfs::listdir(), XFILE::CXbtManager::NormalizePath(), CGUIMediaWindow::OnClick(), CGUIWindowSlideShow::OnLoadPic(), CDVDInputStreamBluray::Open(), XFILE::CCurlFile::Open(), XFILE::CISO9660File::Open(), XFILE::CUDFFile::Open(), XFILE::CZipFile::Open(), XFILE::CAPKFile::Open(), XFILE::CCurlFile::OpenForWrite(), CExecString::Parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), CApplication::PlayMedia(), prepareWin32SMBDirectoryName(), CExternalPlayer::Process(), CWakeOnAccess::QueueMACDiscoveryForAllRemotes(), XFILE::CWin32SMBDirectory::RealCreate(), XFILE::CWin32SMBDirectory::RealExists(), CZipManager::release(), CFileUtils::RemoteAccessAllowed(), URIUtils::RemoveSlashAtEnd(), CNfsConnection::resolveHost(), XFILE::CPluginDirectory::RunScriptWithParams(), XFILE::CCurlFile::Seek(), CGUIDialogNetworkSetup::SetPath(), CGUIWindowFileManager::ShowShareErrorMessage(), CGUIMediaWindow::ShowShareErrorMessage(), CNfsConnection::splitUrlIntoExportAndPath(), XFILE::CPluginDirectory::StartScript(), CNfsConnection::stat(), XFILE::CCurlFile::Stat(), XFILE::CXbtFile::Stat(), XFILE::CZipFile::Stat(), XFILE::CAPKFile::Stat(), XFILE::CBlurayFile::TranslatePath(), CTextureDatabase::UpdateTables(), URIUtils::UpdateUrlEncoding(), CSMB::URLEncode(), and CWakeOnAccess::WakeUpHost().
GetOption() [1/2]
std::string CURL::GetOption (const std::string & key) const
References GetOption(), and value.
GetOption() [2/2]
bool CURL::GetOption (const std::string & key, std::string & value) const
References CVariant::asString(), CUrlOptions::GetOption(), GetOption(), m_options, and value.
Referenced by KODI::PLAYLIST::CPlayListFactory::Create(), CGUIDialogSubtitles::Download(), PVR::CPVRGUIDirectory::GetChannelsDirectory(), PVR::UTILS::GetClientAndProviderFromPath(), GetOption(), GetOption(), PVR::CPVRGUIDirectory::GetRecordingsDirectory(), PVR::CPVRGUIDirectory::GetTimersDirectory(), KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::GetUrlOption(), PVR::UTILS::HasClientAndProvider(), CGUIMediaWindow::OnFilterItems(), CGUIDialogSubtitles::OnJobComplete(), CGUIWindowMusicNav::OnMessage(), CGUIWindowVideoNav::OnMessage(), CXBMCApp::onNewIntent(), and CGUIMediaWindow::UpdateFilterPath().
GetOptions() [1/2]
const std::string & CURL::GetOptions () const inline
References m_strOptions.
Referenced by ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::Directorize(), CScriptRunner::ExecuteScript(), CScraperUrl::Get(), GetOptions(), URIUtils::GetParentPath(), CGUIWindowMusicNav::ManageInfoProvider(), XFILE::CZipFile::Open(), CMusicDbUrl::parse(), CVideoDbUrl::parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions(), and CVideoDatabase::SplitPath().
GetOptions() [2/2]
void CURL::GetOptions (std::map< std::string, std::string > & options) const
References GetOptions(), CUrlOptions::GetOptions(), and m_options.
GetPassWord()
const std::string & CURL::GetPassWord () const inline
References m_strPassword.
Referenced by CPasswordManager::AuthenticateURL(), XFILE::CWin32SMBDirectory::ConnectAndAuthenticate(), CDVDFactoryInputStream::CreateInputStream(), ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::CDirectory::GetDirectory(), XFILE::CCurlFile::ParseAndCorrectUrl(), CGUIDialogNetworkSetup::SetPath(), and CSMB::URLEncode().
GetPort()
int CURL::GetPort () const inline
References m_iPort.
Referenced by ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::CCurlFile::ParseAndCorrectUrl(), CGUIDialogNetworkSetup::SetPath(), and CSMB::URLEncode().
GetProtocol()
const std::string & CURL::GetProtocol () const inline
References m_strProtocol.
Referenced by UPNP::BuildObject(), CFavouritesURL::CFavouritesURL(), CFileUtils::CheckFileAccessAllowed(), CWIN32Util::ConvertPathToWin32Form(), XFILE::CFile::Copy(), XFILE::CDirectoryFactory::Create(), XFILE::CFileFactory::CreateLoader(), ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::CWin32File::Delete(), XFILE::CDAVFile::Execute(), XFILE::CWin32File::Exists(), XFILE::CCurlFile::Exists(), XFILE::CShoutcastFile::ExtractTagInfo(), CGUIDialogContextMenu::GetContextButtons(), XFILE::CCurlFile::GetCookies(), CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput(), XFILE::CWinLibraryFile::GetFile(), CUtil::GetFileAndProtocol(), CFreeTypeLibrary::GetFont(), KODI::GAME::CGameUtils::GetGameClients(), CPasswordManager::GetLookupPath(), CPlayerSelectionRule::GetPlayers(), UPNP::GetProtocolInfo(), CUtil::GetQualifiedFilename(), CPasswordManager::GetServerLookup(), GetTranslatedProtocol(), URIUtils::HasParentInHostname(), URIUtils::IsHD(), URIUtils::IsHTTP(), URIUtils::IsInternetStream(), URIUtils::IsNetworkFilesystem(), URIUtils::IsStreamedFilesystem(), KODI::PLAYLIST::CPlayListXSPF::Load(), XFILE::CWin32File::Open(), XFILE::CCurlFile::Open(), XFILE::CShoutcastFile::Open(), KODI::GAME::CGameClient::OpenFile(), XFILE::CWin32File::OpenForWrite(), XFILE::CCurlFile::OpenForWrite(), CApplication::PlayMedia(), XFILE::CWin32File::Rename(), XFILE::CCurlFile::Seek(), XFILE::CWin32File::SetHidden(), CGUIDialogNetworkSetup::SetPath(), XFILE::CCurlFile::Stat(), XFILE::CWin32File::Stat(), CInputStreamAddon::Supports(), and CUtil::SupportsWriteFileOperations().
GetProtocolOption() [1/2]
std::string CURL::GetProtocolOption (const std::string & key) const
References GetProtocolOption(), and value.
GetProtocolOption() [2/2]
bool CURL::GetProtocolOption (const std::string & key, std::string & value) const
References CVariant::asString(), CUrlOptions::GetOption(), GetProtocolOption(), m_protocolOptions, and value.
Referenced by ADDON::CRepository::CRepository(), XFILE::CFTPDirectory::GetDirectory(), GetProtocolOption(), GetProtocolOption(), and XFILE::CCurlFile::ParseAndCorrectUrl().
GetProtocolOptions() [1/2]
const std::string & CURL::GetProtocolOptions () const inline
References m_strProtocolOptions.
Referenced by CDVDFactoryInputStream::CreateInputStream(), XFILE::CDAVDirectory::GetDirectory(), CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput(), GetProtocolOptions(), XFILE::CShoutcastFile::Open(), XFILE::CCurlFile::ParseAndCorrectUrl(), CMusicDatabase::SplitPath(), and CVideoDatabase::SplitPath().
GetProtocolOptions() [2/2]
void CURL::GetProtocolOptions (std::map< std::string, std::string > & options) const
References CUrlOptions::GetOptions(), GetProtocolOptions(), and m_protocolOptions.
GetRedacted() [1/2]
std::string CURL::GetRedacted () const
References GetRedacted(), and GetWithoutUserDetails().
Referenced by XFILE::CFile::Copy(), XFILE::CDirectory::Create(), XFILE::CDirectoryFactory::Create(), XFILE::CDAVDirectory::Create(), XFILE::CFileFactory::CreateLoader(), ADDON::CRepository::CRepository(), ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::CDAVFile::Delete(), XFILE::CCurlFile::Exists(), XFILE::CMultiPathDirectory::Exists(), XFILE::CDirectory::Exists(), XFILE::CCurlFile::GetContentType(), XFILE::CCurlFile::GetCookies(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CMultiPathDirectory::GetDirectory(), XFILE::CMusicSearchDirectory::GetDirectory(), XFILE::CDirectory::GetDirectory(), XFILE::CWinLibraryFile::GetFile(), XFILE::CWinLibraryDirectory::GetFolder(), XFILE::CCurlFile::GetHttpHeader(), XFILE::CCurlFile::GetMimeType(), GetRedacted(), GetRedacted(), CZipManager::GetZipList(), XFILE::CFileCache::Open(), XFILE::CSMBFile::Open(), XFILE::CWinLibraryFile::OpenIntenal(), XFILE::CCurlFile::ParseAndCorrectUrl(), KODI::PLAYLIST::CSmartPlaylist::readNameFromPath(), XFILE::CDirectory::Remove(), XFILE::CDAVDirectory::Remove(), XFILE::CDirectory::RemoveRecursive(), XFILE::CDAVFile::Rename(), XFILE::CCurlFile::Stat(), and CGUIDialogFileBrowser::Update().
GetRedacted() [2/2]
std::string CURL::GetRedacted (std::string path) static
References CURL, and GetRedacted().
GetShareName()
const std::string & CURL::GetShareName () const inline
References m_strShareName.
Referenced by CFileOperationJob::CanBeRenamed(), XFILE::CWin32SMBDirectory::ConnectAndAuthenticate(), ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CNFSDirectory::GetDirectory(), CPasswordManager::GetLookupPath(), XFILE::CWin32SMBDirectory::GetNetworkResources(), prepareWin32SMBDirectoryName(), XFILE::CWin32SMBDirectory::RealCreate(), XFILE::CWin32SMBDirectory::RealExists(), XFILE::CFile::ShouldUseStreamBuffer(), and XFILE::CResourceFile::TranslatePath().
GetTranslatedProtocol()
std::string CURL::GetTranslatedProtocol () const
References GetProtocol(), GetTranslatedProtocol(), and IsProtocol().
Referenced by GetTranslatedProtocol(), URIUtils::HasEncodedFilename(), URIUtils::IsHTTP(), Parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), and XFILE::CDAVFile::Rename().
GetUserName()
const std::string & CURL::GetUserName () const inline
References m_strUserName.
Referenced by CPasswordManager::AuthenticateURL(), XFILE::CWin32SMBDirectory::ConnectAndAuthenticate(), XFILE::CDirectory::Create(), CDVDFactoryInputStream::CreateInputStream(), ADDON::CVFSURLWrapper::CVFSURLWrapper(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), XFILE::CDirectory::GetDirectory(), CGUIDialogMediaSource::GetPaths(), XFILE::CFile::Open(), XFILE::CFileStream::Open(), NPT_XbmcFile::Open(), XFILE::CFile::OpenForWrite(), XFILE::CCurlFile::ParseAndCorrectUrl(), CPasswordManager::PromptToAuthenticateURL(), XFILE::CDirectory::Remove(), XFILE::CDirectory::RemoveRecursive(), XFILE::CFile::Rename(), CPasswordManager::SaveAuthenticatedURL(), XFILE::CFile::SetHidden(), CGUIDialogNetworkSetup::SetPath(), XFILE::CFile::Stat(), and CSMB::URLEncode().
GetWithoutFilename()
std::string CURL::GetWithoutFilename () const
References Encode(), GetWithoutFilename(), URIUtils::HasEncodedHostname(), HasPort(), m_iPort, m_strDomain, m_strHostName, m_strPassword, m_strProtocol, m_strUserName, and protectIPv6().
Referenced by XFILE::CDAVDirectory::GetDirectory(), GetWithoutFilename(), GetWithoutOptions(), XFILE::CFileCDDA::Open(), ParseItemSVT(), XFILE::CWinLibraryFile::Rename(), KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions(), CVideoDatabase::SplitPath(), and URIUtils::SplitPath().
GetWithoutOptions()
std::string CURL::GetWithoutOptions () const
References GetWithoutFilename(), GetWithoutOptions(), URIUtils::HasSlashAtEnd(), IsProtocol(), m_strFileName, m_strProtocol, and URIUtils::RemoveSlashAtEnd().
Referenced by CFileItemList::Add(), CFileItemList::Add(), CFileItemList::AddFront(), XFILE::CDirectoryCache::ClearDirectory(), XFILE::CDirectoryCache::ClearFile(), XFILE::CDirectoryCache::ClearSubPaths(), XFILE::CDirectoryCache::FileExists(), Get(), CGUIMediaWindow::GetAdvanceFilteredItems(), PVR::CPVRGUIDirectory::GetChannelsDirectory(), XFILE::CDirectoryCache::GetDirectory(), PVR::CPVRGUIDirectory::GetProvidersDirectory(), PVR::CPVRGUIDirectory::GetRecordingsDirectory(), PVR::CPVRGUIDirectory::GetTimersDirectory(), GetWithoutOptions(), XFILE::CMusicDatabaseDirectory::IsAllItem(), URIUtils::PathEquals(), CFileItemList::Remove(), CFileItemList::Remove(), PVR::CGUIWindowPVRBase::SetChannelGroupPath(), XFILE::CDirectoryCache::SetDirectory(), CFileItemList::SetFastLookup(), and CVideoDatabase::SplitPath().
GetWithoutUserDetails()
std::string CURL::GetWithoutUserDetails (bool redact = false) const
References XFILE::CStackDirectory::ConstructStackPath(), CURL, Encode(), XFILE::CStackDirectory::GetDirectory(), GetWithoutUserDetails(), URIUtils::HasEncodedHostname(), URIUtils::HasParentInHostname(), HasPort(), IsProtocol(), m_iPort, m_strDomain, m_strFileName, m_strHostName, m_strOptions, m_strPassword, m_strProtocol, m_strProtocolOptions, m_strUserName, protectIPv6(), CFileItem::SetPath(), and CFileItemList::Size().
Referenced by CVideoDatabase::CleanMediaType(), CGUIDialogFileBrowser::FrameMove(), XFILE::CMultiPathDirectory::GetDirectory(), JSONRPC::CFileOperations::GetDirectory(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CUtil::GetMatchingSource(), CGUIInfoManager::GetMultiInfoItemLabel(), CMediaManager::GetNetworkLocations(), GetRedacted(), JSONRPC::CFileOperations::GetRootDirectory(), ADDON::Interface_GUIDialogFileBrowser::GetVECShares(), GetWithoutUserDetails(), CGUIDialogFileBrowser::OnAddNetworkLocation(), CGUIDialogMediaSource::OnPath(), CGUIDialogMediaSource::OnPathBrowse(), CGUIDialogFileBrowser::OnPopupMenu(), CGUIWindowPictures::OnPrepareFileItems(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), CGUIDialogNetworkSetup::OnServerBrowse(), XFILE::CCurlFile::ParseAndCorrectUrl(), Prettify(), CPasswordManager::PromptToAuthenticateURL(), XFILE::CDAVFile::Rename(), CGUIDialogMediaSource::UpdateButtons(), CGUIWindowFileManager::UpdateButtons(), and CGUIMediaWindow::WaitForNetwork().
HasOption()
bool CURL::HasOption (const std::string & key) const
References HasOption(), CUrlOptions::HasOption(), and m_options.
Referenced by KODI::PLAYLIST::CPlayListFactory::Create(), CGUIMediaWindow::GetAdvanceFilteredItems(), PVR::CPVRGUIDirectory::GetChannelsDirectory(), URIUtils::GetParentPath(), PVR::CPVRGUIDirectory::GetRecordingsDirectory(), PVR::CPVRGUIDirectory::GetTimersDirectory(), CGUIMediaWindow::GoParentFolder(), HasOption(), CGUIMediaWindow::OnBack(), CGUIMediaWindow::OnFilterItems(), CGUIMediaWindow::RemoveParameterFromPath(), and CGUIMediaWindow::UpdateFilterPath().
HasPort()
bool CURL::HasPort () const inline
References m_iPort.
Referenced by GetWithoutFilename(), GetWithoutUserDetails(), and CSMB::URLEncode().
HasProtocolOption()
bool CURL::HasProtocolOption (const std::string & key) const
References CUrlOptions::HasOption(), HasProtocolOption(), and m_protocolOptions.
Referenced by ADDON::CRepository::CRepository(), HasProtocolOption(), and XFILE::CCurlFile::ParseAndCorrectUrl().
IsFileOnly()
bool CURL::IsFileOnly (const std::string & url) static
return true if there are no directories in the url.
References IsFileOnly().
Referenced by IsFileOnly().
IsFileType()
bool CURL::IsFileType (const char * type) const inline
Check whether a URL is a given filetype. Comparison is effectively case-insensitive as both the parameter and m_strFileType are lower-case.
Parameters
type a lower-case filetype, e.g. "mp3".
Returns
true if the url is of the given filetype, false otherwise.
References m_strFileType.
Referenced by XFILE::CFileDirectoryFactory::Create(), and CodecFactory::CreateCodecDemux().
IsFullPath()
bool CURL::IsFullPath (const std::string & url) static
return true if the url includes the full path
References IsFullPath().
Referenced by IsFullPath().
IsLocal()
bool CURL::IsLocal () const
References IsLocal(), IsLocalHost(), IsProtocol(), and m_strProtocol.
Referenced by dll_findfirst64i32(), dll_opendir(), CMediaSourceSettings::GetSource(), IsLocal(), and URIUtils::IsRemote().
IsLocalHost()
bool CURL::IsLocalHost () const
References CServiceBroker::GetNetwork(), IsLocalHost(), CNetworkBase::IsLocalHost(), and m_strHostName.
Referenced by IsLocal(), IsLocalHost(), and XFILE::CCurlFile::ParseAndCorrectUrl().
IsProtocol()
bool CURL::IsProtocol (const char * type) const inline
Check whether a URL is a given URL scheme. Comparison is case-insensitive as per RFC1738.
Parameters
type a lower-case scheme name, e.g. "smb".
Returns
true if the url is of the given scheme, false otherwise.
References IsProtocolEqual(), and m_strProtocol.
Referenced by AddHostsFromMediaSource(), UPNP::CUPnPServer::BuildSafeResourceUri(), XFILE::CWin32SMBDirectory::ConnectAndAuthenticate(), CGUIDialogNetworkSetup::ConstructPath(), CWIN32Util::ConvertPathToWin32Form(), XFILE::CDirectoryFactory::Create(), XFILE::CFileDirectoryFactory::Create(), CodecFactory::CreateCodecDemux(), XFILE::CFileFactory::CreateLoader(), ADDON::CRepository::CRepository(), XFILE::CWin32File::Delete(), XFILE::CWin32SMBFile::Delete(), PVR::CPVRGUIDirectory::Exists(), XFILE::CWin32File::Exists(), XFILE::CWin32SMBFile::Exists(), XFILE::CCurlFile::Exists(), XFILE::CFavouritesDirectory::Exists(), MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), CFileItem::GetBlurayPath(), XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CISO9660Directory::GetDirectory(), XFILE::CPlaylistDirectory::GetDirectory(), XFILE::CUDFDirectory::GetDirectory(), XFILE::CXbtDirectory::GetDirectory(), XFILE::CZeroconfDirectory::GetDirectory(), XFILE::CZipDirectory::GetDirectory(), CGUIMediaWindow::GetDirectory(), CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput(), XFILE::CWinLibraryFile::GetFile(), CDVDInputStreamFFmpeg::GetFileName(), GetFileNameWithoutPath(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), CPasswordManager::GetLookupPath(), CUtil::GetMatchingSource(), CMime::GetMimeType(), URIUtils::GetParentPath(), XFILE::CUPnPDirectory::GetResource(), XFILE::CWinLibraryDirectory::GetRootFolder(), CUtil::GetSkinThemes(), CMusicDatabase::GetSongByFileName(), CMusicDatabase::GetSongIDFromPath(), CMediaSourceSettings::GetSource(), CUtil::GetTitleFromPath(), GetTranslatedProtocol(), XFILE::CBlurayDirectory::GetUnderlyingCURL(), CUtil::GetVideoBasePathAndFileName(), CGUIViewState::GetViewState(), GetWithoutOptions(), GetWithoutUserDetails(), CGUIWindowFileManager::GoParentFolder(), URIUtils::HasEncodedHostname(), URIUtils::HasParentInHostname(), URIUtils::IsAddonsPath(), URIUtils::IsHD(), URIUtils::IsInAPK(), URIUtils::IsInArchive(), URIUtils::IsInRAR(), URIUtils::IsInternetStream(), URIUtils::IsInZIP(), URIUtils::IsLibraryFolder(), IsLocal(), URIUtils::IsNetworkFilesystem(), URIUtils::IsPlugin(), XFILE::CAddonsDirectory::IsRepoDirectory(), URIUtils::IsScript(), URIUtils::IsSourcesPath(), URIUtils::IsStreamedFilesystem(), CPasswordManager::IsURLSupported(), XFILE::CWinLibraryDirectory::IsValid(), CTexture::LoadFromFile(), CTexture::LoadFromFileInternal(), CGUIWindowMusicPlaylistEditor::LoadPlaylist(), XFILE::CXbtManager::NormalizePath(), CGUIDialogMusicInfo::OnGetArt(), CApplication::OnMessage(), CXBMCApp::onNewIntent(), XFILE::CFile::Open(), XFILE::CWin32File::Open(), XFILE::CWin32SMBFile::Open(), XFILE::CCurlFile::Open(), CDVDDemuxFFmpeg::Open(), XFILE::CWin32File::OpenForWrite(), XFILE::CWin32SMBFile::OpenForWrite(), CMusicDbUrl::parse(), CVideoDbUrl::parse(), Parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), prepareWin32SMBDirectoryName(), CExternalPlayer::Process(), CRssReader::Process(), CPasswordManager::PromptToAuthenticateURL(), XFILE::CWin32SMBDirectory::RealCreate(), XFILE::CWin32SMBDirectory::RealExists(), XFILE::CWin32SMBDirectory::Remove(), XFILE::CWin32File::Rename(), XFILE::CWin32SMBFile::Rename(), XFILE::CWin32File::SetHidden(), XFILE::CWin32SMBFile::SetHidden(), CGUIWindowFileManager::ShowShareErrorMessage(), CGUIMediaWindow::ShowShareErrorMessage(), CGUIWindowVideoBase::StackingAvailable(), XFILE::CCurlFile::Stat(), XFILE::CWin32File::Stat(), XFILE::CWin32SMBFile::Stat(), CSpecialProtocol::TranslatePath(), XFILE::CBlurayFile::TranslatePath(), XFILE::CResourceFile::TranslatePath(), CSpecialProtocol::TranslatePath(), and CWakeOnAccess::WakeUpHost().
IsProtocolEqual()
bool CURL::IsProtocolEqual (const std::string & protocol, const char * type) static
Check whether a URL protocol is a given URL scheme. Both parameters MUST be lower-case. Typically this would be called using the result of TranslateProtocol() which enforces this for protocol.
Parameters
protocol a lower-case scheme name, e.g. "ftp"
type a lower-case scheme name, e.g. "smb".
Returns
true if the url is of the given scheme, false otherwise.
References IsProtocolEqual().
Referenced by IsProtocol(), IsProtocolEqual(), and Parse().
operator==()
bool CURL::operator== (const std::string & url) const inline
References Get().
Parse()
void CURL::Parse (std::string strURL)
Todo:
fix all Addon paths
References __stat64, Decode(), Encode(), GetTranslatedProtocol(), URIUtils::HasEncodedHostname(), IsProtocol(), IsProtocolEqual(), m_iPort, m_strDomain, m_strFileName, m_strHostName, m_strPassword, m_strUserName, Parse(), Reset(), S_IFDIR, S_ISDIR, SetFileName(), SetHostName(), SetOptions(), SetProtocol(), SetProtocolOptions(), XFILE::CFile::Stat(), and CUtil::ValidatePath().
Referenced by XFILE::CFile::CURLCreate(), CDbUrl::FromString(), XFILE::CCurlFile::IsInternet(), CTexture::LoadFromFileInternal(), Parse(), and URIUtils::UpdateUrlEncoding().
RemoveOption()
void CURL::RemoveOption (const std::string & key)
References CUrlOptions::GetOptionsString(), m_options, RemoveOption(), CUrlOptions::RemoveOption(), and SetOptions().
Referenced by CGUIWindowMusicNav::ManageInfoProvider(), CGUIMediaWindow::OnFilterItems(), RemoveOption(), and CGUIMediaWindow::RemoveParameterFromPath().
RemoveProtocolOption()
void CURL::RemoveProtocolOption (const std::string & key)
References CUrlOptions::GetOptionsString(), m_protocolOptions, m_strProtocolOptions, CUrlOptions::RemoveOption(), and RemoveProtocolOption().
Referenced by XFILE::CFTPDirectory::GetDirectory(), and RemoveProtocolOption().
Reset()
void CURL::Reset ()
References CUrlOptions::Clear(), m_iPort, m_options, m_protocolOptions, m_strDomain, m_strFileName, m_strFileType, m_strHostName, m_strOptions, m_strPassword, m_strProtocol, m_strProtocolOptions, m_strShareName, m_strUserName, and Reset().
Referenced by XFILE::CTVOSFile::Close(), XFILE::CISO9660Directory::GetDirectory(), XFILE::CUDFDirectory::GetDirectory(), XFILE::CNFSFile::Open(), XFILE::CNFSFile::OpenForWrite(), XFILE::CWin32SMBDirectory::RealExists(), CDbUrl::Reset(), Reset(), and XFILE::CNFSDirectory::ResolveSymlink().
SetDomain()
void CURL::SetDomain (std::string strDomain) inline
References m_strDomain.
Referenced by CPasswordManager::AuthenticateURL(), CGUIDialogNetworkSetup::ConstructPath(), XFILE::CDirectory::GetDirectory(), CGUIDialogMediaSource::GetPaths(), and CPasswordManager::PromptToAuthenticateURL().
SetFileName()
void CURL::SetFileName (std::string strFileName)
References GetDirectorySeparator(), m_strFileName, m_strFileType, m_strShareName, and SetFileName().
Referenced by URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), CDbUrl::AppendPath(), CGUIDialogNetworkSetup::ConstructPath(), URIUtils::CreateArchivePath(), CDVDFactoryInputStream::CreateInputStream(), XFILE::Directorize(), dll_findfirst64i32(), XFILE::CAddonsDirectory::GenerateAddonListing(), XFILE::GenerateGameListing(), XFILE::GenerateTypeListing(), XFILE::CFTPDirectory::GetDirectory(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CXbtDirectory::GetDirectory(), XFILE::CZeroconfDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), URIUtils::GetParentPath(), URIUtils::GetRealPath(), XFILE::CBlurayDirectory::GetRoot(), XFILE::CAddonsDirectory::GetSearchResults(), KODI::ART::GetTBNFile(), XFILE::CBlurayDirectory::GetTitle(), Parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), URIUtils::RemoveExtension(), URIUtils::RemoveSlashAtEnd(), URIUtils::ReplaceExtension(), XFILE::CNFSDirectory::ResolveSymlink(), CDACP::SendCmd(), SetFile(), SetFileName(), CGUIDialogSimpleMenu::ShowPlaySelection(), and XFILE::UserInstalledAddons().
SetHostName()
void CURL::SetHostName (std::string strHostName) inline
References m_strHostName.
Referenced by CDACP::CDACP(), CGUIDialogNetworkSetup::ConstructPath(), URIUtils::CreateArchivePath(), CDVDFactoryInputStream::CreateInputStream(), XFILE::CISO9660Directory::GetDirectory(), XFILE::CUDFDirectory::GetDirectory(), XFILE::CZeroconfDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), URIUtils::GetParentPath(), URIUtils::GetRealPath(), CSMB::GetResolvedUrl(), XFILE::CWinLibraryDirectory::GetStoragePath(), Parse(), XFILE::CWin32SMBDirectory::RealExists(), XFILE::CNFSDirectory::ResolveSymlink(), SetFile(), CGUIDialogSimpleMenu::ShowPlaySelection(), IMAGE_FILES::CImageFileURL::ToString(), and URIUtils::UpdateUrlEncoding().
SetOption()
void CURL::SetOption (const std::string & key, const std::string & value)
References CUrlOptions::AddOption(), CUrlOptions::GetOptionsString(), m_options, SetOption(), SetOptions(), and value.
Referenced by XFILE::CPluginDirectory::CheckExists(), XFILE::CFile::CURLAddOption(), CGUIDialogSubtitles::Download(), CVideoTagLoaderPlugin::Load(), CGUIMediaWindow::OnFilterItems(), CGUIDialogSubtitles::Search(), SetOption(), IMAGE_FILES::CImageFileURL::ToString(), and CGUIMediaWindow::UpdateFilterPath().
SetOptions()
void CURL::SetOptions (std::string strOptions)
References CUrlOptions::AddOptions(), CUrlOptions::Clear(), CLog::Log(), LOGWARNING, m_options, m_strOptions, and SetOptions().
Referenced by XFILE::CFile::Copy(), XFILE::Directorize(), CScriptRunner::ExecuteScript(), CScraperUrl::Get(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CXbtDirectory::GetDirectory(), CUtil::GetMatchingSource(), URIUtils::GetParentPath(), XFILE::CXbtFile::GetReader(), XFILE::CXbtFile::GetReaderAndFile(), XFILE::CAddonsDirectory::GetScriptsAndPlugins(), CGUIWindowVideoBase::OnSearchItemFound(), XFILE::CFile::Open(), XFILE::CXbtFile::Open(), XFILE::CZipFile::Open(), Parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), RemoveOption(), CGUIMediaWindow::SetHistoryForPath(), SetOption(), SetOptions(), KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions(), and CDbUrl::updateOptions().
SetPassword()
void CURL::SetPassword (std::string strPassword) inline
References m_strPassword.
Referenced by CPasswordManager::AuthenticateURL(), CGUIDialogNetworkSetup::ConstructPath(), CDVDFactoryInputStream::CreateInputStream(), XFILE::CFile::CURLAddOption(), XFILE::CDirectory::GetDirectory(), GetDirectoryFromTxtRecords(), CGUIDialogMediaSource::GetPaths(), CPasswordManager::PromptToAuthenticateURL(), and SetFile().
SetPort()
void CURL::SetPort (int port) inline
References m_iPort.
Referenced by CDACP::CDACP(), CGUIDialogNetworkSetup::ConstructPath(), XFILE::CZeroconfDirectory::GetDirectory(), and XFILE::CNFSDirectory::ResolveSymlink().
SetProtocol()
void CURL::SetProtocol (std::string strProtocol)
References m_strProtocol, and SetProtocol().
Referenced by CDACP::CDACP(), CGUIDialogNetworkSetup::ConstructPath(), URIUtils::CreateArchivePath(), XFILE::CISO9660Directory::GetDirectory(), XFILE::CUDFDirectory::GetDirectory(), XFILE::CZeroconfDirectory::GetDirectory(), XFILE::CWinLibraryDirectory::GetStoragePath(), XFILE::CShoutcastFile::Open(), CDVDDemuxFFmpeg::Open(), KODI::GAME::CGameClient::OpenFile(), Parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), XFILE::CWin32SMBDirectory::RealExists(), XFILE::CDAVFile::Rename(), XFILE::CNFSDirectory::ResolveSymlink(), SetFile(), SetProtocol(), and IMAGE_FILES::CImageFileURL::ToString().
SetProtocolOption()
void CURL::SetProtocolOption (const std::string & key, const std::string & value)
References CUrlOptions::AddOption(), CUrlOptions::GetOptionsString(), m_protocolOptions, m_strProtocolOptions, SetProtocolOption(), and value.
Referenced by CDACP::CDACP(), XFILE::CFile::CURLAddOption(), XFILE::CFTPDirectory::GetDirectory(), ADDON::CRepository::ResolvePathAndHash(), and SetProtocolOption().
SetProtocolOptions()
void CURL::SetProtocolOptions (std::string strOptions)
References CUrlOptions::AddOptions(), CUrlOptions::Clear(), m_protocolOptions, m_strProtocolOptions, and SetProtocolOptions().
Referenced by CDVDFactoryInputStream::CreateInputStream(), CDVDInputStream::GetFileName(), CUtil::GetMatchingSource(), XFILE::CShoutcastFile::Open(), CDVDDemuxFFmpeg::Open(), Parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), and SetProtocolOptions().
SetUserName()
void CURL::SetUserName (std::string strUserName) inline
References m_strUserName.
Referenced by CPasswordManager::AuthenticateURL(), CGUIDialogNetworkSetup::ConstructPath(), URIUtils::CreateArchivePath(), CDVDFactoryInputStream::CreateInputStream(), XFILE::CFile::CURLAddOption(), XFILE::CDirectory::GetDirectory(), GetDirectoryFromTxtRecords(), CGUIDialogMediaSource::GetPaths(), CPasswordManager::PromptToAuthenticateURL(), and IMAGE_FILES::CImageFileURL::ToString().
Member Data Documentation
m_iPort
int CURL::m_iPort = 0 protected
Referenced by GetPort(), GetWithoutFilename(), GetWithoutUserDetails(), HasPort(), Parse(), Reset(), and SetPort().
m_options
CUrlOptions CURL::m_options protected
Referenced by GetOption(), GetOptions(), HasOption(), RemoveOption(), Reset(), SetOption(), and SetOptions().
m_protocolOptions
CUrlOptions CURL::m_protocolOptions protected
Referenced by GetProtocolOption(), GetProtocolOptions(), HasProtocolOption(), RemoveProtocolOption(), Reset(), SetProtocolOption(), and SetProtocolOptions().
m_strDomain
std::string CURL::m_strDomain protected
Referenced by Get(), GetDomain(), GetWithoutFilename(), GetWithoutUserDetails(), Parse(), Reset(), and SetDomain().
m_strFileName
std::string CURL::m_strFileName protected
Referenced by Get(), GetFileName(), GetFileNameWithoutPath(), GetWithoutOptions(), GetWithoutUserDetails(), Parse(), Reset(), and SetFileName().
m_strFileType
std::string CURL::m_strFileType protected
Referenced by GetFileType(), IsFileType(), Reset(), and SetFileName().
m_strHostName
std::string CURL::m_strHostName protected
Referenced by Get(), GetFileNameWithoutPath(), GetHostName(), GetWithoutFilename(), GetWithoutUserDetails(), IsLocalHost(), Parse(), Reset(), and SetHostName().
m_strOptions
std::string CURL::m_strOptions protected
Referenced by Get(), GetOptions(), GetWithoutUserDetails(), Reset(), and SetOptions().
m_strPassword
std::string CURL::m_strPassword protected
Referenced by Get(), GetPassWord(), GetWithoutFilename(), GetWithoutUserDetails(), Parse(), Reset(), and SetPassword().
m_strProtocol
std::string CURL::m_strProtocol protected
Referenced by Get(), GetDirectorySeparator(), GetProtocol(), GetWithoutFilename(), GetWithoutOptions(), GetWithoutUserDetails(), IsLocal(), IsProtocol(), Reset(), and SetProtocol().
m_strProtocolOptions
std::string CURL::m_strProtocolOptions protected
Referenced by Get(), GetProtocolOptions(), GetWithoutUserDetails(), RemoveProtocolOption(), Reset(), SetProtocolOption(), and SetProtocolOptions().
m_strShareName
std::string CURL::m_strShareName protected
Referenced by GetShareName(), Reset(), and SetFileName().
m_strUserName
std::string CURL::m_strUserName protected
Referenced by Get(), GetUserName(), GetWithoutFilename(), GetWithoutUserDetails(), Parse(), Reset(), and SetUserName().
The documentation for this class was generated from the following files:
URL.h
URL.cpp