Kodi Documentation: JSONRPC::CPlayerOperations Class Reference
JSONRPC::CPlayerOperations Class Reference
#include <PlayerOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetActivePlayers (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetPlayers (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetProperties (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetItem (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS PlayPause (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Stop (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetAudioDelay (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetAudioDelay (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetSpeed (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetTempo (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Seek (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Move (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Zoom (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetViewMode (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetViewMode (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Rotate (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Open (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GoTo (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetShuffle (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetRepeat (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetPartymode (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetAudioStream (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS AddSubtitle (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetSubtitle (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetVideoStream (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Static Private Member Functions
static int GetActivePlayers ()
static PlayerType GetPlayer (const CVariant &player)
static KODI::PLAYLIST::Id GetPlaylist (PlayerType player)
static JSONRPC_STATUS StartSlideshow (const std::string &path, bool recursive, bool random, const std::string &firstPicturePath="")
static void SendSlideshowAction (int actionID)
static JSONRPC_STATUS GetPropertyValue (PlayerType player, const std::string &property, CVariant &result)
static KODI::PLAYLIST::RepeatState ParseRepeatState (const CVariant &repeat)
static double ParseTimeInSeconds (const CVariant &time)
static bool IsPVRChannel ()
static std::shared_ptr< PVR::CPVREpgInfoTag > GetCurrentEpg ()
Static Private Member Functions inherited from JSONRPC::CFileItemHandler
static void FillDetails (const ISerializable *info, const std::shared_ptr< CFileItem > &item, std::set< std::string > &fields, CVariant &result, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, bool sortLimit=true)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, int size, bool sortLimit=true)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const CVariant &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const std::set< std::string > &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
Static Private Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Member Function Documentation
AddSubtitle()
JSONRPC_STATUS CPlayerOperations::AddSubtitle (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asString(), JSONRPC::FailedToExecute, CServiceBroker::GetAppComponents(), GetPlayer(), and JSONRPC::Video.
GetActivePlayers() [1/2]
int CPlayerOperations::GetActivePlayers () static private
References JSONRPC::Audio, JSONRPC::External, CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), JSONRPC::Picture, PVR::CPVRManager::PlaybackState(), JSONRPC::Remote, JSONRPC::Video, and WINDOW_SLIDESHOW.
Referenced by GetActivePlayers().
GetActivePlayers() [2/2]
JSONRPC_STATUS CPlayerOperations::GetActivePlayers (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::append(), JSONRPC::Audio, JSONRPC::External, GetActivePlayers(), GetPlaylist(), JSONRPC::OK, JSONRPC::Picture, JSONRPC::Remote, CVariant::VariantTypeArray, CVariant::VariantTypeObject, and JSONRPC::Video.
GetAudioDelay()
JSONRPC_STATUS CPlayerOperations::GetAudioDelay (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CServiceBroker::GetAppComponents(), and JSONRPC::OK.
GetCurrentEpg()
std::shared_ptr< CPVREpgInfoTag > CPlayerOperations::GetCurrentEpg () static private
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::PlaybackState().
Referenced by GetPropertyValue().
GetItem()
JSONRPC_STATUS CPlayerOperations::GetItem (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
Todo:
remove this once there is no route to playback that updates
Todo:
remove this once there is no route to playback that updates
References CFileItemList::Add(), JSONRPC::Audio, CDatabase::Close(), CSlideShowDelegator::CurrentSlide(), CVariant::end_array(), EPISODES, JSONRPC::FailedToExecute, JSONRPC::CAudioLibrary::FillFileItem(), JSONRPC::CVideoLibrary::FillFileItem(), g_application, JSONRPC::CAudioLibrary::GetAdditionalSongDetails(), CGUIInfoManager::GetCurrentMovieTag(), CGUIInfoManager::GetCurrentSongTag(), CVideoDatabase::GetEpisodeInfo(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMusicVideoInfo(), CVideoInfoTag::GetPath(), GetPlayer(), CSlideShowDelegator::GetSlideShowContents(), CServiceBroker::GetSlideShowDelegator(), JSONRPC::CFileItemHandler::HandleFileItem(), KODI::MUSIC::IsMusicDb(), IsPVRChannel(), MOVIE_SETS, MOVIES, MUSICVIDEOS, JSONRPC::None, JSONRPC::OK, CVideoDatabase::Open(), JSONRPC::Picture, TVSHOWS, and JSONRPC::Video.
GetPlayer()
PlayerType CPlayerOperations::GetPlayer (const CVariant & player) static private
References CVariant::asInteger32(), JSONRPC::Audio, GetPlaylist(), JSONRPC::None, JSONRPC::Picture, and JSONRPC::Video.
Referenced by AddSubtitle(), GetItem(), GetProperties(), GoTo(), Move(), PlayPause(), Rotate(), Seek(), SetAudioDelay(), SetAudioStream(), SetPartymode(), SetRepeat(), SetShuffle(), SetSpeed(), SetSubtitle(), SetTempo(), SetVideoStream(), Stop(), and Zoom().
GetPlayers()
JSONRPC_STATUS CPlayerOperations::GetPlayers (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), CServiceBroker::GetPlayerCoreFactory(), CPlayerCoreFactory::GetPlayers(), CPlayerCoreFactory::GetPlayerType(), JSONRPC::OK, CPlayerCoreFactory::PlaysAudio(), CPlayerCoreFactory::PlaysVideo(), CVariant::push_back(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
GetPlaylist()
PLAYLIST::Id CPlayerOperations::GetPlaylist (PlayerType player) static private
References JSONRPC::Audio, CServiceBroker::GetAppComponents(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CServiceBroker::GetPlaylistPlayer(), CApplicationPlayer::GetPreferredPlaylist(), JSONRPC::Picture, and JSONRPC::Video.
Referenced by GetActivePlayers(), GetPlayer(), GetPropertyValue(), SetRepeat(), and SetShuffle().
GetProperties()
JSONRPC_STATUS CPlayerOperations::GetProperties (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), GetPlayer(), GetPropertyValue(), index(), JSONRPC::OK, CVariant::size(), and CVariant::VariantTypeObject.
GetPropertyValue()
JSONRPC_STATUS CPlayerOperations::GetPropertyValue (PlayerType player, const std::string & property, CVariant & result) static private
References CVariant::append(), JSONRPC::Audio, CSlideShowDelegator::CurrentSlide(), JSONRPC::FailedToExecute, g_application, g_partyModeManager, CServiceBroker::GetAppComponents(), GetCurrentEpg(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CSlideShowDelegator::GetDirection(), GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetSlideShowDelegator(), CApplicationPlayer::GetVideoStream(), CApplicationPlayer::GetVideoStreamCount(), index(), JSONRPC::InvalidParams, CPartyModeManager::IsEnabled(), CSlideShowDelegator::IsPaused(), CSlideShowDelegator::IsPlaying(), IsPVRChannel(), CSlideShowDelegator::IsShuffled(), KODI::PLAYLIST::CPlayListPlayer::IsShuffled(), JSONRPC::CJSONUtils::MillisecondsToTimeObject(), JSONRPC::None, CSlideShowDelegator::NumSlides(), JSONRPC::OK, JSONRPC::Picture, CVariant::VariantTypeArray, CVariant::VariantTypeNull, CVariant::VariantTypeObject, and JSONRPC::Video.
Referenced by GetProperties(), and Seek().
GetViewMode()
JSONRPC_STATUS CPlayerOperations::GetViewMode (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CServiceBroker::GetAppComponents(), CDisplaySettings::GetInstance(), CDisplaySettings::GetPixelRatio(), GetStringFromViewMode(), CDisplaySettings::GetVerticalShift(), CApplicationPlayer::GetVideoSettings(), CDisplaySettings::GetZoomAmount(), CDisplaySettings::IsNonLinearStretched(), CVideoSettings::m_ViewMode, and JSONRPC::OK.
GoTo()
JSONRPC_STATUS CPlayerOperations::GoTo (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, ACTION_CHANNEL_SWITCH, ACTION_NEXT_ITEM, ACTION_NEXT_PICTURE, ACTION_PREV_ITEM, ACTION_PREV_PICTURE, CVariant::asInteger(), CVariant::asString(), JSONRPC::Audio, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), GetPlayer(), JSONRPC::InvalidParams, CVariant::isInteger(), IsPVRChannel(), CVariant::isString(), JSONRPC::None, JSONRPC::Picture, SendSlideshowAction(), TMSG_GUI_ACTION, TMSG_PLAYLISTPLAYER_PLAY, JSONRPC::Video, and WINDOW_INVALID.
IsPVRChannel()
bool CPlayerOperations::IsPVRChannel () static private
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::PlaybackState().
Referenced by GetItem(), GetPropertyValue(), GoTo(), SetPartymode(), SetRepeat(), and SetShuffle().
Move()
JSONRPC_STATUS CPlayerOperations::Move (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NEXT_ITEM, ACTION_PREV_ITEM, CVariant::asString(), JSONRPC::Audio, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), GetPlayer(), JSONRPC::InvalidParams, JSONRPC::None, JSONRPC::Picture, SendSlideshowAction(), TMSG_GUI_ACTION, JSONRPC::Video, and WINDOW_INVALID.
Open()
JSONRPC_STATUS CPlayerOperations::Open (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
Todo:
: This should be a delegator method instead of going via GUI! look into triggering stop from Reset() itself!
References JSONRPC::ACK, ACTION_STOP, CSlideShowDelegator::Add(), CVariant::asBoolean(), CVariant::asInteger32(), CVariant::asString(), PVR::CPVRManager::ChannelGroups(), CUtil::ConvertSecsToMilliSecs(), CPartyModeManager::Disable(), PVR::CPVRManager::EpgContainer(), JSONRPC::FailedToExecute, JSONRPC::CFileItemHandler::FillFileItemList(), g_partyModeManager, PVR::CPVRManager::Get(), CFileItemList::Get(), CServiceBroker::GetAppMessenger(), CFileItem::GetPath(), CServiceBroker::GetPlayerCoreFactory(), CPlayerCoreFactory::GetPlayers(), CPlayerCoreFactory::GetPlayerType(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetPVRManager(), CSlideShowDelegator::GetSlideShowContents(), CServiceBroker::GetSlideShowDelegator(), PVR::CPVREpgContainer::GetTagByDatabaseId(), index(), JSONRPC::InvalidParams, CVariant::isBoolean(), CVariant::isDouble(), CPartyModeManager::IsEnabled(), CVariant::isNull(), CVariant::isObject(), URIUtils::IsPVRChannel(), URIUtils::IsPVRRecording(), CVariant::isString(), ParseRepeatState(), ParseTimeInSeconds(), PVR::CPVRManager::Recordings(), CSlideShowDelegator::Reset(), SendSlideshowAction(), CGUIListItem::SetProperty(), KODI::PLAYLIST::CPlayListPlayer::SetRepeat(), KODI::PLAYLIST::CPlayListPlayer::SetShuffle(), CFileItemList::Size(), slideshow, STARTOFFSET_RESUME, StartSlideshow(), TMSG_EXECUTE_BUILT_IN, and TMSG_MEDIA_PLAY.
ParseRepeatState()
PLAYLIST::RepeatState CPlayerOperations::ParseRepeatState (const CVariant & repeat) static private
References CVariant::asString().
Referenced by Open(), and SetRepeat().
ParseTimeInSeconds()
double CPlayerOperations::ParseTimeInSeconds (const CVariant & time) static private
Referenced by Open(), and Seek().
PlayPause()
JSONRPC_STATUS CPlayerOperations::PlayPause (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_PAUSE, CVariant::asBoolean(), JSONRPC::Audio, CBuiltins::Execute(), JSONRPC::FailedToExecute, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CSlideShowDelegator::GetDirection(), CBuiltins::GetInstance(), GetPlayer(), CServiceBroker::GetSlideShowDelegator(), CVariant::isBoolean(), CSlideShowDelegator::IsPaused(), CSlideShowDelegator::IsPlaying(), CVariant::isString(), JSONRPC::None, JSONRPC::OK, JSONRPC::Picture, SendSlideshowAction(), TMSG_MEDIA_PAUSE, and JSONRPC::Video.
Rotate()
JSONRPC_STATUS CPlayerOperations::Rotate (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, ACTION_ROTATE_PICTURE_CCW, ACTION_ROTATE_PICTURE_CW, JSONRPC::Audio, JSONRPC::FailedToExecute, GetPlayer(), JSONRPC::None, JSONRPC::Picture, SendSlideshowAction(), and JSONRPC::Video.
Seek()
JSONRPC_STATUS CPlayerOperations::Seek (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), JSONRPC::Audio, CBuiltins::Execute(), JSONRPC::FailedToExecute, g_application, CServiceBroker::GetAppComponents(), CBuiltins::GetInstance(), GetPlayer(), GetPropertyValue(), JSONRPC::InvalidParams, JSONRPC::None, JSONRPC::OK, ParseTimeInSeconds(), JSONRPC::Picture, value, and JSONRPC::Video.
SendSlideshowAction()
void CPlayerOperations::SendSlideshowAction (int actionID) static private
References CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_SLIDESHOW.
Referenced by GoTo(), Move(), Open(), PlayPause(), Rotate(), Stop(), and Zoom().
SetAudioDelay()
JSONRPC_STATUS CPlayerOperations::SetAudioDelay (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asDouble(), JSONRPC::Audio, AUDIO_DELAY_STEP, JSONRPC::FailedToExecute, CServiceBroker::GetAppComponents(), GetPlayer(), CServiceBroker::GetSettingsComponent(), JSONRPC::InvalidParams, CVideoSettings::m_AudioDelay, JSONRPC::None, JSONRPC::OK, JSONRPC::Picture, MathUtils::RoundF(), and JSONRPC::Video.
SetAudioStream()
JSONRPC_STATUS CPlayerOperations::SetAudioStream (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asInteger(), CVariant::asString(), JSONRPC::Audio, JSONRPC::FailedToExecute, CServiceBroker::GetAppComponents(), GetPlayer(), index(), JSONRPC::InvalidParams, JSONRPC::Picture, and JSONRPC::Video.
SetPartymode()
JSONRPC_STATUS CPlayerOperations::SetPartymode (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::Audio, JSONRPC::FailedToExecute, g_partyModeManager, CServiceBroker::GetAppMessenger(), GetPlayer(), CPartyModeManager::GetType(), JSONRPC::InvalidParams, CPartyModeManager::IsEnabled(), IsPVRChannel(), CVariant::isString(), PARTYMODECONTEXT_MUSIC, PARTYMODECONTEXT_UNKNOWN, PARTYMODECONTEXT_VIDEO, JSONRPC::Picture, TMSG_EXECUTE_BUILT_IN, and JSONRPC::Video.
SetRepeat()
JSONRPC_STATUS CPlayerOperations::SetRepeat (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::Audio, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), GetPlayer(), GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), KODI::PLAYLIST::CPlayListPlayer::GetRepeat(), IsPVRChannel(), ParseRepeatState(), JSONRPC::Picture, TMSG_PLAYLISTPLAYER_REPEAT, and JSONRPC::Video.
SetShuffle()
JSONRPC_STATUS CPlayerOperations::SetShuffle (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asBoolean(), CVariant::asString(), JSONRPC::Audio, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), GetPlayer(), GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetSlideShowDelegator(), CVariant::isBoolean(), IsPVRChannel(), CSlideShowDelegator::IsShuffled(), CVariant::isString(), CSlideShowDelegator::NumSlides(), JSONRPC::Picture, CSlideShowDelegator::Shuffle(), TMSG_PLAYLISTPLAYER_SHUFFLE, and JSONRPC::Video.
SetSpeed()
JSONRPC_STATUS CPlayerOperations::SetSpeed (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::Audio, CBuiltins::Execute(), JSONRPC::FailedToExecute, CServiceBroker::GetAppComponents(), CBuiltins::GetInstance(), GetPlayer(), JSONRPC::InvalidParams, JSONRPC::None, JSONRPC::OK, JSONRPC::Picture, and JSONRPC::Video.
SetSubtitle()
JSONRPC_STATUS CPlayerOperations::SetSubtitle (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asInteger(), CVariant::asString(), JSONRPC::Audio, JSONRPC::FailedToExecute, CServiceBroker::GetAppComponents(), GetPlayer(), index(), JSONRPC::InvalidParams, JSONRPC::Picture, and JSONRPC::Video.
SetTempo()
JSONRPC_STATUS CPlayerOperations::SetTempo (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CPlayerUtils::AdvanceTempoStep(), CVariant::asFloat(), JSONRPC::Audio, DECREASE, JSONRPC::FailedToExecute, CServiceBroker::GetAppComponents(), GetPlayer(), INCREASE, JSONRPC::InvalidParams, JSONRPC::None, JSONRPC::OK, JSONRPC::Picture, CApplicationPlayer::SetTempo(), and JSONRPC::Video.
SetVideoStream()
JSONRPC_STATUS CPlayerOperations::SetVideoStream (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asInteger(), CVariant::asString(), JSONRPC::Audio, JSONRPC::FailedToExecute, CServiceBroker::GetAppComponents(), GetPlayer(), CApplicationPlayer::GetVideoStreamCount(), index(), JSONRPC::InvalidParams, JSONRPC::Picture, and JSONRPC::Video.
SetViewMode()
JSONRPC_STATUS CPlayerOperations::SetViewMode (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asBoolean(), CVariant::asString(), CServiceBroker::GetAppComponents(), GetNewValueForViewModeParameter(), JSONRPC::InvalidParams, CVariant::isBoolean(), CVariant::isNull(), CVariant::isObject(), CVariant::isString(), ViewModeCustom, ViewModeNormal, and viewModes.
StartSlideshow()
JSONRPC_STATUS CPlayerOperations::StartSlideshow (const std::string & path, bool recursive, bool random, const std::string & firstPicturePath = "") static private
References JSONRPC::ACK, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), GUI_MSG_START_SLIDESHOW, CApplicationPowerHandling::ResetScreenSaver(), CGUIMessage::SetStringParams(), and WINDOW_SLIDESHOW.
Referenced by Open().
Stop()
JSONRPC_STATUS CPlayerOperations::Stop (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, ACTION_STOP, JSONRPC::Audio, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), GetPlayer(), JSONRPC::None, JSONRPC::Picture, SendSlideshowAction(), TMSG_MEDIA_STOP, and JSONRPC::Video.
Zoom()
JSONRPC_STATUS CPlayerOperations::Zoom (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, ACTION_ZOOM_IN, ACTION_ZOOM_LEVEL_NORMAL, ACTION_ZOOM_OUT, CVariant::asInteger(), CVariant::asString(), JSONRPC::Audio, JSONRPC::FailedToExecute, GetPlayer(), JSONRPC::InvalidParams, CVariant::isInteger(), CVariant::isString(), JSONRPC::None, JSONRPC::Picture, SendSlideshowAction(), and JSONRPC::Video.
The documentation for this class was generated from the following files:
PlayerOperations.h
PlayerOperations.cpp