Kodi Documentation: KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp} Namespace Reference
KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp} Namespace Reference
Functions
void SetupRarOptions (CFileItem &item, const std::string &path)
Function Documentation
SetupRarOptions()
void KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions (CFileItem & item, const std::string & path)
References XFILE::CDirectoryCache::ClearDirectory(), g_directoryCache, CURL::Get(), CURL::GetOptions(), CFileItem::GetVideoInfoTag(), CURL::GetWithoutFilename(), CFileItem::HasVideoInfoTag(), KODI::VIDEO::IsVideoDb(), CVideoInfoTag::m_strFileNameAndPath, CURL::SetOptions(), CFileItem::SetPath(), and SetupRarOptions().
Referenced by SetupRarOptions().