Kodi Documentation: KODI::GAME::CGameClientInput Class Reference
KODI::GAME::CGameClientInput Class Reference
Games
#include <GameClientInput.h>
Public Types
using PortAddress = std::string
using JoystickMap = std::map< PortAddress, std::shared_ptr< CGameClientJoystick > >
Public Member Functions
CGameClientInput (CGameClient &gameClient, AddonInstance_Game &addonStruct, CCriticalSection &clientAccess)
~CGameClientInput () override
void Initialize ()
void Deinitialize ()
void Start (IGameInputCallback *input)
void Stop ()
bool HasFeature (const std::string &controllerId, const std::string &featureName) const
bool AcceptsInput () const
bool InputEvent (const game_input_event &event)
float GetPortActivation (const std::string &portAddress)
const CControllerTree & GetDefaultControllerTree () const
CControllerTree GetActiveControllerTree () const
bool SupportsKeyboard () const
bool SupportsMouse () const
int GetPlayerLimit () const
bool ConnectController (const std::string &portAddress, const ControllerPtr &controller)
bool DisconnectController (const std::string &portAddress)
void SavePorts ()
void ResetPorts ()
const JoystickMap & GetJoystickMap () const
void CloseJoysticks (PERIPHERALS::EventLockHandlePtr &inputHandlingLock)
bool OpenKeyboard (const ControllerPtr &controller, const PERIPHERALS::PeripheralPtr &keyboard)
bool IsKeyboardOpen () const
void CloseKeyboard ()
bool OpenMouse (const ControllerPtr &controller, const PERIPHERALS::PeripheralPtr &mouse)
bool IsMouseOpen () const
void CloseMouse ()
bool HasAgent () const
void HardwareReset ()
bool ReceiveInputEvent (const game_input_event &eventStruct)
Public Member Functions inherited from Observable
Observable ()=default
virtual ~Observable ()=default
Observable & operator= (const Observable &observable)
virtual void RegisterObserver (Observer *obs)
Register an observer.
virtual void UnregisterObserver (Observer *obs)
Unregister an observer.
virtual void NotifyObservers (const ObservableMessage message=ObservableMessageNone)
Send a message to all observers when m_bObservableChanged is true.
virtual void SetChanged (bool bSetTo=true)
Mark an observable changed.
virtual bool IsObserving (const Observer &obs) const
Check whether this observable is being observed by an observer.
Private Types
using ControllerLayoutMap = std::map< std::string, std::unique_ptr< CGameClientController > >
Private Member Functions
void LoadTopology ()
void SetControllerLayouts (const ControllerVector &controllers)
bool OpenJoystick (const std::string &portAddress, const ControllerPtr &controller)
void CloseJoysticks (const CPortNode &port, PERIPHERALS::EventLockHandlePtr &inputHandlingLock)
void CloseJoystick (const std::string &portAddress, PERIPHERALS::EventLockHandlePtr &inputHandlingLock)
bool SetRumble (const std::string &portAddress, const std::string &feature, float magnitude)
Static Private Member Functions
static ControllerVector GetControllers (const CGameClient &gameClient)
static void ActivateControllers (CControllerHub &hub)
Private Attributes
IGameInputCallback * m_inputCallback = nullptr
std::unique_ptr< CGameClientTopology > m_topology
ControllerLayoutMap m_controllerLayouts
JoystickMap m_joysticks
Map of port address to joystick handler.
std::unique_ptr< CPortManager > m_portManager
Serializable port state.
std::recursive_mutex m_portMutex
Mutex for port state.
std::unique_ptr< CGameClientKeyboard > m_keyboard
Keyboard handler.
std::unique_ptr< CGameClientMouse > m_mouse
Mouse handler.
std::unique_ptr< CGameClientHardware > m_hardware
Hardware input handler.
Additional Inherited Members
Protected Member Functions inherited from KODI::GAME::CGameClientSubsystem
CGameClientSubsystem (CGameClient &gameClient, AddonInstance_Game &addonStruct, CCriticalSection &clientAccess)
virtual ~CGameClientSubsystem ()
CGameClientCheevos & Cheevos () const
CGameClientInput & Input () const
CGameClientProperties & AddonProperties () const
CGameClientStreams & Streams () const
Protected Member Functions inherited from Observable
void SendMessage (const ObservableMessage message)
Send a message to all observer when m_bObservableChanged is true.
Observable ()=default
virtual ~Observable ()=default
Observable & operator= (const Observable &observable)
virtual void RegisterObserver (Observer *obs)
Register an observer.
virtual void UnregisterObserver (Observer *obs)
Unregister an observer.
virtual void NotifyObservers (const ObservableMessage message=ObservableMessageNone)
Send a message to all observers when m_bObservableChanged is true.
virtual void SetChanged (bool bSetTo=true)
Mark an observable changed.
virtual bool IsObserving (const Observer &obs) const
Check whether this observable is being observed by an observer.
Static Protected Member Functions inherited from KODI::GAME::CGameClientSubsystem
static GameClientSubsystems CreateSubsystems (CGameClient &gameClient, AddonInstance_Game &gameStruct, CCriticalSection &clientAccess)
Create a struct with the allocated subsystems.
static void DestroySubsystems (GameClientSubsystems &subsystems)
Deallocate subsystems.
Protected Attributes inherited from KODI::GAME::CGameClientSubsystem
CGameClient & m_gameClient
AddonInstance_Game & m_struct
CCriticalSection & m_clientAccess
Protected Attributes inherited from Observable
std::atomic< bool > m_bObservableChanged {false}
std::vector< Observer * > m_observers
CCriticalSection m_obsCritSection
Member Typedef Documentation
ControllerLayoutMap
using KODI::GAME::CGameClientInput::ControllerLayoutMap = std::map<std::string, std::unique_ptr<CGameClientController> > private
JoystickMap
using KODI::GAME::CGameClientInput::JoystickMap = std::map<PortAddress, std::shared_ptr<CGameClientJoystick> >
PortAddress
using KODI::GAME::CGameClientInput::PortAddress = std::string
Todo:
de-duplicate
Constructor & Destructor Documentation
CGameClientInput()
CGameClientInput::CGameClientInput (CGameClient & gameClient, AddonInstance_Game & addonStruct, CCriticalSection & clientAccess)
~CGameClientInput()
CGameClientInput::~CGameClientInput () override
References Deinitialize().
Member Function Documentation
AcceptsInput()
bool CGameClientInput::AcceptsInput () const
References KODI::GAME::IGameInputCallback::AcceptsInput(), and m_inputCallback.
Referenced by KODI::GAME::CGameClientJoystick::AcceptsInput(), KODI::GAME::CGameClientMouse::OnButtonPress(), KODI::GAME::CGameClientKeyboard::OnKeyPress(), and KODI::GAME::CGameClientMouse::OnMotion().
ActivateControllers()
void CGameClientInput::ActivateControllers (CControllerHub & hub) static private
References ActivateControllers(), and KODI::GAME::CControllerHub::GetPorts().
Referenced by ActivateControllers(), and Initialize().
CloseJoystick()
void CGameClientInput::CloseJoystick (const std::string & portAddress, PERIPHERALS::EventLockHandlePtr & inputHandlingLock) private
References CServiceBroker::GetPeripherals(), m_joysticks, and PERIPHERALS::CPeripherals::RegisterEventLock().
Referenced by CloseJoysticks(), CloseJoysticks(), and DisconnectController().
CloseJoysticks() [1/2]
void CGameClientInput::CloseJoysticks (const CPortNode & port, PERIPHERALS::EventLockHandlePtr & inputHandlingLock) private
References CloseJoystick(), CloseJoysticks(), KODI::GAME::CPortNode::GetActiveController(), KODI::GAME::CPortNode::GetAddress(), KODI::GAME::CControllerNode::GetHub(), and KODI::GAME::CControllerHub::GetPorts().
CloseJoysticks() [2/2]
void CGameClientInput::CloseJoysticks (PERIPHERALS::EventLockHandlePtr & inputHandlingLock)
References CloseJoystick(), and m_joysticks.
Referenced by CloseJoysticks(), ConnectController(), DisconnectController(), and Stop().
CloseKeyboard()
void CGameClientInput::CloseKeyboard ()
References ADDON::CAddonDll::Initialized(), KODI::GAME::CGameClient::LogException(), KODI::GAME::CGameClientSubsystem::m_clientAccess, KODI::GAME::CGameClientSubsystem::m_gameClient, m_keyboard, KODI::GAME::CGameClientSubsystem::m_struct, and AddonInstance_Game::toAddon.
Referenced by Stop().
CloseMouse()
void CGameClientInput::CloseMouse ()
References ADDON::CAddonDll::Initialized(), KODI::GAME::CGameClient::LogException(), KODI::GAME::CGameClientSubsystem::m_clientAccess, KODI::GAME::CGameClientSubsystem::m_gameClient, m_mouse, KODI::GAME::CGameClientSubsystem::m_struct, and AddonInstance_Game::toAddon.
Referenced by Stop().
ConnectController()
bool CGameClientInput::ConnectController (const std::string & portAddress, const ControllerPtr & controller)
References CloseJoysticks(), ConnectController(), KODI::GAME::CPortNode::GetActiveController(), GetDefaultControllerTree(), KODI::GAME::CControllerNode::GetHub(), KODI::GAME::CControllerHub::GetPort(), KODI::GAME::CPortNode::GetPort(), KODI::GAME::CControllerHub::GetPorts(), ADDON::CAddonDll::Initialized(), KODI::GAME::CPortNode::IsControllerAccepted(), CLog::Log(), LOGERROR, KODI::GAME::CGameClient::LogException(), KODI::GAME::CGameClientSubsystem::m_clientAccess, KODI::GAME::CGameClientSubsystem::m_gameClient, m_portManager, m_portMutex, KODI::GAME::CGameClientSubsystem::m_struct, OpenJoystick(), Observable::SetChanged(), and AddonInstance_Game::toAddon.
Referenced by ConnectController(), ResetPorts(), and Start().
Deinitialize()
void CGameClientInput::Deinitialize ()
References m_controllerLayouts, m_portManager, m_topology, and Stop().
Referenced by KODI::GAME::CGameClient::Unload(), and ~CGameClientInput().
DisconnectController()
bool CGameClientInput::DisconnectController (const std::string & portAddress)
References CloseJoystick(), CloseJoysticks(), KODI::GAME::CPortNode::GetPort(), ADDON::CAddonDll::Initialized(), KODI::GAME::CGameClient::LogException(), KODI::GAME::CGameClientSubsystem::m_clientAccess, KODI::GAME::CGameClientSubsystem::m_gameClient, m_portManager, m_portMutex, KODI::GAME::CGameClientSubsystem::m_struct, Observable::SetChanged(), and AddonInstance_Game::toAddon.
Referenced by Start().
GetActiveControllerTree()
CControllerTree CGameClientInput::GetActiveControllerTree () const
References m_portManager, and m_portMutex.
GetControllers()
ControllerVector CGameClientInput::GetControllers (const CGameClient & gameClient) static private
References KODI::GAME::CGameServices::GetController(), KODI::GAME::CGameServices::GetDefaultController(), ADDON::CAddon::GetDependencies(), and CServiceBroker::GetGameServices().
Referenced by LoadTopology().
GetDefaultControllerTree()
const CControllerTree & CGameClientInput::GetDefaultControllerTree () const
References m_topology.
Referenced by ConnectController(), ResetPorts(), SupportsKeyboard(), and SupportsMouse().
GetJoystickMap()
const JoystickMap & KODI::GAME::CGameClientInput::GetJoystickMap () const inline
References m_joysticks.
GetPlayerLimit()
int CGameClientInput::GetPlayerLimit () const
References m_topology.
GetPortActivation()
float CGameClientInput::GetPortActivation (const std::string & portAddress)
References KEYBOARD_PORT_ADDRESS, m_joysticks, m_keyboard, m_mouse, m_portMutex, and MOUSE_PORT_ADDRESS.
HardwareReset()
void CGameClientInput::HardwareReset ()
References m_hardware.
HasAgent()
bool CGameClientInput::HasAgent () const
References m_joysticks, m_keyboard, and m_mouse.
HasFeature()
bool CGameClientInput::HasFeature (const std::string & controllerId, const std::string & featureName) const
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, KODI::GAME::CGameClientSubsystem::m_gameClient, KODI::GAME::CGameClientSubsystem::m_struct, and AddonInstance_Game::toAddon.
Referenced by KODI::GAME::CGameClientController::CGameClientController(), KODI::GAME::CGameClientJoystick::HasFeature(), and KODI::GAME::CGameClientKeyboard::HasKey().
Initialize()
void CGameClientInput::Initialize ()
References ActivateControllers(), LoadTopology(), KODI::GAME::CGameClientSubsystem::m_gameClient, m_portManager, m_portMutex, m_topology, ADDON::CAddon::Profile(), and SetControllerLayouts().
Referenced by KODI::GAME::CGameClient::Initialize().
InputEvent()
bool CGameClientInput::InputEvent (const game_input_event & event)
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, KODI::GAME::CGameClientSubsystem::m_gameClient, KODI::GAME::CGameClientSubsystem::m_struct, and AddonInstance_Game::toAddon.
Referenced by KODI::GAME::CGameClientJoystick::OnAccelerometerMotion(), KODI::GAME::CGameClientJoystick::OnAnalogStickMotion(), KODI::GAME::CGameClientJoystick::OnButtonMotion(), KODI::GAME::CGameClientMouse::OnButtonPress(), KODI::GAME::CGameClientJoystick::OnButtonPress(), KODI::GAME::CGameClientMouse::OnButtonRelease(), KODI::GAME::CGameClientKeyboard::OnKeyPress(), KODI::GAME::CGameClientKeyboard::OnKeyRelease(), KODI::GAME::CGameClientMouse::OnMotion(), KODI::GAME::CGameClientJoystick::OnThrottleMotion(), and KODI::GAME::CGameClientJoystick::OnWheelMotion().
IsKeyboardOpen()
bool CGameClientInput::IsKeyboardOpen () const
References m_keyboard.
IsMouseOpen()
bool CGameClientInput::IsMouseOpen () const
References m_mouse.
LoadTopology()
void CGameClientInput::LoadTopology () private
Todo:
Guard against infinite loops provided by the game client
References GetControllers(), KodiToAddonFuncTable_Game::GetTopology(), ADDON::CAddonDll::Initialized(), KODI::GAME::CGameClient::LogException(), KODI::GAME::CGameClientSubsystem::m_gameClient, KODI::GAME::CGameClientSubsystem::m_struct, m_topology, game_input_topology::player_limit, game_input_topology::port_count, game_input_topology::ports, and AddonInstance_Game::toAddon.
Referenced by Initialize().
OpenJoystick()
bool CGameClientInput::OpenJoystick (const std::string & portAddress, const ControllerPtr & controller) private
References CLog::Log(), LOGERROR, KODI::GAME::CGameClientSubsystem::m_gameClient, and m_joysticks.
Referenced by ConnectController().
OpenKeyboard()
bool CGameClientInput::OpenKeyboard (const ControllerPtr & controller, const PERIPHERALS::PeripheralPtr & keyboard)
References ADDON::CAddon::ID(), ADDON::CAddonDll::Initialized(), CLog::Log(), LOGERROR, KODI::GAME::CGameClient::LogException(), KODI::GAME::CGameClientSubsystem::m_clientAccess, KODI::GAME::CGameClientSubsystem::m_gameClient, m_keyboard, KODI::GAME::CGameClientSubsystem::m_struct, and AddonInstance_Game::toAddon.
OpenMouse()
bool CGameClientInput::OpenMouse (const ControllerPtr & controller, const PERIPHERALS::PeripheralPtr & mouse)
References ADDON::CAddon::ID(), ADDON::CAddonDll::Initialized(), CLog::Log(), LOGERROR, KODI::GAME::CGameClient::LogException(), KODI::GAME::CGameClientSubsystem::m_clientAccess, KODI::GAME::CGameClientSubsystem::m_gameClient, m_mouse, KODI::GAME::CGameClientSubsystem::m_struct, and AddonInstance_Game::toAddon.
ReceiveInputEvent()
bool CGameClientInput::ReceiveInputEvent (const game_input_event & eventStruct)
References game_input_event::feature_name, GAME_INPUT_EVENT_MOTOR, game_motor_event::magnitude, game_input_event::motor, game_input_event::port_address, SetRumble(), and game_input_event::type.
Referenced by KODI::GAME::CGameClient::cb_input_event().
ResetPorts()
void CGameClientInput::ResetPorts ()
References ConnectController(), GetDefaultControllerTree(), KODI::GAME::CControllerHub::GetPorts(), and m_portMutex.
SavePorts()
void CGameClientInput::SavePorts ()
References m_portManager, m_portMutex, Observable::NotifyObservers(), and ObservableMessageGamePortsChanged.
SetControllerLayouts()
void CGameClientInput::SetControllerLayouts (const ControllerVector & controllers) private
References KODI::GAME::CGameClient::LogException(), m_controllerLayouts, KODI::GAME::CGameClientSubsystem::m_gameClient, KODI::GAME::CGameClientSubsystem::m_struct, and AddonInstance_Game::toAddon.
Referenced by Initialize().
SetRumble()
bool CGameClientInput::SetRumble (const std::string & portAddress, const std::string & feature, float magnitude) private
References m_joysticks.
Referenced by ReceiveInputEvent().
Start()
void CGameClientInput::Start (IGameInputCallback * input)
References ConnectController(), DisconnectController(), KODI::GAME::CGameClientSubsystem::m_gameClient, m_hardware, m_inputCallback, m_portManager, m_portMutex, Observable::NotifyObservers(), and ObservableMessageGamePortsChanged.
Referenced by KODI::GAME::CGameClient::InitializeGameplay().
Stop()
void CGameClientInput::Stop ()
References CloseJoysticks(), CloseKeyboard(), CloseMouse(), m_hardware, m_inputCallback, and m_portMutex.
Referenced by KODI::GAME::CGameClient::CloseFile(), and Deinitialize().
SupportsKeyboard()
bool CGameClientInput::SupportsKeyboard () const
References GetDefaultControllerTree(), and KODI::GAME::CControllerHub::GetPorts().
SupportsMouse()
bool CGameClientInput::SupportsMouse () const
References GetDefaultControllerTree(), and KODI::GAME::CControllerHub::GetPorts().
Member Data Documentation
m_controllerLayouts
ControllerLayoutMap KODI::GAME::CGameClientInput::m_controllerLayouts private
Referenced by Deinitialize(), and SetControllerLayouts().
m_hardware
std::unique_ptr<CGameClientHardware> KODI::GAME::CGameClientInput::m_hardware private
Hardware input handler.
This connects to input from game console hardware belonging to the game client.
Referenced by HardwareReset(), Start(), and Stop().
m_inputCallback
IGameInputCallback* KODI::GAME::CGameClientInput::m_inputCallback = nullptr private
Referenced by AcceptsInput(), Start(), and Stop().
m_joysticks
JoystickMap KODI::GAME::CGameClientInput::m_joysticks private
Map of port address to joystick handler.
The port address is a string that identifies the adress of the port.
The joystick handler connects to joystick input of the game client.
This property is always populated with the default joystick configuration (i.e. all ports are connected to the first controller they accept).
Referenced by CloseJoystick(), CloseJoysticks(), GetJoystickMap(), GetPortActivation(), HasAgent(), OpenJoystick(), and SetRumble().
m_keyboard
std::unique_ptr<CGameClientKeyboard> KODI::GAME::CGameClientInput::m_keyboard private
Keyboard handler.
This connects to the keyboard input of the game client.
Referenced by CloseKeyboard(), GetPortActivation(), HasAgent(), IsKeyboardOpen(), and OpenKeyboard().
m_mouse
std::unique_ptr<CGameClientMouse> KODI::GAME::CGameClientInput::m_mouse private
Mouse handler.
This connects to the mouse input of the game client.
Referenced by CloseMouse(), GetPortActivation(), HasAgent(), IsMouseOpen(), and OpenMouse().
m_portManager
std::unique_ptr<CPortManager> KODI::GAME::CGameClientInput::m_portManager private
Serializable port state.
Referenced by ConnectController(), Deinitialize(), DisconnectController(), GetActiveControllerTree(), Initialize(), SavePorts(), and Start().
m_portMutex
std::recursive_mutex KODI::GAME::CGameClientInput::m_portMutex mutable private
Mutex for port state.
Mutex is recursive to allow for management of several ports within the function ResetPorts().
Referenced by ConnectController(), DisconnectController(), GetActiveControllerTree(), GetPortActivation(), Initialize(), ResetPorts(), SavePorts(), Start(), and Stop().
m_topology
std::unique_ptr<CGameClientTopology> KODI::GAME::CGameClientInput::m_topology private
Referenced by Deinitialize(), GetDefaultControllerTree(), GetPlayerLimit(), Initialize(), and LoadTopology().
The documentation for this class was generated from the following files:
GameClientInput.h
GameClientInput.cpp