Kodi Documentation: CGUISourcesAnnouncementHandler Class Reference
CGUISourcesAnnouncementHandler Class Reference
Handler for announcements of type sources.
#include <GUISourcesAnnouncementHandler.h>
Public Member Functions
CGUISourcesAnnouncementHandler ()
~CGUISourcesAnnouncementHandler ()
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Detailed Description
Handler for announcements of type sources.
Constructor & Destructor Documentation
CGUISourcesAnnouncementHandler()
CGUISourcesAnnouncementHandler::CGUISourcesAnnouncementHandler ()
References CServiceBroker::GetAnnouncementManager(), and ANNOUNCEMENT::Sources.
~CGUISourcesAnnouncementHandler()
CGUISourcesAnnouncementHandler::~CGUISourcesAnnouncementHandler ()
References CServiceBroker::GetAnnouncementManager().
Member Function Documentation
Announce()
void CGUISourcesAnnouncementHandler::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References data(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_PATH, and CGUIMessage::SetStringParam().
The documentation for this class was generated from the following files:
GUISourcesAnnouncementHandler.h
GUISourcesAnnouncementHandler.cpp