Kodi Documentation: VAAPI::IVaapiWinSystem Class Reference
VAAPI::IVaapiWinSystem Class Reference abstract
#include <VAAPI.h>
Public Member Functions
virtual ~IVaapiWinSystem ()=default
virtual VADisplay GetVADisplay ()=0
virtual void * GetEGLDisplay ()
Constructor & Destructor Documentation
~IVaapiWinSystem()
virtual VAAPI::IVaapiWinSystem::~IVaapiWinSystem () virtual default
Member Function Documentation
GetEGLDisplay()
virtual void * VAAPI::IVaapiWinSystem::GetEGLDisplay () inline virtual
Referenced by CRendererVAAPIGL::Configure(), and CRendererVAAPIGLES::Configure().
GetVADisplay()
virtual VADisplay VAAPI::IVaapiWinSystem::GetVADisplay () pure virtual
Referenced by VAAPI::CVAAPIContext::SetVaDisplayForSystem().
The documentation for this class was generated from the following file:
VAAPI.h