Kodi Documentation: ADDON::Interface_GUIWindow Struct Reference
ADDON::Interface_GUIWindow Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Window.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static KODI_GUI_WINDOW_HANDLE create (KODI_HANDLE kodiBase, const char *xml_filename, const char *default_skin, bool as_dialog, bool is_media)
callback functions from add-on to kodi
static void destroy (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static void set_callbacks (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, KODI_GUI_CLIENT_HANDLE clienthandle, bool(*CBInit)(KODI_GUI_CLIENT_HANDLE), bool(*CBFocus)(KODI_GUI_CLIENT_HANDLE, int), bool(*CBClick)(KODI_GUI_CLIENT_HANDLE, int), bool(*CBOnAction)(KODI_GUI_CLIENT_HANDLE, ADDON_ACTION), void(*CBGetContextButtons)(KODI_GUI_CLIENT_HANDLE, int, gui_context_menu_pair *, unsigned int *), bool(*CBOnContextButton)(KODI_GUI_CLIENT_HANDLE, int, unsigned int))
static bool show (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static bool close (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static bool do_modal (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static bool set_focus_id (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static int get_focus_id (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static void set_control_label (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id, const char *label)
static void set_control_visible (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id, bool visible)
static void set_control_selected (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id, bool selected)
static void set_property (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *key, const char *value)
static void set_property_int (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *key, int value)
static void set_property_bool (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *key, bool value)
static void set_property_double (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *key, double value)
static char * get_property (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *key)
static int get_property_int (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *key)
static bool get_property_bool (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *key)
static double get_property_double (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *key)
static void clear_properties (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static void clear_property (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *key)
static void clear_item_list (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static void add_list_item (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, KODI_GUI_LISTITEM_HANDLE item, int list_position)
static void remove_list_item_from_position (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int list_position)
static void remove_list_item (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, KODI_GUI_LISTITEM_HANDLE item)
static KODI_GUI_LISTITEM_HANDLE get_list_item (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int list_position)
static void set_current_list_position (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int list_position)
static int get_current_list_position (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static int get_list_size (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static void set_container_property (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *key, const char *value)
static void set_container_content (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char *value)
static int get_current_container_id (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static void mark_dirty_region (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle)
static KODI_GUI_CONTROL_HANDLE get_control_button (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_edit (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_fade_label (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_image (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_label (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_radio_button (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_progress (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_render_addon (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_settings_slider (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_slider (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_spin (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
static KODI_GUI_CONTROL_HANDLE get_control_text_box (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id)
Static Private Member Functions
static KODI_GUI_CONTROL_HANDLE GetControl (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id, const char *function, CGUIControl::GUICONTROLTYPES type, const std::string &typeName)
static int GetNextAvailableWindowId ()
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/Window.h"
Member Function Documentation
add_list_item()
void ADDON::Interface_GUIWindow::add_list_item (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, KODI_GUI_LISTITEM_HANDLE item, int list_position) static
References ADDON::CGUIAddonWindow::AddItem(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
clear_item_list()
void ADDON::Interface_GUIWindow::clear_item_list (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
List item functions
References ADDON::CGUIAddonWindow::ClearList(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
clear_properties()
void ADDON::Interface_GUIWindow::clear_properties (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
References CGUIWindow::ClearProperties(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
clear_property()
void ADDON::Interface_GUIWindow::clear_property (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * key) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, CGUIWindow::SetProperty(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
close()
bool ADDON::Interface_GUIWindow::close (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
References CGUIWindowManager::ActivateWindow(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), CGUIWindow::IsDialog(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::m_oldWindowId, ADDON::CGUIAddonWindow::PulseActionEvent(), Show(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
create()
KODI_GUI_WINDOW_HANDLE ADDON::Interface_GUIWindow::create (KODI_HANDLE kodiBase, const char * xml_filename, const char * default_skin, bool as_dialog, bool is_media) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
Window creation functions
References CGUIWindowManager::Add(), URIUtils::AddFileToFolder(), ADDON::CAddon::Author(), CFileUtils::Exists(), g_SkinInfo, CServiceBroker::GetGUI(), GetNextAvailableWindowId(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, LOGWARNING, ADDON::CAddon::Name(), ADDON::CAddon::Path(), CGUIWindow::SetCoordsRes(), ADDON::SKIN, ADDON::CAddonInfo::TranslateType(), ADDON::CAddon::Type(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
DeInit()
void ADDON::Interface_GUIWindow::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_Addon::kodi_gui, AddonGlobalInterface::toKodi, and AddonToKodiFuncTable_kodi_gui::window.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
destroy()
void ADDON::Interface_GUIWindow::destroy (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
References CGUIWindowManager::ActivateWindow(), CGUIWindow::ClearProperties(), CGUIWindow::FreeResources(), g_application, CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::m_oldWindowId, CGUIWindowManager::Remove(), ADDON::Interface_GUIGeneral::unlock(), and WINDOW_HOME.
Referenced by Init().
do_modal()
bool ADDON::Interface_GUIWindow::do_modal (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
References CGUIWindowManager::ActivateWindow(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), CGUIWindow::IsDialog(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::m_oldWindowId, ADDON::CGUIAddonWindow::m_windowId, Show(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
get_control_button()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_button (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
GUI control access functions
References GetControl(), and CGUIControl::GUICONTROL_BUTTON.
Referenced by Init().
get_control_edit()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_edit (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_EDIT.
Referenced by Init().
get_control_fade_label()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_fade_label (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_FADELABEL.
Referenced by Init().
get_control_image()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_image (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_IMAGE.
Referenced by Init().
get_control_label()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_label (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_LABEL.
Referenced by Init().
get_control_progress()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_progress (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_PROGRESS.
Referenced by Init().
get_control_radio_button()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_radio_button (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_RADIO.
Referenced by Init().
get_control_render_addon()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_render_addon (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_RENDERADDON.
Referenced by Init().
get_control_settings_slider()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_settings_slider (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_SETTINGS_SLIDER.
Referenced by Init().
get_control_slider()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_slider (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_SLIDER.
Referenced by Init().
get_control_spin()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_spin (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_SPINEX.
Referenced by Init().
get_control_text_box()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::get_control_text_box (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
References GetControl(), and CGUIControl::GUICONTROL_TEXTBOX.
Referenced by Init().
get_current_container_id()
int ADDON::Interface_GUIWindow::get_current_container_id (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
References ADDON::CGUIAddonWindow::GetCurrentContainerControlId(), ADDON::CAddon::ID(), id, ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
get_current_list_position()
int ADDON::Interface_GUIWindow::get_current_list_position (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
References ADDON::CGUIAddonWindow::GetCurrentListPosition(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
get_focus_id()
int ADDON::Interface_GUIWindow::get_focus_id (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
References CGUIControlGroup::GetFocusedControlID(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CAddon::Name(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
get_list_item()
KODI_GUI_LISTITEM_HANDLE ADDON::Interface_GUIWindow::get_list_item (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int list_position) static
References ADDON::CGUIAddonWindow::GetListItem(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CAddon::Name(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
get_list_size()
int ADDON::Interface_GUIWindow::get_list_size (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
References ADDON::CGUIAddonWindow::GetListSize(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
get_property()
char * ADDON::Interface_GUIWindow::get_property (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * key) static
References CVariant::asString(), CGUIWindow::GetProperty(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
get_property_bool()
bool ADDON::Interface_GUIWindow::get_property_bool (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * key) static
References CVariant::asBoolean(), CGUIWindow::GetProperty(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
get_property_double()
double ADDON::Interface_GUIWindow::get_property_double (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * key) static
References CVariant::asDouble(), CGUIWindow::GetProperty(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
get_property_int()
int ADDON::Interface_GUIWindow::get_property_int (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * key) static
References CVariant::asInteger(), CGUIWindow::GetProperty(), ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
GetControl()
KODI_GUI_CONTROL_HANDLE ADDON::Interface_GUIWindow::GetControl (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id, const char * function, CGUIControl::GUICONTROLTYPES type, const std::string & typeName) static private
References ADDON::CGUIAddonWindow::GetAddonControl(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by get_control_button(), get_control_edit(), get_control_fade_label(), get_control_image(), get_control_label(), get_control_progress(), get_control_radio_button(), get_control_render_addon(), get_control_settings_slider(), get_control_slider(), get_control_spin(), and get_control_text_box().
GetNextAvailableWindowId()
int ADDON::Interface_GUIWindow::GetNextAvailableWindowId () static private
References CServiceBroker::GetGUI(), id, ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::Interface_GUIGeneral::unlock(), WINDOW_ADDON_END, and WINDOW_ADDON_START.
Referenced by create().
Init()
void ADDON::Interface_GUIWindow::Init (AddonGlobalInterface * addonInterface) static
References add_list_item(), AddonToKodiFuncTable_kodi_gui_window::add_list_item, clear_item_list(), AddonToKodiFuncTable_kodi_gui_window::clear_item_list, clear_properties(), AddonToKodiFuncTable_kodi_gui_window::clear_properties, clear_property(), AddonToKodiFuncTable_kodi_gui_window::clear_property, close(), AddonToKodiFuncTable_kodi_gui_window::close, create(), destroy(), AddonToKodiFuncTable_kodi_gui_window::destroy, do_modal(), AddonToKodiFuncTable_kodi_gui_window::do_modal, get_control_button(), get_control_edit(), get_control_fade_label(), get_control_image(), get_control_label(), get_control_progress(), get_control_radio_button(), get_control_render_addon(), get_control_settings_slider(), get_control_slider(), get_control_spin(), get_control_text_box(), get_current_container_id(), AddonToKodiFuncTable_kodi_gui_window::get_current_container_id, get_current_list_position(), AddonToKodiFuncTable_kodi_gui_window::get_current_list_position, get_focus_id(), AddonToKodiFuncTable_kodi_gui_window::get_focus_id, get_list_item(), get_list_size(), AddonToKodiFuncTable_kodi_gui_window::get_list_size, get_property(), AddonToKodiFuncTable_kodi_gui_window::get_property, get_property_bool(), AddonToKodiFuncTable_kodi_gui_window::get_property_bool, get_property_double(), AddonToKodiFuncTable_kodi_gui_window::get_property_double, get_property_int(), AddonToKodiFuncTable_kodi_gui_window::get_property_int, AddonToKodiFuncTable_Addon::kodi_gui, mark_dirty_region(), AddonToKodiFuncTable_kodi_gui_window::mark_dirty_region, remove_list_item(), AddonToKodiFuncTable_kodi_gui_window::remove_list_item, remove_list_item_from_position(), AddonToKodiFuncTable_kodi_gui_window::remove_list_item_from_position, set_callbacks(), AddonToKodiFuncTable_kodi_gui_window::set_callbacks, set_container_content(), AddonToKodiFuncTable_kodi_gui_window::set_container_content, set_container_property(), AddonToKodiFuncTable_kodi_gui_window::set_container_property, set_control_label(), AddonToKodiFuncTable_kodi_gui_window::set_control_label, set_control_selected(), AddonToKodiFuncTable_kodi_gui_window::set_control_selected, set_control_visible(), AddonToKodiFuncTable_kodi_gui_window::set_control_visible, set_current_list_position(), AddonToKodiFuncTable_kodi_gui_window::set_current_list_position, set_focus_id(), AddonToKodiFuncTable_kodi_gui_window::set_focus_id, set_property(), AddonToKodiFuncTable_kodi_gui_window::set_property, set_property_bool(), AddonToKodiFuncTable_kodi_gui_window::set_property_bool, set_property_double(), AddonToKodiFuncTable_kodi_gui_window::set_property_double, set_property_int(), AddonToKodiFuncTable_kodi_gui_window::set_property_int, show(), AddonToKodiFuncTable_kodi_gui_window::show, AddonGlobalInterface::toKodi, and AddonToKodiFuncTable_kodi_gui::window.
Referenced by ADDON::Interface_GUIGeneral::Init().
mark_dirty_region()
void ADDON::Interface_GUIWindow::mark_dirty_region (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
Various functions
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, CGUIControl::MarkDirtyRegion(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
remove_list_item()
void ADDON::Interface_GUIWindow::remove_list_item (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, KODI_GUI_LISTITEM_HANDLE item) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::RemoveItem(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
remove_list_item_from_position()
void ADDON::Interface_GUIWindow::remove_list_item_from_position (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int list_position) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::RemoveItem(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_callbacks()
void ADDON::Interface_GUIWindow::set_callbacks (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, KODI_GUI_CLIENT_HANDLE clienthandle, bool(*)(KODI_GUI_CLIENT_HANDLE) CBInit, bool(*)(KODI_GUI_CLIENT_HANDLE, int) CBFocus, bool(*)(KODI_GUI_CLIENT_HANDLE, int) CBClick, bool(*)(KODI_GUI_CLIENT_HANDLE, ADDON_ACTION) CBOnAction, void(*)(KODI_GUI_CLIENT_HANDLE, int, gui_context_menu_pair *, unsigned int *) CBGetContextButtons, bool(*)(KODI_GUI_CLIENT_HANDLE, int, unsigned int) CBOnContextButton) static
References ADDON::CGUIAddonWindow::CBGetContextButtons, ADDON::CGUIAddonWindow::CBOnAction, ADDON::CGUIAddonWindow::CBOnClick, ADDON::CGUIAddonWindow::CBOnContextButton, ADDON::CGUIAddonWindow::CBOnFocus, ADDON::CGUIAddonWindow::CBOnInit, ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::m_clientHandle, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_container_content()
void ADDON::Interface_GUIWindow::set_container_content (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * value) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::SetContainerContent(), ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
set_container_property()
void ADDON::Interface_GUIWindow::set_container_property (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * key, const char * value) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::SetContainerProperty(), ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
set_control_label()
void ADDON::Interface_GUIWindow::set_control_label (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id, const char * label) static
References GUI_MSG_LABEL_SET, ADDON::CAddon::ID(), label, ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::m_windowId, ADDON::CGUIAddonWindow::OnMessage(), CGUIMessage::SetLabel(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_control_selected()
void ADDON::Interface_GUIWindow::set_control_selected (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id, bool selected) static
References GUI_MSG_SET_DESELECTED, GUI_MSG_SET_SELECTED, ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::m_windowId, ADDON::CGUIAddonWindow::OnMessage(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_control_visible()
void ADDON::Interface_GUIWindow::set_control_visible (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id, bool visible) static
References GUI_MSG_HIDDEN, GUI_MSG_VISIBLE, ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::m_windowId, ADDON::CGUIAddonWindow::OnMessage(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_current_list_position()
void ADDON::Interface_GUIWindow::set_current_list_position (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int list_position) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::SetCurrentListPosition(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_focus_id()
bool ADDON::Interface_GUIWindow::set_focus_id (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, int control_id) static
Window control functions
References CGUIControlLookup::GetControl(), GUI_MSG_SETFOCUS, ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::m_windowId, ADDON::CAddon::Name(), ADDON::CGUIAddonWindow::OnMessage(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_property()
void ADDON::Interface_GUIWindow::set_property (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * key, const char * value) static
Window property functions
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, CGUIWindow::SetProperty(), ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
set_property_bool()
void ADDON::Interface_GUIWindow::set_property_bool (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * key, bool value) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, CGUIWindow::SetProperty(), ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
set_property_double()
void ADDON::Interface_GUIWindow::set_property_double (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * key, double value) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, CGUIWindow::SetProperty(), ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
set_property_int()
void ADDON::Interface_GUIWindow::set_property_int (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle, const char * key, int value) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, CGUIWindow::SetProperty(), ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
show()
bool ADDON::Interface_GUIWindow::show (KODI_HANDLE kodiBase, KODI_GUI_WINDOW_HANDLE handle) static
References CGUIWindowManager::ActivateWindow(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), CGUIWindow::IsDialog(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonWindow::m_oldWindowId, ADDON::CGUIAddonWindow::m_windowId, Show(), and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
The documentation for this struct was generated from the following files:
addons/interfaces/gui/Window.h
addons/interfaces/gui/Window.cpp