Kodi Documentation: XFILE::CStackDirectory Class Reference
XFILE::CStackDirectory Class Reference
#include <StackDirectory.h>
Public Member Functions
CStackDirectory ()
~CStackDirectory () override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool AllowAll () const override
Whether to allow all files/folders to be listed.
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool Create (const CURL &url)
Create the directory.
virtual bool Exists (const CURL &url)
Check for directory existence.
virtual bool Remove (const CURL &url)
Removes the directory.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Static Public Member Functions
static std::string GetStackedTitlePath (const std::string &strPath)
static std::string GetStackedTitlePath (const std::string &strPath, VECCREGEXP &RegExps)
static std::string GetFirstStackedFile (const std::string &strPath)
static bool GetPaths (const std::string &strPath, std::vector< std::string > &vecPaths)
static std::string ConstructStackPath (const CFileItemList &items, const std::vector< int > &stack)
static bool ConstructStackPath (const std::vector< std::string > &paths, std::string &stackedPath)
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Additional Inherited Members
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CStackDirectory()
XFILE::CStackDirectory::CStackDirectory () default
~CStackDirectory()
XFILE::CStackDirectory::~CStackDirectory () override default
Member Function Documentation
AllowAll()
bool XFILE::CStackDirectory::AllowAll () const inline override virtual
Whether to allow all files/folders to be listed.
Returns
Returns true if all files/folder should be listed.
Reimplemented from XFILE::IDirectory.
ConstructStackPath() [1/2]
std::string XFILE::CStackDirectory::ConstructStackPath (const CFileItemList & items, const std::vector< int > & stack) static
References CFileItem::GetPath(), and URIUtils::Split().
Referenced by CURL::GetWithoutUserDetails(), CFileItemList::StackFiles(), TEST(), TEST(), and URIUtils::UpdateUrlEncoding().
ConstructStackPath() [2/2]
bool XFILE::CStackDirectory::ConstructStackPath (const std::vector< std::string > & paths, std::string & stackedPath) static
References URIUtils::Split().
GetDirectory()
bool XFILE::CStackDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References CFileItemList::Add(), CFileItemList::Clear(), CURL::Get(), and GetPaths().
Referenced by CDVDFileInfo::DemuxerToStreamDetails(), CVideoDatabase::GetBookMarksForFile(), URIUtils::GetParentPath(), CVideoDatabase::GetResumePoint(), GetStackedTitlePath(), CURL::GetWithoutUserDetails(), CApplicationStackHelper::InitializeStack(), and CDVDInputStreamStack::Open().
GetFirstStackedFile()
std::string XFILE::CStackDirectory::GetFirstStackedFile (const std::string & strPath) static
References URIUtils::AddFileToFolder(), and URIUtils::Split().
Referenced by CVideoDatabase::CleanDatabase(), CVideoTagLoaderFFmpeg::CVideoTagLoaderFFmpeg(), CFileItem::Exists(), CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), URIUtils::GetBasePath(), CVideoThumbLoader::GetEmbeddedThumbURL(), CDVDFileInfo::GetFileStreamDetails(), KODI::ART::GetLocalFanart(), UPNP::GetMimeType(), CFileUtils::GetModificationDate(), KODI::ART::GetTBNFile(), URIUtils::IsDAV(), URIUtils::IsDiscImageStack(), URIUtils::IsFTP(), URIUtils::IsHD(), URIUtils::IsHTTP(), URIUtils::IsInternetStream(), URIUtils::IsNetworkFilesystem(), URIUtils::IsNfs(), URIUtils::IsOnLAN(), URIUtils::IsPVR(), URIUtils::IsPVRChannel(), URIUtils::IsPVRChannelGroup(), URIUtils::IsPVRGuideItem(), URIUtils::IsPVRRadioChannel(), URIUtils::IsRemote(), URIUtils::IsSmb(), URIUtils::IsSpecial(), URIUtils::IsStreamedFilesystem(), URIUtils::IsTCP(), URIUtils::IsUDP(), CUtil::MakeLegalPath(), and CUtil::SupportsWriteFileOperations().
GetPaths()
bool XFILE::CStackDirectory::GetPaths (const std::string & strPath, std::vector< std::string > & vecPaths) static
Referenced by GetDirectory(), CGUIDialogSubtitles::OnDownloadComplete(), and URIUtils::UpdateUrlEncoding().
GetStackedTitlePath() [1/2]
std::string XFILE::CStackDirectory::GetStackedTitlePath (const std::string & strPath) static
References CRegExp::autoUtf8, CRegExp::GetCaptureTotal(), CServiceBroker::GetSettingsComponent(), GetStackedTitlePath(), CLog::Log(), LOGERROR, CRegExp::RegComp(), and void().
Referenced by CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), CFileItem::GetMovieName(), GetStackedTitlePath(), and KODI::ART::GetTBNFile().
GetStackedTitlePath() [2/2]
std::string XFILE::CStackDirectory::GetStackedTitlePath (const std::string & strPath, VECCREGEXP & RegExps) static
References CURL, GetDirectory(), URIUtils::GetFileName(), URIUtils::GetParentPath(), URIUtils::HasEncodedFilename(), and CFileItemList::Size().
The documentation for this class was generated from the following files:
StackDirectory.h
StackDirectory.cpp