Kodi Documentation: AddonsOperations.cpp File Reference
AddonsOperations.cpp File Reference
#include "AddonsOperations.h"
#include "JSONUtils.h"
#include "ServiceBroker.h"
#include "TextureCache.h"
#include "addons/AddonManager.h"
#include "addons/PluginSource.h"
#include "addons/addoninfo/AddonInfo.h"
#include "addons/addoninfo/AddonType.h"
#include "imagefiles/ImageFileURL.h"
#include "messaging/ApplicationMessenger.h"
#include "utils/FileUtils.h"
#include "utils/StringUtils.h"
#include "utils/Variant.h"
Functions
static CVariant Serialize (const AddonPtr &addon)
Function Documentation
Serialize()
static CVariant Serialize (const AddonPtr & addon) static
References ADDON::CAddonInfo::TranslateType(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by kodi::addon::CInstanceGame::ADDON_Serialize(), and JSONRPC::CAddonsOperations::FillDetails().