Kodi Documentation: KODI::RETRO::CGUIGameSettings Class Reference
KODI::RETRO::CGUIGameSettings Class Reference
#include <GUIGameSettings.h>
Public Member Functions
CGUIGameSettings (CRPProcessInfo &processInfo)
~CGUIGameSettings () override
CRenderSettings GetSettings () const override
Get the settings used to render this target.
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
Public Member Functions inherited from KODI::RETRO::IGUIRenderSettings
virtual ~IGUIRenderSettings ()=default
virtual bool HasVideoFilter () const
Returns true if this render target has a video filter set.
virtual bool HasStretchMode () const
Returns true if this render target has a stretch mode set.
virtual bool HasRotation () const
Returns true if this render target has a video rotation set.
virtual bool HasPixels () const
Returns true if this render target has a path to a savestate for showing pixel data.
virtual CRect GetDimensions () const
Get the dimensions of this target.
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Private Member Functions
void UpdateSettings ()
Private Attributes
CRPProcessInfo & m_processInfo
CGameSettings & m_guiSettings
CRenderSettings m_renderSettings
CCriticalSection m_mutex
Constructor & Destructor Documentation
CGUIGameSettings()
CGUIGameSettings::CGUIGameSettings (CRPProcessInfo & processInfo)
References KODI::RETRO::CRenderContext::GetDefaultGameSettings(), KODI::RETRO::CRPProcessInfo::GetRenderContext(), m_guiSettings, m_processInfo, Observable::RegisterObserver(), and UpdateSettings().
~CGUIGameSettings()
CGUIGameSettings::~CGUIGameSettings () override
References m_guiSettings, and Observable::UnregisterObserver().
Member Function Documentation
GetSettings()
CRenderSettings CGUIGameSettings::GetSettings () const override virtual
Get the settings used to render this target.
Returns
The render settings
Implements KODI::RETRO::IGUIRenderSettings.
References m_mutex, and m_renderSettings.
Notify()
void CGUIGameSettings::Notify (const Observable & obs, const ObservableMessage msg) override virtual
Process a message from an observable.
Parameters
obs The observable that sends the message.
msg The message.
Implements Observer.
References ObservableMessageSettingsChanged, and UpdateSettings().
UpdateSettings()
void CGUIGameSettings::UpdateSettings () private
References m_guiSettings, m_mutex, m_renderSettings, CGameSettings::RotationDegCCW(), KODI::RETRO::CRenderVideoSettings::SetRenderRotation(), KODI::RETRO::CRenderVideoSettings::SetRenderStretchMode(), KODI::RETRO::CRenderVideoSettings::SetVideoFilter(), CGameSettings::StretchMode(), CGameSettings::VideoFilter(), and KODI::RETRO::CRenderSettings::VideoSettings().
Referenced by CGUIGameSettings(), and Notify().
Member Data Documentation
m_guiSettings
CGameSettings& KODI::RETRO::CGUIGameSettings::m_guiSettings private
Referenced by CGUIGameSettings(), UpdateSettings(), and ~CGUIGameSettings().
m_mutex
CCriticalSection KODI::RETRO::CGUIGameSettings::m_mutex mutable private
Referenced by GetSettings(), and UpdateSettings().
m_processInfo
CRPProcessInfo& KODI::RETRO::CGUIGameSettings::m_processInfo private
Referenced by CGUIGameSettings().
m_renderSettings
CRenderSettings KODI::RETRO::CGUIGameSettings::m_renderSettings private
Referenced by GetSettings(), and UpdateSettings().
The documentation for this class was generated from the following files:
GUIGameSettings.h
GUIGameSettings.cpp