Kodi Documentation: WakeOnAccess.cpp File Reference
WakeOnAccess.cpp File Reference
#include "WakeOnAccess.h"
#include "DNSNameCache.h"
#include "ServiceBroker.h"
#include "application/ApplicationComponents.h"
#include "application/ApplicationPlayer.h"
#include "dialogs/GUIDialogKaiToast.h"
#include "dialogs/GUIDialogProgress.h"
#include "filesystem/SpecialProtocol.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "guilib/LocalizeStrings.h"
#include "messaging/ApplicationMessenger.h"
#include "network/Network.h"
#include "settings/AdvancedSettings.h"
#include "settings/MediaSourceSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "settings/lib/Setting.h"
#include "utils/JobManager.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/Variant.h"
#include "utils/XBMCTinyXML2.h"
#include "utils/XMLUtils.h"
#include "utils/XTimeUtils.h"
#include "utils/log.h"
#include <limits.h>
#include <mutex>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
Classes
struct UPnPServer
class CMACDiscoveryJob
class WaitCondition
class NestDetect
class ProgressDialogHelper
class NetworkStartWaiter
class PingResponseWaiter
class PingResponseWaiter::CHostProberJob
Macros
#define DEFAULT_NETWORK_INIT_SEC (20)
#define DEFAULT_NETWORK_SETTLE_MS (500)
#define DEFAULT_TIMEOUT_SEC (5*60)
#define DEFAULT_WAIT_FOR_ONLINE_SEC_1 (40)
#define DEFAULT_WAIT_FOR_ONLINE_SEC_2 (40)
#define DEFAULT_WAIT_FOR_SERVICES_SEC (5)
#define LOCALIZED(id) g_localizeStrings.Get(id)
Functions
static int GetTotalSeconds (const CDateTimeSpan &ts)
static unsigned long HostToIP (const std::string &host)
static void ShowDiscoveryMessage (const char *function, const char *server_name, bool new_entry)
static UPnPServer * LookupUPnPServer (std::vector< UPnPServer > &list, const std::string &uuid)
static void AddOrUpdateUPnPServer (std::vector< UPnPServer > &list, const UPnPServer &server)
static void AddMatchingUPnPServers (std::vector< UPnPServer > &list, const std::string &host, const std::string &mac, const CDateTimeSpan &wakeupDelay)
static std::string LookupUPnPHost (const std::string &uuid)
static void AddHost (const std::string &host, std::vector< std::string > &hosts)
static void AddHostFromDatabase (const DatabaseSettings &setting, std::vector< std::string > &hosts)
static void AddHostsFromMediaSource (const CMediaSource &source, std::vector< std::string > &hosts)
static void AddHostsFromVecSource (const std::vector< CMediaSource > &sources, std::vector< std::string > &hosts)
static void AddHostsFromVecSource (const std::vector< CMediaSource > *sources, std::vector< std::string > &hosts)
Variables
static CDateTime upnpInitReady
Macro Definition Documentation
DEFAULT_NETWORK_INIT_SEC
#define DEFAULT_NETWORK_INIT_SEC (20)
DEFAULT_NETWORK_SETTLE_MS
#define DEFAULT_NETWORK_SETTLE_MS (500)
DEFAULT_TIMEOUT_SEC
#define DEFAULT_TIMEOUT_SEC (5*60)
DEFAULT_WAIT_FOR_ONLINE_SEC_1
#define DEFAULT_WAIT_FOR_ONLINE_SEC_1 (40)
DEFAULT_WAIT_FOR_ONLINE_SEC_2
#define DEFAULT_WAIT_FOR_ONLINE_SEC_2 (40)
DEFAULT_WAIT_FOR_SERVICES_SEC
#define DEFAULT_WAIT_FOR_SERVICES_SEC (5)
LOCALIZED
#define LOCALIZED (id) g_localizeStrings.Get(id)
Function Documentation
AddHost()
static void AddHost (const std::string & host, std::vector< std::string > & hosts) static
References KODI::UTILS::StringUtils::EqualsNoCase().
Referenced by AddHostFromDatabase(), AddHostsFromMediaSource(), and CWakeOnAccess::QueueMACDiscoveryForAllRemotes().
AddHostFromDatabase()
static void AddHostFromDatabase (const DatabaseSettings & setting, std::vector< std::string > & hosts) static
References AddHost(), KODI::UTILS::StringUtils::EqualsNoCase(), DatabaseSettings::host, and DatabaseSettings::type.
Referenced by CWakeOnAccess::QueueMACDiscoveryForAllRemotes().
AddHostsFromMediaSource()
static void AddHostsFromMediaSource (const CMediaSource & source, std::vector< std::string > & hosts) static
References AddHost(), CURL::GetHostName(), CURL::IsProtocol(), LookupUPnPHost(), and CMediaSource::vecPaths.
Referenced by AddHostsFromVecSource().
AddHostsFromVecSource() [1/2]
static void AddHostsFromVecSource (const std::vector< CMediaSource > & sources, std::vector< std::string > & hosts) static
References AddHostsFromMediaSource().
Referenced by AddHostsFromVecSource(), and CWakeOnAccess::QueueMACDiscoveryForAllRemotes().
AddHostsFromVecSource() [2/2]
static void AddHostsFromVecSource (const std::vector< CMediaSource > * sources, std::vector< std::string > & hosts) static
References AddHostsFromVecSource().
AddMatchingUPnPServers()
static void AddMatchingUPnPServers (std::vector< UPnPServer > & list, const std::string & host, const std::string & mac, const CDateTimeSpan & wakeupDelay) static
References AddOrUpdateUPnPServer(), CDateTime::GetCurrentDateTime(), UPNP::CUPnP::GetInstance(), UPnPServer::m_mac, UPNP::CUPnP::m_MediaBrowser, UPnPServer::m_name, UPnPServer::m_nextWake, UPnPServer::m_uuid, KODI::TIME::Sleep(), and upnpInitReady.
Referenced by CWakeOnAccess::SaveMACDiscoveryResult().
AddOrUpdateUPnPServer()
static void AddOrUpdateUPnPServer (std::vector< UPnPServer > & list, const UPnPServer & server) static
References UPnPServer::m_name, and ShowDiscoveryMessage().
Referenced by AddMatchingUPnPServers().
GetTotalSeconds()
static int GetTotalSeconds (const CDateTimeSpan & ts) static
References CDateTimeSpan::GetDays(), CDateTimeSpan::GetHours(), CDateTimeSpan::GetMinutes(), and CDateTimeSpan::GetSeconds().
Referenced by CWakeOnAccess::LoadFromXML(), and CWakeOnAccess::SaveToXML().
HostToIP()
static unsigned long HostToIP (const std::string & host) static
References CDNSNameCache::Lookup().
Referenced by CMACDiscoveryJob::DoWork(), PingResponseWaiter::Ping(), NetworkStartWaiter::SuccessWaiting(), and CWakeOnAccess::WakeUpHost().
LookupUPnPHost()
static std::string LookupUPnPHost (const std::string & uuid) static
References CDateTime::GetCurrentDateTime(), UPNP::CUPnP::GetInstance(), UPNP::CUPnP::IsClientStarted(), UPNP::CUPnP::m_MediaBrowser, UPNP::CUPnP::StartClient(), and upnpInitReady.
Referenced by AddHostsFromMediaSource(), and PingResponseWaiter::Ping().
LookupUPnPServer()
static UPnPServer * LookupUPnPServer (std::vector< UPnPServer > & list, const std::string & uuid) static
Referenced by CWakeOnAccess::FindOrTouchHostEntry(), and CWakeOnAccess::TouchHostEntry().
ShowDiscoveryMessage()
static void ShowDiscoveryMessage (const char * function, const char * server_name, bool new_entry) static
References KODI::UTILS::StringUtils::Format(), CGUIDialogKaiToast::Info, LOCALIZED, CLog::Log(), LOGINFO, and CGUIDialogKaiToast::QueueNotification().
Referenced by AddOrUpdateUPnPServer(), and CWakeOnAccess::SaveMACDiscoveryResult().
Variable Documentation
upnpInitReady
CDateTime upnpInitReady static
Referenced by AddMatchingUPnPServers(), and LookupUPnPHost().