Kodi Documentation: CGUITexture Class Reference
CGUITexture Class Reference abstract
#include <GUITexture.h>
Public Member Functions
virtual ~CGUITexture ()=default
virtual CGUITexture * Clone () const =0
bool Process (unsigned int currentTime)
void Render (int32_t depthOffset=0, int32_t overrideDepth=-1)
void DynamicResourceAlloc (bool bOnOff)
bool AllocResources ()
void FreeResources (bool immediately=false)
void SetInvalid ()
bool SetVisible (bool visible)
bool SetAlpha (unsigned char alpha)
bool SetDiffuseColor (KODI::UTILS::COLOR::Color color, const CGUIListItem *item=nullptr)
bool SetPosition (float x, float y)
bool SetWidth (float width)
bool SetHeight (float height)
bool SetFileName (const std::string &filename)
void SetUseCache (const bool useCache=true)
bool SetAspectRatio (const CAspectRatio &aspect)
const std::string & GetFileName () const
float GetTextureWidth () const
float GetTextureHeight () const
float GetWidth () const
float GetHeight () const
float GetXPosition () const
float GetYPosition () const
int GetOrientation () const
const CRect & GetRenderRect () const
bool IsLazyLoaded () const
KODI::GUILIB::GUIINFO::CGUIInfoColor GetDiffuseColor () const
Get the diffuse color (info color) associated to this texture.
bool HitTest (const CPoint &point) const
bool IsAllocated () const
bool FailedToAlloc () const
bool ReadyToRender () const
Static Public Member Functions
static void Register (const CreateGUITextureFunc &createFunction, const DrawQuadFunc &drawQuadFunction)
static CGUITexture * CreateTexture (float posX, float posY, float width, float height, const CTextureInfo &texture)
static void DrawQuad (const CRect &coords, KODI::UTILS::COLOR::Color color, CTexture *texture=nullptr, const CRect *texCoords=nullptr, const float depth=1.0, const bool blending=true)
Protected Types
enum ALLOCATE_TYPE {
NO = 0 , NORMAL , LARGE , NORMAL_FAILED ,
LARGE_FAILED
}
Protected Member Functions
CGUITexture (float posX, float posY, float width, float height, const CTextureInfo &texture)
CGUITexture (const CGUITexture &left)
bool CalculateSize ()
bool AllocateOnDemand ()
bool UpdateAnimFrame (unsigned int currentTime)
void Render (float left, float top, float right, float bottom, float u1, float v1, float u2, float v2, float u3, float v3)
void ResetAnimState ()
virtual void Allocate ()
virtual void Free ()
called after our textures have been allocated
virtual void Begin (KODI::UTILS::COLOR::Color color)=0
called after our textures have been freed
virtual void Draw (float *x, float *y, float *z, const CRect &texture, const CRect &diffuse, int orientation)=0
virtual void End ()=0
Static Protected Member Functions
static void OrientateTexture (CRect &rect, float width, float height, int orientation)
Protected Attributes
bool m_visible
KODI::UTILS::COLOR::Color m_diffuseColor
float m_posX
float m_posY
float m_width
float m_height
float m_depth {0}
CRect m_vertex
bool m_invalid
bool m_use_cache
unsigned char m_alpha
float m_frameWidth
float m_frameHeight
float m_texCoordsScaleU
float m_texCoordsScaleV
int m_currentLoop
unsigned int m_currentFrame
uint32_t m_lasttime
float m_diffuseU
float m_diffuseV
float m_diffuseScaleU
float m_diffuseScaleV
CPoint m_diffuseOffset
bool m_allocateDynamically
ALLOCATE_TYPE m_isAllocated
CTextureInfo m_info
CAspectRatio m_aspect
CTextureArray m_diffuse
CTextureArray m_texture
Static Private Attributes
static CreateGUITextureFunc m_createGUITextureFunc
static DrawQuadFunc m_drawQuadFunc
Member Enumeration Documentation
ALLOCATE_TYPE
enum CGUITexture::ALLOCATE_TYPE protected
Enumerator
NO
NORMAL
LARGE
NORMAL_FAILED
LARGE_FAILED
Constructor & Destructor Documentation
~CGUITexture()
virtual CGUITexture::~CGUITexture () virtual default
CGUITexture() [1/2]
CGUITexture::CGUITexture (float posX, float posY, float width, float height, const CTextureInfo & texture) protected
References m_allocateDynamically, m_alpha, m_diffuseColor, m_diffuseScaleU, m_diffuseScaleV, m_diffuseU, m_diffuseV, m_frameHeight, m_frameWidth, m_height, m_invalid, m_isAllocated, m_posX, m_posY, m_texCoordsScaleU, m_texCoordsScaleV, m_use_cache, m_vertex, m_visible, m_width, NO, ResetAnimState(), and CRectGen< T >::SetRect().
CGUITexture() [2/2]
CGUITexture::CGUITexture (const CGUITexture & left) protected
References m_diffuseScaleU, m_diffuseScaleV, m_diffuseU, m_diffuseV, m_frameHeight, m_frameWidth, m_height, m_invalid, m_isAllocated, m_posX, m_posY, m_texCoordsScaleU, m_texCoordsScaleV, m_vertex, m_width, NO, ResetAnimState(), and CRectGen< T >::SetRect().
Member Function Documentation
Allocate()
virtual void CGUITexture::Allocate () inline protected virtual
Referenced by AllocResources().
AllocateOnDemand()
bool CGUITexture::AllocateOnDemand () protected
References AllocResources(), FreeResources(), IsAllocated(), LARGE, m_allocateDynamically, m_isAllocated, m_texture, m_visible, ResetAnimState(), and CTextureArray::size().
Referenced by Process().
AllocResources()
bool CGUITexture::AllocResources ()
References Allocate(), CalculateSize(), CGUITextureManager::CanLoad(), CTextureInfo::diffuse, CTextureInfo::filename, CServiceBroker::GetGUI(), CGUIComponent::GetTextureManager(), IsAllocated(), LARGE, LARGE_FAILED, CGUITextureManager::Load(), m_diffuse, m_frameHeight, m_frameWidth, CTextureArray::m_height, m_info, m_isAllocated, m_texture, m_use_cache, CTextureArray::m_width, NORMAL, NORMAL_FAILED, ResetAnimState(), CTextureArray::size(), and CTextureInfo::useLarge.
Referenced by AllocateOnDemand().
Begin()
virtual void CGUITexture::Begin (KODI::UTILS::COLOR::Color color) protected pure virtual
called after our textures have been freed
Implemented in CGUITextureD3D, CGUITextureGL, and CGUITextureGLES.
Referenced by Render().
CalculateSize()
bool CGUITexture::CalculateSize () protected
References CAspectRatio::align, CAspectRatio::AR_CENTER, CAspectRatio::AR_KEEP, CAspectRatio::AR_SCALE, CAspectRatio::AR_STRETCH, ASPECT_ALIGN_LEFT, ASPECT_ALIGN_RIGHT, ASPECT_ALIGNY_BOTTOM, ASPECT_ALIGNY_TOP, CWinSystemBase::GetGfxContext(), GetOrientation(), CGraphicContext::GetScalingPixelRatio(), CServiceBroker::GetWinSystem(), CRectGen< T >::Height(), m_aspect, m_currentFrame, m_diffuse, m_diffuseOffset, m_diffuseScaleU, m_diffuseScaleV, m_diffuseU, m_diffuseV, m_frameHeight, m_frameWidth, m_height, CTextureArray::m_height, m_invalid, m_posX, m_posY, CTextureArray::m_texCoordsArePixels, m_texCoordsScaleU, m_texCoordsScaleV, CTextureArray::m_texHeight, m_texture, CTextureArray::m_texWidth, m_vertex, m_width, CTextureArray::m_width, CAspectRatio::ratio, CAspectRatio::scaleDiffuse, CRectGen< T >::SetRect(), CTextureArray::size(), CRectGen< T >::Width(), CRectGen< T >::x1, and CRectGen< T >::y1.
Referenced by AllocResources(), and Process().
Clone()
virtual CGUITexture * CGUITexture::Clone () const pure virtual
Implemented in CGUITextureD3D, CGUITextureGL, and CGUITextureGLES.
Referenced by CGUIImage::CFadingTexture::CFadingTexture().
CreateTexture()
CGUITexture * CGUITexture::CreateTexture (float posX, float posY, float width, float height, const CTextureInfo & texture) static
References m_createGUITextureFunc.
Draw()
virtual void CGUITexture::Draw (float * x, float * y, float * z, const CRect & texture, const CRect & diffuse, int orientation) protected pure virtual
Implemented in CGUITextureD3D, CGUITextureGL, and CGUITextureGLES.
Referenced by Render().
DrawQuad()
void CGUITexture::DrawQuad (const CRect & coords, KODI::UTILS::COLOR::Color color, CTexture * texture = nullptr, const CRect * texCoords = nullptr, const float depth = 1.0, const bool blending = true) static
References color, CServiceBroker::GetWinSystem(), m_drawQuadFunc, and RENDER_ORDER_FRONT_TO_BACK.
Referenced by CGUIControl::DoRender(), CGUIWindowManager::Render(), CGUIVideoControl::Render(), CGUIDialogTeletext::Render(), CGUIWindowScreensaver::Render(), and CGUIWindowScreensaverDim::Render().
DynamicResourceAlloc()
void CGUITexture::DynamicResourceAlloc (bool bOnOff)
References m_allocateDynamically.
End()
virtual void CGUITexture::End () protected pure virtual
Implemented in CGUITextureD3D, CGUITextureGL, and CGUITextureGLES.
Referenced by Render().
FailedToAlloc()
bool CGUITexture::FailedToAlloc () const inline
References LARGE_FAILED, m_isAllocated, and NORMAL_FAILED.
Free()
virtual void CGUITexture::Free () inline protected virtual
called after our textures have been allocated
Referenced by FreeResources().
FreeResources()
void CGUITexture::FreeResources (bool immediately = false)
References CTextureInfo::diffuse, CTextureInfo::filename, Free(), CServiceBroker::GetGUI(), CGUIComponent::GetLargeTextureManager(), CGUIComponent::GetTextureManager(), LARGE, LARGE_FAILED, m_diffuse, m_info, m_isAllocated, m_texCoordsScaleU, m_texCoordsScaleV, m_texture, NO, NORMAL, CGUILargeTextureManager::ReleaseImage(), CGUITextureManager::ReleaseTexture(), CTextureArray::Reset(), ResetAnimState(), and CTextureArray::size().
Referenced by AllocateOnDemand(), and SetFileName().
GetDiffuseColor()
KODI::GUILIB::GUIINFO::CGUIInfoColor CGUITexture::GetDiffuseColor () const inline
Get the diffuse color (info color) associated to this texture.
Returns
the infocolor associated to this texture
References CTextureInfo::diffuseColor, and m_info.
GetFileName()
const std::string & CGUITexture::GetFileName () const inline
References CTextureInfo::filename, and m_info.
GetHeight()
float CGUITexture::GetHeight () const inline
References m_height.
Referenced by CGUISliderControl::ProcessSelector().
GetOrientation()
int CGUITexture::GetOrientation () const
References m_info, CTextureArray::m_orientation, m_texture, and CTextureInfo::orientation.
Referenced by CalculateSize(), and Render().
GetRenderRect()
const CRect & CGUITexture::GetRenderRect () const inline
References m_vertex.
Referenced by CGUISliderControl::ProcessSelector().
GetTextureHeight()
float CGUITexture::GetTextureHeight () const inline
References m_frameHeight.
Referenced by CGUISliderControl::Process(), and CGUISliderControl::ProcessSelector().
GetTextureWidth()
float CGUITexture::GetTextureWidth () const inline
References m_frameWidth.
Referenced by CGUISliderControl::Process(), and CGUISliderControl::ProcessSelector().
GetWidth()
float CGUITexture::GetWidth () const inline
References m_width.
Referenced by CGUISliderControl::ProcessSelector().
GetXPosition()
float CGUITexture::GetXPosition () const inline
References m_posX.
Referenced by CGUISliderControl::ProcessSelector().
GetYPosition()
float CGUITexture::GetYPosition () const inline
References m_posY.
Referenced by CGUISliderControl::ProcessSelector().
HitTest()
bool CGUITexture::HitTest (const CPoint & point) const inline
References m_height, m_posX, m_posY, m_width, and CRectGen< T >::PtInRect().
IsAllocated()
bool CGUITexture::IsAllocated () const inline
References m_isAllocated, and NO.
Referenced by AllocateOnDemand(), and AllocResources().
IsLazyLoaded()
bool CGUITexture::IsLazyLoaded () const inline
References m_info, and CTextureInfo::useLarge.
OrientateTexture()
void CGUITexture::OrientateTexture (CRect & rect, float width, float height, int orientation) static protected
References CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by Render().
Process()
bool CGUITexture::Process (unsigned int currentTime)
References AllocateOnDemand(), CalculateSize(), m_invalid, m_isAllocated, m_texture, ReadyToRender(), CTextureArray::size(), and UpdateAnimFrame().
Referenced by CGUISliderControl::Process(), and CGUISliderControl::ProcessSelector().
ReadyToRender()
bool CGUITexture::ReadyToRender () const
References m_texture, and CTextureArray::size().
Referenced by Process().
Register()
void CGUITexture::Register (const CreateGUITextureFunc & createFunction, const DrawQuadFunc & drawQuadFunction) static
References m_createGUITextureFunc, and m_drawQuadFunc.
Referenced by CGUITextureD3D::Register(), CGUITextureGL::Register(), and CGUITextureGLES::Register().
Render() [1/2]
void CGUITexture::Render (float left, float top, float right, float bottom, float u1, float v1, float u2, float v2, float u3, float v3) protected
References CGraphicContext::ClipRect(), Draw(), CWinSystemBase::GetGfxContext(), GetOrientation(), CServiceBroker::GetWinSystem(), CRectGen< T >::IsEmpty(), left, m_diffuse, m_diffuseOffset, m_diffuseScaleU, m_diffuseScaleV, m_diffuseU, m_diffuseV, m_info, OrientateTexture(), CTextureInfo::orientation, right, ROUND_TO_PIXEL, CTextureArray::size(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Render() [2/2]
void CGUITexture::Render (int32_t depthOffset = 0, int32_t overrideDepth = -1)
Todo:
The diffuse coloring applies to all vertices, which will look weird for stuff with borders, as will the -ve height/width for flipping
References Begin(), CTextureInfo::border, color, CTextureInfo::diffuseColor, End(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetNormalizedDepth(), CGraphicContext::GetRenderOrder(), CGraphicContext::GetTransformDepth(), CServiceBroker::GetWinSystem(), CRectGen< T >::Height(), m_alpha, m_currentFrame, m_depth, m_diffuse, m_diffuseColor, m_frameHeight, m_frameWidth, m_height, CTextureInfo::m_infill, m_info, m_posX, m_posY, CTextureArray::m_texCoordsArePixels, m_texCoordsScaleU, m_texCoordsScaleV, m_texture, CTextureArray::m_textures, m_vertex, m_visible, m_width, CGraphicContext::MergeColor(), MIX_ALPHA, Render(), RENDER_ORDER_BACK_TO_FRONT, RENDER_ORDER_FRONT_TO_BACK, CGraphicContext::RestoreClipRegion(), CTextureArray::size(), CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUISliderControl::Render(), and Render().
ResetAnimState()
void CGUITexture::ResetAnimState () protected
References m_currentFrame, m_currentLoop, and m_lasttime.
Referenced by AllocateOnDemand(), AllocResources(), CGUITexture(), CGUITexture(), and FreeResources().
SetAlpha()
bool CGUITexture::SetAlpha (unsigned char alpha)
References m_alpha.
SetAspectRatio()
bool CGUITexture::SetAspectRatio (const CAspectRatio & aspect)
References m_aspect, and m_invalid.
Referenced by CGUISliderControl::ProcessSelector().
SetDiffuseColor()
bool CGUITexture::SetDiffuseColor (KODI::UTILS::COLOR::Color color, const CGUIListItem * item = nullptr)
References color, CTextureInfo::diffuseColor, m_diffuseColor, m_info, and KODI::GUILIB::GUIINFO::CGUIInfoColor::Update().
SetFileName()
bool CGUITexture::SetFileName (const std::string & filename)
References CTextureInfo::filename, FreeResources(), m_info, SetUseCache(), and CTextureInfo::useLarge.
SetHeight()
bool CGUITexture::SetHeight (float height)
References CTextureInfo::border, m_height, m_info, m_invalid, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUISliderControl::Process(), and CGUISliderControl::ProcessSelector().
SetInvalid()
void CGUITexture::SetInvalid ()
References m_invalid.
SetPosition()
bool CGUITexture::SetPosition (float x, float y)
References m_invalid, m_posX, and m_posY.
Referenced by CGUISliderControl::Process(), and CGUISliderControl::ProcessSelector().
SetUseCache()
void CGUITexture::SetUseCache (const bool useCache = true)
References m_use_cache.
Referenced by SetFileName().
SetVisible()
bool CGUITexture::SetVisible (bool visible)
References m_visible.
SetWidth()
bool CGUITexture::SetWidth (float width)
References CTextureInfo::border, m_info, m_invalid, m_width, CRectGen< T >::x1, and CRectGen< T >::x2.
Referenced by CGUISliderControl::Process(), and CGUISliderControl::ProcessSelector().
UpdateAnimFrame()
bool CGUITexture::UpdateAnimFrame (unsigned int currentTime) protected
References m_currentFrame, m_currentLoop, CTextureArray::m_delays, m_lasttime, CTextureArray::m_loops, m_texture, and CTextureArray::size().
Referenced by Process().
Member Data Documentation
m_allocateDynamically
bool CGUITexture::m_allocateDynamically protected
Referenced by AllocateOnDemand(), CGUITexture(), and DynamicResourceAlloc().
m_alpha
unsigned char CGUITexture::m_alpha protected
Referenced by CGUITexture(), Render(), and SetAlpha().
m_aspect
CAspectRatio CGUITexture::m_aspect protected
Referenced by CalculateSize(), and SetAspectRatio().
m_createGUITextureFunc
CreateGUITextureFunc CGUITexture::m_createGUITextureFunc static private
Referenced by CreateTexture(), and Register().
m_currentFrame
unsigned int CGUITexture::m_currentFrame protected
Referenced by CGUITextureD3D::Begin(), CGUITextureGL::Begin(), CGUITextureGLES::Begin(), CalculateSize(), CGUITextureD3D::Draw(), Render(), ResetAnimState(), and UpdateAnimFrame().
m_currentLoop
int CGUITexture::m_currentLoop protected
Referenced by ResetAnimState(), and UpdateAnimFrame().
m_depth
float CGUITexture::m_depth {0} protected
Referenced by CGUITextureGL::End(), CGUITextureGLES::End(), and Render().
m_diffuse
CTextureArray CGUITexture::m_diffuse protected
Referenced by AllocResources(), CGUITextureD3D::Begin(), CGUITextureGL::Begin(), CGUITextureGLES::Begin(), CalculateSize(), CGUITextureD3D::Draw(), CGUITextureGL::Draw(), CGUITextureGLES::Draw(), CGUITextureGL::End(), CGUITextureGLES::End(), FreeResources(), Render(), and Render().
m_diffuseColor
KODI::UTILS::COLOR::Color CGUITexture::m_diffuseColor protected
Referenced by CGUITexture(), Render(), and SetDiffuseColor().
m_diffuseOffset
CPoint CGUITexture::m_diffuseOffset protected
Referenced by CalculateSize(), and Render().
m_diffuseScaleU
float CGUITexture::m_diffuseScaleU protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), and Render().
m_diffuseScaleV
float CGUITexture::m_diffuseScaleV protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), and Render().
m_diffuseU
float CGUITexture::m_diffuseU protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), and Render().
m_diffuseV
float CGUITexture::m_diffuseV protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), and Render().
m_drawQuadFunc
DrawQuadFunc CGUITexture::m_drawQuadFunc static private
Referenced by DrawQuad(), and Register().
m_frameHeight
float CGUITexture::m_frameHeight protected
Referenced by AllocResources(), CalculateSize(), CGUITexture(), CGUITexture(), GetTextureHeight(), and Render().
m_frameWidth
float CGUITexture::m_frameWidth protected
Referenced by AllocResources(), CalculateSize(), CGUITexture(), CGUITexture(), GetTextureWidth(), and Render().
m_height
float CGUITexture::m_height protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), GetHeight(), HitTest(), Render(), and SetHeight().
m_info
CTextureInfo CGUITexture::m_info protected
Referenced by AllocResources(), CGUITextureD3D::Draw(), CGUITextureGL::Draw(), CGUITextureGLES::Draw(), FreeResources(), GetDiffuseColor(), GetFileName(), GetOrientation(), IsLazyLoaded(), Render(), Render(), SetDiffuseColor(), SetFileName(), SetHeight(), and SetWidth().
m_invalid
bool CGUITexture::m_invalid protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), Process(), SetAspectRatio(), SetHeight(), SetInvalid(), SetPosition(), and SetWidth().
m_isAllocated
ALLOCATE_TYPE CGUITexture::m_isAllocated protected
Referenced by AllocateOnDemand(), AllocResources(), CGUITexture(), CGUITexture(), FailedToAlloc(), FreeResources(), IsAllocated(), and Process().
m_lasttime
uint32_t CGUITexture::m_lasttime protected
Referenced by ResetAnimState(), and UpdateAnimFrame().
m_posX
float CGUITexture::m_posX protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), GetXPosition(), HitTest(), Render(), and SetPosition().
m_posY
float CGUITexture::m_posY protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), GetYPosition(), HitTest(), Render(), and SetPosition().
m_texCoordsScaleU
float CGUITexture::m_texCoordsScaleU protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), FreeResources(), and Render().
m_texCoordsScaleV
float CGUITexture::m_texCoordsScaleV protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), FreeResources(), and Render().
m_texture
CTextureArray CGUITexture::m_texture protected
Referenced by AllocateOnDemand(), AllocResources(), CGUITextureD3D::Begin(), CGUITextureGL::Begin(), CGUITextureGLES::Begin(), CalculateSize(), CGUITextureD3D::Draw(), FreeResources(), GetOrientation(), Process(), ReadyToRender(), Render(), and UpdateAnimFrame().
m_use_cache
bool CGUITexture::m_use_cache protected
Referenced by AllocResources(), CGUITexture(), and SetUseCache().
m_vertex
CRect CGUITexture::m_vertex protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), GetRenderRect(), and Render().
m_visible
bool CGUITexture::m_visible protected
Referenced by AllocateOnDemand(), CGUITexture(), Render(), and SetVisible().
m_width
float CGUITexture::m_width protected
Referenced by CalculateSize(), CGUITexture(), CGUITexture(), GetWidth(), HitTest(), Render(), and SetWidth().
The documentation for this class was generated from the following files:
GUITexture.h
GUITexture.cpp