Kodi Documentation: CInputManager Class Reference
CInputManager Class Reference
Input | Input » Keyboard | Input » Mouse | Input » Touch | Input » Joystick
Main input processing class.
#include <InputManager.h>
Public Member Functions
CInputManager ()
CInputManager (const CInputManager &)=delete
CInputManager const & operator= (CInputManager const &)=delete
~CInputManager () override
bool ProcessMouse (int windowId)
decode a mouse event and reset idle timers.
bool ProcessEventServer (int windowId, float frameTime)
decode an event from the event service, this can be mouse, key, joystick, reset idle timers.
bool ProcessPeripherals (float frameTime)
decode an event from peripherals.
bool Process (int windowId, float frameTime)
Process all inputs.
void InitializeInputs ()
Call once during application startup to initialize peripherals that need it.
void Deinitialize ()
Deinitialize input and keymaps.
bool OnEvent (XBMC_Event &newEvent)
Handle an input event.
void SetMouseActive (bool active=true)
Control if the mouse is actively used or not.
void SetMouseEnabled (bool mouseEnabled=true)
Control if we should use a mouse or not.
void SetMouseState (MOUSE_STATE mouseState)
Set the current state of the mouse such as click, drag operation.
bool IsMouseActive ()
Check if the mouse is currently active.
MOUSE_STATE GetMouseState ()
Get the current state of the mouse, such as click or drag operation.
MousePosition GetMousePosition ()
Get the current mouse positions x and y coordinates.
void SetMouseResolution (int maxX, int maxY, float speedX, float speedY)
Set the current screen resolution and pointer speed.
bool IsControllerEnabled () const
Get the status of the controller-enable setting.
bool HasBuiltin (const std::string &command)
Returns whether or not we can handle a given built-in command.
int ExecuteBuiltin (const std::string &execute, const std::vector< std::string > &params)
Parse a builtin command and execute any input action currently only LIRC commands implemented.
bool LoadKeymaps ()
bool ReloadKeymaps ()
void ClearKeymaps ()
void AddKeymap (const std::string &keymap)
void RemoveKeymap (const std::string &keymap)
const KODI::KEYMAP::IKeymapEnvironment * KeymapEnvironment () const
CAction GetAction (int window, const CKey &key, bool fallback=true)
Obtain the action configured for a given window and key.
bool TranslateCustomControllerString (int windowId, const std::string &controllerName, int buttonId, int &action, std::string &strAction)
bool TranslateTouchAction (int windowId, int touchAction, int touchPointers, int &action, std::string &actionString)
std::vector< std::shared_ptr< const KODI::KEYMAP::IWindowKeymap > > GetJoystickKeymaps () const
void QueueAction (const CAction &action)
Queue an action to be processed on the next call to Process()
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
bool OnAction (const CAction &action) override
Handle a GUI action.
void RegisterKeyboardDriverHandler (KODI::KEYBOARD::IKeyboardDriverHandler *handler)
void UnregisterKeyboardDriverHandler (KODI::KEYBOARD::IKeyboardDriverHandler *handler)
virtual void RegisterMouseDriverHandler (KODI::MOUSE::IMouseDriverHandler *handler)
virtual void UnregisterMouseDriverHandler (KODI::MOUSE::IMouseDriverHandler *handler)
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from KODI::ACTION::IActionListener
virtual ~IActionListener ()=default
Public Member Functions inherited from Observable
Observable ()=default
virtual ~Observable ()=default
Observable & operator= (const Observable &observable)
virtual void RegisterObserver (Observer *obs)
Register an observer.
virtual void UnregisterObserver (Observer *obs)
Unregister an observer.
virtual void NotifyObservers (const ObservableMessage message=ObservableMessageNone)
Send a message to all observers when m_bObservableChanged is true.
virtual void SetChanged (bool bSetTo=true)
Mark an observable changed.
virtual bool IsObserving (const Observer &obs) const
Check whether this observable is being observed by an observer.
Private Member Functions
bool OnKey (const CKey &key)
Process keyboard event and translate into an action.
void OnKeyUp (const CKey &key)
Process key up event.
bool HandleKey (const CKey &key)
Handle keypress.
bool AlwaysProcess (const CAction &action)
Determine if an action should be processed or just cancel the screensaver.
bool ExecuteInputAction (const CAction &action)
Send the Action to CApplication for further handling, play a sound before or after sending the action.
void ProcessQueuedActions ()
Dispatch actions queued since the last call to Process()
Private Attributes
KODI::KEYBOARD::CKeyboardStat m_Keyboard
KODI::KEYMAP::CButtonStat m_buttonStat
CMouseStat m_Mouse
CKey m_LastKey
std::map< std::string, std::map< int, float > > m_lastAxisMap
std::vector< CAction > m_queuedActions
CCriticalSection m_actionMutex
std::unique_ptr< KODI::KEYMAP::IKeymapEnvironment > m_keymapEnvironment
std::unique_ptr< KODI::KEYMAP::CButtonTranslator > m_buttonTranslator
std::unique_ptr< KODI::KEYMAP::CCustomControllerTranslator > m_customControllerTranslator
std::unique_ptr< KODI::KEYMAP::CTouchTranslator > m_touchTranslator
std::unique_ptr< KODI::KEYMAP::CJoystickMapper > m_joystickTranslator
std::vector< KODI::KEYBOARD::IKeyboardDriverHandler * > m_keyboardHandlers
std::vector< KODI::MOUSE::IMouseDriverHandler * > m_mouseHandlers
std::unique_ptr< KODI::KEYBOARD::IKeyboardDriverHandler > m_keyboardEasterEgg
bool m_enableController = true
Static Private Attributes
static const std::string SETTING_INPUT_ENABLE_CONTROLLER = "input.enablejoystick"
Additional Inherited Members
Protected Member Functions inherited from Observable
void SendMessage (const ObservableMessage message)
Send a message to all observer when m_bObservableChanged is true.
Protected Attributes inherited from Observable
std::atomic< bool > m_bObservableChanged {false}
std::vector< Observer * > m_observers
CCriticalSection m_obsCritSection
Detailed Description
Main input processing class.
This class consolidates all input generated from different sources such as mouse, keyboard, joystick or touch (in OnEvent).
Keyboard input is processed by CInputManager and forwarded to registered keyboard handlers (e.g. game clients) or as actions to the UI:
If no keyboard handlers are registered or if they don't consume events, the keyboard events are forwarded to the UI via CInputManager::OnKey.
Clients (e.g. game clients implementing KEYBOARD::IKeyboardHandler) call CInputManager::RegisterKeyboardHandler to register themselves as eligible for keyboard input events.
Keyboards can emulate Joysticks as described in KEYBOARD::CJoystickEmulation.
Everything around mouse
Mouse input is processed by CInputManager and forwarded to registered mouse handlers (e.g. game clients) or as actions to the UI:
If no mouse handlers are registered or if they don't consume events, the mouse input events are forwarded to the UI via CInputManager::ProcessMouse.
Clients (e.g. game clients implementing MOUSE::IMouseInputHandler) call CInputManager::RegisterMouseHandler to register themselves as eligible for mouse input events.
Mouse events (from CInputManager::OnEvent) are collected via implementations of MOUSE::IMouseDriverHandler and transformed into higher level features by MOUSE::IMouseButtonMap instances before they are sent to the handlers.
Constructor & Destructor Documentation
CInputManager() [1/2]
CInputManager::CInputManager ()
References CServiceBroker::GetSettingsComponent(), m_buttonTranslator, m_customControllerTranslator, m_joystickTranslator, m_keyboardEasterEgg, m_touchTranslator, RegisterKeyboardDriverHandler(), SETTING_INPUT_ENABLE_CONTROLLER, and CSettings::SETTING_INPUT_ENABLEMOUSE.
CInputManager() [2/2]
CInputManager::CInputManager (const CInputManager &) delete
~CInputManager()
CInputManager::~CInputManager () override
References Deinitialize(), CServiceBroker::GetSettingsComponent(), m_buttonTranslator, m_customControllerTranslator, m_joystickTranslator, m_keyboardEasterEgg, m_touchTranslator, and UnregisterKeyboardDriverHandler().
Member Function Documentation
AddKeymap()
void CInputManager::AddKeymap (const std::string & keymap)
References m_buttonTranslator, Observable::NotifyObservers(), ObservableMessageButtonMapsChanged, and Observable::SetChanged().
Referenced by PERIPHERALS::CPeripheralHID::InitialiseFeature().
AlwaysProcess()
bool CInputManager::AlwaysProcess (const CAction & action) private
Determine if an action should be processed or just cancel the screensaver.
Parameters
action Action that is about to be processed
Returns
true on any poweractions such as shutdown/reboot/sleep/suspend, false otherwise
See also
CAction
References CExecString::GetFunction(), and CExecString::IsValid().
Referenced by HandleKey().
ClearKeymaps()
void CInputManager::ClearKeymaps ()
References m_buttonTranslator, Observable::NotifyObservers(), ObservableMessageButtonMapsChanged, and Observable::SetChanged().
Deinitialize()
void CInputManager::Deinitialize ()
Deinitialize input and keymaps.
Referenced by ~CInputManager().
ExecuteBuiltin()
int CInputManager::ExecuteBuiltin (const std::string & execute, const std::vector< std::string > & params)
Parse a builtin command and execute any input action currently only LIRC commands implemented.
Parameters
[in] execute Command to execute
[in] params parameters that was passed to the command
Returns
0 on success, -1 on failure
Referenced by CBuiltins::Execute().
ExecuteInputAction()
bool CInputManager::ExecuteInputAction (const CAction & action) private
Send the Action to CApplication for further handling, play a sound before or after sending the action.
Parameters
action Action to send to CApplication
Returns
result from CApplication::OnAction
See also
CAction
References g_application, CGUIComponent::GetAudioManager(), CServiceBroker::GetGUI(), and CGUIAudioManager::PlayActionSound().
Referenced by HandleKey(), OnEvent(), and ProcessEventServer().
GetAction()
CAction CInputManager::GetAction (int window, const CKey & key, bool fallback = true)
Obtain the action configured for a given window and key.
Parameters
window the window id
key the key to query the action for
fallback if no action is directly configured for the given window, obtain the action from fallback window, if exists or from global config as last resort
Returns
the action matching the key
References m_buttonTranslator.
Referenced by KODI::KEYMAP::CKeyboardActionMap::GetActionID(), and CWinEventsWin32::WndProc().
GetJoystickKeymaps()
std::vector< std::shared_ptr< const KEYMAP::IWindowKeymap > > CInputManager::GetJoystickKeymaps () const
References m_joystickTranslator.
GetMousePosition()
MousePosition CInputManager::GetMousePosition ()
Get the current mouse positions x and y coordinates.
Returns
a struct containing the x and y coordinates
See also
MousePosition
References CMouseStat::GetPosition(), and m_Mouse.
Referenced by CGUIWindowPointer::Process().
GetMouseState()
MOUSE_STATE CInputManager::GetMouseState ()
Get the current state of the mouse, such as click or drag operation.
Returns
the current state of the mouse as a value from MOUSE_STATE
See also
MOUSE_STATE
References CMouseStat::GetState(), and m_Mouse.
HandleKey()
bool CInputManager::HandleKey (const CKey & key) private
Handle keypress.
Parameters
key keypress details
Returns
true on successfully handled event
References ACTION_BACKSPACE, ACTION_CURSOR_LEFT, ACTION_CURSOR_RIGHT, ACTION_ENTER, ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NAV_BACK, ACTION_PASTE, ACTION_PREVIOUS_MENU, ACTION_SELECT_ITEM, ACTION_SHIFT, ACTION_SYMBOLS, ACTION_VOICE_RECOGNIZE, AlwaysProcess(), ExecuteInputAction(), CKey::FromKeyboard(), g_application, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CKey::GetButtonCode(), CGUIControl::GetControlType(), CGUIControlGroup::GetFocusedControl(), CKey::GetFromService(), CServiceBroker::GetGUI(), KODI::KEYBOARD::CKeyboardStat::GetKeyName(), CKey::GetModifiers(), CKey::GetUnicode(), CKey::GetVKey(), CGUIComponent::GetWindowManager(), CGUIControl::GUICONTROL_EDIT, CKey::IsAnalogButton(), CGUIControl::IsContainer(), KEY_INVALID, KEY_UNICODE, KEY_VKEY, LOGDEBUG, m_buttonTranslator, m_Keyboard, m_Mouse, CKey::MODIFIER_CTRL, CKey::MODIFIER_META, CKey::MODIFIER_SHIFT, REMOTE_0, REMOTE_9, CApplicationPowerHandling::ResetSystemIdleTimer(), CMouseStat::SetActive(), TMSG_CECSTANDBY, TMSG_CECTOGGLESTATE, WINDOW_DIALOG_KEYBOARD, WINDOW_DIALOG_NUMERIC, WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, and XBMCVK_V.
Referenced by OnEvent(), OnKey(), and OnKeyUp().
HasBuiltin()
bool CInputManager::HasBuiltin (const std::string & command)
Returns whether or not we can handle a given built-in command.
InitializeInputs()
void CInputManager::InitializeInputs ()
Call once during application startup to initialize peripherals that need it.
References CServiceBroker::GetSettingsComponent(), KODI::KEYBOARD::CKeyboardStat::Initialize(), CMouseStat::Initialize(), m_enableController, m_Keyboard, m_Mouse, CMouseStat::SetEnabled(), SETTING_INPUT_ENABLE_CONTROLLER, and CSettings::SETTING_INPUT_ENABLEMOUSE.
IsControllerEnabled()
bool CInputManager::IsControllerEnabled () const
Get the status of the controller-enable setting.
Returns
True if controller input is enabled for the UI, false otherwise
References m_enableController.
Referenced by PERIPHERALS::CPeripheralJoystick::OnAxisMotion(), PERIPHERALS::CPeripheralJoystick::OnButtonMotion(), and PERIPHERALS::CPeripheralJoystick::OnHatMotion().
IsMouseActive()
bool CInputManager::IsMouseActive ()
Check if the mouse is currently active.
Returns
true if active, false otherwise
References CMouseStat::IsActive(), and m_Mouse.
Referenced by CGUIWindowPointer::Process().
KeymapEnvironment()
const KEYMAP::IKeymapEnvironment * CInputManager::KeymapEnvironment () const
References m_keymapEnvironment.
Referenced by PERIPHERALS::CPeripheralJoystick::InitialiseFeature().
LoadKeymaps()
bool CInputManager::LoadKeymaps ()
References m_buttonTranslator, Observable::NotifyObservers(), ObservableMessageButtonMapsChanged, and Observable::SetChanged().
Referenced by CProfileManager::LoadProfile(), and ReloadKeymaps().
OnAction()
bool CInputManager::OnAction (const CAction & action) override virtual
Handle a GUI action.
Parameters
action The GUI action
Returns
True if the action was handled, false otherwise
Implements KODI::ACTION::IActionListener.
References ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NONE, ACTION_PAGE_DOWN, ACTION_PAGE_UP, and QueueAction().
OnEvent()
bool CInputManager::OnEvent (XBMC_Event & newEvent)
Handle an input event.
Parameters
newEvent event details
Returns
true on successfully handled event
See also
XBMC_Event
References XBMC_TouchEvent::action, ACTION_BUILT_IN_FUNCTION, ACTION_GESTURE_ABORT, ACTION_GESTURE_BEGIN, ACTION_GESTURE_END, ACTION_MOUSE_END, ACTION_MOUSE_MOVE, ACTION_MOUSE_START, ACTION_TOUCH_TAP, XBMC_MouseButtonEvent::button, XBMC_ButtonEvent::button, XBMC_Event::button, ExecuteInputAction(), g_application, CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CMouseStat::HandleEvent(), HandleKey(), XBMC_ButtonEvent::holdtime, XBMC_Event::key, XBMC_Event::keybutton, XBMC_KeyboardEvent::keysym, m_buttonStat, m_Keyboard, m_Mouse, m_mouseHandlers, m_touchTranslator, XBMC_Event::motion, OnKey(), OnKeyUp(), XBMC_TouchEvent::pointers, KODI::KEYBOARD::CKeyboardStat::ProcessKeyDown(), KODI::KEYBOARD::CKeyboardStat::ProcessKeyUp(), ProcessMouse(), TMSG_GUI_ACTION, XBMC_Event::touch, CMouseTranslator::TranslateEventID(), KODI::KEYMAP::CButtonStat::TranslateKey(), KODI::KEYBOARD::CKeyboardStat::TranslateKey(), XBMC_Event::type, XBMC_keysym::unicode, WINDOW_INVALID, XBMC_MouseMotionEvent::x, XBMC_TouchEvent::x, XBMC_TouchEvent::x2, XBMC_TouchEvent::x3, XBMC_BUTTON, XBMC_KEYCOMPOSING_CANCELLED, XBMC_KEYCOMPOSING_COMPOSING, XBMC_KEYCOMPOSING_FINISHED, XBMC_KEYDOWN, XBMC_KEYUP, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, XBMC_MOUSEMOTION, XBMC_TOUCH, XBMC_MouseMotionEvent::y, XBMC_TouchEvent::y, XBMC_TouchEvent::y2, and XBMC_TouchEvent::y3.
Referenced by CAppInboundProtocol::HandleEvents().
OnKey()
bool CInputManager::OnKey (const CKey & key) private
Process keyboard event and translate into an action.
Parameters
key keypress details
Returns
true on successfully handled event
See also
CKey
References CKey::GetButtonCode(), CKey::GetFromService(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), HandleKey(), m_buttonTranslator, m_keyboardHandlers, m_LastKey, CKey::MODIFIER_LONG, and CKey::Reset().
Referenced by OnEvent(), ProcessEventServer(), and ProcessPeripherals().
OnKeyUp()
void CInputManager::OnKeyUp (const CKey & key) private
Process key up event.
Parameters
key details of released key
See also
CKey
References CKey::GetButtonCode(), HandleKey(), KEY_INVALID, m_keyboardHandlers, m_LastKey, CKey::MODIFIER_LONG, and CKey::Reset().
Referenced by OnEvent().
OnSettingChanged()
void CInputManager::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References GetValue(), m_enableController, m_Mouse, CMouseStat::SetEnabled(), SETTING_INPUT_ENABLE_CONTROLLER, and CSettings::SETTING_INPUT_ENABLEMOUSE.
operator=()
CInputManager const & CInputManager::operator= (CInputManager const &) delete
Process()
bool CInputManager::Process (int windowId, float frameTime)
Process all inputs.
Parameters
windowId Currently active window
frameTime Time in seconds since last call
Returns
true on success, false otherwise
References m_keymapEnvironment, ProcessEventServer(), ProcessPeripherals(), and ProcessQueuedActions().
Referenced by CApplication::FrameMove().
ProcessEventServer()
bool CInputManager::ProcessEventServer (int windowId, float frameTime)
decode an event from the event service, this can be mouse, key, joystick, reset idle timers.
Parameters
windowId Currently active window
frameTime Time in seconds since last call
Returns
true if event is handled, false otherwise
References ACTION_MOUSE_MOVE, ES_FLAG_UNICODE, ExecuteInputAction(), EVENTSERVER::CEventServer::ExecuteNextAction(), g_application, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppPort(), EVENTSERVER::CEventServer::GetButtonCode(), EVENTSERVER::CEventServer::GetMousePos(), EVENTSERVER::CEventServer::GetNumberOfClients(), CMouseStat::IsEnabled(), KEY_BUTTON_LEFT_ANALOG_TRIGGER, KEY_BUTTON_LEFT_THUMB_STICK_DOWN, KEY_BUTTON_LEFT_THUMB_STICK_LEFT, KEY_BUTTON_LEFT_THUMB_STICK_RIGHT, KEY_BUTTON_LEFT_THUMB_STICK_UP, KEY_BUTTON_RIGHT_ANALOG_TRIGGER, KEY_BUTTON_RIGHT_THUMB_STICK_DOWN, KEY_BUTTON_RIGHT_THUMB_STICK_LEFT, KEY_BUTTON_RIGHT_THUMB_STICK_RIGHT, KEY_BUTTON_RIGHT_THUMB_STICK_UP, CLog::Log(), LOGDEBUG, m_customControllerTranslator, m_Mouse, XBMC_Event::motion, OnKey(), CApplicationPowerHandling::ResetSystemIdleTimer(), EVENTSERVER::CEventServer::Running(), CMouseStat::SetActive(), CKey::SetFromService(), XBMC_Event::type, XBMC_MouseMotionEvent::x, XBMC_MOUSEMOTION, and XBMC_MouseMotionEvent::y.
Referenced by Process().
ProcessMouse()
bool CInputManager::ProcessMouse (int windowId)
decode a mouse event and reset idle timers.
Parameters
windowId Currently active window
Returns
true if event is handled, false otherwise
References ACTION_MOUSE_MOVE, ACTION_NOOP, g_application, CServiceBroker::GetAppComponents(), CMouseStat::GetDX(), CMouseStat::GetDY(), CMouseStat::GetHold(), CAction::GetID(), CMouseStat::GetKey(), CAction::GetName(), CMouseStat::GetX(), CMouseStat::GetY(), CMouseStat::IsActive(), CAction::IsMouse(), KEY_MOUSE_NOOP, LOGDEBUG, m_buttonTranslator, m_Mouse, MOUSE_LEFT_BUTTON, CApplicationPowerHandling::ResetSystemIdleTimer(), and CMouseStat::SetActive().
Referenced by OnEvent().
ProcessPeripherals()
bool CInputManager::ProcessPeripherals (float frameTime)
decode an event from peripherals.
Parameters
frameTime Time in seconds since last call
Returns
true if event is handled, false otherwise
References CServiceBroker::GetPeripherals(), and OnKey().
Referenced by Process().
ProcessQueuedActions()
void CInputManager::ProcessQueuedActions () private
Dispatch actions queued since the last call to Process()
References g_application, m_actionMutex, and m_queuedActions.
Referenced by Process().
QueueAction()
void CInputManager::QueueAction (const CAction & action)
Queue an action to be processed on the next call to Process()
References m_actionMutex, and m_queuedActions.
Referenced by TVOSLibInputHandler::init, OnAction(), and CWinEventsWin32::WndProc().
RegisterKeyboardDriverHandler()
void CInputManager::RegisterKeyboardDriverHandler (KODI::KEYBOARD::IKeyboardDriverHandler * handler)
References m_keyboardHandlers.
Referenced by KODI::GAME::CAgentInput::CAgentInput(), CInputManager(), PERIPHERALS::CPeripheralKeyboard::InitialiseFeature(), and KODI::GAME::CGUIConfigurationWizard::InstallHooks().
RegisterMouseDriverHandler()
void CInputManager::RegisterMouseDriverHandler (KODI::MOUSE::IMouseDriverHandler * handler) virtual
References m_mouseHandlers.
Referenced by KODI::GAME::CAgentInput::CAgentInput(), and PERIPHERALS::CPeripheralMouse::InitialiseFeature().
ReloadKeymaps()
bool CInputManager::ReloadKeymaps ()
References LoadKeymaps().
Referenced by CApplication::OnAction().
RemoveKeymap()
void CInputManager::RemoveKeymap (const std::string & keymap)
References m_buttonTranslator, Observable::NotifyObservers(), ObservableMessageButtonMapsChanged, and Observable::SetChanged().
Referenced by PERIPHERALS::CPeripheralHID::InitialiseFeature(), and PERIPHERALS::CPeripheralHID::~CPeripheralHID().
SetMouseActive()
void CInputManager::SetMouseActive (bool active = true)
Control if the mouse is actively used or not.
Parameters
[in] active sets mouse active or inactive
References m_Mouse, and CMouseStat::SetActive().
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWayland::InitWindowSystem(), KODI::WINDOWING::X11::CWinEventsX11::MessagePump(), CApplication::OnAction(), KODI::JOYSTICK::CJoystickMonitor::OnAnalogStickMotion(), KODI::JOYSTICK::CJoystickMonitor::OnButtonMotion(), KODI::JOYSTICK::CJoystickMonitor::OnButtonPress(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnEnter(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnLeave(), KODI::JOYSTICK::CJoystickMonitor::OnThrottleMotion(), KODI::JOYSTICK::CJoystickMonitor::OnWheelMotion(), and KODI::WINDOWING::X11::CWinSystemX11::SetWindow().
SetMouseEnabled()
void CInputManager::SetMouseEnabled (bool mouseEnabled = true)
Control if we should use a mouse or not.
Parameters
[in] mouseEnabled sets mouse enabled or disabled
References m_Mouse, and CMouseStat::SetEnabled().
Referenced by CProfileManager::LoadProfile().
SetMouseResolution()
void CInputManager::SetMouseResolution (int maxX, int maxY, float speedX, float speedY)
Set the current screen resolution and pointer speed.
Parameters
[in] maxX screen width
[in] maxY screen height
[in] speedX mouse speed in x dimension
[in] speedY mouse speed in y dimension
Returns
References m_Mouse, and CMouseStat::SetResolution().
Referenced by CGraphicContext::ApplyVideoResolution(), and CGraphicContext::SetVideoResolutionInternal().
SetMouseState()
void CInputManager::SetMouseState (MOUSE_STATE mouseState)
Set the current state of the mouse such as click, drag operation.
Parameters
[in] mouseState which state the mouse should be set to
See also
MOUSE_STATE
References m_Mouse, and CMouseStat::SetState().
Referenced by CGUIControl::OnMouseOver().
TranslateCustomControllerString()
bool CInputManager::TranslateCustomControllerString (int windowId, const std::string & controllerName, int buttonId, int & action, std::string & strAction)
References m_customControllerTranslator.
TranslateTouchAction()
bool CInputManager::TranslateTouchAction (int windowId, int touchAction, int touchPointers, int & action, std::string & actionString)
References m_touchTranslator.
UnregisterKeyboardDriverHandler()
void CInputManager::UnregisterKeyboardDriverHandler (KODI::KEYBOARD::IKeyboardDriverHandler * handler)
References m_keyboardHandlers.
Referenced by KODI::GAME::CGUIConfigurationWizard::RemoveHooks(), KODI::GAME::CAgentInput::~CAgentInput(), ~CInputManager(), and PERIPHERALS::CPeripheralKeyboard::~CPeripheralKeyboard().
UnregisterMouseDriverHandler()
void CInputManager::UnregisterMouseDriverHandler (KODI::MOUSE::IMouseDriverHandler * handler) virtual
References m_mouseHandlers.
Referenced by KODI::GAME::CAgentInput::~CAgentInput(), and PERIPHERALS::CPeripheralMouse::~CPeripheralMouse().
Member Data Documentation
m_actionMutex
CCriticalSection CInputManager::m_actionMutex private
Referenced by ProcessQueuedActions(), and QueueAction().
m_buttonStat
KODI::KEYMAP::CButtonStat CInputManager::m_buttonStat private
Referenced by OnEvent().
m_buttonTranslator
std::unique_ptr<KODI::KEYMAP::CButtonTranslator> CInputManager::m_buttonTranslator private
Referenced by AddKeymap(), CInputManager(), ClearKeymaps(), GetAction(), HandleKey(), LoadKeymaps(), OnKey(), ProcessMouse(), RemoveKeymap(), and ~CInputManager().
m_customControllerTranslator
std::unique_ptr<KODI::KEYMAP::CCustomControllerTranslator> CInputManager::m_customControllerTranslator private
Referenced by CInputManager(), ProcessEventServer(), TranslateCustomControllerString(), and ~CInputManager().
m_enableController
bool CInputManager::m_enableController = true private
Referenced by InitializeInputs(), IsControllerEnabled(), and OnSettingChanged().
m_joystickTranslator
std::unique_ptr<KODI::KEYMAP::CJoystickMapper> CInputManager::m_joystickTranslator private
Referenced by CInputManager(), GetJoystickKeymaps(), and ~CInputManager().
m_Keyboard
KODI::KEYBOARD::CKeyboardStat CInputManager::m_Keyboard private
Referenced by HandleKey(), InitializeInputs(), and OnEvent().
m_keyboardEasterEgg
std::unique_ptr<KODI::KEYBOARD::IKeyboardDriverHandler> CInputManager::m_keyboardEasterEgg private
Referenced by CInputManager(), and ~CInputManager().
m_keyboardHandlers
std::vector<KODI::KEYBOARD::IKeyboardDriverHandler*> CInputManager::m_keyboardHandlers private
Referenced by OnKey(), OnKeyUp(), RegisterKeyboardDriverHandler(), and UnregisterKeyboardDriverHandler().
m_keymapEnvironment
std::unique_ptr<KODI::KEYMAP::IKeymapEnvironment> CInputManager::m_keymapEnvironment private
Referenced by KeymapEnvironment(), and Process().
m_lastAxisMap
std::map<std::string, std::map<int, float> > CInputManager::m_lastAxisMap private
m_LastKey
CKey CInputManager::m_LastKey private
Referenced by OnKey(), and OnKeyUp().
m_Mouse
CMouseStat CInputManager::m_Mouse private
Referenced by GetMousePosition(), GetMouseState(), HandleKey(), InitializeInputs(), IsMouseActive(), OnEvent(), OnSettingChanged(), ProcessEventServer(), ProcessMouse(), SetMouseActive(), SetMouseEnabled(), SetMouseResolution(), and SetMouseState().
m_mouseHandlers
std::vector<KODI::MOUSE::IMouseDriverHandler*> CInputManager::m_mouseHandlers private
Referenced by OnEvent(), RegisterMouseDriverHandler(), and UnregisterMouseDriverHandler().
m_queuedActions
std::vector<CAction> CInputManager::m_queuedActions private
Referenced by ProcessQueuedActions(), and QueueAction().
m_touchTranslator
std::unique_ptr<KODI::KEYMAP::CTouchTranslator> CInputManager::m_touchTranslator private
Referenced by CInputManager(), OnEvent(), TranslateTouchAction(), and ~CInputManager().
SETTING_INPUT_ENABLE_CONTROLLER
const std::string CInputManager::SETTING_INPUT_ENABLE_CONTROLLER = "input.enablejoystick" static private
Referenced by CInputManager(), InitializeInputs(), and OnSettingChanged().
The documentation for this class was generated from the following files:
InputManager.h
InputManager.cpp