Kodi Documentation: DVDDemuxFFmpeg.cpp File Reference
DVDDemuxFFmpeg.cpp File Reference
#include "DVDDemuxFFmpeg.h"
#include "DVDDemuxUtils.h"
#include "DVDInputStreams/DVDInputStream.h"
#include "DVDInputStreams/DVDInputStreamFFmpeg.h"
#include "ServiceBroker.h"
#include "URL.h"
#include "Util.h"
#include "commons/Exception.h"
#include "cores/FFmpeg.h"
#include "cores/MenuType.h"
#include "cores/VideoPlayer/Interface/TimingConstants.h"
#include "filesystem/CurlFile.h"
#include "filesystem/Directory.h"
#include "filesystem/File.h"
#include "settings/AdvancedSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "threads/SystemClock.h"
#include "utils/FontUtils.h"
#include "utils/LangCodeExpander.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/XTimeUtils.h"
#include "utils/log.h"
#include <memory>
#include <mutex>
#include <sstream>
#include <tuple>
#include <utility>
#include <libavutil/channel_layout.h>
#include <libavutil/dict.h>
#include <libavutil/display.h>
#include <libavutil/dovi_meta.h>
#include <libavutil/opt.h>
#include <libavutil/pixdesc.h>
Classes
struct StereoModeConversionMap
Namespaces
namespace anonymous_namespace{DVDDemuxFFmpeg.cpp}
Macros
#define __STDC_CONSTANT_MACROS
#define __STDC_LIMIT_MACROS
Functions
bool anonymous_namespace{DVDDemuxFFmpeg.cpp}::AttachmentIsFont (const AVDictionaryEntry *dict)
static int interrupt_cb (void *ctx)
static int dvd_file_read (void *h, uint8_t *buf, int size)
static int64_t dvd_file_seek (void *h, int64_t pos, int whence)
Variables
static const struct StereoModeConversionMap WmvToInternalStereoModeMap []
const std::vector< std::string > anonymous_namespace{DVDDemuxFFmpeg.cpp}::font_mimetypes
Macro Definition Documentation
__STDC_CONSTANT_MACROS
#define __STDC_CONSTANT_MACROS
__STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS
Function Documentation
dvd_file_read()
static int dvd_file_read (void * h, uint8_t * buf, int size) static
References interrupt_cb(), and CDVDDemuxFFmpeg::Read().
Referenced by CDVDDemuxFFmpeg::Open().
dvd_file_seek()
static int64_t dvd_file_seek (void * h, int64_t pos, int whence) static
References interrupt_cb().
Referenced by CDVDDemuxFFmpeg::Open().
interrupt_cb()
static int interrupt_cb (void * ctx) static
References CDVDDemuxFFmpeg::Aborted().
Referenced by dvd_file_read(), dvd_file_seek(), and CDVDDemuxFFmpeg::Open().
Variable Documentation
WmvToInternalStereoModeMap
const struct StereoModeConversionMap WmvToInternalStereoModeMap[] static
Initial value:
=
{
  { "SideBySideRF",             "right_left" },
  { "SideBySideLF",             "left_right" },
  { "OverUnderRT",              "bottom_top" },
  { "OverUnderLT",              "top_bottom" },
  {}
}
Referenced by CDVDDemuxFFmpeg::GetStereoModeFromMetadata().