Kodi Documentation: CGUIControlProfiler Class Reference
CGUIControlProfiler Class Reference
#include <GUIControlProfiler.h>
Public Member Functions
void Start (void)
void EndFrame (void)
void BeginVisibility (CGUIControl *pControl)
void EndVisibility (CGUIControl *pControl)
void BeginRender (CGUIControl *pControl)
void EndRender (CGUIControl *pControl)
int GetMaxFrameCount (void) const
void SetMaxFrameCount (int iMaxFrameCount)
void SetOutputFile (const std::string &strOutputFile)
const std::string & GetOutputFile (void) const
bool SaveResults (void)
unsigned int GetTotalTime (void) const
Static Public Member Functions
static CGUIControlProfiler & Instance (void)
static bool IsRunning (void)
Public Attributes
float m_fPerfScale
Private Member Functions
CGUIControlProfiler (void)
~CGUIControlProfiler (void)=default
CGUIControlProfiler (const CGUIControlProfiler &that)=delete
CGUIControlProfiler & operator= (const CGUIControlProfiler &that)=delete
CGUIControlProfilerItem * FindOrAddControl (CGUIControl *pControl)
Private Attributes
CGUIControlProfilerItem m_ItemHead
CGUIControlProfilerItem * m_pLastItem
std::string m_strOutputFile
int m_iMaxFrameCount = 200
int m_iFrameCount = 0
Static Private Attributes
static bool m_bIsRunning = false
Constructor & Destructor Documentation
CGUIControlProfiler() [1/2]
CGUIControlProfiler::CGUIControlProfiler (void) private
References CurrentHostFrequency(), and m_fPerfScale.
~CGUIControlProfiler()
CGUIControlProfiler::~CGUIControlProfiler (void) private default
CGUIControlProfiler() [2/2]
CGUIControlProfiler::CGUIControlProfiler (const CGUIControlProfiler & that) private delete
Member Function Documentation
BeginRender()
void CGUIControlProfiler::BeginRender (CGUIControl * pControl)
References CGUIControlProfilerItem::BeginRender(), and FindOrAddControl().
BeginVisibility()
void CGUIControlProfiler::BeginVisibility (CGUIControl * pControl)
References CGUIControlProfilerItem::BeginVisibility(), and FindOrAddControl().
EndFrame()
void CGUIControlProfiler::EndFrame (void)
References m_bIsRunning, m_iFrameCount, m_iMaxFrameCount, m_ItemHead, CGUIControlProfilerItem::m_renderTime, CGUIControlProfilerItem::m_vecChildren, CGUIControlProfilerItem::m_visTime, CGUIControlProfilerItem::Reset(), and SaveResults().
Referenced by CGUIWindow::DoRender().
EndRender()
void CGUIControlProfiler::EndRender (CGUIControl * pControl)
References CGUIControlProfilerItem::EndRender(), and FindOrAddControl().
EndVisibility()
void CGUIControlProfiler::EndVisibility (CGUIControl * pControl)
References CGUIControlProfilerItem::EndVisibility(), and FindOrAddControl().
FindOrAddControl()
CGUIControlProfilerItem * CGUIControlProfiler::FindOrAddControl (CGUIControl * pControl) private
References CGUIControlProfilerItem::AddControl(), CGUIControlProfilerItem::FindOrAddControl(), m_ItemHead, CGUIControlProfilerItem::m_pControl, m_pLastItem, and CGUIControlProfilerItem::m_pParent.
Referenced by BeginRender(), BeginVisibility(), EndRender(), and EndVisibility().
GetMaxFrameCount()
int CGUIControlProfiler::GetMaxFrameCount (void) const inline
References m_iMaxFrameCount.
GetOutputFile()
const std::string & CGUIControlProfiler::GetOutputFile (void) const inline
References m_strOutputFile.
GetTotalTime()
unsigned int CGUIControlProfiler::GetTotalTime (void) const inline
References CGUIControlProfilerItem::GetTotalTime(), and m_ItemHead.
Referenced by CGUIControlProfilerItem::SaveToXML().
Instance()
CGUIControlProfiler & CGUIControlProfiler::Instance (void) static
Referenced by CGUIWindow::DoRender(), and CApplication::OnAction().
IsRunning()
bool CGUIControlProfiler::IsRunning (void) static
References m_bIsRunning.
Referenced by CGUIWindow::DoRender(), and CGUIWindowDebugInfo::Process().
operator=()
CGUIControlProfiler & CGUIControlProfiler::operator= (const CGUIControlProfiler & that) private delete
SaveResults()
bool CGUIControlProfiler::SaveResults (void)
References m_iFrameCount, m_ItemHead, m_strOutputFile, root, CXBMCTinyXML::SaveFile(), and CGUIControlProfilerItem::SaveToXML().
Referenced by EndFrame().
SetMaxFrameCount()
void CGUIControlProfiler::SetMaxFrameCount (int iMaxFrameCount) inline
References m_iMaxFrameCount.
SetOutputFile()
void CGUIControlProfiler::SetOutputFile (const std::string & strOutputFile) inline
References m_strOutputFile.
Referenced by CApplication::OnAction().
Start()
void CGUIControlProfiler::Start (void)
References m_bIsRunning, m_iFrameCount, m_ItemHead, m_pLastItem, and CGUIControlProfilerItem::Reset().
Referenced by CApplication::OnAction().
Member Data Documentation
m_bIsRunning
bool CGUIControlProfiler::m_bIsRunning = false static private
Referenced by EndFrame(), IsRunning(), and Start().
m_fPerfScale
float CGUIControlProfiler::m_fPerfScale
Referenced by CGUIControlProfiler(), CGUIControlProfilerItem::EndRender(), and CGUIControlProfilerItem::EndVisibility().
m_iFrameCount
int CGUIControlProfiler::m_iFrameCount = 0 private
Referenced by EndFrame(), SaveResults(), and Start().
m_iMaxFrameCount
int CGUIControlProfiler::m_iMaxFrameCount = 200 private
Referenced by EndFrame(), GetMaxFrameCount(), and SetMaxFrameCount().
m_ItemHead
CGUIControlProfilerItem CGUIControlProfiler::m_ItemHead private
Referenced by EndFrame(), FindOrAddControl(), GetTotalTime(), SaveResults(), and Start().
m_pLastItem
CGUIControlProfilerItem* CGUIControlProfiler::m_pLastItem private
Referenced by FindOrAddControl(), and Start().
m_strOutputFile
std::string CGUIControlProfiler::m_strOutputFile private
Referenced by GetOutputFile(), SaveResults(), and SetOutputFile().
The documentation for this class was generated from the following files:
GUIControlProfiler.h
GUIControlProfiler.cpp