Kodi Documentation: CDVDOverlayCodecCCText Class Reference
CDVDOverlayCodecCCText Class Reference
#include <DVDOverlayCodecCCText.h>
Public Member Functions
CDVDOverlayCodecCCText ()
~CDVDOverlayCodecCCText () override=default
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
OverlayMessage Decode (DemuxPacket *pPacket) override
void Reset () override
void Flush () override
std::shared_ptr< CDVDOverlay > GetOverlay () override
void PostProcess (std::string &text) override
Post processing of subtitle, will be called before processing AddSubtitle method.
Public Member Functions inherited from CDVDOverlayCodec
CDVDOverlayCodec (const char *name)
virtual ~CDVDOverlayCodec ()=default
const std::string & GetName () const
Private Attributes
std::shared_ptr< CDVDOverlay > m_pOverlay
int m_prevSubId
double m_prevPTSStart
std::string m_prevText
bool m_changePrevStopTime
Additional Inherited Members
Static Protected Member Functions inherited from CDVDOverlayCodec
static void GetAbsoluteTimes (double &starttime, double &stoptime, DemuxPacket *pkt)
Private Member Functions inherited from CSubtitlesAdapter
CSubtitlesAdapter ()
virtual ~CSubtitlesAdapter ()
bool Initialize ()
Initialize the subtitles adapter.
int AddSubtitle (std::string &text, double startTime, double stopTime)
Add a subtitle.
int AddSubtitle (std::string &text, double startTime, double stopTime, KODI::SUBTITLES::STYLE::subtitleOpts *opts)
Add a subtitle with supplementary options.
void AppendToSubtitle (int subtitleId, const char *text)
Append text to the specified subtitle ID.
int DeleteSubtitles (int nSubtitles, int threshold)
Delete old subtitles only if the total number of subtitles added reaches the threshold.
void ChangeSubtitleStopTime (int subtitleId, double stopTime)
Change the stop time of a subtitle ID with the specified time.
void FlushSubtitles ()
std::shared_ptr< CDVDOverlay > CreateOverlay ()
Constructor & Destructor Documentation
CDVDOverlayCodecCCText()
CDVDOverlayCodecCCText::CDVDOverlayCodecCCText ()
References m_changePrevStopTime, m_prevPTSStart, m_prevSubId, m_prevText, and NO_SUBTITLE_ID.
~CDVDOverlayCodecCCText()
CDVDOverlayCodecCCText::~CDVDOverlayCodecCCText () override default
Member Function Documentation
Decode()
OverlayMessage CDVDOverlayCodecCCText::Decode (DemuxPacket * pPacket) override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::AddSubtitle(), CSubtitlesAdapter::ChangeSubtitleStopTime(), CDVDSubtitleTagSami::CloseTag(), CDVDSubtitleTagSami::ConvertLine(), data(), CSubtitlesAdapter::DeleteSubtitles(), CDVDOverlayCodec::GetAbsoluteTimes(), CDVDSubtitleTagSami::Init(), DEMUX_PACKET::iSize, CLog::Log(), LOGERROR, m_changePrevStopTime, m_pOverlay, m_prevPTSStart, m_prevSubId, m_prevText, NO_SUBTITLE_ID, OC_DONE, OC_ERROR, OC_OVERLAY, DEMUX_PACKET::pData, and text.
Flush()
void CDVDOverlayCodecCCText::Flush () override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::FlushSubtitles(), m_changePrevStopTime, m_pOverlay, m_prevPTSStart, m_prevSubId, m_prevText, and NO_SUBTITLE_ID.
Referenced by Reset().
GetOverlay()
std::shared_ptr< CDVDOverlay > CDVDOverlayCodecCCText::GetOverlay () override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::CreateOverlay(), and m_pOverlay.
Open()
bool CDVDOverlayCodecCCText::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::Initialize(), and m_pOverlay.
PostProcess()
void CDVDOverlayCodecCCText::PostProcess (std::string & text) override virtual
Post processing of subtitle, will be called before processing AddSubtitle method.
Parameters
text The subtitle text
Todo:
This must be removed after the rework of the CC decoders
Reimplemented from CSubtitlesAdapter.
References CSubtitlesAdapter::PostProcess(), and text.
Reset()
void CDVDOverlayCodecCCText::Reset () override virtual
Implements CDVDOverlayCodec.
References Flush().
Member Data Documentation
m_changePrevStopTime
bool CDVDOverlayCodecCCText::m_changePrevStopTime private
Referenced by CDVDOverlayCodecCCText(), Decode(), and Flush().
m_pOverlay
std::shared_ptr<CDVDOverlay> CDVDOverlayCodecCCText::m_pOverlay private
Referenced by Decode(), Flush(), GetOverlay(), and Open().
m_prevPTSStart
double CDVDOverlayCodecCCText::m_prevPTSStart private
Referenced by CDVDOverlayCodecCCText(), Decode(), and Flush().
m_prevSubId
int CDVDOverlayCodecCCText::m_prevSubId private
Referenced by CDVDOverlayCodecCCText(), Decode(), and Flush().
m_prevText
std::string CDVDOverlayCodecCCText::m_prevText private
Referenced by CDVDOverlayCodecCCText(), Decode(), and Flush().
The documentation for this class was generated from the following files:
DVDOverlayCodecCCText.h
DVDOverlayCodecCCText.cpp