Kodi Documentation: anonymous_namespace{TestJobManager.cpp} Namespace Reference
anonymous_namespace{TestJobManager.cpp} Namespace Reference
Classes
class BroadcastingJob
struct JobControlPackage
Functions
BroadcastingJob * WaitForJobToStartProcessing (CJob::PRIORITY priority, JobControlPackage &package)
Function Documentation
WaitForJobToStartProcessing()
BroadcastingJob * anonymous_namespace{TestJobManager.cpp}::WaitForJobToStartProcessing (CJob::PRIORITY priority, JobControlPackage & package) protected
References CServiceBroker::GetJobManager(), anonymous_namespace{TestJobManager.cpp}::JobControlPackage::jobCreatedCond, anonymous_namespace{TestJobManager.cpp}::JobControlPackage::jobCreatedMutex, anonymous_namespace{TestJobManager.cpp}::JobControlPackage::ready, and XbmcThreads::ConditionVariable::wait().
Referenced by TEST_F(), and TEST_F().