Kodi Documentation: anonymous_namespace{VideoStreamSelectHelper.cpp} Namespace Reference
anonymous_namespace{VideoStreamSelectHelper.cpp} Namespace Reference
Classes
struct AudioStreamInfoExt
struct SortComparerStreamAudio
struct SortComparerStreamSubtitle
struct SortComparerStreamVideo
struct SubtitleStreamInfoExt
struct VideoStreamInfoExt
Functions
const std::shared_ptr< CFileItem > MakeFileItemDisable (bool isSelected)
const std::shared_ptr< CFileItem > MakeFileItemNone ()
std::shared_ptr< const CFileItem > OpenSelectDialog (CGUIDialogSelect &dialog, int headingId, const CFileItemList &itemsToDisplay)
std::string ConvertFpsToString (float value)
bool SupportsAudioFeature (IPlayerAudioCaps feature, const std::vector< IPlayerAudioCaps > &caps)
bool SupportsSubtitleFeature (IPlayerSubtitleCaps feature, const std::vector< IPlayerSubtitleCaps > &caps)
Variables
constexpr int STREAM_ID_DISABLE = -2
constexpr int STREAM_ID_NONE = -1
Function Documentation
ConvertFpsToString()
std::string anonymous_namespace{VideoStreamSelectHelper.cpp}::ConvertFpsToString (float value)
References KODI::UTILS::StringUtils::Format(), and value.
Referenced by KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream().
MakeFileItemDisable()
const std::shared_ptr< CFileItem > anonymous_namespace{VideoStreamSelectHelper.cpp}::MakeFileItemDisable (bool isSelected)
References g_localizeStrings, CLocalizeStrings::Get(), and STREAM_ID_DISABLE.
Referenced by KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream().
MakeFileItemNone()
const std::shared_ptr< CFileItem > anonymous_namespace{VideoStreamSelectHelper.cpp}::MakeFileItemNone ()
References g_localizeStrings, CLocalizeStrings::Get(), and STREAM_ID_NONE.
Referenced by KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), and KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream().
OpenSelectDialog()
std::shared_ptr< const CFileItem > anonymous_namespace{VideoStreamSelectHelper.cpp}::OpenSelectDialog (CGUIDialogSelect & dialog, int headingId, const CFileItemList & itemsToDisplay)
References CGUIDialogSelect::GetSelectedFileItem(), CGUIDialogBoxBase::IsConfirmed(), CGUIDialog::Open(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CGUIDialogSelect::SetMultiSelection(), and CGUIDialogSelect::SetUseDetails().
Referenced by KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), and KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream().
SupportsAudioFeature()
bool anonymous_namespace{VideoStreamSelectHelper.cpp}::SupportsAudioFeature (IPlayerAudioCaps feature, const std::vector< IPlayerAudioCaps > & caps)
References ALL.
Referenced by KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream().
SupportsSubtitleFeature()
bool anonymous_namespace{VideoStreamSelectHelper.cpp}::SupportsSubtitleFeature (IPlayerSubtitleCaps feature, const std::vector< IPlayerSubtitleCaps > & caps)
References ALL.
Referenced by KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream().
Variable Documentation
STREAM_ID_DISABLE
constexpr int anonymous_namespace{VideoStreamSelectHelper.cpp}::STREAM_ID_DISABLE = -2 constexpr
Referenced by MakeFileItemDisable(), and KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream().
STREAM_ID_NONE
constexpr int anonymous_namespace{VideoStreamSelectHelper.cpp}::STREAM_ID_NONE = -1 constexpr
Referenced by MakeFileItemNone(), KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), and KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream().