Kodi Documentation: IDVDResourceCounted< T > Struct Template Reference
IDVDResourceCounted< T > Struct Template Reference
#include <DVDResource.h>
Public Member Functions
IDVDResourceCounted ()
virtual ~IDVDResourceCounted ()=default
IDVDResourceCounted (const IDVDResourceCounted &)=delete
IDVDResourceCounted & operator= (const IDVDResourceCounted &)=delete
virtual T * Acquire ()
virtual long Release ()
Public Attributes
std::atomic< long > m_refs
Constructor & Destructor Documentation
IDVDResourceCounted() [1/2]
template<typename T > IDVDResourceCounted< T >::IDVDResourceCounted () inline
~IDVDResourceCounted()
template<typename T > virtual IDVDResourceCounted< T >::~IDVDResourceCounted () virtual default
IDVDResourceCounted() [2/2]
template<typename T > IDVDResourceCounted< T >::IDVDResourceCounted (const IDVDResourceCounted< T > &) delete
Member Function Documentation
Acquire()
template<typename T > virtual T * IDVDResourceCounted< T >::Acquire () inline virtual
References IDVDResourceCounted< T >::m_refs.
Referenced by VAAPI::CDecoder::FFGetBuffer(), VAAPI::CVaapiBufferPool::Get(), and VDPAU::CVdpauBufferPool::Get().
operator=()
template<typename T > IDVDResourceCounted & IDVDResourceCounted< T >::operator= (const IDVDResourceCounted< T > &) delete
Release()
template<typename T > virtual long IDVDResourceCounted< T >::Release () inline virtual
Reimplemented in VAAPI::CDecoder, and VDPAU::CDecoder.
References IDVDResourceCounted< T >::m_refs.
Referenced by CDVDVideoCodecFFmpeg::Dispose(), CDVDVideoCodecFFmpeg::GetFormat(), and CDVDVideoCodecFFmpeg::SetHardware().
Member Data Documentation
m_refs
template<typename T > std::atomic<long> IDVDResourceCounted< T >::m_refs
Referenced by IDVDResourceCounted< T >::Acquire(), and IDVDResourceCounted< T >::Release().
The documentation for this struct was generated from the following file:
DVDResource.h