Kodi Documentation: CocoaInterface.mm File Reference
CocoaInterface.mm File Reference
import "CocoaInterface.h"
#include "CompileInfo.h"
import "DllPaths_generated.h"
#include "ServiceBroker.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include "windowing/osx/WinSystemOSX.h"
import <AudioToolbox/AudioToolbox.h>
import <AudioUnit/AudioUnit.h>
import <Cocoa/Cocoa.h>
import <CoreServices/CoreServices.h>
import <OpenGL/OpenGL.h>
import <OpenGL/gl.h>
import <QuartzCore/QuartzCore.h>
import <sys/mount.h>
import <unistd.h>
Functions
CGDirectDisplayID Cocoa_GetDisplayIDFromScreen (NSScreen *screen)
uint32_t Cocoa_GL_GetCurrentDisplayID (void)
bool Cocoa_CVDisplayLinkCreate (void *displayLinkcallback, void *displayLinkContext)
void Cocoa_CVDisplayLinkRelease (void)
void Cocoa_CVDisplayLinkUpdate (void)
void Cocoa_DoAppleScript (const char *scriptSource)
void Cocoa_DoAppleScriptFile (const char *filePath)
char * Cocoa_MountPoint2DeviceName (char *path)
bool Cocoa_GetVolumeNameFromMountPoint (const std::string &mountPoint, std::string &volumeName)
const char * Cocoa_Paste ()
Variables
static CVDisplayLinkRef displayLink = NULL
Function Documentation
Cocoa_CVDisplayLinkCreate()
bool Cocoa_CVDisplayLinkCreate (void * displayLinkcallback, void * displayLinkContext)
References Cocoa_GL_GetCurrentDisplayID(), and displayLink.
Referenced by CVideoSyncOsx::InitDisplayLink().
Cocoa_CVDisplayLinkRelease()
void Cocoa_CVDisplayLinkRelease (void)
References displayLink.
Referenced by CVideoSyncOsx::DeinitDisplayLink().
Cocoa_CVDisplayLinkUpdate()
void Cocoa_CVDisplayLinkUpdate (void)
References Cocoa_GL_GetCurrentDisplayID(), and displayLink.
Referenced by CWinSystemOSX::OnMove(), and CWinSystemOSX::SwitchToVideoMode().
Cocoa_DoAppleScript()
void Cocoa_DoAppleScript (const char * scriptSource)
Cocoa_DoAppleScriptFile()
void Cocoa_DoAppleScriptFile (const char * filePath)
References CCompileInfo::GetAppName().
Referenced by RunScript().
Cocoa_GetDisplayIDFromScreen()
CGDirectDisplayID Cocoa_GetDisplayIDFromScreen (NSScreen * screen)
Cocoa_GetVolumeNameFromMountPoint()
bool Cocoa_GetVolumeNameFromMountPoint (const std::string & mountPoint, std::string & volumeName)
References name, and success.
Referenced by COSXStorageProvider::GetLocalDrives(), and COSXStorageProvider::GetRemovableDrives().
Cocoa_GL_GetCurrentDisplayID()
uint32_t Cocoa_GL_GetCurrentDisplayID (void)
Referenced by Cocoa_CVDisplayLinkCreate(), and Cocoa_CVDisplayLinkUpdate().
Cocoa_MountPoint2DeviceName()
char * Cocoa_MountPoint2DeviceName (char * path)
References KODI::UTILS::StringUtils::CompareNoCase().
Referenced by CDVDInputStreamNavigator::Open().
Cocoa_Paste()
const char * Cocoa_Paste ()
Referenced by CWinSystemOSX::GetClipboardText().
Variable Documentation
displayLink
CVDisplayLinkRef displayLink = NULL static
Referenced by Cocoa_CVDisplayLinkCreate(), Cocoa_CVDisplayLinkRelease(), and Cocoa_CVDisplayLinkUpdate().