Kodi Documentation: CWinRenderer Class Reference
CWinRenderer Class Reference
#include <WinRenderer.h>
Public Member Functions
CWinRenderer ()
~CWinRenderer ()
void Update () override
bool RenderCapture (int index, CRenderCapture *capture) override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
void AddVideoPicture (const VideoPicture &picture, int index) override
void UnInit () override
bool IsConfigured () override
bool Flush (bool saveBuffers) override
CRenderInfo GetRenderInfo () override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
void SetBufferSize (int numBuffers) override
void ReleaseBuffer (int idx) override
bool NeedBuffer (int idx) override
bool SupportsMultiPassRendering () override
bool Supports (ERENDERFEATURE feature) const override
bool Supports (ESCALINGMETHOD method) const override
bool WantsDoublePass () override
bool ConfigChanged (const VideoPicture &picture) override
DEBUG_INFO_VIDEO GetDebugInfo (int idx) override
CRenderCapture * GetRenderCapture () override
Public Member Functions inherited from CBaseRenderer
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool IsPictureHW (const VideoPicture &picture)
virtual bool IsGuiLayer ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
Static Public Member Functions
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Static Public Member Functions inherited from CBaseRenderer
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
void PreInit ()
int NextBuffer () const
CRendererBase * SelectRenderer (const VideoPicture &picture)
CRect GetScreenRect () const
Protected Member Functions inherited from CBaseRenderer
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ManageRenderArea ()
virtual void ReorderDrawPoints ()
virtual EShaderFormat GetShaderFormat ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Protected Attributes
bool m_bConfigured = false
std::unique_ptr< CRendererBase > m_renderer
Protected Attributes inherited from CBaseRenderer
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Constructor & Destructor Documentation
CWinRenderer()
CWinRenderer::CWinRenderer ()
References CBaseRenderer::m_format, and PreInit().
Referenced by Create().
~CWinRenderer()
CWinRenderer::~CWinRenderer ()
References UnInit().
Member Function Documentation
AddVideoPicture()
void CWinRenderer::AddVideoPicture (const VideoPicture & picture, int index) override virtual
Implements CBaseRenderer.
References index(), and m_renderer.
ConfigChanged()
bool CWinRenderer::ConfigChanged (const VideoPicture & picture) override virtual
Implements CBaseRenderer.
References CVideoBuffer::GetFormat(), m_bConfigured, CBaseRenderer::m_format, and VideoPicture::videoBuffer.
Configure()
bool CWinRenderer::Configure (const VideoPicture & picture, float fps, unsigned int orientation) override virtual
Implements CBaseRenderer.
References CBaseRenderer::CalculateFrameAspectRatio(), VideoPicture::chroma_position, VideoPicture::color_primaries, VideoPicture::color_space, GetFlagsChromaPosition(), GetFlagsColorMatrix(), GetFlagsColorPrimaries(), GetFlagsStereoMode(), CVideoBuffer::GetFormat(), VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iHeight, VideoPicture::iWidth, m_bConfigured, CBaseRenderer::m_format, CBaseRenderer::m_fps, CBaseRenderer::m_iFlags, m_renderer, CBaseRenderer::m_renderOrientation, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, CBaseRenderer::m_videoSettings, CVideoSettings::m_ViewMode, CBaseRenderer::ManageRenderArea(), SelectRenderer(), CBaseRenderer::SetViewMode(), VideoPicture::stereoMode, and VideoPicture::videoBuffer.
Create()
CBaseRenderer * CWinRenderer::Create (CVideoBuffer * buffer) static
References CWinRenderer().
Referenced by Register().
Flush()
bool CWinRenderer::Flush (bool saveBuffers) override virtual
Reimplemented from CBaseRenderer.
References m_bConfigured, and m_renderer.
GetDebugInfo()
DEBUG_INFO_VIDEO CWinRenderer::GetDebugInfo (int idx) override virtual
Reimplemented from CBaseRenderer.
References m_bConfigured, and m_renderer.
GetRenderCapture()
CRenderCapture * CWinRenderer::GetRenderCapture () override virtual
Reimplemented from CBaseRenderer.
GetRenderInfo()
CRenderInfo CWinRenderer::GetRenderInfo () override virtual
Reimplemented from CBaseRenderer.
References m_bConfigured, and m_renderer.
GetScreenRect()
CRect CWinRenderer::GetScreenRect () const protected
References CServiceBroker::GetWinSystem(), RENDER_STEREO_MODE_SPLIT_HORIZONTAL, RENDER_STEREO_MODE_SPLIT_VERTICAL, CRectGen< T >::x2, and CRectGen< T >::y2.
Referenced by RenderCapture(), and RenderUpdate().
IsConfigured()
bool CWinRenderer::IsConfigured () inline override virtual
Implements CBaseRenderer.
References m_bConfigured.
NeedBuffer()
bool CWinRenderer::NeedBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References m_bConfigured, and m_renderer.
NextBuffer()
int CWinRenderer::NextBuffer () const protected
References m_renderer.
PreInit()
void CWinRenderer::PreInit () protected
References CServiceBroker::GetWinSystem(), m_bConfigured, and UnInit().
Referenced by CWinRenderer().
Register()
bool CWinRenderer::Register () static
References Create(), and VIDEOPLAYER::CRendererFactory::RegisterRenderer().
Referenced by CRenderSystemDX::InitRenderSystem().
ReleaseBuffer()
void CWinRenderer::ReleaseBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References m_bConfigured, and m_renderer.
RenderCapture()
bool CWinRenderer::RenderCapture (int index, CRenderCapture * capture) override virtual
Implements CBaseRenderer.
References CRenderCapture::BeginRender(), CAPTURESTATE_FAILED, CRenderCapture::EndRender(), CRenderCapture::GetHeight(), GetScreenRect(), CRenderCapture::GetState(), CRenderCapture::GetWidth(), m_bConfigured, m_renderer, and CBaseRenderer::m_sourceRect.
RenderUpdate()
void CWinRenderer::RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override virtual
Implements CBaseRenderer.
References CGraphicContext::Clear(), CWinSystemBase::GetGfxContext(), GetScreenRect(), CServiceBroker::GetWinSystem(), index(), m_bConfigured, CBaseRenderer::m_destRect, m_renderer, CBaseRenderer::m_sourceRect, and CBaseRenderer::ManageRenderArea().
SelectRenderer()
CRendererBase * CWinRenderer::SelectRenderer (const VideoPicture & picture) protected
References CServiceBroker::GetSettingsComponent(), LOGDEBUG, LOGERROR, CBaseRenderer::m_videoSettings, RENDER_DXVA, RENDER_METHOD_AUTO, RENDER_METHOD_D3D_PS, RENDER_METHOD_DXVA, RENDER_METHOD_SOFTWARE, RENDER_PS, RENDER_SW, RenderMethodDetails, and CSettings::SETTING_VIDEOPLAYER_RENDERMETHOD.
Referenced by Configure().
SetBufferSize()
void CWinRenderer::SetBufferSize (int numBuffers) override virtual
Reimplemented from CBaseRenderer.
References m_bConfigured, and m_renderer.
Supports() [1/2]
bool CWinRenderer::Supports (ERENDERFEATURE feature) const override virtual
Reimplemented from CBaseRenderer.
References m_bConfigured, and m_renderer.
Supports() [2/2]
bool CWinRenderer::Supports (ESCALINGMETHOD method) const override virtual
Implements CBaseRenderer.
References m_bConfigured, and m_renderer.
SupportsMultiPassRendering()
bool CWinRenderer::SupportsMultiPassRendering () inline override virtual
Implements CBaseRenderer.
UnInit()
void CWinRenderer::UnInit () override virtual
Implements CBaseRenderer.
References CServiceBroker::GetWinSystem(), m_bConfigured, and m_renderer.
Referenced by PreInit(), and ~CWinRenderer().
Update()
void CWinRenderer::Update () override virtual
Implements CBaseRenderer.
References m_bConfigured, m_renderer, and CBaseRenderer::ManageRenderArea().
WantsDoublePass()
bool CWinRenderer::WantsDoublePass () override virtual
Reimplemented from CBaseRenderer.
References m_bConfigured, and m_renderer.
Member Data Documentation
m_bConfigured
bool CWinRenderer::m_bConfigured = false protected
Referenced by ConfigChanged(), Configure(), Flush(), GetDebugInfo(), GetRenderInfo(), IsConfigured(), NeedBuffer(), PreInit(), ReleaseBuffer(), RenderCapture(), RenderUpdate(), SetBufferSize(), Supports(), Supports(), UnInit(), Update(), and WantsDoublePass().
m_renderer
std::unique_ptr<CRendererBase> CWinRenderer::m_renderer protected
Referenced by AddVideoPicture(), Configure(), Flush(), GetDebugInfo(), GetRenderInfo(), NeedBuffer(), NextBuffer(), ReleaseBuffer(), RenderCapture(), RenderUpdate(), SetBufferSize(), Supports(), Supports(), UnInit(), Update(), and WantsDoublePass().
The documentation for this class was generated from the following files:
WinRenderer.h
WinRenderer.cpp