Kodi Documentation: CFDEventMonitor Class Reference
CFDEventMonitor Class Reference
#include <FDEventMonitor.h>
Classes
struct MonitoredFD
Public Types
typedef void(* EventCallback) (int id, int fd, short revents, void *data)
Public Member Functions
CFDEventMonitor ()
~CFDEventMonitor () override
void AddFD (const MonitoredFD &monitoredFD, int &id)
void AddFDs (const std::vector< MonitoredFD > &monitoredFDs, std::vector< int > &ids)
void RemoveFD (int id)
void RemoveFDs (const std::vector< int > &ids)
Public Member Functions inherited from IPlatformService
virtual ~IPlatformService ()=default
Protected Member Functions
void Process () override
Private Member Functions
void AddFDLocked (const MonitoredFD &monitoredFD, int &id)
void AddPollDesc (int id, int fd, short events)
void UpdatePollDescs ()
void StartMonitoring ()
void InterruptPoll ()
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Attributes
std::map< int, MonitoredFD > m_monitoredFDs
std::vector< int > m_monitoredFDbyPollDescs
std::vector< struct pollfd > m_pollDescs
int m_nextID = 0
int m_wakeupfd = -1
CCriticalSection m_mutex
CCriticalSection m_pollMutex
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Detailed Description
Monitor a file descriptor with callback on poll() events.
Member Typedef Documentation
EventCallback
typedef void(* CFDEventMonitor::EventCallback) (int id, int fd, short revents, void *data)
Constructor & Destructor Documentation
CFDEventMonitor()
CFDEventMonitor::CFDEventMonitor ()
~CFDEventMonitor()
CFDEventMonitor::~CFDEventMonitor () override
References InterruptPoll(), m_mutex, m_wakeupfd, and CThread::StopThread().
Member Function Documentation
AddFD()
void CFDEventMonitor::AddFD (const MonitoredFD & monitoredFD, int & id)
References AddFDLocked(), InterruptPoll(), m_mutex, and StartMonitoring().
Referenced by CALSADeviceMonitor::Start().
AddFDLocked()
void CFDEventMonitor::AddFDLocked (const MonitoredFD & monitoredFD, int & id) private
References AddPollDesc(), CFDEventMonitor::MonitoredFD::events, CFDEventMonitor::MonitoredFD::fd, id, m_monitoredFDs, and m_nextID.
Referenced by AddFD(), AddFDs(), and StartMonitoring().
AddFDs()
void CFDEventMonitor::AddFDs (const std::vector< MonitoredFD > & monitoredFDs, std::vector< int > & ids)
References AddFDLocked(), id, InterruptPoll(), m_mutex, and StartMonitoring().
Referenced by CALSAHControlMonitor::Start().
AddPollDesc()
void CFDEventMonitor::AddPollDesc (int id, int fd, short events) private
References events, m_monitoredFDbyPollDescs, and m_pollDescs.
Referenced by AddFDLocked(), and UpdatePollDescs().
InterruptPoll()
void CFDEventMonitor::InterruptPoll () private
References m_pollMutex, and m_wakeupfd.
Referenced by AddFD(), AddFDs(), RemoveFD(), RemoveFDs(), and ~CFDEventMonitor().
Process()
void CFDEventMonitor::Process (void) override protected virtual
Reimplemented from CThread.
References CFDEventMonitor::MonitoredFD::callback, CFDEventMonitor::MonitoredFD::callbackData, err(), id, CLog::Log(), LOGERROR, CThread::m_bStop, m_monitoredFDbyPollDescs, m_monitoredFDs, m_mutex, m_pollDescs, m_pollMutex, m_wakeupfd, CThread::StopThread(), and UpdatePollDescs().
RemoveFD()
void CFDEventMonitor::RemoveFD (int id)
References InterruptPoll(), CLog::Log(), LOGERROR, m_monitoredFDs, m_mutex, and UpdatePollDescs().
Referenced by CALSADeviceMonitor::Stop().
RemoveFDs()
void CFDEventMonitor::RemoveFDs (const std::vector< int > & ids)
References InterruptPoll(), CLog::Log(), LOGERROR, m_monitoredFDs, m_mutex, and UpdatePollDescs().
Referenced by CALSAHControlMonitor::Stop().
StartMonitoring()
void CFDEventMonitor::StartMonitoring () private
References AddFDLocked(), CThread::Create(), id, CThread::IsRunning(), CLog::Log(), LOGERROR, and m_wakeupfd.
Referenced by AddFD(), and AddFDs().
UpdatePollDescs()
void CFDEventMonitor::UpdatePollDescs () private
References AddPollDesc(), m_monitoredFDbyPollDescs, m_monitoredFDs, and m_pollDescs.
Referenced by Process(), RemoveFD(), and RemoveFDs().
Member Data Documentation
m_monitoredFDbyPollDescs
std::vector<int> CFDEventMonitor::m_monitoredFDbyPollDescs private
Referenced by AddPollDesc(), Process(), and UpdatePollDescs().
m_monitoredFDs
std::map<int, MonitoredFD> CFDEventMonitor::m_monitoredFDs private
Referenced by AddFDLocked(), Process(), RemoveFD(), RemoveFDs(), and UpdatePollDescs().
m_mutex
CCriticalSection CFDEventMonitor::m_mutex private
Referenced by AddFD(), AddFDs(), Process(), RemoveFD(), RemoveFDs(), and ~CFDEventMonitor().
m_nextID
int CFDEventMonitor::m_nextID = 0 private
Referenced by AddFDLocked().
m_pollDescs
std::vector<struct pollfd> CFDEventMonitor::m_pollDescs private
Referenced by AddPollDesc(), Process(), and UpdatePollDescs().
m_pollMutex
CCriticalSection CFDEventMonitor::m_pollMutex private
Referenced by InterruptPoll(), and Process().
m_wakeupfd
int CFDEventMonitor::m_wakeupfd = -1 private
Referenced by InterruptPoll(), Process(), StartMonitoring(), and ~CFDEventMonitor().
The documentation for this class was generated from the following files:
FDEventMonitor.h
FDEventMonitor.cpp