Kodi Documentation: Shaders::GLES::ConvolutionFilterShader Class Reference
Shaders::GLES::ConvolutionFilterShader Class Reference
#include <VideoFilterShaderGLES.h>
Public Member Functions
ConvolutionFilterShader (ESCALINGMETHOD method)
~ConvolutionFilterShader () override
void OnCompiledAndLinked () override
bool OnEnabled () override
void OnDisabled () override
void Free ()
bool GetTextureFilter (GLint &filter) override
Public Member Functions inherited from Shaders::GLES::BaseVideoFilterShader
BaseVideoFilterShader ()
virtual void SetSourceTexture (GLint ytex)
virtual void SetWidth (int w)
virtual void SetHeight (int h)
virtual GLint GetVertexLoc ()
virtual GLint GetcoordLoc ()
virtual void SetMatrices (const GLfloat *p, const GLfloat *m)
virtual void SetAlpha (GLfloat alpha)
Public Member Functions inherited from Shaders::CGLSLShaderProgram
CGLSLShaderProgram ()
CGLSLShaderProgram (const std::string &vert, const std::string &frag)
~CGLSLShaderProgram () override
bool Enable () override
void Disable () override
bool CompileAndLink () override
Public Member Functions inherited from Shaders::CShaderProgram
CShaderProgram ()=default
virtual ~CShaderProgram ()
bool OK () const
CVertexShader * VertexShader ()
CPixelShader * PixelShader ()
virtual GLuint ProgramHandle ()
Protected Attributes
GLuint m_kernelTex1 = 0
GLint m_hKernTex = -1
ESCALINGMETHOD m_method
bool m_floattex
GLint m_internalformat
Protected Attributes inherited from Shaders::GLES::BaseVideoFilterShader
int m_width
int m_height
float m_stepX
float m_stepY
GLint m_sourceTexUnit = 0
GLint m_hSourceTex = 0
GLint m_hStepXY = 0
GLint m_hVertex = -1
GLint m_hcoord = -1
GLint m_hProj = -1
GLint m_hModel = -1
GLint m_hAlpha = -1
const GLfloat * m_proj
const GLfloat * m_model
GLfloat m_alpha = -1
Protected Attributes inherited from Shaders::CGLSLShaderProgram
GLint m_lastProgram
bool m_validated = false
Protected Attributes inherited from Shaders::CShaderProgram
CVertexShader * m_pVP = nullptr
CPixelShader * m_pFP = nullptr
GLuint m_shaderProgram = 0
bool m_ok = false
Additional Inherited Members
Protected Member Functions inherited from Shaders::CGLSLShaderProgram
void Free ()
Constructor & Destructor Documentation
ConvolutionFilterShader()
ConvolutionFilterShader::ConvolutionFilterShader (ESCALINGMETHOD method)
References CServiceBroker::GetRenderSystem(), Shaders::CShader::LoadSource(), CLog::Log(), LOGDEBUG, m_floattex, m_internalformat, m_method, Shaders::CShaderProgram::PixelShader(), VS_SCALINGMETHOD_CUBIC_0_075, VS_SCALINGMETHOD_CUBIC_0_1, VS_SCALINGMETHOD_CUBIC_B_SPLINE, VS_SCALINGMETHOD_CUBIC_CATMULL, VS_SCALINGMETHOD_CUBIC_MITCHELL, VS_SCALINGMETHOD_LANCZOS2, VS_SCALINGMETHOD_LANCZOS3, VS_SCALINGMETHOD_LANCZOS3_FAST, VS_SCALINGMETHOD_SPLINE36, and VS_SCALINGMETHOD_SPLINE36_FAST.
~ConvolutionFilterShader()
ConvolutionFilterShader::~ConvolutionFilterShader () override
References Free().
Member Function Documentation
Free()
void ConvolutionFilterShader::Free ()
References Shaders::CGLSLShaderProgram::Free(), and m_kernelTex1.
Referenced by ~ConvolutionFilterShader().
GetTextureFilter()
bool Shaders::GLES::ConvolutionFilterShader::GetTextureFilter (GLint & filter) inline override virtual
Reimplemented from Shaders::GLES::BaseVideoFilterShader.
OnCompiledAndLinked()
void ConvolutionFilterShader::OnCompiledAndLinked () override virtual
Reimplemented from Shaders::GLES::BaseVideoFilterShader.
References data(), CConvolutionKernel::GetFloatPixels(), CConvolutionKernel::GetSize(), CConvolutionKernel::GetUint8Pixels(), CLog::Log(), LOGERROR, m_floattex, m_hKernTex, Shaders::GLES::BaseVideoFilterShader::m_hSourceTex, Shaders::GLES::BaseVideoFilterShader::m_hStepXY, m_internalformat, m_kernelTex1, m_method, Shaders::GLES::BaseVideoFilterShader::OnCompiledAndLinked(), Shaders::CShaderProgram::ProgramHandle(), and VerifyGLState.
OnDisabled()
void ConvolutionFilterShader::OnDisabled () override virtual
Reimplemented from Shaders::CShaderProgram.
OnEnabled()
bool ConvolutionFilterShader::OnEnabled () override virtual
Reimplemented from Shaders::GLES::BaseVideoFilterShader.
References m_hKernTex, Shaders::GLES::BaseVideoFilterShader::m_hSourceTex, Shaders::GLES::BaseVideoFilterShader::m_hStepXY, m_kernelTex1, Shaders::GLES::BaseVideoFilterShader::m_sourceTexUnit, Shaders::GLES::BaseVideoFilterShader::m_stepX, Shaders::GLES::BaseVideoFilterShader::m_stepY, Shaders::GLES::BaseVideoFilterShader::OnEnabled(), and VerifyGLState.
Member Data Documentation
m_floattex
bool Shaders::GLES::ConvolutionFilterShader::m_floattex protected
Referenced by ConvolutionFilterShader(), and OnCompiledAndLinked().
m_hKernTex
GLint Shaders::GLES::ConvolutionFilterShader::m_hKernTex = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_internalformat
GLint Shaders::GLES::ConvolutionFilterShader::m_internalformat protected
Referenced by ConvolutionFilterShader(), and OnCompiledAndLinked().
m_kernelTex1
GLuint Shaders::GLES::ConvolutionFilterShader::m_kernelTex1 = 0 protected
Referenced by Free(), OnCompiledAndLinked(), and OnEnabled().
m_method
ESCALINGMETHOD Shaders::GLES::ConvolutionFilterShader::m_method protected
Referenced by ConvolutionFilterShader(), and OnCompiledAndLinked().
The documentation for this class was generated from the following files:
VideoFilterShaderGLES.h
VideoFilterShaderGLES.cpp