Kodi Documentation: FFmpegExtraData Class Reference
FFmpegExtraData Class Reference
#include <FFmpeg.h>
Public Member Functions
FFmpegExtraData ()=default
FFmpegExtraData (size_t size)
FFmpegExtraData (const uint8_t *data, size_t size)
FFmpegExtraData (const FFmpegExtraData &other)
FFmpegExtraData (FFmpegExtraData &&other) noexcept
~FFmpegExtraData ()
FFmpegExtraData & operator= (const FFmpegExtraData &other)
FFmpegExtraData & operator= (FFmpegExtraData &&other) noexcept
bool operator== (const FFmpegExtraData &other) const
bool operator!= (const FFmpegExtraData &other) const
operator bool () const
uint8_t * GetData ()
const uint8_t * GetData () const
size_t GetSize () const
uint8_t * TakeData ()
Take ownership over the extra data buffer.
Private Attributes
uint8_t * m_data {nullptr}
size_t m_size {}
Constructor & Destructor Documentation
FFmpegExtraData() [1/5]
FFmpegExtraData::FFmpegExtraData () default
FFmpegExtraData() [2/5]
FFmpegExtraData::FFmpegExtraData (size_t size) explicit
References m_data.
FFmpegExtraData() [3/5]
FFmpegExtraData::FFmpegExtraData (const uint8_t * data, size_t size)
References data(), and m_data.
FFmpegExtraData() [4/5]
FFmpegExtraData::FFmpegExtraData (const FFmpegExtraData & other)
References m_data, and m_size.
FFmpegExtraData() [5/5]
FFmpegExtraData::FFmpegExtraData (FFmpegExtraData && other) noexcept
~FFmpegExtraData()
FFmpegExtraData::~FFmpegExtraData ()
References m_data.
Member Function Documentation
GetData() [1/2]
uint8_t * FFmpegExtraData::GetData () inline
References m_data.
Referenced by CDVDAudioCodecAndroidMediaCodec::ConfigureMediaCodec(), CAddonVideoCodec::CopyToInitData(), CBitstreamConverter::GetExtraData(), CBitstreamConverter::GetExtraData(), CDVDVideoCodecAndroidMediaCodec::InjectExtraData(), CDVDAudioCodecFFmpeg::Open(), CDVDOverlayCodecFFmpeg::Open(), CDVDOverlayCodecSSA::Open(), COverlayCodecWebVTT::Open(), CDVDVideoCodecAndroidMediaCodec::Open(), CDVDVideoCodecDRMPRIME::Open(), CDVDVideoCodecFFmpeg::Open(), CBitstreamConverter::Open(), and CDVDVideoCodecStarfish::OpenInternal().
GetData() [2/2]
const uint8_t * FFmpegExtraData::GetData () const inline
References m_data.
GetSize()
size_t FFmpegExtraData::GetSize () const inline
References m_size.
Referenced by CDVDAudioCodecAndroidMediaCodec::ConfigureMediaCodec(), CAddonVideoCodec::CopyToInitData(), CBitstreamConverter::GetExtraSize(), CDVDVideoCodecAndroidMediaCodec::InjectExtraData(), CDVDDemuxFFmpeg::IsProgramChange(), CDVDAudioCodecAndroidMediaCodec::Open(), CDVDAudioCodecFFmpeg::Open(), CDVDOverlayCodecFFmpeg::Open(), CDVDOverlayCodecSSA::Open(), COverlayCodecWebVTT::Open(), CDVDVideoCodecAndroidMediaCodec::Open(), CDVDVideoCodecDRMPRIME::Open(), CDVDVideoCodecFFmpeg::Open(), CBitstreamConverter::Open(), CDVDVideoCodecStarfish::OpenInternal(), CDVDDemuxFFmpeg::ParsePacket(), and CDVDDemuxClient::SetStreamProps().
operator bool()
FFmpegExtraData::operator bool () const inline
References m_data, and m_size.
operator!=()
bool FFmpegExtraData::operator!= (const FFmpegExtraData & other) const
operator=() [1/2]
FFmpegExtraData & FFmpegExtraData::operator= (const FFmpegExtraData & other)
References m_data, and m_size.
operator=() [2/2]
FFmpegExtraData & FFmpegExtraData::operator= (FFmpegExtraData && other) noexcept
operator==()
bool FFmpegExtraData::operator== (const FFmpegExtraData & other) const
References m_data, and m_size.
TakeData()
uint8_t * FFmpegExtraData::TakeData ()
Take ownership over the extra data buffer.
It's in the responsibility of the caller to free the buffer with av_free. After the call FFmpegExtraData is empty.
Returns
The extra data buffer or nullptr if FFmpegExtraData is empty.
References m_data, and m_size.
Referenced by CDVDDemuxFFmpeg::ParsePacket().
Member Data Documentation
m_data
uint8_t* FFmpegExtraData::m_data {nullptr} private
Referenced by FFmpegExtraData(), FFmpegExtraData(), FFmpegExtraData(), GetData(), GetData(), operator bool(), operator=(), operator==(), TakeData(), and ~FFmpegExtraData().
m_size
size_t FFmpegExtraData::m_size {} private
Referenced by FFmpegExtraData(), GetSize(), operator bool(), operator=(), operator==(), and TakeData().
The documentation for this class was generated from the following files:
FFmpeg.h
FFmpeg.cpp