Kodi Documentation: Time value processing
Time value processing
C++ » Interface - kodi::tools » class StringUtils
String time formats
This is used to process the respective time formats in text fields.
Functions
static long kodi::tools::StringUtils::TimeStringToSeconds (const std::string &timeString)
Converts a time string to the respective integer value.
static std::string kodi::tools::StringUtils::SecondsToTimeString (long seconds, TIME_FORMAT format=TIME_FORMAT_GUESS)
Convert a time in seconds to a string based on the given time format.
static int kodi::tools::StringUtils::DateStringToYYYYMMDD (const std::string &dateString)
Converts a string in the format YYYYMMDD to the corresponding integer value.
Detailed Description
String time formats
This is used to process the respective time formats in text fields.
Function Documentation
DateStringToYYYYMMDD()
static int kodi::tools::StringUtils::DateStringToYYYYMMDD (const std::string & dateString) inline static
Converts a string in the format YYYYMMDD to the corresponding integer value.
Parameters
[in] dateString The date in the associated format, possible values are:
DD (for days only)
MM-DD (for days with month)
YYYY-MM-DD (for years, then month and last days)
Returns
Corresponding integer, e.g. "2020-12-24" return as integer value 20201224
Example:
#include <kodi/tools/StringUtils.h>
int ref, var;
ref = 20120706;
var = kodi::tools::StringUtils::DateStringToYYYYMMDD("2012-07-06");
EXPECT_EQ(ref, var);
References kodi::tools::StringUtils::Split().
SecondsToTimeString()
static std::string kodi::tools::StringUtils::SecondsToTimeString (long seconds, TIME_FORMAT format = TIME_FORMAT_GUESS) inline static
Convert a time in seconds to a string based on the given time format.
Parameters
[in] seconds time in seconds
[in] format [opt] The format we want the time in
Returns
The formatted time
See also
TIME_FORMAT
Example:
#include <kodi/tools/StringUtils.h>
std::string ref, var;
ref = "21:30:55";
var = kodi::tools::StringUtils::SecondsToTimeString(77455);
EXPECT_STREQ(ref.c_str(), var.c_str());
References kodi::tools::StringUtils::Format(), kodi::tools::TIME_FORMAT_GUESS, kodi::tools::TIME_FORMAT_H, kodi::tools::TIME_FORMAT_HH, kodi::tools::TIME_FORMAT_HH_MM_SS, kodi::tools::TIME_FORMAT_HOURS, kodi::tools::TIME_FORMAT_M, kodi::tools::TIME_FORMAT_MINS, kodi::tools::TIME_FORMAT_MM, kodi::tools::TIME_FORMAT_MM_SS, kodi::tools::TIME_FORMAT_SECS, and kodi::tools::TIME_FORMAT_SS.
TimeStringToSeconds()
static long kodi::tools::StringUtils::TimeStringToSeconds (const std::string & timeString) inline static
Converts a time string to the respective integer value.
Parameters
[in] timeString String with time.
Following types are possible:
"MM min" (integer number with "min" on end)
"HH:MM:SS"
Returns
Time in seconds
Example:
#include <kodi/tools/StringUtils.h>
EXPECT_EQ(77455, kodi::tools::StringUtils::TimeStringToSeconds("21:30:55"));
EXPECT_EQ(7*60, kodi::tools::StringUtils::TimeStringToSeconds("7 min"));
EXPECT_EQ(7*60, kodi::tools::StringUtils::TimeStringToSeconds("7 min\t"));
EXPECT_EQ(154*60, kodi::tools::StringUtils::TimeStringToSeconds("   154 min"));
EXPECT_EQ(1*60+1, kodi::tools::StringUtils::TimeStringToSeconds("1:01"));
EXPECT_EQ(4*60+3, kodi::tools::StringUtils::TimeStringToSeconds("4:03"));
EXPECT_EQ(2*3600+4*60+3, kodi::tools::StringUtils::TimeStringToSeconds("2:04:03"));
EXPECT_EQ(2*3600+4*60+3, kodi::tools::StringUtils::TimeStringToSeconds("   2:4:3"));
EXPECT_EQ(2*3600+4*60+3, kodi::tools::StringUtils::TimeStringToSeconds("  \t\t 02:04:03 \n "));
EXPECT_EQ(1*3600+5*60+2, kodi::tools::StringUtils::TimeStringToSeconds("01:05:02:04:03 \n "));
EXPECT_EQ(0, kodi::tools::StringUtils::TimeStringToSeconds("blah"));
EXPECT_EQ(0, kodi::tools::StringUtils::TimeStringToSeconds("ля-ля"));
References kodi::tools::StringUtils::EndsWithNoCase(), kodi::tools::StringUtils::Split(), and kodi::tools::StringUtils::Trim().