Kodi Documentation: CMusicLibraryScanningJob Class Reference
CMusicLibraryScanningJob Class Reference
Music library job implementation for scanning items. Uses CMusicInfoScanner for scanning and can be run with or without a visible progress bar.
#include <MusicLibraryScanningJob.h>
Public Member Functions
CMusicLibraryScanningJob (const std::string &directory, int flags, bool showProgress=true)
Creates a new music library tag scanning and data scraping job.
~CMusicLibraryScanningJob () override
bool CanBeCancelled () const override
Whether the job can be cancelled or not.
bool Cancel () override
Tries to cancel the running job.
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
Public Member Functions inherited from CMusicLibraryJob
~CMusicLibraryJob () override
bool DoWork () override
Main workhorse function of CJob instances.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Protected Member Functions
bool Work (CMusicDatabase &db) override
Worker method to be implemented by an actual implementation.
Protected Member Functions inherited from CMusicLibraryJob
CMusicLibraryJob ()
Private Attributes
MUSIC_INFO::CMusicInfoScanner m_scanner
std::string m_directory
bool m_showProgress
int m_flags
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Detailed Description
Music library job implementation for scanning items. Uses CMusicInfoScanner for scanning and can be run with or without a visible progress bar.
Constructor & Destructor Documentation
CMusicLibraryScanningJob()
CMusicLibraryScanningJob::CMusicLibraryScanningJob (const std::string & directory, int flags, bool showProgress = true)
Creates a new music library tag scanning and data scraping job.
Parameters
[in] directory Directory to be scanned for new items
[in] flags What kind of scan to do
[in] showProgress Whether to show a progress bar or not
~CMusicLibraryScanningJob()
CMusicLibraryScanningJob::~CMusicLibraryScanningJob () override default
Member Function Documentation
CanBeCancelled()
bool CMusicLibraryScanningJob::CanBeCancelled () const inline override virtual
Whether the job can be cancelled or not.
Reimplemented from CMusicLibraryJob.
Cancel()
bool CMusicLibraryScanningJob::Cancel () override virtual
Tries to cancel the running job.
Returns
True if the job was cancelled, false otherwise
Reimplemented from CMusicLibraryJob.
References CInfoScanner::IsScanning(), m_scanner, and MUSIC_INFO::CMusicInfoScanner::Stop().
GetType()
const char * CMusicLibraryScanningJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CMusicLibraryJob.
Referenced by operator==().
operator==()
bool CMusicLibraryScanningJob::operator== (const CJob * job) const override virtual
Reimplemented from CMusicLibraryJob.
References CJob::GetType(), GetType(), m_directory, and m_flags.
Work()
bool CMusicLibraryScanningJob::Work (CMusicDatabase & db) override protected virtual
Worker method to be implemented by an actual implementation.
Parameters
[in] db Already open music database to be used for interaction
Returns
True if the process succeeded, false otherwise
Implements CMusicLibraryJob.
References MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), m_directory, m_flags, m_scanner, m_showProgress, MUSIC_INFO::CMusicInfoScanner::SCAN_ALBUMS, MUSIC_INFO::CMusicInfoScanner::SCAN_ARTISTS, MUSIC_INFO::CMusicInfoScanner::SCAN_RESCAN, CInfoScanner::ShowDialog(), and MUSIC_INFO::CMusicInfoScanner::Start().
Member Data Documentation
m_directory
std::string CMusicLibraryScanningJob::m_directory private
Referenced by operator==(), and Work().
m_flags
int CMusicLibraryScanningJob::m_flags private
Referenced by operator==(), and Work().
m_scanner
MUSIC_INFO::CMusicInfoScanner CMusicLibraryScanningJob::m_scanner private
Referenced by Cancel(), and Work().
m_showProgress
bool CMusicLibraryScanningJob::m_showProgress private
Referenced by Work().
The documentation for this class was generated from the following files:
MusicLibraryScanningJob.h
MusicLibraryScanningJob.cpp