Kodi Documentation: CPlatformDarwinEmbedded Class Reference
CPlatformDarwinEmbedded Class Reference
#include <PlatformDarwinEmbedded.h>
Public Member Functions
CPlatformDarwinEmbedded ()=default
~CPlatformDarwinEmbedded () override=default
bool InitStageOne () override
Called at an early stage of application startup.
bool InitStageTwo () override
Called at a middle stage of application startup.
bool SupportsUserInstalledBinaryAddons () override
Flag whether this platform supports user installation of binary add-ons.
Public Member Functions inherited from CPlatformDarwin
CPlatformDarwin ()=default
C'tor.
~CPlatformDarwin () override=default
D'tor.
Public Member Functions inherited from CPlatformPosix
bool InitStageOne () override
Called at an early stage of application startup.
Public Member Functions inherited from CPlatform
CPlatform ()=default
C'tor.
virtual ~CPlatform ()=default
D'tor.
virtual bool InitStageThree ()
Called at a late stage of application startup.
virtual void DeinitStageOne ()
Called at a late stage of application shutdown.
virtual void DeinitStageTwo ()
Called at a middle stage of application shutdown.
virtual void DeinitStageThree ()
Called at an early stage of application shutdown.
virtual bool IsConfigureAddonsAtStartupEnabled ()
Flag whether disabled add-ons - installed via packagemanager or manually - should be offered for configuration and activation on kodi startup for this platform.
virtual void PlatformSyslog ()
Print platform specific info to log.
template<class T >
std::shared_ptr< T > GetService ()
Get a platform service instance.
Public Member Functions inherited from CComponentContainer< IPlatformService >
std::shared_ptr< T > GetComponent ()
Obtain a component.
std::shared_ptr< const T > GetComponent () const
Obtain a component.
std::size_t size () const
Returns number of registered components.
Additional Inherited Members
Static Public Member Functions inherited from CPlatformPosix
static bool TestQuitFlag ()
static void RequestQuit ()
Static Public Member Functions inherited from CPlatform
static CPlatform * CreateInstance ()
Creates the Platform object.
Protected Member Functions inherited from CComponentContainer< IPlatformService >
void RegisterComponent (const std::shared_ptr< IPlatformService > &component)
Register a new component instance.
void DeregisterComponent (const std::type_info &typeInfo)
Deregister a component.
Constructor & Destructor Documentation
CPlatformDarwinEmbedded()
CPlatformDarwinEmbedded::CPlatformDarwinEmbedded () default
~CPlatformDarwinEmbedded()
CPlatformDarwinEmbedded::~CPlatformDarwinEmbedded () override default
Member Function Documentation
InitStageOne()
bool CPlatformDarwinEmbedded::InitStageOne () override virtual
Called at an early stage of application startup.
This method can be used to do platform specific environment preparation or initialisation (like setting environment variables for example)
Reimplemented from CPlatformDarwin.
References CUtil::CopyUserDataIfNeeded(), CPlatformDarwin::InitStageOne(), CTVOSPowerSyscall::Register(), CWinSystemIOS::Register(), and CWinSystemTVOS::Register().
InitStageTwo()
bool CPlatformDarwinEmbedded::InitStageTwo () override virtual
Called at a middle stage of application startup.
This method can be used for starting platform specific services that do not depend on windowing/gui. (eg macos XBMCHelper)
Reimplemented from CPlatform.
References CTVOSInputSettings::GetInstance(), and CTVOSInputSettings::Initialize().
SupportsUserInstalledBinaryAddons()
bool CPlatformDarwinEmbedded::SupportsUserInstalledBinaryAddons () override virtual
Flag whether this platform supports user installation of binary add-ons.
Reimplemented from CPlatform.
The documentation for this class was generated from the following files:
PlatformDarwinEmbedded.h
PlatformDarwinEmbedded.cpp