Kodi Documentation: PVR::CPVRGUIActionListener Class Reference
PVR::CPVRGUIActionListener Class Reference
#include <PVRGUIActionListener.h>
Public Member Functions
CPVRGUIActionListener ()
~CPVRGUIActionListener () override
void Init (CPVRManager &mgr)
void Deinit (CPVRManager &mgr)
bool OnAction (const CAction &action) override
Handle a GUI action.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
void OnPVRManagerEvent (const PVREvent &event)
Public Member Functions inherited from KODI::ACTION::IActionListener
virtual ~IActionListener ()=default
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Private Member Functions
CPVRGUIActionListener (const CPVRGUIActionListener &)=delete
CPVRGUIActionListener & operator= (const CPVRGUIActionListener &)=delete
Static Private Member Functions
static ChannelSwitchMode GetChannelSwitchMode (int iAction)
Constructor & Destructor Documentation
CPVRGUIActionListener() [1/2]
PVR::CPVRGUIActionListener::CPVRGUIActionListener ()
References CServiceBroker::GetAppComponents(), CServiceBroker::GetSettingsComponent(), CApplicationActionListeners::RegisterActionListener(), CSettings::SETTING_EPG_FUTURE_DAYSTODISPLAY, CSettings::SETTING_EPG_PAST_DAYSTODISPLAY, CSettings::SETTING_EPG_RESETEPG, CSettings::SETTING_PVRCLIENT_MENUHOOK, CSettings::SETTING_PVRMANAGER_ADDONS, CSettings::SETTING_PVRMANAGER_CHANNELMANAGER, CSettings::SETTING_PVRMANAGER_CHANNELSCAN, CSettings::SETTING_PVRMANAGER_CLIENTPRIORITIES, CSettings::SETTING_PVRMANAGER_GROUPMANAGER, CSettings::SETTING_PVRMANAGER_RESETDB, CSettings::SETTING_PVRMENU_SEARCHICONS, and CSettings::SETTING_PVRPARENTAL_ENABLED.
~CPVRGUIActionListener()
PVR::CPVRGUIActionListener::~CPVRGUIActionListener () override
References CServiceBroker::GetAppComponents(), CServiceBroker::GetSettingsComponent(), and CApplicationActionListeners::UnregisterActionListener().
CPVRGUIActionListener() [2/2]
PVR::CPVRGUIActionListener::CPVRGUIActionListener (const CPVRGUIActionListener &) private delete
Member Function Documentation
Deinit()
void PVR::CPVRGUIActionListener::Deinit (CPVRManager & mgr)
References PVR::CPVRManager::Events(), and CEventStream< Event >::Unsubscribe().
Referenced by PVR::CPVRManager::~CPVRManager().
GetChannelSwitchMode()
ChannelSwitchMode PVR::CPVRGUIActionListener::GetChannelSwitchMode (int iAction) static private
References ACTION_MOVE_DOWN, ACTION_MOVE_UP, CServiceBroker::GetSettingsComponent(), PVR::INSTANT_OR_DELAYED_SWITCH, PVR::NO_SWITCH, and CSettings::SETTING_PVRPLAYBACK_CONFIRMCHANNELSWITCH.
Referenced by OnAction().
Init()
void PVR::CPVRGUIActionListener::Init (CPVRManager & mgr)
References PVR::CPVRManager::Events(), OnPVRManagerEvent(), and CEventStream< Event >::Subscribe().
OnAction()
bool PVR::CPVRGUIActionListener::OnAction (const CAction & action) override virtual
Handle a GUI action.
Parameters
action The GUI action
Returns
True if the action was handled, false otherwise
Implements KODI::ACTION::IActionListener.
References ACTION_CHANNEL_DOWN, ACTION_CHANNEL_NUMBER_SEP, ACTION_CHANNEL_SWITCH, ACTION_CHANNEL_UP, ACTION_JUMP_SMS2, ACTION_JUMP_SMS3, ACTION_JUMP_SMS4, ACTION_JUMP_SMS5, ACTION_JUMP_SMS6, ACTION_JUMP_SMS7, ACTION_JUMP_SMS8, ACTION_JUMP_SMS9, ACTION_MOVE_DOWN, ACTION_MOVE_UP, ACTION_NEXT_ITEM, ACTION_PREV_ITEM, CApplication::ACTION_PREV_ITEM_THRESHOLD, ACTION_PVR_ANNOUNCE_REMINDERS, ACTION_PVR_PLAY, ACTION_PVR_PLAY_RADIO, ACTION_PVR_PLAY_TV, ACTION_RECORD, ACTION_SELECT_ITEM, ACTION_SHOW_INFO, g_application, PVR::CPVRManager::Get(), GetChannelSwitchMode(), CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), PVR::CPVRManager::PlaybackState(), PVR::PlaybackTypeAny, PVR::PlaybackTypeRadio, PVR::PlaybackTypeTV, REMOTE_0, REMOTE_1, REMOTE_2, REMOTE_3, REMOTE_4, REMOTE_5, REMOTE_6, REMOTE_7, REMOTE_8, REMOTE_9, PVR::CPVRChannelNumber::SEPARATOR, CSettings::SETTING_PVRPLAYBACK_CONFIRMCHANNELSWITCH, WINDOW_FULLSCREEN_VIDEO, and WINDOW_VISUALISATION.
OnPVRManagerEvent()
void PVR::CPVRGUIActionListener::OnPVRManagerEvent (const PVREvent & event)
References ACTION_PVR_ANNOUNCE_REMINDERS, PVR::AnnounceReminder, g_application, CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by Init().
OnSettingAction()
void PVR::CPVRGUIActionListener::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References CGUIWindowManager::ActivateWindow(), PVR::CPVRManager::ChannelGroups(), PVR::CPVRManager::Get(), CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), CGUIDialog::Open(), CSettings::SETTING_EPG_RESETEPG, CSettings::SETTING_PVRCLIENT_MENUHOOK, CSettings::SETTING_PVRMANAGER_ADDONS, CSettings::SETTING_PVRMANAGER_CHANNELMANAGER, CSettings::SETTING_PVRMANAGER_CHANNELSCAN, CSettings::SETTING_PVRMANAGER_CLIENTPRIORITIES, CSettings::SETTING_PVRMANAGER_GROUPMANAGER, CSettings::SETTING_PVRMANAGER_RESETDB, CSettings::SETTING_PVRMENU_SEARCHICONS, PVR::CPVRManager::TriggerSearchMissingChannelIcons(), WINDOW_ADDON_BROWSER, WINDOW_DIALOG_PVR_CHANNEL_MANAGER, WINDOW_DIALOG_PVR_CLIENT_PRIORITIES, and WINDOW_DIALOG_PVR_GROUP_MANAGER.
OnSettingChanged()
void PVR::CPVRGUIActionListener::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), GetValue(), CSettings::SETTING_EPG_FUTURE_DAYSTODISPLAY, CSettings::SETTING_EPG_PAST_DAYSTODISPLAY, CSettings::SETTING_PVRPARENTAL_ENABLED, CSettings::SETTING_PVRPARENTAL_PIN, and CGUIDialogNumeric::ShowAndVerifyNewPassword().
operator=()
CPVRGUIActionListener & PVR::CPVRGUIActionListener::operator= (const CPVRGUIActionListener &) private delete
The documentation for this class was generated from the following files:
PVRGUIActionListener.h
PVRGUIActionListener.cpp