Kodi Documentation: screensaver.h File Reference
screensaver.h File Reference
#include "../addon_base.h"
Classes
struct KODI_ADDON_SCREENSAVER_PROPS
struct KodiToAddonFuncTable_Screensaver
struct AddonToKodiFuncTable_Screensaver
struct AddonInstance_Screensaver
Typedefs
typedef KODI_ADDON_INSTANCE_HDL KODI_ADDON_SCREENSAVER_HDL
typedef struct KodiToAddonFuncTable_Screensaver KodiToAddonFuncTable_Screensaver
typedef struct AddonToKodiFuncTable_Screensaver AddonToKodiFuncTable_Screensaver
typedef struct AddonInstance_Screensaver AddonInstance_Screensaver
Functions
typedef bool (ATTR_APIENTRYP PFN_KODI_ADDON_SCREENSAVER_START_V1)(const KODI_ADDON_SCREENSAVER_HDL hdl)
typedef void (ATTR_APIENTRYP PFN_KODI_ADDON_SCREENSAVER_STOP_V1)(const KODI_ADDON_SCREENSAVER_HDL hdl)
Typedef Documentation
AddonInstance_Screensaver
typedef struct AddonInstance_Screensaver AddonInstance_Screensaver
AddonToKodiFuncTable_Screensaver
typedef struct AddonToKodiFuncTable_Screensaver AddonToKodiFuncTable_Screensaver
KODI_ADDON_SCREENSAVER_HDL
typedef KODI_ADDON_INSTANCE_HDL KODI_ADDON_SCREENSAVER_HDL
KodiToAddonFuncTable_Screensaver
typedef struct KodiToAddonFuncTable_Screensaver KodiToAddonFuncTable_Screensaver
Function Documentation
bool()
typedef bool (ATTR_APIENTRYP PFN_KODI_ADDON_SCREENSAVER_START_V1) const
Referenced by CAESinkFactoryWin::BuildWaveFormatExtensible(), CLinuxPowerSyscall::CreateInstance(), CMediaCodecVideoBuffer::HasSurfaceTexture(), and CDBusUtil::ParseType().
void()
typedef void (ATTR_APIENTRYP PFN_KODI_ADDON_SCREENSAVER_STOP_V1) const
Referenced by jni::CJNIXBMCMainView::_attach(), jni::CJNIMainActivity::_callNative(), jni::CJNIMainActivity::_doFrame(), jni::CJNIMainActivity::_onActivityResult(), jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener::_onAudioFocusChange(), jni::CJNIXBMCNsdManagerDiscoveryListener::_onDiscoveryStarted(), jni::CJNIXBMCNsdManagerDiscoveryListener::_onDiscoveryStopped(), jni::CJNIXBMCMediaSession::_onForwardRequested(), jni::CJNIXBMCSurfaceTextureOnFrameAvailableListener::_onFrameAvailable(), jni::CJNIXBMCMediaSession::_onMediaButtonEvent(), jni::CJNIMainActivity::_onNewIntent(), jni::CJNIXBMCMediaSession::_onNextRequested(), jni::CJNIXBMCMediaSession::_onPauseRequested(), jni::CJNIXBMCMediaSession::_onPlayRequested(), jni::CJNIXBMCMediaSession::_onPreviousRequested(), jni::CJNIXBMCMediaSession::_onRewindRequested(), jni::CJNIXBMCMediaSession::_onSeekRequested(), jni::CJNIXBMCNsdManagerDiscoveryListener::_onStartDiscoveryFailed(), jni::CJNIXBMCNsdManagerDiscoveryListener::_onStopDiscoveryFailed(), jni::CJNIXBMCMediaSession::_onStopRequested(), jni::CJNIMainActivity::_onVisibleBehindCanceled(), jni::CJNIMainActivity::_onVolumeChanged(), jni::CJNIXBMCMainView::_surfaceChanged(), jni::CJNIXBMCVideoView::_surfaceChanged(), jni::CJNIXBMCMainView::_surfaceCreated(), jni::CJNIXBMCVideoView::_surfaceCreated(), jni::CJNIXBMCMainView::_surfaceDestroyed(), jni::CJNIXBMCVideoView::_surfaceDestroyed(), dbiplus::SqliteDatabase::copy(), CGUIWindowVideoNav::DoSearch(), CWinSystemWin10::DPIChanged(), CWinSystemWin32::DPIChanged(), kodi::addon::DriverPrimitive::FreeStruct(), kodi::addon::PeripheralEvent::FreeStruct(), XFILE::CStackDirectory::GetStackedTitlePath(), VDPAU::CVDPAUContext::LoadSymbols(), LogError(), KODI::WINDOWING::GBM::CDRMLegacy::PageFlipHandler(), CNetworkBase::PingHost(), CEdl::ReadComskip(), CZeroconfMDNS::registerCallback(), KODI::RETRO::CRPRendererGuiTexture::RenderInternal(), KODI::RETRO::CRPRenderManager::SaveThumbnail(), TEST(), and TEST_F().