Kodi Documentation: XBMCAddonUtils Namespace Reference
XBMCAddonUtils Namespace Reference
Classes
class GuiLock
class InvertSingleLockGuard
Functions
const char * getDefaultImage (const char *cControlType, const char *cTextureType)
Variables
static char defaultImage [1024]
Function Documentation
getDefaultImage()
const char * XBMCAddonUtils::getDefaultImage (const char * cControlType, const char * cTextureType)
References defaultImage, and g_SkinInfo.
Referenced by XBMCAddon::xbmcgui::ControlButton::ControlButton(), XBMCAddon::xbmcgui::ControlList::ControlList(), XBMCAddon::xbmcgui::ControlProgress::ControlProgress(), XBMCAddon::xbmcgui::ControlRadioButton::ControlRadioButton(), XBMCAddon::xbmcgui::ControlSlider::ControlSlider(), and XBMCAddon::xbmcgui::ControlSpin::ControlSpin().
Variable Documentation
defaultImage
char XBMCAddonUtils::defaultImage[1024] static
Referenced by getDefaultImage().