Kodi Documentation: jni::CJNIXBMCDisplayManagerDisplayListener Class Reference
jni::CJNIXBMCDisplayManagerDisplayListener Class Reference
#include <JNIXBMCDisplayManagerDisplayListener.h>
Public Member Functions
CJNIXBMCDisplayManagerDisplayListener ()
CJNIXBMCDisplayManagerDisplayListener (const jni::jhobject &object)
Static Public Member Functions
static void RegisterNatives (JNIEnv *env)
Static Protected Member Functions
static void _onDisplayAdded (JNIEnv *env, jobject thiz, int displayId)
static void _onDisplayChanged (JNIEnv *env, jobject thiz, int displayId)
static void _onDisplayRemoved (JNIEnv *env, jobject thiz, int displayId)
Constructor & Destructor Documentation
CJNIXBMCDisplayManagerDisplayListener() [1/2]
CJNIXBMCDisplayManagerDisplayListener::CJNIXBMCDisplayManagerDisplayListener ()
References s_className.
CJNIXBMCDisplayManagerDisplayListener() [2/2]
jni::CJNIXBMCDisplayManagerDisplayListener::CJNIXBMCDisplayManagerDisplayListener (const jni::jhobject & object) inline
Member Function Documentation
_onDisplayAdded()
void CJNIXBMCDisplayManagerDisplayListener::_onDisplayAdded (JNIEnv * env, jobject thiz, int displayId) static protected
References CXBMCApp::Get(), and CXBMCApp::onDisplayAdded().
Referenced by RegisterNatives().
_onDisplayChanged()
void CJNIXBMCDisplayManagerDisplayListener::_onDisplayChanged (JNIEnv * env, jobject thiz, int displayId) static protected
References CXBMCApp::Get(), and CXBMCApp::onDisplayChanged().
Referenced by RegisterNatives().
_onDisplayRemoved()
void CJNIXBMCDisplayManagerDisplayListener::_onDisplayRemoved (JNIEnv * env, jobject thiz, int displayId) static protected
References CXBMCApp::Get(), and CXBMCApp::onDisplayRemoved().
Referenced by RegisterNatives().
RegisterNatives()
void CJNIXBMCDisplayManagerDisplayListener::RegisterNatives (JNIEnv * env) static
References _onDisplayAdded(), _onDisplayChanged(), _onDisplayRemoved(), and s_className.
Referenced by JNI_OnLoad().
The documentation for this class was generated from the following files:
JNIXBMCDisplayManagerDisplayListener.h
JNIXBMCDisplayManagerDisplayListener.cpp