Kodi Documentation: IHardwareDecoder Class Reference
IHardwareDecoder Class Reference abstract
#include <DVDVideoCodec.h>
Public Member Functions
IHardwareDecoder ()=default
~IHardwareDecoder () override=default
virtual bool Open (AVCodecContext *avctx, AVCodecContext *mainctx, const enum AVPixelFormat)=0
virtual CDVDVideoCodec::VCReturn Decode (AVCodecContext *avctx, AVFrame *frame)=0
virtual bool GetPicture (AVCodecContext *avctx, VideoPicture *picture)=0
virtual CDVDVideoCodec::VCReturn Check (AVCodecContext *avctx)=0
virtual void Reset ()
virtual unsigned GetAllowedReferences ()
virtual bool CanSkipDeint ()
virtual const std::string Name ()=0
virtual void SetCodecControl (int flags)
Public Member Functions inherited from IDVDResourceCounted< IHardwareDecoder >
IDVDResourceCounted ()
IDVDResourceCounted (const IDVDResourceCounted &)=delete
virtual ~IDVDResourceCounted ()=default
IDVDResourceCounted & operator= (const IDVDResourceCounted &)=delete
virtual IHardwareDecoder * Acquire ()
virtual long Release ()
Additional Inherited Members
Public Attributes inherited from IDVDResourceCounted< IHardwareDecoder >
std::atomic< long > m_refs
Constructor & Destructor Documentation
IHardwareDecoder()
IHardwareDecoder::IHardwareDecoder () default
~IHardwareDecoder()
IHardwareDecoder::~IHardwareDecoder () override default
Member Function Documentation
CanSkipDeint()
virtual bool IHardwareDecoder::CanSkipDeint () inline virtual
Reimplemented in VAAPI::CDecoder, and VDPAU::CDecoder.
Referenced by CDVDVideoCodecFFmpeg::SetCodecControl().
Check()
virtual CDVDVideoCodec::VCReturn IHardwareDecoder::Check (AVCodecContext * avctx) pure virtual
Implemented in DXVA::CDecoder, VAAPI::CDecoder, VDPAU::CDecoder, and VTB::CDecoder.
Referenced by CDVDVideoCodecFFmpeg::AddData().
Decode()
virtual CDVDVideoCodec::VCReturn IHardwareDecoder::Decode (AVCodecContext * avctx, AVFrame * frame) pure virtual
Implemented in DXVA::CDecoder, VAAPI::CDecoder, VDPAU::CDecoder, and VTB::CDecoder.
Referenced by CDVDVideoCodecFFmpeg::GetPicture().
GetAllowedReferences()
virtual unsigned IHardwareDecoder::GetAllowedReferences () inline virtual
Reimplemented in DXVA::CDecoder, VAAPI::CDecoder, VDPAU::CDecoder, and VTB::CDecoder.
Referenced by CDVDVideoCodecFFmpeg::GetAllowedReferences().
GetPicture()
virtual bool IHardwareDecoder::GetPicture (AVCodecContext * avctx, VideoPicture * picture) pure virtual
Implemented in DXVA::CDecoder, VAAPI::CDecoder, VDPAU::CDecoder, and VTB::CDecoder.
Referenced by CDVDVideoCodecFFmpeg::GetPicture().
Name()
virtual const std::string IHardwareDecoder::Name () pure virtual
Implemented in DXVA::CDecoder, VAAPI::CDecoder, VDPAU::CDecoder, and VTB::CDecoder.
Referenced by CDVDVideoCodecFFmpeg::UpdateName().
Open()
virtual bool IHardwareDecoder::Open (AVCodecContext * avctx, AVCodecContext * mainctx, const enum AVPixelFormat) pure virtual
Implemented in DXVA::CDecoder, VAAPI::CDecoder, VDPAU::CDecoder, and VTB::CDecoder.
Referenced by CDVDVideoCodecFFmpeg::GetFormat().
Reset()
virtual void IHardwareDecoder::Reset () inline virtual
Reimplemented in DXVA::CDecoder, VAAPI::CDecoder, and VDPAU::CDecoder.
Referenced by CDVDVideoCodecFFmpeg::Reset().
SetCodecControl()
virtual void IHardwareDecoder::SetCodecControl (int flags) inline virtual
Reimplemented in VAAPI::CDecoder, and VDPAU::CDecoder.
Referenced by CDVDVideoCodecFFmpeg::GetPicture(), and CDVDVideoCodecFFmpeg::SetCodecControl().
The documentation for this class was generated from the following file:
DVDVideoCodec.h