Kodi Documentation: CStreamDetails Class Reference
CStreamDetails Class Reference final
#include <StreamDetails.h>
Public Member Functions
CStreamDetails ()
CStreamDetails (const CStreamDetails &that)
CStreamDetails & operator= (const CStreamDetails &that)
bool operator== (const CStreamDetails &that) const
bool operator!= (const CStreamDetails &that) const
bool HasItems (void) const
int GetStreamCount (CStreamDetail::StreamType type) const
int GetVideoStreamCount (void) const
int GetAudioStreamCount (void) const
int GetSubtitleStreamCount (void) const
const CStreamDetail * GetNthStream (CStreamDetail::StreamType type, int idx) const
std::string GetVideoCodec (int idx=0) const
float GetVideoAspect (int idx=0) const
int GetVideoWidth (int idx=0) const
int GetVideoHeight (int idx=0) const
std::string GetVideoHdrType (int idx=0) const
int GetVideoDuration (int idx=0) const
void SetVideoDuration (int idx, const int duration)
std::string GetStereoMode (int idx=0) const
std::string GetVideoLanguage (int idx=0) const
std::string GetAudioCodec (int idx=0) const
std::string GetAudioLanguage (int idx=0) const
int GetAudioChannels (int idx=0) const
std::string GetSubtitleLanguage (int idx=0) const
void AddStream (CStreamDetail *item)
void Reset (void)
void DetermineBestStreams (void)
void Archive (CArchive &ar) override
void Serialize (CVariant &value) const override
bool SetStreams (const VideoStreamInfo &videoInfo, int videoDuration, const AudioStreamInfo &audioInfo, const SubtitleStreamInfo &subtitleInfo)
Static Public Member Functions
static std::string VideoDimsToResolutionDescription (int iWidth, int iHeight)
static std::string VideoAspectToAspectDescription (float fAspect)
static std::string HdrTypeToString (StreamHdrType hdrType)
Private Member Functions
CStreamDetail * NewStream (CStreamDetail::StreamType type)
Private Attributes
std::vector< std::unique_ptr< CStreamDetail > > m_vecItems
const CStreamDetailVideo * m_pBestVideo
const CStreamDetailAudio * m_pBestAudio
const CStreamDetailSubtitle * m_pBestSubtitle
Additional Inherited Members
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Constructor & Destructor Documentation
CStreamDetails() [1/2]
CStreamDetails::CStreamDetails () inline
References Reset().
CStreamDetails() [2/2]
CStreamDetails::CStreamDetails (const CStreamDetails & that)
References m_pBestAudio, m_pBestSubtitle, and m_pBestVideo.
Member Function Documentation
AddStream()
void CStreamDetails::AddStream (CStreamDetail * item)
References CStreamDetail::m_pParent, and m_vecItems.
Referenced by CDVDFileInfo::AddExternalSubtitleToDetails(), XBMCAddon::xbmc::InfoTagVideo::addStreamRaw(), CDVDFileInfo::DemuxerToStreamDetails(), CDVDFileInfo::DemuxerToStreamDetails(), CVideoDatabase::GetStreamDetails(), NewStream(), operator=(), CVideoInfoTag::ParseNative(), SetStreams(), and TEST().
Archive()
void CStreamDetails::Archive (CArchive & ar) override virtual
Implements IArchivable.
References DetermineBestStreams(), CArchive::IsStoring(), m_vecItems, NewStream(), and Reset().
DetermineBestStreams()
void CStreamDetails::DetermineBestStreams (void)
References CStreamDetail::AUDIO, m_pBestAudio, m_pBestSubtitle, m_pBestVideo, m_vecItems, CStreamDetail::SUBTITLE, and CStreamDetail::VIDEO.
Referenced by Archive(), CDVDFileInfo::DemuxerToStreamDetails(), XBMCAddon::xbmc::InfoTagVideo::finalizeStreamsRaw(), CVideoDatabase::GetStreamDetails(), operator=(), CVideoInfoTag::ParseNative(), SetStreams(), and TEST().
GetAudioChannels()
int CStreamDetails::GetAudioChannels (int idx = 0) const
References CStreamDetail::AUDIO, GetNthStream(), and CStreamDetailAudio::m_iChannels.
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), CPlayerSelectionRule::GetPlayers(), operator==(), UPNP::PopulateObjectFromTag(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), and CVideoInfoTag::ToSortable().
GetAudioCodec()
std::string CStreamDetails::GetAudioCodec (int idx = 0) const
References CStreamDetail::AUDIO, GetNthStream(), and CStreamDetailAudio::m_strCodec.
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), CPlayerSelectionRule::GetPlayers(), operator==(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), and CVideoInfoTag::ToSortable().
GetAudioLanguage()
std::string CStreamDetails::GetAudioLanguage (int idx = 0) const
References CStreamDetail::AUDIO, GetNthStream(), and CStreamDetailAudio::m_strLanguage.
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), operator==(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), and CVideoInfoTag::ToSortable().
GetAudioStreamCount()
int CStreamDetails::GetAudioStreamCount (void) const
References CStreamDetail::AUDIO, and GetStreamCount().
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), operator==(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), and TEST().
GetNthStream()
const CStreamDetail * CStreamDetails::GetNthStream (CStreamDetail::StreamType type, int idx) const
References CStreamDetail::AUDIO, m_pBestAudio, m_pBestSubtitle, m_pBestVideo, m_vecItems, CStreamDetail::SUBTITLE, and CStreamDetail::VIDEO.
Referenced by CDVDFileInfo::DemuxerToStreamDetails(), GetAudioChannels(), GetAudioCodec(), GetAudioLanguage(), GetStereoMode(), GetSubtitleLanguage(), GetVideoAspect(), GetVideoCodec(), GetVideoDuration(), GetVideoHdrType(), GetVideoHeight(), GetVideoLanguage(), GetVideoWidth(), and SetVideoDuration().
GetStereoMode()
std::string CStreamDetails::GetStereoMode (int idx = 0) const
References GetNthStream(), CStreamDetailVideo::m_strStereoMode, and CStreamDetail::VIDEO.
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), TEST(), and CVideoInfoTag::ToSortable().
GetStreamCount()
int CStreamDetails::GetStreamCount (CStreamDetail::StreamType type) const
References m_vecItems.
Referenced by GetAudioStreamCount(), GetSubtitleStreamCount(), GetVideoStreamCount(), and TEST().
GetSubtitleLanguage()
std::string CStreamDetails::GetSubtitleLanguage (int idx = 0) const
References GetNthStream(), CStreamDetailSubtitle::m_strLanguage, and CStreamDetail::SUBTITLE.
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), operator==(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), and CVideoInfoTag::ToSortable().
GetSubtitleStreamCount()
int CStreamDetails::GetSubtitleStreamCount (void) const
References GetStreamCount(), and CStreamDetail::SUBTITLE.
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), operator==(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), and TEST().
GetVideoAspect()
float CStreamDetails::GetVideoAspect (int idx = 0) const
References GetNthStream(), CStreamDetailVideo::m_fAspect, and CStreamDetail::VIDEO.
Referenced by CPlayerSelectionRule::GetPlayers(), operator==(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), TEST(), and CVideoInfoTag::ToSortable().
GetVideoCodec()
std::string CStreamDetails::GetVideoCodec (int idx = 0) const
References GetNthStream(), CStreamDetailVideo::m_strCodec, and CStreamDetail::VIDEO.
Referenced by CPlayerSelectionRule::GetPlayers(), operator==(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), TEST(), and CVideoInfoTag::ToSortable().
GetVideoDuration()
int CStreamDetails::GetVideoDuration (int idx = 0) const
References GetNthStream(), CStreamDetailVideo::m_iDuration, and CStreamDetail::VIDEO.
Referenced by CVideoInfoTag::GetDuration(), CVideoDatabase::GetStreamDetails(), operator==(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), TEST(), and JSONRPC::CVideoLibrary::UpdateResumePoint().
GetVideoHdrType()
std::string CStreamDetails::GetVideoHdrType (int idx = 0) const
References GetNthStream(), CStreamDetailVideo::m_strHdrType, and CStreamDetail::VIDEO.
Referenced by CPlayerSelectionRule::GetPlayers(), CVideoInfoTag::Save(), and CVideoDatabase::SetStreamDetailsForFileId().
GetVideoHeight()
int CStreamDetails::GetVideoHeight (int idx = 0) const
References GetNthStream(), CStreamDetailVideo::m_iHeight, and CStreamDetail::VIDEO.
Referenced by CPlayerSelectionRule::GetPlayers(), operator==(), UPNP::PopulateObjectFromTag(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), TEST(), and CVideoInfoTag::ToSortable().
GetVideoLanguage()
std::string CStreamDetails::GetVideoLanguage (int idx = 0) const
References GetNthStream(), CStreamDetailVideo::m_strLanguage, and CStreamDetail::VIDEO.
Referenced by CVideoDatabase::SetStreamDetailsForFileId().
GetVideoStreamCount()
int CStreamDetails::GetVideoStreamCount (void) const
References GetStreamCount(), and CStreamDetail::VIDEO.
Referenced by operator==(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), and TEST().
GetVideoWidth()
int CStreamDetails::GetVideoWidth (int idx = 0) const
References GetNthStream(), CStreamDetailVideo::m_iWidth, and CStreamDetail::VIDEO.
Referenced by CPlayerSelectionRule::GetPlayers(), operator==(), UPNP::PopulateObjectFromTag(), CVideoInfoTag::Save(), CVideoDatabase::SetStreamDetailsForFileId(), and TEST().
HasItems()
bool CStreamDetails::HasItems (void) const inline
References m_vecItems.
Referenced by CVideoInfoTag::HasStreamDetails(), CVideoInfoTag::Merge(), CVideoInfoTag::Save(), and TEST().
HdrTypeToString()
std::string CStreamDetails::HdrTypeToString (StreamHdrType hdrType) static
References HDR_TYPE_DOLBYVISION, HDR_TYPE_HDR10, HDR_TYPE_HLG, and HDR_TYPE_NONE.
Referenced by CDVDFileInfo::DemuxerToStreamDetails(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), and KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream().
NewStream()
CStreamDetail * CStreamDetails::NewStream (CStreamDetail::StreamType type) private
References AddStream(), CStreamDetail::AUDIO, CStreamDetail::SUBTITLE, and CStreamDetail::VIDEO.
Referenced by Archive().
operator!=()
bool CStreamDetails::operator!= (const CStreamDetails & that) const
References right.
operator=()
CStreamDetails & CStreamDetails::operator= (const CStreamDetails & that)
References AddStream(), CStreamDetail::AUDIO, DetermineBestStreams(), m_vecItems, Reset(), CStreamDetail::SUBTITLE, and CStreamDetail::VIDEO.
operator==()
bool CStreamDetails::operator== (const CStreamDetails & that) const
References GetAudioChannels(), GetAudioCodec(), GetAudioLanguage(), GetAudioStreamCount(), GetSubtitleLanguage(), GetSubtitleStreamCount(), GetVideoAspect(), GetVideoCodec(), GetVideoDuration(), GetVideoHeight(), GetVideoStreamCount(), GetVideoWidth(), right, and VIDEOASPECT_EPSILON.
Reset()
void CStreamDetails::Reset (void)
References m_pBestAudio, m_pBestSubtitle, m_pBestVideo, and m_vecItems.
Referenced by Archive(), CStreamDetails(), CDVDFileInfo::DemuxerToStreamDetails(), ContentUtils::GeneratePlayableTrailerItem(), CVideoDatabase::GetStreamDetails(), operator=(), CVideoInfoTag::Reset(), and SetStreams().
Serialize()
void CStreamDetails::Serialize (CVariant & value) const override virtual
Implements ISerializable.
References CStreamDetail::AUDIO, CVariant::clear(), m_vecItems, CStreamDetail::SUBTITLE, value, CVariant::VariantTypeArray, and CStreamDetail::VIDEO.
Referenced by CVideoInfoTag::Serialize().
SetStreams()
bool CStreamDetails::SetStreams (const VideoStreamInfo & videoInfo, int videoDuration, const AudioStreamInfo & audioInfo, const SubtitleStreamInfo & subtitleInfo)
References AddStream(), DetermineBestStreams(), Reset(), and StreamInfo::valid.
SetVideoDuration()
void CStreamDetails::SetVideoDuration (int idx, const int duration)
References GetNthStream(), CStreamDetailVideo::m_iDuration, and CStreamDetail::VIDEO.
Referenced by CApplicationPlayerCallback::OnPlayerCloseFile().
VideoAspectToAspectDescription()
std::string CStreamDetails::VideoAspectToAspectDescription (float fAspect) static
Referenced by KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CPlayerSelectionRule::GetPlayers(), and TEST().
VideoDimsToResolutionDescription()
std::string CStreamDetails::VideoDimsToResolutionDescription (int iWidth, int iHeight) static
Referenced by KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CPlayerSelectionRule::GetPlayers(), and TEST().
Member Data Documentation
m_pBestAudio
const CStreamDetailAudio* CStreamDetails::m_pBestAudio private
Referenced by CStreamDetails(), DetermineBestStreams(), GetNthStream(), and Reset().
m_pBestSubtitle
const CStreamDetailSubtitle* CStreamDetails::m_pBestSubtitle private
Referenced by CStreamDetails(), DetermineBestStreams(), GetNthStream(), and Reset().
m_pBestVideo
const CStreamDetailVideo* CStreamDetails::m_pBestVideo private
Referenced by CStreamDetails(), DetermineBestStreams(), GetNthStream(), and Reset().
m_vecItems
std::vector<std::unique_ptr<CStreamDetail> > CStreamDetails::m_vecItems private
Referenced by AddStream(), Archive(), DetermineBestStreams(), GetNthStream(), GetStreamCount(), HasItems(), operator=(), Reset(), and Serialize().
The documentation for this class was generated from the following files:
StreamDetails.h
StreamDetails.cpp