Kodi Documentation: CLinuxPowerSyscall Class Reference
CLinuxPowerSyscall Class Reference
#include <LinuxPowerSyscall.h>
Static Public Member Functions
static IPowerSyscall * CreateInstance ()
static void Register ()
Member Function Documentation
CreateInstance()
IPowerSyscall * CLinuxPowerSyscall::CreateInstance () static
References bool(), IPowerSyscall::CountPowerFeatures(), CConsoleUPowerSyscall::HasConsoleKitAndUPower(), CLogindUPowerSyscall::HasLogind(), CUPowerSyscall::HasUPower(), and IPowerSyscall::MAX_COUNT_POWER_FEATURES.
Referenced by Register().
Register()
void CLinuxPowerSyscall::Register () static
References CreateInstance(), and IPowerSyscall::RegisterPowerSyscall().
Referenced by CPlatformFreebsd::InitStageOne(), and CPlatformLinux::RegisterPowerManagement().
The documentation for this class was generated from the following files:
LinuxPowerSyscall.h
LinuxPowerSyscall.cpp