Kodi Documentation: CImageLoader Class Reference
CImageLoader Class Reference
Guilib classes » Graphics and Screen » Textures and Fonts | Asynchronous jobs
Image loader job class.
#include <GUILargeTextureManager.h>
Public Member Functions
CImageLoader (const std::string &path, const bool useCache)
~CImageLoader () override
bool DoWork () override
Work function that loads in a particular image.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual const char * GetType () const
Function that returns the type of job.
virtual bool operator== (const CJob *job) const
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Public Attributes
bool m_use_cache
Whether or not to use any caching with this image.
std::string m_path
path of image to load
std::unique_ptr< CTexture > m_texture
Texture object to load the image into.
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Detailed Description
Image loader job class.
,
Used by the CGUILargeTextureManager to perform asynchronous loading of textures.
See also
CGUILargeTextureManager and CJob
Constructor & Destructor Documentation
CImageLoader()
CImageLoader::CImageLoader (const std::string & path, const bool useCache)
References m_use_cache.
~CImageLoader()
CImageLoader::~CImageLoader () override default
Member Function Documentation
DoWork()
bool CImageLoader::DoWork (void) override virtual
Work function that loads in a particular image.
Implements CJob.
References end(), CServiceBroker::GetGUI(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetTextureCache(), CGUIComponent::GetTextureManager(), CGUITextureManager::GetTexturePath(), CServiceBroker::GetWinSystem(), CTexture::LoadFromFile(), CLog::Log(), LOGDEBUG, LOGERROR, m_path, m_texture, and m_use_cache.
Member Data Documentation
m_path
std::string CImageLoader::m_path
path of image to load
Referenced by DoWork().
m_texture
std::unique_ptr<CTexture> CImageLoader::m_texture
Texture object to load the image into.
See also
CTexture.
Referenced by DoWork(), and CGUILargeTextureManager::OnJobComplete().
m_use_cache
bool CImageLoader::m_use_cache
Whether or not to use any caching with this image.
Referenced by CImageLoader(), and DoWork().
The documentation for this class was generated from the following files:
GUILargeTextureManager.h
GUILargeTextureManager.cpp