Kodi Documentation: kodi::addon::CInstancePeripheral Class Reference
kodi::addon::CInstancePeripheral Class Reference
#include <Peripheral.h>
Public Member Functions
CInstancePeripheral ()
Peripheral class constructor.
CInstancePeripheral (const IInstanceInfo &instance)
Peripheral addon class constructor used to support multiple instance types.
~CInstancePeripheral () override=default
Destructor.
virtual void GetCapabilities (kodi::addon::PeripheralCapabilities &capabilities)
Get the list of features that this add-on provides.
virtual PERIPHERAL_ERROR PerformDeviceScan (std::vector< std::shared_ptr< kodi::addon::Peripheral > > &scan_results)
Perform a scan for joysticks.
virtual PERIPHERAL_ERROR GetEvents (std::vector< kodi::addon::PeripheralEvent > &events)
Get all events that have occurred since the last call to GetEvents().
virtual bool SendEvent (const kodi::addon::PeripheralEvent &event)
Send an input event to the peripheral.
virtual PERIPHERAL_ERROR GetJoystickInfo (unsigned int index, kodi::addon::Joystick &info)
Get extended info about an attached joystick.
virtual PERIPHERAL_ERROR GetAppearance (const kodi::addon::Joystick &joystick, std::string &controllerId)
Get the ID of the controller that best represents the peripheral's appearance.
virtual PERIPHERAL_ERROR SetAppearance (const kodi::addon::Joystick &joystick, const std::string &controllerId)
Set the ID of the controller that best represents the peripheral's appearance.
virtual PERIPHERAL_ERROR GetFeatures (const kodi::addon::Joystick &joystick, const std::string &controller_id, std::vector< kodi::addon::JoystickFeature > &features)
Get the features that allow translating the joystick into the controller profile.
virtual PERIPHERAL_ERROR MapFeatures (const kodi::addon::Joystick &joystick, const std::string &controller_id, const std::vector< kodi::addon::JoystickFeature > &features)
Add or update joystick features.
virtual PERIPHERAL_ERROR GetIgnoredPrimitives (const kodi::addon::Joystick &joystick, std::vector< kodi::addon::DriverPrimitive > &primitives)
Get the driver primitives that should be ignored while mapping the device.
virtual PERIPHERAL_ERROR SetIgnoredPrimitives (const kodi::addon::Joystick &joystick, const std::vector< kodi::addon::DriverPrimitive > &primitives)
Set the list of driver primitives that are ignored for the device.
virtual void SaveButtonMap (const kodi::addon::Joystick &joystick)
Save the button map for the given joystick.
virtual void RevertButtonMap (const kodi::addon::Joystick &joystick)
Revert the button map to the last time it was loaded or committed to disk.
virtual void ResetButtonMap (const kodi::addon::Joystick &joystick, const std::string &controller_id)
Reset the button map for the given joystick and controller profile ID.
virtual void PowerOffJoystick (unsigned int index)
Powers off the given joystick if supported.
const std::string AddonPath () const
Used to get the full path where the add-on is installed.
const std::string UserPath () const
Used to get the full path to the add-on's user profile.
void TriggerScan (void)
Trigger a scan for peripherals.
void RefreshButtonMaps (const std::string &deviceName="", const std::string &controllerId="")
Notify the frontend that button maps have changed.
unsigned int FeatureCount (const std::string &controllerId, JOYSTICK_FEATURE_TYPE type=JOYSTICK_FEATURE_TYPE_UNKNOWN)
Return the number of features belonging to the specified controller.
JOYSTICK_FEATURE_TYPE FeatureType (const std::string &controllerId, const std::string &featureName)
Return the type of the feature.
Public Member Functions inherited from kodi::addon::IAddonInstance
IAddonInstance (const kodi::addon::IInstanceInfo &instance)
virtual ~IAddonInstance ()=default
virtual ADDON_STATUS CreateInstance (const kodi::addon::IInstanceInfo &instance, KODI_ADDON_INSTANCE_HDL &hdl)
std::string GetInstanceAPIVersion () const
virtual ADDON_STATUS SetInstanceSetting (const std::string &settingName, const kodi::addon::CSettingValue &settingValue)
bool IsInstanceSettingUsingDefault (const std::string &settingName)
std::string GetInstanceUserPath (const std::string &append="")
bool CheckInstanceSettingString (const std::string &settingName, std::string &settingValue)
std::string GetInstanceSettingString (const std::string &settingName, const std::string &defaultValue="")
void SetInstanceSettingString (const std::string &settingName, const std::string &settingValue)
bool CheckInstanceSettingInt (const std::string &settingName, int &settingValue)
int GetInstanceSettingInt (const std::string &settingName, int defaultValue=0)
void SetInstanceSettingInt (const std::string &settingName, int settingValue)
bool CheckInstanceSettingBoolean (const std::string &settingName, bool &settingValue)
bool GetInstanceSettingBoolean (const std::string &settingName, bool defaultValue=false)
void SetInstanceSettingBoolean (const std::string &settingName, bool settingValue)
bool CheckInstanceSettingFloat (const std::string &settingName, float &settingValue)
float GetInstanceSettingFloat (const std::string &settingName, float defaultValue=0.0f)
void SetInstanceSettingFloat (const std::string &settingName, float settingValue)
template<typename enumType >
bool CheckInstanceSettingEnum (const std::string &settingName, enumType &settingValue)
template<typename enumType >
enumType GetInstanceSettingEnum (const std::string &settingName, enumType defaultValue=static_cast< enumType >(0))
template<typename enumType >
void SetInstanceSettingEnum (const std::string &settingName, enumType settingValue)
Private Member Functions
void SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT *instance)
Static Private Member Functions
static void ADDON_GetCapabilities (const AddonInstance_Peripheral *addonInstance, PERIPHERAL_CAPABILITIES *capabilities)
static PERIPHERAL_ERROR ADDON_PerformDeviceScan (const AddonInstance_Peripheral *addonInstance, unsigned int *peripheral_count, PERIPHERAL_INFO **scan_results)
static void ADDON_FreeScanResults (const AddonInstance_Peripheral *addonInstance, unsigned int peripheral_count, PERIPHERAL_INFO *scan_results)
static PERIPHERAL_ERROR ADDON_GetEvents (const AddonInstance_Peripheral *addonInstance, unsigned int *event_count, PERIPHERAL_EVENT **events)
static void ADDON_FreeEvents (const AddonInstance_Peripheral *addonInstance, unsigned int event_count, PERIPHERAL_EVENT *events)
static bool ADDON_SendEvent (const AddonInstance_Peripheral *addonInstance, const PERIPHERAL_EVENT *event)
static PERIPHERAL_ERROR ADDON_GetJoystickInfo (const AddonInstance_Peripheral *addonInstance, unsigned int index, JOYSTICK_INFO *info)
static void ADDON_FreeJoystickInfo (const AddonInstance_Peripheral *addonInstance, JOYSTICK_INFO *info)
static PERIPHERAL_ERROR ADDON_GetAppearance (const AddonInstance_Peripheral *addonInstance, const JOYSTICK_INFO *joystick, char *buffer, unsigned int bufferSize)
static PERIPHERAL_ERROR ADDON_SetAppearance (const AddonInstance_Peripheral *addonInstance, const JOYSTICK_INFO *joystick, const char *controllerId)
static PERIPHERAL_ERROR ADDON_GetFeatures (const AddonInstance_Peripheral *addonInstance, const JOYSTICK_INFO *joystick, const char *controller_id, unsigned int *feature_count, JOYSTICK_FEATURE **features)
static void ADDON_FreeFeatures (const AddonInstance_Peripheral *addonInstance, unsigned int feature_count, JOYSTICK_FEATURE *features)
static PERIPHERAL_ERROR ADDON_MapFeatures (const AddonInstance_Peripheral *addonInstance, const JOYSTICK_INFO *joystick, const char *controller_id, unsigned int feature_count, const JOYSTICK_FEATURE *features)
static PERIPHERAL_ERROR ADDON_GetIgnoredPrimitives (const AddonInstance_Peripheral *addonInstance, const JOYSTICK_INFO *joystick, unsigned int *primitive_count, JOYSTICK_DRIVER_PRIMITIVE **primitives)
static void ADDON_FreePrimitives (const AddonInstance_Peripheral *addonInstance, unsigned int primitive_count, JOYSTICK_DRIVER_PRIMITIVE *primitives)
static PERIPHERAL_ERROR ADDON_SetIgnoredPrimitives (const AddonInstance_Peripheral *addonInstance, const JOYSTICK_INFO *joystick, unsigned int primitive_count, const JOYSTICK_DRIVER_PRIMITIVE *primitives)
static void ADDON_SaveButtonMap (const AddonInstance_Peripheral *addonInstance, const JOYSTICK_INFO *joystick)
static void ADDON_RevertButtonMap (const AddonInstance_Peripheral *addonInstance, const JOYSTICK_INFO *joystick)
static void ADDON_ResetButtonMap (const AddonInstance_Peripheral *addonInstance, const JOYSTICK_INFO *joystick, const char *controller_id)
static void ADDON_PowerOffJoystick (const AddonInstance_Peripheral *addonInstance, unsigned int index)
Private Attributes
AddonInstance_Peripheral * m_instanceData
Member Function Documentation
ADDON_FreeEvents()
static void kodi::addon::CInstancePeripheral::ADDON_FreeEvents (const AddonInstance_Peripheral * addonInstance, unsigned int event_count, PERIPHERAL_EVENT * events) inline static private
References events, and kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::FreeStructs().
ADDON_FreeFeatures()
static void kodi::addon::CInstancePeripheral::ADDON_FreeFeatures (const AddonInstance_Peripheral * addonInstance, unsigned int feature_count, JOYSTICK_FEATURE * features) inline static private
References kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::FreeStructs().
ADDON_FreeJoystickInfo()
static void kodi::addon::CInstancePeripheral::ADDON_FreeJoystickInfo (const AddonInstance_Peripheral * addonInstance, JOYSTICK_INFO * info) inline static private
References kodi::addon::Joystick::FreeStruct().
ADDON_FreePrimitives()
static void kodi::addon::CInstancePeripheral::ADDON_FreePrimitives (const AddonInstance_Peripheral * addonInstance, unsigned int primitive_count, JOYSTICK_DRIVER_PRIMITIVE * primitives) inline static private
References kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::FreeStructs().
ADDON_FreeScanResults()
static void kodi::addon::CInstancePeripheral::ADDON_FreeScanResults (const AddonInstance_Peripheral * addonInstance, unsigned int peripheral_count, PERIPHERAL_INFO * scan_results) inline static private
References kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::FreeStructs().
ADDON_GetAppearance()
static PERIPHERAL_ERROR kodi::addon::CInstancePeripheral::ADDON_GetAppearance (const AddonInstance_Peripheral * addonInstance, const JOYSTICK_INFO * joystick, char * buffer, unsigned int bufferSize) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, err(), PERIPHERAL_ERROR_INVALID_PARAMETERS, PERIPHERAL_NO_ERROR, and AddonInstance_Peripheral::toAddon.
ADDON_GetCapabilities()
static void kodi::addon::CInstancePeripheral::ADDON_GetCapabilities (const AddonInstance_Peripheral * addonInstance, PERIPHERAL_CAPABILITIES * capabilities) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, and AddonInstance_Peripheral::toAddon.
ADDON_GetEvents()
static PERIPHERAL_ERROR kodi::addon::CInstancePeripheral::ADDON_GetEvents (const AddonInstance_Peripheral * addonInstance, unsigned int * event_count, PERIPHERAL_EVENT ** events) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, err(), events, PERIPHERAL_ERROR_INVALID_PARAMETERS, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, and kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::ToStructs().
ADDON_GetFeatures()
static PERIPHERAL_ERROR kodi::addon::CInstancePeripheral::ADDON_GetFeatures (const AddonInstance_Peripheral * addonInstance, const JOYSTICK_INFO * joystick, const char * controller_id, unsigned int * feature_count, JOYSTICK_FEATURE ** features) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, err(), PERIPHERAL_ERROR_INVALID_PARAMETERS, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, and kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::ToStructs().
ADDON_GetIgnoredPrimitives()
static PERIPHERAL_ERROR kodi::addon::CInstancePeripheral::ADDON_GetIgnoredPrimitives (const AddonInstance_Peripheral * addonInstance, const JOYSTICK_INFO * joystick, unsigned int * primitive_count, JOYSTICK_DRIVER_PRIMITIVE ** primitives) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, err(), PERIPHERAL_ERROR_INVALID_PARAMETERS, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, and kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::ToStructs().
ADDON_GetJoystickInfo()
static PERIPHERAL_ERROR kodi::addon::CInstancePeripheral::ADDON_GetJoystickInfo (const AddonInstance_Peripheral * addonInstance, unsigned int index, JOYSTICK_INFO * info) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, err(), index(), PERIPHERAL_ERROR_INVALID_PARAMETERS, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, and kodi::addon::Joystick::ToStruct().
ADDON_MapFeatures()
static PERIPHERAL_ERROR kodi::addon::CInstancePeripheral::ADDON_MapFeatures (const AddonInstance_Peripheral * addonInstance, const JOYSTICK_INFO * joystick, const char * controller_id, unsigned int feature_count, const JOYSTICK_FEATURE * features) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, PERIPHERAL_ERROR_INVALID_PARAMETERS, and AddonInstance_Peripheral::toAddon.
ADDON_PerformDeviceScan()
static PERIPHERAL_ERROR kodi::addon::CInstancePeripheral::ADDON_PerformDeviceScan (const AddonInstance_Peripheral * addonInstance, unsigned int * peripheral_count, PERIPHERAL_INFO ** scan_results) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, err(), PERIPHERAL_ERROR_INVALID_PARAMETERS, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, and kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::ToStructs().
ADDON_PowerOffJoystick()
static void kodi::addon::CInstancePeripheral::ADDON_PowerOffJoystick (const AddonInstance_Peripheral * addonInstance, unsigned int index) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, index(), and AddonInstance_Peripheral::toAddon.
ADDON_ResetButtonMap()
static void kodi::addon::CInstancePeripheral::ADDON_ResetButtonMap (const AddonInstance_Peripheral * addonInstance, const JOYSTICK_INFO * joystick, const char * controller_id) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, and AddonInstance_Peripheral::toAddon.
ADDON_RevertButtonMap()
static void kodi::addon::CInstancePeripheral::ADDON_RevertButtonMap (const AddonInstance_Peripheral * addonInstance, const JOYSTICK_INFO * joystick) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, and AddonInstance_Peripheral::toAddon.
ADDON_SaveButtonMap()
static void kodi::addon::CInstancePeripheral::ADDON_SaveButtonMap (const AddonInstance_Peripheral * addonInstance, const JOYSTICK_INFO * joystick) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, and AddonInstance_Peripheral::toAddon.
ADDON_SendEvent()
static bool kodi::addon::CInstancePeripheral::ADDON_SendEvent (const AddonInstance_Peripheral * addonInstance, const PERIPHERAL_EVENT * event) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, and AddonInstance_Peripheral::toAddon.
ADDON_SetAppearance()
static PERIPHERAL_ERROR kodi::addon::CInstancePeripheral::ADDON_SetAppearance (const AddonInstance_Peripheral * addonInstance, const JOYSTICK_INFO * joystick, const char * controllerId) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, PERIPHERAL_ERROR_INVALID_PARAMETERS, and AddonInstance_Peripheral::toAddon.
ADDON_SetIgnoredPrimitives()
static PERIPHERAL_ERROR kodi::addon::CInstancePeripheral::ADDON_SetIgnoredPrimitives (const AddonInstance_Peripheral * addonInstance, const JOYSTICK_INFO * joystick, unsigned int primitive_count, const JOYSTICK_DRIVER_PRIMITIVE * primitives) inline static private
References KodiToAddonFuncTable_Peripheral::addonInstance, PERIPHERAL_ERROR_INVALID_PARAMETERS, and AddonInstance_Peripheral::toAddon.
SetAddonStruct()
void kodi::addon::CInstancePeripheral::SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT * instance) inline private
References KodiToAddonFuncTable_Peripheral::addonInstance, KODI_ADDON_INSTANCE_STRUCT::hdl, KODI_ADDON_INSTANCE_STRUCT::peripheral, and AddonInstance_Peripheral::toAddon.
Member Data Documentation
m_instanceData
AddonInstance_Peripheral* kodi::addon::CInstancePeripheral::m_instanceData private
The documentation for this class was generated from the following file:
addons/kodi-dev-kit/include/kodi/addon-instance/Peripheral.h