Kodi Documentation: KODI::WINDOWING::WAYLAND::COutput::Mode Struct Reference
KODI::WINDOWING::WAYLAND::COutput::Mode Struct Reference
#include <Output.h>
Public Member Functions
Mode (CSizeInt size, std::int32_t refreshMilliHz)
float GetRefreshInHz () const
std::tuple< std::int32_t, std::int32_t, std::int32_t > AsTuple () const
bool operator< (const Mode &right) const
bool operator== (const Mode &right) const
bool operator!= (const Mode &right) const
Public Attributes
CSizeInt size
std::int32_t refreshMilliHz
Constructor & Destructor Documentation
Mode()
KODI::WINDOWING::WAYLAND::COutput::Mode::Mode (CSizeInt size, std::int32_t refreshMilliHz) inline
Member Function Documentation
AsTuple()
std::tuple< std::int32_t, std::int32_t, std::int32_t > KODI::WINDOWING::WAYLAND::COutput::Mode::AsTuple () const inline
References refreshMilliHz.
Referenced by operator<(), and operator==().
GetRefreshInHz()
float KODI::WINDOWING::WAYLAND::COutput::Mode::GetRefreshInHz () const inline
References refreshMilliHz.
operator!=()
bool KODI::WINDOWING::WAYLAND::COutput::Mode::operator!= (const Mode & right) const inline
References right.
operator<()
bool KODI::WINDOWING::WAYLAND::COutput::Mode::operator< (const Mode & right) const inline
References AsTuple(), and right.
operator==()
bool KODI::WINDOWING::WAYLAND::COutput::Mode::operator== (const Mode & right) const inline
References AsTuple(), and right.
Member Data Documentation
refreshMilliHz
std::int32_t KODI::WINDOWING::WAYLAND::COutput::Mode::refreshMilliHz
Referenced by AsTuple(), and GetRefreshInHz().
size
CSizeInt KODI::WINDOWING::WAYLAND::COutput::Mode::size
Referenced by KODI::WINDOWING::WAYLAND::COutput::GetDpiForMode(), and KODI::WINDOWING::WAYLAND::COutput::GetPixelRatioForMode().
The documentation for this struct was generated from the following file:
Output.h