Kodi Documentation: KODI::GUILIB::GUIINFO::CMusicGUIInfo Class Reference
KODI::GUILIB::GUIINFO::CMusicGUIInfo Class Reference
#include <MusicGUIInfo.h>
Public Member Functions
CMusicGUIInfo ()=default
~CMusicGUIInfo () override=default
bool InitCurrentItem (CFileItem *item) override
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) const override
Get a GUIInfoManager label string.
bool GetFallbackLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) override
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager integer value.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager bool value.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
CGUIInfoProvider ()=default
~CGUIInfoProvider () override=default
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo) override
Set new audio/video stream info data.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::IGUIInfoProvider
virtual ~IGUIInfoProvider ()=default
Private Member Functions
bool GetPartyModeLabel (std::string &value, const CGUIInfo &info) const
bool GetPlaylistInfo (std::string &value, const CGUIInfo &info) const
Additional Inherited Members
Protected Attributes inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
VideoStreamInfo m_videoInfo
AudioStreamInfo m_audioInfo
SubtitleStreamInfo m_subtitleInfo
Constructor & Destructor Documentation
CMusicGUIInfo()
KODI::GUILIB::GUIINFO::CMusicGUIInfo::CMusicGUIInfo () default
~CMusicGUIInfo()
KODI::GUILIB::GUIINFO::CMusicGUIInfo::~CMusicGUIInfo () override default
Member Function Documentation
GetBool()
bool CMusicGUIInfo::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager bool value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References g_partyModeManager, CServiceBroker::GetAppComponents(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CFileItem::GetMusicInfoTag(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), MUSIC_INFO::CMusicInfoTag::GetTotalDiscs(), index(), CPartyModeManager::IsEnabled(), LISTITEM_IS_BOXSET, MUSICPLAYER_CONTENT, MUSICPLAYER_EXISTS, MUSICPLAYER_HASNEXT, MUSICPLAYER_HASPREVIOUS, MUSICPLAYER_ISMULTIDISC, MUSICPLAYER_PLAYLISTPLAYING, MUSICPM_ENABLED, KODI::PLAYLIST::CPlayList::size(), KODI::PLAYLIST::TYPE_MUSIC, and value.
GetFallbackLabel()
bool CMusicGUIInfo::GetFallbackLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) override virtual
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Reimplemented from KODI::GUILIB::GUIINFO::CGUIInfoProvider.
References CGUIListItem::GetLabel(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), CUtil::GetTitleFromPath(), MUSICPLAYER_OFFSET_POSITION_FIRST, MUSICPLAYER_OFFSET_POSITION_LAST, MUSICPLAYER_TITLE, PLAYER_OFFSET_POSITION_FIRST, PLAYER_OFFSET_POSITION_LAST, and value.
GetInt()
bool CMusicGUIInfo::GetInt (int & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager integer value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
GetLabel()
bool CMusicGUIInfo::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) const override virtual
Get a GUIInfoManager label string.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CVariant::asString(), StreamInfo::bitrate, AudioStreamInfo::bitspersample, AudioStreamInfo::channels, StreamInfo::codecName, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAppComponents(), CGUIListItem::GetArt(), MUSIC_INFO::CMusicInfoTag::GetArtistStringForRole(), CDateTime::GetAsLocalizedDate(), URIUtils::GetDirectory(), URIUtils::GetExtension(), KODI::GUILIB::GUIINFO::GetFileInfoLabelValueFromPath(), URIUtils::GetFileName(), CFileItem::GetMusicInfoTag(), URIUtils::GetParentPath(), GetPartyModeLabel(), CFileItem::GetPath(), GetPlaylistInfo(), KODI::GUILIB::GUIINFO::GetPlaylistLabel(), CServiceBroker::GetPlaylistPlayer(), CGUIListItem::GetProperty(), CServiceBroker::GetSettingsComponent(), MUSIC_INFO::CMusicInfoTag::GetURL(), CURL::GetWithoutUserDetails(), CGUIListItem::HasArt(), CFileItem::HasMusicInfoTag(), CFileItem::HasVideoInfoTag(), KODI::MUSIC::IsMusicDb(), CDateTime::IsValid(), LISTITEM_ALBUM, LISTITEM_ALBUM_ARTIST, LISTITEM_ALBUMSTATUS, LISTITEM_ARTIST, LISTITEM_BITRATE, LISTITEM_BPM, LISTITEM_COMMENT, LISTITEM_CONTRIBUTOR_AND_ROLE, LISTITEM_CONTRIBUTORS, LISTITEM_DATE_ADDED, LISTITEM_DBID, LISTITEM_DBTYPE, LISTITEM_DISC_NUMBER, LISTITEM_DISC_TITLE, LISTITEM_DURATION, LISTITEM_FILE_EXTENSION, LISTITEM_FILENAME, LISTITEM_FILENAME_AND_PATH, LISTITEM_FOLDERNAME, LISTITEM_GENRE, LISTITEM_LASTPLAYED, LISTITEM_MOOD, LISTITEM_MUSICCHANNELS, LISTITEM_ORIGINALDATE, LISTITEM_PATH, LISTITEM_PLAYCOUNT, LISTITEM_PROPERTY, LISTITEM_RATING, LISTITEM_RATING_AND_VOTES, LISTITEM_RELEASEDATE, LISTITEM_SAMPLERATE, LISTITEM_SONG_VIDEO_URL, LISTITEM_TITLE, LISTITEM_TOTALDISCS, LISTITEM_TRACKNUMBER, LISTITEM_USER_RATING, LISTITEM_VOTES, LISTITEM_YEAR, KODI::GUILIB::GUIINFO::CGUIInfoProvider::m_audioInfo, MUSICPLAYER_ALBUM, MUSICPLAYER_ALBUM_ARTIST, MUSICPLAYER_ARTIST, MUSICPLAYER_BITRATE, MUSICPLAYER_BITSPERSAMPLE, MUSICPLAYER_BPM, MUSICPLAYER_CHANNELS, MUSICPLAYER_CODEC, MUSICPLAYER_COMMENT, MUSICPLAYER_CONTRIBUTOR_AND_ROLE, MUSICPLAYER_CONTRIBUTORS, MUSICPLAYER_COVER, MUSICPLAYER_DBID, MUSICPLAYER_DISC_NUMBER, MUSICPLAYER_DISC_TITLE, MUSICPLAYER_DURATION, MUSICPLAYER_GENRE, MUSICPLAYER_LASTPLAYED, MUSICPLAYER_LYRICS, MUSICPLAYER_MOOD, MUSICPLAYER_OFFSET_POSITION_FIRST, MUSICPLAYER_OFFSET_POSITION_LAST, MUSICPLAYER_ORIGINALDATE, MUSICPLAYER_PLAYCOUNT, MUSICPLAYER_PLAYLISTLEN, MUSICPLAYER_PLAYLISTPOS, MUSICPLAYER_PROPERTY, MUSICPLAYER_RATING, MUSICPLAYER_RATING_AND_VOTES, MUSICPLAYER_RELEASEDATE, MUSICPLAYER_SAMPLERATE, MUSICPLAYER_STATIONNAME, MUSICPLAYER_TITLE, MUSICPLAYER_TOTALDISCS, MUSICPLAYER_TRACK_NUMBER, MUSICPLAYER_USER_RATING, MUSICPLAYER_YEAR, PLAYER_DURATION, PLAYER_FILENAME, PLAYER_FILEPATH, PLAYER_OFFSET_POSITION_FIRST, PLAYER_OFFSET_POSITION_LAST, PLAYER_PATH, PLAYER_TITLE, PLAYLIST_LENGTH, PLAYLIST_POSITION, URIUtils::RemoveSlashAtEnd(), AudioStreamInfo::samplerate, KODI::PLAYLIST::TYPE_MUSIC, and value.
Referenced by GetPlaylistInfo().
GetPartyModeLabel()
bool CMusicGUIInfo::GetPartyModeLabel (std::string & value, const CGUIInfo & info) const private
References g_partyModeManager, CPartyModeManager::GetMatchingSongs(), CPartyModeManager::GetMatchingSongsLeft(), CPartyModeManager::GetMatchingSongsPicked(), CPartyModeManager::GetRandomSongs(), CPartyModeManager::GetRelaxedSongs(), CPartyModeManager::GetSongsPlayed(), MUSICPM_MATCHINGSONGS, MUSICPM_MATCHINGSONGSLEFT, MUSICPM_MATCHINGSONGSPICKED, MUSICPM_RANDOMSONGSPICKED, MUSICPM_RELAXEDSONGSPICKED, MUSICPM_SONGSPLAYED, and value.
Referenced by GetLabel().
GetPlaylistInfo()
bool CMusicGUIInfo::GetPlaylistInfo (std::string & value, const CGUIInfo & info) const private
References GetLabel(), KODI::PLAYLIST::CPlayListPlayer::GetNextItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), index(), CMusicThumbLoader::LoadItem(), MUSICPLAYER_COVER, MUSICPLAYER_PLAYLISTPOS, playlist, KODI::PLAYLIST::TYPE_MUSIC, and value.
Referenced by GetLabel().
InitCurrentItem()
bool CMusicGUIInfo::InitCurrentItem (CFileItem * item) override virtual
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by the provider, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CMusicThumbLoader::FillThumb(), g_application, CServiceBroker::GetAppComponents(), CGUIListItem::GetArt(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), CGUIListItem::HasArt(), KODI::MUSIC::IsAudio(), KODI::NETWORK::IsInternetStream(), KODI::MUSIC::IsMusicDb(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CMusicThumbLoader::LoadItem(), CFileItem::LoadMusicTag(), CLog::Log(), LOGDEBUG, CGUIListItem::SetArt(), and MUSIC_INFO::CMusicInfoTag::SetLoaded().
The documentation for this class was generated from the following files:
MusicGUIInfo.h
MusicGUIInfo.cpp