Kodi Documentation: CServicesSettings Class Reference
CServicesSettings Class Reference
#include <ServicesSettings.h>
Static Public Member Functions
static void SettingOptionsChunkSizesFiller (const SettingConstPtr &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsBufferModesFiller (const SettingConstPtr &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsMemorySizesFiller (const SettingConstPtr &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsReadFactorsFiller (const SettingConstPtr &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsCacheChunkSizesFiller (const SettingConstPtr &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Additional Inherited Members
Public Member Functions inherited from ISubSettings
virtual ~ISubSettings ()=default
virtual bool Load (const TiXmlNode *settings)
Load settings from the given XML node.
virtual bool Save (TiXmlNode *settings) const
Save settings to the given XML node.
virtual void Clear ()
Clear any loaded setting values.
Member Function Documentation
SettingOptionsBufferModesFiller()
void CServicesSettings::SettingOptionsBufferModesFiller (const SettingConstPtr & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References XFILE::CACHE_BUFFER_MODE_ALL, XFILE::CACHE_BUFFER_MODE_INTERNET, XFILE::CACHE_BUFFER_MODE_NETWORK, XFILE::CACHE_BUFFER_MODE_NONE, XFILE::CACHE_BUFFER_MODE_TRUE_INTERNET, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsCacheChunkSizesFiller()
void CServicesSettings::SettingOptionsCacheChunkSizesFiller (const SettingConstPtr & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsChunkSizesFiller()
void CServicesSettings::SettingOptionsChunkSizesFiller (const SettingConstPtr & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsMemorySizesFiller()
void CServicesSettings::SettingOptionsMemorySizesFiller (const SettingConstPtr & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsReadFactorsFiller()
void CServicesSettings::SettingOptionsReadFactorsFiller (const SettingConstPtr & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
The documentation for this class was generated from the following files:
ServicesSettings.h
ServicesSettings.cpp