Kodi Documentation: CGUITextureManager Class Reference
CGUITextureManager Class Reference
Guilib classes » Graphics and Screen » Textures and Fonts
#include <TextureManager.h>
Public Member Functions
CGUITextureManager (void)
virtual ~CGUITextureManager (void)
bool HasTexture (const std::string &textureName, std::string *path=NULL, int *bundle=NULL, int *size=NULL)
const CTextureArray & Load (const std::string &strTextureName, bool checkBundleOnly=false)
void ReleaseTexture (const std::string &strTextureName, bool immediately=false)
void Cleanup ()
void Dump () const
uint32_t GetMemoryUsage () const
void Flush ()
std::string GetTexturePath (const std::string &textureName, bool directory=false)
std::vector< std::string > GetBundledTexturesFromPath (const std::string &texturePath)
void AddTexturePath (const std::string &texturePath)
Add a new path to the paths to check when loading media.
void SetTexturePath (const std::string &texturePath)
Set a single path as the path to check when loading media (clear then add)
void RemoveTexturePath (const std::string &texturePath)
Remove a path from the paths to check when loading media.
void FreeUnusedTextures (unsigned int timeDelay=0)
Free textures (called from app thread only)
void ReleaseHwTexture (unsigned int texture)
Static Public Member Functions
static bool CanLoad (const std::string &texturePath)
Returns true if the texture manager can load this texture.
Protected Types
typedef std::vector< CTextureMap * >::iterator ivecTextures
Protected Attributes
std::vector< CTextureMap * > m_vecTextures
std::list< std::pair< CTextureMap *, std::chrono::time_point< std::chrono::steady_clock > > > m_unusedTextures
std::vector< unsigned int > m_unusedHwTextures
CTextureBundle m_TexBundle [2]
std::vector< std::string > m_texturePaths
CCriticalSection m_section
Member Typedef Documentation
ivecTextures
typedef std::vector<CTextureMap*>::iterator CGUITextureManager::ivecTextures protected
Constructor & Destructor Documentation
CGUITextureManager()
CGUITextureManager::CGUITextureManager (void)
References m_TexBundle, and CTextureBundle::SetThemeBundle().
~CGUITextureManager()
CGUITextureManager::~CGUITextureManager (void) virtual
References Cleanup().
Member Function Documentation
AddTexturePath()
void CGUITextureManager::AddTexturePath (const std::string & texturePath)
Add a new path to the paths to check when loading media.
References m_section, and m_texturePaths.
Referenced by XBMCAddon::xbmcgui::WindowXML::AllocResources(), ADDON::CGUIAddonWindow::AllocResources(), XBMCAddon::xbmcgui::WindowXML::Process(), ADDON::CGUIAddonWindow::Render(), and SetTexturePath().
CanLoad()
bool CGUITextureManager::CanLoad (const std::string & texturePath) static
Returns true if the texture manager can load this texture.
References URIUtils::IsHD().
Referenced by CGUITexture::AllocResources(), and HasTexture().
Cleanup()
void CGUITextureManager::Cleanup ()
References CTextureBundle::Close(), FreeUnusedTextures(), CTextureMap::GetName(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGWARNING, m_TexBundle, and m_vecTextures.
Referenced by CApplicationSkinHandling::UnloadSkin(), and ~CGUITextureManager().
Dump()
void CGUITextureManager::Dump () const
References CTextureMap::Dump(), CTextureMap::IsEmpty(), CLog::Log(), LOGDEBUG, and m_vecTextures.
Flush()
void CGUITextureManager::Flush ()
References CTextureMap::Flush(), CServiceBroker::GetWinSystem(), CTextureMap::IsEmpty(), and m_vecTextures.
FreeUnusedTextures()
void CGUITextureManager::FreeUnusedTextures (unsigned int timeDelay = 0)
Free textures (called from app thread only)
References CServiceBroker::GetWinSystem(), m_unusedHwTextures, and m_unusedTextures.
Referenced by Cleanup(), and CApplication::ProcessSlow().
GetBundledTexturesFromPath()
std::vector< std::string > CGUITextureManager::GetBundledTexturesFromPath (const std::string & texturePath)
References CTextureBundle::GetTexturesFromPath(), and m_TexBundle.
Referenced by CGUIMultiImage::LoadDirectory().
GetMemoryUsage()
unsigned int CGUITextureManager::GetMemoryUsage () const
References CTextureMap::GetMemoryUsage(), and m_vecTextures.
GetTexturePath()
std::string CGUITextureManager::GetTexturePath (const std::string & textureName, bool directory = false)
References URIUtils::AddFileToFolder(), XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), CLog::Log(), LOGDEBUG, m_section, and m_texturePaths.
Referenced by CImageLoader::DoWork(), CGUIMultiImage::CMultiImageJob::DoWork(), and HasTexture().
HasTexture()
bool CGUITextureManager::HasTexture (const std::string & textureName, std::string * path = NULL, int * bundle = NULL, int * size = NULL)
References CanLoad(), CTextureMap::GetName(), GetTexturePath(), m_section, m_TexBundle, m_vecTextures, and CTextureBundle::Normalize().
Referenced by XFILE::GenerateGameListing(), XFILE::GenerateTypeListing(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectory(), XFILE::CSourcesDirectory::GetDirectory(), Load(), and XBMCAddon::xbmc::skinHasImage().
Load()
const CTextureArray & CGUITextureManager::Load (const std::string & strTextureName, bool checkBundleOnly = false)
References CTextureMap::Add(), CTexture::CreateTexture(), end(), CTextureMap::GetMemoryUsage(), CTextureMap::GetName(), CTextureMap::GetTexture(), CServiceBroker::GetWinSystem(), HasTexture(), IImage::Height(), CFFmpegImage::Initialize(), CTextureBundle::LoadAnim(), CTexture::LoadFromFile(), CTextureBundle::LoadTexture(), CLog::Log(), LOGDEBUG, LOGERROR, m_TexBundle, m_unusedTextures, m_vecTextures, CFFmpegImage::ReadFrame(), CTextureMap::SetHeight(), CTextureMap::SetWidth(), CTextureArray::size(), IImage::Width(), and XB_FMT_A8R8G8B8.
Referenced by CGUITexture::AllocResources().
ReleaseHwTexture()
void CGUITextureManager::ReleaseHwTexture (unsigned int texture)
References CServiceBroker::GetWinSystem(), and m_unusedHwTextures.
Referenced by CGUIFontTTFGL::DeleteHardwareTexture(), CGUIFontTTFGLES::DeleteHardwareTexture(), CGLTexture::DestroyTextureObject(), CGLESTexture::DestroyTextureObject(), CGUIFontTTFGL::FirstBegin(), and CGUIFontTTFGLES::FirstBegin().
ReleaseTexture()
void CGUITextureManager::ReleaseTexture (const std::string & strTextureName, bool immediately = false)
References CTextureMap::GetName(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGWARNING, m_unusedTextures, m_vecTextures, and CTextureMap::Release().
Referenced by CGUITexture::FreeResources().
RemoveTexturePath()
void CGUITextureManager::RemoveTexturePath (const std::string & texturePath)
Remove a path from the paths to check when loading media.
References m_section, and m_texturePaths.
Referenced by XBMCAddon::xbmcgui::WindowXML::AllocResources(), ADDON::CGUIAddonWindow::AllocResources(), XBMCAddon::xbmcgui::WindowXML::Process(), and ADDON::CGUIAddonWindow::Render().
SetTexturePath()
void CGUITextureManager::SetTexturePath (const std::string & texturePath)
Set a single path as the path to check when loading media (clear then add)
References AddTexturePath(), m_section, and m_texturePaths.
Referenced by CGraphicContext::SetMediaDir().
Member Data Documentation
m_section
CCriticalSection CGUITextureManager::m_section protected
Referenced by AddTexturePath(), GetTexturePath(), HasTexture(), RemoveTexturePath(), and SetTexturePath().
m_TexBundle
CTextureBundle CGUITextureManager::m_TexBundle[2] protected
Referenced by CGUITextureManager(), Cleanup(), GetBundledTexturesFromPath(), HasTexture(), and Load().
m_texturePaths
std::vector<std::string> CGUITextureManager::m_texturePaths protected
Referenced by AddTexturePath(), GetTexturePath(), RemoveTexturePath(), and SetTexturePath().
m_unusedHwTextures
std::vector<unsigned int> CGUITextureManager::m_unusedHwTextures protected
Referenced by FreeUnusedTextures(), and ReleaseHwTexture().
m_unusedTextures
std::list<std::pair<CTextureMap*, std::chrono::time_point<std::chrono::steady_clock> > > CGUITextureManager::m_unusedTextures protected
Referenced by FreeUnusedTextures(), Load(), and ReleaseTexture().
m_vecTextures
std::vector<CTextureMap*> CGUITextureManager::m_vecTextures protected
Referenced by Cleanup(), Dump(), Flush(), GetMemoryUsage(), HasTexture(), Load(), and ReleaseTexture().
The documentation for this class was generated from the following files:
TextureManager.h
TextureManager.cpp