Kodi Documentation: class JoystickFeature
class JoystickFeature
C++ » Interface - kodi::addon » Addon type instances » Peripheral » Definitions, structures and enumerators » 4. Joystick
Base class for joystick feature primitives
Classes
class kodi::addon::JoystickFeature
Functions
kodi::addon::JoystickFeature::JoystickFeature (const std::string &name="", JOYSTICK_FEATURE_TYPE type=JOYSTICK_FEATURE_TYPE_UNKNOWN)
Class constructor.
kodi::addon::JoystickFeature::JoystickFeature (const JoystickFeature &other)
Class copy constructor.
JoystickFeature & kodi::addon::JoystickFeature::operator= (const JoystickFeature &rhs)
Copy data from another JoystickFeature class to here.
bool kodi::addon::JoystickFeature::operator== (const JoystickFeature &other) const
Compare this with another class of this type.
const std::string & kodi::addon::JoystickFeature::Name (void) const
Get name of feature.
JOYSTICK_FEATURE_TYPE kodi::addon::JoystickFeature::Type (void) const
Get name of feature.
bool kodi::addon::JoystickFeature::IsValid () const
Check this feature is valid.
void kodi::addon::JoystickFeature::SetName (const std::string &name)
Set name of feature.
void kodi::addon::JoystickFeature::SetType (JOYSTICK_FEATURE_TYPE type)
Set type of feature.
void kodi::addon::JoystickFeature::SetInvalid (void)
Set type as invalid.
const DriverPrimitive & kodi::addon::JoystickFeature::Primitive (JOYSTICK_FEATURE_PRIMITIVE which) const
Get primitive of feature by wanted type.
void kodi::addon::JoystickFeature::SetPrimitive (JOYSTICK_FEATURE_PRIMITIVE which, const DriverPrimitive &primitive)
Set primitive for feature by wanted type.
std::array< DriverPrimitive, JOYSTICK_PRIMITIVE_MAX > & kodi::addon::JoystickFeature::Primitives ()
Get all primitives on this class.
const std::array< DriverPrimitive, JOYSTICK_PRIMITIVE_MAX > & kodi::addon::JoystickFeature::Primitives () const
Get all primitives on this class (as constant).
Detailed Description
Base class for joystick feature primitives
Class for joystick features. A feature can be:
scalar [1]
analog stick
accelerometer
motor
relative pointer [2]
absolute pointer
wheel
throttle
keyboard key
[1] All three driver primitives (buttons, hats and axes) have a state that can be represented using a single scalar value. For this reason, features that map to a single primitive are called "scalar features".
[2] Relative pointers are similar to analog sticks, but they use relative distances instead of positions.
Function Documentation
IsValid()
bool kodi::addon::JoystickFeature::IsValid () const inline
Check this feature is valid.
Returns
True if valid (type != JOYSTICK_FEATURE_TYPE_UNKNOWN), false otherwise
References JOYSTICK_FEATURE_TYPE_UNKNOWN, and kodi::addon::JoystickFeature::m_type.
JoystickFeature() [1/2]
kodi::addon::JoystickFeature::JoystickFeature (const JoystickFeature & other) inline
Class copy constructor.
Parameters
[in] other Other class to copy on construct here
JoystickFeature() [2/2]
kodi::addon::JoystickFeature::JoystickFeature (const std::string & name = "", JOYSTICK_FEATURE_TYPE type = JOYSTICK_FEATURE_TYPE_UNKNOWN) inline
Class constructor.
Parameters
[in] name [optional] Name of the feature
[in] type [optional] Type of the feature, JOYSTICK_FEATURE_TYPE_UNKNOWN as default
Name()
const std::string & kodi::addon::JoystickFeature::Name (void) const inline
Get name of feature.
Returns
Name of feature
References kodi::addon::JoystickFeature::m_name.
Referenced by PERIPHERALS::CPeripheralAddon::GetFeatures().
operator=()
JoystickFeature & kodi::addon::JoystickFeature::operator= (const JoystickFeature & rhs) inline
Copy data from another JoystickFeature class to here.
Parameters
[in] other Other class to copy here
References kodi::addon::JoystickFeature::m_name, kodi::addon::JoystickFeature::m_primitives, and kodi::addon::JoystickFeature::m_type.
operator==()
bool kodi::addon::JoystickFeature::operator== (const JoystickFeature & other) const inline
Compare this with another class of this type.
Parameters
[in] other Other class to compare
Returns
True if they are equal, false otherwise
References kodi::addon::JoystickFeature::m_name, kodi::addon::JoystickFeature::m_primitives, and kodi::addon::JoystickFeature::m_type.
Primitive()
const DriverPrimitive & kodi::addon::JoystickFeature::Primitive (JOYSTICK_FEATURE_PRIMITIVE which) const inline
Get primitive of feature by wanted type.
Parameters
[in] which Type of feature, defined with JOYSTICK_FEATURE_PRIMITIVE
Returns
Primitive of asked type
References kodi::addon::JoystickFeature::m_primitives.
Referenced by PERIPHERALS::CAddonButtonMap::AddAnalogStick(), PERIPHERALS::CAddonButtonMap::AddRelativePointer(), PERIPHERALS::CAddonButtonMap::AddThrottle(), PERIPHERALS::CAddonButtonMap::AddWheel(), PERIPHERALS::CAddonButtonMap::CreateLookupTable(), PERIPHERALS::CAddonButtonMap::GetAccelerometer(), PERIPHERALS::CAddonButtonMap::GetAnalogStick(), PERIPHERALS::CAddonButtonMap::GetKey(), PERIPHERALS::CAddonButtonMap::GetRelativePointer(), PERIPHERALS::CAddonButtonMap::GetScalar(), PERIPHERALS::CAddonButtonMap::GetThrottle(), and PERIPHERALS::CAddonButtonMap::GetWheel().
Primitives() [1/2]
std::array< DriverPrimitive, JOYSTICK_PRIMITIVE_MAX > & kodi::addon::JoystickFeature::Primitives () inline
Get all primitives on this class.
Returns
Array list of primitives
References kodi::addon::JoystickFeature::m_primitives.
Primitives() [2/2]
const std::array< DriverPrimitive, JOYSTICK_PRIMITIVE_MAX > & kodi::addon::JoystickFeature::Primitives () const inline
Get all primitives on this class (as constant).
Returns
Constant array list of primitives
References kodi::addon::JoystickFeature::m_primitives.
SetInvalid()
void kodi::addon::JoystickFeature::SetInvalid (void) inline
Set type as invalid.
References JOYSTICK_FEATURE_TYPE_UNKNOWN, and kodi::addon::JoystickFeature::m_type.
SetName()
void kodi::addon::JoystickFeature::SetName (const std::string & name) inline
Set name of feature.
Parameters
[in] name Name of feature
References kodi::addon::JoystickFeature::m_name, and name.
SetPrimitive()
void kodi::addon::JoystickFeature::SetPrimitive (JOYSTICK_FEATURE_PRIMITIVE which, const DriverPrimitive & primitive) inline
Set primitive for feature by wanted type.
Parameters
[in] which Type of feature, defined with JOYSTICK_FEATURE_PRIMITIVE
[in] primitive The with DriverPrimitive defined primitive to set
References kodi::addon::JoystickFeature::m_primitives.
Referenced by PERIPHERALS::CAddonButtonMap::AddAccelerometer(), PERIPHERALS::CAddonButtonMap::AddAnalogStick(), PERIPHERALS::CAddonButtonMap::AddKey(), PERIPHERALS::CAddonButtonMap::AddRelativePointer(), PERIPHERALS::CAddonButtonMap::AddScalar(), PERIPHERALS::CAddonButtonMap::AddThrottle(), and PERIPHERALS::CAddonButtonMap::AddWheel().
SetType()
void kodi::addon::JoystickFeature::SetType (JOYSTICK_FEATURE_TYPE type) inline
Set type of feature.
Parameters
[in] type Type of feature
References kodi::addon::JoystickFeature::m_type.
Type()
JOYSTICK_FEATURE_TYPE kodi::addon::JoystickFeature::Type (void) const inline
Get name of feature.
Returns
Type of feature defined with JOYSTICK_FEATURE_TYPE
References kodi::addon::JoystickFeature::m_type.
Referenced by PERIPHERALS::CAddonButtonMap::CreateLookupTable(), PERIPHERALS::CAddonButtonMap::GetAccelerometer(), PERIPHERALS::CAddonButtonMap::GetAnalogStick(), PERIPHERALS::CPeripheralAddon::GetFeatures(), PERIPHERALS::CAddonButtonMap::GetKey(), PERIPHERALS::CAddonButtonMap::GetRelativePointer(), PERIPHERALS::CAddonButtonMap::GetScalar(), PERIPHERALS::CAddonButtonMap::GetThrottle(), and PERIPHERALS::CAddonButtonMap::GetWheel().