Kodi Documentation: TestDefaultKeyboardTranslator.cpp File Reference
TestDefaultKeyboardTranslator.cpp File Reference
#include "ServiceBroker.h"
#include "addons/AddonManager.h"
#include "addons/addoninfo/AddonType.h"
#include "games/controllers/Controller.h"
#include "games/controllers/ControllerIDs.h"
#include "games/controllers/input/DefaultKeyboardTranslator.h"
#include "games/controllers/input/PhysicalFeature.h"
#include <gtest/gtest.h>
Namespaces
namespace anonymous_namespace{TestDefaultKeyboardTranslator.cpp}
Functions
KEYBOARD::XBMCKey anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetKeycode (KEYBOARD::XBMCKey keysym, const ControllerPtr &controller, unsigned int &count)
const GAME::ControllerPtr anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetController ()
TEST (TestDefaultKeyboardTranslator, TranslateKeycode)
Function Documentation
TEST()
TEST (TestDefaultKeyboardTranslator , TranslateKeycode)
References EXPECT_EQ(), anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetController(), anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetKeycode(), XBMCK_0, XBMCK_1, XBMCK_2, XBMCK_3, XBMCK_4, XBMCK_5, XBMCK_6, XBMCK_7, XBMCK_8, XBMCK_9, XBMCK_a, XBMCK_AMPERSAND, XBMCK_ASTERISK, XBMCK_AT, XBMCK_b, XBMCK_BACKQUOTE, XBMCK_BACKSLASH, XBMCK_BACKSPACE, XBMCK_BREAK, XBMCK_c, XBMCK_CAPSLOCK, XBMCK_CARET, XBMCK_CLEAR, XBMCK_COLON, XBMCK_COMMA, XBMCK_COMPOSE, XBMCK_d, XBMCK_DELETE, XBMCK_DOLLAR, XBMCK_DOWN, XBMCK_e, XBMCK_END, XBMCK_EQUALS, XBMCK_ESCAPE, XBMCK_EURO, XBMCK_EXCLAIM, XBMCK_f, XBMCK_F1, XBMCK_F10, XBMCK_F11, XBMCK_F12, XBMCK_F13, XBMCK_F14, XBMCK_F15, XBMCK_F2, XBMCK_F3, XBMCK_F4, XBMCK_F5, XBMCK_F6, XBMCK_F7, XBMCK_F8, XBMCK_F9, XBMCK_g, XBMCK_GREATER, XBMCK_h, XBMCK_HASH, XBMCK_HELP, XBMCK_HOME, XBMCK_i, XBMCK_INSERT, XBMCK_j, XBMCK_k, XBMCK_KP0, XBMCK_KP1, XBMCK_KP2, XBMCK_KP3, XBMCK_KP4, XBMCK_KP5, XBMCK_KP6, XBMCK_KP7, XBMCK_KP8, XBMCK_KP9, XBMCK_KP_DIVIDE, XBMCK_KP_ENTER, XBMCK_KP_EQUALS, XBMCK_KP_MINUS, XBMCK_KP_MULTIPLY, XBMCK_KP_PERIOD, XBMCK_KP_PLUS, XBMCK_l, XBMCK_LALT, XBMCK_LCTRL, XBMCK_LEFT, XBMCK_LEFTBRACE, XBMCK_LEFTBRACKET, XBMCK_LEFTPAREN, XBMCK_LESS, XBMCK_LMETA, XBMCK_LSHIFT, XBMCK_LSUPER, XBMCK_m, XBMCK_MENU, XBMCK_MINUS, XBMCK_MODE, XBMCK_n, XBMCK_NUMLOCK, XBMCK_o, XBMCK_OEM_102, XBMCK_p, XBMCK_PAGEDOWN, XBMCK_PAGEUP, XBMCK_PAUSE, XBMCK_PERIOD, XBMCK_PIPE, XBMCK_PLUS, XBMCK_POWER, XBMCK_PRINT, XBMCK_q, XBMCK_QUESTION, XBMCK_QUOTE, XBMCK_QUOTEDBL, XBMCK_r, XBMCK_RALT, XBMCK_RCTRL, XBMCK_RETURN, XBMCK_RIGHT, XBMCK_RIGHTBRACE, XBMCK_RIGHTBRACKET, XBMCK_RIGHTPAREN, XBMCK_RMETA, XBMCK_RSHIFT, XBMCK_RSUPER, XBMCK_s, XBMCK_SCROLLOCK, XBMCK_SEMICOLON, XBMCK_SLASH, XBMCK_SPACE, XBMCK_SYSREQ, XBMCK_t, XBMCK_TAB, XBMCK_TILDE, XBMCK_u, XBMCK_UNDERSCORE, XBMCK_UNDO, XBMCK_UP, XBMCK_v, XBMCK_w, XBMCK_x, XBMCK_y, and XBMCK_z.