Kodi Documentation: CDVDDemux Class Reference
CDVDDemux Class Reference abstract
#include <DVDDemux.h>
Public Member Functions
CDVDDemux ()
virtual ~CDVDDemux ()=default
virtual bool Reset ()=0
virtual void Abort ()
virtual void Flush ()=0
virtual DemuxPacket * Read ()=0
virtual bool SeekTime (double time, bool backwards=false, double *startpts=NULL)=0
virtual bool SeekChapter (int chapter, double *startpts=NULL)
virtual int GetChapterCount ()
virtual int GetChapter ()
virtual void GetChapterName (std::string &strChapterName, int chapterIdx=-1)
virtual int64_t GetChapterPos (int chapterIdx=-1)
virtual void SetSpeed (int iSpeed)
virtual void FillBuffer (bool mode)
virtual int GetStreamLength ()
virtual CDemuxStream * GetStream (int64_t demuxerId, int iStreamId) const
virtual std::vector< CDemuxStream * > GetStreams () const =0
virtual int GetNrOfStreams () const =0
virtual int GetPrograms (std::vector< ProgramInfo > &programs)
virtual void SetProgram (int progId)
virtual std::string GetFileName ()
int GetNrOfSubtitleStreams ()
virtual std::string GetStreamCodecName (int64_t demuxerId, int iStreamId)
virtual void EnableStream (int64_t demuxerId, int id, bool enable)
virtual void OpenStream (int64_t demuxerId, int id)
virtual void SetVideoResolution (unsigned int width, unsigned int height)
int64_t GetDemuxerId ()
Protected Member Functions
virtual void EnableStream (int id, bool enable)
virtual void OpenStream (int id)
virtual CDemuxStream * GetStream (int iStreamId) const =0
virtual std::string GetStreamCodecName (int iStreamId)
int GetNrOfStreams (StreamType streamType)
Protected Attributes
int64_t m_demuxerId
Private Member Functions
int64_t NewGuid ()
Constructor & Destructor Documentation
CDVDDemux()
CDVDDemux::CDVDDemux () inline
~CDVDDemux()
virtual CDVDDemux::~CDVDDemux () virtual default
Member Function Documentation
Abort()
virtual void CDVDDemux::Abort () inline virtual
Reimplemented in CDemuxMultiSource, CDVDDemuxBXA, CDVDDemuxCDDA, CDVDDemuxClient, and CDVDDemuxFFmpeg.
EnableStream() [1/2]
virtual void CDVDDemux::EnableStream (int id, bool enable) inline protected virtual
Reimplemented in CDVDDemuxClient, and CDVDDemuxVobsub.
EnableStream() [2/2]
virtual void CDVDDemux::EnableStream (int64_t demuxerId, int id, bool enable) inline virtual
Reimplemented in CDemuxMultiSource.
References EnableStream().
Referenced by EnableStream().
FillBuffer()
virtual void CDVDDemux::FillBuffer (bool mode) inline virtual
Reimplemented in CDVDDemuxClient.
Flush()
virtual void CDVDDemux::Flush () pure virtual
Implemented in CDemuxMultiSource, CDVDDemuxBXA, CDVDDemuxCC, CDVDDemuxCDDA, CDVDDemuxClient, CDVDDemuxFFmpeg, and CDVDDemuxVobsub.
GetChapter()
virtual int CDVDDemux::GetChapter () inline virtual
Reimplemented in CDVDDemuxFFmpeg.
GetChapterCount()
virtual int CDVDDemux::GetChapterCount () inline virtual
Reimplemented in CDVDDemuxFFmpeg.
GetChapterName()
virtual void CDVDDemux::GetChapterName (std::string & strChapterName, int chapterIdx = -1) inline virtual
Reimplemented in CDVDDemuxFFmpeg.
GetChapterPos()
virtual int64_t CDVDDemux::GetChapterPos (int chapterIdx = -1) inline virtual
Reimplemented in CDVDDemuxFFmpeg.
GetDemuxerId()
int64_t CDVDDemux::GetDemuxerId () inline
References m_demuxerId.
GetFileName()
virtual std::string CDVDDemux::GetFileName () inline virtual
Reimplemented in CDVDDemuxBXA, CDVDDemuxCDDA, CDVDDemuxClient, CDVDDemuxFFmpeg, and CDVDDemuxVobsub.
Referenced by CSelectionStreams::Update().
GetNrOfStreams() [1/2]
virtual int CDVDDemux::GetNrOfStreams () const pure virtual
Implemented in CDemuxMultiSource, CDVDDemuxBXA, CDVDDemuxCC, CDVDDemuxCDDA, CDVDDemuxClient, CDVDDemuxFFmpeg, and CDVDDemuxVobsub.
Referenced by GetNrOfSubtitleStreams().
GetNrOfStreams() [2/2]
int CDVDDemux::GetNrOfStreams (StreamType streamType) protected
References GetStreams().
GetNrOfSubtitleStreams()
int CDVDDemux::GetNrOfSubtitleStreams ()
References GetNrOfStreams(), and STREAM_SUBTITLE.
GetPrograms()
virtual int CDVDDemux::GetPrograms (std::vector< ProgramInfo > & programs) inline virtual
Reimplemented in CDVDDemuxFFmpeg.
GetStream() [1/2]
virtual CDemuxStream * CDVDDemux::GetStream (int iStreamId) const protected pure virtual
Implemented in CDVDDemuxVobsub, CDemuxMultiSource, CDVDDemuxBXA, CDVDDemuxCC, CDVDDemuxCDDA, CDVDDemuxClient, and CDVDDemuxFFmpeg.
GetStream() [2/2]
virtual CDemuxStream * CDVDDemux::GetStream (int64_t demuxerId, int iStreamId) const inline virtual
Reimplemented in CDemuxMultiSource.
References GetStream().
Referenced by GetStream().
GetStreamCodecName() [1/2]
virtual std::string CDVDDemux::GetStreamCodecName (int iStreamId) inline protected virtual
Reimplemented in CDVDDemuxBXA, CDVDDemuxCDDA, CDVDDemuxClient, and CDVDDemuxFFmpeg.
GetStreamCodecName() [2/2]
virtual std::string CDVDDemux::GetStreamCodecName (int64_t demuxerId, int iStreamId) inline virtual
Reimplemented in CDemuxMultiSource.
References GetStreamCodecName().
Referenced by CDVDFileInfo::DemuxerToStreamDetails(), GetStreamCodecName(), VideoPlayerCodec::Init(), and CSelectionStreams::Update().
GetStreamLength()
virtual int CDVDDemux::GetStreamLength () inline virtual
Reimplemented in CDemuxMultiSource, CDVDDemuxBXA, CDVDDemuxCDDA, and CDVDDemuxFFmpeg.
Referenced by CDVDFileInfo::DemuxerToStreamDetails(), and VideoPlayerCodec::Init().
GetStreams()
virtual std::vector< CDemuxStream * > CDVDDemux::GetStreams () const pure virtual
Implemented in CDemuxMultiSource, CDVDDemuxBXA, CDVDDemuxCC, CDVDDemuxCDDA, CDVDDemuxClient, CDVDDemuxFFmpeg, and CDVDDemuxVobsub.
Referenced by CDVDFileInfo::DemuxerToStreamDetails(), GetNrOfStreams(), VideoPlayerCodec::Init(), and CSelectionStreams::Update().
NewGuid()
int64_t CDVDDemux::NewGuid () inline private
References int64_t().
OpenStream() [1/2]
virtual void CDVDDemux::OpenStream (int id) inline protected virtual
Reimplemented in CDVDDemuxClient.
OpenStream() [2/2]
virtual void CDVDDemux::OpenStream (int64_t demuxerId, int id) inline virtual
References OpenStream().
Referenced by OpenStream().
Read()
virtual DemuxPacket * CDVDDemux::Read () pure virtual
Implemented in CDemuxMultiSource, CDVDDemuxBXA, CDVDDemuxCC, CDVDDemuxCDDA, CDVDDemuxClient, CDVDDemuxFFmpeg, and CDVDDemuxVobsub.
Referenced by VideoPlayerCodec::ReadPCM(), and VideoPlayerCodec::ReadRaw().
Reset()
virtual bool CDVDDemux::Reset () pure virtual
Implemented in CDemuxMultiSource, CDVDDemuxBXA, CDVDDemuxCC, CDVDDemuxCDDA, CDVDDemuxClient, CDVDDemuxFFmpeg, and CDVDDemuxVobsub.
Referenced by VideoPlayerCodec::Init().
SeekChapter()
virtual bool CDVDDemux::SeekChapter (int chapter, double * startpts = NULL) inline virtual
Reimplemented in CDVDDemuxFFmpeg.
SeekTime()
virtual bool CDVDDemux::SeekTime (double time, bool backwards = false, double * startpts = NULL) pure virtual
Implemented in CDVDDemuxVobsub, CDemuxMultiSource, CDVDDemuxBXA, CDVDDemuxCC, CDVDDemuxCDDA, CDVDDemuxClient, and CDVDDemuxFFmpeg.
Referenced by VideoPlayerCodec::Seek().
SetProgram()
virtual void CDVDDemux::SetProgram (int progId) inline virtual
Reimplemented in CDVDDemuxFFmpeg.
SetSpeed()
virtual void CDVDDemux::SetSpeed (int iSpeed) inline virtual
Reimplemented in CDVDDemuxClient, and CDVDDemuxFFmpeg.
SetVideoResolution()
virtual void CDVDDemux::SetVideoResolution (unsigned int width, unsigned int height) inline virtual
Reimplemented in CDVDDemuxClient.
Member Data Documentation
m_demuxerId
int64_t CDVDDemux::m_demuxerId protected
Referenced by CDVDDemuxFFmpeg::AddStream(), GetDemuxerId(), CDVDDemuxVobsub::ParseId(), CDVDDemuxClient::Read(), and CDVDDemuxFFmpeg::ReadInternal().
The documentation for this class was generated from the following files:
DVDDemux.h
DVDDemux.cpp