Kodi Documentation: KODI::PLAYLIST::CPlayListPlayer Class Reference
KODI::PLAYLIST::CPlayListPlayer Class Reference
#include <PlayListPlayer.h>
Public Member Functions
CPlayListPlayer (void)
~CPlayListPlayer (void) override
bool OnMessage (CGUIMessage &message) override
int GetMessageMask () override
Should return the message mask that it wishes to receive messages for.
void OnApplicationMessage (KODI::MESSAGING::ThreadMessage *pMsg) override
This gets called whenever a message matching the registered message mask is processed.
bool PlayNext (int offset=1, bool autoPlay=false)
Play the next (or another) entry in the current playlist.
bool PlayPrevious ()
Play the previous entry in the current playlist.
bool PlayItemIdx (int itemIdx)
bool Play ()
bool Play (const CFileItemPtr &pItem, const std::string &player, bool forceSelection=false)
Creates a new playlist for an item and starts playing it.
bool Play (int index, const std::string &player, bool replace=false, bool playPreviousOnFail=false, bool forceSelection=false)
Start playing a particular entry in the current playlist.
int GetCurrentItemIdx () const
Returns the index of the current item in active playlist.
void SetCurrentItemIdx (int index)
Change the current item in the active playlist.
int GetNextItemIdx ()
int GetNextItemIdx (int offset) const
Get the index in the playlist that is offset away from the current index in the current playlist. Obeys any repeat settings (eg repeat one will return the current index regardless of offset)
void SetCurrentPlaylist (Id playlistId)
Set the active playlist.
Id GetCurrentPlaylist () const
Get the currently active playlist.
CPlayList & GetPlaylist (Id playlistId)
Get a particular playlist object.
const CPlayList & GetPlaylist (Id playlistId) const
int RemoveDVDItems ()
Removes any item from all playlists located on a removable share.
void Reset ()
Resets the current song and unplayable counts. Does not alter the active playlist.
void ClearPlaylist (Id playlistId)
void Clear ()
void SetShuffle (Id playlistId, bool shuffle, bool notify=false)
Set shuffle state of a playlist. If the shuffle state changes, the playlist is shuffled or unshuffled. Has no effect if Party Mode is enabled.
bool IsShuffled (Id playlistId) const
Return whether a playlist is shuffled. If partymode is enabled, this always returns false.
bool HasPlayedFirstFile () const
Return whether or not something has been played yet from the current playlist.
void SetRepeat (Id playlistId, RepeatState state, bool notify=false)
Set repeat state of a playlist. If called while in Party Mode, repeat is disabled.
RepeatState GetRepeat (Id playlistId) const
void Add (Id playlistId, const CPlayList &playlist)
void Add (Id playlistId, const CFileItemPtr &pItem)
void Add (Id playlistId, const CFileItemList &items)
void Insert (Id playlistId, const CPlayList &playlist, int iIndex)
void Insert (Id playlistId, const CFileItemPtr &pItem, int iIndex)
void Insert (Id playlistId, const CFileItemList &items, int iIndex)
void Remove (Id playlistId, int iPosition)
void Swap (Id playlistId, int indexItem1, int indexItem2)
bool IsSingleItemNonRepeatPlaylist () const
bool OnAction (const CAction &action)
Public Member Functions inherited from IMsgTargetCallback
virtual ~IMsgTargetCallback ()=default
Public Member Functions inherited from KODI::MESSAGING::IMessageTarget
virtual ~IMessageTarget ()=default
Protected Member Functions
bool Repeated (Id playlistId) const
Returns true if the given is set to repeat all.
bool RepeatedOne (Id playlistId) const
Returns true if the given is set to repeat one.
void ReShuffle (Id playlistId, int iPosition)
void AnnouncePropertyChanged (Id playlistId, const std::string &strProperty, const CVariant &value)
Protected Attributes
bool m_bPlayedFirstFile
bool m_bPlaybackStarted
int m_iFailedSongs
std::chrono::time_point< std::chrono::steady_clock > m_failedSongsStart
int m_iCurrentSong
Id m_iCurrentPlayList {Id::TYPE_NONE}
CPlayList * m_PlaylistMusic
CPlayList * m_PlaylistVideo
CPlayList * m_PlaylistEmpty
std::map< Id, RepeatState > m_repeatState
Constructor & Destructor Documentation
CPlayListPlayer()
KODI::PLAYLIST::CPlayListPlayer::CPlayListPlayer (void)
References m_bPlaybackStarted, m_bPlayedFirstFile, m_failedSongsStart, m_iCurrentSong, m_iFailedSongs, m_PlaylistEmpty, m_PlaylistMusic, m_PlaylistVideo, KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
~CPlayListPlayer()
KODI::PLAYLIST::CPlayListPlayer::~CPlayListPlayer (void) override
References Clear(), m_PlaylistEmpty, m_PlaylistMusic, and m_PlaylistVideo.
Member Function Documentation
Add() [1/3]
void KODI::PLAYLIST::CPlayListPlayer::Add (Id playlistId, const CFileItemList & items)
References KODI::PLAYLIST::CPlayList::Add(), CServiceBroker::GetGUI(), GetPlaylist(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLIST_CHANGED, KODI::PLAYLIST::CPlayList::IsShuffled(), ReShuffle(), CGUIWindowManager::SendMessage(), KODI::PLAYLIST::CPlayList::size(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Add() [2/3]
void KODI::PLAYLIST::CPlayListPlayer::Add (Id playlistId, const CFileItemPtr & pItem)
References KODI::PLAYLIST::CPlayList::Add(), CServiceBroker::GetGUI(), GetPlaylist(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLIST_CHANGED, KODI::PLAYLIST::CPlayList::IsShuffled(), ReShuffle(), CGUIWindowManager::SendMessage(), KODI::PLAYLIST::CPlayList::size(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Add() [3/3]
void KODI::PLAYLIST::CPlayListPlayer::Add (Id playlistId, const CPlayList & playlist)
References KODI::PLAYLIST::CPlayList::Add(), GetPlaylist(), KODI::PLAYLIST::CPlayList::IsShuffled(), playlist, ReShuffle(), KODI::PLAYLIST::CPlayList::size(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Referenced by CGUIMediaWindow::OnPlayAndQueueMedia(), Play(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::PlayItem(), CApplication::ProcessAndStartPlaylist(), CApplication::Run(), and CGUIMediaWindow::UpdateFileList().
AnnouncePropertyChanged()
void KODI::PLAYLIST::CPlayListPlayer::AnnouncePropertyChanged (Id playlistId, const std::string & strProperty, const CVariant & value) protected
References data(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppComponents(), ANNOUNCEMENT::Player, KODI::PLAYLIST::TYPE_MUSIC, KODI::PLAYLIST::TYPE_VIDEO, and value.
Referenced by SetRepeat(), and SetShuffle().
Clear()
void KODI::PLAYLIST::CPlayListPlayer::Clear ()
References KODI::PLAYLIST::CPlayList::Clear(), m_PlaylistEmpty, m_PlaylistMusic, and m_PlaylistVideo.
Referenced by CApplication::Cleanup(), ClearPlaylist(), and ~CPlayListPlayer().
ClearPlaylist()
void KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist (Id playlistId)
References g_application, CServiceBroker::GetGUI(), GetPlaylist(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLIST_CHANGED, playlist, and CGUIWindowManager::SendMessage().
Referenced by CGUIWindowMusicPlayList::ClearPlayList(), CGUIWindowVideoPlaylist::ClearPlayList(), CPartyModeManager::Enable(), CProfileManager::FinalizeLoadProfile(), XBMCAddon::xbmc::PlayList::load(), CGUIMediaWindow::OnPlayAndQueueMedia(), Play(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::PlayItem(), CApplication::ProcessAndStartPlaylist(), and CGUIMediaWindow::UpdateFileList().
GetCurrentItemIdx()
int KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx () const
Returns the index of the current item in active playlist.
Returns
Current item in the active playlist.
See also
SetCurrentItemIdx
References m_iCurrentSong.
Referenced by AnnounceBridge(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), CGUIWindowMusicPlayList::GetContextButtons(), CGUIWindowVideoPlaylist::GetContextButtons(), KODI::GUILIB::GUIINFO::GetPlaylistLabel(), XBMCAddon::xbmc::PlayList::getposition(), JSONRPC::CPlayerOperations::GetPropertyValue(), CGUIWindowMusicPlayList::MoveCurrentPlayListItem(), CGUIWindowVideoPlaylist::MoveCurrentPlayListItem(), CPartyModeManager::MovePlaying(), CApplication::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), MUSIC_UTILS::QueueItem(), CPartyModeManager::ReapSongs(), JSONRPC::CPlaylistOperations::Remove(), CGUIWindowMusicPlayList::RemovePlayListItem(), CGUIWindowVideoPlaylist::RemovePlayListItem(), and CGUIMediaWindow::UpdateFileList().
GetCurrentPlaylist()
Id KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist () const
Get the currently active playlist.
Returns
Id of playlist
See also
SetCurrentPlaylist, GetPlaylist
References m_iCurrentPlayList.
Referenced by CPartyModeManager::Announce(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), GetNextItemIdx(), GetNextItemIdx(), JSONRPC::CPlayerOperations::GetPlaylist(), KODI::GUILIB::GUIINFO::GetPlaylistLabel(), JSONRPC::CPlayerOperations::GetPropertyValue(), CApplication::OnAction(), CApplication::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CApplication::PlaybackCleanup(), PlayerControl(), CApplication::PlayFile(), JSONRPC::CPlaylistOperations::Remove(), CGUIWindowMusicPlayList::RemovePlayListItem(), CGUIWindowVideoPlaylist::RemovePlayListItem(), CGUIWindowMusicPlayList::UpdateButtons(), and CGUIWindowVideoPlaylist::UpdateButtons().
GetMessageMask()
int KODI::PLAYLIST::CPlayListPlayer::GetMessageMask () override virtual
Should return the message mask that it wishes to receive messages for.
The message mask is defined in "messaging/ApplicationMessenger.h" pick the next one available when creating a new
Implements KODI::MESSAGING::IMessageTarget.
References TMSG_MASK_PLAYLISTPLAYER.
GetNextItemIdx() [1/2]
int KODI::PLAYLIST::CPlayListPlayer::GetNextItemIdx ()
References g_partyModeManager, GetCurrentPlaylist(), CServiceBroker::GetGUI(), GetPlaylist(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLISTPLAYER_STOPPED, CPartyModeManager::IsEnabled(), CLog::Log(), LOGERROR, m_iCurrentPlayList, m_iCurrentSong, playlist, Repeated(), RepeatedOne(), Reset(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_NONE.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPlaylistInfo(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetPlaylistInfo(), CApplication::OnMessage(), and PlayNext().
GetNextItemIdx() [2/2]
int KODI::PLAYLIST::CPlayListPlayer::GetNextItemIdx (int offset) const
Get the index in the playlist that is offset away from the current index in the current playlist. Obeys any repeat settings (eg repeat one will return the current index regardless of offset)
Returns
the index of the entry, or -1 if there is no current playlist. There is no guarantee that the returned index is valid.
References g_partyModeManager, GetCurrentPlaylist(), GetPlaylist(), CPartyModeManager::IsEnabled(), m_iCurrentPlayList, m_iCurrentSong, playlist, Repeated(), RepeatedOne(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_NONE.
GetPlaylist() [1/2]
CPlayList & KODI::PLAYLIST::CPlayListPlayer::GetPlaylist (Id playlistId)
Get a particular playlist object.
Parameters
id Id of playlist
Returns
A reference to the CPlayList object.
See also
GetCurrentPlaylist
References KODI::PLAYLIST::CPlayList::Clear(), m_PlaylistEmpty, m_PlaylistMusic, m_PlaylistVideo, KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Referenced by CPartyModeManager::Add(), Add(), Add(), Add(), CPartyModeManager::AddRandomSongs(), CPartyModeManager::AddUserSongs(), CPartyModeManager::AddUserSongs(), AnnounceBridge(), ClearPlaylist(), MUSIC_UTILS::CSetArtJob::DoWork(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetBool(), XFILE::CPlaylistDirectory::GetDirectory(), GetNextItemIdx(), GetNextItemIdx(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPlaylistInfo(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetPlaylistInfo(), KODI::GUILIB::GUIINFO::GetPlaylistLabel(), Insert(), Insert(), Insert(), IsShuffled(), IsSingleItemNonRepeatPlaylist(), CGUIWindowMusicPlayList::MoveCurrentPlayListItem(), CGUIWindowVideoPlaylist::MoveCurrentPlayListItem(), CPartyModeManager::MovePlaying(), CApplication::OnMessage(), OnMessage(), CGUIMediaWindow::OnPlayAndQueueMedia(), Play(), Play(), PlayItemIdx(), XBMCAddon::xbmc::PlayList::PlayList(), PlayNext(), PlayPrevious(), CPartyModeManager::ReapSongs(), Remove(), ReShuffle(), SetCurrentItemIdx(), SetShuffle(), Swap(), and CGUIMediaWindow::UpdateFileList().
GetPlaylist() [2/2]
const CPlayList & KODI::PLAYLIST::CPlayListPlayer::GetPlaylist (Id playlistId) const
References m_PlaylistEmpty, m_PlaylistMusic, m_PlaylistVideo, KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
GetRepeat()
RepeatState KODI::PLAYLIST::CPlayListPlayer::GetRepeat (Id playlistId) const
References m_repeatState, and KODI::PLAYLIST::NONE.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::GetPlaylistLabel(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), PlayerControl(), JSONRPC::CPlayerOperations::SetRepeat(), CGUIWindowMusicPlayList::UpdateButtons(), and CGUIWindowVideoPlaylist::UpdateButtons().
HasPlayedFirstFile()
bool KODI::PLAYLIST::CPlayListPlayer::HasPlayedFirstFile () const
Return whether or not something has been played yet from the current playlist.
Returns
true if something has been played, false otherwise.
References m_bPlayedFirstFile.
Referenced by CApplication::PlayFile().
Insert() [1/3]
void KODI::PLAYLIST::CPlayListPlayer::Insert (Id playlistId, const CFileItemList & items, int iIndex)
References CServiceBroker::GetGUI(), GetPlaylist(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLIST_CHANGED, KODI::PLAYLIST::CPlayList::Insert(), KODI::PLAYLIST::CPlayList::IsShuffled(), m_iCurrentPlayList, m_iCurrentSong, ReShuffle(), CGUIWindowManager::SendMessage(), KODI::PLAYLIST::CPlayList::size(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Insert() [2/3]
void KODI::PLAYLIST::CPlayListPlayer::Insert (Id playlistId, const CFileItemPtr & pItem, int iIndex)
References GetPlaylist(), KODI::PLAYLIST::CPlayList::Insert(), KODI::PLAYLIST::CPlayList::IsShuffled(), m_iCurrentPlayList, m_iCurrentSong, ReShuffle(), KODI::PLAYLIST::CPlayList::size(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Insert() [3/3]
void KODI::PLAYLIST::CPlayListPlayer::Insert (Id playlistId, const CPlayList & playlist, int iIndex)
References GetPlaylist(), KODI::PLAYLIST::CPlayList::Insert(), KODI::PLAYLIST::CPlayList::IsShuffled(), m_iCurrentPlayList, m_iCurrentSong, playlist, ReShuffle(), KODI::PLAYLIST::CPlayList::size(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
IsShuffled()
bool KODI::PLAYLIST::CPlayListPlayer::IsShuffled (Id playlistId) const
Return whether a playlist is shuffled. If partymode is enabled, this always returns false.
Parameters
playlist the playlist to query for shuffle state, PLAYLIST::TYPE_MUSIC or PLAYLIST::TYPE_VIDEO.
Returns
true if the given playlist is shuffled and party mode isn't enabled, false otherwise.
See also
SetShuffle
References g_partyModeManager, GetPlaylist(), CPartyModeManager::IsEnabled(), KODI::PLAYLIST::CPlayList::IsShuffled(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::GetPlaylistLabel(), JSONRPC::CPlayerOperations::GetPropertyValue(), PlayerControl(), and SetShuffle().
IsSingleItemNonRepeatPlaylist()
bool KODI::PLAYLIST::CPlayListPlayer::IsSingleItemNonRepeatPlaylist () const
References GetPlaylist(), m_iCurrentPlayList, playlist, Repeated(), and RepeatedOne().
Referenced by OnAction().
OnAction()
bool KODI::PLAYLIST::CPlayListPlayer::OnAction (const CAction & action)
References ACTION_NEXT_ITEM, ACTION_PREV_ITEM, IsSingleItemNonRepeatPlaylist(), PlayNext(), and PlayPrevious().
OnApplicationMessage()
void KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage (KODI::MESSAGING::ThreadMessage * msg) override virtual
This gets called whenever a message matching the registered message mask is processed.
There are no ordering guarantees here so implementations should never rely on a certain ordering of messages.
Cleaning up any pointers stored in the message payload is not specified and is decided by the implementer of the message. In general prefer to delete any data in this method to keep the callsites cleaner and simpler but if data is to be passed back it's perfectly valid to handle it any way that fits the situation as long as it's documented along with the message.
To return a simple value the result parameter of
See also
ThreadMessage can be used as it will be used as the return value for
CApplicationMessenger::SendMsg. It is up to the implementer to decide if this is to be used and it should be documented along with any new message implemented.
Implements KODI::MESSAGING::IMessageTarget.
References CFileItemList::Add(), CVariant::asBoolean(), CVariant::asInteger(), ClearPlaylist(), KODI::MESSAGING::ThreadMessage::dwMessage, g_application, g_passwordManager, CFileItemList::Get(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), CGUIListItem::GetProperty(), XFILE::CPluginDirectory::GetResolvedPluginResult(), CGUIComponent::GetWindowManager(), URIUtils::HasPluginPath(), CGUIListItem::HasProperty(), KODI::MUSIC::IsAudio(), CVariant::isBoolean(), CVariant::isInteger(), CGUIPassword::IsMusicUnlocked(), KODI::PLAYLIST::IsPlayList(), KODI::VIDEO::IsVideo(), CGUIPassword::IsVideoUnlocked(), LOGERROR, KODI::MESSAGING::ThreadMessage::lpVoid, KODI::MESSAGING::ThreadMessage::param1, KODI::MESSAGING::ThreadMessage::param2, KODI::MESSAGING::ThreadMessage::param3, playlist, CGUIWindowManager::PreviousWindow(), Reset(), CApplicationPowerHandling::ResetScreenSaver(), CFileItemList::Size(), KODI::MESSAGING::ThreadMessage::strParam, TMSG_MEDIA_PAUSE, TMSG_MEDIA_PAUSE_IF_PLAYING, TMSG_MEDIA_PLAY, TMSG_MEDIA_RESTART, TMSG_MEDIA_SEEK_TIME, TMSG_MEDIA_STOP, TMSG_MEDIA_UNPAUSE, TMSG_PLAYLISTPLAYER_ADD, TMSG_PLAYLISTPLAYER_CLEAR, TMSG_PLAYLISTPLAYER_GET_ITEMS, TMSG_PLAYLISTPLAYER_INSERT, TMSG_PLAYLISTPLAYER_NEXT, TMSG_PLAYLISTPLAYER_PLAY, TMSG_PLAYLISTPLAYER_PLAY_ITEM_ID, TMSG_PLAYLISTPLAYER_PREV, TMSG_PLAYLISTPLAYER_REMOVE, TMSG_PLAYLISTPLAYER_REPEAT, TMSG_PLAYLISTPLAYER_SHUFFLE, TMSG_PLAYLISTPLAYER_SWAP, KODI::PLAYLIST::TYPE_MUSIC, KODI::PLAYLIST::TYPE_NONE, KODI::PLAYLIST::TYPE_PICTURE, KODI::PLAYLIST::TYPE_VIDEO, WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, WINDOW_SLIDESHOW, and WINDOW_VISUALISATION.
OnMessage()
bool KODI::PLAYLIST::CPlayListPlayer::OnMessage (CGUIMessage & message) override virtual
Implements IMsgTargetCallback.
References CServiceBroker::GetGUI(), CGUIMessage::GetItem(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), GetPlaylist(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_PLAYBACK_STARTED, GUI_MSG_PLAYBACK_STOPPED, GUI_MSG_PLAYLISTPLAYER_STOPPED, GUI_MSG_UPDATE_ITEM, m_bPlaybackStarted, m_iCurrentPlayList, m_iCurrentSong, playlist, Reset(), KODI::PLAYLIST::TYPE_MUSIC, KODI::PLAYLIST::TYPE_NONE, and KODI::PLAYLIST::TYPE_VIDEO.
Play() [1/3]
bool KODI::PLAYLIST::CPlayListPlayer::Play ()
References GetPlaylist(), m_iCurrentPlayList, Play(), playlist, and KODI::PLAYLIST::TYPE_NONE.
Referenced by CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIMediaWindow::OnPlayAndQueueMedia(), CGUIWindowVideoBase::OnPlayMedia(), CGUIWindowMusicBase::OnPlayMedia(), CGUIWindowMusicPlayList::OnPlayMedia(), CGUIWindowFileManager::OnStart(), Play(), Play(), CPartyModeManager::Play(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::PlayItem(), PlayItemIdx(), PlayNext(), PlayOffset(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), PlayPrevious(), and CApplication::ProcessAndStartPlaylist().
Play() [2/3]
bool KODI::PLAYLIST::CPlayListPlayer::Play (const CFileItemPtr & pItem, const std::string & player, bool forceSelection = false)
Creates a new playlist for an item and starts playing it.
Parameters
pItem The item to play.
player The player name.
forceSelection for Blurays, force simple menu to change playlist (default to false)
Returns
True if has success, otherwise false.
References Add(), ClearPlaylist(), KODI::MUSIC::IsAudio(), KODI::VIDEO::IsVideo(), LOGWARNING, Play(), Reset(), SetCurrentPlaylist(), KODI::PLAYLIST::TYPE_MUSIC, KODI::PLAYLIST::TYPE_NONE, and KODI::PLAYLIST::TYPE_VIDEO.
Play() [3/3]
bool KODI::PLAYLIST::CPlayListPlayer::Play (int index, const std::string & player, bool replace = false, bool playPreviousOnFail = false, bool forceSelection = false)
Start playing a particular entry in the current playlist.
Parameters
index the index of the item to play. This value is modified to ensure it lies within the current playlist.
replace whether this item should replace the currently playing item. See CApplication::PlayFile (defaults to false).
playPreviousOnFail whether to go back to the previous item if playback fails (default to false)
forceSelection for Blurays, force simple menu to change playlist (default to false)
Todo:
move the above failure logic and the below success logic to callbacks instead so we don't rely on the return value of PlayFile()
References KODI::PLAYLIST::CPlayList::Clear(), g_application, CServiceBroker::GetGUI(), GetPlaylist(), CServiceBroker::GetSettingsComponent(), XFILE::CVideoDatabaseFile::GetVideoTag(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLISTPLAYER_STOPPED, KODI::VIDEO::IsVideoDb(), CLog::Log(), LOGDEBUG, LOGERROR, m_bPlaybackStarted, m_bPlayedFirstFile, m_failedSongsStart, m_iCurrentPlayList, m_iCurrentSong, m_iFailedSongs, playlist, PlayNext(), PlayPrevious(), Reset(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), STARTOFFSET_RESUME, and KODI::PLAYLIST::TYPE_NONE.
PlayItemIdx()
bool KODI::PLAYLIST::CPlayListPlayer::PlayItemIdx (int itemIdx)
References GetPlaylist(), m_iCurrentPlayList, Play(), playlist, and KODI::PLAYLIST::TYPE_NONE.
PlayNext()
bool KODI::PLAYLIST::CPlayListPlayer::PlayNext (int offset = 1, bool autoPlay = false)
Play the next (or another) entry in the current playlist.
Parameters
offset The offset from the current entry (defaults to 1, i.e. the next entry).
autoPlay Whether we should start playing if not already (defaults to false).
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CApplicationPlayer::GetName(), GetNextItemIdx(), GetPlaylist(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLISTPLAYER_STOPPED, CGUIDialogKaiToast::Info, m_iCurrentPlayList, m_iCurrentSong, Play(), playlist, CGUIDialogKaiToast::QueueNotification(), Reset(), and KODI::PLAYLIST::TYPE_NONE.
Referenced by OnAction(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), Play(), and PlayOffset().
PlayPrevious()
bool KODI::PLAYLIST::CPlayListPlayer::PlayPrevious ()
Play the previous entry in the current playlist.
See also
PlayNext
References g_localizeStrings, CLocalizeStrings::Get(), GetPlaylist(), CGUIDialogKaiToast::Info, m_iCurrentPlayList, m_iCurrentSong, Play(), playlist, CGUIDialogKaiToast::QueueNotification(), Repeated(), RepeatedOne(), and KODI::PLAYLIST::TYPE_NONE.
Referenced by OnAction(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), and Play().
Remove()
void KODI::PLAYLIST::CPlayListPlayer::Remove (Id playlistId, int iPosition)
References CServiceBroker::GetGUI(), GetPlaylist(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLIST_CHANGED, m_iCurrentPlayList, m_iCurrentSong, KODI::PLAYLIST::CPlayList::Remove(), CGUIWindowManager::SendMessage(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Referenced by CGUIWindowMusicPlayList::RemovePlayListItem(), and CGUIWindowVideoPlaylist::RemovePlayListItem().
RemoveDVDItems()
int KODI::PLAYLIST::CPlayListPlayer::RemoveDVDItems ()
Removes any item from all playlists located on a removable share.
Returns
Number of items removed from PLAYLIST::TYPE_MUSIC and PLAYLIST::TYPE_VIDEO
References m_PlaylistMusic, m_PlaylistVideo, and KODI::PLAYLIST::CPlayList::RemoveDVDItems().
Referenced by CApplication::OnMessage().
Repeated()
bool KODI::PLAYLIST::CPlayListPlayer::Repeated (Id playlistId) const protected
Returns true if the given is set to repeat all.
Parameters
playlist Playlist to be query
Returns
true if the given playlist is set to repeat all, false otherwise.
References KODI::PLAYLIST::ALL, and m_repeatState.
Referenced by GetNextItemIdx(), GetNextItemIdx(), IsSingleItemNonRepeatPlaylist(), and PlayPrevious().
RepeatedOne()
bool KODI::PLAYLIST::CPlayListPlayer::RepeatedOne (Id playlistId) const protected
Returns true if the given is set to repeat one.
Parameters
playlist Playlist to be query
Returns
true if the given playlist is set to repeat one, false otherwise.
References m_repeatState, and KODI::PLAYLIST::ONE.
Referenced by GetNextItemIdx(), GetNextItemIdx(), IsSingleItemNonRepeatPlaylist(), and PlayPrevious().
Reset()
void KODI::PLAYLIST::CPlayListPlayer::Reset ()
Resets the current song and unplayable counts. Does not alter the active playlist.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLIST_CHANGED, m_bPlaybackStarted, m_bPlayedFirstFile, m_iCurrentSong, and CGUIWindowManager::SendMessage().
Referenced by CGUIWindowMusicPlayList::ClearPlayList(), CGUIWindowVideoPlaylist::ClearPlayList(), GetNextItemIdx(), CGUIWindowMusicPlayList::OnMessage(), OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIMediaWindow::OnPlayAndQueueMedia(), CGUIWindowVideoBase::OnPlayMedia(), CGUIMediaWindow::OnPlayMedia(), CGUIWindowMusicPlayList::OnPlayMedia(), Play(), Play(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::PlayItem(), PlayNext(), PlayOffset(), CApplication::ProcessAndStartPlaylist(), and CGUIMediaWindow::UpdateFileList().
ReShuffle()
void KODI::PLAYLIST::CPlayListPlayer::ReShuffle (Id playlistId, int iPosition) protected
References CServiceBroker::GetAppComponents(), GetPlaylist(), m_iCurrentPlayList, m_iCurrentSong, KODI::PLAYLIST::CPlayList::Shuffle(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Referenced by Add(), Add(), Add(), Insert(), Insert(), and Insert().
SetCurrentItemIdx()
void KODI::PLAYLIST::CPlayListPlayer::SetCurrentItemIdx (int index)
Change the current item in the active playlist.
Parameters
index item index in playlist. Set only if the index is within the range of the current playlist.
See also
GetCurrentItemIdx
References GetPlaylist(), m_iCurrentPlayList, and m_iCurrentSong.
Referenced by CGUIWindowMusicPlayList::MoveCurrentPlayListItem(), CGUIWindowVideoPlaylist::MoveCurrentPlayListItem(), CPartyModeManager::MovePlaying(), CApplication::OnMessage(), XBMCAddon::xbmc::Player::playPlaylist(), XBMCAddon::xbmc::Player::playselected(), CPartyModeManager::ReapSongs(), and CGUIMediaWindow::UpdateFileList().
SetCurrentPlaylist()
void KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist (Id playlistId)
Set the active playlist.
Parameters
id Id of playlist
See also
GetCurrentPlaylist
References CPartyModeManager::Disable(), g_partyModeManager, CPartyModeManager::IsEnabled(), m_bPlayedFirstFile, and m_iCurrentPlayList.
Referenced by CGUIWindowMusicPlayList::ClearPlayList(), CGUIWindowVideoPlaylist::ClearPlayList(), CPartyModeManager::Enable(), CProfileManager::FinalizeLoadProfile(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIMediaWindow::OnPlayAndQueueMedia(), CGUIWindowVideoBase::OnPlayMedia(), CGUIMediaWindow::OnPlayMedia(), CGUIWindowMusicPlayList::OnPlayMedia(), Play(), XBMCAddon::xbmc::Player::playCurrent(), CApplication::PlayFile(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::PlayItem(), PlayOffset(), XBMCAddon::xbmc::Player::playPlaylist(), XBMCAddon::xbmc::Player::playselected(), CApplication::ProcessAndStartPlaylist(), and CApplication::Run().
SetRepeat()
void KODI::PLAYLIST::CPlayListPlayer::SetRepeat (Id playlistId, RepeatState state, bool notify = false)
Set repeat state of a playlist. If called while in Party Mode, repeat is disabled.
Parameters
playlist the playlist to set repeat state for, PLAYLIST::TYPE_MUSIC or PLAYLIST::TYPE_VIDEO.
state set to RepeatState::NONE, RepeatState::ONE or RepeatState::ALL
notify notify the user with a Toast notification
See also
GetRepeat
References KODI::PLAYLIST::ALL, AnnouncePropertyChanged(), data(), g_localizeStrings, g_partyModeManager, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLIST_CHANGED, CGUIDialogKaiToast::Info, CPartyModeManager::IsEnabled(), m_repeatState, KODI::PLAYLIST::NONE, KODI::PLAYLIST::ONE, CGUIDialogKaiToast::QueueNotification(), CGUIWindowManager::SendMessage(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Referenced by CPartyModeManager::Enable(), CMediaSettings::Load(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), JSONRPC::CPlayerOperations::Open(), and PlayerControl().
SetShuffle()
void KODI::PLAYLIST::CPlayListPlayer::SetShuffle (Id playlistId, bool shuffle, bool notify = false)
Set shuffle state of a playlist. If the shuffle state changes, the playlist is shuffled or unshuffled. Has no effect if Party Mode is enabled.
Parameters
playlist the playlist to (un)shuffle, PLAYLIST::TYPE_MUSIC or PLAYLIST::TYPE_VIDEO.
shuffle set true to shuffle, false to unshuffle.
notify notify the user with a Toast notification (defaults to false)
See also
IsShuffled
References AnnouncePropertyChanged(), g_localizeStrings, g_partyModeManager, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), GetPlaylist(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLIST_CHANGED, CGUIDialogKaiToast::Info, CPartyModeManager::IsEnabled(), IsShuffled(), m_iCurrentSong, playlist, CGUIDialogKaiToast::QueueNotification(), CGUIWindowManager::SendMessage(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Referenced by CPartyModeManager::Enable(), CMediaSettings::Load(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIWindowVideoBase::OnPlayAndQueueMedia(), JSONRPC::CPlayerOperations::Open(), and PlayerControl().
Swap()
void KODI::PLAYLIST::CPlayListPlayer::Swap (Id playlistId, int indexItem1, int indexItem2)
References CServiceBroker::GetGUI(), GetPlaylist(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLIST_CHANGED, m_iCurrentPlayList, m_iCurrentSong, CGUIWindowManager::SendMessage(), KODI::PLAYLIST::CPlayList::Swap(), KODI::PLAYLIST::TYPE_MUSIC, and KODI::PLAYLIST::TYPE_VIDEO.
Member Data Documentation
m_bPlaybackStarted
bool KODI::PLAYLIST::CPlayListPlayer::m_bPlaybackStarted protected
Referenced by CPlayListPlayer(), OnMessage(), Play(), and Reset().
m_bPlayedFirstFile
bool KODI::PLAYLIST::CPlayListPlayer::m_bPlayedFirstFile protected
Referenced by CPlayListPlayer(), HasPlayedFirstFile(), Play(), Reset(), and SetCurrentPlaylist().
m_failedSongsStart
std::chrono::time_point<std::chrono::steady_clock> KODI::PLAYLIST::CPlayListPlayer::m_failedSongsStart protected
Referenced by CPlayListPlayer(), and Play().
m_iCurrentPlayList
Id KODI::PLAYLIST::CPlayListPlayer::m_iCurrentPlayList {Id::TYPE_NONE} protected
Referenced by GetCurrentPlaylist(), GetNextItemIdx(), GetNextItemIdx(), Insert(), Insert(), Insert(), IsSingleItemNonRepeatPlaylist(), OnMessage(), Play(), Play(), PlayItemIdx(), PlayNext(), PlayPrevious(), Remove(), ReShuffle(), SetCurrentItemIdx(), SetCurrentPlaylist(), and Swap().
m_iCurrentSong
int KODI::PLAYLIST::CPlayListPlayer::m_iCurrentSong protected
Referenced by CPlayListPlayer(), GetCurrentItemIdx(), GetNextItemIdx(), GetNextItemIdx(), Insert(), Insert(), Insert(), OnMessage(), Play(), PlayNext(), PlayPrevious(), Remove(), Reset(), ReShuffle(), SetCurrentItemIdx(), SetShuffle(), and Swap().
m_iFailedSongs
int KODI::PLAYLIST::CPlayListPlayer::m_iFailedSongs protected
Referenced by CPlayListPlayer(), and Play().
m_PlaylistEmpty
CPlayList* KODI::PLAYLIST::CPlayListPlayer::m_PlaylistEmpty protected
Referenced by Clear(), CPlayListPlayer(), GetPlaylist(), GetPlaylist(), and ~CPlayListPlayer().
m_PlaylistMusic
CPlayList* KODI::PLAYLIST::CPlayListPlayer::m_PlaylistMusic protected
Referenced by Clear(), CPlayListPlayer(), GetPlaylist(), GetPlaylist(), RemoveDVDItems(), and ~CPlayListPlayer().
m_PlaylistVideo
CPlayList* KODI::PLAYLIST::CPlayListPlayer::m_PlaylistVideo protected
Referenced by Clear(), CPlayListPlayer(), GetPlaylist(), GetPlaylist(), RemoveDVDItems(), and ~CPlayListPlayer().
m_repeatState
std::map<Id, RepeatState> KODI::PLAYLIST::CPlayListPlayer::m_repeatState protected
Initial value:
{
      {Id::TYPE_MUSIC, RepeatState::NONE},
      {Id::TYPE_VIDEO, RepeatState::NONE},
      {Id::TYPE_PICTURE, RepeatState::NONE},
  }
Referenced by GetRepeat(), Repeated(), RepeatedOne(), and SetRepeat().
The documentation for this class was generated from the following files:
PlayListPlayer.h
PlayListPlayer.cpp