Kodi Documentation: CAESpinSection Class Reference
CAESpinSection Class Reference
lockless consistency guaranteeer
#include <AEUtil.h>
Public Member Functions
void enter ()
void leave ()
Protected Attributes
std::atomic_uint32_t m_enter = 0
std::atomic_uint32_t m_leave = 0
Friends
class CAESpinLock
Detailed Description
lockless consistency guaranteeer
Requires write to be a higher priority thread
use in writer: m_locker.enter(); update_stuff(); m_locker.leave();
use in reader: CAESpinLock lock(m_locker); do { get_stuff(); } while(lock.retry());
Member Function Documentation
enter()
void CAESpinSection::enter () inline
References m_enter.
Referenced by CAESinkDARWINOSX::renderCallback(), and CAAudioUnitSink::renderCallback().
leave()
void CAESpinSection::leave () inline
References m_enter, and m_leave.
Referenced by CAESinkDARWINOSX::renderCallback(), and CAAudioUnitSink::renderCallback().
Friends And Related Symbol Documentation
CAESpinLock
friend class CAESpinLock friend
Member Data Documentation
m_enter
std::atomic_uint32_t CAESpinSection::m_enter = 0 protected
Referenced by enter(), leave(), and CAESpinLock::retry().
m_leave
std::atomic_uint32_t CAESpinSection::m_leave = 0 protected
Referenced by leave(), and CAESpinLock::retry().
The documentation for this class was generated from the following file:
AEUtil.h