Kodi Documentation: TestNetwork Class Reference
TestNetwork Class Reference
Public Member Functions
TestNetwork ()=default
~TestNetwork ()=default
bool PingHost (const std::string &ip) const
unsigned int GetPort () const
unsigned int GetTimeout () const
Private Attributes
unsigned int m_port {0}
unsigned int m_timeoutMs {100}
Constructor & Destructor Documentation
TestNetwork()
TestNetwork::TestNetwork () default
~TestNetwork()
TestNetwork::~TestNetwork () default
Member Function Documentation
GetPort()
unsigned int TestNetwork::GetPort () const inline
References m_port.
Referenced by PingHost().
GetTimeout()
unsigned int TestNetwork::GetTimeout () const inline
References m_timeoutMs.
Referenced by PingHost().
PingHost()
bool TestNetwork::PingHost (const std::string & ip) const inline
References CServiceBroker::GetNetwork(), GetPort(), and GetTimeout().
Member Data Documentation
m_port
unsigned int TestNetwork::m_port {0} private
Referenced by GetPort().
m_timeoutMs
unsigned int TestNetwork::m_timeoutMs {100} private
Referenced by GetTimeout().
The documentation for this class was generated from the following file:
TestNetwork.cpp