Kodi Documentation: CGUIControlSliderSetting Class Reference
CGUIControlSliderSetting Class Reference
#include <GUIControlSettings.h>
Public Member Functions
CGUIControlSliderSetting (CGUISettingsSliderControl *pSlider, int id, std::shared_ptr< CSetting > pSetting, ILocalizer *localizer)
~CGUIControlSliderSetting () override
CGUIControl * GetControl () override
bool OnClick () override
void Clear () override
Clears the attached control.
Public Member Functions inherited from CGUIControlBaseSetting
CGUIControlBaseSetting (int id, std::shared_ptr< CSetting > pSetting, ILocalizer *localizer)
~CGUIControlBaseSetting () override=default
int GetID () const
std::shared_ptr< CSetting > GetSetting ()
void SetDelayed ()
Specifies that this setting should update after a delay Useful for settings that have options to navigate through and may take a while, or require additional input to update once the final setting is chosen. Settings default to updating instantly.
bool IsDelayed () const
Returns whether this setting should have delayed update.
bool IsEnabled () const
Returns whether this setting is enabled or disabled This state is independent of the real enabled state of a setting control but represents the enabled state of the setting itself based on specific conditions.
bool IsValid () const
Returns whether the setting's value is valid or not.
void SetValid (bool valid)
void UpdateFromControl ()
void UpdateFromSetting (bool updateDisplayOnly=false)
Static Public Member Functions
static std::string GetText (const std::shared_ptr< CSetting > &setting, const CVariant &value, const CVariant &minimum, const CVariant &step, const CVariant &maximum, ILocalizer *localizer)
Protected Member Functions
void Update (bool fromControl, bool updateDisplayOnly) override
Protected Member Functions inherited from CGUIControlBaseSetting
std::string Localize (std::uint32_t code) const override
Protected Member Functions inherited from ILocalizer
ILocalizer ()=default
virtual ~ILocalizer ()=default
Static Private Member Functions
static bool FormatText (const std::string &formatString, const CVariant &value, const std::string &settingId, std::string &formattedText)
Private Attributes
CGUISettingsSliderControl * m_pSlider
Additional Inherited Members
Protected Attributes inherited from CGUIControlBaseSetting
int m_id
std::shared_ptr< CSetting > m_pSetting
ILocalizer * m_localizer
bool m_delayed = false
bool m_valid = true
Constructor & Destructor Documentation
CGUIControlSliderSetting()
CGUIControlSliderSetting::CGUIControlSliderSetting (CGUISettingsSliderControl * pSlider, int id, std::shared_ptr< CSetting > pSetting, ILocalizer * localizer)
References Integer, CGUIControlBaseSetting::m_pSetting, m_pSlider, Number, CGUISliderControl::SetFloatInterval(), CGUISliderControl::SetFloatRange(), CGUIControl::SetID(), CGUISliderControl::SetIntInterval(), CGUISliderControl::SetRange(), CGUISliderControl::SetType(), SLIDER_CONTROL_TYPE_FLOAT, SLIDER_CONTROL_TYPE_INT, and SLIDER_CONTROL_TYPE_PERCENTAGE.
~CGUIControlSliderSetting()
CGUIControlSliderSetting::~CGUIControlSliderSetting () override default
Member Function Documentation
Clear()
void CGUIControlSliderSetting::Clear () inline override virtual
Clears the attached control.
Implements CGUIControlBaseSetting.
References m_pSlider.
FormatText()
bool CGUIControlSliderSetting::FormatText (const std::string & formatString, const CVariant & value, const std::string & settingId, std::string & formattedText) static private
References err(), CLog::Log(), LOGERROR, and value.
Referenced by GetText().
GetControl()
CGUIControl * CGUIControlSliderSetting::GetControl () inline override virtual
Reimplemented from CGUIControlBaseSetting.
References m_pSlider.
GetText()
std::string CGUIControlSliderSetting::GetText (const std::shared_ptr< CSetting > & setting, const CVariant & value, const CVariant & minimum, const CVariant & step, const CVariant & maximum, ILocalizer * localizer) static
References FormatText(), CGUIControlBaseSetting::Localize(), and value.
Referenced by CGUIControlButtonSetting::OnSliderChange(), CGUIControlButtonSetting::Update(), and Update().
OnClick()
bool CGUIControlSliderSetting::OnClick () override virtual
Reimplemented from CGUIControlBaseSetting.
References CGUISliderControl::GetFloatValue(), CGUISliderControl::GetIntValue(), Integer, CGUIControlBaseSetting::IsValid(), CGUIControlBaseSetting::m_pSetting, m_pSlider, Number, and CGUIControlBaseSetting::SetValid().
Update()
void CGUIControlSliderSetting::Update (bool fromControl, bool updateDisplayOnly) override protected virtual
Reimplemented from CGUIControlBaseSetting.
References CGUISliderControl::GetFloatValue(), CGUISliderControl::GetIntValue(), GetText(), Integer, CGUIControlBaseSetting::m_localizer, CGUIControlBaseSetting::m_pSetting, m_pSlider, Number, CGUISliderControl::SetFloatValue(), CGUISliderControl::SetIntValue(), CGUISliderControl::SetTextValue(), CGUIControlBaseSetting::Update(), and value.
Member Data Documentation
m_pSlider
CGUISettingsSliderControl* CGUIControlSliderSetting::m_pSlider private
Referenced by CGUIControlSliderSetting(), Clear(), GetControl(), OnClick(), and Update().
The documentation for this class was generated from the following files:
GUIControlSettings.h
GUIControlSettings.cpp