Kodi Documentation: PVR::CPVRGUIActionsChannels Class Reference
PVR::CPVRGUIActionsChannels Class Reference
#include <PVRGUIActionsChannels.h>
Public Member Functions
CPVRGUIActionsChannels ()
~CPVRGUIActionsChannels () override
CEventStream< PVRChannelNumberInputChangedEvent > & Events ()
Get the events available for CEventStream.
void RegisterChannelNumberInputHandler (CPVRChannelNumberInputHandler *handler)
Register a handler for channel number input.
void DeregisterChannelNumberInputHandler (CPVRChannelNumberInputHandler *handler)
Deregister a handler for channel number input.
void Notify (const PVRChannelNumberInputChangedEvent &event)
CEventStream callback for channel number input changes.
bool HideChannel (const CFileItem &item) const
Hide a channel, always showing a confirmation dialog.
bool StartChannelScan ()
Open a selection dialog and start a channel scan on the selected client.
bool StartChannelScan (int clientId)
Start a channel scan on the specified client or open a dialog to select a client.
bool IsRunningChannelScan () const
std::shared_ptr< CPVRChannelGroupMember > GetChannelGroupMember (const std::shared_ptr< const CPVRChannel > &channel) const
Get a channel group member for the given channel, either from the currently active group or if not found there, from the 'all channels' group.
std::shared_ptr< CPVRChannelGroupMember > GetChannelGroupMember (const CFileItem &item) const
Get a channel group member for the given item, either from the currently active group or if not found there, from the 'all channels' group.
CPVRChannelNumberInputHandler & GetChannelNumberInputHandler ()
Get the currently active channel number input handler.
CPVRGUIChannelNavigator & GetChannelNavigator ()
Get the channel navigator.
void OnPlaybackStarted (const CFileItem &item)
Inform GUI actions that playback of an item just started.
void OnPlaybackStopped (const CFileItem &item)
Inform GUI actions that playback of an item was stopped due to user interaction.
std::string GetSelectedChannelPath (bool bRadio) const
Get the currently selected channel item path; used across several windows/dialogs to share item selection.
void SetSelectedChannelPath (bool bRadio, const std::string &path)
Set the currently selected channel item path; used across several windows/dialogs to share item selection.
Public Member Functions inherited from PVR::IPVRComponent
virtual ~IPVRComponent ()=default
Private Member Functions
CPVRGUIActionsChannels (const CPVRGUIActionsChannels &)=delete
CPVRGUIActionsChannels const & operator= (CPVRGUIActionsChannels const &)=delete
Private Attributes
CPVRChannelSwitchingInputHandler m_channelNumberInputHandler
bool m_bChannelScanRunning {false}
CPVRGUIChannelNavigator m_channelNavigator
CEventSource< PVRChannelNumberInputChangedEvent > m_events
CCriticalSection m_critSection
CPVRSettings m_settings
std::string m_selectedChannelPathTV
std::string m_selectedChannelPathRadio
Constructor & Destructor Documentation
CPVRGUIActionsChannels() [1/2]
CPVRGUIActionsChannels::CPVRGUIActionsChannels ()
References CSettings::SETTING_PVRMANAGER_PRESELECTPLAYINGCHANNEL.
~CPVRGUIActionsChannels()
CPVRGUIActionsChannels::~CPVRGUIActionsChannels () override
References DeregisterChannelNumberInputHandler(), and m_channelNumberInputHandler.
CPVRGUIActionsChannels() [2/2]
PVR::CPVRGUIActionsChannels::CPVRGUIActionsChannels (const CPVRGUIActionsChannels &) private delete
Member Function Documentation
DeregisterChannelNumberInputHandler()
void CPVRGUIActionsChannels::DeregisterChannelNumberInputHandler (CPVRChannelNumberInputHandler * handler)
Deregister a handler for channel number input.
Parameters
handler The handler to deregister.
References PVR::CPVRChannelNumberInputHandler::Events().
Referenced by ~CPVRGUIActionsChannels().
Events()
CEventStream< PVRChannelNumberInputChangedEvent > & PVR::CPVRGUIActionsChannels::Events () inline
Get the events available for CEventStream.
Returns
The events.
References m_events.
Referenced by PVR::CPVRGUIInfo::Process().
GetChannelGroupMember() [1/2]
std::shared_ptr< CPVRChannelGroupMember > CPVRGUIActionsChannels::GetChannelGroupMember (const CFileItem & item) const
Get a channel group member for the given item, either from the currently active group or if not found there, from the 'all channels' group.
Parameters
item the item containing a channel, channel group, recording, timer or epg tag.
Returns
the group member or nullptr if not found.
References GetChannelGroupMember(), and CFileItem::GetPVRChannelGroupMemberInfoTag().
GetChannelGroupMember() [2/2]
std::shared_ptr< CPVRChannelGroupMember > CPVRGUIActionsChannels::GetChannelGroupMember (const std::shared_ptr< const CPVRChannel > & channel) const
Get a channel group member for the given channel, either from the currently active group or if not found there, from the 'all channels' group.
Parameters
channel the channel.
Returns
the group member or nullptr if not found.
References PVR::CPVRManager::ChannelGroups(), CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), PVR::CPVRManager::PlaybackState(), WINDOW_RADIO_RECORDINGS, WINDOW_RADIO_SEARCH, WINDOW_RADIO_TIMER_RULES, WINDOW_RADIO_TIMERS, WINDOW_TV_RECORDINGS, WINDOW_TV_SEARCH, WINDOW_TV_TIMER_RULES, and WINDOW_TV_TIMERS.
Referenced by GetChannelGroupMember(), GetSelectedChannelPath(), and OnPlaybackStarted().
GetChannelNavigator()
CPVRGUIChannelNavigator & CPVRGUIActionsChannels::GetChannelNavigator ()
Get the channel navigator.
Returns
the navigator.
References m_channelNavigator.
Referenced by PVR::CPVRGUIInfo::Stop().
GetChannelNumberInputHandler()
CPVRChannelNumberInputHandler & CPVRGUIActionsChannels::GetChannelNumberInputHandler ()
Get the currently active channel number input handler.
Returns
the handler.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and m_channelNumberInputHandler.
GetSelectedChannelPath()
std::string CPVRGUIActionsChannels::GetSelectedChannelPath (bool bRadio) const
Get the currently selected channel item path; used across several windows/dialogs to share item selection.
Parameters
bRadio True to query the selected path for PVR radio, false for Live TV.
Returns
the path.
References PVR::CPVRManager::ChannelGroups(), PVR::CPVRSettings::GetBoolValue(), GetChannelGroupMember(), CServiceBroker::GetPVRManager(), m_critSection, m_selectedChannelPathRadio, m_selectedChannelPathTV, m_settings, PVR::CPVRManager::PlaybackState(), and CSettings::SETTING_PVRMANAGER_PRESELECTPLAYINGCHANNEL.
Referenced by PVR::CGUIWindowPVRGuideBase::InitEpgGridControl(), and PVR::CGUIDialogPVRChannelsOSD::Update().
HideChannel()
bool CPVRGUIActionsChannels::HideChannel (const CFileItem & item) const
Hide a channel, always showing a confirmation dialog.
Parameters
item containing a channel or an epg tag.
Returns
true on success, false otherwise.
References PVR::CPVRManager::ChannelGroups(), PVR::CGUIWindowPVRBase::DoRefresh(), CServiceBroker::GetGUI(), CFileItem::GetPVRChannelGroupMemberInfoTag(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), LOGERROR, and CGUIDialogYesNo::ShowAndGetInput().
IsRunningChannelScan()
bool PVR::CPVRGUIActionsChannels::IsRunningChannelScan () const inline
Returns
True when a channel scan is currently running, false otherwise.
References m_bChannelScanRunning.
Referenced by StartChannelScan().
Notify()
void CPVRGUIActionsChannels::Notify (const PVRChannelNumberInputChangedEvent & event)
CEventStream callback for channel number input changes.
Parameters
event The event.
References m_events.
Referenced by RegisterChannelNumberInputHandler().
OnPlaybackStarted()
void CPVRGUIActionsChannels::OnPlaybackStarted (const CFileItem & item)
Inform GUI actions that playback of an item just started.
Parameters
item The item that started to play.
References GetChannelGroupMember(), m_channelNavigator, PVR::CPVRGUIChannelNavigator::SetPlayingChannel(), and SetSelectedChannelPath().
OnPlaybackStopped()
void CPVRGUIActionsChannels::OnPlaybackStopped (const CFileItem & item)
Inform GUI actions that playback of an item was stopped due to user interaction.
Parameters
item The item that stopped to play.
References PVR::CPVRGUIChannelNavigator::ClearPlayingChannel(), CFileItem::HasEPGInfoTag(), CFileItem::HasPVRChannelInfoTag(), and m_channelNavigator.
operator=()
CPVRGUIActionsChannels const & PVR::CPVRGUIActionsChannels::operator= (CPVRGUIActionsChannels const &) private delete
RegisterChannelNumberInputHandler()
void CPVRGUIActionsChannels::RegisterChannelNumberInputHandler (CPVRChannelNumberInputHandler * handler)
Register a handler for channel number input.
Parameters
handler The handler to register.
References PVR::CPVRChannelNumberInputHandler::Events(), and Notify().
SetSelectedChannelPath()
void CPVRGUIActionsChannels::SetSelectedChannelPath (bool bRadio, const std::string & path)
Set the currently selected channel item path; used across several windows/dialogs to share item selection.
Parameters
bRadio True to set the selected path for PVR radio, false for Live TV.
path The new path to set.
References m_critSection, m_selectedChannelPathRadio, and m_selectedChannelPathTV.
Referenced by OnPlaybackStarted().
StartChannelScan() [1/2]
bool CPVRGUIActionsChannels::StartChannelScan ()
Open a selection dialog and start a channel scan on the selected client.
Returns
true on success, false otherwise.
References PVR::PVR_CLIENT_INVALID_UID, and StartChannelScan().
Referenced by StartChannelScan().
StartChannelScan() [2/2]
bool CPVRGUIActionsChannels::StartChannelScan (int clientId)
Start a channel scan on the specified client or open a dialog to select a client.
Parameters
clientId the id of client to scan or PVR_INVALID_CLIENT_ID if a dialog will be opened
Returns
true on success, false otherwise.
References CGUIDialogSelect::Add(), PVR::CPVRManager::Clients(), end(), CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CGUIDialogSelect::GetSelectedItem(), CGUIComponent::GetWindowManager(), IsRunningChannelScan(), LOGDEBUG, LOGERROR, LOGPVR, m_bChannelScanRunning, CGUIDialog::Open(), PVR::PVR_CLIENT_INVALID_UID, PVR_ERROR_NO_ERROR, CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and WINDOW_DIALOG_SELECT.
Member Data Documentation
m_bChannelScanRunning
bool PVR::CPVRGUIActionsChannels::m_bChannelScanRunning {false} private
Referenced by IsRunningChannelScan(), and StartChannelScan().
m_channelNavigator
CPVRGUIChannelNavigator PVR::CPVRGUIActionsChannels::m_channelNavigator private
Referenced by GetChannelNavigator(), OnPlaybackStarted(), and OnPlaybackStopped().
m_channelNumberInputHandler
CPVRChannelSwitchingInputHandler PVR::CPVRGUIActionsChannels::m_channelNumberInputHandler private
Referenced by GetChannelNumberInputHandler(), and ~CPVRGUIActionsChannels().
m_critSection
CCriticalSection PVR::CPVRGUIActionsChannels::m_critSection mutable private
Referenced by GetSelectedChannelPath(), and SetSelectedChannelPath().
m_events
CEventSource<PVRChannelNumberInputChangedEvent> PVR::CPVRGUIActionsChannels::m_events private
Referenced by Events(), and Notify().
m_selectedChannelPathRadio
std::string PVR::CPVRGUIActionsChannels::m_selectedChannelPathRadio private
Referenced by GetSelectedChannelPath(), and SetSelectedChannelPath().
m_selectedChannelPathTV
std::string PVR::CPVRGUIActionsChannels::m_selectedChannelPathTV private
Referenced by GetSelectedChannelPath(), and SetSelectedChannelPath().
m_settings
CPVRSettings PVR::CPVRGUIActionsChannels::m_settings private
Referenced by GetSelectedChannelPath().
The documentation for this class was generated from the following files:
PVRGUIActionsChannels.h
PVRGUIActionsChannels.cpp