Kodi Documentation: CSettingDependency Class Reference
CSettingDependency Class Reference
#include <SettingDependency.h>
Public Member Functions
CSettingDependency (CSettingsManager *settingsManager=nullptr)
CSettingDependency (SettingDependencyType type, CSettingsManager *settingsManager=nullptr)
~CSettingDependency () override=default
bool Deserialize (const TiXmlNode *node) override
SettingDependencyType GetType () const
std::set< std::string > GetSettings () const
CSettingDependencyConditionCombinationPtr And ()
CSettingDependencyConditionCombinationPtr Or ()
Public Member Functions inherited from CSettingCondition
CSettingCondition (CSettingsManager *settingsManager=nullptr)
~CSettingCondition () override=default
bool Check () const override
Public Member Functions inherited from CBooleanLogic
const CBooleanLogicOperationPtr & Get () const
CBooleanLogicOperationPtr Get ()
Public Member Functions inherited from IXmlDeserializable
virtual ~IXmlDeserializable ()=default
Public Member Functions inherited from ISettingCondition
ISettingCondition (CSettingsManager *settingsManager)
virtual ~ISettingCondition ()=default
Private Member Functions
bool setType (const std::string &type)
Private Attributes
SettingDependencyType m_type = SettingDependencyType::Unknown
Static Private Attributes
static Logger s_logger
Additional Inherited Members
Protected Member Functions inherited from CBooleanLogic
~CBooleanLogic () override=default
Protected Attributes inherited from CBooleanLogic
CBooleanLogicOperationPtr m_operation
Protected Attributes inherited from ISettingCondition
CSettingsManager * m_settingsManager
Constructor & Destructor Documentation
CSettingDependency() [1/2]
CSettingDependency::CSettingDependency (CSettingsManager * settingsManager = nullptr) explicit
CSettingDependency() [2/2]
CSettingDependency::CSettingDependency (SettingDependencyType type, CSettingsManager * settingsManager = nullptr)
References CLog::GetLogger(), CServiceBroker::GetLogging(), CBooleanLogic::m_operation, ISettingCondition::m_settingsManager, and s_logger.
~CSettingDependency()
CSettingDependency::~CSettingDependency () override default
Member Function Documentation
And()
CSettingDependencyConditionCombinationPtr CSettingDependency::And ()
References BooleanLogicOperationAnd, CBooleanLogic::m_operation, and ISettingCondition::m_settingsManager.
Referenced by PVR::CGUIDialogPVRTimerSettings::AddCondition(), CGUIDialogContentSettings::InitializeSettings(), CGUIDialogCMSSettings::InitializeSettings(), and ADDON::CAddonSettings::ParseOldCondition().
Deserialize()
bool CSettingDependency::Deserialize (const TiXmlNode * node) override virtual
Reimplemented from CBooleanLogic.
References CBooleanLogic::Deserialize(), node, s_logger, SETTING_XML_ATTR_TYPE, and setType().
Referenced by CSetting::Deserialize().
GetSettings()
std::set< std::string > CSettingDependency::GetSettings () const
References CBooleanLogic::m_operation.
GetType()
SettingDependencyType CSettingDependency::GetType () const inline
References m_type.
Referenced by CSettingsManager::UpdateSettingByDependency().
Or()
CSettingDependencyConditionCombinationPtr CSettingDependency::Or ()
References BooleanLogicOperationOr, CBooleanLogic::m_operation, and ISettingCondition::m_settingsManager.
Referenced by CGUIDialogContentSettings::InitializeSettings(), CGUIDialogAudioSettings::InitializeSettings(), CGUIDialogCMSSettings::InitializeSettings(), and ADDON::CAddonSettings::ParseOldCondition().
setType()
bool CSettingDependency::setType (const std::string & type) private
References Enable, m_type, Update, and Visible.
Referenced by Deserialize().
Member Data Documentation
m_type
SettingDependencyType CSettingDependency::m_type = SettingDependencyType::Unknown private
Referenced by GetType(), and setType().
s_logger
Logger CSettingDependency::s_logger static private
Referenced by CSettingDependency(), and Deserialize().
The documentation for this class was generated from the following files:
SettingDependency.h
SettingDependency.cpp