Kodi Documentation: CGUITextLayout Class Reference
CGUITextLayout Class Reference
#include <GUITextLayout.h>
Public Member Functions
CGUITextLayout (CGUIFont *font, bool wrap, float fHeight=0.0f, CGUIFont *borderFont=NULL)
bool UpdateScrollinfo (CScrollInfo &scrollInfo)
void Render (float x, float y, float angle, KODI::UTILS::COLOR::Color color, KODI::UTILS::COLOR::Color shadowColor, uint32_t alignment, float maxWidth, bool solid=false)
void RenderScrolling (float x, float y, float angle, KODI::UTILS::COLOR::Color color, KODI::UTILS::COLOR::Color shadowColor, uint32_t alignment, float maxWidth, const CScrollInfo &scrollInfo)
void RenderOutline (float x, float y, KODI::UTILS::COLOR::Color color, KODI::UTILS::COLOR::Color outlineColor, uint32_t alignment, float maxWidth)
void GetTextExtent (float &width, float &height) const
Returns the precalculated width and height of the text to be rendered (in constant time).
float GetTextWidth () const
Returns the precalculated width of the text to be rendered (in constant time).
float GetTextWidth (const std::wstring &text) const
float GetTextWidth (const vecText &text) const
float GetTextHeight () const
Returns the precalculated height of the text to be rendered (in constant time).
bool Update (const std::string &text, float maxWidth=0, bool forceUpdate=false, bool forceLTRReadingOrder=false)
bool UpdateW (const std::wstring &text, float maxWidth=0, bool forceUpdate=false, bool forceLTRReadingOrder=false)
void UpdateStyled (const vecText &text, const std::vector< KODI::UTILS::COLOR::Color > &colors, float maxWidth=0, bool forceLTRReadingOrder=false)
Update text from a pre-styled vecText/std::vector<KODI::UTILS::COLOR::Color> combination Allows styled text to be passed directly to the text layout.
unsigned int GetTextLength () const
void GetFirstText (vecText &text) const
void Reset ()
void SetWrap (bool bWrap=true)
void SetMaxHeight (float fHeight)
Static Public Member Functions
static void DrawText (CGUIFont *font, float x, float y, KODI::UTILS::COLOR::Color color, KODI::UTILS::COLOR::Color shadowColor, const std::string &text, uint32_t align)
static void Filter (std::string &text)
Protected Types
typedef std::vector< CGUIString >::iterator iLine
Protected Member Functions
void LineBreakText (const vecText &text, std::vector< CGUIString > &lines)
void WrapText (const vecText &text, float maxWidth)
void CalcTextExtent ()
void UpdateCommon (const std::wstring &text, float maxWidth, bool forceLTRReadingOrder)
std::string GetText () const
Returns the text, utf8 encoded.
void SetMonoFont (CGUIFont *font)
Set the monospaced font to use.
void UseMonoFont (bool use)
Set whether or not to use the monospace font.
Static Protected Member Functions
static void BidiTransform (std::vector< CGUIString > &lines, bool forceLTRReadingOrder)
static std::wstring BidiFlip (const std::wstring &text, bool forceLTRReadingOrder, int *visualToLogicalMap=nullptr)
Protected Attributes
std::vector< KODI::UTILS::COLOR::Color > m_colors
std::vector< CGUIString > m_lines
CGUIFont * m_font
CGUIFont * m_borderFont
CGUIFont * m_monoFont = nullptr
Mono-space font to use.
CGUIFont * m_varFont
Varible-space font to use.
bool m_wrap
float m_maxHeight
KODI::UTILS::COLOR::Color m_textColor
std::string m_lastUtf8Text
std::wstring m_lastText
bool m_lastUpdateW
true if the last string we updated was the wstring version
float m_textWidth
float m_textHeight
Private Member Functions
bool IsSpace (character_t letter) const XBMC_FORCE_INLINE
bool CanWrapAtLetter (character_t letter) const XBMC_FORCE_INLINE
Static Private Member Functions
static void AppendToUTF32 (const std::string &utf8, character_t colStyle, vecText &utf32)
static void AppendToUTF32 (const std::wstring &utf16, character_t colStyle, vecText &utf32)
static void ParseText (const std::wstring &text, uint32_t defaultStyle, KODI::UTILS::COLOR::Color defaultColor, std::vector< KODI::UTILS::COLOR::Color > &colors, vecText &parsedText)
Member Typedef Documentation
iLine
typedef std::vector<CGUIString>::iterator CGUITextLayout::iLine protected
Constructor & Destructor Documentation
CGUITextLayout()
CGUITextLayout::CGUITextLayout (CGUIFont * font, bool wrap, float fHeight = 0.0f, CGUIFont * borderFont = NULL)
References m_borderFont, m_font, m_lastUpdateW, m_maxHeight, m_textColor, m_textHeight, m_textWidth, m_varFont, and m_wrap.
Member Function Documentation
AppendToUTF32() [1/2]
void CGUITextLayout::AppendToUTF32 (const std::string & utf8, character_t colStyle, vecText & utf32) static private
References AppendToUTF32(), and g_charsetConverter.
Referenced by AppendToUTF32(), DrawText(), GetTextWidth(), and ParseText().
AppendToUTF32() [2/2]
void CGUITextLayout::AppendToUTF32 (const std::wstring & utf16, character_t colStyle, vecText & utf32) static private
BidiFlip()
std::wstring CGUITextLayout::BidiFlip (const std::wstring & text, bool forceLTRReadingOrder, int * visualToLogicalMap = nullptr) static protected
References g_charsetConverter, and text.
Referenced by BidiTransform().
BidiTransform()
void CGUITextLayout::BidiTransform (std::vector< CGUIString > & lines, bool forceLTRReadingOrder) static protected
References BidiFlip(), CGUIString::m_carriageReturn, and CGUIString::m_text.
Referenced by UpdateStyled().
CalcTextExtent()
void CGUITextLayout::CalcTextExtent () protected
References CGUIFont::GetTextHeight(), CGUIFont::GetTextWidth(), m_font, m_lines, m_textHeight, and m_textWidth.
Referenced by UpdateStyled().
CanWrapAtLetter()
bool CGUITextLayout::CanWrapAtLetter (character_t letter) const inline private
Todo:
: unicode spaces are not handled, to check also all other GUI parts
Referenced by WrapText().
DrawText()
void CGUITextLayout::DrawText (CGUIFont * font, float x, float y, KODI::UTILS::COLOR::Color color, KODI::UTILS::COLOR::Color shadowColor, const std::string & text, uint32_t align) static
References AppendToUTF32(), color, CGUIFont::DrawText(), and text.
Referenced by CGUIWindowSlideShow::RenderErrorMessage().
Filter()
void CGUITextLayout::Filter (std::string & text) static
References g_charsetConverter, ParseText(), and text.
GetFirstText()
void CGUITextLayout::GetFirstText (vecText & text) const
References m_lines, and text.
GetText()
std::string CGUITextLayout::GetText () const protected
Returns the text, utf8 encoded.
Returns
utf8 text
References g_charsetConverter, m_lastText, m_lastUpdateW, and m_lastUtf8Text.
Referenced by CGUITextBox::GetDescription().
GetTextExtent()
void CGUITextLayout::GetTextExtent (float & width, float & height) const
Returns the precalculated width and height of the text to be rendered (in constant time).
Parameters
width [out] width of text
height [out] height of text
See also
GetTextWidth, CalcTextExtent
References m_textHeight, and m_textWidth.
Referenced by CGUIFadeLabelControl::Process(), CGUIWindowDebugInfo::Process(), and CGUILabel::UpdateRenderRect().
GetTextHeight()
float CGUITextLayout::GetTextHeight () const inline
Returns the precalculated height of the text to be rendered (in constant time).
Returns
height of text
References m_textHeight.
GetTextLength()
unsigned int CGUITextLayout::GetTextLength () const
References m_lines.
GetTextWidth() [1/3]
float CGUITextLayout::GetTextWidth () const inline
Returns the precalculated width of the text to be rendered (in constant time).
Returns
width of text
See also
GetTextExtent, CalcTextExtent
References m_textWidth.
Referenced by CGUILabel::CalcTextWidth(), CGUILabel::GetTextWidth(), CGUILabel::Process(), and CGUILabel::Render().
GetTextWidth() [2/3]
float CGUITextLayout::GetTextWidth (const std::wstring & text) const
References AppendToUTF32(), FONT_STYLE_MASK, CGUIFont::GetStyle(), CGUIFont::GetTextWidth(), m_font, and text.
GetTextWidth() [3/3]
float CGUITextLayout::GetTextWidth (const vecText & text) const
References CGUIFont::GetTextWidth(), m_font, and text.
IsSpace()
bool CGUITextLayout::IsSpace (character_t letter) const inline private
LineBreakText()
void CGUITextLayout::LineBreakText (const vecText & text, std::vector< CGUIString > & lines) protected
References CGUIFont::GetLineHeight(), m_font, m_maxHeight, and text.
Referenced by UpdateStyled(), and WrapText().
ParseText()
void CGUITextLayout::ParseText (const std::wstring & text, uint32_t defaultStyle, KODI::UTILS::COLOR::Color defaultColor, std::vector< KODI::UTILS::COLOR::Color > & colors, vecText & parsedText) static private
References AppendToUTF32(), color, end(), FONT_STYLE_BOLD, FONT_STYLE_CAPITALIZE, FONT_STYLE_ITALICS, FONT_STYLE_LIGHT, FONT_STYLE_LOWERCASE, FONT_STYLE_MASK, FONT_STYLE_UPPERCASE, g_charsetConverter, CGUIColorManager::GetColor(), CGUIComponent::GetColorManager(), CServiceBroker::GetGUI(), t, and text.
Referenced by Filter(), and UpdateCommon().
Render()
void CGUITextLayout::Render (float x, float y, float angle, KODI::UTILS::COLOR::Color color, KODI::UTILS::COLOR::Color shadowColor, uint32_t alignment, float maxWidth, bool solid = false)
References CGraphicContext::AddTransform(), CGUIFont::Begin(), color, TransformMatrix::CreateZRotation(), CGUIFont::DrawText(), CGUIFont::End(), CWinSystemBase::GetGfxContext(), CGUIFont::GetLineHeight(), CGUIFont::GetTextHeight(), CServiceBroker::GetWinSystem(), m_colors, m_font, m_lines, CGraphicContext::RemoveTransform(), solid, XBFONT_CENTER_Y, and XBFONT_JUSTIFIED.
Referenced by CGUILabel::Render(), and CGUIFadeLabelControl::Render().
RenderOutline()
void CGUITextLayout::RenderOutline (float x, float y, KODI::UTILS::COLOR::Color color, KODI::UTILS::COLOR::Color outlineColor, uint32_t alignment, float maxWidth)
Todo:
We should really have a better way to handle text extent - at the moment we assume that text is rendered from a posx, posy, width, and height which isn't enough to accurately position text. We need a vertical and horizontal offset of the baseline and cursor as well.
References CGUIFont::Begin(), color, CGUIFont::DrawText(), CGUIFont::End(), CGUIFont::GetLineHeight(), CGUIFont::GetTextBaseLine(), CGUIFont::GetTextHeight(), CGUIFont::GetTextWidth(), m_borderFont, m_colors, m_font, m_lines, XBFONT_CENTER_X, XBFONT_CENTER_Y, and XBFONT_JUSTIFIED.
Referenced by CGUIWindowDebugInfo::Render().
RenderScrolling()
void CGUITextLayout::RenderScrolling (float x, float y, float angle, KODI::UTILS::COLOR::Color color, KODI::UTILS::COLOR::Color shadowColor, uint32_t alignment, float maxWidth, const CScrollInfo & scrollInfo)
References CGraphicContext::AddTransform(), CGUIFont::Begin(), color, TransformMatrix::CreateZRotation(), CGUIFont::DrawScrollingText(), CGUIFont::End(), CWinSystemBase::GetGfxContext(), CGUIFont::GetLineHeight(), CGUIFont::GetTextHeight(), CServiceBroker::GetWinSystem(), m_colors, m_font, m_lines, CGraphicContext::RemoveTransform(), and XBFONT_CENTER_Y.
Referenced by CGUILabel::Render(), and CGUIFadeLabelControl::Render().
Reset()
void CGUITextLayout::Reset ()
References m_lastText, m_lastUtf8Text, m_lines, m_textHeight, and m_textWidth.
Referenced by CGUITextBox::OnMessage().
SetMaxHeight()
void CGUITextLayout::SetMaxHeight (float fHeight)
References m_maxHeight.
SetMonoFont()
void CGUITextLayout::SetMonoFont (CGUIFont * font) inline protected
Set the monospaced font to use.
References m_monoFont.
Referenced by CGUITextBox::CGUITextBox().
SetWrap()
void CGUITextLayout::SetWrap (bool bWrap = true)
References m_wrap.
Update()
bool CGUITextLayout::Update (const std::string & text, float maxWidth = 0, bool forceUpdate = false, bool forceLTRReadingOrder = false)
References g_charsetConverter, m_lastUpdateW, m_lastUtf8Text, text, and UpdateCommon().
Referenced by CGUIFadeLabelControl::Process(), CGUIWindowDebugInfo::Process(), CGUILabel::SetText(), and CGUITextBox::UpdateInfo().
UpdateCommon()
void CGUITextLayout::UpdateCommon (const std::wstring & text, float maxWidth, bool forceLTRReadingOrder) protected
References CGUIFont::GetStyle(), m_font, m_textColor, ParseText(), text, and UpdateStyled().
Referenced by Update(), and UpdateW().
UpdateScrollinfo()
bool CGUITextLayout::UpdateScrollinfo (CScrollInfo & scrollInfo)
References m_font, m_lines, and CGUIFont::UpdateScrollInfo().
Referenced by CGUILabel::Process(), and CGUIFadeLabelControl::Process().
UpdateStyled()
void CGUITextLayout::UpdateStyled (const vecText & text, const std::vector< KODI::UTILS::COLOR::Color > & colors, float maxWidth = 0, bool forceLTRReadingOrder = false)
Update text from a pre-styled vecText/std::vector<KODI::UTILS::COLOR::Color> combination Allows styled text to be passed directly to the text layout.
Parameters
text the styled text to set.
colors the colors used on the text.
maxWidth the maximum width for wrapping text, defaults to 0 (no max width).
forceLTRReadingOrder whether to force left to right reading order, defaults to false.
References BidiTransform(), CalcTextExtent(), LineBreakText(), m_colors, m_lines, m_wrap, text, and WrapText().
Referenced by CGUILabel::SetStyledText(), and UpdateCommon().
UpdateW()
bool CGUITextLayout::UpdateW (const std::wstring & text, float maxWidth = 0, bool forceUpdate = false, bool forceLTRReadingOrder = false)
References m_lastText, m_lastUpdateW, text, and UpdateCommon().
Referenced by CGUILabel::SetTextW().
UseMonoFont()
void CGUITextLayout::UseMonoFont (bool use) inline protected
Set whether or not to use the monospace font.
References m_font, m_monoFont, and m_varFont.
Referenced by CGUITextBox::OnMessage().
WrapText()
void CGUITextLayout::WrapText (const vecText & text, float maxWidth) protected
References CanWrapAtLetter(), CGUIFont::GetLineHeight(), CGUIFont::GetTextWidth(), LineBreakText(), LOGWARNING, CGUIString::m_carriageReturn, m_font, m_lines, m_maxHeight, and text.
Referenced by UpdateStyled().
Member Data Documentation
m_borderFont
CGUIFont* CGUITextLayout::m_borderFont protected
Referenced by CGUITextLayout(), and RenderOutline().
m_colors
std::vector<KODI::UTILS::COLOR::Color> CGUITextLayout::m_colors protected
Referenced by CGUITextBox::Render(), Render(), RenderOutline(), RenderScrolling(), and UpdateStyled().
m_font
CGUIFont* CGUITextLayout::m_font protected
Referenced by CalcTextExtent(), CGUITextLayout(), GetTextWidth(), GetTextWidth(), LineBreakText(), CGUITextBox::Render(), Render(), RenderOutline(), RenderScrolling(), UpdateCommon(), CGUITextBox::UpdateInfo(), UpdateScrollinfo(), UseMonoFont(), and WrapText().
m_lastText
std::wstring CGUITextLayout::m_lastText protected
Referenced by GetText(), Reset(), and UpdateW().
m_lastUpdateW
bool CGUITextLayout::m_lastUpdateW protected
true if the last string we updated was the wstring version
Referenced by CGUITextLayout(), GetText(), Update(), and UpdateW().
m_lastUtf8Text
std::string CGUITextLayout::m_lastUtf8Text protected
Referenced by GetText(), Reset(), and Update().
m_lines
std::vector<CGUIString> CGUITextLayout::m_lines protected
Referenced by CalcTextExtent(), GetFirstText(), CGUITextBox::GetRows(), GetTextLength(), CGUITextBox::Process(), CGUITextBox::Render(), Render(), RenderOutline(), RenderScrolling(), Reset(), CGUITextBox::Scroll(), CGUITextBox::UpdateInfo(), CGUITextBox::UpdatePageControl(), UpdateScrollinfo(), UpdateStyled(), and WrapText().
m_maxHeight
float CGUITextLayout::m_maxHeight protected
Referenced by CGUITextLayout(), LineBreakText(), SetMaxHeight(), and WrapText().
m_monoFont
CGUIFont* CGUITextLayout::m_monoFont = nullptr protected
Mono-space font to use.
Referenced by SetMonoFont(), and UseMonoFont().
m_textColor
KODI::UTILS::COLOR::Color CGUITextLayout::m_textColor protected
Referenced by CGUITextLayout(), UpdateCommon(), and CGUITextBox::UpdateInfo().
m_textHeight
float CGUITextLayout::m_textHeight protected
Referenced by CalcTextExtent(), CGUITextLayout(), GetTextExtent(), GetTextHeight(), and Reset().
m_textWidth
float CGUITextLayout::m_textWidth protected
Referenced by CalcTextExtent(), CGUITextLayout(), GetTextExtent(), GetTextWidth(), and Reset().
m_varFont
CGUIFont* CGUITextLayout::m_varFont protected
Varible-space font to use.
Referenced by CGUITextLayout(), and UseMonoFont().
m_wrap
bool CGUITextLayout::m_wrap protected
Referenced by CGUITextLayout(), SetWrap(), and UpdateStyled().
The documentation for this class was generated from the following files:
GUITextLayout.h
GUITextLayout.cpp