Kodi Documentation: CDataCacheCore::SContentInfo Struct Reference
CDataCacheCore::SContentInfo Struct Reference
#include <DataCacheCore.h>
Public Member Functions
void SetEditList (const std::vector< EDL::Edit > &editList)
Set the EDL edit list in cache.
const std::vector< EDL::Edit > & GetEditList () const
Get the EDL edit list in cache.
void SetCuts (const std::vector< std::chrono::milliseconds > &cuts)
Save the list of cut markers in cache.
const std::vector< std::chrono::milliseconds > & GetCuts () const
Get the list of cut markers in cache.
void SetSceneMarkers (const std::vector< std::chrono::milliseconds > &sceneMarkers)
Save the list of scene markers in cache.
const std::vector< std::chrono::milliseconds > & GetSceneMarkers () const
Get the list of scene markers in cache.
void SetChapters (const std::vector< std::pair< std::string, int64_t > > &chapters)
Save the chapter list in cache.
const std::vector< std::pair< std::string, int64_t > > & GetChapters () const
Get the list of chapters in cache.
void Reset ()
Reset the content cache to the original values (all empty)
Private Attributes
std::vector< EDL::Edit > m_editList
std::vector< std::pair< std::string, int64_t > > m_chapters
std::vector< std::chrono::milliseconds > m_cuts
std::vector< std::chrono::milliseconds > m_sceneMarkers
Member Function Documentation
GetChapters()
const std::vector< std::pair< std::string, int64_t > > & CDataCacheCore::SContentInfo::GetChapters () const inline
Get the list of chapters in cache.
Returns
the list of chapters in cache
References m_chapters.
Referenced by CDataCacheCore::GetChapters().
GetCuts()
const std::vector< std::chrono::milliseconds > & CDataCacheCore::SContentInfo::GetCuts () const inline
Get the list of cut markers in cache.
Returns
the list of cut markers in cache
References m_cuts.
Referenced by CDataCacheCore::GetCuts().
GetEditList()
const std::vector< EDL::Edit > & CDataCacheCore::SContentInfo::GetEditList () const inline
Get the EDL edit list in cache.
Returns
the list of edits in cache
References m_editList.
Referenced by CDataCacheCore::GetEditList().
GetSceneMarkers()
const std::vector< std::chrono::milliseconds > & CDataCacheCore::SContentInfo::GetSceneMarkers () const inline
Get the list of scene markers in cache.
Returns
the list of scene markers in cache
References m_sceneMarkers.
Referenced by CDataCacheCore::GetSceneMarkers().
Reset()
void CDataCacheCore::SContentInfo::Reset () inline
Reset the content cache to the original values (all empty)
References m_chapters, m_cuts, m_editList, and m_sceneMarkers.
Referenced by CDataCacheCore::Reset().
SetChapters()
void CDataCacheCore::SContentInfo::SetChapters (const std::vector< std::pair< std::string, int64_t > > & chapters) inline
Save the chapter list in cache.
Parameters
chapters the list of chapters to store in cache
References m_chapters.
Referenced by CDataCacheCore::SetChapters().
SetCuts()
void CDataCacheCore::SContentInfo::SetCuts (const std::vector< std::chrono::milliseconds > & cuts) inline
Save the list of cut markers in cache.
Parameters
cuts the list of cut markers to store in cache
References m_cuts.
Referenced by CDataCacheCore::SetCuts().
SetEditList()
void CDataCacheCore::SContentInfo::SetEditList (const std::vector< EDL::Edit > & editList) inline
Set the EDL edit list in cache.
Parameters
editList the list of edits to store in cache
References m_editList.
Referenced by CDataCacheCore::SetEditList().
SetSceneMarkers()
void CDataCacheCore::SContentInfo::SetSceneMarkers (const std::vector< std::chrono::milliseconds > & sceneMarkers) inline
Save the list of scene markers in cache.
Parameters
sceneMarkers the list of scene markers to store in cache
References m_sceneMarkers.
Referenced by CDataCacheCore::SetSceneMarkers().
Member Data Documentation
m_chapters
std::vector<std::pair<std::string, int64_t> > CDataCacheCore::SContentInfo::m_chapters private
position for EDL cuts
Referenced by GetChapters(), Reset(), and SetChapters().
m_cuts
std::vector<std::chrono::milliseconds> CDataCacheCore::SContentInfo::m_cuts private
position for EDL scene markers
Referenced by GetCuts(), Reset(), and SetCuts().
m_editList
std::vector<EDL::Edit> CDataCacheCore::SContentInfo::m_editList private
< list of EDL edits name and position for chapters
Referenced by GetEditList(), Reset(), and SetEditList().
m_sceneMarkers
std::vector<std::chrono::milliseconds> CDataCacheCore::SContentInfo::m_sceneMarkers private
Referenced by GetSceneMarkers(), Reset(), and SetSceneMarkers().
The documentation for this struct was generated from the following file:
DataCacheCore.h