Kodi Documentation: AESinkFactoryWin32.cpp File Reference
AESinkFactoryWin32.cpp File Reference
#include "AESinkFactoryWin.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include "platform/win32/CharsetConverter.h"
#include "platform/win32/WIN32Util.h"
#include <algorithm>
#include <mmdeviceapi.h>
#include <wrl/client.h>
Classes
struct AEWASAPIDeviceWin32
Macros
#define EXIT_ON_FAILURE(hr, reason)
Functions
DEFINE_PROPERTYKEY (PKEY_Device_FriendlyName, 0xa45c254e, 0xdf1c, 0x4efd, 0x80, 0x20, 0x67, 0xd1, 0x46, 0xa8, 0x50, 0xe0, 14)
DEFINE_PROPERTYKEY (PKEY_Device_EnumeratorName, 0xa45c254e, 0xdf1c, 0x4efd, 0x80, 0x20, 0x67, 0xd1, 0x46, 0xa8, 0x50, 0xe0, 24)
Variables
const CLSID CLSID_MMDeviceEnumerator = __uuidof(MMDeviceEnumerator)
const IID IID_IMMDeviceEnumerator = __uuidof(IMMDeviceEnumerator)
const IID IID_IAudioClient = __uuidof(IAudioClient)
Macro Definition Documentation
EXIT_ON_FAILURE
#define EXIT_ON_FAILURE (hr, reason)
Value:
  if (FAILED(hr)) \
  { \
    CLog::LogF(LOGERROR, reason " - {}", hr, CWIN32Util::FormatHRESULT(hr)); \
    goto failed; \
  }
Function Documentation
DEFINE_PROPERTYKEY() [1/2]
DEFINE_PROPERTYKEY (PKEY_Device_EnumeratorName , 0xa45c254e , 0xdf1c , 0x4efd , 0x80 , 0x20 , 0x67 , 0xd1 , 0x46 , 0xa8 , 0x50 , 0xe0 , 24)
DEFINE_PROPERTYKEY() [2/2]
DEFINE_PROPERTYKEY (PKEY_Device_FriendlyName , 0xa45c254e , 0xdf1c , 0x4efd , 0x80 , 0x20 , 0x67 , 0xd1 , 0x46 , 0xa8 , 0x50 , 0xe0 , 14)
Variable Documentation
CLSID_MMDeviceEnumerator
const CLSID CLSID_MMDeviceEnumerator = __uuidof(MMDeviceEnumerator)
Referenced by CAESinkDirectSound::EnumerateDevicesEx(), CAESinkDirectSound::GetDefaultDevice(), and XBMC_Run().
IID_IAudioClient
const IID IID_IAudioClient = __uuidof(IAudioClient)
Referenced by AEWASAPIDeviceWin32::Activate(), and CAESinkDirectSound::EnumerateDevicesEx().
IID_IMMDeviceEnumerator
const IID IID_IMMDeviceEnumerator = __uuidof(IMMDeviceEnumerator)
Referenced by CAESinkDirectSound::EnumerateDevicesEx(), CAESinkDirectSound::GetDefaultDevice(), and XBMC_Run().