Kodi Documentation: CIRServerSuite Class Reference
CIRServerSuite Class Reference
#include <IRServerSuite.h>
Public Member Functions
CIRServerSuite ()
virtual ~CIRServerSuite ()
void Initialize ()
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Protected Member Functions
virtual void Process ()
bool ReadNext ()
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Member Functions
bool SendPacket (CIrssMessage &message)
int ReadPacket (CIrssMessage &message)
int ReadN (char *buffer, int n)
bool WriteN (const char *buffer, int n)
bool Connect (bool logMessages)
void Close ()
bool HandleRemoteEvent (CIrssMessage &message)
Private Attributes
bool m_bInitialized
bool m_isConnecting
int m_profileId
SOCKET m_socket
CEvent m_event
CCriticalSection m_critSection
KODI::KEYMAP::CIRTranslator m_irTranslator
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CIRServerSuite()
CIRServerSuite::CIRServerSuite ()
~CIRServerSuite()
CIRServerSuite::~CIRServerSuite () virtual
References Close(), m_critSection, m_event, CEvent::Set(), and CThread::StopThread().
Member Function Documentation
Close()
void CIRServerSuite::Close () private
References closesocket, INVALID_SOCKET, IRSSMF_ForceNotRespond, IRSSMF_Request, IRSSMT_UnregisterClient, m_bInitialized, m_isConnecting, m_socket, SendPacket(), and shutdown().
Referenced by Connect(), Process(), ReadN(), ReadNext(), SendPacket(), WriteN(), and ~CIRServerSuite().
Connect()
bool CIRServerSuite::Connect (bool logMessages) private
References Close(), closesocket, KODI::PLATFORM::WINDOWS::FromW(), INVALID_SOCKET, ioctlsocket, IRSS_PORT, IRSSMF_Request, IRSSMT_RegisterClient, LOGDEBUG, LOGERROR, m_isConnecting, m_socket, SendPacket(), and SOCKET_ERROR.
Referenced by Process().
HandleRemoteEvent()
bool CIRServerSuite::HandleRemoteEvent (CIrssMessage & message) private
References XBMC_ButtonEvent::button, data(), CServiceBroker::GetAppPort(), CIrssMessage::GetData(), CIrssMessage::GetDataSize(), CServiceBroker::GetSettingsComponent(), XBMC_ButtonEvent::holdtime, IRSS_MAP_FILENAME, XBMC_Event::keybutton, KODI::KEYMAP::CIRTranslator::Load(), LOGDEBUG, LOGERROR, m_irTranslator, m_profileId, KODI::KEYMAP::CIRTranslator::TranslateButton(), XBMC_Event::type, and XBMC_BUTTON.
Referenced by ReadNext().
Initialize()
void CIRServerSuite::Initialize ()
References CThread::Create(), LOWEST, and CThread::SetPriority().
Process()
void CIRServerSuite::Process (void) protected virtual
Reimplemented from CThread.
References CThread::AbortableWait(), Close(), Connect(), CServiceBroker::GetSettingsComponent(), IRSS_MAP_FILENAME, KODI::KEYMAP::CIRTranslator::Load(), LOGINFO, CThread::m_bStop, m_event, m_irTranslator, m_profileId, ReadNext(), and CThread::WAIT_SIGNALED.
ReadN()
int CIRServerSuite::ReadN (char * buffer, int n) private
References Close(), LOGDEBUG, LOGERROR, m_critSection, m_isConnecting, m_socket, and WSAGetLastError.
Referenced by ReadPacket().
ReadNext()
bool CIRServerSuite::ReadNext () protected
References Close(), data(), CIrssMessage::GetData(), CIrssMessage::GetDataSize(), CIrssMessage::GetFlags(), CIrssMessage::GetType(), HandleRemoteEvent(), INVALID_SOCKET, IRSSMF_Request, IRSSMF_Success, IRSSMT_ActiveReceivers, IRSSMT_AvailableReceivers, IRSSMT_DetectedReceivers, IRSSMT_Error, IRSSMT_RegisterClient, IRSSMT_RemoteEvent, IRSSMT_ServerResume, IRSSMT_ServerShutdown, IRSSMT_ServerSuspend, LOGERROR, LOGINFO, m_bInitialized, m_isConnecting, m_socket, ReadPacket(), SendPacket(), and CIrssMessage::SetType().
Referenced by Process().
ReadPacket()
int CIRServerSuite::ReadPacket (CIrssMessage & message) private
References CIrssMessage::FromBytes(), LOGERROR, and ReadN().
Referenced by ReadNext().
SendPacket()
bool CIRServerSuite::SendPacket (CIrssMessage & message) private
References Close(), CIrssMessage::ToBytes(), and WriteN().
Referenced by Close(), Connect(), and ReadNext().
WriteN()
bool CIRServerSuite::WriteN (const char * buffer, int n) private
References Close(), LOGERROR, m_critSection, m_socket, and WSAGetLastError.
Referenced by SendPacket().
Member Data Documentation
m_bInitialized
bool CIRServerSuite::m_bInitialized private
Referenced by Close(), and ReadNext().
m_critSection
CCriticalSection CIRServerSuite::m_critSection private
Referenced by ReadN(), WriteN(), and ~CIRServerSuite().
m_event
CEvent CIRServerSuite::m_event private
Referenced by Process(), and ~CIRServerSuite().
m_irTranslator
KODI::KEYMAP::CIRTranslator CIRServerSuite::m_irTranslator private
Referenced by HandleRemoteEvent(), and Process().
m_isConnecting
bool CIRServerSuite::m_isConnecting private
Referenced by Close(), Connect(), ReadN(), and ReadNext().
m_profileId
int CIRServerSuite::m_profileId private
Referenced by HandleRemoteEvent(), and Process().
m_socket
SOCKET CIRServerSuite::m_socket private
Referenced by Close(), Connect(), ReadN(), ReadNext(), and WriteN().
The documentation for this class was generated from the following files:
IRServerSuite.h
IRServerSuite.cpp