Kodi Documentation: CEventLog Class Reference
CEventLog Class Reference
#include <EventLog.h>
Public Member Functions
CEventLog ()=default
CEventLog (const CEventLog &)=delete
CEventLog & operator= (CEventLog const &)=delete
~CEventLog ()=default
const Events & Get () const
Events Get (EventLevel level, bool includeHigherLevels=false) const
EventPtr Get (const std::string &eventIdentifier) const
void Add (const EventPtr &event)
void Add (const EventPtr &event, bool withNotification, bool withSound=true)
void AddWithNotification (const EventPtr &event, unsigned int displayTime=NOTIFICATION_DISPLAY_TIME, unsigned int messageTime=NOTIFICATION_MESSAGE_TIME, bool withSound=true)
void AddWithNotification (const EventPtr &event, bool withSound)
void Remove (const EventPtr &event)
void Remove (const std::string &eventIdentifier)
void Clear ()
void Clear (EventLevel level, bool includeHigherLevels=false)
bool Execute (const std::string &eventIdentifier)
void ShowFullEventLog (EventLevel level=EventLevel::Basic, bool includeHigherLevels=true)
Static Public Member Functions
static std::string EventLevelToString (EventLevel level)
static EventLevel EventLevelFromString (const std::string &level)
Private Types
typedef std::vector< EventPtr > EventsList
typedef std::map< std::string, EventPtr > EventsMap
Private Member Functions
void SendMessage (const EventPtr &event, int message)
Private Attributes
EventsList m_events
EventsMap m_eventsMap
CCriticalSection m_critical
Member Typedef Documentation
EventsList
typedef std::vector<EventPtr> CEventLog::EventsList private
EventsMap
typedef std::map<std::string, EventPtr> CEventLog::EventsMap private
Constructor & Destructor Documentation
CEventLog() [1/2]
CEventLog::CEventLog () default
CEventLog() [2/2]
CEventLog::CEventLog (const CEventLog &) delete
~CEventLog()
CEventLog::~CEventLog () default
Member Function Documentation
Add() [1/2]
void CEventLog::Add (const EventPtr & event)
References CServiceBroker::GetSettingsComponent(), GUI_MSG_EVENT_ADDED, Information, m_critical, m_events, m_eventsMap, SendMessage(), CSettings::SETTING_EVENTLOG_ENABLED, and CSettings::SETTING_EVENTLOG_ENABLED_NOTIFICATIONS.
Referenced by Add(), and AddWithNotification().
Add() [2/2]
void CEventLog::Add (const EventPtr & event, bool withNotification, bool withSound = true)
References Add(), and AddWithNotification().
AddWithNotification() [1/2]
void CEventLog::AddWithNotification (const EventPtr & event, bool withSound)
References AddWithNotification(), NOTIFICATION_DISPLAY_TIME, and NOTIFICATION_MESSAGE_TIME.
AddWithNotification() [2/2]
void CEventLog::AddWithNotification (const EventPtr & event, unsigned int displayTime = NOTIFICATION_DISPLAY_TIME, unsigned int messageTime = NOTIFICATION_MESSAGE_TIME, bool withSound = true)
References Add(), CGUIDialogKaiToast::Error, Error, CGUIDialogKaiToast::Info, CGUIDialogKaiToast::QueueNotification(), CGUIDialogKaiToast::Warning, and Warning.
Referenced by Add(), AddWithNotification(), ADDON::CAddonDll::CheckAPIVersion(), and KODI::GAME::CGameSettings::LoginToRA().
Clear() [1/2]
void CEventLog::Clear ()
References m_critical, m_events, and m_eventsMap.
Clear() [2/2]
void CEventLog::Clear (EventLevel level, bool includeHigherLevels = false)
References m_events, and Remove().
EventLevelFromString()
EventLevel CEventLog::EventLevelFromString (const std::string & level) static
References Basic, Error, Information, and Warning.
Referenced by XFILE::CEventsDirectory::GetDirectory(), and CGUIWindowEventLog::GetDirectory().
EventLevelToString()
std::string CEventLog::EventLevelToString (EventLevel level) static
References Basic, Error, Information, and Warning.
Referenced by XFILE::CEventsDirectory::EventToFileItem(), and ShowFullEventLog().
Execute()
bool CEventLog::Execute (const std::string & eventIdentifier)
References m_critical, and m_eventsMap.
Get() [1/3]
const Events & CEventLog::Get () const
References m_events.
Get() [2/3]
EventPtr CEventLog::Get (const std::string & eventIdentifier) const
References m_critical, and m_eventsMap.
Get() [3/3]
Events CEventLog::Get (EventLevel level, bool includeHigherLevels = false) const
References events, m_critical, and m_events.
operator=()
CEventLog & CEventLog::operator= (CEventLog const &) delete
Remove() [1/2]
void CEventLog::Remove (const EventPtr & event)
References Remove().
Referenced by Clear(), and Remove().
Remove() [2/2]
void CEventLog::Remove (const std::string & eventIdentifier)
References GUI_MSG_EVENT_REMOVED, m_critical, m_events, m_eventsMap, and SendMessage().
SendMessage()
void CEventLog::SendMessage (const EventPtr & event, int message) private
References XFILE::CEventsDirectory::EventToFileItem(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and GUI_MSG_NOTIFY_ALL.
Referenced by Add(), and Remove().
ShowFullEventLog()
void CEventLog::ShowFullEventLog (EventLevel level = EventLevel::Basic, bool includeHigherLevels = true)
References CGUIWindowManager::ActivateWindow(), Basic, EventLevelToString(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and WINDOW_EVENT_LOG.
Referenced by CProfileManager::OnSettingAction().
Member Data Documentation
m_critical
CCriticalSection CEventLog::m_critical mutable private
Referenced by Add(), Clear(), Execute(), Get(), Get(), and Remove().
m_events
EventsList CEventLog::m_events private
Referenced by Add(), Clear(), Clear(), Get(), Get(), and Remove().
m_eventsMap
EventsMap CEventLog::m_eventsMap private
Referenced by Add(), Clear(), Execute(), Get(), and Remove().
The documentation for this class was generated from the following files:
EventLog.h
EventLog.cpp