Kodi Documentation: CDVDSubtitleLineCollection Class Reference
CDVDSubtitleLineCollection Class Reference
#include <DVDSubtitleLineCollection.h>
Public Member Functions
CDVDSubtitleLineCollection ()
virtual ~CDVDSubtitleLineCollection ()
void Add (std::shared_ptr< CDVDOverlay > pSubtitle)
void Sort ()
std::shared_ptr< CDVDOverlay > Get (double iPts=0LL)
void Reset ()
void Remove ()
void Clear ()
int GetSize ()
Private Attributes
ListElement * m_pHead
ListElement * m_pCurrent
ListElement * m_pTail
int m_iSize
Constructor & Destructor Documentation
CDVDSubtitleLineCollection()
CDVDSubtitleLineCollection::CDVDSubtitleLineCollection ()
References m_iSize, m_pCurrent, m_pHead, and m_pTail.
~CDVDSubtitleLineCollection()
CDVDSubtitleLineCollection::~CDVDSubtitleLineCollection () virtual
References Clear().
Member Function Documentation
Add()
void CDVDSubtitleLineCollection::Add (std::shared_ptr< CDVDOverlay > pSubtitle)
References m_iSize, m_pCurrent, m_pHead, m_pTail, stListElement::pNext, and stListElement::pOverlay.
Referenced by CDVDSubtitleParserMicroDVD::Open(), CDVDSubtitleParserMPL2::Open(), CDVDSubtitleParserSami::Open(), CDVDSubtitleParserSSA::Open(), CDVDSubtitleParserSubrip::Open(), CDVDSubtitleParserVplayer::Open(), and CSubtitleParserWebVTT::Open().
Clear()
void CDVDSubtitleLineCollection::Clear ()
References m_iSize, m_pCurrent, m_pHead, m_pTail, and stListElement::pNext.
Referenced by ~CDVDSubtitleLineCollection().
Get()
std::shared_ptr< CDVDOverlay > CDVDSubtitleLineCollection::Get (double iPts = 0LL)
References m_pCurrent, stListElement::pNext, and stListElement::pOverlay.
Referenced by CDVDSubtitleParserCollection::Parse().
GetSize()
int CDVDSubtitleLineCollection::GetSize () inline
References m_iSize.
Remove()
void CDVDSubtitleLineCollection::Remove ()
Reset()
void CDVDSubtitleLineCollection::Reset ()
References m_pCurrent, and m_pHead.
Referenced by CDVDSubtitleParserCollection::Reset().
Sort()
void CDVDSubtitleLineCollection::Sort ()
References m_pHead, and stListElement::pNext.
Member Data Documentation
m_iSize
int CDVDSubtitleLineCollection::m_iSize private
Referenced by Add(), CDVDSubtitleLineCollection(), Clear(), and GetSize().
m_pCurrent
ListElement* CDVDSubtitleLineCollection::m_pCurrent private
Referenced by Add(), CDVDSubtitleLineCollection(), Clear(), Get(), and Reset().
m_pHead
ListElement* CDVDSubtitleLineCollection::m_pHead private
Referenced by Add(), CDVDSubtitleLineCollection(), Clear(), Reset(), and Sort().
m_pTail
ListElement* CDVDSubtitleLineCollection::m_pTail private
Referenced by Add(), CDVDSubtitleLineCollection(), and Clear().
The documentation for this class was generated from the following files:
DVDSubtitleLineCollection.h
DVDSubtitleLineCollection.cpp