Kodi Documentation: CPlatformLinux Class Reference
CPlatformLinux Class Reference
#include <PlatformLinux.h>
Public Member Functions
CPlatformLinux ()=default
~CPlatformLinux () override=default
bool InitStageOne () override
Called at an early stage of application startup.
void DeinitStageOne () override
Called at a late stage of application shutdown.
bool IsConfigureAddonsAtStartupEnabled () override
Flag whether disabled add-ons - installed via packagemanager or manually - should be offered for configuration and activation on kodi startup for this platform.
Public Member Functions inherited from CPlatformPosix
bool InitStageOne () override
Called at an early stage of application startup.
Public Member Functions inherited from CPlatform
CPlatform ()=default
C'tor.
virtual ~CPlatform ()=default
D'tor.
virtual bool InitStageTwo ()
Called at a middle stage of application startup.
virtual bool InitStageThree ()
Called at a late stage of application startup.
virtual void DeinitStageTwo ()
Called at a middle stage of application shutdown.
virtual void DeinitStageThree ()
Called at an early stage of application shutdown.
virtual bool SupportsUserInstalledBinaryAddons ()
Flag whether this platform supports user installation of binary add-ons.
virtual void PlatformSyslog ()
Print platform specific info to log.
template<class T >
std::shared_ptr< T > GetService ()
Get a platform service instance.
Public Member Functions inherited from CComponentContainer< IPlatformService >
std::shared_ptr< T > GetComponent ()
Obtain a component.
std::shared_ptr< const T > GetComponent () const
Obtain a component.
std::size_t size () const
Returns number of registered components.
Protected Member Functions
virtual void RegisterPowerManagement ()
Protected Member Functions inherited from CComponentContainer< IPlatformService >
void RegisterComponent (const std::shared_ptr< IPlatformService > &component)
Register a new component instance.
void DeregisterComponent (const std::type_info &typeInfo)
Deregister a component.
Private Attributes
std::unique_ptr< OPTIONALS::CLircContainer, OPTIONALS::delete_CLircContainer > m_lirc
Additional Inherited Members
Static Public Member Functions inherited from CPlatformPosix
static bool TestQuitFlag ()
static void RequestQuit ()
Static Public Member Functions inherited from CPlatform
static CPlatform * CreateInstance ()
Creates the Platform object.
Constructor & Destructor Documentation
CPlatformLinux()
CPlatformLinux::CPlatformLinux () default
~CPlatformLinux()
CPlatformLinux::~CPlatformLinux () override default
Member Function Documentation
DeinitStageOne()
void CPlatformLinux::DeinitStageOne () override virtual
Called at a late stage of application shutdown.
This method should be used to cleanup resources allocated in InitStageOne
Reimplemented from CPlatform.
References CComponentContainer< IPlatformService >::DeregisterComponent().
InitStageOne()
bool CPlatformLinux::InitStageOne () override virtual
Called at an early stage of application startup.
This method can be used to do platform specific environment preparation or initialisation (like setting environment variables for example)
Reimplemented from CPlatform.
Reimplemented in CPlatformWebOS.
References OPTIONALS::ALSARegister(), CServiceBroker::GetAppParams(), CPlatformPosix::InitStageOne(), OPTIONALS::LircRegister(), m_lirc, OPTIONALS::PipewireRegister(), OPTIONALS::PulseAudioRegister(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::Register(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::Register(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::Register(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::Register(), KODI::WINDOWING::X11::CWinSystemX11GLContext::Register(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::Register(), CComponentContainer< IPlatformService >::RegisterComponent(), RegisterPowerManagement(), and OPTIONALS::SndioRegister().
Referenced by CPlatformWebOS::InitStageOne().
IsConfigureAddonsAtStartupEnabled()
bool CPlatformLinux::IsConfigureAddonsAtStartupEnabled () override virtual
Flag whether disabled add-ons - installed via packagemanager or manually - should be offered for configuration and activation on kodi startup for this platform.
Reimplemented from CPlatform.
RegisterPowerManagement()
void CPlatformLinux::RegisterPowerManagement () protected virtual
Reimplemented in CPlatformWebOS.
References CLinuxPowerSyscall::Register().
Referenced by InitStageOne().
Member Data Documentation
m_lirc
std::unique_ptr<OPTIONALS::CLircContainer, OPTIONALS::delete_CLircContainer> CPlatformLinux::m_lirc private
Referenced by InitStageOne().
The documentation for this class was generated from the following files:
PlatformLinux.h
PlatformLinux.cpp