Kodi Documentation: MatrixGL.cpp File Reference
MatrixGL.cpp File Reference
#include "MatrixGL.h"
#include "ServiceBroker.h"
#include "utils/TransformMatrix.h"
#include <cmath>
Functions
static void __gluMultMatrixVecf (const GLfloat matrix[16], const GLfloat in[4], GLfloat out[4])
Variables
CMatrixGLStack glMatrixModview = CMatrixGLStack()
CMatrixGLStack glMatrixProject = CMatrixGLStack()
CMatrixGLStack glMatrixTexture = CMatrixGLStack()
Function Documentation
__gluMultMatrixVecf()
static void __gluMultMatrixVecf (const GLfloat matrix[16], const GLfloat in[4], GLfloat out[4]) static
Referenced by CMatrixGL::Project().
Variable Documentation
glMatrixModview
CMatrixGLStack glMatrixModview = CMatrixGLStack()
Referenced by _VerifyGLState(), CRenderSystemGL::ApplyStateBlock(), CRenderSystemGLES::ApplyStateBlock(), CRenderSystemGL::CaptureStateBlock(), CRenderSystemGLES::CaptureStateBlock(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGLShader::OnEnabled(), CGLESShader::OnEnabled(), CRenderSystemGL::Project(), CRenderSystemGLES::Project(), OVERLAY::COverlayGlyphGL::Render(), OVERLAY::COverlayGlyphGLES::Render(), CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGLES::RenderFromFBO(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGLES::RenderSinglePass(), CLinuxRendererGL::RenderSinglePass(), CLinuxRendererGLES::RenderToFBO(), CLinuxRendererGL::RenderToFBO(), CRenderSystemGL::ResetRenderSystem(), CRenderSystemGLES::ResetRenderSystem(), CRenderSystemGL::SetCameraPosition(), and CRenderSystemGLES::SetCameraPosition().
glMatrixProject
CMatrixGLStack glMatrixProject = CMatrixGLStack()
Referenced by _VerifyGLState(), CRenderSystemGL::ApplyStateBlock(), CRenderSystemGLES::ApplyStateBlock(), CRenderSystemGL::CaptureStateBlock(), CRenderSystemGLES::CaptureStateBlock(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGLShader::OnEnabled(), CGLESShader::OnEnabled(), CRenderSystemGL::Project(), CRenderSystemGLES::Project(), OVERLAY::COverlayGlyphGL::Render(), OVERLAY::COverlayGlyphGLES::Render(), CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGLES::RenderFromFBO(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGLES::RenderSinglePass(), CLinuxRendererGL::RenderSinglePass(), CLinuxRendererGLES::RenderToFBO(), CLinuxRendererGL::RenderToFBO(), CRenderSystemGL::ResetRenderSystem(), CRenderSystemGLES::ResetRenderSystem(), CRenderSystemGL::SetCameraPosition(), and CRenderSystemGLES::SetCameraPosition().
glMatrixTexture
CMatrixGLStack glMatrixTexture = CMatrixGLStack()
Referenced by CRenderSystemGL::ApplyStateBlock(), CRenderSystemGLES::ApplyStateBlock(), CRenderSystemGL::CaptureStateBlock(), CRenderSystemGLES::CaptureStateBlock(), CRenderSystemGL::ResetRenderSystem(), and CRenderSystemGLES::ResetRenderSystem().