Kodi Documentation: CWinEventsAndroid Class Reference
CWinEventsAndroid Class Reference
#include <WinEventsAndroid.h>
Public Member Functions
CWinEventsAndroid ()
~CWinEventsAndroid () override
void MessagePush (XBMC_Event *newEvent)
void MessagePushRepeat (XBMC_Event *repeatEvent)
bool MessagePump () override
Public Member Functions inherited from IWinEvents
virtual ~IWinEvents ()=default
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Member Functions
size_t GetQueueSize ()
void Process () override
Private Attributes
CCriticalSection m_eventsCond
std::list< XBMC_Event > m_events
CCriticalSection m_lasteventCond
std::queue< XBMC_Event > m_lastevent
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CWinEventsAndroid()
CWinEventsAndroid::CWinEventsAndroid ()
References CThread::Create(), CLog::Log(), and LOGDEBUG.
~CWinEventsAndroid()
CWinEventsAndroid::~CWinEventsAndroid () override
References CThread::m_bStop, and CThread::StopThread().
Member Function Documentation
GetQueueSize()
size_t CWinEventsAndroid::GetQueueSize () private
References m_events, and m_eventsCond.
Referenced by MessagePump().
MessagePump()
bool CWinEventsAndroid::MessagePump () override virtual
Implements IWinEvents.
References CServiceBroker::GetAppPort(), CServiceBroker::GetGUI(), GetQueueSize(), CGUIComponent::GetWindowManager(), GUI_MSG_UNFOCUS_ALL, m_events, m_eventsCond, CGUIWindowManager::SendMessage(), XBMC_Event::type, and XBMC_MOUSEBUTTONUP.
MessagePush()
void CWinEventsAndroid::MessagePush (XBMC_Event * newEvent)
References m_events, and m_eventsCond.
Referenced by CWinSystemAndroid::MessagePush().
MessagePushRepeat()
void CWinEventsAndroid::MessagePushRepeat (XBMC_Event * repeatEvent)
References different_event(), m_events, and m_eventsCond.
Referenced by Process().
Process()
void CWinEventsAndroid::Process (void) override private virtual
Reimplemented from CThread.
References different_event(), EVENT_STATE_HOLD, EVENT_STATE_REPEAT, EVENT_STATE_TEST, CLog::Log(), LOGDEBUG, CThread::m_bStop, m_lastevent, m_lasteventCond, MessagePushRepeat(), and CThread::Sleep().
Member Data Documentation
m_events
std::list<XBMC_Event> CWinEventsAndroid::m_events private
Referenced by GetQueueSize(), MessagePump(), MessagePush(), and MessagePushRepeat().
m_eventsCond
CCriticalSection CWinEventsAndroid::m_eventsCond private
Referenced by GetQueueSize(), MessagePump(), MessagePush(), and MessagePushRepeat().
m_lastevent
std::queue<XBMC_Event> CWinEventsAndroid::m_lastevent private
Referenced by Process().
m_lasteventCond
CCriticalSection CWinEventsAndroid::m_lasteventCond private
Referenced by Process().
The documentation for this class was generated from the following files:
WinEventsAndroid.h
WinEventsAndroid.cpp