Kodi Documentation: CFileItemList Class Reference
CFileItemList Class Reference
Represents a list of files.
#include <FileItemList.h>
Public Types
enum CACHE_TYPE { CACHE_NEVER = 0 , CACHE_IF_SLOW , CACHE_ALWAYS }
Public Types inherited from CGUIListItem
enum GUIIconOverlay {
ICON_OVERLAY_NONE = 0 , ICON_OVERLAY_RAR , ICON_OVERLAY_ZIP , ICON_OVERLAY_LOCKED ,
ICON_OVERLAY_UNWATCHED , ICON_OVERLAY_WATCHED , ICON_OVERLAY_HD
}
typedef std::map< std::string, std::string > ArtMap
Public Member Functions
CFileItemList ()
CFileItemList (const std::string &strPath)
~CFileItemList () override
void Archive (CArchive &ar) override
CFileItemPtr operator[] (int iItem)
const CFileItemPtr operator[] (int iItem) const
CFileItemPtr operator[] (const std::string &strPath)
const CFileItemPtr operator[] (const std::string &strPath) const
void Clear ()
void ClearItems ()
void Add (CFileItemPtr item)
void Add (CFileItem &&item)
void AddFront (const CFileItemPtr &pItem, int itemPosition)
void Remove (CFileItem *pItem)
void Remove (int iItem)
CFileItemPtr Get (int iItem) const
const VECFILEITEMS & GetList () const
CFileItemPtr Get (const std::string &strPath) const
int Size () const
bool IsEmpty () const
void Append (const CFileItemList &itemlist)
void Assign (const CFileItemList &itemlist, bool append=false)
bool Copy (const CFileItemList &item, bool copyItems=true)
void Reserve (size_t iCount)
void Sort (SortBy sortBy, SortOrder sortOrder, SortAttribute sortAttributes=SortAttributeNone)
void Sort (SortDescription sortDescription)
void Randomize ()
void FillInDefaultIcons ()
int GetFolderCount () const
int GetFileCount () const
int GetSelectedCount () const
int GetObjectCount () const
void FilterCueItems ()
void RemoveExtensions ()
void SetIgnoreURLOptions (bool ignoreURLOptions)
void SetFastLookup (bool fastLookup)
bool Contains (const std::string &fileName) const
bool GetFastLookup () const
void Stack (bool stackFiles=true)
stack a CFileItemList By default we stack all items (files and folders) in a CFileItemList
SortOrder GetSortOrder () const
SortBy GetSortMethod () const
void SetSortOrder (SortOrder sortOrder)
void SetSortMethod (SortBy sortBy)
bool Load (int windowID=0)
load a CFileItemList out of the cache
bool Save (int windowID=0)
save a CFileItemList to the cache
void SetCacheToDisc (CACHE_TYPE cacheToDisc)
bool CacheToDiscAlways () const
bool CacheToDiscIfSlow () const
void RemoveDiscCache (int windowID=0) const
remove a previously cached CFileItemList from the cache
void RemoveDiscCache (const std::string &cachefile) const
void RemoveDiscCacheCRC (const std::string &crc) const
bool AlwaysCache () const
void Swap (unsigned int item1, unsigned int item2)
bool UpdateItem (const CFileItem *item)
Update an item in the item list.
void AddSortMethod (SortBy sortBy, int buttonLabel, const LABEL_MASKS &labelMasks, SortAttribute sortAttributes=SortAttributeNone)
void AddSortMethod (SortBy sortBy, SortAttribute sortAttributes, int buttonLabel, const LABEL_MASKS &labelMasks)
void AddSortMethod (const SortDescription &sortDescription, int buttonLabel, const LABEL_MASKS &labelMasks)
bool HasSortDetails () const
const std::vector< GUIViewSortDetails > & GetSortDetails () const
void SetSortIgnoreFolders (bool sort)
Specify whether this list should be sorted with folders separate from files By default we sort with folders listed (and sorted separately) except for those sort modes which should be explicitly sorted with folders interleaved with files (eg SORT_METHOD_FILES). With this set the folder state will be ignored, allowing folders and files to sort interleaved.
bool GetReplaceListing () const
void SetReplaceListing (bool replace)
void SetContent (const std::string &content)
const std::string & GetContent () const
void ClearSortState ()
VECFILEITEMS::iterator begin ()
VECFILEITEMS::iterator end ()
VECFILEITEMS::iterator erase (VECFILEITEMS::iterator first, VECFILEITEMS::iterator last)
VECFILEITEMS::const_iterator begin () const
VECFILEITEMS::const_iterator end () const
VECFILEITEMS::const_iterator cbegin () const
VECFILEITEMS::const_iterator cend () const
std::reverse_iterator< VECFILEITEMS::const_iterator > rbegin () const
std::reverse_iterator< VECFILEITEMS::const_iterator > rend () const
Public Member Functions inherited from CFileItem
CFileItem (void)
CFileItem (const CFileItem &item)
CFileItem (const CGUIListItem &item)
CFileItem (const std::string &strLabel)
CFileItem (const char *strLabel)
CFileItem (const CURL &path, bool bIsFolder)
CFileItem (const std::string &strPath, bool bIsFolder)
CFileItem (const CSong &song)
CFileItem (const CSong &song, const MUSIC_INFO::CMusicInfoTag &music)
CFileItem (const CURL &path, const CAlbum &album)
CFileItem (const std::string &path, const CAlbum &album)
CFileItem (const CArtist &artist)
CFileItem (const CGenre &genre)
CFileItem (const MUSIC_INFO::CMusicInfoTag &music)
CFileItem (const CVideoInfoTag &movie)
CFileItem (const std::shared_ptr< PVR::CPVREpgInfoTag > &tag)
CFileItem (const std::shared_ptr< PVR::CPVREpgSearchFilter > &filter)
CFileItem (const std::shared_ptr< PVR::CPVRChannelGroupMember > &channelGroupMember)
CFileItem (const std::shared_ptr< PVR::CPVRRecording > &record)
CFileItem (const std::shared_ptr< PVR::CPVRTimerInfoTag > &timer)
CFileItem (const std::string &path, const std::shared_ptr< PVR::CPVRProvider > &provider)
CFileItem (const CMediaSource &share)
CFileItem (std::shared_ptr< const ADDON::IAddon > addonInfo)
CFileItem (const EventPtr &eventLogEntry)
~CFileItem (void) override
CGUIListItem * Clone () const override
const CURL GetURL () const
void SetURL (const CURL &url)
bool IsURL (const CURL &url) const
const std::string & GetPath () const
void SetPath (const std::string &path)
bool IsPath (const std::string &path, bool ignoreURLOptions=false) const
const CURL GetDynURL () const
void SetDynURL (const CURL &url)
const std::string & GetDynPath () const
void SetDynPath (const std::string &path)
std::string GetBlurayPath () const
void Reset ()
reset class to it's default values as per construction. Free's all allocated memory.
CFileItem & operator= (const CFileItem &item)
void Serialize (CVariant &value) const override
void ToSortable (SortItem &sortable, Field field) const override
void ToSortable (SortItem &sortable, const Fields &fields) const
bool IsFileItem () const override
bool Exists (bool bUseCache=true) const
bool IsPicture () const
Check whether an item is a picture item. Note that this returns true for anything with a picture info tag, so that may include eg. folders.
bool IsDeleted () const
Check whether an item is 'deleted' (for example, a trashed pvr recording).
bool IsGame () const
bool IsLibraryFolder () const
bool IsPythonScript () const
bool IsPlugin () const
bool IsScript () const
bool IsAddonsPath () const
bool IsSourcesPath () const
bool IsNFO () const
bool IsDiscImage () const
bool IsOpticalMediaFile () const
bool IsBluray () const
bool IsRAR () const
bool IsAPK () const
bool IsZIP () const
bool IsCBZ () const
bool IsCBR () const
bool IsISO9660 () const
bool IsDVD () const
bool IsOnDVD () const
bool IsHD () const
bool IsNfs () const
bool IsSmb () const
bool IsURL () const
bool IsStack () const
bool IsFavourite () const
bool IsMultiPath () const
bool IsEPG () const
bool IsPVRChannel () const
bool IsPVRChannelGroup () const
bool IsPVRRecording () const
bool IsUsablePVRRecording () const
bool IsDeletedPVRRecording () const
bool IsInProgressPVRRecording () const
bool IsPVRTimer () const
bool IsPVRProvider () const
bool IsType (const char *ext) const
bool IsVirtualDirectoryRoot () const
bool IsReadOnly () const
bool CanQueue () const
void SetCanQueue (bool bYesNo)
bool IsParentFolder () const
bool IsFileFolder (EFileFolderType types=EFILEFOLDER_MASK_ALL) const
bool IsRemovable () const
bool IsPVR () const
bool IsLiveTV () const
bool IsRSS () const
bool IsAndroidApp () const
bool HasVideoVersions () const
bool HasVideoExtras () const
void RemoveExtension ()
void CleanString ()
void SetFileSizeLabel ()
void SetLabel (const std::string &strLabel) override
VideoDbContentType GetVideoContentType () const
bool IsLabelPreformatted () const
void SetLabelPreformatted (bool bYesNo)
bool SortsOnTop () const
bool SortsOnBottom () const
void SetSpecialSort (SortSpecial sort)
bool HasMusicInfoTag () const
MUSIC_INFO::CMusicInfoTag * GetMusicInfoTag ()
const MUSIC_INFO::CMusicInfoTag * GetMusicInfoTag () const
bool HasVideoInfoTag () const
CVideoInfoTag * GetVideoInfoTag ()
const CVideoInfoTag * GetVideoInfoTag () const
bool HasEPGInfoTag () const
const std::shared_ptr< PVR::CPVREpgInfoTag > GetEPGInfoTag () const
bool HasEPGSearchFilter () const
const std::shared_ptr< PVR::CPVREpgSearchFilter > GetEPGSearchFilter () const
bool HasPVRChannelGroupMemberInfoTag () const
const std::shared_ptr< PVR::CPVRChannelGroupMember > GetPVRChannelGroupMemberInfoTag () const
bool HasPVRChannelInfoTag () const
const std::shared_ptr< PVR::CPVRChannel > GetPVRChannelInfoTag () const
bool HasPVRRecordingInfoTag () const
const std::shared_ptr< PVR::CPVRRecording > GetPVRRecordingInfoTag () const
bool HasPVRTimerInfoTag () const
const std::shared_ptr< PVR::CPVRTimerInfoTag > GetPVRTimerInfoTag () const
bool HasPVRProviderInfoTag () const
const std::shared_ptr< PVR::CPVRProvider > GetPVRProviderInfoTag () const
CFileItem GetItemToPlay () const
return the item to play. will be almost 'this', but can be different (e.g. "Play recording" from PVR EPG grid window)
bool IsResumePointSet () const
Test if this item has a valid resume point set.
double GetCurrentResumeTime () const
Return the current resume time.
bool GetCurrentResumeTimeAndPartNumber (int64_t &startOffset, int &partNumber) const
Return the current resume time and part.
bool IsResumable () const
Test if this item type can be resumed.
int64_t GetStartOffset () const
Get the offset where start the playback.
void SetStartOffset (const int64_t offset)
Set the offset where start the playback.
int64_t GetEndOffset () const
Get the end offset.
void SetEndOffset (const int64_t offset)
Set the end offset.
bool HasPictureInfoTag () const
const CPictureInfoTag * GetPictureInfoTag () const
bool HasAddonInfo () const
const std::shared_ptr< const ADDON::IAddon > GetAddonInfo () const
bool HasGameInfoTag () const
KODI::GAME::CGameInfoTag * GetGameInfoTag ()
const KODI::GAME::CGameInfoTag * GetGameInfoTag () const
CPictureInfoTag * GetPictureInfoTag ()
std::string FindLocalArt (const std::string &artFile, bool useFolder) const
Assemble the filename of a particular piece of local artwork for an item, and check for file existence.
bool SkipLocalArt () const
Whether or not to skip searching for local art.
std::string GetThumbHideIfUnwatched (const CFileItem *item) const
Get the thumb for the item, but hide it to prevent spoilers if the user has set 'Show information for unwatched items' appropriately.
std::string GetMovieName (bool bUseFolderNames=false) const
std::string GetBaseMoviePath (bool useFolderNames) const
Find the base movie path (i.e. the item the user expects us to use to lookup the movie) For folder items, with "use foldernames for lookups" it returns the folder. Regardless of settings, for VIDEO_TS/BDMV it returns the parent of the VIDEO_TS/BDMV folder (if present)
std::string GetUserMusicThumb (bool alwaysCheckRemote=false, bool fallbackToFolder=false) const
std::string GetLocalMetadataPath () const
Get the path where we expect local metadata to reside. For a folder, this is just the existing path (eg tvshow folder) For a file, this is the parent path, with exceptions made for VIDEO_TS and BDMV files.
bool LoadMusicTag ()
bool LoadGameTag ()
bool LoadDetails ()
Load detailed data for an item constructed with only a path and a folder flag Fills item's video info tag, sets item properties.
const std::string & GetMimeType () const
void SetMimeType (const std::string &mimetype)
void FillInMimeType (bool lookup=true)
Resolve the MIME type based on file extension or a web lookup If m_mimetype is already set (non-empty), this function has no effect. For http:// and shout:// streams, this will query the stream (blocking operation). Set lookup=false to skip any internet lookups and always return immediately.
bool ContentLookup ()
Some sources do not support HTTP HEAD request to determine i.e. mime type.
void SetMimeTypeForInternetFile ()
(Re)set the mime-type for internet files if allowed (m_doContentLookup) Some sources do not support HTTP HEAD request to determine i.e. mime type
void SetContentLookup (bool enable)
Lookup via HTTP HEAD request might not be needed, use this setter to disable ContentLookup.
void SetExtraInfo (const std::string &info)
const std::string & GetExtraInfo () const
void UpdateInfo (const CFileItem &item, bool replaceLabels=true)
Update an item with information from another item We take metadata information from the given item and supplement the current item with that info. If tags exist in the new item we use the entire tag information. Properties are appended, and labels, thumbnail and icon are updated if non-empty in the given item.
void MergeInfo (const CFileItem &item)
Merge an item with information from another item We take metadata/art information from the given item and supplement the current item with that info. If tags exist in the new item we only merge the missing tag information. Properties are appended, and labels are updated if non-empty in the given item.
bool IsSamePath (const CFileItem *item) const
bool IsAlbum () const
void SetFromVideoInfoTag (const CVideoInfoTag &video)
Sets details using the information from the CVideoInfoTag object Sets the videoinfotag and uses its information to set the label and path.
void SetFromMusicInfoTag (const MUSIC_INFO::CMusicInfoTag &music)
Sets details using the information from the CMusicInfoTag object Sets the musicinfotag and uses its information to set the label and path.
void SetFromAlbum (const CAlbum &album)
Sets details using the information from the CAlbum object Sets the album in the music info tag and uses its information to set the label and album-specific properties.
void SetFromSong (const CSong &song)
Sets details using the information from the CSong object Sets the song in the music info tag and uses its information to set the label, path, song-specific properties and artwork.
void SetCueDocument (const CCueDocumentPtr &cuePtr)
void LoadEmbeddedCue ()
bool HasCueDocument () const
bool LoadTracksFromCueDocument (CFileItemList &scannedItems)
Public Member Functions inherited from CGUIListItem
CGUIListItem (void)
CGUIListItem (const CGUIListItem &item)
CGUIListItem (const std::string &strLabel)
virtual ~CGUIListItem (void)
CGUIListItem & operator= (const CGUIListItem &item)
const std::string & GetLabel () const
void SetLabel2 (const std::string &strLabel)
const std::string & GetLabel2 () const
void SetOverlayImage (GUIIconOverlay icon)
std::string GetOverlayImage () const
void SetArt (const std::string &type, const std::string &url)
Set a particular art type for an item.
void SetArt (const ArtMap &art)
set artwork for an item
void AppendArt (const ArtMap &art, const std::string &prefix="")
append artwork to an item
void SetArtFallback (const std::string &from, const std::string &to)
set a fallback image for art
void ClearArt ()
clear art on an item
std::string GetArt (const std::string &type) const
Get a particular art type for an item.
const ArtMap & GetArt () const
get artwork for an item Retrieves artwork in a type:url map
bool HasArt (const std::string &type) const
Check whether an item has a particular piece of art Equivalent to !GetArt(type).empty()
void SetSortLabel (const std::string &label)
void SetSortLabel (const std::wstring &label)
const std::wstring & GetSortLabel () const
void Select (bool bOnOff)
bool IsSelected () const
bool HasOverlay () const
void SetLayout (std::unique_ptr< CGUIListItemLayout > layout)
CGUIListItemLayout * GetLayout ()
void SetFocusedLayout (std::unique_ptr< CGUIListItemLayout > layout)
CGUIListItemLayout * GetFocusedLayout ()
void FreeIcons ()
void FreeMemory (bool immediately=false)
void SetInvalid ()
void SetProperty (const std::string &strKey, const CVariant &value)
void IncrementProperty (const std::string &strKey, int nVal)
void IncrementProperty (const std::string &strKey, int64_t nVal)
void IncrementProperty (const std::string &strKey, double dVal)
void ClearProperties ()
void AppendProperties (const CGUIListItem &item)
Append the properties of one CGUIListItem to another. Any existing properties in the current item will be overridden if they are set in the passed in item.
void Archive (CArchive &ar)
void Serialize (CVariant &value)
bool HasProperty (const std::string &strKey) const
bool HasProperties () const
void ClearProperty (const std::string &strKey)
const CVariant & GetProperty (const std::string &strKey) const
void SetCurrentItem (unsigned int position)
Set the current item number within it's container Our container classes will set this member with the items position in the container starting at 1.
unsigned int GetCurrentItem () const
Get the current item number within it's container Retrieve the items position in a container, this is useful to show for example numbering in front of entities in an arbitrary list of entities, like songs of a playlist.
Private Member Functions
void Sort (FILEITEMLISTCOMPARISONFUNC func)
void FillSortFields (FILEITEMFILLFUNC func)
std::string GetDiscFileCache (int windowID) const
void StackFiles ()
stack files in a CFileItemList
void StackFolders ()
stack folders in a CFileItemList
Private Attributes
VECFILEITEMS m_items
MAPFILEITEMS m_map
bool m_ignoreURLOptions = false
bool m_fastLookup = false
SortDescription m_sortDescription
bool m_sortIgnoreFolders = false
CACHE_TYPE m_cacheToDisc = CACHE_IF_SLOW
bool m_replaceListing = false
std::string m_content
std::vector< GUIViewSortDetails > m_sortDetails
CCriticalSection m_lock
Additional Inherited Members
Public Attributes inherited from CFileItem
bool m_bIsShareOrDrive
is this a root share/drive
int m_iDriveType
If m_bIsShareOrDrive is true, use to get the share type. Types see: CMediaSource::m_iDriveType.
CDateTime m_dateTime
file creation date & time
int64_t m_dwSize
file size (0 for folders)
std::string m_strDVDLabel
std::string m_strTitle
int m_iprogramCount
int m_idepth
int m_lStartPartNumber
LockType m_iLockMode
std::string m_strLockCode
int m_iHasLock
int m_iBadPwdCount
Public Attributes inherited from CGUIListItem
bool m_bIsFolder
is item a folder or a file
Protected Types inherited from CGUIListItem
typedef std::map< std::string, CVariant, icompare > PropertyMap
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Protected Member Functions inherited from ISortable
~ISortable ()=default
Protected Attributes inherited from CGUIListItem
std::string m_strLabel2
GUIIconOverlay m_overlayIcon
std::unique_ptr< CGUIListItemLayout > m_layout
std::unique_ptr< CGUIListItemLayout > m_focusedLayout
bool m_bSelected
unsigned int m_currentItem
PropertyMap m_mapProperties
Detailed Description
Represents a list of files.
See also
CFileItemList, CFileItem
Member Enumeration Documentation
CACHE_TYPE
enum CFileItemList::CACHE_TYPE
Enumerator
CACHE_NEVER
CACHE_IF_SLOW
CACHE_ALWAYS
Constructor & Destructor Documentation
CFileItemList() [1/2]
CFileItemList::CFileItemList ()
CFileItemList() [2/2]
CFileItemList::CFileItemList (const std::string & strPath) explicit
~CFileItemList()
CFileItemList::~CFileItemList () override
References Clear().
Member Function Documentation
Add() [1/2]
void CFileItemList::Add (CFileItem && item)
References CURL::GetWithoutOptions(), m_fastLookup, m_ignoreURLOptions, m_items, m_lock, and m_map.
Add() [2/2]
void CFileItemList::Add (CFileItemPtr item)
References CURL::GetWithoutOptions(), m_fastLookup, m_ignoreURLOptions, m_items, m_lock, and m_map.
Referenced by XBMCAddon::xbmc::PlayList::add(), XBMCAddon::xbmcplugin::addDirectoryItems(), ADDON::CGUIAddonWindow::AddItem(), CGUIDialogColorPicker::AddItem(), CFavouritesService::AddOrRemove(), CMusicFileItemListModifier::AddQueuingFolder(), CVideoFileItemListModifier::AddQueuingFolder(), Append(), Archive(), FAVOURITES_UTILS::ChooseAndSetNewThumbnail(), PVR::CPVRGUIActionsEPG::ChooseIconForSavedSearch(), XBMCAddon::xbmcgui::Dialog::colorpicker(), Copy(), CFileUtils::DeleteItem(), XFILE::Directorize(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording::DoRun(), KODI::VIDEO::CVideoInfoScanner::DoScan(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DownloadPackage(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), MUSIC_UTILS::FillArtTypesList(), JSONRPC::CPVROperations::FillChannelGroupDetails(), JSONRPC::CAudioLibrary::FillFileItem(), JSONRPC::CAudioLibrary::FillFileItemList(), JSONRPC::CFileItemHandler::FillFileItemList(), JSONRPC::CFileOperations::FillFileItemList(), JSONRPC::CVideoLibrary::FillFileItemList(), CGUIDialogSubtitles::FillServices(), XFILE::CAddonsDirectory::GenerateAddonListing(), XFILE::GenerateGameListing(), XFILE::GenerateMainCategoryListing(), XFILE::GenerateTypeListing(), CGUIMediaWindow::GetAdvanceFilteredItems(), JSONRPC::CAudioLibrary::GetAlbumDetails(), CMusicDatabase::GetAlbumsByWhere(), CFavouritesService::GetAll(), CMusicDatabase::GetArtistDiscography(), CMusicDatabase::GetArtistsByWhere(), CVideoDatabase::GetAssetsForVideo(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), JSONRPC::CPVROperations::GetBroadcasts(), PVR::CPVRGUIDirectory::GetChannelGroupsDirectory(), JSONRPC::CPVROperations::GetChannels(), PVR::CPVRGUIDirectory::GetChannelsDirectory(), CMusicDatabase::GetCommonNav(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeOverview::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeTop100::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMusicVideosOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview::GetContent(), PVR::CPVRGUIDirectory::GetDirectory(), XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CAudioBookFileDirectory::GetDirectory(), XFILE::CCDDADirectory::GetDirectory(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CEventsDirectory::GetDirectory(), XFILE::CFTPDirectory::GetDirectory(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CISO9660Directory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMusicFileDirectory::GetDirectory(), XFILE::CNFSDirectory::GetDirectory(), XFILE::CPlaylistDirectory::GetDirectory(), XFILE::CPlaylistFileDirectory::GetDirectory(), XFILE::CRSSDirectory::GetDirectory(), XFILE::CStackDirectory::GetDirectory(), XFILE::CUDFDirectory::GetDirectory(), XFILE::CUPnPDirectory::GetDirectory(), XFILE::CZeroconfDirectory::GetDirectory(), XFILE::CAndroidAppDirectory::GetDirectory(), XFILE::CAPKDirectory::GetDirectory(), XFILE::CTVOSDirectory::GetDirectory(), XFILE::CPosixDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), XFILE::CWinLibraryDirectory::GetDirectory(), XFILE::CWin32Directory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), JSONRPC::CFileOperations::GetDirectory(), CGUIWindowEventLog::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowMusicPlaylistEditor::GetDirectory(), CGUIWindowVideoBase::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), PERIPHERALS::CPeripheralAddon::GetDirectory(), PERIPHERALS::CPeripheralBus::GetDirectory(), XFILE::CSourcesDirectory::GetDirectory(), XFILE::CNFSDirectory::GetDirectoryFromExportList(), GetDirectoryFromTxtRecords(), CMusicDatabase::GetDiscsByWhere(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CGUIMediaWindow::GetFilteredItems(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetGenresNav(), anonymous_namespace{PVRGUIDirectory.cpp}::GetGetRecordingsSubDirectories(), CGUIControlListSetting::GetIntegerItems(), JSONRPC::CPlayerOperations::GetItem(), KODI::GAME::CDialogGameStretchMode::GetItems(), KODI::GAME::CDialogGameVideoFilter::GetItems(), KODI::GAME::CDialogGameVideoRotation::GetItems(), KODI::GAME::CDialogInGameSaves::GetItems(), CGUIDialogVideoInfo::GetItemsForTag(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CGUIDialogVideoInfo::GetMoviesForSet(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByArtist(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), JSONRPC::CProfilesOperations::GetProfiles(), PVR::CPVRGUIDirectory::GetProvidersDirectory(), JSONRPC::CAudioLibrary::GetRecentlyAddedAlbums(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), JSONRPC::CAudioLibrary::GetRecentlyPlayedAlbums(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), JSONRPC::CPVROperations::GetRecordings(), PVR::CPVRGUIDirectory::GetRecordingsDirectory(), CUtil::GetRecursiveDirsListing(), KODI::VIDEO::CVideoInfoScanner::GetRecursiveFastHash(), CUtil::GetRecursiveListing(), CMusicDatabase::GetRolesNav(), XFILE::CBlurayDirectory::GetRoot(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), JSONRPC::CFileOperations::GetRootDirectory(), CVideoDatabase::GetSameVideoItems(), PVR::CPVRGUIDirectory::GetSavedSearchesDirectory(), PVR::CPVRGUIDirectory::GetSavedSearchResults(), XFILE::CAddonsDirectory::GetScriptsAndPlugins(), CVideoDatabase::GetSeasonsByWhere(), XFILE::CNFSDirectory::GetServerList(), WSDiscovery::CWSDiscoveryPosix::GetServerList(), CGUIWindowSlideShow::GetSlideShowContents(), JSONRPC::CAudioLibrary::GetSongDetails(), CMusicDatabase::GetSongsByWhere(), CGUIWindowMusicNav::GetSongsFromPlayList(), CMusicDatabase::GetSongsFullByWhere(), CMusicDatabase::GetSources(), CMusicDatabase::GetSourcesNav(), CGUIControlListSetting::GetStringItems(), JSONRPC::CPVROperations::GetTimers(), anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersRootDirectory(), anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersSubDirectory(), XFILE::CBlurayDirectory::GetTitles(), CMusicDatabase::GetTop100(), CMusicDatabase::GetTop100AlbumSongs(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), CVideoDatabase::GetVideoVersions(), CVideoDatabase::GetVideoVersionsNav(), CVideoDatabase::GetVideoVersionTypes(), CMusicDatabase::GetYearsNav(), CVideoDatabase::GetYearsNav(), GroupUtils::Group(), KODI::GAME::CDialogGameVideoFilter::InitVideoFilters(), CGUIDialogVideoInfo::LinkMovieToTvShow(), MUSIC_INFO::CMusicInfoLoader::LoadCache(), CGUIDialogColorPicker::LoadColors(), anonymous_namespace{FavouritesService.cpp}::LoadFromFile(), CGUIWindowSettingsProfile::LoadList(), CCueDocument::LoadTracks(), localGetNetworkResources(), localGetServers(), localGetShares(), CGUIDialogVideoInfo::ManageVideoItemArtwork(), FAVOURITES_UTILS::MoveItem(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), UPNP::CUPnPServer::OnBrowseDirectChildren(), PVR::CGUIDialogPVRChannelManager::OnClickButtonChannelLogo(), CGUIDialogContextMenu::OnContextButton(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSongInfo::OnGetArt(), CGUIDialogMediaSource::OnPathAdd(), PVR::CGUIWindowPVRRecordingsBase::OnPrepareFileItems(), PVR::CGUIWindowPVRSearchBase::OnPrepareFileItems(), CGUIDialogVideoBookmarks::OnRefreshList(), CGUIDialogProfileSettings::OnSettingAction(), KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream(), XFILE::OutdatedAddons(), UPNP::CUPnPRenderer::PlayMedia(), XBMCAddon::xbmc::Player::playStream(), KODI::GAME::CDialogGameVideoFilter::PreInit(), KODI::GAME::CControllerInstaller::Process(), KODI::GAME::CControllerSelect::Process(), CAirPlayServer::CTCPClient::ProcessRequest(), ADDON::CAddonInstaller::PrunePackageCache(), XFILE::Repos(), XFILE::RootDirectory(), MUSIC_INFO::CMusicInfoScanner::ScanTags(), CMusicDatabase::SearchAlbums(), CMusicDatabase::SearchAlbumsByArtistName(), CMusicDatabase::SearchArtists(), CMusicDatabase::SearchSongs(), CGUIWindowAddonBrowser::SelectAddonID(), CFileOperationJob::SetFileOperation(), CGUIDialogVideoInfo::SetMovie(), CGUIDialogMediaSource::SetShare(), CGUIDialogFileBrowser::ShowAndGetFile(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), CGUIDialogFileBrowser::ShowAndGetImage(), CGUIDialogAddonSettings::ShowForMultipleInstances(), MUSIC_UTILS::ShowSelectArtTypeDialog(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), CGUIDialogSongInfo::Update(), PVR::CGUIDialogPVRChannelManager::Update(), PVR::CGUIDialogPVRGroupManager::Update(), CGUIWindowLoginScreen::Update(), CGUIDialogFileBrowser::Update(), CGUIMediaWindow::Update(), CGUIWindowFileManager::Update(), CGUIDialogSmartPlaylistEditor::UpdateButtons(), CGUIDialogAddonInfo::UpdateControls(), XFILE::UserInstalledAddons(), ADDON::VFSDirEntriesToCFileItemList(), CVideoLibraryMarkWatchedJob::Work(), CVideoLibraryRefreshingJob::Work(), and CVideoLibraryResetResumePointJob::Work().
AddFront()
void CFileItemList::AddFront (const CFileItemPtr & pItem, int itemPosition)
References CURL::GetWithoutOptions(), m_fastLookup, m_ignoreURLOptions, m_items, m_lock, and m_map.
Referenced by ADDON::CGUIAddonWindow::AddItem(), CMusicFileItemListModifier::AddQueuingFolder(), CGUIMediaWindow::GetDirectory(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CGUIDialogVideoInfo::GetSetForMovie(), FAVOURITES_UTILS::MoveItem(), CGUIMediaWindow::OnFilterItems(), KODI::GAME::CDialogInGameSaves::OnItemRefresh(), KODI::GAME::CDialogInGameSaves::OnNewSave(), PVR::CGUIWindowPVRTimersBase::OnPrepareFileItems(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), GUIFontManager::SettingOptionsFontsFiller(), CGUIDialogFileBrowser::Update(), and CGUIWindowFileManager::Update().
AddSortMethod() [1/3]
void CFileItemList::AddSortMethod (const SortDescription & sortDescription, int buttonLabel, const LABEL_MASKS & labelMasks)
References GUIViewSortDetails::m_buttonLabel, GUIViewSortDetails::m_labelMasks, GUIViewSortDetails::m_sortDescription, and m_sortDetails.
AddSortMethod() [2/3]
void CFileItemList::AddSortMethod (SortBy sortBy, int buttonLabel, const LABEL_MASKS & labelMasks, SortAttribute sortAttributes = SortAttributeNone)
References AddSortMethod().
Referenced by AddSortMethod(), AddSortMethod(), PVR::CPVRGUIDirectory::GetDirectory(), XFILE::CBlurayDirectory::GetDirectory(), XFILE::CRSSDirectory::GetDirectory(), and XFILE::CUPnPDirectory::GetDirectory().
AddSortMethod() [3/3]
void CFileItemList::AddSortMethod (SortBy sortBy, SortAttribute sortAttributes, int buttonLabel, const LABEL_MASKS & labelMasks)
References AddSortMethod(), SortDescription::sortAttributes, and SortDescription::sortBy.
AlwaysCache()
bool CFileItemList::AlwaysCache () const
References XFILE::CVideoDatabaseDirectory::CanCache(), XFILE::CMusicDatabaseDirectory::CanCache(), CFileItem::GetPath(), CFileItem::IsEPG(), and KODI::MUSIC::IsMusicDb().
Referenced by CGUIMediaWindow::OnClick().
Append()
void CFileItemList::Append (const CFileItemList & itemlist)
References Add(), m_lock, and Size().
Referenced by CGUIWindowVideoBase::AppendAndClearSearchItems(), CGUIWindowMusicPlaylistEditor::AppendToPlaylist(), Assign(), CGUIMediaWindow::GetAdvanceFilteredItems(), XFILE::CMultiPathDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), CGUIWindowEventLog::GetDirectory(), CVideoDatabase::GetEpisodesNav(), CGUIMediaWindow::GetFilteredItems(), CGUIWindowVideoBase::GetGroupedItems(), CUtil::GetItemsToScan(), KODI::ART::GetLocalFanart(), CVideoDatabase::GetSeasonsNav(), CVideoDatabase::GetSetsByWhere(), GroupUtils::GroupAndMix(), localGetShares(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIMediaWindow::OnFilterItems(), UPNP::CUPnPServer::OnSearchContainer(), CGUIWindowMusicBase::RetrieveMusicInfo(), CUtil::ScanForExternalSubtitles(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), CGUIDialogFileBrowser::ShowAndGetImage(), and CGUIWindowFileManager::Update().
Archive()
void CFileItemList::Archive (CArchive & ar) override virtual
Reimplemented from CFileItem.
References Add(), CFileItem::Archive(), Clear(), IsEmpty(), CArchive::IsStoring(), GUIViewSortDetails::m_buttonLabel, m_cacheToDisc, m_content, m_fastLookup, m_ignoreURLOptions, m_items, GUIViewSortDetails::m_labelMasks, m_lock, m_sortDescription, GUIViewSortDetails::m_sortDescription, m_sortDetails, m_sortIgnoreFolders, LABEL_MASKS::m_strLabel2File, LABEL_MASKS::m_strLabel2Folder, LABEL_MASKS::m_strLabelFile, LABEL_MASKS::m_strLabelFolder, SetFastLookup(), SetIgnoreURLOptions(), SortDescription::sortAttributes, SortDescription::sortBy, and SortDescription::sortOrder.
Assign()
void CFileItemList::Assign (const CFileItemList & itemlist, bool append = false)
References Append(), Clear(), CGUIListItem::GetLabel(), CFileItem::GetPath(), m_cacheToDisc, m_content, m_lock, CGUIListItem::m_mapProperties, m_replaceListing, m_sortDescription, m_sortDetails, CFileItem::SetLabel(), and CFileItem::SetPath().
Referenced by XFILE::CPluginDirectory::GetDirectory(), CGUIMediaWindow::GetDirectory(), PVR::CGUIWindowPVRGuideBase::GetDirectory(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), CGUIDialogSubtitles::OnSearchComplete(), CGUIDialogSubtitles::Process(), and CGUIMediaWindow::Update().
begin() [1/2]
VECFILEITEMS::iterator CFileItemList::begin () inline
References m_items.
Referenced by KODI::VIDEO::CVideoInfoScanner::DoScan(), and KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder().
begin() [2/2]
VECFILEITEMS::const_iterator CFileItemList::begin () const inline
References m_items.
CacheToDiscAlways()
bool CFileItemList::CacheToDiscAlways () const inline
References CACHE_ALWAYS, and m_cacheToDisc.
Referenced by UPNP::CUPnPServer::OnBrowseDirectChildren(), and CGUIMediaWindow::OnCacheFileItems().
CacheToDiscIfSlow()
bool CFileItemList::CacheToDiscIfSlow () const inline
References CACHE_IF_SLOW, and m_cacheToDisc.
Referenced by CGUIMediaWindow::GetDirectory(), and UPNP::CUPnPServer::OnBrowseDirectChildren().
cbegin()
VECFILEITEMS::const_iterator CFileItemList::cbegin () const inline
References m_items.
Referenced by CGUIDialogVideoManager::ChooseVideoAsset(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording::DoRun(), CONTEXTMENU::CFavouriteContextMenuAction::Execute(), KODI::GAME::CDialogInGameSaves::GetItems(), PVR::CGUIDialogPVRChannelManager::HasChangedItems(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadRecordingFileOrFolderItem(), KODI::GAME::CDialogInGameSaves::OnItemRefresh(), and CGUIWindowMusicBase::OnSelect().
cend()
VECFILEITEMS::const_iterator CFileItemList::cend () const inline
References m_items.
Referenced by CGUIDialogVideoManager::ChooseVideoAsset(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording::DoRun(), CONTEXTMENU::CFavouriteContextMenuAction::Execute(), KODI::GAME::CDialogInGameSaves::GetItems(), PVR::CGUIDialogPVRChannelManager::HasChangedItems(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadRecordingFileOrFolderItem(), KODI::GAME::CDialogInGameSaves::OnItemRefresh(), and CGUIWindowMusicBase::OnSelect().
Clear()
void CFileItemList::Clear ()
References CACHE_IF_SLOW, ClearItems(), m_cacheToDisc, m_content, m_lock, m_replaceListing, m_sortDescription, m_sortDetails, m_sortIgnoreFolders, SortAttributeNone, SortDescription::sortAttributes, SortDescription::sortBy, SortByNone, SortDescription::sortOrder, and SortOrderNone.
Referenced by CGUIWindowVideoBase::AppendAndClearSearchItems(), Archive(), Assign(), CGUIDialogSongInfo::CGUIDialogSongInfo(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), PVR::CGUIDialogPVRChannelManager::Clear(), PVR::CGUIDialogPVRGroupManager::Clear(), CGUIDialogVideoBookmarks::Clear(), CGUIDialogVideoInfo::ClearCastList(), CGUIDialogFileBrowser::ClearFileItems(), CGUIMediaWindow::ClearFileItems(), CGUIWindowFileManager::ClearFileItems(), CGUIWindowSettingsProfile::ClearListItems(), CGUIWindowMusicPlaylistEditor::ClearPlaylist(), CGUIDialogSubtitles::ClearServices(), CGUIDialogSubtitles::ClearSubtitles(), dll_closedir(), dll_findclose(), dll_findfirst64i32(), dll_findnext64i32(), dll_opendir(), KODI::VIDEO::CVideoInfoScanner::DoScan(), CVideoDatabase::DumpToDummyFiles(), MUSIC_UTILS::FillArtTypesList(), CFavouritesService::GetAll(), CGUIDialogVideoManagerVersions::GetAllOtherMovies(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetChilds(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetChilds(), CGetDirectory::GetDirectory(), XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CFavouritesDirectory::GetDirectory(), XFILE::CStackDirectory::GetDirectory(), XFILE::CWinLibraryDirectory::GetDirectory(), XFILE::CVirtualDirectory::GetDirectory(), CGUIWindowMusicPlaylistEditor::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CVideoDatabase::GetMusicVideosByArtist(), CGUIDialogVideoManagerVersions::GetSimilarMovies(), XFILE::CDirectoryCache::InitCache(), KODI::GAME::CDialogInGameSaves::InitSavedGames(), CGUIDialogColorPicker::OnBack(), CGUIDialogSmartPlaylistEditor::OnDeinitWindow(), CGUIWindowVideoBase::OnItemInfo(), MUSIC_INFO::CMusicInfoLoader::OnLoaderFinish(), CPictureInfoLoader::OnLoaderFinish(), CGUIDialogColorPicker::OnMessage(), CGUIDialogSongInfo::OnMessage(), CGUIWindowLoginScreen::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnPrepareFileItems(), CGUIDialogVideoBookmarks::OnRefreshList(), UPNP::CUPnPServer::OnSearchContainer(), CGUIDialogVideoBookmarks::OnWindowLoaded(), CGUIDialogVideoBookmarks::OnWindowUnload(), KODI::GAME::CDialogGameVideoFilter::PostExit(), KODI::GAME::CDialogInGameSaves::PostExit(), KODI::GAME::CDialogGameVideoFilter::PreInit(), ADDON::CAddonInstaller::PrunePackageCache(), CFavouritesService::ReInit(), CGUIDialogColorPicker::Reset(), CFavouritesService::Save(), CFileOperationJob::SetFileOperation(), CGUIDialogColorPicker::SetItems(), CGUIDialogMediaSource::SetShare(), CGUIDialogMediaSource::ShowAndAddMediaSource(), CGUIDialogMediaSource::ShowAndEditMediaSource(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetImage(), CGUIDialogSimpleMenu::ShowPlaySelection(), TEST(), CFilesystemInstaller::UnpackArchive(), CGUIWindowLoginScreen::Update(), CGUIDialogSmartPlaylistEditor::UpdateButtons(), PERIPHERALS::CGUIDialogPeripherals::UpdatePeripheralsSync(), and ~CFileItemList().
ClearItems()
void CFileItemList::ClearItems ()
References CGUIListItem::FreeMemory(), m_items, m_lock, and m_map.
Referenced by Clear(), XFILE::CAddonsDirectory::GenerateAddonListing(), CGUIMediaWindow::GetAdvanceFilteredItems(), XFILE::CAddonsDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), CGUIWindowEventLog::GetDirectory(), CGUIMediaWindow::GetFilteredItems(), CGUIWindowVideoBase::GetGroupedItems(), CVideoDatabase::GetSetsByWhere(), CGUIMediaWindow::OnFilterItems(), and XFILE::UserInstalledAddons().
ClearSortState()
void CFileItemList::ClearSortState ()
References m_sortDescription, SortAttributeNone, SortDescription::sortAttributes, SortDescription::sortBy, SortByNone, SortDescription::sortOrder, and SortOrderNone.
Referenced by CGUIWindowVideoNav::ApplyWatchedFilter(), CGUIMediaWindow::FormatItemLabels(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), and CGUIMediaWindow::OnFilterItems().
Contains()
bool CFileItemList::Contains (const std::string & fileName) const
References m_fastLookup, m_ignoreURLOptions, m_items, m_lock, and m_map.
Referenced by XFILE::Directorize(), XFILE::CAPKDirectory::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowVideoBase::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), JSONRPC::CFileOperations::GetFileDetails(), anonymous_namespace{PVRGUIDirectory.cpp}::GetGetRecordingsSubDirectories(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetYearsNav(), anonymous_namespace{FavouritesService.cpp}::LoadFromFile(), GUIFontManager::LoadUserFonts(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), and CGUIWindowAddonBrowser::SelectAddonID().
Copy()
bool CFileItemList::Copy (const CFileItemList & item, bool copyItems = true)
References Add(), CFileItem::CFileItem(), m_cacheToDisc, m_content, CGUIListItem::m_mapProperties, m_replaceListing, m_sortDescription, m_sortDetails, m_sortIgnoreFolders, and Size().
Referenced by XFILE::CPluginDirectory::AddItems(), CFavouritesService::GetAll(), CGetDirectory::GetDirectory(), XFILE::CDirectoryCache::GetDirectory(), CGUIMediaWindow::OnFilterItems(), CFavouritesService::Save(), CGUIDialogSongInfo::SetArtTypeList(), CGUIDialogColorPicker::SetItems(), and CGUIDialogFileBrowser::Update().
end() [1/2]
VECFILEITEMS::iterator CFileItemList::end () inline
References m_items.
Referenced by KODI::VIDEO::CVideoInfoScanner::DoScan(), and KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder().
end() [2/2]
VECFILEITEMS::const_iterator CFileItemList::end () const inline
References m_items.
erase()
VECFILEITEMS::iterator CFileItemList::erase (VECFILEITEMS::iterator first, VECFILEITEMS::iterator last)
References m_items, and m_lock.
Referenced by KODI::VIDEO::CVideoInfoScanner::DoScan(), and KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder().
FillInDefaultIcons()
void CFileItemList::FillInDefaultIcons ()
References KODI::ART::FillInDefaultIcon(), m_items, and m_lock.
Referenced by CGUIDialogFileBrowser::Update(), CGUIMediaWindow::Update(), and CGUIWindowFileManager::Update().
FillSortFields()
void CFileItemList::FillSortFields (FILEITEMFILLFUNC func) private
References m_items, and m_lock.
FilterCueItems()
void CFileItemList::FilterCueItems ()
References Contains, XFILE::CFile::Exists(), CServiceBroker::GetFileExtensionProvider(), KODI::MUSIC::IsAudio(), KODI::MUSIC::IsCUESheet(), KODI::PLAYLIST::IsPlayList(), m_items, m_lock, URIUtils::RemoveExtension(), and URIUtils::ReplaceExtension().
Referenced by MUSIC_INFO::CMusicInfoScanner::DoScan(), CGUIWindowMusicBase::GetDirectory(), and CGUIWindowMusicPlaylistEditor::GetDirectory().
Get() [1/2]
CFileItemPtr CFileItemList::Get (const std::string & strPath) const
References m_fastLookup, m_ignoreURLOptions, m_items, m_lock, and m_map.
Get() [2/2]
CFileItemPtr CFileItemList::Get (int iItem) const
References m_items, and m_lock.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonChannelGroups(), PVR::CGUIDialogPVRGroupManager::ActionButtonDeleteGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonGroupMembers(), PVR::CGUIDialogPVRGroupManager::ActionButtonRenameGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonUngroupedChannels(), CGUIWindowVideoNav::ApplyWatchedFilter(), CGUIMediaWindow::GetAdvanceFilteredItems(), CGUIWindowEventLog::GetContextButtons(), KODI::GAME::CGUIWindowGames::GetContextButtons(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowMusicPlayList::GetContextButtons(), CGUIWindowPictures::GetContextButtons(), CGUIWindowPrograms::GetContextButtons(), PVR::CGUIWindowPVRRecordingsBase::GetContextButtons(), CGUIWindowVideoBase::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), PVR::CGUIDialogPVRChannelManager::GetCurrentListItem(), CGUIMediaWindow::GetCurrentListItem(), CGUIWindowLoginScreen::GetCurrentListItem(), CGUIWindowEventLog::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), JSONRPC::CFavouritesOperations::GetFavourites(), JSONRPC::CFileOperations::GetFileDetails(), CGUIMediaWindow::GetFilteredItems(), PVR::CGUIWindowPVRRecordingsBase::GetFilteredItems(), CGUIWindowVideoNav::GetFirstUnwatchedItemIndex(), anonymous_namespace{PVRGUIDirectory.cpp}::GetGetRecordingsSubDirectories(), CGUIDialogMediaFilter::GetItems(), CGUIDialogVideoInfo::GetItemsForTag(), ADDON::CGUIAddonWindow::GetListItem(), CGUIDialogVideoInfo::GetMoviesForSet(), CUtil::GetNextFilename(), CGUIDialogMediaSource::GetPaths(), CVideoDatabase::GetPlayCounts(), CVideoDatabase::GetSeasonInfo(), CGUIDialogColorPicker::GetSelectedItem(), CGUIViewControl::GetSelectedItemPath(), CGUIDialogSubtitles::GetService(), CGUIDialogVideoInfo::GetSetForMovie(), CGUIDialogVideoBookmarks::GotoBookmark(), GroupUtils::Group(), JSONRPC::CFileItemHandler::HandleFileItemList(), CGUIDialogMediaSource::HighlightItem(), GUIFontManager::LoadUserFonts(), CGUIWindowVideoBase::LoadVideoInfo(), XFILE::CMultiPathDirectory::MergeItems(), CGUIWindowMusicBase::OnAction(), CGUIWindowMusicNav::OnAction(), PVR::CGUIWindowPVRRecordingsBase::OnAction(), CGUIWindowVideoNav::OnAction(), CGUIWindowFileManager::OnAction(), PVR::CGUIDialogPVRChannelManager::OnActionMove(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIMediaWindow::OnClick(), CGUIWindowAddonBrowser::OnClick(), KODI::GAME::CGUIWindowGames::OnClick(), CGUIWindowMusicNav::OnClick(), CGUIWindowMusicPlaylistEditor::OnClick(), CGUIWindowPictures::OnClick(), CGUIWindowVideoNav::OnClick(), CGUIWindowFileManager::OnClick(), PVR::CGUIDialogPVRChannelManager::OnClickButtonChannelLogo(), PVR::CGUIDialogPVRChannelManager::OnClickButtonEditName(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRadioActive(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRadioParentalLocked(), PVR::CGUIDialogPVRChannelManager::OnClickButtonUseEPG(), PVR::CGUIDialogPVRChannelManager::OnClickListChannels(), KODI::GAME::CGUIWindowGames::OnClickMsg(), PVR::CGUIDialogPVRChannelManager::OnContextButton(), CGUIWindowEventLog::OnContextButton(), KODI::GAME::CGUIWindowGames::OnContextButton(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowPictures::OnContextButton(), CGUIWindowPrograms::OnContextButton(), PVR::CGUIWindowPVRChannelsBase::OnContextButton(), PVR::CGUIWindowPVRRecordingsBase::OnContextButton(), PVR::CGUIWindowPVRSearchBase::OnContextButton(), CGUIWindowVideoBase::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), PVR::CGUIDialogPVRGroupManager::OnContextButton(), CGUIMediaWindow::OnDeleteItem(), CGUIWindowVideoBase::OnDeleteItem(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIWindowEventLog::OnEventRemoved(), CGUIWindowVideoBase::OnFileAction(), CGUIMediaWindow::OnFilterItems(), PVR::CGUIDialogPVRChannelManager::OnInitWindow(), CGUIWindowMusicBase::OnItemInfo(), CGUIWindowPrograms::OnItemInfo(), CGUIWindowPictures::OnItemInfo(), CGUIWindowVideoBase::OnItemInfo(), KODI::GAME::CGUIWindowGames::OnItemInfo(), CGUIWindowFileManager::OnMark(), CGUIWindowAddonBrowser::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIWindowEventLog::OnMessage(), CGUIBaseContainer::OnMessage(), CGUIWindowMusicNav::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIDialogSubtitles::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowFileManager::OnNewFolder(), CGUIDialogMediaSource::OnPath(), CGUIDialogMediaSource::OnPathBrowse(), CGUIWindowPrograms::OnPlayMedia(), CGUIMediaWindow::OnPlayMedia(), CGUIWindowMusicBase::OnPlayMedia(), CGUIWindowMusicPlayList::OnPlayMedia(), CGUIWindowPictures::OnPlayMedia(), CGUIWindowVideoBase::OnPlayMedia(), CGUIWindowVideoPlaylist::OnPlayMedia(), CGUIWindowVideoBase::OnPlayOrResumeItem(), CGUIDialogFileBrowser::OnPopupMenu(), PVR::CGUIDialogPVRChannelManager::OnPopupMenu(), CGUIMediaWindow::OnPopupMenu(), CGUIWindowLoginScreen::OnPopupMenu(), CGUIWindowMusicNav::OnPopupMenu(), PVR::CGUIWindowPVRRecordingsBase::OnPopupMenu(), CGUIWindowVideoNav::OnPopupMenu(), CGUIWindowFileManager::OnPopupMenu(), CGUIDialogSmartPlaylistEditor::OnPopupMenu(), PVR::CGUIDialogPVRGroupManager::OnPopupMenu(), CGUIWindowMusicBase::OnQueueItem(), CGUIWindowVideoBase::OnQueueItem(), CGUIWindowMusicPlaylistEditor::OnQueueItem(), CGUIWindowMusicBase::OnRemoveSource(), CGUIWindowFileManager::OnRename(), CGUIMediaWindow::OnRenameItem(), CGUIWindowMusicBase::OnRipTrack(), CGUIWindowMusicBase::OnScan(), CGUIDialogSubtitles::OnSearchComplete(), CGUIWindowVideoBase::OnSearchItemFound(), CGUIWindowMusicBase::OnSelect(), CGUIWindowVideoBase::OnSelect(), CGUIWindowEventLog::OnSelect(), CGUIWindowFileManager::OnSelectAll(), CGUIWindowFileManager::OnSort(), CGUIDialogSubtitles::OnSubtitleServiceContextMenu(), JSONRPC::CPlayerOperations::Open(), operator[](), operator[](), operator[](), operator[](), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::PlayItem(), CGUIWindowMusicNav::PlayItem(), CGUIWindowMusicPlaylistEditor::PlayItem(), ADDON::Interface_Filesystem::remove_directory(), CGUIMediaWindow::RestoreSelectedItemFromHistory(), PVR::CGUIDialogPVRChannelManager::SaveList(), CGUIWindowMusicPlayList::SavePlayList(), CGUIMediaWindow::SaveSelectedItemInHistory(), CGUIWindowAddonBrowser::SelectAddonID(), CGUIWindowFileManager::SelectItem(), PVR::CGUIDialogPVRChannelManager::SetData(), CGUIDialogSubtitles::SetService(), CTVOSTopShelf::SetTopShelfItems(), CGUIDialogMediaSource::ShowAndAddMediaSource(), PVR::CGUIWindowPVRChannelsBase::ShowChannelManager(), CGUIWindowPictures::ShowPicture(), StackFiles(), StackFolders(), TEST_F(), TEST_F(), TEST_F(), PVR::CGUIDialogPVRGroupManager::Update(), CGUIWindowFileManager::Update(), CGUIDialogMediaSource::UpdateButtons(), CGUIWindowMusicNav::UpdateButtons(), CGUIWindowVideoNav::UpdateButtons(), CGUIMediaWindow::UpdateFileList(), CGUIWindowFileManager::UpdateItemCounts(), CRecentlyAddedJob::UpdateMusic(), CGUIWindowMusicPlaylistEditor::UpdatePlaylist(), CRecentlyAddedJob::UpdateTotal(), CRecentlyAddedJob::UpdateVideo(), and CVideoLibraryMarkWatchedJob::Work().
GetContent()
const std::string & CFileItemList::GetContent () const inline
References m_content.
Referenced by CGUIWindowVideoNav::ApplyWatchedFilter(), CGUIViewState::AutoPlayNextVideoItem(), CGUIViewStateAddonBrowser::CGUIViewStateAddonBrowser(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIWindowMusicBase::CheckFilterAdvanced(), CGUIWindowVideoBase::CheckFilterAdvanced(), JSONRPC::CAudioLibrary::GetAdditionalDetails(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIWindowMusicNav::GetContextButtons(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowPictures::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CGUIWindowVideoBase::GetGroupedItems(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), CGUIViewState::GetViewState(), CGUIWindowVideoBase::LoadVideoInfo(), CGUIWindowMusicBase::OnItemInfoAll(), CGUIWindowVideoNav::OnMessage(), CGUIWindowMusicBase::RefreshContent(), CGUIMediaWindow::Update(), CGUIWindowMusicPlayList::Update(), and CGUIWindowVideoNav::UpdateButtons().
GetDiscFileCache()
std::string CFileItemList::GetDiscFileCache (int windowID) const private
References Crc32::ComputeFromLowerCase(), CFileItem::GetPath(), KODI::MUSIC::IsCDDA(), KODI::MUSIC::IsMusicDb(), CFileItem::IsOnDVD(), KODI::PLAYLIST::IsSmartPlayList(), and URIUtils::RemoveSlashAtEnd().
Referenced by Load(), RemoveDiscCache(), and Save().
GetFastLookup()
bool CFileItemList::GetFastLookup () const inline
References m_fastLookup.
Referenced by XFILE::Directorize().
GetFileCount()
int CFileItemList::GetFileCount () const
References m_items, and m_lock.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonGroupMembers(), PVR::CGUIDialogPVRGroupManager::ActionButtonUngroupedChannels(), CGUIWindowVideoNav::ApplyWatchedFilter(), CAutoSwitch::ByFileCount(), CAutoSwitch::ByFolderThumbPercentage(), PVR::CGUIWindowPVRRecordingsBase::GetFilteredItems(), MUSIC_INFO::CMusicInfoLoader::OnLoaderStart(), and CPictureInfoLoader::OnLoaderStart().
GetFolderCount()
int CFileItemList::GetFolderCount () const
References m_items, and m_lock.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonUngroupedChannels(), CAutoSwitch::ByFiles(), CAutoSwitch::ByFolders(), CGUIWindowPictures::OnPrepareFileItems(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), and CGUIWindowPictures::UpdateButtons().
GetList()
const VECFILEITEMS & CFileItemList::GetList () const inline
References m_items.
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetGetRecordingsSubDirectories(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), CGUIDialogVideoInfo::ManageMovieSets(), XFILE::CWin32SMBDirectory::RealExists(), and CUtil::ScanForExternalAudio().
GetObjectCount()
int CFileItemList::GetObjectCount () const
References CFileItem::IsParentFolder(), m_items, and m_lock.
Referenced by CMusicFileItemListModifier::AddQueuingFolder(), CVideoFileItemListModifier::AddQueuingFolder(), CGUIWindowVideoNav::ApplyWatchedFilter(), TestHTTPDirectory::CheckFileItemDateTimes(), TestHTTPDirectory::CheckFileItemLabels(), TestHTTPDirectory::CheckFileItemSizes(), TestHTTPDirectory::CheckFileItemTypes(), PVR::CGUIWindowPVRRecordingsBase::GetContextButtons(), CGUIWindowVideoNav::GetDirectory(), CGUIMediaWindow::GetFilteredItems(), PVR::CGUIWindowPVRRecordingsBase::GetFilteredItems(), PVR::CGUIWindowPVRSearchBase::OnPrepareFileItems(), PVR::CGUIWindowPVRChannelsBase::Update(), PVR::CGUIWindowPVRRecordingsBase::Update(), PVR::CGUIWindowPVRSearchBase::Update(), PVR::CGUIWindowPVRTimersBase::Update(), CGUIMediaWindow::UpdateButtons(), CGUIWindowEventLog::UpdateButtons(), CGUIWindowMusicPlayList::UpdateButtons(), and CGUIWindowMusicPlaylistEditor::UpdateButtons().
GetReplaceListing()
bool CFileItemList::GetReplaceListing () const inline
References m_replaceListing.
Referenced by CGUIMediaWindow::GetDirectory().
GetSelectedCount()
int CFileItemList::GetSelectedCount () const
References m_items, and m_lock.
Referenced by CGUIWindowFileManager::OnPopupMenu().
GetSortDetails()
const std::vector< GUIViewSortDetails > & CFileItemList::GetSortDetails () const inline
References m_sortDetails.
Referenced by CGUIViewStateFromItems::CGUIViewStateFromItems().
GetSortMethod()
SortBy CFileItemList::GetSortMethod () const inline
References m_sortDescription, and SortDescription::sortBy.
Referenced by CGUIMediaWindow::FormatItemLabels(), and CGUIWindowMusicBase::RefreshContent().
GetSortOrder()
SortOrder CFileItemList::GetSortOrder () const inline
References m_sortDescription, and SortDescription::sortOrder.
HasSortDetails()
bool CFileItemList::HasSortDetails () const inline
References m_sortDetails.
Referenced by CGUIViewState::GetViewState().
IsEmpty()
bool CFileItemList::IsEmpty () const
References m_items, and m_lock.
Referenced by Archive(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), CDirectoryJob::DoWork(), MUSIC_UTILS::FillArtTypesList(), JSONRPC::CAudioLibrary::GetAdditionalDetails(), CGUIWindowVideoNav::GetDirectory(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), CGUIDialogVideoInfo::LinkMovieToTvShow(), CBackgroundInfoLoader::Load(), CPictureFolderImageFileLoader::Load(), CVideoTagLoaderPlugin::Load(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIMediaWindow::OnFilterItems(), CGUIDialogColorPicker::OnInitWindow(), CGUIDialogColorPicker::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnPrepareFileItems(), PVR::CGUIWindowPVRSearchBase::OnPrepareFileItems(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), CGUIDialogSubtitles::OnSearchComplete(), CGUIDialogSubtitles::OnSubtitleServiceContextMenu(), KODI::GAME::CDialogGameSaves::Open(), KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream(), XFILE::OutdatedAddons(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CGUIDialogSubtitles::Process(), CPictureThumbLoader::ProcessFoldersAndArchives(), PVR::CPVRGUIChannelIconUpdater::SearchAndUpdateMissingChannelIcons(), CGUIWindowAddonBrowser::SelectAddonID(), KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), CGUIDialogSimpleMenu::ShowPlaySelection(), TEST(), TEST_F(), CGUIWindowFileManager::Update(), CVideoDatabase::UpdateDetailsForMovie(), and CGUIDialogSubtitles::UpdateStatus().
Load()
bool CFileItemList::Load (int windowID = 0)
load a CFileItemList out of the cache
The file list may be cached based on which window we're viewing in, as different windows will be listing different portions of the same URL (eg viewing music files versus viewing video files)
Parameters
windowID id of the window that's loading this list (defaults to 0)
Returns
true if we loaded from the cache, false otherwise.
See also
Save,RemoveDiscCache
References CArchive::Close(), GetDiscFileCache(), CFileItem::GetPath(), CArchive::load, CLog::Log(), LOGDEBUG, LOGERROR, m_sortDescription, Size(), SortDescription::sortBy, SortDescription::sortOrder, and SortOrderAscending.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetChilds(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetChilds(), XFILE::CRSSDirectory::GetDirectory(), CGUIMediaWindow::GetDirectory(), UPNP::CUPnPServer::OnBrowseDirectChildren(), MUSIC_INFO::CMusicInfoLoader::OnLoaderStart(), and CPictureInfoLoader::OnLoaderStart().
operator[]() [1/4]
CFileItemPtr CFileItemList::operator[] (const std::string & strPath)
References Get().
operator[]() [2/4]
const CFileItemPtr CFileItemList::operator[] (const std::string & strPath) const
References Get().
operator[]() [3/4]
CFileItemPtr CFileItemList::operator[] (int iItem)
References Get().
operator[]() [4/4]
const CFileItemPtr CFileItemList::operator[] (int iItem) const
References Get().
Randomize()
void CFileItemList::Randomize ()
References m_items, m_lock, and KODI::UTILS::RandomShuffle().
Referenced by CPartyModeManager::AddRandomSongs(), CPictureFolderImageFileLoader::Load(), and CPictureThumbLoader::ProcessFoldersAndArchives().
rbegin()
std::reverse_iterator< VECFILEITEMS::const_iterator > CFileItemList::rbegin () const inline
References m_items.
Referenced by GUIFontManager::SettingOptionsFontsFiller().
Remove() [1/2]
void CFileItemList::Remove (CFileItem * pItem)
References CFileItem::GetPath(), CURL::GetWithoutOptions(), m_fastLookup, m_ignoreURLOptions, m_items, m_lock, and m_map.
Referenced by CFavouritesService::AddOrRemove(), CGUIWindowVideoNav::ApplyWatchedFilter(), UPNP::CUPnPServer::BuildResponse(), anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::ClearFavourites(), XFILE::CDirectory::FilterFileDirectories(), CGUIMediaWindow::GetAdvanceFilteredItems(), XFILE::CDirectory::GetDirectory(), CGUIMediaWindow::GetDirectory(), CGUIWindowAddonBrowser::GetDirectory(), PVR::CGUIWindowPVRRecordingsBase::GetFilteredItems(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::RETRO::CSavestateDatabase::GetSavestatesNav(), CGUIDialogVideoInfo::GetSetForMovie(), CGUIDialogVideoInfo::LinkMovieToTvShow(), CPictureFolderImageFileLoader::Load(), GUIFontManager::LoadUserFonts(), XFILE::CMultiPathDirectory::MergeItems(), FAVOURITES_UTILS::MoveItem(), CGUIDialogSmartPlaylistRule::OnBrowse(), KODI::GAME::CDialogInGameSaves::OnDelete(), CGUIWindowMusicPlaylistEditor::OnDeletePlaylistItem(), CGUIDialogMediaSource::OnPathRemove(), CGUIWindowPictures::OnPrepareFileItems(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CGUIDialogVideoManagerVersions::PostProcessList(), CPictureThumbLoader::ProcessFoldersAndArchives(), FAVOURITES_UTILS::RemoveItem(), ADDON::CGUIAddonWindow::RemoveItem(), ADDON::CGUIAddonWindow::RemoveItem(), CGUIWindowMusicBase::RetrieveMusicInfo(), StackFiles(), and CGUIDialogFileBrowser::Update().
Remove() [2/2]
void CFileItemList::Remove (int iItem)
References CURL::GetWithoutOptions(), m_fastLookup, m_ignoreURLOptions, m_items, m_lock, m_map, and Size().
RemoveDiscCache() [1/2]
void CFileItemList::RemoveDiscCache (const std::string & cachefile) const
References XFILE::CFile::Delete(), XFILE::CFile::Exists(), CFileItem::GetPath(), CLog::Log(), and LOGDEBUG.
RemoveDiscCache() [2/2]
void CFileItemList::RemoveDiscCache (int windowID = 0) const
remove a previously cached CFileItemList from the cache
The file list may be cached based on which window we're viewing in, as different windows will be listing different portions of the same URL (eg viewing music files versus viewing video files)
Parameters
windowID id of the window whose cache we which to remove (defaults to 0)
See also
Save,Load
References GetDiscFileCache(), and RemoveDiscCache().
Referenced by MUSIC_UTILS::CSetArtJob::DoWork(), PVR::CGUIWindowPVRGuideBase::GetDirectory(), CGUIMediaWindow::OnClick(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), CGUIMediaWindow::OnMessage(), CGUIWindowMusicBase::OnRemoveSource(), CGUIMediaWindow::Refresh(), RemoveDiscCache(), and RemoveDiscCacheCRC().
RemoveDiscCacheCRC()
void CFileItemList::RemoveDiscCacheCRC (const std::string & crc) const
References RemoveDiscCache().
Referenced by CGUIMediaWindow::OnMessage().
RemoveExtensions()
void CFileItemList::RemoveExtensions ()
References m_items, m_lock, CFileItem::RemoveExtension(), and Size().
rend()
std::reverse_iterator< VECFILEITEMS::const_iterator > CFileItemList::rend () const inline
References m_items.
Referenced by GUIFontManager::SettingOptionsFontsFiller().
Reserve()
void CFileItemList::Reserve (size_t iCount)
References m_items, and m_lock.
Referenced by CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetArtistsByWhere(), XFILE::CPlaylistDirectory::GetDirectory(), CMusicDatabase::GetDiscsByWhere(), CVideoDatabase::GetEpisodesByWhere(), CMusicDatabase::GetGenresJSON(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideosByWhere(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsFullByWhere(), CMusicDatabase::GetTop100(), CMusicDatabase::GetTop100AlbumSongs(), CVideoDatabase::GetTvShowsByWhere(), KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), and KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream().
Save()
bool CFileItemList::Save (int windowID = 0)
save a CFileItemList to the cache
The file list may be cached based on which window we're viewing in, as different windows will be listing different portions of the same URL (eg viewing music files versus viewing video files)
Parameters
windowID id of the window that's saving this list (defaults to 0)
Returns
true if successful, false otherwise.
See also
Load,RemoveDiscCache
References CArchive::Close(), GetDiscFileCache(), CFileItem::GetPath(), CLog::Log(), LOGDEBUG, m_items, m_sortDescription, Size(), SortDescription::sortBy, SortDescription::sortOrder, SortOrderAscending, and CArchive::store.
Referenced by XFILE::CRSSDirectory::GetDirectory(), CGUIMediaWindow::GetDirectory(), UPNP::CUPnPServer::OnBrowseDirectChildren(), CGUIMediaWindow::OnCacheFileItems(), MUSIC_INFO::CMusicInfoLoader::OnLoaderFinish(), and CPictureInfoLoader::OnLoaderFinish().
SetCacheToDisc()
void CFileItemList::SetCacheToDisc (CACHE_TYPE cacheToDisc) inline
References m_cacheToDisc.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetChilds(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetChilds(), PVR::CPVRGUIDirectory::GetDirectory(), XFILE::CAddonsDirectory::GetDirectory(), and XFILE::CUPnPDirectory::GetDirectory().
SetContent()
void CFileItemList::SetContent (const std::string & content) inline
References m_content.
Referenced by XFILE::CAddonsDirectory::GenerateAddonListing(), XFILE::CEventsDirectory::GetDirectory(), XFILE::CUPnPDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowMusicNav::GetDirectory(), CGUIWindowPictures::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), PVR::CPVRGUIDirectory::GetRecordingsDirectory(), XFILE::CAddonsDirectory::GetScriptsAndPlugins(), CVideoDatabase::GetSortedVideos(), CGUIWindowVideoBase::LoadVideoInfo(), CFavouritesService::ReInit(), XFILE::Repos(), ADDON::CGUIAddonWindow::SetContainerContent(), CGUIDialogVideoInfo::SetMovie(), CGUIWindowMusicPlayList::Update(), and CGUIWindowMusicPlaylistEditor::Update().
SetFastLookup()
void CFileItemList::SetFastLookup (bool fastLookup)
References CURL::GetWithoutOptions(), m_fastLookup, m_ignoreURLOptions, m_items, m_lock, and m_map.
Referenced by Archive(), XFILE::Directorize(), CUtil::GetNextFilename(), CVideoDatabase::GetPlayCounts(), MUSIC_INFO::CMusicInfoLoader::LoadCache(), GUIFontManager::LoadUserFonts(), CGUIWindowVideoBase::LoadVideoInfo(), MUSIC_INFO::CMusicInfoLoader::OnLoaderStart(), CPictureInfoLoader::OnLoaderStart(), and SetIgnoreURLOptions().
SetIgnoreURLOptions()
void CFileItemList::SetIgnoreURLOptions (bool ignoreURLOptions)
References m_fastLookup, m_ignoreURLOptions, and SetFastLookup().
Referenced by Archive().
SetReplaceListing()
void CFileItemList::SetReplaceListing (bool replace)
References m_replaceListing.
SetSortIgnoreFolders()
void CFileItemList::SetSortIgnoreFolders (bool sort) inline
Specify whether this list should be sorted with folders separate from files By default we sort with folders listed (and sorted separately) except for those sort modes which should be explicitly sorted with folders interleaved with files (eg SORT_METHOD_FILES). With this set the folder state will be ignored, allowing folders and files to sort interleaved.
Parameters
sort whether to ignore the folder state.
References m_sortIgnoreFolders.
Referenced by XFILE::CSmartPlaylistDirectory::GetDirectory(), and CGUIWindowVideoBase::LoadVideoInfo().
SetSortMethod()
void CFileItemList::SetSortMethod (SortBy sortBy) inline
References m_sortDescription, and SortDescription::sortBy.
Referenced by CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetArtistsByWhere(), and CMusicDatabase::GetSongsFullByWhere().
SetSortOrder()
void CFileItemList::SetSortOrder (SortOrder sortOrder) inline
References m_sortDescription, and SortDescription::sortOrder.
Referenced by CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetArtistsByWhere(), and CMusicDatabase::GetSongsFullByWhere().
Size()
int CFileItemList::Size () const
References m_items, and m_lock.
Referenced by KODI::PLAYLIST::CPlayList::Add(), JSONRPC::CPlaylistOperations::Add(), ADDON::CGUIAddonWindow::AddItem(), CGUIWindowSlideShow::AddItems(), CGUIDialogVideoInfo::AddItemsToTag(), CMusicFileItemListModifier::AddQueuingFolder(), CVideoFileItemListModifier::AddQueuingFolder(), CPartyModeManager::AddUserSongs(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersion(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), Append(), CGUIWindowVideoBase::AppendAndClearSearchItems(), CGUIWindowVideoNav::ApplyWatchedFilter(), UPNP::CUPnPServer::BuildResponse(), CAutoSwitch::ByFileCount(), CAutoSwitch::ByFiles(), CAutoSwitch::ByFolders(), CAutoSwitch::ByFolderThumbPercentage(), CAutoSwitch::ByThumbPercent(), CGUIWindowFileManager::CalculateFolderSize(), KODI::VIDEO::CVideoInfoScanner::CanFastHash(), ADDON::CFileItemListToVFSDirEntries(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::ChooseStackItemPartNumber(), CGUIDialogVideoManagerVersions::ChooseVideoAndConvertToVideoVersion(), ADDON::CScraper::ClearCache(), anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::ClearFavourites(), ClearPhotoAssetCache(), CGUIDialogCMSSettings::Cms3dLutsFiller(), XFILE::CRSSDirectory::ContainsFiles(), Copy(), MUSIC_INFO::CMusicInfoScanner::CountFiles(), XFILE::CFileDirectoryFactory::Create(), CMusicDatabase::DeleteCDDBInfo(), CDVDFileInfo::DemuxerToStreamDetails(), XFILE::DependencyAddons(), CBlurayCallback::dir_read(), dll_readdir(), CFileOperationJob::DoProcess(), CFileOperationJob::DoProcessFolder(), MUSIC_INFO::CMusicInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::DoScan(), CGUIDialogVideoInfo::DoSearch(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CGUIMultiImage::CMultiImageJob::DoWork(), CDirectoryJob::DoWork(), CVideoDatabase::DumpToDummyFiles(), ADDON::CAddonInstaller::EnumeratePackageFolder(), KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs(), MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), MUSIC_INFO::CMusicInfoScanner::FileItemsToAlbums(), JSONRPC::CFileItemHandler::FillFileItemList(), JSONRPC::CFileOperations::FillFileItemList(), XFILE::CDirectory::FilterFileDirectories(), ADDON::CAddonMgr::FindAddons(), CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), CGUIMediaWindow::FormatItemLabels(), ADDON::Interface_Filesystem::get_directory(), CVideoDatabase::GetActorsNav(), JSONRPC::CAudioLibrary::GetAdditionalAlbumDetails(), JSONRPC::CAudioLibrary::GetAdditionalArtistDetails(), JSONRPC::CAudioLibrary::GetAdditionalSongDetails(), CGUIMediaWindow::GetAdvanceFilteredItems(), CMusicDatabase::GetAlbumsByWhere(), CGUIDialogVideoManagerVersions::GetAllOtherMovies(), JSONRPC::CAudioLibrary::GetArtistDetails(), CMusicDatabase::GetArtistsByWhere(), CVideoDatabase::GetBookMarksForFile(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), JSONRPC::CPVROperations::GetBroadcasts(), CGUIWindowEventLog::GetContextButtons(), CGUIWindowMusicPlayList::GetContextButtons(), CGUIWindowPrograms::GetContextButtons(), PVR::CGUIWindowPVRRecordingsBase::GetContextButtons(), PVR::CGUIWindowPVRSearchBase::GetContextButtons(), CGUIWindowVideoBase::GetContextButtons(), CGUIWindowVideoPlaylist::GetContextButtons(), CGUIDialogFileBrowser::GetCurrentListItem(), CGUIMediaWindow::GetCurrentListItem(), CGUIWindowLoginScreen::GetCurrentListItem(), CGUIWindowMusicPlaylistEditor::GetCurrentPlaylistItem(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CResourceDirectory::GetDirectory(), XFILE::CSpecialProtocolDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectory(), XFILE::CDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), JSONRPC::CFileOperations::GetDirectory(), CGUIMediaWindow::GetDirectory(), CGUIWindowAddonBrowser::GetDirectory(), CGUIWindowEventLog::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), XFILE::CDirectoryCache::GetDirectory(), CMusicDatabase::GetDiscsByWhere(), ADDON::CScraper::GetEpisodeList(), CVideoDatabase::GetEpisodesNav(), JSONRPC::CFavouritesOperations::GetFavourites(), CGUIMediaWindow::GetFilteredItems(), PVR::CGUIWindowPVRRecordingsBase::GetFilteredItems(), CGUIWindowVideoNav::GetFirstUnwatchedItemIndex(), KODI::GAME::CDialogGameVideoFilter::GetFocusedItem(), JSONRPC::CVideoLibrary::GetGenres(), CMusicDatabase::GetGenresJSON(), PERIPHERALS::CGUIDialogPeripherals::GetItem(), CGUIDialogMediaFilter::GetItems(), CVideoDatabase::GetItemsForPath(), CGUIDialogVideoInfo::GetItemsForTag(), ADDON::CGUIAddonWindow::GetListItem(), ADDON::CGUIAddonWindow::GetListSize(), CGUIDialogVideoInfo::GetMoviesForSet(), CVideoDatabase::GetMusicVideoAlbumsNav(), URIUtils::GetParentPath(), MUSIC_INFO::CMusicInfoScanner::GetPathHash(), KODI::VIDEO::CVideoInfoScanner::GetPathHash(), CGUIDialogMediaSource::GetPaths(), CVideoDatabase::GetPeopleNav(), XFILE::CSmartPlaylistDirectory::GetPlaylistByName(), JSONRPC::CPlaylistOperations::GetPropertyValue(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), KODI::VIDEO::CVideoInfoScanner::GetRecursiveFastHash(), CVideoDatabase::GetResumePoint(), JSONRPC::CAudioLibrary::GetRoles(), JSONRPC::CFileOperations::GetRootDirectory(), KODI::RETRO::CSavestateDatabase::GetSavestatesNav(), CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetSeasonsNav(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), CGUIDialogMediaSource::GetSelectedItem(), CGUIDialogColorPicker::GetSelectedItem(), CGUIViewControl::GetSelectedItem(), CGUIDialogSubtitles::GetService(), CGUIDialogVideoInfo::GetSetForMovie(), CVideoDatabase::GetSetInfo(), CGUIDialogVideoManagerVersions::GetSimilarMovies(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsFullByWhere(), CGUIViewStateWindowMusicNav::GetSources(), CGUIViewStateWindowVideoNav::GetSources(), CMusicDatabase::GetSources(), XFILE::CStackDirectory::GetStackedTitlePath(), JSONRPC::CVideoLibrary::GetTags(), CURL::GetWithoutUserDetails(), CGUIMediaWindow::GoParentFolder(), CGUIDialogVideoBookmarks::GotoBookmark(), GroupUtils::Group(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::CVideoLibrary::HandleItems(), CGUIDialogMediaSource::HighlightItem(), CGUIDialogSmartPlaylistEditor::HighlightItem(), KODI::PLAYLIST::CPlayList::Insert(), ADDON::CAddonInstaller::InstallFromZip(), CGUIDialogVideoInfo::LinkMovieToTvShow(), XBMCAddon::xbmcvfs::listdir(), KODI::KEYMAP::CButtonTranslator::Load(), CBackgroundInfoLoader::Load(), CPictureFolderImageFileLoader::Load(), Load(), GUIFontManager::LoadFonts(), CGUIWindowVideoBase::LoadVideoInfo(), CGUIDialogVideoInfo::ManageMovieSets(), XFILE::CMultiPathDirectory::MergeItems(), CAutoSwitch::MetadataPercentage(), FAVOURITES_UTILS::MoveItem(), CGUIWindowMusicPlayList::MoveItem(), CGUIWindowVideoPlaylist::MoveItem(), CGUIWindowFavourites::MoveItem(), ADDON::CScraper::NfoUrl(), CGUIWindowFileManager::NumSelected(), CGUIDialogFileBrowser::OnAction(), CGUIWindowFavourites::OnAction(), CGUIWindowFileManager::OnAction(), PVR::CGUIDialogPVRChannelManager::OnActionMove(), PVR::CGUIDialogPVRGroupManager::OnActionMove(), CApplication::OnApplicationMessage(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIDialogFileBrowser::OnClick(), CGUIMediaWindow::OnClick(), KODI::GAME::CGUIWindowGames::OnClick(), CGUIWindowMusicNav::OnClick(), CGUIWindowMusicPlaylistEditor::OnClick(), CGUIWindowPictures::OnClick(), CGUIWindowVideoNav::OnClick(), KODI::GAME::CDialogInGameSaves::OnClickAction(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), PVR::CGUIDialogPVRChannelManager::OnClickListChannels(), PVR::CGUIDialogPVRChannelManager::OnContextButton(), CGUIWindowEventLog::OnContextButton(), CGUIWindowPictures::OnContextButton(), CGUIWindowPrograms::OnContextButton(), PVR::CGUIWindowPVRChannelsBase::OnContextButton(), PVR::CGUIWindowPVRGuideBase::OnContextButton(), PVR::CGUIWindowPVRRecordingsBase::OnContextButton(), PVR::CGUIWindowPVRSearchBase::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), PVR::CGUIDialogPVRGroupManager::OnContextButton(), KODI::GAME::CDialogInGameSaves::OnDeleteAction(), CGUIWindowVideoNav::OnDeleteItem(), CGUIMediaWindow::OnDeleteItem(), CGUIWindowVideoBase::OnDeleteItem(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIMediaWindow::OnFilterItems(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogColorPicker::OnInitWindow(), PVR::CGUIDialogPVRChannelManager::OnInitWindow(), KODI::GAME::CDialogGameVideoFilter::OnItemFocus(), KODI::GAME::CDialogInGameSaves::OnItemFocus(), CGUIWindowVideoBase::OnItemInfo(), CGUIWindowMusicBase::OnItemInfo(), CGUIWindowPrograms::OnItemInfo(), CGUIWindowVideoBase::OnItemInfo(), KODI::GAME::CDialogInGameSaves::OnMenuAction(), CGUIWindowAddonBrowser::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowEventLog::OnMessage(), CGUIWindowFavourites::OnMessage(), CGUIBaseContainer::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowMusicPlayList::OnMove(), CGUIWindowVideoPlaylist::OnMove(), CGUIWindowMusicPlaylistEditor::OnMovePlaylistItem(), CGUIWindowFileManager::OnNewFolder(), KODI::GAME::CDialogInGameSaves::OnOverwriteAction(), CGUIDialogMediaSource::OnPath(), CGUIDialogMediaSource::OnPathAdd(), CGUIDialogMediaSource::OnPathBrowse(), CGUIDialogMediaSource::OnPathRemove(), CGUIWindowPrograms::OnPlayMedia(), CGUIWindowVideoBase::OnPlayMedia(), CGUIWindowVideoPlaylist::OnPlayMedia(), CGUIWindowVideoBase::OnPlayOrResumeItem(), CGUIMediaWindow::OnPopupMenu(), CGUIWindowLoginScreen::OnPopupMenu(), CGUIWindowFileManager::OnPopupMenu(), PVR::CGUIDialogPVRGroupManager::OnPopupMenu(), CGUIWindowPictures::OnPrepareFileItems(), CGUIWindowMusicBase::OnQueueItem(), CGUIWindowVideoBase::OnQueueItem(), CGUIWindowMusicPlaylistEditor::OnQueueItem(), CGUIDialogVideoBookmarks::OnRefreshList(), CGUIWindowFileManager::OnRename(), KODI::GAME::CDialogInGameSaves::OnRenameAction(), CGUIMediaWindow::OnRenameItem(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), CGUIDialogSmartPlaylistEditor::OnRuleRemove(), CGUIWindowMusicBase::OnScan(), CGUIWindowVideoBase::OnSearch(), CGUIDialogVideoInfo::OnSearch(), CGUIWindowVideoBase::OnSearchItemFound(), CGUIWindowVideoBase::OnSelect(), CGUIWindowEventLog::OnSelect(), CGUIWindowFavourites::OnSelect(), CGUIWindowFileManager::OnSelectAll(), CGUIDialogAddonInfo::OnSelectVersion(), CGUIWindowFileManager::OnSort(), CDVDInputStreamStack::Open(), JSONRPC::CPlayerOperations::Open(), CFileOperationJob::operator==(), CGUIWindowVideoBase::PlayItem(), CApplication::PlayMedia(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CGUIDialogVideoManagerVersions::PostProcessList(), KODI::GAME::CDialogGameVideoFilter::PreInit(), KODI::GAME::CControllerSelect::Process(), PVR::CPVRRefreshTimelineItemsThread::Process(), CPictureThumbLoader::ProcessFoldersAndArchives(), CGUIDialogVideoManagerVersions::ProcessVideoVersion(), ADDON::CAddonInstaller::PrunePackageCache(), Remove(), ADDON::Interface_Filesystem::remove_directory(), RemoveExtensions(), FAVOURITES_UTILS::RemoveItem(), CGUIWindowFavourites::RemoveItem(), CGUIDialogVideoInfo::RemoveItemsFromTag(), CGUIWindowMusicPlayList::RemovePlayListItem(), CGUIWindowVideoPlaylist::RemovePlayListItem(), CCueDocument::ResolvePath(), CGUIMediaWindow::RestoreSelectedItemFromHistory(), CGUIWindowMusicBase::RetrieveMusicInfo(), MUSIC_INFO::CMusicInfoScanner::RetrieveMusicInfo(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), KODI::CDRIP::CCDDARipper::RipCD(), Save(), MUSIC_INFO::CMusicInfoLoader::SaveCache(), PVR::CGUIDialogPVRChannelManager::SaveList(), CGUIWindowMusicPlayList::SavePlayList(), MUSIC_INFO::CMusicInfoScanner::ScanTags(), PVR::CGUIDialogPVRChannelManager::SetData(), CFileOperationJob::SetFileOperation(), CGUIMediaWindow::SetHistoryForPath(), CGUIViewControl::SetSelectedItem(), CGUIViewControl::SetSelectedItem(), CGUIDialogSubtitles::SetService(), ADDON::CSkinInfo::SettingOptionsSkinColorsFiller(), ADDON::CSkinInfo::SettingOptionsSkinFontsFiller(), CTVOSTopShelf::SetTopShelfItems(), CGUIDialogMediaSource::ShowAndAddMediaSource(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), CGUIDialogAddonSettings::ShowForMultipleInstances(), CGUIWindowPictures::ShowPicture(), CFavouritesService::Size(), Sort(), StackFiles(), StackFolders(), ADDON::CSkinInfo::Start(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), CFilesystemInstaller::UnpackArchive(), PVR::CGUIDialogPVRChannelManager::Update(), CGUIDialogFileBrowser::Update(), CGUIMediaWindow::Update(), PVR::CGUIWindowPVRBase::Update(), CGUIWindowFileManager::Update(), CGUIDialogMediaSource::UpdateButtons(), CGUIWindowMusicNav::UpdateButtons(), CGUIWindowMusicPlayList::UpdateButtons(), CGUIWindowPictures::UpdateButtons(), CGUIWindowVideoNav::UpdateButtons(), CGUIWindowVideoPlaylist::UpdateButtons(), CGUIMediaWindow::UpdateFileList(), CGUIWindowFileManager::UpdateItemCounts(), CRecentlyAddedJob::UpdateMusic(), PERIPHERALS::CGUIDialogPeripherals::UpdatePeripheralsSync(), CGUIWindowMusicPlaylistEditor::UpdatePlaylist(), CGUIDialogSubtitles::UpdateStatus(), CRecentlyAddedJob::UpdateTotal(), CRecentlyAddedJob::UpdateVideo(), and CVideoLibraryMarkWatchedJob::Work().
Sort() [1/3]
void CFileItemList::Sort (FILEITEMLISTCOMPARISONFUNC func) private
References m_items, and m_lock.
Sort() [2/3]
void CFileItemList::Sort (SortBy sortBy, SortOrder sortOrder, SortAttribute sortAttributes = SortAttributeNone)
References m_sortDescription, Sort(), SortDescription::sortAttributes, SortDescription::sortBy, SortByNone, and SortDescription::sortOrder.
Referenced by CGUIWindowSlideShow::AddItems(), CGUIWindowVideoBase::AppendAndClearSearchItems(), UPNP::CUPnPServer::DefaultSortItems(), MUSIC_INFO::CMusicInfoScanner::DoScan(), CDirectoryJob::DoWork(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), JSONRPC::CAudioLibrary::FillFileItemList(), JSONRPC::CFileOperations::FillFileItemList(), CGUIMediaWindow::FormatAndSort(), CGUIDialogVideoManagerVersions::GetAllOtherMovies(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), CMusicDatabase::GetDiscsByWhere(), CGUIDialogMediaFilter::GetItems(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CGUIDialogVideoInfo::GetItemsForTag(), CGUIDialogVideoInfo::GetMoviesForSet(), CGUIDialogVideoInfo::GetSetForMovie(), CMusicDatabase::GetSongsFullByWhere(), KODI::GAME::CDialogInGameSaves::InitSavedGames(), CGUIDialogVideoInfo::LinkMovieToTvShow(), KODI::KEYMAP::CButtonTranslator::Load(), XFILE::CMultiPathDirectory::MergeItems(), CGUIDialogSmartPlaylistRule::OnBrowse(), UPNP::CUPnPServer::OnBrowseDirectChildren(), CGUIDialogFileBrowser::OnSort(), CGUIWindowFileManager::OnSort(), KODI::GAME::CDialogGameSaves::Open(), CPictureThumbLoader::ProcessFoldersAndArchives(), ADDON::CAddonInstaller::PrunePackageCache(), CGUIWindowAddonBrowser::SelectAddonID(), CGUIDialogVideoInfo::SetMovie(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), JSONRPC::CFileItemHandler::Sort(), Sort(), CGUIMediaWindow::SortItems(), and Stack().
Sort() [3/3]
void CFileItemList::Sort (SortDescription sortDescription)
References FieldId, fields, FieldSort, SortUtils::GetFieldsForSorting(), index(), m_items, m_sortDescription, m_sortIgnoreFolders, Size(), SortUtils::Sort(), SortAttributeIgnoreFolders, SortDescription::sortAttributes, SortDescription::sortBy, SortByDateAdded, SortByFile, SortByLastPlayed, SortByNone, SortByOriginalTitle, SortByPlaycount, SortByPlaylistOrder, SortByRating, SortBySortTitle, SortByYear, and SortDescription::sortOrder.
Stack()
void CFileItemList::Stack (bool stackFiles = true)
stack a CFileItemList By default we stack all items (files and folders) in a CFileItemList
Parameters
stackFiles whether to stack all items or just collapse folders (defaults to true)
See also
StackFiles,StackFolders
References CFileItem::IsLibraryFolder(), CFileItem::IsLiveTV(), CFileItem::IsSourcesPath(), CFileItem::IsVirtualDirectoryRoot(), m_lock, CGUIListItem::SetProperty(), Sort(), SortByLabel, SortOrderAscending, StackFiles(), and StackFolders().
Referenced by KODI::VIDEO::CVideoInfoScanner::DoScan(), CGUIWindowVideoBase::GetDirectory(), CGUIWindowVideoBase::OnItemInfo(), TEST_F(), TEST_F(), and TEST_F().
StackFiles()
void CFileItemList::StackFiles () private
stack files in a CFileItemList
See also
Stack
References CRegExp::autoUtf8, XFILE::CStackDirectory::ConstructStackPath(), Get(), CRegExp::GetCaptureTotal(), CServiceBroker::GetSettingsComponent(), URIUtils::HasEncodedFilename(), int64_t(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsRAR(), CLog::Log(), LOGERROR, CRegExp::RegComp(), Remove(), URIUtils::RemoveExtension(), CSettings::SETTING_FILELISTS_SHOWEXTENSIONS, Size(), and URIUtils::Split().
Referenced by Stack().
StackFolders()
void CFileItemList::StackFolders () private
stack folders in a CFileItemList
See also
Stack
References CRegExp::autoUtf8, XFILE::DIR_FLAG_DEFAULTS, Get(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), KODI::VIDEO::UTILS::GetOpticalMediaPath(), CServiceBroker::GetSettingsComponent(), CFileExtensionProvider::GetVideoExtensions(), index(), CRegExp::IsCompiled(), URIUtils::IsInRAR(), URIUtils::IsInZIP(), URIUtils::IsOnLAN(), KODI::NETWORK::IsRemote(), CLog::Log(), LOGDEBUG, LOGERROR, CGUIListItem::m_bIsFolder, m_sortDescription, CRegExp::RegComp(), Size(), SortDescription::sortBy, and SortByNone.
Referenced by Stack().
Swap()
void CFileItemList::Swap (unsigned int item1, unsigned int item2)
References m_items.
Referenced by FAVOURITES_UTILS::MoveItem(), PVR::CGUIDialogPVRChannelManager::OnActionMove(), PVR::CGUIDialogPVRGroupManager::OnActionMove(), and CGUIWindowMusicPlaylistEditor::OnMovePlaylistItem().
UpdateItem()
bool CFileItemList::UpdateItem (const CFileItem * item)
Update an item in the item list.
Parameters
item the new item, which we match based on path to an existing item in the list
Returns
true if the item exists in the list (and was thus updated), false otherwise.
References m_items, and m_lock.
Referenced by CGUIMediaWindow::OnMessage().
Member Data Documentation
m_cacheToDisc
CACHE_TYPE CFileItemList::m_cacheToDisc = CACHE_IF_SLOW private
Referenced by Archive(), Assign(), CacheToDiscAlways(), CacheToDiscIfSlow(), Clear(), Copy(), and SetCacheToDisc().
m_content
std::string CFileItemList::m_content private
Referenced by Archive(), Assign(), Clear(), Copy(), GetContent(), and SetContent().
m_fastLookup
bool CFileItemList::m_fastLookup = false private
Referenced by Add(), Add(), AddFront(), Archive(), Contains(), Get(), GetFastLookup(), Remove(), Remove(), SetFastLookup(), and SetIgnoreURLOptions().
m_ignoreURLOptions
bool CFileItemList::m_ignoreURLOptions = false private
Referenced by Add(), Add(), AddFront(), Archive(), Contains(), Get(), Remove(), Remove(), SetFastLookup(), and SetIgnoreURLOptions().
m_items
VECFILEITEMS CFileItemList::m_items private
Referenced by Add(), Add(), AddFront(), Archive(), begin(), begin(), cbegin(), cend(), ClearItems(), Contains(), end(), end(), erase(), FillInDefaultIcons(), FillSortFields(), FilterCueItems(), Get(), Get(), GetFileCount(), GetFolderCount(), GetList(), GetObjectCount(), GetSelectedCount(), IsEmpty(), Randomize(), rbegin(), Remove(), Remove(), RemoveExtensions(), rend(), Reserve(), Save(), SetFastLookup(), Size(), Sort(), Sort(), Swap(), and UpdateItem().
m_lock
CCriticalSection CFileItemList::m_lock mutable private
Referenced by Add(), Add(), AddFront(), Append(), Archive(), Assign(), Clear(), ClearItems(), Contains(), erase(), FillInDefaultIcons(), FillSortFields(), FilterCueItems(), Get(), Get(), GetFileCount(), GetFolderCount(), GetObjectCount(), GetSelectedCount(), IsEmpty(), Randomize(), Remove(), Remove(), RemoveExtensions(), Reserve(), SetFastLookup(), Size(), Sort(), Stack(), and UpdateItem().
m_map
MAPFILEITEMS CFileItemList::m_map private
Referenced by Add(), Add(), AddFront(), ClearItems(), Contains(), Get(), Remove(), Remove(), and SetFastLookup().
m_replaceListing
bool CFileItemList::m_replaceListing = false private
Referenced by Assign(), Clear(), Copy(), GetReplaceListing(), and SetReplaceListing().
m_sortDescription
SortDescription CFileItemList::m_sortDescription private
Referenced by Archive(), Assign(), Clear(), ClearSortState(), Copy(), GetSortMethod(), GetSortOrder(), Load(), Save(), SetSortMethod(), SetSortOrder(), Sort(), Sort(), and StackFolders().
m_sortDetails
std::vector<GUIViewSortDetails> CFileItemList::m_sortDetails private
Referenced by AddSortMethod(), Archive(), Assign(), Clear(), Copy(), GetSortDetails(), and HasSortDetails().
m_sortIgnoreFolders
bool CFileItemList::m_sortIgnoreFolders = false private
Referenced by Archive(), Clear(), Copy(), SetSortIgnoreFolders(), and Sort().
The documentation for this class was generated from the following files:
FileItemList.h
FileItemList.cpp