Kodi Documentation: KODI::MUSIC Namespace Reference
KODI::MUSIC Namespace Reference
Functions
bool IsAudio (const CFileItem &item)
Check whether an item is an audio item.
bool IsAudioBook (const CFileItem &item)
Check whether an item is an audio book item.
bool IsCDDA (const CFileItem &item)
Check whether an item is an audio cd item.
bool IsCUESheet (const CFileItem &item)
Check whether an item is a cue sheet.
bool IsLyrics (const CFileItem &item)
Check whether an item is a lyrics file.
bool IsMusicDb (const CFileItem &item)
Check whether an item is a music database item.
Function Documentation
IsAudio()
bool KODI::MUSIC::IsAudio (const CFileItem & item)
Check whether an item is an audio item.
Note that this returns true for anything with a music info tag, so that may include eg. folders.
Todo:
If the file is a zip file, ask the game clients if any support this
References CServiceBroker::GetFileExtensionProvider(), CFileItem::GetMimeType(), CFileExtensionProvider::GetMusicExtensions(), CFileItem::GetPath(), URIUtils::HasExtension(), CFileItem::HasGameInfoTag(), CFileItem::HasMusicInfoTag(), CFileItem::HasPictureInfoTag(), CFileItem::HasVideoInfoTag(), and IsCDDA().
Referenced by UPNP::CUPnPServer::Build(), UPNP::BuildObject(), MUSIC_INFO::CMusicInfoScanner::CountFiles(), CSaveFileState::DoWork(), CApplication::ExecuteXBMCAction(), KODI::ART::FillInDefaultIcon(), CFileItemList::FilterCueItems(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), UPNP::GetMimeType(), MUSIC_INFO::CMusicInfoScanner::GetPathHash(), CPlayerCoreFactory::GetPlayers(), CPlayerSelectionRule::GetPlayers(), anonymous_namespace{PlayerBuiltins.cpp}::GetPlayListId(), CDirectoryJob::getThumbLoader(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), MUSIC_UTILS::IsItemPlayable(), anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked(), KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListPLS::Load(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), MUSIC_INFO::CMusicInfoLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CFileItem::LoadMusicTag(), CSeekHandler::OnAction(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CApplication::OnMessage(), CApplicationPlayerCallback::OnPlayerCloseFile(), CGUIWindowFileManager::OnStart(), UPNP::CUPnPPlayer::OpenFile(), KODI::PLAYLIST::CPlayListPlayer::Play(), CApplication::PlayFile(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), TEST(), and TEST_P().
IsAudioBook()
bool KODI::MUSIC::IsAudioBook (const CFileItem & item)
Check whether an item is an audio book item.
References CFileItem::IsType().
Referenced by XFILE::CFileDirectoryFactory::Create(), CSaveFileState::DoWork(), CFileItem::IsFileFolder(), CGUIMediaWindow::OnPlayAndQueueMedia(), CGUIWindowMusicBase::OnSelect(), and TEST_P().
IsCDDA()
bool KODI::MUSIC::IsCDDA (const CFileItem & item)
Check whether an item is an audio cd item.
References CFileItem::GetPath(), and URIUtils::IsCDDA().
Referenced by CONTEXTMENU::CVideoResume::Execute(), CONTEXTMENU::CVideoPlay::Execute(), CGUIDialogContextMenu::GetContextButtons(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), XFILE::CSourcesDirectory::GetDirectory(), CFileItemList::GetDiscFileCache(), IsAudio(), KODI::VIDEO::UTILS::IsItemPlayable(), CFileItem::IsRemovable(), CONTEXTMENU::CEjectDisk::IsVisible(), CONTEXTMENU::CEjectDrive::IsVisible(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CFileItem::LoadMusicTag(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), CGUIWindowMusicBase::OnRipCD(), CGUIWindowMusicBase::OnRipTrack(), CApplication::PlaybackCleanup(), PAPlayer::QueueNextFileEx(), KODI::PLAYLIST::CPlayList::RemoveDVDItems(), TEST_P(), and PAPlayer::UpdateCrossfadeTime().
IsCUESheet()
bool KODI::MUSIC::IsCUESheet (const CFileItem & item)
Check whether an item is a cue sheet.
References CFileItem::GetPath(), and URIUtils::HasExtension().
Referenced by CFileItemList::FilterCueItems(), and TEST_P().
IsLyrics()
bool KODI::MUSIC::IsLyrics (const CFileItem & item)
Check whether an item is a lyrics file.
References CFileItem::GetPath(), and URIUtils::HasExtension().
Referenced by CGUIWindowMusicBase::RetrieveMusicInfo(), MUSIC_INFO::CMusicInfoScanner::ScanTags(), and TEST_P().
IsMusicDb()
bool KODI::MUSIC::IsMusicDb (const CFileItem & item)
Check whether an item is a music database item.
References CFileItem::GetPath(), and URIUtils::IsMusicDb().
Referenced by CMusicFileItemListModifier::AddQueuingFolder(), CFileItemList::AlwaysCache(), UPNP::BuildObject(), CMusicFileItemListModifier::CanModify(), CGUIWindowMusicBase::CheckFilterAdvanced(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), CSaveFileState::DoWork(), XFILE::CDirectory::GetDirectory(), CGUIWindowMusicNav::GetDirectory(), XFILE::CSourcesDirectory::GetDirectory(), CFileItemList::GetDiscFileCache(), JSONRPC::CPlayerOperations::GetItem(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), UPNP::GetMimeType(), CFileItem::GetUserMusicThumb(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), CFileItem::IsSamePath(), MUSIC_INFO::CMusicInfoLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), UPNP::CUPnPServer::OnBrowseMetadata(), CGUIWindowMusicNav::OnClick(), CGUIDialogSongInfo::OnGetArt(), CGUIWindowMusicBase::OnPrepareFileItems(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), UPNP::CUPnPServer::OnUpdateObject(), CExecString::Parse(), UPNP::CUPnPPlayer::PlayFile(), UPNP::CUPnPPlayer::QueueNextFile(), KODI::PLAYLIST::CPlayList::ResolveURL(), CGUIWindowMusicPlayList::SavePlayList(), CGUIDialogMusicInfo::ShowFor(), CGUIDialogSongInfo::ShowFor(), TEST_P(), and CGUIWindowMusicBase::UpdateButtons().