Kodi Documentation: CWinSystemOSX Class Reference
CWinSystemOSX Class Reference
#include <WinSystemOSX.h>
Classes
struct ScreenResolution
Public Member Functions
CWinSystemOSX ()
~CWinSystemOSX () override
void OnTimeout () override
bool InitWindowSystem () override
bool DestroyWindowSystem () override
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override
bool DestroyWindow () override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
void UpdateResolutions () override
bool Minimize () override
bool Restore () override
bool Hide () override
bool HasCursor () override
bool Show (bool raise=true) override
unsigned int GetScreenId (const std::string &screen) override
Get the screen ID provided the screen name.
void MoveToScreen (unsigned int screenIdx) override
Window was requested to move to the given screen.
void OnMove (int x, int y) override
void OnChangeScreen (unsigned int screenIdx) override
Used to signal the windowing system about the change of the current screen.
bool HasValidResolution () const
std::string GetClipboardText () override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
void WindowChangedScreen ()
void AnnounceOnLostDevice ()
void AnnounceOnResetDevice ()
void HandleOnResetDevice ()
void StartLostDeviceTimer ()
void StopLostDeviceTimer ()
int CheckDisplayChanging (uint32_t flags)
void SetFullscreenWillToggle (bool toggle)
bool GetFullscreenWillToggle ()
void SignalFullScreenStateChanged (bool fullscreenState)
CGLContextObj GetCGLContextObj ()
std::vector< std::string > GetConnectedOutputs () override
bool MessagePump () override
NSRect GetWindowDimensions ()
void enableInputEvents ()
void disableInputEvents ()
void signalMouseEntered ()
void signalMouseExited ()
void SendInputEvent (NSEvent *nsEvent)
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual CRenderSystemBase * GetRenderSystem ()
virtual const std::string GetName ()
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual void FinishWindowResize (int newWidth, int newHeight)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppFocusChange (bool bGaining)
virtual void NotifyAppActiveChange (bool bActivated)
virtual void ShowOSMouse (bool show)
virtual bool HasInertialGestures ()
virtual bool UseLimitedColor ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual float GetDisplayLatency ()
Get average display latency.
virtual float GetFrameLatencyAdjustment ()
Get time that should be subtracted from the display latency for this frame in milliseconds.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
virtual bool CanDoWindowed ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual bool SetHDR (const VideoPicture *videoPicture)
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
virtual bool IsHDRDisplay ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual CHDRCapabilities GetDisplayHDRCapabilities () const
virtual float GetGuiSdrPeakLuminance () const
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
virtual bool BindTextureUploadContext ()
Binds a shared context to the current thread, in order to upload textures asynchronously.
virtual bool UnbindTextureUploadContext ()
Unbinds the shared context.
virtual bool HasContext ()
Checks if a graphics context is already bound to the current thread.
Public Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Protected Member Functions
std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl () override
ScreenResolution GetScreenResolution (unsigned long screenIdx)
void EnableVSync (bool enable)
bool SwitchToVideoMode (RESOLUTION_INFO &res)
void FillInVideoModes ()
bool FlushBuffer ()
bool DestroyWindowInternal ()
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
Protected Attributes
std::unique_ptr< CWinEventsOSX > m_winEvents
std::string m_name
NSWindow * m_appWindow
OSXGLView * m_glView
unsigned long m_lastDisplayNr
double m_refreshRate
CCriticalSection m_resourceSection
std::vector< IDispResource * > m_resources
CTimer m_lostDeviceTimer
bool m_delayDispReset
XbmcThreads::EndTime m_dispResetTimer
bool m_fullscreenWillToggle
bool m_hasCursor {false}
std::optional< unsigned long > m_fullScreenMovingToScreen
Set while moving the fullscreen window to another screen. Stores the target screen id.
CCriticalSection m_critSection
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Private Attributes
NSWindowController * m_appWindowController
Additional Inherited Members
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Constructor & Destructor Documentation
CWinSystemOSX()
CWinSystemOSX::CWinSystemOSX ()
References AE::CAESinkFactory::ClearSinks(), m_appWindow, m_delayDispReset, CWinSystemBase::m_dpms, m_glView, m_lastDisplayNr, m_refreshRate, m_winEvents, CAESinkDARWINOSX::Register(), and CCocoaPowerSyscall::Register().
~CWinSystemOSX()
CWinSystemOSX::~CWinSystemOSX () override default
Member Function Documentation
AnnounceOnLostDevice()
void CWinSystemOSX::AnnounceOnLostDevice ()
References LOGDEBUG, m_resources, and m_resourceSection.
Referenced by DisplayReconfigured().
AnnounceOnResetDevice()
void CWinSystemOSX::AnnounceOnResetDevice ()
References GetScreenResolution(), LOGDEBUG, CWinSystemBase::m_gfxContext, m_lastDisplayNr, m_resources, and m_resourceSection.
Referenced by HandleOnResetDevice(), and CWinSystemOSXGL::PresentRenderImpl().
CheckDisplayChanging()
int CWinSystemOSX::CheckDisplayChanging (uint32_t flags)
CreateNewWindow()
bool CWinSystemOSX::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) override virtual
Implements CWinSystemBase.
References CheckAndUpdateCurrentMonitor(), CDVDFactoryCodec::ClearHWAccels(), VIDEOPLAYER::CRendererFactory::ClearRenderer(), GetDisplayIndex(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), GetScreenResolution(), CServiceBroker::GetSettingsComponent(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, m_appWindow, m_appWindowController, CWinSystemBase::m_bFullScreen, CWinSystemBase::m_bWindowCreated, m_glView, m_lastDisplayNr, m_name, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, m_refreshRate, name, KODI::RETRO::CRPProcessInfoOSX::Register(), VTB::CDecoder::Register(), VIDEOPLAYER::CProcessInfoOSX::Register(), CRendererVTB::Register(), CLinuxRendererGL::Register(), CScreenshotSurfaceGL::Register(), RES_WINDOW, CSettings::SETTING_VIDEOSCREEN_MONITOR, CWinSystemBase::SetWindowResolution(), and Update.
DestroyWindow()
bool CWinSystemOSX::DestroyWindow () override virtual
Reimplemented from CWinSystemBase.
DestroyWindowInternal()
bool CWinSystemOSX::DestroyWindowInternal () protected
References m_appWindow, m_appWindowController, and CWinSystemBase::m_bWindowCreated.
Referenced by DestroyWindowSystem().
DestroyWindowSystem()
bool CWinSystemOSX::DestroyWindowSystem () override virtual
Reimplemented from CWinSystemBase.
References DestroyWindowInternal(), DisplayReconfigured(), m_glView, m_lastDisplayNr, and UnblankDisplays().
disableInputEvents()
void CWinSystemOSX::disableInputEvents ()
References m_winEvents, and signalMouseExited().
enableInputEvents()
void CWinSystemOSX::enableInputEvents ()
References m_winEvents, and signalMouseEntered().
EnableVSync()
void CWinSystemOSX::EnableVSync (bool enable) protected
Referenced by CWinSystemOSXGL::ResizeWindow(), CWinSystemOSXGL::SetFullScreen(), and CWinSystemOSXGL::SetVSyncImpl().
FillInVideoModes()
void CWinSystemOSX::FillInVideoModes () protected
References CDisplaySettings::AddResolutionInfo(), ComputeVideoModeId(), CopyAllDisplayModes(), DisplayBitsPerPixelForMode(), GetDisplayID(), GetDisplayIndex(), CDisplaySettings::GetInstance(), GetScreenEdgeInsets(), CServiceBroker::GetSettingsComponent(), RESOLUTION_INFO::guiInsets, LOGINFO, CWinSystemBase::m_gfxContext, screenNameForDisplay(), CSettings::SETTING_VIDEOSCREEN_MONITOR, RESOLUTION_INFO::strId, and CWinSystemBase::UpdateDesktopResolution().
Referenced by UpdateResolutions().
FlushBuffer()
bool CWinSystemOSX::FlushBuffer () protected
References FlushBuffer(), and m_appWindow.
Referenced by FlushBuffer(), and CWinSystemOSXGL::PresentRenderImpl().
GetCGLContextObj()
CGLContextObj CWinSystemOSX::GetCGLContextObj ()
References m_appWindow.
Referenced by CRendererVTB::UploadTexture().
GetClipboardText()
std::string CWinSystemOSX::GetClipboardText (void) override virtual
Reimplemented from CWinSystemBase.
References Cocoa_Paste().
GetConnectedOutputs()
std::vector< std::string > CWinSystemOSX::GetConnectedOutputs () override virtual
Reimplemented from CWinSystemBase.
References screenNameForDisplay().
GetFullscreenWillToggle()
bool CWinSystemOSX::GetFullscreenWillToggle () inline
References m_fullscreenWillToggle.
GetOSScreenSaverImpl()
std::unique_ptr< IOSScreenSaver > CWinSystemOSX::GetOSScreenSaverImpl () override protected virtual
Reimplemented from CWinSystemBase.
GetScreenId()
unsigned int CWinSystemOSX::GetScreenId (const std::string & screen) override virtual
Get the screen ID provided the screen name.
Parameters
screen the name of the screen as presented on the application display settings
Returns
the screen index as known by the windowing system implementation (or the default screen by default)
Reimplemented from CWinSystemBase.
References GetDisplayIndex().
GetScreenResolution()
CWinSystemOSX::ScreenResolution CWinSystemOSX::GetScreenResolution (unsigned long screenIdx) protected
References GetDisplayID(), CWinSystemOSX::ScreenResolution::interlaced, CWinSystemOSX::ScreenResolution::pixelHeight, CWinSystemOSX::ScreenResolution::pixelWidth, CWinSystemOSX::ScreenResolution::refreshrate, CWinSystemOSX::ScreenResolution::resHeight, and CWinSystemOSX::ScreenResolution::resWidth.
Referenced by AnnounceOnResetDevice(), CreateNewWindow(), OnMove(), SwitchToVideoMode(), and UpdateResolutions().
GetVideoSync()
std::unique_ptr< CVideoSync > CWinSystemOSX::GetVideoSync (CVideoReferenceClock * clock) override virtual
Reimplemented from CWinSystemBase.
GetWindowDimensions()
NSRect CWinSystemOSX::GetWindowDimensions ()
References m_appWindow.
HandleOnResetDevice()
void CWinSystemOSX::HandleOnResetDevice ()
References AnnounceOnResetDevice(), CServiceBroker::GetSettingsComponent(), m_delayDispReset, and m_dispResetTimer.
Referenced by DisplayReconfigured(), and OnTimeout().
HasCursor()
bool CWinSystemOSX::HasCursor () override virtual
Reimplemented from CWinSystemBase.
References m_hasCursor.
HasValidResolution()
bool CWinSystemOSX::HasValidResolution () const
References CWinSystemBase::m_gfxContext, and RES_INVALID.
Referenced by DisplayReconfigured().
Hide()
bool CWinSystemOSX::Hide () override virtual
Reimplemented from CWinSystemBase.
InitWindowSystem()
bool CWinSystemOSX::InitWindowSystem () override virtual
Reimplemented from CWinSystemBase.
References DisplayReconfigured(), and CWinSystemBase::InitWindowSystem().
MessagePump()
bool CWinSystemOSX::MessagePump () override virtual
Reimplemented from CWinSystemBase.
References m_winEvents.
Minimize()
bool CWinSystemOSX::Minimize () override virtual
Reimplemented from CWinSystemBase.
MoveToScreen()
void CWinSystemOSX::MoveToScreen (unsigned int screenIdx) override virtual
Window was requested to move to the given screen.
Parameters
screenIdx the screen index as known by the windowing system implementation
Reimplemented from CWinSystemBase.
References CServiceBroker::GetAppMessenger(), m_appWindow, CWinSystemBase::m_bFullScreen, m_fullScreenMovingToScreen, m_fullscreenWillToggle, m_lastDisplayNr, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, and TMSG_TOGGLEFULLSCREEN.
OnChangeScreen()
void CWinSystemOSX::OnChangeScreen (unsigned int screenIdx) override virtual
Used to signal the windowing system about the change of the current screen.
Parameters
screenIdx the screen index as known by the windowing system implementation
Reimplemented from CWinSystemBase.
References CheckAndUpdateCurrentMonitor(), GetDisplayIDFromScreen(), GetDisplayIndex(), m_appWindow, CWinSystemBase::m_bFullScreen, m_lastDisplayNr, and UnblankDisplay().
OnMove()
void CWinSystemOSX::OnMove (int x, int y) override virtual
Reimplemented from CWinSystemBase.
References CheckAndUpdateCurrentMonitor(), Cocoa_CVDisplayLinkUpdate(), CServiceBroker::GetAppMessenger(), GetScreenResolution(), m_appWindow, m_fullScreenMovingToScreen, m_lastDisplayNr, m_refreshRate, TMSG_TOGGLEFULLSCREEN, and TMSG_VIDEORESIZE.
OnTimeout()
void CWinSystemOSX::OnTimeout () override virtual
Implements ITimerCallback.
References HandleOnResetDevice().
Register()
void CWinSystemOSX::Register (IDispResource * resource) override virtual
Implements CWinSystemBase.
References m_resources, and m_resourceSection.
ResizeWindow()
bool CWinSystemOSX::ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemOSXGL.
References m_appWindow, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, and Update.
Referenced by CWinSystemOSXGL::ResizeWindow(), and SetFullScreen().
Restore()
bool CWinSystemOSX::Restore () override virtual
Reimplemented from CWinSystemBase.
SendInputEvent()
void CWinSystemOSX::SendInputEvent (NSEvent * nsEvent)
References m_winEvents.
SetFullScreen()
bool CWinSystemOSX::SetFullScreen (bool fullScreen, RESOLUTION_INFO & res, bool blankOtherDisplays) override virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemOSXGL.
References BlankOtherDisplays(), GetDisplayIndex(), CServiceBroker::GetSettingsComponent(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, m_appWindow, CWinSystemBase::m_bFullScreen, m_critSection, m_fullscreenWillToggle, m_lastDisplayNr, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, ResizeWindow(), CSettings::SETTING_VIDEOSCREEN_MONITOR, SwitchToVideoMode(), and UnblankDisplays().
Referenced by CWinSystemOSXGL::SetFullScreen().
SetFullscreenWillToggle()
void CWinSystemOSX::SetFullscreenWillToggle (bool toggle) inline
References m_fullscreenWillToggle.
Show()
bool CWinSystemOSX::Show (bool raise = true) override virtual
Reimplemented from CWinSystemBase.
SignalFullScreenStateChanged()
void CWinSystemOSX::SignalFullScreenStateChanged (bool fullscreenState)
References CServiceBroker::GetAppMessenger(), m_fullScreenMovingToScreen, m_lastDisplayNr, TMSG_MOVETOSCREEN, and TMSG_TOGGLEFULLSCREEN.
signalMouseEntered()
void CWinSystemOSX::signalMouseEntered ()
References m_appWindow, m_hasCursor, and m_winEvents.
Referenced by enableInputEvents().
signalMouseExited()
void CWinSystemOSX::signalMouseExited ()
References m_appWindow, m_hasCursor, and m_winEvents.
Referenced by disableInputEvents().
StartLostDeviceTimer()
void CWinSystemOSX::StartLostDeviceTimer ()
References CTimer::IsRunning(), m_lostDeviceTimer, CTimer::Restart(), and CTimer::Start().
Referenced by DisplayReconfigured().
StopLostDeviceTimer()
void CWinSystemOSX::StopLostDeviceTimer ()
References m_lostDeviceTimer, and CTimer::Stop().
Referenced by DisplayReconfigured().
SwitchToVideoMode()
bool CWinSystemOSX::SwitchToVideoMode (RESOLUTION_INFO & res) protected
References BestMatchForMode(), Cocoa_CVDisplayLinkUpdate(), CreateMode(), CreateModeById(), err(), RESOLUTION_INFO::fRefreshRate, GetDisplayID(), GetDisplayIndex(), GetScreenResolution(), CServiceBroker::GetSettingsComponent(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, m_refreshRate, CSettings::SETTING_VIDEOSCREEN_MONITOR, and RESOLUTION_INFO::strId.
Referenced by SetFullScreen().
Unregister()
void CWinSystemOSX::Unregister (IDispResource * resource) override virtual
Implements CWinSystemBase.
References m_resources, and m_resourceSection.
UpdateResolutions()
void CWinSystemOSX::UpdateResolutions () override virtual
Reimplemented from CWinSystemBase.
References CDisplaySettings::ApplyCalibrations(), CDisplaySettings::ClearCustomResolutions(), ComputeVideoModeId(), FillInVideoModes(), GetDisplayIndex(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), GetScreenEdgeInsets(), GetScreenResolution(), CServiceBroker::GetSettingsComponent(), RESOLUTION_INFO::guiInsets, RES_DESKTOP, screenNameForDisplay(), CSettings::SETTING_VIDEOSCREEN_MONITOR, RESOLUTION_INFO::strId, CWinSystemBase::UpdateDesktopResolution(), and CWinSystemBase::UpdateResolutions().
WindowChangedScreen()
void CWinSystemOSX::WindowChangedScreen ()
Member Data Documentation
m_appWindow
NSWindow* CWinSystemOSX::m_appWindow protected
Referenced by CreateNewWindow(), CWinSystemOSX(), DestroyWindowInternal(), FlushBuffer(), GetCGLContextObj(), GetWindowDimensions(), MoveToScreen(), OnChangeScreen(), OnMove(), ResizeWindow(), SetFullScreen(), signalMouseEntered(), and signalMouseExited().
m_appWindowController
NSWindowController* CWinSystemOSX::m_appWindowController private
Referenced by CreateNewWindow(), and DestroyWindowInternal().
m_critSection
CCriticalSection CWinSystemOSX::m_critSection protected
Referenced by SetFullScreen().
m_delayDispReset
bool CWinSystemOSX::m_delayDispReset protected
Referenced by CWinSystemOSX(), HandleOnResetDevice(), and CWinSystemOSXGL::PresentRenderImpl().
m_dispResetTimer
XbmcThreads::EndTime CWinSystemOSX::m_dispResetTimer protected
Referenced by HandleOnResetDevice(), and CWinSystemOSXGL::PresentRenderImpl().
m_fullScreenMovingToScreen
std::optional<unsigned long> CWinSystemOSX::m_fullScreenMovingToScreen protected
Set while moving the fullscreen window to another screen. Stores the target screen id.
Referenced by MoveToScreen(), OnMove(), and SignalFullScreenStateChanged().
m_fullscreenWillToggle
bool CWinSystemOSX::m_fullscreenWillToggle protected
Referenced by GetFullscreenWillToggle(), MoveToScreen(), SetFullScreen(), and SetFullscreenWillToggle().
m_glView
OSXGLView* CWinSystemOSX::m_glView protected
Referenced by CreateNewWindow(), CWinSystemOSX(), and DestroyWindowSystem().
m_hasCursor
bool CWinSystemOSX::m_hasCursor {false} protected
Referenced by HasCursor(), signalMouseEntered(), and signalMouseExited().
m_lastDisplayNr
unsigned long CWinSystemOSX::m_lastDisplayNr protected
Referenced by AnnounceOnResetDevice(), CreateNewWindow(), CWinSystemOSX(), DestroyWindowSystem(), MoveToScreen(), OnChangeScreen(), OnMove(), SetFullScreen(), and SignalFullScreenStateChanged().
m_lostDeviceTimer
CTimer CWinSystemOSX::m_lostDeviceTimer protected
Referenced by StartLostDeviceTimer(), and StopLostDeviceTimer().
m_name
std::string CWinSystemOSX::m_name protected
Referenced by CreateNewWindow().
m_refreshRate
double CWinSystemOSX::m_refreshRate protected
Referenced by CreateNewWindow(), CWinSystemOSX(), OnMove(), and SwitchToVideoMode().
m_resources
std::vector<IDispResource*> CWinSystemOSX::m_resources protected
Referenced by AnnounceOnLostDevice(), AnnounceOnResetDevice(), Register(), and Unregister().
m_resourceSection
CCriticalSection CWinSystemOSX::m_resourceSection protected
Referenced by AnnounceOnLostDevice(), AnnounceOnResetDevice(), Register(), and Unregister().
m_winEvents
std::unique_ptr<CWinEventsOSX> CWinSystemOSX::m_winEvents protected
Referenced by CWinSystemOSX(), disableInputEvents(), enableInputEvents(), MessagePump(), SendInputEvent(), signalMouseEntered(), and signalMouseExited().
The documentation for this class was generated from the following files:
WinSystemOSX.h
WinSystemOSX.mm