Kodi Documentation: LocalizeStrings.cpp File Reference
LocalizeStrings.cpp File Reference
#include "LocalizeStrings.h"
#include "addons/LanguageResource.h"
#include "filesystem/Directory.h"
#include "filesystem/SpecialProtocol.h"
#include "threads/SharedSection.h"
#include "utils/CharsetConverter.h"
#include "utils/POUtils.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/log.h"
#include <mutex>
#include <shared_mutex>
Functions
static bool LoadPO (const std::string &filename, std::map< uint32_t, LocStr > &strings, std::string &encoding, uint32_t offset=0, bool bSourceLanguage=false)
Tries to load ids and strings from a strings.po file to the strings map. It should only be called from the LoadStr2Mem function to have a fallback.
static bool LoadStr2Mem (const std::string &pathname_in, const std::string &language, std::map< uint32_t, LocStr > &strings, std::string &encoding, uint32_t offset=0)
Loads language ids and strings to memory map strings.
static bool LoadWithFallback (const std::string &path, const std::string &language, std::map< uint32_t, LocStr > &strings)
Function Documentation
LoadPO()
static bool LoadPO (const std::string & filename, std::map< uint32_t, LocStr > & strings, std::string & encoding, uint32_t offset = 0, bool bSourceLanguage = false) static
Tries to load ids and strings from a strings.po file to the strings map. It should only be called from the LoadStr2Mem function to have a fallback.
Parameters
pathname The directory name, where we look for the strings file.
strings [out] The resulting strings map.
encoding Encoding of the strings. For PO files we only use utf-8.
offset An offset value to place strings from the id value.
bSourceLanguage If we are loading the source English strings.po.
Returns
false if no strings.po file was loaded.
Todo:
implement reading of non-id based string entries from the PO files. These entries would go into a separate memory map, using hash codes for fast look-up. With this memory map we can implement using gettext(), ngettext(), pgettext() calls, so that we don't have to use new IDs for new strings. Even we can start converting the ID based calls to normal gettext calls.
Todo:
implement reading of non-id based pluralized string entries from the PO files. We can store the pluralforms for each language, in the langinfo.xml files.
References CPODocument::GetEntryID(), CPODocument::GetEntryType(), CPODocument::GetMsgid(), CPODocument::GetMsgstr(), CPODocument::GetNextEntry(), id, ID_FOUND, CPODocument::LoadFile(), CLog::Log(), LOGDEBUG, MSGID_FOUND, MSGID_PLURAL_FOUND, and CPODocument::ParseEntry().
Referenced by LoadStr2Mem().
LoadStr2Mem()
static bool LoadStr2Mem (const std::string & pathname_in, const std::string & language, std::map< uint32_t, LocStr > & strings, std::string & encoding, uint32_t offset = 0) static
Loads language ids and strings to memory map strings.
Parameters
pathname The directory name, where we look for the strings file.
language We load the strings for this language. Fallback language is always English.
strings [out] The resulting strings map.
encoding Encoding of the strings. For PO files we only use utf-8.
offset An offset value to place strings from the id value.
Returns
false if no strings.po file was loaded.
References URIUtils::AddFileToFolder(), KODI::UTILS::StringUtils::EqualsNoCase(), exists(), XFILE::CDirectory::Exists(), ADDON::CLanguageResource::FindLegacyLanguage(), LANGUAGE_DEFAULT, LANGUAGE_OLD_DEFAULT, LoadPO(), and CSpecialProtocol::TranslatePathConvertCase().
Referenced by LoadWithFallback().
LoadWithFallback()
static bool LoadWithFallback (const std::string & path, const std::string & language, std::map< uint32_t, LocStr > & strings) static
References KODI::UTILS::StringUtils::EqualsNoCase(), LANGUAGE_DEFAULT, and LoadStr2Mem().
Referenced by CLocalizeStrings::Load(), CLocalizeStrings::LoadAddonStrings(), and CLocalizeStrings::LoadSkinStrings().