Kodi Documentation: PVR::CPVRGUIActionsTimers Class Reference
PVR::CPVRGUIActionsTimers Class Reference
#include <PVRGUIActionsTimers.h>
Public Member Functions
CPVRGUIActionsTimers ()
~CPVRGUIActionsTimers () override=default
bool AddTimer (bool bRadio) const
Open the timer settings dialog to create a new tv or radio timer.
bool AddTimer (const CFileItem &item, bool bShowTimerSettings) const
Create a new timer, either interactive or non-interactive.
bool AddTimer (const std::shared_ptr< CPVRTimerInfoTag > &item) const
Add a timer to the client. Doesn't add the timer to the container. The backend will do this.
bool AddTimerRule (const CFileItem &item, bool bShowTimerSettings, bool bFallbackToOneShotTimer) const
Create a new timer rule, either interactive or non-interactive.
bool ToggleTimer (const CFileItem &item) const
Creates or deletes a timer for the given epg tag.
bool ToggleTimerState (const CFileItem &item) const
Toggles a given timer's enabled/disabled state.
bool EditTimer (const CFileItem &item) const
Open the timer settings dialog to edit an existing timer.
bool EditTimerRule (const CFileItem &item) const
Open the timer settings dialog to edit an existing timer rule.
std::shared_ptr< CFileItem > GetTimerRule (const CFileItem &item) const
Get the timer rule for a given timer.
bool DeleteTimer (const CFileItem &item) const
Delete a timer, always showing a confirmation dialog.
bool DeleteTimer (const std::shared_ptr< CPVRTimerInfoTag > &timer, bool bIsRecording, bool bDeleteRule) const
Delete a timer or timer rule, showing a confirmation dialog in case a timer currently recording shall be deleted.
bool DeleteTimerRule (const CFileItem &item) const
Delete a timer rule, always showing a confirmation dialog.
bool ToggleRecordingOnPlayingChannel ()
Toggle recording on the currently playing channel, if any.
bool SetRecordingOnChannel (const std::shared_ptr< CPVRChannel > &channel, bool bOnOff)
Start or stop recording on a given channel.
bool StopRecording (const CFileItem &item) const
Stop a currently active recording, always showing a confirmation dialog.
bool AddReminder (const CFileItem &item) const
Create a new reminder timer, non-interactive.
void AnnounceReminders () const
Announce due reminders, if any.
Public Member Functions inherited from PVR::IPVRComponent
virtual ~IPVRComponent ()=default
Private Member Functions
CPVRGUIActionsTimers (const CPVRGUIActionsTimers &)=delete
CPVRGUIActionsTimers const & operator= (CPVRGUIActionsTimers const &)=delete
bool ShowTimerSettings (const std::shared_ptr< CPVRTimerInfoTag > &timer) const
Open the timer settings dialog.
bool AddTimer (const CFileItem &item, bool bCreateRule, bool bShowTimerSettings, bool bFallbackToOneShotTimer) const
Add a timer or timer rule, either interactive or non-interactive.
bool DeleteTimer (const CFileItem &item, bool bIsRecording, bool bDeleteRule) const
Delete a timer or timer rule, always showing a confirmation dialog.
bool ConfirmDeleteTimer (const std::shared_ptr< const CPVRTimerInfoTag > &timer, bool &bDeleteRule) const
Open a dialog to confirm timer delete.
bool ConfirmStopRecording (const std::shared_ptr< const CPVRTimerInfoTag > &timer) const
Open a dialog to confirm stop recording.
void AnnounceReminder (const std::shared_ptr< CPVRTimerInfoTag > &timer) const
Announce and process a reminder timer.
Private Attributes
CPVRSettings m_settings
bool m_bReminderAnnouncementRunning {false}
Constructor & Destructor Documentation
CPVRGUIActionsTimers() [1/2]
CPVRGUIActionsTimers::CPVRGUIActionsTimers ()
References CSettings::SETTING_PVRRECORD_INSTANTRECORDACTION, CSettings::SETTING_PVRRECORD_INSTANTRECORDTIME, CSettings::SETTING_PVRREMINDERS_AUTOCLOSEDELAY, CSettings::SETTING_PVRREMINDERS_AUTORECORD, and CSettings::SETTING_PVRREMINDERS_AUTOSWITCH.
~CPVRGUIActionsTimers()
PVR::CPVRGUIActionsTimers::~CPVRGUIActionsTimers () override default
CPVRGUIActionsTimers() [2/2]
PVR::CPVRGUIActionsTimers::CPVRGUIActionsTimers (const CPVRGUIActionsTimers &) private delete
Member Function Documentation
AddReminder()
bool CPVRGUIActionsTimers::AddReminder (const CFileItem & item) const
Create a new reminder timer, non-interactive.
Parameters
item containing epg data to create a reminder timer for. item must be an epg tag.
Returns
true, if the timer was created successfully, false otherwise.
References AddTimer(), PVR::CPVRTimerInfoTag::CreateReminderFromEpg(), PVR::CPVRItem::GetEpgInfoTag(), CServiceBroker::GetPVRManager(), LOGERROR, KODI::MESSAGING::HELPERS::ShowOKDialogText(), and PVR::Timers.
AddTimer() [1/4]
bool CPVRGUIActionsTimers::AddTimer (bool bRadio) const
Open the timer settings dialog to create a new tv or radio timer.
Parameters
bRadio indicates whether a radio or tv timer shall be created.
Returns
true on success, false otherwise.
References AddTimer(), and ShowTimerSettings().
Referenced by AddReminder(), AddTimer(), AddTimer(), AddTimer(), AddTimer(), and AddTimerRule().
AddTimer() [2/4]
bool CPVRGUIActionsTimers::AddTimer (const CFileItem & item, bool bCreateRule, bool bShowTimerSettings, bool bFallbackToOneShotTimer) const private
Add a timer or timer rule, either interactive or non-interactive.
Parameters
item containing epg data to create a timer or timer rule for. item must be an epg tag or a channel.
bCreateteRule denotes whether to create a one-shot timer or a timer rule.
bShowTimerSettings is used to control whether a settings dialog will be opened prior creating the timer or timer rule.
bFallbackToOneShotTimer if bCreateteRule is true and no timer rule can be created, try to create a one-shot timer instead.
Returns
true, if the timer or timer rule was created successfully, false otherwise.
References AddTimer(), PVR::CPVRTimerInfoTag::CreateFromEpg(), PVR::CPVRTimerInfoTag::CreateInstantTimerTag(), PVR::CPVRTimerInfoTag::CreateTimerTag(), PVR::CPVRTimerInfoTag::DEFAULT_PVRRECORD_INSTANTRECORDTIME, PVR::CPVRItem::GetEpgInfoTag(), PVR::CPVRSettings::GetIntValue(), CServiceBroker::GetPVRManager(), GetTimerRule(), CDateTime::GetUTCDateTime(), CDateTime::IsValid(), LOGERROR, m_settings, CSettings::SETTING_PVRRECORD_INSTANTRECORDTIME, KODI::MESSAGING::HELPERS::ShowOKDialogText(), ShowTimerSettings(), PVR::SUCCESS, PVR::Timers, and PVR::CPVRManager::Timers().
AddTimer() [3/4]
bool CPVRGUIActionsTimers::AddTimer (const CFileItem & item, bool bShowTimerSettings) const
Create a new timer, either interactive or non-interactive.
Parameters
item containing epg data to create a timer for. item must be an epg tag or a channel.
bShowTimerSettings is used to control whether a settings dialog will be opened prior creating the timer.
Returns
true, if the timer was created successfully, false otherwise.
References AddTimer().
AddTimer() [4/4]
bool CPVRGUIActionsTimers::AddTimer (const std::shared_ptr< CPVRTimerInfoTag > & item) const
Add a timer to the client. Doesn't add the timer to the container. The backend will do this.
Returns
True if it was sent correctly, false if not.
References AddTimer(), CServiceBroker::GetPVRManager(), LOGERROR, KODI::MESSAGING::HELPERS::ShowOKDialogText(), PVR::SUCCESS, and PVR::Timers.
AddTimerRule()
bool CPVRGUIActionsTimers::AddTimerRule (const CFileItem & item, bool bShowTimerSettings, bool bFallbackToOneShotTimer) const
Create a new timer rule, either interactive or non-interactive.
Parameters
item containing epg data to create a timer rule for. item must be an epg tag or a channel.
bShowTimerSettings is used to control whether a settings dialog will be opened prior creating the timer rule.
bFallbackToOneShotTimer if no timer rule can be created, try to create a one-shot timer instead.
Returns
true, if the timer rule was created successfully, false otherwise.
References AddTimer().
AnnounceReminder()
void CPVRGUIActionsTimers::AnnounceReminder (const std::shared_ptr< CPVRTimerInfoTag > & timer) const private
Announce and process a reminder timer.
Parameters
timer The reminder timer.
References anonymous_namespace{PVRGUIActionsTimers.cpp}::AddEventLogEntry(), CGUIDialogProgress::CHOICE_NONE, CGUIWindow::Close(), PVR::CPVRTimerInfoTag::CreateFromEpg(), PVR::CPVRTimerInfoTag::CreateTimerTag(), g_localizeStrings, PVR::CPVRManager::Get(), CLocalizeStrings::Get(), anonymous_namespace{PVRGUIActionsTimers.cpp}::GetAnnouncerText(), CGUIDialogProgress::GetChoice(), PVR::CPVRManager::GetClient(), CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CDateTime::GetUTCDateTime(), CGUIComponent::GetWindowManager(), LOGERROR, CGUIDialogProgress::Open(), CGUIDialogProgress::Progress(), CGUIDialogProgress::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogProgress::SetPercentage(), CGUIDialogBoxBase::SetText(), CSettings::SETTING_PVRREMINDERS_AUTOCLOSEDELAY, CSettings::SETTING_PVRREMINDERS_AUTORECORD, CSettings::SETTING_PVRREMINDERS_AUTOSWITCH, CGUIDialogProgress::ShowChoice(), text, and WINDOW_DIALOG_PROGRESS.
AnnounceReminders()
void CPVRGUIActionsTimers::AnnounceReminders () const
Announce due reminders, if any.
References PVR::AnnounceReminder, CServiceBroker::GetPVRManager(), and PVR::CPVRManager::Timers().
ConfirmDeleteTimer()
bool CPVRGUIActionsTimers::ConfirmDeleteTimer (const std::shared_ptr< const CPVRTimerInfoTag > & timer, bool & bDeleteRule) const private
Open a dialog to confirm timer delete.
Parameters
timer the timer to delete.
bDeleteRule in: ignored. out, for one shot timer scheduled by a timer rule: true to also delete the timer rule that has scheduled this timer, false to only delete the one shot timer. out, for one shot timer not scheduled by a timer rule: ignored
Returns
true, to proceed with delete, false otherwise.
References CServiceBroker::GetPVRManager(), CGUIDialogYesNo::ShowAndGetInput(), and PVR::Timers.
ConfirmStopRecording()
bool CPVRGUIActionsTimers::ConfirmStopRecording (const std::shared_ptr< const CPVRTimerInfoTag > & timer) const private
Open a dialog to confirm stop recording.
Parameters
timer the recording to stop (actually the timer to delete).
Returns
true, to proceed with delete, false otherwise.
References CGUIDialogYesNo::ShowAndGetInput().
DeleteTimer() [1/3]
bool CPVRGUIActionsTimers::DeleteTimer (const CFileItem & item) const
Delete a timer, always showing a confirmation dialog.
Parameters
item containing a timer to delete. item must be a timer, an epg tag or a channel.
Returns
true, if the timer was deleted successfully, false otherwise.
DeleteTimer() [2/3]
bool CPVRGUIActionsTimers::DeleteTimer (const CFileItem & item, bool bIsRecording, bool bDeleteRule) const private
Delete a timer or timer rule, always showing a confirmation dialog.
Parameters
item containing a timer or timer rule to delete. item must be a timer, an epg tag or a channel.
bIsRecording denotes whether the timer is currently recording (controls correct confirmation dialog).
bDeleteRule denotes to delete a timer rule. For convenience, one can pass a timer created by a rule.
Returns
true, if the timer or timer rule was deleted successfully, false otherwise.
References CServiceBroker::GetPVRManager(), PVR::CPVRItem::GetTimerInfoTag(), LOGERROR, KODI::MESSAGING::HELPERS::ShowOKDialogText(), PVR::Timers, and PVR::CPVRManager::Timers().
DeleteTimer() [3/3]
bool CPVRGUIActionsTimers::DeleteTimer (const std::shared_ptr< CPVRTimerInfoTag > & timer, bool bIsRecording, bool bDeleteRule) const
Delete a timer or timer rule, showing a confirmation dialog in case a timer currently recording shall be deleted.
Parameters
timer containing a timer or timer rule to delete.
bIsRecording denotes whether the timer is currently recording (controls correct confirmation dialog).
bDeleteRule denotes to delete a timer rule. For convenience, one can pass a timer created by a rule.
Returns
true, if the timer or timer rule was deleted successfully, false otherwise.
References CServiceBroker::GetPVRManager(), LOGERROR, KODI::MESSAGING::HELPERS::ShowOKDialogText(), KODI::MESSAGING::HELPERS::ShowYesNoDialogText(), and PVR::CPVRManager::Timers().
DeleteTimerRule()
bool CPVRGUIActionsTimers::DeleteTimerRule (const CFileItem & item) const
Delete a timer rule, always showing a confirmation dialog.
Parameters
item containing a timer rule to delete. item must be a timer, an epg tag or a channel.
Returns
true, if the timer rule was deleted successfully, false otherwise.
EditTimer()
bool CPVRGUIActionsTimers::EditTimer (const CFileItem & item) const
Open the timer settings dialog to edit an existing timer.
Parameters
item containing an epg tag or a timer.
Returns
true on success, false otherwise.
References LOGERROR.
EditTimerRule()
bool CPVRGUIActionsTimers::EditTimerRule (const CFileItem & item) const
Open the timer settings dialog to edit an existing timer rule.
Parameters
item containing an epg tag or a timer.
Returns
true on success, false otherwise.
GetTimerRule()
std::shared_ptr< CFileItem > CPVRGUIActionsTimers::GetTimerRule (const CFileItem & item) const
Get the timer rule for a given timer.
Parameters
item containing an item to query the timer rule for. item must be a timer or an epg tag.
Returns
The timer rule item, or nullptr if none was found.
References CFileItem::GetEPGInfoTag(), CServiceBroker::GetPVRManager(), CFileItem::GetPVRTimerInfoTag(), CFileItem::HasEPGInfoTag(), CFileItem::HasPVRTimerInfoTag(), and PVR::CPVRManager::Timers().
Referenced by AddTimer().
operator=()
CPVRGUIActionsTimers const & PVR::CPVRGUIActionsTimers::operator= (CPVRGUIActionsTimers const &) private delete
SetRecordingOnChannel()
bool CPVRGUIActionsTimers::SetRecordingOnChannel (const std::shared_ptr< CPVRChannel > & channel, bool bOnOff)
Start or stop recording on a given channel.
Parameters
channel the channel to start/stop recording.
bOnOff True to start recording, false to stop.
Returns
True if the recording was started or stopped successfully, false otherwise.
References anonymous_namespace{PVRGUIActionsTimers.cpp}::ASK, PVR::CPVRTimerInfoTag::CreateFromEpg(), PVR::CPVRTimerInfoTag::CreateInstantTimerTag(), g_localizeStrings, CLocalizeStrings::Get(), PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), PVR::CPVRManager::IsParentalLocked(), LOGERROR, anonymous_namespace{PVRGUIActionsTimers.cpp}::NONE, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_120_MINUTES, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_30_MINUTES, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_60_MINUTES, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_CURRENT_SHOW, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_INSTANTRECORDTIME, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_NEXT_SHOW, CSettings::SETTING_PVRRECORD_INSTANTRECORDACTION, CSettings::SETTING_PVRRECORD_INSTANTRECORDTIME, KODI::MESSAGING::HELPERS::ShowOKDialogText(), PVR::Timers, and PVR::CPVRManager::Timers().
ShowTimerSettings()
bool CPVRGUIActionsTimers::ShowTimerSettings (const std::shared_ptr< CPVRTimerInfoTag > & timer) const private
Open the timer settings dialog.
Parameters
timer containing the timer the settings shall be displayed for.
Returns
true, if the dialog was ended successfully, false otherwise.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialogSettingsBase::IsConfirmed(), LOGERROR, CGUIDialog::Open(), PVR::CGUIDialogPVRTimerSettings::SetTimer(), and WINDOW_DIALOG_PVR_TIMER_SETTING.
Referenced by AddTimer(), and AddTimer().
StopRecording()
bool CPVRGUIActionsTimers::StopRecording (const CFileItem & item) const
Stop a currently active recording, always showing a confirmation dialog.
Parameters
item containing a recording to stop. item must be a timer, an epg tag or a channel.
Returns
true, if the recording was stopped successfully, false otherwise.
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::TriggerRecordingsUpdate().
ToggleRecordingOnPlayingChannel()
bool CPVRGUIActionsTimers::ToggleRecordingOnPlayingChannel ()
Toggle recording on the currently playing channel, if any.
Returns
True if the recording was started or stopped successfully, false otherwise.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::PlaybackState(), and PVR::Timers.
ToggleTimer()
bool CPVRGUIActionsTimers::ToggleTimer (const CFileItem & item) const
Creates or deletes a timer for the given epg tag.
Parameters
item containing an epg tag.
Returns
true on success, false otherwise.
References CFileItem::HasEPGInfoTag().
ToggleTimerState()
bool CPVRGUIActionsTimers::ToggleTimerState (const CFileItem & item) const
Toggles a given timer's enabled/disabled state.
Parameters
item containing a timer.
Returns
true on success, false otherwise.
References CServiceBroker::GetPVRManager(), CFileItem::GetPVRTimerInfoTag(), CFileItem::HasPVRTimerInfoTag(), PVR_TIMER_STATE_DISABLED, PVR_TIMER_STATE_SCHEDULED, KODI::MESSAGING::HELPERS::ShowOKDialogText(), and PVR::Timers.
Member Data Documentation
m_bReminderAnnouncementRunning
bool PVR::CPVRGUIActionsTimers::m_bReminderAnnouncementRunning {false} mutable private
m_settings
CPVRSettings PVR::CPVRGUIActionsTimers::m_settings private
Referenced by AddTimer().
The documentation for this class was generated from the following files:
PVRGUIActionsTimers.h
PVRGUIActionsTimers.cpp