Kodi Documentation: PVR::CPVRGUIAnyTimerInfo Class Reference
PVR::CPVRGUIAnyTimerInfo Class Reference
#include <PVRGUITimerInfo.h>
Public Member Functions
CPVRGUIAnyTimerInfo ()=default
Public Member Functions inherited from PVR::CPVRGUITimerInfo
CPVRGUITimerInfo ()
virtual ~CPVRGUITimerInfo ()=default
void ResetProperties ()
void UpdateTimersCache ()
void UpdateTimersToggle ()
void UpdateNextTimer ()
const std::string & GetActiveTimerTitle () const
const std::string & GetActiveTimerChannelName () const
const std::string & GetActiveTimerChannelIcon () const
const std::string & GetActiveTimerDateTime () const
const std::string & GetNextTimerTitle () const
const std::string & GetNextTimerChannelName () const
const std::string & GetNextTimerChannelIcon () const
const std::string & GetNextTimerDateTime () const
const std::string & GetNextTimer () const
bool HasTimers () const
bool HasRecordingTimers () const
bool HasNonRecordingTimers () const
Private Member Functions
int AmountActiveTimers () override
int AmountActiveRecordings () override
std::vector< std::shared_ptr< CPVRTimerInfoTag > > GetActiveRecordings () override
std::shared_ptr< CPVRTimerInfoTag > GetNextActiveTimer () override
Constructor & Destructor Documentation
CPVRGUIAnyTimerInfo()
PVR::CPVRGUIAnyTimerInfo::CPVRGUIAnyTimerInfo () default
Member Function Documentation
AmountActiveRecordings()
int CPVRGUIAnyTimerInfo::AmountActiveRecordings () override private virtual
Implements PVR::CPVRGUITimerInfo.
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::Timers().
AmountActiveTimers()
int CPVRGUIAnyTimerInfo::AmountActiveTimers () override private virtual
Implements PVR::CPVRGUITimerInfo.
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::Timers().
GetActiveRecordings()
std::vector< std::shared_ptr< CPVRTimerInfoTag > > CPVRGUIAnyTimerInfo::GetActiveRecordings () override private virtual
Implements PVR::CPVRGUITimerInfo.
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::Timers().
GetNextActiveTimer()
std::shared_ptr< CPVRTimerInfoTag > CPVRGUIAnyTimerInfo::GetNextActiveTimer () override private virtual
Implements PVR::CPVRGUITimerInfo.
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::Timers().
The documentation for this class was generated from the following files:
PVRGUITimerInfo.h
PVRGUITimerInfo.cpp