Kodi Documentation: CAESinkDARWINTVOS Class Reference
CAESinkDARWINTVOS Class Reference
#include <AESinkDARWINTVOS.h>
Public Member Functions
const char * GetName () override
CAESinkDARWINTVOS ()
~CAESinkDARWINTVOS () override=default
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
double GetCacheTotal () override
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void Drain () override
bool HasVolume () override
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual double GetLatency ()
virtual void AddPause (unsigned int millis)
instruct the sink to add a pause
virtual void SetVolume (float volume)
Static Public Member Functions
static void Register ()
static void EnumerateDevicesEx (AEDeviceInfoList &list, bool force)
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
Private Attributes
CAEDeviceInfo m_info
AEAudioFormat m_format
CAAudioUnitSink * m_audioSink = nullptr
Static Private Attributes
static AEDeviceInfoList m_devices
Constructor & Destructor Documentation
CAESinkDARWINTVOS()
CAESinkDARWINTVOS::CAESinkDARWINTVOS ()
~CAESinkDARWINTVOS()
CAESinkDARWINTVOS::~CAESinkDARWINTVOS () override default
Member Function Documentation
AddPackets()
unsigned int CAESinkDARWINTVOS::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References AE_FMT_FLOAT, data(), m_audioSink, AEAudioFormat::m_dataFormat, m_format, AEAudioFormat::m_frameSize, and CAAudioUnitSink::write().
Create()
std::unique_ptr< IAESink > CAESinkDARWINTVOS::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
Deinitialize()
void CAESinkDARWINTVOS::Deinitialize () override virtual
Implements IAESink.
References m_audioSink.
Drain()
void CAESinkDARWINTVOS::Drain () override virtual
Reimplemented from IAESink.
References CAAudioUnitSink::drain(), and m_audioSink.
EnumerateDevicesEx()
void CAESinkDARWINTVOS::EnumerateDevicesEx (AEDeviceInfoList & list, bool force) static
References EnumerateDevices(), and m_devices.
Referenced by Register().
GetCacheTotal()
double CAESinkDARWINTVOS::GetCacheTotal () override virtual
Implements IAESink.
References CAAudioUnitSink::buffertime(), and m_audioSink.
GetDelay()
void CAESinkDARWINTVOS::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References m_audioSink, AEDelayStatus::SetDelay(), and CAAudioUnitSink::updatedelay().
GetName()
const char * CAESinkDARWINTVOS::GetName () inline override virtual
Implements IAESink.
HasVolume()
bool CAESinkDARWINTVOS::HasVolume () override virtual
Reimplemented from IAESink.
Initialize()
bool CAESinkDARWINTVOS::Initialize (AEAudioFormat & format, std::string & device) override virtual
Implements IAESink.
References CAAudioUnitSink::activate(), AE_FMT_FLOAT, AE_FMT_RAW, AE_FMT_S16LE, CAChannel_PCM_6CHAN, CAChannel_PCM_8CHAN, CAChannel_PCM_DD5_1, CAChannelMap, CAEUtil::DataFormatToBits(), getAudioRoute(), CLog::Log(), LOGDEBUG, m_audioSink, m_devices, m_format, m_info, CAAudioUnitSink::open(), CAAudioUnitSink::sampletrate(), CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_EAC3, and StreamDescriptionToString().
Register()
void CAESinkDARWINTVOS::Register () static
References Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
Referenced by CWinSystemTVOS::CWinSystemTVOS().
Member Data Documentation
m_audioSink
CAAudioUnitSink* CAESinkDARWINTVOS::m_audioSink = nullptr private
Referenced by AddPackets(), Deinitialize(), Drain(), GetCacheTotal(), GetDelay(), and Initialize().
m_devices
AEDeviceInfoList CAESinkDARWINTVOS::m_devices static private
Referenced by EnumerateDevicesEx(), and Initialize().
m_format
AEAudioFormat CAESinkDARWINTVOS::m_format private
Referenced by AddPackets(), and Initialize().
m_info
CAEDeviceInfo CAESinkDARWINTVOS::m_info private
Referenced by Initialize().
The documentation for this class was generated from the following files:
AESinkDARWINTVOS.h
AESinkDARWINTVOS.mm