Kodi Documentation: CGUIFont Class Reference
CGUIFont Class Reference
Guilib classes » Graphics and Screen » Textures and Fonts
#include <GUIFont.h>
Public Member Functions
CGUIFont (const std::string &strFontName, uint32_t style, KODI::UTILS::COLOR::Color textColor, KODI::UTILS::COLOR::Color shadowColor, float lineSpacing, float origHeight, CGUIFontTTF *font)
virtual ~CGUIFont ()
std::string & GetFontName ()
void DrawText (float x, float y, KODI::UTILS::COLOR::Color color, KODI::UTILS::COLOR::Color shadowColor, const vecText &text, uint32_t alignment, float maxPixelWidth)
void DrawText (float x, float y, const std::vector< KODI::UTILS::COLOR::Color > &colors, KODI::UTILS::COLOR::Color shadowColor, const vecText &text, uint32_t alignment, float maxPixelWidth)
void DrawScrollingText (float x, float y, const std::vector< KODI::UTILS::COLOR::Color > &colors, KODI::UTILS::COLOR::Color shadowColor, const vecText &text, uint32_t alignment, float maxPixelWidth, const CScrollInfo &scrollInfo)
bool UpdateScrollInfo (const vecText &text, CScrollInfo &scrollInfo)
float GetTextWidth (const vecText &text)
float GetCharWidth (character_t ch)
float GetTextHeight (int numLines) const
float GetTextBaseLine () const
float GetLineHeight () const
float GetScaleFactor () const
get font scale factor (rendered height / original height)
void Begin ()
void End ()
uint32_t GetStyle () const
CGUIFontTTF * GetFont () const
void SetFont (CGUIFontTTF *font)
Protected Attributes
std::string m_strFontName
uint32_t m_style
KODI::UTILS::COLOR::Color m_shadowColor
KODI::UTILS::COLOR::Color m_textColor
float m_lineSpacing
float m_origHeight
CGUIFontTTF * m_font
Private Member Functions
bool ClippedRegionIsEmpty (CGraphicContext &context, float x, float y, float width, uint32_t alignment) const
Constructor & Destructor Documentation
CGUIFont()
CGUIFont::CGUIFont (const std::string & strFontName, uint32_t style, KODI::UTILS::COLOR::Color textColor, KODI::UTILS::COLOR::Color shadowColor, float lineSpacing, float origHeight, CGUIFontTTF * font)
References CGUIFontTTF::AddReference(), FONT_STYLE_MASK, m_font, m_lineSpacing, m_origHeight, m_shadowColor, m_style, and m_textColor.
~CGUIFont()
CGUIFont::~CGUIFont () virtual
References m_font, and CGUIFontTTF::RemoveReference().
Member Function Documentation
Begin()
void CGUIFont::Begin ()
References CGUIFontTTF::Begin(), and m_font.
Referenced by CGUITextBox::Render(), CGUITextLayout::Render(), CGUITextLayout::RenderOutline(), and CGUITextLayout::RenderScrolling().
ClippedRegionIsEmpty()
bool CGUIFont::ClippedRegionIsEmpty (CGraphicContext & context, float x, float y, float width, uint32_t alignment) const private
References CGraphicContext::GetGUIScaleY(), CGUIFontTTF::GetLineHeight(), CGUIFontTTF::GetTextHeight(), m_font, m_lineSpacing, CGraphicContext::SetClipRegion(), XBFONT_CENTER_X, and XBFONT_CENTER_Y.
Referenced by DrawScrollingText(), and DrawText().
DrawScrollingText()
void CGUIFont::DrawScrollingText (float x, float y, const std::vector< KODI::UTILS::COLOR::Color > & colors, KODI::UTILS::COLOR::Color shadowColor, const vecText & text, uint32_t alignment, float maxPixelWidth, const CScrollInfo & scrollInfo)
References ClippedRegionIsEmpty(), color, CGUIFontTTF::DrawTextInternal(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIScaleX(), GetTextWidth(), CServiceBroker::GetWinSystem(), m_font, CScrollInfo::m_pixelPos, CScrollInfo::m_pixelSpeed, m_shadowColor, CScrollInfo::m_suffix, m_textColor, CScrollInfo::m_textWidth, CScrollInfo::m_totalWidth, CScrollInfo::m_waitTime, CScrollInfo::m_widthValid, CGraphicContext::MergeColor(), CGraphicContext::RestoreClipRegion(), ROUND, and text.
Referenced by CGUIRSSControl::Render(), and CGUITextLayout::RenderScrolling().
DrawText() [1/2]
void CGUIFont::DrawText (float x, float y, const std::vector< KODI::UTILS::COLOR::Color > & colors, KODI::UTILS::COLOR::Color shadowColor, const vecText & text, uint32_t alignment, float maxPixelWidth)
References ClippedRegionIsEmpty(), color, CGUIFontTTF::DrawTextInternal(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIScaleX(), CServiceBroker::GetWinSystem(), m_font, m_shadowColor, m_textColor, CGraphicContext::MergeColor(), CGraphicContext::RestoreClipRegion(), ROUND, and text.
DrawText() [2/2]
void CGUIFont::DrawText (float x, float y, KODI::UTILS::COLOR::Color color, KODI::UTILS::COLOR::Color shadowColor, const vecText & text, uint32_t alignment, float maxPixelWidth) inline
References color, DrawText(), and text.
Referenced by CGUITextLayout::DrawText(), DrawText(), CGUITextBox::Render(), CGUITextLayout::Render(), and CGUITextLayout::RenderOutline().
End()
void CGUIFont::End ()
References CGUIFontTTF::End(), and m_font.
Referenced by CGUITextBox::Render(), CGUITextLayout::Render(), CGUITextLayout::RenderOutline(), and CGUITextLayout::RenderScrolling().
GetCharWidth()
float CGUIFont::GetCharWidth (character_t ch)
References CGUIFontTTF::GetCharWidthInternal(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIScaleX(), CServiceBroker::GetWinSystem(), and m_font.
Referenced by CGUIFadeLabelControl::Process(), CGUIRSSControl::Process(), and CGUIDialogKeyboardGeneric::ShowWordList().
GetFont()
CGUIFontTTF * CGUIFont::GetFont () const inline
References m_font.
Referenced by XBMCAddon::xbmcgui::ControlLabel::Create(), XBMCAddon::xbmcgui::ControlEdit::Create(), XBMCAddon::xbmcgui::ControlFadeLabel::Create(), XBMCAddon::xbmcgui::ControlTextBox::Create(), XBMCAddon::xbmcgui::ControlButton::Create(), XBMCAddon::xbmcgui::ControlRadioButton::Create(), CGUIControlFactory::Create(), and CGUIButtonControl::PythonSetLabel().
GetFontName()
std::string & CGUIFont::GetFontName ()
References m_strFontName.
Referenced by XBMCAddon::xbmcgui::Window::GetControlById(), GUIFontManager::GetDefaultFont(), and GUIFontManager::GetFont().
GetLineHeight()
float CGUIFont::GetLineHeight () const
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIScaleY(), CGUIFontTTF::GetLineHeight(), CServiceBroker::GetWinSystem(), m_font, and m_lineSpacing.
Referenced by CGUITextLayout::LineBreakText(), CGUITextLayout::Render(), CGUITextLayout::RenderOutline(), CGUITextLayout::RenderScrolling(), CGUITextBox::UpdateInfo(), and CGUITextLayout::WrapText().
GetScaleFactor()
float CGUIFont::GetScaleFactor () const
get font scale factor (rendered height / original height)
References CGUIFontTTF::GetFontHeight(), m_font, and m_origHeight.
GetStyle()
uint32_t CGUIFont::GetStyle () const inline
References m_style.
Referenced by CGUITextLayout::GetTextWidth(), CGUIEditControl::SetStyledText(), CGUITextLayout::UpdateCommon(), and CGUILabelControl::UpdateInfo().
GetTextBaseLine()
float CGUIFont::GetTextBaseLine () const
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIScaleY(), CGUIFontTTF::GetTextBaseLine(), CServiceBroker::GetWinSystem(), and m_font.
Referenced by CGUITextLayout::RenderOutline().
GetTextHeight()
float CGUIFont::GetTextHeight (int numLines) const
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIScaleY(), CGUIFontTTF::GetTextHeight(), CServiceBroker::GetWinSystem(), m_font, and m_lineSpacing.
Referenced by CGUIRSSControl::CalcRenderRegion(), CGUITextLayout::CalcTextExtent(), CGUIEditControl::CGUIEditControl(), CGUITextBox::Render(), CGUITextLayout::Render(), CGUITextLayout::RenderOutline(), CGUITextLayout::RenderScrolling(), and CGUITextBox::UpdateInfo().
GetTextWidth()
float CGUIFont::GetTextWidth (const vecText & text)
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIScaleX(), CGUIFontTTF::GetTextWidthInternal(), CServiceBroker::GetWinSystem(), m_font, and text.
Referenced by CGUITextLayout::CalcTextExtent(), DrawScrollingText(), CGUIDialogKeyboardGeneric::GetStringWidth(), CGUITextLayout::GetTextWidth(), CGUITextLayout::GetTextWidth(), CGUITextLayout::RenderOutline(), UpdateScrollInfo(), and CGUITextLayout::WrapText().
SetFont()
void CGUIFont::SetFont (CGUIFontTTF * font)
References CGUIFontTTF::AddReference(), m_font, and CGUIFontTTF::RemoveReference().
UpdateScrollInfo()
bool CGUIFont::UpdateScrollInfo (const vecText & text, CScrollInfo & scrollInfo)
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIScaleX(), CScrollInfo::GetPixelsPerFrame(), GetTextWidth(), CServiceBroker::GetWinSystem(), CScrollInfo::m_loopCount, CScrollInfo::m_pixelPos, CScrollInfo::m_suffix, CScrollInfo::m_textWidth, CScrollInfo::m_totalWidth, CScrollInfo::m_waitTime, CScrollInfo::m_widthValid, and text.
Referenced by CGUIRSSControl::Process(), and CGUITextLayout::UpdateScrollinfo().
Member Data Documentation
m_font
CGUIFontTTF* CGUIFont::m_font protected
Referenced by Begin(), CGUIFont(), ClippedRegionIsEmpty(), DrawScrollingText(), DrawText(), End(), GetCharWidth(), GetFont(), GetLineHeight(), GetScaleFactor(), GetTextBaseLine(), GetTextHeight(), GetTextWidth(), SetFont(), and ~CGUIFont().
m_lineSpacing
float CGUIFont::m_lineSpacing protected
Referenced by CGUIFont(), ClippedRegionIsEmpty(), GetLineHeight(), and GetTextHeight().
m_origHeight
float CGUIFont::m_origHeight protected
Referenced by CGUIFont(), and GetScaleFactor().
m_shadowColor
KODI::UTILS::COLOR::Color CGUIFont::m_shadowColor protected
Referenced by CGUIFont(), DrawScrollingText(), and DrawText().
m_strFontName
std::string CGUIFont::m_strFontName protected
Referenced by GetFontName().
m_style
uint32_t CGUIFont::m_style protected
Referenced by CGUIFont(), and GetStyle().
m_textColor
KODI::UTILS::COLOR::Color CGUIFont::m_textColor protected
Referenced by CGUIFont(), DrawScrollingText(), and DrawText().
The documentation for this class was generated from the following files:
GUIFont.h
GUIFont.cpp