Kodi Documentation: TimeUtils.h File Reference
TimeUtils.h File Reference
#include <stdint.h>
#include <string>
#include <time.h>
Classes
class CTimeUtils
Functions
int64_t CurrentHostCounter (void)
int64_t CurrentHostFrequency (void)
Function Documentation
CurrentHostCounter()
int64_t CurrentHostCounter (void)
References int64_t(), and _LARGE_INTEGER::QuadPart.
Referenced by CAESinkAUDIOTRACK::AddPackets(), CGUIControlProfilerItem::BeginRender(), CGUIControlProfilerItem::BeginVisibility(), BitstreamStats::CalculateBitrate(), VDPAU::CDecoder::Decode(), CGUIControlProfilerItem::EndRender(), CGUIControlProfilerItem::EndVisibility(), AEDelayStatus::GetDelay(), CAESinkAUDIOTRACK::GetDelay(), CXBMCApp::GetFrameLatencyMs(), CVideoReferenceClock::GetTime(), KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::HandlePresentation(), CVideoSyncIos::IosVblankHandler(), VDPAU::CDecoder::Open(), CVideoReferenceClock::Process(), CMediaCodecVideoBuffer::ReleaseOutputBuffer(), VDPAU::CDecoder::Render(), CVideoSyncD3D::Run(), KODI::WINDOWING::X11::CVideoSyncGLX::Run(), KODI::WINDOWING::X11::CVideoSyncOML::Run(), AEDelayStatus::SetDelay(), CVideoSyncAndroid::Setup(), CVideoSyncGbm::Setup(), CVideoSyncIos::Setup(), CVideoSyncTVos::Setup(), BitstreamStats::Start(), CVideoSyncTVos::TVosVblankHandler(), and CVideoSyncOsx::VblankHandler().
CurrentHostFrequency()
int64_t CurrentHostFrequency (void)
References int64_t(), and _LARGE_INTEGER::QuadPart.
Referenced by CAESinkAUDIOTRACK::AddPackets(), BitstreamStats::BitstreamStats(), CDVDClock::CDVDClock(), CGUIControlProfiler::CGUIControlProfiler(), CVideoReferenceClock::CVideoReferenceClock(), CVideoSyncAndroid::FrameCallback(), AEDelayStatus::GetDelay(), CAESinkWASAPI::GetDelay(), CVideoSyncIos::IosVblankHandler(), VDPAU::CDecoder::Render(), CAESinkDARWINOSX::renderCallback(), CVideoSyncD3D::Run(), and CVideoSyncTVos::TVosVblankHandler().