Kodi Documentation: CWebSocket Class Reference
CWebSocket Class Reference abstract
#include <WebSocket.h>
Public Member Functions
CWebSocket ()
virtual ~CWebSocket ()
int GetVersion ()
WebSocketState GetState ()
virtual bool Handshake (const char *data, size_t length, std::string &response)=0
virtual const CWebSocketMessage * Handle (const char *&buffer, size_t &length, bool &send)
virtual const CWebSocketMessage * Send (WebSocketFrameOpcode opcode, const char *data=NULL, uint32_t length=0)
virtual const CWebSocketFrame * Ping (const char *data=NULL) const =0
virtual const CWebSocketFrame * Pong (const char *data, uint32_t length) const =0
virtual const CWebSocketFrame * Close (WebSocketCloseReason reason=WebSocketCloseNormal, const std::string &message="")=0
virtual void Fail ()=0
Protected Member Functions
virtual CWebSocketFrame * GetFrame (const char *data, uint64_t length)=0
virtual CWebSocketFrame * GetFrame (WebSocketFrameOpcode opcode, const char *data=NULL, uint32_t length=0, bool final=true, bool masked=false, int32_t mask=0, int8_t extension=0)=0
virtual CWebSocketMessage * GetMessage ()=0
Protected Attributes
int m_version
WebSocketState m_state
CWebSocketMessage * m_message
Constructor & Destructor Documentation
CWebSocket()
CWebSocket::CWebSocket () inline
References m_message, m_state, and WebSocketStateNotConnected.
~CWebSocket()
virtual CWebSocket::~CWebSocket () inline virtual
References m_message.
Member Function Documentation
Close()
virtual const CWebSocketFrame * CWebSocket::Close (WebSocketCloseReason reason = WebSocketCloseNormal, const std::string & message = "") pure virtual
Implemented in CWebSocketV13, and CWebSocketV8.
Fail()
virtual void CWebSocket::Fail () pure virtual
Implemented in CWebSocketV8.
GetFrame() [1/2]
virtual CWebSocketFrame * CWebSocket::GetFrame (const char * data, uint64_t length) protected pure virtual
Implemented in CWebSocketV8.
Referenced by Handle(), and Send().
GetFrame() [2/2]
virtual CWebSocketFrame * CWebSocket::GetFrame (WebSocketFrameOpcode opcode, const char * data = NULL, uint32_t length = 0, bool final = true, bool masked = false, int32_t mask = 0, int8_t extension = 0) protected pure virtual
Implemented in CWebSocketV8.
GetMessage()
virtual CWebSocketMessage * CWebSocket::GetMessage () protected pure virtual
Implemented in CWebSocketV8.
Referenced by Handle(), and Send().
GetState()
WebSocketState CWebSocket::GetState () inline
References m_state.
Referenced by JSONRPC::CTCPServer::CWebSocketClient::Closing().
GetVersion()
int CWebSocket::GetVersion () inline
References m_version.
Handle()
const CWebSocketMessage * CWebSocket::Handle (const char *& buffer, size_t & length, bool & send) virtual
References CWebSocketMessage::AddFrame(), Close(), CWebSocketFrame::GetApplicationData(), GetFrame(), CWebSocketFrame::GetFrameLength(), CWebSocketFrame::GetLength(), GetMessage(), CWebSocketFrame::GetOpcode(), CWebSocketMessage::IsComplete(), CWebSocketFrame::IsControlFrame(), CWebSocketFrame::IsFinal(), CWebSocketFrame::IsValid(), CLog::Log(), LOGINFO, m_message, m_state, Pong(), WebSocketBinaryFrame, WebSocketConnectionClose, WebSocketContinuationFrame, WebSocketPing, WebSocketPong, WebSocketStateClosed, WebSocketStateClosing, WebSocketStateConnected, WebSocketStateHandshaking, WebSocketStateNotConnected, WebSocketTextFrame, and WebSocketUnknownFrame.
Handshake()
virtual bool CWebSocket::Handshake (const char * data, size_t length, std::string & response) pure virtual
Implemented in CWebSocketV13, and CWebSocketV8.
Referenced by CWebSocketManager::Handle().
Ping()
virtual const CWebSocketFrame * CWebSocket::Ping (const char * data = NULL) const pure virtual
Implemented in CWebSocketV8.
Pong()
virtual const CWebSocketFrame * CWebSocket::Pong (const char * data, uint32_t length) const pure virtual
Implemented in CWebSocketV8.
Referenced by Handle().
Send()
const CWebSocketMessage * CWebSocket::Send (WebSocketFrameOpcode opcode, const char * data = NULL, uint32_t length = 0) virtual
References CWebSocketMessage::AddFrame(), data(), GetFrame(), GetMessage(), CWebSocketMessage::IsComplete(), CWebSocketFrame::IsValid(), CLog::Log(), and LOGINFO.
Member Data Documentation
m_message
CWebSocketMessage* CWebSocket::m_message protected
Referenced by CWebSocket(), Handle(), and ~CWebSocket().
m_state
WebSocketState CWebSocket::m_state protected
Referenced by CWebSocketV8::close(), CWebSocketV13::Close(), CWebSocketV8::Close(), CWebSocket(), CWebSocketV8::Fail(), GetState(), Handle(), CWebSocketV13::Handshake(), and CWebSocketV8::Handshake().
m_version
int CWebSocket::m_version protected
Referenced by CWebSocketV13::CWebSocketV13(), CWebSocketV8::CWebSocketV8(), and GetVersion().
The documentation for this class was generated from the following files:
WebSocket.h
WebSocket.cpp