Kodi Documentation: DllDvdNavInterface Class Reference
DllDvdNavInterface Class Reference abstract
#include <DllDvdNav.h>
Public Member Functions
virtual ~DllDvdNavInterface ()=default
virtual dvdnav_status_t dvdnav_open (dvdnav_t **dest, const char *path)=0
virtual dvdnav_status_t dvdnav_open2 (dvdnav_t **dest, void *, const dvdnav_logger_cb *, const char *path)=0
virtual dvdnav_status_t dvdnav_open_stream (dvdnav_t **dest, void *stream, dvdnav_stream_cb *stream_cb)=0
virtual dvdnav_status_t dvdnav_open_stream2 (dvdnav_t **dest, void *stream, const dvdnav_logger_cb *, dvdnav_stream_cb *stream_cb)=0
virtual dvdnav_status_t dvdnav_close (dvdnav_t *self)=0
virtual dvdnav_status_t dvdnav_reset (dvdnav_t *self)=0
virtual const char * dvdnav_err_to_string (dvdnav_t *self)=0
virtual dvdnav_status_t dvdnav_set_readahead_flag (dvdnav_t *self, int32_t read_ahead_flag)=0
virtual dvdnav_status_t dvdnav_set_PGC_positioning_flag (dvdnav_t *self, int32_t pgc_based_flag)=0
virtual dvdnav_status_t dvdnav_get_next_cache_block (dvdnav_t *self, uint8_t **buf, int32_t *event, int32_t *len)=0
virtual dvdnav_status_t dvdnav_free_cache_block (dvdnav_t *self, unsigned char *buf)=0
virtual dvdnav_status_t dvdnav_still_skip (dvdnav_t *self)=0
virtual dvdnav_status_t dvdnav_wait_skip (dvdnav_t *self)=0
virtual dvdnav_status_t dvdnav_stop (dvdnav_t *self)=0
virtual dvdnav_status_t dvdnav_button_select (dvdnav_t *self, pci_t *pci, int32_t button)=0
virtual dvdnav_status_t dvdnav_button_activate (dvdnav_t *self, pci_t *pci)=0
virtual dvdnav_status_t dvdnav_upper_button_select (dvdnav_t *self, pci_t *pci)=0
virtual dvdnav_status_t dvdnav_lower_button_select (dvdnav_t *self, pci_t *pci)=0
virtual dvdnav_status_t dvdnav_right_button_select (dvdnav_t *self, pci_t *pci)=0
virtual dvdnav_status_t dvdnav_left_button_select (dvdnav_t *self, pci_t *pci)=0
virtual dvdnav_status_t dvdnav_sector_search (dvdnav_t *self, uint64_t offset, int32_t origin)=0
virtual pci_t * dvdnav_get_current_nav_pci (dvdnav_t *self)=0
virtual dsi_t * dvdnav_get_current_nav_dsi (dvdnav_t *self)=0
virtual dvdnav_status_t dvdnav_get_position (dvdnav_t *self, uint32_t *pos, uint32_t *len)=0
virtual dvdnav_status_t dvdnav_current_title_info (dvdnav_t *self, int32_t *title, int32_t *part)=0
virtual dvdnav_status_t dvdnav_spu_language_select (dvdnav_t *self, char *code)=0
virtual dvdnav_status_t dvdnav_audio_language_select (dvdnav_t *self, char *code)=0
virtual dvdnav_status_t dvdnav_menu_language_select (dvdnav_t *self, char *code)=0
virtual int8_t dvdnav_is_domain_vts (dvdnav_t *self)=0
virtual int8_t dvdnav_get_active_spu_stream (dvdnav_t *self)=0
virtual int8_t dvdnav_get_spu_logical_stream (dvdnav_t *self, uint8_t subp_num)=0
virtual uint16_t dvdnav_spu_stream_to_lang (dvdnav_t *self, uint8_t stream)=0
virtual dvdnav_status_t dvdnav_get_current_highlight (dvdnav_t *self, int32_t *button)=0
virtual dvdnav_status_t dvdnav_menu_call (dvdnav_t *self, DVDMenuID_t menu)=0
virtual dvdnav_status_t dvdnav_prev_pg_search (dvdnav_t *self)=0
virtual dvdnav_status_t dvdnav_next_pg_search (dvdnav_t *self)=0
virtual dvdnav_status_t dvdnav_get_highlight_area (pci_t *nav_pci, int32_t button, int32_t mode, dvdnav_highlight_area_t *highlight)=0
virtual dvdnav_status_t dvdnav_go_up (dvdnav_t *self)=0
virtual int8_t dvdnav_get_active_audio_stream (dvdnav_t *self)=0
virtual uint16_t dvdnav_audio_stream_to_lang (dvdnav_t *self, uint8_t stream)=0
virtual int8_t dvdnav_get_audio_logical_stream (dvdnav_t *self, uint8_t audio_num)=0
virtual dvdnav_status_t dvdnav_set_region_mask (dvdnav_t *self, int32_t region_mask)=0
virtual uint8_t dvdnav_get_video_aspect (dvdnav_t *self)=0
virtual uint8_t dvdnav_get_video_scale_permission (dvdnav_t *self)=0
virtual dvdnav_status_t dvdnav_get_number_of_titles (dvdnav_t *self, int32_t *titles)=0
virtual dvdnav_status_t dvdnav_get_number_of_parts (dvdnav_t *self, int32_t title, int32_t *parts)=0
virtual dvdnav_status_t dvdnav_title_play (dvdnav_t *self, int32_t title)=0
virtual dvdnav_status_t dvdnav_part_play (dvdnav_t *self, int32_t title, int32_t part)=0
virtual dvdnav_status_t dvdnav_get_audio_attr (dvdnav_t *self, int32_t streamid, audio_attr_t *audio_attributes)=0
virtual dvdnav_status_t dvdnav_get_spu_attr (dvdnav_t *self, int32_t streamid, subp_attr_t *stitle_attributes)=0
virtual dvdnav_status_t dvdnav_jump_to_sector_by_time (dvdnav_t *self, uint64_t offset, int32_t origin)=0
virtual int64_t dvdnav_convert_time (dvd_time_t *time)=0
virtual dvdnav_status_t dvdnav_get_angle_info (dvdnav_t *self, int32_t *current_angle, int32_t *number_of_angles)=0
virtual dvdnav_status_t dvdnav_angle_change (dvdnav_t *self, int32_t angle)=0
virtual dvdnav_status_t dvdnav_mouse_activate (dvdnav_t *self, pci_t *pci, int32_t x, int32_t y)=0
virtual dvdnav_status_t dvdnav_mouse_select (dvdnav_t *self, pci_t *pci, int32_t x, int32_t y)=0
virtual dvdnav_status_t dvdnav_get_title_string (dvdnav_t *self, const char **title_str)=0
virtual dvdnav_status_t dvdnav_get_serial_string (dvdnav_t *self, const char **serial_str)=0
virtual const char * dvdnav_get_volid_string (dvdnav_t *self)=0
virtual dvdnav_status_t dvdnav_get_disk_region_mask (dvdnav_t *self, int32_t *region_mask)=0
virtual uint32_t dvdnav_describe_title_chapters (dvdnav_t *self, uint32_t title, uint64_t **times, uint64_t *duration)=0
virtual int64_t dvdnav_get_current_time (dvdnav_t *self)=0
virtual int dvdnav_get_video_resolution (dvdnav_t *self, uint32_t *width, uint32_t *height)=0
virtual int8_t dvdnav_get_number_of_streams (dvdnav_t *self, dvdnav_stream_type_t stream_type)=0
virtual dvdnav_status_t dvdnav_toggle_spu_stream (dvdnav_t *self, uint8_t visibility)=0
virtual dvdnav_status_t dvdnav_set_active_stream (dvdnav_t *self, uint8_t stream_num, dvdnav_stream_type_t stream_type)=0
virtual dvdnav_status_t dvdnav_program_play (dvdnav_t *self, int32_t title, int32_t pgcn, int32_t pgn)=0
virtual dvdnav_status_t dvdnav_current_title_program (dvdnav_t *self, int32_t *title, int32_t *pgcn, int32_t *pgn)=0
Constructor & Destructor Documentation
~DllDvdNavInterface()
virtual DllDvdNavInterface::~DllDvdNavInterface () virtual default
Member Function Documentation
dvdnav_angle_change()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_angle_change (dvdnav_t * self, int32_t angle) pure virtual
Referenced by CDVDInputStreamNavigator::SetAngle(), and CDVDInputStreamNavigator::SetState().
dvdnav_audio_language_select()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_audio_language_select (dvdnav_t * self, char * code) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_audio_stream_to_lang()
virtual uint16_t DllDvdNavInterface::dvdnav_audio_stream_to_lang (dvdnav_t * self, uint8_t stream) pure virtual
dvdnav_button_activate()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_button_activate (dvdnav_t * self, pci_t * pci) pure virtual
Referenced by CDVDInputStreamNavigator::ActivateButton().
dvdnav_button_select()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_button_select (dvdnav_t * self, pci_t * pci, int32_t button) pure virtual
Referenced by CDVDInputStreamNavigator::CheckButtons(), and CDVDInputStreamNavigator::SelectButton().
dvdnav_close()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_close (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::Close().
dvdnav_convert_time()
virtual int64_t DllDvdNavInterface::dvdnav_convert_time (dvd_time_t * time) pure virtual
dvdnav_current_title_info()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_current_title_info (dvdnav_t * self, int32_t * title, int32_t * part) pure virtual
Referenced by CDVDInputStreamNavigator::ProcessBlock().
dvdnav_current_title_program()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_current_title_program (dvdnav_t * self, int32_t * title, int32_t * pgcn, int32_t * pgn) pure virtual
Referenced by CDVDInputStreamNavigator::FillDVDState().
dvdnav_describe_title_chapters()
virtual uint32_t DllDvdNavInterface::dvdnav_describe_title_chapters (dvdnav_t * self, uint32_t title, uint64_t ** times, uint64_t * duration) pure virtual
Referenced by CDVDInputStreamNavigator::ProcessBlock().
dvdnav_err_to_string()
virtual const char * DllDvdNavInterface::dvdnav_err_to_string (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::Close(), CDVDInputStreamNavigator::FillDVDState(), CDVDInputStreamNavigator::GetActiveAngle(), CDVDInputStreamNavigator::GetCurrentButton(), CDVDInputStreamNavigator::GetVideoResolution(), CDVDInputStreamNavigator::Open(), CDVDInputStreamNavigator::PosTime(), CDVDInputStreamNavigator::ProcessBlock(), CDVDInputStreamNavigator::SeekChapter(), CDVDInputStreamNavigator::SetActiveAudioStream(), and CDVDInputStreamNavigator::SetActiveSubtitleStream().
dvdnav_free_cache_block()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_free_cache_block (dvdnav_t * self, unsigned char * buf) pure virtual
Referenced by CDVDInputStreamNavigator::ProcessBlock().
dvdnav_get_active_audio_stream()
virtual int8_t DllDvdNavInterface::dvdnav_get_active_audio_stream (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::GetActiveAudioStream().
dvdnav_get_active_spu_stream()
virtual int8_t DllDvdNavInterface::dvdnav_get_active_spu_stream (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::GetActiveSubtitleStream(), and CDVDInputStreamNavigator::IsSubtitleStreamEnabled().
dvdnav_get_angle_info()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_angle_info (dvdnav_t * self, int32_t * current_angle, int32_t * number_of_angles) pure virtual
Referenced by CDVDInputStreamNavigator::GetActiveAngle(), and CDVDInputStreamNavigator::GetAngleCount().
dvdnav_get_audio_attr()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_audio_attr (dvdnav_t * self, int32_t streamid, audio_attr_t * audio_attributes) pure virtual
Referenced by CDVDInputStreamNavigator::GetAudioStreamInfo().
dvdnav_get_audio_logical_stream()
virtual int8_t DllDvdNavInterface::dvdnav_get_audio_logical_stream (dvdnav_t * self, uint8_t audio_num) pure virtual
Referenced by CDVDInputStreamNavigator::GetActiveAudioStream().
dvdnav_get_current_highlight()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_current_highlight (dvdnav_t * self, int32_t * button) pure virtual
Referenced by CDVDInputStreamNavigator::GetCurrentButton().
dvdnav_get_current_nav_dsi()
virtual dsi_t * DllDvdNavInterface::dvdnav_get_current_nav_dsi (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::ProcessBlock().
dvdnav_get_current_nav_pci()
virtual pci_t * DllDvdNavInterface::dvdnav_get_current_nav_pci (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::ActivateButton(), CDVDInputStreamNavigator::CheckButtons(), CDVDInputStreamNavigator::GetCurrentButtonInfo(), CDVDInputStreamNavigator::GetTotalButtons(), CDVDInputStreamNavigator::OnDown(), CDVDInputStreamNavigator::OnLeft(), CDVDInputStreamNavigator::OnMouseClick(), CDVDInputStreamNavigator::OnMouseMove(), CDVDInputStreamNavigator::OnRight(), CDVDInputStreamNavigator::OnUp(), CDVDInputStreamNavigator::ProcessBlock(), and CDVDInputStreamNavigator::SelectButton().
dvdnav_get_current_time()
virtual int64_t DllDvdNavInterface::dvdnav_get_current_time (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::ProcessBlock().
dvdnav_get_disk_region_mask()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_disk_region_mask (dvdnav_t * self, int32_t * region_mask) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_get_highlight_area()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_highlight_area (pci_t * nav_pci, int32_t button, int32_t mode, dvdnav_highlight_area_t * highlight) pure virtual
Referenced by CDVDInputStreamNavigator::GetCurrentButtonInfo().
dvdnav_get_next_cache_block()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_next_cache_block (dvdnav_t * self, uint8_t ** buf, int32_t * event, int32_t * len) pure virtual
Referenced by CDVDInputStreamNavigator::Open(), and CDVDInputStreamNavigator::ProcessBlock().
dvdnav_get_number_of_parts()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_number_of_parts (dvdnav_t * self, int32_t title, int32_t * parts) pure virtual
Referenced by CDVDInputStreamNavigator::ProcessBlock().
dvdnav_get_number_of_streams()
virtual int8_t DllDvdNavInterface::dvdnav_get_number_of_streams (dvdnav_t * self, dvdnav_stream_type_t stream_type) pure virtual
Referenced by CDVDInputStreamNavigator::GetAudioStreamCount(), and CDVDInputStreamNavigator::GetSubTitleStreamCount().
dvdnav_get_number_of_titles()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_number_of_titles (dvdnav_t * self, int32_t * titles) pure virtual
Referenced by CDVDInputStreamNavigator::ProcessBlock().
dvdnav_get_position()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_position (dvdnav_t * self, uint32_t * pos, uint32_t * len) pure virtual
Referenced by CDVDInputStreamNavigator::ProcessBlock().
dvdnav_get_serial_string()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_serial_string (dvdnav_t * self, const char ** serial_str) pure virtual
Referenced by CDVDInputStreamNavigator::GetDVDSerialString().
dvdnav_get_spu_attr()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_spu_attr (dvdnav_t * self, int32_t streamid, subp_attr_t * stitle_attributes) pure virtual
Referenced by CDVDInputStreamNavigator::GetSubtitleStreamInfo().
dvdnav_get_spu_logical_stream()
virtual int8_t DllDvdNavInterface::dvdnav_get_spu_logical_stream (dvdnav_t * self, uint8_t subp_num) pure virtual
Referenced by CDVDInputStreamNavigator::GetActiveSubtitleStream().
dvdnav_get_title_string()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_get_title_string (dvdnav_t * self, const char ** title_str) pure virtual
Referenced by CDVDInputStreamNavigator::GetDVDTitleString().
dvdnav_get_video_aspect()
virtual uint8_t DllDvdNavInterface::dvdnav_get_video_aspect (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::GetVideoAspectRatio().
dvdnav_get_video_resolution()
virtual int DllDvdNavInterface::dvdnav_get_video_resolution (dvdnav_t * self, uint32_t * width, uint32_t * height) pure virtual
Referenced by CDVDInputStreamNavigator::GetVideoResolution().
dvdnav_get_video_scale_permission()
virtual uint8_t DllDvdNavInterface::dvdnav_get_video_scale_permission (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::GetVideoAspectRatio().
dvdnav_get_volid_string()
virtual const char * DllDvdNavInterface::dvdnav_get_volid_string (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::GetDVDVolIdString().
dvdnav_go_up()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_go_up (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::OnBack().
dvdnav_is_domain_vts()
virtual int8_t DllDvdNavInterface::dvdnav_is_domain_vts (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::GetState(), and CDVDInputStreamNavigator::ProcessBlock().
dvdnav_jump_to_sector_by_time()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_jump_to_sector_by_time (dvdnav_t * self, uint64_t offset, int32_t origin) pure virtual
Referenced by CDVDInputStreamNavigator::PosTime().
dvdnav_left_button_select()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_left_button_select (dvdnav_t * self, pci_t * pci) pure virtual
Referenced by CDVDInputStreamNavigator::OnLeft().
dvdnav_lower_button_select()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_lower_button_select (dvdnav_t * self, pci_t * pci) pure virtual
Referenced by CDVDInputStreamNavigator::OnDown().
dvdnav_menu_call()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_menu_call (dvdnav_t * self, DVDMenuID_t menu) pure virtual
Referenced by CDVDInputStreamNavigator::OnMenu(), and CDVDInputStreamNavigator::Open().
dvdnav_menu_language_select()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_menu_language_select (dvdnav_t * self, char * code) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_mouse_activate()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_mouse_activate (dvdnav_t * self, pci_t * pci, int32_t x, int32_t y) pure virtual
Referenced by CDVDInputStreamNavigator::OnMouseClick().
dvdnav_mouse_select()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_mouse_select (dvdnav_t * self, pci_t * pci, int32_t x, int32_t y) pure virtual
Referenced by CDVDInputStreamNavigator::OnMouseMove().
dvdnav_next_pg_search()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_next_pg_search (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::OnNext(), and CDVDInputStreamNavigator::SeekChapter().
dvdnav_open()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_open (dvdnav_t ** dest, const char * path) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_open2()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_open2 (dvdnav_t ** dest, void * , const dvdnav_logger_cb * , const char * path) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_open_stream()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_open_stream (dvdnav_t ** dest, void * stream, dvdnav_stream_cb * stream_cb) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_open_stream2()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_open_stream2 (dvdnav_t ** dest, void * stream, const dvdnav_logger_cb * , dvdnav_stream_cb * stream_cb) pure virtual
dvdnav_part_play()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_part_play (dvdnav_t * self, int32_t title, int32_t part) pure virtual
Referenced by CDVDInputStreamNavigator::SeekChapter().
dvdnav_prev_pg_search()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_prev_pg_search (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::OnPrevious(), and CDVDInputStreamNavigator::SeekChapter().
dvdnav_program_play()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_program_play (dvdnav_t * self, int32_t title, int32_t pgcn, int32_t pgn) pure virtual
dvdnav_reset()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_reset (dvdnav_t * self) pure virtual
dvdnav_right_button_select()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_right_button_select (dvdnav_t * self, pci_t * pci) pure virtual
Referenced by CDVDInputStreamNavigator::OnRight().
dvdnav_sector_search()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_sector_search (dvdnav_t * self, uint64_t offset, int32_t origin) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_set_active_stream()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_set_active_stream (dvdnav_t * self, uint8_t stream_num, dvdnav_stream_type_t stream_type) pure virtual
Referenced by CDVDInputStreamNavigator::SetActiveAudioStream(), and CDVDInputStreamNavigator::SetActiveSubtitleStream().
dvdnav_set_PGC_positioning_flag()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_set_PGC_positioning_flag (dvdnav_t * self, int32_t pgc_based_flag) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_set_readahead_flag()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_set_readahead_flag (dvdnav_t * self, int32_t read_ahead_flag) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_set_region_mask()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_set_region_mask (dvdnav_t * self, int32_t region_mask) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_spu_language_select()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_spu_language_select (dvdnav_t * self, char * code) pure virtual
Referenced by CDVDInputStreamNavigator::Open().
dvdnav_spu_stream_to_lang()
virtual uint16_t DllDvdNavInterface::dvdnav_spu_stream_to_lang (dvdnav_t * self, uint8_t stream) pure virtual
dvdnav_still_skip()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_still_skip (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::SkipStill().
dvdnav_stop()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_stop (dvdnav_t * self) pure virtual
dvdnav_title_play()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_title_play (dvdnav_t * self, int32_t title) pure virtual
dvdnav_toggle_spu_stream()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_toggle_spu_stream (dvdnav_t * self, uint8_t visibility) pure virtual
Referenced by CDVDInputStreamNavigator::EnableSubtitleStream().
dvdnav_upper_button_select()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_upper_button_select (dvdnav_t * self, pci_t * pci) pure virtual
Referenced by CDVDInputStreamNavigator::OnUp().
dvdnav_wait_skip()
virtual dvdnav_status_t DllDvdNavInterface::dvdnav_wait_skip (dvdnav_t * self) pure virtual
Referenced by CDVDInputStreamNavigator::SkipWait().
The documentation for this class was generated from the following file:
DllDvdNav.h