Kodi Documentation: AddonToKodiFuncTable_kodi Struct Reference
AddonToKodiFuncTable_kodi Struct Reference
#include <general.h>
Public Attributes
char *(* unknown_to_utf8)(void *kodiBase, const char *source, bool *ret, bool failOnBadChar)
char *(* get_language)(void *kodiBase, int format, bool region)
bool(* queue_notification)(void *kodiBase, int type, const char *header, const char *message, const char *imageFile, unsigned int displayTime, bool withSound, unsigned int messageTime)
void(* get_md5)(void *kodiBase, const char *text, char *md5)
char *(* get_region)(void *kodiBase, const char *id)
void(* get_free_mem)(void *kodiBase, long *free, long *total, bool as_bytes)
int(* get_global_idle_time)(void *kodiBase)
bool(* is_addon_avilable)(void *kodiBase, const char *id, char **version, bool *enabled)
void(* kodi_version)(void *kodiBase, char **compile_name, int *major, int *minor, char **revision, char **tag, char **tagversion)
char *(* get_current_skin_id)(void *kodiBase)
bool(* get_keyboard_layout)(void *kodiBase, char **layout_name, int modifier_key, struct AddonKeyboardKeyTable *layout)
bool(* change_keyboard_layout)(void *kodiBase, char **layout_name)
Member Data Documentation
change_keyboard_layout
bool(* AddonToKodiFuncTable_kodi::change_keyboard_layout) (void *kodiBase, char **layout_name)
Referenced by kodi::ChangeKeyboardLayout(), and ADDON::Interface_General::Init().
get_current_skin_id
char *(* AddonToKodiFuncTable_kodi::get_current_skin_id) (void *kodiBase)
Referenced by kodi::GetCurrentSkinId(), and ADDON::Interface_General::Init().
get_free_mem
void(* AddonToKodiFuncTable_kodi::get_free_mem) (void *kodiBase, long *free, long *total, bool as_bytes)
Referenced by kodi::GetFreeMem(), and ADDON::Interface_General::Init().
get_global_idle_time
int(* AddonToKodiFuncTable_kodi::get_global_idle_time) (void *kodiBase)
Referenced by kodi::GetGlobalIdleTime(), and ADDON::Interface_General::Init().
get_keyboard_layout
bool(* AddonToKodiFuncTable_kodi::get_keyboard_layout) (void *kodiBase, char **layout_name, int modifier_key, struct AddonKeyboardKeyTable *layout)
Referenced by kodi::GetKeyboardLayout(), and ADDON::Interface_General::Init().
get_language
char *(* AddonToKodiFuncTable_kodi::get_language) (void *kodiBase, int format, bool region)
Referenced by ADDON::Interface_General::Init().
get_md5
void(* AddonToKodiFuncTable_kodi::get_md5) (void *kodiBase, const char *text, char *md5)
Referenced by ADDON::Interface_General::Init().
get_region
char *(* AddonToKodiFuncTable_kodi::get_region) (void *kodiBase, const char *id)
Referenced by kodi::GetRegion(), and ADDON::Interface_General::Init().
is_addon_avilable
bool(* AddonToKodiFuncTable_kodi::is_addon_avilable) (void *kodiBase, const char *id, char **version, bool *enabled)
Referenced by ADDON::Interface_General::Init(), and kodi::IsAddonAvailable().
kodi_version
void(* AddonToKodiFuncTable_kodi::kodi_version) (void *kodiBase, char **compile_name, int *major, int *minor, char **revision, char **tag, char **tagversion)
Referenced by ADDON::Interface_General::Init(), and kodi::KodiVersion().
queue_notification
bool(* AddonToKodiFuncTable_kodi::queue_notification) (void *kodiBase, int type, const char *header, const char *message, const char *imageFile, unsigned int displayTime, bool withSound, unsigned int messageTime)
Referenced by ADDON::Interface_General::Init().
unknown_to_utf8
char *(* AddonToKodiFuncTable_kodi::unknown_to_utf8) (void *kodiBase, const char *source, bool *ret, bool failOnBadChar)
Referenced by ADDON::Interface_General::Init().
The documentation for this struct was generated from the following file:
kodi-dev-kit/include/kodi/c-api/General.h