Kodi Documentation: CHttpRange Class Reference
CHttpRange Class Reference
#include <HttpRangeUtils.h>
Public Member Functions
CHttpRange ()=default
CHttpRange (uint64_t firstPosition, uint64_t lastPosition)
virtual ~CHttpRange ()=default
bool operator< (const CHttpRange &other) const
bool operator== (const CHttpRange &other) const
bool operator!= (const CHttpRange &other) const
virtual uint64_t GetFirstPosition () const
virtual void SetFirstPosition (uint64_t firstPosition)
virtual uint64_t GetLastPosition () const
virtual void SetLastPosition (uint64_t lastPosition)
virtual uint64_t GetLength () const
virtual void SetLength (uint64_t length)
virtual bool IsValid () const
Protected Attributes
uint64_t m_first = 1
uint64_t m_last = 0
Constructor & Destructor Documentation
CHttpRange() [1/2]
CHttpRange::CHttpRange () default
CHttpRange() [2/2]
CHttpRange::CHttpRange (uint64_t firstPosition, uint64_t lastPosition)
~CHttpRange()
virtual CHttpRange::~CHttpRange () virtual default
Member Function Documentation
GetFirstPosition()
virtual uint64_t CHttpRange::GetFirstPosition () const inline virtual
References m_first.
Referenced by TestWebServer::CheckRangesTestFileResponse(), CWebServer::ContentReaderCallback(), CWebServer::CreateMemoryDownloadResponse(), HttpRangeUtils::GenerateContentRangeHeaderValue(), CHttpRanges::GetFirstPosition(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetLastPosition()
virtual uint64_t CHttpRange::GetLastPosition () const inline virtual
References m_last.
Referenced by TestWebServer::CheckRangesTestFileResponse(), CWebServer::ContentReaderCallback(), CWebServer::CreateMemoryDownloadResponse(), HttpRangeUtils::GenerateContentRangeHeaderValue(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetLength()
uint64_t CHttpRange::GetLength () const virtual
References IsValid(), m_first, and m_last.
Referenced by TestWebServer::CheckRangesTestFileResponse(), CWebServer::CreateMemoryDownloadResponse(), HttpRangeUtils::GenerateContentRangeHeaderValue(), TEST(), TEST(), TEST(), and TEST().
IsValid()
bool CHttpRange::IsValid () const virtual
Reimplemented in CHttpResponseRange.
References m_first, and m_last.
Referenced by CHttpRanges::Add(), GetLength(), CHttpRanges::GetTotalRange(), CHttpResponseRange::IsValid(), TEST(), and TEST().
operator!=()
bool CHttpRange::operator!= (const CHttpRange & other) const
operator<()
bool CHttpRange::operator< (const CHttpRange & other) const
References m_first, and m_last.
operator==()
bool CHttpRange::operator== (const CHttpRange & other) const
References m_first, and m_last.
SetFirstPosition()
virtual void CHttpRange::SetFirstPosition (uint64_t firstPosition) inline virtual
References m_first.
Referenced by CHttpRanges::GetTotalRange(), CHttpResponseRange::SetData(), TEST(), TEST(), and TEST().
SetLastPosition()
virtual void CHttpRange::SetLastPosition (uint64_t lastPosition) inline virtual
References m_last.
Referenced by CHttpRanges::GetTotalRange(), CHttpResponseRange::SetData(), TEST(), TEST(), and TEST().
SetLength()
void CHttpRange::SetLength (uint64_t length) virtual
References m_first, and m_last.
Referenced by CHttpResponseRange::SetData(), and TEST().
Member Data Documentation
m_first
uint64_t CHttpRange::m_first = 1 protected
Referenced by GetFirstPosition(), GetLength(), IsValid(), operator<(), operator==(), CHttpResponseRange::SetData(), SetFirstPosition(), and SetLength().
m_last
uint64_t CHttpRange::m_last = 0 protected
Referenced by GetLastPosition(), GetLength(), IsValid(), operator<(), operator==(), SetLastPosition(), and SetLength().
The documentation for this class was generated from the following files:
HttpRangeUtils.h
HttpRangeUtils.cpp