Kodi Documentation: PVR::CPVRProvidersPath Class Reference
PVR::CPVRProvidersPath Class Reference
#include <PVRProvidersPath.h>
Public Types
enum class Kind { UNKNOWN , RADIO , TV }
Public Member Functions
CPVRProvidersPath (const std::string &path)
CPVRProvidersPath (Kind kind, int clientId, int providerUid, const std::string &lastSegment="")
bool IsValid () const
operator std::string () const
const std::string & GetPath () const
bool IsProvidersRoot () const
bool IsProvider () const
bool IsChannels () const
bool IsRecordings () const
bool IsRadio () const
Kind GetKind () const
int GetProviderUid () const
int GetClientId () const
Static Public Attributes
static const std::string PATH_TV_PROVIDERS = "pvr://providers/tv/"
static const std::string PATH_RADIO_PROVIDERS = "pvr://providers/radio/"
static const std::string CHANNELS = "channels"
static const std::string RECORDINGS = "recordings"
Private Member Functions
bool Init (const std::string &path)
Private Attributes
std::string m_path
bool m_isValid {false}
bool m_isRoot {false}
bool m_isProvider {false}
bool m_isChannels {false}
bool m_isRecordings {false}
Kind m_kind {Kind::UNKNOWN}
int m_providerUid {PVR_PROVIDER_INVALID_UID}
int m_clientId {PVR_CLIENT_INVALID_UID}
Member Enumeration Documentation
Kind
enum class PVR::CPVRProvidersPath::Kind strong
Enumerator
UNKNOWN
RADIO
TV
Constructor & Destructor Documentation
CPVRProvidersPath() [1/2]
CPVRProvidersPath::CPVRProvidersPath (const std::string & path) explicit
References Init().
CPVRProvidersPath() [2/2]
CPVRProvidersPath::CPVRProvidersPath (CPVRProvidersPath::Kind kind, int clientId, int providerUid, const std::string & lastSegment = "")
References CHANNELS, m_clientId, m_isChannels, m_isProvider, m_isRecordings, m_isRoot, m_isValid, m_kind, m_path, m_providerUid, RADIO, RECORDINGS, and TV.
Member Function Documentation
GetClientId()
int PVR::CPVRProvidersPath::GetClientId () const inline
References m_clientId.
Referenced by PVR::CGUIWindowPVRProvidersBase::ActivateChannelsWindow(), PVR::CGUIWindowPVRProvidersBase::ActivateRecordingsWindow(), and PVR::CPVRGUIDirectory::GetProvidersDirectory().
GetKind()
Kind PVR::CPVRProvidersPath::GetKind () const inline
References m_kind.
Referenced by PVR::CPVRGUIDirectory::GetProvidersDirectory().
GetPath()
const std::string & PVR::CPVRProvidersPath::GetPath () const inline
References m_path.
Referenced by PVR::CGUIWindowPVRProvidersBase::OnMessage().
GetProviderUid()
int PVR::CPVRProvidersPath::GetProviderUid () const inline
References m_providerUid.
Referenced by PVR::CGUIWindowPVRProvidersBase::ActivateChannelsWindow(), PVR::CGUIWindowPVRProvidersBase::ActivateRecordingsWindow(), and PVR::CPVRGUIDirectory::GetProvidersDirectory().
Init()
bool CPVRProvidersPath::Init (const std::string & path) private
References CHANNELS, m_clientId, m_isChannels, m_isProvider, m_isRecordings, m_isRoot, m_isValid, m_kind, m_path, m_providerUid, PVR::PVR_CLIENT_INVALID_UID, PVR_PROVIDER_INVALID_UID, RADIO, RECORDINGS, URIUtils::RemoveSlashAtEnd(), URIUtils::SplitPath(), and TV.
Referenced by CPVRProvidersPath().
IsChannels()
bool PVR::CPVRProvidersPath::IsChannels () const inline
References m_isChannels.
Referenced by PVR::CPVRGUIDirectory::GetProvidersDirectory().
IsProvider()
bool PVR::CPVRProvidersPath::IsProvider () const inline
References m_isProvider.
Referenced by PVR::CPVRGUIDirectory::GetProvidersDirectory().
IsProvidersRoot()
bool PVR::CPVRProvidersPath::IsProvidersRoot () const inline
References m_isRoot.
Referenced by PVR::CGUIViewStateWindowPVRProviders::CGUIViewStateWindowPVRProviders(), PVR::CPVRGUIDirectory::GetProvidersDirectory(), and PVR::CGUIViewStateWindowPVRProviders::HideParentDirItems().
IsRadio()
bool PVR::CPVRProvidersPath::IsRadio () const inline
References m_kind, and RADIO.
Referenced by PVR::CGUIWindowPVRProvidersBase::ActivateChannelsWindow(), PVR::CGUIWindowPVRProvidersBase::ActivateRecordingsWindow(), and PVR::CPVRGUIDirectory::GetProvidersDirectory().
IsRecordings()
bool PVR::CPVRProvidersPath::IsRecordings () const inline
References m_isRecordings.
Referenced by PVR::CPVRGUIDirectory::GetProvidersDirectory().
IsValid()
bool PVR::CPVRProvidersPath::IsValid () const inline
References m_isValid.
Referenced by PVR::CPVRGUIDirectory::GetProvidersDirectory().
operator std::string()
PVR::CPVRProvidersPath::operator std::string () const inline
References m_path.
Member Data Documentation
CHANNELS
const std::string CPVRProvidersPath::CHANNELS = "channels" static
Referenced by CPVRProvidersPath(), PVR::CPVRGUIDirectory::GetProvidersDirectory(), and Init().
m_clientId
int PVR::CPVRProvidersPath::m_clientId {PVR_CLIENT_INVALID_UID} private
Referenced by CPVRProvidersPath(), GetClientId(), and Init().
m_isChannels
bool PVR::CPVRProvidersPath::m_isChannels {false} private
Referenced by CPVRProvidersPath(), Init(), and IsChannels().
m_isProvider
bool PVR::CPVRProvidersPath::m_isProvider {false} private
Referenced by CPVRProvidersPath(), Init(), and IsProvider().
m_isRecordings
bool PVR::CPVRProvidersPath::m_isRecordings {false} private
Referenced by CPVRProvidersPath(), Init(), and IsRecordings().
m_isRoot
bool PVR::CPVRProvidersPath::m_isRoot {false} private
Referenced by CPVRProvidersPath(), Init(), and IsProvidersRoot().
m_isValid
bool PVR::CPVRProvidersPath::m_isValid {false} private
Referenced by CPVRProvidersPath(), Init(), and IsValid().
m_kind
Kind PVR::CPVRProvidersPath::m_kind {Kind::UNKNOWN} private
Referenced by CPVRProvidersPath(), GetKind(), Init(), and IsRadio().
m_path
std::string PVR::CPVRProvidersPath::m_path private
Referenced by CPVRProvidersPath(), GetPath(), Init(), and operator std::string().
m_providerUid
int PVR::CPVRProvidersPath::m_providerUid {PVR_PROVIDER_INVALID_UID} private
Referenced by CPVRProvidersPath(), GetProviderUid(), and Init().
PATH_RADIO_PROVIDERS
const std::string CPVRProvidersPath::PATH_RADIO_PROVIDERS = "pvr://providers/radio/" static
Referenced by PVR::CGUIWindowPVRRadioProviders::GetDirectoryPath(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), and PVR::CGUIWindowPVRRadioProviders::GetRootPath().
PATH_TV_PROVIDERS
const std::string CPVRProvidersPath::PATH_TV_PROVIDERS = "pvr://providers/tv/" static
Referenced by PVR::CGUIWindowPVRTVProviders::GetDirectoryPath(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), and PVR::CGUIWindowPVRTVProviders::GetRootPath().
RECORDINGS
const std::string CPVRProvidersPath::RECORDINGS = "recordings" static
Referenced by CPVRProvidersPath(), PVR::CPVRGUIDirectory::GetProvidersDirectory(), and Init().
The documentation for this class was generated from the following files:
PVRProvidersPath.h
PVRProvidersPath.cpp