Kodi Documentation: CPartyModeManager Class Reference
CPartyModeManager Class Reference final
#include <PartyModeManager.h>
Public Member Functions
CPartyModeManager (void)
bool Enable (PartyModeContext context=PARTYMODECONTEXT_MUSIC, const std::string &strXspPath="")
void Disable ()
void Play (int iPos)
void OnSongChange (bool bUpdatePlayed=false)
void AddUserSongs (KODI::PLAYLIST::CPlayList &tempList, bool bPlay=false)
void AddUserSongs (CFileItemList &tempList, bool bPlay=false)
bool IsEnabled (PartyModeContext context=PARTYMODECONTEXT_UNKNOWN) const
int GetSongsPlayed ()
int GetMatchingSongs ()
int GetMatchingSongsPicked ()
int GetMatchingSongsLeft ()
int GetRelaxedSongs ()
int GetRandomSongs ()
PartyModeContext GetType () const
Private Member Functions
void Process ()
bool AddRandomSongs ()
void Add (CFileItemPtr &pItem)
bool ReapSongs ()
bool MovePlaying ()
void SendUpdateMessage ()
void OnError (int iError, const std::string &strLogMessage)
void ClearState ()
void UpdateStats ()
void Announce ()
KODI::PLAYLIST::Id GetPlaylistId () const
Private Attributes
bool m_bEnabled
bool m_bIsVideo
int m_iLastUserSong
std::string m_type
int m_iSongsPlayed
int m_iMatchingSongs
int m_iMatchingSongsPicked
int m_iMatchingSongsLeft
int m_iRelaxedSongs
int m_iRandomSongs
std::vector< std::pair< int, int > > m_songIDCache
Constructor & Destructor Documentation
CPartyModeManager()
CPartyModeManager::CPartyModeManager (void)
References ClearState(), m_bEnabled, and m_bIsVideo.
Member Function Documentation
Add()
void CPartyModeManager::Add (CFileItemPtr & pItem) private
References KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), GetPlaylistId(), CServiceBroker::GetPlaylistPlayer(), CLog::Log(), LOGINFO, m_iMatchingSongsPicked, and playlist.
Referenced by AddRandomSongs().
AddRandomSongs()
bool CPartyModeManager::AddRandomSongs () private
References Add(), CDatabase::Close(), CVideoDatabase::GetMusicVideosByWhere(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), GetPlaylistId(), CServiceBroker::GetPlaylistPlayer(), CMusicDatabase::GetSongsFullByWhere(), SortDescription::limitEnd, m_iMatchingSongsPicked, m_songIDCache, OnError(), CMusicDatabase::Open(), CVideoDatabase::Open(), playlist, QUEUE_DEPTH, CFileItemList::Randomize(), CMusicDatabase::SetPropertiesForFileItem(), SortDescription::sortBy, and SortByRandom.
Referenced by Enable(), and Process().
AddUserSongs() [1/2]
void CPartyModeManager::AddUserSongs (CFileItemList & tempList, bool bPlay = false)
References KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), GetPlaylistId(), CServiceBroker::GetPlaylistPlayer(), KODI::PLAYLIST::CPlayList::Insert(), IsEnabled(), CLog::Log(), LOGINFO, m_iLastUserSong, Play(), and CFileItemList::Size().
AddUserSongs() [2/2]
void CPartyModeManager::AddUserSongs (KODI::PLAYLIST::CPlayList & tempList, bool bPlay = false)
References KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), GetPlaylistId(), CServiceBroker::GetPlaylistPlayer(), KODI::PLAYLIST::CPlayList::Insert(), IsEnabled(), CLog::Log(), LOGINFO, m_iLastUserSong, Play(), and KODI::PLAYLIST::CPlayList::size().
Referenced by CGUIWindowVideoBase::OnPlayMedia(), CGUIWindowMusicBase::OnPlayMedia(), CGUIWindowMusicBase::PlayItem(), MUSIC_UTILS::QueueItem(), and KODI::VIDEO::UTILS::QueueItem().
Announce()
void CPartyModeManager::Announce () private
References data(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppComponents(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CServiceBroker::GetPlaylistPlayer(), m_bEnabled, and ANNOUNCEMENT::Player.
Referenced by Disable(), and Enable().
ClearState()
void CPartyModeManager::ClearState () private
References m_iLastUserSong, m_iMatchingSongs, m_iMatchingSongsLeft, m_iMatchingSongsPicked, m_iRandomSongs, m_iRelaxedSongs, m_iSongsPlayed, and m_songIDCache.
Referenced by CPartyModeManager(), and Enable().
Disable()
void CPartyModeManager::Disable ()
References Announce(), IsEnabled(), CLog::Log(), LOGINFO, and m_bEnabled.
Referenced by CGUIWindowMusicBase::LoadPlayList(), CGUIWindowVideoBase::LoadPlayList(), CGUIWindowMusicPlayList::OnContextButton(), CGUIWindowVideoPlaylist::OnContextButton(), CGUIWindowMusicNav::OnMessage(), CGUIWindowVideoNav::OnMessage(), JSONRPC::CPlayerOperations::Open(), PlayerControl(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), and CApplication::StopPlaying().
Enable()
bool CPartyModeManager::Enable (PartyModeContext context = PARTYMODECONTEXT_MUSIC, const std::string & strXspPath = "")
References CGUIWindowManager::ActivateWindow(), AddRandomSongs(), Announce(), KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist(), ClearState(), CDatabase::Close(), CGUIWindow::Close(), end(), CServiceBroker::GetGUI(), GetPlaylistId(), CServiceBroker::GetPlaylistPlayer(), CVideoDatabase::GetRandomMusicVideoIDs(), CMusicDatabase::GetRandomSongIDs(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CLog::Log(), LOGDEBUG, LOGINFO, m_bEnabled, m_bIsVideo, m_iMatchingSongs, m_songIDCache, m_type, OnError(), CMusicDatabase::Open(), CVideoDatabase::Open(), CGUIDialogProgress::Open(), PARTYMODECONTEXT_UNKNOWN, PARTYMODECONTEXT_VIDEO, Play(), playlist, CGUIDialogProgress::Progress(), KODI::UTILS::RandomShuffle(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), KODI::PLAYLIST::CPlayListPlayer::SetRepeat(), KODI::PLAYLIST::CPlayListPlayer::SetShuffle(), WINDOW_DIALOG_PROGRESS, and WINDOW_MUSIC_PLAYLIST.
Referenced by CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicPlayList::OnContextButton(), CGUIWindowVideoBase::OnContextButton(), CGUIWindowVideoPlaylist::OnContextButton(), CGUIWindowMusicNav::OnMessage(), CGUIWindowVideoNav::OnMessage(), and PlayerControl().
GetMatchingSongs()
int CPartyModeManager::GetMatchingSongs ()
References IsEnabled(), and m_iMatchingSongs.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPartyModeLabel().
GetMatchingSongsLeft()
int CPartyModeManager::GetMatchingSongsLeft ()
References IsEnabled(), and m_iMatchingSongsLeft.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPartyModeLabel().
GetMatchingSongsPicked()
int CPartyModeManager::GetMatchingSongsPicked ()
References IsEnabled(), and m_iMatchingSongsPicked.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPartyModeLabel().
GetPlaylistId()
PLAYLIST::Id CPartyModeManager::GetPlaylistId () const private
References m_bIsVideo.
Referenced by Add(), AddRandomSongs(), AddUserSongs(), AddUserSongs(), Enable(), MovePlaying(), and ReapSongs().
GetRandomSongs()
int CPartyModeManager::GetRandomSongs ()
References IsEnabled(), and m_iRandomSongs.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPartyModeLabel().
GetRelaxedSongs()
int CPartyModeManager::GetRelaxedSongs ()
References IsEnabled(), and m_iRelaxedSongs.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPartyModeLabel().
GetSongsPlayed()
int CPartyModeManager::GetSongsPlayed ()
References IsEnabled(), and m_iSongsPlayed.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPartyModeLabel().
GetType()
PartyModeContext CPartyModeManager::GetType () const
References IsEnabled(), m_bIsVideo, PARTYMODECONTEXT_MUSIC, PARTYMODECONTEXT_UNKNOWN, and PARTYMODECONTEXT_VIDEO.
Referenced by JSONRPC::CPlayerOperations::SetPartymode().
IsEnabled()
bool CPartyModeManager::IsEnabled (PartyModeContext context = PARTYMODECONTEXT_UNKNOWN) const
References m_bEnabled, m_bIsVideo, PARTYMODECONTEXT_MUSIC, and PARTYMODECONTEXT_VIDEO.
Referenced by AddUserSongs(), AddUserSongs(), Disable(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetBool(), CGUIWindowMusicPlayList::GetContextButtons(), CGUIWindowVideoPlaylist::GetContextButtons(), GetMatchingSongs(), GetMatchingSongsLeft(), GetMatchingSongsPicked(), KODI::PLAYLIST::CPlayListPlayer::GetNextItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetNextItemIdx(), JSONRPC::CPlayerOperations::GetPropertyValue(), GetRandomSongs(), GetRelaxedSongs(), GetSongsPlayed(), GetType(), KODI::PLAYLIST::CPlayListPlayer::IsShuffled(), CGUIWindowMusicBase::LoadPlayList(), CGUIWindowVideoBase::LoadPlayList(), CGUIMediaWindow::OnClick(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIWindowVideoBase::OnPlayMedia(), CGUIWindowMusicBase::OnPlayMedia(), CGUIWindowMusicPlayList::OnPlayMedia(), CGUIWindowVideoPlaylist::OnPlayMedia(), OnSongChange(), JSONRPC::CPlayerOperations::Open(), PlayerControl(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::PlayItem(), MUSIC_UTILS::QueueItem(), KODI::VIDEO::UTILS::QueueItem(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), JSONRPC::CPlayerOperations::SetPartymode(), KODI::PLAYLIST::CPlayListPlayer::SetRepeat(), KODI::PLAYLIST::CPlayListPlayer::SetShuffle(), CGUIWindowMusicNav::UpdateButtons(), CGUIWindowMusicPlayList::UpdateButtons(), and CGUIWindowVideoNav::UpdateButtons().
MovePlaying()
bool CPartyModeManager::MovePlaying () private
References KODI::PLAYLIST::CPlayList::Add(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), GetPlaylistId(), CServiceBroker::GetPlaylistPlayer(), CLog::Log(), LOGINFO, playlist, KODI::PLAYLIST::CPlayListPlayer::SetCurrentItemIdx(), and KODI::PLAYLIST::CPlayList::size().
Referenced by Process().
OnError()
void CPartyModeManager::OnError (int iError, const std::string & strLogMessage) private
References CLog::Log(), LOGERROR, m_bEnabled, SendUpdateMessage(), and KODI::MESSAGING::HELPERS::ShowOKDialogLines().
Referenced by AddRandomSongs(), and Enable().
OnSongChange()
void CPartyModeManager::OnSongChange (bool bUpdatePlayed = false)
References IsEnabled(), m_iSongsPlayed, and Process().
Referenced by CApplication::OnMessage(), CGUIWindowMusicPlayList::RemovePlayListItem(), and CGUIWindowVideoPlaylist::RemovePlayListItem().
Play()
void CPartyModeManager::Play (int iPos)
References CServiceBroker::GetPlaylistPlayer(), CLog::Log(), LOGINFO, and KODI::PLAYLIST::CPlayListPlayer::Play().
Referenced by AddUserSongs(), AddUserSongs(), Enable(), CGUIWindowMusicPlayList::OnPlayMedia(), and CGUIWindowVideoPlaylist::OnPlayMedia().
Process()
void CPartyModeManager::Process () private
References AddRandomSongs(), MovePlaying(), ReapSongs(), SendUpdateMessage(), and UpdateStats().
Referenced by OnSongChange().
ReapSongs()
bool CPartyModeManager::ReapSongs () private
References KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), GetPlaylistId(), CServiceBroker::GetPlaylistPlayer(), m_iLastUserSong, KODI::PLAYLIST::CPlayList::Remove(), and KODI::PLAYLIST::CPlayListPlayer::SetCurrentItemIdx().
Referenced by Process().
SendUpdateMessage()
void CPartyModeManager::SendUpdateMessage () private
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and GUI_MSG_PLAYLIST_CHANGED.
Referenced by OnError(), and Process().
UpdateStats()
void CPartyModeManager::UpdateStats () private
References m_iMatchingSongs, m_iMatchingSongsLeft, m_iMatchingSongsPicked, m_iRandomSongs, and m_iRelaxedSongs.
Referenced by Process().
Member Data Documentation
m_bEnabled
bool CPartyModeManager::m_bEnabled private
Referenced by Announce(), CPartyModeManager(), Disable(), Enable(), IsEnabled(), and OnError().
m_bIsVideo
bool CPartyModeManager::m_bIsVideo private
Referenced by CPartyModeManager(), Enable(), GetPlaylistId(), GetType(), and IsEnabled().
m_iLastUserSong
int CPartyModeManager::m_iLastUserSong private
Referenced by AddUserSongs(), AddUserSongs(), ClearState(), and ReapSongs().
m_iMatchingSongs
int CPartyModeManager::m_iMatchingSongs private
Referenced by ClearState(), Enable(), GetMatchingSongs(), and UpdateStats().
m_iMatchingSongsLeft
int CPartyModeManager::m_iMatchingSongsLeft private
Referenced by ClearState(), GetMatchingSongsLeft(), and UpdateStats().
m_iMatchingSongsPicked
int CPartyModeManager::m_iMatchingSongsPicked private
Referenced by Add(), AddRandomSongs(), ClearState(), GetMatchingSongsPicked(), and UpdateStats().
m_iRandomSongs
int CPartyModeManager::m_iRandomSongs private
Referenced by ClearState(), GetRandomSongs(), and UpdateStats().
m_iRelaxedSongs
int CPartyModeManager::m_iRelaxedSongs private
Referenced by ClearState(), GetRelaxedSongs(), and UpdateStats().
m_iSongsPlayed
int CPartyModeManager::m_iSongsPlayed private
Referenced by ClearState(), GetSongsPlayed(), and OnSongChange().
m_songIDCache
std::vector<std::pair<int, int> > CPartyModeManager::m_songIDCache private
Referenced by AddRandomSongs(), ClearState(), and Enable().
m_type
std::string CPartyModeManager::m_type private
Referenced by Enable().
The documentation for this class was generated from the following files:
PartyModeManager.h
PartyModeManager.cpp