Kodi Documentation: CAESinkDARWINOSX Class Reference
CAESinkDARWINOSX Class Reference
#include <AESinkDARWINOSX.h>
Public Member Functions
const char * GetName () override
CAESinkDARWINOSX ()
~CAESinkDARWINOSX () override
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
double GetCacheTotal () override
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void Drain () override
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual double GetLatency ()
virtual void AddPause (unsigned int millis)
instruct the sink to add a pause
virtual bool HasVolume ()
virtual void SetVolume (float volume)
Static Public Member Functions
static void Register ()
static void EnumerateDevicesEx (AEDeviceInfoList &list, bool force)
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
Private Member Functions
void SetHogMode (bool on)
Static Private Member Functions
static OSStatus renderCallback (AudioDeviceID inDevice, const AudioTimeStamp *inNow, const AudioBufferList *inInputData, const AudioTimeStamp *inInputTime, AudioBufferList *outOutputData, const AudioTimeStamp *inOutputTime, void *inClientData)
Private Attributes
CAEDeviceInfo m_info
CCoreAudioDevice m_device
CCoreAudioStream m_outputStream
unsigned int m_latentFrames = 0
unsigned int m_outputBufferIndex = 0
bool m_outputBitstream
true if we're bistreaming into a LinearPCM stream rather than AC3 stream.
unsigned int m_planes = 1
number of audio planes (1 if non-planar)
unsigned int m_frameSizePerPlane = 0
frame size (per plane) in bytes
unsigned int m_framesPerSecond = 0
sample rate
AERingBuffer * m_buffer = nullptr
volatile bool m_started
CAESpinSection m_render_locker
volatile int64_t m_render_tick = 0
volatile double m_render_delay = 0.0
Constructor & Destructor Documentation
CAESinkDARWINOSX()
CAESinkDARWINOSX::CAESinkDARWINOSX ()
References deviceChangedCB(), CLog::Log(), LOGERROR, CCoreAudioDevice::RegisterDefaultOutputDeviceChangedCB(), and CCoreAudioDevice::RegisterDeviceChangedCB().
~CAESinkDARWINOSX()
CAESinkDARWINOSX::~CAESinkDARWINOSX () override
References deviceChangedCB(), CCoreAudioDevice::RegisterDefaultOutputDeviceChangedCB(), and CCoreAudioDevice::RegisterDeviceChangedCB().
Member Function Documentation
AddPackets()
unsigned int CAESinkDARWINOSX::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References condVar, data(), AERingBuffer::GetWriteSize(), CLog::Log(), LOGERROR, m_buffer, m_frameSizePerPlane, m_framesPerSecond, m_started, mutex, AERingBuffer::NumPlanes(), XbmcThreads::ConditionVariable::wait(), and AERingBuffer::Write().
Create()
std::unique_ptr< IAESink > CAESinkDARWINOSX::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
Deinitialize()
void CAESinkDARWINOSX::Deinitialize () override virtual
Implements IAESink.
References CCoreAudioDevice::Close(), CCoreAudioStream::Close(), m_buffer, m_device, m_outputBitstream, m_outputBufferIndex, m_outputStream, m_planes, m_started, CCoreAudioDevice::RemoveIOProc(), and CCoreAudioDevice::Stop().
Drain()
void CAESinkDARWINOSX::Drain () override virtual
Reimplemented from IAESink.
References condVar, AERingBuffer::GetReadSize(), m_buffer, m_frameSizePerPlane, m_framesPerSecond, mutex, and XbmcThreads::ConditionVariable::wait().
EnumerateDevicesEx()
void CAESinkDARWINOSX::EnumerateDevicesEx (AEDeviceInfoList & list, bool force) static
References EnumerateDevices(), and s_devices.
Referenced by Register().
GetCacheTotal()
double CAESinkDARWINOSX::GetCacheTotal () override virtual
Implements IAESink.
References AERingBuffer::GetMaxSize(), m_buffer, m_frameSizePerPlane, and m_framesPerSecond.
GetDelay()
void CAESinkDARWINOSX::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References AEDelayStatus::delay, AERingBuffer::GetReadSize(), m_buffer, m_frameSizePerPlane, m_framesPerSecond, m_latentFrames, m_render_delay, m_render_locker, m_render_tick, CAESpinLock::retry(), and AEDelayStatus::tick.
GetName()
const char * CAESinkDARWINOSX::GetName () inline override virtual
Implements IAESink.
Initialize()
bool CAESinkDARWINOSX::Initialize (AEAudioFormat & format, std::string & device) override virtual
Todo:
Should we use the virtual format to determine our data format?
Implements IAESink.
References CCoreAudioDevice::AddIOProc(), AE_FMT_FLOAT, AE_FMT_FLOATP, AE_FMT_RAW, AE_FMT_S16NE, CADeviceInstance::audioDeviceId, CAEUtil::DataFormatToBits(), AEDeviceEnumerationOSX::FindSuitableFormatForStream(), AEDeviceEnumerationOSX::GetAEChannelMap(), CCoreAudioDevice::GetBufferSize(), CCoreAudioHardware::GetDefaultOutputDevice(), GetDevices(), AERingBuffer::GetMaxSize(), CCoreAudioDevice::GetNumLatencyFrames(), CCoreAudioStream::GetNumLatencyFrames(), AEDeviceEnumerationOSX::GetNumPlanes(), CCoreAudioHardware::GetOutputDeviceName(), CCoreAudioStream::GetPhysicalFormat(), CCoreAudioStream::GetVirtualFormat(), AEDeviceEnumerationOSX::IsPlanar(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_buffer, m_device, m_frameSizePerPlane, m_framesPerSecond, m_latentFrames, m_outputBitstream, m_outputBufferIndex, m_outputStream, m_planes, CCoreAudioDevice::Open(), CCoreAudioStream::Open(), renderCallback(), CCoreAudioDevice::SetDataSource(), SetHogMode(), CCoreAudioStream::SetPhysicalFormat(), CCoreAudioStream::SetVirtualFormat(), CADeviceInstance::sourceId, CCoreAudioDevice::Start(), StreamDescriptionToString(), and CADeviceInstance::streamIndex.
Register()
void CAESinkDARWINOSX::Register () static
References Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
Referenced by CWinSystemOSX::CWinSystemOSX().
renderCallback()
OSStatus CAESinkDARWINOSX::renderCallback (AudioDeviceID inDevice, const AudioTimeStamp * inNow, const AudioBufferList * inInputData, const AudioTimeStamp * inInputTime, AudioBufferList * outOutputData, const AudioTimeStamp * inOutputTime, void * inClientData) static private
References condVar, CurrentHostFrequency(), CAESpinSection::enter(), AERingBuffer::GetReadSize(), CAESpinSection::leave(), LogLevel(), m_buffer, m_outputBitstream, m_outputBufferIndex, m_render_delay, m_render_locker, m_render_tick, m_started, XbmcThreads::ConditionVariable::notifyAll(), AERingBuffer::NumPlanes(), and AERingBuffer::Read().
Referenced by Initialize().
SetHogMode()
void CAESinkDARWINOSX::SetHogMode (bool on) private
Todo:
Auto hogging sets this for us. Figure out how/when to turn it off or use it It appears that leaving this set will also restore the previous stream format when the Application exits. If auto hogging is set and we try to set hog mode, we will deadlock From the SDK docs: "If the AudioDevice is in a non-mixable mode, the HAL will automatically take hog mode on behalf of the first process to start an IOProc."
Lock down the device. This MUST be done PRIOR to switching to a non-mixable format, if it is done at all If it is attempted after the format change, there is a high likelihood of a deadlock We may need to do this sooner to enable mix-disable (i.e. before setting the stream format)
References CCoreAudioHardware::GetAutoHogMode(), CLog::Log(), LOGDEBUG, m_device, CCoreAudioHardware::SetAutoHogMode(), CCoreAudioDevice::SetHogStatus(), and CCoreAudioDevice::SetMixingSupport().
Referenced by Initialize().
Member Data Documentation
m_buffer
AERingBuffer* CAESinkDARWINOSX::m_buffer = nullptr private
Referenced by AddPackets(), Deinitialize(), Drain(), GetCacheTotal(), GetDelay(), Initialize(), and renderCallback().
m_device
CCoreAudioDevice CAESinkDARWINOSX::m_device private
Referenced by Deinitialize(), Initialize(), and SetHogMode().
m_frameSizePerPlane
unsigned int CAESinkDARWINOSX::m_frameSizePerPlane = 0 private
frame size (per plane) in bytes
Referenced by AddPackets(), Drain(), GetCacheTotal(), GetDelay(), and Initialize().
m_framesPerSecond
unsigned int CAESinkDARWINOSX::m_framesPerSecond = 0 private
sample rate
Referenced by AddPackets(), Drain(), GetCacheTotal(), GetDelay(), and Initialize().
m_info
CAEDeviceInfo CAESinkDARWINOSX::m_info private
m_latentFrames
unsigned int CAESinkDARWINOSX::m_latentFrames = 0 private
Referenced by GetDelay(), and Initialize().
m_outputBitstream
bool CAESinkDARWINOSX::m_outputBitstream private
Initial value:
=
      false
true if we're bistreaming into a LinearPCM stream rather than AC3 stream.
Referenced by Deinitialize(), Initialize(), and renderCallback().
m_outputBufferIndex
unsigned int CAESinkDARWINOSX::m_outputBufferIndex = 0 private
Referenced by Deinitialize(), Initialize(), and renderCallback().
m_outputStream
CCoreAudioStream CAESinkDARWINOSX::m_outputStream private
Referenced by Deinitialize(), and Initialize().
m_planes
unsigned int CAESinkDARWINOSX::m_planes = 1 private
number of audio planes (1 if non-planar)
Referenced by Deinitialize(), and Initialize().
m_render_delay
volatile double CAESinkDARWINOSX::m_render_delay = 0.0 private
Referenced by GetDelay(), and renderCallback().
m_render_locker
CAESpinSection CAESinkDARWINOSX::m_render_locker private
Referenced by GetDelay(), and renderCallback().
m_render_tick
volatile int64_t CAESinkDARWINOSX::m_render_tick = 0 private
Referenced by GetDelay(), and renderCallback().
m_started
volatile bool CAESinkDARWINOSX::m_started private
Initial value:
=
      false
Referenced by AddPackets(), Deinitialize(), and renderCallback().
The documentation for this class was generated from the following files:
AESinkDARWINOSX.h
AESinkDARWINOSX.cpp