Kodi Documentation: CDVDSubtitlesLibass Class Reference
CDVDSubtitlesLibass Class Reference
#include <DVDSubtitlesLibass.h>
Public Member Functions
CDVDSubtitlesLibass ()
~CDVDSubtitlesLibass ()
void Configure ()
Configure libass. This method groups any configurations that might change throughout the lifecycle of libass (e.g. fonts)
ASS_Image * RenderImage (double pts, KODI::SUBTITLES::STYLE::renderOpts opts, bool updateStyle, const std::shared_ptr< struct KODI::SUBTITLES::STYLE::style > &subStyle, int *changes=NULL)
ASS_Event * GetEvents ()
int GetNrOfEvents () const
Get the number of events (subtitle entries) in the ASS track.
bool DecodeHeader (char *data, int size)
Decode Header of ASS/SSA, needed to properly decode demux packets with DecodeDemuxPkt.
bool DecodeDemuxPkt (const char *data, int size, double start, double duration)
Decode ASS/SSA demux packet (depends from DecodeHeader)
bool CreateTrack (char *buf, size_t size)
Create a new ASS track based on an SSA buffer.
void FlushEvents ()
Flush buffered events.
int GetPlayResY ()
Get PlayResY value.
Protected Member Functions
bool CreateTrack ()
Create a new empty ASS track.
bool CreateStyle ()
Create a new empty ASS style.
void SetSubtitleType (ASSSubType type)
Specify whether the subtitles are native (loaded from ASS/SSA file or stream) or adapted (converted from other types e.g. SubRip)
int AddEvent (const char *text, double startTime, double stopTime)
Add an ASS event to show a subtitle on a specified time.
int AddEvent (const char *text, double startTime, double stopTime, KODI::SUBTITLES::STYLE::subtitleOpts *opts)
Add an ASS event to show a subtitle on a specified time.
void AppendTextToEvent (int eventId, const char *text)
Append text to the specified event.
int DeleteEvents (int nEvents, int threshold)
Delete old events only if the total number of events reaches the threshold.
void ChangeEventStopTime (int eventId, double stopTime)
Change the stop time of an Event with the specified time.
Private Member Functions
void ConfigureAssOverride (const std::shared_ptr< struct KODI::SUBTITLES::STYLE::style > &subStyle, ASS_Style *style)
void ApplyStyle (const std::shared_ptr< struct KODI::SUBTITLES::STYLE::style > &subStyle, KODI::SUBTITLES::STYLE::renderOpts opts)
Private Attributes
ASS_Library * m_library = nullptr
ASS_Track * m_track = nullptr
ASS_Renderer * m_renderer = nullptr
CCriticalSection m_section
ASSSubType m_subtitleType {NATIVE}
int m_currentDefaultStyleId {ASS_NO_ID}
int m_defaultKodiStyleId {ASS_NO_ID}
std::string m_defaultFontFamilyName
Friends
class CSubtitlesAdapter
Constructor & Destructor Documentation
CDVDSubtitlesLibass()
CDVDSubtitlesLibass::CDVDSubtitlesLibass ()
References libass_log(), CLog::Log(), LOGINFO, m_library, and m_renderer.
~CDVDSubtitlesLibass()
CDVDSubtitlesLibass::~CDVDSubtitlesLibass ()
References m_library, m_renderer, and m_track.
Member Function Documentation
AddEvent() [1/2]
int CDVDSubtitlesLibass::AddEvent (const char * text, double startTime, double stopTime) protected
Add an ASS event to show a subtitle on a specified time.
Parameters
text The subtitle text
startTime The PTS start time of the Event
stopTime The PTS stop time of the Event
Returns
Return the Event ID, otherwise ASS_NO_ID if fails
References AddEvent(), and text.
Referenced by AddEvent().
AddEvent() [2/2]
int CDVDSubtitlesLibass::AddEvent (const char * text, double startTime, double stopTime, KODI::SUBTITLES::STYLE::subtitleOpts * opts) protected
Add an ASS event to show a subtitle on a specified time.
Parameters
text The subtitle text
startTime The PTS start time of the Event
stopTime The PTS stop time of the Event
opts Subtitle options
Returns
Return the Event ID, otherwise ASS_NO_ID if fails
References ASS_NO_ID, DVD_TIME_TO_MSEC(), CLog::Log(), LOGDEBUG, LOGERROR, m_defaultKodiStyleId, m_library, m_section, m_track, KODI::SUBTITLES::STYLE::subtitleOpts::marginLeft, KODI::SUBTITLES::STYLE::subtitleOpts::marginRight, KODI::SUBTITLES::STYLE::subtitleOpts::marginVertical, text, and KODI::SUBTITLES::STYLE::subtitleOpts::useMargins.
AppendTextToEvent()
void CDVDSubtitlesLibass::AppendTextToEvent (int eventId, const char * text) protected
Append text to the specified event.
References ASS_NO_ID, CLog::Log(), LOGERROR, m_section, m_track, and text.
ApplyStyle()
void CDVDSubtitlesLibass::ApplyStyle (const std::shared_ptr< struct KODI::SUBTITLES::STYLE::style > & subStyle, KODI::SUBTITLES::STYLE::renderOpts opts) private
Todo:
Libass has a problem with color transparencies when set to: PrimaryColour/SecondaryColour/OutlineColour by causing a gap between border and text color. As workaround the SecondaryColour must have no transparency this will fix just use cases without transparencies, for a full fix will be needed in future update libass library having the gap fix.
Bug:
in libass - force secondary color without transparency otherwise cause a visible color gap, we also avoid reusing the same primary color otherwise the karaoke effect will not be visible.
References ADAPTED, KODI::UTILS::COLOR::BLACK, ConfigureAssOverride(), KODI::SUBTITLES::FONT_DEFAULT_FAMILYNAME, KODI::SUBTITLES::STYLE::style::fontSize, KODI::SUBTITLES::STYLE::renderOpts::frameHeight, KODI::SUBTITLES::STYLE::renderOpts::frameWidth, KODI::SUBTITLES::STYLE::renderOpts::horizontalAlignment, CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_currentDefaultStyleId, m_defaultFontFamilyName, m_defaultKodiStyleId, m_renderer, m_subtitleType, m_track, KODI::SUBTITLES::STYLE::renderOpts::marginsMode, NATIVE, and KODI::UTILS::COLOR::NONE.
Referenced by RenderImage().
ChangeEventStopTime()
void CDVDSubtitlesLibass::ChangeEventStopTime (int eventId, double stopTime) protected
Change the stop time of an Event with the specified time.
Parameters
eventId The ASS Event ID
stopTime The PTS stop time
References ASS_NO_ID, DVD_TIME_TO_MSEC(), CLog::Log(), LOGERROR, m_section, and m_track.
Configure()
void CDVDSubtitlesLibass::Configure ()
Configure libass. This method groups any configurations that might change throughout the lifecycle of libass (e.g. fonts)
References KODI::UTILS::StringUtils::CompareNoCase(), XFILE::DIR_FLAG_BYPASS_CACHE, XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, XFILE::CDirectory::Exists(), KODI::UTILS::FONT::FONT_DEFAULT_FILENAME, XFILE::CDirectory::GetDirectory(), KODI::UTILS::FONT::GetFontFamily(), CServiceBroker::GetSettingsComponent(), KODI::UTILS::FONT::FONTPATH::GetSystemFontPath(), XFILE::CFile::LoadFile(), CLog::Log(), LOGERROR, LOGINFO, m_defaultFontFamilyName, m_library, m_renderer, CSettings::SETTING_SUBTITLES_OVERRIDEFONTS, KODI::UTILS::FONT::SUPPORTED_EXTENSIONS_MASK, KODI::UTILS::FONT::FONTPATH::SYSTEM, KODI::UTILS::FONT::FONTPATH::TEMP, CSpecialProtocol::TranslatePath(), and KODI::UTILS::FONT::FONTPATH::USER.
ConfigureAssOverride()
void CDVDSubtitlesLibass::ConfigureAssOverride (const std::shared_ptr< struct KODI::SUBTITLES::STYLE::style > & subStyle, ASS_Style * style) private
References CLog::Log(), LOGERROR, and m_renderer.
Referenced by ApplyStyle().
CreateStyle()
bool CDVDSubtitlesLibass::CreateStyle () protected
Create a new empty ASS style.
Returns
True if success, false if error
References CLog::Log(), LOGERROR, m_defaultKodiStyleId, m_library, m_section, and m_track.
CreateTrack() [1/2]
bool CDVDSubtitlesLibass::CreateTrack () protected
Create a new empty ASS track.
Returns
True if success, false if error
References CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, m_library, m_section, m_track, KODI::SUBTITLES::STYLE::VIEWPORT_HEIGHT, and KODI::SUBTITLES::STYLE::VIEWPORT_WIDTH.
CreateTrack() [2/2]
bool CDVDSubtitlesLibass::CreateTrack (char * buf, size_t size)
Create a new ASS track based on an SSA buffer.
Returns
True if success, false if error
References CLog::Log(), LOGERROR, LOGINFO, m_library, m_section, and m_track.
DecodeDemuxPkt()
bool CDVDSubtitlesLibass::DecodeDemuxPkt (const char * data, int size, double start, double duration)
Decode ASS/SSA demux packet (depends from DecodeHeader)
Returns
True if success, false if error
Bug:
libass isn't const correct
References data(), DVD_TIME_TO_MSEC(), CLog::Log(), LOGERROR, m_section, and m_track.
DecodeHeader()
bool CDVDSubtitlesLibass::DecodeHeader (char * data, int size)
Decode Header of ASS/SSA, needed to properly decode demux packets with DecodeDemuxPkt.
Returns
True if success, false if error
References data(), CLog::Log(), LOGINFO, m_library, m_section, and m_track.
DeleteEvents()
int CDVDSubtitlesLibass::DeleteEvents (int nEvents, int threshold) protected
Delete old events only if the total number of events reaches the threshold.
Parameters
nEvents The number of events to delete
threshold Start deleting only when the number of events is reached
Returns
The updated ID of the last Event, otherwise ASS_NO_ID if error or no events
References ASS_NO_ID, CLog::Log(), LOGERROR, m_library, m_section, and m_track.
FlushEvents()
void CDVDSubtitlesLibass::FlushEvents ()
Flush buffered events.
References CLog::Log(), LOGERROR, m_library, m_section, and m_track.
GetEvents()
ASS_Event * CDVDSubtitlesLibass::GetEvents ()
References CLog::Log(), LOGERROR, m_section, and m_track.
GetNrOfEvents()
int CDVDSubtitlesLibass::GetNrOfEvents () const
Get the number of events (subtitle entries) in the ASS track.
Returns
The number of events in the ASS track
References m_section, and m_track.
GetPlayResY()
int CDVDSubtitlesLibass::GetPlayResY ()
Get PlayResY value.
Returns
The PlayResY value of current track
References CLog::Log(), LOGERROR, m_track, and KODI::SUBTITLES::STYLE::VIEWPORT_HEIGHT.
RenderImage()
ASS_Image * CDVDSubtitlesLibass::RenderImage (double pts, KODI::SUBTITLES::STYLE::renderOpts opts, bool updateStyle, const std::shared_ptr< struct KODI::SUBTITLES::STYLE::style > & subStyle, int * changes = NULL)
References ApplyStyle(), ASS_NO_ID, DVD_TIME_TO_MSEC(), KODI::SUBTITLES::STYLE::renderOpts::frameHeight, KODI::SUBTITLES::STYLE::renderOpts::frameWidth, CLog::Log(), LOGERROR, m_currentDefaultStyleId, KODI::SUBTITLES::STYLE::renderOpts::m_par, m_renderer, m_section, m_subtitleType, m_track, KODI::SUBTITLES::STYLE::renderOpts::marginsMode, NATIVE, KODI::SUBTITLES::STYLE::renderOpts::position, KODI::SUBTITLES::STYLE::renderOpts::sourceHeight, KODI::SUBTITLES::STYLE::renderOpts::sourceWidth, KODI::SUBTITLES::STYLE::renderOpts::videoHeight, and KODI::SUBTITLES::STYLE::renderOpts::videoWidth.
SetSubtitleType()
void CDVDSubtitlesLibass::SetSubtitleType (ASSSubType type) inline protected
Specify whether the subtitles are native (loaded from ASS/SSA file or stream) or adapted (converted from other types e.g. SubRip)
References m_subtitleType.
Friends And Related Symbol Documentation
CSubtitlesAdapter
friend class CSubtitlesAdapter friend
Member Data Documentation
m_currentDefaultStyleId
int CDVDSubtitlesLibass::m_currentDefaultStyleId {ASS_NO_ID} private
Referenced by ApplyStyle(), and RenderImage().
m_defaultFontFamilyName
std::string CDVDSubtitlesLibass::m_defaultFontFamilyName private
Referenced by ApplyStyle(), and Configure().
m_defaultKodiStyleId
int CDVDSubtitlesLibass::m_defaultKodiStyleId {ASS_NO_ID} private
Referenced by AddEvent(), ApplyStyle(), and CreateStyle().
m_library
ASS_Library* CDVDSubtitlesLibass::m_library = nullptr private
Referenced by AddEvent(), CDVDSubtitlesLibass(), Configure(), CreateStyle(), CreateTrack(), CreateTrack(), DecodeHeader(), DeleteEvents(), FlushEvents(), and ~CDVDSubtitlesLibass().
m_renderer
ASS_Renderer* CDVDSubtitlesLibass::m_renderer = nullptr private
Referenced by ApplyStyle(), CDVDSubtitlesLibass(), Configure(), ConfigureAssOverride(), RenderImage(), and ~CDVDSubtitlesLibass().
m_section
CCriticalSection CDVDSubtitlesLibass::m_section mutable private
Referenced by AddEvent(), AppendTextToEvent(), ChangeEventStopTime(), CreateStyle(), CreateTrack(), CreateTrack(), DecodeDemuxPkt(), DecodeHeader(), DeleteEvents(), FlushEvents(), GetEvents(), GetNrOfEvents(), and RenderImage().
m_subtitleType
ASSSubType CDVDSubtitlesLibass::m_subtitleType {NATIVE} private
Referenced by ApplyStyle(), RenderImage(), and SetSubtitleType().
m_track
ASS_Track* CDVDSubtitlesLibass::m_track = nullptr private
Referenced by AddEvent(), AppendTextToEvent(), ApplyStyle(), ChangeEventStopTime(), CreateStyle(), CreateTrack(), CreateTrack(), DecodeDemuxPkt(), DecodeHeader(), DeleteEvents(), FlushEvents(), GetEvents(), GetNrOfEvents(), GetPlayResY(), RenderImage(), and ~CDVDSubtitlesLibass().
The documentation for this class was generated from the following files:
DVDSubtitlesLibass.h
DVDSubtitlesLibass.cpp