Kodi Documentation: KODI::RETRO::IRetroPlayerStream Class Reference
KODI::RETRO::IRetroPlayerStream Class Reference abstract
#include <IRetroPlayerStream.h>
Public Member Functions
virtual ~IRetroPlayerStream ()=default
virtual bool OpenStream (const StreamProperties &properties)=0
Open a stream.
virtual bool GetStreamBuffer (unsigned int width, unsigned int height, StreamBuffer &buffer)=0
Get a buffer for zero-copy stream data.
virtual void AddStreamData (const StreamPacket &packet)=0
Add a data packet to a stream.
virtual void CloseStream ()=0
Close the stream.
Constructor & Destructor Documentation
~IRetroPlayerStream()
virtual KODI::RETRO::IRetroPlayerStream::~IRetroPlayerStream () virtual default
Member Function Documentation
AddStreamData()
virtual void KODI::RETRO::IRetroPlayerStream::AddStreamData (const StreamPacket & packet) pure virtual
Add a data packet to a stream.
Parameters
packet The data packet
Implemented in KODI::RETRO::CRetroPlayerAudio, and KODI::RETRO::CRetroPlayerVideo.
Referenced by KODI::GAME::CGameClientStreamAudio::AddData(), and KODI::GAME::CGameClientStreamVideo::AddData().
CloseStream()
virtual void KODI::RETRO::IRetroPlayerStream::CloseStream () pure virtual
Close the stream.
Implemented in KODI::RETRO::CRetroPlayerAudio, and KODI::RETRO::CRetroPlayerVideo.
Referenced by KODI::GAME::CGameClientStreamAudio::CloseStream(), and KODI::GAME::CGameClientStreamVideo::CloseStream().
GetStreamBuffer()
virtual bool KODI::RETRO::IRetroPlayerStream::GetStreamBuffer (unsigned int width, unsigned int height, StreamBuffer & buffer) pure virtual
Get a buffer for zero-copy stream data.
Parameters
width The framebuffer width, or 0 for no width specified
height The framebuffer height, or 0 for no height specified
[out] buffer The buffer, or unmodified if false is returned
Returns
True if a buffer was returned, false otherwise
Implemented in KODI::RETRO::CRetroPlayerAudio, and KODI::RETRO::CRetroPlayerVideo.
Referenced by KODI::GAME::CGameClientStreamSwFramebuffer::GetBuffer().
OpenStream()
virtual bool KODI::RETRO::IRetroPlayerStream::OpenStream (const StreamProperties & properties) pure virtual
Open a stream.
Returns
True if the stream was opened, false otherwise
Implemented in KODI::RETRO::CRetroPlayerAudio, and KODI::RETRO::CRetroPlayerVideo.
The documentation for this class was generated from the following file:
IRetroPlayerStream.h