Kodi Documentation: CJob Class Reference
CJob Class Reference abstract
Asynchronous jobs
Base class for jobs that are executed asynchronously.
#include <Job.h>
Public Types
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Public Member Functions
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual bool DoWork ()=0
Main workhorse function of CJob instances.
virtual const char * GetType () const
Function that returns the type of job.
virtual bool operator== (const CJob *job) const
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Private Attributes
CJobManager * m_callback
Friends
class CJobManager
Detailed Description
Base class for jobs that are executed asynchronously.
Clients of the CJobManager should subclass CJob and provide the DoWork() function. Data should be passed to the job on creation, and any data sharing between the job and the client should be kept to within the callback functions if possible, and guarded with critical sections as appropriate.
Jobs typically fall into two groups: small jobs that perform a single function, and larger jobs that perform a sequence of functions. Clients with small jobs should implement the IJobCallback::OnJobComplete() callback to receive results. Clients with larger jobs may wish to implement both the IJobCallback::OnJobComplete() and IJobCallback::OnJobProgress() callbacks to receive updates. Jobs may be cancelled at any point by the client via CJobManager::CancelJob(), however effort should be taken to ensure that any callbacks and cancellation is suitably guarded against simultaneous thread access.
Handling cancellation of jobs within the OnJobProgress callback is a threadsafe operation, as all execution is then in the Job thread.
See also
CJobManager and IJobCallback
Member Enumeration Documentation
PRIORITY
enum CJob::PRIORITY
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
See also
CJobManager
Enumerator
PRIORITY_LOW_PAUSABLE
PRIORITY_LOW
PRIORITY_NORMAL
PRIORITY_HIGH
PRIORITY_DEDICATED
Constructor & Destructor Documentation
CJob()
CJob::CJob () inline
References m_callback.
~CJob()
virtual CJob::~CJob () virtual default
Destructor for job objects.
Jobs are destroyed by the CJobManager after the OnJobComplete() or OnJobAbort() callback is complete. CJob subclasses should therefore supply a virtual destructor to cleanup any memory allocated by complete or cancelled jobs.
See also
CJobManager
Member Function Documentation
DoWork()
virtual bool CJob::DoWork () pure virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implemented in CDetectDisc, anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob, anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob, ADDON::CRepositoryUpdateJob, KODI::CDRIP::CCDDARipJob, CGetDirectory::CGetJob, CImageLoader, CGUIMultiImage::CMultiImageJob, CDirectoryJob, CGetInfoJob, CRefreshInfoJob, CGetSongInfoJob, CMusicLibraryJob, CMusicLibraryProgressJob, CMACDiscoveryJob, PingResponseWaiter::CHostProberJob, CZeroconf::CPublish, CThumbnailWriter, anonymous_namespace{PVRGUIChannelNavigator.cpp}::CPVRChannelTimeoutJobBase, PVR::CPVREventLogJob, CAutorunMediaJob, CTextureCacheJob, CTextureUseCountJob, CFileOperationJob, CLambdaJob< F >, CRecentlyAddedJob, CSysInfoJob, DummyJob, ReallyDumbJob, anonymous_namespace{TestJobManager.cpp}::BroadcastingJob, CSubtitlesJob, CVideoLibraryJob, CVideoLibraryProgressJob, CWeatherJob, CSetUserratingJob, MUSIC_UTILS::CSetArtJob, MUSIC_UTILS::CSetSongRatingJob, and PERIPHERALS::CPeripheralCecAdapterReopenJob.
Referenced by CProgressJob::DoModal(), and CJobWorker::Process().
GetType()
virtual const char * CJob::GetType () const inline virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented in anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob, KODI::CDRIP::CCDDARipJob, CGUIMultiImage::CMultiImageJob, CDirectoryJob, CMusicLibraryCleaningJob, CMusicLibraryExportJob, CMusicLibraryImportJob, CMusicLibraryJob, CMusicLibraryProgressJob, CMusicLibraryScanningJob, anonymous_namespace{PVRGUIChannelNavigator.cpp}::CPVRChannelEntryTimeoutJob, anonymous_namespace{PVRGUIChannelNavigator.cpp}::CPVRChannelInfoTimeoutJob, PVR::CPVREventLogJob, CTextureCacheJob, CTextureUseCountJob, CFileOperationJob, CProgressJob, anonymous_namespace{TestJobManager.cpp}::BroadcastingJob, CVideoLibraryCleaningJob, CVideoLibraryJob, CVideoLibraryMarkWatchedJob, CVideoLibraryProgressJob, CVideoLibraryRefreshingJob, CVideoLibraryResetResumePointJob, and CVideoLibraryScanningJob.
Referenced by CJobManager::OnJobComplete(), CGUIMultiImage::OnJobComplete(), CMusicLibraryQueue::OnJobComplete(), CTextureCache::OnJobComplete(), CVideoLibraryQueue::OnJobComplete(), ADDON::CAddonInstaller::OnJobProgress(), KODI::CDRIP::CCDDARipJob::operator==(), CDirectoryJob::operator==(), CMusicLibraryCleaningJob::operator==(), CMusicLibraryExportJob::operator==(), CMusicLibraryImportJob::operator==(), CMusicLibraryScanningJob::operator==(), CTextureCacheJob::operator==(), CTextureUseCountJob::operator==(), CFileOperationJob::operator==(), CSubtitlesJob::operator==(), CVideoLibraryCleaningJob::operator==(), CVideoLibraryMarkWatchedJob::operator==(), CVideoLibraryRefreshingJob::operator==(), CVideoLibraryResetResumePointJob::operator==(), CVideoLibraryScanningJob::operator==(), and CJobWorker::Process().
operator==()
virtual bool CJob::operator== (const CJob * job) const inline virtual
Reimplemented in KODI::CDRIP::CCDDARipJob, CDirectoryJob, CMusicLibraryCleaningJob, CMusicLibraryExportJob, CMusicLibraryImportJob, CMusicLibraryJob, CMusicLibraryProgressJob, CMusicLibraryScanningJob, CTextureCacheJob, CTextureUseCountJob, CFileOperationJob, CLambdaJob< F >, CProgressJob, CSubtitlesJob, CVideoLibraryCleaningJob, CVideoLibraryJob, CVideoLibraryMarkWatchedJob, CVideoLibraryProgressJob, CVideoLibraryRefreshingJob, CVideoLibraryResetResumePointJob, and CVideoLibraryScanningJob.
ShouldCancel()
bool CJob::ShouldCancel (unsigned int progress, unsigned int total) const virtual
Function for longer jobs to report progress and check whether they have been cancelled.
Jobs that contain loops that may take time should check this routine each iteration of the loop, both to (optionally) report progress, and to check for cancellation.
Parameters
progress the amount of the job performed, out of total.
total the total amount of processing to be performed
Returns
if true, the job has been asked to cancel.
See also
IJobCallback::OnJobProgress()
Reimplemented in CProgressJob.
References m_callback, and CJobManager::OnJobProgress().
Referenced by KODI::CDRIP::CCDDARipJob::DoWork(), CTextureCacheJob::DoWork(), DummyJob::DoWork(), and CProgressJob::ShouldCancel().
Friends And Related Symbol Documentation
CJobManager
friend class CJobManager friend
Member Data Documentation
m_callback
CJobManager* CJob::m_callback private
Referenced by CJob(), CJobManager::PopJob(), and ShouldCancel().
The documentation for this class was generated from the following files:
Job.h
JobManager.cpp