Kodi Documentation: KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo Class Reference
KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo Class Reference
#include <GUIControlsGUIInfo.h>
Public Member Functions
~CGUIControlsGUIInfo () override=default
bool InitCurrentItem (CFileItem *item) override
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) const override
Get a GUIInfoManager label string.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager integer value.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager bool value.
void SetNextWindow (int windowID)
void SetPreviousWindow (int windowID)
void SetContainerMoving (int id, bool next, bool scrolling)
containers call this to specify that the focus is changing
void ResetContainerMovingCache ()
Public Member Functions inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
CGUIInfoProvider ()=default
~CGUIInfoProvider () override=default
bool GetFallbackLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) override
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo) override
Set new audio/video stream info data.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::IGUIInfoProvider
virtual ~IGUIInfoProvider ()=default
Private Attributes
int m_nextWindowID = WINDOW_INVALID
int m_prevWindowID = WINDOW_INVALID
std::map< int, int > m_containerMoves
Additional Inherited Members
Protected Attributes inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
VideoStreamInfo m_videoInfo
AudioStreamInfo m_audioInfo
SubtitleStreamInfo m_subtitleInfo
Constructor & Destructor Documentation
~CGUIControlsGUIInfo()
KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::~CGUIControlsGUIInfo () override default
Member Function Documentation
GetBool()
bool CGUIControlsGUIInfo::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager bool value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CVariant::asBoolean(), CVariant::asString(), CGUIMediaWindow::CanFilterAdvanced(), CONTAINER_CAN_FILTER, CONTAINER_CAN_FILTERADVANCED, CONTAINER_COLUMN, CONTAINER_CONTENT, CONTAINER_FILTERED, CONTAINER_HAS_FOCUS, CONTAINER_HAS_NEXT, CONTAINER_HAS_PARENT_ITEM, CONTAINER_HAS_PREVIOUS, CONTAINER_HAS_THUMB, CONTAINER_HASFILES, CONTAINER_HASFOLDERS, CONTAINER_ISUPDATING, CONTAINER_MOVE_NEXT, CONTAINER_MOVE_PREVIOUS, CONTAINER_POSITION, CONTAINER_ROW, CONTAINER_SCROLL_NEXT, CONTAINER_SCROLL_PREVIOUS, CONTAINER_SCROLLING, CONTAINER_SORT_DIRECTION, CONTAINER_SORT_METHOD, CONTAINER_STACKED, CONTAINER_SUBITEM, CONTROL_GROUP_HAS_FOCUS, CONTROL_HAS_FOCUS, CONTROL_IS_ENABLED, CONTROL_IS_VISIBLE, CGUIWindow::ControlGroupHasFocus(), CGUIDialogVideoInfo::CurrentDirectory(), CGUIMediaWindow::CurrentDirectory(), KODI::GUILIB::GUIINFO::GetActiveContainer(), CGUIControl::GetCondition(), CGUIDialogSongInfo::GetContent(), CFileItemList::GetContent(), CGUIControlLookup::GetControl(), URIUtils::GetFileName(), CGUIControlGroup::GetFocusedControlID(), CServiceBroker::GetGUI(), CGUIControl::GetID(), KODI::GUILIB::GUIINFO::GetMediaWindow(), CGUIWindow::GetProperty(), CGUIListItem::GetProperty(), CGUIViewState::GetSortMethod(), CGUIViewState::GetSortOrder(), CGUIMediaWindow::GetViewContainerID(), CGUIMediaWindow::GetViewState(), KODI::GUILIB::GUIINFO::GetWindow(), CGUIComponent::GetWindowManager(), CGUIListItem::HasArt(), CGUIWindow::IsActive(), CGUIControl::IsContainer(), CGUIControl::IsDisabled(), CGUIMediaWindow::IsFiltered(), CGUIDialogNumeric::IsInputHidden(), CGUIWindow::IsMediaWindow(), CGUIControl::IsVisible(), m_containerMoves, m_nextWindowID, m_prevWindowID, SortDescription::sortBy, SYSTEM_HAS_ACTIVE_MODAL_DIALOG, SYSTEM_HAS_INPUT_HIDDEN, SYSTEM_HAS_VISIBLE_MODAL_DIALOG, value, WINDOW_DIALOG_KEYBOARD, WINDOW_DIALOG_MUSIC_INFO, WINDOW_DIALOG_NUMERIC, WINDOW_DIALOG_SONG_INFO, WINDOW_DIALOG_VIDEO_INFO, WINDOW_IS, WINDOW_IS_ACTIVE, WINDOW_IS_DIALOG_TOPMOST, WINDOW_IS_MEDIA, WINDOW_IS_MODAL_DIALOG_TOPMOST, WINDOW_IS_VISIBLE, WINDOW_NEXT, and WINDOW_PREVIOUS.
GetInt()
bool CGUIControlsGUIInfo::GetInt (int & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager integer value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CServiceBroker::GetGUI(), CGUIDialogProgress::GetPercentage(), CGUIComponent::GetWindowManager(), CGUIDialog::IsDialogRunning(), SYSTEM_PROGRESS_BAR, value, and WINDOW_DIALOG_PROGRESS.
Referenced by GetLabel().
GetLabel()
bool CGUIControlsGUIInfo::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) const override virtual
Get a GUIInfoManager label string.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CVariant::asString(), CONTAINER_ART, CONTAINER_COLUMN, CONTAINER_CONTENT, CONTAINER_CURRENT_ITEM, CONTAINER_CURRENT_PAGE, CONTAINER_FOLDERNAME, CONTAINER_FOLDERPATH, CONTAINER_NUM_ALL_ITEMS, CONTAINER_NUM_ITEMS, CONTAINER_NUM_NONFOLDER_ITEMS, CONTAINER_NUM_PAGES, CONTAINER_PLUGINCATEGORY, CONTAINER_PLUGINNAME, CONTAINER_POSITION, CONTAINER_PROPERTY, CONTAINER_ROW, CONTAINER_SHOWPLOT, CONTAINER_SHOWTITLE, CONTAINER_SORT_METHOD, CONTAINER_SORT_ORDER, CONTAINER_TOTALTIME, CONTAINER_TOTALUNWATCHED, CONTAINER_TOTALWATCHED, CONTAINER_VIEWCOUNT, CONTAINER_VIEWMODE, CONTROL_GET_LABEL, CGUIMediaWindow::CurrentDirectory(), FANART_COLOR1, FANART_COLOR2, FANART_COLOR3, FANART_IMAGE, g_localizeStrings, CLocalizeStrings::Get(), CGUIListItem::GetArt(), CFileItemList::GetContent(), CGUIControlLookup::GetControl(), CGUIControl::GetControlType(), CGUIControl::GetDescription(), CGUIControl::GetDescriptionByIndex(), MUSIC_INFO::CMusicInfoTag::GetDuration(), URIUtils::GetFileName(), CGUIControlGroup::GetFocusedControl(), CServiceBroker::GetGUI(), CURL::GetHostName(), CGUIControl::GetID(), GetInt(), CGUIListItem::GetLabel(), CGUIControlGroupList::GetLabel(), CGUITextBox::GetLabel(), GetLabel(), KODI::GUILIB::GUIINFO::GetMediaWindow(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), CGUIDialogProgress::GetPercentage(), CGUIWindow::GetProperty(), CGUIListItem::GetProperty(), CServiceBroker::GetSettingsComponent(), CGUIViewState::GetSortMethodLabel(), CGUIViewState::GetSortOrderLabel(), CGUIMediaWindow::GetViewContainerID(), CGUIMediaWindow::GetViewCount(), CGUIMediaWindow::GetViewState(), KODI::GUILIB::GUIINFO::GetWindow(), CGUIComponent::GetWindowManager(), CURL::GetWithoutUserDetails(), CGUIControl::GUICONTROL_GROUPLIST, CGUIControl::GUICONTROL_TEXTBOX, CGUIControl::IsContainer(), CGUIDialog::IsDialogRunning(), CURL::IsProtocol(), CSettings::SETTING_LOOKANDFEEL_STARTUPWINDOW, SYSTEM_CURRENT_CONTROL, SYSTEM_CURRENT_CONTROL_ID, SYSTEM_CURRENT_WINDOW, SYSTEM_PROGRESS_BAR, SYSTEM_STARTUP_WINDOW, value, WINDOW_DIALOG_PROGRESS, and WINDOW_PROPERTY.
Referenced by GetLabel().
InitCurrentItem()
bool CGUIControlsGUIInfo::InitCurrentItem (CFileItem * item) override virtual
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by the provider, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
ResetContainerMovingCache()
void CGUIControlsGUIInfo::ResetContainerMovingCache ()
References m_containerMoves.
Referenced by CProfileManager::LoadProfile(), CApplication::Render(), CSkinSettings::Reset(), CGUIWindow::SetInitialVisibility(), and CGUIViewControl::UpdateViewVisibility().
SetContainerMoving()
void CGUIControlsGUIInfo::SetContainerMoving (int id, bool next, bool scrolling)
containers call this to specify that the focus is changing
Parameters
id control id
next true if we're moving to the next item, false if previous
scrolling true if the container is scrolling, false if the movement requires no scroll
References id, and m_containerMoves.
Referenced by CGUIBaseContainer::SetContainerMoving().
SetNextWindow()
void KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::SetNextWindow (int windowID) inline
References m_nextWindowID.
Referenced by CGUIWindowManager::PreviousWindow().
SetPreviousWindow()
void KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::SetPreviousWindow (int windowID) inline
References m_prevWindowID.
Referenced by CGUIWindowManager::PreviousWindow().
Member Data Documentation
m_containerMoves
std::map<int, int> KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::m_containerMoves private
Referenced by GetBool(), ResetContainerMovingCache(), and SetContainerMoving().
m_nextWindowID
int KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::m_nextWindowID = WINDOW_INVALID private
Referenced by GetBool(), and SetNextWindow().
m_prevWindowID
int KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::m_prevWindowID = WINDOW_INVALID private
Referenced by GetBool(), and SetPreviousWindow().
The documentation for this class was generated from the following files:
GUIControlsGUIInfo.h
GUIControlsGUIInfo.cpp