Kodi Documentation: CGLContextEGL Class Reference
CGLContextEGL Class Reference
#include <GLContextEGL.h>
Classes
struct Sync
Public Member Functions
CGLContextEGL (Display *dpy, EGLint renderingApi)
~CGLContextEGL () override
bool Refresh (bool force, int screen, Window glWindow, bool &newContext) override
bool CreatePB () override
void Destroy () override
void Detach () override
void SetVSync (bool enable) override
void SwapBuffers () override
void QueryExtensions () override
uint64_t GetVblankTiming (uint64_t &msc, uint64_t &interval) override
bool BindTextureUploadContext ()
bool UnbindTextureUploadContext ()
bool HasContext ()
Public Member Functions inherited from CGLContext
CGLContext (Display *dpy)
virtual ~CGLContext ()=default
bool IsExtSupported (const char *extension) const
const std::string & ExtPrefix () const
Public Attributes
EGLint m_renderingApi
EGLDisplay m_eglDisplay = EGL_NO_DISPLAY
EGLSurface m_eglSurface = EGL_NO_SURFACE
EGLContext m_eglContext = EGL_NO_CONTEXT
EGLConfig m_eglConfig
Public Attributes inherited from CGLContext
std::string m_extPrefix
std::string m_extensions
Display * m_dpy
Protected Member Functions
bool SuitableCheck (EGLDisplay eglDisplay, EGLConfig config)
EGLConfig GetEGLConfig (EGLDisplay eglDisplay, XVisualInfo *vInfo)
Protected Attributes
PFNEGLGETSYNCVALUESCHROMIUMPROC m_eglGetSyncValuesCHROMIUM = nullptr
PFNEGLGETPLATFORMDISPLAYEXTPROC m_eglGetPlatformDisplayEXT = nullptr
struct CGLContextEGL::Sync m_sync
CCriticalSection m_syncLock
bool m_usePB = false
EGLContext m_eglUploadContext = EGL_NO_CONTEXT
CCriticalSection m_textureUploadLock
Protected Attributes inherited from CGLContext
bool m_omlSync = true
Constructor & Destructor Documentation
CGLContextEGL()
CGLContextEGL::CGLContextEGL (Display * dpy, EGLint renderingApi) explicit
References CServiceBroker::GetSettingsComponent(), CGLContext::m_extPrefix, and CGLContext::m_omlSync.
~CGLContextEGL()
CGLContextEGL::~CGLContextEGL () override
References Destroy().
Member Function Documentation
BindTextureUploadContext()
bool CGLContextEGL::BindTextureUploadContext ()
References LOGERROR, m_eglDisplay, m_eglUploadContext, and m_textureUploadLock.
CreatePB()
bool CGLContextEGL::CreatePB () override virtual
Reimplemented from CGLContext.
References Destroy(), CLog::Log(), LOGERROR, LOGWARNING, CGLContext::m_dpy, m_eglConfig, m_eglContext, m_eglDisplay, m_eglGetPlatformDisplayEXT, m_eglSurface, m_eglUploadContext, m_renderingApi, and m_usePB.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLESContext::RefreshGLContext().
Destroy()
void CGLContextEGL::Destroy () override virtual
Implements CGLContext.
References EGL_NO_CONFIG, m_eglConfig, m_eglContext, m_eglDisplay, m_eglSurface, and m_eglUploadContext.
Referenced by CreatePB(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::DestroyWindowSystem(), Refresh(), and ~CGLContextEGL().
Detach()
void CGLContextEGL::Detach () override virtual
Implements CGLContext.
References m_eglContext, m_eglDisplay, and m_eglSurface.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLESContext::DestroyWindow().
GetEGLConfig()
EGLConfig CGLContextEGL::GetEGLConfig (EGLDisplay eglDisplay, XVisualInfo * vInfo) protected
References EGL_NO_CONFIG, CLog::Log(), LOGERROR, SuitableCheck(), and value.
Referenced by Refresh().
GetVblankTiming()
uint64_t CGLContextEGL::GetVblankTiming (uint64_t & msc, uint64_t & interval) override virtual
Reimplemented from CGLContext.
References CGLContextEGL::Sync::cont, CGLContextEGL::Sync::interval, m_sync, m_syncLock, CGLContextEGL::Sync::msc2, CGLContextEGL::Sync::ust1, and CGLContextEGL::Sync::ust2.
HasContext()
bool CGLContextEGL::HasContext ()
QueryExtensions()
void CGLContextEGL::QueryExtensions () override virtual
Implements CGLContext.
References CLog::Log(), LOGDEBUG, m_eglDisplay, and CGLContext::m_extensions.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLESContext::CreateNewWindow().
Refresh()
bool CGLContextEGL::Refresh (bool force, int screen, Window glWindow, bool & newContext) override virtual
Implements CGLContext.
References CGLContextEGL::Sync::cont, Destroy(), EGL_NO_CONFIG, GetEGLConfig(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, CGLContext::m_dpy, m_eglConfig, m_eglContext, m_eglDisplay, m_eglGetPlatformDisplayEXT, m_eglGetSyncValuesCHROMIUM, m_eglSurface, m_eglUploadContext, m_renderingApi, m_sync, and m_usePB.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLESContext::RefreshGLContext().
SetVSync()
void CGLContextEGL::SetVSync (bool enable) override virtual
Implements CGLContext.
References m_eglDisplay.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetVSyncImpl().
SuitableCheck()
bool CGLContextEGL::SuitableCheck (EGLDisplay eglDisplay, EGLConfig config) protected
References EGL_NO_CONFIG, and value.
Referenced by GetEGLConfig().
SwapBuffers()
void CGLContextEGL::SwapBuffers () override virtual
Implements CGLContext.
References CGLContextEGL::Sync::cont, CGLContextEGL::Sync::interval, CLog::Log(), LOGDEBUG, LOGWARNING, m_eglDisplay, m_eglGetSyncValuesCHROMIUM, m_eglSurface, CGLContext::m_omlSync, m_sync, m_syncLock, m_usePB, CGLContextEGL::Sync::msc1, CGLContextEGL::Sync::msc2, CGLContextEGL::Sync::ust1, and CGLContextEGL::Sync::ust2.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLESContext::PresentRenderImpl().
UnbindTextureUploadContext()
bool CGLContextEGL::UnbindTextureUploadContext ()
References LOGERROR, m_eglDisplay, m_eglUploadContext, and m_textureUploadLock.
Member Data Documentation
m_eglConfig
EGLConfig CGLContextEGL::m_eglConfig
Referenced by CreatePB(), Destroy(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::GetEGLConfig(), and Refresh().
m_eglContext
EGLContext CGLContextEGL::m_eglContext = EGL_NO_CONTEXT
Referenced by CreatePB(), Destroy(), Detach(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::GetEGLContext(), and Refresh().
m_eglDisplay
EGLDisplay CGLContextEGL::m_eglDisplay = EGL_NO_DISPLAY
Referenced by BindTextureUploadContext(), CreatePB(), Destroy(), Detach(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::GetEGLDisplay(), QueryExtensions(), Refresh(), SetVSync(), SwapBuffers(), and UnbindTextureUploadContext().
m_eglGetPlatformDisplayEXT
PFNEGLGETPLATFORMDISPLAYEXTPROC CGLContextEGL::m_eglGetPlatformDisplayEXT = nullptr protected
Referenced by CreatePB(), and Refresh().
m_eglGetSyncValuesCHROMIUM
PFNEGLGETSYNCVALUESCHROMIUMPROC CGLContextEGL::m_eglGetSyncValuesCHROMIUM = nullptr protected
Referenced by Refresh(), and SwapBuffers().
m_eglSurface
EGLSurface CGLContextEGL::m_eglSurface = EGL_NO_SURFACE
Referenced by CreatePB(), Destroy(), Detach(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::GetEGLSurface(), Refresh(), and SwapBuffers().
m_eglUploadContext
EGLContext CGLContextEGL::m_eglUploadContext = EGL_NO_CONTEXT protected
Referenced by BindTextureUploadContext(), CreatePB(), Destroy(), Refresh(), and UnbindTextureUploadContext().
m_renderingApi
EGLint CGLContextEGL::m_renderingApi
Referenced by CreatePB(), and Refresh().
m_sync
struct CGLContextEGL::Sync CGLContextEGL::m_sync protected
Referenced by GetVblankTiming(), Refresh(), and SwapBuffers().
m_syncLock
CCriticalSection CGLContextEGL::m_syncLock protected
Referenced by GetVblankTiming(), and SwapBuffers().
m_textureUploadLock
CCriticalSection CGLContextEGL::m_textureUploadLock mutable protected
Referenced by BindTextureUploadContext(), and UnbindTextureUploadContext().
m_usePB
bool CGLContextEGL::m_usePB = false protected
Referenced by CreatePB(), Refresh(), and SwapBuffers().
The documentation for this class was generated from the following files:
GLContextEGL.h
GLContextEGL.cpp