Kodi Documentation: XbmcThreads::ConditionVariable Class Reference
XbmcThreads::ConditionVariable Class Reference
#include <Condition.h>
Public Member Functions
ConditionVariable ()=default
void wait (CCriticalSection &lock, std::function< bool()> predicate)
void wait (CCriticalSection &lock)
template<typename Rep , typename Period >
bool wait (CCriticalSection &lock, std::chrono::duration< Rep, Period > duration, std::function< bool()> predicate)
template<typename Rep , typename Period >
bool wait (CCriticalSection &lock, std::chrono::duration< Rep, Period > duration)
void wait (std::unique_lock< CCriticalSection > &lock, std::function< bool()> predicate)
void wait (std::unique_lock< CCriticalSection > &lock)
template<typename Rep , typename Period >
bool wait (std::unique_lock< CCriticalSection > &lock, std::chrono::duration< Rep, Period > duration, std::function< bool()> predicate)
template<typename Rep , typename Period >
bool wait (std::unique_lock< CCriticalSection > &lock, std::chrono::duration< Rep, Period > duration)
void notifyAll ()
void notify ()
Private Member Functions
ConditionVariable (const ConditionVariable &)=delete
ConditionVariable & operator= (const ConditionVariable &)=delete
Private Attributes
std::condition_variable_any cond
Detailed Description
This is a thin wrapper around std::condition_variable_any. It is subject to "spurious returns"
Constructor & Destructor Documentation
ConditionVariable() [1/2]
XbmcThreads::ConditionVariable::ConditionVariable (const ConditionVariable &) private delete
ConditionVariable() [2/2]
XbmcThreads::ConditionVariable::ConditionVariable () default
Member Function Documentation
notify()
void XbmcThreads::ConditionVariable::notify () inline
References cond.
Referenced by CRenderSystemDX::ReleaseDecodingTime().
notifyAll()
void XbmcThreads::ConditionVariable::notifyAll () inline
References cond.
Referenced by CRenderManager::AddVideoPicture(), CRenderManager::Configure(), CRenderManager::Configure(), CRenderManager::DiscardBuffer(), CRenderManager::FrameMove(), CRenderManager::PrepareNextRender(), CRenderManager::Render(), CAESinkDARWINOSX::renderCallback(), CAAudioUnitSink::renderCallback(), CEvent::Set(), XbmcThreads::CEventGroup::Set(), CSharedSection::unlock_shared(), CDVDMsgGeneralSynchronize::Wait(), and CDVDMsgGeneralSynchronize::~CDVDMsgGeneralSynchronize().
operator=()
ConditionVariable & XbmcThreads::ConditionVariable::operator= (const ConditionVariable &) private delete
wait() [1/8]
void XbmcThreads::ConditionVariable::wait (CCriticalSection & lock) inline
References cond.
wait() [2/8]
template<typename Rep , typename Period > bool XbmcThreads::ConditionVariable::wait (CCriticalSection & lock, std::chrono::duration< Rep, Period > duration) inline
References cond.
wait() [3/8]
template<typename Rep , typename Period > bool XbmcThreads::ConditionVariable::wait (CCriticalSection & lock, std::chrono::duration< Rep, Period > duration, std::function< bool()> predicate) inline
References cond.
wait() [4/8]
void XbmcThreads::ConditionVariable::wait (CCriticalSection & lock, std::function< bool()> predicate) inline
References cond.
Referenced by CAESinkDARWINOSX::AddPackets(), CRenderManager::AddVideoPicture(), CRenderManager::Configure(), CAAudioUnitSink::drain(), CAESinkDARWINOSX::Drain(), CRenderManager::FrameWait(), CSharedSection::lock(), CRenderSystemDX::PresentRender(), CEvent::Wait(), CEvent::Wait(), XbmcThreads::CEventGroup::wait(), CDVDMsgGeneralSynchronize::Wait(), wait(), wait(), CRenderManager::WaitForBuffer(), anonymous_namespace{TestJobManager.cpp}::WaitForJobToStartProcessing(), CAAudioUnitSink::write(), and CAAudioUnitSink::write().
wait() [5/8]
void XbmcThreads::ConditionVariable::wait (std::unique_lock< CCriticalSection > & lock) inline
References wait().
Referenced by wait().
wait() [6/8]
template<typename Rep , typename Period > bool XbmcThreads::ConditionVariable::wait (std::unique_lock< CCriticalSection > & lock, std::chrono::duration< Rep, Period > duration) inline
References wait().
wait() [7/8]
template<typename Rep , typename Period > bool XbmcThreads::ConditionVariable::wait (std::unique_lock< CCriticalSection > & lock, std::chrono::duration< Rep, Period > duration, std::function< bool()> predicate) inline
References wait().
wait() [8/8]
void XbmcThreads::ConditionVariable::wait (std::unique_lock< CCriticalSection > & lock, std::function< bool()> predicate) inline
References cond.
Member Data Documentation
cond
std::condition_variable_any XbmcThreads::ConditionVariable::cond private
Referenced by notify(), notifyAll(), wait(), wait(), wait(), wait(), and wait().
The documentation for this class was generated from the following file:
Condition.h