Kodi Documentation: PVR::CPVRIntSettingValues Class Reference
PVR::CPVRIntSettingValues Class Reference
#include <PVRIntSettingValues.h>
Public Member Functions
CPVRIntSettingValues ()=default
CPVRIntSettingValues (int defaultValue)
CPVRIntSettingValues (struct PVR_ATTRIBUTE_INT_VALUE *values, unsigned int valuesSize, int defaultValue, int defaultDescriptionResourceId=0)
CPVRIntSettingValues (struct PVR_ATTRIBUTE_INT_VALUE *values, unsigned int valuesSize, unsigned int defaultValue, int defaultDescriptionResourceId=0)
CPVRIntSettingValues (const std::vector< SettingIntValue > &values, int defaultValue)
virtual ~CPVRIntSettingValues ()=default
bool operator== (const CPVRIntSettingValues &right) const
const std::vector< SettingIntValue > & GetValues () const
int GetDefaultValue () const
Private Attributes
std::vector< SettingIntValue > m_values
int m_defaultValue {0}
Constructor & Destructor Documentation
CPVRIntSettingValues() [1/5]
PVR::CPVRIntSettingValues::CPVRIntSettingValues () default
CPVRIntSettingValues() [2/5]
PVR::CPVRIntSettingValues::CPVRIntSettingValues (int defaultValue) explicit
CPVRIntSettingValues() [3/5]
PVR::CPVRIntSettingValues::CPVRIntSettingValues (struct PVR_ATTRIBUTE_INT_VALUE * values, unsigned int valuesSize, int defaultValue, int defaultDescriptionResourceId = 0)
References g_localizeStrings, CLocalizeStrings::Get(), m_values, value, and values.
CPVRIntSettingValues() [4/5]
PVR::CPVRIntSettingValues::CPVRIntSettingValues (struct PVR_ATTRIBUTE_INT_VALUE * values, unsigned int valuesSize, unsigned int defaultValue, int defaultDescriptionResourceId = 0)
CPVRIntSettingValues() [5/5]
PVR::CPVRIntSettingValues::CPVRIntSettingValues (const std::vector< SettingIntValue > & values, int defaultValue)
~CPVRIntSettingValues()
virtual PVR::CPVRIntSettingValues::~CPVRIntSettingValues () virtual default
Member Function Documentation
GetDefaultValue()
int PVR::CPVRIntSettingValues::GetDefaultValue () const inline
References m_defaultValue.
Referenced by PVR::CPVRIntSettingDefinition::GetDefaultValue(), PVR::CPVRTimerType::GetLifetimeDefault(), PVR::CPVRTimerType::GetMaxRecordingsDefault(), PVR::CPVRTimerType::GetPreventDuplicateEpisodesDefault(), PVR::CPVRTimerType::GetPriorityDefault(), and PVR::CPVRTimerType::GetRecordingGroupDefault().
GetValues()
const std::vector< SettingIntValue > & PVR::CPVRIntSettingValues::GetValues () const inline
References m_values.
Referenced by PVR::CPVRTimerType::GetLifetimeValues(), PVR::CPVRTimerType::GetMaxRecordingsValues(), PVR::CPVRTimerType::GetPreventDuplicateEpisodesValues(), PVR::CPVRTimerType::GetPriorityValues(), PVR::CPVRTimerType::GetRecordingGroupValues(), and PVR::CPVRIntSettingDefinition::GetValues().
operator==()
bool PVR::CPVRIntSettingValues::operator== (const CPVRIntSettingValues & right) const
References m_defaultValue, m_values, and right.
Member Data Documentation
m_defaultValue
int PVR::CPVRIntSettingValues::m_defaultValue {0} private
Referenced by GetDefaultValue(), and operator==().
m_values
std::vector<SettingIntValue> PVR::CPVRIntSettingValues::m_values private
Referenced by CPVRIntSettingValues(), GetValues(), PVR::CPVRIntSettingDefinition::operator==(), and operator==().
The documentation for this class was generated from the following files:
PVRIntSettingValues.h
PVRIntSettingValues.cpp