Kodi Documentation: ReplayGain::Info Class Reference
ReplayGain::Info Class Reference
#include <ReplayGain.h>
Public Member Functions
void SetGain (float aGain)
void SetGain (const std::string &aStrGain)
float Gain () const
void SetPeak (const std::string &aStrPeak)
void SetPeak (float aPeak)
float Peak () const
bool HasGain () const
bool HasPeak () const
bool Valid () const
Private Attributes
float m_gain = REPLAY_GAIN_NO_GAIN
float m_peak = REPLAY_GAIN_NO_PEAK
Member Function Documentation
Gain()
float ReplayGain::Info::Gain () const
Referenced by CAudioDecoder::GetReplayGain().
HasGain()
bool ReplayGain::Info::HasGain () const
References REPLAY_GAIN_NO_GAIN.
Referenced by CAudioDecoder::GetReplayGain().
HasPeak()
bool ReplayGain::Info::HasPeak () const
References REPLAY_GAIN_NO_PEAK.
Referenced by CAudioDecoder::GetReplayGain().
Peak()
float ReplayGain::Info::Peak () const
Referenced by CAudioDecoder::GetReplayGain().
SetGain() [1/2]
void ReplayGain::Info::SetGain (const std::string & aStrGain)
References ReplayGain::SetGain().
SetGain() [2/2]
void ReplayGain::Info::SetGain (float aGain)
References m_gain.
Referenced by CCueDocument::Parse(), ReplayGain::ParseGain(), and ReplayGain::SetGain().
SetPeak() [1/2]
void ReplayGain::Info::SetPeak (const std::string & aStrPeak)
References ReplayGain::SetPeak().
Referenced by CCueDocument::Parse(), ReplayGain::ParsePeak(), and ReplayGain::SetPeak().
SetPeak() [2/2]
void ReplayGain::Info::SetPeak (float aPeak)
Valid()
bool ReplayGain::Info::Valid () const
Referenced by CAudioDecoder::Create(), CCueDocument::GetSongs(), and MUSIC_INFO::CMusicInfoTag::SetSong().
Member Data Documentation
m_gain
float ReplayGain::Info::m_gain = REPLAY_GAIN_NO_GAIN private
Referenced by SetGain().
m_peak
float ReplayGain::Info::m_peak = REPLAY_GAIN_NO_PEAK private
The documentation for this class was generated from the following files:
ReplayGain.h
ReplayGain.cpp