Kodi Documentation: CNetworkPosix Class Reference
CNetworkPosix Class Reference abstract
#include <NetworkPosix.h>
Public Member Functions
virtual ~CNetworkPosix () override
std::vector< CNetworkInterface * > & GetInterfaceList () override
CNetworkInterface * GetFirstConnectedInterface () override
int GetSocket ()
Public Member Functions inherited from CNetworkBase
CNetworkBase ()
virtual ~CNetworkBase ()
CNetworkServices & GetServices ()
virtual bool GetHostName (std::string &hostname)
bool HasInterfaceForIP (unsigned long address)
bool IsAvailable (void)
bool IsConnected (void)
bool WakeOnLan (const char *mac)
bool PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms=2000, bool readability_check=false)
virtual bool PingHost (unsigned long host, unsigned int timeout_ms=2000)=0
virtual std::vector< std::string > GetNameServers (void)=0
void NetworkMessage (EMESSAGE message, int param)
bool IsLocalHost (const std::string &hostname)
void WaitForNet ()
Protected Member Functions
CNetworkPosix ()
Protected Attributes
std::vector< CNetworkInterface * > m_interfaces
Private Member Functions
virtual void GetMacAddress (const std::string &interfaceName, char macAddrRaw[6])=0
virtual void queryInterfaceList ()=0
Private Attributes
int m_sock
Additional Inherited Members
Public Types inherited from CNetworkBase
enum EMESSAGE { SERVICES_UP , SERVICES_DOWN }
Static Public Member Functions inherited from CNetworkBase
static std::unique_ptr< CNetworkBase > GetNetwork ()
static int ParseHex (char *str, unsigned char *addr)
static std::string GetIpStr (const sockaddr *sa)
IPv6/IPv4 compatible conversion of host IP address.
static std::string GetMaskByPrefixLength (uint8_t prefixLength)
convert prefix length of IPv4 address to IP mask representation
Public Attributes inherited from CNetworkBase
std::unique_ptr< CNetworkServices > m_services
Constructor & Destructor Documentation
~CNetworkPosix()
CNetworkPosix::~CNetworkPosix () override virtual
References m_interfaces, and m_sock.
CNetworkPosix()
CNetworkPosix::CNetworkPosix () protected
References m_sock.
Member Function Documentation
GetFirstConnectedInterface()
CNetworkInterface * CNetworkPosix::GetFirstConnectedInterface (void) override virtual
Bug:
Overwrite the GetFirstConnectedInterface and requery the interface list if no connected device is found this fixes a bug when no network is available after first start of xbmc and the interface comes up during runtime
Reimplemented from CNetworkBase.
References CNetworkBase::GetFirstConnectedInterface(), CLog::Log(), LOGDEBUG, and queryInterfaceList().
GetInterfaceList()
std::vector< CNetworkInterface * > & CNetworkPosix::GetInterfaceList (void) override virtual
Implements CNetworkBase.
References m_interfaces.
GetMacAddress()
virtual void CNetworkPosix::GetMacAddress (const std::string & interfaceName, char macAddrRaw[6]) private pure virtual
Implemented in CNetworkMacOS, CNetworkFreebsd, and CNetworkLinux.
GetSocket()
int CNetworkPosix::GetSocket () inline
References m_sock.
Referenced by CNetworkInterfacePosix::GetCurrentIPAddress(), CNetworkInterfacePosix::GetCurrentNetmask(), CNetworkInterfaceLinux::GetHostMacAddress(), CNetworkLinux::GetMacAddress(), CNetworkInterfacePosix::IsConnected(), and CNetworkInterfacePosix::IsEnabled().
queryInterfaceList()
virtual void CNetworkPosix::queryInterfaceList () private pure virtual
Implemented in CNetworkMacOS, CNetworkFreebsd, and CNetworkLinux.
Referenced by GetFirstConnectedInterface().
Member Data Documentation
m_interfaces
std::vector<CNetworkInterface*> CNetworkPosix::m_interfaces protected
Referenced by GetInterfaceList(), CNetworkMacOS::queryInterfaceList(), CNetworkFreebsd::queryInterfaceList(), CNetworkLinux::queryInterfaceList(), and ~CNetworkPosix().
m_sock
int CNetworkPosix::m_sock private
Referenced by CNetworkPosix(), GetSocket(), and ~CNetworkPosix().
The documentation for this class was generated from the following files:
NetworkPosix.h
NetworkPosix.cpp