Kodi Documentation: CSettingsBase Class Reference
CSettingsBase Class Reference abstract
Basic wrapper around CSettingsManager providing the framework for properly setting up the settings manager and registering all the callbacks, handlers and custom setting types.
#include <SettingsBase.h>
Public Member Functions
virtual ~CSettingsBase ()
CSettingsManager * GetSettingsManager () const
virtual bool Initialize ()
Initializes the setting system with the generic settings definition and platform specific setting definitions.
virtual bool IsInitialized () const
Returns whether the settings system has been initialized or not.
virtual bool Load ()=0
Loads the setting values.
virtual void SetLoaded ()
Tells the settings system that all setting values have been loaded.
virtual bool IsLoaded () const
Returns whether the settings system has been loaded or not.
virtual bool Save ()=0
Saves the setting values.
virtual void Unload ()
Unloads the previously loaded setting values.
virtual void Uninitialize ()
Uninitializes the settings system.
void RegisterCallback (ISettingCallback *callback, const std::set< std::string > &settingList)
Registers the given ISettingCallback implementation for the given set of settings.
void UnregisterCallback (ISettingCallback *callback)
Unregisters the given ISettingCallback implementation.
std::shared_ptr< CSetting > GetSetting (const std::string &id) const
Gets the setting with the given identifier.
std::vector< std::shared_ptr< CSettingSection > > GetSections () const
Gets the full list of setting sections.
std::shared_ptr< CSettingSection > GetSection (const std::string &section) const
Gets the setting section with the given identifier.
bool GetBool (const std::string &id) const
Gets the boolean value of the setting with the given identifier.
int GetInt (const std::string &id) const
Gets the integer value of the setting with the given identifier.
double GetNumber (const std::string &id) const
Gets the real number value of the setting with the given identifier.
std::string GetString (const std::string &id) const
Gets the string value of the setting with the given identifier.
std::vector< CVariant > GetList (const std::string &id) const
Gets the values of the list setting with the given identifier.
bool SetBool (const std::string &id, bool value)
Sets the boolean value of the setting with the given identifier.
bool ToggleBool (const std::string &id)
Toggles the boolean value of the setting with the given identifier.
bool SetInt (const std::string &id, int value)
Sets the integer value of the setting with the given identifier.
bool SetNumber (const std::string &id, double value)
Sets the real number value of the setting with the given identifier.
bool SetString (const std::string &id, const std::string &value)
Sets the string value of the setting with the given identifier.
bool SetList (const std::string &id, const std::vector< CVariant > &value)
Sets the values of the list setting with the given identifier.
bool SetDefault (const std::string &id)
Sets the value of the setting with the given identifier to its default.
void SetDefaults ()
Sets the value of all settings to their default.
Protected Member Functions
CSettingsBase ()
virtual void InitializeSettingTypes ()
virtual void InitializeControls ()
virtual void InitializeOptionFillers ()
virtual void UninitializeOptionFillers ()
virtual void InitializeConditions ()
virtual void UninitializeConditions ()
virtual bool InitializeDefinitions ()=0
virtual void InitializeVisibility ()
virtual void InitializeDefaults ()
virtual void InitializeISettingsHandlers ()
virtual void UninitializeISettingsHandlers ()
virtual void InitializeISubSettings ()
virtual void UninitializeISubSettings ()
virtual void InitializeISettingCallbacks ()
virtual void UninitializeISettingCallbacks ()
bool InitializeDefinitionsFromXml (const CXBMCTinyXML &xml)
bool LoadValuesFromXml (const CXBMCTinyXML &xml, bool &updated)
Loads setting values from the given document in XML format.
bool SaveValuesToXml (CXBMCTinyXML &xml) const
Saves the setting values in XML format to the given document.
bool LoadValuesFromXml (const TiXmlElement *root, bool &updated)
Loads setting values from the given XML element.
bool LoadHiddenValuesFromXml (const TiXmlElement *root)
Loads hidden setting values from the given XML element.
Protected Attributes
bool m_initialized = false
CSettingsManager * m_settingsManager
CCriticalSection m_critical
Private Member Functions
CSettingsBase (const CSettingsBase &)=delete
CSettingsBase & operator= (const CSettingsBase &)=delete
Detailed Description
Basic wrapper around CSettingsManager providing the framework for properly setting up the settings manager and registering all the callbacks, handlers and custom setting types.
See also
CSettingsManager
Constructor & Destructor Documentation
~CSettingsBase()
CSettingsBase::~CSettingsBase () virtual
References m_settingsManager, and Uninitialize().
CSettingsBase() [1/2]
CSettingsBase::CSettingsBase () protected
CSettingsBase() [2/2]
CSettingsBase::CSettingsBase (const CSettingsBase &) private delete
Member Function Documentation
GetBool()
bool CSettingsBase::GetBool (const std::string & id) const
Gets the boolean value of the setting with the given identifier.
Parameters
id Setting identifier
Returns
Boolean value of the setting with the given identifier
References CSettingsManager::GetBool(), and m_settingsManager.
Referenced by CSettings::GetBool().
GetInt()
int CSettingsBase::GetInt (const std::string & id) const
Gets the integer value of the setting with the given identifier.
Parameters
id Setting identifier
Returns
Integer value of the setting with the given identifier
References CSettingsManager::GetInt(), and m_settingsManager.
Referenced by CApplicationVolumeHandling::CacheReplayGainSettings().
GetList()
std::vector< CVariant > CSettingsBase::GetList (const std::string & id) const
Gets the values of the list setting with the given identifier.
Parameters
id Setting identifier
Returns
List of values of the setting with the given identifier
References CSettingUtils::GetList(), CSettingsManager::GetSetting(), List, and m_settingsManager.
GetNumber()
double CSettingsBase::GetNumber (const std::string & id) const
Gets the real number value of the setting with the given identifier.
Parameters
id Setting identifier
Returns
Real number value of the setting with the given identifier
References CSettingsManager::GetNumber(), and m_settingsManager.
GetSection()
std::shared_ptr< CSettingSection > CSettingsBase::GetSection (const std::string & section) const
Gets the setting section with the given identifier.
Parameters
section Setting section identifier
Returns
Setting section with the given identifier or NULL if the identifier is unknown
References CSettingsManager::GetSection(), and m_settingsManager.
GetSections()
std::vector< std::shared_ptr< CSettingSection > > CSettingsBase::GetSections () const
Gets the full list of setting sections.
Returns
List of setting sections
References CSettingsManager::GetSections(), and m_settingsManager.
GetSetting()
SettingPtr CSettingsBase::GetSetting (const std::string & id) const
Gets the setting with the given identifier.
Parameters
id Setting identifier
Returns
Setting object with the given identifier or NULL if the identifier is unknown
References CSettingsManager::GetSetting(), and m_settingsManager.
Referenced by ADDON::CAddonSettings::AddInstanceSettings(), CSettings::InitializeDefaults(), and ADDON::CAddonSettings::Load().
GetSettingsManager()
CSettingsManager * CSettingsBase::GetSettingsManager () const inline
References m_settingsManager.
Referenced by ADDON::CAddonSettings::AddInstanceSettings(), anonymous_namespace{AddonSettings.cpp}::AddSettingWithoutDefinition(), ADDON::CAddonSettings::HasSettings(), ADDON::CAddonSettings::Initialize(), ADDON::CAddonSettings::InitializeConditions(), ADDON::CAddonSettings::InitializeControls(), ADDON::CAddonSettings::InitializeFromOldSettingAction(), ADDON::CAddonSettings::InitializeFromOldSettingAddon(), ADDON::CAddonSettings::InitializeFromOldSettingBool(), ADDON::CAddonSettings::InitializeFromOldSettingDate(), ADDON::CAddonSettings::InitializeFromOldSettingDefinitions(), ADDON::CAddonSettings::InitializeFromOldSettingEnums(), ADDON::CAddonSettings::InitializeFromOldSettingFileWithSource(), ADDON::CAddonSettings::InitializeFromOldSettingLabel(), ADDON::CAddonSettings::InitializeFromOldSettingNumber(), ADDON::CAddonSettings::InitializeFromOldSettingPath(), ADDON::CAddonSettings::InitializeFromOldSettingRangeOfNum(), ADDON::CAddonSettings::InitializeFromOldSettingSelect(), ADDON::CAddonSettings::InitializeFromOldSettingSlider(), ADDON::CAddonSettings::InitializeFromOldSettingTextIpAddress(), ADDON::CAddonSettings::InitializeFromOldSettingTime(), anonymous_namespace{AddonSettings.cpp}::InitializeFromOldSettingWithoutDefinition(), anonymous_namespace{AddonSettings.cpp}::InitializeFromOldSettingWithoutDefinition< CSettingString >(), ADDON::CAddonSettings::InitializeSettingTypes(), ADDON::CAddonSettings::ParseOldCategoryElement(), ADDON::CAddonSettings::ParseOldCondition(), ADDON::CAddonSettings::ParseOldSettingElement(), and ADDON::CAddonSettings::ParseSettingVersion().
GetString()
std::string CSettingsBase::GetString (const std::string & id) const
Gets the string value of the setting with the given identifier.
Parameters
id Setting identifier
Returns
String value of the setting with the given identifier
References CSettingsManager::GetString(), and m_settingsManager.
Initialize()
bool CSettingsBase::Initialize () virtual
Initializes the setting system with the generic settings definition and platform specific setting definitions.
Returns
True if the initialization was successful, false otherwise
Reimplemented in ADDON::CAddonSettings, and CSettings.
References InitializeConditions(), InitializeControls(), InitializeDefaults(), InitializeDefinitions(), InitializeISettingCallbacks(), InitializeISettingsHandlers(), InitializeISubSettings(), InitializeOptionFillers(), InitializeSettingTypes(), InitializeVisibility(), m_critical, m_initialized, m_settingsManager, and CSettingsManager::SetInitialized().
InitializeConditions()
virtual void CSettingsBase::InitializeConditions () inline protected virtual
Reimplemented in ADDON::CAddonSettings, and CSettings.
Referenced by Initialize().
InitializeControls()
virtual void CSettingsBase::InitializeControls () inline protected virtual
Reimplemented in ADDON::CAddonSettings, and CSettings.
Referenced by Initialize().
InitializeDefaults()
virtual void CSettingsBase::InitializeDefaults () inline protected virtual
Reimplemented in CSettings.
Referenced by Initialize().
InitializeDefinitions()
virtual bool CSettingsBase::InitializeDefinitions () protected pure virtual
Implemented in ADDON::CAddonSettings, and CSettings.
Referenced by Initialize().
InitializeDefinitionsFromXml()
bool CSettingsBase::InitializeDefinitionsFromXml (const CXBMCTinyXML & xml) protected
References CSettingsManager::Initialize(), m_settingsManager, and root.
Referenced by CSettings::Initialize(), and ADDON::CAddonSettings::InitializeDefinitions().
InitializeISettingCallbacks()
virtual void CSettingsBase::InitializeISettingCallbacks () inline protected virtual
Reimplemented in CSettings.
Referenced by Initialize().
InitializeISettingsHandlers()
virtual void CSettingsBase::InitializeISettingsHandlers () inline protected virtual
Reimplemented in CSettings.
Referenced by Initialize().
InitializeISubSettings()
virtual void CSettingsBase::InitializeISubSettings () inline protected virtual
Reimplemented in CSettings.
Referenced by Initialize().
InitializeOptionFillers()
virtual void CSettingsBase::InitializeOptionFillers () inline protected virtual
Reimplemented in CSettings.
Referenced by Initialize().
InitializeSettingTypes()
virtual void CSettingsBase::InitializeSettingTypes () inline protected virtual
Reimplemented in ADDON::CAddonSettings, and CSettings.
Referenced by Initialize().
InitializeVisibility()
virtual void CSettingsBase::InitializeVisibility () inline protected virtual
Referenced by Initialize(), and CSettings::InitializeDefinitions().
IsInitialized()
bool CSettingsBase::IsInitialized () const virtual
Returns whether the settings system has been initialized or not.
References CSettingsManager::IsInitialized(), m_initialized, and m_settingsManager.
Referenced by anonymous_namespace{AddonSettings.cpp}::AddSettingWithoutDefinition(), and ADDON::CAddonSettings::HasSettings().
IsLoaded()
bool CSettingsBase::IsLoaded () const virtual
Returns whether the settings system has been loaded or not.
References CSettingsManager::IsLoaded(), and m_settingsManager.
Load()
virtual bool CSettingsBase::Load () pure virtual
Loads the setting values.
Returns
True if the setting values are successfully loaded, false otherwise
Implemented in ADDON::CAddonSettings, and CSettings.
LoadHiddenValuesFromXml()
bool CSettingsBase::LoadHiddenValuesFromXml (const TiXmlElement * root) protected
Loads hidden setting values from the given XML element.
Parameters
root XML element containing setting values
Returns
True if the setting values were successfully loaded, false otherwise
References CSettingsManager::Load(), m_settingsManager, root, and success.
Referenced by CSettings::LoadHidden().
LoadValuesFromXml() [1/2]
bool CSettingsBase::LoadValuesFromXml (const CXBMCTinyXML & xml, bool & updated) protected
Loads setting values from the given document in XML format.
Parameters
xml Document in XML format from which the settings are loaded
updated Output parameter indicating whether setting values had to be updated
Returns
True if the setting values were successfully loaded, false otherwise
References CSettingsManager::Load(), m_settingsManager, and SETTINGS_XML_ROOT.
Referenced by ADDON::CAddonSettings::Load(), and CSettings::Load().
LoadValuesFromXml() [2/2]
bool CSettingsBase::LoadValuesFromXml (const TiXmlElement * root, bool & updated) protected
Loads setting values from the given XML element.
Parameters
root XML element containing setting values
updated Output parameter indicating whether setting values had to be updated
Returns
True if the setting values were successfully loaded, false otherwise
References CSettingsManager::Load(), m_settingsManager, and root.
operator=()
CSettingsBase & CSettingsBase::operator= (const CSettingsBase &) private delete
RegisterCallback()
void CSettingsBase::RegisterCallback (ISettingCallback * callback, const std::set< std::string > & settingList)
Registers the given ISettingCallback implementation for the given set of settings.
Parameters
callback ISettingCallback implementation
settingList List of setting identifiers for which the given callback shall be triggered
References m_settingsManager, and CSettingsManager::RegisterCallback().
Save()
virtual bool CSettingsBase::Save () pure virtual
Saves the setting values.
Returns
True if the setting values were successfully saved, false otherwise
Implemented in ADDON::CAddonSettings, and CSettings.
SaveValuesToXml()
bool CSettingsBase::SaveValuesToXml (CXBMCTinyXML & xml) const protected
Saves the setting values in XML format to the given document.
Parameters
xml Document to save the setting values in XML format into
Returns
True if the setting values were successfully saved, false otherwise
References m_settingsManager, CXBMCTinyXML::Parse(), and CSettingsManager::Save().
Referenced by CSettings::Save(), and ADDON::CAddonSettings::Save().
SetBool()
bool CSettingsBase::SetBool (const std::string & id, bool value)
Sets the boolean value of the setting with the given identifier.
Parameters
id Setting identifier
value Boolean value to set
Returns
True if setting the value was successful, false otherwise
References m_settingsManager, CSettingsManager::SetBool(), and value.
SetDefault()
bool CSettingsBase::SetDefault (const std::string & id)
Sets the value of the setting with the given identifier to its default.
Parameters
id Setting identifier
Returns
True if setting the value to its default was successful, false otherwise
References m_settingsManager, and CSettingsManager::SetDefault().
SetDefaults()
void CSettingsBase::SetDefaults ()
Sets the value of all settings to their default.
References m_settingsManager, and CSettingsManager::SetDefaults().
SetInt()
bool CSettingsBase::SetInt (const std::string & id, int value)
Sets the integer value of the setting with the given identifier.
Parameters
id Setting identifier
value Integer value to set
Returns
True if setting the value was successful, false otherwise
References m_settingsManager, CSettingsManager::SetInt(), and value.
SetList()
bool CSettingsBase::SetList (const std::string & id, const std::vector< CVariant > & value)
Sets the values of the list setting with the given identifier.
Parameters
id Setting identifier
value Values to set
Returns
True if setting the values was successful, false otherwise
References CSettingsManager::GetSetting(), List, m_settingsManager, CSettingUtils::SetList(), and value.
SetLoaded()
void CSettingsBase::SetLoaded () virtual
Tells the settings system that all setting values have been loaded.
This manual trigger is necessary to enable the ISettingCallback methods being executed.
References m_settingsManager, and CSettingsManager::SetLoaded().
Referenced by ADDON::CAddonSettings::Load().
SetNumber()
bool CSettingsBase::SetNumber (const std::string & id, double value)
Sets the real number value of the setting with the given identifier.
Parameters
id Setting identifier
value Real number value to set
Returns
True if setting the value was successful, false otherwise
References m_settingsManager, CSettingsManager::SetNumber(), and value.
SetString()
bool CSettingsBase::SetString (const std::string & id, const std::string & value)
Sets the string value of the setting with the given identifier.
Parameters
id Setting identifier
value String value to set
Returns
True if setting the value was successful, false otherwise
References m_settingsManager, CSettingsManager::SetString(), and value.
ToggleBool()
bool CSettingsBase::ToggleBool (const std::string & id)
Toggles the boolean value of the setting with the given identifier.
Parameters
id Setting identifier
Returns
True if toggling the boolean value was successful, false otherwise
References m_settingsManager, and CSettingsManager::ToggleBool().
Uninitialize()
void CSettingsBase::Uninitialize () virtual
Uninitializes the settings system.
Unregisters all previously registered callbacks and destroys all setting objects.
References CSettingsManager::Clear(), m_critical, m_initialized, m_settingsManager, UninitializeConditions(), UninitializeISettingCallbacks(), UninitializeISettingsHandlers(), UninitializeISubSettings(), and UninitializeOptionFillers().
Referenced by ~CSettingsBase().
UninitializeConditions()
virtual void CSettingsBase::UninitializeConditions () inline protected virtual
Reimplemented in CSettings.
Referenced by Uninitialize().
UninitializeISettingCallbacks()
virtual void CSettingsBase::UninitializeISettingCallbacks () inline protected virtual
Reimplemented in CSettings.
Referenced by Uninitialize().
UninitializeISettingsHandlers()
virtual void CSettingsBase::UninitializeISettingsHandlers () inline protected virtual
Reimplemented in CSettings.
Referenced by Uninitialize().
UninitializeISubSettings()
virtual void CSettingsBase::UninitializeISubSettings () inline protected virtual
Reimplemented in CSettings.
Referenced by Uninitialize().
UninitializeOptionFillers()
virtual void CSettingsBase::UninitializeOptionFillers () inline protected virtual
Reimplemented in CSettings.
Referenced by Uninitialize().
Unload()
void CSettingsBase::Unload () virtual
Unloads the previously loaded setting values.
The values of all the settings are reset to their default values.
References m_settingsManager, and CSettingsManager::Unload().
Referenced by CSettings::Reset().
UnregisterCallback()
void CSettingsBase::UnregisterCallback (ISettingCallback * callback)
Unregisters the given ISettingCallback implementation.
Parameters
callback ISettingCallback implementation
References m_settingsManager, and CSettingsManager::UnregisterCallback().
Member Data Documentation
m_critical
CCriticalSection CSettingsBase::m_critical mutable protected
Referenced by CSettings::Clear(), Initialize(), CSettings::Initialize(), ADDON::CAddonSettings::Initialize(), ADDON::CAddonSettings::Load(), CSettings::Load(), CSettings::RegisterSubSettings(), ADDON::CAddonSettings::Save(), CSettings::Save(), Uninitialize(), and CSettings::UnregisterSubSettings().
m_initialized
bool CSettingsBase::m_initialized = false protected
Referenced by CSettings::Clear(), Initialize(), CSettings::Initialize(), ADDON::CAddonSettings::Initialize(), IsInitialized(), ADDON::CAddonSettings::Load(), ADDON::CAddonSettings::Save(), and Uninitialize().
m_settingsManager
CSettingsManager* CSettingsBase::m_settingsManager protected
Referenced by GetBool(), GetInt(), GetList(), GetNumber(), GetSection(), GetSections(), GetSetting(), CSettings::GetSettingsManager(), GetSettingsManager(), GetString(), Initialize(), InitializeDefinitionsFromXml(), IsInitialized(), IsLoaded(), LoadHiddenValuesFromXml(), LoadValuesFromXml(), LoadValuesFromXml(), RegisterCallback(), SaveValuesToXml(), SetBool(), SetDefault(), SetDefaults(), SetInt(), SetList(), SetLoaded(), SetNumber(), SetString(), ToggleBool(), Uninitialize(), Unload(), UnregisterCallback(), and ~CSettingsBase().
The documentation for this class was generated from the following files:
SettingsBase.h
SettingsBase.cpp