Kodi Documentation: ADDON::CVFSAddonCache Class Reference
ADDON::CVFSAddonCache Class Reference
#include <VFSEntry.h>
Public Member Functions
virtual ~CVFSAddonCache ()
void Init ()
void Deinit ()
const std::vector< VFSEntryPtr > GetAddonInstances ()
VFSEntryPtr GetAddonInstance (const std::string &strId)
Public Member Functions inherited from ADDON::CAddonDllInformer
virtual ~CAddonDllInformer ()=default
Protected Member Functions
void Update (const std::string &id)
void OnEvent (const AddonEvent &event)
bool IsInUse (const std::string &id) override
Protected Attributes
CCriticalSection m_critSection
std::vector< VFSEntryPtr > m_addonsInstances
Constructor & Destructor Documentation
~CVFSAddonCache()
ADDON::CVFSAddonCache::~CVFSAddonCache () virtual
References Deinit().
Member Function Documentation
Deinit()
void ADDON::CVFSAddonCache::Deinit ()
References ADDON::CAddonMgr::Events(), and CServiceBroker::GetAddonMgr().
Referenced by ~CVFSAddonCache().
GetAddonInstance()
VFSEntryPtr ADDON::CVFSAddonCache::GetAddonInstance (const std::string & strId)
References m_addonsInstances, and m_critSection.
GetAddonInstances()
const std::vector< VFSEntryPtr > ADDON::CVFSAddonCache::GetAddonInstances ()
References m_addonsInstances, and m_critSection.
Referenced by CGUIDialogSubtitleSettings::BrowseForSubtitle(), CApplication::CloseNetworkShares(), XFILE::CDirectoryFactory::Create(), XFILE::CFileDirectoryFactory::Create(), XFILE::CFileFactory::CreateLoader(), CMediaManager::GetNetworkLocations(), CApplication::ProcessSlow(), CApplication::Stop(), CUtil::SupportsWriteFileOperations(), and CGUIDialogNetworkSetup::UpdateAvailableProtocols().
Init()
void ADDON::CVFSAddonCache::Init ()
References CZeroconfBrowser::AddServiceType(), ADDON::CAddonMgr::Events(), ADDON::CAddonMgr::GetAddonInfos(), CServiceBroker::GetAddonMgr(), CZeroconfBrowser::GetInstance(), m_addonsInstances, m_critSection, OnEvent(), and ADDON::VFS.
IsInUse()
bool ADDON::CVFSAddonCache::IsInUse (const std::string & id) override protected virtual
Implements ADDON::CAddonDllInformer.
References m_addonsInstances, and m_critSection.
OnEvent()
void ADDON::CVFSAddonCache::OnEvent (const AddonEvent & event) protected
References ADDON::AddonEvent::addonId, CServiceBroker::GetAddonMgr(), CZeroconfBrowser::GetInstance(), ADDON::CAddonMgr::HasType(), m_addonsInstances, CZeroconfBrowser::RemoveServiceType(), Update, and ADDON::VFS.
Referenced by Init().
Update()
void ADDON::CVFSAddonCache::Update (const std::string & id) protected
References CZeroconfBrowser::AddServiceType(), ADDON::CAddonMgr::GetAddonInfo(), CServiceBroker::GetAddonMgr(), CZeroconfBrowser::GetInstance(), m_addonsInstances, m_critSection, and ADDON::VFS.
Member Data Documentation
m_addonsInstances
std::vector<VFSEntryPtr> ADDON::CVFSAddonCache::m_addonsInstances protected
Referenced by GetAddonInstance(), GetAddonInstances(), Init(), IsInUse(), OnEvent(), and Update().
m_critSection
CCriticalSection ADDON::CVFSAddonCache::m_critSection protected
Referenced by GetAddonInstance(), GetAddonInstances(), Init(), IsInUse(), and Update().
The documentation for this class was generated from the following files:
VFSEntry.h
VFSEntry.cpp