Kodi Documentation: PVR::CPVRGUIActionsDatabase Class Reference
PVR::CPVRGUIActionsDatabase Class Reference
#include <PVRGUIActionsDatabase.h>
Public Member Functions
CPVRGUIActionsDatabase ()=default
~CPVRGUIActionsDatabase () override=default
bool ResetDatabase (bool bResetEPGOnly)
Reset the TV database to it's initial state and delete all the data.
Public Member Functions inherited from PVR::IPVRComponent
virtual ~IPVRComponent ()=default
Private Member Functions
CPVRGUIActionsDatabase (const CPVRGUIActionsDatabase &)=delete
CPVRGUIActionsDatabase const & operator= (CPVRGUIActionsDatabase const &)=delete
Constructor & Destructor Documentation
CPVRGUIActionsDatabase() [1/2]
PVR::CPVRGUIActionsDatabase::CPVRGUIActionsDatabase () default
~CPVRGUIActionsDatabase()
PVR::CPVRGUIActionsDatabase::~CPVRGUIActionsDatabase () override default
CPVRGUIActionsDatabase() [2/2]
PVR::CPVRGUIActionsDatabase::CPVRGUIActionsDatabase (const CPVRGUIActionsDatabase &) private delete
Member Function Documentation
operator=()
CPVRGUIActionsDatabase const & PVR::CPVRGUIActionsDatabase::operator= (CPVRGUIActionsDatabase const &) private delete
ResetDatabase()
bool CPVRGUIActionsDatabase::ResetDatabase (bool bResetEPGOnly)
Reset the TV database to it's initial state and delete all the data.
Parameters
bResetEPGOnly True to only reset the EPG database, false to reset both PVR and EPG database.
Returns
true on success, false otherwise.
References CDatabase::Close(), CGUIWindow::Close(), PVR::EpgContainer, CVideoDatabase::EraseAllForPath(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, LOGPVR, CVideoDatabase::Open(), CGUIDialogProgress::Open(), PVR::CPVRRecordingsPath::PATH_RECORDINGS, PVR::CPVRManager::PlaybackState(), CGUIDialogProgress::Progress(), CDateTime::ResetTimezoneBias(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CGUIDialogProgress::SetPercentage(), CGUIDialogYesNo::ShowAndGetInput(), PVR::CPVRManager::Start(), PVR::CPVRManager::Stop(), PVR::SUCCESS, TMSG_MEDIA_STOP, and WINDOW_DIALOG_PROGRESS.
The documentation for this class was generated from the following files:
PVRGUIActionsDatabase.h
PVRGUIActionsDatabase.cpp