Kodi Documentation: KODI::RETRO::CRenderUtils Class Reference
KODI::RETRO::CRenderUtils Class Reference
#include <RenderUtils.h>
Static Public Member Functions
static void CalculateStretchMode (STRETCHMODE stretchMode, unsigned int rotationDegCCW, unsigned int sourceWidth, unsigned int sourceHeight, float screenWidth, float screenHeight, float &pixelRatio, float &zoomAmount)
static void CalcNormalRenderRect (const CRect &viewRect, float outputFrameRatio, float zoomAmount, CRect &destRect)
static void ClipRect (const CRect &viewRect, CRect &sourceRect, CRect &destRect)
static void CropSource (CRect &sourceRect, unsigned int rotationDegCCW, float viewWidth, float viewHeight, float sourceWidth, float sourceHeight, float destWidth, float destHeight)
static std::array< CPoint, 4 > ReorderDrawPoints (const CRect &destRect, unsigned int orientationDegCCW)
Member Function Documentation
CalcNormalRenderRect()
void CRenderUtils::CalcNormalRenderRect (const CRect & viewRect, float outputFrameRatio, float zoomAmount, CRect & destRect) static
References CRectGen< T >::Height(), MathUtils::round_int(), CRectGen< T >::SetRect(), CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by KODI::RETRO::CRPBaseRenderer::ManageRenderArea().
CalculateStretchMode()
void CRenderUtils::CalculateStretchMode (STRETCHMODE stretchMode, unsigned int rotationDegCCW, unsigned int sourceWidth, unsigned int sourceHeight, float screenWidth, float screenHeight, float & pixelRatio, float & zoomAmount) static
References KODI::RETRO::Fullscreen, KODI::RETRO::Normal, KODI::RETRO::Original, KODI::RETRO::Stretch4x3, and KODI::RETRO::Zoom.
Referenced by KODI::RETRO::CRPBaseRenderer::ManageRenderArea().
ClipRect()
void CRenderUtils::ClipRect (const CRect & viewRect, CRect & sourceRect, CRect & destRect) static
References CRectGen< T >::Height(), CRectGen< T >::Intersect(), CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by KODI::RETRO::CRPBaseRenderer::ManageRenderArea().
CropSource()
void CRenderUtils::CropSource (CRect & sourceRect, unsigned int rotationDegCCW, float viewWidth, float viewHeight, float sourceWidth, float sourceHeight, float destWidth, float destHeight) static
References CRectGen< T >::Height(), CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by KODI::RETRO::CRPBaseRenderer::ManageRenderArea().
ReorderDrawPoints()
std::array< CPoint, 4 > CRenderUtils::ReorderDrawPoints (const CRect & destRect, unsigned int orientationDegCCW) static
References CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by KODI::RETRO::CRPBaseRenderer::ManageRenderArea().
The documentation for this class was generated from the following files:
RenderUtils.h
RenderUtils.cpp