Kodi Documentation: CBlurayCallback Class Reference
CBlurayCallback Class Reference
#include <BlurayCallback.h>
Static Public Member Functions
static void bluray_logger (const char *msg)
static void dir_close (BD_DIR_H *dir)
static BD_DIR_H * dir_open (void *handle, const char *rel_path)
static int dir_read (BD_DIR_H *dir, BD_DIRENT *entry)
static void file_close (BD_FILE_H *file)
static int file_eof (BD_FILE_H *file)
static BD_FILE_H * file_open (void *handle, const char *rel_path)
static int64_t file_read (BD_FILE_H *file, uint8_t *buf, int64_t size)
static int64_t file_seek (BD_FILE_H *file, int64_t offset, int32_t origin)
static int64_t file_tell (BD_FILE_H *file)
static int64_t file_write (BD_FILE_H *file, const uint8_t *buf, int64_t size)
Private Member Functions
CBlurayCallback ()=default
~CBlurayCallback ()=default
Constructor & Destructor Documentation
CBlurayCallback()
CBlurayCallback::CBlurayCallback () private default
~CBlurayCallback()
CBlurayCallback::~CBlurayCallback () private default
Member Function Documentation
bluray_logger()
void CBlurayCallback::bluray_logger (const char * msg) static
References CLog::Log(), and LOGDEBUG.
Referenced by XFILE::CBlurayDirectory::InitializeBluray(), and CDVDInputStreamBluray::Open().
dir_close()
void CBlurayCallback::dir_close (BD_DIR_H * dir) static
References CLog::Log(), and LOGDEBUG.
Referenced by dir_open().
dir_open()
BD_DIR_H * CBlurayCallback::dir_open (void * handle, const char * rel_path) static
References URIUtils::AddFileToFolder(), dir_close(), XFILE::DIR_FLAG_DEFAULTS, dir_read(), XFILE::CFile::Exists(), XFILE::CDirectory::GetDirectory(), URIUtils::HasSlashAtEnd(), SDirState::list, CLog::Log(), LOGDEBUG, and URIUtils::RemoveSlashAtEnd().
Referenced by XFILE::CBlurayDirectory::InitializeBluray(), and CDVDInputStreamBluray::Open().
dir_read()
int CBlurayCallback::dir_read (BD_DIR_H * dir, BD_DIRENT * entry) static
References SDirState::curr, CGUIListItem::GetLabel(), SDirState::list, and CFileItemList::Size().
Referenced by dir_open().
file_close()
void CBlurayCallback::file_close (BD_FILE_H * file) static
Referenced by file_open().
file_eof()
int CBlurayCallback::file_eof (BD_FILE_H * file) static
References XFILE::CFile::GetLength(), and XFILE::CFile::GetPosition().
Referenced by file_open().
file_open()
BD_FILE_H * CBlurayCallback::file_open (void * handle, const char * rel_path) static
References URIUtils::AddFileToFolder(), file_close(), file_eof(), file_read(), file_seek(), file_tell(), file_write(), CLog::Log(), LOGDEBUG, and XFILE::CFile::Open().
Referenced by XFILE::CBlurayDirectory::InitializeBluray(), and CDVDInputStreamBluray::Open().
file_read()
int64_t CBlurayCallback::file_read (BD_FILE_H * file, uint8_t * buf, int64_t size) static
References int64_t().
Referenced by file_open().
file_seek()
int64_t CBlurayCallback::file_seek (BD_FILE_H * file, int64_t offset, int32_t origin) static
References Seek().
Referenced by file_open().
file_tell()
int64_t CBlurayCallback::file_tell (BD_FILE_H * file) static
Referenced by file_open().
file_write()
int64_t CBlurayCallback::file_write (BD_FILE_H * file, const uint8_t * buf, int64_t size) static
References int64_t().
Referenced by file_open().
The documentation for this class was generated from the following files:
BlurayCallback.h
BlurayCallback.cpp