Kodi Documentation: PVR::CPVRClients Class Reference
PVR::CPVRClients Class Reference
#include <PVRClients.h>
Public Member Functions
CPVRClients ()
~CPVRClients () override
void Start ()
Start all clients.
void Stop ()
Stop all clients.
void Continue ()
Continue all clients.
void UpdateClients (const std::string &changedAddonId="", ADDON::AddonInstanceId changedInstanceId=ADDON::ADDON_SINGLETON_INSTANCE_ID)
Update all clients, sync with Addon Manager state (start, restart, shutdown clients).
bool RequestRestart (const std::string &addonId, ADDON::AddonInstanceId instanceId, bool bDataChanged) override
Restart a single client add-on.
bool StopClient (int clientId, bool restart)
Stop a client.
void OnAddonEvent (const ADDON::AddonEvent &event)
Handle addon events (enable, disable, ...).
int CreatedClientAmount () const
Get the number of created clients.
bool HasCreatedClients () const
Check whether there are any created clients.
bool IsCreatedClient (int iClientId) const
Check whether a given client ID points to a created client.
std::shared_ptr< CPVRClient > GetCreatedClient (int clientId) const
Get the the client for the given client id, if it is created.
CPVRClientMap GetCreatedClients () const
Get all created clients.
int GetFirstCreatedClientID () const
Get the ID of the first created client.
bool HasIgnoredClients () const
Check whether there are any created, but not (yet) connected clients.
int EnabledClientAmount () const
Get the number of enabled clients.
bool IsEnabledClient (int clientId) const
Check whether a given client ID points to an enabled client.
std::vector< CVariant > GetEnabledClientInfos () const
Get a list of the enabled client infos.
std::vector< CVariant > GetClientProviderInfos () const
Get info required for providers. Include both enabled and disabled PVR add-ons.
general methods
std::vector< SBackend > GetBackendProperties () const
Returns properties about all created clients.
Timer methods
bool GetTimers (const std::vector< std::shared_ptr< CPVRClient > > &clients, CPVRTimersContainer *timers, std::vector< int > &failedClients) const
Get all timers from the given clients.
PVR_ERROR UpdateTimerTypes (const std::vector< std::shared_ptr< CPVRClient > > &clients, std::vector< int > &failedClients)
Update all timer types from the given clients.
const std::vector< std::shared_ptr< CPVRTimerType > > GetTimerTypes () const
Get all timer types supported by the backends, without updating them from the backends.
Recording methods
PVR_ERROR GetRecordings (const std::vector< std::shared_ptr< CPVRClient > > &clients, CPVRRecordings *recordings, bool deleted, std::vector< int > &failedClients) const
Get all recordings from the given clients.
PVR_ERROR DeleteAllRecordingsFromTrash ()
Delete all "soft" deleted recordings permanently on the backend.
EPG methods
PVR_ERROR SetEPGMaxPastDays (int iPastDays)
Tell all clients the past time frame to use when notifying epg events back to Kodi.
PVR_ERROR SetEPGMaxFutureDays (int iFutureDays)
Tell all clients the future time frame to use when notifying epg events back to Kodi.
Channel methods
PVR_ERROR GetChannels (const std::vector< std::shared_ptr< CPVRClient > > &clients, bool bRadio, std::vector< std::shared_ptr< CPVRChannel > > &channels, std::vector< int > &failedClients) const
Get all channels from the given clients.
PVR_ERROR GetProviders (const std::vector< std::shared_ptr< CPVRClient > > &clients, CPVRProvidersContainer *providers, std::vector< int > &failedClients) const
Get all providers from backends.
PVR_ERROR GetChannelGroups (const std::vector< std::shared_ptr< CPVRClient > > &clients, CPVRChannelGroups *groups, std::vector< int > &failedClients) const
Get all channel groups from the given clients.
PVR_ERROR GetChannelGroupMembers (const std::vector< std::shared_ptr< CPVRClient > > &clients, CPVRChannelGroup *group, std::vector< std::shared_ptr< CPVRChannelGroupMember > > &groupMembers, std::vector< int > &failedClients) const
Get all group members of a channel group from the given clients.
std::vector< std::shared_ptr< CPVRClient > > GetClientsSupportingChannelScan () const
Get a list of clients providing a channel scan dialog.
std::vector< std::shared_ptr< CPVRClient > > GetClientsSupportingChannelSettings (bool bRadio) const
Get a list of clients providing a channel settings dialog.
bool AnyClientSupportingRecordingsSize () const
Get whether or not any client supports recording size.
bool AnyClientSupportingEPG () const
Get whether or not any client supports EPG.
bool AnyClientSupportingRecordings () const
Get whether or not any client supports recordings.
bool AnyClientSupportingRecordingsDelete () const
Get whether or not any client supports recordings delete.
Public Member Functions inherited from ADDON::IAddonMgrCallback
virtual ~IAddonMgrCallback ()=default
Power management methods
typedef std::function< PVR_ERROR(const std::shared_ptr< CPVRClient > &)> PVRClientFunction
CCriticalSection m_critSection
CPVRClientMap m_clientMap
void OnSystemSleep ()
Propagate "system sleep" event to clients.
void OnSystemWake ()
Propagate "system wakeup" event to clients.
void OnPowerSavingActivated ()
Propagate "power saving activated" event to clients.
void OnPowerSavingDeactivated ()
Propagate "power saving deactivated" event to clients.
void ConnectionStateChange (CPVRClient *client, const std::string &strConnectionString, PVR_CONNECTION_STATE newState, const std::string &strMessage)
Notify a change of an addon connection state.
std::vector< ADDON::AddonInstanceId > GetKnownInstanceIds (const std::string &addonID) const
Get the known instance ids for a given addon id.
bool GetAddonsWithStatus (const std::string &changedAddonId, std::vector< std::pair< std::shared_ptr< ADDON::CAddonInfo >, bool > > &addonsWithStatus) const
std::vector< std::pair< ADDON::AddonInstanceId, bool > > GetInstanceIdsWithStatus (const std::shared_ptr< ADDON::CAddonInfo > &addon, bool addonIsEnabled) const
std::shared_ptr< CPVRClient > GetClient (int clientId) const
Get the client instance for a given client id.
bool IsKnownClient (int iClientId) const
Check whether a client is known.
PVR_ERROR GetCallableClients (CPVRClientMap &clientsReady, std::vector< int > &clientsNotReady) const
Get all created clients and clients not (yet) ready to use.
PVR_ERROR ForClients (const char *strFunctionName, const std::vector< std::shared_ptr< CPVRClient > > &clients, const PVRClientFunction &function, std::vector< int > &failedClients) const
Wraps calls to the given clients in order to do common pre and post function invocation actions.
PVR_ERROR ForCreatedClients (const char *strFunctionName, const PVRClientFunction &function) const
Wraps calls to all created clients in order to do common pre and post function invocation actions.
PVR_ERROR ForCreatedClients (const char *strFunctionName, const PVRClientFunction &function, std::vector< int > &failedClients) const
Wraps calls to all created clients in order to do common pre and post function invocation actions.
Member Typedef Documentation
PVRClientFunction
typedef std::function<PVR_ERROR(const std::shared_ptr<CPVRClient>&)> PVR::CPVRClients::PVRClientFunction private
Constructor & Destructor Documentation
CPVRClients()
CPVRClients::CPVRClients ()
References ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), OnAddonEvent(), and ADDON::CAddonMgr::RegisterAddonMgrCallback().
~CPVRClients()
CPVRClients::~CPVRClients () override
References ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), m_clientMap, and ADDON::CAddonMgr::UnregisterAddonMgrCallback().
Member Function Documentation
AnyClientSupportingEPG()
bool CPVRClients::AnyClientSupportingEPG () const
Get whether or not any client supports EPG.
Returns
True if any client supports EPG.
References m_clientMap, and m_critSection.
AnyClientSupportingRecordings()
bool CPVRClients::AnyClientSupportingRecordings () const
Get whether or not any client supports recordings.
Returns
True if any client supports recordings.
References m_clientMap, and m_critSection.
AnyClientSupportingRecordingsDelete()
bool CPVRClients::AnyClientSupportingRecordingsDelete () const
Get whether or not any client supports recordings delete.
Returns
True if any client supports recordings delete.
References m_clientMap, and m_critSection.
AnyClientSupportingRecordingsSize()
bool CPVRClients::AnyClientSupportingRecordingsSize () const
Get whether or not any client supports recording size.
Returns
True if any client supports recording size.
References m_clientMap, and m_critSection.
ConnectionStateChange()
void CPVRClients::ConnectionStateChange (CPVRClient * client, const std::string & strConnectionString, PVR_CONNECTION_STATE newState, const std::string & strMessage)
Notify a change of an addon connection state.
Parameters
client The changed client.
strConnectionString A human-readable string providing additional information.
newState The new connection state.
strMessage A human readable string replacing default state message.
References Basic, Error, g_localizeStrings, CLocalizeStrings::Get(), PVR::CPVRClient::GetFullClientName(), CServiceBroker::GetJobManager(), PVR::CPVRClient::GetPreviousConnectionState(), ADDON::IAddonInstanceHandler::Icon(), Information, LOGERROR, PVR_CONNECTION_STATE_ACCESS_DENIED, PVR_CONNECTION_STATE_CONNECTED, PVR_CONNECTION_STATE_CONNECTING, PVR_CONNECTION_STATE_DISCONNECTED, PVR_CONNECTION_STATE_SERVER_MISMATCH, PVR_CONNECTION_STATE_SERVER_UNREACHABLE, PVR_CONNECTION_STATE_UNKNOWN, and PVR_CONNECTION_STATE_VERSION_MISMATCH.
Continue()
void CPVRClients::Continue ()
Continue all clients.
References m_clientMap, and m_critSection.
CreatedClientAmount()
int CPVRClients::CreatedClientAmount () const
Get the number of created clients.
Returns
The amount of created clients.
References m_clientMap, and m_critSection.
DeleteAllRecordingsFromTrash()
PVR_ERROR CPVRClients::DeleteAllRecordingsFromTrash ()
Delete all "soft" deleted recordings permanently on the backend.
Returns
PVR_ERROR_NO_ERROR if the operation succeeded, the respective PVR_ERROR value otherwise.
References ForCreatedClients().
EnabledClientAmount()
int CPVRClients::EnabledClientAmount () const
Get the number of enabled clients.
Returns
The amount of enabled clients.
References CServiceBroker::GetAddonMgr(), m_clientMap, and m_critSection.
ForClients()
PVR_ERROR CPVRClients::ForClients (const char * strFunctionName, const std::vector< std::shared_ptr< CPVRClient > > & clients, const PVRClientFunction & function, std::vector< int > & failedClients) const private
Wraps calls to the given clients in order to do common pre and post function invocation actions.
Parameters
strFunctionName The function name, for logging purposes.
clients The clients to wrap.
function The function to wrap. It has to have return type PVR_ERROR and must take a const reference to a std::shared_ptr<CPVRClient> as parameter.
failedClients Contains a list of the ids of clients for that the call failed, if any.
Returns
PVR_ERROR_NO_ERROR on success, any other PVR_ERROR_* value otherwise.
References ForCreatedClients(), LOGDEBUG, LOGPVR, m_clientMap, m_critSection, PVR_ERROR_NO_ERROR, and PVR_ERROR_NOT_IMPLEMENTED.
Referenced by GetChannelGroupMembers(), GetChannelGroups(), GetChannels(), GetProviders(), GetRecordings(), GetTimers(), and UpdateTimerTypes().
ForCreatedClients() [1/2]
PVR_ERROR CPVRClients::ForCreatedClients (const char * strFunctionName, const PVRClientFunction & function) const private
Wraps calls to all created clients in order to do common pre and post function invocation actions.
Parameters
strFunctionName The function name, for logging purposes.
function The function to wrap. It has to have return type PVR_ERROR and must take a const reference to a std::shared_ptr<CPVRClient> as parameter.
Returns
PVR_ERROR_NO_ERROR on success, any other PVR_ERROR_* value otherwise.
References ForCreatedClients().
Referenced by DeleteAllRecordingsFromTrash(), ForClients(), ForCreatedClients(), GetBackendProperties(), OnPowerSavingActivated(), OnPowerSavingDeactivated(), OnSystemSleep(), OnSystemWake(), SetEPGMaxFutureDays(), and SetEPGMaxPastDays().
ForCreatedClients() [2/2]
PVR_ERROR CPVRClients::ForCreatedClients (const char * strFunctionName, const PVRClientFunction & function, std::vector< int > & failedClients) const private
Wraps calls to all created clients in order to do common pre and post function invocation actions.
Parameters
strFunctionName The function name, for logging purposes.
function The function to wrap. It has to have return type PVR_ERROR and must take a const reference to a std::shared_ptr<CPVRClient> as parameter.
failedClients Contains a list of the ids of clients for that the call failed, if any.
Returns
PVR_ERROR_NO_ERROR on success, any other PVR_ERROR_* value otherwise.
References GetCallableClients(), GetClient(), LOGDEBUG, LOGPVR, PVR_ERROR_NO_ERROR, and PVR_ERROR_NOT_IMPLEMENTED.
GetAddonsWithStatus()
bool CPVRClients::GetAddonsWithStatus (const std::string & changedAddonId, std::vector< std::pair< std::shared_ptr< ADDON::CAddonInfo >, bool > > & addonsWithStatus) const private
References addons, ADDON::CAddonMgr::GetAddonInfos(), CServiceBroker::GetAddonMgr(), and ADDON::CAddonMgr::IsAddonDisabled().
Referenced by UpdateClients().
GetBackendProperties()
std::vector< SBackend > CPVRClients::GetBackendProperties () const
Returns properties about all created clients.
Returns
the properties
References PVR::SBackend::clientname, PVR::SBackend::diskTotal, PVR::SBackend::diskUsed, ForCreatedClients(), PVR::SBackend::host, PVR::SBackend::instancename, PVR::SBackend::name, PVR::SBackend::numChannelGroups, PVR::SBackend::numChannels, PVR::SBackend::numDeletedRecordings, PVR::SBackend::numProviders, PVR::SBackend::numRecordings, PVR::SBackend::numTimers, PVR_ERROR_NO_ERROR, and PVR::SBackend::version.
GetCallableClients()
PVR_ERROR CPVRClients::GetCallableClients (CPVRClientMap & clientsReady, std::vector< int > & clientsNotReady) const private
Get all created clients and clients not (yet) ready to use.
Parameters
clientsReady Store the created clients in this map.
clientsNotReady Store the the ids of the not (yet) ready clients in this list.
Returns
PVR_ERROR_NO_ERROR in case all clients are ready, PVR_ERROR_SERVER_ERROR otherwise.
References addons, ADDON::CAddonMgr::GetAddonInfos(), CServiceBroker::GetAddonMgr(), GetClient(), PVR::CPVRClientUID::GetUID(), PVR_ERROR_NO_ERROR, and PVR_ERROR_SERVER_ERROR.
Referenced by ForCreatedClients().
GetChannelGroupMembers()
PVR_ERROR CPVRClients::GetChannelGroupMembers (const std::vector< std::shared_ptr< CPVRClient > > & clients, CPVRChannelGroup * group, std::vector< std::shared_ptr< CPVRChannelGroupMember > > & groupMembers, std::vector< int > & failedClients) const
Get all group members of a channel group from the given clients.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
group The group to get the member for.
groupMembers The container for the group members.
failedClients in case of errors will contain the ids of the clients for which the channel group members could not be obtained.
Returns
PVR_ERROR_NO_ERROR if the channel group members were fetched successfully, last error otherwise.
References ForClients().
GetChannelGroups()
PVR_ERROR CPVRClients::GetChannelGroups (const std::vector< std::shared_ptr< CPVRClient > > & clients, CPVRChannelGroups * groups, std::vector< int > & failedClients) const
Get all channel groups from the given clients.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
groups Store the channel groups in this container.
failedClients in case of errors will contain the ids of the clients for which the channel groups could not be obtained.
Returns
PVR_ERROR_NO_ERROR if the channel groups were fetched successfully, last error otherwise.
References ForClients().
GetChannels()
PVR_ERROR CPVRClients::GetChannels (const std::vector< std::shared_ptr< CPVRClient > > & clients, bool bRadio, std::vector< std::shared_ptr< CPVRChannel > > & channels, std::vector< int > & failedClients) const
Get all channels from the given clients.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
bRadio Whether to fetch radio or TV channels.
channels The container to store the channels.
failedClients in case of errors will contain the ids of the clients for which the channels could not be obtained.
Returns
PVR_ERROR_NO_ERROR if the channels were fetched successfully, last error otherwise.
References ForClients().
GetClient()
std::shared_ptr< CPVRClient > CPVRClients::GetClient (int clientId) const private
Get the client instance for a given client id.
Parameters
clientId The id of the client to get.
Returns
The client if found, nullptr otherwise.
References m_clientMap, m_critSection, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by ForCreatedClients(), GetCallableClients(), GetClientProviderInfos(), GetCreatedClient(), IsEnabledClient(), StopClient(), and UpdateClients().
GetClientProviderInfos()
std::vector< CVariant > CPVRClients::GetClientProviderInfos () const
Get info required for providers. Include both enabled and disabled PVR add-ons.
Returns
A list containing the information required to create client providers.
References ADDON::CAddonMgr::GetAddonInfos(), CServiceBroker::GetAddonMgr(), GetClient(), PVR::CPVRClientUID::GetUID(), ADDON::CAddonMgr::IsAddonDisabled(), m_critSection, and CVariant::VariantTypeObject.
GetClientsSupportingChannelScan()
std::vector< std::shared_ptr< CPVRClient > > CPVRClients::GetClientsSupportingChannelScan () const
Get a list of clients providing a channel scan dialog.
Returns
All clients supporting channel scan.
References m_clientMap, and m_critSection.
GetClientsSupportingChannelSettings()
std::vector< std::shared_ptr< CPVRClient > > CPVRClients::GetClientsSupportingChannelSettings (bool bRadio) const
Get a list of clients providing a channel settings dialog.
Returns
All clients supporting channel settings.
References m_clientMap, m_critSection, PVR::CPVRClientCapabilities::SupportsChannelSettings(), PVR::CPVRClientCapabilities::SupportsRadio(), and PVR::CPVRClientCapabilities::SupportsTV().
GetCreatedClient()
std::shared_ptr< CPVRClient > CPVRClients::GetCreatedClient (int clientId) const
Get the the client for the given client id, if it is created.
Parameters
clientId The ID of the client to get.
Returns
The client if found, nullptr otherwise.
References GetClient().
Referenced by IsCreatedClient().
GetCreatedClients()
CPVRClientMap CPVRClients::GetCreatedClients () const
Get all created clients.
Returns
All created clients.
References m_clientMap, and m_critSection.
GetEnabledClientInfos()
std::vector< CVariant > CPVRClients::GetEnabledClientInfos () const
Get a list of the enabled client infos.
Returns
A list of enabled client infos.
References ADDON::CAddonMgr::GetAddonInfo(), CServiceBroker::GetAddonMgr(), m_clientMap, m_critSection, CVariant::push_back(), and CVariant::VariantTypeObject.
GetFirstCreatedClientID()
int CPVRClients::GetFirstCreatedClientID () const
Get the ID of the first created client.
Returns
the ID or PVR_CLIENT_INVALID_UID if no clients are created;
References m_clientMap, m_critSection, and PVR::PVR_CLIENT_INVALID_UID.
GetInstanceIdsWithStatus()
std::vector< std::pair< ADDON::AddonInstanceId, bool > > CPVRClients::GetInstanceIdsWithStatus (const std::shared_ptr< ADDON::CAddonInfo > & addon, bool addonIsEnabled) const private
References GetKnownInstanceIds().
Referenced by UpdateClients().
GetKnownInstanceIds()
std::vector< ADDON::AddonInstanceId > CPVRClients::GetKnownInstanceIds (const std::string & addonID) const private
Get the known instance ids for a given addon id.
Parameters
addonID The addon id.
Returns
The list of known instance ids.
References m_clientMap, and m_critSection.
Referenced by GetInstanceIdsWithStatus().
GetProviders()
PVR_ERROR CPVRClients::GetProviders (const std::vector< std::shared_ptr< CPVRClient > > & clients, CPVRProvidersContainer * providers, std::vector< int > & failedClients) const
Get all providers from backends.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
group The container to store the providers in.
failedClients in case of errors will contain the ids of the clients for which the providers could not be obtained.
Returns
PVR_ERROR_NO_ERROR if the providers were fetched successfully, last error otherwise.
References ForClients().
GetRecordings()
PVR_ERROR CPVRClients::GetRecordings (const std::vector< std::shared_ptr< CPVRClient > > & clients, CPVRRecordings * recordings, bool deleted, std::vector< int > & failedClients) const
Get all recordings from the given clients.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
recordings Store the recordings in this container.
deleted If true, return deleted recordings, return not deleted recordings otherwise.
failedClients in case of errors will contain the ids of the clients for which the recordings could not be obtained.
Returns
PVR_ERROR_NO_ERROR if the operation succeeded, the respective PVR_ERROR value otherwise.
References ForClients().
GetTimers()
bool CPVRClients::GetTimers (const std::vector< std::shared_ptr< CPVRClient > > & clients, CPVRTimersContainer * timers, std::vector< int > & failedClients) const
Get all timers from the given clients.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
timers Store the timers in this container.
failedClients in case of errors will contain the ids of the clients for which the timers could not be obtained.
Returns
true on success for all clients, false in case of error for at least one client.
References ForClients(), and PVR_ERROR_NO_ERROR.
GetTimerTypes()
const std::vector< std::shared_ptr< CPVRTimerType > > CPVRClients::GetTimerTypes () const
Get all timer types supported by the backends, without updating them from the backends.
Returns
the types.
References m_clientMap, m_critSection, and ADDON::types.
HasCreatedClients()
bool CPVRClients::HasCreatedClients () const
Check whether there are any created clients.
Returns
True if at least one client is created.
References m_clientMap, and m_critSection.
HasIgnoredClients()
bool CPVRClients::HasIgnoredClients () const
Check whether there are any created, but not (yet) connected clients.
Returns
True if at least one client is ignored.
References m_clientMap, and m_critSection.
IsCreatedClient()
bool CPVRClients::IsCreatedClient (int iClientId) const
Check whether a given client ID points to a created client.
Parameters
iClientId The client ID.
Returns
True if the the client ID represents a created client, false otherwise.
References GetCreatedClient().
Referenced by UpdateClients().
IsEnabledClient()
bool CPVRClients::IsEnabledClient (int clientId) const
Check whether a given client ID points to an enabled client.
Parameters
clientId The client ID.
Returns
True if the the client ID represents an enabled client, false otherwise.
References CServiceBroker::GetAddonMgr(), GetClient(), and ADDON::CAddonMgr::IsAddonDisabled().
IsKnownClient()
bool CPVRClients::IsKnownClient (int iClientId) const private
Check whether a client is known.
Parameters
iClientId The id of the client to check.
Returns
True if this client is known, false otherwise.
References m_clientMap, and m_critSection.
Referenced by UpdateClients().
OnAddonEvent()
void CPVRClients::OnAddonEvent (const ADDON::AddonEvent & event)
Handle addon events (enable, disable, ...).
Parameters
event The addon event.
References CServiceBroker::GetAddonMgr(), CServiceBroker::GetJobManager(), and UpdateClients().
Referenced by CPVRClients().
OnPowerSavingActivated()
void CPVRClients::OnPowerSavingActivated ()
Propagate "power saving activated" event to clients.
References ForCreatedClients(), and PVR_ERROR_NO_ERROR.
OnPowerSavingDeactivated()
void CPVRClients::OnPowerSavingDeactivated ()
Propagate "power saving deactivated" event to clients.
References ForCreatedClients(), and PVR_ERROR_NO_ERROR.
OnSystemSleep()
void CPVRClients::OnSystemSleep ()
Propagate "system sleep" event to clients.
References ForCreatedClients(), and PVR_ERROR_NO_ERROR.
OnSystemWake()
void CPVRClients::OnSystemWake ()
Propagate "system wakeup" event to clients.
References ForCreatedClients(), and PVR_ERROR_NO_ERROR.
RequestRestart()
bool CPVRClients::RequestRestart (const std::string & addonId, ADDON::AddonInstanceId instanceId, bool bDataChanged) override virtual
Restart a single client add-on.
Parameters
addonId The add-on to restart.
instanceId Instance identifier to use
bDataChanged True if the client's data changed, false otherwise (unused).
Returns
True if the client was found and restarted, false otherwise.
Implements ADDON::IAddonMgrCallback.
References CServiceBroker::GetJobManager(), and UpdateClients().
SetEPGMaxFutureDays()
PVR_ERROR CPVRClients::SetEPGMaxFutureDays (int iFutureDays)
Tell all clients the future time frame to use when notifying epg events back to Kodi.
The clients might push epg events asynchronously to Kodi using the callback function EpgEventStateChange. To be able to only push events that are actually of interest for Kodi, clients need to know about the future epg time frame Kodi uses.
Parameters
[in] iFutureDays number of days from "now". EPG_TIMEFRAME_UNLIMITED means that Kodi is interested in all epg events, regardless of event times.
Returns
PVR_ERROR_NO_ERROR if the operation succeeded, the respective PVR_ERROR value otherwise.
References ForCreatedClients().
SetEPGMaxPastDays()
PVR_ERROR CPVRClients::SetEPGMaxPastDays (int iPastDays)
Tell all clients the past time frame to use when notifying epg events back to Kodi.
The clients might push epg events asynchronously to Kodi using the callback function EpgEventStateChange. To be able to only push events that are actually of interest for Kodi, clients need to know about the future epg time frame Kodi uses.
Parameters
[in] iPastDays number of days before "now". EPG_TIMEFRAME_UNLIMITED means that Kodi is interested in all epg events, regardless of event times.
Returns
PVR_ERROR_NO_ERROR if the operation succeeded, the respective PVR_ERROR value otherwise.
References ForCreatedClients().
Start()
void CPVRClients::Start ()
Start all clients.
References UpdateClients().
Stop()
void CPVRClients::Stop ()
Stop all clients.
References m_clientMap, and m_critSection.
StopClient()
bool CPVRClients::StopClient (int clientId, bool restart)
Stop a client.
Parameters
clientId The id of the client to stop.
restart If true, restart the client.
Returns
True if the client was found, false otherwise.
References CServiceBroker::GetAppMessenger(), GetClient(), CServiceBroker::GetPVRManager(), m_clientMap, m_critSection, restart(), and TMSG_MEDIA_STOP.
Referenced by UpdateClients().
UpdateClients()
void CPVRClients::UpdateClients (const std::string & changedAddonId = "", ADDON::AddonInstanceId changedInstanceId = ADDON::ADDON_SINGLETON_INSTANCE_ID)
Update all clients, sync with Addon Manager state (start, restart, shutdown clients).
Parameters
changedAddonId The id of the changed addon, empty string denotes 'any addon'.
changedInstanceId The Identifier of the changed add-on instance
References ADDON::ADDON_SINGLETON_INSTANCE_ID, ADDON_STATUS_OK, ADDON_STATUS_PERMANENT_FAILURE, ADDON::CAddonMgr::DisableAddon(), Error, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), GetAddonsWithStatus(), GetClient(), GetInstanceIdsWithStatus(), CServiceBroker::GetJobManager(), CServiceBroker::GetPVRManager(), PVR::CPVRClientUID::GetUID(), IsCreatedClient(), IsKnownClient(), LOGINFO, m_clientMap, m_critSection, PVR::CPVRManager::Start(), PVR::CPVRManager::Stop(), and StopClient().
Referenced by OnAddonEvent(), RequestRestart(), and Start().
UpdateTimerTypes()
PVR_ERROR CPVRClients::UpdateTimerTypes (const std::vector< std::shared_ptr< CPVRClient > > & clients, std::vector< int > & failedClients)
Update all timer types from the given clients.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
failedClients in case of errors will contain the ids of the clients for which the timer types could not be obtained.
Returns
PVR_ERROR_NO_ERROR if the operation succeeded, the respective PVR_ERROR value otherwise.
References ForClients().
Member Data Documentation
m_clientMap
CPVRClientMap PVR::CPVRClients::m_clientMap private
Referenced by AnyClientSupportingEPG(), AnyClientSupportingRecordings(), AnyClientSupportingRecordingsDelete(), AnyClientSupportingRecordingsSize(), Continue(), CreatedClientAmount(), EnabledClientAmount(), ForClients(), GetClient(), GetClientsSupportingChannelScan(), GetClientsSupportingChannelSettings(), GetCreatedClients(), GetEnabledClientInfos(), GetFirstCreatedClientID(), GetKnownInstanceIds(), GetTimerTypes(), HasCreatedClients(), HasIgnoredClients(), IsKnownClient(), Stop(), StopClient(), UpdateClients(), and ~CPVRClients().
m_critSection
CCriticalSection PVR::CPVRClients::m_critSection mutable private
Referenced by AnyClientSupportingEPG(), AnyClientSupportingRecordings(), AnyClientSupportingRecordingsDelete(), AnyClientSupportingRecordingsSize(), Continue(), CreatedClientAmount(), EnabledClientAmount(), ForClients(), GetClient(), GetClientProviderInfos(), GetClientsSupportingChannelScan(), GetClientsSupportingChannelSettings(), GetCreatedClients(), GetEnabledClientInfos(), GetFirstCreatedClientID(), GetKnownInstanceIds(), GetTimerTypes(), HasCreatedClients(), HasIgnoredClients(), IsKnownClient(), Stop(), StopClient(), and UpdateClients().
The documentation for this class was generated from the following files:
PVRClients.h
PVRClients.cpp