Kodi Documentation: CWebSocketV8 Class Reference
CWebSocketV8 Class Reference
#include <WebSocketV8.h>
Public Member Functions
CWebSocketV8 ()
bool Handshake (const char *data, size_t length, std::string &response) override
const CWebSocketFrame * Ping (const char *data=NULL) const override
const CWebSocketFrame * Pong (const char *data, uint32_t length) const override
const CWebSocketFrame * Close (WebSocketCloseReason reason=WebSocketCloseNormal, const std::string &message="") override
void Fail () override
Public Member Functions inherited from CWebSocket
CWebSocket ()
virtual ~CWebSocket ()
int GetVersion ()
WebSocketState GetState ()
virtual const CWebSocketMessage * Handle (const char *&buffer, size_t &length, bool &send)
virtual const CWebSocketMessage * Send (WebSocketFrameOpcode opcode, const char *data=NULL, uint32_t length=0)
Protected Member Functions
CWebSocketFrame * GetFrame (const char *data, uint64_t length) override
CWebSocketFrame * GetFrame (WebSocketFrameOpcode opcode, const char *data=NULL, uint32_t length=0, bool final=true, bool masked=false, int32_t mask=0, int8_t extension=0) override
CWebSocketMessage * GetMessage () override
virtual const CWebSocketFrame * close (WebSocketCloseReason reason=WebSocketCloseNormal, const std::string &message="")
std::string calculateKey (const std::string &key)
Additional Inherited Members
Protected Attributes inherited from CWebSocket
int m_version
WebSocketState m_state
CWebSocketMessage * m_message
Constructor & Destructor Documentation
CWebSocketV8()
CWebSocketV8::CWebSocketV8 () inline
References CWebSocket::m_version.
Member Function Documentation
calculateKey()
std::string CWebSocketV8::calculateKey (const std::string & key) protected
References Base64::Encode(), KODI::UTILITY::CDigest::Update(), and WS_KEY_MAGICSTRING.
Referenced by CWebSocketV13::Handshake(), and Handshake().
close()
const CWebSocketFrame * CWebSocketV8::close (WebSocketCloseReason reason = WebSocketCloseNormal, const std::string & message = "") protected virtual
References data(), Endian_SwapBE16, CWebSocket::m_state, WebSocketConnectionClose, WebSocketStateClosed, WebSocketStateClosing, and WebSocketStateConnected.
Referenced by CWebSocketV13::Close(), and Close().
Close()
const CWebSocketFrame * CWebSocketV8::Close (WebSocketCloseReason reason = WebSocketCloseNormal, const std::string & message = "") override virtual
Implements CWebSocket.
References close(), CLog::Log(), LOGINFO, CWebSocket::m_state, WebSocketStateClosed, WebSocketStateHandshaking, and WebSocketStateNotConnected.
Fail()
void CWebSocketV8::Fail () override virtual
Implements CWebSocket.
References CWebSocket::m_state, and WebSocketStateClosed.
GetFrame() [1/2]
CWebSocketFrame * CWebSocketV8::GetFrame (const char * data, uint64_t length) override protected virtual
Implements CWebSocket.
References data().
GetFrame() [2/2]
CWebSocketFrame * CWebSocketV8::GetFrame (WebSocketFrameOpcode opcode, const char * data = NULL, uint32_t length = 0, bool final = true, bool masked = false, int32_t mask = 0, int8_t extension = 0) override protected virtual
Implements CWebSocket.
References data().
GetMessage()
CWebSocketMessage * CWebSocketV8::GetMessage () override protected virtual
Implements CWebSocket.
Handshake()
bool CWebSocketV8::Handshake (const char * data, size_t length, std::string & response) override virtual
Implements CWebSocket.
References HttpParser::addBytes(), CHttpResponse::AddHeader(), calculateKey(), CHttpResponse::Create(), data(), HttpParser::Done, HTTP::Get, HttpParser::getMethod(), HttpParser::getValue(), CLog::Log(), LOGINFO, CWebSocket::m_state, HTTP::SwitchingProtocols, value, HTTP::Version1_1, WebSocketStateConnected, WS_HEADER_ACCEPT, WS_HEADER_CONNECTION, WS_HEADER_KEY_LC, WS_HEADER_PROTOCOL, WS_HEADER_PROTOCOL_LC, WS_HEADER_UPGRADE, WS_HEADER_UPGRADE_VALUE, WS_HTTP_METHOD, WS_HTTP_TAG, and WS_PROTOCOL_JSONRPC.
Ping()
const CWebSocketFrame * CWebSocketV8::Ping (const char * data = NULL) const inline override virtual
Implements CWebSocket.
References data(), and WebSocketPing.
Pong()
const CWebSocketFrame * CWebSocketV8::Pong (const char * data, uint32_t length) const inline override virtual
Implements CWebSocket.
References data(), and WebSocketPong.
The documentation for this class was generated from the following files:
WebSocketV8.h
WebSocketV8.cpp