Kodi Documentation: KODI::RETRO::ISavestate Class Reference
KODI::RETRO::ISavestate Class Reference abstract
#include <ISavestate.h>
Public Member Functions
virtual ~ISavestate ()=default
virtual void Reset ()=0
Reset to the initial state.
virtual bool Serialize (const uint8_t *&data, size_t &size) const =0
Savestate properties
{
virtual SAVE_TYPE Type () const =0
The type of save action that created this savestate, either manual or automatic.
virtual uint8_t Slot () const =0
The slot this savestate was saved into, or 0 for no slot.
virtual std::string Label () const =0
The label shown in the GUI for this savestate.
virtual std::string Caption () const =0
A caption that describes the state of the game for this savestate.
virtual CDateTime Created () const =0
The timestamp of this savestate's creation.
Game properties
}
{
virtual std::string GameFileName () const =0
The name of the file belonging to this savestate's game.
Environment properties
}
{
virtual uint64_t TimestampFrames () const =0
The number of frames in the entire gameplay history.
virtual double TimestampWallClock () const =0
The duration of the entire gameplay history as seen by a wall clock.
Game client properties
}
{
virtual std::string GameClientID () const =0
The game client add-on ID that created this savestate.
virtual std::string GameClientVersion () const =0
The semantic version of the game client.
Video stream properties
}
{
virtual AVPixelFormat GetPixelFormat () const =0
The pixel format of the video stream.
virtual unsigned int GetNominalWidth () const =0
The nominal width of the video stream, a good guess for subsequent frames.
virtual unsigned int GetNominalHeight () const =0
The nominal height of the video stream, a good guess for subsequent frames.
virtual unsigned int GetMaxWidth () const =0
The maximum width of the video stream, in pixels.
virtual unsigned int GetMaxHeight () const =0
The maximum height of the video stream, in pixels.
virtual float GetPixelAspectRatio () const =0
The pixel aspect ratio of the video stream.
Video frame properties
}
{
virtual const uint8_t * GetVideoData () const =0
A pointer to the frame's video data (pixels)
virtual size_t GetVideoSize () const =0
The size of the frame's video data, in bytes.
virtual unsigned int GetVideoWidth () const =0
The width of the video frame, in pixels.
virtual unsigned int GetVideoHeight () const =0
The height of the video frame, in pixels.
virtual unsigned int GetRotationDegCCW () const =0
The rotation of the video frame, in degrees counter-clockwise.
Memory properties
}
{
virtual const uint8_t * GetMemoryData () const =0
A pointer to the internal memory (SRAM) of the frame.
virtual size_t GetMemorySize () const =0
The size of the memory region returned by GetMemoryData()
Builders for setting individual fields
}
{
virtual void SetType (SAVE_TYPE type)=0
virtual void SetSlot (uint8_t slot)=0
virtual void SetLabel (const std::string &label)=0
virtual void SetCaption (const std::string &caption)=0
virtual void SetCreated (const CDateTime &createdUTC)=0
virtual void SetGameFileName (const std::string &gameFileName)=0
virtual void SetTimestampFrames (uint64_t timestampFrames)=0
virtual void SetTimestampWallClock (double timestampWallClock)=0
virtual void SetGameClientID (const std::string &gameClient)=0
virtual void SetGameClientVersion (const std::string &gameClient)=0
virtual void SetPixelFormat (AVPixelFormat pixelFormat)=0
virtual void SetNominalWidth (unsigned int nominalWidth)=0
virtual void SetNominalHeight (unsigned int nominalHeight)=0
virtual void SetMaxWidth (unsigned int maxWidth)=0
virtual void SetMaxHeight (unsigned int maxHeight)=0
virtual void SetPixelAspectRatio (float pixelAspectRatio)=0
virtual uint8_t * GetVideoBuffer (size_t size)=0
virtual void SetVideoWidth (unsigned int videoWidth)=0
virtual void SetVideoHeight (unsigned int videoHeight)=0
virtual void SetRotationDegCCW (unsigned int rotationCCW)=0
virtual uint8_t * GetMemoryBuffer (size_t size)=0
virtual void Finalize ()=0
virtual bool Deserialize (std::vector< uint8_t > data)=0
}
Constructor & Destructor Documentation
~ISavestate()
virtual KODI::RETRO::ISavestate::~ISavestate () virtual default
Member Function Documentation
Caption()
virtual std::string KODI::RETRO::ISavestate::Caption () const pure virtual
A caption that describes the state of the game for this savestate.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
Created()
virtual CDateTime KODI::RETRO::ISavestate::Created () const pure virtual
The timestamp of this savestate's creation.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
Referenced by KODI::RETRO::CSavestateDatabase::AddSavestate().
Deserialize()
virtual bool KODI::RETRO::ISavestate::Deserialize (std::vector< uint8_t > data) pure virtual
}
Take ownership and initialize the flatbuffer with the given vector
Implemented in KODI::RETRO::CSavestateFlatBuffer.
Referenced by KODI::RETRO::CSavestateDatabase::GetSavestate().
Finalize()
virtual void KODI::RETRO::ISavestate::Finalize () pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GameClientID()
virtual std::string KODI::RETRO::ISavestate::GameClientID () const pure virtual
The game client add-on ID that created this savestate.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GameClientVersion()
virtual std::string KODI::RETRO::ISavestate::GameClientVersion () const pure virtual
The semantic version of the game client.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GameFileName()
virtual std::string KODI::RETRO::ISavestate::GameFileName () const pure virtual
The name of the file belonging to this savestate's game.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetMaxHeight()
virtual unsigned int KODI::RETRO::ISavestate::GetMaxHeight () const pure virtual
The maximum height of the video stream, in pixels.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetMaxWidth()
virtual unsigned int KODI::RETRO::ISavestate::GetMaxWidth () const pure virtual
The maximum width of the video stream, in pixels.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetMemoryBuffer()
virtual uint8_t * KODI::RETRO::ISavestate::GetMemoryBuffer (size_t size) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetMemoryData()
virtual const uint8_t * KODI::RETRO::ISavestate::GetMemoryData () const pure virtual
A pointer to the internal memory (SRAM) of the frame.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetMemorySize()
virtual size_t KODI::RETRO::ISavestate::GetMemorySize () const pure virtual
The size of the memory region returned by GetMemoryData()
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetNominalHeight()
virtual unsigned int KODI::RETRO::ISavestate::GetNominalHeight () const pure virtual
The nominal height of the video stream, a good guess for subsequent frames.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetNominalWidth()
virtual unsigned int KODI::RETRO::ISavestate::GetNominalWidth () const pure virtual
The nominal width of the video stream, a good guess for subsequent frames.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetPixelAspectRatio()
virtual float KODI::RETRO::ISavestate::GetPixelAspectRatio () const pure virtual
The pixel aspect ratio of the video stream.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetPixelFormat()
virtual AVPixelFormat KODI::RETRO::ISavestate::GetPixelFormat () const pure virtual
The pixel format of the video stream.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetRotationDegCCW()
virtual unsigned int KODI::RETRO::ISavestate::GetRotationDegCCW () const pure virtual
The rotation of the video frame, in degrees counter-clockwise.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetVideoBuffer()
virtual uint8_t * KODI::RETRO::ISavestate::GetVideoBuffer (size_t size) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetVideoData()
virtual const uint8_t * KODI::RETRO::ISavestate::GetVideoData () const pure virtual
A pointer to the frame's video data (pixels)
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetVideoHeight()
virtual unsigned int KODI::RETRO::ISavestate::GetVideoHeight () const pure virtual
The height of the video frame, in pixels.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetVideoSize()
virtual size_t KODI::RETRO::ISavestate::GetVideoSize () const pure virtual
The size of the frame's video data, in bytes.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
GetVideoWidth()
virtual unsigned int KODI::RETRO::ISavestate::GetVideoWidth () const pure virtual
The width of the video frame, in pixels.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
Label()
virtual std::string KODI::RETRO::ISavestate::Label () const pure virtual
The label shown in the GUI for this savestate.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
Reset()
virtual void KODI::RETRO::ISavestate::Reset () pure virtual
Reset to the initial state.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
Serialize()
virtual bool KODI::RETRO::ISavestate::Serialize (const uint8_t *& data, size_t & size) const pure virtual
Access the data representation of this savestate
Implemented in KODI::RETRO::CSavestateFlatBuffer.
Referenced by KODI::RETRO::CSavestateDatabase::AddSavestate().
SetCaption()
virtual void KODI::RETRO::ISavestate::SetCaption (const std::string & caption) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetCreated()
virtual void KODI::RETRO::ISavestate::SetCreated (const CDateTime & createdUTC) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetGameClientID()
virtual void KODI::RETRO::ISavestate::SetGameClientID (const std::string & gameClient) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetGameClientVersion()
virtual void KODI::RETRO::ISavestate::SetGameClientVersion (const std::string & gameClient) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetGameFileName()
virtual void KODI::RETRO::ISavestate::SetGameFileName (const std::string & gameFileName) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetLabel()
virtual void KODI::RETRO::ISavestate::SetLabel (const std::string & label) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetMaxHeight()
virtual void KODI::RETRO::ISavestate::SetMaxHeight (unsigned int maxHeight) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetMaxWidth()
virtual void KODI::RETRO::ISavestate::SetMaxWidth (unsigned int maxWidth) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetNominalHeight()
virtual void KODI::RETRO::ISavestate::SetNominalHeight (unsigned int nominalHeight) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetNominalWidth()
virtual void KODI::RETRO::ISavestate::SetNominalWidth (unsigned int nominalWidth) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetPixelAspectRatio()
virtual void KODI::RETRO::ISavestate::SetPixelAspectRatio (float pixelAspectRatio) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetPixelFormat()
virtual void KODI::RETRO::ISavestate::SetPixelFormat (AVPixelFormat pixelFormat) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetRotationDegCCW()
virtual void KODI::RETRO::ISavestate::SetRotationDegCCW (unsigned int rotationCCW) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetSlot()
virtual void KODI::RETRO::ISavestate::SetSlot (uint8_t slot) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetTimestampFrames()
virtual void KODI::RETRO::ISavestate::SetTimestampFrames (uint64_t timestampFrames) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetTimestampWallClock()
virtual void KODI::RETRO::ISavestate::SetTimestampWallClock (double timestampWallClock) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetType()
virtual void KODI::RETRO::ISavestate::SetType (SAVE_TYPE type) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetVideoHeight()
virtual void KODI::RETRO::ISavestate::SetVideoHeight (unsigned int videoHeight) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
SetVideoWidth()
virtual void KODI::RETRO::ISavestate::SetVideoWidth (unsigned int videoWidth) pure virtual
Implemented in KODI::RETRO::CSavestateFlatBuffer.
Slot()
virtual uint8_t KODI::RETRO::ISavestate::Slot () const pure virtual
The slot this savestate was saved into, or 0 for no slot.
This allows for keyboard access of saved games using the number keys 1-9.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
TimestampFrames()
virtual uint64_t KODI::RETRO::ISavestate::TimestampFrames () const pure virtual
The number of frames in the entire gameplay history.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
TimestampWallClock()
virtual double KODI::RETRO::ISavestate::TimestampWallClock () const pure virtual
The duration of the entire gameplay history as seen by a wall clock.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
Type()
virtual SAVE_TYPE KODI::RETRO::ISavestate::Type () const pure virtual
The type of save action that created this savestate, either manual or automatic.
Implemented in KODI::RETRO::CSavestateFlatBuffer.
The documentation for this class was generated from the following file:
ISavestate.h