Kodi Documentation: KODI::PLATFORM::WINDOWS Namespace Reference
KODI::PLATFORM::WINDOWS Namespace Reference
Functions
std::string FromW (const wchar_t *str, size_t length)
std::string FromW (const std::wstring &str)
std::wstring ToW (const char *str, size_t length)
std::wstring ToW (const std::string &str)
Function Documentation
FromW() [1/2]
std::string KODI::PLATFORM::WINDOWS::FromW (const std::wstring & str)
Convert UTF-16 to UTF-8 strings Windows specific method to avoid initialization issues and locking issues that are unique to Windows as API calls expect UTF-16 strings
Parameters
str[in] string to be converted
Returns
utf8 string, empty string on failure
References FromW().
FromW() [2/2]
std::string KODI::PLATFORM::WINDOWS::FromW (const wchar_t * str, size_t length)
Convert UTF-16 to UTF-8 strings Windows specific method to avoid initialization issues and locking issues that are unique to Windows as API calls expect UTF-16 strings
Parameters
str[in] string to be converted
length[in] length in characters of the string
Returns
utf8 string, empty string on failure
References FromW().
Referenced by CIRServerSuite::Connect(), DXVA::CContext::CreateContext(), DX::DeviceResources::CreateDeviceResources(), DSEnumCallback(), CAESinkDirectSound::EnumerateDevicesEx(), FromW(), FromW(), CWinSystemWin10::GetClipboardText(), CWinSystemWin32::GetClipboardText(), CWinSystemWin32::GetConnectedDisplays(), CWinSystemWin32::GetConnectedOutputs(), CAESinkDirectSound::GetDefaultDevice(), CAESinkFactoryWin::GetDefaultDeviceId(), XFILE::CWinLibraryDirectory::GetDirectory(), CWin32StorageProvider::GetDiskUsage(), CStorageProvider::GetDiskUsage(), CWin32StorageProvider::GetDrivesByType(), XFILE::CWinLibraryFile::GetFile(), XFILE::CWinLibraryDirectory::GetFolder(), CWin32StorageProvider::GetLocalDrives(), CWIN32Util::GetProfilePath(), CStorageProvider::GetRemovableDrives(), CAESinkFactoryWin::GetRendererDetailsWinRT(), XFILE::CWinLibraryDirectory::GetRootFolder(), CWIN32Util::GetVideoDriverInfo(), CWIN32Util::GetVideoDriverInfoDX(), DX::DeviceResources::HandleOutputChange(), init_emu_environ(), CAESinkDirectSound::Initialize(), CAESinkXAudio::InitializeInternal(), CRenderSystemDX::InitRenderSystem(), XFILE::CWinLibraryFile::IsInAccessList(), AEWASAPIDeviceWin32::IsUSBDevice(), KODI::PLATFORM::WINDOWS10::App::OnActivated(), CWinSystemWin32DX::OnMove(), XFILE::CWin32File::OpenForWrite(), XFILE::CWinLibraryFile::OpenIntenal(), XFILE::CWinLibraryFile::Read(), XFILE::CWinLibraryDirectory::Remove(), CWinSystemWin32::RestoreDesktopResolution(), TEST_F(), CWinSystemWin32::UpdateResolutions(), CWinEventsWin32::WndProc(), and XFILE::CWinLibraryFile::Write().
ToW() [1/2]
std::wstring KODI::PLATFORM::WINDOWS::ToW (const char * str, size_t length)
Convert UTF-8 to UTF-16 strings Windows specific method to avoid initialization issues and locking issues that are unique to Windows as API calls expect UTF-16 strings
Parameters
str[in] string to be converted
length[in] length in characters of the string
Returns
UTF-16 string, empty string on failure
Referenced by AEWASAPIDeviceWin10::Activate(), CWinSystemWin32::ChangeResolution(), XFILE::CWinLibraryDirectory::Create(), CWinSystemWin32::CreateNewWindow(), CWin32StorageProvider::Eject(), CAESinkXAudio::EnumerateDevicesEx(), CSysInfo::GetDiskSpace(), CWin32StorageProvider::GetDiskUsage(), CWinSystemWin32::GetDisplayDetails(), CWIN32Util::GetDriveStatus(), XFILE::CWinLibraryFile::GetFile(), XFILE::CWinLibraryDirectory::GetFolder(), XFILE::CWinLibraryFile::GetTokenFromList(), JSONRPC::CTCPServer::InitializeBlue(), CAESinkXAudio::InitializeInternal(), URIUtils::IsDVD(), URIUtils::IsOnDVD(), MessageBox(), XFILE::CWinLibraryFile::OpenIntenal(), Win32DllLoader::OverrideImports(), WSDiscovery::CWSDiscoveryWindows::ResolveHostName(), CWIN32Util::SetThreadName(), ToW(), WinMain(), win32_exception::write_minidump(), and win32_exception::write_stacktrace().
ToW() [2/2]
std::wstring KODI::PLATFORM::WINDOWS::ToW (const std::string & str)
Convert UTF-8 to UTF-16 strings Windows specific method to avoid initialization issues and locking issues that are unique to Windows as API calls expect UTF-16 strings
Parameters
str[in] string to be converted
Returns
UTF-16 string, empty string on failure
References ToW().