Kodi Documentation: CSystemBuiltins Class Reference
CSystemBuiltins Class Reference
Class providing system related built-in commands.
#include <SystemBuiltins.h>
Public Member Functions
CBuiltins::CommandMap GetOperations () const
Returns the map of operations.
Detailed Description
Class providing system related built-in commands.
Member Function Documentation
GetOperations()
CBuiltins::CommandMap CSystemBuiltins::GetOperations () const
Returns the map of operations.
References ActivateScreensaver(), Hibernate(), InhibitIdle(), InhibitScreenSaver(), Minimize(), Powerdown(), Quit(), Reboot(), ResetScreensaver(), RestartApp(), Shutdown(), and Suspend().
The documentation for this class was generated from the following files:
SystemBuiltins.h
SystemBuiltins.cpp