Kodi Documentation: CGUILargeTextureManager::CLargeTexture Class Reference
CGUILargeTextureManager::CLargeTexture Class Reference
Public Member Functions
CLargeTexture (const std::string &path)
virtual ~CLargeTexture ()
void AddRef ()
bool DecrRef (bool deleteImmediately)
bool DeleteIfRequired (bool deleteImmediately=false)
void SetTexture (std::unique_ptr< CTexture > texture)
const std::string & GetPath () const
const CTextureArray & GetTexture () const
Private Attributes
unsigned int m_refCount
std::string m_path
CTextureArray m_texture
unsigned int m_timeToDelete
Static Private Attributes
static const unsigned int TIME_TO_DELETE = 2000
Constructor & Destructor Documentation
CLargeTexture()
CGUILargeTextureManager::CLargeTexture::CLargeTexture (const std::string & path) explicit
References m_refCount, and m_timeToDelete.
~CLargeTexture()
CGUILargeTextureManager::CLargeTexture::~CLargeTexture () virtual
Member Function Documentation
AddRef()
void CGUILargeTextureManager::CLargeTexture::AddRef ()
Referenced by CGUILargeTextureManager::GetImage(), and CGUILargeTextureManager::QueueImage().
DecrRef()
bool CGUILargeTextureManager::CLargeTexture::DecrRef (bool deleteImmediately)
References CTimeUtils::GetFrameTime().
Referenced by CGUILargeTextureManager::ReleaseImage().
DeleteIfRequired()
bool CGUILargeTextureManager::CLargeTexture::DeleteIfRequired (bool deleteImmediately = false)
References CTimeUtils::GetFrameTime().
Referenced by CGUILargeTextureManager::CleanupUnusedImages().
GetPath()
const std::string & CGUILargeTextureManager::CLargeTexture::GetPath () const inline
References m_path.
Referenced by CGUILargeTextureManager::GetImage(), CGUILargeTextureManager::QueueImage(), and CGUILargeTextureManager::ReleaseImage().
GetTexture()
const CTextureArray & CGUILargeTextureManager::CLargeTexture::GetTexture () const inline
References m_texture.
Referenced by CGUILargeTextureManager::GetImage().
SetTexture()
void CGUILargeTextureManager::CLargeTexture::SetTexture (std::unique_ptr< CTexture > texture)
Referenced by CGUILargeTextureManager::OnJobComplete().
Member Data Documentation
m_path
std::string CGUILargeTextureManager::CLargeTexture::m_path private
Referenced by GetPath().
m_refCount
unsigned int CGUILargeTextureManager::CLargeTexture::m_refCount private
Referenced by CLargeTexture().
m_texture
CTextureArray CGUILargeTextureManager::CLargeTexture::m_texture private
Referenced by GetTexture().
m_timeToDelete
unsigned int CGUILargeTextureManager::CLargeTexture::m_timeToDelete private
Referenced by CLargeTexture().
TIME_TO_DELETE
const unsigned int CGUILargeTextureManager::CLargeTexture::TIME_TO_DELETE = 2000 static private
The documentation for this class was generated from the following files:
GUILargeTextureManager.h
GUILargeTextureManager.cpp