Kodi Documentation: KODI::JOYSTICK::IInputHandler Class Reference
KODI::JOYSTICK::IInputHandler Class Reference abstract
Input » Joystick
Interface for handling input events for game controllers.
#include <IInputHandler.h>
Public Member Functions
virtual ~IInputHandler ()=default
virtual std::string ControllerID (void) const =0
The add-on ID of the game controller associated with this input handler.
virtual bool HasFeature (const FeatureName &feature) const =0
Return true if the input handler accepts the given feature.
virtual bool AcceptsInput (const FeatureName &feature) const =0
Return true if the input handler is currently accepting input for the given feature.
virtual bool OnButtonPress (const FeatureName &feature, bool bPressed)=0
A digital button has been pressed or released.
virtual void OnButtonHold (const FeatureName &feature, unsigned int holdTimeMs)=0
A digital button has been pressed for more than one event frame.
virtual bool OnButtonMotion (const FeatureName &feature, float magnitude, unsigned int motionTimeMs)=0
An analog button (trigger or a pressure-sensitive button) has changed state.
virtual bool OnAnalogStickMotion (const FeatureName &feature, float x, float y, unsigned int motionTimeMs)=0
An analog stick has moved.
virtual bool OnAccelerometerMotion (const FeatureName &feature, float x, float y, float z)
An accelerometer's state has changed.
virtual bool OnWheelMotion (const FeatureName &feature, float position, unsigned int motionTimeMs)=0
A wheel has changed state.
virtual bool OnThrottleMotion (const FeatureName &feature, float position, unsigned int motionTimeMs)=0
A throttle has changed state.
virtual void OnInputFrame ()=0
Called at the end of the frame that provided input.
void SetInputReceiver (IInputReceiver *receiver)
void ResetInputReceiver (void)
IInputReceiver * InputReceiver (void)
Private Attributes
IInputReceiver * m_receiver = nullptr
Detailed Description
Interface for handling input events for game controllers.
Constructor & Destructor Documentation
~IInputHandler()
virtual KODI::JOYSTICK::IInputHandler::~IInputHandler () virtual default
Member Function Documentation
AcceptsInput()
virtual bool KODI::JOYSTICK::IInputHandler::AcceptsInput (const FeatureName & feature) const pure virtual
Return true if the input handler is currently accepting input for the given feature.
Parameters
feature A feature belonging to the controller specified by ControllerID()
Returns
True if the feature is currently accepting input, false otherwise
This does not prevent the input events from being called, but can return false to indicate that input wasn't handled for the specified feature.
Implemented in KODI::JOYSTICK::CJoystickMonitor, KODI::KEYMAP::CKeymapHandler, KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, and KODI::GAME::CPortInput.
Referenced by KODI::JOYSTICK::CJoystickFeature::AcceptsInput(), KODI::GAME::CInputSink::AcceptsInput(), KODI::GAME::CPortInput::AcceptsInput(), KODI::GAME::CPortInput::OnAccelerometerMotion(), KODI::GAME::CPortInput::OnAnalogStickMotion(), KODI::GAME::CPortInput::OnButtonMotion(), KODI::GAME::CPortInput::OnButtonPress(), KODI::GAME::CPortInput::OnThrottleMotion(), and KODI::GAME::CPortInput::OnWheelMotion().
ControllerID()
virtual std::string KODI::JOYSTICK::IInputHandler::ControllerID (void) const pure virtual
The add-on ID of the game controller associated with this input handler.
Returns
The ID of the add-on extending kodi.game.controller
Implemented in KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, KODI::GAME::CPortInput, KODI::JOYSTICK::CJoystickMonitor, and KODI::KEYMAP::CKeymapHandler.
Referenced by KODI::GAME::CPortInput::ControllerID(), KODI::JOYSTICK::CScalarFeature::CScalarFeature(), PERIPHERALS::CAddonInputHandling::Load(), KODI::JOYSTICK::CScalarFeature::OnAnalogMotion(), KODI::JOYSTICK::CScalarFeature::OnDigitalMotion(), KODI::JOYSTICK::CAxisFeature::ProcessMotions(), and KODI::JOYSTICK::CAnalogStick::ProcessMotions().
HasFeature()
virtual bool KODI::JOYSTICK::IInputHandler::HasFeature (const FeatureName & feature) const pure virtual
Return true if the input handler accepts the given feature.
Parameters
feature A feature belonging to the controller specified by ControllerID()
Returns
True if the feature is used for input, false otherwise
Implemented in KODI::JOYSTICK::CJoystickMonitor, KODI::KEYMAP::CKeymapHandler, KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, and KODI::GAME::CPortInput.
InputReceiver()
IInputReceiver * KODI::JOYSTICK::IInputHandler::InputReceiver (void) inline
References m_receiver.
Referenced by KODI::GAME::CGameClientJoystick::SetRumble().
OnAccelerometerMotion()
virtual bool KODI::JOYSTICK::IInputHandler::OnAccelerometerMotion (const FeatureName & feature, float x, float y, float z) inline virtual
An accelerometer's state has changed.
Parameters
feature The accelerometer being accelerated
x The x coordinate in the closed interval [-1, 1]
y The y coordinate in the closed interval [-1, 1]
z The z coordinate in the closed interval [-1, 1]
Returns
True if the event was handled otherwise false
Reimplemented in KODI::JOYSTICK::CJoystickMonitor, KODI::KEYMAP::CKeymapHandler, KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, and KODI::GAME::CPortInput.
Referenced by KODI::GAME::CPortInput::OnAccelerometerMotion(), and KODI::JOYSTICK::CAccelerometer::ProcessMotions().
OnAnalogStickMotion()
virtual bool KODI::JOYSTICK::IInputHandler::OnAnalogStickMotion (const FeatureName & feature, float x, float y, unsigned int motionTimeMs) pure virtual
An analog stick has moved.
Parameters
feature The analog stick being moved
x The x coordinate in the closed interval [-1, 1]
y The y coordinate in the closed interval [-1, 1]
motionTimeMs The time elapsed since this analog stick was centered, or 0 if the analog stick is centered
Returns
True if the event was handled otherwise false
Implemented in KODI::JOYSTICK::CJoystickMonitor, KODI::KEYMAP::CKeymapHandler, KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, and KODI::GAME::CPortInput.
Referenced by KODI::GAME::CPortInput::OnAnalogStickMotion(), and KODI::JOYSTICK::CAnalogStick::ProcessMotions().
OnButtonHold()
virtual void KODI::JOYSTICK::IInputHandler::OnButtonHold (const FeatureName & feature, unsigned int holdTimeMs) pure virtual
A digital button has been pressed for more than one event frame.
Parameters
feature The feature being held
holdTimeMs The time elapsed since the initial press (ms)
If OnButtonPress() returns true for the initial press, then this callback is invoked on subsequent frames until the button is released.
Implemented in KODI::JOYSTICK::CJoystickMonitor, KODI::KEYMAP::CKeymapHandler, KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, and KODI::GAME::CPortInput.
Referenced by KODI::GAME::CPortInput::OnButtonHold(), and KODI::JOYSTICK::CScalarFeature::ProcessDigitalMotion().
OnButtonMotion()
virtual bool KODI::JOYSTICK::IInputHandler::OnButtonMotion (const FeatureName & feature, float magnitude, unsigned int motionTimeMs) pure virtual
An analog button (trigger or a pressure-sensitive button) has changed state.
Parameters
feature The feature changing state
magnitude The button pressure or trigger travel distance in the closed interval [0, 1]
motionTimeMs The time elapsed since the magnitude was 0
Returns
True if the event was handled otherwise false
Implemented in KODI::JOYSTICK::CJoystickMonitor, KODI::KEYMAP::CKeymapHandler, KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, and KODI::GAME::CPortInput.
Referenced by KODI::GAME::CPortInput::OnButtonMotion(), and KODI::JOYSTICK::CScalarFeature::ProcessAnalogMotion().
OnButtonPress()
virtual bool KODI::JOYSTICK::IInputHandler::OnButtonPress (const FeatureName & feature, bool bPressed) pure virtual
A digital button has been pressed or released.
Parameters
feature The feature being pressed
bPressed True if pressed, false if released
Returns
True if the event was handled otherwise false
Implemented in KODI::JOYSTICK::CJoystickMonitor, KODI::KEYMAP::CKeymapHandler, KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, and KODI::GAME::CPortInput.
Referenced by KODI::GAME::CPortInput::OnButtonPress(), and KODI::JOYSTICK::CScalarFeature::OnDigitalMotion().
OnInputFrame()
virtual void KODI::JOYSTICK::IInputHandler::OnInputFrame () pure virtual
Called at the end of the frame that provided input.
Implemented in KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, KODI::GAME::CPortInput, KODI::JOYSTICK::CJoystickMonitor, and KODI::KEYMAP::CKeymapHandler.
Referenced by KODI::JOYSTICK::CInputHandling::OnInputFrame().
OnThrottleMotion()
virtual bool KODI::JOYSTICK::IInputHandler::OnThrottleMotion (const FeatureName & feature, float position, unsigned int motionTimeMs) pure virtual
A throttle has changed state.
Up is positive position, down is negative position.
Parameters
feature The wheel changing state
position The position in the closed interval [-1, 1]
motionTimeMs The time elapsed since the position was 0
Returns
True if the event was handled otherwise false
Implemented in KODI::JOYSTICK::CJoystickMonitor, KODI::KEYMAP::CKeymapHandler, KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, and KODI::GAME::CPortInput.
Referenced by KODI::GAME::CPortInput::OnThrottleMotion(), and KODI::JOYSTICK::CAxisFeature::ProcessMotions().
OnWheelMotion()
virtual bool KODI::JOYSTICK::IInputHandler::OnWheelMotion (const FeatureName & feature, float position, unsigned int motionTimeMs) pure virtual
A wheel has changed state.
Left is negative position, right is positive position
Parameters
feature The wheel changing state
position The position in the closed interval [-1, 1]
motionTimeMs The time elapsed since the position was 0
Returns
True if the event was handled otherwise false
Implemented in KODI::JOYSTICK::CJoystickMonitor, KODI::KEYMAP::CKeymapHandler, KODI::GAME::CGameClientJoystick, KODI::GAME::CAgentJoystick, KODI::GAME::CInputSink, and KODI::GAME::CPortInput.
Referenced by KODI::GAME::CPortInput::OnWheelMotion(), and KODI::JOYSTICK::CAxisFeature::ProcessMotions().
ResetInputReceiver()
void KODI::JOYSTICK::IInputHandler::ResetInputReceiver (void) inline
References m_receiver.
Referenced by PERIPHERALS::CPeripheral::UnregisterInputHandler().
SetInputReceiver()
void KODI::JOYSTICK::IInputHandler::SetInputReceiver (IInputReceiver * receiver) inline
References m_receiver.
Referenced by PERIPHERALS::CAddonInputHandling::Load().
Member Data Documentation
m_receiver
IInputReceiver* KODI::JOYSTICK::IInputHandler::m_receiver = nullptr private
Referenced by InputReceiver(), ResetInputReceiver(), and SetInputReceiver().
The documentation for this class was generated from the following file:
input/joysticks/interfaces/IInputHandler.h