Kodi Documentation: KODI::JOYSTICK::IInputProvider Class Reference
KODI::JOYSTICK::IInputProvider Class Reference abstract
Input » Joystick
Interface for classes that can provide input.
#include <IInputProvider.h>
Public Member Functions
virtual ~IInputProvider ()=default
virtual void RegisterInputHandler (IInputHandler *handler, bool bPromiscuous)=0
Register a handler for the provided input.
virtual void UnregisterInputHandler (IInputHandler *handler)=0
Unregister a handler.
Detailed Description
Interface for classes that can provide input.
Constructor & Destructor Documentation
~IInputProvider()
virtual KODI::JOYSTICK::IInputProvider::~IInputProvider () virtual default
Member Function Documentation
RegisterInputHandler()
virtual void KODI::JOYSTICK::IInputProvider::RegisterInputHandler (IInputHandler * handler, bool bPromiscuous) pure virtual
Register a handler for the provided input.
Parameters
handler The handler to receive input provided by this class
bPromiscuous If true, receives all input (including handled input) in the background
Implemented in PERIPHERALS::CPeripheral.
Referenced by KODI::GAME::CAgentJoystick::Initialize(), KODI::KEYMAP::CKeymapHandling::LoadKeymaps(), and KODI::GAME::CPortInput::RegisterInput().
UnregisterInputHandler()
virtual void KODI::JOYSTICK::IInputProvider::UnregisterInputHandler (IInputHandler * handler) pure virtual
Unregister a handler.
Parameters
handler The handler that was receiving input
Implemented in PERIPHERALS::CPeripheral.
Referenced by KODI::GAME::CAgentJoystick::Deinitialize(), KODI::KEYMAP::CKeymapHandling::UnloadKeymaps(), and KODI::GAME::CPortInput::UnregisterInput().
The documentation for this class was generated from the following file:
IInputProvider.h