Kodi Documentation: CUDFBlockInput Class Reference
CUDFBlockInput Class Reference
#include <UDFBlockInput.h>
Classes
struct UDF_BI
Public Member Functions
CUDFBlockInput ()=default
~CUDFBlockInput ()=default
udfread_block_input * GetBlockInput (const std::string &file)
Static Private Member Functions
static int Close (udfread_block_input *bi)
static uint32_t Size (udfread_block_input *bi)
static int Read (udfread_block_input *bi, uint32_t lba, void *buf, uint32_t nblocks, int flags)
Private Attributes
std::unique_ptr< UDF_BI > m_bi {nullptr}
Constructor & Destructor Documentation
CUDFBlockInput()
CUDFBlockInput::CUDFBlockInput () default
~CUDFBlockInput()
CUDFBlockInput::~CUDFBlockInput () default
Member Function Documentation
Close()
int CUDFBlockInput::Close (udfread_block_input * bi) static private
References CUDFBlockInput::UDF_BI::fp, and m_bi.
Referenced by GetBlockInput().
GetBlockInput()
udfread_block_input * CUDFBlockInput::GetBlockInput (const std::string & file)
References Close(), m_bi, Read(), and Size().
Referenced by XFILE::CUDFDirectory::GetDirectory().
Read()
int CUDFBlockInput::Read (udfread_block_input * bi, uint32_t lba, void * buf, uint32_t nblocks, int flags) static private
References int64_t(), and m_bi.
Referenced by GetBlockInput().
Size()
uint32_t CUDFBlockInput::Size (udfread_block_input * bi) static private
References m_bi.
Referenced by GetBlockInput().
Member Data Documentation
m_bi
std::unique_ptr<UDF_BI> CUDFBlockInput::m_bi {nullptr} private
Referenced by Close(), GetBlockInput(), Read(), and Size().
The documentation for this class was generated from the following files:
UDFBlockInput.h
UDFBlockInput.cpp