Kodi Documentation: KODI::GAME::CGUIDialogSelectGameClient Class Reference
KODI::GAME::CGUIDialogSelectGameClient Class Reference
Games
#include <GUIDialogSelectGameClient.h>
Static Public Member Functions
static std::string ShowAndGetGameClient (const std::string &gamePath, const GameClientVector &candidates, const GameClientVector &installable)
Show a series of dialogs that results in a game client being selected.
Static Private Member Functions
static CGUIDialogSelect * GetDialog (const std::string &title)
Get an initialized select dialog.
static void LogGameClients (const GameClientVector &candidates, const GameClientVector &installable)
Log the candidates and installable game clients.
Member Function Documentation
GetDialog()
CGUIDialogSelect * CGUIDialogSelectGameClient::GetDialog (const std::string & title) static private
Get an initialized select dialog.
Parameters
title The title of the select dialog
Returns
A select dialog with its properties initialized, or nullptr if the dialog isn't found
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetUseDetails(), and WINDOW_DIALOG_SELECT.
Referenced by ShowAndGetGameClient().
LogGameClients()
void CGUIDialogSelectGameClient::LogGameClients (const GameClientVector & candidates, const GameClientVector & installable) static private
Log the candidates and installable game clients.
Other than logging, this has no side effects.
References CLog::Log(), and LOGDEBUG.
Referenced by ShowAndGetGameClient().
ShowAndGetGameClient()
std::string CGUIDialogSelectGameClient::ShowAndGetGameClient (const std::string & gamePath, const GameClientVector & candidates, const GameClientVector & installable) static
Show a series of dialogs that results in a game client being selected.
Parameters
gamePath The path of the file being played
candidates A list of installed candidates that the user can select from
installable A list of installable candidates that the user can select from
Returns
The ID of the selected game client, or empty if no game client was selected
References CFileItemList::Add(), CFileItemList::Append(), XFILE::CAddonsDirectory::FileItemFromAddon(), g_localizeStrings, CLocalizeStrings::Get(), GetDialog(), URIUtils::GetExtension(), CFileItem::GetPath(), CGUIDialogSelect::GetSelectedItem(), CGUIDialogBoxBase::IsConfirmed(), CLog::Log(), LOGDEBUG, LogGameClients(), CGUIDialog::Open(), CGUIDialogSelect::SetItems(), CFileItemList::Size(), CFileItemList::Sort(), SortByLabel, and SortOrderAscending.
Referenced by KODI::GAME::CGameUtils::FillInGameClient().
The documentation for this class was generated from the following files:
GUIDialogSelectGameClient.h
GUIDialogSelectGameClient.cpp