Kodi Documentation: XFILE::CMusicDatabaseFile Class Reference
XFILE::CMusicDatabaseFile Class Reference
#include <MusicDatabaseFile.h>
Public Member Functions
CMusicDatabaseFile (void)
~CMusicDatabaseFile (void) override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
void Close () override
int64_t GetPosition () override
int64_t GetLength () override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool OpenForWrite (const CURL &url, bool bOverWrite=false)
virtual bool ReOpen (const CURL &url)
virtual int Stat (struct __stat64 *buffer)
virtual ssize_t Write (const void *bufPtr, size_t bufSize)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool Delete (const CURL &url)
virtual bool Rename (const CURL &url, const CURL &urlnew)
virtual bool SetHidden (const CURL &url, bool hidden)
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Static Public Member Functions
static std::string TranslateUrl (const CURL &url)
Protected Attributes
CFile m_file
Constructor & Destructor Documentation
CMusicDatabaseFile()
CMusicDatabaseFile::CMusicDatabaseFile (void) default
~CMusicDatabaseFile()
CMusicDatabaseFile::~CMusicDatabaseFile (void) override
References Close().
Member Function Documentation
Close()
void CMusicDatabaseFile::Close () override virtual
Implements XFILE::IFile.
References XFILE::CFile::Close(), and m_file.
Referenced by ~CMusicDatabaseFile().
Exists()
bool CMusicDatabaseFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References TranslateUrl().
GetLength()
int64_t CMusicDatabaseFile::GetLength () override virtual
Implements XFILE::IFile.
References XFILE::CFile::GetLength(), and m_file.
GetPosition()
int64_t CMusicDatabaseFile::GetPosition () override virtual
Implements XFILE::IFile.
References XFILE::CFile::GetPosition(), and m_file.
Open()
bool CMusicDatabaseFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References m_file, XFILE::CFile::Open(), and TranslateUrl().
Read()
ssize_t CMusicDatabaseFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References m_file, and XFILE::CFile::Read().
Seek()
int64_t CMusicDatabaseFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
References m_file, and XFILE::CFile::Seek().
Stat()
int CMusicDatabaseFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References m_file, XFILE::CFile::Stat(), and TranslateUrl().
TranslateUrl()
std::string CMusicDatabaseFile::TranslateUrl (const CURL & url) static
References CURL::Get(), URIUtils::GetExtension(), URIUtils::GetFileName(), CMusicDatabase::GetSong(), URIUtils::HasExtension(), CMusicDatabase::Open(), URIUtils::RemoveExtension(), and CSong::strFileName.
Referenced by Exists(), Open(), CExternalPlayer::Process(), and Stat().
Member Data Documentation
m_file
CFile XFILE::CMusicDatabaseFile::m_file protected
Referenced by Close(), GetLength(), GetPosition(), Open(), Read(), Seek(), and Stat().
The documentation for this class was generated from the following files:
MusicDatabaseFile.h
MusicDatabaseFile.cpp