Kodi Documentation: CRssReader Class Reference
CRssReader Class Reference
#include <RssReader.h>
Public Member Functions
CRssReader ()
~CRssReader () override
void Create (IRssObserver *aObserver, const std::vector< std::string > &aUrl, const std::vector< int > &times, int spacesBetweenFeeds, bool rtl)
bool Parse (const std::string &data, int iFeed)
void getFeed (vecText &text)
void AddTag (const std::string &addTag)
void AddToQueue (int iAdd)
void UpdateObserver ()
void SetObserver (IRssObserver *observer)
void CheckForUpdates ()
void requestRefresh ()
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Public Attributes
float m_savedScrollPixelPos
Private Member Functions
void Process () override
bool Parse (int iFeed)
void GetNewsItems (tinyxml2::XMLNode *channelXmlNode, int iFeed)
void AddString (std::wstring aString, int aColour, int iFeed)
void UpdateFeed ()
void OnExit () override
int GetQueueSize ()
Private Attributes
IRssObserver * m_pObserver
std::vector< std::wstring > m_strFeed
std::vector< std::wstring > m_strColors
std::vector< KODI::TIME::SystemTime * > m_vecTimeStamps
std::vector< int > m_vecUpdateTimes
int m_spacesBetweenFeeds
CXBMCTinyXML2 m_xml
std::list< std::string > m_tagSet
std::vector< std::string > m_vecUrls
std::vector< int > m_vecQueue
bool m_bIsRunning
bool m_rtlText
bool m_requestRefresh
CCriticalSection m_critical
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CRssReader()
CRssReader::CRssReader ()
References m_bIsRunning, m_pObserver, m_requestRefresh, m_rtlText, m_savedScrollPixelPos, and m_spacesBetweenFeeds.
~CRssReader()
CRssReader::~CRssReader () override
References m_pObserver, m_vecTimeStamps, IRssObserver::OnFeedRelease(), and CThread::StopThread().
Member Function Documentation
AddString()
void CRssReader::AddString (std::wstring aString, int aColour, int iFeed) private
References m_rtlText, m_strColors, and m_strFeed.
Referenced by GetNewsItems(), and Parse().
AddTag()
void CRssReader::AddTag (const std::string & addTag)
References m_tagSet.
Referenced by GetNewsItems(), and CGUIRSSControl::Process().
AddToQueue()
void CRssReader::AddToQueue (int iAdd)
References CThread::Create(), m_bIsRunning, m_critical, m_vecQueue, m_vecUrls, and CThread::StopThread().
Referenced by CheckForUpdates(), and Create().
CheckForUpdates()
void CRssReader::CheckForUpdates ()
References AddToQueue(), KODI::TIME::GetLocalTime(), CLog::Log(), LOGDEBUG, m_requestRefresh, m_vecTimeStamps, and m_vecUpdateTimes.
Referenced by CGUIRSSControl::Render().
Create()
void CRssReader::Create (IRssObserver * aObserver, const std::vector< std::string > & aUrl, const std::vector< int > & times, int spacesBetweenFeeds, bool rtl)
References AddToQueue(), KODI::TIME::GetLocalTime(), m_critical, m_pObserver, m_requestRefresh, m_rtlText, m_spacesBetweenFeeds, m_strColors, m_strFeed, m_vecTimeStamps, m_vecUpdateTimes, and m_vecUrls.
Referenced by CGUIRSSControl::Process(), TEST(), and TEST().
getFeed()
void CRssReader::getFeed (vecText & text)
References m_spacesBetweenFeeds, m_strColors, m_strFeed, and text.
Referenced by UpdateObserver().
GetNewsItems()
void CRssReader::GetNewsItems (tinyxml2::XMLNode * channelXmlNode, int iFeed) private
References AddString(), AddTag(), HTML::CHTMLUtil::ConvertHTMLToW(), g_charsetConverter, m_rtlText, m_tagSet, RSS_COLOR_BODY, RSS_COLOR_HEADLINE, and text.
Referenced by Parse().
GetQueueSize()
int CRssReader::GetQueueSize () private
References m_critical, and m_vecQueue.
Referenced by Process().
OnExit()
void CRssReader::OnExit () override private virtual
Reimplemented from CThread.
References m_bIsRunning.
Parse() [1/2]
bool CRssReader::Parse (const std::string & data, int iFeed)
References data(), m_xml, Parse(), and CXBMCTinyXML2::Parse().
Referenced by Parse(), Process(), TEST(), and TEST().
Parse() [2/2]
bool CRssReader::Parse (int iFeed) private
References AddString(), g_charsetConverter, GetNewsItems(), m_rtlText, m_strColors, m_strFeed, m_xml, and RSS_COLOR_CHANNEL.
Process()
void CRssReader::Process (void) override private virtual
Reimplemented from CThread.
References XFILE::CCurlFile::Cancel(), g_localizeStrings, XFILE::CCurlFile::Get(), CLocalizeStrings::Get(), CServiceBroker::GetNetwork(), GetQueueSize(), CServiceBroker::GetSettingsComponent(), CNetworkBase::IsAvailable(), CURL::IsProtocol(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, CThread::m_bStop, m_critical, m_pObserver, m_strColors, m_strFeed, m_vecQueue, m_vecUrls, Parse(), XFILE::CCurlFile::SetTimeout(), XFILE::CCurlFile::SetUserAgent(), CThread::Sleep(), and UpdateObserver().
requestRefresh()
void CRssReader::requestRefresh ()
References m_requestRefresh.
SetObserver()
void CRssReader::SetObserver (IRssObserver * observer)
References m_pObserver.
Referenced by CRssManager::GetReader(), and CGUIRSSControl::~CGUIRSSControl().
UpdateFeed()
void CRssReader::UpdateFeed () private
UpdateObserver()
void CRssReader::UpdateObserver ()
References getFeed(), CServiceBroker::GetWinSystem(), m_pObserver, and IRssObserver::OnFeedUpdate().
Referenced by CRssManager::GetReader(), and Process().
Member Data Documentation
m_bIsRunning
bool CRssReader::m_bIsRunning private
Referenced by AddToQueue(), CRssReader(), and OnExit().
m_critical
CCriticalSection CRssReader::m_critical private
Referenced by AddToQueue(), Create(), GetQueueSize(), and Process().
m_pObserver
IRssObserver* CRssReader::m_pObserver private
Referenced by Create(), CRssReader(), Process(), SetObserver(), UpdateObserver(), and ~CRssReader().
m_requestRefresh
bool CRssReader::m_requestRefresh private
Referenced by CheckForUpdates(), Create(), CRssReader(), and requestRefresh().
m_rtlText
bool CRssReader::m_rtlText private
Referenced by AddString(), Create(), CRssReader(), GetNewsItems(), and Parse().
m_savedScrollPixelPos
float CRssReader::m_savedScrollPixelPos
Referenced by CRssReader(), CGUIRSSControl::Process(), and CGUIRSSControl::Render().
m_spacesBetweenFeeds
int CRssReader::m_spacesBetweenFeeds private
Referenced by Create(), CRssReader(), and getFeed().
m_strColors
std::vector<std::wstring> CRssReader::m_strColors private
Referenced by AddString(), Create(), getFeed(), Parse(), and Process().
m_strFeed
std::vector<std::wstring> CRssReader::m_strFeed private
Referenced by AddString(), Create(), getFeed(), Parse(), and Process().
m_tagSet
std::list<std::string> CRssReader::m_tagSet private
Referenced by AddTag(), and GetNewsItems().
m_vecQueue
std::vector<int> CRssReader::m_vecQueue private
Referenced by AddToQueue(), GetQueueSize(), and Process().
m_vecTimeStamps
std::vector<KODI::TIME::SystemTime*> CRssReader::m_vecTimeStamps private
Referenced by CheckForUpdates(), Create(), and ~CRssReader().
m_vecUpdateTimes
std::vector<int> CRssReader::m_vecUpdateTimes private
Referenced by CheckForUpdates(), and Create().
m_vecUrls
std::vector<std::string> CRssReader::m_vecUrls private
Referenced by AddToQueue(), Create(), and Process().
m_xml
CXBMCTinyXML2 CRssReader::m_xml private
Referenced by Parse(), and Parse().
The documentation for this class was generated from the following files:
RssReader.h
RssReader.cpp