Kodi Documentation: PERIPHERALS::CPeripheralBusAndroid Class Reference
PERIPHERALS::CPeripheralBusAndroid Class Reference
#include <PeripheralBusAndroid.h>
Public Member Functions
CPeripheralBusAndroid (CPeripherals &manager)
~CPeripheralBusAndroid () override
bool InitializeProperties (CPeripheral &peripheral) override
Initialize the properties of a peripheral with a known location.
bool InitializeButtonMap (const CPeripheral &peripheral, KODI::JOYSTICK::IButtonMap &buttonMap) const override
Initialize a joystick buttonmap, if possible.
void Initialise (void) override
Initialise this bus and start a polling thread if this bus needs polling.
void ProcessEvents () override
Poll for events.
void OnInputDeviceAdded (int deviceId) override
void OnInputDeviceChanged (int deviceId) override
void OnInputDeviceRemoved (int deviceId) override
bool OnInputDeviceEvent (const AInputEvent *event) override
Public Member Functions inherited from PERIPHERALS::CPeripheralBus
CPeripheralBus (const std::string &threadname, CPeripherals &manager, PeripheralBusType type)
~CPeripheralBus (void) override
PeripheralBusType Type (void) const
bool NeedsPolling (void) const
virtual PeripheralPtr GetPeripheral (const std::string &strLocation) const
Get the instance of the peripheral at the given location.
virtual bool HasPeripheral (const std::string &strLocation) const
Check whether a peripheral is present at the given location.
virtual bool SupportsFeature (PeripheralFeature feature) const
Check if the bus supports the given feature.
virtual unsigned int GetPeripheralsWithFeature (PeripheralVector &results, const PeripheralFeature feature) const
Get all peripheral instances that have the given feature.
virtual unsigned int GetNumberOfPeripherals () const
virtual unsigned int GetNumberOfPeripheralsWithId (const int iVendorId, const int iProductId) const
virtual void GetFeatures (std::vector< PeripheralFeature > &features) const
Get all features that are supported by devices on this bus.
virtual bool HasFeature (const PeripheralFeature feature) const
Check whether there is at least one device present with the given feature.
virtual void OnDeviceAdded (const std::string &strLocation)
Callback method for when a device has been added. Will perform a device scan.
virtual void OnDeviceChanged (const std::string &strLocation)
Callback method for when a device has been changed. Will perform a device scan.
virtual void OnDeviceRemoved (const std::string &strLocation)
Callback method for when a device has been removed. Will perform a device scan.
virtual void Clear (void)
Stop the polling thread and clear all known devices on this bus.
virtual void TriggerDeviceScan (void)
Scan for devices.
virtual void GetDirectory (const std::string &strPath, CFileItemList &items) const
Get all fileitems for a path.
virtual PeripheralPtr GetByPath (const std::string &strPath) const
Get the instance of a peripheral given it's path.
virtual void Register (const PeripheralPtr &peripheral)
Register a new peripheral on this bus.
virtual bool FindComPort (std::string &strLocation)
virtual void EnableButtonMapping ()
Initialize button mapping.
virtual void PowerOff (const std::string &strLocation)
Power off the specified device.
Public Member Functions inherited from IInputDeviceCallbacks
virtual ~IInputDeviceCallbacks ()=default
Public Member Functions inherited from IInputDeviceEventHandler
virtual ~IInputDeviceEventHandler ()=default
Protected Member Functions
bool PerformDeviceScan (PeripheralScanResults &results) override
Scan for devices on this bus and add them to the results list. This will have to be implemented for each bus.
Protected Member Functions inherited from PERIPHERALS::CPeripheralBus
void Process (void) override
virtual bool ScanForDevices (void)
virtual void UnregisterRemovedDevices (const PeripheralScanResults &results)
virtual void RegisterNewDevices (const PeripheralScanResults &results)
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Protected Member Functions inherited from IInputDeviceCallbacks
IInputDeviceCallbacks ()=default
Protected Member Functions inherited from IInputDeviceEventHandler
IInputDeviceEventHandler ()=default
Static Private Member Functions
static PeripheralScanResults GetInputDevices ()
static std::string GetDeviceLocation (int deviceId)
static bool GetDeviceId (const std::string &deviceLocation, int &deviceId)
static bool ConvertToPeripheralScanResult (const CJNIViewInputDevice &inputDevice, PeripheralScanResult &peripheralScanResult)
static void LogInputDevice (const CJNIViewInputDevice &device)
static std::vector< std::pair< int, const char * > > GetInputSources ()
Private Attributes
std::map< int, CAndroidJoystickState > m_joystickStates
PeripheralScanResults m_scanResults
CCriticalSection m_critSectionStates
CCriticalSection m_critSectionResults
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Attributes inherited from PERIPHERALS::CPeripheralBus
PeripheralVector m_peripherals
std::chrono::milliseconds m_iRescanTime
bool m_bNeedsPolling
CPeripherals & m_manager
const PeripheralBusType m_type
CCriticalSection m_critSection
CEvent m_triggerEvent
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CPeripheralBusAndroid()
CPeripheralBusAndroid::CPeripheralBusAndroid (CPeripherals & manager) explicit
References CXBMCApp::Get(), GetInputDevices(), PERIPHERALS::CPeripheralBus::m_bNeedsPolling, m_scanResults, CXBMCApp::RegisterInputDeviceCallbacks(), and CXBMCApp::RegisterInputDeviceEventHandler().
~CPeripheralBusAndroid()
CPeripheralBusAndroid::~CPeripheralBusAndroid () override
References CXBMCApp::Get(), CXBMCApp::UnregisterInputDeviceCallbacks(), and CXBMCApp::UnregisterInputDeviceEventHandler().
Member Function Documentation
ConvertToPeripheralScanResult()
bool CPeripheralBusAndroid::ConvertToPeripheralScanResult (const CJNIViewInputDevice & inputDevice, PeripheralScanResult & peripheralScanResult) static private
References GetDeviceLocation(), CLog::Log(), LOGDEBUG, PERIPHERALS::PeripheralScanResult::m_busType, PERIPHERALS::PeripheralScanResult::m_iProductId, PERIPHERALS::PeripheralScanResult::m_iSequence, PERIPHERALS::PeripheralScanResult::m_iVendorId, PERIPHERALS::PeripheralScanResult::m_mappedBusType, PERIPHERALS::PeripheralScanResult::m_mappedType, PERIPHERALS::PeripheralScanResult::m_strDeviceName, PERIPHERALS::PeripheralScanResult::m_strLocation, PERIPHERALS::PeripheralScanResult::m_type, and PERIPHERALS::PERIPHERAL_JOYSTICK.
Referenced by GetInputDevices(), OnInputDeviceAdded(), and OnInputDeviceChanged().
GetDeviceId()
bool CPeripheralBusAndroid::GetDeviceId (const std::string & deviceLocation, int & deviceId) static private
References DeviceLocationPrefix.
Referenced by InitializeButtonMap(), and InitializeProperties().
GetDeviceLocation()
std::string CPeripheralBusAndroid::GetDeviceLocation (int deviceId) static private
References DeviceLocationPrefix.
Referenced by ConvertToPeripheralScanResult(), OnInputDeviceAdded(), OnInputDeviceChanged(), OnInputDeviceRemoved(), and ProcessEvents().
GetInputDevices()
PeripheralScanResults CPeripheralBusAndroid::GetInputDevices () static private
References ConvertToPeripheralScanResult(), CXBMCApp::GetInputDevice(), CXBMCApp::GetInputDeviceIds(), CLog::Log(), LOGDEBUG, LOGINFO, LogInputDevice(), LOGWARNING, and PERIPHERALS::PeripheralScanResults::m_results.
Referenced by CPeripheralBusAndroid().
GetInputSources()
std::vector< std::pair< int, const char * > > CPeripheralBusAndroid::GetInputSources () static private
Referenced by LogInputDevice().
Initialise()
void CPeripheralBusAndroid::Initialise (void) override virtual
Initialise this bus and start a polling thread if this bus needs polling.
Reimplemented from PERIPHERALS::CPeripheralBus.
References PERIPHERALS::CPeripheralBus::Initialise(), and PERIPHERALS::CPeripheralBus::TriggerDeviceScan().
InitializeButtonMap()
bool CPeripheralBusAndroid::InitializeButtonMap (const CPeripheral & peripheral, KODI::JOYSTICK::IButtonMap & buttonMap) const override virtual
Initialize a joystick buttonmap, if possible.
Reimplemented from PERIPHERALS::CPeripheralBus.
References PERIPHERALS::CAndroidJoystickState::GetAxisCount(), PERIPHERALS::CAndroidJoystickState::GetButtonCount(), GetDeviceId(), PERIPHERALS::CAndroidJoystickState::InitializeButtonMap(), PERIPHERALS::CPeripheral::Location(), CLog::Log(), LOGDEBUG, LOGWARNING, m_critSectionStates, and m_joystickStates.
InitializeProperties()
bool CPeripheralBusAndroid::InitializeProperties (CPeripheral & peripheral) override virtual
Initialize the properties of a peripheral with a known location.
Reimplemented from PERIPHERALS::CPeripheralBus.
References PERIPHERALS::CPeripheralJoystick::AxisCount(), PERIPHERALS::CPeripheralJoystick::ButtonCount(), PERIPHERALS::CPeripheral::DeviceName(), PERIPHERALS::CAndroidJoystickState::GetAxisCount(), PERIPHERALS::CAndroidJoystickState::GetButtonCount(), GetDeviceId(), CXBMCApp::GetInputDevice(), PERIPHERALS::CAndroidJoystickState::Initialize(), PERIPHERALS::CPeripheralBus::InitializeProperties(), JOYSTICK_PROVIDER_ANDROID, PERIPHERALS::CPeripheral::Location(), CLog::Log(), LOGDEBUG, LOGWARNING, m_critSectionStates, m_joystickStates, PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERALS::CPeripheralJoystick::SetAxisCount(), PERIPHERALS::CPeripheralJoystick::SetButtonCount(), PERIPHERALS::CPeripheralJoystick::SetProvider(), PERIPHERALS::CPeripheralJoystick::SetRequestedPort(), PERIPHERALS::CPeripheral::Type(), and PERIPHERALS::PeripheralTypeTranslator::TypeToString().
LogInputDevice()
void CPeripheralBusAndroid::LogInputDevice (const CJNIViewInputDevice & device) static private
References GetInputSources(), index(), KEY_CODE_FINAL, CLog::Log(), LOGDEBUG, LOGERROR, PERIPHERALS::CAndroidJoystickTranslator::TranslateAxis(), and PERIPHERALS::CAndroidJoystickTranslator::TranslateKeyCode().
Referenced by GetInputDevices(), and OnInputDeviceAdded().
OnInputDeviceAdded()
void CPeripheralBusAndroid::OnInputDeviceAdded (int deviceId) override virtual
Implements IInputDeviceCallbacks.
References ConvertToPeripheralScanResult(), GetDeviceLocation(), CXBMCApp::GetInputDevice(), CLog::Log(), LOGDEBUG, LOGINFO, LogInputDevice(), LOGWARNING, m_critSectionResults, PERIPHERALS::PeripheralScanResults::m_results, m_scanResults, and PERIPHERALS::CPeripheralBus::OnDeviceAdded().
OnInputDeviceChanged()
void CPeripheralBusAndroid::OnInputDeviceChanged (int deviceId) override virtual
Implements IInputDeviceCallbacks.
References ConvertToPeripheralScanResult(), GetDeviceLocation(), CXBMCApp::GetInputDevice(), CLog::Log(), LOGINFO, LOGWARNING, m_critSectionResults, PERIPHERALS::PeripheralScanResults::m_results, m_scanResults, and PERIPHERALS::CPeripheralBus::OnDeviceChanged().
OnInputDeviceEvent()
bool CPeripheralBusAndroid::OnInputDeviceEvent (const AInputEvent * event) override virtual
Implements IInputDeviceEventHandler.
References CLog::Log(), LOGDEBUG, m_critSectionStates, and m_joystickStates.
OnInputDeviceRemoved()
void CPeripheralBusAndroid::OnInputDeviceRemoved (int deviceId) override virtual
Implements IInputDeviceCallbacks.
References GetDeviceLocation(), CLog::Log(), LOGINFO, LOGWARNING, m_critSectionResults, m_critSectionStates, m_joystickStates, PERIPHERALS::PeripheralScanResults::m_results, m_scanResults, and PERIPHERALS::CPeripheralBus::OnDeviceRemoved().
PerformDeviceScan()
bool CPeripheralBusAndroid::PerformDeviceScan (PeripheralScanResults & results) override protected virtual
Scan for devices on this bus and add them to the results list. This will have to be implemented for each bus.
Parameters
results The result list.
Returns
True when the scan was successful, false otherwise.
Implements PERIPHERALS::CPeripheralBus.
References m_critSectionResults, and m_scanResults.
ProcessEvents()
void CPeripheralBusAndroid::ProcessEvents (void) override virtual
Poll for events.
Reimplemented from PERIPHERALS::CPeripheralBus.
References events, GetDeviceLocation(), PERIPHERALS::CPeripheralBus::GetPeripheral(), JOYSTICK_STATE_BUTTON_PRESSED, m_critSectionStates, m_joystickStates, PERIPHERALS::CPeripheralJoystick::OnAxisMotion(), PERIPHERALS::CPeripheralJoystick::OnButtonMotion(), PERIPHERAL_EVENT_TYPE_DRIVER_AXIS, PERIPHERAL_EVENT_TYPE_DRIVER_BUTTON, and PERIPHERALS::PERIPHERAL_JOYSTICK.
Member Data Documentation
m_critSectionResults
CCriticalSection PERIPHERALS::CPeripheralBusAndroid::m_critSectionResults private
Referenced by OnInputDeviceAdded(), OnInputDeviceChanged(), OnInputDeviceRemoved(), and PerformDeviceScan().
m_critSectionStates
CCriticalSection PERIPHERALS::CPeripheralBusAndroid::m_critSectionStates mutable private
Referenced by InitializeButtonMap(), InitializeProperties(), OnInputDeviceEvent(), OnInputDeviceRemoved(), and ProcessEvents().
m_joystickStates
std::map<int, CAndroidJoystickState> PERIPHERALS::CPeripheralBusAndroid::m_joystickStates mutable private
Referenced by InitializeButtonMap(), InitializeProperties(), OnInputDeviceEvent(), OnInputDeviceRemoved(), and ProcessEvents().
m_scanResults
PeripheralScanResults PERIPHERALS::CPeripheralBusAndroid::m_scanResults private
Referenced by CPeripheralBusAndroid(), OnInputDeviceAdded(), OnInputDeviceChanged(), OnInputDeviceRemoved(), and PerformDeviceScan().
The documentation for this class was generated from the following files:
PeripheralBusAndroid.h
PeripheralBusAndroid.cpp