Kodi Documentation: XFILE::CPosixDirectory Class Reference
XFILE::CPosixDirectory Class Reference
#include <PosixDirectory.h>
Public Member Functions
CPosixDirectory (void)
~CPosixDirectory (void) override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool Create (const CURL &url) override
Create the directory.
bool Exists (const CURL &url) override
Check for directory existence.
bool Remove (const CURL &url) override
Removes the directory.
bool RemoveRecursive (const CURL &url) override
Recursively removes the directory.
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual bool AllowAll () const
Whether to allow all files/folders to be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Private Member Functions
bool Create (const std::string &path)
Additional Inherited Members
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CPosixDirectory()
CPosixDirectory::CPosixDirectory (void) default
~CPosixDirectory()
CPosixDirectory::~CPosixDirectory (void) override default
Member Function Documentation
Create() [1/2]
bool CPosixDirectory::Create (const CURL & url) override virtual
Create the directory.
Parameters
url Directory to create.
Returns
Returns true, if directory is created or if it already exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
Reimplemented in XFILE::CTVOSDirectory.
References Create(), Exists(), and CURL::Get().
Referenced by XFILE::CTVOSDirectory::Create(), Create(), and Create().
Create() [2/2]
bool CPosixDirectory::Create (const std::string & path) private
References Create(), and mkdir().
Exists()
bool CPosixDirectory::Exists (const CURL & url) override virtual
Check for directory existence.
Parameters
url Directory to check.
Returns
Returns true, if directory exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
Reimplemented in XFILE::CTVOSDirectory.
References CURL::Get(), IsAliasShortcut(), S_ISDIR, and TranslateAliasShortcut().
Referenced by Create(), XFILE::CTVOSDirectory::Exists(), and Remove().
GetDirectory()
bool CPosixDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
Reimplemented in XFILE::CTVOSDirectory.
References CFileItemList::Add(), URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), closedir(), dirent::d_name, dirent::d_type, XFILE::DIR_FLAG_NO_FILE_INFO, DT_DIR, DT_UNKNOWN, KODI::TIME::FileTimeToLocalFileTime(), CURL::Get(), IsAliasShortcut(), XFILE::IDirectory::m_flags, opendir(), readdir(), root, S_ISDIR, KODI::TIME::TimeTToFileTime(), TranslateAliasShortcut(), and CCharsetConverter::unknownToUTF8().
Referenced by XFILE::CTVOSDirectory::GetDirectory().
Remove()
bool CPosixDirectory::Remove (const CURL & url) override virtual
Removes the directory.
Parameters
url Directory to remove.
Returns
Returns false if not successful
Reimplemented from XFILE::IDirectory.
Reimplemented in XFILE::CTVOSDirectory.
References Exists(), CURL::Get(), and rmdir().
Referenced by XFILE::CTVOSDirectory::Remove().
RemoveRecursive()
bool CPosixDirectory::RemoveRecursive (const CURL & url) override virtual
Recursively removes the directory.
Parameters
url Directory to remove.
Returns
Returns false if not successful
Reimplemented from XFILE::IDirectory.
References URIUtils::AddFileToFolder(), closedir(), dirent::d_name, dirent::d_type, DT_DIR, DT_UNKNOWN, CURL::Get(), IsAliasShortcut(), opendir(), readdir(), RemoveRecursive(), rmdir(), root, S_ISDIR, success, TranslateAliasShortcut(), and CCharsetConverter::unknownToUTF8().
Referenced by RemoveRecursive().
The documentation for this class was generated from the following files:
PosixDirectory.h
PosixDirectory.cpp