Kodi Documentation: KODI::RETRO::CGUIGameRenderManager Class Reference
KODI::RETRO::CGUIGameRenderManager Class Reference
Class to safely route commands between the GUI and RetroPlayer.
#include <GUIGameRenderManager.h>
Public Member Functions
CGUIGameRenderManager ()=default
~CGUIGameRenderManager ()
void RegisterPlayer (CGUIRenderTargetFactory *factory, IRenderCallback *callback, IGameCallback *gameCallback)
Register a RetroPlayer instance.
void UnregisterPlayer ()
Unregister a RetroPlayer instance.
std::shared_ptr< CGUIRenderHandle > RegisterControl (CGUIGameControl &control)
Register a GUI game control ("gamewindow" skin control)
std::shared_ptr< CGUIRenderHandle > RegisterWindow (CGameWindowFullScreen &window)
Register a fullscreen game window ("FullscreenGame" window)
std::shared_ptr< CGUIGameVideoHandle > RegisterDialog (GAME::CDialogGameVideoSelect &dialog)
Register a video select dialog (for selecting video filters, view modes, etc.)
std::shared_ptr< CGUIGameSettingsHandle > RegisterGameSettingsDialog ()
Register a game settings dialog.
Protected Member Functions
void UnregisterHandle (CGUIRenderHandle *handle)
void Render (CGUIRenderHandle *handle)
void RenderEx (CGUIRenderHandle *handle)
void ClearBackground (CGUIRenderHandle *handle)
bool IsDirty (CGUIRenderHandle *handle)
void UnregisterHandle (CGUIGameVideoHandle *handle)
bool IsPlayingGame ()
bool SupportsRenderFeature (RENDERFEATURE feature)
bool SupportsScalingMethod (SCALINGMETHOD method)
void UnregisterHandle (CGUIGameSettingsHandle *handle)
std::string GameClientID ()
std::string GetPlayingGame ()
std::string CreateSavestate (bool autosave)
bool UpdateSavestate (const std::string &savestatePath)
bool LoadSavestate (const std::string &savestatePath)
void FreeSavestateResources (const std::string &savestatePath)
void CloseOSD ()
Private Member Functions
void UpdateRenderTargets ()
Helper function to create or destroy render targets when a factory is registered/unregistered.
CGUIRenderTarget * CreateRenderTarget (CGUIRenderHandle *handle)
Helper function to create a render target.
Private Attributes
CGUIRenderTargetFactory * m_factory = nullptr
std::map< CGUIRenderHandle *, std::shared_ptr< CGUIRenderTarget > > m_renderTargets
CCriticalSection m_targetMutex
IRenderCallback * m_callback = nullptr
CCriticalSection m_callbackMutex
IGameCallback * m_gameCallback = nullptr
CCriticalSection m_gameCallbackMutex
Friends
class CGUIGameSettingsHandle
class CGUIGameVideoHandle
class CGUIRenderHandle
Detailed Description
Class to safely route commands between the GUI and RetroPlayer.
This class is brought up before the GUI and player core factory. It provides the GUI with safe access to a registered player.
Access to the player is done through handles. When a handle is no longer needed, it should be destroyed.
Three kinds of handles are provided:
CGUIRenderHandle Allows the holder to invoke render events
CGUIGameVideoHandle Allows the holder to query video properties, such as the filter or view mode.
CGUIGameSettingsHandle Allows the holder to query game properties, such as the ID of the game client or the game's filename.
Each manager fulfills the following design requirements:
No assumption of player lifetimes
No assumption of GUI element lifetimes, as long as handles are destroyed before this class is destructed
No limit on the number of handles
Constructor & Destructor Documentation
CGUIGameRenderManager()
KODI::RETRO::CGUIGameRenderManager::CGUIGameRenderManager () default
~CGUIGameRenderManager()
CGUIGameRenderManager::~CGUIGameRenderManager () default
Member Function Documentation
ClearBackground()
void CGUIGameRenderManager::ClearBackground (CGUIRenderHandle * handle) protected
References m_renderTargets, and m_targetMutex.
Referenced by KODI::RETRO::CGUIRenderHandle::ClearBackground().
CloseOSD()
void CGUIGameRenderManager::CloseOSD () protected
References KODI::RETRO::IGameCallback::CloseOSDCallback(), m_callbackMutex, and m_gameCallback.
Referenced by KODI::RETRO::CGUIGameSettingsHandle::CloseOSD().
CreateRenderTarget()
CGUIRenderTarget * CGUIGameRenderManager::CreateRenderTarget (CGUIRenderHandle * handle) private
Helper function to create a render target.
Parameters
handle The handle given to the registered GUI element
Returns
A target to receive rendering commands
References KODI::RETRO::CONTROL, KODI::RETRO::CGUIRenderTargetFactory::CreateRenderControl(), KODI::RETRO::CGUIRenderTargetFactory::CreateRenderFullScreen(), KODI::RETRO::CGUIRenderControlHandle::GetControl(), KODI::RETRO::CGUIRenderFullScreenHandle::GetWindow(), m_factory, KODI::RETRO::CGUIRenderHandle::Type(), and KODI::RETRO::WINDOW.
Referenced by UpdateRenderTargets().
CreateSavestate()
std::string CGUIGameRenderManager::CreateSavestate (bool autosave) protected
References KODI::RETRO::IGameCallback::CreateSavestate(), m_callbackMutex, and m_gameCallback.
Referenced by KODI::RETRO::CGUIGameSettingsHandle::CreateSavestate().
FreeSavestateResources()
void CGUIGameRenderManager::FreeSavestateResources (const std::string & savestatePath) protected
References KODI::RETRO::IGameCallback::FreeSavestateResources(), m_callbackMutex, and m_gameCallback.
Referenced by KODI::RETRO::CGUIGameSettingsHandle::FreeSavestateResources().
GameClientID()
std::string CGUIGameRenderManager::GameClientID () protected
References KODI::RETRO::IGameCallback::GameClientID(), m_callbackMutex, and m_gameCallback.
Referenced by KODI::RETRO::CGUIGameSettingsHandle::GameClientID().
GetPlayingGame()
std::string CGUIGameRenderManager::GetPlayingGame () protected
References KODI::RETRO::IGameCallback::GetPlayingGame(), m_callbackMutex, and m_gameCallback.
Referenced by KODI::RETRO::CGUIGameSettingsHandle::GetPlayingGame().
IsDirty()
bool CGUIGameRenderManager::IsDirty (CGUIRenderHandle * handle) protected
References m_renderTargets, and m_targetMutex.
Referenced by KODI::RETRO::CGUIRenderHandle::IsDirty().
IsPlayingGame()
bool CGUIGameRenderManager::IsPlayingGame () protected
References m_callback, and m_callbackMutex.
Referenced by KODI::RETRO::CGUIGameVideoHandle::IsPlayingGame().
LoadSavestate()
bool CGUIGameRenderManager::LoadSavestate (const std::string & savestatePath) protected
References KODI::RETRO::IGameCallback::LoadSavestate(), m_callbackMutex, and m_gameCallback.
Referenced by KODI::RETRO::CGUIGameSettingsHandle::LoadSavestate().
RegisterControl()
std::shared_ptr< CGUIRenderHandle > CGUIGameRenderManager::RegisterControl (CGUIGameControl & control)
Register a GUI game control ("gamewindow" skin control)
Parameters
control The game control
Returns
A handle to invoke render events
References KODI::RETRO::CGUIRenderTargetFactory::CreateRenderControl(), m_factory, m_renderTargets, and m_targetMutex.
Referenced by KODI::RETRO::CGUIGameControl::RegisterControl().
RegisterDialog()
std::shared_ptr< CGUIGameVideoHandle > CGUIGameRenderManager::RegisterDialog (GAME::CDialogGameVideoSelect & dialog)
Register a video select dialog (for selecting video filters, view modes, etc.)
Parameters
dialog The video select dialog
Returns
A handle to query game and video properties
Referenced by KODI::GAME::CDialogGameVideoSelect::RegisterDialog().
RegisterGameSettingsDialog()
std::shared_ptr< CGUIGameSettingsHandle > CGUIGameRenderManager::RegisterGameSettingsDialog ()
Register a game settings dialog.
Returns
A handle to query game properties
Referenced by KODI::GAME::CDialogInGameSaves::InitSavedGames(), KODI::GAME::CDialogInGameSaves::OnDelete(), KODI::GAME::CGUIAgentWindow::OnInitWindow(), KODI::GAME::CGUIControllerWindow::OnInitWindow(), KODI::GAME::CGUIPortWindow::OnInitWindow(), KODI::GAME::CDialogInGameSaves::OnLoad(), KODI::GAME::CDialogGameAdvancedSettings::OnMessage(), KODI::GAME::CDialogInGameSaves::OnNewSave(), and KODI::GAME::CDialogInGameSaves::OnOverwrite().
RegisterPlayer()
void CGUIGameRenderManager::RegisterPlayer (CGUIRenderTargetFactory * factory, IRenderCallback * callback, IGameCallback * gameCallback)
Register a RetroPlayer instance.
Parameters
factory The interface for creating render targets exposed to the GUI
callback The interface for querying video properties
gameCallback The interface for querying game properties
References m_callback, m_callbackMutex, m_factory, m_gameCallback, m_gameCallbackMutex, m_targetMutex, and UpdateRenderTargets().
Referenced by KODI::RETRO::CRetroPlayer::RegisterWindowCallbacks().
RegisterWindow()
std::shared_ptr< CGUIRenderHandle > CGUIGameRenderManager::RegisterWindow (CGameWindowFullScreen & window)
Register a fullscreen game window ("FullscreenGame" window)
Parameters
window The game window
Returns
A handle to invoke render events
References KODI::RETRO::CGUIRenderTargetFactory::CreateRenderFullScreen(), m_factory, m_renderTargets, and m_targetMutex.
Referenced by KODI::RETRO::CGameWindowFullScreen::RegisterWindow().
Render()
void CGUIGameRenderManager::Render (CGUIRenderHandle * handle) protected
References m_renderTargets, and m_targetMutex.
Referenced by KODI::RETRO::CGUIRenderHandle::Render().
RenderEx()
void CGUIGameRenderManager::RenderEx (CGUIRenderHandle * handle) protected
References m_renderTargets, and m_targetMutex.
Referenced by KODI::RETRO::CGUIRenderHandle::RenderEx().
SupportsRenderFeature()
bool CGUIGameRenderManager::SupportsRenderFeature (RENDERFEATURE feature) protected
References m_callback, m_callbackMutex, and KODI::RETRO::IRenderCallback::SupportsRenderFeature().
Referenced by KODI::RETRO::CGUIGameVideoHandle::SupportsRenderFeature().
SupportsScalingMethod()
bool CGUIGameRenderManager::SupportsScalingMethod (SCALINGMETHOD method) protected
References m_callback, m_callbackMutex, and KODI::RETRO::IRenderCallback::SupportsScalingMethod().
Referenced by KODI::RETRO::CGUIGameVideoHandle::SupportsScalingMethod().
UnregisterHandle() [1/3]
void KODI::RETRO::CGUIGameRenderManager::UnregisterHandle (CGUIGameSettingsHandle * handle) inline protected
UnregisterHandle() [2/3]
void KODI::RETRO::CGUIGameRenderManager::UnregisterHandle (CGUIGameVideoHandle * handle) inline protected
UnregisterHandle() [3/3]
void CGUIGameRenderManager::UnregisterHandle (CGUIRenderHandle * handle) protected
References m_renderTargets, and m_targetMutex.
Referenced by KODI::RETRO::CGUIGameSettingsHandle::~CGUIGameSettingsHandle(), KODI::RETRO::CGUIGameVideoHandle::~CGUIGameVideoHandle(), and KODI::RETRO::CGUIRenderHandle::~CGUIRenderHandle().
UnregisterPlayer()
void CGUIGameRenderManager::UnregisterPlayer ()
Unregister a RetroPlayer instance.
References m_callback, m_callbackMutex, m_factory, m_gameCallback, m_gameCallbackMutex, m_targetMutex, and UpdateRenderTargets().
Referenced by KODI::RETRO::CRetroPlayer::UnregisterWindowCallbacks().
UpdateRenderTargets()
void CGUIGameRenderManager::UpdateRenderTargets () private
Helper function to create or destroy render targets when a factory is registered/unregistered.
References CreateRenderTarget(), m_factory, and m_renderTargets.
Referenced by RegisterPlayer(), and UnregisterPlayer().
UpdateSavestate()
bool CGUIGameRenderManager::UpdateSavestate (const std::string & savestatePath) protected
References m_callbackMutex, m_gameCallback, and KODI::RETRO::IGameCallback::UpdateSavestate().
Referenced by KODI::RETRO::CGUIGameSettingsHandle::UpdateSavestate().
Friends And Related Symbol Documentation
CGUIGameSettingsHandle
friend class CGUIGameSettingsHandle friend
CGUIGameVideoHandle
friend class CGUIGameVideoHandle friend
CGUIRenderHandle
friend class CGUIRenderHandle friend
Member Data Documentation
m_callback
IRenderCallback* KODI::RETRO::CGUIGameRenderManager::m_callback = nullptr private
Referenced by IsPlayingGame(), RegisterPlayer(), SupportsRenderFeature(), SupportsScalingMethod(), and UnregisterPlayer().
m_callbackMutex
CCriticalSection KODI::RETRO::CGUIGameRenderManager::m_callbackMutex private
Referenced by CloseOSD(), CreateSavestate(), FreeSavestateResources(), GameClientID(), GetPlayingGame(), IsPlayingGame(), LoadSavestate(), RegisterPlayer(), SupportsRenderFeature(), SupportsScalingMethod(), UnregisterPlayer(), and UpdateSavestate().
m_factory
CGUIRenderTargetFactory* KODI::RETRO::CGUIGameRenderManager::m_factory = nullptr private
Referenced by CreateRenderTarget(), RegisterControl(), RegisterPlayer(), RegisterWindow(), UnregisterPlayer(), and UpdateRenderTargets().
m_gameCallback
IGameCallback* KODI::RETRO::CGUIGameRenderManager::m_gameCallback = nullptr private
Referenced by CloseOSD(), CreateSavestate(), FreeSavestateResources(), GameClientID(), GetPlayingGame(), LoadSavestate(), RegisterPlayer(), UnregisterPlayer(), and UpdateSavestate().
m_gameCallbackMutex
CCriticalSection KODI::RETRO::CGUIGameRenderManager::m_gameCallbackMutex private
Referenced by RegisterPlayer(), and UnregisterPlayer().
m_renderTargets
std::map<CGUIRenderHandle*, std::shared_ptr<CGUIRenderTarget> > KODI::RETRO::CGUIGameRenderManager::m_renderTargets private
Referenced by ClearBackground(), IsDirty(), RegisterControl(), RegisterWindow(), Render(), RenderEx(), UnregisterHandle(), and UpdateRenderTargets().
m_targetMutex
CCriticalSection KODI::RETRO::CGUIGameRenderManager::m_targetMutex private
Referenced by ClearBackground(), IsDirty(), RegisterControl(), RegisterPlayer(), RegisterWindow(), Render(), RenderEx(), UnregisterHandle(), and UnregisterPlayer().
The documentation for this class was generated from the following files:
GUIGameRenderManager.h
GUIGameRenderManager.cpp