Kodi Documentation: CZeroconfBrowserAvahi Class Reference
CZeroconfBrowserAvahi Class Reference
#include <ZeroconfBrowserAvahi.h>
Classes
struct AvahiSpecificInfos
Public Member Functions
CZeroconfBrowserAvahi ()
~CZeroconfBrowserAvahi () override
Public Member Functions inherited from CZeroconfBrowser
void Start ()
void Stop ()
std::vector< ZeroconfService > GetFoundServices ()
bool ResolveService (ZeroconfService &fr_service, double f_timeout=1.0)
virtual void ProcessResults ()
bool AddServiceType (const std::string &fcr_service_type)
bool RemoveServiceType (const std::string &fcr_service_type)
Private Member Functions
bool doAddServiceType (const std::string &fcr_service_type) override
bool doRemoveServiceType (const std::string &fcr_service_type) override
std::vector< CZeroconfBrowser::ZeroconfService > doGetFoundServices () override
bool doResolveService (CZeroconfBrowser::ZeroconfService &fr_service, double f_timeout) override
typedef std::map< std::string, AvahiServiceBrowser * > tBrowserMap
typedef std::map< CZeroconfBrowser::ZeroconfService, AvahiSpecificInfos > tDiscoveredServices
AvahiClient * mp_client = 0
AvahiThreadedPoll * mp_poll = 0
tBrowserMap m_browsers
std::set< AvahiServiceBrowser * > m_all_for_now_browsers
tDiscoveredServices m_discovered_services
CZeroconfBrowser::ZeroconfService m_resolving_service
CEvent m_resolved_event
bool createClient ()
static void clientCallback (AvahiClient *c, AvahiClientState state, AVAHI_GCC_UNUSED void *userdata)
static void browseCallback (AvahiServiceBrowser *b, AvahiIfIndex interface, AvahiProtocol protocol, AvahiBrowserEvent event, const char *name, const char *type, const char *domain, AVAHI_GCC_UNUSED AvahiLookupResultFlags flags, void *userdata)
static void resolveCallback (AvahiServiceResolver *r, AvahiIfIndex interface, AvahiProtocol protocol, AvahiResolverEvent event, const char *name, const char *type, const char *domain, const char *host_name, const AvahiAddress *address, uint16_t port, AvahiStringList *txt, AvahiLookupResultFlags flags, AVAHI_GCC_UNUSED void *userdata)
static AvahiServiceBrowser * createServiceBrowser (const std::string &fcr_service_type, AvahiClient *fp_client, void *fp_userdata)
Additional Inherited Members
Static Public Member Functions inherited from CZeroconfBrowser
static CZeroconfBrowser * GetInstance ()
static void ReleaseInstance ()
static bool IsInstantiated ()
Protected Member Functions inherited from CZeroconfBrowser
CZeroconfBrowser (const CZeroconfBrowser &)=delete
CZeroconfBrowser & operator= (const CZeroconfBrowser &)=delete
Member Typedef Documentation
tBrowserMap
typedef std::map<std::string, AvahiServiceBrowser*> CZeroconfBrowserAvahi::tBrowserMap private
tDiscoveredServices
typedef std::map<CZeroconfBrowser::ZeroconfService, AvahiSpecificInfos> CZeroconfBrowserAvahi::tDiscoveredServices private
Constructor & Destructor Documentation
CZeroconfBrowserAvahi()
CZeroconfBrowserAvahi::CZeroconfBrowserAvahi ()
Todo:
throw exception? can this even happen?
References createClient(), CLog::Log(), LOGERROR, and mp_poll.
~CZeroconfBrowserAvahi()
CZeroconfBrowserAvahi::~CZeroconfBrowserAvahi () override
References CLog::Log(), LOGDEBUG, mp_client, and mp_poll.
Member Function Documentation
browseCallback()
void CZeroconfBrowserAvahi::browseCallback (AvahiServiceBrowser * b, AvahiIfIndex interface, AvahiProtocol protocol, AvahiBrowserEvent event, const char * name, const char * type, const char * domain, AVAHI_GCC_UNUSED AvahiLookupResultFlags flags, void * userdata) static private
Todo:
implement
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_PATH, CZeroconfBrowserAvahi::AvahiSpecificInfos::interface, CLog::Log(), LOGDEBUG, LOGERROR, m_all_for_now_browsers, m_discovered_services, name, CGUIMessage::SetStringParam(), and success.
Referenced by createServiceBrowser().
clientCallback()
void CZeroconfBrowserAvahi::clientCallback (AvahiClient * c, AvahiClientState state, AVAHI_GCC_UNUSED void * userdata) static private
avahi callbacks
References createClient(), createServiceBrowser(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_PATH, CLog::Log(), LOGDEBUG, LOGINFO, m_browsers, m_discovered_services, mp_client, and CGUIMessage::SetStringParam().
Referenced by createClient().
createClient()
bool CZeroconfBrowserAvahi::createClient () private
References clientCallback(), mp_client, and mp_poll.
Referenced by clientCallback(), and CZeroconfBrowserAvahi().
createServiceBrowser()
AvahiServiceBrowser * CZeroconfBrowserAvahi::createServiceBrowser (const std::string & fcr_service_type, AvahiClient * fp_client, void * fp_userdata) static private
References browseCallback(), CLog::Log(), and LOGERROR.
Referenced by clientCallback(), and doAddServiceType().
doAddServiceType()
bool CZeroconfBrowserAvahi::doAddServiceType (const std::string & fcr_service_type) override private virtual
implementation if CZeroconfBrowser interface
Implements CZeroconfBrowser.
References createServiceBrowser(), CLog::Log(), LOGINFO, m_browsers, mp_client, and mp_poll.
doGetFoundServices()
std::vector< CZeroconfBrowser::ZeroconfService > CZeroconfBrowserAvahi::doGetFoundServices () override private virtual
Implements CZeroconfBrowser.
References m_discovered_services, and mp_poll.
doRemoveServiceType()
bool CZeroconfBrowserAvahi::doRemoveServiceType (const std::string & fcr_service_type) override private virtual
Implements CZeroconfBrowser.
References m_all_for_now_browsers, m_browsers, m_discovered_services, and mp_poll.
doResolveService()
bool CZeroconfBrowserAvahi::doResolveService (CZeroconfBrowser::ZeroconfService & fr_service, double f_timeout) override private virtual
Implements CZeroconfBrowser.
References CZeroconfBrowser::ZeroconfService::GetIP(), CLog::Log(), LOGERROR, m_discovered_services, m_resolved_event, m_resolving_service, mp_client, mp_poll, CEvent::Reset(), resolveCallback(), and CEvent::Wait().
resolveCallback()
void CZeroconfBrowserAvahi::resolveCallback (AvahiServiceResolver * r, AvahiIfIndex interface, AvahiProtocol protocol, AvahiResolverEvent event, const char * name, const char * type, const char * domain, const char * host_name, const AvahiAddress * address, uint16_t port, AvahiStringList * txt, AvahiLookupResultFlags flags, AVAHI_GCC_UNUSED void * userdata) static private
References GetTxtRecords(), CLog::Log(), LOGDEBUG, LOGERROR, m_resolved_event, m_resolving_service, name, CEvent::Set(), CZeroconfBrowser::ZeroconfService::SetIP(), CZeroconfBrowser::ZeroconfService::SetPort(), and CZeroconfBrowser::ZeroconfService::SetTxtRecords().
Referenced by doResolveService().
Member Data Documentation
m_all_for_now_browsers
std::set<AvahiServiceBrowser*> CZeroconfBrowserAvahi::m_all_for_now_browsers private
Referenced by browseCallback(), and doRemoveServiceType().
m_browsers
tBrowserMap CZeroconfBrowserAvahi::m_browsers private
Referenced by clientCallback(), doAddServiceType(), and doRemoveServiceType().
m_discovered_services
tDiscoveredServices CZeroconfBrowserAvahi::m_discovered_services private
Referenced by browseCallback(), clientCallback(), doGetFoundServices(), doRemoveServiceType(), and doResolveService().
m_resolved_event
CEvent CZeroconfBrowserAvahi::m_resolved_event private
Referenced by doResolveService(), and resolveCallback().
m_resolving_service
CZeroconfBrowser::ZeroconfService CZeroconfBrowserAvahi::m_resolving_service private
Referenced by doResolveService(), and resolveCallback().
mp_client
AvahiClient* CZeroconfBrowserAvahi::mp_client = 0 private
Referenced by clientCallback(), createClient(), doAddServiceType(), doResolveService(), and ~CZeroconfBrowserAvahi().
mp_poll
AvahiThreadedPoll* CZeroconfBrowserAvahi::mp_poll = 0 private
Referenced by createClient(), CZeroconfBrowserAvahi(), doAddServiceType(), doGetFoundServices(), doRemoveServiceType(), doResolveService(), and ~CZeroconfBrowserAvahi().
The documentation for this class was generated from the following files:
ZeroconfBrowserAvahi.h
ZeroconfBrowserAvahi.cpp