Kodi Documentation: CGUIAction Class Reference
CGUIAction Class Reference
#include <GUIAction.h>
Classes
class CExecutableAction
Public Member Functions
CGUIAction ()=default
CGUIAction (int controlID)
bool ExecuteActions () const
bool ExecuteActions (int controlID, int parentID, const std::shared_ptr< CGUIListItem > &item=nullptr) const
bool HasConditionalActions () const
bool HasActionsMeetingCondition () const
bool HasAnyActions () const
size_t GetActionCount () const
int GetNavigation () const
void SetNavigation (int id)
void EnableSendThreadMessageMode ()
void Append (const CExecutableAction &action)
void Reset ()
bool operator== (const CGUIAction &rhs) const
Private Attributes
std::vector< CExecutableAction > m_actions
bool m_sendThreadMessages = false
Detailed Description
Class containing vector of condition->(action/navigation route) and handling its execution.
Constructor & Destructor Documentation
CGUIAction() [1/2]
CGUIAction::CGUIAction () default
CGUIAction() [2/2]
CGUIAction::CGUIAction (int controlID) explicit
References SetNavigation().
Member Function Documentation
Append()
void CGUIAction::Append (const CExecutableAction & action)
Add an executable action to the CGUIAction container
References m_actions.
Referenced by CSkinTimerManager::LoadTimerInternal(), and TEST_P().
EnableSendThreadMessageMode()
void CGUIAction::EnableSendThreadMessageMode ()
Configure CGUIAction to send threaded messages
References m_sendThreadMessages.
Referenced by CGUIControlFactory::Create(), and CSkinTimerManager::LoadTimerInternal().
ExecuteActions() [1/2]
bool CGUIAction::ExecuteActions () const
Execute actions without specifying any target control or parent control. Action will use the default focused control.
References ExecuteActions().
Referenced by ExecuteActions(), CGUIButtonControl::OnClick(), CStaticListProvider::OnClick(), CGUIBaseContainer::OnClick(), CGUIBaseContainer::OnFocus(), CGUIButtonControl::OnFocus(), CSkinTimer::OnStart(), CSkinTimer::OnStop(), CGUIBaseContainer::OnUnFocus(), CGUIButtonControl::OnUnFocus(), CGUIWindow::RunLoadActions(), CGUIWindow::RunUnloadActions(), and CGUIEditControl::UpdateText().
ExecuteActions() [2/2]
bool CGUIAction::ExecuteActions (int controlID, int parentID, const std::shared_ptr< CGUIListItem > & item = nullptr) const
Execute actions (no navigation paths); if action is paired with condition - evaluate condition first
References actions, CGUIInfoManager::EvaluateBool(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIComponent::GetWindowManager(), GUI_MSG_EXECUTE, m_actions, m_sendThreadMessages, CGUIWindowManager::SendMessage(), and CGUIMessage::SetStringParam().
GetActionCount()
size_t CGUIAction::GetActionCount () const
Get the total number of actions
References m_actions.
GetNavigation()
int CGUIAction::GetNavigation () const
Get navigation route that meet its conditions first
References INFO::DEFAULT_CONTEXT, CGUIInfoManager::EvaluateBool(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), and m_actions.
Referenced by CGUIControlGroupList::AddControl(), XBMCAddon::xbmcgui::Window::GetControlById(), and PVR::CGUIWindowPVRGuideBase::ShouldNavigateToGridContainer().
HasActionsMeetingCondition()
bool CGUIAction::HasActionsMeetingCondition () const
Check if there is any action that meet its condition
References INFO::DEFAULT_CONTEXT, CGUIInfoManager::EvaluateBool(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), and m_actions.
Referenced by CGUIControlGroupList::AddControl(), CGUIButtonControl::HasClickActions(), CGUIEditControl::HasTextChangeActions(), and CGUIBaseContainer::OnClick().
HasAnyActions()
bool CGUIAction::HasAnyActions () const
Check if there is any action
References m_actions.
Referenced by CGUIBaseContainer::OnFocus(), CSkinTimer::OnStart(), CSkinTimer::OnStop(), and CGUIBaseContainer::OnUnFocus().
HasConditionalActions()
bool CGUIAction::HasConditionalActions () const
Check if there are any conditional actions
References m_actions.
operator==()
bool CGUIAction::operator== (const CGUIAction & rhs) const inline
References m_actions, and m_sendThreadMessages.
Reset()
void CGUIAction::Reset ()
Prune any executable actions stored in the CGUIAction
References m_actions.
SetNavigation()
void CGUIAction::SetNavigation (int id)
Set navigation route
References m_actions.
Referenced by CGUIAction().
Member Data Documentation
m_actions
std::vector<CExecutableAction> CGUIAction::m_actions private
Referenced by Append(), ExecuteActions(), GetActionCount(), GetNavigation(), HasActionsMeetingCondition(), HasAnyActions(), HasConditionalActions(), operator==(), Reset(), and SetNavigation().
m_sendThreadMessages
bool CGUIAction::m_sendThreadMessages = false private
Referenced by EnableSendThreadMessageMode(), ExecuteActions(), and operator==().
The documentation for this class was generated from the following files:
GUIAction.h
GUIAction.cpp