Kodi Documentation: KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser Class Reference
KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser Class Reference
Public Member Functions
CVideoChooser (const std::shared_ptr< const CFileItem > &item)
virtual ~CVideoChooser ()=default
void EnableTypeSwitch (bool enable)
void SetInitialAssetType (VideoAssetType type)
std::shared_ptr< const CFileItem > ChooseVideo ()
Private Member Functions
CVideoChooser ()=delete
std::shared_ptr< const CFileItem > ChooseVideoVersion ()
std::shared_ptr< const CFileItem > ChooseVideoExtra ()
std::shared_ptr< const CFileItem > ChooseVideo (CGUIDialogSelect &dialog, int headingId, int buttonId, CFileItemList &itemsToDisplay, const CFileItemList &itemsToSwitchTo)
Private Attributes
const std::shared_ptr< const CFileItem > m_item
bool m_enableTypeSwitch {false}
VideoAssetType m_initialAssetType {VideoAssetType::UNKNOWN}
bool m_switchType {false}
CFileItemList m_videoVersions
CFileItemList m_videoExtras
Constructor & Destructor Documentation
CVideoChooser() [1/2]
KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::CVideoChooser (const std::shared_ptr< const CFileItem > & item) inline explicit
~CVideoChooser()
virtual KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::~CVideoChooser () virtual default
CVideoChooser() [2/2]
KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::CVideoChooser () private delete
Member Function Documentation
ChooseVideo() [1/2]
std::shared_ptr< const CFileItem > KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo ()
References CFileItemList::Clear(), EXTRA, CVideoDatabase::GetAssetsForVideo(), LOGERROR, CVideoDatabase::Open(), and VERSION.
ChooseVideo() [2/2]
std::shared_ptr< const CFileItem > KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo (CGUIDialogSelect & dialog, int headingId, int buttonId, CFileItemList & itemsToDisplay, const CFileItemList & itemsToSwitchTo) private
References CGUIDialogSelect::EnableButton(), g_localizeStrings, CLocalizeStrings::Get(), CGUIDialogSelect::GetSelectedFileItem(), CGUIDialogSelect::IsButtonPressed(), CGUIDialogBoxBase::IsConfirmed(), CFileItemList::IsEmpty(), CBackgroundInfoLoader::IsLoading(), CBackgroundInfoLoader::Load(), CGUIDialog::Open(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CGUIDialogSelect::SetMultiSelection(), CGUIDialogSelect::SetUseDetails(), and CBackgroundInfoLoader::StopThread().
ChooseVideoExtra()
std::shared_ptr< const CFileItem > KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideoExtra () private
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), LOGERROR, and WINDOW_DIALOG_SELECT_VIDEO_EXTRA.
ChooseVideoVersion()
std::shared_ptr< const CFileItem > KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideoVersion () private
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), LOGERROR, and WINDOW_DIALOG_SELECT_VIDEO_VERSION.
EnableTypeSwitch()
void KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::EnableTypeSwitch (bool enable) inline
SetInitialAssetType()
void KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::SetInitialAssetType (VideoAssetType type) inline
Member Data Documentation
m_enableTypeSwitch
bool KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::m_enableTypeSwitch {false} private
m_initialAssetType
VideoAssetType KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::m_initialAssetType {VideoAssetType::UNKNOWN} private
m_item
const std::shared_ptr<const CFileItem> KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::m_item private
m_switchType
bool KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::m_switchType {false} private
m_videoExtras
CFileItemList KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::m_videoExtras private
m_videoVersions
CFileItemList KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::m_videoVersions private
The documentation for this class was generated from the following file:
VideoVersionHelper.cpp