Kodi Documentation: KODI::WINDOWING::GBM::CDRMAtomic Class Reference
KODI::WINDOWING::GBM::CDRMAtomic Class Reference
#include <DRMAtomic.h>
Classes
class CDRMAtomicRequest
Public Member Functions
CDRMAtomic ()=default
~CDRMAtomic () override=default
void FlipPage (struct gbm_bo *bo, bool rendered, bool videoLayer, bool async) override
bool SetVideoMode (const RESOLUTION_INFO &res, struct gbm_bo *bo) override
bool SetActive (bool active) override
bool InitDrm () override
void DestroyDrm () override
bool AddProperty (CDRMObject *object, const char *name, uint64_t value)
bool DisplayHardwareScalingEnabled ()
Public Member Functions inherited from KODI::WINDOWING::GBM::CDRMUtils
CDRMUtils ()=default
virtual ~CDRMUtils ()
int GetFileDescriptor () const
int GetRenderNodeFileDescriptor () const
const char * GetRenderDevicePath () const
CDRMPlane * GetVideoPlane () const
CDRMPlane * GetGuiPlane () const
CDRMCrtc * GetCrtc () const
CDRMConnector * GetConnector () const
std::vector< std::string > GetConnectedConnectorNames ()
virtual RESOLUTION_INFO GetCurrentMode ()
virtual std::vector< RESOLUTION_INFO > GetModes ()
virtual bool SetMode (const RESOLUTION_INFO &res)
void SetInFenceFd (int fd)
int TakeOutFenceFd ()
Private Member Functions
void DrmAtomicCommit (int fb_id, int flags, bool rendered, bool videoLayer)
bool SetScalingFilter (CDRMObject *object, const char *name, const char *type)
Private Attributes
bool m_need_modeset
bool m_active = true
CDRMAtomicRequest * m_req = nullptr
std::deque< std::unique_ptr< CDRMAtomicRequest > > m_atomicRequestQueue
Additional Inherited Members
Static Public Member Functions inherited from KODI::WINDOWING::GBM::CDRMUtils
static uint32_t FourCCWithAlpha (uint32_t fourcc)
static uint32_t FourCCWithoutAlpha (uint32_t fourcc)
Protected Member Functions inherited from KODI::WINDOWING::GBM::CDRMUtils
bool OpenDrm (bool needConnector)
drm_fb * DrmFbGetFromBo (struct gbm_bo *bo)
Protected Attributes inherited from KODI::WINDOWING::GBM::CDRMUtils
int m_fd
CDRMConnector * m_connector {nullptr}
CDRMEncoder * m_encoder {nullptr}
CDRMCrtc * m_crtc {nullptr}
CDRMCrtc * m_orig_crtc {nullptr}
CDRMPlane * m_video_plane {nullptr}
CDRMPlane * m_gui_plane {nullptr}
drmModeModeInfo * m_mode = nullptr
int m_width = 0
int m_height = 0
int m_inFenceFd {-1}
int m_outFenceFd {-1}
std::vector< std::unique_ptr< CDRMPlane > > m_planes
Constructor & Destructor Documentation
CDRMAtomic()
KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomic () default
~CDRMAtomic()
KODI::WINDOWING::GBM::CDRMAtomic::~CDRMAtomic () override default
Member Function Documentation
AddProperty()
bool CDRMAtomic::AddProperty (CDRMObject * object, const char * name, uint64_t value)
References KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::AddProperty(), m_req, name, and value.
Referenced by DrmAtomicCommit(), InitDrm(), and SetScalingFilter().
DestroyDrm()
void CDRMAtomic::DestroyDrm () override virtual
Reimplemented from KODI::WINDOWING::GBM::CDRMUtils.
References KODI::WINDOWING::GBM::CDRMUtils::DestroyDrm().
DisplayHardwareScalingEnabled()
bool CDRMAtomic::DisplayHardwareScalingEnabled ()
References CServiceBroker::GetSettingsComponent().
DrmAtomicCommit()
void CDRMAtomic::DrmAtomicCommit (int fb_id, int flags, bool rendered, bool videoLayer) private
Todo:
: disabled until upstream kernel changes are merged
References AddProperty(), KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::Get(), KODI::WINDOWING::GBM::CDRMCrtc::GetCrtcId(), CServiceBroker::GetGUI(), CServiceBroker::GetLogging(), CLog::Log(), KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::LogAtomicDiff(), KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::LogAtomicRequest(), LOGERROR, LOGWINDOWING, m_active, m_atomicRequestQueue, KODI::WINDOWING::GBM::CDRMUtils::m_connector, KODI::WINDOWING::GBM::CDRMUtils::m_crtc, KODI::WINDOWING::GBM::CDRMUtils::m_fd, KODI::WINDOWING::GBM::CDRMUtils::m_gui_plane, KODI::WINDOWING::GBM::CDRMUtils::m_height, KODI::WINDOWING::GBM::CDRMUtils::m_inFenceFd, KODI::WINDOWING::GBM::CDRMUtils::m_mode, KODI::WINDOWING::GBM::CDRMUtils::m_orig_crtc, KODI::WINDOWING::GBM::CDRMUtils::m_outFenceFd, m_req, and KODI::WINDOWING::GBM::CDRMUtils::m_width.
Referenced by FlipPage().
FlipPage()
void CDRMAtomic::FlipPage (struct gbm_bo * bo, bool rendered, bool videoLayer, bool async) override virtual
Reimplemented from KODI::WINDOWING::GBM::CDRMUtils.
References DrmAtomicCommit(), KODI::WINDOWING::GBM::CDRMUtils::DrmFbGetFromBo(), KODI::WINDOWING::GBM::drm_fb::fb_id, KODI::WINDOWING::GBM::CDRMUtils::FourCCWithAlpha(), KODI::WINDOWING::GBM::CDRMUtils::FourCCWithoutAlpha(), KODI::WINDOWING::GBM::CDRMPlane::GetFormat(), CLog::Log(), LOGDEBUG, LOGERROR, KODI::WINDOWING::GBM::CDRMUtils::m_gui_plane, m_need_modeset, and KODI::WINDOWING::GBM::CDRMPlane::SetFormat().
InitDrm()
bool CDRMAtomic::InitDrm () override virtual
Todo:
: disabled until upstream kernel changes are merged
Reimplemented from KODI::WINDOWING::GBM::CDRMUtils.
References AddProperty(), KODI::WINDOWING::GBM::CDRMUtils::InitDrm(), CLog::Log(), LOGDEBUG, LOGERROR, m_atomicRequestQueue, KODI::WINDOWING::GBM::CDRMUtils::m_fd, KODI::WINDOWING::GBM::CDRMUtils::m_planes, m_req, and KODI::WINDOWING::GBM::CDRMUtils::OpenDrm().
SetActive()
bool CDRMAtomic::SetActive (bool active) override virtual
Reimplemented from KODI::WINDOWING::GBM::CDRMUtils.
References m_active, and m_need_modeset.
SetScalingFilter()
bool CDRMAtomic::SetScalingFilter (CDRMObject * object, const char * name, const char * type) private
References AddProperty(), KODI::WINDOWING::GBM::CDRMObject::GetPropertyValue(), KODI::WINDOWING::GBM::CDRMUtils::m_gui_plane, KODI::WINDOWING::GBM::CDRMUtils::m_height, KODI::WINDOWING::GBM::CDRMUtils::m_mode, KODI::WINDOWING::GBM::CDRMUtils::m_width, and name.
SetVideoMode()
bool CDRMAtomic::SetVideoMode (const RESOLUTION_INFO & res, struct gbm_bo * bo) override virtual
Reimplemented from KODI::WINDOWING::GBM::CDRMUtils.
References m_need_modeset.
Member Data Documentation
m_active
bool KODI::WINDOWING::GBM::CDRMAtomic::m_active = true private
Referenced by DrmAtomicCommit(), and SetActive().
m_atomicRequestQueue
std::deque<std::unique_ptr<CDRMAtomicRequest> > KODI::WINDOWING::GBM::CDRMAtomic::m_atomicRequestQueue private
Referenced by DrmAtomicCommit(), and InitDrm().
m_need_modeset
bool KODI::WINDOWING::GBM::CDRMAtomic::m_need_modeset private
Referenced by FlipPage(), SetActive(), and SetVideoMode().
m_req
CDRMAtomicRequest* KODI::WINDOWING::GBM::CDRMAtomic::m_req = nullptr private
Referenced by AddProperty(), DrmAtomicCommit(), and InitDrm().
The documentation for this class was generated from the following files:
DRMAtomic.h
DRMAtomic.cpp