Kodi Documentation: XFILE::CSourcesDirectory Class Reference
XFILE::CSourcesDirectory Class Reference
#include <SourcesDirectory.h>
Public Member Functions
CSourcesDirectory (void)
~CSourcesDirectory (void) override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool GetDirectory (const std::vector< CMediaSource > &sources, CFileItemList &items)
bool Exists (const CURL &url) override
Check for directory existence.
bool AllowAll () const override
Whether to allow all files/folders to be listed.
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool Create (const CURL &url)
Create the directory.
virtual bool Remove (const CURL &url)
Removes the directory.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Additional Inherited Members
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CSourcesDirectory()
CSourcesDirectory::CSourcesDirectory (void) default
~CSourcesDirectory()
CSourcesDirectory::~CSourcesDirectory (void) override default
Member Function Documentation
AllowAll()
bool XFILE::CSourcesDirectory::AllowAll () const inline override virtual
Whether to allow all files/folders to be listed.
Returns
Returns true if all files/folder should be listed.
Reimplemented from XFILE::IDirectory.
Exists()
bool CSourcesDirectory::Exists (const CURL & url) override virtual
Check for directory existence.
Parameters
url Directory to check.
Returns
Returns true, if directory exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
GetDirectory() [1/2]
bool CSourcesDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References GetDirectory(), CURL::GetFileName(), CMediaSourceSettings::GetInstance(), CServiceBroker::GetMediaManager(), CMediaManager::GetRemovableDrives(), CMediaSourceSettings::GetSources(), and URIUtils::RemoveSlashAtEnd().
Referenced by GetDirectory(), and XFILE::CVirtualDirectory::GetDirectory().
GetDirectory() [2/2]
bool CSourcesDirectory::GetDirectory (const std::vector< CMediaSource > & sources, CFileItemList & items)
References CFileItemList::Add(), CFileUtils::Exists(), CUtil::GetDVDDriveIcon(), CServiceBroker::GetGUI(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CGUIComponent::GetTextureManager(), CGUITextureManager::HasTexture(), CGUIListItem::ICON_OVERLAY_LOCKED, CGUIListItem::ICON_OVERLAY_NONE, KODI::MUSIC::IsCDDA(), KODI::MUSIC::IsMusicDb(), URIUtils::IsProtocol(), KODI::NETWORK::IsRemote(), LOCK_MODE_EVERYONE, LOCK_STATE_LOCKED, CMediaSource::m_iDriveType, CMediaSource::m_iHasLock, XFILE::IDirectory::m_profileManager, CMediaSource::m_strThumbnailImage, and CMediaSource::SOURCE_TYPE_OPTICAL_DISC.
The documentation for this class was generated from the following files:
SourcesDirectory.h
SourcesDirectory.cpp