Kodi Documentation: PVR::CGUIPVRRecordingsPlayActionProcessor Class Reference
PVR::CGUIPVRRecordingsPlayActionProcessor Class Reference
#include <PVRGUIRecordingsPlayActionProcessor.h>
Public Member Functions
CGUIPVRRecordingsPlayActionProcessor (const std::shared_ptr< CFileItem > &item)
Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
CVideoPlayActionProcessorBase (const std::shared_ptr< CFileItem > &item)
virtual ~CVideoPlayActionProcessorBase ()=default
bool ProcessDefaultAction ()
bool ProcessAction (Action action)
bool UserCancelled () const
Protected Member Functions
bool OnResumeSelected () override
bool OnPlaySelected () override
Protected Member Functions inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
virtual Action GetDefaultAction ()
virtual bool Process (Action action)
Private Member Functions
void Play ()
Additional Inherited Members
Static Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
static Action ChoosePlayOrResume (const CFileItem &item)
Protected Attributes inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
std::shared_ptr< CFileItem > m_item
bool m_userCancelled {false}
Constructor & Destructor Documentation
CGUIPVRRecordingsPlayActionProcessor()
PVR::CGUIPVRRecordingsPlayActionProcessor::CGUIPVRRecordingsPlayActionProcessor (const std::shared_ptr< CFileItem > & item) inline explicit
Member Function Documentation
OnPlaySelected()
bool PVR::CGUIPVRRecordingsPlayActionProcessor::OnPlaySelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase.
References Play().
OnResumeSelected()
bool PVR::CGUIPVRRecordingsPlayActionProcessor::OnResumeSelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase.
References KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::m_item, Play(), and STARTOFFSET_RESUME.
Play()
void PVR::CGUIPVRRecordingsPlayActionProcessor::Play () inline private
References PVR::CPVRManager::Get(), CServiceBroker::GetPVRManager(), and KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::m_item.
Referenced by OnPlaySelected(), and OnResumeSelected().
The documentation for this class was generated from the following file:
PVRGUIRecordingsPlayActionProcessor.h