Kodi Documentation: CViewModeSettings Class Reference
CViewModeSettings Class Reference
#include <ViewModeSettings.h>
Static Public Member Functions
static int GetNextQuickCycleViewMode (int viewMode)
static int GetViewModeStringIndex (int viewMode)
static void ViewModesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Private Member Functions
CViewModeSettings ()
~CViewModeSettings ()=default
Constructor & Destructor Documentation
CViewModeSettings()
CViewModeSettings::CViewModeSettings () private
~CViewModeSettings()
CViewModeSettings::~CViewModeSettings () private default
Member Function Documentation
GetNextQuickCycleViewMode()
int CViewModeSettings::GetNextQuickCycleViewMode (int viewMode) static
Gets the next view mode for quick cycling through the modes
Parameters
viewMode The current view mode
Returns
The next view mode
References GetViewModeIndex(), NUMBER_OF_VIEW_MODES, ViewModeProperties::viewMode, ViewModeNormal, and viewModes.
Referenced by CGUIWindowFullScreen::OnAction().
GetViewModeStringIndex()
int CViewModeSettings::GetViewModeStringIndex (int viewMode) static
Gets the string index for the view mode
Parameters
viewMode The current view mode
Returns
The string index
References GetViewModeIndex(), and viewModes.
Referenced by CGUIWindowFullScreen::FrameMove().
ViewModesFiller()
void CViewModeSettings::ViewModesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
Fills the list with all visible view modes
References g_localizeStrings, CLocalizeStrings::Get(), and viewModes.
Referenced by CGUIDialogVideoSettings::InitializeSettings().
The documentation for this class was generated from the following files:
ViewModeSettings.h
ViewModeSettings.cpp