Kodi Documentation: XFILE::CBlurayDirectory Class Reference
XFILE::CBlurayDirectory Class Reference
#include <BlurayDirectory.h>
Public Member Functions
CBlurayDirectory ()=default
~CBlurayDirectory () override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool InitializeBluray (const std::string &root)
std::string GetBlurayTitle ()
std::string GetBlurayID ()
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool Create (const CURL &url)
Create the directory.
virtual bool Exists (const CURL &url)
Check for directory existence.
virtual bool Remove (const CURL &url)
Removes the directory.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual bool AllowAll () const
Whether to allow all files/folders to be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Private Types
enum class DiscInfo { TITLE , ID }
Private Member Functions
void Dispose ()
std::string GetDiscInfoString (DiscInfo info)
void GetRoot (CFileItemList &items)
void GetTitles (bool main, CFileItemList &items)
std::vector< BLURAY_TITLE_INFO * > GetUserPlaylists ()
std::shared_ptr< CFileItem > GetTitle (const BLURAY_TITLE_INFO *title, const std::string &label)
CURL GetUnderlyingCURL (const CURL &url)
std::string HexToString (const uint8_t *buf, int count)
Private Attributes
CURL m_url
BLURAY * m_bd = nullptr
bool m_blurayInitialized = false
Additional Inherited Members
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Member Enumeration Documentation
DiscInfo
enum class XFILE::CBlurayDirectory::DiscInfo strong private
Enumerator
TITLE
ID
Constructor & Destructor Documentation
CBlurayDirectory()
XFILE::CBlurayDirectory::CBlurayDirectory () default
~CBlurayDirectory()
XFILE::CBlurayDirectory::~CBlurayDirectory () override
References Dispose().
Member Function Documentation
Dispose()
void XFILE::CBlurayDirectory::Dispose () private
References m_bd.
Referenced by GetDirectory(), and ~CBlurayDirectory().
GetBlurayID()
std::string XFILE::CBlurayDirectory::GetBlurayID ()
References GetDiscInfoString(), and ID.
Referenced by UTILS::DISCS::ProbeBlurayDiscInfo().
GetBlurayTitle()
std::string XFILE::CBlurayDirectory::GetBlurayTitle ()
References GetDiscInfoString(), and TITLE.
Referenced by UTILS::DISCS::ProbeBlurayDiscInfo().
GetDirectory()
bool XFILE::CBlurayDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References CFileItemList::AddSortMethod(), Dispose(), XFILE::CDirectory::CHints::flags, XFILE::CDirectory::GetDirectory(), CURL::GetFileName(), CURL::GetHostName(), GetRoot(), GetTitles(), GetUnderlyingCURL(), InitializeBluray(), XFILE::IDirectory::m_flags, m_url, URIUtils::RemoveSlashAtEnd(), root, SortBySize, and SortByTrackNumber.
GetDiscInfoString()
std::string XFILE::CBlurayDirectory::GetDiscInfoString (DiscInfo info) private
References HexToString(), ID, id, m_bd, m_blurayInitialized, and TITLE.
Referenced by GetBlurayID(), and GetBlurayTitle().
GetRoot()
void XFILE::CBlurayDirectory::GetRoot (CFileItemList & items) private
References CFileItemList::Add(), URIUtils::AddFileToFolder(), g_localizeStrings, CURL::Get(), CLocalizeStrings::Get(), CURL::GetFileName(), GetTitles(), CLog::Log(), LOGDEBUG, m_bd, m_url, and CURL::SetFileName().
Referenced by GetDirectory().
GetTitle()
std::shared_ptr< CFileItem > XFILE::CBlurayDirectory::GetTitle (const BLURAY_TITLE_INFO * title, const std::string & label) private
References g_localizeStrings, CURL::Get(), CLocalizeStrings::Get(), label, m_url, and CURL::SetFileName().
Referenced by GetTitles().
GetTitles()
void XFILE::CBlurayDirectory::GetTitles (bool main, CFileItemList & items) private
References CFileItemList::Add(), g_localizeStrings, CLocalizeStrings::Get(), GetTitle(), GetUserPlaylists(), CLog::Log(), LOGDEBUG, m_bd, main(), MAIN_TITLE_LENGTH_PERCENT, and t.
Referenced by GetDirectory(), and GetRoot().
GetUnderlyingCURL()
CURL XFILE::CBlurayDirectory::GetUnderlyingCURL (const CURL & url) private
References CURL, CURL::GetFileName(), CURL::GetHostName(), and CURL::IsProtocol().
Referenced by GetDirectory().
GetUserPlaylists()
std::vector< BLURAY_TITLE_INFO * > XFILE::CBlurayDirectory::GetUserPlaylists () private
References URIUtils::AddFileToFolder(), CURL::GetHostName(), CRegExp::GetMatch(), int64_t(), CLog::Log(), LOGDEBUG, m_bd, m_url, playlist, CRegExp::RegComp(), CRegExp::RegFind(), root, and t.
Referenced by GetTitles().
HexToString()
std::string XFILE::CBlurayDirectory::HexToString (const uint8_t * buf, int count) private
Referenced by GetDiscInfoString().
InitializeBluray()
bool XFILE::CBlurayDirectory::InitializeBluray (const std::string & root)
References CBlurayCallback::bluray_logger(), CLangCodeExpander::ConvertToISO6392T(), CBlurayCallback::dir_open(), CBlurayCallback::file_open(), g_LangCodeExpander, g_langInfo, CLog::Log(), LOGERROR, m_bd, m_blurayInitialized, and root.
Referenced by GetDirectory(), and UTILS::DISCS::ProbeBlurayDiscInfo().
Member Data Documentation
m_bd
BLURAY* XFILE::CBlurayDirectory::m_bd = nullptr private
Referenced by Dispose(), GetDiscInfoString(), GetRoot(), GetTitles(), GetUserPlaylists(), and InitializeBluray().
m_blurayInitialized
bool XFILE::CBlurayDirectory::m_blurayInitialized = false private
Referenced by GetDiscInfoString(), and InitializeBluray().
m_url
CURL XFILE::CBlurayDirectory::m_url private
Referenced by GetDirectory(), GetRoot(), GetTitle(), and GetUserPlaylists().
The documentation for this class was generated from the following files:
BlurayDirectory.h
BlurayDirectory.cpp