Kodi Documentation: InfoTagVideo
InfoTagVideo
Python » Library - xbmc
Kodi's video info tag class.
Classes
class XBMCAddon::xbmc::InfoTagVideo
Functions
SActorInfo XBMCAddon::xbmc::Actor::ToActorInfo () const
CStreamDetailVideo * XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo () const
CStreamDetailAudio * XBMCAddon::xbmc::AudioStreamDetail::ToStreamDetailAudio () const
CStreamDetailSubtitle * XBMCAddon::xbmc::SubtitleStreamDetail::ToStreamDetailSubtitle () const
XBMCAddon::xbmc::InfoTagVideo::InfoTagVideo (const CVideoInfoTag *tag)
XBMCAddon::xbmc::InfoTagVideo::InfoTagVideo (CVideoInfoTag *tag, bool offscreen=false)
XBMCAddon::xbmc::InfoTagVideo::InfoTagVideo (...)
Function: xbmc.InfoTagVideo([offscreen])
Create a video info tag.
XBMCAddon::xbmc::InfoTagVideo::~InfoTagVideo () override
XBMCAddon::xbmc::InfoTagVideo::getDbId ()
Function: getDbId()
Get identification number of tag in database
XBMCAddon::xbmc::InfoTagVideo::getDirector ()
Function: getDirector()
Get film director who has made the film (if present).
XBMCAddon::xbmc::InfoTagVideo::getDirectors ()
Function: getDirectors()
Get a list of film directors who have made the film (if present).
XBMCAddon::xbmc::InfoTagVideo::getWritingCredits ()
Function: getWritingCredits()
Get the writing credits if present from video info tag.
XBMCAddon::xbmc::InfoTagVideo::getWriters ()
Function: getWriters()
Get the list of writers (if present) from video info tag.
XBMCAddon::xbmc::InfoTagVideo::getGenre ()
Function: getGenre()
To get the Video Genre if available.
XBMCAddon::xbmc::InfoTagVideo::getGenres ()
Function: getGenres()
Get the list of Video Genres if available.
XBMCAddon::xbmc::InfoTagVideo::getTagLine ()
Function: getTagLine()
Get video tag line if available.
XBMCAddon::xbmc::InfoTagVideo::getPlotOutline ()
Function: getPlotOutline()
Get the outline plot of the video if present.
XBMCAddon::xbmc::InfoTagVideo::getPlot ()
Function: getPlot()
Get the plot of the video if present.
XBMCAddon::xbmc::InfoTagVideo::getPictureURL ()
Function: getPictureURL()
Get a picture URL of the video to show as screenshot.
XBMCAddon::xbmc::InfoTagVideo::getTitle ()
Function: getTitle()
Get the video title.
XBMCAddon::xbmc::InfoTagVideo::getTVShowTitle ()
Function: getTVShowTitle()
Get the video TV show title.
XBMCAddon::xbmc::InfoTagVideo::getMediaType ()
Function: getMediaType()
Get the media type of the video.
XBMCAddon::xbmc::InfoTagVideo::getVotes ()
Function: getVotes()
Get the video votes if available from video info tag.
XBMCAddon::xbmc::InfoTagVideo::getVotesAsInt (type)
Function: getVotesAsInt([type])
Get the votes of the rating (if available) as an integer.
XBMCAddon::xbmc::InfoTagVideo::getCast ()
Function: getCast()
To get the cast of the video when available.
XBMCAddon::xbmc::InfoTagVideo::getActors ()
Function: getActors()
Get the cast of the video if available.
XBMCAddon::xbmc::InfoTagVideo::getFile ()
Function: getFile()
To get the video file name.
XBMCAddon::xbmc::InfoTagVideo::getPath ()
Function: getPath()
To get the path where the video is stored.
XBMCAddon::xbmc::InfoTagVideo::getFilenameAndPath ()
Function: getFilenameAndPath()
To get the full path with filename where the video is stored.
XBMCAddon::xbmc::InfoTagVideo::getIMDBNumber ()
Function: getIMDBNumber()
To get the IMDb number of the video (if present).
XBMCAddon::xbmc::InfoTagVideo::getSeason ()
Function: getSeason()
To get season number of a series
XBMCAddon::xbmc::InfoTagVideo::getEpisode ()
Function: getEpisode()
To get episode number of a series
XBMCAddon::xbmc::InfoTagVideo::getYear ()
Function: getYear()
Get production year of video if present.
XBMCAddon::xbmc::InfoTagVideo::getRating (type)
Function: getRating([type])
Get the video rating if present as float (double where supported).
XBMCAddon::xbmc::InfoTagVideo::getUserRating ()
Function: getUserRating()
Get the user rating if present as integer.
XBMCAddon::xbmc::InfoTagVideo::getPlayCount ()
Function: getPlayCount()
To get the number of plays of the video.
XBMCAddon::xbmc::InfoTagVideo::getLastPlayed ()
Function: getLastPlayed()
Get the last played date / time as string.
XBMCAddon::xbmc::InfoTagVideo::getLastPlayedAsW3C ()
Function: getLastPlayedAsW3C()
Get last played datetime as string in W3C format (YYYY-MM-DDThh:mm:ssTZD).
XBMCAddon::xbmc::InfoTagVideo::getOriginalTitle ()
Function: getOriginalTitle()
To get the original title of the video.
XBMCAddon::xbmc::InfoTagVideo::getPremiered ()
Function: getPremiered()
To get premiered date of the video, if available.
XBMCAddon::xbmc::InfoTagVideo::getPremieredAsW3C ()
Function: getPremieredAsW3C()
Get premiered date as string in W3C format (YYYY-MM-DD).
XBMCAddon::xbmc::InfoTagVideo::getFirstAired ()
Function: getFirstAired()
Returns first aired date as string from info tag.
XBMCAddon::xbmc::InfoTagVideo::getFirstAiredAsW3C ()
Function: getFirstAiredAsW3C()
Get first aired date as string in W3C format (YYYY-MM-DD).
XBMCAddon::xbmc::InfoTagVideo::getTrailer ()
Function: getTrailer()
To get the path where the trailer is stored.
XBMCAddon::xbmc::InfoTagVideo::getArtist ()
Function: getArtist()
To get the artist name (for musicvideos)
XBMCAddon::xbmc::InfoTagVideo::getAlbum ()
Function: getAlbum()
To get the album name (for musicvideos)
XBMCAddon::xbmc::InfoTagVideo::getTrack ()
Function: getTrack()
To get the track number (for musicvideos)
XBMCAddon::xbmc::InfoTagVideo::getDuration ()
Function: getDuration()
To get the duration
XBMCAddon::xbmc::InfoTagVideo::getResumeTime (...)
Function: getResumeTime())
Gets the resume time of the video item.
XBMCAddon::xbmc::InfoTagVideo::getResumeTimeTotal (...)
Function: getResumeTimeTotal())
Gets the total duration stored with the resume time of the video item.
XBMCAddon::xbmc::InfoTagVideo::getUniqueID (key)
Function: getUniqueID(key)
Get the unique ID of the given key. A unique ID is an identifier used by a (online) video database used to identify a video in its database.
XBMCAddon::xbmc::InfoTagVideo::setUniqueID (...)
Function: setUniqueID(uniqueid, [type], [isdefault])
Set the given unique ID. A unique ID is an identifier used by a (online) video database used to identify a video in its database.
XBMCAddon::xbmc::InfoTagVideo::setUniqueIDs (...)
Function: setUniqueIDs(values, defaultuniqueid)
Set the given unique IDs. A unique ID is an identifier used by a (online) video database used to identify a video in its database.
XBMCAddon::xbmc::InfoTagVideo::setDbId (...)
Function: setDbId(dbid)
Set the database identifier of the video item.
XBMCAddon::xbmc::InfoTagVideo::setYear (...)
Function: setYear(year)
Set the year of the video item.
XBMCAddon::xbmc::InfoTagVideo::setEpisode (...)
Function: setEpisode(episode)
Set the episode number of the episode.
XBMCAddon::xbmc::InfoTagVideo::setSeason (...)
Function: setSeason(season)
Set the season number of the video item.
XBMCAddon::xbmc::InfoTagVideo::setSortEpisode (...)
Function: setSortEpisode(sortepisode)
Set the episode sort number of the episode.
XBMCAddon::xbmc::InfoTagVideo::setSortSeason (...)
Function: setSortSeason(sortseason)
Set the season sort number of the season.
XBMCAddon::xbmc::InfoTagVideo::setEpisodeGuide (...)
Function: setEpisodeGuide(episodeguide)
Set the episode guide of the video item.
XBMCAddon::xbmc::InfoTagVideo::setTop250 (...)
Function: setTop250(top250)
Set the top 250 number of the video item.
XBMCAddon::xbmc::InfoTagVideo::setSetId (...)
Function: setSetId(setid)
Set the movie set identifier of the video item.
XBMCAddon::xbmc::InfoTagVideo::setTrackNumber (...)
Function: setTrackNumber(tracknumber)
Set the track number of the music video item.
XBMCAddon::xbmc::InfoTagVideo::setRating (...)
Function: setRating(rating, [votes], [type], [isdefault])
Set the rating of the video item.
XBMCAddon::xbmc::InfoTagVideo::setRatings (...)
Function: setRatings(ratings, [defaultrating])
Set the ratings of the video item.
XBMCAddon::xbmc::InfoTagVideo::setUserRating (...)
Function: setUserRating(userrating)
Set the user rating of the video item.
XBMCAddon::xbmc::InfoTagVideo::setPlaycount (...)
Function: setPlaycount(playcount)
Set the playcount of the video item.
XBMCAddon::xbmc::InfoTagVideo::setMpaa (...)
Function: setMpaa(mpaa)
Set the MPAA rating of the video item.
XBMCAddon::xbmc::InfoTagVideo::setPlot (...)
Function: setPlot(plot)
Set the plot of the video item.
XBMCAddon::xbmc::InfoTagVideo::setPlotOutline (...)
Function: setPlotOutline(plotoutline)
Set the plot outline of the video item.
XBMCAddon::xbmc::InfoTagVideo::setTitle (...)
Function: setTitle(title)
Set the title of the video item.
XBMCAddon::xbmc::InfoTagVideo::setOriginalTitle (...)
Function: setOriginalTitle(originaltitle)
Set the original title of the video item.
XBMCAddon::xbmc::InfoTagVideo::setSortTitle (...)
Function: setSortTitle(sorttitle)
Set the sort title of the video item.
XBMCAddon::xbmc::InfoTagVideo::setTagLine (...)
Function: setTagLine(tagline)
Set the tagline of the video item.
XBMCAddon::xbmc::InfoTagVideo::setTvShowTitle (...)
Function: setTvShowTitle(tvshowtitle)
Set the TV show title of the video item.
XBMCAddon::xbmc::InfoTagVideo::setTvShowStatus (...)
Function: setTvShowStatus(tvshowstatus)
Set the TV show status of the video item.
XBMCAddon::xbmc::InfoTagVideo::setGenres (...)
Function: setGenres(genre)
Set the genres of the video item.
XBMCAddon::xbmc::InfoTagVideo::setCountries (...)
Function: setCountries(countries)
Set the countries of the video item.
XBMCAddon::xbmc::InfoTagVideo::setDirectors (...)
Function: setDirectors(directors)
Set the directors of the video item.
XBMCAddon::xbmc::InfoTagVideo::setStudios (...)
Function: setStudios(studios)
Set the studios of the video item.
XBMCAddon::xbmc::InfoTagVideo::setWriters (...)
Function: setWriters(writers)
Set the writers of the video item.
XBMCAddon::xbmc::InfoTagVideo::setDuration (...)
Function: setDuration(duration)
Set the duration of the video item.
XBMCAddon::xbmc::InfoTagVideo::setPremiered (...)
Function: setPremiered(premiered)
Set the premiere date of the video item.
XBMCAddon::xbmc::InfoTagVideo::setSet (...)
Function: setSet(set)
Set the movie set (name) of the video item.
XBMCAddon::xbmc::InfoTagVideo::setSetOverview (...)
Function: setSetOverview(setoverview)
Set the movie set overview of the video item.
XBMCAddon::xbmc::InfoTagVideo::setTags (...)
Function: setTags(tags)
Set the tags of the video item.
XBMCAddon::xbmc::InfoTagVideo::setVideoAssetTitle (...)
Function: setVideoAssetTitle(videoAssetTitle)
Set the video asset title of the item.
XBMCAddon::xbmc::InfoTagVideo::setProductionCode (...)
Function: setProductionCode(const String& productioncode)
Set the production code of the video item.
XBMCAddon::xbmc::InfoTagVideo::setFirstAired (...)
Function: setFirstAired(firstaired)
Set the first aired date of the video item.
XBMCAddon::xbmc::InfoTagVideo::setLastPlayed (...)
Function: setLastPlayed(lastplayed)
Set the last played date of the video item.
XBMCAddon::xbmc::InfoTagVideo::setAlbum (...)
Function: setAlbum(album)
Set the album of the video item.
XBMCAddon::xbmc::InfoTagVideo::setVotes (...)
Function: setVotes(votes)
Set the number of votes of the video item.
XBMCAddon::xbmc::InfoTagVideo::setTrailer (...)
Function: setTrailer(trailer)
Set the trailer of the video item.
XBMCAddon::xbmc::InfoTagVideo::setPath (...)
Function: setPath(path)
Set the path of the video item.
XBMCAddon::xbmc::InfoTagVideo::setFilenameAndPath (...)
Function: setFilenameAndPath(filenameandpath)
Set the filename and path of the video item.
XBMCAddon::xbmc::InfoTagVideo::setIMDBNumber (...)
Function: setIMDBNumber(imdbnumber)
Set the IMDb number of the video item.
XBMCAddon::xbmc::InfoTagVideo::setDateAdded (...)
Function: setDateAdded(dateadded)
Set the date added of the video item.
XBMCAddon::xbmc::InfoTagVideo::setMediaType (...)
Function: setMediaType(mediatype)
Set the media type of the video item.
XBMCAddon::xbmc::InfoTagVideo::setShowLinks (...)
Function: setShowLinks(showlinks)
Set the TV show links of the movie.
XBMCAddon::xbmc::InfoTagVideo::setArtists (...)
Function: setArtists(artists)
Set the artists of the music video item.
XBMCAddon::xbmc::InfoTagVideo::setCast (...)
Function: setCast(actors)
Set the cast / actors of the video item.
XBMCAddon::xbmc::InfoTagVideo::setResumePoint (...)
Function: setResumePoint(time, [totaltime])
Set the resume point of the video item.
XBMCAddon::xbmc::InfoTagVideo::addSeason (...)
Function: addSeason(number, [name])
Add a season with name. It needs at least the season number.
XBMCAddon::xbmc::InfoTagVideo::addSeasons (...)
Function: addSeasons(namedseasons)
Add named seasons to the TV show.
XBMCAddon::xbmc::InfoTagVideo::addVideoStream (...)
Function: addVideoStream(stream)
Add a video stream to the video item.
XBMCAddon::xbmc::InfoTagVideo::addAudioStream (...)
Function: addAudioStream(stream)
Add an audio stream to the video item.
XBMCAddon::xbmc::InfoTagVideo::addSubtitleStream (...)
Function: addSubtitleStream(stream)
Add a subtitle stream to the video item.
XBMCAddon::xbmc::InfoTagVideo::addAvailableArtwork (...)
Function: addAvailableArtwork(images)
Add an image to available artworks (needed for video scrapers)
Variables
String XBMCAddon::xbmc::Actor::m_name
String XBMCAddon::xbmc::Actor::m_role
int XBMCAddon::xbmc::Actor::m_order
String XBMCAddon::xbmc::Actor::m_thumbnail
int XBMCAddon::xbmc::VideoStreamDetail::m_width
int XBMCAddon::xbmc::VideoStreamDetail::m_height
float XBMCAddon::xbmc::VideoStreamDetail::m_aspect
int XBMCAddon::xbmc::VideoStreamDetail::m_duration
String XBMCAddon::xbmc::VideoStreamDetail::m_codec
String XBMCAddon::xbmc::VideoStreamDetail::m_stereoMode
String XBMCAddon::xbmc::VideoStreamDetail::m_language
String XBMCAddon::xbmc::VideoStreamDetail::m_hdrType
int XBMCAddon::xbmc::AudioStreamDetail::m_channels
String XBMCAddon::xbmc::AudioStreamDetail::m_codec
String XBMCAddon::xbmc::AudioStreamDetail::m_language
String XBMCAddon::xbmc::SubtitleStreamDetail::m_language
CVideoInfoTag * XBMCAddon::xbmc::InfoTagVideo::infoTag
bool XBMCAddon::xbmc::InfoTagVideo::offscreen
bool XBMCAddon::xbmc::InfoTagVideo::owned
Detailed Description
Kodi's video info tag class.
Class: xbmc.InfoTagVideo([offscreen])
Access and / or modify the video metadata of a ListItem.
Example:
...
tag = xbmc.Player().getVideoInfoTag()
title = tag.getTitle()
file  = tag.getFile()
...
Function Documentation
addAudioStream()
void XBMCAddon::xbmc::InfoTagVideo::addAudioStream (...)
Function: addAudioStream(stream)
Add an audio stream to the video item.
Parameters
stream AudioStreamDetail - Audio stream.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::addStreamRaw(), XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::AudioStreamDetail::ToStreamDetailAudio().
addAvailableArtwork()
void XBMCAddon::xbmc::InfoTagVideo::addAvailableArtwork (...)
Function: addAvailableArtwork(images)
Add an image to available artworks (needed for video scrapers)
Parameters
url string - image path url
arttype string - image type
preview [opt] string - image preview path url
referrer [opt] string - referrer url
cache [opt] string - filename in cache
post [opt] bool - use post to retrieve the image (default false)
isgz [opt] bool - use gzip to retrieve the image (default false)
season [opt] integer - number of season in case of season thumb
v20 Python API changes:
New function added.
Example:
...
infotagvideo.addAvailableArtwork(path_to_image_1, "thumb")
...
References XBMCAddon::xbmc::InfoTagVideo::addAvailableArtworkRaw(), XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, and XBMCAddon::xbmc::InfoTagVideo::offscreen.
addSeason()
void XBMCAddon::xbmc::InfoTagVideo::addSeason (...)
Function: addSeason(number, [name])
Add a season with name. It needs at least the season number.
Parameters
number int - the number of the season.
name string - the name of the season. Default "".
v20 Python API changes:
New function added.
Example:
...
# addSeason(number, name))
infotagvideo.addSeason(1, "Murder House")
...
References XBMCAddon::xbmc::InfoTagVideo::addSeasonRaw(), XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, name, and XBMCAddon::xbmc::InfoTagVideo::offscreen.
addSeasons()
void XBMCAddon::xbmc::InfoTagVideo::addSeasons (...)
Function: addSeasons(namedseasons)
Add named seasons to the TV show.
Parameters
namedseasons list - [ (season, name) ].
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::addSeasonsRaw(), XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, and XBMCAddon::xbmc::InfoTagVideo::offscreen.
addSubtitleStream()
void XBMCAddon::xbmc::InfoTagVideo::addSubtitleStream (...)
Function: addSubtitleStream(stream)
Add a subtitle stream to the video item.
Parameters
stream SubtitleStreamDetail - Subtitle stream.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::addStreamRaw(), XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::SubtitleStreamDetail::ToStreamDetailSubtitle().
addVideoStream()
void XBMCAddon::xbmc::InfoTagVideo::addVideoStream (...)
Function: addVideoStream(stream)
Add a video stream to the video item.
Parameters
stream VideoStreamDetail - Video stream.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::addStreamRaw(), XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo().
getActors()
std::vector< Actor * > XBMCAddon::xbmc::InfoTagVideo::getActors ()
Function: getActors()
Get the cast of the video if available.
Returns
[list] List of actors
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_cast.
getAlbum()
String XBMCAddon::xbmc::InfoTagVideo::getAlbum ()
Function: getAlbum()
To get the album name (for musicvideos)
Returns
[string] Album name
v18 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strAlbum.
getArtist()
std::vector< std::string > XBMCAddon::xbmc::InfoTagVideo::getArtist ()
Function: getArtist()
To get the artist name (for musicvideos)
Returns
[std::vector<std::string>] Artist name
v18 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_artist.
getCast()
String XBMCAddon::xbmc::InfoTagVideo::getCast ()
Function: getCast()
To get the cast of the video when available.
Returns
[string] Video casts
v20 Python API changes:
Deprecated. Use getActors() instead.
References CVideoInfoTag::GetCast(), and XBMCAddon::xbmc::InfoTagVideo::infoTag.
getDbId()
int XBMCAddon::xbmc::InfoTagVideo::getDbId ()
Function: getDbId()
Get identification number of tag in database
Returns
[integer] database id
v17 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_iDbId.
getDirector()
String XBMCAddon::xbmc::InfoTagVideo::getDirector ()
Function: getDirector()
Get film director who has made the film (if present).
Returns
[string] Film director name.
v20 Python API changes:
Deprecated. Use getDirectors() instead.
References CServiceBroker::GetSettingsComponent(), XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_director.
getDirectors()
std::vector< String > XBMCAddon::xbmc::InfoTagVideo::getDirectors ()
Function: getDirectors()
Get a list of film directors who have made the film (if present).
Returns
[list] List of film director names.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_director.
getDuration()
unsigned int XBMCAddon::xbmc::InfoTagVideo::getDuration ()
Function: getDuration()
To get the duration
Returns
[unsigned int] Duration
v18 Python API changes:
New function added.
References CVideoInfoTag::GetDuration(), and XBMCAddon::xbmc::InfoTagVideo::infoTag.
getEpisode()
int XBMCAddon::xbmc::InfoTagVideo::getEpisode ()
Function: getEpisode()
To get episode number of a series
Returns
[integer] episode number
v17 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_iEpisode.
getFile()
String XBMCAddon::xbmc::InfoTagVideo::getFile ()
Function: getFile()
To get the video file name.
Returns
[string] File name
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strFile.
getFilenameAndPath()
String XBMCAddon::xbmc::InfoTagVideo::getFilenameAndPath ()
Function: getFilenameAndPath()
To get the full path with filename where the video is stored.
Returns
[string] File name and Path
v19 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strFileNameAndPath.
getFirstAired()
String XBMCAddon::xbmc::InfoTagVideo::getFirstAired ()
Function: getFirstAired()
Returns first aired date as string from info tag.
Returns
[string] First aired date
v20 Python API changes:
Deprecated. Use getFirstAiredAsW3C() instead.
References CDateTime::GetAsLocalizedDate(), XBMCAddon::xbmc::InfoTagVideo::infoTag, CLog::Log(), LOGWARNING, and CVideoInfoTag::m_firstAired.
getFirstAiredAsW3C()
String XBMCAddon::xbmc::InfoTagVideo::getFirstAiredAsW3C ()
Function: getFirstAiredAsW3C()
Get first aired date as string in W3C format (YYYY-MM-DD).
Returns
[string] First aired date (W3C)
v20 Python API changes:
New function added.
References CDateTime::GetAsW3CDate(), XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_firstAired.
getGenre()
String XBMCAddon::xbmc::InfoTagVideo::getGenre ()
Function: getGenre()
To get the Video Genre if available.
Returns
[string] Genre name
v20 Python API changes:
Deprecated. Use getGenres() instead.
References CServiceBroker::GetSettingsComponent(), XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_genre.
getGenres()
std::vector< String > XBMCAddon::xbmc::InfoTagVideo::getGenres ()
Function: getGenres()
Get the list of Video Genres if available.
Returns
[list] List of genres
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_genre.
getIMDBNumber()
String XBMCAddon::xbmc::InfoTagVideo::getIMDBNumber ()
Function: getIMDBNumber()
To get the IMDb number of the video (if present).
Returns
[string] IMDb number
References CVideoInfoTag::GetUniqueID(), and XBMCAddon::xbmc::InfoTagVideo::infoTag.
getLastPlayed()
String XBMCAddon::xbmc::InfoTagVideo::getLastPlayed ()
Function: getLastPlayed()
Get the last played date / time as string.
Returns
[string] Last played date / time
v20 Python API changes:
Deprecated. Use getLastPlayedAsW3C() instead.
References CDateTime::GetAsLocalizedDateTime(), XBMCAddon::xbmc::InfoTagVideo::infoTag, CLog::Log(), LOGWARNING, and CVideoInfoTag::m_lastPlayed.
getLastPlayedAsW3C()
String XBMCAddon::xbmc::InfoTagVideo::getLastPlayedAsW3C ()
Function: getLastPlayedAsW3C()
Get last played datetime as string in W3C format (YYYY-MM-DDThh:mm:ssTZD).
Returns
[string] Last played datetime (W3C)
v20 Python API changes:
New function added.
References CDateTime::GetAsW3CDateTime(), XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_lastPlayed.
getMediaType()
String XBMCAddon::xbmc::InfoTagVideo::getMediaType ()
Function: getMediaType()
Get the media type of the video.
Returns
[string] media type
Available strings about media type for video:
String Description
video For normal video
set For a selection of video
musicvideo To define it as music video
movie To define it as normal movie
tvshow If this is it defined as tvshow
season The type is used as a series season
episode The type is used as a series episode
v17 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_type.
getOriginalTitle()
String XBMCAddon::xbmc::InfoTagVideo::getOriginalTitle ()
Function: getOriginalTitle()
To get the original title of the video.
Returns
[string] Original title
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strOriginalTitle.
getPath()
String XBMCAddon::xbmc::InfoTagVideo::getPath ()
Function: getPath()
To get the path where the video is stored.
Returns
[string] Path
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strPath.
getPictureURL()
String XBMCAddon::xbmc::InfoTagVideo::getPictureURL ()
Function: getPictureURL()
Get a picture URL of the video to show as screenshot.
Returns
[string] Picture URL
References CScraperUrl::GetFirstThumbUrl(), XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, CVideoInfoTag::m_strPictureURL, XBMCAddon::xbmc::InfoTagVideo::offscreen, and CScraperUrl::Parse().
getPlayCount()
int XBMCAddon::xbmc::InfoTagVideo::getPlayCount ()
Function: getPlayCount()
To get the number of plays of the video.
Returns
[integer] Play Count
References CVideoInfoTag::GetPlayCount(), and XBMCAddon::xbmc::InfoTagVideo::infoTag.
getPlot()
String XBMCAddon::xbmc::InfoTagVideo::getPlot ()
Function: getPlot()
Get the plot of the video if present.
Returns
[string] Plot
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strPlot.
getPlotOutline()
String XBMCAddon::xbmc::InfoTagVideo::getPlotOutline ()
Function: getPlotOutline()
Get the outline plot of the video if present.
Returns
[string] Outline plot
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strPlotOutline.
getPremiered()
String XBMCAddon::xbmc::InfoTagVideo::getPremiered ()
Function: getPremiered()
To get premiered date of the video, if available.
Returns
[string]
v20 Python API changes:
Deprecated. Use getPremieredAsW3C() instead.
References CDateTime::GetAsLocalizedDate(), CVideoInfoTag::GetPremiered(), XBMCAddon::xbmc::InfoTagVideo::infoTag, CLog::Log(), and LOGWARNING.
getPremieredAsW3C()
String XBMCAddon::xbmc::InfoTagVideo::getPremieredAsW3C ()
Function: getPremieredAsW3C()
Get premiered date as string in W3C format (YYYY-MM-DD).
Returns
[string] Premiered date (W3C)
v20 Python API changes:
New function added.
References CDateTime::GetAsW3CDate(), CVideoInfoTag::GetPremiered(), and XBMCAddon::xbmc::InfoTagVideo::infoTag.
getRating()
double XBMCAddon::xbmc::InfoTagVideo::getRating (type)
Function: getRating([type])
Get the video rating if present as float (double where supported).
Parameters
type [opt] string - the type of the rating.
Some rating type values (any string possible):
Label Type
imdb string - type name
tvdb string - type name
tmdb string - type name
anidb string - type name
Returns
[float] The rating of the video
v20 Python API changes:
Optional type parameter added.
References CVideoInfoTag::GetRating(), XBMCAddon::xbmc::InfoTagVideo::infoTag, and CRating::rating.
getResumeTime()
double XBMCAddon::xbmc::InfoTagVideo::getResumeTime (...)
Function: getResumeTime())
Gets the resume time of the video item.
Returns
[double] Resume time
v20 Python API changes:
New function added.
References CVideoInfoTag::GetResumePoint(), XBMCAddon::xbmc::InfoTagVideo::infoTag, and CBookmark::timeInSeconds.
getResumeTimeTotal()
double XBMCAddon::xbmc::InfoTagVideo::getResumeTimeTotal (...)
Function: getResumeTimeTotal())
Gets the total duration stored with the resume time of the video item.
Returns
[double] Total duration stored with the resume time
v20 Python API changes:
New function added.
References CVideoInfoTag::GetResumePoint(), XBMCAddon::xbmc::InfoTagVideo::infoTag, and CBookmark::totalTimeInSeconds.
getSeason()
int XBMCAddon::xbmc::InfoTagVideo::getSeason ()
Function: getSeason()
To get season number of a series
Returns
[integer] season number
v17 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_iSeason.
getTagLine()
String XBMCAddon::xbmc::InfoTagVideo::getTagLine ()
Function: getTagLine()
Get video tag line if available.
Returns
[string] Video tag line
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strTagLine.
getTitle()
String XBMCAddon::xbmc::InfoTagVideo::getTitle ()
Function: getTitle()
Get the video title.
Returns
[string] Video title
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strTitle.
getTrack()
int XBMCAddon::xbmc::InfoTagVideo::getTrack ()
Function: getTrack()
To get the track number (for musicvideos)
Returns
[int] Track number
v18 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_iTrack.
getTrailer()
String XBMCAddon::xbmc::InfoTagVideo::getTrailer ()
Function: getTrailer()
To get the path where the trailer is stored.
Returns
[string] Trailer path
v17 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strTrailer.
getTVShowTitle()
String XBMCAddon::xbmc::InfoTagVideo::getTVShowTitle ()
Function: getTVShowTitle()
Get the video TV show title.
Returns
[string] TV show title
v17 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_strShowTitle.
getUniqueID()
String XBMCAddon::xbmc::InfoTagVideo::getUniqueID (key)
Function: getUniqueID(key)
Get the unique ID of the given key. A unique ID is an identifier used by a (online) video database used to identify a video in its database.
Parameters
key string - uniqueID name.
Some default uniqueID values (any string possible):
Label Type
imdb string - uniqueid name
tvdb string - uniqueid name
tmdb string - uniqueid name
anidb string - uniqueid name
v20 Python API changes:
New function added.
References CVideoInfoTag::GetUniqueID(), and XBMCAddon::xbmc::InfoTagVideo::infoTag.
getUserRating()
int XBMCAddon::xbmc::InfoTagVideo::getUserRating ()
Function: getUserRating()
Get the user rating if present as integer.
Returns
[integer] The user rating of the video
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_iUserRating.
getVotes()
String XBMCAddon::xbmc::InfoTagVideo::getVotes ()
Function: getVotes()
Get the video votes if available from video info tag.
Returns
[string] Votes
v20 Python API changes:
Deprecated. Use getVotesAsInt() instead.
References XBMCAddon::xbmc::InfoTagVideo::getVotesAsInt(), CLog::Log(), and LOGWARNING.
getVotesAsInt()
int XBMCAddon::xbmc::InfoTagVideo::getVotesAsInt (type)
Function: getVotesAsInt([type])
Get the votes of the rating (if available) as an integer.
Parameters
type [opt] string - the type of the rating.
Some rating type values (any string possible):
Label Type
imdb string - type name
tvdb string - type name
tmdb string - type name
anidb string - type name
Returns
[integer] Votes
v20 Python API changes:
New function added.
References CVideoInfoTag::GetRating(), XBMCAddon::xbmc::InfoTagVideo::infoTag, and CRating::votes.
Referenced by XBMCAddon::xbmc::InfoTagVideo::getVotes().
getWriters()
std::vector< String > XBMCAddon::xbmc::InfoTagVideo::getWriters ()
Function: getWriters()
Get the list of writers (if present) from video info tag.
Returns
[list] List of writers
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_writingCredits.
getWritingCredits()
String XBMCAddon::xbmc::InfoTagVideo::getWritingCredits ()
Function: getWritingCredits()
Get the writing credits if present from video info tag.
Returns
[string] Writing credits
v20 Python API changes:
Deprecated. Use getWriters() instead.
References CServiceBroker::GetSettingsComponent(), XBMCAddon::xbmc::InfoTagVideo::infoTag, and CVideoInfoTag::m_writingCredits.
getYear()
int XBMCAddon::xbmc::InfoTagVideo::getYear ()
Function: getYear()
Get production year of video if present.
Returns
[integer] Production Year
References CVideoInfoTag::GetYear(), and XBMCAddon::xbmc::InfoTagVideo::infoTag.
InfoTagVideo() [1/3]
XBMCAddon::xbmc::InfoTagVideo::InfoTagVideo (...)
Function: xbmc.InfoTagVideo([offscreen])
Create a video info tag.
Parameters
offscreen [opt] bool (default False) - if GUI based locks should be avoided. Most of the times listitems are created offscreen and added later to a container for display (e.g. plugins) or they are not even displayed (e.g. python scrapers). In such cases, there is no need to lock the GUI when creating the items (increasing your addon performance). Note however, that if you are creating listitems and managing the container itself (e.g using WindowXML or WindowXMLDialog classes) subsquent modifications to the item will require locking. Thus, in such cases, use the default value (False).
v20 Python API changes:
Added offscreen argument.
Example:
...
videoinfo = xbmc.InfoTagVideo(offscreen=False)
...
InfoTagVideo() [2/3]
XBMCAddon::xbmc::InfoTagVideo::InfoTagVideo (const CVideoInfoTag * tag) explicit
InfoTagVideo() [3/3]
XBMCAddon::xbmc::InfoTagVideo::InfoTagVideo (CVideoInfoTag * tag, bool offscreen = false) explicit
setAlbum()
void XBMCAddon::xbmc::InfoTagVideo::setAlbum (...)
Function: setAlbum(album)
Set the album of the video item.
Parameters
album string - Album.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setAlbumRaw().
setArtists()
void XBMCAddon::xbmc::InfoTagVideo::setArtists (...)
Function: setArtists(artists)
Set the artists of the music video item.
Parameters
artists list - Artists.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setArtistsRaw().
setCast()
void XBMCAddon::xbmc::InfoTagVideo::setCast (...)
Function: setCast(actors)
Set the cast / actors of the video item.
Parameters
actors list - Cast / Actors.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setCastRaw().
setCountries()
void XBMCAddon::xbmc::InfoTagVideo::setCountries (...)
Function: setCountries(countries)
Set the countries of the video item.
Parameters
countries list - Countries.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setCountriesRaw().
setDateAdded()
void XBMCAddon::xbmc::InfoTagVideo::setDateAdded (...)
Function: setDateAdded(dateadded)
Set the date added of the video item.
Parameters
dateadded string - Date added (YYYY-MM-DD HH:MM:SS).
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setDateAddedRaw().
setDbId()
void XBMCAddon::xbmc::InfoTagVideo::setDbId (...)
Function: setDbId(dbid)
Set the database identifier of the video item.
Parameters
dbid integer - Database identifier.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setDbIdRaw().
setDirectors()
void XBMCAddon::xbmc::InfoTagVideo::setDirectors (...)
Function: setDirectors(directors)
Set the directors of the video item.
Parameters
directors list - Directors.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setDirectorsRaw().
setDuration()
void XBMCAddon::xbmc::InfoTagVideo::setDuration (...)
Function: setDuration(duration)
Set the duration of the video item.
Parameters
duration integer - Duration in seconds.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setDurationRaw().
setEpisode()
void XBMCAddon::xbmc::InfoTagVideo::setEpisode (...)
Function: setEpisode(episode)
Set the episode number of the episode.
Parameters
episode integer - Episode number.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setEpisodeRaw().
setEpisodeGuide()
void XBMCAddon::xbmc::InfoTagVideo::setEpisodeGuide (...)
Function: setEpisodeGuide(episodeguide)
Set the episode guide of the video item.
Parameters
episodeguide string - Episode guide.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setEpisodeGuideRaw().
setFilenameAndPath()
void XBMCAddon::xbmc::InfoTagVideo::setFilenameAndPath (...)
Function: setFilenameAndPath(filenameandpath)
Set the filename and path of the video item.
Parameters
filenameandpath string - Filename and path.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setFilenameAndPathRaw().
setFirstAired()
void XBMCAddon::xbmc::InfoTagVideo::setFirstAired (...)
Function: setFirstAired(firstaired)
Set the first aired date of the video item.
Parameters
firstaired string - First aired date.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setFirstAiredRaw().
setGenres()
void XBMCAddon::xbmc::InfoTagVideo::setGenres (...)
Function: setGenres(genre)
Set the genres of the video item.
Parameters
genre list - Genres.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setGenresRaw().
setIMDBNumber()
void XBMCAddon::xbmc::InfoTagVideo::setIMDBNumber (...)
Function: setIMDBNumber(imdbnumber)
Set the IMDb number of the video item.
Parameters
imdbnumber string - IMDb number.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setIMDBNumberRaw().
setLastPlayed()
void XBMCAddon::xbmc::InfoTagVideo::setLastPlayed (...)
Function: setLastPlayed(lastplayed)
Set the last played date of the video item.
Parameters
lastplayed string - Last played date (YYYY-MM-DD HH:MM:SS).
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setLastPlayedRaw().
setMediaType()
void XBMCAddon::xbmc::InfoTagVideo::setMediaType (...)
Function: setMediaType(mediatype)
Set the media type of the video item.
Parameters
mediatype string - Media type.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and XBMCAddon::xbmc::InfoTagVideo::setMediaTypeRaw().
setMpaa()
void XBMCAddon::xbmc::InfoTagVideo::setMpaa (...)
Function: setMpaa(mpaa)
Set the MPAA rating of the video item.
Parameters
mpaa string - MPAA rating.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setMpaaRaw().
setOriginalTitle()
void XBMCAddon::xbmc::InfoTagVideo::setOriginalTitle (...)
Function: setOriginalTitle(originaltitle)
Set the original title of the video item.
Parameters
originaltitle string - Original title.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setOriginalTitleRaw().
setPath()
void XBMCAddon::xbmc::InfoTagVideo::setPath (...)
Function: setPath(path)
Set the path of the video item.
Parameters
path string - Path.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setPathRaw().
setPlaycount()
void XBMCAddon::xbmc::InfoTagVideo::setPlaycount (...)
Function: setPlaycount(playcount)
Set the playcount of the video item.
Parameters
playcount integer - Playcount.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setPlaycountRaw().
setPlot()
void XBMCAddon::xbmc::InfoTagVideo::setPlot (...)
Function: setPlot(plot)
Set the plot of the video item.
Parameters
plot string - Plot.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setPlotRaw().
setPlotOutline()
void XBMCAddon::xbmc::InfoTagVideo::setPlotOutline (...)
Function: setPlotOutline(plotoutline)
Set the plot outline of the video item.
Parameters
plotoutline string - Plot outline.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setPlotOutlineRaw().
setPremiered()
void XBMCAddon::xbmc::InfoTagVideo::setPremiered (...)
Function: setPremiered(premiered)
Set the premiere date of the video item.
Parameters
premiered string - Premiere date.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setPremieredRaw().
setProductionCode()
void XBMCAddon::xbmc::InfoTagVideo::setProductionCode (...)
Function: setProductionCode(const String& productioncode)
Set the production code of the video item.
Parameters
productioncode string - Production code.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setProductionCodeRaw().
setRating()
void XBMCAddon::xbmc::InfoTagVideo::setRating (...)
Function: setRating(rating, [votes], [type], [isdefault])
Set the rating of the video item.
Parameters
rating float - Rating number.
votes integer - Number of votes.
type string - Type of the rating.
isdefault bool - Whether the rating is the default or not.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setRatingRaw().
setRatings()
void XBMCAddon::xbmc::InfoTagVideo::setRatings (...)
Function: setRatings(ratings, [defaultrating])
Set the ratings of the video item.
Parameters
ratings dictionary - ‘{ 'type’: (rating, votes) }`.
defaultrating string - Type / Label of the default rating.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setRatingsRaw().
setResumePoint()
void XBMCAddon::xbmc::InfoTagVideo::setResumePoint (...)
Function: setResumePoint(time, [totaltime])
Set the resume point of the video item.
Parameters
time float - Resume point in seconds.
totaltime float - Total duration in seconds.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setResumePointRaw().
setSeason()
void XBMCAddon::xbmc::InfoTagVideo::setSeason (...)
Function: setSeason(season)
Set the season number of the video item.
Parameters
season integer - Season number.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setSeasonRaw().
setSet()
void XBMCAddon::xbmc::InfoTagVideo::setSet (...)
Function: setSet(set)
Set the movie set (name) of the video item.
Parameters
set string - Movie set (name).
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setSetRaw().
setSetId()
void XBMCAddon::xbmc::InfoTagVideo::setSetId (...)
Function: setSetId(setid)
Set the movie set identifier of the video item.
Parameters
setid integer - Set identifier.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setSetIdRaw().
setSetOverview()
void XBMCAddon::xbmc::InfoTagVideo::setSetOverview (...)
Function: setSetOverview(setoverview)
Set the movie set overview of the video item.
Parameters
setoverview string - Movie set overview.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setSetOverviewRaw().
setShowLinks()
void XBMCAddon::xbmc::InfoTagVideo::setShowLinks (...)
Function: setShowLinks(showlinks)
Set the TV show links of the movie.
Parameters
showlinks list - TV show links.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setShowLinksRaw().
setSortEpisode()
void XBMCAddon::xbmc::InfoTagVideo::setSortEpisode (...)
Function: setSortEpisode(sortepisode)
Set the episode sort number of the episode.
Parameters
sortepisode integer - Episode sort number.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setSortEpisodeRaw().
setSortSeason()
void XBMCAddon::xbmc::InfoTagVideo::setSortSeason (...)
Function: setSortSeason(sortseason)
Set the season sort number of the season.
Parameters
sortseason integer - Season sort number.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setSortSeasonRaw().
setSortTitle()
void XBMCAddon::xbmc::InfoTagVideo::setSortTitle (...)
Function: setSortTitle(sorttitle)
Set the sort title of the video item.
Parameters
sorttitle string - Sort title.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setSortTitleRaw().
setStudios()
void XBMCAddon::xbmc::InfoTagVideo::setStudios (...)
Function: setStudios(studios)
Set the studios of the video item.
Parameters
studios list - Studios.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setStudiosRaw().
setTagLine()
void XBMCAddon::xbmc::InfoTagVideo::setTagLine (...)
Function: setTagLine(tagline)
Set the tagline of the video item.
Parameters
tagline string - Tagline.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setTagLineRaw().
setTags()
void XBMCAddon::xbmc::InfoTagVideo::setTags (...)
Function: setTags(tags)
Set the tags of the video item.
Parameters
tags list - Tags.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, XBMCAddon::xbmc::InfoTagVideo::setTagsRaw(), and tags.
setTitle()
void XBMCAddon::xbmc::InfoTagVideo::setTitle (...)
Function: setTitle(title)
Set the title of the video item.
Parameters
title string - Title.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setTitleRaw().
setTop250()
void XBMCAddon::xbmc::InfoTagVideo::setTop250 (...)
Function: setTop250(top250)
Set the top 250 number of the video item.
Parameters
top250 integer - Top 250 number.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setTop250Raw().
setTrackNumber()
void XBMCAddon::xbmc::InfoTagVideo::setTrackNumber (...)
Function: setTrackNumber(tracknumber)
Set the track number of the music video item.
Parameters
tracknumber integer - Track number.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setTrackNumberRaw().
setTrailer()
void XBMCAddon::xbmc::InfoTagVideo::setTrailer (...)
Function: setTrailer(trailer)
Set the trailer of the video item.
Parameters
trailer string - Trailer.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setTrailerRaw().
setTvShowStatus()
void XBMCAddon::xbmc::InfoTagVideo::setTvShowStatus (...)
Function: setTvShowStatus(tvshowstatus)
Set the TV show status of the video item.
Parameters
status string - TV show status.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setTvShowStatusRaw().
setTvShowTitle()
void XBMCAddon::xbmc::InfoTagVideo::setTvShowTitle (...)
Function: setTvShowTitle(tvshowtitle)
Set the TV show title of the video item.
Parameters
tvshowtitle string - TV show title.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setTvShowTitleRaw().
setUniqueID()
void XBMCAddon::xbmc::InfoTagVideo::setUniqueID (...)
Function: setUniqueID(uniqueid, [type], [isdefault])
Set the given unique ID. A unique ID is an identifier used by a (online) video database used to identify a video in its database.
Parameters
uniqueid string - value of the unique ID.
type [opt] string - type / label of the unique ID.
isdefault [opt] bool - whether the given unique ID is the default unique ID.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setUniqueIDRaw().
setUniqueIDs()
void XBMCAddon::xbmc::InfoTagVideo::setUniqueIDs (...)
Function: setUniqueIDs(values, defaultuniqueid)
Set the given unique IDs. A unique ID is an identifier used by a (online) video database used to identify a video in its database.
Parameters
values dictionary - pairs of ‘{ 'label’: 'value' }`.
defaultuniqueid [opt] string - the name of default uniqueID.
Some example values (any string possible):
Label Type
imdb string - uniqueid name
tvdb string - uniqueid name
tmdb string - uniqueid name
anidb string - uniqueid name
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setUniqueIDsRaw().
setUserRating()
void XBMCAddon::xbmc::InfoTagVideo::setUserRating (...)
Function: setUserRating(userrating)
Set the user rating of the video item.
Parameters
userrating integer - User rating.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setUserRatingRaw().
setVideoAssetTitle()
void XBMCAddon::xbmc::InfoTagVideo::setVideoAssetTitle (...)
Function: setVideoAssetTitle(videoAssetTitle)
Set the video asset title of the item.
Parameters
videoAssetTitle string - Video asset title.
v21 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and XBMCAddon::xbmc::InfoTagVideo::setVideoAssetTitleRaw().
setVotes()
void XBMCAddon::xbmc::InfoTagVideo::setVotes (...)
Function: setVotes(votes)
Set the number of votes of the video item.
Parameters
votes integer - Number of votes.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setVotesRaw().
setWriters()
void XBMCAddon::xbmc::InfoTagVideo::setWriters (...)
Function: setWriters(writers)
Set the writers of the video item.
Parameters
writers list - Writers.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setWritersRaw().
setYear()
void XBMCAddon::xbmc::InfoTagVideo::setYear (...)
Function: setYear(year)
Set the year of the video item.
Parameters
year integer - Year.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagVideo::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagVideo::offscreen, and XBMCAddon::xbmc::InfoTagVideo::setYearRaw().
ToActorInfo()
SActorInfo XBMCAddon::xbmc::Actor::ToActorInfo () const
References CScraperUrl::GetFirstThumbUrl(), CScraperUrl::GetFirstUrlByType(), CScraperUrl::GetThumbUrl(), XBMCAddon::xbmc::Actor::m_name, XBMCAddon::xbmc::Actor::m_order, XBMCAddon::xbmc::Actor::m_role, XBMCAddon::xbmc::Actor::m_thumbnail, SActorInfo::order, SActorInfo::strName, SActorInfo::strRole, SActorInfo::thumb, and SActorInfo::thumbUrl.
ToStreamDetailAudio()
CStreamDetailAudio * XBMCAddon::xbmc::AudioStreamDetail::ToStreamDetailAudio () const
References XBMCAddon::xbmc::AudioStreamDetail::m_channels, XBMCAddon::xbmc::AudioStreamDetail::m_codec, and XBMCAddon::xbmc::AudioStreamDetail::m_language.
Referenced by XBMCAddon::xbmc::InfoTagVideo::addAudioStream().
ToStreamDetailSubtitle()
CStreamDetailSubtitle * XBMCAddon::xbmc::SubtitleStreamDetail::ToStreamDetailSubtitle () const
References XBMCAddon::xbmc::SubtitleStreamDetail::m_language.
Referenced by XBMCAddon::xbmc::InfoTagVideo::addSubtitleStream().
ToStreamDetailVideo()
CStreamDetailVideo * XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo () const
References XBMCAddon::xbmc::VideoStreamDetail::m_aspect, XBMCAddon::xbmc::VideoStreamDetail::m_codec, XBMCAddon::xbmc::VideoStreamDetail::m_duration, XBMCAddon::xbmc::VideoStreamDetail::m_hdrType, XBMCAddon::xbmc::VideoStreamDetail::m_height, XBMCAddon::xbmc::VideoStreamDetail::m_language, XBMCAddon::xbmc::VideoStreamDetail::m_stereoMode, and XBMCAddon::xbmc::VideoStreamDetail::m_width.
Referenced by XBMCAddon::xbmc::InfoTagVideo::addVideoStream().
~InfoTagVideo()
XBMCAddon::xbmc::InfoTagVideo::~InfoTagVideo () override
References XBMCAddon::xbmc::InfoTagVideo::infoTag, and XBMCAddon::xbmc::InfoTagVideo::owned.
Variable Documentation
infoTag
CVideoInfoTag* XBMCAddon::xbmc::InfoTagVideo::infoTag private
Referenced by XBMCAddon::xbmc::InfoTagVideo::addAudioStream(), XBMCAddon::xbmc::InfoTagVideo::addAvailableArtwork(), XBMCAddon::xbmc::InfoTagVideo::addSeason(), XBMCAddon::xbmc::InfoTagVideo::addSeasons(), XBMCAddon::xbmc::InfoTagVideo::addSubtitleStream(), XBMCAddon::xbmc::InfoTagVideo::addVideoStream(), XBMCAddon::xbmc::InfoTagVideo::getActors(), XBMCAddon::xbmc::InfoTagVideo::getAlbum(), XBMCAddon::xbmc::InfoTagVideo::getArtist(), XBMCAddon::xbmc::InfoTagVideo::getCast(), XBMCAddon::xbmc::InfoTagVideo::getDbId(), XBMCAddon::xbmc::InfoTagVideo::getDirector(), XBMCAddon::xbmc::InfoTagVideo::getDirectors(), XBMCAddon::xbmc::InfoTagVideo::getDuration(), XBMCAddon::xbmc::InfoTagVideo::getEpisode(), XBMCAddon::xbmc::InfoTagVideo::getFile(), XBMCAddon::xbmc::InfoTagVideo::getFilenameAndPath(), XBMCAddon::xbmc::InfoTagVideo::getFirstAired(), XBMCAddon::xbmc::InfoTagVideo::getFirstAiredAsW3C(), XBMCAddon::xbmc::InfoTagVideo::getGenre(), XBMCAddon::xbmc::InfoTagVideo::getGenres(), XBMCAddon::xbmc::InfoTagVideo::getIMDBNumber(), XBMCAddon::xbmc::InfoTagVideo::getLastPlayed(), XBMCAddon::xbmc::InfoTagVideo::getLastPlayedAsW3C(), XBMCAddon::xbmc::InfoTagVideo::getMediaType(), XBMCAddon::xbmc::InfoTagVideo::getOriginalTitle(), XBMCAddon::xbmc::InfoTagVideo::getPath(), XBMCAddon::xbmc::InfoTagVideo::getPictureURL(), XBMCAddon::xbmc::InfoTagVideo::getPlayCount(), XBMCAddon::xbmc::InfoTagVideo::getPlot(), XBMCAddon::xbmc::InfoTagVideo::getPlotOutline(), XBMCAddon::xbmc::InfoTagVideo::getPremiered(), XBMCAddon::xbmc::InfoTagVideo::getPremieredAsW3C(), XBMCAddon::xbmc::InfoTagVideo::getRating(), XBMCAddon::xbmc::InfoTagVideo::getResumeTime(), XBMCAddon::xbmc::InfoTagVideo::getResumeTimeTotal(), XBMCAddon::xbmc::InfoTagVideo::getSeason(), XBMCAddon::xbmc::InfoTagVideo::getTagLine(), XBMCAddon::xbmc::InfoTagVideo::getTitle(), XBMCAddon::xbmc::InfoTagVideo::getTrack(), XBMCAddon::xbmc::InfoTagVideo::getTrailer(), XBMCAddon::xbmc::InfoTagVideo::getTVShowTitle(), XBMCAddon::xbmc::InfoTagVideo::getUniqueID(), XBMCAddon::xbmc::InfoTagVideo::getUserRating(), XBMCAddon::xbmc::InfoTagVideo::getVotesAsInt(), XBMCAddon::xbmc::InfoTagVideo::getWriters(), XBMCAddon::xbmc::InfoTagVideo::getWritingCredits(), XBMCAddon::xbmc::InfoTagVideo::getYear(), XBMCAddon::xbmc::InfoTagVideo::setAlbum(), XBMCAddon::xbmc::InfoTagVideo::setArtists(), XBMCAddon::xbmc::InfoTagVideo::setCast(), XBMCAddon::xbmc::InfoTagVideo::setCountries(), XBMCAddon::xbmc::InfoTagVideo::setDateAdded(), XBMCAddon::xbmc::InfoTagVideo::setDbId(), XBMCAddon::xbmc::InfoTagVideo::setDbIdRaw(), XBMCAddon::xbmc::InfoTagVideo::setDirectors(), XBMCAddon::xbmc::InfoTagVideo::setDuration(), XBMCAddon::xbmc::InfoTagVideo::setEpisode(), XBMCAddon::xbmc::InfoTagVideo::setEpisodeGuide(), XBMCAddon::xbmc::InfoTagVideo::setEpisodeGuideRaw(), XBMCAddon::xbmc::InfoTagVideo::setEpisodeRaw(), XBMCAddon::xbmc::InfoTagVideo::setFilenameAndPath(), XBMCAddon::xbmc::InfoTagVideo::setFirstAired(), XBMCAddon::xbmc::InfoTagVideo::setGenres(), XBMCAddon::xbmc::InfoTagVideo::setIMDBNumber(), XBMCAddon::xbmc::InfoTagVideo::setLastPlayed(), XBMCAddon::xbmc::InfoTagVideo::setMediaType(), XBMCAddon::xbmc::InfoTagVideo::setMpaa(), XBMCAddon::xbmc::InfoTagVideo::setOriginalTitle(), XBMCAddon::xbmc::InfoTagVideo::setPath(), XBMCAddon::xbmc::InfoTagVideo::setPlaycount(), XBMCAddon::xbmc::InfoTagVideo::setPlot(), XBMCAddon::xbmc::InfoTagVideo::setPlotOutline(), XBMCAddon::xbmc::InfoTagVideo::setPremiered(), XBMCAddon::xbmc::InfoTagVideo::setProductionCode(), XBMCAddon::xbmc::InfoTagVideo::setRating(), XBMCAddon::xbmc::InfoTagVideo::setRatingRaw(), XBMCAddon::xbmc::InfoTagVideo::setRatings(), XBMCAddon::xbmc::InfoTagVideo::setResumePoint(), XBMCAddon::xbmc::InfoTagVideo::setSeason(), XBMCAddon::xbmc::InfoTagVideo::setSeasonRaw(), XBMCAddon::xbmc::InfoTagVideo::setSet(), XBMCAddon::xbmc::InfoTagVideo::setSetId(), XBMCAddon::xbmc::InfoTagVideo::setSetIdRaw(), XBMCAddon::xbmc::InfoTagVideo::setSetOverview(), XBMCAddon::xbmc::InfoTagVideo::setShowLinks(), XBMCAddon::xbmc::InfoTagVideo::setSortEpisode(), XBMCAddon::xbmc::InfoTagVideo::setSortEpisodeRaw(), XBMCAddon::xbmc::InfoTagVideo::setSortSeason(), XBMCAddon::xbmc::InfoTagVideo::setSortSeasonRaw(), XBMCAddon::xbmc::InfoTagVideo::setSortTitle(), XBMCAddon::xbmc::InfoTagVideo::setStudios(), XBMCAddon::xbmc::InfoTagVideo::setTagLine(), XBMCAddon::xbmc::InfoTagVideo::setTags(), XBMCAddon::xbmc::InfoTagVideo::setTitle(), XBMCAddon::xbmc::InfoTagVideo::setTop250(), XBMCAddon::xbmc::InfoTagVideo::setTop250Raw(), XBMCAddon::xbmc::InfoTagVideo::setTrackNumber(), XBMCAddon::xbmc::InfoTagVideo::setTrackNumberRaw(), XBMCAddon::xbmc::InfoTagVideo::setTrailer(), XBMCAddon::xbmc::InfoTagVideo::setTvShowStatus(), XBMCAddon::xbmc::InfoTagVideo::setTvShowTitle(), XBMCAddon::xbmc::InfoTagVideo::setUniqueID(), XBMCAddon::xbmc::InfoTagVideo::setUniqueIDRaw(), XBMCAddon::xbmc::InfoTagVideo::setUniqueIDs(), XBMCAddon::xbmc::InfoTagVideo::setUniqueIDsRaw(), XBMCAddon::xbmc::InfoTagVideo::setUserRating(), XBMCAddon::xbmc::InfoTagVideo::setVideoAssetTitle(), XBMCAddon::xbmc::InfoTagVideo::setVotes(), XBMCAddon::xbmc::InfoTagVideo::setWriters(), XBMCAddon::xbmc::InfoTagVideo::setYear(), XBMCAddon::xbmc::InfoTagVideo::setYearRaw(), and XBMCAddon::xbmc::InfoTagVideo::~InfoTagVideo().
m_aspect
float XBMCAddon::xbmc::VideoStreamDetail::m_aspect private
Referenced by XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo().
m_channels
int XBMCAddon::xbmc::AudioStreamDetail::m_channels private
Referenced by XBMCAddon::xbmc::AudioStreamDetail::ToStreamDetailAudio().
m_codec [1/2]
String XBMCAddon::xbmc::VideoStreamDetail::m_codec private
Referenced by XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo().
m_codec [2/2]
String XBMCAddon::xbmc::AudioStreamDetail::m_codec private
Referenced by XBMCAddon::xbmc::AudioStreamDetail::ToStreamDetailAudio().
m_duration
int XBMCAddon::xbmc::VideoStreamDetail::m_duration private
Referenced by XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo().
m_hdrType
String XBMCAddon::xbmc::VideoStreamDetail::m_hdrType private
Referenced by XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo().
m_height
int XBMCAddon::xbmc::VideoStreamDetail::m_height private
Referenced by XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo().
m_language [1/3]
String XBMCAddon::xbmc::VideoStreamDetail::m_language private
Referenced by XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo().
m_language [2/3]
String XBMCAddon::xbmc::AudioStreamDetail::m_language private
Referenced by XBMCAddon::xbmc::AudioStreamDetail::ToStreamDetailAudio().
m_language [3/3]
String XBMCAddon::xbmc::SubtitleStreamDetail::m_language private
Referenced by XBMCAddon::xbmc::SubtitleStreamDetail::ToStreamDetailSubtitle().
m_name
String XBMCAddon::xbmc::Actor::m_name private
Referenced by XBMCAddon::xbmc::Actor::Actor(), and XBMCAddon::xbmc::Actor::ToActorInfo().
m_order
int XBMCAddon::xbmc::Actor::m_order private
Referenced by XBMCAddon::xbmc::Actor::ToActorInfo().
m_role
String XBMCAddon::xbmc::Actor::m_role private
Referenced by XBMCAddon::xbmc::Actor::ToActorInfo().
m_stereoMode
String XBMCAddon::xbmc::VideoStreamDetail::m_stereoMode private
Referenced by XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo().
m_thumbnail
String XBMCAddon::xbmc::Actor::m_thumbnail private
Referenced by XBMCAddon::xbmc::Actor::ToActorInfo().
m_width
int XBMCAddon::xbmc::VideoStreamDetail::m_width private
Referenced by XBMCAddon::xbmc::VideoStreamDetail::ToStreamDetailVideo().
offscreen
bool XBMCAddon::xbmc::InfoTagVideo::offscreen private
Referenced by XBMCAddon::xbmc::InfoTagVideo::addAudioStream(), XBMCAddon::xbmc::InfoTagVideo::addAvailableArtwork(), XBMCAddon::xbmc::InfoTagVideo::addSeason(), XBMCAddon::xbmc::InfoTagVideo::addSeasons(), XBMCAddon::xbmc::InfoTagVideo::addSubtitleStream(), XBMCAddon::xbmc::InfoTagVideo::addVideoStream(), XBMCAddon::xbmc::InfoTagVideo::getPictureURL(), XBMCAddon::xbmc::InfoTagVideo::setAlbum(), XBMCAddon::xbmc::InfoTagVideo::setArtists(), XBMCAddon::xbmc::InfoTagVideo::setCast(), XBMCAddon::xbmc::InfoTagVideo::setCountries(), XBMCAddon::xbmc::InfoTagVideo::setDateAdded(), XBMCAddon::xbmc::InfoTagVideo::setDbId(), XBMCAddon::xbmc::InfoTagVideo::setDirectors(), XBMCAddon::xbmc::InfoTagVideo::setDuration(), XBMCAddon::xbmc::InfoTagVideo::setEpisode(), XBMCAddon::xbmc::InfoTagVideo::setEpisodeGuide(), XBMCAddon::xbmc::InfoTagVideo::setFilenameAndPath(), XBMCAddon::xbmc::InfoTagVideo::setFirstAired(), XBMCAddon::xbmc::InfoTagVideo::setGenres(), XBMCAddon::xbmc::InfoTagVideo::setIMDBNumber(), XBMCAddon::xbmc::InfoTagVideo::setLastPlayed(), XBMCAddon::xbmc::InfoTagVideo::setMpaa(), XBMCAddon::xbmc::InfoTagVideo::setOriginalTitle(), XBMCAddon::xbmc::InfoTagVideo::setPath(), XBMCAddon::xbmc::InfoTagVideo::setPlaycount(), XBMCAddon::xbmc::InfoTagVideo::setPlot(), XBMCAddon::xbmc::InfoTagVideo::setPlotOutline(), XBMCAddon::xbmc::InfoTagVideo::setPremiered(), XBMCAddon::xbmc::InfoTagVideo::setProductionCode(), XBMCAddon::xbmc::InfoTagVideo::setRating(), XBMCAddon::xbmc::InfoTagVideo::setRatings(), XBMCAddon::xbmc::InfoTagVideo::setResumePoint(), XBMCAddon::xbmc::InfoTagVideo::setSeason(), XBMCAddon::xbmc::InfoTagVideo::setSet(), XBMCAddon::xbmc::InfoTagVideo::setSetId(), XBMCAddon::xbmc::InfoTagVideo::setSetOverview(), XBMCAddon::xbmc::InfoTagVideo::setShowLinks(), XBMCAddon::xbmc::InfoTagVideo::setSortEpisode(), XBMCAddon::xbmc::InfoTagVideo::setSortSeason(), XBMCAddon::xbmc::InfoTagVideo::setSortTitle(), XBMCAddon::xbmc::InfoTagVideo::setStudios(), XBMCAddon::xbmc::InfoTagVideo::setTagLine(), XBMCAddon::xbmc::InfoTagVideo::setTags(), XBMCAddon::xbmc::InfoTagVideo::setTitle(), XBMCAddon::xbmc::InfoTagVideo::setTop250(), XBMCAddon::xbmc::InfoTagVideo::setTrackNumber(), XBMCAddon::xbmc::InfoTagVideo::setTrailer(), XBMCAddon::xbmc::InfoTagVideo::setTvShowStatus(), XBMCAddon::xbmc::InfoTagVideo::setTvShowTitle(), XBMCAddon::xbmc::InfoTagVideo::setUniqueID(), XBMCAddon::xbmc::InfoTagVideo::setUniqueIDs(), XBMCAddon::xbmc::InfoTagVideo::setUserRating(), XBMCAddon::xbmc::InfoTagVideo::setVotes(), XBMCAddon::xbmc::InfoTagVideo::setWriters(), and XBMCAddon::xbmc::InfoTagVideo::setYear().
owned
bool XBMCAddon::xbmc::InfoTagVideo::owned private
Referenced by XBMCAddon::xbmc::InfoTagVideo::~InfoTagVideo().