Kodi Documentation: KODI::UTILS::GL Namespace Reference
KODI::UTILS::GL Namespace Reference
Enumerations
enum class ColorChannel { A , R , G , B }
Functions
void GlErrorCallback (GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *message, const void *userParam)
int glFormatElementByteCount (GLenum format)
uint8_t GetChannelFromARGB (const ColorChannel colorChannel, const uint32_t argb)
Enumeration Type Documentation
ColorChannel
enum class KODI::UTILS::GL::ColorChannel strong
Enumerator
A
R
G
B
Function Documentation
GetChannelFromARGB()
uint8_t KODI::UTILS::GL::GetChannelFromARGB (const ColorChannel colorChannel, const uint32_t argb)
References A, B, G, and R.
Referenced by CGUITextureGL::Begin(), CGUITextureGLES::Begin(), CRenderSystemGL::ClearBuffers(), CRenderSystemGLES::ClearBuffers(), CGUITextureGL::DrawQuad(), CGUITextureGLES::DrawQuad(), CSlideShowPicGL::Render(), CSlideShowPicGLES::Render(), KODI::RETRO::CRPRendererOpenGL::Render(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), CGUIFontTTF::RenderCharacter(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
GlErrorCallback()
void KODI::UTILS::GL::GlErrorCallback (GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar * message, const void * userParam)
References anonymous_namespace{GLUtils.cpp}::glErrorSeverity, anonymous_namespace{GLUtils.cpp}::glErrorSource, anonymous_namespace{GLUtils.cpp}::glErrorType, CLog::Log(), and LOGDEBUG.
Referenced by CRenderSystemGL::InitRenderSystem(), and CRenderSystemGLES::InitRenderSystem().
glFormatElementByteCount()
int KODI::UTILS::GL::glFormatElementByteCount (GLenum format)
References CLog::Log(), and LOGERROR.
Referenced by CLinuxRendererGL::LoadPlane(), CLinuxRendererGLES::LoadPlane(), LoadTexture(), and LoadTexture().