Kodi Documentation: TestVideoFileItemClassify.cpp File Reference
TestVideoFileItemClassify.cpp File Reference
#include "FileItem.h"
#include "ServiceBroker.h"
#include "filesystem/Directory.h"
#include "filesystem/File.h"
#include "games/tags/GameInfoTag.h"
#include "music/tags/MusicInfoTag.h"
#include "pictures/PictureInfoTag.h"
#include "test/TestUtils.h"
#include "utils/FileExtensionProvider.h"
#include "utils/FileUtils.h"
#include "utils/URIUtils.h"
#include "video/VideoFileItemClassify.h"
#include "video/VideoInfoTag.h"
#include <array>
#include <gtest/gtest.h>
Classes
struct StubDefinition
class DiscStubTest
struct VideoClassifyTest
class VideoTest
Functions
TEST_P (DiscStubTest, IsDiscStub)
INSTANTIATE_TEST_SUITE_P (TestVideoFileItemClassify, DiscStubTest, testing::ValuesIn(discstub_tests))
TEST_P (VideoTest, IsVideo)
INSTANTIATE_TEST_SUITE_P (TestVideoFileItemClassify, VideoTest, testing::ValuesIn(video_tests))
TEST (TestVideoFileItemClassify, VideoExtensions)
TEST (TestVideoFileItemClassify, IsBDFile)
TEST (TestVideoFileItemClassify, IsDVDFile)
TEST (TestVideoFileItemClassify, IsProtectedBlurayDisc)
TEST (TestVideoFileItemClassify, IsSubtitle)
TEST (TestVideoFileItemClassify, IsVideoAssetsFile)
TEST (TestVideoFileItemClassify, IsVideoDb)
TEST (TestVideoFileItemClassify, IsVideoExtrasFolder)
Variables
const auto discstub_tests
const auto video_tests
Function Documentation
INSTANTIATE_TEST_SUITE_P() [1/2]
INSTANTIATE_TEST_SUITE_P (TestVideoFileItemClassify , DiscStubTest , testing::ValuesIn(discstub_tests))
INSTANTIATE_TEST_SUITE_P() [2/2]
INSTANTIATE_TEST_SUITE_P (TestVideoFileItemClassify , VideoTest , testing::ValuesIn(video_tests))
TEST() [1/8]
TEST (TestVideoFileItemClassify , IsBDFile)
References EXPECT_TRUE().
TEST() [2/8]
TEST (TestVideoFileItemClassify , IsDVDFile)
References EXPECT_TRUE().
TEST() [3/8]
TEST (TestVideoFileItemClassify , IsProtectedBlurayDisc)
References URIUtils::AddFileToFolder(), XFILE::CFile::Close(), XFILE::CDirectory::Create(), CXBMCTestUtils::CreateTempFile(), CFileUtils::DeleteItem(), CXBMCTestUtils::DeleteTempFile(), EXPECT_TRUE(), CXBMCTestUtils::Instance(), XFILE::CFile::OpenForWrite(), and CXBMCTestUtils::TempFileDirectory().
TEST() [4/8]
TEST (TestVideoFileItemClassify , IsSubtitle)
References EXPECT_TRUE(), CServiceBroker::GetFileExtensionProvider(), CFileExtensionProvider::GetSubtitleExtensions(), and KODI::UTILS::StringUtils::Split().
TEST() [5/8]
TEST (TestVideoFileItemClassify , IsVideoAssetsFile)
References EXPECT_TRUE().
TEST() [6/8]
TEST (TestVideoFileItemClassify , IsVideoDb)
References EXPECT_TRUE().
TEST() [7/8]
TEST (TestVideoFileItemClassify , IsVideoExtrasFolder)
References EXPECT_TRUE().
TEST() [8/8]
TEST (TestVideoFileItemClassify , VideoExtensions)
References EXPECT_TRUE(), CServiceBroker::GetFileExtensionProvider(), CFileExtensionProvider::GetVideoExtensions(), and KODI::UTILS::StringUtils::Split().
TEST_P() [1/2]
TEST_P (DiscStubTest , IsDiscStub)
References EXPECT_EQ().
TEST_P() [2/2]
TEST_P (VideoTest , IsVideo)
References EXPECT_EQ().
Variable Documentation
discstub_tests
const auto discstub_tests
Initial value:
= std::array{
    StubDefinition{"/home/user/test.disc"},
    StubDefinition{"videodb://foo/bar", true, "/home/user/test.disc"},
    StubDefinition{"videodb://foo/bar", false, "/home/user/test.disc", true},
    StubDefinition{"/home/user/test.avi", false},
}
video_tests
const auto video_tests
Initial value:
= std::array{
    VideoClassifyTest{"/home/user/video.avi", true, "video/avi"},
    VideoClassifyTest{"/home/user/video.avi", true, "", 1},
    VideoClassifyTest{"/home/user/video.gam", false, "", 2},
    VideoClassifyTest{"/home/user/video.mus", false, "", 3},
    VideoClassifyTest{"/home/user/video.pic", false, "", 4},
    VideoClassifyTest{"pvr://recordings/tv/1", true},
    VideoClassifyTest{"pvr://123", false},
    VideoClassifyTest{"dvd://VIDEO_TS/video_ts.ifo", true},
    VideoClassifyTest{"dvd://1", true},
    VideoClassifyTest{"/home/user/video.not", true, "application/ogg"},
    VideoClassifyTest{"/home/user/video.not", true, "application/mp4"},
    VideoClassifyTest{"/home/user/video.not", true, "application/mxf"},
}