Kodi Documentation: PVR::CPVREpgDatabase Class Reference
PVR::CPVREpgDatabase Class Reference
#include <EpgDatabase.h>
Public Member Functions
CPVREpgDatabase ()=default
Create a new instance of the EPG database.
~CPVREpgDatabase () override=default
Destroy this instance.
bool Open () override
Open the database.
void Close () override
Close the database.
void Lock ()
Lock the database.
void Unlock ()
Unlock the database.
int GetSchemaVersion () const override
Get the minimal database version that is required to operate correctly.
const char * GetBaseDBName () const override
Get the default sqlite database filename.
EPG methods
bool DeleteEpg ()
Remove all EPG information from the database.
bool QueueDeleteEpgQuery (const CPVREpg &table)
Queue deletionof an EPG table.
bool QueueDeleteTagQuery (const CPVREpgInfoTag &tag)
Write the query to delete the given EPG tag to db query queue.
std::vector< std::shared_ptr< CPVREpg > > GetAll ()
Get all EPG tables from the database. Does not get the EPG tables' entries.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetAllEpgTags (int iEpgID) const
Get all tags for a given EPG id.
bool GetAllIconPaths (int iEpgID, std::vector< std::string > &paths) const
Get all icon paths for a given EPG id.
bool GetAllParentalRatingIconPaths (int iEpgID, std::vector< std::string > &paths) const
Get all parental rating icon paths for a given EPG id.
bool HasTags (int iEpgID) const
Check whether this EPG has any tags.
CDateTime GetLastEndTime (int iEpgID) const
Get the end time of the last tag in this EPG.
std::pair< CDateTime, CDateTime > GetFirstAndLastEPGDate () const
Get the start and end time across all EPGs.
CDateTime GetMinStartTime (int iEpgID, const CDateTime &minStart) const
Get the start time of the first tag with a start time greater than the given min time.
CDateTime GetMaxEndTime (int iEpgID, const CDateTime &maxEnd) const
Get the end time of the first tag with an end time less than the given max time.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetEpgTags (const PVREpgSearchData &searchData) const
Get all EPG tags matching the given search criteria.
std::shared_ptr< CPVREpgInfoTag > GetEpgTagByUniqueBroadcastID (int iEpgID, unsigned int iUniqueBroadcastId) const
Get an EPG tag given its EPG id and unique broadcast ID.
std::shared_ptr< CPVREpgInfoTag > GetEpgTagByDatabaseID (int iEpgID, int iDatabaseId) const
Get an EPG tag given its EPG id and database ID.
std::shared_ptr< CPVREpgInfoTag > GetEpgTagByStartTime (int iEpgID, const CDateTime &startTime) const
Get an EPG tag given its EPG ID and start time.
std::shared_ptr< CPVREpgInfoTag > GetEpgTagByMinStartTime (int iEpgID, const CDateTime &minStartTime) const
Get the next EPG tag matching the given EPG id and min start time.
std::shared_ptr< CPVREpgInfoTag > GetEpgTagByMaxEndTime (int iEpgID, const CDateTime &maxEndTime) const
Get the next EPG tag matching the given EPG id and max end time.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetEpgTagsByMinStartMaxEndTime (int iEpgID, const CDateTime &minStartTime, const CDateTime &maxEndTime) const
Get all EPG tags matching the given EPG id, min start time and max end time.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetEpgTagsByMinEndMaxStartTime (int iEpgID, const CDateTime &minEndTime, const CDateTime &maxStartTime) const
Get all EPG tags matching the given EPG id, min end time and max start time.
bool QueueDeleteEpgTagsByMinEndMaxStartTimeQuery (int iEpgID, const CDateTime &minEndTime, const CDateTime &maxStartTime)
Write the query to delete all EPG tags in range of given EPG id, min end time and max start time to db query queue. .
bool GetLastEpgScanTime (int iEpgId, CDateTime *lastScan) const
Get the last stored EPG scan time.
bool QueuePersistLastEpgScanTimeQuery (int iEpgId, const CDateTime &lastScanTime)
Write the query to update the last scan time for the given EPG to db query queue.
bool QueueDeleteLastEpgScanTimeQuery (const CPVREpg &table)
Write the query to delete the last scan time for the given EPG to db query queue.
int Persist (const CPVREpg &epg, bool bQueueWrite)
Persist an EPG table. It's entries are not persisted.
bool DeleteEpgTags (int iEpgId, const CDateTime &maxEndTime)
Erase all EPG tags with the given epg ID and an end time less than the given time.
bool DeleteEpgTags (int iEpgId)
Erase all EPG tags with the given epg ID.
bool QueueDeleteEpgTags (int iEpgId)
Queue the erase all EPG tags with the given epg ID.
bool QueuePersistQuery (const CPVREpgInfoTag &tag)
Write the query to persist the given EPG tag to db query queue.
int GetLastEPGId () const
Public Member Functions inherited from CDatabase
CDatabase ()
virtual ~CDatabase (void)
bool IsOpen ()
bool Compress (bool bForce=true)
void Interrupt ()
bool Open (const DatabaseSettings &db)
void BeginTransaction ()
virtual bool CommitTransaction ()
void RollbackTransaction ()
void CopyDB (const std::string &latestDb)
void DropAnalytics ()
std::string PrepareSQL (std::string strStmt,...) const
std::string GetSingleValue (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single value from a table.
std::string GetSingleValue (const std::string &query) const
std::string GetSingleValue (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single value from a query on a dataset.
int GetSingleValueInt (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single integer value from a table.
int GetSingleValueInt (const std::string &query) const
int GetSingleValueInt (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single integer value from a query on a dataset.
bool DeleteValues (const std::string &strTable, const Filter &filter=Filter())
Delete values from a table.
bool ExecuteQuery (const std::string &strQuery)
Execute a query that does not return any result. Note that if BeginMultipleExecute() has been called, the query will be queued until CommitMultipleExecute() is called.
bool ResultQuery (const std::string &strQuery) const
Execute a query that returns a result.
bool BeginMultipleExecute ()
Start a multiple execution queue. Any ExecuteQuery() function following this call will be queued rather than executed until CommitMultipleExecute() is performed. NOTE: Queries that rely on any queued execute query will not function as expected during this period!
bool CommitMultipleExecute ()
Commit the multiple execution queue to the database. Queries are performed within a transaction, and the transaction is rolled back should any one query fail.
bool QueueInsertQuery (const std::string &strQuery)
Put an INSERT or REPLACE query in the queue.
bool CommitInsertQueries ()
Commit all queries in the queue.
size_t GetInsertQueriesCount ()
Get the number of INSERT queries in the queue.
bool QueueDeleteQuery (const std::string &strQuery)
Put a DELETE query in the queue.
bool CommitDeleteQueries ()
Commit all queued DELETE queries.
size_t GetDeleteQueriesCount ()
Get the number of DELETE queries in the queue.
virtual bool GetFilter (CDbUrl &dbUrl, Filter &filter, SortDescription &sorting)
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl)
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl, SortDescription &sorting)
bool Connect (const std::string &dbName, const DatabaseSettings &db, bool create)
EPG searches methods
CCriticalSection m_critSection
std::vector< std::shared_ptr< CPVREpgSearchFilter > > GetSavedSearches (bool bRadio) const
Get all saved searches from the database.
std::shared_ptr< CPVREpgSearchFilter > GetSavedSearchById (bool bRadio, int iId) const
Get the saved search matching the given id.
bool Persist (CPVREpgSearchFilter &epgSearch)
Persist a search.
bool UpdateSavedSearchLastExecuted (const CPVREpgSearchFilter &epgSearch)
Update time last executed for the given search.
bool Delete (const CPVREpgSearchFilter &epgSearch)
Delete a saved search.
bool DeleteSavedSearches ()
Delete all saved searches.
void CreateTables () override
Create the EPG database tables.
void CreateAnalytics () override
Create the EPG database analytics.
void UpdateTables (int version) override
Update an old version of the database.
int GetMinSchemaVersion () const override
std::shared_ptr< CPVREpgInfoTag > CreateEpgTag (const std::unique_ptr< dbiplus::Dataset > &pDS) const
std::shared_ptr< CPVREpgSearchFilter > CreateEpgSearchFilter (bool bRadio, const std::unique_ptr< dbiplus::Dataset > &pDS) const
Additional Inherited Members
Protected Member Functions inherited from CDatabase
void Split (const std::string &strFileNameAndPath, std::string &strPath, std::string &strFileName)
bool CreateDatabase ()
Create database tables and analytics as needed. Calls CreateTables() and CreateAnalytics() on child classes.
int GetDBVersion ()
bool BuildSQL (const std::string &strQuery, const Filter &filter, std::string &strSQL) const
Protected Attributes inherited from CDatabase
bool m_sqlite
whether we use sqlite (defaults to true)
std::unique_ptr< dbiplus::Database > m_pDB
std::unique_ptr< dbiplus::Dataset > m_pDS
std::unique_ptr< dbiplus::Dataset > m_pDS2
const CProfileManager & m_profileManager
Constructor & Destructor Documentation
CPVREpgDatabase()
PVR::CPVREpgDatabase::CPVREpgDatabase () default
Create a new instance of the EPG database.
~CPVREpgDatabase()
PVR::CPVREpgDatabase::~CPVREpgDatabase () override default
Destroy this instance.
Member Function Documentation
Close()
void CPVREpgDatabase::Close () override virtual
Close the database.
Reimplemented from CDatabase.
References CDatabase::Close(), and m_critSection.
CreateAnalytics()
void CPVREpgDatabase::CreateAnalytics () override private virtual
Create the EPG database analytics.
Implements CDatabase.
References LOGDEBUG, LOGEPG, m_critSection, and CDatabase::m_pDS.
CreateEpgSearchFilter()
std::shared_ptr< CPVREpgSearchFilter > CPVREpgDatabase::CreateEpgSearchFilter (bool bRadio, const std::unique_ptr< dbiplus::Dataset > & pDS) const private
References end(), CDateTime::FromDBDateTime(), and CDatabase::m_pDS.
Referenced by GetSavedSearchById(), and GetSavedSearches().
CreateEpgTag()
std::shared_ptr< CPVREpgInfoTag > CPVREpgDatabase::CreateEpgTag (const std::unique_ptr< dbiplus::Dataset > & pDS) const private
References EPG_TAG_INVALID_UID, CDatabase::m_pDS, and CDateTime::SetFromW3CDate().
Referenced by GetAllEpgTags(), GetEpgTagByDatabaseID(), GetEpgTagByMaxEndTime(), GetEpgTagByMinStartTime(), GetEpgTagByStartTime(), GetEpgTagByUniqueBroadcastID(), GetEpgTags(), GetEpgTagsByMinEndMaxStartTime(), and GetEpgTagsByMinStartMaxEndTime().
CreateTables()
void CPVREpgDatabase::CreateTables () override private virtual
Create the EPG database tables.
Implements CDatabase.
References CLog::Log(), LOGDEBUG, LOGEPG, LOGINFO, m_critSection, and CDatabase::m_pDS.
Delete()
bool CPVREpgDatabase::Delete (const CPVREpgSearchFilter & epgSearch)
Delete a saved search.
Parameters
epgSearch The search.
Returns
True on success, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::DeleteValues(), PVR::CPVREpgSearchFilter::GetDatabaseId(), PVR::CPVREpgSearchFilter::GetTitle(), LOGDEBUG, LOGEPG, m_critSection, CDatabase::PrepareSQL(), and PVR::PVR_EPG_SEARCH_INVALID_DATABASE_ID.
DeleteEpg()
bool CPVREpgDatabase::DeleteEpg ()
Remove all EPG information from the database.
Returns
True if the EPG information was erased, false otherwise.
References CDatabase::DeleteValues(), LOGDEBUG, LOGEPG, and m_critSection.
DeleteEpgTags() [1/2]
bool CPVREpgDatabase::DeleteEpgTags (int iEpgId)
Erase all EPG tags with the given epg ID.
Parameters
iEpgId The ID of the EPG.
Returns
True if the entries were removed successfully, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::DeleteValues(), m_critSection, and CDatabase::PrepareSQL().
DeleteEpgTags() [2/2]
bool CPVREpgDatabase::DeleteEpgTags (int iEpgId, const CDateTime & maxEndTime)
Erase all EPG tags with the given epg ID and an end time less than the given time.
Parameters
iEpgId The ID of the EPG.
maxEndTime The maximum allowed end time.
Returns
True if the entries were removed successfully, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::DeleteValues(), CDateTime::GetAsTime(), m_critSection, and CDatabase::PrepareSQL().
DeleteSavedSearches()
bool CPVREpgDatabase::DeleteSavedSearches ()
Delete all saved searches.
Returns
True on success, false otherwise.
References CDatabase::DeleteValues(), LOGDEBUG, LOGEPG, and m_critSection.
GetAll()
std::vector< std::shared_ptr< CPVREpg > > CPVREpgDatabase::GetAll ()
Get all EPG tables from the database. Does not get the EPG tables' entries.
Returns
The entries.
References LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetAllEpgTags()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVREpgDatabase::GetAllEpgTags (int iEpgID) const
Get all tags for a given EPG id.
Parameters
iEpgID The ID of the EPG.
Returns
The entries.
References CreateEpgTag(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), CDatabase::ResultQuery(), and tags.
GetAllIconPaths()
bool CPVREpgDatabase::GetAllIconPaths (int iEpgID, std::vector< std::string > & paths) const
Get all icon paths for a given EPG id.
Parameters
iEpgID The ID of the EPG.
path The paths returned.
Returns
True on success, false otherwise.
References LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetAllParentalRatingIconPaths()
bool CPVREpgDatabase::GetAllParentalRatingIconPaths (int iEpgID, std::vector< std::string > & paths) const
Get all parental rating icon paths for a given EPG id.
Parameters
iEpgID The ID of the EPG.
path The paths returned.
Returns
True on success, false otherwise.
References LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetBaseDBName()
const char * PVR::CPVREpgDatabase::GetBaseDBName () const inline override virtual
Get the default sqlite database filename.
Returns
The default filename.
Implements CDatabase.
GetEpgTagByDatabaseID()
std::shared_ptr< CPVREpgInfoTag > CPVREpgDatabase::GetEpgTagByDatabaseID (int iEpgID, int iDatabaseId) const
Get an EPG tag given its EPG id and database ID.
Parameters
iEpgID The ID of the EPG for the tag to get.
iDatabaseId The database ID for the tag to get.
Returns
The tag or nullptr, if not found.
References CreateEpgTag(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetEpgTagByMaxEndTime()
std::shared_ptr< CPVREpgInfoTag > CPVREpgDatabase::GetEpgTagByMaxEndTime (int iEpgID, const CDateTime & maxEndTime) const
Get the next EPG tag matching the given EPG id and max end time.
Parameters
iEpgID The ID of the EPG for the tag to get.
maxEndTime The max end time for the tag to get.
Returns
The tag or nullptr, if not found.
References CreateEpgTag(), CDateTime::GetAsDBDateTime(), CDateTime::GetAsTime(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetEpgTagByMinStartTime()
std::shared_ptr< CPVREpgInfoTag > CPVREpgDatabase::GetEpgTagByMinStartTime (int iEpgID, const CDateTime & minStartTime) const
Get the next EPG tag matching the given EPG id and min start time.
Parameters
iEpgID The ID of the EPG for the tag to get.
minStartTime The min start time for the tag to get.
Returns
The tag or nullptr, if not found.
References CreateEpgTag(), CDateTime::GetAsDBDateTime(), CDateTime::GetAsTime(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetEpgTagByStartTime()
std::shared_ptr< CPVREpgInfoTag > CPVREpgDatabase::GetEpgTagByStartTime (int iEpgID, const CDateTime & startTime) const
Get an EPG tag given its EPG ID and start time.
Parameters
iEpgID The ID of the EPG for the tag to get.
startTime The start time for the tag to get.
Returns
The tag or nullptr, if not found.
References CreateEpgTag(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetEpgTagByUniqueBroadcastID()
std::shared_ptr< CPVREpgInfoTag > CPVREpgDatabase::GetEpgTagByUniqueBroadcastID (int iEpgID, unsigned int iUniqueBroadcastId) const
Get an EPG tag given its EPG id and unique broadcast ID.
Parameters
iEpgID The ID of the EPG for the tag to get.
iUniqueBroadcastId The unique broadcast ID for the tag to get.
Returns
The tag or nullptr, if not found.
References CreateEpgTag(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetEpgTags()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVREpgDatabase::GetEpgTags (const PVREpgSearchData & searchData) const
Get all EPG tags matching the given search criteria.
Parameters
searchData The search criteria.
Returns
The matching tags.
References CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), CreateEpgTag(), EPG_EVENT_CONTENTMASK_MOVIEDRAMA, EPG_EVENT_CONTENTMASK_USERDEFINED, PVR::EPG_SEARCH_UNSET, CDateTime::GetAsTime(), CDateTime::IsValid(), LOGERROR, PVR::PVREpgSearchData::m_bIgnoreFinishedBroadcasts, PVR::PVREpgSearchData::m_bIgnoreFutureBroadcasts, PVR::PVREpgSearchData::m_bIncludeUnknownGenres, PVR::PVREpgSearchData::m_bSearchInDescription, m_critSection, PVR::PVREpgSearchData::m_endAnyTime, PVR::PVREpgSearchData::m_endDateTime, PVR::PVREpgSearchData::m_iGenreType, CDatabase::m_pDS, PVR::PVREpgSearchData::m_startAnyTime, PVR::PVREpgSearchData::m_startDateTime, PVR::PVREpgSearchData::m_strSearchTerm, CDatabase::PrepareSQL(), and tags.
GetEpgTagsByMinEndMaxStartTime()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVREpgDatabase::GetEpgTagsByMinEndMaxStartTime (int iEpgID, const CDateTime & minEndTime, const CDateTime & maxStartTime) const
Get all EPG tags matching the given EPG id, min end time and max start time.
Parameters
iEpgID The ID of the EPG for the tags to get.
minEndTime The min end time for the tags to get.
maxStartTime The max start time for the tags to get.
Returns
The tags or empty vector, if no tags were found.
References CreateEpgTag(), CDateTime::GetAsDBDateTime(), CDateTime::GetAsTime(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), CDatabase::ResultQuery(), and tags.
GetEpgTagsByMinStartMaxEndTime()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVREpgDatabase::GetEpgTagsByMinStartMaxEndTime (int iEpgID, const CDateTime & minStartTime, const CDateTime & maxEndTime) const
Get all EPG tags matching the given EPG id, min start time and max end time.
Parameters
iEpgID The ID of the EPG for the tags to get.
minStartTime The min start time for the tags to get.
maxEndTime The max end time for the tags to get.
Returns
The tags or empty vector, if no tags were found.
References CreateEpgTag(), CDateTime::GetAsDBDateTime(), CDateTime::GetAsTime(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), CDatabase::ResultQuery(), and tags.
GetFirstAndLastEPGDate()
std::pair< CDateTime, CDateTime > CPVREpgDatabase::GetFirstAndLastEPGDate () const
Get the start and end time across all EPGs.
Returns
The times; first: start time, second: end time.
References CDatabase::GetSingleValue(), m_critSection, and CDatabase::PrepareSQL().
GetLastEndTime()
CDateTime CPVREpgDatabase::GetLastEndTime (int iEpgID) const
Get the end time of the last tag in this EPG.
Parameters
iEpgID The ID of the EPG.
Returns
The time.
References CDatabase::GetSingleValue(), m_critSection, and CDatabase::PrepareSQL().
GetLastEPGId()
int CPVREpgDatabase::GetLastEPGId () const
Returns
Last EPG id in the database
References CDatabase::GetSingleValue(), m_critSection, and CDatabase::PrepareSQL().
GetLastEpgScanTime()
bool CPVREpgDatabase::GetLastEpgScanTime (int iEpgId, CDateTime * lastScan) const
Get the last stored EPG scan time.
Parameters
iEpgId The table to update the time for. Use 0 for a global value.
lastScan The last scan time or -1 if it wasn't found.
Returns
True if the time was fetched successfully, false otherwise.
References CDatabase::GetSingleValue(), m_critSection, CDatabase::PrepareSQL(), CDateTime::SetFromDBDateTime(), and CDateTime::SetValid().
GetMaxEndTime()
CDateTime CPVREpgDatabase::GetMaxEndTime (int iEpgID, const CDateTime & maxEnd) const
Get the end time of the first tag with an end time less than the given max time.
Parameters
iEpgID The ID of the EPG.
maxEnd The mx end time.
Returns
The time.
References CDateTime::GetAsTime(), CDatabase::GetSingleValue(), m_critSection, CDatabase::PrepareSQL(), and t.
GetMinSchemaVersion()
int PVR::CPVREpgDatabase::GetMinSchemaVersion () const inline override private virtual
Reimplemented from CDatabase.
GetMinStartTime()
CDateTime CPVREpgDatabase::GetMinStartTime (int iEpgID, const CDateTime & minStart) const
Get the start time of the first tag with a start time greater than the given min time.
Parameters
iEpgID The ID of the EPG.
minStart The min start time.
Returns
The time.
References CDateTime::GetAsTime(), CDatabase::GetSingleValue(), m_critSection, CDatabase::PrepareSQL(), and t.
GetSavedSearchById()
std::shared_ptr< CPVREpgSearchFilter > CPVREpgDatabase::GetSavedSearchById (bool bRadio, int iId) const
Get the saved search matching the given id.
Parameters
bRadio Whether to fetch a TV or radio saved search.
iId The id.
Returns
The saved search or nullptr if not found.
References CreateEpgSearchFilter(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetSavedSearches()
std::vector< std::shared_ptr< CPVREpgSearchFilter > > CPVREpgDatabase::GetSavedSearches (bool bRadio) const
Get all saved searches from the database.
Parameters
bRadio Whether to fetch saved searches for radio or TV.
Returns
The searches.
References CreateEpgSearchFilter(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetSchemaVersion()
int PVR::CPVREpgDatabase::GetSchemaVersion () const inline override virtual
Get the minimal database version that is required to operate correctly.
Returns
The minimal database version.
Implements CDatabase.
HasTags()
bool CPVREpgDatabase::HasTags (int iEpgID) const
Check whether this EPG has any tags.
Parameters
iEpgID The ID of the EPG.
Returns
True in case there are tags, false otherwise.
References CDatabase::GetSingleValue(), m_critSection, and CDatabase::PrepareSQL().
Lock()
void CPVREpgDatabase::Lock ()
Lock the database.
References m_critSection.
Open()
bool CPVREpgDatabase::Open () override virtual
Open the database.
Returns
True if it was opened successfully, false otherwise.
Reimplemented from CDatabase.
References CServiceBroker::GetSettingsComponent(), m_critSection, and CDatabase::Open().
Persist() [1/2]
int CPVREpgDatabase::Persist (const CPVREpg & epg, bool bQueueWrite)
Persist an EPG table. It's entries are not persisted.
Parameters
epg The table to persist.
bQueueWrite If true, don't execute the query immediately but queue it.
Returns
The database ID of this entry or 0 if bQueueWrite is false and the query was queued.
References PVR::CPVREpg::EpgID(), CDatabase::ExecuteQuery(), m_critSection, CDatabase::m_pDS, PVR::CPVREpg::Name(), CDatabase::PrepareSQL(), CDatabase::QueueInsertQuery(), and PVR::CPVREpg::ScraperName().
Persist() [2/2]
bool CPVREpgDatabase::Persist (CPVREpgSearchFilter & epgSearch)
Persist a search.
Parameters
epgSearch The search.
Returns
True on success, false otherwise.
References CDatabase::ExecuteQuery(), CDateTime::GetAsDBDateTime(), PVR::CPVREpgSearchFilter::GetChannelGroupID(), PVR::CPVREpgSearchFilter::GetChannelUID(), PVR::CPVREpgSearchFilter::GetClientID(), PVR::CPVREpgSearchFilter::GetDatabaseId(), PVR::CPVREpgSearchFilter::GetEndDateTime(), PVR::CPVREpgSearchFilter::GetGenreType(), PVR::CPVREpgSearchFilter::GetIconPath(), PVR::CPVREpgSearchFilter::GetLastExecutedDateTime(), PVR::CPVREpgSearchFilter::GetMaximumDuration(), PVR::CPVREpgSearchFilter::GetMinimumDuration(), PVR::CPVREpgSearchFilter::GetSearchTerm(), PVR::CPVREpgSearchFilter::GetStartDateTime(), PVR::CPVREpgSearchFilter::GetTitle(), PVR::CPVREpgSearchFilter::IsCaseSensitive(), PVR::CPVREpgSearchFilter::IsEndAnyTime(), PVR::CPVREpgSearchFilter::IsFreeToAirOnly(), PVR::CPVREpgSearchFilter::IsRadio(), PVR::CPVREpgSearchFilter::IsStartAnyTime(), CDateTime::IsValid(), m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), PVR::PVR_EPG_SEARCH_INVALID_DATABASE_ID, PVR::CPVREpgSearchFilter::SetChanged(), PVR::CPVREpgSearchFilter::SetDatabaseId(), PVR::CPVREpgSearchFilter::ShouldIgnoreFinishedBroadcasts(), PVR::CPVREpgSearchFilter::ShouldIgnoreFutureBroadcasts(), PVR::CPVREpgSearchFilter::ShouldIgnorePresentRecordings(), PVR::CPVREpgSearchFilter::ShouldIgnorePresentTimers(), PVR::CPVREpgSearchFilter::ShouldIncludeUnknownGenres(), PVR::CPVREpgSearchFilter::ShouldRemoveDuplicates(), and PVR::CPVREpgSearchFilter::ShouldSearchInDescription().
QueueDeleteEpgQuery()
bool CPVREpgDatabase::QueueDeleteEpgQuery (const CPVREpg & table)
Queue deletionof an EPG table.
Parameters
tag The table to queue for deletion.
Returns
True on success, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), LOGERROR, m_critSection, CDatabase::PrepareSQL(), CDatabase::QueueDeleteQuery(), and table.
QueueDeleteEpgTags()
bool CPVREpgDatabase::QueueDeleteEpgTags (int iEpgId)
Queue the erase all EPG tags with the given epg ID.
Parameters
iEpgId The ID of the EPG.
Returns
True if the entries were queued successfully, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), m_critSection, CDatabase::PrepareSQL(), and CDatabase::QueueDeleteQuery().
QueueDeleteEpgTagsByMinEndMaxStartTimeQuery()
bool CPVREpgDatabase::QueueDeleteEpgTagsByMinEndMaxStartTimeQuery (int iEpgID, const CDateTime & minEndTime, const CDateTime & maxStartTime)
Write the query to delete all EPG tags in range of given EPG id, min end time and max start time to db query queue. .
Parameters
iEpgID The ID of the EPG for the tags to delete.
minEndTime The min end time for the tags to delete.
maxStartTime The max start time for the tags to delete.
Returns
True if it was removed or queued successfully, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), CDateTime::GetAsTime(), m_critSection, CDatabase::PrepareSQL(), and CDatabase::QueueDeleteQuery().
QueueDeleteLastEpgScanTimeQuery()
bool CPVREpgDatabase::QueueDeleteLastEpgScanTimeQuery (const CPVREpg & table)
Write the query to delete the last scan time for the given EPG to db query queue.
Parameters
iEpgId The table to delete the time for.
Returns
True on success, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), LOGERROR, m_critSection, CDatabase::PrepareSQL(), CDatabase::QueueDeleteQuery(), and table.
QueueDeleteTagQuery()
bool CPVREpgDatabase::QueueDeleteTagQuery (const CPVREpgInfoTag & tag)
Write the query to delete the given EPG tag to db query queue.
Parameters
tag The EPG tag to remove.
Returns
True on success, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), m_critSection, CDatabase::PrepareSQL(), and CDatabase::QueueDeleteQuery().
QueuePersistLastEpgScanTimeQuery()
bool CPVREpgDatabase::QueuePersistLastEpgScanTimeQuery (int iEpgId, const CDateTime & lastScanTime)
Write the query to update the last scan time for the given EPG to db query queue.
Parameters
iEpgId The table to update the time for.
lastScanTime The time to write to the database.
Returns
True on success, false otherwise.
References CDateTime::GetAsDBDateTime(), m_critSection, CDatabase::PrepareSQL(), and CDatabase::QueueInsertQuery().
QueuePersistQuery()
bool CPVREpgDatabase::QueuePersistQuery (const CPVREpgInfoTag & tag)
Write the query to persist the given EPG tag to db query queue.
Parameters
tag The tag to persist.
Returns
True on success, false otherwise.
References LOGERROR, m_critSection, CDatabase::PrepareSQL(), and CDatabase::QueueInsertQuery().
Unlock()
void CPVREpgDatabase::Unlock ()
Unlock the database.
References m_critSection.
UpdateSavedSearchLastExecuted()
bool CPVREpgDatabase::UpdateSavedSearchLastExecuted (const CPVREpgSearchFilter & epgSearch)
Update time last executed for the given search.
Parameters
epgSearch The search.
Returns
True on success, false otherwise.
References CDatabase::ExecuteQuery(), CDateTime::GetAsDBDateTime(), PVR::CPVREpgSearchFilter::GetDatabaseId(), PVR::CPVREpgSearchFilter::GetLastExecutedDateTime(), m_critSection, CDatabase::PrepareSQL(), and PVR::PVR_EPG_SEARCH_INVALID_DATABASE_ID.
UpdateTables()
void CPVREpgDatabase::UpdateTables (int version) override private virtual
Update an old version of the database.
Parameters
version The version to update the database from.
Reimplemented from CDatabase.
References CServiceBroker::GetSettingsComponent(), m_critSection, and CDatabase::m_pDS.
Member Data Documentation
m_critSection
CCriticalSection PVR::CPVREpgDatabase::m_critSection mutable private
Referenced by Close(), CreateAnalytics(), CreateTables(), Delete(), DeleteEpg(), DeleteEpgTags(), DeleteEpgTags(), DeleteSavedSearches(), GetAll(), GetAllEpgTags(), GetAllIconPaths(), GetAllParentalRatingIconPaths(), GetEpgTagByDatabaseID(), GetEpgTagByMaxEndTime(), GetEpgTagByMinStartTime(), GetEpgTagByStartTime(), GetEpgTagByUniqueBroadcastID(), GetEpgTags(), GetEpgTagsByMinEndMaxStartTime(), GetEpgTagsByMinStartMaxEndTime(), GetFirstAndLastEPGDate(), GetLastEndTime(), GetLastEPGId(), GetLastEpgScanTime(), GetMaxEndTime(), GetMinStartTime(), GetSavedSearchById(), GetSavedSearches(), HasTags(), Lock(), Open(), Persist(), Persist(), QueueDeleteEpgQuery(), QueueDeleteEpgTags(), QueueDeleteEpgTagsByMinEndMaxStartTimeQuery(), QueueDeleteLastEpgScanTimeQuery(), QueueDeleteTagQuery(), QueuePersistLastEpgScanTimeQuery(), QueuePersistQuery(), Unlock(), UpdateSavedSearchLastExecuted(), and UpdateTables().
The documentation for this class was generated from the following files:
EpgDatabase.h
EpgDatabase.cpp