Kodi Documentation: AddonToKodiFuncTable_kodi_gui_control_image Struct Reference
AddonToKodiFuncTable_kodi_gui_control_image Struct Reference
#include <image.h>
Public Attributes
void(* set_visible)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
void(* set_filename)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *filename, bool use_cache)
void(* set_color_diffuse)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, uint32_t color_diffuse)
Member Data Documentation
set_color_diffuse
void(* AddonToKodiFuncTable_kodi_gui_control_image::set_color_diffuse) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, uint32_t color_diffuse)
Referenced by ADDON::Interface_GUIControlImage::Init().
set_filename
void(* AddonToKodiFuncTable_kodi_gui_control_image::set_filename) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *filename, bool use_cache)
Referenced by ADDON::Interface_GUIControlImage::Init().
set_visible
void(* AddonToKodiFuncTable_kodi_gui_control_image::set_visible) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
Referenced by ADDON::Interface_GUIControlImage::Init().
The documentation for this struct was generated from the following file:
kodi-dev-kit/include/kodi/c-api/gui/controls/image.h