Kodi Documentation: AddonToKodiFuncTable_Visualization Struct Reference
AddonToKodiFuncTable_Visualization Struct Reference
#include <visualization.h>
Public Attributes
void(* get_properties)(const KODI_HANDLE hdl, struct KODI_ADDON_VISUALIZATION_PROPS *props)
void(* transfer_preset)(const KODI_HANDLE hdl, const char *preset)
void(* clear_presets)(const KODI_HANDLE hdl)
Member Data Documentation
clear_presets
void(* AddonToKodiFuncTable_Visualization::clear_presets) (const KODI_HANDLE hdl)
Referenced by KODI::ADDONS::CVisualization::CVisualization().
get_properties
void(* AddonToKodiFuncTable_Visualization::get_properties) (const KODI_HANDLE hdl, struct KODI_ADDON_VISUALIZATION_PROPS *props)
Referenced by KODI::ADDONS::CVisualization::CVisualization().
transfer_preset
void(* AddonToKodiFuncTable_Visualization::transfer_preset) (const KODI_HANDLE hdl, const char *preset)
Referenced by kodi::addon::CInstanceVisualization::ADDON_get_presets(), and KODI::ADDONS::CVisualization::CVisualization().
The documentation for this struct was generated from the following file:
kodi-dev-kit/include/kodi/c-api/addon-instance/Visualization.h