Kodi Documentation: CBitstream Class Reference
CBitstream Class Reference
Public Member Functions
CBitstream (uint8_t *data, int bits)
unsigned int readBits (int num)
unsigned int readGolombUE (int maxbits=32)
Private Attributes
uint8_t * m_data
int m_offset
int m_len
bool m_error
Constructor & Destructor Documentation
CBitstream()
CBitstream::CBitstream (uint8_t * data, int bits) inline
References data(), m_data, m_error, m_len, and m_offset.
Member Function Documentation
readBits()
unsigned int CBitstream::readBits (int num) inline
References m_data, m_error, m_len, and m_offset.
Referenced by readGolombUE().
readGolombUE()
unsigned int CBitstream::readGolombUE (int maxbits = 32) inline
References readBits().
Referenced by CDVDDemuxCC::Read().
Member Data Documentation
m_data
uint8_t* CBitstream::m_data private
Referenced by CBitstream(), and readBits().
m_error
bool CBitstream::m_error private
Referenced by CBitstream(), and readBits().
m_len
int CBitstream::m_len private
Referenced by CBitstream(), and readBits().
m_offset
int CBitstream::m_offset private
Referenced by CBitstream(), and readBits().
The documentation for this class was generated from the following file:
DVDDemuxCC.cpp