Kodi Documentation: PVR::CPVRChannelSwitchingInputHandler Class Reference
PVR::CPVRChannelSwitchingInputHandler Class Reference
#include <PVRGUIActionsChannels.h>
Public Member Functions
void GetChannelNumbers (std::vector< std::string > &channelNumbers) override
Get the currently available channel numbers.
void AppendChannelNumberCharacter (char cCharacter) override
Appends a channel number character.
void OnInputDone () override
This method gets called after the channel number input timer has expired.
Public Member Functions inherited from PVR::CPVRChannelNumberInputHandler
CPVRChannelNumberInputHandler ()
CPVRChannelNumberInputHandler (int iDelay, int iMaxDigits=CHANNEL_NUMBER_INPUT_MAX_DIGITS)
ctor.
~CPVRChannelNumberInputHandler () override=default
CEventStream< PVRChannelNumberInputChangedEvent > & Events ()
Get the events available for CEventStream.
void OnTimeout () override
bool HasChannelNumber () const
Check whether a channel number was entered.
std::string GetChannelNumberLabel () const
Get the currently entered channel number as a formatted string.
bool CheckInputAndExecuteAction ()
If a number was entered, execute the associated action.
Private Member Functions
void SwitchToChannel (const CPVRChannelNumber &channelNumber)
Switch to the channel with the given number.
void SwitchToPreviousChannel ()
Switch to the previously played channel.
Additional Inherited Members
Static Public Attributes inherited from PVR::CPVRChannelNumberInputHandler
static const int CHANNEL_NUMBER_INPUT_MAX_DIGITS = 5
Protected Member Functions inherited from PVR::CPVRChannelNumberInputHandler
CPVRChannelNumber GetChannelNumber () const
Get the currently entered channel number.
size_t GetCurrentDigitCount () const
Get the currently entered number of digits.
Protected Attributes inherited from PVR::CPVRChannelNumberInputHandler
CCriticalSection m_mutex
Member Function Documentation
AppendChannelNumberCharacter()
void CPVRChannelSwitchingInputHandler::AppendChannelNumberCharacter (char cCharacter) override virtual
Appends a channel number character.
Parameters
cCharacter The character to append. value must be CPVRChannelNumber::SEPARATOR ('.') or any char in the range from '0' to '9'.
Reimplemented from PVR::CPVRChannelNumberInputHandler.
References PVR::CPVRChannelNumberInputHandler::AppendChannelNumberCharacter(), PVR::CPVRChannelNumberInputHandler::GetCurrentDigitCount(), and SwitchToPreviousChannel().
GetChannelNumbers()
void CPVRChannelSwitchingInputHandler::GetChannelNumbers (std::vector< std::string > & channelNumbers) override virtual
Get the currently available channel numbers.
Parameters
channelNumbers The list to fill with the channel numbers.
Implements PVR::CPVRChannelNumberInputHandler.
References PVR::CPVRManager::ChannelGroups(), CServiceBroker::GetPVRManager(), and PVR::CPVRManager::PlaybackState().
OnInputDone()
void CPVRChannelSwitchingInputHandler::OnInputDone () override virtual
This method gets called after the channel number input timer has expired.
Implements PVR::CPVRChannelNumberInputHandler.
References PVR::CPVRChannelNumber::GetChannelNumber(), PVR::CPVRChannelNumberInputHandler::GetChannelNumber(), and SwitchToChannel().
SwitchToChannel()
void CPVRChannelSwitchingInputHandler::SwitchToChannel (const CPVRChannelNumber & channelNumber) private
Switch to the channel with the given number.
Parameters
channelNumber the channel number
References PVR::CPVRManager::ChannelGroups(), CServiceBroker::GetPVRManager(), PVR::CPVRChannelNumber::IsValid(), and PVR::CPVRManager::PlaybackState().
Referenced by OnInputDone().
SwitchToPreviousChannel()
void CPVRChannelSwitchingInputHandler::SwitchToPreviousChannel () private
Switch to the previously played channel.
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::PlaybackState().
Referenced by AppendChannelNumberCharacter().
The documentation for this class was generated from the following files:
PVRGUIActionsChannels.h
PVRGUIActionsChannels.cpp