Kodi Documentation: CMusicFileItemListModifier Class Reference
CMusicFileItemListModifier Class Reference
#include <MusicFileItemListModifier.h>
Public Member Functions
CMusicFileItemListModifier ()=default
~CMusicFileItemListModifier () override=default
bool CanModify (const CFileItemList &items) const override
bool Modify (CFileItemList &items) const override
Public Member Functions inherited from IFileItemListModifier
IFileItemListModifier ()=default
virtual ~IFileItemListModifier ()=default
Static Private Member Functions
static void AddQueuingFolder (CFileItemList &items)
Constructor & Destructor Documentation
CMusicFileItemListModifier()
CMusicFileItemListModifier::CMusicFileItemListModifier () default
~CMusicFileItemListModifier()
CMusicFileItemListModifier::~CMusicFileItemListModifier () override default
Member Function Documentation
AddQueuingFolder()
void CMusicFileItemListModifier::AddQueuingFolder (CFileItemList & items) static private
References CFileItemList::Add(), CFileItemList::AddFront(), CDbUrl::AppendPath(), CDbUrl::FromString(), g_localizeStrings, CLocalizeStrings::Get(), CFileItemList::GetObjectCount(), CDbUrl::GetOptions(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), CDbUrl::HasOption(), KODI::MUSIC::IsMusicDb(), CFileItem::IsParentFolder(), XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ARTIST, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_DISC, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_OVERVIEW, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), CSettings::SETTING_MUSICLIBRARY_SHOWALLITEMS, CFileItemList::Size(), SortSpecialOnBottom, SortSpecialOnTop, and CDbUrl::ToString().
Referenced by Modify().
CanModify()
bool CMusicFileItemListModifier::CanModify (const CFileItemList & items) const override virtual
Implements IFileItemListModifier.
References KODI::MUSIC::IsMusicDb().
Modify()
bool CMusicFileItemListModifier::Modify (CFileItemList & items) const override virtual
Implements IFileItemListModifier.
References AddQueuingFolder().
The documentation for this class was generated from the following files:
MusicFileItemListModifier.h
MusicFileItemListModifier.cpp