Kodi Documentation: anonymous_namespace{TestDefaultKeyboardTranslator.cpp} Namespace Reference
anonymous_namespace{TestDefaultKeyboardTranslator.cpp} Namespace Reference
Functions
KEYBOARD::XBMCKey GetKeycode (KEYBOARD::XBMCKey keysym, const ControllerPtr &controller, unsigned int &count)
const GAME::ControllerPtr GetController ()
Function Documentation
GetController()
const GAME::ControllerPtr anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetController ()
References ADDON::CHOICE_YES, DEFAULT_KEYBOARD_ID, EXPECT_EQ(), EXPECT_NE(), EXPECT_TRUE(), ADDON::GAME_CONTROLLER, ADDON::CAddonMgr::GetAddon(), and CServiceBroker::GetAddonMgr().
Referenced by TEST().
GetKeycode()
KEYBOARD::XBMCKey anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetKeycode (KEYBOARD::XBMCKey keysym, const ControllerPtr & controller, unsigned int & count)
References KODI::GAME::CDefaultKeyboardTranslator::TranslateKeycode().
Referenced by TEST().