Kodi Documentation: anonymous_namespace{MusicUtils.cpp} Namespace Reference
anonymous_namespace{MusicUtils.cpp} Namespace Reference
Classes
class CAsyncGetItemsForPlaylist
Functions
SortDescription GetSortDescription (const CGUIViewState &state, const CFileItemList &items)
void ShowToastNotification (const CFileItem &item, int titleId)
std::string GetMusicDbItemPath (const CFileItem &item)
void AddItemToPlayListAndPlay (const std::shared_ptr< CFileItem > &itemToQueue, const std::shared_ptr< CFileItem > &itemToPlay, const std::string &player)
Function Documentation
AddItemToPlayListAndPlay()
void anonymous_namespace{MusicUtils.cpp}::AddItemToPlayListAndPlay (const std::shared_ptr< CFileItem > & itemToQueue, const std::shared_ptr< CFileItem > & itemToPlay, const std::string & player)
References KODI::PLAYLIST::CPlayList::FindOrder(), MUSIC_UTILS::GetItemsForPlayList(), CServiceBroker::GetPlaylistPlayer(), and KODI::PLAYLIST::CPlayList::Swap().
GetMusicDbItemPath()
std::string anonymous_namespace{MusicUtils.cpp}::GetMusicDbItemPath (const CFileItem & item)
References CVariant::asString(), CFileItem::GetPath(), CGUIListItem::GetProperty(), and URIUtils::IsMusicDb().
GetSortDescription()
SortDescription anonymous_namespace{MusicUtils.cpp}::GetSortDescription (const CGUIViewState & state, const CFileItemList & items)
References CGUIViewState::GetSortDescriptions(), CGUIViewState::GetSortMethod(), SortDescription::sortBy, SortByArtistThenYear, SortByNone, SortByTrackNumber, SortDescription::sortOrder, and SortOrderAscending.
Referenced by anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist().
ShowToastNotification()
void anonymous_namespace{MusicUtils.cpp}::ShowToastNotification (const CFileItem & item, int titleId)
References g_localizeStrings, CLocalizeStrings::Get(), CMediaTypes::GetCapitalLocalization(), CGUIListItem::GetLabel(), CFileItem::GetMusicInfoTag(), MUSIC_INFO::CMusicInfoTag::GetTitle(), MUSIC_INFO::CMusicInfoTag::GetType(), CFileItem::HasMusicInfoTag(), CGUIDialogKaiToast::Info, and CGUIDialogKaiToast::QueueNotification().