Kodi Documentation: PVR::CPVRGUITimesInfo Class Reference
PVR::CPVRGUITimesInfo Class Reference
#include <PVRGUITimesInfo.h>
Public Member Functions
CPVRGUITimesInfo ()
virtual ~CPVRGUITimesInfo ()=default
void Reset ()
void Update ()
std::string GetTimeshiftStartTime (TIME_FORMAT format) const
std::string GetTimeshiftEndTime (TIME_FORMAT format) const
std::string GetTimeshiftPlayTime (TIME_FORMAT format) const
std::string GetTimeshiftOffset (TIME_FORMAT format) const
std::string GetTimeshiftProgressDuration (TIME_FORMAT format) const
std::string GetTimeshiftProgressStartTime (TIME_FORMAT format) const
std::string GetTimeshiftProgressEndTime (TIME_FORMAT format) const
std::string GetEpgEventDuration (const std::shared_ptr< const CPVREpgInfoTag > &epgTag, TIME_FORMAT format) const
std::string GetEpgEventElapsedTime (const std::shared_ptr< const CPVREpgInfoTag > &epgTag, TIME_FORMAT format) const
std::string GetEpgEventRemainingTime (const std::shared_ptr< const CPVREpgInfoTag > &epgTag, TIME_FORMAT format) const
std::string GetEpgEventFinishTime (const std::shared_ptr< const CPVREpgInfoTag > &epgTag, TIME_FORMAT format) const
std::string GetEpgEventSeekTime (int iSeekSize, TIME_FORMAT format) const
int GetTimeshiftProgress () const
int GetTimeshiftProgressDuration () const
int GetTimeshiftProgressPlayPosition () const
int GetTimeshiftProgressEpgStart () const
int GetTimeshiftProgressEpgEnd () const
int GetTimeshiftProgressBufferStart () const
int GetTimeshiftProgressBufferEnd () const
int GetEpgEventDuration (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
int GetEpgEventProgress (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
bool IsTimeshifting () const
Private Member Functions
void UpdatePlayingTag ()
void UpdateTimeshiftData ()
void UpdateTimeshiftProgressData ()
int GetElapsedTime () const
int GetRemainingTime (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
Static Private Member Functions
static std::string TimeToTimeString (time_t datetime, TIME_FORMAT format, bool withSeconds)
Private Attributes
CCriticalSection m_critSection
std::shared_ptr< const CPVREpgInfoTag > m_playingEpgTag
std::shared_ptr< const CPVRChannel > m_playingChannel
time_t m_iStartTime
unsigned int m_iDuration
time_t m_iTimeshiftStartTime
time_t m_iTimeshiftEndTime
time_t m_iTimeshiftPlayTime
int64_t m_iTimeshiftOffset
time_t m_iTimeshiftProgressStartTime
time_t m_iTimeshiftProgressEndTime
unsigned int m_iTimeshiftProgressDuration
Constructor & Destructor Documentation
CPVRGUITimesInfo()
CPVRGUITimesInfo::CPVRGUITimesInfo ()
References Reset().
~CPVRGUITimesInfo()
virtual PVR::CPVRGUITimesInfo::~CPVRGUITimesInfo () virtual default
Member Function Documentation
GetElapsedTime()
int CPVRGUITimesInfo::GetElapsedTime () const private
References m_critSection, m_iTimeshiftPlayTime, m_iTimeshiftStartTime, and m_playingEpgTag.
Referenced by GetEpgEventElapsedTime(), GetEpgEventProgress(), GetEpgEventSeekTime(), and GetRemainingTime().
GetEpgEventDuration() [1/2]
int CPVRGUITimesInfo::GetEpgEventDuration (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const
References m_critSection, m_iDuration, and m_playingEpgTag.
GetEpgEventDuration() [2/2]
std::string CPVRGUITimesInfo::GetEpgEventDuration (const std::shared_ptr< const CPVREpgInfoTag > & epgTag, TIME_FORMAT format) const
References GetEpgEventDuration(), and m_critSection.
Referenced by GetEpgEventDuration(), PVR::CPVRGUIInfo::GetPVRInt(), and PVR::CPVRGUIInfo::GetPVRLabel().
GetEpgEventElapsedTime()
std::string CPVRGUITimesInfo::GetEpgEventElapsedTime (const std::shared_ptr< const CPVREpgInfoTag > & epgTag, TIME_FORMAT format) const
References GetElapsedTime(), m_critSection, and m_playingEpgTag.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetEpgEventFinishTime()
std::string CPVRGUITimesInfo::GetEpgEventFinishTime (const std::shared_ptr< const CPVREpgInfoTag > & epgTag, TIME_FORMAT format) const
References CDateTime::GetAsLocalizedTime(), CDateTime::GetCurrentDateTime(), and GetRemainingTime().
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetEpgEventProgress()
int CPVRGUITimesInfo::GetEpgEventProgress (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const
References GetElapsedTime(), m_critSection, m_iDuration, and m_playingEpgTag.
Referenced by PVR::CPVRGUIInfo::GetPVRInt().
GetEpgEventRemainingTime()
std::string CPVRGUITimesInfo::GetEpgEventRemainingTime (const std::shared_ptr< const CPVREpgInfoTag > & epgTag, TIME_FORMAT format) const
References GetRemainingTime(), and m_critSection.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetEpgEventSeekTime()
std::string CPVRGUITimesInfo::GetEpgEventSeekTime (int iSeekSize, TIME_FORMAT format) const
References GetElapsedTime().
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetRemainingTime()
int CPVRGUITimesInfo::GetRemainingTime (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const private
References GetElapsedTime(), m_critSection, m_iDuration, and m_playingEpgTag.
Referenced by GetEpgEventFinishTime(), and GetEpgEventRemainingTime().
GetTimeshiftEndTime()
std::string CPVRGUITimesInfo::GetTimeshiftEndTime (TIME_FORMAT format) const
References m_critSection, m_iTimeshiftEndTime, and TimeToTimeString().
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetTimeshiftOffset()
std::string CPVRGUITimesInfo::GetTimeshiftOffset (TIME_FORMAT format) const
References m_critSection, and m_iTimeshiftOffset.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetTimeshiftPlayTime()
std::string CPVRGUITimesInfo::GetTimeshiftPlayTime (TIME_FORMAT format) const
References m_critSection, m_iTimeshiftPlayTime, and TimeToTimeString().
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetTimeshiftProgress()
int CPVRGUITimesInfo::GetTimeshiftProgress () const
References m_critSection, m_iTimeshiftEndTime, m_iTimeshiftPlayTime, and m_iTimeshiftStartTime.
Referenced by PVR::CPVRGUIInfo::GetPVRInt().
GetTimeshiftProgressBufferEnd()
int CPVRGUITimesInfo::GetTimeshiftProgressBufferEnd () const
References m_critSection, m_iTimeshiftEndTime, m_iTimeshiftProgressDuration, and m_iTimeshiftProgressStartTime.
Referenced by PVR::CPVRGUIInfo::GetPVRInt().
GetTimeshiftProgressBufferStart()
int CPVRGUITimesInfo::GetTimeshiftProgressBufferStart () const
References m_critSection, m_iTimeshiftProgressDuration, m_iTimeshiftProgressStartTime, and m_iTimeshiftStartTime.
Referenced by PVR::CPVRGUIInfo::GetPVRInt().
GetTimeshiftProgressDuration() [1/2]
int CPVRGUITimesInfo::GetTimeshiftProgressDuration () const
References m_critSection, and m_iTimeshiftProgressDuration.
GetTimeshiftProgressDuration() [2/2]
std::string CPVRGUITimesInfo::GetTimeshiftProgressDuration (TIME_FORMAT format) const
References m_critSection, and m_iTimeshiftProgressDuration.
Referenced by PVR::CPVRGUIInfo::GetPVRInt(), PVR::CPVRGUIInfo::GetPVRLabel(), and PVR::CPVRGUIInfo::GetTimeShiftSeekPercent().
GetTimeshiftProgressEndTime()
std::string CPVRGUITimesInfo::GetTimeshiftProgressEndTime (TIME_FORMAT format) const
References m_critSection, m_iTimeshiftProgressEndTime, and TimeToTimeString().
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetTimeshiftProgressEpgEnd()
int CPVRGUITimesInfo::GetTimeshiftProgressEpgEnd () const
References m_critSection, m_iTimeshiftProgressDuration, m_iTimeshiftProgressStartTime, and m_playingEpgTag.
Referenced by PVR::CPVRGUIInfo::GetPVRInt().
GetTimeshiftProgressEpgStart()
int CPVRGUITimesInfo::GetTimeshiftProgressEpgStart () const
References m_critSection, m_iTimeshiftProgressDuration, m_iTimeshiftProgressStartTime, and m_playingEpgTag.
Referenced by PVR::CPVRGUIInfo::GetPVRInt().
GetTimeshiftProgressPlayPosition()
int CPVRGUITimesInfo::GetTimeshiftProgressPlayPosition () const
References m_critSection, m_iTimeshiftPlayTime, m_iTimeshiftProgressDuration, and m_iTimeshiftProgressStartTime.
Referenced by PVR::CPVRGUIInfo::GetPVRInt(), and PVR::CPVRGUIInfo::GetTimeShiftSeekPercent().
GetTimeshiftProgressStartTime()
std::string CPVRGUITimesInfo::GetTimeshiftProgressStartTime (TIME_FORMAT format) const
References m_critSection, m_iTimeshiftProgressStartTime, and TimeToTimeString().
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetTimeshiftStartTime()
std::string CPVRGUITimesInfo::GetTimeshiftStartTime (TIME_FORMAT format) const
References m_critSection, m_iTimeshiftStartTime, and TimeToTimeString().
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
IsTimeshifting()
bool CPVRGUITimesInfo::IsTimeshifting () const
References CServiceBroker::GetSettingsComponent(), m_critSection, and m_iTimeshiftOffset.
Referenced by PVR::CPVRGUIInfo::GetPVRBool().
Reset()
void CPVRGUITimesInfo::Reset ()
References m_critSection, m_iDuration, m_iStartTime, m_iTimeshiftEndTime, m_iTimeshiftOffset, m_iTimeshiftPlayTime, m_iTimeshiftProgressDuration, m_iTimeshiftProgressEndTime, m_iTimeshiftProgressStartTime, m_iTimeshiftStartTime, m_playingChannel, and m_playingEpgTag.
Referenced by CPVRGUITimesInfo(), PVR::CPVRGUIInfo::ResetProperties(), and UpdateTimeshiftData().
TimeToTimeString()
std::string CPVRGUITimesInfo::TimeToTimeString (time_t datetime, TIME_FORMAT format, bool withSeconds) static private
References CDateTime::SetFromUTCDateTime().
Referenced by GetTimeshiftEndTime(), GetTimeshiftPlayTime(), GetTimeshiftProgressEndTime(), GetTimeshiftProgressStartTime(), and GetTimeshiftStartTime().
Update()
void CPVRGUITimesInfo::Update ()
References UpdatePlayingTag(), and UpdateTimeshiftData().
Referenced by PVR::CPVRGUIInfo::UpdateTimeshiftData().
UpdatePlayingTag()
void CPVRGUITimesInfo::UpdatePlayingTag () private
References PVR::CPVRManager::ChannelGroups(), CServiceBroker::GetPVRManager(), m_critSection, m_iDuration, m_iTimeshiftEndTime, m_iTimeshiftStartTime, m_playingEpgTag, and PVR::CPVRManager::PlaybackState().
Referenced by Update().
UpdateTimeshiftData()
void CPVRGUITimesInfo::UpdateTimeshiftData () private
References CServiceBroker::GetDataCacheCore(), CDataCacheCore::GetPlayTimes(), CServiceBroker::GetPVRManager(), CDataCacheCore::GetSpeed(), int64_t(), m_critSection, m_iStartTime, m_iTimeshiftEndTime, m_iTimeshiftOffset, m_iTimeshiftPlayTime, m_iTimeshiftStartTime, m_playingChannel, PVR::CPVRManager::PlaybackState(), Reset(), and UpdateTimeshiftProgressData().
Referenced by Update().
UpdateTimeshiftProgressData()
void CPVRGUITimesInfo::UpdateTimeshiftProgressData () private
References end(), CServiceBroker::GetSettingsComponent(), m_critSection, m_iTimeshiftEndTime, m_iTimeshiftProgressDuration, m_iTimeshiftProgressEndTime, m_iTimeshiftProgressStartTime, m_iTimeshiftStartTime, and m_playingEpgTag.
Referenced by UpdateTimeshiftData().
Member Data Documentation
m_critSection
CCriticalSection PVR::CPVRGUITimesInfo::m_critSection mutable private
Referenced by GetElapsedTime(), GetEpgEventDuration(), GetEpgEventDuration(), GetEpgEventElapsedTime(), GetEpgEventProgress(), GetEpgEventRemainingTime(), GetRemainingTime(), GetTimeshiftEndTime(), GetTimeshiftOffset(), GetTimeshiftPlayTime(), GetTimeshiftProgress(), GetTimeshiftProgressBufferEnd(), GetTimeshiftProgressBufferStart(), GetTimeshiftProgressDuration(), GetTimeshiftProgressDuration(), GetTimeshiftProgressEndTime(), GetTimeshiftProgressEpgEnd(), GetTimeshiftProgressEpgStart(), GetTimeshiftProgressPlayPosition(), GetTimeshiftProgressStartTime(), GetTimeshiftStartTime(), IsTimeshifting(), Reset(), UpdatePlayingTag(), UpdateTimeshiftData(), and UpdateTimeshiftProgressData().
m_iDuration
unsigned int PVR::CPVRGUITimesInfo::m_iDuration private
Referenced by GetEpgEventDuration(), GetEpgEventProgress(), GetRemainingTime(), Reset(), and UpdatePlayingTag().
m_iStartTime
time_t PVR::CPVRGUITimesInfo::m_iStartTime private
Referenced by Reset(), and UpdateTimeshiftData().
m_iTimeshiftEndTime
time_t PVR::CPVRGUITimesInfo::m_iTimeshiftEndTime private
Referenced by GetTimeshiftEndTime(), GetTimeshiftProgress(), GetTimeshiftProgressBufferEnd(), Reset(), UpdatePlayingTag(), UpdateTimeshiftData(), and UpdateTimeshiftProgressData().
m_iTimeshiftOffset
int64_t PVR::CPVRGUITimesInfo::m_iTimeshiftOffset private
Referenced by GetTimeshiftOffset(), IsTimeshifting(), Reset(), and UpdateTimeshiftData().
m_iTimeshiftPlayTime
time_t PVR::CPVRGUITimesInfo::m_iTimeshiftPlayTime private
Referenced by GetElapsedTime(), GetTimeshiftPlayTime(), GetTimeshiftProgress(), GetTimeshiftProgressPlayPosition(), Reset(), and UpdateTimeshiftData().
m_iTimeshiftProgressDuration
unsigned int PVR::CPVRGUITimesInfo::m_iTimeshiftProgressDuration private
Referenced by GetTimeshiftProgressBufferEnd(), GetTimeshiftProgressBufferStart(), GetTimeshiftProgressDuration(), GetTimeshiftProgressDuration(), GetTimeshiftProgressEpgEnd(), GetTimeshiftProgressEpgStart(), GetTimeshiftProgressPlayPosition(), Reset(), and UpdateTimeshiftProgressData().
m_iTimeshiftProgressEndTime
time_t PVR::CPVRGUITimesInfo::m_iTimeshiftProgressEndTime private
Referenced by GetTimeshiftProgressEndTime(), Reset(), and UpdateTimeshiftProgressData().
m_iTimeshiftProgressStartTime
time_t PVR::CPVRGUITimesInfo::m_iTimeshiftProgressStartTime private
Referenced by GetTimeshiftProgressBufferEnd(), GetTimeshiftProgressBufferStart(), GetTimeshiftProgressEpgEnd(), GetTimeshiftProgressEpgStart(), GetTimeshiftProgressPlayPosition(), GetTimeshiftProgressStartTime(), Reset(), and UpdateTimeshiftProgressData().
m_iTimeshiftStartTime
time_t PVR::CPVRGUITimesInfo::m_iTimeshiftStartTime private
Referenced by GetElapsedTime(), GetTimeshiftProgress(), GetTimeshiftProgressBufferStart(), GetTimeshiftStartTime(), Reset(), UpdatePlayingTag(), UpdateTimeshiftData(), and UpdateTimeshiftProgressData().
m_playingChannel
std::shared_ptr<const CPVRChannel> PVR::CPVRGUITimesInfo::m_playingChannel private
Referenced by Reset(), and UpdateTimeshiftData().
m_playingEpgTag
std::shared_ptr<const CPVREpgInfoTag> PVR::CPVRGUITimesInfo::m_playingEpgTag private
Referenced by GetElapsedTime(), GetEpgEventDuration(), GetEpgEventElapsedTime(), GetEpgEventProgress(), GetRemainingTime(), GetTimeshiftProgressEpgEnd(), GetTimeshiftProgressEpgStart(), Reset(), UpdatePlayingTag(), and UpdateTimeshiftProgressData().
The documentation for this class was generated from the following files:
PVRGUITimesInfo.h
PVRGUITimesInfo.cpp