Kodi Documentation: KODI::GAME::CControllerInstaller Class Reference
KODI::GAME::CControllerInstaller Class Reference
Games
#include <ControllerInstaller.h>
Public Member Functions
CControllerInstaller ()
~CControllerInstaller () override=default
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Protected Member Functions
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CControllerInstaller()
CControllerInstaller::CControllerInstaller ()
~CControllerInstaller()
KODI::GAME::CControllerInstaller::~CControllerInstaller () override default
Member Function Documentation
Process()
void CControllerInstaller::Process (void) override protected virtual
Reimplemented from CThread.
References CFileItemList::Add(), ADDON::CHOICE_NO, g_localizeStrings, ADDON::GAME_CONTROLLER, CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), CServiceBroker::GetGUI(), ADDON::CAddonMgr::GetInstallableAddons(), ADDON::CAddonInstaller::GetInstance(), CGUIComponent::GetWindowManager(), ADDON::CAddonInstaller::InstallOrUpdate(), CLog::Log(), LOGDEBUG, LOGERROR, KODI::MESSAGING::HELPERS::ShowOKDialogText(), WINDOW_DIALOG_PROGRESS, and WINDOW_DIALOG_SELECT.
The documentation for this class was generated from the following files:
ControllerInstaller.h
ControllerInstaller.cpp