Kodi Documentation: XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview Class Reference
XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview Class Reference
#include <DirectoryNodeOverview.h>
Public Member Functions
CDirectoryNodeOverview (const std::string &strName, CDirectoryNode *pParent)
Public Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
virtual ~CDirectoryNode ()
NODE_TYPE GetType () const
bool GetChilds (CFileItemList &items)
void CollectQueryParams (CQueryParams &params) const
CDirectoryNode * GetParent () const
std::string BuildPath () const
virtual bool CanCache () const
Protected Member Functions
NODE_TYPE GetChildType () const override
bool GetContent (CFileItemList &items) const override
std::string GetLocalizedName () const override
Protected Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
CDirectoryNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
void AddOptions (const std::string &options)
const std::string & GetName () const
int GetID () const
void RemoveParent ()
Additional Inherited Members
Static Public Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
static CDirectoryNode * ParseURL (const std::string &strPath)
static void GetDatabaseInfo (const std::string &strPath, CQueryParams &params)
Static Protected Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
static CDirectoryNode * CreateNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
Constructor & Destructor Documentation
CDirectoryNodeOverview()
CDirectoryNodeOverview::CDirectoryNodeOverview (const std::string & strName, CDirectoryNode * pParent)
Member Function Documentation
GetChildType()
NODE_TYPE CDirectoryNodeOverview::GetChildType () const override protected virtual
Reimplemented from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode.
References XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetName(), node, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_NONE, and OverviewChildren.
GetContent()
bool CDirectoryNodeOverview::GetContent (CFileItemList & items) const override protected virtual
Reimplemented from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode.
References CFileItemList::Add(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::BuildPath(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetSettingsComponent(), CVideoDatabase::HasContent(), MOVIES, MUSICVIDEOS, CVideoDatabase::Open(), CSettings::SETTING_MYVIDEOS_FLATTEN, and TVSHOWS.
GetLocalizedName()
std::string CDirectoryNodeOverview::GetLocalizedName () const override protected virtual
Reimplemented from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode.
References g_localizeStrings, CLocalizeStrings::Get(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetName(), node, and OverviewChildren.
The documentation for this class was generated from the following files:
VideoDatabaseDirectory/DirectoryNodeOverview.h
VideoDatabaseDirectory/DirectoryNodeOverview.cpp