Kodi Documentation: GUIFont.h File Reference
GUIFont.h File Reference
#include "utils/ColorUtils.h"
#include <assert.h>
#include <math.h>
#include <stdint.h>
#include <string>
#include <vector>
Classes
class CScrollInfo
class CGUIFont
Typedefs
typedef uint32_t character_t
typedef std::vector< character_t > vecText
Variables
constexpr int XBFONT_LEFT = 0
Align X left.
constexpr int XBFONT_RIGHT = (1 << 0)
Align X right.
constexpr int XBFONT_CENTER_X = (1 << 1)
Align X center.
constexpr int XBFONT_CENTER_Y = (1 << 2)
Align Y center.
constexpr int XBFONT_TRUNCATED = (1 << 3)
Truncated text from right (text end with ellipses)
constexpr int XBFONT_JUSTIFIED = (1 << 4)
Justify text.
constexpr int XBFONT_TRUNCATED_LEFT = (1 << 5)
Truncated text from left (text start with ellipses)
constexpr int FONT_STYLE_NORMAL = 0
constexpr int FONT_STYLE_BOLD = (1 << 0)
constexpr int FONT_STYLE_ITALICS = (1 << 1)
constexpr int FONT_STYLE_LIGHT = (1 << 2)
constexpr int FONT_STYLE_UPPERCASE = (1 << 3)
constexpr int FONT_STYLE_LOWERCASE = (1 << 4)
constexpr int FONT_STYLE_CAPITALIZE = (1 << 5)
constexpr int FONT_STYLE_MASK = 0xFF
constexpr int FONT_STYLES_COUNT = 7
Typedef Documentation
character_t
typedef uint32_t character_t
vecText
typedef std::vector<character_t> vecText
Variable Documentation
FONT_STYLE_BOLD
constexpr int FONT_STYLE_BOLD = (1 << 0) constexpr
Referenced by CGUIFontTTF::CacheCharacter(), GUIFontManager::GetStyle(), and CGUITextLayout::ParseText().
FONT_STYLE_CAPITALIZE
constexpr int FONT_STYLE_CAPITALIZE = (1 << 5) constexpr
Referenced by GUIFontManager::GetStyle(), and CGUITextLayout::ParseText().
FONT_STYLE_ITALICS
constexpr int FONT_STYLE_ITALICS = (1 << 1) constexpr
Referenced by CGUIFontTTF::CacheCharacter(), GUIFontManager::GetStyle(), and CGUITextLayout::ParseText().
FONT_STYLE_LIGHT
constexpr int FONT_STYLE_LIGHT = (1 << 2) constexpr
Referenced by CGUIFontTTF::CacheCharacter(), GUIFontManager::GetStyle(), and CGUITextLayout::ParseText().
FONT_STYLE_LOWERCASE
constexpr int FONT_STYLE_LOWERCASE = (1 << 4) constexpr
Referenced by GUIFontManager::GetStyle(), and CGUITextLayout::ParseText().
FONT_STYLE_MASK
constexpr int FONT_STYLE_MASK = 0xFF constexpr
Referenced by CGUIFont::CGUIFont(), CGUITextLayout::GetTextWidth(), CGUITextLayout::ParseText(), CGUIEditControl::SetStyledText(), and CGUILabelControl::UpdateInfo().
FONT_STYLE_NORMAL
constexpr int FONT_STYLE_NORMAL = 0 constexpr
Referenced by GUIFontManager::GetStyle(), GUIFontManager::LoadFonts(), CGUIEditControl::SetStyledText(), CRenderSystemBase::ShowSplash(), and CGUILabelControl::UpdateInfo().
FONT_STYLE_UPPERCASE
constexpr int FONT_STYLE_UPPERCASE = (1 << 3) constexpr
Referenced by GUIFontManager::GetStyle(), and CGUITextLayout::ParseText().
FONT_STYLES_COUNT
constexpr int FONT_STYLES_COUNT = 7 constexpr