Kodi Documentation: KODI::RETRO::CRetroPlayerAudio Class Reference
KODI::RETRO::CRetroPlayerAudio Class Reference
#include <RetroPlayerAudio.h>
Public Member Functions
CRetroPlayerAudio (CRPProcessInfo &processInfo)
~CRetroPlayerAudio () override
void Enable (bool bEnabled)
bool OpenStream (const StreamProperties &properties) override
Open a stream.
bool GetStreamBuffer (unsigned int width, unsigned int height, StreamBuffer &buffer) override
Get a buffer for zero-copy stream data.
void AddStreamData (const StreamPacket &packet) override
Add a data packet to a stream.
void CloseStream () override
Close the stream.
Public Member Functions inherited from KODI::RETRO::IRetroPlayerStream
virtual ~IRetroPlayerStream ()=default
Private Attributes
CRPProcessInfo & m_processInfo
IAE::StreamPtr m_pAudioStream
bool m_bAudioEnabled = true
Constructor & Destructor Documentation
CRetroPlayerAudio()
CRetroPlayerAudio::CRetroPlayerAudio (CRPProcessInfo & processInfo) explicit
References CLog::Log(), and LOGDEBUG.
~CRetroPlayerAudio()
CRetroPlayerAudio::~CRetroPlayerAudio () override
References CloseStream(), CLog::Log(), and LOGDEBUG.
Member Function Documentation
AddStreamData()
void CRetroPlayerAudio::AddStreamData (const StreamPacket & packet) override virtual
Add a data packet to a stream.
Parameters
packet The data packet
Implements KODI::RETRO::IRetroPlayerStream.
References KODI::RETRO::AudioStreamPacket::data, CAEUtil::DataFormatToBits(), CLog::Log(), LOGDEBUG, m_bAudioEnabled, m_pAudioStream, MAX_DELAY, and KODI::RETRO::AudioStreamPacket::size.
CloseStream()
void CRetroPlayerAudio::CloseStream () override virtual
Close the stream.
Implements KODI::RETRO::IRetroPlayerStream.
References CLog::Log(), LOGDEBUG, and m_pAudioStream.
Referenced by KODI::RETRO::CRPStreamManager::CloseStream(), OpenStream(), and ~CRetroPlayerAudio().
Enable()
void KODI::RETRO::CRetroPlayerAudio::Enable (bool bEnabled) inline
References m_bAudioEnabled.
Referenced by KODI::RETRO::CRPStreamManager::EnableAudio().
GetStreamBuffer()
bool KODI::RETRO::CRetroPlayerAudio::GetStreamBuffer (unsigned int width, unsigned int height, StreamBuffer & buffer) inline override virtual
Get a buffer for zero-copy stream data.
Parameters
width The framebuffer width, or 0 for no width specified
height The framebuffer height, or 0 for no height specified
[out] buffer The buffer, or unmodified if false is returned
Returns
True if a buffer was returned, false otherwise
Implements KODI::RETRO::IRetroPlayerStream.
OpenStream()
bool CRetroPlayerAudio::OpenStream (const StreamProperties & properties) override virtual
Open a stream.
Returns
True if the stream was opened, false otherwise
Implements KODI::RETRO::IRetroPlayerStream.
References AE_CH_NULL, AE_FMT_INVALID, audioEngine, KODI::RETRO::AudioStreamProperties::channelMap, CloseStream(), CAEChannelInfo::Count(), CAEUtil::DataFormatToStr(), CAEUtil::DataFormatToUsedBits(), KODI::RETRO::AudioStreamProperties::format, CServiceBroker::GetActiveAE(), CAEChannelInfo::IsLayoutValid(), CLog::Log(), LOGERROR, LOGINFO, AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, m_pAudioStream, m_processInfo, AEAudioFormat::m_sampleRate, KODI::RETRO::AudioStreamProperties::sampleRate, KODI::RETRO::CRPProcessInfo::SetAudioBitsPerSample(), KODI::RETRO::CRPProcessInfo::SetAudioChannels(), KODI::RETRO::CRPProcessInfo::SetAudioSampleRate(), KODI::RETRO::CAudioTranslator::TranslateAudioChannel(), and KODI::RETRO::CAudioTranslator::TranslatePCMFormat().
Referenced by KODI::GAME::CGameClientStreamAudio::OpenStream().
Member Data Documentation
m_bAudioEnabled
bool KODI::RETRO::CRetroPlayerAudio::m_bAudioEnabled = true private
Referenced by AddStreamData(), and Enable().
m_pAudioStream
IAE::StreamPtr KODI::RETRO::CRetroPlayerAudio::m_pAudioStream private
Referenced by AddStreamData(), CloseStream(), and OpenStream().
m_processInfo
CRPProcessInfo& KODI::RETRO::CRetroPlayerAudio::m_processInfo private
Referenced by OpenStream().
The documentation for this class was generated from the following files:
RetroPlayerAudio.h
RetroPlayerAudio.cpp