Kodi Documentation: JSONRPC::CInputOperations Class Reference
JSONRPC::CInputOperations Class Reference
#include <InputOperations.h>
Static Public Member Functions
static JSONRPC_STATUS SendText (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ExecuteAction (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ButtonEvent (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Left (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Right (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Down (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Up (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Select (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Back (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ContextMenu (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Info (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Home (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ShowCodec (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ShowOSD (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ShowPlayerProcessInfo (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SendAction (int actionID, bool wakeScreensaver=true, bool waitResult=false)
Static Private Member Functions
static JSONRPC_STATUS activateWindow (int windowID)
static bool handleScreenSaver ()
Member Function Documentation
activateWindow()
JSONRPC_STATUS CInputOperations::activateWindow (int windowID) static private
References JSONRPC::ACK, CServiceBroker::GetAppMessenger(), handleScreenSaver(), and TMSG_GUI_ACTIVATE_WINDOW.
Referenced by Home().
Back()
JSONRPC_STATUS CInputOperations::Back (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_NAV_BACK, and SendAction().
ButtonEvent()
JSONRPC_STATUS CInputOperations::ButtonEvent (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asInteger(), CVariant::asString(), XBMC_ButtonEvent::button, CServiceBroker::GetAppMessenger(), XBMC_ButtonEvent::holdtime, JSONRPC::InvalidParams, XBMC_Event::keybutton, TMSG_EVENT, KODI::KEYMAP::CButtonTranslator::TranslateString(), XBMC_Event::type, and XBMC_BUTTON.
ContextMenu()
JSONRPC_STATUS CInputOperations::ContextMenu (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_CONTEXT_MENU, and SendAction().
Down()
JSONRPC_STATUS CInputOperations::Down (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_MOVE_DOWN, and SendAction().
ExecuteAction()
JSONRPC_STATUS CInputOperations::ExecuteAction (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::InvalidParams, SendAction(), and KODI::ACTION::CActionTranslator::TranslateString().
handleScreenSaver()
bool CInputOperations::handleScreenSaver () static private
Todo:
the breakage of the screensaver should be refactored to one central super duper place for getting rid of 1 million dupes
References CServiceBroker::GetAppComponents(), and CApplicationPowerHandling::ResetScreenSaver().
Referenced by activateWindow(), and SendAction().
Home()
JSONRPC_STATUS CInputOperations::Home (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References activateWindow(), and WINDOW_HOME.
Info()
JSONRPC_STATUS CInputOperations::Info (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_SHOW_INFO, and SendAction().
Left()
JSONRPC_STATUS CInputOperations::Left (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_MOVE_LEFT, and SendAction().
Right()
JSONRPC_STATUS CInputOperations::Right (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_MOVE_RIGHT, and SendAction().
Select()
JSONRPC_STATUS CInputOperations::Select (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_SELECT_ITEM, and SendAction().
SendAction()
JSONRPC_STATUS CInputOperations::SendAction (int actionID, bool wakeScreensaver = true, bool waitResult = false) static
References JSONRPC::ACK, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CGUIComponent::GetAudioManager(), CServiceBroker::GetGUI(), handleScreenSaver(), CGUIAudioManager::PlayActionSound(), CApplicationPowerHandling::ResetSystemIdleTimer(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by Back(), ContextMenu(), Down(), ExecuteAction(), Info(), Left(), Right(), Select(), JSONRPC::CApplicationOperations::SetVolume(), ShowOSD(), ShowPlayerProcessInfo(), and Up().
SendText()
JSONRPC_STATUS CInputOperations::SendText (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CServiceBroker::GetAppMessenger(), CGUIControlGroup::GetFocusedControlID(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), GUI_MSG_SET_TEXT, CGUIKeyboardFactory::SendTextToActiveKeyboard(), CGUIMessage::SetLabel(), and CGUIMessage::SetParam1().
ShowCodec()
JSONRPC_STATUS CInputOperations::ShowCodec (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::MethodNotFound.
ShowOSD()
JSONRPC_STATUS CInputOperations::ShowOSD (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_SHOW_OSD, and SendAction().
ShowPlayerProcessInfo()
JSONRPC_STATUS CInputOperations::ShowPlayerProcessInfo (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_PLAYER_PROCESS_INFO, and SendAction().
Up()
JSONRPC_STATUS CInputOperations::Up (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_MOVE_UP, and SendAction().
The documentation for this class was generated from the following files:
InputOperations.h
InputOperations.cpp