Kodi Documentation: PVR::CPVRClientMenuHook Class Reference
PVR::CPVRClientMenuHook Class Reference
#include <PVRClientMenuHooks.h>
Public Member Functions
CPVRClientMenuHook ()=delete
virtual ~CPVRClientMenuHook ()=default
CPVRClientMenuHook (const std::string &addonId, const PVR_MENUHOOK &hook)
bool operator== (const CPVRClientMenuHook &right) const
bool IsAllHook () const
bool IsChannelHook () const
bool IsTimerHook () const
bool IsEpgHook () const
bool IsRecordingHook () const
bool IsDeletedRecordingHook () const
bool IsSettingsHook () const
const std::string & GetAddonId () const
unsigned int GetId () const
unsigned int GetLabelId () const
std::string GetLabel () const
Private Attributes
std::string m_addonId
std::shared_ptr< PVR_MENUHOOK > m_hook
Constructor & Destructor Documentation
CPVRClientMenuHook() [1/2]
PVR::CPVRClientMenuHook::CPVRClientMenuHook () delete
~CPVRClientMenuHook()
virtual PVR::CPVRClientMenuHook::~CPVRClientMenuHook () virtual default
CPVRClientMenuHook() [2/2]
PVR::CPVRClientMenuHook::CPVRClientMenuHook (const std::string & addonId, const PVR_MENUHOOK & hook)
References PVR_MENUHOOK::category, LOGERROR, PVR_MENUHOOK_ALL, PVR_MENUHOOK_CHANNEL, PVR_MENUHOOK_DELETED_RECORDING, PVR_MENUHOOK_EPG, PVR_MENUHOOK_RECORDING, PVR_MENUHOOK_SETTING, PVR_MENUHOOK_TIMER, and PVR_MENUHOOK_UNKNOWN.
Member Function Documentation
GetAddonId()
const std::string & PVR::CPVRClientMenuHook::GetAddonId () const inline
References m_addonId.
Referenced by PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible().
GetId()
unsigned int PVR::CPVRClientMenuHook::GetId () const
References m_hook.
Referenced by PVR::CPVRClient::CallChannelMenuHook(), PVR::CPVRClient::CallEpgTagMenuHook(), PVR::CPVRClient::CallRecordingMenuHook(), PVR::CPVRClient::CallSettingsMenuHook(), and PVR::CPVRClient::CallTimerMenuHook().
GetLabel()
std::string PVR::CPVRClientMenuHook::GetLabel () const
References g_localizeStrings, CLocalizeStrings::GetAddonString(), m_addonId, and m_hook.
Referenced by PVR::CONTEXTMENUITEM::PVRClientMenuHook::GetLabel().
GetLabelId()
unsigned int PVR::CPVRClientMenuHook::GetLabelId () const
References m_hook.
Referenced by PVR::CPVRClient::CallChannelMenuHook(), PVR::CPVRClient::CallEpgTagMenuHook(), PVR::CPVRClient::CallRecordingMenuHook(), PVR::CPVRClient::CallSettingsMenuHook(), and PVR::CPVRClient::CallTimerMenuHook().
IsAllHook()
bool PVR::CPVRClientMenuHook::IsAllHook () const
References m_hook, and PVR_MENUHOOK_ALL.
Referenced by PVR::CPVRClientMenuHooks::GetHooks(), and PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible().
IsChannelHook()
bool PVR::CPVRClientMenuHook::IsChannelHook () const
References m_hook, and PVR_MENUHOOK_CHANNEL.
Referenced by PVR::CPVRClientMenuHooks::GetChannelHooks(), and PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible().
IsDeletedRecordingHook()
bool PVR::CPVRClientMenuHook::IsDeletedRecordingHook () const
References m_hook, and PVR_MENUHOOK_DELETED_RECORDING.
Referenced by PVR::CPVRClientMenuHooks::GetDeletedRecordingHooks(), and PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible().
IsEpgHook()
bool PVR::CPVRClientMenuHook::IsEpgHook () const
References m_hook, and PVR_MENUHOOK_EPG.
Referenced by PVR::CPVRClientMenuHooks::GetEpgHooks(), and PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible().
IsRecordingHook()
bool PVR::CPVRClientMenuHook::IsRecordingHook () const
References m_hook, and PVR_MENUHOOK_RECORDING.
Referenced by PVR::CPVRClientMenuHooks::GetRecordingHooks(), and PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible().
IsSettingsHook()
bool PVR::CPVRClientMenuHook::IsSettingsHook () const
References m_hook, and PVR_MENUHOOK_SETTING.
Referenced by PVR::CPVRContextMenuManager::AddMenuHook(), PVR::CPVRClientMenuHooks::GetSettingsHooks(), and PVR::CPVRContextMenuManager::RemoveMenuHook().
IsTimerHook()
bool PVR::CPVRClientMenuHook::IsTimerHook () const
References m_hook, and PVR_MENUHOOK_TIMER.
Referenced by PVR::CPVRClientMenuHooks::GetTimerHooks(), and PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible().
operator==()
bool PVR::CPVRClientMenuHook::operator== (const CPVRClientMenuHook & right) const
References m_addonId, m_hook, and right.
Member Data Documentation
m_addonId
std::string PVR::CPVRClientMenuHook::m_addonId private
Referenced by GetAddonId(), GetLabel(), and operator==().
m_hook
std::shared_ptr<PVR_MENUHOOK> PVR::CPVRClientMenuHook::m_hook private
Referenced by GetId(), GetLabel(), GetLabelId(), IsAllHook(), IsChannelHook(), IsDeletedRecordingHook(), IsEpgHook(), IsRecordingHook(), IsSettingsHook(), IsTimerHook(), and operator==().
The documentation for this class was generated from the following files:
PVRClientMenuHooks.h
PVRClientMenuHooks.cpp