Kodi Documentation: CDVDSubtitleParserVplayer Class Reference
CDVDSubtitleParserVplayer Class Reference
#include <DVDSubtitleParserVplayer.h>
Public Member Functions
CDVDSubtitleParserVplayer (std::unique_ptr< CDVDSubtitleStream > &&pStream, const std::string &strFile)
~CDVDSubtitleParserVplayer ()=default
bool Open (CDVDStreamInfo &hints) override
Public Member Functions inherited from CDVDSubtitleParserText
CDVDSubtitleParserText (std::unique_ptr< CDVDSubtitleStream > &&stream, const std::string &filename, const char *name)
~CDVDSubtitleParserText () override=default
const std::string & GetName () const override
Public Member Functions inherited from CDVDSubtitleParserCollection
CDVDSubtitleParserCollection (const std::string &strFile)
~CDVDSubtitleParserCollection () override=default
std::shared_ptr< CDVDOverlay > Parse (double iPts) override
void Reset () override
Public Member Functions inherited from CDVDSubtitleParser
virtual ~CDVDSubtitleParser ()=default
Private Attributes
double m_framerate
Additional Inherited Members
Protected Member Functions inherited from CDVDSubtitleParserText
bool Open ()
Protected Attributes inherited from CDVDSubtitleParserText
std::unique_ptr< CDVDSubtitleStream > m_pStream
std::string m_parserName
Protected Attributes inherited from CDVDSubtitleParserCollection
CDVDSubtitleLineCollection m_collection
std::string m_filename
Private Member Functions inherited from CSubtitlesAdapter
CSubtitlesAdapter ()
virtual ~CSubtitlesAdapter ()
bool Initialize ()
Initialize the subtitles adapter.
int AddSubtitle (std::string &text, double startTime, double stopTime)
Add a subtitle.
int AddSubtitle (std::string &text, double startTime, double stopTime, KODI::SUBTITLES::STYLE::subtitleOpts *opts)
Add a subtitle with supplementary options.
void AppendToSubtitle (int subtitleId, const char *text)
Append text to the specified subtitle ID.
int DeleteSubtitles (int nSubtitles, int threshold)
Delete old subtitles only if the total number of subtitles added reaches the threshold.
void ChangeSubtitleStopTime (int subtitleId, double stopTime)
Change the stop time of a subtitle ID with the specified time.
void FlushSubtitles ()
std::shared_ptr< CDVDOverlay > CreateOverlay ()
virtual void PostProcess (std::string &text)
Post processing of subtitle, will be called before processing AddSubtitle method.
Constructor & Destructor Documentation
CDVDSubtitleParserVplayer()
CDVDSubtitleParserVplayer::CDVDSubtitleParserVplayer (std::unique_ptr< CDVDSubtitleStream > && pStream, const std::string & strFile)
~CDVDSubtitleParserVplayer()
CDVDSubtitleParserVplayer::~CDVDSubtitleParserVplayer () default
Member Function Documentation
Open()
bool CDVDSubtitleParserVplayer::Open (CDVDStreamInfo & hints) override virtual
Implements CDVDSubtitleParser.
References CDVDSubtitleLineCollection::Add(), CSubtitlesAdapter::AddSubtitle(), CSubtitlesAdapter::ChangeSubtitleStopTime(), CSubtitlesAdapter::CreateOverlay(), DVD_TIME_BASE, CRegExp::GetMatch(), CSubtitlesAdapter::Initialize(), CDVDSubtitleParserCollection::m_collection, m_framerate, CDVDSubtitleParserText::m_pStream, min, NO_SUBTITLE_ID, CDVDSubtitleParserText::Open(), CRegExp::RegComp(), and CRegExp::RegFind().
Member Data Documentation
m_framerate
double CDVDSubtitleParserVplayer::m_framerate private
Referenced by Open().
The documentation for this class was generated from the following files:
DVDSubtitleParserVplayer.h
DVDSubtitleParserVplayer.cpp