Kodi Documentation: CLinuxRendererGL Class Reference
CLinuxRendererGL Class Reference
#include <LinuxRendererGL.h>
Classes
struct CPictureBuffer
struct CYuvPlane
Public Member Functions
CLinuxRendererGL ()
~CLinuxRendererGL () override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
bool IsConfigured () override
void AddVideoPicture (const VideoPicture &picture, int index) override
void UnInit () override
bool Flush (bool saveBuffers) override
void SetBufferSize (int numBuffers) override
void ReleaseBuffer (int idx) override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
void Update () override
bool RenderCapture (int index, CRenderCapture *capture) override
CRenderInfo GetRenderInfo () override
bool ConfigChanged (const VideoPicture &picture) override
bool SupportsMultiPassRendering () override
bool Supports (ERENDERFEATURE feature) const override
bool Supports (ESCALINGMETHOD method) const override
CRenderCapture * GetRenderCapture () override
Public Member Functions inherited from CBaseRenderer
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool IsPictureHW (const VideoPicture &picture)
virtual bool NeedBuffer (int idx)
virtual bool IsGuiLayer ()
virtual bool WantsDoublePass ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
virtual DEBUG_INFO_VIDEO GetDebugInfo (int idx)
Static Public Member Functions
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Static Public Member Functions inherited from CBaseRenderer
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
bool Render (unsigned int flags, int renderBuffer)
void ClearBackBuffer ()
void ClearBackBufferQuad ()
void DrawBlackBars ()
bool ValidateRenderer ()
virtual bool ValidateRenderTarget ()
virtual void LoadShaders (int field=FIELD_FULL)
void SetTextureFilter (GLenum method)
void UpdateVideoFilter ()
void CheckVideoParameters (int index)
AVColorPrimaries GetSrcPrimaries (AVColorPrimaries srcPrimaries, unsigned int width, unsigned int height)
virtual bool UploadTexture (int index)
virtual void DeleteTexture (int index)
virtual bool CreateTexture (int index)
bool UploadYV12Texture (int index)
void DeleteYV12Texture (int index)
bool CreateYV12Texture (int index)
bool UploadNV12Texture (int index)
void DeleteNV12Texture (int index)
bool CreateNV12Texture (int index)
bool UploadYUV422PackedTexture (int index)
void DeleteYUV422PackedTexture (int index)
bool CreateYUV422PackedTexture (int index)
void CalculateTextureSourceRects (int source, int num_planes)
void RenderToFBO (int renderBuffer, int field, bool weave=false)
void RenderFromFBO ()
void RenderSinglePass (int renderBuffer, int field)
void RenderRGB (int renderBuffer, int field)
void RenderProgressiveWeave (int renderBuffer, int field)
void BindPbo (CPictureBuffer &buff)
void UnBindPbo (CPictureBuffer &buff)
void LoadPlane (CYuvPlane &plane, int type, unsigned width, unsigned height, int stride, int bpp, void *data)
void GetPlaneTextureSize (CYuvPlane &plane)
GLint GetInternalFormat (GLint format, int bpp)
virtual bool LoadShadersHook ()
virtual bool RenderHook (int idx)
virtual void AfterRenderHook (int idx)
virtual bool CanSaveBuffers ()
bool LoadCLUT ()
void DeleteCLUT ()
Protected Member Functions inherited from CBaseRenderer
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ManageRenderArea ()
virtual void ReorderDrawPoints ()
virtual EShaderFormat GetShaderFormat ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Protected Attributes
struct {
CFrameBufferObject fbo
float width
float height
} m_fbo
GLint m_intermediateFormat {GL_RGBA8}
GLint m_intermediateType {GL_UNSIGNED_BYTE}
bool m_intermediateGammaCorrection {false}
int m_iYV12RenderBuffer = 0
int m_NumYV12Buffers = 0
bool m_bConfigured = false
bool m_bValidated = false
GLenum m_textureTarget = GL_TEXTURE_2D
int m_renderMethod = RENDER_GLSL
RenderQuality m_renderQuality = RQ_SINGLEPASS
CRenderSystemGL * m_renderSystem = nullptr
int m_currentField = FIELD_FULL
int m_reloadShaders = 0
CPictureBuffer m_buffers [NUM_BUFFERS]
Shaders::GL::BaseYUV2RGBGLSLShader * m_pYUVShader = nullptr
Shaders::GL::BaseVideoFilterShader * m_pVideoFilterShader = nullptr
ESCALINGMETHOD m_scalingMethod = VS_SCALINGMETHOD_LINEAR
ESCALINGMETHOD m_scalingMethodGui = VS_SCALINGMETHOD_MAX
bool m_useDithering
unsigned int m_ditherDepth
bool m_fullRange
AVColorPrimaries m_srcPrimaries
bool m_toneMap = false
ETONEMAPMETHOD m_toneMapMethod = VS_TONEMAPMETHOD_OFF
float m_clearColour = 0.0f
bool m_pboSupported = true
bool m_pboUsed = false
bool m_nonLinStretch = false
bool m_nonLinStretchGui = false
float m_pixelRatio = 0.0f
CRect m_viewRect
std::unique_ptr< CColorManager > m_ColorManager
GLuint m_tCLUTTex
uint16_t * m_CLUT
int m_CLUTsize
int m_cmsToken
bool m_cmsOn
Protected Attributes inherited from CBaseRenderer
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Constructor & Destructor Documentation
CLinuxRendererGL()
CLinuxRendererGL::CLinuxRendererGL ()
References CWinSystemBase::GetDitherSettings(), CServiceBroker::GetRenderSystem(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), m_CLUT, m_CLUTsize, m_cmsOn, m_cmsToken, m_ColorManager, m_ditherDepth, m_fbo, CBaseRenderer::m_format, m_fullRange, CBaseRenderer::m_iFlags, m_intermediateFormat, m_intermediateGammaCorrection, m_intermediateType, m_renderSystem, m_tCLUTTex, m_useDithering, CSettings::SETTING_VIDEOPLAYER_HQSCALERPRECISION, and CWinSystemBase::UseLimitedColor().
Referenced by Create().
~CLinuxRendererGL()
CLinuxRendererGL::~CLinuxRendererGL () override
References m_pVideoFilterShader, m_pYUVShader, and UnInit().
Member Function Documentation
AddVideoPicture()
void CLinuxRendererGL::AddVideoPicture (const VideoPicture & picture, int index) override virtual
Implements CBaseRenderer.
References CVideoBuffer::Acquire(), VideoPicture::color_primaries, VideoPicture::color_range, VideoPicture::color_space, VideoPicture::colorBits, VideoPicture::displayMetadata, CLinuxRendererGL::CPictureBuffer::displayMetadata, VideoPicture::hasDisplayMetadata, CLinuxRendererGL::CPictureBuffer::hasDisplayMetadata, VideoPicture::hasLightMetadata, CLinuxRendererGL::CPictureBuffer::hasLightMetadata, index(), VideoPicture::lightMetadata, CLinuxRendererGL::CPictureBuffer::lightMetadata, CLinuxRendererGL::CPictureBuffer::loaded, LOGERROR, m_buffers, CLinuxRendererGL::CPictureBuffer::m_srcBits, CLinuxRendererGL::CPictureBuffer::m_srcColSpace, CLinuxRendererGL::CPictureBuffer::m_srcFullRange, CLinuxRendererGL::CPictureBuffer::m_srcPrimaries, CVideoBuffer::Release(), VideoPicture::videoBuffer, and CLinuxRendererGL::CPictureBuffer::videoBuffer.
AfterRenderHook()
virtual void CLinuxRendererGL::AfterRenderHook (int idx) inline protected virtual
Reimplemented in CRendererVAAPIGL, CRendererVDPAU, CRendererVTB, and CRendererVTB.
Referenced by Render().
BindPbo()
void CLinuxRendererGL::BindPbo (CPictureBuffer & buff) protected
References CLinuxRendererGL::CPictureBuffer::image, YuvImage::MAX_PLANES, CLinuxRendererGL::CPictureBuffer::pbo, PBO_OFFSET, and YuvImage::plane.
Referenced by UploadTexture(), and CRendererVAAPIGL::UploadTexture().
CalculateTextureSourceRects()
void CLinuxRendererGL::CalculateTextureSourceRects (int source, int num_planes) protected
References YuvImage::cshift_x, YuvImage::cshift_y, FIELD_BOT, FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGL::CYuvPlane::height, CLinuxRendererGL::CPictureBuffer::image, m_buffers, CBaseRenderer::m_sourceRect, m_textureTarget, CLinuxRendererGL::CYuvPlane::pixpertex_x, CLinuxRendererGL::CYuvPlane::pixpertex_y, CLinuxRendererGL::CYuvPlane::rect, CLinuxRendererGL::CYuvPlane::texheight, CLinuxRendererGL::CYuvPlane::texwidth, YuvImage::width, CLinuxRendererGL::CYuvPlane::width, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by UploadTexture(), CRendererVAAPIGL::UploadTexture(), CRendererVTB::UploadTexture(), and CRendererVDPAU::UploadVDPAUTexture420().
CanSaveBuffers()
virtual bool CLinuxRendererGL::CanSaveBuffers () inline protected virtual
Reimplemented in CRendererVDPAU.
Referenced by Flush().
CheckVideoParameters()
void CLinuxRendererGL::CheckVideoParameters (int index) protected
References CLinuxRendererGL::CPictureBuffer::displayMetadata, CLinuxRendererGL::CPictureBuffer::hasDisplayMetadata, CLinuxRendererGL::CPictureBuffer::hasLightMetadata, index(), m_buffers, m_reloadShaders, CLinuxRendererGL::CPictureBuffer::m_srcPrimaries, m_srcPrimaries, m_toneMap, m_toneMapMethod, CVideoSettings::m_ToneMapMethod, CBaseRenderer::m_videoSettings, and VS_TONEMAPMETHOD_OFF.
Referenced by RenderSinglePass(), and RenderToFBO().
ClearBackBuffer()
void CLinuxRendererGL::ClearBackBuffer () protected
References CGraphicContext::Clear(), ClearBackBufferQuad(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), and RENDER_ORDER_ALL_BACK_TO_FRONT.
Referenced by RenderUpdate().
ClearBackBufferQuad()
void CLinuxRendererGL::ClearBackBufferQuad () protected
References CRenderSystemGL::DisableShader(), CRenderSystemGL::EnableShader(), CServiceBroker::GetWinSystem(), m_clearColour, m_renderSystem, CRenderSystemGL::ShaderGetPos(), CRenderSystemGL::ShaderGetUniCol(), SM_DEFAULT, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by ClearBackBuffer().
ConfigChanged()
bool CLinuxRendererGL::ConfigChanged (const VideoPicture & picture) override virtual
Implements CBaseRenderer.
Reimplemented in CRendererVAAPIGL, and CRendererVDPAU.
References CVideoBuffer::GetFormat(), CBaseRenderer::m_format, and VideoPicture::videoBuffer.
Configure()
bool CLinuxRendererGL::Configure (const VideoPicture & picture, float fps, unsigned int orientation) override virtual
Implements CBaseRenderer.
Reimplemented in CRendererVAAPIGL, and CRendererVDPAU.
References CBaseRenderer::CalculateFrameAspectRatio(), VideoPicture::chroma_position, VideoPicture::color_primaries, GetFlagsChromaPosition(), GetFlagsStereoMode(), CVideoBuffer::GetFormat(), CServiceBroker::GetRenderSystem(), CServiceBroker::GetWinSystem(), VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iHeight, CRenderSystemBase::IsExtSupported(), VideoPicture::iWidth, LoadCLUT(), CLog::Log(), LOGDEBUG, m_bConfigured, m_bValidated, m_clearColour, m_cmsOn, m_cmsToken, m_ColorManager, CBaseRenderer::m_format, CBaseRenderer::m_fps, CBaseRenderer::m_iFlags, m_nonLinStretch, m_nonLinStretchGui, m_pboSupported, m_pixelRatio, CBaseRenderer::m_renderOrientation, m_scalingMethodGui, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, m_srcPrimaries, m_toneMap, CBaseRenderer::m_videoSettings, CVideoSettings::m_ViewMode, CBaseRenderer::ManageRenderArea(), CBaseRenderer::SetViewMode(), VideoPicture::stereoMode, CWinSystemBase::UseLimitedColor(), and VideoPicture::videoBuffer.
Referenced by CRendererVAAPIGL::Configure(), and CRendererVDPAU::Configure().
Create()
CBaseRenderer * CLinuxRendererGL::Create (CVideoBuffer * buffer) static
References CLinuxRendererGL().
Referenced by Register().
CreateNV12Texture()
bool CLinuxRendererGL::CreateNV12Texture (int index) protected
References YuvImage::bpp, YuvImage::cshift_x, YuvImage::cshift_y, DeleteNV12Texture(), f, FIELD_BOT, FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGL::CYuvPlane::id, CLinuxRendererGL::CPictureBuffer::image, index(), CLog::Log(), LOGWARNING, m_buffers, m_pboUsed, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, m_textureTarget, MAX_FIELDS, YuvImage::MAX_PLANES, CLinuxRendererGL::CYuvPlane::pbo, CLinuxRendererGL::CPictureBuffer::pbo, PBO_OFFSET, YuvImage::plane, YuvImage::planesize, YuvImage::stride, CLinuxRendererGL::CYuvPlane::texheight, CLinuxRendererGL::CYuvPlane::texwidth, VerifyGLState, and YuvImage::width.
Referenced by CreateTexture(), and CRendererVAAPIGL::CreateTexture().
CreateTexture()
bool CLinuxRendererGL::CreateTexture (int index) protected virtual
Reimplemented in CRendererVAAPIGL, CRendererVDPAU, CRendererVTB, and CRendererVTB.
References CreateNV12Texture(), CreateYUV422PackedTexture(), CreateYV12Texture(), index(), and CBaseRenderer::m_format.
Referenced by ValidateRenderTarget().
CreateYUV422PackedTexture()
bool CLinuxRendererGL::CreateYUV422PackedTexture (int index) protected
References YuvImage::bpp, YuvImage::cshift_x, YuvImage::cshift_y, DeleteYUV422PackedTexture(), f, FIELD_BOT, FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGL::CYuvPlane::id, CLinuxRendererGL::CPictureBuffer::image, index(), CLog::Log(), LOGWARNING, m_buffers, m_pboUsed, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, m_textureTarget, MAX_FIELDS, YuvImage::MAX_PLANES, CLinuxRendererGL::CYuvPlane::pbo, CLinuxRendererGL::CPictureBuffer::pbo, PBO_OFFSET, YuvImage::plane, YuvImage::planesize, YuvImage::stride, CLinuxRendererGL::CYuvPlane::texheight, CLinuxRendererGL::CYuvPlane::texwidth, VerifyGLState, and YuvImage::width.
Referenced by CreateTexture().
CreateYV12Texture()
bool CLinuxRendererGL::CreateYV12Texture (int index) protected
References YuvImage::bpp, YuvImage::cshift_x, YuvImage::cshift_y, DeleteYV12Texture(), f, FIELD_BOT, FIELD_FULL, fields, CLinuxRendererGL::CPictureBuffer::fields, GetInternalFormat(), YuvImage::height, CLinuxRendererGL::CYuvPlane::id, CLinuxRendererGL::CPictureBuffer::image, index(), CLog::Log(), LOGWARNING, m_buffers, CBaseRenderer::m_format, m_pboUsed, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, CLinuxRendererGL::CPictureBuffer::m_srcTextureBits, m_textureTarget, MAX_FIELDS, YuvImage::MAX_PLANES, CLinuxRendererGL::CYuvPlane::pbo, CLinuxRendererGL::CPictureBuffer::pbo, PBO_OFFSET, YuvImage::plane, YuvImage::planesize, YuvImage::stride, CLinuxRendererGL::CYuvPlane::texheight, CLinuxRendererGL::CYuvPlane::texwidth, VerifyGLState, and YuvImage::width.
Referenced by CreateTexture().
DeleteCLUT()
void CLinuxRendererGL::DeleteCLUT () protected
References CLog::Log(), LOGDEBUG, and m_tCLUTTex.
Referenced by LoadCLUT(), and UnInit().
DeleteNV12Texture()
void CLinuxRendererGL::DeleteNV12Texture (int index) protected
References f, FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, CLinuxRendererGL::CYuvPlane::id, CLinuxRendererGL::CPictureBuffer::image, index(), m_buffers, MAX_FIELDS, CLinuxRendererGL::CPictureBuffer::pbo, and YuvImage::plane.
Referenced by CreateNV12Texture(), DeleteTexture(), and CRendererVAAPIGL::DeleteTexture().
DeleteTexture()
void CLinuxRendererGL::DeleteTexture (int index) protected virtual
Reimplemented in CRendererVAAPIGL, CRendererVDPAU, CRendererVTB, and CRendererVTB.
References DeleteNV12Texture(), DeleteYUV422PackedTexture(), DeleteYV12Texture(), index(), CLinuxRendererGL::CPictureBuffer::loaded, m_buffers, and CBaseRenderer::m_format.
Referenced by Flush(), UnInit(), and ValidateRenderTarget().
DeleteYUV422PackedTexture()
void CLinuxRendererGL::DeleteYUV422PackedTexture (int index) protected
References f, FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, CLinuxRendererGL::CYuvPlane::id, CLinuxRendererGL::CPictureBuffer::image, index(), m_buffers, MAX_FIELDS, CLinuxRendererGL::CPictureBuffer::pbo, and YuvImage::plane.
Referenced by CreateYUV422PackedTexture(), and DeleteTexture().
DeleteYV12Texture()
void CLinuxRendererGL::DeleteYV12Texture (int index) protected
References f, FIELD_FULL, fields, CLinuxRendererGL::CPictureBuffer::fields, CLinuxRendererGL::CYuvPlane::id, CLinuxRendererGL::CPictureBuffer::image, index(), m_buffers, MAX_FIELDS, YuvImage::MAX_PLANES, CLinuxRendererGL::CPictureBuffer::pbo, and YuvImage::plane.
Referenced by CreateYV12Texture(), and DeleteTexture().
DrawBlackBars()
void CLinuxRendererGL::DrawBlackBars () protected
References CRenderSystemGL::DisableShader(), CRenderSystemGL::EnableShader(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetHeight(), CGraphicContext::GetWidth(), CServiceBroker::GetWinSystem(), m_clearColour, CBaseRenderer::m_destRect, m_renderSystem, CRenderSystemGL::ShaderGetPos(), CRenderSystemGL::ShaderGetUniCol(), SM_DEFAULT, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by RenderUpdate().
Flush()
bool CLinuxRendererGL::Flush (bool saveBuffers) override virtual
Reimplemented from CBaseRenderer.
Reimplemented in CRendererVAAPIGL, and CRendererVDPAU.
References CanSaveBuffers(), DeleteTexture(), m_bValidated, m_fbo, m_iYV12RenderBuffer, m_NumYV12Buffers, m_pVideoFilterShader, m_pYUVShader, and ReleaseBuffer().
Referenced by CRendererVAAPIGL::Flush(), and CRendererVDPAU::Flush().
GetInternalFormat()
GLint CLinuxRendererGL::GetInternalFormat (GLint format, int bpp) protected
References CRenderSystemBase::GetRenderVersion(), and m_renderSystem.
Referenced by CreateYV12Texture().
GetPlaneTextureSize()
void CLinuxRendererGL::GetPlaneTextureSize (CYuvPlane & plane) protected
References CLog::Log(), LOGDEBUG, m_textureTarget, CLinuxRendererGL::CYuvPlane::texheight, and CLinuxRendererGL::CYuvPlane::texwidth.
Referenced by RenderRGB().
GetRenderCapture()
CRenderCapture * CLinuxRendererGL::GetRenderCapture () override virtual
Reimplemented from CBaseRenderer.
GetRenderInfo()
CRenderInfo CLinuxRendererGL::GetRenderInfo () override virtual
Reimplemented from CBaseRenderer.
References CRenderInfo::max_buffer_size, and NUM_BUFFERS.
GetSrcPrimaries()
AVColorPrimaries CLinuxRendererGL::GetSrcPrimaries (AVColorPrimaries srcPrimaries, unsigned int width, unsigned int height) protected
IsConfigured()
bool CLinuxRendererGL::IsConfigured () inline override virtual
Implements CBaseRenderer.
References m_bConfigured.
LoadCLUT()
bool CLinuxRendererGL::LoadCLUT () protected
References CMS_DATA_FMT_RGB, DeleteCLUT(), CColorManager::Get3dLutSize(), CLog::Log(), LOGDEBUG, LOGERROR, m_CLUT, m_CLUTsize, m_cmsToken, m_ColorManager, m_srcPrimaries, and m_tCLUTTex.
Referenced by Configure(), and UpdateVideoFilter().
LoadPlane()
void CLinuxRendererGL::LoadPlane (CYuvPlane & plane, int type, unsigned width, unsigned height, int stride, int bpp, void * data) protected
References data(), KODI::UTILS::GL::glFormatElementByteCount(), CLinuxRendererGL::CYuvPlane::id, m_textureTarget, CLinuxRendererGL::CYuvPlane::pbo, CLinuxRendererGL::CYuvPlane::texheight, and CLinuxRendererGL::CYuvPlane::texwidth.
Referenced by UploadNV12Texture(), UploadYUV422PackedTexture(), and UploadYV12Texture().
LoadShaders()
void CLinuxRendererGL::LoadShaders (int field = FIELD_FULL) protected virtual
References Shaders::CGLSLShaderProgram::CompileAndLink(), CServiceBroker::GetSettingsComponent(), CBaseRenderer::GetShaderFormat(), LoadShadersHook(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_CLUTsize, m_cmsOn, m_ditherDepth, m_fullRange, m_intermediateGammaCorrection, m_nonLinStretch, m_pboSupported, m_pboUsed, m_pYUVShader, m_reloadShaders, m_renderMethod, m_renderQuality, m_scalingMethod, m_srcPrimaries, m_tCLUTTex, m_textureTarget, m_toneMap, m_toneMapMethod, CVideoSettings::m_ToneMapMethod, m_useDithering, CBaseRenderer::m_videoSettings, RENDER_GLSL, RQ_MULTIPASS, RQ_SINGLEPASS, Shaders::GL::BaseYUV2RGBGLSLShader::SetConvertFullColorRange(), CSettings::SETTING_VIDEOPLAYER_RENDERMETHOD, UpdateVideoFilter(), VS_SCALINGMETHOD_LANCZOS3_FAST, and VS_SCALINGMETHOD_SPLINE36_FAST.
Referenced by RenderSinglePass(), RenderToFBO(), and ValidateRenderTarget().
LoadShadersHook()
virtual bool CLinuxRendererGL::LoadShadersHook () inline protected virtual
Reimplemented in CRendererVAAPIGL, CRendererVDPAU, CRendererVTB, and CRendererVTB.
Referenced by LoadShaders().
Register()
bool CLinuxRendererGL::Register () static
References Create(), and VIDEOPLAYER::CRendererFactory::RegisterRenderer().
Referenced by CWinSystemOSX::CreateNewWindow(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::InitWindowSystem(), and KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext().
ReleaseBuffer()
void CLinuxRendererGL::ReleaseBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
Reimplemented in CRendererVAAPIGL, CRendererVDPAU, CRendererVTB, and CRendererVTB.
References m_buffers, CVideoBuffer::Release(), and CLinuxRendererGL::CPictureBuffer::videoBuffer.
Referenced by Flush(), CRendererVAAPIGL::ReleaseBuffer(), CRendererVDPAU::ReleaseBuffer(), and UnInit().
Render()
bool CLinuxRendererGL::Render (unsigned int flags, int renderBuffer) protected
References AfterRenderHook(), FIELD_BOT, FIELD_FULL, FIELD_TOP, m_currentField, m_renderMethod, m_renderQuality, RENDER_FLAG_BOT, RENDER_FLAG_TOP, RENDER_GLSL, RenderFromFBO(), RenderHook(), RenderSinglePass(), RenderToFBO(), RQ_LOW, RQ_MULTIPASS, RQ_SINGLEPASS, UpdateVideoFilter(), UploadTexture(), and VerifyGLState.
Referenced by RenderCapture(), and RenderUpdate().
RenderCapture()
bool CLinuxRendererGL::RenderCapture (int index, CRenderCapture * capture) override virtual
Implements CBaseRenderer.
References CRenderCapture::BeginRender(), CRenderCapture::EndRender(), CRenderCapture::GetHeight(), CRenderCapture::GetRenderBuffer(), CRenderCapture::GetWidth(), CServiceBroker::GetWinSystem(), glMatrixModview, index(), CMatrixGLStack::Load(), m_bValidated, CBaseRenderer::m_destRect, CBaseRenderer::MarkDirty(), CMatrixGLStack::PopLoad(), CMatrixGLStack::Push(), Render(), RENDER_FLAG_NOOSD, CBaseRenderer::restoreRotatedCoords(), CBaseRenderer::saveRotatedCoords(), CMatrixGL::Scalef(), CRectGen< T >::SetRect(), CBaseRenderer::syncDestRectToRotatedPoints(), and CMatrixGL::Translatef().
RenderFromFBO()
void CLinuxRendererGL::RenderFromFBO () protected
References Shaders::CGLSLShaderProgram::Disable(), Shaders::CGLSLShaderProgram::Enable(), CMatrixGLStack::Get(), CServiceBroker::GetAppComponents(), Shaders::GL::BaseVideoFilterShader::GetCoordLoc(), CDisplaySettings::GetInstance(), CServiceBroker::GetSettingsComponent(), Shaders::GL::BaseVideoFilterShader::GetTextureFilter(), Shaders::GL::BaseVideoFilterShader::GetVertexLoc(), glMatrixModview, glMatrixProject, CLog::Log(), LOGERROR, m_fbo, m_pVideoFilterShader, CBaseRenderer::m_rotatedDestCoords, m_scalingMethod, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, Shaders::GL::BaseVideoFilterShader::SetHeight(), Shaders::GL::BaseVideoFilterShader::SetMatrices(), Shaders::GL::BaseVideoFilterShader::SetNonLinStretch(), Shaders::GL::BaseVideoFilterShader::SetSourceTexture(), Shaders::GL::BaseVideoFilterShader::SetWidth(), VerifyGLState, VS_SCALINGMETHOD_NEAREST, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by Render(), CRendererVDPAU::RenderHook(), and RenderProgressiveWeave().
RenderHook()
virtual bool CLinuxRendererGL::RenderHook (int idx) inline protected virtual
Reimplemented in CRendererVAAPIGL, and CRendererVDPAU.
Referenced by Render().
RenderProgressiveWeave()
void CLinuxRendererGL::RenderProgressiveWeave (int renderBuffer, int field) protected
References FIELD_BOT, FIELD_TOP, CRectGen< T >::Height(), index(), CBaseRenderer::m_destRect, m_fbo, m_renderQuality, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, RenderFromFBO(), RenderSinglePass(), RenderToFBO(), RQ_MULTIPASS, stipple_weave, and CRectGen< T >::Width().
Referenced by CRendererVDPAU::RenderHook().
RenderRGB()
void CLinuxRendererGL::RenderRGB (int renderBuffer, int field) protected
References Shaders::CGLSLShaderProgram::Disable(), Shaders::CGLSLShaderProgram::Enable(), FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, CMatrixGLStack::Get(), CServiceBroker::GetAppComponents(), Shaders::GL::BaseVideoFilterShader::GetCoordLoc(), CDisplaySettings::GetInstance(), GetPlaneTextureSize(), CServiceBroker::GetSettingsComponent(), Shaders::GL::BaseVideoFilterShader::GetTextureFilter(), Shaders::GL::BaseVideoFilterShader::GetVertexLoc(), glMatrixModview, glMatrixProject, CLinuxRendererGL::CYuvPlane::id, index(), CLog::Log(), LOGERROR, m_buffers, m_pVideoFilterShader, CBaseRenderer::m_rotatedDestCoords, m_scalingMethod, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, m_textureTarget, CLinuxRendererGL::CYuvPlane::rect, Shaders::GL::BaseVideoFilterShader::SetHeight(), Shaders::GL::BaseVideoFilterShader::SetMatrices(), Shaders::GL::BaseVideoFilterShader::SetNonLinStretch(), Shaders::GL::BaseVideoFilterShader::SetSourceTexture(), Shaders::GL::BaseVideoFilterShader::SetWidth(), VerifyGLState, VS_SCALINGMETHOD_NEAREST, CPointGen< T >::x, CRectGen< T >::x1, CRectGen< T >::x2, CPointGen< T >::y, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CRendererVDPAU::RenderHook().
RenderSinglePass()
void CLinuxRendererGL::RenderSinglePass (int renderBuffer, int field) protected
References CheckVideoParameters(), Shaders::CGLSLShaderProgram::Disable(), CLinuxRendererGL::CPictureBuffer::displayMetadata, Shaders::CGLSLShaderProgram::Enable(), FIELD_BOT, FIELD_TOP, CLinuxRendererGL::CPictureBuffer::fields, CMatrixGLStack::Get(), CServiceBroker::GetAppComponents(), CDisplaySettings::GetInstance(), CServiceBroker::GetSettingsComponent(), Shaders::GL::BaseYUV2RGBGLSLShader::GetUcoordLoc(), Shaders::GL::BaseYUV2RGBGLSLShader::GetVcoordLoc(), Shaders::GL::BaseYUV2RGBGLSLShader::GetVertexLoc(), Shaders::GL::BaseYUV2RGBGLSLShader::GetYcoordLoc(), glMatrixModview, glMatrixProject, CLinuxRendererGL::CPictureBuffer::hasDisplayMetadata, CLinuxRendererGL::CPictureBuffer::hasLightMetadata, index(), CLinuxRendererGL::CPictureBuffer::lightMetadata, LoadShaders(), CVideoSettings::m_Brightness, m_buffers, CVideoSettings::m_Contrast, m_pYUVShader, m_reloadShaders, CBaseRenderer::m_rotatedDestCoords, CLinuxRendererGL::CPictureBuffer::m_srcBits, CLinuxRendererGL::CPictureBuffer::m_srcColSpace, CLinuxRendererGL::CPictureBuffer::m_srcFullRange, CLinuxRendererGL::CPictureBuffer::m_srcTextureBits, m_textureTarget, m_toneMapMethod, CVideoSettings::m_ToneMapParam, CBaseRenderer::m_videoSettings, YuvImage::MAX_PLANES, Shaders::GL::BaseYUV2RGBGLSLShader::SetBlack(), Shaders::GL::BaseYUV2RGBGLSLShader::SetColParams(), Shaders::GL::BaseYUV2RGBGLSLShader::SetContrast(), Shaders::GL::BaseYUV2RGBGLSLShader::SetDisplayMetadata(), Shaders::GL::BaseYUV2RGBGLSLShader::SetField(), Shaders::GL::BaseYUV2RGBGLSLShader::SetHeight(), Shaders::GL::BaseYUV2RGBGLSLShader::SetMatrices(), Shaders::GL::BaseYUV2RGBGLSLShader::SetNonLinStretch(), Shaders::GL::BaseYUV2RGBGLSLShader::SetToneMapParam(), Shaders::GL::BaseYUV2RGBGLSLShader::SetWidth(), VerifyGLState, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by Render(), CRendererVDPAU::RenderHook(), and RenderProgressiveWeave().
RenderToFBO()
void CLinuxRendererGL::RenderToFBO (int renderBuffer, int field, bool weave = false) protected
References CheckVideoParameters(), Shaders::CGLSLShaderProgram::Disable(), CLinuxRendererGL::CPictureBuffer::displayMetadata, Shaders::CGLSLShaderProgram::Enable(), FIELD_BOT, FIELD_TOP, CLinuxRendererGL::CPictureBuffer::fields, CMatrixGLStack::Get(), Shaders::GL::BaseYUV2RGBGLSLShader::GetUcoordLoc(), Shaders::GL::BaseYUV2RGBGLSLShader::GetVcoordLoc(), Shaders::GL::BaseYUV2RGBGLSLShader::GetVertexLoc(), CRenderSystemGL::GetViewPort(), Shaders::GL::BaseYUV2RGBGLSLShader::GetYcoordLoc(), glMatrixModview, glMatrixProject, CLinuxRendererGL::CPictureBuffer::hasDisplayMetadata, CLinuxRendererGL::CPictureBuffer::hasLightMetadata, index(), CLinuxRendererGL::CPictureBuffer::lightMetadata, CMatrixGLStack::Load(), CMatrixGL::LoadIdentity(), LoadShaders(), CLog::Log(), LOGERROR, CVideoSettings::m_Brightness, m_buffers, CVideoSettings::m_Contrast, m_currentField, m_fbo, m_pYUVShader, m_reloadShaders, m_renderSystem, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, CLinuxRendererGL::CPictureBuffer::m_srcBits, CLinuxRendererGL::CPictureBuffer::m_srcColSpace, CLinuxRendererGL::CPictureBuffer::m_srcFullRange, CLinuxRendererGL::CPictureBuffer::m_srcTextureBits, m_textureTarget, m_toneMapMethod, CVideoSettings::m_ToneMapParam, CBaseRenderer::m_videoSettings, YuvImage::MAX_PLANES, Shaders::CShaderProgram::OK(), CMatrixGL::Ortho2D(), CMatrixGLStack::PopLoad(), CMatrixGLStack::Push(), Shaders::GL::BaseYUV2RGBGLSLShader::SetBlack(), Shaders::GL::BaseYUV2RGBGLSLShader::SetColParams(), Shaders::GL::BaseYUV2RGBGLSLShader::SetContrast(), Shaders::GL::BaseYUV2RGBGLSLShader::SetDisplayMetadata(), Shaders::GL::BaseYUV2RGBGLSLShader::SetField(), Shaders::GL::BaseYUV2RGBGLSLShader::SetHeight(), Shaders::GL::BaseYUV2RGBGLSLShader::SetMatrices(), Shaders::GL::BaseYUV2RGBGLSLShader::SetNonLinStretch(), Shaders::GL::BaseYUV2RGBGLSLShader::SetToneMapParam(), CRenderSystemGL::SetViewPort(), Shaders::GL::BaseYUV2RGBGLSLShader::SetWidth(), and VerifyGLState.
Referenced by Render(), CRendererVDPAU::RenderHook(), and RenderProgressiveWeave().
RenderUpdate()
void CLinuxRendererGL::RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override virtual
Implements CBaseRenderer.
References ClearBackBuffer(), DrawBlackBars(), index(), m_iYV12RenderBuffer, m_pVideoFilterShader, m_pYUVShader, CBaseRenderer::ManageRenderArea(), Render(), Shaders::GL::BaseVideoFilterShader::SetAlpha(), Shaders::GL::BaseYUV2RGBGLSLShader::SetAlpha(), ValidateRenderer(), and VerifyGLState.
SetBufferSize()
void CLinuxRendererGL::SetBufferSize (int numBuffers) inline override virtual
Reimplemented from CBaseRenderer.
References m_NumYV12Buffers.
SetTextureFilter()
void CLinuxRendererGL::SetTextureFilter (GLenum method) protected
References f, FIELD_BOT, FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, CLinuxRendererGL::CYuvPlane::id, m_buffers, m_NumYV12Buffers, m_textureTarget, and VerifyGLState.
Referenced by UpdateVideoFilter().
Supports() [1/2]
bool CLinuxRendererGL::Supports (ERENDERFEATURE feature) const override virtual
Reimplemented from CBaseRenderer.
Reimplemented in CRendererVAAPIGL, and CRendererVDPAU.
References RENDERFEATURE_BRIGHTNESS, RENDERFEATURE_CONTRAST, RENDERFEATURE_NONLINSTRETCH, RENDERFEATURE_PIXEL_RATIO, RENDERFEATURE_POSTPROCESS, RENDERFEATURE_ROTATION, RENDERFEATURE_STRETCH, RENDERFEATURE_TONEMAP, RENDERFEATURE_VERTICAL_SHIFT, and RENDERFEATURE_ZOOM.
Referenced by CRendererVAAPIGL::Supports(), CRendererVAAPIGL::Supports(), CRendererVDPAU::Supports(), and UpdateVideoFilter().
Supports() [2/2]
bool CLinuxRendererGL::Supports (ESCALINGMETHOD method) const override virtual
Implements CBaseRenderer.
Reimplemented in CRendererVAAPIGL, and CRendererVDPAU.
References CRenderSystemBase::GetRenderVersion(), CServiceBroker::GetSettingsComponent(), CRectGen< T >::Height(), CRenderSystemGL::IsExtSupported(), CBaseRenderer::m_destRect, CBaseRenderer::m_format, m_renderMethod, m_renderSystem, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, RENDER_GLSL, CSettings::SETTING_VIDEOPLAYER_HQSCALERS, VS_SCALINGMETHOD_AUTO, VS_SCALINGMETHOD_CUBIC_0_075, VS_SCALINGMETHOD_CUBIC_0_1, VS_SCALINGMETHOD_CUBIC_B_SPLINE, VS_SCALINGMETHOD_CUBIC_CATMULL, VS_SCALINGMETHOD_CUBIC_MITCHELL, VS_SCALINGMETHOD_LANCZOS2, VS_SCALINGMETHOD_LANCZOS3, VS_SCALINGMETHOD_LANCZOS3_FAST, VS_SCALINGMETHOD_LINEAR, VS_SCALINGMETHOD_NEAREST, VS_SCALINGMETHOD_SPLINE36, VS_SCALINGMETHOD_SPLINE36_FAST, and CRectGen< T >::Width().
SupportsMultiPassRendering()
bool CLinuxRendererGL::SupportsMultiPassRendering () override virtual
Implements CBaseRenderer.
References CRenderSystemGL::IsExtSupported(), and m_renderSystem.
UnBindPbo()
void CLinuxRendererGL::UnBindPbo (CPictureBuffer & buff) protected
References CLinuxRendererGL::CPictureBuffer::image, YuvImage::MAX_PLANES, CLinuxRendererGL::CPictureBuffer::pbo, PBO_OFFSET, YuvImage::plane, and YuvImage::planesize.
Referenced by UploadTexture(), and CRendererVAAPIGL::UploadTexture().
UnInit()
void CLinuxRendererGL::UnInit () override virtual
Implements CBaseRenderer.
References DeleteCLUT(), DeleteTexture(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, m_bConfigured, m_bValidated, m_fbo, NUM_BUFFERS, and ReleaseBuffer().
Referenced by ~CLinuxRendererGL().
Update()
void CLinuxRendererGL::Update () override virtual
Implements CBaseRenderer.
References m_bConfigured, m_scalingMethodGui, CBaseRenderer::ManageRenderArea(), and ValidateRenderTarget().
UpdateVideoFilter()
void CLinuxRendererGL::UpdateVideoFilter () protected
References Shaders::CGLSLShaderProgram::CompileAndLink(), CDisplaySettings::GetInstance(), CDisplaySettings::GetPixelRatio(), CRenderSystemBase::GetRenderVersion(), CServiceBroker::GetSettingsComponent(), CBaseRenderer::GetShaderFormat(), CBaseRenderer::GetVideoRect(), CRectGen< T >::Height(), CDisplaySettings::IsNonLinearStretched(), LoadCLUT(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_CLUTsize, m_cmsOn, m_cmsToken, m_ColorManager, m_ditherDepth, m_fbo, CBaseRenderer::m_fps, m_fullRange, m_intermediateFormat, m_intermediateGammaCorrection, m_intermediateType, m_nonLinStretch, m_nonLinStretchGui, m_pixelRatio, m_pVideoFilterShader, m_reloadShaders, m_renderMethod, m_renderQuality, m_renderSystem, m_scalingMethod, CVideoSettings::m_ScalingMethod, m_scalingMethodGui, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, m_srcPrimaries, m_tCLUTTex, m_useDithering, CBaseRenderer::m_videoSettings, m_viewRect, RENDER_GLSL, RENDERFEATURE_NONLINSTRETCH, RQ_MULTIPASS, RQ_SINGLEPASS, SetTextureFilter(), SHADER_NV12, SHADER_YV12, SHADER_YV12_16, Supports(), VerifyGLState, VS_SCALINGMETHOD_AUTO, VS_SCALINGMETHOD_BICUBIC_SOFTWARE, VS_SCALINGMETHOD_CUBIC_0_075, VS_SCALINGMETHOD_CUBIC_0_1, VS_SCALINGMETHOD_CUBIC_B_SPLINE, VS_SCALINGMETHOD_CUBIC_CATMULL, VS_SCALINGMETHOD_CUBIC_MITCHELL, VS_SCALINGMETHOD_LANCZOS2, VS_SCALINGMETHOD_LANCZOS3, VS_SCALINGMETHOD_LANCZOS3_FAST, VS_SCALINGMETHOD_LANCZOS_SOFTWARE, VS_SCALINGMETHOD_LINEAR, VS_SCALINGMETHOD_NEAREST, VS_SCALINGMETHOD_SINC8, VS_SCALINGMETHOD_SINC_SOFTWARE, VS_SCALINGMETHOD_SPLINE36, VS_SCALINGMETHOD_SPLINE36_FAST, and CRectGen< T >::Width().
Referenced by LoadShaders(), Render(), CRendererVDPAU::RenderHook(), and ValidateRenderTarget().
UploadNV12Texture()
bool CLinuxRendererGL::UploadNV12Texture (int index) protected
References YuvImage::bpp, YuvImage::cshift_x, YuvImage::cshift_y, FIELD_BOT, FIELD_FULL, FIELD_TOP, fields, CLinuxRendererGL::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGL::CPictureBuffer::image, LoadPlane(), m_buffers, m_currentField, YuvImage::plane, YuvImage::stride, VerifyGLState, and YuvImage::width.
Referenced by UploadTexture(), and CRendererVAAPIGL::UploadTexture().
UploadTexture()
bool CLinuxRendererGL::UploadTexture (int index) protected virtual
Reimplemented in CRendererVAAPIGL, CRendererVDPAU, CRendererVTB, and CRendererVTB.
References BindPbo(), CalculateTextureSourceRects(), CVideoBuffer::CopyNV12Picture(), CVideoBuffer::CopyPicture(), CVideoBuffer::CopyYUV422PackedPicture(), CVideoBuffer::GetPlanes(), CVideoBuffer::GetStrides(), CLinuxRendererGL::CPictureBuffer::image, index(), CLinuxRendererGL::CPictureBuffer::loaded, m_buffers, CBaseRenderer::m_format, YuvImage::plane, YuvImage::stride, UnBindPbo(), UploadNV12Texture(), UploadYUV422PackedTexture(), UploadYV12Texture(), and CLinuxRendererGL::CPictureBuffer::videoBuffer.
Referenced by Render().
UploadYUV422PackedTexture()
bool CLinuxRendererGL::UploadYUV422PackedTexture (int index) protected
References YuvImage::bpp, FIELD_BOT, FIELD_FULL, FIELD_TOP, CLinuxRendererGL::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGL::CPictureBuffer::image, LoadPlane(), m_buffers, m_currentField, YuvImage::plane, YuvImage::stride, VerifyGLState, and YuvImage::width.
Referenced by UploadTexture().
UploadYV12Texture()
bool CLinuxRendererGL::UploadYV12Texture (int index) protected
References YuvImage::bpp, YuvImage::cshift_x, YuvImage::cshift_y, FIELD_BOT, FIELD_FULL, FIELD_TOP, CLinuxRendererGL::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGL::CPictureBuffer::image, LoadPlane(), m_buffers, m_currentField, YuvImage::plane, YuvImage::stride, VerifyGLState, and YuvImage::width.
Referenced by UploadTexture().
ValidateRenderer()
bool CLinuxRendererGL::ValidateRenderer () protected
References FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, CLinuxRendererGL::CYuvPlane::id, index(), m_bConfigured, m_buffers, m_iYV12RenderBuffer, and ValidateRenderTarget().
Referenced by RenderUpdate().
ValidateRenderTarget()
bool CLinuxRendererGL::ValidateRenderTarget () protected virtual
References CreateTexture(), DeleteTexture(), LoadShaders(), CLog::Log(), LOGINFO, m_bValidated, m_NumYV12Buffers, m_renderMethod, m_scalingMethodGui, m_textureTarget, NUM_BUFFERS, and UpdateVideoFilter().
Referenced by Update(), and ValidateRenderer().
Member Data Documentation
fbo
CFrameBufferObject CLinuxRendererGL::fbo
height
float CLinuxRendererGL::height
m_bConfigured
bool CLinuxRendererGL::m_bConfigured = false protected
Referenced by Configure(), IsConfigured(), UnInit(), Update(), and ValidateRenderer().
m_buffers
CPictureBuffer CLinuxRendererGL::m_buffers[NUM_BUFFERS] protected
Referenced by AddVideoPicture(), CRendererVTB::AfterRenderHook(), CalculateTextureSourceRects(), CheckVideoParameters(), CreateNV12Texture(), CRendererVAAPIGL::CreateTexture(), CRendererVTB::CreateTexture(), CRendererVDPAU::CreateVDPAUTexture(), CRendererVDPAU::CreateVDPAUTexture420(), CreateYUV422PackedTexture(), CreateYV12Texture(), DeleteNV12Texture(), DeleteTexture(), CRendererVAAPIGL::DeleteTexture(), CRendererVTB::DeleteTexture(), CRendererVDPAU::DeleteVDPAUTexture(), CRendererVDPAU::DeleteVDPAUTexture420(), DeleteYUV422PackedTexture(), DeleteYV12Texture(), CRendererVTB::NeedBuffer(), CRendererVTB::ReleaseBuffer(), ReleaseBuffer(), RenderRGB(), RenderSinglePass(), RenderToFBO(), SetTextureFilter(), UploadNV12Texture(), UploadTexture(), CRendererVAAPIGL::UploadTexture(), CRendererVTB::UploadTexture(), CRendererVDPAU::UploadVDPAUTexture(), CRendererVDPAU::UploadVDPAUTexture420(), UploadYUV422PackedTexture(), UploadYV12Texture(), and ValidateRenderer().
m_bValidated
bool CLinuxRendererGL::m_bValidated = false protected
Referenced by Configure(), Flush(), RenderCapture(), UnInit(), and ValidateRenderTarget().
m_clearColour
float CLinuxRendererGL::m_clearColour = 0.0f protected
Referenced by ClearBackBufferQuad(), Configure(), and DrawBlackBars().
m_CLUT
uint16_t* CLinuxRendererGL::m_CLUT protected
Referenced by CLinuxRendererGL(), and LoadCLUT().
m_CLUTsize
int CLinuxRendererGL::m_CLUTsize protected
Referenced by CLinuxRendererGL(), LoadCLUT(), LoadShaders(), and UpdateVideoFilter().
m_cmsOn
bool CLinuxRendererGL::m_cmsOn protected
Referenced by CLinuxRendererGL(), Configure(), LoadShaders(), and UpdateVideoFilter().
m_cmsToken
int CLinuxRendererGL::m_cmsToken protected
Referenced by CLinuxRendererGL(), Configure(), LoadCLUT(), and UpdateVideoFilter().
m_ColorManager
std::unique_ptr<CColorManager> CLinuxRendererGL::m_ColorManager protected
Referenced by CLinuxRendererGL(), Configure(), LoadCLUT(), and UpdateVideoFilter().
m_currentField
int CLinuxRendererGL::m_currentField = FIELD_FULL protected
Referenced by Render(), CRendererVDPAU::RenderHook(), RenderToFBO(), UploadNV12Texture(), UploadYUV422PackedTexture(), and UploadYV12Texture().
m_ditherDepth
unsigned int CLinuxRendererGL::m_ditherDepth protected
Referenced by CLinuxRendererGL(), LoadShaders(), and UpdateVideoFilter().
[struct]
struct { ... } CLinuxRendererGL::m_fbo
Referenced by CLinuxRendererGL(), Flush(), RenderFromFBO(), RenderProgressiveWeave(), RenderToFBO(), UnInit(), and UpdateVideoFilter().
m_fullRange
bool CLinuxRendererGL::m_fullRange protected
Referenced by CLinuxRendererGL(), LoadShaders(), CRendererVDPAU::LoadShadersHook(), and UpdateVideoFilter().
m_intermediateFormat
GLint CLinuxRendererGL::m_intermediateFormat {GL_RGBA8} protected
Referenced by CLinuxRendererGL(), and UpdateVideoFilter().
m_intermediateGammaCorrection
bool CLinuxRendererGL::m_intermediateGammaCorrection {false} protected
Referenced by CLinuxRendererGL(), LoadShaders(), and UpdateVideoFilter().
m_intermediateType
GLint CLinuxRendererGL::m_intermediateType {GL_UNSIGNED_BYTE} protected
Referenced by CLinuxRendererGL(), and UpdateVideoFilter().
m_iYV12RenderBuffer
int CLinuxRendererGL::m_iYV12RenderBuffer = 0 protected
Referenced by Flush(), RenderUpdate(), and ValidateRenderer().
m_nonLinStretch
bool CLinuxRendererGL::m_nonLinStretch = false protected
Referenced by Configure(), LoadShaders(), and UpdateVideoFilter().
m_nonLinStretchGui
bool CLinuxRendererGL::m_nonLinStretchGui = false protected
Referenced by Configure(), and UpdateVideoFilter().
m_NumYV12Buffers
int CLinuxRendererGL::m_NumYV12Buffers = 0 protected
Referenced by Flush(), SetBufferSize(), SetTextureFilter(), and ValidateRenderTarget().
m_pboSupported
bool CLinuxRendererGL::m_pboSupported = true protected
Referenced by Configure(), and LoadShaders().
m_pboUsed
bool CLinuxRendererGL::m_pboUsed = false protected
Referenced by CreateNV12Texture(), CreateYUV422PackedTexture(), CreateYV12Texture(), and LoadShaders().
m_pixelRatio
float CLinuxRendererGL::m_pixelRatio = 0.0f protected
Referenced by Configure(), and UpdateVideoFilter().
m_pVideoFilterShader
Shaders::GL::BaseVideoFilterShader* CLinuxRendererGL::m_pVideoFilterShader = nullptr protected
Referenced by Flush(), RenderFromFBO(), RenderRGB(), RenderUpdate(), UpdateVideoFilter(), and ~CLinuxRendererGL().
m_pYUVShader
Shaders::GL::BaseYUV2RGBGLSLShader* CLinuxRendererGL::m_pYUVShader = nullptr protected
Referenced by Flush(), LoadShaders(), RenderSinglePass(), RenderToFBO(), RenderUpdate(), and ~CLinuxRendererGL().
m_reloadShaders
int CLinuxRendererGL::m_reloadShaders = 0 protected
Referenced by CheckVideoParameters(), LoadShaders(), RenderSinglePass(), RenderToFBO(), and UpdateVideoFilter().
m_renderMethod
int CLinuxRendererGL::m_renderMethod = RENDER_GLSL protected
Referenced by LoadShaders(), CRendererVDPAU::LoadShadersHook(), Render(), CRendererVDPAU::Supports(), Supports(), UpdateVideoFilter(), and ValidateRenderTarget().
m_renderQuality
RenderQuality CLinuxRendererGL::m_renderQuality = RQ_SINGLEPASS protected
Referenced by LoadShaders(), Render(), CRendererVDPAU::RenderHook(), RenderProgressiveWeave(), and UpdateVideoFilter().
m_renderSystem
CRenderSystemGL* CLinuxRendererGL::m_renderSystem = nullptr protected
Referenced by ClearBackBufferQuad(), CLinuxRendererGL(), DrawBlackBars(), GetInternalFormat(), RenderToFBO(), Supports(), SupportsMultiPassRendering(), and UpdateVideoFilter().
m_scalingMethod
ESCALINGMETHOD CLinuxRendererGL::m_scalingMethod = VS_SCALINGMETHOD_LINEAR protected
Referenced by LoadShaders(), RenderFromFBO(), RenderRGB(), and UpdateVideoFilter().
m_scalingMethodGui
ESCALINGMETHOD CLinuxRendererGL::m_scalingMethodGui = VS_SCALINGMETHOD_MAX protected
Referenced by Configure(), Update(), UpdateVideoFilter(), and ValidateRenderTarget().
m_srcPrimaries
AVColorPrimaries CLinuxRendererGL::m_srcPrimaries protected
Referenced by CheckVideoParameters(), Configure(), LoadCLUT(), LoadShaders(), and UpdateVideoFilter().
m_tCLUTTex
GLuint CLinuxRendererGL::m_tCLUTTex protected
Referenced by CLinuxRendererGL(), DeleteCLUT(), LoadCLUT(), LoadShaders(), and UpdateVideoFilter().
m_textureTarget
GLenum CLinuxRendererGL::m_textureTarget = GL_TEXTURE_2D protected
Referenced by CalculateTextureSourceRects(), CreateNV12Texture(), CreateYUV422PackedTexture(), CreateYV12Texture(), GetPlaneTextureSize(), LoadPlane(), LoadShaders(), CRendererVTB::LoadShadersHook(), RenderRGB(), RenderSinglePass(), RenderToFBO(), SetTextureFilter(), CRendererVAAPIGL::UploadTexture(), CRendererVTB::UploadTexture(), CRendererVDPAU::UploadVDPAUTexture(), CRendererVDPAU::UploadVDPAUTexture420(), and ValidateRenderTarget().
m_toneMap
bool CLinuxRendererGL::m_toneMap = false protected
Referenced by CheckVideoParameters(), Configure(), and LoadShaders().
m_toneMapMethod
ETONEMAPMETHOD CLinuxRendererGL::m_toneMapMethod = VS_TONEMAPMETHOD_OFF protected
Referenced by CheckVideoParameters(), LoadShaders(), RenderSinglePass(), and RenderToFBO().
m_useDithering
bool CLinuxRendererGL::m_useDithering protected
Referenced by CLinuxRendererGL(), LoadShaders(), and UpdateVideoFilter().
m_viewRect
CRect CLinuxRendererGL::m_viewRect protected
Referenced by UpdateVideoFilter().
width
float CLinuxRendererGL::width
The documentation for this class was generated from the following files:
LinuxRendererGL.h
LinuxRendererGL.cpp