Kodi Documentation: KODI::PLATFORM::WINDOWS10::App Struct Reference
KODI::PLATFORM::WINDOWS10::App Struct Reference
#include <Win10App.h>
Public Member Functions
App ()
winrt::Windows::ApplicationModel::Core::IFrameworkView CreateView ()
void Initialize (const winrt::Windows::ApplicationModel::Core::CoreApplicationView &)
void SetWindow (const winrt::Windows::UI::Core::CoreWindow &)
void Load (const winrt::hstring &entryPoint)
void Run ()
void Uninitialize ()
Protected Member Functions
void OnActivated (const winrt::Windows::ApplicationModel::Core::CoreApplicationView &, const winrt::Windows::ApplicationModel::Activation::IActivatedEventArgs &)
void OnSuspending (const winrt::Windows::Foundation::IInspectable &, const winrt::Windows::ApplicationModel::SuspendingEventArgs &)
void OnResuming (const winrt::Windows::Foundation::IInspectable &, const winrt::Windows::Foundation::IInspectable &)
Private Attributes
std::vector< char * > m_argv
Constructor & Destructor Documentation
App()
App::App () default
Member Function Documentation
CreateView()
winrt::Windows::ApplicationModel::Core::IFrameworkView KODI::PLATFORM::WINDOWS10::App::CreateView () inline
Initialize()
void App::Initialize (const winrt::Windows::ApplicationModel::Core::CoreApplicationView &)
References OnActivated(), OnResuming(), and OnSuspending().
Load()
void App::Load (const winrt::hstring & entryPoint)
OnActivated()
void App::OnActivated (const winrt::Windows::ApplicationModel::Core::CoreApplicationView & , const winrt::Windows::ApplicationModel::Activation::IActivatedEventArgs &) protected
References KODI::PLATFORM::WINDOWS::FromW(), m_argv, and push_back().
Referenced by Initialize().
OnResuming()
void App::OnResuming (const winrt::Windows::Foundation::IInspectable & , const winrt::Windows::Foundation::IInspectable &) protected
Referenced by Initialize().
OnSuspending()
void App::OnSuspending (const winrt::Windows::Foundation::IInspectable & , const winrt::Windows::ApplicationModel::SuspendingEventArgs &) protected
Referenced by Initialize().
Run()
void App::Run ()
References CAppParamParser::GetAppParams(), CSysInfo::GetWindowsDeviceFamily(), m_argv, CAppParamParser::Parse(), CAppEnvironment::SetUp(), CAppEnvironment::TearDown(), XBMC_Run(), and CSysInfo::Xbox.
SetWindow()
void App::SetWindow (const winrt::Windows::UI::Core::CoreWindow &)
Uninitialize()
void App::Uninitialize ()
Member Data Documentation
m_argv
std::vector<char*> KODI::PLATFORM::WINDOWS10::App::m_argv private
Referenced by OnActivated(), and Run().
The documentation for this struct was generated from the following files:
Win10App.h
Win10App.cpp