Kodi Documentation: JSONRPC::CFileItemHandler Class Reference
JSONRPC::CFileItemHandler Class Reference
#include <FileItemHandler.h>
Static Protected Member Functions
static void FillDetails (const ISerializable *info, const std::shared_ptr< CFileItem > &item, std::set< std::string > &fields, CVariant &result, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, bool sortLimit=true)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, int size, bool sortLimit=true)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const CVariant &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const std::set< std::string > &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
Static Protected Member Functions inherited from JSONRPC::CJSONUtils
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Static Private Member Functions
static void Sort (CFileItemList &items, const CVariant &parameterObject)
static bool GetField (const std::string &field, const CVariant &info, const std::shared_ptr< CFileItem > &item, CVariant &result, bool &fetchedArt, CThumbLoader *thumbLoader=nullptr)
Additional Inherited Members
Static Public Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
Member Function Documentation
FillDetails()
void CFileItemHandler::FillDetails (const ISerializable * info, const std::shared_ptr< CFileItem > & item, std::set< std::string > & fields, CVariant & result, CThumbLoader * thumbLoader = nullptr) static protected
References CVariant::empty(), fields, GetField(), and CVariant::isMember().
Referenced by HandleFileItem().
FillFileItemList()
bool CFileItemHandler::FillFileItemList (const CVariant & parameterObject, CFileItemList & list) static protected
References CFileItemList::Add(), CVariant::asString(), XFILE::CDirectory::Exists(), CFileUtils::Exists(), JSONRPC::CAudioLibrary::FillFileItemList(), JSONRPC::CFileOperations::FillFileItemList(), JSONRPC::CVideoLibrary::FillFileItemList(), URIUtils::GetFileName(), CUtil::GetTitleFromPath(), index(), URIUtils::IsURL(), CPictureInfoTag::Load(), and CFileItemList::Size().
Referenced by JSONRPC::CPlaylistOperations::HandleItemsParameter(), and JSONRPC::CPlayerOperations::Open().
GetField()
bool CFileItemHandler::GetField (const std::string & field, const CVariant & info, const std::shared_ptr< CFileItem > & item, CVariant & result, bool & fetchedArt, CThumbLoader * thumbLoader = nullptr) static private
References CVariant::asInteger(), CVariant::empty(), EPG_STRING_TOKEN_SEPARATOR, CThumbLoader::FillLibraryArt(), CServiceBroker::GetPVRManager(), CVariant::isMember(), CVariant::push_back(), PVR::CPVRManager::Recordings(), PVR::CPVRManager::Timers(), TVSHOWS, IMAGE_FILES::URLFromFile(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by FillDetails().
HandleFileItem() [1/2]
void CFileItemHandler::HandleFileItem (const char * ID, bool allowFile, const char * resultname, const std::shared_ptr< CFileItem > & item, const CVariant & parameterObject, const CVariant & validFields, CVariant & result, bool append = true, CThumbLoader * thumbLoader = nullptr) static protected
References CVariant::end_array(), fields, HandleFileItem(), ID, CVariant::isArray(), and CVariant::isMember().
Referenced by JSONRPC::CAudioLibrary::GetAlbumDetails(), JSONRPC::CAudioLibrary::GetArtistDetails(), JSONRPC::CPVROperations::GetBroadcastDetails(), JSONRPC::CPVROperations::GetChannelDetails(), JSONRPC::CVideoLibrary::GetEpisodeDetails(), JSONRPC::CFileOperations::GetFileDetails(), JSONRPC::CPlayerOperations::GetItem(), JSONRPC::CVideoLibrary::GetMovieDetails(), JSONRPC::CVideoLibrary::GetMovieSetDetails(), JSONRPC::CVideoLibrary::GetMusicVideoDetails(), JSONRPC::CPVROperations::GetRecordingDetails(), JSONRPC::CVideoLibrary::GetSeasonDetails(), JSONRPC::CAudioLibrary::GetSongDetails(), JSONRPC::CPVROperations::GetTimerDetails(), JSONRPC::CVideoLibrary::GetTVShowDetails(), HandleFileItem(), and HandleFileItemList().
HandleFileItem() [2/2]
void CFileItemHandler::HandleFileItem (const char * ID, bool allowFile, const char * resultname, const std::shared_ptr< CFileItem > & item, const CVariant & parameterObject, const std::set< std::string > & validFields, CVariant & result, bool append = true, CThumbLoader * thumbLoader = nullptr) static protected
References CVariant::append(), fields, FillDetails(), ID, MediaTypeAlbum, MediaTypeArtist, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSong, MediaTypeTvShow, CThumbLoader::OnLoaderStart(), and CVariant::VariantTypeNull.
HandleFileItemList() [1/2]
void CFileItemHandler::HandleFileItemList (const char * ID, bool allowFile, const char * resultname, CFileItemList & items, const CVariant & parameterObject, CVariant & result, bool sortLimit = true) static protected
References HandleFileItemList(), ID, and CFileItemList::Size().
Referenced by JSONRPC::CPVROperations::FillChannelGroupDetails(), JSONRPC::CPVROperations::GetBroadcasts(), JSONRPC::CPVROperations::GetChannels(), JSONRPC::CFileOperations::GetDirectory(), JSONRPC::CAudioLibrary::GetGenres(), JSONRPC::CVideoLibrary::GetGenres(), JSONRPC::CPlaylistOperations::GetItems(), JSONRPC::CVideoLibrary::GetMovieSets(), JSONRPC::CProfilesOperations::GetProfiles(), JSONRPC::CAudioLibrary::GetRecentlyAddedAlbums(), JSONRPC::CAudioLibrary::GetRecentlyAddedSongs(), JSONRPC::CAudioLibrary::GetRecentlyPlayedAlbums(), JSONRPC::CAudioLibrary::GetRecentlyPlayedSongs(), JSONRPC::CPVROperations::GetRecordings(), JSONRPC::CAudioLibrary::GetRoles(), JSONRPC::CFileOperations::GetRootDirectory(), JSONRPC::CVideoLibrary::GetSeasons(), JSONRPC::CVideoLibrary::GetTags(), JSONRPC::CPVROperations::GetTimers(), HandleFileItemList(), and JSONRPC::CVideoLibrary::HandleItems().
HandleFileItemList() [2/2]
void CFileItemHandler::HandleFileItemList (const char * ID, bool allowFile, const char * resultname, CFileItemList & items, const CVariant & parameterObject, CVariant & result, int size, bool sortLimit = true) static protected
References end(), CVariant::end_array(), fields, CFileItemList::Get(), HandleFileItem(), JSONRPC::CJSONUtils::HandleLimits(), ID, CVariant::isArray(), CVariant::isMember(), CThumbLoader::OnLoaderStart(), CVariant::reserve(), CFileItemList::Size(), and Sort().
Sort()
void CFileItemHandler::Sort (CFileItemList & items, const CVariant & parameterObject) static private
References JSONRPC::CJSONUtils::ParseSorting(), CFileItemList::Sort(), SortDescription::sortAttributes, SortDescription::sortBy, and SortDescription::sortOrder.
Referenced by HandleFileItemList().
The documentation for this class was generated from the following files:
FileItemHandler.h
FileItemHandler.cpp