Kodi Documentation: CRssManager Class Reference
CRssManager Class Reference
#include <RssManager.h>
Classes
struct READERCONTROL
Public Member Functions
void OnSettingsLoaded () override
Settings have been loaded.
void OnSettingsUnloaded () override
Setting values have been unloaded.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
void Start ()
void Stop ()
bool Load ()
bool Reload ()
void Clear ()
bool IsActive () const
bool GetReader (int controlID, int windowID, IRssObserver *observer, CRssReader *&reader)
const RssUrls & GetUrls () const
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingChanged (const std::shared_ptr< const CSetting > &setting)
The value of the given setting has changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsCleared ()
Settings have been cleared.
Static Public Member Functions
static CRssManager & GetInstance ()
Protected Member Functions
CRssManager ()
~CRssManager () override
Private Member Functions
CRssManager (const CRssManager &)=delete
CRssManager & operator= (const CRssManager &)=delete
Private Attributes
std::vector< READERCONTROL > m_readers
RssUrls m_mapRssUrls
bool m_bActive
CCriticalSection m_critical
Constructor & Destructor Documentation
CRssManager() [1/2]
CRssManager::CRssManager () protected
References m_bActive.
~CRssManager()
CRssManager::~CRssManager () override protected
References Stop().
CRssManager() [2/2]
CRssManager::CRssManager (const CRssManager &) private delete
Member Function Documentation
Clear()
void CRssManager::Clear ()
References m_critical, and m_mapRssUrls.
Referenced by OnSettingsUnloaded().
GetInstance()
CRssManager & CRssManager::GetInstance () static
Referenced by CGUIControlFactory::Create(), CSettings::InitializeISettingCallbacks(), CSettings::InitializeISettingsHandlers(), CNetworkServices::IsRssRunning(), CGUIRSSControl::Process(), anonymous_namespace{GUIBuiltins.cpp}::RefreshRSS(), CGUIRSSControl::Render(), CNetworkServices::StartRss(), CNetworkServices::StopRss(), CSettings::UninitializeISettingCallbacks(), and CSettings::UninitializeISettingsHandlers().
GetReader()
bool CRssManager::GetReader (int controlID, int windowID, IRssObserver * observer, CRssReader *& reader)
References CRssManager::READERCONTROL::controlID, m_critical, m_readers, CRssManager::READERCONTROL::reader, CRssReader::SetObserver(), CRssReader::UpdateObserver(), and CRssManager::READERCONTROL::windowID.
Referenced by CGUIRSSControl::Process().
GetUrls()
const RssUrls & CRssManager::GetUrls () const inline
References m_mapRssUrls.
Referenced by CGUIControlFactory::Create(), and CGUIRSSControl::Process().
IsActive()
bool CRssManager::IsActive () const inline
References m_bActive.
Referenced by CNetworkServices::IsRssRunning().
Load()
bool CRssManager::Load ()
References CFileUtils::Exists(), CServiceBroker::GetSettingsComponent(), RssSet::interval, CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGDEBUG, LOGERROR, m_critical, m_mapRssUrls, RssSet::rtl, and RssSet::url.
Referenced by OnSettingsLoaded(), and Reload().
OnSettingAction()
void CRssManager::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References ADDON::CHOICE_YES, CBuiltins::Execute(), CServiceBroker::GetAddonMgr(), ADDON::CAddonInstaller::GetInstance(), CBuiltins::GetInstance(), and CSettings::SETTING_LOOKANDFEEL_RSSEDIT.
OnSettingsLoaded()
void CRssManager::OnSettingsLoaded () override virtual
Settings have been loaded.
This callback can be used to trigger loading other settings.
Reimplemented from ISettingsHandler.
References Load().
OnSettingsUnloaded()
void CRssManager::OnSettingsUnloaded () override virtual
Setting values have been unloaded.
This callback can be used to trigger uninitializing any state variables (e.g. before re-loading the settings).
Reimplemented from ISettingsHandler.
References Clear().
operator=()
CRssManager & CRssManager::operator= (const CRssManager &) private delete
Reload()
bool CRssManager::Reload ()
References Load(), Start(), and Stop().
Referenced by anonymous_namespace{GUIBuiltins.cpp}::RefreshRSS().
Start()
void CRssManager::Start ()
References m_bActive.
Referenced by Reload(), and CNetworkServices::StartRss().
Stop()
void CRssManager::Stop ()
References m_bActive, m_critical, and m_readers.
Referenced by Reload(), CNetworkServices::StopRss(), and ~CRssManager().
Member Data Documentation
m_bActive
bool CRssManager::m_bActive private
Referenced by CRssManager(), IsActive(), Start(), and Stop().
m_critical
CCriticalSection CRssManager::m_critical private
Referenced by Clear(), GetReader(), Load(), and Stop().
m_mapRssUrls
RssUrls CRssManager::m_mapRssUrls private
Referenced by Clear(), GetUrls(), and Load().
m_readers
std::vector<READERCONTROL> CRssManager::m_readers private
Referenced by GetReader(), and Stop().
The documentation for this class was generated from the following files:
RssManager.h
RssManager.cpp