Kodi Documentation: JSONRPC::CAudioLibrary Class Reference
JSONRPC::CAudioLibrary Class Reference
#include <AudioLibrary.h>
Static Public Member Functions
static JSONRPC_STATUS GetProperties (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetArtists (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetArtistDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetAlbums (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetAlbumDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetSongs (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetSongDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetGenres (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetRoles (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetSources (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetAvailableArtTypes (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetAvailableArt (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetRecentlyAddedAlbums (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetRecentlyAddedSongs (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetRecentlyPlayedAlbums (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetRecentlyPlayedSongs (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetArtistDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetAlbumDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetSongDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Scan (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Export (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Clean (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static bool FillFileItem (const std::string &strFilename, std::shared_ptr< CFileItem > &item, const CVariant &parameterObject=CVariant(CVariant::VariantTypeArray))
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
static JSONRPC_STATUS GetAdditionalDetails (const CVariant &parameterObject, CFileItemList &items)
static JSONRPC_STATUS GetAdditionalArtistDetails (const CVariant &parameterObject, const CFileItemList &items, CMusicDatabase &musicdatabase)
static JSONRPC_STATUS GetAdditionalAlbumDetails (const CVariant &parameterObject, const CFileItemList &items, CMusicDatabase &musicdatabase)
static JSONRPC_STATUS GetAdditionalSongDetails (const CVariant &parameterObject, const CFileItemList &items, CMusicDatabase &musicdatabase)
static JSONRPC_STATUS RefreshArtist (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS RefreshAlbum (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Static Public Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
Static Private Member Functions
static void FillAlbumItem (const CAlbum &album, const std::string &path, std::shared_ptr< CFileItem > &item)
static void FillItemArtistIDs (const std::vector< int > &artistids, std::shared_ptr< CFileItem > &item)
static bool CheckForAdditionalProperties (const CVariant &properties, const std::set< std::string > &checkProperties, std::set< std::string > &foundProperties)
Additional Inherited Members
Static Protected Member Functions inherited from JSONRPC::CFileItemHandler
static void FillDetails (const ISerializable *info, const std::shared_ptr< CFileItem > &item, std::set< std::string > &fields, CVariant &result, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, bool sortLimit=true)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, int size, bool sortLimit=true)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const CVariant &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const std::set< std::string > &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
Static Protected Member Functions inherited from JSONRPC::CJSONUtils
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Member Function Documentation
CheckForAdditionalProperties()
bool CAudioLibrary::CheckForAdditionalProperties (const CVariant & properties, const std::set< std::string > & checkProperties, std::set< std::string > & foundProperties) static private
References CVariant::begin_array(), CVariant::empty(), CVariant::end_array(), and CVariant::isArray().
Referenced by GetAdditionalAlbumDetails(), GetAdditionalArtistDetails(), GetAdditionalSongDetails(), and GetGenres().
Clean()
JSONRPC_STATUS CAudioLibrary::Clean (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CServiceBroker::GetAppMessenger(), and TMSG_EXECUTE_BUILT_IN.
Export()
JSONRPC_STATUS CAudioLibrary::Export (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CServiceBroker::GetAppMessenger(), and TMSG_EXECUTE_BUILT_IN.
FillAlbumItem()
void CAudioLibrary::FillAlbumItem (const CAlbum & album, const std::string & path, std::shared_ptr< CFileItem > & item) static private
References FillItemArtistIDs(), and CAlbum::GetArtistIDArray().
Referenced by GetAlbumDetails(), GetRecentlyAddedAlbums(), and GetRecentlyPlayedAlbums().
FillFileItem()
bool CAudioLibrary::FillFileItem (const std::string & strFilename, std::shared_ptr< CFileItem > & item, const CVariant & parameterObject = CVariant(CVariant::VariantTypeArray)) static
References CFileItemList::Add(), XFILE::CDirectory::Exists(), FillItemArtistIDs(), GetAdditionalAlbumDetails(), GetAdditionalSongDetails(), CMusicDatabase::GetAlbum(), CMusicDatabase::GetAlbumIdByPath(), CAlbum::GetArtistIDArray(), CSong::GetArtistIDArray(), URIUtils::GetFileName(), CMusicDatabase::GetSongByFileName(), CUtil::GetTitleFromPath(), JSONRPC::OK, and CMusicDatabase::Open().
Referenced by JSONRPC::CFileOperations::FillFileItem(), FillFileItemList(), and JSONRPC::CPlayerOperations::GetItem().
FillFileItemList()
bool CAudioLibrary::FillFileItemList (const CVariant & parameterObject, CFileItemList & list) static
References CFileItemList::Add(), CVariant::asString(), FillFileItem(), CServiceBroker::GetSettingsComponent(), CMusicDatabase::GetSong(), CMusicDatabase::GetSongsNav(), CMusicDatabase::Open(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CFileItemList::Sort(), SortAttributeIgnoreArticle, SortAttributeNone, SortByAlbum, SortByArtist, SortByTrackNumber, SortOrderAscending, and success.
Referenced by JSONRPC::CFileItemHandler::FillFileItemList().
FillItemArtistIDs()
void CAudioLibrary::FillItemArtistIDs (const std::vector< int > & artistids, std::shared_ptr< CFileItem > & item) static private
References CVariant::push_back(), and CVariant::VariantTypeArray.
Referenced by FillAlbumItem(), FillFileItem(), and GetSongDetails().
GetAdditionalAlbumDetails()
JSONRPC_STATUS CAudioLibrary::GetAdditionalAlbumDetails (const CVariant & parameterObject, const CFileItemList & items, CMusicDatabase & musicdatabase) static
References CheckForAdditionalProperties(), CMusicDatabase::GetGenresByAlbum(), CMusicDatabase::GetSourcesByAlbum(), JSONRPC::InternalError, JSONRPC::OK, CMusicDatabase::Open(), and CFileItemList::Size().
Referenced by FillFileItem(), GetAdditionalDetails(), GetAlbumDetails(), GetRecentlyAddedAlbums(), and GetRecentlyPlayedAlbums().
GetAdditionalArtistDetails()
JSONRPC_STATUS CAudioLibrary::GetAdditionalArtistDetails (const CVariant & parameterObject, const CFileItemList & items, CMusicDatabase & musicdatabase) static
References CheckForAdditionalProperties(), CMusicDatabase::GetGenresByArtist(), CMusicDatabase::GetIsAlbumArtist(), CMusicDatabase::GetRolesByArtist(), CMusicDatabase::GetSourcesByArtist(), JSONRPC::InternalError, JSONRPC::OK, CMusicDatabase::Open(), and CFileItemList::Size().
Referenced by GetAdditionalDetails(), and GetArtistDetails().
GetAdditionalDetails()
JSONRPC_STATUS CAudioLibrary::GetAdditionalDetails (const CVariant & parameterObject, CFileItemList & items) static
References GetAdditionalAlbumDetails(), GetAdditionalArtistDetails(), GetAdditionalSongDetails(), CFileItemList::GetContent(), CFileItemList::IsEmpty(), CMediaTypes::IsMediaType(), MediaTypeAlbum, MediaTypeArtist, MediaTypeSong, and JSONRPC::OK.
Referenced by JSONRPC::CFileOperations::GetDirectory().
GetAdditionalSongDetails()
JSONRPC_STATUS CAudioLibrary::GetAdditionalSongDetails (const CVariant & parameterObject, const CFileItemList & items, CMusicDatabase & musicdatabase) static
References CheckForAdditionalProperties(), CMusicDatabase::GetArtistsByAlbum(), CMusicDatabase::GetGenresBySong(), CMusicDatabase::GetSourcesBySong(), JSONRPC::InternalError, JSONRPC::OK, CMusicDatabase::Open(), CVariant::push_back(), CFileItemList::Size(), and CVariant::VariantTypeArray.
Referenced by FillFileItem(), GetAdditionalDetails(), JSONRPC::CPlayerOperations::GetItem(), GetRecentlyAddedSongs(), GetRecentlyPlayedSongs(), and GetSongDetails().
GetAlbumDetails()
JSONRPC_STATUS CAudioLibrary::GetAlbumDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFileItemList::Add(), FillAlbumItem(), GetAdditionalAlbumDetails(), CMusicDatabase::GetAlbum(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InternalError, JSONRPC::InvalidParams, JSONRPC::OK, and CMusicDatabase::Open().
GetAlbums()
JSONRPC_STATUS CAudioLibrary::GetAlbums (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CDbUrl::AddOption(), CVariant::asBoolean(), end(), CVariant::end_array(), fields, CThumbLoader::FillLibraryArt(), CDbUrl::FromString(), CMusicDatabase::GetAlbumsByWhereJSON(), CGUIListItem::GetArt(), CFileItem::GetMusicInfoTag(), JSONRPC::CJSONUtils::GetXspFiltering(), JSONRPC::CJSONUtils::HandleLimits(), CGUIListItem::HasArt(), index(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVariant::isArray(), CVariant::isMember(), CVariant::isNull(), CVariant::isObject(), SortDescription::limitEnd, SortDescription::limitStart, MediaTypeAlbum, JSONRPC::OK, CThumbLoader::OnLoaderStart(), CMusicDatabase::Open(), JSONRPC::CJSONUtils::ParseLimits(), JSONRPC::CJSONUtils::ParseSorting(), MUSIC_INFO::CMusicInfoTag::SetDatabaseId(), CVariant::size(), SortDescription::sortAttributes, SortDescription::sortBy, SortDescription::sortOrder, CDbUrl::ToString(), IMAGE_FILES::URLFromFile(), and CVariant::VariantTypeObject.
GetArtistDetails()
JSONRPC_STATUS CAudioLibrary::GetArtistDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CDbUrl::AddOption(), CVariant::append(), CDbUrl::FromString(), GetAdditionalArtistDetails(), CMusicDatabase::GetArtistsByWhere(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVariant::isMember(), JSONRPC::OK, CMusicDatabase::Open(), CFileItemList::Size(), CDbUrl::ToString(), and CVariant::VariantTypeArray.
GetArtists()
JSONRPC_STATUS CAudioLibrary::GetArtists (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CDbUrl::AddOption(), CVariant::asBoolean(), end(), CVariant::end_array(), fields, CDbUrl::FromString(), CMusicDatabase::GetArtistsByWhereJSON(), CServiceBroker::GetSettingsComponent(), JSONRPC::CJSONUtils::GetXspFiltering(), JSONRPC::CJSONUtils::HandleLimits(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVariant::isArray(), CVariant::isMember(), CVariant::isObject(), SortDescription::limitEnd, SortDescription::limitStart, JSONRPC::OK, CMusicDatabase::Open(), JSONRPC::CJSONUtils::ParseLimits(), JSONRPC::CJSONUtils::ParseSorting(), CSettings::SETTING_MUSICLIBRARY_SHOWCOMPILATIONARTISTS, CMusicDatabase::SetTranslateBlankArtist(), SortDescription::sortAttributes, SortDescription::sortBy, SortDescription::sortOrder, and CDbUrl::ToString().
GetAvailableArt()
JSONRPC_STATUS CAudioLibrary::GetAvailableArt (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::append(), CVariant::asInteger32(), CVariant::asString(), CMusicDatabase::GetAvailableArtForItem(), JSONRPC::InternalError, MediaTypeAlbum, MediaTypeArtist, JSONRPC::OK, CMusicDatabase::Open(), IMAGE_FILES::URLFromFile(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
GetAvailableArtTypes()
JSONRPC_STATUS CAudioLibrary::GetAvailableArtTypes (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::append(), CVariant::asInteger32(), CMusicDatabase::GetAvailableArtTypesForItem(), JSONRPC::InternalError, MediaTypeAlbum, MediaTypeArtist, JSONRPC::OK, CMusicDatabase::Open(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
GetGenres()
JSONRPC_STATUS CAudioLibrary::GetGenres (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CheckForAdditionalProperties(), CMusicDatabase::GetGenresJSON(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InternalError, JSONRPC::OK, and CMusicDatabase::Open().
GetProperties()
JSONRPC_STATUS CAudioLibrary::GetProperties (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References BLANKARTIST_ID, CVariant::end_array(), CMusicDatabase::GetAlbumsLastAdded(), CMusicDatabase::GetAlbumsLastModified(), CMusicDatabase::GetArtistLinksUpdated(), CMusicDatabase::GetArtistsLastAdded(), CMusicDatabase::GetArtistsLastModified(), CMusicDatabase::GetGenresLastAdded(), CMusicDatabase::GetLibraryLastCleaned(), CMusicDatabase::GetLibraryLastUpdated(), CMusicDatabase::GetSongsLastAdded(), CMusicDatabase::GetSongsLastModified(), JSONRPC::InternalError, JSONRPC::OK, CMusicDatabase::Open(), and CVariant::VariantTypeObject.
GetRecentlyAddedAlbums()
JSONRPC_STATUS CAudioLibrary::GetRecentlyAddedAlbums (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFileItemList::Add(), FillAlbumItem(), GetAdditionalAlbumDetails(), CMusicDatabase::GetRecentlyAddedAlbums(), JSONRPC::CFileItemHandler::HandleFileItemList(), index(), JSONRPC::InternalError, JSONRPC::OK, and CMusicDatabase::Open().
GetRecentlyAddedSongs()
JSONRPC_STATUS CAudioLibrary::GetRecentlyAddedSongs (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References GetAdditionalSongDetails(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InternalError, JSONRPC::OK, and CMusicDatabase::Open().
GetRecentlyPlayedAlbums()
JSONRPC_STATUS CAudioLibrary::GetRecentlyPlayedAlbums (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFileItemList::Add(), FillAlbumItem(), GetAdditionalAlbumDetails(), CMusicDatabase::GetRecentlyPlayedAlbums(), JSONRPC::CFileItemHandler::HandleFileItemList(), index(), JSONRPC::InternalError, JSONRPC::OK, and CMusicDatabase::Open().
GetRecentlyPlayedSongs()
JSONRPC_STATUS CAudioLibrary::GetRecentlyPlayedSongs (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References GetAdditionalSongDetails(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InternalError, JSONRPC::OK, and CMusicDatabase::Open().
GetRoles()
JSONRPC_STATUS CAudioLibrary::GetRoles (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CMusicDatabase::GetRolesNav(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InternalError, JSONRPC::OK, CMusicDatabase::Open(), and CFileItemList::Size().
GetSongDetails()
JSONRPC_STATUS CAudioLibrary::GetSongDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFileItemList::Add(), FillItemArtistIDs(), GetAdditionalSongDetails(), CSong::GetArtistIDArray(), CMusicDatabase::GetSong(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InternalError, JSONRPC::InvalidParams, JSONRPC::OK, and CMusicDatabase::Open().
GetSongs()
JSONRPC_STATUS CAudioLibrary::GetSongs (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CDbUrl::AddOption(), CVariant::asBoolean(), end(), CVariant::end_array(), fields, CThumbLoader::FillLibraryArt(), CDbUrl::FromString(), CGUIListItem::GetArt(), CFileItem::GetMusicInfoTag(), CMusicDatabase::GetSongsByWhereJSON(), JSONRPC::CJSONUtils::GetXspFiltering(), JSONRPC::CJSONUtils::HandleLimits(), CGUIListItem::HasArt(), index(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVariant::isArray(), CVariant::isMember(), CVariant::isNull(), CVariant::isObject(), SortDescription::limitEnd, SortDescription::limitStart, MediaTypeSong, JSONRPC::OK, CThumbLoader::OnLoaderStart(), CMusicDatabase::Open(), JSONRPC::CJSONUtils::ParseLimits(), JSONRPC::CJSONUtils::ParseSorting(), MUSIC_INFO::CMusicInfoTag::SetAlbumId(), MUSIC_INFO::CMusicInfoTag::SetDatabaseId(), CVariant::size(), SortDescription::sortAttributes, SortDescription::sortBy, SortDescription::sortOrder, CDbUrl::ToString(), IMAGE_FILES::URLFromFile(), and CVariant::VariantTypeObject.
GetSources()
JSONRPC_STATUS JSONRPC::CAudioLibrary::GetSources (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::append(), CMusicDatabase::GetSources(), JSONRPC::InternalError, CVariant::isMember(), JSONRPC::OK, CMusicDatabase::Open(), and CVariant::VariantTypeArray.
RefreshAlbum()
JSONRPC_STATUS CAudioLibrary::RefreshAlbum (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CMusicDatabase::GetAlbum(), CMusicLibraryQueue::GetInstance(), JSONRPC::InternalError, JSONRPC::InvalidParams, CMusicDatabase::Open(), and CMusicLibraryQueue::StartAlbumScan().
RefreshArtist()
JSONRPC_STATUS CAudioLibrary::RefreshArtist (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CDbUrl::AddOption(), CDbUrl::FromString(), CMusicDatabase::GetArtistExists(), CMusicLibraryQueue::GetInstance(), JSONRPC::InternalError, JSONRPC::InvalidParams, CMusicDatabase::Open(), CMusicLibraryQueue::StartArtistScan(), and CDbUrl::ToString().
Scan()
JSONRPC_STATUS CAudioLibrary::Scan (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asString(), CServiceBroker::GetAppMessenger(), and TMSG_EXECUTE_BUILT_IN.
SetAlbumDetails()
JSONRPC_STATUS CAudioLibrary::SetAlbumDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CAlbum::art, CVariant::asBoolean(), CVariant::asFloat(), CVariant::asInteger(), CVariant::asString(), CAlbum::bArtistSongMerge, CAlbum::bBoxedSet, CVariant::begin_map(), JSONRPC::CJSONUtils::CopyStringArray(), CVariant::end_map(), CAlbum::fRating, CAlbum::genre, CMusicDatabase::GetAlbum(), CMusicDatabase::GetArtForItem(), CServiceBroker::GetSettingsComponent(), CAlbum::idAlbum, JSONRPC::InternalError, JSONRPC::InvalidParams, CAlbum::iUserrating, CAlbum::iVotes, MediaTypeAlbum, CAlbum::moods, JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CMusicDatabase::Open(), JSONRPC::CJSONUtils::ParameterNotNull(), CMusicDatabase::RemoveArtForItem(), CAlbum::SetArtistCredits(), CAlbum::strAlbum, CAlbum::strArtistDesc, CAlbum::strArtistSort, CAlbum::strLabel, CAlbum::strMusicBrainzAlbumID, CAlbum::strOrigReleaseDate, CAlbum::strReleaseDate, CAlbum::strReleaseGroupMBID, CAlbum::strReleaseStatus, CAlbum::strReview, CAlbum::strType, CAlbum::styles, CAlbum::themes, IMAGE_FILES::ToCacheKey(), and CMusicDatabase::UpdateAlbum().
SetArtistDetails()
JSONRPC_STATUS CAudioLibrary::SetArtistDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CArtist::art, CVariant::asString(), CVariant::begin_map(), JSONRPC::CJSONUtils::CopyStringArray(), CVariant::end_map(), CArtist::genre, CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtist(), CArtist::idArtist, CArtist::instruments, JSONRPC::InternalError, JSONRPC::InvalidParams, MediaTypeArtist, CArtist::moods, JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CMusicDatabase::Open(), JSONRPC::CJSONUtils::ParameterNotNull(), CMusicDatabase::RemoveArtForItem(), CArtist::strArtist, CArtist::strBiography, CArtist::strBorn, CArtist::strDied, CArtist::strDisambiguation, CArtist::strDisbanded, CArtist::strFormed, CArtist::strGender, CArtist::strMusicBrainzArtistID, CArtist::strSortName, CArtist::strType, CArtist::styles, IMAGE_FILES::ToCacheKey(), CMusicDatabase::UpdateArtist(), and CArtist::yearsActive.
SetSongDetails()
JSONRPC_STATUS CAudioLibrary::SetSongDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asFloat(), CVariant::asInteger(), CVariant::asString(), CVariant::begin_map(), JSONRPC::CJSONUtils::CopyStringArray(), CVariant::end_map(), CVariant::erase(), CSong::genre, CMusicDatabase::GetArtForItem(), CServiceBroker::GetSettingsComponent(), CMusicDatabase::GetSong(), CSong::iBPM, id, CSong::idSong, CSong::iDuration, JSONRPC::InternalError, JSONRPC::InvalidParams, CSong::iTimesPlayed, CSong::iTrack, CSong::lastPlayed, MediaTypeSong, JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CMusicDatabase::Open(), JSONRPC::CJSONUtils::ParameterNotNull(), CSong::rating, CMusicDatabase::RemoveArtForItem(), CMusicDatabase::SetArtForItem(), CSong::SetArtistCredits(), CDateTime::SetFromDBDateTime(), CSong::songVideoURL, CSong::strArtistDesc, CSong::strArtistSort, CSong::strComment, CSong::strDiscSubtitle, CSong::strMood, CSong::strMusicBrainzTrackID, CSong::strOrigReleaseDate, CSong::strReleaseDate, CSong::strTitle, IMAGE_FILES::ToCacheKey(), CMusicDatabase::UpdateSong(), and CSong::userrating.
The documentation for this class was generated from the following files:
AudioLibrary.h
AudioLibrary.cpp