Kodi Documentation: XFILE::CUPnPDirectory Class Reference
XFILE::CUPnPDirectory Class Reference
#include <UPnPDirectory.h>
Public Member Functions
CUPnPDirectory (void)=default
~CUPnPDirectory (void) override=default
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool AllowAll () const override
Whether to allow all files/folders to be listed.
bool Resolve (CFileItem &item) const override
Resolves a given item to a playable item.
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool Create (const CURL &url)
Create the directory.
virtual bool Exists (const CURL &url)
Check for directory existence.
virtual bool Remove (const CURL &url)
Removes the directory.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
Static Public Member Functions
static std::string GetFriendlyName (const CURL &url)
static bool GetResource (const CURL &path, CFileItem &item)
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Additional Inherited Members
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CUPnPDirectory()
XFILE::CUPnPDirectory::CUPnPDirectory (void) default
~CUPnPDirectory()
XFILE::CUPnPDirectory::~CUPnPDirectory (void) override default
Member Function Documentation
AllowAll()
bool XFILE::CUPnPDirectory::AllowAll () const inline override virtual
Whether to allow all files/folders to be listed.
Returns
Returns true if all files/folder should be listed.
Reimplemented from XFILE::IDirectory.
GetDirectory()
bool XFILE::CUPnPDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References CFileItemList::Add(), URIUtils::AddSlashAtEnd(), CFileItemList::AddSortMethod(), UPNP::BuildObject(), CFileItemList::CACHE_NEVER, XFILE::FindDeviceWait(), CURL::Get(), XFILE::GetContentMapping(), UPNP::CUPnP::GetInstance(), CServiceBroker::GetSettingsComponent(), id, UPNP::CUPnP::m_MediaBrowser, XFILE::IDirectory::m_strFileMask, name, CFileItemList::SetCacheToDisc(), CFileItemList::SetContent(), CSettings::SETTING_SERVICES_UPNP, SortAttributeIgnoreFolders, SortByDate, SortByLabel, SortByNone, SortBySize, UPNP::CUPnP::StartClient(), and UPNP::UPnPClient.
GetFriendlyName()
std::string XFILE::CUPnPDirectory::GetFriendlyName (const CURL & url) static
References XFILE::FindDeviceWait(), CURL::Get(), and UPNP::CUPnP::GetInstance().
Referenced by CUtil::GetTitleFromPath().
GetResource()
bool XFILE::CUPnPDirectory::GetResource (const CURL & path, CFileItem & item) static
References XFILE::FindDeviceWait(), CURL::GetFileName(), CURL::GetHostName(), UPNP::CUPnP::GetInstance(), UPNP::GetResource(), CServiceBroker::GetSettingsComponent(), CURL::IsProtocol(), CLog::Log(), LOGERROR, UPNP::CUPnP::m_MediaBrowser, and CSettings::SETTING_SERVICES_UPNP.
Referenced by XFILE::CUPnPFile::Exists(), CApplication::OnMessage(), XFILE::CUPnPFile::Open(), Resolve(), and XFILE::CUPnPFile::Stat().
Resolve()
bool CUPnPDirectory::Resolve (CFileItem & item) const override virtual
Resolves a given item to a playable item.
Note
Some directories (e.g. dvd, bluray, plugins etc) need to be translated/resolved to the actual playback url
Parameters
item The item being manipulated (which the path points to a vfs protocol implementation)
Returns
true if the item was resolved, false if it failed to resolve
Reimplemented from XFILE::IDirectory.
References GetResource(), and CFileItem::GetURL().
The documentation for this class was generated from the following files:
UPnPDirectory.h
UPnPDirectory.cpp