Kodi Documentation: anonymous_namespace{TestConversionMatrix.cpp} Namespace Reference
anonymous_namespace{TestConversionMatrix.cpp} Namespace Reference
Functions
void DebugPrint (const Matrix3 &matrix)
void DebugPrint (const Matrix4 &matrix)
template<uint8_t Order>
bool CompareMatrices (CMatrix< Order > &matrixA, CMatrix< Order > &matrixB, float threshold)
Variables
constexpr bool DEBUG_PRINT {false}
std::array< std::array< float, 4 >, 4 > bt709_8bit
Matrix4 bt709Mat_8bit (bt709_8bit)
std::array< std::array< float, 4 >, 4 > bt709_10bit
Matrix4 bt709Mat_10bit (bt709_10bit)
std::array< std::array< float, 4 >, 4 > bt709_10bit_texture
Matrix4 bt709Mat_10bit_texture (bt709_10bit_texture)
std::array< std::array< float, 3 >, 3 > bt601_to_bt709
Matrix3 bt601_to_bt709_Mat (bt601_to_bt709)
std::array< std::array< float, 3 >, 3 > bt2020_to_bt709
Matrix3 bt2020_to_bt709_Mat (bt2020_to_bt709)
Function Documentation
CompareMatrices()
template<uint8_t Order> bool anonymous_namespace{TestConversionMatrix.cpp}::CompareMatrices (CMatrix< Order > & matrixA, CMatrix< Order > & matrixB, float threshold)
References MathUtils::FloatEquals().
Referenced by TEST(), and TEST().
DebugPrint() [1/2]
void anonymous_namespace{TestConversionMatrix.cpp}::DebugPrint (const Matrix3 & matrix)
References DEBUG_PRINT.
Referenced by TEST(), and TEST().
DebugPrint() [2/2]
void anonymous_namespace{TestConversionMatrix.cpp}::DebugPrint (const Matrix4 & matrix)
References DEBUG_PRINT.
Variable Documentation
bt2020_to_bt709
std::array<std::array<float, 3>, 3> anonymous_namespace{TestConversionMatrix.cpp}::bt2020_to_bt709
Initial value:
=
{{
  {1.6604905128, -0.1245504916, -0.0181507617},
  {-0.5876411796, 1.1328998804, -0.1005788445},
  {-0.0728498399, -0.0083493963, 1.1187294722},
}}
bt2020_to_bt709_Mat
Matrix3 anonymous_namespace{TestConversionMatrix.cpp}::bt2020_to_bt709_Mat(bt2020_to_bt709) (bt2020_to_bt709)
Referenced by TEST().
bt601_to_bt709
std::array<std::array<float, 3>, 3> anonymous_namespace{TestConversionMatrix.cpp}::bt601_to_bt709
Initial value:
=
{{
  {1.0440435410, -0.0000000230, 0.0000000056},
  {-0.0440433398, 0.9999997616, 0.0117934495},
  {-0.0000000298, -0.0000000075, 0.9882065654},
}}
bt601_to_bt709_Mat
Matrix3 anonymous_namespace{TestConversionMatrix.cpp}::bt601_to_bt709_Mat(bt601_to_bt709) (bt601_to_bt709)
Referenced by TEST().
bt709_10bit
std::array<std::array<float, 4>, 4> anonymous_namespace{TestConversionMatrix.cpp}::bt709_10bit
Initial value:
=
{{
  {1.1678080559, 1.1678080559, 1.1678080559, 0.0000000000},
  {0.0000000000, -0.2138758004, 2.1186144352, 0.0000000000},
  {1.7980136871, -0.5344766378, 0.0000000000, 0.0000000000},
  {-0.9729449749, 0.3014826477, -1.1334021091, 1.0000000000},
}}
bt709_10bit_texture
std::array<std::array<float, 4>, 4> anonymous_namespace{TestConversionMatrix.cpp}::bt709_10bit_texture
Initial value:
=
{{
  {74.8116378784, 74.8116378784, 74.8116378784, 0.0000000000},
  {0.0000000000, -13.7012224197, 135.7218017578, 0.0000000000},
  {115.1836090088, -34.2394218445, 0.0000000000, 0.0000000000},
  {-0.9729449749, 0.3014826477, -1.1334021091, 1.0000000000},
}}
bt709_8bit
std::array<std::array<float, 4>, 4> anonymous_namespace{TestConversionMatrix.cpp}::bt709_8bit
Initial value:
=
{{
  {1.1643834114, 1.1643834114, 1.1643834114, 0.0000000000},
  {0.0000000000, -0.2132485956, 2.1124014854, 0.0000000000},
  {1.7927408218, -0.5329092145, 0.0000000000, 0.0000000000},
  {-0.9729449749, 0.3014826477, -1.1334021091, 1.0000000000}
}}
bt709Mat_10bit
Matrix4 anonymous_namespace{TestConversionMatrix.cpp}::bt709Mat_10bit(bt709_10bit) (bt709_10bit)
Referenced by TEST().
bt709Mat_10bit_texture
Matrix4 anonymous_namespace{TestConversionMatrix.cpp}::bt709Mat_10bit_texture(bt709_10bit_texture) (bt709_10bit_texture)
Referenced by TEST().
bt709Mat_8bit
Matrix4 anonymous_namespace{TestConversionMatrix.cpp}::bt709Mat_8bit(bt709_8bit) (bt709_8bit)
Referenced by TEST().
DEBUG_PRINT
constexpr bool anonymous_namespace{TestConversionMatrix.cpp}::DEBUG_PRINT {false} constexpr
Referenced by DebugPrint(), and DebugPrint().