Kodi Documentation: KODI::RETRO::CGUIGameSettingsHandle Class Reference
KODI::RETRO::CGUIGameSettingsHandle Class Reference
#include <GUIGameSettingsHandle.h>
Public Member Functions
CGUIGameSettingsHandle (CGUIGameRenderManager &renderManager)
virtual ~CGUIGameSettingsHandle ()
std::string GameClientID ()
Get the ID of the active game client.
std::string GetPlayingGame ()
Get the full path of the game being played.
std::string CreateSavestate (bool autosave)
Create a savestate of the current game being played.
bool UpdateSavestate (const std::string &savestatePath)
Update a savestate for the current game being played.
bool LoadSavestate (const std::string &savestatePath)
Load a savestate for the current game being played.
void FreeSavestateResources (const std::string &savestatePath)
Clear the video frame stored for the given statestate.
void CloseOSD ()
Close the in-game OSD.
Private Attributes
CGUIGameRenderManager & m_renderManager
Constructor & Destructor Documentation
CGUIGameSettingsHandle()
CGUIGameSettingsHandle::CGUIGameSettingsHandle (CGUIGameRenderManager & renderManager)
~CGUIGameSettingsHandle()
CGUIGameSettingsHandle::~CGUIGameSettingsHandle () virtual
References m_renderManager, and KODI::RETRO::CGUIGameRenderManager::UnregisterHandle().
Member Function Documentation
CloseOSD()
void CGUIGameSettingsHandle::CloseOSD ()
Close the in-game OSD.
References KODI::RETRO::CGUIGameRenderManager::CloseOSD(), and m_renderManager.
CreateSavestate()
std::string CGUIGameSettingsHandle::CreateSavestate (bool autosave)
Create a savestate of the current game being played.
Parameters
autosave True if the save was invoked automatically, or false if the save was invoked by a player
Returns
The path to the created savestate file, or empty string on failure or if a game is not playing
References KODI::RETRO::CGUIGameRenderManager::CreateSavestate(), and m_renderManager.
FreeSavestateResources()
void CGUIGameSettingsHandle::FreeSavestateResources (const std::string & savestatePath)
Clear the video frame stored for the given statestate.
Useful to reclaim memory if a savestate has been deleted.
Parameters
savestatePath The path to the savestate file
References KODI::RETRO::CGUIGameRenderManager::FreeSavestateResources(), and m_renderManager.
GameClientID()
std::string CGUIGameSettingsHandle::GameClientID ()
Get the ID of the active game client.
Returns
The ID of the active game client, or empty string if a game is not playing
References KODI::RETRO::CGUIGameRenderManager::GameClientID(), and m_renderManager.
GetPlayingGame()
std::string CGUIGameSettingsHandle::GetPlayingGame ()
Get the full path of the game being played.
Returns
The game's path, or empty string if a game is not playing
References KODI::RETRO::CGUIGameRenderManager::GetPlayingGame(), and m_renderManager.
LoadSavestate()
bool CGUIGameSettingsHandle::LoadSavestate (const std::string & savestatePath)
Load a savestate for the current game being played.
Parameters
savestatePath The path to the created savestate file returned by CreateSavestate()
Returns
True if the savestate was loaded successfully, false otherwise
References KODI::RETRO::CGUIGameRenderManager::LoadSavestate(), and m_renderManager.
UpdateSavestate()
bool CGUIGameSettingsHandle::UpdateSavestate (const std::string & savestatePath)
Update a savestate for the current game being played.
Parameters
savestatePath The path to the created savestate file returned by CreateSavestate()
Returns
True if the savestate was updated successfully, false otherwise
References m_renderManager, and KODI::RETRO::CGUIGameRenderManager::UpdateSavestate().
Member Data Documentation
m_renderManager
CGUIGameRenderManager& KODI::RETRO::CGUIGameSettingsHandle::m_renderManager private
Referenced by CloseOSD(), CreateSavestate(), FreeSavestateResources(), GameClientID(), GetPlayingGame(), LoadSavestate(), UpdateSavestate(), and ~CGUIGameSettingsHandle().
The documentation for this class was generated from the following files:
GUIGameSettingsHandle.h
GUIGameSettingsHandle.cpp