Kodi Documentation: ADDON::Interface_GUIControlProgress Struct Reference
ADDON::Interface_GUIControlProgress Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Progress.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
callback functions from add-on to kodi
static void set_percentage (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float percent)
static float get_percentage (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold general gui functions and initialize also all other gui related types not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/controls/Progress.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIControlProgress::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_progress, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
get_percentage()
float ADDON::Interface_GUIControlProgress::get_percentage (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUIProgressControl::GetPercentage(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIControlProgress::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_progress, get_percentage(), AddonToKodiFuncTable_kodi_gui_control_progress::get_percentage, AddonToKodiFuncTable_Addon::kodi_gui, set_percentage(), AddonToKodiFuncTable_kodi_gui_control_progress::set_percentage, set_visible(), AddonToKodiFuncTable_kodi_gui_control_progress::set_visible, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
set_percentage()
void ADDON::Interface_GUIControlProgress::set_percentage (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float percent) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIProgressControl::SetPercentage().
Referenced by Init().
set_visible()
void ADDON::Interface_GUIControlProgress::set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetVisible().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/controls/progress.h
controls/Progress.cpp