Kodi Documentation: GUIControlSettings.cpp File Reference
GUIControlSettings.cpp File Reference
#include "GUIControlSettings.h"
#include "FileItem.h"
#include "FileItemList.h"
#include "ServiceBroker.h"
#include "Util.h"
#include "addons/AddonManager.h"
#include "addons/gui/GUIWindowAddonBrowser.h"
#include "addons/settings/SettingUrlEncodedString.h"
#include "dialogs/GUIDialogColorPicker.h"
#include "dialogs/GUIDialogFileBrowser.h"
#include "dialogs/GUIDialogNumeric.h"
#include "dialogs/GUIDialogSelect.h"
#include "dialogs/GUIDialogSlider.h"
#include "guilib/GUIColorButtonControl.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIEditControl.h"
#include "guilib/GUIImage.h"
#include "guilib/GUIKeyboardFactory.h"
#include "guilib/GUILabelControl.h"
#include "guilib/GUIRadioButtonControl.h"
#include "guilib/GUISettingsSliderControl.h"
#include "guilib/GUISpinControlEx.h"
#include "guilib/GUIWindowManager.h"
#include "guilib/LocalizeStrings.h"
#include "settings/MediaSourceSettings.h"
#include "settings/SettingAddon.h"
#include "settings/SettingControl.h"
#include "settings/SettingDateTime.h"
#include "settings/SettingPath.h"
#include "settings/SettingUtils.h"
#include "settings/lib/Setting.h"
#include "settings/lib/SettingDefinitions.h"
#include "storage/MediaManager.h"
#include "utils/FileExtensionProvider.h"
#include "utils/StringUtils.h"
#include "utils/Variant.h"
#include "utils/log.h"
#include <set>
#include <utility>
Functions
static std::string Localize (std::uint32_t code, ILocalizer *localizer, const std::string &addonId="")
template<typename TValueType >
static CFileItemPtr GetFileItem (const std::string &label, const std::string &label2, const TValueType &value, const std::vector< std::pair< std::string, CVariant > > &properties, const std::set< TValueType > &selectedValues)
template<class SettingOption >
static bool CompareSettingOptionAseconding (const SettingOption &lhs, const SettingOption &rhs)
template<class SettingOption >
static bool CompareSettingOptionDeseconding (const SettingOption &lhs, const SettingOption &rhs)
static bool GetIntegerOptions (const SettingConstPtr &setting, IntegerSettingOptions &options, std::set< int > &selectedOptions, ILocalizer *localizer, bool updateOptions)
static bool GetStringOptions (const SettingConstPtr &setting, StringSettingOptions &options, std::set< std::string > &selectedOptions, ILocalizer *localizer, bool updateOptions)
Function Documentation
CompareSettingOptionAseconding()
template<class SettingOption > static bool CompareSettingOptionAseconding (const SettingOption & lhs, const SettingOption & rhs) static
References KODI::UTILS::StringUtils::CompareNoCase().
CompareSettingOptionDeseconding()
template<class SettingOption > static bool CompareSettingOptionDeseconding (const SettingOption & lhs, const SettingOption & rhs) static
References KODI::UTILS::StringUtils::CompareNoCase().
GetFileItem()
template<typename TValueType > static CFileItemPtr GetFileItem (const std::string & label, const std::string & label2, const TValueType & value, const std::vector< std::pair< std::string, CVariant > > & properties, const std::set< TValueType > & selectedValues) static
References label, and value.
Referenced by CGUIControlListSetting::GetIntegerItems(), and CGUIControlListSetting::GetStringItems().
GetIntegerOptions()
static bool GetIntegerOptions (const SettingConstPtr & setting, IntegerSettingOptions & options, std::set< int > & selectedOptions, ILocalizer * localizer, bool updateOptions) static
References Ascending, Descending, Dynamic, KODI::UTILS::StringUtils::Format(), CSettingUtils::GetList(), Integer, List, Localize(), NoSorting, Static, StaticTranslatable, and Unknown.
Referenced by CGUIControlSpinExSetting::FillIntegerSettingControl(), and CGUIControlListSetting::GetIntegerItems().
GetStringOptions()
static bool GetStringOptions (const SettingConstPtr & setting, StringSettingOptions & options, std::set< std::string > & selectedOptions, ILocalizer * localizer, bool updateOptions) static
References Ascending, Descending, Dynamic, CSettingUtils::GetList(), List, Localize(), NoSorting, Static, StaticTranslatable, String, and Unknown.
Referenced by CGUIControlSpinExSetting::FillStringSettingControl(), and CGUIControlListSetting::GetStringItems().
Localize()
static std::string Localize (std::uint32_t code, ILocalizer * localizer, const std::string & addonId = "") static
References g_localizeStrings, CLocalizeStrings::GetAddonString(), label, and ILocalizer::Localize().
Referenced by GetIntegerOptions(), and GetStringOptions().