Kodi Documentation: KODI::KEYBOARD::IKeyboardInputProvider Class Reference
KODI::KEYBOARD::IKeyboardInputProvider Class Reference abstract
Input » Keyboard
Interface for classes that can provide keyboard input.
#include <IKeyboardInputProvider.h>
Public Member Functions
virtual ~IKeyboardInputProvider ()=default
virtual void RegisterKeyboardHandler (IKeyboardInputHandler *handler, bool bPromiscuous, bool forceDefaultMap)=0
Registers a handler to be called on keyboard input.
virtual void UnregisterKeyboardHandler (IKeyboardInputHandler *handler)=0
Unregisters handler from keyboard input.
Detailed Description
Interface for classes that can provide keyboard input.
Constructor & Destructor Documentation
~IKeyboardInputProvider()
virtual KODI::KEYBOARD::IKeyboardInputProvider::~IKeyboardInputProvider () virtual default
Member Function Documentation
RegisterKeyboardHandler()
virtual void KODI::KEYBOARD::IKeyboardInputProvider::RegisterKeyboardHandler (IKeyboardInputHandler * handler, bool bPromiscuous, bool forceDefaultMap) pure virtual
Registers a handler to be called on keyboard input.
Parameters
handler The handler to receive keyboard input provided by this class
bPromiscuous True to observe all events without affecting the input's destination
forceDefaultMap Always use the default keyboard buttonmap, avoiding buttonmaps provided by add-ons
Implemented in PERIPHERALS::CPeripheral.
Referenced by KODI::GAME::CGameClientKeyboard::CGameClientKeyboard(), and KODI::GAME::CAgentKeyboard::Initialize().
UnregisterKeyboardHandler()
virtual void KODI::KEYBOARD::IKeyboardInputProvider::UnregisterKeyboardHandler (IKeyboardInputHandler * handler) pure virtual
Unregisters handler from keyboard input.
Parameters
handler The handler that was receiving keyboard input
Implemented in PERIPHERALS::CPeripheral.
Referenced by KODI::GAME::CAgentKeyboard::Deinitialize(), and KODI::GAME::CGameClientKeyboard::~CGameClientKeyboard().
The documentation for this class was generated from the following file:
IKeyboardInputProvider.h