Kodi Documentation: anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor Class Reference
anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor Class Reference
Public Member Functions
CVideoSelectActionProcessor (const std::shared_ptr< CFileItem > &item)
Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase
CVideoSelectActionProcessorBase (const std::shared_ptr< CFileItem > &item)
~CVideoSelectActionProcessorBase () override=default
Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
CVideoPlayActionProcessorBase (const std::shared_ptr< CFileItem > &item)
virtual ~CVideoPlayActionProcessorBase ()=default
bool ProcessDefaultAction ()
bool ProcessAction (Action action)
bool UserCancelled () const
Protected Member Functions
bool OnPlayPartSelected (unsigned int part) override
bool OnResumeSelected () override
bool OnPlaySelected () override
bool OnQueueSelected () override
bool OnInfoSelected () override
bool OnChooseSelected () override
Protected Member Functions inherited from KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase
Action GetDefaultAction () override
bool Process (Action action) override
Additional Inherited Members
Static Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase
static Action GetDefaultSelectAction ()
Static Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
static Action ChoosePlayOrResume (const CFileItem &item)
Protected Attributes inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
std::shared_ptr< CFileItem > m_item
bool m_userCancelled {false}
Constructor & Destructor Documentation
CVideoSelectActionProcessor()
anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::CVideoSelectActionProcessor (const std::shared_ptr< CFileItem > & item) inline explicit
Member Function Documentation
OnChooseSelected()
bool anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnChooseSelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase.
References CContextMenuManager::MAIN, and CONTEXTMENU::ShowFor().
OnInfoSelected()
bool anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnInfoSelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase.
References KODI::UTILS::GUILIB::CGUIContentUtils::ShowInfoForItem().
OnPlayPartSelected()
bool anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnPlayPartSelected (unsigned int part) inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase.
References FAVOURITES_UTILS::ExecuteAction().
OnPlaySelected()
bool anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnPlaySelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase.
References FAVOURITES_UTILS::ExecuteAction().
OnQueueSelected()
bool anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnQueueSelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase.
References FAVOURITES_UTILS::ExecuteAction().
OnResumeSelected()
bool anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnResumeSelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase.
References FAVOURITES_UTILS::ExecuteAction().
The documentation for this class was generated from the following file:
GUIWindowFavourites.cpp