Kodi Documentation: CRegExp Class Reference
CRegExp Class Reference
#include <RegExp.h>
Public Types
enum studyMode { NoStudy = 0 , StudyRegExp = 1 , StudyWithJitComp }
enum utf8Mode { autoUtf8 = -1 , asciiOnly = 0 , forceUtf8 = 1 }
Public Member Functions
CRegExp (bool caseless=false, utf8Mode utf8=asciiOnly)
CRegExp (bool caseless, utf8Mode utf8, const char *re, studyMode study=NoStudy)
CRegExp (const CRegExp &re)
~CRegExp ()
bool RegComp (const char *re, studyMode study=NoStudy)
bool RegComp (const std::string &re, studyMode study=NoStudy)
int RegFind (const char *str, unsigned int startoffset=0, int maxNumberOfCharsToTest=-1)
int RegFind (const std::string &str, unsigned int startoffset=0, int maxNumberOfCharsToTest=-1)
std::string GetReplaceString (const std::string &sReplaceExp) const
int GetFindLen () const
int GetSubCount () const
int GetSubStart (int iSub) const
int GetSubLength (int iSub) const
int GetCaptureTotal () const
std::string GetMatch (int iSub=0) const
const std::string & GetPattern () const
void DumpOvector (int iLog)
bool IsCompiled (void) const
CRegExp & operator= (const CRegExp &re)
Static Public Member Functions
static bool IsUtf8Supported (void)
static bool AreUnicodePropertiesSupported (void)
static bool LogCheckUtf8Support (void)
static bool IsJitSupported (void)
Static Public Attributes
static const int m_MaxNumOfBackrefrences = 20
Private Member Functions
int PrivateRegFind (size_t bufferLen, const char *str, unsigned int startoffset=0, int maxNumberOfCharsToTest=-1)
void InitValues (bool caseless=false, CRegExp::utf8Mode utf8=asciiOnly)
void Cleanup ()
bool IsValidSubNumber (int iSub) const
Static Private Member Functions
static bool requireUtf8 (const std::string &regexp)
static int readCharXCode (const std::string &regexp, size_t &pos)
static bool isCharClassWithUnicode (const std::string &regexp, size_t &pos)
Private Attributes
pcre2_code * m_re
pcre2_match_context * m_ctxt
unsigned int m_offset
pcre2_match_data * m_matchData
PCRE2_SIZE * m_iOvector
utf8Mode m_utf8Mode
int m_iMatchCount
uint32_t m_iOptions
bool m_jitCompiled
bool m_bMatched
pcre2_jit_stack * m_jitStack
std::string m_subject
std::string m_pattern
Static Private Attributes
static const int OVECCOUNT =(m_MaxNumOfBackrefrences + 1) * 3
static int m_Utf8Supported = -1
static int m_UcpSupported = -1
static int m_JitSupported = -1
Member Enumeration Documentation
studyMode
enum CRegExp::studyMode
Enumerator
NoStudy
StudyRegExp
StudyWithJitComp
utf8Mode
enum CRegExp::utf8Mode
Enumerator
autoUtf8
asciiOnly
forceUtf8
Constructor & Destructor Documentation
CRegExp() [1/3]
CRegExp::CRegExp (bool caseless = false, CRegExp::utf8Mode utf8 = asciiOnly)
Parameters
caseless (optional) Matching will be case insensitive if set to true or case sensitive if set to false
utf8 (optional) Control UTF-8 processing
References InitValues().
CRegExp() [2/3]
CRegExp::CRegExp (bool caseless, CRegExp::utf8Mode utf8, const char * re, studyMode study = NoStudy)
Create new CRegExp object and compile regexp expression in one step
Warning
Use only with hardcoded regexp when you're sure that regexp is compiled without errors
Parameters
caseless Matching will be case insensitive if set to true or case sensitive if set to false
utf8 Control UTF-8 processing
re The regular expression
study (optional) Controls study of expression, useful if expression will be used several times
References asciiOnly, autoUtf8, forceUtf8, InitValues(), RegComp(), and requireUtf8().
CRegExp() [3/3]
CRegExp::CRegExp (const CRegExp & re)
References m_ctxt, m_iOptions, m_iOvector, m_jitStack, m_matchData, m_re, and m_utf8Mode.
~CRegExp()
CRegExp::~CRegExp ()
References Cleanup().
Member Function Documentation
AreUnicodePropertiesSupported()
bool CRegExp::AreUnicodePropertiesSupported (void) static
References m_UcpSupported.
Referenced by InitValues(), LogCheckUtf8Support(), and RegComp().
Cleanup()
void CRegExp::Cleanup () private
References m_ctxt, m_jitStack, m_matchData, and m_re.
Referenced by operator=(), RegComp(), and ~CRegExp().
DumpOvector()
void CRegExp::DumpOvector (int iLog)
References GetSubCount(), CLog::Log(), LOGNONE, m_iOvector, and t.
Referenced by TEST_F().
GetCaptureTotal()
int CRegExp::GetCaptureTotal () const
References m_re.
Referenced by XFILE::CStackDirectory::GetStackedTitlePath(), CFileItemList::StackFiles(), and TEST().
GetFindLen()
int CRegExp::GetFindLen () const inline
References m_bMatched, m_iOvector, and m_re.
Referenced by CLabelFormatter::AssembleMask(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), CWebVTTHandler::GetCueData(), CScraperParser::ParseExpression(), CExternalPlayer::Process(), CLabelFormatter::SplitMask(), and TEST().
GetMatch()
std::string CRegExp::GetMatch (int iSub = 0) const
References IsValidSubNumber(), m_iOvector, and m_subject.
Referenced by CLabelFormatter::AssembleMask(), CUtil::CleanString(), CScraperParser::ConvertJSON(), CDVDSubtitleTagSami::ConvertLine(), CWebVTTHandler::ConvertSubtitle(), CWebVTTHandler::DecodeLine(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), XFILE::CDAVFile::Execute(), XFILE::CShoutcastFile::ExtractTagInfo(), CLangCodeExpander::FindLanguageCodeWithSubtag(), KODI::VIDEO::CVideoInfoScanner::GetAirDateFromRegExp(), XFILE::CHTTPDirectory::GetDirectory(), KODI::VIDEO::CVideoInfoScanner::GetEpisodeAndSeasonFromRegExp(), KODI::VIDEO::CVideoInfoScanner::GetEpisodeTitleFromRegExp(), CUtil::GetFilenameIdentifier(), GetReplaceString(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), CWebVTTHandler::GetTimeFromRegexTS(), PVR::CPVRRecordingsPath::GetTitle(), XFILE::CBlurayDirectory::GetUserPlaylists(), CDVDSubtitleTagSami::LoadHead(), CDVDSubtitleParserMicroDVD::Open(), CDVDSubtitleParserMPL2::Open(), CDVDSubtitleParserSami::Open(), CDVDSubtitleParserVplayer::Open(), CScraperParser::ParseExpression(), CLabelFormatter::SplitMask(), CTagLoaderTagLib::SplitMBID(), and TEST().
GetPattern()
const std::string & CRegExp::GetPattern () const inline
References m_pattern.
Referenced by TEST().
GetReplaceString()
std::string CRegExp::GetReplaceString (const std::string & sReplaceExp) const
References GetMatch(), and m_bMatched.
Referenced by CPosixMountProvider::GetDrives(), CAndroidStorageProvider::GetRemovableDrivesLinux(), CScraperParser::ParseExpression(), CExternalPlayer::Process(), and TEST().
GetSubCount()
int CRegExp::GetSubCount () const inline
References m_iMatchCount.
Referenced by CWebVTTHandler::DecodeLine(), DumpOvector(), XFILE::CDAVFile::Execute(), CWebVTTHandler::GetCueData(), and TEST().
GetSubLength()
int CRegExp::GetSubLength (int iSub) const
References IsValidSubNumber(), and m_iOvector.
Referenced by CScraperParser::ConvertJSON(), XFILE::CHTTPDirectory::GetDirectory(), and CGUIDialogKeyboardGeneric::OnIPAddress().
GetSubStart()
int CRegExp::GetSubStart (int iSub) const
References IsValidSubNumber(), m_iOvector, and m_offset.
Referenced by CScraperParser::ConvertJSON(), and TEST().
InitValues()
void CRegExp::InitValues (bool caseless = false, CRegExp::utf8Mode utf8 = asciiOnly) private
References AreUnicodePropertiesSupported(), forceUtf8, IsUtf8Supported(), m_bMatched, m_ctxt, m_iMatchCount, m_iOptions, m_iOvector, m_jitCompiled, m_jitStack, m_matchData, m_offset, m_re, and m_utf8Mode.
Referenced by CRegExp(), and CRegExp().
isCharClassWithUnicode()
bool CRegExp::isCharClassWithUnicode (const std::string & regexp, size_t & pos) static private
References readCharXCode().
Referenced by requireUtf8().
IsCompiled()
bool CRegExp::IsCompiled (void) const inline
Check is RegExp object is ready for matching
Returns
true if RegExp object is ready for matching, false otherwise
References m_pattern.
Referenced by CFileItemList::StackFolders().
IsJitSupported()
bool CRegExp::IsJitSupported (void) static
References m_JitSupported.
Referenced by RegComp().
IsUtf8Supported()
bool CRegExp::IsUtf8Supported (void) static
References m_Utf8Supported.
Referenced by InitValues(), LogCheckUtf8Support(), and RegComp().
IsValidSubNumber()
bool CRegExp::IsValidSubNumber (int iSub) const inline private
References m_iMatchCount, and m_MaxNumOfBackrefrences.
Referenced by GetMatch(), GetSubLength(), and GetSubStart().
LogCheckUtf8Support()
bool CRegExp::LogCheckUtf8Support (void) static
References AreUnicodePropertiesSupported(), IsUtf8Supported(), CLog::Log(), LOGINFO, and LOGWARNING.
Referenced by CApplication::PrintStartupLog().
operator=()
CRegExp & CRegExp::operator= (const CRegExp & re)
References Cleanup(), CLog::Log(), LOGFATAL, m_bMatched, m_ctxt, m_iMatchCount, m_iOptions, m_iOvector, m_jitCompiled, m_offset, m_pattern, m_re, and m_subject.
PrivateRegFind()
int CRegExp::PrivateRegFind (size_t bufferLen, const char * str, unsigned int startoffset = 0, int maxNumberOfCharsToTest = -1) private
References CLog::Log(), LOGERROR, LOGWARNING, m_bMatched, m_ctxt, m_iMatchCount, m_iOvector, m_jitCompiled, m_jitStack, m_matchData, m_offset, m_re, m_subject, OVECCOUNT, and CUtf8Utils::RFindValidUtf8Char().
Referenced by RegFind(), and RegFind().
readCharXCode()
int CRegExp::readCharXCode (const std::string & regexp, size_t & pos) inline static private
Referenced by isCharClassWithUnicode(), and requireUtf8().
RegComp() [1/2]
bool CRegExp::RegComp (const char * re, studyMode study = NoStudy)
Compile (prepare) regular expression
Parameters
re The regular expression
study (optional) Controls study of expression, useful if expression will be used several times
Returns
true on success, false on any error
References AreUnicodePropertiesSupported(), autoUtf8, Cleanup(), IsJitSupported(), IsUtf8Supported(), CLog::Log(), LOGERROR, m_bMatched, m_iMatchCount, m_iOptions, m_jitCompiled, m_offset, m_pattern, m_re, m_utf8Mode, requireUtf8(), and StudyWithJitComp.
Referenced by CLabelFormatter::AssembleMask(), CUtil::CleanString(), CPlayerSelectionRule::CompileRegExp(), CScraperParser::ConvertJSON(), CRegExp(), CWebVTTHandler::DecodeLine(), CStereoscopicsManager::DetectStereoModeByString(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), CUtil::ExcludeFileOrFolder(), XFILE::CDAVFile::Execute(), XFILE::CShoutcastFile::ExtractTagInfo(), CLangCodeExpander::FindLanguageCodeWithSubtag(), KODI::VIDEO::UTILS::FindTrailer(), XFILE::CHTTPDirectory::GetDirectory(), CPosixMountProvider::GetDrives(), CUtil::GetFilenameIdentifier(), CAndroidStorageProvider::GetRemovableDrivesLinux(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), XFILE::CStackDirectory::GetStackedTitlePath(), PVR::CPVRRecordingsPath::GetTitle(), XFILE::CBlurayDirectory::GetUserPlaylists(), CZipManager::GetZipList(), CDVDSubtitleTagSami::Init(), CWebVTTHandler::Initialize(), CDVDSubtitleTagSami::LoadHead(), CGUIDialogKeyboardGeneric::OnIPAddress(), CDVDSubtitleParserMicroDVD::Open(), CDVDSubtitleParserMPL2::Open(), CDVDSubtitleParserSami::Open(), CDVDSubtitleParserVplayer::Open(), CScraperParser::ParseExpression(), CExternalPlayer::Process(), RegComp(), CLabelFormatter::SplitMask(), CTagLoaderTagLib::SplitMBID(), CFileItemList::StackFiles(), CFileItemList::StackFolders(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and KODI::UTILS::StringUtils::ValidateUUID().
RegComp() [2/2]
bool CRegExp::RegComp (const std::string & re, studyMode study = NoStudy) inline
Compile (prepare) regular expression
Parameters
re The regular expression
study (optional) Controls study of expression, useful if expression will be used several times
Returns
true on success, false on any error
References RegComp().
RegFind() [1/2]
int CRegExp::RegFind (const char * str, unsigned int startoffset = 0, int maxNumberOfCharsToTest = -1)
Find first match of regular expression in given string
Parameters
str The string to match against regular expression
startoffset (optional) The string offset to start matching
maxNumberOfCharsToTest (optional) The maximum number of characters to test (match) in string. If set to -1 string checked up to the end.
Returns
staring position of match in string, negative value in case of error or no match
References PrivateRegFind().
Referenced by CLabelFormatter::AssembleMask(), CUtil::CleanString(), CScraperParser::ConvertJSON(), CDVDSubtitleTagSami::ConvertLine(), CWebVTTHandler::ConvertSubtitle(), CWebVTTHandler::DecodeLine(), CStereoscopicsManager::DetectStereoModeByString(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), CUtil::ExcludeFileOrFolder(), XFILE::CDAVFile::Execute(), XFILE::CShoutcastFile::ExtractTagInfo(), CLangCodeExpander::FindLanguageCodeWithSubtag(), XFILE::CHTTPDirectory::GetDirectory(), CPosixMountProvider::GetDrives(), CUtil::GetFilenameIdentifier(), CAndroidStorageProvider::GetRemovableDrivesLinux(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), PVR::CPVRRecordingsPath::GetTitle(), XFILE::CBlurayDirectory::GetUserPlaylists(), CZipManager::GetZipList(), CWebVTTHandler::InsertCssStyleStartTag(), CXBMCTinyXML::InternalParse(), CWebVTTHandler::IsCueLine(), CDVDSubtitleTagSami::LoadHead(), CPlayerSelectionRule::MatchesRegExp(), CGUIDialogKeyboardGeneric::OnIPAddress(), CDVDSubtitleParserMicroDVD::Open(), CDVDSubtitleParserMPL2::Open(), CDVDSubtitleParserSami::Open(), CDVDSubtitleParserVplayer::Open(), CScraperParser::ParseExpression(), CXBMCTinyXML2::ParseHelper(), CExternalPlayer::Process(), CLabelFormatter::SplitMask(), CTagLoaderTagLib::SplitMBID(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and KODI::UTILS::StringUtils::ValidateUUID().
RegFind() [2/2]
int CRegExp::RegFind (const std::string & str, unsigned int startoffset = 0, int maxNumberOfCharsToTest = -1) inline
Find first match of regular expression in given string
Parameters
str The string to match against regular expression
startoffset (optional) The string offset to start matching
maxNumberOfCharsToTest (optional) The maximum number of characters to test (match) in string. If set to -1 string checked up to the end.
Returns
staring position of match in string, negative value in case of error or no match
References PrivateRegFind().
requireUtf8()
bool CRegExp::requireUtf8 (const std::string & regexp) static private
References CUtf8Utils::checkStrForUtf8(), isCharClassWithUnicode(), readCharXCode(), and CUtf8Utils::utf8string.
Referenced by CRegExp(), and RegComp().
Member Data Documentation
m_bMatched
bool CRegExp::m_bMatched private
Referenced by GetFindLen(), GetReplaceString(), InitValues(), operator=(), PrivateRegFind(), and RegComp().
m_ctxt
pcre2_match_context* CRegExp::m_ctxt private
Referenced by Cleanup(), CRegExp(), InitValues(), operator=(), and PrivateRegFind().
m_iMatchCount
int CRegExp::m_iMatchCount private
Referenced by GetSubCount(), InitValues(), IsValidSubNumber(), operator=(), PrivateRegFind(), and RegComp().
m_iOptions
uint32_t CRegExp::m_iOptions private
Referenced by CRegExp(), InitValues(), operator=(), and RegComp().
m_iOvector
PCRE2_SIZE* CRegExp::m_iOvector private
Referenced by CRegExp(), DumpOvector(), GetFindLen(), GetMatch(), GetSubLength(), GetSubStart(), InitValues(), operator=(), and PrivateRegFind().
m_jitCompiled
bool CRegExp::m_jitCompiled private
Referenced by InitValues(), operator=(), PrivateRegFind(), and RegComp().
m_jitStack
pcre2_jit_stack* CRegExp::m_jitStack private
Referenced by Cleanup(), CRegExp(), InitValues(), and PrivateRegFind().
m_JitSupported
int CRegExp::m_JitSupported = -1 static private
Referenced by IsJitSupported().
m_matchData
pcre2_match_data* CRegExp::m_matchData private
Referenced by Cleanup(), CRegExp(), InitValues(), and PrivateRegFind().
m_MaxNumOfBackrefrences
const int CRegExp::m_MaxNumOfBackrefrences = 20 static
Referenced by IsValidSubNumber().
m_offset
unsigned int CRegExp::m_offset private
Referenced by GetSubStart(), InitValues(), operator=(), PrivateRegFind(), and RegComp().
m_pattern
std::string CRegExp::m_pattern private
Referenced by GetPattern(), IsCompiled(), operator=(), and RegComp().
m_re
pcre2_code* CRegExp::m_re private
Referenced by Cleanup(), CRegExp(), GetCaptureTotal(), GetFindLen(), InitValues(), operator=(), PrivateRegFind(), and RegComp().
m_subject
std::string CRegExp::m_subject private
Referenced by GetMatch(), operator=(), and PrivateRegFind().
m_UcpSupported
int CRegExp::m_UcpSupported = -1 static private
Referenced by AreUnicodePropertiesSupported().
m_utf8Mode
utf8Mode CRegExp::m_utf8Mode private
Referenced by CRegExp(), InitValues(), and RegComp().
m_Utf8Supported
int CRegExp::m_Utf8Supported = -1 static private
Referenced by IsUtf8Supported().
OVECCOUNT
const int CRegExp::OVECCOUNT =(m_MaxNumOfBackrefrences + 1) * 3 static private
Referenced by PrivateRegFind().
The documentation for this class was generated from the following files:
RegExp.h
RegExp.cpp