Kodi Documentation: PVR::CPVRTimerType Class Reference
PVR::CPVRTimerType Class Reference
#include <PVRTimerType.h>
Public Member Functions
CPVRTimerType ()
CPVRTimerType (const PVR_TIMER_TYPE &type, int iClientId)
CPVRTimerType (unsigned int iTypeId, uint64_t iAttributes, const std::string &strDescription="")
virtual ~CPVRTimerType ()
CPVRTimerType (const CPVRTimerType &type)=delete
CPVRTimerType & operator= (const CPVRTimerType &orig)=delete
bool operator== (const CPVRTimerType &right) const
bool operator!= (const CPVRTimerType &right) const
void Update (const CPVRTimerType &type)
Update the data of this instance with the data given by another type instance.
int GetClientId () const
Get the PVR client id for this type.
unsigned int GetTypeId () const
Get the numeric type id of this type.
const std::string & GetDescription () const
Get the plain text (UI) description of this type.
uint64_t GetAttributes () const
Get the attributes of this type.
bool IsTimerRule () const
Check whether this type is for timer rules or one time timers.
bool IsReminder () const
Check whether this type is for reminder timers or recording timers.
bool IsOnetime () const
Check whether this type is for timer rules or one time timers.
bool IsManual () const
Check whether this type is for epg-based or manual timers.
bool IsEpgBased () const
Check whether this type is for epg-based or manual timers.
bool IsEpgBasedTimerRule () const
Check whether this type is for epg-based timer rules.
bool IsEpgBasedOnetime () const
Check whether this type is for one time epg-based timers.
bool IsManualTimerRule () const
Check whether this type is for manual timer rules.
bool IsManualOnetime () const
Check whether this type is for one time manual timers.
bool IsReadOnly () const
Check whether this type is readonly (must not be modified after initial creation).
bool AllowsDelete () const
Check whether this type allows deletion.
bool ForbidsNewInstances () const
Check whether this type forbids creation of new timers of this type.
bool ForbidsEpgTagOnCreate () const
Check whether this timer type is forbidden when epg tag info is present.
bool RequiresEpgTagOnCreate () const
Check whether this timer type requires epg tag info to be present.
bool RequiresEpgSeriesOnCreate () const
Check whether this timer type requires epg tag info including series attributes to be present.
bool RequiresEpgSeriesLinkOnCreate () const
Check whether this timer type requires epg tag info including a series link to be present.
bool SupportsEnableDisable () const
Check whether this type supports the "enabling/disabling" of timers of its type.
bool SupportsChannels () const
Check whether this type supports channels.
bool SupportsStartTime () const
Check whether this type supports start time.
bool SupportsEndTime () const
Check whether this type supports end time.
bool SupportsStartAnyTime () const
Check whether this type supports start any time.
bool SupportsEndAnyTime () const
Check whether this type supports end any time.
bool SupportsEpgTitleMatch () const
Check whether this type supports matching a search string against epg episode title.
bool SupportsEpgFulltextMatch () const
Check whether this type supports matching a search string against extended (fulltext) epg data. This includes title matching.
bool SupportsFirstDay () const
Check whether this type supports a first day the timer is active.
bool SupportsWeekdays () const
Check whether this type supports weekdays for timer schedules.
bool SupportsRecordOnlyNewEpisodes () const
Check whether this type supports the "record only new episodes" feature.
bool SupportsStartMargin () const
Check whether this type supports pre record time.
bool SupportsEndMargin () const
Check whether this type supports post record time.
bool SupportsPriority () const
Check whether this type supports recording priorities.
bool SupportsLifetime () const
Check whether this type supports lifetime for recordings.
bool SupportsMaxRecordings () const
Check whether this type supports MaxRecordings for recordings.
bool SupportsRecordingFolders () const
Check whether this type supports user specified recording folders.
bool SupportsRecordingGroup () const
Check whether this type supports recording groups.
bool SupportsAnyChannel () const
Check whether this type supports 'any channel', for example for defining a timer rule that should match any channel instead of a particular channel.
bool SupportsReadOnlyDelete () const
Check whether this type supports deletion of an otherwise read-only timer.
const std::vector< SettingIntValue > & GetPriorityValues () const
Obtain a list with all possible values for the priority attribute.
int GetPriorityDefault () const
Obtain the default value for the priority attribute.
const std::vector< SettingIntValue > & GetLifetimeValues () const
Obtain a list with all possible values for the lifetime attribute.
int GetLifetimeDefault () const
Obtain the default value for the lifetime attribute.
const std::vector< SettingIntValue > & GetMaxRecordingsValues () const
Obtain a list with all possible values for the MaxRecordings attribute.
int GetMaxRecordingsDefault () const
Obtain the default value for the MaxRecordings attribute.
const std::vector< SettingIntValue > & GetPreventDuplicateEpisodesValues () const
Obtain a list with all possible values for the duplicate episode prevention attribute.
int GetPreventDuplicateEpisodesDefault () const
Obtain the default value for the duplicate episode prevention attribute.
const std::vector< SettingIntValue > & GetRecordingGroupValues () const
Obtain a list with all possible values for the recording group attribute.
int GetRecordingGroupDefault () const
Obtain the default value for the Recording Group attribute.
const std::vector< std::shared_ptr< const CPVRTimerSettingDefinition > > & GetCustomSettingDefinitions () const
Get custom setting definitions for this type.
Static Public Member Functions
static const std::vector< std::shared_ptr< CPVRTimerType > > GetAllTypes ()
Return a list with all known timer types.
static const std::shared_ptr< CPVRTimerType > GetFirstAvailableType (const std::shared_ptr< const CPVRClient > &client)
Return the first available timer type from given client.
static std::shared_ptr< CPVRTimerType > CreateFromIds (unsigned int iTypeId, int iClientId)
Create a timer type from given timer type id and client id.
static std::shared_ptr< CPVRTimerType > CreateFromAttributes (uint64_t iMustHaveAttr, uint64_t iMustNotHaveAttr, int iClientId)
Create a timer type from given timer type attributes and client id.
Private Member Functions
void InitDescription ()
void InitAttributeValues (const PVR_TIMER_TYPE &type)
void InitPriorityValues (const PVR_TIMER_TYPE &type)
void InitLifetimeValues (const PVR_TIMER_TYPE &type)
void InitMaxRecordingsValues (const PVR_TIMER_TYPE &type)
void InitPreventDuplicateEpisodesValues (const PVR_TIMER_TYPE &type)
void InitRecordingGroupValues (const PVR_TIMER_TYPE &type)
void InitCustomSettingDefinitions (const PVR_TIMER_TYPE &type)
Private Attributes
int m_iClientId = PVR_CLIENT_INVALID_UID
unsigned int m_iTypeId
uint64_t m_iAttributes
std::string m_strDescription
CPVRIntSettingValues m_priorityValues {DEFAULT_RECORDING_PRIORITY}
CPVRIntSettingValues m_lifetimeValues {DEFAULT_RECORDING_LIFETIME}
CPVRIntSettingValues m_maxRecordingsValues {0}
CPVRIntSettingValues m_preventDupEpisodesValues {DEFAULT_RECORDING_DUPLICATEHANDLING}
CPVRIntSettingValues m_recordingGroupValues {0}
std::vector< std::shared_ptr< const CPVRTimerSettingDefinition > > m_customSettingDefs
Constructor & Destructor Documentation
CPVRTimerType() [1/4]
CPVRTimerType::CPVRTimerType ()
CPVRTimerType() [2/4]
CPVRTimerType::CPVRTimerType (const PVR_TIMER_TYPE & type, int iClientId)
References InitAttributeValues(), InitCustomSettingDefinitions(), and InitDescription().
CPVRTimerType() [3/4]
CPVRTimerType::CPVRTimerType (unsigned int iTypeId, uint64_t iAttributes, const std::string & strDescription = "")
References InitDescription().
~CPVRTimerType()
CPVRTimerType::~CPVRTimerType () virtual default
CPVRTimerType() [4/4]
PVR::CPVRTimerType::CPVRTimerType (const CPVRTimerType & type) delete
Member Function Documentation
AllowsDelete()
bool PVR::CPVRTimerType::AllowsDelete () const inline
Check whether this type allows deletion.
Returns
True if type allows deletion, false otherwise.
References IsReadOnly(), and SupportsReadOnlyDelete().
CreateFromAttributes()
std::shared_ptr< CPVRTimerType > CPVRTimerType::CreateFromAttributes (uint64_t iMustHaveAttr, uint64_t iMustNotHaveAttr, int iClientId) static
Create a timer type from given timer type attributes and client id.
Parameters
iMustHaveAttr a combination of PVR_TIMER_TYPE_* attributes the type to create must have.
iMustNotHaveAttr a combination of PVR_TIMER_TYPE_* attributes the type to create must not have.
iClientId the PVR client id.
Returns
A timer type instance.
References CreateFromAttributes(), GetAllTypes(), LOGERROR, PVR::PVR_CLIENT_INVALID_UID, and types.
Referenced by PVR::CPVRTimerInfoTag::CPVRTimerInfoTag(), PVR::CPVRTimerInfoTag::CPVRTimerInfoTag(), CreateFromAttributes(), PVR::CPVRTimerInfoTag::CreateFromDate(), and PVR::CPVRTimerInfoTag::CreateFromEpg().
CreateFromIds()
std::shared_ptr< CPVRTimerType > CPVRTimerType::CreateFromIds (unsigned int iTypeId, int iClientId) static
Create a timer type from given timer type id and client id.
Parameters
iTimerType the timer type id.
iClientId the PVR client id.
Returns
A timer type instance.
References CreateFromIds(), GetAllTypes(), LOGERROR, PVR::PVR_CLIENT_INVALID_UID, and types.
Referenced by PVR::CPVRTimerInfoTag::CPVRTimerInfoTag(), CreateFromIds(), and PVR::CPVRDatabase::GetTimers().
ForbidsEpgTagOnCreate()
bool PVR::CPVRTimerType::ForbidsEpgTagOnCreate () const inline
Check whether this timer type is forbidden when epg tag info is present.
Returns
True if new instances are forbidden when epg info is present, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_FORBIDS_EPG_TAG_ON_CREATE.
ForbidsNewInstances()
bool PVR::CPVRTimerType::ForbidsNewInstances () const inline
Check whether this type forbids creation of new timers of this type.
Returns
True if new instances are forbidden, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_FORBIDS_NEW_INSTANCES.
GetAllTypes()
const std::vector< std::shared_ptr< CPVRTimerType > > CPVRTimerType::GetAllTypes () static
Return a list with all known timer types.
Returns
A list of timer types or an empty list if no types available.
References PVR::CPVRManager::Clients(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetPVRManager(), PVR_TIMER_TYPE_IS_MANUAL, PVR_TIMER_TYPE_IS_READONLY, PVR_TIMER_TYPE_IS_REMINDER, PVR_TIMER_TYPE_IS_REPEATING, PVR_TIMER_TYPE_NONE, PVR_TIMER_TYPE_REQUIRES_EPG_TAG_ON_CREATE, PVR_TIMER_TYPE_SUPPORTS_ANY_CHANNEL, PVR_TIMER_TYPE_SUPPORTS_CHANNELS, PVR_TIMER_TYPE_SUPPORTS_ENABLE_DISABLE, PVR_TIMER_TYPE_SUPPORTS_END_ANYTIME, PVR_TIMER_TYPE_SUPPORTS_END_TIME, PVR_TIMER_TYPE_SUPPORTS_FIRST_DAY, PVR_TIMER_TYPE_SUPPORTS_FULLTEXT_EPG_MATCH, PVR_TIMER_TYPE_SUPPORTS_START_ANYTIME, PVR_TIMER_TYPE_SUPPORTS_START_END_MARGIN, PVR_TIMER_TYPE_SUPPORTS_START_MARGIN, PVR_TIMER_TYPE_SUPPORTS_START_TIME, PVR_TIMER_TYPE_SUPPORTS_TITLE_EPG_MATCH, and PVR_TIMER_TYPE_SUPPORTS_WEEKDAYS.
Referenced by CreateFromAttributes(), CreateFromIds(), and PVR::CGUIDialogPVRTimerSettings::InitializeTypesList().
GetAttributes()
uint64_t PVR::CPVRTimerType::GetAttributes () const inline
Get the attributes of this type.
Returns
The attributes.
References m_iAttributes.
GetClientId()
int PVR::CPVRTimerType::GetClientId () const inline
Get the PVR client id for this type.
Returns
The PVR client id.
References m_iClientId.
Referenced by PVR::CPVRCustomTimerSettings::IsSettingSupportedForTimerType(), and PVR::CPVRCustomTimerSettings::SetTimerType().
GetCustomSettingDefinitions()
const std::vector< std::shared_ptr< const CPVRTimerSettingDefinition > > & PVR::CPVRTimerType::GetCustomSettingDefinitions () const inline
Get custom setting definitions for this type.
Returns
The list of settings or an empty list if none present.
References m_customSettingDefs.
GetDescription()
const std::string & PVR::CPVRTimerType::GetDescription () const inline
Get the plain text (UI) description of this type.
Returns
The description.
References m_strDescription.
GetFirstAvailableType()
const std::shared_ptr< CPVRTimerType > CPVRTimerType::GetFirstAvailableType (const std::shared_ptr< const CPVRClient > & client) static
Return the first available timer type from given client.
Parameters
client the PVR client.
Returns
A timer type or NULL if none available.
References types.
Referenced by PVR::CPVRTimerInfoTag::CPVRTimerInfoTag().
GetLifetimeDefault()
int PVR::CPVRTimerType::GetLifetimeDefault () const inline
Obtain the default value for the lifetime attribute.
Returns
the default value.
References PVR::CPVRIntSettingValues::GetDefaultValue(), and m_lifetimeValues.
GetLifetimeValues()
const std::vector< SettingIntValue > & PVR::CPVRTimerType::GetLifetimeValues () const inline
Obtain a list with all possible values for the lifetime attribute.
Returns
the list with the values or an empty list, if lifetime is not supported by this type.
References PVR::CPVRIntSettingValues::GetValues(), and m_lifetimeValues.
GetMaxRecordingsDefault()
int PVR::CPVRTimerType::GetMaxRecordingsDefault () const inline
Obtain the default value for the MaxRecordings attribute.
Returns
the default value.
References PVR::CPVRIntSettingValues::GetDefaultValue(), and m_maxRecordingsValues.
GetMaxRecordingsValues()
const std::vector< SettingIntValue > & PVR::CPVRTimerType::GetMaxRecordingsValues () const inline
Obtain a list with all possible values for the MaxRecordings attribute.
Returns
the list with the values or an empty list, if MaxRecordings is not supported by this type.
References PVR::CPVRIntSettingValues::GetValues(), and m_maxRecordingsValues.
GetPreventDuplicateEpisodesDefault()
int PVR::CPVRTimerType::GetPreventDuplicateEpisodesDefault () const inline
Obtain the default value for the duplicate episode prevention attribute.
Returns
the default value.
References PVR::CPVRIntSettingValues::GetDefaultValue(), and m_preventDupEpisodesValues.
GetPreventDuplicateEpisodesValues()
const std::vector< SettingIntValue > & PVR::CPVRTimerType::GetPreventDuplicateEpisodesValues () const inline
Obtain a list with all possible values for the duplicate episode prevention attribute.
Returns
the list with the values or an empty list, if duplicate episode prevention is not supported by this type.
References PVR::CPVRIntSettingValues::GetValues(), and m_preventDupEpisodesValues.
GetPriorityDefault()
int PVR::CPVRTimerType::GetPriorityDefault () const inline
Obtain the default value for the priority attribute.
Returns
the default value.
References PVR::CPVRIntSettingValues::GetDefaultValue(), and m_priorityValues.
GetPriorityValues()
const std::vector< SettingIntValue > & PVR::CPVRTimerType::GetPriorityValues () const inline
Obtain a list with all possible values for the priority attribute.
Returns
the list with the values or an empty list, if priority is not supported by this type.
References PVR::CPVRIntSettingValues::GetValues(), and m_priorityValues.
GetRecordingGroupDefault()
int PVR::CPVRTimerType::GetRecordingGroupDefault () const inline
Obtain the default value for the Recording Group attribute.
Returns
the default value.
References PVR::CPVRIntSettingValues::GetDefaultValue(), and m_recordingGroupValues.
GetRecordingGroupValues()
const std::vector< SettingIntValue > & PVR::CPVRTimerType::GetRecordingGroupValues () const inline
Obtain a list with all possible values for the recording group attribute.
Returns
the list with the values or an empty list, if recording group is not supported by this type.
References PVR::CPVRIntSettingValues::GetValues(), and m_recordingGroupValues.
GetTypeId()
unsigned int PVR::CPVRTimerType::GetTypeId () const inline
Get the numeric type id of this type.
Returns
The type id.
References m_iTypeId.
Referenced by PVR::CPVRCustomTimerSettings::IsSettingSupportedForTimerType(), and PVR::CPVRCustomTimerSettings::SetTimerType().
InitAttributeValues()
void CPVRTimerType::InitAttributeValues (const PVR_TIMER_TYPE & type) private
References InitLifetimeValues(), InitMaxRecordingsValues(), InitPreventDuplicateEpisodesValues(), InitPriorityValues(), and InitRecordingGroupValues().
Referenced by CPVRTimerType().
InitCustomSettingDefinitions()
void CPVRTimerType::InitCustomSettingDefinitions (const PVR_TIMER_TYPE & type) private
References PVR::CPVRTimerSettingDefinition::CreateSettingDefinitionsList(), PVR_TIMER_TYPE::customSettingDefs, PVR_TIMER_TYPE::iCustomSettingDefsSize, m_customSettingDefs, m_iClientId, and m_iTypeId.
Referenced by CPVRTimerType().
InitDescription()
void CPVRTimerType::InitDescription () private
References g_localizeStrings, CLocalizeStrings::Get(), id, m_iAttributes, m_strDescription, PVR_TIMER_TYPE_IS_MANUAL, PVR_TIMER_TYPE_IS_REMINDER, and PVR_TIMER_TYPE_IS_REPEATING.
Referenced by CPVRTimerType(), and CPVRTimerType().
InitLifetimeValues()
void CPVRTimerType::InitLifetimeValues (const PVR_TIMER_TYPE & type) private
References PVR::DEFAULT_RECORDING_LIFETIME, g_localizeStrings, CLocalizeStrings::Get(), PVR_TIMER_TYPE::iLifetimesDefault, PVR_TIMER_TYPE::iLifetimesSize, PVR_TIMER_TYPE::lifetimes, m_lifetimeValues, SupportsLifetime(), and values.
Referenced by InitAttributeValues().
InitMaxRecordingsValues()
void CPVRTimerType::InitMaxRecordingsValues (const PVR_TIMER_TYPE & type) private
References PVR_TIMER_TYPE::iMaxRecordingsDefault, PVR_TIMER_TYPE::iMaxRecordingsSize, m_maxRecordingsValues, and PVR_TIMER_TYPE::maxRecordings.
Referenced by InitAttributeValues().
InitPreventDuplicateEpisodesValues()
void CPVRTimerType::InitPreventDuplicateEpisodesValues (const PVR_TIMER_TYPE & type) private
References PVR::DEFAULT_RECORDING_DUPLICATEHANDLING, g_localizeStrings, CLocalizeStrings::Get(), PVR_TIMER_TYPE::iPreventDuplicateEpisodesDefault, PVR_TIMER_TYPE::iPreventDuplicateEpisodesSize, m_preventDupEpisodesValues, PVR_TIMER_TYPE::preventDuplicateEpisodes, and SupportsRecordOnlyNewEpisodes().
Referenced by InitAttributeValues().
InitPriorityValues()
void CPVRTimerType::InitPriorityValues (const PVR_TIMER_TYPE & type) private
References PVR::DEFAULT_RECORDING_PRIORITY, PVR_TIMER_TYPE::iPrioritiesDefault, PVR_TIMER_TYPE::iPrioritiesSize, m_priorityValues, PVR_TIMER_TYPE::priorities, SupportsPriority(), and values.
Referenced by InitAttributeValues().
InitRecordingGroupValues()
void CPVRTimerType::InitRecordingGroupValues (const PVR_TIMER_TYPE & type) private
References PVR_TIMER_TYPE::iRecordingGroupDefault, PVR_TIMER_TYPE::iRecordingGroupSize, m_recordingGroupValues, and PVR_TIMER_TYPE::recordingGroup.
Referenced by InitAttributeValues().
IsEpgBased()
bool PVR::CPVRTimerType::IsEpgBased () const inline
Check whether this type is for epg-based or manual timers.
Returns
True if epg-based, false otherwise.
References IsManual().
Referenced by IsEpgBasedOnetime(), and IsEpgBasedTimerRule().
IsEpgBasedOnetime()
bool PVR::CPVRTimerType::IsEpgBasedOnetime () const inline
Check whether this type is for one time epg-based timers.
Returns
True if one time epg-based, false otherwise.
References IsEpgBased(), and IsOnetime().
IsEpgBasedTimerRule()
bool PVR::CPVRTimerType::IsEpgBasedTimerRule () const inline
Check whether this type is for epg-based timer rules.
Returns
True if epg-based timer rule, false otherwise.
References IsEpgBased(), and IsTimerRule().
IsManual()
bool PVR::CPVRTimerType::IsManual () const inline
Check whether this type is for epg-based or manual timers.
Returns
True if manual, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_IS_MANUAL.
Referenced by IsEpgBased(), IsManualOnetime(), and IsManualTimerRule().
IsManualOnetime()
bool PVR::CPVRTimerType::IsManualOnetime () const inline
Check whether this type is for one time manual timers.
Returns
True if one time manual, false otherwise.
References IsManual(), and IsOnetime().
IsManualTimerRule()
bool PVR::CPVRTimerType::IsManualTimerRule () const inline
Check whether this type is for manual timer rules.
Returns
True if manual timer rule, false otherwise.
References IsManual(), and IsTimerRule().
IsOnetime()
bool PVR::CPVRTimerType::IsOnetime () const inline
Check whether this type is for timer rules or one time timers.
Returns
True if type represents a one time timer, false otherwise.
References IsTimerRule().
Referenced by IsEpgBasedOnetime(), and IsManualOnetime().
IsReadOnly()
bool PVR::CPVRTimerType::IsReadOnly () const inline
Check whether this type is readonly (must not be modified after initial creation).
Returns
True if readonly, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_IS_READONLY.
Referenced by AllowsDelete().
IsReminder()
bool PVR::CPVRTimerType::IsReminder () const inline
Check whether this type is for reminder timers or recording timers.
Returns
True if type represents a reminder timer, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_IS_REMINDER.
IsTimerRule()
bool PVR::CPVRTimerType::IsTimerRule () const inline
Check whether this type is for timer rules or one time timers.
Returns
True if type represents a timer rule, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_IS_REPEATING.
Referenced by IsEpgBasedTimerRule(), IsManualTimerRule(), and IsOnetime().
operator!=()
bool CPVRTimerType::operator!= (const CPVRTimerType & right) const
References right.
operator=()
CPVRTimerType & PVR::CPVRTimerType::operator= (const CPVRTimerType & orig) delete
operator==()
bool CPVRTimerType::operator== (const CPVRTimerType & right) const
References m_customSettingDefs, m_iAttributes, m_iClientId, m_iTypeId, m_lifetimeValues, m_maxRecordingsValues, m_preventDupEpisodesValues, m_priorityValues, m_recordingGroupValues, m_strDescription, and right.
RequiresEpgSeriesLinkOnCreate()
bool PVR::CPVRTimerType::RequiresEpgSeriesLinkOnCreate () const inline
Check whether this timer type requires epg tag info including a series link to be present.
Returns
True if new instances require an EPG tag with a series link, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_REQUIRES_EPG_SERIESLINK_ON_CREATE.
RequiresEpgSeriesOnCreate()
bool PVR::CPVRTimerType::RequiresEpgSeriesOnCreate () const inline
Check whether this timer type requires epg tag info including series attributes to be present.
Returns
True if new instances require an EPG tag with series attributes, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_REQUIRES_EPG_SERIES_ON_CREATE.
RequiresEpgTagOnCreate()
bool PVR::CPVRTimerType::RequiresEpgTagOnCreate () const inline
Check whether this timer type requires epg tag info to be present.
Returns
True if new instances require EPG info, false otherwise.
References m_iAttributes, PVR_TIMER_TYPE_REQUIRES_EPG_SERIES_ON_CREATE, PVR_TIMER_TYPE_REQUIRES_EPG_SERIESLINK_ON_CREATE, and PVR_TIMER_TYPE_REQUIRES_EPG_TAG_ON_CREATE.
SupportsAnyChannel()
bool PVR::CPVRTimerType::SupportsAnyChannel () const inline
Check whether this type supports 'any channel', for example for defining a timer rule that should match any channel instead of a particular channel.
Returns
True if any channel is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_ANY_CHANNEL.
SupportsChannels()
bool PVR::CPVRTimerType::SupportsChannels () const inline
Check whether this type supports channels.
Returns
True if channels are supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_CHANNELS.
SupportsEnableDisable()
bool PVR::CPVRTimerType::SupportsEnableDisable () const inline
Check whether this type supports the "enabling/disabling" of timers of its type.
Returns
True if "enabling/disabling" feature is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_ENABLE_DISABLE.
SupportsEndAnyTime()
bool PVR::CPVRTimerType::SupportsEndAnyTime () const inline
Check whether this type supports end any time.
Returns
True if end any time is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_END_ANYTIME.
SupportsEndMargin()
bool PVR::CPVRTimerType::SupportsEndMargin () const inline
Check whether this type supports post record time.
Returns
True if post record time is supported, false otherwise.
References m_iAttributes, PVR_TIMER_TYPE_SUPPORTS_END_MARGIN, and PVR_TIMER_TYPE_SUPPORTS_START_END_MARGIN.
SupportsEndTime()
bool PVR::CPVRTimerType::SupportsEndTime () const inline
Check whether this type supports end time.
Returns
True if end time values are supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_END_TIME.
SupportsEpgFulltextMatch()
bool PVR::CPVRTimerType::SupportsEpgFulltextMatch () const inline
Check whether this type supports matching a search string against extended (fulltext) epg data. This includes title matching.
Returns
True if fulltext matching is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_FULLTEXT_EPG_MATCH.
SupportsEpgTitleMatch()
bool PVR::CPVRTimerType::SupportsEpgTitleMatch () const inline
Check whether this type supports matching a search string against epg episode title.
Returns
True if title matching is supported, false otherwise.
References m_iAttributes, PVR_TIMER_TYPE_SUPPORTS_FULLTEXT_EPG_MATCH, and PVR_TIMER_TYPE_SUPPORTS_TITLE_EPG_MATCH.
SupportsFirstDay()
bool PVR::CPVRTimerType::SupportsFirstDay () const inline
Check whether this type supports a first day the timer is active.
Returns
True if first day is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_FIRST_DAY.
SupportsLifetime()
bool PVR::CPVRTimerType::SupportsLifetime () const inline
Check whether this type supports lifetime for recordings.
Returns
True if recording lifetime is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_LIFETIME.
Referenced by InitLifetimeValues().
SupportsMaxRecordings()
bool PVR::CPVRTimerType::SupportsMaxRecordings () const inline
Check whether this type supports MaxRecordings for recordings.
Returns
True if MaxRecordings is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_MAX_RECORDINGS.
SupportsPriority()
bool PVR::CPVRTimerType::SupportsPriority () const inline
Check whether this type supports recording priorities.
Returns
True if recording priority is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_PRIORITY.
Referenced by InitPriorityValues().
SupportsReadOnlyDelete()
bool PVR::CPVRTimerType::SupportsReadOnlyDelete () const inline
Check whether this type supports deletion of an otherwise read-only timer.
Returns
True if read-only deletion is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_READONLY_DELETE.
Referenced by AllowsDelete().
SupportsRecordingFolders()
bool PVR::CPVRTimerType::SupportsRecordingFolders () const inline
Check whether this type supports user specified recording folders.
Returns
True if recording folders are supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_RECORDING_FOLDERS.
SupportsRecordingGroup()
bool PVR::CPVRTimerType::SupportsRecordingGroup () const inline
Check whether this type supports recording groups.
Returns
True if recording groups are supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_RECORDING_GROUP.
SupportsRecordOnlyNewEpisodes()
bool PVR::CPVRTimerType::SupportsRecordOnlyNewEpisodes () const inline
Check whether this type supports the "record only new episodes" feature.
Returns
True if the "record only new episodes" feature is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_RECORD_ONLY_NEW_EPISODES.
Referenced by InitPreventDuplicateEpisodesValues().
SupportsStartAnyTime()
bool PVR::CPVRTimerType::SupportsStartAnyTime () const inline
Check whether this type supports start any time.
Returns
True if start any time is supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_START_ANYTIME.
SupportsStartMargin()
bool PVR::CPVRTimerType::SupportsStartMargin () const inline
Check whether this type supports pre record time.
Returns
True if pre record time is supported, false otherwise.
References m_iAttributes, PVR_TIMER_TYPE_SUPPORTS_START_END_MARGIN, and PVR_TIMER_TYPE_SUPPORTS_START_MARGIN.
SupportsStartTime()
bool PVR::CPVRTimerType::SupportsStartTime () const inline
Check whether this type supports start time.
Returns
True if start time values are supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_START_TIME.
SupportsWeekdays()
bool PVR::CPVRTimerType::SupportsWeekdays () const inline
Check whether this type supports weekdays for timer schedules.
Returns
True if weekdays are supported, false otherwise.
References m_iAttributes, and PVR_TIMER_TYPE_SUPPORTS_WEEKDAYS.
Update()
void CPVRTimerType::Update (const CPVRTimerType & type)
Update the data of this instance with the data given by another type instance.
Parameters
type The instance containing the updated data.
References m_customSettingDefs, m_iAttributes, m_iClientId, m_iTypeId, m_lifetimeValues, m_maxRecordingsValues, m_preventDupEpisodesValues, m_priorityValues, m_recordingGroupValues, and m_strDescription.
Member Data Documentation
m_customSettingDefs
std::vector<std::shared_ptr<const CPVRTimerSettingDefinition> > PVR::CPVRTimerType::m_customSettingDefs private
Referenced by GetCustomSettingDefinitions(), InitCustomSettingDefinitions(), operator==(), and Update().
m_iAttributes
uint64_t PVR::CPVRTimerType::m_iAttributes private
Referenced by ForbidsEpgTagOnCreate(), ForbidsNewInstances(), GetAttributes(), InitDescription(), IsManual(), IsReadOnly(), IsReminder(), IsTimerRule(), operator==(), RequiresEpgSeriesLinkOnCreate(), RequiresEpgSeriesOnCreate(), RequiresEpgTagOnCreate(), SupportsAnyChannel(), SupportsChannels(), SupportsEnableDisable(), SupportsEndAnyTime(), SupportsEndMargin(), SupportsEndTime(), SupportsEpgFulltextMatch(), SupportsEpgTitleMatch(), SupportsFirstDay(), SupportsLifetime(), SupportsMaxRecordings(), SupportsPriority(), SupportsReadOnlyDelete(), SupportsRecordingFolders(), SupportsRecordingGroup(), SupportsRecordOnlyNewEpisodes(), SupportsStartAnyTime(), SupportsStartMargin(), SupportsStartTime(), SupportsWeekdays(), and Update().
m_iClientId
int PVR::CPVRTimerType::m_iClientId = PVR_CLIENT_INVALID_UID private
Referenced by GetClientId(), InitCustomSettingDefinitions(), operator==(), and Update().
m_iTypeId
unsigned int PVR::CPVRTimerType::m_iTypeId private
Referenced by GetTypeId(), InitCustomSettingDefinitions(), operator==(), and Update().
m_lifetimeValues
CPVRIntSettingValues PVR::CPVRTimerType::m_lifetimeValues {DEFAULT_RECORDING_LIFETIME} private
Referenced by GetLifetimeDefault(), GetLifetimeValues(), InitLifetimeValues(), operator==(), and Update().
m_maxRecordingsValues
CPVRIntSettingValues PVR::CPVRTimerType::m_maxRecordingsValues {0} private
Referenced by GetMaxRecordingsDefault(), GetMaxRecordingsValues(), InitMaxRecordingsValues(), operator==(), and Update().
m_preventDupEpisodesValues
CPVRIntSettingValues PVR::CPVRTimerType::m_preventDupEpisodesValues {DEFAULT_RECORDING_DUPLICATEHANDLING} private
Referenced by GetPreventDuplicateEpisodesDefault(), GetPreventDuplicateEpisodesValues(), InitPreventDuplicateEpisodesValues(), operator==(), and Update().
m_priorityValues
CPVRIntSettingValues PVR::CPVRTimerType::m_priorityValues {DEFAULT_RECORDING_PRIORITY} private
Referenced by GetPriorityDefault(), GetPriorityValues(), InitPriorityValues(), operator==(), and Update().
m_recordingGroupValues
CPVRIntSettingValues PVR::CPVRTimerType::m_recordingGroupValues {0} private
Referenced by GetRecordingGroupDefault(), GetRecordingGroupValues(), InitRecordingGroupValues(), operator==(), and Update().
m_strDescription
std::string PVR::CPVRTimerType::m_strDescription private
Referenced by GetDescription(), InitDescription(), operator==(), and Update().
The documentation for this class was generated from the following files:
PVRTimerType.h
PVRTimerType.cpp