Kodi Documentation: KODI::RETRO::CGUIGameVideoHandle Class Reference
KODI::RETRO::CGUIGameVideoHandle Class Reference
#include <GUIGameVideoHandle.h>
Public Member Functions
CGUIGameVideoHandle (CGUIGameRenderManager &renderManager)
virtual ~CGUIGameVideoHandle ()
bool IsPlayingGame ()
bool SupportsRenderFeature (RENDERFEATURE feature)
bool SupportsScalingMethod (SCALINGMETHOD method)
Private Attributes
CGUIGameRenderManager & m_renderManager
Constructor & Destructor Documentation
CGUIGameVideoHandle()
CGUIGameVideoHandle::CGUIGameVideoHandle (CGUIGameRenderManager & renderManager)
~CGUIGameVideoHandle()
CGUIGameVideoHandle::~CGUIGameVideoHandle () virtual
References m_renderManager, and KODI::RETRO::CGUIGameRenderManager::UnregisterHandle().
Member Function Documentation
IsPlayingGame()
bool CGUIGameVideoHandle::IsPlayingGame ()
References KODI::RETRO::CGUIGameRenderManager::IsPlayingGame(), and m_renderManager.
SupportsRenderFeature()
bool CGUIGameVideoHandle::SupportsRenderFeature (RENDERFEATURE feature)
References m_renderManager, and KODI::RETRO::CGUIGameRenderManager::SupportsRenderFeature().
SupportsScalingMethod()
bool CGUIGameVideoHandle::SupportsScalingMethod (SCALINGMETHOD method)
References m_renderManager, and KODI::RETRO::CGUIGameRenderManager::SupportsScalingMethod().
Member Data Documentation
m_renderManager
CGUIGameRenderManager& KODI::RETRO::CGUIGameVideoHandle::m_renderManager private
Referenced by IsPlayingGame(), SupportsRenderFeature(), SupportsScalingMethod(), and ~CGUIGameVideoHandle().
The documentation for this class was generated from the following files:
GUIGameVideoHandle.h
GUIGameVideoHandle.cpp