Kodi Documentation: CMouseStat Class Reference
CMouseStat Class Reference
#include <MouseStat.h>
Classes
class CButtonState
Holds information regarding a particular mouse button state.
Public Member Functions
CMouseStat ()
virtual ~CMouseStat ()
void Initialize ()
void HandleEvent (const XBMC_Event &newEvent)
void SetResolution (int maxX, int maxY, float speedX, float speedY)
bool IsActive ()
bool IsEnabled () const
void SetActive (bool active=true)
void SetState (MOUSE_STATE state)
void SetEnabled (bool enabled=true)
MOUSE_STATE GetState () const
uint32_t GetKey () const
HoldAction GetHold (int ButtonID) const
int GetX (void) const
int GetY (void) const
int GetDX (void) const
int GetDY (void) const
MousePosition GetPosition ()
Private Member Functions
bool MovedPastThreshold () const
detect whether the mouse has moved
Private Attributes
MOUSE_STATE m_pointerState {MOUSE_STATE_NORMAL}
MouseState m_mouseState {}
bool m_mouseEnabled
CButtonState m_buttonState [MOUSE_MAX_BUTTON]
int m_maxX {0}
int m_maxY {0}
float m_speedX {0.0f}
float m_speedY {0.0f}
unsigned int m_lastActiveTime
bool bClick [MOUSE_MAX_BUTTON] {}
bool bDoubleClick [MOUSE_MAX_BUTTON] {}
HoldAction m_hold [MOUSE_MAX_BUTTON] {}
bool bLongClick [MOUSE_MAX_BUTTON] {}
uint32_t m_Key
Constructor & Destructor Documentation
CMouseStat()
CMouseStat::CMouseStat ()
References KEY_MOUSE_NOOP, m_Key, and SetEnabled().
~CMouseStat()
CMouseStat::~CMouseStat () virtual default
Member Function Documentation
GetDX()
int CMouseStat::GetDX (void) const inline
References MouseState::dx, and m_mouseState.
Referenced by CInputManager::ProcessMouse().
GetDY()
int CMouseStat::GetDY (void) const inline
References MouseState::dy, and m_mouseState.
Referenced by CInputManager::ProcessMouse().
GetHold()
HoldAction CMouseStat::GetHold (int ButtonID) const
References m_hold, MOUSE_LEFT_BUTTON, and NONE.
Referenced by CInputManager::ProcessMouse().
GetKey()
uint32_t CMouseStat::GetKey () const
References m_Key.
Referenced by CInputManager::ProcessMouse().
GetPosition()
MousePosition CMouseStat::GetPosition () inline
References m_mouseState, MouseState::x, and MouseState::y.
Referenced by CInputManager::GetMousePosition().
GetState()
MOUSE_STATE CMouseStat::GetState () const inline
References m_pointerState.
Referenced by CInputManager::GetMouseState().
GetX()
int CMouseStat::GetX (void) const inline
References m_mouseState, and MouseState::x.
Referenced by CInputManager::ProcessMouse().
GetY()
int CMouseStat::GetY (void) const inline
References m_mouseState, and MouseState::y.
Referenced by CInputManager::ProcessMouse().
HandleEvent()
void CMouseStat::HandleEvent (const XBMC_Event & newEvent)
References bClick, bDoubleClick, bLongClick, MouseState::button, XBMC_MouseButtonEvent::button, XBMC_Event::button, DRAG, DRAG_END, DRAG_START, MouseState::dx, MouseState::dy, MouseState::dz, CTimeUtils::GetFrameTime(), KEY_MOUSE_CLICK, KEY_MOUSE_DOUBLE_CLICK, KEY_MOUSE_DRAG, KEY_MOUSE_DRAG_END, KEY_MOUSE_DRAG_START, KEY_MOUSE_LONG_CLICK, KEY_MOUSE_MOVE, KEY_MOUSE_NOOP, KEY_MOUSE_RDRAG, KEY_MOUSE_RDRAG_END, KEY_MOUSE_RDRAG_START, KEY_MOUSE_WHEEL_DOWN, KEY_MOUSE_WHEEL_UP, m_buttonState, m_hold, m_Key, m_maxX, m_maxY, m_mouseState, CMouseStat::CButtonState::MB_DOUBLE_CLICK, CMouseStat::CButtonState::MB_DRAG, CMouseStat::CButtonState::MB_DRAG_END, CMouseStat::CButtonState::MB_DRAG_START, CMouseStat::CButtonState::MB_LONG_CLICK, CMouseStat::CButtonState::MB_SHORT_CLICK, XBMC_Event::motion, MOUSE_EXTRA_BUTTON1, MOUSE_EXTRA_BUTTON2, MOUSE_EXTRA_BUTTON3, MOUSE_EXTRA_BUTTON4, MOUSE_LEFT_BUTTON, MOUSE_MAX_BUTTON, MOUSE_MIDDLE_BUTTON, MOUSE_RIGHT_BUTTON, MOUSE_STATE_NORMAL, MovedPastThreshold(), NONE, SetActive(), SetState(), XBMC_Event::type, CMouseStat::CButtonState::Update(), MouseState::x, XBMC_MouseMotionEvent::x, XBMC_MouseButtonEvent::x, XBMC_BUTTON_LEFT, XBMC_BUTTON_MIDDLE, XBMC_BUTTON_RIGHT, XBMC_BUTTON_WHEELDOWN, XBMC_BUTTON_WHEELUP, XBMC_BUTTON_X1, XBMC_BUTTON_X2, XBMC_BUTTON_X3, XBMC_BUTTON_X4, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, XBMC_MOUSEMOTION, MouseState::y, XBMC_MouseMotionEvent::y, and XBMC_MouseButtonEvent::y.
Referenced by CInputManager::OnEvent().
Initialize()
void CMouseStat::Initialize ()
References SetResolution().
Referenced by CInputManager::InitializeInputs().
IsActive()
bool CMouseStat::IsActive ()
References MouseState::active, CTimeUtils::GetFrameTime(), IsEnabled(), m_lastActiveTime, m_mouseState, MOUSE_ACTIVE_LENGTH, and SetActive().
Referenced by CInputManager::IsMouseActive(), and CInputManager::ProcessMouse().
IsEnabled()
bool CMouseStat::IsEnabled () const
References m_mouseEnabled.
Referenced by IsActive(), CInputManager::ProcessEventServer(), and SetActive().
MovedPastThreshold()
bool CMouseStat::MovedPastThreshold () const private
detect whether the mouse has moved
Uses a trigger threshold of 2 pixels to detect mouse movement
Returns
whether the mouse has moved past the trigger threshold.
References MouseState::dx, MouseState::dy, m_mouseState, and MOUSE_MINIMUM_MOVEMENT.
Referenced by HandleEvent().
SetActive()
void CMouseStat::SetActive (bool active = true)
References MouseState::active, CTimeUtils::GetFrameTime(), CServiceBroker::GetWinSystem(), IsEnabled(), m_lastActiveTime, m_mouseState, and CWinSystemBase::ShowOSMouse().
Referenced by HandleEvent(), CInputManager::HandleKey(), IsActive(), CInputManager::ProcessEventServer(), CInputManager::ProcessMouse(), SetEnabled(), and CInputManager::SetMouseActive().
SetEnabled()
void CMouseStat::SetEnabled (bool enabled = true)
References m_mouseEnabled, and SetActive().
Referenced by CMouseStat(), CInputManager::InitializeInputs(), CInputManager::OnSettingChanged(), and CInputManager::SetMouseEnabled().
SetResolution()
void CMouseStat::SetResolution (int maxX, int maxY, float speedX, float speedY)
References m_maxX, m_maxY, m_speedX, and m_speedY.
Referenced by Initialize(), and CInputManager::SetMouseResolution().
SetState()
void CMouseStat::SetState (MOUSE_STATE state) inline
References m_pointerState.
Referenced by HandleEvent(), and CInputManager::SetMouseState().
Member Data Documentation
bClick
bool CMouseStat::bClick[MOUSE_MAX_BUTTON] {} private
Referenced by HandleEvent().
bDoubleClick
bool CMouseStat::bDoubleClick[MOUSE_MAX_BUTTON] {} private
Referenced by HandleEvent().
bLongClick
bool CMouseStat::bLongClick[MOUSE_MAX_BUTTON] {} private
Referenced by HandleEvent().
m_buttonState
CButtonState CMouseStat::m_buttonState[MOUSE_MAX_BUTTON] private
Referenced by HandleEvent().
m_hold
HoldAction CMouseStat::m_hold[MOUSE_MAX_BUTTON] {} private
Referenced by GetHold(), and HandleEvent().
m_Key
uint32_t CMouseStat::m_Key private
Referenced by CMouseStat(), GetKey(), and HandleEvent().
m_lastActiveTime
unsigned int CMouseStat::m_lastActiveTime private
Referenced by IsActive(), and SetActive().
m_maxX
int CMouseStat::m_maxX {0} private
Referenced by HandleEvent(), and SetResolution().
m_maxY
int CMouseStat::m_maxY {0} private
Referenced by HandleEvent(), and SetResolution().
m_mouseEnabled
bool CMouseStat::m_mouseEnabled private
Referenced by IsEnabled(), and SetEnabled().
m_mouseState
MouseState CMouseStat::m_mouseState {} private
Referenced by GetDX(), GetDY(), GetPosition(), GetX(), GetY(), HandleEvent(), IsActive(), MovedPastThreshold(), and SetActive().
m_pointerState
MOUSE_STATE CMouseStat::m_pointerState {MOUSE_STATE_NORMAL} private
Referenced by GetState(), and SetState().
m_speedX
float CMouseStat::m_speedX {0.0f} private
Referenced by SetResolution().
m_speedY
float CMouseStat::m_speedY {0.0f} private
Referenced by SetResolution().
The documentation for this class was generated from the following files:
MouseStat.h
MouseStat.cpp