Kodi Documentation: PVR::UTILS Namespace Reference
PVR::UTILS Namespace Reference
Functions
bool HasClientAndProvider (const std::string &path)
Check whether the given path contains a client id and a provider id.
bool GetClientAndProviderFromPath (const CURL &url, int &clientId, int &providerId)
Get client id and provider id from the given URL.
std::string GetProviderNameFromPath (const std::string &path)
Get the name of a provider from the given path.
Function Documentation
GetClientAndProviderFromPath()
bool PVR::UTILS::GetClientAndProviderFromPath (const CURL & url, int & clientId, int & providerId)
Get client id and provider id from the given URL.
Parameters
url The URL.
clientId Filled with the client id on success, PVR_CLIENT_INVALID_UID otherwise
providerId Filled with the provider id on success, PVR_PROVIDER_INVALID_UID otherwise
Returns
True on success, false otherwise.
References CURL::GetOption(), PVR::PVR_CLIENT_INVALID_UID, and PVR_PROVIDER_INVALID_UID.
Referenced by GetProviderNameFromPath().
GetProviderNameFromPath()
std::string PVR::UTILS::GetProviderNameFromPath (const std::string & path)
Get the name of a provider from the given path.
Parameters
path The path.
Returns
the name on success, an empty string otherwise.
References GetClientAndProviderFromPath(), CServiceBroker::GetPVRManager(), PVR::CPVRManager::Providers(), PVR::PVR_CLIENT_INVALID_UID, and PVR_PROVIDER_INVALID_UID.
Referenced by PVR::CGUIWindowPVRChannelsBase::UpdateButtons(), and PVR::CGUIWindowPVRRecordingsBase::UpdateButtons().
HasClientAndProvider()
bool PVR::UTILS::HasClientAndProvider (const std::string & path)
Check whether the given path contains a client id and a provider id.
Parameters
path The path.
Returns
True if both client id and provider id are present, false otherwise.
References CURL::GetOption().
Referenced by PVR::CGUIWindowPVRRecordingsBase::OnDeinitWindow().