Kodi Documentation: ADDON::Interface_GUIDialogFileBrowser Struct Reference
ADDON::Interface_GUIDialogFileBrowser Struct Reference
Global gui Add-on to Kodi callback functions.
#include <FileBrowser.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static bool show_and_get_directory (KODI_HANDLE kodiBase, const char *shares, const char *heading, const char *path_in, char **path_out, bool write_only)
callback functions from add-on to kodi
static bool show_and_get_file (KODI_HANDLE kodiBase, const char *shares, const char *mask, const char *heading, const char *path_in, char **path_out, bool use_thumbs, bool use_file_directories)
static bool show_and_get_file_from_dir (KODI_HANDLE kodiBase, const char *directory, const char *mask, const char *heading, const char *path_in, char **path_out, bool use_thumbs, bool use_file_directories, bool singleList)
static bool show_and_get_file_list (KODI_HANDLE kodiBase, const char *shares, const char *mask, const char *heading, char ***file_list, unsigned int *entries, bool use_thumbs, bool use_file_directories)
static bool show_and_get_source (KODI_HANDLE kodiBase, const char *path_in, char **path_out, bool allow_network_shares, const char *additional_share, const char *type)
static bool show_and_get_image (KODI_HANDLE kodiBase, const char *shares, const char *heading, const char *path_in, char **path_out)
static bool show_and_get_image_list (KODI_HANDLE kodiBase, const char *shares, const char *heading, char ***file_list, unsigned int *entries)
static void clear_file_list (KODI_HANDLE kodiBase, char ***file_list, unsigned int entries)
Static Private Member Functions
static void GetVECShares (std::vector< CMediaSource > &vecShares, const std::string &strShares, const std::string &strPath)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/dialogs/FileBrowser.h"
Member Function Documentation
clear_file_list()
void ADDON::Interface_GUIDialogFileBrowser::clear_file_list (KODI_HANDLE kodiBase, char *** file_list, unsigned int entries) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
DeInit()
void ADDON::Interface_GUIDialogFileBrowser::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogFileBrowser, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
GetVECShares()
void ADDON::Interface_GUIDialogFileBrowser::GetVECShares (std::vector< CMediaSource > & vecShares, const std::string & strShares, const std::string & strPath) static private
References CMediaSourceSettings::GetInstance(), CMediaManager::GetLocalDrives(), CServiceBroker::GetMediaManager(), CMediaManager::GetNetworkLocations(), URIUtils::GetParentPath(), CMediaManager::GetRemovableDrives(), CMediaSourceSettings::GetSources(), CURL::GetWithoutUserDetails(), CMediaSource::strName, and CMediaSource::strPath.
Referenced by show_and_get_directory(), show_and_get_file(), show_and_get_file_list(), show_and_get_image(), show_and_get_image_list(), and show_and_get_source().
Init()
void ADDON::Interface_GUIDialogFileBrowser::Init (AddonGlobalInterface * addonInterface) static
References clear_file_list(), AddonToKodiFuncTable_kodi_gui_dialogFileBrowser::clear_file_list, AddonToKodiFuncTable_kodi_gui::dialogFileBrowser, AddonToKodiFuncTable_Addon::kodi_gui, show_and_get_directory(), AddonToKodiFuncTable_kodi_gui_dialogFileBrowser::show_and_get_directory, show_and_get_file(), AddonToKodiFuncTable_kodi_gui_dialogFileBrowser::show_and_get_file, show_and_get_file_from_dir(), AddonToKodiFuncTable_kodi_gui_dialogFileBrowser::show_and_get_file_from_dir, show_and_get_file_list(), AddonToKodiFuncTable_kodi_gui_dialogFileBrowser::show_and_get_file_list, show_and_get_image(), AddonToKodiFuncTable_kodi_gui_dialogFileBrowser::show_and_get_image, show_and_get_image_list(), AddonToKodiFuncTable_kodi_gui_dialogFileBrowser::show_and_get_image_list, show_and_get_source(), AddonToKodiFuncTable_kodi_gui_dialogFileBrowser::show_and_get_source, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
show_and_get_directory()
bool ADDON::Interface_GUIDialogFileBrowser::show_and_get_directory (KODI_HANDLE kodiBase, const char * shares, const char * heading, const char * path_in, char ** path_out, bool write_only) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References GetVECShares(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogFileBrowser::ShowAndGetDirectory().
Referenced by Init().
show_and_get_file()
bool ADDON::Interface_GUIDialogFileBrowser::show_and_get_file (KODI_HANDLE kodiBase, const char * shares, const char * mask, const char * heading, const char * path_in, char ** path_out, bool use_thumbs, bool use_file_directories) static
References GetVECShares(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogFileBrowser::ShowAndGetFile().
Referenced by Init().
show_and_get_file_from_dir()
bool ADDON::Interface_GUIDialogFileBrowser::show_and_get_file_from_dir (KODI_HANDLE kodiBase, const char * directory, const char * mask, const char * heading, const char * path_in, char ** path_out, bool use_thumbs, bool use_file_directories, bool singleList) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogFileBrowser::ShowAndGetFile().
Referenced by Init().
show_and_get_file_list()
bool ADDON::Interface_GUIDialogFileBrowser::show_and_get_file_list (KODI_HANDLE kodiBase, const char * shares, const char * mask, const char * heading, char *** file_list, unsigned int * entries, bool use_thumbs, bool use_file_directories) static
References GetVECShares(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogFileBrowser::ShowAndGetFileList().
Referenced by Init().
show_and_get_image()
bool ADDON::Interface_GUIDialogFileBrowser::show_and_get_image (KODI_HANDLE kodiBase, const char * shares, const char * heading, const char * path_in, char ** path_out) static
References GetVECShares(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogFileBrowser::ShowAndGetImage().
Referenced by Init().
show_and_get_image_list()
bool ADDON::Interface_GUIDialogFileBrowser::show_and_get_image_list (KODI_HANDLE kodiBase, const char * shares, const char * heading, char *** file_list, unsigned int * entries) static
References GetVECShares(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogFileBrowser::ShowAndGetImageList().
Referenced by Init().
show_and_get_source()
bool ADDON::Interface_GUIDialogFileBrowser::show_and_get_source (KODI_HANDLE kodiBase, const char * path_in, char ** path_out, bool allow_network_shares, const char * additional_share, const char * type) static
References GetVECShares(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogFileBrowser::ShowAndGetSource().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/dialogs/filebrowser.h
FileBrowser.cpp