Kodi Documentation: TestMap.cpp File Reference
TestMap.cpp File Reference
#include "utils/Map.h"
#include <algorithm>
#include <gtest/gtest.h>
Functions
TEST (TestMap, SortableKey)
TEST (TestMap, NonSortableKey)
TEST (TestMap, EnumConstexpr)
Function Documentation
TEST() [1/3]
TEST (TestMap , EnumConstexpr)
TEST() [2/3]
TEST (TestMap , NonSortableKey)
References EXPECT_EQ(), and operator==().
TEST() [3/3]
TEST (TestMap , SortableKey)
References EXPECT_EQ(), and EXPECT_TRUE().