Kodi Documentation: KODI::GUILIB::GUIINFO::CSystemGUIInfo Class Reference
KODI::GUILIB::GUIINFO::CSystemGUIInfo Class Reference
#include <SystemGUIInfo.h>
Public Member Functions
CSystemGUIInfo ()
~CSystemGUIInfo () override=default
bool InitCurrentItem (CFileItem *item) override
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) const override
Get a GUIInfoManager label string.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager integer value.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager bool value.
float GetFPS () const
void UpdateFPS ()
Public Member Functions inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
CGUIInfoProvider ()=default
~CGUIInfoProvider () override=default
bool GetFallbackLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) override
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo) override
Set new audio/video stream info data.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::IGUIInfoProvider
virtual ~IGUIInfoProvider ()=default
Private Member Functions
std::string GetSystemHeatInfo (int info) const
Private Attributes
std::unique_ptr< CGPUInfo > m_gpuInfo
unsigned int m_lastSysHeatInfoTime
CTemperature m_gpuTemp
CTemperature m_cpuTemp
int m_fanSpeed = 0
float m_fps = 0.0
unsigned int m_frameCounter = 0
unsigned int m_lastFPSTime = 0
Static Private Attributes
static const int SYSTEM_HEAT_UPDATE_INTERVAL = 60000
Additional Inherited Members
Protected Attributes inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
VideoStreamInfo m_videoInfo
AudioStreamInfo m_audioInfo
SubtitleStreamInfo m_subtitleInfo
Constructor & Destructor Documentation
CSystemGUIInfo()
CSystemGUIInfo::CSystemGUIInfo ()
~CSystemGUIInfo()
KODI::GUILIB::GUIINFO::CSystemGUIInfo::~CSystemGUIInfo () override default
Member Function Documentation
GetBool()
bool CSystemGUIInfo::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager bool value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CGUIPassword::bMasterUser, CPowerManager::CanHibernate(), CPowerManager::CanPowerdown(), CPowerManager::CanReboot(), CPowerManager::CanSuspend(), CGUIMediaWindow::CurrentDirectory(), CSettingUtils::FindIntInList(), g_alarmClock, g_passwordManager, g_sysinfo, CServiceBroker::GetAddonMgr(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppParams(), CFileItemList::GetContent(), CServiceBroker::GetCPUInfo(), CDateTime::GetCurrentDateTime(), CDateTime::GetDay(), CMediaManager::GetDriveStatus(), CServiceBroker::GetGUI(), CInfoLoader::GetInfo(), CMediaSettings::GetInstance(), CServiceBroker::GetMediaManager(), KODI::GUILIB::GUIINFO::GetMediaWindow(), CDateTime::GetMinuteOfDay(), CDateTime::GetMonth(), CServiceBroker::GetPowerManager(), CAlarmClock::GetRemaining(), CServiceBroker::GetSettingsComponent(), CMediaSettings::GetWatchedMode(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), ADDON::CAddonMgr::HasAddons(), CAlarmClock::HasAlarm(), CSysInfo::HasInternet(), MEDIA_DETECT::CCdInfo::IsAudio(), MEDIA_DETECT::CCdInfo::IsCDExtra(), CMediaManager::IsDiscInDrive(), CWinSystemBase::IsFullScreen(), CApplicationPowerHandling::IsInScreenSaver(), MEDIA_DETECT::CCdInfo::IsMixedMode(), LOCK_MODE_EVERYONE, NOT_READY, OPEN, ADDON::PVRDLL, CSettings::SETTING_POWERMANAGEMENT_SHUTDOWNTIME, CSettings::SETTING_VIDEOLIBRARY_SHOWUNWATCHEDPLOTS, SYSTEM_ALARM_LESS_OR_EQUAL, SYSTEM_ALWAYS_FALSE, SYSTEM_ALWAYS_TRUE, SYSTEM_CAN_HIBERNATE, SYSTEM_CAN_POWERDOWN, SYSTEM_CAN_REBOOT, SYSTEM_CAN_SUSPEND, SYSTEM_DATE, SYSTEM_DPMS_ACTIVE, SYSTEM_DVDREADY, SYSTEM_ETHERNET_LINK_ACTIVE, SYSTEM_GET_BOOL, SYSTEM_HAS_ALARM, SYSTEM_HAS_CMS, SYSTEM_HAS_CORE_ID, SYSTEM_HAS_LOGINSCREEN, SYSTEM_HAS_PVR, SYSTEM_HAS_PVR_ADDON, SYSTEM_HAS_SHUTDOWN, SYSTEM_HASLOCKS, SYSTEM_IDLE_SHUTDOWN_INHIBITED, SYSTEM_IDLE_TIME, SYSTEM_INTERNET_STATE, SYSTEM_IS_SCREENSAVER_INHIBITED, SYSTEM_ISFULLSCREEN, SYSTEM_ISMASTER, SYSTEM_ISSTANDALONE, SYSTEM_LOGGEDON, SYSTEM_MEDIA_AUDIO_CD, SYSTEM_MEDIA_DVD, SYSTEM_PLATFORM_ANDROID, SYSTEM_PLATFORM_DARWIN, SYSTEM_PLATFORM_DARWIN_IOS, SYSTEM_PLATFORM_DARWIN_OSX, SYSTEM_PLATFORM_DARWIN_TVOS, SYSTEM_PLATFORM_LINUX, SYSTEM_PLATFORM_UWP, SYSTEM_PLATFORM_WEBOS, SYSTEM_PLATFORM_WINDOWS, SYSTEM_SCREENSAVER_ACTIVE, SYSTEM_SETTING, SYSTEM_SHOW_EXIT_BUTTON, SYSTEM_SUPPORTS_CPU_USAGE, SYSTEM_TIME, SYSTEM_TRAYOPEN, value, CSettings::VIDEOLIBRARY_THUMB_SHOW_UNWATCHED_EPISODE, WatchedModeUnwatched, and WINDOW_LOGIN_SCREEN.
GetFPS()
float KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetFPS () const inline
References m_fps.
Referenced by CGUIWindowDebugInfo::Process().
GetInt()
bool CSystemGUIInfo::GetInt (int & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager integer value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References KODI::MEMORY::MemoryStatus::availPhys, CPowerManager::BatteryLevel(), g_sysinfo, CServiceBroker::GetCPUInfo(), CSysInfo::GetHddSpaceInfo(), KODI::MEMORY::GetMemoryStatus(), CServiceBroker::GetPowerManager(), SYSTEM_BATTERY_LEVEL, SYSTEM_CPU_USAGE, SYSTEM_FREE_MEMORY, SYSTEM_FREE_SPACE, SYSTEM_USED_MEMORY, SYSTEM_USED_SPACE, KODI::MEMORY::MemoryStatus::totalPhys, and value.
GetLabel()
bool CSystemGUIInfo::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) const override virtual
Get a GUIInfoManager label string.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References KODI::MEMORY::MemoryStatus::availPhys, RESOLUTION_INFO::fRefreshRate, g_alarmClock, g_langInfo, g_localizeStrings, g_sysinfo, CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), CDateTime::GetAsLocalizedDate(), CDateTime::GetAsLocalizedTime(), CSysInfo::GetBuildDate(), CServiceBroker::GetCPUInfo(), CDateTime::GetCurrentDateTime(), CSysInfo::GetDeviceName(), CWinSystemBase::GetDisplayHDRCapabilities(), CWinSystemBase::GetGfxContext(), CSysInfo::GetHddSpaceInfo(), CInfoLoader::GetInfo(), ADDON::CAddonMgr::GetLastAvailableUpdatesCountAsString(), CServiceBroker::GetMediaManager(), KODI::MEMORY::GetMemoryStatus(), CWinSystemBase::GetName(), CSysInfo::GetPrivacyPolicy(), CAlarmClock::GetRemaining(), CRenderSystemBase::GetRenderRenderer(), CServiceBroker::GetRenderSystem(), CRenderSystemBase::GetRenderVendor(), CRenderSystemBase::GetRenderVersionString(), CGraphicContext::GetResInfo(), CServiceBroker::GetSettingsComponent(), GetSystemHeatInfo(), CSysInfo::GetVersion(), CSysInfo::GetVersionCode(), CSysInfo::GetVersionGit(), CSysInfo::GetVersionShort(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, m_fps, MB, NETWORK_DNS1_ADDRESS, NETWORK_DNS2_ADDRESS, NETWORK_GATEWAY_ADDRESS, NETWORK_IP_ADDRESS, NETWORK_LINK_STATE, NETWORK_MAC_ADDRESS, NETWORK_SUBNET_MASK, CSettings::SETTING_VIDEOSCREEN_STEREOSCOPICMODE, RESOLUTION_INFO::strMode, CHDRCapabilities::SupportsDolbyVision(), CHDRCapabilities::SupportsHDR10Plus(), CHDRCapabilities::SupportsHLG(), SYSTEM_ADDON_UPDATE_COUNT, SYSTEM_ALARM_POS, SYSTEM_BATTERY_LEVEL, SYSTEM_BUILD_DATE, SYSTEM_BUILD_VERSION, SYSTEM_BUILD_VERSION_CODE, SYSTEM_BUILD_VERSION_GIT, SYSTEM_BUILD_VERSION_SHORT, SYSTEM_CPU_TEMPERATURE, SYSTEM_CPU_USAGE, SYSTEM_CPUFREQUENCY, SYSTEM_DATE, SYSTEM_DVD_LABEL, SYSTEM_FAN_SPEED, SYSTEM_FPS, SYSTEM_FREE_MEMORY, SYSTEM_FREE_MEMORY_PERCENT, SYSTEM_FREE_SPACE, SYSTEM_FREE_SPACE_PERCENT, SYSTEM_FRIENDLY_NAME, SYSTEM_GET_CORE_USAGE, SYSTEM_GPU_TEMPERATURE, SYSTEM_INTERNET_STATE, SYSTEM_LANGUAGE, SYSTEM_LOCALE, SYSTEM_LOCALE_REGION, SYSTEM_OS_VERSION_INFO, SYSTEM_PLATFORM_WINDOWING, SYSTEM_PRIVACY_POLICY, SYSTEM_PROFILEAUTOLOGIN, SYSTEM_PROFILECOUNT, SYSTEM_PROFILENAME, SYSTEM_PROFILETHUMB, SYSTEM_RENDER_RENDERER, SYSTEM_RENDER_VENDOR, SYSTEM_RENDER_VERSION, SYSTEM_SCREEN_HEIGHT, SYSTEM_SCREEN_MODE, SYSTEM_SCREEN_RESOLUTION, SYSTEM_SCREEN_WIDTH, SYSTEM_STEREOSCOPIC_MODE, SYSTEM_SUPPORTED_HDR_TYPES, SYSTEM_TEMPERATURE_UNITS, SYSTEM_TIME, SYSTEM_TOTAL_MEMORY, SYSTEM_TOTAL_SPACE, SYSTEM_TOTALUPTIME, SYSTEM_UPTIME, SYSTEM_USED_MEMORY, SYSTEM_USED_MEMORY_PERCENT, SYSTEM_USED_SPACE, SYSTEM_USED_SPACE_PERCENT, SYSTEM_VIDEO_ENCODER_INFO, KODI::MEMORY::MemoryStatus::totalPhys, types, and value.
GetSystemHeatInfo()
std::string CSystemGUIInfo::GetSystemHeatInfo (int info) const private
References g_langInfo, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetCPUInfo(), CTimeUtils::GetFrameTime(), CTemperature::IsValid(), m_cpuTemp, m_fanSpeed, m_gpuInfo, m_gpuTemp, m_lastSysHeatInfoTime, SYSTEM_CPU_TEMPERATURE, SYSTEM_CPU_USAGE, SYSTEM_FAN_SPEED, SYSTEM_GPU_TEMPERATURE, SYSTEM_HEAT_UPDATE_INTERVAL, and text.
Referenced by GetLabel().
InitCurrentItem()
bool CSystemGUIInfo::InitCurrentItem (CFileItem * item) override virtual
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by the provider, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
UpdateFPS()
void CSystemGUIInfo::UpdateFPS ()
References CTimeUtils::GetFrameTime(), m_fps, m_frameCounter, and m_lastFPSTime.
Referenced by CApplication::Render().
Member Data Documentation
m_cpuTemp
CTemperature KODI::GUILIB::GUIINFO::CSystemGUIInfo::m_cpuTemp mutable private
Referenced by GetSystemHeatInfo().
m_fanSpeed
int KODI::GUILIB::GUIINFO::CSystemGUIInfo::m_fanSpeed = 0 private
Referenced by GetSystemHeatInfo().
m_fps
float KODI::GUILIB::GUIINFO::CSystemGUIInfo::m_fps = 0.0 private
Referenced by GetFPS(), GetLabel(), and UpdateFPS().
m_frameCounter
unsigned int KODI::GUILIB::GUIINFO::CSystemGUIInfo::m_frameCounter = 0 private
Referenced by UpdateFPS().
m_gpuInfo
std::unique_ptr<CGPUInfo> KODI::GUILIB::GUIINFO::CSystemGUIInfo::m_gpuInfo private
Referenced by GetSystemHeatInfo().
m_gpuTemp
CTemperature KODI::GUILIB::GUIINFO::CSystemGUIInfo::m_gpuTemp mutable private
Referenced by GetSystemHeatInfo().
m_lastFPSTime
unsigned int KODI::GUILIB::GUIINFO::CSystemGUIInfo::m_lastFPSTime = 0 private
Referenced by UpdateFPS().
m_lastSysHeatInfoTime
unsigned int KODI::GUILIB::GUIINFO::CSystemGUIInfo::m_lastSysHeatInfoTime mutable private
Referenced by GetSystemHeatInfo().
SYSTEM_HEAT_UPDATE_INTERVAL
const int KODI::GUILIB::GUIINFO::CSystemGUIInfo::SYSTEM_HEAT_UPDATE_INTERVAL = 60000 static private
Referenced by GetSystemHeatInfo().
The documentation for this class was generated from the following files:
SystemGUIInfo.h
SystemGUIInfo.cpp