Kodi Documentation: TestAddonInfoBuilder.cpp File Reference
TestAddonInfoBuilder.cpp File Reference
#include "addons/Repository.h"
#include "addons/addoninfo/AddonInfo.h"
#include "addons/addoninfo/AddonInfoBuilder.h"
#include "addons/addoninfo/AddonType.h"
#include "utils/XBMCTinyXML2.h"
#include <set>
#include <gtest/gtest.h>
Classes
class TestAddonInfoBuilder
Functions
TEST_F (TestAddonInfoBuilder, ShouldFailWhenIdIsNotSet)
TEST_F (TestAddonInfoBuilder, TestGenerate_Id_Type)
TEST_F (TestAddonInfoBuilder, TestGenerate_Repo)
TEST_F (TestAddonInfoBuilder, TestGenerate_DBEntry)
Variables
const std::string addonXML
Function Documentation
TEST_F() [1/4]
TEST_F (TestAddonInfoBuilder , ShouldFailWhenIdIsNotSet)
References EXPECT_EQ(), and ADDON::CAddonInfoBuilder::Generate().
TEST_F() [2/4]
TEST_F (TestAddonInfoBuilder , TestGenerate_DBEntry)
References ASSERT_NE(), EXPECT_EQ(), EXPECT_TRUE(), ADDON::CAddonInfoBuilderFromDB::get(), ADDON::CAddonExtensions::Insert(), ADDON::CAddonInfoBuilderFromDB::SetAuthor(), ADDON::CAddonInfoBuilderFromDB::SetDescription(), ADDON::CAddonInfoBuilderFromDB::SetDisclaimer(), ADDON::CAddonInfoBuilderFromDB::SetEMail(), ADDON::CAddonInfoBuilderFromDB::SetExtensions(), ADDON::CAddonInfoBuilderFromDB::SetExtrainfo(), ADDON::CAddonInfoBuilderFromDB::SetForum(), ADDON::CAddonInfoBuilderFromDB::SetId(), ADDON::CAddonInfoBuilderFromDB::SetLicense(), ADDON::CAddonInfoBuilderFromDB::SetName(), ADDON::CAddonInfoBuilderFromDB::SetSource(), ADDON::CAddonInfoBuilderFromDB::SetSummary(), ADDON::CAddonInfoBuilderFromDB::SetVersion(), and ADDON::CAddonInfoBuilderFromDB::SetWebsite().
TEST_F() [3/4]
TEST_F (TestAddonInfoBuilder , TestGenerate_Id_Type)
References EXPECT_EQ(), EXPECT_NE(), EXPECT_TRUE(), and ADDON::CAddonInfoBuilder::Generate().
TEST_F() [4/4]
TEST_F (TestAddonInfoBuilder , TestGenerate_Repo)
References addonXML, ASSERT_NE(), EXPECT_EQ(), EXPECT_TRUE(), ADDON::CAddonInfoBuilder::Generate(), and CXBMCTinyXML2::Parse().
Variable Documentation
addonXML
const std::string addonXML
Initial value:
= R"xml(
<addon id="metadata.blablabla.org"
       name="The Bla Bla Bla Addon"
       version="1.2.3"
       provider-name="Team Kodi">
  <requires>
    <import addon="xbmc.metadata" version="2.1.0"/>
    <import addon="metadata.common.imdb.com" minversion="2.9.2" version="2.9.2"/>
    <import addon="metadata.common.themoviedb.org" minversion="3.1.0" version="3.1.0"/>
    <import addon="plugin.video.youtube" minversion="4.4.0" version="4.4.10" optional="true"/>
  </requires>
  <extension point="xbmc.metadata.scraper.movies"
             language="en"
             library="blablabla.xml"/>
  <extension point="xbmc.python.module"
             library="lib.so"/>
  <extension point="kodi.addon.metadata">
    <summary lang="en">Summary bla bla bla</summary>
    <description lang="en">Description bla bla bla</description>
    <disclaimer lang="en">Disclaimer bla bla bla</disclaimer>
    <platform>all</platform>
    <language>marsian</language>
    <license>GPL v2.0</license>
    <forum>https://forum.kodi.tv</forum>
    <website>https://kodi.tv</website>
    <email>a@a.dummy</email>
    <source>https://github.com/xbmc/xbmc</source>
  </extension>
</addon>
)xml"
Referenced by TEST_F().