Kodi Documentation: KODI::JOYSTICK::CJoystickTranslator Class Reference
KODI::JOYSTICK::CJoystickTranslator Class Reference
Input » Joystick
Joystick translation utilities.
#include <JoystickTranslator.h>
Static Public Member Functions
static const char * HatStateToString (HAT_STATE state)
Translate a hat state to a string representation.
static const char * TranslateAnalogStickDirection (ANALOG_STICK_DIRECTION dir)
Translate an analog stick direction to a lower-case string.
static ANALOG_STICK_DIRECTION TranslateAnalogStickDirection (const std::string &dir)
Translate an analog stick direction string to an enum value.
static const char * TranslateWheelDirection (WHEEL_DIRECTION dir)
Translate a wheel direction to a lower-case string.
static WHEEL_DIRECTION TranslateWheelDirection (const std::string &dir)
Translate a wheel direction string to an enum value.
static const char * TranslateThrottleDirection (THROTTLE_DIRECTION dir)
Translate a throttle direction to a lower-case string.
static THROTTLE_DIRECTION TranslateThrottleDirection (const std::string &dir)
Translate a throttle direction string to an enum value.
static SEMIAXIS_DIRECTION PositionToSemiAxisDirection (float position)
Get the semi-axis direction containing the specified position.
static WHEEL_DIRECTION PositionToWheelDirection (float position)
Get the wheel direction containing the specified position.
static THROTTLE_DIRECTION PositionToThrottleDirection (float position)
Get the throttle direction containing the specified position.
static std::string GetPrimitiveName (const CDriverPrimitive &primitive)
Get the localized name of the primitive.
Detailed Description
Joystick translation utilities.
Member Function Documentation
GetPrimitiveName()
std::string CJoystickTranslator::GetPrimitiveName (const CDriverPrimitive & primitive) static
Get the localized name of the primitive.
Parameters
primitive The primitive, currently only buttons and axes are supported
Returns
A title for the primitive, e.g. "Button 0" or "Axis 1"
References KODI::JOYSTICK::BUTTON, g_localizeStrings, CLocalizeStrings::Get(), KODI::JOYSTICK::CDriverPrimitive::Index(), KODI::JOYSTICK::SEMIAXIS, and KODI::JOYSTICK::CDriverPrimitive::Type().
Referenced by KODI::GAME::CGUIDialogAxisDetection::GetDialogText().
HatStateToString()
const char * CJoystickTranslator::HatStateToString (HAT_STATE state) static
Translate a hat state to a string representation.
Parameters
state The hat state
Returns
A capitalized string representation, or "RELEASED" if the hat is centered.
Referenced by PERIPHERALS::CPeripheralJoystick::OnHatMotion().
PositionToSemiAxisDirection()
SEMIAXIS_DIRECTION CJoystickTranslator::PositionToSemiAxisDirection (float position) static
Get the semi-axis direction containing the specified position.
Parameters
position The position of the axis
Returns
POSITIVE, NEGATIVE, or UNKNOWN if position is 0
References KODI::JOYSTICK::NEGATIVE, KODI::JOYSTICK::POSITIVE, and KODI::JOYSTICK::ZERO.
Referenced by KODI::JOYSTICK::CAxisDetector::OnMotion().
PositionToThrottleDirection()
THROTTLE_DIRECTION CJoystickTranslator::PositionToThrottleDirection (float position) static
Get the throttle direction containing the specified position.
Parameters
position The position of the axis
Returns
UP, DOWN, or UNKNOWN if position is 0
References KODI::JOYSTICK::DOWN, KODI::JOYSTICK::NONE, and KODI::JOYSTICK::UP.
Referenced by KODI::KEYMAP::CKeymapHandler::OnThrottleMotion().
PositionToWheelDirection()
WHEEL_DIRECTION CJoystickTranslator::PositionToWheelDirection (float position) static
Get the wheel direction containing the specified position.
Parameters
position The position of the axis
Returns
LEFT, RIGHT, or UNKNOWN if position is 0
References KODI::JOYSTICK::LEFT, KODI::JOYSTICK::NONE, and KODI::JOYSTICK::RIGHT.
Referenced by KODI::KEYMAP::CKeymapHandler::OnWheelMotion().
TranslateAnalogStickDirection() [1/2]
const char * CJoystickTranslator::TranslateAnalogStickDirection (ANALOG_STICK_DIRECTION dir) static
Translate an analog stick direction to a lower-case string.
Parameters
dir The analog stick direction
Returns
A lower-case string representation, or "" if the direction is invalid
Referenced by KODI::KEYMAP::CJoystickMapper::DeserializeButton(), and KODI::JOYSTICK::CJoystickUtils::MakeKeyName().
TranslateAnalogStickDirection() [2/2]
ANALOG_STICK_DIRECTION CJoystickTranslator::TranslateAnalogStickDirection (const std::string & dir) static
Translate an analog stick direction string to an enum value.
Parameters
dir The analog stick direction
Returns
The translated direction, or ANALOG_STICK_DIRECTION::UNKNOWN if unknown
TranslateThrottleDirection() [1/2]
THROTTLE_DIRECTION CJoystickTranslator::TranslateThrottleDirection (const std::string & dir) static
Translate a throttle direction string to an enum value.
Parameters
dir The throttle direction
Returns
The translated direction, or THROTTLE_DIRECTION::UNKNOWN if unknown
References KODI::JOYSTICK::DOWN, KODI::JOYSTICK::NONE, and KODI::JOYSTICK::UP.
TranslateThrottleDirection() [2/2]
const char * CJoystickTranslator::TranslateThrottleDirection (THROTTLE_DIRECTION dir) static
Translate a throttle direction to a lower-case string.
Parameters
dir The analog stick direction
Returns
A lower-case string representation, or "" if the direction is invalid
References KODI::JOYSTICK::DOWN, and KODI::JOYSTICK::UP.
TranslateWheelDirection() [1/2]
WHEEL_DIRECTION CJoystickTranslator::TranslateWheelDirection (const std::string & dir) static
Translate a wheel direction string to an enum value.
Parameters
dir The wheel direction
Returns
The translated direction, or WHEEL_DIRECTION::UNKNOWN if unknown
References KODI::JOYSTICK::LEFT, KODI::JOYSTICK::NONE, and KODI::JOYSTICK::RIGHT.
TranslateWheelDirection() [2/2]
const char * CJoystickTranslator::TranslateWheelDirection (WHEEL_DIRECTION dir) static
Translate a wheel direction to a lower-case string.
Parameters
dir The wheel direction
Returns
A lower-case string representation, or "" if the direction is invalid
References KODI::JOYSTICK::LEFT, and KODI::JOYSTICK::RIGHT.
The documentation for this class was generated from the following files:
JoystickTranslator.h
JoystickTranslator.cpp