Kodi Documentation: ILanguageInvocationHandler Class Reference
ILanguageInvocationHandler Class Reference abstract
#include <ILanguageInvocationHandler.h>
Public Member Functions
ILanguageInvocationHandler ()=default
virtual ~ILanguageInvocationHandler ()=default
virtual bool Initialize ()
virtual void Process ()
virtual void PulseGlobalEvent ()
virtual void Uninitialize ()
virtual bool OnScriptInitialized (ILanguageInvoker *invoker)
virtual void OnScriptStarted (ILanguageInvoker *invoker)
virtual void NotifyScriptAborting (ILanguageInvoker *invoker)
virtual void OnExecutionEnded (ILanguageInvoker *invoker)
virtual void OnScriptFinalized (ILanguageInvoker *invoker)
virtual ILanguageInvoker * CreateInvoker ()=0
Constructor & Destructor Documentation
ILanguageInvocationHandler()
ILanguageInvocationHandler::ILanguageInvocationHandler () default
~ILanguageInvocationHandler()
virtual ILanguageInvocationHandler::~ILanguageInvocationHandler () virtual default
Member Function Documentation
CreateInvoker()
virtual ILanguageInvoker * ILanguageInvocationHandler::CreateInvoker () pure virtual
Implemented in XBPython.
Initialize()
virtual bool ILanguageInvocationHandler::Initialize () inline virtual
Referenced by CScriptInvocationManager::RegisterLanguageInvocationHandler().
NotifyScriptAborting()
virtual void ILanguageInvocationHandler::NotifyScriptAborting (ILanguageInvoker * invoker) inline virtual
Reimplemented in XBPython.
Referenced by ILanguageInvoker::AbortNotification().
OnExecutionEnded()
virtual void ILanguageInvocationHandler::OnExecutionEnded (ILanguageInvoker * invoker) inline virtual
Reimplemented in XBPython.
Referenced by ILanguageInvoker::onExecutionDone(), and ILanguageInvoker::onExecutionFailed().
OnScriptFinalized()
virtual void ILanguageInvocationHandler::OnScriptFinalized (ILanguageInvoker * invoker) inline virtual
Reimplemented in XBPython.
Referenced by ILanguageInvoker::onExecutionFinalized().
OnScriptInitialized()
virtual bool ILanguageInvocationHandler::OnScriptInitialized (ILanguageInvoker * invoker) inline virtual
Reimplemented in XBPython.
Referenced by ILanguageInvoker::onExecutionInitialized().
OnScriptStarted()
virtual void ILanguageInvocationHandler::OnScriptStarted (ILanguageInvoker * invoker) inline virtual
Reimplemented in XBPython.
Referenced by ILanguageInvoker::Execute().
Process()
virtual void ILanguageInvocationHandler::Process () inline virtual
Reimplemented in XBPython.
PulseGlobalEvent()
virtual void ILanguageInvocationHandler::PulseGlobalEvent () inline virtual
Reimplemented in XBPython.
Referenced by ILanguageInvoker::pulseGlobalEvent().
Uninitialize()
virtual void ILanguageInvocationHandler::Uninitialize () inline virtual
Reimplemented in XBPython.
Referenced by CScriptInvocationManager::UnregisterLanguageInvocationHandler().
The documentation for this class was generated from the following file:
ILanguageInvocationHandler.h