Kodi Documentation: TestFile.cpp File Reference
TestFile.cpp File Reference
#include "filesystem/File.h"
#include "test/TestUtils.h"
#include <errno.h>
#include <string>
#include <gtest/gtest.h>
Functions
TEST (TestFile, Read)
TEST (TestFile, Write)
TEST (TestFile, Exists)
TEST (TestFile, Stat)
TEST (TestFile, Delete)
TEST (TestFile, Rename)
TEST (TestFile, Copy)
TEST (TestFile, SetHidden)
Function Documentation
TEST() [1/8]
TEST (TestFile , Copy)
References ASSERT_NE(), XFILE::CFile::Close(), XFILE::CFile::Copy(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), EXPECT_TRUE(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [2/8]
TEST (TestFile , Delete)
References ASSERT_NE(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), EXPECT_TRUE(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [3/8]
TEST (TestFile , Exists)
References ASSERT_NE(), XFILE::CFile::Exists(), EXPECT_TRUE(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [4/8]
TEST (TestFile , Read)
References EXPECT_EQ(), CXBMCTestUtils::getNewLineCharacters(), CXBMCTestUtils::Instance(), int64_t(), and XBMC_REF_FILE_PATH.
TEST() [5/8]
TEST (TestFile , Rename)
References ASSERT_NE(), XFILE::CFile::Close(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), EXPECT_TRUE(), XFILE::CFile::Rename(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [6/8]
TEST (TestFile , SetHidden)
References ASSERT_NE(), XFILE::CFile::Exists(), EXPECT_TRUE(), XFILE::CFile::SetHidden(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [7/8]
TEST (TestFile , Stat)
References __stat64, _S_IFREG, ASSERT_NE(), EXPECT_EQ(), EXPECT_NE(), EXPECT_TRUE(), XFILE::CFile::Stat(), XBMC_CREATETEMPFILE, and XBMC_DELETETEMPFILE.
TEST() [8/8]
TEST (TestFile , Write)
References ASSERT_NE(), EXPECT_EQ(), EXPECT_TRUE(), int64_t(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.