Kodi Documentation: KODI::JOYSTICK::CAxisFeature Class Reference
KODI::JOYSTICK::CAxisFeature Class Reference
Input » Joystick
#include <FeatureHandling.h>
Public Member Functions
CAxisFeature (const FeatureName &name, IInputHandler *handler, IButtonMap *buttonMap)
~CAxisFeature () override=default
bool OnDigitalMotion (const CDriverPrimitive &source, bool bPressed) override
A digital motion has occurred.
void ProcessMotions () override
Process the motions that have occurred since the last invocation.
Public Member Functions inherited from KODI::JOYSTICK::CJoystickFeature
CJoystickFeature (const FeatureName &name, IInputHandler *handler, IButtonMap *buttonMap)
virtual ~CJoystickFeature ()=default
virtual bool OnAnalogMotion (const CDriverPrimitive &source, float magnitude)=0
An analog motion has occurred.
bool AcceptsInput (bool bActivation)
Check if the input handler is accepting input.
Protected Attributes
CFeatureAxis m_axis
float m_state = 0.0f
Protected Attributes inherited from KODI::JOYSTICK::CJoystickFeature
const FeatureName m_name
IInputHandler *const m_handler
IButtonMap *const m_buttonMap
const bool m_bEnabled
Additional Inherited Members
Protected Member Functions inherited from KODI::JOYSTICK::CJoystickFeature
void ResetMotion ()
Reset motion timer.
void StartMotion ()
Start the motion timer.
bool InMotion () const
Check if the feature is in motion.
unsigned int MotionTimeMs () const
Get the time for which the feature has been in motion.
Constructor & Destructor Documentation
CAxisFeature()
CAxisFeature::CAxisFeature (const FeatureName & name, IInputHandler * handler, IButtonMap * buttonMap)
~CAxisFeature()
KODI::JOYSTICK::CAxisFeature::~CAxisFeature () override default
Member Function Documentation
OnDigitalMotion()
bool CAxisFeature::OnDigitalMotion (const CDriverPrimitive & source, bool bPressed) override virtual
A digital motion has occurred.
Parameters
source The source of the motion. Must be digital (button or hat)
bPressed True for press motion, false for release motion
Returns
true if the motion was handled, false otherwise
Implements KODI::JOYSTICK::CJoystickFeature.
References KODI::JOYSTICK::CJoystickFeature::OnAnalogMotion().
ProcessMotions()
void CAxisFeature::ProcessMotions () override virtual
Process the motions that have occurred since the last invocation.
This allows features with motion on multiple driver primitives to call their handler once all driver primitives are accounted for.
Implements KODI::JOYSTICK::CJoystickFeature.
References KODI::JOYSTICK::CJoystickFeature::AcceptsInput(), KODI::JOYSTICK::IInputHandler::ControllerID(), KODI::JOYSTICK::IButtonMap::GetFeatureType(), KODI::JOYSTICK::CFeatureAxis::GetPosition(), KODI::JOYSTICK::CJoystickFeature::InMotion(), CLog::Log(), LOGDEBUG, m_axis, KODI::JOYSTICK::CJoystickFeature::m_buttonMap, KODI::JOYSTICK::CJoystickFeature::m_handler, KODI::JOYSTICK::CJoystickFeature::m_name, m_state, KODI::JOYSTICK::CJoystickFeature::MotionTimeMs(), KODI::JOYSTICK::IInputHandler::OnThrottleMotion(), KODI::JOYSTICK::IInputHandler::OnWheelMotion(), KODI::JOYSTICK::CJoystickFeature::ResetMotion(), KODI::JOYSTICK::CJoystickFeature::StartMotion(), KODI::JOYSTICK::THROTTLE, and KODI::JOYSTICK::WHEEL.
Member Data Documentation
m_axis
CFeatureAxis KODI::JOYSTICK::CAxisFeature::m_axis protected
Referenced by KODI::JOYSTICK::CWheel::OnAnalogMotion(), KODI::JOYSTICK::CThrottle::OnAnalogMotion(), and ProcessMotions().
m_state
float KODI::JOYSTICK::CAxisFeature::m_state = 0.0f protected
Referenced by ProcessMotions().
The documentation for this class was generated from the following files:
FeatureHandling.h
FeatureHandling.cpp