Kodi Documentation: XFILE::MUSICDATABASEDIRECTORY::CQueryParams Class Reference
XFILE::MUSICDATABASEDIRECTORY::CQueryParams Class Reference
#include <QueryParams.h>
Public Member Functions
CQueryParams ()
int GetArtistId ()
int GetAlbumId ()
int GetGenreId ()
int GetSongId ()
int GetYear ()
int GetDisc ()
Protected Member Functions
void SetQueryParam (NODE_TYPE NodeType, const std::string &strNodeName)
Private Attributes
int m_idArtist
int m_idAlbum
int m_idGenre
int m_idSong
int m_year
int m_disc
Friends
class CDirectoryNode
Constructor & Destructor Documentation
CQueryParams()
CQueryParams::CQueryParams ()
References m_disc, m_idAlbum, m_idArtist, m_idGenre, m_idSong, and m_year.
Member Function Documentation
GetAlbumId()
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetAlbumId () inline
References m_idAlbum.
Referenced by UPNP::CUPnPServer::Build(), MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSong::GetContent(), XFILE::CMusicDatabaseDirectory::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetLabel(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetLocalizedName(), CGUIWindowMusicNav::ManageInfoProvider(), CMusicDbUrl::parse(), MUSIC_INFO::CMusicInfoScanner::Process(), and CGUIDialogMusicInfo::ShowFor().
GetArtistId()
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetArtistId () inline
References m_idArtist.
Referenced by UPNP::CUPnPServer::Build(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSong::GetContent(), CGUIWindowMusicBase::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetLabel(), CGUIWindowMusicNav::ManageInfoProvider(), CMusicDbUrl::parse(), MUSIC_INFO::CMusicInfoScanner::Process(), and CGUIDialogMusicInfo::ShowFor().
GetDisc()
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetDisc () inline
References m_disc.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetLocalizedName().
GetGenreId()
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetGenreId () inline
References m_idGenre.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSong::GetContent(), XFILE::CMusicDatabaseDirectory::GetLabel(), and CMusicDbUrl::parse().
GetSongId()
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetSongId () inline
References m_idSong.
Referenced by UPNP::CUPnPServer::Build(), MUSIC_INFO::CMusicInfoTagLoaderDatabase::Load(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), and CMusicDbUrl::parse().
GetYear()
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetYear () inline
References m_year.
Referenced by CMusicDbUrl::parse().
SetQueryParam()
void CQueryParams::SetQueryParam (NODE_TYPE NodeType, const std::string & strNodeName) protected
References m_disc, m_idAlbum, m_idArtist, m_idGenre, m_idSong, m_year, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ARTIST, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_DISC, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG_TOP100, and XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_YEAR.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::CollectQueryParams().
Friends And Related Symbol Documentation
CDirectoryNode
friend class CDirectoryNode friend
Member Data Documentation
m_disc
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::m_disc private
Referenced by CQueryParams(), GetDisc(), and SetQueryParam().
m_idAlbum
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::m_idAlbum private
Referenced by CQueryParams(), GetAlbumId(), and SetQueryParam().
m_idArtist
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::m_idArtist private
Referenced by CQueryParams(), GetArtistId(), and SetQueryParam().
m_idGenre
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::m_idGenre private
Referenced by CQueryParams(), GetGenreId(), and SetQueryParam().
m_idSong
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::m_idSong private
Referenced by CQueryParams(), GetSongId(), and SetQueryParam().
m_year
int XFILE::MUSICDATABASEDIRECTORY::CQueryParams::m_year private
Referenced by CQueryParams(), GetYear(), and SetQueryParam().
The documentation for this class was generated from the following files:
MusicDatabaseDirectory/QueryParams.h
MusicDatabaseDirectory/QueryParams.cpp