Kodi Documentation: CD3DEffect Class Reference
CD3DEffect Class Reference
#include <D3DResource.h>
Public Member Functions
CD3DEffect ()
virtual ~CD3DEffect ()
bool Create (const std::string &effectString, DefinesMap *defines)
void Release ()
bool SetFloatArray (LPCSTR handle, const float *val, unsigned int count)
bool SetMatrix (LPCSTR handle, const float *mat)
bool SetTechnique (LPCSTR handle)
bool SetTexture (LPCSTR handle, CD3DTexture &texture)
bool SetResources (LPCSTR handle, ID3D11ShaderResourceView **ppSRViews, size_t count)
bool SetConstantBuffer (LPCSTR handle, ID3D11Buffer *buffer)
bool SetScalar (LPCSTR handle, float value)
bool Begin (UINT *passes, DWORD flags)
bool BeginPass (UINT pass)
bool EndPass ()
bool End ()
ID3DX11Effect * Get () const
void OnDestroyDevice (bool fatal) override
void OnCreateDevice () override
__declspec (nothrow) HRESULT __stdcall Open(D3D_INCLUDE_TYPE IncludeType
__declspec (nothrow) HRESULT __stdcall Close(LPCVOID pData) override
Public Member Functions inherited from ID3DResource
virtual ~ID3DResource ()
Public Attributes
LPCSTR pFileName
LPCSTR LPCVOID pParentData
LPCSTR LPCVOID LPCVOID * ppData
LPCSTR LPCVOID LPCVOID UINT *pBytes override
Private Member Functions
bool CreateEffect ()
Private Attributes
std::string m_effectString
DefinesMap m_defines
Microsoft::WRL::ComPtr< ID3DX11Effect > m_effect
Microsoft::WRL::ComPtr< ID3DX11EffectTechnique > m_techniquie
Microsoft::WRL::ComPtr< ID3DX11EffectPass > m_currentPass
Additional Inherited Members
Protected Member Functions inherited from ID3DResource
void Register ()
void Unregister ()
Protected Attributes inherited from ID3DResource
bool m_bRegistered = false
Constructor & Destructor Documentation
CD3DEffect()
CD3DEffect::CD3DEffect ()
References m_currentPass, m_effect, and m_techniquie.
~CD3DEffect()
CD3DEffect::~CD3DEffect () virtual
References Release().
Member Function Documentation
__declspec() [1/2]
CD3DEffect::__declspec (nothrow) override
__declspec() [2/2]
CD3DEffect::__declspec (nothrow)
Begin()
bool CD3DEffect::Begin (UINT * passes, DWORD flags)
References m_effect, and m_techniquie.
Referenced by CWinShader::Execute().
BeginPass()
bool CD3DEffect::BeginPass (UINT pass)
References DX::DeviceResources::Get(), m_currentPass, m_effect, and m_techniquie.
Referenced by CWinShader::Execute().
Create()
bool CD3DEffect::Create (const std::string & effectString, DefinesMap * defines)
References CreateEffect(), m_defines, m_effectString, ID3DResource::Register(), and Release().
Referenced by CTestShader::Create(), and CWinShader::LoadEffect().
CreateEffect()
bool CD3DEffect::CreateEffect () private
References DX::DeviceResources::Get(), CLog::Log(), LOGERROR, m_defines, m_effect, and m_effectString.
Referenced by Create(), and OnCreateDevice().
End()
bool CD3DEffect::End ()
References m_effect, and m_techniquie.
Referenced by CWinShader::Execute().
EndPass()
bool CD3DEffect::EndPass ()
References m_currentPass, and m_effect.
Referenced by CWinShader::Execute().
Get()
ID3DX11Effect * CD3DEffect::Get () const inline
References m_effect.
Referenced by CWinShader::CreateInputLayout().
OnCreateDevice()
void CD3DEffect::OnCreateDevice (void) override virtual
Implements ID3DResource.
References CreateEffect().
OnDestroyDevice()
void CD3DEffect::OnDestroyDevice (bool fatal) override virtual
Implements ID3DResource.
References m_currentPass, m_effect, and m_techniquie.
Referenced by Release().
Release()
void CD3DEffect::Release ()
References OnDestroyDevice(), and ID3DResource::Unregister().
Referenced by Create(), and ~CD3DEffect().
SetConstantBuffer()
bool CD3DEffect::SetConstantBuffer (LPCSTR handle, ID3D11Buffer * buffer)
References m_effect.
SetFloatArray()
bool CD3DEffect::SetFloatArray (LPCSTR handle, const float * val, unsigned int count)
References m_effect.
Referenced by COutputShader::ApplyEffectParameters(), CConvolutionShader1Pass::SetShaderParameters(), CConvolutionShaderSeparable::SetShaderParameters(), KODI::RETRO::CRPWinOutputShader::SetShaderParameters(), COutputShader::SetShaderParameters(), CYUV2RGBShader::SetShaderParameters(), and CConvolutionShaderSeparable::SetStepParams().
SetMatrix()
bool CD3DEffect::SetMatrix (LPCSTR handle, const float * mat)
References m_effect.
Referenced by CYUV2RGBShader::SetShaderParameters().
SetResources()
bool CD3DEffect::SetResources (LPCSTR handle, ID3D11ShaderResourceView ** ppSRViews, size_t count)
References m_effect.
Referenced by COutputShader::ApplyEffectParameters(), KODI::RETRO::CRPWinOutputShader::SetShaderParameters(), COutputShader::SetShaderParameters(), and CYUV2RGBShader::SetShaderParameters().
SetScalar()
bool CD3DEffect::SetScalar (LPCSTR handle, float value)
References m_effect, and value.
Referenced by COutputShader::ApplyEffectParameters(), and CYUV2RGBShader::SetShaderParameters().
SetTechnique()
bool CD3DEffect::SetTechnique (LPCSTR handle)
References m_effect, and m_techniquie.
Referenced by CConvolutionShader1Pass::SetShaderParameters(), CConvolutionShaderSeparable::SetShaderParameters(), KODI::RETRO::CRPWinOutputShader::SetShaderParameters(), COutputShader::SetShaderParameters(), and CYUV2RGBShader::SetShaderParameters().
SetTexture()
bool CD3DEffect::SetTexture (LPCSTR handle, CD3DTexture & texture)
References CD3DTexture::GetShaderResource(), and m_effect.
Referenced by CConvolutionShader1Pass::SetShaderParameters(), CConvolutionShaderSeparable::SetShaderParameters(), and CConvolutionShaderSeparable::SetStepParams().
Member Data Documentation
m_currentPass
Microsoft::WRL::ComPtr<ID3DX11EffectPass> CD3DEffect::m_currentPass private
Referenced by BeginPass(), CD3DEffect(), EndPass(), and OnDestroyDevice().
m_defines
DefinesMap CD3DEffect::m_defines private
Referenced by Create(), and CreateEffect().
m_effect
Microsoft::WRL::ComPtr<ID3DX11Effect> CD3DEffect::m_effect private
Referenced by Begin(), BeginPass(), CD3DEffect(), CreateEffect(), End(), EndPass(), Get(), OnDestroyDevice(), SetConstantBuffer(), SetFloatArray(), SetMatrix(), SetResources(), SetScalar(), SetTechnique(), and SetTexture().
m_effectString
std::string CD3DEffect::m_effectString private
Referenced by Create(), and CreateEffect().
m_techniquie
Microsoft::WRL::ComPtr<ID3DX11EffectTechnique> CD3DEffect::m_techniquie private
Referenced by Begin(), BeginPass(), CD3DEffect(), End(), OnDestroyDevice(), and SetTechnique().
override
LPCSTR LPCVOID LPCVOID UINT* pBytes CD3DEffect::override
pFileName
LPCSTR CD3DEffect::pFileName
pParentData
LPCSTR LPCVOID CD3DEffect::pParentData
ppData
LPCSTR LPCVOID LPCVOID* CD3DEffect::ppData
The documentation for this class was generated from the following files:
D3DResource.h
D3DResource.cpp