Kodi Documentation: CSetUserratingJob Class Reference
CSetUserratingJob Class Reference
Public Member Functions
CSetUserratingJob (int albumId, int userrating)
~CSetUserratingJob (void) override=default
bool DoWork (void) override
Main workhorse function of CJob instances.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual const char * GetType () const
Function that returns the type of job.
virtual bool operator== (const CJob *job) const
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Private Attributes
int idAlbum
int iUserrating
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Constructor & Destructor Documentation
CSetUserratingJob()
CSetUserratingJob::CSetUserratingJob (int albumId, int userrating) inline
~CSetUserratingJob()
CSetUserratingJob::~CSetUserratingJob (void) override default
Member Function Documentation
DoWork()
bool CSetUserratingJob::DoWork (void) inline override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CDatabase::Close(), idAlbum, iUserrating, CMusicDatabase::Open(), and CMusicDatabase::SetAlbumUserrating().
Member Data Documentation
idAlbum
int CSetUserratingJob::idAlbum private
Referenced by DoWork().
iUserrating
int CSetUserratingJob::iUserrating private
Referenced by DoWork().
The documentation for this class was generated from the following file:
GUIDialogMusicInfo.cpp