Kodi Documentation: PVR::CPVRThumbLoader Class Reference
PVR::CPVRThumbLoader Class Reference
#include <PVRThumbLoader.h>
Public Member Functions
CPVRThumbLoader ()=default
~CPVRThumbLoader () override=default
bool LoadItem (CFileItem *item) override
bool LoadItemCached (CFileItem *item) override
bool LoadItemLookup (CFileItem *item) override
void ClearCachedImage (CFileItem &item)
void ClearCachedImages (const CFileItemList &items)
Public Member Functions inherited from CThumbLoader
CThumbLoader ()
~CThumbLoader () override
void OnLoaderStart () override
void OnLoaderFinish () override
virtual bool FillLibraryArt (CFileItem &item)
helper function to fill the art for a library item
virtual std::string GetCachedImage (const CFileItem &item, const std::string &type)
Checks whether the given item has an image listed in the texture database.
virtual void SetCachedImage (const CFileItem &item, const std::string &type, const std::string &image)
Associate an image with the given item in the texture database.
Public Member Functions inherited from CBackgroundInfoLoader
CBackgroundInfoLoader ()
~CBackgroundInfoLoader () override
void Load (CFileItemList &items)
bool IsLoading ()
void Run () override
void SetObserver (IBackgroundLoaderObserver *pObserver)
void SetProgressCallback (IProgressCallback *pCallback)
void StopThread ()
void StopAsync ()
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Protected Member Functions
void OnLoaderFinish () override
Private Member Functions
bool FillThumb (CFileItem &item)
std::string CreateChannelGroupThumb (const CFileItem &channelGroupItem)
Private Attributes
bool m_bInvalidated = false
Additional Inherited Members
Protected Attributes inherited from CThumbLoader
CTextureDatabase * m_textureDatabase
Protected Attributes inherited from CBackgroundInfoLoader
CFileItemList * m_pVecItems {nullptr}
std::vector< CFileItemPtr > m_vecItems
CCriticalSection m_lock
volatile bool m_bIsLoading {false}
volatile bool m_bStop {true}
CThread * m_thread {nullptr}
IBackgroundLoaderObserver * m_pObserver {nullptr}
IProgressCallback * m_pProgressCallback {nullptr}
Constructor & Destructor Documentation
CPVRThumbLoader()
PVR::CPVRThumbLoader::CPVRThumbLoader () default
~CPVRThumbLoader()
PVR::CPVRThumbLoader::~CPVRThumbLoader () override default
Member Function Documentation
ClearCachedImage()
void PVR::CPVRThumbLoader::ClearCachedImage (CFileItem & item)
References CTextureDatabase::ClearTextureForPath(), CDatabase::Close(), CGUIListItem::GetArt(), CFileItem::GetPath(), CServiceBroker::GetTextureCache(), m_bInvalidated, CThumbLoader::m_textureDatabase, CTextureDatabase::Open(), and CGUIListItem::SetArt().
Referenced by ClearCachedImages(), and PVR::CGUIDialogPVRGroupManager::ClearGroupThumbnails().
ClearCachedImages()
void PVR::CPVRThumbLoader::ClearCachedImages (const CFileItemList & items)
References ClearCachedImage().
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonRecreateThumbnail().
CreateChannelGroupThumb()
std::string PVR::CPVRThumbLoader::CreateChannelGroupThumb (const CFileItem & channelGroupItem) private
References CFileItem::GetPath(), and IMAGE_FILES::URLFromFile().
Referenced by FillThumb().
FillThumb()
bool PVR::CPVRThumbLoader::FillThumb (CFileItem & item) private
References CreateChannelGroupThumb(), CThumbLoader::GetCachedImage(), CFileItem::GetPath(), CFileItem::IsPVRChannelGroup(), LOGERROR, m_bInvalidated, CGUIListItem::SetArt(), and CThumbLoader::SetCachedImage().
Referenced by LoadItemCached().
LoadItem()
bool PVR::CPVRThumbLoader::LoadItem (CFileItem * item) override virtual
Reimplemented from CBackgroundInfoLoader.
References LoadItemCached(), and LoadItemLookup().
Referenced by PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog().
LoadItemCached()
bool PVR::CPVRThumbLoader::LoadItemCached (CFileItem * item) override virtual
Reimplemented from CBackgroundInfoLoader.
References FillThumb().
Referenced by LoadItem().
LoadItemLookup()
bool PVR::CPVRThumbLoader::LoadItemLookup (CFileItem * item) override virtual
Reimplemented from CBackgroundInfoLoader.
Referenced by LoadItem().
OnLoaderFinish()
void PVR::CPVRThumbLoader::OnLoaderFinish () override protected virtual
Reimplemented from CBackgroundInfoLoader.
References PVR::ChannelGroupsInvalidated, CServiceBroker::GetPVRManager(), m_bInvalidated, CThumbLoader::OnLoaderFinish(), and PVR::CPVRManager::PublishEvent().
Member Data Documentation
m_bInvalidated
bool PVR::CPVRThumbLoader::m_bInvalidated = false private
Referenced by ClearCachedImage(), FillThumb(), and OnLoaderFinish().
The documentation for this class was generated from the following files:
PVRThumbLoader.h
PVRThumbLoader.cpp