var dir_177569a4416a5982621c50f2599d1324 =
[
    [ "GUIDialogPVRChannelGuide.cpp", "df/dc5/_g_u_i_dialog_p_v_r_channel_guide_8cpp.html", null ],
    [ "GUIDialogPVRChannelGuide.h", "d8/db9/_g_u_i_dialog_p_v_r_channel_guide_8h.html", "d8/db9/_g_u_i_dialog_p_v_r_channel_guide_8h" ],
    [ "GUIDialogPVRChannelManager.cpp", "de/d2e/_g_u_i_dialog_p_v_r_channel_manager_8cpp.html", "de/d2e/_g_u_i_dialog_p_v_r_channel_manager_8cpp" ],
    [ "GUIDialogPVRChannelManager.h", "dc/d9b/_g_u_i_dialog_p_v_r_channel_manager_8h.html", "dc/d9b/_g_u_i_dialog_p_v_r_channel_manager_8h" ],
    [ "GUIDialogPVRChannelsOSD.cpp", "d2/da6/_g_u_i_dialog_p_v_r_channels_o_s_d_8cpp.html", "d2/da6/_g_u_i_dialog_p_v_r_channels_o_s_d_8cpp" ],
    [ "GUIDialogPVRChannelsOSD.h", "db/d94/_g_u_i_dialog_p_v_r_channels_o_s_d_8h.html", "db/d94/_g_u_i_dialog_p_v_r_channels_o_s_d_8h" ],
    [ "GUIDialogPVRClientPriorities.cpp", "db/d41/_g_u_i_dialog_p_v_r_client_priorities_8cpp.html", null ],
    [ "GUIDialogPVRClientPriorities.h", "d0/dcf/_g_u_i_dialog_p_v_r_client_priorities_8h.html", "d0/dcf/_g_u_i_dialog_p_v_r_client_priorities_8h" ],
    [ "GUIDialogPVRGroupManager.cpp", "d7/d94/_g_u_i_dialog_p_v_r_group_manager_8cpp.html", "d7/d94/_g_u_i_dialog_p_v_r_group_manager_8cpp" ],
    [ "GUIDialogPVRGroupManager.h", "db/d30/_g_u_i_dialog_p_v_r_group_manager_8h.html", "db/d30/_g_u_i_dialog_p_v_r_group_manager_8h" ],
    [ "GUIDialogPVRGuideControls.cpp", "d4/d6b/_g_u_i_dialog_p_v_r_guide_controls_8cpp.html", null ],
    [ "GUIDialogPVRGuideControls.h", "d3/d98/_g_u_i_dialog_p_v_r_guide_controls_8h.html", "d3/d98/_g_u_i_dialog_p_v_r_guide_controls_8h" ],
    [ "GUIDialogPVRGuideInfo.cpp", "d2/d64/_g_u_i_dialog_p_v_r_guide_info_8cpp.html", "d2/d64/_g_u_i_dialog_p_v_r_guide_info_8cpp" ],
    [ "GUIDialogPVRGuideInfo.h", "de/d3b/_g_u_i_dialog_p_v_r_guide_info_8h.html", "de/d3b/_g_u_i_dialog_p_v_r_guide_info_8h" ],
    [ "GUIDialogPVRGuideSearch.cpp", "d5/d8b/_g_u_i_dialog_p_v_r_guide_search_8cpp.html", "d5/d8b/_g_u_i_dialog_p_v_r_guide_search_8cpp" ],
    [ "GUIDialogPVRGuideSearch.h", "d5/dbd/_g_u_i_dialog_p_v_r_guide_search_8h.html", "d5/dbd/_g_u_i_dialog_p_v_r_guide_search_8h" ],
    [ "GUIDialogPVRItemsViewBase.cpp", "d7/d9c/_g_u_i_dialog_p_v_r_items_view_base_8cpp.html", "d7/d9c/_g_u_i_dialog_p_v_r_items_view_base_8cpp" ],
    [ "GUIDialogPVRItemsViewBase.h", "d5/d69/_g_u_i_dialog_p_v_r_items_view_base_8h.html", "d5/d69/_g_u_i_dialog_p_v_r_items_view_base_8h" ],
    [ "GUIDialogPVRRadioRDSInfo.cpp", "df/ddf/_g_u_i_dialog_p_v_r_radio_r_d_s_info_8cpp.html", "df/ddf/_g_u_i_dialog_p_v_r_radio_r_d_s_info_8cpp" ],
    [ "GUIDialogPVRRadioRDSInfo.h", "de/d5a/_g_u_i_dialog_p_v_r_radio_r_d_s_info_8h.html", "de/d5a/_g_u_i_dialog_p_v_r_radio_r_d_s_info_8h" ],
    [ "GUIDialogPVRRecordingInfo.cpp", "d1/ddf/_g_u_i_dialog_p_v_r_recording_info_8cpp.html", "d1/ddf/_g_u_i_dialog_p_v_r_recording_info_8cpp" ],
    [ "GUIDialogPVRRecordingInfo.h", "df/dd7/_g_u_i_dialog_p_v_r_recording_info_8h.html", "df/dd7/_g_u_i_dialog_p_v_r_recording_info_8h" ],
    [ "GUIDialogPVRRecordingSettings.cpp", "dc/db5/_g_u_i_dialog_p_v_r_recording_settings_8cpp.html", "dc/db5/_g_u_i_dialog_p_v_r_recording_settings_8cpp" ],
    [ "GUIDialogPVRRecordingSettings.h", "d4/dd3/_g_u_i_dialog_p_v_r_recording_settings_8h.html", "d4/dd3/_g_u_i_dialog_p_v_r_recording_settings_8h" ],
    [ "GUIDialogPVRTimerSettings.cpp", "d1/d97/_g_u_i_dialog_p_v_r_timer_settings_8cpp.html", "d1/d97/_g_u_i_dialog_p_v_r_timer_settings_8cpp" ],
    [ "GUIDialogPVRTimerSettings.h", "d0/d79/_g_u_i_dialog_p_v_r_timer_settings_8h.html", "d0/d79/_g_u_i_dialog_p_v_r_timer_settings_8h" ]
];