Kodi Documentation: CPlatformWebOS Class Reference
CPlatformWebOS Class Reference
#include <PlatformWebOS.h>
Public Member Functions
bool InitStageOne () override
Called at an early stage of application startup.
bool InitStageTwo () override
Called at a middle stage of application startup.
Public Member Functions inherited from CPlatformLinux
CPlatformLinux ()=default
~CPlatformLinux () override=default
void DeinitStageOne () override
Called at a late stage of application shutdown.
bool IsConfigureAddonsAtStartupEnabled () override
Flag whether disabled add-ons - installed via packagemanager or manually - should be offered for configuration and activation on kodi startup for this platform.
Public Member Functions inherited from CPlatform
CPlatform ()=default
C'tor.
virtual ~CPlatform ()=default
D'tor.
virtual bool InitStageThree ()
Called at a late stage of application startup.
virtual void DeinitStageTwo ()
Called at a middle stage of application shutdown.
virtual void DeinitStageThree ()
Called at an early stage of application shutdown.
virtual bool SupportsUserInstalledBinaryAddons ()
Flag whether this platform supports user installation of binary add-ons.
virtual void PlatformSyslog ()
Print platform specific info to log.
template<class T >
std::shared_ptr< T > GetService ()
Get a platform service instance.
Public Member Functions inherited from CComponentContainer< IPlatformService >
std::shared_ptr< T > GetComponent ()
Obtain a component.
std::shared_ptr< const T > GetComponent () const
Obtain a component.
std::size_t size () const
Returns number of registered components.
Static Public Member Functions
static CPlatform * CreateInstance ()
Static Public Member Functions inherited from CPlatformPosix
static bool TestQuitFlag ()
static void RequestQuit ()
Static Public Member Functions inherited from CPlatform
static CPlatform * CreateInstance ()
Creates the Platform object.
Protected Member Functions
void RegisterPowerManagement () override
Protected Member Functions inherited from CComponentContainer< IPlatformService >
void RegisterComponent (const std::shared_ptr< IPlatformService > &component)
Register a new component instance.
void DeregisterComponent (const std::type_info &typeInfo)
Deregister a component.
Member Function Documentation
CreateInstance()
static CPlatform * CPlatformWebOS::CreateInstance () static
InitStageOne()
bool CPlatformWebOS::InitStageOne () override virtual
Called at an early stage of application startup.
This method can be used to do platform specific environment preparation or initialisation (like setting environment variables for example)
Reimplemented from CPlatformLinux.
References HOME, CPlatformLinux::InitStageOne(), and CSpecialProtocol::TranslatePath().
InitStageTwo()
bool CPlatformWebOS::InitStageTwo () override virtual
Called at a middle stage of application startup.
This method can be used for starting platform specific services that do not depend on windowing/gui. (eg macos XBMCHelper)
Reimplemented from CPlatform.
References CServiceBroker::GetLogging(), CPlatform::InitStageTwo(), CLog::Log(), LOG_LEVEL_DEBUG, and LOGERROR.
RegisterPowerManagement()
void CPlatformWebOS::RegisterPowerManagement () override protected virtual
Reimplemented from CPlatformLinux.
References CLunaPowerManagement::Register().
The documentation for this class was generated from the following files:
PlatformWebOS.h
PlatformWebOS.cpp