Kodi Documentation: CDVDInputStreamFFmpeg Class Reference
CDVDInputStreamFFmpeg Class Reference
#include <DVDInputStreamFFmpeg.h>
Public Member Functions
CDVDInputStreamFFmpeg (const CFileItem &fileitem)
~CDVDInputStreamFFmpeg () override
bool Open () override
void Close () override
int Read (uint8_t *buf, int buf_size) override
int64_t Seek (int64_t offset, int whence) override
bool IsEOF () override
int64_t GetLength () override
std::string GetFileName () override
void Abort () override
bool Aborted ()
const CFileItem & GetItem () const
std::string GetProxyType () const
std::string GetProxyHost () const
uint16_t GetProxyPort () const
std::string GetProxyUser () const
std::string GetProxyPassword () const
Public Member Functions inherited from CDVDInputStream
CDVDInputStream (DVDStreamType m_streamType, const CFileItem &fileitem)
virtual ~CDVDInputStream ()
virtual std::string & GetContent ()
virtual CURL GetURL ()
virtual ENextStream NextStream ()
virtual int GetBlockSize ()
virtual bool CanSeek ()
virtual bool CanPause ()
virtual void SetReadRate (uint32_t rate)
Indicate expected read rate in bytes per second. This could be used to throttle caching rate. Should be seen as only a hint.
virtual bool GetCacheStatus (XFILE::SCacheStatus *status)
Get the cache status.
bool IsStreamType (DVDStreamType type) const
virtual BitstreamStats GetBitstreamStats () const
bool ContentLookup ()
virtual bool IsRealtime ()
void SetRealtime (bool realtime)
virtual IDemux * GetIDemux ()
virtual IPosTime * GetIPosTime ()
virtual IDisplayTime * GetIDisplayTime ()
virtual ITimes * GetITimes ()
virtual IChapter * GetIChapter ()
const CVariant & GetProperty (const std::string &key)
Protected Attributes
bool m_aborted = false
Protected Attributes inherited from CDVDInputStream
DVDStreamType m_streamType
BitstreamStats m_stats
std::string m_content
CFileItem m_item
bool m_contentLookup
bool m_realtime
Additional Inherited Members
Public Types inherited from CDVDInputStream
enum ENextStream { NEXTSTREAM_NONE , NEXTSTREAM_OPEN , NEXTSTREAM_RETRY }
Constructor & Destructor Documentation
CDVDInputStreamFFmpeg()
CDVDInputStreamFFmpeg::CDVDInputStreamFFmpeg (const CFileItem & fileitem) explicit
~CDVDInputStreamFFmpeg()
CDVDInputStreamFFmpeg::~CDVDInputStreamFFmpeg () override
References Close().
Member Function Documentation
Abort()
void CDVDInputStreamFFmpeg::Abort () inline override virtual
Reimplemented from CDVDInputStream.
References m_aborted.
Aborted()
bool CDVDInputStreamFFmpeg::Aborted () inline
References m_aborted.
Close()
void CDVDInputStreamFFmpeg::Close () override virtual
Reimplemented from CDVDInputStream.
References CDVDInputStream::Close().
Referenced by ~CDVDInputStreamFFmpeg().
GetFileName()
std::string CDVDInputStreamFFmpeg::GetFileName () override virtual
Reimplemented from CDVDInputStream.
References CURL::Get(), CDVDInputStream::GetFileName(), CDVDInputStream::GetURL(), and CURL::IsProtocol().
GetItem()
const CFileItem & CDVDInputStreamFFmpeg::GetItem () const inline
References CDVDInputStream::m_item.
GetLength()
int64_t CDVDInputStreamFFmpeg::GetLength () override virtual
Implements CDVDInputStream.
GetProxyHost()
std::string CDVDInputStreamFFmpeg::GetProxyHost () const
References CVariant::asString(), CGUIListItem::GetProperty(), CGUIListItem::HasProperty(), and CDVDInputStream::m_item.
GetProxyPassword()
std::string CDVDInputStreamFFmpeg::GetProxyPassword () const
References CVariant::asString(), CGUIListItem::GetProperty(), CGUIListItem::HasProperty(), and CDVDInputStream::m_item.
GetProxyPort()
uint16_t CDVDInputStreamFFmpeg::GetProxyPort () const
References CVariant::asInteger(), CGUIListItem::GetProperty(), GetProxyType(), CGUIListItem::HasProperty(), CDVDInputStream::m_item, and value.
GetProxyType()
std::string CDVDInputStreamFFmpeg::GetProxyType () const
References CVariant::asString(), CGUIListItem::GetProperty(), CGUIListItem::HasProperty(), and CDVDInputStream::m_item.
Referenced by GetProxyPort().
GetProxyUser()
std::string CDVDInputStreamFFmpeg::GetProxyUser () const
References CVariant::asString(), CGUIListItem::GetProperty(), CGUIListItem::HasProperty(), and CDVDInputStream::m_item.
IsEOF()
bool CDVDInputStreamFFmpeg::IsEOF () override virtual
Implements CDVDInputStream.
References m_aborted.
Open()
bool CDVDInputStreamFFmpeg::Open () override virtual
Reimplemented from CDVDInputStream.
References CFileItem::GetDynPath(), m_aborted, CDVDInputStream::m_item, CDVDInputStream::m_realtime, and CDVDInputStream::Open().
Read()
int CDVDInputStreamFFmpeg::Read (uint8_t * buf, int buf_size) override virtual
Implements CDVDInputStream.
Seek()
int64_t CDVDInputStreamFFmpeg::Seek (int64_t offset, int whence) override virtual
Implements CDVDInputStream.
Member Data Documentation
m_aborted
bool CDVDInputStreamFFmpeg::m_aborted = false protected
Referenced by Abort(), Aborted(), IsEOF(), and Open().
The documentation for this class was generated from the following files:
DVDInputStreamFFmpeg.h
DVDInputStreamFFmpeg.cpp