Kodi Documentation: CZeroconfBrowserAndroid Class Reference
CZeroconfBrowserAndroid Class Reference
#include <ZeroconfBrowserAndroid.h>
Public Member Functions
CZeroconfBrowserAndroid ()
~CZeroconfBrowserAndroid () override
Public Member Functions inherited from CZeroconfBrowser
void Start ()
void Stop ()
std::vector< ZeroconfService > GetFoundServices ()
bool ResolveService (ZeroconfService &fr_service, double f_timeout=1.0)
virtual void ProcessResults ()
bool AddServiceType (const std::string &fcr_service_type)
bool RemoveServiceType (const std::string &fcr_service_type)
Protected Member Functions
bool doAddServiceType (const std::string &fcr_service_type) override
bool doRemoveServiceType (const std::string &fcr_service_type) override
std::vector< ZeroconfService > doGetFoundServices () override
bool doResolveService (ZeroconfService &fr_service, double f_timeout) override
void addDiscoveredService (CZeroconfBrowserAndroidDiscover *browser, const CZeroconfBrowser::ZeroconfService &fcr_service)
adds the service to list of found services
void removeDiscoveredService (CZeroconfBrowserAndroidDiscover *browser, const CZeroconfBrowser::ZeroconfService &fcr_service)
Protected Member Functions inherited from CZeroconfBrowser
CZeroconfBrowser (const CZeroconfBrowser &)=delete
CZeroconfBrowser & operator= (const CZeroconfBrowser &)=delete
Private Types
typedef std::map< std::string, CZeroconfBrowserAndroidDiscover * > tBrowserMap
typedef std::map< CZeroconfBrowserAndroidDiscover *, std::vector< std::pair< ZeroconfService, unsigned int > > > tDiscoveredServicesMap
Private Attributes
jni::CJNINsdManager m_manager
CCriticalSection m_data_guard
tBrowserMap m_service_browsers
tDiscoveredServicesMap m_discovered_services
Friends
class CZeroconfBrowserAndroidDiscover
Additional Inherited Members
Static Public Member Functions inherited from CZeroconfBrowser
static CZeroconfBrowser * GetInstance ()
static void ReleaseInstance ()
static bool IsInstantiated ()
Member Typedef Documentation
tBrowserMap
typedef std::map<std::string, CZeroconfBrowserAndroidDiscover*> CZeroconfBrowserAndroid::tBrowserMap private
tDiscoveredServicesMap
typedef std::map<CZeroconfBrowserAndroidDiscover*, std::vector<std::pair<ZeroconfService, unsigned int> > > CZeroconfBrowserAndroid::tDiscoveredServicesMap private
Constructor & Destructor Documentation
CZeroconfBrowserAndroid()
CZeroconfBrowserAndroid::CZeroconfBrowserAndroid ()
~CZeroconfBrowserAndroid()
CZeroconfBrowserAndroid::~CZeroconfBrowserAndroid () override
References doRemoveServiceType(), m_data_guard, and m_service_browsers.
Member Function Documentation
addDiscoveredService()
void CZeroconfBrowserAndroid::addDiscoveredService (CZeroconfBrowserAndroidDiscover * browser, const CZeroconfBrowser::ZeroconfService & fcr_service) protected
adds the service to list of found services
References m_data_guard, and m_discovered_services.
Referenced by CZeroconfBrowserAndroidDiscover::onServiceFound().
doAddServiceType()
bool CZeroconfBrowserAndroid::doAddServiceType (const std::string & fcr_service_type) override protected virtual
Implements CZeroconfBrowser.
References CZeroconfBrowserAndroidDiscover, CLog::Log(), LOGDEBUG, m_data_guard, m_manager, and m_service_browsers.
doGetFoundServices()
std::vector< CZeroconfBrowser::ZeroconfService > CZeroconfBrowserAndroid::doGetFoundServices () override protected virtual
Implements CZeroconfBrowser.
References m_data_guard, and m_discovered_services.
doRemoveServiceType()
bool CZeroconfBrowserAndroid::doRemoveServiceType (const std::string & fcr_service_type) override protected virtual
Implements CZeroconfBrowser.
References CZeroconfBrowserAndroidDiscover::IsActive(), CLog::Log(), LOGDEBUG, m_data_guard, m_discovered_services, m_manager, and m_service_browsers.
Referenced by ~CZeroconfBrowserAndroid().
doResolveService()
bool CZeroconfBrowserAndroid::doResolveService (CZeroconfBrowser::ZeroconfService & fr_service, double f_timeout) override protected virtual
Implements CZeroconfBrowser.
References CZeroconfBrowser::ZeroconfService::GetIP(), CZeroconfBrowser::ZeroconfService::GetName(), CZeroconfBrowser::ZeroconfService::GetType(), CLog::Log(), LOGDEBUG, LOGERROR, CZeroconfBrowserAndroidResolve::m_errorCode, m_manager, CZeroconfBrowserAndroidResolve::m_resolutionDone, CZeroconfBrowserAndroidResolve::m_retServiceInfo, CZeroconfBrowser::ZeroconfService::SetHostname(), CZeroconfBrowser::ZeroconfService::SetIP(), CZeroconfBrowser::ZeroconfService::SetPort(), CZeroconfBrowser::ZeroconfService::SetTxtRecords(), value, and CEvent::Wait().
removeDiscoveredService()
void CZeroconfBrowserAndroid::removeDiscoveredService (CZeroconfBrowserAndroidDiscover * browser, const CZeroconfBrowser::ZeroconfService & fcr_service) protected
References m_data_guard, and m_discovered_services.
Friends And Related Symbol Documentation
CZeroconfBrowserAndroidDiscover
friend class CZeroconfBrowserAndroidDiscover friend
Referenced by doAddServiceType().
Member Data Documentation
m_data_guard
CCriticalSection CZeroconfBrowserAndroid::m_data_guard private
Referenced by addDiscoveredService(), doAddServiceType(), doGetFoundServices(), doRemoveServiceType(), removeDiscoveredService(), and ~CZeroconfBrowserAndroid().
m_discovered_services
tDiscoveredServicesMap CZeroconfBrowserAndroid::m_discovered_services private
Referenced by addDiscoveredService(), doGetFoundServices(), doRemoveServiceType(), and removeDiscoveredService().
m_manager
jni::CJNINsdManager CZeroconfBrowserAndroid::m_manager private
Referenced by doAddServiceType(), doRemoveServiceType(), and doResolveService().
m_service_browsers
tBrowserMap CZeroconfBrowserAndroid::m_service_browsers private
Referenced by doAddServiceType(), doRemoveServiceType(), and ~CZeroconfBrowserAndroid().
The documentation for this class was generated from the following files:
ZeroconfBrowserAndroid.h
ZeroconfBrowserAndroid.cpp