Kodi Documentation: MUSIC_GRABBER::CMusicInfoScraper Class Reference
MUSIC_GRABBER::CMusicInfoScraper Class Reference
#include <MusicInfoScraper.h>
Public Member Functions
CMusicInfoScraper (const ADDON::ScraperPtr &scraper)
~CMusicInfoScraper (void) override
void FindAlbumInfo (const std::string &strAlbum, const std::string &strArtist="")
void LoadAlbumInfo (int iAlbum)
void FindArtistInfo (const std::string &strArtist)
void LoadArtistInfo (int iArtist, const std::string &strSearch)
bool Completed ()
bool Succeeded ()
void Cancel ()
bool IsCanceled ()
int GetAlbumCount () const
int GetArtistCount () const
CMusicAlbumInfo & GetAlbum (int iAlbum)
CMusicArtistInfo & GetArtist (int iArtist)
std::vector< CMusicArtistInfo > & GetArtists ()
std::vector< CMusicAlbumInfo > & GetAlbums ()
void SetScraperInfo (const ADDON::ScraperPtr &scraper)
bool CheckValidOrFallback (const std::string &fallbackScraper)
Checks whether we have a valid scraper. If not, we try the fallbackScraper First tests the current scraper for validity by loading it. If it is not valid we attempt to load the fallback scraper. If this is also invalid we return false.
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Protected Member Functions
void FindAlbumInfo ()
void LoadAlbumInfo ()
void FindArtistInfo ()
void LoadArtistInfo ()
void OnStartup () override
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes
std::vector< CMusicAlbumInfo > m_vecAlbums
std::vector< CMusicArtistInfo > m_vecArtists
std::string m_strAlbum
std::string m_strArtist
std::string m_strSearch
int m_iAlbum
int m_iArtist
bool m_bSucceeded
bool m_bCanceled
XFILE::CCurlFile * m_http
ADDON::ScraperPtr m_scraper
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Constructor & Destructor Documentation
CMusicInfoScraper()
CMusicInfoScraper::CMusicInfoScraper (const ADDON::ScraperPtr & scraper) explicit
References m_bCanceled, m_bSucceeded, m_http, m_iAlbum, and m_iArtist.
~CMusicInfoScraper()
CMusicInfoScraper::~CMusicInfoScraper (void) override
References m_http, and CThread::StopThread().
Member Function Documentation
Cancel()
void CMusicInfoScraper::Cancel ()
References XFILE::CCurlFile::Cancel(), m_bCanceled, m_http, and XFILE::CCurlFile::Reset().
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), and MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo().
CheckValidOrFallback()
bool CMusicInfoScraper::CheckValidOrFallback (const std::string & fallbackScraper)
Checks whether we have a valid scraper. If not, we try the fallbackScraper First tests the current scraper for validity by loading it. If it is not valid we attempt to load the fallback scraper. If this is also invalid we return false.
Parameters
fallbackScraper name of scraper to use as a fallback
Returns
true if we have a valid scraper (or the default is valid).
Todo:
Handle fallback mechanism
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo().
Completed()
bool CMusicInfoScraper::Completed ()
References CThread::Join().
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), and MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo().
FindAlbumInfo() [1/2]
void CMusicInfoScraper::FindAlbumInfo () protected
References m_bSucceeded, m_http, m_scraper, m_strAlbum, m_strArtist, and m_vecAlbums.
Referenced by Process().
FindAlbumInfo() [2/2]
void CMusicInfoScraper::FindAlbumInfo (const std::string & strAlbum, const std::string & strArtist = "")
References CThread::Create(), m_bSucceeded, m_strAlbum, m_strArtist, and CThread::StopThread().
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo().
FindArtistInfo() [1/2]
void CMusicInfoScraper::FindArtistInfo () protected
References m_bSucceeded, m_http, m_scraper, m_strArtist, and m_vecArtists.
Referenced by Process().
FindArtistInfo() [2/2]
void CMusicInfoScraper::FindArtistInfo (const std::string & strArtist)
References CThread::Create(), m_bSucceeded, m_strArtist, and CThread::StopThread().
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo().
GetAlbum()
CMusicAlbumInfo & CMusicInfoScraper::GetAlbum (int iAlbum)
References m_vecAlbums.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo().
GetAlbumCount()
int CMusicInfoScraper::GetAlbumCount () const
References m_vecAlbums.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo().
GetAlbums()
std::vector< CMusicAlbumInfo > & MUSIC_GRABBER::CMusicInfoScraper::GetAlbums () inline
References m_vecAlbums.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo().
GetArtist()
CMusicArtistInfo & CMusicInfoScraper::GetArtist (int iArtist)
References m_vecArtists.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo().
GetArtistCount()
int CMusicInfoScraper::GetArtistCount () const
References m_vecArtists.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo().
GetArtists()
std::vector< CMusicArtistInfo > & MUSIC_GRABBER::CMusicInfoScraper::GetArtists () inline
References m_vecArtists.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo().
IsCanceled()
bool CMusicInfoScraper::IsCanceled ()
References m_bCanceled.
LoadAlbumInfo() [1/2]
void CMusicInfoScraper::LoadAlbumInfo () protected
References CAlbum::artistCredits, MUSIC_GRABBER::CMusicAlbumInfo::GetAlbum(), MUSIC_GRABBER::CMusicAlbumInfo::Load(), m_bSucceeded, m_http, m_iAlbum, m_scraper, and m_vecAlbums.
Referenced by Process().
LoadAlbumInfo() [2/2]
void CMusicInfoScraper::LoadAlbumInfo (int iAlbum)
References CThread::Create(), m_iAlbum, m_iArtist, and CThread::StopThread().
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo().
LoadArtistInfo() [1/2]
void CMusicInfoScraper::LoadArtistInfo () protected
References MUSIC_GRABBER::CMusicArtistInfo::GetArtist(), MUSIC_GRABBER::CMusicArtistInfo::Load(), m_bSucceeded, m_http, m_iArtist, m_scraper, m_strSearch, m_vecArtists, and CArtist::strArtist.
Referenced by Process().
LoadArtistInfo() [2/2]
void CMusicInfoScraper::LoadArtistInfo (int iArtist, const std::string & strSearch)
References CThread::Create(), m_iAlbum, m_iArtist, m_strSearch, and CThread::StopThread().
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo().
OnStartup()
void CMusicInfoScraper::OnStartup () override protected virtual
Reimplemented from CThread.
References m_bCanceled, and m_bSucceeded.
Process()
void CMusicInfoScraper::Process (void) override protected virtual
Reimplemented from CThread.
References FindAlbumInfo(), FindArtistInfo(), LoadAlbumInfo(), LoadArtistInfo(), CLog::Log(), LOGERROR, m_iAlbum, m_iArtist, m_strAlbum, and m_strArtist.
SetScraperInfo()
void MUSIC_GRABBER::CMusicInfoScraper::SetScraperInfo (const ADDON::ScraperPtr & scraper) inline
References m_scraper.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), and MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo().
Succeeded()
bool CMusicInfoScraper::Succeeded ()
References m_bCanceled, and m_bSucceeded.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), and MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo().
Member Data Documentation
m_bCanceled
bool MUSIC_GRABBER::CMusicInfoScraper::m_bCanceled protected
Referenced by Cancel(), CMusicInfoScraper(), IsCanceled(), OnStartup(), and Succeeded().
m_bSucceeded
bool MUSIC_GRABBER::CMusicInfoScraper::m_bSucceeded protected
Referenced by CMusicInfoScraper(), FindAlbumInfo(), FindAlbumInfo(), FindArtistInfo(), FindArtistInfo(), LoadAlbumInfo(), LoadArtistInfo(), OnStartup(), and Succeeded().
m_http
XFILE::CCurlFile* MUSIC_GRABBER::CMusicInfoScraper::m_http protected
Referenced by Cancel(), CMusicInfoScraper(), FindAlbumInfo(), FindArtistInfo(), LoadAlbumInfo(), LoadArtistInfo(), and ~CMusicInfoScraper().
m_iAlbum
int MUSIC_GRABBER::CMusicInfoScraper::m_iAlbum protected
Referenced by CMusicInfoScraper(), LoadAlbumInfo(), LoadAlbumInfo(), LoadArtistInfo(), and Process().
m_iArtist
int MUSIC_GRABBER::CMusicInfoScraper::m_iArtist protected
Referenced by CMusicInfoScraper(), LoadAlbumInfo(), LoadArtistInfo(), LoadArtistInfo(), and Process().
m_scraper
ADDON::ScraperPtr MUSIC_GRABBER::CMusicInfoScraper::m_scraper protected
Referenced by FindAlbumInfo(), FindArtistInfo(), LoadAlbumInfo(), LoadArtistInfo(), and SetScraperInfo().
m_strAlbum
std::string MUSIC_GRABBER::CMusicInfoScraper::m_strAlbum protected
Referenced by FindAlbumInfo(), FindAlbumInfo(), and Process().
m_strArtist
std::string MUSIC_GRABBER::CMusicInfoScraper::m_strArtist protected
Referenced by FindAlbumInfo(), FindAlbumInfo(), FindArtistInfo(), FindArtistInfo(), and Process().
m_strSearch
std::string MUSIC_GRABBER::CMusicInfoScraper::m_strSearch protected
Referenced by LoadArtistInfo(), and LoadArtistInfo().
m_vecAlbums
std::vector<CMusicAlbumInfo> MUSIC_GRABBER::CMusicInfoScraper::m_vecAlbums protected
Referenced by FindAlbumInfo(), GetAlbum(), GetAlbumCount(), GetAlbums(), and LoadAlbumInfo().
m_vecArtists
std::vector<CMusicArtistInfo> MUSIC_GRABBER::CMusicInfoScraper::m_vecArtists protected
Referenced by FindArtistInfo(), GetArtist(), GetArtistCount(), GetArtists(), and LoadArtistInfo().
The documentation for this class was generated from the following files:
MusicInfoScraper.h
MusicInfoScraper.cpp