Kodi Documentation: PVR::CPVRClientCapabilities Class Reference
PVR::CPVRClientCapabilities Class Reference
#include <PVRClientCapabilities.h>
Public Member Functions
CPVRClientCapabilities ()=default
virtual ~CPVRClientCapabilities ()=default
CPVRClientCapabilities (const CPVRClientCapabilities &other)
const CPVRClientCapabilities & operator= (const CPVRClientCapabilities &other)
const CPVRClientCapabilities & operator= (const PVR_ADDON_CAPABILITIES &addonCapabilities)
void clear ()
bool SupportsTV () const
Check whether this add-on supports TV channels.
bool SupportsRadio () const
Check whether this add-on supports radio channels.
bool SupportsProviders () const
Check whether this add-on supports providers.
bool SupportsChannelGroups () const
Check whether this add-on supports channel groups.
bool SupportsChannelScan () const
Check whether this add-on supports scanning for new channels on the backend.
bool SupportsChannelSettings () const
Check whether this add-on supports the following functions: DeleteChannel, RenameChannel, DialogChannelSettings and DialogAddChannel.
bool SupportsDescrambleInfo () const
Check whether this add-on supports descramble information for playing channels.
bool SupportsEPG () const
Check whether this add-on provides EPG information.
bool SupportsAsyncEPGTransfer () const
Check whether this add-on supports asynchronous transfer of epg events.
bool SupportsEpgTagEdl () const
Check whether this add-on supports retrieving an edit decision list for epg tags.
bool SupportsTimers () const
Check whether this add-on supports the creation and editing of timers.
bool SupportsRecordings () const
Check whether this add-on supports recordings.
bool SupportsRecordingsUndelete () const
Check whether this add-on supports undelete of deleted recordings.
bool SupportsRecordingsPlayCount () const
Check whether this add-on supports play count for recordings.
bool SupportsRecordingsLastPlayedPosition () const
Check whether this add-on supports store/retrieve of last played position for recordings..
bool SupportsRecordingsEdl () const
Check whether this add-on supports retrieving an edit decision list for recordings.
bool SupportsRecordingsRename () const
Check whether this add-on supports renaming recordings..
bool SupportsRecordingsLifetimeChange () const
Check whether this add-on supports changing lifetime of recording.
void GetRecordingsLifetimeValues (std::vector< std::pair< std::string, int > > &list) const
Obtain a list with all possible values for recordings lifetime.
bool SupportsRecordingsSize () const
Check whether this add-on supports retrieving the size recordings..
bool SupportsRecordingsDelete () const
Check whether this add-on supports deleting recordings.
bool SupportsMultipleRecordedStreams () const
Check whether this add-on supports multiple recorded streams at a time.
bool HandlesInputStream () const
Check whether this add-on provides an input stream. false if Kodi handles the stream.
bool HandlesDemuxing () const
Check whether this add-on demultiplexes packets.
Private Member Functions
void InitRecordingsLifetimeValues ()
Private Attributes
std::unique_ptr< PVR_ADDON_CAPABILITIES > m_addonCapabilities
std::vector< std::pair< std::string, int > > m_recordingsLifetimeValues
Constructor & Destructor Documentation
CPVRClientCapabilities() [1/2]
PVR::CPVRClientCapabilities::CPVRClientCapabilities () default
~CPVRClientCapabilities()
virtual PVR::CPVRClientCapabilities::~CPVRClientCapabilities () virtual default
CPVRClientCapabilities() [2/2]
CPVRClientCapabilities::CPVRClientCapabilities (const CPVRClientCapabilities & other)
References InitRecordingsLifetimeValues(), and m_addonCapabilities.
Member Function Documentation
clear()
void CPVRClientCapabilities::clear ()
References m_addonCapabilities, and m_recordingsLifetimeValues.
Referenced by PVR::CPVRClient::ResetProperties().
GetRecordingsLifetimeValues()
void CPVRClientCapabilities::GetRecordingsLifetimeValues (std::vector< std::pair< std::string, int > > & list) const
Obtain a list with all possible values for recordings lifetime.
Parameters
list out, the list with the values or an empty list, if lifetime is not supported.
References m_recordingsLifetimeValues.
HandlesDemuxing()
bool PVR::CPVRClientCapabilities::HandlesDemuxing () const inline
Check whether this add-on demultiplexes packets.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::DemuxAbort(), PVR::CPVRClient::DemuxFlush(), PVR::CPVRClient::DemuxRead(), and PVR::CPVRClient::DemuxReset().
HandlesInputStream()
bool PVR::CPVRClientCapabilities::HandlesInputStream () const inline
Check whether this add-on provides an input stream. false if Kodi handles the stream.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::GetStreamReadChunkSize().
InitRecordingsLifetimeValues()
void CPVRClientCapabilities::InitRecordingsLifetimeValues () private
References g_localizeStrings, CLocalizeStrings::Get(), m_addonCapabilities, m_recordingsLifetimeValues, and SupportsRecordingsLifetimeChange().
Referenced by CPVRClientCapabilities(), operator=(), and operator=().
operator=() [1/2]
const CPVRClientCapabilities & CPVRClientCapabilities::operator= (const CPVRClientCapabilities & other)
References InitRecordingsLifetimeValues(), and m_addonCapabilities.
operator=() [2/2]
const CPVRClientCapabilities & CPVRClientCapabilities::operator= (const PVR_ADDON_CAPABILITIES & addonCapabilities)
References InitRecordingsLifetimeValues(), and m_addonCapabilities.
SupportsAsyncEPGTransfer()
bool PVR::CPVRClientCapabilities::SupportsAsyncEPGTransfer () const inline
Check whether this add-on supports asynchronous transfer of epg events.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
SupportsChannelGroups()
bool PVR::CPVRClientCapabilities::SupportsChannelGroups () const inline
Check whether this add-on supports channel groups.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::GetChannelGroupMembers(), PVR::CPVRClient::GetChannelGroups(), and PVR::CPVRClient::GetChannelGroupsAmount().
SupportsChannelScan()
bool PVR::CPVRClientCapabilities::SupportsChannelScan () const inline
Check whether this add-on supports scanning for new channels on the backend.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::StartChannelScan().
SupportsChannelSettings()
bool PVR::CPVRClientCapabilities::SupportsChannelSettings () const inline
Check whether this add-on supports the following functions: DeleteChannel, RenameChannel, DialogChannelSettings and DialogAddChannel.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::DeleteChannel(), PVR::CPVRClients::GetClientsSupportingChannelSettings(), PVR::CPVRClient::OpenDialogChannelAdd(), PVR::CPVRClient::OpenDialogChannelSettings(), and PVR::CPVRClient::RenameChannel().
SupportsDescrambleInfo()
bool PVR::CPVRClientCapabilities::SupportsDescrambleInfo () const inline
Check whether this add-on supports descramble information for playing channels.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::GetDescrambleInfo().
SupportsEPG()
bool PVR::CPVRClientCapabilities::SupportsEPG () const inline
Check whether this add-on provides EPG information.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::GetEPGForChannel(), PVR::CPVRClient::IsPlayable(), PVR::CPVRClient::IsRecordable(), PVR::CPVRClient::SetEPGMaxFutureDays(), PVR::CPVRClient::SetEPGMaxPastDays(), and PVR::CPVRClient::UpdateTimerTypes().
SupportsEpgTagEdl()
bool PVR::CPVRClientCapabilities::SupportsEpgTagEdl () const inline
Check whether this add-on supports retrieving an edit decision list for epg tags.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::GetEpgTagEdl().
SupportsMultipleRecordedStreams()
bool PVR::CPVRClientCapabilities::SupportsMultipleRecordedStreams () const inline
Check whether this add-on supports multiple recorded streams at a time.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::GetRecordedStreamTimes(), PVR::CPVRClient::IsRecordedStreamRealTime(), PVR::CPVRClient::OpenRecordedStream(), and PVR::CPVRClient::PauseRecordedStream().
SupportsProviders()
bool PVR::CPVRClientCapabilities::SupportsProviders () const inline
Check whether this add-on supports providers.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::GetProviders().
SupportsRadio()
bool PVR::CPVRClientCapabilities::SupportsRadio () const inline
Check whether this add-on supports radio channels.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::CanPlayChannel(), PVR::CPVRClient::GetChannelGroupMembers(), PVR::CPVRClient::GetChannelGroups(), PVR::CPVRClient::GetChannels(), and PVR::CPVRClients::GetClientsSupportingChannelSettings().
SupportsRecordings()
bool PVR::CPVRClientCapabilities::SupportsRecordings () const inline
Check whether this add-on supports recordings.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::DeleteRecording(), PVR::CPVRClient::GetRecordings(), PVR::CPVRClient::GetRecordingsAmount(), PVR::CPVRClient::GetRecordingStreamProperties(), PVR::CPVRClient::GetStreamReadChunkSize(), PVR::CPVRClient::IsRecordable(), PVR::CPVRClient::OpenRecordedStream(), and PVR::CPVRClient::RenameRecording().
SupportsRecordingsDelete()
bool PVR::CPVRClientCapabilities::SupportsRecordingsDelete () const inline
Check whether this add-on supports deleting recordings.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::DeleteRecording().
SupportsRecordingsEdl()
bool PVR::CPVRClientCapabilities::SupportsRecordingsEdl () const inline
Check whether this add-on supports retrieving an edit decision list for recordings.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::GetRecordingEdl().
SupportsRecordingsLastPlayedPosition()
bool PVR::CPVRClientCapabilities::SupportsRecordingsLastPlayedPosition () const inline
Check whether this add-on supports store/retrieve of last played position for recordings..
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::GetRecordingLastPlayedPosition(), PVR::CPVRClient::SetRecordingLastPlayedPosition(), PVR::CPVRRecording::Update(), and PVR::CPVRRecording::UpdateMetadata().
SupportsRecordingsLifetimeChange()
bool PVR::CPVRClientCapabilities::SupportsRecordingsLifetimeChange () const inline
Check whether this add-on supports changing lifetime of recording.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CGUIDialogPVRRecordingSettings::CanEditRecording(), InitRecordingsLifetimeValues(), and PVR::CPVRClient::SetRecordingLifetime().
SupportsRecordingsPlayCount()
bool PVR::CPVRClientCapabilities::SupportsRecordingsPlayCount () const inline
Check whether this add-on supports play count for recordings.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CGUIDialogPVRRecordingSettings::CanEditRecording(), PVR::CPVRClient::SetRecordingPlayCount(), PVR::CPVRRecording::Update(), and PVR::CPVRRecording::UpdateMetadata().
SupportsRecordingsRename()
bool PVR::CPVRClientCapabilities::SupportsRecordingsRename () const inline
Check whether this add-on supports renaming recordings..
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CGUIDialogPVRRecordingSettings::CanEditRecording().
SupportsRecordingsSize()
bool PVR::CPVRClientCapabilities::SupportsRecordingsSize () const inline
Check whether this add-on supports retrieving the size recordings..
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::GetRecordingSize().
SupportsRecordingsUndelete()
bool PVR::CPVRClientCapabilities::SupportsRecordingsUndelete () const inline
Check whether this add-on supports undelete of deleted recordings.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::DeleteAllRecordingsFromTrash(), PVR::CPVRClient::GetRecordings(), PVR::CPVRClient::GetRecordingsAmount(), and PVR::CPVRClient::UndeleteRecording().
SupportsTimers()
bool PVR::CPVRClientCapabilities::SupportsTimers () const inline
Check whether this add-on supports the creation and editing of timers.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::AddTimer(), PVR::CPVRClient::DeleteTimer(), PVR::CPVRClient::GetTimers(), PVR::CPVRClient::GetTimersAmount(), PVR::CPVRClient::UpdateTimer(), and PVR::CPVRClient::UpdateTimerTypes().
SupportsTV()
bool PVR::CPVRClientCapabilities::SupportsTV () const inline
Check whether this add-on supports TV channels.
Returns
True if supported, false otherwise.
References m_addonCapabilities.
Referenced by PVR::CPVRClient::CanPlayChannel(), PVR::CPVRClient::GetChannelGroupMembers(), PVR::CPVRClient::GetChannelGroups(), PVR::CPVRClient::GetChannels(), and PVR::CPVRClients::GetClientsSupportingChannelSettings().
Member Data Documentation
m_addonCapabilities
std::unique_ptr<PVR_ADDON_CAPABILITIES> PVR::CPVRClientCapabilities::m_addonCapabilities private
Referenced by clear(), CPVRClientCapabilities(), HandlesDemuxing(), HandlesInputStream(), InitRecordingsLifetimeValues(), operator=(), operator=(), SupportsAsyncEPGTransfer(), SupportsChannelGroups(), SupportsChannelScan(), SupportsChannelSettings(), SupportsDescrambleInfo(), SupportsEPG(), SupportsEpgTagEdl(), SupportsMultipleRecordedStreams(), SupportsProviders(), SupportsRadio(), SupportsRecordings(), SupportsRecordingsDelete(), SupportsRecordingsEdl(), SupportsRecordingsLastPlayedPosition(), SupportsRecordingsLifetimeChange(), SupportsRecordingsPlayCount(), SupportsRecordingsRename(), SupportsRecordingsSize(), SupportsRecordingsUndelete(), SupportsTimers(), and SupportsTV().
m_recordingsLifetimeValues
std::vector<std::pair<std::string, int> > PVR::CPVRClientCapabilities::m_recordingsLifetimeValues private
Referenced by clear(), GetRecordingsLifetimeValues(), and InitRecordingsLifetimeValues().
The documentation for this class was generated from the following files:
PVRClientCapabilities.h
PVRClientCapabilities.cpp