Kodi Documentation: KODI::RETRO::IGUIRenderSettings Class Reference
KODI::RETRO::IGUIRenderSettings Class Reference abstract
Interface to pass render settings from the GUI to the renderer.
#include <IGUIRenderSettings.h>
Public Member Functions
virtual ~IGUIRenderSettings ()=default
virtual bool HasVideoFilter () const
Returns true if this render target has a video filter set.
virtual bool HasStretchMode () const
Returns true if this render target has a stretch mode set.
virtual bool HasRotation () const
Returns true if this render target has a video rotation set.
virtual bool HasPixels () const
Returns true if this render target has a path to a savestate for showing pixel data.
virtual CRenderSettings GetSettings () const =0
Get the settings used to render this target.
virtual CRect GetDimensions () const
Get the dimensions of this target.
Detailed Description
Interface to pass render settings from the GUI to the renderer.
Constructor & Destructor Documentation
~IGUIRenderSettings()
virtual KODI::RETRO::IGUIRenderSettings::~IGUIRenderSettings () virtual default
Member Function Documentation
GetDimensions()
virtual CRect KODI::RETRO::IGUIRenderSettings::GetDimensions () const inline virtual
Get the dimensions of this target.
Dimensions are ignored for fullscreen windows.
Returns
The destination dimensions, or unused for fullscreen window
Reimplemented in KODI::RETRO::CGUIRenderSettings.
Referenced by KODI::RETRO::CRPRenderManager::RenderControl().
GetSettings()
virtual CRenderSettings KODI::RETRO::IGUIRenderSettings::GetSettings () const pure virtual
Get the settings used to render this target.
Returns
The render settings
Implemented in KODI::RETRO::CGUIGameSettings, and KODI::RETRO::CGUIRenderSettings.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings().
HasPixels()
virtual bool KODI::RETRO::IGUIRenderSettings::HasPixels () const inline virtual
Returns true if this render target has a path to a savestate for showing pixel data.
Reimplemented in KODI::RETRO::CGUIRenderSettings.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings().
HasRotation()
virtual bool KODI::RETRO::IGUIRenderSettings::HasRotation () const inline virtual
Returns true if this render target has a video rotation set.
Reimplemented in KODI::RETRO::CGUIRenderSettings.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings().
HasStretchMode()
virtual bool KODI::RETRO::IGUIRenderSettings::HasStretchMode () const inline virtual
Returns true if this render target has a stretch mode set.
Reimplemented in KODI::RETRO::CGUIRenderSettings.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings().
HasVideoFilter()
virtual bool KODI::RETRO::IGUIRenderSettings::HasVideoFilter () const inline virtual
Returns true if this render target has a video filter set.
Reimplemented in KODI::RETRO::CGUIRenderSettings.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings().
The documentation for this class was generated from the following file:
IGUIRenderSettings.h