Kodi Documentation: CTimer Class Reference
CTimer Class Reference
#include <Timer.h>
Public Member Functions
CTimer (ITimerCallback *callback)
CTimer (std::function< void()> const &callback)
~CTimer () override
bool Start (std::chrono::milliseconds timeout, bool interval=false)
bool Stop (bool wait=false)
bool Restart ()
void RestartAsync (std::chrono::milliseconds timeout)
bool IsRunning () const
float GetElapsedSeconds () const
float GetElapsedMilliseconds () const
Protected Member Functions
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Attributes
std::function< void()> m_callback
std::chrono::milliseconds m_timeout
bool m_interval
std::chrono::time_point< std::chrono::steady_clock > m_endTime
CEvent m_eventTimeout
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CTimer() [1/2]
CTimer::CTimer (ITimerCallback * callback) explicit
CTimer() [2/2]
CTimer::CTimer (std::function< void()> const & callback) explicit
~CTimer()
CTimer::~CTimer () override
References Stop().
Member Function Documentation
GetElapsedMilliseconds()
float CTimer::GetElapsedMilliseconds () const
References IsRunning(), m_endTime, and m_timeout.
Referenced by GetElapsedSeconds(), and CWinSystemAndroid::SetHdmiState().
GetElapsedSeconds()
float CTimer::GetElapsedSeconds () const
References GetElapsedMilliseconds().
IsRunning()
bool CTimer::IsRunning () const inline
References CThread::IsRunning().
Referenced by PVR::CPVRChannelNumberInputHandler::AppendChannelNumberCharacter(), GetElapsedMilliseconds(), CGUIDialogSettingsBase::OnClick(), PVR::CPVRChannelNumberInputHandler::OnTimeout(), CGUIKeyboard::resetAutoCloseTimer(), Restart(), CWinSystemAndroid::SetHdmiState(), Start(), CWinSystemOSX::StartLostDeviceTimer(), CWinSystemTVOS::StartLostDeviceTimer(), Stop(), and ADDON::CSkinSettingUpdateHandler::TriggerSave().
Process()
void CTimer::Process (void) override protected virtual
Reimplemented from CThread.
References CThread::m_bStop, m_callback, m_endTime, m_eventTimeout, m_interval, m_timeout, and CEvent::Wait().
Restart()
bool CTimer::Restart ()
References IsRunning(), m_interval, m_timeout, Start(), and Stop().
Referenced by PVR::CPVRChannelNumberInputHandler::AppendChannelNumberCharacter(), CGUIDialogSettingsBase::OnClick(), CGUIKeyboard::resetAutoCloseTimer(), CWinSystemOSX::StartLostDeviceTimer(), CWinSystemTVOS::StartLostDeviceTimer(), and ADDON::CSkinSettingUpdateHandler::TriggerSave().
RestartAsync()
void CTimer::RestartAsync (std::chrono::milliseconds timeout)
References m_endTime, m_eventTimeout, m_timeout, and CEvent::Set().
Referenced by CLibInputKeyboard::KeyRepeatTimeout(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::KeyRepeatTimeout(), and ADDON::CRepositoryUpdater::OnTimeout().
Start()
bool CTimer::Start (std::chrono::milliseconds timeout, bool interval = false)
References CThread::Create(), IsRunning(), m_callback, m_interval, and m_timeout.
Referenced by PVR::CPVRChannelNumberInputHandler::AppendChannelNumberCharacter(), CTextureCache::CleanTimer(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::ConvertAndSendKey(), COSScreenSaverX11::Inhibit(), CTextureCache::Initialize(), CWinSystemAndroid::InitiateModeChange(), CGUIDialogSettingsBase::OnClick(), PVR::CPVRChannelNumberInputHandler::OnTimeout(), CLibInputKeyboard::ProcessKey(), Restart(), ADDON::CRepositoryUpdater::ScheduleUpdate(), CGUIKeyboard::startAutoCloseTimer(), CWinSystemOSX::StartLostDeviceTimer(), CWinSystemTVOS::StartLostDeviceTimer(), and ADDON::CSkinSettingUpdateHandler::TriggerSave().
Stop()
bool CTimer::Stop (bool wait = false)
References IsRunning(), CThread::m_bStop, m_eventTimeout, CEvent::Set(), and CThread::StopThread().
Referenced by KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::ConvertAndSendKey(), CWinSystemAndroid::CreateNewWindow(), PVR::CPVRChannelNumberInputHandler::ExecuteAction(), CWinSystemAndroid::InitiateModeChange(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::OnKeyboardKeymap(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::OnKeyboardLeave(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::OnKeyboardModifiers(), CGUIDialogSettingsBase::OnMessage(), CLibInputKeyboard::ProcessKey(), Restart(), ADDON::CRepositoryUpdater::ScheduleUpdate(), CWinSystemAndroid::SetHdmiState(), CWinSystemOSX::StopLostDeviceTimer(), CWinSystemTVOS::StopLostDeviceTimer(), COSScreenSaverX11::Uninhibit(), and ~CTimer().
Member Data Documentation
m_callback
std::function<void()> CTimer::m_callback private
Referenced by Process(), and Start().
m_endTime
std::chrono::time_point<std::chrono::steady_clock> CTimer::m_endTime private
Referenced by GetElapsedMilliseconds(), Process(), and RestartAsync().
m_eventTimeout
CEvent CTimer::m_eventTimeout private
Referenced by Process(), RestartAsync(), and Stop().
m_interval
bool CTimer::m_interval private
Referenced by Process(), Restart(), and Start().
m_timeout
std::chrono::milliseconds CTimer::m_timeout private
Referenced by GetElapsedMilliseconds(), Process(), Restart(), RestartAsync(), and Start().
The documentation for this class was generated from the following files:
threads/Timer.h
Timer.cpp