Kodi Documentation: CDirectoryJob Class Reference
CDirectoryJob Class Reference
Public Member Functions
CDirectoryJob (const std::string &url, const std::string &target, SortDescription sort, int limit, CDirectoryProvider::BrowseMode browse, int parentID)
~CDirectoryJob () override=default
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
bool DoWork () override
Main workhorse function of CJob instances.
std::shared_ptr< CThumbLoader > getThumbLoader (const CGUIStaticItemPtr &item)
template<class CThumbLoaderClass >
void initThumbLoader (InfoTagType type)
const std::vector< CGUIStaticItemPtr > & GetItems () const
const std::string & GetTarget () const
std::vector< InfoTagType > GetItemTypes (std::vector< InfoTagType > &itemTypes) const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Private Attributes
std::string m_url
std::string m_target
SortDescription m_sort
unsigned int m_limit
CDirectoryProvider::BrowseMode m_browse {CDirectoryProvider::BrowseMode::AUTO}
int m_parentID
std::vector< CGUIStaticItemPtr > m_items
std::map< InfoTagType, std::shared_ptr< CThumbLoader > > m_thumbloaders
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Constructor & Destructor Documentation
CDirectoryJob()
CDirectoryJob::CDirectoryJob (const std::string & url, const std::string & target, SortDescription sort, int limit, CDirectoryProvider::BrowseMode browse, int parentID) inline
~CDirectoryJob()
CDirectoryJob::~CDirectoryJob () override default
Member Function Documentation
DoWork()
bool CDirectoryJob::DoWork () inline override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CDirectoryProvider::ALWAYS, CVariant::asString(), CDirectoryProvider::AUTO, XFILE::DIR_FLAG_DEFAULTS, g_localizeStrings, CLocalizeStrings::Get(), XFILE::CDirectory::GetDirectory(), CGUIListItem::GetProperty(), getThumbLoader(), CGUIListItem::HasProperty(), CFileItemList::IsEmpty(), LOGWARNING, m_browse, m_items, m_limit, m_parentID, m_sort, m_target, m_url, CGUIListItem::SetArt(), CFileItem::SetLabel(), CGUIListItem::SetProperty(), CFileItemList::Size(), CFileItemList::Sort(), SortDescription::sortBy, and SortByNone.
GetItems()
const std::vector< CGUIStaticItemPtr > & CDirectoryJob::GetItems () const inline
References m_items.
GetItemTypes()
std::vector< InfoTagType > CDirectoryJob::GetItemTypes (std::vector< InfoTagType > & itemTypes) const inline
References m_thumbloaders.
GetTarget()
const std::string & CDirectoryJob::GetTarget () const inline
References m_target.
getThumbLoader()
std::shared_ptr< CThumbLoader > CDirectoryJob::getThumbLoader (const CGUIStaticItemPtr & item) inline
References AUDIO, KODI::MUSIC::IsAudio(), m_thumbloaders, PICTURE, PROGRAM, PVR, and VIDEO.
Referenced by DoWork().
GetType()
const char * CDirectoryJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CJob.
Referenced by operator==().
initThumbLoader()
template<class CThumbLoaderClass > void CDirectoryJob::initThumbLoader (InfoTagType type) inline
References m_thumbloaders.
operator==()
bool CDirectoryJob::operator== (const CJob * job) const inline override virtual
Reimplemented from CJob.
References CJob::GetType(), GetType(), and m_url.
Member Data Documentation
m_browse
CDirectoryProvider::BrowseMode CDirectoryJob::m_browse {CDirectoryProvider::BrowseMode::AUTO} private
Referenced by DoWork().
m_items
std::vector<CGUIStaticItemPtr> CDirectoryJob::m_items private
Referenced by DoWork(), and GetItems().
m_limit
unsigned int CDirectoryJob::m_limit private
Referenced by DoWork().
m_parentID
int CDirectoryJob::m_parentID private
Referenced by DoWork().
m_sort
SortDescription CDirectoryJob::m_sort private
Referenced by DoWork().
m_target
std::string CDirectoryJob::m_target private
Referenced by DoWork(), and GetTarget().
m_thumbloaders
std::map<InfoTagType, std::shared_ptr<CThumbLoader> > CDirectoryJob::m_thumbloaders private
Referenced by GetItemTypes(), getThumbLoader(), and initThumbLoader().
m_url
std::string CDirectoryJob::m_url private
Referenced by DoWork(), and operator==().
The documentation for this class was generated from the following file:
DirectoryProvider.cpp