Kodi Documentation: KODI::GUILIB::GUIINFO::CGUIInfoProviders Class Reference
KODI::GUILIB::GUIINFO::CGUIInfoProviders Class Reference
#include <GUIInfoProviders.h>
Public Member Functions
CGUIInfoProviders ()
virtual ~CGUIInfoProviders ()
void RegisterProvider (IGUIInfoProvider *provider, bool bAppend=true)
Register a guiinfo provider.
void UnregisterProvider (IGUIInfoProvider *provider)
Unregister a guiinfo provider.
bool InitCurrentItem (CFileItem *item)
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) const
Get a GUIInfoManager label string from one of the registered providers.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const
Get a GUIInfoManager integer value from one of the registered providers.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const
Get a GUIInfoManager bool value from one of the registered providers.
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo)
Set new audio/video/subtitle stream info data at all registered providers.
CPlayerGUIInfo & GetPlayerInfoProvider ()
Get the player guiinfo provider.
CSystemGUIInfo & GetSystemInfoProvider ()
Get the system guiinfo provider.
CPicturesGUIInfo & GetPicturesInfoProvider ()
Get the pictures guiinfo provider.
CGUIControlsGUIInfo & GetGUIControlsInfoProvider ()
Get the gui controls guiinfo provider.
CLibraryGUIInfo & GetLibraryInfoProvider ()
Get the library guiinfo provider.
Private Attributes
std::vector< IGUIInfoProvider * > m_providers
CAddonsGUIInfo m_addonsGUIInfo
CGamesGUIInfo m_gamesGUIInfo
CGUIControlsGUIInfo m_guiControlsGUIInfo
CLibraryGUIInfo m_libraryGUIInfo
CMusicGUIInfo m_musicGUIInfo
CPicturesGUIInfo m_picturesGUIInfo
CPlayerGUIInfo m_playerGUIInfo
CSkinGUIInfo m_skinGUIInfo
CSystemGUIInfo m_systemGUIInfo
CVideoGUIInfo m_videoGUIInfo
CVisualisationGUIInfo m_visualisationGUIInfo
CWeatherGUIInfo m_weatherGUIInfo
Constructor & Destructor Documentation
CGUIInfoProviders()
CGUIInfoProviders::CGUIInfoProviders ()
References m_addonsGUIInfo, m_gamesGUIInfo, m_guiControlsGUIInfo, m_libraryGUIInfo, m_musicGUIInfo, m_picturesGUIInfo, m_playerGUIInfo, m_skinGUIInfo, m_systemGUIInfo, m_videoGUIInfo, m_visualisationGUIInfo, m_weatherGUIInfo, and RegisterProvider().
~CGUIInfoProviders()
CGUIInfoProviders::~CGUIInfoProviders () virtual
References m_addonsGUIInfo, m_gamesGUIInfo, m_guiControlsGUIInfo, m_libraryGUIInfo, m_musicGUIInfo, m_picturesGUIInfo, m_playerGUIInfo, m_skinGUIInfo, m_systemGUIInfo, m_videoGUIInfo, m_visualisationGUIInfo, m_weatherGUIInfo, and UnregisterProvider().
Member Function Documentation
GetBool()
bool CGUIInfoProviders::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const
Get a GUIInfoManager bool value from one of the registered providers.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully by one of the providers, false otherwise.
References m_providers, and value.
Referenced by CGUIInfoManager::GetBool(), CGUIInfoManager::GetItemBool(), and CGUIInfoManager::GetMultiInfoBool().
GetGUIControlsInfoProvider()
CGUIControlsGUIInfo & KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetGUIControlsInfoProvider () inline
Get the gui controls guiinfo provider.
Returns
The gui controls guiinfo provider.
References m_guiControlsGUIInfo.
Referenced by CProfileManager::LoadProfile(), CGUIWindowManager::PreviousWindow(), CApplication::Render(), CSkinSettings::Reset(), CGUIBaseContainer::SetContainerMoving(), CGUIWindow::SetInitialVisibility(), and CGUIViewControl::UpdateViewVisibility().
GetInt()
bool CGUIInfoProviders::GetInt (int & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const
Get a GUIInfoManager integer value from one of the registered providers.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully by one of the providers, false otherwise.
References m_providers, and value.
Referenced by CGUIInfoManager::GetInt(), CGUIInfoManager::GetItemInt(), and CGUIInfoManager::GetMultiInfoInt().
GetLabel()
bool CGUIInfoProviders::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) const
Get a GUIInfoManager label string from one of the registered providers.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully by one of the providers, false otherwise.
References m_providers, and value.
Referenced by CGUIInfoManager::GetLabel(), CGUIInfoManager::GetMultiInfoItemLabel(), and CGUIInfoManager::GetMultiInfoLabel().
GetLibraryInfoProvider()
CLibraryGUIInfo & KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetLibraryInfoProvider () inline
Get the library guiinfo provider.
Returns
The library guiinfo provider.
References m_libraryGUIInfo.
Referenced by CMusicDatabase::CommitTransaction(), CVideoDatabase::CommitTransaction(), CMusicDatabase::ImportFromXML(), CProfileManager::LoadProfile(), CGUIWindowMusicBase::OnRemoveSource(), MUSIC_INFO::CMusicInfoScanner::Process(), and KODI::VIDEO::CVideoInfoScanner::Process().
GetPicturesInfoProvider()
CPicturesGUIInfo & KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetPicturesInfoProvider () inline
Get the pictures guiinfo provider.
Returns
The pictures guiinfo provider.
References m_picturesGUIInfo.
Referenced by CGUIDialogPictureInfo::FrameMove(), CGUIWindowSlideShow::OnDeinitWindow(), CGUIWindowSlideShow::Process(), and CGUIDialogPictureInfo::SetPicture().
GetPlayerInfoProvider()
CPlayerGUIInfo & KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetPlayerInfoProvider () inline
Get the player guiinfo provider.
Returns
The player guiinfo provider.
References m_playerGUIInfo.
Referenced by CGUIWindowVisualisation::FrameMove(), PVR::CPVRGUIChannelNavigator::HideInfo(), CApplication::OnAction(), CGUIWindowVisualisation::OnAction(), CGUIWindowFullScreen::OnAction(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), CGUIWindowVisualisation::OnMessage(), CGUIWindowFullScreen::OnMessage(), PVR::CPVRGUIChannelNavigator::ShowInfo(), and PVR::CPVRGUIChannelNavigator::SubscribeToShowInfoEventStream().
GetSystemInfoProvider()
CSystemGUIInfo & KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetSystemInfoProvider () inline
Get the system guiinfo provider.
Returns
The system guiinfo provider.
References m_systemGUIInfo.
Referenced by CGUIWindowDebugInfo::Process(), and CApplication::Render().
InitCurrentItem()
bool CGUIInfoProviders::InitCurrentItem (CFileItem * item)
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by one of the providers, false otherwise.
References m_providers.
Referenced by CGUIInfoManager::ResetCurrentItem(), and CGUIInfoManager::SetCurrentItem().
RegisterProvider()
void CGUIInfoProviders::RegisterProvider (IGUIInfoProvider * provider, bool bAppend = true)
Register a guiinfo provider.
Parameters
provider The provider to register.
bAppend True to append to the list of providers, false to insert before the first provider
References m_providers.
Referenced by CGUIInfoProviders(), and CGUIInfoManager::RegisterInfoProvider().
UnregisterProvider()
void CGUIInfoProviders::UnregisterProvider (IGUIInfoProvider * provider)
Unregister a guiinfo provider.
Parameters
provider The provider to unregister.
References m_providers.
Referenced by CGUIInfoManager::UnregisterInfoProvider(), and ~CGUIInfoProviders().
UpdateAVInfo()
void CGUIInfoProviders::UpdateAVInfo (const AudioStreamInfo & audioInfo, const VideoStreamInfo & videoInfo, const SubtitleStreamInfo & subtitleInfo)
Set new audio/video/subtitle stream info data at all registered providers.
Parameters
audioInfo New audio stream info.
videoInfo New video stream info.
subtitleInfo New subtitle stream info.
References m_providers.
Referenced by CGUIInfoManager::UpdateAVInfo().
Member Data Documentation
m_addonsGUIInfo
CAddonsGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_addonsGUIInfo private
Referenced by CGUIInfoProviders(), and ~CGUIInfoProviders().
m_gamesGUIInfo
CGamesGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_gamesGUIInfo private
Referenced by CGUIInfoProviders(), and ~CGUIInfoProviders().
m_guiControlsGUIInfo
CGUIControlsGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_guiControlsGUIInfo private
Referenced by CGUIInfoProviders(), GetGUIControlsInfoProvider(), and ~CGUIInfoProviders().
m_libraryGUIInfo
CLibraryGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_libraryGUIInfo private
Referenced by CGUIInfoProviders(), GetLibraryInfoProvider(), and ~CGUIInfoProviders().
m_musicGUIInfo
CMusicGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_musicGUIInfo private
Referenced by CGUIInfoProviders(), and ~CGUIInfoProviders().
m_picturesGUIInfo
CPicturesGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_picturesGUIInfo private
Referenced by CGUIInfoProviders(), GetPicturesInfoProvider(), and ~CGUIInfoProviders().
m_playerGUIInfo
CPlayerGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_playerGUIInfo private
Referenced by CGUIInfoProviders(), GetPlayerInfoProvider(), and ~CGUIInfoProviders().
m_providers
std::vector<IGUIInfoProvider *> KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_providers private
Referenced by GetBool(), GetInt(), GetLabel(), InitCurrentItem(), RegisterProvider(), UnregisterProvider(), and UpdateAVInfo().
m_skinGUIInfo
CSkinGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_skinGUIInfo private
Referenced by CGUIInfoProviders(), and ~CGUIInfoProviders().
m_systemGUIInfo
CSystemGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_systemGUIInfo private
Referenced by CGUIInfoProviders(), GetSystemInfoProvider(), and ~CGUIInfoProviders().
m_videoGUIInfo
CVideoGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_videoGUIInfo private
Referenced by CGUIInfoProviders(), and ~CGUIInfoProviders().
m_visualisationGUIInfo
CVisualisationGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_visualisationGUIInfo private
Referenced by CGUIInfoProviders(), and ~CGUIInfoProviders().
m_weatherGUIInfo
CWeatherGUIInfo KODI::GUILIB::GUIINFO::CGUIInfoProviders::m_weatherGUIInfo private
Referenced by CGUIInfoProviders(), and ~CGUIInfoProviders().
The documentation for this class was generated from the following files:
GUIInfoProviders.h
GUIInfoProviders.cpp