Kodi Documentation: CDVDVideoPPFFmpeg Class Reference
CDVDVideoPPFFmpeg Class Reference
#include <DVDVideoPPFFmpeg.h>
Public Member Functions
CDVDVideoPPFFmpeg (CProcessInfo &processInfo)
~CDVDVideoPPFFmpeg ()
void SetType (const std::string &mType, bool deinterlace)
void Process (VideoPicture *pPicture)
Protected Member Functions
void Dispose ()
bool CheckInit (int iWidth, int iHeight)
bool CheckFrameBuffer (const VideoPicture *pSource)
Protected Attributes
std::string m_sType
CProcessInfo & m_processInfo
void * m_pContext
void * m_pMode
bool m_deinterlace
int m_iInitWidth
int m_iInitHeight
Constructor & Destructor Documentation
CDVDVideoPPFFmpeg()
CDVDVideoPPFFmpeg::CDVDVideoPPFFmpeg (CProcessInfo & processInfo) explicit
References m_deinterlace, m_iInitHeight, m_iInitWidth, m_pContext, and m_pMode.
~CDVDVideoPPFFmpeg()
CDVDVideoPPFFmpeg::~CDVDVideoPPFFmpeg ()
References Dispose().
Member Function Documentation
CheckFrameBuffer()
bool CDVDVideoPPFFmpeg::CheckFrameBuffer (const VideoPicture * pSource) protected
CheckInit()
bool CDVDVideoPPFFmpeg::CheckInit (int iWidth, int iHeight) protected
References Dispose(), m_iInitHeight, m_iInitWidth, m_pContext, m_pMode, m_sType, and PPCPUFlags().
Referenced by Process().
Dispose()
void CDVDVideoPPFFmpeg::Dispose () protected
References m_iInitHeight, m_iInitWidth, m_pContext, and m_pMode.
Referenced by CheckInit(), SetType(), and ~CDVDVideoPPFFmpeg().
Process()
void CDVDVideoPPFFmpeg::Process (VideoPicture * pPicture)
Bug:
libpostproc isn't const correct
References CheckInit(), CVideoBufferManager::Get(), CVideoBuffer::GetFormat(), CVideoBuffer::GetPlanes(), CVideoBuffer::GetStrides(), CProcessInfo::GetVideoBufferManager(), VideoPicture::iFlags, VideoPicture::iHeight, VideoPicture::iWidth, CLog::Log(), LOGERROR, m_deinterlace, m_pContext, m_pMode, m_processInfo, YuvImage::MAX_PLANES, VideoPicture::pict_type, VideoPicture::qp_table, VideoPicture::qscale_type, VideoPicture::qstride, CVideoBuffer::Release(), CVideoBuffer::SetDimensions(), VideoPicture::SetParams(), and VideoPicture::videoBuffer.
Referenced by CDVDVideoCodecFFmpeg::SetPictureParams().
SetType()
void CDVDVideoPPFFmpeg::SetType (const std::string & mType, bool deinterlace)
References Dispose(), m_deinterlace, m_pContext, m_pMode, and m_sType.
Referenced by CDVDVideoCodecFFmpeg::SetPictureParams().
Member Data Documentation
m_deinterlace
bool CDVDVideoPPFFmpeg::m_deinterlace protected
Referenced by CDVDVideoPPFFmpeg(), Process(), and SetType().
m_iInitHeight
int CDVDVideoPPFFmpeg::m_iInitHeight protected
Referenced by CDVDVideoPPFFmpeg(), CheckInit(), and Dispose().
m_iInitWidth
int CDVDVideoPPFFmpeg::m_iInitWidth protected
Referenced by CDVDVideoPPFFmpeg(), CheckInit(), and Dispose().
m_pContext
void* CDVDVideoPPFFmpeg::m_pContext protected
Referenced by CDVDVideoPPFFmpeg(), CheckInit(), Dispose(), Process(), and SetType().
m_pMode
void* CDVDVideoPPFFmpeg::m_pMode protected
Referenced by CDVDVideoPPFFmpeg(), CheckInit(), Dispose(), Process(), and SetType().
m_processInfo
CProcessInfo& CDVDVideoPPFFmpeg::m_processInfo protected
Referenced by Process().
m_sType
std::string CDVDVideoPPFFmpeg::m_sType protected
Referenced by CheckInit(), and SetType().
The documentation for this class was generated from the following files:
DVDVideoPPFFmpeg.h
DVDVideoPPFFmpeg.cpp