Kodi Documentation: CDNSNameCache Class Reference
CDNSNameCache Class Reference
#include <DNSNameCache.h>
Classes
class CDNSName
Public Member Functions
CDNSNameCache (void)
virtual ~CDNSNameCache (void)
Static Public Member Functions
static void Add (const std::string &strHostName, const std::string &strIpAddress)
static bool GetCached (const std::string &strHostName, std::string &strIpAddress)
static bool Lookup (const std::string &strHostName, std::string &strIpAddress)
Protected Attributes
std::vector< CDNSName > m_vecDNSNames
Static Protected Attributes
static CCriticalSection m_critical
Constructor & Destructor Documentation
CDNSNameCache()
CDNSNameCache::CDNSNameCache (void) default
~CDNSNameCache()
CDNSNameCache::~CDNSNameCache (void) virtual default
Member Function Documentation
Add()
void CDNSNameCache::Add (const std::string & strHostName, const std::string & strIpAddress) static
References g_DNSCache, m_critical, CDNSNameCache::CDNSName::m_strHostName, CDNSNameCache::CDNSName::m_strIpAddress, and m_vecDNSNames.
Referenced by Lookup(), and CAdvancedSettings::ParseSettingsFile().
GetCached()
bool CDNSNameCache::GetCached (const std::string & strHostName, std::string & strIpAddress) static
References g_DNSCache, WSDiscovery::CWSDiscoveryPosix::GetCached(), CServiceBroker::GetWSDiscovery(), WSDiscovery::CWSDiscoveryPosix::IsInitialized(), CLog::Log(), LOGDEBUG, LOGWSDISCOVERY, m_critical, and m_vecDNSNames.
Referenced by Lookup(), and XFILE::CCurlFile::ParseAndCorrectUrl().
Lookup()
bool CDNSNameCache::Lookup (const std::string & strHostName, std::string & strIpAddress) static
References Add(), g_DNSCache, GetCached(), CNetworkBase::GetIpStr(), CLog::Log(), and LOGERROR.
Referenced by dbiplus::MysqlDatabase::connect(), ADDON::Interface_Network::dns_lookup(), CZeroconfBrowserMDNS::doResolveService(), CSMB::GetResolvedUrl(), HostToIP(), URIUtils::IsHostOnLAN(), and CNfsConnection::resolveHost().
Member Data Documentation
m_critical
CCriticalSection CDNSNameCache::m_critical static protected
Referenced by Add(), and GetCached().
m_vecDNSNames
std::vector<CDNSName> CDNSNameCache::m_vecDNSNames protected
Referenced by Add(), and GetCached().
The documentation for this class was generated from the following files:
DNSNameCache.h
DNSNameCache.cpp