Kodi Documentation: KODI::RETRO::CRetroPlayerVideo Class Reference
KODI::RETRO::CRetroPlayerVideo Class Reference
Renders video frames provided by the game loop.
#include <RetroPlayerVideo.h>
Public Member Functions
CRetroPlayerVideo (CRPRenderManager &m_renderManager, CRPProcessInfo &m_processInfo)
~CRetroPlayerVideo () override
bool OpenStream (const StreamProperties &properties) override
Open a stream.
bool GetStreamBuffer (unsigned int width, unsigned int height, StreamBuffer &buffer) override
Get a buffer for zero-copy stream data.
void AddStreamData (const StreamPacket &packet) override
Add a data packet to a stream.
void CloseStream () override
Close the stream.
Public Member Functions inherited from KODI::RETRO::IRetroPlayerStream
virtual ~IRetroPlayerStream ()=default
Private Attributes
CRPRenderManager & m_renderManager
CRPProcessInfo & m_processInfo
bool m_bOpen = false
Detailed Description
Renders video frames provided by the game loop.
See also
CRPRenderManager
Constructor & Destructor Documentation
CRetroPlayerVideo()
CRetroPlayerVideo::CRetroPlayerVideo (CRPRenderManager & m_renderManager, CRPProcessInfo & m_processInfo)
References KODI::RETRO::CRPRenderManager::Initialize(), CLog::Log(), LOGDEBUG, and m_renderManager.
~CRetroPlayerVideo()
CRetroPlayerVideo::~CRetroPlayerVideo () override
References CloseStream(), KODI::RETRO::CRPRenderManager::Deinitialize(), CLog::Log(), LOGDEBUG, and m_renderManager.
Member Function Documentation
AddStreamData()
void CRetroPlayerVideo::AddStreamData (const StreamPacket & packet) override virtual
Add a data packet to a stream.
Parameters
packet The data packet
Implements KODI::RETRO::IRetroPlayerStream.
References KODI::RETRO::CRPRenderManager::AddFrame(), KODI::RETRO::VideoStreamPacket::data, KODI::RETRO::VideoStreamPacket::height, m_bOpen, m_renderManager, KODI::RETRO::VideoStreamPacket::rotation, KODI::RETRO::ROTATION_180_CCW, KODI::RETRO::ROTATION_270_CCW, KODI::RETRO::ROTATION_90_CCW, KODI::RETRO::VideoStreamPacket::size, and KODI::RETRO::VideoStreamPacket::width.
CloseStream()
void CRetroPlayerVideo::CloseStream () override virtual
Close the stream.
Implements KODI::RETRO::IRetroPlayerStream.
References KODI::RETRO::CRPRenderManager::Flush(), CLog::Log(), LOGDEBUG, m_bOpen, and m_renderManager.
Referenced by OpenStream(), and ~CRetroPlayerVideo().
GetStreamBuffer()
bool CRetroPlayerVideo::GetStreamBuffer (unsigned int width, unsigned int height, StreamBuffer & buffer) override virtual
Get a buffer for zero-copy stream data.
Parameters
width The framebuffer width, or 0 for no width specified
height The framebuffer height, or 0 for no height specified
[out] buffer The buffer, or unmodified if false is returned
Returns
True if a buffer was returned, false otherwise
Implements KODI::RETRO::IRetroPlayerStream.
References KODI::RETRO::CRPRenderManager::GetVideoBuffer(), m_bOpen, and m_renderManager.
OpenStream()
bool CRetroPlayerVideo::OpenStream (const StreamProperties & properties) override virtual
Open a stream.
Returns
True if the stream was opened, false otherwise
Implements KODI::RETRO::IRetroPlayerStream.
References CloseStream(), KODI::RETRO::CRPRenderManager::Configure(), CLog::Log(), LOGDEBUG, m_bOpen, m_processInfo, m_renderManager, KODI::RETRO::VideoStreamProperties::maxHeight, KODI::RETRO::VideoStreamProperties::maxWidth, KODI::RETRO::VideoStreamProperties::nominalHeight, KODI::RETRO::VideoStreamProperties::nominalWidth, KODI::RETRO::VideoStreamProperties::pixelAspectRatio, KODI::RETRO::VideoStreamProperties::pixfmt, KODI::RETRO::CRPProcessInfo::SetVideoDimensions(), KODI::RETRO::CRPProcessInfo::SetVideoPixelFormat(), and KODI::RETRO::CRenderTranslator::TranslatePixelFormat().
Referenced by KODI::GAME::CGameClientStreamVideo::OpenStream().
Member Data Documentation
m_bOpen
bool KODI::RETRO::CRetroPlayerVideo::m_bOpen = false private
Referenced by AddStreamData(), CloseStream(), GetStreamBuffer(), and OpenStream().
m_processInfo
CRPProcessInfo& KODI::RETRO::CRetroPlayerVideo::m_processInfo private
Referenced by OpenStream().
m_renderManager
CRPRenderManager& KODI::RETRO::CRetroPlayerVideo::m_renderManager private
Referenced by AddStreamData(), CloseStream(), CRetroPlayerVideo(), GetStreamBuffer(), OpenStream(), and ~CRetroPlayerVideo().
The documentation for this class was generated from the following files:
RetroPlayerVideo.h
RetroPlayerVideo.cpp