Kodi Documentation: XMLUtils Class Reference
XMLUtils Class Reference
#include <XMLUtils.h>
Static Public Member Functions
static bool HasChild (const TiXmlNode *pRootNode, const char *strTag)
static bool HasChild (const tinyxml2::XMLNode *rootNode, const char *tag)
static bool GetHex (const TiXmlNode *pRootNode, const char *strTag, uint32_t &dwHexValue)
static bool GetUInt (const TiXmlNode *pRootNode, const char *strTag, uint32_t &dwUIntValue)
static bool GetLong (const TiXmlNode *pRootNode, const char *strTag, long &lLongValue)
static bool GetFloat (const TiXmlNode *pRootNode, const char *strTag, float &value)
static bool GetDouble (const TiXmlNode *pRootNode, const char *strTag, double &value)
static bool GetInt (const TiXmlNode *pRootNode, const char *strTag, int &iIntValue)
static bool GetBoolean (const TiXmlNode *pRootNode, const char *strTag, bool &bBoolValue)
static bool GetHex (const tinyxml2::XMLNode *rootNode, const char *tag, uint32_t &value)
static bool GetUInt (const tinyxml2::XMLNode *rootNode, const char *tag, uint32_t &value)
static bool GetLong (const tinyxml2::XMLNode *rootNode, const char *tag, long &value)
static bool GetFloat (const tinyxml2::XMLNode *rootNode, const char *tag, float &value)
static bool GetDouble (const tinyxml2::XMLNode *rootNode, const char *tag, double &value)
static bool GetInt (const tinyxml2::XMLNode *rootNode, const char *tag, int &value)
static bool GetBoolean (const tinyxml2::XMLNode *rootNode, const char *tag, bool &value)
static bool GetString (const TiXmlNode *pRootNode, const char *strTag, std::string &strStringValue)
Get a string value from the xml tag If the specified tag isn't found strStringvalue is not modified and will contain whatever value it had before the method call.
static bool GetString (const tinyxml2::XMLNode *rootNode, const char *tag, std::string &value)
static std::string GetString (const TiXmlNode *pRootNode, const char *strTag)
Get a string value from the xml tag.
static std::string GetString (const tinyxml2::XMLNode *rootNode, const char *tag)
static bool GetAdditiveString (const TiXmlNode *rootNode, const char *tag, const std::string &separator, std::string &value, bool clear=false)
Get multiple tags, concatenating the values together. Transforms <tag>value1</tag> <tag clear="true">value2</tag> ... <tag>valuen</tag> into value2<sep>...<sep>valuen, appending it to the value string. Note that <value1> is overwritten by the clear="true" tag.
static bool GetStringArray (const TiXmlNode *rootNode, const char *tag, std::vector< std::string > &arrayValue, bool clear=false, const std::string &separator="")
static bool GetPath (const TiXmlNode *pRootNode, const char *strTag, std::string &strStringValue)
static bool GetFloat (const TiXmlNode *pRootNode, const char *strTag, float &value, const float min, const float max)
static bool GetUInt (const TiXmlNode *pRootNode, const char *strTag, uint32_t &dwUIntValue, const uint32_t min, const uint32_t max)
static bool GetInt (const TiXmlNode *pRootNode, const char *strTag, int &iIntValue, const int min, const int max)
static bool GetDate (const TiXmlNode *pRootNode, const char *strTag, CDateTime &date)
static bool GetDateTime (const TiXmlNode *pRootNode, const char *strTag, CDateTime &dateTime)
static bool GetAdditiveString (const tinyxml2::XMLNode *rootNode, const char *tag, const std::string &separator, std::string &value, bool clear=false)
static bool GetStringArray (const tinyxml2::XMLNode *rootNode, const char *tag, std::vector< std::string > &value, bool clear=false, const std::string &separator="")
static bool GetPath (const tinyxml2::XMLNode *rootNode, const char *tag, std::string &value)
static bool GetFloat (const tinyxml2::XMLNode *rootNode, const char *tag, float &value, const float min, const float max)
static bool GetUInt (const tinyxml2::XMLNode *rootNode, const char *tag, uint32_t &value, const uint32_t min, const uint32_t max)
static bool GetInt (const tinyxml2::XMLNode *rootNode, const char *tag, int &value, const int min, const int max)
static bool GetDate (const tinyxml2::XMLNode *rootNode, const char *tag, CDateTime &date)
static bool GetDateTime (const tinyxml2::XMLNode *rootNode, const char *tag, CDateTime &dateTime)
static std::string GetAttribute (const TiXmlElement *element, const char *tag)
Fetch a std::string copy of an attribute, if it exists. Cannot distinguish between empty and non-existent attributes.
static std::string GetAttribute (const tinyxml2::XMLElement *element, const char *tag)
static TiXmlNode * SetString (TiXmlNode *pRootNode, const char *strTag, const std::string &strValue)
static void SetAdditiveString (TiXmlNode *pRootNode, const char *strTag, const std::string &strSeparator, const std::string &strValue)
static void SetStringArray (TiXmlNode *pRootNode, const char *strTag, const std::vector< std::string > &arrayValue)
static TiXmlNode * SetInt (TiXmlNode *pRootNode, const char *strTag, int value)
static TiXmlNode * SetFloat (TiXmlNode *pRootNode, const char *strTag, float value)
static TiXmlNode * SetDouble (TiXmlNode *pRootNode, const char *strTag, double value)
static void SetBoolean (TiXmlNode *pRootNode, const char *strTag, bool value)
static void SetHex (TiXmlNode *pRootNode, const char *strTag, uint32_t value)
static void SetPath (TiXmlNode *pRootNode, const char *strTag, const std::string &strValue)
static void SetLong (TiXmlNode *pRootNode, const char *strTag, long iValue)
static void SetDate (TiXmlNode *pRootNode, const char *strTag, const CDateTime &date)
static void SetDateTime (TiXmlNode *pRootNode, const char *strTag, const CDateTime &dateTime)
static tinyxml2::XMLNode * SetString (tinyxml2::XMLNode *rootNode, const char *tag, const std::string &value)
static void SetAdditiveString (tinyxml2::XMLNode *rootNode, const char *tag, const std::string &separator, const std::string &value)
static void SetStringArray (tinyxml2::XMLNode *rootNode, const char *tag, const std::vector< std::string > &value)
static tinyxml2::XMLNode * SetInt (tinyxml2::XMLNode *rootNode, const char *tag, int value)
static tinyxml2::XMLNode * SetFloat (tinyxml2::XMLNode *rootNode, const char *tag, float value)
static tinyxml2::XMLNode * SetDouble (tinyxml2::XMLNode *rootNode, const char *tag, double value)
static void SetBoolean (tinyxml2::XMLNode *rootNode, const char *tag, bool value)
static void SetHex (tinyxml2::XMLNode *rootNode, const char *tag, uint32_t value)
static void SetPath (tinyxml2::XMLNode *rootNode, const char *tag, const std::string &value)
static void SetLong (tinyxml2::XMLNode *rootNode, const char *tag, long value)
static void SetDate (tinyxml2::XMLNode *rootNode, const char *tag, const CDateTime &date)
static void SetDateTime (tinyxml2::XMLNode *rootNode, const char *tag, const CDateTime &dateTime)
Static Public Attributes
static const int path_version = 1
Member Function Documentation
GetAdditiveString() [1/2]
bool XMLUtils::GetAdditiveString (const tinyxml2::XMLNode * rootNode, const char * tag, const std::string & separator, std::string & value, bool clear = false) static
References node, and value.
GetAdditiveString() [2/2]
bool XMLUtils::GetAdditiveString (const TiXmlNode * rootNode, const char * tag, const std::string & separator, std::string & value, bool clear = false) static
Get multiple tags, concatenating the values together. Transforms <tag>value1</tag> <tag clear="true">value2</tag> ... <tag>valuen</tag> into value2<sep>...<sep>valuen, appending it to the value string. Note that <value1> is overwritten by the clear="true" tag.
Parameters
rootNode the parent containing the <tag>'s.
tag the <tag> in question.
separator the separator to use when concatenating values.
value [out] the resulting string. Remains untouched if no <tag> is available, else is appended (or cleared based on the clear parameter).
clear if true, clears the string prior to adding tags, if tags are available. Defaults to false.
References node.
Referenced by TEST(), and TEST().
GetAttribute() [1/2]
std::string XMLUtils::GetAttribute (const tinyxml2::XMLElement * element, const char * tag) static
GetAttribute() [2/2]
std::string XMLUtils::GetAttribute (const TiXmlElement * element, const char * tag) static
Fetch a std::string copy of an attribute, if it exists. Cannot distinguish between empty and non-existent attributes.
Parameters
element the element to query.
tag the name of the attribute.
Returns
the attribute, if it exists, else an empty string
Referenced by CGUIStaticItem::CGUIStaticItem(), CAnimation::Create(), KODI::GAME::CPhysicalTopology::Deserialize(), KODI::GAME::CPhysicalPort::Deserialize(), KODI::GAME::CPhysicalFeature::Deserialize(), KODI::GAME::CControllerLayout::Deserialize(), ADDON::CSkinSetting::Deserialize(), KODI::GAME::CPortManager::DeserializeControllers(), KODI::GAME::CPortManager::DeserializePort(), KODI::GAME::CPortManager::DeserializePorts(), CGUIControlFactory::GetActions(), CAdvancedSettings::GetCustomTVRegexps(), XFILE::CLibraryDirectory::GetDirectory(), CGUIControlFactory::GetInfoLabelFromElement(), CGUIControlFactory::GetMovingSpeedConfig(), PERIPHERALS::CPeripherals::GetSettingsFromMappingsFile(), CGUIControlFactory::GetTexture(), CGUIControlFactory::GetType(), CPlayerSelectionRule::Initialize(), ADDON::CAddonSettings::InitializeFromOldSettingAction(), ADDON::CAddonSettings::InitializeFromOldSettingAddon(), ADDON::CAddonSettings::InitializeFromOldSettingEnums(), ADDON::CAddonSettings::InitializeFromOldSettingFileWithSource(), ADDON::CAddonSettings::InitializeFromOldSettingPath(), ADDON::CAddonSettings::InitializeFromOldSettingSelect(), ADDON::CAddonSettings::InitializeFromOldSettingSlider(), ADDON::CAddonSettings::InitializeFromOldSettingTextIpAddress(), CLangInfo::Load(), CPlayerCoreFactory::LoadConfiguration(), KODI::PLAYLIST::CPlayListASX::LoadData(), KODI::PLAYLIST::CPlayListB4S::LoadData(), KODI::PLAYLIST::CPlayListWPL::LoadData(), ADDON::LoadManifest(), PERIPHERALS::CPeripherals::LoadMappings(), PERIPHERALS::CPeripheral::LoadPersistedSettings(), XFILE::CLibraryDirectory::LoadXML(), CScraperUrl::ParseAndAppendUrl(), CScraperParser::ParseExpression(), ParseItemMRSS(), ParseItemRSS(), ParseItemVoddler(), ADDON::CAddonSettings::ParseOldSettingElement(), ADDON::CSkinInfo::ParseSetting(), CAdvancedSettings::ParseSettingsFile(), and CFanart::Unpack().
GetBoolean() [1/2]
bool XMLUtils::GetBoolean (const tinyxml2::XMLNode * rootNode, const char * tag, bool & value) static
References node, and value.
GetBoolean() [2/2]
bool XMLUtils::GetBoolean (const TiXmlNode * pRootNode, const char * strTag, bool & bBoolValue) static
Referenced by CGUIControlFactory::Create(), ISetting::Deserialize(), CSetting::Deserialize(), CSettingBool::Deserialize(), CSettingString::Deserialize(), CSettingControlEdit::Deserialize(), CSettingControlButton::Deserialize(), CSettingControlList::Deserialize(), CSettingControlSlider::Deserialize(), CSettingControlTitle::Deserialize(), CSettingPath::Deserialize(), CMediaSourceSettings::GetSource(), CVideoDatabase::ImportFromXML(), CExternalPlayer::Initialize(), CProfileManager::Load(), CDecoderFilter::Load(), CAlbum::Load(), CProfile::Load(), CApplicationVolumeHandling::Load(), CMediaSettings::Load(), CViewStateSettings::Load(), CAdvancedSettings::ParseSettingsFile(), TEST(), and TEST().
GetDate() [1/2]
bool XMLUtils::GetDate (const tinyxml2::XMLNode * rootNode, const char * tag, CDateTime & date) static
References GetString(), and CDateTime::SetFromDBDate().
GetDate() [2/2]
bool XMLUtils::GetDate (const TiXmlNode * pRootNode, const char * strTag, CDateTime & date) static
References GetString(), and CDateTime::SetFromDBDate().
Referenced by CVideoInfoTag::ParseNative(), TEST(), and TEST().
GetDateTime() [1/2]
bool XMLUtils::GetDateTime (const tinyxml2::XMLNode * rootNode, const char * tag, CDateTime & dateTime) static
References GetString(), and CDateTime::SetFromDBDateTime().
GetDateTime() [2/2]
bool XMLUtils::GetDateTime (const TiXmlNode * pRootNode, const char * strTag, CDateTime & dateTime) static
References GetString(), and CDateTime::SetFromDBDateTime().
Referenced by CVideoInfoTag::ParseNative(), TEST(), and TEST().
GetDouble() [1/2]
bool XMLUtils::GetDouble (const tinyxml2::XMLNode * rootNode, const char * tag, double & value) static
References node, and value.
GetDouble() [2/2]
bool XMLUtils::GetDouble (const TiXmlNode * pRootNode, const char * strTag, double & value) static
References node, root, and value.
Referenced by CSettingNumber::Deserialize(), CVideoInfoTag::ParseNative(), and TEST().
GetFloat() [1/4]
bool XMLUtils::GetFloat (const tinyxml2::XMLNode * rootNode, const char * tag, float & value) static
References node, and value.
GetFloat() [2/4]
bool XMLUtils::GetFloat (const tinyxml2::XMLNode * rootNode, const char * tag, float & value, const float min, const float max) static
References GetFloat(), max, min, and value.
GetFloat() [3/4]
bool XMLUtils::GetFloat (const TiXmlNode * pRootNode, const char * strTag, float & value) static
References value.
Referenced by CGUIControlFactory::Create(), GetFloat(), GetFloat(), CMusicDatabase::ImportSongHistory(), CAlbum::Load(), CApplicationVolumeHandling::Load(), CDisplaySettings::Load(), CMediaSettings::Load(), CGUIWindow::Load(), GUIFontManager::LoadFonts(), CVideoInfoTag::ParseNative(), CAdvancedSettings::ParseSettingsFile(), TEST(), and TEST().
GetFloat() [4/4]
bool XMLUtils::GetFloat (const TiXmlNode * pRootNode, const char * strTag, float & value, const float min, const float max) static
References GetFloat().
GetHex() [1/2]
bool XMLUtils::GetHex (const tinyxml2::XMLNode * rootNode, const char * tag, uint32_t & value) static
References node, and value.
GetHex() [2/2]
bool XMLUtils::GetHex (const TiXmlNode * pRootNode, const char * strTag, uint32_t & dwHexValue) static
Referenced by TEST(), and TEST().
GetInt() [1/4]
bool XMLUtils::GetInt (const tinyxml2::XMLNode * rootNode, const char * tag, int & value) static
References node, and value.
GetInt() [2/4]
bool XMLUtils::GetInt (const tinyxml2::XMLNode * rootNode, const char * tag, int & value, const int min, const int max) static
References GetInt(), max, min, and value.
GetInt() [3/4]
bool XMLUtils::GetInt (const TiXmlNode * pRootNode, const char * strTag, int & iIntValue) static
Referenced by CGUIControlFactory::Create(), CStaticListProvider::CStaticListProvider(), CSetting::Deserialize(), CSettingList::Deserialize(), CSettingInt::Deserialize(), CSettingControlFormattedRange::Deserialize(), CSettingControlEdit::Deserialize(), CSettingControlButton::Deserialize(), CSettingControlList::Deserialize(), CSettingControlSlider::Deserialize(), CSettingControlRange::Deserialize(), ADDON::CScraper::GetEpisodeList(), CGUIControlFactory::GetInfoLabels(), GetInt(), GetInt(), CVideoDatabase::ImportFromXML(), CMusicDatabase::ImportSongHistory(), CExternalPlayer::Initialize(), CProfileManager::Load(), CUPnPSettings::Load(), CDecoderFilter::Load(), CAlbum::Load(), CProfile::Load(), CDisplaySettings::Load(), CMediaSettings::Load(), CSysInfo::Load(), CViewStateSettings::Load(), GUIFontManager::LoadFonts(), CWakeOnAccess::LoadFromXML(), CVideoInfoTag::ParseNative(), CVideoInfoTag::CAssetInfo::ParseNative(), CAdvancedSettings::ParseSettingsFile(), TEST(), and TEST().
GetInt() [4/4]
bool XMLUtils::GetInt (const TiXmlNode * pRootNode, const char * strTag, int & iIntValue, const int min, const int max) static
References GetInt(), max, min, and value.
GetLong() [1/2]
bool XMLUtils::GetLong (const tinyxml2::XMLNode * rootNode, const char * tag, long & value) static
References node, and value.
GetLong() [2/2]
bool XMLUtils::GetLong (const TiXmlNode * pRootNode, const char * strTag, long & lLongValue) static
Referenced by TEST(), and TEST().
GetPath() [1/2]
bool XMLUtils::GetPath (const tinyxml2::XMLNode * rootNode, const char * tag, std::string & value) static
References node, and value.
GetPath() [2/2]
bool XMLUtils::GetPath (const TiXmlNode * pRootNode, const char * strTag, std::string & strStringValue) static
Referenced by XFILE::CLibraryDirectory::GetDirectory(), CPasswordManager::Load(), CProfile::Load(), CAdvancedSettings::ParseSettingsFile(), TEST(), and TEST().
GetString() [1/4]
std::string XMLUtils::GetString (const tinyxml2::XMLNode * rootNode, const char * tag) static
References GetString().
GetString() [2/4]
bool XMLUtils::GetString (const tinyxml2::XMLNode * rootNode, const char * tag, std::string & value) static
References node, and value.
GetString() [3/4]
std::string XMLUtils::GetString (const TiXmlNode * pRootNode, const char * strTag) static
Get a string value from the xml tag.
Parameters
[in] pRootNode the xml node that contains the tag
[in] strTag the tag to read from
Returns
the value in the specified tag or an empty string if the tag isn't found
References GetString().
GetString() [4/4]
bool XMLUtils::GetString (const TiXmlNode * pRootNode, const char * strTag, std::string & strStringValue) static
Get a string value from the xml tag If the specified tag isn't found strStringvalue is not modified and will contain whatever value it had before the method call.
Parameters
[in] pRootNode the xml node that contains the tag
[in] strTag the xml tag to read from
[in,out] strStringValue where to store the read string
Returns
true on success, false if the tag isn't found
Referenced by ADDON::CheckScraperError(), CGUIControlFactory::Create(), CSettingList::Deserialize(), CSettingString::Deserialize(), CSettingAction::Deserialize(), CSettingAddon::Deserialize(), CSettingControlFormattedRange::Deserialize(), CSettingControlButton::Deserialize(), CSettingControlSlider::Deserialize(), CSettingControlTitle::Deserialize(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), ADDON::CScraper::FindMovie(), CAdvancedSettings::GetCustomExtensions(), CExternalPlayer::GetCustomRegexpReplacers(), GetDate(), GetDate(), GetDateTime(), GetDateTime(), XFILE::CLibraryDirectory::GetDirectory(), ADDON::CScraper::GetEpisodeList(), KODI::PLAYLIST::GetString(), GetString(), GetString(), CGUIControlFactory::GetString(), GUIFontManager::GetStyle(), CGUIControlFactory::GetType(), CVideoDatabase::ImportFromXML(), CMusicDatabase::ImportSongHistory(), CExternalPlayer::Initialize(), CUPnPSettings::Load(), CDecoderFilter::Load(), CAlbum::Load(), CArtist::Load(), CProfile::Load(), CDisplaySettings::Load(), CMediaSettings::Load(), GUIFontManager::LoadFonts(), CWakeOnAccess::LoadFromXML(), KODI::PLAYLIST::CSmartPlaylist::LoadFromXML(), GUIFontManager::LoadUserFonts(), CVideoInfoTag::ParseNative(), CVideoInfoTag::CAssetInfo::ParseNative(), CAdvancedSettings::ParseSettingsFile(), CMediaManager::playStubFile(), KODI::PLAYLIST::CSmartPlaylist::readName(), TEST(), and TEST().
GetStringArray() [1/2]
bool XMLUtils::GetStringArray (const tinyxml2::XMLNode * rootNode, const char * tag, std::vector< std::string > & value, bool clear = false, const std::string & separator = "") static
References node, and value.
GetStringArray() [2/2]
bool XMLUtils::GetStringArray (const TiXmlNode * pRootNode, const char * strTag, std::vector< std::string > & arrayValue, bool clear = false, const std::string & separator = "") static
Parses the XML for multiple tags of the given name. Does not clear the array to support chaining.
References node.
Referenced by CAlbum::Load(), CArtist::Load(), CVideoInfoTag::ParseNative(), TEST(), and TEST().
GetUInt() [1/4]
bool XMLUtils::GetUInt (const tinyxml2::XMLNode * rootNode, const char * tag, uint32_t & value) static
References node, and value.
GetUInt() [2/4]
bool XMLUtils::GetUInt (const tinyxml2::XMLNode * rootNode, const char * tag, uint32_t & value, const uint32_t min, const uint32_t max) static
References GetUInt(), max, min, and value.
GetUInt() [3/4]
bool XMLUtils::GetUInt (const TiXmlNode * pRootNode, const char * strTag, uint32_t & dwUIntValue) static
Referenced by CGUIControlFactory::Create(), CGUIControlFactory::GetScroller(), GetUInt(), GetUInt(), CProfileManager::Load(), KODI::PLAYLIST::CSmartPlaylist::LoadFromXML(), CAdvancedSettings::ParseSettingsFile(), and TEST().
GetUInt() [4/4]
bool XMLUtils::GetUInt (const TiXmlNode * pRootNode, const char * strTag, uint32_t & dwUIntValue, const uint32_t min, const uint32_t max) static
References GetUInt(), max, min, and value.
HasChild() [1/2]
bool XMLUtils::HasChild (const tinyxml2::XMLNode * rootNode, const char * tag) static
References node.
HasChild() [2/2]
bool XMLUtils::HasChild (const TiXmlNode * pRootNode, const char * strTag) static
SetAdditiveString() [1/2]
void XMLUtils::SetAdditiveString (tinyxml2::XMLNode * rootNode, const char * tag, const std::string & separator, const std::string & value) static
References SetString(), and value.
SetAdditiveString() [2/2]
void XMLUtils::SetAdditiveString (TiXmlNode * pRootNode, const char * strTag, const std::string & strSeparator, const std::string & strValue) static
References SetString().
Referenced by TEST().
SetBoolean() [1/2]
void XMLUtils::SetBoolean (tinyxml2::XMLNode * rootNode, const char * tag, bool value) static
References SetString(), and value.
SetBoolean() [2/2]
void XMLUtils::SetBoolean (TiXmlNode * pRootNode, const char * strTag, bool value) static
References SetString(), and value.
Referenced by CVideoDatabase::ExportToXML(), CProfileManager::Save(), CDecoderFilter::Save(), CVideoInfoTag::Save(), CAlbum::Save(), CProfile::Save(), CApplicationVolumeHandling::Save(), CMediaSettings::Save(), CViewStateSettings::Save(), CMediaSourceSettings::SetSources(), and TEST().
SetDate() [1/2]
void XMLUtils::SetDate (tinyxml2::XMLNode * rootNode, const char * tag, const CDateTime & date) static
References CDateTime::GetAsDBDate(), CDateTime::IsValid(), and SetString().
SetDate() [2/2]
void XMLUtils::SetDate (TiXmlNode * pRootNode, const char * strTag, const CDateTime & date) static
References CDateTime::GetAsDBDate(), CDateTime::IsValid(), and SetString().
Referenced by CVideoInfoTag::Save(), and TEST().
SetDateTime() [1/2]
void XMLUtils::SetDateTime (tinyxml2::XMLNode * rootNode, const char * tag, const CDateTime & dateTime) static
References CDateTime::GetAsDBDateTime(), CDateTime::IsValid(), and SetString().
SetDateTime() [2/2]
void XMLUtils::SetDateTime (TiXmlNode * pRootNode, const char * strTag, const CDateTime & dateTime) static
References CDateTime::GetAsDBDateTime(), CDateTime::IsValid(), and SetString().
Referenced by CVideoInfoTag::Save(), and TEST().
SetDouble() [1/2]
tinyxml2::XMLNode * XMLUtils::SetDouble (tinyxml2::XMLNode * rootNode, const char * tag, double value) static
References SetString(), and value.
SetDouble() [2/2]
TiXmlNode * XMLUtils::SetDouble (TiXmlNode * pRootNode, const char * strTag, double value) static
References SetString(), and value.
Referenced by CVideoInfoTag::Save().
SetFloat() [1/2]
tinyxml2::XMLNode * XMLUtils::SetFloat (tinyxml2::XMLNode * rootNode, const char * tag, float value) static
References SetString(), and value.
SetFloat() [2/2]
TiXmlNode * XMLUtils::SetFloat (TiXmlNode * pRootNode, const char * strTag, float value) static
References SetString(), and value.
Referenced by CVideoInfoTag::Save(), CAlbum::Save(), CApplicationVolumeHandling::Save(), CDisplaySettings::Save(), CMediaSettings::Save(), and TEST().
SetHex() [1/2]
void XMLUtils::SetHex (tinyxml2::XMLNode * rootNode, const char * tag, uint32_t value) static
References SetString(), and value.
SetHex() [2/2]
void XMLUtils::SetHex (TiXmlNode * pRootNode, const char * strTag, uint32_t value) static
References SetString(), and value.
Referenced by TEST().
SetInt() [1/2]
tinyxml2::XMLNode * XMLUtils::SetInt (tinyxml2::XMLNode * rootNode, const char * tag, int value) static
References SetString(), and value.
SetInt() [2/2]
TiXmlNode * XMLUtils::SetInt (TiXmlNode * pRootNode, const char * strTag, int value) static
References SetString(), and value.
Referenced by CMusicDatabase::ExportSongHistory(), CVideoDatabase::ExportToXML(), CProfileManager::Save(), CUPnPSettings::Save(), KODI::PLAYLIST::CSmartPlaylist::Save(), CDecoderFilter::Save(), CVideoInfoTag::CAssetInfo::Save(), CVideoInfoTag::Save(), CAlbum::Save(), CProfile::Save(), CDisplaySettings::Save(), CMediaSettings::Save(), CSysInfo::Save(), CViewStateSettings::Save(), CWakeOnAccess::SaveToXML(), CMediaSourceSettings::SetSources(), and TEST().
SetLong() [1/2]
void XMLUtils::SetLong (tinyxml2::XMLNode * rootNode, const char * tag, long value) static
References SetString(), and value.
SetLong() [2/2]
void XMLUtils::SetLong (TiXmlNode * pRootNode, const char * strTag, long iValue) static
References SetString(), and value.
Referenced by TEST().
SetPath() [1/2]
void XMLUtils::SetPath (tinyxml2::XMLNode * rootNode, const char * tag, const std::string & value) static
References node, path_version, and value.
SetPath() [2/2]
void XMLUtils::SetPath (TiXmlNode * pRootNode, const char * strTag, const std::string & strValue) static
References path_version, and value.
Referenced by CPasswordManager::Save(), CProfile::Save(), CMediaSourceSettings::SetSources(), and TEST().
SetString() [1/2]
tinyxml2::XMLNode * XMLUtils::SetString (tinyxml2::XMLNode * rootNode, const char * tag, const std::string & value) static
References node, and value.
SetString() [2/2]
TiXmlNode * XMLUtils::SetString (TiXmlNode * pRootNode, const char * strTag, const std::string & strValue) static
References value.
Referenced by CMusicDatabase::ExportSongHistory(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), GUIFontManager::LoadUserFonts(), CUPnPSettings::Save(), KODI::PLAYLIST::CSmartPlaylist::Save(), CDecoderFilter::Save(), CVideoInfoTag::CAssetInfo::Save(), CVideoInfoTag::Save(), CAlbum::Save(), CArtist::Save(), CProfile::Save(), CDisplaySettings::Save(), CMediaSettings::Save(), CWakeOnAccess::SaveToXML(), SetAdditiveString(), SetAdditiveString(), SetBoolean(), SetBoolean(), SetDate(), SetDate(), SetDateTime(), SetDateTime(), SetDouble(), SetDouble(), SetFloat(), SetFloat(), SetHex(), SetHex(), SetInt(), SetInt(), SetLong(), SetLong(), CMediaSourceSettings::SetSources(), SetStringArray(), SetStringArray(), and TEST().
SetStringArray() [1/2]
void XMLUtils::SetStringArray (tinyxml2::XMLNode * rootNode, const char * tag, const std::vector< std::string > & value) static
References SetString(), and value.
SetStringArray() [2/2]
void XMLUtils::SetStringArray (TiXmlNode * pRootNode, const char * strTag, const std::vector< std::string > & arrayValue) static
References SetString().
Referenced by CVideoInfoTag::Save(), CAlbum::Save(), CArtist::Save(), and TEST().
Member Data Documentation
path_version
const int XMLUtils::path_version = 1 static
Referenced by SetPath(), and SetPath().
The documentation for this class was generated from the following files:
XMLUtils.h
XMLUtils.cpp