Kodi Documentation: GroupUtils Class Reference
GroupUtils Class Reference
#include <GroupUtils.h>
Static Public Member Functions
static bool Group (GroupBy groupBy, const std::string &baseDir, const CFileItemList &items, CFileItemList &groupedItems, GroupAttribute groupAttributes=GroupAttributeNone)
static bool Group (GroupBy groupBy, const std::string &baseDir, const CFileItemList &items, CFileItemList &groupedItems, CFileItemList &ungroupedItems, GroupAttribute groupAttributes=GroupAttributeNone)
static bool GroupAndMix (GroupBy groupBy, const std::string &baseDir, const CFileItemList &items, CFileItemList &groupedItemsMixed, GroupAttribute groupAttributes=GroupAttributeNone)
Member Function Documentation
Group() [1/2]
bool GroupUtils::Group (GroupBy groupBy, const std::string & baseDir, const CFileItemList & items, CFileItemList & groupedItems, CFileItemList & ungroupedItems, GroupAttribute groupAttributes = GroupAttributeNone) static
References CFileItemList::Add(), CDbUrl::AddOptions(), XFILE::CMultiPathDirectory::ConstructMultiPath(), CDbUrl::FromString(), CFileItemList::Get(), URIUtils::GetParentPath(), CVideoInfoTag::GetPlayCount(), CVideoInfoTag::GetRating(), CVideoInfoTag::GetResumePoint(), CVideoInfoTag::GetYear(), GroupAttributeIgnoreSingleItems, GroupByNone, GroupBySet, CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, index(), CBookmark::IsSet(), CDateTime::IsValid(), CVideoInfoTag::m_basePath, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_strPath, CVideoInfoTag::m_strPlot, CVideoInfoTag::m_strTitle, MediaTypeVideoCollection, CRating::rating, CVideoInfoTag::SetPlayCount(), CVideoInfoTag::SetYear(), CFileItemList::Size(), and CDbUrl::ToString().
Group() [2/2]
bool GroupUtils::Group (GroupBy groupBy, const std::string & baseDir, const CFileItemList & items, CFileItemList & groupedItems, GroupAttribute groupAttributes = GroupAttributeNone) static
References Group().
Referenced by CVideoDatabase::GetSetsByWhere(), Group(), and GroupAndMix().
GroupAndMix()
bool GroupUtils::GroupAndMix (GroupBy groupBy, const std::string & baseDir, const CFileItemList & items, CFileItemList & groupedItemsMixed, GroupAttribute groupAttributes = GroupAttributeNone) static
References CFileItemList::Append(), and Group().
Referenced by CGUIWindowVideoBase::GetGroupedItems().
The documentation for this class was generated from the following files:
GroupUtils.h
GroupUtils.cpp