Kodi Documentation: KODI::PIPEWIRE::CPipewireRegistry Class Reference
KODI::PIPEWIRE::CPipewireRegistry Class Reference
#include <PipewireRegistry.h>
Classes
struct PipewireRegistryDeleter
Public Member Functions
CPipewireRegistry (CPipewireCore &core)
CPipewireRegistry ()=delete
~CPipewireRegistry ()
pw_registry * Get () const
CPipewireCore & GetCore () const
std::map< uint32_t, std::unique_ptr< CPipewireGlobal > > & GetGlobals ()
Static Private Member Functions
static void OnGlobalAdded (void *userdata, uint32_t id, uint32_t permissions, const char *type, uint32_t version, const struct spa_dict *props)
static void OnGlobalRemoved (void *userdata, uint32_t id)
static pw_registry_events CreateRegistryEvents ()
Private Attributes
CPipewireCore & m_core
const pw_registry_events m_registryEvents
spa_hook m_registryListener
std::unique_ptr< pw_registry, PipewireRegistryDeleter > m_registry
std::map< uint32_t, std::unique_ptr< CPipewireGlobal > > m_globals
Constructor & Destructor Documentation
CPipewireRegistry() [1/2]
CPipewireRegistry::CPipewireRegistry (CPipewireCore & core) explicit
References KODI::PIPEWIRE::CPipewireCore::Get(), CLog::Log(), LOGERROR, m_registry, m_registryEvents, and m_registryListener.
CPipewireRegistry() [2/2]
KODI::PIPEWIRE::CPipewireRegistry::CPipewireRegistry () delete
~CPipewireRegistry()
CPipewireRegistry::~CPipewireRegistry () default
Member Function Documentation
CreateRegistryEvents()
pw_registry_events CPipewireRegistry::CreateRegistryEvents () static private
References OnGlobalAdded(), and OnGlobalRemoved().
Get()
pw_registry * KODI::PIPEWIRE::CPipewireRegistry::Get () const inline
References m_registry.
Referenced by KODI::PIPEWIRE::CPipewireProxy::CPipewireProxy().
GetCore()
CPipewireCore & KODI::PIPEWIRE::CPipewireRegistry::GetCore () const inline
References m_core.
Referenced by KODI::PIPEWIRE::CPipewireNode::Param().
GetGlobals()
std::map< uint32_t, std::unique_ptr< CPipewireGlobal > > & KODI::PIPEWIRE::CPipewireRegistry::GetGlobals () inline
References m_globals.
Referenced by OnGlobalRemoved().
OnGlobalAdded()
void CPipewireRegistry::OnGlobalAdded (void * userdata, uint32_t id, uint32_t permissions, const char * type, uint32_t version, const struct spa_dict * props) static private
References id, name, and node.
Referenced by CreateRegistryEvents().
OnGlobalRemoved()
void CPipewireRegistry::OnGlobalRemoved (void * userdata, uint32_t id) static private
References GetGlobals(), CLog::Log(), and LOGDEBUG.
Referenced by CreateRegistryEvents().
Member Data Documentation
m_core
CPipewireCore& KODI::PIPEWIRE::CPipewireRegistry::m_core private
Referenced by GetCore().
m_globals
std::map<uint32_t, std::unique_ptr<CPipewireGlobal> > KODI::PIPEWIRE::CPipewireRegistry::m_globals private
Referenced by GetGlobals().
m_registry
std::unique_ptr<pw_registry, PipewireRegistryDeleter> KODI::PIPEWIRE::CPipewireRegistry::m_registry private
Referenced by CPipewireRegistry(), and Get().
m_registryEvents
const pw_registry_events KODI::PIPEWIRE::CPipewireRegistry::m_registryEvents private
Referenced by CPipewireRegistry().
m_registryListener
spa_hook KODI::PIPEWIRE::CPipewireRegistry::m_registryListener private
Referenced by CPipewireRegistry().
The documentation for this class was generated from the following files:
PipewireRegistry.h
PipewireRegistry.cpp