Kodi Documentation: CRenderCaptureGL Class Reference
CRenderCaptureGL Class Reference
#include <RenderCaptureGL.h>
Public Member Functions
CRenderCaptureGL ()=default
~CRenderCaptureGL () override
void BeginRender () override
void EndRender () override
void ReadOut () override
void * GetRenderBuffer () override
Public Member Functions inherited from CRenderCapture
CRenderCapture ()=default
virtual ~CRenderCapture ()=default
void SetState (ECAPTURESTATE state)
ECAPTURESTATE GetState ()
void SetUserState (ECAPTURESTATE state)
ECAPTURESTATE GetUserState ()
CEvent & GetEvent ()
void SetFlags (int flags)
int GetFlags ()
void SetWidth (unsigned int width)
void SetHeight (unsigned int height)
unsigned int GetWidth ()
unsigned int GetHeight ()
uint8_t * GetPixels () const
bool IsAsync ()
Private Member Functions
void PboToBuffer ()
Private Attributes
GLuint m_pbo {0}
GLuint m_query {0}
bool m_occlusionQuerySupported {false}
Additional Inherited Members
Protected Member Functions inherited from CRenderCapture
bool UseOcclusionQuery ()
Protected Attributes inherited from CRenderCapture
ECAPTURESTATE m_state {CAPTURESTATE_FAILED}
ECAPTURESTATE m_userState {CAPTURESTATE_FAILED}
int m_flags {0}
CEvent m_event
uint8_t * m_pixels {nullptr}
unsigned int m_width {0}
unsigned int m_height {0}
unsigned int m_bufferSize {0}
bool m_asyncSupported {false}
bool m_asyncChecked {false}
Constructor & Destructor Documentation
CRenderCaptureGL()
CRenderCaptureGL::CRenderCaptureGL () default
~CRenderCaptureGL()
CRenderCaptureGL::~CRenderCaptureGL () override
References CRenderCapture::m_asyncSupported, m_pbo, CRenderCapture::m_pixels, and m_query.
Member Function Documentation
BeginRender()
void CRenderCaptureGL::BeginRender () override virtual
Implements CRenderCapture.
References CAPTUREFLAG_CONTINUOUS, CServiceBroker::GetRenderSystem(), CRenderSystemBase::GetRenderVersion(), CLog::Log(), LOGWARNING, CRenderCapture::m_asyncChecked, CRenderCapture::m_asyncSupported, CRenderCapture::m_bufferSize, CRenderCapture::m_flags, CRenderCapture::m_height, m_occlusionQuerySupported, m_pbo, CRenderCapture::m_pixels, m_query, CRenderCapture::m_width, and CRenderCapture::UseOcclusionQuery().
EndRender()
void CRenderCaptureGL::EndRender () override virtual
Implements CRenderCapture.
References CAPTUREFLAG_IMMEDIATELY, CAPTURESTATE_DONE, CAPTURESTATE_NEEDSREADOUT, CRenderCapture::m_asyncSupported, CRenderCapture::m_flags, m_query, PboToBuffer(), and CRenderCapture::SetState().
GetRenderBuffer()
void * CRenderCaptureGL::GetRenderBuffer () override virtual
Reimplemented from CRenderCapture.
References CRenderCapture::m_asyncSupported, and CRenderCapture::m_pixels.
PboToBuffer()
void CRenderCaptureGL::PboToBuffer () private
References CAPTURESTATE_DONE, CAPTURESTATE_FAILED, CLog::Log(), LOGERROR, CRenderCapture::m_bufferSize, m_pbo, CRenderCapture::m_pixels, and CRenderCapture::SetState().
Referenced by EndRender(), and ReadOut().
ReadOut()
void CRenderCaptureGL::ReadOut () override virtual
Reimplemented from CRenderCapture.
References CRenderCapture::m_asyncSupported, m_query, and PboToBuffer().
Member Data Documentation
m_occlusionQuerySupported
bool CRenderCaptureGL::m_occlusionQuerySupported {false} private
Referenced by BeginRender().
m_pbo
GLuint CRenderCaptureGL::m_pbo {0} private
Referenced by BeginRender(), PboToBuffer(), and ~CRenderCaptureGL().
m_query
GLuint CRenderCaptureGL::m_query {0} private
Referenced by BeginRender(), EndRender(), ReadOut(), and ~CRenderCaptureGL().
The documentation for this class was generated from the following files:
RenderCaptureGL.h
RenderCaptureGL.cpp