Kodi Documentation: PERIPHERALS::CPeripheralBusAddon Class Reference
PERIPHERALS::CPeripheralBusAddon Class Reference
#include <PeripheralBusAddon.h>
Public Member Functions
CPeripheralBusAddon (CPeripherals &manager)
~CPeripheralBusAddon (void) override
void UpdateAddons (void)
bool GetAddonWithButtonMap (PeripheralAddonPtr &addon) const
Get peripheral add-on that can provide button maps.
bool GetAddonWithButtonMap (const CPeripheral *device, PeripheralAddonPtr &addon) const
Get peripheral add-on that can provide button maps for the given device.
bool SendRumbleEvent (const std::string &strLocation, unsigned int motorIndex, float magnitude)
Set the rumble state of a rumble motor.
bool InitializeProperties (CPeripheral &peripheral) override
Initialize the properties of a peripheral with a known location.
void Register (const PeripheralPtr &peripheral) override
Register a new peripheral on this bus.
void GetFeatures (std::vector< PeripheralFeature > &features) const override
Get all features that are supported by devices on this bus.
bool HasFeature (const PeripheralFeature feature) const override
Check whether there is at least one device present with the given feature.
PeripheralPtr GetPeripheral (const std::string &strLocation) const override
Get the instance of the peripheral at the given location.
PeripheralPtr GetByPath (const std::string &strPath) const override
Get the instance of a peripheral given it's path.
bool SupportsFeature (PeripheralFeature feature) const override
Check if the bus supports the given feature.
unsigned int GetPeripheralsWithFeature (PeripheralVector &results, const PeripheralFeature feature) const override
Get all peripheral instances that have the given feature.
unsigned int GetNumberOfPeripherals (void) const override
unsigned int GetNumberOfPeripheralsWithId (const int iVendorId, const int iProductId) const override
void GetDirectory (const std::string &strPath, CFileItemList &items) const override
Get all fileitems for a path.
void ProcessEvents (void) override
Poll for events.
void EnableButtonMapping () override
Initialize button mapping.
void PowerOff (const std::string &strLocation) override
Power off the specified device.
bool SplitLocation (const std::string &strLocation, PeripheralAddonPtr &addon, unsigned int &peripheralIndex) const
Public Member Functions inherited from PERIPHERALS::CPeripheralBus
CPeripheralBus (const std::string &threadname, CPeripherals &manager, PeripheralBusType type)
~CPeripheralBus (void) override
PeripheralBusType Type (void) const
bool NeedsPolling (void) const
virtual bool InitializeButtonMap (const CPeripheral &peripheral, KODI::JOYSTICK::IButtonMap &buttonMap) const
Initialize a joystick buttonmap, if possible.
virtual bool HasPeripheral (const std::string &strLocation) const
Check whether a peripheral is present at the given location.
virtual void OnDeviceAdded (const std::string &strLocation)
Callback method for when a device has been added. Will perform a device scan.
virtual void OnDeviceChanged (const std::string &strLocation)
Callback method for when a device has been changed. Will perform a device scan.
virtual void OnDeviceRemoved (const std::string &strLocation)
Callback method for when a device has been removed. Will perform a device scan.
virtual void Initialise (void)
Initialise this bus and start a polling thread if this bus needs polling.
virtual void Clear (void)
Stop the polling thread and clear all known devices on this bus.
virtual void TriggerDeviceScan (void)
Scan for devices.
virtual bool FindComPort (std::string &strLocation)
Protected Member Functions
bool PerformDeviceScan (PeripheralScanResults &results) override
Scan for devices on this bus and add them to the results list. This will have to be implemented for each bus.
void UnregisterRemovedDevices (const PeripheralScanResults &results) override
Protected Member Functions inherited from PERIPHERALS::CPeripheralBus
void Process (void) override
virtual bool ScanForDevices (void)
virtual void RegisterNewDevices (const PeripheralScanResults &results)
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Member Functions
void OnEvent (const ADDON::AddonEvent &event)
void UnRegisterAddon (const std::string &addonId)
void PromptEnableAddons (const std::vector< std::shared_ptr< ADDON::CAddonInfo > > &disabledAddons)
Private Attributes
PeripheralAddonVector m_addons
PeripheralAddonVector m_failedAddons
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Attributes inherited from PERIPHERALS::CPeripheralBus
PeripheralVector m_peripherals
std::chrono::milliseconds m_iRescanTime
bool m_bNeedsPolling
CPeripherals & m_manager
const PeripheralBusType m_type
CCriticalSection m_critSection
CEvent m_triggerEvent
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CPeripheralBusAddon()
CPeripheralBusAddon::CPeripheralBusAddon (CPeripherals & manager) explicit
References ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), OnEvent(), and UpdateAddons().
~CPeripheralBusAddon()
CPeripheralBusAddon::~CPeripheralBusAddon (void) override
References PERIPHERALS::CPeripheralBus::Clear(), ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), m_addons, and m_failedAddons.
Member Function Documentation
EnableButtonMapping()
void CPeripheralBusAddon::EnableButtonMapping () override virtual
Initialize button mapping.
Returns
True if button mapping is enabled for this bus
Reimplemented from PERIPHERALS::CPeripheralBus.
References CServiceBroker::GetAddonMgr(), GetAddonWithButtonMap(), ADDON::CAddonMgr::GetDisabledAddonInfos(), PERIPHERALS::CPeripheralBus::m_critSection, and PromptEnableAddons().
GetAddonWithButtonMap() [1/2]
bool CPeripheralBusAddon::GetAddonWithButtonMap (const CPeripheral * device, PeripheralAddonPtr & addon) const
Get peripheral add-on that can provide button maps for the given device.
References PERIPHERALS::CPeripheral::GetBusType(), index(), PERIPHERALS::CPeripheral::Location(), CLog::Log(), LOGDEBUG, m_addons, PERIPHERALS::CPeripheralBus::m_critSection, PERIPHERALS::PERIPHERAL_BUS_ADDON, and SplitLocation().
GetAddonWithButtonMap() [2/2]
bool CPeripheralBusAddon::GetAddonWithButtonMap (PeripheralAddonPtr & addon) const
Get peripheral add-on that can provide button maps.
References m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
Referenced by EnableButtonMapping().
GetByPath()
PeripheralPtr CPeripheralBusAddon::GetByPath (const std::string & strPath) const override virtual
Get the instance of a peripheral given it's path.
Parameters
strPath The path to the peripheral.
Returns
The peripheral or NULL if it wasn't found.
Reimplemented from PERIPHERALS::CPeripheralBus.
References m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
GetDirectory()
void CPeripheralBusAddon::GetDirectory (const std::string & strPath, CFileItemList & items) const override virtual
Get all fileitems for a path.
Parameters
strPath The path to the directory to get the items from.
items The item list.
Reimplemented from PERIPHERALS::CPeripheralBus.
References m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
GetFeatures()
void CPeripheralBusAddon::GetFeatures (std::vector< PeripheralFeature > & features) const override virtual
Get all features that are supported by devices on this bus.
Parameters
features All features.
Reimplemented from PERIPHERALS::CPeripheralBus.
References m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
GetNumberOfPeripherals()
unsigned int CPeripheralBusAddon::GetNumberOfPeripherals (void) const override virtual
Reimplemented from PERIPHERALS::CPeripheralBus.
References m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
GetNumberOfPeripheralsWithId()
unsigned int CPeripheralBusAddon::GetNumberOfPeripheralsWithId (const int iVendorId, const int iProductId) const override virtual
Reimplemented from PERIPHERALS::CPeripheralBus.
References m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
GetPeripheral()
PeripheralPtr CPeripheralBusAddon::GetPeripheral (const std::string & strLocation) const override virtual
Get the instance of the peripheral at the given location.
Parameters
strLocation The location.
Returns
The peripheral or NULL if it wasn't found.
Reimplemented from PERIPHERALS::CPeripheralBus.
References PERIPHERALS::CPeripheralBus::m_critSection, and SplitLocation().
GetPeripheralsWithFeature()
unsigned int CPeripheralBusAddon::GetPeripheralsWithFeature (PeripheralVector & results, const PeripheralFeature feature) const override virtual
Get all peripheral instances that have the given feature.
Parameters
results The list of results.
feature The feature to search for.
Returns
The number of devices that have been found.
Reimplemented from PERIPHERALS::CPeripheralBus.
References m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
HasFeature()
bool CPeripheralBusAddon::HasFeature (const PeripheralFeature feature) const override virtual
Check whether there is at least one device present with the given feature.
Parameters
feature The feature to check for.
Returns
True when at least one device was found with this feature, false otherwise.
Reimplemented from PERIPHERALS::CPeripheralBus.
References m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
InitializeProperties()
bool CPeripheralBusAddon::InitializeProperties (CPeripheral & peripheral) override virtual
Initialize the properties of a peripheral with a known location.
Reimplemented from PERIPHERALS::CPeripheralBus.
References index(), PERIPHERALS::CPeripheralBus::InitializeProperties(), PERIPHERALS::CPeripheral::Location(), PERIPHERALS::PERIPHERAL_JOYSTICK, SplitLocation(), and PERIPHERALS::CPeripheral::Type().
OnEvent()
void CPeripheralBusAddon::OnEvent (const ADDON::AddonEvent & event) private
References ADDON::AddonEvent::addonId, CServiceBroker::GetAddonMgr(), ADDON::PERIPHERALDLL, UnRegisterAddon(), and UpdateAddons().
Referenced by CPeripheralBusAddon().
PerformDeviceScan()
bool CPeripheralBusAddon::PerformDeviceScan (PeripheralScanResults & results) override protected virtual
Scan for devices on this bus and add them to the results list. This will have to be implemented for each bus.
Parameters
results The result list.
Returns
True when the scan was successful, false otherwise.
Implements PERIPHERALS::CPeripheralBus.
References addons, m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
PowerOff()
void CPeripheralBusAddon::PowerOff (const std::string & strLocation) override virtual
Power off the specified device.
Parameters
strLocation The device's location
Reimplemented from PERIPHERALS::CPeripheralBus.
References SplitLocation().
ProcessEvents()
void CPeripheralBusAddon::ProcessEvents (void) override virtual
Poll for events.
Reimplemented from PERIPHERALS::CPeripheralBus.
References addons, m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
PromptEnableAddons()
void CPeripheralBusAddon::PromptEnableAddons (const std::vector< std::shared_ptr< ADDON::CAddonInfo > > & disabledAddons) private
References ADDON::CAddonMgr::EnableAddon(), CServiceBroker::GetAddonMgr(), and PERIPHERALS::CPeripheralAddon::ProvidesJoysticks().
Referenced by EnableButtonMapping().
Register()
void CPeripheralBusAddon::Register (const PeripheralPtr & peripheral) override virtual
Register a new peripheral on this bus.
Parameters
peripheral The peripheral to register.
Reimplemented from PERIPHERALS::CPeripheralBus.
References PERIPHERALS::CPeripheralBus::m_critSection, PERIPHERALS::CPeripheralBus::m_manager, PERIPHERALS::CPeripherals::OnDeviceAdded(), and SplitLocation().
SendRumbleEvent()
bool CPeripheralBusAddon::SendRumbleEvent (const std::string & strLocation, unsigned int motorIndex, float magnitude)
Set the rumble state of a rumble motor.
Parameters
strLocation The location of the peripheral with the motor
motorIndex The index of the motor being rumbled
magnitude The amount of vibration in the closed interval [0.0, 1.0]
Returns
true if the rumble motor's state is set, false otherwise
TODO: Move declaration to parent class
References SplitLocation().
Referenced by PERIPHERALS::CPeripheralJoystick::SetMotorState().
SplitLocation()
bool CPeripheralBusAddon::SplitLocation (const std::string & strLocation, PeripheralAddonPtr & addon, unsigned int & peripheralIndex) const
References m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
Referenced by GetAddonWithButtonMap(), PERIPHERALS::CPeripheral::GetIcon(), GetPeripheral(), InitializeProperties(), PowerOff(), Register(), and SendRumbleEvent().
SupportsFeature()
bool CPeripheralBusAddon::SupportsFeature (PeripheralFeature feature) const override virtual
Check if the bus supports the given feature.
Parameters
feature The feature to check for
Returns
True if the bus supports the feature, false otherwise
Reimplemented from PERIPHERALS::CPeripheralBus.
References m_addons, and PERIPHERALS::CPeripheralBus::m_critSection.
UnRegisterAddon()
void CPeripheralBusAddon::UnRegisterAddon (const std::string & addonId) private
References CLog::Log(), LOGDEBUG, m_addons, PERIPHERALS::CPeripheralBus::m_critSection, and m_failedAddons.
Referenced by OnEvent(), and UpdateAddons().
UnregisterRemovedDevices()
void CPeripheralBusAddon::UnregisterRemovedDevices (const PeripheralScanResults & results) override protected virtual
Reimplemented from PERIPHERALS::CPeripheralBus.
References m_addons, PERIPHERALS::CPeripheralBus::m_critSection, PERIPHERALS::CPeripheralBus::m_manager, and PERIPHERALS::CPeripherals::OnDeviceDeleted().
UpdateAddons()
void CPeripheralBusAddon::UpdateAddons (void)
References ADDON::CAddonMgr::GetAddonInfos(), CServiceBroker::GetAddonMgr(), CLog::Log(), LOGDEBUG, m_addons, PERIPHERALS::CPeripheralBus::m_critSection, m_failedAddons, PERIPHERALS::CPeripheralBus::m_manager, and UnRegisterAddon().
Referenced by CPeripheralBusAddon(), and OnEvent().
Member Data Documentation
m_addons
PeripheralAddonVector PERIPHERALS::CPeripheralBusAddon::m_addons private
Referenced by GetAddonWithButtonMap(), GetAddonWithButtonMap(), GetByPath(), GetDirectory(), GetFeatures(), GetNumberOfPeripherals(), GetNumberOfPeripheralsWithId(), GetPeripheralsWithFeature(), HasFeature(), PerformDeviceScan(), ProcessEvents(), SplitLocation(), SupportsFeature(), UnRegisterAddon(), UnregisterRemovedDevices(), UpdateAddons(), and ~CPeripheralBusAddon().
m_failedAddons
PeripheralAddonVector PERIPHERALS::CPeripheralBusAddon::m_failedAddons private
Referenced by UnRegisterAddon(), UpdateAddons(), and ~CPeripheralBusAddon().
The documentation for this class was generated from the following files:
PeripheralBusAddon.h
PeripheralBusAddon.cpp