Kodi Documentation: PVR::CPVRGUIActionsPowerManagement Class Reference
PVR::CPVRGUIActionsPowerManagement Class Reference
#include <PVRGUIActionsPowerManagement.h>
Public Member Functions
CPVRGUIActionsPowerManagement ()
~CPVRGUIActionsPowerManagement () override=default
bool CanSystemPowerdown (bool bAskUser=true) const
Check whether the system Kodi is running on can be powered down (shutdown/reboot/suspend/hibernate) without stopping any active recordings and/or without preventing the start of recordings scheduled for now + pvrpowermanagement.backendidletime.
Public Member Functions inherited from PVR::IPVRComponent
virtual ~IPVRComponent ()=default
Private Member Functions
CPVRGUIActionsPowerManagement (const CPVRGUIActionsPowerManagement &)=delete
CPVRGUIActionsPowerManagement const & operator= (CPVRGUIActionsPowerManagement const &)=delete
bool AllLocalBackendsIdle (std::shared_ptr< CPVRTimerInfoTag > &causingEvent) const
bool EventOccursOnLocalBackend (const std::shared_ptr< CPVRTimerInfoTag > &event) const
bool IsNextEventWithinBackendIdleTime () const
Private Attributes
CPVRSettings m_settings
Constructor & Destructor Documentation
CPVRGUIActionsPowerManagement() [1/2]
CPVRGUIActionsPowerManagement::CPVRGUIActionsPowerManagement ()
References CSettings::SETTING_PVRPOWERMANAGEMENT_BACKENDIDLETIME, and CSettings::SETTING_PVRPOWERMANAGEMENT_DAILYWAKEUPTIME.
~CPVRGUIActionsPowerManagement()
PVR::CPVRGUIActionsPowerManagement::~CPVRGUIActionsPowerManagement () override default
CPVRGUIActionsPowerManagement() [2/2]
PVR::CPVRGUIActionsPowerManagement::CPVRGUIActionsPowerManagement (const CPVRGUIActionsPowerManagement &) private delete
Member Function Documentation
AllLocalBackendsIdle()
bool CPVRGUIActionsPowerManagement::AllLocalBackendsIdle (std::shared_ptr< CPVRTimerInfoTag > & causingEvent) const private
References EventOccursOnLocalBackend(), CServiceBroker::GetPVRManager(), IsNextEventWithinBackendIdleTime(), and PVR::CPVRManager::Timers().
Referenced by CanSystemPowerdown().
CanSystemPowerdown()
bool CPVRGUIActionsPowerManagement::CanSystemPowerdown (bool bAskUser = true) const
Check whether the system Kodi is running on can be powered down (shutdown/reboot/suspend/hibernate) without stopping any active recordings and/or without preventing the start of recordings scheduled for now + pvrpowermanagement.backendidletime.
Parameters
bAskUser True to informs user in case of potential data loss. User can decide to allow powerdown anyway. False to not to ask user and to not confirm power down.
Returns
True if system can be safely powered down, false otherwise.
References AllLocalBackendsIdle(), g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetAsUTCDateTime(), CServiceBroker::GetPVRManager(), CDateTimeSpan::GetSecondsTotal(), PVR::CPVRSettings::GetStringValue(), CDateTime::GetUTCDateTime(), m_settings, CDateTime::SetFromDBTime(), CSettings::SETTING_PVRPOWERMANAGEMENT_DAILYWAKEUPTIME, KODI::MESSAGING::HELPERS::ShowYesNoDialogText(), and text.
Referenced by CApplication::OnAction(), and CGUIWindowLoginScreen::OnAction().
EventOccursOnLocalBackend()
bool CPVRGUIActionsPowerManagement::EventOccursOnLocalBackend (const std::shared_ptr< CPVRTimerInfoTag > & event) const private
References PVR::CPVRManager::GetClient(), CServiceBroker::GetNetwork(), CServiceBroker::GetPVRManager(), and CNetworkBase::IsLocalHost().
Referenced by AllLocalBackendsIdle().
IsNextEventWithinBackendIdleTime()
bool CPVRGUIActionsPowerManagement::IsNextEventWithinBackendIdleTime () const private
References PVR::CPVRSettings::GetIntValue(), CServiceBroker::GetPVRManager(), CDateTime::GetUTCDateTime(), m_settings, CSettings::SETTING_PVRPOWERMANAGEMENT_BACKENDIDLETIME, and PVR::Timers.
Referenced by AllLocalBackendsIdle().
operator=()
CPVRGUIActionsPowerManagement const & PVR::CPVRGUIActionsPowerManagement::operator= (CPVRGUIActionsPowerManagement const &) private delete
Member Data Documentation
m_settings
CPVRSettings PVR::CPVRGUIActionsPowerManagement::m_settings private
Referenced by CanSystemPowerdown(), and IsNextEventWithinBackendIdleTime().
The documentation for this class was generated from the following files:
PVRGUIActionsPowerManagement.h
PVRGUIActionsPowerManagement.cpp