Kodi Documentation: CGUIWindowMusicPlayList Class Reference
CGUIWindowMusicPlayList Class Reference
#include <GUIWindowMusicPlaylist.h>
Public Member Functions
CGUIWindowMusicPlayList (void)
~CGUIWindowMusicPlayList (void) override
bool OnMessage (CGUIMessage &message) override
Handle messages on window.
bool OnAction (const CAction &action) override
bool OnBack (int actionID) override
void RemovePlayListItem (int iItem)
void MoveItem (int iStart, int iDest)
Public Member Functions inherited from CGUIWindowMusicBase
CGUIWindowMusicBase (int id, const std::string &xmlFile)
~CGUIWindowMusicBase (void) override
void DoScan (const std::string &strPath, bool bRescan=false)
void RefreshContent (const std::string &strContent)
Public Member Functions inherited from CGUIMediaWindow
CGUIMediaWindow (int id, const char *xmlFile)
~CGUIMediaWindow (void) override
void OnWindowLoaded () override
void OnWindowUnload () override
bool IsMediaWindow () const override
int GetViewContainerID () const override
int GetViewCount () const override
bool HasListItems () const override
CFileItemPtr GetCurrentListItem (int offset=0) override
virtual bool CanFilterAdvanced ()
virtual bool IsFiltered ()
virtual bool IsSameStartFolder (const std::string &dir)
virtual std::string GetRootPath () const
const CFileItemList & CurrentDirectory () const
const CGUIViewState * GetViewState () const
virtual bool UseFileDirectories ()
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsDialog () const
virtual bool IsDialogRunning () const
virtual bool IsModalDialog () const
virtual bool IsSoundEnabled () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
virtual void OnDeinitWindow (int nextWindowID)
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Public Member Functions inherited from IBackgroundLoaderObserver
virtual ~IBackgroundLoaderObserver ()=default
Protected Member Functions
bool GoParentFolder () override
Go one directory up on list items.
void UpdateButtons () override
Overwrite to update your gui buttons (visible, enable,...)
void OnItemLoaded (CFileItem *pItem) override
bool Update (const std::string &strDirectory, bool updateFilterPath=true) override
Retrieves the items from the given path and updates the list.
void GetContextButtons (int itemNumber, CContextButtons &buttons) override
Will be called when an popup context menu has been asked for.
bool OnContextButton (int itemNumber, CONTEXT_BUTTON button) override
void OnMove (int iItem, int iAction)
bool OnPlayMedia (int iItem, const std::string &player="") override
On media play.
void SavePlayList ()
void ClearPlayList ()
void MarkPlaying ()
bool MoveCurrentPlayListItem (int iItem, int iAction, bool bUpdate=true)
Protected Member Functions inherited from CGUIWindowMusicBase
void OnInitWindow () override
Called on window open.
void GetNonContextButtons (CContextButtons &buttons)
bool OnAddMediaSource () override
bool GetDirectory (const std::string &strDirectory, CFileItemList &items) override
Overwrite to fill fileitems from a source.
virtual void OnRetrieveMusicInfo (CFileItemList &items)
Can be overwritten to implement an own tag filling function.
void OnPrepareFileItems (CFileItemList &items) override
On prepare file items.
void OnRipCD ()
std::string GetStartFolder (const std::string &dir) override
Translate the folder to start in from the given quick path.
virtual void OnScan (int iItem, bool bPromptRescan=false)
bool CheckFilterAdvanced (CFileItemList &items) const override
Check if the given list can be advance filtered or not.
bool CanContainFilter (const std::string &strDirectory) const override
Check if the given path can contain a "filter" parameter.
bool OnSelect (int iItem) override
virtual void PlayItem (int iItem)
void RetrieveMusicInfo ()
Retrieve tag information for m_vecItems.
void OnItemInfo (int iItem)
void OnItemInfoAll (const std::string &strPath, bool refresh=false)
virtual void OnQueueItem (int iItem, bool first=false)
Add selected list/thumb control item to playlist and start playing.
void OnRipTrack (int iItem)
void LoadPlayList (const std::string &strPlayList) override
virtual void OnRemoveSource (int iItem)
Protected Member Functions inherited from CGUIMediaWindow
CGUIControl * GetFirstFocusableControl (int id) override
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
virtual void SetupShares ()
virtual bool OnClick (int iItem, const std::string &player="")
On click.
virtual bool OnPopupMenu (int iItem)
virtual void FormatItemLabels (CFileItemList &items, const LABEL_MASKS &labelMasks)
Formats item labels.
void SaveControlStates () override
void RestoreControlStates () override
virtual bool Refresh (bool clearCache=false)
Refreshes the current list by retrieving the lists's path.
virtual void FormatAndSort (CFileItemList &items)
Format and sort file items.
virtual void OnCacheFileItems (CFileItemList &items)
On cache file items.
virtual void GetGroupedItems (CFileItemList &items)
void ClearFileItems ()
virtual void SortItems (CFileItemList &items)
Sort file items.
virtual void UpdateFilterPath (const std::string &strDirector, const CFileItemList &items, bool updateFilterPath)
virtual bool Filter (bool advanced=true)
void OnFilterItems (const std::string &filter)
virtual bool GetFilteredItems (const std::string &filter, CFileItemList &items)
virtual bool GetAdvanceFilteredItems (CFileItemList &items)
virtual bool HaveDiscOrConnection (const std::string &strPath, int iDriveType)
Check disc or connection present.
void ShowShareErrorMessage (CFileItem *pItem) const
Shows a standard error message for a given pItem.
void SaveSelectedItemInHistory ()
void RestoreSelectedItemFromHistory ()
void GetDirectoryHistoryString (const CFileItem *pItem, std::string &strHistoryString) const
Get history string for given file item.
void SetHistoryForPath (const std::string &strDirectory)
Set history for path.
virtual bool OnPlayAndQueueMedia (const CFileItemPtr &item, const std::string &player="")
On play and media queue.
void UpdateFileList ()
Update file list.
virtual void OnDeleteItem (int iItem)
void OnRenameItem (int iItem)
bool WaitForNetwork () const
bool GetDirectoryItems (CURL &url, CFileItemList &items, bool useDir)
bool WaitGetDirectoryItems (CGetDirectoryItems &items)
void CancelUpdateItems ()
bool ProcessRenderLoop (bool renderOnly)
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void SetDefaults ()
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
int m_movingFrom
std::vector< CMediaSource > m_shares
Protected Attributes inherited from CGUIWindowMusicBase
CGUIDialogProgress * m_dlgProgress
Progress dialog.
CMusicDatabase m_musicdatabase
MUSIC_INFO::CMusicInfoLoader m_musicInfoLoader
CMusicThumbLoader m_thumbLoader
Protected Attributes inherited from CGUIMediaWindow
XFILE::CVirtualDirectory m_rootDir
CGUIViewControl m_viewControl
CFileItemList * m_vecItems
CFileItemList * m_unfilteredItems
items prior to filtering using FilterItems()
CDirectoryHistory m_history
std::unique_ptr< CGUIViewState > m_guiState
std::atomic_bool m_vecItemsUpdating = {false}
CEvent m_updateEvent
std::atomic_bool m_updateAborted = {false}
std::atomic_bool m_updateJobActive = {false}
int m_iLastControl
std::string m_startDirectory
KODI::PLAYLIST::CSmartPlaylist m_filter
bool m_canFilterAdvanced
std::string m_strFilterPath
Contains the path used for filtering (including any active filter)
bool m_backgroundLoad = false
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Static Public Member Functions inherited from CGUIWindowMusicBase
static void OnAssignContent (const std::string &oldName, const CMediaSource &source)
Once a music source is added, store source in library, and prompt the user to scan this folder into the library.
Protected Types inherited from CGUIWindowMusicBase
enum ALLOW_SELECTION { SELECTION_ALLOWED = 0 , SELECTION_AUTO , SELECTION_FORCED }
typedef std::vector< CFileItem * >::iterator ivecItems
CFileItem* vector Iterator.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Member Functions inherited from CGUIMediaWindow
static std::string RemoveParameterFromPath (const std::string &strDirectory, const std::string &strParameter)
Utility method to remove the given parameter from a path/URL.
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIWindowMusicPlayList()
CGUIWindowMusicPlayList::CGUIWindowMusicPlayList (void)
References m_movingFrom, CGUIWindowMusicBase::m_musicInfoLoader, and CBackgroundInfoLoader::SetObserver().
~CGUIWindowMusicPlayList()
CGUIWindowMusicPlayList::~CGUIWindowMusicPlayList (void) override default
Member Function Documentation
ClearPlayList()
void CGUIWindowMusicPlayList::ClearPlayList () protected
References CGUIMediaWindow::ClearFileItems(), KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist(), CONTROL_BTNVIEWASICONS, CServiceBroker::GetPlaylistPlayer(), CGUIMediaWindow::Refresh(), KODI::PLAYLIST::CPlayListPlayer::Reset(), SET_CONTROL_FOCUS, and KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist().
Referenced by OnMessage().
GetContextButtons()
void CGUIWindowMusicPlayList::GetContextButtons (int itemNumber, CContextButtons & buttons) override protected virtual
Will be called when an popup context menu has been asked for.
Parameters
itemNumber List/thumb control item that has been clicked on
Todo:
get rid of IsAddonsPath and IsScript check. CanQueue should be enough!
Reimplemented from CGUIWindowMusicBase.
References CContextButtons::Add(), CONTEXT_BUTTON_CANCEL_MOVE, CONTEXT_BUTTON_CANCEL_PARTYMODE, CONTEXT_BUTTON_DELETE, CONTEXT_BUTTON_EDIT_PARTYMODE, CONTEXT_BUTTON_MOVE_HERE, CONTEXT_BUTTON_MOVE_ITEM, CONTEXT_BUTTON_MOVE_ITEM_DOWN, CONTEXT_BUTTON_MOVE_ITEM_UP, g_partyModeManager, CFileItemList::Get(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), CServiceBroker::GetPlaylistPlayer(), CPartyModeManager::IsEnabled(), m_movingFrom, CGUIMediaWindow::m_vecItems, and CFileItemList::Size().
GoParentFolder()
bool CGUIWindowMusicPlayList::GoParentFolder () inline override protected virtual
Go one directory up on list items.
The function goes up one level in the directory tree
Reimplemented from CGUIMediaWindow.
MarkPlaying()
void CGUIWindowMusicPlayList::MarkPlaying () protected
Referenced by OnMessage(), and UpdateButtons().
MoveCurrentPlayListItem()
bool CGUIWindowMusicPlayList::MoveCurrentPlayListItem (int iItem, int iAction, bool bUpdate = true) protected
References ACTION_MOVE_ITEM_UP, CServiceBroker::GetAppComponents(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), playlist, CGUIMediaWindow::Refresh(), and KODI::PLAYLIST::CPlayListPlayer::SetCurrentItemIdx().
Referenced by MoveItem(), and OnMove().
MoveItem()
void CGUIWindowMusicPlayList::MoveItem (int iStart, int iDest)
References ACTION_MOVE_ITEM_DOWN, ACTION_MOVE_ITEM_UP, CBackgroundInfoLoader::IsLoading(), CBackgroundInfoLoader::Load(), CGUIWindowMusicBase::m_musicInfoLoader, CGUIMediaWindow::m_vecItems, MoveCurrentPlayListItem(), CGUIMediaWindow::Refresh(), CFileItemList::Size(), and CBackgroundInfoLoader::StopThread().
Referenced by OnContextButton().
OnAction()
bool CGUIWindowMusicPlayList::OnAction (const CAction & action) override virtual
Reimplemented from CGUIWindowMusicBase.
References ACTION_MOVE_ITEM_DOWN, ACTION_MOVE_ITEM_UP, ACTION_PARENT_DIR, ACTION_SHOW_PLAYLIST, CGUIControlGroup::GetFocusedControlID(), CServiceBroker::GetGUI(), CGUIViewControl::GetSelectedItem(), CGUIComponent::GetWindowManager(), CGUIViewControl::HasControl(), CGUIMediaWindow::m_viewControl, CGUIWindowMusicBase::OnAction(), OnMove(), and CGUIWindowManager::PreviousWindow().
OnBack()
bool CGUIWindowMusicPlayList::OnBack (int actionID) override virtual
Reimplemented from CGUIWindowMusicBase.
References ACTION_NAV_BACK, CGUIMediaWindow::CancelUpdateItems(), and CGUIControl::OnBack().
OnContextButton()
bool CGUIWindowMusicPlayList::OnContextButton (int itemNumber, CONTEXT_BUTTON button) override protected virtual
Reimplemented from CGUIWindowMusicBase.
References ACTION_MOVE_ITEM_DOWN, ACTION_MOVE_ITEM_UP, CONTEXT_BUTTON_CANCEL_MOVE, CONTEXT_BUTTON_CANCEL_PARTYMODE, CONTEXT_BUTTON_DELETE, CONTEXT_BUTTON_EDIT_PARTYMODE, CONTEXT_BUTTON_MOVE_HERE, CONTEXT_BUTTON_MOVE_ITEM, CONTEXT_BUTTON_MOVE_ITEM_DOWN, CONTEXT_BUTTON_MOVE_ITEM_UP, CPartyModeManager::Disable(), CGUIDialogSmartPlaylistEditor::EditPlaylist(), CPartyModeManager::Enable(), g_partyModeManager, CServiceBroker::GetSettingsComponent(), m_movingFrom, MoveItem(), CGUIWindowMusicBase::OnContextButton(), OnMove(), playlist, and RemovePlayListItem().
OnItemLoaded()
void CGUIWindowMusicPlayList::OnItemLoaded (CFileItem * pItem) override protected virtual
Reimplemented from CGUIWindowMusicBase.
References CLabelFormatter::FormatLabels(), MUSIC_INFO::CMusicInfoTag::GetDuration(), CGUIListItem::GetLabel(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), CUtil::GetTitleFromPath(), CFileItem::HasMusicInfoTag(), MUSIC_INFO::CMusicInfoTag::Loaded(), CFileItem::m_iprogramCount, CFileItem::SetLabel(), CGUIListItem::SetLabel2(), CSettings::SETTING_MUSICFILES_NOWPLAYINGTRACKFORMAT, and CSettings::SETTING_MUSICFILES_TRACKFORMAT.
OnMessage()
bool CGUIWindowMusicPlayList::OnMessage (CGUIMessage & message) override virtual
Handle messages on window.
Parameters
message GUI Message that can be reacted on.
Returns
if a message can't be processed, return false
On these messages this class reacts.
When retrieving...
GUI_MSG_WINDOW_DEINIT
...the last focused control is saved to m_iLastControl.
GUI_MSG_WINDOW_INIT
...the musicdatabase is opend and the music extensions and shares are set. The last focused control is set.
GUI_MSG_CLICKED
... the base class reacts on the following controls:
Buttons:
CONTROL_BTNVIEWASICONS - switch between list, thumb and with large items
CONTROL_BTNSEARCH - Search for items
Other Controls:
The container controls
Have the following actions in message them clicking on them.
ACTION_QUEUE_ITEM - add selected item to end of playlist
ACTION_QUEUE_ITEM_NEXT - add selected item to next pos in playlist
ACTION_SHOW_INFO - retrieve album info from the internet
ACTION_SELECT_ITEM - Item has been selected. Overwrite OnClick() to react on it
Reimplemented from CGUIWindowMusicBase.
References ACTION_DELETE_ITEM, ACTION_MOUSE_MIDDLE_CLICK, ClearPlayList(), CONTROL_BTNCLEAR, CONTROL_BTNNEXT, CONTROL_BTNPLAY, CONTROL_BTNPREVIOUS, CONTROL_BTNREPEAT, CONTROL_BTNSAVE, CONTROL_BTNSHUFFLE, CONTROL_BTNVIEWASICONS, g_partyModeManager, CServiceBroker::GetAppComponents(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CMediaSettings::GetInstance(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CServiceBroker::GetPlaylistPlayer(), KODI::PLAYLIST::CPlayListPlayer::GetRepeat(), CGUIViewControl::GetSelectedItem(), CGUIMessage::GetSenderId(), CServiceBroker::GetSettingsComponent(), GUI_MSG_CLICKED, GUI_MSG_PLAYLIST_CHANGED, GUI_MSG_PLAYLISTPLAYER_RANDOM, GUI_MSG_PLAYLISTPLAYER_REPEAT, GUI_MSG_WINDOW_DEINIT, GUI_MSG_WINDOW_INIT, CGUIViewControl::HasControl(), CPartyModeManager::IsEnabled(), CBackgroundInfoLoader::IsLoading(), CLog::Log(), LOGWARNING, CGUIMediaWindow::m_guiState, CGUIMediaWindow::m_iLastControl, m_movingFrom, CGUIWindowMusicBase::m_musicInfoLoader, CGUIMediaWindow::m_vecItems, CGUIMediaWindow::m_vecItemsUpdating, CGUIMediaWindow::m_viewControl, MarkPlaying(), CGUIWindowMusicBase::OnMessage(), KODI::PLAYLIST::CPlayListPlayer::Play(), KODI::PLAYLIST::CPlayListPlayer::PlayNext(), KODI::PLAYLIST::CPlayListPlayer::PlayPrevious(), CGUIMediaWindow::Refresh(), RemovePlayListItem(), KODI::PLAYLIST::CPlayListPlayer::Reset(), SavePlayList(), SET_CONTROL_FOCUS, KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), CMediaSettings::SetMusicPlaylistRepeat(), CMediaSettings::SetMusicPlaylistShuffled(), CFileItem::SetPath(), KODI::PLAYLIST::CPlayListPlayer::SetRepeat(), CGUIViewControl::SetSelectedItem(), KODI::PLAYLIST::CPlayListPlayer::SetShuffle(), CFileItemList::Size(), CBackgroundInfoLoader::StopThread(), UpdateButtons(), and MUSIC_INFO::CMusicInfoLoader::UseCacheOnHD().
OnMove()
void CGUIWindowMusicPlayList::OnMove (int iItem, int iAction) protected
References CBackgroundInfoLoader::IsLoading(), CBackgroundInfoLoader::Load(), CGUIWindowMusicBase::m_musicInfoLoader, CGUIMediaWindow::m_vecItems, MoveCurrentPlayListItem(), CFileItemList::Size(), and CBackgroundInfoLoader::StopThread().
Referenced by OnAction(), and OnContextButton().
OnPlayMedia()
bool CGUIWindowMusicPlayList::OnPlayMedia (int iItem, const std::string & player = "") override protected virtual
On media play.
Note
Override if you want to change the default behavior, what is done when the user clicks on a file.
This function is called by OnClick()
Todo:
Should the playlist be cleared if nothing is already playing?
Reimplemented from CGUIWindowMusicBase.
References g_application, g_partyModeManager, CFileItemList::Get(), CFileItem::GetPath(), CServiceBroker::GetPlaylistPlayer(), CPartyModeManager::IsEnabled(), CGUIMediaWindow::m_guiState, CGUIMediaWindow::m_vecItems, KODI::PLAYLIST::CPlayListPlayer::Play(), CPartyModeManager::Play(), KODI::PLAYLIST::CPlayListPlayer::Reset(), and KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist().
RemovePlayListItem()
void CGUIWindowMusicPlayList::RemovePlayListItem (int iItem)
References CONTROL_BTNVIEWASICONS, g_partyModeManager, CServiceBroker::GetAppComponents(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CServiceBroker::GetPlaylistPlayer(), CGUIMediaWindow::m_vecItems, CGUIMediaWindow::m_viewControl, CPartyModeManager::OnSongChange(), CGUIMediaWindow::Refresh(), KODI::PLAYLIST::CPlayListPlayer::Remove(), SET_CONTROL_FOCUS, CGUIViewControl::SetSelectedItem(), and CFileItemList::Size().
Referenced by OnContextButton(), and OnMessage().
SavePlayList()
void CGUIWindowMusicPlayList::SavePlayList () protected
References URIUtils::AddFileToFolder(), g_localizeStrings, CFileItemList::Get(), CLocalizeStrings::Get(), CGUIMediaWindow::GetDirectoryHistoryString(), CFileItem::GetPath(), CGUIViewControl::GetSelectedItem(), CServiceBroker::GetSettingsComponent(), KODI::MUSIC::IsMusicDb(), CLog::Log(), LOGDEBUG, CGUIMediaWindow::m_history, CGUIMediaWindow::m_vecItems, CGUIMediaWindow::m_viewControl, CUtil::MakeLegalFileName(), playlist, CGUIMediaWindow::Refresh(), CDirectoryHistory::SetSelectedItem(), CSettings::SETTING_SYSTEM_PLAYLISTSPATH, CGUIKeyboardFactory::ShowAndGetInput(), and CFileItemList::Size().
Referenced by OnMessage().
Update()
bool CGUIWindowMusicPlayList::Update (const std::string & strDirectory, bool updateFilterPath = true) override protected virtual
Retrieves the items from the given path and updates the list.
Parameters
strDirectory The path to the directory to get the items from
updateFilterPath Whether to update the filter path in m_strFilterPath or not
Returns
true if the list was successfully updated otherwise false
See also
GetDirectory
m_vecItems
m_strFilterPath
Todo:
OnInitWindow calls Update() before window path has been set properly.
Reimplemented from CGUIMediaWindow.
References CFileItemList::GetContent(), CBackgroundInfoLoader::IsLoading(), CBackgroundInfoLoader::Load(), CGUIWindowMusicBase::m_musicInfoLoader, CGUIMediaWindow::m_vecItems, CFileItemList::SetContent(), CBackgroundInfoLoader::StopThread(), and CGUIMediaWindow::Update().
UpdateButtons()
void CGUIWindowMusicPlayList::UpdateButtons () override protected virtual
Overwrite to update your gui buttons (visible, enable,...)
Reimplemented from CGUIWindowMusicBase.
References CONTROL_BTNCLEAR, CONTROL_BTNNEXT, CONTROL_BTNPLAY, CONTROL_BTNPREVIOUS, CONTROL_BTNREPEAT, CONTROL_BTNSAVE, CONTROL_BTNSHUFFLE, CONTROL_DESELECT, CONTROL_DISABLE, CONTROL_ENABLE, CONTROL_LABELFILES, CONTROL_SELECT, g_localizeStrings, g_partyModeManager, CLocalizeStrings::Get(), CServiceBroker::GetAppComponents(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CFileItemList::GetObjectCount(), CServiceBroker::GetPlaylistPlayer(), KODI::PLAYLIST::CPlayListPlayer::GetRepeat(), CPartyModeManager::IsEnabled(), CGUIMediaWindow::m_vecItems, MarkPlaying(), SET_CONTROL_LABEL, CFileItemList::Size(), and CGUIWindowMusicBase::UpdateButtons().
Referenced by OnMessage().
Member Data Documentation
m_movingFrom
int CGUIWindowMusicPlayList::m_movingFrom protected
Referenced by CGUIWindowMusicPlayList(), GetContextButtons(), OnContextButton(), and OnMessage().
m_shares
std::vector<CMediaSource> CGUIWindowMusicPlayList::m_shares protected
The documentation for this class was generated from the following files:
GUIWindowMusicPlaylist.h
GUIWindowMusicPlaylist.cpp