Kodi Documentation: CPlatformAndroid Class Reference
CPlatformAndroid Class Reference
#include <PlatformAndroid.h>
Public Member Functions
CPlatformAndroid ()=default
C'tor.
~CPlatformAndroid () override=default
D'tor.
bool InitStageOne () override
Called at an early stage of application startup.
bool InitStageThree () override
Called at a late stage of application startup.
void PlatformSyslog () override
Print platform specific info to log.
Public Member Functions inherited from CPlatformPosix
bool InitStageOne () override
Called at an early stage of application startup.
Public Member Functions inherited from CPlatform
CPlatform ()=default
C'tor.
virtual ~CPlatform ()=default
D'tor.
virtual bool InitStageTwo ()
Called at a middle stage of application startup.
virtual void DeinitStageOne ()
Called at a late stage of application shutdown.
virtual void DeinitStageTwo ()
Called at a middle stage of application shutdown.
virtual void DeinitStageThree ()
Called at an early stage of application shutdown.
virtual bool IsConfigureAddonsAtStartupEnabled ()
Flag whether disabled add-ons - installed via packagemanager or manually - should be offered for configuration and activation on kodi startup for this platform.
virtual bool SupportsUserInstalledBinaryAddons ()
Flag whether this platform supports user installation of binary add-ons.
template<class T >
std::shared_ptr< T > GetService ()
Get a platform service instance.
Public Member Functions inherited from CComponentContainer< IPlatformService >
std::shared_ptr< T > GetComponent ()
Obtain a component.
std::shared_ptr< const T > GetComponent () const
Obtain a component.
std::size_t size () const
Returns number of registered components.
Additional Inherited Members
Static Public Member Functions inherited from CPlatformPosix
static bool TestQuitFlag ()
static void RequestQuit ()
Static Public Member Functions inherited from CPlatform
static CPlatform * CreateInstance ()
Creates the Platform object.
Protected Member Functions inherited from CComponentContainer< IPlatformService >
void RegisterComponent (const std::shared_ptr< IPlatformService > &component)
Register a new component instance.
void DeregisterComponent (const std::type_info &typeInfo)
Deregister a component.
Constructor & Destructor Documentation
CPlatformAndroid()
CPlatformAndroid::CPlatformAndroid () default
C'tor.
~CPlatformAndroid()
CPlatformAndroid::~CPlatformAndroid () override default
D'tor.
Member Function Documentation
InitStageOne()
bool CPlatformAndroid::InitStageOne () override virtual
Called at an early stage of application startup.
This method can be used to do platform specific environment preparation or initialisation (like setting environment variables for example)
Reimplemented from CPlatform.
References CPlatformPosix::InitStageOne(), CAndroidPowerSyscall::Register(), CWinSystemAndroidGLESContext::Register(), and CSpecialProtocol::TranslatePath().
InitStageThree()
bool CPlatformAndroid::InitStageThree () override virtual
Called at a late stage of application startup.
This method can be used for starting platform specific Window/GUI related services/components. (eg , WS-Discovery Daemons)
Reimplemented from CPlatform.
References CXBMCApp::Get(), CServiceBroker::GetSettingsComponent(), CPlatform::InitStageThree(), CLog::Log(), LOGINFO, and CXBMCApp::SetVideoLayoutBackgroundColor().
PlatformSyslog()
void CPlatformAndroid::PlatformSyslog () override virtual
Print platform specific info to log.
Logs platform specific system info during application creation startup
Reimplemented from CPlatform.
References CAndroidStorageProvider::GetExternalStorage(), CLog::Log(), and LOGINFO.
The documentation for this class was generated from the following files:
PlatformAndroid.h
PlatformAndroid.cpp