Kodi Documentation: CGUIWindowVideoBase Class Reference
CGUIWindowVideoBase Class Reference
#include <GUIWindowVideoBase.h>
Public Member Functions
CGUIWindowVideoBase (int id, const std::string &xmlFile)
~CGUIWindowVideoBase (void) override
bool OnMessage (CGUIMessage &message) override
bool OnAction (const CAction &action) override
bool OnItemInfo (const CFileItem &fileItem)
Gets called to process the "info" action for the given file item Default implementation shows a dialog containing information for the movie/episode/... represented by the file item.
Public Member Functions inherited from CGUIMediaWindow
CGUIMediaWindow (int id, const char *xmlFile)
~CGUIMediaWindow (void) override
bool OnBack (int actionID) override
void OnWindowLoaded () override
void OnWindowUnload () override
void OnInitWindow () override
Called on window open.
bool IsMediaWindow () const override
int GetViewContainerID () const override
int GetViewCount () const override
bool HasListItems () const override
CFileItemPtr GetCurrentListItem (int offset=0) override
virtual bool CanFilterAdvanced ()
virtual bool IsFiltered ()
virtual bool IsSameStartFolder (const std::string &dir)
virtual std::string GetRootPath () const
const CFileItemList & CurrentDirectory () const
const CGUIViewState * GetViewState () const
virtual bool UseFileDirectories ()
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsDialog () const
virtual bool IsDialogRunning () const
virtual bool IsModalDialog () const
virtual bool IsSoundEnabled () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
virtual void OnDeinitWindow (int nextWindowID)
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Public Member Functions inherited from IBackgroundLoaderObserver
virtual ~IBackgroundLoaderObserver ()=default
Static Public Member Functions
static void AppendAndClearSearchItems (CFileItemList &searchItems, const std::string &prependLabel, CFileItemList &results)
Append a set of search items to a results list using a specific prepend label Sorts the search items first, then appends with the given prependLabel to the results list. Then empty the search item list so it can be refilled.
static void OnAssignContent (const std::string &path)
Prompt the user for assigning content to a path. Based on changes, we then call OnUnassignContent, update or refresh scraper information in the database and optionally start a scan.
static void LoadVideoInfo (CFileItemList &items, CVideoDatabase &database, bool allowReplaceLabels=true)
Load video information from the database for these items (public static version) Useful for grabbing information for file listings, from watched status to full metadata.
Protected Member Functions
void OnScan (const std::string &strPath, bool scanAll=false)
bool Update (const std::string &strDirectory, bool updateFilterPath=true) override
Retrieves the items from the given path and updates the list.
bool GetDirectory (const std::string &strDirectory, CFileItemList &items) override
Overwrite to fill fileitems from a source.
void OnItemLoaded (CFileItem *pItem) override
void GetGroupedItems (CFileItemList &items) override
bool CheckFilterAdvanced (CFileItemList &items) const override
Check if the given list can be advance filtered or not.
bool CanContainFilter (const std::string &strDirectory) const override
Check if the given path can contain a "filter" parameter.
void GetContextButtons (int itemNumber, CContextButtons &buttons) override
bool OnContextButton (int itemNumber, CONTEXT_BUTTON button) override
virtual void OnQueueItem (int iItem, bool first=false)
void OnQueueItem (const std::shared_ptr< CFileItem > &item, int iItem, bool first=false)
virtual void OnDeleteItem (const CFileItemPtr &pItem)
void OnDeleteItem (int iItem) override
virtual void DoSearch (const std::string &strSearch, CFileItemList &items)
std::string GetStartFolder (const std::string &dir) override
Translate the folder to start in from the given quick path.
bool OnSelect (int iItem) override
bool OnItemInfo (int item)
react to an Info action on a view item
bool OnFileAction (int item, KODI::VIDEO::GUILIB::Action action, const std::string &player)
perform a given action on a file
void OnRestartItem (int iItem, const std::string &player="")
bool OnPlayOrResumeItem (int iItem, const std::string &player="")
bool OnPlayMedia (int iItem, const std::string &player="") override
On media play.
bool OnPlayMedia (const std::shared_ptr< CFileItem > &item, const std::string &player)
bool OnPlayAndQueueMedia (const CFileItemPtr &item, const std::string &player="") override
On play and media queue.
void LoadPlayList (const std::string &strPlayList, KODI::PLAYLIST::Id playlistId=KODI::PLAYLIST::Id::TYPE_VIDEO)
bool PlayItem (const std::shared_ptr< CFileItem > &item, const std::string &player)
bool ShowInfoAndRefresh (const CFileItemPtr &item, const ADDON::ScraperPtr &content)
Lookup the information of an item and display an Info dialog If item has changed then refresh the active underlying list.
void OnSearch ()
Search the current directory for a string got from the virtual keyboard.
void OnSearchItemFound (const CFileItem *pSelItem)
React on the selected search item.
int GetScraperForItem (CFileItem *item, ADDON::ScraperPtr &info, KODI::VIDEO::SScanSettings &settings)
bool OnPlayStackPart (const std::shared_ptr< CFileItem > &item, unsigned int partNumber)
void UpdateVideoVersionItems ()
void UpdateVideoVersionItemsLabel (const std::string &directory)
virtual void LoadPlayList (const std::string &strFileName)
Protected Member Functions inherited from CGUIMediaWindow
CGUIControl * GetFirstFocusableControl (int id) override
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
virtual void SetupShares ()
virtual bool GoParentFolder ()
Go one directory up on list items.
virtual bool OnClick (int iItem, const std::string &player="")
On click.
virtual bool OnPopupMenu (int iItem)
virtual bool OnAddMediaSource ()
virtual void FormatItemLabels (CFileItemList &items, const LABEL_MASKS &labelMasks)
Formats item labels.
virtual void UpdateButtons ()
Updates the states.
void SaveControlStates () override
void RestoreControlStates () override
virtual bool Refresh (bool clearCache=false)
Refreshes the current list by retrieving the lists's path.
virtual void FormatAndSort (CFileItemList &items)
Format and sort file items.
virtual void OnPrepareFileItems (CFileItemList &items)
On prepare file items.
virtual void OnCacheFileItems (CFileItemList &items)
On cache file items.
void ClearFileItems ()
virtual void SortItems (CFileItemList &items)
Sort file items.
virtual void UpdateFilterPath (const std::string &strDirector, const CFileItemList &items, bool updateFilterPath)
virtual bool Filter (bool advanced=true)
void OnFilterItems (const std::string &filter)
virtual bool GetFilteredItems (const std::string &filter, CFileItemList &items)
virtual bool GetAdvanceFilteredItems (CFileItemList &items)
virtual bool HaveDiscOrConnection (const std::string &strPath, int iDriveType)
Check disc or connection present.
void ShowShareErrorMessage (CFileItem *pItem) const
Shows a standard error message for a given pItem.
void SaveSelectedItemInHistory ()
void RestoreSelectedItemFromHistory ()
void GetDirectoryHistoryString (const CFileItem *pItem, std::string &strHistoryString) const
Get history string for given file item.
void SetHistoryForPath (const std::string &strDirectory)
Set history for path.
void UpdateFileList ()
Update file list.
void OnRenameItem (int iItem)
bool WaitForNetwork () const
bool GetDirectoryItems (CURL &url, CFileItemList &items, bool useDir)
bool WaitGetDirectoryItems (CGetDirectoryItems &items)
void CancelUpdateItems ()
bool ProcessRenderLoop (bool renderOnly)
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void SetDefaults ()
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Static Protected Member Functions
static bool OnUnAssignContent (const std::string &path, int header, int text)
static bool StackingAvailable (const CFileItemList &items)
Static Protected Member Functions inherited from CGUIMediaWindow
static std::string RemoveParameterFromPath (const std::string &strDirectory, const std::string &strParameter)
Utility method to remove the given parameter from a path/URL.
Protected Attributes
CGUIDialogProgress * m_dlgProgress
CVideoDatabase m_database
CVideoThumbLoader m_thumbLoader
bool m_stackingAvailable
Protected Attributes inherited from CGUIMediaWindow
XFILE::CVirtualDirectory m_rootDir
CGUIViewControl m_viewControl
CFileItemList * m_vecItems
CFileItemList * m_unfilteredItems
items prior to filtering using FilterItems()
CDirectoryHistory m_history
std::unique_ptr< CGUIViewState > m_guiState
std::atomic_bool m_vecItemsUpdating = {false}
CEvent m_updateEvent
std::atomic_bool m_updateAborted = {false}
std::atomic_bool m_updateJobActive = {false}
int m_iLastControl
std::string m_startDirectory
KODI::PLAYLIST::CSmartPlaylist m_filter
bool m_canFilterAdvanced
std::string m_strFilterPath
Contains the path used for filtering (including any active filter)
bool m_backgroundLoad = false
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Private Member Functions
bool ShowInfo (const CFileItemPtr &item, const ADDON::ScraperPtr &content)
Lookup the information of an item and display an Info dialog.
Private Attributes
bool m_forceSelection
Friends
class ::CVideoSelectActionProcessor
class ::CVideoPlayActionProcessor
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIWindowVideoBase()
CGUIWindowVideoBase::CGUIWindowVideoBase (int id, const std::string & xmlFile)
References m_dlgProgress, m_stackingAvailable, m_thumbLoader, and CBackgroundInfoLoader::SetObserver().
~CGUIWindowVideoBase()
CGUIWindowVideoBase::~CGUIWindowVideoBase (void) override default
Member Function Documentation
AppendAndClearSearchItems()
void CGUIWindowVideoBase::AppendAndClearSearchItems (CFileItemList & searchItems, const std::string & prependLabel, CFileItemList & results) static
Append a set of search items to a results list using a specific prepend label Sorts the search items first, then appends with the given prependLabel to the results list. Then empty the search item list so it can be refilled.
Parameters
searchItems The search items to append.
prependLabel the label that should be prepended to all search results.
results the fileitemlist to append the search results to.
See also
DoSearch
References CFileItemList::Append(), CFileItemList::Clear(), CServiceBroker::GetSettingsComponent(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CFileItemList::Size(), CFileItemList::Sort(), SortAttributeIgnoreArticle, SortAttributeNone, SortByLabel, and SortOrderAscending.
Referenced by CGUIWindowVideoNav::DoSearch(), and CGUIDialogVideoInfo::DoSearch().
CanContainFilter()
bool CGUIWindowVideoBase::CanContainFilter (const std::string & strDirectory) const override protected virtual
Check if the given path can contain a "filter" parameter.
Parameters
strDirectory Path to check
Returns
true if the given path can contain a "filter" parameter otherwise false
Reimplemented from CGUIMediaWindow.
References URIUtils::IsProtocol().
Referenced by CheckFilterAdvanced().
CheckFilterAdvanced()
bool CGUIWindowVideoBase::CheckFilterAdvanced (CFileItemList & items) const override protected virtual
Check if the given list can be advance filtered or not.
Parameters
items List of items to check
Returns
true if the list can be advance filtered otherwise false
Reimplemented from CGUIMediaWindow.
References CanContainFilter(), ADDON::content, CFileItemList::GetContent(), and CGUIMediaWindow::m_strFilterPath.
DoSearch()
virtual void CGUIWindowVideoBase::DoSearch (const std::string & strSearch, CFileItemList & items) inline protected virtual
Reimplemented in CGUIWindowVideoNav.
Referenced by OnSearch().
GetContextButtons()
void CGUIWindowVideoBase::GetContextButtons (int itemNumber, CContextButtons & buttons) override protected virtual
Reimplemented from CGUIMediaWindow.
Reimplemented in CGUIWindowVideoNav, and CGUIWindowVideoPlaylist.
References CContextButtons::Add(), CONTEXT_BUTTON_CHOOSE_PLAYLIST, CONTEXT_BUTTON_EDIT_SMART_PLAYLIST, CONTEXT_BUTTON_PLAY_AND_QUEUE, CONTEXT_BUTTON_PLAY_ONLY_THIS, CONTEXT_BUTTON_PLAY_PART, CONTEXT_BUTTON_PLAY_PARTYMODE, CFileItemList::Get(), CGUIMediaWindow::GetContextButtons(), CVideoDatabase::GetStackTimes(), KODI::VIDEO::UTILS::IsAutoPlayNextItem(), URIUtils::IsDiscImageStack(), KODI::PLAYLIST::IsSmartPlayList(), URIUtils::IsStack(), m_database, CGUIMediaWindow::m_vecItems, and CFileItemList::Size().
Referenced by CGUIWindowVideoNav::GetContextButtons().
GetDirectory()
bool CGUIWindowVideoBase::GetDirectory (const std::string & strDirectory, CFileItemList & items) override protected virtual
Overwrite to fill fileitems from a source.
Parameters
[in] strDirectory Path to read
[out] items Fill with items specified in strDirectory
Returns
false if given directory not present
Todo:
Do we want to limit the directories we apply the video ones to?
Reimplemented from CGUIMediaWindow.
Reimplemented in CGUIWindowVideoNav.
References CFileItemList::Add(), CFileItemList::Contains(), CONTENT_TVSHOWS, g_localizeStrings, CLocalizeStrings::Get(), CGUIMediaWindow::GetDirectory(), CFileItem::GetPath(), CVideoDatabase::GetScraperForPath(), CServiceBroker::GetSettingsComponent(), CFileItem::IsStack(), m_database, m_stackingAvailable, CSettings::SETTING_MYVIDEOS_STACKVIDEOS, CFileItemList::Stack(), and StackingAvailable().
Referenced by CGUIWindowVideoNav::GetDirectory().
GetGroupedItems()
void CGUIWindowVideoBase::GetGroupedItems (CFileItemList & items) override protected virtual
Reimplemented from CGUIMediaWindow.
References CFileItemList::Append(), CVariant::asBoolean(), CVariant::asString(), CFileItemList::ClearItems(), CFileItemList::GetContent(), XFILE::CVideoDatabaseDirectory::GetDirectoryChildType(), CGUIMediaWindow::GetGroupedItems(), CFileItem::GetPath(), CGUIListItem::GetProperty(), XFILE::CVideoDatabaseDirectory::GetQueryParams(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSetId(), CServiceBroker::GetSettingsComponent(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetVideoVersionId(), GroupUtils::GroupAndMix(), GroupAttributeIgnoreSingleItems, GroupAttributeNone, GroupBySet, CGUIListItem::HasProperty(), CBackgroundInfoLoader::IsLoading(), CBackgroundInfoLoader::Load(), CGUIMediaWindow::m_strFilterPath, m_thumbLoader, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, PROPERTY_GROUP_BY, PROPERTY_GROUP_MIXED, CSettings::SETTING_VIDEOLIBRARY_GROUPMOVIESETS, CSettings::SETTING_VIDEOLIBRARY_GROUPSINGLEITEMSETS, and CBackgroundInfoLoader::StopThread().
GetScraperForItem()
int CGUIWindowVideoBase::GetScraperForItem (CFileItem * item, ADDON::ScraperPtr & info, KODI::VIDEO::SScanSettings & settings) protected
References CFileItem::GetPath(), CVideoDatabase::GetScraperForPath(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CFileItem::IsLiveTV(), CFileItem::IsPlugin(), CFileItem::IsRSS(), m_database, CVideoInfoTag::m_strPath, and CGUIMediaWindow::m_vecItems.
Referenced by CGUIWindowVideoNav::GetContextButtons().
GetStartFolder()
std::string CGUIWindowVideoBase::GetStartFolder (const std::string & url) override protected virtual
Translate the folder to start in from the given quick path.
Parameters
url the folder the user wants
Returns
the resulting path
Todo:
This ifdef block probably belongs somewhere else. Move it to a better place!
Reimplemented from CGUIMediaWindow.
Reimplemented in CGUIWindowVideoNav.
References CGUIMediaWindow::GetStartFolder().
Referenced by CGUIWindowVideoNav::GetStartFolder().
LoadPlayList() [1/2]
virtual void CGUIMediaWindow::LoadPlayList (const std::string & strFileName) inline protected virtual
Reimplemented from CGUIMediaWindow.
LoadPlayList() [2/2]
void CGUIWindowVideoBase::LoadPlayList (const std::string & strPlayList, KODI::PLAYLIST::Id playlistId = KODI::PLAYLIST::Id::TYPE_VIDEO) protected
References KODI::PLAYLIST::CPlayListFactory::Create(), CPartyModeManager::Disable(), g_application, g_partyModeManager, CPartyModeManager::IsEnabled(), CGUIMediaWindow::m_guiState, and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by PlayItem().
LoadVideoInfo()
void CGUIWindowVideoBase::LoadVideoInfo (CFileItemList & items, CVideoDatabase & database, bool allowReplaceLabels = true) static
Load video information from the database for these items (public static version) Useful for grabbing information for file listings, from watched status to full metadata.
Parameters
items the items to load information for.
database open database object to retrieve the data from
allowReplaceLabels allow label replacement if according GUI setting is enabled
Todo:
this could possibly be threaded as per the music info loading, we could also cache the info
References CVariant::asBoolean(), ADDON::content, CFileItemList::Get(), CFileItemList::GetContent(), CVideoDatabase::GetContentForPath(), XFILE::CMultiPathDirectory::GetFirstPath(), CVideoDatabase::GetItemsForPath(), CFileItem::GetPath(), CVideoDatabase::GetPlayCounts(), CGUIListItem::GetProperty(), CServiceBroker::GetSettingsComponent(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, URIUtils::IsMultiPath(), CFileItem::IsPlugin(), CFileItemList::SetContent(), CFileItemList::SetFastLookup(), CGUIListItem::SetProperty(), CFileItemList::SetSortIgnoreFolders(), CSettings::SETTING_MYVIDEOS_REPLACELABELS, CSettings::SETTING_MYVIDEOS_STACKVIDEOS, CFileItemList::Size(), and StackingAvailable().
Referenced by CGUIWindowVideoNav::GetDirectory(), PVR::CGUIWindowPVRRecordingsBase::OnPrepareFileItems(), and CGUIWindowVideoPlaylist::OnPrepareFileItems().
OnAction()
bool CGUIWindowVideoBase::OnAction (const CAction & action) override virtual
Reimplemented from CGUIMediaWindow.
Reimplemented in CGUIWindowVideoNav, and CGUIWindowVideoPlaylist.
References ACTION_SCAN_ITEM, ACTION_SHOW_PLAYLIST, CGUIWindowManager::ActivateWindow(), CONTEXT_BUTTON_SCAN, CServiceBroker::GetGUI(), CServiceBroker::GetPlaylistPlayer(), CGUIViewControl::GetSelectedItem(), CGUIComponent::GetWindowManager(), CGUIMediaWindow::m_viewControl, CGUIMediaWindow::OnAction(), OnContextButton(), and WINDOW_VIDEO_PLAYLIST.
Referenced by CGUIWindowVideoNav::OnAction(), and CGUIWindowVideoPlaylist::OnAction().
OnAssignContent()
void CGUIWindowVideoBase::OnAssignContent (const std::string & path) static
Prompt the user for assigning content to a path. Based on changes, we then call OnUnassignContent, update or refresh scraper information in the database and optionally start a scan.
Parameters
path the path to assign content for
References KODI::VIDEO::SScanSettings::exclude, CVideoLibraryQueue::GetInstance(), CVideoDatabase::GetScraperForPath(), OnUnAssignContent(), CVideoDatabase::Open(), CVideoLibraryQueue::ScanLibrary(), CVideoDatabase::SetScraperForPath(), and CGUIDialogContentSettings::Show().
Referenced by OnContextButton(), and CGUIDialogMediaSource::OnMediaSourceChanged().
OnContextButton()
bool CGUIWindowVideoBase::OnContextButton (int itemNumber, CONTEXT_BUTTON button) override protected virtual
Reimplemented from CGUIMediaWindow.
Reimplemented in CGUIWindowVideoNav, and CGUIWindowVideoPlaylist.
References KODI::VIDEO::GUILIB::ACTION_PLAYPART, CONTEXT_BUTTON_CHOOSE_PLAYLIST, CONTEXT_BUTTON_DELETE, CONTEXT_BUTTON_EDIT_SMART_PLAYLIST, CONTEXT_BUTTON_PLAY_AND_QUEUE, CONTEXT_BUTTON_PLAY_ONLY_THIS, CONTEXT_BUTTON_PLAY_PART, CONTEXT_BUTTON_PLAY_PARTYMODE, CONTEXT_BUTTON_RENAME, CONTEXT_BUTTON_SCAN, CONTEXT_BUTTON_SET_CONTENT, CGUIDialogSmartPlaylistEditor::EditPlaylist(), CPartyModeManager::Enable(), g_partyModeManager, CFileItemList::Get(), CFileItem::GetPath(), KODI::PLAYLIST::IsSmartPlayList(), m_forceSelection, CGUIMediaWindow::m_vecItems, OnAssignContent(), CGUIMediaWindow::OnContextButton(), OnDeleteItem(), OnFileAction(), OnItemInfo(), OnPlayAndQueueMedia(), OnPlayMedia(), CGUIMediaWindow::OnRenameItem(), OnScan(), PARTYMODECONTEXT_VIDEO, playlist, and CGUIMediaWindow::Refresh().
Referenced by OnAction(), CGUIWindowVideoNav::OnContextButton(), and CGUIWindowVideoPlaylist::OnContextButton().
OnDeleteItem() [1/2]
void CGUIWindowVideoBase::OnDeleteItem (const CFileItemPtr & pItem) protected virtual
Reimplemented in CGUIWindowVideoNav.
References CFileUtils::DeleteItemWithConfirm(), g_passwordManager, CServiceBroker::GetSettingsComponent(), CGUIPassword::IsMasterLockUnlocked(), CFileItem::IsPath(), LOCK_MODE_EVERYONE, CGUIMediaWindow::m_vecItems, CSettings::SETTING_FILELISTS_ALLOWFILEDELETION, and CUtil::SupportsWriteFileOperations().
Referenced by OnContextButton(), CGUIWindowVideoNav::OnDeleteItem(), OnDeleteItem(), and OnMessage().
OnDeleteItem() [2/2]
void CGUIWindowVideoBase::OnDeleteItem (int iItem) override protected virtual
Reimplemented from CGUIMediaWindow.
References CFileItemList::Get(), CGUIMediaWindow::m_vecItems, CGUIMediaWindow::m_viewControl, OnDeleteItem(), CGUIMediaWindow::Refresh(), CGUIViewControl::SetSelectedItem(), and CFileItemList::Size().
OnFileAction()
bool CGUIWindowVideoBase::OnFileAction (int item, KODI::VIDEO::GUILIB::Action action, const std::string & player) protected
perform a given action on a file
Parameters
item the selected item
action the action to perform
Returns
true if the action is performed, false otherwise
References ::CVideoSelectActionProcessor, CFileItemList::Get(), and CGUIMediaWindow::m_vecItems.
Referenced by OnContextButton(), and OnSelect().
OnItemInfo() [1/2]
bool CGUIWindowVideoBase::OnItemInfo (const CFileItem & fileItem)
Gets called to process the "info" action for the given file item Default implementation shows a dialog containing information for the movie/episode/... represented by the file item.
Parameters
fileItem the item for which information is to be presented.
Returns
true if information was presented, false otherwise.
References CFileItemList::Clear(), CGUIListItem::ClearArt(), CDatabase::Close(), CONTENT_TVSHOWS, XFILE::DIR_FLAG_DEFAULTS, CUtil::ExcludeFileOrFolder(), XFILE::CDirectory::GetDirectory(), URIUtils::GetDirectory(), CFileItem::GetDynPath(), CServiceBroker::GetFileExtensionProvider(), KODI::VIDEO::UTILS::GetOpticalMediaPath(), CFileItem::GetPath(), CVideoDatabase::GetScraperForPath(), CServiceBroker::GetSettingsComponent(), CFileExtensionProvider::GetVideoExtensions(), CFileItem::GetVideoInfoTag(), CFileItem::HasAddonInfo(), URIUtils::HasExtension(), KODI::VIDEO::UTILS::HasItemVideoDbInformation(), CGUIListItem::HasProperty(), CFileItem::HasVideoInfoTag(), CFileItem::IsParentFolder(), CFileItem::IsPath(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsPlugin(), CFileItem::IsScript(), CGUIListItem::m_bIsFolder, CFileItem::m_bIsShareOrDrive, m_database, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iIdShow, CVideoInfoTag::m_strPath, CVideoInfoTag::m_type, MediaTypeSeason, MediaTypeVideoVersion, CVideoDatabase::Open(), KODI::VIDEO::SScanSettings::parent_name_root, CFileItem::SetPath(), CGUIListItem::SetProperty(), CGUIDialogMusicInfo::ShowFor(), CGUIDialogAddonInfo::ShowForItem(), ShowInfoAndRefresh(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), CFileItemList::Size(), and CFileItemList::Stack().
Referenced by OnContextButton(), OnItemInfo(), OnMessage(), CGUIWindowVideoNav::OnMessage(), and CGUIDialogVideoInfo::ShowFor().
OnItemInfo() [2/2]
bool CGUIWindowVideoBase::OnItemInfo (int item) protected
react to an Info action on a view item
Parameters
item the selected item
Returns
true if the action is performed, false otherwise
References CFileItemList::Get(), CGUIMediaWindow::m_vecItems, OnItemInfo(), and CFileItemList::Size().
OnItemLoaded()
void CGUIWindowVideoBase::OnItemLoaded (CFileItem * pItem) inline override protected virtual
Implements IBackgroundLoaderObserver.
Reimplemented in CGUIWindowVideoNav.
OnMessage()
bool CGUIWindowVideoBase::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIMediaWindow.
Reimplemented in CGUIWindowVideoNav, and CGUIWindowVideoPlaylist.
References ACTION_DELETE_ITEM, ACTION_MOUSE_MIDDLE_CLICK, ACTION_PLAYER_PLAY, ACTION_QUEUE_ITEM, ACTION_QUEUE_ITEM_NEXT, ACTION_SHOW_INFO, CDatabase::Close(), CONTROL_PLAY_DVD, CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CServiceBroker::GetMediaManager(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIViewControl::GetSelectedItem(), CGUIMessage::GetSenderId(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), GUI_MSG_CLICKED, GUI_MSG_SEARCH, GUI_MSG_WINDOW_DEINIT, GUI_MSG_WINDOW_INIT, CGUIViewControl::HasControl(), CBackgroundInfoLoader::IsLoading(), CFileItem::IsPath(), m_database, m_dlgProgress, m_thumbLoader, CGUIMediaWindow::m_vecItems, CGUIMediaWindow::m_viewControl, OnDeleteItem(), OnItemInfo(), CGUIMediaWindow::OnMessage(), OnPlayOrResumeItem(), OnQueueItem(), OnSearch(), CVideoDatabase::Open(), CBackgroundInfoLoader::StopThread(), WINDOW_DIALOG_PROGRESS, and WINDOW_VIDEO_NAV.
Referenced by CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), and ShowInfo().
OnPlayAndQueueMedia()
bool CGUIWindowVideoBase::OnPlayAndQueueMedia (const CFileItemPtr & item, const std::string & player = "") override protected virtual
On play and media queue.
Note
Override if you want to change the default behavior of what is done when the user clicks on a file in a "folder" with similar files.
This function is called by OnClick()
Reimplemented from CGUIMediaWindow.
References CServiceBroker::GetPlaylistPlayer(), CGUIMediaWindow::m_guiState, CGUIMediaWindow::OnPlayAndQueueMedia(), and KODI::PLAYLIST::CPlayListPlayer::SetShuffle().
Referenced by OnContextButton(), and PlayItem().
OnPlayMedia() [1/2]
bool CGUIWindowVideoBase::OnPlayMedia (const std::shared_ptr< CFileItem > & item, const std::string & player) protected
References KODI::PLAYLIST::CPlayList::Add(), CPartyModeManager::AddUserSongs(), g_partyModeManager, CServiceBroker::GetAppComponents(), CServiceBroker::GetPlaylistPlayer(), CPartyModeManager::IsEnabled(), CBackgroundInfoLoader::IsLoading(), CBackgroundInfoLoader::Load(), CLog::Log(), LOGDEBUG, m_forceSelection, CGUIMediaWindow::m_guiState, m_thumbLoader, CGUIMediaWindow::m_vecItems, PARTYMODECONTEXT_VIDEO, KODI::PLAYLIST::CPlayListPlayer::Play(), KODI::PLAYLIST::CPlayListPlayer::Reset(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), and CBackgroundInfoLoader::StopAsync().
OnPlayMedia() [2/2]
bool CGUIWindowVideoBase::OnPlayMedia (int iItem, const std::string & player = "") override protected virtual
On media play.
Note
Override if you want to change the default behavior, what is done when the user clicks on a file.
This function is called by OnClick()
Reimplemented from CGUIMediaWindow.
Reimplemented in CGUIWindowVideoPlaylist.
References CFileItemList::Get(), CGUIMediaWindow::m_vecItems, OnPlayMedia(), and CFileItemList::Size().
Referenced by OnContextButton(), OnPlayMedia(), and PlayItem().
OnPlayOrResumeItem()
bool CGUIWindowVideoBase::OnPlayOrResumeItem (int iItem, const std::string & player = "") protected
References ::CVideoPlayActionProcessor, CFileItemList::Get(), CGUIMediaWindow::m_vecItems, and CFileItemList::Size().
Referenced by OnMessage().
OnPlayStackPart()
bool CGUIWindowVideoBase::OnPlayStackPart (const std::shared_ptr< CFileItem > & item, unsigned int partNumber) protected
References KODI::VIDEO::GUILIB::ACTION_PLAY_FROM_BEGINNING, KODI::VIDEO::GUILIB::ACTION_RESUME, KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::ChoosePlayOrResume(), XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::GetDirectory(), KODI::VIDEO::UTILS::GetItemResumeInformation(), CVideoDatabase::GetStackTimes(), URIUtils::IsDiscImageStack(), URIUtils::IsStack(), m_database, PlayItem(), KODI::VIDEO::UTILS::ResumeInformation::startOffset, and value.
OnQueueItem() [1/2]
void CGUIWindowVideoBase::OnQueueItem (const std::shared_ptr< CFileItem > & item, int iItem, bool first = false) protected
References CGUIControl::GetID(), CGUIMediaWindow::m_viewControl, KODI::VIDEO::UTILS::QueueItem(), CGUIViewControl::SetSelectedItem(), and WINDOW_VIDEO_PLAYLIST.
OnQueueItem() [2/2]
void CGUIWindowVideoBase::OnQueueItem (int iItem, bool first = false) protected virtual
References CFileItemList::Get(), CGUIMediaWindow::m_vecItems, OnQueueItem(), and CFileItemList::Size().
Referenced by OnMessage(), and OnQueueItem().
OnRestartItem()
void CGUIWindowVideoBase::OnRestartItem (int iItem, const std::string & player = "") protected
References CGUIMediaWindow::OnClick().
OnScan()
void CGUIWindowVideoBase::OnScan (const std::string & strPath, bool scanAll = false) protected
References CVideoLibraryQueue::GetInstance(), and CVideoLibraryQueue::ScanLibrary().
Referenced by OnContextButton(), and CGUIWindowVideoNav::OnMessage().
OnSearch()
void CGUIWindowVideoBase::OnSearch () protected
Search the current directory for a string got from the virtual keyboard.
References CGUIDialogSelect::Add(), CGUIWindow::Close(), DoSearch(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedItem(), CGUIComponent::GetWindowManager(), m_dlgProgress, OnSearchItemFound(), CGUIDialogProgress::Open(), CGUIDialog::Open(), CGUIDialogProgress::Progress(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CGUIKeyboardFactory::ShowAndGetInput(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), CFileItemList::Size(), and WINDOW_DIALOG_SELECT.
Referenced by OnMessage(), and CGUIWindowVideoNav::OnMessage().
OnSearchItemFound()
void CGUIWindowVideoBase::OnSearchItemFound (const CFileItem * pSelItem) protected
React on the selected search item.
Parameters
pItem Search result item
References CURL::Get(), CFileItemList::Get(), URIUtils::GetDirectory(), URIUtils::GetParentPath(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), URIUtils::HasSlashAtEnd(), CFileItem::IsSmb(), CGUIListItem::m_bIsFolder, CGUIMediaWindow::m_vecItems, CGUIMediaWindow::m_viewControl, CGUIViewControl::SetFocused(), CGUIMediaWindow::SetHistoryForPath(), CURL::SetOptions(), CGUIViewControl::SetSelectedItem(), CSettings::SETTING_MYVIDEOS_FLATTEN, CFileItemList::Size(), and Update.
Referenced by OnSearch().
OnSelect()
bool CGUIWindowVideoBase::OnSelect (int iItem) override protected virtual
Reimplemented from CGUIMediaWindow.
Reimplemented in CGUIWindowVideoPlaylist.
References CFileItemList::Get(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::GetDefaultSelectAction(), CGUIMediaWindow::m_vecItems, OnFileAction(), CGUIMediaWindow::OnSelect(), and CFileItemList::Size().
OnUnAssignContent()
bool CGUIWindowVideoBase::OnUnAssignContent (const std::string & path, int header, int text) static protected
References CDatabase::Close(), CUtil::DeleteVideoDatabaseDirectoryCache(), KODI::VIDEO::SScanSettings::exclude, CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialogYesNo::NO_TIMEOUT, CVideoDatabase::Open(), CVideoDatabase::RemoveContentForPath(), CVideoDatabase::SetScraperForPath(), CGUIDialogYesNo::ShowAndGetInput(), text, and WINDOW_DIALOG_PROGRESS.
Referenced by OnAssignContent(), and CGUIWindowVideoNav::OnContextButton().
PlayItem()
bool CGUIWindowVideoBase::PlayItem (const std::shared_ptr< CFileItem > & item, const std::string & player) protected
Todo:
get rid of "videos with versions as folder" hack!
References KODI::PLAYLIST::CPlayListPlayer::Add(), CGUIPassword::bMasterUser, KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist(), CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), g_partyModeManager, g_passwordManager, CFileItemList::Get(), KODI::VIDEO::UTILS::GetItemsForPlayList(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetSettingsComponent(), CPartyModeManager::IsEnabled(), KODI::PLAYLIST::IsPlayList(), LoadPlayList(), LOGDEBUG, m_forceSelection, CGUIMediaWindow::m_guiState, CGUIMediaWindow::m_vecItems, CGUIMediaWindow::m_viewControl, OnPlayAndQueueMedia(), OnPlayMedia(), KODI::PLAYLIST::CPlayListPlayer::Play(), CGUIMediaWindow::Refresh(), KODI::PLAYLIST::CPlayListPlayer::Reset(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), CGUIViewControl::SetSelectedItem(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and CFileItemList::Size().
Referenced by OnPlayStackPart().
ShowInfo()
bool CGUIWindowVideoBase::ShowInfo (const CFileItemPtr & item, const ADDON::ScraperPtr & content) private
Lookup the information of an item and display an Info dialog.
Parameters
item the item to lookup
content
Returns
true: the information of the item was modified. false: no change.
Todo:
get rid of "videos with versions as folder" hack to be able to fix in CFileItem::GetBaseMoviePath()
!todo we need this to update images in video info dialog immediatly after refresh, but why?
References CGUIPassword::bMasterUser, CDatabase::Close(), CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_NONE, CONTENT_TVSHOWS, CUtil::DeleteVideoDatabaseDirectoryCache(), g_passwordManager, CGUIDialogVideoInfo::GetCurrentListItem(), CVideoDatabase::GetEpisodeInfo(), CServiceBroker::GetGUI(), CVideoLibraryQueue::GetInstance(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMusicVideoInfo(), URIUtils::GetParentPath(), CVideoDatabase::GetSeasonInfo(), CServiceBroker::GetSettingsComponent(), CGUIDialogVideoInfo::GetThumbnail(), CVideoDatabase::GetTvShowId(), CVideoDatabase::GetTvShowInfo(), CVideoInfoTag::GetUniqueID(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_REFRESH_THUMBS, CGUIDialogVideoInfo::HasUpdatedItems(), CGUIDialogVideoInfo::HasUpdatedThumb(), CGUIDialogVideoInfo::HasUpdatedUserrating(), CGUIWindow::IsActive(), CLog::Log(), LOGERROR, m_database, CVideoInfoTag::m_iIdSeason, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_type, MediaTypeSeason, CGUIDialogVideoInfo::NeedRefresh(), OnMessage(), CVideoDatabase::Open(), CGUIDialog::Open(), CGUIDialogVideoInfo::RefreshAll(), CGUIDialogVideoInfo::SetMovie(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and WINDOW_DIALOG_VIDEO_INFO.
Referenced by ShowInfoAndRefresh().
ShowInfoAndRefresh()
bool CGUIWindowVideoBase::ShowInfoAndRefresh (const CFileItemPtr & item, const ADDON::ScraperPtr & content) protected
Lookup the information of an item and display an Info dialog If item has changed then refresh the active underlying list.
Parameters
item the item to lookup
content
Returns
true: the information of the item was modified. false: no change.
References CGUIViewControl::GetSelectedItem(), CGUIWindow::IsActive(), CGUIMediaWindow::m_viewControl, CGUIMediaWindow::Refresh(), CGUIViewControl::SetSelectedItem(), and ShowInfo().
Referenced by OnItemInfo().
StackingAvailable()
bool CGUIWindowVideoBase::StackingAvailable (const CFileItemList & items) static protected
References CFileItem::GetPath(), CFileItem::IsAddonsPath(), KODI::NETWORK::IsInternetStream(), CFileItem::IsPlugin(), CURL::IsProtocol(), and CFileItem::IsRSS().
Referenced by GetDirectory(), and LoadVideoInfo().
Update()
bool CGUIWindowVideoBase::Update (const std::string & strDirectory, bool updateFilterPath = true) override protected virtual
Retrieves the items from the given path and updates the list.
Parameters
strDirectory The path to the directory to get the items from
updateFilterPath Whether to update the filter path in m_strFilterPath or not
Returns
true if the list was successfully updated otherwise false
See also
GetDirectory
m_vecItems
m_strFilterPath
Todo:
OnInitWindow calls Update() before window path has been set properly.
Reimplemented from CGUIMediaWindow.
Reimplemented in CGUIWindowVideoNav.
References CBackgroundInfoLoader::IsLoading(), CBackgroundInfoLoader::Load(), m_thumbLoader, CGUIMediaWindow::m_vecItems, CBackgroundInfoLoader::StopThread(), CGUIMediaWindow::Update(), UpdateVideoVersionItems(), and UpdateVideoVersionItemsLabel().
Referenced by CGUIWindowVideoNav::Update().
UpdateVideoVersionItems()
void CGUIWindowVideoBase::UpdateVideoVersionItems () protected
Todo:
patching the items after loading is a hack, which only works in the video window, not for example for home screen widgets!
References CDbUrl::AddOption(), CDbUrl::FromString(), CServiceBroker::GetSettingsComponent(), CGUIMediaWindow::m_vecItems, MediaTypeMovie, MediaTypeVideoVersion, CSettings::SETTING_VIDEOLIBRARY_SHOWVIDEOVERSIONSASFOLDER, CDbUrl::ToString(), and VIDEO_VERSION_ID_ALL.
Referenced by Update().
UpdateVideoVersionItemsLabel()
void CGUIWindowVideoBase::UpdateVideoVersionItemsLabel (const std::string & directory) protected
References CDbUrl::FromString(), CDbUrl::GetOption(), CFileItem::GetVideoContentType(), CVideoDatabase::GetVideoItemTitle(), CDbUrl::HasOption(), m_database, CGUIMediaWindow::m_vecItems, CFileItem::SetLabel(), CGUIWindow::SetProperty(), value, and VIDEO_VERSION_ID_ALL.
Referenced by Update().
Friends And Related Symbol Documentation
::CVideoPlayActionProcessor
friend class ::CVideoPlayActionProcessor friend
Referenced by CGUIWindowVideoPlaylist::OnPlayMedia(), and OnPlayOrResumeItem().
::CVideoSelectActionProcessor
friend class ::CVideoSelectActionProcessor friend
Referenced by OnFileAction().
Member Data Documentation
m_database
CVideoDatabase CGUIWindowVideoBase::m_database protected
Referenced by CGUIWindowVideoNav::DoSearch(), GetContextButtons(), GetDirectory(), CGUIWindowVideoNav::GetDirectory(), GetScraperForItem(), CGUIWindowVideoNav::OnDeleteItem(), OnItemInfo(), OnMessage(), OnPlayStackPart(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), ShowInfo(), and UpdateVideoVersionItemsLabel().
m_dlgProgress
CGUIDialogProgress* CGUIWindowVideoBase::m_dlgProgress protected
Referenced by CGUIWindowVideoBase(), OnMessage(), and OnSearch().
m_forceSelection
bool CGUIWindowVideoBase::m_forceSelection private
Referenced by OnContextButton(), OnPlayMedia(), and PlayItem().
m_stackingAvailable
bool CGUIWindowVideoBase::m_stackingAvailable protected
Referenced by CGUIWindowVideoBase(), and GetDirectory().
m_thumbLoader
CVideoThumbLoader CGUIWindowVideoBase::m_thumbLoader protected
Referenced by CGUIWindowVideoBase(), CGUIWindowVideoNav::CGUIWindowVideoNav(), CGUIWindowVideoNav::GetDirectory(), GetGroupedItems(), OnMessage(), CGUIWindowVideoNav::OnMessage(), OnPlayMedia(), and Update().
The documentation for this class was generated from the following files:
GUIWindowVideoBase.h
GUIWindowVideoBase.cpp