Kodi Documentation: KODI::GUILIB::GUIINFO::CSkinGUIInfo Class Reference
KODI::GUILIB::GUIINFO::CSkinGUIInfo Class Reference
#include <SkinGUIInfo.h>
Public Member Functions
CSkinGUIInfo ()=default
~CSkinGUIInfo () override=default
bool InitCurrentItem (CFileItem *item) override
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) const override
Get a GUIInfoManager label string.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager integer value.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager bool value.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
CGUIInfoProvider ()=default
~CGUIInfoProvider () override=default
bool GetFallbackLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) override
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo) override
Set new audio/video stream info data.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::IGUIInfoProvider
virtual ~IGUIInfoProvider ()=default
Additional Inherited Members
Protected Attributes inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
VideoStreamInfo m_videoInfo
AudioStreamInfo m_audioInfo
SubtitleStreamInfo m_subtitleInfo
Constructor & Destructor Documentation
CSkinGUIInfo()
KODI::GUILIB::GUIINFO::CSkinGUIInfo::CSkinGUIInfo () default
~CSkinGUIInfo()
KODI::GUILIB::GUIINFO::CSkinGUIInfo::~CSkinGUIInfo () override default
Member Function Documentation
GetBool()
bool CSkinGUIInfo::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager bool value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References g_SkinInfo, CSkinSettings::GetBool(), CSkinSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CSkinSettings::GetString(), URIUtils::RemoveExtension(), CSettings::SETTING_LOOKANDFEEL_SKINTHEME, SKIN_BOOL, SKIN_HAS_THEME, SKIN_STRING, SKIN_STRING_IS_EQUAL, SKIN_TIMER_IS_RUNNING, and value.
GetInt()
bool CSkinGUIInfo::GetInt (int & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager integer value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References g_SkinInfo, CSkinSettings::GetInstance(), CSkinSettings::GetInt(), SKIN_INTEGER, SKIN_TIMER_ELAPSEDSECS, and value.
GetLabel()
bool CSkinGUIInfo::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) const override virtual
Get a GUIInfoManager label string.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References g_localizeStrings, g_SkinInfo, CLocalizeStrings::Get(), CSkinSettings::GetBool(), CSkinSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CSkinSettings::GetString(), CSettings::SETTING_LOOKANDFEEL_FONT, CSettings::SETTING_LOOKANDFEEL_SKINCOLORS, CSettings::SETTING_LOOKANDFEEL_SKINTHEME, SKIN_ASPECT_RATIO, SKIN_BOOL, SKIN_COLOUR_THEME, SKIN_FONT, SKIN_STRING, SKIN_THEME, SKIN_TIMER_ELAPSEDSECS, and value.
InitCurrentItem()
bool CSkinGUIInfo::InitCurrentItem (CFileItem * item) override virtual
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by the provider, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
The documentation for this class was generated from the following files:
SkinGUIInfo.h
SkinGUIInfo.cpp