Kodi Documentation: KODI::WINDOWING::WAYLAND::IInputHandler Class Reference
KODI::WINDOWING::WAYLAND::IInputHandler Class Reference
#include <SeatInputProcessing.h>
Public Member Functions
virtual void OnEvent (InputType type, XBMC_Event &event)
virtual void OnEnter (InputType type)
virtual void OnLeave (InputType type)
virtual void OnSetCursor (std::uint32_t seatGlobalName, std::uint32_t serial)
virtual ~IInputHandler ()=default
Detailed Description
Handler interface for input events from CSeatInputProcessor
Constructor & Destructor Documentation
~IInputHandler()
virtual KODI::WINDOWING::WAYLAND::IInputHandler::~IInputHandler () virtual default
Member Function Documentation
OnEnter()
virtual void KODI::WINDOWING::WAYLAND::IInputHandler::OnEnter (InputType type) inline virtual
Handle focus enter
Parameters
type input device type for which the surface has gained the focus
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::OnKeyboardEnter(), and KODI::WINDOWING::WAYLAND::CSeatInputProcessing::OnPointerEnter().
OnEvent()
virtual void KODI::WINDOWING::WAYLAND::IInputHandler::OnEvent (InputType type, XBMC_Event & event) inline virtual
Handle input event
Parameters
type input device type that caused the event
event XBMC event data
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::OnKeyboardEvent(), and KODI::WINDOWING::WAYLAND::CSeatInputProcessing::OnPointerEvent().
OnLeave()
virtual void KODI::WINDOWING::WAYLAND::IInputHandler::OnLeave (InputType type) inline virtual
Handle focus leave
Parameters
type input device type for which the surface has lost the focus
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::OnKeyboardLeave(), and KODI::WINDOWING::WAYLAND::CSeatInputProcessing::OnPointerLeave().
OnSetCursor()
virtual void KODI::WINDOWING::WAYLAND::IInputHandler::OnSetCursor (std::uint32_t seatGlobalName, std::uint32_t serial) inline virtual
Handle request for setting the cursor
When the client gains pointer focus for a surface, a cursor image must be attached to the pointer. Otherwise the previous pointer image would be used.
This request is sent in addition to OnEnter for InputType::POINTER.
Parameters
seatGlobalName numeric Wayland global name of the seat the event occurred on
pointer pointer instance that needs its cursor set
serial Wayland protocol message serial that must be sent back in set_cursor
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::OnPointerEnter().
The documentation for this class was generated from the following file:
SeatInputProcessing.h