Kodi Documentation: class CDllHelper
class CDllHelper
C++ » Interface - kodi::tools
Class to help with load of shared library functions
You can add them as parent to your class and to help with load of shared library functions.
Classes
class kodi::tools::CDllHelper
Macros
#define REGISTER_DLL_SYMBOL(functionPtr) kodi::tools::CDllHelper::RegisterSymbol(functionPtr, #functionPtr)
Macro to translate the given pointer value name of functions to requested function name.
Functions
kodi::tools::CDllHelper::CDllHelper ()=default
Class constructor.
virtual kodi::tools::CDllHelper::~CDllHelper ()
Class destructor.
bool kodi::tools::CDllHelper::LoadDll (std::string path)
Function to load requested library.
template<typename T >
bool kodi::tools::CDllHelper::RegisterSymbol (T &functionPtr, const char *strFunctionPtr)
Function to register requested library symbol.
Detailed Description
Class to help with load of shared library functions
You can add them as parent to your class and to help with load of shared library functions.
Note
To use on Windows must you also include dlfcn-win32 on your addon!
Furthermore, this allows the use of Android where the required library is copied to an EXE useable folder.
Example:
#include <kodi/tools/DllHelper.h>
...
class CMyInstance : public kodi::addon::CInstanceAudioDecoder,
                    private kodi::tools::CDllHelper
{
public:
  CMyInstance(KODI_HANDLE instance, const std::string& kodiVersion);
  bool Start();
  ...
  // The pointers for on shared library exported functions
  int (*Init)();
  void (*Cleanup)();
  int (*GetLength)();
};
CMyInstance::CMyInstance(KODI_HANDLE instance, const std::string& kodiVersion)
  : CInstanceAudioDecoder(instance, kodiVersion)
{
}
bool CMyInstance::Start()
{
  std::string lib = kodi::GetAddonPath("myLib.so");
  if (!LoadDll(lib)) return false;
  if (!REGISTER_DLL_SYMBOL(Init)) return false;
  if (!REGISTER_DLL_SYMBOL(Cleanup)) return false;
  if (!REGISTER_DLL_SYMBOL(GetLength)) return false;
  Init();
  return true;
}
...
Macro Definition Documentation
REGISTER_DLL_SYMBOL
#define REGISTER_DLL_SYMBOL (functionPtr) kodi::tools::CDllHelper::RegisterSymbol(functionPtr, #functionPtr)
Macro to translate the given pointer value name of functions to requested function name.
Note
This should always be used and does the work of kodi::tools::CDllHelper::RegisterSymbol().
Function Documentation
CDllHelper()
kodi::tools::CDllHelper::CDllHelper () default
Class constructor.
LoadDll()
bool kodi::tools::CDllHelper::LoadDll (std::string path) inline
Function to load requested library.
Parameters
[in] path The path with filename of shared library to load
Returns
true if load was successful done
References ADDON_LOG_DEBUG, ADDON_LOG_ERROR, kodi::vfs::CopyFile(), kodi::vfs::FileExists(), kodi::vfs::GetFileName(), kodi::vfs::FileStatus::GetModificationTime(), kodi::vfs::FileStatus::GetSize(), kodi::Log(), kodi::vfs::StatFile(), and kodi::vfs::TranslateSpecialProtocol().
RegisterSymbol()
template<typename T > bool kodi::tools::CDllHelper::RegisterSymbol (T & functionPtr, const char * strFunctionPtr) inline
Function to register requested library symbol.
Warning
This function should not be used, use instead the macro REGISTER_DLL_SYMBOL to register the symbol pointer.
Use this always via Macro, e.g.:
if (!REGISTER_DLL_SYMBOL(Init))
  return false;
References ADDON_LOG_ERROR, and kodi::Log().
~CDllHelper()
virtual kodi::tools::CDllHelper::~CDllHelper () inline virtual
Class destructor.