Kodi Documentation: CDatabaseManager Class Reference
CDatabaseManager Class Reference
Database
Database manager class for handling database updating.
#include <DatabaseManager.h>
Public Member Functions
CDatabaseManager ()
CDatabaseManager (const CDatabaseManager &)=delete
CDatabaseManager const & operator= (CDatabaseManager const &)=delete
~CDatabaseManager ()
void Initialize ()
Initialize the database manager Checks that all databases are up to date, otherwise updates them.
bool CanOpen (const std::string &name)
Check whether we can open a database.
bool IsUpgrading () const
void LocalizationChanged ()
Private Types
enum DB_STATUS { DB_CLOSED , DB_UPDATING , DB_READY , DB_FAILED }
Private Member Functions
void UpdateStatus (const std::string &name, DB_STATUS status)
void UpdateDatabase (CDatabase &db, DatabaseSettings *settings=NULL)
bool Update (CDatabase &db, const DatabaseSettings &settings)
bool UpdateVersion (CDatabase &db, const std::string &dbName)
Private Attributes
std::atomic< bool > m_bIsUpgrading
CCriticalSection m_section
Critical section protecting m_dbStatus.
std::map< std::string, DB_STATUS > m_dbStatus
Our database status map.
Detailed Description
Database manager class for handling database updating.
Ensures that databases used in XBMC are up to date, and if a database can't be opened, ensures we don't continuously try it.
Member Enumeration Documentation
DB_STATUS
enum CDatabaseManager::DB_STATUS private
Enumerator
DB_CLOSED
DB_UPDATING
DB_READY
DB_FAILED
Constructor & Destructor Documentation
CDatabaseManager() [1/2]
CDatabaseManager::CDatabaseManager ()
References UpdateDatabase().
CDatabaseManager() [2/2]
CDatabaseManager::CDatabaseManager (const CDatabaseManager &) delete
~CDatabaseManager()
CDatabaseManager::~CDatabaseManager () default
Member Function Documentation
CanOpen()
bool CDatabaseManager::CanOpen (const std::string & name)
Check whether we can open a database.
Checks whether the database has been updated correctly, if so returns true. If the database update failed, returns false immediately. If the database update is in progress, returns false.
Parameters
name the name of the database to check.
Returns
true if the database can be opened, false otherwise.
References DB_READY, m_dbStatus, m_section, and name.
Initialize()
void CDatabaseManager::Initialize ()
Initialize the database manager Checks that all databases are up to date, otherwise updates them.
References CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, m_bIsUpgrading, m_dbStatus, m_section, and UpdateDatabase().
Referenced by CApplication::Initialize(), and CProfileManager::LoadProfile().
IsUpgrading()
bool CDatabaseManager::IsUpgrading () const inline
References m_bIsUpgrading.
Referenced by CApplication::Initialize().
LocalizationChanged()
void CDatabaseManager::LocalizationChanged ()
References CLog::Log(), LOGDEBUG, m_section, CVideoDatabase::Open(), and CVideoDatabase::UpdateVideoVersionTypeTable().
Referenced by CLangInfo::SetLanguage().
operator=()
CDatabaseManager const & CDatabaseManager::operator= (CDatabaseManager const &) delete
Update()
bool CDatabaseManager::Update (CDatabase & db, const DatabaseSettings & settings) private
References CDatabase::Close(), CDatabase::Connect(), CDatabase::CopyDB(), CDatabase::GetMinSchemaVersion(), CDatabase::GetSchemaVersion(), CDatabase::InitSettings(), CLog::Log(), LOGERROR, LOGINFO, m_bIsUpgrading, DatabaseSettings::name, and UpdateVersion().
UpdateDatabase()
void CDatabaseManager::UpdateDatabase (CDatabase & db, DatabaseSettings * settings = NULL) private
References DB_FAILED, DB_READY, DB_UPDATING, CDatabase::GetBaseDBName(), name, Update, and UpdateStatus().
Referenced by CDatabaseManager(), and Initialize().
UpdateStatus()
void CDatabaseManager::UpdateStatus (const std::string & name, DB_STATUS status) private
References m_dbStatus, m_section, and name.
Referenced by UpdateDatabase().
UpdateVersion()
bool CDatabaseManager::UpdateVersion (CDatabase & db, const std::string & dbName) private
References CDatabase::BeginTransaction(), CDatabase::CommitTransaction(), CDatabase::CreateAnalytics(), CDatabase::DropAnalytics(), CDatabase::GetDBVersion(), CDatabase::GetMinSchemaVersion(), CDatabase::GetSchemaVersion(), CLog::Log(), LOGERROR, LOGINFO, CDatabase::RollbackTransaction(), success, CDatabase::UpdateTables(), and CDatabase::UpdateVersionNumber().
Referenced by Update().
Member Data Documentation
m_bIsUpgrading
std::atomic<bool> CDatabaseManager::m_bIsUpgrading private
Referenced by Initialize(), IsUpgrading(), and Update().
m_dbStatus
std::map<std::string, DB_STATUS> CDatabaseManager::m_dbStatus private
Our database status map.
Referenced by CanOpen(), Initialize(), and UpdateStatus().
m_section
CCriticalSection CDatabaseManager::m_section private
Critical section protecting m_dbStatus.
Referenced by CanOpen(), Initialize(), LocalizationChanged(), and UpdateStatus().
The documentation for this class was generated from the following files:
DatabaseManager.h
DatabaseManager.cpp