Kodi Documentation: CCoreAudioHardware Class Reference
CCoreAudioHardware Class Reference
#include <CoreAudioHardware.h>
Static Public Member Functions
static bool GetAutoHogMode ()
static void SetAutoHogMode (bool enable)
static AudioStreamBasicDescription * FormatsList (AudioStreamID stream)
static AudioStreamID * StreamsList (AudioDeviceID device)
static void ResetAudioDevices ()
static void ResetStream (AudioStreamID streamId)
static AudioDeviceID FindAudioDevice (const std::string &deviceName)
static AudioDeviceID GetDefaultOutputDevice ()
static void GetOutputDeviceName (std::string &name)
static UInt32 GetOutputDevices (CoreAudioDeviceList *pList)
Member Function Documentation
FindAudioDevice()
AudioDeviceID CCoreAudioHardware::FindAudioDevice (const std::string & deviceName) static
References GetDefaultOutputDevice(), GetError(), CCoreAudioDevice::GetName(), CLog::Log(), LOGDEBUG, LOGERROR, and CCoreAudioDevice::Open().
FormatsList()
static AudioStreamBasicDescription * CCoreAudioHardware::FormatsList (AudioStreamID stream) static
GetAutoHogMode()
bool CCoreAudioHardware::GetAutoHogMode () static
References GetError(), CLog::Log(), and LOGERROR.
Referenced by CAESinkDARWINOSX::SetHogMode().
GetDefaultOutputDevice()
AudioDeviceID CCoreAudioHardware::GetDefaultOutputDevice () static
References GetError(), CLog::Log(), and LOGERROR.
Referenced by deviceChangedCB(), EnumerateDevices(), FindAudioDevice(), GetOutputDeviceName(), and CAESinkDARWINOSX::Initialize().
GetOutputDeviceName()
void CCoreAudioHardware::GetOutputDeviceName (std::string & name) static
References CDarwinUtils::CFStringRefToUTF8String(), GetDefaultOutputDevice(), and name.
Referenced by EnumerateDevices(), and CAESinkDARWINOSX::Initialize().
GetOutputDevices()
UInt32 CCoreAudioHardware::GetOutputDevices (CoreAudioDeviceList * pList) static
References GetError(), CCoreAudioDevice::GetTotalOutputChannels(), CLog::Log(), and LOGERROR.
Referenced by EnumerateDevices(), and ResetAudioDevices().
ResetAudioDevices()
void CCoreAudioHardware::ResetAudioDevices () static
References CCoreAudioDevice::GetName(), GetOutputDevices(), CCoreAudioDevice::GetStreams(), CLog::Log(), LOGDEBUG, and ResetStream().
ResetStream()
void CCoreAudioHardware::ResetStream (AudioStreamID streamId) static
References CCoreAudioStream::Close(), CCoreAudioStream::GetAvailablePhysicalFormats(), CCoreAudioStream::GetPhysicalFormat(), CLog::Log(), LOGDEBUG, CCoreAudioStream::Open(), and CCoreAudioStream::SetPhysicalFormat().
Referenced by ResetAudioDevices().
SetAutoHogMode()
void CCoreAudioHardware::SetAutoHogMode (bool enable) static
References GetError(), CLog::Log(), and LOGERROR.
Referenced by CCoreAudioDevice::Close(), and CAESinkDARWINOSX::SetHogMode().
StreamsList()
static AudioStreamID * CCoreAudioHardware::StreamsList (AudioDeviceID device) static
The documentation for this class was generated from the following files:
CoreAudioHardware.h
CoreAudioHardware.cpp