Kodi Documentation: PVR::CPVRStreamProperties Class Reference
PVR::CPVRStreamProperties Class Reference
#include <PVRStreamProperties.h>
Public Member Functions
CPVRStreamProperties ()=default
virtual ~CPVRStreamProperties ()=default
std::string GetStreamURL () const
Obtain the URL of the stream.
std::string GetStreamMimeType () const
Obtain the MIME type of the stream.
bool EPGPlaybackAsLive () const
If props are from an EPG tag indicates if playback should be as live playback would be.
bool LivePlaybackAsEPG () const
If props are from an channel indicates if playback should be as a video playback would be.
Constructor & Destructor Documentation
CPVRStreamProperties()
PVR::CPVRStreamProperties::CPVRStreamProperties () default
~CPVRStreamProperties()
virtual PVR::CPVRStreamProperties::~CPVRStreamProperties () virtual default
Member Function Documentation
EPGPlaybackAsLive()
bool CPVRStreamProperties::EPGPlaybackAsLive () const
If props are from an EPG tag indicates if playback should be as live playback would be.
Returns
true if it should be played back as live, false otherwise.
References PVR_STREAM_PROPERTY_EPGPLAYBACKASLIVE.
Referenced by PVR::CPVRGUIActionsPlayback::PlayEpgTag().
GetStreamMimeType()
std::string CPVRStreamProperties::GetStreamMimeType () const
Obtain the MIME type of the stream.
Returns
The stream's MIME type or empty string, if not found.
References PVR_STREAM_PROPERTY_MIMETYPE.
Referenced by PVR::CPVRPlaybackState::StartPlayback().
GetStreamURL()
std::string CPVRStreamProperties::GetStreamURL () const
Obtain the URL of the stream.
Returns
The stream URL or empty string, if not found.
References PVR_STREAM_PROPERTY_STREAMURL.
Referenced by PVR::CPVRPlaybackState::StartPlayback().
LivePlaybackAsEPG()
bool CPVRStreamProperties::LivePlaybackAsEPG () const
If props are from an channel indicates if playback should be as a video playback would be.
Returns
true if it should be played back as live, false otherwise.
References PVR_STREAM_PROPERTY_LIVEPLAYBACKASEPG.
Referenced by PVR::CPVRPlaybackState::StartPlayback().
The documentation for this class was generated from the following files:
PVRStreamProperties.h
PVRStreamProperties.cpp