Kodi Documentation: MUSIC_INFO::CMusicInfoTagLoaderCDDA Class Reference
MUSIC_INFO::CMusicInfoTagLoaderCDDA Class Reference
#include <MusicInfoTagLoaderCDDA.h>
Public Member Functions
CMusicInfoTagLoaderCDDA (void)
~CMusicInfoTagLoaderCDDA () override
bool Load (const std::string &strFileName, CMusicInfoTag &tag, EmbeddedArt *art=NULL) override
Public Member Functions inherited from MUSIC_INFO::IMusicInfoTagLoader
IMusicInfoTagLoader (void)=default
virtual ~IMusicInfoTagLoader ()=default
Constructor & Destructor Documentation
CMusicInfoTagLoaderCDDA()
CMusicInfoTagLoaderCDDA::CMusicInfoTagLoaderCDDA (void) default
~CMusicInfoTagLoaderCDDA()
CMusicInfoTagLoaderCDDA::~CMusicInfoTagLoaderCDDA () override default
Member Function Documentation
Load()
bool CMusicInfoTagLoaderCDDA::Load (const std::string & strFileName, CMusicInfoTag & tag, EmbeddedArt * art = NULL) override virtual
Implements MUSIC_INFO::IMusicInfoTagLoader.
References MEDIA_DETECT::TRACKINFO::cdtext, CDTEXT_FIELD_GENRE, CDTEXT_FIELD_PERFORMER, CDTEXT_FIELD_TITLE, MEDIA_DETECT::CCdInfo::GetDiscCDTextInformation(), CDDB::Xcddb::getDiskArtist(), CDDB::Xcddb::getDiskTitle(), CDDB::Xcddb::getGenre(), CServiceBroker::GetMediaManager(), CServiceBroker::GetSettingsComponent(), CDDB::Xcddb::getTrackArtist(), MEDIA_DETECT::CCdInfo::GetTrackInformation(), CDDB::Xcddb::getTrackTitle(), CDDB::Xcddb::getYear(), MEDIA_DETECT::CCdInfo::HasCDDBInfo(), CDDB::Xcddb::isCDCached(), CLog::Log(), LOGERROR, MEDIA_DETECT::TRACKINFO::nMins, MEDIA_DETECT::TRACKINFO::nSecs, CDDB::Xcddb::queryCDinfo(), and CDDB::Xcddb::setCacheDir().
The documentation for this class was generated from the following files:
MusicInfoTagLoaderCDDA.h
MusicInfoTagLoaderCDDA.cpp