Kodi Documentation: CDVDOverlayCodecFFmpeg Class Reference
CDVDOverlayCodecFFmpeg Class Reference
#include <DVDOverlayCodecFFmpeg.h>
Public Member Functions
CDVDOverlayCodecFFmpeg ()
~CDVDOverlayCodecFFmpeg () override
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
OverlayMessage Decode (DemuxPacket *pPacket) override
void Reset () override
void Flush () override
std::shared_ptr< CDVDOverlay > GetOverlay () override
Public Member Functions inherited from CDVDOverlayCodec
CDVDOverlayCodec (const char *name)
virtual ~CDVDOverlayCodec ()=default
const std::string & GetName () const
Private Attributes
AVCodecContext * m_pCodecContext
AVSubtitle m_Subtitle
int m_SubtitleIndex
double m_StartTime
double m_StopTime
int m_width
int m_height
Additional Inherited Members
Static Protected Member Functions inherited from CDVDOverlayCodec
static void GetAbsoluteTimes (double &starttime, double &stoptime, DemuxPacket *pkt)
Constructor & Destructor Documentation
CDVDOverlayCodecFFmpeg()
CDVDOverlayCodecFFmpeg::CDVDOverlayCodecFFmpeg ()
References m_height, m_pCodecContext, m_StartTime, m_StopTime, m_Subtitle, m_SubtitleIndex, and m_width.
~CDVDOverlayCodecFFmpeg()
CDVDOverlayCodecFFmpeg::~CDVDOverlayCodecFFmpeg () override
References m_pCodecContext, and m_Subtitle.
Member Function Documentation
Decode()
OverlayMessage CDVDOverlayCodecFFmpeg::Decode (DemuxPacket * pPacket) override virtual
Implements CDVDOverlayCodec.
References DEMUX_PACKET::dts, DVD_MSEC_TO_TIME(), DVD_NOPTS_VALUE, Flush(), CDVDOverlayCodec::GetAbsoluteTimes(), int64_t(), DEMUX_PACKET::iSize, CLog::Log(), LOGERROR, LOGWARNING, m_pCodecContext, m_StartTime, m_StopTime, m_Subtitle, m_SubtitleIndex, OC_BUFFER, OC_ERROR, OC_OVERLAY, DEMUX_PACKET::pData, and DEMUX_PACKET::pts.
Flush()
void CDVDOverlayCodecFFmpeg::Flush () override virtual
Implements CDVDOverlayCodec.
References m_pCodecContext, m_Subtitle, and m_SubtitleIndex.
Referenced by Decode(), and Reset().
GetOverlay()
std::shared_ptr< CDVDOverlay > CDVDOverlayCodecFFmpeg::GetOverlay () override virtual
Implements CDVDOverlayCodec.
References DVDOVERLAY_TYPE_NONE, Endian_SwapLE32, CWinSystemBase::GetGfxContext(), CGraphicContext::GetStereoMode(), CServiceBroker::GetWinSystem(), m_height, m_pCodecContext, m_StartTime, m_StopTime, m_Subtitle, m_SubtitleIndex, m_width, RENDER_STEREO_MODE_HARDWAREBASED, RENDER_STEREO_MODE_OFF, and t.
Open()
bool CDVDOverlayCodecFFmpeg::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Implements CDVDOverlayCodec.
References CDVDStreamInfo::codec, CDVDStreamInfo::codec_tag, DVD_TIME_BASE, CDVDStreamInfo::extradata, FFmpegExtraData::GetData(), FFmpegExtraData::GetSize(), CLog::Log(), LOGDEBUG, and m_pCodecContext.
Reset()
void CDVDOverlayCodecFFmpeg::Reset () override virtual
Implements CDVDOverlayCodec.
References Flush().
Member Data Documentation
m_height
int CDVDOverlayCodecFFmpeg::m_height private
Referenced by CDVDOverlayCodecFFmpeg(), and GetOverlay().
m_pCodecContext
AVCodecContext* CDVDOverlayCodecFFmpeg::m_pCodecContext private
Referenced by CDVDOverlayCodecFFmpeg(), Decode(), Flush(), GetOverlay(), Open(), and ~CDVDOverlayCodecFFmpeg().
m_StartTime
double CDVDOverlayCodecFFmpeg::m_StartTime private
Referenced by CDVDOverlayCodecFFmpeg(), Decode(), and GetOverlay().
m_StopTime
double CDVDOverlayCodecFFmpeg::m_StopTime private
Referenced by CDVDOverlayCodecFFmpeg(), Decode(), and GetOverlay().
m_Subtitle
AVSubtitle CDVDOverlayCodecFFmpeg::m_Subtitle private
Referenced by CDVDOverlayCodecFFmpeg(), Decode(), Flush(), GetOverlay(), and ~CDVDOverlayCodecFFmpeg().
m_SubtitleIndex
int CDVDOverlayCodecFFmpeg::m_SubtitleIndex private
Referenced by CDVDOverlayCodecFFmpeg(), Decode(), Flush(), and GetOverlay().
m_width
int CDVDOverlayCodecFFmpeg::m_width private
Referenced by CDVDOverlayCodecFFmpeg(), and GetOverlay().
The documentation for this class was generated from the following files:
DVDOverlayCodecFFmpeg.h
DVDOverlayCodecFFmpeg.cpp