Kodi Documentation: XFILE::CZipFile Class Reference
XFILE::CZipFile Class Reference
#include <ZipFile.h>
Public Member Functions
CZipFile ()
~CZipFile () override
int64_t GetPosition () override
int64_t GetLength () override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (struct __stat64 *buffer) override
int Stat (const CURL &url, struct __stat64 *buffer) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
void Close () override
int UnpackFromMemory (std::string &strDest, const std::string &strInput, bool isGZ=false)
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool OpenForWrite (const CURL &url, bool bOverWrite=false)
virtual bool ReOpen (const CURL &url)
virtual ssize_t Write (const void *bufPtr, size_t bufSize)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool Delete (const CURL &url)
virtual bool Rename (const CURL &url, const CURL &urlnew)
virtual bool SetHidden (const CURL &url, bool hidden)
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Static Public Member Functions
static bool DecompressGzip (const std::string &in, std::string &out)
Private Member Functions
bool InitDecompress ()
bool FillBuffer ()
void DestroyBuffer (void *lpBuffer, int iBufSize)
Private Attributes
CFile mFile
SZipEntry mZipItem
int64_t m_iFilePos = 0
int64_t m_iZipFilePos = 0
int m_iAvailBuffer = 0
z_stream m_ZStream
char m_szBuffer [65535]
char * m_szStringBuffer
char * m_szStartOfStringBuffer
size_t m_iDataInStringBuffer
int m_iRead
bool m_bFlush = false
bool m_bCached
Constructor & Destructor Documentation
CZipFile()
CZipFile::CZipFile ()
References m_bCached, m_iDataInStringBuffer, m_iRead, m_szStartOfStringBuffer, and m_szStringBuffer.
~CZipFile()
CZipFile::~CZipFile () override
References Close(), and m_szStringBuffer.
Member Function Documentation
Close()
void CZipFile::Close () override virtual
Implements XFILE::IFile.
References XFILE::CFile::Close(), m_bCached, m_iRead, m_ZStream, SZipEntry::method, mFile, and mZipItem.
Referenced by Read(), UnpackFromMemory(), and ~CZipFile().
DecompressGzip()
bool CZipFile::DecompressGzip (const std::string & in, std::string & out) static
Decompress gzip encoded buffer in-memory
References err(), CLog::Log(), and LOGERROR.
Referenced by ADDON::CRepository::FetchIndex().
DestroyBuffer()
void CZipFile::DestroyBuffer (void * lpBuffer, int iBufSize) private
References m_bFlush, and m_ZStream.
Exists()
bool CZipFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References g_ZipManager, and CZipManager::GetZipEntry().
FillBuffer()
bool CZipFile::FillBuffer () private
References SZipEntry::csize, m_iZipFilePos, m_szBuffer, m_ZStream, mFile, mZipItem, and XFILE::CFile::Read().
Referenced by Read().
GetLength()
int64_t CZipFile::GetLength () override virtual
Implements XFILE::IFile.
References mZipItem, and SZipEntry::usize.
GetPosition()
int64_t CZipFile::GetPosition () override virtual
Implements XFILE::IFile.
References XFILE::CFile::GetPosition(), m_bCached, m_iFilePos, and mFile.
InitDecompress()
bool CZipFile::InitDecompress () private
References CLog::Log(), LOGERROR, m_bFlush, m_iAvailBuffer, m_iFilePos, m_iRead, m_iZipFilePos, m_szBuffer, m_ZStream, SZipEntry::method, and mZipItem.
Referenced by Open(), and UnpackFromMemory().
Open()
bool CZipFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References XFILE::CFile::Copy(), XFILE::CFile::Exists(), SZipEntry::flags, g_ZipManager, URIUtils::GetFileName(), CURL::GetHostName(), CURL::GetOptions(), CZipManager::GetZipEntry(), InitDecompress(), CLog::Log(), LOGERROR, m_bCached, SZipEntry::method, mFile, mZipItem, SZipEntry::offset, XFILE::CFile::Open(), XFILE::CFile::Seek(), CURL::SetOptions(), SZipEntry::usize, and ZIP_CACHE_LIMIT.
Read()
ssize_t CZipFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References Close(), SZipEntry::csize, FillBuffer(), m_bCached, m_bFlush, m_iDataInStringBuffer, m_iFilePos, m_iZipFilePos, m_szStartOfStringBuffer, m_ZStream, SZipEntry::method, mFile, mZipItem, XFILE::CFile::Read(), and SSIZE_MAX.
Referenced by Seek(), and UnpackFromMemory().
Seek()
int64_t CZipFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
References int64_t(), m_bCached, m_iFilePos, m_iZipFilePos, m_szBuffer, m_ZStream, SZipEntry::method, mFile, mZipItem, SZipEntry::offset, Read(), XFILE::CFile::Seek(), Seek(), and SZipEntry::usize.
Referenced by Seek().
Stat() [1/2]
int CZipFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References _S_IFDIR, XFILE::CFile::Exists(), g_ZipManager, CURL::GetFileName(), CURL::GetHostName(), CZipManager::GetZipEntry(), SZipEntry::mod_time, mZipItem, and SZipEntry::usize.
Stat() [2/2]
int CZipFile::Stat (struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about currently open file For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Reimplemented from XFILE::IFile.
References SZipEntry::crc32, mFile, SZipEntry::mod_date, SZipEntry::mod_time, mZipItem, XFILE::CFile::Stat(), and SZipEntry::usize.
UnpackFromMemory()
int CZipFile::UnpackFromMemory (std::string & strDest, const std::string & strInput, bool isGZ = false)
References Close(), SZipEntry::crc32, SZipEntry::csize, DREC_SIZE, SZipEntry::elength, SZipEntry::flags, SZipEntry::flength, SZipEntry::header, InitDecompress(), LHDR_SIZE, CLog::Log(), LOGERROR, m_ZStream, mZipItem, Read(), CZipManager::readHeader(), SZipEntry::usize, ZIP_DATA_RECORD_HEADER, and ZIP_LOCAL_HEADER.
Referenced by CScraperUrl::Get(), and TEST_F().
Member Data Documentation
m_bCached
bool XFILE::CZipFile::m_bCached private
Referenced by Close(), CZipFile(), GetPosition(), Open(), Read(), and Seek().
m_bFlush
bool XFILE::CZipFile::m_bFlush = false private
Referenced by DestroyBuffer(), InitDecompress(), and Read().
m_iAvailBuffer
int XFILE::CZipFile::m_iAvailBuffer = 0 private
Referenced by InitDecompress().
m_iDataInStringBuffer
size_t XFILE::CZipFile::m_iDataInStringBuffer private
Referenced by CZipFile(), and Read().
m_iFilePos
int64_t XFILE::CZipFile::m_iFilePos = 0 private
Referenced by GetPosition(), InitDecompress(), Read(), and Seek().
m_iRead
int XFILE::CZipFile::m_iRead private
Referenced by Close(), CZipFile(), and InitDecompress().
m_iZipFilePos
int64_t XFILE::CZipFile::m_iZipFilePos = 0 private
Referenced by FillBuffer(), InitDecompress(), Read(), and Seek().
m_szBuffer
char XFILE::CZipFile::m_szBuffer[65535] private
Referenced by FillBuffer(), InitDecompress(), and Seek().
m_szStartOfStringBuffer
char* XFILE::CZipFile::m_szStartOfStringBuffer private
Referenced by CZipFile(), and Read().
m_szStringBuffer
char* XFILE::CZipFile::m_szStringBuffer private
Referenced by CZipFile(), and ~CZipFile().
m_ZStream
z_stream XFILE::CZipFile::m_ZStream private
Referenced by Close(), DestroyBuffer(), FillBuffer(), InitDecompress(), Read(), Seek(), and UnpackFromMemory().
mFile
CFile XFILE::CZipFile::mFile private
Referenced by Close(), FillBuffer(), GetPosition(), Open(), Read(), Seek(), and Stat().
mZipItem
SZipEntry XFILE::CZipFile::mZipItem private
Referenced by Close(), FillBuffer(), GetLength(), InitDecompress(), Open(), Read(), Seek(), Stat(), Stat(), and UnpackFromMemory().
The documentation for this class was generated from the following files:
ZipFile.h
ZipFile.cpp