Kodi Documentation: kodi::addon::PVRSettingDefinition Class Reference
kodi::addon::PVRSettingDefinition Class Reference
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General » class PVRSettingDefinition
#include <General.h>
Public Member Functions
PVRSettingDefinition (unsigned int settingDefId, const std::string &settingDefName, uint64_t readonlyConditions, const PVRIntSettingDefinition &settingDef)
Class constructor with integrated values.
PVRSettingDefinition (unsigned int settingDefId, const std::string &settingDefName, uint64_t readonlyConditions, const PVRStringSettingDefinition &settingDef)
Class constructor with integrated values.
PVRSettingDefinition (unsigned int settingDefId, const std::string &settingDefName, PVR_SETTING_TYPE eType, uint64_t readonlyConditions, const PVRIntSettingDefinition &intSettingDef, const PVRStringSettingDefinition &stringSettingDef)
Class constructor with integrated values.
void SetId (unsigned int defId)
required
This setting definition's identifier.
unsigned int GetId () const
To get with SetId changed values.
void SetName (const std::string &name)
required
A short localized string with the name of the setting.
std::string GetName () const
To get with SetName changed values.
void SetType (PVR_SETTING_TYPE eType)
required
This setting definition's identifier.
PVR_SETTING_TYPE GetType () const
To get with SetType changed values.
void SetReadonlyConditions (uint64_t conditions)
optional
The read-only conditions value for this setting. PVR_SETTING_READONLY_CONDITION_* enum values
uint64_t GetReadonlyConditions () const
To get with SetReadonlyConditions changed values.
void SetIntDefinition (const PVRIntSettingDefinition &def)
optional
PVRIntSettingDefinition GetIntDefinition () const
To get with SetIntDefinition changed values.
void SetStringDefinition (const PVRStringSettingDefinition &def)
optional
PVRStringSettingDefinition GetStringDefinition () const
To get with SetStringDefinition changed values.
Public Member Functions inherited from kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >
DynamicCStructHdl ()
DynamicCStructHdl (const DynamicCStructHdl &cppClass)
DynamicCStructHdl (const PVR_SETTING_DEFINITION *cStructure)
DynamicCStructHdl (PVR_SETTING_DEFINITION *cStructure)
const DynamicCStructHdl & operator= (const DynamicCStructHdl &right)
const DynamicCStructHdl & operator= (const PVR_SETTING_DEFINITION &right)
virtual ~DynamicCStructHdl ()
operator PVR_SETTING_DEFINITION * ()
operator const PVR_SETTING_DEFINITION * () const
const PVR_SETTING_DEFINITION * GetCStructure () const
PVR_SETTING_DEFINITION * release ()
Static Public Member Functions
static PVR_SETTING_DEFINITION ** AllocAndCopyData (const std::vector< PVRSettingDefinition > &source)
static PVR_SETTING_DEFINITION ** AllocAndCopyData (PVR_SETTING_DEFINITION **source, unsigned int size)
static void AllocResources (const PVR_SETTING_DEFINITION *source, PVR_SETTING_DEFINITION *target)
static void FreeResources (PVR_SETTING_DEFINITION *target)
static void FreeResources (PVR_SETTING_DEFINITION **defs, unsigned int size)
static void ReallocAndCopyData (PVR_SETTING_DEFINITION ***source, unsigned int *size, const std::vector< PVRSettingDefinition > &defs)
Private Member Functions
PVRSettingDefinition (const PVR_SETTING_DEFINITION *def)
PVRSettingDefinition (PVR_SETTING_DEFINITION *def)
Friends
class CInstancePVRClient
Additional Inherited Members
Protected Attributes inherited from kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >
PVR_SETTING_DEFINITION * m_cStructure
Constructor & Destructor Documentation
PVRSettingDefinition() [1/2]
kodi::addon::PVRSettingDefinition::PVRSettingDefinition (const PVR_SETTING_DEFINITION * def) inline private
PVRSettingDefinition() [2/2]
kodi::addon::PVRSettingDefinition::PVRSettingDefinition (PVR_SETTING_DEFINITION * def) inline private
Member Function Documentation
AllocAndCopyData() [1/2]
static PVR_SETTING_DEFINITION ** kodi::addon::PVRSettingDefinition::AllocAndCopyData (const std::vector< PVRSettingDefinition > & source) inline static
References AllocResources(), PVR_SETTING_DEFINITION::eType, kodi::addon::DynamicCStructHdl< PVRSettingDefinition, PVR_SETTING_DEFINITION >::GetCStructure(), PVR_SETTING_DEFINITION::iId, and PVR_SETTING_DEFINITION::iReadonlyConditions.
Referenced by kodi::addon::PVRTimerType::AllocResources(), and ReallocAndCopyData().
AllocAndCopyData() [2/2]
static PVR_SETTING_DEFINITION ** kodi::addon::PVRSettingDefinition::AllocAndCopyData (PVR_SETTING_DEFINITION ** source, unsigned int size) inline static
References AllocResources(), PVR_SETTING_DEFINITION::eType, PVR_SETTING_DEFINITION::iId, and PVR_SETTING_DEFINITION::iReadonlyConditions.
AllocResources()
static void kodi::addon::PVRSettingDefinition::AllocResources (const PVR_SETTING_DEFINITION * source, PVR_SETTING_DEFINITION * target) inline static
References kodi::addon::PVRIntSettingDefinition::AllocAndCopyData(), kodi::addon::PVRStringSettingDefinition::AllocAndCopyData(), kodi::addon::AllocAndCopyString(), PVR_SETTING_DEFINITION::intSettingDefinition, PVR_SETTING_DEFINITION::stringSettingDefinition, and PVR_SETTING_DEFINITION::strName.
Referenced by AllocAndCopyData(), and AllocAndCopyData().
FreeResources() [1/2]
static void kodi::addon::PVRSettingDefinition::FreeResources (PVR_SETTING_DEFINITION ** defs, unsigned int size) inline static
References FreeResources().
FreeResources() [2/2]
static void kodi::addon::PVRSettingDefinition::FreeResources (PVR_SETTING_DEFINITION * target) inline static
References kodi::addon::PVRIntSettingDefinition::FreeResources(), kodi::addon::PVRStringSettingDefinition::FreeResources(), kodi::addon::FreeString(), PVR_SETTING_DEFINITION::intSettingDefinition, PVR_SETTING_DEFINITION::stringSettingDefinition, and PVR_SETTING_DEFINITION::strName.
Referenced by FreeResources(), kodi::addon::PVRTimerType::FreeResources(), and ReallocAndCopyData().
ReallocAndCopyData()
static void kodi::addon::PVRSettingDefinition::ReallocAndCopyData (PVR_SETTING_DEFINITION *** source, unsigned int * size, const std::vector< PVRSettingDefinition > & defs) inline static
References AllocAndCopyData(), and FreeResources().
Referenced by kodi::addon::PVRTimerType::SetCustomSettingDefinitions().
Friends And Related Symbol Documentation
CInstancePVRClient
friend class CInstancePVRClient friend
The documentation for this class was generated from the following file:
kodi-dev-kit/include/kodi/addon-instance/pvr/General.h