Kodi Documentation: KODI::WINDOWING::GBM::CDRMEncoder Class Reference
KODI::WINDOWING::GBM::CDRMEncoder Class Reference
#include <DRMEncoder.h>
Classes
struct DrmModeEncoderDeleter
Public Member Functions
CDRMEncoder (int fd, uint32_t encoder)
CDRMEncoder (const CDRMEncoder &)=delete
CDRMEncoder & operator= (const CDRMEncoder &)=delete
~CDRMEncoder ()=default
uint32_t GetEncoderId () const
uint32_t GetCrtcId () const
uint32_t GetPossibleCrtcs () const
Public Member Functions inherited from KODI::WINDOWING::GBM::CDRMObject
CDRMObject (const CDRMObject &)=delete
CDRMObject & operator= (const CDRMObject &)=delete
virtual ~CDRMObject ()=default
std::string GetTypeName () const
std::string GetPropertyName (uint32_t propertyId) const
uint32_t GetId () const
uint32_t GetPropertyId (const std::string &name) const
std::optional< uint64_t > GetPropertyValue (std::string_view name, std::string_view valueName) const
bool SetProperty (const std::string &name, uint64_t value)
bool SupportsProperty (const std::string &name)
Private Attributes
std::unique_ptr< drmModeEncoder, DrmModeEncoderDeleter > m_encoder
Additional Inherited Members
Protected Member Functions inherited from KODI::WINDOWING::GBM::CDRMObject
CDRMObject (int fd)
bool GetProperties (uint32_t id, uint32_t type)
Protected Attributes inherited from KODI::WINDOWING::GBM::CDRMObject
std::unique_ptr< drmModeObjectProperties, DrmModeObjectPropertiesDeleter > m_props
std::vector< std::unique_ptr< drmModePropertyRes, DrmModePropertyResDeleter > > m_propsInfo
int m_fd {-1}
Constructor & Destructor Documentation
CDRMEncoder() [1/2]
CDRMEncoder::CDRMEncoder (int fd, uint32_t encoder) explicit
References m_encoder.
CDRMEncoder() [2/2]
KODI::WINDOWING::GBM::CDRMEncoder::CDRMEncoder (const CDRMEncoder &) delete
~CDRMEncoder()
KODI::WINDOWING::GBM::CDRMEncoder::~CDRMEncoder () default
Member Function Documentation
GetCrtcId()
uint32_t KODI::WINDOWING::GBM::CDRMEncoder::GetCrtcId () const inline
References m_encoder.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::FindCrtc().
GetEncoderId()
uint32_t KODI::WINDOWING::GBM::CDRMEncoder::GetEncoderId () const inline
References m_encoder.
GetPossibleCrtcs()
uint32_t KODI::WINDOWING::GBM::CDRMEncoder::GetPossibleCrtcs () const inline
References m_encoder.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::FindCrtc(), and KODI::WINDOWING::GBM::CDRMUtils::FindPlanes().
operator=()
CDRMEncoder & KODI::WINDOWING::GBM::CDRMEncoder::operator= (const CDRMEncoder &) delete
Member Data Documentation
m_encoder
std::unique_ptr<drmModeEncoder, DrmModeEncoderDeleter> KODI::WINDOWING::GBM::CDRMEncoder::m_encoder private
Referenced by CDRMEncoder(), GetCrtcId(), GetEncoderId(), and GetPossibleCrtcs().
The documentation for this class was generated from the following files:
DRMEncoder.h
DRMEncoder.cpp