Kodi Documentation: CVC1BitstreamParser Class Reference
CVC1BitstreamParser Class Reference
#include <VC1BitstreamParser.h>
Public Member Functions
CVC1BitstreamParser ()
~CVC1BitstreamParser ()=default
void Reset ()
bool IsRecoveryPoint (const uint8_t *buf, int buf_size)
bool IsIFrame (const uint8_t *buf, int buf_size)
Protected Member Functions
bool vc1_parse_frame (const uint8_t *buf, const uint8_t *buf_end, bool sequenceOnly)
Private Attributes
uint8_t m_Profile
uint8_t m_MaxBFrames
uint8_t m_SimpleSkipBits
uint8_t m_AdvInterlace
Constructor & Destructor Documentation
CVC1BitstreamParser()
CVC1BitstreamParser::CVC1BitstreamParser ()
References Reset().
~CVC1BitstreamParser()
CVC1BitstreamParser::~CVC1BitstreamParser () default
Member Function Documentation
IsIFrame()
bool CVC1BitstreamParser::IsIFrame (const uint8_t * buf, int buf_size) inline
References vc1_parse_frame().
IsRecoveryPoint()
bool CVC1BitstreamParser::IsRecoveryPoint (const uint8_t * buf, int buf_size) inline
References vc1_parse_frame().
Reset()
void CVC1BitstreamParser::Reset ()
References m_Profile, and VC1_PROFILE_NOPROFILE.
Referenced by CVC1BitstreamParser().
vc1_parse_frame()
bool CVC1BitstreamParser::vc1_parse_frame (const uint8_t * buf, const uint8_t * buf_end, bool sequenceOnly) protected
References find_start_code(), m_AdvInterlace, m_MaxBFrames, m_Profile, m_SimpleSkipBits, CBitstreamReader::ReadBits(), CBitstreamReader::SkipBits(), VC1_FIELD_INTERLACE, VC1_FRAME, VC1_FRAME_PROGRESSIVE, VC1_PROFILE_ADVANCED, VC1_PROFILE_NOPROFILE, and VC1_SEQUENCE.
Referenced by IsIFrame(), and IsRecoveryPoint().
Member Data Documentation
m_AdvInterlace
uint8_t CVC1BitstreamParser::m_AdvInterlace private
Referenced by vc1_parse_frame().
m_MaxBFrames
uint8_t CVC1BitstreamParser::m_MaxBFrames private
Referenced by vc1_parse_frame().
m_Profile
uint8_t CVC1BitstreamParser::m_Profile private
Referenced by Reset(), and vc1_parse_frame().
m_SimpleSkipBits
uint8_t CVC1BitstreamParser::m_SimpleSkipBits private
Referenced by vc1_parse_frame().
The documentation for this class was generated from the following files:
VC1BitstreamParser.h
VC1BitstreamParser.cpp