Kodi Documentation: CONTEXTMENU::CVideoMarkWatched Struct Reference
CONTEXTMENU::CVideoMarkWatched Struct Reference
#include <ContextMenus.h>
Public Member Functions
CVideoMarkWatched ()
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Constructor & Destructor Documentation
CVideoMarkWatched()
CONTEXTMENU::CVideoMarkWatched::CVideoMarkWatched () inline
Member Function Documentation
Execute()
bool CONTEXTMENU::CVideoMarkWatched::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References CVideoLibraryQueue::GetInstance(), and CVideoLibraryQueue::MarkAsWatched().
IsVisible()
bool CONTEXTMENU::CVideoMarkWatched::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References CVariant::asBoolean(), CFileItem::GetPath(), CVideoInfoTag::GetPlayCount(), CGUIListItem::GetProperty(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CFileItem::IsDeleted(), CFileItem::IsParentFolder(), CFileItem::IsPlugin(), URIUtils::IsPVRRecordingFileOrFolder(), and CGUIListItem::m_bIsFolder.
The documentation for this struct was generated from the following files:
video/ContextMenus.h
video/ContextMenus.cpp