Kodi Documentation: MusicInfoTagLoaderFFmpeg.cpp File Reference
MusicInfoTagLoaderFFmpeg.cpp File Reference
#include "MusicInfoTagLoaderFFmpeg.h"
#include "MusicInfoTag.h"
#include "cores/FFmpeg.h"
#include "filesystem/File.h"
#include "utils/StringUtils.h"
Functions
static int vfs_file_read (void *h, uint8_t *buf, int size)
static int64_t vfs_file_seek (void *h, int64_t pos, int whence)
Function Documentation
vfs_file_read()
static int vfs_file_read (void * h, uint8_t * buf, int size) static
References XFILE::CFile::Read().
Referenced by CVideoTagLoaderFFmpeg::CVideoTagLoaderFFmpeg(), and MUSIC_INFO::CMusicInfoTagLoaderFFmpeg::Load().
vfs_file_seek()
static int64_t vfs_file_seek (void * h, int64_t pos, int whence) static
References XFILE::CFile::GetLength(), and XFILE::CFile::Seek().
Referenced by CVideoTagLoaderFFmpeg::CVideoTagLoaderFFmpeg(), and MUSIC_INFO::CMusicInfoTagLoaderFFmpeg::Load().