Kodi Documentation: ConvUtils.cpp File Reference
ConvUtils.cpp File Reference
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include "PlatformDefs.h"
Functions
DWORD GetLastError ()
void SetLastError (DWORD dwErrCode)
Function Documentation
GetLastError()
DWORD GetLastError ()
Referenced by CWinSystemWin32::AdjustWindow(), dbiplus::MysqlDatabase::connect(), XFILE::CWin32Directory::Create(), CWinSystemWin32::CreateBlankWindows(), CDatabase::CreateDatabase(), CWinSystemWin32::CreateNewWindow(), XFILE::CWin32File::Delete(), XFILE::CCurlFile::Download(), CAESinkXAudio::Drain(), XFILE::CWin32File::Exists(), XFILE::CWin32SMBFile::Exists(), XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CWin32Directory::GetDirectory(), CWIN32Util::GetDriveStatus(), CWinSystemWin32::GetNcAreaOffsets(), CWinSystemWin32::GetScreenWorkArea(), CWinRtUtil::GetWindowsHDRStatus(), anonymous_namespace{AESinkXAudio.cpp}::KXAudio2Create(), Win32DllLoader::Load(), XFILE::CWin32File::Open(), XFILE::CWin32File::OpenForWrite(), CNetworkWin32::PingHost(), CNetworkWin10::PingHost(), XFILE::CFileCache::Process(), XFILE::CWin32SMBDirectory::RealCreate(), XFILE::CWin32SMBDirectory::RealExists(), XFILE::CWin32SMBDirectory::Remove(), XFILE::CWin32Directory::RemoveRecursive(), XFILE::CWin32File::Rename(), CWinSystemWin32::ScreenRect(), XFILE::CWin32File::SetHidden(), XFILE::CWin32SMBFile::SetHidden(), XFILE::CWin32File::Stat(), KODI::PLATFORM::FILESYSTEM::anonymous_namespace{Filesystem.cpp}::temp_directory_path_w(), CWIN32Util::ToggleTray(), TranslateKey(), WinMain(), and CWinEventsWin32::WndProc().
SetLastError()
void SetLastError (DWORD dwErrCode)
Referenced by CWinSystemWin32::AdjustWindow(), CNetworkWin32::PingHost(), and CNetworkWin10::PingHost().