Kodi Documentation: CSeekHandler Class Reference
CSeekHandler Class Reference
#include <SeekHandler.h>
Public Member Functions
CSeekHandler ()=default
~CSeekHandler () override
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
bool OnAction (const CAction &action) override
Handle a GUI action.
void Seek (bool forward, float amount, float duration=0, bool analogSeek=false, SeekType type=SEEK_TYPE_VIDEO)
void SeekSeconds (int seconds)
void FrameMove ()
void Reset ()
void Configure ()
int GetSeekSize () const
bool InProgress () const
bool HasTimeCode () const
int GetTimeCodeSeconds () const
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from KODI::ACTION::IActionListener
virtual ~IActionListener ()=default
Static Public Member Functions
static void SettingOptionsSeekStepsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
CSeekHandler (const CSeekHandler &)=delete
CSeekHandler & operator= (CSeekHandler const &)=delete
bool SeekTimeCode (const CAction &action)
void ChangeTimeCode (int remote)
Private Member Functions
void SetSeekSize (double seekSize)
int GetSeekStepSize (SeekType type, int step)
Private Attributes
int m_seekDelay = 500
std::map< SeekType, int > m_seekDelays
bool m_requireSeek = false
bool m_seekChanged = false
bool m_analogSeek = false
double m_seekSize = 0
int m_seekStep = 0
std::map< SeekType, std::vector< int > > m_forwardSeekSteps
std::map< SeekType, std::vector< int > > m_backwardSeekSteps
CStopWatch m_timer
CStopWatch m_timerTimeCode
int m_timeCodeStamp [6]
int m_timeCodePosition
CCriticalSection m_critSection
Static Private Attributes
static const int analogSeekDelay = 500
Constructor & Destructor Documentation
CSeekHandler() [1/2]
CSeekHandler::CSeekHandler () default
~CSeekHandler()
CSeekHandler::~CSeekHandler () override
References m_backwardSeekSteps, m_forwardSeekSteps, and m_seekDelays.
CSeekHandler() [2/2]
CSeekHandler::CSeekHandler (const CSeekHandler &) protected delete
Member Function Documentation
ChangeTimeCode()
void CSeekHandler::ChangeTimeCode (int remote) protected
References ACTION_JUMP_SMS2, ACTION_JUMP_SMS9, m_timeCodePosition, m_timeCodeStamp, m_timerTimeCode, REMOTE_0, REMOTE_2, REMOTE_9, and CStopWatch::StartZero().
Referenced by OnAction().
Configure()
void CSeekHandler::Configure ()
References CServiceBroker::GetSettingsComponent(), m_backwardSeekSteps, m_forwardSeekSteps, m_seekDelays, Reset(), SEEK_TYPE_MUSIC, SEEK_TYPE_VIDEO, CSettings::SETTING_MUSICPLAYER_SEEKDELAY, CSettings::SETTING_MUSICPLAYER_SEEKSTEPS, CSettings::SETTING_VIDEOPLAYER_SEEKDELAY, and CSettings::SETTING_VIDEOPLAYER_SEEKSTEPS.
Referenced by OnSettingChanged().
FrameMove()
void CSeekHandler::FrameMove ()
References CServiceBroker::GetAppComponents(), CStopWatch::GetElapsedMilliseconds(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_STATE_CHANGED, int64_t(), m_critSection, m_requireSeek, m_seekChanged, m_seekDelay, m_seekSize, m_timeCodePosition, m_timer, m_timerTimeCode, Reset(), CApplicationPlayer::SeekTimeRelative(), and CGUIWindowManager::SendMessage().
GetSeekSize()
int CSeekHandler::GetSeekSize () const
References m_seekSize, and MathUtils::round_int().
Referenced by CGUIDialogSeekBar::GetEpgEventProgress(), and PVR::CPVRGUIInfo::GetTimeShiftSeekPercent().
GetSeekStepSize()
int CSeekHandler::GetSeekStepSize (SeekType type, int step) private
References CLog::Log(), LOGERROR, m_backwardSeekSteps, m_forwardSeekSteps, and SEEK_TYPE_VIDEO.
Referenced by Seek().
GetTimeCodeSeconds()
int CSeekHandler::GetTimeCodeSeconds () const
References m_timeCodePosition, and m_timeCodeStamp.
Referenced by SeekTimeCode().
HasTimeCode()
bool CSeekHandler::HasTimeCode () const inline
References m_timeCodePosition.
InProgress()
bool CSeekHandler::InProgress () const
References CServiceBroker::GetDataCacheCore(), CDataCacheCore::IsSeeking(), and m_requireSeek.
OnAction()
bool CSeekHandler::OnAction (const CAction & action) override virtual
Handle a GUI action.
Parameters
action The GUI action
Returns
True if the action was handled, false otherwise
Implements KODI::ACTION::IActionListener.
References ACTION_ANALOG_SEEK_BACK, ACTION_ANALOG_SEEK_FORWARD, ACTION_BIG_STEP_BACK, ACTION_BIG_STEP_FORWARD, ACTION_CHAPTER_OR_BIG_STEP_BACK, ACTION_CHAPTER_OR_BIG_STEP_FORWARD, ACTION_JUMP_SMS2, ACTION_JUMP_SMS3, ACTION_JUMP_SMS4, ACTION_JUMP_SMS5, ACTION_JUMP_SMS6, ACTION_JUMP_SMS7, ACTION_JUMP_SMS8, ACTION_JUMP_SMS9, ACTION_NEXT_SCENE, ACTION_PREV_SCENE, ACTION_SMALL_STEP_BACK, ACTION_STEP_BACK, ACTION_STEP_FORWARD, BACKWARD, ChangeTimeCode(), FORWARD, g_application, CServiceBroker::GetAppComponents(), KODI::MUSIC::IsAudio(), REMOTE_0, REMOTE_1, REMOTE_2, REMOTE_3, REMOTE_4, REMOTE_5, REMOTE_6, REMOTE_7, REMOTE_8, REMOTE_9, Seek(), SEEK_TYPE_MUSIC, SEEK_TYPE_VIDEO, and SeekTimeCode().
OnSettingChanged()
void CSeekHandler::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References Configure(), CSettings::SETTING_MUSICPLAYER_SEEKDELAY, CSettings::SETTING_MUSICPLAYER_SEEKSTEPS, CSettings::SETTING_VIDEOPLAYER_SEEKDELAY, and CSettings::SETTING_VIDEOPLAYER_SEEKSTEPS.
operator=()
CSeekHandler & CSeekHandler::operator= (CSeekHandler const &) protected delete
Reset()
void CSeekHandler::Reset ()
References m_analogSeek, m_requireSeek, m_seekSize, m_seekStep, and m_timeCodePosition.
Referenced by Configure(), FrameMove(), Seek(), SeekSeconds(), and SeekTimeCode().
Seek()
void CSeekHandler::Seek (bool forward, float amount, float duration = 0, bool analogSeek = false, SeekType type = SEEK_TYPE_VIDEO)
References analogSeekDelay, g_application, CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), GetSeekStepSize(), CServiceBroker::GetWinSystem(), m_analogSeek, m_critSection, m_requireSeek, m_seekChanged, m_seekDelay, m_seekDelays, m_seekSize, m_seekStep, m_timer, Reset(), SeekSeconds(), SetSeekSize(), and CStopWatch::StartZero().
Referenced by OnAction().
SeekSeconds()
void CSeekHandler::SeekSeconds (int seconds)
References CServiceBroker::GetAppComponents(), int64_t(), m_critSection, Reset(), CApplicationPlayer::SeekTimeRelative(), and SetSeekSize().
Referenced by Seek(), Seek(), and SeekTimeCode().
SeekTimeCode()
bool CSeekHandler::SeekTimeCode (const CAction & action) protected
References ACTION_BIG_STEP_BACK, ACTION_BIG_STEP_FORWARD, ACTION_CHAPTER_OR_BIG_STEP_BACK, ACTION_CHAPTER_OR_BIG_STEP_FORWARD, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_PAUSE, ACTION_PLAYER_PLAY, ACTION_SELECT_ITEM, ACTION_SMALL_STEP_BACK, ACTION_STEP_BACK, ACTION_STEP_FORWARD, g_application, GetTimeCodeSeconds(), m_critSection, m_timeCodePosition, Reset(), and SeekSeconds().
Referenced by OnAction().
SetSeekSize()
void CSeekHandler::SetSeekSize (double seekSize) private
References CServiceBroker::GetAppComponents(), CApplicationPlayer::GetTime(), int64_t(), and m_seekSize.
Referenced by Seek(), and SeekSeconds().
SettingOptionsSeekStepsFiller()
void CSeekHandler::SettingOptionsSeekStepsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetSettingsComponent(), and label.
Referenced by CSettings::InitializeOptionFillers().
Member Data Documentation
analogSeekDelay
const int CSeekHandler::analogSeekDelay = 500 static private
Referenced by Seek().
m_analogSeek
bool CSeekHandler::m_analogSeek = false private
Referenced by Reset(), and Seek().
m_backwardSeekSteps
std::map<SeekType, std::vector<int> > CSeekHandler::m_backwardSeekSteps private
Referenced by Configure(), GetSeekStepSize(), and ~CSeekHandler().
m_critSection
CCriticalSection CSeekHandler::m_critSection private
Referenced by FrameMove(), Seek(), SeekSeconds(), and SeekTimeCode().
m_forwardSeekSteps
std::map<SeekType, std::vector<int> > CSeekHandler::m_forwardSeekSteps private
Referenced by Configure(), GetSeekStepSize(), and ~CSeekHandler().
m_requireSeek
bool CSeekHandler::m_requireSeek = false private
Referenced by FrameMove(), InProgress(), Reset(), and Seek().
m_seekChanged
bool CSeekHandler::m_seekChanged = false private
Referenced by FrameMove(), and Seek().
m_seekDelay
int CSeekHandler::m_seekDelay = 500 private
Referenced by FrameMove(), and Seek().
m_seekDelays
std::map<SeekType, int > CSeekHandler::m_seekDelays private
Referenced by Configure(), Seek(), and ~CSeekHandler().
m_seekSize
double CSeekHandler::m_seekSize = 0 private
Referenced by FrameMove(), GetSeekSize(), Reset(), Seek(), and SetSeekSize().
m_seekStep
int CSeekHandler::m_seekStep = 0 private
Referenced by Reset(), and Seek().
m_timeCodePosition
int CSeekHandler::m_timeCodePosition private
Referenced by ChangeTimeCode(), FrameMove(), GetTimeCodeSeconds(), HasTimeCode(), Reset(), and SeekTimeCode().
m_timeCodeStamp
int CSeekHandler::m_timeCodeStamp[6] private
Referenced by ChangeTimeCode(), and GetTimeCodeSeconds().
m_timer
CStopWatch CSeekHandler::m_timer private
Referenced by FrameMove(), and Seek().
m_timerTimeCode
CStopWatch CSeekHandler::m_timerTimeCode private
Referenced by ChangeTimeCode(), and FrameMove().
The documentation for this class was generated from the following files:
SeekHandler.h
SeekHandler.cpp