Kodi Documentation: JSONRPC::CJSONServiceDescription Class Reference
JSONRPC::CJSONServiceDescription Class Reference
Interfaces » JSON-RPC
Helper class for json schema service descriptor based service descriptions for the json rpc API.
#include <JSONServiceDescription.h>
Classes
class CJsonRpcMethodMap
struct IncompleteSchemaDefinition
Static Public Member Functions
static bool AddType (const std::string &jsonType)
Parses the given json schema description and evaluates and stores the defined type.
static bool AddMethod (const std::string &jsonMethod, MethodCall method)
Parses the given json schema description and evaluates and stores the defined method.
static bool AddBuiltinMethod (const std::string &jsonMethod)
Parses the given json schema description and evaluates and stores the defined builtin method.
static bool AddNotification (const std::string &jsonNotification)
Parses the given json schema description and evaluates and stores the defined notification.
static bool AddEnum (const std::string &name, const std::vector< CVariant > &values, CVariant::VariantType type=CVariant::VariantTypeNull, const CVariant &defaultValue=CVariant::ConstNullVariant)
static bool AddEnum (const std::string &name, const std::vector< std::string > &values)
static bool AddEnum (const std::string &name, const std::vector< int > &values)
static const char * GetVersion ()
Gets the version of the json schema description.
static JSONRPC_STATUS Print (CVariant &result, ITransportLayer *transport, IClient *client, bool printDescriptions=true, bool printMetadata=false, bool filterByTransport=true, const std::string &filterByName="", const std::string &filterByType="", bool printReferences=true)
Prints the json schema description into the given result object.
static JSONRPC_STATUS CheckCall (const char *method, const CVariant &requestParameters, ITransportLayer *transport, IClient *client, bool notification, MethodCall &methodCall, CVariant &outputParameters)
Checks the given parameters from the request against the json schema description for the given method.
static JSONSchemaTypeDefinitionPtr GetType (const std::string &identification)
static void ResolveReferences ()
static void Cleanup ()
Static Public Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
Private Types
enum SchemaDefinition { SchemaDefinitionType , SchemaDefinitionMethod }
typedef enum JSONRPC::CJSONServiceDescription::SchemaDefinition SchemaDefinition
typedef struct JSONRPC::CJSONServiceDescription::IncompleteSchemaDefinition IncompleteSchemaDefinition
typedef std::map< std::string, std::vector< IncompleteSchemaDefinition > > IncompleteSchemaDefinitionMap
Static Private Member Functions
static bool prepareDescription (std::string &description, CVariant &descriptionObject, std::string &name)
static bool addMethod (const std::string &jsonMethod, MethodCall method)
static void parseHeader (const CVariant &descriptionObject)
static bool parseJSONSchemaType (const CVariant &value, std::vector< JSONSchemaTypeDefinitionPtr > &typeDefinitions, JSONSchemaType &schemaType, std::string &missingReference)
static void addReferenceTypeDefinition (const JSONSchemaTypeDefinitionPtr &typeDefinition)
static void removeReferenceTypeDefinition (const std::string &typeID)
static void getReferencedTypes (const JSONSchemaTypeDefinitionPtr &type, std::vector< std::string > &referencedTypes)
Static Private Attributes
static CJsonRpcMethodMap m_actionMap
static std::map< std::string, JSONSchemaTypeDefinitionPtr > m_types = std::map<std::string, JSONSchemaTypeDefinitionPtr>()
static std::map< std::string, CVariant > m_notifications = std::map<std::string, CVariant>()
static JsonRpcMethodMap m_methodMaps []
static IncompleteSchemaDefinitionMap m_incompleteDefinitions = CJSONServiceDescription::IncompleteSchemaDefinitionMap()
Friends
class JSONSchemaTypeDefinition
class JsonRpcMethod
Additional Inherited Members
Static Protected Member Functions inherited from JSONRPC::CJSONUtils
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Detailed Description
Helper class for json schema service descriptor based service descriptions for the json rpc API.
Provides static functions to parse a complete json schema service descriptor of a published service containing json rpc methods, print the json schema service descriptor representation into a string (mainly for output purposes) and evaluate and verify parameters provided in a call to one of the publish json rpc methods against a parameter definition parsed from a json schema service descriptor.
Member Typedef Documentation
IncompleteSchemaDefinition
typedef struct JSONRPC::CJSONServiceDescription::IncompleteSchemaDefinition JSONRPC::CJSONServiceDescription::IncompleteSchemaDefinition private
IncompleteSchemaDefinitionMap
typedef std::map<std::string, std::vector<IncompleteSchemaDefinition> > JSONRPC::CJSONServiceDescription::IncompleteSchemaDefinitionMap private
SchemaDefinition
typedef enum JSONRPC::CJSONServiceDescription::SchemaDefinition JSONRPC::CJSONServiceDescription::SchemaDefinition private
Member Enumeration Documentation
SchemaDefinition
enum JSONRPC::CJSONServiceDescription::SchemaDefinition private
Enumerator
SchemaDefinitionType
SchemaDefinitionMethod
Member Function Documentation
AddBuiltinMethod()
bool CJSONServiceDescription::AddBuiltinMethod (const std::string & jsonMethod) static
Parses the given json schema description and evaluates and stores the defined builtin method.
Parameters
jsonMethod json schema description to parse
Returns
True if the json schema description has been parsed successfully otherwise false
References addMethod().
Referenced by JSONRPC::CJSONRPC::Initialize().
AddEnum() [1/3]
bool CJSONServiceDescription::AddEnum (const std::string & name, const std::vector< CVariant > & values, CVariant::VariantType type = CVariant::VariantTypeNull, const CVariant & defaultValue = CVariant::ConstNullVariant) static
References addReferenceTypeDefinition(), JSONRPC::AnyValue, JSONRPC::ArrayValue, JSONRPC::BooleanValue, index(), JSONRPC::IntegerValue, m_types, name, JSONRPC::NumberValue, JSONRPC::ObjectValue, JSONRPC::StringValue, translateType::type, CVariant::type(), types, values, CVariant::VariantTypeArray, CVariant::VariantTypeBoolean, CVariant::VariantTypeConstNull, CVariant::VariantTypeDouble, CVariant::VariantTypeInteger, CVariant::VariantTypeNull, CVariant::VariantTypeObject, CVariant::VariantTypeString, and CVariant::VariantTypeUnsignedInteger.
Referenced by AddEnum(), AddEnum(), and JSONRPC::CJSONRPC::Initialize().
AddEnum() [2/3]
bool CJSONServiceDescription::AddEnum (const std::string & name, const std::vector< int > & values) static
References AddEnum(), name, values, and CVariant::VariantTypeInteger.
AddEnum() [3/3]
bool CJSONServiceDescription::AddEnum (const std::string & name, const std::vector< std::string > & values) static
References AddEnum(), name, values, and CVariant::VariantTypeString.
AddMethod()
bool CJSONServiceDescription::AddMethod (const std::string & jsonMethod, MethodCall method) static
Parses the given json schema description and evaluates and stores the defined method.
Parameters
jsonMethod json schema description to parse
method pointer to the implementation
Returns
True if the json schema description has been parsed successfully otherwise false
References addMethod(), CLog::Log(), and LOGERROR.
Referenced by addReferenceTypeDefinition().
addMethod()
bool CJSONServiceDescription::addMethod (const std::string & jsonMethod, MethodCall method) static private
References JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::add(), JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::end(), JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::find(), JSONRPC::CJSONUtils::GetString(), index(), CLog::Log(), LOGERROR, LOGINFO, m_actionMap, m_incompleteDefinitions, m_methodMaps, JSONRPC::JsonRpcMethod::method, JSONRPC::JsonRpcMethodMap::method, JSONRPC::CJSONServiceDescription::IncompleteSchemaDefinition::Method, JSONRPC::JsonRpcMethod::missingReference, JSONRPC::JsonRpcMethod::name, JSONRPC::JsonRpcMethodMap::name, JSONRPC::JsonRpcMethod::Parse(), prepareDescription(), JSONRPC::CJSONServiceDescription::IncompleteSchemaDefinition::Schema, SchemaDefinitionMethod, and JSONRPC::CJSONServiceDescription::IncompleteSchemaDefinition::Type.
Referenced by AddBuiltinMethod(), and AddMethod().
AddNotification()
bool CJSONServiceDescription::AddNotification (const std::string & jsonNotification) static
Parses the given json schema description and evaluates and stores the defined notification.
Parameters
jsonNotification json schema description to parse
Returns
True if the json schema description has been parsed successfully otherwise false
References JSONRPC::CJSONUtils::GetString(), CLog::Log(), LOGERROR, m_notifications, and prepareDescription().
Referenced by JSONRPC::CJSONRPC::Initialize().
addReferenceTypeDefinition()
void CJSONServiceDescription::addReferenceTypeDefinition (const JSONSchemaTypeDefinitionPtr & typeDefinition) static private
References AddMethod(), AddType(), index(), CLog::Log(), LOGINFO, m_incompleteDefinitions, m_types, and SchemaDefinitionType.
Referenced by AddEnum(), and AddType().
AddType()
bool CJSONServiceDescription::AddType (const std::string & jsonType) static
Parses the given json schema description and evaluates and stores the defined type.
Parameters
jsonType json schema description to parse
Returns
True if the json schema description has been parsed successfully otherwise false
References addReferenceTypeDefinition(), CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, m_incompleteDefinitions, m_types, prepareDescription(), removeReferenceTypeDefinition(), JSONRPC::CJSONServiceDescription::IncompleteSchemaDefinition::Schema, SchemaDefinitionType, and JSONRPC::CJSONServiceDescription::IncompleteSchemaDefinition::Type.
Referenced by addReferenceTypeDefinition(), and JSONRPC::CJSONRPC::Initialize().
CheckCall()
JSONRPC_STATUS CJSONServiceDescription::CheckCall (const char * method, const CVariant & requestParameters, ITransportLayer * transport, IClient * client, bool notification, MethodCall & methodCall, CVariant & outputParameters) static
Checks the given parameters from the request against the json schema description for the given method.
Parameters
method Called method
requestParameters Parameters from the request
client Client who sent the request
notification Whether the request was sent as a notification or not
methodCall Object which will contain the actual C/C++ method to be called
outputParameters Cleaned up parameter list
Returns
OK if the validation of the request succeeded otherwise an appropriate error code
Checks if the given method is a valid json rpc method, if the client has the permission to call this method, if the method can be called as a notification or not, assigns the actual C/C++ implementation of the method to the "methodCall" parameter and checks the given parameters from the request against the json schema description for the given method.
References JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::end(), JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::find(), m_actionMap, and JSONRPC::MethodNotFound.
Referenced by JSONRPC::CJSONRPC::HandleMethodCall().
Cleanup()
void CJSONServiceDescription::Cleanup () static
References JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::clear(), CVariant::clear(), m_actionMap, m_incompleteDefinitions, m_notifications, and m_types.
Referenced by JSONRPC::CJSONRPC::Cleanup().
getReferencedTypes()
void CJSONServiceDescription::getReferencedTypes (const JSONSchemaTypeDefinitionPtr & type, std::vector< std::string > & referencedTypes) static private
References JSONRPC::ArrayValue, getReferencedTypes(), JSONRPC::CJSONUtils::HasType(), index(), and JSONRPC::ObjectValue.
Referenced by getReferencedTypes(), and Print().
GetType()
JSONSchemaTypeDefinitionPtr CJSONServiceDescription::GetType (const std::string & identification) static
References m_types.
Referenced by JSONRPC::JSONSchemaTypeDefinition::Parse().
GetVersion()
const char * CJSONServiceDescription::GetVersion () static
Gets the version of the json schema description.
Returns
Version of the json schema description
Referenced by JSONRPC::CJSONRPC::Initialize(), and JSONRPC::CJSONRPC::Version().
parseHeader()
static void JSONRPC::CJSONServiceDescription::parseHeader (const CVariant & descriptionObject) static private
parseJSONSchemaType()
bool CJSONServiceDescription::parseJSONSchemaType (const CVariant & value, std::vector< JSONSchemaTypeDefinitionPtr > & typeDefinitions, JSONSchemaType & schemaType, std::string & missingReference) static private
References JSONRPC::AnyValue, CLog::Log(), LOGERROR, LOGWARNING, JSONRPC::CJSONUtils::StringToSchemaValueType(), and value.
Referenced by JSONRPC::JSONSchemaTypeDefinition::Parse(), and JSONRPC::JsonRpcMethod::parseReturn().
prepareDescription()
bool CJSONServiceDescription::prepareDescription (std::string & description, CVariant & descriptionObject, std::string & name) static private
References CVariant::begin_map(), CVariant::end_map(), CVariant::isMember(), CVariant::isObject(), CLog::Log(), LOGERROR, name, and CJSONVariantParser::Parse().
Referenced by addMethod(), AddNotification(), and AddType().
Print()
JSONRPC_STATUS CJSONServiceDescription::Print (CVariant & result, ITransportLayer * transport, IClient * client, bool printDescriptions = true, bool printMetadata = false, bool filterByTransport = true, const std::string & filterByName = "", const std::string & filterByType = "", bool printReferences = true) static
Prints the json schema description into the given result object.
Parameters
result Object into which the json schema description is printed
transport Transport layer capabilities
client Client requesting a print
printDescriptions Whether to print descriptions or not
printMetadata Whether to print XBMC specific data or not
filterByTransport Whether to filter by transport or not
References JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::add(), CVariant::append(), JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::begin(), JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::end(), JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::find(), JSONRPC::ITransportLayer::GetCapabilities(), JSONRPC::IClient::GetPermissionFlags(), getReferencedTypes(), index(), JSONRPC::InvalidParams, m_actionMap, m_notifications, m_types, name, JSONRPC::OK, JSONRPC::OPERATION_PERMISSION_ALL, JSONRPC::PermissionToString(), CVariant::push_back(), JSONRPC::ReadData, CVariant::size(), types, CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by CHTTPJsonRpcHandler::HandleRequest(), and JSONRPC::CJSONRPC::Introspect().
removeReferenceTypeDefinition()
void CJSONServiceDescription::removeReferenceTypeDefinition (const std::string & typeID) static private
References m_types.
Referenced by AddType().
ResolveReferences()
void CJSONServiceDescription::ResolveReferences () static
References m_types.
Referenced by JSONRPC::CJSONRPC::Initialize().
Friends And Related Symbol Documentation
JsonRpcMethod
friend class JsonRpcMethod friend
JSONSchemaTypeDefinition
friend class JSONSchemaTypeDefinition friend
Member Data Documentation
m_actionMap
CJSONServiceDescription::CJsonRpcMethodMap CJSONServiceDescription::m_actionMap static private
Referenced by addMethod(), CheckCall(), Cleanup(), and Print().
m_incompleteDefinitions
CJSONServiceDescription::IncompleteSchemaDefinitionMap CJSONServiceDescription::m_incompleteDefinitions = CJSONServiceDescription::IncompleteSchemaDefinitionMap() static private
Referenced by addMethod(), addReferenceTypeDefinition(), AddType(), and Cleanup().
m_methodMaps
JsonRpcMethodMap CJSONServiceDescription::m_methodMaps static private
Referenced by addMethod().
m_notifications
std::map< std::string, CVariant > CJSONServiceDescription::m_notifications = std::map<std::string, CVariant>() static private
Referenced by AddNotification(), Cleanup(), and Print().
m_types
std::map< std::string, JSONSchemaTypeDefinitionPtr > CJSONServiceDescription::m_types = std::map<std::string, JSONSchemaTypeDefinitionPtr>() static private
Referenced by AddEnum(), addReferenceTypeDefinition(), AddType(), Cleanup(), GetType(), Print(), removeReferenceTypeDefinition(), and ResolveReferences().
The documentation for this class was generated from the following files:
JSONServiceDescription.h
JSONServiceDescription.cpp