Kodi Documentation: TimingConstants.h File Reference
TimingConstants.h File Reference
#include <cstdint>
Macros
#define DVD_TIME_BASE 1000000
#define DVD_NOPTS_VALUE 0xFFF0000000000000
#define DVD_PLAYSPEED_PAUSE 0
#define DVD_PLAYSPEED_NORMAL 1000
Functions
constexpr int64_t DVD_TIME_TO_MSEC (double x)
constexpr double DVD_SEC_TO_TIME (double x)
constexpr double DVD_MSEC_TO_TIME (double x)
Macro Definition Documentation
DVD_NOPTS_VALUE
#define DVD_NOPTS_VALUE 0xFFF0000000000000
DVD_PLAYSPEED_NORMAL
#define DVD_PLAYSPEED_NORMAL 1000
DVD_PLAYSPEED_PAUSE
#define DVD_PLAYSPEED_PAUSE 0
DVD_TIME_BASE
#define DVD_TIME_BASE 1000000
Function Documentation
DVD_MSEC_TO_TIME()
constexpr double DVD_MSEC_TO_TIME (double x) constexpr
References DVD_TIME_BASE.
Referenced by CVideoPlayer::CheckContinuity(), CDVDOverlayCodecFFmpeg::Decode(), CDVDClock::ErrorAdjust(), CVideoPlayer::GetCachingTimes(), CDVDAudioCodecPassthrough::GetData(), CVideoPlayer::HandleMessages(), CVideoPlayer::HandlePlaySpeed(), CDVDCodecUtils::NormalizeFrameduration(), CVideoPlayer::Prepare(), CRenderManager::PrepareNextRender(), CVideoPlayerVideo::ProcessDecoderOutput(), CVideoPlayerAudio::ProcessDecoderOutput(), CDVDDemuxVobsub::SeekTime(), CDVDDemuxFFmpeg::SeekTime(), and CVideoPlayer::UpdatePlayState().
DVD_SEC_TO_TIME()
constexpr double DVD_SEC_TO_TIME (double x) constexpr
References DVD_TIME_BASE.
Referenced by CAudioSinkAE::AddPackets(), CVideoPlayer::CheckPlayerInit(), CDVDDemuxVobsub::ParseTimestamp(), CVideoPlayerVideo::Process(), CVideoPlayerSubtitle::Process(), CDVDDemuxFFmpeg::ReadInternal(), and CDVDDemuxFFmpeg::SeekChapter().
DVD_TIME_TO_MSEC()
constexpr int64_t DVD_TIME_TO_MSEC (double x) constexpr
References DVD_TIME_BASE, and int64_t().
Referenced by CDVDSubtitlesLibass::AddEvent(), CDVDSubtitlesLibass::ChangeEventStopTime(), CDVDSubtitlesLibass::DecodeDemuxPkt(), CVideoPlayer::HandleMessages(), CVideoPlayerVideo::OutputPicture(), CVideoPlayer::ProcessAudioData(), CDVDDemuxClient::Read(), CDVDDemuxFFmpeg::ReadInternal(), CRenderManager::Render(), CDVDSubtitlesLibass::RenderImage(), and CDVDDemuxFFmpeg::SeekChapter().