Kodi Documentation: CTextureBundle Class Reference
CTextureBundle Class Reference
#include <TextureBundle.h>
Public Member Functions
CTextureBundle ()
CTextureBundle (bool useXBT)
~CTextureBundle ()=default
void SetThemeBundle (bool themeBundle)
bool HasFile (const std::string &Filename)
std::vector< std::string > GetTexturesFromPath (const std::string &path)
std::optional< CTextureBundleXBT::Texture > LoadTexture (const std::string &filename)
Load texture from bundle.
std::optional< CTextureBundleXBT::Animation > LoadAnim (const std::string &filename)
Load animation from bundle.
void Close ()
Static Public Member Functions
static std::string Normalize (std::string name)
Private Attributes
CTextureBundleXBT m_tbXBT
bool m_useXBT
Constructor & Destructor Documentation
CTextureBundle() [1/2]
CTextureBundle::CTextureBundle ()
CTextureBundle() [2/2]
CTextureBundle::CTextureBundle (bool useXBT) explicit
~CTextureBundle()
CTextureBundle::~CTextureBundle () default
Member Function Documentation
Close()
void CTextureBundle::Close ()
References CTextureBundleXBT::CloseBundle(), and m_tbXBT.
Referenced by CGUITextureManager::Cleanup().
GetTexturesFromPath()
std::vector< std::string > CTextureBundle::GetTexturesFromPath (const std::string & path)
References CTextureBundleXBT::GetTexturesFromPath(), m_tbXBT, and m_useXBT.
Referenced by CGUITextureManager::GetBundledTexturesFromPath().
HasFile()
bool CTextureBundle::HasFile (const std::string & Filename)
References CTextureBundleXBT::HasFile(), m_tbXBT, and m_useXBT.
LoadAnim()
std::optional< CTextureBundleXBT::Animation > CTextureBundle::LoadAnim (const std::string & filename)
Load animation from bundle.
Parameters
[in] filename name of the animation to load
Returns
std::optional<CTextureBundleXBT::Animation> if animation was loaded
References CTextureBundleXBT::LoadAnim(), m_tbXBT, and m_useXBT.
Referenced by CGUITextureManager::Load().
LoadTexture()
std::optional< CTextureBundleXBT::Texture > CTextureBundle::LoadTexture (const std::string & filename)
Load texture from bundle.
Parameters
[in] filename name of the texture to load
Returns
std::optional<CTextureBundleXBT::Texture> if texture was loaded
References CTextureBundleXBT::LoadTexture(), m_tbXBT, and m_useXBT.
Referenced by CGUITextureManager::Load().
Normalize()
std::string CTextureBundle::Normalize (std::string name) static
References name, and CTextureBundleXBT::Normalize().
Referenced by CGUITextureManager::HasTexture().
SetThemeBundle()
void CTextureBundle::SetThemeBundle (bool themeBundle)
References m_tbXBT, and CTextureBundleXBT::SetThemeBundle().
Referenced by CGUITextureManager::CGUITextureManager().
Member Data Documentation
m_tbXBT
CTextureBundleXBT CTextureBundle::m_tbXBT private
Referenced by Close(), GetTexturesFromPath(), HasFile(), LoadAnim(), LoadTexture(), and SetThemeBundle().
m_useXBT
bool CTextureBundle::m_useXBT private
Referenced by GetTexturesFromPath(), HasFile(), LoadAnim(), and LoadTexture().
The documentation for this class was generated from the following files:
TextureBundle.h
TextureBundle.cpp