Kodi Documentation: CWebSocketManager Class Reference
CWebSocketManager Class Reference
#include <WebSocketManager.h>
Static Public Member Functions
static CWebSocket * Handle (const char *data, unsigned int length, std::string &response)
Member Function Documentation
Handle()
CWebSocket * CWebSocketManager::Handle (const char * data, unsigned int length, std::string & response) static
References HttpParser::addBytes(), CHttpResponse::AddHeader(), HTTP::BadRequest, CHttpResponse::Create(), data(), HttpParser::Done, HttpParser::Error, HTTP::Get, HttpParser::getValue(), CWebSocket::Handshake(), HttpParser::Incomplete, CLog::Log(), LOGINFO, HTTP::UpgradeRequired, value, HTTP::Version1_1, WS_HEADER_VERSION, WS_HEADER_VERSION_LC, and WS_SUPPORTED_VERSIONS.
Referenced by JSONRPC::CTCPServer::Process().
The documentation for this class was generated from the following files:
WebSocketManager.h
WebSocketManager.cpp