Kodi Documentation: CGUIDialogYesNo Class Reference
CGUIDialogYesNo Class Reference
#include <GUIDialogYesNo.h>
Public Types
enum DialogResult { DIALOG_RESULT_CANCEL = -1 , DIALOG_RESULT_NO = 0 , DIALOG_RESULT_YES = 1 , DIALOG_RESULT_CUSTOM = 2 }
enum TimeOut { NO_TIMEOUT = 0 }
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Public Member Functions
CGUIDialogYesNo (int overrideId=-1)
~CGUIDialogYesNo (void) override
bool OnMessage (CGUIMessage &message) override
bool OnBack (int actionID) override
void Reset ()
DialogResult GetResult () const
DialogResult ShowAndGetInput (const KODI::MESSAGING::HELPERS::DialogYesNoMessage &options)
Open a Yes/No dialog and wait for input.
Public Member Functions inherited from CGUIDialogBoxBase
CGUIDialogBoxBase (int id, const std::string &xmlFile)
~CGUIDialogBoxBase (void) override
bool IsConfirmed () const
void SetLine (unsigned int iLine, const CVariant &line)
void SetText (const CVariant &text)
bool HasText () const
void SetHeading (const CVariant &heading)
bool HasHeading () const
void SetChoice (int iButton, const CVariant &choice)
Public Member Functions inherited from CGUIDialog
CGUIDialog (int id, const std::string &xmlFile, DialogModalityType modalityType=DialogModalityType::MODAL)
~CGUIDialog (void) override
bool OnAction (const CAction &action) override
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void Open (const std::string &param="")
void Open (bool bProcessRenderLoop, const std::string &param="")
bool IsDialogRunning () const override
bool IsDialog () const override
bool IsModalDialog () const override
virtual DialogModalityType GetModalityType () const
void SetAutoClose (unsigned int timeoutMs)
void ResetAutoClose (void)
void CancelAutoClose (void)
bool IsAutoClosed (void) const
void SetSound (bool OnOff)
bool IsSoundEnabled () const override
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
bool OnAction (const CAction &action) override
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool OnMessage (CGUIMessage &message) override
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsMediaWindow () const
virtual bool HasListItems () const
virtual CFileItemPtr GetCurrentListItem (int offset=0)
virtual int GetViewContainerID () const
virtual int GetViewCount () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual CGUIControl * GetFirstFocusableControl (int id)
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Static Public Member Functions
static bool ShowAndGetInput (const CVariant &heading, const CVariant &line0, const CVariant &line1, const CVariant &line2, bool &bCanceled)
Show a yes-no dialog, then wait for user to dismiss it.
static bool ShowAndGetInput (const CVariant &heading, const CVariant &line0, const CVariant &line1, const CVariant &line2, const CVariant &noLabel="", const CVariant &yesLabel="")
Show a yes-no dialog, then wait for user to dismiss it.
static bool ShowAndGetInput (const CVariant &heading, const CVariant &line0, const CVariant &line1, const CVariant &line2, bool &bCanceled, const CVariant &noLabel, const CVariant &yesLabel, unsigned int autoCloseTime)
Show a yes-no dialog, then wait for user to dismiss it.
static bool ShowAndGetInput (const CVariant &heading, const CVariant &text)
Show a yes-no dialog, then wait for user to dismiss it.
static bool ShowAndGetInput (const CVariant &heading, const CVariant &text, bool &bCanceled, const CVariant &noLabel, const CVariant &yesLabel, unsigned int autoCloseTime, int defaultButtonId=CONTROL_NO_BUTTON)
Show a yes-no dialog, then wait for user to dismiss it.
static DialogResult ShowAndGetInput (const CVariant &heading, const CVariant &text, const CVariant &noLabel, const CVariant &yesLabel, const CVariant &customLabel, unsigned int autoCloseTime, int defaultButtonId=CONTROL_NO_BUTTON)
Show a yes-no dialog with 3rd custom button, then wait for user to dismiss it.
Protected Member Functions
void OnInitWindow () override
Called on window open.
int GetDefaultLabelID (int controlId) const override
Protected Member Functions inherited from CGUIDialogBoxBase
std::string GetDefaultLabel (int controlId) const
std::string GetLocalized (const CVariant &var) const
Get a localized string from a variant If the variant is already a string we return directly, else if it's an integer we return the corresponding localized string.
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void OnDeinitWindow (int nextWindowID) override
Protected Member Functions inherited from CGUIDialog
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
void SetDefaults () override
void OnWindowLoaded () override
virtual void UpdateVisibility ()
virtual void Open_Internal (bool bProcessRenderLoop, const std::string &param="")
void ProcessRenderLoop (bool renderOnly=false)
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void OnWindowUnload ()
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
virtual void SaveControlStates ()
virtual void RestoreControlStates ()
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
bool m_bCanceled
bool m_bCustom
int m_defaultButtonId
Protected Attributes inherited from CGUIDialogBoxBase
bool m_bConfirmed
bool m_hasTextbox
CCriticalSection m_section
std::string m_strHeading
std::string m_text
std::string m_strChoices [DIALOG_MAX_CHOICES]
Protected Attributes inherited from CGUIDialog
bool m_wasRunning
true if we were running during the last DoProcess()
bool m_autoClosing
bool m_enableSound
unsigned int m_showStartTime
unsigned int m_showDuration
bool m_bAutoClosed
DialogModalityType m_modalityType
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Enumeration Documentation
DialogResult
enum CGUIDialogYesNo::DialogResult
Enumerator
DIALOG_RESULT_CANCEL
DIALOG_RESULT_NO
DIALOG_RESULT_YES
DIALOG_RESULT_CUSTOM
TimeOut
enum CGUIDialogYesNo::TimeOut
Enumerator
NO_TIMEOUT
Constructor & Destructor Documentation
CGUIDialogYesNo()
CGUIDialogYesNo::CGUIDialogYesNo (int overrideId = -1) explicit
References Reset().
~CGUIDialogYesNo()
CGUIDialogYesNo::~CGUIDialogYesNo (void) override default
Member Function Documentation
GetDefaultLabelID()
int CGUIDialogYesNo::GetDefaultLabelID (int controlId) const override protected virtual
Reimplemented from CGUIDialogBoxBase.
References CONTROL_CUSTOM_BUTTON, CONTROL_NO_BUTTON, CONTROL_YES_BUTTON, and CGUIDialogBoxBase::GetDefaultLabelID().
GetResult()
CGUIDialogYesNo::DialogResult CGUIDialogYesNo::GetResult () const
References DIALOG_RESULT_CANCEL, DIALOG_RESULT_CUSTOM, DIALOG_RESULT_NO, DIALOG_RESULT_YES, CGUIDialogBoxBase::IsConfirmed(), m_bCanceled, and m_bCustom.
Referenced by ShowAndGetInput(), and ShowAndGetInput().
OnBack()
bool CGUIDialogYesNo::OnBack (int actionID) override virtual
Reimplemented from CGUIDialog.
References m_bCanceled, CGUIDialogBoxBase::m_bConfirmed, m_bCustom, and CGUIControl::OnBack().
OnInitWindow()
void CGUIDialogYesNo::OnInitWindow (void) override protected virtual
Called on window open.
Restores the control state(s)
Sets initial visibility of controls
Queue WindowOpen animation
Set overlay state Override this function and do any window-specific initialisation such as filling control contents and setting control focus before calling the base method.
Reimplemented from CGUIDialogBoxBase.
References CONTROL_CUSTOM_BUTTON, CONTROL_PROGRESS_BAR, m_defaultButtonId, CGUIDialogBoxBase::m_strChoices, CGUIDialogBoxBase::OnInitWindow(), SET_CONTROL_FOCUS, SET_CONTROL_HIDDEN, and SET_CONTROL_VISIBLE.
Referenced by CGUIDialogPlayEject::OnInitWindow().
OnMessage()
bool CGUIDialogYesNo::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIDialogBoxBase.
References ACTION_SELECT_ITEM, Close(), CONTROL_CUSTOM_BUTTON, CONTROL_NO_BUTTON, CONTROL_YES_BUTTON, CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIMessage::GetSenderId(), GUI_MSG_CLICKED, CGUIDialogBoxBase::m_bConfirmed, m_bCustom, and CGUIDialogBoxBase::OnMessage().
Referenced by CGUIDialogPlayEject::OnMessage().
Reset()
void CGUIDialogYesNo::Reset ()
References CONTROL_NO_BUTTON, CGUIDialog::m_bAutoClosed, m_bCanceled, CGUIDialogBoxBase::m_bConfirmed, m_bCustom, and m_defaultButtonId.
Referenced by CGUIDialogYesNo().
ShowAndGetInput() [1/7]
bool CGUIDialogYesNo::ShowAndGetInput (const CVariant & heading, const CVariant & line0, const CVariant & line1, const CVariant & line2, bool & bCanceled) static
Show a yes-no dialog, then wait for user to dismiss it.
Parameters
heading Localized label id or string for the heading of the dialog
line0 Localized label id or string for line 1 of the dialog message
line1 Localized label id or string for line 2 of the dialog message
line2 Localized label id or string for line 3 of the dialog message
bCanceled Holds true if the dialog was canceled otherwise false
Returns
true if user selects Yes, otherwise false if user selects No.
References NO_TIMEOUT, and ShowAndGetInput().
Referenced by CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersion(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), CGUIDialogVideoManagerVersions::ChooseVideoAndConvertToVideoVersion(), PVR::CPVRGUIActionsRecordings::ConfirmDeleteAllRecordingsFromTrash(), PVR::CPVRGUIActionsRecordings::ConfirmDeleteRecording(), PVR::CPVRGUIActionsTimers::ConfirmDeleteTimer(), PVR::CPVRGUIActionsRecordings::ConfirmDeleteWatchedRecordings(), PVR::CPVRGUIActionsTimers::ConfirmStopRecording(), PVR::CPVRGUIActionsEPG::DeleteSavedSearch(), ADDON::GUI::CHelpers::DialogAddonLifecycleUseAsk(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), KODI::GAME::CGameClientProperties::GetProxyAddons(), PVR::CPVRGUIActionsChannels::HideChannel(), CGUIWindowMusicNav::ManageInfoProvider(), CGUIDialogFileBrowser::OnAddNetworkLocation(), CGUIWindowAddonBrowser::OnClick(), CGUIDialogContextMenu::OnContextButton(), CGUIWindowFileManager::OnCopy(), KODI::GAME::CDialogInGameSaves::OnDelete(), KODI::GAME::CDialogGameSaves::OnDelete(), CGUIWindowFileManager::OnDelete(), CGUIWindowMusicBase::OnInitWindow(), CGUIDialogAddonInfo::OnInstall(), CGUIDialogVideoInfo::OnMessage(), CGUIWindowFileManager::OnMove(), CGUIDialogMediaSource::OnOK(), CGUIWindowMusicBase::OnRemoveSource(), CGUIDialogSettingsBase::OnResetSettings(), PERIPHERALS::CGUIDialogPeripheralSettings::OnResetSettings(), CGUIWindowMusicBase::OnScan(), CGUIDialogProfileSettings::OnSettingAction(), XBMCHelper::OnSettingChanging(), CGUIWindowVideoBase::OnUnAssignContent(), CGUIDialogAddonInfo::OnUninstall(), KODI::RETRO::CRetroPlayer::OpenFile(), CGUIDialogVideoManagerVersions::ProcessVideoVersion(), CGUIDialogVideoManager::Remove(), KODI::GAME::CGUIControllerList::ResetController(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), CGUIDialogAudioSettings::Save(), CGUIDialogSubtitleSettings::Save(), CGUIDialogVideoSettings::Save(), PVR::CGUIWindowPVRSearchBase::SetSearchFilter(), ShowAndGetInput(), ShowAndGetInput(), ShowAndGetInput(), ShowAndGetInput(), CGUIDialogAddonSettings::ShowForMultipleInstances(), CGUIDialogProfileSettings::ShowForProfile(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), PVR::CGUIWindowPVRChannelsBase::UpdateEpg(), and CVideoLibraryRefreshingJob::Work().
ShowAndGetInput() [2/7]
bool CGUIDialogYesNo::ShowAndGetInput (const CVariant & heading, const CVariant & line0, const CVariant & line1, const CVariant & line2, bool & bCanceled, const CVariant & noLabel, const CVariant & yesLabel, unsigned int autoCloseTime) static
Show a yes-no dialog, then wait for user to dismiss it.
Parameters
heading Localized label id or string for the heading of the dialog
line0 Localized label id or string for line 1 of the dialog message
line1 Localized label id or string for line 2 of the dialog message
line2 Localized label id or string for line 3 of the dialog message
bCanceled Holds true if the dialog was canceled otherwise false
iNoLabel Localized label id or string for the no button
iYesLabel Localized label id or string for the yes button
autoCloseTime Time in ms before the dialog becomes automatically closed
Returns
true if user selects Yes, otherwise false if user selects No.
References CONTROL_NO_BUTTON, CVariant::empty(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), m_bCanceled, m_defaultButtonId, CGUIDialog::Open(), CGUIDialog::SetAutoClose(), CGUIDialogBoxBase::SetChoice(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), and WINDOW_DIALOG_YES_NO.
ShowAndGetInput() [3/7]
bool CGUIDialogYesNo::ShowAndGetInput (const CVariant & heading, const CVariant & line0, const CVariant & line1, const CVariant & line2, const CVariant & noLabel = "", const CVariant & yesLabel = "") static
Show a yes-no dialog, then wait for user to dismiss it.
Parameters
heading Localized label id or string for the heading of the dialog
line0 Localized label id or string for line 1 of the dialog message
line1 Localized label id or string for line 2 of the dialog message
line2 Localized label id or string for line 3 of the dialog message
iNoLabel Localized label id or string for the no button
iYesLabel Localized label id or string for the yes button
Returns
true if user selects Yes, otherwise false if user selects No.
References NO_TIMEOUT, and ShowAndGetInput().
ShowAndGetInput() [4/7]
bool CGUIDialogYesNo::ShowAndGetInput (const CVariant & heading, const CVariant & text) static
Show a yes-no dialog, then wait for user to dismiss it.
Parameters
heading Localized label id or string for the heading of the dialog
text Localized label id or string for the dialog message
Returns
true if user selects Yes, otherwise false if user selects No.
References ShowAndGetInput(), and text.
ShowAndGetInput() [5/7]
bool CGUIDialogYesNo::ShowAndGetInput (const CVariant & heading, const CVariant & text, bool & bCanceled, const CVariant & noLabel, const CVariant & yesLabel, unsigned int autoCloseTime, int defaultButtonId = CONTROL_NO_BUTTON) static
Show a yes-no dialog, then wait for user to dismiss it.
Parameters
heading Localized label id or string for the heading of the dialog
text Localized label id or string for the dialog message
bCanceled Holds true if the dialog was canceled otherwise false
iNoLabel Localized label id or string for the no button
iYesLabel Localized label id or string for the yes button
autoCloseTime Time in ms before the dialog becomes automatically closed
defaultButtonId Specifies the default focused button
Returns
true if user selects Yes, otherwise false if user selects No.
References DIALOG_RESULT_CANCEL, ShowAndGetInput(), and text.
ShowAndGetInput() [6/7]
CGUIDialogYesNo::DialogResult CGUIDialogYesNo::ShowAndGetInput (const CVariant & heading, const CVariant & text, const CVariant & noLabel, const CVariant & yesLabel, const CVariant & customLabel, unsigned int autoCloseTime, int defaultButtonId = CONTROL_NO_BUTTON) static
Show a yes-no dialog with 3rd custom button, then wait for user to dismiss it.
Parameters
heading Localized label id or string for the heading of the dialog
text Localized label id or string for the dialog message
noLabel Localized label id or string for the no button
yesLabel Localized label id or string for the yes button
customLabel Localized label id or string for the custom button
autoCloseTime Time in ms before the dialog becomes automatically closed
defaultButtonId Specifies the default focused button
Returns
action that closed the dialog
References DIALOG_RESULT_CANCEL, CVariant::empty(), CServiceBroker::GetGUI(), GetResult(), CGUIComponent::GetWindowManager(), m_bCanceled, m_bCustom, m_defaultButtonId, CGUIDialog::Open(), CGUIDialog::SetAutoClose(), CGUIDialogBoxBase::SetChoice(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetText(), text, and WINDOW_DIALOG_YES_NO.
ShowAndGetInput() [7/7]
CGUIDialogYesNo::DialogResult CGUIDialogYesNo::ShowAndGetInput (const KODI::MESSAGING::HELPERS::DialogYesNoMessage & options)
Open a Yes/No dialog and wait for input.
Parameters
[in] options a struct of type DialogYesNoMessage containing the options to set for this dialog.
Returns
action that closed the dialog
See also
KODI::MESSAGING::HELPERS::DialogYesNoMessage
References CONTROL_NO_BUTTON, GetResult(), m_bCanceled, m_bCustom, m_defaultButtonId, CGUIDialog::Open(), CGUIDialog::SetAutoClose(), CGUIDialogBoxBase::SetChoice(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), and CGUIDialogBoxBase::SetText().
Member Data Documentation
m_bCanceled
bool CGUIDialogYesNo::m_bCanceled protected
Referenced by GetResult(), OnBack(), Reset(), ShowAndGetInput(), ShowAndGetInput(), and ShowAndGetInput().
m_bCustom
bool CGUIDialogYesNo::m_bCustom protected
Referenced by GetResult(), OnBack(), OnMessage(), Reset(), ShowAndGetInput(), and ShowAndGetInput().
m_defaultButtonId
int CGUIDialogYesNo::m_defaultButtonId protected
Referenced by OnInitWindow(), Reset(), ShowAndGetInput(), ShowAndGetInput(), and ShowAndGetInput().
The documentation for this class was generated from the following files:
GUIDialogYesNo.h
GUIDialogYesNo.cpp