Kodi Documentation: jni::CJNIXBMCMediaSession Class Reference
jni::CJNIXBMCMediaSession Class Reference
#include <JNIXBMCMediaSession.h>
Public Member Functions
CJNIXBMCMediaSession ()
CJNIXBMCMediaSession (const CJNIXBMCMediaSession &other)
CJNIXBMCMediaSession (const jni::jhobject &object)
~CJNIXBMCMediaSession () override
void activate (bool state)
void updatePlaybackState (const CJNIPlaybackState &state)
void updateMetadata (const CJNIMediaMetadata &myData)
void updateIntent (const CJNIIntent &intent)
void OnPlayRequested ()
void OnPauseRequested ()
void OnNextRequested ()
void OnPreviousRequested ()
void OnForwardRequested ()
void OnRewindRequested ()
void OnStopRequested ()
void OnSeekRequested (int64_t pos)
bool OnMediaButtonEvent (const CJNIIntent &intent)
bool isActive () const
Static Public Member Functions
static void RegisterNatives (JNIEnv *env)
Static Protected Member Functions
static void _onPlayRequested (JNIEnv *env, jobject thiz)
static void _onPauseRequested (JNIEnv *env, jobject thiz)
static void _onNextRequested (JNIEnv *env, jobject thiz)
static void _onPreviousRequested (JNIEnv *env, jobject thiz)
static void _onForwardRequested (JNIEnv *env, jobject thiz)
static void _onRewindRequested (JNIEnv *env, jobject thiz)
static void _onStopRequested (JNIEnv *env, jobject thiz)
static void _onSeekRequested (JNIEnv *env, jobject thiz, jlong pos)
static bool _onMediaButtonEvent (JNIEnv *env, jobject thiz, jobject intent)
Protected Attributes
bool m_isActive = false
Constructor & Destructor Documentation
CJNIXBMCMediaSession() [1/3]
CJNIXBMCMediaSession::CJNIXBMCMediaSession ()
References s_className.
CJNIXBMCMediaSession() [2/3]
CJNIXBMCMediaSession::CJNIXBMCMediaSession (const CJNIXBMCMediaSession & other)
CJNIXBMCMediaSession() [3/3]
jni::CJNIXBMCMediaSession::CJNIXBMCMediaSession (const jni::jhobject & object) inline
~CJNIXBMCMediaSession()
CJNIXBMCMediaSession::~CJNIXBMCMediaSession () override
Member Function Documentation
_onForwardRequested()
void CJNIXBMCMediaSession::_onForwardRequested (JNIEnv * env, jobject thiz) static protected
References OnForwardRequested(), and void().
Referenced by RegisterNatives().
_onMediaButtonEvent()
bool CJNIXBMCMediaSession::_onMediaButtonEvent (JNIEnv * env, jobject thiz, jobject intent) static protected
References OnMediaButtonEvent(), and void().
Referenced by RegisterNatives().
_onNextRequested()
void CJNIXBMCMediaSession::_onNextRequested (JNIEnv * env, jobject thiz) static protected
References OnNextRequested(), and void().
Referenced by RegisterNatives().
_onPauseRequested()
void CJNIXBMCMediaSession::_onPauseRequested (JNIEnv * env, jobject thiz) static protected
References OnPauseRequested(), and void().
Referenced by RegisterNatives().
_onPlayRequested()
void CJNIXBMCMediaSession::_onPlayRequested (JNIEnv * env, jobject thiz) static protected
References OnPlayRequested(), and void().
Referenced by RegisterNatives().
_onPreviousRequested()
void CJNIXBMCMediaSession::_onPreviousRequested (JNIEnv * env, jobject thiz) static protected
References OnPreviousRequested(), and void().
Referenced by RegisterNatives().
_onRewindRequested()
void CJNIXBMCMediaSession::_onRewindRequested (JNIEnv * env, jobject thiz) static protected
References OnRewindRequested(), and void().
Referenced by RegisterNatives().
_onSeekRequested()
void CJNIXBMCMediaSession::_onSeekRequested (JNIEnv * env, jobject thiz, jlong pos) static protected
References OnSeekRequested(), and void().
Referenced by RegisterNatives().
_onStopRequested()
void CJNIXBMCMediaSession::_onStopRequested (JNIEnv * env, jobject thiz) static protected
References OnStopRequested(), and void().
Referenced by RegisterNatives().
activate()
void CJNIXBMCMediaSession::activate (bool state)
References m_isActive.
isActive()
bool CJNIXBMCMediaSession::isActive () const
References m_isActive.
OnForwardRequested()
void CJNIXBMCMediaSession::OnForwardRequested ()
References ACTION_PLAYER_FORWARD, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by _onForwardRequested().
OnMediaButtonEvent()
bool CJNIXBMCMediaSession::OnMediaButtonEvent (const CJNIIntent & intent)
References CXBMCApp::Get(), and CXBMCApp::onReceive().
Referenced by _onMediaButtonEvent().
OnNextRequested()
void CJNIXBMCMediaSession::OnNextRequested ()
References ACTION_NEXT_ITEM, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by _onNextRequested().
OnPauseRequested()
void CJNIXBMCMediaSession::OnPauseRequested ()
References ACTION_PAUSE, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by _onPauseRequested().
OnPlayRequested()
void CJNIXBMCMediaSession::OnPlayRequested ()
References ACTION_PAUSE, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by _onPlayRequested().
OnPreviousRequested()
void CJNIXBMCMediaSession::OnPreviousRequested ()
References ACTION_PREV_ITEM, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by _onPreviousRequested().
OnRewindRequested()
void CJNIXBMCMediaSession::OnRewindRequested ()
References ACTION_PLAYER_REWIND, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by _onRewindRequested().
OnSeekRequested()
void CJNIXBMCMediaSession::OnSeekRequested (int64_t pos)
References g_application, and CApplicationPlayer::SeekTime().
Referenced by _onSeekRequested().
OnStopRequested()
void CJNIXBMCMediaSession::OnStopRequested ()
References ACTION_STOP, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by _onStopRequested().
RegisterNatives()
void CJNIXBMCMediaSession::RegisterNatives (JNIEnv * env) static
References _onForwardRequested(), _onMediaButtonEvent(), _onNextRequested(), _onPauseRequested(), _onPlayRequested(), _onPreviousRequested(), _onRewindRequested(), _onSeekRequested(), _onStopRequested(), and s_className.
Referenced by JNI_OnLoad().
updateIntent()
void CJNIXBMCMediaSession::updateIntent (const CJNIIntent & intent)
updateMetadata()
void CJNIXBMCMediaSession::updateMetadata (const CJNIMediaMetadata & myData)
updatePlaybackState()
void CJNIXBMCMediaSession::updatePlaybackState (const CJNIPlaybackState & state)
Member Data Documentation
m_isActive
bool jni::CJNIXBMCMediaSession::m_isActive = false protected
Referenced by activate(), and isActive().
The documentation for this class was generated from the following files:
JNIXBMCMediaSession.h
JNIXBMCMediaSession.cpp