Kodi Documentation: KODI::GAME::CControllerManager Class Reference
KODI::GAME::CControllerManager Class Reference
Games
#include <ControllerManager.h>
Public Member Functions
CControllerManager (ADDON::CAddonMgr &addonManager)
~CControllerManager ()
ControllerPtr GetController (const std::string &controllerId)
Get a controller.
ControllerPtr GetDefaultController ()
Get the default controller.
ControllerPtr GetDefaultKeyboard ()
Get the default keyboard.
ControllerPtr GetDefaultMouse ()
Get the default mouse.
ControllerVector GetControllers ()
Get installed controllers.
std::string TranslateFeature (const std::string &controllerId, const std::string &featureName)
Translate a feature on a controller into its localized name.
Private Member Functions
void OnEvent (const ADDON::AddonEvent &event)
ControllerPtr LoadController (const ADDON::AddonPtr &addon)
Private Attributes
ADDON::CAddonMgr & m_addonManager
std::map< std::string, ControllerPtr > m_cache
std::set< std::string > m_failedControllers
CCriticalSection m_mutex
Constructor & Destructor Documentation
CControllerManager()
CControllerManager::CControllerManager (ADDON::CAddonMgr & addonManager)
References ADDON::CAddonMgr::Events(), m_addonManager, and OnEvent().
~CControllerManager()
CControllerManager::~CControllerManager ()
References ADDON::CAddonMgr::Events(), and m_addonManager.
Member Function Documentation
GetController()
ControllerPtr CControllerManager::GetController (const std::string & controllerId)
Get a controller.
A cache is used to avoid reloading controllers each time they are requested.
Parameters
controllerId The controller's ID
Returns
The controller, or empty if the controller isn't installed or can't be loaded
References ADDON::CAddonMgr::GetAddon(), LoadController(), m_addonManager, m_cache, m_failedControllers, and m_mutex.
Referenced by PERIPHERALS::CPeripheralJoystick::ControllerProfile(), KODI::JOYSTICK::CScalarFeature::CScalarFeature(), KODI::GAME::CGameServices::GetController(), GetDefaultController(), GetDefaultKeyboard(), GetDefaultMouse(), PERIPHERALS::CPeripheralJoystick::InitializeControllerProfile(), PERIPHERALS::CPeripheralJoystick::InstallAsync(), PERIPHERALS::CGUIDialogPeripheralSettings::OnSettingChanged(), and TranslateFeature().
GetControllers()
ControllerVector CControllerManager::GetControllers ()
Get installed controllers.
Returns
The installed controllers that loaded successfully
References addons, ADDON::CAddonMgr::GetInstalledAddons(), LoadController(), m_addonManager, m_cache, m_failedControllers, and m_mutex.
Referenced by KODI::GAME::CGameServices::GetControllers().
GetDefaultController()
ControllerPtr CControllerManager::GetDefaultController ()
Get the default controller.
Returns
The default controller, or empty if the controller failed to load
References DEFAULT_CONTROLLER_ID, and GetController().
Referenced by PERIPHERALS::CPeripheralJoystick::ControllerProfile(), and KODI::GAME::CGameServices::GetDefaultController().
GetDefaultKeyboard()
ControllerPtr CControllerManager::GetDefaultKeyboard ()
Get the default keyboard.
Returns
The keyboard controller, or empty if the controller failed to load
References DEFAULT_KEYBOARD_ID, and GetController().
Referenced by PERIPHERALS::CPeripheralKeyboard::ControllerProfile(), and KODI::GAME::CGameServices::GetDefaultKeyboard().
GetDefaultMouse()
ControllerPtr CControllerManager::GetDefaultMouse ()
Get the default mouse.
Returns
The mouse controller, or empty if the controller failed to load
References DEFAULT_MOUSE_ID, and GetController().
Referenced by PERIPHERALS::CPeripheralMouse::ControllerProfile(), and KODI::GAME::CGameServices::GetDefaultMouse().
LoadController()
ControllerPtr CControllerManager::LoadController (const ADDON::AddonPtr & addon) private
References m_failedControllers.
Referenced by GetController(), and GetControllers().
OnEvent()
void CControllerManager::OnEvent (const ADDON::AddonEvent & event) private
References m_cache, m_failedControllers, and m_mutex.
Referenced by CControllerManager().
TranslateFeature()
std::string CControllerManager::TranslateFeature (const std::string & controllerId, const std::string & featureName)
Translate a feature on a controller into its localized name.
Parameters
controllerId The controller ID that the feature belongs to
featureName The feature name
Returns
The localized feature name, or empty if the controller or feature doesn't exist
References GetController().
Referenced by KODI::GAME::CGameServices::TranslateFeature().
Member Data Documentation
m_addonManager
ADDON::CAddonMgr& KODI::GAME::CControllerManager::m_addonManager private
Referenced by CControllerManager(), GetController(), GetControllers(), and ~CControllerManager().
m_cache
std::map<std::string, ControllerPtr> KODI::GAME::CControllerManager::m_cache private
Referenced by GetController(), GetControllers(), and OnEvent().
m_failedControllers
std::set<std::string> KODI::GAME::CControllerManager::m_failedControllers private
Referenced by GetController(), GetControllers(), LoadController(), and OnEvent().
m_mutex
CCriticalSection KODI::GAME::CControllerManager::m_mutex private
Referenced by GetController(), GetControllers(), and OnEvent().
The documentation for this class was generated from the following files:
ControllerManager.h
ControllerManager.cpp