Kodi Documentation: anonymous_namespace{PlayerBuiltins.cpp} Namespace Reference
anonymous_namespace{PlayerBuiltins.cpp} Namespace Reference
Functions
void GetItemsForPlayList (const std::shared_ptr< CFileItem > &item, CFileItemList &queuedItems)
PLAYLIST::Id GetPlayListId (const CFileItem &item)
int PlayOrQueueMedia (const std::vector< std::string > &params, bool forcePlay)
int PlayMedia (const std::vector< std::string > &params)
Start playback of media.
int QueueMedia (const std::vector< std::string > &params)
Queue media in the video or music playlist, according to type of media items. If both audio and video items are contained, queue to video playlist. Start playback at requested position if player is not playing.
Function Documentation
GetItemsForPlayList()
void anonymous_namespace{PlayerBuiltins.cpp}::GetItemsForPlayList (const std::shared_ptr< CFileItem > & item, CFileItemList & queuedItems)
References MUSIC_UTILS::GetItemsForPlayList(), KODI::VIDEO::UTILS::GetItemsForPlayList(), MUSIC_UTILS::IsItemPlayable(), and KODI::VIDEO::UTILS::IsItemPlayable().
Referenced by PlayOrQueueMedia().
GetPlayListId()
PLAYLIST::Id anonymous_namespace{PlayerBuiltins.cpp}::GetPlayListId (const CFileItem & item)
References KODI::MUSIC::IsAudio().
Referenced by PlayOrQueueMedia().
PlayMedia()
int anonymous_namespace{PlayerBuiltins.cpp}::PlayMedia (const std::vector< std::string > & params)
Start playback of media.
Parameters
params The parameters.
params[0] = URL to media to play (optional). params[1,...] = "isdir" if media is a directory (optional). params[1,...] = "1" to start playback in fullscreen (optional). params[1,...] = "resume" to force resuming (optional). params[1,...] = "noresume" to force not resuming (optional). params[1,...] = "playoffset=<offset>" to start playback from a given position in a playlist (optional). params[1,...] = "playlist_type_hint=<id>" to set the playlist type if a playlist file (e.g. STRM) is played (optional), for <id> value refer to PLAYLIST::TYPE_MUSIC / PLAYLIST::TYPE_VIDEO values, if not set will fallback to music playlist.
References PlayOrQueueMedia().
PlayOrQueueMedia()
int anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia (const std::vector< std::string > & params, bool forcePlay)
References KODI::VIDEO::GUILIB::ACTION_PLAY_FROM_BEGINNING, KODI::VIDEO::GUILIB::ACTION_RESUME, KODI::UTILS::StringUtils::EqualsNoCase(), g_application, g_passwordManager, CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CMediaSettings::GetInstance(), KODI::VIDEO::UTILS::GetItemResumeInformation(), GetItemsForPlayList(), CFileItem::GetPath(), GetPlayListId(), CServiceBroker::GetPlaylistPlayer(), CGUIComponent::GetWindowManager(), CGUIListItem::HasProperty(), URIUtils::HasSlashAtEnd(), KODI::MUSIC::IsAudio(), CFileItemList::IsEmpty(), CGUIPassword::IsMusicUnlocked(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsPlugin(), CFileItem::IsPVR(), KODI::PLAYLIST::IsSmartPlayList(), CGUIPassword::IsVideoUnlocked(), CFileItem::LoadDetails(), LOGERROR, CGUIListItem::m_bIsFolder, KODI::PLAYLIST::CPlayListPlayer::Play(), CGUIWindowManager::PreviousWindow(), CFileItemList::Remove(), CApplicationPowerHandling::ResetScreenSaver(), CMediaSettings::SetMediaStartWindowed(), CGUIListItem::SetProperty(), CFileItem::SetStartOffset(), CFileItemList::Size(), STARTOFFSET_RESUME, KODI::UTILS::StringUtils::StartsWithNoCase(), WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, WINDOW_SLIDESHOW, and WINDOW_VISUALISATION.
Referenced by PlayMedia(), and QueueMedia().
QueueMedia()
int anonymous_namespace{PlayerBuiltins.cpp}::QueueMedia (const std::vector< std::string > & params)
Queue media in the video or music playlist, according to type of media items. If both audio and video items are contained, queue to video playlist. Start playback at requested position if player is not playing.
Parameters
params The parameters.
params[0] = URL of media to queue. params[1,...] = "isdir" if media is a directory (optional). params[1,...] = "1" to start playback in fullscreen (optional). params[1,...] = "resume" to force resuming (optional). params[1,...] = "noresume" to force not resuming (optional). params[1,...] = "playoffset=<offset>" to start playback from a given position in a playlist (optional). params[1,...] = "playlist_type_hint=<id>" to set the playlist type if a playlist file (e.g. STRM) is played (optional), for <id> value refer to PLAYLIST::TYPE_MUSIC / PLAYLIST::TYPE_VIDEO values, if not set will fallback to music playlist. params[1,...] = "playnext" if player is currently playing, to play the media right after the currently playing item. If player is not playing, append media to current playlist (optional).
References PlayOrQueueMedia().