Kodi Documentation: CGUILabel Class Reference
CGUILabel Class Reference
Guilib classes » Window Reference » Controls | Guilib classes » Labels
Class for rendering text labels. Handles alignment and rendering of text within a control.
#include <GUILabel.h>
Public Types
enum COLOR {
COLOR_TEXT = 0 , COLOR_SELECTED , COLOR_FOCUSED , COLOR_DISABLED ,
COLOR_INVALID
}
allowed color categories for labels, as defined by the skin
enum OVER_FLOW {
OVER_FLOW_TRUNCATE = 0 , OVER_FLOW_SCROLL , OVER_FLOW_WRAP , OVER_FLOW_CLIP ,
OVER_FLOW_TRUNCATE_LEFT
}
allowed overflow handling techniques for labels, as defined by the skin
Public Member Functions
CGUILabel (float posX, float posY, float width, float height, const CLabelInfo &labelInfo, OVER_FLOW overflow=OVER_FLOW_TRUNCATE)
CGUILabel (const CGUILabel &label)
virtual ~CGUILabel ()=default
bool Process (unsigned int currentTime)
Process the label.
void Render ()
Render the label on screen.
bool SetMaxRect (float x, float y, float w, float h)
Set the maximal extent of the label Sets the maximal size and positioning that the label may render in. Note that textwidth> can override this, and <textoffsetx> and <textoffsety> may also allow the label to be moved outside this rectangle.
bool SetAlign (uint32_t align)
bool SetText (const std::string &label)
Set the text to be displayed in the label Updates the label control and recomputes final position and size.
bool SetTextW (const std::wstring &label)
Set the text to be displayed in the label Updates the label control and recomputes final position and size.
bool SetStyledText (const vecText &text, const std::vector< KODI::UTILS::COLOR::Color > &colors)
Set styled text to be displayed in the label Updates the label control and recomputes final position and size.
bool SetColor (COLOR color)
Set the color to use for the label Sets the color to be used for this label. Takes effect at the next render.
void SetRenderRect (const CRect &rect)
Set the final layout of the current text Overrides the calculated layout of the current text, forcing a particular size and position.
bool SetScrolling (bool scrolling)
Set whether or not this label control should scroll.
void SetScrollLoopCount (unsigned int loopCount)
Set max. text scroll count.
bool SetOverflow (OVER_FLOW overflow)
Set how this label should handle overflowing text.
void SetInvalid ()
Set this label invalid. Forces an update of the control.
bool UpdateColors ()
Update this labels colors.
const CRect & GetRenderRect () const
Returns the precalculated final layout of the current text.
float GetTextWidth () const
Returns the precalculated full width of the current text, regardless of layout.
float GetMaxWidth () const
Returns the maximal width that this label can render into.
float CalcTextWidth (const std::wstring &text) const
Calculates the width of some text.
const CLabelInfo & GetLabelInfo () const
CLabelInfo & GetLabelInfo ()
Static Public Member Functions
static bool CheckAndCorrectOverlap (CGUILabel &label1, CGUILabel &label2)
Check a left aligned and right aligned label for overlap and cut the labels off so that no overlap occurs.
Protected Member Functions
KODI::UTILS::COLOR::Color GetColor () const
void UpdateRenderRect ()
Computes the final layout of the text Uses the maximal position and width of the text, as well as the text length and alignment to compute the final render rect of the text.
Private Attributes
CLabelInfo m_label
CGUITextLayout m_textLayout
bool m_scrolling
OVER_FLOW m_overflowType
CScrollInfo m_scrollInfo
CRect m_renderRect
actual sizing of text
CRect m_maxRect
maximum sizing of text
bool m_invalid = true
if true, the label needs recomputing
COLOR m_color = COLOR_TEXT
color to render text
unsigned int m_maxScrollLoops = ~0U
Detailed Description
Class for rendering text labels. Handles alignment and rendering of text within a control.
,
Member Enumeration Documentation
COLOR
enum CGUILabel::COLOR
allowed color categories for labels, as defined by the skin
Enumerator
COLOR_TEXT
COLOR_SELECTED
COLOR_FOCUSED
COLOR_DISABLED
COLOR_INVALID
OVER_FLOW
enum CGUILabel::OVER_FLOW
allowed overflow handling techniques for labels, as defined by the skin
Enumerator
OVER_FLOW_TRUNCATE
OVER_FLOW_SCROLL
OVER_FLOW_WRAP
OVER_FLOW_CLIP
OVER_FLOW_TRUNCATE_LEFT
Constructor & Destructor Documentation
CGUILabel() [1/2]
CGUILabel::CGUILabel (float posX, float posY, float width, float height, const CLabelInfo & labelInfo, CGUILabel::OVER_FLOW overflow = OVER_FLOW_TRUNCATE)
CGUILabel() [2/2]
CGUILabel::CGUILabel (const CGUILabel & label)
~CGUILabel()
virtual CGUILabel::~CGUILabel () virtual default
Member Function Documentation
CalcTextWidth()
float CGUILabel::CalcTextWidth (const std::wstring & text) const inline
Calculates the width of some text.
Parameters
text std::wstring of text whose width we want
Returns
width of the given text
See also
GetTextWidth
References CGUITextLayout::GetTextWidth(), m_textLayout, and text.
Referenced by CGUIEditControl::RecalcRightLabelPosition().
CheckAndCorrectOverlap()
bool CGUILabel::CheckAndCorrectOverlap (CGUILabel & label1, CGUILabel & label2) static
Check a left aligned and right aligned label for overlap and cut the labels off so that no overlap occurs.
If a left-aligned label occupies some of the same space on screen as a right-aligned label, then we may be able to correct for this by restricting the width of one or both of them. This routine checks two labels to see whether they satisfy this assumption and, if so, adjusts the render rect of both labels so that they no longer do so. The order of the two labels is not important, but we do assume that the left-aligned label is also the left-most on screen, and that the right-aligned label is the right most on-screen, so that they overlap due to the fact that one or both of the labels are longer than anticipated. In the following diagram, [R...[R R] refers to the maximal allowed and actual space occupied by the right label. Similarly, [L L]...L] refers to the maximal and actual space occupied by the left label. | refers to the central cutting point, i.e. the point that would divide the maximal allowed overlap perfectly in two. There are 3 scenarios to consider:
cut [L [R...[R L].|..........L] R] left label ends to the left of the cut -> just crop the left label. [L [R.....[R | L]..L] R] both left and right labels occupy more than the cut allows, so crop both. [L [R..........|.[R L]..L] R] right label ends to the right of the cut -> just crop the right label.
Parameters
label1 First label to check
label2 Second label to check
References CRectGen< T >::Intersect(), CRectGen< T >::IsEmpty(), left, m_renderRect, right, CRectGen< T >::x1, and XBFONT_RIGHT.
Referenced by CGUIListLabel::CheckAndCorrectOverlap(), and CGUIButtonControl::ProcessText().
GetColor()
KODI::UTILS::COLOR::Color CGUILabel::GetColor () const protected
References COLOR_DISABLED, COLOR_FOCUSED, COLOR_INVALID, COLOR_SELECTED, CLabelInfo::disabledColor, CLabelInfo::focusedColor, CLabelInfo::invalidColor, m_color, m_label, CLabelInfo::selectedColor, and CLabelInfo::textColor.
Referenced by Render().
GetLabelInfo() [1/2]
CLabelInfo & CGUILabel::GetLabelInfo () inline
References m_label.
GetLabelInfo() [2/2]
const CLabelInfo & CGUILabel::GetLabelInfo () const inline
References m_label.
Referenced by CGUISpinControlEx::AllocResources(), CGUIColorButtonControl::CGUIColorButtonControl(), CGUIEditControl::CGUIEditControl(), CGUIEditControl::DefaultConstructor(), CGUIButtonControl::GetLabelInfo(), CGUILabelControl::GetLabelInfo(), CGUIButtonControl::GetWidth(), CGUISpinControl::Process(), CGUIColorButtonControl::ProcessInfoText(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIButtonControl::PythonSetDisabledColor(), CGUIButtonControl::PythonSetLabel(), CGUIEditControl::RecalcRightLabelPosition(), CGUISpinControl::Render(), CGUISpinControlEx::RenderText(), CGUILabelControl::SetAlignment(), CGUISpinControlEx::SetItemInvalid(), CGUISpinControl::SetSpinAlign(), CGUIEditControl::SetStyledText(), CGUIListLabel::SetWidth(), and CGUILabelControl::UpdateInfo().
GetMaxWidth()
float CGUILabel::GetMaxWidth () const
Returns the maximal width that this label can render into.
Returns
Maximal width that this label can render into. Note that this may differ from the amount given in SetMaxRect as offsets and text width overrides have been taken into account.
See also
SetMaxRect
References m_label, m_maxRect, CLabelInfo::offsetX, CLabelInfo::width, and CRectGen< T >::Width().
Referenced by CGUIEditControl::RecalcRightLabelPosition(), and UpdateRenderRect().
GetRenderRect()
const CRect & CGUILabel::GetRenderRect () const inline
Returns the precalculated final layout of the current text.
Returns
CRect containing the extents of the current text
See also
SetRenderRect, UpdateRenderRect
References m_renderRect.
Referenced by CGUIButtonControl::CalcRenderRegion(), CGUILabelControl::CalcRenderRegion(), CGUIListLabel::CalcRenderRegion(), CGUIColorButtonControl::ProcessInfoText(), CGUIButtonControl::ProcessText(), and CGUISpinControl::Render().
GetTextWidth()
float CGUILabel::GetTextWidth () const inline
Returns the precalculated full width of the current text, regardless of layout.
Returns
full width of the current text
See also
CalcTextWidth
References CGUITextLayout::GetTextWidth(), and m_textLayout.
Referenced by CGUILabelControl::GetMaxWidth(), CGUIButtonControl::GetWidth(), CGUILabelControl::GetWidth(), CGUISpinControl::Process(), CGUIColorButtonControl::ProcessInfoText(), CGUIEditControl::ProcessText(), CGUIEditControl::RecalcRightLabelPosition(), CGUISpinControl::Render(), and CGUILabelControl::ShortenPath().
Process()
bool CGUILabel::Process (unsigned int currentTime)
Process the label.
Returns
bool stating if process caused control to change
Todo:
Add the correct processing
References COLOR_DISABLED, CGUITextLayout::GetTextWidth(), m_color, CScrollInfo::m_loopCount, m_maxScrollLoops, m_renderRect, m_scrollInfo, m_scrolling, m_textLayout, SetScrolling(), CGUITextLayout::UpdateScrollinfo(), and CRectGen< T >::Width().
Referenced by CGUILabelControl::Process(), CGUIListLabel::Process(), CGUISpinControl::Process(), CGUIColorButtonControl::ProcessInfoText(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), and CGUIToggleButtonControl::ProcessToggle().
Render()
void CGUILabel::Render ()
Render the label on screen.
References CLabelInfo::align, CLabelInfo::angle, color, COLOR_DISABLED, GetColor(), CGUITextLayout::GetTextWidth(), CRectGen< T >::Height(), m_color, m_label, m_overflowType, m_renderRect, m_scrollInfo, m_scrolling, m_textLayout, OVER_FLOW_CLIP, OVER_FLOW_TRUNCATE_LEFT, CGUITextLayout::Render(), CGUITextLayout::RenderScrolling(), CLabelInfo::shadowColor, CRectGen< T >::Width(), CRectGen< T >::x1, XBFONT_CENTER_X, XBFONT_CENTER_Y, XBFONT_RIGHT, XBFONT_TRUNCATED, XBFONT_TRUNCATED_LEFT, and CRectGen< T >::y1.
Referenced by CGUILabelControl::Render(), CGUIListLabel::Render(), CGUISettingsSliderControl::Render(), CGUIColorButtonControl::RenderInfoText(), CGUIButtonControl::RenderText(), CGUIEditControl::RenderText(), and CGUISpinControl::RenderText().
SetAlign()
bool CGUILabel::SetAlign (uint32_t align)
References CLabelInfo::align, m_label, and UpdateRenderRect().
Referenced by CGUISettingsSliderControl::CGUISettingsSliderControl(), CGUIButtonControl::ProcessText(), and CGUIEditControl::ProcessText().
SetColor()
bool CGUILabel::SetColor (COLOR color)
Set the color to use for the label Sets the color to be used for this label. Takes effect at the next render.
Parameters
color color to be used for the label
References color, and m_color.
Referenced by CGUILabelControl::Process(), CGUIColorButtonControl::ProcessInfoText(), CGUISettingsSliderControl::ProcessText(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIToggleButtonControl::ProcessToggle(), CGUISpinControl::RenderText(), and CGUIListLabel::SetSelected().
SetInvalid()
void CGUILabel::SetInvalid ()
Set this label invalid. Forces an update of the control.
References m_invalid.
Referenced by CGUILabelControl::OnMessage(), CGUIButtonControl::SetInvalid(), CGUIColorButtonControl::SetInvalid(), CGUIListLabel::SetInvalid(), and CGUISpinControl::SetInvalid().
SetMaxRect()
bool CGUILabel::SetMaxRect (float x, float y, float w, float h)
Set the maximal extent of the label Sets the maximal size and positioning that the label may render in. Note that textwidth> can override this, and <textoffsetx> and <textoffsety> may also allow the label to be moved outside this rectangle.
References m_maxRect, CRectGen< T >::SetRect(), and UpdateRenderRect().
Referenced by CGUILabelControl::Process(), CGUIColorButtonControl::ProcessInfoText(), CGUISettingsSliderControl::ProcessText(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIToggleButtonControl::ProcessToggle(), CGUISpinControl::RenderText(), CGUILabelControl::SetWidth(), CGUIListLabel::SetWidth(), and CGUILabelControl::UpdateInfo().
SetOverflow()
bool CGUILabel::SetOverflow (OVER_FLOW overflow)
Set how this label should handle overflowing text.
Parameters
overflow the overflow type
See also
OVER_FLOW
References m_overflowType.
Referenced by CGUIEditControl::ProcessText().
SetRenderRect()
void CGUILabel::SetRenderRect (const CRect & rect) inline
Set the final layout of the current text Overrides the calculated layout of the current text, forcing a particular size and position.
Parameters
rect CRect containing the extents of the current text
See also
GetRenderRect, UpdateRenderRect
References m_renderRect.
SetScrolling()
bool CGUILabel::SetScrolling (bool scrolling)
Set whether or not this label control should scroll.
Parameters
scrolling true if this label should scroll.
References m_scrollInfo, m_scrolling, and CScrollInfo::Reset().
Referenced by Process(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIToggleButtonControl::ProcessToggle(), CGUISpinControlEx::RenderText(), CGUIListLabel::SetFocus(), and CGUILabelControl::SetWidthControl().
SetScrollLoopCount()
void CGUILabel::SetScrollLoopCount (unsigned int loopCount) inline
Set max. text scroll count.
References m_maxScrollLoops.
Referenced by CGUILabelControl::CGUILabelControl(), and CGUIListLabel::CGUIListLabel().
SetStyledText()
bool CGUILabel::SetStyledText (const vecText & text, const std::vector< KODI::UTILS::COLOR::Color > & colors)
Set styled text to be displayed in the label Updates the label control and recomputes final position and size.
Parameters
text styled text to set.
colors colors referenced in the styled text.
See also
SetText, SetTextW
References m_invalid, m_maxRect, m_textLayout, text, CGUITextLayout::UpdateStyled(), and CRectGen< T >::Width().
Referenced by CGUIEditControl::SetStyledText(), and CGUILabelControl::UpdateInfo().
SetText()
bool CGUILabel::SetText (const std::string & label)
Set the text to be displayed in the label Updates the label control and recomputes final position and size.
Parameters
text std::string to set as this labels text
See also
SetTextW, SetStyledText
References label, m_invalid, m_maxRect, m_scrollInfo, m_textLayout, CScrollInfo::Reset(), CGUITextLayout::Update(), UpdateRenderRect(), and CRectGen< T >::Width().
Referenced by CGUISpinControl::Process(), CGUIColorButtonControl::ProcessInfoText(), CGUISettingsSliderControl::ProcessText(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIToggleButtonControl::ProcessToggle(), CGUIListLabel::SetLabel(), CGUILabelControl::ShortenPath(), and CGUILabelControl::UpdateInfo().
SetTextW()
bool CGUILabel::SetTextW (const std::wstring & label)
Set the text to be displayed in the label Updates the label control and recomputes final position and size.
Parameters
text std::wstring to set as this labels text
See also
SetText, SetStyledText
References label, m_invalid, m_maxRect, m_scrollInfo, m_textLayout, CScrollInfo::Reset(), UpdateRenderRect(), CGUITextLayout::UpdateW(), and CRectGen< T >::Width().
Referenced by CGUIEditControl::ProcessText().
UpdateColors()
bool CGUILabel::UpdateColors ()
Update this labels colors.
References m_label, and CLabelInfo::UpdateColors().
Referenced by CGUIButtonControl::UpdateColors(), CGUIColorButtonControl::UpdateColors(), CGUILabelControl::UpdateColors(), CGUIListLabel::UpdateColors(), CGUISettingsSliderControl::UpdateColors(), and CGUISpinControl::UpdateColors().
UpdateRenderRect()
void CGUILabel::UpdateRenderRect () protected
Computes the final layout of the text Uses the maximal position and width of the text, as well as the text length and alignment to compute the final render rect of the text.
See also
GetRenderRect, SetRenderRect
References CLabelInfo::align, GetMaxWidth(), CGUITextLayout::GetTextExtent(), CRectGen< T >::Height(), m_label, m_maxRect, m_renderRect, m_textLayout, CLabelInfo::offsetX, CLabelInfo::offsetY, CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, XBFONT_CENTER_X, XBFONT_CENTER_Y, XBFONT_RIGHT, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by SetAlign(), SetMaxRect(), SetText(), and SetTextW().
Member Data Documentation
m_color
COLOR CGUILabel::m_color = COLOR_TEXT private
color to render text
See also
SetColor, GetColor
Referenced by GetColor(), Process(), Render(), and SetColor().
m_invalid
bool CGUILabel::m_invalid = true private
if true, the label needs recomputing
Referenced by SetInvalid(), SetStyledText(), SetText(), and SetTextW().
m_label
CLabelInfo CGUILabel::m_label private
Referenced by GetColor(), GetLabelInfo(), GetLabelInfo(), GetMaxWidth(), Render(), SetAlign(), UpdateColors(), and UpdateRenderRect().
m_maxRect
CRect CGUILabel::m_maxRect private
maximum sizing of text
Referenced by GetMaxWidth(), SetMaxRect(), SetStyledText(), SetText(), SetTextW(), and UpdateRenderRect().
m_maxScrollLoops
unsigned int CGUILabel::m_maxScrollLoops = ~0U private
Referenced by Process(), and SetScrollLoopCount().
m_overflowType
OVER_FLOW CGUILabel::m_overflowType private
Referenced by Render(), and SetOverflow().
m_renderRect
CRect CGUILabel::m_renderRect private
actual sizing of text
Referenced by CheckAndCorrectOverlap(), GetRenderRect(), Process(), Render(), SetRenderRect(), and UpdateRenderRect().
m_scrollInfo
CScrollInfo CGUILabel::m_scrollInfo private
Referenced by Process(), Render(), SetScrolling(), SetText(), and SetTextW().
m_scrolling
bool CGUILabel::m_scrolling private
Referenced by Process(), Render(), and SetScrolling().
m_textLayout
CGUITextLayout CGUILabel::m_textLayout private
Referenced by CalcTextWidth(), GetTextWidth(), Process(), Render(), SetStyledText(), SetText(), SetTextW(), and UpdateRenderRect().
The documentation for this class was generated from the following files:
GUILabel.h
GUILabel.cpp