Kodi Documentation: KODI::CDRIP::CCDDARipper Class Reference
KODI::CDRIP::CCDDARipper Class Reference
Rip an entire CD or a single track.
#include <CDDARipper.h>
Public Member Functions
bool RipTrack (CFileItem *pItem)
Rip a single track.
bool RipCD ()
Rip an entire CD.
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
Public Member Functions inherited from CJobQueue
CJobQueue (bool lifo=false, unsigned int jobsAtOnce=1, CJob::PRIORITY priority=CJob::PRIORITY_LOW)
CJobQueue constructor.
~CJobQueue () override
CJobQueue destructor Cancels any in-process jobs, and destroys the job queue.
bool AddJob (CJob *job)
Add a job to the queue On completion of the job, destruction of the job queue or in case the job could not be added successfully, the CJob object will be destroyed.
template<typename F >
void Submit (F &&f)
Add a function f to this job queue.
void CancelJob (const CJob *job)
Cancel a job in the queue Cancels a job in the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed. If the job is only queued then it will be removed from the queue and deleted.
void CancelJobs ()
Cancel all jobs in the queue Removes all jobs from the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed.
bool IsProcessing () const
Check whether the queue is processing a job.
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
void OnJobAbort (unsigned int jobID, CJob *job) override
The callback used when a job will be aborted.
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Static Public Member Functions
static CCDDARipper & GetInstance ()
The only way through which the global instance of the CDDARipper should be accessed.
Private Member Functions
CCDDARipper ()
CCDDARipper (const CCDDARipper &)=delete
~CCDDARipper () override
CCDDARipper const & operator= (CCDDARipper const &)=delete
bool CreateAlbumDir (const MUSIC_INFO::CMusicInfoTag &infoTag, std::string &strDirectory, int &legalType)
Create folder where CD tracks will be stored.
std::string GetAlbumDirName (const MUSIC_INFO::CMusicInfoTag &infoTag)
Return formatted album subfolder for rip path.
std::string GetTrackName (CFileItem *item)
Return file name for the track.
Additional Inherited Members
Protected Member Functions inherited from CJobQueue
bool QueueEmpty () const
Returns if we still have jobs waiting to be processed NOTE: This function does not take into account the jobs that are currently processing.
Detailed Description
Rip an entire CD or a single track.
The CCDDARipper class is used to rip an entire CD or just a single track. Tracks are stored in a folder constructed from two user settings: audiocds.recordingpath and audiocds.trackpathformat. The former is the absolute file system path for the root folder where ripped music is stored, and the latter specifies the format for the album subfolder and for the track file name. Format used to encode ripped tracks is defined by the audiocds.encoder user setting, and there are several choices: wav, ogg vorbis and mp3.
Constructor & Destructor Documentation
CCDDARipper() [1/2]
CCDDARipper::CCDDARipper () private
CCDDARipper() [2/2]
KODI::CDRIP::CCDDARipper::CCDDARipper (const CCDDARipper &) private delete
~CCDDARipper()
CCDDARipper::~CCDDARipper () override private default
Member Function Documentation
CreateAlbumDir()
bool CCDDARipper::CreateAlbumDir (const MUSIC_INFO::CMusicInfoTag & infoTag, std::string & strDirectory, int & legalType) private
Create folder where CD tracks will be stored.
Parameters
[in] infoTag music info tags for the CD, used to format album name
[out] strDirectory full path of the created folder
[out] legalType created directory type (see LEGAL_... constants)
Returns
true if success, false if failure
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), CUtil::CreateDirectoryEx(), g_localizeStrings, GetAlbumDirName(), CGUIControlButtonSetting::GetPath(), CServiceBroker::GetSettingsComponent(), CFileItem::IsHD(), CFileItem::IsSmb(), LEGAL_NONE, LEGAL_WIN32_COMPAT, CLog::Log(), LOGERROR, CUtil::MakeLegalPath(), CSettings::SETTING_AUDIOCDS_RECORDINGPATH, and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by RipCD(), and RipTrack().
GetAlbumDirName()
std::string CCDDARipper::GetAlbumDirName (const MUSIC_INFO::CMusicInfoTag & infoTag) private
Return formatted album subfolder for rip path.
Parameters
infoTag music info tags for the CD, used to format album name
Returns
album subfolder path name
References MUSIC_INFO::CMusicInfoTag::GetAlbum(), MUSIC_INFO::CMusicInfoTag::GetAlbumArtistString(), MUSIC_INFO::CMusicInfoTag::GetArtistString(), CDateTime::GetCurrentDateTime(), MUSIC_INFO::CMusicInfoTag::GetGenre(), CServiceBroker::GetSettingsComponent(), MUSIC_INFO::CMusicInfoTag::GetYearString(), and CSettings::SETTING_AUDIOCDS_TRACKPATHFORMAT.
Referenced by CreateAlbumDir().
GetInstance()
CCDDARipper & CCDDARipper::GetInstance () static
The only way through which the global instance of the CDDARipper should be accessed.
Returns
the global instance.
Referenced by CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicBase::OnRipCD(), CGUIWindowMusicBase::OnRipTrack(), and RipCD().
GetTrackName()
std::string CCDDARipper::GetTrackName (CFileItem * item) private
Return file name for the track.
Parameters
[in] item CFileItem representing a track
Returns
track file name
References CLabelFormatter::FormatLabel(), ADDON::CAddonMgr::GetAddonInfo(), CServiceBroker::GetAddonMgr(), CGUIListItem::GetLabel(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), CFileItem::SetLabel(), CSettings::SETTING_AUDIOCDS_ENCODER, and CSettings::SETTING_AUDIOCDS_TRACKPATHFORMAT.
Referenced by RipCD(), and RipTrack().
OnJobComplete()
void CCDDARipper::OnJobComplete (unsigned int jobID, bool success, CJob * job) override virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
References CJobQueue::CancelJobs(), CDatabase::Close(), URIUtils::GetDirectory(), CMusicLibraryQueue::GetInstance(), CMediaSourceSettings::GetInstance(), CUtil::GetMatchingSource(), CMediaSourceSettings::GetSources(), CMusicDatabase::InsideScannedPath(), CJobQueue::OnJobComplete(), CMusicDatabase::Open(), CJobQueue::QueueEmpty(), MUSIC_INFO::CMusicInfoScanner::SCAN_NORMAL, CMusicLibraryQueue::ScanLibrary(), and success.
operator=()
CCDDARipper const & KODI::CDRIP::CCDDARipper::operator= (CCDDARipper const &) private delete
RipCD()
bool CCDDARipper::RipCD ()
Rip an entire CD.
Returns
true if success, false if failure
References URIUtils::AddFileToFolder(), CJobQueue::AddJob(), CreateAlbumDir(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), XFILE::CCDDADirectory::GetDirectory(), CServiceBroker::GetMediaManager(), CServiceBroker::GetSettingsComponent(), GetTrackName(), MEDIA_DETECT::CCdInfo::IsAudio(), CLog::Log(), LOGDEBUG, CUtil::MakeLegalFileName(), CSettings::SETTING_AUDIOCDS_EJECTONRIP, CSettings::SETTING_AUDIOCDS_ENCODER, and CFileItemList::Size().
Referenced by CGUIWindowMusicBase::OnRipCD(), and RipCD().
RipTrack()
bool CCDDARipper::RipTrack (CFileItem * pItem)
Rip a single track.
Parameters
[in] pItem CFileItem representing a track to rip
Returns
true if success, false if failure
References URIUtils::AddFileToFolder(), CJobQueue::AddJob(), CreateAlbumDir(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), GetTrackName(), URIUtils::HasExtension(), CLog::Log(), LOGDEBUG, CUtil::MakeLegalFileName(), and CSettings::SETTING_AUDIOCDS_ENCODER.
Referenced by CGUIWindowMusicBase::OnRipTrack().
The documentation for this class was generated from the following files:
CDDARipper.h
CDDARipper.cpp