Kodi Documentation: XFILE::CDirectoryFactory Class Reference
XFILE::CDirectoryFactory Class Reference
Filesystem
Get access to a directory of a file system.
#include <DirectoryFactory.h>
Static Public Member Functions
static IDirectory * Create (const CURL &url)
Create a IDirectory object of the share type specified in strPath .
static IDirectory * Create (const CFileItem &item)
Create a IDirectory object of the share type specified in a given item path.
Detailed Description
Get access to a directory of a file system.
The Factory can be used to create a directory object for every file system accessable.
Example:
std::string strShare="iso9660://";
IDirectory* pDir=CDirectoryFactory::Create(strShare);
The pDir pointer can be used to access a directory and retrieve it's content.
When different types of shares have to be accessed use CVirtualDirectory.
See also
IDirectory
Member Function Documentation
Create() [1/2]
IDirectory * CDirectoryFactory::Create (const CFileItem & item) static
Create a IDirectory object of the share type specified in a given item path.
Parameters
item Specifies the item to which the factory will create the directory instance
Returns
IDirectory object to access the directories on the share.
See also
IDirectory
References Create(), CFileItem::GetDynPath(), and CFileItem::GetMimeType().
Create() [2/2]
IDirectory * CDirectoryFactory::Create (const CURL & url) static
Create a IDirectory object of the share type specified in strPath .
Parameters
strPath Specifies the share type to access, can be a share or share with path.
Returns
IDirectory object to access the directories on the share.
See also
IDirectory
References XFILE::CFileDirectoryFactory::Create(), CURL::Get(), ADDON::CVFSAddonCache::GetAddonInstances(), CWakeOnAccess::GetInstance(), CURL::GetProtocol(), CURL::GetRedacted(), CServiceBroker::GetVFSAddonCache(), CServiceBroker::IsAddonInterfaceUp(), CURL::IsProtocol(), XFILE::CWinLibraryDirectory::IsValid(), CLog::Log(), LOGWARNING, and XFILE::CTVOSDirectory::WantsDirectory().
Referenced by Create(), XFILE::CDirectory::Create(), XFILE::CDirectory::Exists(), XFILE::CVirtualDirectory::GetDirectory(), XFILE::CDirectory::GetDirectory(), CApplication::PlayFile(), XFILE::CDirectory::Remove(), and XFILE::CDirectory::RemoveRecursive().
The documentation for this class was generated from the following files:
DirectoryFactory.h
DirectoryFactory.cpp