Kodi Documentation: dbiplus Namespace Reference
dbiplus Namespace Reference
Classes
class Database
class Dataset
class DbErrors
struct et_info
struct field
struct field_prop
class field_value
class MysqlDatabase
class MysqlDataset
class result_set
class SqliteDatabase
class SqliteDataset
struct StrAccum
Typedefs
typedef std::list< std::string > StringList
typedef std::map< std::string, field_value > ParamList
typedef unsigned char etByte
typedef struct dbiplus::et_info et_info
typedef std::vector< field > Fields
typedef std::vector< field_value > sql_record
typedef std::vector< field_prop > record_prop
typedef std::vector< sql_record * > query_data
typedef field_value variant
Enumerations
enum dsStates {
dsSelect , dsInsert , dsEdit , dsUpdate ,
dsDelete , dsInactive
}
enum sqlType {
sqlSelect , sqlUpdate , sqlInsert , sqlDelete ,
sqlExec
}
enum fType {
ft_String , ft_Boolean , ft_Char , ft_WChar ,
ft_WideString , ft_Short , ft_UShort , ft_Int ,
ft_UInt , ft_Float , ft_Double , ft_LongDouble ,
ft_Int64 , ft_Object
}
Functions
static bool ci_test (char l, char r)
static size_t ci_find (const std::string &where, const std::string &what)
int callback (void *res_ptr, int ncol, char **result, char **cols)
static int busy_callback (void *, int busyCount)
static int AlphaNumericCollation (void *not_used, int nKey1, const void *pKey1, int nKey2, const void *pKey2)
Variables
static const char aDigits [] = "0123456789ABCDEF0123456789abcdef"
static const char aPrefix [] = "-x0\000X0"
constexpr std::array< et_info, 20 > fmtinfo
Typedef Documentation
et_info
typedef struct dbiplus::et_info dbiplus::et_info
etByte
typedef unsigned char dbiplus::etByte
Fields
typedef std::vector<field> dbiplus::Fields
ParamList
typedef std::map<std::string, field_value> dbiplus::ParamList
query_data
typedef std::vector<sql_record*> dbiplus::query_data
record_prop
typedef std::vector<field_prop> dbiplus::record_prop
sql_record
typedef std::vector< field_value > dbiplus::sql_record
StringList
typedef std::list<std::string> dbiplus::StringList
variant
typedef field_value dbiplus::variant
Enumeration Type Documentation
dsStates
enum dbiplus::dsStates
Enumerator
dsSelect
dsInsert
dsEdit
dsUpdate
dsDelete
dsInactive
fType
enum dbiplus::fType
Enumerator
ft_String
ft_Boolean
ft_Char
ft_WChar
ft_WideString
ft_Short
ft_UShort
ft_Int
ft_UInt
ft_Float
ft_Double
ft_LongDouble
ft_Int64
ft_Object
sqlType
enum dbiplus::sqlType
Enumerator
sqlSelect
sqlUpdate
sqlInsert
sqlDelete
sqlExec
Function Documentation
AlphaNumericCollation()
static int dbiplus::AlphaNumericCollation (void * not_used, int nKey1, const void * pKey1, int nKey2, const void * pKey2) static
Referenced by dbiplus::SqliteDatabase::connect().
busy_callback()
static int dbiplus::busy_callback (void * , int busyCount) static
References KODI::TIME::Sleep().
Referenced by dbiplus::SqliteDatabase::connect().
callback()
int dbiplus::callback (void * res_ptr, int ncol, char ** result, char ** cols)
References dbiplus::field_prop::name, dbiplus::result_set::record_header, dbiplus::result_set::records, dbiplus::field_value::set_asString(), and dbiplus::field_value::set_isNull().
Referenced by dbiplus::SqliteDatabase::drop_analytics(), dbiplus::SqliteDataset::exec(), dbiplus::SqliteDatabase::exists(), and dbiplus::SqliteDatabase::nextid().
ci_find()
static size_t dbiplus::ci_find (const std::string & where, const std::string & what) static
References ci_test().
Referenced by dbiplus::MysqlDataset::exec(), and dbiplus::MysqlDataset::query().
ci_test()
static bool dbiplus::ci_test (char l, char r) static
Referenced by ci_find().
Variable Documentation
aDigits
const char dbiplus::aDigits[] = "0123456789ABCDEF0123456789abcdef" static
Referenced by dbiplus::MysqlDatabase::mysqlVXPrintf().
aPrefix
const char dbiplus::aPrefix[] = "-x0\000X0" static
Referenced by dbiplus::MysqlDatabase::mysqlVXPrintf().
fmtinfo
constexpr std::array<et_info, 20> dbiplus::fmtinfo constexpr
Initial value:
= {{
  {'d', 10, 1, etRADIX, 0, 0},
  {'s', 0, 4, etSTRING, 0, 0},
  {'g', 0, 1, etGENERIC, 30, 0},
  {'z', 0, 4, etDYNSTRING, 0, 0},
  {'q', 0, 4, etSQLESCAPE, 0, 0},
  {'Q', 0, 4, etSQLESCAPE2, 0, 0},
  {'w', 0, 4, etSQLESCAPE3, 0, 0},
  {'c', 0, 0, etCHARX, 0, 0},
  {'o', 8, 0, etRADIX, 0, 2},
  {'u', 10, 0, etRADIX, 0, 0},
  {'x', 16, 0, etRADIX, 16, 1},
  {'X', 16, 0, etRADIX, 0, 4},
  {'f', 0, 1, etFLOAT, 0, 0},
  {'e', 0, 1, etEXP, 30, 0},
  {'E', 0, 1, etEXP, 14, 0},
  {'G', 0, 1, etGENERIC, 14, 0},
  {'i', 10, 1, etRADIX, 0, 0},
  {'n', 0, 0, etSIZE, 0, 0},
  {'%', 0, 0, etPERCENT, 0, 0},
  {'p', 16, 0, etPOINTER, 0, 1},
}}
Referenced by dbiplus::MysqlDatabase::mysqlVXPrintf().