Kodi Documentation: CSettingConditionsManager Class Reference
CSettingConditionsManager Class Reference
#include <SettingConditions.h>
Public Member Functions
CSettingConditionsManager ()=default
CSettingConditionsManager (const CSettingConditionsManager &)=delete
CSettingConditionsManager const & operator= (CSettingConditionsManager const &)=delete
virtual ~CSettingConditionsManager ()=default
void AddCondition (std::string condition)
void AddDynamicCondition (std::string identifier, SettingConditionCheck condition, void *data=nullptr)
void RemoveDynamicCondition (std::string identifier)
bool Check (std::string condition, const std::string &value="", const std::shared_ptr< const CSetting > &setting=std::shared_ptr< const CSetting >()) const
Private Types
using SettingConditionPair = std::pair< std::string, std::pair< SettingConditionCheck, void * > >
using SettingConditionMap = std::map< std::string, std::pair< SettingConditionCheck, void * > >
Private Attributes
SettingConditionMap m_conditions
std::set< std::string > m_defines
Member Typedef Documentation
SettingConditionMap
using CSettingConditionsManager::SettingConditionMap = std::map<std::string, std::pair<SettingConditionCheck, void*> > private
SettingConditionPair
using CSettingConditionsManager::SettingConditionPair = std::pair<std::string, std::pair<SettingConditionCheck, void*> > private
Constructor & Destructor Documentation
CSettingConditionsManager() [1/2]
CSettingConditionsManager::CSettingConditionsManager () default
CSettingConditionsManager() [2/2]
CSettingConditionsManager::CSettingConditionsManager (const CSettingConditionsManager &) delete
~CSettingConditionsManager()
virtual CSettingConditionsManager::~CSettingConditionsManager () virtual default
Member Function Documentation
AddCondition()
void CSettingConditionsManager::AddCondition (std::string condition)
References m_defines.
Referenced by CSettingsManager::AddCondition().
AddDynamicCondition()
void CSettingConditionsManager::AddDynamicCondition (std::string identifier, SettingConditionCheck condition, void * data = nullptr)
References data(), and m_conditions.
Referenced by CSettingsManager::AddDynamicCondition().
Check()
bool CSettingConditionsManager::Check (std::string condition, const std::string & value = "", const std::shared_ptr< const CSetting > & setting = std::shared_ptr<const CSetting>()) const
References m_conditions, m_defines, and value.
Referenced by CSettingCategoryAccessCondition::Check(), CSettingConditionItem::Check(), CSettingDependencyCondition::Check(), and CSettingRequirementCondition::Check().
operator=()
CSettingConditionsManager const & CSettingConditionsManager::operator= (CSettingConditionsManager const &) delete
RemoveDynamicCondition()
void CSettingConditionsManager::RemoveDynamicCondition (std::string identifier)
References m_conditions.
Referenced by CSettingsManager::RemoveDynamicCondition().
Member Data Documentation
m_conditions
SettingConditionMap CSettingConditionsManager::m_conditions private
Referenced by AddDynamicCondition(), Check(), and RemoveDynamicCondition().
m_defines
std::set<std::string> CSettingConditionsManager::m_defines private
Referenced by AddCondition(), and Check().
The documentation for this class was generated from the following files:
lib/SettingConditions.h
lib/SettingConditions.cpp