Kodi Documentation: CGUIWindowManager Class Reference
CGUIWindowManager Class Reference
Guilib classes » Window Reference » Window Manager and Callbacks
#include <GUIWindowManager.h>
Public Member Functions
CGUIWindowManager ()
~CGUIWindowManager () override
bool SendMessage (CGUIMessage &message)
bool SendMessage (int message, int senderID, int destID, int param1=0, int param2=0)
bool SendMessage (CGUIMessage &message, int window)
void Initialize ()
void Add (CGUIWindow *pWindow)
void AddUniqueInstance (CGUIWindow *window)
void AddCustomWindow (CGUIWindow *pWindow)
void Remove (int id)
void Delete (int id)
void ActivateWindow (int iWindowID, const std::string &strPath="")
void ForceActivateWindow (int iWindowID, const std::string &strPath="")
void ChangeActiveWindow (int iNewID, const std::string &strPath="")
void ActivateWindow (int iWindowID, const std::vector< std::string > &params, bool swappingWindows=false, bool force=false)
void PreviousWindow ()
bool SwitchToFullScreen (bool force=false)
Switch window to fullscreen.
void CloseDialogs (bool forceClose=false) const
void CloseInternalModalDialogs (bool forceClose=false) const
void OnApplicationMessage (KODI::MESSAGING::ThreadMessage *pMsg) override
This gets called whenever a message matching the registered message mask is processed.
int GetMessageMask () override
Should return the message mask that it wishes to receive messages for.
bool OnAction (const CAction &action) const
void Process (unsigned int currentTime)
Process active controls allowing them to animate before rendering.
void MarkDirty ()
Mark the screen as dirty, forcing a redraw at the next Render()
void MarkDirty (const CRect &rect)
Mark a region as dirty, forcing a redraw at the next Render()
bool Render ()
Rendering of the current window and any dialogs Render is called every frame to draw the current window and any dialogs. It should only be called from the application thread. Returns true only if it has rendered something.
void RenderEx () const
void AfterRender ()
Do any post render activities.
void FrameMove ()
Per-frame updating of the current window and any dialogs FrameMove is called every frame to update the current window and any dialogs on screen. It should only be called from the application thread.
bool Initialized () const
Return whether the window manager is initialized. The window manager is initialized on skin load - if the skin isn't yet loaded, no windows should be able to be initialized.
void CreateWindows ()
Create and initialize all windows and dialogs.
bool DestroyWindows ()
Destroy and remove all windows and dialogs.
void DestroyWindow (int id)
Destroy and remove the window or dialog with the given id.
Public Member Functions inherited from KODI::MESSAGING::IMessageTarget
virtual ~IMessageTarget ()=default
Private Attributes
friend CGUIDialog
friend CGUIMediaWindow
Constructor & Destructor Documentation
CGUIWindowManager()
CGUIWindowManager::CGUIWindowManager ()
~CGUIWindowManager()
CGUIWindowManager::~CGUIWindowManager () override default
Member Function Documentation
ActivateWindow() [1/2]
void CGUIWindowManager::ActivateWindow (int iWindowID, const std::string & strPath = "")
References ActivateWindow().
Referenced by anonymous_namespace{GUIBuiltins.cpp}::ActivateAndFocus(), PVR::CGUIWindowPVRProvidersBase::ActivateChannelsWindow(), PVR::CGUIWindowPVRProvidersBase::ActivateRecordingsWindow(), CApplicationPowerHandling::ActivateScreenSaver(), anonymous_namespace{GUIBuiltins.cpp}::ActivateWindow(), ActivateWindow(), CGUIPlayerAnnouncementHandler::Announce(), ChangeActiveWindow(), ADDON::Interface_GUIWindow::close(), ADDON::Interface_GUIWindow::destroy(), XBMCAddon::xbmcgui::Window::dispose(), ADDON::Interface_GUIWindow::do_modal(), PVR::CPVRGUIActionsEPG::EditSavedSearch(), CPartyModeManager::Enable(), CMediaLibraryEvent::Execute(), PVR::CPVRGUIActionsEPG::ExecuteSavedSearch(), PVR::CPVRGUIActionsEPG::FindSimilar(), ForceActivateWindow(), CApplication::Initialize(), CGUIWindowAddonBrowser::InstallFromZip(), CGUIWindowMusicBase::LoadPlayList(), CGUIWindowPictures::LoadPlayList(), CApplicationSkinHandling::LoadSkin(), CProfileManager::LogOff(), CApplication::OnAction(), CGUIWindowMusicBase::OnAction(), CGUIWindowVisualisation::OnAction(), CGUIWindowFullScreen::OnAction(), CGUIWindowVideoBase::OnAction(), CApplication::OnApplicationMessage(), OnApplicationMessage(), CGUIMediaWindow::OnClick(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), CGUIWindowAddonBrowser::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), CGUIDialogLibExportSettings::OnOK(), ADDON::CAddonSystemSettings::OnSettingAction(), CApplicationSettingsHandling::OnSettingAction(), PERIPHERALS::CPeripherals::OnSettingAction(), PVR::CPVRGUIActionListener::OnSettingAction(), CGUIWindowPictures::OnShowPictureRecursive(), CGUIWindowFileManager::OnStart(), KODI::RETRO::CRetroPlayer::OpenOSD(), CGUIDialogVideoInfo::Play(), PreviousWindow(), KODI::JOYSTICK::CGUIDialogNewJoystick::Process(), CApplicationSkinHandling::ReloadSkin(), CGUIWindowSlideShow::RunSlideShow(), ADDON::Interface_GUIWindow::show(), CGUIDialogAddonSettings::ShowForAddon(), CEventLog::ShowFullEventLog(), CGUIWindowPictures::ShowPicture(), CNetworkServices::Start(), and SwitchToFullScreen().
ActivateWindow() [2/2]
void CGUIWindowManager::ActivateWindow (int iWindowID, const std::vector< std::string > & params, bool swappingWindows = false, bool force = false)
References CServiceBroker::GetAppMessenger(), CServiceBroker::GetWinSystem(), and TMSG_GUI_ACTIVATE_WINDOW.
Add()
void CGUIWindowManager::Add (CGUIWindow * pWindow)
References CGUIWindow::GetIDRange(), CServiceBroker::GetWinSystem(), CLog::Log(), and LOGERROR.
Referenced by AddCustomWindow(), AddUniqueInstance(), ADDON::Interface_GUIWindow::create(), CreateWindows(), CApplicationSkinHandling::LoadSkin(), and XBMCAddon::xbmcgui::Window::setWindow().
AddCustomWindow()
void CGUIWindowManager::AddCustomWindow (CGUIWindow * pWindow)
References Add(), and CServiceBroker::GetWinSystem().
Referenced by CApplicationSkinHandling::LoadCustomWindows().
AddUniqueInstance()
void CGUIWindowManager::AddUniqueInstance (CGUIWindow * window)
References Add(), CGUIControl::GetID(), CServiceBroker::GetWinSystem(), and CGUIWindow::SetID().
Referenced by CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFileList(), CGUIDialogFileBrowser::ShowAndGetImage(), and CGUIDialogFileBrowser::ShowAndGetSource().
AfterRender()
void CGUIWindowManager::AfterRender ()
Do any post render activities.
References CGUIWindow::AfterRender(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CGUIControl::IsControlDirty(), CGUIWindow::IsDialogRunning(), CGUIControl::MarkDirtyRegion(), and CGraphicContext::ResetDepth().
Referenced by CApplication::Render().
ChangeActiveWindow()
void CGUIWindowManager::ChangeActiveWindow (int iNewID, const std::string & strPath = "")
References ActivateWindow().
Referenced by CProfileManager::FinalizeLoadProfile(), and CGUIDialogContextMenu::SwitchMedia().
CloseDialogs()
void CGUIWindowManager::CloseDialogs (bool forceClose = false) const
References CServiceBroker::GetWinSystem().
Referenced by anonymous_namespace{GUIBuiltins.cpp}::CloseDialog(), and KODI::RETRO::CRetroPlayer::CloseOSD().
CloseInternalModalDialogs()
void CGUIWindowManager::CloseInternalModalDialogs (bool forceClose = false) const
References CServiceBroker::GetWinSystem().
Referenced by KODI::RETRO::CGameWindowFullScreen::OnDeinitWindow(), CGUIWindowVisualisation::OnMessage(), and CGUIWindowFullScreen::OnMessage().
CreateWindows()
void CGUIWindowManager::CreateWindows ()
Create and initialize all windows and dialogs.
References Add(), WINDOW_DIALOG_SELECT_AUDIO_STREAM, WINDOW_DIALOG_SELECT_SUBTITLE_STREAM, WINDOW_DIALOG_SELECT_VIDEO_EXTRA, WINDOW_DIALOG_SELECT_VIDEO_STREAM, WINDOW_DIALOG_SELECT_VIDEO_VERSION, and WINDOW_SKIN_SETTINGS.
Referenced by CApplication::Initialize().
Delete()
void CGUIWindowManager::Delete (int id)
References CServiceBroker::GetWinSystem(), and Remove().
Referenced by XBMCAddon::xbmcgui::Window::dispose(), XBMCAddon::xbmcgui::Window::OnDeinitWindow(), CApplication::OnMessage(), and CApplicationSkinHandling::UnloadSkin().
DestroyWindow()
void CGUIWindowManager::DestroyWindow (int id)
Destroy and remove the window or dialog with the given id.
Parameters
id the window id
References CGUIWindow::FreeResources(), CServiceBroker::GetWinSystem(), and Remove().
Referenced by DestroyWindows().
DestroyWindows()
bool CGUIWindowManager::DestroyWindows ()
Destroy and remove all windows and dialogs.
Returns
true on success, false if destruction fails for any window
References DestroyWindow(), CLog::Log(), LOGERROR, Remove(), WINDOW_ADDON_BROWSER, WINDOW_DIALOG_ADDON_INFO, WINDOW_DIALOG_ADDON_SETTINGS, WINDOW_DIALOG_AUDIO_OSD_SETTINGS, WINDOW_DIALOG_BUSY, WINDOW_DIALOG_BUSY_NOCANCEL, WINDOW_DIALOG_BUTTON_MENU, WINDOW_DIALOG_CMS_OSD_SETTINGS, WINDOW_DIALOG_COLOR_PICKER, WINDOW_DIALOG_CONTENT_SETTINGS, WINDOW_DIALOG_CONTEXT_MENU, WINDOW_DIALOG_GAME_ADVANCED_SETTINGS, WINDOW_DIALOG_GAME_AGENTS, WINDOW_DIALOG_GAME_CONTROLLERS, WINDOW_DIALOG_GAME_OSD, WINDOW_DIALOG_GAME_PORTS, WINDOW_DIALOG_GAME_SAVES, WINDOW_DIALOG_GAME_STRETCH_MODE, WINDOW_DIALOG_GAME_VIDEO_FILTER, WINDOW_DIALOG_GAME_VIDEO_ROTATION, WINDOW_DIALOG_GAME_VOLUME, WINDOW_DIALOG_GAMEPAD, WINDOW_DIALOG_IN_GAME_SAVES, WINDOW_DIALOG_INFOPROVIDER_SETTINGS, WINDOW_DIALOG_KAI_TOAST, WINDOW_DIALOG_KEYBOARD, WINDOW_DIALOG_KEYBOARD_TOUCH, WINDOW_DIALOG_LIBEXPORT_SETTINGS, WINDOW_DIALOG_LOCK_SETTINGS, WINDOW_DIALOG_MANAGE_VIDEO_EXTRAS, WINDOW_DIALOG_MANAGE_VIDEO_VERSIONS, WINDOW_DIALOG_MEDIA_FILTER, WINDOW_DIALOG_MEDIA_SOURCE, WINDOW_DIALOG_MUSIC_INFO, WINDOW_DIALOG_MUSIC_OSD, WINDOW_DIALOG_NETWORK_SETUP, WINDOW_DIALOG_NUMERIC, WINDOW_DIALOG_OK, WINDOW_DIALOG_OSD_TELETEXT, WINDOW_DIALOG_PERIPHERAL_SETTINGS, WINDOW_DIALOG_PERIPHERALS, WINDOW_DIALOG_PICTURE_INFO, WINDOW_DIALOG_PLAYER_CONTROLS, WINDOW_DIALOG_PLAYER_PROCESS_INFO, WINDOW_DIALOG_PROFILE_SETTINGS, WINDOW_DIALOG_PROGRESS, WINDOW_DIALOG_PVR_CHANNEL_GUIDE, WINDOW_DIALOG_PVR_CHANNEL_MANAGER, WINDOW_DIALOG_PVR_CHANNEL_SCAN, WINDOW_DIALOG_PVR_CLIENT_PRIORITIES, WINDOW_DIALOG_PVR_GROUP_MANAGER, WINDOW_DIALOG_PVR_GUIDE_CONTROLS, WINDOW_DIALOG_PVR_GUIDE_INFO, WINDOW_DIALOG_PVR_GUIDE_SEARCH, WINDOW_DIALOG_PVR_OSD_CHANNELS, WINDOW_DIALOG_PVR_RADIO_RDS_INFO, WINDOW_DIALOG_PVR_RECORDING_INFO, WINDOW_DIALOG_PVR_RECORDING_SETTING, WINDOW_DIALOG_PVR_TIMER_SETTING, WINDOW_DIALOG_PVR_UPDATE_PROGRESS, WINDOW_DIALOG_SEEK_BAR, WINDOW_DIALOG_SELECT, WINDOW_DIALOG_SELECT_AUDIO_STREAM, WINDOW_DIALOG_SELECT_SUBTITLE_STREAM, WINDOW_DIALOG_SELECT_VIDEO_EXTRA, WINDOW_DIALOG_SELECT_VIDEO_STREAM, WINDOW_DIALOG_SELECT_VIDEO_VERSION, WINDOW_DIALOG_SLIDER, WINDOW_DIALOG_SMART_PLAYLIST_EDITOR, WINDOW_DIALOG_SMART_PLAYLIST_RULE, WINDOW_DIALOG_SONG_INFO, WINDOW_DIALOG_SUB_MENU, WINDOW_DIALOG_SUBTITLE_OSD_SETTINGS, WINDOW_DIALOG_SUBTITLES, WINDOW_DIALOG_TEXT_VIEWER, WINDOW_DIALOG_VIDEO_BOOKMARKS, WINDOW_DIALOG_VIDEO_INFO, WINDOW_DIALOG_VIDEO_OSD, WINDOW_DIALOG_VIDEO_OSD_SETTINGS, WINDOW_DIALOG_VIS_PRESET_LIST, WINDOW_DIALOG_VOLUME_BAR, WINDOW_DIALOG_YES_NO, WINDOW_EVENT_LOG, WINDOW_FAVOURITES, WINDOW_FILES, WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, WINDOW_GAMES, WINDOW_HOME, WINDOW_LOGIN_SCREEN, WINDOW_MUSIC_NAV, WINDOW_MUSIC_PLAYLIST, WINDOW_MUSIC_PLAYLIST_EDITOR, WINDOW_PICTURES, WINDOW_PROGRAMS, WINDOW_RADIO_CHANNELS, WINDOW_RADIO_GUIDE, WINDOW_RADIO_PROVIDERS, WINDOW_RADIO_RECORDINGS, WINDOW_RADIO_SEARCH, WINDOW_RADIO_TIMER_RULES, WINDOW_RADIO_TIMERS, WINDOW_SCREEN_CALIBRATION, WINDOW_SCREENSAVER, WINDOW_SETTINGS_INTERFACE, WINDOW_SETTINGS_MEDIA, WINDOW_SETTINGS_MENU, WINDOW_SETTINGS_MYGAMES, WINDOW_SETTINGS_MYPVR, WINDOW_SETTINGS_PLAYER, WINDOW_SETTINGS_PROFILES, WINDOW_SETTINGS_SERVICE, WINDOW_SETTINGS_SYSTEM, WINDOW_SKIN_SETTINGS, WINDOW_SLIDESHOW, WINDOW_SPLASH, WINDOW_STARTUP_ANIM, WINDOW_SYSTEM_INFORMATION, WINDOW_TV_CHANNELS, WINDOW_TV_GUIDE, WINDOW_TV_PROVIDERS, WINDOW_TV_RECORDINGS, WINDOW_TV_SEARCH, WINDOW_TV_TIMER_RULES, WINDOW_TV_TIMERS, WINDOW_VIDEO_NAV, WINDOW_VIDEO_PLAYLIST, WINDOW_VISUALISATION, and WINDOW_WEATHER.
ForceActivateWindow()
void CGUIWindowManager::ForceActivateWindow (int iWindowID, const std::string & strPath = "")
References ActivateWindow().
Referenced by CGUIDialogVideoSettings::OnSettingAction(), and SwitchToFullScreen().
FrameMove()
void CGUIWindowManager::FrameMove ()
Per-frame updating of the current window and any dialogs FrameMove is called every frame to update the current window and any dialogs on screen. It should only be called from the application thread.
References CGUIWindow::FrameMove(), CGUIWindow::FreeResources(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CServiceBroker::GetWinSystem(), and CGUIInfoManager::UpdateAVInfo().
Referenced by CApplication::FrameMove().
GetMessageMask()
int CGUIWindowManager::GetMessageMask () override virtual
Should return the message mask that it wishes to receive messages for.
The message mask is defined in "messaging/ApplicationMessenger.h" pick the next one available when creating a new
Implements KODI::MESSAGING::IMessageTarget.
References TMSG_MASK_WINDOWMANAGER.
Initialize()
void CGUIWindowManager::Initialize ()
References CServiceBroker::GetAppMessenger().
Referenced by CApplicationSkinHandling::LoadSkin().
Initialized()
bool CGUIWindowManager::Initialized () const inline
Return whether the window manager is initialized. The window manager is initialized on skin load - if the skin isn't yet loaded, no windows should be able to be initialized.
Returns
true if the window manager is initialized, false otherwise.
MarkDirty() [1/2]
void CGUIWindowManager::MarkDirty ()
Mark the screen as dirty, forcing a redraw at the next Render()
References CServiceBroker::GetWinSystem(), and MarkDirty().
Referenced by CBaseRenderer::MarkDirty(), MarkDirty(), KODI::WINDOWING::X11::CWinEventsX11::MessagePump(), CApplication::OnApplicationMessage(), and CWinEventsWin32::WndProc().
MarkDirty() [2/2]
void CGUIWindowManager::MarkDirty (const CRect & rect)
Mark a region as dirty, forcing a redraw at the next Render()
References CGUIWindow::IsDialogRunning(), and CGUIControl::MarkDirtyRegion().
OnAction()
bool CGUIWindowManager::OnAction (const CAction & action) const
References ACTION_GESTURE_ABORT, ACTION_GESTURE_BEGIN, ACTION_GESTURE_END, CLog::Log(), and LOGDEBUG.
Referenced by OnApplicationMessage().
OnApplicationMessage()
void CGUIWindowManager::OnApplicationMessage (KODI::MESSAGING::ThreadMessage * msg) override virtual
This gets called whenever a message matching the registered message mask is processed.
There are no ordering guarantees here so implementations should never rely on a certain ordering of messages.
Cleaning up any pointers stored in the message payload is not specified and is decided by the implementer of the message. In general prefer to delete any data in this method to keep the callsites cleaner and simpler but if data is to be passed back it's perfectly valid to handle it any way that fits the situation as long as it's documented along with the message.
To return a simple value the result parameter of
See also
ThreadMessage can be used as it will be used as the return value for
CApplicationMessenger::SendMsg. It is up to the implementer to decide if this is to be used and it should be documented along with any new message implemented.
Implements KODI::MESSAGING::IMessageTarget.
References ActivateWindow(), CGUIWindow::Close(), KODI::MESSAGING::ThreadMessage::dwMessage, g_application, CLog::Log(), LOGWARNING, KODI::MESSAGING::ThreadMessage::lpVoid, OnAction(), CGUIWindow::OnAction(), CGUIDialog::Open(), KODI::MESSAGING::ThreadMessage::param1, KODI::MESSAGING::ThreadMessage::param2, KODI::MESSAGING::ThreadMessage::params, PreviousWindow(), SendMessage(), KODI::MESSAGING::ThreadMessage::SetResult(), CGUIDialogOK::ShowAndGetInput(), KODI::MESSAGING::ThreadMessage::strParam, TMSG_GUI_ACTION, TMSG_GUI_ACTIVATE_WINDOW, TMSG_GUI_ADDON_DIALOG, TMSG_GUI_DIALOG_OK, TMSG_GUI_DIALOG_OPEN, TMSG_GUI_DIALOG_YESNO, TMSG_GUI_MESSAGE, TMSG_GUI_PREVIOUS_WINDOW, TMSG_GUI_PYTHON_DIALOG, TMSG_GUI_WINDOW_CLOSE, WINDOW_DIALOG_OK, WINDOW_DIALOG_YES_NO, and WINDOW_INVALID.
PreviousWindow()
void CGUIWindowManager::PreviousWindow ()
Todo:
we may need to test here for the whether our history should be changed
References ActivateWindow(), CServiceBroker::GetGUI(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetGUIControlsInfoProvider(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CGUIWindow::GetPreviousWindow(), CServiceBroker::GetWinSystem(), GUI_MSG_WINDOW_INIT, CLog::Log(), LOGDEBUG, LOGERROR, CGUIWindow::OnMessage(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::SetNextWindow(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::SetPreviousWindow(), WINDOW_HOME, and WINDOW_INVALID.
Referenced by KODI::RETRO::CGameWindowFullScreen::OnAction(), CGUIWindowMusicPlayList::OnAction(), CGUIWindowVisualisation::OnAction(), CGUIWindowFullScreen::OnAction(), CGUIWindowVideoPlaylist::OnAction(), CApplication::OnApplicationMessage(), OnApplicationMessage(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CGUIWindow::OnBack(), CGUIWindowVisualisation::OnMessage(), CGUIWindowFullScreen::OnMessage(), CApplication::PlaybackCleanup(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CApplication::StopPlaying(), and CApplicationPowerHandling::WakeUpScreenSaver().
Process()
void CGUIWindowManager::Process (unsigned int currentTime)
Process active controls allowing them to animate before rendering.
References CGUIControlGroup::AssignDepth(), CGUIWindow::DoProcess(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetWinSystem(), CGUIWindow::IsDialog(), CGUIWindow::IsDialogRunning(), and RenderOrderSortFunction().
Referenced by CApplication::FrameMove().
Remove()
void CGUIWindowManager::Remove (int id)
References CServiceBroker::GetWinSystem(), CLog::Log(), and LOGWARNING.
Referenced by Delete(), ADDON::Interface_GUIWindow::destroy(), DestroyWindow(), DestroyWindows(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFileList(), CGUIDialogFileBrowser::ShowAndGetImage(), and CGUIDialogFileBrowser::ShowAndGetSource().
Render()
bool CGUIWindowManager::Render ()
Rendering of the current window and any dialogs Render is called every frame to draw the current window and any dialogs. It should only be called from the application thread. Returns true only if it has rendered something.
References DIRTYREGION_SOLVER_FILL_VIEWPORT_ALWAYS, DIRTYREGION_SOLVER_FILL_VIEWPORT_ON_CHANGE, CGUITexture::DrawQuad(), CServiceBroker::GetAppMessenger(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), CGraphicContext::ResetScissors(), CGraphicContext::SetRenderingResolution(), and CGraphicContext::SetScissors().
Referenced by CScreenshotSurfaceWindows::Capture(), CScreenshotSurfaceGL::Capture(), CScreenshotSurfaceGLES::Capture(), and CApplication::Render().
RenderEx()
void CGUIWindowManager::RenderEx () const
References CGUIControlGroup::RenderEx().
Referenced by CApplication::Render().
SendMessage() [1/3]
bool CGUIWindowManager::SendMessage (CGUIMessage & message)
References CGUIMessage::GetControlId(), CGUIControl::GetID(), CGUIMessage::GetMessage(), CGUIMessage::GetSenderId(), CServiceBroker::GetWinSystem(), GUI_MSG_NOTIFY_ALL, CGUIWindow::IsModalDialog(), CGUIWindow::OnMessage(), and IMsgTargetCallback::OnMessage().
Referenced by anonymous_namespace{GUIBuiltins.cpp}::ActivateAndFocus(), KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), CGraphicContext::ApplyVideoResolution(), ChangeSortMethod(), ChangeViewMode(), PVR::CPVRGUIActionsPlayback::CheckAndSwitchToFullscreen(), CInertialScrollingHandler::CheckForInertialScrolling(), CGUIViewControl::Clear(), CGUIWindowFileManager::ClearFileItems(), CGUIWindowSettingsProfile::ClearListItems(), KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist(), ControlMove(), CGUIVisualisationControl::DeInitVisualization(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::ExecuteAction(), FAVOURITES_UTILS::anonymous_namespace{FavouritesUtils.cpp}::ExecuteAction(), anonymous_namespace{DirectoryProvider.cpp}::ExecuteAction(), CGUIAction::ExecuteActions(), CGraphicContext::Flip(), CApplicationPlayer::FrameMove(), CSeekHandler::FrameMove(), CGUIWindowSettingsScreenCalibration::FrameMove(), CApplication::FrameMove(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetLabel(), CGUIWindowSettingsProfile::GetSelectedItem(), CGUIViewControl::GetSelectedItem(), XBMCAddon::xbmcgui::ControlEdit::getText(), KODI::PLAYLIST::CPlayListPlayer::Insert(), CProfileManager::LoadProfile(), CGUIDialogVideoInfo::ManageVideoItemArtwork(), MasterMode(), CWinEventsAndroid::MessagePump(), CWinEventsWin10::MessagePump(), CApplication::OnAction(), CGUIWindowSettingsScreenCalibration::OnAction(), CGUIDialogVideoBookmarks::OnAddBookmark(), CGUIDialogVideoBookmarks::OnAddEpisodeBookmark(), OnApplicationMessage(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRefreshChannelLogos(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSongInfo::OnGetArt(), CGUIDialogVisualisationPresetList::OnInitWindow(), CPictureThumbLoader::OnLoaderFinish(), CApplication::OnMessage(), GUIFontManager::OnMessage(), CGUIDialogMusicInfo::OnMessage(), CGUIDialogMusicOSD::OnMessage(), CGUIDialogSongInfo::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIVideoControl::OnMouseEvent(), OpenDefaultSettings(), CGUIDialogVideoInfo::Play(), PVR::CPVRGUIActionsPlayback::PlayEpgTag(), PVR::CPVRGUIActionsPlayback::PlayRecording(), Refresh(), CApplicationSkinHandling::ReloadSkin(), KODI::PLAYLIST::CPlayListPlayer::Remove(), KODI::PLAYLIST::CPlayListPlayer::Reset(), CGUIWindowSettingsScreenCalibration::ResetCalibration(), SearchVideoLibrary(), CGUISliderControl::SendClick(), SendClick(), SendMessage(), SendMessage(), SendMessage(), CGUIControl::SendWindowMessage(), CGUIViewControl::SetCurrentView(), SetDefaultAddon(), CGUIDialogVideoManagerVersions::SetDefaultVideoVersion(), SetFocus(), CGUIViewControl::SetFocused(), SetHidden(), SetLocation(), KODI::PLAYLIST::CPlayListPlayer::SetRepeat(), CGUIViewControl::SetSelectedItem(), KODI::PLAYLIST::CPlayListPlayer::SetShuffle(), SetSortMethod(), CGUIDialogVideoInfo::SetUserrating(), CGraphicContext::SetVideoResolutionInternal(), SetViewMode(), SetVisible(), ShiftPage(), KODI::PLAYLIST::CPlayListPlayer::Swap(), SwitchLocation(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), ToggleSortDirection(), CGUIDialogVideoInfo::Update(), Update(), CGUIViewControl::UpdateContents(), CGUIWindowFileManager::UpdateControl(), XBMCAddon::xbmc::Player::updateInfoTag(), and CGUIViewControl::UpdateViewAsControl().
SendMessage() [2/3]
bool CGUIWindowManager::SendMessage (CGUIMessage & message, int window)
References CGUIWindow::OnMessage(), and SendMessage().
SendMessage() [3/3]
bool CGUIWindowManager::SendMessage (int message, int senderID, int destID, int param1 = 0, int param2 = 0)
References SendMessage().
SwitchToFullScreen()
bool CGUIWindowManager::SwitchToFullScreen (bool force = false)
Switch window to fullscreen.
Parameters
force enforce fullscreen switch
Returns
True if switch is made to fullscreen, otherwise False
References ActivateWindow(), CGUIWindow::Close(), ForceActivateWindow(), CServiceBroker::GetAppComponents(), WINDOW_DIALOG_MUSIC_INFO, WINDOW_DIALOG_SONG_INFO, WINDOW_DIALOG_VIDEO_INFO, WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, WINDOW_INVALID, WINDOW_SLIDESHOW, and WINDOW_VISUALISATION.
Referenced by CApplication::OnAction(), CGUIWindowHome::OnAction(), CApplication::OnApplicationMessage(), CApplication::OnMessage(), and CXBMCApp::onPause().
Member Data Documentation
CGUIDialog
friend CGUIWindowManager::CGUIDialog private
CGUIMediaWindow
friend CGUIWindowManager::CGUIMediaWindow private
The documentation for this class was generated from the following files:
GUIWindowManager.h
GUIWindowManager.cpp