Kodi Documentation: kodi::addon::PVRTimer Class Reference
kodi::addon::PVRTimer Class Reference
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 6. Timer » class PVRTimer
#include <Timers.h>
Public Member Functions
void SetClientIndex (unsigned int clientIndex)
required
The index of this timer given by the client.
unsigned int GetClientIndex () const
To get with SetClientIndex changed values.
void SetState (PVR_TIMER_STATE state)
required
The state of this timer.
PVR_TIMER_STATE GetState () const
To get with SetState changed values.
void SetTimerType (unsigned int timerType)
required
The type of this timer.
unsigned int GetTimerType () const
To get with SetTimerType changed values.
void SetTitle (const std::string &title)
required
A title for this timer.
std::string GetTitle () const
To get with SetTitle changed values.
void SetParentClientIndex (unsigned int parentClientIndex)
optional
For timers scheduled by a repeating timer.
unsigned int GetParentClientIndex () const
To get with SetParentClientIndex changed values.
void SetClientChannelUid (int clientChannelUid)
optional
Unique identifier of the channel to record on.
int GetClientChannelUid () const
To get with SetClientChannelUid changed values.
void SetStartTime (time_t startTime)
optional
Start time of the recording in UTC.
time_t GetStartTime () const
To get with SetStartTime changed values.
void SetEndTime (time_t endTime)
optional
End time of the recording in UTC.
time_t GetEndTime () const
To get with SetEndTime changed values.
void SetStartAnyTime (bool startAnyTime)
optional
For EPG based (not Manual) timers indicates startTime does not apply.
bool GetStartAnyTime () const
To get with SetStartAnyTime changed values.
void SetEndAnyTime (bool endAnyTime)
optional
For EPG based (not Manual) timers indicates endTime does not apply.
bool GetEndAnyTime () const
To get with SetEndAnyTime changed values.
void SetEPGSearchString (const std::string &epgSearchString)
optional
A string used to search epg data for repeating epg-based timers.
std::string GetEPGSearchString () const
To get with SetEPGSearchString changed values.
void SetFullTextEpgSearch (bool fullTextEpgSearch)
optional
Indicates, whether SetEPGSearchString() is to match against the epg episode title only or also against "other" epg data (backend-dependent).
bool GetFullTextEpgSearch () const
To get with SetFullTextEpgSearch changed values.
void SetDirectory (const std::string &directory)
optional
The (relative) directory where the recording will be stored in.
std::string GetDirectory () const
To get with SetDirectory changed values.
void SetSummary (const std::string &summary)
optional
The summary for this timer.
std::string GetSummary () const
To get with SetDirectory changed values.
void SetPriority (int priority)
optional
The priority of this timer.
int GetPriority () const
To get with SetPriority changed values.
void SetLifetime (int priority)
optional
Lifetime of recordings created by this timer.
int GetLifetime () const
To get with SetLifetime changed values.
void SetMaxRecordings (int maxRecordings)
optional
Maximum number of recordings this timer shall create.
int GetMaxRecordings () const
To get with SetMaxRecordings changed values.
void SetRecordingGroup (unsigned int recordingGroup)
optional
Integer ref to addon/backend defined list of recording groups.
unsigned int GetRecordingGroup () const
To get with SetRecordingGroup changed values.
void SetFirstDay (time_t firstDay)
optional
The first day this timer is active, for repeating timers.
time_t GetFirstDay () const
To get with SetFirstDay changed values.
void SetWeekdays (unsigned int weekdays)
optional
Week days, for repeating timers (see PVR_WEEKDAY_* constant values)
unsigned int GetWeekdays () const
To get with SetFirstDay changed values.
void SetPreventDuplicateEpisodes (unsigned int preventDuplicateEpisodes)
optional
Prevent duplicate episodes.
unsigned int GetPreventDuplicateEpisodes () const
To get with SetPreventDuplicateEpisodes changed values.
void SetEPGUid (unsigned int epgUid)
optional
EPG event id associated with this timer. Event ids must be unique for a channel.
unsigned int GetEPGUid () const
To get with SetEPGUid changed values.
void SetMarginStart (unsigned int marginStart)
optional
If set, the backend starts the recording selected minutes before SetStartTime.
unsigned int GetMarginStart () const
To get with SetMarginStart changed values.
void SetMarginEnd (unsigned int marginEnd)
optional
If set, the backend ends the recording selected minutes after SetEndTime.
unsigned int GetMarginEnd () const
To get with SetMarginEnd changed values.
void SetGenreType (int genreType)
optional
Genre type.
int GetGenreType () const
To get with SetGenreType changed values.
void SetGenreSubType (int genreSubType)
optional
Genre sub type.
int GetGenreSubType () const
To get with SetGenreType changed values.
void SetSeriesLink (const std::string &seriesLink)
optional
Series link for this timer.
std::string GetSeriesLink () const
To get with SetSeriesLink changed values.
void SetCustomProperties (const std::vector< PVRSettingKeyValuePair > &properties)
optional
Array containing the custom properties.
std::vector< PVRSettingKeyValuePair > GetCustomProperties () const
To get with SetCustomProperties changed values.
Public Member Functions inherited from kodi::addon::DynamicCStructHdl< PVRTimer, PVR_TIMER >
DynamicCStructHdl ()
DynamicCStructHdl (const DynamicCStructHdl &cppClass)
DynamicCStructHdl (const PVR_TIMER *cStructure)
DynamicCStructHdl (PVR_TIMER *cStructure)
const DynamicCStructHdl & operator= (const DynamicCStructHdl &right)
const DynamicCStructHdl & operator= (const PVR_TIMER &right)
virtual ~DynamicCStructHdl ()
operator PVR_TIMER * ()
operator const PVR_TIMER * () const
const PVR_TIMER * GetCStructure () const
PVR_TIMER * release ()
Static Public Member Functions
static void AllocResources (const PVR_TIMER *source, PVR_TIMER *target)
static void FreeResources (PVR_TIMER *target)
Private Member Functions
PVRTimer (const PVR_TIMER *timer)
PVRTimer (PVR_TIMER *timer)
Friends
class CInstancePVRClient
Additional Inherited Members
Protected Attributes inherited from kodi::addon::DynamicCStructHdl< PVRTimer, PVR_TIMER >
PVR_TIMER * m_cStructure
Constructor & Destructor Documentation
PVRTimer() [1/2]
kodi::addon::PVRTimer::PVRTimer (const PVR_TIMER * timer) inline private
PVRTimer() [2/2]
kodi::addon::PVRTimer::PVRTimer (PVR_TIMER * timer) inline private
Member Function Documentation
AllocResources()
static void kodi::addon::PVRTimer::AllocResources (const PVR_TIMER * source, PVR_TIMER * target) inline static
References kodi::addon::PVRSettingKeyValuePair::AllocAndCopyData(), kodi::addon::AllocAndCopyString(), PVR_TIMER::customProps, PVR_TIMER::iCustomPropsSize, PVR_TIMER::strDirectory, PVR_TIMER::strEpgSearchString, PVR_TIMER::strSeriesLink, PVR_TIMER::strSummary, and PVR_TIMER::strTitle.
FreeResources()
static void kodi::addon::PVRTimer::FreeResources (PVR_TIMER * target) inline static
References PVR_TIMER::customProps, kodi::addon::PVRSettingKeyValuePair::FreeResources(), kodi::addon::FreeString(), PVR_TIMER::iCustomPropsSize, PVR_TIMER::strDirectory, PVR_TIMER::strEpgSearchString, PVR_TIMER::strSeriesLink, PVR_TIMER::strSummary, and PVR_TIMER::strTitle.
Friends And Related Symbol Documentation
CInstancePVRClient
friend class CInstancePVRClient friend
The documentation for this class was generated from the following file:
Timers.h