Kodi Documentation: XFILE::CFileAndroidApp Class Reference
XFILE::CFileAndroidApp Class Reference
#include <AndroidAppFile.h>
Public Member Functions
CFileAndroidApp (void)
Currently only used for retrieving App Icons.
~CFileAndroidApp () override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
Return 32bit rgba raw bitmap.
void Close () override
int64_t GetLength () override
int64_t Seek (int64_t, int) override
int64_t GetPosition () override
int GetChunkSize () override
int IoControl (EIoControl request, void *param) override
virtual unsigned int ReadIcon (unsigned char **lpBuf, unsigned int *width, unsigned int *height)
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool OpenForWrite (const CURL &url, bool bOverWrite=false)
virtual bool ReOpen (const CURL &url)
virtual int Stat (struct __stat64 *buffer)
virtual ssize_t Write (const void *bufPtr, size_t bufSize)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual double GetDownloadSpeed ()
virtual bool Delete (const CURL &url)
virtual bool Rename (const CURL &url, const CURL &urlnew)
virtual bool SetHidden (const CURL &url, bool hidden)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Protected Member Functions
bool IsValidFile (const CURL &url)
Private Attributes
CURL m_url
std::string m_packageName
std::string m_packageLabel
int m_icon
int m_iconWidth
int m_iconHeight
Constructor & Destructor Documentation
CFileAndroidApp()
CFileAndroidApp::CFileAndroidApp (void)
Currently only used for retrieving App Icons.
References m_iconHeight, and m_iconWidth.
~CFileAndroidApp()
CFileAndroidApp::~CFileAndroidApp (void) override
References Close().
Member Function Documentation
Close()
void CFileAndroidApp::Close () override virtual
Implements XFILE::IFile.
Referenced by ~CFileAndroidApp().
Exists()
bool CFileAndroidApp::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References CXBMCApp::Get(), CURL::Get(), CXBMCApp::GetApplications(), and URIUtils::GetFileName().
GetChunkSize()
int CFileAndroidApp::GetChunkSize () override virtual
Reimplemented from XFILE::IFile.
GetLength()
int64_t XFILE::CFileAndroidApp::GetLength () inline override virtual
Implements XFILE::IFile.
GetPosition()
int64_t XFILE::CFileAndroidApp::GetPosition () inline override virtual
Implements XFILE::IFile.
IoControl()
int CFileAndroidApp::IoControl (EIoControl request, void * param) override virtual
Reimplemented from XFILE::IFile.
References XFILE::IOCTRL_SEEK_POSSIBLE.
IsValidFile()
bool XFILE::CFileAndroidApp::IsValidFile (const CURL & url) protected
Open()
bool CFileAndroidApp::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References CXBMCApp::Get(), CURL::Get(), CXBMCApp::GetApplications(), URIUtils::GetFileName(), m_icon, m_packageLabel, m_packageName, and m_url.
Read()
ssize_t XFILE::CFileAndroidApp::Read (void * lpBuf, size_t uiBufSize) inline override virtual
Return 32bit rgba raw bitmap.
Implements XFILE::IFile.
ReadIcon()
unsigned int CFileAndroidApp::ReadIcon (unsigned char ** lpBuf, unsigned int * width, unsigned int * height) virtual
References CLog::Log(), LOGWARNING, m_icon, and m_packageName.
Referenced by CTexture::LoadFromFile().
Seek()
int64_t XFILE::CFileAndroidApp::Seek (int64_t , int) inline override virtual
Implements XFILE::IFile.
Stat()
int CFileAndroidApp::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
Member Data Documentation
m_icon
int XFILE::CFileAndroidApp::m_icon private
Referenced by Open(), and ReadIcon().
m_iconHeight
int XFILE::CFileAndroidApp::m_iconHeight private
Referenced by CFileAndroidApp().
m_iconWidth
int XFILE::CFileAndroidApp::m_iconWidth private
Referenced by CFileAndroidApp().
m_packageLabel
std::string XFILE::CFileAndroidApp::m_packageLabel private
Referenced by Open().
m_packageName
std::string XFILE::CFileAndroidApp::m_packageName private
Referenced by Open(), and ReadIcon().
m_url
CURL XFILE::CFileAndroidApp::m_url private
Referenced by Open().
The documentation for this class was generated from the following files:
AndroidAppFile.h
AndroidAppFile.cpp