Kodi Documentation: WsgiResponse
WsgiResponse
Python » Library - xbmcwsgi
Represents the start_response callable passed to a WSGI handler.
Classes
class XBMCAddon::xbmcwsgi::WsgiResponse
Functions
XBMCAddon::xbmcwsgi::WsgiResponse::WsgiResponse ()
XBMCAddon::xbmcwsgi::WsgiResponse::~WsgiResponse () override
XBMCAddon::xbmcwsgi::WsgiResponse::operator (...)
void XBMCAddon::xbmcwsgi::WsgiResponse::Append (const std::string &data)
bool XBMCAddon::xbmcwsgi::WsgiResponse::Finalize (HTTPPythonRequest *request) const
Variables
bool XBMCAddon::xbmcwsgi::WsgiResponse::m_called = false
int XBMCAddon::xbmcwsgi::WsgiResponse::m_status = MHD_HTTP_INTERNAL_SERVER_ERROR
std::multimap< std::string, std::string > XBMCAddon::xbmcwsgi::WsgiResponse::m_responseHeaders
WsgiResponseBody XBMCAddon::xbmcwsgi::WsgiResponse::m_body
Detailed Description
Represents the start_response callable passed to a WSGI handler.
Class: WsgiResponse()
Function Documentation
Append()
void XBMCAddon::xbmcwsgi::WsgiResponse::Append (const std::string & data)
References data(), and XBMCAddon::xbmcwsgi::WsgiResponse::m_body.
Referenced by CHTTPPythonWsgiInvoker::executeScript().
Finalize()
bool XBMCAddon::xbmcwsgi::WsgiResponse::Finalize (HTTPPythonRequest * request) const
References XBMCAddon::xbmcwsgi::WsgiResponse::m_body, XBMCAddon::xbmcwsgi::WsgiResponse::m_called, XBMCAddon::xbmcwsgi::WsgiResponse::m_responseHeaders, XBMCAddon::xbmcwsgi::WsgiResponse::m_status, HTTPPythonRequest::responseData, HTTPPythonRequest::responseHeaders, HTTPPythonRequest::responseHeadersError, and HTTPPythonRequest::responseStatus.
Referenced by CHTTPPythonWsgiInvoker::GetRequest().
operator()
XBMCAddon::xbmcwsgi::WsgiResponse::operator (...)
Function: operator(status, response_headers[, exc_info])
Callable implementation to initialize the response with the given HTTP status and the HTTP response headers.
Parameters
status an HTTP status string like 200 OK or 404 Not Found.
response_headers a list of (header_name, header_value) tuples. It must be a Python list. Each header_name must be a valid HTTP header field-name (as
exc_info [optional] python sys.exc_info() tuple. This argument should be supplied by the application only if start_response is being called by an error
Returns
The write() method WsgiResponseBody
WsgiResponse()
XBMCAddon::xbmcwsgi::WsgiResponse::WsgiResponse ()
~WsgiResponse()
XBMCAddon::xbmcwsgi::WsgiResponse::~WsgiResponse () override default
Variable Documentation
m_body
WsgiResponseBody XBMCAddon::xbmcwsgi::WsgiResponse::m_body private
Referenced by XBMCAddon::xbmcwsgi::WsgiResponse::Append(), and XBMCAddon::xbmcwsgi::WsgiResponse::Finalize().
m_called
bool XBMCAddon::xbmcwsgi::WsgiResponse::m_called = false private
Referenced by XBMCAddon::xbmcwsgi::WsgiResponse::Finalize().
m_responseHeaders
std::multimap<std::string, std::string> XBMCAddon::xbmcwsgi::WsgiResponse::m_responseHeaders private
Referenced by XBMCAddon::xbmcwsgi::WsgiResponse::Finalize().
m_status
int XBMCAddon::xbmcwsgi::WsgiResponse::m_status = MHD_HTTP_INTERNAL_SERVER_ERROR private
Referenced by XBMCAddon::xbmcwsgi::WsgiResponse::Finalize().