Kodi Documentation: ADDON::Interface_GUIDialogOK Struct Reference
ADDON::Interface_GUIDialogOK Struct Reference
Global gui Add-on to Kodi callback functions.
#include <OK.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void show_and_get_input_single_text (KODI_HANDLE kodiBase, const char *heading, const char *text)
callback functions from add-on to kodi
static void show_and_get_input_line_text (KODI_HANDLE kodiBase, const char *heading, const char *line0, const char *line1, const char *line2)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/dialogs/OK.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIDialogOK::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogOK, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
Init()
void ADDON::Interface_GUIDialogOK::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogOK, AddonToKodiFuncTable_Addon::kodi_gui, show_and_get_input_line_text(), AddonToKodiFuncTable_kodi_gui_dialogOK::show_and_get_input_line_text, show_and_get_input_single_text(), AddonToKodiFuncTable_kodi_gui_dialogOK::show_and_get_input_single_text, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
show_and_get_input_line_text()
void ADDON::Interface_GUIDialogOK::show_and_get_input_line_text (KODI_HANDLE kodiBase, const char * heading, const char * line0, const char * line1, const char * line2) static
References CLog::Log(), LOGERROR, and KODI::MESSAGING::HELPERS::ShowOKDialogLines().
Referenced by Init().
show_and_get_input_single_text()
void ADDON::Interface_GUIDialogOK::show_and_get_input_single_text (KODI_HANDLE kodiBase, const char * heading, const char * text) static
callback functions from add-on to kodi
Note
For add of new functions use the "_" style to identify direct a add-on callback function. Everything with CamelCase is only for the usage in Kodi only.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References CLog::Log(), LOGERROR, KODI::MESSAGING::HELPERS::ShowOKDialogText(), and text.
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/dialogs/ok.h
OK.cpp