Kodi Documentation: CSettingsValueFlatJsonSerializer Class Reference
CSettingsValueFlatJsonSerializer Class Reference
#include <SettingsValueFlatJsonSerializer.h>
Public Member Functions
CSettingsValueFlatJsonSerializer (bool compact=true)
~CSettingsValueFlatJsonSerializer ()=default
void SetCompact (bool compact=true)
std::string SerializeValues (const CSettingsManager *settingsManager) const override
Public Member Functions inherited from ISettingsValueSerializer
virtual ~ISettingsValueSerializer ()=default
Private Member Functions
void SerializeSection (CVariant &parent, const std::shared_ptr< CSettingSection > &section) const
void SerializeCategory (CVariant &parent, const std::shared_ptr< CSettingCategory > &category) const
void SerializeGroup (CVariant &parent, const std::shared_ptr< CSettingGroup > &group) const
void SerializeSetting (CVariant &parent, const std::shared_ptr< CSetting > &setting) const
CVariant SerializeSettingValue (const std::shared_ptr< CSetting > &setting) const
Private Attributes
bool m_compact
Constructor & Destructor Documentation
CSettingsValueFlatJsonSerializer()
CSettingsValueFlatJsonSerializer::CSettingsValueFlatJsonSerializer (bool compact = true) explicit
~CSettingsValueFlatJsonSerializer()
CSettingsValueFlatJsonSerializer::~CSettingsValueFlatJsonSerializer () default
Member Function Documentation
SerializeCategory()
void CSettingsValueFlatJsonSerializer::SerializeCategory (CVariant & parent, const std::shared_ptr< CSettingCategory > & category) const private
References SerializeGroup().
Referenced by SerializeSection().
SerializeGroup()
void CSettingsValueFlatJsonSerializer::SerializeGroup (CVariant & parent, const std::shared_ptr< CSettingGroup > & group) const private
References SerializeSetting().
Referenced by SerializeCategory().
SerializeSection()
void CSettingsValueFlatJsonSerializer::SerializeSection (CVariant & parent, const std::shared_ptr< CSettingSection > & section) const private
References SerializeCategory().
Referenced by SerializeValues().
SerializeSetting()
void CSettingsValueFlatJsonSerializer::SerializeSetting (CVariant & parent, const std::shared_ptr< CSetting > & setting) const private
References Action, and SerializeSettingValue().
Referenced by SerializeGroup().
SerializeSettingValue()
CVariant CSettingsValueFlatJsonSerializer::SerializeSettingValue (const std::shared_ptr< CSetting > & setting) const private
References Action, Boolean, CVariant::ConstNullVariant, GetValue(), Integer, List, CLog::Log(), LOGWARNING, Number, CVariant::push_back(), SerializeSettingValue(), String, Unknown, and CVariant::VariantTypeArray.
Referenced by SerializeSetting(), and SerializeSettingValue().
SerializeValues()
std::string CSettingsValueFlatJsonSerializer::SerializeValues (const CSettingsManager * settingsManager) const override virtual
Implements ISettingsValueSerializer.
References CSettingsManager::GetSections(), CLog::Log(), LOGWARNING, m_compact, root, SerializeSection(), CVariant::VariantTypeObject, and CJSONVariantWriter::Write().
Referenced by ADDON::CScraper::GetPathSettingsAsJSON().
SetCompact()
void CSettingsValueFlatJsonSerializer::SetCompact (bool compact = true) inline
References m_compact.
Member Data Documentation
m_compact
bool CSettingsValueFlatJsonSerializer::m_compact private
Referenced by SerializeValues(), and SetCompact().
The documentation for this class was generated from the following files:
SettingsValueFlatJsonSerializer.h
SettingsValueFlatJsonSerializer.cpp