Kodi Documentation: CImageMetadataParser Class Reference
CImageMetadataParser Class Reference
#include <ImageMetadataParser.h>
Public Member Functions
~CImageMetadataParser ()=default
Static Public Member Functions
static std::unique_ptr< ImageMetadata > ExtractMetadata (const std::string &picFileName)
Private Member Functions
CImageMetadataParser ()
void ExtractCommonMetadata (Exiv2::Image &image)
void ExtractExif (Exiv2::ExifData &exifData)
void ExtractIPTC (Exiv2::IptcData &iptcData)
Private Attributes
int m_imageWidth {0}
float m_focalPlaneXRes {0.0}
float m_focalPlaneUnits {0}
std::unique_ptr< ImageMetadata > m_imageMetadata
Constructor & Destructor Documentation
~CImageMetadataParser()
CImageMetadataParser::~CImageMetadataParser () default
CImageMetadataParser()
CImageMetadataParser::CImageMetadataParser () private
Member Function Documentation
ExtractCommonMetadata()
void CImageMetadataParser::ExtractCommonMetadata (Exiv2::Image & image) private
TODO: all these elements are generic should be moved out of the exif struct
References m_imageMetadata.
ExtractExif()
void CImageMetadataParser::ExtractExif (Exiv2::ExifData & exifData) private
References log(), LOGWARNING, m_focalPlaneUnits, m_focalPlaneXRes, m_imageMetadata, m_imageWidth, and value.
ExtractIPTC()
void CImageMetadataParser::ExtractIPTC (Exiv2::IptcData & iptcData) private
References m_imageMetadata.
ExtractMetadata()
std::unique_ptr< ImageMetadata > CImageMetadataParser::ExtractMetadata (const std::string & picFileName) static
References XFILE::CFile::LoadFile().
Referenced by CPictureInfoTag::Load(), TEST_F(), and TEST_F().
Member Data Documentation
m_focalPlaneUnits
float CImageMetadataParser::m_focalPlaneUnits {0} private
Referenced by ExtractExif().
m_focalPlaneXRes
float CImageMetadataParser::m_focalPlaneXRes {0.0} private
Referenced by ExtractExif().
m_imageMetadata
std::unique_ptr<ImageMetadata> CImageMetadataParser::m_imageMetadata private
Referenced by ExtractCommonMetadata(), ExtractExif(), and ExtractIPTC().
m_imageWidth
int CImageMetadataParser::m_imageWidth {0} private
Referenced by ExtractExif().
The documentation for this class was generated from the following files:
ImageMetadataParser.h
ImageMetadataParser.cpp