Kodi Documentation: CCharsetConverter Class Reference
CCharsetConverter Class Reference
#include <CharsetConverter.h>
Classes
class CInnerConverter
Public Member Functions
CCharsetConverter ()
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Static Public Member Functions
static void reset ()
static void resetSystemCharset ()
static void reinitCharsetsFromSettings (void)
static void clear ()
static bool utf8ToUtf32 (const std::string &utf8StringSrc, std::u32string &utf32StringDst, bool failOnBadChar=true)
static std::u32string utf8ToUtf32 (const std::string &utf8StringSrc, bool failOnBadChar=true)
static bool utf8ToUtf32Visual (const std::string &utf8StringSrc, std::u32string &utf32StringDst, bool bVisualBiDiFlip=false, bool forceLTRReadingOrder=false, bool failOnBadChar=false)
static bool utf32ToUtf8 (const std::u32string &utf32StringSrc, std::string &utf8StringDst, bool failOnBadChar=false)
static std::string utf32ToUtf8 (const std::u32string &utf32StringSrc, bool failOnBadChar=false)
static bool utf32ToW (const std::u32string &utf32StringSrc, std::wstring &wStringDst, bool failOnBadChar=false)
static bool utf32logicalToVisualBiDi (const std::u32string &logicalStringSrc, std::u32string &visualStringDst, bool forceLTRReadingOrder=false, bool failOnBadString=false, int *visualToLogicalMap=nullptr)
static bool wToUtf32 (const std::wstring &wStringSrc, std::u32string &utf32StringDst, bool failOnBadChar=false)
static bool utf8ToW (const std::string &utf8StringSrc, std::wstring &wStringDst, bool bVisualBiDiFlip=true, bool forceLTRReadingOrder=false, bool failOnBadChar=false)
static bool utf16LEtoW (const std::u16string &utf16String, std::wstring &wString)
static bool subtitleCharsetToUtf8 (const std::string &stringSrc, std::string &utf8StringDst)
static bool utf8ToStringCharset (const std::string &utf8StringSrc, std::string &stringDst)
static bool utf8ToStringCharset (std::string &stringSrcDst)
static bool utf8ToSystem (std::string &stringSrcDst, bool failOnBadChar=false)
static bool systemToUtf8 (const std::string &sysStringSrc, std::string &utf8StringDst, bool failOnBadChar=false)
static bool utf8To (const std::string &strDestCharset, const std::string &utf8StringSrc, std::string &stringDst)
static bool utf8To (const std::string &strDestCharset, const std::string &utf8StringSrc, std::u16string &utf16StringDst)
static bool utf8To (const std::string &strDestCharset, const std::string &utf8StringSrc, std::u32string &utf32StringDst)
static bool ToUtf8 (const std::string &strSourceCharset, const std::string &stringSrc, std::string &utf8StringDst, bool failOnBadChar=false)
static bool wToUTF8 (const std::wstring &wStringSrc, std::string &utf8StringDst, bool failOnBadChar=false)
static bool utf16BEtoUTF8 (const std::u16string &utf16StringSrc, std::string &utf8StringDst)
Convert UTF-16BE (u16string) string to UTF-8 string. No RTL visual-logical transformation is performed.
static bool utf16BEtoUTF8 (const std::string &utf16StringSrc, std::string &utf8StringDst)
Convert UTF-16BE (string) string to UTF-8 string. No RTL visual-logical transformation is performed.
static bool utf16LEtoUTF8 (const std::u16string &utf16StringSrc, std::string &utf8StringDst)
static bool ucs2ToUTF8 (const std::u16string &ucs2StringSrc, std::string &utf8StringDst)
static bool MacintoshToUTF8 (const std::string &macStringSrc, std::string &utf8StringDst)
Convert Macintosh (string) string to UTF-8 string. No RTL visual-logical transformation is performed.
static bool utf8logicalToVisualBiDi (const std::string &utf8StringSrc, std::string &utf8StringDst, bool failOnBadString=false)
static bool utf8IsRTLBidiDirection (const std::string &utf8String)
static bool utf32ToStringCharset (const std::u32string &utf32StringSrc, std::string &stringDst)
static std::vector< std::string > getCharsetLabels ()
static std::string getCharsetLabelByName (const std::string &charsetName)
static std::string getCharsetNameByLabel (const std::string &charsetLabel)
static bool unknownToUTF8 (std::string &stringSrcDst)
static bool unknownToUTF8 (const std::string &stringSrc, std::string &utf8StringDst, bool failOnBadChar=false)
static bool toW (const std::string &stringSrc, std::wstring &wStringDst, const std::string &enc)
static bool fromW (const std::wstring &wStringSrc, std::string &stringDst, const std::string &enc)
static void SettingOptionsCharsetsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
Static Private Member Functions
static void resetUserCharset (void)
static void resetSubtitleCharset (void)
Static Private Attributes
static const int m_Utf8CharMinSize = 1
static const int m_Utf8CharMaxSize = 4
Constructor & Destructor Documentation
CCharsetConverter()
CCharsetConverter::CCharsetConverter () default
Member Function Documentation
clear()
void CCharsetConverter::clear () static
fromW()
bool CCharsetConverter::fromW (const std::wstring & wStringSrc, std::string & stringDst, const std::string & enc) static
References CCharsetConverter::CInnerConverter::customConvert(), and WCHAR_CHARSET.
getCharsetLabelByName()
std::string CCharsetConverter::getCharsetLabelByName (const std::string & charsetName) static
References SCharsetMapping::charset, and g_charsets.
getCharsetLabels()
std::vector< std::string > CCharsetConverter::getCharsetLabels () static
References SCharsetMapping::charset, and g_charsets.
getCharsetNameByLabel()
std::string CCharsetConverter::getCharsetNameByLabel (const std::string & charsetLabel) static
References SCharsetMapping::charset, and g_charsets.
MacintoshToUTF8()
bool CCharsetConverter::MacintoshToUTF8 (const std::string & macStringSrc, std::string & utf8StringDst) static
Convert Macintosh (string) string to UTF-8 string. No RTL visual-logical transformation is performed.
Parameters
macStringSrc Is source Macintosh string to convert
utf8StringDst Is output UTF-8 string, empty on any error
Returns
True on successful conversion, false on any error
References MacintoshToUtf8, and CCharsetConverter::CInnerConverter::stdConvert().
Referenced by KODI::UTILS::FONT::anonymous_namespace{FontUtils.cpp}::GetFamilyNameFromSfnt().
OnSettingChanged()
void CCharsetConverter::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References resetSubtitleCharset(), resetUserCharset(), CSettings::SETTING_LOCALE_CHARSET, and CSettings::SETTING_SUBTITLES_CHARSET.
reinitCharsetsFromSettings()
void CCharsetConverter::reinitCharsetsFromSettings (void) static
References resetUserCharset().
reset()
void CCharsetConverter::reset (void) static
References CCharsetConverter::CInnerConverter::m_stdConversion.
resetSubtitleCharset()
void CCharsetConverter::resetSubtitleCharset (void) static private
References CCharsetConverter::CInnerConverter::m_stdConversion, CConverterType::Reset(), and SubtitleCharsetToUtf8.
Referenced by OnSettingChanged(), and resetUserCharset().
resetSystemCharset()
void CCharsetConverter::resetSystemCharset (void) static
References CCharsetConverter::CInnerConverter::m_stdConversion, CConverterType::Reset(), SystemToUtf8, and Utf8ToSystem.
resetUserCharset()
void CCharsetConverter::resetUserCharset (void) static private
References CCharsetConverter::CInnerConverter::m_stdConversion, CConverterType::Reset(), resetSubtitleCharset(), UserCharsetToUtf8, and Utf32ToUserCharset.
Referenced by OnSettingChanged(), and reinitCharsetsFromSettings().
SettingOptionsCharsetsFiller()
void CCharsetConverter::SettingOptionsCharsetsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References g_charsetConverter, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
subtitleCharsetToUtf8()
bool CCharsetConverter::subtitleCharsetToUtf8 (const std::string & stringSrc, std::string & utf8StringDst) static
References CCharsetConverter::CInnerConverter::stdConvert(), and SubtitleCharsetToUtf8.
systemToUtf8()
bool CCharsetConverter::systemToUtf8 (const std::string & sysStringSrc, std::string & utf8StringDst, bool failOnBadChar = false) static
References CCharsetConverter::CInnerConverter::stdConvert(), and SystemToUtf8.
ToUtf8()
bool CCharsetConverter::ToUtf8 (const std::string & strSourceCharset, const std::string & stringSrc, std::string & utf8StringDst, bool failOnBadChar = false) static
References CCharsetConverter::CInnerConverter::customConvert().
toW()
bool CCharsetConverter::toW (const std::string & stringSrc, std::wstring & wStringDst, const std::string & enc) static
References CCharsetConverter::CInnerConverter::customConvert(), and WCHAR_CHARSET.
ucs2ToUTF8()
bool CCharsetConverter::ucs2ToUTF8 (const std::u16string & ucs2StringSrc, std::string & utf8StringDst) static
References CCharsetConverter::CInnerConverter::stdConvert(), and Ucs2CharsetToUtf8.
unknownToUTF8() [1/2]
bool CCharsetConverter::unknownToUTF8 (const std::string & stringSrc, std::string & utf8StringDst, bool failOnBadChar = false) static
References CUtf8Utils::isValidUtf8(), CCharsetConverter::CInnerConverter::stdConvert(), and UserCharsetToUtf8.
unknownToUTF8() [2/2]
bool CCharsetConverter::unknownToUTF8 (std::string & stringSrcDst) static
References unknownToUTF8().
Referenced by XFILE::CPosixDirectory::GetDirectory(), XFILE::CPosixDirectory::RemoveRecursive(), and unknownToUTF8().
utf16BEtoUTF8() [1/2]
bool CCharsetConverter::utf16BEtoUTF8 (const std::string & utf16StringSrc, std::string & utf8StringDst) static
Convert UTF-16BE (string) string to UTF-8 string. No RTL visual-logical transformation is performed.
Parameters
utf16StringSrc Is source UTF-16BE string to convert
utf8StringDst Is output UTF-8 string, empty on any error
Returns
True on successful conversion, false on any error
References CCharsetConverter::CInnerConverter::stdConvert(), and Utf16BEtoUtf8.
utf16BEtoUTF8() [2/2]
bool CCharsetConverter::utf16BEtoUTF8 (const std::u16string & utf16StringSrc, std::string & utf8StringDst) static
Convert UTF-16BE (u16string) string to UTF-8 string. No RTL visual-logical transformation is performed.
Parameters
utf16StringSrc Is source UTF-16BE u16string string to convert
utf8StringDst Is output UTF-8 string, empty on any error
Returns
True on successful conversion, false on any error
References CCharsetConverter::CInnerConverter::stdConvert(), and Utf16BEtoUtf8.
Referenced by KODI::UTILS::FONT::anonymous_namespace{FontUtils.cpp}::GetFamilyNameFromSfnt().
utf16LEtoUTF8()
bool CCharsetConverter::utf16LEtoUTF8 (const std::u16string & utf16StringSrc, std::string & utf8StringDst) static
References CCharsetConverter::CInnerConverter::stdConvert(), and Utf16LEtoUtf8.
utf16LEtoW()
bool CCharsetConverter::utf16LEtoW (const std::u16string & utf16String, std::wstring & wString) static
References CCharsetConverter::CInnerConverter::stdConvert(), and Utf16LEtoW.
utf32logicalToVisualBiDi()
bool CCharsetConverter::utf32logicalToVisualBiDi (const std::u32string & logicalStringSrc, std::u32string & visualStringDst, bool forceLTRReadingOrder = false, bool failOnBadString = false, int * visualToLogicalMap = nullptr) static
Perform logical to visual flip.
Parameters
logicalStringSrc is source string with logical characters order
visualStringDst is output string with visual characters order, empty on any error
forceLTRReadingOrder force LTR reading order
visualToLogicalMap is output mapping of positions in the visual string to the logical string
Returns
true on success, false otherwise
References CCharsetConverter::CInnerConverter::logicalToVisualBiDi().
utf32ToStringCharset()
bool CCharsetConverter::utf32ToStringCharset (const std::u32string & utf32StringSrc, std::string & stringDst) static
References CCharsetConverter::CInnerConverter::stdConvert(), and Utf32ToUserCharset.
utf32ToUtf8() [1/2]
std::string CCharsetConverter::utf32ToUtf8 (const std::u32string & utf32StringSrc, bool failOnBadChar = false) static
Convert UTF-32 string to UTF-8 string. No RTL visual-logical transformation is performed.
Parameters
utf32StringSrc is source UTF-32 string to convert
failOnBadChar if set to true function will fail on invalid character, otherwise invalid character will be skipped
Returns
converted string on successful conversion, empty string on any error
References utf32ToUtf8().
utf32ToUtf8() [2/2]
bool CCharsetConverter::utf32ToUtf8 (const std::u32string & utf32StringSrc, std::string & utf8StringDst, bool failOnBadChar = false) static
Convert UTF-32 string to UTF-8 string. No RTL visual-logical transformation is performed.
Parameters
utf32StringSrc is source UTF-32 string to convert
utf8StringDst is output UTF-8 string, empty on any error
failOnBadChar if set to true function will fail on invalid character, otherwise invalid character will be skipped
Returns
true on successful conversion, false on any error
References CCharsetConverter::CInnerConverter::stdConvert(), and Utf32ToUtf8.
Referenced by utf32ToUtf8().
utf32ToW()
bool CCharsetConverter::utf32ToW (const std::u32string & utf32StringSrc, std::wstring & wStringDst, bool failOnBadChar = false) static
Convert UTF-32 string to wchar_t string (wstring). No RTL visual-logical transformation is performed.
Parameters
utf32StringSrc is source UTF-32 string to convert
wStringDst is output wchar_t string, empty on any error
failOnBadChar if set to true function will fail on invalid character, otherwise invalid character will be skipped
Returns
true on successful conversion, false on any error
References CCharsetConverter::CInnerConverter::stdConvert(), and Utf32ToW.
utf8IsRTLBidiDirection()
bool CCharsetConverter::utf8IsRTLBidiDirection (const std::string & utf8String) static
Check if a string has RTL direction.
Parameters
utf8StringSrc the string
Returns
true if the string is RTL, otherwise false
References CCharsetConverter::CInnerConverter::isBidiDirectionRTL().
Referenced by CWebVTTHandler::CalculateTextPosition().
utf8logicalToVisualBiDi()
bool CCharsetConverter::utf8logicalToVisualBiDi (const std::string & utf8StringSrc, std::string & utf8StringDst, bool failOnBadString = false) static
References CCharsetConverter::CInnerConverter::stdConvert(), Utf32ToUtf8, and utf8ToUtf32Visual().
utf8To() [1/3]
bool CCharsetConverter::utf8To (const std::string & strDestCharset, const std::string & utf8StringSrc, std::string & stringDst) static
References CCharsetConverter::CInnerConverter::customConvert(), and UTF8_SOURCE.
utf8To() [2/3]
bool CCharsetConverter::utf8To (const std::string & strDestCharset, const std::string & utf8StringSrc, std::u16string & utf16StringDst) static
References CCharsetConverter::CInnerConverter::customConvert(), and UTF8_SOURCE.
utf8To() [3/3]
bool CCharsetConverter::utf8To (const std::string & strDestCharset, const std::string & utf8StringSrc, std::u32string & utf32StringDst) static
References CCharsetConverter::CInnerConverter::customConvert(), and UTF8_SOURCE.
utf8ToStringCharset() [1/2]
bool CCharsetConverter::utf8ToStringCharset (const std::string & utf8StringSrc, std::string & stringDst) static
References CCharsetConverter::CInnerConverter::stdConvert(), and Utf8ToUserCharset.
Referenced by utf8ToStringCharset().
utf8ToStringCharset() [2/2]
bool CCharsetConverter::utf8ToStringCharset (std::string & stringSrcDst) static
References utf8ToStringCharset().
utf8ToSystem()
bool CCharsetConverter::utf8ToSystem (std::string & stringSrcDst, bool failOnBadChar = false) static
References CCharsetConverter::CInnerConverter::stdConvert(), and Utf8ToSystem.
utf8ToUtf32() [1/2]
std::u32string CCharsetConverter::utf8ToUtf32 (const std::string & utf8StringSrc, bool failOnBadChar = true) static
Convert UTF-8 string to UTF-32 string. No RTL logical-visual transformation is performed.
Parameters
utf8StringSrc is source UTF-8 string to convert
failOnBadChar if set to true function will fail on invalid character, otherwise invalid character will be skipped
Returns
converted string on successful conversion, empty string on any error
References utf8ToUtf32().
utf8ToUtf32() [2/2]
bool CCharsetConverter::utf8ToUtf32 (const std::string & utf8StringSrc, std::u32string & utf32StringDst, bool failOnBadChar = true) static
Convert UTF-8 string to UTF-32 string. No RTL logical-visual transformation is performed.
Parameters
utf8StringSrc is source UTF-8 string to convert
utf32StringDst is output UTF-32 string, empty on any error
failOnBadChar if set to true function will fail on invalid character, otherwise invalid character will be skipped
Returns
true on successful conversion, false on any error
References CCharsetConverter::CInnerConverter::stdConvert(), and Utf8ToUtf32.
Referenced by utf8ToUtf32().
utf8ToUtf32Visual()
bool CCharsetConverter::utf8ToUtf32Visual (const std::string & utf8StringSrc, std::u32string & utf32StringDst, bool bVisualBiDiFlip = false, bool forceLTRReadingOrder = false, bool failOnBadChar = false) static
Convert UTF-8 string to UTF-32 string. RTL logical-visual transformation is optionally performed. Use it for readable text, GUI strings etc.
Parameters
utf8StringSrc is source UTF-8 string to convert
utf32StringDst is output UTF-32 string, empty on any error
bVisualBiDiFlip allow RTL visual-logical transformation if set to true, must be set to false is logical-visual transformation is already done
forceLTRReadingOrder force LTR reading order
failOnBadChar if set to true function will fail on invalid character, otherwise invalid character will be skipped
Returns
true on successful conversion, false on any error
References CCharsetConverter::CInnerConverter::logicalToVisualBiDi(), CCharsetConverter::CInnerConverter::stdConvert(), and Utf8ToUtf32.
Referenced by utf8logicalToVisualBiDi().
utf8ToW()
bool CCharsetConverter::utf8ToW (const std::string & utf8StringSrc, std::wstring & wStringDst, bool bVisualBiDiFlip = true, bool forceLTRReadingOrder = false, bool failOnBadChar = false) static
References CCharsetConverter::CInnerConverter::logicalToVisualBiDi(), CCharsetConverter::CInnerConverter::stdConvert(), Utf32ToW, Utf8ToUtf32, and Utf8toW.
Referenced by XBPython::OnScriptInitialized().
wToUtf32()
bool CCharsetConverter::wToUtf32 (const std::wstring & wStringSrc, std::u32string & utf32StringDst, bool failOnBadChar = false) static
Strictly convert wchar_t string (wstring) to UTF-32 string. No RTL visual-logical transformation is performed.
Parameters
wStringSrc is source wchar_t string to convert
utf32StringDst is output UTF-32 string, empty on any error
failOnBadChar if set to true function will fail on invalid character, otherwise invalid character will be skipped
Returns
true on successful conversion, false on any error
References CCharsetConverter::CInnerConverter::stdConvert(), and WToUtf32.
wToUTF8()
bool CCharsetConverter::wToUTF8 (const std::wstring & wStringSrc, std::string & utf8StringDst, bool failOnBadChar = false) static
References CCharsetConverter::CInnerConverter::stdConvert(), and WtoUtf8.
Member Data Documentation
m_Utf8CharMaxSize
const int CCharsetConverter::m_Utf8CharMaxSize = 4 static private
Referenced by CCharsetConverter::CInnerConverter::customConvert().
m_Utf8CharMinSize
const int CCharsetConverter::m_Utf8CharMinSize = 1 static private
The documentation for this class was generated from the following files:
utils/CharsetConverter.h
utils/CharsetConverter.cpp