Kodi Documentation: CTempFile Class Reference
CTempFile Class Reference
Public Member Functions
CTempFile ()=default
~CTempFile ()
bool Create (const std::string &suffix)
bool Delete ()
const std::string & getTempFilePath () const
std::string getTempFileDirectory () const
Public Member Functions inherited from XFILE::CFile
CFile ()
~CFile ()
bool CURLCreate (const std::string &url)
bool CURLAddOption (XFILE::CURLOPTIONTYPE type, const char *name, const char *value)
bool CURLOpen (unsigned int flags)
bool Open (const CURL &file, const unsigned int flags=0)
bool Open (const std::string &strFileName, const unsigned int flags=0)
bool OpenForWrite (const CURL &file, bool bOverWrite=false)
bool OpenForWrite (const std::string &strFileName, bool bOverWrite=false)
ssize_t LoadFile (const CURL &file, std::vector< uint8_t > &outputBuffer)
ssize_t Read (void *bufPtr, size_t bufSize)
bool ReadString (std::vector< char > &line)
String reading by line.
bool ReadString (char *szLine, int iLineLength)
ssize_t Write (const void *bufPtr, size_t bufSize)
void Flush ()
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET)
int Truncate (int64_t iSize)
int64_t GetPosition () const
int64_t GetLength ()
void Close ()
int GetChunkSize ()
const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
ssize_t LoadFile (const std::string &filename, std::vector< uint8_t > &outputBuffer)
const std::unique_ptr< BitstreamStats > & GetBitstreamStats () const
int IoControl (EIoControl request, void *param)
IFile * GetImplementation () const
int Stat (struct __stat64 *buffer)
double GetDownloadSpeed ()
Private Attributes
std::string m_ptempFilePath
Additional Inherited Members
Static Public Member Functions inherited from XFILE::CFile
static int DetermineChunkSize (const int srcChunkSize, const int reqChunkSize)
static bool Exists (const CURL &file, bool bUseCache=true)
static bool Delete (const CURL &file)
static int Stat (const CURL &file, struct __stat64 *buffer)
static bool Rename (const CURL &file, const CURL &urlNew)
static bool Copy (const CURL &file, const CURL &dest, XFILE::IFileCallback *pCallback=NULL, void *pContext=NULL)
static bool SetHidden (const CURL &file, bool hidden)
static bool Exists (const std::string &strFileName, bool bUseCache=true)
static int Stat (const std::string &strFileName, struct __stat64 *buffer)
static bool Delete (const std::string &strFileName)
static bool Rename (const std::string &strFileName, const std::string &strNewFileName)
static bool Copy (const std::string &strFileName, const std::string &strDest, XFILE::IFileCallback *pCallback=NULL, void *pContext=NULL)
static bool SetHidden (const std::string &fileName, bool hidden)
Constructor & Destructor Documentation
CTempFile()
CTempFile::CTempFile () default
~CTempFile()
CTempFile::~CTempFile () inline
References Delete().
Member Function Documentation
Create()
bool CTempFile::Create (const std::string & suffix) inline
References m_ptempFilePath, XFILE::CFile::OpenForWrite(), and KODI::PLATFORM::FILESYSTEM::temp_file_path().
Delete()
bool CTempFile::Delete () inline
References XFILE::CFile::Close(), and m_ptempFilePath.
Referenced by CXBMCTestUtils::DeleteTempFile(), and ~CTempFile().
getTempFileDirectory()
std::string CTempFile::getTempFileDirectory () const inline
References URIUtils::GetDirectory(), and m_ptempFilePath.
Referenced by CXBMCTestUtils::TempFileDirectory().
getTempFilePath()
const std::string & CTempFile::getTempFilePath () const inline
References m_ptempFilePath.
Referenced by CXBMCTestUtils::TempFilePath().
Member Data Documentation
m_ptempFilePath
std::string CTempFile::m_ptempFilePath private
Referenced by Create(), Delete(), getTempFileDirectory(), and getTempFilePath().
The documentation for this class was generated from the following file:
TestUtils.cpp