Kodi Documentation: XSLTUtils Class Reference
XSLTUtils Class Reference
#include <XSLTUtils.h>
Public Member Functions
XSLTUtils ()
~XSLTUtils ()
bool SetInput (const std::string &input)
Set the input XML for an XSLT transform from a string. This sets up the XSLT transformer with some input XML from a string in memory. The input XML should be well formed.
bool SetStylesheet (const std::string &stylesheet)
Set the stylesheet (XSL) for an XSLT transform from a string. This sets up the XSLT transformer with some stylesheet XML from a string in memory. The input XSL should be well formed.
bool XSLTTransform (std::string &output)
Perform an XSLT transform on an inbound XML document. This will apply an XSLT transformation on an input XML document, giving an output XML document, using the specified XSLT document as the transformer.
Private Attributes
xmlDocPtr m_xmlInput = nullptr
xmlDocPtr m_xmlOutput = nullptr
xmlDocPtr m_xmlStylesheet = nullptr
xsltStylesheetPtr m_xsltStylesheet = nullptr
Constructor & Destructor Documentation
XSLTUtils()
XSLTUtils::XSLTUtils ()
References err().
~XSLTUtils()
XSLTUtils::~XSLTUtils ()
References m_xmlInput, m_xmlOutput, and m_xsltStylesheet.
Member Function Documentation
SetInput()
bool XSLTUtils::SetInput (const std::string & input)
Set the input XML for an XSLT transform from a string. This sets up the XSLT transformer with some input XML from a string in memory. The input XML should be well formed.
Parameters
input the XML document to be transformed.
References m_xmlInput.
Referenced by CScraperParser::ParseXSLT().
SetStylesheet()
bool XSLTUtils::SetStylesheet (const std::string & stylesheet)
Set the stylesheet (XSL) for an XSLT transform from a string. This sets up the XSLT transformer with some stylesheet XML from a string in memory. The input XSL should be well formed.
Parameters
input the XSL document to be transformed.
References CLog::Log(), LOGDEBUG, m_xmlStylesheet, and m_xsltStylesheet.
Referenced by CScraperParser::ParseXSLT().
XSLTTransform()
bool XSLTUtils::XSLTTransform (std::string & output)
Perform an XSLT transform on an inbound XML document. This will apply an XSLT transformation on an input XML document, giving an output XML document, using the specified XSLT document as the transformer.
Parameters
input the parent containing the <tag>'s.
filename the <tag> in question.
References CLog::Log(), LOGDEBUG, m_xmlInput, m_xmlOutput, and m_xsltStylesheet.
Referenced by CScraperParser::ParseXSLT().
Member Data Documentation
m_xmlInput
xmlDocPtr XSLTUtils::m_xmlInput = nullptr private
Referenced by SetInput(), XSLTTransform(), and ~XSLTUtils().
m_xmlOutput
xmlDocPtr XSLTUtils::m_xmlOutput = nullptr private
Referenced by XSLTTransform(), and ~XSLTUtils().
m_xmlStylesheet
xmlDocPtr XSLTUtils::m_xmlStylesheet = nullptr private
Referenced by SetStylesheet().
m_xsltStylesheet
xsltStylesheetPtr XSLTUtils::m_xsltStylesheet = nullptr private
Referenced by SetStylesheet(), XSLTTransform(), and ~XSLTUtils().
The documentation for this class was generated from the following files:
XSLTUtils.h
XSLTUtils.cpp