Kodi Documentation: CUtil Class Reference
CUtil Class Reference
#include <Util.h>
Static Public Member Functions
static void CleanString (const std::string &strFileName, std::string &strTitle, std::string &strTitleAndYear, std::string &strYear, bool bRemoveExtension=false, bool bCleanChars=true)
static bool GetFilenameIdentifier (const std::string &fileName, std::string &identifierType, std::string &identifier)
static bool GetFilenameIdentifier (const std::string &fileName, std::string &identifierType, std::string &identifier, std::string &match)
static bool HasFilenameIdentifier (const std::string &fileName)
static std::string GetTitleFromPath (const CURL &url, bool bIsFolder=false)
static std::string GetTitleFromPath (const std::string &strFileNameAndPath, bool bIsFolder=false)
static std::string GetDiscNumberFromPath (const std::string &path)
Return the disc number in case the last segment of given path ends with 'Disc n'. Will look for 'Disc', 'Disk' and the locale specific spelling.
static std::string RemoveTrailingDiscNumberSegmentFromPath (std::string path)
Remove last segment of the given path if it matches 'Disc n'. Will look for 'Disc', 'Disk' and the locale specific spelling.
static void GetQualifiedFilename (const std::string &strBasePath, std::string &strFilename)
static void RunShortcut (const char *szPath)
static std::string GetHomePath (const std::string &strTarget="KODI_HOME")
static bool ExcludeFileOrFolder (const std::string &strFileOrFolder, const std::vector< std::string > &regexps)
static void GetFileAndProtocol (const std::string &strURL, std::string &strDir)
static int GetDVDIfoTitle (const std::string &strPathFile)
static bool IsPicture (const std::string &strFile)
static std::string GetSplashPath ()
Get resolved filesystem location of splash image.
static std::string GetFileDigest (const std::string &strPath, KODI::UTILITY::CDigest::Type type)
retrieve MD5sum of a file
static bool GetDirectoryName (const std::string &strFileName, std::string &strDescription)
static void GetDVDDriveIcon (const std::string &strPath, std::string &strIcon)
static void RemoveTempFiles ()
static void ClearSubtitles ()
static void ScanForExternalSubtitles (const std::string &strMovie, std::vector< std::string > &vecSubtitles)
static ExternalStreamInfo GetExternalStreamDetailsFromFilename (const std::string &videoPath, const std::string &associatedFile)
Retrieves stream info of external associated files, e.g., subtitles, for a given video.
static bool FindVobSubPair (const std::vector< std::string > &vecSubtitles, const std::string &strIdxPath, std::string &strSubPath)
in a vector of subtitles finds the corresponding .sub file for a given .idx file
static bool IsVobSub (const std::vector< std::string > &vecSubtitles, const std::string &strSubPath)
checks if in the vector of subtitles the given .sub file has a corresponding idx and hence is a vobsub file
static std::string GetVobSubSubFromIdx (const std::string &vobSubIdx)
find a plain or archived vobsub .sub file corresponding to an .idx file
static std::string GetVobSubIdxFromSub (const std::string &vobSub)
find a .idx file from a path of a plain or archived vobsub .sub file
static void ScanForExternalAudio (const std::string &videoPath, std::vector< std::string > &vecAudio)
Retrieves paths of external audio files for a given video.
static int64_t ToInt64 (uint32_t high, uint32_t low)
static std::string GetNextFilename (const std::string &fn_template, int max)
Finds next unused filename that matches padded int format identifier provided.
static std::string GetNextPathname (const std::string &path_template, int max)
static void StatToStatI64 (struct _stati64 *result, struct stat *stat)
static void StatToStat64 (struct __stat64 *result, const struct stat *stat)
static void Stat64ToStatI64 (struct _stati64 *result, struct __stat64 *stat)
static void StatI64ToStat64 (struct __stat64 *result, struct _stati64 *stat)
static void Stat64ToStat (struct stat *result, struct __stat64 *stat)
static bool CreateDirectoryEx (const std::string &strPath)
static std::string MakeLegalFileName (std::string strFile, int LegalType=LEGAL_NONE)
static std::string MakeLegalPath (std::string strPath, int LegalType=LEGAL_NONE)
static std::string ValidatePath (std::string path, bool bFixDoubleSlashes=false)
return a validated path, with correct directory separators.
static bool IsSupportedFontExtension (const std::string &fileName)
Check if a filename contains a supported font extension.
static void SplitParams (const std::string &paramString, std::vector< std::string > &parameters)
Split a comma separated parameter list into separate parameters. Takes care of the case where we may have a quoted string containing commas, or we may have a function (i.e. parentheses) with multiple parameters as a single parameter.
static int GetMatchingSource (const std::string &strPath, std::vector< CMediaSource > &sources, bool &bIsSourceName)
static std::string TranslateSpecialSource (const std::string &strSpecial)
static void DeleteDirectoryCache (const std::string &prefix="")
static void DeleteMusicDatabaseDirectoryCache ()
static void DeleteVideoDatabaseDirectoryCache ()
static std::string MusicPlaylistsLocation ()
static std::string VideoPlaylistsLocation ()
static void GetSkinThemes (std::vector< std::string > &vecTheme)
static void GetRecursiveListing (const std::string &strPath, CFileItemList &items, const std::string &strMask, unsigned int flags=0)
static void GetRecursiveDirsListing (const std::string &strPath, CFileItemList &items, unsigned int flags=0)
static void ForceForwardSlashes (std::string &strPath)
static double AlbumRelevance (const std::string &strAlbumTemp1, const std::string &strAlbum1, const std::string &strArtistTemp1, const std::string &strArtist1)
static bool MakeShortenPath (std::string StrInput, std::string &StrOutput, size_t iTextMaxLength)
static bool SupportsWriteFileOperations (const std::string &strPath)
Checks whether the supplied path supports Write file operations (e.g. Rename, Delete, ...)
static bool SupportsReadFileOperations (const std::string &strPath)
Checks whether the supplied path supports Read file operations (e.g. Copy, ...)
static std::string GetDefaultFolderThumb (const std::string &folderThumb)
static void InitRandomSeed ()
static int LookupRomanDigit (char roman_digit)
static int TranslateRomanNumeral (const char *roman_numeral)
static std::string ResolveExecutablePath ()
static std::string GetFrameworksPath (bool forPython=false)
static bool CanBindPrivileged ()
static bool ValidatePort (int port)
static int GetRandomNumber ()
Thread-safe random number generation.
static int64_t ConvertSecsToMilliSecs (double secs)
static double ConvertMilliSecsToSecs (int64_t offset)
static int64_t ConvertMilliSecsToSecsInt (int64_t offset)
static int64_t ConvertMilliSecsToSecsIntRounded (int64_t offset)
static void CopyUserDataIfNeeded (const std::string &strPath, const std::string &file, const std::string &destname="")
Copy files from the application bundle over to the user data directory in Application Support/Kodi.
Static Protected Member Functions
static void GetVideoBasePathAndFileName (const std::string &videoPath, std::string &basePath, std::string &videoFileName)
Retrieves the base path and the filename of a given video.
static void GetItemsToScan (const std::string &videoPath, const std::string &item_exts, const std::vector< std::string > &sub_dirs, CFileItemList &items)
Retrieves FileItems that could contain associated files of a given video.
static void ScanPathsForAssociatedItems (const std::string &videoName, const CFileItemList &items, const std::vector< std::string > &item_exts, std::vector< std::string > &associatedFiles)
Searches for associated files of a given video.
static int ScanArchiveForAssociatedItems (const std::string &strArchivePath, const std::string &videoNameNoExt, const std::vector< std::string > &item_exts, std::vector< std::string > &associatedFiles)
Searches in an archive for associated files of a given video.
Private Member Functions
CUtil ()=delete
Static Private Attributes
static unsigned int s_randomSeed = time(NULL)
Constructor & Destructor Documentation
CUtil()
CUtil::CUtil () private delete
Member Function Documentation
AlbumRelevance()
double CUtil::AlbumRelevance (const std::string & strAlbumTemp1, const std::string & strAlbum1, const std::string & strArtistTemp1, const std::string & strArtist1) static
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo().
CanBindPrivileged()
bool CUtil::CanBindPrivileged () static
References value.
Referenced by CNetworkServices::ValidatePort(), and ValidatePort().
CleanString()
void CUtil::CleanString (const std::string & strFileName, std::string & strTitle, std::string & strTitleAndYear, std::string & strYear, bool bRemoveExtension = false, bool bCleanChars = true) static
References CRegExp::autoUtf8, URIUtils::GetExtension(), GetFilenameIdentifier(), CRegExp::GetMatch(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, CRegExp::RegComp(), CRegExp::RegFind(), and URIUtils::RemoveExtension().
Referenced by CFileItem::CleanString(), ADDON::CScraper::FindMovie(), XBMCAddon::xbmc::getCleanMovieTitle(), and TEST_P().
ClearSubtitles()
void CUtil::ClearSubtitles () static
References XFILE::CFile::Delete(), XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::GetDirectory(), CLog::Log(), and LOGDEBUG.
Referenced by CApplication::PlayFile().
ConvertMilliSecsToSecs()
static double CUtil::ConvertMilliSecsToSecs (int64_t offset) inline static
Referenced by XFILE::CAudioBookFileDirectory::GetDirectory(), XBMCAddon::xbmcgui::ListItem::getProperty(), CApplication::PlayFile(), and PAPlayer::QueueNextFileEx().
ConvertMilliSecsToSecsInt()
static int64_t CUtil::ConvertMilliSecsToSecsInt (int64_t offset) inline static
Referenced by ConvertMilliSecsToSecsIntRounded(), XFILE::CAudioBookFileDirectory::GetDirectory(), and KODI::VIDEO::UTILS::GetResumeString().
ConvertMilliSecsToSecsIntRounded()
static int64_t CUtil::ConvertMilliSecsToSecsIntRounded (int64_t offset) inline static
References ConvertMilliSecsToSecsInt().
Referenced by CCueDocument::GetSongs(), KODI::PLAYLIST::CPlayListM3U::Load(), and CCueDocument::LoadTracks().
ConvertSecsToMilliSecs()
static int64_t CUtil::ConvertSecsToMilliSecs (double secs) inline static
References int64_t().
Referenced by CSaveFileState::DoWork(), CCueDocument::ExtractTimeFromIndex(), XFILE::CAudioBookFileDirectory::GetDirectory(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), CCueDocument::LoadTracks(), CApplication::OnAction(), JSONRPC::CPlayerOperations::Open(), CApplication::Restart(), and XBMCAddon::xbmcgui::ListItem::setStartOffsetRaw().
CopyUserDataIfNeeded()
void CUtil::CopyUserDataIfNeeded (const std::string & strPath, const std::string & file, const std::string & destname = "") static
Copy files from the application bundle over to the user data directory in Application Support/Kodi.
References URIUtils::AddFileToFolder(), XFILE::CFile::Copy(), and XFILE::CFile::Exists().
Referenced by CApplication::Create(), and CPlatformDarwinEmbedded::InitStageOne().
CreateDirectoryEx()
bool CUtil::CreateDirectoryEx (const std::string & strPath) static
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), XFILE::CDirectory::Create(), XFILE::CDirectory::Exists(), URIUtils::IsHD(), URIUtils::IsNfs(), URIUtils::IsSmb(), CLog::Log(), LOGERROR, and URIUtils::SplitPath().
Referenced by KODI::CDRIP::CCDDARipper::CreateAlbumDir(), XBMCAddon::xbmcvfs::mkdirs(), and TEST_P().
DeleteDirectoryCache()
void CUtil::DeleteDirectoryCache (const std::string & prefix = "") static
References XFILE::CFile::Delete(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::GetDirectory(), and URIUtils::GetFileName().
Referenced by DeleteMusicDatabaseDirectoryCache(), CGUIWindowMusicPlaylistEditor::DeleteRemoveableMediaDirectoryCache(), DeleteVideoDatabaseDirectoryCache(), CProfileManager::LoadProfile(), CGUIWindowMusicBase::OnMessage(), and CGUIDialogContextMenu::SwitchMedia().
DeleteMusicDatabaseDirectoryCache()
void CUtil::DeleteMusicDatabaseDirectoryCache () static
References DeleteDirectoryCache().
Referenced by UPNP::CUPnPServer::OnUpdateObject(), MUSIC_INFO::CMusicInfoScanner::Process(), and CMusicLibraryQueue::Refresh().
DeleteVideoDatabaseDirectoryCache()
void CUtil::DeleteVideoDatabaseDirectoryCache () static
References DeleteDirectoryCache().
Referenced by CVideoDatabase::CleanDatabase(), CGUIDialogVideoBookmarks::Delete(), CGUIDialogVideoInfo::DeleteVideoItem(), CSaveFileState::DoWork(), CGUIDialogVideoInfo::ManageVideoItemArtwork(), MasterMode(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoNav::OnDeleteItem(), CGUIDialogVideoBookmarks::OnMessage(), CGUIWindowVideoBase::OnUnAssignContent(), UPNP::CUPnPServer::OnUpdateObject(), CVideoLibraryQueue::Refresh(), CGUIDialogVideoInfo::SetMovie(), and CGUIWindowVideoBase::ShowInfo().
ExcludeFileOrFolder()
bool CUtil::ExcludeFileOrFolder (const std::string & strFileOrFolder, const std::vector< std::string > & regexps) static
References CRegExp::autoUtf8, CLog::Log(), LOGDEBUG, LOGERROR, CRegExp::RegComp(), and CRegExp::RegFind().
Referenced by KODI::VIDEO::CVideoInfoScanner::CanFastHash(), MUSIC_INFO::CMusicInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::DoScan(), JSONRPC::CFileOperations::FillFileItemList(), JSONRPC::CFileOperations::GetDirectory(), CGUIMediaWindow::GetDirectory(), CGUIWindowVideoBase::OnItemInfo(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), and MUSIC_INFO::CMusicInfoScanner::ScanTags().
FindVobSubPair()
bool CUtil::FindVobSubPair (const std::vector< std::string > & vecSubtitles, const std::string & strIdxPath, std::string & strSubPath) static
in a vector of subtitles finds the corresponding .sub file for a given .idx file
References URIUtils::HasExtension(), URIUtils::IsInArchive(), URIUtils::PathEquals(), URIUtils::ReplaceExtension(), and URIUtils::Split().
Referenced by CVideoPlayer::OpenInputStream(), and CDVDFileInfo::ProcessExternalSubtitles().
ForceForwardSlashes()
void CUtil::ForceForwardSlashes (std::string & strPath) static
Referenced by GetMatchingSource().
GetDefaultFolderThumb()
std::string CUtil::GetDefaultFolderThumb (const std::string & folderThumb) static
References CServiceBroker::GetGUI().
GetDirectoryName()
bool CUtil::GetDirectoryName (const std::string & strFileName, std::string & strDescription) static
References URIUtils::GetDirectory(), URIUtils::GetFileName(), and URIUtils::RemoveSlashAtEnd().
GetDiscNumberFromPath()
std::string CUtil::GetDiscNumberFromPath (const std::string & path) static
Return the disc number in case the last segment of given path ends with 'Disc n'. Will look for 'Disc', 'Disk' and the locale specific spelling.
Returns
the disc number as string if found, empty string otherwise.
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo().
GetDVDDriveIcon()
void CUtil::GetDVDDriveIcon (const std::string & strPath, std::string & strIcon) static
References CServiceBroker::GetMediaManager(), CFileItem::IsBluray(), URIUtils::IsCDDA(), URIUtils::IsDVD(), URIUtils::IsISO9660(), and MEDIA_DETECT::CCdInfo::IsVideoCd().
Referenced by XFILE::CSourcesDirectory::GetDirectory().
GetDVDIfoTitle()
int CUtil::GetDVDIfoTitle (const std::string & strPathFile) static
References URIUtils::GetFileName().
GetExternalStreamDetailsFromFilename()
ExternalStreamInfo CUtil::GetExternalStreamDetailsFromFilename (const std::string & videoPath, const std::string & associatedFile) static
Retrieves stream info of external associated files, e.g., subtitles, for a given video.
Parameters
[in] videoPath The full path of the video file.
[in] associatedFile A file that provides additional streams for the given video file.
Returns
stream info for the given associatedFile
References CLangCodeExpander::ConvertToISO6392B(), FLAG_DEFAULT, FLAG_FORCED, FLAG_HEARING_IMPAIRED, FLAG_NONE, FLAG_ORIGINAL, g_LangCodeExpander, g_localizeStrings, CLocalizeStrings::Get(), URIUtils::GetExtension(), URIUtils::GetFileName(), URIUtils::IsInArchive(), CLog::Log(), LOGDEBUG, name, and URIUtils::RemoveExtension().
Referenced by CDVDFileInfo::AddExternalSubtitleToDetails(), CVideoPlayer::AddSubtitleFile(), UPNP::BuildObject(), and CDemuxMultiSource::SetMissingStreamDetails().
GetFileAndProtocol()
void CUtil::GetFileAndProtocol (const std::string & strURL, std::string & strDir) static
References CURL::GetFileName(), CURL::GetProtocol(), URIUtils::IsDVD(), and URIUtils::IsRemote().
GetFileDigest()
std::string CUtil::GetFileDigest (const std::string & strPath, KODI::UTILITY::CDigest::Type type) static
retrieve MD5sum of a file
Parameters
strPath - path to the file to MD5sum
Returns
md5 sum of the file
References KODI::UTILITY::CDigest::Update().
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), ADDON::Interface_Filesystem::get_file_md5(), and CGUIDialogAddonInfo::OnSelectVersion().
GetFilenameIdentifier() [1/2]
bool CUtil::GetFilenameIdentifier (const std::string & fileName, std::string & identifierType, std::string & identifier) static
References GetFilenameIdentifier().
Referenced by CleanString(), GetFilenameIdentifier(), HasFilenameIdentifier(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), and TEST_P().
GetFilenameIdentifier() [2/2]
bool CUtil::GetFilenameIdentifier (const std::string & fileName, std::string & identifierType, std::string & identifier, std::string & match) static
References CRegExp::autoUtf8, CRegExp::GetMatch(), CServiceBroker::GetSettingsComponent(), LOGERROR, CRegExp::RegComp(), and CRegExp::RegFind().
GetFrameworksPath()
std::string CUtil::GetFrameworksPath (bool forPython = false) static
References CDarwinUtils::GetFrameworkPath().
Referenced by init_emu_environ(), CSettingsComponent::InitDirectoriesOSX(), CSpecialProtocol::LogPaths(), XBPython::OnScriptInitialized(), and TestBasicEnvironment::SetUp().
GetHomePath()
std::string CUtil::GetHomePath (const std::string & strTarget = "KODI_HOME") static
References CEnvironment::getenv().
Referenced by CWIN32Util::GetProfilePath(), CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), CSettingsComponent::InitDirectoriesWin32(), CPlatformDarwinOSX::InitStageOne(), CXBMCTestUtils::SetReferenceFileBasePath(), and XBMCHelper::XBMCHelper().
GetItemsToScan()
void CUtil::GetItemsToScan (const std::string & videoPath, const std::string & item_exts, const std::vector< std::string > & sub_dirs, CFileItemList & items) static protected
Retrieves FileItems that could contain associated files of a given video.
Parameters
[in] videoPath The full path of the video file.
[in] item_exts A | separated string of extensions specifying the associated files.
[in] sub_dirs A vector of sub directory names to look for.
[out] items A List of FileItems to scan for associated files.
References CFileItemList::Append(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, and XFILE::CDirectory::GetDirectory().
Referenced by ScanForExternalAudio(), and ScanForExternalSubtitles().
GetMatchingSource()
int CUtil::GetMatchingSource (const std::string & strPath, std::vector< CMediaSource > & sources, bool & bIsSourceName) static
References ForceForwardSlashes(), XFILE::CMultiPathDirectory::GetFirstPath(), CURL::GetHostName(), GetMatchingSource(), CURL::GetWithoutUserDetails(), URIUtils::HasSlashAtEnd(), URIUtils::IsOnDVD(), CURL::IsProtocol(), CLog::Log(), LOGDEBUG, CURL::SetOptions(), CURL::SetProtocolOptions(), CMediaSource::strName, CMediaSource::strPath, and CMediaSource::vecPaths.
Referenced by CHTTPVfsHandler::CHTTPVfsHandler(), CVideoDatabase::CleanDatabase(), CVideoDatabase::CleanMediaType(), CGUIDialogContextMenu::GetDefaultShareNameByType(), GetMatchingSource(), KODI::GAME::CGUIWindowGames::GetStartFolder(), CGUIWindowPictures::GetStartFolder(), CGUIWindowPrograms::GetStartFolder(), CGUIPassword::IsDatabasePathUnlocked(), XFILE::CVirtualDirectory::IsInSource(), CGUIPassword::IsMediaFileUnlocked(), CGUIPassword::IsMediaPathUnlocked(), KODI::CDRIP::CCDDARipper::OnJobComplete(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogInfoProviderSettings::OnSettingAction(), CGUIDialogLibExportSettings::OnSettingAction(), CFileUtils::RemoteAccessAllowed(), SetFile(), SetImage(), CGUIWindowFileManager::SetInitialPath(), and SetPath().
GetNextFilename()
std::string CUtil::GetNextFilename (const std::string & fn_template, int max) static
Finds next unused filename that matches padded int format identifier provided.
Parameters
[in] fn_template filename template consisting of a padded int format identifier (eg screenshot%03d)
[in] max maximum number to search for available name
Returns
"" on failure, string next available name matching format identifier on success
References XFILE::DIR_FLAG_NO_FILE_DIRS, CFileItemList::Get(), XFILE::CDirectory::GetDirectory(), URIUtils::GetDirectory(), URIUtils::GetExtension(), max, name, and CFileItemList::SetFastLookup().
Referenced by XFILE::CSimpleFileCache::Open(), anonymous_namespace{GUIBuiltins.cpp}::Screenshot(), and CScreenShot::TakeScreenshot().
GetNextPathname()
std::string CUtil::GetNextPathname (const std::string & path_template, int max) static
References XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), max, and name.
GetQualifiedFilename()
void CUtil::GetQualifiedFilename (const std::string & strBasePath, std::string & strFilename) static
References URIUtils::AddFileToFolder(), URIUtils::GetParentPath(), and CURL::GetProtocol().
Referenced by KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListPLS::Load(), KODI::PLAYLIST::CPlayListB4S::LoadData(), KODI::PLAYLIST::CPlayListWPL::LoadData(), TEST(), and TEST().
GetRandomNumber()
int CUtil::GetRandomNumber () static
Thread-safe random number generation.
References s_randomSeed.
Referenced by ByRandom().
GetRecursiveDirsListing()
void CUtil::GetRecursiveDirsListing (const std::string & strPath, CFileItemList & items, unsigned int flags = 0) static
References CFileItemList::Add(), XFILE::CDirectory::GetDirectory(), and GetRecursiveDirsListing().
Referenced by GetRecursiveDirsListing(), and KODI::VIDEO::CVideoInfoScanner::GetRecursiveFastHash().
GetRecursiveListing()
void CUtil::GetRecursiveListing (const std::string & strPath, CFileItemList & items, const std::string & strMask, unsigned int flags = 0) static
References CFileItemList::Add(), XFILE::CDirectory::GetDirectory(), and GetRecursiveListing().
Referenced by anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording::DoRun(), GetRecursiveListing(), CApplication::OnApplicationMessage(), CApplication::PlayMedia(), CVideoLibraryMarkWatchedJob::Work(), and CVideoLibraryResetResumePointJob::Work().
GetSkinThemes()
void CUtil::GetSkinThemes (std::vector< std::string > & vecTheme) static
References URIUtils::AddFileToFolder(), XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::GetDirectory(), URIUtils::GetExtension(), CURL::GetFileName(), URIUtils::GetFileName(), CURL::GetHostName(), CServiceBroker::GetWinSystem(), and CURL::IsProtocol().
Referenced by SetTheme(), and ADDON::CSkinInfo::SettingOptionsSkinThemesFiller().
GetSplashPath()
std::string CUtil::GetSplashPath () static
Get resolved filesystem location of splash image.
References CSpecialProtocol::TranslatePathConvertCase().
Referenced by IOSExternalTouchController::createGestureRecognizers, CGUIWindowSplash::OnInitWindow(), and CRenderSystemBase::ShowSplash().
GetTitleFromPath() [1/2]
std::string CUtil::GetTitleFromPath (const CURL & url, bool bIsFolder = false) static
References g_localizeStrings, CURL::Get(), CLocalizeStrings::Get(), XFILE::CRSSDirectory::GetDirectory(), URIUtils::GetFileName(), XFILE::CUPnPDirectory::GetFriendlyName(), CURL::GetHostName(), CServiceBroker::GetSettingsComponent(), URIUtils::HasParentInHostname(), CURL::IsProtocol(), CFileItem::m_strTitle, URIUtils::RemoveExtension(), URIUtils::RemoveSlashAtEnd(), and CSettings::SETTING_FILELISTS_SHOWEXTENSIONS.
Referenced by CFavouritesService::AddOrRemove(), JSONRPC::CFileOperations::FillFileItem(), JSONRPC::CAudioLibrary::FillFileItem(), JSONRPC::CVideoLibrary::FillFileItem(), JSONRPC::CFileItemHandler::FillFileItemList(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetFallbackLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetFallbackLabel(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel(), CLabelFormatter::GetMaskContent(), GetTitleFromPath(), GetVideoBasePathAndFileName(), KODI::GUILIB::GUIINFO::CGamesGUIInfo::InitCurrentItem(), CGUIWindowMusicPlayList::OnItemLoaded(), CGUIDialogMediaSource::OnPath(), CGUIDialogMediaSource::OnPathBrowse(), KODI::PLAYLIST::CSmartPlaylist::readNameFromPath(), and CGUIMediaWindow::Update().
GetTitleFromPath() [2/2]
std::string CUtil::GetTitleFromPath (const std::string & strFileNameAndPath, bool bIsFolder = false) static
References GetTitleFromPath().
GetVideoBasePathAndFileName()
void CUtil::GetVideoBasePathAndFileName (const std::string & videoPath, std::string & basePath, std::string & videoFileName) static protected
Retrieves the base path and the filename of a given video.
Parameters
[in] videoPath The full path of the video file.
[out] basePath The base path of the given video.
[out] videoFileName The file name of the given video..
References URIUtils::GetBasePath(), URIUtils::GetFileName(), CURL::GetHostName(), CFileItem::GetLocalMetadataPath(), URIUtils::GetParentPath(), GetTitleFromPath(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CFileItem::IsOpticalMediaFile(), CURL::IsProtocol(), CVideoInfoTag::m_basePath, and URIUtils::ReplaceExtension().
Referenced by ScanForExternalAudio(), and ScanForExternalSubtitles().
GetVobSubIdxFromSub()
std::string CUtil::GetVobSubIdxFromSub (const std::string & vobSub) static
find a .idx file from a path of a plain or archived vobsub .sub file
References URIUtils::AddFileToFolder(), XFILE::CFile::Exists(), URIUtils::GetDirectory(), URIUtils::GetFileName(), URIUtils::GetParentPath(), URIUtils::IsInArchive(), and URIUtils::ReplaceExtension().
Referenced by CVideoPlayer::AddSubtitleFile().
GetVobSubSubFromIdx()
std::string CUtil::GetVobSubSubFromIdx (const std::string & vobSubIdx) static
find a plain or archived vobsub .sub file corresponding to an .idx file
References URIUtils::CreateArchivePath(), XFILE::CFile::Exists(), CURL::Get(), URIUtils::GetFileName(), and URIUtils::ReplaceExtension().
Referenced by CVideoPlayer::AddSubtitleFile().
HasFilenameIdentifier()
bool CUtil::HasFilenameIdentifier (const std::string & fileName) static
References GetFilenameIdentifier().
Referenced by CVideoLibraryRefreshingJob::Work().
InitRandomSeed()
void CUtil::InitRandomSeed () static
Referenced by CApplication::Create().
IsPicture()
bool CUtil::IsPicture (const std::string & strFile) static
References CServiceBroker::GetFileExtensionProvider(), and URIUtils::HasExtension().
Referenced by CFileItem::IsPicture().
IsSupportedFontExtension()
static bool CUtil::IsSupportedFontExtension (const std::string & fileName) static
Check if a filename contains a supported font extension.
Parameters
filename The filename to check
Returns
True if it is supported, otherwise false
IsVobSub()
bool CUtil::IsVobSub (const std::vector< std::string > & vecSubtitles, const std::string & strSubPath) static
checks if in the vector of subtitles the given .sub file has a corresponding idx and hence is a vobsub file
References URIUtils::HasExtension(), URIUtils::IsInArchive(), URIUtils::PathEquals(), URIUtils::ReplaceExtension(), and URIUtils::Split().
Referenced by CVideoPlayer::OpenInputStream(), and CDVDFileInfo::ProcessExternalSubtitles().
LookupRomanDigit()
int CUtil::LookupRomanDigit (char roman_digit) static
Referenced by TranslateRomanNumeral().
MakeLegalFileName()
std::string CUtil::MakeLegalFileName (std::string strFile, int LegalType = LEGAL_NONE) static
References LEGAL_WIN32_COMPAT.
Referenced by CDVDDemuxFFmpeg::AddStream(), CFileOperationJob::DoProcess(), CVideoDatabase::DumpToDummyFiles(), CVideoDatabase::ExportToXML(), CMusicDatabase::GetAlbumFolder(), CMusicDatabase::GetArtistFolderName(), KODI::VIDEO::CVideoInfoScanner::GetMovieSetInfoFolder(), CVideoDatabase::GetSafeFile(), CVideoDatabase::ImportFromXML(), PERIPHERALS::CPeripheral::Initialise(), ADDON::Interface_Filesystem::make_legal_filename(), MakeLegalPath(), CGUIDialogSmartPlaylistEditor::OnOK(), KODI::CDRIP::CCDDARipper::RipCD(), KODI::CDRIP::CCDDARipper::RipTrack(), CGUIWindowMusicPlayList::SavePlayList(), CGUIWindowVideoPlaylist::SavePlayList(), PVR::CPVRGUIChannelIconUpdater::SearchAndUpdateMissingChannelIcons(), CGUIDialogProfileSettings::ShowForProfile(), win32_exception::write_minidump(), and win32_exception::write_stacktrace().
MakeLegalPath()
std::string CUtil::MakeLegalPath (std::string strPath, int LegalType = LEGAL_NONE) static
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), XFILE::CMultiPathDirectory::GetFirstPath(), XFILE::CStackDirectory::GetFirstStackedFile(), URIUtils::HasSlashAtEnd(), URIUtils::IsHD(), URIUtils::IsMultiPath(), URIUtils::IsNfs(), URIUtils::IsSmb(), URIUtils::IsStack(), MakeLegalFileName(), MakeLegalPath(), and URIUtils::SplitPath().
Referenced by KODI::CDRIP::CCDDARipper::CreateAlbumDir(), ADDON::Interface_Filesystem::make_legal_path(), XBMCAddon::xbmcvfs::makeLegalFilename(), MakeLegalPath(), KODI::PLAYLIST::CPlayListB4S::Save(), KODI::PLAYLIST::CPlayListM3U::Save(), KODI::PLAYLIST::CPlayListPLS::Save(), KODI::PLAYLIST::CPlayListWPL::Save(), KODI::PLAYLIST::CPlayListXML::Save(), and TEST().
MakeShortenPath()
bool CUtil::MakeShortenPath (std::string StrInput, std::string & StrOutput, size_t iTextMaxLength) static
Referenced by TEST(), and CGUIControlButtonSetting::Update().
MusicPlaylistsLocation()
std::string CUtil::MusicPlaylistsLocation () static
References URIUtils::AddFileToFolder(), XFILE::CMultiPathDirectory::ConstructMultiPath(), CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_SYSTEM_PLAYLISTSPATH.
Referenced by CGUIWindowMusicNav::GetContextButtons(), and CSpecialProtocol::TranslatePath().
RemoveTempFiles()
void CUtil::RemoveTempFiles () static
References XFILE::CFile::Delete(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::GetDirectory(), and CServiceBroker::GetSettingsComponent().
Referenced by CApplication::Initialize(), and CGUIWindowMusicBase::OnBack().
RemoveTrailingDiscNumberSegmentFromPath()
std::string CUtil::RemoveTrailingDiscNumberSegmentFromPath (std::string path) static
Remove last segment of the given path if it matches 'Disc n'. Will look for 'Disc', 'Disk' and the locale specific spelling.
Returns
the given path with last segment removed if it matches 'Disc n', unchanged path otherwise.
Referenced by CFileItem::GetBaseMoviePath().
ResolveExecutablePath()
std::string CUtil::ResolveExecutablePath () static
References g_charsetConverter, CCompileInfo::GetAppName(), CDarwinUtils::GetExecutablePath(), MAX_PATH, and PATH_MAX.
Referenced by CApplication::PrintStartupLog().
RunShortcut()
void CUtil::RunShortcut (const char * szPath) static
ScanArchiveForAssociatedItems()
int CUtil::ScanArchiveForAssociatedItems (const std::string & strArchivePath, const std::string & videoNameNoExt, const std::vector< std::string > & item_exts, std::vector< std::string > & associatedFiles) static protected
Searches in an archive for associated files of a given video.
Parameters
[in] strArchivePath The full path of the archive.
[in] videoNameNoExt The filename of the video without extension for which associated files should be retrieved.
[in] item_exts A vector of extensions specifying the associated files.
[out] associatedFiles A vector containing the full paths of all found associated files.
References URIUtils::CreateArchivePath(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::GetDirectory(), URIUtils::GetExtension(), URIUtils::GetFileName(), URIUtils::HasExtension(), CLog::Log(), LOGDEBUG, LOGINFO, and ScanArchiveForAssociatedItems().
Referenced by ScanArchiveForAssociatedItems(), and ScanPathsForAssociatedItems().
ScanForExternalAudio()
void CUtil::ScanForExternalAudio (const std::string & videoPath, std::vector< std::string > & vecAudio) static
Retrieves paths of external audio files for a given video.
Parameters
[in] videoPath The full path of the video file.
[out] vecAudio A vector containing the full paths of all found external audio files.
References CServiceBroker::GetFileExtensionProvider(), GetItemsToScan(), CFileItemList::GetList(), CVideoDatabase::GetUseAllExternalAudioForVideo(), GetVideoBasePathAndFileName(), KODI::NETWORK::IsInternetStream(), CFileItem::IsLiveTV(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsPVR(), CVideoDatabase::Open(), and ScanPathsForAssociatedItems().
Referenced by CDVDFactoryInputStream::CreateInputStream().
ScanForExternalSubtitles()
void CUtil::ScanForExternalSubtitles (const std::string & strMovie, std::vector< std::string > & vecSubtitles) static
References URIUtils::AddSlashAtEnd(), CFileItemList::Append(), XFILE::CFile::Copy(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, end(), XFILE::CDirectory::Exists(), XFILE::CDirectory::GetDirectory(), CFileItem::GetDynPath(), CServiceBroker::GetFileExtensionProvider(), CMediaSettings::GetInstance(), GetItemsToScan(), CServiceBroker::GetNetwork(), CServiceBroker::GetSettingsComponent(), CFileExtensionProvider::GetSubtitleExtensions(), GetVideoBasePathAndFileName(), URIUtils::HasExtension(), URIUtils::IsHD(), KODI::NETWORK::IsInternetStream(), URIUtils::IsOnLAN(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsPVR(), CDVDSubtitleTagSami::LoadHead(), CLog::Log(), LOGDEBUG, LOGINFO, CDVDSubtitleTagSami::m_Langclass, CDVDSubtitleStream::Open(), ScanPathsForAssociatedItems(), CMediaSettings::SetAdditionalSubtitleDirectoryChecked(), and CSettings::SETTING_SUBTITLES_CUSTOMPATH.
Referenced by UPNP::BuildObject(), CVideoPlayer::OpenInputStream(), and CDVDFileInfo::ProcessExternalSubtitles().
ScanPathsForAssociatedItems()
void CUtil::ScanPathsForAssociatedItems (const std::string & videoName, const CFileItemList & items, const std::vector< std::string > & item_exts, std::vector< std::string > & associatedFiles) static protected
Searches for associated files of a given video.
Parameters
[in] videoName The name of the video file.
[in] items A List of FileItems to scan for associated files.
[in] item_exts A vector of extensions specifying the associated files.
[out] associatedFiles A vector containing the full paths of all found associated files.
References URIUtils::GetFileName(), URIUtils::IsRAR(), URIUtils::IsZIP(), CLog::Log(), LOGINFO, URIUtils::RemoveExtension(), and ScanArchiveForAssociatedItems().
Referenced by ScanForExternalAudio(), and ScanForExternalSubtitles().
SplitParams()
void CUtil::SplitParams (const std::string & paramString, std::vector< std::string > & parameters) static
Split a comma separated parameter list into separate parameters. Takes care of the case where we may have a quoted string containing commas, or we may have a function (i.e. parentheses) with multiple parameters as a single parameter.
eg:
foo, bar(param1, param2), foo
will return:
"foo", "bar(param1, param2)", and "foo".
Parameters
paramString the string to break up
parameters the returned parameters
References CLog::Log(), and LOGWARNING.
Referenced by CGUIInfoManager::Property::Property(), anonymous_namespace{ExecString.cpp}::SplitExecFunction(), and TEST_P().
Stat64ToStat()
void CUtil::Stat64ToStat (struct stat * result, struct __stat64 * stat) static
References CLog::Log(), and LOGWARNING.
Referenced by dll_fstat(), and dll_stat().
Stat64ToStatI64()
void CUtil::Stat64ToStatI64 (struct _stati64 * result, struct __stat64 * stat) static
References _stati64::_st_atime, _stati64::_st_ctime, _stati64::_st_mtime, _stati64::st_dev, _stati64::st_gid, _stati64::st_ino, _stati64::st_mode, _stati64::st_nlink, _stati64::st_rdev, _stati64::st_size, and _stati64::st_uid.
Referenced by dll_stati64().
StatI64ToStat64()
void CUtil::StatI64ToStat64 (struct __stat64 * result, struct _stati64 * stat) static
References _stati64::_st_atime, _stati64::_st_ctime, _stati64::_st_mtime, _stati64::st_dev, _stati64::st_gid, _stati64::st_ino, _stati64::st_mode, _stati64::st_nlink, _stati64::st_rdev, _stati64::st_size, and _stati64::st_uid.
StatToStat64()
void CUtil::StatToStat64 (struct __stat64 * result, const struct stat * stat) static
Referenced by XFILE::CSMBFile::Stat(), and XFILE::CSMBFile::Stat().
StatToStatI64()
void CUtil::StatToStatI64 (struct _stati64 * result, struct stat * stat) static
References _stati64::_st_atime, _stati64::_st_ctime, _stati64::_st_mtime, int64_t(), _stati64::st_dev, _stati64::st_gid, _stati64::st_ino, _stati64::st_mode, _stati64::st_nlink, _stati64::st_rdev, _stati64::st_size, and _stati64::st_uid.
Referenced by dll_fstati64().
SupportsReadFileOperations()
bool CUtil::SupportsReadFileOperations (const std::string & strPath) static
Checks whether the supplied path supports Read file operations (e.g. Copy, ...)
Parameters
strPath the path to be checked
Returns
true if Read file operations are supported, false otherwise
References URIUtils::IsVideoDb().
Referenced by CGUIWindowFileManager::CanCopy().
SupportsWriteFileOperations()
bool CUtil::SupportsWriteFileOperations (const std::string & strPath) static
Checks whether the supplied path supports Write file operations (e.g. Rename, Delete, ...)
Parameters
strPath the path to be checked
Returns
true if Write file operations are supported, false otherwise
References ADDON::CVFSAddonCache::GetAddonInstances(), XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetProtocol(), CServiceBroker::GetVFSAddonCache(), CServiceBroker::IsAddonInterfaceUp(), URIUtils::IsDAV(), URIUtils::IsHD(), URIUtils::IsMultiPath(), URIUtils::IsNfs(), URIUtils::IsPVRRecording(), URIUtils::IsSmb(), URIUtils::IsStack(), XFILE::CMultiPathDirectory::SupportsWriteFileOperations(), XFILE::CPVRDirectory::SupportsWriteFileOperations(), and SupportsWriteFileOperations().
Referenced by CGUIDialogVideoInfo::DeleteVideoItem(), CVideoDatabase::ExportToXML(), CGUIWindowVideoNav::GetContextButtons(), CFileItem::IsReadOnly(), CMediaSource::IsWritable(), CGUIWindowVideoBase::OnDeleteItem(), CGUIDialogSubtitles::OnDownloadComplete(), XFILE::CMultiPathDirectory::SupportsWriteFileOperations(), and SupportsWriteFileOperations().
ToInt64()
int64_t CUtil::ToInt64 (uint32_t high, uint32_t low) static
References int64_t().
TranslateRomanNumeral()
int CUtil::TranslateRomanNumeral (const char * roman_numeral) static
References LookupRomanDigit().
Referenced by KODI::VIDEO::CVideoInfoScanner::GetEpisodeAndSeasonFromRegExp().
TranslateSpecialSource()
std::string CUtil::TranslateSpecialSource (const std::string & strSpecial) static
References URIUtils::AddFileToFolder(), CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_SYSTEM_PLAYLISTSPATH.
Referenced by CMediaSourceSettings::AddShare(), CMediaSourceSettings::GetSource(), CDecoderFilterManager::Load(), and CDecoderFilterManager::Save().
ValidatePath()
std::string CUtil::ValidatePath (std::string path, bool bFixDoubleSlashes = false) static
return a validated path, with correct directory separators.
References URIUtils::IsDOSPath(), and URIUtils::IsURL().
Referenced by dll_findfirst64i32(), dll_mkdir(), dll_open(), dll_opendir(), CURL::Parse(), TEST(), CSpecialProtocol::TranslatePath(), XFILE::CResourceFile::TranslatePath(), and XBMCAddon::xbmcvfs::validatePath().
ValidatePort()
bool CUtil::ValidatePort (int port) static
References CanBindPrivileged().
VideoPlaylistsLocation()
std::string CUtil::VideoPlaylistsLocation () static
References URIUtils::AddFileToFolder(), XFILE::CMultiPathDirectory::ConstructMultiPath(), CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_SYSTEM_PLAYLISTSPATH.
Referenced by CGUIWindowVideoNav::GetContextButtons(), CGUIWindowVideoNav::OnDeleteItem(), and CSpecialProtocol::TranslatePath().
Member Data Documentation
s_randomSeed
unsigned int CUtil::s_randomSeed = time(NULL) static private
Referenced by GetRandomNumber().
The documentation for this class was generated from the following files:
Util.h
Util.cpp