Kodi Documentation: CVideoLibraryMarkWatchedJob Class Reference
CVideoLibraryMarkWatchedJob Class Reference
Video library job implementation for marking items as watched/unwatched.
#include <VideoLibraryMarkWatchedJob.h>
Public Member Functions
CVideoLibraryMarkWatchedJob (const std::shared_ptr< CFileItem > &item, bool mark)
Creates a new video library scanning job.
~CVideoLibraryMarkWatchedJob () override
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
Public Member Functions inherited from CVideoLibraryJob
~CVideoLibraryJob () override
virtual bool CanBeCancelled () const
Whether the job can be cancelled or not.
virtual bool Cancel ()
Tries to cancel the running job.
bool DoWork () override
Main workhorse function of CJob instances.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Protected Member Functions
bool Work (CVideoDatabase &db) override
Worker method to be implemented by an actual implementation.
Protected Member Functions inherited from CVideoLibraryJob
CVideoLibraryJob ()
Private Attributes
std::shared_ptr< CFileItem > m_item
bool m_mark
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Detailed Description
Video library job implementation for marking items as watched/unwatched.
Constructor & Destructor Documentation
CVideoLibraryMarkWatchedJob()
CVideoLibraryMarkWatchedJob::CVideoLibraryMarkWatchedJob (const std::shared_ptr< CFileItem > & item, bool mark)
Creates a new video library scanning job.
Parameters
[in] item Item to be marked as watched/unwatched
[in] mark Whether to mark the item as watched or unwatched
~CVideoLibraryMarkWatchedJob()
CVideoLibraryMarkWatchedJob::~CVideoLibraryMarkWatchedJob () override default
Member Function Documentation
GetType()
const char * CVideoLibraryMarkWatchedJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CVideoLibraryJob.
Referenced by operator==().
operator==()
bool CVideoLibraryMarkWatchedJob::operator== (const CJob * job) const override virtual
Reimplemented from CVideoLibraryJob.
References CJob::GetType(), GetType(), m_item, and m_mark.
Work()
bool CVideoLibraryMarkWatchedJob::Work (CVideoDatabase & db) override protected virtual
Worker method to be implemented by an actual implementation.
Parameters
[in] db Already open video database to be used for interaction
Returns
True if the process succeeded, false otherwise
Implements CVideoLibraryJob.
References CFileItemList::Add(), CDatabase::BeginTransaction(), CVideoDatabase::ClearBookMarksOfFile(), CDatabase::Close(), CVideoDatabase::CommitTransaction(), XFILE::DIR_FLAG_NO_FILE_INFO, PVR::CPVRManager::Get(), CFileItemList::Get(), CServiceBroker::GetPVRManager(), CUtil::GetRecursiveListing(), CServiceBroker::GetSettingsComponent(), CVideoDatabase::IncrementPlayCount(), URIUtils::IsUPnP(), CDateTime::IsValid(), m_item, m_mark, PVR::CPVRGUIActionsRecordings::MarkWatched(), UPNP::CUPnP::MarkWatched(), CBookmark::RESUME, CVideoDatabase::SetPlayCount(), and CFileItemList::Size().
Member Data Documentation
m_item
std::shared_ptr<CFileItem> CVideoLibraryMarkWatchedJob::m_item private
Referenced by operator==(), and Work().
m_mark
bool CVideoLibraryMarkWatchedJob::m_mark private
Referenced by operator==(), and Work().
The documentation for this class was generated from the following files:
VideoLibraryMarkWatchedJob.h
VideoLibraryMarkWatchedJob.cpp