Kodi Documentation: Base64 Class Reference
Base64 Class Reference
#include <Base64.h>
Static Public Member Functions
static void Encode (const char *input, unsigned int length, std::string &output)
static std::string Encode (const char *input, unsigned int length)
static void Encode (const std::string &input, std::string &output)
static std::string Encode (const std::string &input)
static void Decode (const char *input, unsigned int length, std::string &output)
static std::string Decode (const char *input, unsigned int length)
static void Decode (const std::string &input, std::string &output)
static std::string Decode (const std::string &input)
Static Private Attributes
static const std::string m_characters
Member Function Documentation
Decode() [1/4]
std::string Base64::Decode (const char * input, unsigned int length) static
References Decode().
Decode() [2/4]
void Base64::Decode (const char * input, unsigned int length, std::string & output) static
References index(), and m_characters.
Referenced by Decode(), Decode(), Decode(), UPNP::DecodeObjectId(), XFILE::CCurlFile::ParseAndCorrectUrl(), CTagLoaderTagLib::ParseTag(), ADDON::CRepository::ResolvePathAndHash(), CTVOSTopShelf::RunTopShelf(), TEST(), TEST(), TEST(), and TEST().
Decode() [3/4]
std::string Base64::Decode (const std::string & input) static
References Decode().
Decode() [4/4]
void Base64::Decode (const std::string & input, std::string & output) static
References Decode(), and PADDING.
Encode() [1/4]
std::string Base64::Encode (const char * input, unsigned int length) static
References Encode().
Encode() [2/4]
void Base64::Encode (const char * input, unsigned int length, std::string & output) static
References left, m_characters, and PADDING.
Referenced by CWebSocketV8::calculateKey(), Encode(), Encode(), Encode(), UPNP::EncodeObjectId(), DRM::CMediaDrmCryptoSession::ProvisionRequest(), CTVOSTopShelf::SetTopShelfItems(), TEST(), TEST(), TEST(), and TEST().
Encode() [3/4]
std::string Base64::Encode (const std::string & input) static
References Encode().
Encode() [4/4]
void Base64::Encode (const std::string & input, std::string & output) static
References Encode().
Member Data Documentation
m_characters
const std::string Base64::m_characters static private
Initial value:
= "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                         "abcdefghijklmnopqrstuvwxyz"
                                         "0123456789+/"
Referenced by Decode(), and Encode().
The documentation for this class was generated from the following files:
Base64.h
Base64.cpp