Kodi Documentation: Subclass - ControlTextBox
Subclass - ControlTextBox
Python » Library - xbmcgui » Control
Used to show a multi-page piece of text.
Classes
class XBMCAddon::xbmcgui::ControlTextBox
Functions
XBMCAddon::xbmcgui::ControlTextBox::setText (...)
Function: setText(text)
Sets the text for this textbox.
XBMCAddon::xbmcgui::ControlTextBox::getText ()
Function: getText()
Returns the text value for this textbox.
XBMCAddon::xbmcgui::ControlTextBox::reset ()
Function: reset()
Clear's this textbox.
XBMCAddon::xbmcgui::ControlTextBox::scroll (...)
Function: scroll(id)
Scrolls to the given position.
XBMCAddon::xbmcgui::ControlTextBox::autoScroll (...)
Function: autoScroll(delay, time, repeat)
Set autoscrolling times.
Detailed Description
Used to show a multi-page piece of text.
Class: ControlTextBox(x, y, width, height[, font, textColor])
The text box is used for showing a large multipage piece of text in Kodi. You can choose the position, size, and look of the text.
Note
This class include also all calls from Control
Parameters
x integer - x coordinate of control.
y integer - y coordinate of control.
width integer - width of control.
height integer - height of control.
font [opt] string - font used for text. (e.g. 'font13')
textColor [opt] hexstring - color of textbox's text. (e.g. '0xFFFFFFFF')
Note
You can use the above as keywords for arguments and skip certain optional arguments.
Once you use a keyword, all following arguments require the keyword.
After you create the control, you need to add it to the window with addControl().
Example:
...
# ControlTextBox(x, y, width, height[, font, textColor])
self.textbox = xbmcgui.ControlTextBox(100, 250, 300, 300, textColor='0xFFFFFFFF')
...
As stated above, the GUI control is only created once added to a window. The example below shows how a ControlTextBox can be created, added to the current window and have some of its properties changed.
Extended example:
...
textbox = xbmcgui.ControlTextBox(100, 250, 300, 300, textColor='0xFFFFFFFF')
window = xbmcgui.Window(xbmcgui.getCurrentWindowId())
window.addControl(textbox)
textbox.setText("My Text Box")
textbox.scroll()
...
Function Documentation
autoScroll()
void XBMCAddon::xbmcgui::ControlTextBox::autoScroll (...)
Function: autoScroll(delay, time, repeat)
Set autoscrolling times.
Parameters
delay integer - Scroll delay (in ms)
time integer - Scroll time (in ms)
repeat integer - Repeat time
Note
autoScroll only works after you add the control to a window.
v15 Python API changes:
New function added.
Example:
...
self.textbox.autoScroll(1, 2, 1)
...
References XBMCAddon::xbmcgui::Control::pGUIControl.
getText()
String XBMCAddon::xbmcgui::ControlTextBox::getText ()
Function: getText()
Returns the text value for this textbox.
Returns
To get text from box
v19 Python API changes:
getText() can now be used before adding the control to the window
Example:
...
# getText()
text = self.text.getText()
...
References XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmcgui::Control::m_label, and XBMCAddon::xbmcgui::Control::pGUIControl.
reset()
void XBMCAddon::xbmcgui::ControlTextBox::reset ()
Function: reset()
Clear's this textbox.
v19 Python API changes:
reset() will reset any text defined for this control even before you add the control to the window
Example:
...
# reset()
self.textbox.reset()
...
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_RESET, XBMCAddon::xbmcgui::Control::iControlId, XBMCAddon::xbmcgui::Control::iParentId, XBMCAddon::xbmcgui::Control::m_label, and XBMCAddon::xbmcgui::Control::pGUIControl.
scroll()
void XBMCAddon::xbmcgui::ControlTextBox::scroll (...)
Function: scroll(id)
Scrolls to the given position.
Parameters
id integer - position to scroll to.
Note
scroll() only works after the control is added to a window.
Example:
...
# scroll(position)
self.textbox.scroll(10)
...
References XBMCAddon::xbmcgui::Control::pGUIControl.
setText()
void XBMCAddon::xbmcgui::ControlTextBox::setText (...)
Function: setText(text)
Sets the text for this textbox.
Parameters
text string - text string.
v19 Python API changes:
setText can now be used before adding the control to the window (the defined value is taken into consideration when the control is created)
Example:
...
# setText(text)
self.textbox.setText('This is a line of text that can wrap.')
...
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_SET, XBMCAddon::xbmcgui::Control::iControlId, XBMCAddon::xbmcgui::Control::iParentId, XBMCAddon::xbmcgui::Control::m_label, XBMCAddon::xbmcgui::Control::pGUIControl, CGUIMessage::SetLabel(), and text.