Kodi Documentation: CVideoPlayerVideo Class Reference
CVideoPlayerVideo Class Reference
#include <VideoPlayerVideo.h>
Public Member Functions
CVideoPlayerVideo (CDVDClock *pClock, CDVDOverlayContainer *pOverlayContainer, CDVDMessageQueue &parent, CRenderManager &renderManager, CProcessInfo &processInfo, double messageQueueTimeSize)
~CVideoPlayerVideo () override
bool OpenStream (CDVDStreamInfo hint) override
void CloseStream (bool bWaitForBuffers) override
void Flush (bool sync) override
bool AcceptsData () const override
bool HasData () const override
bool IsInited () const override
void SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority=0) override
void FlushMessages () override
void EnableSubtitle (bool bEnable) override
bool IsSubtitleEnabled () override
double GetSubtitleDelay () override
void SetSubtitleDelay (double delay) override
bool IsStalled () const override
bool IsRewindStalled () const override
double GetCurrentPts () override
double GetOutputDelay () override
std::string GetPlayerInfo () override
int GetVideoBitrate () override
void SetSpeed (int iSpeed) override
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Public Member Functions inherited from IDVDStreamPlayerVideo
IDVDStreamPlayerVideo (CProcessInfo &processInfo)
~IDVDStreamPlayerVideo () override=default
virtual bool IsEOS ()
Public Member Functions inherited from IDVDStreamPlayer
IDVDStreamPlayer (CProcessInfo &processInfo)
virtual ~IDVDStreamPlayer ()=default
Public Attributes
CDVDOverlayContainer * m_pOverlayContainer
CDVDClock * m_pClock
Protected Types
enum EOutputState { OUTPUT_NORMAL , OUTPUT_ABORT , OUTPUT_DROPPED , OUTPUT_AGAIN }
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions
void OnExit () override
void Process () override
bool ProcessDecoderOutput (double &frametime, double &pts)
void SendMessageBack (const std::shared_ptr< CDVDMsg > &pMsg, int priority=0)
MsgQueueReturnCode GetMessage (std::shared_ptr< CDVDMsg > &pMsg, std::chrono::milliseconds timeout, int &priority)
EOutputState OutputPicture (const VideoPicture *src)
void ProcessOverlays (const VideoPicture *pSource, double pts)
void OpenStream (CDVDStreamInfo &hint, std::unique_ptr< CDVDVideoCodec > codec)
void ResetFrameRateCalc ()
void CalcFrameRate ()
int CalcDropRequirement (double pts)
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes
double m_iSubtitleDelay
int m_iLateFrames
int m_iDroppedFrames
int m_iDroppedRequest
double m_fFrameRate
double m_fStableFrameRate
int m_iFrameRateCount
bool m_bAllowDrop
int m_iFrameRateErr
int m_iFrameRateLength
bool m_bFpsInvalid
bool m_bRenderSubs
float m_fForcedAspectRatio
int m_speed
std::atomic_bool m_stalled = false
std::atomic_bool m_rewindStalled
bool m_paused
IDVDStreamPlayer::ESyncState m_syncState
std::atomic_bool m_bAbortOutput
BitstreamStats m_videoStats
CDVDMessageQueue m_messageQueue
CDVDMessageQueue & m_messageParent
CDVDStreamInfo m_hints
std::unique_ptr< CDVDVideoCodec > m_pVideoCodec
CPtsTracker m_ptsTracker
std::list< DVDMessageListItem > m_packets
CDroppingStats m_droppingStats
CRenderManager & m_renderManager
VideoPicture m_picture
EOutputState m_outputSate {OUTPUT_NORMAL}
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Protected Attributes inherited from IDVDStreamPlayer
CProcessInfo & m_processInfo
Additional Inherited Members
Public Types inherited from IDVDStreamPlayer
enum ESyncState { SYNC_STARTING , SYNC_WAITSYNC , SYNC_INSYNC }
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Member Enumeration Documentation
EOutputState
enum CVideoPlayerVideo::EOutputState protected
Enumerator
OUTPUT_NORMAL
OUTPUT_ABORT
OUTPUT_DROPPED
OUTPUT_AGAIN
Constructor & Destructor Documentation
CVideoPlayerVideo()
CVideoPlayerVideo::CVideoPlayerVideo (CDVDClock * pClock, CDVDOverlayContainer * pOverlayContainer, CDVDMessageQueue & parent, CRenderManager & renderManager, CProcessInfo & processInfo, double messageQueueTimeSize)
References DVD_PLAYSPEED_NORMAL, CServiceBroker::GetSettingsComponent(), m_bAllowDrop, m_bFpsInvalid, m_bRenderSubs, m_fForcedAspectRatio, m_fFrameRate, m_fStableFrameRate, m_iDroppedFrames, m_iDroppedRequest, m_iFrameRateCount, m_iFrameRateErr, m_iFrameRateLength, m_iLateFrames, m_iSubtitleDelay, m_messageQueue, m_paused, m_pClock, m_pOverlayContainer, m_speed, m_syncState, CDVDMessageQueue::SetMaxDataSize(), CDVDMessageQueue::SetMaxTimeSize(), CSettings::SETTING_VIDEOPLAYER_QUEUEDATASIZE, and IDVDStreamPlayer::SYNC_STARTING.
~CVideoPlayerVideo()
CVideoPlayerVideo::~CVideoPlayerVideo () override
References m_bAbortOutput, and CThread::StopThread().
Member Function Documentation
AcceptsData()
bool CVideoPlayerVideo::AcceptsData () const override virtual
Implements IDVDStreamPlayerVideo.
References full, CDVDMessageQueue::IsFull(), and m_messageQueue.
CalcDropRequirement()
int CVideoPlayerVideo::CalcDropRequirement (double pts) protected
References DROP_BUFFER_LEVEL, DROP_DROPPED, DROP_VERYLATE, DVD_NOPTS_VALUE, CDroppingStats::CGain::frames, CRenderManager::GetStats(), CLog::Log(), LOGDEBUG, LOGVIDEO, m_bAllowDrop, m_droppingStats, CDroppingStats::m_gain, CDroppingStats::m_lastPts, m_pVideoCodec, m_renderManager, m_speed, CDroppingStats::m_totalGain, and CDroppingStats::CGain::pts.
Referenced by Process().
CalcFrameRate()
void CVideoPlayerVideo::CalcFrameRate () protected
References DVD_NOPTS_VALUE, DVD_TIME_BASE, CPtsTracker::GetFrameDuration(), CPtsTracker::GetMinFrameDuration(), CPtsTracker::GetPatternLength(), CServiceBroker::GetSettingsComponent(), CPtsTracker::HasFullBuffer(), CLog::Log(), LOGDEBUG, m_bAllowDrop, m_bFpsInvalid, m_fFrameRate, m_fStableFrameRate, m_iFrameRateCount, m_iFrameRateErr, m_iFrameRateLength, IDVDStreamPlayer::m_processInfo, m_ptsTracker, MAXFRAMERATEDIFF, MAXFRAMESERR, MathUtils::round_int(), CProcessInfo::SetVideoFps(), and CPtsTracker::VFRDetection().
Referenced by OutputPicture().
CloseStream()
void CVideoPlayerVideo::CloseStream (bool bWaitForBuffers) override virtual
Implements IDVDStreamPlayerVideo.
References CDVDMessageQueue::Abort(), CDVDMessageQueue::End(), CLog::Log(), LOGINFO, m_bAbortOutput, m_messageQueue, m_picture, m_pVideoCodec, m_speed, CVideoBuffer::Release(), SendMessage(), CThread::StopThread(), CDVDMsg::VIDEO_DRAIN, VideoPicture::videoBuffer, and CDVDMessageQueue::WaitUntilEmpty().
EnableSubtitle()
void CVideoPlayerVideo::EnableSubtitle (bool bEnable) inline override virtual
Implements IDVDStreamPlayerVideo.
References m_bRenderSubs.
Flush()
void CVideoPlayerVideo::Flush (bool sync) override virtual
Implements IDVDStreamPlayerVideo.
References CDVDMsg::GENERAL_FLUSH, m_bAbortOutput, and SendMessage().
FlushMessages()
void CVideoPlayerVideo::FlushMessages () inline override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::Flush(), CDVDMessageQueue::GetLevel(), m_messageQueue, IDVDStreamPlayer::m_processInfo, and CProcessInfo::SetLevelVQ().
Referenced by Process().
GetCurrentPts()
double CVideoPlayerVideo::GetCurrentPts () override virtual
Implements IDVDStreamPlayerVideo.
References DVD_NOPTS_VALUE, DVD_PLAYSPEED_NORMAL, CRenderManager::GetStats(), m_renderManager, m_speed, and m_stalled.
GetMessage()
MsgQueueReturnCode CVideoPlayerVideo::GetMessage (std::shared_ptr< CDVDMsg > & pMsg, std::chrono::milliseconds timeout, int & priority) inline protected
References CDVDMessageQueue::Get(), CDVDMessageQueue::GetLevel(), m_messageQueue, IDVDStreamPlayer::m_processInfo, and CProcessInfo::SetLevelVQ().
Referenced by Process().
GetOutputDelay()
double CVideoPlayerVideo::GetOutputDelay () override virtual
Implements IDVDStreamPlayerVideo.
References CDVDMsg::DEMUXER_PACKET, DVD_PLAYSPEED_NORMAL, DVD_TIME_BASE, CDVDMessageQueue::GetPacketCount(), m_fFrameRate, m_messageQueue, and m_speed.
GetPlayerInfo()
std::string CVideoPlayerVideo::GetPlayerInfo () override virtual
Implements IDVDStreamPlayerVideo.
References CProcessInfo::GetLevelVQ(), CPtsTracker::GetPatternLength(), CRenderManager::GetSkippedFrames(), CDVDMessageQueue::GetTimeSize(), GetVideoBitrate(), m_fFrameRate, m_iDroppedFrames, m_messageQueue, IDVDStreamPlayer::m_processInfo, m_ptsTracker, and m_renderManager.
GetSubtitleDelay()
double CVideoPlayerVideo::GetSubtitleDelay () inline override virtual
Implements IDVDStreamPlayerVideo.
References m_iSubtitleDelay.
GetVideoBitrate()
int CVideoPlayerVideo::GetVideoBitrate () override virtual
Implements IDVDStreamPlayerVideo.
References BitstreamStats::GetBitrate(), and m_videoStats.
Referenced by GetPlayerInfo().
HasData()
bool CVideoPlayerVideo::HasData () const override virtual
Implements IDVDStreamPlayerVideo.
References CDVDMessageQueue::GetDataSize(), and m_messageQueue.
IsInited()
bool CVideoPlayerVideo::IsInited () const override virtual
Implements IDVDStreamPlayerVideo.
References CDVDMessageQueue::IsInited(), and m_messageQueue.
IsRewindStalled()
bool CVideoPlayerVideo::IsRewindStalled () const inline override virtual
Reimplemented from IDVDStreamPlayerVideo.
References m_rewindStalled.
IsStalled()
bool CVideoPlayerVideo::IsStalled () const inline override virtual
Implements IDVDStreamPlayerVideo.
References m_stalled.
IsSubtitleEnabled()
bool CVideoPlayerVideo::IsSubtitleEnabled () inline override virtual
Implements IDVDStreamPlayerVideo.
References m_bRenderSubs.
OnExit()
void CVideoPlayerVideo::OnExit () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
OpenStream() [1/2]
void CVideoPlayerVideo::OpenStream (CDVDStreamInfo & hint, std::unique_ptr< CDVDVideoCodec > codec) protected
References CDVDStreamInfo::aspect, CDVDStreamInfo::codec, CODEC_ALLOW_FALLBACK, CDVDStreamInfo::codecOptions, CDVDFactoryCodec::CreateVideoCodec(), CDVDMsg::DEMUXER_PACKET, DVD_TIME_BASE, CDVDStreamInfo::forced_aspect, CDVDStreamInfo::fpsrate, CDVDStreamInfo::fpsscale, CDVDMessageQueue::GetPacketCount(), CProcessInfo::GetVideoBufferManager(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_bFpsInvalid, m_fForcedAspectRatio, m_fFrameRate, m_hints, m_iDroppedRequest, m_iLateFrames, m_messageParent, m_messageQueue, m_packets, IDVDStreamPlayer::m_processInfo, m_ptsTracker, m_pVideoCodec, m_renderManager, m_rewindStalled, m_stalled, m_syncState, CDVDCodecUtils::NormalizeFrameduration(), CDVDMsg::PLAYER_ABORT, CDVDMessageQueue::Put(), CVideoBufferManager::ReleasePools(), ResetFrameRateCalc(), CPtsTracker::ResetVFRDetection(), CProcessInfo::SetVideoFps(), CRenderManager::ShowVideo(), CThread::StopThread(), and IDVDStreamPlayer::SYNC_STARTING.
OpenStream() [2/2]
bool CVideoPlayerVideo::OpenStream (CDVDStreamInfo hint) override virtual
Implements IDVDStreamPlayerVideo.
References CDVDStreamInfo::codec, CODEC_ALLOW_FALLBACK, CDVDStreamInfo::codec_tag, CDVDStreamInfo::codecOptions, CThread::Create(), CDVDFactoryCodec::CreateVideoCodec(), CDVDStreamInfo::extradata, CDVDStreamInfo::flags, CDVDMessageQueue::Init(), CDVDMessageQueue::IsInited(), CProcessInfo::IsVideoHwDecoder(), CLog::Log(), LOGERROR, LOGINFO, m_messageQueue, IDVDStreamPlayer::m_processInfo, m_pVideoCodec, OpenStream(), CProcessInfo::ResetVideoCodecInfo(), SendMessage(), and CProcessInfo::SetLevelVQ().
Referenced by OpenStream(), and Process().
OutputPicture()
CVideoPlayerVideo::EOutputState CVideoPlayerVideo::OutputPicture (const VideoPicture * src) protected
References CPtsTracker::Add(), CDroppingStats::AddOutputDropGain(), CRenderManager::AddVideoPicture(), CalcFrameRate(), CRenderManager::Configure(), DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, DVD_TIME_TO_MSEC(), DVP_FLAG_DROPPED, MathUtils::FloatEquals(), CDVDClock::GetClock(), CProcessInfo::GetDeinterlacingMethodDefault(), CRenderManager::GetStats(), CProcessInfo::GetVideoInterlaced(), CProcessInfo::GetVideoSettings(), CProcessInfo::GetVideoStereoMode(), VideoPicture::iFlags, CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_bAbortOutput, m_bFpsInvalid, m_droppingStats, m_fFrameRate, m_hints, CVideoSettings::m_InterlaceMethod, CDroppingStats::m_lastPts, m_messageParent, CVideoSettings::m_Orientation, m_pClock, IDVDStreamPlayer::m_processInfo, m_ptsTracker, m_pVideoCodec, m_renderManager, m_rewindStalled, m_speed, m_stalled, m_syncState, CDVDStreamInfo::orientation, OUTPUT_ABORT, OUTPUT_AGAIN, OUTPUT_DROPPED, OUTPUT_NORMAL, CDVDMsg::PLAYER_AVCHANGE, ProcessOverlays(), VideoPicture::pts, CDVDMessageQueue::Put(), CProcessInfo::SetVideoStereoMode(), CThread::Sleep(), VideoPicture::stereoMode, CProcessInfo::Supports(), IDVDStreamPlayer::SYNC_STARTING, CDVDClock::UpdateFramerate(), VS_INTERLACEMETHOD_NONE, and CRenderManager::WaitForBuffer().
Referenced by Process(), and ProcessDecoderOutput().
Process()
void CVideoPlayerVideo::Process (void) override protected virtual
Todo:
this needs to be set on a streamchange instead
Reimplemented from CThread.
References BitstreamStats::AddSampleBytes(), CalcDropRequirement(), CDVDMsg::DEMUXER_PACKET, CRenderManager::DiscardBuffer(), DROP_BUFFER_LEVEL, DROP_DROPPED, DROP_VERYLATE, DVD_CODEC_CTRL_DRAIN, DVD_CODEC_CTRL_DROP, DVD_CODEC_CTRL_DROP_ANY, DVD_CODEC_CTRL_HURRY, DVD_CODEC_CTRL_NO_POSTPROC, DVD_CODEC_CTRL_ROTATE, DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, DVD_SEC_TO_TIME(), DVD_TIME_BASE, CPtsTracker::Flush(), FlushMessages(), CDVDMsg::GENERAL_FLUSH, CDVDMsg::GENERAL_PAUSE, CDVDMsg::GENERAL_RESET, CDVDMsg::GENERAL_RESYNC, CDVDMsg::GENERAL_STREAMCHANGE, CDVDMsg::GENERAL_SYNCHRONIZE, CDVDMessageQueue::GetDataSize(), GetMessage(), CProcessInfo::IsFrameAdvance(), DEMUX_PACKET::iSize, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_bAllowDrop, CThread::m_bStop, m_droppingStats, m_fForcedAspectRatio, m_fFrameRate, m_iDroppedFrames, m_iDroppedRequest, m_iLateFrames, m_messageParent, m_messageQueue, m_outputSate, m_packets, m_paused, m_picture, IDVDStreamPlayer::m_processInfo, m_ptsTracker, m_pVideoCodec, m_renderManager, m_rewindStalled, m_speed, m_stalled, m_syncState, m_videoStats, MSGQ_IS_ERROR, MSGQ_TIMEOUT, OpenStream(), OUTPUT_AGAIN, OUTPUT_NORMAL, OutputPicture(), SStateMsg::player, CDVDMsg::PLAYER_REPORT_STATE, CDVDMsg::PLAYER_REQUEST_STATE, CDVDMsg::PLAYER_SETSPEED, ProcessDecoderOutput(), VideoPicture::pts, CDVDMessageQueue::Put(), CDVDMessageQueue::ReceivedAbortRequest(), CVideoBuffer::Release(), RENDERFEATURE_ROTATION, CDroppingStats::Reset(), ResetFrameRateCalc(), SendMessage(), SendMessageBack(), CRenderManager::ShowVideo(), BitstreamStats::Start(), CRenderManager::Supports(), IDVDStreamPlayer::SYNC_INSYNC, IDVDStreamPlayer::SYNC_STARTING, IDVDStreamPlayer::SYNC_WAITSYNC, SYNCSOURCE_VIDEO, SStateMsg::syncState, CDVDMsg::VIDEO_DRAIN, CDVDMsg::VIDEO_SET_ASPECT, VideoPicture::videoBuffer, VideoPlayer_VIDEO, and Wait().
ProcessDecoderOutput()
bool CVideoPlayerVideo::ProcessDecoderOutput (double & frametime, double & pts) protected
Todo:
implement
Todo:
implement
References SStartMsg::cachetime, SStartMsg::cachetotal, CRenderManager::DiscardBuffer(), VideoPicture::dts, DVD_MSEC_TO_TIME(), DVD_NOPTS_VALUE, DVD_TIME_BASE, DVP_FLAG_DROPPED, CPtsTracker::Flush(), CRenderManager::GetDelay(), CProcessInfo::GetVideoSettings(), VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iDuration, VideoPicture::iFlags, VideoPicture::iRepeatPicture, VideoPicture::iWidth, CLog::Log(), LOGDEBUG, m_fForcedAspectRatio, m_fFrameRate, m_hints, m_iDroppedFrames, m_messageParent, m_outputSate, m_packets, m_picture, IDVDStreamPlayer::m_processInfo, m_ptsTracker, m_pVideoCodec, m_renderManager, m_speed, CVideoSettings::m_StereoInvert, CVideoSettings::m_StereoMode, m_syncState, OUTPUT_ABORT, OUTPUT_AGAIN, OUTPUT_DROPPED, OutputPicture(), SStartMsg::player, CDVDMsg::PLAYER_STARTED, VideoPicture::pts, CDVDMessageQueue::Put(), RENDER_STEREO_MODE_SPLIT_HORIZONTAL, RENDER_STEREO_MODE_SPLIT_VERTICAL, SendMessage(), CDVDStreamInfo::stereo_mode, VideoPicture::stereoMode, IDVDStreamPlayer::SYNC_STARTING, IDVDStreamPlayer::SYNC_WAITSYNC, SStartMsg::timestamp, CDVDVideoCodec::VC_BUFFER, CDVDVideoCodec::VC_EOF, CDVDVideoCodec::VC_ERROR, CDVDVideoCodec::VC_FLUSHED, CDVDVideoCodec::VC_PICTURE, CDVDVideoCodec::VC_REOPEN, and VideoPlayer_VIDEO.
Referenced by Process().
ProcessOverlays()
void CVideoPlayerVideo::ProcessOverlays (const VideoPicture * pSource, double pts) protected
References CRenderManager::AddOverlay(), CDVDOverlayContainer::CleanUp(), DVDOVERLAY_TYPE_GROUP, CDVDOverlayContainer::GetOverlays(), m_bRenderSubs, m_iSubtitleDelay, CDVDOverlayGroup::m_overlays, m_pOverlayContainer, m_renderManager, m_syncState, and IDVDStreamPlayer::SYNC_INSYNC.
Referenced by OutputPicture().
ResetFrameRateCalc()
void CVideoPlayerVideo::ResetFrameRateCalc () protected
References CServiceBroker::GetSettingsComponent(), m_bAllowDrop, m_fStableFrameRate, m_iFrameRateCount, m_iFrameRateErr, and m_iFrameRateLength.
Referenced by OpenStream(), and Process().
SendMessage()
void CVideoPlayerVideo::SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority = 0) inline override virtual
Implements IDVDStreamPlayerVideo.
References CDVDMessageQueue::GetLevel(), m_messageQueue, IDVDStreamPlayer::m_processInfo, CDVDMessageQueue::Put(), and CProcessInfo::SetLevelVQ().
Referenced by CloseStream(), Flush(), OpenStream(), Process(), ProcessDecoderOutput(), and SetSpeed().
SendMessageBack()
void CVideoPlayerVideo::SendMessageBack (const std::shared_ptr< CDVDMsg > & pMsg, int priority = 0) inline protected
References CDVDMessageQueue::GetLevel(), m_messageQueue, IDVDStreamPlayer::m_processInfo, CDVDMessageQueue::PutBack(), and CProcessInfo::SetLevelVQ().
Referenced by Process().
SetSpeed()
void CVideoPlayerVideo::SetSpeed (int iSpeed) override virtual
Implements IDVDStreamPlayerVideo.
References CDVDMessageQueue::IsInited(), m_messageQueue, m_speed, CDVDMsg::PLAYER_SETSPEED, and SendMessage().
SetSubtitleDelay()
void CVideoPlayerVideo::SetSubtitleDelay (double delay) inline override virtual
Implements IDVDStreamPlayerVideo.
References m_iSubtitleDelay.
Member Data Documentation
m_bAbortOutput
std::atomic_bool CVideoPlayerVideo::m_bAbortOutput protected
Referenced by CloseStream(), Flush(), OutputPicture(), and ~CVideoPlayerVideo().
m_bAllowDrop
bool CVideoPlayerVideo::m_bAllowDrop protected
Referenced by CalcDropRequirement(), CalcFrameRate(), CVideoPlayerVideo(), Process(), and ResetFrameRateCalc().
m_bFpsInvalid
bool CVideoPlayerVideo::m_bFpsInvalid protected
Referenced by CalcFrameRate(), CVideoPlayerVideo(), OpenStream(), and OutputPicture().
m_bRenderSubs
bool CVideoPlayerVideo::m_bRenderSubs protected
Referenced by CVideoPlayerVideo(), EnableSubtitle(), IsSubtitleEnabled(), and ProcessOverlays().
m_droppingStats
CDroppingStats CVideoPlayerVideo::m_droppingStats protected
Referenced by CalcDropRequirement(), OutputPicture(), and Process().
m_fForcedAspectRatio
float CVideoPlayerVideo::m_fForcedAspectRatio protected
Referenced by CVideoPlayerVideo(), OpenStream(), Process(), and ProcessDecoderOutput().
m_fFrameRate
double CVideoPlayerVideo::m_fFrameRate protected
Referenced by CalcFrameRate(), CVideoPlayerVideo(), GetOutputDelay(), GetPlayerInfo(), OpenStream(), OutputPicture(), Process(), and ProcessDecoderOutput().
m_fStableFrameRate
double CVideoPlayerVideo::m_fStableFrameRate protected
Referenced by CalcFrameRate(), CVideoPlayerVideo(), and ResetFrameRateCalc().
m_hints
CDVDStreamInfo CVideoPlayerVideo::m_hints protected
Referenced by OpenStream(), OutputPicture(), and ProcessDecoderOutput().
m_iDroppedFrames
int CVideoPlayerVideo::m_iDroppedFrames protected
Referenced by CVideoPlayerVideo(), GetPlayerInfo(), Process(), and ProcessDecoderOutput().
m_iDroppedRequest
int CVideoPlayerVideo::m_iDroppedRequest protected
Referenced by CVideoPlayerVideo(), OpenStream(), and Process().
m_iFrameRateCount
int CVideoPlayerVideo::m_iFrameRateCount protected
Referenced by CalcFrameRate(), CVideoPlayerVideo(), and ResetFrameRateCalc().
m_iFrameRateErr
int CVideoPlayerVideo::m_iFrameRateErr protected
Referenced by CalcFrameRate(), CVideoPlayerVideo(), and ResetFrameRateCalc().
m_iFrameRateLength
int CVideoPlayerVideo::m_iFrameRateLength protected
Referenced by CalcFrameRate(), CVideoPlayerVideo(), and ResetFrameRateCalc().
m_iLateFrames
int CVideoPlayerVideo::m_iLateFrames protected
Referenced by CVideoPlayerVideo(), OpenStream(), and Process().
m_iSubtitleDelay
double CVideoPlayerVideo::m_iSubtitleDelay protected
Referenced by CVideoPlayerVideo(), GetSubtitleDelay(), ProcessOverlays(), and SetSubtitleDelay().
m_messageParent
CDVDMessageQueue& CVideoPlayerVideo::m_messageParent protected
Referenced by OpenStream(), OutputPicture(), Process(), and ProcessDecoderOutput().
m_messageQueue
CDVDMessageQueue CVideoPlayerVideo::m_messageQueue protected
Referenced by AcceptsData(), CloseStream(), CVideoPlayerVideo(), FlushMessages(), GetMessage(), GetOutputDelay(), GetPlayerInfo(), HasData(), IsInited(), OpenStream(), OpenStream(), Process(), SendMessage(), SendMessageBack(), and SetSpeed().
m_outputSate
EOutputState CVideoPlayerVideo::m_outputSate {OUTPUT_NORMAL} protected
Referenced by Process(), and ProcessDecoderOutput().
m_packets
std::list<DVDMessageListItem> CVideoPlayerVideo::m_packets protected
Referenced by OpenStream(), Process(), and ProcessDecoderOutput().
m_paused
bool CVideoPlayerVideo::m_paused protected
Referenced by CVideoPlayerVideo(), and Process().
m_pClock
CDVDClock* CVideoPlayerVideo::m_pClock
Referenced by CVideoPlayerVideo(), and OutputPicture().
m_picture
VideoPicture CVideoPlayerVideo::m_picture protected
Referenced by CloseStream(), Process(), and ProcessDecoderOutput().
m_pOverlayContainer
CDVDOverlayContainer* CVideoPlayerVideo::m_pOverlayContainer
Referenced by CVideoPlayerVideo(), and ProcessOverlays().
m_ptsTracker
CPtsTracker CVideoPlayerVideo::m_ptsTracker protected
Referenced by CalcFrameRate(), GetPlayerInfo(), OpenStream(), OutputPicture(), Process(), and ProcessDecoderOutput().
m_pVideoCodec
std::unique_ptr<CDVDVideoCodec> CVideoPlayerVideo::m_pVideoCodec protected
Referenced by CalcDropRequirement(), CloseStream(), OpenStream(), OpenStream(), OutputPicture(), Process(), and ProcessDecoderOutput().
m_renderManager
CRenderManager& CVideoPlayerVideo::m_renderManager protected
Referenced by CalcDropRequirement(), GetCurrentPts(), GetPlayerInfo(), OpenStream(), OutputPicture(), Process(), ProcessDecoderOutput(), and ProcessOverlays().
m_rewindStalled
std::atomic_bool CVideoPlayerVideo::m_rewindStalled protected
Referenced by IsRewindStalled(), OpenStream(), OutputPicture(), and Process().
m_speed
int CVideoPlayerVideo::m_speed protected
Referenced by CalcDropRequirement(), CloseStream(), CVideoPlayerVideo(), GetCurrentPts(), GetOutputDelay(), OutputPicture(), Process(), ProcessDecoderOutput(), and SetSpeed().
m_stalled
std::atomic_bool CVideoPlayerVideo::m_stalled = false protected
Referenced by GetCurrentPts(), IsStalled(), OpenStream(), OutputPicture(), and Process().
m_syncState
IDVDStreamPlayer::ESyncState CVideoPlayerVideo::m_syncState protected
Referenced by CVideoPlayerVideo(), OpenStream(), OutputPicture(), Process(), ProcessDecoderOutput(), and ProcessOverlays().
m_videoStats
BitstreamStats CVideoPlayerVideo::m_videoStats protected
Referenced by GetVideoBitrate(), and Process().
The documentation for this class was generated from the following files:
VideoPlayerVideo.h
VideoPlayerVideo.cpp