Kodi Documentation: WinMain.cpp File Reference
WinMain.cpp File Reference
#include "CompileInfo.h"
#include "ServiceBroker.h"
#include "application/AppEnvironment.h"
#include "application/AppParamParser.h"
#include "application/AppParams.h"
#include "platform/Environment.h"
#include "platform/xbmc.h"
#include "threads/Thread.h"
#include "utils/CharsetConverter.h"
#include "platform/win32/CharsetConverter.h"
#include "platform/win32/threads/Win32Exception.h"
#include <Objbase.h>
#include <WinSock2.h>
#include <dbghelp.h>
#include <mmsystem.h>
#include <shellapi.h>
Functions
LONG WINAPI CreateMiniDump (EXCEPTION_POINTERS *pEp)
template<typename... Args>
static void LogError (const wchar_t *format, Args &&... args)
Basic error reporting before the log subsystem is initialized.
static std::shared_ptr< CAppParams > ParseCommandLine ()
_Use_decl_annotations_ INT WINAPI WinMain (HINSTANCE, HINSTANCE, LPSTR, INT)
Variables
static bool isConsoleAttached {false}
Function Documentation
CreateMiniDump()
LONG WINAPI CreateMiniDump (EXCEPTION_POINTERS * pEp)
References win32_exception::write_minidump(), and win32_exception::write_stacktrace().
Referenced by WinMain().
LogError()
template<typename... Args> static void LogError (const wchar_t * format, Args &&... args) static
Basic error reporting before the log subsystem is initialized.
The message is formatted using printf and output to debugger and cmd.exe, as applicable.
Parameters
[in] format printf-style format string
[in] ... optional parameters for the format string.
References isConsoleAttached, and void().
Referenced by WinMain().
ParseCommandLine()
static std::shared_ptr< CAppParams > ParseCommandLine () static
References CAppParamParser::GetAppParams(), and CAppParamParser::Parse().
Referenced by WinMain().
WinMain()
_Use_decl_annotations_ INT WINAPI WinMain (HINSTANCE , HINSTANCE , LPSTR , INT)
References CloseHandle(), CreateMiniDump(), CCompileInfo::GetAppName(), GetLastError(), CCompileInfo::GetMajor(), CCompileInfo::GetMinor(), CCompileInfo::GetSCMID(), CCompileInfo::GetSuffix(), LogError(), ParseCommandLine(), win32_exception::set_platformDirectories(), win32_exception::set_version(), CAppEnvironment::SetUp(), win32_exception::ShouldHook(), CAppEnvironment::TearDown(), KODI::PLATFORM::WINDOWS::ToW(), CEnvironment::unsetenv(), and XBMC_Run().
Variable Documentation
isConsoleAttached
bool isConsoleAttached {false} static
Referenced by LogError().