Kodi Documentation: KODI::RETRO::CRenderBufferGuiTexture Class Reference
KODI::RETRO::CRenderBufferGuiTexture Class Reference
#include <RenderBufferGuiTexture.h>
Public Member Functions
CRenderBufferGuiTexture (SCALINGMETHOD scalingMethod)
~CRenderBufferGuiTexture () override=default
bool Allocate (AVPixelFormat format, unsigned int width, unsigned int height) override
size_t GetFrameSize () const override
uint8_t * GetMemory () override
bool UploadTexture () override
void BindToUnit (unsigned int unit) override
CTexture * GetTexture ()
Public Member Functions inherited from KODI::RETRO::CBaseRenderBuffer
CBaseRenderBuffer ()
~CBaseRenderBuffer () override=default
void Acquire () override
void Acquire (std::shared_ptr< IRenderBufferPool > pool) override
void Release () override
IRenderBufferPool * GetPool () override
DataAccess GetMemoryAccess () const override
DataAlignment GetMemoryAlignment () const override
Public Member Functions inherited from KODI::RETRO::IRenderBuffer
virtual ~IRenderBuffer ()=default
virtual void Update ()
virtual void ReleaseMemory ()
virtual void SetHeader (void *header)
AVPixelFormat GetFormat () const
unsigned int GetWidth () const
unsigned int GetHeight () const
bool IsLoaded () const
void SetLoaded (bool bLoaded)
bool IsRendered () const
void SetRendered (bool bRendered)
unsigned int GetRotation () const
void SetRotation (unsigned int rotationDegCCW)
Protected Member Functions
AVPixelFormat TranslateFormat (XB_FMT textureFormat)
TEXTURE_SCALING TranslateScalingMethod (SCALINGMETHOD scalingMethod)
Protected Attributes
SCALINGMETHOD m_scalingMethod
XB_FMT m_textureFormat = XB_FMT_UNKNOWN
std::unique_ptr< CTexture > m_texture
Protected Attributes inherited from KODI::RETRO::CBaseRenderBuffer
std::atomic_int m_refCount
std::shared_ptr< IRenderBufferPool > m_pool
Protected Attributes inherited from KODI::RETRO::IRenderBuffer
AVPixelFormat m_format = AV_PIX_FMT_NONE
unsigned int m_width = 0
unsigned int m_height = 0
bool m_bLoaded = false
bool m_bRendered = false
unsigned int m_rotationDegCCW = 0
Constructor & Destructor Documentation
CRenderBufferGuiTexture()
CRenderBufferGuiTexture::CRenderBufferGuiTexture (SCALINGMETHOD scalingMethod)
References m_textureFormat, and XB_FMT_A8R8G8B8.
~CRenderBufferGuiTexture()
KODI::RETRO::CRenderBufferGuiTexture::~CRenderBufferGuiTexture () override default
Member Function Documentation
Allocate()
bool CRenderBufferGuiTexture::Allocate (AVPixelFormat format, unsigned int width, unsigned int height) override virtual
Implements KODI::RETRO::IRenderBuffer.
References CTexture::CreateTexture(), KODI::RETRO::IRenderBuffer::m_format, KODI::RETRO::IRenderBuffer::m_height, m_scalingMethod, m_texture, m_textureFormat, KODI::RETRO::IRenderBuffer::m_width, TranslateFormat(), and TranslateScalingMethod().
BindToUnit()
void CRenderBufferGuiTexture::BindToUnit (unsigned int unit) override virtual
Reimplemented from KODI::RETRO::IRenderBuffer.
References m_texture.
Referenced by KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
GetFrameSize()
size_t CRenderBufferGuiTexture::GetFrameSize () const override virtual
Todo:
Remove me
Implements KODI::RETRO::IRenderBuffer.
References m_texture.
GetMemory()
uint8_t * CRenderBufferGuiTexture::GetMemory () override virtual
Implements KODI::RETRO::IRenderBuffer.
References m_texture.
GetTexture()
CTexture * KODI::RETRO::CRenderBufferGuiTexture::GetTexture () inline
References m_texture.
Referenced by KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
TranslateFormat()
AVPixelFormat CRenderBufferGuiTexture::TranslateFormat (XB_FMT textureFormat) protected
References XB_FMT_A8R8G8B8, and XB_FMT_RGBA8.
Referenced by Allocate().
TranslateScalingMethod()
TEXTURE_SCALING CRenderBufferGuiTexture::TranslateScalingMethod (SCALINGMETHOD scalingMethod) protected
References KODI::RETRO::LINEAR, LINEAR, KODI::RETRO::NEAREST, and NEAREST.
Referenced by Allocate().
UploadTexture()
bool CRenderBufferGuiTexture::UploadTexture () override virtual
Implements KODI::RETRO::IRenderBuffer.
References m_texture.
Member Data Documentation
m_scalingMethod
SCALINGMETHOD KODI::RETRO::CRenderBufferGuiTexture::m_scalingMethod protected
Referenced by Allocate().
m_texture
std::unique_ptr<CTexture> KODI::RETRO::CRenderBufferGuiTexture::m_texture protected
Referenced by Allocate(), BindToUnit(), GetFrameSize(), GetMemory(), GetTexture(), and UploadTexture().
m_textureFormat
XB_FMT KODI::RETRO::CRenderBufferGuiTexture::m_textureFormat = XB_FMT_UNKNOWN protected
Referenced by Allocate(), and CRenderBufferGuiTexture().
The documentation for this class was generated from the following files:
RenderBufferGuiTexture.h
RenderBufferGuiTexture.cpp