Kodi Documentation: CPictureThumbLoader Class Reference
CPictureThumbLoader Class Reference
#include <PictureThumbLoader.h>
Public Member Functions
CPictureThumbLoader ()
~CPictureThumbLoader () override
bool LoadItem (CFileItem *pItem) override
bool LoadItemCached (CFileItem *pItem) override
bool LoadItemLookup (CFileItem *pItem) override
void SetRegenerateThumbs (bool regenerate)
Public Member Functions inherited from CThumbLoader
CThumbLoader ()
~CThumbLoader () override
void OnLoaderStart () override
void OnLoaderFinish () override
virtual bool FillLibraryArt (CFileItem &item)
helper function to fill the art for a library item
virtual std::string GetCachedImage (const CFileItem &item, const std::string &type)
Checks whether the given item has an image listed in the texture database.
virtual void SetCachedImage (const CFileItem &item, const std::string &type, const std::string &image)
Associate an image with the given item in the texture database.
Public Member Functions inherited from CBackgroundInfoLoader
CBackgroundInfoLoader ()
~CBackgroundInfoLoader () override
void Load (CFileItemList &items)
bool IsLoading ()
void Run () override
void SetObserver (IBackgroundLoaderObserver *pObserver)
void SetProgressCallback (IProgressCallback *pCallback)
void StopThread ()
void StopAsync ()
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Static Public Member Functions
static void ProcessFoldersAndArchives (CFileItem *pItem)
Protected Member Functions
void OnLoaderFinish () override
Private Attributes
bool m_regenerateThumbs
Additional Inherited Members
Protected Attributes inherited from CThumbLoader
CTextureDatabase * m_textureDatabase
Protected Attributes inherited from CBackgroundInfoLoader
CFileItemList * m_pVecItems {nullptr}
std::vector< CFileItemPtr > m_vecItems
CCriticalSection m_lock
volatile bool m_bIsLoading {false}
volatile bool m_bStop {true}
CThread * m_thread {nullptr}
IBackgroundLoaderObserver * m_pObserver {nullptr}
IProgressCallback * m_pProgressCallback {nullptr}
Constructor & Destructor Documentation
CPictureThumbLoader()
CPictureThumbLoader::CPictureThumbLoader ()
References m_regenerateThumbs.
~CPictureThumbLoader()
CPictureThumbLoader::~CPictureThumbLoader () override
References CBackgroundInfoLoader::StopThread().
Member Function Documentation
LoadItem()
bool CPictureThumbLoader::LoadItem (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References LoadItemCached(), and LoadItemLookup().
Referenced by CGUIWindowSlideShow::GetPicturePath().
LoadItemCached()
bool CPictureThumbLoader::LoadItemCached (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References CTextureDatabase::ClearTextureForPath(), CDatabase::Close(), KODI::ART::FillInDefaultIcon(), CGUIListItem::GetArt(), CThumbLoader::GetCachedImage(), CFileItem::GetPath(), CServiceBroker::GetTextureCache(), CGUIListItem::HasArt(), CFileItem::IsCBR(), CFileItem::IsCBZ(), CFileItem::IsParentFolder(), CFileItem::IsPicture(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsRAR(), CFileItem::IsZIP(), CVideoThumbLoader::LoadItem(), CFileItem::m_bIsShareOrDrive, m_regenerateThumbs, CThumbLoader::m_textureDatabase, CTextureDatabase::Open(), CGUIListItem::SetArt(), and IMAGE_FILES::URLFromFile().
Referenced by LoadItem().
LoadItemLookup()
bool CPictureThumbLoader::LoadItemLookup (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
Referenced by LoadItem().
OnLoaderFinish()
void CPictureThumbLoader::OnLoaderFinish () override protected virtual
Reimplemented from CBackgroundInfoLoader.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_REFRESH_THUMBS, m_regenerateThumbs, CThumbLoader::OnLoaderFinish(), and CGUIWindowManager::SendMessage().
ProcessFoldersAndArchives()
void CPictureThumbLoader::ProcessFoldersAndArchives (CFileItem * pItem) static
References URIUtils::AddFileToFolder(), URIUtils::CreateArchivePath(), XFILE::DIR_FLAG_NO_FILE_DIRS, CFileUtils::Exists(), KODI::ART::FillInDefaultIcon(), CURL::Get(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), XFILE::CMultiPathDirectory::GetFirstPath(), CFileItem::GetPath(), CServiceBroker::GetTextureCache(), CFileItem::GetURL(), CGUIListItem::HasArt(), CFileItem::IsCBR(), CFileItem::IsCBZ(), CFileItemList::IsEmpty(), CFileItem::IsMultiPath(), CFileItem::IsParentFolder(), CFileItem::IsPath(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsPlugin(), CGUIListItem::m_bIsFolder, CFileItem::m_bIsShareOrDrive, CTextureDatabase::Open(), ProcessFoldersAndArchives(), CFileItemList::Randomize(), CFileItemList::Remove(), URIUtils::ReplaceExtension(), CGUIListItem::SetArt(), CTextureDatabase::SetTextureForPath(), CFileItemList::Size(), CFileItemList::Sort(), SortByLabel, SortOrderAscending, and IMAGE_FILES::URLFromFile().
Referenced by CGUIWindowPictures::OnItemLoaded(), and ProcessFoldersAndArchives().
SetRegenerateThumbs()
void CPictureThumbLoader::SetRegenerateThumbs (bool regenerate) inline
References m_regenerateThumbs.
Referenced by CGUIWindowPictures::OnRegenerateThumbs().
Member Data Documentation
m_regenerateThumbs
bool CPictureThumbLoader::m_regenerateThumbs private
Referenced by CPictureThumbLoader(), LoadItemCached(), OnLoaderFinish(), and SetRegenerateThumbs().
The documentation for this class was generated from the following files:
PictureThumbLoader.h
PictureThumbLoader.cpp