Kodi Documentation: CGetSongInfoJob Class Reference
CGetSongInfoJob Class Reference
Public Member Functions
~CGetSongInfoJob (void) override=default
bool DoWork () override
Main workhorse function of CJob instances.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual const char * GetType () const
Function that returns the type of job.
virtual bool operator== (const CJob *job) const
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Constructor & Destructor Documentation
~CGetSongInfoJob()
CGetSongInfoJob::~CGetSongInfoJob (void) override default
Member Function Documentation
DoWork()
bool CGetSongInfoJob::DoWork () inline override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CDatabase::Close(), CGUIDialogSongInfo::FetchComplete(), MUSIC_UTILS::FillArtTypesList(), CMusicDatabase::GetAlbumPath(), CGUIDialogSongInfo::GetCurrentListItem(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialogSongInfo::IsCancelled(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CMusicThumbLoader::LoadItem(), CMusicDatabase::Open(), CGUIDialogSongInfo::SetArtTypeList(), and WINDOW_DIALOG_SONG_INFO.
The documentation for this class was generated from the following file:
GUIDialogSongInfo.cpp