Kodi Documentation: KODI::PLAYLIST::CSmartPlaylist Class Reference
KODI::PLAYLIST::CSmartPlaylist Class Reference
#include <SmartPlayList.h>
Public Member Functions
CSmartPlaylist ()
~CSmartPlaylist () override=default
bool Load (const CURL &url)
bool Load (const std::string &path)
bool Load (const CVariant &obj)
bool LoadFromXml (const std::string &xml)
bool LoadFromJson (const std::string &json)
bool Save (const std::string &path) const
bool Save (CVariant &obj, bool full=true) const
bool SaveAsJson (std::string &json, bool full=true) const
bool OpenAndReadName (const CURL &url)
bool LoadFromXML (const TiXmlNode *root, const std::string &encoding="UTF-8")
void Reset ()
void SetName (const std::string &name)
void SetType (const std::string &type)
const std::string & GetName () const
const std::string & GetType () const
bool IsVideoType () const
bool IsMusicType () const
void SetMatchAllRules (bool matchAll)
bool GetMatchAllRules () const
void SetLimit (unsigned int limit)
unsigned int GetLimit () const
void SetOrder (SortBy order)
SortBy GetOrder () const
void SetOrderAscending (bool orderAscending)
bool GetOrderAscending () const
SortOrder GetOrderDirection () const
void SetOrderAttributes (SortAttribute attributes)
SortAttribute GetOrderAttributes () const
void SetGroup (const std::string &group)
const std::string & GetGroup () const
void SetGroupMixed (bool mixed)
bool IsGroupMixed () const
std::string GetWhereClause (const CDatabase &db, std::set< std::string > &referencedPlaylists) const
get the where clause for a playlist We handle playlists inside playlists separately in order to ensure we don't introduce infinite loops by playlist A including playlist B which also (perhaps via other playlists) then includes playlistA.
void GetVirtualFolders (std::vector< std::string > &virtualFolders) const
std::string GetSaveLocation () const
bool IsEmpty (bool ignoreSortAndLimit=true) const
CDatabaseQueryRule * CreateRule () const override
CDatabaseQueryRuleCombination * CreateCombination () const override
Public Member Functions inherited from IDatabaseQueryRuleFactory
virtual ~IDatabaseQueryRuleFactory ()=default
Static Public Member Functions
static void GetAvailableFields (const std::string &type, std::vector< std::string > &fieldList)
static bool IsVideoType (const std::string &type)
static bool IsMusicType (const std::string &type)
static bool CheckTypeCompatibility (const std::string &typeLeft, const std::string &typeRight)
Private Member Functions
const TiXmlNode * readName (const TiXmlNode *root)
const TiXmlNode * readNameFromPath (const CURL &url)
const TiXmlNode * readNameFromXml (const std::string &xml)
bool load (const TiXmlNode *root)
Private Attributes
CSmartPlaylistRuleCombination m_ruleCombination
std::string m_playlistName
std::string m_playlistType
unsigned int m_limit
SortBy m_orderField
SortOrder m_orderDirection
SortAttribute m_orderAttributes
std::string m_group
bool m_groupMixed
CXBMCTinyXML m_xmlDoc
Friends
class ::CGUIDialogSmartPlaylistEditor
class ::CGUIDialogMediaFilter
Constructor & Destructor Documentation
CSmartPlaylist()
KODI::PLAYLIST::CSmartPlaylist::CSmartPlaylist ()
References Reset().
~CSmartPlaylist()
KODI::PLAYLIST::CSmartPlaylist::~CSmartPlaylist () override default
Member Function Documentation
CheckTypeCompatibility()
bool KODI::PLAYLIST::CSmartPlaylist::CheckTypeCompatibility (const std::string & typeLeft, const std::string & typeRight) static
Referenced by KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetVirtualFolders(), and CGUIDialogSmartPlaylistRule::OnBrowse().
CreateCombination()
CDatabaseQueryRuleCombination * KODI::PLAYLIST::CSmartPlaylist::CreateCombination () const override virtual
Implements IDatabaseQueryRuleFactory.
CreateRule()
CDatabaseQueryRule * KODI::PLAYLIST::CSmartPlaylist::CreateRule () const override virtual
Implements IDatabaseQueryRuleFactory.
GetAvailableFields()
void KODI::PLAYLIST::CSmartPlaylist::GetAvailableFields (const std::string & type, std::vector< std::string > & fieldList) static
References KODI::PLAYLIST::fields, and KODI::PLAYLIST::CSmartPlaylistRule::GetFields().
Referenced by JSONRPC::CJSONRPC::Initialize().
GetGroup()
const std::string & KODI::PLAYLIST::CSmartPlaylist::GetGroup () const inline
References m_group.
Referenced by CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), CGUIDialogSmartPlaylistEditor::OnType(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
GetLimit()
unsigned int KODI::PLAYLIST::CSmartPlaylist::GetLimit () const inline
References m_limit.
Referenced by CMusicDatabase::GetFilter(), and CVideoDatabase::GetFilter().
GetMatchAllRules()
bool KODI::PLAYLIST::CSmartPlaylist::GetMatchAllRules () const inline
References CDatabaseQueryRuleCombination::CombinationAnd, CDatabaseQueryRuleCombination::GetType(), and m_ruleCombination.
GetName()
const std::string & KODI::PLAYLIST::CSmartPlaylist::GetName () const inline
References m_playlistName.
Referenced by CApplication::PlayMedia().
GetOrder()
SortBy KODI::PLAYLIST::CSmartPlaylist::GetOrder () const inline
References m_orderField.
Referenced by CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), and KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::Modify().
GetOrderAscending()
bool KODI::PLAYLIST::CSmartPlaylist::GetOrderAscending () const inline
References m_orderDirection, and SortOrderDescending.
Referenced by CMusicDatabase::GetFilter().
GetOrderAttributes()
SortAttribute KODI::PLAYLIST::CSmartPlaylist::GetOrderAttributes () const inline
References m_orderAttributes.
GetOrderDirection()
SortOrder KODI::PLAYLIST::CSmartPlaylist::GetOrderDirection () const inline
References m_orderDirection.
Referenced by CVideoDatabase::GetFilter(), and KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::Modify().
GetSaveLocation()
std::string KODI::PLAYLIST::CSmartPlaylist::GetSaveLocation () const
References IsMusicType(), and m_playlistType.
Referenced by CGUIDialogSmartPlaylistEditor::OnOK().
GetType()
const std::string & KODI::PLAYLIST::CSmartPlaylist::GetType () const inline
References m_playlistType.
Referenced by XFILE::CSmartPlaylistDirectory::GetDirectory(), CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), GetVirtualFolders(), GetWhereClause(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), CGUIDialogSmartPlaylistEditor::OnInitWindow(), CGUIDialogSmartPlaylistEditor::OnMessage(), CGUIDialogSmartPlaylistEditor::OnOrder(), CGUIDialogSmartPlaylistEditor::OnRuleAdd(), CGUIDialogSmartPlaylistEditor::OnRuleList(), CGUIDialogSmartPlaylistEditor::OnType(), CApplication::PlayMedia(), CGUIDialogSmartPlaylistEditor::UpdateButtons(), CMusicDbUrl::validateOption(), and CVideoDbUrl::validateOption().
GetVirtualFolders()
void KODI::PLAYLIST::CSmartPlaylist::GetVirtualFolders (std::vector< std::string > & virtualFolders) const
References GetType(), KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetVirtualFolders(), and m_ruleCombination.
GetWhereClause()
std::string KODI::PLAYLIST::CSmartPlaylist::GetWhereClause (const CDatabase & db, std::set< std::string > & referencedPlaylists) const
get the where clause for a playlist We handle playlists inside playlists separately in order to ensure we don't introduce infinite loops by playlist A including playlist B which also (perhaps via other playlists) then includes playlistA.
Parameters
db the database to use to format up results
referencedPlaylists a set of playlists to know when we reach a cycle
needWhere whether we need to prepend the where clause with "WHERE "
References GetType(), KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetWhereClause(), and m_ruleCombination.
Referenced by CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), and CGUIDialogMediaFilter::GetItems().
IsEmpty()
bool KODI::PLAYLIST::CSmartPlaylist::IsEmpty (bool ignoreSortAndLimit = true) const
References CDatabaseQueryRuleCombination::empty(), m_limit, m_orderDirection, m_orderField, m_ruleCombination, SortByNone, and SortOrderNone.
Referenced by CGUIMediaWindow::GetAdvanceFilteredItems(), XFILE::CSmartPlaylistDirectory::GetDirectory(), CGUIMediaWindow::GoParentFolder(), CGUIMediaWindow::IsFiltered(), and CGUIMediaWindow::OnClick().
IsGroupMixed()
bool KODI::PLAYLIST::CSmartPlaylist::IsGroupMixed () const inline
References m_groupMixed.
Referenced by CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), CGUIDialogSmartPlaylistEditor::OnGroupMixed(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
IsMusicType() [1/2]
bool KODI::PLAYLIST::CSmartPlaylist::IsMusicType () const
References IsMusicType(), and m_playlistType.
Referenced by XFILE::CSmartPlaylistDirectory::GetPlaylistByName(), GetSaveLocation(), IsMusicType(), and CGUIDialogSmartPlaylistRule::OnBrowse().
IsMusicType() [2/2]
bool KODI::PLAYLIST::CSmartPlaylist::IsMusicType (const std::string & type) static
IsVideoType() [1/2]
bool KODI::PLAYLIST::CSmartPlaylist::IsVideoType () const
References IsVideoType(), and m_playlistType.
Referenced by IsVideoType(), and CGUIDialogSmartPlaylistRule::OnBrowse().
IsVideoType() [2/2]
bool KODI::PLAYLIST::CSmartPlaylist::IsVideoType (const std::string & type) static
Load() [1/3]
bool KODI::PLAYLIST::CSmartPlaylist::Load (const CURL & url)
References load(), and readNameFromPath().
Referenced by LoadFromJson(), and CGUIDialogSmartPlaylistEditor::OnMessage().
Load() [2/3]
bool KODI::PLAYLIST::CSmartPlaylist::Load (const CVariant & obj)
References CVariant::asBoolean(), CVariant::asString(), CVariant::asUnsignedInteger(), CVariant::isBoolean(), CVariant::isInteger(), CVariant::isMember(), CVariant::isObject(), CVariant::isString(), CVariant::isUnsignedInteger(), CDatabaseQueryRuleCombination::Load(), m_group, m_groupMixed, m_limit, m_orderAttributes, m_orderDirection, m_orderField, m_playlistName, m_playlistType, m_ruleCombination, SortAttributeIgnoreFolders, SortAttributeNone, SortOrderAscending, SortOrderDescending, and KODI::PLAYLIST::CSmartPlaylistRule::TranslateOrder().
Load() [3/3]
bool KODI::PLAYLIST::CSmartPlaylist::Load (const std::string & path)
References load(), and readNameFromPath().
load()
bool KODI::PLAYLIST::CSmartPlaylist::load (const TiXmlNode * root) private
References LoadFromXML(), and root.
Referenced by Load(), Load(), and LoadFromXml().
LoadFromJson()
bool KODI::PLAYLIST::CSmartPlaylist::LoadFromJson (const std::string & json)
References Load(), and CJSONVariantParser::Parse().
Referenced by CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::Modify(), CGUIMediaWindow::UpdateFilterPath(), CMusicDbUrl::validateOption(), and CVideoDbUrl::validateOption().
LoadFromXml()
bool KODI::PLAYLIST::CSmartPlaylist::LoadFromXml (const std::string & xml)
References load(), and readNameFromXml().
LoadFromXML()
bool KODI::PLAYLIST::CSmartPlaylist::LoadFromXML (const TiXmlNode * root, const std::string & encoding = "UTF-8")
References KODI::PLAYLIST::CSmartPlaylistRuleCombination::AddRule(), CDatabaseQueryRuleCombination::CombinationAnd, CDatabaseQueryRuleCombination::CombinationOr, XMLUtils::GetString(), XMLUtils::GetUInt(), CDatabaseQueryRule::Load(), m_group, m_groupMixed, m_limit, m_orderAttributes, m_orderDirection, m_orderField, m_ruleCombination, root, CDatabaseQueryRuleCombination::SetType(), SortAttributeIgnoreFolders, SortAttributeNone, SortOrderAscending, SortOrderDescending, and KODI::PLAYLIST::CSmartPlaylistRule::TranslateOrder().
Referenced by load().
OpenAndReadName()
bool KODI::PLAYLIST::CSmartPlaylist::OpenAndReadName (const CURL & url)
References m_playlistName, and readNameFromPath().
Referenced by CApplication::PlayMedia().
readName()
const TiXmlNode * KODI::PLAYLIST::CSmartPlaylist::readName (const TiXmlNode * root) private
References XMLUtils::GetString(), CLog::Log(), LOGERROR, m_playlistName, m_playlistType, and root.
Referenced by readNameFromPath(), and readNameFromXml().
readNameFromPath()
const TiXmlNode * KODI::PLAYLIST::CSmartPlaylist::readNameFromPath (const CURL & url) private
References CURL::Get(), CURL::GetRedacted(), CUtil::GetTitleFromPath(), URIUtils::HasExtension(), CLog::Log(), LOGERROR, m_playlistName, m_xmlDoc, readName(), URIUtils::RemoveExtension(), and root.
Referenced by Load(), Load(), and OpenAndReadName().
readNameFromXml()
const TiXmlNode * KODI::PLAYLIST::CSmartPlaylist::readNameFromXml (const std::string & xml) private
References CLog::Log(), LOGERROR, m_xmlDoc, CXBMCTinyXML::Parse(), readName(), and root.
Referenced by LoadFromXml().
Reset()
void KODI::PLAYLIST::CSmartPlaylist::Reset ()
References CDatabaseQueryRuleCombination::clear(), m_group, m_groupMixed, m_limit, m_orderAttributes, m_orderDirection, m_orderField, m_playlistType, m_ruleCombination, SortAttributeNone, SortByNone, and SortOrderNone.
Referenced by CSmartPlaylist(), CGUIMediaWindow::GetDirectory(), CGUIDialogMediaFilter::OnMessage(), CGUIDialogSmartPlaylistEditor::OnMessage(), CGUIMediaWindow::OnMessage(), and CGUIMediaWindow::UpdateFilterPath().
Save() [1/2]
bool KODI::PLAYLIST::CSmartPlaylist::Save (const std::string & path) const
References CDatabaseQueryRuleCombination::CombinationAnd, CDatabaseQueryRuleCombination::GetType(), m_group, m_groupMixed, m_limit, m_orderAttributes, m_orderDirection, m_orderField, m_playlistName, m_playlistType, m_ruleCombination, CDatabaseQueryRuleCombination::Save(), CXBMCTinyXML::SaveFile(), XMLUtils::SetInt(), XMLUtils::SetString(), SortAttributeIgnoreFolders, SortByNone, SortOrderDescending, and KODI::PLAYLIST::CSmartPlaylistRule::TranslateOrder().
Referenced by CGUIDialogSmartPlaylistEditor::OnOK(), and SaveAsJson().
Save() [2/2]
bool KODI::PLAYLIST::CSmartPlaylist::Save (CVariant & obj, bool full = true) const
References CVariant::clear(), full, m_group, m_groupMixed, m_limit, m_orderAttributes, m_orderDirection, m_orderField, m_playlistType, m_ruleCombination, CDatabaseQueryRuleCombination::Save(), SortAttributeIgnoreFolders, SortByNone, SortOrderDescending, KODI::PLAYLIST::CSmartPlaylistRule::TranslateOrder(), CVariant::type(), CVariant::VariantTypeConstNull, and CVariant::VariantTypeObject.
SaveAsJson()
bool KODI::PLAYLIST::CSmartPlaylist::SaveAsJson (std::string & json, bool full = true) const
References full, Save(), CVariant::VariantTypeObject, and CJSONVariantWriter::Write().
Referenced by XFILE::CSmartPlaylistDirectory::GetDirectory().
SetGroup()
void KODI::PLAYLIST::CSmartPlaylist::SetGroup (const std::string & group) inline
References m_group.
Referenced by XFILE::CSmartPlaylistDirectory::GetDirectory(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), and CGUIDialogSmartPlaylistEditor::OnType().
SetGroupMixed()
void KODI::PLAYLIST::CSmartPlaylist::SetGroupMixed (bool mixed) inline
References m_groupMixed.
Referenced by CGUIDialogSmartPlaylistEditor::OnGroupBy(), and CGUIDialogSmartPlaylistEditor::OnGroupMixed().
SetLimit()
void KODI::PLAYLIST::CSmartPlaylist::SetLimit (unsigned int limit) inline
References m_limit.
SetMatchAllRules()
void KODI::PLAYLIST::CSmartPlaylist::SetMatchAllRules (bool matchAll) inline
References CDatabaseQueryRuleCombination::CombinationAnd, CDatabaseQueryRuleCombination::CombinationOr, m_ruleCombination, and CDatabaseQueryRuleCombination::SetType().
SetName()
void KODI::PLAYLIST::CSmartPlaylist::SetName (const std::string & name)
References m_playlistName, and name.
SetOrder()
void KODI::PLAYLIST::CSmartPlaylist::SetOrder (SortBy order) inline
References m_orderField.
SetOrderAscending()
void KODI::PLAYLIST::CSmartPlaylist::SetOrderAscending (bool orderAscending) inline
References m_orderDirection, SortOrderAscending, and SortOrderDescending.
SetOrderAttributes()
void KODI::PLAYLIST::CSmartPlaylist::SetOrderAttributes (SortAttribute attributes) inline
References m_orderAttributes.
SetType()
void KODI::PLAYLIST::CSmartPlaylist::SetType (const std::string & type)
References m_playlistType.
Referenced by XFILE::CSmartPlaylistDirectory::GetDirectory(), CGUIDialogSmartPlaylistEditor::OnInitWindow(), CGUIDialogMediaFilter::OnMessage(), CGUIDialogSmartPlaylistEditor::OnType(), CGUIDialogMediaFilter::SetPath(), and CGUIMediaWindow::Update().
Friends And Related Symbol Documentation
::CGUIDialogMediaFilter
friend class ::CGUIDialogMediaFilter friend
::CGUIDialogSmartPlaylistEditor
friend class ::CGUIDialogSmartPlaylistEditor friend
Member Data Documentation
m_group
std::string KODI::PLAYLIST::CSmartPlaylist::m_group private
Referenced by GetGroup(), Load(), LoadFromXML(), Reset(), Save(), Save(), and SetGroup().
m_groupMixed
bool KODI::PLAYLIST::CSmartPlaylist::m_groupMixed private
Referenced by IsGroupMixed(), Load(), LoadFromXML(), Reset(), Save(), Save(), and SetGroupMixed().
m_limit
unsigned int KODI::PLAYLIST::CSmartPlaylist::m_limit private
Referenced by GetLimit(), IsEmpty(), Load(), LoadFromXML(), CGUIDialogSmartPlaylistEditor::OnLimit(), Reset(), Save(), Save(), SetLimit(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
m_orderAttributes
SortAttribute KODI::PLAYLIST::CSmartPlaylist::m_orderAttributes private
Referenced by GetOrderAttributes(), Load(), LoadFromXML(), Reset(), Save(), Save(), and SetOrderAttributes().
m_orderDirection
SortOrder KODI::PLAYLIST::CSmartPlaylist::m_orderDirection private
Referenced by GetOrderAscending(), GetOrderDirection(), IsEmpty(), Load(), LoadFromXML(), CGUIDialogSmartPlaylistEditor::OnOrderDirection(), Reset(), Save(), Save(), SetOrderAscending(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
m_orderField
SortBy KODI::PLAYLIST::CSmartPlaylist::m_orderField private
Referenced by GetOrder(), IsEmpty(), Load(), LoadFromXML(), CGUIDialogSmartPlaylistEditor::OnOrder(), Reset(), Save(), Save(), SetOrder(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
m_playlistName
std::string KODI::PLAYLIST::CSmartPlaylist::m_playlistName private
Referenced by GetName(), Load(), CGUIDialogSmartPlaylistEditor::OnName(), CGUIDialogSmartPlaylistEditor::OnOK(), OpenAndReadName(), readName(), readNameFromPath(), Save(), SetName(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
m_playlistType
std::string KODI::PLAYLIST::CSmartPlaylist::m_playlistType private
Referenced by GetSaveLocation(), GetType(), IsMusicType(), IsVideoType(), Load(), readName(), Reset(), Save(), Save(), and SetType().
m_ruleCombination
CSmartPlaylistRuleCombination KODI::PLAYLIST::CSmartPlaylist::m_ruleCombination private
Referenced by CGUIDialogMediaFilter::AddRule(), CGUIDialogMediaFilter::DeleteRule(), CGUIDialogMediaFilter::GetItems(), GetMatchAllRules(), GetVirtualFolders(), GetWhereClause(), CGUIDialogMediaFilter::InitializeSettings(), IsEmpty(), Load(), LoadFromXML(), CGUIDialogSmartPlaylistEditor::OnMatch(), CGUIDialogSmartPlaylistEditor::OnPopupMenu(), CGUIDialogSmartPlaylistEditor::OnRuleAdd(), CGUIDialogSmartPlaylistEditor::OnRuleList(), CGUIDialogSmartPlaylistEditor::OnRuleRemove(), Reset(), Save(), Save(), SetMatchAllRules(), CGUIDialogSmartPlaylistEditor::UpdateButtons(), and CGUIDialogSmartPlaylistEditor::UpdateRuleControlButtons().
m_xmlDoc
CXBMCTinyXML KODI::PLAYLIST::CSmartPlaylist::m_xmlDoc private
Referenced by readNameFromPath(), and readNameFromXml().
The documentation for this class was generated from the following files:
SmartPlayList.h
SmartPlayList.cpp