Kodi Documentation: CVideoLibraryRefreshingJob Class Reference
CVideoLibraryRefreshingJob Class Reference
Video library job implementation for refreshing a single item.
#include <VideoLibraryRefreshingJob.h>
Public Member Functions
CVideoLibraryRefreshingJob (std::shared_ptr< CFileItem > item, bool forceRefresh, bool refreshAll, bool ignoreNfo=false, const std::string &searchTitle="")
Creates a new video library cleaning job for the given paths.
~CVideoLibraryRefreshingJob () override
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
Public Member Functions inherited from CVideoLibraryProgressJob
~CVideoLibraryProgressJob () override
bool DoWork () override
Main workhorse function of CJob instances.
Public Member Functions inherited from CProgressJob
~CProgressJob () override
bool ShouldCancel (unsigned int progress, unsigned int total) const override
Function for longer jobs to report progress and check whether they have been cancelled.
bool DoModal ()
Executes the job showing a modal progress dialog.
void SetProgressIndicators (CGUIDialogProgressBarHandle *progressBar, CGUIDialogProgress *progressDialog, bool updateProgress=true, bool updateInformation=true)
Sets the given progress indicators to be used during execution of the job.
bool HasProgressIndicator () const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
Public Member Functions inherited from CVideoLibraryJob
~CVideoLibraryJob () override
virtual bool CanBeCancelled () const
Whether the job can be cancelled or not.
virtual bool Cancel ()
Tries to cancel the running job.
Protected Member Functions
bool Work (CVideoDatabase &db) override
Worker method to be implemented by an actual implementation.
Protected Member Functions inherited from CVideoLibraryProgressJob
CVideoLibraryProgressJob (CGUIDialogProgressBarHandle *progressBar)
Protected Member Functions inherited from CProgressJob
CProgressJob ()
CProgressJob (CGUIDialogProgressBarHandle *progressBar)
bool IsModal () const
Whether the job is being run modally or in the background.
CGUIDialogProgressBarHandle * GetProgressBar () const
Returns the progress bar indicating the progress of the job.
void SetProgressBar (CGUIDialogProgressBarHandle *progress)
Sets the progress bar indicating the progress of the job.
CGUIDialogProgress * GetProgressDialog () const
Returns the progress dialog indicating the progress of the job.
void SetProgressDialog (CGUIDialogProgress *progressDialog)
Sets the progress bar indicating the progress of the job.
bool GetAutoClose ()
Whether to automatically close the progress indicator in MarkFinished().
void SetAutoClose (bool autoClose)
Set whether to automatically close the progress indicator in MarkFinished().
bool GetUpdateProgress ()
Whether to update the progress bar or not.
void SetUpdateProgress (bool updateProgress)
Set whether to update the progress bar or not.
bool GetUpdateInformation ()
Whether to update the progress information or not.
void SetUpdateInformation (bool updateInformation)
Set whether to update the progress information or not.
void ShowProgressDialog () const
Makes sure that the modal dialog is being shown.
void SetTitle (const std::string &title)
Sets the given title as the title of the progress bar.
void SetText (const std::string &text)
Sets the given text as the description of the progress bar.
void SetProgress (float percentage) const
Sets the progress of the progress bar to the given value in percentage.
void SetProgress (int currentStep, int totalSteps) const
Sets the progress of the progress bar to the given value.
void MarkFinished ()
Marks the progress as finished by setting it to 100%.
bool IsCancelled () const
Checks if the progress dialog has been cancelled.
Protected Member Functions inherited from CVideoLibraryJob
CVideoLibraryJob ()
Private Attributes
std::shared_ptr< CFileItem > m_item
bool m_forceRefresh
bool m_refreshAll
bool m_ignoreNfo
std::string m_searchTitle
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Detailed Description
Video library job implementation for refreshing a single item.
Constructor & Destructor Documentation
CVideoLibraryRefreshingJob()
CVideoLibraryRefreshingJob::CVideoLibraryRefreshingJob (std::shared_ptr< CFileItem > item, bool forceRefresh, bool refreshAll, bool ignoreNfo = false, const std::string & searchTitle = "")
Creates a new video library cleaning job for the given paths.
Parameters
[in,out] item Video item to be refreshed
[in] forceRefresh Whether to force a complete refresh (including NFO or internet lookup)
[in] refreshAll Whether to refresh all sub-items (in case of a tvshow)
[in] ignoreNfo Whether or not to ignore local NFO files
[in] searchTitle Title to use for the search (instead of determining it from the item's filename/path)
~CVideoLibraryRefreshingJob()
CVideoLibraryRefreshingJob::~CVideoLibraryRefreshingJob () override default
Member Function Documentation
GetType()
const char * CVideoLibraryRefreshingJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CVideoLibraryProgressJob.
Referenced by operator==().
operator==()
bool CVideoLibraryRefreshingJob::operator== (const CJob * job) const override virtual
Reimplemented from CVideoLibraryProgressJob.
References CJob::GetType(), GetType(), and m_item.
Work()
bool CVideoLibraryRefreshingJob::Work (CVideoDatabase & db) override protected virtual
Worker method to be implemented by an actual implementation.
Parameters
[in] db Already open video database to be used for interaction
Returns
True if the process succeeded, false otherwise
Implements CVideoLibraryJob.
References CFileItemList::Add(), CGUIDialogSelect::Add(), CScraperUrl::Clear(), CDatabase::Close(), CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_TVSHOWS, KODI::VIDEO::CVideoInfoTagLoaderFactory::CreateLoader(), DEFAULT_VERSION, CVideoDatabase::DeleteDetailsForTvShow(), CVideoDatabase::DeleteEpisode(), CVideoDatabase::DeleteMovie(), CVideoDatabase::DeleteMusicVideo(), CVideoDatabase::DeleteSeason(), CVideoDatabase::DeleteTvShow(), KODI::VIDEO::CVideoInfoScanner::DownloadFailed(), CGUIDialogSelect::EnableButton(), CInfoScanner::ERROR_NFO, CVideoInfoDownloader::FindMovie(), CInfoScanner::FULL_NFO, g_localizeStrings, CLocalizeStrings::Get(), CVideoTagLoaderPlugin::GetArt(), URIUtils::GetDirectory(), CVideoDatabase::GetEpisodeInfo(), CScraperUrl::GetFirstThumbUrl(), CServiceBroker::GetGUI(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMusicVideoInfo(), URIUtils::GetParentPath(), CVideoDatabase::GetPathsLinkedToTvShow(), CProgressJob::GetProgressDialog(), CVideoDatabase::GetScraperForPath(), CVideoDatabase::GetSeasonInfo(), CGUIDialogSelect::GetSelectedItem(), CScraperUrl::GetTitle(), CVideoDatabase::GetTvShowInfo(), CGUIComponent::GetWindowManager(), CUtil::HasFilenameIdentifier(), CScraperUrl::HasUrls(), CTextureDatabase::InvalidateCachedTexture(), CGUIDialogSelect::IsButtonPressed(), CProgressJob::IsCancelled(), XFILE::CPluginDirectory::IsMediaLibraryScanningAllowed(), CMediaTypes::IsMediaType(), CProgressJob::IsModal(), URIUtils::IsPlugin(), CLog::Log(), LOGDEBUG, LOGINFO, m_forceRefresh, m_ignoreNfo, CVideoInfoTag::m_iSeason, m_item, m_refreshAll, m_searchTitle, CVideoInfoTag::m_type, CProgressJob::MarkFinished(), MediaTypeSeason, MediaTypeTvShow, CInfoScanner::NO_NFO, CTextureDatabase::Open(), CGUIDialog::Open(), KODI::VIDEO::SScanSettings::parent_name, KODI::VIDEO::SScanSettings::parent_name_root, CGUIDialogSelect::Reset(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), CGUIDialogBoxBase::SetHeading(), CFileItem::SetPath(), CProgressJob::SetProgress(), CProgressJob::SetText(), CProgressJob::SetTitle(), CGUIDialogYesNo::ShowAndGetInput(), CGUIKeyboardFactory::ShowAndGetInput(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), ADDON::TranslateContent(), CVideoDatabase::UpdateAssetsOwner(), CInfoScanner::URL_NFO, and WINDOW_DIALOG_SELECT.
Member Data Documentation
m_forceRefresh
bool CVideoLibraryRefreshingJob::m_forceRefresh private
Referenced by Work().
m_ignoreNfo
bool CVideoLibraryRefreshingJob::m_ignoreNfo private
Referenced by Work().
m_item
std::shared_ptr<CFileItem> CVideoLibraryRefreshingJob::m_item private
Referenced by operator==(), and Work().
m_refreshAll
bool CVideoLibraryRefreshingJob::m_refreshAll private
Referenced by Work().
m_searchTitle
std::string CVideoLibraryRefreshingJob::m_searchTitle private
Referenced by Work().
The documentation for this class was generated from the following files:
VideoLibraryRefreshingJob.h
VideoLibraryRefreshingJob.cpp