Kodi Documentation: CRendererVDPAU Class Reference
CRendererVDPAU Class Reference
#include <RendererVDPAU.h>
Public Member Functions
CRendererVDPAU ()
~CRendererVDPAU () override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
void ReleaseBuffer (int idx) override
bool ConfigChanged (const VideoPicture &picture) override
bool NeedBuffer (int idx) override
bool Flush (bool saveBuffers) override
bool Supports (ERENDERFEATURE feature) const override
bool Supports (ESCALINGMETHOD method) const override
Public Member Functions inherited from CLinuxRendererGL
CLinuxRendererGL ()
~CLinuxRendererGL () override
bool IsConfigured () override
void AddVideoPicture (const VideoPicture &picture, int index) override
void UnInit () override
void SetBufferSize (int numBuffers) override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
void Update () override
bool RenderCapture (int index, CRenderCapture *capture) override
CRenderInfo GetRenderInfo () override
bool SupportsMultiPassRendering () override
CRenderCapture * GetRenderCapture () override
Public Member Functions inherited from CBaseRenderer
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool IsPictureHW (const VideoPicture &picture)
virtual bool IsGuiLayer ()
virtual bool WantsDoublePass ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
virtual DEBUG_INFO_VIDEO GetDebugInfo (int idx)
Static Public Member Functions
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Static Public Member Functions inherited from CLinuxRendererGL
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Static Public Member Functions inherited from CBaseRenderer
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
bool LoadShadersHook () override
bool RenderHook (int idx) override
void AfterRenderHook (int idx) override
bool UploadTexture (int index) override
void DeleteTexture (int index) override
bool CreateTexture (int index) override
bool CreateVDPAUTexture (int index)
void DeleteVDPAUTexture (int index)
bool UploadVDPAUTexture (int index)
bool CreateVDPAUTexture420 (int index)
void DeleteVDPAUTexture420 (int index)
bool UploadVDPAUTexture420 (int index)
EShaderFormat GetShaderFormat () override
bool CanSaveBuffers () override
Protected Member Functions inherited from CLinuxRendererGL
bool Render (unsigned int flags, int renderBuffer)
void ClearBackBuffer ()
void ClearBackBufferQuad ()
void DrawBlackBars ()
bool ValidateRenderer ()
virtual bool ValidateRenderTarget ()
virtual void LoadShaders (int field=FIELD_FULL)
void SetTextureFilter (GLenum method)
void UpdateVideoFilter ()
void CheckVideoParameters (int index)
AVColorPrimaries GetSrcPrimaries (AVColorPrimaries srcPrimaries, unsigned int width, unsigned int height)
bool UploadYV12Texture (int index)
void DeleteYV12Texture (int index)
bool CreateYV12Texture (int index)
bool UploadNV12Texture (int index)
void DeleteNV12Texture (int index)
bool CreateNV12Texture (int index)
bool UploadYUV422PackedTexture (int index)
void DeleteYUV422PackedTexture (int index)
bool CreateYUV422PackedTexture (int index)
void CalculateTextureSourceRects (int source, int num_planes)
void RenderToFBO (int renderBuffer, int field, bool weave=false)
void RenderFromFBO ()
void RenderSinglePass (int renderBuffer, int field)
void RenderRGB (int renderBuffer, int field)
void RenderProgressiveWeave (int renderBuffer, int field)
void BindPbo (CPictureBuffer &buff)
void UnBindPbo (CPictureBuffer &buff)
void LoadPlane (CYuvPlane &plane, int type, unsigned width, unsigned height, int stride, int bpp, void *data)
void GetPlaneTextureSize (CYuvPlane &plane)
GLint GetInternalFormat (GLint format, int bpp)
bool LoadCLUT ()
void DeleteCLUT ()
Protected Member Functions inherited from CBaseRenderer
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ManageRenderArea ()
virtual void ReorderDrawPoints ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Protected Attributes
bool m_isYuv = false
VDPAU::CInteropState m_interopState
VDPAU::CVdpauTexture m_vdpauTextures [NUM_BUFFERS]
GLsync m_fences [NUM_BUFFERS]
Protected Attributes inherited from CLinuxRendererGL
struct {
CFrameBufferObject fbo
float width
float height
} m_fbo
GLint m_intermediateFormat {GL_RGBA8}
GLint m_intermediateType {GL_UNSIGNED_BYTE}
bool m_intermediateGammaCorrection {false}
int m_iYV12RenderBuffer = 0
int m_NumYV12Buffers = 0
bool m_bConfigured = false
bool m_bValidated = false
GLenum m_textureTarget = GL_TEXTURE_2D
int m_renderMethod = RENDER_GLSL
RenderQuality m_renderQuality = RQ_SINGLEPASS
CRenderSystemGL * m_renderSystem = nullptr
int m_currentField = FIELD_FULL
int m_reloadShaders = 0
CPictureBuffer m_buffers [NUM_BUFFERS]
Shaders::GL::BaseYUV2RGBGLSLShader * m_pYUVShader = nullptr
Shaders::GL::BaseVideoFilterShader * m_pVideoFilterShader = nullptr
ESCALINGMETHOD m_scalingMethod = VS_SCALINGMETHOD_LINEAR
ESCALINGMETHOD m_scalingMethodGui = VS_SCALINGMETHOD_MAX
bool m_useDithering
unsigned int m_ditherDepth
bool m_fullRange
AVColorPrimaries m_srcPrimaries
bool m_toneMap = false
ETONEMAPMETHOD m_toneMapMethod = VS_TONEMAPMETHOD_OFF
float m_clearColour = 0.0f
bool m_pboSupported = true
bool m_pboUsed = false
bool m_nonLinStretch = false
bool m_nonLinStretchGui = false
float m_pixelRatio = 0.0f
CRect m_viewRect
std::unique_ptr< CColorManager > m_ColorManager
GLuint m_tCLUTTex
uint16_t * m_CLUT
int m_CLUTsize
int m_cmsToken
bool m_cmsOn
Protected Attributes inherited from CBaseRenderer
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Constructor & Destructor Documentation
CRendererVDPAU()
CRendererVDPAU::CRendererVDPAU () default
Referenced by Create().
~CRendererVDPAU()
CRendererVDPAU::~CRendererVDPAU () override
References DeleteTexture(), VDPAU::CInteropState::Finish(), m_interopState, and NUM_BUFFERS.
Member Function Documentation
AfterRenderHook()
void CRendererVDPAU::AfterRenderHook (int idx) override protected virtual
Reimplemented from CLinuxRendererGL.
References m_fences.
CanSaveBuffers()
bool CRendererVDPAU::CanSaveBuffers () inline override protected virtual
Reimplemented from CLinuxRendererGL.
ConfigChanged()
bool CRendererVDPAU::ConfigChanged (const VideoPicture & picture) override virtual
Reimplemented from CLinuxRendererGL.
References VDPAU::CVdpauRenderPicture::device, VDPAU::CVdpauRenderPicture::ident, VDPAU::CVdpauProcessedPicture::isYuv, m_interopState, m_isYuv, VDPAU::CInteropState::NeedInit(), VDPAU::CVdpauRenderPicture::procFunc, VDPAU::CVdpauRenderPicture::procPic, and VideoPicture::videoBuffer.
Configure()
bool CRendererVDPAU::Configure (const VideoPicture & picture, float fps, unsigned int orientation) override virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::Configure(), VDPAU::CVdpauRenderPicture::device, VDPAU::CInteropState::GetInterop(), VDPAU::CVdpauRenderPicture::ident, VDPAU::CInteropState::Init(), VDPAU::CVdpauProcessedPicture::isYuv, m_fences, m_interopState, m_isYuv, m_vdpauTextures, VDPAU::CVdpauRenderPicture::procFunc, VDPAU::CVdpauRenderPicture::procPic, and VideoPicture::videoBuffer.
Create()
CBaseRenderer * CRendererVDPAU::Create (CVideoBuffer * buffer) static
References CRendererVDPAU().
Referenced by Register().
CreateTexture()
bool CRendererVDPAU::CreateTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
References CreateVDPAUTexture(), CreateVDPAUTexture420(), index(), and m_isYuv.
CreateVDPAUTexture()
bool CRendererVDPAU::CreateVDPAUTexture (int index) protected
References DeleteVDPAUTexture(), FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGL::CYuvPlane::id, CLinuxRendererGL::CPictureBuffer::image, index(), CLinuxRendererGL::m_buffers, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, CLinuxRendererGL::CYuvPlane::pixpertex_x, CLinuxRendererGL::CYuvPlane::pixpertex_y, CLinuxRendererGL::CYuvPlane::texheight, CLinuxRendererGL::CYuvPlane::texwidth, and YuvImage::width.
Referenced by CreateTexture().
CreateVDPAUTexture420()
bool CRendererVDPAU::CreateVDPAUTexture420 (int index) protected
References YuvImage::cshift_x, YuvImage::cshift_y, DeleteVDPAUTexture420(), CLinuxRendererGL::CPictureBuffer::fields, CLinuxRendererGL::CPictureBuffer::image, index(), CLinuxRendererGL::m_buffers, YuvImage::MAX_PLANES, CLinuxRendererGL::CPictureBuffer::pbo, and YuvImage::plane.
Referenced by CreateTexture().
DeleteTexture()
void CRendererVDPAU::DeleteTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
References DeleteVDPAUTexture(), DeleteVDPAUTexture420(), index(), m_isYuv, and ReleaseBuffer().
Referenced by ~CRendererVDPAU().
DeleteVDPAUTexture()
void CRendererVDPAU::DeleteVDPAUTexture (int index) protected
References FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, CLinuxRendererGL::CYuvPlane::id, index(), and CLinuxRendererGL::m_buffers.
Referenced by CreateVDPAUTexture(), and DeleteTexture().
DeleteVDPAUTexture420()
void CRendererVDPAU::DeleteVDPAUTexture420 (int index) protected
References CLinuxRendererGL::CPictureBuffer::fields, CLinuxRendererGL::CYuvPlane::id, index(), and CLinuxRendererGL::m_buffers.
Referenced by CreateVDPAUTexture420(), and DeleteTexture().
Flush()
bool CRendererVDPAU::Flush (bool saveBuffers) override virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::Flush(), m_vdpauTextures, and NUM_BUFFERS.
GetShaderFormat()
EShaderFormat CRendererVDPAU::GetShaderFormat () override protected virtual
Reimplemented from CBaseRenderer.
References m_isYuv, SHADER_NONE, and SHADER_NV12.
LoadShadersHook()
bool CRendererVDPAU::LoadShadersHook () override protected virtual
Reimplemented from CLinuxRendererGL.
References CLog::Log(), LOGINFO, CLinuxRendererGL::m_fullRange, m_isYuv, CLinuxRendererGL::m_renderMethod, and RENDER_CUSTOM.
NeedBuffer()
bool CRendererVDPAU::NeedBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References m_fences.
Register()
bool CRendererVDPAU::Register () static
References Create(), and VIDEOPLAYER::CRendererFactory::RegisterRenderer().
ReleaseBuffer()
void CRendererVDPAU::ReleaseBuffer (int idx) override virtual
Reimplemented from CLinuxRendererGL.
References m_fences, m_vdpauTextures, CLinuxRendererGL::ReleaseBuffer(), and VDPAU::CVdpauTexture::Unmap().
Referenced by DeleteTexture().
RenderHook()
bool CRendererVDPAU::RenderHook (int idx) override protected virtual
Reimplemented from CLinuxRendererGL.
References FIELD_FULL, CLinuxRendererGL::m_currentField, m_isYuv, CLinuxRendererGL::m_renderQuality, CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGL::RenderProgressiveWeave(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGL::RenderSinglePass(), CLinuxRendererGL::RenderToFBO(), RQ_LOW, RQ_MULTIPASS, RQ_SINGLEPASS, CLinuxRendererGL::UpdateVideoFilter(), and VerifyGLState.
Supports() [1/2]
bool CRendererVDPAU::Supports (ERENDERFEATURE feature) const override virtual
Reimplemented from CLinuxRendererGL.
References CServiceBroker::GetSettingsComponent(), m_isYuv, CLinuxRendererGL::m_renderMethod, RENDER_GLSL, RENDERFEATURE_BRIGHTNESS, RENDERFEATURE_CONTRAST, RENDERFEATURE_NOISE, RENDERFEATURE_NONLINSTRETCH, RENDERFEATURE_PIXEL_RATIO, RENDERFEATURE_POSTPROCESS, RENDERFEATURE_ROTATION, RENDERFEATURE_SHARPNESS, RENDERFEATURE_STRETCH, RENDERFEATURE_VERTICAL_SHIFT, RENDERFEATURE_ZOOM, and CSettings::SETTING_VIDEOSCREEN_LIMITEDRANGE.
Supports() [2/2]
bool CRendererVDPAU::Supports (ESCALINGMETHOD method) const override virtual
Reimplemented from CLinuxRendererGL.
References CServiceBroker::GetSettingsComponent(), CRectGen< T >::Height(), CBaseRenderer::m_destRect, m_isYuv, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, CLinuxRendererGL::Supports(), VS_SCALINGMETHOD_AUTO, VS_SCALINGMETHOD_CUBIC_0_075, VS_SCALINGMETHOD_CUBIC_0_1, VS_SCALINGMETHOD_CUBIC_B_SPLINE, VS_SCALINGMETHOD_CUBIC_CATMULL, VS_SCALINGMETHOD_CUBIC_MITCHELL, VS_SCALINGMETHOD_LANCZOS2, VS_SCALINGMETHOD_LANCZOS3, VS_SCALINGMETHOD_LANCZOS3_FAST, VS_SCALINGMETHOD_LINEAR, VS_SCALINGMETHOD_NEAREST, VS_SCALINGMETHOD_SPLINE36, VS_SCALINGMETHOD_SPLINE36_FAST, and CRectGen< T >::Width().
UploadTexture()
bool CRendererVDPAU::UploadTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
References index(), m_isYuv, UploadVDPAUTexture(), and UploadVDPAUTexture420().
UploadVDPAUTexture()
bool CRendererVDPAU::UploadVDPAUTexture (int index) protected
References VDPAU::CVdpauRenderPicture::crop, FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, CLinuxRendererGL::CYuvPlane::id, index(), CLinuxRendererGL::m_buffers, CBaseRenderer::m_sourceRect, VDPAU::CVdpauTexture::m_texHeight, VDPAU::CVdpauTexture::m_texture, CLinuxRendererGL::m_textureTarget, VDPAU::CVdpauTexture::m_texWidth, m_vdpauTextures, CLinuxRendererGL::CYuvPlane::rect, CLinuxRendererGL::CYuvPlane::texheight, CLinuxRendererGL::CYuvPlane::texwidth, CLinuxRendererGL::CPictureBuffer::videoBuffer, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by UploadTexture().
UploadVDPAUTexture420()
bool CRendererVDPAU::UploadVDPAUTexture420 (int index) protected
References CLinuxRendererGL::CalculateTextureSourceRects(), YuvImage::cshift_x, YuvImage::cshift_y, f, FIELD_BOT, FIELD_TOP, CLinuxRendererGL::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGL::CYuvPlane::id, CLinuxRendererGL::CPictureBuffer::image, index(), CLinuxRendererGL::m_buffers, VDPAU::CVdpauTexture::m_texHeight, VDPAU::CVdpauTexture::m_textureBotUV, VDPAU::CVdpauTexture::m_textureBotY, CLinuxRendererGL::m_textureTarget, VDPAU::CVdpauTexture::m_textureTopUV, VDPAU::CVdpauTexture::m_textureTopY, VDPAU::CVdpauTexture::m_texWidth, m_vdpauTextures, YuvImage::MAX_PLANES, CLinuxRendererGL::CYuvPlane::texwidth, VerifyGLState, CLinuxRendererGL::CPictureBuffer::videoBuffer, and YuvImage::width.
Referenced by UploadTexture().
Member Data Documentation
m_fences
GLsync CRendererVDPAU::m_fences[NUM_BUFFERS] protected
Referenced by AfterRenderHook(), Configure(), NeedBuffer(), and ReleaseBuffer().
m_interopState
VDPAU::CInteropState CRendererVDPAU::m_interopState protected
Referenced by ConfigChanged(), Configure(), and ~CRendererVDPAU().
m_isYuv
bool CRendererVDPAU::m_isYuv = false protected
Referenced by ConfigChanged(), Configure(), CreateTexture(), DeleteTexture(), GetShaderFormat(), LoadShadersHook(), RenderHook(), Supports(), Supports(), and UploadTexture().
m_vdpauTextures
VDPAU::CVdpauTexture CRendererVDPAU::m_vdpauTextures[NUM_BUFFERS] protected
Referenced by Configure(), Flush(), ReleaseBuffer(), UploadVDPAUTexture(), and UploadVDPAUTexture420().
The documentation for this class was generated from the following files:
RendererVDPAU.h
RendererVDPAU.cpp