Kodi Documentation: CXBTFBase Class Reference
CXBTFBase Class Reference
#include <XBTF.h>
Public Member Functions
virtual ~CXBTFBase ()=default
uint64_t GetHeaderSize () const
bool Exists (const std::string &name) const
bool Get (const std::string &name, CXBTFFile &file) const
std::vector< CXBTFFile > GetFiles () const
void AddFile (const CXBTFFile &file)
void UpdateFile (const CXBTFFile &file)
Protected Member Functions
CXBTFBase ()=default
Protected Attributes
std::map< std::string, CXBTFFile > m_files
Constructor & Destructor Documentation
~CXBTFBase()
virtual CXBTFBase::~CXBTFBase () virtual default
CXBTFBase()
CXBTFBase::CXBTFBase () protected default
Member Function Documentation
AddFile()
void CXBTFBase::AddFile (const CXBTFFile & file)
References m_files.
Referenced by CXBTFReader::Open().
Exists()
bool CXBTFBase::Exists (const std::string & name) const
References Get(), and name.
Get()
bool CXBTFBase::Get (const std::string & name, CXBTFFile & file) const
References m_files, and name.
Referenced by Exists().
GetFiles()
std::vector< CXBTFFile > CXBTFBase::GetFiles () const
References m_files.
GetHeaderSize()
uint64_t CXBTFBase::GetHeaderSize () const
References m_files, XBTF_MAGIC, and XBTF_VERSION.
Referenced by CXBTFReader::Open().
UpdateFile()
void CXBTFBase::UpdateFile (const CXBTFFile & file)
References m_files.
Member Data Documentation
m_files
std::map<std::string, CXBTFFile> CXBTFBase::m_files protected
Referenced by AddFile(), CXBTFReader::Close(), Get(), GetFiles(), GetHeaderSize(), and UpdateFile().
The documentation for this class was generated from the following files:
XBTF.h
XBTF.cpp