Kodi Documentation: CEventStream< Event > Class Template Reference
CEventStream< Event > Class Template Reference
#include <EventStream.h>
Public Member Functions
template<typename A >
void Subscribe (A *owner, void(A::*fn)(const Event &))
template<typename A >
void Unsubscribe (A *obj)
Protected Attributes
std::vector< std::shared_ptr< detail::ISubscription< Event > > > m_subscriptions
CCriticalSection m_criticalSection
Member Function Documentation
Subscribe()
template<typename Event > template<typename A > void CEventStream< Event >::Subscribe (A * owner, void(A::*)(const Event &) fn) inline
References CEventStream< Event >::m_criticalSection, CEventStream< Event >::m_subscriptions, and owner.
Referenced by PVR::CGUIWindowPVRBase::CGUIWindowPVRBase(), PVR::CPVRGUIActionListener::Init(), PVR::CPVRChannelGroups::LoadFromDatabase(), PVR::CPVRTimers::Start(), PVR::CGUIDialogPVRChannelsOSD::Update(), and CDirectoryProvider::UpdateURL().
Unsubscribe()
template<typename Event > template<typename A > void CEventStream< Event >::Unsubscribe (A * obj) inline
References CEventStream< Event >::m_criticalSection, and CEventStream< Event >::m_subscriptions.
Referenced by PVR::CPVRGUIActionListener::Deinit(), CDirectoryProvider::Reset(), PVR::CPVRTimers::Stop(), PVR::CPVRChannelGroups::Unload(), and PVR::CGUIWindowPVRBase::~CGUIWindowPVRBase().
Member Data Documentation
m_criticalSection
template<typename Event > CCriticalSection CEventStream< Event >::m_criticalSection protected
Referenced by CBlockingEventSource< Event >::HandleEvent(), CEventSource< Event >::Publish(), CEventStream< Event >::Subscribe(), and CEventStream< Event >::Unsubscribe().
m_subscriptions
template<typename Event > std::vector<std::shared_ptr<detail::ISubscription<Event> > > CEventStream< Event >::m_subscriptions protected
Referenced by CBlockingEventSource< Event >::HandleEvent(), CEventSource< Event >::Publish(), CEventStream< Event >::Subscribe(), and CEventStream< Event >::Unsubscribe().
The documentation for this class was generated from the following file:
EventStream.h