Kodi Documentation: CStorageProvider Class Reference
CStorageProvider Class Reference
#include <Win10StorageProvider.h>
Public Member Functions
virtual ~CStorageProvider ()
void Initialize () override
void Stop () override
void GetLocalDrives (std::vector< CMediaSource > &localDrives) override
void GetRemovableDrives (std::vector< CMediaSource > &removableDrives) override
std::string GetFirstOpticalDeviceFileName () override
bool Eject (const std::string &mountpath) override
std::vector< std::string > GetDiskUsage () override
bool PumpDriveChangeEvents (IStorageEventsCallback *callback) override
Public Member Functions inherited from IStorageProvider
virtual ~IStorageProvider ()=default
Private Types
enum Drive_Types { ALL_DRIVES = 0 , LOCAL_DRIVES , REMOVABLE_DRIVES , DVD_DRIVES }
Static Private Member Functions
static void GetDrivesByType (std::vector< CMediaSource > &localDrives, Drive_Types eDriveType=ALL_DRIVES, bool bonlywithmedia=false)
Private Attributes
winrt::Windows::Devices::Enumeration::DeviceWatcher m_watcher { nullptr }
std::atomic< bool > m_changed
Additional Inherited Members
Static Public Member Functions inherited from IStorageProvider
static std::unique_ptr< IStorageProvider > CreateInstance ()
Called by media manager to create platform storage provider.
Member Enumeration Documentation
Drive_Types
enum CStorageProvider::Drive_Types private
Enumerator
ALL_DRIVES
LOCAL_DRIVES
REMOVABLE_DRIVES
DVD_DRIVES
Constructor & Destructor Documentation
~CStorageProvider()
CStorageProvider::~CStorageProvider () virtual
References m_watcher.
Member Function Documentation
Eject()
bool CStorageProvider::Eject (const std::string & mountpath) override virtual
Implements IStorageProvider.
GetDiskUsage()
std::vector< std::string > CStorageProvider::GetDiskUsage (void) override virtual
Implements IStorageProvider.
References KODI::PLATFORM::WINDOWS::FromW(), g_localizeStrings, CLocalizeStrings::Get(), and _ULARGE_INTEGER::QuadPart.
GetDrivesByType()
void CStorageProvider::GetDrivesByType (std::vector< CMediaSource > & localDrives, Drive_Types eDriveType = ALL_DRIVES, bool bonlywithmedia = false) static private
References AddOrReplace(), DVD_DRIVES, g_localizeStrings, CLocalizeStrings::Get(), LOCAL_DRIVES, CMediaSource::m_iDriveType, CMediaSource::m_ignore, REMOVABLE_DRIVES, CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::SOURCE_TYPE_OPTICAL_DISC, CMediaSource::SOURCE_TYPE_REMOTE, CMediaSource::SOURCE_TYPE_REMOVABLE, CMediaSource::SOURCE_TYPE_UNKNOWN, CMediaSource::strName, CMediaSource::strPath, and CMediaSource::strStatus.
Referenced by GetFirstOpticalDeviceFileName(), GetLocalDrives(), GetRemovableDrives(), and Initialize().
GetFirstOpticalDeviceFileName()
std::string CStorageProvider::GetFirstOpticalDeviceFileName () override virtual
Reimplemented from IStorageProvider.
References DVD_DRIVES, and GetDrivesByType().
GetLocalDrives()
void CStorageProvider::GetLocalDrives (std::vector< CMediaSource > & localDrives) override virtual
Implements IStorageProvider.
References g_localizeStrings, CLocalizeStrings::Get(), GetDrivesByType(), LOCAL_DRIVES, CMediaSource::m_iDriveType, CMediaSource::m_ignore, CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::strName, CMediaSource::strPath, and CSpecialProtocol::TranslatePath().
GetRemovableDrives()
void CStorageProvider::GetRemovableDrives (std::vector< CMediaSource > & removableDrives) override virtual
Implements IStorageProvider.
References KODI::PLATFORM::WINDOWS::FromW(), GetDrivesByType(), CMediaSource::m_iDriveType, REMOVABLE_DRIVES, CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::SOURCE_TYPE_OPTICAL_DISC, CMediaSource::SOURCE_TYPE_REMOTE, CMediaSource::SOURCE_TYPE_REMOVABLE, CMediaSource::SOURCE_TYPE_UNKNOWN, CMediaSource::strName, CMediaSource::strPath, and Wait().
Initialize()
void CStorageProvider::Initialize () override virtual
Implements IStorageProvider.
References DVD_DRIVES, GetDrivesByType(), CServiceBroker::GetMediaManager(), CLog::Log(), LOGDEBUG, m_changed, m_watcher, and CMediaManager::SetHasOpticalDrive().
PumpDriveChangeEvents()
bool CStorageProvider::PumpDriveChangeEvents (IStorageEventsCallback * callback) override virtual
Implements IStorageProvider.
References m_changed.
Stop()
void CStorageProvider::Stop () inline override virtual
Implements IStorageProvider.
Member Data Documentation
m_changed
std::atomic<bool> CStorageProvider::m_changed private
Referenced by Initialize(), and PumpDriveChangeEvents().
m_watcher
winrt::Windows::Devices::Enumeration::DeviceWatcher CStorageProvider::m_watcher { nullptr } private
Referenced by Initialize(), and ~CStorageProvider().
The documentation for this class was generated from the following files:
Win10StorageProvider.h
Win10StorageProvider.cpp