Kodi Documentation: CVideoDatabase Class Reference
CVideoDatabase Class Reference
#include <VideoDatabase.h>
Classes
class CActor
class CSeason
class CSetInfo
Public Member Functions
CVideoDatabase (void)
~CVideoDatabase (void) override
bool Open () override
bool CommitTransaction () override
int AddNewEpisode (int idShow, CVideoInfoTag &details)
CDateTime SetPlayCount (const CFileItem &item, int count, const CDateTime &date=CDateTime())
Set the playcount of an item, update last played time Sets the playcount and last played date to a given value.
CDateTime IncrementPlayCount (const CFileItem &item)
Increment the playcount of an item Increments the playcount and updates the last played date.
int GetPlayCount (const CFileItem &item)
Get the playcount of an item.
int GetPlayCount (const std::string &strFilenameAndPath)
Get the playcount of a filename and path.
CDateTime GetLastPlayed (const std::string &strFilenameAndPath)
Get the last played time of a filename and path.
CDateTime UpdateLastPlayed (const CFileItem &item)
Update the last played time of an item Updates the last played date.
bool GetPlayCounts (const std::string &path, CFileItemList &items)
Get the playcount and resume point of a list of items Note that if the resume point is already set on an item, it won't be overridden.
void UpdateMovieTitle (int idMovie, const std::string &strNewMovieTitle, VideoDbContentType iType=VideoDbContentType::MOVIES)
bool UpdateVideoSortTitle (int idDb, const std::string &strNewSortTitle, VideoDbContentType iType=VideoDbContentType::MOVIES)
bool HasMovieInfo (const std::string &strFilenameAndPath)
bool HasTvShowInfo (const std::string &strFilenameAndPath)
bool HasEpisodeInfo (const std::string &strFilenameAndPath)
bool HasMusicVideoInfo (const std::string &strFilenameAndPath)
void GetFilePathById (int idMovie, std::string &filePath, VideoDbContentType iType)
std::string GetGenreById (int id)
std::string GetCountryById (int id)
std::string GetSetById (int id)
std::string GetTagById (int id)
std::string GetPersonById (int id)
std::string GetStudioById (int id)
std::string GetTvShowTitleById (int id)
std::string GetMusicVideoAlbumById (int id)
int GetTvShowForEpisode (int idEpisode)
int GetSeasonForEpisode (int idEpisode)
bool LoadVideoInfo (const std::string &strFilenameAndPath, CVideoInfoTag &details, int getDetails=VideoDbDetailsAll)
bool GetMovieInfo (const std::string &strFilenameAndPath, CVideoInfoTag &details, int idMovie=-1, int idVersion=-1, int getDetails=VideoDbDetailsAll)
bool GetTvShowInfo (const std::string &strPath, CVideoInfoTag &details, int idTvShow=-1, CFileItem *item=NULL, int getDetails=VideoDbDetailsAll)
bool GetSeasonInfo (const std::string &path, int season, CVideoInfoTag &details, CFileItem *item)
bool GetSeasonInfo (int idSeason, CVideoInfoTag &details, CFileItem *item)
bool GetSeasonInfo (int idSeason, CVideoInfoTag &details, bool allDetails=true)
bool GetEpisodeBasicInfo (const std::string &strFilenameAndPath, CVideoInfoTag &details, int idEpisode=-1)
bool GetEpisodeInfo (const std::string &strFilenameAndPath, CVideoInfoTag &details, int idEpisode=-1, int getDetails=VideoDbDetailsAll)
bool GetMusicVideoInfo (const std::string &strFilenameAndPath, CVideoInfoTag &details, int idMVideo=-1, int getDetails=VideoDbDetailsAll)
bool GetSetInfo (int idSet, CVideoInfoTag &details, CFileItem *item=nullptr)
bool GetFileInfo (const std::string &strFilenameAndPath, CVideoInfoTag &details, int idFile=-1)
int GetPathId (const std::string &strPath)
int GetTvShowId (const std::string &strPath)
int GetEpisodeId (const std::string &strFilenameAndPath, int idEpisode=-1, int idSeason=-1)
int GetSeasonId (int idShow, int season)
void GetEpisodesByFile (const std::string &strFilenameAndPath, std::vector< CVideoInfoTag > &episodes)
int SetDetailsForItem (CVideoInfoTag &details, const std::map< std::string, std::string > &artwork)
int SetDetailsForItem (int id, const MediaType &mediaType, CVideoInfoTag &details, const std::map< std::string, std::string > &artwork)
int SetDetailsForMovie (CVideoInfoTag &details, const std::map< std::string, std::string > &artwork, int idMovie=-1)
int SetDetailsForMovieSet (const CVideoInfoTag &details, const std::map< std::string, std::string > &artwork, int idSet=-1)
int SetDetailsForTvShow (const std::vector< std::pair< std::string, std::string > > &paths, CVideoInfoTag &details, const std::map< std::string, std::string > &artwork, const std::map< int, std::map< std::string, std::string > > &seasonArt, int idTvShow=-1)
add a tvshow to the library, setting metadata detail First checks for whether this TV Show is already in the database (based on idTvShow, or via GetMatchingTvShow) and if present adds the paths to the show. If not present, we add a new show and set the show metadata.
bool UpdateDetailsForTvShow (int idTvShow, CVideoInfoTag &details, const std::map< std::string, std::string > &artwork, const std::map< int, std::map< std::string, std::string > > &seasonArt)
int SetDetailsForSeason (const CVideoInfoTag &details, const std::map< std::string, std::string > &artwork, int idShow, int idSeason=-1)
int SetDetailsForEpisode (CVideoInfoTag &details, const std::map< std::string, std::string > &artwork, int idShow, int idEpisode=-1)
bool SetFileForEpisode (const std::string &fileAndPath, int idEpisode, int idFile)
bool SetFileForMovie (const std::string &fileAndPath, int idMovie, int idFile)
int SetDetailsForMusicVideo (CVideoInfoTag &details, const std::map< std::string, std::string > &artwork, int idMVideo=-1)
int SetStreamDetailsForFile (const CStreamDetails &details, const std::string &strFileNameAndPath)
bool SetStreamDetailsForFileId (const CStreamDetails &details, int idFile)
Clear any existing stream details and add the new provided details to a file.
bool SetSingleValue (VideoDbContentType type, int dbId, int dbField, const std::string &strValue)
bool SetSingleValue (VideoDbContentType type, int dbId, Field dbField, const std::string &strValue)
bool SetSingleValue (const std::string &table, const std::string &fieldName, const std::string &strValue, const std::string &conditionName="", int conditionValue=-1)
int UpdateDetailsForMovie (int idMovie, CVideoInfoTag &details, const std::map< std::string, std::string > &artwork, const std::set< std::string > &updatedDetails)
void DeleteMovie (int idMovie, DeleteMovieCascadeAction action=DeleteMovieCascadeAction::ALL_ASSETS, DeleteMovieHashAction hashAction=DeleteMovieHashAction::HASH_DELETE)
void DeleteTvShow (int idTvShow, bool bKeepId=false)
void DeleteTvShow (const std::string &strPath)
void DeleteSeason (int idSeason, bool bKeepId=false)
void DeleteEpisode (int idEpisode, bool bKeepId=false)
void DeleteMusicVideo (int idMusicVideo, bool bKeepId=false)
void DeleteDetailsForTvShow (int idTvShow)
void DeleteStreamDetails (int idFile)
void RemoveContentForPath (const std::string &strPath, CGUIDialogProgress *progress=NULL)
void UpdateFanart (const CFileItem &item, VideoDbContentType type)
void DeleteSet (int idSet)
void DeleteTag (int idTag, VideoDbContentType mediaType)
bool GetVideoSettings (int idFile, CVideoSettings &settings)
Get video settings for the specified file id.
bool GetVideoSettings (const CFileItem &item, CVideoSettings &settings)
Get video settings for the specified file item.
bool GetVideoSettings (const std::string &filePath, CVideoSettings &settings)
Get video settings for the specified file path.
void SetVideoSettings (const CFileItem &item, const CVideoSettings &settings)
Set video settings for the specified file path.
void SetVideoSettings (int idFile, const CVideoSettings &settings)
Set video settings for the specified file path.
void EraseVideoSettings (const CFileItem &item)
EraseVideoSettings() Erases the videoSettings table and reconstructs it.
void EraseAllVideoSettings ()
void EraseAllVideoSettings (const std::string &path)
void EraseAllForPath (const std::string &path)
void EraseAllForFile (const std::string &fileNameAndPath)
bool GetStackTimes (const std::string &filePath, std::vector< uint64_t > &times)
GetStackTimes() obtains any saved video times for the stacked file.
void SetStackTimes (const std::string &filePath, const std::vector< uint64_t > &times)
Sets the stack times for a particular video file.
void GetBookMarksForFile (const std::string &strFilenameAndPath, VECBOOKMARKS &bookmarks, CBookmark::EType type=CBookmark::STANDARD, bool bAppend=false, long partNumber=0)
void AddBookMarkToFile (const std::string &strFilenameAndPath, const CBookmark &bookmark, CBookmark::EType type=CBookmark::STANDARD)
bool GetResumeBookMark (const std::string &strFilenameAndPath, CBookmark &bookmark)
void DeleteResumeBookMark (const CFileItem &item)
void ClearBookMarkOfFile (const std::string &strFilenameAndPath, CBookmark &bookmark, CBookmark::EType type=CBookmark::STANDARD)
void ClearBookMarksOfFile (const std::string &strFilenameAndPath, CBookmark::EType type=CBookmark::STANDARD)
void ClearBookMarksOfFile (int idFile, CBookmark::EType type=CBookmark::STANDARD)
bool GetBookMarkForEpisode (const CVideoInfoTag &tag, CBookmark &bookmark)
void AddBookMarkForEpisode (const CVideoInfoTag &tag, const CBookmark &bookmark)
void DeleteBookMarkForEpisode (const CVideoInfoTag &tag)
bool GetResumePoint (CVideoInfoTag &tag)
bool GetStreamDetails (CFileItem &item)
bool GetStreamDetails (CVideoInfoTag &tag)
bool GetStreamDetails (const std::string &filenameAndPath, CStreamDetails &details)
bool GetDetailsByTypeAndId (CFileItem &item, VideoDbContentType type, int id)
CVideoInfoTag GetDetailsByTypeAndId (VideoDbContentType type, int id)
void SetScraperForPath (const std::string &filePath, const ADDON::ScraperPtr &info, const KODI::VIDEO::SScanSettings &settings)
ADDON::ScraperPtr GetScraperForPath (const std::string &strPath)
ADDON::ScraperPtr GetScraperForPath (const std::string &strPath, KODI::VIDEO::SScanSettings &settings)
ADDON::ScraperPtr GetScraperForPath (const std::string &strPath, KODI::VIDEO::SScanSettings &settings, bool &foundDirectly)
Retrieve the scraper and settings we should use for the specified path If the scraper is not set on this particular path, we'll recursively check parent folders.
std::string GetContentForPath (const std::string &strPath)
Retrieve the content type of videos in the given path If content is set on the folder, we return the given content type, except in the case of tvshows, where we first check for whether we have episodes directly in the path (thus return episodes) or whether we've found a scraper directly (shows). Any folders inbetween are treated as seasons (regardless of whether they actually are seasons). Note that any subfolders in movies will be treated as movies.
bool GetItemsForPath (const std::string &content, const std::string &path, CFileItemList &items)
Get videos of the given content type from the given path.
bool ScraperInUse (const std::string &scraperID) const
Check whether a given scraper is in use.
bool SetPathHash (const std::string &path, const std::string &hash)
bool GetPathHash (const std::string &path, std::string &hash)
bool GetPaths (std::set< std::string > &paths)
bool GetPathsForTvShow (int idShow, std::set< int > &paths)
bool GetPathsLinkedToTvShow (int idShow, std::vector< std::string > &paths)
return the paths linked to a tvshow.
bool GetSubPaths (const std::string &basepath, std::vector< std::pair< int, std::string > > &subpaths)
retrieve subpaths of a given path. Assumes a hierarchical folder structure
bool GetSourcePath (const std::string &path, std::string &sourcePath)
bool GetSourcePath (const std::string &path, std::string &sourcePath, KODI::VIDEO::SScanSettings &settings)
int GetMatchingMusicVideo (const std::string &strArtist, const std::string &strAlbum="", const std::string &strTitle="")
void GetMoviesByActor (const std::string &strActor, CFileItemList &items)
void GetTvShowsByActor (const std::string &strActor, CFileItemList &items)
void GetEpisodesByActor (const std::string &strActor, CFileItemList &items)
void GetMusicVideosByArtist (const std::string &strArtist, CFileItemList &items)
void GetMusicVideosByAlbum (const std::string &strAlbum, CFileItemList &items)
void GetMovieGenresByName (const std::string &strSearch, CFileItemList &items)
void GetTvShowGenresByName (const std::string &strSearch, CFileItemList &items)
void GetMusicVideoGenresByName (const std::string &strSearch, CFileItemList &items)
void GetMovieCountriesByName (const std::string &strSearch, CFileItemList &items)
void GetMusicVideoAlbumsByName (const std::string &strSearch, CFileItemList &items)
void GetMovieActorsByName (const std::string &strSearch, CFileItemList &items)
void GetTvShowsActorsByName (const std::string &strSearch, CFileItemList &items)
void GetMusicVideoArtistsByName (const std::string &strSearch, CFileItemList &items)
void GetMovieDirectorsByName (const std::string &strSearch, CFileItemList &items)
void GetTvShowsDirectorsByName (const std::string &strSearch, CFileItemList &items)
void GetMusicVideoDirectorsByName (const std::string &strSearch, CFileItemList &items)
void GetMoviesByName (const std::string &strSearch, CFileItemList &items)
void GetTvShowsByName (const std::string &strSearch, CFileItemList &items)
void GetEpisodesByName (const std::string &strSearch, CFileItemList &items)
void GetMusicVideosByName (const std::string &strSearch, CFileItemList &items)
void GetEpisodesByPlot (const std::string &strSearch, CFileItemList &items)
void GetMoviesByPlot (const std::string &strSearch, CFileItemList &items)
bool LinkMovieToTvshow (int idMovie, int idShow, bool bRemove)
bool IsLinkedToTvshow (int idMovie)
bool GetLinksToTvShow (int idMovie, std::vector< int > &ids)
bool GetGenresNav (const std::string &strBaseDir, CFileItemList &items, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter(), bool countOnly=false)
bool GetCountriesNav (const std::string &strBaseDir, CFileItemList &items, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter(), bool countOnly=false)
bool GetStudiosNav (const std::string &strBaseDir, CFileItemList &items, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter(), bool countOnly=false)
bool GetYearsNav (const std::string &strBaseDir, CFileItemList &items, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter())
bool GetActorsNav (const std::string &strBaseDir, CFileItemList &items, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter(), bool countOnly=false)
bool GetDirectorsNav (const std::string &strBaseDir, CFileItemList &items, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter(), bool countOnly=false)
bool GetWritersNav (const std::string &strBaseDir, CFileItemList &items, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter(), bool countOnly=false)
bool GetSetsNav (const std::string &strBaseDir, CFileItemList &items, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter(), bool ignoreSingleMovieSets=false)
bool GetTagsNav (const std::string &strBaseDir, CFileItemList &items, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter(), bool countOnly=false)
bool GetMusicVideoAlbumsNav (const std::string &strBaseDir, CFileItemList &items, int idArtist, const Filter &filter=Filter(), bool countOnly=false)
bool GetMoviesNav (const std::string &strBaseDir, CFileItemList &items, int idGenre=-1, int idYear=-1, int idActor=-1, int idDirector=-1, int idStudio=-1, int idCountry=-1, int idSet=-1, int idTag=-1, const SortDescription &sortDescription=SortDescription(), int getDetails=VideoDbDetailsNone)
bool GetTvShowsNav (const std::string &strBaseDir, CFileItemList &items, int idGenre=-1, int idYear=-1, int idActor=-1, int idDirector=-1, int idStudio=-1, int idTag=-1, const SortDescription &sortDescription=SortDescription(), int getDetails=VideoDbDetailsNone)
bool GetSeasonsNav (const std::string &strBaseDir, CFileItemList &items, int idActor=-1, int idDirector=-1, int idGenre=-1, int idYear=-1, int idShow=-1, bool getLinkedMovies=true)
bool GetEpisodesNav (const std::string &strBaseDir, CFileItemList &items, int idGenre=-1, int idYear=-1, int idActor=-1, int idDirector=-1, int idShow=-1, int idSeason=-1, const SortDescription &sortDescription=SortDescription(), int getDetails=VideoDbDetailsNone)
bool GetMusicVideosNav (const std::string &strBaseDir, CFileItemList &items, int idGenre=-1, int idYear=-1, int idArtist=-1, int idDirector=-1, int idStudio=-1, int idAlbum=-1, int idTag=-1, const SortDescription &sortDescription=SortDescription(), int getDetails=VideoDbDetailsNone)
bool GetRecentlyAddedMoviesNav (const std::string &strBaseDir, CFileItemList &items, unsigned int limit=0, int getDetails=VideoDbDetailsNone)
bool GetRecentlyAddedEpisodesNav (const std::string &strBaseDir, CFileItemList &items, unsigned int limit=0, int getDetails=VideoDbDetailsNone)
bool GetRecentlyAddedMusicVideosNav (const std::string &strBaseDir, CFileItemList &items, unsigned int limit=0, int getDetails=VideoDbDetailsNone)
bool GetInProgressTvShowsNav (const std::string &strBaseDir, CFileItemList &items, unsigned int limit=0, int getDetails=VideoDbDetailsNone)
bool HasContent ()
bool HasContent (VideoDbContentType type)
bool HasSets () const
void CleanDatabase (CGUIDialogProgressBarHandle *handle=NULL, const std::set< int > &paths=std::set< int >(), bool showProgress=true)
int AddFile (const std::string &url, const std::string &parentPath="", const CDateTime &dateAdded=CDateTime(), int playcount=0, const CDateTime &lastPlayed=CDateTime())
Add a file to the database, if necessary If the file is already in the database, we simply return its id.
int AddFile (const CFileItem &item)
Add a file to the database, if necessary Works for both videodb:// items and normal fileitems.
int AddFile (const CVideoInfoTag &details, const std::string &parentPath="")
Add a file to the database, if necessary Works for both videodb:// items and normal fileitems.
int AddPath (const std::string &strPath, const std::string &parentPath="", const CDateTime &dateAdded=CDateTime())
Add a path to the database, if necessary If the path is already in the database, we simply return its id.
void UpdateFileDateAdded (CVideoInfoTag &details)
Updates the dateAdded field in the files table for the file with the given idFile and the given path based on the files modification date.
void ExportToXML (const std::string &path, bool singleFile=true, bool images=false, bool actorThumbs=false, bool overwrite=false)
void ExportActorThumbs (const std::string &path, const CVideoInfoTag &tag, bool singleFiles, bool overwrite=false)
void ImportFromXML (const std::string &path)
void DumpToDummyFiles (const std::string &path)
bool ImportArtFromXML (const TiXmlNode *node, std::map< std::string, std::string > &artwork)
bool GetMoviesByWhere (const std::string &strBaseDir, const Filter &filter, CFileItemList &items, const SortDescription &sortDescription=SortDescription(), int getDetails=VideoDbDetailsNone)
bool GetSetsByWhere (const std::string &strBaseDir, const Filter &filter, CFileItemList &items, bool ignoreSingleMovieSets=false)
bool GetTvShowsByWhere (const std::string &strBaseDir, const Filter &filter, CFileItemList &items, const SortDescription &sortDescription=SortDescription(), int getDetails=VideoDbDetailsNone)
bool GetSeasonsByWhere (const std::string &strBaseDir, const Filter &filter, CFileItemList &items, bool appendFullShowPath=true, const SortDescription &sortDescription=SortDescription())
bool GetEpisodesByWhere (const std::string &strBaseDir, const Filter &filter, CFileItemList &items, bool appendFullShowPath=true, const SortDescription &sortDescription=SortDescription(), int getDetails=VideoDbDetailsNone)
bool GetMusicVideosByWhere (const std::string &baseDir, const Filter &filter, CFileItemList &items, bool checkLocks=true, const SortDescription &sortDescription=SortDescription(), int getDetails=VideoDbDetailsNone)
bool GetSortedVideos (const MediaType &mediaType, const std::string &strBaseDir, const SortDescription &sortDescription, CFileItemList &items, const Filter &filter=Filter())
bool GetItems (const std::string &strBaseDir, CFileItemList &items, const Filter &filter=Filter(), const SortDescription &sortDescription=SortDescription())
bool GetItems (const std::string &strBaseDir, const std::string &mediaType, const std::string &itemType, CFileItemList &items, const Filter &filter=Filter(), const SortDescription &sortDescription=SortDescription())
bool GetItems (const std::string &strBaseDir, VideoDbContentType mediaType, const std::string &itemType, CFileItemList &items, const Filter &filter=Filter(), const SortDescription &sortDescription=SortDescription())
std::string GetItemById (const std::string &itemType, int id)
unsigned int GetRandomMusicVideoIDs (const std::string &strWhere, std::vector< std::pair< int, int > > &songIDs)
Gets music video IDs in random order that match the where clause.
void SetArtForItem (int mediaId, const MediaType &mediaType, const std::string &artType, const std::string &url)
void SetArtForItem (int mediaId, const MediaType &mediaType, const std::map< std::string, std::string > &art)
bool GetArtForItem (int mediaId, const MediaType &mediaType, std::map< std::string, std::string > &art)
std::string GetArtForItem (int mediaId, const MediaType &mediaType, const std::string &artType)
void UpdateArtForItem (int mediaId, const MediaType &mediaType)
bool GetArtForAsset (int assetId, ArtFallbackOptions fallback, std::map< std::string, std::string > &art)
Retrieve all art for the given video asset, with optional fallback to the art of the parent/owner of the asset.
bool HasArtForItem (int mediaId, const MediaType &mediaType)
bool RemoveArtForItem (int mediaId, const MediaType &mediaType, const std::string &artType)
bool RemoveArtForItem (int mediaId, const MediaType &mediaType, const std::set< std::string > &artTypes)
bool GetTvShowSeasons (int showId, std::map< int, int > &seasons)
bool GetTvShowNamedSeasons (int showId, std::map< int, std::string > &seasons)
std::string GetTvShowNamedSeasonById (int tvshowId, int seasonId)
Get the custom named season.
bool GetTvShowSeasonArt (int mediaId, std::map< int, std::map< std::string, std::string > > &seasonArt)
bool GetArtTypes (const MediaType &mediaType, std::vector< std::string > &artTypes)
std::vector< std::string > GetAvailableArtTypesForItem (int mediaId, const MediaType &mediaType)
Fetch the distinct types of available-but-unassigned art held in the database for a specific media item.
std::vector< CScraperUrl::SUrlEntry > GetAvailableArtForItem (int mediaId, const MediaType &mediaType, const std::string &artType)
Fetch the list of available-but-unassigned art URLs held in the database for a specific media item and art type.
int AddTag (const std::string &tag)
void AddTagToItem (int idItem, int idTag, const std::string &type)
void RemoveTagFromItem (int idItem, int idTag, const std::string &type)
void RemoveTagsFromItem (int idItem, const std::string &type)
bool GetFilter (CDbUrl &videoUrl, Filter &filter, SortDescription &sorting) override
int AddSeason (int showID, int season, const std::string &name="")
Will check if the season exists and if that is not the case add it to the database.
int AddSet (const std::string &strSet, const std::string &strOverview="", const bool updateOverview=true)
void ClearMovieSet (int idMovie)
void SetMovieSet (int idMovie, int idSet)
bool SetVideoUserRating (int dbId, int rating, const MediaType &mediaType)
bool GetUseAllExternalAudioForVideo (const std::string &videoPath)
std::string GetSetByNameLike (const std::string &nameLike) const
std::string GetVideoItemTitle (VideoDbContentType itemType, int dbId)
std::string GetVideoVersionById (int id)
void GetVideoVersions (VideoDbContentType itemType, int dbId, CFileItemList &items, VideoAssetType videoAssetType)
void GetDefaultVideoVersion (VideoDbContentType itemType, int dbId, CFileItem &item)
bool ConvertVideoToVersion (VideoDbContentType itemType, int dbIdSource, int dbIdTarget, int idVideoVersion, VideoAssetType assetType)
Remove a video from the library and transfer all of its assets to another video of the same type.
void SetDefaultVideoVersion (VideoDbContentType itemType, int dbId, int idFile)
void SetVideoVersion (int idFile, int idVideoVersion)
int AddVideoVersionType (const std::string &typeVideoVersion, VideoAssetTypeOwner owner, VideoAssetType assetType)
void AddVideoAsset (VideoDbContentType itemType, int dbId, int idVideoVersion, VideoAssetType videoAssetType, CFileItem &item)
bool DeleteVideoAsset (int idFile)
bool IsDefaultVideoVersion (int idFile)
bool GetVideoVersionTypes (VideoDbContentType idContent, VideoAssetType asset, CFileItemList &items)
void SetVideoVersionDefaultArt (int dbId, int idFrom, VideoDbContentType type)
void InitializeVideoVersionTypeTable (int schemaVersion)
void UpdateVideoVersionTypeTable ()
bool GetVideoVersionsNav (const std::string &strBaseDir, CFileItemList &items, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter())
VideoAssetInfo GetVideoVersionInfo (const std::string &filenameAndPath)
bool GetAssetsForVideo (VideoDbContentType itemType, int mediaId, VideoAssetType assetType, CFileItemList &items)
bool GetDefaultVersionForVideo (VideoDbContentType itemType, int mediaId, CFileItem &item)
bool UpdateAssetsOwner (const std::string &mediaType, int dbIdSource, int dbIdTarget)
int GetMovieId (const std::string &strFilenameAndPath)
std::string GetMovieTitle (int idMovie)
void GetSameVideoItems (const CFileItem &item, CFileItemList &items)
int GetFileIdByMovie (int idMovie)
std::string GetFileBasePathById (int idFile)
std::vector< std::string > GetUsedImages (const std::vector< std::string > &imagesToCheck)
Check the passed in list of images if used in this database. Used to clean the image cache.
Public Member Functions inherited from CDatabase
CDatabase ()
virtual ~CDatabase (void)
bool IsOpen ()
virtual void Close ()
bool Compress (bool bForce=true)
void Interrupt ()
bool Open (const DatabaseSettings &db)
void BeginTransaction ()
void RollbackTransaction ()
void CopyDB (const std::string &latestDb)
void DropAnalytics ()
std::string PrepareSQL (std::string strStmt,...) const
std::string GetSingleValue (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single value from a table.
std::string GetSingleValue (const std::string &query) const
std::string GetSingleValue (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single value from a query on a dataset.
int GetSingleValueInt (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single integer value from a table.
int GetSingleValueInt (const std::string &query) const
int GetSingleValueInt (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single integer value from a query on a dataset.
bool DeleteValues (const std::string &strTable, const Filter &filter=Filter())
Delete values from a table.
bool ExecuteQuery (const std::string &strQuery)
Execute a query that does not return any result. Note that if BeginMultipleExecute() has been called, the query will be queued until CommitMultipleExecute() is called.
bool ResultQuery (const std::string &strQuery) const
Execute a query that returns a result.
bool BeginMultipleExecute ()
Start a multiple execution queue. Any ExecuteQuery() function following this call will be queued rather than executed until CommitMultipleExecute() is performed. NOTE: Queries that rely on any queued execute query will not function as expected during this period!
bool CommitMultipleExecute ()
Commit the multiple execution queue to the database. Queries are performed within a transaction, and the transaction is rolled back should any one query fail.
bool QueueInsertQuery (const std::string &strQuery)
Put an INSERT or REPLACE query in the queue.
bool CommitInsertQueries ()
Commit all queries in the queue.
size_t GetInsertQueriesCount ()
Get the number of INSERT queries in the queue.
bool QueueDeleteQuery (const std::string &strQuery)
Put a DELETE query in the queue.
bool CommitDeleteQueries ()
Commit all queued DELETE queries.
size_t GetDeleteQueriesCount ()
Get the number of DELETE queries in the queue.
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl)
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl, SortDescription &sorting)
bool Connect (const std::string &dbName, const DatabaseSettings &db, bool create)
Static Public Member Functions
static void VideoContentTypeToString (VideoDbContentType type, std::string &out)
Protected Member Functions
int AddNewMovie (CVideoInfoTag &details)
int AddNewMusicVideo (CVideoInfoTag &details)
int GetMusicVideoId (const std::string &strFilenameAndPath)
int GetFileId (const CFileItem &item)
Get the id of this fileitem Works for both videodb:// items and normal fileitems.
int GetFileId (const CVideoInfoTag &details)
int GetAndFillFileId (CVideoInfoTag &details)
Get the id of the file of this item and store it in the item.
int GetFileId (const std::string &url)
Get the id of a file from path.
int AddToTable (const std::string &table, const std::string &firstField, const std::string &secondField, const std::string &value)
int UpdateRatings (int mediaId, const char *mediaType, const RatingMap &values, const std::string &defaultRating)
int AddRatings (int mediaId, const char *mediaType, const RatingMap &values, const std::string &defaultRating)
int UpdateUniqueIDs (int mediaId, const char *mediaType, const CVideoInfoTag &details)
int AddUniqueIDs (int mediaId, const char *mediaType, const CVideoInfoTag &details)
int AddActor (const std::string &strActor, const std::string &thumbURL, const std::string &thumb="")
int AddTvShow ()
bool AddPathToTvShow (int idShow, const std::string &path, const std::string &parentPath, const CDateTime &dateAdded=CDateTime())
Adds a path to the tvshow link table.
int GetMatchingTvShow (const CVideoInfoTag &show)
Check whether a show is already in the library. Matches on unique identifier or matching title and premiered date.
void AddLinkToActor (int mediaId, const char *mediaType, int actorId, const std::string &role, int order)
void AddToLinkTable (int mediaId, const std::string &mediaType, const std::string &table, int valueId, const char *foreignKey=NULL)
void RemoveFromLinkTable (int mediaId, const std::string &mediaType, const std::string &table, int valueId, const char *foreignKey=NULL)
void AddLinksToItem (int mediaId, const std::string &mediaType, const std::string &field, const std::vector< std::string > &values)
void UpdateLinksToItem (int mediaId, const std::string &mediaType, const std::string &field, const std::vector< std::string > &values)
void AddActorLinksToItem (int mediaId, const std::string &mediaType, const std::string &field, const std::vector< std::string > &values)
void UpdateActorLinksToItem (int mediaId, const std::string &mediaType, const std::string &field, const std::vector< std::string > &values)
void AddCast (int mediaId, const char *mediaType, const std::vector< SActorInfo > &cast)
CVideoInfoTag GetDetailsForMovie (std::unique_ptr< dbiplus::Dataset > &pDS, int getDetails=VideoDbDetailsNone)
CVideoInfoTag GetDetailsForMovie (const dbiplus::sql_record *const record, int getDetails=VideoDbDetailsNone)
CVideoInfoTag GetDetailsForTvShow (std::unique_ptr< dbiplus::Dataset > &pDS, int getDetails=VideoDbDetailsNone, CFileItem *item=NULL)
CVideoInfoTag GetDetailsForTvShow (const dbiplus::sql_record *const record, int getDetails=VideoDbDetailsNone, CFileItem *item=NULL)
CVideoInfoTag GetBasicDetailsForEpisode (std::unique_ptr< dbiplus::Dataset > &pDS)
CVideoInfoTag GetBasicDetailsForEpisode (const dbiplus::sql_record *const record)
CVideoInfoTag GetDetailsForEpisode (std::unique_ptr< dbiplus::Dataset > &pDS, int getDetails=VideoDbDetailsNone)
CVideoInfoTag GetDetailsForEpisode (const dbiplus::sql_record *const record, int getDetails=VideoDbDetailsNone)
CVideoInfoTag GetDetailsForMusicVideo (std::unique_ptr< dbiplus::Dataset > &pDS, int getDetails=VideoDbDetailsNone)
CVideoInfoTag GetDetailsForMusicVideo (const dbiplus::sql_record *const record, int getDetails=VideoDbDetailsNone)
bool GetPeopleNav (const std::string &strBaseDir, CFileItemList &items, const char *type, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter(), bool countOnly=false)
bool GetNavCommon (const std::string &strBaseDir, CFileItemList &items, const char *type, VideoDbContentType idContent=VideoDbContentType::UNKNOWN, const Filter &filter=Filter(), bool countOnly=false)
void GetCast (int media_id, const std::string &media_type, std::vector< SActorInfo > &cast)
void GetTags (int media_id, const std::string &media_type, std::vector< std::string > &tags)
void GetRatings (int media_id, const std::string &media_type, RatingMap &ratings)
void GetUniqueIDs (int media_id, const std::string &media_type, CVideoInfoTag &details)
void GetDetailsFromDB (std::unique_ptr< dbiplus::Dataset > &pDS, int min, int max, const SDbTableOffsets *offsets, CVideoInfoTag &details, int idxOffset=2)
void GetDetailsFromDB (const dbiplus::sql_record *const record, int min, int max, const SDbTableOffsets *offsets, CVideoInfoTag &details, int idxOffset=2)
std::string GetValueString (const CVideoInfoTag &details, int min, int max, const SDbTableOffsets *offsets) const
Protected Member Functions inherited from CDatabase
void Split (const std::string &strFileNameAndPath, std::string &strPath, std::string &strFileName)
bool CreateDatabase ()
Create database tables and analytics as needed. Calls CreateTables() and CreateAnalytics() on child classes.
int GetDBVersion ()
bool BuildSQL (const std::string &strQuery, const Filter &filter, std::string &strSQL) const
Private Member Functions
void CreateTables () override
void CreateAnalytics () override
void UpdateTables (int version) override
void CreateLinkIndex (const char *table)
void CreateForeignLinkIndex (const char *table, const char *foreignkey)
virtual void CreateViews ()
(Re)Create the generic database views for movies, tvshows, episodes and music videos
int GetDbId (const std::string &query)
Helper to get a database id given a query. Returns an integer, -1 if not found, and greater than 0 if found.
int RunQuery (const std::string &sql)
Run a query on the main dataset and return the number of rows If no rows are found we close the dataset and return 0.
void AppendIdLinkFilter (const char *field, const char *table, const MediaType &mediaType, const char *view, const char *viewKey, const CUrlOptions::UrlOptions &options, Filter &filter)
void AppendLinkFilter (const char *field, const char *table, const MediaType &mediaType, const char *view, const char *viewKey, const CUrlOptions::UrlOptions &options, Filter &filter)
bool LookupByFolders (const std::string &path, bool shows=false)
Determine whether the path is using lookup using folders.
int GetPlayCount (int iFileId)
Get the playcount for a file id.
CDateTime GetLastPlayed (int iFileId)
Get the last played time of a filename and path.
bool GetSeasonInfo (int idSeason, CVideoInfoTag &details, bool allDetails, CFileItem *item)
int GetMinSchemaVersion () const override
int GetSchemaVersion () const override
virtual int GetExportVersion () const
const char * GetBaseDBName () const override
void ConstructPath (std::string &strDest, const std::string &strPath, const std::string &strFileName)
void SplitPath (const std::string &strFileNameAndPath, std::string &strPath, std::string &strFileName)
void InvalidatePathHash (const std::string &strPath)
std::string GetSafeFile (const std::string &dir, const std::string &name) const
Get a safe filename from a given string.
std::vector< int > CleanMediaType (const std::string &mediaType, const std::string &cleanableFileIDs, std::map< int, bool > &pathsDeleteDecisions, std::string &deletedFileIDs, bool silent)
bool FillMovieItem (std::unique_ptr< dbiplus::Dataset > &dataset, int movieId, CFileItem &item)
Static Private Member Functions
static void AnnounceRemove (const std::string &content, int id, bool scanning=false)
static void AnnounceUpdate (const std::string &content, int id)
static CDateTime GetDateAdded (const std::string &filename, CDateTime dateAdded=CDateTime())
Additional Inherited Members
Protected Attributes inherited from CDatabase
bool m_sqlite
whether we use sqlite (defaults to true)
std::unique_ptr< dbiplus::Database > m_pDB
std::unique_ptr< dbiplus::Dataset > m_pDS
std::unique_ptr< dbiplus::Dataset > m_pDS2
const CProfileManager & m_profileManager
Constructor & Destructor Documentation
CVideoDatabase()
CVideoDatabase::CVideoDatabase (void) default
~CVideoDatabase()
CVideoDatabase::~CVideoDatabase (void) override default
Member Function Documentation
AddActor()
int CVideoDatabase::AddActor (const std::string & strActor, const std::string & thumbURL, const std::string & thumb = "") protected
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, name, CDatabase::PrepareSQL(), and SetArtForItem().
Referenced by AddActorLinksToItem(), and AddCast().
AddActorLinksToItem()
void CVideoDatabase::AddActorLinksToItem (int mediaId, const std::string & mediaType, const std::string & field, const std::vector< std::string > & values) protected
References AddActor(), AddToLinkTable(), and values.
Referenced by SetDetailsForEpisode(), SetDetailsForMovie(), SetDetailsForMusicVideo(), UpdateActorLinksToItem(), and UpdateDetailsForTvShow().
AddBookMarkForEpisode()
void CVideoDatabase::AddBookMarkForEpisode (const CVideoInfoTag & tag, const CBookmark & bookmark)
References AddBookMarkToFile(), CBookmark::EPISODE, GetFileId(), CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), VIDEODB_ID_EPISODE_BOOKMARK, VIDEODB_ID_EPISODE_EPISODE, and VIDEODB_ID_EPISODE_SEASON.
Referenced by CGUIDialogVideoBookmarks::AddBookmark().
AddBookMarkToFile()
void CVideoDatabase::AddBookMarkToFile (const std::string & strFilenameAndPath, const CBookmark & bookmark, CBookmark::EType type = CBookmark::STANDARD)
References AddFile(), CBookmark::EPISODE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CBookmark::player, CBookmark::playerState, CDatabase::PrepareSQL(), CBookmark::RESUME, CBookmark::STANDARD, CBookmark::thumbNailImage, CBookmark::timeInSeconds, and CBookmark::totalTimeInSeconds.
Referenced by CGUIDialogVideoBookmarks::AddBookmark(), AddBookMarkForEpisode(), CSaveFileState::DoWork(), UPNP::CUPnPServer::OnUpdateObject(), and JSONRPC::CVideoLibrary::UpdateResumePoint().
AddCast()
void CVideoDatabase::AddCast (int mediaId, const char * mediaType, const std::vector< SActorInfo > & cast) protected
References AddActor(), and AddLinkToActor().
Referenced by SetDetailsForEpisode(), SetDetailsForMovie(), SetDetailsForMusicVideo(), and UpdateDetailsForTvShow().
AddFile() [1/3]
int CVideoDatabase::AddFile (const CFileItem & item)
Add a file to the database, if necessary Works for both videodb:// items and normal fileitems.
Parameters
item CFileItem to add.
Returns
id of the file, -1 if it could not be added.
References AddFile(), CFileItem::GetPath(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), KODI::VIDEO::IsVideoDb(), and CVideoInfoTag::m_iFileId.
AddFile() [2/3]
int CVideoDatabase::AddFile (const CVideoInfoTag & details, const std::string & parentPath = "")
Add a file to the database, if necessary Works for both videodb:// items and normal fileitems.
Parameters
url full path of the file to add.
details details of the item to add.
Returns
id of the file, -1 if it could not be added.
References AddFile(), CVideoInfoTag::GetPath(), CVideoInfoTag::GetPlayCount(), CVideoInfoTag::m_dateAdded, and CVideoInfoTag::m_lastPlayed.
AddFile() [3/3]
int CVideoDatabase::AddFile (const std::string & url, const std::string & parentPath = "", const CDateTime & dateAdded = CDateTime(), int playcount = 0, const CDateTime & lastPlayed = CDateTime())
Add a file to the database, if necessary If the file is already in the database, we simply return its id.
Parameters
url - full path of the file to add.
parentPath the parent path of the path to add. If empty, URIUtils::GetParentPath() will determine the path.
dateAdded datetime when the file was added to the filesystem/database
playcount the playcount of the file to add.
lastPlayed the date and time when the file to add was last played.
Returns
id of the file, -1 if it could not be added.
References AddPath(), CDateTime::GetAsDBDateTime(), GetDateAdded(), CDateTime::IsValid(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddBookMarkToFile(), AddFile(), AddFile(), AddNewEpisode(), AddNewMovie(), AddNewMusicVideo(), AddVideoAsset(), JSONRPC::CFileOperations::SetFileDetails(), SetPlayCount(), SetStackTimes(), SetStreamDetailsForFile(), and SetVideoSettings().
AddLinksToItem()
void CVideoDatabase::AddLinksToItem (int mediaId, const std::string & mediaType, const std::string & field, const std::vector< std::string > & values) protected
References AddToLinkTable(), AddToTable(), and values.
Referenced by SetDetailsForMovie(), SetDetailsForMusicVideo(), UpdateDetailsForTvShow(), and UpdateLinksToItem().
AddLinkToActor()
void CVideoDatabase::AddLinkToActor (int mediaId, const char * mediaType, int actorId, const std::string & role, int order) protected
References CDatabase::ExecuteQuery(), CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by AddCast().
AddNewEpisode()
int CVideoDatabase::AddNewEpisode (int idShow, CVideoInfoTag & details)
References AddFile(), CVideoInfoTag::GetPath(), CLog::Log(), LOGERROR, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iFileId, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by SetDetailsForEpisode().
AddNewMovie()
int CVideoDatabase::AddNewMovie (CVideoInfoTag & details) protected
References AddFile(), CVideoInfoTag::GetPath(), CLog::Log(), LOGERROR, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iFileId, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMovie, CDatabase::PrepareSQL(), VERSION, and VIDEO_VERSION_ID_DEFAULT.
Referenced by SetDetailsForMovie().
AddNewMusicVideo()
int CVideoDatabase::AddNewMusicVideo (CVideoInfoTag & details) protected
References AddFile(), CVideoInfoTag::GetPath(), CLog::Log(), LOGERROR, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iFileId, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by SetDetailsForMusicVideo().
AddPath()
int CVideoDatabase::AddPath (const std::string & strPath, const std::string & parentPath = "", const CDateTime & dateAdded = CDateTime())
Add a path to the database, if necessary If the path is already in the database, we simply return its id.
Parameters
strPath the path to add
parentPath the parent path of the path to add. If empty, URIUtils::GetParentPath() will determine the path.
dateAdded datetime when the path was added to the filesystem/database
Returns
id of the file, -1 if it could not be added.
References URIUtils::AddSlashAtEnd(), CDateTime::GetAsDBDateTime(), URIUtils::GetParentPath(), GetPathId(), URIUtils::IsStack(), CDateTime::IsValid(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddFile(), AddPathToTvShow(), ImportFromXML(), SetPathHash(), SetScraperForPath(), and UpdateTables().
AddPathToTvShow()
bool CVideoDatabase::AddPathToTvShow (int idShow, const std::string & path, const std::string & parentPath, const CDateTime & dateAdded = CDateTime()) protected
Adds a path to the tvshow link table.
Parameters
idShow the id of the show.
path the path to add.
parentPath the parent path of the path to add.
dateAdded date/time when the path was added
Returns
true if successfully added, false otherwise.
References AddPath(), CDatabase::ExecuteQuery(), GetDateAdded(), GetPathId(), and CDatabase::PrepareSQL().
Referenced by SetDetailsForTvShow().
AddRatings()
int CVideoDatabase::AddRatings (int mediaId, const char * mediaType, const RatingMap & values, const std::string & defaultRating) protected
References id, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and values.
Referenced by SetDetailsForEpisode(), SetDetailsForMovie(), UpdateDetailsForTvShow(), and UpdateRatings().
AddSeason()
int CVideoDatabase::AddSeason (int showID, int season, const std::string & name = "")
Will check if the season exists and if that is not the case add it to the database.
Parameters
showID The id of the show in question.
season The season number we want to add.
Returns
The dbId of the season.
References CDatabase::ExecuteQuery(), GetSeasonId(), CDatabase::m_pDS, name, and CDatabase::PrepareSQL().
Referenced by ImportFromXML(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForEpisodes(), SetDetailsForEpisode(), SetDetailsForSeason(), and UpdateDetailsForTvShow().
AddSet()
int CVideoDatabase::AddSet (const std::string & strSet, const std::string & strOverview = "", const bool updateOverview = true)
References id, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIDialogVideoInfo::GetSetForMovie(), SetDetailsForMovie(), SetDetailsForMovieSet(), and UpdateDetailsForMovie().
AddTag()
int CVideoDatabase::AddTag (const std::string & tag)
References AddToTable(), and name.
Referenced by CGUIWindowVideoNav::OnClick().
AddTagToItem()
void CVideoDatabase::AddTagToItem (int idItem, int idTag, const std::string & type)
References AddToLinkTable().
Referenced by CGUIDialogVideoInfo::AddItemsToTag(), and CGUIWindowVideoNav::OnClick().
AddToLinkTable()
void CVideoDatabase::AddToLinkTable (int mediaId, const std::string & mediaType, const std::string & table, int valueId, const char * foreignKey = NULL) protected
References CDatabase::ExecuteQuery(), CDatabase::GetSingleValue(), CDatabase::PrepareSQL(), and table.
Referenced by AddActorLinksToItem(), AddLinksToItem(), and AddTagToItem().
AddToTable()
int CVideoDatabase::AddToTable (const std::string & table, const std::string & firstField, const std::string & secondField, const std::string & value) protected
References id, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), table, and value.
Referenced by AddLinksToItem(), and AddTag().
AddTvShow()
int CVideoDatabase::AddTvShow () protected
References CDatabase::ExecuteQuery(), and CDatabase::m_pDS.
Referenced by SetDetailsForTvShow().
AddUniqueIDs()
int CVideoDatabase::AddUniqueIDs (int mediaId, const char * mediaType, const CVideoInfoTag & details) protected
References CVideoInfoTag::GetDefaultUniqueID(), CVideoInfoTag::GetUniqueIDs(), id, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by SetDetailsForEpisode(), SetDetailsForMovie(), UpdateDetailsForTvShow(), and UpdateUniqueIDs().
AddVideoAsset()
void CVideoDatabase::AddVideoAsset (VideoDbContentType itemType, int dbId, int idVideoVersion, VideoAssetType videoAssetType, CFileItem & item)
References AddFile(), CDatabase::BeginTransaction(), CommitTransaction(), CFileItem::GetPath(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::HasStreamDetails(), LOGERROR, CVideoInfoTag::m_iDbId, CDatabase::m_pDB, CDatabase::m_pDS, CVideoInfoTag::m_streamDetails, MediaTypeMovie, MOVIES, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), SetStreamDetailsForFileId(), SetVideoVersionDefaultArt(), and VERSION.
Referenced by CGUIDialogVideoManagerExtras::AddVideoExtra(), and CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker().
AddVideoVersionType()
int CVideoDatabase::AddVideoVersionType (const std::string & typeVideoVersion, VideoAssetTypeOwner owner, VideoAssetType assetType)
References id, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, owner, CDatabase::PrepareSQL(), SYSTEM, and USER.
Referenced by CGUIDialogVideoManagerExtras::AddVideoExtra(), and CGUIDialogVideoManager::ChooseVideoAsset().
AnnounceRemove()
void CVideoDatabase::AnnounceRemove (const std::string & content, int id, bool scanning = false) static private
References ADDON::content, data(), CServiceBroker::GetAnnouncementManager(), id, and ANNOUNCEMENT::VideoLibrary.
Referenced by CleanDatabase(), DeleteEpisode(), DeleteMovie(), DeleteMusicVideo(), and DeleteTvShow().
AnnounceUpdate()
void CVideoDatabase::AnnounceUpdate (const std::string & content, int id) static private
References ADDON::content, data(), CServiceBroker::GetAnnouncementManager(), id, and ANNOUNCEMENT::VideoLibrary.
Referenced by DeleteResumeBookMark(), UpdateArtForItem(), UpdateFanart(), UpdateMovieTitle(), and UpdateVideoSortTitle().
AppendIdLinkFilter()
void CVideoDatabase::AppendIdLinkFilter (const char * field, const char * table, const MediaType & mediaType, const char * view, const char * viewKey, const CUrlOptions::UrlOptions & options, Filter & filter) private
References CDatabase::Filter::AppendJoin(), CDatabase::Filter::AppendWhere(), CDatabase::PrepareSQL(), and table.
Referenced by GetFilter().
AppendLinkFilter()
void CVideoDatabase::AppendLinkFilter (const char * field, const char * table, const MediaType & mediaType, const char * view, const char * viewKey, const CUrlOptions::UrlOptions & options, Filter & filter) private
References CDatabase::Filter::AppendJoin(), CDatabase::Filter::AppendWhere(), CDatabase::PrepareSQL(), and table.
Referenced by GetFilter().
CleanDatabase()
void CVideoDatabase::CleanDatabase (CGUIDialogProgressBarHandle * handle = NULL, const std::set< int > & paths = std::set<int>(), bool showProgress = true)
References AnnounceRemove(), CDatabase::BeginTransaction(), XFILE::CPluginDirectory::CheckExists(), CleanMediaType(), CGUIWindow::Close(), CommitTransaction(), CDatabase::Compress(), ConstructPath(), CUtil::DeleteVideoDatabaseDirectoryCache(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, end(), exists(), XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAnnouncementManager(), XFILE::CDirectory::GetDirectory(), URIUtils::GetDirectory(), XFILE::CStackDirectory::GetFirstStackedFile(), CServiceBroker::GetGUI(), CURL::GetHostName(), CMediaSourceSettings::GetInstance(), CUtil::GetMatchingSource(), CServiceBroker::GetMediaManager(), CGUIDialogProgress::GetPercentage(), CMediaManager::GetRemovableDrives(), GetScraperForPath(), CGUIComponent::GetWindowManager(), InvalidatePathHash(), CGUIDialogProgress::IsCanceled(), URIUtils::IsInArchive(), URIUtils::IsOnDVD(), URIUtils::IsPlugin(), URIUtils::IsStack(), CLog::Log(), LOGDATABASE, LOGDEBUG, LOGERROR, LOGINFO, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MediaTypeVideoVersion, CGUIDialogProgress::Open(), CDatabase::PrepareSQL(), CGUIDialogProgress::Progress(), CDatabase::RollbackTransaction(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CGUIDialogProgressBarHandle::SetPercentage(), CGUIDialogProgress::SetPercentage(), CGUIDialogProgressBarHandle::SetText(), CGUIDialogProgressBarHandle::SetTitle(), CGUIDialogProgress::ShowProgressBar(), ADDON::TranslateContent(), VIDEODB_ID_EPISODE_PARENTPATHID, VIDEODB_ID_MUSICVIDEO_PARENTPATHID, VIDEODB_ID_PARENTPATHID, ANNOUNCEMENT::VideoLibrary, and WINDOW_DIALOG_PROGRESS.
Referenced by KODI::VIDEO::CVideoInfoScanner::Process(), and CVideoLibraryCleaningJob::Work().
CleanMediaType()
std::vector< int > CVideoDatabase::CleanMediaType (const std::string & mediaType, const std::string & cleanableFileIDs, std::map< int, bool > & pathsDeleteDecisions, std::string & deletedFileIDs, bool silent) private
References XFILE::CDirectory::Exists(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CMediaSourceSettings::GetInstance(), CUtil::GetMatchingSource(), CServiceBroker::GetMediaManager(), GetPathId(), CMediaManager::GetRemovableDrives(), GetSourcePath(), CGUIComponent::GetWindowManager(), CURL::GetWithoutUserDetails(), CGUIDialogBoxBase::IsConfirmed(), CDatabase::m_pDS2, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeVideoVersion, CGUIDialog::Open(), KODI::VIDEO::SScanSettings::parent_name, CDatabase::PrepareSQL(), CGUIDialogBoxBase::SetChoice(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetText(), table, VIDEODB_ID_MUSICVIDEO_PARENTPATHID, VIDEODB_ID_PARENTPATHID, and WINDOW_DIALOG_YES_NO.
Referenced by CleanDatabase().
ClearBookMarkOfFile()
void CVideoDatabase::ClearBookMarkOfFile (const std::string & strFilenameAndPath, CBookmark & bookmark, CBookmark::EType type = CBookmark::STANDARD)
References CBookmark::EPISODE, GetFileId(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CBookmark::player, CBookmark::playerState, CDatabase::PrepareSQL(), CBookmark::timeInSeconds, and VIDEODB_ID_EPISODE_BOOKMARK.
Referenced by CGUIDialogVideoBookmarks::Delete().
ClearBookMarksOfFile() [1/2]
void CVideoDatabase::ClearBookMarksOfFile (const std::string & strFilenameAndPath, CBookmark::EType type = CBookmark::STANDARD)
References ClearBookMarksOfFile(), and GetFileId().
Referenced by PVR::CPVRRecordings::ChangeRecordingsPlayCount(), CGUIDialogVideoBookmarks::ClearBookmarks(), ClearBookMarksOfFile(), CSaveFileState::DoWork(), UPNP::CUPnPServer::OnUpdateObject(), PVR::CPVRRecordings::ResetResumePoint(), JSONRPC::CVideoLibrary::UpdateResumePoint(), and CVideoLibraryMarkWatchedJob::Work().
ClearBookMarksOfFile() [2/2]
void CVideoDatabase::ClearBookMarksOfFile (int idFile, CBookmark::EType type = CBookmark::STANDARD)
References CBookmark::EPISODE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and VIDEODB_ID_EPISODE_BOOKMARK.
ClearMovieSet()
void CVideoDatabase::ClearMovieSet (int idMovie)
References SetMovieSet().
CommitTransaction()
bool CVideoDatabase::CommitTransaction () override virtual
Reimplemented from CDatabase.
References CDatabase::CommitTransaction(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetLibraryInfoProvider(), HasContent(), LIBRARY_HAS_MOVIES, LIBRARY_HAS_MUSICVIDEOS, LIBRARY_HAS_TVSHOWS, MOVIES, MUSICVIDEOS, KODI::GUILIB::GUIINFO::CLibraryGUIInfo::SetLibraryBool(), and TVSHOWS.
Referenced by AddVideoAsset(), CleanDatabase(), ConvertVideoToVersion(), DeleteMovie(), DeleteMusicVideo(), DeleteSeason(), DeleteTvShow(), DeleteVideoAsset(), CSaveFileState::DoWork(), CVideoThumbLoader::LoadItemLookup(), SetDetailsForEpisode(), SetDetailsForMovie(), SetDetailsForMovieSet(), SetDetailsForMusicVideo(), SetDetailsForSeason(), UpdateDetailsForMovie(), UpdateDetailsForTvShow(), UpdateVideoVersionTypeTable(), CVideoLibraryMarkWatchedJob::Work(), and CVideoLibraryResetResumePointJob::Work().
ConstructPath()
void CVideoDatabase::ConstructPath (std::string & strDest, const std::string & strPath, const std::string & strFileName) private
References URIUtils::AddFileToFolder(), URIUtils::IsInArchive(), URIUtils::IsPlugin(), and URIUtils::IsStack().
Referenced by CleanDatabase(), GetDetailsForEpisode(), GetDetailsForMovie(), GetDetailsForMusicVideo(), GetFileInfo(), GetFilePathById(), GetPlayCounts(), and RemoveContentForPath().
ConvertVideoToVersion()
bool CVideoDatabase::ConvertVideoToVersion (VideoDbContentType itemType, int dbIdSource, int dbIdTarget, int idVideoVersion, VideoAssetType assetType)
Remove a video from the library and transfer all of its assets to another video of the same type.
Parameters
itemType Type of the video being converted
dbIdSource id of the video being converted
dbIdTarget id that the video will be attached to
idVideoVersion new versiontype of the default version of the video
assetType new asset type of the default version of the video
Returns
true for success, false otherwise
References ALL_ASSETS, CDatabase::BeginTransaction(), CommitTransaction(), DeleteMovie(), CDatabase::ExecuteQuery(), GetFileIdByMovie(), HASH_PRESERVE, MOVIES, CDatabase::PrepareSQL(), SetVideoVersionDefaultArt(), UpdateAssetsOwner(), and VideoContentTypeToString().
Referenced by CGUIDialogVideoManagerVersions::AddSimilarMovieAsVersion(), CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), and CGUIDialogVideoManagerVersions::ChooseVideoAndConvertToVideoVersion().
CreateAnalytics()
void CVideoDatabase::CreateAnalytics () override private virtual
Implements CDatabase.
References CreateForeignLinkIndex(), CreateLinkIndex(), CreateViews(), CLog::Log(), LOGINFO, CDatabase::m_pDS, CDatabase::PrepareSQL(), VIDEODB_ID_EPISODE_BOOKMARK, VIDEODB_ID_EPISODE_EPISODE, VIDEODB_ID_EPISODE_SEASON, and VIDEODB_ID_TITLE.
CreateForeignLinkIndex()
void CVideoDatabase::CreateForeignLinkIndex (const char * table, const char * foreignkey) private
References CDatabase::m_pDS, CDatabase::PrepareSQL(), and table.
Referenced by CreateAnalytics().
CreateLinkIndex()
void CVideoDatabase::CreateLinkIndex (const char * table) private
References CDatabase::m_pDS, CDatabase::PrepareSQL(), and table.
Referenced by CreateAnalytics().
CreateTables()
void CVideoDatabase::CreateTables () override private virtual
Implements CDatabase.
References GetSchemaVersion(), InitializeVideoVersionTypeTable(), CLog::Log(), LOGINFO, CDatabase::m_pDS, VIDEODB_ID_EPISODE_BOOKMARK, VIDEODB_ID_EPISODE_EPISODE, VIDEODB_ID_EPISODE_SEASON, and VIDEODB_MAX_COLUMNS.
CreateViews()
void CVideoDatabase::CreateViews () private virtual
(Re)Create the generic database views for movies, tvshows, episodes and music videos
Todo:
Remove the hacky selection of a semi-random path for tvshows from the queries and UI
References EXTRA, CLog::Log(), LOGINFO, CDatabase::m_pDS, MediaTypeMovie, CDatabase::PrepareSQL(), VERSION, VIDEODB_ID_EPISODE_AIRED, VIDEODB_ID_EPISODE_IDENT_ID, VIDEODB_ID_EPISODE_RATING_ID, VIDEODB_ID_EPISODE_SEASON, VIDEODB_ID_IDENT_ID, VIDEODB_ID_MUSICVIDEO_IDENT_ID, VIDEODB_ID_RATING_ID, VIDEODB_ID_TV_GENRE, VIDEODB_ID_TV_IDENT_ID, VIDEODB_ID_TV_MPAA, VIDEODB_ID_TV_PLOT, VIDEODB_ID_TV_PREMIERED, VIDEODB_ID_TV_RATING_ID, VIDEODB_ID_TV_STUDIOS, and VIDEODB_ID_TV_TITLE.
Referenced by CreateAnalytics().
DeleteBookMarkForEpisode()
void CVideoDatabase::DeleteBookMarkForEpisode (const CVideoInfoTag & tag)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), and VIDEODB_ID_EPISODE_BOOKMARK.
Referenced by CGUIDialogVideoInfo::ManageVideoItem().
DeleteDetailsForTvShow()
void CVideoDatabase::DeleteDetailsForTvShow (int idTvShow)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), VIDEODB_ID_TV_MAX, and VIDEODB_ID_TV_MIN.
Referenced by DeleteTvShow(), UpdateDetailsForTvShow(), and CVideoLibraryRefreshingJob::Work().
DeleteEpisode()
void CVideoDatabase::DeleteEpisode (int idEpisode, bool bKeepId = false)
Todo:
move this below CommitTransaction() once UPnP doesn't rely on this anymore
References AnnounceRemove(), DeleteStreamDetails(), GetDbId(), CDatabase::GetSingleValue(), InvalidatePathHash(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeEpisode, and CDatabase::PrepareSQL().
Referenced by DeleteSeason(), DeleteTvShow(), CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), JSONRPC::CVideoLibrary::RemoveVideo(), SetDetailsForEpisode(), and CVideoLibraryRefreshingJob::Work().
DeleteMovie()
void CVideoDatabase::DeleteMovie (int idMovie, DeleteMovieCascadeAction action = DeleteMovieCascadeAction::ALL_ASSETS, DeleteMovieHashAction hashAction = DeleteMovieHashAction::HASH_DELETE)
Todo:
move this below CommitTransaction() once UPnP doesn't rely on this anymore
References ALL_ASSETS, AnnounceRemove(), CDatabase::BeginTransaction(), CommitTransaction(), DeleteStreamDetails(), DeleteVideoAsset(), GetDbId(), CDatabase::GetSingleValue(), HASH_DELETE, InvalidatePathHash(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMovie, CDatabase::PrepareSQL(), and CDatabase::RollbackTransaction().
Referenced by ConvertVideoToVersion(), CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), RemoveContentForPath(), JSONRPC::CVideoLibrary::RemoveVideo(), and CVideoLibraryRefreshingJob::Work().
DeleteMusicVideo()
void CVideoDatabase::DeleteMusicVideo (int idMusicVideo, bool bKeepId = false)
Todo:
move this below CommitTransaction() once UPnP doesn't rely on this anymore
References AnnounceRemove(), CDatabase::BeginTransaction(), CommitTransaction(), DeleteStreamDetails(), GetDbId(), CDatabase::GetSingleValue(), InvalidatePathHash(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMusicVideo, CDatabase::PrepareSQL(), and CDatabase::RollbackTransaction().
Referenced by CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), RemoveContentForPath(), JSONRPC::CVideoLibrary::RemoveVideo(), SetDetailsForMusicVideo(), and CVideoLibraryRefreshingJob::Work().
DeleteResumeBookMark()
void CVideoDatabase::DeleteResumeBookMark (const CFileItem & item)
References AnnounceUpdate(), ADDON::content, EPISODES, GetFileId(), CFileItem::GetPath(), CFileItem::GetVideoContentType(), CFileItem::GetVideoInfoTag(), CLog::Log(), LOGERROR, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iFileId, CDatabase::m_pDB, CDatabase::m_pDS, CVideoInfoTag::m_strFileNameAndPath, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MOVIES, MUSICVIDEOS, CDatabase::PrepareSQL(), CBookmark::RESUME, and TVSHOWS.
Referenced by CVideoLibraryResetResumePointJob::Work().
DeleteSeason()
void CVideoDatabase::DeleteSeason (int idSeason, bool bKeepId = false)
References CDatabase::BeginTransaction(), CommitTransaction(), DeleteEpisode(), CDatabase::ExecuteQuery(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), and VIDEODB_ID_EPISODE_SEASON.
Referenced by CVideoLibraryRefreshingJob::Work().
DeleteSet()
void CVideoDatabase::DeleteSet (int idSet)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), and CGUIWindowVideoNav::OnDeleteItem().
DeleteStreamDetails()
void CVideoDatabase::DeleteStreamDetails (int idFile)
References CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by DeleteEpisode(), DeleteMovie(), and DeleteMusicVideo().
DeleteTag()
void CVideoDatabase::DeleteTag (int idTag, VideoDbContentType mediaType)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MOVIES, MUSICVIDEOS, CDatabase::PrepareSQL(), and TVSHOWS.
Referenced by CGUIDialogVideoInfo::DeleteVideoItemFromDatabase().
DeleteTvShow() [1/2]
void CVideoDatabase::DeleteTvShow (const std::string & strPath)
References DeleteTvShow(), and GetTvShowId().
DeleteTvShow() [2/2]
void CVideoDatabase::DeleteTvShow (int idTvShow, bool bKeepId = false)
Todo:
move this below CommitTransaction() once UPnP doesn't rely on this anymore
References AnnounceRemove(), CDatabase::BeginTransaction(), CommitTransaction(), DeleteDetailsForTvShow(), DeleteEpisode(), GetPathsForTvShow(), CDatabase::GetSingleValue(), InvalidatePathHash(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, MediaTypeTvShow, CDatabase::PrepareSQL(), and CDatabase::RollbackTransaction().
Referenced by DeleteTvShow(), CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), ImportFromXML(), RemoveContentForPath(), JSONRPC::CVideoLibrary::RemoveVideo(), and CVideoLibraryRefreshingJob::Work().
DeleteVideoAsset()
bool CVideoDatabase::DeleteVideoAsset (int idFile)
References CDatabase::BeginTransaction(), CommitTransaction(), CDatabase::GetSingleValue(), InvalidatePathHash(), IsDefaultVideoVersion(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::RollbackTransaction().
Referenced by DeleteMovie(), and CGUIDialogVideoManager::Remove().
DumpToDummyFiles()
void CVideoDatabase::DumpToDummyFiles (const std::string & path)
References URIUtils::AddFileToFolder(), CFileItemList::Clear(), XFILE::CFile::Close(), XFILE::CDirectory::Create(), GetEpisodesByWhere(), GetMoviesByWhere(), GetTvShowsByWhere(), CFileItem::GetVideoInfoTag(), CUtil::MakeLegalFileName(), CDatabase::PrepareSQL(), and CFileItemList::Size().
EraseAllForFile()
void CVideoDatabase::EraseAllForFile (const std::string & fileNameAndPath)
Erases all entries for the given file, including path entry if no longer used
Parameters
fileNameAndPath The name and path of the file to erase db entries for
References GetFileId(), GetPathId(), CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by PVR::CPVRRecording::DeleteMetadata().
EraseAllForPath()
void CVideoDatabase::EraseAllForPath (const std::string & path)
Erases all entries for files starting with path, including the files and path entries
Parameters
path pattern
References CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by PVR::CPVRGUIActionsDatabase::ResetDatabase().
EraseAllVideoSettings() [1/2]
void CVideoDatabase::EraseAllVideoSettings ()
Erases all video settings
References CLog::Log(), LOGERROR, LOGINFO, and CDatabase::m_pDS.
Referenced by CGUIDialogAudioSettings::Save(), CGUIDialogSubtitleSettings::Save(), and CGUIDialogVideoSettings::Save().
EraseAllVideoSettings() [2/2]
void CVideoDatabase::EraseAllVideoSettings (const std::string & path)
Erases video settings for files starting with path
Parameters
path pattern
References CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
EraseVideoSettings()
void CVideoDatabase::EraseVideoSettings (const CFileItem & item)
EraseVideoSettings() Erases the videoSettings table and reconstructs it.
Erases video settings for file item
Parameters
fileitem
References GetFileId(), CFileItem::GetPath(), CLog::Log(), LOGERROR, LOGINFO, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CApplicationPlayerCallback::StoreVideoSettings().
ExportActorThumbs()
void CVideoDatabase::ExportActorThumbs (const std::string & path, const CVideoInfoTag & tag, bool singleFiles, bool overwrite = false)
References URIUtils::AddFileToFolder(), XFILE::CDirectory::Create(), XFILE::CDirectory::Exists(), GetSafeFile(), CServiceBroker::GetTextureCache(), XFILE::CFile::SetHidden(), and CFileItem::SetLabel().
Referenced by ExportToXML().
ExportToXML()
void CVideoDatabase::ExportToXML (const std::string & path, bool singleFile = true, bool images = false, bool actorThumbs = false, bool overwrite = false)
References URIUtils::AddFileToFolder(), CGUIWindow::Close(), XFILE::CDirectory::Create(), data(), CGUIDialogKaiToast::Error, CFileItem::Exists(), XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), ExportActorThumbs(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAnnouncementManager(), GetArtForItem(), CDateTime::GetCurrentDateTime(), GetDetailsForEpisode(), GetDetailsForMovie(), GetDetailsForMusicVideo(), GetDetailsForTvShow(), GetExportVersion(), URIUtils::GetFileName(), CServiceBroker::GetGUI(), KODI::ART::GetLocalArt(), URIUtils::GetParentPath(), CFileItem::GetPath(), GetPaths(), GetSafeFile(), GetScraperForPath(), CServiceBroker::GetSettingsComponent(), KODI::ART::GetTBNFile(), CServiceBroker::GetTextureCache(), GetTvShowNamedSeasons(), GetTvShowSeasonArt(), CGUIComponent::GetWindowManager(), CVideoInfoTag::GetYear(), CVideoInfoTag::HasYear(), CGUIDialogProgress::IsCanceled(), CFileItem::IsOpticalMediaFile(), LEGAL_WIN32_COMPAT, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, CVideoInfoTag::m_artist, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iFileId, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_namedSeasons, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPath, CVideoInfoTag::m_strTitle, CVideoInfoTag::m_strTrailer, CVideoInfoTag::m_type, CUtil::MakeLegalFileName(), MediaTypeEpisode, MediaTypeVideoCollection, CGUIDialogProgress::Open(), KODI::VIDEO::SScanSettings::parent_name, CDatabase::PrepareSQL(), CGUIDialogProgress::Progress(), CGUIDialogKaiToast::QueueNotification(), KODI::VIDEO::SScanSettings::recurse, XFILE::CDirectory::Remove(), URIUtils::ReplaceExtension(), CVideoInfoTag::Save(), CXBMCTinyXML::SaveFile(), XMLUtils::SetBoolean(), CGUIDialogBoxBase::SetHeading(), XMLUtils::SetInt(), CGUIDialogBoxBase::SetLine(), CFileItem::SetPath(), CGUIDialogProgress::SetPercentage(), XMLUtils::SetString(), CSettings::SETTING_VIDEOLIBRARY_MOVIESETSFOLDER, KODI::MESSAGING::HELPERS::ShowOKDialogText(), CGUIDialogProgress::ShowProgressBar(), CUtil::SupportsWriteFileOperations(), ADDON::TranslateContent(), VideoDbDetailsAll, ANNOUNCEMENT::VideoLibrary, and WINDOW_DIALOG_PROGRESS.
Referenced by ExportLibrary(), and ExportLibrary2().
FillMovieItem()
bool CVideoDatabase::FillMovieItem (std::unique_ptr< dbiplus::Dataset > & dataset, int movieId, CFileItem & item) private
References CDbUrl::AddOption(), CDbUrl::AppendPath(), CDbUrl::FromString(), GetDetailsForMovie(), LOGERROR, CFileItem::SetDynPath(), CFileItem::SetFromVideoInfoTag(), CFileItem::SetPath(), and CDbUrl::ToString().
Referenced by GetAssetsForVideo(), and GetDefaultVersionForVideo().
GetActorsNav()
bool CVideoDatabase::GetActorsNav (const std::string & strBaseDir, CFileItemList & items, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter(), bool countOnly = false)
References GetPeopleNav(), MUSICVIDEOS, CGUIListItem::SetArt(), and CFileItemList::Size().
Referenced by CGUIDialogMediaFilter::GetItems(), GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetAndFillFileId()
int CVideoDatabase::GetAndFillFileId (CVideoInfoTag & details) protected
Get the id of the file of this item and store it in the item.
Parameters
details CVideoInfoTag for which to get and store the id of the file
Returns
id of the file, -1 if it is not in the db.
References GetFileId(), and CVideoInfoTag::m_iFileId.
Referenced by SetDetailsForEpisode(), SetDetailsForMovie(), SetDetailsForMusicVideo(), and UpdateFileDateAdded().
GetArtForAsset()
bool CVideoDatabase::GetArtForAsset (int assetId, ArtFallbackOptions fallback, std::map< std::string, std::string > & art)
Retrieve all art for the given video asset, with optional fallback to the art of the parent/owner of the asset.
Parameters
assetId id of the file of the asset
fallback optionally request fallback to the art of the parent/owner for each art type that is not defined for the asset
art collection of the retrieved art
Returns
References LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, MediaTypeVideoVersion, PARENT, and CDatabase::PrepareSQL().
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::AddCurrentArtTypes(), and CVideoThumbLoader::FillLibraryArt().
GetArtForItem() [1/2]
std::string CVideoDatabase::GetArtForItem (int mediaId, const MediaType & mediaType, const std::string & artType)
References CDatabase::GetSingleValue(), CDatabase::m_pDS2, and CDatabase::PrepareSQL().
GetArtForItem() [2/2]
bool CVideoDatabase::GetArtForItem (int mediaId, const MediaType & mediaType, std::map< std::string, std::string > & art)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::AddCurrentArtTypes(), ExportToXML(), CVideoThumbLoader::FillLibraryArt(), CVideoThumbLoader::GetArtFromCache(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetCurrentArt(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkActorHandler::GetCurrentArt(), CGUIWindowVideoNav::GetDirectory(), CGUIDialogVideoInfo::GetSetForMovie(), GetTvShowSeasonArt(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), JSONRPC::CVideoLibrary::SetMovieDetails(), JSONRPC::CVideoLibrary::SetMovieSetDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), JSONRPC::CVideoLibrary::SetSeasonDetails(), JSONRPC::CVideoLibrary::SetTVShowDetails(), SetVideoVersionDefaultArt(), and CRecentlyAddedJob::UpdateVideo().
GetArtTypes()
bool CVideoDatabase::GetArtTypes (const MediaType & mediaType, std::vector< std::string > & artTypes)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and RunQuery().
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::AddMediaTypeArtTypes().
GetAssetsForVideo()
bool CVideoDatabase::GetAssetsForVideo (VideoDbContentType itemType, int mediaId, VideoAssetType assetType, CFileItemList & items)
Todo:
add bool return type to GetVideoVersions
References CFileItemList::Add(), FillMovieItem(), GetVideoVersions(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMovie, MOVIES, CDatabase::PrepareSQL(), and VERSION.
Referenced by KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo().
GetAvailableArtForItem()
std::vector< CScraperUrl::SUrlEntry > CVideoDatabase::GetAvailableArtForItem (int mediaId, const MediaType & mediaType, const std::string & artType)
Fetch the list of available-but-unassigned art URLs held in the database for a specific media item and art type.
Parameters
mediaId the id in the media table.
mediaType corresponds to the table the item resides in.
artType e.g. "thumb", "fanart", etc.
Returns
list of URLs
References MediaTypeSeason, MediaTypeVideoCollection, and UNKNOWN.
Referenced by JSONRPC::CVideoLibrary::GetAvailableArt().
GetAvailableArtTypesForItem()
std::vector< std::string > CVideoDatabase::GetAvailableArtTypesForItem (int mediaId, const MediaType & mediaType)
Fetch the distinct types of available-but-unassigned art held in the database for a specific media item.
Parameters
mediaId the id in the media table.
mediaType the type of media, which corresponds to the table the item resides in.
Returns
the types of art e.g. "thumb", "fanart", etc.
References MediaTypeSeason, MediaTypeVideoCollection, and UNKNOWN.
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::AddAvailableArtTypes(), and JSONRPC::CVideoLibrary::GetAvailableArtTypes().
GetBaseDBName()
const char * CVideoDatabase::GetBaseDBName () const inline override private virtual
Implements CDatabase.
GetBasicDetailsForEpisode() [1/2]
CVideoInfoTag CVideoDatabase::GetBasicDetailsForEpisode (const dbiplus::sql_record *const record) protected
References DbEpisodeOffsets, GetDetailsFromDB(), CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iFileId, CVideoInfoTag::m_iIdSeason, CVideoInfoTag::m_iIdShow, CVideoInfoTag::m_iUserRating, CVideoInfoTag::m_type, MediaTypeEpisode, VIDEODB_DETAILS_EPISODE_SEASON_ID, VIDEODB_DETAILS_EPISODE_TVSHOW_ID, VIDEODB_DETAILS_EPISODE_USER_RATING, VIDEODB_DETAILS_FILEID, VIDEODB_ID_EPISODE_MAX, and VIDEODB_ID_EPISODE_MIN.
GetBasicDetailsForEpisode() [2/2]
CVideoInfoTag CVideoDatabase::GetBasicDetailsForEpisode (std::unique_ptr< dbiplus::Dataset > & pDS) protected
References GetBasicDetailsForEpisode().
Referenced by GetBasicDetailsForEpisode(), GetDetailsForEpisode(), and GetEpisodeBasicInfo().
GetBookMarkForEpisode()
bool CVideoDatabase::GetBookMarkForEpisode (const CVideoInfoTag & tag, CBookmark & bookmark)
References CLog::Log(), LOGERROR, CDatabase::m_pDS2, CBookmark::player, CBookmark::playerState, CDatabase::PrepareSQL(), CBookmark::thumbNailImage, CBookmark::timeInSeconds, CBookmark::totalTimeInSeconds, CBookmark::type, and VIDEODB_ID_EPISODE_BOOKMARK.
Referenced by GetDetailsForEpisode(), and CApplication::PlayFile().
GetBookMarksForFile()
void CVideoDatabase::GetBookMarksForFile (const std::string & strFilenameAndPath, VECBOOKMARKS & bookmarks, CBookmark::EType type = CBookmark::STANDARD, bool bAppend = false, long partNumber = 0)
References CBookmark::EPISODE, CBookmark::episodeNumber, GetBookMarksForFile(), XFILE::CStackDirectory::GetDirectory(), GetFileId(), URIUtils::IsDiscImageStack(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, CBookmark::partNumber, CBookmark::player, CBookmark::playerState, CDatabase::PrepareSQL(), CBookmark::seasonNumber, CFileItemList::Size(), CBookmark::thumbNailImage, CBookmark::timeInSeconds, CBookmark::totalTimeInSeconds, CBookmark::type, VIDEODB_ID_EPISODE_BOOKMARK, VIDEODB_ID_EPISODE_EPISODE, VIDEODB_ID_EPISODE_SEASON, VIDEODB_ID_EPISODE_SORTEPISODE, and VIDEODB_ID_EPISODE_SORTSEASON.
Referenced by GetBookMarksForFile(), GetResumeBookMark(), and CGUIDialogVideoBookmarks::OnRefreshList().
GetCast()
void CVideoDatabase::GetCast (int media_id, const std::string & media_type, std::vector< SActorInfo > & cast) protected
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, CDatabase::PrepareSQL(), and SActorInfo::strName.
Referenced by GetDetailsForEpisode(), GetDetailsForMovie(), GetDetailsForMusicVideo(), and GetDetailsForTvShow().
GetContentForPath()
std::string CVideoDatabase::GetContentForPath (const std::string & strPath)
Retrieve the content type of videos in the given path If content is set on the folder, we return the given content type, except in the case of tvshows, where we first check for whether we have episodes directly in the path (thus return episodes) or whether we've found a scraper directly (shows). Any folders inbetween are treated as seasons (regardless of whether they actually are seasons). Note that any subfolders in movies will be treated as movies.
Parameters
strPath path to start searching in.
Returns
A content type string for the current path.
References CONTENT_TVSHOWS, GetScraperForPath(), CDatabase::m_pDS, CDatabase::PrepareSQL(), and ADDON::TranslateContent().
Referenced by CleanLibrary(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), and CGUIWindowVideoBase::LoadVideoInfo().
GetCountriesNav()
bool CVideoDatabase::GetCountriesNav (const std::string & strBaseDir, CFileItemList & items, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter(), bool countOnly = false)
References GetNavCommon().
Referenced by GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetCountryById()
std::string CVideoDatabase::GetCountryById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetItemById(), and XFILE::CVideoDatabaseDirectory::GetLabel().
GetDateAdded()
CDateTime CVideoDatabase::GetDateAdded (const std::string & filename, CDateTime dateAdded = CDateTime()) static private
References CDateTime::GetCurrentDateTime(), CFileUtils::GetModificationDate(), CServiceBroker::GetSettingsComponent(), URIUtils::IsPlugin(), and CDateTime::IsValid().
Referenced by AddFile(), AddPathToTvShow(), and UpdateFileDateAdded().
GetDbId()
int CVideoDatabase::GetDbId (const std::string & query) private
Helper to get a database id given a query. Returns an integer, -1 if not found, and greater than 0 if found.
Parameters
query the SQL that will retrieve a database id.
Returns
-1 if not found, else a valid database id (i.e. > 0)
References CDatabase::GetSingleValue().
Referenced by DeleteEpisode(), DeleteMovie(), DeleteMusicVideo(), and GetMatchingTvShow().
GetDefaultVersionForVideo()
bool CVideoDatabase::GetDefaultVersionForVideo (VideoDbContentType itemType, int mediaId, CFileItem & item)
References FillMovieItem(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMovie, MOVIES, CDatabase::PrepareSQL(), and VERSION.
Referenced by KODI::VIDEO::GUILIB::CVideoVersionHelper::ChooseVideoFromAssets().
GetDefaultVideoVersion()
void CVideoDatabase::GetDefaultVideoVersion (VideoDbContentType itemType, int dbId, CFileItem & item)
References CVideoInfoTag::GetAssetInfo(), GetFileInfo(), CLog::Log(), LOGERROR, CVideoInfoTag::m_iDbId, CDatabase::m_pDB, CDatabase::m_pDS, CFileItem::m_strTitle, CVideoInfoTag::m_strTitle, CVideoInfoTag::m_type, MediaTypeMovie, MediaTypeVideoVersion, MOVIES, name, CDatabase::PrepareSQL(), CFileItem::SetFromVideoInfoTag(), CVideoInfoTag::CAssetInfo::SetId(), CFileItem::SetLabel(), CVideoInfoTag::CAssetInfo::SetTitle(), and CVideoInfoTag::CAssetInfo::SetType().
Referenced by CGUIDialogVideoManagerVersions::Refresh(), and CGUIDialogVideoManagerVersions::SetDefault().
GetDetailsByTypeAndId() [1/2]
bool CVideoDatabase::GetDetailsByTypeAndId (CFileItem & item, VideoDbContentType type, int id)
References EPISODES, GetEpisodeInfo(), GetMovieInfo(), GetMusicVideoInfo(), GetTvShowInfo(), MOVIES, MUSICVIDEOS, CVideoInfoTag::Reset(), CFileItem::SetFromVideoInfoTag(), and TVSHOWS.
Referenced by anonymous_namespace{VideoDatabase.cpp}::GetBasicItemAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetBasicItemAvailableArtTypes(), GetDetailsByTypeAndId(), GetSameVideoItems(), XFILE::CVideoDatabaseFile::GetVideoTag(), GetVideoVersions(), CGUIDialogVideoManagerVersions::ProcessVideoVersion(), and CGUIDialogVideoManagerVersions::SetDefaultVideoVersion().
GetDetailsByTypeAndId() [2/2]
CVideoInfoTag CVideoDatabase::GetDetailsByTypeAndId (VideoDbContentType type, int id)
References GetDetailsByTypeAndId(), and CFileItem::GetVideoInfoTag().
GetDetailsForEpisode() [1/2]
CVideoInfoTag CVideoDatabase::GetDetailsForEpisode (const dbiplus::sql_record *const record, int getDetails = VideoDbDetailsNone) protected
References ConstructPath(), GetBasicDetailsForEpisode(), GetBookMarkForEpisode(), GetCast(), GetRatings(), CServiceBroker::GetSettingsComponent(), GetStreamDetails(), GetUniqueIDs(), CVideoInfoTag::m_cast, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_EpBookmark, CVideoInfoTag::m_genre, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iIdShow, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_parsedDetails, CVideoInfoTag::m_ratings, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strMPAARating, CVideoInfoTag::m_strPath, CVideoInfoTag::m_strShowTitle, CVideoInfoTag::m_studio, MediaTypeEpisode, MediaTypeTvShow, CDateTime::SetFromDBDateTime(), CVideoInfoTag::SetPlayCount(), CVideoInfoTag::SetPremieredFromDBDate(), CVideoInfoTag::SetRating(), CVideoInfoTag::SetResumePoint(), CVideoInfoTag::SetUniqueID(), VIDEODB_DETAILS_EPISODE_DATEADDED, VIDEODB_DETAILS_EPISODE_FILE, VIDEODB_DETAILS_EPISODE_LASTPLAYED, VIDEODB_DETAILS_EPISODE_PATH, VIDEODB_DETAILS_EPISODE_PLAYCOUNT, VIDEODB_DETAILS_EPISODE_PLAYER_STATE, VIDEODB_DETAILS_EPISODE_RATING, VIDEODB_DETAILS_EPISODE_RATING_TYPE, VIDEODB_DETAILS_EPISODE_RESUME_TIME, VIDEODB_DETAILS_EPISODE_TOTAL_TIME, VIDEODB_DETAILS_EPISODE_TVSHOW_AIRED, VIDEODB_DETAILS_EPISODE_TVSHOW_GENRE, VIDEODB_DETAILS_EPISODE_TVSHOW_MPAA, VIDEODB_DETAILS_EPISODE_TVSHOW_NAME, VIDEODB_DETAILS_EPISODE_TVSHOW_STUDIO, VIDEODB_DETAILS_EPISODE_UNIQUEID_TYPE, VIDEODB_DETAILS_EPISODE_UNIQUEID_VALUE, VIDEODB_DETAILS_EPISODE_VOTES, VideoDbDetailsBookmark, VideoDbDetailsCast, VideoDbDetailsRating, VideoDbDetailsStream, and VideoDbDetailsUniqueID.
GetDetailsForEpisode() [2/2]
CVideoInfoTag CVideoDatabase::GetDetailsForEpisode (std::unique_ptr< dbiplus::Dataset > & pDS, int getDetails = VideoDbDetailsNone) protected
References GetDetailsForEpisode().
Referenced by ExportToXML(), GetDetailsForEpisode(), GetEpisodeInfo(), GetEpisodesByFile(), and GetEpisodesByWhere().
GetDetailsForMovie() [1/2]
CVideoInfoTag CVideoDatabase::GetDetailsForMovie (const dbiplus::sql_record *const record, int getDetails = VideoDbDetailsNone) protected
References ConstructPath(), DbMovieOffsets, CVideoInfoTag::GetAssetInfo(), GetCast(), GetDetailsFromDB(), GetLinksToTvShow(), GetRatings(), GetStreamDetails(), GetTags(), GetUniqueIDs(), CVideoInfoTag::SetInfo::id, CVideoInfoTag::m_cast, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iFileId, CVideoInfoTag::m_iUserRating, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_parsedDetails, CDatabase::m_pDS2, CVideoInfoTag::m_ratings, CVideoInfoTag::m_set, CVideoInfoTag::m_showLink, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPath, CVideoInfoTag::m_tags, CVideoInfoTag::m_type, MediaTypeMovie, CVideoInfoTag::SetInfo::overview, CDatabase::PrepareSQL(), CDateTime::SetFromDBDateTime(), CVideoInfoTag::SetHasVideoExtras(), CVideoInfoTag::SetHasVideoVersions(), CVideoInfoTag::CAssetInfo::SetId(), CVideoInfoTag::SetIsDefaultVideoVersion(), CVideoInfoTag::SetPlayCount(), CVideoInfoTag::SetPremieredFromDBDate(), CVideoInfoTag::SetRating(), CVideoInfoTag::SetResumePoint(), CVideoInfoTag::SetUniqueID(), CVideoInfoTag::SetYear(), CVideoInfoTag::SetInfo::title, VIDEODB_DETAILS_MOVIE_DATEADDED, VIDEODB_DETAILS_MOVIE_FILE, VIDEODB_DETAILS_MOVIE_HASEXTRAS, VIDEODB_DETAILS_MOVIE_HASVERSIONS, VIDEODB_DETAILS_MOVIE_ISDEFAULTVERSION, VIDEODB_DETAILS_MOVIE_LASTPLAYED, VIDEODB_DETAILS_MOVIE_PATH, VIDEODB_DETAILS_MOVIE_PLAYCOUNT, VIDEODB_DETAILS_MOVIE_PLAYER_STATE, VIDEODB_DETAILS_MOVIE_PREMIERED, VIDEODB_DETAILS_MOVIE_RATING, VIDEODB_DETAILS_MOVIE_RATING_TYPE, VIDEODB_DETAILS_MOVIE_RESUME_TIME, VIDEODB_DETAILS_MOVIE_SET_ID, VIDEODB_DETAILS_MOVIE_SET_NAME, VIDEODB_DETAILS_MOVIE_SET_OVERVIEW, VIDEODB_DETAILS_MOVIE_TOTAL_TIME, VIDEODB_DETAILS_MOVIE_UNIQUEID_TYPE, VIDEODB_DETAILS_MOVIE_UNIQUEID_VALUE, VIDEODB_DETAILS_MOVIE_USER_RATING, VIDEODB_DETAILS_MOVIE_VERSION_FILEID, VIDEODB_DETAILS_MOVIE_VERSION_ITEMTYPE, VIDEODB_DETAILS_MOVIE_VERSION_TYPEID, VIDEODB_DETAILS_MOVIE_VERSION_TYPENAME, VIDEODB_DETAILS_MOVIE_VOTES, VIDEODB_ID_MAX, VIDEODB_ID_MIN, VIDEODB_ID_TV_TITLE, VideoDbDetailsCast, VideoDbDetailsRating, VideoDbDetailsShowLink, VideoDbDetailsStream, VideoDbDetailsTag, and VideoDbDetailsUniqueID.
GetDetailsForMovie() [2/2]
CVideoInfoTag CVideoDatabase::GetDetailsForMovie (std::unique_ptr< dbiplus::Dataset > & pDS, int getDetails = VideoDbDetailsNone) protected
References GetDetailsForMovie().
Referenced by ExportToXML(), FillMovieItem(), GetDetailsForMovie(), GetMovieInfo(), and GetMoviesByWhere().
GetDetailsForMusicVideo() [1/2]
CVideoInfoTag CVideoDatabase::GetDetailsForMusicVideo (const dbiplus::sql_record *const record, int getDetails = VideoDbDetailsNone) protected
References ConstructPath(), DbMusicVideoOffsets, GetCast(), GetDetailsFromDB(), GetStreamDetails(), GetTags(), GetUniqueIDs(), CVideoInfoTag::m_cast, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iFileId, CVideoInfoTag::m_iUserRating, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_parsedDetails, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPath, CVideoInfoTag::m_tags, CVideoInfoTag::m_type, MediaTypeMusicVideo, CDateTime::SetFromDBDateTime(), CVideoInfoTag::SetPlayCount(), CVideoInfoTag::SetPremieredFromDBDate(), CVideoInfoTag::SetResumePoint(), CVideoInfoTag::SetUniqueID(), CVideoInfoTag::SetYear(), VIDEODB_DETAILS_FILEID, VIDEODB_DETAILS_MUSICVIDEO_DATEADDED, VIDEODB_DETAILS_MUSICVIDEO_FILE, VIDEODB_DETAILS_MUSICVIDEO_LASTPLAYED, VIDEODB_DETAILS_MUSICVIDEO_PATH, VIDEODB_DETAILS_MUSICVIDEO_PLAYCOUNT, VIDEODB_DETAILS_MUSICVIDEO_PLAYER_STATE, VIDEODB_DETAILS_MUSICVIDEO_PREMIERED, VIDEODB_DETAILS_MUSICVIDEO_RESUME_TIME, VIDEODB_DETAILS_MUSICVIDEO_TOTAL_TIME, VIDEODB_DETAILS_MUSICVIDEO_UNIQUEID_TYPE, VIDEODB_DETAILS_MUSICVIDEO_UNIQUEID_VALUE, VIDEODB_DETAILS_MUSICVIDEO_USER_RATING, VIDEODB_ID_MUSICVIDEO_MAX, VIDEODB_ID_MUSICVIDEO_MIN, VideoDbDetailsAll, VideoDbDetailsStream, VideoDbDetailsTag, and VideoDbDetailsUniqueID.
GetDetailsForMusicVideo() [2/2]
CVideoInfoTag CVideoDatabase::GetDetailsForMusicVideo (std::unique_ptr< dbiplus::Dataset > & pDS, int getDetails = VideoDbDetailsNone) protected
References GetDetailsForMusicVideo().
Referenced by ExportToXML(), GetDetailsForMusicVideo(), GetMusicVideoInfo(), GetMusicVideosByArtist(), and GetMusicVideosByWhere().
GetDetailsForTvShow() [1/2]
CVideoInfoTag CVideoDatabase::GetDetailsForTvShow (const dbiplus::sql_record *const record, int getDetails = VideoDbDetailsNone, CFileItem * item = NULL) protected
Todo:
videotag member + guiinfo int needed? – Currently not needed; having it available as item prop seems sufficient for skinning
References DbTvShowOffsets, GetCast(), GetDetailsFromDB(), CVideoInfoTag::GetPlayCount(), CVideoInfoTag::GetPremiered(), GetRatings(), GetTags(), GetUniqueIDs(), CDateTime::IsValid(), CVideoInfoTag::m_basePath, CVideoInfoTag::m_bHasPremiered, CVideoInfoTag::m_cast, CVideoInfoTag::m_dateAdded, CFileItem::m_dateTime, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_iUserRating, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_parentPathID, CVideoInfoTag::m_parsedDetails, CVideoInfoTag::m_premiered, CVideoInfoTag::m_ratings, CVideoInfoTag::m_strPath, CVideoInfoTag::m_strShowTitle, CVideoInfoTag::m_strTitle, CVideoInfoTag::m_tags, CVideoInfoTag::m_type, MediaTypeTvShow, CVideoInfoTag::SetDuration(), CDateTime::SetFromDBDateTime(), CVideoInfoTag::SetPlayCount(), CGUIListItem::SetProperty(), CVideoInfoTag::SetRating(), CVideoInfoTag::SetUniqueID(), VIDEODB_DETAILS_TVSHOW_DATEADDED, VIDEODB_DETAILS_TVSHOW_DURATION, VIDEODB_DETAILS_TVSHOW_LASTPLAYED, VIDEODB_DETAILS_TVSHOW_NUM_EPISODES, VIDEODB_DETAILS_TVSHOW_NUM_INPROGRESS, VIDEODB_DETAILS_TVSHOW_NUM_SEASONS, VIDEODB_DETAILS_TVSHOW_NUM_WATCHED, VIDEODB_DETAILS_TVSHOW_PARENTPATHID, VIDEODB_DETAILS_TVSHOW_PATH, VIDEODB_DETAILS_TVSHOW_RATING, VIDEODB_DETAILS_TVSHOW_RATING_TYPE, VIDEODB_DETAILS_TVSHOW_UNIQUEID_TYPE, VIDEODB_DETAILS_TVSHOW_UNIQUEID_VALUE, VIDEODB_DETAILS_TVSHOW_USER_RATING, VIDEODB_DETAILS_TVSHOW_VOTES, VIDEODB_ID_TV_MAX, VIDEODB_ID_TV_MIN, VideoDbDetailsCast, VideoDbDetailsRating, VideoDbDetailsTag, and VideoDbDetailsUniqueID.
GetDetailsForTvShow() [2/2]
CVideoInfoTag CVideoDatabase::GetDetailsForTvShow (std::unique_ptr< dbiplus::Dataset > & pDS, int getDetails = VideoDbDetailsNone, CFileItem * item = NULL) protected
References GetDetailsForTvShow().
Referenced by ExportToXML(), GetDetailsForTvShow(), GetTvShowInfo(), and GetTvShowsByWhere().
GetDetailsFromDB() [1/2]
void CVideoDatabase::GetDetailsFromDB (const dbiplus::sql_record *const record, int min, int max, const SDbTableOffsets * offsets, CVideoInfoTag & details, int idxOffset = 2) protected
References CServiceBroker::GetSettingsComponent(), max, min, SDbTableOffsets::offset, value, VIDEODB_TYPE_BOOL, VIDEODB_TYPE_COUNT, VIDEODB_TYPE_DATE, VIDEODB_TYPE_DATETIME, VIDEODB_TYPE_FLOAT, VIDEODB_TYPE_INT, VIDEODB_TYPE_STRING, VIDEODB_TYPE_STRINGARRAY, and VIDEODB_TYPE_UNUSED.
GetDetailsFromDB() [2/2]
void CVideoDatabase::GetDetailsFromDB (std::unique_ptr< dbiplus::Dataset > & pDS, int min, int max, const SDbTableOffsets * offsets, CVideoInfoTag & details, int idxOffset = 2) protected
References GetDetailsFromDB(), max, and min.
Referenced by GetBasicDetailsForEpisode(), GetDetailsForMovie(), GetDetailsForMusicVideo(), GetDetailsForTvShow(), and GetDetailsFromDB().
GetDirectorsNav()
bool CVideoDatabase::GetDirectorsNav (const std::string & strBaseDir, CFileItemList & items, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter(), bool countOnly = false)
References GetPeopleNav().
Referenced by CGUIDialogMediaFilter::GetItems(), GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetEpisodeBasicInfo()
bool CVideoDatabase::GetEpisodeBasicInfo (const std::string & strFilenameAndPath, CVideoInfoTag & details, int idEpisode = -1)
References GetBasicDetailsForEpisode(), GetEpisodeId(), CVideoInfoTag::IsEmpty(), CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by GetEpisodeId().
GetEpisodeId()
int CVideoDatabase::GetEpisodeId (const std::string & strFilenameAndPath, int idEpisode = -1, int idSeason = -1)
References GetEpisodeBasicInfo(), GetFileId(), CLog::Log(), LOGDATABASE, LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by GetEpisodeBasicInfo(), GetEpisodeInfo(), HasEpisodeInfo(), and SetDetailsForEpisode().
GetEpisodeInfo()
bool CVideoDatabase::GetEpisodeInfo (const std::string & strFilenameAndPath, CVideoInfoTag & details, int idEpisode = -1, int getDetails = VideoDbDetailsAll)
References GetDetailsForEpisode(), GetEpisodeId(), CVideoInfoTag::IsEmpty(), CLog::Log(), LOGERROR, CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iSeason, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by UPNP::CUPnPServer::Build(), JSONRPC::CVideoLibrary::FillFileItemList(), GetDetailsByTypeAndId(), JSONRPC::CVideoLibrary::GetEpisodeDetails(), JSONRPC::CPlayerOperations::GetItem(), LoadVideoInfo(), CGUIDialogVideoInfo::OnSearchItemFound(), JSONRPC::CVideoLibrary::RefreshEpisode(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), CGUIWindowVideoBase::ShowInfo(), CGUIDialogVideoInfo::UpdateVideoItemTitle(), and CVideoLibraryRefreshingJob::Work().
GetEpisodesByActor()
void CVideoDatabase::GetEpisodesByActor (const std::string & strActor, CFileItemList & items)
References GetEpisodesByWhere(), CDatabase::Filter::group, CDatabase::Filter::join, name, CDatabase::PrepareSQL(), and CDatabase::Filter::where.
Referenced by CGUIDialogVideoInfo::DoSearch().
GetEpisodesByFile()
void CVideoDatabase::GetEpisodesByFile (const std::string & strFilenameAndPath, std::vector< CVideoInfoTag > & episodes)
References GetDetailsForEpisode(), GetFileId(), CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), VIDEODB_ID_EPISODE_SORTEPISODE, and VIDEODB_ID_EPISODE_SORTSEASON.
Referenced by CGUIDialogVideoBookmarks::AddEpisodeBookmark(), CGUIDialogVideoBookmarks::OnAddEpisodeBookmark(), and CGUIDialogVideoBookmarks::Update().
GetEpisodesByName()
void CVideoDatabase::GetEpisodesByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CDatabase::PrepareSQL(), VIDEODB_ID_EPISODE_SEASON, VIDEODB_ID_EPISODE_TITLE, and VIDEODB_ID_TV_TITLE.
Referenced by CGUIWindowVideoNav::DoSearch().
GetEpisodesByPlot()
void CVideoDatabase::GetEpisodesByPlot (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CDatabase::PrepareSQL(), VIDEODB_ID_EPISODE_PLOT, VIDEODB_ID_EPISODE_SEASON, VIDEODB_ID_EPISODE_TITLE, and VIDEODB_ID_TV_TITLE.
Referenced by CGUIWindowVideoNav::DoSearch().
GetEpisodesByWhere()
bool CVideoDatabase::GetEpisodesByWhere (const std::string & strBaseDir, const Filter & filter, CFileItemList & items, bool appendFullShowPath = true, const SortDescription & sortDescription = SortDescription(), int getDetails = VideoDbDetailsNone)
References CFileItemList::Add(), CDbUrl::AppendPath(), CGUIPassword::bMasterUser, DatabaseUtils::BuildLimitClause(), CDatabase::BuildSQL(), data(), FieldRow, CDatabase::Filter::fields, CLabelFormatter::FormatLabel(), g_passwordManager, GetDetailsForEpisode(), CMediaSourceSettings::GetInstance(), CVideoDbUrl::GetItemType(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CVideoInfoTag::GetPlayCount(), CDatabase::GetSingleValue(), CMediaSourceSettings::GetSources(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, CGUIPassword::IsDatabasePathUnlocked(), CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CVideoInfoTag::m_firstAired, CVideoInfoTag::m_iSeason, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPath, MediaTypeEpisode, CDatabase::PrepareSQL(), CFileItemList::Reserve(), RunQuery(), CGUIListItem::SetProperty(), SortDescription::sortBy, SortByNone, SortUtils::SortFromDataset(), CDbUrl::ToString(), and VIDEODB_DETAILS_EPISODE_TVSHOW_ID.
Referenced by DumpToDummyFiles(), JSONRPC::CVideoLibrary::GetEpisodes(), GetEpisodesByActor(), GetEpisodesNav(), GetItems(), GetItemsForPath(), GetRecentlyAddedEpisodesNav(), GetSortedVideos(), and UPNP::CUPnPServer::OnSearchContainer().
GetEpisodesNav()
bool CVideoDatabase::GetEpisodesNav (const std::string & strBaseDir, CFileItemList & items, int idGenre = -1, int idYear = -1, int idActor = -1, int idDirector = -1, int idShow = -1, int idSeason = -1, const SortDescription & sortDescription = SortDescription(), int getDetails = VideoDbDetailsNone)
References CDbUrl::AddOption(), CFileItemList::Append(), CDbUrl::FromString(), GetEpisodesByWhere(), GetMoviesByWhere(), CDatabase::Filter::join, CDatabase::PrepareSQL(), CFileItemList::Size(), CDbUrl::ToString(), and CDatabase::Filter::where.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetExportVersion()
virtual int CVideoDatabase::GetExportVersion () const inline private virtual
Referenced by ExportToXML().
GetFileBasePathById()
std::string CVideoDatabase::GetFileBasePathById (int idFile)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by SetDefaultVideoVersion().
GetFileId() [1/3]
int CVideoDatabase::GetFileId (const CFileItem & item) protected
Get the id of this fileitem Works for both videodb:// items and normal fileitems.
Parameters
item CFileItem to grab the fileid of
Returns
id of the file, -1 if it is not in the db.
References GetFileId(), CFileItem::GetPath(), CFileItem::GetVideoInfoTag(), and CFileItem::HasVideoInfoTag().
Referenced by AddBookMarkForEpisode(), ClearBookMarkOfFile(), ClearBookMarksOfFile(), DeleteResumeBookMark(), EraseAllForFile(), EraseVideoSettings(), GetAndFillFileId(), GetBookMarksForFile(), GetEpisodeId(), GetEpisodesByFile(), GetFileId(), GetFileId(), GetFileInfo(), GetLastPlayed(), GetMovieId(), GetMovieInfo(), GetMusicVideoId(), GetPlayCount(), GetPlayCount(), GetStackTimes(), GetStreamDetails(), GetStreamDetails(), GetStreamDetails(), GetUsedImages(), GetVideoSettings(), GetVideoSettings(), and GetVideoVersionInfo().
GetFileId() [2/3]
int CVideoDatabase::GetFileId (const CVideoInfoTag & details) protected
References GetFileId(), CVideoInfoTag::GetPath(), and CVideoInfoTag::m_iFileId.
GetFileId() [3/3]
int CVideoDatabase::GetFileId (const std::string & url) protected
Get the id of a file from path.
Parameters
url full path to the file
Returns
id of the file, -1 if it is not in the db.
References GetPathId(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
GetFileIdByMovie()
int CVideoDatabase::GetFileIdByMovie (int idMovie)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by ConvertVideoToVersion().
GetFileInfo()
bool CVideoDatabase::GetFileInfo (const std::string & strFilenameAndPath, CVideoInfoTag & details, int idFile = -1)
References ConstructPath(), GetFileId(), CVideoInfoTag::GetPlayCount(), CVideoInfoTag::GetResumePoint(), GetStreamDetails(), CBookmark::HasSavedPlayerState(), CVideoInfoTag::IsEmpty(), CBookmark::IsSet(), CDateTime::IsValid(), CLog::Log(), LOGERROR, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_iFileId, CVideoInfoTag::m_lastPlayed, CDatabase::m_pDS, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPath, CDatabase::PrepareSQL(), CBookmark::RESUME, CDateTime::SetFromDBDateTime(), CVideoInfoTag::SetPlayCount(), and CVideoInfoTag::SetResumePoint().
Referenced by GetDefaultVideoVersion(), GetVideoVersions(), LoadVideoInfo(), and JSONRPC::CFileOperations::SetFileDetails().
GetFilePathById()
void CVideoDatabase::GetFilePathById (int idMovie, std::string & filePath, VideoDbContentType iType)
References ConstructPath(), EPISODES, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MOVIES, MUSICVIDEOS, CDatabase::PrepareSQL(), and TVSHOWS.
Referenced by anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), UPNP::CUPnPServer::OnUpdateObject(), CGUIDialogVideoManagerVersions::ProcessVideoVersion(), and XFILE::CVideoDatabaseFile::TranslatePath().
GetFilter()
bool CVideoDatabase::GetFilter (CDbUrl & videoUrl, Filter & filter, SortDescription & sorting) override virtual
Reimplemented from CDatabase.
References AppendIdLinkFilter(), CDatabase::Filter::AppendJoin(), AppendLinkFilter(), CDatabase::Filter::AppendWhere(), KODI::PLAYLIST::CSmartPlaylist::GetGroup(), KODI::PLAYLIST::CSmartPlaylist::GetLimit(), CDbUrl::GetOptions(), KODI::PLAYLIST::CSmartPlaylist::GetOrder(), KODI::PLAYLIST::CSmartPlaylist::GetOrderDirection(), CServiceBroker::GetSettingsComponent(), CDbUrl::GetType(), KODI::PLAYLIST::CSmartPlaylist::GetType(), KODI::PLAYLIST::CSmartPlaylist::GetWhereClause(), KODI::PLAYLIST::CSmartPlaylist::IsGroupMixed(), CDbUrl::IsValid(), SortDescription::limitEnd, KODI::PLAYLIST::CSmartPlaylist::LoadFromJson(), CDatabase::PrepareSQL(), CDbUrl::RemoveOption(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, SortAttributeIgnoreArticle, SortDescription::sortAttributes, SortDescription::sortBy, SortByNone, SortDescription::sortOrder, SortOrderNone, VIDEODB_ID_EPISODE_SEASON, VIDEODB_ID_EPISODE_SORTSEASON, VIDEODB_ID_MUSICVIDEO_ALBUM, and VIDEODB_ID_TV_PREMIERED.
Referenced by GetMoviesByWhere().
GetGenreById()
std::string CVideoDatabase::GetGenreById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetItemById(), and XFILE::CVideoDatabaseDirectory::GetLabel().
GetGenresNav()
bool CVideoDatabase::GetGenresNav (const std::string & strBaseDir, CFileItemList & items, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter(), bool countOnly = false)
References GetNavCommon().
Referenced by JSONRPC::CVideoLibrary::GetGenres(), CGUIDialogMediaFilter::GetItems(), GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetInProgressTvShowsNav()
bool CVideoDatabase::GetInProgressTvShowsNav (const std::string & strBaseDir, CFileItemList & items, unsigned int limit = 0, int getDetails = VideoDbDetailsNone)
References GetTvShowsByWhere(), CDatabase::Filter::order, CDatabase::PrepareSQL(), VIDEODB_ID_TV_TITLE, and CDatabase::Filter::where.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows::GetContent(), and JSONRPC::CVideoLibrary::GetInProgressTVShows().
GetItemById()
std::string CVideoDatabase::GetItemById (const std::string & itemType, int id)
References GetCountryById(), GetGenreById(), GetMusicVideoAlbumById(), GetPersonById(), GetSetById(), GetStudioById(), GetTagById(), and GetVideoVersionById().
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetLocalizedName().
GetItems() [1/3]
bool CVideoDatabase::GetItems (const std::string & strBaseDir, CFileItemList & items, const Filter & filter = Filter(), const SortDescription & sortDescription = SortDescription())
References CDbUrl::FromString(), GetItems(), CVideoDbUrl::GetItemType(), and CDbUrl::GetType().
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetContent(), XFILE::CSmartPlaylistDirectory::GetDirectory(), GetItems(), and GetItems().
GetItems() [2/3]
bool CVideoDatabase::GetItems (const std::string & strBaseDir, const std::string & mediaType, const std::string & itemType, CFileItemList & items, const Filter & filter = Filter(), const SortDescription & sortDescription = SortDescription())
References EPISODES, GetItems(), MOVIES, MUSICVIDEOS, and TVSHOWS.
GetItems() [3/3]
bool CVideoDatabase::GetItems (const std::string & strBaseDir, VideoDbContentType mediaType, const std::string & itemType, CFileItemList & items, const Filter & filter = Filter(), const SortDescription & sortDescription = SortDescription())
References CDatabase::Filter::AppendWhere(), EPISODES, GetActorsNav(), GetCountriesNav(), GetDirectorsNav(), GetEpisodesByWhere(), GetGenresNav(), GetMoviesByWhere(), GetMusicVideoAlbumsNav(), GetMusicVideosByWhere(), GetSeasonsNav(), GetSetsNav(), CServiceBroker::GetSettingsComponent(), GetStudiosNav(), GetTagsNav(), GetTvShowsByWhere(), GetVideoVersionsNav(), GetWritersNav(), GetYearsNav(), MOVIE_SETS, MOVIES, MUSICVIDEOS, CSettings::SETTING_VIDEOLIBRARY_GROUPSINGLEITEMSETS, CSettings::SETTING_VIDEOLIBRARY_SHOWEMPTYTVSHOWS, and TVSHOWS.
GetItemsForPath()
bool CVideoDatabase::GetItemsForPath (const std::string & content, const std::string & path, CFileItemList & items)
Get videos of the given content type from the given path.
Parameters
content the content type to fetch.
path the path to fetch videos from.
items the returned items
Returns
true if items are found, false otherwise.
References ADDON::content, GetEpisodesByWhere(), GetItemsForPath(), GetMoviesByWhere(), GetMusicVideosByWhere(), GetPathId(), XFILE::CMultiPathDirectory::GetPaths(), GetTvShowsByWhere(), URIUtils::IsMultiPath(), CDatabase::PrepareSQL(), SetPath(), CFileItemList::Size(), VIDEODB_ID_EPISODE_PARENTPATHID, VIDEODB_ID_MUSICVIDEO_PARENTPATHID, and VIDEODB_ID_PARENTPATHID.
Referenced by GetItemsForPath(), and CGUIWindowVideoBase::LoadVideoInfo().
GetLastPlayed() [1/2]
CDateTime CVideoDatabase::GetLastPlayed (const std::string & strFilenameAndPath)
Get the last played time of a filename and path.
Parameters
strFilenameAndPath filename and path to get the last played time for
Returns
the last played time of the item, or an invalid CDateTime on error
See also
UpdateLastPlayed
References GetFileId(), and GetLastPlayed().
Referenced by GetLastPlayed(), and PVR::CPVRRecording::UpdateMetadata().
GetLastPlayed() [2/2]
CDateTime CVideoDatabase::GetLastPlayed (int iFileId) private
Get the last played time of a filename and path.
Parameters
iFileId file id to get the playcount for
Returns
the last played time of the item, or an invalid CDateTime on error
See also
UpdateLastPlayed
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDateTime::SetFromDBDateTime().
GetLinksToTvShow()
bool CVideoDatabase::GetLinksToTvShow (int idMovie, std::vector< int > & ids)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by GetDetailsForMovie(), CGUIDialogVideoInfo::LinkMovieToTvShow(), and UpdateDetailsForMovie().
GetMatchingMusicVideo()
int CVideoDatabase::GetMatchingMusicVideo (const std::string & strArtist, const std::string & strAlbum = "", const std::string & strTitle = "")
References CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CDatabase::PrepareSQL(), VIDEODB_ID_MUSICVIDEO_ALBUM, and VIDEODB_ID_MUSICVIDEO_TITLE.
Referenced by CGUIWindowMusicNav::GetContextButtons(), and CGUIWindowMusicNav::OnContextButton().
GetMatchingTvShow()
int CVideoDatabase::GetMatchingTvShow (const CVideoInfoTag & show) protected
Check whether a show is already in the library. Matches on unique identifier or matching title and premiered date.
Parameters
show the details of the show to check for.
Returns
the show id if found, else -1.
References CDateTime::GetAsDBDate(), GetDbId(), CVideoInfoTag::GetPremiered(), CVideoInfoTag::GetUniqueID(), CVideoInfoTag::HasUniqueID(), id, CVideoInfoTag::m_strTitle, CDatabase::PrepareSQL(), VIDEODB_ID_TV_PREMIERED, and VIDEODB_ID_TV_TITLE.
Referenced by SetDetailsForTvShow().
GetMinSchemaVersion()
int CVideoDatabase::GetMinSchemaVersion () const inline override private virtual
Reimplemented from CDatabase.
GetMovieActorsByName()
void CVideoDatabase::GetMovieActorsByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoNav::DoSearch().
GetMovieCountriesByName()
void CVideoDatabase::GetMovieCountriesByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, and CDatabase::PrepareSQL().
GetMovieDirectorsByName()
void CVideoDatabase::GetMovieDirectorsByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoNav::DoSearch().
GetMovieGenresByName()
void CVideoDatabase::GetMovieGenresByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoNav::DoSearch().
GetMovieId()
int CVideoDatabase::GetMovieId (const std::string & strFilenameAndPath)
References GetFileId(), GetPathId(), CLog::Log(), LOGDATABASE, LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMovie, CDatabase::PrepareSQL(), and VERSION.
Referenced by GetMovieInfo(), HasMovieInfo(), RemoveContentForPath(), and SetDetailsForMovie().
GetMovieInfo()
bool CVideoDatabase::GetMovieInfo (const std::string & strFilenameAndPath, CVideoInfoTag & details, int idMovie = -1, int idVersion = -1, int getDetails = VideoDbDetailsAll)
Todo:
get rid of "videos with versions as folder" hack!
References GetDetailsForMovie(), GetFileId(), GetMovieId(), CVideoInfoTag::IsEmpty(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and VIDEO_VERSION_ID_ALL.
Referenced by UPNP::CUPnPServer::Build(), JSONRPC::CVideoLibrary::FillFileItemList(), GetDetailsByTypeAndId(), JSONRPC::CPlayerOperations::GetItem(), JSONRPC::CVideoLibrary::GetMovieDetails(), CFileItem::LoadDetails(), LoadVideoInfo(), CGUIDialogVideoInfo::OnSearchItemFound(), JSONRPC::CVideoLibrary::RefreshMovie(), JSONRPC::CVideoLibrary::SetMovieDetails(), CGUIWindowVideoBase::ShowInfo(), CGUIDialogVideoInfo::UpdateVideoItemSortTitle(), CGUIDialogVideoInfo::UpdateVideoItemTitle(), and CVideoLibraryRefreshingJob::Work().
GetMoviesByActor()
void CVideoDatabase::GetMoviesByActor (const std::string & strActor, CFileItemList & items)
References GetMoviesByWhere(), CDatabase::Filter::group, CDatabase::Filter::join, name, CDatabase::PrepareSQL(), and CDatabase::Filter::where.
Referenced by CGUIDialogVideoInfo::DoSearch().
GetMoviesByName()
void CVideoDatabase::GetMoviesByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CServiceBroker::GetSettingsComponent(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CDatabase::PrepareSQL(), CSettings::SETTING_VIDEOLIBRARY_GROUPMOVIESETS, VIDEODB_ID_ORIGINALTITLE, and VIDEODB_ID_TITLE.
Referenced by CGUIWindowVideoNav::DoSearch().
GetMoviesByPlot()
void CVideoDatabase::GetMoviesByPlot (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CDatabase::PrepareSQL(), VIDEODB_ID_PLOT, VIDEODB_ID_PLOTOUTLINE, VIDEODB_ID_TAGLINE, and VIDEODB_ID_TITLE.
Referenced by CGUIWindowVideoNav::DoSearch().
GetMoviesByWhere()
bool CVideoDatabase::GetMoviesByWhere (const std::string & strBaseDir, const Filter & filter, CFileItemList & items, const SortDescription & sortDescription = SortDescription(), int getDetails = VideoDbDetailsNone)
Todo:
get rid of "videos with versions as folder" hack!
References CFileItemList::Add(), CGUIPassword::bMasterUser, DatabaseUtils::BuildLimitClause(), CDatabase::BuildSQL(), data(), FieldRow, CDatabase::Filter::fields, CDbUrl::FromString(), g_passwordManager, GetDetailsForMovie(), GetFilter(), CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CVideoInfoTag::GetPlayCount(), CDatabase::GetSingleValue(), CMediaSourceSettings::GetSources(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, CGUIPassword::IsDatabasePathUnlocked(), CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CVideoInfoTag::m_iDbId, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPath, MediaTypeMovie, CDatabase::PrepareSQL(), CFileItemList::Reserve(), RunQuery(), CGUIListItem::SetProperty(), SortDescription::sortBy, SortByNone, SortUtils::SortFromDataset(), value, and VIDEO_VERSION_ID_ALL.
Referenced by DumpToDummyFiles(), GetEpisodesNav(), GetItems(), GetItemsForPath(), GetMoviesByActor(), GetMoviesNav(), GetRecentlyAddedMoviesNav(), GetSeasonsNav(), GetSetsByWhere(), GetSortedVideos(), and UPNP::CUPnPServer::OnSearchContainer().
GetMoviesNav()
bool CVideoDatabase::GetMoviesNav (const std::string & strBaseDir, CFileItemList & items, int idGenre = -1, int idYear = -1, int idActor = -1, int idDirector = -1, int idStudio = -1, int idCountry = -1, int idSet = -1, int idTag = -1, const SortDescription & sortDescription = SortDescription(), int getDetails = VideoDbDetailsNone)
References CDbUrl::AddOption(), CDbUrl::FromString(), GetMoviesByWhere(), and CDbUrl::ToString().
Referenced by CGUIDialogVideoManagerVersions::GetAllOtherMovies(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), JSONRPC::CVideoLibrary::GetMovies(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArtTypes(), JSONRPC::CVideoLibrary::GetMovieSetDetails(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::GetRemoteArt(), CGUIDialogSmartPlaylistRule::OnBrowse(), and CGUIDialogVideoInfo::SetMovie().
GetMovieTitle()
std::string CVideoDatabase::GetMovieTitle (int idMovie)
References CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and VIDEODB_ID_TITLE.
Referenced by CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), and GetVideoItemTitle().
GetMusicVideoAlbumById()
std::string CVideoDatabase::GetMusicVideoAlbumById (int id)
References CDatabase::GetSingleValue(), CDatabase::PrepareSQL(), and VIDEODB_ID_MUSICVIDEO_ALBUM.
Referenced by GetItemById().
GetMusicVideoAlbumsByName()
void CVideoDatabase::GetMusicVideoAlbumsByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CDatabase::PrepareSQL(), and VIDEODB_ID_MUSICVIDEO_ALBUM.
Referenced by CGUIDialogSmartPlaylistRule::OnBrowse().
GetMusicVideoAlbumsNav()
bool CVideoDatabase::GetMusicVideoAlbumsNav (const std::string & strBaseDir, CFileItemList & items, int idArtist, const Filter & filter = Filter(), bool countOnly = false)
References CFileItemList::Add(), CDbUrl::AddOption(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDbUrl::AppendPath(), CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), CFileItemList::Contains(), CDatabase::Filter::fields, CDbUrl::FromString(), g_passwordManager, CMediaSourceSettings::GetInstance(), GetMusicVideoInfo(), CMediaSourceSettings::GetSources(), CDatabase::Filter::group, CGUIPassword::IsDatabasePathUnlocked(), CLog::Log(), LOGERROR, CVideoInfoTag::m_artist, CVideoInfoTag::m_iDbId, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, CVideoInfoTag::m_strAlbum, CVideoInfoTag::m_type, MediaTypeAlbum, CDatabase::Filter::order, CDatabase::PrepareSQL(), RunQuery(), CFileItem::SetFromVideoInfoTag(), CFileItem::SetLabel(), CVideoInfoTag::SetPath(), CGUIListItem::SetProperty(), CFileItemList::Size(), CDbUrl::ToString(), VIDEODB_ID_MUSICVIDEO_ALBUM, VIDEODB_ID_MUSICVIDEO_ARTIST, VIDEODB_ID_MUSICVIDEO_PLOT, and VIDEODB_ID_MUSICVIDEO_TITLE.
Referenced by CGUIDialogMediaFilter::GetItems(), and GetItems().
GetMusicVideoArtistsByName()
void CVideoDatabase::GetMusicVideoArtistsByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoNav::DoSearch(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetMusicVideoDirectorsByName()
void CVideoDatabase::GetMusicVideoDirectorsByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoNav::DoSearch().
GetMusicVideoGenresByName()
void CVideoDatabase::GetMusicVideoGenresByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoNav::DoSearch().
GetMusicVideoId()
int CVideoDatabase::GetMusicVideoId (const std::string & strFilenameAndPath) protected
References GetFileId(), CLog::Log(), LOGDATABASE, LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by GetMusicVideoInfo(), HasMusicVideoInfo(), RemoveContentForPath(), and SetDetailsForMusicVideo().
GetMusicVideoInfo()
bool CVideoDatabase::GetMusicVideoInfo (const std::string & strFilenameAndPath, CVideoInfoTag & details, int idMVideo = -1, int getDetails = VideoDbDetailsAll)
References GetDetailsForMusicVideo(), GetMusicVideoId(), CVideoInfoTag::IsEmpty(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by UPNP::CUPnPServer::Build(), JSONRPC::CVideoLibrary::FillFileItemList(), GetDetailsByTypeAndId(), JSONRPC::CPlayerOperations::GetItem(), GetMusicVideoAlbumsNav(), JSONRPC::CVideoLibrary::GetMusicVideoDetails(), CFileItem::LoadDetails(), LoadVideoInfo(), CGUIWindowMusicNav::OnContextButton(), CGUIDialogVideoInfo::OnSearchItemFound(), JSONRPC::CVideoLibrary::RefreshMusicVideo(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), CGUIWindowVideoBase::ShowInfo(), CGUIDialogVideoInfo::UpdateVideoItemTitle(), and CVideoLibraryRefreshingJob::Work().
GetMusicVideosByAlbum()
void CVideoDatabase::GetMusicVideosByAlbum (const std::string & strAlbum, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CDatabase::PrepareSQL(), VIDEODB_ID_MUSICVIDEO_ALBUM, and VIDEODB_ID_MUSICVIDEO_TITLE.
Referenced by CGUIWindowVideoNav::DoSearch().
GetMusicVideosByArtist()
void CVideoDatabase::GetMusicVideosByArtist (const std::string & strArtist, CFileItemList & items)
Todo:
SMARTPLAYLISTS what is this here for???
References CFileItemList::Add(), CFileItemList::Clear(), GetDetailsForMusicVideo(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIDialogVideoInfo::DoSearch().
GetMusicVideosByName()
void CVideoDatabase::GetMusicVideosByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CDatabase::PrepareSQL(), and VIDEODB_ID_MUSICVIDEO_TITLE.
Referenced by CGUIWindowVideoNav::DoSearch().
GetMusicVideosByWhere()
bool CVideoDatabase::GetMusicVideosByWhere (const std::string & baseDir, const Filter & filter, CFileItemList & items, bool checkLocks = true, const SortDescription & sortDescription = SortDescription(), int getDetails = VideoDbDetailsNone)
References CFileItemList::Add(), CDbUrl::AppendPath(), CGUIPassword::bMasterUser, DatabaseUtils::BuildLimitClause(), CDatabase::BuildSQL(), data(), FieldRow, CDatabase::Filter::fields, CDbUrl::FromString(), g_passwordManager, GetDetailsForMusicVideo(), CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CDbUrl::GetOptions(), CVideoInfoTag::GetPlayCount(), CDatabase::GetSingleValue(), CMediaSourceSettings::GetSources(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, CGUIPassword::IsDatabasePathUnlocked(), CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPath, MediaTypeMusicVideo, CDatabase::PrepareSQL(), CFileItemList::Reserve(), RunQuery(), CGUIListItem::SetProperty(), SortDescription::sortBy, SortByNone, SortUtils::SortFromDataset(), and CDbUrl::ToString().
Referenced by CPartyModeManager::AddRandomSongs(), GetItems(), GetItemsForPath(), GetMusicVideosNav(), GetRecentlyAddedMusicVideosNav(), GetSortedVideos(), and UPNP::CUPnPServer::OnSearchContainer().
GetMusicVideosNav()
bool CVideoDatabase::GetMusicVideosNav (const std::string & strBaseDir, CFileItemList & items, int idGenre = -1, int idYear = -1, int idArtist = -1, int idDirector = -1, int idStudio = -1, int idAlbum = -1, int idTag = -1, const SortDescription & sortDescription = SortDescription(), int getDetails = VideoDbDetailsNone)
References CDbUrl::AddOption(), CDbUrl::FromString(), GetMusicVideosByWhere(), and CDbUrl::ToString().
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), JSONRPC::CVideoLibrary::GetMusicVideos(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetNavCommon()
bool CVideoDatabase::GetNavCommon (const std::string & strBaseDir, CFileItemList & items, const char * type, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter(), bool countOnly = false) protected
References CFileItemList::Add(), CDatabase::Filter::AppendField(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDbUrl::AppendPath(), CGUIPassword::bMasterUser, CDatabase::BuildSQL(), CFileItemList::Contains(), CDatabase::Filter::fields, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CDatabase::Filter::group, CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MOVIES, MUSICVIDEOS, CDatabase::Filter::order, CDatabase::PrepareSQL(), RunQuery(), CDbUrl::ToString(), and TVSHOWS.
Referenced by GetCountriesNav(), GetGenresNav(), GetStudiosNav(), and GetTagsNav().
GetPathHash()
bool CVideoDatabase::GetPathHash (const std::string & path, std::string & hash)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by KODI::VIDEO::CVideoInfoScanner::DoScan(), and KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder().
GetPathId()
int CVideoDatabase::GetPathId (const std::string & strPath)
References URIUtils::AddSlashAtEnd(), URIUtils::GetParentPath(), URIUtils::IsStack(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddPath(), AddPathToTvShow(), CleanLibrary(), CleanMediaType(), KODI::VIDEO::CVideoInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), EraseAllForFile(), GetFileId(), GetItemsForPath(), GetMovieId(), GetPathsForTvShow(), GetPlayCounts(), GetScraperForPath(), GetSourcePath(), GetTvShowId(), and KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo().
GetPaths()
bool CVideoDatabase::GetPaths (std::set< std::string > & paths)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, and CDatabase::m_pDS.
Referenced by CleanLibrary(), ExportToXML(), and KODI::VIDEO::CVideoInfoScanner::Start().
GetPathsForTvShow()
bool CVideoDatabase::GetPathsForTvShow (int idShow, std::set< int > & paths)
References GetPathId(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by DeleteTvShow(), and KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder().
GetPathsLinkedToTvShow()
bool CVideoDatabase::GetPathsLinkedToTvShow (int idShow, std::vector< std::string > & paths)
return the paths linked to a tvshow.
Parameters
idShow the id of the tvshow.
paths [out] the list of paths associated with the show.
Returns
true on success, false on failure.
References CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CVideoLibraryRefreshingJob::Work().
GetPeopleNav()
bool CVideoDatabase::GetPeopleNav (const std::string & strBaseDir, CFileItemList & items, const char * type, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter(), bool countOnly = false) protected
Todo:
This routine (and probably others at this same level) use playcount as a reference to filter on at a later point. This means that we MUST filter these levels as you'll get double ups. Ideally we'd allow playcount to filter through as we normally do for tvshows to save this happening. Also, we apply this same filtering logic to the locked or unlocked paths to prevent these from showing. Whether or not this should happen is a tricky one - it complicates all the high level categories (everything above titles).
References CFileItemList::Add(), CVideoDatabase::CActor::appearances, CDatabase::Filter::AppendField(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDbUrl::AppendPath(), CGUIPassword::bMasterUser, CDatabase::BuildSQL(), end(), EPISODES, CDatabase::Filter::fields, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CServiceBroker::GetSettingsComponent(), CMediaSourceSettings::GetSources(), CDatabase::Filter::group, CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGDATABASE, LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, MediaTypeArtist, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MOVIES, MUSICVIDEOS, CVideoDatabase::CActor::name, CDatabase::Filter::order, CVideoDatabase::CActor::playcount, CDatabase::PrepareSQL(), CSettings::SETTING_VIDEOLIBRARY_SHOWPERFORMERS, CFileItemList::Size(), CVideoDatabase::CActor::thumb, CDbUrl::ToString(), and TVSHOWS.
Referenced by GetActorsNav(), GetDirectorsNav(), and GetWritersNav().
GetPersonById()
std::string CVideoDatabase::GetPersonById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetItemById().
GetPlayCount() [1/3]
int CVideoDatabase::GetPlayCount (const CFileItem & item)
Get the playcount of an item.
Parameters
item CFileItem to get the playcount for
Returns
the playcount of the item, or -1 on error
See also
SetPlayCount, IncrementPlayCount, GetPlayCounts
References CFileItem::GetDynPath(), GetFileId(), GetPlayCount(), and KODI::VIDEO::IsBlurayPlaylist().
Referenced by GetPlayCount(), GetPlayCount(), GetVideoVersions(), IncrementPlayCount(), UpdateLastPlayed(), and PVR::CPVRRecording::UpdateMetadata().
GetPlayCount() [2/3]
int CVideoDatabase::GetPlayCount (const std::string & strFilenameAndPath)
Get the playcount of a filename and path.
Parameters
strFilenameAndPath filename and path to get the playcount for
Returns
the playcount of the item, or -1 on error
See also
SetPlayCount, IncrementPlayCount, GetPlayCounts
References GetFileId(), and GetPlayCount().
GetPlayCount() [3/3]
int CVideoDatabase::GetPlayCount (int iFileId) private
Get the playcount for a file id.
Parameters
iFileId file id to get the playcount for
Returns
the playcount of the item, or -1 on error
See also
SetPlayCount, IncrementPlayCount, GetPlayCounts
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
GetPlayCounts()
bool CVideoDatabase::GetPlayCounts (const std::string & path, CFileItemList & items)
Get the playcount and resume point of a list of items Note that if the resume point is already set on an item, it won't be overridden.
Parameters
path the path to fetch videos from
items CFileItemList to fetch the playcounts for
See also
GetPlayCount, SetPlayCount, IncrementPlayCount
Todo:
also test a single query for the above and below
References ConstructPath(), CFileItemList::Get(), GetPathId(), XFILE::CMultiPathDirectory::GetPaths(), GetPlayCounts(), URIUtils::IsMultiPath(), CFileItem::IsPlugin(), URIUtils::IsPlugin(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), CBookmark::RESUME, RunQuery(), and CFileItemList::SetFastLookup().
Referenced by KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), GetPlayCounts(), and CGUIWindowVideoBase::LoadVideoInfo().
GetRandomMusicVideoIDs()
unsigned int CVideoDatabase::GetRandomMusicVideoIDs (const std::string & strWhere, std::vector< std::pair< int, int > > & songIDs)
Gets music video IDs in random order that match the where clause.
Parameters
strWhere the SQL where clause to apply in the query
songIDs a vector of <2, id> pairs suited to party mode use
Returns
count of music video IDs found.
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CPartyModeManager::Enable().
GetRatings()
void CVideoDatabase::GetRatings (int media_id, const std::string & media_type, RatingMap & ratings) protected
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by GetDetailsForEpisode(), GetDetailsForMovie(), and GetDetailsForTvShow().
GetRecentlyAddedEpisodesNav()
bool CVideoDatabase::GetRecentlyAddedEpisodesNav (const std::string & strBaseDir, CFileItemList & items, unsigned int limit = 0, int getDetails = VideoDbDetailsNone)
References GetEpisodesByWhere(), CServiceBroker::GetSettingsComponent(), CDatabase::Filter::limit, CDatabase::Filter::order, and CDatabase::PrepareSQL().
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedEpisodes::GetContent(), JSONRPC::CVideoLibrary::GetRecentlyAddedEpisodes(), and CRecentlyAddedJob::UpdateVideo().
GetRecentlyAddedMoviesNav()
bool CVideoDatabase::GetRecentlyAddedMoviesNav (const std::string & strBaseDir, CFileItemList & items, unsigned int limit = 0, int getDetails = VideoDbDetailsNone)
References GetMoviesByWhere(), CServiceBroker::GetSettingsComponent(), CDatabase::Filter::limit, CDatabase::Filter::order, and CDatabase::PrepareSQL().
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMovies::GetContent(), JSONRPC::CVideoLibrary::GetRecentlyAddedMovies(), and CRecentlyAddedJob::UpdateVideo().
GetRecentlyAddedMusicVideosNav()
bool CVideoDatabase::GetRecentlyAddedMusicVideosNav (const std::string & strBaseDir, CFileItemList & items, unsigned int limit = 0, int getDetails = VideoDbDetailsNone)
References GetMusicVideosByWhere(), CServiceBroker::GetSettingsComponent(), CDatabase::Filter::limit, CDatabase::Filter::order, and CDatabase::PrepareSQL().
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMusicVideos::GetContent(), JSONRPC::CVideoLibrary::GetRecentlyAddedMusicVideos(), and CRecentlyAddedJob::UpdateVideo().
GetResumeBookMark()
bool CVideoDatabase::GetResumeBookMark (const std::string & strFilenameAndPath, CBookmark & bookmark)
References GetBookMarksForFile(), and CBookmark::RESUME.
Referenced by anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), GetResumePoint(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), CApplication::PlayFile(), PVR::CPVRRecording::UpdateMetadata(), and JSONRPC::CVideoLibrary::UpdateResumePoint().
GetResumePoint()
bool CVideoDatabase::GetResumePoint (CVideoInfoTag & tag)
References XFILE::CStackDirectory::GetDirectory(), GetResumeBookMark(), URIUtils::IsDiscImageStack(), CLog::Log(), LOGERROR, CDatabase::m_pDS2, CBookmark::partNumber, CDatabase::PrepareSQL(), CBookmark::RESUME, and CFileItemList::Size().
Referenced by CSaveFileState::DoWork().
GetSafeFile()
std::string CVideoDatabase::GetSafeFile (const std::string & dir, const std::string & name) const private
Get a safe filename from a given string.
Parameters
dir directory to use for the file
name movie, show name, or actor to get a safe filename for
Returns
safe filename based on this title
References URIUtils::AddFileToFolder(), CUtil::MakeLegalFileName(), and name.
Referenced by ExportActorThumbs(), ExportToXML(), and ImportFromXML().
GetSameVideoItems()
void CVideoDatabase::GetSameVideoItems (const CFileItem & item, CFileItemList & items)
References CFileItemList::Add(), GetDetailsByTypeAndId(), CVideoInfoTag::GetTitle(), CFileItem::GetVideoContentType(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::GetYear(), CVideoInfoTag::HasYear(), CLog::Log(), LOGERROR, CVideoInfoTag::m_iDbId, CDatabase::m_pDB, CDatabase::m_pDS, CVideoInfoTag::m_type, MOVIES, CDatabase::PrepareSQL(), and VIDEODB_ID_TITLE.
Referenced by CGUIDialogVideoManagerVersions::GetSimilarMovies(), and CGUIDialogVideoManagerVersions::ProcessVideoVersion().
GetSchemaVersion()
int CVideoDatabase::GetSchemaVersion () const override private virtual
Implements CDatabase.
Referenced by CreateTables().
GetScraperForPath() [1/3]
ScraperPtr CVideoDatabase::GetScraperForPath (const std::string & strPath)
References GetScraperForPath().
Referenced by CleanDatabase(), KODI::VIDEO::CVideoInfoScanner::DoScan(), ExportToXML(), GetContentForPath(), CGUIWindowVideoNav::GetContextButtons(), CGUIWindowVideoBase::GetDirectory(), CGUIWindowVideoBase::GetScraperForItem(), GetScraperForPath(), GetScraperForPath(), InvalidatePathHash(), LookupByFolders(), CGUIWindowVideoBase::OnAssignContent(), CGUIWindowVideoBase::OnItemInfo(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), and CVideoLibraryRefreshingJob::Work().
GetScraperForPath() [2/3]
ScraperPtr CVideoDatabase::GetScraperForPath (const std::string & strPath, KODI::VIDEO::SScanSettings & settings)
References GetScraperForPath().
GetScraperForPath() [3/3]
ScraperPtr CVideoDatabase::GetScraperForPath (const std::string & strPath, KODI::VIDEO::SScanSettings & settings, bool & foundDirectly)
Retrieve the scraper and settings we should use for the specified path If the scraper is not set on this particular path, we'll recursively check parent folders.
Parameters
strPath path to start searching in.
settings [out] scan settings for this folder.
foundDirectly [out] true if a scraper was found directly for strPath, false if it was in a parent path.
Returns
A ScraperPtr containing the scraper information. Returns NULL if a trivial (Content == CONTENT_NONE) scraper or no scraper is found.
References ADDON::CHOICE_YES, ADDON::content, CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_NONE, CONTENT_TVSHOWS, KODI::VIDEO::SScanSettings::exclude, ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), URIUtils::GetDirectory(), XFILE::CMultiPathDirectory::GetFirstPath(), URIUtils::GetParentPath(), GetPathId(), URIUtils::IsMultiPath(), CLog::Log(), LOGERROR, KODI::VIDEO::SScanSettings::m_allExtAudio, CDatabase::m_pDB, CDatabase::m_pDS, KODI::VIDEO::SScanSettings::noupdate, KODI::VIDEO::SScanSettings::parent_name, KODI::VIDEO::SScanSettings::parent_name_root, CDatabase::PrepareSQL(), KODI::VIDEO::SScanSettings::recurse, and ADDON::TranslateContent().
GetSeasonForEpisode()
int CVideoDatabase::GetSeasonForEpisode (int idEpisode)
References CDatabase::GetSingleValue(), CDatabase::PrepareSQL(), and VIDEODB_ID_EPISODE_SEASON.
Referenced by UPNP::CUPnPServer::Announce().
GetSeasonId()
int CVideoDatabase::GetSeasonId (int idShow, int season)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by CVideoFileItemListModifier::AddQueuingFolder(), AddSeason(), UPNP::CUPnPServer::Build(), CGUIWindowVideoNav::GetDirectory(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), and KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow().
GetSeasonInfo() [1/4]
bool CVideoDatabase::GetSeasonInfo (const std::string & path, int season, CVideoInfoTag & details, CFileItem * item)
References GetSeasonInfo(), CDatabase::GetSingleValue(), LOGERROR, and CDatabase::PrepareSQL().
Referenced by UPNP::CUPnPServer::Build(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArtTypes(), JSONRPC::CVideoLibrary::GetSeasonDetails(), GetSeasonInfo(), GetSeasonInfo(), GetSeasonInfo(), CGUIDialogVideoInfo::OnSearchItemFound(), JSONRPC::CVideoLibrary::SetSeasonDetails(), CGUIWindowVideoBase::ShowInfo(), UpdateDetailsForTvShow(), CGUIDialogVideoInfo::UpdateVideoItemTitle(), and CVideoLibraryRefreshingJob::Work().
GetSeasonInfo() [2/4]
bool CVideoDatabase::GetSeasonInfo (int idSeason, CVideoInfoTag & details, bool allDetails, CFileItem * item) private
References g_localizeStrings, CFileItemList::Get(), CLocalizeStrings::Get(), GetSeasonsNav(), index(), CLog::Log(), LOGERROR, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iIdSeason, CVideoInfoTag::m_iIdShow, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_iUserRating, CDatabase::m_pDB, CDatabase::m_pDS, CVideoInfoTag::m_strSortTitle, CVideoInfoTag::m_strTitle, CVideoInfoTag::m_type, MediaTypeSeason, name, CDatabase::PrepareSQL(), and CFileItemList::Size().
GetSeasonInfo() [3/4]
bool CVideoDatabase::GetSeasonInfo (int idSeason, CVideoInfoTag & details, bool allDetails = true)
References GetSeasonInfo().
GetSeasonInfo() [4/4]
bool CVideoDatabase::GetSeasonInfo (int idSeason, CVideoInfoTag & details, CFileItem * item)
References GetSeasonInfo().
GetSeasonsByWhere()
bool CVideoDatabase::GetSeasonsByWhere (const std::string & strBaseDir, const Filter & filter, CFileItemList & items, bool appendFullShowPath = true, const SortDescription & sortDescription = SortDescription())
References CFileItemList::Add(), CDbUrl::AppendPath(), CGUIPassword::bMasterUser, DatabaseUtils::BuildLimitClause(), CDatabase::BuildSQL(), CDatabase::Filter::fields, g_localizeStrings, g_passwordManager, CLocalizeStrings::Get(), CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CServiceBroker::GetSettingsComponent(), CDatabase::GetSingleValue(), CMediaSourceSettings::GetSources(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, id, CGUIPassword::IsDatabasePathUnlocked(), CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, MediaTypeSeason, name, CDatabase::PrepareSQL(), RunQuery(), CGUIListItem::SetProperty(), SortDescription::sortBy, SortByNone, CDbUrl::ToString(), VIDEODB_ID_SEASON_EPISODES_INPROGRESS, VIDEODB_ID_SEASON_EPISODES_TOTAL, VIDEODB_ID_SEASON_EPISODES_WATCHED, VIDEODB_ID_SEASON_ID, VIDEODB_ID_SEASON_NAME, VIDEODB_ID_SEASON_NUMBER, VIDEODB_ID_SEASON_PREMIERED, VIDEODB_ID_SEASON_TVSHOW_GENRE, VIDEODB_ID_SEASON_TVSHOW_ID, VIDEODB_ID_SEASON_TVSHOW_MPAA, VIDEODB_ID_SEASON_TVSHOW_PATH, VIDEODB_ID_SEASON_TVSHOW_PLOT, VIDEODB_ID_SEASON_TVSHOW_PREMIERED, VIDEODB_ID_SEASON_TVSHOW_STUDIO, VIDEODB_ID_SEASON_TVSHOW_TITLE, and VIDEODB_ID_SEASON_USER_RATING.
Referenced by GetSeasonsNav(), and UPNP::CUPnPServer::OnSearchContainer().
GetSeasonsNav()
bool CVideoDatabase::GetSeasonsNav (const std::string & strBaseDir, CFileItemList & items, int idActor = -1, int idDirector = -1, int idGenre = -1, int idYear = -1, int idShow = -1, bool getLinkedMovies = true)
References CDbUrl::AddOption(), CFileItemList::Append(), CDbUrl::FromString(), GetMoviesByWhere(), GetSeasonsByWhere(), CDatabase::Filter::join, CDatabase::PrepareSQL(), CFileItemList::Size(), CDbUrl::ToString(), and CDatabase::Filter::where.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetContent(), GetItems(), GetSeasonInfo(), and JSONRPC::CVideoLibrary::GetSeasons().
GetSetById()
std::string CVideoDatabase::GetSetById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetItemById(), XFILE::CVideoDatabaseDirectory::GetLabel(), and CGUIDialogVideoInfo::GetSetForMovie().
GetSetByNameLike()
std::string CVideoDatabase::GetSetByNameLike (const std::string & nameLike) const
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
GetSetInfo()
bool CVideoDatabase::GetSetInfo (int idSet, CVideoInfoTag & details, CFileItem * item = nullptr)
References GetSetsByWhere(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CVideoInfoTag::IsEmpty(), CLog::Log(), LOGERROR, CDatabase::PrepareSQL(), CFileItemList::Size(), and CDatabase::Filter::where.
Referenced by anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), JSONRPC::CVideoLibrary::GetMovieSetDetails(), JSONRPC::CVideoLibrary::SetMovieSetDetails(), and CGUIDialogVideoInfo::UpdateVideoItemTitle().
GetSetsByWhere()
bool CVideoDatabase::GetSetsByWhere (const std::string & strBaseDir, const Filter & filter, CFileItemList & items, bool ignoreSingleMovieSets = false)
References CFileItemList::Append(), CFileItemList::ClearItems(), CDbUrl::FromString(), GetMoviesByWhere(), CDbUrl::GetOptions(), GroupUtils::Group(), GroupAttributeIgnoreSingleItems, GroupAttributeNone, GroupBySet, CDatabase::Filter::join, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::Filter::order.
Referenced by GetSetInfo(), and GetSetsNav().
GetSetsNav()
bool CVideoDatabase::GetSetsNav (const std::string & strBaseDir, CFileItemList & items, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter(), bool ignoreSingleMovieSets = false)
References GetSetsByWhere(), and MOVIES.
Referenced by GetItems(), JSONRPC::CVideoLibrary::GetMovieSets(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetSortedVideos()
bool CVideoDatabase::GetSortedVideos (const MediaType & mediaType, const std::string & strBaseDir, const SortDescription & sortDescription, CFileItemList & items, const Filter & filter = Filter())
References GetEpisodesByWhere(), GetMoviesByWhere(), GetMusicVideosByWhere(), GetTvShowsByWhere(), CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, CFileItemList::SetContent(), SortAttributeIgnoreFolders, SortDescription::sortAttributes, SortDescription::sortBy, SortByDateAdded, SortByFile, SortByLabel, SortByLastPlayed, SortByOriginalTitle, SortByPlaycount, SortByRating, SortBySortTitle, SortByTitle, SortByUserRating, SortByYear, success, and CMediaTypes::ToPlural().
Referenced by CGUIDialogVideoInfo::GetItemsForTag(), and CGUIDialogVideoInfo::GetMoviesForSet().
GetSourcePath() [1/2]
bool CVideoDatabase::GetSourcePath (const std::string & path, std::string & sourcePath)
References GetSourcePath().
Referenced by CleanMediaType(), and GetSourcePath().
GetSourcePath() [2/2]
bool CVideoDatabase::GetSourcePath (const std::string & path, std::string & sourcePath, KODI::VIDEO::SScanSettings & settings)
References KODI::VIDEO::SScanSettings::exclude, URIUtils::GetDirectory(), XFILE::CMultiPathDirectory::GetFirstPath(), URIUtils::GetParentPath(), GetPathId(), URIUtils::IsMultiPath(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, KODI::VIDEO::SScanSettings::noupdate, KODI::VIDEO::SScanSettings::parent_name, KODI::VIDEO::SScanSettings::parent_name_root, CDatabase::PrepareSQL(), and KODI::VIDEO::SScanSettings::recurse.
GetStackTimes()
bool CVideoDatabase::GetStackTimes (const std::string & filePath, std::vector< uint64_t > & times)
GetStackTimes() obtains any saved video times for the stacked file.
Return values
Returns true if the stack times exist, false otherwise.
References GetFileId(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoBase::GetContextButtons(), KODI::VIDEO::UTILS::GetStackPartResumeInformation(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), and CGUIWindowVideoBase::OnPlayStackPart().
GetStreamDetails() [1/3]
bool CVideoDatabase::GetStreamDetails (CFileItem & item)
References GetFileId(), GetStreamDetails(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), and CVideoInfoTag::m_iFileId.
Referenced by CSaveFileState::DoWork(), GetDetailsForEpisode(), GetDetailsForMovie(), GetDetailsForMusicVideo(), GetFileInfo(), GetStreamDetails(), GetStreamDetails(), CVideoThumbLoader::LoadItemCached(), and PVR::CPVRRecording::UpdateMetadata().
GetStreamDetails() [2/3]
bool CVideoDatabase::GetStreamDetails (const std::string & filenameAndPath, CStreamDetails & details)
References GetFileId(), and GetStreamDetails().
GetStreamDetails() [3/3]
bool CVideoDatabase::GetStreamDetails (CVideoInfoTag & tag)
References CStreamDetails::AddStream(), CStreamDetail::AUDIO, CStreamDetails::DetermineBestStreams(), URIUtils::GetExtension(), GetFileId(), CStreamDetails::GetVideoDuration(), CLog::Log(), LOGERROR, CStreamDetailVideo::m_fAspect, CStreamDetailAudio::m_iChannels, CStreamDetailVideo::m_iDuration, CStreamDetailVideo::m_iHeight, CStreamDetailVideo::m_iWidth, CDatabase::m_pDB, CStreamDetailVideo::m_strCodec, CStreamDetailAudio::m_strCodec, CStreamDetailVideo::m_strHdrType, CStreamDetailVideo::m_strLanguage, CStreamDetailAudio::m_strLanguage, CStreamDetailSubtitle::m_strLanguage, CStreamDetailVideo::m_strStereoMode, CDatabase::PrepareSQL(), CStreamDetails::Reset(), CStreamDetail::SUBTITLE, and CStreamDetail::VIDEO.
GetStudioById()
std::string CVideoDatabase::GetStudioById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetItemById().
GetStudiosNav()
bool CVideoDatabase::GetStudiosNav (const std::string & strBaseDir, CFileItemList & items, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter(), bool countOnly = false)
References GetNavCommon().
Referenced by CGUIDialogMediaFilter::GetItems(), GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetSubPaths()
bool CVideoDatabase::GetSubPaths (const std::string & basepath, std::vector< std::pair< int, std::string > > & subpaths)
retrieve subpaths of a given path. Assumes a hierarchical folder structure
Parameters
basepath the root path to retrieve subpaths for
subpaths the returned subpaths
Returns
true if we successfully retrieve subpaths (may be zero), false on error
References URIUtils::AddSlashAtEnd(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CleanLibrary(), RemoveContentForPath(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), and KODI::VIDEO::CVideoInfoScanner::Start().
GetTagById()
std::string CVideoDatabase::GetTagById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetItemById(), and XFILE::CVideoDatabaseDirectory::GetLabel().
GetTags()
void CVideoDatabase::GetTags (int media_id, const std::string & media_type, std::vector< std::string > & tags) protected
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, CDatabase::PrepareSQL(), and tags.
Referenced by GetDetailsForMovie(), GetDetailsForMusicVideo(), and GetDetailsForTvShow().
GetTagsNav()
bool CVideoDatabase::GetTagsNav (const std::string & strBaseDir, CFileItemList & items, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter(), bool countOnly = false)
References GetNavCommon().
Referenced by CGUIDialogMediaFilter::GetItems(), GetItems(), JSONRPC::CVideoLibrary::GetTags(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetTvShowForEpisode()
int CVideoDatabase::GetTvShowForEpisode (int idEpisode)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by UPNP::CUPnPServer::Announce(), JSONRPC::CVideoLibrary::GetEpisodeDetails(), JSONRPC::CVideoLibrary::RefreshEpisode(), and JSONRPC::CVideoLibrary::SetEpisodeDetails().
GetTvShowGenresByName()
void CVideoDatabase::GetTvShowGenresByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoNav::DoSearch().
GetTvShowId()
int CVideoDatabase::GetTvShowId (const std::string & strPath)
References URIUtils::GetParentPath(), GetPathId(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by DeleteTvShow(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), GetTvShowInfo(), HasTvShowInfo(), RemoveContentForPath(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), SetDetailsForTvShow(), and CGUIWindowVideoBase::ShowInfo().
GetTvShowInfo()
bool CVideoDatabase::GetTvShowInfo (const std::string & strPath, CVideoInfoTag & details, int idTvShow = -1, CFileItem * item = NULL, int getDetails = VideoDbDetailsAll)
References GetDetailsForTvShow(), GetTvShowId(), CVideoInfoTag::IsEmpty(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by UPNP::CUPnPServer::Build(), GetDetailsByTypeAndId(), CGUIWindowVideoNav::GetDirectory(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkSeasonHandler::GetRemoteArt(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArtTypes(), JSONRPC::CVideoLibrary::GetTVShowDetails(), CGUIDialogVideoInfo::LinkMovieToTvShow(), CGUIDialogVideoInfo::OnSearchItemFound(), JSONRPC::CVideoLibrary::RefreshTVShow(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForEpisodes(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), JSONRPC::CVideoLibrary::SetTVShowDetails(), CGUIWindowVideoBase::ShowInfo(), CGUIDialogVideoInfo::UpdateVideoItemSortTitle(), CGUIDialogVideoInfo::UpdateVideoItemTitle(), and CVideoLibraryRefreshingJob::Work().
GetTvShowNamedSeasonById()
std::string CVideoDatabase::GetTvShowNamedSeasonById (int tvshowId, int seasonId)
Get the custom named season.
Parameters
tvshowId The tv show id relative to the season.
seasonId The season id for which to search the named title.
Returns
The named title if found, otherwise empty.
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetSeasonTitle().
GetTvShowNamedSeasons()
bool CVideoDatabase::GetTvShowNamedSeasons (int showId, std::map< int, std::string > & seasons)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by ExportToXML().
GetTvShowsActorsByName()
void CVideoDatabase::GetTvShowsActorsByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoNav::DoSearch().
GetTvShowsByActor()
void CVideoDatabase::GetTvShowsByActor (const std::string & strActor, CFileItemList & items)
References GetTvShowsByWhere(), CDatabase::Filter::join, name, CDatabase::PrepareSQL(), and CDatabase::Filter::where.
Referenced by CGUIDialogVideoInfo::DoSearch().
GetTvShowsByName()
void CVideoDatabase::GetTvShowsByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CDatabase::PrepareSQL(), and VIDEODB_ID_TV_TITLE.
Referenced by CGUIWindowVideoNav::DoSearch(), and UpdateDetailsForMovie().
GetTvShowsByWhere()
bool CVideoDatabase::GetTvShowsByWhere (const std::string & strBaseDir, const Filter & filter, CFileItemList & items, const SortDescription & sortDescription = SortDescription(), int getDetails = VideoDbDetailsNone)
References CFileItemList::Add(), CDbUrl::AppendPath(), CGUIPassword::bMasterUser, DatabaseUtils::BuildLimitClause(), CDatabase::BuildSQL(), data(), FieldRow, CDatabase::Filter::fields, g_passwordManager, GetDetailsForTvShow(), CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CDatabase::GetSingleValue(), CMediaSourceSettings::GetSources(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, CGUIPassword::IsDatabasePathUnlocked(), CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, CVideoInfoTag::m_strPath, MediaTypeTvShow, CDatabase::PrepareSQL(), CFileItemList::Reserve(), RunQuery(), CGUIListItem::SetProperty(), SortDescription::sortBy, SortByNone, SortUtils::SortFromDataset(), and CDbUrl::ToString().
Referenced by DumpToDummyFiles(), GetInProgressTvShowsNav(), GetItems(), GetItemsForPath(), GetSortedVideos(), JSONRPC::CVideoLibrary::GetTVShows(), GetTvShowsByActor(), GetTvShowsNav(), and UPNP::CUPnPServer::OnSearchContainer().
GetTvShowsDirectorsByName()
void CVideoDatabase::GetTvShowsDirectorsByName (const std::string & strSearch, CFileItemList & items)
References CFileItemList::Add(), CGUIPassword::bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoNav::DoSearch().
GetTvShowSeasonArt()
bool CVideoDatabase::GetTvShowSeasonArt (int mediaId, std::map< int, std::map< std::string, std::string > > & seasonArt)
References GetArtForItem(), GetTvShowSeasons(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and MediaTypeSeason.
Referenced by ExportToXML(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForEpisodes(), and JSONRPC::CVideoLibrary::SetTVShowDetails().
GetTvShowSeasons()
bool CVideoDatabase::GetTvShowSeasons (int showId, std::map< int, int > & seasons)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by GetTvShowSeasonArt().
GetTvShowsNav()
bool CVideoDatabase::GetTvShowsNav (const std::string & strBaseDir, CFileItemList & items, int idGenre = -1, int idYear = -1, int idActor = -1, int idDirector = -1, int idStudio = -1, int idTag = -1, const SortDescription & sortDescription = SortDescription(), int getDetails = VideoDbDetailsNone)
References CDbUrl::AddOption(), CDatabase::Filter::AppendWhere(), CDbUrl::FromString(), CServiceBroker::GetSettingsComponent(), GetTvShowsByWhere(), CSettings::SETTING_VIDEOLIBRARY_SHOWEMPTYTVSHOWS, and CDbUrl::ToString().
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), CGUIDialogVideoInfo::LinkMovieToTvShow(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetTvShowTitleById()
std::string CVideoDatabase::GetTvShowTitleById (int id)
References CDatabase::GetSingleValue(), CDatabase::PrepareSQL(), and VIDEODB_ID_TV_TITLE.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows::GetLocalizedName(), and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetLocalizedName().
GetUniqueIDs()
void CVideoDatabase::GetUniqueIDs (int media_id, const std::string & media_type, CVideoInfoTag & details) protected
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, CDatabase::PrepareSQL(), and CVideoInfoTag::SetUniqueID().
Referenced by GetDetailsForEpisode(), GetDetailsForMovie(), GetDetailsForMusicVideo(), and GetDetailsForTvShow().
GetUseAllExternalAudioForVideo()
bool CVideoDatabase::GetUseAllExternalAudioForVideo (const std::string & videoPath)
References CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CUtil::ScanForExternalAudio().
GetUsedImages()
std::vector< std::string > CVideoDatabase::GetUsedImages (const std::vector< std::string > & imagesToCheck)
Check the passed in list of images if used in this database. Used to clean the image cache.
Parameters
imagesToCheck
Returns
a list of the passed in images used by this database.
References CVideoThumbLoader::GetArtTypes(), GetFileId(), CServiceBroker::GetSettingsComponent(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSeason, MediaTypeTvShow, MediaTypeVideoCollection, MediaTypeVideoVersion, CDatabase::PrepareSQL(), CSettings::SETTING_MYVIDEOS_EXTRACTCHAPTERTHUMBS, CSettings::SETTING_VIDEOLIBRARY_ACTORTHUMBS, CSettings::SETTING_VIDEOLIBRARY_ARTWORK_LEVEL, CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_ALL, CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_BASIC, and CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_NONE.
GetValueString()
std::string CVideoDatabase::GetValueString (const CVideoInfoTag & details, int min, int max, const SDbTableOffsets * offsets) const protected
References CServiceBroker::GetSettingsComponent(), max, min, SDbTableOffsets::offset, CDatabase::PrepareSQL(), value, VIDEODB_TYPE_BOOL, VIDEODB_TYPE_COUNT, VIDEODB_TYPE_DATE, VIDEODB_TYPE_DATETIME, VIDEODB_TYPE_FLOAT, VIDEODB_TYPE_INT, VIDEODB_TYPE_STRING, VIDEODB_TYPE_STRINGARRAY, and VIDEODB_TYPE_UNUSED.
Referenced by SetDetailsForEpisode(), SetDetailsForMovie(), SetDetailsForMusicVideo(), UpdateDetailsForMovie(), and UpdateDetailsForTvShow().
GetVideoItemTitle()
std::string CVideoDatabase::GetVideoItemTitle (VideoDbContentType itemType, int dbId)
References GetMovieTitle(), and MOVIES.
Referenced by CGUIWindowVideoBase::UpdateVideoVersionItemsLabel().
GetVideoSettings() [1/3]
bool CVideoDatabase::GetVideoSettings (const CFileItem & item, CVideoSettings & settings)
Get video settings for the specified file item.
Parameters
item item to get the settings for
Returns
true if video settings found, false otherwise
See also
SetVideoSettings
References GetFileId(), and GetVideoSettings().
GetVideoSettings() [2/3]
bool CVideoDatabase::GetVideoSettings (const std::string & filePath, CVideoSettings & settings)
Get video settings for the specified file path.
GetVideoSettings() obtains any saved video settings for the current file.
Parameters
filePath filepath to get the settings for
Returns
true if video settings found, false otherwise
See also
SetVideoSettings
Return values
Returns true if the settings exist, false otherwise.
References GetFileId(), and GetVideoSettings().
GetVideoSettings() [3/3]
bool CVideoDatabase::GetVideoSettings (int idFile, CVideoSettings & settings)
Get video settings for the specified file id.
Parameters
idFile file id to get the settings for
Returns
true if video settings found, false otherwise
See also
SetVideoSettings
References CLog::Log(), LOGERROR, CVideoSettings::m_AudioDelay, CVideoSettings::m_AudioStream, CVideoSettings::m_Brightness, CVideoSettings::m_CenterMixLevel, CVideoSettings::m_Contrast, CVideoSettings::m_CustomNonLinStretch, CVideoSettings::m_CustomPixelRatio, CVideoSettings::m_CustomVerticalShift, CVideoSettings::m_CustomZoomAmount, CVideoSettings::m_Gamma, CVideoSettings::m_InterlaceMethod, CVideoSettings::m_NoiseReduction, CVideoSettings::m_Orientation, CDatabase::m_pDB, CDatabase::m_pDS, CVideoSettings::m_PostProcess, CVideoSettings::m_ResumeTime, CVideoSettings::m_ScalingMethod, CVideoSettings::m_Sharpness, CVideoSettings::m_StereoInvert, CVideoSettings::m_StereoMode, CVideoSettings::m_SubtitleDelay, CVideoSettings::m_SubtitleOn, CVideoSettings::m_SubtitleStream, CVideoSettings::m_ToneMapMethod, CVideoSettings::m_ToneMapParam, CVideoSettings::m_VideoStream, CVideoSettings::m_ViewMode, CVideoSettings::m_VolumeAmplification, and CDatabase::PrepareSQL().
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), GetVideoSettings(), GetVideoSettings(), and CApplicationPlayerCallback::RequestVideoSettings().
GetVideoVersionById()
std::string CVideoDatabase::GetVideoVersionById (int id)
References CDatabase::GetSingleValue(), CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by GetItemById(), and XFILE::CVideoDatabaseDirectory::GetLabel().
GetVideoVersionInfo()
VideoAssetInfo CVideoDatabase::GetVideoVersionInfo (const std::string & filenameAndPath)
References GetFileId(), LOGERROR, VideoAssetInfo::m_idFile, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIDialogVideoManagerExtras::AddVideoExtra(), and CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker().
GetVideoVersions()
void CVideoDatabase::GetVideoVersions (VideoDbContentType itemType, int dbId, CFileItemList & items, VideoAssetType videoAssetType)
References CFileItemList::Add(), CDbUrl::AddOption(), CDbUrl::FromString(), CVideoInfoTag::GetAssetInfo(), GetDetailsByTypeAndId(), GetFileInfo(), GetPlayCount(), CFileItem::GetVideoInfoTag(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, CLog::Log(), LOGERROR, CVideoInfoTag::m_fanart, CVideoInfoTag::m_iDbId, CDatabase::m_pDB, CDatabase::m_pDS2, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPictureURL, CVideoInfoTag::m_strTitle, CVideoInfoTag::m_type, MediaTypeMovie, MediaTypeVideoVersion, MOVIES, name, CDatabase::PrepareSQL(), CVideoInfoTag::CAssetInfo::SetId(), CVideoInfoTag::CAssetInfo::SetTitle(), CVideoInfoTag::CAssetInfo::SetType(), CMediaTypes::ToPlural(), and CDbUrl::ToString().
Referenced by CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), CGUIDialogVideoManagerVersions::ChooseVideoAndConvertToVideoVersion(), CGUIDialogVideoManager::ChooseVideoAsset(), GetAssetsForVideo(), and CGUIDialogVideoManager::Refresh().
GetVideoVersionsNav()
bool CVideoDatabase::GetVideoVersionsNav (const std::string & strBaseDir, CFileItemList & items, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter())
References CFileItemList::Add(), CDbUrl::AppendPath(), CDbUrl::FromString(), id, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMovie, MediaTypeVideoVersion, MOVIES, CDatabase::PrepareSQL(), SYSTEM, USER, and VERSION.
Referenced by GetItems().
GetVideoVersionTypes()
bool CVideoDatabase::GetVideoVersionTypes (VideoDbContentType idContent, VideoAssetType asset, CFileItemList & items)
References CFileItemList::Add(), id, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMovie, MediaTypeVideoVersion, MOVIES, name, CDatabase::PrepareSQL(), SYSTEM, and USER.
Referenced by CGUIDialogVideoManager::ChooseVideoAsset().
GetWritersNav()
bool CVideoDatabase::GetWritersNav (const std::string & strBaseDir, CFileItemList & items, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter(), bool countOnly = false)
References GetPeopleNav().
Referenced by GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetYearsNav()
bool CVideoDatabase::GetYearsNav (const std::string & strBaseDir, CFileItemList & items, VideoDbContentType idContent = VideoDbContentType::UNKNOWN, const Filter & filter = Filter())
References CFileItemList::Add(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDbUrl::AppendPath(), CGUIPassword::bMasterUser, CDatabase::BuildSQL(), CFileItemList::Contains(), g_passwordManager, CMediaSourceSettings::GetInstance(), CProfile::getLockMode(), CProfileManager::GetMasterProfile(), CMediaSourceSettings::GetSources(), CGUIPassword::IsDatabasePathUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_profileManager, MOVIES, MUSICVIDEOS, CDatabase::PrepareSQL(), RunQuery(), CDateTime::SetFromDateString(), CDbUrl::ToString(), TVSHOWS, and VIDEODB_ID_TV_PREMIERED.
Referenced by GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
HasArtForItem()
bool CVideoDatabase::HasArtForItem (int mediaId, const MediaType & mediaType)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by SetDetailsForMovie().
HasContent() [1/2]
bool CVideoDatabase::HasContent ()
References HasContent(), MOVIES, MUSICVIDEOS, and TVSHOWS.
Referenced by CommitTransaction(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview::GetContent(), HasContent(), CGUIDialogVideoInfo::ManageVideoItem(), and UPNP::CUPnPServer::OnBrowseDirectChildren().
HasContent() [2/2]
bool CVideoDatabase::HasContent (VideoDbContentType type)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MOVIES, MUSICVIDEOS, and TVSHOWS.
HasEpisodeInfo()
bool CVideoDatabase::HasEpisodeInfo (const std::string & strFilenameAndPath)
References GetEpisodeId(), CLog::Log(), LOGERROR, CDatabase::m_pDB, and CDatabase::m_pDS.
Referenced by KODI::VIDEO::UTILS::HasItemVideoDbInformation().
HasMovieInfo()
bool CVideoDatabase::HasMovieInfo (const std::string & strFilenameAndPath)
References GetMovieId(), CLog::Log(), LOGERROR, CDatabase::m_pDB, and CDatabase::m_pDS.
Referenced by KODI::VIDEO::UTILS::HasItemVideoDbInformation(), and KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie().
HasMusicVideoInfo()
bool CVideoDatabase::HasMusicVideoInfo (const std::string & strFilenameAndPath)
References GetMusicVideoId(), CLog::Log(), LOGERROR, CDatabase::m_pDB, and CDatabase::m_pDS.
Referenced by KODI::VIDEO::UTILS::HasItemVideoDbInformation(), and KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo().
HasSets()
bool CVideoDatabase::HasSets () const
References CLog::Log(), LOGERROR, CDatabase::m_pDB, and CDatabase::m_pDS.
Referenced by KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview::GetContent().
HasTvShowInfo()
bool CVideoDatabase::HasTvShowInfo (const std::string & strFilenameAndPath)
References GetTvShowId(), CLog::Log(), LOGERROR, CDatabase::m_pDB, and CDatabase::m_pDS.
Referenced by KODI::VIDEO::UTILS::HasItemVideoDbInformation().
ImportArtFromXML()
bool CVideoDatabase::ImportArtFromXML (const TiXmlNode * node, std::map< std::string, std::string > & artwork)
References node.
ImportFromXML()
void CVideoDatabase::ImportFromXML (const std::string & path)
References URIUtils::AddFileToFolder(), AddPath(), AddSeason(), URIUtils::AddSlashAtEnd(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), CGUIListItem::AppendArt(), ADDON::CHOICE_YES, CGUIWindow::Close(), ADDON::content, CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_TVSHOWS, DeleteTvShow(), XFILE::CDirectory::Exists(), CServiceBroker::GetAddonMgr(), CGUIListItem::GetArt(), CVideoThumbLoader::GetArtTypes(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), XMLUtils::GetBoolean(), CServiceBroker::GetGUI(), XMLUtils::GetInt(), CVideoThumbLoader::GetLocalArt(), CFileItem::GetPath(), GetSafeFile(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), CServiceBroker::GetSettingsComponent(), XMLUtils::GetString(), CFileItem::GetVideoInfoTag(), CGUIComponent::GetWindowManager(), id, CGUIDialogProgress::IsCanceled(), LEGAL_WIN32_COMPAT, CVideoInfoTag::Load(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGERROR, LOGINFO, LookupByFolders(), CDatabase::m_pDB, CDatabase::m_pDS, CVideoInfoTag::m_set, CVideoInfoTag::m_strPath, CUtil::MakeLegalFileName(), MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSeason, MediaTypeTvShow, MediaTypeVideoCollection, CGUIDialogProgress::Open(), KODI::VIDEO::SScanSettings::parent_name, CGUIDialogProgress::Progress(), KODI::VIDEO::SScanSettings::recurse, root, CGUIListItem::SetArt(), SetArtForItem(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CFileItem::SetPath(), CGUIDialogProgress::SetPercentage(), SetScraperForPath(), CGUIDialogProgress::ShowProgressBar(), CVideoInfoTag::SetInfo::title, ADDON::TranslateContent(), and WINDOW_DIALOG_PROGRESS.
Referenced by CMediaSettings::OnSettingAction().
IncrementPlayCount()
CDateTime CVideoDatabase::IncrementPlayCount (const CFileItem & item)
Increment the playcount of an item Increments the playcount and updates the last played date.
Parameters
item CFileItem to increment the playcount for
Returns
on success, the new last played time set, invalid datetime otherwise.
See also
GetPlayCount, SetPlayCount, GetPlayCounts
References GetPlayCount(), and SetPlayCount().
Referenced by CSaveFileState::DoWork(), and CVideoLibraryMarkWatchedJob::Work().
InitializeVideoVersionTypeTable()
void CVideoDatabase::InitializeVideoVersionTypeTable (int schemaVersion)
References g_localizeStrings, CLocalizeStrings::Get(), id, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), SYSTEM, VERSION, VIDEO_VERSION_ID_BEGIN, and VIDEO_VERSION_ID_END.
Referenced by CreateTables(), and UpdateTables().
InvalidatePathHash()
void CVideoDatabase::InvalidatePathHash (const std::string & strPath) private
References CONTENT_MOVIES, CONTENT_TVSHOWS, URIUtils::GetParentPath(), GetScraperForPath(), URIUtils::IsPlugin(), KODI::VIDEO::SScanSettings::parent_name_root, and SetPathHash().
Referenced by CleanDatabase(), DeleteEpisode(), DeleteMovie(), DeleteMusicVideo(), DeleteTvShow(), and DeleteVideoAsset().
IsDefaultVideoVersion()
bool CVideoDatabase::IsDefaultVideoVersion (int idFile)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMovie, and CDatabase::PrepareSQL().
Referenced by CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), DeleteVideoAsset(), and CGUIDialogVideoManagerVersions::Remove().
IsLinkedToTvshow()
bool CVideoDatabase::IsLinkedToTvshow (int idMovie)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIDialogVideoInfo::ManageVideoItem().
LinkMovieToTvshow()
bool CVideoDatabase::LinkMovieToTvshow (int idMovie, int idShow, bool bRemove)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIDialogVideoInfo::LinkMovieToTvShow(), and UpdateDetailsForMovie().
LoadVideoInfo()
bool CVideoDatabase::LoadVideoInfo (const std::string & strFilenameAndPath, CVideoInfoTag & details, int getDetails = VideoDbDetailsAll)
References GetEpisodeInfo(), GetFileInfo(), GetMovieInfo(), and GetMusicVideoInfo().
Referenced by ANNOUNCEMENT::CAnnouncementManager::DoAnnounce(), CSaveFileState::DoWork(), JSONRPC::CVideoLibrary::FillFileItem(), UPNP::CUPnPServer::OnUpdateObject(), and CApplication::PlayFile().
LookupByFolders()
bool CVideoDatabase::LookupByFolders (const std::string & path, bool shows = false) private
Determine whether the path is using lookup using folders.
Parameters
path the path to check
shows whether this path is from a tvshow (defaults to false)
References CONTENT_TVSHOWS, GetScraperForPath(), and KODI::VIDEO::SScanSettings::parent_name_root.
Referenced by ImportFromXML().
Open()
bool CVideoDatabase::Open () override virtual
Reimplemented from CDatabase.
References CServiceBroker::GetSettingsComponent(), and CDatabase::Open().
Referenced by CGUIDialogVideoBookmarks::AddBookmark(), CGUIDialogVideoBookmarks::AddEpisodeBookmark(), CGUIDialogVideoInfo::AddItemsToTag(), CVideoFileItemListModifier::AddQueuingFolder(), CPartyModeManager::AddRandomSongs(), CGUIDialogVideoManagerVersions::AddSimilarMovieAsVersion(), CGUIDialogVideoManagerVersions::AddVideoVersion(), UPNP::CUPnPServer::Announce(), UPNP::CUPnPServer::Build(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), CGUIDialogVideoManager::ChooseVideoAsset(), KODI::VIDEO::GUILIB::CVideoVersionHelper::ChooseVideoFromAssets(), CleanLibrary(), CGUIDialogVideoBookmarks::ClearBookmarks(), CGUIDialogVideoBookmarks::Delete(), CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), CVideoThumbLoader::DetectAndAddMissingItemData(), ANNOUNCEMENT::CAnnouncementManager::DoAnnounce(), CGUIDialogVideoInfo::DoSearch(), CVideoLibraryJob::DoWork(), CSaveFileState::DoWork(), CPartyModeManager::Enable(), ExportLibrary(), ExportLibrary2(), JSONRPC::CVideoLibrary::FillFileItem(), JSONRPC::CVideoLibrary::FillFileItemList(), CVideoThumbLoader::FillLibraryArt(), anonymous_namespace{GUIDialogVideoInfo.cpp}::GetArtTypesList(), JSONRPC::CVideoLibrary::GetAvailableArt(), JSONRPC::CVideoLibrary::GetAvailableArtTypes(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetCurrentArt(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkActorHandler::GetCurrentArt(), XFILE::CSmartPlaylistDirectory::GetDirectory(), JSONRPC::CVideoLibrary::GetEpisodeDetails(), JSONRPC::CVideoLibrary::GetEpisodes(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), JSONRPC::CVideoLibrary::GetGenres(), JSONRPC::CVideoLibrary::GetInProgressTVShows(), JSONRPC::CPlayerOperations::GetItem(), CGUIDialogMediaFilter::GetItems(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CGUIDialogVideoInfo::GetItemsForTag(), XFILE::CVideoDatabaseDirectory::GetLabel(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetLocalizedName(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows::GetLocalizedName(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetLocalizedName(), CGUIDialogMediaFilter::GetMinMax(), JSONRPC::CVideoLibrary::GetMovieDetails(), JSONRPC::CVideoLibrary::GetMovies(), JSONRPC::CVideoLibrary::GetMovieSetDetails(), JSONRPC::CVideoLibrary::GetMovieSets(), CGUIDialogVideoInfo::GetMoviesForSet(), JSONRPC::CVideoLibrary::GetMusicVideoDetails(), JSONRPC::CVideoLibrary::GetMusicVideos(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), JSONRPC::CVideoLibrary::GetRecentlyAddedEpisodes(), JSONRPC::CVideoLibrary::GetRecentlyAddedMovies(), JSONRPC::CVideoLibrary::GetRecentlyAddedMusicVideos(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkSeasonHandler::GetRemoteArt(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::GetRemoteArt(), JSONRPC::CVideoLibrary::GetSeasonDetails(), JSONRPC::CVideoLibrary::GetSeasons(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetSeasonTitle(), CGUIDialogVideoInfo::GetSetForMovie(), KODI::VIDEO::UTILS::GetStackPartResumeInformation(), JSONRPC::CVideoLibrary::GetTags(), JSONRPC::CVideoLibrary::GetTVShowDetails(), JSONRPC::CVideoLibrary::GetTVShows(), XFILE::CVideoDatabaseFile::GetVideoTag(), KODI::VIDEO::UTILS::HasItemVideoDbInformation(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), ADDON::CScraper::IsInUse(), CFileItem::LoadDetails(), CVideoThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), CDatabaseManager::LocalizationChanged(), CGUIDialogVideoInfo::ManageVideoItem(), CApplication::OnAction(), CGUIDialogVideoBookmarks::OnAddEpisodeBookmark(), CGUIWindowVideoBase::OnAssignContent(), CGUIDialogSmartPlaylistRule::OnBrowse(), UPNP::CUPnPServer::OnBrowseDirectChildren(), CGUIWindowVideoNav::OnClick(), CGUIWindowMusicNav::OnContextButton(), CGUIDialogVideoManager::OnInitWindow(), CGUIWindowVideoBase::OnItemInfo(), CVideoThumbLoader::OnLoaderStart(), CGUIDialogVideoInfo::OnMessage(), CGUIWindowVideoBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnPrepareFileItems(), CGUIDialogVideoBookmarks::OnRefreshList(), UPNP::CUPnPServer::OnSearchContainer(), CGUIDialogVideoInfo::OnSearchItemFound(), CMediaSettings::OnSettingAction(), CGUIWindowVideoBase::OnUnAssignContent(), UPNP::CUPnPServer::OnUpdateObject(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::PersistArt(), CApplication::PlayFile(), KODI::VIDEO::CVideoInfoScanner::Process(), CGUIDialogVideoManagerVersions::ProcessVideoVersion(), CGUIDialogVideoManager::Refresh(), JSONRPC::CVideoLibrary::RefreshEpisode(), JSONRPC::CVideoLibrary::RefreshMovie(), JSONRPC::CVideoLibrary::RefreshMusicVideo(), JSONRPC::CVideoLibrary::RefreshTVShow(), CGUIDialogVideoInfo::RemoveItemsFromTag(), JSONRPC::CVideoLibrary::RemoveVideo(), CApplicationPlayerCallback::RequestVideoSettings(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), CGUIDialogAudioSettings::Save(), CGUIDialogSubtitleSettings::Save(), CGUIDialogVideoSettings::Save(), CUtil::ScanForExternalAudio(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), JSONRPC::CFileOperations::SetFileDetails(), CGUIDialogVideoInfo::SetMovie(), JSONRPC::CVideoLibrary::SetMovieDetails(), CGUIDialogVideoInfo::SetMovieSet(), JSONRPC::CVideoLibrary::SetMovieSetDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), JSONRPC::CVideoLibrary::SetSeasonDetails(), CTVOSTopShelf::SetTopShelfItems(), JSONRPC::CVideoLibrary::SetTVShowDetails(), CGUIWindowVideoBase::ShowInfo(), KODI::VIDEO::CVideoInfoScanner::Start(), CApplicationPlayerCallback::StoreVideoSettings(), XFILE::CVideoDatabaseFile::TranslatePath(), CGUIDialogVideoBookmarks::Update(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::UpdateEmbeddedArt(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::UpdateRemoteArt(), CRecentlyAddedJob::UpdateTotal(), CRecentlyAddedJob::UpdateVideo(), CGUIDialogVideoInfo::UpdateVideoItemSortTitle(), and CGUIDialogVideoInfo::UpdateVideoItemTitle().
RemoveArtForItem() [1/2]
bool CVideoDatabase::RemoveArtForItem (int mediaId, const MediaType & mediaType, const std::set< std::string > & artTypes)
References RemoveArtForItem().
RemoveArtForItem() [2/2]
bool CVideoDatabase::RemoveArtForItem (int mediaId, const MediaType & mediaType, const std::string & artType)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by RemoveArtForItem(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), JSONRPC::CVideoLibrary::SetMovieDetails(), JSONRPC::CVideoLibrary::SetMovieSetDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), JSONRPC::CVideoLibrary::SetSeasonDetails(), and JSONRPC::CVideoLibrary::SetTVShowDetails().
RemoveContentForPath()
void CVideoDatabase::RemoveContentForPath (const std::string & strPath, CGUIDialogProgress * progress = NULL)
References CGUIWindow::Close(), ConstructPath(), DeleteMovie(), DeleteMusicVideo(), DeleteTvShow(), GetMovieId(), GetMusicVideoId(), XFILE::CMultiPathDirectory::GetPaths(), GetSubPaths(), GetTvShowId(), URIUtils::IsMultiPath(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, CGUIDialogProgress::Open(), CDatabase::PrepareSQL(), CGUIDialogProgress::Progress(), RemoveContentForPath(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CGUIDialogProgress::SetPercentage(), and CGUIDialogProgress::ShowProgressBar().
Referenced by CGUIWindowVideoBase::OnUnAssignContent(), and RemoveContentForPath().
RemoveFromLinkTable()
void CVideoDatabase::RemoveFromLinkTable (int mediaId, const std::string & mediaType, const std::string & table, int valueId, const char * foreignKey = NULL) protected
References CDatabase::ExecuteQuery(), CDatabase::PrepareSQL(), and table.
Referenced by RemoveTagFromItem().
RemoveTagFromItem()
void CVideoDatabase::RemoveTagFromItem (int idItem, int idTag, const std::string & type)
References RemoveFromLinkTable().
Referenced by CGUIDialogVideoInfo::RemoveItemsFromTag().
RemoveTagsFromItem()
void CVideoDatabase::RemoveTagsFromItem (int idItem, const std::string & type)
References CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by JSONRPC::CVideoLibrary::SetMusicVideoDetails(), and JSONRPC::CVideoLibrary::SetTVShowDetails().
RunQuery()
int CVideoDatabase::RunQuery (const std::string & sql) private
Run a query on the main dataset and return the number of rows If no rows are found we close the dataset and return 0.
Parameters
sql the sql query to run
Returns
the number of rows, -1 for an error.
References end(), CLog::Log(), LOGDATABASE, LOGDEBUG, and CDatabase::m_pDS.
Referenced by GetArtTypes(), GetEpisodesByWhere(), GetMoviesByWhere(), GetMusicVideoAlbumsNav(), GetMusicVideosByWhere(), GetNavCommon(), GetPlayCounts(), GetSeasonsByWhere(), GetTvShowsByWhere(), and GetYearsNav().
ScraperInUse()
bool CVideoDatabase::ScraperInUse (const std::string & scraperID) const
Check whether a given scraper is in use.
Parameters
scraperID the scraper to check for.
Returns
true if the scraper is in use, false otherwise.
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by ADDON::CScraper::IsInUse().
SetArtForItem() [1/2]
void CVideoDatabase::SetArtForItem (int mediaId, const MediaType & mediaType, const std::map< std::string, std::string > & art)
References SetArtForItem().
SetArtForItem() [2/2]
void CVideoDatabase::SetArtForItem (int mediaId, const MediaType & mediaType, const std::string & artType, const std::string & url)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddActor(), CGUIDialogVideoInfo::GetSetForMovie(), ImportFromXML(), CVideoThumbLoader::LoadItemLookup(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::PersistArt(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForEpisodes(), SetArtForItem(), SetDetailsForEpisode(), SetDetailsForMovie(), SetDetailsForMovieSet(), SetDetailsForMusicVideo(), SetDetailsForSeason(), SetVideoVersionDefaultArt(), UpdateDetailsForMovie(), and UpdateDetailsForTvShow().
SetDefaultVideoVersion()
void CVideoDatabase::SetDefaultVideoVersion (VideoDbContentType itemType, int dbId, int idFile)
References GetFileBasePathById(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MOVIES, CDatabase::PrepareSQL(), and VIDEODB_ID_BASEPATH.
Referenced by CGUIDialogVideoManagerVersions::SetDefaultVideoVersion().
SetDetailsForEpisode()
int CVideoDatabase::SetDetailsForEpisode (CVideoInfoTag & details, const std::map< std::string, std::string > & artwork, int idShow, int idEpisode = -1)
References AddActorLinksToItem(), AddCast(), AddNewEpisode(), AddRatings(), AddSeason(), AddUniqueIDs(), CDatabase::BeginTransaction(), CommitTransaction(), DbEpisodeOffsets, DeleteEpisode(), GetAndFillFileId(), CDateTime::GetAsDBDateTime(), CVideoInfoTag::GetDefaultRating(), GetEpisodeId(), CVideoInfoTag::GetPath(), GetValueString(), CVideoInfoTag::HasStreamDetails(), CDateTime::IsValid(), CLog::Log(), LOGERROR, CVideoInfoTag::m_cast, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_director, CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iIdRating, CVideoInfoTag::m_iIdUniqueID, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_iUserRating, CDatabase::m_pDS, CVideoInfoTag::m_ratings, CVideoInfoTag::m_streamDetails, CVideoInfoTag::m_writingCredits, MediaTypeEpisode, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), SetArtForItem(), CDateTime::SetFromDBDateTime(), SetStreamDetailsForFileId(), UpdateFileDateAdded(), VIDEODB_ID_EPISODE_EPISODE, VIDEODB_ID_EPISODE_MAX, VIDEODB_ID_EPISODE_MIN, and VIDEODB_ID_EPISODE_SEASON.
Referenced by SetDetailsForItem(), and JSONRPC::CVideoLibrary::SetEpisodeDetails().
SetDetailsForItem() [1/2]
int CVideoDatabase::SetDetailsForItem (CVideoInfoTag & details, const std::map< std::string, std::string > & artwork)
References CVideoInfoTag::m_iDbId, CVideoInfoTag::m_type, and SetDetailsForItem().
Referenced by CVideoThumbLoader::LoadItemLookup(), and SetDetailsForItem().
SetDetailsForItem() [2/2]
int CVideoDatabase::SetDetailsForItem (int id, const MediaType & mediaType, CVideoInfoTag & details, const std::map< std::string, std::string > & artwork)
References id, CVideoInfoTag::m_iIdShow, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeNone, MediaTypeSeason, MediaTypeTvShow, MediaTypeVideoCollection, SetDetailsForEpisode(), SetDetailsForMovie(), SetDetailsForMovieSet(), SetDetailsForMusicVideo(), SetDetailsForSeason(), and UpdateDetailsForTvShow().
SetDetailsForMovie()
int CVideoDatabase::SetDetailsForMovie (CVideoInfoTag & details, const std::map< std::string, std::string > & artwork, int idMovie = -1)
References AddActorLinksToItem(), AddCast(), AddLinksToItem(), AddNewMovie(), AddRatings(), AddSet(), AddUniqueIDs(), CDatabase::BeginTransaction(), CommitTransaction(), DbMovieOffsets, GetAndFillFileId(), CDateTime::GetAsDBDate(), CDateTime::GetAsDBDateTime(), CVideoInfoTag::GetDefaultRating(), GetMovieId(), CVideoInfoTag::GetPath(), CVideoInfoTag::GetPremiered(), CVideoInfoTag::GetUniqueID(), CVideoInfoTag::GetUpdateSetOverview(), GetValueString(), CVideoInfoTag::GetYear(), HasArtForItem(), CVideoInfoTag::HasPremiered(), CVideoInfoTag::HasStreamDetails(), CVideoInfoTag::HasUniqueID(), CVideoInfoTag::HasYear(), CDateTime::IsValid(), CLog::Log(), LOGERROR, CVideoInfoTag::m_cast, CVideoInfoTag::m_country, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_director, CVideoInfoTag::m_genre, CVideoInfoTag::m_iIdRating, CVideoInfoTag::m_iIdUniqueID, CVideoInfoTag::m_iUserRating, CDatabase::m_pDS, CVideoInfoTag::m_ratings, CVideoInfoTag::m_set, CVideoInfoTag::m_streamDetails, CVideoInfoTag::m_studio, CVideoInfoTag::m_tags, CVideoInfoTag::m_writingCredits, MediaTypeMovie, MediaTypeVideoCollection, CVideoInfoTag::SetInfo::overview, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), SetArtForItem(), CDateTime::SetFromDBDateTime(), SetStreamDetailsForFileId(), CVideoInfoTag::SetInfo::title, UpdateFileDateAdded(), VIDEODB_ID_MAX, and VIDEODB_ID_MIN.
Referenced by SetDetailsForItem().
SetDetailsForMovieSet()
int CVideoDatabase::SetDetailsForMovieSet (const CVideoInfoTag & details, const std::map< std::string, std::string > & artwork, int idSet = -1)
References AddSet(), CDatabase::BeginTransaction(), CommitTransaction(), CLog::Log(), LOGERROR, CDatabase::m_pDS, CVideoInfoTag::m_strPlot, CVideoInfoTag::m_strTitle, MediaTypeVideoCollection, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), and SetArtForItem().
Referenced by SetDetailsForItem(), and JSONRPC::CVideoLibrary::SetMovieSetDetails().
SetDetailsForMusicVideo()
int CVideoDatabase::SetDetailsForMusicVideo (CVideoInfoTag & details, const std::map< std::string, std::string > & artwork, int idMVideo = -1)
References AddActorLinksToItem(), AddCast(), AddLinksToItem(), AddNewMusicVideo(), CDatabase::BeginTransaction(), CommitTransaction(), DbMusicVideoOffsets, DeleteMusicVideo(), GetAndFillFileId(), CDateTime::GetAsDBDate(), GetMusicVideoId(), CVideoInfoTag::GetPath(), CVideoInfoTag::GetPremiered(), GetValueString(), CVideoInfoTag::GetYear(), CVideoInfoTag::HasPremiered(), CVideoInfoTag::HasStreamDetails(), CDateTime::IsValid(), CLog::Log(), LOGERROR, CVideoInfoTag::m_artist, CVideoInfoTag::m_cast, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_director, CVideoInfoTag::m_genre, CVideoInfoTag::m_iIdUniqueID, CVideoInfoTag::m_iUserRating, CDatabase::m_pDS, CVideoInfoTag::m_streamDetails, CVideoInfoTag::m_studio, CVideoInfoTag::m_tags, MediaTypeMusicVideo, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), SetArtForItem(), SetStreamDetailsForFileId(), UpdateFileDateAdded(), UpdateUniqueIDs(), VIDEODB_ID_MUSICVIDEO_MAX, and VIDEODB_ID_MUSICVIDEO_MIN.
Referenced by SetDetailsForItem(), and JSONRPC::CVideoLibrary::SetMusicVideoDetails().
SetDetailsForSeason()
int CVideoDatabase::SetDetailsForSeason (const CVideoInfoTag & details, const std::map< std::string, std::string > & artwork, int idShow, int idSeason = -1)
References AddSeason(), CDatabase::BeginTransaction(), CommitTransaction(), CLog::Log(), LOGERROR, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_iUserRating, CDatabase::m_pDS, CVideoInfoTag::m_strSortTitle, MediaTypeSeason, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), and SetArtForItem().
Referenced by SetDetailsForItem(), JSONRPC::CVideoLibrary::SetSeasonDetails(), UpdateDetailsForTvShow(), and CGUIDialogVideoInfo::UpdateVideoItemTitle().
SetDetailsForTvShow()
int CVideoDatabase::SetDetailsForTvShow (const std::vector< std::pair< std::string, std::string > > & paths, CVideoInfoTag & details, const std::map< std::string, std::string > & artwork, const std::map< int, std::map< std::string, std::string > > & seasonArt, int idTvShow = -1)
add a tvshow to the library, setting metadata detail First checks for whether this TV Show is already in the database (based on idTvShow, or via GetMatchingTvShow) and if present adds the paths to the show. If not present, we add a new show and set the show metadata.
Parameters
paths a vector<string,string> list of the path(s) and parent path(s) for the show.
details a CVideoInfoTag filled with the metadata for the show.
artwork the artwork map for the show.
seasonArt the artwork map for seasons.
idTvShow the database id of the tvshow if known (defaults to -1)
Returns
the id of the tvshow.
References AddPathToTvShow(), AddTvShow(), GetMatchingTvShow(), GetTvShowId(), CVideoInfoTag::m_dateAdded, and UpdateDetailsForTvShow().
SetFileForEpisode()
bool CVideoDatabase::SetFileForEpisode (const std::string & fileAndPath, int idEpisode, int idFile)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CSaveFileState::DoWork().
SetFileForMovie()
bool CVideoDatabase::SetFileForMovie (const std::string & fileAndPath, int idMovie, int idFile)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CSaveFileState::DoWork().
SetMovieSet()
void CVideoDatabase::SetMovieSet (int idMovie, int idSet)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by ClearMovieSet(), and CGUIDialogVideoInfo::SetMovieSet().
SetPathHash()
bool CVideoDatabase::SetPathHash (const std::string & path, const std::string & hash)
References AddPath(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by KODI::VIDEO::CVideoInfoScanner::DoScan(), InvalidatePathHash(), CGUIDialogVideoInfo::OnMessage(), and KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow().
SetPlayCount()
CDateTime CVideoDatabase::SetPlayCount (const CFileItem & item, int count, const CDateTime & date = CDateTime())
Set the playcount of an item, update last played time Sets the playcount and last played date to a given value.
Parameters
item CFileItem to set the playcount for
count The playcount to set.
date The date the file was last viewed (does not denote the video was watched to completion). If empty we use current datetime (if count > 0) or never viewed (if count = 0).
Returns
on success, the new last played time set, invalid datetime otherwise.
See also
GetPlayCount, IncrementPlayCount, UpdateLastPlayed
References AddFile(), CVariant::asString(), data(), CServiceBroker::GetAnnouncementManager(), CDateTime::GetCurrentDateTime(), CFileItem::GetDynPath(), CVideoLibraryQueue::GetInstance(), CVideoInfoTag::GetPlayCount(), CGUIListItem::GetProperty(), CFileItem::GetVideoInfoTag(), CGUIListItem::HasProperty(), CFileItem::HasVideoInfoTag(), KODI::VIDEO::IsBlurayPlaylist(), URIUtils::IsPlugin(), CDateTime::IsValid(), CLog::Log(), LOGERROR, CVideoInfoTag::m_iDbId, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), CFileItem::SetPath(), and ANNOUNCEMENT::VideoLibrary.
Referenced by IncrementPlayCount(), UPNP::CUPnPServer::OnUpdateObject(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), JSONRPC::CFileOperations::SetFileDetails(), JSONRPC::CVideoLibrary::SetMovieDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), UpdateLastPlayed(), and CVideoLibraryMarkWatchedJob::Work().
SetScraperForPath()
void CVideoDatabase::SetScraperForPath (const std::string & filePath, const ADDON::ScraperPtr & info, const KODI::VIDEO::SScanSettings & settings)
References AddPath(), ADDON::content, KODI::VIDEO::SScanSettings::exclude, XFILE::CMultiPathDirectory::GetPaths(), URIUtils::IsMultiPath(), CLog::Log(), LOGERROR, KODI::VIDEO::SScanSettings::m_allExtAudio, CDatabase::m_pDB, CDatabase::m_pDS, KODI::VIDEO::SScanSettings::noupdate, KODI::VIDEO::SScanSettings::parent_name, CDatabase::PrepareSQL(), KODI::VIDEO::SScanSettings::recurse, SetScraperForPath(), and ADDON::TranslateContent().
Referenced by ImportFromXML(), CGUIWindowVideoBase::OnAssignContent(), CGUIWindowVideoBase::OnUnAssignContent(), and SetScraperForPath().
SetSingleValue() [1/3]
bool CVideoDatabase::SetSingleValue (const std::string & table, const std::string & fieldName, const std::string & strValue, const std::string & conditionName = "", int conditionValue = -1)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and table.
SetSingleValue() [2/3]
bool CVideoDatabase::SetSingleValue (VideoDbContentType type, int dbId, Field dbField, const std::string & strValue)
References DatabaseUtils::GetField(), DatabaseUtils::MediaTypeFromVideoContentType(), MediaTypeNone, and SetSingleValue().
SetSingleValue() [3/3]
bool CVideoDatabase::SetSingleValue (VideoDbContentType type, int dbId, int dbField, const std::string & strValue)
References EPISODES, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MOVIES, MUSICVIDEOS, SetSingleValue(), and TVSHOWS.
Referenced by CGUIDialogVideoInfo::SetMovie(), SetSingleValue(), SetSingleValue(), UpdateMovieTitle(), and UpdateVideoSortTitle().
SetStackTimes()
void CVideoDatabase::SetStackTimes (const std::string & filePath, const std::vector< uint64_t > & times)
Sets the stack times for a particular video file.
References AddFile(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CApplicationStackHelper::InitializeStackStartPartAndOffset().
SetStreamDetailsForFile()
int CVideoDatabase::SetStreamDetailsForFile (const CStreamDetails & details, const std::string & strFileNameAndPath)
Todo:
ugly error return mechanism, fixme
References AddFile(), and SetStreamDetailsForFileId().
Referenced by CSaveFileState::DoWork(), and CVideoThumbLoader::LoadItemLookup().
SetStreamDetailsForFileId()
bool CVideoDatabase::SetStreamDetailsForFileId (const CStreamDetails & details, int idFile)
Clear any existing stream details and add the new provided details to a file.
Parameters
[in] details New stream details
[in] idFile Identifier of the file
Returns
operation success. true for success, false for failure
References CStreamDetail::AUDIO, CStreamDetails::GetAudioChannels(), CStreamDetails::GetAudioCodec(), CStreamDetails::GetAudioLanguage(), CStreamDetails::GetAudioStreamCount(), CStreamDetails::GetStereoMode(), CStreamDetails::GetSubtitleLanguage(), CStreamDetails::GetSubtitleStreamCount(), CStreamDetails::GetVideoAspect(), CStreamDetails::GetVideoCodec(), CStreamDetails::GetVideoDuration(), CStreamDetails::GetVideoHdrType(), CStreamDetails::GetVideoHeight(), CStreamDetails::GetVideoLanguage(), CStreamDetails::GetVideoStreamCount(), CStreamDetails::GetVideoWidth(), CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), CStreamDetail::SUBTITLE, CStreamDetail::VIDEO, VIDEODB_ID_EPISODE_RUNTIME, VIDEODB_ID_MUSICVIDEO_RUNTIME, and VIDEODB_ID_RUNTIME.
Referenced by AddVideoAsset(), CVideoThumbLoader::LoadItemLookup(), SetDetailsForEpisode(), SetDetailsForMovie(), SetDetailsForMusicVideo(), and SetStreamDetailsForFile().
SetVideoSettings() [1/2]
void CVideoDatabase::SetVideoSettings (const CFileItem & item, const CVideoSettings & settings)
Set video settings for the specified file path.
Parameters
fileItem to set the settings for
See also
GetVideoSettings
References AddFile(), and SetVideoSettings().
Referenced by SetVideoSettings(), and CApplicationPlayerCallback::StoreVideoSettings().
SetVideoSettings() [2/2]
void CVideoDatabase::SetVideoSettings (int idFile, const CVideoSettings & settings)
Set video settings for the specified file path.
Sets the settings for a particular video file.
Parameters
fileId to set the settings for
See also
GetVideoSettings
References CLog::Log(), LOGERROR, CVideoSettings::m_AudioDelay, CVideoSettings::m_AudioStream, CVideoSettings::m_Brightness, CVideoSettings::m_CenterMixLevel, CVideoSettings::m_Contrast, CVideoSettings::m_CustomNonLinStretch, CVideoSettings::m_CustomPixelRatio, CVideoSettings::m_CustomVerticalShift, CVideoSettings::m_CustomZoomAmount, CVideoSettings::m_Gamma, CVideoSettings::m_InterlaceMethod, CVideoSettings::m_NoiseReduction, CVideoSettings::m_Orientation, CDatabase::m_pDB, CDatabase::m_pDS, CVideoSettings::m_PostProcess, CVideoSettings::m_ResumeTime, CVideoSettings::m_ScalingMethod, CVideoSettings::m_Sharpness, CVideoSettings::m_StereoInvert, CVideoSettings::m_StereoMode, CVideoSettings::m_SubtitleDelay, CVideoSettings::m_SubtitleOn, CVideoSettings::m_SubtitleStream, CVideoSettings::m_ToneMapMethod, CVideoSettings::m_ToneMapParam, CVideoSettings::m_VideoStream, CVideoSettings::m_ViewMode, CVideoSettings::m_VolumeAmplification, and CDatabase::PrepareSQL().
SetVideoUserRating()
bool CVideoDatabase::SetVideoUserRating (int dbId, int rating, const MediaType & mediaType)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeNone, MediaTypeSeason, MediaTypeTvShow, and CDatabase::PrepareSQL().
Referenced by CApplication::OnAction(), and CGUIDialogVideoInfo::OnMessage().
SetVideoVersion()
void CVideoDatabase::SetVideoVersion (int idFile, int idVideoVersion)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIDialogVideoManager::Rename().
SetVideoVersionDefaultArt()
void CVideoDatabase::SetVideoVersionDefaultArt (int dbId, int idFrom, VideoDbContentType type)
References GetArtForItem(), MediaTypeVideoVersion, SetArtForItem(), and VideoContentTypeToString().
Referenced by AddVideoAsset(), and ConvertVideoToVersion().
SplitPath()
void CVideoDatabase::SplitPath (const std::string & strFileNameAndPath, std::string & strPath, std::string & strFileName) private
References CURL::GetOptions(), URIUtils::GetParentPath(), CURL::GetProtocolOptions(), CURL::GetWithoutFilename(), CURL::GetWithoutOptions(), URIUtils::IsPlugin(), URIUtils::IsStack(), URIUtils::IsURL(), and URIUtils::Split().
UpdateActorLinksToItem()
void CVideoDatabase::UpdateActorLinksToItem (int mediaId, const std::string & mediaType, const std::string & field, const std::vector< std::string > & values) protected
References AddActorLinksToItem(), CDatabase::m_pDS, CDatabase::PrepareSQL(), and values.
Referenced by UpdateDetailsForMovie().
UpdateArtForItem()
void CVideoDatabase::UpdateArtForItem (int mediaId, const MediaType & mediaType)
References AnnounceUpdate().
Referenced by KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::PersistArt().
UpdateAssetsOwner()
bool CVideoDatabase::UpdateAssetsOwner (const std::string & mediaType, int dbIdSource, int dbIdTarget)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by ConvertVideoToVersion(), and CVideoLibraryRefreshingJob::Work().
UpdateDetailsForMovie()
int CVideoDatabase::UpdateDetailsForMovie (int idMovie, CVideoInfoTag & details, const std::map< std::string, std::string > & artwork, const std::set< std::string > & updatedDetails)
References AddSet(), CDatabase::BeginTransaction(), CommitTransaction(), DbMovieOffsets, CDateTime::GetAsDBDate(), CVideoInfoTag::GetDefaultRating(), GetLinksToTvShow(), CVideoInfoTag::GetPremiered(), GetTvShowsByName(), GetValueString(), CVideoInfoTag::GetYear(), CVideoInfoTag::HasPremiered(), CFileItemList::IsEmpty(), CDateTime::IsValid(), LinkMovieToTvshow(), CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, CVideoInfoTag::m_country, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_director, CVideoInfoTag::m_genre, CVideoInfoTag::m_iIdRating, CVideoInfoTag::m_iIdUniqueID, CVideoInfoTag::m_iUserRating, CDatabase::m_pDS, CVideoInfoTag::m_ratings, CVideoInfoTag::m_set, CVideoInfoTag::m_showLink, CVideoInfoTag::m_strTitle, CVideoInfoTag::m_studio, CVideoInfoTag::m_tags, CVideoInfoTag::m_writingCredits, MediaTypeMovie, CVideoInfoTag::SetInfo::overview, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), SetArtForItem(), CVideoInfoTag::SetInfo::title, UpdateActorLinksToItem(), UpdateFileDateAdded(), UpdateLinksToItem(), UpdateRatings(), UpdateUniqueIDs(), VIDEODB_ID_MAX, and VIDEODB_ID_MIN.
Referenced by JSONRPC::CVideoLibrary::SetMovieDetails().
UpdateDetailsForTvShow()
bool CVideoDatabase::UpdateDetailsForTvShow (int idTvShow, CVideoInfoTag & details, const std::map< std::string, std::string > & artwork, const std::map< int, std::map< std::string, std::string > > & seasonArt)
References AddActorLinksToItem(), AddCast(), AddLinksToItem(), AddRatings(), AddSeason(), AddUniqueIDs(), CDatabase::BeginTransaction(), CommitTransaction(), DbTvShowOffsets, DeleteDetailsForTvShow(), CDatabase::ExecuteQuery(), CVideoInfoTag::GetDefaultRating(), CVideoInfoTag::GetDuration(), GetSeasonInfo(), GetValueString(), CVideoInfoTag::m_cast, CVideoInfoTag::m_director, CVideoInfoTag::m_genre, CVideoInfoTag::m_iIdRating, CVideoInfoTag::m_iIdUniqueID, CVideoInfoTag::m_iUserRating, CVideoInfoTag::m_namedSeasons, CVideoInfoTag::m_ratings, CVideoInfoTag::m_strSortTitle, CVideoInfoTag::m_studio, CVideoInfoTag::m_tags, MediaTypeSeason, MediaTypeTvShow, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), SetArtForItem(), SetDetailsForSeason(), CVideoInfoTag::SetSortTitle(), VIDEODB_ID_TV_MAX, and VIDEODB_ID_TV_MIN.
Referenced by SetDetailsForItem(), SetDetailsForTvShow(), and JSONRPC::CVideoLibrary::SetTVShowDetails().
UpdateFanart()
void CVideoDatabase::UpdateFanart (const CFileItem & item, VideoDbContentType type)
References AnnounceUpdate(), CFileItem::GetPath(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CLog::Log(), LOGERROR, CVideoInfoTag::m_fanart, CVideoInfoTag::m_iDbId, CDatabase::m_pDB, CDatabase::m_pDS, CFanart::m_xml, MediaTypeMovie, MediaTypeTvShow, MOVIES, CDatabase::PrepareSQL(), TVSHOWS, VIDEODB_ID_FANART, and VIDEODB_ID_TV_FANART.
Referenced by KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::UpdateEmbeddedArt(), and KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::UpdateRemoteArt().
UpdateFileDateAdded()
void CVideoDatabase::UpdateFileDateAdded (CVideoInfoTag & details)
Updates the dateAdded field in the files table for the file with the given idFile and the given path based on the files modification date.
Parameters
details details of the video file
References GetAndFillFileId(), CDateTime::GetAsDBDateTime(), GetDateAdded(), CVideoInfoTag::GetPath(), CLog::Log(), LOGERROR, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_iFileId, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by SetDetailsForEpisode(), SetDetailsForMovie(), SetDetailsForMusicVideo(), and UpdateDetailsForMovie().
UpdateLastPlayed()
CDateTime CVideoDatabase::UpdateLastPlayed (const CFileItem & item)
Update the last played time of an item Updates the last played date.
Parameters
item CFileItem to update the last played time for
Returns
on success, the last played time set, invalid datetime otherwise.
See also
GetPlayCount, SetPlayCount, IncrementPlayCount, GetPlayCounts
References CDateTime::GetCurrentDateTime(), GetPlayCount(), and SetPlayCount().
Referenced by CSaveFileState::DoWork().
UpdateLinksToItem()
void CVideoDatabase::UpdateLinksToItem (int mediaId, const std::string & mediaType, const std::string & field, const std::vector< std::string > & values) protected
References AddLinksToItem(), CDatabase::m_pDS, CDatabase::PrepareSQL(), and values.
Referenced by UpdateDetailsForMovie().
UpdateMovieTitle()
void CVideoDatabase::UpdateMovieTitle (int idMovie, const std::string & strNewMovieTitle, VideoDbContentType iType = VideoDbContentType::MOVIES)
References AnnounceUpdate(), ADDON::content, EPISODES, FieldTitle, CLog::Log(), LOGERROR, LOGINFO, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MOVIE_SETS, MOVIES, MUSICVIDEOS, CDatabase::PrepareSQL(), SetSingleValue(), and TVSHOWS.
Referenced by CGUIDialogVideoInfo::UpdateVideoItemTitle().
UpdateRatings()
int CVideoDatabase::UpdateRatings (int mediaId, const char * mediaType, const RatingMap & values, const std::string & defaultRating) protected
References AddRatings(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and values.
Referenced by UpdateDetailsForMovie().
UpdateTables()
void CVideoDatabase::UpdateTables (int version) override private virtual
Reimplemented from CDatabase.
References AddPath(), exists(), EXTRA, URIUtils::GetParentPath(), XFILE::CMultiPathDirectory::GetPaths(), CDatabase::GetSingleValue(), id, CShowItem::id, CShowItem::ident, InitializeVideoVersionTypeTable(), CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, CShowItem::path, CShowLink::path, CShowLink::pathId, CDatabase::PrepareSQL(), CShowLink::show, table, CShowItem::title, USER, VERSION, VIDEO_VERSION_ID_DEFAULT, VIDEO_VERSION_ID_END, VIDEODB_ID_EPISODE_IDENT_ID, VIDEODB_ID_EPISODE_RATING_ID, VIDEODB_ID_EPISODE_RUNTIME, VIDEODB_ID_EPISODE_SEASON, VIDEODB_ID_EPISODE_VOTES, VIDEODB_ID_IDENT_ID, VIDEODB_ID_MUSICVIDEO_YEAR, VIDEODB_ID_RATING_ID, VIDEODB_ID_TV_IDENT_ID, VIDEODB_ID_TV_PREMIERED, VIDEODB_ID_TV_RATING_ID, VIDEODB_ID_TV_TITLE, VIDEODB_ID_TV_VOTES, VIDEODB_ID_VOTES, VIDEODB_ID_YEAR, VIDEODB_MAX_COLUMNS, and CShowItem::year.
UpdateUniqueIDs()
int CVideoDatabase::UpdateUniqueIDs (int mediaId, const char * mediaType, const CVideoInfoTag & details) protected
References AddUniqueIDs(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by SetDetailsForMusicVideo(), and UpdateDetailsForMovie().
UpdateVideoSortTitle()
bool CVideoDatabase::UpdateVideoSortTitle (int idDb, const std::string & strNewSortTitle, VideoDbContentType iType = VideoDbContentType::MOVIES)
References AnnounceUpdate(), ADDON::content, FieldSortTitle, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeMovie, MediaTypeTvShow, MOVIES, SetSingleValue(), and TVSHOWS.
Referenced by CGUIDialogVideoInfo::UpdateVideoItemSortTitle().
UpdateVideoVersionTypeTable()
void CVideoDatabase::UpdateVideoVersionTypeTable ()
References CDatabase::BeginTransaction(), CommitTransaction(), g_localizeStrings, CLocalizeStrings::Get(), id, CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), SYSTEM, VIDEO_VERSION_ID_BEGIN, and VIDEO_VERSION_ID_END.
Referenced by CDatabaseManager::LocalizationChanged().
VideoContentTypeToString()
static void CVideoDatabase::VideoContentTypeToString (VideoDbContentType type, std::string & out) inline static
References EPISODES, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MOVIES, MUSICVIDEOS, and TVSHOWS.
Referenced by ConvertVideoToVersion(), ANNOUNCEMENT::CAnnouncementManager::DoAnnounce(), and SetVideoVersionDefaultArt().
The documentation for this class was generated from the following files:
VideoDatabase.h
VideoDatabase.cpp