Kodi Documentation: PVR::CGUIDialogPVRTimerSettings Class Reference
PVR::CGUIDialogPVRTimerSettings Class Reference
#include <GUIDialogPVRTimerSettings.h>
Classes
struct ChannelDescriptor
Public Member Functions
CGUIDialogPVRTimerSettings ()
~CGUIDialogPVRTimerSettings () override
bool CanBeActivated () const override
void SetTimer (const std::shared_ptr< CPVRTimerInfoTag > &timer)
void AddMultiIntSetting (const std::shared_ptr< CSettingGroup > &group, const std::string &settingName, int settingValue) override
void AddSingleIntSetting (const std::shared_ptr< CSettingGroup > &group, const std::string &settingName, int settingValue, int minValue, int step, int maxValue) override
void AddMultiStringSetting (const std::shared_ptr< CSettingGroup > &group, const std::string &settingName, const std::string &settingValue) override
void AddSingleStringSetting (const std::shared_ptr< CSettingGroup > &group, const std::string &settingName, const std::string &settingValue, bool allowEmptyValue) override
Public Member Functions inherited from CGUIDialogSettingsManualBase
CGUIDialogSettingsManualBase (int windowId, const std::string &xmlFile)
~CGUIDialogSettingsManualBase () override
Public Member Functions inherited from CGUIDialogSettingsManagerBase
CGUIDialogSettingsManagerBase (int windowId, const std::string &xmlFile)
~CGUIDialogSettingsManagerBase () override
Public Member Functions inherited from CGUIDialogSettingsBase
CGUIDialogSettingsBase (int windowId, const std::string &xmlFile)
~CGUIDialogSettingsBase () override
bool OnMessage (CGUIMessage &message) override
bool OnAction (const CAction &action) override
bool OnBack (int actionID) override
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
virtual bool IsConfirmed () const
std::string Localize (std::uint32_t code) const override
Public Member Functions inherited from CGUIDialog
CGUIDialog (int id, const std::string &xmlFile, DialogModalityType modalityType=DialogModalityType::MODAL)
~CGUIDialog (void) override
void Render () override
void Open (const std::string &param="")
void Open (bool bProcessRenderLoop, const std::string &param="")
bool IsDialogRunning () const override
bool IsDialog () const override
bool IsModalDialog () const override
virtual DialogModalityType GetModalityType () const
void SetAutoClose (unsigned int timeoutMs)
void ResetAutoClose (void)
void CancelAutoClose (void)
bool IsAutoClosed (void) const
void SetSound (bool OnOff)
bool IsSoundEnabled () const override
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
bool OnAction (const CAction &action) override
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool OnMessage (CGUIMessage &message) override
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsMediaWindow () const
virtual bool HasListItems () const
virtual CFileItemPtr GetCurrentListItem (int offset=0)
virtual int GetViewContainerID () const
virtual int GetViewCount () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual CGUIControl * GetFirstFocusableControl (int id)
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Public Member Functions inherited from CSettingControlCreator
std::shared_ptr< ISettingControl > CreateControl (const std::string &controlType) const override
Creates a new setting control of the given custom setting control type.
Public Member Functions inherited from ISettingControlCreator
virtual ~ISettingControlCreator ()=default
Public Member Functions inherited from ILocalizer
virtual ~ILocalizer ()=default
Public Member Functions inherited from PVR::IPVRSettingsContainer
virtual ~IPVRSettingsContainer ()=default
Protected Member Functions
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
bool AllowResettingSettings () const override
std::string GetSettingsLabel (const std::shared_ptr< ISetting > &setting) override
Get the name for the setting entry.
bool Save () override
void SetupView () override
void InitializeSettings () override
Protected Member Functions inherited from CGUIDialogSettingsManualBase
std::shared_ptr< CSettingSection > GetSection () override
void SetupView () override
CSettingsManager * GetSettingsManager () const override
std::shared_ptr< CSettingCategory > AddCategory (const std::string &id, int label, int help=-1)
std::shared_ptr< CSettingGroup > AddGroup (const std::shared_ptr< CSettingCategory > &category, int label=-1, int help=-1, bool separatorBelowLabel=true, bool hideSeparator=false)
std::shared_ptr< CSettingBool > AddToggle (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, bool value, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddEdit (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, int minimum=0, int step=1, int maximum=0, bool verifyNewValue=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingNumber > AddEdit (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float value, float minimum=0.0f, float step=1.0f, float maximum=0.0f, bool verifyNewValue=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddEdit (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool allowEmpty=false, bool hidden=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddIp (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool allowEmpty=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddPasswordMd5 (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool allowEmpty=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingAction > AddButton (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &data="", bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddInfoLabelButton (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &info, bool visible=true, int help=-1)
std::shared_ptr< CSettingAddon > AddAddon (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, ADDON::AddonType addonType, bool allowEmpty=false, int heading=-1, bool hideValue=false, bool showInstalledAddons=true, bool showInstallableAddons=false, bool showMoreAddons=true, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingPath > AddPath (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool writable=true, const std::vector< std::string > &sources=std::vector< std::string >(), bool allowEmpty=false, int heading=-1, bool hideValue=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingDate > AddDate (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool allowEmpty=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingTime > AddTime (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool allowEmpty=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, StringSettingOptionsFiller filler, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, int minimum, int step, int maximum, int formatLabel=-1, int minimumLabel=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, int minimum, int step, int maximum, const std::string &formatString, int minimumLabel=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const TranslatableIntegerSettingOptions &entries, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const IntegerSettingOptions &entries, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, IntegerSettingOptionsFiller filler, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingNumber > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float value, float minimum, float step, float maximum, int formatLabel=-1, int minimumLabel=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingNumber > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float value, float minimum, float step, float maximum, const std::string &formatString, int minimumLabel=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, StringSettingOptionsFiller filler, int heading, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingInt > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const TranslatableIntegerSettingOptions &entries, int heading, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingInt > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const IntegerSettingOptions &entries, int heading, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingInt > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, IntegerSettingOptionsFiller filler, int heading, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingList > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, std::vector< std::string > values, StringSettingOptionsFiller filler, int heading, int minimumItems=0, int maximumItems=-1, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingList > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, std::vector< int > values, const TranslatableIntegerSettingOptions &entries, int heading, int minimumItems=0, int maximumItems=-1, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingList > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, std::vector< int > values, const IntegerSettingOptions &entries, int heading, int minimumItems=0, int maximumItems=-1, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingList > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, std::vector< int > values, IntegerSettingOptionsFiller filler, int heading, int minimumItems=0, int maximumItems=-1, bool visible=true, int help=-1, SettingControlListValueFormatter formatter=nullptr, bool details=false)
std::shared_ptr< CSettingInt > AddPercentageSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, int formatLabel, int step=1, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddPercentageSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const std::string &formatString, int step=1, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, int formatLabel, int minimum, int step, int maximum, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const std::string &formatString, int minimum, int step, int maximum, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingNumber > AddSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float value, int formatLabel, float minimum, float step, float maximum, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingNumber > AddSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float value, const std::string &formatString, float minimum, float step, float maximum, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddPercentageRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int valueFormatLabel, int step=1, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddPercentageRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, const std::string &valueFormatString="{:d} %", int step=1, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, int valueFormatLabel, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, const std::string &valueFormatString="{:d}", int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float valueLower, float valueUpper, float minimum, float step, float maximum, int valueFormatLabel, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float valueLower, float valueUpper, float minimum, float step, float maximum, const std::string &valueFormatString="{:.1f}", int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddDateRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, int valueFormatLabel, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddDateRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, const std::string &valueFormatString="", int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddTimeRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, int valueFormatLabel, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddTimeRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, const std::string &valueFormatString="mm:ss", int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< ISettingControl > GetTitleControl (bool separatorBelowLabel=true, bool hideSeparator=false)
std::shared_ptr< ISettingControl > GetCheckmarkControl (bool delayed=false)
std::shared_ptr< ISettingControl > GetEditControl (const std::string &format, bool delayed=false, bool hidden=false, bool verifyNewValue=false, int heading=-1)
std::shared_ptr< ISettingControl > GetButtonControl (const std::string &format, bool delayed=false, int heading=-1, bool hideValue=false, bool showInstalledAddons=true, bool showInstallableAddons=false, bool showMoreAddons=true)
std::shared_ptr< ISettingControl > GetSpinnerControl (const std::string &format, bool delayed=false, int minimumLabel=-1, int formatLabel=-1, const std::string &formatString="")
std::shared_ptr< ISettingControl > GetListControl (const std::string &format, bool delayed=false, int heading=-1, bool multiselect=false, SettingControlListValueFormatter formatter=nullptr, bool details=false)
std::shared_ptr< ISettingControl > GetSliderControl (const std::string &format, bool delayed=false, int heading=-1, bool usePopup=false, int formatLabel=-1, const std::string &formatString="")
std::shared_ptr< ISettingControl > GetRangeControl (const std::string &format, bool delayed=false, int formatLabel=-1, int valueFormatLabel=-1, const std::string &valueFormatString="")
Protected Member Functions inherited from CGUIDialogSettingsManagerBase
std::shared_ptr< CSetting > GetSetting (const std::string &settingId) override
bool OnOkay () override
std::set< std::string > CreateSettings () override
void FreeSettingsControls () override
std::shared_ptr< ISettingControl > CreateControl (const std::string &controlType) const override
Creates a new setting control of the given custom setting control type.
Protected Member Functions inherited from CGUIDialogSettingsBase
void OnInitWindow () override
Called on window open.
void OnTimeout () override
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName) override
The given property of the given setting has changed.
virtual int GetSettingLevel () const
virtual std::chrono::milliseconds GetDelayMs () const
virtual std::string GetLocalizedString (uint32_t labelId) const
virtual void OnCancel ()
virtual void UpdateSettings ()
virtual CGUIControl * AddSetting (const std::shared_ptr< CSetting > &pSetting, float width, int &iControlID)
virtual CGUIControl * AddSettingControl (CGUIControl *pControl, BaseSettingControlPtr pSettingControl, float width, int &iControlID)
virtual void SetupControls (bool createSettings=true)
virtual void FreeControls ()
virtual void DeleteControls ()
virtual void SetHeading (const CVariant &label)
virtual void SetDescription (const CVariant &label)
virtual void OnResetSettings ()
virtual void OnClick (const BaseSettingControlPtr &pSettingControl)
A setting control has been interacted with by the user.
void UpdateSettingControl (const std::string &settingId, bool updateDisplayOnly=false)
void UpdateSettingControl (const BaseSettingControlPtr &pSettingControl, bool updateDisplayOnly=false)
void SetControlLabel (int controlId, const CVariant &label)
BaseSettingControlPtr GetSettingControl (const std::string &setting)
BaseSettingControlPtr GetSettingControl (int controlId)
CGUIControl * AddSeparator (float width, int &iControlID)
CGUIControl * AddGroupLabel (const std::shared_ptr< CSettingGroup > &group, float width, int &iControlID)
Protected Member Functions inherited from CGUIDialog
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
void SetDefaults () override
void OnWindowLoaded () override
virtual void UpdateVisibility ()
virtual void Open_Internal (bool bProcessRenderLoop, const std::string &param="")
void OnDeinitWindow (int nextWindowID) override
void ProcessRenderLoop (bool renderOnly=false)
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void OnWindowUnload ()
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
virtual void SaveControlStates ()
virtual void RestoreControlStates ()
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Member Functions inherited from CSettingControlCreator
CSettingControlCreator ()=default
~CSettingControlCreator () override=default
Protected Member Functions inherited from ILocalizer
ILocalizer ()=default
Protected Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Protected Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
Private Types
typedef std::map< int, std::shared_ptr< CPVRTimerType > > TypeEntriesMap
typedef struct PVR::CGUIDialogPVRTimerSettings::ChannelDescriptor ChannelDescriptor
typedef std::map< int, ChannelDescriptor > ChannelEntriesMap
Private Member Functions
bool Validate ()
void InitializeTypesList ()
void InitializeChannelsList ()
void SetButtonLabels ()
void AddCondition (const std::shared_ptr< CSetting > &setting, const std::string &identifier, SettingConditionCheck condition, SettingDependencyType depType, const std::string &settingId)
void AddTypeDependentEnableCondition (const std::shared_ptr< CSetting > &setting, const std::string &identifier)
void AddTypeDependentVisibilityCondition (const std::shared_ptr< CSetting > &setting, const std::string &identifier)
void AddStartAnytimeDependentVisibilityCondition (const std::shared_ptr< CSetting > &setting, const std::string &identifier)
void AddEndAnytimeDependentVisibilityCondition (const std::shared_ptr< CSetting > &setting, const std::string &identifier)
Static Private Member Functions
static int GetDateAsIndex (const CDateTime &datetime)
static void SetDateFromIndex (CDateTime &datetime, int date)
static void SetTimeFromSystemTime (CDateTime &datetime, const KODI::TIME::SystemTime &time)
static int GetWeekdaysFromSetting (const std::shared_ptr< const CSetting > &setting)
static void TypesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void ChannelsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void DaysFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void DupEpisodesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void WeekdaysFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void PrioritiesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void LifetimesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void MaxRecordingsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void RecordingGroupFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void MarginTimeFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void CustomIntSettingDefinitionsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void CustomStringSettingDefinitionsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static std::string WeekdaysValueFormatter (const std::shared_ptr< const CSetting > &setting)
static bool TypeReadOnlyCondition (const std::string &condition, const std::string &value, const std::shared_ptr< const CSetting > &setting, void *data)
static bool TypeSupportsCondition (const std::string &condition, const std::string &value, const std::shared_ptr< const CSetting > &setting, void *data)
static bool StartAnytimeSetCondition (const std::string &condition, const std::string &value, const std::shared_ptr< const CSetting > &setting, void *data)
static bool EndAnytimeSetCondition (const std::string &condition, const std::string &value, const std::shared_ptr< const CSetting > &setting, void *data)
Private Attributes
std::unique_ptr< CPVRCustomTimerSettings > m_customTimerSettings
std::shared_ptr< CPVRTimerInfoTag > m_timerInfoTag
TypeEntriesMap m_typeEntries
ChannelEntriesMap m_channelEntries
std::string m_timerStartTimeStr
std::string m_timerEndTimeStr
std::shared_ptr< CPVRTimerType > m_timerType
bool m_bIsRadio = false
bool m_bIsNewTimer = true
bool m_bTimerActive = false
std::string m_strTitle
std::string m_strEpgSearchString
bool m_bFullTextEpgSearch = true
ChannelDescriptor m_channel
CDateTime m_startLocalTime
CDateTime m_endLocalTime
bool m_bStartAnyTime = false
bool m_bEndAnyTime = false
unsigned int m_iWeekdays
CDateTime m_firstDayLocalTime
unsigned int m_iPreventDupEpisodes = 0
unsigned int m_iMarginStart = 0
unsigned int m_iMarginEnd = 0
int m_iPriority = 0
int m_iLifetime = 0
int m_iMaxRecordings = 0
std::string m_strDirectory
unsigned int m_iRecordingGroup = 0
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Protected Attributes inherited from CGUIDialogSettingsBase
std::vector< std::shared_ptr< CSettingCategory > > m_categories
std::vector< BaseSettingControlPtr > m_settingControls
int m_iSetting = 0
int m_iCategory = 0
std::shared_ptr< CSettingAction > m_resetSetting
std::shared_ptr< CSettingCategory > m_dummyCategory
CGUISpinControlEx * m_pOriginalSpin
CGUISettingsSliderControl * m_pOriginalSlider
CGUIRadioButtonControl * m_pOriginalRadioButton
CGUIColorButtonControl * m_pOriginalColorButton = nullptr
CGUIButtonControl * m_pOriginalCategoryButton
CGUIButtonControl * m_pOriginalButton
CGUIEditControl * m_pOriginalEdit
CGUIImage * m_pOriginalImage
CGUILabelControl * m_pOriginalGroupTitle
bool m_newOriginalEdit = false
BaseSettingControlPtr m_delayedSetting
Current delayed setting.
CTimer m_delayedTimer
Delayed setting timer.
bool m_confirmed = false
int m_focusedControl = 0
int m_fadedControl = 0
Protected Attributes inherited from CGUIDialog
bool m_wasRunning
true if we were running during the last DoProcess()
bool m_autoClosing
bool m_enableSound
unsigned int m_showStartTime
unsigned int m_showDuration
bool m_bAutoClosed
DialogModalityType m_modalityType
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Typedef Documentation
ChannelDescriptor
typedef struct PVR::CGUIDialogPVRTimerSettings::ChannelDescriptor PVR::CGUIDialogPVRTimerSettings::ChannelDescriptor private
ChannelEntriesMap
typedef std::map<int, ChannelDescriptor> PVR::CGUIDialogPVRTimerSettings::ChannelEntriesMap private
TypeEntriesMap
typedef std::map<int, std::shared_ptr<CPVRTimerType> > PVR::CGUIDialogPVRTimerSettings::TypeEntriesMap private
Constructor & Destructor Documentation
CGUIDialogPVRTimerSettings()
CGUIDialogPVRTimerSettings::CGUIDialogPVRTimerSettings ()
References CGUIWindow::LOAD_EVERY_TIME, and CGUIWindow::m_loadType.
~CGUIDialogPVRTimerSettings()
CGUIDialogPVRTimerSettings::~CGUIDialogPVRTimerSettings () override default
Member Function Documentation
AddCondition()
void CGUIDialogPVRTimerSettings::AddCondition (const std::shared_ptr< CSetting > & setting, const std::string & identifier, SettingConditionCheck condition, SettingDependencyType depType, const std::string & settingId) private
References CSettingsManager::AddDynamicCondition(), CSettingDependency::And(), and CGUIDialogSettingsManualBase::GetSettingsManager().
Referenced by AddEndAnytimeDependentVisibilityCondition(), AddStartAnytimeDependentVisibilityCondition(), AddTypeDependentEnableCondition(), and AddTypeDependentVisibilityCondition().
AddEndAnytimeDependentVisibilityCondition()
void CGUIDialogPVRTimerSettings::AddEndAnytimeDependentVisibilityCondition (const std::shared_ptr< CSetting > & setting, const std::string & identifier) private
References AddCondition(), END_ANYTIME_DEP_VISIBI_COND_ID_POSTFIX, EndAnytimeSetCondition(), id, SETTING_TMR_END_ANYTIME, and Visible.
Referenced by InitializeSettings().
AddMultiIntSetting()
void CGUIDialogPVRTimerSettings::AddMultiIntSetting (const std::shared_ptr< CSettingGroup > & group, const std::string & settingName, int settingValue) override virtual
Reimplemented from PVR::IPVRSettingsContainer.
References CGUIDialogSettingsManualBase::AddList(), AddTypeDependentEnableCondition(), AddTypeDependentVisibilityCondition(), Basic, and CustomIntSettingDefinitionsFiller().
AddMultiStringSetting()
void CGUIDialogPVRTimerSettings::AddMultiStringSetting (const std::shared_ptr< CSettingGroup > & group, const std::string & settingName, const std::string & settingValue) override virtual
Reimplemented from PVR::IPVRSettingsContainer.
References CGUIDialogSettingsManualBase::AddList(), AddTypeDependentEnableCondition(), AddTypeDependentVisibilityCondition(), Basic, and CustomStringSettingDefinitionsFiller().
AddSingleIntSetting()
void CGUIDialogPVRTimerSettings::AddSingleIntSetting (const std::shared_ptr< CSettingGroup > & group, const std::string & settingName, int settingValue, int minValue, int step, int maxValue) override virtual
Reimplemented from PVR::IPVRSettingsContainer.
References CGUIDialogSettingsManualBase::AddEdit(), AddTypeDependentEnableCondition(), AddTypeDependentVisibilityCondition(), and Basic.
AddSingleStringSetting()
void CGUIDialogPVRTimerSettings::AddSingleStringSetting (const std::shared_ptr< CSettingGroup > & group, const std::string & settingName, const std::string & settingValue, bool allowEmptyValue) override virtual
Reimplemented from PVR::IPVRSettingsContainer.
References CGUIDialogSettingsManualBase::AddEdit(), AddTypeDependentEnableCondition(), AddTypeDependentVisibilityCondition(), and Basic.
AddStartAnytimeDependentVisibilityCondition()
void CGUIDialogPVRTimerSettings::AddStartAnytimeDependentVisibilityCondition (const std::shared_ptr< CSetting > & setting, const std::string & identifier) private
References AddCondition(), id, SETTING_TMR_START_ANYTIME, START_ANYTIME_DEP_VISIBI_COND_ID_POSTFIX, StartAnytimeSetCondition(), and Visible.
Referenced by InitializeSettings().
AddTypeDependentEnableCondition()
void CGUIDialogPVRTimerSettings::AddTypeDependentEnableCondition (const std::shared_ptr< CSetting > & setting, const std::string & identifier) private
References AddCondition(), Enable, id, SETTING_TMR_TYPE, TYPE_DEP_ENABLE_COND_ID_POSTFIX, and TypeReadOnlyCondition().
Referenced by AddMultiIntSetting(), AddMultiStringSetting(), AddSingleIntSetting(), AddSingleStringSetting(), and InitializeSettings().
AddTypeDependentVisibilityCondition()
void CGUIDialogPVRTimerSettings::AddTypeDependentVisibilityCondition (const std::shared_ptr< CSetting > & setting, const std::string & identifier) private
References AddCondition(), id, SETTING_TMR_TYPE, TYPE_DEP_VISIBI_COND_ID_POSTFIX, TypeSupportsCondition(), and Visible.
Referenced by AddMultiIntSetting(), AddMultiStringSetting(), AddSingleIntSetting(), AddSingleStringSetting(), and InitializeSettings().
AllowResettingSettings()
bool PVR::CGUIDialogPVRTimerSettings::AllowResettingSettings () const inline override protected virtual
Reimplemented from CGUIDialogSettingsBase.
CanBeActivated()
bool CGUIDialogPVRTimerSettings::CanBeActivated () const override virtual
Reimplemented from CGUIWindow.
References LOGERROR, and m_timerInfoTag.
ChannelsFiller()
void CGUIDialogPVRTimerSettings::ChannelsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References data(), LOGERROR, m_channel, m_channelEntries, m_timerType, PVR_CHANNEL_INVALID_UID, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by InitializeSettings().
CustomIntSettingDefinitionsFiller()
void CGUIDialogPVRTimerSettings::CustomIntSettingDefinitionsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References data(), LOGERROR, and m_customTimerSettings.
Referenced by AddMultiIntSetting().
CustomStringSettingDefinitionsFiller()
void CGUIDialogPVRTimerSettings::CustomStringSettingDefinitionsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static private
References data(), LOGERROR, and m_customTimerSettings.
Referenced by AddMultiStringSetting().
DaysFiller()
void CGUIDialogPVRTimerSettings::DaysFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References data(), CDateTime::GetAsLocalizedDate(), CDateTime::GetCurrentDateTime(), GetDateAsIndex(), CDateTime::GetDay(), CDateTime::GetMonth(), CDateTime::GetYear(), LOGERROR, m_endLocalTime, m_firstDayLocalTime, m_startLocalTime, m_timerInfoTag, SETTING_TMR_FIRST_DAY, and SETTING_TMR_START_DAY.
Referenced by InitializeSettings().
DupEpisodesFiller()
void CGUIDialogPVRTimerSettings::DupEpisodesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References data(), LOGERROR, m_iPreventDupEpisodes, m_timerType, value, and values.
Referenced by InitializeSettings().
EndAnytimeSetCondition()
bool CGUIDialogPVRTimerSettings::EndAnytimeSetCondition (const std::string & condition, const std::string & value, const std::shared_ptr< const CSetting > & setting, void * data) static private
References data(), END_ANYTIME_DEP_VISIBI_COND_ID_POSTFIX, LOGERROR, m_timerType, SETTING_TMR_END, SETTING_TMR_END_DAY, and value.
Referenced by AddEndAnytimeDependentVisibilityCondition().
GetDateAsIndex()
int CGUIDialogPVRTimerSettings::GetDateAsIndex (const CDateTime & datetime) static private
References CDateTime::GetAsTime(), CDateTime::GetDay(), CDateTime::GetMonth(), CDateTime::GetYear(), and t.
Referenced by DaysFiller(), and InitializeSettings().
GetSettingsLabel()
std::string CGUIDialogPVRTimerSettings::GetSettingsLabel (const std::shared_ptr< ISetting > & pSetting) override protected virtual
Get the name for the setting entry.
Used as virtual to allow related settings dialog to give a std::string name of the setting. If not used on own dialog class it handle the string from int CSetting::GetLabel(), This must also be used if on related dialog no special entry is wanted.
Parameters
pSetting Base settings class which need the name
Returns
Name used on settings dialog
Reimplemented from CGUIDialogSettingsBase.
References CGUIDialogSettingsBase::GetSettingsLabel(), label, and m_customTimerSettings.
GetWeekdaysFromSetting()
int CGUIDialogPVRTimerSettings::GetWeekdaysFromSetting (const std::shared_ptr< const CSetting > & setting) static private
References CSettingUtils::GetList(), Integer, LOGERROR, and value.
Referenced by OnSettingChanged(), and WeekdaysValueFormatter().
InitializeChannelsList()
void CGUIDialogPVRTimerSettings::InitializeChannelsList () private
References PVR::CPVRManager::ChannelGroups(), PVR::CPVRManager::Clients(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetPVRManager(), index(), m_bIsRadio, m_channelEntries, PVR::CPVRChannelGroup::ONLY_VISIBLE, PVR_CHANNEL_INVALID_UID, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by SetTimer().
InitializeSettings()
void CGUIDialogPVRTimerSettings::InitializeSettings () override protected virtual
Reimplemented from CGUIDialogSettingsManualBase.
References CGUIDialogSettingsManualBase::AddButton(), CGUIDialogSettingsManualBase::AddCategory(), CGUIDialogSettingsManualBase::AddEdit(), AddEndAnytimeDependentVisibilityCondition(), CGUIDialogSettingsManualBase::AddGroup(), CGUIDialogSettingsManualBase::AddList(), CGUIDialogSettingsManualBase::AddSpinner(), AddStartAnytimeDependentVisibilityCondition(), CGUIDialogSettingsManualBase::AddToggle(), AddTypeDependentEnableCondition(), AddTypeDependentVisibilityCondition(), Basic, ChannelsFiller(), PVR::CPVRManager::Clients(), DaysFiller(), DupEpisodesFiller(), GetDateAsIndex(), CServiceBroker::GetPVRManager(), CGUIDialogSettingsManualBase::InitializeSettings(), LifetimesFiller(), LOGERROR, m_bEndAnyTime, m_bFullTextEpgSearch, m_bStartAnyTime, m_bTimerActive, m_customTimerSettings, m_endLocalTime, m_firstDayLocalTime, m_iLifetime, m_iMarginEnd, m_iMarginStart, m_iMaxRecordings, m_iPreventDupEpisodes, m_iPriority, m_iRecordingGroup, m_iWeekdays, m_startLocalTime, m_strDirectory, m_strEpgSearchString, m_strTitle, MarginTimeFiller(), MaxRecordingsFiller(), PrioritiesFiller(), PVR_WEEKDAY_FRIDAY, PVR_WEEKDAY_MONDAY, PVR_WEEKDAY_SATURDAY, PVR_WEEKDAY_SUNDAY, PVR_WEEKDAY_THURSDAY, PVR_WEEKDAY_TUESDAY, PVR_WEEKDAY_WEDNESDAY, RecordingGroupFiller(), SETTING_TMR_ACTIVE, SETTING_TMR_BEGIN, SETTING_TMR_BEGIN_PRE, SETTING_TMR_CHANNEL, SETTING_TMR_DIR, SETTING_TMR_END, SETTING_TMR_END_ANYTIME, SETTING_TMR_END_DAY, SETTING_TMR_END_POST, SETTING_TMR_EPGSEARCH, SETTING_TMR_FIRST_DAY, SETTING_TMR_FULLTEXT, SETTING_TMR_LIFETIME, SETTING_TMR_MAX_REC, SETTING_TMR_NAME, SETTING_TMR_NEW_EPISODES, SETTING_TMR_PRIORITY, SETTING_TMR_REC_GROUP, SETTING_TMR_START_ANYTIME, SETTING_TMR_START_DAY, SETTING_TMR_TYPE, SETTING_TMR_WEEKDAYS, TypesFiller(), WeekdaysFiller(), and WeekdaysValueFormatter().
InitializeTypesList()
void CGUIDialogPVRTimerSettings::InitializeTypesList () private
References PVR::CPVRTimerType::GetAllTypes(), CDateTime::GetCurrentDateTime(), m_timerInfoTag, m_timerType, m_typeEntries, and types.
Referenced by SetTimer().
LifetimesFiller()
void CGUIDialogPVRTimerSettings::LifetimesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References data(), g_localizeStrings, CLocalizeStrings::Get(), LOGERROR, m_iLifetime, m_timerType, value, and values.
Referenced by InitializeSettings().
MarginTimeFiller()
void CGUIDialogPVRTimerSettings::MarginTimeFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References data(), g_localizeStrings, CLocalizeStrings::Get(), LOGERROR, m_iMarginEnd, m_iMarginStart, PVR::CPVRSettings::MarginTimeFiller(), and SETTING_TMR_BEGIN_PRE.
Referenced by InitializeSettings().
MaxRecordingsFiller()
void CGUIDialogPVRTimerSettings::MaxRecordingsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References data(), LOGERROR, m_iMaxRecordings, m_timerType, value, and values.
Referenced by InitializeSettings().
OnSettingAction()
void CGUIDialogPVRTimerSettings::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override protected virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetAsLocalizedTime(), CDateTime::GetAsSystemTime(), LOGERROR, m_endLocalTime, m_startLocalTime, m_timerEndTimeStr, m_timerStartTimeStr, ISettingCallback::OnSettingAction(), SetButtonLabels(), SetTimeFromSystemTime(), SETTING_TMR_BEGIN, SETTING_TMR_END, and CGUIDialogNumeric::ShowAndGetTime().
OnSettingChanged()
void CGUIDialogPVRTimerSettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override protected virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References GetValue(), GetWeekdaysFromSetting(), LOGERROR, m_bEndAnyTime, m_bFullTextEpgSearch, m_bStartAnyTime, m_bTimerActive, m_channel, m_channelEntries, m_customTimerSettings, m_endLocalTime, m_firstDayLocalTime, m_iLifetime, m_iMarginEnd, m_iMarginStart, m_iMaxRecordings, m_iPreventDupEpisodes, m_iPriority, m_iRecordingGroup, m_iWeekdays, m_startLocalTime, m_strDirectory, m_strEpgSearchString, m_strTitle, m_timerType, m_typeEntries, CGUIDialogSettingsBase::OnSettingChanged(), PVR_WEEKDAY_ALLDAYS, SetButtonLabels(), SetDateFromIndex(), SETTING_TMR_ACTIVE, SETTING_TMR_BEGIN_PRE, SETTING_TMR_CHANNEL, SETTING_TMR_DIR, SETTING_TMR_END_ANYTIME, SETTING_TMR_END_DAY, SETTING_TMR_END_POST, SETTING_TMR_EPGSEARCH, SETTING_TMR_FIRST_DAY, SETTING_TMR_FULLTEXT, SETTING_TMR_LIFETIME, SETTING_TMR_MAX_REC, SETTING_TMR_NAME, SETTING_TMR_NEW_EPISODES, SETTING_TMR_PRIORITY, SETTING_TMR_REC_GROUP, SETTING_TMR_START_ANYTIME, SETTING_TMR_START_DAY, SETTING_TMR_TYPE, and SETTING_TMR_WEEKDAYS.
PrioritiesFiller()
void CGUIDialogPVRTimerSettings::PrioritiesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References data(), LOGERROR, m_iPriority, m_timerType, value, and values.
Referenced by InitializeSettings().
RecordingGroupFiller()
void CGUIDialogPVRTimerSettings::RecordingGroupFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References data(), LOGERROR, m_iRecordingGroup, m_timerType, value, and values.
Referenced by InitializeSettings().
Save()
bool CGUIDialogPVRTimerSettings::Save () override protected virtual
Implements CGUIDialogSettingsManagerBase.
References PVR::CGUIDialogPVRTimerSettings::ChannelDescriptor::channelUid, PVR::CGUIDialogPVRTimerSettings::ChannelDescriptor::clientId, g_localizeStrings, CLocalizeStrings::Get(), CLog::Log(), LOGDEBUG, LOGPVR, LOGWARNING, m_bEndAnyTime, m_bFullTextEpgSearch, m_bIsRadio, m_bStartAnyTime, m_bTimerActive, m_channel, m_customTimerSettings, m_endLocalTime, m_firstDayLocalTime, m_iLifetime, m_iMarginEnd, m_iMarginStart, m_iMaxRecordings, m_iPreventDupEpisodes, m_iPriority, m_iRecordingGroup, m_iWeekdays, m_startLocalTime, m_strDirectory, m_strEpgSearchString, m_strTitle, m_timerInfoTag, m_timerType, PVR_TIMER_STATE_DISABLED, PVR_TIMER_STATE_SCHEDULED, PVR_WEEKDAY_NONE, and Validate().
SetButtonLabels()
void CGUIDialogPVRTimerSettings::SetButtonLabels () private
References CGUIDialogSettingsBase::GetSettingControl(), m_timerEndTimeStr, m_timerStartTimeStr, SET_CONTROL_LABEL2, SETTING_TMR_BEGIN, and SETTING_TMR_END.
Referenced by OnSettingAction(), OnSettingChanged(), and SetupView().
SetDateFromIndex()
void CGUIDialogPVRTimerSettings::SetDateFromIndex (CDateTime & datetime, int date) static private
References CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetSecond(), CDateTime::GetYear(), and CDateTime::SetDateTime().
Referenced by OnSettingChanged().
SetTimeFromSystemTime()
void CGUIDialogPVRTimerSettings::SetTimeFromSystemTime (CDateTime & datetime, const KODI::TIME::SystemTime & time) static private
References CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetSecond(), CDateTime::GetYear(), and CDateTime::SetDateTime().
Referenced by OnSettingAction().
SetTimer()
void CGUIDialogPVRTimerSettings::SetTimer (const std::shared_ptr< CPVRTimerInfoTag > & timer)
References CDateTime::GetAsLocalizedTime(), InitializeChannelsList(), InitializeTypesList(), LOGERROR, m_bEndAnyTime, m_bFullTextEpgSearch, m_bIsNewTimer, m_bIsRadio, m_bStartAnyTime, m_bTimerActive, m_channel, m_channelEntries, m_customTimerSettings, m_endLocalTime, m_firstDayLocalTime, m_iLifetime, m_iMarginEnd, m_iMarginStart, m_iMaxRecordings, m_iPreventDupEpisodes, m_iPriority, m_iRecordingGroup, m_iWeekdays, m_startLocalTime, m_strDirectory, m_strEpgSearchString, m_strTitle, m_timerEndTimeStr, m_timerInfoTag, m_timerStartTimeStr, m_timerType, m_typeEntries, PVR_CHANNEL_INVALID_UID, PVR_TIMER_NO_CLIENT_INDEX, PVR_TIMER_STATE_DISABLED, PVR_WEEKDAY_ALLDAYS, and PVR_WEEKDAY_NONE.
Referenced by PVR::CPVRGUIActionsTimers::ShowTimerSettings().
SetupView()
void CGUIDialogPVRTimerSettings::SetupView () override protected virtual
Reimplemented from CGUIDialogSettingsBase.
References CONTROL_SETTINGS_CANCEL_BUTTON, CONTROL_SETTINGS_CUSTOM_BUTTON, CONTROL_SETTINGS_OKAY_BUTTON, SET_CONTROL_HIDDEN, SET_CONTROL_LABEL, SetButtonLabels(), CGUIDialogSettingsBase::SetHeading(), and CGUIDialogSettingsManualBase::SetupView().
StartAnytimeSetCondition()
bool CGUIDialogPVRTimerSettings::StartAnytimeSetCondition (const std::string & condition, const std::string & value, const std::shared_ptr< const CSetting > & setting, void * data) static private
References data(), LOGERROR, m_timerType, SETTING_TMR_BEGIN, SETTING_TMR_START_DAY, START_ANYTIME_DEP_VISIBI_COND_ID_POSTFIX, and value.
Referenced by AddStartAnytimeDependentVisibilityCondition().
TypeReadOnlyCondition()
bool CGUIDialogPVRTimerSettings::TypeReadOnlyCondition (const std::string & condition, const std::string & value, const std::shared_ptr< const CSetting > & setting, void * data) static private
References data(), LOGERROR, m_bIsNewTimer, m_customTimerSettings, m_timerInfoTag, m_timerType, m_typeEntries, PVR_TIMER_STATE_RECORDING, SETTING_TMR_ACTIVE, SETTING_TMR_BEGIN, SETTING_TMR_BEGIN_PRE, SETTING_TMR_CHANNEL, SETTING_TMR_DIR, SETTING_TMR_END, SETTING_TMR_END_DAY, SETTING_TMR_NAME, SETTING_TMR_PRIORITY, SETTING_TMR_START_DAY, SETTING_TMR_TYPE, TYPE_DEP_ENABLE_COND_ID_POSTFIX, and value.
Referenced by AddTypeDependentEnableCondition().
TypesFiller()
void CGUIDialogPVRTimerSettings::TypesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References PVR::CPVRManager::Clients(), data(), CServiceBroker::GetPVRManager(), LOGERROR, m_timerType, and m_typeEntries.
Referenced by InitializeSettings().
TypeSupportsCondition()
bool CGUIDialogPVRTimerSettings::TypeSupportsCondition (const std::string & condition, const std::string & value, const std::shared_ptr< const CSetting > & setting, void * data) static private
References data(), LOGERROR, m_customTimerSettings, m_typeEntries, SETTING_TMR_ACTIVE, SETTING_TMR_BEGIN, SETTING_TMR_BEGIN_PRE, SETTING_TMR_CHANNEL, SETTING_TMR_DIR, SETTING_TMR_END, SETTING_TMR_END_ANYTIME, SETTING_TMR_END_DAY, SETTING_TMR_END_POST, SETTING_TMR_EPGSEARCH, SETTING_TMR_FIRST_DAY, SETTING_TMR_FULLTEXT, SETTING_TMR_LIFETIME, SETTING_TMR_MAX_REC, SETTING_TMR_NEW_EPISODES, SETTING_TMR_PRIORITY, SETTING_TMR_REC_GROUP, SETTING_TMR_START_ANYTIME, SETTING_TMR_START_DAY, SETTING_TMR_WEEKDAYS, TYPE_DEP_VISIBI_COND_ID_POSTFIX, and value.
Referenced by AddTypeDependentVisibilityCondition().
Validate()
bool CGUIDialogPVRTimerSettings::Validate () private
References m_bEndAnyTime, m_bStartAnyTime, m_endLocalTime, m_startLocalTime, m_timerType, and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by Save().
WeekdaysFiller()
void CGUIDialogPVRTimerSettings::WeekdaysFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static private
References data(), g_localizeStrings, CLocalizeStrings::Get(), LOGERROR, m_iWeekdays, PVR_WEEKDAY_FRIDAY, PVR_WEEKDAY_MONDAY, PVR_WEEKDAY_SATURDAY, PVR_WEEKDAY_SUNDAY, PVR_WEEKDAY_THURSDAY, PVR_WEEKDAY_TUESDAY, and PVR_WEEKDAY_WEDNESDAY.
Referenced by InitializeSettings().
WeekdaysValueFormatter()
std::string CGUIDialogPVRTimerSettings::WeekdaysValueFormatter (const std::shared_ptr< const CSetting > & setting) static private
References GetWeekdaysFromSetting(), and PVR::CPVRTimerInfoTag::GetWeekdaysString().
Referenced by InitializeSettings().
Member Data Documentation
m_bEndAnyTime
bool PVR::CGUIDialogPVRTimerSettings::m_bEndAnyTime = false private
Referenced by InitializeSettings(), OnSettingChanged(), Save(), SetTimer(), and Validate().
m_bFullTextEpgSearch
bool PVR::CGUIDialogPVRTimerSettings::m_bFullTextEpgSearch = true private
Referenced by InitializeSettings(), OnSettingChanged(), Save(), and SetTimer().
m_bIsNewTimer
bool PVR::CGUIDialogPVRTimerSettings::m_bIsNewTimer = true private
Referenced by SetTimer(), and TypeReadOnlyCondition().
m_bIsRadio
bool PVR::CGUIDialogPVRTimerSettings::m_bIsRadio = false private
Referenced by InitializeChannelsList(), Save(), and SetTimer().
m_bStartAnyTime
bool PVR::CGUIDialogPVRTimerSettings::m_bStartAnyTime = false private
Referenced by InitializeSettings(), OnSettingChanged(), Save(), SetTimer(), and Validate().
m_bTimerActive
bool PVR::CGUIDialogPVRTimerSettings::m_bTimerActive = false private
Referenced by InitializeSettings(), OnSettingChanged(), Save(), and SetTimer().
m_channel
ChannelDescriptor PVR::CGUIDialogPVRTimerSettings::m_channel private
Referenced by ChannelsFiller(), OnSettingChanged(), Save(), and SetTimer().
m_channelEntries
ChannelEntriesMap PVR::CGUIDialogPVRTimerSettings::m_channelEntries private
Referenced by ChannelsFiller(), InitializeChannelsList(), OnSettingChanged(), and SetTimer().
m_customTimerSettings
std::unique_ptr<CPVRCustomTimerSettings> PVR::CGUIDialogPVRTimerSettings::m_customTimerSettings private
Referenced by CustomIntSettingDefinitionsFiller(), CustomStringSettingDefinitionsFiller(), GetSettingsLabel(), InitializeSettings(), OnSettingChanged(), Save(), SetTimer(), TypeReadOnlyCondition(), and TypeSupportsCondition().
m_endLocalTime
CDateTime PVR::CGUIDialogPVRTimerSettings::m_endLocalTime private
Referenced by DaysFiller(), InitializeSettings(), OnSettingAction(), OnSettingChanged(), Save(), SetTimer(), and Validate().
m_firstDayLocalTime
CDateTime PVR::CGUIDialogPVRTimerSettings::m_firstDayLocalTime private
Referenced by DaysFiller(), InitializeSettings(), OnSettingChanged(), Save(), and SetTimer().
m_iLifetime
int PVR::CGUIDialogPVRTimerSettings::m_iLifetime = 0 private
Referenced by InitializeSettings(), LifetimesFiller(), OnSettingChanged(), Save(), and SetTimer().
m_iMarginEnd
unsigned int PVR::CGUIDialogPVRTimerSettings::m_iMarginEnd = 0 private
Referenced by InitializeSettings(), MarginTimeFiller(), OnSettingChanged(), Save(), and SetTimer().
m_iMarginStart
unsigned int PVR::CGUIDialogPVRTimerSettings::m_iMarginStart = 0 private
Referenced by InitializeSettings(), MarginTimeFiller(), OnSettingChanged(), Save(), and SetTimer().
m_iMaxRecordings
int PVR::CGUIDialogPVRTimerSettings::m_iMaxRecordings = 0 private
Referenced by InitializeSettings(), MaxRecordingsFiller(), OnSettingChanged(), Save(), and SetTimer().
m_iPreventDupEpisodes
unsigned int PVR::CGUIDialogPVRTimerSettings::m_iPreventDupEpisodes = 0 private
Referenced by DupEpisodesFiller(), InitializeSettings(), OnSettingChanged(), Save(), and SetTimer().
m_iPriority
int PVR::CGUIDialogPVRTimerSettings::m_iPriority = 0 private
Referenced by InitializeSettings(), OnSettingChanged(), PrioritiesFiller(), Save(), and SetTimer().
m_iRecordingGroup
unsigned int PVR::CGUIDialogPVRTimerSettings::m_iRecordingGroup = 0 private
Referenced by InitializeSettings(), OnSettingChanged(), RecordingGroupFiller(), Save(), and SetTimer().
m_iWeekdays
unsigned int PVR::CGUIDialogPVRTimerSettings::m_iWeekdays private
Referenced by InitializeSettings(), OnSettingChanged(), Save(), SetTimer(), and WeekdaysFiller().
m_startLocalTime
CDateTime PVR::CGUIDialogPVRTimerSettings::m_startLocalTime private
Referenced by DaysFiller(), InitializeSettings(), OnSettingAction(), OnSettingChanged(), Save(), SetTimer(), and Validate().
m_strDirectory
std::string PVR::CGUIDialogPVRTimerSettings::m_strDirectory private
Referenced by InitializeSettings(), OnSettingChanged(), Save(), and SetTimer().
m_strEpgSearchString
std::string PVR::CGUIDialogPVRTimerSettings::m_strEpgSearchString private
Referenced by InitializeSettings(), OnSettingChanged(), Save(), and SetTimer().
m_strTitle
std::string PVR::CGUIDialogPVRTimerSettings::m_strTitle private
Referenced by InitializeSettings(), OnSettingChanged(), Save(), and SetTimer().
m_timerEndTimeStr
std::string PVR::CGUIDialogPVRTimerSettings::m_timerEndTimeStr private
Referenced by OnSettingAction(), SetButtonLabels(), and SetTimer().
m_timerInfoTag
std::shared_ptr<CPVRTimerInfoTag> PVR::CGUIDialogPVRTimerSettings::m_timerInfoTag private
Referenced by CanBeActivated(), DaysFiller(), InitializeTypesList(), Save(), SetTimer(), and TypeReadOnlyCondition().
m_timerStartTimeStr
std::string PVR::CGUIDialogPVRTimerSettings::m_timerStartTimeStr private
Referenced by OnSettingAction(), SetButtonLabels(), and SetTimer().
m_timerType
std::shared_ptr<CPVRTimerType> PVR::CGUIDialogPVRTimerSettings::m_timerType private
Referenced by ChannelsFiller(), DupEpisodesFiller(), EndAnytimeSetCondition(), InitializeTypesList(), LifetimesFiller(), MaxRecordingsFiller(), OnSettingChanged(), PrioritiesFiller(), RecordingGroupFiller(), Save(), SetTimer(), StartAnytimeSetCondition(), TypeReadOnlyCondition(), TypesFiller(), and Validate().
m_typeEntries
TypeEntriesMap PVR::CGUIDialogPVRTimerSettings::m_typeEntries private
Referenced by InitializeTypesList(), OnSettingChanged(), SetTimer(), TypeReadOnlyCondition(), TypesFiller(), and TypeSupportsCondition().
The documentation for this class was generated from the following files:
GUIDialogPVRTimerSettings.h
GUIDialogPVRTimerSettings.cpp