Kodi Documentation: CDbUrl Class Reference
CDbUrl Class Reference abstract
#include <DbUrl.h>
Public Member Functions
CDbUrl ()
~CDbUrl () override
bool IsValid () const
void Reset ()
std::string ToString () const
bool FromString (const std::string &dbUrl)
const std::string & GetType () const
void AppendPath (const std::string &subPath)
void AddOption (const std::string &key, const char *value) override
void AddOption (const std::string &key, const std::string &value) override
void AddOption (const std::string &key, int value) override
void AddOption (const std::string &key, float value) override
void AddOption (const std::string &key, double value) override
void AddOption (const std::string &key, bool value) override
void AddOptions (const std::string &options) override
void RemoveOption (const std::string &key) override
bool GetOption (const std::string &key, CVariant &value) const
const UrlOptions & GetOptions () const
std::string GetOptionsString (bool withLeadingSeparator=false) const
bool HasOption (const std::string &key) const
Protected Member Functions
virtual bool parse ()=0
virtual bool validateOption (const std::string &key, const CVariant &value)
Protected Attributes
CURL m_url
std::string m_type
Private Member Functions
void updateOptions ()
Private Member Functions inherited from CUrlOptions
CUrlOptions ()
CUrlOptions (const std::string &options, const char *strLead="")
virtual ~CUrlOptions ()
void Clear ()
const UrlOptions & GetOptions () const
std::string GetOptionsString (bool withLeadingSeparator=false) const
virtual void AddOptions (const CUrlOptions &options)
bool HasOption (const std::string &key) const
bool GetOption (const std::string &key, CVariant &value) const
Private Attributes
bool m_valid
Private Attributes inherited from CUrlOptions
UrlOptions m_options
std::string m_strLead
Additional Inherited Members
Private Types inherited from CUrlOptions
typedef std::map< std::string, CVariant > UrlOptions
Constructor & Destructor Documentation
CDbUrl()
CDbUrl::CDbUrl ()
References Reset().
~CDbUrl()
CDbUrl::~CDbUrl () override default
Member Function Documentation
AddOption() [1/6]
void CDbUrl::AddOption (const std::string & key, bool value) override virtual
Reimplemented from CUrlOptions.
References CUrlOptions::AddOption(), updateOptions(), validateOption(), and value.
AddOption() [2/6]
void CDbUrl::AddOption (const std::string & key, const char * value) override virtual
Reimplemented from CUrlOptions.
References CUrlOptions::AddOption(), updateOptions(), validateOption(), and value.
Referenced by CVideoDatabase::FillMovieItem(), JSONRPC::CAudioLibrary::GetAlbums(), CMusicDatabase::GetAlbumsByYear(), CMusicDatabase::GetAlbumsNav(), JSONRPC::CAudioLibrary::GetArtistDetails(), JSONRPC::CAudioLibrary::GetArtists(), CMusicDatabase::GetArtistsNav(), XFILE::CSmartPlaylistDirectory::GetDirectory(), CMusicDatabase::GetDiscsByWhere(), CMusicDatabase::GetDiscsNav(), JSONRPC::CVideoLibrary::GetEpisodes(), CVideoDatabase::GetEpisodesNav(), CGUIDialogVideoInfo::GetItemsForTag(), JSONRPC::CVideoLibrary::GetMovies(), CVideoDatabase::GetMoviesNav(), CVideoDatabase::GetMusicVideoAlbumsNav(), JSONRPC::CVideoLibrary::GetMusicVideos(), CVideoDatabase::GetMusicVideosNav(), CMusicDatabase::GetRolesNav(), CVideoDatabase::GetSeasonsNav(), JSONRPC::CAudioLibrary::GetSongs(), CMusicDatabase::GetSongsByYear(), CMusicDatabase::GetSongsNav(), CMusicDatabase::GetSourcesNav(), JSONRPC::CVideoLibrary::GetTVShows(), CVideoDatabase::GetTvShowsNav(), CVideoDatabase::GetVideoVersions(), CMusicDatabase::GetYearsNav(), CMusicDbUrl::parse(), CVideoDbUrl::parse(), JSONRPC::CAudioLibrary::RefreshArtist(), anonymous_namespace{VideoDatabase.cpp}::RewriteVideoVersionURL(), CRecentlyAddedJob::UpdateTotal(), and CGUIWindowVideoBase::UpdateVideoVersionItems().
AddOption() [3/6]
void CDbUrl::AddOption (const std::string & key, const std::string & value) override virtual
Reimplemented from CUrlOptions.
References CUrlOptions::AddOption(), updateOptions(), validateOption(), and value.
AddOption() [4/6]
void CDbUrl::AddOption (const std::string & key, double value) override virtual
Reimplemented from CUrlOptions.
References CUrlOptions::AddOption(), updateOptions(), validateOption(), and value.
AddOption() [5/6]
void CDbUrl::AddOption (const std::string & key, float value) override virtual
Reimplemented from CUrlOptions.
References CUrlOptions::AddOption(), updateOptions(), validateOption(), and value.
AddOption() [6/6]
void CDbUrl::AddOption (const std::string & key, int value) override virtual
Reimplemented from CUrlOptions.
References CUrlOptions::AddOption(), updateOptions(), validateOption(), and value.
AddOptions()
void CDbUrl::AddOptions (const std::string & options) override virtual
Reimplemented from CUrlOptions.
References CUrlOptions::AddOptions(), and updateOptions().
Referenced by GroupUtils::Group(), CMusicDbUrl::parse(), and CVideoDbUrl::parse().
AppendPath()
void CDbUrl::AppendPath (const std::string & subPath)
References URIUtils::AddFileToFolder(), CURL::GetFileName(), m_url, m_valid, and CURL::SetFileName().
Referenced by CMusicFileItemListModifier::AddQueuingFolder(), CVideoFileItemListModifier::AddQueuingFolder(), CVideoDatabase::FillMovieItem(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetCommonNav(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMusicVideosOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview::GetContent(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CMusicDatabase::GetDiscsByWhere(), CVideoDatabase::GetEpisodesByWhere(), CMusicDatabase::GetFileItemFromDataset(), CMusicDatabase::GetGenresNav(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), CMusicDatabase::GetRolesNav(), CVideoDatabase::GetSeasonsByWhere(), CMusicDatabase::GetSourcesNav(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetVideoVersionsNav(), CMusicDatabase::GetYearsNav(), CVideoDatabase::GetYearsNav(), and anonymous_namespace{VideoDatabase.cpp}::RewriteVideoVersionURL().
FromString()
bool CDbUrl::FromString (const std::string & dbUrl)
References m_url, m_valid, parse(), CURL::Parse(), and Reset().
Referenced by CGUIDialogVideoInfo::AddItemsToTag(), CMusicFileItemListModifier::AddQueuingFolder(), CVideoFileItemListModifier::AddQueuingFolder(), CDatabase::BuildSQL(), CVideoDatabase::FillMovieItem(), JSONRPC::CAudioLibrary::GetAlbums(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetAlbumsByYear(), CMusicDatabase::GetAlbumsNav(), JSONRPC::CAudioLibrary::GetArtistDetails(), JSONRPC::CAudioLibrary::GetArtists(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetArtistsNav(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMusicVideosOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview::GetContent(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CMusicDatabase::GetDiscsByWhere(), CMusicDatabase::GetDiscsNav(), JSONRPC::CVideoLibrary::GetEpisodes(), CVideoDatabase::GetEpisodesNav(), CMusicDatabase::GetGenresNav(), CMusicDatabase::GetItems(), CVideoDatabase::GetItems(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CGUIDialogVideoInfo::GetItemsForTag(), JSONRPC::CVideoLibrary::GetMovies(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMoviesNav(), CVideoDatabase::GetMusicVideoAlbumsNav(), JSONRPC::CVideoLibrary::GetMusicVideos(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetMusicVideosNav(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), CMusicDatabase::GetRolesNav(), CVideoDatabase::GetSeasonsNav(), CVideoDatabase::GetSetsByWhere(), JSONRPC::CAudioLibrary::GetSongs(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsByYear(), CMusicDatabase::GetSongsFullByWhere(), CMusicDatabase::GetSongsNav(), CMusicDatabase::GetSourcesNav(), CMusicDatabase::GetTop100(), CMusicDatabase::GetTop100AlbumSongs(), JSONRPC::CVideoLibrary::GetTVShows(), CVideoDatabase::GetTvShowsNav(), CVideoDatabase::GetVideoVersions(), CVideoDatabase::GetVideoVersionsNav(), CMusicDatabase::GetYearsNav(), GroupUtils::Group(), CGUIDialogVideoInfo::ManageVideoItem(), JSONRPC::CAudioLibrary::RefreshArtist(), CGUIDialogVideoInfo::RemoveItemsFromTag(), anonymous_namespace{VideoDatabase.cpp}::RewriteVideoVersionURL(), CMusicDatabase::SearchSongs(), CGUIDialogMediaFilter::SetPath(), CMusicDatabase::SetScraperAll(), CRecentlyAddedJob::UpdateTotal(), CGUIWindowVideoBase::UpdateVideoVersionItems(), and CGUIWindowVideoBase::UpdateVideoVersionItemsLabel().
GetOption()
bool CUrlOptions::GetOption (const std::string & key, CVariant & value) const
Referenced by CGUIWindowVideoBase::UpdateVideoVersionItemsLabel().
GetOptions()
const UrlOptions & CUrlOptions::GetOptions () const inline
Referenced by CMusicFileItemListModifier::AddQueuingFolder(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), CVideoDatabase::GetMusicVideosByWhere(), and CVideoDatabase::GetSetsByWhere().
GetOptionsString()
std::string CUrlOptions::GetOptionsString (bool withLeadingSeparator = false) const
Referenced by updateOptions().
GetType()
const std::string & CDbUrl::GetType () const inline
References m_type.
Referenced by CGUIWindowVideoNav::GetDirectory(), CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), CMusicDatabase::GetItems(), CVideoDatabase::GetItems(), CGUIDialogMediaFilter::SetPath(), and CMusicDatabase::SetScraperAll().
HasOption()
bool CUrlOptions::HasOption (const std::string & key) const
Referenced by CMusicFileItemListModifier::AddQueuingFolder(), CMusicDatabase::GetArtistsNav(), JSONRPC::CVideoLibrary::GetEpisodes(), CGUIDialogMediaFilter::SetPath(), and CGUIWindowVideoBase::UpdateVideoVersionItemsLabel().
IsValid()
bool CDbUrl::IsValid () const inline
References m_valid.
Referenced by CMusicDatabase::GetFileItemFromDataset(), CMusicDatabase::GetFilter(), and CVideoDatabase::GetFilter().
parse()
virtual bool CDbUrl::parse () protected pure virtual
Implemented in CMusicDbUrl, and CVideoDbUrl.
Referenced by FromString().
RemoveOption()
void CDbUrl::RemoveOption (const std::string & key) override virtual
Reimplemented from CUrlOptions.
References CUrlOptions::RemoveOption(), and updateOptions().
Referenced by XFILE::CSmartPlaylistDirectory::GetDirectory(), CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), and CGUIDialogMediaFilter::SetPath().
Reset()
void CDbUrl::Reset ()
References CUrlOptions::m_options, m_type, m_url, m_valid, and CURL::Reset().
Referenced by CDatabase::BuildSQL(), CDbUrl(), and FromString().
ToString()
std::string CDbUrl::ToString () const
References CURL::Get(), m_url, and m_valid.
Referenced by CMusicFileItemListModifier::AddQueuingFolder(), CVideoFileItemListModifier::AddQueuingFolder(), CVideoDatabase::FillMovieItem(), JSONRPC::CAudioLibrary::GetAlbums(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByYear(), CMusicDatabase::GetAlbumsNav(), JSONRPC::CAudioLibrary::GetArtistDetails(), JSONRPC::CAudioLibrary::GetArtists(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsNav(), CMusicDatabase::GetCommonNav(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMusicVideosOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview::GetContent(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CMusicDatabase::GetDiscsByWhere(), JSONRPC::CVideoLibrary::GetEpisodes(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetEpisodesNav(), CMusicDatabase::GetFileItemFromDataset(), CMusicDatabase::GetGenresNav(), CGUIDialogMediaFilter::GetItems(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CGUIDialogVideoInfo::GetItemsForTag(), CGUIDialogMediaFilter::GetMinMax(), JSONRPC::CVideoLibrary::GetMovies(), CVideoDatabase::GetMoviesNav(), CVideoDatabase::GetMusicVideoAlbumsNav(), JSONRPC::CVideoLibrary::GetMusicVideos(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetMusicVideosNav(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), CMusicDatabase::GetRolesNav(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetSeasonsNav(), JSONRPC::CAudioLibrary::GetSongs(), CMusicDatabase::GetSongsNav(), CMusicDatabase::GetSourcesNav(), JSONRPC::CVideoLibrary::GetTVShows(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsNav(), CVideoDatabase::GetVideoVersions(), CMusicDatabase::GetYearsNav(), CVideoDatabase::GetYearsNav(), GroupUtils::Group(), JSONRPC::CAudioLibrary::RefreshArtist(), anonymous_namespace{VideoDatabase.cpp}::RewriteVideoVersionURL(), CRecentlyAddedJob::UpdateTotal(), and CGUIWindowVideoBase::UpdateVideoVersionItems().
updateOptions()
void CDbUrl::updateOptions () private
References GetOptionsString(), m_url, and CURL::SetOptions().
Referenced by AddOption(), AddOption(), AddOption(), AddOption(), AddOption(), AddOption(), AddOptions(), and RemoveOption().
validateOption()
bool CDbUrl::validateOption (const std::string & key, const CVariant & value) protected virtual
Reimplemented in CMusicDbUrl, and CVideoDbUrl.
Referenced by AddOption(), AddOption(), AddOption(), AddOption(), AddOption(), AddOption(), CMusicDbUrl::validateOption(), and CVideoDbUrl::validateOption().
Member Data Documentation
m_type
std::string CDbUrl::m_type protected
Referenced by GetType(), CMusicDbUrl::parse(), CVideoDbUrl::parse(), Reset(), and CMusicDbUrl::validateOption().
m_url
CURL CDbUrl::m_url protected
Referenced by AppendPath(), FromString(), CMusicDbUrl::parse(), CVideoDbUrl::parse(), Reset(), ToString(), and updateOptions().
m_valid
bool CDbUrl::m_valid private
Referenced by AppendPath(), FromString(), IsValid(), Reset(), and ToString().
The documentation for this class was generated from the following files:
DbUrl.h
DbUrl.cpp