Kodi Documentation: CRendererBase Class Reference
CRendererBase Class Reference abstract
#include <RendererBase.h>
Public Member Functions
virtual ~CRendererBase ()
virtual CRenderInfo GetRenderInfo ()
virtual bool Configure (const VideoPicture &picture, float fps, unsigned int orientation)
virtual bool Supports (ESCALINGMETHOD method) const =0
virtual bool Supports (ERENDERFEATURE feature) const
virtual bool WantsDoublePass ()
virtual bool NeedBuffer (int idx)
void AddVideoPicture (const VideoPicture &picture, int index)
void Render (int index, int index2, CD3DTexture &target, const CRect &sourceRect, const CRect &destRect, const CRect &viewRect, unsigned flags)
void Render (CD3DTexture &target, const CRect &sourceRect, const CRect &destRect, const CRect &viewRect, unsigned flags=0)
void ManageTextures ()
int NextBuffer () const
void ReleaseBuffer (int idx)
bool Flush (bool saveBuffers)
void SetBufferSize (int numBuffers)
DEBUG_INFO_VIDEO GetDebugInfo (int idx)
Static Public Member Functions
static DXGI_FORMAT GetDXGIFormat (const VideoPicture &picture)
static DXGI_FORMAT GetDXGIFormat (CVideoBuffer *videoBuffer)
static AVPixelFormat GetAVFormat (DXGI_FORMAT dxgi_format)
static DXGI_HDR_METADATA_HDR10 GetDXGIHDR10MetaData (CRenderBuffer *rb)
Protected Member Functions
CRendererBase (CVideoSettings &videoSettings)
bool CreateIntermediateTarget (unsigned int width, unsigned int height, bool dynamic=false, DXGI_FORMAT format=DXGI_FORMAT_UNKNOWN)
void OnCMSConfigChanged (AVColorPrimaries srcPrimaries)
void ReorderDrawPoints (const CRect &destRect, CPoint(&rotatedPoints)[4]) const
bool CreateRenderBuffer (int index)
void DeleteRenderBuffer (int index)
void ProcessHDR (CRenderBuffer *rb)
bool ActualRenderAsHDR ()
Call after rendering has started to find out if the output is configured as SDR or HDR.
virtual void RenderImpl (CD3DTexture &target, CRect &sourceRect, CPoint(&destPoints)[4], uint32_t flags)=0
virtual void FinalOutput (CD3DTexture &source, CD3DTexture &target, const CRect &sourceRect, const CPoint(&destPoints)[4])
virtual CRenderBuffer * CreateBuffer ()=0
virtual void UpdateVideoFilters ()
virtual void CheckVideoParameters ()
virtual void OnViewSizeChanged ()
virtual void OnOutputReset ()
virtual std::string GetRenderMethodDebugInfo () const
Static Protected Member Functions
static bool IntendToRenderAsHDR (const VideoPicture &picture)
Call before rendering begins to find out if rendering will be attempted as SDR or HDR.
Protected Attributes
bool m_toneMapping = false
bool m_useDithering = false
bool m_cmsOn = false
bool m_lutIsLoading = false
bool m_useHLGtoPQ = false
ETONEMAPMETHOD m_toneMapMethod = VS_TONEMAPMETHOD_OFF
int m_iBufferIndex = 0
int m_iNumBuffers = 0
int m_iBuffersRequired = 0
int m_ditherDepth = 0
int m_cmsToken = -1
int m_lutSize = 0
unsigned m_sourceWidth = 0
unsigned m_sourceHeight = 0
unsigned m_viewWidth = 0
unsigned m_viewHeight = 0
unsigned m_renderOrientation = 0
float m_fps = 0.0f
uint64_t m_frameIdx = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CD3DTexture m_IntermediateTarget
std::shared_ptr< COutputShader > m_outputShader
std::unique_ptr< CColorManager > m_colorManager
Microsoft::WRL::ComPtr< ID3D11ShaderResourceView > m_pLUTView
CVideoSettings & m_videoSettings
std::map< int, CRenderBuffer * > m_renderBuffers
DXGI_HDR_METADATA_HDR10 m_lastHdr10 = {}
HDR_TYPE m_HdrType = HDR_TYPE::HDR_INVALID
bool m_AutoSwitchHDR = false
bool m_initialHdrEnabled = false
std::string m_renderMethodName
Constructor & Destructor Documentation
~CRendererBase()
CRendererBase::~CRendererBase () virtual
References Flush(), LOGDEBUG, m_AutoSwitchHDR, and m_initialHdrEnabled.
CRendererBase()
CRendererBase::CRendererBase (CVideoSettings & videoSettings) explicit protected
References m_colorManager.
Member Function Documentation
ActualRenderAsHDR()
bool CRendererBase::ActualRenderAsHDR () inline protected
Call after rendering has started to find out if the output is configured as SDR or HDR.
Returns
true: HDR output, false: SDR output
References HDR_HDR10, HDR_HLG, and m_HdrType.
Referenced by CRendererDXVA::CheckVideoParameters().
AddVideoPicture()
void CRendererBase::AddVideoPicture (const VideoPicture & picture, int index)
References index(), m_frameIdx, and m_renderBuffers.
CheckVideoParameters()
void CRendererBase::CheckVideoParameters () protected virtual
Reimplemented in CRendererDXVA, CRendererHQ, and CRendererShaders.
References CRenderBuffer::color_transfer, HDR_HLG, HDR_NONE_SDR, m_cmsOn, m_cmsToken, m_colorManager, m_HdrType, m_iBufferIndex, m_lutIsLoading, m_outputShader, m_renderBuffers, m_toneMapMethod, CVideoSettings::m_ToneMapMethod, m_toneMapping, m_useHLGtoPQ, m_videoSettings, OnCMSConfigChanged(), OnOutputReset(), CRenderBuffer::primaries, and VS_TONEMAPMETHOD_OFF.
Referenced by Render().
Configure()
bool CRendererBase::Configure (const VideoPicture & picture, float fps, unsigned int orientation) virtual
References VideoPicture::color_primaries, VideoPicture::color_transfer, HDR_INVALID, VideoPicture::iHeight, VideoPicture::iWidth, LOGDEBUG, m_AutoSwitchHDR, m_ditherDepth, m_fps, m_HdrType, m_iBufferIndex, m_initialHdrEnabled, m_iNumBuffers, m_lastHdr10, m_renderOrientation, m_sourceHeight, m_sourceWidth, m_useDithering, and m_useHLGtoPQ.
CreateBuffer()
virtual CRenderBuffer * CRendererBase::CreateBuffer () protected pure virtual
Implemented in CRendererDXVA, CRendererShaders, and CRendererSoftware.
Referenced by CreateRenderBuffer().
CreateIntermediateTarget()
bool CRendererBase::CreateIntermediateTarget (unsigned int width, unsigned int height, bool dynamic = false, DXGI_FORMAT format = DXGI_FORMAT_UNKNOWN) protected
References CD3DTexture::Create(), DX::DXGIFormatToString(), CD3DTexture::Get(), CD3DTexture::GetFormat(), CD3DTexture::GetHeight(), CD3DTexture::GetWidth(), LOGDEBUG, LOGERROR, m_IntermediateTarget, and CD3DTexture::Release().
Referenced by CRendererDXVA::CheckVideoParameters(), CRendererShaders::Configure(), and CRendererSoftware::Configure().
CreateRenderBuffer()
bool CRendererBase::CreateRenderBuffer (int index) protected
References CreateBuffer(), index(), and m_renderBuffers.
Referenced by ManageTextures().
DeleteRenderBuffer()
void CRendererBase::DeleteRenderBuffer (int index) protected
References index(), and m_renderBuffers.
Referenced by Flush(), and ManageTextures().
FinalOutput()
void CRendererBase::FinalOutput (CD3DTexture & source, CD3DTexture & target, const CRect & sourceRect, const CPoint(&) destPoints[4]) protected virtual
Reimplemented in CRendererHQ, and CRendererSoftware.
References m_outputShader.
Referenced by Render().
Flush()
bool CRendererBase::Flush (bool saveBuffers)
References DeleteRenderBuffer(), m_iBufferIndex, m_iNumBuffers, and NUM_BUFFERS.
Referenced by ~CRendererBase().
GetAVFormat()
AVPixelFormat CRendererBase::GetAVFormat (DXGI_FORMAT dxgi_format) static
Referenced by CRendererShaders::Configure(), CRendererSoftware::Configure(), and CRendererSoftware::GetWeight().
GetDebugInfo()
DEBUG_INFO_VIDEO CRendererBase::GetDebugInfo (int idx)
References CRenderBuffer::bits, CRenderBuffer::color_transfer, CRenderBuffer::displayMetadata, DVP_FLAG_INTERLACED, DX::DXGIFormatToShortString(), CRenderBuffer::full_range, CD3DTexture::GetFormat(), CD3DTexture::GetHeight(), GetRenderMethodDebugInfo(), CD3DTexture::GetWidth(), CRenderBuffer::hasDisplayMetadata, CRenderBuffer::hasLightMetadata, CRenderBuffer::lightMetadata, m_fps, m_IntermediateTarget, CRenderBuffer::m_originalPrimaries, m_outputShader, m_renderBuffers, m_renderMethodName, m_sourceHeight, m_sourceWidth, max, CRenderBuffer::pictureFlags, CRenderBuffer::pixelFormat, CRenderBuffer::primaries, and DEBUG_INFO_VIDEO::videoSource.
GetDXGIFormat() [1/2]
DXGI_FORMAT CRendererBase::GetDXGIFormat (const VideoPicture & picture) static
References GetDXGIFormat(), CVideoBuffer::GetFormat(), and VideoPicture::videoBuffer.
Referenced by CRendererShaders::Configure(), CRendererSoftware::Configure(), GetDXGIFormat(), CRendererShaders::CRenderBufferImpl::GetView(), CRendererSoftware::GetWeight(), and CRendererShaders::IsHWPicSupported().
GetDXGIFormat() [2/2]
DXGI_FORMAT CRendererBase::GetDXGIFormat (CVideoBuffer * videoBuffer) static
References DXVA::CVideoBuffer::format.
GetDXGIHDR10MetaData()
DXGI_HDR_METADATA_HDR10 CRendererBase::GetDXGIHDR10MetaData (CRenderBuffer * rb) static
References CRenderBuffer::displayMetadata, CRenderBuffer::hasDisplayMetadata, CRenderBuffer::hasLightMetadata, and CRenderBuffer::lightMetadata.
Referenced by ProcessHDR().
GetRenderInfo()
CRenderInfo CRendererBase::GetRenderInfo () virtual
Reimplemented in CRendererDXVA.
References CRenderInfo::formats, and NUM_BUFFERS.
GetRenderMethodDebugInfo()
virtual std::string CRendererBase::GetRenderMethodDebugInfo () const inline protected virtual
Reimplemented in CRendererDXVA.
Referenced by GetDebugInfo().
IntendToRenderAsHDR()
bool CRendererBase::IntendToRenderAsHDR (const VideoPicture & picture) static protected
Call before rendering begins to find out if rendering will be attempted as SDR or HDR.
Parameters
picture description of the source
Returns
true: intent to render as HDR, false: intent to render as SDR
References VideoPicture::color_primaries, and VideoPicture::color_transfer.
Referenced by CRendererDXVA::Configure().
ManageTextures()
void CRendererBase::ManageTextures ()
References CreateRenderBuffer(), DeleteRenderBuffer(), m_iBufferIndex, m_iBuffersRequired, and m_iNumBuffers.
Referenced by Render().
NeedBuffer()
virtual bool CRendererBase::NeedBuffer (int idx) inline virtual
Reimplemented in CRendererDXVA.
NextBuffer()
int CRendererBase::NextBuffer () const
References m_iBufferIndex, and m_iNumBuffers.
OnCMSConfigChanged()
void CRendererBase::OnCMSConfigChanged (AVColorPrimaries srcPrimaries) protected
References KODI::MEMORY::AlignedFree(), KODI::MEMORY::AlignedMalloc(), CMS_DATA_FMT_RGBA, COutputShader::CreateLUTView(), CColorManager::Get3dLutSize(), CLog::Log(), LOGERROR, m_cmsToken, m_colorManager, m_lutIsLoading, m_lutSize, m_outputShader, m_pLUTView, and success.
Referenced by CheckVideoParameters().
OnOutputReset()
virtual void CRendererBase::OnOutputReset () inline protected virtual
Reimplemented in CRendererHQ.
Referenced by CheckVideoParameters().
OnViewSizeChanged()
virtual void CRendererBase::OnViewSizeChanged () inline protected virtual
Referenced by Render().
ProcessHDR()
void CRendererBase::ProcessHDR (CRenderBuffer * rb) protected
References CRenderBuffer::color_transfer, GetDXGIHDR10MetaData(), HDR_HDR10, HDR_HLG, HDR_NONE_SDR, LOGINFO, m_AutoSwitchHDR, m_HdrType, m_lastHdr10, and CRenderBuffer::primaries.
Referenced by Render().
ReleaseBuffer()
void CRendererBase::ReleaseBuffer (int idx)
References m_renderBuffers.
Render() [1/2]
void CRendererBase::Render (CD3DTexture & target, const CRect & sourceRect, const CRect & destRect, const CRect & viewRect, unsigned flags = 0)
References CheckVideoParameters(), CRenderBuffer::displayMetadata, FinalOutput(), CRectGen< T >::GetQuad(), CRenderBuffer::hasDisplayMetadata, CRenderBuffer::hasLightMetadata, CRectGen< T >::Height(), CRenderBuffer::IsLoaded(), CRenderBuffer::lightMetadata, m_iBufferIndex, m_IntermediateTarget, m_iNumBuffers, m_outputShader, m_renderBuffers, m_toneMapMethod, CVideoSettings::m_ToneMapParam, m_toneMapping, m_videoSettings, m_viewHeight, m_viewWidth, OnViewSizeChanged(), ProcessHDR(), RenderImpl(), UpdateVideoFilters(), CRenderBuffer::UploadBuffer(), and CRectGen< T >::Width().
Render() [2/2]
void CRendererBase::Render (int index, int index2, CD3DTexture & target, const CRect & sourceRect, const CRect & destRect, const CRect & viewRect, unsigned flags)
References index(), m_iBufferIndex, ManageTextures(), and Render().
Referenced by Render().
RenderImpl()
virtual void CRendererBase::RenderImpl (CD3DTexture & target, CRect & sourceRect, CPoint(&) destPoints[4], uint32_t flags) protected pure virtual
Implemented in CRendererDXVA, CRendererShaders, and CRendererSoftware.
Referenced by Render().
ReorderDrawPoints()
void CRendererBase::ReorderDrawPoints (const CRect & destRect, CPoint(&) rotatedPoints[4]) const protected
References m_renderOrientation, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CRendererDXVA::ApplyTransforms(), CRendererShaders::RenderImpl(), and CRendererSoftware::RenderImpl().
SetBufferSize()
void CRendererBase::SetBufferSize (int numBuffers) inline
References m_iBuffersRequired.
Supports() [1/2]
bool CRendererBase::Supports (ERENDERFEATURE feature) const virtual
Reimplemented in CRendererDXVA.
References RENDERFEATURE_BRIGHTNESS, RENDERFEATURE_CONTRAST, RENDERFEATURE_NONLINSTRETCH, RENDERFEATURE_PIXEL_RATIO, RENDERFEATURE_POSTPROCESS, RENDERFEATURE_ROTATION, RENDERFEATURE_STRETCH, RENDERFEATURE_TONEMAP, RENDERFEATURE_VERTICAL_SHIFT, and RENDERFEATURE_ZOOM.
Supports() [2/2]
virtual bool CRendererBase::Supports (ESCALINGMETHOD method) const pure virtual
Implemented in CRendererDXVA, CRendererHQ, CRendererShaders, and CRendererSoftware.
Referenced by CRendererDXVA::Supports().
UpdateVideoFilters()
void CRendererBase::UpdateVideoFilters () protected virtual
Reimplemented in CRendererHQ, and CRendererShaders.
References LOGDEBUG, m_cmsOn, m_ditherDepth, m_lutSize, m_outputShader, m_pLUTView, m_toneMapMethod, m_toneMapping, m_useDithering, and m_useHLGtoPQ.
Referenced by Render().
WantsDoublePass()
virtual bool CRendererBase::WantsDoublePass () inline virtual
Reimplemented in CRendererDXVA.
Member Data Documentation
m_AutoSwitchHDR
bool CRendererBase::m_AutoSwitchHDR = false protected
Referenced by Configure(), ProcessHDR(), and ~CRendererBase().
m_cmsOn
bool CRendererBase::m_cmsOn = false protected
Referenced by CheckVideoParameters(), and UpdateVideoFilters().
m_cmsToken
int CRendererBase::m_cmsToken = -1 protected
Referenced by CheckVideoParameters(), and OnCMSConfigChanged().
m_colorManager
std::unique_ptr<CColorManager> CRendererBase::m_colorManager protected
Referenced by CheckVideoParameters(), CRendererBase(), and OnCMSConfigChanged().
m_ditherDepth
int CRendererBase::m_ditherDepth = 0 protected
Referenced by Configure(), and UpdateVideoFilters().
m_format
AVPixelFormat CRendererBase::m_format = AV_PIX_FMT_NONE protected
Referenced by CRendererDXVA::Configure(), CRendererShaders::Configure(), CRendererSoftware::Configure(), CRendererDXVA::CreateBuffer(), CRendererShaders::CreateBuffer(), CRendererSoftware::CreateBuffer(), and CRendererShaders::UpdateVideoFilters().
m_fps
float CRendererBase::m_fps = 0.0f protected
Referenced by Configure(), GetDebugInfo(), and CRendererHQ::SelectPSVideoFilter().
m_frameIdx
uint64_t CRendererBase::m_frameIdx = 0 protected
Referenced by AddVideoPicture().
m_HdrType
HDR_TYPE CRendererBase::m_HdrType = HDR_TYPE::HDR_INVALID protected
Referenced by ActualRenderAsHDR(), CheckVideoParameters(), Configure(), and ProcessHDR().
m_iBufferIndex
int CRendererBase::m_iBufferIndex = 0 protected
Referenced by CheckVideoParameters(), CRendererDXVA::CheckVideoParameters(), CRendererShaders::CheckVideoParameters(), Configure(), CRendererDXVA::FillBuffersSet(), Flush(), ManageTextures(), CRendererDXVA::NeedBuffer(), NextBuffer(), Render(), Render(), CRendererDXVA::RenderImpl(), CRendererShaders::RenderImpl(), and CRendererSoftware::RenderImpl().
m_iBuffersRequired
int CRendererBase::m_iBuffersRequired = 0 protected
Referenced by ManageTextures(), and SetBufferSize().
m_initialHdrEnabled
bool CRendererBase::m_initialHdrEnabled = false protected
Referenced by Configure(), and ~CRendererBase().
m_IntermediateTarget
CD3DTexture CRendererBase::m_IntermediateTarget protected
Referenced by CreateIntermediateTarget(), GetDebugInfo(), and Render().
m_iNumBuffers
int CRendererBase::m_iNumBuffers = 0 protected
Referenced by Configure(), CRendererDXVA::FillBuffersSet(), Flush(), ManageTextures(), NextBuffer(), and Render().
m_lastHdr10
DXGI_HDR_METADATA_HDR10 CRendererBase::m_lastHdr10 = {} protected
Referenced by Configure(), and ProcessHDR().
m_lutIsLoading
bool CRendererBase::m_lutIsLoading = false protected
Referenced by CheckVideoParameters(), and OnCMSConfigChanged().
m_lutSize
int CRendererBase::m_lutSize = 0 protected
Referenced by OnCMSConfigChanged(), and UpdateVideoFilters().
m_outputShader
std::shared_ptr<COutputShader> CRendererBase::m_outputShader protected
Referenced by CheckVideoParameters(), FinalOutput(), CRendererSoftware::FinalOutput(), GetDebugInfo(), OnCMSConfigChanged(), Render(), CRendererSoftware::RenderImpl(), UpdateVideoFilters(), and CRendererHQ::UpdateVideoFilters().
m_pLUTView
Microsoft::WRL::ComPtr<ID3D11ShaderResourceView> CRendererBase::m_pLUTView protected
Referenced by OnCMSConfigChanged(), and UpdateVideoFilters().
m_renderBuffers
std::map<int, CRenderBuffer*> CRendererBase::m_renderBuffers protected
Referenced by AddVideoPicture(), CheckVideoParameters(), CRendererDXVA::CheckVideoParameters(), CRendererShaders::CheckVideoParameters(), CreateRenderBuffer(), DeleteRenderBuffer(), CRendererDXVA::FillBuffersSet(), GetDebugInfo(), CRendererDXVA::NeedBuffer(), ReleaseBuffer(), Render(), CRendererDXVA::RenderImpl(), CRendererShaders::RenderImpl(), and CRendererSoftware::RenderImpl().
m_renderMethodName
std::string CRendererBase::m_renderMethodName protected
Referenced by CRendererDXVA::CRendererDXVA(), CRendererShaders::CRendererShaders(), CRendererSoftware::CRendererSoftware(), and GetDebugInfo().
m_renderOrientation
unsigned CRendererBase::m_renderOrientation = 0 protected
Referenced by CRendererDXVA::ApplyTransforms(), Configure(), CRendererDXVA::RenderImpl(), ReorderDrawPoints(), CRendererHQ::SelectPSVideoFilter(), and CRendererHQ::Supports().
m_sourceHeight
unsigned CRendererBase::m_sourceHeight = 0 protected
Referenced by CRendererDXVA::CheckVideoParameters(), Configure(), CRendererShaders::Configure(), CRendererSoftware::Configure(), CRendererDXVA::CreateBuffer(), CRendererShaders::CreateBuffer(), CRendererSoftware::CreateBuffer(), GetDebugInfo(), CRendererHQ::SelectPSVideoFilter(), and CRendererHQ::Supports().
m_sourceWidth
unsigned CRendererBase::m_sourceWidth = 0 protected
Referenced by CRendererDXVA::CheckVideoParameters(), Configure(), CRendererShaders::Configure(), CRendererSoftware::Configure(), CRendererDXVA::CreateBuffer(), CRendererShaders::CreateBuffer(), CRendererSoftware::CreateBuffer(), GetDebugInfo(), CRendererHQ::SelectPSVideoFilter(), and CRendererHQ::Supports().
m_toneMapMethod
ETONEMAPMETHOD CRendererBase::m_toneMapMethod = VS_TONEMAPMETHOD_OFF protected
Referenced by CheckVideoParameters(), Render(), and UpdateVideoFilters().
m_toneMapping
bool CRendererBase::m_toneMapping = false protected
Referenced by CheckVideoParameters(), Render(), and UpdateVideoFilters().
m_useDithering
bool CRendererBase::m_useDithering = false protected
Referenced by Configure(), and UpdateVideoFilters().
m_useHLGtoPQ
bool CRendererBase::m_useHLGtoPQ = false protected
Referenced by CheckVideoParameters(), Configure(), and UpdateVideoFilters().
m_videoSettings
CVideoSettings& CRendererBase::m_videoSettings protected
Referenced by CheckVideoParameters(), CRendererHQ::CheckVideoParameters(), CRendererSoftware::FinalOutput(), Render(), CRendererDXVA::RenderImpl(), and CRendererShaders::RenderImpl().
m_viewHeight
unsigned CRendererBase::m_viewHeight = 0 protected
Referenced by CRendererDXVA::CheckVideoParameters(), Render(), CRendererHQ::SelectPSVideoFilter(), and CRendererHQ::Supports().
m_viewWidth
unsigned CRendererBase::m_viewWidth = 0 protected
Referenced by CRendererDXVA::CheckVideoParameters(), Render(), CRendererHQ::SelectPSVideoFilter(), and CRendererHQ::Supports().
The documentation for this class was generated from the following files:
RendererBase.h
RendererBase.cpp