Kodi Documentation: TestGUIControlFactory.cpp File Reference
TestGUIControlFactory.cpp File Reference
#include "GUIInfoManager.h"
#include "LangInfo.h"
#include "guilib/GUIAction.h"
#include "guilib/GUIColorManager.h"
#include "guilib/GUIControlFactory.h"
#include "guilib/GUIFont.h"
#include "guilib/GUILabelControl.h"
#include "guilib/GUITexture.h"
#include "guilib/LocalizeStrings.h"
#include "guilib/guiinfo/GUIInfoLabel.h"
#include "utils/SystemInfo.h"
#include "utils/XBMCTinyXML.h"
#include <limits>
#include <string>
#include <gtest/gtest.h>
Classes
class CGFTestable
class anonymous_namespace{TestGUIControlFactory.cpp}::CGUITestColorManager
class anonymous_namespace{TestGUIControlFactory.cpp}::CGUITestComponent
struct anonymous_namespace{TestGUIControlFactory.cpp}::ActionsTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetActions
struct anonymous_namespace{TestGUIControlFactory.cpp}::AlignmentTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetAlignment
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetAlignmentY
struct anonymous_namespace{TestGUIControlFactory.cpp}::AspectRatioTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestAspectRatio
struct anonymous_namespace{TestGUIControlFactory.cpp}::ColorTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetColor
struct anonymous_namespace{TestGUIControlFactory.cpp}::ConditionalVisibilityTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestConditionalVisibility
struct anonymous_namespace{TestGUIControlFactory.cpp}::DimensionTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetDimension
struct anonymous_namespace{TestGUIControlFactory.cpp}::DimensionsTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetDimensions
struct anonymous_namespace{TestGUIControlFactory.cpp}::RangeTest< T >
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetFloatRange
struct anonymous_namespace{TestGUIControlFactory.cpp}::HitRectTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetHitRect
struct anonymous_namespace{TestGUIControlFactory.cpp}::InfoLabelTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetInfoLabel
struct anonymous_namespace{TestGUIControlFactory.cpp}::InfoLabelsTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetInfoLabels
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetIntRange
struct anonymous_namespace{TestGUIControlFactory.cpp}::MovingSpeedTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetMovingSpeed
struct anonymous_namespace{TestGUIControlFactory.cpp}::PositionTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetPosition
struct anonymous_namespace{TestGUIControlFactory.cpp}::ScrollerTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetScroller
struct anonymous_namespace{TestGUIControlFactory.cpp}::StringTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetString
struct anonymous_namespace{TestGUIControlFactory.cpp}::TextureTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetTexture
struct anonymous_namespace{TestGUIControlFactory.cpp}::TypeTest
class anonymous_namespace{TestGUIControlFactory.cpp}::TestGetType
Namespaces
namespace anonymous_namespace{TestGUIControlFactory.cpp}
Functions
TEST_P (TestGetActions, GetActions)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetActions, testing::ValuesIn(ActionsTests))
TEST_P (TestGetAlignment, GetAlignment)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetAlignment, testing::ValuesIn(AlignmentTests))
TEST_P (TestGetAlignmentY, GetAlignmentY)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetAlignmentY, testing::ValuesIn(AlignmentYTests))
TEST_P (TestAspectRatio, GetAspectRatio)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestAspectRatio, testing::ValuesIn(AspectRatioTests))
TEST_P (TestGetColor, GetColor)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetColor, testing::ValuesIn(ColorTests))
TEST_P (TestGetDimension, GetDimension)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetDimension, testing::ValuesIn(DimensionTests))
TEST_P (TestGetDimensions, GetDimensions)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetDimensions, testing::ValuesIn(DimensionsTests))
TEST_P (TestGetFloatRange, GetFloatRange)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetFloatRange, testing::ValuesIn(FloatRangeTests))
TEST_P (TestGetHitRect, GetHitRect)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetHitRect, testing::ValuesIn(HitRectTests))
TEST_P (TestGetInfoLabel, GetInfoLabel)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetInfoLabel, testing::ValuesIn(InfoLabelTests))
TEST_P (TestGetInfoLabels, GetInfoLabels)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetInfoLabels, testing::ValuesIn(InfoLabelsTests))
TEST_P (TestGetIntRange, GetIntRange)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetIntRange, testing::ValuesIn(IntRangeTests))
TEST_P (TestGetMovingSpeed, GetMovingSpeed)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetMovingSpeed, testing::ValuesIn(MovingSpeedTests))
TEST_P (TestGetPosition, GetPosition)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetPosition, testing::ValuesIn(PositionTests))
TEST_P (TestGetScroller, GetScroller)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetScroller, testing::ValuesIn(ScrollerTests))
TEST_P (TestGetString, GetString)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetString, testing::ValuesIn(StringTests))
TEST_P (TestGetTexture, GetTexture)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetTexture, testing::ValuesIn(TextureTests))
TEST_P (TestGetType, GetType)
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory, TestGetType, testing::ValuesIn(TypeTests))
Variables
const auto anonymous_namespace{TestGUIControlFactory.cpp}::ActionsTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::AlignmentTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::AlignmentYTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::AspectRatioTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::ColorTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::ConditionalVisibilityTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::DimensionTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::DimensionsTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::FloatRangeTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::HitRectTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::InfoLabelTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::InfoLabelsTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::IntRangeTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::MovingSpeedTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::PositionTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::ScrollerTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::StringTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::TextureTests
const auto anonymous_namespace{TestGUIControlFactory.cpp}::TypeTests
Function Documentation
INSTANTIATE_TEST_SUITE_P() [1/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestAspectRatio , testing::ValuesIn(AspectRatioTests))
INSTANTIATE_TEST_SUITE_P() [2/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetActions , testing::ValuesIn(ActionsTests))
INSTANTIATE_TEST_SUITE_P() [3/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetAlignment , testing::ValuesIn(AlignmentTests))
INSTANTIATE_TEST_SUITE_P() [4/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetAlignmentY , testing::ValuesIn(AlignmentYTests))
INSTANTIATE_TEST_SUITE_P() [5/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetColor , testing::ValuesIn(ColorTests))
INSTANTIATE_TEST_SUITE_P() [6/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetDimension , testing::ValuesIn(DimensionTests))
INSTANTIATE_TEST_SUITE_P() [7/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetDimensions , testing::ValuesIn(DimensionsTests))
INSTANTIATE_TEST_SUITE_P() [8/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetFloatRange , testing::ValuesIn(FloatRangeTests))
INSTANTIATE_TEST_SUITE_P() [9/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetHitRect , testing::ValuesIn(HitRectTests))
INSTANTIATE_TEST_SUITE_P() [10/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetInfoLabel , testing::ValuesIn(InfoLabelTests))
INSTANTIATE_TEST_SUITE_P() [11/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetInfoLabels , testing::ValuesIn(InfoLabelsTests))
INSTANTIATE_TEST_SUITE_P() [12/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetIntRange , testing::ValuesIn(IntRangeTests))
INSTANTIATE_TEST_SUITE_P() [13/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetMovingSpeed , testing::ValuesIn(MovingSpeedTests))
INSTANTIATE_TEST_SUITE_P() [14/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetPosition , testing::ValuesIn(PositionTests))
INSTANTIATE_TEST_SUITE_P() [15/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetScroller , testing::ValuesIn(ScrollerTests))
INSTANTIATE_TEST_SUITE_P() [16/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetString , testing::ValuesIn(StringTests))
INSTANTIATE_TEST_SUITE_P() [17/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetTexture , testing::ValuesIn(TextureTests))
INSTANTIATE_TEST_SUITE_P() [18/18]
INSTANTIATE_TEST_SUITE_P (TestGUIControlFactory , TestGetType , testing::ValuesIn(TypeTests))
TEST_P() [1/18]
TEST_P (TestAspectRatio , GetAspectRatio)
References CAspectRatio::align, EXPECT_EQ(), CGUIControlFactory::GetAspectRatio(), CXBMCTinyXML::Parse(), CAspectRatio::ratio, and CAspectRatio::scaleDiffuse.
TEST_P() [2/18]
TEST_P (TestGetActions , GetActions)
References actions, CGUIAction::Append(), EXPECT_EQ(), CGUIControlFactory::GetActions(), and CXBMCTinyXML::Parse().
TEST_P() [3/18]
TEST_P (TestGetAlignment , GetAlignment)
References EXPECT_EQ(), CGUIControlFactory::GetAlignment(), and CXBMCTinyXML::Parse().
TEST_P() [4/18]
TEST_P (TestGetAlignmentY , GetAlignmentY)
References EXPECT_EQ(), CGUIControlFactory::GetAlignmentY(), and CXBMCTinyXML::Parse().
TEST_P() [5/18]
TEST_P (TestGetColor , GetColor)
References EXPECT_EQ(), CGUIControlFactory::GetColor(), CXBMCTinyXML::Parse(), and value.
TEST_P() [6/18]
TEST_P (TestGetDimension , GetDimension)
References EXPECT_EQ(), CGFTestable::GetDimension(), min, CXBMCTinyXML::Parse(), and value.
TEST_P() [7/18]
TEST_P (TestGetDimensions , GetDimensions)
References EXPECT_EQ(), CGFTestable::GetDimensions(), left, and CXBMCTinyXML::Parse().
TEST_P() [8/18]
TEST_P (TestGetFloatRange , GetFloatRange)
References EXPECT_EQ(), CGFTestable::GetFloatRange(), max, min, and CXBMCTinyXML::Parse().
TEST_P() [9/18]
TEST_P (TestGetHitRect , GetHitRect)
References EXPECT_EQ(), CGUIControlFactory::GetHitRect(), CXBMCTinyXML::Parse(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
TEST_P() [10/18]
TEST_P (TestGetInfoLabel , GetInfoLabel)
References INFO::DEFAULT_CONTEXT, EXPECT_EQ(), g_langInfo, g_localizeStrings, KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetFallback(), CGUIControlFactory::GetInfoLabelFromElement(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), label, CLocalizeStrings::Load(), and CXBMCTinyXML::Parse().
TEST_P() [11/18]
TEST_P (TestGetInfoLabels , GetInfoLabels)
References INFO::DEFAULT_CONTEXT, EXPECT_EQ(), g_langInfo, g_localizeStrings, CGUIControlFactory::GetInfoLabels(), CLocalizeStrings::Load(), and CXBMCTinyXML::Parse().
TEST_P() [12/18]
TEST_P (TestGetIntRange , GetIntRange)
References EXPECT_EQ(), CGFTestable::GetIntRange(), max, min, and CXBMCTinyXML::Parse().
TEST_P() [13/18]
TEST_P (TestGetMovingSpeed , GetMovingSpeed)
References EXPECT_EQ(), CGFTestable::GetMovingSpeedConfig(), and CXBMCTinyXML::Parse().
TEST_P() [14/18]
TEST_P (TestGetPosition , GetPosition)
References EXPECT_EQ(), CGFTestable::GetPosition(), and CXBMCTinyXML::Parse().
TEST_P() [15/18]
TEST_P (TestGetScroller , GetScroller)
References EXPECT_EQ(), EXPECT_TRUE(), CGUIControlFactory::GetScroller(), CXBMCTinyXML::Parse(), value, and values.
TEST_P() [16/18]
TEST_P (TestGetString , GetString)
References EXPECT_EQ(), g_langInfo, g_localizeStrings, CGFTestable::GetString(), CLocalizeStrings::Load(), CXBMCTinyXML::Parse(), and value.
TEST_P() [17/18]
TEST_P (TestGetTexture , GetTexture)
References EXPECT_EQ(), CGUIControlFactory::GetTexture(), and CXBMCTinyXML::Parse().
TEST_P() [18/18]
TEST_P (TestGetType , GetType)
References EXPECT_EQ(), CGFTestable::GetType(), and CXBMCTinyXML::Parse().