Kodi Documentation: WSDiscovery::CWSDiscoveryWindows Class Reference
WSDiscovery::CWSDiscoveryWindows Class Reference
#include <WSDiscoveryWin32.h>
Public Member Functions
CWSDiscoveryWindows ()=default
~CWSDiscoveryWindows () override
bool StartServices () override
bool StopServices () override
bool IsRunning () override
bool ThereAreServers ()
std::vector< std::wstring > GetServersIPs ()
Public Member Functions inherited from WSDiscovery::IWSDiscovery
virtual ~IWSDiscovery ()=default
Static Public Member Functions
static std::wstring ResolveHostName (const std::wstring &serverIP)
Static Public Member Functions inherited from WSDiscovery::IWSDiscovery
static std::unique_ptr< IWSDiscovery > GetInstance ()
Private Attributes
bool m_initialized = false
IWSDiscoveryProvider * m_provider = nullptr
CClientNotificationSink * m_sink = nullptr
Constructor & Destructor Documentation
CWSDiscoveryWindows()
WSDiscovery::CWSDiscoveryWindows::CWSDiscoveryWindows () default
~CWSDiscoveryWindows()
WSDiscovery::CWSDiscoveryWindows::~CWSDiscoveryWindows () override
References StopServices().
Member Function Documentation
GetServersIPs()
std::vector< std::wstring > WSDiscovery::CWSDiscoveryWindows::GetServersIPs ()
References WSDiscovery::CClientNotificationSink::GetServersIPs(), and m_sink.
Referenced by localGetServers().
IsRunning()
bool WSDiscovery::CWSDiscoveryWindows::IsRunning () override virtual
Implements WSDiscovery::IWSDiscovery.
References m_initialized.
Referenced by localGetServers().
ResolveHostName()
std::wstring WSDiscovery::CWSDiscoveryWindows::ResolveHostName (const std::wstring & serverIP) static
References LOGERROR, LOGWARNING, and KODI::PLATFORM::WINDOWS::ToW().
Referenced by localGetServers().
StartServices()
bool WSDiscovery::CWSDiscoveryWindows::StartServices () override virtual
Implements WSDiscovery::IWSDiscovery.
References WSDiscovery::CClientNotificationSink::Create(), CLog::Log(), LOGERROR, LOGINFO, m_initialized, m_provider, m_sink, and StopServices().
StopServices()
bool WSDiscovery::CWSDiscoveryWindows::StopServices () override virtual
Implements WSDiscovery::IWSDiscovery.
References CLog::Log(), LOGINFO, m_initialized, m_provider, m_sink, and WSDiscovery::CClientNotificationSink::Release().
Referenced by StartServices(), and ~CWSDiscoveryWindows().
ThereAreServers()
bool WSDiscovery::CWSDiscoveryWindows::ThereAreServers ()
References m_sink, and WSDiscovery::CClientNotificationSink::ThereAreServers().
Referenced by localGetServers().
Member Data Documentation
m_initialized
bool WSDiscovery::CWSDiscoveryWindows::m_initialized = false private
Referenced by IsRunning(), StartServices(), and StopServices().
m_provider
IWSDiscoveryProvider* WSDiscovery::CWSDiscoveryWindows::m_provider = nullptr private
Referenced by StartServices(), and StopServices().
m_sink
CClientNotificationSink* WSDiscovery::CWSDiscoveryWindows::m_sink = nullptr private
Referenced by GetServersIPs(), StartServices(), StopServices(), and ThereAreServers().
The documentation for this class was generated from the following files:
WSDiscoveryWin32.h
WSDiscoveryWin32.cpp