Kodi Documentation: TestNetworkFileItemClassify.cpp File Reference
TestNetworkFileItemClassify.cpp File Reference
#include "FileItem.h"
#include "URL.h"
#include "filesystem/StackDirectory.h"
#include "network/NetworkFileItemClassify.h"
#include <array>
#include <string>
#include <gtest/gtest.h>
Classes
struct anonymous_namespace{TestNetworkFileItemClassify.cpp}::SimpleDefinition
class InternetStreamTest
class RemoteTest
class StreamedFilesystemTest
Namespaces
namespace anonymous_namespace{TestNetworkFileItemClassify.cpp}
Functions
TEST_P (InternetStreamTest, IsInternetStream)
INSTANTIATE_TEST_SUITE_P (TestNetworkFileItemClassify, InternetStreamTest, testing::ValuesIn(inetstream_tests))
TEST (TestNetworkWorkFileItemClassify, InternetStreamStacks)
TEST_P (RemoteTest, IsRemote)
INSTANTIATE_TEST_SUITE_P (TestNetworkFileItemClassify, RemoteTest, testing::ValuesIn(remote_tests))
TEST_P (StreamedFilesystemTest, IsStreamedFilesystem)
INSTANTIATE_TEST_SUITE_P (TestNetworkFileItemClassify, StreamedFilesystemTest, testing::ValuesIn(streamedfs_tests))
TEST (TestNetworkWorkFileItemClassify, StreamedFilesystemStacks)
Variables
const auto inetstream_tests
const auto remote_tests
const auto streamedfs_tests
Function Documentation
INSTANTIATE_TEST_SUITE_P() [1/3]
INSTANTIATE_TEST_SUITE_P (TestNetworkFileItemClassify , InternetStreamTest , testing::ValuesIn(inetstream_tests))
INSTANTIATE_TEST_SUITE_P() [2/3]
INSTANTIATE_TEST_SUITE_P (TestNetworkFileItemClassify , RemoteTest , testing::ValuesIn(remote_tests))
INSTANTIATE_TEST_SUITE_P() [3/3]
INSTANTIATE_TEST_SUITE_P (TestNetworkFileItemClassify , StreamedFilesystemTest , testing::ValuesIn(streamedfs_tests))
TEST() [1/2]
TEST (TestNetworkWorkFileItemClassify , InternetStreamStacks)
References XFILE::CStackDirectory::ConstructStackPath(), EXPECT_TRUE(), KODI::NETWORK::IsInternetStream(), and CGUIListItem::SetProperty().
TEST() [2/2]
TEST (TestNetworkWorkFileItemClassify , StreamedFilesystemStacks)
References XFILE::CStackDirectory::ConstructStackPath(), EXPECT_TRUE(), and KODI::NETWORK::IsStreamedFilesystem().
TEST_P() [1/3]
TEST_P (InternetStreamTest , IsInternetStream)
References EXPECT_EQ(), and KODI::NETWORK::IsInternetStream().
TEST_P() [2/3]
TEST_P (RemoteTest , IsRemote)
References EXPECT_EQ(), and KODI::NETWORK::IsRemote().
TEST_P() [3/3]
TEST_P (StreamedFilesystemTest , IsStreamedFilesystem)
References EXPECT_EQ(), and KODI::NETWORK::IsStreamedFilesystem().
Variable Documentation
inetstream_tests
const auto inetstream_tests
remote_tests
const auto remote_tests
Initial value:
= std::array{
    SimpleDefinition{"cdda://1", false, false},
    SimpleDefinition{"cdda://1", true, false},
    SimpleDefinition{"iso9660://some.file", false, false},
    SimpleDefinition{"cdda://some.file", true, false},
    SimpleDefinition{"special://home/foo.xml", false, false},
    SimpleDefinition{"special://home", true, false},
    SimpleDefinition{"zip://" + CURL::Encode("/home/foo/bar.zip"), true, false},
    SimpleDefinition{"zip://" + CURL::Encode("https://some.where/yo.zip"), true, true},
    SimpleDefinition{"addons://plugins", true, false},
    SimpleDefinition{"sources://music", true, false},
    SimpleDefinition{"videodb://1/2", true, false},
    SimpleDefinition{"musicdb://1/2", true, false},
    SimpleDefinition{"library://movies/titles", true, false},
    SimpleDefinition{"plugin://plugin.video.yo", true, false},
    SimpleDefinition{"androidapp://cool.app", true, false},
    SimpleDefinition{"/home/foo/bar", true, false},
    SimpleDefinition{"https://127.0.0.1/bar", true, false},
    SimpleDefinition{"https://some.where/bar", true, true},
}
streamedfs_tests
const auto streamedfs_tests
Initial value:
= std::array{
    SimpleDefinition{"/home/user/test.disc", false, false},
    SimpleDefinition{"/home/user/test.disc", true, false},
    SimpleDefinition{"http://some.where/foo", false, true},
    SimpleDefinition{"http://some.where/foo", true, true},
    SimpleDefinition{"https://some.where/foo", false, true},
    SimpleDefinition{"https://some.where/foo", true, true},
    SimpleDefinition{"ftp://some.where/foo", false, true},
    SimpleDefinition{"ftp://some.where/foo", true, true},
    SimpleDefinition{"sftp://some.where/foo", false, true},
    SimpleDefinition{"sftp://some.where/foo", true, true},
    SimpleDefinition{"ssh://some.where/foo", false, true},
    SimpleDefinition{"ssh://some.where/foo", true, true},
    SimpleDefinition{"ssh://some.where/foo", true, true},
}