Kodi Documentation: KODI::RETRO::IRenderBufferPool Class Reference
KODI::RETRO::IRenderBufferPool Class Reference abstract
#include <IRenderBufferPool.h>
Public Member Functions
virtual ~IRenderBufferPool ()=default
virtual void RegisterRenderer (CRPBaseRenderer *renderer)=0
virtual void UnregisterRenderer (CRPBaseRenderer *renderer)=0
virtual bool HasVisibleRenderer () const =0
virtual bool Configure (AVPixelFormat format)=0
virtual bool IsConfigured () const =0
virtual bool IsCompatible (const CRenderVideoSettings &renderSettings) const =0
virtual IRenderBuffer * GetBuffer (unsigned int width, unsigned int height)=0
Get a free buffer from the pool, sets ref count to 1.
virtual void Return (IRenderBuffer *buffer)=0
Called by buffer when ref count goes to zero.
virtual void Prime (unsigned int width, unsigned int height)=0
virtual void Flush ()=0
virtual DataAccess GetMemoryAccess () const
virtual DataAlignment GetMemoryAlignment () const
virtual std::shared_ptr< IRenderBufferPool > GetPtr ()
Call in GetBuffer() before returning buffer to caller.
Constructor & Destructor Documentation
~IRenderBufferPool()
virtual KODI::RETRO::IRenderBufferPool::~IRenderBufferPool () virtual default
Member Function Documentation
Configure()
virtual bool KODI::RETRO::IRenderBufferPool::Configure (AVPixelFormat format) pure virtual
Implemented in KODI::RETRO::CBaseRenderBufferPool.
Flush()
virtual void KODI::RETRO::IRenderBufferPool::Flush () pure virtual
Implemented in KODI::RETRO::CBaseRenderBufferPool.
GetBuffer()
virtual IRenderBuffer * KODI::RETRO::IRenderBufferPool::GetBuffer (unsigned int width, unsigned int height) pure virtual
Get a free buffer from the pool, sets ref count to 1.
Parameters
width The horizontal pixel count of the buffer
height The vertical pixel could of the buffer
Returns
The allocated buffer, or nullptr on failure
Implemented in KODI::RETRO::CBaseRenderBufferPool.
Referenced by KODI::RETRO::CRPRenderManager::CreateFromCache().
GetMemoryAccess()
virtual DataAccess KODI::RETRO::IRenderBufferPool::GetMemoryAccess () const inline virtual
References KODI::RETRO::READ_WRITE.
GetMemoryAlignment()
virtual DataAlignment KODI::RETRO::IRenderBufferPool::GetMemoryAlignment () const inline virtual
References KODI::RETRO::DATA_UNALIGNED.
GetPtr()
virtual std::shared_ptr< IRenderBufferPool > KODI::RETRO::IRenderBufferPool::GetPtr () inline virtual
Call in GetBuffer() before returning buffer to caller.
Referenced by KODI::RETRO::CBaseRenderBufferPool::GetBuffer().
HasVisibleRenderer()
virtual bool KODI::RETRO::IRenderBufferPool::HasVisibleRenderer () const pure virtual
Implemented in KODI::RETRO::CBaseRenderBufferPool.
IsCompatible()
virtual bool KODI::RETRO::IRenderBufferPool::IsCompatible (const CRenderVideoSettings & renderSettings) const pure virtual
Implemented in KODI::RETRO::CRenderBufferPoolDMA, KODI::RETRO::CRenderBufferPoolOpenGL, KODI::RETRO::CRenderBufferPoolOpenGLES, KODI::RETRO::CRenderBufferPoolGuiTexture, and KODI::RETRO::CWinRenderBufferPool.
Referenced by KODI::RETRO::CRPRenderManager::GetRendererForPool().
IsConfigured()
virtual bool KODI::RETRO::IRenderBufferPool::IsConfigured () const pure virtual
Implemented in KODI::RETRO::CBaseRenderBufferPool.
Prime()
virtual void KODI::RETRO::IRenderBufferPool::Prime (unsigned int width, unsigned int height) pure virtual
Implemented in KODI::RETRO::CBaseRenderBufferPool.
RegisterRenderer()
virtual void KODI::RETRO::IRenderBufferPool::RegisterRenderer (CRPBaseRenderer * renderer) pure virtual
Implemented in KODI::RETRO::CBaseRenderBufferPool.
Return()
virtual void KODI::RETRO::IRenderBufferPool::Return (IRenderBuffer * buffer) pure virtual
Called by buffer when ref count goes to zero.
Parameters
buffer A fully dereferenced buffer
Implemented in KODI::RETRO::CBaseRenderBufferPool.
UnregisterRenderer()
virtual void KODI::RETRO::IRenderBufferPool::UnregisterRenderer (CRPBaseRenderer * renderer) pure virtual
Implemented in KODI::RETRO::CBaseRenderBufferPool.
The documentation for this class was generated from the following file:
IRenderBufferPool.h