Kodi Documentation: IProgressCallback Class Reference
IProgressCallback Class Reference abstract
#include <IProgressCallback.h>
Public Member Functions
virtual ~IProgressCallback ()=default
virtual void SetProgressMax (int max)=0
virtual void SetProgressAdvance (int nSteps=1)=0
virtual bool Abort ()=0
Constructor & Destructor Documentation
~IProgressCallback()
virtual IProgressCallback::~IProgressCallback () virtual default
Member Function Documentation
Abort()
virtual bool IProgressCallback::Abort () pure virtual
Implemented in CGUIDialogProgress.
Referenced by CBackgroundInfoLoader::Run().
SetProgressAdvance()
virtual void IProgressCallback::SetProgressAdvance (int nSteps = 1) pure virtual
Implemented in CGUIDialogProgress.
Referenced by MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), and CPictureInfoLoader::LoadItemLookup().
SetProgressMax()
virtual void IProgressCallback::SetProgressMax (int max) pure virtual
Implemented in CGUIDialogProgress.
Referenced by MUSIC_INFO::CMusicInfoLoader::OnLoaderStart(), and CPictureInfoLoader::OnLoaderStart().
The documentation for this class was generated from the following file:
IProgressCallback.h