Kodi Documentation: CBusyWaiter Class Reference
CBusyWaiter Class Reference
Public Member Functions
CBusyWaiter (IRunnable *runnable)
~CBusyWaiter () override
bool Wait (unsigned int displaytime, bool allowCancel)
void Process () override
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Attributes
std::shared_ptr< CEvent > m_done
IRunnable * m_runnable
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CBusyWaiter()
CBusyWaiter::CBusyWaiter (IRunnable * runnable) inline explicit
~CBusyWaiter()
CBusyWaiter::~CBusyWaiter () inline override
References CThread::StopThread().
Member Function Documentation
Process()
void CBusyWaiter::Process (void) inline override virtual
Reimplemented from CThread.
References m_done, and CThread::Process().
Wait()
bool CBusyWaiter::Wait (unsigned int displaytime, bool allowCancel) inline
References IRunnable::Cancel(), CThread::Create(), end(), m_done, m_runnable, and CGUIDialogBusy::WaitOnEvent().
Member Data Documentation
m_done
std::shared_ptr<CEvent> CBusyWaiter::m_done private
Referenced by Process(), and Wait().
m_runnable
IRunnable* CBusyWaiter::m_runnable private
Referenced by Wait().
The documentation for this class was generated from the following file:
GUIDialogBusy.cpp