Kodi Documentation: ADDON::CScraper Class Reference
ADDON::CScraper Class Reference
#include <Scraper.h>
Public Member Functions
CScraper (const AddonInfoPtr &addonInfo, AddonType addonType)
bool SetPathSettings (CONTENT_TYPE content, const std::string &xml)
Set the scraper settings for a particular path from an XML string Loads the default and user settings (if not already loaded) and, if the given XML string is non-empty, overrides the user settings with the XML.
std::string GetPathSettings ()
Get the scraper settings for a particular path in the form of an XML string Loads the default and user settings (if not already loaded) and returns the user settings in the form or an XML string.
void ClearCache ()
Clear any previously cached results for this scraper Any previously cached files are cleared if they have been cached for longer than the specified cachepersistence.
CONTENT_TYPE Content () const
bool RequiresSettings () const
bool Supports (const CONTENT_TYPE &content) const
bool IsInUse () const override
bool IsNoop ()
bool IsPython () const
CScraperUrl NfoUrl (const std::string &sNfoContent)
CScraperUrl ResolveIDToUrl (const std::string &externalID)
Resolve an external ID (e.g. MusicBrainz IDs) to a URL using scrapers If we have an ID in hand, e.g. MusicBrainz IDs or TheTVDB Season IDs we can get directly to a URL instead of searching by name and choosing from the search results. The correct scraper type should be used to get the right URL for a given ID, so we can differentiate albums, artists, TV Seasons, etc.
std::vector< CScraperUrl > FindMovie (XFILE::CCurlFile &fcurl, const std::string &movieTitle, int movieYear, bool fFirst)
std::vector< MUSIC_GRABBER::CMusicAlbumInfo > FindAlbum (XFILE::CCurlFile &fcurl, const std::string &sAlbum, const std::string &sArtist="")
std::vector< MUSIC_GRABBER::CMusicArtistInfo > FindArtist (XFILE::CCurlFile &fcurl, const std::string &sArtist)
KODI::VIDEO::EPISODELIST GetEpisodeList (XFILE::CCurlFile &fcurl, const CScraperUrl &scurl)
bool GetVideoDetails (XFILE::CCurlFile &fcurl, const std::unordered_map< std::string, std::string > &uniqueIDs, const CScraperUrl &scurl, bool fMovie, CVideoInfoTag &video)
bool GetAlbumDetails (XFILE::CCurlFile &fcurl, const CScraperUrl &scurl, CAlbum &album)
bool GetArtistDetails (XFILE::CCurlFile &fcurl, const CScraperUrl &scurl, const std::string &sSearch, CArtist &artist)
bool GetArtwork (XFILE::CCurlFile &fcurl, CVideoInfoTag &details)
Public Member Functions inherited from ADDON::CAddon
CAddon (const AddonInfoPtr &addonInfo, AddonType addonType)
~CAddon () override=default
AddonType MainType () const override
To get the main type of this addon.
AddonType Type () const override
To get the on this CAddon class processed addon type.
bool HasType (AddonType type) const override
To check complete addon (not only this) contains a type.
bool HasMainType (AddonType type) const override
To check complete addon (not only this) has a specific type defined in its first extension point including the provided subcontent e.g. video or audio.
const CAddonType * Type (AddonType type) const
The get for given addon type information and extension data.
std::string ID () const override
std::string Name () const override
bool IsBinary () const override
CAddonVersion Version () const override
CAddonVersion MinVersion () const override
std::string Summary () const override
std::string Description () const override
std::string Path () const override
std::string Profile () const override
std::string LibPath () const override
std::string Author () const override
std::string ChangeLog () const override
std::string Icon () const override
ArtMap Art () const override
std::vector< std::string > Screenshots () const override
std::string Disclaimer () const override
AddonLifecycleState LifecycleState () const override
std::string LifecycleStateDescription () const override
CDateTime InstallDate () const override
CDateTime LastUpdated () const override
CDateTime LastUsed () const override
std::string Origin () const override
std::string OriginName () const override
uint64_t PackageSize () const override
const InfoMap & ExtraInfo () const override
const std::vector< DependencyInfo > & GetDependencies () const override
std::string FanArt () const override
bool SupportsMultipleInstances () const override
Check add-on for support from independent work instances.
AddonInstanceSupport InstanceUseType () const override
Return the used instance path type of the add-on type.
std::vector< AddonInstanceId > GetKnownInstanceIds () const override
Gives active, independently working instance identifiers for this add-on.
bool SupportsInstanceSettings () const override
Check whether the add-on supports individual settings per add-on instance.
bool DeleteInstanceSettings (AddonInstanceId instance) override
Delete selected instance settings from storage.
bool CanHaveAddonOrInstanceSettings () override
Check whether this add-on can be configured by the user.
bool HasSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Check whether this add-on can be configured by the user.
bool HasUserSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Check whether the user has configured this add-on or not.
bool SaveSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Save any user configured settings.
void UpdateSetting (const std::string &key, const std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new value.
bool UpdateSettingBool (const std::string &key, bool value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new boolean value.
bool UpdateSettingInt (const std::string &key, int value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new integer value.
bool UpdateSettingNumber (const std::string &key, double value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new number value.
bool UpdateSettingString (const std::string &key, const std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new string value.
std::string GetSetting (const std::string &key, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value.
bool GetSettingBool (const std::string &key, bool &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as boolean.
bool GetSettingInt (const std::string &key, int &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as integer.
bool GetSettingNumber (const std::string &key, double &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as number.
bool GetSettingString (const std::string &key, std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as string.
std::shared_ptr< CAddonSettings > GetSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
CAddonVersion GetDependencyVersion (const std::string &dependencyID) const override
get the required version of a dependency.
bool MeetsVersion (const CAddonVersion &versionMin, const CAddonVersion &version) const override
return whether or not this addon satisfies the given version requirements
bool ReloadSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
void ResetSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
AddonPtr GetRunningInstance () const override
retrieve the running instance of an add-on if it persists while running.
void OnPreInstall () override
void OnPostInstall (bool update, bool modal) override
void OnPreUnInstall () override
void OnPostUnInstall () override
Public Member Functions inherited from ADDON::IAddon
virtual ~IAddon ()=default
Private Member Functions
CScraper (const CScraper &rhs)=delete
CScraper & operator= (const CScraper &)=delete
CScraper (CScraper &&)=delete
CScraper & operator= (CScraper &&)=delete
std::string SearchStringEncoding () const
std::string GetPathSettingsAsJSON ()
Get the scraper settings for a particular path in the form of a JSON string Loads the default and user settings (if not already loaded) and returns the user settings in the form of an JSON string. It is used in Python scrapers.
bool Load ()
std::vector< std::string > Run (const std::string &function, const CScraperUrl &url, XFILE::CCurlFile &http, const std::vector< std::string > *extras=nullptr)
std::vector< std::string > RunNoThrow (const std::string &function, const CScraperUrl &url, XFILE::CCurlFile &http, const std::vector< std::string > *extras=nullptr)
std::string InternalRun (const std::string &function, const CScraperUrl &url, XFILE::CCurlFile &http, const std::vector< std::string > *extras)
Private Attributes
bool m_fLoaded = false
bool m_isPython = false
bool m_requiressettings = false
CDateTimeSpan m_persistence
CONTENT_TYPE m_pathContent = CONTENT_NONE
CScraperParser m_parser
Additional Inherited Members
Protected Member Functions inherited from ADDON::CAddon
virtual bool SettingsInitialized (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether or not the settings have been initialized.
virtual bool SettingsLoaded (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether or not the settings have been loaded.
bool LoadSettings (bool bForce, bool loadUserSettings, AddonInstanceId id=ADDON_SETTINGS_ID)
Load the default settings and override these with any previously configured user settings.
virtual bool LoadUserSettings (AddonInstanceId id=ADDON_SETTINGS_ID)
Load the user settings.
virtual bool HasSettingsToSave (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether there are settings to be saved.
virtual bool SettingsFromXML (const CXBMCTinyXML &doc, bool loadDefaults, AddonInstanceId id=ADDON_SETTINGS_ID)
Parse settings from an XML document.
virtual bool SettingsToXML (CXBMCTinyXML &doc, AddonInstanceId id=ADDON_SETTINGS_ID) const
Write settings into an XML document.
Protected Attributes inherited from ADDON::CAddon
const AddonInfoPtr m_addonInfo
Constructor & Destructor Documentation
CScraper() [1/3]
ADDON::CScraper::CScraper (const AddonInfoPtr & addonInfo, AddonType addonType) explicit
References CONTENT_ALBUMS, CONTENT_ARTISTS, CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_TVSHOWS, URIUtils::GetExtension(), m_isPython, m_pathContent, m_persistence, m_requiressettings, ADDON::SCRAPER_ALBUMS, ADDON::SCRAPER_ARTISTS, ADDON::SCRAPER_MOVIES, ADDON::SCRAPER_MUSICVIDEOS, ADDON::SCRAPER_TVSHOWS, CDateTimeSpan::SetFromTimeString(), and ADDON::CAddon::Type().
CScraper() [2/3]
ADDON::CScraper::CScraper (const CScraper & rhs) private delete
CScraper() [3/3]
ADDON::CScraper::CScraper (CScraper &&) private delete
Member Function Documentation
ClearCache()
void ADDON::CScraper::ClearCache ()
Clear any previously cached results for this scraper Any previously cached files are cleared if they have been cached for longer than the specified cachepersistence.
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), XFILE::CDirectory::Create(), XFILE::CFile::Delete(), XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::Exists(), CDateTime::GetCurrentDateTime(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetSettingsComponent(), ADDON::CAddon::ID(), m_persistence, and CFileItemList::Size().
Content()
CONTENT_TYPE ADDON::CScraper::Content () const inline
References m_pathContent.
Referenced by FindAlbum(), FindArtist(), FindMovie(), GetAlbumDetails(), GetArtistDetails(), GetArtwork(), GetEpisodeList(), and GetVideoDetails().
FindAlbum()
std::vector< CMusicAlbumInfo > ADDON::CScraper::FindAlbum (XFILE::CCurlFile & fcurl, const std::string & sAlbum, const std::string & sArtist = "")
References Content(), g_charsetConverter, CScraperUrl::GetData(), GetPathSettingsAsJSON(), XMLUtils::GetString(), CScraperUrl::HasUrls(), ADDON::CAddon::ID(), IsNoop(), CLog::Log(), LOGDEBUG, LOGWARNING, m_isPython, ADDON::CAddon::Name(), CXBMCTinyXML::Parse(), CScraperUrl::ParseAndAppendUrl(), CScraperUrl::ParseFromData(), ADDON::CAddon::Path(), RunNoThrow(), SearchStringEncoding(), MUSIC_GRABBER::CMusicAlbumInfo::SetRelevance(), ADDON::TranslateContent(), and ADDON::CAddon::Version().
FindArtist()
std::vector< CMusicArtistInfo > ADDON::CScraper::FindArtist (XFILE::CCurlFile & fcurl, const std::string & sArtist)
References Content(), g_charsetConverter, CArtist::genre, MUSIC_GRABBER::CMusicArtistInfo::GetArtist(), CScraperUrl::GetData(), GetPathSettingsAsJSON(), CServiceBroker::GetSettingsComponent(), XMLUtils::GetString(), CScraperUrl::HasUrls(), ADDON::CAddon::ID(), IsNoop(), CLog::Log(), LOGDEBUG, LOGERROR, m_isPython, ADDON::CAddon::Name(), CXBMCTinyXML::Parse(), CScraperUrl::ParseAndAppendUrl(), CScraperUrl::ParseFromData(), ADDON::CAddon::Path(), RunNoThrow(), SearchStringEncoding(), CArtist::strBorn, CArtist::strDisambiguation, ADDON::TranslateContent(), and ADDON::CAddon::Version().
FindMovie()
std::vector< CScraperUrl > ADDON::CScraper::FindMovie (XFILE::CCurlFile & fcurl, const std::string & movieTitle, int movieYear, bool fFirst)
References ADDON::CheckScraperError(), CUtil::CleanString(), Content(), g_charsetConverter, CScraperUrl::GetFirstThumbUrl(), GetPathSettingsAsJSON(), XMLUtils::GetString(), CScraperUrl::GetTitle(), ADDON::CAddon::ID(), id, IsNoop(), CLog::Log(), LOGDEBUG, LOGERROR, m_isPython, ADDON::CAddon::Name(), CXBMCTinyXML::Parse(), CScraperUrl::ParseAndAppendUrl(), CScraperUrl::ParseFromData(), ADDON::CAddon::Path(), ADDON::RelevanceSortFunction(), Run(), SearchStringEncoding(), CScraperUrl::SetId(), CScraperUrl::SetRelevance(), CScraperUrl::SetTitle(), ADDON::TranslateContent(), and ADDON::CAddon::Version().
GetAlbumDetails()
bool ADDON::CScraper::GetAlbumDetails (XFILE::CCurlFile & fcurl, const CScraperUrl & scurl, CAlbum & album)
References Content(), CScraperUrl::GetFirstThumbUrl(), GetPathSettingsAsJSON(), ADDON::CAddon::ID(), CAlbum::Load(), CLog::Log(), LOGDEBUG, LOGERROR, m_isPython, ADDON::CAddon::Name(), CXBMCTinyXML::Parse(), ADDON::CAddon::Path(), ADDON::PythonDetails(), RunNoThrow(), ADDON::TranslateContent(), and ADDON::CAddon::Version().
GetArtistDetails()
bool ADDON::CScraper::GetArtistDetails (XFILE::CCurlFile & fcurl, const CScraperUrl & scurl, const std::string & sSearch, CArtist & artist)
References Content(), CScraperUrl::GetFirstThumbUrl(), GetPathSettingsAsJSON(), CScraperUrl::HasUrls(), ADDON::CAddon::ID(), CArtist::Load(), CLog::Log(), LOGDEBUG, LOGERROR, m_isPython, ADDON::CAddon::Name(), CXBMCTinyXML::Parse(), ADDON::CAddon::Path(), ADDON::PythonDetails(), RunNoThrow(), ADDON::TranslateContent(), and ADDON::CAddon::Version().
GetArtwork()
bool ADDON::CScraper::GetArtwork (XFILE::CCurlFile & fcurl, CVideoInfoTag & details)
References Content(), GetPathSettingsAsJSON(), CVideoInfoTag::GetUniqueID(), CVideoInfoTag::HasUniqueID(), ADDON::CAddon::ID(), CVideoInfoTag::Load(), CLog::Log(), LOGDEBUG, LOGERROR, m_isPython, ADDON::CAddon::Name(), CXBMCTinyXML::Parse(), ADDON::CAddon::Path(), ADDON::PythonDetails(), RunNoThrow(), ADDON::TranslateContent(), and ADDON::CAddon::Version().
GetEpisodeList()
VIDEO::EPISODELIST ADDON::CScraper::GetEpisodeList (XFILE::CCurlFile & fcurl, const CScraperUrl & scurl)
References CScraperUrl::AppendUrl(), CVariant::asInteger(), KODI::VIDEO::EPISODE::cDate, Content(), KODI::VIDEO::EPISODE::cScraperUrl, XFILE::DIR_FLAG_DEFAULTS, g_localizeStrings, CScraperUrl::General, CURL::Get(), CLocalizeStrings::Get(), XFILE::CDirectory::GetDirectory(), CScraperUrl::GetFirstThumbUrl(), XMLUtils::GetInt(), GetPathSettingsAsJSON(), CGUIListItem::GetProperty(), XMLUtils::GetString(), CFileItem::GetURL(), CFileItem::GetVideoInfoTag(), CScraperUrl::HasUrls(), ADDON::CAddon::ID(), id, KODI::VIDEO::EPISODE::iEpisode, KODI::VIDEO::EPISODE::iSeason, KODI::VIDEO::EPISODE::iSubepisode, CLog::Log(), LOGDEBUG, LOGERROR, m_isPython, CScraperUrl::SUrlEntry::m_type, CScraperUrl::SUrlEntry::m_url, ADDON::CAddon::Name(), CXBMCTinyXML::Parse(), CScraperUrl::ParseAndAppendUrl(), ADDON::CAddon::Path(), RunNoThrow(), CDateTime::SetDate(), CScraperUrl::SetId(), CScraperUrl::SetTitle(), CDateTime::SetValid(), CFileItemList::Size(), strptime(), KODI::VIDEO::EPISODE::strTitle, ADDON::TranslateContent(), and ADDON::CAddon::Version().
GetPathSettings()
std::string ADDON::CScraper::GetPathSettings ()
Get the scraper settings for a particular path in the form of an XML string Loads the default and user settings (if not already loaded) and returns the user settings in the form or an XML string.
Returns
a string containing the XML settings
See also
SetPathSettings
References ADDON::CAddon::LoadSettings(), and ADDON::CAddon::SettingsToXML().
GetPathSettingsAsJSON()
std::string ADDON::CScraper::GetPathSettingsAsJSON () private
Get the scraper settings for a particular path in the form of a JSON string Loads the default and user settings (if not already loaded) and returns the user settings in the form of an JSON string. It is used in Python scrapers.
Returns
a string containing the JSON settings
See also
SetPathSettings
References ADDON::CAddon::GetSettings(), ADDON::CAddon::LoadSettings(), and CSettingsValueFlatJsonSerializer::SerializeValues().
Referenced by FindAlbum(), FindArtist(), FindMovie(), GetAlbumDetails(), GetArtistDetails(), GetArtwork(), GetEpisodeList(), GetVideoDetails(), NfoUrl(), and ResolveIDToUrl().
GetVideoDetails()
bool ADDON::CScraper::GetVideoDetails (XFILE::CCurlFile & fcurl, const std::unordered_map< std::string, std::string > & uniqueIDs, const CScraperUrl & scurl, bool fMovie, CVideoInfoTag & video)
References ADDON::CAddonVersion::asString(), Content(), CScraperUrl::GetFirstThumbUrl(), CScraperUrl::GetId(), GetPathSettingsAsJSON(), ADDON::CAddon::ID(), CVideoInfoTag::Load(), CLog::Log(), LOGDEBUG, LOGERROR, m_isPython, MediaTypeEpisode, MediaTypeMovie, ADDON::CAddon::Name(), CXBMCTinyXML::Parse(), ADDON::CAddon::Path(), ADDON::PythonDetails(), CVideoInfoTag::Reset(), RunNoThrow(), ADDON::TranslateContent(), and ADDON::CAddon::Version().
InternalRun()
std::string ADDON::CScraper::InternalRun (const std::string & function, const CScraperUrl & url, XFILE::CCurlFile & http, const std::vector< std::string > * extras) private
References CScraperUrl::Get(), CScraperUrl::GetUrls(), ADDON::CAddon::ID(), CScraperParser::m_param, m_parser, and CScraperParser::Parse().
Referenced by Run().
IsInUse()
bool ADDON::CScraper::IsInUse () const override virtual
Reimplemented from ADDON::CAddon.
References CONTENT_ALBUMS, CONTENT_ARTISTS, ADDON::CAddon::ID(), CMusicDatabase::Open(), CVideoDatabase::Open(), CMusicDatabase::ScraperInUse(), CVideoDatabase::ScraperInUse(), and Supports().
IsNoop()
bool ADDON::CScraper::IsNoop ()
References CScraperParser::IsNoop(), Load(), m_isPython, and m_parser.
Referenced by FindAlbum(), FindArtist(), FindMovie(), and NfoUrl().
IsPython()
bool ADDON::CScraper::IsPython () const inline
References m_isPython.
Load()
bool ADDON::CScraper::Load () private
Todo:
this routine assumes that deps are a single level, and assumes the dep is installed.
Does it make sense to have recursive dependencies?
Should we be checking the dep versions or do we assume it is ok?
References CScraperParser::AddDocument(), ADDON::CHOICE_YES, CServiceBroker::GetAddonMgr(), ADDON::CAddon::GetDependencies(), ADDON::CAddon::LibPath(), CScraperParser::Load(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGWARNING, m_fLoaded, m_isPython, m_parser, and ADDON::SCRAPER_LIBRARY.
Referenced by IsNoop(), and Run().
NfoUrl()
CScraperUrl ADDON::CScraper::NfoUrl (const std::string & sNfoContent)
References CScraperUrl::AppendUrl(), ADDON::CheckScraperError(), XFILE::DIR_FLAG_DEFAULTS, CScraperUrl::General, XFILE::CDirectory::GetDirectory(), CFileItem::GetDynPath(), GetPathSettingsAsJSON(), ADDON::CAddon::ID(), IsNoop(), CLog::Log(), LOGWARNING, m_isPython, CScraperUrl::SUrlEntry::m_type, CScraperUrl::SUrlEntry::m_url, CXBMCTinyXML::Parse(), CScraperUrl::ParseAndAppendUrl(), Run(), CScraperUrl::SetId(), and CFileItemList::Size().
operator=() [1/2]
CScraper & ADDON::CScraper::operator= (const CScraper &) private delete
operator=() [2/2]
CScraper & ADDON::CScraper::operator= (CScraper &&) private delete
RequiresSettings()
bool ADDON::CScraper::RequiresSettings () const inline
References m_requiressettings.
ResolveIDToUrl()
CScraperUrl ADDON::CScraper::ResolveIDToUrl (const std::string & externalID)
Resolve an external ID (e.g. MusicBrainz IDs) to a URL using scrapers If we have an ID in hand, e.g. MusicBrainz IDs or TheTVDB Season IDs we can get directly to a URL instead of searching by name and choosing from the search results. The correct scraper type should be used to get the right URL for a given ID, so we can differentiate albums, artists, TV Seasons, etc.
Parameters
externalID the external ID - e.g. MusicBrainzArtist/AlbumID
Returns
a populated URL pointing to the details page for the given ID or an empty URL if we couldn't resolve the ID.
References ADDON::CheckScraperError(), CFileItem::GetDynPath(), GetPathSettingsAsJSON(), XFILE::CPluginDirectory::GetPluginResult(), ADDON::CAddon::ID(), CLog::Log(), LOGWARNING, m_isPython, CXBMCTinyXML::Parse(), CScraperUrl::ParseAndAppendUrl(), CScraperUrl::ParseFromData(), Run(), and CScraperUrl::SetId().
Run()
std::vector< std::string > ADDON::CScraper::Run (const std::string & function, const CScraperUrl & url, XFILE::CCurlFile & http, const std::vector< std::string > * extras = nullptr) private
References InternalRun(), Load(), CLog::Log(), LOGDEBUG, LOGERROR, CScraperParser::m_param, m_parser, CXBMCTinyXML::Parse(), CScraperUrl::ParseAndAppendUrl(), and RunNoThrow().
Referenced by FindMovie(), NfoUrl(), ResolveIDToUrl(), and RunNoThrow().
RunNoThrow()
std::vector< std::string > ADDON::CScraper::RunNoThrow (const std::string & function, const CScraperUrl & url, XFILE::CCurlFile & http, const std::vector< std::string > * extras = nullptr) private
References ADDON::CScraperError::FAborted(), and Run().
Referenced by FindAlbum(), FindArtist(), GetAlbumDetails(), GetArtistDetails(), GetArtwork(), GetEpisodeList(), GetVideoDetails(), and Run().
SearchStringEncoding()
std::string ADDON::CScraper::SearchStringEncoding () const inline private
References CScraperParser::GetSearchStringEncoding(), and m_parser.
Referenced by FindAlbum(), FindArtist(), and FindMovie().
SetPathSettings()
bool ADDON::CScraper::SetPathSettings (CONTENT_TYPE content, const std::string & xml)
Set the scraper settings for a particular path from an XML string Loads the default and user settings (if not already loaded) and, if the given XML string is non-empty, overrides the user settings with the XML.
Parameters
content Content type of the path
xml string of XML with the settings. If non-empty this overrides any saved user settings.
Returns
true if settings are available, false otherwise
See also
GetPathSettings
References ADDON::content, ADDON::CAddon::LoadSettings(), m_pathContent, CXBMCTinyXML::Parse(), and ADDON::CAddon::SettingsFromXML().
Supports()
bool ADDON::CScraper::Supports (const CONTENT_TYPE & content) const
References ADDON::content, ADDON::ScraperTypeFromContent(), and ADDON::CAddon::Type().
Referenced by IsInUse().
Member Data Documentation
m_fLoaded
bool ADDON::CScraper::m_fLoaded = false private
Referenced by Load().
m_isPython
bool ADDON::CScraper::m_isPython = false private
Referenced by CScraper(), FindAlbum(), FindArtist(), FindMovie(), GetAlbumDetails(), GetArtistDetails(), GetArtwork(), GetEpisodeList(), GetVideoDetails(), IsNoop(), IsPython(), Load(), NfoUrl(), and ResolveIDToUrl().
m_parser
CScraperParser ADDON::CScraper::m_parser private
Referenced by InternalRun(), IsNoop(), Load(), Run(), and SearchStringEncoding().
m_pathContent
CONTENT_TYPE ADDON::CScraper::m_pathContent = CONTENT_NONE private
Referenced by Content(), CScraper(), and SetPathSettings().
m_persistence
CDateTimeSpan ADDON::CScraper::m_persistence private
Referenced by ClearCache(), and CScraper().
m_requiressettings
bool ADDON::CScraper::m_requiressettings = false private
Referenced by CScraper(), and RequiresSettings().
The documentation for this class was generated from the following files:
Scraper.h
Scraper.cpp