Kodi Documentation: CWinSystemAndroidGLESContext Class Reference
CWinSystemAndroidGLESContext Class Reference
#include <WinSystemAndroidGLESContext.h>
Public Member Functions
CWinSystemAndroidGLESContext ()=default
~CWinSystemAndroidGLESContext () override=default
CRenderSystemBase * GetRenderSystem () override
bool InitWindowSystem () override
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
float GetFrameLatencyAdjustment () override
Get time that should be subtracted from the display latency for this frame in milliseconds.
bool IsHDRDisplay () override
bool SetHDR (const VideoPicture *videoPicture) override
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
EGLDisplay GetEGLDisplay () const
EGLSurface GetEGLSurface () const
EGLContext GetEGLContext () const
EGLConfig GetEGLConfig () const
Public Member Functions inherited from CWinSystemAndroid
CWinSystemAndroid ()
~CWinSystemAndroid () override
bool DestroyWindowSystem () override
bool DestroyWindow () override
void UpdateResolutions () override
void InitiateModeChange ()
bool IsHdmiModeTriggered () const
void SetHdmiState (bool connected)
void UpdateDisplayModes ()
bool HasCursor () override
bool Minimize () override
bool Hide () override
bool Show (bool raise=true) override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
void MessagePush (XBMC_Event *newEvent)
bool MessagePump () override
CHDRCapabilities GetDisplayHDRCapabilities () const override
float GetGuiSdrPeakLuminance () const override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual const std::string GetName ()
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual void FinishWindowResize (int newWidth, int newHeight)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppFocusChange (bool bGaining)
virtual void NotifyAppActiveChange (bool bActivated)
virtual void ShowOSMouse (bool show)
virtual bool HasInertialGestures ()
virtual bool UseLimitedColor ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual float GetDisplayLatency ()
Get average display latency.
virtual bool Restore ()
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
virtual bool CanDoWindowed ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
virtual std::string GetClipboardText (void)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
virtual std::vector< std::string > GetConnectedOutputs ()
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
virtual bool BindTextureUploadContext ()
Binds a shared context to the current thread, in order to upload textures asynchronously.
virtual bool UnbindTextureUploadContext ()
Unbinds the shared context.
virtual bool HasContext ()
Checks if a graphics context is already bound to the current thread.
Public Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Public Member Functions inherited from CRenderSystemGLES
CRenderSystemGLES ()
~CRenderSystemGLES () override=default
bool InitRenderSystem () override
bool DestroyRenderSystem () override
bool ResetRenderSystem (int width, int height) override
bool BeginRender () override
bool EndRender () override
void PresentRender (bool rendered, bool videoLayer) override
void InvalidateColorBuffer () override
bool ClearBuffers (KODI::UTILS::COLOR::Color color) override
bool IsExtSupported (const char *extension) const override
void SetVSync (bool vsync)
void ResetVSync ()
void SetViewPort (const CRect &viewPort) override
void GetViewPort (CRect &viewPort) override
bool ScissorsCanEffectClipping () override
CRect ClipRectToScissorRect (const CRect &rect) override
void SetScissors (const CRect &rect) override
void ResetScissors () override
void SetDepthCulling (DEPTH_CULLING culling) override
void CaptureStateBlock () override
void ApplyStateBlock () override
void SetCameraPosition (const CPoint &camera, int screenWidth, int screenHeight, float stereoFactor=0.0f) override
bool SupportsStereo (RENDER_STEREO_MODE mode) const override
void Project (float &x, float &y, float &z) override
std::string GetShaderPath (const std::string &filename) override
void InitialiseShaders ()
void ReleaseShaders ()
void EnableGUIShader (ShaderMethodGLES method)
void DisableGUIShader ()
GLint GUIShaderGetPos ()
GLint GUIShaderGetCol ()
GLint GUIShaderGetCoord0 ()
GLint GUIShaderGetCoord1 ()
GLint GUIShaderGetUniCol ()
GLint GUIShaderGetCoord0Matrix ()
GLint GUIShaderGetField ()
GLint GUIShaderGetStep ()
GLint GUIShaderGetContrast ()
GLint GUIShaderGetBrightness ()
GLint GUIShaderGetModel ()
GLint GUIShaderGetMatrix ()
GLint GUIShaderGetClip ()
GLint GUIShaderGetCoordStep ()
GLint GUIShaderGetDepth ()
Public Member Functions inherited from CRenderSystemBase
CRenderSystemBase ()
virtual ~CRenderSystemBase ()
virtual void RestoreViewPort ()
virtual void SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view)
void GetRenderVersion (unsigned int &major, unsigned int &minor) const
const std::string & GetRenderVendor () const
const std::string & GetRenderRenderer () const
const std::string & GetRenderVersionString () const
virtual bool SupportsNPOT (bool dxt) const
unsigned int GetMaxTextureSize () const
unsigned int GetMinDXTPitch () const
virtual void ShowSplash (const std::string &message)
Static Public Member Functions
static void Register ()
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Protected Member Functions
void SetVSyncImpl (bool enable) override
void PresentRenderImpl (bool rendered) override
Protected Member Functions inherited from CWinSystemAndroid
std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl () override
void OnTimeout () override
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
Protected Member Functions inherited from CRenderSystemGLES
void CalculateMaxTexturesize ()
Private Member Functions
bool CreateSurface ()
Private Attributes
CEGLContextUtils m_pGLContext
bool m_hasHDRConfig = false
std::unique_ptr< AVMasteringDisplayMetadata > m_displayMetadata
std::unique_ptr< AVContentLightMetadata > m_lightMetadata
EGLint m_HDRColorSpace = EGL_NONE
bool m_hasEGL_ST2086_Extension = false
bool m_hasEGL_BT2020_PQ_Colorspace_Extension = false
Additional Inherited Members
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Protected Attributes inherited from CWinSystemAndroid
CAndroidUtils * m_android
EGLDisplay m_nativeDisplay = EGL_NO_DISPLAY
std::shared_ptr< CNativeWindow > m_nativeWindow
int m_displayWidth
int m_displayHeight
RENDER_STEREO_MODE m_stereo_mode
CTimer * m_dispResetTimer
CCriticalSection m_resourceSection
std::vector< IDispResource * > m_resources
CDecoderFilterManager * m_decoderFilterManager
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Protected Attributes inherited from CRenderSystemGLES
bool m_bVsyncInit {false}
int m_width
int m_height
std::string m_RenderExtensions
std::map< ShaderMethodGLES, std::unique_ptr< CGLESShader > > m_pShader
ShaderMethodGLES m_method = ShaderMethodGLES::SM_DEFAULT
GLint m_viewPort [4]
Protected Attributes inherited from CRenderSystemBase
bool m_bRenderCreated
bool m_bVSync
unsigned int m_maxTextureSize
unsigned int m_minDXTPitch
std::string m_RenderRenderer
std::string m_RenderVendor
std::string m_RenderVersion
int m_RenderVersionMinor
int m_RenderVersionMajor
RENDER_STEREO_VIEW m_stereoView = RENDER_STEREO_VIEW_OFF
RENDER_STEREO_MODE m_stereoMode = RENDER_STEREO_MODE_OFF
bool m_limitedColorRange = false
bool m_transferPQ {false}
std::unique_ptr< CGUIImage > m_splashImage
std::unique_ptr< CGUITextLayout > m_splashMessageLayout
Constructor & Destructor Documentation
CWinSystemAndroidGLESContext()
CWinSystemAndroidGLESContext::CWinSystemAndroidGLESContext () default
~CWinSystemAndroidGLESContext()
CWinSystemAndroidGLESContext::~CWinSystemAndroidGLESContext () override default
Member Function Documentation
CreateNewWindow()
bool CWinSystemAndroidGLESContext::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) override virtual
Reimplemented from CWinSystemAndroid.
References CEGLContextUtils::BindContext(), CWinSystemAndroid::CreateNewWindow(), CreateSurface(), CEGLContextUtils::DestroySurface(), m_pGLContext, and name.
Referenced by SetFullScreen().
CreateSurface()
bool CWinSystemAndroidGLESContext::CreateSurface () private
References CEGLContextUtils::CreateSurface(), m_displayMetadata, m_HDRColorSpace, m_lightMetadata, CWinSystemAndroid::m_nativeWindow, m_pGLContext, and CEGLContextUtils::SurfaceAttrib().
Referenced by CreateNewWindow(), and SetHDR().
CreateWinSystem()
std::unique_ptr< CWinSystemBase > CWinSystemAndroidGLESContext::CreateWinSystem () static
Referenced by Register().
GetEGLConfig()
EGLConfig CWinSystemAndroidGLESContext::GetEGLConfig () const
References CEGLContextUtils::GetEGLConfig(), and m_pGLContext.
GetEGLContext()
EGLContext CWinSystemAndroidGLESContext::GetEGLContext () const
References CEGLContextUtils::GetEGLContext(), and m_pGLContext.
GetEGLDisplay()
EGLDisplay CWinSystemAndroidGLESContext::GetEGLDisplay () const
References CEGLContextUtils::GetEGLDisplay(), and m_pGLContext.
GetEGLSurface()
EGLSurface CWinSystemAndroidGLESContext::GetEGLSurface () const
References CEGLContextUtils::GetEGLSurface(), and m_pGLContext.
GetFrameLatencyAdjustment()
float CWinSystemAndroidGLESContext::GetFrameLatencyAdjustment () override virtual
Get time that should be subtracted from the display latency for this frame in milliseconds.
Contrary to GetDisplayLatency, this value is calculated ad-hoc for the frame currently being rendered and not a value that is calculated/ averaged from past frames and their presentation times
Reimplemented from CWinSystemBase.
References CXBMCApp::Get(), and CXBMCApp::GetFrameLatencyMs().
GetRenderSystem()
CRenderSystemBase * CWinSystemAndroidGLESContext::GetRenderSystem () inline override virtual
Reimplemented from CWinSystemBase.
GetVideoSync()
std::unique_ptr< CVideoSync > CWinSystemAndroidGLESContext::GetVideoSync (CVideoReferenceClock * clock) override virtual
Reimplemented from CWinSystemBase.
InitWindowSystem()
bool CWinSystemAndroidGLESContext::InitWindowSystem () override virtual
Reimplemented from CWinSystemAndroid.
References CEGLAttributesVec::Add(), CEGLContextUtils::ChooseConfig(), CEGLContextUtils::CreateContext(), CEGLContextUtils::CreateDisplay(), CEGLContextUtils::GetEGLDisplay(), CEGLUtils::HasExtension(), CEGLContextUtils::InitializeDisplay(), CWinSystemAndroid::InitWindowSystem(), CLog::Log(), LOGDEBUG, m_hasEGL_BT2020_PQ_Colorspace_Extension, m_hasEGL_ST2086_Extension, m_hasHDRConfig, CWinSystemAndroid::m_nativeDisplay, and m_pGLContext.
IsHDRDisplay()
bool CWinSystemAndroidGLESContext::IsHDRDisplay () override virtual
Reimplemented from CWinSystemAndroid.
References CWinSystemAndroid::IsHDRDisplay(), m_hasEGL_BT2020_PQ_Colorspace_Extension, m_hasEGL_ST2086_Extension, and m_hasHDRConfig.
PresentRenderImpl()
void CWinSystemAndroidGLESContext::PresentRenderImpl (bool rendered) override protected virtual
Implements CRenderSystemGLES.
References CXBMCApp::Get(), CWinSystemAndroid::IsHdmiModeTriggered(), CEGLUtils::Log(), LOGERROR, CWinSystemAndroid::m_nativeWindow, m_pGLContext, CWinSystemAndroid::SetHdmiState(), CEGLContextUtils::TrySwapBuffers(), and CXBMCApp::WaitVSync().
Register()
void CWinSystemAndroidGLESContext::Register () static
References CreateWinSystem(), and KODI::WINDOWING::CWindowSystemFactory::RegisterWindowSystem().
Referenced by CPlatformAndroid::InitStageOne().
ResizeWindow()
bool CWinSystemAndroidGLESContext::ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override virtual
Implements CWinSystemBase.
References CRenderSystemGLES::ResetRenderSystem().
SetFullScreen()
bool CWinSystemAndroidGLESContext::SetFullScreen (bool fullScreen, RESOLUTION_INFO & res, bool blankOtherDisplays) override virtual
Implements CWinSystemBase.
References CreateNewWindow(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, and CRenderSystemGLES::ResetRenderSystem().
SetHDR()
bool CWinSystemAndroidGLESContext::SetHDR (const VideoPicture * videoPicture) override virtual
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
Reimplemented from CWinSystemBase.
References CEGLContextUtils::BindContext(), VideoPicture::color_space, CreateSurface(), CEGLContextUtils::DestroySurface(), VideoPicture::displayMetadata, CServiceBroker::GetWinSystem(), VideoPicture::hasDisplayMetadata, CWinSystemBase::IsHDRDisplaySettingEnabled(), CLog::Log(), LOGDEBUG, m_displayMetadata, m_hasEGL_BT2020_PQ_Colorspace_Extension, m_hasEGL_ST2086_Extension, m_hasHDRConfig, m_HDRColorSpace, m_lightMetadata, and m_pGLContext.
SetVSyncImpl()
void CWinSystemAndroidGLESContext::SetVSyncImpl (bool enable) override protected virtual
Implements CRenderSystemGLES.
References m_pGLContext, and CEGLContextUtils::SetVSync().
Member Data Documentation
m_displayMetadata
std::unique_ptr<AVMasteringDisplayMetadata> CWinSystemAndroidGLESContext::m_displayMetadata private
Referenced by CreateSurface(), and SetHDR().
m_hasEGL_BT2020_PQ_Colorspace_Extension
bool CWinSystemAndroidGLESContext::m_hasEGL_BT2020_PQ_Colorspace_Extension = false private
Referenced by InitWindowSystem(), IsHDRDisplay(), and SetHDR().
m_hasEGL_ST2086_Extension
bool CWinSystemAndroidGLESContext::m_hasEGL_ST2086_Extension = false private
Referenced by InitWindowSystem(), IsHDRDisplay(), and SetHDR().
m_hasHDRConfig
bool CWinSystemAndroidGLESContext::m_hasHDRConfig = false private
Referenced by InitWindowSystem(), IsHDRDisplay(), and SetHDR().
m_HDRColorSpace
EGLint CWinSystemAndroidGLESContext::m_HDRColorSpace = EGL_NONE private
Referenced by CreateSurface(), and SetHDR().
m_lightMetadata
std::unique_ptr<AVContentLightMetadata> CWinSystemAndroidGLESContext::m_lightMetadata private
Referenced by CreateSurface(), and SetHDR().
m_pGLContext
CEGLContextUtils CWinSystemAndroidGLESContext::m_pGLContext private
Referenced by CreateNewWindow(), CreateSurface(), GetEGLConfig(), GetEGLContext(), GetEGLDisplay(), GetEGLSurface(), InitWindowSystem(), PresentRenderImpl(), SetHDR(), and SetVSyncImpl().
The documentation for this class was generated from the following files:
WinSystemAndroidGLESContext.h
WinSystemAndroidGLESContext.cpp