Kodi Documentation: KODI::GAME::CGameClientDevice Class Reference
KODI::GAME::CGameClientDevice Class Reference
Games
Represents a device connected to a port.
#include <GameClientDevice.h>
Public Member Functions
CGameClientDevice (const game_input_device &device)
Construct a device.
CGameClientDevice (const ControllerPtr &controller)
Construct a device from a controller add-on.
~CGameClientDevice ()
Destructor.
const ControllerPtr & Controller () const
The controller profile.
const GameClientPortVec & Ports () const
The ports on this device.
Private Member Functions
void AddPort (const game_input_port &logicalPort, const CPhysicalPort &physicalPort)
Add a controller port.
Static Private Member Functions
static ControllerPtr GetController (const char *controllerId)
Private Attributes
ControllerPtr m_controller
GameClientPortVec m_ports
Detailed Description
Represents a device connected to a port.
Constructor & Destructor Documentation
CGameClientDevice() [1/2]
CGameClientDevice::CGameClientDevice (const game_input_device & device)
Construct a device.
Parameters
device The device Game API struct
References AddPort(), game_input_device::available_ports, m_controller, and game_input_device::port_count.
CGameClientDevice() [2/2]
CGameClientDevice::CGameClientDevice (const ControllerPtr & controller)
Construct a device from a controller add-on.
Parameters
controller The controller add-on
~CGameClientDevice()
CGameClientDevice::~CGameClientDevice () default
Destructor.
Member Function Documentation
AddPort()
void CGameClientDevice::AddPort (const game_input_port & logicalPort, const CPhysicalPort & physicalPort) private
Add a controller port.
Parameters
logicalPort The logical port Game API struct
physicalPort The physical port definition
References m_ports.
Referenced by CGameClientDevice().
Controller()
const ControllerPtr & KODI::GAME::CGameClientDevice::Controller () const inline
The controller profile.
References m_controller.
GetController()
ControllerPtr CGameClientDevice::GetController (const char * controllerId) static private
References KODI::GAME::CGameServices::GetController(), CServiceBroker::GetGameServices(), CLog::Log(), and LOGERROR.
Ports()
const GameClientPortVec & KODI::GAME::CGameClientDevice::Ports () const inline
The ports on this device.
References m_ports.
Member Data Documentation
m_controller
ControllerPtr KODI::GAME::CGameClientDevice::m_controller private
Referenced by CGameClientDevice(), and Controller().
m_ports
GameClientPortVec KODI::GAME::CGameClientDevice::m_ports private
Referenced by AddPort(), and Ports().
The documentation for this class was generated from the following files:
GameClientDevice.h
GameClientDevice.cpp