Kodi Documentation: CUPnPSettings Class Reference
CUPnPSettings Class Reference
#include <UPnPSettings.h>
Public Member Functions
void OnSettingsUnloaded () override
Setting values have been unloaded.
bool Load (const std::string &file)
bool Save (const std::string &file) const
void Clear ()
const std::string & GetServerUUID () const
int GetServerPort () const
int GetMaximumReturnedItems () const
const std::string & GetRendererUUID () const
int GetRendererPort () const
void SetServerUUID (const std::string &uuid)
void SetServerPort (int port)
void SetMaximumReturnedItems (int maximumReturnedItems)
void SetRendererUUID (const std::string &uuid)
void SetRendererPort (int port)
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual void OnSettingsLoaded ()
Settings have been loaded.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsCleared ()
Settings have been cleared.
Static Public Member Functions
static CUPnPSettings & GetInstance ()
Protected Member Functions
CUPnPSettings ()
CUPnPSettings (const CUPnPSettings &)=delete
CUPnPSettings & operator= (CUPnPSettings const &)=delete
~CUPnPSettings () override
Private Attributes
std::string m_serverUUID
int m_serverPort
int m_maxReturnedItems
std::string m_rendererUUID
int m_rendererPort
CCriticalSection m_critical
Logger m_logger
Constructor & Destructor Documentation
CUPnPSettings() [1/2]
CUPnPSettings::CUPnPSettings () protected
References Clear().
CUPnPSettings() [2/2]
CUPnPSettings::CUPnPSettings (const CUPnPSettings &) protected delete
~CUPnPSettings()
CUPnPSettings::~CUPnPSettings () override protected
References Clear().
Member Function Documentation
Clear()
void CUPnPSettings::Clear ()
References m_critical, m_maxReturnedItems, m_rendererPort, m_rendererUUID, m_serverPort, and m_serverUUID.
Referenced by CUPnPSettings(), Load(), OnSettingsUnloaded(), and ~CUPnPSettings().
GetInstance()
CUPnPSettings & CUPnPSettings::GetInstance () static
Referenced by UPNP::CUPnP::CreateRenderer(), UPNP::CUPnP::CreateServer(), CSettings::InitializeISettingsHandlers(), UPNP::CUPnP::StartRenderer(), UPNP::CUPnP::StartServer(), and CSettings::UninitializeISettingsHandlers().
GetMaximumReturnedItems()
int CUPnPSettings::GetMaximumReturnedItems () const inline
References m_maxReturnedItems.
GetRendererPort()
int CUPnPSettings::GetRendererPort () const inline
References m_rendererPort.
GetRendererUUID()
const std::string & CUPnPSettings::GetRendererUUID () const inline
References m_rendererUUID.
GetServerPort()
int CUPnPSettings::GetServerPort () const inline
References m_serverPort.
GetServerUUID()
const std::string & CUPnPSettings::GetServerUUID () const inline
References m_serverUUID.
Load()
bool CUPnPSettings::Load (const std::string & file)
References Clear(), CFileUtils::Exists(), XMLUtils::GetInt(), XMLUtils::GetString(), CXBMCTinyXML2::LoadFile(), m_critical, m_logger, m_maxReturnedItems, m_rendererPort, m_rendererUUID, m_serverPort, m_serverUUID, XML_MAX_ITEMS, XML_RENDERER_PORT, XML_RENDERER_UUID, XML_SERVER_PORT, XML_SERVER_UUID, and XML_UPNP.
Referenced by UPNP::CUPnP::StartRenderer(), and UPNP::CUPnP::StartServer().
OnSettingsUnloaded()
void CUPnPSettings::OnSettingsUnloaded () override virtual
Setting values have been unloaded.
This callback can be used to trigger uninitializing any state variables (e.g. before re-loading the settings).
Reimplemented from ISettingsHandler.
References Clear().
operator=()
CUPnPSettings & CUPnPSettings::operator= (CUPnPSettings const &) protected delete
Save()
bool CUPnPSettings::Save (const std::string & file) const
References m_critical, m_maxReturnedItems, m_rendererPort, m_rendererUUID, m_serverPort, m_serverUUID, CXBMCTinyXML2::SaveFile(), XMLUtils::SetInt(), XMLUtils::SetString(), XML_MAX_ITEMS, XML_RENDERER_PORT, XML_RENDERER_UUID, XML_SERVER_PORT, XML_SERVER_UUID, and XML_UPNP.
Referenced by UPNP::CUPnP::StartRenderer(), and UPNP::CUPnP::StartServer().
SetMaximumReturnedItems()
void CUPnPSettings::SetMaximumReturnedItems (int maximumReturnedItems) inline
References m_maxReturnedItems.
Referenced by UPNP::CUPnP::StartServer().
SetRendererPort()
void CUPnPSettings::SetRendererPort (int port) inline
References m_rendererPort.
Referenced by UPNP::CUPnP::StartRenderer().
SetRendererUUID()
void CUPnPSettings::SetRendererUUID (const std::string & uuid) inline
References m_rendererUUID.
Referenced by UPNP::CUPnP::StartRenderer().
SetServerPort()
void CUPnPSettings::SetServerPort (int port) inline
References m_serverPort.
Referenced by UPNP::CUPnP::StartServer().
SetServerUUID()
void CUPnPSettings::SetServerUUID (const std::string & uuid) inline
References m_serverUUID.
Referenced by UPNP::CUPnP::StartServer().
Member Data Documentation
m_critical
CCriticalSection CUPnPSettings::m_critical mutable private
Referenced by Clear(), Load(), and Save().
m_logger
Logger CUPnPSettings::m_logger private
Referenced by Load().
m_maxReturnedItems
int CUPnPSettings::m_maxReturnedItems private
Referenced by Clear(), GetMaximumReturnedItems(), Load(), Save(), and SetMaximumReturnedItems().
m_rendererPort
int CUPnPSettings::m_rendererPort private
Referenced by Clear(), GetRendererPort(), Load(), Save(), and SetRendererPort().
m_rendererUUID
std::string CUPnPSettings::m_rendererUUID private
Referenced by Clear(), GetRendererUUID(), Load(), Save(), and SetRendererUUID().
m_serverPort
int CUPnPSettings::m_serverPort private
Referenced by Clear(), GetServerPort(), Load(), Save(), and SetServerPort().
m_serverUUID
std::string CUPnPSettings::m_serverUUID private
Referenced by Clear(), GetServerUUID(), Load(), Save(), and SetServerUUID().
The documentation for this class was generated from the following files:
UPnPSettings.h
UPnPSettings.cpp