Kodi Documentation: ADDON::CAddonInfoBuilder Class Reference
ADDON::CAddonInfoBuilder Class Reference
#include <AddonInfoBuilder.h>
Static Public Member Functions
static AddonInfoPtr Generate (const std::string &id, AddonType type)
static AddonInfoPtr Generate (const std::string &addonPath, bool platformCheck=true)
static AddonInfoPtr Generate (const tinyxml2::XMLElement *baseElement, const RepositoryDirInfo &repo, bool platformCheck=true)
static void SetInstallData (const AddonInfoPtr &addon, const CDateTime &installDate, const CDateTime &lastUpdated, const CDateTime &lastUsed, const std::string &origin)
Parts used from CAddonDatabase.
Static Private Member Functions
static bool ParseXML (const AddonInfoPtr &addon, const tinyxml2::XMLElement *element, const std::string &addonPath)
static bool ParseXML (const AddonInfoPtr &addon, const tinyxml2::XMLElement *element, const std::string &addonPath, const RepositoryDirInfo &repo)
static bool ParseXMLTypes (CAddonType &addonType, const AddonInfoPtr &info, const tinyxml2::XMLElement *child)
static bool ParseXMLExtension (CAddonExtensions &addonExt, const tinyxml2::XMLElement *element)
static bool GetTextList (const tinyxml2::XMLElement *element, const std::string &tag, std::unordered_map< std::string, std::string > &translatedValues)
static const char * GetPlatformLibraryName (const tinyxml2::XMLElement *element)
static bool PlatformSupportsAddon (const AddonInfoPtr &addon)
Member Function Documentation
Generate() [1/3]
AddonInfoPtr ADDON::CAddonInfoBuilder::Generate (const std::string & addonPath, bool platformCheck = true) static
References URIUtils::AddFileToFolder(), CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGERROR, ParseXML(), PlatformSupportsAddon(), and CSpecialProtocol::TranslatePath().
Generate() [2/3]
AddonInfoPtr ADDON::CAddonInfoBuilder::Generate (const std::string & id, AddonType type) static
References id, CLog::Log(), and LOGERROR.
Referenced by ADDON::CAddonMgr::AddonsFromRepoXML(), ADDON::CAddonMgr::FindAddons(), ADDON::CAddonMgr::LoadAddonDescription(), TEST_F(), TEST_F(), and TEST_F().
Generate() [3/3]
AddonInfoPtr ADDON::CAddonInfoBuilder::Generate (const tinyxml2::XMLElement * baseElement, const RepositoryDirInfo & repo, bool platformCheck = true) static
References ADDON::RepositoryDirInfo::datadir, ParseXML(), and PlatformSupportsAddon().
GetPlatformLibraryName()
const char * ADDON::CAddonInfoBuilder::GetPlatformLibraryName (const tinyxml2::XMLElement * element) static private
Referenced by ParseXMLTypes().
GetTextList()
bool ADDON::CAddonInfoBuilder::GetTextList (const tinyxml2::XMLElement * element, const std::string & tag, std::unordered_map< std::string, std::string > & translatedValues) static private
References ADDON::KODI_ADDON_DEFAULT_LANGUAGE_CODE, and text.
Referenced by ParseXML().
ParseXML() [1/2]
bool ADDON::CAddonInfoBuilder::ParseXML (const AddonInfoPtr & addon, const tinyxml2::XMLElement * element, const std::string & addonPath) static private
References ParseXML().
Referenced by Generate(), Generate(), and ParseXML().
ParseXML() [2/2]
bool ADDON::CAddonInfoBuilder::ParseXML (const AddonInfoPtr & addon, const tinyxml2::XMLElement * element, const std::string & addonPath, const RepositoryDirInfo & repo) static private
References URIUtils::AddFileToFolder(), ADDON::RepositoryDirInfo::artdir, ADDON::AUDIODECODER, ADDON::AUDIOENCODER, ADDON::BROKEN, ADDON::RepositoryDirInfo::datadir, ADDON::DEPRECATED, ADDON::GAMEDLL, URIUtils::GetDirectory(), GetTextList(), ADDON::IMAGEDECODER, ADDON::INPUTSTREAM, ADDON::CAddonInfo::InstanceSupportType(), ADDON::KODI_ADDON_DEFAULT_LANGUAGE_CODE, CLog::Log(), LOGERROR, ADDON::MAX_TYPES, ADDON::NORMAL, ParseXMLTypes(), ADDON::PERIPHERALDLL, ADDON::PVRDLL, ADDON::SCREENSAVER, ADDON::CAddonInfo::TranslateType(), ADDON::UNKNOWN, value, ADDON::VFS, and ADDON::VISUALIZATION.
ParseXMLExtension()
bool ADDON::CAddonInfoBuilder::ParseXMLExtension (CAddonExtensions & addonExt, const tinyxml2::XMLElement * element) static private
References ADDON::CAddonExtensions::m_children, ADDON::CAddonExtensions::m_point, ADDON::CAddonExtensions::m_values, name, ParseXMLExtension(), and value.
Referenced by ParseXMLExtension(), and ParseXMLTypes().
ParseXMLTypes()
bool ADDON::CAddonInfoBuilder::ParseXMLTypes (CAddonType & addonType, const AddonInfoPtr & info, const tinyxml2::XMLElement * child) static private
References ADDON::SExtValue::asString(), ADDON::SExtValue::empty(), GetPlatformLibraryName(), ADDON::CAddonExtensions::GetValue(), CLog::Log(), LOGDEBUG, LOGERROR, ADDON::CAddonType::m_libname, ADDON::CAddonType::m_path, ParseXMLExtension(), and ADDON::CAddonType::SetProvides().
Referenced by ParseXML().
PlatformSupportsAddon()
bool ADDON::CAddonInfoBuilder::PlatformSupportsAddon (const AddonInfoPtr & addon) static private
Referenced by Generate(), and Generate().
SetInstallData()
void ADDON::CAddonInfoBuilder::SetInstallData (const AddonInfoPtr & addon, const CDateTime & installDate, const CDateTime & lastUpdated, const CDateTime & lastUsed, const std::string & origin) static
Parts used from CAddonDatabase.
Referenced by ADDON::CAddonDatabase::GetInstallData().
The documentation for this class was generated from the following files:
AddonInfoBuilder.h
AddonInfoBuilder.cpp