Kodi Documentation: CDVDVideoCodecStarfish Class Reference
CDVDVideoCodecStarfish Class Reference
#include <DVDVideoCodecStarfish.h>
Public Member Functions
CDVDVideoCodecStarfish (CProcessInfo &processInfo)
~CDVDVideoCodecStarfish () override
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
bool AddData (const DemuxPacket &packet) override
void Reset () override
bool Reconfigure (CDVDStreamInfo &hints) override
VCReturn GetPicture (VideoPicture *pVideoPicture) override
const char * GetName () override
void SetCodecControl (int flags) override
void SetSpeed (int iSpeed) override
Public Member Functions inherited from CDVDVideoCodec
CDVDVideoCodec (CProcessInfo &processInfo)
virtual ~CDVDVideoCodec ()=default
virtual unsigned GetConvergeCount ()
virtual unsigned GetAllowedReferences ()
virtual bool GetCodecStats (double &pts, int &droppedFrames, int &skippedPics)
virtual void Reopen ()
Static Public Member Functions
static std::unique_ptr< CDVDVideoCodec > Create (CProcessInfo &processInfo)
static bool Register ()
Private Member Functions
void Dispose ()
void SetHDR ()
void UpdateFpsDuration ()
bool OpenInternal (CDVDStreamInfo &hints, CDVDCodecOptions &options)
void PlayerCallback (const int32_t type, const int64_t numValue, const char *strValue)
Static Private Member Functions
static void PlayerCallback (const int32_t type, const int64_t numValue, const char *strValue, void *data)
static void AcbCallback (long acbId, long taskId, long eventType, long appState, long playState, const char *reply)
Private Attributes
std::unique_ptr< StarfishMediaAPIs > m_starfishMediaAPI
long m_acbId {0}
CDVDStreamInfo m_hints
std::string m_codecname
std::string m_formatname {"starfish"}
bool m_opened {false}
int m_codecControlFlags
std::chrono::nanoseconds m_currentPlaytime {0}
bool m_newFrame {false}
StarfishState m_state {StarfishState::FLUSHED}
VideoPicture m_videobuffer
std::unique_ptr< CBitstreamConverter > m_bitstream
Static Private Attributes
static constexpr auto ms_codecMap
static constexpr auto ms_formatInfoMap
static constexpr auto ms_hdrInfoMap
static std::atomic< bool > ms_instanceGuard
Additional Inherited Members
Public Types inherited from CDVDVideoCodec
enum VCReturn {
VC_NONE = 0 , VC_ERROR , VC_FATAL , VC_BUFFER ,
VC_PICTURE , VC_FLUSHED , VC_NOBUFFER , VC_REOPEN ,
VC_EOF
}
Protected Attributes inherited from CDVDVideoCodec
CProcessInfo & m_processInfo
Constructor & Destructor Documentation
CDVDVideoCodecStarfish()
CDVDVideoCodecStarfish::CDVDVideoCodecStarfish (CProcessInfo & processInfo) explicit
References AcbCallback(), CServiceBroker::GetWinSystem(), and m_acbId.
~CDVDVideoCodecStarfish()
CDVDVideoCodecStarfish::~CDVDVideoCodecStarfish () override
References Dispose().
Member Function Documentation
AcbCallback()
void CDVDVideoCodecStarfish::AcbCallback (long acbId, long taskId, long eventType, long appState, long playState, const char * reply) static private
References LOGDEBUG.
Referenced by CDVDVideoCodecStarfish().
AddData()
bool CDVDVideoCodecStarfish::AddData (const DemuxPacket & packet) override virtual
add data, decoder has to consume the entire packet returns true if the packet was consumed or if resubmitting it is useless
Implements CDVDVideoCodec.
References DEMUX_PACKET::dts, DVD_NOPTS_VALUE, FLUSHED, DEMUX_PACKET::iSize, LOGDEBUG, LOGVIDEO, LOGWARNING, m_bitstream, m_currentPlaytime, m_hints, m_newFrame, m_opened, m_starfishMediaAPI, m_state, DEMUX_PACKET::pData, DEMUX_PACKET::pts, CDVDStreamInfo::ptsinvalid, RUNNING, and CJSONVariantWriter::Write().
Create()
std::unique_ptr< CDVDVideoCodec > CDVDVideoCodecStarfish::Create (CProcessInfo & processInfo) static
Referenced by Register().
Dispose()
void CDVDVideoCodecStarfish::Dispose () private
References m_acbId, m_opened, m_starfishMediaAPI, and ms_instanceGuard.
Referenced by ~CDVDVideoCodecStarfish().
GetName()
const char * CDVDVideoCodecStarfish::GetName () inline override virtual
should return codecs name
Implements CDVDVideoCodec.
References m_formatname.
GetPicture()
CDVDVideoCodec::VCReturn CDVDVideoCodecStarfish::GetPicture (VideoPicture * pVideoPicture) override virtual
GetPicture controls decoding. Player calls it on every cycle it can signal a picture, request a buffer, or return none, if nothing applies the data is valid until the next GetPicture return VC_PICTURE
Implements CDVDVideoCodec.
References VideoPicture::dts, EOS, ERROR, FLUSHED, LOGDEBUG, LOGVIDEO, m_currentPlaytime, m_newFrame, m_opened, m_state, m_videobuffer, VideoPicture::pts, VideoPicture::SetParams(), CDVDVideoCodec::VC_BUFFER, CDVDVideoCodec::VC_EOF, CDVDVideoCodec::VC_ERROR, CDVDVideoCodec::VC_NONE, CDVDVideoCodec::VC_PICTURE, and VideoPicture::videoBuffer.
Open()
bool CDVDVideoCodecStarfish::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Open the decoder, returns true on success Decoders not capable of running multiple instances should return false in case there is already a instance open
Implements CDVDVideoCodec.
References LOGERROR, ms_instanceGuard, and OpenInternal().
OpenInternal()
bool CDVDVideoCodecStarfish::OpenInternal (CDVDStreamInfo & hints, CDVDCodecOptions & options) private
References CDVDStreamInfo::aspect, CDVDStreamInfo::codec, CDVDStreamInfo::codec_tag, CDVDStreamInfo::cryptoSession, CDVDStreamInfo::dovi, CDVDStreamInfo::extradata, CSettingUtils::FindIntInList(), CDVDStreamInfo::fpsrate, CDVDStreamInfo::fpsscale, FFmpegExtraData::GetData(), CCompileInfo::GetPackage(), CServiceBroker::GetSettingsComponent(), FFmpegExtraData::GetSize(), CServiceBroker::GetWinSystem(), HDR_TYPE_DOLBYVISION, HDR_TYPE_HDR10, CDVDStreamInfo::hdrType, CDVDStreamInfo::height, VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iHeight, VideoPicture::iWidth, CDVDStreamInfo::level, LOGDEBUG, LOGERROR, LOGINFO, LOGVIDEO, CStarfishVideoBuffer::m_acbId, m_acbId, m_bitstream, m_codecControlFlags, m_codecname, m_formatname, m_hints, m_opened, CDVDVideoCodec::m_processInfo, m_starfishMediaAPI, m_videobuffer, ms_codecMap, ms_formatInfoMap, PlayerCallback(), CDVDStreamInfo::profile, CDVDStreamInfo::ptsinvalid, CVariant::push_back(), VideoPicture::Reset(), SetHDR(), CSettings::SETTING_VIDEOPLAYER_ALLOWEDHDRFORMATS, CSettings::SETTING_VIDEOPLAYER_CONVERTDOVI, CProcessInfo::SetVideoDAR(), CProcessInfo::SetVideoDecoderName(), CProcessInfo::SetVideoDeintMethod(), CProcessInfo::SetVideoDimensions(), CProcessInfo::SetVideoPixelFormat(), CDVDStreamInfo::stereo_mode, VideoPicture::stereoMode, UpdateFpsDuration(), CVariant::VariantTypeArray, VideoPicture::videoBuffer, CSettings::VIDEOPLAYER_ALLOWED_HDR_TYPE_DOLBY_VISION, CDVDStreamInfo::width, and CJSONVariantWriter::Write().
Referenced by Open().
PlayerCallback() [1/2]
void CDVDVideoCodecStarfish::PlayerCallback (const int32_t type, const int64_t numValue, const char * strValue) private
References EOS, ERROR, FLUSHED, LOGDEBUG, LOGERROR, m_acbId, m_currentPlaytime, m_newFrame, m_starfishMediaAPI, and m_state.
Referenced by OpenInternal(), and PlayerCallback().
PlayerCallback() [2/2]
void CDVDVideoCodecStarfish::PlayerCallback (const int32_t type, const int64_t numValue, const char * strValue, void * data) static private
References data(), and PlayerCallback().
Reconfigure()
bool CDVDVideoCodecStarfish::Reconfigure (CDVDStreamInfo & hints) override virtual
Reconfigure the decoder, returns true on success Decoders not capable of running multiple instances may be capable of reconfiguring the running instance. If Reconfigure returns false, player will close / open the decoder
Reimplemented from CDVDVideoCodec.
References CDVDStreamInfo::COMPARE_ALL, CDVDStreamInfo::COMPARE_EXTRADATA, CDVDStreamInfo::COMPARE_ID, CDVDStreamInfo::Equal(), LOGDEBUG, and m_hints.
Register()
bool CDVDVideoCodecStarfish::Register () static
References Create(), and CDVDFactoryCodec::RegisterHWVideoCodec().
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::InitWindowSystem().
Reset()
void CDVDVideoCodecStarfish::Reset () override virtual
Reset the decoder. Should be the same as calling Dispose and Open after each other
Implements CDVDVideoCodec.
References DVD_NOPTS_VALUE, FLUSHED, LOGDEBUG, m_bitstream, m_opened, m_starfishMediaAPI, m_state, m_videobuffer, and VideoPicture::pts.
SetCodecControl()
void CDVDVideoCodecStarfish::SetCodecControl (int flags) override virtual
Codec can be informed by player with the following flags:
DVD_CODEC_CTRL_NO_POSTPROC : if speed is not normal the codec can switch off postprocessing and de-interlacing
DVD_CODEC_CTRL_HURRY : codecs may do postprocessing and de-interlacing. If video buffers in RenderManager are about to run dry, this is signaled to codec. Codec can wait for post-proc to be finished instead of returning empty and getting another packet.
DVD_CODEC_CTRL_DRAIN : instruct decoder to deliver last pictures without requesting new packets
DVD_CODEC_CTRL_DROP : this packet is going to be dropped. decoder is free to use it for decoding
Reimplemented from CDVDVideoCodec.
References LOGDEBUG, LOGVIDEO, and m_codecControlFlags.
SetHDR()
void CDVDVideoCodecStarfish::SetHDR () private
References CDVDStreamInfo::colorPrimaries, CDVDStreamInfo::colorRange, CDVDStreamInfo::colorSpace, CDVDStreamInfo::colorTransferCharacteristic, CDVDStreamInfo::contentLightMetadata, CVariant::empty(), HDR_TYPE_HDR10, HDR_TYPE_HLG, CDVDStreamInfo::hdrType, LOGDEBUG, LOGVIDEO, m_hints, m_starfishMediaAPI, CDVDStreamInfo::masteringMetadata, ms_hdrInfoMap, and CJSONVariantWriter::Write().
Referenced by OpenInternal().
SetSpeed()
void CDVDVideoCodecStarfish::SetSpeed (int iSpeed) override virtual
will be called by video player indicating the playback speed. see DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE and friends.
Reimplemented from CDVDVideoCodec.
References DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, LOGWARNING, and m_starfishMediaAPI.
UpdateFpsDuration()
void CDVDVideoCodecStarfish::UpdateFpsDuration () private
References CDVDStreamInfo::fpsrate, CDVDStreamInfo::fpsscale, LOGDEBUG, m_hints, CDVDVideoCodec::m_processInfo, and CProcessInfo::SetVideoFps().
Referenced by OpenInternal().
Member Data Documentation
m_acbId
long CDVDVideoCodecStarfish::m_acbId {0} private
Referenced by CDVDVideoCodecStarfish(), Dispose(), OpenInternal(), and PlayerCallback().
m_bitstream
std::unique_ptr<CBitstreamConverter> CDVDVideoCodecStarfish::m_bitstream private
Referenced by AddData(), OpenInternal(), and Reset().
m_codecControlFlags
int CDVDVideoCodecStarfish::m_codecControlFlags private
Referenced by OpenInternal(), and SetCodecControl().
m_codecname
std::string CDVDVideoCodecStarfish::m_codecname private
Referenced by OpenInternal().
m_currentPlaytime
std::chrono::nanoseconds CDVDVideoCodecStarfish::m_currentPlaytime {0} private
Referenced by AddData(), GetPicture(), and PlayerCallback().
m_formatname
std::string CDVDVideoCodecStarfish::m_formatname {"starfish"} private
Referenced by GetName(), and OpenInternal().
m_hints
CDVDStreamInfo CDVDVideoCodecStarfish::m_hints private
Referenced by AddData(), OpenInternal(), Reconfigure(), SetHDR(), and UpdateFpsDuration().
m_newFrame
bool CDVDVideoCodecStarfish::m_newFrame {false} private
Referenced by AddData(), GetPicture(), and PlayerCallback().
m_opened
bool CDVDVideoCodecStarfish::m_opened {false} private
Referenced by AddData(), Dispose(), GetPicture(), OpenInternal(), and Reset().
m_starfishMediaAPI
std::unique_ptr<StarfishMediaAPIs> CDVDVideoCodecStarfish::m_starfishMediaAPI private
Referenced by AddData(), Dispose(), OpenInternal(), PlayerCallback(), Reset(), SetHDR(), and SetSpeed().
m_state
StarfishState CDVDVideoCodecStarfish::m_state {StarfishState::FLUSHED} private
Referenced by AddData(), GetPicture(), PlayerCallback(), and Reset().
m_videobuffer
VideoPicture CDVDVideoCodecStarfish::m_videobuffer private
Referenced by GetPicture(), OpenInternal(), and Reset().
ms_codecMap
constexpr auto CDVDVideoCodecStarfish::ms_codecMap static constexpr private
Initial value:
= make_map<AVCodecID, std::string_view>({
      {AV_CODEC_ID_VP8, "VP8"},
      {AV_CODEC_ID_VP9, "VP9"},
      {AV_CODEC_ID_AVS, "H264"},
      {AV_CODEC_ID_CAVS, "H264"},
      {AV_CODEC_ID_H264, "H264"},
      {AV_CODEC_ID_HEVC, "H265"},
      {AV_CODEC_ID_AV1, "AV1"},
  })
Referenced by OpenInternal().
ms_formatInfoMap
constexpr auto CDVDVideoCodecStarfish::ms_formatInfoMap static constexpr private
Initial value:
= make_map<AVCodecID, std::string_view>({
      {AV_CODEC_ID_VP8, "starfish-vp8"},
      {AV_CODEC_ID_VP9, "starfish-vp9"},
      {AV_CODEC_ID_AVS, "starfish-h264"},
      {AV_CODEC_ID_CAVS, "starfish-h264"},
      {AV_CODEC_ID_H264, "starfish-h264"},
      {AV_CODEC_ID_HEVC, "starfish-h265"},
      {AV_CODEC_ID_AV1, "starfish-av1"},
  })
Referenced by OpenInternal().
ms_hdrInfoMap
constexpr auto CDVDVideoCodecStarfish::ms_hdrInfoMap static constexpr private
Initial value:
= make_map<AVColorTransferCharacteristic, std::string_view>({
      {AVCOL_TRC_SMPTE2084, "HDR10"},
      {AVCOL_TRC_ARIB_STD_B67, "HLG"},
  })
Referenced by SetHDR().
ms_instanceGuard
std::atomic< bool > CDVDVideoCodecStarfish::ms_instanceGuard static private
Referenced by Dispose(), and Open().
The documentation for this class was generated from the following files:
DVDVideoCodecStarfish.h
DVDVideoCodecStarfish.cpp