Kodi Documentation: ActiveAE::CActiveAE Class Reference
ActiveAE::CActiveAE Class Reference
#include <ActiveAE.h>
Classes
struct SoundState
Public Member Functions
CActiveAE ()
~CActiveAE () override
void Start () override
Initializes the AudioEngine, called by CFactory when it is time to initialize the audio engine.
void Shutdown () override
Called when the application needs to terminate the engine.
bool Suspend () override
Suspends output and de-initializes sink.
bool Resume () override
Resumes output and re-initializes sink.
bool IsSuspended () override
Get the current Suspend() state.
void OnSettingsChange ()
float GetVolume () override
Returns the current master volume level of the AudioEngine.
void SetVolume (const float volume) override
Sets the master volume level of the AudioEngine.
void SetMute (const bool enabled) override
Set the mute state (does not affect volume level value)
bool IsMuted () override
Get the current mute state.
IAE::StreamPtr MakeStream (AEAudioFormat &audioFormat, unsigned int options=0, IAEClockCallback *clock=NULL) override
Creates and returns a new IAEStream in the format specified, this function should never fail.
IAE::SoundPtr MakeSound (const std::string &file) override
void EnumerateOutputDevices (AEDeviceList &devices, bool passthrough) override
Enumerate the supported audio output devices.
bool SupportsRaw (AEAudioFormat &format) override
Returns true if the AudioEngine supports AE_FMT_RAW streams for use with formats such as IEC61937.
bool SupportsSilenceTimeout () override
Returns true if the AudioEngine supports drain mode which is not streaming silence when idle.
bool UsesDtsCoreFallback () override
Returns true if the AudioEngine is currently configured to extract the DTS Core from DTS-HD streams.
bool HasStereoAudioChannelCount () override
Returns true if the AudioEngine is currently configured for stereo audio.
bool HasHDAudioChannelCount () override
Returns true if the AudioEngine is currently configured for HD audio (more than 5.1)
bool SupportsQualityLevel (enum AEQuality level) override
Returns true if AudioEngine supports specified quality level.
bool IsSettingVisible (const std::string &settingId) override
AE decides whether this settings should be displayed.
void KeepConfiguration (unsigned int millis) override
Instruct AE to keep configuration for a specified time.
void DeviceChange () override
Instruct AE to re-initialize, e.g. after ELD change event.
void DeviceCountChange (const std::string &driver) override
Instruct AE to re-initialize, e.g. after ELD change event.
bool GetCurrentSinkFormat (AEAudioFormat &SinkFormat) override
Get the current sink data format.
void RegisterAudioCallback (IAudioCallback *pCallback) override
void UnregisterAudioCallback (IAudioCallback *pCallback) override
void OnLostDisplay () override
void OnResetDisplay () override
void OnAppFocusChange (bool focus) override
Public Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
Protected Types
enum { MODE_RAW , MODE_TRANSCODE , MODE_PCM }
Protected Member Functions
void PlaySound (CActiveAESound *sound)
void GetDelay (AEDelayStatus &status, CActiveAEStream *stream)
void GetSyncInfo (CAESyncInfo &info, CActiveAEStream *stream)
float GetCacheTime (CActiveAEStream *stream)
float GetCacheTotal ()
float GetMaxDelay ()
void FlushStream (CActiveAEStream *stream)
void PauseStream (CActiveAEStream *stream, bool pause)
void StopSound (CActiveAESound *sound)
void SetStreamAmplification (CActiveAEStream *stream, float amplify)
void SetStreamReplaygain (CActiveAEStream *stream, float rgain)
void SetStreamVolume (CActiveAEStream *stream, float volume)
void SetStreamResampleRatio (CActiveAEStream *stream, double ratio)
void SetStreamResampleMode (CActiveAEStream *stream, int mode)
void SetStreamFFmpegInfo (CActiveAEStream *stream, int profile, enum AVMatrixEncoding matrix_encoding, enum AVAudioServiceType audio_service_type)
void SetStreamFade (CActiveAEStream *stream, float from, float target, unsigned int millis)
void Process () override
void StateMachine (int signal, Protocol *port, Message *msg)
bool InitSink ()
void DrainSink ()
void UnconfigureSink ()
void Dispose ()
void LoadSettings ()
void ValidateOutputDevices (bool saveChanges)
bool NeedReconfigureBuffers ()
bool NeedReconfigureSink ()
void ApplySettingsToFormat (AEAudioFormat &format, const AudioSettings &settings, int *mode=NULL)
void Configure (AEAudioFormat *desiredFmt=NULL)
AEAudioFormat GetInputFormat (AEAudioFormat *desiredFmt=NULL)
CActiveAEStream * CreateStream (MsgStreamNew *streamMsg)
void DiscardStream (CActiveAEStream *stream)
void SFlushStream (CActiveAEStream *stream)
void FlushEngine ()
void ClearDiscardedBuffers ()
void SStopSound (CActiveAESound *sound)
void DiscardSound (CActiveAESound *sound)
void ChangeResamplers ()
bool RunStages ()
bool HasWork ()
CSampleBuffer * SyncStream (CActiveAEStream *stream)
void ResampleSounds ()
bool ResampleSound (CActiveAESound *sound)
void MixSounds (CSoundPacket &dstSample)
void Deamplify (CSoundPacket &dstSample)
bool CompareFormat (const AEAudioFormat &lhs, const AEAudioFormat &rhs)
Protected Member Functions inherited from IAE
IAE ()=default
virtual ~IAE ()=default
Static Protected Member Functions
static uint8_t ** AllocSoundSample (SampleConfig &config, int &samples, int &bytes_per_sample, int &planes, int &linesize)
static void FreeSoundSample (uint8_t **data)
Protected Attributes
CEvent m_inMsgEvent
CEvent m_outMsgEvent
CActiveAEControlProtocol m_controlPort
CActiveAEDataProtocol m_dataPort
int m_state
bool m_bStateMachineSelfTrigger
std::chrono::milliseconds m_extTimeout
bool m_extError
bool m_extDrain
XbmcThreads::EndTime m_extDrainTimer
std::chrono::milliseconds m_extKeepConfig
bool m_extDeferData
std::queue< time_t > m_extLastDeviceChange
bool m_extSuspended = false
bool m_isWinSysReg = false
enum ActiveAE::CActiveAE:: { ... } m_mode
CActiveAESink m_sink
AEAudioFormat m_sinkFormat
AEAudioFormat m_sinkRequestFormat
AEAudioFormat m_encoderFormat
AEAudioFormat m_internalFormat
AEAudioFormat m_inputFormat
AudioSettings m_settings
CEngineStats m_stats
IAEEncoder * m_encoder
std::string m_currDevice
std::unique_ptr< CActiveAESettings > m_settingsHandler
std::unique_ptr< CActiveAEBufferPoolResample > m_sinkBuffers
std::unique_ptr< CActiveAEBufferPoolResample > m_vizBuffers
std::unique_ptr< CActiveAEBufferPool > m_vizBuffersInput
std::unique_ptr< CActiveAEBufferPool > m_silenceBuffers
std::unique_ptr< CActiveAEBufferPool > m_encoderBuffers
std::list< CActiveAEStream * > m_streams
std::list< std::unique_ptr< CActiveAEBufferPool > > m_discardBufferPools
unsigned int m_streamIdGen
std::list< SoundState > m_sounds_playing
std::vector< CActiveAESound * > m_sounds
float m_volume
float m_volumeScaled
bool m_muted
bool m_sinkHasVolume
std::vector< IAudioCallback * > m_audioCallback
bool m_vizInitialized
CCriticalSection m_vizLock
float m_aeVolume
bool m_aeMuted
bool m_aeGUISoundForce
Private Member Functions
bool FreeStream (IAEStream *stream, bool finish) override
This method will remove the specified stream from the engine.
void FreeSound (IAESound *sound) override
Free the supplied IAESound object.
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Friends
class CActiveAESound
class CActiveAEStream
class CSoundPacket
class CActiveAEBufferPoolResample
Additional Inherited Members
Public Types inherited from IAE
using StreamPtr = std::unique_ptr< IAEStream, IAEStreamDeleter >
using SoundPtr = std::unique_ptr< IAESound, IAESoundDeleter >
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
MODE_RAW
MODE_TRANSCODE
MODE_PCM
Constructor & Destructor Documentation
CActiveAE()
CActiveAE::CActiveAE ()
References m_aeGUISoundForce, m_aeMuted, m_aeVolume, m_encoder, m_mode, m_muted, m_settingsHandler, m_sinkHasVolume, m_stats, m_streamIdGen, m_vizInitialized, m_volume, m_volumeScaled, MODE_PCM, and ActiveAE::CEngineStats::Reset().
~CActiveAE()
CActiveAE::~CActiveAE () override
References Dispose(), and m_settingsHandler.
Member Function Documentation
AllocSoundSample()
uint8_t ** CActiveAE::AllocSoundSample (SampleConfig & config, int & samples, int & bytes_per_sample, int & planes, int & linesize) static protected
References SampleConfig::channels, and SampleConfig::fmt.
Referenced by ActiveAE::CSoundPacket::CSoundPacket().
ApplySettingsToFormat()
void CActiveAE::ApplySettingsToFormat (AEAudioFormat & format, const AudioSettings & settings, int * mode = NULL) protected
References ActiveAE::AudioSettings::ac3passthrough, ActiveAE::AudioSettings::ac3transcode, AE_CH_BL, AE_CH_BR, AE_CH_LAYOUT_2_0, AE_CH_LAYOUT_2_1, AE_CH_LAYOUT_3_0, AE_CH_LAYOUT_3_1, AE_CH_LAYOUT_4_0, AE_CH_LAYOUT_4_1, AE_CH_LAYOUT_5_0, AE_CH_LAYOUT_5_1, AE_CH_LAYOUT_7_0, AE_CH_LAYOUT_7_1, AE_CH_SL, AE_CH_SR, AE_CONFIG_AUTO, AE_CONFIG_FIXED, AE_DEVTYPE_IEC958, AE_FMT_FLOAT, AE_FMT_FLOATP, AE_FMT_RAW, AE_IS_PLANAR, ActiveAE::AudioSettings::channels, ActiveAE::AudioSettings::config, CAEChannelInfo::Count(), ActiveAE::AudioSettings::device, ActiveAE::CActiveAESink::GetDeviceType(), ActiveAE::CEngineStats::GetWaterLevel(), CLog::Log(), LOGINFO, AEAudioFormat::m_channelLayout, m_extKeepConfig, m_internalFormat, m_mode, m_settings, m_sink, m_stats, m_streams, MODE_PCM, MODE_RAW, MODE_TRANSCODE, ActiveAE::AudioSettings::passthrough, CAEChannelInfo::ReplaceChannel(), CAEChannelInfo::ResolveChannels(), ActiveAE::AudioSettings::samplerate, ActiveAE::AudioSettings::stereoupmix, and CAEStreamInfo::STREAM_TYPE_AC3.
Referenced by Configure(), NeedReconfigureBuffers(), and NeedReconfigureSink().
ChangeResamplers()
void CActiveAE::ChangeResamplers () protected
References m_settings, m_streams, ActiveAE::AudioSettings::mixSubLevel, ActiveAE::AudioSettings::normalizelevels, ActiveAE::AudioSettings::resampleQuality, and ActiveAE::AudioSettings::stereoupmix.
Referenced by StateMachine().
ClearDiscardedBuffers()
void CActiveAE::ClearDiscardedBuffers () protected
References ActiveAE::CActiveAEBufferPoolResample::Flush(), CLog::Log(), LOGDEBUG, and m_discardBufferPools.
Referenced by Configure(), DiscardStream(), and StateMachine().
CompareFormat()
bool CActiveAE::CompareFormat (const AEAudioFormat & lhs, const AEAudioFormat & rhs) protected
References AE_FMT_RAW, AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, AEAudioFormat::m_sampleRate, AEAudioFormat::m_streamInfo, and CAEStreamInfo::m_type.
Referenced by Configure(), and NeedReconfigureSink().
Configure()
void CActiveAE::Configure (AEAudioFormat * desiredFmt = NULL) protected
Todo:
implement
Todo:
adjust to decoder
Todo:
use cache of sync + water level
References ActiveAE::CEngineStats::AddSamples(), AE_CH_FC, AE_CH_LAYOUT_2_0, AE_FMT_FLOAT, AE_FMT_FLOATP, AE_FMT_RAW, AE_IS_PLANAR, AE_SOUND_ALWAYS, AE_SOUND_IDLE, ApplySettingsToFormat(), ClearDiscardedBuffers(), CompareFormat(), CAEChannelInfo::Count(), CAEUtil::DataFormatToBits(), ActiveAE::AudioSettings::device, AE::AESinkDevice::driver, ActiveAE::AudioSettings::driver, FlushEngine(), CAEUtil::GetAEChannelLayout(), CAEUtil::GetAVChannelLayout(), IAEEncoder::GetCodecID(), GetInputFormat(), ActiveAE::CEngineStats::GetMaxDelay(), ActiveAE::AudioSettings::guisoundmode, IAEEncoder::Initialize(), InitSink(), CLog::Log(), LOGWARNING, m_aeGUISoundForce, m_audioCallback, AEAudioFormat::m_channelLayout, CAEChannelInfo::m_channels, ActiveAE::CActiveAESink::m_controlPort, m_currDevice, AEAudioFormat::m_dataFormat, m_discardBufferPools, m_encoder, m_encoderBuffers, m_encoderFormat, m_extDrain, m_extKeepConfig, AEAudioFormat::m_frames, AEAudioFormat::m_frameSize, m_internalFormat, m_mode, AEAudioFormat::m_sampleRate, m_settings, m_silenceBuffers, m_sink, m_sinkBuffers, m_sinkFormat, m_sinkRequestFormat, m_sounds, m_sounds_playing, m_stats, m_streams, m_vizBuffers, m_vizBuffersInput, m_vizInitialized, m_volume, ActiveAE::AudioSettings::mixSubLevel, MODE_PCM, MODE_RAW, MODE_TRANSCODE, AE::AESinkDevice::name, ActiveAE::AudioSettings::normalizelevels, AE::CAESinkFactory::ParseDevice(), ActiveAE::AudioSettings::passthroughdevice, ActiveAE::AudioSettings::resampleQuality, ActiveAE::CEngineStats::Reset(), CAEChannelInfo::ResolveChannels(), Actor::Protocol::SendOutMessage(), ActiveAE::AudioSettings::stereoupmix, CAEStreamInfo::STREAM_TYPE_AC3, ActiveAE::CSinkControlProtocol::STREAMING, and ActiveAE::CSinkControlProtocol::VOLUME.
Referenced by RunStages(), and StateMachine().
CreateStream()
CActiveAEStream * CActiveAE::CreateStream (MsgStreamNew * streamMsg) protected
References ActiveAE::CEngineStats::AddStream(), AE_FMT_RAW, AESTREAM_FORCE_RESAMPLE, AESTREAM_PAUSED, CActiveAEStream, ActiveAE::MsgStreamNew::clock, ActiveAE::MsgStreamNew::format, AEAudioFormat::m_dataFormat, ActiveAE::CActiveAEStream::m_fadingSamples, ActiveAE::CActiveAEStream::m_forceResampler, ActiveAE::CActiveAEStream::m_id, ActiveAE::CActiveAEStream::m_inMsgEvent, ActiveAE::CActiveAEStream::m_inputBuffers, m_outMsgEvent, ActiveAE::CActiveAEStream::m_paused, ActiveAE::CActiveAEStream::m_pClock, ActiveAE::CActiveAEStream::m_resampleMode, ActiveAE::CActiveAEStream::m_started, m_stats, m_streamIdGen, ActiveAE::CActiveAEStream::m_streamIsBuffering, ActiveAE::CActiveAEStream::m_streamPort, m_streams, ActiveAE::CActiveAEStream::m_syncState, ActiveAE::MsgStreamNew::options, and CAESyncInfo::SYNC_OFF.
Referenced by StateMachine().
Deamplify()
void CActiveAE::Deamplify (CSoundPacket & dstSample) protected
References SampleConfig::channels, ActiveAE::CSoundPacket::config, ActiveAE::CSoundPacket::data, m_muted, m_volumeScaled, ActiveAE::CSoundPacket::nb_samples, and ActiveAE::CSoundPacket::planes.
Referenced by RunStages().
DeviceChange()
void CActiveAE::DeviceChange () override virtual
Instruct AE to re-initialize, e.g. after ELD change event.
Reimplemented from IAE.
References ActiveAE::CActiveAEControlProtocol::DEVICECHANGE, m_controlPort, and Actor::Protocol::SendOutMessage().
DeviceCountChange()
void CActiveAE::DeviceCountChange (const std::string & driver) override virtual
Instruct AE to re-initialize, e.g. after ELD change event.
Reimplemented from IAE.
References ActiveAE::CActiveAEControlProtocol::DEVICECOUNTCHANGE, m_controlPort, name, and Actor::Protocol::SendOutMessage().
DiscardSound()
void CActiveAE::DiscardSound (CActiveAESound * sound) protected
References m_sounds, and SStopSound().
Referenced by StateMachine().
DiscardStream()
void CActiveAE::DiscardStream (CActiveAEStream * stream) protected
References ClearDiscardedBuffers(), CLog::Log(), LOGDEBUG, m_discardBufferPools, ActiveAE::CActiveAEStream::m_processingSamples, m_stats, m_streams, and ActiveAE::CEngineStats::RemoveStream().
Referenced by StateMachine().
Dispose()
void CActiveAE::Dispose () protected
References ActiveAE::CActiveAESink::Dispose(), CServiceBroker::GetWinSystem(), CThread::m_bStop, m_controlPort, m_dataPort, m_isWinSysReg, m_outMsgEvent, m_sink, Actor::Protocol::Purge(), CEvent::Set(), CThread::StopThread(), and CWinSystemBase::Unregister().
Referenced by Shutdown(), and ~CActiveAE().
DrainSink()
void CActiveAE::DrainSink () protected
References ActiveAE::CSinkDataProtocol::ACC, ActiveAE::CSinkDataProtocol::DRAIN, CLog::Log(), LOGERROR, ActiveAE::CActiveAESink::m_dataPort, m_extError, m_sink, Actor::Message::Release(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, and success.
Referenced by StateMachine().
EnumerateOutputDevices()
void CActiveAE::EnumerateOutputDevices (AEDeviceList & devices, bool passthrough) override virtual
Enumerate the supported audio output devices.
Parameters
devices The device list to append supported devices to
passthrough True if only passthrough devices are wanted
Implements IAE.
References ActiveAE::CActiveAESink::EnumerateOutputDevices(), and m_sink.
Referenced by ActiveAE::CActiveAESettings::SettingOptionsAudioDevicesFillerGeneral().
FlushEngine()
void CActiveAE::FlushEngine () protected
References ActiveAE::CSinkControlProtocol::ACC, ActiveAE::CSinkControlProtocol::FLUSH, CLog::Log(), LOGERROR, ActiveAE::CActiveAESink::m_controlPort, m_extError, m_mode, AEAudioFormat::m_sampleRate, m_sink, m_sinkBuffers, m_sinkFormat, m_stats, m_vizBuffers, MODE_PCM, Actor::Message::Release(), ActiveAE::CEngineStats::Reset(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, and success.
Referenced by Configure(), SFlushStream(), and StateMachine().
FlushStream()
void CActiveAE::FlushStream (CActiveAEStream * stream) protected
References ActiveAE::CActiveAEControlProtocol::ACC, ActiveAE::CActiveAEControlProtocol::FLUSHSTREAM, CLog::Log(), LOGERROR, m_controlPort, Actor::Message::Release(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, and success.
Referenced by ActiveAE::CActiveAEStream::Flush().
FreeSound()
void CActiveAE::FreeSound (IAESound * sound) override private virtual
Free the supplied IAESound object.
Parameters
sound The IAESound object to free
Implements IAE.
References ActiveAE::CActiveAEDataProtocol::FREESOUND, m_dataPort, and Actor::Protocol::SendOutMessage().
FreeSoundSample()
void CActiveAE::FreeSoundSample (uint8_t ** data) static protected
References data().
Referenced by ActiveAE::CSoundPacket::~CSoundPacket().
FreeStream()
bool CActiveAE::FreeStream (IAEStream * stream, bool finish) override private virtual
This method will remove the specified stream from the engine.
For OSX/IOS this is essential to reconfigure the audio output.
Parameters
stream The stream to be altered
finish if true AE will switch back to gui sound mode (if this is last stream)
Returns
true on success, else false.
Implements IAE.
References ActiveAE::CActiveAEControlProtocol::ACC, ActiveAE::MsgStreamFree::finish, ActiveAE::CActiveAEDataProtocol::FREESTREAM, CLog::Log(), LOGERROR, m_dataPort, Actor::Message::Release(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, ActiveAE::MsgStreamFree::stream, and success.
GetCacheTime()
float ActiveAE::CActiveAE::GetCacheTime (CActiveAEStream * stream) inline protected
References ActiveAE::CEngineStats::GetCacheTime(), and m_stats.
Referenced by ActiveAE::CActiveAEStream::GetCacheTime().
GetCacheTotal()
float ActiveAE::CActiveAE::GetCacheTotal () inline protected
References ActiveAE::CEngineStats::GetCacheTotal(), and m_stats.
Referenced by ActiveAE::CActiveAEStream::GetCacheTotal().
GetCurrentSinkFormat()
bool CActiveAE::GetCurrentSinkFormat (AEAudioFormat & SinkFormat) override virtual
Get the current sink data format.
Parameters
Current sink data format. For more details see AEAudioFormat.
Returns
Returns true on success, else false.
Reimplemented from IAE.
References ActiveAE::CEngineStats::GetCurrentSinkFormat(), and m_stats.
GetDelay()
void ActiveAE::CActiveAE::GetDelay (AEDelayStatus & status, CActiveAEStream * stream) inline protected
References ActiveAE::CEngineStats::GetDelay(), and m_stats.
Referenced by ActiveAE::CActiveAEStream::GetDelay().
GetInputFormat()
AEAudioFormat CActiveAE::GetInputFormat (AEAudioFormat * desiredFmt = NULL) protected
References AE_CH_LAYOUT_2_0, AE_FMT_FLOAT, AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, AEAudioFormat::m_frames, AEAudioFormat::m_frameSize, m_inputFormat, AEAudioFormat::m_sampleRate, m_silenceBuffers, and m_streams.
Referenced by Configure(), NeedReconfigureBuffers(), and NeedReconfigureSink().
GetMaxDelay()
float ActiveAE::CActiveAE::GetMaxDelay () inline protected
References ActiveAE::CEngineStats::GetMaxDelay(), and m_stats.
Referenced by ActiveAE::CActiveAEStream::GetMaxDelay().
GetSyncInfo()
void ActiveAE::CActiveAE::GetSyncInfo (CAESyncInfo & info, CActiveAEStream * stream) inline protected
References ActiveAE::CEngineStats::GetSyncInfo(), and m_stats.
Referenced by ActiveAE::CActiveAEStream::GetSyncInfo().
GetVolume()
float CActiveAE::GetVolume () override virtual
Returns the current master volume level of the AudioEngine.
Returns
The volume level between 0.0 and 1.0
Implements IAE.
References m_aeVolume.
HasHDAudioChannelCount()
bool CActiveAE::HasHDAudioChannelCount () override virtual
Returns true if the AudioEngine is currently configured for HD audio (more than 5.1)
Returns
true if the AudioEngine is currently configured for HD audio (more than 5.1)
Reimplemented from IAE.
References AE_CH_LAYOUT_2_0, AE_CH_LAYOUT_5_1, AE_DEVTYPE_IEC958, ActiveAE::CActiveAESink::GetDeviceType(), CServiceBroker::GetSettingsComponent(), m_sink, CSettings::SETTING_AUDIOOUTPUT_AUDIODEVICE, and CSettings::SETTING_AUDIOOUTPUT_CHANNELS.
HasStereoAudioChannelCount()
bool CActiveAE::HasStereoAudioChannelCount () override virtual
Returns true if the AudioEngine is currently configured for stereo audio.
Returns
true if the AudioEngine is currently configured for stereo audio
Reimplemented from IAE.
References AE_CH_LAYOUT_2_0, AE_CONFIG_FIXED, AE_DEVTYPE_IEC958, ActiveAE::CActiveAESink::GetDeviceType(), CServiceBroker::GetSettingsComponent(), m_sink, CSettings::SETTING_AUDIOOUTPUT_AUDIODEVICE, CSettings::SETTING_AUDIOOUTPUT_CHANNELS, CSettings::SETTING_AUDIOOUTPUT_CONFIG, and CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGH.
HasWork()
bool CActiveAE::HasWork () protected
References m_sinkBuffers, m_sounds_playing, and m_streams.
Referenced by StateMachine().
InitSink()
bool CActiveAE::InitSink () protected
References ActiveAE::CSinkControlProtocol::ACC, AE_FMT_INVALID, AE_FMT_RAW, ActiveAE::CSinkControlProtocol::CONFIGURE, Actor::Message::data, data(), ActiveAE::AudioSettings::device, ActiveAE::SinkConfig::device, ActiveAE::SinkConfig::format, CLog::Log(), LOGERROR, ActiveAE::CActiveAESink::m_controlPort, AEAudioFormat::m_dataFormat, m_extError, m_inMsgEvent, m_settings, m_sink, m_sinkFormat, m_sinkHasVolume, m_sinkRequestFormat, m_stats, ActiveAE::CActiveAESink::NeedIecPack(), ActiveAE::AudioSettings::passthroughdevice, Actor::Message::Release(), CEvent::Reset(), Actor::Protocol::SendOutMessage(), Actor::Protocol::SendOutMessageSync(), ActiveAE::CEngineStats::SetCurrentSinkFormat(), ActiveAE::CSinkControlProtocol::SETNOISETYPE, ActiveAE::CSinkControlProtocol::SETSILENCETIMEOUT, ActiveAE::CEngineStats::SetSinkCacheTotal(), ActiveAE::CEngineStats::SetSinkLatency(), ActiveAE::CEngineStats::SetSinkNeedIec(), Actor::Message::signal, ActiveAE::AudioSettings::silenceTimeoutMinutes, ActiveAE::SinkConfig::stats, ActiveAE::AudioSettings::streamNoise, and success.
Referenced by Configure().
IsMuted()
bool CActiveAE::IsMuted () override virtual
Get the current mute state.
Returns
The current mute state
Implements IAE.
References m_aeMuted.
IsSettingVisible()
bool CActiveAE::IsSettingVisible (const std::string & settingId) override virtual
AE decides whether this settings should be displayed.
Returns
true if AudioEngine wants to display this setting
Reimplemented from IAE.
References AE_CH_LAYOUT_2_0, AE_CONFIG_FIXED, AE_DEVTYPE_IEC958, AE_FMT_RAW, ActiveAE::CActiveAESink::GetDeviceType(), CServiceBroker::GetSettingsComponent(), ActiveAE::CActiveAESink::HasPassthroughDevice(), AEAudioFormat::m_dataFormat, m_sink, CSettings::SETTING_AUDIOOUTPUT_AC3PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_AC3TRANSCODE, CSettings::SETTING_AUDIOOUTPUT_AUDIODEVICE, CSettings::SETTING_AUDIOOUTPUT_CHANNELS, CSettings::SETTING_AUDIOOUTPUT_CONFIG, CSettings::SETTING_AUDIOOUTPUT_DTSHDPASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_DTSPASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_EAC3PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGHDEVICE, CSettings::SETTING_AUDIOOUTPUT_SAMPLERATE, CSettings::SETTING_AUDIOOUTPUT_STEREOUPMIX, CSettings::SETTING_AUDIOOUTPUT_TRUEHDPASSTHROUGH, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_EAC3, CAEStreamInfo::STREAM_TYPE_TRUEHD, and ActiveAE::CActiveAESink::SupportsFormat().
Referenced by ActiveAE::CActiveAESettings::IsSettingVisible(), and LoadSettings().
IsSuspended()
bool CActiveAE::IsSuspended () override virtual
Get the current Suspend() state.
Used by players to determine if audio is being processed Default is true so players drop audio or pause if engine unloaded
Returns
True if processing suspended
Reimplemented from IAE.
References ActiveAE::CEngineStats::IsSuspended(), and m_stats.
Referenced by MakeStream().
KeepConfiguration()
void CActiveAE::KeepConfiguration (unsigned int millis) override virtual
Instruct AE to keep configuration for a specified time.
Parameters
millis time for which old configuration should be kept
Reimplemented from IAE.
References ActiveAE::CActiveAEControlProtocol::KEEPCONFIG, m_controlPort, and Actor::Protocol::SendOutMessage().
LoadSettings()
void CActiveAE::LoadSettings () protected
References ActiveAE::AudioSettings::ac3passthrough, ActiveAE::AudioSettings::ac3transcode, AE_CH_LAYOUT_2_0, AE_CONFIG_FIXED, AE_DEVTYPE_IEC958, ActiveAE::AudioSettings::atempoThreshold, ActiveAE::AudioSettings::channels, ActiveAE::AudioSettings::config, ActiveAE::AudioSettings::device, ActiveAE::AudioSettings::dtshdpassthrough, ActiveAE::AudioSettings::dtspassthrough, ActiveAE::AudioSettings::eac3passthrough, ActiveAE::CActiveAESink::GetDeviceType(), CServiceBroker::GetSettingsComponent(), ActiveAE::AudioSettings::guisoundmode, ActiveAE::CActiveAESink::HasPassthroughDevice(), IsSettingVisible(), m_settings, m_sink, ActiveAE::AudioSettings::mixSubLevel, ActiveAE::AudioSettings::normalizelevels, ActiveAE::AudioSettings::passthrough, ActiveAE::AudioSettings::passthroughdevice, ActiveAE::AudioSettings::resampleQuality, ActiveAE::AudioSettings::samplerate, CSettings::SETTING_AUDIOOUTPUT_AC3PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_AC3TRANSCODE, CSettings::SETTING_AUDIOOUTPUT_ATEMPOTHRESHOLD, CSettings::SETTING_AUDIOOUTPUT_AUDIODEVICE, CSettings::SETTING_AUDIOOUTPUT_CHANNELS, CSettings::SETTING_AUDIOOUTPUT_CONFIG, CSettings::SETTING_AUDIOOUTPUT_DTSHDCOREFALLBACK, CSettings::SETTING_AUDIOOUTPUT_DTSHDPASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_DTSPASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_EAC3PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_GUISOUNDMODE, CSettings::SETTING_AUDIOOUTPUT_MAINTAINORIGINALVOLUME, CSettings::SETTING_AUDIOOUTPUT_MIXSUBLEVEL, CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGHDEVICE, CSettings::SETTING_AUDIOOUTPUT_PROCESSQUALITY, CSettings::SETTING_AUDIOOUTPUT_SAMPLERATE, CSettings::SETTING_AUDIOOUTPUT_STEREOUPMIX, CSettings::SETTING_AUDIOOUTPUT_STREAMNOISE, CSettings::SETTING_AUDIOOUTPUT_STREAMSILENCE, CSettings::SETTING_AUDIOOUTPUT_TRUEHDPASSTHROUGH, ActiveAE::AudioSettings::silenceTimeoutMinutes, ActiveAE::AudioSettings::stereoupmix, ActiveAE::AudioSettings::streamNoise, ActiveAE::AudioSettings::truehdpassthrough, and ActiveAE::AudioSettings::usesdtscorefallback.
Referenced by StateMachine().
MakeSound()
IAE::SoundPtr CActiveAE::MakeSound (const std::string & file) override virtual
load sound from an audio file and store original format register the sound in ActiveAE later when the engine is idle it will convert the sound to sink format
Implements IAE.
References IAE::IAESoundDeleter, CLog::Log(), LOGERROR, m_dataPort, ActiveAE::CActiveAEDataProtocol::NEWSOUND, ActiveAE::CActiveAESound::Read(), ActiveAE::CActiveAESound::Seek(), and Actor::Protocol::SendOutMessage().
MakeStream()
IAE::StreamPtr CActiveAE::MakeStream (AEAudioFormat & audioFormat, unsigned int options = 0, IAEClockCallback * clock = NULL) override virtual
Creates and returns a new IAEStream in the format specified, this function should never fail.
The cleanup behaviour can be modified with the IAEStreamDeleter::setFinish method. Per default the behaviour is the same as calling FreeStream with true.
Parameters
audioFormat
options A bit field of stream options (see: enum AEStreamOptions)
Returns
a new IAEStream that will accept data in the requested format
Todo:
pass number of samples in audio packet
Implements IAE.
References ActiveAE::CActiveAEControlProtocol::ACC, AE_FMT_INVALID, AE_FMT_MAX, AE_FMT_RAW, ActiveAE::MsgStreamNew::clock, Actor::Message::data, CAEUtil::DataFormatToBits(), ActiveAE::MsgStreamNew::format, IsSuspended(), CLog::Log(), LOGERROR, AEAudioFormat::m_dataFormat, m_dataPort, AEAudioFormat::m_frames, ActiveAE::CActiveAEDataProtocol::NEWSTREAM, ActiveAE::MsgStreamNew::options, Actor::Message::Release(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, and success.
MixSounds()
void CActiveAE::MixSounds (CSoundPacket & dstSample) protected
References SampleConfig::channels, ActiveAE::CSoundPacket::config, ActiveAE::CSoundPacket::data, m_sounds_playing, ActiveAE::CSoundPacket::nb_samples, ActiveAE::CSoundPacket::planes, and ResampleSound().
Referenced by RunStages().
NeedReconfigureBuffers()
bool CActiveAE::NeedReconfigureBuffers () protected
References ApplySettingsToFormat(), GetInputFormat(), AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, AEAudioFormat::m_sampleRate, m_settings, and m_sinkRequestFormat.
Referenced by StateMachine().
NeedReconfigureSink()
bool CActiveAE::NeedReconfigureSink () protected
References AE_FMT_RAW, ApplySettingsToFormat(), CompareFormat(), ActiveAE::AudioSettings::device, AE::AESinkDevice::driver, ActiveAE::AudioSettings::driver, GetInputFormat(), m_currDevice, AEAudioFormat::m_dataFormat, m_settings, m_sinkFormat, AE::AESinkDevice::name, AE::CAESinkFactory::ParseDevice(), and ActiveAE::AudioSettings::passthroughdevice.
Referenced by StateMachine().
OnAppFocusChange()
void CActiveAE::OnAppFocusChange (bool focus) override virtual
Reimplemented from IDispResource.
References ActiveAE::CActiveAEControlProtocol::APPFOCUSED, m_controlPort, and Actor::Protocol::SendOutMessage().
OnLostDisplay()
void CActiveAE::OnLostDisplay () override virtual
Reimplemented from IDispResource.
References ActiveAE::CActiveAEControlProtocol::ACC, ActiveAE::CActiveAEControlProtocol::DISPLAYLOST, CLog::Log(), LOGERROR, m_controlPort, Actor::Message::Release(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, and success.
OnResetDisplay()
void CActiveAE::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References ActiveAE::CActiveAEControlProtocol::DISPLAYRESET, m_controlPort, and Actor::Protocol::SendOutMessage().
OnSettingsChange()
void CActiveAE::OnSettingsChange ()
References m_controlPort, ActiveAE::CActiveAEControlProtocol::RECONFIGURE, and Actor::Protocol::SendOutMessage().
Referenced by ActiveAE::CActiveAESettings::OnSettingChanged().
PauseStream()
void CActiveAE::PauseStream (CActiveAEStream * stream, bool pause) protected
Todo:
pause sink, needs api change
References m_controlPort, ActiveAE::CActiveAEControlProtocol::PAUSESTREAM, ActiveAE::CActiveAEControlProtocol::RESUMESTREAM, and Actor::Protocol::SendOutMessage().
Referenced by ActiveAE::CActiveAEStream::Pause(), and ActiveAE::CActiveAEStream::Resume().
PlaySound()
void CActiveAE::PlaySound (CActiveAESound * sound) protected
References m_dataPort, ActiveAE::CActiveAEDataProtocol::PLAYSOUND, and Actor::Protocol::SendOutMessage().
Referenced by ActiveAE::CActiveAESound::Play().
Process()
void CActiveAE::Process (void) override protected virtual
Reimplemented from CThread.
References AE_TOP_WAIT_PRECOND, Actor::Protocol::GetMessage(), m_bStateMachineSelfTrigger, CThread::m_bStop, m_controlPort, m_dataPort, ActiveAE::CActiveAESink::m_dataPort, m_extDeferData, m_extDrain, m_extKeepConfig, m_extTimeout, m_outMsgEvent, m_sink, m_state, m_streams, Actor::Protocol::ReceiveInMessage(), Actor::Protocol::ReceiveOutMessage(), Actor::Message::Release(), Actor::Message::signal, ActiveAE::CActiveAESink::Start(), StateMachine(), ActiveAE::CActiveAEControlProtocol::TIMEOUT, and CEvent::Wait().
RegisterAudioCallback()
void CActiveAE::RegisterAudioCallback (IAudioCallback * pCallback) override virtual
Reimplemented from IAE.
References m_audioCallback, m_vizInitialized, and m_vizLock.
ResampleSound()
bool CActiveAE::ResampleSound (CActiveAESound * sound) protected
To become center clear on position test ??????
References AE_CH_FC, AE_CH_FL, AE_CH_NULL, AE_FMT_INVALID, ActiveAE::AERESAMPLEFACTORY_QUICK_RESAMPLE, SampleConfig::bits_per_sample, SampleConfig::channel_layout, SampleConfig::channels, ActiveAE::CSoundPacket::config, CAEChannelInfo::Count(), ActiveAE::CAEResampleFactory::Create(), ActiveAE::CSoundPacket::data, CAEUtil::DataFormatToDitherBits(), CAEUtil::DataFormatToUsedBits(), SampleConfig::dither_bits, SampleConfig::fmt, CAEUtil::GetAVChannelLayout(), CAEUtil::GetAVSampleFormat(), ActiveAE::CActiveAESound::GetChannel(), ActiveAE::CActiveAESound::GetSound(), ActiveAE::CActiveAESound::InitSound(), AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, m_internalFormat, m_mode, AEAudioFormat::m_sampleRate, m_settings, MODE_RAW, ActiveAE::CSoundPacket::nb_samples, ActiveAE::AudioSettings::resampleQuality, SampleConfig::sample_rate, and ActiveAE::CActiveAESound::SetConverted().
Referenced by MixSounds(), and ResampleSounds().
ResampleSounds()
void CActiveAE::ResampleSounds () protected
resample sounds to destination format for mixing destination format is either format of stream or default sink format when no stream is playing
References AE_SOUND_IDLE, AE_SOUND_OFF, ActiveAE::AudioSettings::guisoundmode, m_aeGUISoundForce, m_settings, m_sounds, m_streams, and ResampleSound().
Referenced by StateMachine().
Resume()
bool CActiveAE::Resume () override virtual
Resumes output and re-initializes sink.
Used to resume output from Suspend() state above
Returns
True if successful
Implements IAE.
References ActiveAE::CActiveAEControlProtocol::ACC, ActiveAE::CActiveAEControlProtocol::INIT, CLog::Log(), LOGERROR, m_controlPort, m_inMsgEvent, Actor::Message::Release(), CEvent::Reset(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, and success.
RunStages()
bool CActiveAE::RunStages () protected
Todo:
find better solution for this gapless bites audiophile
References ActiveAE::CEngineStats::AddSamples(), AE_CONFIG_MATCH, AE_FMT_FLOAT, AE_FMT_RAW, CAEUtil::ClampArray(), ActiveAE::AudioSettings::config, Configure(), Deamplify(), IAEEncoder::Encode(), ActiveAE::CEngineStats::GetCacheTime(), AEDelayStatus::GetDelay(), ActiveAE::CEngineStats::GetDelay(), ActiveAE::CEngineStats::GetWaterLevel(), int64_t(), CLog::Log(), LOGWARNING, m_audioCallback, AEAudioFormat::m_dataFormat, ActiveAE::CActiveAESink::m_dataPort, m_encoder, m_encoderBuffers, ActiveAE::CActiveAEStream::m_format, m_internalFormat, m_mode, m_muted, ActiveAE::CActiveAEStream::m_paused, AEAudioFormat::m_sampleRate, m_settings, m_silenceBuffers, m_sink, m_sinkBuffers, m_sinkFormat, m_sinkHasVolume, m_sounds_playing, m_stats, AEAudioFormat::m_streamInfo, m_streams, CAEStreamInfo::m_type, m_vizBuffers, m_vizBuffersInput, m_vizInitialized, m_vizLock, MixSounds(), MODE_RAW, MODE_TRANSCODE, ActiveAE::CSampleBuffer::pkt, ActiveAE::CSampleBuffer::pkt_start_offset, ActiveAE::CSampleBuffer::Return(), ActiveAE::CSinkDataProtocol::SAMPLE, Actor::Protocol::SendOutMessage(), CAEStreamInfo::STREAM_TYPE_TRUEHD, ActiveAE::CActiveAEDataProtocol::STREAMBUFFER, ActiveAE::CActiveAEDataProtocol::STREAMDRAINED, CAESyncInfo::SYNC_INSYNC, SyncStream(), ActiveAE::CSampleBuffer::timestamp, and ActiveAE::CEngineStats::UpdateStream().
Referenced by StateMachine().
SetMute()
void CActiveAE::SetMute (const bool enabled) override virtual
Set the mute state (does not affect volume level value)
Parameters
enabled The mute state
Implements IAE.
References m_aeMuted, m_controlPort, ActiveAE::CActiveAEControlProtocol::MUTE, and Actor::Protocol::SendOutMessage().
SetStreamAmplification()
void CActiveAE::SetStreamAmplification (CActiveAEStream * stream, float amplify) protected
References ActiveAE::MsgStreamParameter::float_par, m_controlPort, ActiveAE::MsgStreamParameter::parameter, Actor::Protocol::SendOutMessage(), ActiveAE::MsgStreamParameter::stream, and ActiveAE::CActiveAEControlProtocol::STREAMAMP.
Referenced by ActiveAE::CActiveAEStream::SetAmplification().
SetStreamFade()
void CActiveAE::SetStreamFade (CActiveAEStream * stream, float from, float target, unsigned int millis) protected
References ActiveAE::MsgStreamFade::from, m_controlPort, ActiveAE::MsgStreamFade::millis, Actor::Protocol::SendOutMessage(), ActiveAE::MsgStreamFade::stream, ActiveAE::CActiveAEControlProtocol::STREAMFADE, and ActiveAE::MsgStreamFade::target.
Referenced by ActiveAE::CActiveAEStream::FadeVolume().
SetStreamFFmpegInfo()
void CActiveAE::SetStreamFFmpegInfo (CActiveAEStream * stream, int profile, enum AVMatrixEncoding matrix_encoding, enum AVAudioServiceType audio_service_type) protected
References ActiveAE::MsgStreamFFmpegInfo::audio_service_type, m_controlPort, ActiveAE::MsgStreamFFmpegInfo::matrix_encoding, ActiveAE::MsgStreamFFmpegInfo::profile, Actor::Protocol::SendOutMessage(), ActiveAE::MsgStreamFFmpegInfo::stream, and ActiveAE::CActiveAEControlProtocol::STREAMFFMPEGINFO.
Referenced by ActiveAE::CActiveAEStream::SetFFmpegInfo().
SetStreamReplaygain()
void CActiveAE::SetStreamReplaygain (CActiveAEStream * stream, float rgain) protected
References ActiveAE::MsgStreamParameter::float_par, m_controlPort, ActiveAE::MsgStreamParameter::parameter, Actor::Protocol::SendOutMessage(), ActiveAE::MsgStreamParameter::stream, and ActiveAE::CActiveAEControlProtocol::STREAMRGAIN.
Referenced by ActiveAE::CActiveAEStream::SetReplayGain().
SetStreamResampleMode()
void CActiveAE::SetStreamResampleMode (CActiveAEStream * stream, int mode) protected
References ActiveAE::MsgStreamParameter::int_par, m_controlPort, ActiveAE::MsgStreamParameter::parameter, Actor::Protocol::SendOutMessage(), ActiveAE::MsgStreamParameter::stream, and ActiveAE::CActiveAEControlProtocol::STREAMRESAMPLEMODE.
Referenced by ActiveAE::CActiveAEStream::SetResampleMode().
SetStreamResampleRatio()
void CActiveAE::SetStreamResampleRatio (CActiveAEStream * stream, double ratio) protected
References ActiveAE::MsgStreamParameter::double_par, m_controlPort, ActiveAE::MsgStreamParameter::parameter, Actor::Protocol::SendOutMessage(), ActiveAE::MsgStreamParameter::stream, and ActiveAE::CActiveAEControlProtocol::STREAMRESAMPLERATIO.
Referenced by ActiveAE::CActiveAEStream::SetResampleRatio().
SetStreamVolume()
void CActiveAE::SetStreamVolume (CActiveAEStream * stream, float volume) protected
References ActiveAE::MsgStreamParameter::float_par, m_controlPort, ActiveAE::MsgStreamParameter::parameter, Actor::Protocol::SendOutMessage(), ActiveAE::MsgStreamParameter::stream, and ActiveAE::CActiveAEControlProtocol::STREAMVOLUME.
Referenced by ActiveAE::CActiveAEStream::SetVolume().
SetVolume()
void CActiveAE::SetVolume (const float volume) override virtual
Sets the master volume level of the AudioEngine.
Parameters
volume The new volume level between 0.0 and 1.0
Implements IAE.
References m_aeVolume, m_controlPort, Actor::Protocol::SendOutMessage(), and ActiveAE::CActiveAEControlProtocol::VOLUME.
SFlushStream()
void CActiveAE::SFlushStream (CActiveAEStream * stream) protected
References ActiveAE::CSyncError::Flush(), FlushEngine(), ActiveAE::CActiveAEStream::m_bufferedTime, ActiveAE::CActiveAEStream::m_paused, ActiveAE::CActiveAEStream::m_processingBuffers, ActiveAE::CActiveAEStream::m_processingSamples, m_stats, ActiveAE::CActiveAEStream::m_streamPort, m_streams, ActiveAE::CActiveAEStream::m_syncError, ActiveAE::CActiveAEStream::m_syncState, ActiveAE::CActiveAEStream::ResetFreeBuffers(), CAESyncInfo::SYNC_START, and ActiveAE::CEngineStats::UpdateStream().
Referenced by StateMachine().
Shutdown()
void CActiveAE::Shutdown () override virtual
Called when the application needs to terminate the engine.
Reimplemented from IAE.
References Dispose().
SStopSound()
void CActiveAE::SStopSound (CActiveAESound * sound) protected
References AE_CH_NULL, ActiveAE::CActiveAESound::GetChannel(), m_aeGUISoundForce, and m_sounds_playing.
Referenced by DiscardSound(), and StateMachine().
Start()
void CActiveAE::Start () override virtual
Initializes the AudioEngine, called by CFactory when it is time to initialize the audio engine.
Do not call this directly, CApplication will call this when it is ready
Implements IAE.
References ActiveAE::CActiveAEControlProtocol::ACC, CThread::Create(), ActiveAE::CActiveAEControlProtocol::INIT, CLog::Log(), LOGERROR, m_controlPort, m_inMsgEvent, Actor::Message::Release(), CEvent::Reset(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, and success.
StateMachine()
void CActiveAE::StateMachine (int signal, Protocol * port, Message * msg) protected
References ActiveAE::CActiveAEControlProtocol::ACC, ActiveAE::CActiveAEDataProtocol::ACC, AE_DEVTYPE_HDMI, AE_parentStates, AE_SOUND_IDLE, AE_SOUND_OFF, AE_TOP, AE_TOP_CONFIGURED, AE_TOP_CONFIGURED_IDLE, AE_TOP_CONFIGURED_PLAY, AE_TOP_CONFIGURED_SUSPEND, AE_TOP_ERROR, AE_TOP_RECONFIGURING, AE_TOP_UNCONFIGURED, AE_TOP_WAIT_PRECOND, ActiveAE::CActiveAEControlProtocol::APPFOCUSED, ActiveAE::CSinkControlProtocol::APPFOCUSED, ActiveAE::AudioSettings::atempoThreshold, ActiveAE::MsgStreamSample::buffer, ChangeResamplers(), ClearDiscardedBuffers(), Configure(), CreateStream(), Actor::Message::data, ActiveAE::AudioSettings::device, ActiveAE::CActiveAEControlProtocol::DEVICECHANGE, ActiveAE::CActiveAEControlProtocol::DEVICECOUNTCHANGE, ActiveAE::CActiveAESink::DeviceExist(), DiscardSound(), DiscardStream(), ActiveAE::CActiveAEControlProtocol::DISPLAYLOST, ActiveAE::CActiveAEControlProtocol::DISPLAYRESET, ActiveAE::MsgStreamParameter::double_par, DrainSink(), ActiveAE::CActiveAEDataProtocol::DRAINSTREAM, ActiveAE::AudioSettings::driver, ActiveAE::CActiveAESink::EnumerateSinkList(), ActiveAE::CActiveAEDataProtocol::ERR, fade, ActiveAE::MsgStreamFree::finish, ActiveAE::MsgStreamParameter::float_par, FlushEngine(), ActiveAE::CActiveAEControlProtocol::FLUSHSTREAM, ActiveAE::CActiveAEDataProtocol::FREESOUND, ActiveAE::CActiveAEDataProtocol::FREESTREAM, CAEUtil::GainToScale(), AEDelayStatus::GetDelay(), ActiveAE::CEngineStats::GetDelay(), ActiveAE::CActiveAESink::GetDeviceType(), ActiveAE::CActiveAEControlProtocol::GETSTATE, CServiceBroker::GetWinSystem(), ActiveAE::AudioSettings::guisoundmode, AE::CAESinkFactory::HasSinks(), HasWork(), ActiveAE::CActiveAEControlProtocol::INIT, ActiveAE::MsgStreamParameter::int_par, ActiveAE::CActiveAEControlProtocol::KEEPCONFIG, LoadSettings(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, ActiveAE::CActiveAEStream::m_amplify, m_bStateMachineSelfTrigger, m_controlPort, ActiveAE::CActiveAESink::m_controlPort, m_currDevice, m_dataPort, ActiveAE::CActiveAESink::m_dataPort, ActiveAE::CActiveAEStream::m_drain, m_extDeferData, m_extDrain, m_extDrainTimer, m_extError, m_extKeepConfig, m_extLastDeviceChange, m_extSuspended, m_extTimeout, ActiveAE::CActiveAEStream::m_fadingBase, m_isWinSysReg, ActiveAE::CActiveAEStream::m_limiter, m_mode, m_muted, ActiveAE::CActiveAEStream::m_paused, ActiveAE::CActiveAEStream::m_processingBuffers, ActiveAE::CActiveAEStream::m_processingSamples, ActiveAE::CActiveAEStream::m_profile, ActiveAE::CActiveAEStream::m_resampleIntegral, ActiveAE::CActiveAEStream::m_resampleMode, ActiveAE::CActiveAEStream::m_rgain, m_settings, m_sink, m_sinkBuffers, m_sinkHasVolume, m_sounds, m_sounds_playing, m_state, m_stats, ActiveAE::CActiveAEStream::m_streamPort, m_streams, ActiveAE::CActiveAEStream::m_syncState, m_volume, ActiveAE::CActiveAEStream::m_volume, m_volumeScaled, MODE_PCM, ActiveAE::CActiveAEControlProtocol::MUTE, NeedReconfigureBuffers(), NeedReconfigureSink(), ActiveAE::CActiveAEDataProtocol::NEWSOUND, ActiveAE::CActiveAEDataProtocol::NEWSTREAM, ActiveAE::MsgStreamParameter::parameter, ActiveAE::AudioSettings::passthroughdevice, ActiveAE::CActiveAEControlProtocol::PAUSESTREAM, CAEUtil::PercentToGain(), ActiveAE::CSampleBuffer::pkt, ActiveAE::CActiveAEDataProtocol::PLAYSOUND, Actor::Protocol::portName, Actor::Protocol::PurgeOut(), ActiveAE::CActiveAEControlProtocol::RECONFIGURE, CWinSystemBase::Register(), Actor::Message::Reply(), ResampleSounds(), ActiveAE::CActiveAEControlProtocol::RESUMESTREAM, ActiveAE::CSampleBuffer::Return(), ActiveAE::CSinkDataProtocol::RETURNSAMPLE, RunStages(), Actor::Protocol::SendOutMessage(), CAELimiter::SetAmplification(), ActiveAE::CSinkControlProtocol::SETNOISETYPE, ActiveAE::CSinkControlProtocol::SETSILENCETIMEOUT, ActiveAE::CEngineStats::SetSuspended(), SFlushStream(), ActiveAE::AudioSettings::silenceTimeoutMinutes, SStopSound(), ActiveAE::CActiveAEControlProtocol::STOPSOUND, ActiveAE::MsgStreamFree::stream, ActiveAE::MsgStreamSample::stream, ActiveAE::MsgStreamParameter::stream, ActiveAE::MsgStreamFade::stream, ActiveAE::MsgStreamFFmpegInfo::stream, ActiveAE::CActiveAEControlProtocol::STREAMAMP, ActiveAE::CActiveAEDataProtocol::STREAMDRAINED, ActiveAE::CActiveAEControlProtocol::STREAMFADE, ActiveAE::CActiveAEControlProtocol::STREAMFFMPEGINFO, ActiveAE::CSinkControlProtocol::STREAMING, ActiveAE::AudioSettings::streamNoise, ActiveAE::CActiveAEControlProtocol::STREAMRESAMPLEMODE, ActiveAE::CActiveAEControlProtocol::STREAMRESAMPLERATIO, ActiveAE::CActiveAEControlProtocol::STREAMRGAIN, ActiveAE::CActiveAEDataProtocol::STREAMSAMPLE, ActiveAE::CActiveAEControlProtocol::STREAMVOLUME, ActiveAE::CActiveAEControlProtocol::SUSPEND, CAESyncInfo::SYNC_START, ActiveAE::CActiveAEControlProtocol::TIMEOUT, UnconfigureSink(), ValidateOutputDevices(), ActiveAE::CActiveAEControlProtocol::VOLUME, and ActiveAE::CSinkControlProtocol::VOLUME.
Referenced by Process().
StopSound()
void CActiveAE::StopSound (CActiveAESound * sound) protected
References m_controlPort, Actor::Protocol::SendOutMessage(), and ActiveAE::CActiveAEControlProtocol::STOPSOUND.
Referenced by ActiveAE::CActiveAESound::Stop().
SupportsQualityLevel()
bool CActiveAE::SupportsQualityLevel (enum AEQuality level) override virtual
Returns true if AudioEngine supports specified quality level.
Returns
true if specified quality level is supported, otherwise false
Reimplemented from IAE.
References AE_QUALITY_HIGH, AE_QUALITY_LOW, and AE_QUALITY_MID.
Referenced by ActiveAE::CActiveAESettings::SettingOptionsAudioQualityLevelsFiller().
SupportsRaw()
bool CActiveAE::SupportsRaw (AEAudioFormat & format) override virtual
Returns true if the AudioEngine supports AE_FMT_RAW streams for use with formats such as IEC61937.
See also
CAEPackIEC61937::CAEPackIEC61937()
Returns
true if the AudioEngine is capable of RAW output
Reimplemented from IAE.
References ActiveAE::AudioSettings::ac3passthrough, AE_CONFIG_FIXED, ActiveAE::AudioSettings::dtshdpassthrough, ActiveAE::AudioSettings::dtspassthrough, ActiveAE::AudioSettings::eac3passthrough, CServiceBroker::GetSettingsComponent(), m_settings, m_sink, CSettings::SETTING_AUDIOOUTPUT_CONFIG, CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGHDEVICE, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, CAEStreamInfo::STREAM_TYPE_TRUEHD, ActiveAE::CActiveAESink::SupportsFormat(), and ActiveAE::AudioSettings::truehdpassthrough.
SupportsSilenceTimeout()
bool CActiveAE::SupportsSilenceTimeout () override virtual
Returns true if the AudioEngine supports drain mode which is not streaming silence when idle.
Returns
true if the AudioEngine is capable of drain mode
Reimplemented from IAE.
Referenced by ActiveAE::CActiveAESettings::SettingOptionsAudioStreamsilenceFiller().
Suspend()
bool CActiveAE::Suspend () override virtual
Suspends output and de-initializes sink.
Used to avoid conflicts with external players or to reduce power consumption
Returns
True if successful
Implements IAE.
References m_controlPort, Actor::Protocol::SendOutMessage(), and ActiveAE::CActiveAEControlProtocol::SUSPEND.
SyncStream()
CSampleBuffer * CActiveAE::SyncStream (CActiveAEStream * stream) protected
References ActiveAE::AudioSettings::atempoThreshold, ActiveAE::CActiveAEStream::CalcResampleRatio(), ActiveAE::CSyncError::Correction(), ActiveAE::CSyncError::Flush(), ActiveAE::CSyncError::Get(), IAEClockCallback::GetClockSpeed(), CAEStreamInfo::GetDuration(), ActiveAE::CActiveAEStream::GetErrorInterval(), CLog::Log(), LOGDEBUG, m_encoderFormat, ActiveAE::CActiveAEStream::m_format, AEAudioFormat::m_frames, ActiveAE::CActiveAEStream::m_lastSyncError, m_mode, ActiveAE::CActiveAEStream::m_pClock, ActiveAE::CActiveAEStream::m_processingBuffers, ActiveAE::CActiveAEStream::m_resampleIntegral, ActiveAE::CActiveAEStream::m_resampleMode, m_settings, m_silenceBuffers, AEAudioFormat::m_streamInfo, ActiveAE::CActiveAEStream::m_syncError, ActiveAE::CActiveAEStream::m_syncState, MODE_RAW, MODE_TRANSCODE, ActiveAE::CSampleBuffer::pkt, ActiveAE::CSampleBuffer::Return(), ActiveAE::CSyncError::SetErrorInterval(), CAESyncInfo::SYNC_ADJUST, CAESyncInfo::SYNC_INSYNC, CAESyncInfo::SYNC_MUTE, and CAESyncInfo::SYNC_START.
Referenced by RunStages().
UnconfigureSink()
void CActiveAE::UnconfigureSink () protected
References ActiveAE::CSinkControlProtocol::ACC, CLog::Log(), LOGERROR, ActiveAE::CActiveAESink::m_controlPort, m_currDevice, m_extError, m_inMsgEvent, m_sink, Actor::Message::Release(), CEvent::Reset(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, success, and ActiveAE::CSinkControlProtocol::UNCONFIGURE.
Referenced by StateMachine().
UnregisterAudioCallback()
void CActiveAE::UnregisterAudioCallback (IAudioCallback * pCallback) override virtual
Reimplemented from IAE.
References m_audioCallback, and m_vizLock.
UsesDtsCoreFallback()
bool CActiveAE::UsesDtsCoreFallback () override virtual
Returns true if the AudioEngine is currently configured to extract the DTS Core from DTS-HD streams.
Returns
true if the AudioEngine is currently configured to extract the DTS Core from DTS-HD streams
Reimplemented from IAE.
References m_settings, and ActiveAE::AudioSettings::usesdtscorefallback.
ValidateOutputDevices()
void CActiveAE::ValidateOutputDevices (bool saveChanges) protected
References ActiveAE::AudioSettings::device, CServiceBroker::GetSettingsComponent(), AE::AESinkDevice::IsSameDeviceAs(), LOGDEBUG, LOGWARNING, m_settings, m_sink, AE::CAESinkFactory::ParseDevice(), ActiveAE::AudioSettings::passthroughdevice, CSettings::SETTING_AUDIOOUTPUT_AUDIODEVICE, CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGHDEVICE, and ActiveAE::CActiveAESink::ValidateOuputDevice().
Referenced by StateMachine().
Friends And Related Symbol Documentation
CActiveAEBufferPoolResample
friend class CActiveAEBufferPoolResample friend
CActiveAESound
friend class CActiveAESound friend
CActiveAEStream
friend class CActiveAEStream friend
Referenced by CreateStream().
CSoundPacket
friend class CSoundPacket friend
Member Data Documentation
m_aeGUISoundForce
bool ActiveAE::CActiveAE::m_aeGUISoundForce protected
Referenced by CActiveAE(), Configure(), ResampleSounds(), and SStopSound().
m_aeMuted
bool ActiveAE::CActiveAE::m_aeMuted protected
Referenced by CActiveAE(), IsMuted(), and SetMute().
m_aeVolume
float ActiveAE::CActiveAE::m_aeVolume protected
Referenced by CActiveAE(), GetVolume(), and SetVolume().
m_audioCallback
std::vector<IAudioCallback*> ActiveAE::CActiveAE::m_audioCallback protected
Referenced by Configure(), RegisterAudioCallback(), RunStages(), and UnregisterAudioCallback().
m_bStateMachineSelfTrigger
bool ActiveAE::CActiveAE::m_bStateMachineSelfTrigger protected
Referenced by Process(), and StateMachine().
m_controlPort
CActiveAEControlProtocol ActiveAE::CActiveAE::m_controlPort protected
Referenced by DeviceChange(), DeviceCountChange(), Dispose(), FlushStream(), KeepConfiguration(), OnAppFocusChange(), OnLostDisplay(), OnResetDisplay(), OnSettingsChange(), PauseStream(), Process(), Resume(), SetMute(), SetStreamAmplification(), SetStreamFade(), SetStreamFFmpegInfo(), SetStreamReplaygain(), SetStreamResampleMode(), SetStreamResampleRatio(), SetStreamVolume(), SetVolume(), Start(), StateMachine(), StopSound(), and Suspend().
m_currDevice
std::string ActiveAE::CActiveAE::m_currDevice protected
Referenced by Configure(), NeedReconfigureSink(), StateMachine(), and UnconfigureSink().
m_dataPort
CActiveAEDataProtocol ActiveAE::CActiveAE::m_dataPort protected
Referenced by Dispose(), FreeSound(), FreeStream(), MakeSound(), MakeStream(), PlaySound(), Process(), and StateMachine().
m_discardBufferPools
std::list<std::unique_ptr<CActiveAEBufferPool> > ActiveAE::CActiveAE::m_discardBufferPools protected
Referenced by ClearDiscardedBuffers(), Configure(), and DiscardStream().
m_encoder
IAEEncoder* ActiveAE::CActiveAE::m_encoder protected
Referenced by CActiveAE(), Configure(), and RunStages().
m_encoderBuffers
std::unique_ptr<CActiveAEBufferPool> ActiveAE::CActiveAE::m_encoderBuffers protected
Referenced by Configure(), and RunStages().
m_encoderFormat
AEAudioFormat ActiveAE::CActiveAE::m_encoderFormat protected
Referenced by Configure(), and SyncStream().
m_extDeferData
bool ActiveAE::CActiveAE::m_extDeferData protected
Referenced by Process(), and StateMachine().
m_extDrain
bool ActiveAE::CActiveAE::m_extDrain protected
Referenced by Configure(), Process(), and StateMachine().
m_extDrainTimer
XbmcThreads::EndTime ActiveAE::CActiveAE::m_extDrainTimer protected
Referenced by StateMachine().
m_extError
bool ActiveAE::CActiveAE::m_extError protected
Referenced by DrainSink(), FlushEngine(), InitSink(), StateMachine(), and UnconfigureSink().
m_extKeepConfig
std::chrono::milliseconds ActiveAE::CActiveAE::m_extKeepConfig protected
Referenced by ApplySettingsToFormat(), Configure(), Process(), and StateMachine().
m_extLastDeviceChange
std::queue<time_t> ActiveAE::CActiveAE::m_extLastDeviceChange protected
Referenced by StateMachine().
m_extSuspended
bool ActiveAE::CActiveAE::m_extSuspended = false protected
Referenced by StateMachine().
m_extTimeout
std::chrono::milliseconds ActiveAE::CActiveAE::m_extTimeout protected
Referenced by Process(), and StateMachine().
m_inMsgEvent
CEvent ActiveAE::CActiveAE::m_inMsgEvent protected
Referenced by InitSink(), Resume(), Start(), and UnconfigureSink().
m_inputFormat
AEAudioFormat ActiveAE::CActiveAE::m_inputFormat protected
Referenced by GetInputFormat().
m_internalFormat
AEAudioFormat ActiveAE::CActiveAE::m_internalFormat protected
Referenced by ApplySettingsToFormat(), Configure(), ResampleSound(), and RunStages().
m_isWinSysReg
bool ActiveAE::CActiveAE::m_isWinSysReg = false protected
Referenced by Dispose(), and StateMachine().
[]
enum { ... } ActiveAE::CActiveAE::m_mode
Referenced by ApplySettingsToFormat(), CActiveAE(), Configure(), FlushEngine(), ResampleSound(), RunStages(), StateMachine(), and SyncStream().
m_muted
bool ActiveAE::CActiveAE::m_muted protected
Referenced by CActiveAE(), Deamplify(), RunStages(), and StateMachine().
m_outMsgEvent
CEvent ActiveAE::CActiveAE::m_outMsgEvent protected
Referenced by CreateStream(), Dispose(), and Process().
m_settings
AudioSettings ActiveAE::CActiveAE::m_settings protected
Referenced by ApplySettingsToFormat(), ChangeResamplers(), Configure(), InitSink(), LoadSettings(), NeedReconfigureBuffers(), NeedReconfigureSink(), ResampleSound(), ResampleSounds(), RunStages(), StateMachine(), SupportsRaw(), SyncStream(), UsesDtsCoreFallback(), and ValidateOutputDevices().
m_settingsHandler
std::unique_ptr<CActiveAESettings> ActiveAE::CActiveAE::m_settingsHandler protected
Referenced by CActiveAE(), and ~CActiveAE().
m_silenceBuffers
std::unique_ptr<CActiveAEBufferPool> ActiveAE::CActiveAE::m_silenceBuffers protected
Referenced by Configure(), GetInputFormat(), RunStages(), and SyncStream().
m_sink
CActiveAESink ActiveAE::CActiveAE::m_sink protected
Referenced by ApplySettingsToFormat(), Configure(), Dispose(), DrainSink(), EnumerateOutputDevices(), FlushEngine(), HasHDAudioChannelCount(), HasStereoAudioChannelCount(), InitSink(), IsSettingVisible(), LoadSettings(), Process(), RunStages(), StateMachine(), SupportsRaw(), UnconfigureSink(), and ValidateOutputDevices().
m_sinkBuffers
std::unique_ptr<CActiveAEBufferPoolResample> ActiveAE::CActiveAE::m_sinkBuffers protected
Referenced by Configure(), FlushEngine(), HasWork(), RunStages(), and StateMachine().
m_sinkFormat
AEAudioFormat ActiveAE::CActiveAE::m_sinkFormat protected
Referenced by Configure(), FlushEngine(), InitSink(), NeedReconfigureSink(), and RunStages().
m_sinkHasVolume
bool ActiveAE::CActiveAE::m_sinkHasVolume protected
Referenced by CActiveAE(), InitSink(), RunStages(), and StateMachine().
m_sinkRequestFormat
AEAudioFormat ActiveAE::CActiveAE::m_sinkRequestFormat protected
Referenced by Configure(), InitSink(), and NeedReconfigureBuffers().
m_sounds
std::vector<CActiveAESound*> ActiveAE::CActiveAE::m_sounds protected
Referenced by Configure(), DiscardSound(), ResampleSounds(), and StateMachine().
m_sounds_playing
std::list<SoundState> ActiveAE::CActiveAE::m_sounds_playing protected
Referenced by Configure(), HasWork(), MixSounds(), RunStages(), SStopSound(), and StateMachine().
m_state
int ActiveAE::CActiveAE::m_state protected
Referenced by Process(), and StateMachine().
m_stats
CEngineStats ActiveAE::CActiveAE::m_stats protected
Referenced by ApplySettingsToFormat(), CActiveAE(), Configure(), CreateStream(), DiscardStream(), FlushEngine(), GetCacheTime(), GetCacheTotal(), GetCurrentSinkFormat(), GetDelay(), GetMaxDelay(), GetSyncInfo(), InitSink(), IsSuspended(), RunStages(), SFlushStream(), and StateMachine().
m_streamIdGen
unsigned int ActiveAE::CActiveAE::m_streamIdGen protected
Referenced by CActiveAE(), and CreateStream().
m_streams
std::list<CActiveAEStream*> ActiveAE::CActiveAE::m_streams protected
Referenced by ApplySettingsToFormat(), ChangeResamplers(), Configure(), CreateStream(), DiscardStream(), GetInputFormat(), HasWork(), Process(), ResampleSounds(), RunStages(), SFlushStream(), and StateMachine().
m_vizBuffers
std::unique_ptr<CActiveAEBufferPoolResample> ActiveAE::CActiveAE::m_vizBuffers protected
Referenced by Configure(), FlushEngine(), and RunStages().
m_vizBuffersInput
std::unique_ptr<CActiveAEBufferPool> ActiveAE::CActiveAE::m_vizBuffersInput protected
Referenced by Configure(), and RunStages().
m_vizInitialized
bool ActiveAE::CActiveAE::m_vizInitialized protected
Referenced by CActiveAE(), Configure(), RegisterAudioCallback(), and RunStages().
m_vizLock
CCriticalSection ActiveAE::CActiveAE::m_vizLock protected
Referenced by RegisterAudioCallback(), RunStages(), and UnregisterAudioCallback().
m_volume
float ActiveAE::CActiveAE::m_volume protected
Referenced by CActiveAE(), Configure(), and StateMachine().
m_volumeScaled
float ActiveAE::CActiveAE::m_volumeScaled protected
Referenced by CActiveAE(), Deamplify(), and StateMachine().
The documentation for this class was generated from the following files:
ActiveAE.h
ActiveAE.cpp