Kodi Documentation: CUDisks2Provider::Filesystem Class Reference
CUDisks2Provider::Filesystem Class Reference
Public Member Functions
Filesystem (const char *object)
~Filesystem ()=default
bool Mount ()
bool Unmount ()
std::string GetDisplayName () const
Get the device display name/label.
bool IsApproved () const
Check if the device is approved/whitelisted.
bool IsMounted () const
Check if the device is mounted.
bool IsReady () const
Check if the device is ready.
bool IsOptical () const
Check if the device is optical.
MEDIA_DETECT::STORAGE::Type GetStorageType () const
Get the storage type of this device.
const std::string & GetMountPoint () const
Get the device mount point.
void ResetMountPoint ()
Reset the device mount point.
void SetMountPoint (const std::string &mountPoint)
Set the device mount point.
const std::string & GetObject () const
Get the device dbus object.
std::string ToString () const
Get a representation of the device as a readable string.
CMediaSource ToMediaShare () const
Get a representation of the device as a media share.
MEDIA_DETECT::STORAGE::StorageDevice ToStorageDevice () const
Get a representation of the device as a storage device abstraction.
Public Attributes
Block * m_block = nullptr
Private Attributes
bool m_isMounted = false
std::string m_object
std::string m_mountPoint
Constructor & Destructor Documentation
Filesystem()
CUDisks2Provider::Filesystem::Filesystem (const char * object) explicit
~Filesystem()
CUDisks2Provider::Filesystem::~Filesystem () default
Member Function Documentation
GetDisplayName()
std::string CUDisks2Provider::Filesystem::GetDisplayName () const
Get the device display name/label.
Returns
the device display name/label
References g_localizeStrings, and CLocalizeStrings::Get().
GetMountPoint()
const std::string & CUDisks2Provider::Filesystem::GetMountPoint () const inline
Get the device mount point.
Returns
the device mount point
References m_mountPoint.
GetObject()
const std::string & CUDisks2Provider::Filesystem::GetObject () const inline
Get the device dbus object.
Returns
the device dbus object
References m_object.
GetStorageType()
MEDIA_DETECT::STORAGE::Type CUDisks2Provider::Filesystem::GetStorageType () const
Get the storage type of this device.
Returns
the storage type (e.g. OPTICAL) or UNKNOWN if the type couldn't be detected
References MEDIA_DETECT::STORAGE::OPTICAL, and MEDIA_DETECT::STORAGE::UNKNOWN.
IsApproved()
bool CUDisks2Provider::Filesystem::IsApproved () const
Check if the device is approved/whitelisted.
Returns
true if the device is approved/whitelisted, false otherwise
IsMounted()
bool CUDisks2Provider::Filesystem::IsMounted () const
Check if the device is mounted.
Returns
true if the device is mounted, false otherwise
IsOptical()
bool CUDisks2Provider::Filesystem::IsOptical () const
Check if the device is optical.
Returns
true if the device is optical, false otherwise
IsReady()
bool CUDisks2Provider::Filesystem::IsReady () const
Check if the device is ready.
Returns
true if the device is ready, false otherwise
Mount()
bool CUDisks2Provider::Filesystem::Mount ()
References CUDisks2Provider::AppendEmptyOptions(), CDBusMessage::GetArgumentIter(), CLog::Log(), LOGDEBUG, CDBusMessage::SendSystem(), UDISKS2_INTERFACE_FILESYSTEM, and UDISKS2_SERVICE_UDISKS2.
ResetMountPoint()
void CUDisks2Provider::Filesystem::ResetMountPoint ()
Reset the device mount point.
SetMountPoint()
void CUDisks2Provider::Filesystem::SetMountPoint (const std::string & mountPoint)
Set the device mount point.
Parameters
mountPoint the device mount point
ToMediaShare()
CMediaSource CUDisks2Provider::Filesystem::ToMediaShare () const
Get a representation of the device as a media share.
Returns
the media share
References CMediaSource::m_iDriveType, CMediaSource::m_ignore, CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::SOURCE_TYPE_OPTICAL_DISC, CMediaSource::SOURCE_TYPE_REMOVABLE, CMediaSource::strName, and CMediaSource::strPath.
ToStorageDevice()
MEDIA_DETECT::STORAGE::StorageDevice CUDisks2Provider::Filesystem::ToStorageDevice () const
Get a representation of the device as a storage device abstraction.
Returns
the storage device abstraction of the device
References MEDIA_DETECT::STORAGE::StorageDevice::label, MEDIA_DETECT::STORAGE::StorageDevice::path, and MEDIA_DETECT::STORAGE::StorageDevice::type.
ToString()
std::string CUDisks2Provider::Filesystem::ToString () const
Get a representation of the device as a readable string.
Returns
device as a string
References BOOL2SZ.
Unmount()
bool CUDisks2Provider::Filesystem::Unmount ()
References CUDisks2Provider::AppendEmptyOptions(), CDBusMessage::GetArgumentIter(), CLog::Log(), LOGDEBUG, CDBusMessage::SendSystem(), UDISKS2_INTERFACE_FILESYSTEM, and UDISKS2_SERVICE_UDISKS2.
Member Data Documentation
m_block
Block* CUDisks2Provider::Filesystem::m_block = nullptr
m_isMounted
bool CUDisks2Provider::Filesystem::m_isMounted = false private
m_mountPoint
std::string CUDisks2Provider::Filesystem::m_mountPoint private
Referenced by GetMountPoint().
m_object
std::string CUDisks2Provider::Filesystem::m_object private
Referenced by GetObject().
The documentation for this class was generated from the following files:
UDisks2Provider.h
UDisks2Provider.cpp