Kodi Documentation: KODI::JOYSTICK::CFeatureAxis Class Reference
KODI::JOYSTICK::CFeatureAxis Class Reference
Input » Joystick
Axis of a feature (analog stick, accelerometer, etc)
#include <FeatureHandling.h>
Public Member Functions
CFeatureAxis (void)
void SetPositiveDistance (float distance)
Set value of positive axis.
void SetNegativeDistance (float distance)
Set value of negative axis.
float GetPosition (void) const
Get the final value of this axis.
void Reset (void)
Reset both positive and negative values to zero.
Protected Attributes
float m_positiveDistance
float m_negativeDistance
Detailed Description
Axis of a feature (analog stick, accelerometer, etc)
Axes are composed of two driver primitives, one for the positive semiaxis and one for the negative semiaxis.
This effectively means that an axis is two-dimensional, with each dimension either:
a digital value (0.0 or 1.0)
an analog value (continuous in the interval [0.0, 1.0])
Constructor & Destructor Documentation
CFeatureAxis()
KODI::JOYSTICK::CFeatureAxis::CFeatureAxis (void) inline
References Reset().
Member Function Documentation
GetPosition()
float KODI::JOYSTICK::CFeatureAxis::GetPosition (void) const inline
Get the final value of this axis.
This axis is two-dimensional, so we need to compress these into a single dimension. This is done by subtracting the negative from the positive. Some examples:
 Positive axis:  1.0 (User presses right or analog stick moves right)
 Negative axis:  0.0
 -------------------
 Pos - Neg:      1.0 (Emulated analog stick moves right)
 Positive axis:  0.0
 Negative axis:  1.0 (User presses left or analog stick moves left)
 -------------------
 Pos - Neg:     -1.0 (Emulated analog stick moves left)
 Positive axis:  1.0 (User presses both buttons)
 Negative axis:  1.0
 -------------------
 Pos - Neg:      0.0 (Emulated analog stick is centered)
References m_negativeDistance, and m_positiveDistance.
Referenced by KODI::JOYSTICK::CAxisFeature::ProcessMotions(), KODI::JOYSTICK::CAnalogStick::ProcessMotions(), and KODI::JOYSTICK::CAccelerometer::ProcessMotions().
Reset()
void KODI::JOYSTICK::CFeatureAxis::Reset (void) inline
Reset both positive and negative values to zero.
References m_negativeDistance, and m_positiveDistance.
Referenced by CFeatureAxis(), KODI::JOYSTICK::CWheel::OnAnalogMotion(), KODI::JOYSTICK::CThrottle::OnAnalogMotion(), KODI::JOYSTICK::CAnalogStick::OnAnalogMotion(), and KODI::JOYSTICK::CAccelerometer::OnAnalogMotion().
SetNegativeDistance()
void KODI::JOYSTICK::CFeatureAxis::SetNegativeDistance (float distance) inline
Set value of negative axis.
References m_negativeDistance.
Referenced by KODI::JOYSTICK::CWheel::OnAnalogMotion(), KODI::JOYSTICK::CThrottle::OnAnalogMotion(), and KODI::JOYSTICK::CAnalogStick::OnAnalogMotion().
SetPositiveDistance()
void KODI::JOYSTICK::CFeatureAxis::SetPositiveDistance (float distance) inline
Set value of positive axis.
References m_positiveDistance.
Referenced by KODI::JOYSTICK::CWheel::OnAnalogMotion(), KODI::JOYSTICK::CThrottle::OnAnalogMotion(), KODI::JOYSTICK::CAnalogStick::OnAnalogMotion(), and KODI::JOYSTICK::CAccelerometer::OnAnalogMotion().
Member Data Documentation
m_negativeDistance
float KODI::JOYSTICK::CFeatureAxis::m_negativeDistance protected
Referenced by GetPosition(), Reset(), and SetNegativeDistance().
m_positiveDistance
float KODI::JOYSTICK::CFeatureAxis::m_positiveDistance protected
Referenced by GetPosition(), Reset(), and SetPositiveDistance().
The documentation for this class was generated from the following file:
FeatureHandling.h