Kodi Documentation: CScraperParser Class Reference
CScraperParser Class Reference
#include <ScraperParser.h>
Public Member Functions
CScraperParser ()
CScraperParser (const CScraperParser &parser)
~CScraperParser ()
CScraperParser & operator= (const CScraperParser &parser)
bool Load (const std::string &strXMLFile)
bool IsNoop () const
void Clear ()
const std::string & GetFilename () const
std::string GetSearchStringEncoding () const
const std::string Parse (const std::string &strTag, ADDON::CScraper *scraper)
void AddDocument (const CXBMCTinyXML *doc)
Public Attributes
std::string m_param [MAX_SCRAPER_BUFFERS]
Private Member Functions
bool LoadFromXML ()
void ReplaceBuffers (std::string &strDest)
void ParseExpression (const std::string &input, std::string &dest, TiXmlElement *element, bool bAppend)
void ParseXSLT (const std::string &input, std::string &dest, TiXmlElement *element, bool bAppend)
Parse an 'XSLT' declaration from the scraper This allow us to transform an inbound XML document using XSLT to a different type of XML document, ready to be output direct to the album loaders or similar.
void ParseNext (TiXmlElement *element)
void Clean (std::string &strDirty)
void ConvertJSON (std::string &string)
void ClearBuffers ()
void GetBufferParams (bool *result, const char *attribute, bool defvalue)
void InsertToken (std::string &strOutput, int buf, const char *token)
Private Attributes
CXBMCTinyXML * m_document
TiXmlElement * m_pRootElement
const char * m_SearchStringEncoding
bool m_isNoop
std::string m_strFile
ADDON::CScraper * m_scraper
Constructor & Destructor Documentation
CScraperParser() [1/2]
CScraperParser::CScraperParser ()
References m_document, m_isNoop, m_pRootElement, m_scraper, and m_SearchStringEncoding.
CScraperParser() [2/2]
CScraperParser::CScraperParser (const CScraperParser & parser)
References m_document, m_isNoop, m_pRootElement, m_scraper, and m_SearchStringEncoding.
~CScraperParser()
CScraperParser::~CScraperParser ()
References Clear().
Member Function Documentation
AddDocument()
void CScraperParser::AddDocument (const CXBMCTinyXML * doc)
References m_pRootElement, and node.
Referenced by ADDON::CScraper::Load().
Clean()
void CScraperParser::Clean (std::string & strDirty) private
References HTML::CHTMLUtil::ConvertHTMLToW(), ConvertJSON(), g_charsetConverter, and HTML::CHTMLUtil::RemoveTags().
Referenced by ParseExpression().
Clear()
void CScraperParser::Clear ()
References m_document, m_pRootElement, and m_strFile.
Referenced by Load(), operator=(), TEST(), and ~CScraperParser().
ClearBuffers()
void CScraperParser::ClearBuffers () private
References m_param.
Referenced by Parse().
ConvertJSON()
void CScraperParser::ConvertJSON (std::string & string) private
References CRegExp::GetMatch(), CRegExp::GetSubLength(), CRegExp::GetSubStart(), CRegExp::RegComp(), and CRegExp::RegFind().
Referenced by Clean().
GetBufferParams()
void CScraperParser::GetBufferParams (bool * result, const char * attribute, bool defvalue) private
References index(), and MAX_SCRAPER_BUFFERS.
Referenced by ParseExpression().
GetFilename()
const std::string & CScraperParser::GetFilename () const inline
References m_strFile.
Referenced by TEST().
GetSearchStringEncoding()
std::string CScraperParser::GetSearchStringEncoding () const inline
References m_SearchStringEncoding.
Referenced by ADDON::CScraper::SearchStringEncoding(), and TEST().
InsertToken()
void CScraperParser::InsertToken (std::string & strOutput, int buf, const char * token) private
Referenced by ParseExpression().
IsNoop()
bool CScraperParser::IsNoop () const inline
References m_isNoop.
Referenced by ADDON::CScraper::IsNoop().
Load()
bool CScraperParser::Load (const std::string & strXMLFile)
References Clear(), CXBMCTinyXML::LoadFile(), LoadFromXML(), m_document, and m_strFile.
Referenced by ADDON::CScraper::Load(), and TEST().
LoadFromXML()
bool CScraperParser::LoadFromXML () private
References m_document, m_isNoop, m_pRootElement, and m_SearchStringEncoding.
Referenced by Load(), and operator=().
operator=()
CScraperParser & CScraperParser::operator= (const CScraperParser & parser)
References Clear(), LoadFromXML(), m_document, and m_scraper.
Parse()
const std::string CScraperParser::Parse (const std::string & strTag, ADDON::CScraper * scraper)
References ClearBuffers(), FirstChildScraperElement(), CLog::Log(), LOGERROR, m_param, m_pRootElement, m_scraper, and ParseNext().
Referenced by ADDON::CScraper::InternalRun().
ParseExpression()
void CScraperParser::ParseExpression (const std::string & input, std::string & dest, TiXmlElement * element, bool bAppend) private
References CRegExp::asciiOnly, CRegExp::autoUtf8, Clean(), CRegExp::forceUtf8, XMLUtils::GetAttribute(), GetBufferParams(), CRegExp::GetFindLen(), CRegExp::GetMatch(), CRegExp::GetReplaceString(), InsertToken(), m_param, MAX_SCRAPER_BUFFERS, CRegExp::RegComp(), CRegExp::RegFind(), and ReplaceBuffers().
Referenced by ParseNext().
ParseNext()
void CScraperParser::ParseNext (TiXmlElement * element) private
References FirstChildScraperElement(), ADDON::CAddon::GetSetting(), ADDON::CAddon::HasSettings(), CLog::Log(), LOGERROR, m_param, m_scraper, MAX_SCRAPER_BUFFERS, NextSiblingScraperElement(), ParseExpression(), ParseNext(), ParseXSLT(), and ReplaceBuffers().
Referenced by Parse(), and ParseNext().
ParseXSLT()
void CScraperParser::ParseXSLT (const std::string & input, std::string & dest, TiXmlElement * element, bool bAppend) private
Parse an 'XSLT' declaration from the scraper This allow us to transform an inbound XML document using XSLT to a different type of XML document, ready to be output direct to the album loaders or similar.
Parameters
input the input document
dest the output destination for the conversion
element the current XML element
bAppend append or clear the buffer
References CLog::Log(), LOGDEBUG, ReplaceBuffers(), XSLTUtils::SetInput(), XSLTUtils::SetStylesheet(), and XSLTUtils::XSLTTransform().
Referenced by ParseNext().
ReplaceBuffers()
void CScraperParser::ReplaceBuffers (std::string & strDest) private
References g_localizeStrings, CLocalizeStrings::GetAddonString(), ADDON::CAddon::GetSetting(), ADDON::CAddon::ID(), m_param, m_scraper, MAX_SCRAPER_BUFFERS, and strReplace().
Referenced by ParseExpression(), ParseNext(), and ParseXSLT().
Member Data Documentation
m_document
CXBMCTinyXML* CScraperParser::m_document private
Referenced by Clear(), CScraperParser(), CScraperParser(), Load(), LoadFromXML(), and operator=().
m_isNoop
bool CScraperParser::m_isNoop private
Referenced by CScraperParser(), CScraperParser(), IsNoop(), and LoadFromXML().
m_param
std::string CScraperParser::m_param[MAX_SCRAPER_BUFFERS]
Referenced by ClearBuffers(), ADDON::CScraper::InternalRun(), Parse(), ParseExpression(), ParseNext(), ReplaceBuffers(), and ADDON::CScraper::Run().
m_pRootElement
TiXmlElement* CScraperParser::m_pRootElement private
Referenced by AddDocument(), Clear(), CScraperParser(), CScraperParser(), LoadFromXML(), and Parse().
m_scraper
ADDON::CScraper* CScraperParser::m_scraper private
Referenced by CScraperParser(), CScraperParser(), operator=(), Parse(), ParseNext(), and ReplaceBuffers().
m_SearchStringEncoding
const char* CScraperParser::m_SearchStringEncoding private
Referenced by CScraperParser(), CScraperParser(), GetSearchStringEncoding(), and LoadFromXML().
m_strFile
std::string CScraperParser::m_strFile private
Referenced by Clear(), GetFilename(), and Load().
The documentation for this class was generated from the following files:
ScraperParser.h
ScraperParser.cpp