Kodi Documentation: XFILE::CPVRDirectory Class Reference
XFILE::CPVRDirectory Class Reference
#include <PVRDirectory.h>
Public Member Functions
CPVRDirectory ()
~CPVRDirectory () override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool AllowAll () const override
Whether to allow all files/folders to be listed.
DIR_CACHE_TYPE GetCacheType (const CURL &url) const override
How this directory should be cached.
bool Exists (const CURL &url) override
Check for directory existence.
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool Create (const CURL &url)
Create the directory.
virtual bool Remove (const CURL &url)
Removes the directory.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Static Public Member Functions
static bool SupportsWriteFileOperations (const std::string &strPath)
static bool HasTVRecordings ()
static bool HasDeletedTVRecordings ()
static bool HasRadioRecordings ()
static bool HasDeletedRadioRecordings ()
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Additional Inherited Members
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CPVRDirectory()
CPVRDirectory::CPVRDirectory () default
~CPVRDirectory()
CPVRDirectory::~CPVRDirectory () override default
Member Function Documentation
AllowAll()
bool XFILE::CPVRDirectory::AllowAll () const inline override virtual
Whether to allow all files/folders to be listed.
Returns
Returns true if all files/folder should be listed.
Reimplemented from XFILE::IDirectory.
Exists()
bool CPVRDirectory::Exists (const CURL & url) override virtual
Check for directory existence.
Parameters
url Directory to check.
Returns
Returns true, if directory exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
References PVR::CPVRGUIDirectory::Exists().
GetCacheType()
DIR_CACHE_TYPE XFILE::CPVRDirectory::GetCacheType (const CURL & url) const inline override virtual
How this directory should be cached.
Parameters
url Directory at hand.
Returns
Returns the cache type.
Reimplemented from XFILE::IDirectory.
References XFILE::DIR_CACHE_NEVER.
GetDirectory()
bool CPVRDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References PVR::CPVRGUIDirectory::GetDirectory().
HasDeletedRadioRecordings()
bool CPVRDirectory::HasDeletedRadioRecordings () static
References PVR::CPVRGUIDirectory::HasDeletedRadioRecordings().
Referenced by CGUIDialogMediaSource::OnPathBrowse().
HasDeletedTVRecordings()
bool CPVRDirectory::HasDeletedTVRecordings () static
References PVR::CPVRGUIDirectory::HasDeletedTVRecordings().
Referenced by CGUIDialogMediaSource::OnPathBrowse().
HasRadioRecordings()
bool CPVRDirectory::HasRadioRecordings () static
References PVR::CPVRGUIDirectory::HasRadioRecordings().
Referenced by CGUIDialogMediaSource::OnPathBrowse().
HasTVRecordings()
bool CPVRDirectory::HasTVRecordings () static
References PVR::CPVRGUIDirectory::HasTVRecordings().
Referenced by CGUIDialogMediaSource::OnPathBrowse().
SupportsWriteFileOperations()
bool CPVRDirectory::SupportsWriteFileOperations (const std::string & strPath) static
References PVR::CPVRGUIDirectory::SupportsWriteFileOperations().
Referenced by CUtil::SupportsWriteFileOperations().
The documentation for this class was generated from the following files:
PVRDirectory.h
PVRDirectory.cpp