Kodi Documentation: EVENTPACKET::CEventPacket Class Reference
EVENTPACKET::CEventPacket Class Reference
#include <EventPacket.h>
Public Member Functions
CEventPacket ()=default
CEventPacket (int datasize, const void *data)
virtual ~CEventPacket ()=default
virtual bool Parse (int datasize, const void *data)
bool IsValid () const
PacketType Type () const
unsigned int Size () const
unsigned int Sequence () const
const uint8_t * Payload () const
unsigned int PayloadSize () const
unsigned int ClientToken () const
void SetPayload (std::vector< uint8_t > payload)
Protected Attributes
bool m_bValid {false}
unsigned int m_iSeq {0}
unsigned int m_iTotalPackets {0}
unsigned char m_header [32]
std::vector< uint8_t > m_pPayload
unsigned int m_iClientToken {0}
unsigned char m_cMajVer {'0'}
unsigned char m_cMinVer {'0'}
PacketType m_eType {PT_LAST}
Constructor & Destructor Documentation
CEventPacket() [1/2]
EVENTPACKET::CEventPacket::CEventPacket () default
CEventPacket() [2/2]
EVENTPACKET::CEventPacket::CEventPacket (int datasize, const void * data) inline explicit
References data(), and Parse().
~CEventPacket()
virtual EVENTPACKET::CEventPacket::~CEventPacket () virtual default
Member Function Documentation
ClientToken()
unsigned int EVENTPACKET::CEventPacket::ClientToken () const inline
References m_iClientToken.
IsValid()
bool EVENTPACKET::CEventPacket::IsValid () const inline
References m_bValid.
Parse()
bool CEventPacket::Parse (int datasize, const void * data) virtual
References data(), EVENTPACKET::HEADER_SIG, EVENTPACKET::HEADER_SIG_LENGTH, EVENTPACKET::HEADER_SIZE, m_bValid, m_cMajVer, m_cMinVer, m_eType, m_iClientToken, m_iSeq, m_iTotalPackets, m_pPayload, EVENTPACKET::PACKET_SIZE, EVENTPACKET::PT_HELO, and EVENTPACKET::PT_LAST.
Referenced by CEventPacket().
Payload()
const uint8_t * EVENTPACKET::CEventPacket::Payload () const inline
References m_pPayload.
Referenced by EVENTCLIENT::CEventClient::OnPacketACTION(), EVENTCLIENT::CEventClient::OnPacketBUTTON(), EVENTCLIENT::CEventClient::OnPacketHELO(), EVENTCLIENT::CEventClient::OnPacketLOG(), EVENTCLIENT::CEventClient::OnPacketMOUSE(), and EVENTCLIENT::CEventClient::OnPacketNOTIFICATION().
PayloadSize()
unsigned int EVENTPACKET::CEventPacket::PayloadSize () const inline
References m_pPayload.
Referenced by EVENTCLIENT::CEventClient::OnPacketACTION(), EVENTCLIENT::CEventClient::OnPacketBUTTON(), EVENTCLIENT::CEventClient::OnPacketHELO(), EVENTCLIENT::CEventClient::OnPacketLOG(), EVENTCLIENT::CEventClient::OnPacketMOUSE(), and EVENTCLIENT::CEventClient::OnPacketNOTIFICATION().
Sequence()
unsigned int EVENTPACKET::CEventPacket::Sequence () const inline
References m_iSeq.
SetPayload()
void CEventPacket::SetPayload (std::vector< uint8_t > payload)
References m_pPayload.
Size()
unsigned int EVENTPACKET::CEventPacket::Size () const inline
References m_iTotalPackets.
Type()
PacketType EVENTPACKET::CEventPacket::Type () const inline
References m_eType.
Referenced by EVENTCLIENT::CEventClient::ProcessPacket().
Member Data Documentation
m_bValid
bool EVENTPACKET::CEventPacket::m_bValid {false} protected
Referenced by IsValid(), and Parse().
m_cMajVer
unsigned char EVENTPACKET::CEventPacket::m_cMajVer {'0'} protected
Referenced by Parse().
m_cMinVer
unsigned char EVENTPACKET::CEventPacket::m_cMinVer {'0'} protected
Referenced by Parse().
m_eType
PacketType EVENTPACKET::CEventPacket::m_eType {PT_LAST} protected
Referenced by Parse(), and Type().
m_header
unsigned char EVENTPACKET::CEventPacket::m_header[32] protected
m_iClientToken
unsigned int EVENTPACKET::CEventPacket::m_iClientToken {0} protected
Referenced by ClientToken(), and Parse().
m_iSeq
unsigned int EVENTPACKET::CEventPacket::m_iSeq {0} protected
Referenced by Parse(), and Sequence().
m_iTotalPackets
unsigned int EVENTPACKET::CEventPacket::m_iTotalPackets {0} protected
Referenced by Parse(), and Size().
m_pPayload
std::vector<uint8_t> EVENTPACKET::CEventPacket::m_pPayload protected
Referenced by Parse(), Payload(), PayloadSize(), and SetPayload().
The documentation for this class was generated from the following files:
EventPacket.h
EventPacket.cpp