Kodi Documentation: CLocale Class Reference
CLocale Class Reference
Class representing a full locale of the form [language[_territory][.codeset][@modifier]].
#include <Locale.h>
Public Member Functions
CLocale ()
CLocale (const std::string &language)
CLocale (const std::string &language, const std::string &territory)
CLocale (const std::string &language, const std::string &territory, const std::string &codeset)
CLocale (const std::string &language, const std::string &territory, const std::string &codeset, const std::string &modifier)
~CLocale ()
bool operator== (const CLocale &other) const
bool operator!= (const CLocale &other) const
bool IsValid () const
Whether the locale is valid or not.
const std::string & GetLanguageCode () const
Returns the (lower-case) ISO 639-1 language code of the locale.
const std::string & GetTerritoryCode () const
Returns the (upper-case) ISO 3166-1 Alpha-2 territory code of the locale.
const std::string & GetCodeset () const
Returns the codeset of the locale.
const std::string & GetModifier () const
Returns the modifier of the locale.
std::string ToString () const
Returns the full string representation of the locale.
std::string ToStringLC () const
Returns the full string representation of the locale in lowercase.
std::string ToShortString () const
Returns the short string representation of the locale.
std::string ToShortStringLC () const
Returns the short string representation of the locale in lowercase.
bool Equals (const std::string &locale) const
Checks if the given string representation of a locale exactly matches the locale.
bool Matches (const std::string &locale) const
Checks if the given string representation of a locale partly matches the locale.
std::string FindBestMatch (const std::set< std::string > &locales) const
Tries to find the locale in the given list that matches this locale best.
std::string FindBestMatch (const std::unordered_map< std::string, std::string > &locales) const
Tries to find the locale in the given list that matches this locale best.
Static Public Member Functions
static CLocale FromString (const std::string &locale)
Parses the given string representation and turns it into a locale.
Static Public Attributes
static const CLocale Empty
Empty (and invalid) CLocale instance.
Private Member Functions
void Initialize ()
int GetMatchRank (const std::string &locale) const
Static Private Member Functions
static bool CheckValidity (const std::string &language, const std::string &territory, const std::string &codeset, const std::string &modifier)
static bool ParseLocale (const std::string &locale, std::string &language, std::string &territory, std::string &codeset, std::string &modifier)
Private Attributes
bool m_valid = false
std::string m_language
std::string m_territory
std::string m_codeset
std::string m_modifier
Detailed Description
Class representing a full locale of the form [language[_territory][.codeset][@modifier]].
Constructor & Destructor Documentation
CLocale() [1/5]
CLocale::CLocale ()
Referenced by FromString().
CLocale() [2/5]
CLocale::CLocale (const std::string & language) explicit
References m_codeset, m_language, m_modifier, m_territory, m_valid, and ParseLocale().
CLocale() [3/5]
CLocale::CLocale (const std::string & language, const std::string & territory)
References Initialize().
CLocale() [4/5]
CLocale::CLocale (const std::string & language, const std::string & territory, const std::string & codeset)
References Initialize().
CLocale() [5/5]
CLocale::CLocale (const std::string & language, const std::string & territory, const std::string & codeset, const std::string & modifier)
References Initialize().
~CLocale()
CLocale::~CLocale () default
Member Function Documentation
CheckValidity()
bool CLocale::CheckValidity (const std::string & language, const std::string & territory, const std::string & codeset, const std::string & modifier) static private
Referenced by Initialize(), and ParseLocale().
Equals()
bool CLocale::Equals (const std::string & locale) const
Checks if the given string representation of a locale exactly matches the locale.
Parameters
locale String representation of a locale
Returns
True if the string representation matches the locale, false otherwise.
References FromString().
Referenced by TEST().
FindBestMatch() [1/2]
std::string CLocale::FindBestMatch (const std::set< std::string > & locales) const
Tries to find the locale in the given list that matches this locale best.
Parameters
locales List of string representations of locales
Returns
Best matching locale from the given list or empty string.
References Equals, and GetMatchRank().
FindBestMatch() [2/2]
std::string CLocale::FindBestMatch (const std::unordered_map< std::string, std::string > & locales) const
Tries to find the locale in the given list that matches this locale best.
Parameters
locales Map list of string representations of locales with first as locale identifier
Returns
Best matching locale from the given list or empty string.
Remarks
Used from CAddonInfo::GetTranslatedText to prevent copy from map to set.
References Equals, and GetMatchRank().
FromString()
CLocale CLocale::FromString (const std::string & locale) static
Parses the given string representation and turns it into a locale.
Parameters
locale String representation of a locale
References CLocale().
Referenced by Equals(), GetMatchRank(), Matches(), and TEST().
GetCodeset()
const std::string & CLocale::GetCodeset () const inline
Returns the codeset of the locale.
References m_codeset.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetLanguageCode()
const std::string & CLocale::GetLanguageCode () const inline
Returns the (lower-case) ISO 639-1 language code of the locale.
References m_language.
Referenced by ADDON::CLanguageResource::CLanguageResource(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetMatchRank()
int CLocale::GetMatchRank (const std::string & locale) const private
References FromString(), m_codeset, m_language, m_modifier, m_territory, m_valid, and rank.
Referenced by FindBestMatch(), and FindBestMatch().
GetModifier()
const std::string & CLocale::GetModifier () const inline
Returns the modifier of the locale.
References m_modifier.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetTerritoryCode()
const std::string & CLocale::GetTerritoryCode () const inline
Returns the (upper-case) ISO 3166-1 Alpha-2 territory code of the locale.
References m_territory.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
Initialize()
void CLocale::Initialize () private
References CheckValidity(), m_codeset, m_language, m_modifier, m_territory, and m_valid.
Referenced by CLocale(), CLocale(), and CLocale().
IsValid()
bool CLocale::IsValid () const inline
Whether the locale is valid or not.
A locale is considered valid if at least the language code is set.
References m_valid.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
Matches()
bool CLocale::Matches (const std::string & locale) const
Checks if the given string representation of a locale partly matches the locale.
Partial matching means that every available locale part needs to match the same locale part of the other locale if present.
Parameters
locale String representation of a locale
Returns
True if the string representation matches the locale, false otherwise.
References FromString(), m_codeset, m_language, m_modifier, m_territory, and m_valid.
operator!=()
bool CLocale::operator!= (const CLocale & other) const inline
operator==()
bool CLocale::operator== (const CLocale & other) const
References m_codeset, m_language, m_modifier, m_territory, and m_valid.
ParseLocale()
bool CLocale::ParseLocale (const std::string & locale, std::string & language, std::string & territory, std::string & codeset, std::string & modifier) static private
References CheckValidity().
Referenced by CLocale().
ToShortString()
std::string CLocale::ToShortString () const
Returns the short string representation of the locale.
The format of the short string representation is [language[_territory] where the language is represented as a (lower-case) two character ISO 639-1 code and the territory is represented as a (upper-case) two character ISO 3166-1 Alpha-2 code.
References m_language, m_territory, and m_valid.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), ToShortStringLC(), and ToString().
ToShortStringLC()
std::string CLocale::ToShortStringLC () const
Returns the short string representation of the locale in lowercase.
The format of the short string representation is [language[_territory] where the language is represented as a two character ISO 639-1 code and the territory is represented as a two character ISO 3166-1 Alpha-2 code.
References m_valid, and ToShortString().
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
ToString()
std::string CLocale::ToString () const
Returns the full string representation of the locale.
The format of the string representation is [language[_territory][.codeset][@modifier]] where the language is represented as a (lower-case) two character ISO 639-1 code and the territory is represented as a (upper-case) two character ISO 3166-1 Alpha-2 code.
References m_codeset, m_modifier, m_valid, and ToShortString().
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and ToStringLC().
ToStringLC()
std::string CLocale::ToStringLC () const
Returns the full string representation of the locale in lowercase.
The format of the string representation is language[_territory][.codeset][@modifier]] where the language is represented as a two character ISO 639-1 code and the territory is represented as a two character ISO 3166-1 Alpha-2 code.
References m_valid, and ToString().
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
Member Data Documentation
Empty
const CLocale CLocale::Empty static
Empty (and invalid) CLocale instance.
Referenced by CLangInfo::GetLocale(), and TEST().
m_codeset
std::string CLocale::m_codeset private
Referenced by CLocale(), GetCodeset(), GetMatchRank(), Initialize(), Matches(), operator==(), and ToString().
m_language
std::string CLocale::m_language private
Referenced by CLocale(), GetLanguageCode(), GetMatchRank(), Initialize(), Matches(), operator==(), and ToShortString().
m_modifier
std::string CLocale::m_modifier private
Referenced by CLocale(), GetMatchRank(), GetModifier(), Initialize(), Matches(), operator==(), and ToString().
m_territory
std::string CLocale::m_territory private
Referenced by CLocale(), GetMatchRank(), GetTerritoryCode(), Initialize(), Matches(), operator==(), and ToShortString().
m_valid
bool CLocale::m_valid = false private
Referenced by CLocale(), GetMatchRank(), Initialize(), IsValid(), Matches(), operator==(), ToShortString(), ToShortStringLC(), ToString(), and ToStringLC().
The documentation for this class was generated from the following files:
Locale.h
Locale.cpp