var searchData=
[
  ['2_201_20types_20of_20driver_20primitives_0',['2.1. Types of driver primitives',['../d4/dfe/group__cpp__kodi__addon__peripheral___docs___controller_input___joystick_drivers.html#autotoc_md13',1,'']]],
  ['2_20casts_1',['12.2. Casts',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1215',1,'']]],
  ['2_20channel_2',['2. Channel',['../dd/dd7/group__cpp__kodi__addon__pvr___defs___channel.html',1,'']]],
  ['2_20channels_20required_3',['2. Channels (required)',['../df/d40/group__cpp__kodi__addon__pvr___channels.html',1,'']]],
  ['2_20const_20correctness_4',['11.2. Const correctness',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1208',1,'']]],
  ['2_20constants_5',['8.2. Constants',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1193',1,'']]],
  ['2_20dialogs_6',['2. Dialogs',['../db/d44/group__cpp__kodi__gui__dialogs.html',1,'']]],
  ['2_20doxygen_7',['9.2. Doxygen',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1204',1,'']]],
  ['2_20file_20editing_20functions_8',['2. File editing functions',['../d6/d60/group__cpp__kodi__addon__vfs__filecontrol.html',1,'']]],
  ['2_20file_20functions_9',['2. File functions',['../d6/d3e/group__cpp__kodi__vfs___file.html',1,'']]],
  ['2_20game_20operations_10',['2. Game operations',['../d4/d54/group__cpp__kodi__addon__game___operation.html',1,'']]],
  ['2_20gui_20list_20item_20kodi_3a_3agui_3a_3aclistitem_11',['2. GUI list item (kodi::gui::CListItem)',['../d7/d0c/group__cpp__kodi__gui__windows__listitem.html',1,'']]],
  ['2_20indentation_12',['3.2. Indentation',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1167',1,'']]],
  ['2_20joystick_20drivers_13',['2 joystick drivers',['../d4/dfe/group__cpp__kodi__addon__peripheral___docs___controller_input___joystick_drivers.html#autotoc_md12',1,'2. Joystick drivers'],['../d4/dfe/group__cpp__kodi__addon__peripheral___docs___controller_input___joystick_drivers.html',1,'2. Joystick drivers']]],
  ['2_20joystick_20operations_14',['2. Joystick operations',['../de/d2e/group__cpp__kodi__addon__peripheral__joystick_op.html',1,'']]],
  ['2_20language_20standard_15',['2. Language standard',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1163',1,'']]],
  ['2_20local_20functions_16',['6.2. Local functions',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1187',1,'']]],
  ['2_20multiple_20declarations_17',['5.2. Multiple declarations',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1181',1,'']]],
  ['2_20peripheral_18',['2. Peripheral',['../d8/d0d/group__cpp__kodi__addon__peripheral___defs___peripheral.html',1,'']]],
  ['2_20receiving_20joystick_20events_19',['2 receiving joystick events',['../d9/dea/group__cpp__kodi__addon__peripheral___docs___lifetime___receiving.html#autotoc_md28',1,'2. Receiving joystick events'],['../d9/dea/group__cpp__kodi__addon__peripheral___docs___lifetime___receiving.html',1,'2. Receiving joystick events']]],
  ['2_20recording_20stream_20',['8.2. Recording stream',['../dd/dc3/group__cpp__kodi__addon__pvr___streams___recording.html',1,'']]],
  ['2_20stream_20constants_21',['2. Stream constants',['../da/d7f/group__cpp__kodi__addon__inputstream___defs___stream_constants.html',1,'']]],
  ['2_20stream_20demuxing_20optional_22',['2. Stream demuxing (optional)',['../da/d1b/group__cpp__kodi__addon__inputstream___demux.html',1,'']]],
  ['2_20switch_20case_23',['3.3.2. switch case',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1170',1,'']]],
  ['2_20tt_20switch_20tt_20default_20case_24',['4.2. &lt;tt&gt;switch&lt;/tt&gt; default case',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1178',1,'']]],
  ['2_20use_20c_20wrappers_20for_20c_20headers_25',['7.2. Use C++ wrappers for C headers',['../df/d02/md__2tmp_2xbmc_2docs_2_c_o_d_e___g_u_i_d_e_l_i_n_e_s.html#autotoc_md1190',1,'']]],
  ['2_20video_20stream_26',['2. Video stream',['../d1/dc2/group__cpp__kodi__addon__game___defs___video_stream.html',1,'']]]
];
