var searchData=
[
  ['d3dpalette_0',['D3DPalette',['../d5/d94/struct_d3_d_palette.html',1,'']]],
  ['d3dtexture_1',['D3DTexture',['../d3/ddf/struct_d3_d_texture.html',1,'']]],
  ['daoperationcontext_2',['DAOperationContext',['../d4/dd3/classanonymous__namespace_02_o_s_x_storage_provider_8cpp_03_1_1_d_a_operation_context.html',1,'anonymous_namespace{OSXStorageProvider.cpp}']]],
  ['darwinembednowplayinginfomanager_3',['DarwinEmbedNowPlayingInfoManager',['../dc/dc2/interface_darwin_embed_now_playing_info_manager.html',1,'']]],
  ['data_4',['Data',['../d1/d2a/struct_k_o_d_i_1_1_c_signal_handler_list_1_1_data.html',1,'KODI::CSignalHandlerList']]],
  ['database_5',['Database',['../d3/d50/classdbiplus_1_1_database.html',1,'dbiplus']]],
  ['databasesettings_6',['DatabaseSettings',['../d2/d70/class_database_settings.html',1,'']]],
  ['databaseutils_7',['DatabaseUtils',['../d4/dc0/class_database_utils.html',1,'']]],
  ['dataholder_8',['DataHolder',['../d7/d25/struct_data_holder.html',1,'']]],
  ['dataset_9',['Dataset',['../da/df6/classdbiplus_1_1_dataset.html',1,'dbiplus']]],
  ['datasetfieldinfo_10',['DatasetFieldInfo',['../d7/dcf/struct_c_database_1_1_dataset_field_info.html',1,'CDatabase']]],
  ['datasetlayout_11',['DatasetLayout',['../d7/d77/class_c_database_1_1_dataset_layout.html',1,'CDatabase']]],
  ['dberrors_12',['DbErrors',['../dd/d9e/classdbiplus_1_1_db_errors.html',1,'dbiplus']]],
  ['dbusconnectiondeleter_13',['DBusConnectionDeleter',['../db/d96/struct_c_d_bus_connection_1_1_d_bus_connection_deleter.html',1,'CDBusConnection']]],
  ['dbusmessagedeleter_14',['DBusMessageDeleter',['../d2/d95/struct_d_bus_message_deleter.html',1,'']]],
  ['ddcaps2_15',['ddcaps2',['../d1/d2c/struct_c_d_d_s_image_1_1ddcaps2.html',1,'CDDSImage']]],
  ['ddpixelformat_16',['ddpixelformat',['../de/d84/struct_c_d_d_s_image_1_1ddpixelformat.html',1,'CDDSImage']]],
  ['ddsurfacedesc2_17',['ddsurfacedesc2',['../d5/d53/struct_c_d_d_s_image_1_1ddsurfacedesc2.html',1,'CDDSImage']]],
  ['debug_5finfo_5fplayer_18',['DEBUG_INFO_PLAYER',['../dd/ddd/struct_d_e_b_u_g___i_n_f_o___p_l_a_y_e_r.html',1,'']]],
  ['debug_5finfo_5frender_19',['DEBUG_INFO_RENDER',['../df/d94/struct_d_e_b_u_g___i_n_f_o___r_e_n_d_e_r.html',1,'']]],
  ['debug_5finfo_5fvideo_20',['DEBUG_INFO_VIDEO',['../d8/db1/struct_d_e_b_u_g___i_n_f_o___v_i_d_e_o.html',1,'']]],
  ['debuglogsharingpresenter_21',['DebugLogSharingPresenter',['../d2/d66/class_debug_log_sharing_presenter.html',1,'']]],
  ['defaultfiltershader_22',['defaultfiltershader',['../d5/dea/class_shaders_1_1_g_l_1_1_default_filter_shader.html',1,'Shaders::GL::DefaultFilterShader'],['../dd/d08/class_shaders_1_1_g_l_e_s_1_1_default_filter_shader.html',1,'Shaders::GLES::DefaultFilterShader']]],
  ['delayedcallguard_23',['DelayedCallGuard',['../d9/d64/class_x_b_m_c_addon_1_1_delayed_call_guard.html',1,'XBMCAddon']]],
  ['delete_5fclirccontainer_24',['delete_CLircContainer',['../d8/d5a/struct_o_p_t_i_o_n_a_l_s_1_1delete___c_lirc_container.html',1,'OPTIONALS']]],
  ['delete_5fcvaapiproxy_25',['delete_cvaapiproxy',['../d7/dcf/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_win_system_gbm_e_g_l_context_1_1delete___c_vaapi_proxy.html',1,'KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::delete_CVaapiProxy'],['../d9/d95/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_w_a_y_l_a_n_d_1_1_c_win_system_wayland_e_g_l_context_g_l_1_1delete___c_vaapi_proxy.html',1,'KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::delete_CVaapiProxy'],['../da/dac/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_w_a_y_l_a_n_d_1_1_c_win_system_wayland_e_g_l_context_g_l_e_s_1_1delete___c_vaapi_proxy.html',1,'KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::delete_CVaapiProxy'],['../d3/d32/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_x11_1_1_c_win_system_x11_g_l_context_1_1delete___c_vaapi_proxy.html',1,'KODI::WINDOWING::X11::CWinSystemX11GLContext::delete_CVaapiProxy']]],
  ['deleter_26',['Deleter',['../da/dd5/classxbmcutil_1_1_globals_singleton_1_1_deleter.html',1,'xbmcutil::GlobalsSingleton']]],
  ['deleter_3c_20std_3a_3ashared_5fptr_3c_20t_20_3e_20_3e_27',['Deleter&lt; std::shared_ptr&lt; T &gt; &gt;',['../da/dd5/classxbmcutil_1_1_globals_singleton_1_1_deleter.html',1,'xbmcutil::GlobalsSingleton']]],
  ['deletestream_28',['DeleteStream',['../d2/d1d/struct_k_o_d_i_1_1_r_e_t_r_o_1_1_delete_stream.html',1,'KODI::RETRO']]],
  ['deltapair_29',['DeltaPair',['../d9/d7d/struct_k_o_d_i_1_1_r_e_t_r_o_1_1_c_delta_pair_memory_stream_1_1_delta_pair.html',1,'KODI::RETRO::CDeltaPairMemoryStream']]],
  ['demux_5fcrypto_5finfo_30',['DEMUX_CRYPTO_INFO',['../d2/d5f/struct_d_e_m_u_x___c_r_y_p_t_o___i_n_f_o.html',1,'']]],
  ['demux_5fpacket_31',['DEMUX_PACKET',['../db/de6/struct_d_e_m_u_x___p_a_c_k_e_t.html',1,'']]],
  ['demuxcryptoinfo_32',['DemuxCryptoInfo',['../d3/dcd/struct_demux_crypto_info.html',1,'']]],
  ['demuxcryptosession_33',['DemuxCryptoSession',['../d8/d8a/struct_demux_crypto_session.html',1,'']]],
  ['demuxpacket_34',['DemuxPacket',['../d5/d74/struct_demux_packet.html',1,'']]],
  ['dependencyinfo_35',['DependencyInfo',['../db/d7c/struct_a_d_d_o_n_1_1_dependency_info.html',1,'ADDON']]],
  ['derivedtype1_36',['DerivedType1',['../d4/d21/struct_derived_type1.html',1,'']]],
  ['derivedtype2_37',['DerivedType2',['../df/d0f/struct_derived_type2.html',1,'']]],
  ['derivedtype3_38',['DerivedType3',['../de/dbc/struct_derived_type3.html',1,'']]],
  ['desc_39',['Desc',['../d0/d18/struct_v_d_p_a_u_1_1_c_decoder_1_1_desc.html',1,'VDPAU::CDecoder']]],
  ['deviceresources_40',['DeviceResources',['../db/df3/class_d_x_1_1_device_resources.html',1,'DX']]],
  ['dialog_41',['Dialog',['../da/d2a/class_x_b_m_c_addon_1_1xbmcgui_1_1_dialog.html',1,'XBMCAddon::xbmcgui']]],
  ['dialogokmessage_42',['dialogokmessage',['../db/d62/struct_dialog_ok_message.html',1,'DialogOkMessage'],['../da/d25/struct_k_o_d_i_1_1_m_e_s_s_a_g_i_n_g_1_1_h_e_l_p_e_r_s_1_1_dialog_o_k_message.html',1,'KODI::MESSAGING::HELPERS::DialogOKMessage']]],
  ['dialogprogress_43',['DialogProgress',['../db/d29/class_x_b_m_c_addon_1_1xbmcgui_1_1_dialog_progress.html',1,'XBMCAddon::xbmcgui']]],
  ['dialogprogressbg_44',['DialogProgressBG',['../df/d5a/class_x_b_m_c_addon_1_1xbmcgui_1_1_dialog_progress_b_g.html',1,'XBMCAddon::xbmcgui']]],
  ['dialogyesnomessage_45',['DialogYesNoMessage',['../da/d1e/struct_k_o_d_i_1_1_m_e_s_s_a_g_i_n_g_1_1_h_e_l_p_e_r_s_1_1_dialog_yes_no_message.html',1,'KODI::MESSAGING::HELPERS']]],
  ['dictionary_46',['Dictionary',['../d4/d80/class_x_b_m_c_addon_1_1_dictionary.html',1,'XBMCAddon']]],
  ['diinfodeleter_47',['DiInfoDeleter',['../d6/d47/struct_k_o_d_i_1_1_u_t_i_l_s_1_1_c_display_info_1_1_di_info_deleter.html',1,'KODI::UTILS::CDisplayInfo']]],
  ['dimensionstest_48',['DimensionsTest',['../d1/d08/structanonymous__namespace_02_test_g_u_i_control_factory_8cpp_03_1_1_dimensions_test.html',1,'anonymous_namespace{TestGUIControlFactory.cpp}']]],
  ['dimensiontest_49',['DimensionTest',['../db/d4e/structanonymous__namespace_02_test_g_u_i_control_factory_8cpp_03_1_1_dimension_test.html',1,'anonymous_namespace{TestGUIControlFactory.cpp}']]],
  ['dir_50',['DIR',['../d9/d31/struct_d_i_r.html',1,'']]],
  ['director_51',['Director',['../de/db1/class_python_bindings_1_1_director.html',1,'PythonBindings']]],
  ['dirent_52',['dirent',['../d5/de2/structdirent.html',1,'']]],
  ['disabled_53',['Disabled',['../d3/d2b/struct_a_d_d_o_n_1_1_addon_events_1_1_disabled.html',1,'ADDON::AddonEvents']]],
  ['discinfo_54',['DiscInfo',['../d2/d98/struct_u_t_i_l_s_1_1_d_i_s_c_s_1_1_disc_info.html',1,'UTILS::DISCS']]],
  ['discstubtest_55',['DiscStubTest',['../d8/d64/class_disc_stub_test.html',1,'']]],
  ['dist_5fsink_56',['dist_sink',['../d6/dc4/classspdlog_1_1sinks_1_1dist__sink.html',1,'spdlog::sinks']]],
  ['dlladdon_57',['DllAddon',['../d1/d51/class_dll_addon.html',1,'']]],
  ['dlladdoninterface_58',['DllAddonInterface',['../d8/d2a/class_dll_addon_interface.html',1,'']]],
  ['dlldvdnav_59',['DllDvdNav',['../d9/d93/class_dll_dvd_nav.html',1,'']]],
  ['dlldvdnavinterface_60',['DllDvdNavInterface',['../db/dbd/class_dll_dvd_nav_interface.html',1,'']]],
  ['dlldynamic_61',['DllDynamic',['../da/d5d/class_dll_dynamic.html',1,'']]],
  ['dlllibcurl_62',['DllLibCurl',['../d6/d0c/class_x_c_u_r_l_1_1_dll_lib_curl.html',1,'XCURL']]],
  ['dlllibcurlglobal_63',['DllLibCurlGlobal',['../d3/dd9/class_x_c_u_r_l_1_1_dll_lib_curl_global.html',1,'XCURL']]],
  ['dlllibsse4_64',['DllLibSSE4',['../dd/d4f/class_dll_lib_s_s_e4.html',1,'']]],
  ['dlllibsse4interface_65',['DllLibSSE4Interface',['../d6/dc8/class_dll_lib_s_s_e4_interface.html',1,'']]],
  ['dllloadercontainer_66',['DllLoaderContainer',['../da/d45/class_dll_loader_container.html',1,'']]],
  ['drive_67',['Drive',['../d1/d12/class_c_u_disks2_provider_1_1_drive.html',1,'CUDisks2Provider']]],
  ['driverhandler_68',['DriverHandler',['../d3/dad/struct_p_e_r_i_p_h_e_r_a_l_s_1_1_c_peripheral_joystick_1_1_driver_handler.html',1,'PERIPHERALS::CPeripheralJoystick']]],
  ['driverprimitive_69',['DriverPrimitive',['../de/d51/structkodi_1_1addon_1_1_driver_primitive.html',1,'kodi::addon']]],
  ['drm_5ffb_70',['drm_fb',['../d0/da4/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1drm__fb.html',1,'KODI::WINDOWING::GBM']]],
  ['drmmodeatomicreqdeleter_71',['DrmModeAtomicReqDeleter',['../da/d4b/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_d_r_m_atomic_1_1_c_d_r_m_atomic_request_1_1_drm_mode_atomic_req_deleter.html',1,'KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest']]],
  ['drmmodeconnectordeleter_72',['DrmModeConnectorDeleter',['../d9/ddc/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_d_r_m_connector_1_1_drm_mode_connector_deleter.html',1,'KODI::WINDOWING::GBM::CDRMConnector']]],
  ['drmmodecrtcdeleter_73',['DrmModeCrtcDeleter',['../df/df0/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_d_r_m_crtc_1_1_drm_mode_crtc_deleter.html',1,'KODI::WINDOWING::GBM::CDRMCrtc']]],
  ['drmmodeencoderdeleter_74',['DrmModeEncoderDeleter',['../df/d8b/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_d_r_m_encoder_1_1_drm_mode_encoder_deleter.html',1,'KODI::WINDOWING::GBM::CDRMEncoder']]],
  ['drmmodeobjectpropertiesdeleter_75',['DrmModeObjectPropertiesDeleter',['../de/d13/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_d_r_m_object_1_1_drm_mode_object_properties_deleter.html',1,'KODI::WINDOWING::GBM::CDRMObject']]],
  ['drmmodeplanedeleter_76',['DrmModePlaneDeleter',['../d2/d45/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_d_r_m_plane_1_1_drm_mode_plane_deleter.html',1,'KODI::WINDOWING::GBM::CDRMPlane']]],
  ['drmmodepropertyresdeleter_77',['DrmModePropertyResDeleter',['../d9/d4d/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_d_r_m_object_1_1_drm_mode_property_res_deleter.html',1,'KODI::WINDOWING::GBM::CDRMObject']]],
  ['dsdevice_78',['DSDevice',['../df/d92/struct_d_s_device.html',1,'']]],
  ['dummyjob_79',['DummyJob',['../d4/d86/class_dummy_job.html',1,'']]],
  ['dvd_5flogger_5fcb_80',['dvd_logger_cb',['../dc/df8/structdvd__logger__cb.html',1,'']]],
  ['dvd_5freader_5fstream_5fcb_81',['dvd_reader_stream_cb',['../d8/d30/structdvd__reader__stream__cb.html',1,'']]],
  ['dvd_5fstat_5ft_82',['dvd_stat_t',['../d5/d5d/structdvd__stat__t.html',1,'']]],
  ['dvdmessagelistitem_83',['DVDMessageListItem',['../dd/d72/struct_d_v_d_message_list_item.html',1,'']]],
  ['dvdnav_5faudio_5fstream_5fchange_5fevent_5ft_84',['dvdnav_audio_stream_change_event_t',['../de/dbd/structdvdnav__audio__stream__change__event__t.html',1,'']]],
  ['dvdnav_5fcell_5fchange_5fevent_5ft_85',['dvdnav_cell_change_event_t',['../df/d1a/structdvdnav__cell__change__event__t.html',1,'']]],
  ['dvdnav_5fhighlight_5farea_5ft_86',['dvdnav_highlight_area_t',['../da/ddc/structdvdnav__highlight__area__t.html',1,'']]],
  ['dvdnav_5fhighlight_5fevent_5ft_87',['dvdnav_highlight_event_t',['../d1/d91/structdvdnav__highlight__event__t.html',1,'']]],
  ['dvdnav_5flogger_5fcb_88',['dvdnav_logger_cb',['../dc/d7d/structdvdnav__logger__cb.html',1,'']]],
  ['dvdnav_5fspu_5fstream_5fchange_5fevent_5ft_89',['dvdnav_spu_stream_change_event_t',['../d8/d33/structdvdnav__spu__stream__change__event__t.html',1,'']]],
  ['dvdnav_5fstill_5fevent_5ft_90',['dvdnav_still_event_t',['../db/df1/structdvdnav__still__event__t.html',1,'']]],
  ['dvdnav_5fvts_5fchange_5fevent_5ft_91',['dvdnav_vts_change_event_t',['../d0/d09/structdvdnav__vts__change__event__t.html',1,'']]],
  ['dvdstate_92',['DVDState',['../d6/d23/struct_d_v_d_state.html',1,'']]],
  ['dxgicolorspaceargs_93',['DXGIColorSpaceArgs',['../da/d91/struct_d_x_v_a_1_1_d_x_g_i_color_space_args.html',1,'DXVA']]],
  ['dxva2_5fmode_5ft_94',['dxva2_mode_t',['../d9/dc9/structdxva2__mode__t.html',1,'']]],
  ['dynamiccstructhdl_95',['DynamicCStructHdl',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrcapabilities_2c_20pvr_5faddon_5fcapabilities_20_3e_96',['DynamicCStructHdl&lt; PVRCapabilities, PVR_ADDON_CAPABILITIES &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrchannel_2c_20pvr_5fchannel_20_3e_97',['DynamicCStructHdl&lt; PVRChannel, PVR_CHANNEL &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrchannelgroup_2c_20pvr_5fchannel_5fgroup_20_3e_98',['DynamicCStructHdl&lt; PVRChannelGroup, PVR_CHANNEL_GROUP &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrchannelgroupmember_2c_20pvr_5fchannel_5fgroup_5fmember_20_3e_99',['DynamicCStructHdl&lt; PVRChannelGroupMember, PVR_CHANNEL_GROUP_MEMBER &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrdescrambleinfo_2c_20pvr_5fdescramble_5finfo_20_3e_100',['DynamicCStructHdl&lt; PVRDescrambleInfo, PVR_DESCRAMBLE_INFO &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrepgtag_2c_20epg_5ftag_20_3e_101',['DynamicCStructHdl&lt; PVREPGTag, EPG_TAG &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrintsettingdefinition_2c_20pvr_5fint_5fsetting_5fdefinition_20_3e_102',['DynamicCStructHdl&lt; PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrprovider_2c_20pvr_5fprovider_20_3e_103',['DynamicCStructHdl&lt; PVRProvider, PVR_PROVIDER &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrrecording_2c_20pvr_5frecording_20_3e_104',['DynamicCStructHdl&lt; PVRRecording, PVR_RECORDING &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrsettingdefinition_2c_20pvr_5fsetting_5fdefinition_20_3e_105',['DynamicCStructHdl&lt; PVRSettingDefinition, PVR_SETTING_DEFINITION &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrsettingkeyvaluepair_2c_20pvr_5fsetting_5fkey_5fvalue_5fpair_20_3e_106',['DynamicCStructHdl&lt; PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrsignalstatus_2c_20pvr_5fsignal_5fstatus_20_3e_107',['DynamicCStructHdl&lt; PVRSignalStatus, PVR_SIGNAL_STATUS &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrstreamproperty_2c_20pvr_5fnamed_5fvalue_20_3e_108',['DynamicCStructHdl&lt; PVRStreamProperty, PVR_NAMED_VALUE &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrstringsettingdefinition_2c_20pvr_5fstring_5fsetting_5fdefinition_20_3e_109',['DynamicCStructHdl&lt; PVRStringSettingDefinition, PVR_STRING_SETTING_DEFINITION &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrtimer_2c_20pvr_5ftimer_20_3e_110',['DynamicCStructHdl&lt; PVRTimer, PVR_TIMER &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrtimertype_2c_20pvr_5ftimer_5ftype_20_3e_111',['DynamicCStructHdl&lt; PVRTimerType, PVR_TIMER_TYPE &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrtypeintvalue_2c_20pvr_5fattribute_5fint_5fvalue_20_3e_112',['DynamicCStructHdl&lt; PVRTypeIntValue, PVR_ATTRIBUTE_INT_VALUE &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrtypestringvalue_2c_20pvr_5fattribute_5fstring_5fvalue_20_3e_113',['DynamicCStructHdl&lt; PVRTypeStringValue, PVR_ATTRIBUTE_STRING_VALUE &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]]
];
