var searchData=
[
  ['rangetest_0',['RangeTest',['../de/df2/structanonymous__namespace_02_test_g_u_i_control_factory_8cpp_03_1_1_range_test.html',1,'anonymous_namespace{TestGUIControlFactory.cpp}']]],
  ['readercontrol_1',['READERCONTROL',['../d7/d93/struct_c_rss_manager_1_1_r_e_a_d_e_r_c_o_n_t_r_o_l.html',1,'CRssManager']]],
  ['reallydumbjob_2',['ReallyDumbJob',['../de/dc1/class_really_dumb_job.html',1,'']]],
  ['ref_3',['ref',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass::Ref&lt; T &gt;'],['../db/dd5/class_x_b_m_c_addon_1_1xbmcgui_1_1ref.html',1,'XBMCAddon::xbmcgui::ref']]],
  ['ref_3c_20p1_20_3e_4',['Ref&lt; P1 &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3acallback_20_3e_5',['Ref&lt; XBMCAddon::Callback &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3acallbackhandler_20_3e_6',['Ref&lt; XBMCAddon::CallbackHandler &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3apython_3a_3apythonlanguagehook_20_3e_7',['Ref&lt; XBMCAddon::Python::PythonLanguageHook &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3aretardedasynccallbackhandler_20_3e_8',['Ref&lt; XBMCAddon::RetardedAsyncCallbackHandler &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3axbmcgui_3a_3acontrol_20_3e_9',['Ref&lt; XBMCAddon::xbmcgui::Control &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3axbmcgui_3a_3acontrolspin_20_3e_10',['Ref&lt; XBMCAddon::xbmcgui::ControlSpin &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3axbmcgui_3a_3awindow_20_3e_11',['Ref&lt; XBMCAddon::xbmcgui::Window &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['refreshoverride_12',['RefreshOverride',['../d2/db1/struct_refresh_override.html',1,'']]],
  ['refreshrate_13',['REFRESHRATE',['../d9/d4c/struct_r_e_f_r_e_s_h_r_a_t_e.html',1,'']]],
  ['refreshvideolatency_14',['RefreshVideoLatency',['../d5/d5c/struct_refresh_video_latency.html',1,'']]],
  ['reinstalled_15',['ReInstalled',['../dc/d2a/struct_a_d_d_o_n_1_1_addon_events_1_1_re_installed.html',1,'ADDON::AddonEvents']]],
  ['releasetypeinfo_16',['ReleaseTypeInfo',['../dc/df5/struct_release_type_info.html',1,'']]],
  ['remotetest_17',['RemoteTest',['../db/de6/class_remote_test.html',1,'']]],
  ['render_5fdetails_18',['render_details',['../d7/d1d/structrender__details.html',1,'']]],
  ['renderbufferpools_19',['RenderBufferPools',['../d5/d2a/struct_k_o_d_i_1_1_r_e_t_r_o_1_1_c_render_buffer_manager_1_1_render_buffer_pools.html',1,'KODI::RETRO::CRenderBufferManager']]],
  ['rendercapture_20',['RenderCapture',['../d0/dab/class_x_b_m_c_addon_1_1xbmc_1_1_render_capture.html',1,'XBMCAddon::xbmc']]],
  ['rendererdetail_21',['RendererDetail',['../d6/db1/struct_renderer_detail.html',1,'']]],
  ['renderitem_22',['RENDERITEM',['../d5/d28/struct_c_g_u_i_base_container_1_1_r_e_n_d_e_r_i_t_e_m.html',1,'CGUIBaseContainer']]],
  ['renderopts_23',['renderOpts',['../d0/d3f/struct_k_o_d_i_1_1_s_u_b_t_i_t_l_e_s_1_1_s_t_y_l_e_1_1render_opts.html',1,'KODI::SUBTITLES::STYLE']]],
  ['replaygain_24',['ReplayGain',['../d7/d7e/class_replay_gain.html',1,'']]],
  ['replaygainsettings_25',['ReplayGainSettings',['../db/dac/struct_c_application_volume_handling_1_1_replay_gain_settings.html',1,'CApplicationVolumeHandling']]],
  ['repoinfo_26',['RepoInfo',['../d7/ddd/struct_a_d_d_o_n_1_1_repo_info.html',1,'ADDON']]],
  ['repositorydirinfo_27',['RepositoryDirInfo',['../d1/d04/struct_a_d_d_o_n_1_1_repository_dir_info.html',1,'ADDON']]],
  ['repositoryupdated_28',['RepositoryUpdated',['../d2/db1/struct_a_d_d_o_n_1_1_c_repository_updater_1_1_repository_updated.html',1,'ADDON::CRepositoryUpdater']]],
  ['repoupdatedata_29',['RepoUpdateData',['../db/d85/struct_a_d_d_o_n_1_1_c_addon_database_1_1_repo_update_data.html',1,'ADDON::CAddonDatabase']]],
  ['resolution_5finfo_30',['RESOLUTION_INFO',['../db/d94/struct_r_e_s_o_l_u_t_i_o_n___i_n_f_o.html',1,'']]],
  ['resolution_5fwhr_31',['RESOLUTION_WHR',['../d9/d18/struct_r_e_s_o_l_u_t_i_o_n___w_h_r.html',1,'']]],
  ['resolveresult_32',['ResolveResult',['../d2/da7/struct_a_d_d_o_n_1_1_c_repository_1_1_resolve_result.html',1,'ADDON::CRepository']]],
  ['resourceprioritysort_33',['ResourcePrioritySort',['../d2/dda/struct_u_p_n_p_1_1_resource_priority_sort.html',1,'UPNP']]],
  ['result_34',['Result',['../de/d04/classhelper___log_1_1_result.html',1,'helper_Log']]],
  ['result_5fset_35',['result_set',['../dc/d6e/classdbiplus_1_1result__set.html',1,'dbiplus']]],
  ['resumeinformation_36',['ResumeInformation',['../dd/dab/struct_k_o_d_i_1_1_v_i_d_e_o_1_1_u_t_i_l_s_1_1_resume_information.html',1,'KODI::VIDEO::UTILS']]],
  ['retardedasynccallbackhandler_37',['RetardedAsyncCallbackHandler',['../d8/d43/class_x_b_m_c_addon_1_1_retarded_async_callback_handler.html',1,'XBMCAddon']]],
  ['rssset_38',['RssSet',['../d2/db3/struct_rss_set.html',1,'']]],
  ['rt_5faddrinfo_39',['rt_addrinfo',['../df/dda/structrt__addrinfo.html',1,'']]],
  ['rt_5fmetrics_40',['rt_metrics',['../df/db3/structrt__metrics.html',1,'']]],
  ['rt_5fmsghdr_41',['rt_msghdr',['../d1/df2/structrt__msghdr.html',1,'']]],
  ['rt_5fmsghdr2_42',['rt_msghdr2',['../dc/de5/structrt__msghdr2.html',1,'']]],
  ['rtstat_43',['rtstat',['../de/d53/structrtstat.html',1,'']]],
  ['runinfo_44',['RunInfo',['../d4/df0/struct_c_g_u_i_font_t_t_f_1_1_run_info.html',1,'CGUIFontTTF']]]
];
