var searchData=
[
  ['c_0',['C++',['../d1/ddf/group__cpp.html',1,'']]],
  ['cachestatus_1',['class CacheStatus',['../d6/d53/group__cpp__kodi__vfs___defs___cache_status.html',1,'']]],
  ['caddonbase_2',['class CAddonBase',['../dc/d7b/group__cpp__kodi__addon__addonbase.html',1,'']]],
  ['caestream_3',['class CAEStream',['../d0/db0/group__cpp__kodi__audioengine___c_a_e_stream.html',1,'']]],
  ['callback_20functions_4',['3. Callback functions',['../db/d3b/group__cpp__kodi__addon__peripheral__callbacks.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_20on_5',['callback functions from kodi to add on',['../dd/d1b/group__cpp__kodi__gui__windows__window__callbacks.html',1,'Callback functions from Kodi to add-on'],['../d4/df8/group__python__xbmcgui__window__cb.html',1,'Callback functions from Kodi to add-on'],['../dd/d41/group__python___player_c_b.html',1,'Callback functions from Kodi to Add-On']]],
  ['callbacks_6',['Window Manager and Callbacks',['../d6/df1/group__winman.html',1,'']]],
  ['callbacks_20getdirectory_7',['Callbacks GetDirectory()',['../d8/dfe/group__cpp__kodi__addon__vfs__general__cb___get_directory.html',1,'']]],
  ['cdirentry_8',['class CDirEntry',['../d7/ded/group__cpp__kodi__vfs___c_dir_entry.html',1,'']]],
  ['cdllhelper_9',['class CDllHelper',['../dd/dea/group__cpp__kodi__tools___c_dll_helper.html',1,'']]],
  ['cendtime_10',['class CEndTime',['../d5/dd9/group__cpp__kodi__tools___c_end_time.html',1,'']]],
  ['cfile_11',['4. class CFile',['../d1/d6e/group__cpp__kodi__vfs___c_file.html',1,'']]],
  ['channel_12',['2. Channel',['../dd/dd7/group__cpp__kodi__addon__pvr___defs___channel.html',1,'']]],
  ['channel_20edit_20optional_13',['4. Channel edit (optional)',['../dd/dc5/group__cpp__kodi__addon__pvr__supports_channel_edit.html',1,'']]],
  ['channel_20group_14',['3. Channel Group',['../de/dfd/group__cpp__kodi__addon__pvr___defs___channel_group.html',1,'']]],
  ['channel_20groups_20optional_15',['3. Channel Groups (optional)',['../da/db1/group__cpp__kodi__addon__pvr__supports_channel_groups.html',1,'']]],
  ['channels_20required_16',['2. Channels (required)',['../df/d40/group__cpp__kodi__addon__pvr___channels.html',1,'']]],
  ['chapter_20optional_17',['6. Chapter (optional)',['../d6/d44/group__cpp__kodi__addon__inputstream___chapter.html',1,'']]],
  ['cheat_20operations_18',['6. Cheat operations',['../d3/d05/group__cpp__kodi__addon__game___cheat_operations.html',1,'']]],
  ['child_20functions_19',['Child Functions',['../dc/d01/group__cpp__kodi__gui__helpers__gl___c_shader_program__child.html',1,'']]],
  ['cinterfaceandroidsystem_20',['class CInterfaceAndroidSystem',['../da/d34/group__cpp__kodi__platform___c_interface_android_system.html',1,'']]],
  ['class_20audiodecoderinfotag_21',['class AudioDecoderInfoTag',['../d2/d69/group__cpp__kodi__addon__audiodecoder___defs___audio_decoder_info_tag.html',1,'']]],
  ['class_20audioencoderinfotag_22',['class AudioEncoderInfoTag',['../de/dfd/group__cpp__kodi__addon__audioencoder___defs___audio_encoder_info_tag.html',1,'']]],
  ['class_20audioengineformat_23',['class AudioEngineFormat',['../d2/de7/group__cpp__kodi__audioengine___defs___audio_engine_format.html',1,'']]],
  ['class_20cachestatus_24',['class CacheStatus',['../d6/d53/group__cpp__kodi__vfs___defs___cache_status.html',1,'']]],
  ['class_20caddonbase_25',['class CAddonBase',['../dc/d7b/group__cpp__kodi__addon__addonbase.html',1,'']]],
  ['class_20caestream_26',['class CAEStream',['../d0/db0/group__cpp__kodi__audioengine___c_a_e_stream.html',1,'']]],
  ['class_20cdirentry_27',['class CDirEntry',['../d7/ded/group__cpp__kodi__vfs___c_dir_entry.html',1,'']]],
  ['class_20cdllhelper_28',['class CDllHelper',['../dd/dea/group__cpp__kodi__tools___c_dll_helper.html',1,'']]],
  ['class_20cendtime_29',['class CEndTime',['../d5/dd9/group__cpp__kodi__tools___c_end_time.html',1,'']]],
  ['class_20cfile_30',['4. class CFile',['../d1/d6e/group__cpp__kodi__vfs___c_file.html',1,'']]],
  ['class_20cinterfaceandroidsystem_31',['class CInterfaceAndroidSystem',['../da/d34/group__cpp__kodi__platform___c_interface_android_system.html',1,'']]],
  ['class_20csettingvalue_32',['class CSettingValue',['../df/d58/group__cpp__kodi__addon__addonbase___defs___c_setting_value.html',1,'']]],
  ['class_20cthread_33',['class CThread',['../d4/dfd/group__cpp__kodi__tools___c_thread.html',1,'']]],
  ['class_20ctimer_34',['class CTimer',['../d2/d33/group__cpp__kodi__tools___c_timer.html',1,'']]],
  ['class_20driverprimitive_35',['class DriverPrimitive',['../d5/d57/group__cpp__kodi__addon__peripheral___defs___joystick___driver_primitive.html',1,'']]],
  ['class_20filestatus_36',['class FileStatus',['../df/d08/group__cpp__kodi__vfs___defs___file_status.html',1,'']]],
  ['class_20gamecontrollerlayout_37',['class GameControllerLayout',['../dd/d1e/group__cpp__kodi__addon__game___defs___input_types___game_controller_layout.html',1,'']]],
  ['class_20httpheader_38',['class HttpHeader',['../d9/d25/group__cpp__kodi__vfs___defs___http_header.html',1,'']]],
  ['class_20iinstanceinfo_39',['class IInstanceInfo',['../d2/dad/group__cpp__kodi__addon__addonbase___defs___i_instance_info.html',1,'']]],
  ['class_20imagedecoderinfotag_40',['class ImageDecoderInfoTag',['../d5/dff/group__cpp__kodi__addon__imagedecoder___defs___image_decoder_info_tag.html',1,'']]],
  ['class_20inputstreamcapabilities_41',['class InputstreamCapabilities',['../dc/d43/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_capabilities.html',1,'']]],
  ['class_20inputstreamcontentlightmetadata_42',['class InputstreamContentlightMetadata',['../d9/d31/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_contentlight_metadata.html',1,'']]],
  ['class_20inputstreaminfo_43',['class InputstreamInfo',['../db/d82/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_info.html',1,'']]],
  ['class_20inputstreammasteringmetadata_44',['class InputstreamMasteringMetadata',['../da/d1e/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_mastering_metadata.html',1,'']]],
  ['class_20inputstreamproperty_45',['class InputstreamProperty',['../d6/df1/group__cpp__kodi__addon__inputstream___defs___inputstream_property.html',1,'']]],
  ['class_20inputstreamtimes_46',['class InputstreamTimes',['../dc/d8d/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_times.html',1,'']]],
  ['class_20itimercallback_47',['class ITimerCallback',['../df/de6/group__cpp__kodi__tools___c_timer___c_b.html',1,'']]],
  ['class_20joystick_48',['class Joystick',['../d0/da1/group__cpp__kodi__addon__peripheral___defs___joystick___joystick.html',1,'']]],
  ['class_20joystickfeature_49',['class JoystickFeature',['../db/d89/group__cpp__kodi__addon__peripheral___defs___joystick___joystick_feature.html',1,'']]],
  ['class_20peripheral_50',['class Peripheral',['../d3/da4/group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral.html',1,'']]],
  ['class_20peripheralcapabilities_51',['class PeripheralCapabilities',['../d6/dbe/group__cpp__kodi__addon__peripheral___defs___peripheral_capabilities.html',1,'']]],
  ['class_20peripheralevent_52',['class PeripheralEvent',['../d7/d89/group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral_event.html',1,'']]],
  ['class_20pvrcapabilities_53',['class PVRCapabilities',['../d3/df7/group__cpp__kodi__addon__pvr___defs___p_v_r_capabilities.html',1,'']]],
  ['class_20pvrchannel_54',['class PVRChannel',['../df/d03/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_channel.html',1,'']]],
  ['class_20pvrchannelgroup_55',['class PVRChannelGroup',['../d3/dec/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group.html',1,'']]],
  ['class_20pvrchannelgroupmember_56',['class PVRChannelGroupMember',['../de/da7/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group_member.html',1,'']]],
  ['class_20pvrchannelgroupmembersresultset_57',['class PVRChannelGroupMembersResultSet',['../d9/d7f/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group_members_result_set.html',1,'']]],
  ['class_20pvrchannelgroupsresultset_58',['class PVRChannelGroupsResultSet',['../d9/d68/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_groups_result_set.html',1,'']]],
  ['class_20pvrchannelsresultset_59',['class PVRChannelsResultSet',['../dc/d71/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_channels_result_set.html',1,'']]],
  ['class_20pvrcodec_60',['class PVRCodec',['../d1/d0c/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_codec.html',1,'']]],
  ['class_20pvrdescrambleinfo_61',['class PVRDescrambleInfo',['../df/d52/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_descramble_info.html',1,'']]],
  ['class_20pvredlentry_62',['class PVREDLEntry',['../d7/d48/group__cpp__kodi__addon__pvr___defs___e_d_l_entry___p_v_r_e_d_l_entry.html',1,'']]],
  ['class_20pvrepgtag_63',['class PVREPGTag',['../d1/dfb/group__cpp__kodi__addon__pvr___defs__epg___p_v_r_e_p_g_tag.html',1,'']]],
  ['class_20pvrepgtagsresultset_64',['class PVREPGTagsResultSet',['../da/d89/group__cpp__kodi__addon__pvr___defs__epg___p_v_r_e_p_g_tags_result_set.html',1,'']]],
  ['class_20pvrintsettingdefinition_65',['class PVRIntSettingDefinition',['../d7/d23/group__cpp__kodi__addon__pvr___defs___p_v_r_int_setting_definition.html',1,'']]],
  ['class_20pvrmenuhook_66',['class PVRMenuhook',['../d5/db8/group__cpp__kodi__addon__pvr___defs___menuhook___p_v_r_menuhook.html',1,'']]],
  ['class_20pvrprovider_67',['class PVRProvider',['../d2/dd9/group__cpp__kodi__addon__pvr___defs___p_v_r_provider.html',1,'']]],
  ['class_20pvrprovidersresultset_68',['class PVRProvidersResultSet',['../d5/d91/group__cpp__kodi__addon__pvr___defs___p_v_r_providers_result_set.html',1,'']]],
  ['class_20pvrrecording_69',['class PVRRecording',['../d5/d9e/group__cpp__kodi__addon__pvr___defs___recording___p_v_r_recording.html',1,'']]],
  ['class_20pvrrecordingsresultset_70',['class PVRRecordingsResultSet',['../d0/dac/group__cpp__kodi__addon__pvr___defs___recording___p_v_r_recordings_result_set.html',1,'']]],
  ['class_20pvrsettingdefinition_71',['class PVRSettingDefinition',['../dc/d36/group__cpp__kodi__addon__pvr___defs___p_v_r_setting_definition.html',1,'']]],
  ['class_20pvrsettingkeyvaluepair_72',['class PVRSettingKeyValuePair',['../d9/dcb/group__cpp__kodi__addon__pvr___defs___general___p_v_r_setting_key_value_pair.html',1,'']]],
  ['class_20pvrsignalstatus_73',['class PVRSignalStatus',['../d8/dd4/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_signal_status.html',1,'']]],
  ['class_20pvrstreamproperties_74',['class PVRStreamProperties',['../dc/d27/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_properties.html',1,'']]],
  ['class_20pvrstreamproperty_75',['class PVRStreamProperty',['../d8/d5c/group__cpp__kodi__addon__pvr___defs___general___inputstream___p_v_r_stream_property.html',1,'']]],
  ['class_20pvrstreamproperty_20definition_20pvr_5fstream_5fproperty_76',['class PVRStreamProperty &amp; definition PVR_STREAM_PROPERTY',['../db/de7/group__cpp__kodi__addon__pvr___defs___general___inputstream.html',1,'']]],
  ['class_20pvrstreamtimes_77',['class PVRStreamTimes',['../de/d74/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_times.html',1,'']]],
  ['class_20pvrstringsettingdefinition_78',['class PVRStringSettingDefinition',['../d0/d73/group__cpp__kodi__addon__pvr___defs___p_v_r_string_setting_definition.html',1,'']]],
  ['class_20pvrtimer_79',['class PVRTimer',['../dd/dd8/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer.html',1,'']]],
  ['class_20pvrtimersresultset_80',['class PVRTimersResultSet',['../d8/d1b/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timers_result_set.html',1,'']]],
  ['class_20pvrtimertype_81',['class PVRTimerType',['../d4/dd4/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer_type.html',1,'']]],
  ['class_20pvrtypeintvalue_82',['class PVRTypeIntValue',['../d8/d9f/group__cpp__kodi__addon__pvr___defs___p_v_r_type_int_value.html',1,'']]],
  ['class_20pvrtypestringvalue_83',['class PVRTypeStringValue',['../d4/dbe/group__cpp__kodi__addon__pvr___defs___p_v_r_type_string_value.html',1,'']]],
  ['class_20streamcryptosession_84',['class StreamCryptoSession',['../dd/dba/group__cpp__kodi__addon__inputstream___defs___stream_encryption___stream_crypto_session.html',1,'']]],
  ['class_20stringutils_85',['class StringUtils',['../df/d5a/group__cpp__kodi__tools___string_utils.html',1,'']]],
  ['class_20vfsurl_86',['class VFSUrl',['../dd/d23/group__cpp__kodi__addon__vfs___defs___v_f_s_url.html',1,'']]],
  ['class_20videocodecinitdata_87',['class VideoCodecInitdata',['../d2/dbb/group__cpp__kodi__addon__videocodec___defs___video_codec_initdata.html',1,'']]],
  ['class_20visualizationtrack_88',['class VisualizationTrack',['../d1/d1e/group__cpp__kodi__addon__visualization___defs___visualization_track.html',1,'']]],
  ['class_3a_20cstream_89',['Class: CStream',['../d2/d9b/group__cpp__kodi__addon__game___operation___c_stream.html',1,'']]],
  ['classes_90',['Guilib classes',['../d4/dee/group__guilib.html',1,'']]],
  ['cmake_20addon_20creation_20structure_91',['CMake addon creation structure',['../d0/dbc/group__cpp__cmake.html',1,'']]],
  ['codec_92',['codec',['../d8/dbe/group__cpp__kodi__addon__inputstream___defs___stream_codec.html',1,'4. Stream codec'],['../db/ddf/group__cpp__kodi__addon__videocodec.html',1,'Video Codec']]],
  ['compare_93',['String compare',['../d4/d27/group__cpp__kodi__tools___string_utils___compare_control.html',1,'']]],
  ['configuration_94',['8. Button mapping (controller configuration)',['../df/d8c/group__cpp__kodi__addon__peripheral___docs___lifetime___button_mapping.html',1,'']]],
  ['constants_95',['2. Stream constants',['../da/d7f/group__cpp__kodi__addon__inputstream___defs___stream_constants.html',1,'']]],
  ['context_20menu_96',['Dialog Context Menu',['../de/d4c/group__cpp__kodi__gui__dialogs___context_menu.html',1,'']]],
  ['control_97',['control',['../de/dca/group__cpp__kodi__settings.html',1,'1. Setting control'],['../d9/d2a/group__python__xbmcgui__control.html',1,'Control']]],
  ['control_20button_98',['Control Button',['../d9/d72/group__cpp__kodi__gui__windows__controls___c_button.html',1,'']]],
  ['control_20edit_99',['Control Edit',['../d9/d7c/group__cpp__kodi__gui__windows__controls___c_edit.html',1,'']]],
  ['control_20fade_20label_100',['Control Fade Label',['../d2/d86/group__cpp__kodi__gui__windows__controls___c_fade_label.html',1,'']]],
  ['control_20image_101',['Control Image',['../d8/dea/group__cpp__kodi__gui__windows__controls___c_image.html',1,'']]],
  ['control_20label_102',['Control Label',['../d5/d2b/group__cpp__kodi__gui__windows__controls___c_label.html',1,'']]],
  ['control_20progress_103',['Control Progress',['../d0/d04/group__cpp__kodi__gui__windows__controls___c_progress.html',1,'']]],
  ['control_20radio_20button_104',['Control Radio Button',['../d2/d21/group__cpp__kodi__gui__windows__controls___c_radio_button.html',1,'']]],
  ['control_20rendering_105',['Control Rendering',['../dd/df5/group__cpp__kodi__gui__windows__controls___c_rendering.html',1,'']]],
  ['control_20settings_20slider_106',['Control Settings Slider',['../d1/dd9/group__cpp__kodi__gui__windows__controls___c_settings_slider.html',1,'']]],
  ['control_20slider_107',['Control Slider',['../d9/d7f/group__cpp__kodi__gui__windows__controls___c_slider.html',1,'']]],
  ['control_20spin_108',['Control Spin',['../de/db4/group__cpp__kodi__gui__windows__controls___c_spin.html',1,'']]],
  ['control_20text_20box_109',['Control Text Box',['../df/d0b/group__cpp__kodi__gui__windows__controls___c_text_box.html',1,'']]],
  ['controlbutton_110',['Subclass - ControlButton',['../dc/d18/group__python__xbmcgui__control__button.html',1,'']]],
  ['controledit_111',['Subclass - ControlEdit',['../d4/d8b/group__python__xbmcgui__control__edit.html',1,'']]],
  ['controlfadelabel_112',['Subclass - ControlFadeLabel',['../dc/d41/group__python__xbmcgui__control__fadelabel.html',1,'']]],
  ['controlgroup_113',['Subclass - ControlGroup',['../da/d1f/group__python__xbmcgui__control__group.html',1,'']]],
  ['controlimage_114',['Subclass - ControlImage',['../d5/dec/group__python__xbmcgui__control__image.html',1,'']]],
  ['controllabel_115',['Subclass - ControlLabel',['../d4/dd9/group__python__xbmcgui__control__label.html',1,'']]],
  ['controller_116',['5. Mapping driver elements to the system&apos;s controller',['../da/da9/group__cpp__kodi__addon__peripheral___docs___lifetime___driver_elements.html',1,'']]],
  ['controller_20configuration_117',['8. Button mapping (controller configuration)',['../df/d8c/group__cpp__kodi__addon__peripheral___docs___lifetime___button_mapping.html',1,'']]],
  ['controller_20input_118',['Controller Input',['../df/db3/group__cpp__kodi__addon__peripheral___docs___controller_input.html',1,'']]],
  ['controller_20profiles_119',['1. Controller profiles',['../da/dc3/group__cpp__kodi__addon__peripheral___docs___controller_input___profiles.html',1,'']]],
  ['controller_20to_20libretro_20s_20retropad_120',['6. Translating Kodi controller to libretro&apos;s &quot;RetroPad&quot;',['../db/d99/group__cpp__kodi__addon__peripheral___docs___lifetime___translating.html',1,'']]],
  ['controllist_121',['Subclass - ControlList',['../da/d30/group__python__xbmcgui__control__list.html',1,'']]],
  ['controlprogress_122',['Subclass - ControlProgress',['../d4/d4a/group__python__xbmcgui__control__progress.html',1,'']]],
  ['controlradiobutton_123',['Subclass - ControlRadioButton',['../d7/d8e/group__python__xbmcgui__control__radiobutton.html',1,'']]],
  ['controls_124',['Controls',['../dd/d87/group__controls.html',1,'']]],
  ['controls_20kodi_3a_3agui_3a_3acontrols_3a_3ac_125',['3. GUI controls (kodi::gui::controls::C...)',['../d5/d39/group__cpp__kodi__gui__windows__controls.html',1,'']]],
  ['controlslider_126',['Subclass - ControlSlider',['../d0/d9c/group__python__xbmcgui__control__slider.html',1,'']]],
  ['controlspin_127',['Subclass - ControlSpin',['../dd/d02/group__python__xbmcgui__control__spin.html',1,'']]],
  ['controltextbox_128',['Subclass - ControlTextBox',['../da/df5/group__python__xbmcgui__control__textbox.html',1,'']]],
  ['creation_20structure_129',['CMake addon creation structure',['../d0/dbc/group__cpp__cmake.html',1,'']]],
  ['csettingvalue_130',['class CSettingValue',['../df/d58/group__cpp__kodi__addon__addonbase___defs___c_setting_value.html',1,'']]],
  ['cstream_131',['Class: CStream',['../d2/d9b/group__cpp__kodi__addon__game___operation___c_stream.html',1,'']]],
  ['cthread_132',['class CThread',['../d4/dfd/group__cpp__kodi__tools___c_thread.html',1,'']]],
  ['ctimer_133',['class CTimer',['../d2/d33/group__cpp__kodi__tools___c_timer.html',1,'']]],
  ['curloptiontype_134',['enum CURLOptiontype',['../d2/dbb/group__cpp__kodi__vfs___defs___c_u_r_l_optiontype.html',1,'']]]
];
