var searchData=
[
  ['icon_20types_0',['Overlay icon types',['../d2/d59/group__kodi__guilib__listitem__iconoverlay.html',1,'']]],
  ['id_20s_1',['Action Id&apos;s',['../d9/d2e/group__kodi__key__action__ids.html',1,'']]],
  ['iinstanceinfo_2',['class IInstanceInfo',['../d2/dad/group__cpp__kodi__addon__addonbase___defs___i_instance_info.html',1,'']]],
  ['image_3',['Control Image',['../d8/dea/group__cpp__kodi__gui__windows__controls___c_image.html',1,'']]],
  ['image_20decoder_4',['Image Decoder',['../d1/dbc/group__cpp__kodi__addon__imagedecoder.html',1,'']]],
  ['imagedecoderinfotag_5',['class ImageDecoderInfoTag',['../d5/dff/group__cpp__kodi__addon__imagedecoder___defs___image_decoder_info_tag.html',1,'']]],
  ['info_6',['info',['../db/da8/group__info.html',1,'Info'],['../d8/df5/group__music.html',1,'Music info']]],
  ['information_20functions_7',['information functions',['../d0/d39/group__cpp__kodi__addon__visualization___c_b.html',1,'Information functions'],['../d8/d06/group__cpp__kodi__addon__screensaver___c_b.html',1,'Information functions']]],
  ['infotaggame_8',['InfoTagGame',['../d7/d0a/group__python___info_tag_game.html',1,'']]],
  ['infotagmusic_9',['InfoTagMusic',['../da/d88/group__python___info_tag_music.html',1,'']]],
  ['infotagpicture_10',['InfoTagPicture',['../df/d80/group__python___info_tag_picture.html',1,'']]],
  ['infotagradiords_11',['InfoTagRadioRDS',['../d9/df4/group__python___info_tag_radio_r_d_s.html',1,'']]],
  ['infotagvideo_12',['InfoTagVideo',['../d9/dc2/group__python___info_tag_video.html',1,'']]],
  ['input_13',['input',['../df/d9e/group__cpp__kodi__addon__peripheral___docs___lifetime___kodi_input.html',1,'7. Kodi Input'],['../df/dcf/group__cpp__kodi__addon__peripheral___docs___lifetime___keyboard_input.html',1,'9. Keyboard input'],['../df/db3/group__cpp__kodi__addon__peripheral___docs___controller_input.html',1,'Controller Input'],['../dc/df1/group__input.html',1,'Input']]],
  ['input_20for_20the_20game_20api_14',['4. Handling input for the Game API',['../de/d62/group__cpp__kodi__addon__peripheral___docs___lifetime___input.html',1,'']]],
  ['input_20operations_15',['4. Input operations',['../db/d24/group__cpp__kodi__addon__game___input_operations.html',1,'']]],
  ['input_20types_16',['7. Input types',['../d4/d53/group__cpp__kodi__addon__game___defs___input_types.html',1,'']]],
  ['inputstream_17',['inputstream',['../d5/d50/group__cpp__kodi__addon__pvr___defs___stream.html',1,'10. Inputstream'],['../d0/dac/group__cpp__kodi__addon__pvr___streams.html',1,'8. Inputstream'],['../d5/d93/group__cpp__kodi__addon__inputstream.html',1,'Inputstream']]],
  ['inputstream_5fcodec_5ffeatures_18',['enum INPUTSTREAM_CODEC_FEATURES',['../d1/d2b/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___c_o_d_e_c___f_e_a_t_u_r_e_s.html',1,'']]],
  ['inputstream_5fcolorprimaries_19',['enum INPUTSTREAM_COLORPRIMARIES',['../d9/d13/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___c_o_l_o_r_p_r_i_m_a_r_i_e_s.html',1,'']]],
  ['inputstream_5fcolorrange_20',['enum INPUTSTREAM_COLORRANGE',['../dd/d57/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___c_o_l_o_r_r_a_n_g_e.html',1,'']]],
  ['inputstream_5fcolorspace_21',['enum INPUTSTREAM_COLORSPACE',['../db/d96/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___c_o_l_o_r_s_p_a_c_e.html',1,'']]],
  ['inputstream_5fcolortrc_22',['enum INPUTSTREAM_COLORTRC',['../d5/d84/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___c_o_l_o_r_t_r_c.html',1,'']]],
  ['inputstream_5fflags_23',['enum INPUTSTREAM_FLAGS',['../d0/d11/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___f_l_a_g_s.html',1,'']]],
  ['inputstream_5ftype_24',['enum INPUTSTREAM_TYPE',['../d2/d54/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___t_y_p_e.html',1,'']]],
  ['inputstreamcapabilities_25',['class InputstreamCapabilities',['../dc/d43/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_capabilities.html',1,'']]],
  ['inputstreamcontentlightmetadata_26',['class InputstreamContentlightMetadata',['../d9/d31/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_contentlight_metadata.html',1,'']]],
  ['inputstreaminfo_27',['class InputstreamInfo',['../db/d82/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_info.html',1,'']]],
  ['inputstreammasteringmetadata_28',['class InputstreamMasteringMetadata',['../da/d1e/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_mastering_metadata.html',1,'']]],
  ['inputstreamproperty_29',['class InputstreamProperty',['../d6/df1/group__cpp__kodi__addon__inputstream___defs___inputstream_property.html',1,'']]],
  ['inputstreamtimes_30',['class InputstreamTimes',['../dc/d8d/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_times.html',1,'']]],
  ['instances_31',['Addon type instances',['../d5/d80/group__cpp__kodi__addon__instances.html',1,'']]],
  ['interface_32',['1. Interface',['../d5/d30/group__cpp__kodi__addon__inputstream___defs___interface.html',1,'']]],
  ['interface_20kodi_33',['Interface - kodi',['../d7/d0c/group__cpp__kodi.html',1,'']]],
  ['interface_20kodi_3a_3aaddon_34',['Interface - kodi::addon',['../d7/d26/group__cpp__kodi__addon.html',1,'']]],
  ['interface_20kodi_3a_3aaudioengine_35',['Interface - kodi::audioengine',['../de/d8c/group__cpp__kodi__audioengine.html',1,'']]],
  ['interface_20kodi_3a_3agui_36',['Interface - kodi::gui',['../dc/d5f/group__cpp__kodi__gui.html',1,'']]],
  ['interface_20kodi_3a_3anetwork_37',['Interface - kodi::network',['../db/d5d/group__cpp__kodi__network.html',1,'']]],
  ['interface_20kodi_3a_3aplatform_38',['Interface - kodi::platform',['../d9/d20/group__cpp__kodi__platform.html',1,'']]],
  ['interface_20kodi_3a_3atools_39',['Interface - kodi::tools',['../d3/dbd/group__cpp__kodi__tools.html',1,'']]],
  ['interface_20kodi_3a_3avfs_40',['Interface - kodi::vfs',['../db/d82/group__cpp__kodi__vfs.html',1,'']]],
  ['interfaces_41',['Interfaces',['../d8/d60/group__interface.html',1,'']]],
  ['item_20kodi_3a_3agui_3a_3aclistitem_42',['2. GUI list item (kodi::gui::CListItem)',['../d7/d0c/group__cpp__kodi__gui__windows__listitem.html',1,'']]],
  ['items_43',['Items',['../db/d08/group__items.html',1,'']]],
  ['itimercallback_44',['class ITimerCallback',['../df/de6/group__cpp__kodi__tools___c_timer___c_b.html',1,'']]]
];
