var searchData=
[
  ['of_20a_20button_20press_0',['Lifetime of a button press',['../d9/db1/group__cpp__kodi__addon__peripheral___docs___lifetime.html',1,'']]],
  ['of_20sort_20methods_1',['List of sort methods',['../d1/d7e/group___list__of__sort__methods.html',1,'']]],
  ['ok_2',['Dialog OK',['../d5/db4/group__cpp__kodi__gui__dialogs___o_k.html',1,'']]],
  ['on_3',['on',['../d4/df8/group__python__xbmcgui__window__cb.html',1,'Callback functions from Kodi to add-on'],['../dd/d41/group__python___player_c_b.html',1,'Callback functions from Kodi to Add-On'],['../dd/d1b/group__cpp__kodi__gui__windows__window__callbacks.html',1,'Callback functions from Kodi to add-on']]],
  ['openfileflags_4',['enum OpenFileFlags',['../da/d47/group__cpp__kodi__vfs___defs___open_file_flags.html',1,'']]],
  ['opengl_20helpers_5',['OpenGL helpers',['../d8/de7/group__cpp__kodi__gui__helpers__gl.html',1,'']]],
  ['operations_6',['operations',['../dc/d01/group__cpp__kodi__addon__peripheral__peripheral_op.html',1,'1. Peripheral operations'],['../d4/d54/group__cpp__kodi__addon__game___operation.html',1,'2. Game operations'],['../de/d2e/group__cpp__kodi__addon__peripheral__joystick_op.html',1,'2. Joystick operations'],['../d1/d4f/group__cpp__kodi__addon__game___hardware_rendering.html',1,'3. Hardware rendering operations'],['../db/d24/group__cpp__kodi__addon__game___input_operations.html',1,'4. Input operations'],['../de/d37/group__cpp__kodi__addon__game___serialization_operations.html',1,'5. Serialization operations'],['../d3/d05/group__cpp__kodi__addon__game___cheat_operations.html',1,'6. Cheat operations']]],
  ['optional_7',['optional',['../da/d1b/group__cpp__kodi__addon__inputstream___demux.html',1,'2. Stream demuxing (optional)'],['../da/db1/group__cpp__kodi__addon__pvr__supports_channel_groups.html',1,'3. Channel Groups (optional)'],['../d6/d52/group__cpp__kodi__addon__inputstream___time.html',1,'3. Time (optional)'],['../dd/dc5/group__cpp__kodi__addon__pvr__supports_channel_edit.html',1,'4. Channel edit (optional)'],['../dd/df4/group__cpp__kodi__addon__pvr___e_p_g_tag.html',1,'4. EPG methods (optional)'],['../df/d90/group__cpp__kodi__addon__inputstream___times.html',1,'4. Times (optional)'],['../df/d0e/group__cpp__kodi__addon__inputstream___pos_time.html',1,'5. Position time (optional)'],['../d7/d76/group__cpp__kodi__addon__pvr___recordings.html',1,'5. Recordings (optional)'],['../d6/d44/group__cpp__kodi__addon__inputstream___chapter.html',1,'6. Chapter (optional)'],['../df/d70/group__cpp__kodi__addon__pvr___timers.html',1,'6. Timers (optional)'],['../df/d4f/group__cpp__kodi__addon__pvr___power_management.html',1,'7. Power management events (optional)']]],
  ['overlay_20icon_20types_8',['Overlay icon types',['../d2/d59/group__kodi__guilib__listitem__iconoverlay.html',1,'']]]
];
