var searchData=
[
  ['edit_0',['edit',['../d9/d7c/group__cpp__kodi__gui__windows__controls___c_edit.html',1,'Control Edit'],['../d2/dca/group__cpp__kodi__tools___string_utils___edit_control.html',1,'String edit']]],
  ['edit_20decision_20list_20edl_1',['9. Edit decision list (EDL)',['../db/d20/group__cpp__kodi__addon__pvr___defs___e_d_l_entry.html',1,'']]],
  ['edit_20optional_2',['4. Channel edit (optional)',['../dd/dc5/group__cpp__kodi__addon__pvr__supports_channel_edit.html',1,'']]],
  ['editing_20functions_3',['2. File editing functions',['../d6/d60/group__cpp__kodi__addon__vfs__filecontrol.html',1,'']]],
  ['edl_4',['9. Edit decision list (EDL)',['../db/d20/group__cpp__kodi__addon__pvr___defs___e_d_l_entry.html',1,'']]],
  ['elements_20to_20the_20system_20s_20controller_5',['5. Mapping driver elements to the system&apos;s controller',['../da/da9/group__cpp__kodi__addon__peripheral___docs___lifetime___driver_elements.html',1,'']]],
  ['em_20value_20help_20em_6',['&lt;em&gt;Value Help&lt;/em&gt;',['../dd/d8b/group__cpp__kodi__audioengine___defs___audio_engine_format___help.html',1,'']]],
  ['encoder_7',['Audio Encoder',['../d3/d8f/group__cpp__kodi__addon__audioencoder.html',1,'']]],
  ['encryption_8',['5. Stream encryption',['../d4/d6e/group__cpp__kodi__addon__inputstream___defs___stream_encryption.html',1,'']]],
  ['enum_20addon_5faction_9',['enum ADDON_ACTION',['../d0/d4c/group__cpp__kodi__gui___defs__action__ids.html',1,'']]],
  ['enum_20addon_5fimg_5fcolor_10',['enum ADDON_IMG_COLOR',['../d8/d53/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___c_o_l_o_r.html',1,'']]],
  ['enum_20addon_5fimg_5fexposure_5fmode_11',['enum ADDON_IMG_EXPOSURE_MODE',['../df/d8b/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___e_x_p_o_s_u_r_e___m_o_d_e.html',1,'']]],
  ['enum_20addon_5fimg_5fexposure_5fprogram_12',['enum ADDON_IMG_EXPOSURE_PROGRAM',['../d3/d93/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___e_x_p_o_s_u_r_e___p_r_o_g_r_a_m.html',1,'']]],
  ['enum_20addon_5fimg_5fflash_5ftype_13',['enum ADDON_IMG_FLASH_TYPE',['../d9/d29/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___f_l_a_s_h___t_y_p_e.html',1,'']]],
  ['enum_20addon_5fimg_5ffmt_14',['enum ADDON_IMG_FMT',['../de/d14/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___f_m_t.html',1,'']]],
  ['enum_20addon_5fimg_5flight_5fsource_15',['enum ADDON_IMG_LIGHT_SOURCE',['../db/dec/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___l_i_g_h_t___s_o_u_r_c_e.html',1,'']]],
  ['enum_20addon_5fimg_5fmetering_5fmode_16',['enum ADDON_IMG_METERING_MODE',['../dc/d0f/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___m_e_t_e_r_i_n_g___m_o_d_e.html',1,'']]],
  ['enum_20addon_5fimg_5forientation_17',['enum ADDON_IMG_ORIENTATION',['../dd/da6/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___o_r_i_e_n_t_a_t_i_o_n.html',1,'']]],
  ['enum_20addon_5flog_18',['enum ADDON_LOG',['../d0/d0a/group__cpp__kodi___defs___a_d_d_o_n___l_o_g.html',1,'']]],
  ['enum_20addon_5fstatus_19',['enum ADDON_STATUS',['../d6/dba/group__cpp__kodi__addon__addonbase___defs___a_d_d_o_n___s_t_a_t_u_s.html',1,'']]],
  ['enum_20addon_5ftype_20',['enum ADDON_TYPE',['../df/d4c/group__cpp__kodi__addon__addonbase___defs___a_d_d_o_n___t_y_p_e.html',1,'']]],
  ['enum_20audiodecoder_5fread_5freturn_21',['enum AUDIODECODER_READ_RETURN',['../db/dcb/group__cpp__kodi__addon__audiodecoder___defs___a_u_d_i_o_d_e_c_o_d_e_r___r_e_a_d___r_e_t_u_r_n.html',1,'']]],
  ['enum_20audioenginechannel_22',['enum AudioEngineChannel',['../d8/dfc/group__cpp__kodi__audioengine___defs___audio_engine_channel.html',1,'']]],
  ['enum_20audioenginedataformat_23',['enum AudioEngineDataFormat',['../de/d26/group__cpp__kodi__audioengine___defs___audio_engine_data_format.html',1,'']]],
  ['enum_20audioenginestreamoptions_24',['enum AudioEngineStreamOptions',['../db/df8/group__cpp__kodi__audioengine___defs___audio_engine_stream_options.html',1,'']]],
  ['enum_20curloptiontype_25',['enum CURLOptiontype',['../d2/dbb/group__cpp__kodi__vfs___defs___c_u_r_l_optiontype.html',1,'']]],
  ['enum_20epg_5fevent_5fcontentmask_20and_20sub_20types_26',['enum EPG_EVENT_CONTENTMASK (and sub types)',['../d9/d93/group__cpp__kodi__addon__pvr___defs__epg___e_p_g___e_v_e_n_t.html',1,'']]],
  ['enum_20epg_5fevent_5fstate_27',['enum EPG_EVENT_STATE',['../df/d83/group__cpp__kodi__addon__pvr___defs__epg___e_p_g___e_v_e_n_t___s_t_a_t_e.html',1,'']]],
  ['enum_20epg_5ftag_5fflag_28',['enum EPG_TAG_FLAG',['../de/dbf/group__cpp__kodi__addon__pvr___defs__epg___e_p_g___t_a_g___f_l_a_g.html',1,'']]],
  ['enum_20filepropertytypes_29',['enum FilePropertyTypes',['../dd/d76/group__cpp__kodi__vfs___defs___file_property_types.html',1,'']]],
  ['enum_20inputstream_5fcodec_5ffeatures_30',['enum INPUTSTREAM_CODEC_FEATURES',['../d1/d2b/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___c_o_d_e_c___f_e_a_t_u_r_e_s.html',1,'']]],
  ['enum_20inputstream_5fcolorprimaries_31',['enum INPUTSTREAM_COLORPRIMARIES',['../d9/d13/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___c_o_l_o_r_p_r_i_m_a_r_i_e_s.html',1,'']]],
  ['enum_20inputstream_5fcolorrange_32',['enum INPUTSTREAM_COLORRANGE',['../dd/d57/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___c_o_l_o_r_r_a_n_g_e.html',1,'']]],
  ['enum_20inputstream_5fcolorspace_33',['enum INPUTSTREAM_COLORSPACE',['../db/d96/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___c_o_l_o_r_s_p_a_c_e.html',1,'']]],
  ['enum_20inputstream_5fcolortrc_34',['enum INPUTSTREAM_COLORTRC',['../d5/d84/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___c_o_l_o_r_t_r_c.html',1,'']]],
  ['enum_20inputstream_5fflags_35',['enum INPUTSTREAM_FLAGS',['../d0/d11/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___f_l_a_g_s.html',1,'']]],
  ['enum_20inputstream_5ftype_36',['enum INPUTSTREAM_TYPE',['../d2/d54/group__cpp__kodi__addon__inputstream___defs___interface___i_n_p_u_t_s_t_r_e_a_m___t_y_p_e.html',1,'']]],
  ['enum_20joystick_5fdriver_5fhat_5fdirection_37',['enum JOYSTICK_DRIVER_HAT_DIRECTION',['../d6/d3a/group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___d_r_i_v_e_r___h_a_t___d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['enum_20joystick_5fdriver_5fmouse_5findex_38',['enum JOYSTICK_DRIVER_MOUSE_INDEX',['../d7/d7e/group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___d_r_i_v_e_r___m_o_u_s_e___i_n_d_e_x.html',1,'']]],
  ['enum_20joystick_5fdriver_5fprimitive_5ftype_39',['enum JOYSTICK_DRIVER_PRIMITIVE_TYPE',['../d5/d1d/group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___d_r_i_v_e_r___p_r_i_m_i_t_i_v_e___t_y_p_e.html',1,'']]],
  ['enum_20joystick_5fdriver_5frelpointer_5fdirection_40',['enum JOYSTICK_DRIVER_RELPOINTER_DIRECTION',['../dd/def/group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___d_r_i_v_e_r___r_e_l_p_o_i_n_t_e_r___d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['enum_20joystick_5fdriver_5fsemiaxis_5fdirection_41',['enum JOYSTICK_DRIVER_SEMIAXIS_DIRECTION',['../de/d2f/group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___d_r_i_v_e_r___s_e_m_i_a_x_i_s___d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['enum_20joystick_5ffeature_5fprimitive_42',['enum JOYSTICK_FEATURE_PRIMITIVE',['../de/d45/group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___f_e_a_t_u_r_e___p_r_i_m_i_t_i_v_e.html',1,'']]],
  ['enum_20joystick_5ffeature_5ftype_43',['enum JOYSTICK_FEATURE_TYPE',['../d0/df0/group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___f_e_a_t_u_r_e___t_y_p_e.html',1,'']]],
  ['enum_20joystick_5fstate_5fbutton_44',['enum JOYSTICK_STATE_BUTTON',['../da/d1d/group__cpp__kodi__addon__peripheral___defs___event___j_o_y_s_t_i_c_k___s_t_a_t_e___b_u_t_t_o_n.html',1,'']]],
  ['enum_20joystick_5fstate_5fhat_45',['enum JOYSTICK_STATE_HAT',['../d7/ddd/group__cpp__kodi__addon__peripheral___defs___event___j_o_y_s_t_i_c_k___s_t_a_t_e___h_a_t.html',1,'']]],
  ['enum_20openfileflags_46',['enum OpenFileFlags',['../da/d47/group__cpp__kodi__vfs___defs___open_file_flags.html',1,'']]],
  ['enum_20peripheral_5ferror_47',['enum PERIPHERAL_ERROR',['../df/dc3/group__cpp__kodi__addon__peripheral___defs___general___p_e_r_i_p_h_e_r_a_l___e_r_r_o_r.html',1,'']]],
  ['enum_20peripheral_5fevent_5ftype_48',['enum PERIPHERAL_EVENT_TYPE',['../db/d9a/group__cpp__kodi__addon__peripheral___defs___event___p_e_r_i_p_h_e_r_a_l___e_v_e_n_t___t_y_p_e.html',1,'']]],
  ['enum_20peripheral_5ftype_49',['enum PERIPHERAL_TYPE',['../dd/d79/group__cpp__kodi__addon__peripheral___defs___peripheral___p_e_r_i_p_h_e_r_a_l___t_y_p_e.html',1,'']]],
  ['enum_20pvr_5fcodec_5ftype_50',['enum PVR_CODEC_TYPE',['../da/db8/group__cpp__kodi__addon__pvr___defs___stream___p_v_r___c_o_d_e_c___t_y_p_e.html',1,'']]],
  ['enum_20pvr_5fconnection_5fstate_51',['enum PVR_CONNECTION_STATE',['../d5/d60/group__cpp__kodi__addon__pvr___defs___general___p_v_r___c_o_n_n_e_c_t_i_o_n___s_t_a_t_e.html',1,'']]],
  ['enum_20pvr_5fedl_5ftype_52',['enum PVR_EDL_TYPE',['../d2/de2/group__cpp__kodi__addon__pvr___defs___e_d_l_entry___p_v_r___e_d_l___t_y_p_e.html',1,'']]],
  ['enum_20pvr_5ferror_53',['enum PVR_ERROR',['../d0/d9d/group__cpp__kodi__addon__pvr___defs___general___p_v_r___e_r_r_o_r.html',1,'']]],
  ['enum_20pvr_5fmenuhook_5fcat_54',['enum PVR_MENUHOOK_CAT',['../d5/d59/group__cpp__kodi__addon__pvr___defs___menuhook___p_v_r___m_e_n_u_h_o_o_k___c_a_t.html',1,'']]],
  ['enum_20pvr_5fprovider_5ftype_55',['enum PVR_PROVIDER_TYPE',['../d4/d14/group__cpp__kodi__addon__pvr___defs___channel___p_v_r___p_r_o_v_i_d_e_r___t_y_p_e.html',1,'']]],
  ['enum_20pvr_5frecording_5fchannel_5ftype_56',['enum PVR_RECORDING_CHANNEL_TYPE',['../d3/df2/group__cpp__kodi__addon__pvr___defs___recording___p_v_r___r_e_c_o_r_d_i_n_g___c_h_a_n_n_e_l___t_y_p_e.html',1,'']]],
  ['enum_20pvr_5frecording_5fflag_57',['enum PVR_RECORDING_FLAG',['../dc/d2c/group__cpp__kodi__addon__pvr___defs___recording___p_v_r___r_e_c_o_r_d_i_n_g___f_l_a_g.html',1,'']]],
  ['enum_20pvr_5fsetting_5freadonly_5fcondition_58',['enum PVR_SETTING_READONLY_CONDITION',['../d7/df8/group__cpp__kodi__addon__pvr___defs___general___p_v_r___s_e_t_t_i_n_g___r_e_a_d_o_n_l_y___c_o_n_d_i_t_i_o_n.html',1,'']]],
  ['enum_20pvr_5fsetting_5ftype_59',['enum PVR_SETTING_TYPE',['../de/d73/group__cpp__kodi__addon__pvr___defs___general___p_v_r___s_e_t_t_i_n_g___t_y_p_e.html',1,'']]],
  ['enum_20pvr_5fsource_60',['enum PVR_SOURCE',['../d2/d09/group__cpp__kodi__addon__pvr___defs___general___p_v_r___s_o_u_r_c_e.html',1,'']]],
  ['enum_20pvr_5ftimer_5fstate_61',['enum PVR_TIMER_STATE',['../d0/d49/group__cpp__kodi__addon__pvr___defs___timer___p_v_r___t_i_m_e_r___s_t_a_t_e.html',1,'']]],
  ['enum_20pvr_5ftimer_5ftypes_62',['enum PVR_TIMER_TYPES',['../d6/d3e/group__cpp__kodi__addon__pvr___defs___timer___p_v_r___t_i_m_e_r___t_y_p_e_s.html',1,'']]],
  ['enum_20pvr_5fweekday_63',['enum PVR_WEEKDAY',['../d1/dcd/group__cpp__kodi__addon__pvr___defs___timer___p_v_r___w_e_e_k_d_a_y.html',1,'']]],
  ['enum_20stream_5fcrypto_5fflags_64',['enum STREAM_CRYPTO_FLAGS',['../d8/db5/group__cpp__kodi__addon__inputstream___defs___stream_encryption___s_t_r_e_a_m___c_r_y_p_t_o___f_l_a_g_s.html',1,'']]],
  ['enum_20stream_5fcrypto_5fkey_5fsystem_65',['enum STREAM_CRYPTO_KEY_SYSTEM',['../d9/d3f/group__cpp__kodi__addon__inputstream___defs___stream_encryption___s_t_r_e_a_m___c_r_y_p_t_o___k_e_y___s_y_s_t_e_m.html',1,'']]],
  ['enum_20streamcodec_5fprofile_66',['enum STREAMCODEC_PROFILE',['../dd/d86/group__cpp__kodi__addon__inputstream___defs___stream_encryption___s_t_r_e_a_m_c_o_d_e_c___p_r_o_f_i_l_e.html',1,'']]],
  ['enum_20time_5fformat_67',['enum TIME_FORMAT',['../dd/da5/group__cpp__kodi__tools___string_utils___defs___t_i_m_e___f_o_r_m_a_t.html',1,'']]],
  ['enumerators_68',['enumerators',['../db/d89/group__cpp__kodi__addon__peripheral___defs.html',1,'Definitions, structures and enumerators'],['../d9/d97/group__cpp__kodi__addon__addonbase___defs.html',1,'Definitions, structures and enumerators'],['../dc/d46/group__cpp__kodi__addon__inputstream___defs.html',1,'Definitions, structures and enumerators'],['../da/dd1/group__cpp__kodi__addon__imagedecoder___defs.html',1,'Definitions, structures and enumerators'],['../d4/d94/group__cpp__kodi__addon__game___defs.html',1,'Definitions, structures and enumerators'],['../d2/d7e/group__cpp__kodi__addon__audiodecoder___defs.html',1,'Definitions, structures and enumerators'],['../d0/da1/group__cpp__kodi__vfs___defs.html',1,'Definitions, structures and enumerators'],['../dd/d40/group__cpp__kodi__gui__windows__controls___c_edit___defs.html',1,'Definitions, structures and enumerators'],['../dc/d99/group__cpp__kodi__gui__dialogs___select___defs.html',1,'Definitions, structures and enumerators'],['../d7/dd1/group__cpp__kodi__gui__windows__window___defs.html',1,'Definitions, structures and enumerators'],['../dc/db9/group__cpp__kodi__tools___string_utils___defs.html',1,'Definitions, structures and enumerators'],['../d2/d35/group__cpp__kodi__gui___defs.html',1,'Definitions, structures and enumerators'],['../d6/dac/group__cpp__kodi__addon__videocodec___defs.html',1,'Definitions, structures and enumerators'],['../d6/d5f/group__cpp__kodi__addon__pvr___defs.html',1,'Definitions, structures and enumerators'],['../de/dac/group__cpp__kodi___defs.html',1,'Definitions, structures and enumerators'],['../d1/d5f/group__cpp__kodi__audioengine___defs.html',1,'Definitions, structures and enumerators'],['../d2/d15/group__cpp__kodi__addon__vfs___defs.html',1,'Definitions, structures and enumerators'],['../df/d16/group__cpp__kodi__addon__visualization___defs.html',1,'Definitions, structures and enumerators']]],
  ['environment_20types_69',['8. Environment types',['../d6/da0/group__cpp__kodi__addon__game___defs___environment_types.html',1,'']]],
  ['epg_20methods_20optional_70',['4. EPG methods (optional)',['../dd/df4/group__cpp__kodi__addon__pvr___e_p_g_tag.html',1,'']]],
  ['epg_20tag_71',['4. EPG Tag',['../d2/d8d/group__cpp__kodi__addon__pvr___defs__epg.html',1,'']]],
  ['epg_5fevent_5fcontentmask_20and_20sub_20types_72',['enum EPG_EVENT_CONTENTMASK (and sub types)',['../d9/d93/group__cpp__kodi__addon__pvr___defs__epg___e_p_g___e_v_e_n_t.html',1,'']]],
  ['epg_5fevent_5fstate_73',['enum EPG_EVENT_STATE',['../df/d83/group__cpp__kodi__addon__pvr___defs__epg___e_p_g___e_v_e_n_t___s_t_a_t_e.html',1,'']]],
  ['epg_5ftag_5fflag_74',['enum EPG_TAG_FLAG',['../de/dbf/group__cpp__kodi__addon__pvr___defs__epg___e_p_g___t_a_g___f_l_a_g.html',1,'']]],
  ['event_75',['3. Event',['../da/dd3/group__cpp__kodi__addon__peripheral___defs___event.html',1,'']]],
  ['events_76',['events',['../d9/dea/group__cpp__kodi__addon__peripheral___docs___lifetime___receiving.html',1,'2. Receiving joystick events'],['../d3/d96/group__cpp__kodi__addon__peripheral___docs___lifetime___events.html',1,'3. Handling events']]],
  ['events_20optional_77',['7. Power management events (optional)',['../df/d4f/group__cpp__kodi__addon__pvr___power_management.html',1,'']]],
  ['extended_20progress_78',['Dialog Extended Progress',['../d8/d50/group__cpp__kodi__gui__dialogs___c_extended_progress.html',1,'']]]
];
