var searchData=
[
  ['database_0',['Database',['../df/db7/group__database.html',1,'']]],
  ['decision_20list_20edl_1',['9. Edit decision list (EDL)',['../db/d20/group__cpp__kodi__addon__pvr___defs___e_d_l_entry.html',1,'']]],
  ['decoder_2',['decoder',['../d1/dbe/group__cpp__kodi__addon__audiodecoder.html',1,'Audio Decoder'],['../d1/dbc/group__cpp__kodi__addon__imagedecoder.html',1,'Image Decoder']]],
  ['definition_20pvr_5fstream_5fproperty_3',['definition pvr_stream_property',['../db/de7/group__cpp__kodi__addon__pvr___defs___general___inputstream.html',1,'class PVRStreamProperty &amp; definition PVR_STREAM_PROPERTY'],['../dc/de0/group__cpp__kodi__addon__pvr___defs___general___p_v_r___s_t_r_e_a_m___p_r_o_p_e_r_t_y.html',1,'definition PVR_STREAM_PROPERTY']]],
  ['definition_20pvr_5ftimer_20various_4',['definition PVR_TIMER (various)',['../d6/df2/group__cpp__kodi__addon__pvr___defs___timer___p_v_r___t_i_m_e_r__.html',1,'']]],
  ['definitions_20structures_20and_20enumerators_5',['definitions structures and enumerators',['../d7/dd1/group__cpp__kodi__gui__windows__window___defs.html',1,'Definitions, structures and enumerators'],['../dc/d99/group__cpp__kodi__gui__dialogs___select___defs.html',1,'Definitions, structures and enumerators'],['../dd/d40/group__cpp__kodi__gui__windows__controls___c_edit___defs.html',1,'Definitions, structures and enumerators'],['../d0/da1/group__cpp__kodi__vfs___defs.html',1,'Definitions, structures and enumerators'],['../d1/d5f/group__cpp__kodi__audioengine___defs.html',1,'Definitions, structures and enumerators'],['../df/d16/group__cpp__kodi__addon__visualization___defs.html',1,'Definitions, structures and enumerators'],['../d6/dac/group__cpp__kodi__addon__videocodec___defs.html',1,'Definitions, structures and enumerators'],['../d2/d15/group__cpp__kodi__addon__vfs___defs.html',1,'Definitions, structures and enumerators'],['../dc/db9/group__cpp__kodi__tools___string_utils___defs.html',1,'Definitions, structures and enumerators'],['../d9/d97/group__cpp__kodi__addon__addonbase___defs.html',1,'Definitions, structures and enumerators'],['../de/dac/group__cpp__kodi___defs.html',1,'Definitions, structures and enumerators'],['../db/d89/group__cpp__kodi__addon__peripheral___defs.html',1,'Definitions, structures and enumerators'],['../dc/d46/group__cpp__kodi__addon__inputstream___defs.html',1,'Definitions, structures and enumerators'],['../da/dd1/group__cpp__kodi__addon__imagedecoder___defs.html',1,'Definitions, structures and enumerators'],['../d4/d94/group__cpp__kodi__addon__game___defs.html',1,'Definitions, structures and enumerators'],['../d2/d7e/group__cpp__kodi__addon__audiodecoder___defs.html',1,'Definitions, structures and enumerators'],['../d2/d35/group__cpp__kodi__gui___defs.html',1,'Definitions, structures and enumerators'],['../d6/d5f/group__cpp__kodi__addon__pvr___defs.html',1,'Definitions, structures and enumerators']]],
  ['demux_5fcrypto_5finfo_6',['struct DEMUX_CRYPTO_INFO',['../db/d45/group__cpp__kodi__addon__inputstream___defs___stream_encryption___d_e_m_u_x___c_r_y_p_t_o___i_n_f_o.html',1,'']]],
  ['demux_5fpacket_7',['struct DEMUX_PACKET',['../d2/ddf/group__cpp__kodi__addon__inputstream___defs___interface___d_e_m_u_x___p_a_c_k_e_t.html',1,'']]],
  ['demuxing_8',['8.1.1. Stream demuxing',['../d6/d00/group__cpp__kodi__addon__pvr___streams___t_v___demux.html',1,'']]],
  ['demuxing_20optional_9',['2. Stream demuxing (optional)',['../da/d1b/group__cpp__kodi__addon__inputstream___demux.html',1,'']]],
  ['dialog_10',['Dialog',['../d6/de8/group__python___dialog.html',1,'']]],
  ['dialog_20context_20menu_11',['Dialog Context Menu',['../de/d4c/group__cpp__kodi__gui__dialogs___context_menu.html',1,'']]],
  ['dialog_20extended_20progress_12',['Dialog Extended Progress',['../d8/d50/group__cpp__kodi__gui__dialogs___c_extended_progress.html',1,'']]],
  ['dialog_20file_20browser_13',['Dialog File Browser',['../dc/dcb/group__cpp__kodi__gui__dialogs___file_browser.html',1,'']]],
  ['dialog_20keyboard_14',['Dialog Keyboard',['../d6/db3/group__cpp__kodi__gui__dialogs___keyboard.html',1,'']]],
  ['dialog_20numeric_15',['Dialog Numeric',['../d0/d8d/group__cpp__kodi__gui__dialogs___numeric.html',1,'']]],
  ['dialog_20ok_16',['Dialog OK',['../d5/db4/group__cpp__kodi__gui__dialogs___o_k.html',1,'']]],
  ['dialog_20progress_17',['Dialog Progress',['../db/dd0/group__cpp__kodi__gui__dialogs___c_progress.html',1,'']]],
  ['dialog_20select_18',['Dialog Select',['../d6/da0/group__cpp__kodi__gui__dialogs___select.html',1,'']]],
  ['dialog_20text_20viewer_19',['Dialog Text Viewer',['../d5/d5f/group__cpp__kodi__gui__dialogs___text_viewer.html',1,'']]],
  ['dialog_20yes_20no_20',['Dialog Yes/No',['../d4/dc5/group__cpp__kodi__gui__dialogs___yes_no.html',1,'']]],
  ['dialogprogress_21',['DialogProgress',['../de/d19/group__python___dialog_progress.html',1,'']]],
  ['dialogprogressbg_22',['DialogProgressBG',['../dd/d18/group__python___dialog_progress_b_g.html',1,'']]],
  ['dialogs_23',['2. Dialogs',['../db/d44/group__cpp__kodi__gui__dialogs.html',1,'']]],
  ['directory_20functions_24',['1. Directory functions',['../dc/da1/group__cpp__kodi__vfs___directory.html',1,'']]],
  ['driver_20elements_20to_20the_20system_20s_20controller_25',['5. Mapping driver elements to the system&apos;s controller',['../da/da9/group__cpp__kodi__addon__peripheral___docs___lifetime___driver_elements.html',1,'']]],
  ['driver_20fuckery_26',['4. Joystick driver fuckery',['../df/d17/group__cpp__kodi__addon__peripheral___docs___controller_input___joystick_driver_fuckery.html',1,'']]],
  ['driverprimitive_27',['class DriverPrimitive',['../d5/d57/group__cpp__kodi__addon__peripheral___defs___joystick___driver_primitive.html',1,'']]],
  ['drivers_28',['2. Joystick drivers',['../d4/dfe/group__cpp__kodi__addon__peripheral___docs___controller_input___joystick_drivers.html',1,'']]]
];
