var searchData=
[
  ['a_20button_20press_0',['Lifetime of a button press',['../d9/db1/group__cpp__kodi__addon__peripheral___docs___lifetime.html',1,'']]],
  ['access_20functions_1',['1. General access functions',['../d4/d15/group__cpp__kodi__addon__vfs__general.html',1,'']]],
  ['action_2',['Action',['../dc/d13/group__python__xbmcgui__action.html',1,'']]],
  ['action_20id_20s_3',['Action Id&apos;s',['../d9/d2e/group__kodi__key__action__ids.html',1,'']]],
  ['actions_20and_20keys_4',['Actions and Keys',['../dd/d89/group__actionkeys.html',1,'']]],
  ['actor_5',['Actor',['../de/d05/group__python__xbmc__actor.html',1,'']]],
  ['add_20on_6',['add on',['../d4/df8/group__python__xbmcgui__window__cb.html',1,'Callback functions from Kodi to add-on'],['../dd/d41/group__python___player_c_b.html',1,'Callback functions from Kodi to Add-On'],['../dd/d1b/group__cpp__kodi__gui__windows__window__callbacks.html',1,'Callback functions from Kodi to add-on']]],
  ['addon_20creation_20structure_7',['CMake addon creation structure',['../d0/dbc/group__cpp__cmake.html',1,'']]],
  ['addon_20type_20instances_8',['Addon type instances',['../d5/d80/group__cpp__kodi__addon__instances.html',1,'']]],
  ['addon_5faction_9',['enum ADDON_ACTION',['../d0/d4c/group__cpp__kodi__gui___defs__action__ids.html',1,'']]],
  ['addon_5fimg_5fcolor_10',['enum ADDON_IMG_COLOR',['../d8/d53/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___c_o_l_o_r.html',1,'']]],
  ['addon_5fimg_5fexposure_5fmode_11',['enum ADDON_IMG_EXPOSURE_MODE',['../df/d8b/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___e_x_p_o_s_u_r_e___m_o_d_e.html',1,'']]],
  ['addon_5fimg_5fexposure_5fprogram_12',['enum ADDON_IMG_EXPOSURE_PROGRAM',['../d3/d93/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___e_x_p_o_s_u_r_e___p_r_o_g_r_a_m.html',1,'']]],
  ['addon_5fimg_5fflash_5ftype_13',['enum ADDON_IMG_FLASH_TYPE',['../d9/d29/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___f_l_a_s_h___t_y_p_e.html',1,'']]],
  ['addon_5fimg_5ffmt_14',['enum ADDON_IMG_FMT',['../de/d14/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___f_m_t.html',1,'']]],
  ['addon_5fimg_5flight_5fsource_15',['enum ADDON_IMG_LIGHT_SOURCE',['../db/dec/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___l_i_g_h_t___s_o_u_r_c_e.html',1,'']]],
  ['addon_5fimg_5fmetering_5fmode_16',['enum ADDON_IMG_METERING_MODE',['../dc/d0f/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___m_e_t_e_r_i_n_g___m_o_d_e.html',1,'']]],
  ['addon_5fimg_5forientation_17',['enum ADDON_IMG_ORIENTATION',['../dd/da6/group__cpp__kodi__addon__imagedecoder___defs___a_d_d_o_n___i_m_g___o_r_i_e_n_t_a_t_i_o_n.html',1,'']]],
  ['addon_5flog_18',['enum ADDON_LOG',['../d0/d0a/group__cpp__kodi___defs___a_d_d_o_n___l_o_g.html',1,'']]],
  ['addon_5fstatus_19',['enum ADDON_STATUS',['../d6/dba/group__cpp__kodi__addon__addonbase___defs___a_d_d_o_n___s_t_a_t_u_s.html',1,'']]],
  ['addon_5ftype_20',['enum ADDON_TYPE',['../df/d4c/group__cpp__kodi__addon__addonbase___defs___a_d_d_o_n___t_y_p_e.html',1,'']]],
  ['addonclass_21',['macro ADDONCREATOR(AddonClass)',['../d1/df4/group__cpp__kodi__addon__addonbase___defs___a_d_d_o_n_c_r_e_a_t_o_r_addon_class.html',1,'']]],
  ['addoncreator_20addonclass_22',['macro ADDONCREATOR(AddonClass)',['../d1/df4/group__cpp__kodi__addon__addonbase___defs___a_d_d_o_n_c_r_e_a_t_o_r_addon_class.html',1,'']]],
  ['alignment_20flags_23',['Font alignment flags',['../d7/d28/group__kodi__gui__font__alignment.html',1,'']]],
  ['and_20callbacks_24',['Window Manager and Callbacks',['../d6/df1/group__winman.html',1,'']]],
  ['and_20enumerators_25',['and enumerators',['../de/dac/group__cpp__kodi___defs.html',1,'Definitions, structures and enumerators'],['../dc/db9/group__cpp__kodi__tools___string_utils___defs.html',1,'Definitions, structures and enumerators'],['../d0/da1/group__cpp__kodi__vfs___defs.html',1,'Definitions, structures and enumerators'],['../dd/d40/group__cpp__kodi__gui__windows__controls___c_edit___defs.html',1,'Definitions, structures and enumerators'],['../dc/d99/group__cpp__kodi__gui__dialogs___select___defs.html',1,'Definitions, structures and enumerators'],['../d7/dd1/group__cpp__kodi__gui__windows__window___defs.html',1,'Definitions, structures and enumerators'],['../d9/d97/group__cpp__kodi__addon__addonbase___defs.html',1,'Definitions, structures and enumerators'],['../d2/d35/group__cpp__kodi__gui___defs.html',1,'Definitions, structures and enumerators'],['../d1/d5f/group__cpp__kodi__audioengine___defs.html',1,'Definitions, structures and enumerators'],['../d2/d7e/group__cpp__kodi__addon__audiodecoder___defs.html',1,'Definitions, structures and enumerators'],['../d4/d94/group__cpp__kodi__addon__game___defs.html',1,'Definitions, structures and enumerators'],['../da/dd1/group__cpp__kodi__addon__imagedecoder___defs.html',1,'Definitions, structures and enumerators'],['../df/d16/group__cpp__kodi__addon__visualization___defs.html',1,'Definitions, structures and enumerators'],['../d6/dac/group__cpp__kodi__addon__videocodec___defs.html',1,'Definitions, structures and enumerators'],['../d2/d15/group__cpp__kodi__addon__vfs___defs.html',1,'Definitions, structures and enumerators'],['../d6/d5f/group__cpp__kodi__addon__pvr___defs.html',1,'Definitions, structures and enumerators'],['../db/d89/group__cpp__kodi__addon__peripheral___defs.html',1,'Definitions, structures and enumerators'],['../dc/d46/group__cpp__kodi__addon__inputstream___defs.html',1,'Definitions, structures and enumerators']]],
  ['and_20fonts_26',['Textures and Fonts',['../d7/db5/group__textures.html',1,'']]],
  ['and_20keys_27',['Actions and Keys',['../dd/d89/group__actionkeys.html',1,'']]],
  ['and_20localization_28',['Strings and Localization',['../d7/d0c/group__strings.html',1,'']]],
  ['and_20messages_29',['Windows and Messages',['../d5/d34/group__winmsg.html',1,'']]],
  ['and_20screen_30',['Graphics and Screen',['../d6/de0/group__graphics.html',1,'']]],
  ['and_20sub_20types_31',['enum EPG_EVENT_CONTENTMASK (and sub types)',['../d9/d93/group__cpp__kodi__addon__pvr___defs__epg___e_p_g___e_v_e_n_t.html',1,'']]],
  ['api_32',['4. Handling input for the Game API',['../de/d62/group__cpp__kodi__addon__peripheral___docs___lifetime___input.html',1,'']]],
  ['asynchronous_20jobs_33',['Asynchronous jobs',['../da/d6b/group__jobs.html',1,'']]],
  ['audio_20decoder_34',['Audio Decoder',['../d1/dbe/group__cpp__kodi__addon__audiodecoder.html',1,'']]],
  ['audio_20encoder_35',['Audio Encoder',['../d3/d8f/group__cpp__kodi__addon__audioencoder.html',1,'']]],
  ['audio_20stream_36',['1. Audio stream',['../d3/d4a/group__cpp__kodi__addon__game___defs___audio_stream.html',1,'']]],
  ['audiodecoder_5fread_5freturn_37',['enum AUDIODECODER_READ_RETURN',['../db/dcb/group__cpp__kodi__addon__audiodecoder___defs___a_u_d_i_o_d_e_c_o_d_e_r___r_e_a_d___r_e_t_u_r_n.html',1,'']]],
  ['audiodecoderinfotag_38',['class AudioDecoderInfoTag',['../d2/d69/group__cpp__kodi__addon__audiodecoder___defs___audio_decoder_info_tag.html',1,'']]],
  ['audioencoderinfotag_39',['class AudioEncoderInfoTag',['../de/dfd/group__cpp__kodi__addon__audioencoder___defs___audio_encoder_info_tag.html',1,'']]],
  ['audioenginechannel_40',['enum AudioEngineChannel',['../d8/dfc/group__cpp__kodi__audioengine___defs___audio_engine_channel.html',1,'']]],
  ['audioenginedataformat_41',['enum AudioEngineDataFormat',['../de/d26/group__cpp__kodi__audioengine___defs___audio_engine_data_format.html',1,'']]],
  ['audioengineformat_42',['class AudioEngineFormat',['../d2/de7/group__cpp__kodi__audioengine___defs___audio_engine_format.html',1,'']]],
  ['audioenginestreamoptions_43',['enum AudioEngineStreamOptions',['../db/df8/group__cpp__kodi__audioengine___defs___audio_engine_stream_options.html',1,'']]],
  ['audiostreamdetail_44',['AudioStreamDetail',['../da/da3/group__python__xbmc__audiostreamdetail.html',1,'']]]
];
