var searchData=
[
  ['tag_0',['4. EPG Tag',['../d2/d8d/group__cpp__kodi__addon__pvr___defs__epg.html',1,'']]],
  ['text_20box_1',['Control Text Box',['../df/d0b/group__cpp__kodi__gui__windows__controls___c_text_box.html',1,'']]],
  ['text_20viewer_2',['Dialog Text Viewer',['../d5/d5f/group__cpp__kodi__gui__dialogs___text_viewer.html',1,'']]],
  ['textures_20and_20fonts_3',['Textures and Fonts',['../d7/db5/group__textures.html',1,'']]],
  ['the_20game_20api_4',['4. Handling input for the Game API',['../de/d62/group__cpp__kodi__addon__peripheral___docs___lifetime___input.html',1,'']]],
  ['the_20system_20s_20controller_5',['5. Mapping driver elements to the system&apos;s controller',['../da/da9/group__cpp__kodi__addon__peripheral___docs___lifetime___driver_elements.html',1,'']]],
  ['thumbs_6',['Thumbs',['../d7/d1a/group__thumbs.html',1,'']]],
  ['time_20optional_7',['time optional',['../d6/d52/group__cpp__kodi__addon__inputstream___time.html',1,'3. Time (optional)'],['../df/d0e/group__cpp__kodi__addon__inputstream___pos_time.html',1,'5. Position time (optional)']]],
  ['time_20value_20processing_8',['Time value processing',['../d2/d34/group__cpp__kodi__tools___string_utils___time_control.html',1,'']]],
  ['time_5fformat_9',['enum TIME_FORMAT',['../dd/da5/group__cpp__kodi__tools___string_utils___defs___t_i_m_e___f_o_r_m_a_t.html',1,'']]],
  ['timer_10',['6. Timer',['../d8/d37/group__cpp__kodi__addon__pvr___defs___timer.html',1,'']]],
  ['timers_20optional_11',['6. Timers (optional)',['../df/d70/group__cpp__kodi__addon__pvr___timers.html',1,'']]],
  ['times_20optional_12',['4. Times (optional)',['../df/d90/group__cpp__kodi__addon__inputstream___times.html',1,'']]],
  ['timing_13',['3. Stream timing',['../dd/da5/group__cpp__kodi__addon__inputstream___defs___timing_constants.html',1,'']]],
  ['to_20add_20on_14',['to add on',['../d4/df8/group__python__xbmcgui__window__cb.html',1,'Callback functions from Kodi to add-on'],['../dd/d41/group__python___player_c_b.html',1,'Callback functions from Kodi to Add-On'],['../dd/d1b/group__cpp__kodi__gui__windows__window__callbacks.html',1,'Callback functions from Kodi to add-on']]],
  ['to_20libretro_20s_20retropad_15',['6. Translating Kodi controller to libretro&apos;s &quot;RetroPad&quot;',['../db/d99/group__cpp__kodi__addon__peripheral___docs___lifetime___translating.html',1,'']]],
  ['to_20the_20system_20s_20controller_16',['5. Mapping driver elements to the system&apos;s controller',['../da/da9/group__cpp__kodi__addon__peripheral___docs___lifetime___driver_elements.html',1,'']]],
  ['touch_17',['touch',['../da/ddf/group__touch__generic.html',1,'Touch'],['../db/d78/group__touch.html',1,'Touch']]],
  ['translating_20kodi_20controller_20to_20libretro_20s_20retropad_18',['6. Translating Kodi controller to libretro&apos;s &quot;RetroPad&quot;',['../db/d99/group__cpp__kodi__addon__peripheral___docs___lifetime___translating.html',1,'']]],
  ['tv_20stream_19',['8.1. TV stream',['../d9/deb/group__cpp__kodi__addon__pvr___streams___t_v.html',1,'']]],
  ['type_20instances_20',['Addon type instances',['../d5/d80/group__cpp__kodi__addon__instances.html',1,'']]],
  ['types_21',['types',['../d2/de0/group__cpp__kodi__addon__game___defs___stream_types.html',1,'5. Stream types'],['../d8/daa/group__cpp__kodi__addon__game___defs___game_types.html',1,'6. Game types'],['../d4/d53/group__cpp__kodi__addon__game___defs___input_types.html',1,'7. Input types'],['../d6/da0/group__cpp__kodi__addon__game___defs___environment_types.html',1,'8. Environment types'],['../d9/d93/group__cpp__kodi__addon__pvr___defs__epg___e_p_g___e_v_e_n_t.html',1,'enum EPG_EVENT_CONTENTMASK (and sub types)'],['../d2/d59/group__kodi__guilib__listitem__iconoverlay.html',1,'Overlay icon types']]]
];
