var searchData=
[
  ['parser_0',['XML Parser',['../dd/db4/group__tinyxml.html',1,'']]],
  ['peripheral_1',['peripheral',['../d8/d0d/group__cpp__kodi__addon__peripheral___defs___peripheral.html',1,'2. Peripheral'],['../d3/da4/group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral.html',1,'class Peripheral'],['../df/d65/group__cpp__kodi__addon__peripheral.html',1,'Peripheral']]],
  ['peripheral_20operations_2',['1. Peripheral operations',['../dc/d01/group__cpp__kodi__addon__peripheral__peripheral_op.html',1,'']]],
  ['peripheral_20system_3',['Peripheral system',['../d6/dde/group__cpp__kodi__addon__peripheral___docs.html',1,'']]],
  ['peripheral_5ferror_4',['enum PERIPHERAL_ERROR',['../df/dc3/group__cpp__kodi__addon__peripheral___defs___general___p_e_r_i_p_h_e_r_a_l___e_r_r_o_r.html',1,'']]],
  ['peripheral_5fevent_5ftype_5',['enum PERIPHERAL_EVENT_TYPE',['../db/d9a/group__cpp__kodi__addon__peripheral___defs___event___p_e_r_i_p_h_e_r_a_l___e_v_e_n_t___t_y_p_e.html',1,'']]],
  ['peripheral_5ftype_6',['enum PERIPHERAL_TYPE',['../dd/d79/group__cpp__kodi__addon__peripheral___defs___peripheral___p_e_r_i_p_h_e_r_a_l___t_y_p_e.html',1,'']]],
  ['peripheralcapabilities_7',['class PeripheralCapabilities',['../d6/dbe/group__cpp__kodi__addon__peripheral___defs___peripheral_capabilities.html',1,'']]],
  ['peripheralevent_8',['class PeripheralEvent',['../d7/d89/group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral_event.html',1,'']]],
  ['peripherals_9',['1. Scanning for peripherals',['../da/deb/group__cpp__kodi__addon__peripheral___docs___lifetime___scanning.html',1,'']]],
  ['player_10',['Player',['../d9/da1/group__python___player.html',1,'']]],
  ['playlist_11',['PlayList',['../d2/d85/group__python___play_list.html',1,'']]],
  ['position_20time_20optional_12',['5. Position time (optional)',['../df/d0e/group__cpp__kodi__addon__inputstream___pos_time.html',1,'']]],
  ['power_20management_20events_20optional_13',['7. Power management events (optional)',['../df/d4f/group__cpp__kodi__addon__pvr___power_management.html',1,'']]],
  ['press_14',['Lifetime of a button press',['../d9/db1/group__cpp__kodi__addon__peripheral___docs___lifetime.html',1,'']]],
  ['processing_15',['Time value processing',['../d2/d34/group__cpp__kodi__tools___string_utils___time_control.html',1,'']]],
  ['profiles_16',['1. Controller profiles',['../da/dc3/group__cpp__kodi__addon__peripheral___docs___controller_input___profiles.html',1,'']]],
  ['program_17',['GL Shader Program',['../db/d9a/group__cpp__kodi__gui__helpers__gl___c_shader_program.html',1,'']]],
  ['progress_18',['progress',['../d0/d04/group__cpp__kodi__gui__windows__controls___c_progress.html',1,'Control Progress'],['../d8/d50/group__cpp__kodi__gui__dialogs___c_extended_progress.html',1,'Dialog Extended Progress'],['../db/dd0/group__cpp__kodi__gui__dialogs___c_progress.html',1,'Dialog Progress']]],
  ['provider_19',['7. Provider',['../d8/dd3/group__cpp__kodi__addon__pvr___defs___provider.html',1,'']]],
  ['pvr_20',['PVR',['../d6/d05/group__cpp__kodi__addon__pvr.html',1,'']]],
  ['pvr_5fcodec_21',['struct PVR_CODEC',['../d2/de7/group__cpp__kodi__addon__pvr___defs___stream___p_v_r___c_o_d_e_c.html',1,'']]],
  ['pvr_5fcodec_5ftype_22',['enum PVR_CODEC_TYPE',['../da/db8/group__cpp__kodi__addon__pvr___defs___stream___p_v_r___c_o_d_e_c___t_y_p_e.html',1,'']]],
  ['pvr_5fconnection_5fstate_23',['enum PVR_CONNECTION_STATE',['../d5/d60/group__cpp__kodi__addon__pvr___defs___general___p_v_r___c_o_n_n_e_c_t_i_o_n___s_t_a_t_e.html',1,'']]],
  ['pvr_5fedl_5ftype_24',['enum PVR_EDL_TYPE',['../d2/de2/group__cpp__kodi__addon__pvr___defs___e_d_l_entry___p_v_r___e_d_l___t_y_p_e.html',1,'']]],
  ['pvr_5ferror_25',['enum PVR_ERROR',['../d0/d9d/group__cpp__kodi__addon__pvr___defs___general___p_v_r___e_r_r_o_r.html',1,'']]],
  ['pvr_5fmenuhook_5fcat_26',['enum PVR_MENUHOOK_CAT',['../d5/d59/group__cpp__kodi__addon__pvr___defs___menuhook___p_v_r___m_e_n_u_h_o_o_k___c_a_t.html',1,'']]],
  ['pvr_5fprovider_5ftype_27',['enum PVR_PROVIDER_TYPE',['../d4/d14/group__cpp__kodi__addon__pvr___defs___channel___p_v_r___p_r_o_v_i_d_e_r___t_y_p_e.html',1,'']]],
  ['pvr_5frecording_5fchannel_5ftype_28',['enum PVR_RECORDING_CHANNEL_TYPE',['../d3/df2/group__cpp__kodi__addon__pvr___defs___recording___p_v_r___r_e_c_o_r_d_i_n_g___c_h_a_n_n_e_l___t_y_p_e.html',1,'']]],
  ['pvr_5frecording_5fflag_29',['enum PVR_RECORDING_FLAG',['../dc/d2c/group__cpp__kodi__addon__pvr___defs___recording___p_v_r___r_e_c_o_r_d_i_n_g___f_l_a_g.html',1,'']]],
  ['pvr_5fsetting_5freadonly_5fcondition_30',['enum PVR_SETTING_READONLY_CONDITION',['../d7/df8/group__cpp__kodi__addon__pvr___defs___general___p_v_r___s_e_t_t_i_n_g___r_e_a_d_o_n_l_y___c_o_n_d_i_t_i_o_n.html',1,'']]],
  ['pvr_5fsetting_5ftype_31',['enum PVR_SETTING_TYPE',['../de/d73/group__cpp__kodi__addon__pvr___defs___general___p_v_r___s_e_t_t_i_n_g___t_y_p_e.html',1,'']]],
  ['pvr_5fsource_32',['enum PVR_SOURCE',['../d2/d09/group__cpp__kodi__addon__pvr___defs___general___p_v_r___s_o_u_r_c_e.html',1,'']]],
  ['pvr_5fstream_5fproperty_33',['pvr_stream_property',['../db/de7/group__cpp__kodi__addon__pvr___defs___general___inputstream.html',1,'class PVRStreamProperty &amp; definition PVR_STREAM_PROPERTY'],['../dc/de0/group__cpp__kodi__addon__pvr___defs___general___p_v_r___s_t_r_e_a_m___p_r_o_p_e_r_t_y.html',1,'definition PVR_STREAM_PROPERTY']]],
  ['pvr_5ftimer_20various_34',['definition PVR_TIMER (various)',['../d6/df2/group__cpp__kodi__addon__pvr___defs___timer___p_v_r___t_i_m_e_r__.html',1,'']]],
  ['pvr_5ftimer_5fstate_35',['enum PVR_TIMER_STATE',['../d0/d49/group__cpp__kodi__addon__pvr___defs___timer___p_v_r___t_i_m_e_r___s_t_a_t_e.html',1,'']]],
  ['pvr_5ftimer_5ftypes_36',['enum PVR_TIMER_TYPES',['../d6/d3e/group__cpp__kodi__addon__pvr___defs___timer___p_v_r___t_i_m_e_r___t_y_p_e_s.html',1,'']]],
  ['pvr_5fweekday_37',['enum PVR_WEEKDAY',['../d1/dcd/group__cpp__kodi__addon__pvr___defs___timer___p_v_r___w_e_e_k_d_a_y.html',1,'']]],
  ['pvrcapabilities_38',['class PVRCapabilities',['../d3/df7/group__cpp__kodi__addon__pvr___defs___p_v_r_capabilities.html',1,'']]],
  ['pvrchannel_39',['class PVRChannel',['../df/d03/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_channel.html',1,'']]],
  ['pvrchannelgroup_40',['class PVRChannelGroup',['../d3/dec/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group.html',1,'']]],
  ['pvrchannelgroupmember_41',['class PVRChannelGroupMember',['../de/da7/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group_member.html',1,'']]],
  ['pvrchannelgroupmembersresultset_42',['class PVRChannelGroupMembersResultSet',['../d9/d7f/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group_members_result_set.html',1,'']]],
  ['pvrchannelgroupsresultset_43',['class PVRChannelGroupsResultSet',['../d9/d68/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_groups_result_set.html',1,'']]],
  ['pvrchannelsresultset_44',['class PVRChannelsResultSet',['../dc/d71/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_channels_result_set.html',1,'']]],
  ['pvrcodec_45',['class PVRCodec',['../d1/d0c/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_codec.html',1,'']]],
  ['pvrdescrambleinfo_46',['class PVRDescrambleInfo',['../df/d52/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_descramble_info.html',1,'']]],
  ['pvredlentry_47',['class PVREDLEntry',['../d7/d48/group__cpp__kodi__addon__pvr___defs___e_d_l_entry___p_v_r_e_d_l_entry.html',1,'']]],
  ['pvrepgtag_48',['class PVREPGTag',['../d1/dfb/group__cpp__kodi__addon__pvr___defs__epg___p_v_r_e_p_g_tag.html',1,'']]],
  ['pvrepgtagsresultset_49',['class PVREPGTagsResultSet',['../da/d89/group__cpp__kodi__addon__pvr___defs__epg___p_v_r_e_p_g_tags_result_set.html',1,'']]],
  ['pvrintsettingdefinition_50',['class PVRIntSettingDefinition',['../d7/d23/group__cpp__kodi__addon__pvr___defs___p_v_r_int_setting_definition.html',1,'']]],
  ['pvrmenuhook_51',['class PVRMenuhook',['../d5/db8/group__cpp__kodi__addon__pvr___defs___menuhook___p_v_r_menuhook.html',1,'']]],
  ['pvrprovider_52',['class PVRProvider',['../d2/dd9/group__cpp__kodi__addon__pvr___defs___p_v_r_provider.html',1,'']]],
  ['pvrprovidersresultset_53',['class PVRProvidersResultSet',['../d5/d91/group__cpp__kodi__addon__pvr___defs___p_v_r_providers_result_set.html',1,'']]],
  ['pvrrecording_54',['class PVRRecording',['../d5/d9e/group__cpp__kodi__addon__pvr___defs___recording___p_v_r_recording.html',1,'']]],
  ['pvrrecordingsresultset_55',['class PVRRecordingsResultSet',['../d0/dac/group__cpp__kodi__addon__pvr___defs___recording___p_v_r_recordings_result_set.html',1,'']]],
  ['pvrsettingdefinition_56',['class PVRSettingDefinition',['../dc/d36/group__cpp__kodi__addon__pvr___defs___p_v_r_setting_definition.html',1,'']]],
  ['pvrsettingkeyvaluepair_57',['class PVRSettingKeyValuePair',['../d9/dcb/group__cpp__kodi__addon__pvr___defs___general___p_v_r_setting_key_value_pair.html',1,'']]],
  ['pvrsignalstatus_58',['class PVRSignalStatus',['../d8/dd4/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_signal_status.html',1,'']]],
  ['pvrstreamproperties_59',['class PVRStreamProperties',['../dc/d27/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_properties.html',1,'']]],
  ['pvrstreamproperty_60',['class PVRStreamProperty',['../d8/d5c/group__cpp__kodi__addon__pvr___defs___general___inputstream___p_v_r_stream_property.html',1,'']]],
  ['pvrstreamproperty_20definition_20pvr_5fstream_5fproperty_61',['class PVRStreamProperty &amp; definition PVR_STREAM_PROPERTY',['../db/de7/group__cpp__kodi__addon__pvr___defs___general___inputstream.html',1,'']]],
  ['pvrstreamtimes_62',['class PVRStreamTimes',['../de/d74/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_times.html',1,'']]],
  ['pvrstringsettingdefinition_63',['class PVRStringSettingDefinition',['../d0/d73/group__cpp__kodi__addon__pvr___defs___p_v_r_string_setting_definition.html',1,'']]],
  ['pvrtimer_64',['class PVRTimer',['../dd/dd8/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer.html',1,'']]],
  ['pvrtimersresultset_65',['class PVRTimersResultSet',['../d8/d1b/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timers_result_set.html',1,'']]],
  ['pvrtimertype_66',['class PVRTimerType',['../d4/dd4/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer_type.html',1,'']]],
  ['pvrtypeintvalue_67',['class PVRTypeIntValue',['../d8/d9f/group__cpp__kodi__addon__pvr___defs___p_v_r_type_int_value.html',1,'']]],
  ['pvrtypestringvalue_68',['class PVRTypeStringValue',['../d4/dbe/group__cpp__kodi__addon__pvr___defs___p_v_r_type_string_value.html',1,'']]],
  ['python_69',['Python',['../de/d69/group__python.html',1,'']]]
];
