var searchData=
[
  ['s_0',['Action Id&apos;s',['../d9/d2e/group__kodi__key__action__ids.html',1,'']]],
  ['s_20controller_1',['5. Mapping driver elements to the system&apos;s controller',['../da/da9/group__cpp__kodi__addon__peripheral___docs___lifetime___driver_elements.html',1,'']]],
  ['s_20retropad_2',['6. Translating Kodi controller to libretro&apos;s &quot;RetroPad&quot;',['../db/d99/group__cpp__kodi__addon__peripheral___docs___lifetime___translating.html',1,'']]],
  ['scanning_20for_20peripherals_3',['1. Scanning for peripherals',['../da/deb/group__cpp__kodi__addon__peripheral___docs___lifetime___scanning.html',1,'']]],
  ['screen_4',['Graphics and Screen',['../d6/de0/group__graphics.html',1,'']]],
  ['screensaver_5',['Screensaver',['../de/da5/group__cpp__kodi__addon__screensaver.html',1,'']]],
  ['search_6',['String search',['../d0/d56/group__cpp__kodi__tools___string_utils___search_control.html',1,'']]],
  ['select_7',['Dialog Select',['../d6/da0/group__cpp__kodi__gui__dialogs___select.html',1,'']]],
  ['serialization_20operations_8',['5. Serialization operations',['../de/d37/group__cpp__kodi__addon__game___serialization_operations.html',1,'']]],
  ['setting_20control_9',['1. Setting control',['../de/dca/group__cpp__kodi__settings.html',1,'']]],
  ['settings_10',['settings',['../d0/de9/group__settings.html',1,'Settings'],['../de/d04/group__python__settings.html',1,'Settings']]],
  ['settings_20slider_11',['Control Settings Slider',['../d1/dd9/group__cpp__kodi__gui__windows__controls___c_settings_slider.html',1,'']]],
  ['shader_20program_12',['GL Shader Program',['../db/d9a/group__cpp__kodi__gui__helpers__gl___c_shader_program.html',1,'']]],
  ['slider_13',['slider',['../d1/dd9/group__cpp__kodi__gui__windows__controls___c_settings_slider.html',1,'Control Settings Slider'],['../d9/d7f/group__cpp__kodi__gui__windows__controls___c_slider.html',1,'Control Slider']]],
  ['software_20framebuffer_20stream_14',['4. Software framebuffer stream',['../d8/da5/group__cpp__kodi__addon__game___defs___software_framebuffer.html',1,'']]],
  ['sort_20methods_15',['List of sort methods',['../d1/d7e/group___list__of__sort__methods.html',1,'']]],
  ['spin_16',['Control Spin',['../de/db4/group__cpp__kodi__gui__windows__controls___c_spin.html',1,'']]],
  ['stat_17',['Stat',['../df/d61/group__python__stat.html',1,'']]],
  ['stream_18',['stream',['../d3/d4a/group__cpp__kodi__addon__game___defs___audio_stream.html',1,'1. Audio stream'],['../d1/dc2/group__cpp__kodi__addon__game___defs___video_stream.html',1,'2. Video stream'],['../d8/d8d/group__cpp__kodi__addon__game___defs___hardware_framebuffer.html',1,'3. Hardware framebuffer stream'],['../d8/da5/group__cpp__kodi__addon__game___defs___software_framebuffer.html',1,'4. Software framebuffer stream'],['../d9/deb/group__cpp__kodi__addon__pvr___streams___t_v.html',1,'8.1. TV stream'],['../dd/dc3/group__cpp__kodi__addon__pvr___streams___recording.html',1,'8.2. Recording stream']]],
  ['stream_20codec_19',['4. Stream codec',['../d8/dbe/group__cpp__kodi__addon__inputstream___defs___stream_codec.html',1,'']]],
  ['stream_20constants_20',['2. Stream constants',['../da/d7f/group__cpp__kodi__addon__inputstream___defs___stream_constants.html',1,'']]],
  ['stream_20demuxing_21',['8.1.1. Stream demuxing',['../d6/d00/group__cpp__kodi__addon__pvr___streams___t_v___demux.html',1,'']]],
  ['stream_20demuxing_20optional_22',['2. Stream demuxing (optional)',['../da/d1b/group__cpp__kodi__addon__inputstream___demux.html',1,'']]],
  ['stream_20encryption_23',['5. Stream encryption',['../d4/d6e/group__cpp__kodi__addon__inputstream___defs___stream_encryption.html',1,'']]],
  ['stream_20read_24',['1. Stream read',['../d8/d35/group__cpp__kodi__addon__inputstream___read.html',1,'']]],
  ['stream_20timing_25',['3. Stream timing',['../dd/da5/group__cpp__kodi__addon__inputstream___defs___timing_constants.html',1,'']]],
  ['stream_20types_26',['5. Stream types',['../d2/de0/group__cpp__kodi__addon__game___defs___stream_types.html',1,'']]],
  ['stream_5fcrypto_5fflags_27',['enum STREAM_CRYPTO_FLAGS',['../d8/db5/group__cpp__kodi__addon__inputstream___defs___stream_encryption___s_t_r_e_a_m___c_r_y_p_t_o___f_l_a_g_s.html',1,'']]],
  ['stream_5fcrypto_5fkey_5fsystem_28',['enum STREAM_CRYPTO_KEY_SYSTEM',['../d9/d3f/group__cpp__kodi__addon__inputstream___defs___stream_encryption___s_t_r_e_a_m___c_r_y_p_t_o___k_e_y___s_y_s_t_e_m.html',1,'']]],
  ['streamcodec_5fprofile_29',['enum STREAMCODEC_PROFILE',['../dd/d86/group__cpp__kodi__addon__inputstream___defs___stream_encryption___s_t_r_e_a_m_c_o_d_e_c___p_r_o_f_i_l_e.html',1,'']]],
  ['streamcryptosession_30',['class StreamCryptoSession',['../dd/dba/group__cpp__kodi__addon__inputstream___defs___stream_encryption___stream_crypto_session.html',1,'']]],
  ['string_20compare_31',['String compare',['../d4/d27/group__cpp__kodi__tools___string_utils___compare_control.html',1,'']]],
  ['string_20edit_32',['String edit',['../d2/dca/group__cpp__kodi__tools___string_utils___edit_control.html',1,'']]],
  ['string_20format_33',['String format',['../d9/d0b/group__cpp__kodi__tools___string_utils___format_control.html',1,'']]],
  ['string_20list_34',['String list',['../d6/d84/group__cpp__kodi__tools___string_utils___list_control.html',1,'']]],
  ['string_20search_35',['String search',['../d0/d56/group__cpp__kodi__tools___string_utils___search_control.html',1,'']]],
  ['strings_20and_20localization_36',['Strings and Localization',['../d7/d0c/group__strings.html',1,'']]],
  ['stringutils_37',['class StringUtils',['../df/d5a/group__cpp__kodi__tools___string_utils.html',1,'']]],
  ['struct_20demux_5fcrypto_5finfo_38',['struct DEMUX_CRYPTO_INFO',['../db/d45/group__cpp__kodi__addon__inputstream___defs___stream_encryption___d_e_m_u_x___c_r_y_p_t_o___i_n_f_o.html',1,'']]],
  ['struct_20demux_5fpacket_39',['struct DEMUX_PACKET',['../d2/ddf/group__cpp__kodi__addon__inputstream___defs___interface___d_e_m_u_x___p_a_c_k_e_t.html',1,'']]],
  ['struct_20pvr_5fcodec_40',['struct PVR_CODEC',['../d2/de7/group__cpp__kodi__addon__pvr___defs___stream___p_v_r___c_o_d_e_c.html',1,'']]],
  ['struct_20videocodec_5fpicture_41',['struct VIDEOCODEC_PICTURE',['../dc/d29/group__cpp__kodi__addon__videocodec___defs___v_i_d_e_o_c_o_d_e_c___p_i_c_t_u_r_e.html',1,'']]],
  ['structure_42',['CMake addon creation structure',['../d0/dbc/group__cpp__cmake.html',1,'']]],
  ['structures_20and_20enumerators_43',['structures and enumerators',['../dc/db9/group__cpp__kodi__tools___string_utils___defs.html',1,'Definitions, structures and enumerators'],['../d7/dd1/group__cpp__kodi__gui__windows__window___defs.html',1,'Definitions, structures and enumerators'],['../de/dac/group__cpp__kodi___defs.html',1,'Definitions, structures and enumerators'],['../dd/d40/group__cpp__kodi__gui__windows__controls___c_edit___defs.html',1,'Definitions, structures and enumerators'],['../d9/d97/group__cpp__kodi__addon__addonbase___defs.html',1,'Definitions, structures and enumerators'],['../d2/d35/group__cpp__kodi__gui___defs.html',1,'Definitions, structures and enumerators'],['../d2/d7e/group__cpp__kodi__addon__audiodecoder___defs.html',1,'Definitions, structures and enumerators'],['../d4/d94/group__cpp__kodi__addon__game___defs.html',1,'Definitions, structures and enumerators'],['../da/dd1/group__cpp__kodi__addon__imagedecoder___defs.html',1,'Definitions, structures and enumerators'],['../dc/d46/group__cpp__kodi__addon__inputstream___defs.html',1,'Definitions, structures and enumerators'],['../db/d89/group__cpp__kodi__addon__peripheral___defs.html',1,'Definitions, structures and enumerators'],['../d2/d15/group__cpp__kodi__addon__vfs___defs.html',1,'Definitions, structures and enumerators'],['../dc/d99/group__cpp__kodi__gui__dialogs___select___defs.html',1,'Definitions, structures and enumerators'],['../d0/da1/group__cpp__kodi__vfs___defs.html',1,'Definitions, structures and enumerators'],['../d1/d5f/group__cpp__kodi__audioengine___defs.html',1,'Definitions, structures and enumerators'],['../d6/d5f/group__cpp__kodi__addon__pvr___defs.html',1,'Definitions, structures and enumerators'],['../d6/dac/group__cpp__kodi__addon__videocodec___defs.html',1,'Definitions, structures and enumerators'],['../df/d16/group__cpp__kodi__addon__visualization___defs.html',1,'Definitions, structures and enumerators']]],
  ['sub_20types_44',['enum EPG_EVENT_CONTENTMASK (and sub types)',['../d9/d93/group__cpp__kodi__addon__pvr___defs__epg___e_p_g___e_v_e_n_t.html',1,'']]],
  ['subclass_20controlbutton_45',['Subclass - ControlButton',['../dc/d18/group__python__xbmcgui__control__button.html',1,'']]],
  ['subclass_20controledit_46',['Subclass - ControlEdit',['../d4/d8b/group__python__xbmcgui__control__edit.html',1,'']]],
  ['subclass_20controlfadelabel_47',['Subclass - ControlFadeLabel',['../dc/d41/group__python__xbmcgui__control__fadelabel.html',1,'']]],
  ['subclass_20controlgroup_48',['Subclass - ControlGroup',['../da/d1f/group__python__xbmcgui__control__group.html',1,'']]],
  ['subclass_20controlimage_49',['Subclass - ControlImage',['../d5/dec/group__python__xbmcgui__control__image.html',1,'']]],
  ['subclass_20controllabel_50',['Subclass - ControlLabel',['../d4/dd9/group__python__xbmcgui__control__label.html',1,'']]],
  ['subclass_20controllist_51',['Subclass - ControlList',['../da/d30/group__python__xbmcgui__control__list.html',1,'']]],
  ['subclass_20controlprogress_52',['Subclass - ControlProgress',['../d4/d4a/group__python__xbmcgui__control__progress.html',1,'']]],
  ['subclass_20controlradiobutton_53',['Subclass - ControlRadioButton',['../d7/d8e/group__python__xbmcgui__control__radiobutton.html',1,'']]],
  ['subclass_20controlslider_54',['Subclass - ControlSlider',['../d0/d9c/group__python__xbmcgui__control__slider.html',1,'']]],
  ['subclass_20controlspin_55',['Subclass - ControlSpin',['../dd/d02/group__python__xbmcgui__control__spin.html',1,'']]],
  ['subclass_20controltextbox_56',['Subclass - ControlTextBox',['../da/df5/group__python__xbmcgui__control__textbox.html',1,'']]],
  ['subclass_20windowdialog_57',['Subclass - WindowDialog',['../d5/d05/group__python__xbmcgui__window__dialog.html',1,'']]],
  ['subclass_20windowdialogxml_58',['Subclass - WindowDialogXML',['../d5/dc9/group__python__xbmcgui__window__dialog__xml.html',1,'']]],
  ['subclass_20windowxml_59',['Subclass - WindowXML',['../dd/d4d/group__python__xbmcgui__window__xml.html',1,'']]],
  ['subtitlestreamdetail_60',['SubtitleStreamDetail',['../d0/dd4/group__python__xbmc__subtitlestreamdetail.html',1,'']]],
  ['system_61',['Peripheral system',['../d6/dde/group__cpp__kodi__addon__peripheral___docs.html',1,'']]],
  ['system_20s_20controller_62',['5. Mapping driver elements to the system&apos;s controller',['../da/da9/group__cpp__kodi__addon__peripheral___docs___lifetime___driver_elements.html',1,'']]]
];
