Kodi Documentation: KODI::JOYSTICK::CAxisDetector Class Reference
KODI::JOYSTICK::CAxisDetector Class Reference
Input » Joystick
Detects when an axis should be mapped.
#include <ButtonMapping.h>
Public Member Functions
CAxisDetector (CButtonMapping *buttonMapping, unsigned int axisIndex, const AxisConfiguration &config)
bool OnMotion (float position)
Axis state has been updated.
void ProcessMotion ()
Called once per frame.
bool IsMapping () const
Check if the axis was mapped and is still in motion.
void SetEmitted (const CDriverPrimitive &activePrimitive)
Set the state such that this axis has generated a mapping event.
Private Types
enum class AXIS_STATE { INACTIVE , ACTIVATED , MAPPED }
enum class AXIS_TYPE { UNKNOWN , NORMAL , OFFSET }
Private Member Functions
void DetectType (float position)
Private Attributes
const unsigned int m_axisIndex
AxisConfiguration m_config
AXIS_STATE m_state = AXIS_STATE::INACTIVE
CDriverPrimitive m_activatedPrimitive
AXIS_TYPE m_type = AXIS_TYPE::UNKNOWN
bool m_initialPositionKnown = false
float m_initialPosition = 0.0f
bool m_initialPositionChanged
std::chrono::time_point< std::chrono::steady_clock > m_activationTimeMs
Additional Inherited Members
Protected Member Functions inherited from KODI::JOYSTICK::CPrimitiveDetector
CPrimitiveDetector (CButtonMapping *buttonMapping)
bool MapPrimitive (const CDriverPrimitive &primitive)
Dispatch a mapping event.
Detailed Description
Detects when an axis should be mapped.
Member Enumeration Documentation
AXIS_STATE
enum class KODI::JOYSTICK::CAxisDetector::AXIS_STATE strong private
Enumerator
INACTIVE
Axis is inactive (position is less than threshold)
ACTIVATED
Axis is activated (position has exceeded threshold)
MAPPED
Axis has generated a mapping event, but has not been centered yet.
AXIS_TYPE
enum class KODI::JOYSTICK::CAxisDetector::AXIS_TYPE strong private
Enumerator
UNKNOWN
Axis type is initially unknown.
NORMAL
Axis is centered about 0.
If the axis is an analog stick, it can travel to -1 or +1.
If the axis is a pressure-sensitive button or a normal trigger, it can travel to +1.
If the axis is a DirectInput trigger, then it is possible that two triggers can be on the same axis in opposite directions.
Normally, D-pads appear as a hat or four buttons. However, some D-pads are reported as two axes that can have the discrete values -1, 0 or 1. This is called a "discrete D-pad".
OFFSET
Axis is centered about -1 or 1.
On OSX, with the cocoa driver, triggers are centered about -1 and travel to +1. In this case, the range is 2 and the direction is positive.
The author of SDL has observed triggers centered at +1 and travel to 0. In this case, the range is 1 and the direction is negative.
Constructor & Destructor Documentation
CAxisDetector()
CAxisDetector::CAxisDetector (CButtonMapping * buttonMapping, unsigned int axisIndex, const AxisConfiguration & config)
Member Function Documentation
DetectType()
void CAxisDetector::DetectType (float position) private
References KODI::JOYSTICK::AxisConfiguration::bKnown, KODI::JOYSTICK::AxisConfiguration::bLateDiscovery, KODI::JOYSTICK::AxisConfiguration::center, CLog::Log(), LOGDEBUG, m_axisIndex, m_config, m_initialPosition, m_initialPositionChanged, m_initialPositionKnown, m_type, NORMAL, OFFSET, KODI::JOYSTICK::AxisConfiguration::range, and UNKNOWN.
Referenced by OnMotion().
IsMapping()
bool KODI::JOYSTICK::CAxisDetector::IsMapping () const inline
Check if the axis was mapped and is still in motion.
Returns
True between when the axis is mapped and when it crosses zero
References m_state, and MAPPED.
OnMotion()
bool CAxisDetector::OnMotion (float position)
Axis state has been updated.
Parameters
position The new state
Returns
Always true - axis motion events are always absorbed while button mapping
References ACTIVATED, AXIS_THRESHOLD, KODI::JOYSTICK::AxisConfiguration::center, DetectType(), INACTIVE, m_activatedPrimitive, m_activationTimeMs, m_axisIndex, m_config, m_state, m_type, MAPPED, OFFSET, KODI::JOYSTICK::CJoystickTranslator::PositionToSemiAxisDirection(), KODI::JOYSTICK::AxisConfiguration::range, KODI::JOYSTICK::CDriverPrimitive::SemiAxisDirection(), and UNKNOWN.
Referenced by KODI::JOYSTICK::CButtonMapping::OnAxisMotion().
ProcessMotion()
void CAxisDetector::ProcessMotion ()
Called once per frame.
If an axis was activated, the button mapping command will be emitted here.
References ACTIVATED, KODI::JOYSTICK::CDriverPrimitive::Center(), KODI::JOYSTICK::CDriverPrimitive::Index(), CLog::Log(), LOGDEBUG, m_activatedPrimitive, m_activationTimeMs, m_axisIndex, m_config, m_state, m_type, MAPPED, KODI::JOYSTICK::CPrimitiveDetector::MapPrimitive(), OFFSET, KODI::JOYSTICK::AxisConfiguration::range, KODI::JOYSTICK::CDriverPrimitive::SemiAxisDirection(), and TRIGGER_DELAY_MS.
SetEmitted()
void CAxisDetector::SetEmitted (const CDriverPrimitive & activePrimitive)
Set the state such that this axis has generated a mapping event.
If an axis is mapped to the Select action, it may be pressed when button mapping begins. This function is used to indicate that the axis shouldn't be mapped until after it crosses zero again.
References m_activatedPrimitive, m_state, and MAPPED.
Referenced by KODI::JOYSTICK::CButtonMapping::CButtonMapping().
Member Data Documentation
m_activatedPrimitive
CDriverPrimitive KODI::JOYSTICK::CAxisDetector::m_activatedPrimitive private
Referenced by OnMotion(), ProcessMotion(), and SetEmitted().
m_activationTimeMs
std::chrono::time_point<std::chrono::steady_clock> KODI::JOYSTICK::CAxisDetector::m_activationTimeMs private
Referenced by OnMotion(), and ProcessMotion().
m_axisIndex
const unsigned int KODI::JOYSTICK::CAxisDetector::m_axisIndex private
Referenced by DetectType(), OnMotion(), and ProcessMotion().
m_config
AxisConfiguration KODI::JOYSTICK::CAxisDetector::m_config private
Referenced by DetectType(), OnMotion(), and ProcessMotion().
m_initialPosition
float KODI::JOYSTICK::CAxisDetector::m_initialPosition = 0.0f private
Referenced by DetectType().
m_initialPositionChanged
bool KODI::JOYSTICK::CAxisDetector::m_initialPositionChanged private
Initial value:
=
      false
Referenced by DetectType().
m_initialPositionKnown
bool KODI::JOYSTICK::CAxisDetector::m_initialPositionKnown = false private
Referenced by DetectType().
m_state
AXIS_STATE KODI::JOYSTICK::CAxisDetector::m_state = AXIS_STATE::INACTIVE private
Referenced by IsMapping(), OnMotion(), ProcessMotion(), and SetEmitted().
m_type
AXIS_TYPE KODI::JOYSTICK::CAxisDetector::m_type = AXIS_TYPE::UNKNOWN private
Referenced by DetectType(), OnMotion(), and ProcessMotion().
The documentation for this class was generated from the following files:
ButtonMapping.h
ButtonMapping.cpp