Kodi Documentation: KODI::RETRO::CBaseRenderBufferPool Class Reference
KODI::RETRO::CBaseRenderBufferPool Class Reference abstract
#include <BaseRenderBufferPool.h>
Public Member Functions
CBaseRenderBufferPool ()=default
~CBaseRenderBufferPool () override
void RegisterRenderer (CRPBaseRenderer *renderer) override
void UnregisterRenderer (CRPBaseRenderer *renderer) override
bool HasVisibleRenderer () const override
bool Configure (AVPixelFormat format) override
bool IsConfigured () const override
IRenderBuffer * GetBuffer (unsigned int width, unsigned int height) override
Get a free buffer from the pool, sets ref count to 1.
void Return (IRenderBuffer *buffer) override
Called by buffer when ref count goes to zero.
void Prime (unsigned int width, unsigned int height) override
void Flush () override
AVPixelFormat Format () const
Public Member Functions inherited from KODI::RETRO::IRenderBufferPool
virtual ~IRenderBufferPool ()=default
virtual bool IsCompatible (const CRenderVideoSettings &renderSettings) const =0
virtual DataAccess GetMemoryAccess () const
virtual DataAlignment GetMemoryAlignment () const
virtual std::shared_ptr< IRenderBufferPool > GetPtr ()
Call in GetBuffer() before returning buffer to caller.
Protected Member Functions
virtual IRenderBuffer * CreateRenderBuffer (void *header=nullptr)=0
virtual bool ConfigureInternal ()
virtual void * GetHeader (unsigned int timeoutMs=0)
virtual bool GetHeaderWithTimeout (void *&header)
virtual bool SendBuffer (IRenderBuffer *buffer)
Protected Attributes
bool m_bConfigured = false
AVPixelFormat m_format = AV_PIX_FMT_NONE
Private Attributes
std::deque< std::unique_ptr< IRenderBuffer > > m_free
std::vector< CRPBaseRenderer * > m_renderers
CCriticalSection m_rendererMutex
CCriticalSection m_bufferMutex
Constructor & Destructor Documentation
CBaseRenderBufferPool()
KODI::RETRO::CBaseRenderBufferPool::CBaseRenderBufferPool () default
~CBaseRenderBufferPool()
CBaseRenderBufferPool::~CBaseRenderBufferPool () override
References Flush().
Member Function Documentation
Configure()
bool CBaseRenderBufferPool::Configure (AVPixelFormat format) override virtual
Implements KODI::RETRO::IRenderBufferPool.
References ConfigureInternal(), m_bConfigured, and m_format.
ConfigureInternal()
virtual bool KODI::RETRO::CBaseRenderBufferPool::ConfigureInternal () inline protected virtual
Reimplemented in KODI::RETRO::CRenderBufferPoolDMA, KODI::RETRO::CRenderBufferPoolOpenGL, and KODI::RETRO::CRenderBufferPoolOpenGLES.
Referenced by Configure().
CreateRenderBuffer()
virtual IRenderBuffer * KODI::RETRO::CBaseRenderBufferPool::CreateRenderBuffer (void * header = nullptr) protected pure virtual
Implemented in KODI::RETRO::CRenderBufferPoolDMA, KODI::RETRO::CRenderBufferPoolOpenGL, KODI::RETRO::CRenderBufferPoolOpenGLES, KODI::RETRO::CRenderBufferPoolGuiTexture, and KODI::RETRO::CWinRenderBufferPool.
Referenced by GetBuffer().
Flush()
void CBaseRenderBufferPool::Flush () override virtual
Implements KODI::RETRO::IRenderBufferPool.
References m_bConfigured, m_bufferMutex, and m_free.
Referenced by ~CBaseRenderBufferPool().
Format()
AVPixelFormat KODI::RETRO::CBaseRenderBufferPool::Format () const inline
References m_format.
GetBuffer()
IRenderBuffer * CBaseRenderBufferPool::GetBuffer (unsigned int width, unsigned int height) override virtual
Get a free buffer from the pool, sets ref count to 1.
Parameters
width The horizontal pixel count of the buffer
height The vertical pixel could of the buffer
Returns
The allocated buffer, or nullptr on failure
Implements KODI::RETRO::IRenderBufferPool.
References KODI::RETRO::IRenderBuffer::Acquire(), CreateRenderBuffer(), GetHeaderWithTimeout(), KODI::RETRO::IRenderBufferPool::GetPtr(), CLog::Log(), LOGDEBUG, LOGERROR, m_bConfigured, m_bufferMutex, m_format, m_free, KODI::RETRO::IRenderBuffer::SetHeader(), and KODI::RETRO::IRenderBuffer::Update().
Referenced by Prime().
GetHeader()
virtual void * KODI::RETRO::CBaseRenderBufferPool::GetHeader (unsigned int timeoutMs = 0) inline protected virtual
GetHeaderWithTimeout()
virtual bool KODI::RETRO::CBaseRenderBufferPool::GetHeaderWithTimeout (void *& header) inline protected virtual
Referenced by GetBuffer().
HasVisibleRenderer()
bool CBaseRenderBufferPool::HasVisibleRenderer () const override virtual
Implements KODI::RETRO::IRenderBufferPool.
References m_rendererMutex, and m_renderers.
IsConfigured()
bool KODI::RETRO::CBaseRenderBufferPool::IsConfigured () const inline override virtual
Implements KODI::RETRO::IRenderBufferPool.
References m_bConfigured.
Prime()
void CBaseRenderBufferPool::Prime (unsigned int width, unsigned int height) override virtual
Implements KODI::RETRO::IRenderBufferPool.
References GetBuffer(), m_bufferMutex, and SendBuffer().
RegisterRenderer()
void CBaseRenderBufferPool::RegisterRenderer (CRPBaseRenderer * renderer) override virtual
Implements KODI::RETRO::IRenderBufferPool.
References m_rendererMutex, and m_renderers.
Return()
void CBaseRenderBufferPool::Return (IRenderBuffer * buffer) override virtual
Called by buffer when ref count goes to zero.
Parameters
buffer A fully dereferenced buffer
Implements KODI::RETRO::IRenderBufferPool.
References m_bufferMutex, and m_free.
SendBuffer()
virtual bool KODI::RETRO::CBaseRenderBufferPool::SendBuffer (IRenderBuffer * buffer) inline protected virtual
Referenced by Prime().
UnregisterRenderer()
void CBaseRenderBufferPool::UnregisterRenderer (CRPBaseRenderer * renderer) override virtual
Implements KODI::RETRO::IRenderBufferPool.
References m_rendererMutex, and m_renderers.
Member Data Documentation
m_bConfigured
bool KODI::RETRO::CBaseRenderBufferPool::m_bConfigured = false protected
Referenced by Configure(), Flush(), GetBuffer(), and IsConfigured().
m_bufferMutex
CCriticalSection KODI::RETRO::CBaseRenderBufferPool::m_bufferMutex private
Referenced by Flush(), GetBuffer(), Prime(), and Return().
m_format
AVPixelFormat KODI::RETRO::CBaseRenderBufferPool::m_format = AV_PIX_FMT_NONE protected
Referenced by Configure(), KODI::RETRO::CRenderBufferPoolDMA::ConfigureInternal(), KODI::RETRO::CRenderBufferPoolOpenGL::ConfigureInternal(), KODI::RETRO::CRenderBufferPoolOpenGLES::ConfigureInternal(), KODI::RETRO::CWinRenderBufferPool::CreateRenderBuffer(), Format(), and GetBuffer().
m_free
std::deque<std::unique_ptr<IRenderBuffer> > KODI::RETRO::CBaseRenderBufferPool::m_free private
Referenced by Flush(), GetBuffer(), and Return().
m_rendererMutex
CCriticalSection KODI::RETRO::CBaseRenderBufferPool::m_rendererMutex mutable private
Referenced by HasVisibleRenderer(), RegisterRenderer(), and UnregisterRenderer().
m_renderers
std::vector<CRPBaseRenderer*> KODI::RETRO::CBaseRenderBufferPool::m_renderers private
Referenced by HasVisibleRenderer(), RegisterRenderer(), and UnregisterRenderer().
The documentation for this class was generated from the following files:
BaseRenderBufferPool.h
BaseRenderBufferPool.cpp