Kodi Documentation: CFavouritesURL Class Reference
CFavouritesURL Class Reference
#include <FavouritesURL.h>
Public Types
enum class Action {
UNKNOWN , ACTIVATE_WINDOW , PLAY_MEDIA , SHOW_PICTURE ,
RUN_SCRIPT , RUN_ADDON , START_ANDROID_ACTIVITY
}
Public Member Functions
CFavouritesURL (const std::string &favouritesURL)
CFavouritesURL (const CExecString &execString)
CFavouritesURL (Action action, const std::vector< std::string > &params)
CFavouritesURL (const CFileItem &item, int contextWindow)
virtual ~CFavouritesURL ()=default
const std::string & GetURL () const
bool IsValid () const
bool IsDir () const
std::string GetExecString () const
Action GetAction () const
std::vector< std::string > GetParams () const
const std::string & GetTarget () const
int GetWindowID () const
const std::string & GetActionLabel () const
const std::string & GetProviderLabel () const
Private Member Functions
bool Parse (CFavouritesURL::Action action, const std::vector< std::string > &params)
Private Attributes
CExecString m_exec
bool m_valid {false}
std::string m_path
Action m_action {Action::UNKNOWN}
std::string m_target
int m_windowId {-1}
bool m_isDir {false}
std::string m_actionLabel
std::string m_providerLabel
Member Enumeration Documentation
Action
enum class CFavouritesURL::Action strong
Enumerator
UNKNOWN
ACTIVATE_WINDOW
PLAY_MEDIA
SHOW_PICTURE
RUN_SCRIPT
RUN_ADDON
START_ANDROID_ACTIVITY
Constructor & Destructor Documentation
CFavouritesURL() [1/4]
CFavouritesURL::CFavouritesURL (const std::string & favouritesURL) explicit
References CExecString::GetFunction(), CURL::GetHostName(), CExecString::GetParams(), CURL::GetProtocol(), CExecString::IsValid(), LOGERROR, m_exec, m_valid, and Parse().
CFavouritesURL() [2/4]
CFavouritesURL::CFavouritesURL (const CExecString & execString) explicit
References CExecString::GetFunction(), CExecString::GetParams(), CExecString::IsValid(), m_exec, m_valid, and Parse().
CFavouritesURL() [3/4]
CFavouritesURL::CFavouritesURL (Action action, const std::vector< std::string > & params)
References CExecString::IsValid(), m_exec, m_valid, and Parse().
CFavouritesURL() [4/4]
CFavouritesURL::CFavouritesURL (const CFileItem & item, int contextWindow)
References CExecString::GetFunction(), CExecString::GetParams(), CExecString::IsValid(), m_exec, m_valid, and Parse().
~CFavouritesURL()
virtual CFavouritesURL::~CFavouritesURL () virtual default
Member Function Documentation
GetAction()
Action CFavouritesURL::GetAction () const inline
References m_action.
Referenced by JSONRPC::CFavouritesOperations::GetFavourites(), anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked(), and CGUIWindowFavourites::OnSelect().
GetActionLabel()
const std::string & CFavouritesURL::GetActionLabel () const inline
References m_actionLabel.
Referenced by CFavouritesService::GetAll().
GetExecString()
std::string CFavouritesURL::GetExecString () const inline
References CExecString::GetExecString(), and m_exec.
Referenced by FAVOURITES_UTILS::ExecuteAction(), Parse(), and CFavouritesService::Persist().
GetParams()
std::vector< std::string > CFavouritesURL::GetParams () const inline
References CExecString::GetParams(), and m_exec.
GetProviderLabel()
const std::string & CFavouritesURL::GetProviderLabel () const inline
References m_providerLabel.
Referenced by CFavouritesService::GetAll().
GetTarget()
const std::string & CFavouritesURL::GetTarget () const inline
References m_target.
Referenced by JSONRPC::CFavouritesOperations::GetFavourites(), and anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked().
GetURL()
const std::string & CFavouritesURL::GetURL () const inline
References m_path.
Referenced by CFavouritesService::AddOrRemove(), and anonymous_namespace{FavouritesService.cpp}::LoadFromFile().
GetWindowID()
int CFavouritesURL::GetWindowID () const inline
References m_windowId.
Referenced by JSONRPC::CFavouritesOperations::GetFavourites().
IsDir()
bool CFavouritesURL::IsDir () const inline
References m_isDir.
Referenced by anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked().
IsValid()
bool CFavouritesURL::IsValid () const inline
References CExecString::IsValid(), m_exec, and m_valid.
Referenced by FAVOURITES_UTILS::ExecuteAction(), JSONRPC::CFavouritesOperations::GetFavourites(), and anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked().
Parse()
bool CFavouritesURL::Parse (CFavouritesURL::Action action, const std::vector< std::string > & params) private
References ACTIVATE_WINDOW, ADDON::CHOICE_NO, CURL, g_localizeStrings, CLocalizeStrings::Get(), ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), CSysInfo::GetAppName(), GetExecString(), URIUtils::HasSlashAtEnd(), URIUtils::IsPlugin(), LOGERROR, m_action, m_actionLabel, m_isDir, m_path, m_providerLabel, m_target, m_windowId, PLAY_MEDIA, RUN_ADDON, RUN_SCRIPT, SHOW_PICTURE, START_ANDROID_ACTIVITY, CWindowTranslator::TranslateWindow(), and UNKNOWN.
Referenced by CFavouritesURL(), CFavouritesURL(), CFavouritesURL(), and CFavouritesURL().
Member Data Documentation
m_action
Action CFavouritesURL::m_action {Action::UNKNOWN} private
Referenced by GetAction(), and Parse().
m_actionLabel
std::string CFavouritesURL::m_actionLabel private
Referenced by GetActionLabel(), and Parse().
m_exec
CExecString CFavouritesURL::m_exec private
Referenced by CFavouritesURL(), CFavouritesURL(), CFavouritesURL(), CFavouritesURL(), GetExecString(), GetParams(), and IsValid().
m_isDir
bool CFavouritesURL::m_isDir {false} private
Referenced by IsDir(), and Parse().
m_path
std::string CFavouritesURL::m_path private
Referenced by GetURL(), and Parse().
m_providerLabel
std::string CFavouritesURL::m_providerLabel private
Referenced by GetProviderLabel(), and Parse().
m_target
std::string CFavouritesURL::m_target private
Referenced by GetTarget(), and Parse().
m_valid
bool CFavouritesURL::m_valid {false} private
Referenced by CFavouritesURL(), CFavouritesURL(), CFavouritesURL(), CFavouritesURL(), and IsValid().
m_windowId
int CFavouritesURL::m_windowId {-1} private
Referenced by GetWindowID(), and Parse().
The documentation for this class was generated from the following files:
FavouritesURL.h
FavouritesURL.cpp