Kodi Documentation: TestBitstreamStats.cpp File Reference
TestBitstreamStats.cpp File Reference
#include "threads/Thread.h"
#include "utils/BitstreamStats.h"
#include <gtest/gtest.h>
Classes
class CTestBitstreamStatsThread
Macros
#define BITS (256 * 8)
#define BYTES (256)
Functions
TEST (TestBitstreamStats, General)
Macro Definition Documentation
BITS
#define BITS (256 * 8)
BYTES
#define BYTES (256)
Function Documentation
TEST()
TEST (TestBitstreamStats , General)
References BitstreamStats::AddSampleBits(), BitstreamStats::AddSampleBytes(), BITS, BYTES, BitstreamStats::CalculateBitrate(), EXPECT_EQ(), BitstreamStats::GetBitrate(), BitstreamStats::GetMaxBitrate(), BitstreamStats::GetMinBitrate(), BitstreamStats::Start(), and t.