Kodi Documentation: CVideoReferenceClock Class Reference
CVideoReferenceClock Class Reference
#include <VideoReferenceClock.h>
Public Member Functions
CVideoReferenceClock ()
~CVideoReferenceClock () override
int64_t GetTime (bool interpolated=true)
void SetSpeed (double Speed)
double GetSpeed ()
double GetRefreshRate (double *interval=nullptr)
bool GetClockInfo (int &MissedVblanks, double &ClockSpeed, double &RefreshRate) const
void UpdateClock (int NrVBlanks, uint64_t time)
Private Member Functions
void Process () override
void Start ()
void UpdateRefreshrate ()
void UpdateClockInternal (int NrVBlanks, bool CheckMissed)
double UpdateInterval () const
int64_t TimeOfNextVblank () const
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Attributes
int64_t m_CurrTime
int64_t m_LastIntTime
double m_CurrTimeFract
double m_ClockSpeed
int64_t m_SystemFrequency
bool m_UseVblank
double m_RefreshRate
int m_MissedVblanks
int m_TotalMissedVblanks
int64_t m_VblankTime
CEvent m_vsyncStopEvent
CCriticalSection m_CritSection
std::unique_ptr< CVideoSync > m_pVideoSync
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Constructor & Destructor Documentation
CVideoReferenceClock()
CVideoReferenceClock::CVideoReferenceClock ()
References CurrentHostFrequency(), m_ClockSpeed, m_CurrTime, m_CurrTimeFract, m_LastIntTime, m_MissedVblanks, m_RefreshRate, m_SystemFrequency, m_TotalMissedVblanks, m_UseVblank, m_VblankTime, m_vsyncStopEvent, CEvent::Reset(), and Start().
~CVideoReferenceClock()
CVideoReferenceClock::~CVideoReferenceClock () override
References CThread::m_bStop, m_vsyncStopEvent, CEvent::Set(), and CThread::StopThread().
Member Function Documentation
GetClockInfo()
bool CVideoReferenceClock::GetClockInfo (int & MissedVblanks, double & ClockSpeed, double & RefreshRate) const
References m_ClockSpeed, m_CritSection, m_RefreshRate, m_TotalMissedVblanks, and m_UseVblank.
GetRefreshRate()
double CVideoReferenceClock::GetRefreshRate (double * interval = nullptr)
References m_ClockSpeed, m_CritSection, m_RefreshRate, and m_UseVblank.
GetSpeed()
double CVideoReferenceClock::GetSpeed ()
References m_ClockSpeed, m_CritSection, and m_UseVblank.
GetTime()
int64_t CVideoReferenceClock::GetTime (bool interpolated = true)
References CurrentHostCounter(), int64_t(), m_ClockSpeed, m_CritSection, m_CurrTime, m_LastIntTime, m_UseVblank, m_VblankTime, TimeOfNextVblank(), UpdateClockInternal(), and UpdateInterval().
Process()
void CVideoReferenceClock::Process (void) override private virtual
Reimplemented from CThread.
References CurrentHostCounter(), CWinSystemBase::GetVideoSync(), CServiceBroker::GetWinSystem(), int64_t(), CLog::Log(), LOGDEBUG, CThread::m_bStop, m_ClockSpeed, m_CritSection, m_CurrTime, m_CurrTimeFract, m_LastIntTime, m_MissedVblanks, m_pVideoSync, m_TotalMissedVblanks, m_UseVblank, m_VblankTime, m_vsyncStopEvent, CEvent::Reset(), CEvent::Signaled(), and UpdateRefreshrate().
SetSpeed()
void CVideoReferenceClock::SetSpeed (double Speed)
References CLog::Log(), LOGDEBUG, m_ClockSpeed, m_CritSection, and m_UseVblank.
Start()
void CVideoReferenceClock::Start () private
References CThread::Create(), CServiceBroker::GetSettingsComponent(), CThread::IsRunning(), and CSettings::SETTING_VIDEOPLAYER_USEDISPLAYASCLOCK.
Referenced by CVideoReferenceClock().
TimeOfNextVblank()
int64_t CVideoReferenceClock::TimeOfNextVblank () const private
References m_RefreshRate, m_SystemFrequency, m_VblankTime, MAXVBLANKDELAY, and MathUtils::round_int().
Referenced by GetTime().
UpdateClock()
void CVideoReferenceClock::UpdateClock (int NrVBlanks, uint64_t time)
References m_CritSection, m_VblankTime, and UpdateClockInternal().
Referenced by CVideoSyncAndroid::FrameCallback(), KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::HandlePresentation(), CVideoSyncIos::IosVblankHandler(), CVideoSyncGbm::Run(), CVideoSyncD3D::Run(), KODI::WINDOWING::X11::CVideoSyncGLX::Run(), KODI::WINDOWING::X11::CVideoSyncOML::Run(), CVideoSyncTVos::TVosVblankHandler(), and CVideoSyncOsx::VblankHandler().
UpdateClockInternal()
void CVideoReferenceClock::UpdateClockInternal (int NrVBlanks, bool CheckMissed) private
References int64_t(), CLog::Log(), LOGDEBUG, m_CurrTime, m_CurrTimeFract, m_MissedVblanks, m_RefreshRate, m_SystemFrequency, m_TotalMissedVblanks, m_VblankTime, MathUtils::round_int(), and UpdateInterval().
Referenced by GetTime(), and UpdateClock().
UpdateInterval()
double CVideoReferenceClock::UpdateInterval () const private
References m_ClockSpeed, m_RefreshRate, and m_SystemFrequency.
Referenced by GetTime(), and UpdateClockInternal().
UpdateRefreshrate()
void CVideoReferenceClock::UpdateRefreshrate () private
References CLog::Log(), LOGDEBUG, m_ClockSpeed, m_CritSection, m_pVideoSync, and m_RefreshRate.
Referenced by Process().
Member Data Documentation
m_ClockSpeed
double CVideoReferenceClock::m_ClockSpeed private
Referenced by CVideoReferenceClock(), GetClockInfo(), GetRefreshRate(), GetSpeed(), GetTime(), Process(), SetSpeed(), UpdateInterval(), and UpdateRefreshrate().
m_CritSection
CCriticalSection CVideoReferenceClock::m_CritSection mutable private
Referenced by GetClockInfo(), GetRefreshRate(), GetSpeed(), GetTime(), Process(), SetSpeed(), UpdateClock(), and UpdateRefreshrate().
m_CurrTime
int64_t CVideoReferenceClock::m_CurrTime private
Referenced by CVideoReferenceClock(), GetTime(), Process(), and UpdateClockInternal().
m_CurrTimeFract
double CVideoReferenceClock::m_CurrTimeFract private
Referenced by CVideoReferenceClock(), Process(), and UpdateClockInternal().
m_LastIntTime
int64_t CVideoReferenceClock::m_LastIntTime private
Referenced by CVideoReferenceClock(), GetTime(), and Process().
m_MissedVblanks
int CVideoReferenceClock::m_MissedVblanks private
Referenced by CVideoReferenceClock(), Process(), and UpdateClockInternal().
m_pVideoSync
std::unique_ptr<CVideoSync> CVideoReferenceClock::m_pVideoSync private
Referenced by Process(), and UpdateRefreshrate().
m_RefreshRate
double CVideoReferenceClock::m_RefreshRate private
Referenced by CVideoReferenceClock(), GetClockInfo(), GetRefreshRate(), TimeOfNextVblank(), UpdateClockInternal(), UpdateInterval(), and UpdateRefreshrate().
m_SystemFrequency
int64_t CVideoReferenceClock::m_SystemFrequency private
Referenced by CVideoReferenceClock(), TimeOfNextVblank(), UpdateClockInternal(), and UpdateInterval().
m_TotalMissedVblanks
int CVideoReferenceClock::m_TotalMissedVblanks private
Referenced by CVideoReferenceClock(), GetClockInfo(), Process(), and UpdateClockInternal().
m_UseVblank
bool CVideoReferenceClock::m_UseVblank private
Referenced by CVideoReferenceClock(), GetClockInfo(), GetRefreshRate(), GetSpeed(), GetTime(), Process(), and SetSpeed().
m_VblankTime
int64_t CVideoReferenceClock::m_VblankTime private
Referenced by CVideoReferenceClock(), GetTime(), Process(), TimeOfNextVblank(), UpdateClock(), and UpdateClockInternal().
m_vsyncStopEvent
CEvent CVideoReferenceClock::m_vsyncStopEvent private
Referenced by CVideoReferenceClock(), Process(), and ~CVideoReferenceClock().
The documentation for this class was generated from the following files:
VideoReferenceClock.h
VideoReferenceClock.cpp