Kodi Documentation: CVideoInfoDownloader Class Reference
CVideoInfoDownloader Class Reference
#include <VideoInfoDownloader.h>
Public Member Functions
CVideoInfoDownloader (const ADDON::ScraperPtr &scraper)
~CVideoInfoDownloader () override
int FindMovie (const std::string &movieTitle, int movieYear, MOVIELIST &movielist, CGUIDialogProgress *pProgress=NULL)
Do a search for matching media items (possibly asynchronously) with our scraper.
bool GetArtwork (CVideoInfoTag &details)
Fetch art URLs for an item with our scraper.
bool GetDetails (const std::unordered_map< std::string, std::string > &uniqueIDs, const CScraperUrl &url, CVideoInfoTag &movieDetails, CGUIDialogProgress *pProgress=NULL)
bool GetEpisodeDetails (const CScraperUrl &url, CVideoInfoTag &movieDetails, CGUIDialogProgress *pProgress=NULL)
bool GetEpisodeList (const CScraperUrl &url, KODI::VIDEO::EPISODELIST &details, CGUIDialogProgress *pProgress=NULL)
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Static Public Member Functions
static void ShowErrorDialog (const ADDON::CScraperError &sce)
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types
enum LOOKUP_STATE {
DO_NOTHING = 0 , FIND_MOVIE = 1 , GET_DETAILS = 2 , GET_EPISODE_LIST = 3 ,
GET_EPISODE_DETAILS = 4
}
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions
void Process () override
void CloseThread ()
int InternalFindMovie (const std::string &movieTitle, int movieYear, MOVIELIST &movielist, bool cleanChars=true)
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes
XFILE::CCurlFile * m_http
std::string m_movieTitle
int m_movieYear
std::unordered_map< std::string, std::string > m_uniqueIDs
MOVIELIST m_movieList
CVideoInfoTag m_movieDetails
CScraperUrl m_url
KODI::VIDEO::EPISODELIST m_episode
LOOKUP_STATE m_state = DO_NOTHING
int m_found = 0
ADDON::ScraperPtr m_info
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Member Enumeration Documentation
LOOKUP_STATE
enum CVideoInfoDownloader::LOOKUP_STATE protected
Enumerator
DO_NOTHING
FIND_MOVIE
GET_DETAILS
GET_EPISODE_LIST
GET_EPISODE_DETAILS
Constructor & Destructor Documentation
CVideoInfoDownloader()
CVideoInfoDownloader::CVideoInfoDownloader (const ADDON::ScraperPtr & scraper) explicit
References m_http.
~CVideoInfoDownloader()
CVideoInfoDownloader::~CVideoInfoDownloader () override
References m_http.
Member Function Documentation
CloseThread()
void CVideoInfoDownloader::CloseThread () protected
References XFILE::CCurlFile::Cancel(), DO_NOTHING, m_found, m_http, m_state, XFILE::CCurlFile::Reset(), and CThread::StopThread().
Referenced by FindMovie(), GetDetails(), GetEpisodeDetails(), and GetEpisodeList().
FindMovie()
int CVideoInfoDownloader::FindMovie (const std::string & movieTitle, int movieYear, MOVIELIST & movielist, CGUIDialogProgress * pProgress = NULL)
Do a search for matching media items (possibly asynchronously) with our scraper.
Parameters
movieTitle title of the media item to look for
movieYear year of the media item to look for (-1 if not known)
movielist [out] list of results to fill. May be empty on success.
pProgress progress bar to update as we go. If NULL we run on thread, if non-NULL we run off thread.
Returns
1 on success, -1 on a scraper-specific error, 0 on some other error
References CloseThread(), CThread::Create(), DO_NOTHING, FIND_MOVIE, InternalFindMovie(), CGUIDialogProgress::IsCanceled(), CThread::IsRunning(), m_found, m_movieList, m_movieTitle, m_movieYear, m_state, CGUIDialogProgress::Progress(), CThread::Sleep(), CThread::StopThread(), and success.
Referenced by KODI::VIDEO::CVideoInfoScanner::FindVideo(), Process(), and CVideoLibraryRefreshingJob::Work().
GetArtwork()
bool CVideoInfoDownloader::GetArtwork (CVideoInfoTag & details)
Fetch art URLs for an item with our scraper.
Parameters
details the video info tag structure to fill with art.
Returns
true on success, false on failure.
References m_http, and m_info.
Referenced by KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForEpisodes().
GetDetails()
bool CVideoInfoDownloader::GetDetails (const std::unordered_map< std::string, std::string > & uniqueIDs, const CScraperUrl & url, CVideoInfoTag & movieDetails, CGUIDialogProgress * pProgress = NULL)
References CloseThread(), CThread::Create(), GET_DETAILS, CGUIDialogProgress::IsCanceled(), CThread::IsRunning(), m_found, m_http, m_info, m_movieDetails, m_state, m_uniqueIDs, m_url, CGUIDialogProgress::Progress(), CVideoInfoTag::Reset(), CThread::Sleep(), and CThread::StopThread().
Referenced by KODI::VIDEO::CVideoInfoScanner::GetDetails(), and Process().
GetEpisodeDetails()
bool CVideoInfoDownloader::GetEpisodeDetails (const CScraperUrl & url, CVideoInfoTag & movieDetails, CGUIDialogProgress * pProgress = NULL)
References CloseThread(), CThread::Create(), GET_EPISODE_DETAILS, CGUIDialogProgress::IsCanceled(), CThread::IsRunning(), m_found, m_http, m_info, m_movieDetails, m_state, m_uniqueIDs, m_url, CGUIDialogProgress::Progress(), CVideoInfoTag::Reset(), CThread::Sleep(), and CThread::StopThread().
Referenced by KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(), and Process().
GetEpisodeList()
bool CVideoInfoDownloader::GetEpisodeList (const CScraperUrl & url, KODI::VIDEO::EPISODELIST & details, CGUIDialogProgress * pProgress = NULL)
References CloseThread(), CThread::Create(), GET_EPISODE_LIST, CGUIDialogProgress::IsCanceled(), CThread::IsRunning(), m_episode, m_found, m_http, m_info, m_state, m_url, CGUIDialogProgress::Progress(), CThread::Sleep(), and CThread::StopThread().
Referenced by KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(), and Process().
InternalFindMovie()
int CVideoInfoDownloader::InternalFindMovie (const std::string & movieTitle, int movieYear, MOVIELIST & movielist, bool cleanChars = true) protected
References ADDON::CScraperError::FAborted(), m_http, m_info, and ShowErrorDialog().
Referenced by FindMovie().
Process()
void CVideoInfoDownloader::Process (void) override protected virtual
Reimplemented from CThread.
References DO_NOTHING, FIND_MOVIE, FindMovie(), GET_DETAILS, GET_EPISODE_DETAILS, GET_EPISODE_LIST, GetDetails(), GetEpisodeDetails(), GetEpisodeList(), CScraperUrl::GetFirstThumbUrl(), CScraperUrl::HasUrls(), CLog::Log(), LOGERROR, m_episode, m_found, m_movieDetails, m_movieList, m_movieTitle, m_movieYear, m_state, m_uniqueIDs, and m_url.
ShowErrorDialog()
void CVideoInfoDownloader::ShowErrorDialog (const ADDON::CScraperError & sce) static
References ADDON::CScraperError::Message(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and ADDON::CScraperError::Title().
Referenced by InternalFindMovie(), and CNfoFile::Scrape().
Member Data Documentation
m_episode
KODI::VIDEO::EPISODELIST CVideoInfoDownloader::m_episode protected
Referenced by GetEpisodeList(), and Process().
m_found
int CVideoInfoDownloader::m_found = 0 protected
Referenced by CloseThread(), FindMovie(), GetDetails(), GetEpisodeDetails(), GetEpisodeList(), and Process().
m_http
XFILE::CCurlFile* CVideoInfoDownloader::m_http protected
Referenced by CloseThread(), CVideoInfoDownloader(), GetArtwork(), GetDetails(), GetEpisodeDetails(), GetEpisodeList(), InternalFindMovie(), and ~CVideoInfoDownloader().
m_info
ADDON::ScraperPtr CVideoInfoDownloader::m_info protected
Referenced by GetArtwork(), GetDetails(), GetEpisodeDetails(), GetEpisodeList(), and InternalFindMovie().
m_movieDetails
CVideoInfoTag CVideoInfoDownloader::m_movieDetails protected
Referenced by GetDetails(), GetEpisodeDetails(), and Process().
m_movieList
MOVIELIST CVideoInfoDownloader::m_movieList protected
Referenced by FindMovie(), and Process().
m_movieTitle
std::string CVideoInfoDownloader::m_movieTitle protected
Referenced by FindMovie(), and Process().
m_movieYear
int CVideoInfoDownloader::m_movieYear protected
Referenced by FindMovie(), and Process().
m_state
LOOKUP_STATE CVideoInfoDownloader::m_state = DO_NOTHING protected
Referenced by CloseThread(), FindMovie(), GetDetails(), GetEpisodeDetails(), GetEpisodeList(), and Process().
m_uniqueIDs
std::unordered_map<std::string, std::string> CVideoInfoDownloader::m_uniqueIDs protected
Referenced by GetDetails(), GetEpisodeDetails(), and Process().
m_url
CScraperUrl CVideoInfoDownloader::m_url protected
Referenced by GetDetails(), GetEpisodeDetails(), GetEpisodeList(), and Process().
The documentation for this class was generated from the following files:
VideoInfoDownloader.h
VideoInfoDownloader.cpp