Kodi Documentation: PVR::CPVRChannelGroupSettings Class Reference
PVR::CPVRChannelGroupSettings Class Reference
#include <PVRChannelGroupSettings.h>
Public Member Functions
CPVRChannelGroupSettings ()
virtual ~CPVRChannelGroupSettings ()
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void RegisterCallback (IChannelGroupSettingsCallback *callback)
void UnregisterCallback (IChannelGroupSettingsCallback *callback)
bool UseBackendChannelOrder () const
bool UseBackendChannelNumbers () const
bool StartGroupChannelNumbersFromOne () const
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Private Member Functions
bool UpdateUseBackendChannelOrder ()
bool UpdateUseBackendChannelNumbers ()
bool UpdateStartGroupChannelNumbersFromOne ()
Private Attributes
bool m_bUseBackendChannelOrder = false
bool m_bUseBackendChannelNumbers = false
bool m_bStartGroupChannelNumbersFromOne = false
CPVRSettings m_settings
std::set< IChannelGroupSettingsCallback * > m_callbacks
Constructor & Destructor Documentation
CPVRChannelGroupSettings()
CPVRChannelGroupSettings::CPVRChannelGroupSettings ()
References CSettings::SETTING_PVRMANAGER_BACKENDCHANNELORDER, CSettings::SETTING_PVRMANAGER_STARTGROUPCHANNELNUMBERSFROMONE, CSettings::SETTING_PVRMANAGER_USEBACKENDCHANNELNUMBERS, and CSettings::SETTING_PVRMANAGER_USEBACKENDCHANNELNUMBERSALWAYS.
~CPVRChannelGroupSettings()
CPVRChannelGroupSettings::~CPVRChannelGroupSettings () virtual
References m_settings, and PVR::CPVRSettings::UnregisterCallback().
Member Function Documentation
OnSettingChanged()
void CPVRChannelGroupSettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References m_callbacks, CSettings::SETTING_PVRMANAGER_STARTGROUPCHANNELNUMBERSFROMONE, CSettings::SETTING_PVRMANAGER_USEBACKENDCHANNELNUMBERS, CSettings::SETTING_PVRMANAGER_USEBACKENDCHANNELNUMBERSALWAYS, StartGroupChannelNumbersFromOne(), UpdateStartGroupChannelNumbersFromOne(), UpdateUseBackendChannelNumbers(), UpdateUseBackendChannelOrder(), UseBackendChannelNumbers(), and UseBackendChannelOrder().
RegisterCallback()
void CPVRChannelGroupSettings::RegisterCallback (IChannelGroupSettingsCallback * callback)
References m_callbacks.
StartGroupChannelNumbersFromOne()
bool PVR::CPVRChannelGroupSettings::StartGroupChannelNumbersFromOne () const inline
References m_bStartGroupChannelNumbersFromOne.
Referenced by OnSettingChanged().
UnregisterCallback()
void CPVRChannelGroupSettings::UnregisterCallback (IChannelGroupSettingsCallback * callback)
References m_callbacks.
UpdateStartGroupChannelNumbersFromOne()
bool CPVRChannelGroupSettings::UpdateStartGroupChannelNumbersFromOne () private
References PVR::CPVRSettings::GetBoolValue(), m_bStartGroupChannelNumbersFromOne, m_settings, CSettings::SETTING_PVRMANAGER_STARTGROUPCHANNELNUMBERSFROMONE, and UseBackendChannelNumbers().
Referenced by OnSettingChanged().
UpdateUseBackendChannelNumbers()
bool CPVRChannelGroupSettings::UpdateUseBackendChannelNumbers () private
References PVR::CPVRManager::Clients(), PVR::CPVRSettings::GetBoolValue(), CServiceBroker::GetPVRManager(), m_bUseBackendChannelNumbers, m_settings, CSettings::SETTING_PVRMANAGER_USEBACKENDCHANNELNUMBERS, and CSettings::SETTING_PVRMANAGER_USEBACKENDCHANNELNUMBERSALWAYS.
Referenced by OnSettingChanged().
UpdateUseBackendChannelOrder()
bool CPVRChannelGroupSettings::UpdateUseBackendChannelOrder () private
References PVR::CPVRSettings::GetBoolValue(), m_bUseBackendChannelOrder, m_settings, and CSettings::SETTING_PVRMANAGER_BACKENDCHANNELORDER.
Referenced by OnSettingChanged().
UseBackendChannelNumbers()
bool PVR::CPVRChannelGroupSettings::UseBackendChannelNumbers () const inline
References m_bUseBackendChannelNumbers.
Referenced by OnSettingChanged(), and UpdateStartGroupChannelNumbersFromOne().
UseBackendChannelOrder()
bool PVR::CPVRChannelGroupSettings::UseBackendChannelOrder () const inline
References m_bUseBackendChannelOrder.
Referenced by OnSettingChanged().
Member Data Documentation
m_bStartGroupChannelNumbersFromOne
bool PVR::CPVRChannelGroupSettings::m_bStartGroupChannelNumbersFromOne = false private
Referenced by StartGroupChannelNumbersFromOne(), and UpdateStartGroupChannelNumbersFromOne().
m_bUseBackendChannelNumbers
bool PVR::CPVRChannelGroupSettings::m_bUseBackendChannelNumbers = false private
Referenced by UpdateUseBackendChannelNumbers(), and UseBackendChannelNumbers().
m_bUseBackendChannelOrder
bool PVR::CPVRChannelGroupSettings::m_bUseBackendChannelOrder = false private
Referenced by UpdateUseBackendChannelOrder(), and UseBackendChannelOrder().
m_callbacks
std::set<IChannelGroupSettingsCallback*> PVR::CPVRChannelGroupSettings::m_callbacks private
Referenced by OnSettingChanged(), RegisterCallback(), and UnregisterCallback().
m_settings
CPVRSettings PVR::CPVRChannelGroupSettings::m_settings private
Referenced by UpdateStartGroupChannelNumbersFromOne(), UpdateUseBackendChannelNumbers(), UpdateUseBackendChannelOrder(), and ~CPVRChannelGroupSettings().
The documentation for this class was generated from the following files:
PVRChannelGroupSettings.h
PVRChannelGroupSettings.cpp