Kodi Documentation: CGUIDialogSelect Class Reference
CGUIDialogSelect Class Reference
#include <GUIDialogSelect.h>
Public Member Functions
CGUIDialogSelect ()
CGUIDialogSelect (int windowid)
~CGUIDialogSelect (void) override
bool OnMessage (CGUIMessage &message) override
bool OnBack (int actionID) override
void Reset ()
int Add (const std::string &strLabel)
int Add (const CFileItem &item)
void SetItems (const CFileItemList &items)
const CFileItemPtr GetSelectedFileItem () const
int GetSelectedItem () const
const std::vector< int > & GetSelectedItems () const
void EnableButton (bool enable, int label)
void EnableButton (bool enable, const std::string &label)
void EnableButton2 (bool enable, int label)
void EnableButton2 (bool enable, const std::string &label)
bool IsButtonPressed ()
bool IsButton2Pressed ()
void Sort (bool bSortOrder=true)
void SetSelected (int iSelected)
void SetSelected (const std::string &strSelectedLabel)
void SetSelected (const std::vector< int > &selectedIndexes)
void SetSelected (const std::vector< std::string > &selectedLabels)
void SetUseDetails (bool useDetails)
void SetMultiSelection (bool multiSelection)
void SetButtonFocus (bool buttonFocus)
Public Member Functions inherited from CGUIDialogBoxBase
CGUIDialogBoxBase (int id, const std::string &xmlFile)
~CGUIDialogBoxBase (void) override
bool IsConfirmed () const
void SetLine (unsigned int iLine, const CVariant &line)
void SetText (const CVariant &text)
bool HasText () const
void SetHeading (const CVariant &heading)
bool HasHeading () const
void SetChoice (int iButton, const CVariant &choice)
Public Member Functions inherited from CGUIDialog
CGUIDialog (int id, const std::string &xmlFile, DialogModalityType modalityType=DialogModalityType::MODAL)
~CGUIDialog (void) override
bool OnAction (const CAction &action) override
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void Open (const std::string &param="")
void Open (bool bProcessRenderLoop, const std::string &param="")
bool IsDialogRunning () const override
bool IsDialog () const override
bool IsModalDialog () const override
virtual DialogModalityType GetModalityType () const
void SetAutoClose (unsigned int timeoutMs)
void ResetAutoClose (void)
void CancelAutoClose (void)
bool IsAutoClosed (void) const
void SetSound (bool OnOff)
bool IsSoundEnabled () const override
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
bool OnAction (const CAction &action) override
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool OnMessage (CGUIMessage &message) override
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsMediaWindow () const
virtual bool HasListItems () const
virtual CFileItemPtr GetCurrentListItem (int offset=0)
virtual int GetViewContainerID () const
virtual int GetViewCount () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
CGUIControl * GetFirstFocusableControl (int id) override
void OnWindowLoaded () override
void OnInitWindow () override
Called on window open.
void OnDeinitWindow (int nextWindowID) override
void OnWindowUnload () override
virtual void OnSelect (int idx)
Protected Member Functions inherited from CGUIDialogBoxBase
std::string GetDefaultLabel (int controlId) const
virtual int GetDefaultLabelID (int controlId) const
std::string GetLocalized (const CVariant &var) const
Get a localized string from a variant If the variant is already a string we return directly, else if it's an integer we return the corresponding localized string.
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
Protected Member Functions inherited from CGUIDialog
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
void SetDefaults () override
virtual void UpdateVisibility ()
virtual void Open_Internal (bool bProcessRenderLoop, const std::string &param="")
void ProcessRenderLoop (bool renderOnly=false)
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
virtual void SaveControlStates ()
virtual void RestoreControlStates ()
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
CFileItemPtr m_selectedItem
std::unique_ptr< CFileItemList > m_vecList
CGUIViewControl m_viewControl
Protected Attributes inherited from CGUIDialogBoxBase
bool m_bConfirmed
bool m_hasTextbox
CCriticalSection m_section
std::string m_strHeading
std::string m_text
std::string m_strChoices [DIALOG_MAX_CHOICES]
Protected Attributes inherited from CGUIDialog
bool m_wasRunning
true if we were running during the last DoProcess()
bool m_autoClosing
bool m_enableSound
unsigned int m_showStartTime
unsigned int m_showDuration
bool m_bAutoClosed
DialogModalityType m_modalityType
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Private Attributes
bool m_bButtonEnabled
bool m_bButton2Enabled
bool m_bButtonPressed
bool m_bButton2Pressed
std::string m_buttonLabel
std::string m_button2Label
bool m_useDetails
bool m_multiSelection
bool m_focusToButton {}
std::vector< int > m_selectedItems
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIDialogSelect() [1/2]
CGUIDialogSelect::CGUIDialogSelect ()
CGUIDialogSelect() [2/2]
CGUIDialogSelect::CGUIDialogSelect (int windowid) explicit
References CGUIWindow::KEEP_IN_MEMORY, CGUIDialogBoxBase::m_bConfirmed, and CGUIWindow::m_loadType.
~CGUIDialogSelect()
CGUIDialogSelect::~CGUIDialogSelect (void) override default
Member Function Documentation
Add() [1/2]
int CGUIDialogSelect::Add (const CFileItem & item)
References m_vecList.
Add() [2/2]
int CGUIDialogSelect::Add (const std::string & strLabel)
References m_vecList.
Referenced by anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::AddAction(), CGUIViewState::ChooseSortMethod(), CMusicDatabase::DeleteCDDBInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CStereoscopicsManager::GetStereoModeByUserChoice(), XBMCAddon::xbmcgui::Dialog::multiselect(), CPlayerController::OnAction(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), CGUIDialogSmartPlaylistRule::OnField(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), CGUIDialogSmartPlaylistEditor::OnLimit(), CGUIDialogSmartPlaylistRule::OnOperator(), CGUIDialogSmartPlaylistEditor::OnOrder(), CGUIWindowVideoBase::OnSearch(), CGUIDialogVideoInfo::OnSearch(), CGUIDialogLockSettings::OnSettingAction(), CGUIDialogContentSettings::OnSettingAction(), CGUIDialogVideoInfo::OnSetUserrating(), CStereoscopicsManager::OnStreamChange(), CGUIDialogSmartPlaylistEditor::OnType(), ADDON::Interface_GUIDialogSelect::open(), ADDON::Interface_GUIDialogSelect::open_multi_select(), PVR::CPVRGUIActionsClients::ProcessSettingsMenuHooks(), XBMCAddon::xbmcgui::Dialog::select(), SelectBool(), CGUIDialogVisualisationPresetList::SetVisualisation(), CGUIDialogAddonSettings::ShowForMultipleInstances(), MUSIC_UTILS::ShowSelectRatingDialog(), PVR::CPVRGUIActionsChannels::StartChannelScan(), and CVideoLibraryRefreshingJob::Work().
EnableButton() [1/2]
void CGUIDialogSelect::EnableButton (bool enable, const std::string & label)
References label, m_bButtonEnabled, and m_buttonLabel.
EnableButton() [2/2]
void CGUIDialogSelect::EnableButton (bool enable, int label)
References g_localizeStrings, CLocalizeStrings::Get(), label, m_bButtonEnabled, and m_buttonLabel.
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CGUIDialogVideoInfo::GetItemsForTag(), CGUIDialogVideoInfo::GetMoviesForSet(), CGUIDialogVideoInfo::GetSetForMovie(), OnInitWindow(), CGUIWindowAddonBrowser::SelectAddonID(), MUSIC_UTILS::ShowSelectArtTypeDialog(), and CVideoLibraryRefreshingJob::Work().
EnableButton2() [1/2]
void CGUIDialogSelect::EnableButton2 (bool enable, const std::string & label)
References label, m_bButton2Enabled, and m_button2Label.
EnableButton2() [2/2]
void CGUIDialogSelect::EnableButton2 (bool enable, int label)
References g_localizeStrings, CLocalizeStrings::Get(), label, m_bButton2Enabled, and m_button2Label.
Referenced by CGUIControlListSetting::OnClick().
GetFirstFocusableControl()
CGUIControl * CGUIDialogSelect::GetFirstFocusableControl (int id) override protected virtual
Reimplemented from CGUIControlGroup.
References CGUIViewControl::GetCurrentControl(), CGUIControlGroup::GetFirstFocusableControl(), CGUIViewControl::HasControl(), and m_viewControl.
GetSelectedFileItem()
const CFileItemPtr CGUIDialogSelect::GetSelectedFileItem () const
References m_selectedItem.
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), CMusicDatabase::DeleteCDDBInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CGUIDialogVideoInfo::GetSetForMovie(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), anonymous_namespace{VideoStreamSelectHelper.cpp}::OpenSelectDialog(), CGUIDialogAddonSettings::ShowForMultipleInstances(), CGUIDialogSimpleMenu::ShowPlaySelection(), and MUSIC_UTILS::ShowSelectArtTypeDialog().
GetSelectedItem()
int CGUIDialogSelect::GetSelectedItem () const
References m_selectedItems.
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), CGUIViewState::ChooseSortMethod(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::ChooseStackItemPartNumber(), CMusicDatabase::DeleteCDDBInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), CStereoscopicsManager::GetStereoModeByUserChoice(), CGUIDialogVideoInfo::LinkMovieToTvShow(), CPlayerController::OnAction(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), CGUIDialogSmartPlaylistRule::OnField(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), OnInitWindow(), CGUIDialogSmartPlaylistEditor::OnLimit(), CGUIDialogSmartPlaylistRule::OnOperator(), CGUIDialogSmartPlaylistEditor::OnOrder(), CGUIWindowVideoBase::OnSearch(), CGUIDialogVideoInfo::OnSearch(), CGUIDialogLockSettings::OnSettingAction(), CGUIDialogContentSettings::OnSettingAction(), CGUIDialogVideoInfo::OnSetUserrating(), CStereoscopicsManager::OnStreamChange(), CGUIDialogSmartPlaylistEditor::OnType(), ADDON::Interface_GUIDialogSelect::open(), PVR::CPVRGUIActionsClients::ProcessSettingsMenuHooks(), anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::Select(), XBMCAddon::xbmcgui::Dialog::select(), SelectBool(), PERIPHERALS::CGUIDialogPeripherals::Show(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), CGUIDialogAddonSettings::ShowForMultipleInstances(), CGUIDialogSimpleMenu::ShowPlaySelection(), MUSIC_UTILS::ShowSelectRatingDialog(), PVR::CPVRGUIActionsChannels::StartChannelScan(), PERIPHERALS::CGUIDialogPeripherals::UpdatePeripheralsSync(), and CVideoLibraryRefreshingJob::Work().
GetSelectedItems()
const std::vector< int > & CGUIDialogSelect::GetSelectedItems () const
References m_selectedItems.
Referenced by CGUIDialogVideoInfo::GetItemsForTag(), CGUIDialogVideoInfo::GetMoviesForSet(), XBMCAddon::xbmcgui::Dialog::multiselect(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIControlListSetting::OnClick(), ADDON::Interface_GUIDialogSelect::open_multi_select(), anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::Select(), and CGUIWindowAddonBrowser::SelectAddonID().
IsButton2Pressed()
bool CGUIDialogSelect::IsButton2Pressed ()
References m_bButton2Pressed.
Referenced by CGUIControlListSetting::OnClick().
IsButtonPressed()
bool CGUIDialogSelect::IsButtonPressed ()
References m_bButtonPressed.
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), CGUIDialogVideoInfo::GetSetForMovie(), CGUIWindowAddonBrowser::SelectAddonID(), CGUIDialogAddonSettings::ShowForMultipleInstances(), MUSIC_UTILS::ShowSelectArtTypeDialog(), and CVideoLibraryRefreshingJob::Work().
OnBack()
bool CGUIDialogSelect::OnBack (int actionID) override virtual
Reimplemented from CGUIDialog.
References CGUIDialogBoxBase::m_bConfirmed, m_selectedItem, m_selectedItems, m_vecList, and CGUIControl::OnBack().
OnDeinitWindow()
void CGUIDialogSelect::OnDeinitWindow (int nextWindowID) override protected virtual
Reimplemented from CGUIDialogBoxBase.
Reimplemented in CGUIDialogVisualisationPresetList.
References CGUIViewControl::Clear(), m_viewControl, and CGUIDialogBoxBase::OnDeinitWindow().
Referenced by CGUIDialogVisualisationPresetList::OnDeinitWindow().
OnInitWindow()
void CGUIDialogSelect::OnInitWindow (void) override protected virtual
Called on window open.
Restores the control state(s)
Sets initial visibility of controls
Queue WindowOpen animation
Set overlay state Override this function and do any window-specific initialisation such as filling control contents and setting control focus before calling the base method.
Reimplemented from CGUIDialogBoxBase.
Reimplemented in CGUIDialogVisualisationPresetList.
References CONTROL_CANCEL_BUTTON, CONTROL_DETAILED_LIST, CONTROL_EXTRA_BUTTON, CONTROL_EXTRA_BUTTON2, CONTROL_NUMBER_OF_ITEMS, CONTROL_SIMPLE_LIST, EnableButton(), g_localizeStrings, CLocalizeStrings::Get(), GetSelectedItem(), m_bButton2Enabled, m_bButtonEnabled, m_button2Label, m_buttonLabel, m_focusToButton, m_multiSelection, m_selectedItem, m_selectedItems, m_useDetails, m_vecList, m_viewControl, CGUIDialogBoxBase::OnInitWindow(), SET_CONTROL_FOCUS, SET_CONTROL_HIDDEN, SET_CONTROL_LABEL, SET_CONTROL_VISIBLE, CGUIViewControl::SetCurrentView(), CGUIViewControl::SetItems(), and CGUIViewControl::SetSelectedItem().
Referenced by CGUIDialogVisualisationPresetList::OnInitWindow(), and PERIPHERALS::CGUIDialogPeripherals::OnInitWindow().
OnMessage()
bool CGUIDialogSelect::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIDialogBoxBase.
Reimplemented in CGUIDialogVisualisationPresetList.
References ACTION_MOUSE_LEFT_CLICK, ACTION_SELECT_ITEM, Close(), CONTROL_CANCEL_BUTTON, CONTROL_EXTRA_BUTTON, CONTROL_EXTRA_BUTTON2, CONTROL_SIMPLE_LIST, CGUIMessage::GetControlId(), CGUIViewControl::GetCurrentControl(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIViewControl::GetSelectedItem(), CGUIMessage::GetSenderId(), GUI_MSG_CLICKED, GUI_MSG_SETFOCUS, GUI_MSG_WINDOW_DEINIT, GUI_MSG_WINDOW_INIT, CGUIViewControl::HasControl(), m_bButton2Enabled, m_bButton2Pressed, m_bButtonEnabled, m_bButtonPressed, CGUIDialogBoxBase::m_bConfirmed, m_multiSelection, m_selectedItem, m_selectedItems, m_useDetails, m_vecList, m_viewControl, CGUIDialogBoxBase::OnMessage(), OnSelect(), SET_CONTROL_FOCUS, and CGUIViewControl::SetFocused().
Referenced by CGUIDialogVisualisationPresetList::OnMessage(), and PERIPHERALS::CGUIDialogPeripherals::OnMessage().
OnSelect()
void CGUIDialogSelect::OnSelect (int idx) protected virtual
Reimplemented in CGUIDialogVisualisationPresetList.
References Close(), and CGUIDialogBoxBase::m_bConfirmed.
Referenced by OnMessage().
OnWindowLoaded()
void CGUIDialogSelect::OnWindowLoaded () override protected virtual
Reimplemented from CGUIDialog.
References CGUIViewControl::AddView(), CONTROL_DETAILED_LIST, CONTROL_SIMPLE_LIST, CGUIControlLookup::GetControl(), CGUIControl::GetID(), m_viewControl, CGUIDialog::OnWindowLoaded(), CGUIViewControl::Reset(), and CGUIViewControl::SetParentWindow().
OnWindowUnload()
void CGUIDialogSelect::OnWindowUnload () override protected virtual
Reimplemented from CGUIWindow.
References m_viewControl, CGUIWindow::OnWindowUnload(), and CGUIViewControl::Reset().
Reset()
void CGUIDialogSelect::Reset ()
References m_bButton2Enabled, m_bButton2Pressed, m_bButtonEnabled, m_bButtonPressed, m_focusToButton, m_multiSelection, m_selectedItem, m_selectedItems, m_useDetails, and m_vecList.
Referenced by CGUIDialogAddonInfo::AskForVersion(), anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), CGUIViewState::ChooseSortMethod(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::ChooseStackItemPartNumber(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), CGUIDialogVisualisationPresetList::ClearVisualisation(), CMusicDatabase::DeleteCDDBInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CAutorunMediaJob::DoWork(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), KODI::GAME::CGUIDialogSelectGameClient::GetDialog(), CGUIDialogVideoInfo::GetItemsForTag(), CGUIDialogVideoInfo::GetMoviesForSet(), CGUIDialogVideoInfo::GetSetForMovie(), CStereoscopicsManager::GetStereoModeByUserChoice(), anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::InstantRecordingActionSelector(), CGUIDialogVideoInfo::LinkMovieToTvShow(), XBMCAddon::xbmcgui::Dialog::multiselect(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIControlListSetting::OnClick(), CGUIDialogSmartPlaylistRule::OnField(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), CGUIDialogSmartPlaylistEditor::OnLimit(), CGUIDialogVideoInfo::OnMessage(), CGUIDialogSmartPlaylistRule::OnOperator(), CGUIDialogSmartPlaylistEditor::OnOrder(), CGUIWindowVideoBase::OnSearch(), CGUIDialogVideoInfo::OnSearch(), CGUIDialogLockSettings::OnSettingAction(), CStereoscopicsManager::OnStreamChange(), CGUIDialogSmartPlaylistEditor::OnType(), ADDON::Interface_GUIDialogSelect::open(), ADDON::Interface_GUIDialogSelect::open_multi_select(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), anonymous_namespace{VideoStreamSelectHelper.cpp}::OpenSelectDialog(), PVR::CPVRGUIActionsClients::ProcessSettingsMenuHooks(), anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::Select(), XBMCAddon::xbmcgui::Dialog::select(), CGUIWindowAddonBrowser::SelectAddonID(), SelectBool(), CGUIDialogVisualisationPresetList::SetVisualisation(), PERIPHERALS::CGUIDialogPeripherals::Show(), CGUIDialogAddonSettings::ShowForMultipleInstances(), CGUIDialogSimpleMenu::ShowPlaySelection(), MUSIC_UTILS::ShowSelectArtTypeDialog(), PVR::CPVRGUIActionsChannels::StartChannelScan(), and CVideoLibraryRefreshingJob::Work().
SetButtonFocus()
void CGUIDialogSelect::SetButtonFocus (bool buttonFocus)
References m_focusToButton.
SetItems()
void CGUIDialogSelect::SetItems (const CFileItemList & items)
References m_vecList, m_viewControl, and CGUIViewControl::SetItems().
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::ChooseStackItemPartNumber(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), CGUIDialogVideoInfo::GetItemsForTag(), CGUIDialogVideoInfo::GetMoviesForSet(), CGUIDialogVideoInfo::GetSetForMovie(), CGUIDialogVideoInfo::LinkMovieToTvShow(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIControlListSetting::OnClick(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), anonymous_namespace{VideoStreamSelectHelper.cpp}::OpenSelectDialog(), anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::Select(), CGUIWindowAddonBrowser::SelectAddonID(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), CGUIDialogSimpleMenu::ShowPlaySelection(), MUSIC_UTILS::ShowSelectArtTypeDialog(), and PERIPHERALS::CGUIDialogPeripherals::UpdatePeripheralsSync().
SetMultiSelection()
void CGUIDialogSelect::SetMultiSelection (bool multiSelection)
References m_multiSelection.
Referenced by KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), CGUIDialogVideoInfo::GetItemsForTag(), CGUIDialogVideoInfo::GetMoviesForSet(), anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::InstantRecordingActionSelector(), XBMCAddon::xbmcgui::Dialog::multiselect(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIControlListSetting::OnClick(), ADDON::Interface_GUIDialogSelect::open_multi_select(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), anonymous_namespace{VideoStreamSelectHelper.cpp}::OpenSelectDialog(), anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::Select(), CGUIWindowAddonBrowser::SelectAddonID(), and CGUIDialogVisualisationPresetList::SetVisualisation().
SetSelected() [1/4]
void CGUIDialogSelect::SetSelected (const std::string & strSelectedLabel)
References index(), m_vecList, and SetSelected().
SetSelected() [2/4]
void CGUIDialogSelect::SetSelected (const std::vector< int > & selectedIndexes)
References SetSelected().
SetSelected() [3/4]
void CGUIDialogSelect::SetSelected (const std::vector< std::string > & selectedLabels)
References label, and SetSelected().
SetSelected() [4/4]
void CGUIDialogSelect::SetSelected (int iSelected)
References m_multiSelection, m_selectedItem, m_selectedItems, and m_vecList.
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), CGUIViewState::ChooseSortMethod(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), CGUIDialogVideoInfo::GetMoviesForSet(), CGUIDialogVideoInfo::GetSetForMovie(), CStereoscopicsManager::GetStereoModeByUserChoice(), XBMCAddon::xbmcgui::Dialog::multiselect(), CPlayerController::OnAction(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIDialogSmartPlaylistRule::OnField(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), CGUIDialogSmartPlaylistEditor::OnLimit(), CGUIDialogSmartPlaylistRule::OnOperator(), CGUIDialogSmartPlaylistEditor::OnOrder(), CGUIDialogLockSettings::OnSettingAction(), CGUIDialogContentSettings::OnSettingAction(), CGUIDialogVideoInfo::OnSetUserrating(), CGUIDialogSmartPlaylistEditor::OnType(), ADDON::Interface_GUIDialogSelect::open(), ADDON::Interface_GUIDialogSelect::open_multi_select(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::PreSelectAction(), XBMCAddon::xbmcgui::Dialog::select(), SetSelected(), SetSelected(), SetSelected(), CGUIDialogVisualisationPresetList::SetVisualisation(), CGUIDialogAddonSettings::ShowForMultipleInstances(), MUSIC_UTILS::ShowSelectRatingDialog(), and PERIPHERALS::CGUIDialogPeripherals::UpdatePeripheralsSync().
SetUseDetails()
void CGUIDialogSelect::SetUseDetails (bool useDetails)
References m_useDetails.
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), KODI::GAME::CGUIDialogSelectGameClient::GetDialog(), XBMCAddon::xbmcgui::Dialog::multiselect(), CGUIControlListSetting::OnClick(), CGUIDialogVideoInfo::OnSearch(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), anonymous_namespace{VideoStreamSelectHelper.cpp}::OpenSelectDialog(), XBMCAddon::xbmcgui::Dialog::select(), CGUIWindowAddonBrowser::SelectAddonID(), CGUIDialogVisualisationPresetList::SetVisualisation(), PERIPHERALS::CGUIDialogPeripherals::Show(), CGUIDialogAddonSettings::ShowForMultipleInstances(), CGUIDialogSimpleMenu::ShowPlaySelection(), and MUSIC_UTILS::ShowSelectArtTypeDialog().
Sort()
void CGUIDialogSelect::Sort (bool bSortOrder = true)
References m_vecList, SortByLabel, SortOrderAscending, and SortOrderDescending.
Referenced by CMusicDatabase::DeleteCDDBInfo(), and MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo().
Member Data Documentation
m_bButton2Enabled
bool CGUIDialogSelect::m_bButton2Enabled private
Referenced by EnableButton2(), EnableButton2(), OnInitWindow(), OnMessage(), and Reset().
m_bButton2Pressed
bool CGUIDialogSelect::m_bButton2Pressed private
Referenced by IsButton2Pressed(), OnMessage(), and Reset().
m_bButtonEnabled
bool CGUIDialogSelect::m_bButtonEnabled private
Referenced by EnableButton(), EnableButton(), OnInitWindow(), OnMessage(), and Reset().
m_bButtonPressed
bool CGUIDialogSelect::m_bButtonPressed private
Referenced by IsButtonPressed(), OnMessage(), and Reset().
m_button2Label
std::string CGUIDialogSelect::m_button2Label private
Referenced by EnableButton2(), EnableButton2(), and OnInitWindow().
m_buttonLabel
std::string CGUIDialogSelect::m_buttonLabel private
Referenced by EnableButton(), EnableButton(), and OnInitWindow().
m_focusToButton
bool CGUIDialogSelect::m_focusToButton {} private
Referenced by OnInitWindow(), Reset(), and SetButtonFocus().
m_multiSelection
bool CGUIDialogSelect::m_multiSelection private
Referenced by OnInitWindow(), OnMessage(), Reset(), SetMultiSelection(), and SetSelected().
m_selectedItem
CFileItemPtr CGUIDialogSelect::m_selectedItem protected
Referenced by GetSelectedFileItem(), OnBack(), OnInitWindow(), OnMessage(), Reset(), and SetSelected().
m_selectedItems
std::vector<int> CGUIDialogSelect::m_selectedItems private
Referenced by GetSelectedItem(), GetSelectedItems(), OnBack(), OnInitWindow(), OnMessage(), Reset(), and SetSelected().
m_useDetails
bool CGUIDialogSelect::m_useDetails private
Referenced by OnInitWindow(), OnMessage(), Reset(), and SetUseDetails().
m_vecList
std::unique_ptr<CFileItemList> CGUIDialogSelect::m_vecList protected
Referenced by Add(), Add(), OnBack(), OnInitWindow(), OnMessage(), Reset(), SetItems(), SetSelected(), SetSelected(), and Sort().
m_viewControl
CGUIViewControl CGUIDialogSelect::m_viewControl protected
Referenced by GetFirstFocusableControl(), OnDeinitWindow(), OnInitWindow(), OnMessage(), OnWindowLoaded(), OnWindowUnload(), and SetItems().
The documentation for this class was generated from the following files:
GUIDialogSelect.h
GUIDialogSelect.cpp