Kodi Documentation: CEmuFileWrapper Class Reference
CEmuFileWrapper Class Reference
#include <EmuFileWrapper.h>
Public Member Functions
CEmuFileWrapper ()
~CEmuFileWrapper ()
void CleanUp ()
EmuFileObject * RegisterFileObject (XFILE::CFile *pFile)
void UnRegisterFileObjectByDescriptor (int fd)
void UnRegisterFileObjectByStream (FILE *stream)
void LockFileObjectByDescriptor (int fd)
bool TryLockFileObjectByDescriptor (int fd)
void UnlockFileObjectByDescriptor (int fd)
EmuFileObject * GetFileObjectByDescriptor (int fd)
EmuFileObject * GetFileObjectByStream (FILE *stream)
XFILE::CFile * GetFileXbmcByDescriptor (int fd)
XFILE::CFile * GetFileXbmcByStream (FILE *stream)
FILE * GetStreamByDescriptor (int fd)
Static Public Member Functions
static int GetDescriptorByStream (FILE *stream)
static constexpr bool DescriptorIsEmulatedFile (int fd)
static bool StreamIsEmulatedFile (FILE *stream)
Private Attributes
EmuFileObject m_files [MAX_EMULATED_FILES]
CCriticalSection m_criticalSection
Constructor & Destructor Documentation
CEmuFileWrapper()
CEmuFileWrapper::CEmuFileWrapper ()
References m_files.
~CEmuFileWrapper()
CEmuFileWrapper::~CEmuFileWrapper ()
References CleanUp().
Member Function Documentation
CleanUp()
void CEmuFileWrapper::CleanUp ()
Only to be called when shutting down xbmc
References m_criticalSection, and m_files.
Referenced by ~CEmuFileWrapper().
DescriptorIsEmulatedFile()
static constexpr bool CEmuFileWrapper::DescriptorIsEmulatedFile (int fd) inline static constexpr
References FILE_WRAPPER_OFFSET, and MAX_EMULATED_FILES.
Referenced by dll_lseek(), and StreamIsEmulatedFile().
GetDescriptorByStream()
int CEmuFileWrapper::GetDescriptorByStream (FILE * stream) static
References stEmuFileObject::fd, FILE_WRAPPER_OFFSET, and MAX_EMULATED_FILES.
Referenced by dll_fclose(), dll_fileno(), dll_flockfile(), dll_fputc(), dll_fseek64(), dll_fsetpos(), dll_fsetpos64(), dll_ftrylockfile(), dll_funlockfile(), dll_open(), and dll_rewind().
GetFileObjectByDescriptor()
EmuFileObject * CEmuFileWrapper::GetFileObjectByDescriptor (int fd)
References FILE_WRAPPER_OFFSET, m_files, and MAX_EMULATED_FILES.
Referenced by dll_fdopen(), GetFileObjectByStream(), GetFileXbmcByDescriptor(), and GetStreamByDescriptor().
GetFileObjectByStream()
EmuFileObject * CEmuFileWrapper::GetFileObjectByStream (FILE * stream)
References stEmuFileObject::fd, and GetFileObjectByDescriptor().
GetFileXbmcByDescriptor()
XFILE::CFile * CEmuFileWrapper::GetFileXbmcByDescriptor (int fd)
References GetFileObjectByDescriptor().
Referenced by dll__commit(), dll_close(), dll_fstat(), dll_fstat64(), dll_fstati64(), dll_lseeki64(), dll_read(), dll_tell(), dll_telli64(), and dll_write().
GetFileXbmcByStream()
XFILE::CFile * CEmuFileWrapper::GetFileXbmcByStream (FILE * stream)
References stEmuFileObject::file_xbmc, and stEmuFileObject::used.
Referenced by dll_feof(), dll_ferror(), dll_fflush(), dll_fgetpos64(), dll_fgets(), dll_fread(), dll_ftell64(), dll_fwrite(), dll_getmntent(), and dll_vfprintf().
GetStreamByDescriptor()
FILE * CEmuFileWrapper::GetStreamByDescriptor (int fd)
References GetFileObjectByDescriptor().
Referenced by dll_fopen().
LockFileObjectByDescriptor()
void CEmuFileWrapper::LockFileObjectByDescriptor (int fd)
References stEmuFileObject::file_lock, FILE_WRAPPER_OFFSET, m_files, and MAX_EMULATED_FILES.
Referenced by dll_flockfile().
RegisterFileObject()
EmuFileObject * CEmuFileWrapper::RegisterFileObject (XFILE::CFile * pFile)
References FILE_WRAPPER_OFFSET, m_criticalSection, m_files, MAX_EMULATED_FILES, and stEmuFileObject::used.
Referenced by dll_open().
StreamIsEmulatedFile()
bool CEmuFileWrapper::StreamIsEmulatedFile (FILE * stream) static
References DescriptorIsEmulatedFile(), and stEmuFileObject::fd.
Referenced by dll_clearerr(), dll_fgetc(), dll_fputc(), dll_fputs(), dll_freopen(), dll_getc(), dll_putc(), and dll_ungetc().
TryLockFileObjectByDescriptor()
bool CEmuFileWrapper::TryLockFileObjectByDescriptor (int fd)
References stEmuFileObject::file_lock, FILE_WRAPPER_OFFSET, m_files, and MAX_EMULATED_FILES.
Referenced by dll_ftrylockfile().
UnlockFileObjectByDescriptor()
void CEmuFileWrapper::UnlockFileObjectByDescriptor (int fd)
References stEmuFileObject::file_lock, FILE_WRAPPER_OFFSET, m_files, and MAX_EMULATED_FILES.
Referenced by dll_funlockfile().
UnRegisterFileObjectByDescriptor()
void CEmuFileWrapper::UnRegisterFileObjectByDescriptor (int fd)
References stEmuFileObject::fd, stEmuFileObject::file_lock, FILE_WRAPPER_OFFSET, m_criticalSection, m_files, MAX_EMULATED_FILES, and stEmuFileObject::used.
Referenced by dll_close(), and UnRegisterFileObjectByStream().
UnRegisterFileObjectByStream()
void CEmuFileWrapper::UnRegisterFileObjectByStream (FILE * stream)
References stEmuFileObject::fd, and UnRegisterFileObjectByDescriptor().
Member Data Documentation
m_criticalSection
CCriticalSection CEmuFileWrapper::m_criticalSection private
Referenced by CleanUp(), RegisterFileObject(), and UnRegisterFileObjectByDescriptor().
m_files
EmuFileObject CEmuFileWrapper::m_files[MAX_EMULATED_FILES] private
Referenced by CEmuFileWrapper(), CleanUp(), GetFileObjectByDescriptor(), LockFileObjectByDescriptor(), RegisterFileObject(), TryLockFileObjectByDescriptor(), UnlockFileObjectByDescriptor(), and UnRegisterFileObjectByDescriptor().
The documentation for this class was generated from the following files:
EmuFileWrapper.h
EmuFileWrapper.cpp