Kodi Documentation: CGUIColorManager Class Reference
CGUIColorManager Class Reference
#include <GUIColorManager.h>
Public Member Functions
CGUIColorManager (void)
virtual ~CGUIColorManager (void)
void Load (const std::string &colorFile)
KODI::UTILS::COLOR::Color GetColor (const std::string &color) const
void Clear ()
bool LoadColorsListFromXML (const std::string &filePath, std::vector< std::pair< std::string, KODI::UTILS::COLOR::ColorInfo > > &colors, bool sortColors)
Load a colors list from a XML file.
Protected Member Functions
bool LoadXML (CXBMCTinyXML &xmlDoc)
Protected Attributes
std::map< std::string, KODI::UTILS::COLOR::Color > m_colors
Constructor & Destructor Documentation
CGUIColorManager()
CGUIColorManager::CGUIColorManager (void) default
~CGUIColorManager()
CGUIColorManager::~CGUIColorManager (void) virtual
References Clear().
Member Function Documentation
Clear()
void CGUIColorManager::Clear ()
References m_colors.
Referenced by Load(), CApplicationSkinHandling::UnloadSkin(), and ~CGUIColorManager().
GetColor()
KODI::UTILS::COLOR::Color CGUIColorManager::GetColor (const std::string & color) const
References color, m_colors, and value.
Referenced by CGUIControlFactory::GetColor(), KODI::GUILIB::GUIINFO::CGUIInfoColor::Parse(), CGUITextLayout::ParseText(), and KODI::GUILIB::GUIINFO::CGUIInfoColor::Update().
Load()
void CGUIColorManager::Load (const std::string & colorFile)
References URIUtils::AddFileToFolder(), Clear(), g_SkinInfo, URIUtils::HasExtension(), CXBMCTinyXML::LoadFile(), LoadXML(), CLog::Log(), LOGINFO, and CSpecialProtocol::TranslatePathConvertCase().
Referenced by CApplicationSkinHandling::LoadSkin().
LoadColorsListFromXML()
bool CGUIColorManager::LoadColorsListFromXML (const std::string & filePath, std::vector< std::pair< std::string, KODI::UTILS::COLOR::ColorInfo > > & colors, bool sortColors)
Load a colors list from a XML file.
Parameters
filePath The path to the XML file
colors The vector to populate
sortColors if true the colors will be sorted in a hue scale
Returns
true if success, otherwise false
References KODI::UTILS::COLOR::comparePairColorInfo(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGDEBUG, LOGERROR, and KODI::UTILS::COLOR::MakeColorInfo().
Referenced by CWebVTTHandler::LoadColors(), and CGUIDialogColorPicker::LoadColors().
LoadXML()
bool CGUIColorManager::LoadXML (CXBMCTinyXML & xmlDoc) protected
References color, CLog::Log(), LOGERROR, m_colors, name, and value.
Referenced by Load().
Member Data Documentation
m_colors
std::map<std::string, KODI::UTILS::COLOR::Color> CGUIColorManager::m_colors protected
Referenced by Clear(), GetColor(), and LoadXML().
The documentation for this class was generated from the following files:
GUIColorManager.h
GUIColorManager.cpp