Kodi Documentation: KODI::VIDEO::GUILIB Namespace Reference
KODI::VIDEO::GUILIB Namespace Reference
Namespaces
namespace anonymous_namespace{VideoVersionHelper.cpp}
Classes
class CVideoPlayActionProcessorBase
class CVideoSelectActionProcessorBase
class CVideoVersionHelper
Enumerations
enum Action {
ACTION_CHOOSE = 0 , ACTION_PLAY_OR_RESUME = 1 , ACTION_RESUME = 2 , ACTION_INFO = 3 ,
ACTION_PLAY_FROM_BEGINNING = 5 , ACTION_PLAYPART = 6 , ACTION_QUEUE = 7
}
Functions
void OpenDialogSelectVideoStream ()
Open dialog window to select/change video stream.
void OpenDialogSelectAudioStream ()
Open dialog window to select/change audio stream.
void OpenDialogSelectSubtitleStream ()
Open dialog window to select/change subtitle stream.
Enumeration Type Documentation
Action
enum KODI::VIDEO::GUILIB::Action
Enumerator
ACTION_CHOOSE
ACTION_PLAY_OR_RESUME
ACTION_RESUME
ACTION_INFO
ACTION_PLAY_FROM_BEGINNING
ACTION_PLAYPART
ACTION_QUEUE
Function Documentation
OpenDialogSelectAudioStream()
void KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream ()
Open dialog window to select/change audio stream.
References CFileItemList::Add(), CServiceBroker::GetAppComponents(), CApplicationPlayer::GetAudioCapabilities(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CFileItemList::IsEmpty(), LOGERROR, anonymous_namespace{VideoStreamSelectHelper.cpp}::MakeFileItemNone(), anonymous_namespace{VideoStreamSelectHelper.cpp}::OpenSelectDialog(), CFileItemList::Reserve(), SELECT_STREAM, anonymous_namespace{VideoStreamSelectHelper.cpp}::STREAM_ID_NONE, anonymous_namespace{VideoStreamSelectHelper.cpp}::SupportsAudioFeature(), and WINDOW_DIALOG_SELECT_AUDIO_STREAM.
Referenced by CPlayerController::OnAction().
OpenDialogSelectSubtitleStream()
void KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream ()
Open dialog window to select/change subtitle stream.
References CFileItemList::Add(), CFileItemList::AddFront(), CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CApplicationPlayer::GetSubtitleCapabilities(), CGUIComponent::GetWindowManager(), CFileItemList::IsEmpty(), LOGERROR, anonymous_namespace{VideoStreamSelectHelper.cpp}::MakeFileItemDisable(), anonymous_namespace{VideoStreamSelectHelper.cpp}::MakeFileItemNone(), anonymous_namespace{VideoStreamSelectHelper.cpp}::OpenSelectDialog(), CFileItemList::Reserve(), SELECT_STREAM, anonymous_namespace{VideoStreamSelectHelper.cpp}::STREAM_ID_DISABLE, anonymous_namespace{VideoStreamSelectHelper.cpp}::STREAM_ID_NONE, anonymous_namespace{VideoStreamSelectHelper.cpp}::SupportsSubtitleFeature(), and WINDOW_DIALOG_SELECT_SUBTITLE_STREAM.
Referenced by CPlayerController::OnAction().
OpenDialogSelectVideoStream()
void KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream ()
Open dialog window to select/change video stream.
References CFileItemList::Add(), anonymous_namespace{VideoStreamSelectHelper.cpp}::ConvertFpsToString(), g_LangCodeExpander, CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CApplicationPlayer::GetVideoStreamCount(), CGUIComponent::GetWindowManager(), CStreamDetails::HdrTypeToString(), CFileItemList::IsEmpty(), LOGERROR, CLangCodeExpander::Lookup(), anonymous_namespace{VideoStreamSelectHelper.cpp}::MakeFileItemNone(), anonymous_namespace{VideoStreamSelectHelper.cpp}::OpenSelectDialog(), CFileItemList::Reserve(), anonymous_namespace{VideoStreamSelectHelper.cpp}::STREAM_ID_NONE, and WINDOW_DIALOG_SELECT_VIDEO_STREAM.
Referenced by CPlayerController::OnAction().