Kodi Documentation: CTVOSNSUserDefaults Class Reference
CTVOSNSUserDefaults Class Reference
#include <TVOSNSUserDefaults.h>
Static Public Member Functions
static bool Synchronize ()
static void GetDirectoryContents (const std::string &path, std::vector< std::string > &contents)
static bool GetKey (const std::string &key, std::string &value)
static bool GetKeyData (const std::string &key, void *lpBuf, size_t &uiBufSize)
static bool SetKey (const std::string &key, const std::string &value, bool synchronize)
static bool SetKeyData (const std::string &key, const void *lpBuf, size_t uiBufSize, bool synchronize)
static bool DeleteKey (const std::string &key, bool synchronize)
static bool KeyExists (const std::string &key)
static bool IsKeyFromPath (const std::string &key)
static bool GetKeyFromPath (const std::string &path, std::string &value)
static bool GetKeyDataFromPath (const std::string &path, void *lpBuf, size_t &uiBufSize)
static bool SetKeyFromPath (const std::string &path, const std::string &value, bool synchronize)
static bool SetKeyDataFromPath (const std::string &path, const void *lpBuf, size_t uiBufSize, bool synchronize)
static bool DeleteKeyFromPath (const std::string &path, bool synchronize)
static bool KeyFromPathExists (const std::string &path)
Member Function Documentation
DeleteKey()
bool CTVOSNSUserDefaults::DeleteKey (const std::string & key, bool synchronize) static
Referenced by DeleteKeyFromPath().
DeleteKeyFromPath()
bool CTVOSNSUserDefaults::DeleteKeyFromPath (const std::string & path, bool synchronize) static
References DeleteKey(), and translatePathIntoKey().
Referenced by XFILE::CTVOSFile::Delete().
GetDirectoryContents()
void CTVOSNSUserDefaults::GetDirectoryContents (const std::string & path, std::vector< std::string > & contents) static
References URIUtils::AddFileToFolder(), URIUtils::GetDirectory(), and CTVOSFileUtils::GetUserHomeDirectory().
Referenced by XFILE::CTVOSDirectory::GetDirectory().
GetKey()
bool CTVOSNSUserDefaults::GetKey (const std::string & key, std::string & value) static
References value.
Referenced by GetKeyFromPath().
GetKeyData()
bool CTVOSNSUserDefaults::GetKeyData (const std::string & key, void * lpBuf, size_t & uiBufSize) static
Referenced by GetKeyDataFromPath().
GetKeyDataFromPath()
bool CTVOSNSUserDefaults::GetKeyDataFromPath (const std::string & path, void * lpBuf, size_t & uiBufSize) static
References GetKeyData(), and translatePathIntoKey().
Referenced by XFILE::CTVOSFile::CacheStat(), XFILE::CTVOSFile::Read(), and XFILE::CTVOSFile::Rename().
GetKeyFromPath()
bool CTVOSNSUserDefaults::GetKeyFromPath (const std::string & path, std::string & value) static
References GetKey(), translatePathIntoKey(), and value.
IsKeyFromPath()
bool CTVOSNSUserDefaults::IsKeyFromPath (const std::string & key) static
References CLog::Log(), LOGDEBUG, and translatePathIntoKey().
Referenced by XFILE::CTVOSFile::WantsFile().
KeyExists()
bool CTVOSNSUserDefaults::KeyExists (const std::string & key) static
Referenced by KeyFromPathExists().
KeyFromPathExists()
bool CTVOSNSUserDefaults::KeyFromPathExists (const std::string & path) static
References KeyExists(), and translatePathIntoKey().
Referenced by XFILE::CTVOSFile::Exists(), XFILE::CTVOSFile::Open(), and XFILE::CTVOSFile::OpenForWrite().
SetKey()
bool CTVOSNSUserDefaults::SetKey (const std::string & key, const std::string & value, bool synchronize) static
References value.
Referenced by SetKeyFromPath().
SetKeyData()
bool CTVOSNSUserDefaults::SetKeyData (const std::string & key, const void * lpBuf, size_t uiBufSize, bool synchronize) static
References CLog::Log(), and LOGDEBUG.
Referenced by SetKeyDataFromPath().
SetKeyDataFromPath()
bool CTVOSNSUserDefaults::SetKeyDataFromPath (const std::string & path, const void * lpBuf, size_t uiBufSize, bool synchronize) static
References SetKeyData(), and translatePathIntoKey().
Referenced by XFILE::CTVOSFile::Rename(), and XFILE::CTVOSFile::Write().
SetKeyFromPath()
bool CTVOSNSUserDefaults::SetKeyFromPath (const std::string & path, const std::string & value, bool synchronize) static
References SetKey(), translatePathIntoKey(), and value.
Synchronize()
bool CTVOSNSUserDefaults::Synchronize () static
The documentation for this class was generated from the following files:
TVOSNSUserDefaults.h
TVOSNSUserDefaults.mm