Kodi Documentation: CXBMCApp Class Reference
CXBMCApp Class Reference
#include <XBMCApp.h>
Public Member Functions
CXBMCApp ()=delete
~CXBMCApp () override
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
void onReceive (CJNIIntent intent) override
void onNewIntent (CJNIIntent intent) override
void onActivityResult (int requestCode, int resultCode, CJNIIntent resultData) override
void onVolumeChanged (int volume) override
virtual void onAudioFocusChange (int focusChange)
void doFrame (int64_t frameTimeNanos) override
void onVisibleBehindCanceled () override
void onInputDeviceAdded (int deviceId) override
void onInputDeviceChanged (int deviceId) override
void onInputDeviceRemoved (int deviceId) override
void onDisplayAdded (int displayId) override
void onDisplayChanged (int displayId) override
void onDisplayRemoved (int displayId) override
jni::jhobject getDisplayListener ()
bool isValid ()
void onStart () override
void onResume () override
void onPause () override
void onStop () override
void onDestroy () override
void onSaveState (void **data, size_t *size) override
void onConfigurationChanged () override
void onLowMemory () override
void onCreateWindow (ANativeWindow *window) override
void onResizeWindow () override
void onDestroyWindow () override
void onGainFocus () override
void onLostFocus () override
void Initialize ()
void Deinitialize ()
bool Stop (int exitCode)
void Quit ()
std::shared_ptr< CNativeWindow > GetNativeWindow (int timeout) const
bool SetBuffersGeometry (int width, int height, int format)
int GetBatteryLevel () const
void KeepScreenOn (bool on)
bool HasFocus () const
std::vector< androidPackage > GetApplications () const
void SetDisplayMode (int mode, float rate)
int GetDPI () const
void SetVideoLayoutBackgroundColor (const int color)
CRect MapRenderToDroid (const CRect &srcRect)
void OnPlayBackStarted ()
void OnPlayBackPaused ()
void OnPlayBackStopped ()
void UpdateSessionMetadata ()
void UpdateSessionState ()
void RegisterInputDeviceCallbacks (IInputDeviceCallbacks *handler)
void UnregisterInputDeviceCallbacks ()
void RegisterInputDeviceEventHandler (IInputDeviceEventHandler *handler)
void UnregisterInputDeviceEventHandler ()
bool onInputDeviceEvent (const AInputEvent *event)
void InitFrameCallback (CVideoSyncAndroid *syncImpl)
void DeinitFrameCallback ()
void ProcessSlow ()
bool WaitVSync (unsigned int milliSeconds)
int64_t GetNextFrameTime () const
float GetFrameLatencyMs () const
bool getVideosurfaceInUse ()
void setVideosurfaceInUse (bool videosurfaceInUse)
void surfaceChanged (CJNISurfaceHolder holder, int format, int width, int height) override
void surfaceCreated (CJNISurfaceHolder holder) override
void surfaceDestroyed (CJNISurfaceHolder holder) override
Public Member Functions inherited from IActivityHandler
virtual ~IActivityHandler ()=default
Public Member Functions inherited from jni::CJNIMainActivity
CJNIMainActivity (const ANativeActivity *nativeActivity)
~CJNIMainActivity () override
CJNIRect getDisplayRect ()
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Static Public Member Functions
static CXBMCApp & Create (ANativeActivity *nativeActivity, IInputHandler &inputhandler)
static CXBMCApp & Get ()
static void Destroy ()
static int android_printf (const char *format,...)
static bool StartActivity (const std::string &package, const std::string &intent=std::string(), const std::string &dataType=std::string(), const std::string &dataURI=std::string(), const std::string &flags=std::string(), const std::string &extras=std::string(), const std::string &action=std::string(), const std::string &category=std::string(), const std::string &className=std::string())
static int GetMaxSystemVolume ()
static float GetSystemVolume ()
static void SetSystemVolume (float percent)
static const CJNIViewInputDevice GetInputDevice (int deviceId)
static std::vector< int > GetInputDeviceIds ()
Static Public Member Functions inherited from jni::CJNIMainActivity
static CJNIMainActivity * GetAppInstance ()
static void RegisterNatives (JNIEnv *env)
static void _onNewIntent (JNIEnv *env, jobject context, jobject intent)
static void _onActivityResult (JNIEnv *env, jobject context, jint requestCode, jint resultCode, jobject resultData)
static void _onVolumeChanged (JNIEnv *env, jobject context, jint volume)
static void _doFrame (JNIEnv *env, jobject context, jlong frameTimeNanos)
static void _onInputDeviceAdded (JNIEnv *env, jobject context, jint deviceId)
static void _onInputDeviceChanged (JNIEnv *env, jobject context, jint deviceId)
static void _onInputDeviceRemoved (JNIEnv *env, jobject context, jint deviceId)
static void _onVisibleBehindCanceled (JNIEnv *env, jobject context)
static void _callNative (JNIEnv *env, jobject context, jlong funcAddr, jlong variantAddr)
static void runNativeOnUiThread (void(*callback)(void *), void *variant)
static void registerMediaButtonEventReceiver ()
static void unregisterMediaButtonEventReceiver ()
Protected Member Functions
bool AcquireAudioFocus ()
bool ReleaseAudioFocus ()
void RequestVisibleBehind (bool requested)
Static Protected Member Functions
static int GetMaxSystemVolume (JNIEnv *env)
Private Member Functions
CXBMCApp (ANativeActivity *nativeActivity, IInputHandler &inputhandler)
std::string GetFilenameFromIntent (const CJNIIntent &intent)
void run ()
void stop ()
void SetupEnv ()
void UnregisterDisplayListener ()
bool XBMC_DestroyDisplay ()
bool XBMC_SetupDisplay ()
void OnSleep ()
void OnWakeup ()
Static Private Member Functions
static void SetDisplayModeCallback (void *modeVariant)
static void KeepScreenOnCallback (void *onVariant)
static void SetViewBackgroundColorCallback (void *mapVariant)
static void RegisterDisplayListenerCallback (void *)
Private Attributes
jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener m_audioFocusListener
jni::CJNIXBMCDisplayManagerDisplayListener m_displayListener
std::unique_ptr< jni::CJNIXBMCMainView > m_mainView
std::unique_ptr< jni::CJNIXBMCMediaSession > m_mediaSession
ANativeActivity * m_activity {nullptr}
IInputHandler & m_inputHandler
int m_batteryLevel {0}
bool m_hasFocus {false}
bool m_headsetPlugged {false}
bool m_hdmiSource {false}
bool m_wakeUp {false}
bool m_aeReset {false}
bool m_hdmiPlugged {true}
bool m_mediaSessionUpdated {false}
IInputDeviceCallbacks * m_inputDeviceCallbacks {nullptr}
IInputDeviceEventHandler * m_inputDeviceEventHandler {nullptr}
bool m_hasReqVisible {false}
bool m_firstrun {true}
std::atomic< bool > m_exiting {false}
int m_exitCode {0}
bool m_bResumePlayback {false}
std::thread m_thread
CCriticalSection m_applicationsMutex
std::vector< androidPackage > m_applications
std::shared_ptr< CNativeWindow > m_window
CVideoSyncAndroid * m_syncImpl {nullptr}
CEvent m_vsyncEvent
CEvent m_displayChangeEvent
uint32_t m_playback_state {0}
int64_t m_frameTimeNanos {0}
float m_refreshRate {0.0f}
Static Private Attributes
static std::unique_ptr< CXBMCApp > m_appinstance
Friends
class CAESinkAUDIOTRACK
Constructor & Destructor Documentation
CXBMCApp() [1/2]
CXBMCApp::CXBMCApp () delete
Referenced by Create().
~CXBMCApp()
CXBMCApp::~CXBMCApp () override
CXBMCApp() [2/2]
CXBMCApp::CXBMCApp (ANativeActivity * nativeActivity, IInputHandler & inputhandler) private
References android_printf(), m_activity, m_hdmiSource, and m_mainView.
Member Function Documentation
AcquireAudioFocus()
bool CXBMCApp::AcquireAudioFocus () protected
References android_printf(), and m_audioFocusListener.
Referenced by OnPlayBackStarted().
android_printf()
int CXBMCApp::android_printf (const char * format, ...) static
References CServiceBroker::IsLoggingUp(), CLog::Log(), and LOGDEBUG.
Referenced by AcquireAudioFocus(), android_main(), CXBMCApp(), GetMaxSystemVolume(), GetSystemVolume(), KeepScreenOn(), CAndroidMouse::MouseButton(), CAndroidMouse::MouseMove(), CAndroidMouse::MouseWheel(), onAudioFocusChange(), onConfigurationChanged(), onCreateWindow(), onDestroy(), onDestroyWindow(), onDisplayAdded(), onDisplayChanged(), onDisplayRemoved(), onGainFocus(), onInputDeviceAdded(), onInputDeviceChanged(), onInputDeviceRemoved(), CAndroidJoyStick::onJoyStickEvent(), CAndroidKey::onKeyboardEvent(), onLostFocus(), onLowMemory(), CAndroidMouse::onMouseEvent(), onPause(), onReceive(), onResizeWindow(), onResume(), onSaveState(), onStart(), onStop(), CAndroidTouch::onTouchEvent(), Quit(), RegisterDisplayListenerCallback(), ReleaseAudioFocus(), run(), CEventLoop::run(), SetSystemVolume(), surfaceChanged(), surfaceCreated(), surfaceDestroyed(), UnregisterDisplayListener(), XBMC_DestroyDisplay(), and XBMC_SetupDisplay().
Announce()
void CXBMCApp::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References ANNOUNCEMENT::CAnnouncementManager::ANNOUNCEMENT_SENDER, ANNOUNCEMENT::Info, ANNOUNCEMENT::Input, m_mediaSessionUpdated, OnPlayBackPaused(), OnPlayBackStarted(), OnPlayBackStopped(), ANNOUNCEMENT::Player, CAndroidKey::SetHandleSearchKeys(), UpdateSessionMetadata(), and UpdateSessionState().
Create()
static CXBMCApp & CXBMCApp::Create (ANativeActivity * nativeActivity, IInputHandler & inputhandler) inline static
References CXBMCApp(), and m_appinstance.
Referenced by android_main().
DeinitFrameCallback()
void CXBMCApp::DeinitFrameCallback ()
References m_syncImpl.
Referenced by CVideoSyncAndroid::Cleanup().
Deinitialize()
void CXBMCApp::Deinitialize ()
Referenced by XBMC_Run().
Destroy()
static void CXBMCApp::Destroy () inline static
References m_appinstance.
Referenced by android_main().
doFrame()
void CXBMCApp::doFrame (int64_t frameTimeNanos) override virtual
Implements jni::CJNIMainActivity.
References CVideoSyncAndroid::FrameCallback(), m_frameTimeNanos, m_syncImpl, m_vsyncEvent, and CEvent::Set().
Get()
static CXBMCApp & CXBMCApp::Get () inline static
References m_appinstance.
Referenced by jni::CJNIXBMCDisplayManagerDisplayListener::_onDisplayAdded(), jni::CJNIXBMCDisplayManagerDisplayListener::_onDisplayChanged(), jni::CJNIXBMCDisplayManagerDisplayListener::_onDisplayRemoved(), CAndroidPowerSyscall::BatteryLevel(), CVideoSyncAndroid::Cleanup(), PERIPHERALS::CPeripheralBusAndroid::CPeripheralBusAndroid(), speech::ISpeechRecognition::CreateInstance(), CWinSystemAndroid::CreateNewWindow(), XFILE::CFileAndroidApp::Exists(), ADDON::Interface_Android::get_sdk_version(), XFILE::CAndroidAppDirectory::GetDirectory(), CWinSystemAndroidGLESContext::GetFrameLatencyAdjustment(), CAndroidUtils::GetNativeResolution(), COSScreenSaverAndroid::Inhibit(), CPlatformAndroid::InitStageThree(), CWinSystemAndroid::Minimize(), jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener::onAudioFocusChange(), CAndroidJoyStick::onJoyStickEvent(), jni::CJNIXBMCMediaSession::OnMediaButtonEvent(), XFILE::CFileAndroidApp::Open(), CWinSystemAndroidGLESContext::PresentRenderImpl(), CEventLoop::processActivity(), CApplication::ProcessSlow(), RegisterDisplayListenerCallback(), CRendererMediaCodecSurface::ReleaseVideoBuffer(), CMediaCodecVideoBuffer::RenderUpdate(), SetDisplayModeCallback(), CAndroidUtils::SetNativeResolution(), CVideoSyncAndroid::Setup(), CApplication::Stop(), COSScreenSaverAndroid::Uninhibit(), XBMC_Run(), and PERIPHERALS::CPeripheralBusAndroid::~CPeripheralBusAndroid().
GetApplications()
std::vector< androidPackage > CXBMCApp::GetApplications () const
References androidPackage::icon, m_applications, m_applicationsMutex, androidPackage::packageLabel, and androidPackage::packageName.
Referenced by XFILE::CFileAndroidApp::Exists(), XFILE::CAndroidAppDirectory::GetDirectory(), and XFILE::CFileAndroidApp::Open().
GetBatteryLevel()
int CXBMCApp::GetBatteryLevel () const
References m_batteryLevel.
Referenced by CAndroidPowerSyscall::BatteryLevel().
getDisplayListener()
jni::jhobject CXBMCApp::getDisplayListener () inline
References m_displayListener.
Referenced by RegisterDisplayListenerCallback().
GetDPI()
int CXBMCApp::GetDPI () const
References m_activity.
Referenced by onDisplayChanged(), and onStart().
GetFilenameFromIntent()
std::string CXBMCApp::GetFilenameFromIntent (const CJNIIntent & intent) private
References data().
Referenced by onNewIntent().
GetFrameLatencyMs()
float CXBMCApp::GetFrameLatencyMs () const
References CurrentHostCounter(), and m_frameTimeNanos.
Referenced by CWinSystemAndroidGLESContext::GetFrameLatencyAdjustment().
GetInputDevice()
const CJNIViewInputDevice CXBMCApp::GetInputDevice (int deviceId) static
Referenced by PERIPHERALS::CPeripheralBusAndroid::GetInputDevices(), PERIPHERALS::CPeripheralBusAndroid::InitializeProperties(), PERIPHERALS::CPeripheralBusAndroid::OnInputDeviceAdded(), and PERIPHERALS::CPeripheralBusAndroid::OnInputDeviceChanged().
GetInputDeviceIds()
std::vector< int > CXBMCApp::GetInputDeviceIds () static
Referenced by PERIPHERALS::CPeripheralBusAndroid::GetInputDevices().
GetMaxSystemVolume() [1/2]
int CXBMCApp::GetMaxSystemVolume () static
References GetMaxSystemVolume().
Referenced by GetMaxSystemVolume(), GetSystemVolume(), CApplication::OnAction(), and SetSystemVolume().
GetMaxSystemVolume() [2/2]
int CXBMCApp::GetMaxSystemVolume (JNIEnv * env) static protected
References android_printf().
GetNativeWindow()
std::shared_ptr< CNativeWindow > CXBMCApp::GetNativeWindow (int timeout) const
References m_mainView, and m_window.
Referenced by CWinSystemAndroid::CreateNewWindow(), CAndroidUtils::GetNativeResolution(), and run().
GetNextFrameTime()
int64_t CXBMCApp::GetNextFrameTime () const
References int64_t(), m_frameTimeNanos, and m_refreshRate.
GetSystemVolume()
float CXBMCApp::GetSystemVolume () static
References android_printf(), and GetMaxSystemVolume().
getVideosurfaceInUse()
bool CXBMCApp::getVideosurfaceInUse ()
HasFocus()
bool CXBMCApp::HasFocus () const inline
References m_hasFocus.
Referenced by onReceive(), and OnWakeup().
InitFrameCallback()
void CXBMCApp::InitFrameCallback (CVideoSyncAndroid * syncImpl)
References m_syncImpl.
Referenced by CVideoSyncAndroid::Setup().
Initialize()
void CXBMCApp::Initialize ()
References CServiceBroker::GetAnnouncementManager(), ANNOUNCEMENT::Info, ANNOUNCEMENT::Input, and ANNOUNCEMENT::Player.
Referenced by XBMC_Run().
isValid()
bool CXBMCApp::isValid () inline
References m_activity.
Referenced by android_main().
KeepScreenOn()
void CXBMCApp::KeepScreenOn (bool on)
References android_printf(), KeepScreenOnCallback(), and jni::CJNIMainActivity::runNativeOnUiThread().
Referenced by COSScreenSaverAndroid::Inhibit(), onPause(), onResume(), and COSScreenSaverAndroid::Uninhibit().
KeepScreenOnCallback()
void CXBMCApp::KeepScreenOnCallback (void * onVariant) static private
References CVariant::asBoolean().
Referenced by KeepScreenOn().
MapRenderToDroid()
CRect CXBMCApp::MapRenderToDroid (const CRect & srcRect)
References jni::CJNIMainActivity::getDisplayRect(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CMediaCodecVideoBuffer::RenderUpdate().
onActivityResult()
void CXBMCApp::onActivityResult (int requestCode, int resultCode, CJNIIntent resultData) override virtual
Implements jni::CJNIMainActivity.
onAudioFocusChange()
void CXBMCApp::onAudioFocusChange (int focusChange) virtual
References ACTION_PAUSE, ACTION_STOP, android_printf(), CServiceBroker::GetAppMessenger(), m_playback_state, PLAYBACK_STATE_CANNOT_PAUSE, PLAYBACK_STATE_PLAYING, TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener::onAudioFocusChange().
onConfigurationChanged()
void CXBMCApp::onConfigurationChanged () override virtual
Reimplemented from IActivityHandler.
References android_printf().
onCreateWindow()
void CXBMCApp::onCreateWindow (ANativeWindow * window) override virtual
Reimplemented from IActivityHandler.
References android_printf().
onDestroy()
void CXBMCApp::onDestroy () override virtual
Reimplemented from IActivityHandler.
References android_printf(), CServiceBroker::GetAnnouncementManager(), m_mediaSession, and UnregisterDisplayListener().
onDestroyWindow()
void CXBMCApp::onDestroyWindow () override virtual
Reimplemented from IActivityHandler.
References android_printf().
onDisplayAdded()
void CXBMCApp::onDisplayAdded (int displayId) override virtual
Implements jni::CJNIMainActivity.
References android_printf().
Referenced by jni::CJNIXBMCDisplayManagerDisplayListener::_onDisplayAdded().
onDisplayChanged()
void CXBMCApp::onDisplayChanged (int displayId) override virtual
Implements jni::CJNIMainActivity.
References android_printf(), g_application, GetDPI(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, m_aeReset, m_displayChangeEvent, m_inputHandler, CEvent::Set(), IInputHandler::setDPI(), and CWinSystemAndroid::UpdateDisplayModes().
Referenced by jni::CJNIXBMCDisplayManagerDisplayListener::_onDisplayChanged().
onDisplayRemoved()
void CXBMCApp::onDisplayRemoved (int displayId) override virtual
Implements jni::CJNIMainActivity.
References android_printf().
Referenced by jni::CJNIXBMCDisplayManagerDisplayListener::_onDisplayRemoved().
onGainFocus()
void CXBMCApp::onGainFocus () override virtual
Reimplemented from IActivityHandler.
References android_printf(), CServiceBroker::GetAppComponents(), m_hasFocus, and CApplicationPowerHandling::WakeUpScreenSaverAndDPMS().
onInputDeviceAdded()
void CXBMCApp::onInputDeviceAdded (int deviceId) override
References android_printf(), m_inputDeviceCallbacks, and IInputDeviceCallbacks::OnInputDeviceAdded().
onInputDeviceChanged()
void CXBMCApp::onInputDeviceChanged (int deviceId) override
References android_printf(), m_inputDeviceCallbacks, and IInputDeviceCallbacks::OnInputDeviceChanged().
onInputDeviceEvent()
bool CXBMCApp::onInputDeviceEvent (const AInputEvent * event)
References m_inputDeviceEventHandler, and IInputDeviceEventHandler::OnInputDeviceEvent().
Referenced by CAndroidJoyStick::onJoyStickEvent().
onInputDeviceRemoved()
void CXBMCApp::onInputDeviceRemoved (int deviceId) override
References android_printf(), m_inputDeviceCallbacks, and IInputDeviceCallbacks::OnInputDeviceRemoved().
onLostFocus()
void CXBMCApp::onLostFocus () override virtual
Reimplemented from IActivityHandler.
References android_printf(), and m_hasFocus.
onLowMemory()
void CXBMCApp::onLowMemory () override virtual
Reimplemented from IActivityHandler.
References android_printf().
onNewIntent()
void CXBMCApp::onNewIntent (CJNIIntent intent) override virtual
Implements jni::CJNIMainActivity.
References ACTION_PAUSE, ACTION_XBMC_RESUME, CURL::Get(), CServiceBroker::GetAppMessenger(), GetFilenameFromIntent(), CURL::GetOption(), CFileItem::GetPath(), CFileItem::GetVideoInfoTag(), XFILE::CVideoDatabaseFile::GetVideoTag(), CURL::IsProtocol(), KODI::VIDEO::IsVideoDb(), CLog::Log(), LOGDEBUG, LOGINFO, m_playback_state, CVideoInfoTag::m_strFileNameAndPath, PLAYBACK_STATE_PLAYING, PLAYBACK_STATE_STOPPED, PLAYBACK_STATE_VIDEO, RequestVisibleBehind(), CFileItem::SetPath(), TMSG_GUI_ACTION, TMSG_GUI_ACTIVATE_WINDOW, TMSG_MEDIA_PLAY, value, WINDOW_INVALID, WINDOW_MUSIC_NAV, and WINDOW_VIDEO_NAV.
onPause()
void CXBMCApp::onPause () override virtual
Reimplemented from IActivityHandler.
References ACTION_PAUSE, android_printf(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), KeepScreenOn(), m_bResumePlayback, m_hasReqVisible, CGUIWindowManager::SwitchToFullScreen(), TMSG_GUI_ACTION, and WINDOW_INVALID.
OnPlayBackPaused()
void CXBMCApp::OnPlayBackPaused ()
References CLog::Log(), LOGDEBUG, m_mediaSessionUpdated, m_playback_state, ReleaseAudioFocus(), RequestVisibleBehind(), and UpdateSessionState().
Referenced by Announce().
OnPlayBackStarted()
void CXBMCApp::OnPlayBackStarted ()
References AcquireAudioFocus(), ACTION_XBMC_RESUME, CServiceBroker::GetAppComponents(), CLog::Log(), LOGDEBUG, m_mediaSession, m_mediaSessionUpdated, m_playback_state, PLAYBACK_STATE_AUDIO, PLAYBACK_STATE_CANNOT_PAUSE, PLAYBACK_STATE_PLAYING, PLAYBACK_STATE_VIDEO, RequestVisibleBehind(), CAndroidKey::SetHandleMediaKeys(), and UpdateSessionState().
Referenced by Announce().
OnPlayBackStopped()
void CXBMCApp::OnPlayBackStopped ()
References CLog::Log(), LOGDEBUG, m_mediaSession, m_mediaSessionUpdated, m_playback_state, PLAYBACK_STATE_STOPPED, ReleaseAudioFocus(), RequestVisibleBehind(), CAndroidKey::SetHandleMediaKeys(), and UpdateSessionState().
Referenced by Announce().
onReceive()
void CXBMCApp::onReceive (CJNIIntent intent) override
References ACTION_PAUSE, ACTION_STOP, android_printf(), IAE::DeviceChange(), g_application, CServiceBroker::GetActiveAE(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetWinSystem(), HasFocus(), CLog::Log(), LOGINFO, m_aeReset, m_batteryLevel, m_hdmiPlugged, m_headsetPlugged, m_playback_state, m_wakeUp, OnSleep(), OnWakeup(), PLAYBACK_STATE_PLAYING, PLAYBACK_STATE_STOPPED, TMSG_GUI_ACTION, CApplicationPowerHandling::WakeUpScreenSaverAndDPMS(), WINDOW_INVALID, CAndroidKey::XBMC_Key(), XBMCK_EJECT, XBMCK_MEDIA_FASTFORWARD, XBMCK_MEDIA_NEXT_TRACK, XBMCK_MEDIA_PLAY_PAUSE, XBMCK_MEDIA_PREV_TRACK, XBMCK_MEDIA_REWIND, XBMCK_MEDIA_STOP, and XBMCK_RECORD.
Referenced by jni::CJNIXBMCMediaSession::OnMediaButtonEvent().
onResizeWindow()
void CXBMCApp::onResizeWindow () override virtual
Reimplemented from IActivityHandler.
References android_printf(), and m_window.
onResume()
void CXBMCApp::onResume () override virtual
Reimplemented from IActivityHandler.
References ACTION_PLAYER_PLAY, android_printf(), g_application, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CWinSystemBase::GetOSScreenSaver(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), KODI::WINDOWING::COSScreenSaverManager::IsInhibited(), KeepScreenOn(), m_applications, m_applicationsMutex, m_bResumePlayback, m_headsetPlugged, m_playback_state, PLAYBACK_STATE_PLAYING, PLAYBACK_STATE_VIDEO, RequestVisibleBehind(), CApplicationPowerHandling::ResetShutdownTimers(), CSettings::SETTING_POWERMANAGEMENT_SHUTDOWNTIME, TMSG_GUI_ACTION, and WINDOW_INVALID.
onSaveState()
void CXBMCApp::onSaveState (void ** data, size_t * size) override virtual
Reimplemented from IActivityHandler.
References android_printf().
OnSleep()
void CXBMCApp::OnSleep () private
References CServiceBroker::GetPowerManager(), CPowerManager::GetPowerSyscall(), CLog::Log(), and LOGDEBUG.
Referenced by onReceive().
onStart()
void CXBMCApp::onStart () override virtual
Reimplemented from IActivityHandler.
References android_printf(), AE::CAESinkFactory::ClearSinks(), GetDPI(), m_firstrun, m_hdmiSource, m_inputHandler, m_mediaSession, m_thread, CAESinkAUDIOTRACK::Register(), RegisterDisplayListenerCallback(), run(), jni::CJNIMainActivity::runNativeOnUiThread(), and IInputHandler::setDPI().
onStop()
void CXBMCApp::onStop () override virtual
Reimplemented from IActivityHandler.
References ACTION_PAUSE, ACTION_STOP, android_printf(), CServiceBroker::GetAppMessenger(), m_hasReqVisible, m_playback_state, PLAYBACK_STATE_CANNOT_PAUSE, PLAYBACK_STATE_PLAYING, PLAYBACK_STATE_VIDEO, TMSG_GUI_ACTION, and WINDOW_INVALID.
onVisibleBehindCanceled()
void CXBMCApp::onVisibleBehindCanceled () override virtual
Implements jni::CJNIMainActivity.
References ACTION_PAUSE, ACTION_STOP, CServiceBroker::GetAppMessenger(), CLog::Log(), LOGDEBUG, m_hasReqVisible, m_playback_state, PLAYBACK_STATE_CANNOT_PAUSE, PLAYBACK_STATE_PLAYING, PLAYBACK_STATE_VIDEO, TMSG_GUI_ACTION, and WINDOW_INVALID.
onVolumeChanged()
void CXBMCApp::onVolumeChanged (int volume) override virtual
Implements jni::CJNIMainActivity.
OnWakeup()
void CXBMCApp::OnWakeup () private
References CServiceBroker::GetAppComponents(), CServiceBroker::GetPowerManager(), CPowerManager::GetPowerSyscall(), HasFocus(), CLog::Log(), LOGDEBUG, and CApplicationPowerHandling::WakeUpScreenSaverAndDPMS().
Referenced by onReceive().
ProcessSlow()
void CXBMCApp::ProcessSlow ()
References m_mediaSession, m_mediaSessionUpdated, m_playback_state, PLAYBACK_STATE_PLAYING, and UpdateSessionState().
Referenced by CApplication::ProcessSlow().
Quit()
void CXBMCApp::Quit ()
References android_printf(), EXITCODE_POWERDOWN, EXITCODE_QUIT, EXITCODE_REBOOT, EXITCODE_RESTARTAPP, CServiceBroker::GetAppMessenger(), CLog::Log(), LOGINFO, LOGWARNING, m_exitCode, m_exiting, m_thread, TMSG_POWERDOWN, TMSG_QUIT, TMSG_RESTART, and TMSG_RESTARTAPP.
Referenced by android_main().
RegisterDisplayListenerCallback()
void CXBMCApp::RegisterDisplayListenerCallback (void *) static private
References android_printf(), Get(), and getDisplayListener().
Referenced by onStart().
RegisterInputDeviceCallbacks()
void CXBMCApp::RegisterInputDeviceCallbacks (IInputDeviceCallbacks * handler)
References m_inputDeviceCallbacks.
Referenced by PERIPHERALS::CPeripheralBusAndroid::CPeripheralBusAndroid().
RegisterInputDeviceEventHandler()
void CXBMCApp::RegisterInputDeviceEventHandler (IInputDeviceEventHandler * handler)
References m_inputDeviceEventHandler.
Referenced by PERIPHERALS::CPeripheralBusAndroid::CPeripheralBusAndroid().
ReleaseAudioFocus()
bool CXBMCApp::ReleaseAudioFocus () protected
References android_printf(), and m_audioFocusListener.
Referenced by OnPlayBackPaused(), and OnPlayBackStopped().
RequestVisibleBehind()
void CXBMCApp::RequestVisibleBehind (bool requested) protected
References CLog::Log(), LOGDEBUG, and m_hasReqVisible.
Referenced by onNewIntent(), OnPlayBackPaused(), OnPlayBackStarted(), OnPlayBackStopped(), and onResume().
run()
void CXBMCApp::run () private
References android_printf(), GetNativeWindow(), m_firstrun, CAppEnvironment::SetUp(), SetupEnv(), CAppEnvironment::TearDown(), and XBMC_Run().
Referenced by onStart().
SetBuffersGeometry()
bool CXBMCApp::SetBuffersGeometry (int width, int height, int format)
References m_window.
Referenced by CAndroidUtils::SetNativeResolution().
SetDisplayMode()
void CXBMCApp::SetDisplayMode (int mode, float rate)
References g_application, CServiceBroker::GetWinSystem(), m_displayChangeEvent, m_hdmiSource, m_refreshRate, CEvent::Reset(), jni::CJNIMainActivity::runNativeOnUiThread(), SetDisplayModeCallback(), and CEvent::Wait().
Referenced by CAndroidUtils::SetNativeResolution().
SetDisplayModeCallback()
void CXBMCApp::SetDisplayModeCallback (void * modeVariant) static private
References CVariant::asInteger(), Get(), m_displayChangeEvent, and CEvent::Set().
Referenced by SetDisplayMode().
SetSystemVolume()
void CXBMCApp::SetSystemVolume (float percent) static
References android_printf(), and GetMaxSystemVolume().
SetupEnv()
void CXBMCApp::SetupEnv () private
References CCompileInfo::GetAppName(), CCompileInfo::GetPackage(), and CCompileInfo::GetPythonVersion().
Referenced by run().
SetVideoLayoutBackgroundColor()
void CXBMCApp::SetVideoLayoutBackgroundColor (const int color)
References color, id, jni::CJNIMainActivity::runNativeOnUiThread(), SetViewBackgroundColorCallback(), and CVariant::VariantTypeObject.
Referenced by CPlatformAndroid::InitStageThree().
setVideosurfaceInUse()
void CXBMCApp::setVideosurfaceInUse (bool videosurfaceInUse)
SetViewBackgroundColorCallback()
void CXBMCApp::SetViewBackgroundColorCallback (void * mapVariant) static private
References CVariant::asInteger(), and color.
Referenced by SetVideoLayoutBackgroundColor().
StartActivity()
bool CXBMCApp::StartActivity (const std::string & package, const std::string & intent = std::string(), const std::string & dataType = std::string(), const std::string & dataURI = std::string(), const std::string & flags = std::string(), const std::string & extras = std::string(), const std::string & action = std::string(), const std::string & category = std::string(), const std::string & className = std::string()) static
References LOGDEBUG, and LOGERROR.
Referenced by CApplication::OnApplicationMessage(), and CGUIMediaWindow::OnClick().
stop()
void CXBMCApp::stop () private
Stop()
bool CXBMCApp::Stop (int exitCode)
References CLog::Log(), LOGINFO, m_activity, m_exitCode, and m_exiting.
surfaceChanged()
void CXBMCApp::surfaceChanged (CJNISurfaceHolder holder, int format, int width, int height) override
References android_printf().
surfaceCreated()
void CXBMCApp::surfaceCreated (CJNISurfaceHolder holder) override
References android_printf(), CNativeWindow::CreateFromSurface(), CServiceBroker::GetAppComponents(), m_firstrun, m_window, CApplicationPowerHandling::SetRenderGUI(), and XBMC_SetupDisplay().
surfaceDestroyed()
void CXBMCApp::surfaceDestroyed (CJNISurfaceHolder holder) override
References android_printf(), CServiceBroker::GetAppComponents(), m_exiting, m_window, CApplicationPowerHandling::SetRenderGUI(), and XBMC_DestroyDisplay().
UnregisterDisplayListener()
void CXBMCApp::UnregisterDisplayListener () private
References android_printf(), and m_displayListener.
Referenced by onDestroy().
UnregisterInputDeviceCallbacks()
void CXBMCApp::UnregisterInputDeviceCallbacks ()
References m_inputDeviceCallbacks.
Referenced by PERIPHERALS::CPeripheralBusAndroid::~CPeripheralBusAndroid().
UnregisterInputDeviceEventHandler()
void CXBMCApp::UnregisterInputDeviceEventHandler ()
References m_inputDeviceEventHandler.
Referenced by PERIPHERALS::CPeripheralBusAndroid::~CPeripheralBusAndroid().
UpdateSessionMetadata()
void CXBMCApp::UpdateSessionMetadata ()
References INFO::DEFAULT_CONTEXT, CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CGUIInfoManager::GetImage(), CGUIComponent::GetInfoManager(), CServiceBroker::GetTextureCache(), m_mediaSession, m_playback_state, MUSICPLAYER_ARTIST, MUSICPLAYER_COVER, PLAYBACK_STATE_AUDIO, PLAYBACK_STATE_VIDEO, PLAYER_TITLE, CSpecialProtocol::TranslatePath(), VIDEOPLAYER_COVER, VIDEOPLAYER_DIRECTOR, and VIDEOPLAYER_TAGLINE.
Referenced by Announce().
UpdateSessionState()
void CXBMCApp::UpdateSessionState ()
References CServiceBroker::GetAppComponents(), int64_t(), m_mediaSession, m_mediaSessionUpdated, m_playback_state, PLAYBACK_STATE_AUDIO, PLAYBACK_STATE_PLAYING, PLAYBACK_STATE_STOPPED, and PLAYBACK_STATE_VIDEO.
Referenced by Announce(), OnPlayBackPaused(), OnPlayBackStarted(), OnPlayBackStopped(), and ProcessSlow().
WaitVSync()
bool CXBMCApp::WaitVSync (unsigned int milliSeconds)
References m_vsyncEvent, and CEvent::Wait().
Referenced by CWinSystemAndroidGLESContext::PresentRenderImpl().
XBMC_DestroyDisplay()
bool CXBMCApp::XBMC_DestroyDisplay () private
References android_printf(), CServiceBroker::GetAppMessenger(), and TMSG_DISPLAY_DESTROY.
Referenced by surfaceDestroyed().
XBMC_SetupDisplay()
bool CXBMCApp::XBMC_SetupDisplay () private
References android_printf(), CServiceBroker::GetAppMessenger(), and TMSG_DISPLAY_SETUP.
Referenced by surfaceCreated().
Friends And Related Symbol Documentation
CAESinkAUDIOTRACK
friend class CAESinkAUDIOTRACK friend
Member Data Documentation
m_activity
ANativeActivity* CXBMCApp::m_activity {nullptr} private
Referenced by CXBMCApp(), GetDPI(), isValid(), and Stop().
m_aeReset
bool CXBMCApp::m_aeReset {false} private
Referenced by onDisplayChanged(), and onReceive().
m_appinstance
std::unique_ptr< CXBMCApp > CXBMCApp::m_appinstance static private
Referenced by Create(), Destroy(), and Get().
m_applications
std::vector<androidPackage> CXBMCApp::m_applications mutable private
Referenced by GetApplications(), and onResume().
m_applicationsMutex
CCriticalSection CXBMCApp::m_applicationsMutex mutable private
Referenced by GetApplications(), and onResume().
m_audioFocusListener
jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener CXBMCApp::m_audioFocusListener private
Referenced by AcquireAudioFocus(), and ReleaseAudioFocus().
m_batteryLevel
int CXBMCApp::m_batteryLevel {0} private
Referenced by GetBatteryLevel(), and onReceive().
m_bResumePlayback
bool CXBMCApp::m_bResumePlayback {false} private
Referenced by onPause(), and onResume().
m_displayChangeEvent
CEvent CXBMCApp::m_displayChangeEvent private
Referenced by onDisplayChanged(), SetDisplayMode(), and SetDisplayModeCallback().
m_displayListener
jni::CJNIXBMCDisplayManagerDisplayListener CXBMCApp::m_displayListener private
Referenced by getDisplayListener(), and UnregisterDisplayListener().
m_exitCode
int CXBMCApp::m_exitCode {0} private
Referenced by Quit(), and Stop().
m_exiting
std::atomic<bool> CXBMCApp::m_exiting {false} private
Referenced by Quit(), Stop(), and surfaceDestroyed().
m_firstrun
bool CXBMCApp::m_firstrun {true} private
Referenced by onStart(), run(), and surfaceCreated().
m_frameTimeNanos
int64_t CXBMCApp::m_frameTimeNanos {0} private
Referenced by doFrame(), GetFrameLatencyMs(), and GetNextFrameTime().
m_hasFocus
bool CXBMCApp::m_hasFocus {false} private
Referenced by HasFocus(), onGainFocus(), and onLostFocus().
m_hasReqVisible
bool CXBMCApp::m_hasReqVisible {false} private
Referenced by onPause(), onStop(), onVisibleBehindCanceled(), and RequestVisibleBehind().
m_hdmiPlugged
bool CXBMCApp::m_hdmiPlugged {true} private
Referenced by onReceive().
m_hdmiSource
bool CXBMCApp::m_hdmiSource {false} private
Referenced by CXBMCApp(), onStart(), and SetDisplayMode().
m_headsetPlugged
bool CXBMCApp::m_headsetPlugged {false} private
Referenced by onReceive(), and onResume().
m_inputDeviceCallbacks
IInputDeviceCallbacks* CXBMCApp::m_inputDeviceCallbacks {nullptr} private
Referenced by onInputDeviceAdded(), onInputDeviceChanged(), onInputDeviceRemoved(), RegisterInputDeviceCallbacks(), and UnregisterInputDeviceCallbacks().
m_inputDeviceEventHandler
IInputDeviceEventHandler* CXBMCApp::m_inputDeviceEventHandler {nullptr} private
Referenced by onInputDeviceEvent(), RegisterInputDeviceEventHandler(), and UnregisterInputDeviceEventHandler().
m_inputHandler
IInputHandler& CXBMCApp::m_inputHandler private
Referenced by onDisplayChanged(), and onStart().
m_mainView
std::unique_ptr<jni::CJNIXBMCMainView> CXBMCApp::m_mainView private
Referenced by CXBMCApp(), and GetNativeWindow().
m_mediaSession
std::unique_ptr<jni::CJNIXBMCMediaSession> CXBMCApp::m_mediaSession private
Referenced by onDestroy(), OnPlayBackStarted(), OnPlayBackStopped(), onStart(), ProcessSlow(), UpdateSessionMetadata(), and UpdateSessionState().
m_mediaSessionUpdated
bool CXBMCApp::m_mediaSessionUpdated {false} private
Referenced by Announce(), OnPlayBackPaused(), OnPlayBackStarted(), OnPlayBackStopped(), ProcessSlow(), and UpdateSessionState().
m_playback_state
uint32_t CXBMCApp::m_playback_state {0} private
Referenced by onAudioFocusChange(), onNewIntent(), OnPlayBackPaused(), OnPlayBackStarted(), OnPlayBackStopped(), onReceive(), onResume(), onStop(), onVisibleBehindCanceled(), ProcessSlow(), UpdateSessionMetadata(), and UpdateSessionState().
m_refreshRate
float CXBMCApp::m_refreshRate {0.0f} private
Referenced by GetNextFrameTime(), and SetDisplayMode().
m_syncImpl
CVideoSyncAndroid* CXBMCApp::m_syncImpl {nullptr} private
Referenced by DeinitFrameCallback(), doFrame(), and InitFrameCallback().
m_thread
std::thread CXBMCApp::m_thread private
Referenced by onStart(), and Quit().
m_vsyncEvent
CEvent CXBMCApp::m_vsyncEvent private
Referenced by doFrame(), and WaitVSync().
m_wakeUp
bool CXBMCApp::m_wakeUp {false} private
Referenced by onReceive().
m_window
std::shared_ptr<CNativeWindow> CXBMCApp::m_window private
Referenced by GetNativeWindow(), onResizeWindow(), SetBuffersGeometry(), surfaceCreated(), and surfaceDestroyed().
The documentation for this class was generated from the following files:
XBMCApp.h
XBMCApp.cpp