Kodi Documentation: TestWebServer Class Reference
TestWebServer Class Reference
Protected Member Functions
TestWebServer ()
~TestWebServer () override=default
void SetUp () override
void TearDown () override
void SetupMediaSources ()
void TearDownMediaSources ()
std::string GetUrl (const std::string &path)
std::string GetUrlOfTestFile (const std::string &testFile)
bool GetLastModifiedOfTestFile (const std::string &testFile, CDateTime &lastModified)
void CheckHtmlTestFileResponse (const CCurlFile &curl)
void CheckRangesTestFileResponse (const CCurlFile &curl, int httpStatus=MHD_HTTP_OK, bool empty=false)
void CheckRangesTestFileResponse (const CCurlFile &curl, const std::string &result, const CHttpRanges &ranges)
std::string GenerateRangeHeaderValue (unsigned int start, unsigned int end)
Protected Attributes
CWebServer webserver
CHTTPJsonRpcHandler m_jsonRpcHandler
CHTTPVfsHandler m_vfsHandler
std::string baseUrl
std::string sourcePath
uint16_t webserverPort
Constructor & Destructor Documentation
TestWebServer()
TestWebServer::TestWebServer () inline protected
References baseUrl, WEBSERVER_HOST, and webserverPort.
~TestWebServer()
TestWebServer::~TestWebServer () override protected default
Member Function Documentation
CheckHtmlTestFileResponse()
void TestWebServer::CheckHtmlTestFileResponse (const CCurlFile & curl) inline protected
References EXPECT_TRUE(), CDateTime::GetAsRFC1123DateTime(), XFILE::CCurlFile::GetHttpHeader(), GetLastModifiedOfTestFile(), CHttpHeader::GetMimeType(), CHttpHeader::GetValue(), CHttpHeader::GetValues(), and TEST_FILES_HTML.
CheckRangesTestFileResponse() [1/2]
void TestWebServer::CheckRangesTestFileResponse (const CCurlFile & curl, const std::string & result, const CHttpRanges & ranges) inline protected
References ASSERT_NE(), data(), EXPECT_EQ(), EXPECT_TRUE(), HttpRangeUtils::GenerateContentRangeHeaderValue(), CHttpRanges::Get(), CDateTime::GetAsRFC1123DateTime(), CHttpRanges::GetFirst(), CHttpRange::GetFirstPosition(), CHttpRanges::GetFirstPosition(), XFILE::CCurlFile::GetHttpHeader(), GetLastModifiedOfTestFile(), CHttpRange::GetLastPosition(), CHttpRanges::GetLastPosition(), CHttpRange::GetLength(), CHttpHeader::GetMimeType(), CHttpHeader::GetProtoLine(), CHttpHeader::GetValue(), CHttpHeader::GetValues(), CHttpRanges::IsEmpty(), CHttpHeader::Parse(), CHttpRanges::Size(), str2uint64(), TEST_FILES_DATA_RANGES, and TEST_FILES_RANGES.
CheckRangesTestFileResponse() [2/2]
void TestWebServer::CheckRangesTestFileResponse (const CCurlFile & curl, int httpStatus = MHD_HTTP_OK, bool empty = false) inline protected
References EXPECT_TRUE(), CDateTime::GetAsRFC1123DateTime(), XFILE::CCurlFile::GetHttpHeader(), GetLastModifiedOfTestFile(), CHttpHeader::GetMimeType(), CHttpHeader::GetProtoLine(), CHttpHeader::GetValue(), CHttpHeader::GetValues(), and TEST_FILES_RANGES.
GenerateRangeHeaderValue()
std::string TestWebServer::GenerateRangeHeaderValue (unsigned int start, unsigned int end) inline protected
References end().
GetLastModifiedOfTestFile()
bool TestWebServer::GetLastModifiedOfTestFile (const std::string & testFile, CDateTime & lastModified) inline protected
References __stat64, URIUtils::AddFileToFolder(), CDateTime::IsValid(), XFILE::READ_NO_CACHE, and sourcePath.
Referenced by CheckHtmlTestFileResponse(), CheckRangesTestFileResponse(), and CheckRangesTestFileResponse().
GetUrl()
std::string TestWebServer::GetUrl (const std::string & path) inline protected
References URIUtils::AddFileToFolder(), and baseUrl.
Referenced by GetUrlOfTestFile().
GetUrlOfTestFile()
std::string TestWebServer::GetUrlOfTestFile (const std::string & testFile) inline protected
References URIUtils::AddFileToFolder(), GetUrl(), and sourcePath.
SetUp()
void TestWebServer::SetUp () inline override protected
References m_jsonRpcHandler, m_vfsHandler, CWebServer::RegisterRequestHandler(), SetupMediaSources(), CWebServer::Start(), webserver, and webserverPort.
SetupMediaSources()
void TestWebServer::SetupMediaSources () inline protected
References CMediaSourceSettings::AddShare(), CMediaSourceSettings::GetInstance(), LOCK_MODE_EVERYONE, CMediaSource::m_allowSharing, CMediaSource::m_iDriveType, CMediaSource::m_ignore, CMediaSource::m_iLockMode, CMediaSource::SOURCE_TYPE_LOCAL, sourcePath, CMediaSource::strName, CMediaSource::strPath, and CMediaSource::vecPaths.
Referenced by SetUp().
TearDown()
void TestWebServer::TearDown () inline override protected
References CWebServer::IsStarted(), m_jsonRpcHandler, m_vfsHandler, CWebServer::Stop(), TearDownMediaSources(), CWebServer::UnregisterRequestHandler(), and webserver.
TearDownMediaSources()
void TestWebServer::TearDownMediaSources () inline protected
References CMediaSourceSettings::Clear(), and CMediaSourceSettings::GetInstance().
Referenced by TearDown().
Member Data Documentation
baseUrl
std::string TestWebServer::baseUrl protected
Referenced by GetUrl(), and TestWebServer().
m_jsonRpcHandler
CHTTPJsonRpcHandler TestWebServer::m_jsonRpcHandler protected
Referenced by SetUp(), and TearDown().
m_vfsHandler
CHTTPVfsHandler TestWebServer::m_vfsHandler protected
Referenced by SetUp(), and TearDown().
sourcePath
std::string TestWebServer::sourcePath protected
Referenced by GetLastModifiedOfTestFile(), GetUrlOfTestFile(), and SetupMediaSources().
webserver
CWebServer TestWebServer::webserver protected
Referenced by SetUp(), and TearDown().
webserverPort
uint16_t TestWebServer::webserverPort protected
Referenced by SetUp(), and TestWebServer().
The documentation for this class was generated from the following file:
TestWebServer.cpp