Kodi Documentation: kodi::addon::CInstanceAudioDecoder Class Reference
kodi::addon::CInstanceAudioDecoder Class Reference abstract
#include <AudioDecoder.h>
Public Member Functions
CInstanceAudioDecoder (const kodi::addon::IInstanceInfo &instance)
Audio decoder class constructor used to support multiple instance types.
virtual bool SupportsFile (const std::string &filename)
Checks addon support given file path.
virtual bool Init (const std::string &filename, unsigned int filecache, int &channels, int &samplerate, int &bitspersample, int64_t &totaltime, int &bitrate, AudioEngineDataFormat &format, std::vector< AudioEngineChannel > &channellist)=0
Initialize a decoder.
virtual int ReadPCM (uint8_t *buffer, size_t size, size_t &actualsize)=0
Produce some noise.
virtual int64_t Seek (int64_t time)
Seek in output stream.
virtual bool ReadTag (const std::string &file, kodi::addon::AudioDecoderInfoTag &tag)
Read tag of a file.
virtual int TrackCount (const std::string &file)
Get number of tracks in a file.
Public Member Functions inherited from kodi::addon::IAddonInstance
IAddonInstance (const kodi::addon::IInstanceInfo &instance)
virtual ~IAddonInstance ()=default
virtual ADDON_STATUS CreateInstance (const kodi::addon::IInstanceInfo &instance, KODI_ADDON_INSTANCE_HDL &hdl)
std::string GetInstanceAPIVersion () const
virtual ADDON_STATUS SetInstanceSetting (const std::string &settingName, const kodi::addon::CSettingValue &settingValue)
bool IsInstanceSettingUsingDefault (const std::string &settingName)
std::string GetInstanceUserPath (const std::string &append="")
bool CheckInstanceSettingString (const std::string &settingName, std::string &settingValue)
std::string GetInstanceSettingString (const std::string &settingName, const std::string &defaultValue="")
void SetInstanceSettingString (const std::string &settingName, const std::string &settingValue)
bool CheckInstanceSettingInt (const std::string &settingName, int &settingValue)
int GetInstanceSettingInt (const std::string &settingName, int defaultValue=0)
void SetInstanceSettingInt (const std::string &settingName, int settingValue)
bool CheckInstanceSettingBoolean (const std::string &settingName, bool &settingValue)
bool GetInstanceSettingBoolean (const std::string &settingName, bool defaultValue=false)
void SetInstanceSettingBoolean (const std::string &settingName, bool settingValue)
bool CheckInstanceSettingFloat (const std::string &settingName, float &settingValue)
float GetInstanceSettingFloat (const std::string &settingName, float defaultValue=0.0f)
void SetInstanceSettingFloat (const std::string &settingName, float settingValue)
template<typename enumType >
bool CheckInstanceSettingEnum (const std::string &settingName, enumType &settingValue)
template<typename enumType >
enumType GetInstanceSettingEnum (const std::string &settingName, enumType defaultValue=static_cast< enumType >(0))
template<typename enumType >
void SetInstanceSettingEnum (const std::string &settingName, enumType settingValue)
Static Public Member Functions
static std::string GetTrack (const std::string &name, const std::string &trackPath, int &track)
Static auxiliary function to read the track number used from the given path.
Private Member Functions
void SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT *instance)
Static Private Member Functions
static bool ADDON_supports_file (const KODI_ADDON_AUDIODECODER_HDL hdl, const char *file)
static bool ADDON_init (const KODI_ADDON_AUDIODECODER_HDL hdl, const char *file, unsigned int filecache, int *channels, int *samplerate, int *bitspersample, int64_t *totaltime, int *bitrate, AudioEngineDataFormat *format, enum AudioEngineChannel info[AUDIOENGINE_CH_MAX])
static int ADDON_read_pcm (const KODI_ADDON_AUDIODECODER_HDL hdl, uint8_t *buffer, size_t size, size_t *actualsize)
static int64_t ADDON_seek (const KODI_ADDON_AUDIODECODER_HDL hdl, int64_t time)
static bool ADDON_read_tag (const KODI_ADDON_AUDIODECODER_HDL hdl, const char *file, struct KODI_ADDON_AUDIODECODER_INFO_TAG *tag)
static int ADDON_track_count (const KODI_ADDON_AUDIODECODER_HDL hdl, const char *file)
Member Function Documentation
ADDON_init()
static bool kodi::addon::CInstanceAudioDecoder::ADDON_init (const KODI_ADDON_AUDIODECODER_HDL hdl, const char * file, unsigned int filecache, int * channels, int * samplerate, int * bitspersample, int64_t * totaltime, int * bitrate, AudioEngineDataFormat * format, enum AudioEngineChannel info[AUDIOENGINE_CH_MAX]) inline static private
References AUDIOENGINE_CH_NULL, and Init().
ADDON_read_pcm()
static int kodi::addon::CInstanceAudioDecoder::ADDON_read_pcm (const KODI_ADDON_AUDIODECODER_HDL hdl, uint8_t * buffer, size_t size, size_t * actualsize) inline static private
ADDON_read_tag()
static bool kodi::addon::CInstanceAudioDecoder::ADDON_read_tag (const KODI_ADDON_AUDIODECODER_HDL hdl, const char * file, struct KODI_ADDON_AUDIODECODER_INFO_TAG * tag) inline static private
References kodi::addon::AudioDecoderInfoTag::GetAlbum(), kodi::addon::AudioDecoderInfoTag::GetAlbumArtist(), kodi::addon::AudioDecoderInfoTag::GetArtist(), kodi::addon::AudioDecoderInfoTag::GetBitrate(), kodi::addon::AudioDecoderInfoTag::GetChannels(), kodi::addon::AudioDecoderInfoTag::GetComment(), kodi::addon::AudioDecoderInfoTag::GetCoverArtByMem(), kodi::addon::AudioDecoderInfoTag::GetCoverArtByPath(), kodi::addon::AudioDecoderInfoTag::GetDisc(), kodi::addon::AudioDecoderInfoTag::GetDiscSubtitle(), kodi::addon::AudioDecoderInfoTag::GetDiscTotal(), kodi::addon::AudioDecoderInfoTag::GetDuration(), kodi::addon::AudioDecoderInfoTag::GetGenre(), kodi::addon::AudioDecoderInfoTag::GetLyrics(), kodi::addon::AudioDecoderInfoTag::GetMediaType(), kodi::addon::AudioDecoderInfoTag::GetReleaseDate(), kodi::addon::AudioDecoderInfoTag::GetSamplerate(), kodi::addon::AudioDecoderInfoTag::GetTitle(), and kodi::addon::AudioDecoderInfoTag::GetTrack().
ADDON_seek()
static int64_t kodi::addon::CInstanceAudioDecoder::ADDON_seek (const KODI_ADDON_AUDIODECODER_HDL hdl, int64_t time) inline static private
References Seek().
ADDON_supports_file()
static bool kodi::addon::CInstanceAudioDecoder::ADDON_supports_file (const KODI_ADDON_AUDIODECODER_HDL hdl, const char * file) inline static private
ADDON_track_count()
static int kodi::addon::CInstanceAudioDecoder::ADDON_track_count (const KODI_ADDON_AUDIODECODER_HDL hdl, const char * file) inline static private
SetAddonStruct()
void kodi::addon::CInstanceAudioDecoder::SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT * instance) inline private
References KODI_ADDON_INSTANCE_STRUCT::audiodecoder, KODI_ADDON_INSTANCE_STRUCT::hdl, KodiToAddonFuncTable_AudioDecoder::init, KodiToAddonFuncTable_AudioDecoder::read_pcm, KodiToAddonFuncTable_AudioDecoder::read_tag, KodiToAddonFuncTable_AudioDecoder::seek, KodiToAddonFuncTable_AudioDecoder::supports_file, AddonInstance_AudioDecoder::toAddon, and KodiToAddonFuncTable_AudioDecoder::track_count.
The documentation for this class was generated from the following file:
addons/kodi-dev-kit/include/kodi/addon-instance/AudioDecoder.h