Kodi Documentation: CLabelFormatter Class Reference
CLabelFormatter Class Reference
#include <LabelFormatter.h>
Classes
class CMaskString
Public Member Functions
CLabelFormatter (const std::string &mask, const std::string &mask2)
void FormatLabel (CFileItem *item) const
void FormatLabel2 (CFileItem *item) const
void FormatLabels (CFileItem *item) const
bool FillMusicTag (const std::string &fileName, MUSIC_INFO::CMusicInfoTag *tag) const
Private Member Functions
void AssembleMask (unsigned int label, const std::string &mask)
void SplitMask (unsigned int label, const std::string &mask)
std::string GetContent (unsigned int label, const CFileItem *item) const
std::string GetMaskContent (const CMaskString &mask, const CFileItem *item) const
void FillMusicMaskContent (const char mask, const std::string &value, MUSIC_INFO::CMusicInfoTag *tag) const
Private Attributes
std::vector< std::string > m_staticContent [2]
std::vector< CMaskString > m_dynamicContent [2]
bool m_hideFileExtensions
Constructor & Destructor Documentation
CLabelFormatter()
CLabelFormatter::CLabelFormatter (const std::string & mask, const std::string & mask2)
References AssembleMask(), CServiceBroker::GetSettingsComponent(), m_hideFileExtensions, and CSettings::SETTING_FILELISTS_SHOWEXTENSIONS.
Member Function Documentation
AssembleMask()
void CLabelFormatter::AssembleMask (unsigned int label, const std::string & mask) private
References CRegExp::GetFindLen(), CRegExp::GetMatch(), label, m_dynamicContent, m_staticContent, MASK_CHARS, CRegExp::RegComp(), CRegExp::RegFind(), and SplitMask().
Referenced by CLabelFormatter().
FillMusicMaskContent()
void CLabelFormatter::FillMusicMaskContent (const char mask, const std::string & value, MUSIC_INFO::CMusicInfoTag * tag) const private
References value.
Referenced by FillMusicTag().
FillMusicTag()
bool CLabelFormatter::FillMusicTag (const std::string & fileName, MUSIC_INFO::CMusicInfoTag * tag) const
References FillMusicMaskContent(), m_dynamicContent, and m_staticContent.
Referenced by CFileItem::LoadMusicTag().
FormatLabel()
void CLabelFormatter::FormatLabel (CFileItem * item) const
References GetContent(), CGUIListItem::m_bIsFolder, m_hideFileExtensions, CFileItem::RemoveExtension(), and CFileItem::SetLabel().
Referenced by FormatLabels(), CVideoDatabase::GetEpisodesByWhere(), KODI::CDRIP::CCDDARipper::GetTrackName(), and TEST_F().
FormatLabel2()
void CLabelFormatter::FormatLabel2 (CFileItem * item) const
References GetContent(), and CGUIListItem::SetLabel2().
Referenced by FormatLabels(), and TEST_F().
FormatLabels()
void CLabelFormatter::FormatLabels (CFileItem * item) const inline
References FormatLabel(), and FormatLabel2().
Referenced by CGUIMediaWindow::FormatItemLabels(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), and CGUIWindowMusicPlayList::OnItemLoaded().
GetContent()
std::string CLabelFormatter::GetContent (unsigned int label, const CFileItem * item) const private
References GetMaskContent(), label, m_dynamicContent, and m_staticContent.
Referenced by FormatLabel(), and FormatLabel2().
GetMaskContent()
std::string CLabelFormatter::GetMaskContent (const CMaskString & mask, const CFileItem * item) const private
References CVariant::asString(), g_localizeStrings, CLocalizeStrings::Get(), CFileItem::GetAddonInfo(), MUSIC_INFO::CMusicInfoTag::GetAlbum(), MUSIC_INFO::CMusicInfoTag::GetArtistString(), CDateTime::GetAsLocalizedDate(), CDateTime::GetAsLocalizedDateTime(), CDateTime::GetAsLocalizedTime(), MUSIC_INFO::CMusicInfoTag::GetBPM(), MUSIC_INFO::CMusicInfoTag::GetDateAdded(), CPictureInfoTag::GetDateTimeTaken(), MUSIC_INFO::CMusicInfoTag::GetDiscNumber(), MUSIC_INFO::CMusicInfoTag::GetDuration(), CVideoInfoTag::GetDuration(), URIUtils::GetFileName(), MUSIC_INFO::CMusicInfoTag::GetGenre(), CGUIListItem::GetLabel(), MUSIC_INFO::CMusicInfoTag::GetLastPlayed(), MUSIC_INFO::CMusicInfoTag::GetListeners(), CFileItem::GetMusicInfoTag(), MUSIC_INFO::CMusicInfoTag::GetOriginalDate(), CFileItem::GetPath(), CFileItem::GetPictureInfoTag(), MUSIC_INFO::CMusicInfoTag::GetPlayCount(), CVideoInfoTag::GetPlayCount(), CGUIListItem::GetProperty(), MUSIC_INFO::CMusicInfoTag::GetRating(), CVideoInfoTag::GetRating(), CServiceBroker::GetSettingsComponent(), MUSIC_INFO::CMusicInfoTag::GetTitle(), CUtil::GetTitleFromPath(), MUSIC_INFO::CMusicInfoTag::GetTotalDiscs(), MUSIC_INFO::CMusicInfoTag::GetTrackNumber(), MUSIC_INFO::CMusicInfoTag::GetUserrating(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::GetYear(), MUSIC_INFO::CMusicInfoTag::GetYearString(), CFileItem::HasAddonInfo(), CGUIListItem::HasProperty(), CVideoInfoTag::HasYear(), CFileItem::IsFileFolder(), CDateTime::IsValid(), CVideoInfoTag::m_artist, CGUIListItem::m_bIsFolder, CLabelFormatter::CMaskString::m_content, CVideoInfoTag::m_dateAdded, CFileItem::m_dateTime, CFileItem::m_dwSize, CVideoInfoTag::m_firstAired, CVideoInfoTag::m_genre, CVideoInfoTag::m_iEpisode, CFileItem::m_iprogramCount, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_iTrack, CVideoInfoTag::m_iUserRating, CVideoInfoTag::m_lastPlayed, CLabelFormatter::CMaskString::m_postfix, CLabelFormatter::CMaskString::m_prefix, CVideoInfoTag::m_relevance, CVideoInfoTag::m_strAlbum, CVideoInfoTag::m_strMPAARating, CVideoInfoTag::m_strProductionCode, CVideoInfoTag::m_strShowTitle, CFileItem::m_strTitle, CVideoInfoTag::m_strTitle, CVideoInfoTag::m_studio, CRating::rating, TIME_FORMAT_H_MM_SS, TIME_FORMAT_MM_SS, and value.
Referenced by GetContent().
SplitMask()
void CLabelFormatter::SplitMask (unsigned int label, const std::string & mask) private
References CRegExp::GetFindLen(), CRegExp::GetMatch(), label, m_dynamicContent, m_staticContent, MASK_CHARS, CRegExp::RegComp(), and CRegExp::RegFind().
Referenced by AssembleMask().
Member Data Documentation
m_dynamicContent
std::vector<CMaskString> CLabelFormatter::m_dynamicContent[2] private
Referenced by AssembleMask(), FillMusicTag(), GetContent(), and SplitMask().
m_hideFileExtensions
bool CLabelFormatter::m_hideFileExtensions private
Referenced by CLabelFormatter(), and FormatLabel().
m_staticContent
std::vector<std::string> CLabelFormatter::m_staticContent[2] private
Referenced by AssembleMask(), FillMusicTag(), GetContent(), and SplitMask().
The documentation for this class was generated from the following files:
LabelFormatter.h
LabelFormatter.cpp