Kodi Documentation: CLangCodeExpander Class Reference
CLangCodeExpander Class Reference
#include <LangCodeExpander.h>
Public Types
enum LANGFORMATS { ISO_639_1 , ISO_639_2 , ENGLISH_NAME }
enum class LANG_LIST { DEFAULT , INCLUDE_ADDONS , INCLUDE_USERDEFINED , INCLUDE_ADDONS_USERDEFINED }
Public Member Functions
CLangCodeExpander ()
~CLangCodeExpander ()
void LoadUserCodes (const TiXmlElement *pRootElement)
void Clear ()
bool Lookup (const std::string &code, std::string &desc)
bool Lookup (const int code, std::string &desc)
bool CompareFullLanguageNames (const std::string &lang1, const std::string &lang2)
Determines if two english language names represent the same language.
bool CompareISO639Codes (const std::string &code1, const std::string &code2)
Determines if two languages given as ISO 639-1, ISO 639-2/T, or ISO 639-2/B codes represent the same language.
bool ConvertToISO6391 (const std::string &lang, std::string &code)
Converts a language given as 2-Char (ISO 639-1), 3-Char (ISO 639-2/T or ISO 639-2/B), or full english name string to a 2-Char (ISO 639-1) code.
std::string ConvertToISO6392B (const std::string &lang)
Converts a language given as 2-Char (ISO 639-1), 3-Char (ISO 639-2/T or ISO 639-2/B), or full english name string to a 3-Char ISO 639-2/B code.
bool ConvertToISO6392B (const std::string &strCharCode, std::string &strISO6392B, bool checkWin32Locales=false)
Converts a language given as 2-Char (ISO 639-1), 3-Char (ISO 639-2/T or ISO 639-2/B), or full english name string to a 3-Char ISO 639-2/T code.
bool ConvertToISO6392T (const std::string &strCharCode, std::string &strISO6392T, bool checkWin32Locales=false)
Converts a language given as 2-Char (ISO 639-1), 3-Char (ISO 639-2/T or ISO 639-2/B), or full english name string to a 3-Char ISO 639-2/T code.
std::string ConvertToISO6392T (const std::string &lang)
Converts a language given as 2-Char (ISO 639-1), 3-Char (ISO 639-2/T or ISO 639-2/B), or full english name string to a 3-Char ISO 639-2/T code.
std::vector< std::string > GetLanguageNames (LANGFORMATS format=ISO_639_1, LANG_LIST list=LANG_LIST::DEFAULT)
Static Public Member Functions
static bool ConvertISO6391ToISO6392B (const std::string &strISO6391, std::string &strISO6392B, bool checkWin32Locales=false)
Converts a language given as 2-Char (ISO 639-1) to a 3-Char (ISO 639-2/T) code.
static std::string FindLanguageCodeWithSubtag (const std::string &str)
Protected Types
typedef std::map< std::string, std::string > STRINGLOOKUPTABLE
Protected Member Functions
bool LookupInUserMap (const std::string &code, std::string &desc)
bool ReverseLookup (const std::string &desc, std::string &code)
Looks up the ISO 639-1, ISO 639-2/T, or ISO 639-2/B, whichever it finds first, code of the given english language name.
bool LookupUserCode (const std::string &desc, std::string &userCode)
Looks up the user defined code of the given code or language name.
Static Protected Member Functions
static std::string CodeToString (long code)
static bool LookupInISO639Tables (const std::string &code, std::string &desc)
static bool LookupInLangAddons (const std::string &code, std::string &desc)
Protected Attributes
STRINGLOOKUPTABLE m_mapUser
Member Typedef Documentation
STRINGLOOKUPTABLE
typedef std::map<std::string, std::string> CLangCodeExpander::STRINGLOOKUPTABLE protected
Member Enumeration Documentation
LANG_LIST
enum class CLangCodeExpander::LANG_LIST strong
Enumerator
DEFAULT
INCLUDE_ADDONS
INCLUDE_USERDEFINED
INCLUDE_ADDONS_USERDEFINED
LANGFORMATS
enum CLangCodeExpander::LANGFORMATS
Enumerator
ISO_639_1
ISO_639_2
ENGLISH_NAME
Constructor & Destructor Documentation
CLangCodeExpander()
CLangCodeExpander::CLangCodeExpander () default
~CLangCodeExpander()
CLangCodeExpander::~CLangCodeExpander () default
Member Function Documentation
Clear()
void CLangCodeExpander::Clear ()
References m_mapUser.
Referenced by CApplication::Cleanup().
CodeToString()
std::string CLangCodeExpander::CodeToString (long code) static protected
Referenced by ConvertToISO6392B(), and ReverseLookup().
CompareFullLanguageNames()
bool CLangCodeExpander::CompareFullLanguageNames (const std::string & lang1, const std::string & lang2)
Determines if two english language names represent the same language.
Parameters
[in] lang1 The first language string to compare given as english language name.
[in] lang2 The second language string to compare given as english language name.
Returns
true if the two language strings represent the same language, false otherwise. For example "Abkhaz" and "Abkhazian" represent the same language.
References Lookup(), and ReverseLookup().
CompareISO639Codes()
bool CLangCodeExpander::CompareISO639Codes (const std::string & code1, const std::string & code2)
Determines if two languages given as ISO 639-1, ISO 639-2/T, or ISO 639-2/B codes represent the same language.
Parameters
[in] code1 The first language to compare given as ISO 639-1, ISO 639-2/T, or ISO 639-2/B code.
[in] code2 The second language to compare given as ISO 639-1, ISO 639-2/T, or ISO 639-2/B code.
Returns
true if the two language codes represent the same language, false otherwise. For example "ger", "deu" and "de" represent the same language.
References Lookup().
Referenced by CVideoPlayer::AdaptForcedSubtitles(), CStreamDetailSubtitle::IsWorseThan(), PredicateAudioFilter::operator()(), PredicateSubtitlePriority::operator()(), and PredicateSubtitleFilter::operator()().
ConvertISO6391ToISO6392B()
bool CLangCodeExpander::ConvertISO6391ToISO6392B (const std::string & strISO6391, std::string & strISO6392B, bool checkWin32Locales = false) static
Converts a language given as 2-Char (ISO 639-1) to a 3-Char (ISO 639-2/T) code.
Parameters
[in] strISO6391 The language that should be converted.
[out] strISO6392B The 3-Char (ISO 639-2/B) language code of the given language strISO6391.
[in] checkWin32Locales Whether to also check WIN32 specific language codes.
Returns
true if the conversion succeeded, false otherwise.
References LanguageCodes.
Referenced by ConvertToISO6392B(), CLangInfo::Load(), and TEST().
ConvertToISO6391()
bool CLangCodeExpander::ConvertToISO6391 (const std::string & lang, std::string & code)
Converts a language given as 2-Char (ISO 639-1), 3-Char (ISO 639-2/T or ISO 639-2/B), or full english name string to a 2-Char (ISO 639-1) code.
Parameters
[out] code The 2-Char language code of the given language lang.
[in] lang The language that should be converted.
Returns
true if the conversion succeeded, false otherwise.
References ConvertToISO6391(), LanguageCodes, Lookup(), LookupUserCode(), RegionCodes, and ReverseLookup().
Referenced by XBMCAddon::xbmc::convertLanguage(), ConvertToISO6391(), ConvertToISO6392B(), ConvertToISO6392T(), ADDON::Interface_General::get_language(), CLangInfo::GetDVDAudioLanguage(), CLangInfo::GetDVDMenuLanguage(), CLangInfo::GetDVDSubtitleLanguage(), XBMCAddon::xbmc::getLanguage(), CLangInfo::Load(), CGUIDialogSubtitles::OnDownloadComplete(), CLangInfo::CRegion::SetGlobalLocale(), and CDVDInputStreamBluray::SetupPlayerSettings().
ConvertToISO6392B() [1/2]
std::string CLangCodeExpander::ConvertToISO6392B (const std::string & lang)
Converts a language given as 2-Char (ISO 639-1), 3-Char (ISO 639-2/T or ISO 639-2/B), or full english name string to a 3-Char ISO 639-2/B code.
Parameters
[in] lang The language that should be converted.
Returns
The 3-Char ISO 639-2/B code of lang if that code exists, lang otherwise.
References ConvertToISO6391(), and ConvertToISO6392B().
Referenced by CDVDFileInfo::AddExternalSubtitleToDetails(), UPNP::BuildObject(), XBMCAddon::xbmc::convertLanguage(), ConvertToISO6392B(), ConvertToISO6392T(), ADDON::Interface_General::get_language(), CDVDInputStreamNavigator::GetAudioStreamInfo(), CUtil::GetExternalStreamDetailsFromFilename(), XBMCAddon::xbmc::getLanguage(), CDVDInputStreamNavigator::GetSubtitleStreamInfo(), CLangInfo::Load(), CLangInfo::SetAudioLanguage(), CLangInfo::SetSubtitleLanguage(), TEST(), and CSelectionStreams::Update().
ConvertToISO6392B() [2/2]
bool CLangCodeExpander::ConvertToISO6392B (const std::string & strCharCode, std::string & strISO6392B, bool checkWin32Locales = false)
Converts a language given as 2-Char (ISO 639-1), 3-Char (ISO 639-2/T or ISO 639-2/B), or full english name string to a 3-Char ISO 639-2/T code.
Parameters
[in] strCharCode The language that should be converted.
[out] strISO6392B The 3-Char (ISO 639-2/B) language code of the given language strISO6391.
[in] checkWin32Locales Whether to also check WIN32 specific language codes.
Returns
true if the conversion succeeded, false otherwise.
References CodeToString(), ConvertISO6391ToISO6392B(), g_iso639_2, g_LangCodeExpander, g_langInfo, LanguageCodes, LookupUserCode(), and RegionCodes.
ConvertToISO6392T() [1/2]
std::string CLangCodeExpander::ConvertToISO6392T (const std::string & lang)
Converts a language given as 2-Char (ISO 639-1), 3-Char (ISO 639-2/T or ISO 639-2/B), or full english name string to a 3-Char ISO 639-2/T code.
Parameters
[in] lang The language that should be converted.
Returns
The 3-Char ISO 639-2/T code of lang if that code exists, lang otherwise.
References ConvertToISO6391(), and ConvertToISO6392T().
ConvertToISO6392T() [2/2]
bool CLangCodeExpander::ConvertToISO6392T (const std::string & strCharCode, std::string & strISO6392T, bool checkWin32Locales = false)
Converts a language given as 2-Char (ISO 639-1), 3-Char (ISO 639-2/T or ISO 639-2/B), or full english name string to a 3-Char ISO 639-2/T code.
Parameters
[in] strCharCode The language that should be converted.
[out] strISO6392T The 3-Char (ISO 639-2/T) language code of the given language strISO6391.
[in] checkWin32Locales Whether to also check WIN32 specific language codes.
Returns
true if the conversion succeeded, false otherwise.
References ConvertToISO6392B(), and LanguageCodes.
Referenced by ConvertToISO6392T(), XFILE::CBlurayDirectory::InitializeBluray(), and CDVDInputStreamBluray::SetupPlayerSettings().
FindLanguageCodeWithSubtag()
std::string CLangCodeExpander::FindLanguageCodeWithSubtag (const std::string & str) static
References CRegExp::GetMatch(), CRegExp::RegComp(), and CRegExp::RegFind().
Referenced by CDVDDemuxFFmpeg::AddStream().
GetLanguageNames()
std::vector< std::string > CLangCodeExpander::GetLanguageNames (LANGFORMATS format = ISO_639_1, LANG_LIST list = LANG_LIST::DEFAULT)
References g_iso639_1, g_iso639_2, g_langInfo, INCLUDE_ADDONS, INCLUDE_ADDONS_USERDEFINED, INCLUDE_USERDEFINED, ISO_639_2, m_mapUser, and value.
Referenced by CLangInfo::AddLanguages(), and CLangInfo::SettingOptionsISO6391LanguagesFiller().
LoadUserCodes()
void CLangCodeExpander::LoadUserCodes (const TiXmlElement * pRootElement)
References m_mapUser.
Referenced by CAdvancedSettings::ParseSettingsFile().
Lookup() [1/2]
bool CLangCodeExpander::Lookup (const int code, std::string & desc)
References Lookup().
Lookup() [2/2]
bool CLangCodeExpander::Lookup (const std::string & code, std::string & desc)
References Lookup(), LookupInISO639Tables(), LookupInLangAddons(), and LookupInUserMap().
Referenced by anonymous_namespace{VideoStreamSelectHelper.cpp}::AudioStreamInfoExt::AudioStreamInfoExt(), CGUIDialogAudioSettings::AudioStreamsOptionFiller(), CompareFullLanguageNames(), CompareISO639Codes(), XBMCAddon::xbmc::convertLanguage(), ConvertToISO6391(), Lookup(), Lookup(), CPlayerController::OnAction(), KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream(), CGUIDialogSubtitles::Search(), anonymous_namespace{VideoStreamSelectHelper.cpp}::SubtitleStreamInfoExt::SubtitleStreamInfoExt(), CGUIDialogSubtitleSettings::SubtitleStreamsOptionFiller(), and CGUIDialogVideoSettings::VideoStreamsOptionFiller().
LookupInISO639Tables()
bool CLangCodeExpander::LookupInISO639Tables (const std::string & code, std::string & desc) static protected
References g_iso639_1, g_iso639_2, and MAKECODE.
Referenced by Lookup().
LookupInLangAddons()
bool CLangCodeExpander::LookupInLangAddons (const std::string & code, std::string & desc) static protected
References g_langInfo.
Referenced by Lookup().
LookupInUserMap()
bool CLangCodeExpander::LookupInUserMap (const std::string & code, std::string & desc) protected
References m_mapUser.
Referenced by Lookup().
LookupUserCode()
bool CLangCodeExpander::LookupUserCode (const std::string & desc, std::string & userCode) protected
Looks up the user defined code of the given code or language name.
Parameters
[in] desc The language code or name that should be converted.
[out] userCode The user defined language code of the given language desc.
Returns
true if desc was found, false otherwise.
References m_mapUser.
Referenced by ConvertToISO6391(), and ConvertToISO6392B().
ReverseLookup()
bool CLangCodeExpander::ReverseLookup (const std::string & desc, std::string & code) protected
Looks up the ISO 639-1, ISO 639-2/T, or ISO 639-2/B, whichever it finds first, code of the given english language name.
Parameters
[in] desc The english language name for which a code is looked for.
[out] code The ISO 639-1, ISO 639-2/T, or ISO 639-2/B code of the given language desc.
Returns
true if the a code was found, false otherwise.
References CodeToString(), g_iso639_1, g_iso639_2, g_langInfo, and m_mapUser.
Referenced by CompareFullLanguageNames(), and ConvertToISO6391().
Member Data Documentation
m_mapUser
STRINGLOOKUPTABLE CLangCodeExpander::m_mapUser protected
Referenced by Clear(), GetLanguageNames(), LoadUserCodes(), LookupInUserMap(), LookupUserCode(), and ReverseLookup().
The documentation for this class was generated from the following files:
LangCodeExpander.h
LangCodeExpander.cpp