Kodi Documentation: TestConversionMatrix.cpp File Reference
TestConversionMatrix.cpp File Reference
#include "cores/VideoPlayer/VideoRenderers/VideoShaders/ConversionMatrix.h"
#include "xbmc/utils/MathUtils.h"
#include <iomanip>
#include <iostream>
#include <gtest/gtest.h>
Namespaces
namespace anonymous_namespace{TestConversionMatrix.cpp}
Functions
void anonymous_namespace{TestConversionMatrix.cpp}::DebugPrint (const Matrix3 &matrix)
void anonymous_namespace{TestConversionMatrix.cpp}::DebugPrint (const Matrix4 &matrix)
template<uint8_t Order>
bool anonymous_namespace{TestConversionMatrix.cpp}::CompareMatrices (CMatrix< Order > &matrixA, CMatrix< Order > &matrixB, float threshold)
TEST (TestConvertMatrix, YUV2RGB)
TEST (TestConvertMatrix, ColorSpaceConversion)
Variables
constexpr bool anonymous_namespace{TestConversionMatrix.cpp}::DEBUG_PRINT {false}
std::array< std::array< float, 4 >, 4 > anonymous_namespace{TestConversionMatrix.cpp}::bt709_8bit
Matrix4 anonymous_namespace{TestConversionMatrix.cpp}::bt709Mat_8bit (bt709_8bit)
std::array< std::array< float, 4 >, 4 > anonymous_namespace{TestConversionMatrix.cpp}::bt709_10bit
Matrix4 anonymous_namespace{TestConversionMatrix.cpp}::bt709Mat_10bit (bt709_10bit)
std::array< std::array< float, 4 >, 4 > anonymous_namespace{TestConversionMatrix.cpp}::bt709_10bit_texture
Matrix4 anonymous_namespace{TestConversionMatrix.cpp}::bt709Mat_10bit_texture (bt709_10bit_texture)
std::array< std::array< float, 3 >, 3 > anonymous_namespace{TestConversionMatrix.cpp}::bt601_to_bt709
Matrix3 anonymous_namespace{TestConversionMatrix.cpp}::bt601_to_bt709_Mat (bt601_to_bt709)
std::array< std::array< float, 3 >, 3 > anonymous_namespace{TestConversionMatrix.cpp}::bt2020_to_bt709
Matrix3 anonymous_namespace{TestConversionMatrix.cpp}::bt2020_to_bt709_Mat (bt2020_to_bt709)
Function Documentation
TEST() [1/2]
TEST (TestConvertMatrix , ColorSpaceConversion)
References anonymous_namespace{TestConversionMatrix.cpp}::bt2020_to_bt709_Mat, anonymous_namespace{TestConversionMatrix.cpp}::bt601_to_bt709_Mat, anonymous_namespace{TestConversionMatrix.cpp}::CompareMatrices(), anonymous_namespace{TestConversionMatrix.cpp}::DebugPrint(), EXPECT_TRUE(), CConvertMatrix::GetPrimMat(), CConvertMatrix::SetDestinationColorPrimaries(), and CConvertMatrix::SetSourceColorPrimaries().
TEST() [2/2]
TEST (TestConvertMatrix , YUV2RGB)
References anonymous_namespace{TestConversionMatrix.cpp}::bt709Mat_10bit, anonymous_namespace{TestConversionMatrix.cpp}::bt709Mat_10bit_texture, anonymous_namespace{TestConversionMatrix.cpp}::bt709Mat_8bit, anonymous_namespace{TestConversionMatrix.cpp}::CompareMatrices(), anonymous_namespace{TestConversionMatrix.cpp}::DebugPrint(), EXPECT_TRUE(), CConvertMatrix::GetYuvMat(), CConvertMatrix::SetDestinationBlack(), CConvertMatrix::SetDestinationContrast(), CConvertMatrix::SetDestinationLimitedRange(), CConvertMatrix::SetSourceBitDepth(), CConvertMatrix::SetSourceColorSpace(), CConvertMatrix::SetSourceLimitedRange(), and CConvertMatrix::SetSourceTextureBitDepth().