Kodi Documentation: CSelectionStreams Class Reference
CSelectionStreams Class Reference
#include <VideoPlayer.h>
Public Member Functions
CSelectionStreams ()=default
int TypeIndexOf (StreamType type, int source, int64_t demuxerId, int id) const
int CountTypeOfSource (StreamType type, StreamSource source) const
int CountType (StreamType type) const
SelectionStream & Get (StreamType type, int index)
const SelectionStream & Get (StreamType type, int index) const
bool Get (StreamType type, StreamFlags flag, SelectionStream &out)
void Clear (StreamType type, StreamSource source)
int Source (StreamSource source, const std::string &filename)
void Update (SelectionStream &s)
void Update (const std::shared_ptr< CDVDInputStream > &input, CDVDDemux *demuxer)
void Update (const std::shared_ptr< CDVDInputStream > &input, CDVDDemux *demuxer, const std::string &filename2)
std::vector< SelectionStream > Get (StreamType type)
template<typename Compare >
std::vector< SelectionStream > Get (StreamType type, Compare compare)
Public Attributes
std::vector< SelectionStream > m_Streams
Protected Attributes
SelectionStream m_invalid
Constructor & Destructor Documentation
CSelectionStreams()
CSelectionStreams::CSelectionStreams () default
Member Function Documentation
Clear()
void CSelectionStreams::Clear (StreamType type, StreamSource source)
References m_Streams.
Referenced by CVideoPlayer::CheckStreamChanges(), CVideoPlayer::CloseDemuxer(), CVideoPlayer::HandleMessages(), CVideoPlayer::OnDiscNavResult(), CVideoPlayer::OnExit(), CVideoPlayer::OpenDemuxStream(), CVideoPlayer::OpenVideoStream(), CVideoPlayer::Process(), and CVideoPlayer::ReadPacket().
CountType()
int CSelectionStreams::CountType (StreamType type) const
References m_Streams.
Referenced by CVideoPlayer::GetAudioStreamCount(), CVideoPlayer::GetSubtitleCount(), CVideoPlayer::GetVideoStreamCount(), and Update().
CountTypeOfSource()
int CSelectionStreams::CountTypeOfSource (StreamType type, StreamSource source) const
References m_Streams.
Referenced by CVideoPlayer::Process().
Get() [1/5]
std::vector< SelectionStream > CSelectionStreams::Get (StreamType type)
References m_Streams.
Get() [2/5]
template<typename Compare > std::vector< SelectionStream > CSelectionStreams::Get (StreamType type, Compare compare) inline
References Get().
Get() [3/5]
SelectionStream & CSelectionStreams::Get (StreamType type, int index)
References index().
Referenced by CVideoPlayer::AdaptForcedSubtitles(), CVideoPlayer::AddSubtitleFile(), Get(), CVideoPlayer::GetAudioStreamInfo(), CVideoPlayer::GetSubtitleStreamInfo(), CVideoPlayer::GetVideoStreamInfo(), CVideoPlayer::HandleMessages(), CVideoPlayer::OpenDefaultStreams(), CVideoPlayer::OpenStream(), and Update().
Get() [4/5]
const SelectionStream & CSelectionStreams::Get (StreamType type, int index) const
References index(), m_invalid, and m_Streams.
Get() [5/5]
bool CSelectionStreams::Get (StreamType type, StreamFlags flag, SelectionStream & out)
References m_Streams.
Source()
int CSelectionStreams::Source (StreamSource source, const std::string & filename)
References SelectionStream::filename, index(), m_Streams, SelectionStream::source, and STREAM_SOURCE_MASK.
Referenced by CVideoPlayer::AddSubtitleFile(), and Update().
TypeIndexOf()
int CSelectionStreams::TypeIndexOf (StreamType type, int source, int64_t demuxerId, int id) const
References m_Streams.
Referenced by CVideoPlayer::AddSubtitleFile(), CVideoPlayer::OpenStream(), Update(), and CVideoPlayer::UpdateContentState().
Update() [1/3]
void CSelectionStreams::Update (const std::shared_ptr< CDVDInputStream > & input, CDVDDemux * demuxer)
References Update.
Update() [2/3]
void CSelectionStreams::Update (const std::shared_ptr< CDVDInputStream > & input, CDVDDemux * demuxer, const std::string & filename2)
References SelectionStream::aspect_ratio, SelectionStream::bitrate, SelectionStream::channels, SelectionStream::codec, SelectionStream::codecDesc, CLangCodeExpander::ConvertToISO6392B(), SelectionStream::demuxerId, DVDSTREAM_TYPE_DVD, CDemuxStreamVideo::fAspect, SelectionStream::filename, SelectionStream::filename2, FLAG_NONE, SelectionStream::flags, SelectionStream::fpsRate, SelectionStream::fpsScale, g_LangCodeExpander, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetDataCacheCore(), CDVDDemux::GetFileName(), CDVDDemux::GetStreamCodecName(), CDVDDemux::GetStreams(), CDemuxStreamVideo::hdr_type, SelectionStream::hdrType, SelectionStream::height, CDemuxStreamVideo::iBitRate, SelectionStream::id, CDemuxStreamVideo::iFpsRate, CDemuxStreamVideo::iFpsScale, CDemuxStreamVideo::iHeight, CDemuxStreamVideo::iWidth, SelectionStream::language, SelectionStream::name, CDataCacheCore::SignalAudioInfoChange(), CDataCacheCore::SignalSubtitleInfoChange(), CDataCacheCore::SignalVideoInfoChange(), SelectionStream::source, Source(), CDemuxStreamVideo::stereo_mode, SelectionStream::stereo_mode, STREAM_AUDIO, STREAM_NONE, STREAM_SOURCE_DEMUX, STREAM_SOURCE_DEMUX_SUB, STREAM_SOURCE_NAV, STREAM_SOURCE_VIDEOMUX, STREAM_SUBTITLE, STREAM_VIDEO, SelectionStream::type, Update, and SelectionStream::width.
Update() [3/3]
void CSelectionStreams::Update (SelectionStream & s)
References CountType(), SelectionStream::demuxerId, Get(), SelectionStream::id, index(), m_Streams, SelectionStream::source, SelectionStream::type, SelectionStream::type_index, and TypeIndexOf().
Referenced by CVideoPlayer::AddSubtitleFile(), CVideoPlayer::CheckStreamChanges(), CVideoPlayer::OnDiscNavResult(), CVideoPlayer::OpenDemuxStream(), CVideoPlayer::Process(), and CVideoPlayer::ReadPacket().
Member Data Documentation
m_invalid
SelectionStream CSelectionStreams::m_invalid protected
Referenced by Get().
m_Streams
std::vector<SelectionStream> CSelectionStreams::m_Streams
Referenced by Clear(), CountType(), CountTypeOfSource(), Get(), Get(), Get(), CVideoPlayer::OpenDefaultStreams(), CVideoPlayer::Process(), Source(), TypeIndexOf(), and Update().
The documentation for this class was generated from the following files:
VideoPlayer.h
VideoPlayer.cpp