Kodi Documentation: TestSharedSection.cpp File Reference
TestSharedSection.cpp File Reference
#include "threads/Event.h"
#include "threads/IRunnable.h"
#include "threads/SharedSection.h"
#include "threads/test/TestHelpers.h"
#include <mutex>
#include <shared_mutex>
#include <stdio.h>
Classes
class locker< L >
Functions
TEST (TestCritSection, General)
TEST (TestSharedSection, General)
TEST (TestSharedSection, GetSharedLockWhileTryingExclusiveLock)
TEST (TestSharedSection, TwoCase)
TEST (TestMultipleSharedSection, General)
Function Documentation
TEST() [1/5]
TEST (TestCritSection , General)
TEST() [2/5]
TEST (TestMultipleSharedSection , General)
References EXPECT_TRUE(), locker< L >::haslock, mutex, thread::timed_join(), waitForThread(), and waitForWaiters().
TEST() [3/5]
TEST (TestSharedSection , General)
TEST() [4/5]
TEST (TestSharedSection , GetSharedLockWhileTryingExclusiveLock)
References EXPECT_TRUE(), locker< L >::haslock, mutex, locker< L >::obtainedlock, thread::timed_join(), and waitForThread().
TEST() [5/5]
TEST (TestSharedSection , TwoCase)
References EXPECT_TRUE(), locker< L >::haslock, mutex, thread::timed_join(), waitForThread(), and waitForWaiters().