Kodi Documentation: XFILE::CSimpleFileCache Class Reference
XFILE::CSimpleFileCache Class Reference
#include <CacheStrategy.h>
Public Member Functions
CSimpleFileCache ()
~CSimpleFileCache () override
int Open () override
void Close () override
size_t GetMaxWriteSize (const size_t &iRequestSize) override
int WriteToCache (const char *pBuffer, size_t iSize) override
int ReadFromCache (char *pBuffer, size_t iMaxSize) override
int64_t WaitForData (uint32_t iMinAvail, std::chrono::milliseconds timeout) override
int64_t Seek (int64_t iFilePosition) override
bool Reset (int64_t iSourcePosition) override
Reset cache position.
void EndOfInput () override
int64_t CachedDataEndPosIfSeekTo (int64_t iFilePosition) override
int64_t CachedDataStartPos () override
int64_t CachedDataEndPos () override
bool IsCachedPosition (int64_t iFilePosition) override
CCacheStrategy * CreateNew () override
int64_t GetAvailableRead ()
Public Member Functions inherited from XFILE::CCacheStrategy
virtual ~CCacheStrategy ()
virtual bool IsEndOfInput ()
virtual void ClearEndOfInput ()
Protected Attributes
std::string m_filename
IFile * m_cacheFileRead
IFile * m_cacheFileWrite
CEvent * m_hDataAvailEvent
int64_t m_nStartPosition = 0
int64_t m_nWritePosition = 0
int64_t m_nReadPosition = 0
Protected Attributes inherited from XFILE::CCacheStrategy
bool m_bEndOfInput = false
Additional Inherited Members
Public Attributes inherited from XFILE::CCacheStrategy
CEvent m_space
Constructor & Destructor Documentation
CSimpleFileCache()
CSimpleFileCache::CSimpleFileCache ()
Referenced by CreateNew().
~CSimpleFileCache()
CSimpleFileCache::~CSimpleFileCache () override
References Close(), m_cacheFileRead, and m_cacheFileWrite.
Member Function Documentation
CachedDataEndPos()
int64_t CSimpleFileCache::CachedDataEndPos () override virtual
Implements XFILE::CCacheStrategy.
References m_nStartPosition, and m_nWritePosition.
CachedDataEndPosIfSeekTo()
int64_t CSimpleFileCache::CachedDataEndPosIfSeekTo (int64_t iFilePosition) override virtual
Implements XFILE::CCacheStrategy.
References m_nStartPosition, and m_nWritePosition.
CachedDataStartPos()
int64_t CSimpleFileCache::CachedDataStartPos () override virtual
Implements XFILE::CCacheStrategy.
References m_nStartPosition.
Close()
void CSimpleFileCache::Close () override virtual
Implements XFILE::CCacheStrategy.
References XFILE::IFile::Close(), XFILE::IFile::Delete(), CLog::Log(), LOGWARNING, m_cacheFileRead, m_cacheFileWrite, m_filename, and m_hDataAvailEvent.
Referenced by Open(), and ~CSimpleFileCache().
CreateNew()
CCacheStrategy * CSimpleFileCache::CreateNew () override virtual
Implements XFILE::CCacheStrategy.
References CSimpleFileCache().
EndOfInput()
void CSimpleFileCache::EndOfInput () override virtual
Reimplemented from XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::EndOfInput(), m_hDataAvailEvent, and CEvent::Set().
GetAvailableRead()
int64_t CSimpleFileCache::GetAvailableRead ()
References m_nReadPosition, and m_nWritePosition.
Referenced by ReadFromCache(), and WaitForData().
GetMaxWriteSize()
size_t CSimpleFileCache::GetMaxWriteSize (const size_t & iRequestSize) override virtual
Implements XFILE::CCacheStrategy.
IsCachedPosition()
bool CSimpleFileCache::IsCachedPosition (int64_t iFilePosition) override virtual
Implements XFILE::CCacheStrategy.
References m_nStartPosition, and m_nWritePosition.
Referenced by Reset().
Open()
int CSimpleFileCache::Open () override virtual
Implements XFILE::CCacheStrategy.
References CACHE_RC_ERROR, CACHE_RC_OK, Close(), CUtil::GetNextFilename(), CLog::Log(), LOGERROR, m_cacheFileRead, m_cacheFileWrite, m_filename, m_hDataAvailEvent, XFILE::IFile::Open(), XFILE::IFile::OpenForWrite(), and CSpecialProtocol::TranslatePath().
ReadFromCache()
int CSimpleFileCache::ReadFromCache (char * pBuffer, size_t iMaxSize) override virtual
Implements XFILE::CCacheStrategy.
References CACHE_RC_ERROR, CACHE_RC_WOULD_BLOCK, GetAvailableRead(), int64_t(), CLog::Log(), LOGERROR, XFILE::CCacheStrategy::m_bEndOfInput, m_cacheFileRead, m_filename, m_nReadPosition, XFILE::CCacheStrategy::m_space, XFILE::IFile::Read(), CEvent::Set(), and SSIZE_MAX.
Reset()
bool CSimpleFileCache::Reset (int64_t iSourcePosition) override virtual
Reset cache position.
Parameters
iSourcePosition position to reset to
Returns
Whether a full reset was performed, or not (e.g. only cache swap)
See also
CCacheStrategy
Implements XFILE::CCacheStrategy.
References IsCachedPosition(), m_cacheFileRead, m_cacheFileWrite, m_nReadPosition, m_nStartPosition, m_nWritePosition, and XFILE::IFile::Seek().
Seek()
int64_t CSimpleFileCache::Seek (int64_t iFilePosition) override virtual
Implements XFILE::CCacheStrategy.
References CACHE_RC_ERROR, CACHE_RC_TIMEOUT, int64_t(), CLog::Log(), LOGDEBUG, LOGERROR, m_cacheFileRead, m_filename, m_nReadPosition, m_nStartPosition, m_nWritePosition, XFILE::CCacheStrategy::m_space, XFILE::IFile::Seek(), CEvent::Set(), and WaitForData().
WaitForData()
int64_t CSimpleFileCache::WaitForData (uint32_t iMinAvail, std::chrono::milliseconds timeout) override virtual
Implements XFILE::CCacheStrategy.
References CACHE_RC_TIMEOUT, GetAvailableRead(), int64_t(), XFILE::CCacheStrategy::IsEndOfInput(), m_hDataAvailEvent, and CEvent::Wait().
Referenced by Seek().
WriteToCache()
int CSimpleFileCache::WriteToCache (const char * pBuffer, size_t iSize) override virtual
Implements XFILE::CCacheStrategy.
References CACHE_RC_ERROR, CLog::Log(), LOGERROR, m_cacheFileWrite, m_filename, m_hDataAvailEvent, m_nWritePosition, CEvent::Set(), SSIZE_MAX, and XFILE::IFile::Write().
Member Data Documentation
m_cacheFileRead
IFile* XFILE::CSimpleFileCache::m_cacheFileRead protected
Referenced by Close(), Open(), ReadFromCache(), Reset(), Seek(), and ~CSimpleFileCache().
m_cacheFileWrite
IFile* XFILE::CSimpleFileCache::m_cacheFileWrite protected
Referenced by Close(), Open(), Reset(), WriteToCache(), and ~CSimpleFileCache().
m_filename
std::string XFILE::CSimpleFileCache::m_filename protected
Referenced by Close(), Open(), ReadFromCache(), Seek(), and WriteToCache().
m_hDataAvailEvent
CEvent* XFILE::CSimpleFileCache::m_hDataAvailEvent protected
Referenced by Close(), EndOfInput(), Open(), WaitForData(), and WriteToCache().
m_nReadPosition
int64_t XFILE::CSimpleFileCache::m_nReadPosition = 0 protected
Referenced by GetAvailableRead(), ReadFromCache(), Reset(), and Seek().
m_nStartPosition
int64_t XFILE::CSimpleFileCache::m_nStartPosition = 0 protected
Referenced by CachedDataEndPos(), CachedDataEndPosIfSeekTo(), CachedDataStartPos(), IsCachedPosition(), Reset(), and Seek().
m_nWritePosition
int64_t XFILE::CSimpleFileCache::m_nWritePosition = 0 protected
Referenced by CachedDataEndPos(), CachedDataEndPosIfSeekTo(), GetAvailableRead(), IsCachedPosition(), Reset(), Seek(), and WriteToCache().
The documentation for this class was generated from the following files:
CacheStrategy.h
CacheStrategy.cpp