Kodi Documentation: CDiscSettings Class Reference
CDiscSettings Class Reference
#include <DiscSettings.h>
Public Member Functions
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Static Public Member Functions
static CDiscSettings & GetInstance ()
Private Member Functions
CDiscSettings ()=default
~CDiscSettings () override=default
Constructor & Destructor Documentation
CDiscSettings()
CDiscSettings::CDiscSettings () private default
~CDiscSettings()
CDiscSettings::~CDiscSettings () override private default
Member Function Documentation
GetInstance()
CDiscSettings & CDiscSettings::GetInstance () static
Referenced by CSettings::InitializeISettingCallbacks(), and CSettings::UninitializeISettingCallbacks().
OnSettingChanged()
void CDiscSettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References BD_PLAYBACK_DISC_MENU, CLog::Log(), LOGDEBUG, CSettings::SETTING_DISC_PLAYBACK, and KODI::MESSAGING::HELPERS::ShowOKDialogText().
The documentation for this class was generated from the following files:
DiscSettings.h
DiscSettings.cpp