Kodi Documentation: PVR::CGUIEPGGridContainer Class Reference
PVR::CGUIEPGGridContainer Class Reference
#include <GUIEPGGridContainer.h>
Public Member Functions
CGUIEPGGridContainer (int parentID, int controlID, float posX, float posY, float width, float height, ORIENTATION orientation, int scrollTime, int preloadItems, int minutesPerPage, int rulerUnit, const CTextureInfo &progressIndicatorTexture)
CGUIEPGGridContainer (const CGUIEPGGridContainer &other)
CGUIEPGGridContainer * Clone () const override
bool HasData () const
Check whether the control currently holds data.
void AllocResources () override
void FreeResources (bool immediately) override
bool OnAction (const CAction &action) override
void OnDown () override
void OnUp () override
void OnLeft () override
void OnRight () override
bool OnMouseOver (const CPoint &point) override
Called when the mouse is over the control. Default implementation selects the control.
bool OnMessage (CGUIMessage &message) override
void SetFocus (bool focus) override
std::string GetDescription () const override
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
std::shared_ptr< CGUIListItem > GetListItem (int offset, unsigned int flag=0) const override
std::string GetLabel (int info) const override
std::shared_ptr< CFileItem > GetSelectedGridItem (int offset=0) const
std::shared_ptr< CPVRChannelGroupMember > GetSelectedChannelGroupMember () const
CDateTime GetSelectedDate () const
void LoadLayout (TiXmlElement *layout)
void SetPageControl (int id)
void SetRenderOffset (const CPoint &offset)
Set the offset of the first item in the container from the container's position Useful for lists/panels where the focused item may be larger than the non-focused items and thus normally cut off from the clipping window defined by the container's position + size.
void JumpToNow ()
void JumpToDate (const CDateTime &date)
void GoToBegin ()
void GoToEnd ()
void GoToNow ()
void GoToDate (const CDateTime &date)
void GoToFirstChannel ()
void GoToLastChannel ()
void GoToTop ()
void GoToBottom ()
void GoToMostLeft ()
void GoToMostRight ()
void SetTimelineItems (const std::unique_ptr< CFileItemList > &items, const CDateTime &gridStart, const CDateTime &gridEnd)
std::unique_ptr< CFileItemList > GetCurrentTimeLineItems () const
bool SetChannel (const std::shared_ptr< CPVRChannel > &channel)
Set the control's selection to the given channel and set the control's view port to show the channel.
bool SetChannel (const std::string &channel)
Set the control's selection to the given channel and set the control's view port to show the channel.
bool SetChannel (const CPVRChannelNumber &channelNumber)
Set the control's selection to the given channel and set the control's view port to show the channel.
virtual void AssignDepth () override
void AssignItemDepth (CGUIListItem *item, bool focused)
Public Member Functions inherited from IGUIContainer
IGUIContainer (int parentID, int controlID, float posX, float posY, float width, float height)
bool IsContainer () const override
VIEW_TYPE GetType () const
const std::string & GetLabel () const
void SetType (VIEW_TYPE type, const std::string &label)
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual void DynamicResourceAlloc (bool bOnOff)
virtual bool IsDynamicallyAllocated ()
virtual bool CanFocus () const
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Private Member Functions
bool OnClick (int actionID)
bool SelectItemFromPoint (const CPoint &point, bool justGrid=true)
void SetChannel (int channel)
void SetBlock (int block, bool bUpdateBlockTravelAxis=true)
void UpdateBlock (bool bUpdateBlockTravelAxis=true)
void ChannelScroll (int amount)
void ProgrammesScroll (int amount)
void ValidateOffset ()
void UpdateLayout ()
void SetItem (const std::pair< std::shared_ptr< CFileItem >, int > &itemInfo)
bool SetItem (const std::shared_ptr< CFileItem > &item, int channelIndex, int blockIndex)
std::shared_ptr< CFileItem > GetItem () const
std::pair< std::shared_ptr< CFileItem >, int > GetNextItem () const
std::pair< std::shared_ptr< CFileItem >, int > GetPrevItem () const
void UpdateItem ()
void MoveToRow (int row)
CGUIListItemLayout * GetFocusedLayout () const
void ScrollToBlockOffset (int offset)
void ScrollToChannelOffset (int offset)
void GoToBlock (int blockIndex)
void GoToChannel (int channelIndex)
void UpdateScrollOffset (unsigned int currentTime)
void ProcessItem (float posX, float posY, const std::shared_ptr< CFileItem > &item, std::shared_ptr< CFileItem > &lastitem, bool focused, CGUIListItemLayout *normallayout, CGUIListItemLayout *focusedlayout, unsigned int currentTime, CDirtyRegionList &dirtyregions, float resize=-1.0f)
void RenderItem (float posX, float posY, CGUIListItem *item, bool focused)
void GetCurrentLayouts ()
void ProcessChannels (unsigned int currentTime, CDirtyRegionList &dirtyregions)
void ProcessRuler (unsigned int currentTime, CDirtyRegionList &dirtyregions)
void ProcessRulerDate (unsigned int currentTime, CDirtyRegionList &dirtyregions)
void ProcessProgrammeGrid (unsigned int currentTime, CDirtyRegionList &dirtyregions)
void ProcessProgressIndicator (unsigned int currentTime, CDirtyRegionList &dirtyregions)
void RenderChannels ()
void RenderRulerDate ()
void RenderRuler ()
void RenderProgrammeGrid ()
void RenderProgressIndicator ()
void GetChannelCacheOffsets (int &cacheBefore, int &cacheAfter)
void GetProgrammeCacheOffsets (int &cacheBefore, int &cacheAfter)
bool OnMouseClick (int dwButton, const CPoint &point)
bool OnMouseDoubleClick (int dwButton, const CPoint &point)
bool OnMouseWheel (char wheel, const CPoint &point)
void HandleChannels (bool bRender, unsigned int currentTime, CDirtyRegionList &dirtyregions, bool bAssignDepth=false)
void HandleRuler (bool bRender, unsigned int currentTime, CDirtyRegionList &dirtyregions, bool bAssignDepth=false)
void HandleRulerDate (bool bRender, unsigned int currentTime, CDirtyRegionList &dirtyregions, bool bAssignDepth=false)
void HandleProgrammeGrid (bool bRender, unsigned int currentTime, CDirtyRegionList &dirtyregions, bool bAssignDepth=false)
float GetCurrentTimePositionOnPage () const
float GetProgressIndicatorWidth () const
float GetProgressIndicatorHeight () const
void UpdateItems ()
float GetChannelScrollOffsetPos () const
float GetProgrammeScrollOffsetPos () const
int GetChannelScrollOffset (CGUIListItemLayout *layout) const
int GetProgrammeScrollOffset () const
Private Attributes
CPoint m_renderOffset
render offset of the first item in the list
ORIENTATION m_orientation
std::vector< CGUIListItemLayout > m_channelLayouts
std::vector< CGUIListItemLayout > m_focusedChannelLayouts
std::vector< CGUIListItemLayout > m_focusedProgrammeLayouts
std::vector< CGUIListItemLayout > m_programmeLayouts
std::vector< CGUIListItemLayout > m_rulerLayouts
std::vector< CGUIListItemLayout > m_rulerDateLayouts
CGUIListItemLayout * m_channelLayout = nullptr
CGUIListItemLayout * m_focusedChannelLayout = nullptr
CGUIListItemLayout * m_programmeLayout = nullptr
CGUIListItemLayout * m_focusedProgrammeLayout = nullptr
CGUIListItemLayout * m_rulerLayout = nullptr
CGUIListItemLayout * m_rulerDateLayout = nullptr
int m_pageControl = 0
int m_rulerUnit
int m_channelsPerPage = 0
number of blocks that makes up one element of the ruler
int m_programmesPerPage = 0
int m_channelCursor = 0
int m_channelOffset = 0
int m_blocksPerPage
int m_blockCursor = 0
int m_blockOffset = 0
int m_blockTravelAxis = 0
int m_cacheChannelItems
int m_cacheProgrammeItems
int m_cacheRulerItems
float m_rulerDateHeight = 0
float m_rulerDateWidth = 0
height of ruler date item
float m_rulerPosX = 0
width of ruler date item
float m_rulerPosY = 0
X position of first ruler item.
float m_rulerHeight = 0
Y position of first ruler item.
float m_rulerWidth = 0
height of the scrolling timeline above the ruler items
float m_channelPosX = 0
width of each element of the ruler
float m_channelPosY = 0
X position of first channel row.
float m_channelHeight = 0
Y position of first channel row.
float m_channelWidth = 0
height of the channel item
float m_gridPosX = 0
width of the channel item
float m_gridPosY = 0
X position of first grid item.
float m_gridWidth = 0
Y position of first grid item.
float m_gridHeight = 0
width of the epg grid control
float m_blockSize = 0
height of the epg grid control
float m_analogScrollCount = 0
a block's width in pixels
std::unique_ptr< CGUITexture > m_guiProgressIndicatorTexture
uint32_t m_guiProgressIndicatorTextureDepth {0}
std::shared_ptr< CFileItem > m_lastItem
std::shared_ptr< CFileItem > m_lastChannel
bool m_bEnableProgrammeScrolling = true
bool m_bEnableChannelScrolling = true
int m_scrollTime
int m_programmeScrollLastTime = 0
float m_programmeScrollSpeed = 0
float m_programmeScrollOffset = 0
int m_channelScrollLastTime = 0
float m_channelScrollSpeed = 0
float m_channelScrollOffset = 0
CCriticalSection m_critSection
std::unique_ptr< CGUIEPGGridContainerModel > m_gridModel
std::unique_ptr< CGUIEPGGridContainerModel > m_updatedGridModel
int m_itemStartBlock = 0
Additional Inherited Members
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes inherited from IGUIContainer
VIEW_TYPE m_type = VIEW_TYPE_NONE
std::string m_label
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIEPGGridContainer() [1/2]
CGUIEPGGridContainer::CGUIEPGGridContainer (int parentID, int controlID, float posX, float posY, float width, float height, ORIENTATION orientation, int scrollTime, int preloadItems, int minutesPerPage, int rulerUnit, const CTextureInfo & progressIndicatorTexture)
References CGUIControl::ControlType, and CGUIControl::GUICONTAINER_EPGGRID.
CGUIEPGGridContainer() [2/2]
CGUIEPGGridContainer::CGUIEPGGridContainer (const CGUIEPGGridContainer & other)
Member Function Documentation
AllocResources()
void CGUIEPGGridContainer::AllocResources () override virtual
Reimplemented from CGUIControl.
References CGUIControl::AllocResources(), and m_guiProgressIndicatorTexture.
AssignDepth()
void CGUIEPGGridContainer::AssignDepth () override virtual
Reimplemented from CGUIControl.
References CGraphicContext::GetDepth(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), HandleChannels(), HandleProgrammeGrid(), HandleRuler(), HandleRulerDate(), and m_guiProgressIndicatorTextureDepth.
AssignItemDepth()
void CGUIEPGGridContainer::AssignItemDepth (CGUIListItem * item, bool focused)
References ANIM_TYPE_UNFOCUS, CGUIListItemLayout::AssignDepth(), CGUIListItem::GetFocusedLayout(), CGUIListItem::GetLayout(), and CGUIListItemLayout::IsAnimating().
Referenced by HandleChannels(), HandleProgrammeGrid(), HandleRuler(), and HandleRulerDate().
ChannelScroll()
void CGUIEPGGridContainer::ChannelScroll (int amount) private
References m_channelCursor, m_channelOffset, m_channelsPerPage, m_gridModel, ScrollToChannelOffset(), and SetChannel().
Referenced by OnAction().
Clone()
CGUIEPGGridContainer * PVR::CGUIEPGGridContainer::Clone (void) const inline override virtual
Implements CGUIControl.
FreeResources()
void CGUIEPGGridContainer::FreeResources (bool immediately) override virtual
Reimplemented from CGUIControl.
References CGUIControl::FreeResources(), and m_guiProgressIndicatorTexture.
GetChannelCacheOffsets()
void CGUIEPGGridContainer::GetChannelCacheOffsets (int & cacheBefore, int & cacheAfter) private
References m_cacheChannelItems, and m_channelScrollSpeed.
Referenced by HandleChannels(), and HandleProgrammeGrid().
GetChannelScrollOffset()
int CGUIEPGGridContainer::GetChannelScrollOffset (CGUIListItemLayout * layout) const private
References m_bEnableChannelScrolling, m_channelOffset, m_channelScrollOffset, m_orientation, MathUtils::round_int(), and CGUIListItemLayout::Size().
Referenced by GetListItem(), HandleChannels(), and HandleProgrammeGrid().
GetChannelScrollOffsetPos()
float CGUIEPGGridContainer::GetChannelScrollOffsetPos () const private
References m_bEnableChannelScrolling, m_channelLayout, m_channelOffset, m_channelScrollOffset, m_orientation, and CGUIListItemLayout::Size().
Referenced by HandleChannels(), and HandleProgrammeGrid().
GetCurrentLayouts()
void CGUIEPGGridContainer::GetCurrentLayouts () private
References m_channelLayout, m_channelLayouts, m_focusedChannelLayout, m_focusedChannelLayouts, m_focusedProgrammeLayout, m_focusedProgrammeLayouts, m_programmeLayout, m_programmeLayouts, m_rulerDateLayout, m_rulerDateLayouts, m_rulerLayout, and m_rulerLayouts.
Referenced by UpdateLayout().
GetCurrentTimeLineItems()
std::unique_ptr< CFileItemList > CGUIEPGGridContainer::GetCurrentTimeLineItems () const
References m_channelOffset, m_channelsPerPage, and m_gridModel.
Referenced by PVR::CGUIWindowPVRGuideBase::GetDirectory().
GetCurrentTimePositionOnPage()
float CGUIEPGGridContainer::GetCurrentTimePositionOnPage () const private
References GetProgrammeScrollOffsetPos(), CDateTimeSpan::GetSecondsTotal(), CDateTime::GetUTCDateTime(), m_blockSize, m_gridHeight, m_gridModel, m_gridWidth, m_orientation, PVR::CGUIEPGGridContainerModel::MINSPERBLOCK, and VERTICAL.
Referenced by GetProgressIndicatorHeight(), and GetProgressIndicatorWidth().
GetDescription()
std::string CGUIEPGGridContainer::GetDescription (void) const override virtual
Reimplemented from CGUIControl.
References m_blockCursor, m_blockOffset, m_channelCursor, m_channelOffset, m_critSection, and m_gridModel.
GetFocusedLayout()
CGUIListItemLayout * CGUIEPGGridContainer::GetFocusedLayout () const private
References GetListItem().
Referenced by OnClick().
GetItem()
std::shared_ptr< CFileItem > CGUIEPGGridContainer::GetItem () const private
References m_blockCursor, m_blockOffset, m_channelCursor, m_channelOffset, and m_gridModel.
Referenced by UpdateItem().
GetLabel()
std::string CGUIEPGGridContainer::GetLabel (int info) const override virtual
Implements IGUIContainer.
References CONTAINER_CURRENT_PAGE, CONTAINER_NUM_ITEMS, CONTAINER_NUM_PAGES, CONTAINER_POSITION, label, m_channelCursor, m_channelOffset, m_channelsPerPage, and m_gridModel.
GetListItem()
std::shared_ptr< CGUIListItem > CGUIEPGGridContainer::GetListItem (int offset, unsigned int flag = 0) const override virtual
Implements IGUIContainer.
References GetChannelScrollOffset(), INFOFLAG_LISTITEM_POSITION, INFOFLAG_LISTITEM_WRAP, m_channelCursor, m_channelLayout, m_channelOffset, and m_gridModel.
Referenced by GetFocusedLayout().
GetNextItem()
std::pair< std::shared_ptr< CFileItem >, int > CGUIEPGGridContainer::GetNextItem () const private
References m_blockCursor, m_blockOffset, m_channelCursor, m_channelOffset, and m_gridModel.
Referenced by OnDown(), and OnRight().
GetPrevItem()
std::pair< std::shared_ptr< CFileItem >, int > CGUIEPGGridContainer::GetPrevItem () const private
References m_blockCursor, m_blockOffset, m_channelCursor, m_channelOffset, and m_gridModel.
Referenced by OnLeft(), OnUp(), and UpdateItems().
GetProgrammeCacheOffsets()
void CGUIEPGGridContainer::GetProgrammeCacheOffsets (int & cacheBefore, int & cacheAfter) private
References m_cacheProgrammeItems, and m_programmeScrollSpeed.
Referenced by HandleProgrammeGrid(), and HandleRuler().
GetProgrammeScrollOffset()
int CGUIEPGGridContainer::GetProgrammeScrollOffset () const private
References m_bEnableProgrammeScrolling, m_blockOffset, m_blockSize, m_programmeScrollOffset, and MathUtils::round_int().
Referenced by HandleProgrammeGrid(), HandleRuler(), and HandleRulerDate().
GetProgrammeScrollOffsetPos()
float CGUIEPGGridContainer::GetProgrammeScrollOffsetPos () const private
References m_bEnableProgrammeScrolling, m_blockOffset, m_blockSize, and m_programmeScrollOffset.
Referenced by GetCurrentTimePositionOnPage(), HandleProgrammeGrid(), and HandleRuler().
GetProgressIndicatorHeight()
float CGUIEPGGridContainer::GetProgressIndicatorHeight () const private
References GetCurrentTimePositionOnPage(), m_gridHeight, m_orientation, m_rulerHeight, and VERTICAL.
Referenced by ProcessProgressIndicator(), and RenderProgressIndicator().
GetProgressIndicatorWidth()
float CGUIEPGGridContainer::GetProgressIndicatorWidth () const private
References GetCurrentTimePositionOnPage(), m_gridWidth, m_orientation, m_rulerWidth, and VERTICAL.
Referenced by ProcessProgressIndicator(), and RenderProgressIndicator().
GetSelectedChannelGroupMember()
std::shared_ptr< CPVRChannelGroupMember > CGUIEPGGridContainer::GetSelectedChannelGroupMember () const
References m_channelCursor, m_channelOffset, m_critSection, and m_gridModel.
Referenced by PVR::CGUIWindowPVRGuideBase::UpdateSelectedItemPath().
GetSelectedDate()
CDateTime CGUIEPGGridContainer::GetSelectedDate () const
References m_blockCursor, m_blockOffset, and m_gridModel.
Referenced by PVR::CGUIWindowPVRGuideBase::GotoDate(), and PVR::CGUIWindowPVRGuideBase::OpenDateSelectionDialog().
GetSelectedGridItem()
CFileItemPtr CGUIEPGGridContainer::GetSelectedGridItem (int offset = 0) const
References m_blockCursor, m_blockOffset, m_channelCursor, m_channelOffset, and m_gridModel.
Referenced by PVR::CGUIWindowPVRGuideBase::GetCurrentListItem().
GoToBegin()
void CGUIEPGGridContainer::GoToBegin ()
References ScrollToBlockOffset(), and SetBlock().
Referenced by PVR::CGUIWindowPVRGuideBase::GotoBegin().
GoToBlock()
void CGUIEPGGridContainer::GoToBlock (int blockIndex) private
References m_blockCursor, m_blocksPerPage, m_gridModel, ScrollToBlockOffset(), and SetBlock().
Referenced by GoToBottom(), GoToMostLeft(), GoToMostRight(), GoToTop(), and UpdateItems().
GoToBottom()
void CGUIEPGGridContainer::GoToBottom ()
References GoToBlock(), GoToChannel(), m_gridModel, m_orientation, and VERTICAL.
Referenced by PVR::CGUIWindowPVRGuideBase::OnAction().
GoToChannel()
void CGUIEPGGridContainer::GoToChannel (int channelIndex) private
References m_channelCursor, m_channelsPerPage, m_gridModel, ScrollToChannelOffset(), and SetChannel().
Referenced by GoToBottom(), GoToFirstChannel(), GoToLastChannel(), GoToMostLeft(), GoToMostRight(), GoToTop(), SetChannel(), SetChannel(), SetChannel(), and UpdateItems().
GoToDate()
void CGUIEPGGridContainer::GoToDate (const CDateTime & date)
References m_blockOffset, m_channelCursor, m_channelOffset, m_gridModel, ScrollToBlockOffset(), and SetBlock().
Referenced by PVR::CGUIWindowPVRGuideBase::GotoCurrentProgramme(), PVR::CGUIWindowPVRGuideBase::GotoDate(), GoToNow(), JumpToDate(), and PVR::CGUIWindowPVRGuideBase::OpenDateSelectionDialog().
GoToEnd()
void CGUIEPGGridContainer::GoToEnd ()
References m_blocksPerPage, m_gridModel, ScrollToBlockOffset(), and SetBlock().
Referenced by PVR::CGUIWindowPVRGuideBase::GotoEnd().
GoToFirstChannel()
void CGUIEPGGridContainer::GoToFirstChannel ()
References GoToChannel().
Referenced by PVR::CGUIWindowPVRGuideBase::GotoFirstChannel().
GoToLastChannel()
void CGUIEPGGridContainer::GoToLastChannel ()
References GoToChannel(), and m_gridModel.
Referenced by PVR::CGUIWindowPVRGuideBase::GotoLastChannel().
GoToMostLeft()
void CGUIEPGGridContainer::GoToMostLeft ()
References GoToBlock(), GoToChannel(), m_orientation, and VERTICAL.
Referenced by PVR::CGUIWindowPVRGuideBase::OnAction().
GoToMostRight()
void CGUIEPGGridContainer::GoToMostRight ()
References GoToBlock(), GoToChannel(), m_gridModel, m_orientation, and VERTICAL.
Referenced by PVR::CGUIWindowPVRGuideBase::OnAction().
GoToNow()
void CGUIEPGGridContainer::GoToNow ()
References CDateTime::GetUTCDateTime(), and GoToDate().
Referenced by PVR::CGUIWindowPVRGuideBase::GotoCurrentProgramme(), JumpToNow(), OnAction(), and UpdateItems().
GoToTop()
void CGUIEPGGridContainer::GoToTop ()
References GoToBlock(), GoToChannel(), m_orientation, and VERTICAL.
Referenced by PVR::CGUIWindowPVRGuideBase::OnAction().
HandleChannels()
void CGUIEPGGridContainer::HandleChannels (bool bRender, unsigned int currentTime, CDirtyRegionList & dirtyregions, bool bAssignDepth = false) private
References AssignItemDepth(), end(), GetChannelCacheOffsets(), GetChannelScrollOffset(), GetChannelScrollOffsetPos(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), m_channelCursor, m_channelHeight, m_channelLayout, m_channelOffset, m_channelPosX, m_channelPosY, m_channelsPerPage, m_channelWidth, m_focusedChannelLayout, m_gridHeight, m_gridModel, m_gridWidth, CGUIControl::m_height, m_lastItem, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, m_programmeLayout, m_renderOffset, CGUIControl::m_width, ProcessItem(), RenderItem(), CGraphicContext::RestoreClipRegion(), CGraphicContext::SetClipRegion(), CGUIListItemLayout::Size(), VERTICAL, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by AssignDepth(), ProcessChannels(), and RenderChannels().
HandleProgrammeGrid()
void CGUIEPGGridContainer::HandleProgrammeGrid (bool bRender, unsigned int currentTime, CDirtyRegionList & dirtyregions, bool bAssignDepth = false) private
References AssignItemDepth(), PVR::Epg, CServiceBroker::GetAppMessenger(), GetChannelCacheOffsets(), GetChannelScrollOffset(), GetChannelScrollOffsetPos(), CWinSystemBase::GetGfxContext(), CGUIControl::GetID(), CGUIControl::GetParentID(), GetProgrammeCacheOffsets(), GetProgrammeScrollOffset(), GetProgrammeScrollOffsetPos(), CServiceBroker::GetWinSystem(), GUI_MSG_REFRESH_LIST, HasData(), m_blockCursor, m_blockOffset, m_blockSize, m_channelCursor, m_channelHeight, m_channelLayout, m_channelOffset, m_channelsPerPage, m_channelWidth, m_critSection, m_focusedProgrammeLayout, m_gridHeight, m_gridModel, m_gridPosX, m_gridPosY, m_gridWidth, CGUIControl::m_height, m_lastChannel, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, m_programmeLayout, m_programmesPerPage, m_renderOffset, CGUIControl::m_width, ProcessItem(), RenderItem(), CGraphicContext::RestoreClipRegion(), MathUtils::round_int(), CGraphicContext::SetClipRegion(), CGUIListItemLayout::Size(), VERTICAL, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by AssignDepth(), ProcessProgrammeGrid(), and RenderProgrammeGrid().
HandleRuler()
void CGUIEPGGridContainer::HandleRuler (bool bRender, unsigned int currentTime, CDirtyRegionList & dirtyregions, bool bAssignDepth = false) private
References AssignItemDepth(), end(), CWinSystemBase::GetGfxContext(), GetProgrammeCacheOffsets(), GetProgrammeScrollOffset(), GetProgrammeScrollOffsetPos(), CServiceBroker::GetWinSystem(), HORIZONTAL, m_blockSize, m_blocksPerPage, m_channelWidth, m_gridHeight, m_gridModel, m_gridWidth, CGUIControl::m_height, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, m_renderOffset, m_rulerDateLayout, m_rulerHeight, m_rulerLayout, m_rulerPosX, m_rulerPosY, m_rulerUnit, m_rulerWidth, CGUIControl::m_width, ProcessItem(), RenderItem(), CGraphicContext::RestoreClipRegion(), CGraphicContext::SetClipRegion(), CGUIListItemLayout::Size(), VERTICAL, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by AssignDepth(), ProcessRuler(), and RenderRuler().
HandleRulerDate()
void CGUIEPGGridContainer::HandleRulerDate (bool bRender, unsigned int currentTime, CDirtyRegionList & dirtyregions, bool bAssignDepth = false) private
References AssignItemDepth(), CWinSystemBase::GetGfxContext(), GetProgrammeScrollOffset(), CServiceBroker::GetWinSystem(), m_gridModel, CGUIControl::m_posX, CGUIControl::m_posY, m_rulerDateHeight, m_rulerDateLayout, m_rulerDateWidth, m_rulerUnit, ProcessItem(), RenderItem(), CGraphicContext::RestoreClipRegion(), and CGraphicContext::SetClipRegion().
Referenced by AssignDepth(), ProcessRulerDate(), and RenderRulerDate().
HasData()
bool CGUIEPGGridContainer::HasData () const
Check whether the control currently holds data.
Returns
true if the control has data, false otherwise.
References m_gridModel.
Referenced by HandleProgrammeGrid(), PVR::CGUIWindowPVRGuideBase::InitEpgGridControl(), OnDown(), OnLeft(), OnRight(), OnUp(), and UpdateItems().
JumpToDate()
void CGUIEPGGridContainer::JumpToDate (const CDateTime & date)
References GoToDate(), and m_bEnableProgrammeScrolling.
Referenced by PVR::CGUIWindowPVRGuideBase::InitEpgGridControl().
JumpToNow()
void CGUIEPGGridContainer::JumpToNow ()
References GoToNow(), and m_bEnableProgrammeScrolling.
Referenced by PVR::CGUIWindowPVRGuideBase::InitEpgGridControl().
LoadLayout()
void CGUIEPGGridContainer::LoadLayout (TiXmlElement * layout)
References CGUIControl::GetParentID(), m_channelLayouts, m_focusedChannelLayouts, m_focusedProgrammeLayouts, CGUIControl::m_height, m_programmeLayouts, m_rulerDateLayouts, m_rulerLayouts, CGUIControl::m_width, and UpdateLayout().
Referenced by CGUIControlFactory::Create().
MoveToRow()
void PVR::CGUIEPGGridContainer::MoveToRow (int row) private
OnAction()
bool CGUIEPGGridContainer::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControl.
References ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NAV_BACK, ACTION_NEXT_ITEM, ACTION_PAGE_DOWN, ACTION_PAGE_UP, ACTION_PREV_ITEM, ACTION_SCROLL_DOWN, ACTION_SCROLL_UP, ACTION_TELETEXT_BLUE, ACTION_TELETEXT_GREEN, ACTION_TELETEXT_RED, ACTION_TELETEXT_YELLOW, ChannelScroll(), GoToNow(), m_analogScrollCount, m_blockCursor, m_blockOffset, m_blocksPerPage, m_channelCursor, m_channelOffset, m_channelsPerPage, m_gridModel, m_orientation, PVR::CGUIEPGGridContainerModel::MINSPERBLOCK, CGUIControl::OnAction(), OnClick(), ProgrammesScroll(), REMOTE_0, ScrollToBlockOffset(), SetBlock(), SetChannel(), and VERTICAL.
OnClick()
bool CGUIEPGGridContainer::OnClick (int actionID) private
References ACTION_MOUSE_LEFT_CLICK, ACTION_SELECT_ITEM, CGUIListItemLayout::GetFocusedItem(), GetFocusedLayout(), CGUIControl::GetID(), CGUIControl::GetParentID(), GUI_MSG_CLICKED, and CGUIControl::SendWindowMessage().
Referenced by OnAction(), OnMouseClick(), and OnMouseDoubleClick().
OnDown()
void CGUIEPGGridContainer::OnDown () override virtual
Reimplemented from CGUIControl.
References ACTION_MOVE_DOWN, BLOCK_SCROLL_OFFSET, CGUIControl::GetAction(), CGUIControl::GetID(), GetNextItem(), HasData(), m_blockCursor, m_blockOffset, m_blocksPerPage, m_channelCursor, m_channelOffset, m_channelsPerPage, m_gridModel, m_orientation, CGUIControl::OnDown(), ScrollToBlockOffset(), ScrollToChannelOffset(), SetChannel(), SetItem(), UpdateBlock(), and VERTICAL.
OnLeft()
void CGUIEPGGridContainer::OnLeft () override virtual
Reimplemented from CGUIControl.
References ACTION_MOVE_LEFT, BLOCK_SCROLL_OFFSET, CGUIControl::GetAction(), CGUIControl::GetID(), GetPrevItem(), HasData(), m_blockCursor, m_blockOffset, m_channelCursor, m_channelOffset, m_channelsPerPage, m_gridModel, m_orientation, CGUIControl::OnLeft(), ScrollToBlockOffset(), ScrollToChannelOffset(), SetChannel(), SetItem(), UpdateBlock(), and VERTICAL.
OnMessage()
bool CGUIEPGGridContainer::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControl.
References CGUIMessage::GetControlId(), CGUIControl::GetID(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIMessage::GetSenderId(), GUI_MSG_LABEL_BIND, GUI_MSG_PAGE_CHANGE, GUI_MSG_REFRESH_LIST, CGUIControl::IsVisible(), m_blockCursor, m_channelCursor, m_gridModel, m_orientation, m_pageControl, CGUIControl::OnMessage(), ScrollToBlockOffset(), ScrollToChannelOffset(), SetBlock(), SetChannel(), UpdateItems(), and VERTICAL.
OnMouseClick()
bool CGUIEPGGridContainer::OnMouseClick (int dwButton, const CPoint & point) private
References ACTION_MOUSE_LEFT_CLICK, m_gridPosX, m_gridPosY, OnClick(), and SelectItemFromPoint().
Referenced by OnMouseEvent().
OnMouseDoubleClick()
bool CGUIEPGGridContainer::OnMouseDoubleClick (int dwButton, const CPoint & point) private
References ACTION_MOUSE_DOUBLE_CLICK, m_gridPosX, m_gridPosY, OnClick(), and SelectItemFromPoint().
Referenced by OnMouseEvent().
OnMouseEvent()
EVENT_RESULT CGUIEPGGridContainer::OnMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) override virtual
Perform a mouse action.
Mouse actions are sent from the window to all controls, and each control can react based on the event and location of the actions.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
SendMouseEvent, HitTest, CanFocusFromPoint, CMouseEvent
Reimplemented from CGUIControl.
References ACTION_GESTURE_ABORT, ACTION_GESTURE_BEGIN, ACTION_GESTURE_END, ACTION_GESTURE_PAN, ACTION_MOUSE_DOUBLE_CLICK, ACTION_MOUSE_LEFT_CLICK, ACTION_MOUSE_RIGHT_CLICK, ACTION_MOUSE_WHEEL_DOWN, ACTION_MOUSE_WHEEL_UP, EVENT_RESULT_HANDLED, EVENT_RESULT_UNHANDLED, CGUIControl::GetID(), CGUIControl::GetParentID(), GUI_MSG_EXCLUSIVE_MOUSE, m_blockCursor, m_blockOffset, m_blockSize, m_channelCursor, m_channelLayout, m_channelOffset, m_channelScrollOffset, m_critSection, KODI::MOUSE::CMouseEvent::m_id, m_orientation, m_programmeScrollOffset, OnMouseClick(), OnMouseDoubleClick(), OnMouseWheel(), MathUtils::round_int(), ScrollToBlockOffset(), ScrollToChannelOffset(), CGUIControl::SendWindowMessage(), SetBlock(), SetChannel(), CGUIListItemLayout::Size(), and ValidateOffset().
OnMouseOver()
bool CGUIEPGGridContainer::OnMouseOver (const CPoint & point) override virtual
Called when the mouse is over the control. Default implementation selects the control.
Parameters
point location of the mouse in transformed skin coordinates
Returns
true if handled, false otherwise.
Reimplemented from CGUIControl.
References m_gridPosX, m_gridPosY, CGUIControl::OnMouseOver(), and SelectItemFromPoint().
OnMouseWheel()
bool CGUIEPGGridContainer::OnMouseWheel (char wheel, const CPoint & point) private
References ProgrammesScroll().
Referenced by OnMouseEvent().
OnRight()
void CGUIEPGGridContainer::OnRight () override virtual
Reimplemented from CGUIControl.
References ACTION_MOVE_RIGHT, BLOCK_SCROLL_OFFSET, CGUIControl::GetAction(), CGUIControl::GetID(), GetNextItem(), HasData(), m_blockCursor, m_blockOffset, m_blocksPerPage, m_channelCursor, m_channelOffset, m_channelsPerPage, m_gridModel, m_orientation, CGUIControl::OnRight(), ScrollToBlockOffset(), ScrollToChannelOffset(), SetChannel(), SetItem(), UpdateBlock(), and VERTICAL.
OnUp()
void CGUIEPGGridContainer::OnUp () override virtual
Reimplemented from CGUIControl.
References ACTION_MOVE_UP, BLOCK_SCROLL_OFFSET, CGUIControl::GetAction(), CGUIControl::GetID(), GetPrevItem(), HasData(), m_blockCursor, m_blockOffset, m_channelCursor, m_channelOffset, m_channelsPerPage, m_gridModel, m_orientation, CGUIControl::OnUp(), ScrollToBlockOffset(), ScrollToChannelOffset(), SetChannel(), SetItem(), UpdateBlock(), and VERTICAL.
Process()
void CGUIEPGGridContainer::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
References CGUIControl::GetID(), GUI_MSG_ITEM_SELECT, GUI_MSG_LABEL_RESET, CGUIControl::m_bInvalidated, m_blocksPerPage, m_channelHeight, m_channelScrollOffset, m_channelsPerPage, m_gridHeight, m_gridModel, m_orientation, m_pageControl, m_programmeScrollOffset, CGUIControl::Process(), ProcessChannels(), ProcessProgrammeGrid(), ProcessProgressIndicator(), ProcessRuler(), ProcessRulerDate(), MathUtils::round_int(), CGUIControl::SendWindowMessage(), UpdateLayout(), UpdateScrollOffset(), ValidateOffset(), and VERTICAL.
ProcessChannels()
void CGUIEPGGridContainer::ProcessChannels (unsigned int currentTime, CDirtyRegionList & dirtyregions) private
References HandleChannels().
Referenced by Process().
ProcessItem()
void CGUIEPGGridContainer::ProcessItem (float posX, float posY, const std::shared_ptr< CFileItem > & item, std::shared_ptr< CFileItem > & lastitem, bool focused, CGUIListItemLayout * normallayout, CGUIListItemLayout * focusedlayout, unsigned int currentTime, CDirtyRegionList & dirtyregions, float resize = -1.0f) private
References ANIM_TYPE_UNFOCUS, CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CGUIControl::HasFocus(), CGUIControl::m_bInvalidated, m_orientation, CGUIControl::m_parentID, CGraphicContext::RestoreOrigin(), CGraphicContext::SetOrigin(), and VERTICAL.
Referenced by HandleChannels(), HandleProgrammeGrid(), HandleRuler(), and HandleRulerDate().
ProcessProgrammeGrid()
void CGUIEPGGridContainer::ProcessProgrammeGrid (unsigned int currentTime, CDirtyRegionList & dirtyregions) private
References HandleProgrammeGrid().
Referenced by Process().
ProcessProgressIndicator()
void CGUIEPGGridContainer::ProcessProgressIndicator (unsigned int currentTime, CDirtyRegionList & dirtyregions) private
References GetProgressIndicatorHeight(), GetProgressIndicatorWidth(), m_guiProgressIndicatorTexture, m_renderOffset, m_rulerPosX, m_rulerPosY, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by Process().
ProcessRuler()
void CGUIEPGGridContainer::ProcessRuler (unsigned int currentTime, CDirtyRegionList & dirtyregions) private
References HandleRuler().
Referenced by Process().
ProcessRulerDate()
void CGUIEPGGridContainer::ProcessRulerDate (unsigned int currentTime, CDirtyRegionList & dirtyregions) private
References HandleRulerDate().
Referenced by Process().
ProgrammesScroll()
void CGUIEPGGridContainer::ProgrammesScroll (int amount) private
References m_blockCursor, m_blockOffset, ScrollToBlockOffset(), and SetBlock().
Referenced by OnAction(), and OnMouseWheel().
Render()
void CGUIEPGGridContainer::Render () override virtual
Reimplemented from CGUIControl.
References CServiceBroker::GetWinSystem(), CGUIControl::Render(), RENDER_ORDER_FRONT_TO_BACK, RenderChannels(), RenderProgrammeGrid(), RenderProgressIndicator(), RenderRuler(), and RenderRulerDate().
RenderChannels()
void CGUIEPGGridContainer::RenderChannels () private
References HandleChannels().
Referenced by Render().
RenderItem()
void CGUIEPGGridContainer::RenderItem (float posX, float posY, CGUIListItem * item, bool focused) private
References ANIM_TYPE_UNFOCUS, CGUIListItem::GetFocusedLayout(), CWinSystemBase::GetGfxContext(), CGUIListItem::GetLayout(), CServiceBroker::GetWinSystem(), CGUIListItemLayout::IsAnimating(), CGUIControl::m_parentID, CGUIListItemLayout::Render(), CGraphicContext::RestoreOrigin(), and CGraphicContext::SetOrigin().
Referenced by HandleChannels(), HandleProgrammeGrid(), HandleRuler(), and HandleRulerDate().
RenderProgrammeGrid()
void CGUIEPGGridContainer::RenderProgrammeGrid () private
References HandleProgrammeGrid().
Referenced by Render().
RenderProgressIndicator()
void CGUIEPGGridContainer::RenderProgressIndicator () private
References CWinSystemBase::GetGfxContext(), GetProgressIndicatorHeight(), GetProgressIndicatorWidth(), CServiceBroker::GetWinSystem(), CGUIControl::m_diffuseColor, m_guiProgressIndicatorTexture, m_guiProgressIndicatorTextureDepth, m_rulerPosX, m_rulerPosY, and CGraphicContext::RestoreClipRegion().
Referenced by Render().
RenderRuler()
void CGUIEPGGridContainer::RenderRuler () private
References HandleRuler().
Referenced by Render().
RenderRulerDate()
void CGUIEPGGridContainer::RenderRulerDate () private
References HandleRulerDate().
Referenced by Render().
ScrollToBlockOffset()
void CGUIEPGGridContainer::ScrollToBlockOffset (int offset) private
References m_blockOffset, m_blockSize, m_blocksPerPage, m_critSection, m_gridModel, m_programmeScrollOffset, m_programmeScrollSpeed, m_scrollTime, and CGUIControl::MarkDirtyRegion().
Referenced by GoToBegin(), GoToBlock(), GoToDate(), GoToEnd(), OnAction(), OnDown(), OnLeft(), OnMessage(), OnMouseEvent(), OnRight(), OnUp(), and ProgrammesScroll().
ScrollToChannelOffset()
void CGUIEPGGridContainer::ScrollToChannelOffset (int offset) private
References m_channelOffset, m_channelScrollOffset, m_channelScrollSpeed, m_channelsPerPage, m_critSection, m_orientation, m_programmeLayout, m_scrollTime, CGUIControl::MarkDirtyRegion(), and CGUIListItemLayout::Size().
Referenced by ChannelScroll(), GoToChannel(), OnDown(), OnLeft(), OnMessage(), OnMouseEvent(), OnRight(), and OnUp().
SelectItemFromPoint()
bool CGUIEPGGridContainer::SelectItemFromPoint (const CPoint & point, bool justGrid = true) private
References m_blockOffset, m_blockSize, m_blocksPerPage, m_channelHeight, m_channelOffset, m_channelsPerPage, m_channelWidth, m_focusedProgrammeLayout, m_gridModel, m_orientation, m_programmeLayout, SetBlock(), SetChannel(), VERTICAL, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by OnMouseClick(), OnMouseDoubleClick(), and OnMouseOver().
SetBlock()
void CGUIEPGGridContainer::SetBlock (int block, bool bUpdateBlockTravelAxis = true) private
References m_blockCursor, m_blockOffset, m_blocksPerPage, m_blockTravelAxis, m_critSection, CGUIControl::MarkDirtyRegion(), and UpdateItem().
Referenced by GoToBegin(), GoToBlock(), GoToDate(), GoToEnd(), OnAction(), OnMessage(), OnMouseEvent(), ProgrammesScroll(), SelectItemFromPoint(), and UpdateBlock().
SetChannel() [1/4]
bool CGUIEPGGridContainer::SetChannel (const CPVRChannelNumber & channelNumber)
Set the control's selection to the given channel and set the control's view port to show the channel.
Parameters
channelNumber the channel's number.
Returns
true if the selection was set to the given channel, false otherwise.
References GoToChannel(), and m_gridModel.
SetChannel() [2/4]
bool CGUIEPGGridContainer::SetChannel (const std::shared_ptr< CPVRChannel > & channel)
Set the control's selection to the given channel and set the control's view port to show the channel.
Parameters
channel the channel.
Returns
true if the selection was set to the given channel, false otherwise.
References GoToChannel(), and m_gridModel.
Referenced by ChannelScroll(), GoToChannel(), PVR::CGUIWindowPVRGuideBase::GotoPlayingChannel(), PVR::CGUIWindowPVRGuideBase::InitEpgGridControl(), OnAction(), OnDown(), PVR::CGUIWindowPVRGuideBase::OnInputDone(), OnLeft(), OnMessage(), OnMouseEvent(), OnRight(), OnUp(), SelectItemFromPoint(), and PVR::CGUIWindowPVRGuideBase::Update().
SetChannel() [3/4]
bool CGUIEPGGridContainer::SetChannel (const std::string & channel)
Set the control's selection to the given channel and set the control's view port to show the channel.
Parameters
channel the channel's path.
Returns
true if the selection was set to the given channel, false otherwise.
References GoToChannel(), and m_gridModel.
SetChannel() [4/4]
void CGUIEPGGridContainer::SetChannel (int channel) private
References m_blockCursor, m_blockOffset, m_blockTravelAxis, m_channelCursor, m_channelOffset, m_critSection, m_gridModel, CGUIControl::MarkDirtyRegion(), SetItem(), and UpdateBlock().
SetFocus()
void CGUIEPGGridContainer::SetFocus (bool focus) override virtual
Reimplemented from CGUIControl.
References CGUIControl::HasFocus(), CGUIControl::SetFocus(), and CGUIControl::SetInvalid().
SetItem() [1/2]
void CGUIEPGGridContainer::SetItem (const std::pair< std::shared_ptr< CFileItem >, int > & itemInfo) private
References m_channelCursor, m_channelOffset, and SetItem().
Referenced by OnDown(), OnLeft(), OnRight(), OnUp(), SetChannel(), SetItem(), and UpdateItem().
SetItem() [2/2]
bool CGUIEPGGridContainer::SetItem (const std::shared_ptr< CFileItem > & item, int channelIndex, int blockIndex) private
References m_gridModel, and m_itemStartBlock.
SetPageControl()
void CGUIEPGGridContainer::SetPageControl (int id)
References id, and m_pageControl.
Referenced by CGUIControlFactory::Create().
SetRenderOffset()
void CGUIEPGGridContainer::SetRenderOffset (const CPoint & offset)
Set the offset of the first item in the container from the container's position Useful for lists/panels where the focused item may be larger than the non-focused items and thus normally cut off from the clipping window defined by the container's position + size.
Parameters
offset CPoint holding the offset in skin coordinates.
References m_renderOffset.
Referenced by CGUIControlFactory::Create().
SetTimelineItems()
void CGUIEPGGridContainer::SetTimelineItems (const std::unique_ptr< CFileItemList > & items, const CDateTime & gridStart, const CDateTime & gridEnd)
References m_blockOffset, m_blockSize, m_blocksPerPage, m_channelOffset, m_channelsPerPage, m_critSection, m_rulerUnit, and m_updatedGridModel.
Referenced by PVR::CGUIWindowPVRGuideBase::RefreshTimelineItems().
UpdateBlock()
void CGUIEPGGridContainer::UpdateBlock (bool bUpdateBlockTravelAxis = true) private
References m_blockOffset, m_itemStartBlock, and SetBlock().
Referenced by OnDown(), OnLeft(), OnRight(), OnUp(), and SetChannel().
UpdateItem()
void CGUIEPGGridContainer::UpdateItem () private
References GetItem(), m_blockCursor, m_blockOffset, m_channelCursor, m_channelOffset, and SetItem().
Referenced by SetBlock(), and UpdateItems().
UpdateItems()
void CGUIEPGGridContainer::UpdateItems () private
References GetPrevItem(), GoToBlock(), GoToChannel(), GoToNow(), HasData(), PVR::CGUIEPGGridContainerModel::INVALID_INDEX, m_bEnableChannelScrolling, m_bEnableProgrammeScrolling, m_blockCursor, m_blockOffset, m_channelCursor, m_channelOffset, m_critSection, m_gridModel, m_lastChannel, m_lastItem, m_updatedGridModel, CGUIControl::SetInvalid(), and UpdateItem().
Referenced by OnMessage().
UpdateLayout()
void CGUIEPGGridContainer::UpdateLayout () private
References GetCurrentLayouts(), HORIZONTAL, m_blockOffset, m_blockSize, m_blocksPerPage, m_channelHeight, m_channelLayout, m_channelOffset, m_channelPosX, m_channelPosY, m_channelScrollOffset, m_channelsPerPage, m_channelWidth, m_critSection, m_focusedChannelLayout, m_focusedProgrammeLayout, m_gridHeight, m_gridPosX, m_gridPosY, m_gridWidth, CGUIControl::m_height, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, m_programmeLayout, m_programmeScrollOffset, m_programmesPerPage, m_rulerDateHeight, m_rulerDateLayout, m_rulerDateWidth, m_rulerHeight, m_rulerLayout, m_rulerPosX, m_rulerPosY, m_rulerUnit, m_rulerWidth, CGUIControl::m_width, CGUIListItemLayout::SetHeight(), CGUIListItemLayout::SetWidth(), CGUIListItemLayout::Size(), and VERTICAL.
Referenced by LoadLayout(), and Process().
UpdateScrollOffset()
void CGUIEPGGridContainer::UpdateScrollOffset (unsigned int currentTime) private
References m_bEnableChannelScrolling, m_bEnableProgrammeScrolling, m_blockOffset, m_blockSize, m_channelOffset, m_channelScrollLastTime, m_channelScrollOffset, m_channelScrollSpeed, m_orientation, m_programmeLayout, m_programmeScrollLastTime, m_programmeScrollOffset, m_programmeScrollSpeed, CGUIControl::MarkDirtyRegion(), and CGUIListItemLayout::Size().
Referenced by Process().
ValidateOffset()
void CGUIEPGGridContainer::ValidateOffset () private
References m_blockOffset, m_blockSize, m_blocksPerPage, m_channelHeight, m_channelOffset, m_channelScrollOffset, m_channelsPerPage, m_channelWidth, m_critSection, m_gridModel, m_orientation, m_programmeLayout, m_programmeScrollOffset, and VERTICAL.
Referenced by OnMouseEvent(), and Process().
Member Data Documentation
m_analogScrollCount
float PVR::CGUIEPGGridContainer::m_analogScrollCount = 0 private
a block's width in pixels
Referenced by OnAction().
m_bEnableChannelScrolling
bool PVR::CGUIEPGGridContainer::m_bEnableChannelScrolling = true private
Referenced by GetChannelScrollOffset(), GetChannelScrollOffsetPos(), UpdateItems(), and UpdateScrollOffset().
m_bEnableProgrammeScrolling
bool PVR::CGUIEPGGridContainer::m_bEnableProgrammeScrolling = true private
Referenced by GetProgrammeScrollOffset(), GetProgrammeScrollOffsetPos(), JumpToDate(), JumpToNow(), UpdateItems(), and UpdateScrollOffset().
m_blockCursor
int PVR::CGUIEPGGridContainer::m_blockCursor = 0 private
Referenced by GetDescription(), GetItem(), GetNextItem(), GetPrevItem(), GetSelectedDate(), GetSelectedGridItem(), GoToBlock(), HandleProgrammeGrid(), OnAction(), OnDown(), OnLeft(), OnMessage(), OnMouseEvent(), OnRight(), OnUp(), ProgrammesScroll(), SetBlock(), SetChannel(), UpdateItem(), and UpdateItems().
m_blockOffset
int PVR::CGUIEPGGridContainer::m_blockOffset = 0 private
Referenced by GetDescription(), GetItem(), GetNextItem(), GetPrevItem(), GetProgrammeScrollOffset(), GetProgrammeScrollOffsetPos(), GetSelectedDate(), GetSelectedGridItem(), GoToDate(), HandleProgrammeGrid(), OnAction(), OnDown(), OnLeft(), OnMouseEvent(), OnRight(), OnUp(), ProgrammesScroll(), ScrollToBlockOffset(), SelectItemFromPoint(), SetBlock(), SetChannel(), SetTimelineItems(), UpdateBlock(), UpdateItem(), UpdateItems(), UpdateLayout(), UpdateScrollOffset(), and ValidateOffset().
m_blockSize
float PVR::CGUIEPGGridContainer::m_blockSize = 0 private
height of the epg grid control
Referenced by GetCurrentTimePositionOnPage(), GetProgrammeScrollOffset(), GetProgrammeScrollOffsetPos(), HandleProgrammeGrid(), HandleRuler(), OnMouseEvent(), ScrollToBlockOffset(), SelectItemFromPoint(), SetTimelineItems(), UpdateLayout(), UpdateScrollOffset(), and ValidateOffset().
m_blocksPerPage
int PVR::CGUIEPGGridContainer::m_blocksPerPage private
Referenced by GoToBlock(), GoToEnd(), HandleRuler(), OnAction(), OnDown(), OnRight(), Process(), ScrollToBlockOffset(), SelectItemFromPoint(), SetBlock(), SetTimelineItems(), UpdateLayout(), and ValidateOffset().
m_blockTravelAxis
int PVR::CGUIEPGGridContainer::m_blockTravelAxis = 0 private
Referenced by SetBlock(), and SetChannel().
m_cacheChannelItems
int PVR::CGUIEPGGridContainer::m_cacheChannelItems private
Referenced by GetChannelCacheOffsets().
m_cacheProgrammeItems
int PVR::CGUIEPGGridContainer::m_cacheProgrammeItems private
Referenced by GetProgrammeCacheOffsets().
m_cacheRulerItems
int PVR::CGUIEPGGridContainer::m_cacheRulerItems private
m_channelCursor
int PVR::CGUIEPGGridContainer::m_channelCursor = 0 private
Referenced by ChannelScroll(), GetDescription(), GetItem(), GetLabel(), GetListItem(), GetNextItem(), GetPrevItem(), GetSelectedChannelGroupMember(), GetSelectedGridItem(), GoToChannel(), GoToDate(), HandleChannels(), HandleProgrammeGrid(), OnAction(), OnDown(), OnLeft(), OnMessage(), OnMouseEvent(), OnRight(), OnUp(), SetChannel(), SetItem(), UpdateItem(), and UpdateItems().
m_channelHeight
float PVR::CGUIEPGGridContainer::m_channelHeight = 0 private
Y position of first channel row.
Referenced by HandleChannels(), HandleProgrammeGrid(), Process(), SelectItemFromPoint(), UpdateLayout(), and ValidateOffset().
m_channelLayout
CGUIListItemLayout* PVR::CGUIEPGGridContainer::m_channelLayout = nullptr private
Referenced by GetChannelScrollOffsetPos(), GetCurrentLayouts(), GetListItem(), HandleChannels(), HandleProgrammeGrid(), OnMouseEvent(), and UpdateLayout().
m_channelLayouts
std::vector<CGUIListItemLayout> PVR::CGUIEPGGridContainer::m_channelLayouts private
Referenced by GetCurrentLayouts(), and LoadLayout().
m_channelOffset
int PVR::CGUIEPGGridContainer::m_channelOffset = 0 private
Referenced by ChannelScroll(), GetChannelScrollOffset(), GetChannelScrollOffsetPos(), GetCurrentTimeLineItems(), GetDescription(), GetItem(), GetLabel(), GetListItem(), GetNextItem(), GetPrevItem(), GetSelectedChannelGroupMember(), GetSelectedGridItem(), GoToDate(), HandleChannels(), HandleProgrammeGrid(), OnAction(), OnDown(), OnLeft(), OnMouseEvent(), OnRight(), OnUp(), ScrollToChannelOffset(), SelectItemFromPoint(), SetChannel(), SetItem(), SetTimelineItems(), UpdateItem(), UpdateItems(), UpdateLayout(), UpdateScrollOffset(), and ValidateOffset().
m_channelPosX
float PVR::CGUIEPGGridContainer::m_channelPosX = 0 private
width of each element of the ruler
Referenced by HandleChannels(), and UpdateLayout().
m_channelPosY
float PVR::CGUIEPGGridContainer::m_channelPosY = 0 private
X position of first channel row.
Referenced by HandleChannels(), and UpdateLayout().
m_channelScrollLastTime
int PVR::CGUIEPGGridContainer::m_channelScrollLastTime = 0 private
Referenced by UpdateScrollOffset().
m_channelScrollOffset
float PVR::CGUIEPGGridContainer::m_channelScrollOffset = 0 private
Referenced by GetChannelScrollOffset(), GetChannelScrollOffsetPos(), OnMouseEvent(), Process(), ScrollToChannelOffset(), UpdateLayout(), UpdateScrollOffset(), and ValidateOffset().
m_channelScrollSpeed
float PVR::CGUIEPGGridContainer::m_channelScrollSpeed = 0 private
Referenced by GetChannelCacheOffsets(), ScrollToChannelOffset(), and UpdateScrollOffset().
m_channelsPerPage
int PVR::CGUIEPGGridContainer::m_channelsPerPage = 0 private
number of blocks that makes up one element of the ruler
Referenced by ChannelScroll(), GetCurrentTimeLineItems(), GetLabel(), GoToChannel(), HandleChannels(), HandleProgrammeGrid(), OnAction(), OnDown(), OnLeft(), OnRight(), OnUp(), Process(), ScrollToChannelOffset(), SelectItemFromPoint(), SetTimelineItems(), UpdateLayout(), and ValidateOffset().
m_channelWidth
float PVR::CGUIEPGGridContainer::m_channelWidth = 0 private
height of the channel item
Referenced by HandleChannels(), HandleProgrammeGrid(), HandleRuler(), SelectItemFromPoint(), UpdateLayout(), and ValidateOffset().
m_critSection
CCriticalSection PVR::CGUIEPGGridContainer::m_critSection mutable private
Referenced by GetDescription(), GetSelectedChannelGroupMember(), HandleProgrammeGrid(), OnMouseEvent(), ScrollToBlockOffset(), ScrollToChannelOffset(), SetBlock(), SetChannel(), SetTimelineItems(), UpdateItems(), UpdateLayout(), and ValidateOffset().
m_focusedChannelLayout
CGUIListItemLayout* PVR::CGUIEPGGridContainer::m_focusedChannelLayout = nullptr private
Referenced by GetCurrentLayouts(), HandleChannels(), and UpdateLayout().
m_focusedChannelLayouts
std::vector<CGUIListItemLayout> PVR::CGUIEPGGridContainer::m_focusedChannelLayouts private
Referenced by GetCurrentLayouts(), and LoadLayout().
m_focusedProgrammeLayout
CGUIListItemLayout* PVR::CGUIEPGGridContainer::m_focusedProgrammeLayout = nullptr private
Referenced by GetCurrentLayouts(), HandleProgrammeGrid(), SelectItemFromPoint(), and UpdateLayout().
m_focusedProgrammeLayouts
std::vector<CGUIListItemLayout> PVR::CGUIEPGGridContainer::m_focusedProgrammeLayouts private
Referenced by GetCurrentLayouts(), and LoadLayout().
m_gridHeight
float PVR::CGUIEPGGridContainer::m_gridHeight = 0 private
width of the epg grid control
Referenced by GetCurrentTimePositionOnPage(), GetProgressIndicatorHeight(), HandleChannels(), HandleProgrammeGrid(), HandleRuler(), Process(), and UpdateLayout().
m_gridModel
std::unique_ptr<CGUIEPGGridContainerModel> PVR::CGUIEPGGridContainer::m_gridModel private
Referenced by ChannelScroll(), GetCurrentTimeLineItems(), GetCurrentTimePositionOnPage(), GetDescription(), GetItem(), GetLabel(), GetListItem(), GetNextItem(), GetPrevItem(), GetSelectedChannelGroupMember(), GetSelectedDate(), GetSelectedGridItem(), GoToBlock(), GoToBottom(), GoToChannel(), GoToDate(), GoToEnd(), GoToLastChannel(), GoToMostRight(), HandleChannels(), HandleProgrammeGrid(), HandleRuler(), HandleRulerDate(), HasData(), OnAction(), OnDown(), OnLeft(), OnMessage(), OnRight(), OnUp(), Process(), ScrollToBlockOffset(), SelectItemFromPoint(), SetChannel(), SetChannel(), SetChannel(), SetChannel(), SetItem(), UpdateItems(), and ValidateOffset().
m_gridPosX
float PVR::CGUIEPGGridContainer::m_gridPosX = 0 private
width of the channel item
Referenced by HandleProgrammeGrid(), OnMouseClick(), OnMouseDoubleClick(), OnMouseOver(), and UpdateLayout().
m_gridPosY
float PVR::CGUIEPGGridContainer::m_gridPosY = 0 private
X position of first grid item.
Referenced by HandleProgrammeGrid(), OnMouseClick(), OnMouseDoubleClick(), OnMouseOver(), and UpdateLayout().
m_gridWidth
float PVR::CGUIEPGGridContainer::m_gridWidth = 0 private
Y position of first grid item.
Referenced by GetCurrentTimePositionOnPage(), GetProgressIndicatorWidth(), HandleChannels(), HandleProgrammeGrid(), HandleRuler(), and UpdateLayout().
m_guiProgressIndicatorTexture
std::unique_ptr<CGUITexture> PVR::CGUIEPGGridContainer::m_guiProgressIndicatorTexture private
Referenced by AllocResources(), FreeResources(), ProcessProgressIndicator(), and RenderProgressIndicator().
m_guiProgressIndicatorTextureDepth
uint32_t PVR::CGUIEPGGridContainer::m_guiProgressIndicatorTextureDepth {0} private
Referenced by AssignDepth(), and RenderProgressIndicator().
m_itemStartBlock
int PVR::CGUIEPGGridContainer::m_itemStartBlock = 0 private
Referenced by SetItem(), and UpdateBlock().
m_lastChannel
std::shared_ptr<CFileItem> PVR::CGUIEPGGridContainer::m_lastChannel private
Referenced by HandleProgrammeGrid(), and UpdateItems().
m_lastItem
std::shared_ptr<CFileItem> PVR::CGUIEPGGridContainer::m_lastItem private
Referenced by HandleChannels(), and UpdateItems().
m_orientation
ORIENTATION PVR::CGUIEPGGridContainer::m_orientation private
Referenced by GetChannelScrollOffset(), GetChannelScrollOffsetPos(), GetCurrentTimePositionOnPage(), GetProgressIndicatorHeight(), GetProgressIndicatorWidth(), GoToBottom(), GoToMostLeft(), GoToMostRight(), GoToTop(), HandleChannels(), HandleProgrammeGrid(), HandleRuler(), OnAction(), OnDown(), OnLeft(), OnMessage(), OnMouseEvent(), OnRight(), OnUp(), Process(), ProcessItem(), ScrollToChannelOffset(), SelectItemFromPoint(), UpdateLayout(), UpdateScrollOffset(), and ValidateOffset().
m_pageControl
int PVR::CGUIEPGGridContainer::m_pageControl = 0 private
Referenced by OnMessage(), Process(), and SetPageControl().
m_programmeLayout
CGUIListItemLayout* PVR::CGUIEPGGridContainer::m_programmeLayout = nullptr private
Referenced by GetCurrentLayouts(), HandleChannels(), HandleProgrammeGrid(), ScrollToChannelOffset(), SelectItemFromPoint(), UpdateLayout(), UpdateScrollOffset(), and ValidateOffset().
m_programmeLayouts
std::vector<CGUIListItemLayout> PVR::CGUIEPGGridContainer::m_programmeLayouts private
Referenced by GetCurrentLayouts(), and LoadLayout().
m_programmeScrollLastTime
int PVR::CGUIEPGGridContainer::m_programmeScrollLastTime = 0 private
Referenced by UpdateScrollOffset().
m_programmeScrollOffset
float PVR::CGUIEPGGridContainer::m_programmeScrollOffset = 0 private
Referenced by GetProgrammeScrollOffset(), GetProgrammeScrollOffsetPos(), OnMouseEvent(), Process(), ScrollToBlockOffset(), UpdateLayout(), UpdateScrollOffset(), and ValidateOffset().
m_programmeScrollSpeed
float PVR::CGUIEPGGridContainer::m_programmeScrollSpeed = 0 private
Referenced by GetProgrammeCacheOffsets(), ScrollToBlockOffset(), and UpdateScrollOffset().
m_programmesPerPage
int PVR::CGUIEPGGridContainer::m_programmesPerPage = 0 private
Referenced by HandleProgrammeGrid(), and UpdateLayout().
m_renderOffset
CPoint PVR::CGUIEPGGridContainer::m_renderOffset private
render offset of the first item in the list
See also
SetRenderOffset
Referenced by HandleChannels(), HandleProgrammeGrid(), HandleRuler(), ProcessProgressIndicator(), and SetRenderOffset().
m_rulerDateHeight
float PVR::CGUIEPGGridContainer::m_rulerDateHeight = 0 private
Referenced by HandleRulerDate(), and UpdateLayout().
m_rulerDateLayout
CGUIListItemLayout* PVR::CGUIEPGGridContainer::m_rulerDateLayout = nullptr private
Referenced by GetCurrentLayouts(), HandleRuler(), HandleRulerDate(), and UpdateLayout().
m_rulerDateLayouts
std::vector<CGUIListItemLayout> PVR::CGUIEPGGridContainer::m_rulerDateLayouts private
Referenced by GetCurrentLayouts(), and LoadLayout().
m_rulerDateWidth
float PVR::CGUIEPGGridContainer::m_rulerDateWidth = 0 private
height of ruler date item
Referenced by HandleRulerDate(), and UpdateLayout().
m_rulerHeight
float PVR::CGUIEPGGridContainer::m_rulerHeight = 0 private
Y position of first ruler item.
Referenced by GetProgressIndicatorHeight(), HandleRuler(), and UpdateLayout().
m_rulerLayout
CGUIListItemLayout* PVR::CGUIEPGGridContainer::m_rulerLayout = nullptr private
Referenced by GetCurrentLayouts(), HandleRuler(), and UpdateLayout().
m_rulerLayouts
std::vector<CGUIListItemLayout> PVR::CGUIEPGGridContainer::m_rulerLayouts private
Referenced by GetCurrentLayouts(), and LoadLayout().
m_rulerPosX
float PVR::CGUIEPGGridContainer::m_rulerPosX = 0 private
width of ruler date item
Referenced by HandleRuler(), ProcessProgressIndicator(), RenderProgressIndicator(), and UpdateLayout().
m_rulerPosY
float PVR::CGUIEPGGridContainer::m_rulerPosY = 0 private
X position of first ruler item.
Referenced by HandleRuler(), ProcessProgressIndicator(), RenderProgressIndicator(), and UpdateLayout().
m_rulerUnit
int PVR::CGUIEPGGridContainer::m_rulerUnit private
Referenced by HandleRuler(), HandleRulerDate(), SetTimelineItems(), and UpdateLayout().
m_rulerWidth
float PVR::CGUIEPGGridContainer::m_rulerWidth = 0 private
height of the scrolling timeline above the ruler items
Referenced by GetProgressIndicatorWidth(), HandleRuler(), and UpdateLayout().
m_scrollTime
int PVR::CGUIEPGGridContainer::m_scrollTime private
Referenced by ScrollToBlockOffset(), and ScrollToChannelOffset().
m_updatedGridModel
std::unique_ptr<CGUIEPGGridContainerModel> PVR::CGUIEPGGridContainer::m_updatedGridModel private
Referenced by SetTimelineItems(), and UpdateItems().
The documentation for this class was generated from the following files:
GUIEPGGridContainer.h
GUIEPGGridContainer.cpp