Kodi Documentation: BitstreamConverter.cpp File Reference
BitstreamConverter.cpp File Reference
#include "utils/log.h"
#include <assert.h>
#include "BitstreamConverter.h"
#include "HevcSei.h"
#include <algorithm>
#include <libavutil/intreadwrite.h>
Macros
#define UINT16_MAX (65535U)
Enumerations
enum {
AVC_NAL_SLICE =1 , AVC_NAL_DPA , AVC_NAL_DPB , AVC_NAL_DPC ,
AVC_NAL_IDR_SLICE , AVC_NAL_SEI , AVC_NAL_SPS , AVC_NAL_PPS ,
AVC_NAL_AUD , AVC_NAL_END_SEQUENCE , AVC_NAL_END_STREAM , AVC_NAL_FILLER_DATA ,
AVC_NAL_SPS_EXT , AVC_NAL_AUXILIARY_SLICE =19
}
enum {
HEVC_NAL_TRAIL_N = 0 , HEVC_NAL_TRAIL_R = 1 , HEVC_NAL_TSA_N = 2 , HEVC_NAL_TSA_R = 3 ,
HEVC_NAL_STSA_N = 4 , HEVC_NAL_STSA_R = 5 , HEVC_NAL_RADL_N = 6 , HEVC_NAL_RADL_R = 7 ,
HEVC_NAL_RASL_N = 8 , HEVC_NAL_RASL_R = 9 , HEVC_NAL_BLA_W_LP = 16 , HEVC_NAL_BLA_W_RADL = 17 ,
HEVC_NAL_BLA_N_LP = 18 , HEVC_NAL_IDR_W_RADL = 19 , HEVC_NAL_IDR_N_LP = 20 , HEVC_NAL_CRA_NUT = 21 ,
HEVC_NAL_VPS = 32 , HEVC_NAL_SPS = 33 , HEVC_NAL_PPS = 34 , HEVC_NAL_AUD = 35 ,
HEVC_NAL_EOS_NUT = 36 , HEVC_NAL_EOB_NUT = 37 , HEVC_NAL_FD_NUT = 38 , HEVC_NAL_SEI_PREFIX = 39 ,
HEVC_NAL_SEI_SUFFIX = 40 , HEVC_NAL_UNSPEC62 = 62 , HEVC_NAL_UNSPEC63 = 63
}
enum {
SEI_BUFFERING_PERIOD = 0 , SEI_PIC_TIMING , SEI_PAN_SCAN_RECT , SEI_FILLER_PAYLOAD ,
SEI_USER_DATA_REGISTERED_ITU_T_T35 , SEI_USER_DATA_UNREGISTERED , SEI_RECOVERY_POINT , SEI_DEC_REF_PIC_MARKING_REPETITION ,
SEI_SPARE_PIC , SEI_SCENE_INFO , SEI_SUB_SEQ_INFO , SEI_SUB_SEQ_LAYER_CHARACTERISTICS ,
SEI_SUB_SEQ_CHARACTERISTICS , SEI_FULL_FRAME_FREEZE , SEI_FULL_FRAME_FREEZE_RELEASE , SEI_FULL_FRAME_SNAPSHOT ,
SEI_PROGRESSIVE_REFINEMENT_SEGMENT_START , SEI_PROGRESSIVE_REFINEMENT_SEGMENT_END , SEI_MOTION_CONSTRAINED_SLICE_GROUP_SET , SEI_FILM_GRAIN_CHARACTERISTICS ,
SEI_DEBLOCKING_FILTER_DISPLAY_PREFERENCE , SEI_STEREO_VIDEO_INFO , SEI_POST_FILTER_HINTS , SEI_TONE_MAPPING
}
Functions
static void nal_bs_init (nal_bitstream *bs, const uint8_t *data, size_t size)
static uint32_t nal_bs_read (nal_bitstream *bs, int n)
static bool nal_bs_eos (nal_bitstream *bs)
static int nal_bs_read_ue (nal_bitstream *bs)
static const uint8_t * avc_find_startcode_internal (const uint8_t *p, const uint8_t *end)
static const uint8_t * avc_find_startcode (const uint8_t *p, const uint8_t *end)
static bool has_sei_recovery_point (const uint8_t *p, const uint8_t *end)
Macro Definition Documentation
UINT16_MAX
#define UINT16_MAX (65535U)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
AVC_NAL_SLICE
AVC_NAL_DPA
AVC_NAL_DPB
AVC_NAL_DPC
AVC_NAL_IDR_SLICE
AVC_NAL_SEI
AVC_NAL_SPS
AVC_NAL_PPS
AVC_NAL_AUD
AVC_NAL_END_SEQUENCE
AVC_NAL_END_STREAM
AVC_NAL_FILLER_DATA
AVC_NAL_SPS_EXT
AVC_NAL_AUXILIARY_SLICE
anonymous enum
anonymous enum
Enumerator
HEVC_NAL_TRAIL_N
HEVC_NAL_TRAIL_R
HEVC_NAL_TSA_N
HEVC_NAL_TSA_R
HEVC_NAL_STSA_N
HEVC_NAL_STSA_R
HEVC_NAL_RADL_N
HEVC_NAL_RADL_R
HEVC_NAL_RASL_N
HEVC_NAL_RASL_R
HEVC_NAL_BLA_W_LP
HEVC_NAL_BLA_W_RADL
HEVC_NAL_BLA_N_LP
HEVC_NAL_IDR_W_RADL
HEVC_NAL_IDR_N_LP
HEVC_NAL_CRA_NUT
HEVC_NAL_VPS
HEVC_NAL_SPS
HEVC_NAL_PPS
HEVC_NAL_AUD
HEVC_NAL_EOS_NUT
HEVC_NAL_EOB_NUT
HEVC_NAL_FD_NUT
HEVC_NAL_SEI_PREFIX
HEVC_NAL_SEI_SUFFIX
HEVC_NAL_UNSPEC62
HEVC_NAL_UNSPEC63
anonymous enum
anonymous enum
Enumerator
SEI_BUFFERING_PERIOD
SEI_PIC_TIMING
SEI_PAN_SCAN_RECT
SEI_FILLER_PAYLOAD
SEI_USER_DATA_REGISTERED_ITU_T_T35
SEI_USER_DATA_UNREGISTERED
SEI_RECOVERY_POINT
SEI_DEC_REF_PIC_MARKING_REPETITION
SEI_SPARE_PIC
SEI_SCENE_INFO
SEI_SUB_SEQ_INFO
SEI_SUB_SEQ_LAYER_CHARACTERISTICS
SEI_SUB_SEQ_CHARACTERISTICS
SEI_FULL_FRAME_FREEZE
SEI_FULL_FRAME_FREEZE_RELEASE
SEI_FULL_FRAME_SNAPSHOT
SEI_PROGRESSIVE_REFINEMENT_SEGMENT_START
SEI_PROGRESSIVE_REFINEMENT_SEGMENT_END
SEI_MOTION_CONSTRAINED_SLICE_GROUP_SET
SEI_FILM_GRAIN_CHARACTERISTICS
SEI_DEBLOCKING_FILTER_DISPLAY_PREFERENCE
SEI_STEREO_VIDEO_INFO
SEI_POST_FILTER_HINTS
SEI_TONE_MAPPING
Function Documentation
avc_find_startcode()
static const uint8_t * avc_find_startcode (const uint8_t * p, const uint8_t * end) static
References avc_find_startcode_internal(), and end().
Referenced by CBitstreamConverter::avc_parse_nal_units(), and CBitstreamConverter::mpeg2_sequence_header().
avc_find_startcode_internal()
static const uint8_t * avc_find_startcode_internal (const uint8_t * p, const uint8_t * end) static
References end().
Referenced by avc_find_startcode().
has_sei_recovery_point()
static bool has_sei_recovery_point (const uint8_t * p, const uint8_t * end) static
References end(), nal_bs_init(), nal_bs_read_ue(), and SEI_RECOVERY_POINT.
Referenced by CBitstreamConverter::BitstreamConvert(), and CBitstreamParser::CanStartDecode().
nal_bs_eos()
static bool nal_bs_eos (nal_bitstream * bs) static
References nal_bitstream::data, nal_bitstream::end, and nal_bitstream::head.
Referenced by nal_bs_read_ue().
nal_bs_init()
static void nal_bs_init (nal_bitstream * bs, const uint8_t * data, size_t size) static
References nal_bitstream::cache, nal_bitstream::data, data(), nal_bitstream::end, and nal_bitstream::head.
Referenced by has_sei_recovery_point(), and CBitstreamConverter::mpeg2_sequence_header().
nal_bs_read()
static uint32_t nal_bs_read (nal_bitstream * bs, int n) static
References nal_bitstream::cache, nal_bitstream::data, nal_bitstream::end, and nal_bitstream::head.
Referenced by CBitstreamConverter::mpeg2_sequence_header(), and nal_bs_read_ue().
nal_bs_read_ue()
static int nal_bs_read_ue (nal_bitstream * bs) static
References nal_bs_eos(), and nal_bs_read().
Referenced by has_sei_recovery_point().