Kodi Documentation: CDBusError Class Reference
CDBusError Class Reference
#include <DBusUtil.h>
Public Member Functions
CDBusError ()
~CDBusError ()
operator DBusError * ()
bool IsSet () const
void Reset ()
operator bool ()
operator bool () const
std::string Name () const
std::string Message () const
void Log (std::string const &message="DBus error") const
void Log (int level, std::string const &message="DBus error") const
Private Member Functions
CDBusError (CDBusError const &other)=delete
CDBusError & operator= (CDBusError const &other)=delete
Private Attributes
DBusError m_error
Constructor & Destructor Documentation
CDBusError() [1/2]
CDBusError::CDBusError ()
~CDBusError()
CDBusError::~CDBusError ()
References Reset().
CDBusError() [2/2]
CDBusError::CDBusError (CDBusError const & other) private delete
Member Function Documentation
IsSet()
bool CDBusError::IsSet () const
Log() [1/2]
void CDBusError::Log (int level, std::string const & message = "DBus error") const
References CLog::Log().
Log() [2/2]
void CDBusError::Log (std::string const & message = "DBus error") const
References LOGERROR.
Referenced by CLogindUPowerSyscall::CLogindUPowerSyscall(), CDBusConnection::Connect(), CUDisks2Provider::CUDisks2Provider(), CUDisksProvider::CUDisksProvider(), CUPowerSyscall::CUPowerSyscall(), CDBusMessage::Send(), and CDBusUtil::TryMethodCall().
Message()
std::string CDBusError::Message () const
Name()
std::string CDBusError::Name () const
Referenced by KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::IsAvailable().
operator bool() [1/2]
CDBusError::operator bool ()
operator bool() [2/2]
CDBusError::operator bool () const
operator DBusError *()
CDBusError::operator DBusError * ()
operator=()
CDBusError & CDBusError::operator= (CDBusError const & other) private delete
Reset()
void CDBusError::Reset ()
Reset this error wrapper
If there was an error, it was handled and this error wrapper should be used again in a new call, it must be reset before that call.
Member Data Documentation
m_error
DBusError CDBusError::m_error private
The documentation for this class was generated from the following files:
DBusUtil.h
DBusUtil.cpp