Kodi Documentation: ADDON::Interface_GUIControlEdit Struct Reference
ADDON::Interface_GUIControlEdit Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Edit.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
callback functions from add-on to kodi
static void set_enabled (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled)
static void set_input_type (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int type, const char *heading)
static void set_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *label)
static char * get_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *text)
static char * get_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_cursor_position (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, unsigned int position)
static unsigned int get_cursor_position (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold general gui functions and initialize also all other gui related types not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/controls/Edit.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIControlEdit::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_edit, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
get_cursor_position()
unsigned int ADDON::Interface_GUIControlEdit::get_cursor_position (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUIEditControl::GetCursorPosition(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_label()
char * ADDON::Interface_GUIControlEdit::get_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUIButtonControl::GetLabel(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_text()
char * ADDON::Interface_GUIControlEdit::get_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUIEditControl::GetLabel2(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIControlEdit::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_edit, get_cursor_position(), AddonToKodiFuncTable_kodi_gui_control_edit::get_cursor_position, get_label(), AddonToKodiFuncTable_kodi_gui_control_edit::get_label, get_text(), AddonToKodiFuncTable_kodi_gui_control_edit::get_text, AddonToKodiFuncTable_Addon::kodi_gui, set_cursor_position(), AddonToKodiFuncTable_kodi_gui_control_edit::set_cursor_position, set_enabled(), AddonToKodiFuncTable_kodi_gui_control_edit::set_enabled, set_input_type(), AddonToKodiFuncTable_kodi_gui_control_edit::set_input_type, set_label(), AddonToKodiFuncTable_kodi_gui_control_edit::set_label, set_text(), AddonToKodiFuncTable_kodi_gui_control_edit::set_text, set_visible(), AddonToKodiFuncTable_kodi_gui_control_edit::set_visible, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
set_cursor_position()
void ADDON::Interface_GUIControlEdit::set_cursor_position (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, unsigned int position) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIEditControl::SetCursorPosition().
Referenced by Init().
set_enabled()
void ADDON::Interface_GUIControlEdit::set_enabled (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetEnabled().
Referenced by Init().
set_input_type()
void ADDON::Interface_GUIControlEdit::set_input_type (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int type, const char * heading) static
References ADDON_INPUT_TYPE_DATE, ADDON_INPUT_TYPE_FILTER, ADDON_INPUT_TYPE_IPADDRESS, ADDON_INPUT_TYPE_NUMBER, ADDON_INPUT_TYPE_PASSWORD, ADDON_INPUT_TYPE_PASSWORD_MD5, ADDON_INPUT_TYPE_READONLY, ADDON_INPUT_TYPE_SEARCH, ADDON_INPUT_TYPE_SECONDS, ADDON_INPUT_TYPE_TEXT, ADDON_INPUT_TYPE_TIME, ADDON::CAddon::ID(), CGUIEditControl::INPUT_TYPE_DATE, CGUIEditControl::INPUT_TYPE_FILTER, CGUIEditControl::INPUT_TYPE_IPADDRESS, CGUIEditControl::INPUT_TYPE_NUMBER, CGUIEditControl::INPUT_TYPE_PASSWORD, CGUIEditControl::INPUT_TYPE_PASSWORD_MD5, CGUIEditControl::INPUT_TYPE_PASSWORD_NUMBER_VERIFY_NEW, CGUIEditControl::INPUT_TYPE_SEARCH, CGUIEditControl::INPUT_TYPE_SECONDS, CGUIEditControl::INPUT_TYPE_TEXT, CGUIEditControl::INPUT_TYPE_TIME, CLog::Log(), LOGERROR, and CGUIEditControl::SetInputType().
Referenced by Init().
set_label()
void ADDON::Interface_GUIControlEdit::set_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * label) static
References ADDON::CAddon::ID(), label, CLog::Log(), LOGERROR, and CGUIEditControl::SetLabel().
Referenced by Init().
set_text()
void ADDON::Interface_GUIControlEdit::set_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * text) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUIEditControl::SetLabel2(), and text.
Referenced by Init().
set_visible()
void ADDON::Interface_GUIControlEdit::set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetVisible().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/controls/edit.h
Edit.cpp