Kodi Documentation: CAEUtil Class Reference
CAEUtil Class Reference
#include <AEUtil.h>
Static Public Member Functions
static CAEChannelInfo GuessChLayout (const unsigned int channels)
static const char * GetStdChLayoutName (const enum AEStdChLayout layout)
static unsigned int DataFormatToBits (const enum AEDataFormat dataFormat)
static unsigned int DataFormatToUsedBits (const enum AEDataFormat dataFormat)
static unsigned int DataFormatToDitherBits (const enum AEDataFormat dataFormat)
static const char * DataFormatToStr (const enum AEDataFormat dataFormat)
static const char * StreamTypeToStr (const enum CAEStreamInfo::DataType dataType)
static float PercentToGain (const float value)
convert a volume percentage (as a proportion) to a dB gain We assume a dB range of 60dB, i.e. assume that 0% volume corresponds to a reduction of 60dB.
static float GainToPercent (const float gain)
convert a dB gain to volume percentage (as a proportion) We assume a dB range of 60dB, i.e. assume that 0% volume corresponds to a reduction of 60dB.
static float GainToScale (const float dB)
convert a dB gain to a scale factor for audio manipulation Inverts gain = 20 log_10(scale)
static float ScaleToGain (const float scale)
convert a scale factor to dB gain for audio manipulation Inverts GainToScale result
static void ClampArray (float *data, uint32_t count)
static bool S16NeedsByteSwap (AEDataFormat in, AEDataFormat out)
static uint64_t GetAVChannelLayout (const CAEChannelInfo &info)
static CAEChannelInfo GetAEChannelLayout (uint64_t layout)
static AVSampleFormat GetAVSampleFormat (AEDataFormat format)
static uint64_t GetAVChannelMask (enum AEChannel aechannel)
static enum AVChannel GetAVChannel (enum AEChannel aechannel)
static int GetAVChannelIndex (enum AEChannel aechannel, uint64_t layout)
static void GenerateSilence (AEDataFormat format, unsigned int frameSize, void *buffer, unsigned int frames)
Static Private Member Functions
static float SoftClamp (const float x)
Member Function Documentation
ClampArray()
void CAEUtil::ClampArray (float * data, uint32_t count) static
References data(), and SoftClamp().
Referenced by ActiveAE::CActiveAE::RunStages().
DataFormatToBits()
unsigned int CAEUtil::DataFormatToBits (const enum AEDataFormat dataFormat) static
References AE_FMT_MAX, and formats.
Referenced by CDVDAudioCodecAndroidMediaCodec::AddData(), KODI::RETRO::CRetroPlayerAudio::AddStreamData(), CAESinkFactoryWin::BuildWaveFormatExtensible(), ActiveAE::CActiveAE::Configure(), DataFormatToUsedBits(), CAESinkWASAPI::EnumerateDevicesEx(), CAESinkXAudio::EnumerateDevicesEx(), CDVDAudioCodecAndroidMediaCodec::GetData(), CDVDAudioCodecFFmpeg::GetData(), CDVDAudioCodecFFmpeg::GetData(), VideoPlayerCodec::Init(), CAEEncoderFFmpeg::Initialize(), CAESinkAUDIOTRACK::Initialize(), CAESinkDARWINIOS::Initialize(), CAESinkDARWINOSX::Initialize(), CAESinkDARWINTVOS::Initialize(), CAESinkOSS::Initialize(), CAESinkALSA::InitializeHW(), ActiveAE::CActiveAE::MakeStream(), PAPlayer::QueueNextFileEx(), and AEDeviceEnumerationOSX::ScoreFormat().
DataFormatToDitherBits()
unsigned int CAEUtil::DataFormatToDitherBits (const enum AEDataFormat dataFormat) static
References AE_FMT_S24NE3, and AE_FMT_S24NE4MSB.
Referenced by ActiveAE::CActiveAEBufferPoolResample::ChangeResampler(), ActiveAE::CActiveAEBufferPool::Create(), ActiveAE::CActiveAESink::GenerateNoise(), VideoPlayerCodec::Init(), ActiveAE::CActiveAEStream::InitRemapper(), ActiveAE::CActiveAESink::OpenSink(), and ActiveAE::CActiveAE::ResampleSound().
DataFormatToStr()
const char * CAEUtil::DataFormatToStr (const enum AEDataFormat dataFormat) static
References AE_FMT_MAX, and formats.
Referenced by AEDeviceEnumerationOSX::FindSuitableFormatForStream(), CAESinkDirectSound::Initialize(), CAESinkAUDIOTRACK::Initialize(), CAESinkOSS::Initialize(), CAESinkPULSE::Initialize(), CAESinkXAudio::Initialize(), CAESinkWASAPI::InitializeExclusive(), CAESinkALSA::InitializeHW(), CAESinkXAudio::InitializeInternal(), ActiveAE::CActiveAESink::OpenSink(), KODI::RETRO::CRetroPlayerAudio::OpenStream(), and CAEDeviceInfo::operator std::string().
DataFormatToUsedBits()
unsigned int CAEUtil::DataFormatToUsedBits (const enum AEDataFormat dataFormat) static
References AE_FMT_S24BE4, AE_FMT_S24LE4, AE_FMT_S24NE4, AE_FMT_S24NE4MSB, and DataFormatToBits().
Referenced by ActiveAE::CActiveAEBufferPoolResample::ChangeResampler(), ActiveAE::CActiveAEBufferPool::Create(), ActiveAE::CActiveAESink::GenerateNoise(), VideoPlayerCodec::Init(), ActiveAE::CActiveAEStream::InitRemapper(), ActiveAE::CActiveAESink::OpenSink(), KODI::RETRO::CRetroPlayerAudio::OpenStream(), and ActiveAE::CActiveAE::ResampleSound().
GainToPercent()
static float CAEUtil::GainToPercent (const float gain) inline static
convert a dB gain to volume percentage (as a proportion) We assume a dB range of 60dB, i.e. assume that 0% volume corresponds to a reduction of 60dB.
Parameters
the corresponding gain in dB from -60dB .. 0dB.
Returns
value the volume from 0..1
See also
ScaleToGain
GainToScale()
static float CAEUtil::GainToScale (const float dB) inline static
convert a dB gain to a scale factor for audio manipulation Inverts gain = 20 log_10(scale)
Parameters
dB the gain in decibels.
Returns
the scale factor (equivalent to a voltage multiplier).
See also
PercentToGain
Referenced by ActiveAE::CActiveAE::StateMachine().
GenerateSilence()
void CAEUtil::GenerateSilence (AEDataFormat format, unsigned int frameSize, void * buffer, unsigned int frames) static
References AE_FMT_U8, and AE_FMT_U8P.
Referenced by CAESinkXAudio::BuildXAudio2Buffer().
GetAEChannelLayout()
CAEChannelInfo CAEUtil::GetAEChannelLayout (uint64_t layout) static
References AE_CH_BC, AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, AE_CH_TFR, and CAEChannelInfo::Reset().
Referenced by ActiveAE::CActiveAE::Configure(), and CVideoPlayerAudio::ProcessDecoderOutput().
GetAVChannel()
enum AVChannel CAEUtil::GetAVChannel (enum AEChannel aechannel) static
References AE_CH_BC, AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_CH_TBC, AE_CH_TBL, AE_CH_TBR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, and AE_CH_TFR.
Referenced by GetAVChannelIndex(), and GetAVChannelMask().
GetAVChannelIndex()
int CAEUtil::GetAVChannelIndex (enum AEChannel aechannel, uint64_t layout) static
References GetAVChannel().
Referenced by ActiveAE::CActiveAEResampleFFMPEG::Init(), and ActiveAE::CActiveAEStream::InitRemapper().
GetAVChannelLayout()
uint64_t CAEUtil::GetAVChannelLayout (const CAEChannelInfo & info) static
References AE_CH_BC, AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_CH_TBC, AE_CH_TBL, AE_CH_TBR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, and AE_CH_TFR.
Referenced by ActiveAE::CActiveAEBufferPoolResample::ChangeResampler(), ActiveAE::CActiveAE::Configure(), ActiveAE::CActiveAEBufferPool::Create(), ActiveAE::CActiveAEBufferPoolAtempo::Create(), VideoPlayerCodec::Init(), ActiveAE::CActiveAEStream::InitRemapper(), ActiveAE::CActiveAESink::OpenSink(), and ActiveAE::CActiveAE::ResampleSound().
GetAVChannelMask()
uint64_t CAEUtil::GetAVChannelMask (enum AEChannel aechannel) static
References GetAVChannel().
Referenced by ActiveAE::CActiveAEStream::InitRemapper().
GetAVSampleFormat()
AVSampleFormat CAEUtil::GetAVSampleFormat (AEDataFormat format) static
References AE_FMT_DOUBLE, AE_FMT_DOUBLEP, AE_FMT_FLOAT, AE_FMT_FLOATP, AE_FMT_RAW, AE_FMT_S16NE, AE_FMT_S16NEP, AE_FMT_S24NE3, AE_FMT_S24NE3P, AE_FMT_S24NE4, AE_FMT_S24NE4MSB, AE_FMT_S24NE4MSBP, AE_FMT_S24NE4P, AE_FMT_S32NE, AE_FMT_S32NEP, AE_FMT_U8, AE_FMT_U8P, and AE_IS_PLANAR.
Referenced by ActiveAE::CActiveAEBufferPoolResample::ChangeResampler(), ActiveAE::CActiveAEBufferPool::Create(), ActiveAE::CActiveAEBufferPoolAtempo::Create(), VideoPlayerCodec::Init(), ActiveAE::CActiveAEStream::InitRemapper(), ActiveAE::CActiveAESink::OpenSink(), and ActiveAE::CActiveAE::ResampleSound().
GetStdChLayoutName()
const char * CAEUtil::GetStdChLayoutName (const enum AEStdChLayout layout) static
References AE_CH_LAYOUT_MAX, and layouts.
GuessChLayout()
CAEChannelInfo CAEUtil::GuessChLayout (const unsigned int channels) static
References AE_CH_LAYOUT_1_0, AE_CH_LAYOUT_2_0, AE_CH_LAYOUT_3_0, AE_CH_LAYOUT_4_0, AE_CH_LAYOUT_5_0, AE_CH_LAYOUT_5_1, AE_CH_LAYOUT_7_0, AE_CH_LAYOUT_7_1, CLog::Log(), and LOGWARNING.
Referenced by KODI::ADDONS::CAudioDecoder::Init().
PercentToGain()
static float CAEUtil::PercentToGain (const float value) inline static
convert a volume percentage (as a proportion) to a dB gain We assume a dB range of 60dB, i.e. assume that 0% volume corresponds to a reduction of 60dB.
Parameters
value the volume from 0..1
Returns
the corresponding gain in dB from -60dB .. 0dB.
See also
GainToScale
References value.
Referenced by CGUIDialogAudioSettings::FormatPercentAsDecibel(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel(), CGUIDialogAudioSettings::SettingFormatterPercentAsDecibel(), and ActiveAE::CActiveAE::StateMachine().
S16NeedsByteSwap()
bool CAEUtil::S16NeedsByteSwap (AEDataFormat in, AEDataFormat out) static
References AE_FMT_RAW, AE_FMT_S16BE, AE_FMT_S16LE, and AE_FMT_S16NE.
Referenced by ActiveAE::CActiveAESink::SwapInit().
ScaleToGain()
static float CAEUtil::ScaleToGain (const float scale) inline static
convert a scale factor to dB gain for audio manipulation Inverts GainToScale result
Parameters
the scale factor (equivalent to a voltage multiplier).
Returns
dB the gain in decibels.
See also
GainToScale
SoftClamp()
float CAEUtil::SoftClamp (const float x) inline static private
Referenced by ClampArray().
StreamTypeToStr()
const char * CAEUtil::StreamTypeToStr (const enum CAEStreamInfo::DataType dataType) static
References CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, CAEStreamInfo::STREAM_TYPE_MLP, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Referenced by CAESinkWASAPI::EnumerateDevicesEx(), CAESinkAUDIOTRACK::Initialize(), and CAEDeviceInfo::operator std::string().
The documentation for this class was generated from the following files:
AEUtil.h
AEUtil.cpp