Kodi Documentation: CDVDSubtitleParserSSA Class Reference
CDVDSubtitleParserSSA Class Reference
#include <DVDSubtitleParserSSA.h>
Public Member Functions
CDVDSubtitleParserSSA (std::unique_ptr< CDVDSubtitleStream > &&pStream, const std::string &strFile)
~CDVDSubtitleParserSSA ()=default
bool Open (CDVDStreamInfo &hints) override
Public Member Functions inherited from CDVDSubtitleParserText
CDVDSubtitleParserText (std::unique_ptr< CDVDSubtitleStream > &&stream, const std::string &filename, const char *name)
~CDVDSubtitleParserText () override=default
const std::string & GetName () const override
Public Member Functions inherited from CDVDSubtitleParserCollection
CDVDSubtitleParserCollection (const std::string &strFile)
~CDVDSubtitleParserCollection () override=default
std::shared_ptr< CDVDOverlay > Parse (double iPts) override
void Reset () override
Public Member Functions inherited from CDVDSubtitleParser
virtual ~CDVDSubtitleParser ()=default
Private Attributes
std::shared_ptr< CDVDSubtitlesLibass > m_libass
Additional Inherited Members
Protected Member Functions inherited from CDVDSubtitleParserText
bool Open ()
Protected Attributes inherited from CDVDSubtitleParserText
std::unique_ptr< CDVDSubtitleStream > m_pStream
std::string m_parserName
Protected Attributes inherited from CDVDSubtitleParserCollection
CDVDSubtitleLineCollection m_collection
std::string m_filename
Constructor & Destructor Documentation
CDVDSubtitleParserSSA()
CDVDSubtitleParserSSA::CDVDSubtitleParserSSA (std::unique_ptr< CDVDSubtitleStream > && pStream, const std::string & strFile)
References m_libass.
~CDVDSubtitleParserSSA()
CDVDSubtitleParserSSA::~CDVDSubtitleParserSSA () default
Member Function Documentation
Open()
bool CDVDSubtitleParserSSA::Open (CDVDStreamInfo & hints) override virtual
Implements CDVDSubtitleParser.
References CDVDSubtitleLineCollection::Add(), data(), DVD_NOPTS_VALUE, CServiceBroker::GetSettingsComponent(), CDVDSubtitleParserCollection::m_collection, m_libass, CDVDSubtitleParserText::m_pStream, and CDVDSubtitleParserText::Open().
Member Data Documentation
m_libass
std::shared_ptr<CDVDSubtitlesLibass> CDVDSubtitleParserSSA::m_libass private
Referenced by CDVDSubtitleParserSSA(), and Open().
The documentation for this class was generated from the following files:
DVDSubtitleParserSSA.h
DVDSubtitleParserSSA.cpp