Kodi Documentation: TestRegExp.cpp File Reference
TestRegExp.cpp File Reference
#include "CompileInfo.h"
#include "ServiceBroker.h"
#include "filesystem/File.h"
#include "filesystem/SpecialProtocol.h"
#include "utils/RegExp.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include <gtest/gtest.h>
Classes
class TestRegExpLog
Functions
TEST (TestRegExp, RegFind)
TEST (TestRegExp, InvalidPattern)
TEST (TestRegExp, Unicode)
TEST (TestRegExp, JIT)
TEST (TestRegExp, GetReplaceString)
TEST (TestRegExp, GetFindLen)
TEST (TestRegExp, GetSubCount)
TEST (TestRegExp, GetSubStart)
TEST (TestRegExp, GetCaptureTotal)
TEST (TestRegExp, GetMatch)
TEST (TestRegExp, GetPattern)
TEST (TestRegExp, operatorEqual)
TEST_F (TestRegExpLog, DumpOvector)
Function Documentation
TEST() [1/12]
TEST (TestRegExp , GetCaptureTotal)
References EXPECT_EQ(), EXPECT_TRUE(), CRegExp::GetCaptureTotal(), CRegExp::RegComp(), and CRegExp::RegFind().
TEST() [2/12]
TEST (TestRegExp , GetFindLen)
References EXPECT_EQ(), EXPECT_TRUE(), CRegExp::GetFindLen(), CRegExp::RegComp(), and CRegExp::RegFind().
TEST() [3/12]
TEST (TestRegExp , GetMatch)
References EXPECT_EQ(), EXPECT_TRUE(), CRegExp::GetMatch(), CRegExp::RegComp(), and CRegExp::RegFind().
TEST() [4/12]
TEST (TestRegExp , GetPattern)
References EXPECT_TRUE(), CRegExp::GetPattern(), and CRegExp::RegComp().
TEST() [5/12]
TEST (TestRegExp , GetReplaceString)
References EXPECT_EQ(), EXPECT_TRUE(), CRegExp::GetReplaceString(), CRegExp::RegComp(), and CRegExp::RegFind().
TEST() [6/12]
TEST (TestRegExp , GetSubCount)
References EXPECT_EQ(), EXPECT_TRUE(), CRegExp::GetSubCount(), CRegExp::RegComp(), and CRegExp::RegFind().
TEST() [7/12]
TEST (TestRegExp , GetSubStart)
References EXPECT_EQ(), EXPECT_TRUE(), CRegExp::GetSubStart(), CRegExp::RegComp(), and CRegExp::RegFind().
TEST() [8/12]
TEST (TestRegExp , InvalidPattern)
References CRegExp::RegComp().
TEST() [9/12]
TEST (TestRegExp , JIT)
References EXPECT_EQ(), EXPECT_TRUE(), CRegExp::RegComp(), CRegExp::RegFind(), and CRegExp::StudyWithJitComp.
TEST() [10/12]
TEST (TestRegExp , operatorEqual)
References EXPECT_EQ(), EXPECT_TRUE(), CRegExp::RegComp(), and CRegExp::RegFind().
TEST() [11/12]
TEST (TestRegExp , RegFind)
Todo:
gtest/gtest.h needs to come in before utils/RegExp.h. Investigate why.
References EXPECT_EQ(), EXPECT_TRUE(), CRegExp::RegComp(), and CRegExp::RegFind().
TEST() [12/12]
TEST (TestRegExp , Unicode)
References EXPECT_EQ(), EXPECT_TRUE(), CRegExp::RegComp(), and CRegExp::RegFind().
TEST_F()
TEST_F (TestRegExpLog , DumpOvector)
References CLog::Deinitialize(), XFILE::CFile::Delete(), CRegExp::DumpOvector(), XFILE::CFile::Exists(), EXPECT_EQ(), EXPECT_TRUE(), CCompileInfo::GetAppName(), CServiceBroker::GetLogging(), CLog::Initialize(), LOGDEBUG, CRegExp::RegComp(), CRegExp::RegFind(), KODI::UTILS::StringUtils::ToLower(), and CSpecialProtocol::TranslatePath().