Kodi Documentation: ADDON::CSkinSetting Class Reference
ADDON::CSkinSetting Class Reference abstract
#include <Skin.h>
Public Member Functions
virtual ~CSkinSetting ()=default
bool Serialize (TiXmlElement *parent) const
virtual std::string GetType () const =0
virtual bool Deserialize (const TiXmlElement *element)
Public Attributes
std::string name
Protected Member Functions
virtual bool SerializeSetting (TiXmlElement *element) const =0
Constructor & Destructor Documentation
~CSkinSetting()
virtual ADDON::CSkinSetting::~CSkinSetting () virtual default
Member Function Documentation
Deserialize()
bool ADDON::CSkinSetting::Deserialize (const TiXmlElement * element) virtual
Reimplemented in ADDON::CSkinSettingString, and ADDON::CSkinSettingBool.
References XMLUtils::GetAttribute(), name, XML_ATTR_ID, and XML_ATTR_NAME.
Referenced by ADDON::CSkinSettingString::Deserialize(), and ADDON::CSkinSettingBool::Deserialize().
GetType()
virtual std::string ADDON::CSkinSetting::GetType () const pure virtual
Implemented in ADDON::CSkinSettingString, and ADDON::CSkinSettingBool.
Referenced by Serialize().
Serialize()
bool ADDON::CSkinSetting::Serialize (TiXmlElement * parent) const
References GetType(), name, SerializeSetting(), XML_ATTR_ID, XML_ATTR_TYPE, and XML_SETTING.
SerializeSetting()
virtual bool ADDON::CSkinSetting::SerializeSetting (TiXmlElement * element) const protected pure virtual
Implemented in ADDON::CSkinSettingString, and ADDON::CSkinSettingBool.
Referenced by Serialize().
Member Data Documentation
name
std::string ADDON::CSkinSetting::name
Referenced by Deserialize(), and Serialize().
The documentation for this class was generated from the following files:
Skin.h
Skin.cpp