Kodi Documentation: PVR::CPVRCachedImage Class Reference
PVR::CPVRCachedImage Class Reference
#include <PVRCachedImage.h>
Public Member Functions
CPVRCachedImage ()=delete
virtual ~CPVRCachedImage ()=default
CPVRCachedImage (const std::string &owner)
CPVRCachedImage (const std::string &clientImage, const std::string &owner)
bool operator== (const CPVRCachedImage &right) const
bool operator!= (const CPVRCachedImage &right) const
const std::string & GetClientImage () const
const std::string & GetLocalImage () const
void SetClientImage (const std::string &image)
void SetOwner (const std::string &owner)
Private Member Functions
void UpdateLocalImage ()
Private Attributes
std::string m_clientImage
std::string m_localImage
std::string m_owner
Constructor & Destructor Documentation
CPVRCachedImage() [1/3]
PVR::CPVRCachedImage::CPVRCachedImage () delete
~CPVRCachedImage()
virtual PVR::CPVRCachedImage::~CPVRCachedImage () virtual default
CPVRCachedImage() [2/3]
CPVRCachedImage::CPVRCachedImage (const std::string & owner) explicit
CPVRCachedImage() [3/3]
CPVRCachedImage::CPVRCachedImage (const std::string & clientImage, const std::string & owner)
References UpdateLocalImage().
Member Function Documentation
GetClientImage()
const std::string & PVR::CPVRCachedImage::GetClientImage () const inline
References m_clientImage.
Referenced by PVR::CPVRRecording::ClientFanartPath(), PVR::CPVRChannel::ClientIconPath(), PVR::CPVREpgInfoTag::ClientIconPath(), PVR::CPVRRecording::ClientIconPath(), PVR::CPVREpgInfoTag::ClientParentalRatingIconPath(), PVR::CPVRRecording::ClientParentalRatingIconPath(), PVR::CPVRRecording::ClientThumbnailPath(), PVR::CPVRProvider::GetClientIconPath(), and PVR::CPVRProvider::GetClientThumbPath().
GetLocalImage()
const std::string & PVR::CPVRCachedImage::GetLocalImage () const inline
References m_localImage.
Referenced by PVR::CPVRRecording::FanartPath(), PVR::CPVRProvider::GetIconPath(), PVR::CPVRRecording::GetParentalRatingIcon(), PVR::CPVRProvider::GetThumbPath(), PVR::CPVRProvider::HasThumbPath(), PVR::CPVRChannel::IconPath(), PVR::CPVREpgInfoTag::IconPath(), PVR::CPVRRecording::IconPath(), PVR::CPVREpgInfoTag::ParentalRatingIcon(), and PVR::CPVRRecording::ThumbnailPath().
operator!=()
bool CPVRCachedImage::operator!= (const CPVRCachedImage & right) const
References right.
operator==()
bool CPVRCachedImage::operator== (const CPVRCachedImage & right) const
References m_clientImage, m_localImage, m_owner, and right.
SetClientImage()
void CPVRCachedImage::SetClientImage (const std::string & image)
References LOGERROR, m_clientImage, m_owner, and UpdateLocalImage().
Referenced by PVR::CPVRProvider::SetIconPath(), and PVR::CPVRChannel::SetIconPath().
SetOwner()
void CPVRCachedImage::SetOwner (const std::string & owner)
References m_owner, owner, and UpdateLocalImage().
Referenced by PVR::CPVREpgInfoTag::SetEpgID().
UpdateLocalImage()
void CPVRCachedImage::UpdateLocalImage () private
References m_clientImage, m_localImage, m_owner, and IMAGE_FILES::URLFromFile().
Referenced by CPVRCachedImage(), SetClientImage(), and SetOwner().
Member Data Documentation
m_clientImage
std::string PVR::CPVRCachedImage::m_clientImage private
Referenced by GetClientImage(), operator==(), SetClientImage(), and UpdateLocalImage().
m_localImage
std::string PVR::CPVRCachedImage::m_localImage private
Referenced by GetLocalImage(), operator==(), and UpdateLocalImage().
m_owner
std::string PVR::CPVRCachedImage::m_owner private
Referenced by operator==(), SetClientImage(), SetOwner(), and UpdateLocalImage().
The documentation for this class was generated from the following files:
PVRCachedImage.h
PVRCachedImage.cpp