Kodi Documentation: XFILE::CSmartPlaylistDirectory Class Reference
XFILE::CSmartPlaylistDirectory Class Reference
#include <SmartPlaylistDirectory.h>
Public Member Functions
CSmartPlaylistDirectory ()
~CSmartPlaylistDirectory () override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool AllowAll () const override
Whether to allow all files/folders to be listed.
bool ContainsFiles (const CURL &url) override
bool Remove (const CURL &url) override
Removes the directory.
Public Member Functions inherited from XFILE::IFileDirectory
~IFileDirectory () override=default
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool Create (const CURL &url)
Create the directory.
virtual bool Exists (const CURL &url)
Check for directory existence.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Static Public Member Functions
static bool GetDirectory (const KODI::PLAYLIST::CSmartPlaylist &playlist, CFileItemList &items, const std::string &strBaseDir="", bool filter=false)
static std::string GetPlaylistByName (const std::string &name, const std::string &playlistType)
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Additional Inherited Members
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CSmartPlaylistDirectory()
XFILE::CSmartPlaylistDirectory::CSmartPlaylistDirectory () default
~CSmartPlaylistDirectory()
XFILE::CSmartPlaylistDirectory::~CSmartPlaylistDirectory () override default
Member Function Documentation
AllowAll()
bool XFILE::CSmartPlaylistDirectory::AllowAll () const inline override virtual
Whether to allow all files/folders to be listed.
Returns
Returns true if all files/folder should be listed.
Reimplemented from XFILE::IDirectory.
ContainsFiles()
bool XFILE::CSmartPlaylistDirectory::ContainsFiles (const CURL & url) override virtual
Implements XFILE::IFileDirectory.
GetDirectory() [1/2]
bool XFILE::CSmartPlaylistDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References GetDirectory(), playlist, and CGUIListItem::SetProperty().
Referenced by MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), CGUIMediaWindow::GetAdvanceFilteredItems(), XFILE::CLibraryDirectory::GetDirectory(), and GetDirectory().
GetDirectory() [2/2]
bool XFILE::CSmartPlaylistDirectory::GetDirectory (const KODI::PLAYLIST::CSmartPlaylist & playlist, CFileItemList & items, const std::string & strBaseDir = "", bool filter = false) static
References CFileItemList::Add(), CDbUrl::AddOption(), URIUtils::AddSlashAtEnd(), CFileItemList::Append(), CDbUrl::AppendPath(), CDatabase::Close(), XFILE::CFileDirectoryFactory::Create(), CDbUrl::FromString(), CMediaTypes::FromString(), CMusicDatabase::GetItems(), CVideoDatabase::GetItems(), CServiceBroker::GetSettingsComponent(), KODI::PLAYLIST::CSmartPlaylist::GetType(), KODI::PLAYLIST::CSmartPlaylist::IsEmpty(), SortDescription::limitEnd, CFileItem::m_iprogramCount, MediaTypeAlbum, MediaTypeArtist, MediaTypeEpisode, MediaTypeMovie, MediaTypeSong, MediaTypeTvShow, CMusicDatabase::Open(), CVideoDatabase::Open(), playlist, PROPERTY_GROUP_BY, PROPERTY_GROUP_MIXED, PROPERTY_PATH_DB, PROPERTY_SORT_ASCENDING, PROPERTY_SORT_ORDER, CDbUrl::RemoveOption(), KODI::PLAYLIST::CSmartPlaylist::SaveAsJson(), CFileItemList::SetContent(), KODI::PLAYLIST::CSmartPlaylist::SetGroup(), CFileItem::SetLabel(), CFileItem::SetPath(), CGUIListItem::SetProperty(), CFileItemList::SetSortIgnoreFolders(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CSettings::SETTING_MUSICLIBRARY_USEARTISTSORTNAME, KODI::PLAYLIST::CSmartPlaylist::SetType(), CFileItemList::Size(), CFileItemList::Sort(), SortAttributeIgnoreArticle, SortAttributeIgnoreFolders, SortAttributeNone, SortDescription::sortAttributes, SortAttributeUseArtistSortName, SortDescription::sortBy, SortByLabel, SortByRandom, SortDescription::sortOrder, SortOrderAscending, SortOrderDescending, SortSpecialOnTop, success, and CDbUrl::ToString().
GetPlaylistByName()
std::string XFILE::CSmartPlaylistDirectory::GetPlaylistByName (const std::string & name, const std::string & playlistType) static
References XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::GetDirectory(), URIUtils::GetFileName(), CFileItem::GetPath(), KODI::PLAYLIST::CSmartPlaylist::IsMusicType(), name, playlist, and CFileItemList::Size().
Referenced by KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetVirtualFolders(), and KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetWhereClause().
Remove()
bool XFILE::CSmartPlaylistDirectory::Remove (const CURL & url) override virtual
Removes the directory.
Parameters
url Directory to remove.
Returns
Returns false if not successful
Reimplemented from XFILE::IDirectory.
References XFILE::CFile::Delete().
The documentation for this class was generated from the following files:
SmartPlaylistDirectory.h
SmartPlaylistDirectory.cpp