Kodi Documentation: XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode Class Reference
XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode Class Reference
#include <DirectoryNode.h>
Public Member Functions
virtual ~CDirectoryNode ()
NODE_TYPE GetType () const
bool GetChilds (CFileItemList &items)
virtual NODE_TYPE GetChildType () const
virtual std::string GetLocalizedName () const
void CollectQueryParams (CQueryParams &params) const
CDirectoryNode * GetParent () const
std::string BuildPath () const
virtual bool CanCache () const
Static Public Member Functions
static CDirectoryNode * ParseURL (const std::string &strPath)
static void GetDatabaseInfo (const std::string &strPath, CQueryParams &params)
Protected Member Functions
CDirectoryNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
void AddOptions (const std::string &options)
const std::string & GetName () const
int GetID () const
void RemoveParent ()
virtual bool GetContent (CFileItemList &items) const
Static Protected Member Functions
static CDirectoryNode * CreateNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
Private Attributes
NODE_TYPE m_Type
std::string m_strName
CDirectoryNode * m_pParent
CUrlOptions m_options
Constructor & Destructor Documentation
~CDirectoryNode()
CDirectoryNode::~CDirectoryNode () virtual
References m_pParent.
CDirectoryNode()
CDirectoryNode::CDirectoryNode (NODE_TYPE Type, const std::string & strName, CDirectoryNode * pParent) protected
References m_pParent, m_strName, and m_Type.
Member Function Documentation
AddOptions()
void CDirectoryNode::AddOptions (const std::string & options) protected
References CUrlOptions::AddOptions(), and m_options.
Referenced by ParseURL().
BuildPath()
std::string CDirectoryNode::BuildPath () const
References GetName(), CUrlOptions::GetOptionsString(), GetParent(), m_options, m_pParent, and m_strName.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMusicVideosOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview::GetContent().
CanCache()
bool CDirectoryNode::CanCache () const virtual
Referenced by GetChilds().
CollectQueryParams()
void CDirectoryNode::CollectQueryParams (CQueryParams & params) const
References GetName(), GetParent(), GetType(), m_pParent, m_strName, m_Type, and XFILE::VIDEODATABASEDIRECTORY::CQueryParams::SetQueryParam().
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetChildType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetContentType(), and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetSeasonTitle().
CreateNode()
CDirectoryNode * CDirectoryNode::CreateNode (NODE_TYPE Type, const std::string & strName, CDirectoryNode * pParent) static protected
References XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ACTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_COUNTRY, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_DIRECTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_INPROGRESS_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MOVIES_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_ALBUM, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ROOT, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SEASONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SETS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_STUDIO, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TAGS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TVSHOWS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_VIDEOVERSIONS, and XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_YEAR.
Referenced by GetChilds(), and ParseURL().
GetChilds()
bool CDirectoryNode::GetChilds (CFileItemList & items)
References CFileItemList::CACHE_ALWAYS, CanCache(), CFileItemList::Clear(), CreateNode(), GetChildType(), CFileItemList::Load(), m_options, and CFileItemList::SetCacheToDisc().
GetChildType()
NODE_TYPE CDirectoryNode::GetChildType () const virtual
Reimplemented in XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMusicVideosOverview, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRoot, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows, and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview.
References XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_NONE.
Referenced by GetChilds(), XFILE::CVideoDatabaseDirectory::GetDirectoryParentType(), and ParseURL().
GetContent()
bool CDirectoryNode::GetContent (CFileItemList & items) const protected virtual
Reimplemented in XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMusicVideosOverview, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedEpisodes, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMovies, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMusicVideos, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows, and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview.
GetDatabaseInfo()
void CDirectoryNode::GetDatabaseInfo (const std::string & strPath, CQueryParams & params) static
References ParseURL().
Referenced by UPNP::CUPnPServer::Build(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), XFILE::CVideoDatabaseDirectory::GetLabel(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), XFILE::CVideoDatabaseDirectory::GetQueryParams(), CFileItem::LoadDetails(), and UPNP::CUPnPServer::OnUpdateObject().
GetID()
int CDirectoryNode::GetID () const protected
References m_strName.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetLocalizedName(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows::GetLocalizedName(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetLocalizedName(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetLocalizedName(), and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetSeasonTitle().
GetLocalizedName()
std::string CDirectoryNode::GetLocalizedName () const virtual
Reimplemented in XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMusicVideosOverview, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows, and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetLocalizedName().
GetName()
const std::string & CDirectoryNode::GetName () const protected
References m_strName.
Referenced by BuildPath(), CollectQueryParams(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview::GetChildType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMusicVideosOverview::GetChildType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview::GetChildType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview::GetChildType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMoviesOverview::GetLocalizedName(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeMusicVideosOverview::GetLocalizedName(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview::GetLocalizedName(), and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview::GetLocalizedName().
GetParent()
CDirectoryNode * CDirectoryNode::GetParent () const
References m_pParent.
Referenced by BuildPath(), CollectQueryParams(), XFILE::CVideoDatabaseDirectory::GetDirectoryParentType(), and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetLocalizedName().
GetType()
NODE_TYPE CDirectoryNode::GetType () const
References m_Type.
Referenced by CollectQueryParams(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetChildType(), and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetContentType().
ParseURL()
CDirectoryNode * CDirectoryNode::ParseURL (const std::string & strPath) static
References AddOptions(), CreateNode(), GetChildType(), CURL::GetFileName(), CURL::GetOptions(), XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ROOT, and URIUtils::RemoveSlashAtEnd().
Referenced by CVideoFileItemListModifier::AddQueuingFolder(), XFILE::CVideoDatabaseDirectory::CanCache(), XFILE::CVideoDatabaseDirectory::Exists(), GetDatabaseInfo(), XFILE::CVideoDatabaseDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectoryChildType(), XFILE::CVideoDatabaseDirectory::GetDirectoryParentType(), XFILE::CVideoDatabaseDirectory::GetDirectoryType(), XFILE::CVideoDatabaseDirectory::GetLabel(), and XFILE::CVideoDatabaseDirectory::GetQueryParams().
RemoveParent()
void CDirectoryNode::RemoveParent () protected
References m_pParent.
Member Data Documentation
m_options
CUrlOptions XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::m_options private
Referenced by AddOptions(), BuildPath(), and GetChilds().
m_pParent
CDirectoryNode* XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::m_pParent private
Referenced by BuildPath(), CDirectoryNode(), CollectQueryParams(), GetParent(), RemoveParent(), and ~CDirectoryNode().
m_strName
std::string XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::m_strName private
Referenced by BuildPath(), CDirectoryNode(), CollectQueryParams(), GetID(), and GetName().
m_Type
NODE_TYPE XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::m_Type private
Referenced by CDirectoryNode(), CollectQueryParams(), and GetType().
The documentation for this class was generated from the following files:
VideoDatabaseDirectory/DirectoryNode.h
VideoDatabaseDirectory/DirectoryNode.cpp