Kodi Documentation: KODI::UTILITY::CDigest Class Reference
KODI::UTILITY::CDigest Class Reference
#include <Digest.h>
Classes
struct MdCtxDeleter
Public Types
enum class Type {
MD5 , SHA1 , SHA256 , SHA512 ,
INVALID
}
Public Member Functions
CDigest (Type type)
void Update (std::string const &data)
void Update (void const *data, std::size_t size)
std::string Finalize ()
std::string FinalizeRaw ()
Static Public Member Functions
static std::string TypeToString (Type type)
static Type TypeFromString (std::string const &type)
static std::string Calculate (Type type, std::string const &data)
static std::string Calculate (Type type, void const *data, std::size_t size)
Private Attributes
bool m_finalized {false}
std::unique_ptr< EVP_MD_CTX, MdCtxDeleter > m_context
EVP_MD const * m_md
Detailed Description
Utility class for calculating message digests/hashes, currently using OpenSSL
Member Enumeration Documentation
Type
enum class KODI::UTILITY::CDigest::Type strong
Enumerator
MD5
SHA1
SHA256
SHA512
INVALID
Constructor & Destructor Documentation
CDigest()
KODI::UTILITY::CDigest::CDigest (Type type)
Create a digest calculation object
References m_context, and m_md.
Member Function Documentation
Calculate() [1/2]
std::string KODI::UTILITY::CDigest::Calculate (Type type, std::string const & data) static
Calculate message digest
References data(), and Update().
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().
Calculate() [2/2]
std::string KODI::UTILITY::CDigest::Calculate (Type type, void const * data, std::size_t size) static
Calculate message digest
References data(), and Update().
Finalize()
std::string KODI::UTILITY::CDigest::Finalize ()
Finalize and return the digest
The digest object cannot be used any more after this function has been called.
Returns
digest value as string in lower-case hexadecimal notation
References FinalizeRaw().
FinalizeRaw()
std::string KODI::UTILITY::CDigest::FinalizeRaw ()
Finalize and return the digest
The digest object cannot be used any more after this function has been called.
Returns
digest value as binary std::string
References m_context, m_finalized, and m_md.
Referenced by Finalize().
TypeFromString()
CDigest::Type KODI::UTILITY::CDigest::TypeFromString (std::string const & type) static
Convert digest type string representation to enumeration value
References MD5, SHA1, SHA256, and SHA512.
TypeToString()
std::string KODI::UTILITY::CDigest::TypeToString (Type type) static
Convert type enumeration value to lower-case string representation
References INVALID, MD5, SHA1, SHA256, and SHA512.
Referenced by KODI::UTILITY::operator<<().
Update() [1/2]
void KODI::UTILITY::CDigest::Update (std::string const & data)
Update digest with data
Cannot be called after Finalize has been called
References data(), and Update.
Referenced by Calculate(), Calculate(), CWebSocketV8::calculateKey(), KODI::VIDEO::CVideoInfoScanner::GetFastHash(), CUtil::GetFileDigest(), KODI::VIDEO::CVideoInfoScanner::GetRecursiveFastHash(), TEST(), and TEST().
Update() [2/2]
void KODI::UTILITY::CDigest::Update (void const * data, std::size_t size)
Update digest with data
Cannot be called after Finalize has been called
References data(), m_context, and m_finalized.
Member Data Documentation
m_context
std::unique_ptr<EVP_MD_CTX, MdCtxDeleter> KODI::UTILITY::CDigest::m_context private
Referenced by CDigest(), FinalizeRaw(), and Update().
m_finalized
bool KODI::UTILITY::CDigest::m_finalized {false} private
Referenced by FinalizeRaw(), and Update().
m_md
EVP_MD const* KODI::UTILITY::CDigest::m_md private
Referenced by CDigest(), and FinalizeRaw().
The documentation for this class was generated from the following files:
Digest.h
Digest.cpp