Kodi Documentation: CEdl Class Reference
CEdl Class Reference
#include <Edl.h>
Public Member Functions
CEdl ()
bool ReadEditDecisionLists (const CFileItem &fileItem, float fps)
void Clear ()
bool HasEdits () const
Check if there are any parsed edits in EDL for the current item.
bool HasCuts () const
Check if the edit list has EDL cuts (edits with action CUT)
bool HasSceneMarker () const
std::chrono::milliseconds GetTotalCutTime () const
Get the total cut time removed from the original item because of EDL cuts.
std::chrono::milliseconds GetTimeWithoutCuts (std::chrono::milliseconds seekTime) const
Providing a given seek time, return the actual time without considering cut ranges removed from the file.
std::chrono::milliseconds GetTimeAfterRestoringCuts (std::chrono::milliseconds seekTime) const
Provided a given seek time, return the time after correction with the addition of the already surpassed EDL cut ranges.
const std::vector< EDL::Edit > & GetRawEditList () const
Get the raw EDL edit list.
const std::vector< EDL::Edit > GetEditList () const
Get the EDL edit list.
const std::vector< std::chrono::milliseconds > GetCutMarkers () const
Get the list of EDL cut markers.
const std::vector< std::chrono::milliseconds > GetSceneMarkers () const
Get the list of EDL scene markers.
std::optional< std::unique_ptr< EDL::Edit > > InEdit (std::chrono::milliseconds seekTime)
Check if for the provided seek time is contained within an EDL edit.
std::optional< std::chrono::milliseconds > GetLastEditTime () const
Get the last processed edit time (set during playback when a given edit is surpassed)
void SetLastEditTime (std::chrono::milliseconds editTime)
Set the last processed edit time (set during playback when a given edit is surpassed)
void ResetLastEditTime ()
Reset the last recorded edit time (nullopt)
void SetLastEditActionType (EDL::Action action)
Set the last processed edit action type.
EDL::Action GetLastEditActionType () const
Get the last processed edit action type (set during playback when a given edit is surpassed)
std::optional< std::chrono::milliseconds > GetNextSceneMarker (Direction direction, std::chrono::milliseconds clockTime)
Get the next scene marker with respect to the provided clock time.
Private Member Functions
bool ReadEdl (const std::string &mediaFilePath, float fps)
bool ReadComskip (const std::string &mediaFilePath, float fps)
bool ReadVideoReDo (const std::string &mediaFilePath)
bool ReadBeyondTV (const std::string &mediaFilePath)
bool ReadPvr (const CFileItem &fileItem)
bool AddEdit (const EDL::Edit &newEdit)
Adds an edit to the list of EDL edits.
bool AddSceneMarker (std::chrono::milliseconds sceneMarker)
void MergeShortCommBreaks ()
void AddSceneMarkersAtStartAndEndOfEdits ()
Adds scene markers at the start and end of some edits (currently only for commercial breaks)
Private Attributes
std::chrono::milliseconds m_totalCutTime
std::vector< EDL::Edit > m_vecEdits
std::vector< std::chrono::milliseconds > m_vecSceneMarkers
std::optional< std::chrono::milliseconds > m_lastEditTime
Last processed EDL edit time (ms)
EDL::Action m_lastEditActionType {EDL::EDL_ACTION_NONE}
Last processed EDL edit action type.
Constructor & Destructor Documentation
CEdl()
CEdl::CEdl ()
References Clear().
Member Function Documentation
AddEdit()
bool CEdl::AddEdit (const EDL::Edit & newEdit) private
Adds an edit to the list of EDL edits.
Parameters
newEdit the edit to add
Returns
true if the operation succeeds, false otherwise
References EDL::Edit::action, EDL::Edit::end, CServiceBroker::GetSettingsComponent(), InEdit(), CLog::Log(), LOGDEBUG, LOGERROR, m_totalCutTime, m_vecEdits, and EDL::Edit::start.
Referenced by ReadBeyondTV(), ReadComskip(), ReadEdl(), ReadPvr(), and ReadVideoReDo().
AddSceneMarker()
bool CEdl::AddSceneMarker (std::chrono::milliseconds sceneMarker) private
References InEdit(), CLog::Log(), LOGDEBUG, and m_vecSceneMarkers.
Referenced by AddSceneMarkersAtStartAndEndOfEdits(), ReadEdl(), ReadPvr(), and ReadVideoReDo().
AddSceneMarkersAtStartAndEndOfEdits()
void CEdl::AddSceneMarkersAtStartAndEndOfEdits () private
Adds scene markers at the start and end of some edits (currently only for commercial breaks)
References AddSceneMarker(), and m_vecEdits.
Referenced by ReadEditDecisionLists().
Clear()
void CEdl::Clear ()
References m_lastEditTime, m_totalCutTime, m_vecEdits, and m_vecSceneMarkers.
Referenced by CEdl(), CVideoPlayer::CloseFile(), CVideoPlayer::OpenVideoStream(), ReadBeyondTV(), ReadComskip(), ReadEdl(), ReadVideoReDo(), and TEST_F().
GetCutMarkers()
const std::vector< std::chrono::milliseconds > CEdl::GetCutMarkers () const
Get the list of EDL cut markers.
Returns
The list of EDL cut markers or an empty vector if no EDL cuts exist. The returned values are accurate with respect to cut durations. I.e. if the file has multiple cuts, the positions of subsquent cuts are automatically corrected by substracting the previous cut durations.
References m_vecEdits.
Referenced by CVideoPlayer::OpenVideoStream(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetEditList()
const std::vector< EDL::Edit > CEdl::GetEditList () const
Get the EDL edit list.
Returns
The EDL edits or an empty vector if no edits exist. Edits are provided with respect to the actual timeline, i.e. considering EDL cuts are not part of the media item.
References m_vecEdits.
Referenced by CVideoPlayer::OpenVideoStream(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetLastEditActionType()
EDL::Action CEdl::GetLastEditActionType () const
Get the last processed edit action type (set during playback when a given edit is surpassed)
Returns
The last processed edit action type or -1 if not any
References m_lastEditActionType.
Referenced by CVideoPlayer::CheckAutoSceneSkip(), and TEST_F().
GetLastEditTime()
std::optional< std::chrono::milliseconds > CEdl::GetLastEditTime () const
Get the last processed edit time (set during playback when a given edit is surpassed)
Returns
The last processed edit time or nullopt if not any
References m_lastEditTime.
Referenced by CVideoPlayer::CheckAutoSceneSkip(), and TEST_F().
GetNextSceneMarker()
std::optional< std::chrono::milliseconds > CEdl::GetNextSceneMarker (Direction direction, std::chrono::milliseconds clockTime)
Get the next scene marker with respect to the provided clock time.
Parameters
direction (the direction of the search - backward or forward)
clock the current position of the clock
Returns
the position of the scenemarker (nullopt if none)
References BACKWARD, FORWARD, GetTimeAfterRestoringCuts(), HasSceneMarker(), InEdit(), and m_vecSceneMarkers.
Referenced by CVideoPlayer::SeekScene(), and TEST_F().
GetRawEditList()
const std::vector< EDL::Edit > & CEdl::GetRawEditList () const inline
Get the raw EDL edit list.
Returns
The EDL edits or an empty vector if no edits exist. Edits are provided with respect to the original media item timeline.
References m_vecEdits.
Referenced by TEST_F(), TEST_F(), and TEST_F().
GetSceneMarkers()
const std::vector< std::chrono::milliseconds > CEdl::GetSceneMarkers () const
Get the list of EDL scene markers.
Returns
The list of EDL scene markers or an empty vector if no EDL scene exist. The returned values are accurate with respect to cut durations. I.e. if the file has multiple cuts, the positions of scene markers are automatically corrected by substracting the surpassed cut durations until the scene marker point.
References GetTimeWithoutCuts(), and m_vecSceneMarkers.
Referenced by CVideoPlayer::OpenVideoStream(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetTimeAfterRestoringCuts()
std::chrono::milliseconds CEdl::GetTimeAfterRestoringCuts (std::chrono::milliseconds seekTime) const
Provided a given seek time, return the time after correction with the addition of the already surpassed EDL cut ranges.
Note
VideoPlayer uses it to restore the correct time after seek since cut blocks are not part of the playable file
Parameters
seek the desired seek time
Returns
the seek time after applying the cut blocks already surpassed by the provided seek time
References HasCuts(), and m_vecEdits.
Referenced by CVideoPlayer::CheckAutoSceneSkip(), GetNextSceneMarker(), CVideoPlayer::HandleMessages(), CVideoPlayer::Prepare(), and TEST_F().
GetTimeWithoutCuts()
std::chrono::milliseconds CEdl::GetTimeWithoutCuts (std::chrono::milliseconds seekTime) const
Providing a given seek time, return the actual time without considering cut ranges removed from the file.
Note
VideoPlayer always displays/returns the playback time considering cut blocks are not part of the playable file
Parameters
seek the desired seek time
Returns
the seek time without considering EDL cut blocks
References HasCuts(), and m_vecEdits.
Referenced by GetSceneMarkers(), TEST_F(), TEST_F(), and CVideoPlayer::UpdatePlayState().
GetTotalCutTime()
std::chrono::milliseconds CEdl::GetTotalCutTime () const
Get the total cut time removed from the original item because of EDL cuts.
Returns
the total cut time
References m_totalCutTime.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and CVideoPlayer::UpdatePlayState().
HasCuts()
bool CEdl::HasCuts () const
Check if the edit list has EDL cuts (edits with action CUT)
Returns
true if EDL has cuts, false otherwise
References m_totalCutTime.
Referenced by GetTimeAfterRestoringCuts(), GetTimeWithoutCuts(), CVideoPlayer::SeekTimeRelative(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and CVideoPlayer::UpdatePlayState().
HasEdits()
bool CEdl::HasEdits () const
Check if there are any parsed edits in EDL for the current item.
Returns
true if EDL has edits, false otherwise
References m_vecEdits.
Referenced by CVideoPlayer::CheckAutoSceneSkip(), CVideoPlayer::CheckSceneSkip(), ReadBeyondTV(), ReadComskip(), ReadEdl(), ReadVideoReDo(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
HasSceneMarker()
bool CEdl::HasSceneMarker () const
References m_vecSceneMarkers.
Referenced by GetNextSceneMarker(), ReadEdl(), ReadVideoReDo(), CVideoPlayer::SeekScene(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
InEdit()
std::optional< std::unique_ptr< EDL::Edit > > CEdl::InEdit (std::chrono::milliseconds seekTime)
Check if for the provided seek time is contained within an EDL edit.
Note
seek time refers to the time in the original file timeline (i.e. without considering cut blocks)
Parameters
seekTime The seek time (on the original timeline)
Returns
a pointer to the edit struct if seekTime is within an edit, nullopt otherwise
References end(), and m_vecEdits.
Referenced by AddEdit(), AddSceneMarker(), CVideoPlayer::CheckAutoSceneSkip(), CVideoPlayer::CheckSceneSkip(), GetNextSceneMarker(), CVideoPlayer::Prepare(), CVideoPlayer::ProcessAudioData(), and TEST_F().
MergeShortCommBreaks()
void CEdl::MergeShortCommBreaks () private
References EDL::Edit::action, EDL::Edit::end, end(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, m_vecEdits, and EDL::Edit::start.
Referenced by ReadEditDecisionLists().
ReadBeyondTV()
bool CEdl::ReadBeyondTV (const std::string & mediaFilePath) private
References EDL::Edit::action, AddEdit(), Clear(), EDL::Edit::end, end(), XFILE::CFile::Exists(), URIUtils::GetExtension(), HasEdits(), CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGDEBUG, LOGERROR, m_vecEdits, URIUtils::ReplaceExtension(), root, and EDL::Edit::start.
Referenced by ReadEditDecisionLists().
ReadComskip()
bool CEdl::ReadComskip (const std::string & mediaFilePath, float fps) private
References EDL::Edit::action, AddEdit(), Clear(), XFILE::CFile::Close(), COMSKIP_HEADER, EDL::Edit::end, XFILE::CFile::Exists(), HasEdits(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_vecEdits, XFILE::CFile::Open(), XFILE::CFile::ReadString(), URIUtils::ReplaceExtension(), EDL::Edit::start, and void().
Referenced by ReadEditDecisionLists().
ReadEditDecisionLists()
bool CEdl::ReadEditDecisionLists (const CFileItem & fileItem, float fps)
References AddSceneMarkersAtStartAndEndOfEdits(), ANY_PRIVATE_SUBNET, CFileItem::GetDynPath(), URIUtils::IsHD(), URIUtils::IsInternetStream(), URIUtils::IsOnLAN(), CLog::Log(), LOGDEBUG, MergeShortCommBreaks(), ReadBeyondTV(), ReadComskip(), ReadEdl(), ReadPvr(), and ReadVideoReDo().
Referenced by CVideoPlayer::OpenVideoStream(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
ReadEdl()
bool CEdl::ReadEdl (const std::string & mediaFilePath, float fps) private
References EDL::Edit::action, AddEdit(), AddSceneMarker(), Clear(), XFILE::CFile::Close(), data(), EDL::Edit::end, XFILE::CFile::Exists(), HasEdits(), HasSceneMarker(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_vecEdits, m_vecSceneMarkers, XFILE::CFile::Open(), XFILE::CFile::ReadString(), URIUtils::ReplaceExtension(), and EDL::Edit::start.
Referenced by ReadEditDecisionLists().
ReadPvr()
bool CEdl::ReadPvr (const CFileItem & fileItem) private
References AddEdit(), AddSceneMarker(), CFileItem::GetDynPath(), PVR::CPVREdl::GetEdits(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, and LOGWARNING.
Referenced by ReadEditDecisionLists().
ReadVideoReDo()
bool CEdl::ReadVideoReDo (const std::string & mediaFilePath) private
References EDL::Edit::action, AddEdit(), AddSceneMarker(), Clear(), XFILE::CFile::Close(), EDL::Edit::end, XFILE::CFile::Exists(), HasEdits(), HasSceneMarker(), CLog::Log(), LOGDEBUG, LOGERROR, m_vecEdits, m_vecSceneMarkers, XFILE::CFile::Open(), XFILE::CFile::ReadString(), URIUtils::ReplaceExtension(), EDL::Edit::start, VIDEOREDO_HEADER, VIDEOREDO_TAG_CUT, and VIDEOREDO_TAG_SCENE.
Referenced by ReadEditDecisionLists().
ResetLastEditTime()
void CEdl::ResetLastEditTime ()
Reset the last recorded edit time (nullopt)
References m_lastEditTime.
Referenced by CVideoPlayer::CheckAutoSceneSkip().
SetLastEditActionType()
void CEdl::SetLastEditActionType (EDL::Action action)
Set the last processed edit action type.
Parameters
action The action type (e.g. COMM_BREAK)
References m_lastEditActionType.
Referenced by CVideoPlayer::CheckAutoSceneSkip(), CVideoPlayer::Prepare(), and TEST_F().
SetLastEditTime()
void CEdl::SetLastEditTime (std::chrono::milliseconds editTime)
Set the last processed edit time (set during playback when a given edit is surpassed)
Parameters
editTime The last processed EDL edit time
References m_lastEditTime.
Referenced by CVideoPlayer::CheckAutoSceneSkip(), CVideoPlayer::Prepare(), and TEST_F().
Member Data Documentation
m_lastEditActionType
EDL::Action CEdl::m_lastEditActionType {EDL::EDL_ACTION_NONE} private
Last processed EDL edit action type.
Referenced by GetLastEditActionType(), and SetLastEditActionType().
m_lastEditTime
std::optional<std::chrono::milliseconds> CEdl::m_lastEditTime private
Last processed EDL edit time (ms)
Referenced by Clear(), GetLastEditTime(), ResetLastEditTime(), and SetLastEditTime().
m_totalCutTime
std::chrono::milliseconds CEdl::m_totalCutTime private
Referenced by AddEdit(), Clear(), GetTotalCutTime(), and HasCuts().
m_vecEdits
std::vector<EDL::Edit> CEdl::m_vecEdits private
Referenced by AddEdit(), AddSceneMarkersAtStartAndEndOfEdits(), Clear(), GetCutMarkers(), GetEditList(), GetRawEditList(), GetTimeAfterRestoringCuts(), GetTimeWithoutCuts(), HasEdits(), InEdit(), MergeShortCommBreaks(), ReadBeyondTV(), ReadComskip(), ReadEdl(), and ReadVideoReDo().
m_vecSceneMarkers
std::vector<std::chrono::milliseconds> CEdl::m_vecSceneMarkers private
Referenced by AddSceneMarker(), Clear(), GetNextSceneMarker(), GetSceneMarkers(), HasSceneMarker(), ReadEdl(), and ReadVideoReDo().
The documentation for this class was generated from the following files:
cores/VideoPlayer/Edl.h
Edl.cpp