Kodi Documentation: MUSIC_INFO::CMusicInfoScanner Class Reference
MUSIC_INFO::CMusicInfoScanner Class Reference
#include <MusicInfoScanner.h>
Public Types
enum SCAN_FLAGS {
SCAN_NORMAL = 0 , SCAN_ONLINE = 1 << 0 , SCAN_BACKGROUND = 1 << 1 , SCAN_RESCAN = 1 << 2 ,
SCAN_ARTISTS = 1 << 3 , SCAN_ALBUMS = 1 << 4
}
Flags for controlling the scanning process.
Public Types inherited from CInfoScanner
enum INFO_RET {
INFO_CANCELLED , INFO_ERROR , INFO_NOT_NEEDED , INFO_HAVE_ALREADY ,
INFO_NOT_FOUND , INFO_ADDED
}
Return values from the information lookup functions.
enum INFO_TYPE {
NO_NFO = 0 , FULL_NFO = 1 , URL_NFO = 2 , OVERRIDE_NFO = 3 ,
COMBINED_NFO = 4 , ERROR_NFO = 5 , TITLE_NFO = 6
}
Public Member Functions
CMusicInfoScanner ()
~CMusicInfoScanner () override
void Start (const std::string &strDirectory, int flags)
void FetchAlbumInfo (const std::string &strDirectory, bool refresh=false)
void FetchArtistInfo (const std::string &strDirectory, bool refresh=false)
void Stop ()
INFO_RET UpdateAlbumInfo (CAlbum &album, const ADDON::ScraperPtr &scraper, bool bAllowSelection, CGUIDialogProgress *pDialog=NULL)
Scrape additional album information and update the music database with it. Given an album, search for it using the given scraper. If info is found, update the database and artwork with the new information.
INFO_RET UpdateArtistInfo (CArtist &artist, const ADDON::ScraperPtr &scraper, bool bAllowSelection, CGUIDialogProgress *pDialog=NULL)
Scrape additional artist information and update the music database with it. Given an artist, search for it using the given scraper. If info is found, update the database and artwork with the new information.
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Public Member Functions inherited from CInfoScanner
virtual ~CInfoScanner ()=default
Empty destructor.
bool HasNoMedia (const std::string &strDirectory) const
Check if the folder is excluded from scanning process.
void ShowDialog (bool show)
Set whether or not to show a progress dialog.
bool IsScanning () const
Returns whether or not a scan is in progress.
Static Public Member Functions
static void FileItemsToAlbums (CFileItemList &items, VECALBUMS &albums, MAPSONGS *songsMap=NULL)
Categorize FileItems into Albums, Songs, and Artists This takes a list of FileItems and turns it into a tree of Albums, Artists, and Songs. Albums are defined uniquely by the album name and album artist.
Protected Member Functions
virtual void Process ()
bool DoScan (const std::string &strDirectory) override
INFO_RET UpdateDatabaseAlbumInfo (CAlbum &album, const ADDON::ScraperPtr &scraper, bool bAllowSelection, CGUIDialogProgress *pDialog=NULL)
Scrape additional album information and update the database. Search for the given album using the given scraper. If info is found, update the database and artwork with the new information.
INFO_RET UpdateDatabaseArtistInfo (CArtist &artist, const ADDON::ScraperPtr &scraper, bool bAllowSelection, CGUIDialogProgress *pDialog=NULL)
Scrape additional artist information and update the database. Search for the given artist using the given scraper. If info is found, update the database and artwork with the new information.
INFO_RET DownloadAlbumInfo (const CAlbum &album, const ADDON::ScraperPtr &scraper, MUSIC_GRABBER::CMusicAlbumInfo &albumInfo, bool bUseScrapedMBID, CGUIDialogProgress *pDialog=NULL)
Using the scrapers download metadata for an album Given a CAlbum style struct containing some data about an album, query the scrapers to try and get more information about the album. The responsibility is with the caller to do something with that information. It will be passed back in a MusicInfo struct, which you can save, display to the user or throw away.
INFO_RET DownloadArtistInfo (const CArtist &artist, const ADDON::ScraperPtr &scraper, MUSIC_GRABBER::CMusicArtistInfo &artistInfo, bool bUseScrapedMBID, CGUIDialogProgress *pDialog=NULL)
Using the scrapers download metadata for an artist Given a CAlbum style struct containing some data about an artist, query the scrapers to try and get more information about the artist. The responsibility is with the caller to do something with that information. It will be passed back in a MusicInfo struct, which you can save, display to the user or throw away.
std::vector< CVariant > GetArtWhitelist (const MediaType &mediaType, int iArtLevel)
Get the types of art for an artist or album that are to be automatically fetched from local files during scanning.
bool AddLocalArtwork (std::map< std::string, std::string > &art, const std::string &mediaType, const std::string &mediaName, const std::string &artfolder, int discnum=0)
Add extra local artwork for albums and artists This common utility scans the given folder for local (non-thumb) art. The art types checked are determined by whitelist and usealllocalart settings.
bool AddRemoteArtwork (std::map< std::string, std::string > &art, const std::string &mediaType, const CScraperUrl &thumbURL)
Add extra remote artwork for albums and artists This common utility fills the gaps in artwork using the first available art of each type from the possible art URL results of previous scraping. The art types applied are determined by whitelist and usealllocalart settings.
bool AddArtistArtwork (CArtist &artist, const std::string &artfolder)
Add art for an artist This scans the given folder for local art and/or applies the first available art of each type from the possible art URLs previously scraped. Art is added to any already stored by previous scanning etc.The art types processed are determined by whitelist and other art settings. When usealllocalart is enabled then all local image files are applied as art (providing name is valid for an art type), and then the URL list of remote art is checked adding the first available image of each art type not yet in the art map. Art found is saved in the album structure and the music database. The images found are cached.
bool AddAlbumArtwork (CAlbum &album)
Add art for an album This scans the album folder, and any disc set subfolders, for local art and/or applies the first available art of each type from the possible art URLs previously scraped. Only those subfolders beneath the album folder containing music files tagged with same unique disc number are scanned. Art is added to any already stored by previous scanning, only "thumb" is optionally replaced. The art types processed are determined by whitelist and other art settings. When usealllocalart is enabled then all local image files are applied as art (providing name is valid for an art type), and then the URL list of remote art is checked adding the first available image of each art type not yet in the art map. Art found is saved in the album structure and the music database. The images found are cached.
int RetrieveMusicInfo (const std::string &strDirectory, CFileItemList &items)
Scan in the ID3/Ogg/FLAC tags for a bunch of FileItems Given a list of FileItems, scan in the tags for those FileItems and populate a new FileItemList with the files that were successfully scanned. Add album to library, populate a list of album ids added for possible scraping later. Any files which couldn't be scanned (no/bad tags) are discarded in the process.
void RetrieveLocalArt ()
void ScrapeInfoAddedAlbums ()
INFO_RET ScanTags (const CFileItemList &items, CFileItemList &scannedItems)
Scan in the ID3/Ogg/FLAC tags for a bunch of FileItems Given a list of FileItems, scan in the tags for those FileItems and populate a new FileItemList with the files that were successfully scanned. Any files which couldn't be scanned (no/bad tags) are discarded in the process.
int GetPathHash (const CFileItemList &items, std::string &hash)
void Run () override
int CountFiles (const CFileItemList &items, bool recursive)
int CountFilesRecursively (const std::string &strPath)
bool ResolveMusicBrainz (const std::string &strMusicBrainzID, const ADDON::ScraperPtr &preferredScraper, CScraperUrl &musicBrainzURL)
Resolve a MusicBrainzID to a URL If we have a MusicBrainz ID for an artist or album, resolve it to an MB URL and set up the scrapers accordingly.
void ScannerWait (unsigned int milliseconds)
Protected Member Functions inherited from CInfoScanner
CInfoScanner ()=default
Protected constructor to only allow subclass instances.
Static Protected Member Functions
static void FindArtForAlbums (VECALBUMS &albums, const std::string &path)
Find art for albums Based on the albums in the folder, finds whether we have unique album art and assigns to the album if we do.
Protected Attributes
int m_currentItem
int m_itemCount
bool m_bStop
bool m_needsCleanup = false
int m_scanType = 0
int m_idSourcePath
CMusicDatabase m_musicDatabase
std::set< int > m_albumsAdded
std::set< std::string > m_seenPaths
int m_flags
CThread m_fileCountReader
Protected Attributes inherited from CInfoScanner
std::set< std::string > m_pathsToScan
Set of paths to scan.
bool m_showDialog = false
Whether or not to show progress bar dialog.
CGUIDialogProgressBarHandle * m_handle = nullptr
Progress bar handle.
bool m_bRunning = false
Whether or not scanner is running.
bool m_bCanInterrupt = false
Whether or not scanner is currently interruptible.
bool m_bClean = false
Whether or not to perform cleaning during scanning.
Member Enumeration Documentation
SCAN_FLAGS
enum MUSIC_INFO::CMusicInfoScanner::SCAN_FLAGS
Flags for controlling the scanning process.
Enumerator
SCAN_NORMAL
SCAN_ONLINE
SCAN_BACKGROUND
SCAN_RESCAN
SCAN_ARTISTS
SCAN_ALBUMS
Constructor & Destructor Documentation
CMusicInfoScanner()
CMusicInfoScanner::CMusicInfoScanner ()
References m_bStop, m_currentItem, m_flags, and m_itemCount.
~CMusicInfoScanner()
CMusicInfoScanner::~CMusicInfoScanner () override default
Member Function Documentation
AddAlbumArtwork()
bool CMusicInfoScanner::AddAlbumArtwork (CAlbum & album) protected
Add art for an album This scans the album folder, and any disc set subfolders, for local art and/or applies the first available art of each type from the possible art URLs previously scraped. Only those subfolders beneath the album folder containing music files tagged with same unique disc number are scanned. Art is added to any already stored by previous scanning, only "thumb" is optionally replaced. The art types processed are determined by whitelist and other art settings. When usealllocalart is enabled then all local image files are applied as art (providing name is valid for an art type), and then the URL list of remote art is checked adding the first available image of each art type not yet in the art map. Art found is saved in the album structure and the music database. The images found are cached.
Parameters
artist [in/out] an album, the art is set
Returns
true when art is added
References AddLocalArtwork(), AddRemoteArtwork(), CAlbum::art, CMusicDatabase::GetAlbumPaths(), CMusicDatabase::GetArtForItem(), CThumbLoader::GetCachedImage(), URIUtils::GetCommonPath(), CMusicDatabase::GetDiscnumberForPathID(), CScraperUrl::GetFirstUrlByType(), CServiceBroker::GetSettingsComponent(), IMAGE_FILES::CImageFileURL::GetSpecialType(), CServiceBroker::GetTextureCache(), CScraperUrl::GetThumbUrl(), CFileItem::GetUserMusicThumb(), CScraperUrl::HasUrls(), CAlbum::idAlbum, m_musicDatabase, MediaTypeAlbum, CSettings::MUSICLIBRARY_ARTWORK_LEVEL_ALL, CMusicDatabase::SetArtForItem(), CThumbLoader::SetCachedImage(), CSettings::SETTING_MUSICLIBRARY_ARTWORKLEVEL, CSettings::SETTING_MUSICLIBRARY_PREFERONLINEALBUMART, CAlbum::strAlbum, CAlbum::strPath, and CAlbum::thumbURL.
Referenced by UpdateDatabaseAlbumInfo().
AddArtistArtwork()
bool CMusicInfoScanner::AddArtistArtwork (CArtist & artist, const std::string & artfolder) protected
Add art for an artist This scans the given folder for local art and/or applies the first available art of each type from the possible art URLs previously scraped. Art is added to any already stored by previous scanning etc.The art types processed are determined by whitelist and other art settings. When usealllocalart is enabled then all local image files are applied as art (providing name is valid for an art type), and then the URL list of remote art is checked adding the first available image of each art type not yet in the art map. Art found is saved in the album structure and the music database. The images found are cached.
Parameters
artist [in/out] an artist, the art is set
artfolder [in] path of the location to search for local art files
Returns
true when art is added
References AddLocalArtwork(), AddRemoteArtwork(), CArtist::art, CMusicDatabase::GetArtForItem(), CScraperUrl::GetFirstUrlByType(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetTextureCache(), CScraperUrl::GetThumbUrl(), CFileItem::GetUserMusicThumb(), CScraperUrl::HasUrls(), CArtist::idArtist, m_musicDatabase, MediaTypeArtist, CSettings::MUSICLIBRARY_ARTWORK_LEVEL_ALL, CMusicDatabase::SetArtForItem(), CSettings::SETTING_MUSICLIBRARY_ARTWORKLEVEL, CArtist::strArtist, and CArtist::thumbURL.
Referenced by UpdateDatabaseArtistInfo().
AddLocalArtwork()
bool CMusicInfoScanner::AddLocalArtwork (std::map< std::string, std::string > & art, const std::string & mediaType, const std::string & mediaName, const std::string & artfolder, int discnum = 0) protected
Add extra local artwork for albums and artists This common utility scans the given folder for local (non-thumb) art. The art types checked are determined by whitelist and usealllocalart settings.
Parameters
art [in/out] map of art type and file location (URL or path) pairs
mediaType [in] artist or album
mediaName [in] artist or album name that may be stripped from image file names
artfolder [in] path of folder containing local image files
Returns
true when art is added
References XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, XFILE::DIR_FLAG_READ_CACHE, GetArtWhitelist(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), URIUtils::GetFileName(), CServiceBroker::GetSettingsComponent(), MUSIC_UTILS::IsValidArtType(), CSettings::MUSICLIBRARY_ARTWORK_LEVEL_ALL, CSettings::MUSICLIBRARY_ARTWORK_LEVEL_CUSTOM, CSettings::SETTING_MUSICLIBRARY_ARTWORKLEVEL, CSettings::SETTING_MUSICLIBRARY_MUSICTHUMBS, and CSettings::SETTING_MUSICLIBRARY_USEALLLOCALART.
Referenced by AddAlbumArtwork(), and AddArtistArtwork().
AddRemoteArtwork()
bool CMusicInfoScanner::AddRemoteArtwork (std::map< std::string, std::string > & art, const std::string & mediaType, const CScraperUrl & thumbURL) protected
Add extra remote artwork for albums and artists This common utility fills the gaps in artwork using the first available art of each type from the possible art URL results of previous scraping. The art types applied are determined by whitelist and usealllocalart settings.
Parameters
art [in/out] map of art type and file location (URL or path) pairs
mediaType [in] artist or album
thumbURL [in] URLs for potential remote artwork (provided by scrapers)
Returns
true when art is added
References GetArtWhitelist(), CServiceBroker::GetSettingsComponent(), CScraperUrl::GetThumbUrl(), CScraperUrl::GetUrls(), CSettings::MUSICLIBRARY_ARTWORK_LEVEL_ALL, CSettings::MUSICLIBRARY_ARTWORK_LEVEL_BASIC, CSettings::MUSICLIBRARY_ARTWORK_LEVEL_CUSTOM, CSettings::SETTING_MUSICLIBRARY_ARTWORKLEVEL, and CSettings::SETTING_MUSICLIBRARY_USEALLREMOTEART.
Referenced by AddAlbumArtwork(), and AddArtistArtwork().
CountFiles()
int CMusicInfoScanner::CountFiles (const CFileItemList & items, bool recursive) protected
References CountFilesRecursively(), KODI::MUSIC::IsAudio(), KODI::PLAYLIST::IsPlayList(), and CFileItemList::Size().
Referenced by CountFilesRecursively(), and DoScan().
CountFilesRecursively()
int CMusicInfoScanner::CountFilesRecursively (const std::string & strPath) protected
References CountFiles(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), and m_bStop.
Referenced by CountFiles(), and Run().
DoScan()
bool CMusicInfoScanner::DoScan (const std::string & strDirectory) override protected virtual
Implements CInfoScanner.
References CountFiles(), XFILE::DIR_FLAG_DEFAULTS, DoScan(), CUtil::ExcludeFileOrFolder(), CFileItemList::FilterCueItems(), g_localizeStrings, CLocalizeStrings::Get(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), CFileItem::GetPath(), GetPathHash(), CMusicDatabase::GetPathHash(), CServiceBroker::GetSettingsComponent(), CInfoScanner::HasNoMedia(), KODI::PLAYLIST::IsPlayList(), CLog::Log(), LOGDEBUG, m_bStop, m_currentItem, m_flags, CInfoScanner::m_handle, m_itemCount, m_musicDatabase, m_seenPaths, OnDirectoryScanned(), Prettify(), RetrieveMusicInfo(), SCAN_RESCAN, CMusicDatabase::SetPathHash(), CGUIDialogProgressBarHandle::SetPercentage(), CGUIDialogProgressBarHandle::SetText(), CGUIDialogProgressBarHandle::SetTitle(), CFileItemList::Size(), CFileItemList::Sort(), SortByLabel, and SortOrderAscending.
Referenced by DoScan(), and Process().
DownloadAlbumInfo()
CInfoScanner::INFO_RET CMusicInfoScanner::DownloadAlbumInfo (const CAlbum & album, const ADDON::ScraperPtr & scraper, MUSIC_GRABBER::CMusicAlbumInfo & albumInfo, bool bUseScrapedMBID, CGUIDialogProgress * pDialog = NULL) protected
Using the scrapers download metadata for an album Given a CAlbum style struct containing some data about an album, query the scrapers to try and get more information about the album. The responsibility is with the caller to do something with that information. It will be passed back in a MusicInfo struct, which you can save, display to the user or throw away.
Parameters
album [in] a partially or fully filled out album structure containing the search query
scraper [in] the scraper to query, usually the default or the relevant scraper for the musicdb path
albumInfo [in/out] a CMusicAlbumInfo struct which will be populated with the output of the scraper
bUseScrapedMBID [in] should scraper use any previously scraped mbid to identify the artist, or use artist name?
pDialog [in] a progress dialog which this and downstream functions can update with status, if required
References CFileItemList::Add(), URIUtils::AddFileToFolder(), CUtil::AlbumRelevance(), CAlbum::art, CAlbum::bScrapedMBID, MUSIC_GRABBER::CMusicInfoScraper::Cancel(), MUSIC_GRABBER::CMusicInfoScraper::CheckValidOrFallback(), CInfoScanner::COMBINED_NFO, MUSIC_GRABBER::CMusicInfoScraper::Completed(), CNfoFile::Create(), DownloadAlbumInfo(), CGUIDialogSelect::EnableButton(), CFileUtils::Exists(), MUSIC_GRABBER::CMusicInfoScraper::FindAlbumInfo(), CInfoScanner::FULL_NFO, g_localizeStrings, CLocalizeStrings::Get(), MUSIC_GRABBER::CMusicAlbumInfo::GetAlbum(), MUSIC_GRABBER::CMusicInfoScraper::GetAlbum(), CAlbum::GetAlbumArtistString(), MUSIC_GRABBER::CMusicInfoScraper::GetAlbumCount(), CMusicDatabase::GetAlbumPath(), MUSIC_GRABBER::CMusicInfoScraper::GetAlbums(), CNfoFile::GetDetails(), CScraperUrl::GetFirstThumbUrl(), CServiceBroker::GetGUI(), CNfoFile::GetScraperInfo(), CGUIDialogSelect::GetSelectedItem(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CAlbum::idAlbum, CInfoScanner::INFO_ADDED, CInfoScanner::INFO_CANCELLED, CInfoScanner::INFO_ERROR, CInfoScanner::INFO_NOT_FOUND, CGUIDialogSelect::IsButtonPressed(), MUSIC_GRABBER::CMusicInfoScraper::LoadAlbumInfo(), CLog::Log(), LOGDEBUG, LOGERROR, m_bStop, CInfoScanner::m_handle, m_musicDatabase, CInfoScanner::NO_NFO, CGUIDialog::Open(), CInfoScanner::OVERRIDE_NFO, CGUIDialogProgress::Progress(), CGUIDialogSelect::Reset(), ResolveMusicBrainz(), ScannerWait(), CNfoFile::ScraperUrl(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CGUIDialogBoxBase::SetLine(), MUSIC_GRABBER::CMusicInfoScraper::SetScraperInfo(), CGUIDialogProgressBarHandle::SetText(), CSettings::SETTING_MUSICLIBRARY_ALBUMSSCRAPER, CGUIDialogProgressBarHandle::SetTitle(), CGUIDialogSelect::SetUseDetails(), CGUIDialogYesNo::ShowAndGetInput(), CGUIKeyboardFactory::ShowAndGetInput(), CGUIDialogSelect::Sort(), CAlbum::strAlbum, CAlbum::strArtistDesc, CAlbum::strLabel, CAlbum::strMusicBrainzAlbumID, CAlbum::strPath, CAlbum::strReleaseDate, CAlbum::strReleaseStatus, CAlbum::strType, MUSIC_GRABBER::CMusicInfoScraper::Succeeded(), THRESHOLD, CInfoScanner::URL_NFO, and WINDOW_DIALOG_SELECT.
Referenced by DownloadAlbumInfo(), and UpdateDatabaseAlbumInfo().
DownloadArtistInfo()
CInfoScanner::INFO_RET CMusicInfoScanner::DownloadArtistInfo (const CArtist & artist, const ADDON::ScraperPtr & scraper, MUSIC_GRABBER::CMusicArtistInfo & artistInfo, bool bUseScrapedMBID, CGUIDialogProgress * pDialog = NULL) protected
Using the scrapers download metadata for an artist Given a CAlbum style struct containing some data about an artist, query the scrapers to try and get more information about the artist. The responsibility is with the caller to do something with that information. It will be passed back in a MusicInfo struct, which you can save, display to the user or throw away.
Parameters
artist [in] a partially or fully filled out artist structure containing the search query
scraper [in] the scraper to query, usually the default or the relevant scraper for the musicdb path
artistInfo [in/out] a CMusicAlbumInfo struct which will be populated with the output of the scraper
bUseScrapedMBID [in] should scraper use any previously scraped mbid to identify the album, or use album and artist name?
pDialog [in] a progress dialog which this and downstream functions can update with status, if required
References CGUIDialogSelect::Add(), URIUtils::AddFileToFolder(), CArtist::bScrapedMBID, MUSIC_GRABBER::CMusicInfoScraper::Cancel(), CInfoScanner::COMBINED_NFO, MUSIC_GRABBER::CMusicInfoScraper::Completed(), CNfoFile::Create(), DownloadArtistInfo(), CGUIDialogSelect::EnableButton(), CFileUtils::Exists(), MUSIC_GRABBER::CMusicInfoScraper::FindArtistInfo(), CInfoScanner::FULL_NFO, g_localizeStrings, CArtist::genre, CLocalizeStrings::Get(), MUSIC_GRABBER::CMusicArtistInfo::GetArtist(), MUSIC_GRABBER::CMusicInfoScraper::GetArtist(), MUSIC_GRABBER::CMusicInfoScraper::GetArtistCount(), CMusicDatabase::GetArtistPath(), MUSIC_GRABBER::CMusicInfoScraper::GetArtists(), CNfoFile::GetDetails(), CScraperUrl::GetFirstThumbUrl(), CServiceBroker::GetGUI(), CMusicDatabase::GetOldArtistPath(), CNfoFile::GetScraperInfo(), CGUIDialogSelect::GetSelectedFileItem(), CGUIDialogSelect::GetSelectedItem(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CArtist::idArtist, CInfoScanner::INFO_ADDED, CInfoScanner::INFO_CANCELLED, CInfoScanner::INFO_ERROR, CInfoScanner::INFO_NOT_FOUND, CGUIDialogSelect::IsButtonPressed(), MUSIC_GRABBER::CMusicInfoScraper::LoadArtistInfo(), CLog::Log(), LOGDEBUG, LOGERROR, m_bStop, CInfoScanner::m_handle, CFileItem::m_idepth, m_musicDatabase, CInfoScanner::NO_NFO, CGUIDialog::Open(), CGUIDialogProgress::Progress(), CGUIDialogSelect::Reset(), ResolveMusicBrainz(), ScannerWait(), CNfoFile::ScraperUrl(), CGUIDialogBoxBase::SetHeading(), CFileItem::SetLabel(), CGUIDialogBoxBase::SetLine(), MUSIC_GRABBER::CMusicInfoScraper::SetScraperInfo(), CGUIDialogProgressBarHandle::SetText(), CGUIDialogProgressBarHandle::SetTitle(), CGUIDialogYesNo::ShowAndGetInput(), CGUIKeyboardFactory::ShowAndGetInput(), CArtist::strArtist, CArtist::strBorn, CArtist::strDisambiguation, CArtist::strMusicBrainzArtistID, CArtist::strPath, MUSIC_GRABBER::CMusicInfoScraper::Succeeded(), CInfoScanner::URL_NFO, and WINDOW_DIALOG_SELECT.
Referenced by DownloadArtistInfo(), and UpdateDatabaseArtistInfo().
FetchAlbumInfo()
void CMusicInfoScanner::FetchAlbumInfo (const std::string & strDirectory, bool refresh = false)
References CFileItemList::Add(), CMusicDatabase::ClearAlbumLastScrapedTime(), CDatabase::Close(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetAlbumId(), CMusicDatabase::GetAlbumsNav(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectoryChildType(), XFILE::CMusicDatabaseDirectory::IsAllItem(), CURL::IsProtocol(), CInfoScanner::m_bRunning, m_fileCountReader, m_musicDatabase, CInfoScanner::m_pathsToScan, m_scanType, MediaTypeAlbum, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM, CMusicDatabase::Open(), Process(), CFileItemList::Size(), and CThread::StopThread().
Referenced by CMusicLibraryScanningJob::Work().
FetchArtistInfo()
void CMusicInfoScanner::FetchArtistInfo (const std::string & strDirectory, bool refresh = false)
References CFileItemList::Add(), CMusicDatabase::ClearArtistLastScrapedTime(), CDatabase::Close(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetAlbumId(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetArtistId(), CMusicDatabase::GetArtistsNav(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectoryChildType(), CServiceBroker::GetSettingsComponent(), XFILE::CMusicDatabaseDirectory::IsAllItem(), CURL::IsProtocol(), CInfoScanner::m_bRunning, m_fileCountReader, m_musicDatabase, CInfoScanner::m_pathsToScan, m_scanType, MediaTypeArtist, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ARTIST, CMusicDatabase::Open(), Process(), CSettings::SETTING_MUSICLIBRARY_SHOWCOMPILATIONARTISTS, CFileItemList::Size(), and CThread::StopThread().
Referenced by CMusicLibraryScanningJob::Work().
FileItemsToAlbums()
void CMusicInfoScanner::FileItemsToAlbums (CFileItemList & items, VECALBUMS & albums, MAPSONGS * songsMap = NULL) static
Categorize FileItems into Albums, Songs, and Artists This takes a list of FileItems and turns it into a tree of Albums, Artists, and Songs. Albums are defined uniquely by the album name and album artist.
Parameters
songs [in/out] list of songs to categorise - albumartist field may be altered.
albums [out] albums found within these songs.
Todo:
in future we may wish to union up the genres, for now we assume they're the same
References CAlbum::artistCredits, CAlbum::bCompilation, CSong::dateNew, g_localizeStrings, CAlbum::genre, CLocalizeStrings::Get(), CFileItem::GetMusicInfoTag(), CServiceBroker::GetSettingsComponent(), CSong::idSong, CSong::iTimesPlayed, CSong::lastPlayed, CLog::Log(), LOGDEBUG, push_back(), CSong::rating, CFileItemList::Size(), CAlbum::songs, SortSongsByTrack(), CAlbum::strAlbum, CAlbum::strArtistSort, CAlbum::strLabel, CAlbum::strReleaseDate, CSong::strThumb, CAlbum::strType, CSong::userrating, and VARIOUSARTISTS_MBID.
Referenced by RetrieveMusicInfo().
FindArtForAlbums()
void CMusicInfoScanner::FindArtForAlbums (VECALBUMS & albums, const std::string & path) static protected
Find art for albums Based on the albums in the folder, finds whether we have unique album art and assigns to the album if we do.
In order of priority:
If there is a single album in the folder, then the folder art is assigned to the album.
We find the art for each song. A .tbn file takes priority over embedded art.
If we have a unique piece of art for all songs in the album, we assign that to the album and remove that art from each song so that they inherit from the album.
If there is not a unique piece of art for each song, then no art is assigned to the album.
Parameters
albums [in/out] list of albums to categorise - art field may be altered.
path [in] path containing albums.
References CSong::ArtMatches(), CFileItem::GetUserMusicThumb(), CThumbLoader::SetCachedImage(), CGUIListItem::SetProperty(), CSong::strFileName, CSong::strThumb, and IMAGE_FILES::URLFromFile().
Referenced by RetrieveMusicInfo().
GetArtWhitelist()
std::vector< CVariant > CMusicInfoScanner::GetArtWhitelist (const MediaType & mediaType, int iArtLevel) protected
Get the types of art for an artist or album that are to be automatically fetched from local files during scanning.
Parameters
mediaType [in] artist or album
iArtLevel [in] art level
Returns
vector of art types that are to be fetched during scanning
References CServiceBroker::GetSettingsComponent(), MediaTypeArtist, CSettings::MUSICLIBRARY_ARTWORK_LEVEL_BASIC, CSettings::SETTING_MUSICLIBRARY_ALBUMART_WHITELIST, and CSettings::SETTING_MUSICLIBRARY_ARTISTART_WHITELIST.
Referenced by AddLocalArtwork(), and AddRemoteArtwork().
GetPathHash()
int CMusicInfoScanner::GetPathHash (const CFileItemList & items, std::string & hash) protected
References KODI::MUSIC::IsAudio(), KODI::PLAYLIST::IsPlayList(), and CFileItemList::Size().
Referenced by DoScan().
Process()
void CMusicInfoScanner::Process () protected virtual
References ANNOUNCEMENT::AudioLibrary, CMusicDatabase::CheckArtistLinksChanged(), CMusicLibraryQueue::CleanLibrary(), CMusicDatabase::CleanupOrphanedItems(), CDatabase::Close(), CDatabase::Compress(), CONTENT_ALBUMS, CONTENT_ARTISTS, CThread::Create(), CUtil::DeleteMusicDatabaseDirectoryCache(), DoScan(), CMusicDatabase::EmptyCache(), XFILE::CDirectory::Exists(), g_localizeStrings, CLocalizeStrings::Get(), CMusicDatabase::GetAlbum(), CAlbum::GetAlbumArtistString(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetAlbumId(), CServiceBroker::GetAnnouncementManager(), CMusicDatabase::GetArtist(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetArtistId(), CMusicDatabase::GetArtistPath(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), CServiceBroker::GetGUI(), CGUIDialogExtendedProgressBar::GetHandle(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CMusicLibraryQueue::GetInstance(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetLibraryInfoProvider(), CMusicDatabase::GetScraper(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), GUI_MSG_SCAN_FINISHED, CMusicDatabase::HasAlbumBeenScraped(), CMusicDatabase::HasArtistBeenScraped(), CAlbum::idAlbum, CArtist::idArtist, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, m_albumsAdded, CInfoScanner::m_bCanInterrupt, CInfoScanner::m_bClean, CInfoScanner::m_bRunning, m_bStop, m_currentItem, m_fileCountReader, m_flags, CInfoScanner::m_handle, m_itemCount, m_musicDatabase, m_needsCleanup, CInfoScanner::m_pathsToScan, m_scanType, m_seenPaths, CInfoScanner::m_showDialog, CGUIDialogProgressBarHandle::MarkFinished(), CSettings::MUSICLIBRARY_ARTWORK_LEVEL_NONE, CMusicDatabase::Open(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::ResetLibraryBools(), RetrieveLocalArt(), SCAN_ONLINE, ScrapeInfoAddedAlbums(), CGUIDialogProgressBarHandle::SetPercentage(), CGUIDialogProgressBarHandle::SetText(), CSettings::SETTING_MUSICLIBRARY_ARTWORKLEVEL, CSettings::SETTING_MUSICLIBRARY_BACKGROUNDUPDATE, CGUIDialogProgressBarHandle::SetTitle(), CThread::StopThread(), CAlbum::strAlbum, CArtist::strArtist, CArtist::strPath, CMusicDatabase::UpdateArtistSortNames(), UpdateDatabaseAlbumInfo(), UpdateDatabaseArtistInfo(), and WINDOW_DIALOG_EXT_PROGRESS.
Referenced by FetchAlbumInfo(), FetchArtistInfo(), and Start().
ResolveMusicBrainz()
bool CMusicInfoScanner::ResolveMusicBrainz (const std::string & strMusicBrainzID, const ADDON::ScraperPtr & preferredScraper, CScraperUrl & musicBrainzURL) protected
Resolve a MusicBrainzID to a URL If we have a MusicBrainz ID for an artist or album, resolve it to an MB URL and set up the scrapers accordingly.
Parameters
preferredScraper [in] A ScraperPtr to the preferred album/artist scraper.
musicBrainzURL [out] will be populated with the MB URL for the artist/album.
References ADDON::CScraperError::FAborted(), CScraperUrl::GetFirstThumbUrl(), CScraperUrl::HasUrls(), CLog::Log(), and LOGDEBUG.
Referenced by DownloadAlbumInfo(), and DownloadArtistInfo().
RetrieveLocalArt()
void MUSIC_INFO::CMusicInfoScanner::RetrieveLocalArt () protected
Todo:
: title = Checking for local art
References CAlbum::artistCredits, XFILE::CDirectory::Exists(), g_localizeStrings, CLocalizeStrings::Get(), CAlbum::GetAlbumArtistString(), URIUtils::GetParentPath(), CAlbum::strAlbum, CAlbum::strPath, and CArtist::strPath.
Referenced by Process().
RetrieveMusicInfo()
int CMusicInfoScanner::RetrieveMusicInfo (const std::string & strDirectory, CFileItemList & items) protected
Scan in the ID3/Ogg/FLAC tags for a bunch of FileItems Given a list of FileItems, scan in the tags for those FileItems and populate a new FileItemList with the files that were successfully scanned. Add album to library, populate a list of album ids added for possible scraping later. Any files which couldn't be scanned (no/bad tags) are discarded in the process.
Parameters
items [in] list of FileItems to scan
scannedItems [in] list to populate with the scannedItems
References CMusicDatabase::AddAlbum(), FileItemsToAlbums(), FindArtForAlbums(), CFileItem::GetPath(), CInfoScanner::INFO_CANCELLED, m_albumsAdded, m_bStop, m_idSourcePath, m_musicDatabase, m_needsCleanup, CMusicDatabase::RemoveSongsFromPath(), ScanTags(), CAlbum::Single, and CFileItemList::Size().
Referenced by DoScan().
Run()
void CMusicInfoScanner::Run () override protected virtual
Implements IRunnable.
References CountFilesRecursively(), m_itemCount, and CInfoScanner::m_pathsToScan.
ScannerWait()
void CMusicInfoScanner::ScannerWait (unsigned int milliseconds) protected
References CEvent::Wait().
Referenced by DownloadAlbumInfo(), and DownloadArtistInfo().
ScanTags()
CInfoScanner::INFO_RET CMusicInfoScanner::ScanTags (const CFileItemList & items, CFileItemList & scannedItems) protected
Scan in the ID3/Ogg/FLAC tags for a bunch of FileItems Given a list of FileItems, scan in the tags for those FileItems and populate a new FileItemList with the files that were successfully scanned. Any files which couldn't be scanned (no/bad tags) are discarded in the process.
Parameters
items [in] list of FileItems to scan
scannedItems [in] list to populate with the scannedItems
References CFileItemList::Add(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), CUtil::ExcludeFileOrFolder(), CServiceBroker::GetSettingsComponent(), CInfoScanner::INFO_ADDED, CInfoScanner::INFO_CANCELLED, KODI::MUSIC::IsLyrics(), KODI::PLAYLIST::IsPlayList(), CLog::Log(), LOGDEBUG, m_bStop, m_currentItem, CInfoScanner::m_handle, m_itemCount, CGUIDialogProgressBarHandle::SetPercentage(), and CFileItemList::Size().
Referenced by RetrieveMusicInfo().
ScrapeInfoAddedAlbums()
void MUSIC_INFO::CMusicInfoScanner::ScrapeInfoAddedAlbums () protected
References CAlbum::artistCredits, CAlbum::GetAlbumArtistString(), ADDON::CAddonSystemSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), ADDON::SCRAPER_ALBUMS, ADDON::SCRAPER_ARTISTS, CSettings::SETTING_MUSICLIBRARY_SHOWCOMPILATIONARTISTS, CAlbum::songs, and CAlbum::strAlbum.
Referenced by Process().
Start()
void CMusicInfoScanner::Start (const std::string & strDirectory, int flags)
References CDatabase::Close(), CMusicDatabase::GetPaths(), CServiceBroker::GetSettingsComponent(), CMusicDatabase::GetSourceFromPath(), m_albumsAdded, CInfoScanner::m_bClean, CInfoScanner::m_bRunning, m_fileCountReader, m_flags, m_idSourcePath, m_musicDatabase, CInfoScanner::m_pathsToScan, m_scanType, m_seenPaths, CMusicDatabase::Open(), Process(), CThread::StopThread(), and CMusicDatabase::UpdateSources().
Referenced by CMusicLibraryScanningJob::Work().
Stop()
void CMusicInfoScanner::Stop ()
References CDatabase::Interrupt(), CInfoScanner::m_bCanInterrupt, m_bStop, and m_musicDatabase.
Referenced by CMusicLibraryScanningJob::Cancel().
UpdateAlbumInfo()
CInfoScanner::INFO_RET CMusicInfoScanner::UpdateAlbumInfo (CAlbum & album, const ADDON::ScraperPtr & scraper, bool bAllowSelection, CGUIDialogProgress * pDialog = NULL)
Scrape additional album information and update the music database with it. Given an album, search for it using the given scraper. If info is found, update the database and artwork with the new information.
Parameters
album [in/out] the album to update
scraper [in] the album scraper to use
bAllowSelection [in] should we allow the user to manually override the info with a GUI if the album is not found?
pDialog [in] a progress dialog which this and downstream functions can update with status, if required
References CDatabase::Close(), m_musicDatabase, CMusicDatabase::Open(), and UpdateDatabaseAlbumInfo().
Referenced by CRefreshInfoJob::DoWork().
UpdateArtistInfo()
CInfoScanner::INFO_RET CMusicInfoScanner::UpdateArtistInfo (CArtist & artist, const ADDON::ScraperPtr & scraper, bool bAllowSelection, CGUIDialogProgress * pDialog = NULL)
Scrape additional artist information and update the music database with it. Given an artist, search for it using the given scraper. If info is found, update the database and artwork with the new information.
Parameters
artist [in/out] the artist to update
scraper [in] the artist scraper to use
bAllowSelection [in] should we allow the user to manually override the info with a GUI if the album is not found?
pDialog [in] a progress dialog which this and downstream functions can update with status, if required
References CDatabase::Close(), m_musicDatabase, CMusicDatabase::Open(), and UpdateDatabaseArtistInfo().
Referenced by CRefreshInfoJob::DoWork().
UpdateDatabaseAlbumInfo()
CInfoScanner::INFO_RET CMusicInfoScanner::UpdateDatabaseAlbumInfo (CAlbum & album, const ADDON::ScraperPtr & scraper, bool bAllowSelection, CGUIDialogProgress * pDialog = NULL) protected
Scrape additional album information and update the database. Search for the given album using the given scraper. If info is found, update the database and artwork with the new information.
Parameters
album [in/out] the album to update
scraper [in] the album scraper to use
bAllowSelection [in] should we allow the user to manually override the info with a GUI if the album is not found?
pDialog [in] a progress dialog which this and downstream functions can update with status, if required
References AddAlbumArtwork(), CAlbum::art, DownloadAlbumInfo(), g_localizeStrings, CLocalizeStrings::Get(), MUSIC_GRABBER::CMusicAlbumInfo::GetAlbum(), CAlbum::GetAlbumArtistString(), CServiceBroker::GetEventLog(), CScraperUrl::GetFirstUrlByType(), CServiceBroker::GetSettingsComponent(), CScraperUrl::GetThumbUrl(), CInfoScanner::INFO_ADDED, CInfoScanner::INFO_CANCELLED, CInfoScanner::INFO_ERROR, CInfoScanner::INFO_NOT_FOUND, CLog::Log(), LOGDEBUG, m_musicDatabase, MediaTypeAlbum, CAlbum::MergeScrapedAlbum(), CSettings::MUSICLIBRARY_ARTWORK_LEVEL_NONE, MUSIC_GRABBER::CMusicAlbumInfo::SetLoaded(), CSettings::SETTING_MUSICLIBRARY_ARTWORKLEVEL, CSettings::SETTING_MUSICLIBRARY_OVERRIDETAGS, CGUIKeyboardFactory::ShowAndGetInput(), CAlbum::strAlbum, CAlbum::strArtistDesc, CAlbum::strPath, CAlbum::thumbURL, CMusicDatabase::UpdateAlbum(), and Warning.
Referenced by Process(), and UpdateAlbumInfo().
UpdateDatabaseArtistInfo()
CInfoScanner::INFO_RET CMusicInfoScanner::UpdateDatabaseArtistInfo (CArtist & artist, const ADDON::ScraperPtr & scraper, bool bAllowSelection, CGUIDialogProgress * pDialog = NULL) protected
Scrape additional artist information and update the database. Search for the given artist using the given scraper. If info is found, update the database and artwork with the new information.
Parameters
artist [in/out] the artist to update
scraper [in] the artist scraper to use
bAllowSelection [in] should we allow the user to manually override the info with a GUI if the album is not found?
pDialog [in] a progress dialog which this and downstream functions can update with status, if required
References AddArtistArtwork(), DownloadArtistInfo(), XFILE::CDirectory::Exists(), g_localizeStrings, CLocalizeStrings::Get(), MUSIC_GRABBER::CMusicArtistInfo::GetArtist(), CMusicDatabase::GetArtistPath(), CServiceBroker::GetEventLog(), CScraperUrl::GetFirstUrlByType(), CMusicDatabase::GetOldArtistPath(), CServiceBroker::GetSettingsComponent(), CScraperUrl::GetThumbUrl(), CArtist::idArtist, CInfoScanner::INFO_ADDED, CInfoScanner::INFO_CANCELLED, CInfoScanner::INFO_ERROR, CInfoScanner::INFO_NOT_FOUND, CLog::Log(), LOGDEBUG, m_musicDatabase, MediaTypeArtist, CArtist::MergeScrapedArtist(), CSettings::MUSICLIBRARY_ARTWORK_LEVEL_NONE, MUSIC_GRABBER::CMusicArtistInfo::SetLoaded(), CSettings::SETTING_MUSICLIBRARY_ARTWORKLEVEL, CSettings::SETTING_MUSICLIBRARY_OVERRIDETAGS, CGUIKeyboardFactory::ShowAndGetInput(), CArtist::strArtist, CArtist::strPath, CArtist::thumbURL, CMusicDatabase::UpdateArtist(), and Warning.
Referenced by Process(), and UpdateArtistInfo().
Member Data Documentation
m_albumsAdded
std::set<int> MUSIC_INFO::CMusicInfoScanner::m_albumsAdded protected
Referenced by Process(), RetrieveMusicInfo(), and Start().
m_bStop
bool MUSIC_INFO::CMusicInfoScanner::m_bStop protected
Referenced by CMusicInfoScanner(), CountFilesRecursively(), DoScan(), DownloadAlbumInfo(), DownloadArtistInfo(), Process(), RetrieveMusicInfo(), ScanTags(), and Stop().
m_currentItem
int MUSIC_INFO::CMusicInfoScanner::m_currentItem protected
Referenced by CMusicInfoScanner(), DoScan(), Process(), and ScanTags().
m_fileCountReader
CThread MUSIC_INFO::CMusicInfoScanner::m_fileCountReader protected
Referenced by FetchAlbumInfo(), FetchArtistInfo(), Process(), and Start().
m_flags
int MUSIC_INFO::CMusicInfoScanner::m_flags protected
Referenced by CMusicInfoScanner(), DoScan(), Process(), and Start().
m_idSourcePath
int MUSIC_INFO::CMusicInfoScanner::m_idSourcePath protected
Referenced by RetrieveMusicInfo(), and Start().
m_itemCount
int MUSIC_INFO::CMusicInfoScanner::m_itemCount protected
Referenced by CMusicInfoScanner(), DoScan(), Process(), Run(), and ScanTags().
m_musicDatabase
CMusicDatabase MUSIC_INFO::CMusicInfoScanner::m_musicDatabase protected
Referenced by AddAlbumArtwork(), AddArtistArtwork(), DoScan(), DownloadAlbumInfo(), DownloadArtistInfo(), FetchAlbumInfo(), FetchArtistInfo(), Process(), RetrieveMusicInfo(), Start(), Stop(), UpdateAlbumInfo(), UpdateArtistInfo(), UpdateDatabaseAlbumInfo(), and UpdateDatabaseArtistInfo().
m_needsCleanup
bool MUSIC_INFO::CMusicInfoScanner::m_needsCleanup = false protected
Referenced by Process(), and RetrieveMusicInfo().
m_scanType
int MUSIC_INFO::CMusicInfoScanner::m_scanType = 0 protected
Referenced by FetchAlbumInfo(), FetchArtistInfo(), Process(), and Start().
m_seenPaths
std::set<std::string> MUSIC_INFO::CMusicInfoScanner::m_seenPaths protected
Referenced by DoScan(), Process(), and Start().
The documentation for this class was generated from the following files:
MusicInfoScanner.h
MusicInfoScanner.cpp