Kodi Documentation: StreamUtils Class Reference
StreamUtils Class Reference
#include <StreamUtils.h>
Static Public Member Functions
static int GetCodecPriority (const std::string &codec)
static constexpr uint32_t MakeFourCC (char c1, char c2, char c3, char c4)
Make a FourCC code as unsigned integer value.
Member Function Documentation
GetCodecPriority()
int StreamUtils::GetCodecPriority (const std::string & codec) static
Referenced by CStreamDetailAudio::IsWorseThan(), PredicateAudioFilter::operator()(), and TEST().
MakeFourCC()
static constexpr uint32_t StreamUtils::MakeFourCC (char c1, char c2, char c3, char c4) inline static constexpr
Make a FourCC code as unsigned integer value.
Parameters
c1 The first FourCC char
c2 The second FourCC char
c3 The third FourCC char
c4 The fourth FourCC char
Returns
The FourCC as unsigned integer value
The documentation for this class was generated from the following files:
StreamUtils.h
StreamUtils.cpp