Kodi Documentation: CSpecialProtocol Class Reference
CSpecialProtocol Class Reference
#include <SpecialProtocol.h>
Static Public Member Functions
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
static void SetProfilePath (const std::string &path)
static void SetXBMCPath (const std::string &path)
static void SetXBMCBinPath (const std::string &path)
static void SetXBMCBinAddonPath (const std::string &path)
static void SetXBMCAltBinAddonPath (const std::string &path)
static void SetXBMCFrameworksPath (const std::string &path)
static void SetHomePath (const std::string &path)
static void SetUserHomePath (const std::string &path)
static void SetEnvHomePath (const std::string &path)
static void SetMasterProfilePath (const std::string &path)
static void SetTempPath (const std::string &path)
static void SetLogPath (const std::string &dir)
static bool ComparePath (const std::string &path1, const std::string &path2)
static void LogPaths ()
static std::string TranslatePath (const std::string &path)
static std::string TranslatePath (const CURL &url)
static std::string TranslatePathConvertCase (const std::string &path)
Static Private Member Functions
static void SetPath (const std::string &key, const std::string &path)
static std::string GetPath (const std::string &key)
Static Private Attributes
static const CProfileManager * m_profileManager = nullptr
static std::map< std::string, std::string > m_pathMap
Member Function Documentation
ComparePath()
bool CSpecialProtocol::ComparePath (const std::string & path1, const std::string & path2) static
References TranslatePath().
Referenced by ADDON::CAddonMgr::FindAddon(), and ADDON::CAddonMgr::FindAddons().
GetPath()
std::string CSpecialProtocol::GetPath (const std::string & key) static private
References m_pathMap.
Referenced by LogPaths(), SetProfilePath(), and TranslatePath().
LogPaths()
void CSpecialProtocol::LogPaths () static
References CUtil::GetFrameworksPath(), GetPath(), CLog::Log(), and LOGINFO.
Referenced by CApplication::PrintStartupLog().
RegisterProfileManager()
void CSpecialProtocol::RegisterProfileManager (const CProfileManager & profileManager) static
References m_profileManager.
Referenced by CSettingsComponent::Load().
SetEnvHomePath()
void CSpecialProtocol::SetEnvHomePath (const std::string & path) static
References SetPath().
Referenced by CPlatformPosix::InitStageOne().
SetHomePath()
void CSpecialProtocol::SetHomePath (const std::string & path) static
References SetPath().
Referenced by CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), CSettingsComponent::InitDirectoriesWin32(), and CXBMCTestUtils::SetReferenceFileBasePath().
SetLogPath()
void CSpecialProtocol::SetLogPath (const std::string & dir) static
References SetPath().
Referenced by CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), and CSettingsComponent::InitDirectoriesWin32().
SetMasterProfilePath()
void CSpecialProtocol::SetMasterProfilePath (const std::string & path) static
References SetPath().
Referenced by CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), and CSettingsComponent::InitDirectoriesWin32().
SetPath()
void CSpecialProtocol::SetPath (const std::string & key, const std::string & path) static private
References m_pathMap.
Referenced by SetEnvHomePath(), SetHomePath(), SetLogPath(), SetMasterProfilePath(), SetProfilePath(), SetTempPath(), SetUserHomePath(), SetXBMCAltBinAddonPath(), SetXBMCBinAddonPath(), SetXBMCBinPath(), SetXBMCFrameworksPath(), and SetXBMCPath().
SetProfilePath()
void CSpecialProtocol::SetProfilePath (const std::string & path) static
References GetPath(), CLog::Log(), LOGINFO, and SetPath().
Referenced by CProfileManager::SetCurrentProfileId(), and TestBasicEnvironment::SetUp().
SetTempPath()
void CSpecialProtocol::SetTempPath (const std::string & path) static
References SetPath().
Referenced by CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), CSettingsComponent::InitDirectoriesWin32(), and TestBasicEnvironment::SetUp().
SetUserHomePath()
void CSpecialProtocol::SetUserHomePath (const std::string & path) static
References SetPath().
SetXBMCAltBinAddonPath()
void CSpecialProtocol::SetXBMCAltBinAddonPath (const std::string & path) static
References SetPath().
Referenced by CSettingsComponent::InitDirectoriesLinux(), and CSettingsComponent::InitDirectoriesOSX().
SetXBMCBinAddonPath()
void CSpecialProtocol::SetXBMCBinAddonPath (const std::string & path) static
References SetPath().
Referenced by CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), and CSettingsComponent::InitDirectoriesWin32().
SetXBMCBinPath()
void CSpecialProtocol::SetXBMCBinPath (const std::string & path) static
References SetPath().
Referenced by CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), CSettingsComponent::InitDirectoriesWin32(), and CXBMCTestUtils::SetReferenceFileBasePath().
SetXBMCFrameworksPath()
void CSpecialProtocol::SetXBMCFrameworksPath (const std::string & path) static
References SetPath().
Referenced by CSettingsComponent::InitDirectoriesOSX(), and TestBasicEnvironment::SetUp().
SetXBMCPath()
void CSpecialProtocol::SetXBMCPath (const std::string & path) static
References SetPath().
Referenced by CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), CSettingsComponent::InitDirectoriesWin32(), and CXBMCTestUtils::SetReferenceFileBasePath().
TranslatePath() [1/2]
std::string CSpecialProtocol::TranslatePath (const CURL & url) static
References URIUtils::AddFileToFolder(), CURL::Get(), CProfileManager::GetDatabaseFolder(), CURL::GetFileName(), GetPath(), CServiceBroker::GetSettingsComponent(), CProfileManager::GetThumbnailsFolder(), CProfileManager::GetUserDataFolder(), CServiceBroker::GetWinSystem(), CURL::IsProtocol(), URIUtils::IsSpecial(), CLog::Log(), LOGWARNING, m_profileManager, CUtil::MusicPlaylistsLocation(), CSettings::SETTING_AUDIOCDS_RECORDINGPATH, CSettings::SETTING_DEBUG_SCREENSHOTPATH, CSettings::SETTING_MUSICLIBRARY_ARTISTSFOLDER, CSettings::SETTING_SUBTITLES_CUSTOMPATH, TranslatePath(), CUtil::ValidatePath(), and CUtil::VideoPlaylistsLocation().
TranslatePath() [2/2]
std::string CSpecialProtocol::TranslatePath (const std::string & path) static
References CURL::IsProtocol(), and TranslatePath().
Referenced by AnnounceBridge(), CFileUtils::CheckFileAccessAllowed(), ComparePath(), CDVDSubtitlesLibass::Configure(), CApplication::Create(), CSettingsComponent::CreateUserDirs(), CTeletextDecoder::CTeletextDecoder(), CWinSystemWin32::CWinSystemWin32(), ADDON::CAddonMgr::DeInit(), dll_findfirst64i32(), dll_mkdir(), dll_opendir(), CPythonInvoker::Execute(), CPythonInvoker::execute(), ADDON::CAddonInfoBuilder::Generate(), ADDON::Interface_Base::get_addon_path(), ADDON::Interface_Filesystem::get_disk_space(), ADDON::IAddonInstanceHandler::get_instance_user_path(), ADDON::Interface_Base::get_lib_path(), ADDON::Interface_Base::get_temp_path(), ADDON::Interface_Base::get_user_path(), CPythonInvoker::getAddonModuleDeps(), XFILE::CSpecialProtocolDirectory::GetDirectory(), XFILE::CTVOSDirectory::GetDirectory(), ADDON::CAddonDll::GetDllPath(), CFreeTypeLibrary::GetFont(), KODI::GAME::CGameUtils::GetGameClients(), KODI::GAME::CGameClientProperties::GetLibraryPath(), CWin32StorageProvider::GetLocalDrives(), CStorageProvider::GetLocalDrives(), KODI::GAME::CGameClientProperties::GetProfileDirectory(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), CWakeOnAccess::GetSettingFile(), KODI::UTILS::FONT::FONTPATH::GetSystemFontPath(), CSMB::Init(), init_emu_environ(), CSettingsComponent::InitDirectoriesWin32(), CDatabase::InitSettings(), CPlatformAndroid::InitStageOne(), CPlatformDarwin::InitStageOne(), CPlatformWebOS::InitStageOne(), ADDON::CAddonMgr::IsBundledAddon(), URIUtils::IsDAV(), URIUtils::IsFTP(), URIUtils::IsHD(), URIUtils::IsHTTP(), URIUtils::IsNfs(), URIUtils::IsOnLAN(), URIUtils::IsRemote(), URIUtils::IsSmb(), Win32DllLoader::Load(), SoLoader::Load(), GUIFontManager::LoadFonts(), CApplication::OnAction(), CGUIDialogSubtitles::OnDownloadComplete(), XBPython::OnScriptInitialized(), DebugLogSharingPresenter::OnSettingAction(), CDVDInputStreamNavigator::Open(), CInputStreamAddon::Open(), XFILE::CSimpleFileCache::Open(), CXBTFReader::Open(), KODI::GAME::CGameClient::OpenFile(), Win32DllLoader::OverrideImports(), CAdvancedSettings::ParseSettingsFile(), URIUtils::PathHasParent(), CApplication::PrintStartupLog(), CGUIWindowDebugInfo::Process(), CXBMCTestUtils::ReferenceFilePath(), PVR::CPVRClient::ResetProperties(), PERIPHERALS::CPeripheralAddon::ResetProperties(), RunScript(), XFILE::CCurlFile::SetCommonOptions(), ADDON::CSkinInfo::SettingOptionsSkinFontsFiller(), AddonDatabaseTest::SetUp(), UPNP::CUPnPRenderer::SetupIcons(), UPNP::CUPnPServer::SetupIcons(), CDVDInputStreamBluray::SetupPlayerSettings(), KODI::CDRIP::CCDDARipJob::SetupTempFile(), KODI::PLATFORM::FILESYSTEM::space(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), ADDON::Interface_Filesystem::translate_special_protocol(), TranslatePath(), XFILE::CSpecialProtocolDirectory::TranslatePath(), XFILE::CSpecialProtocolFile::TranslatePath(), TranslatePath(), XBMCAddon::xbmcvfs::translatePath(), TranslatePathConvertCase(), translatePathIntoKey(), CXBMCApp::UpdateSessionMetadata(), CGUIVisualisationControl::UpdateTrack(), and XFILE::CTVOSDirectory::WantsDirectory().
TranslatePathConvertCase()
std::string CSpecialProtocol::TranslatePathConvertCase (const std::string & path) static
References closedir(), dirent::d_name, opendir(), readdir(), and TranslatePath().
Referenced by CheckFont(), ADDON::CFontResource::GetFont(), CUtil::GetSplashPath(), CGUIColorManager::Load(), CWebVTTHandler::LoadColors(), CGUIDialogColorPicker::LoadColors(), ADDON::CSkinInfo::LoadIncludes(), LoadStr2Mem(), ADDON::CSkinInfo::LoadTimers(), GUIFontManager::LoadTTF(), CTextureBundleXBT::OpenBundle(), and ADDON::CSkinInfo::SettingOptionsSkinColorsFiller().
UnregisterProfileManager()
void CSpecialProtocol::UnregisterProfileManager () static
References m_profileManager.
Referenced by CSettingsComponent::Deinitialize().
Member Data Documentation
m_pathMap
std::map< std::string, std::string > CSpecialProtocol::m_pathMap static private
Referenced by GetPath(), and SetPath().
m_profileManager
const CProfileManager * CSpecialProtocol::m_profileManager = nullptr static private
Referenced by RegisterProfileManager(), TranslatePath(), and UnregisterProfileManager().
The documentation for this class was generated from the following files:
SpecialProtocol.h
SpecialProtocol.cpp
SystemGlobals.cpp