Kodi Documentation: PERIPHERALS::CPeripheralAddon Class Reference
PERIPHERALS::CPeripheralAddon Class Reference
#include <PeripheralAddon.h>
Public Member Functions
CPeripheralAddon (const ADDON::AddonInfoPtr &addonInfo, CPeripherals &manager)
~CPeripheralAddon (void) override
bool CreateAddon (void)
Initialise the instance of this add-on.
void DestroyAddon ()
Deinitialize the instance of this add-on.
bool Register (unsigned int peripheralIndex, const PeripheralPtr &peripheral)
void UnregisterRemovedDevices (const PeripheralScanResults &results, PeripheralVector &removedPeripherals)
void GetFeatures (std::vector< PeripheralFeature > &features) const
bool HasFeature (const PeripheralFeature feature) const
PeripheralPtr GetPeripheral (unsigned int index) const
PeripheralPtr GetByPath (const std::string &strPath) const
bool SupportsFeature (PeripheralFeature feature) const
unsigned int GetPeripheralsWithFeature (PeripheralVector &results, const PeripheralFeature feature) const
unsigned int GetNumberOfPeripherals (void) const
unsigned int GetNumberOfPeripheralsWithId (const int iVendorId, const int iProductId) const
void GetDirectory (const std::string &strPath, CFileItemList &items) const
Peripheral add-on methods
bool PerformDeviceScan (PeripheralScanResults &results)
bool ProcessEvents (void)
bool SendRumbleEvent (unsigned int index, unsigned int driverIndex, float magnitude)
Public Member Functions inherited from ADDON::IAddonInstanceHandler
IAddonInstanceHandler (ADDON_TYPE type, const AddonInfoPtr &addonInfo, AddonInstanceId instanceId=ADDON_INSTANCE_ID_UNUSED, KODI_HANDLE parentInstance=nullptr, const std::string &uniqueWorkID="")
Class constructor for handling add-on instance processes, allowing an add-on to handle multiple work simultaneously and independently.
virtual ~IAddonInstanceHandler ()
ADDON_TYPE UsedType () const
AddonInstanceId InstanceId () const
const std::string & UniqueWorkID ()
std::string ID () const
AddonInstanceId InstanceID () const
std::string Name () const
std::string Author () const
std::string Icon () const
std::string Path () const
std::string Profile () const
CAddonVersion Version () const
ADDON_STATUS CreateInstance ()
void DestroyInstance ()
const AddonDllPtr & Addon () const
AddonInfoPtr GetAddonInfo () const
virtual void OnPreInstall ()
virtual void OnPostInstall (bool update, bool modal)
virtual void OnPreUnInstall ()
virtual void OnPostUnInstall ()
Joystick methods
CPeripherals & m_manager
std::string m_strUserPath
translated path to the user profile
std::string m_strClientPath
translated path to this add-on
bool m_bProvidesJoysticks
bool m_bSupportsJoystickRumble = false
bool m_bSupportsJoystickPowerOff = false
bool m_bProvidesButtonMaps
std::map< unsigned int, PeripheralPtr > m_peripherals
std::vector< std::pair< CPeripheral *, KODI::JOYSTICK::IButtonMap * > > m_buttonMaps
CCriticalSection m_buttonMapMutex
CCriticalSection m_critSection
CSharedSection m_dllSection
bool GetJoystickProperties (unsigned int index, CPeripheralJoystick &joystick)
bool HasButtonMaps (void) const
bool GetAppearance (const CPeripheral *device, std::string &controllerId)
bool SetAppearance (const CPeripheral *device, const std::string &controllerId)
bool GetFeatures (const CPeripheral *device, const std::string &strControllerId, FeatureMap &features)
bool MapFeature (const CPeripheral *device, const std::string &strControllerId, const kodi::addon::JoystickFeature &feature)
bool GetIgnoredPrimitives (const CPeripheral *device, PrimitiveVector &primitives)
bool SetIgnoredPrimitives (const CPeripheral *device, const PrimitiveVector &primitives)
void SaveButtonMap (const CPeripheral *device)
void RevertButtonMap (const CPeripheral *device)
void ResetButtonMap (const CPeripheral *device, const std::string &strControllerId)
void PowerOffJoystick (unsigned int index)
void RegisterButtonMap (CPeripheral *device, KODI::JOYSTICK::IButtonMap *buttonMap)
void UnregisterButtonMap (KODI::JOYSTICK::IButtonMap *buttonMap)
static bool ProvidesJoysticks (const ADDON::AddonInfoPtr &addonInfo)
static bool ProvidesButtonMaps (const ADDON::AddonInfoPtr &addonInfo)
void UnregisterButtonMap (CPeripheral *device)
void TriggerDeviceScan ()
void RefreshButtonMaps (const std::string &strDeviceName="")
unsigned int FeatureCount (const std::string &controllerId, JOYSTICK_FEATURE_TYPE type) const
JOYSTICK_FEATURE_TYPE FeatureType (const std::string &controllerId, const std::string &featureName) const
void ResetProperties (void)
Reset all class members to their defaults. Called by the constructors.
bool GetAddonProperties (void)
Retrieve add-on properties from the add-on.
bool LogError (const PERIPHERAL_ERROR error, const char *strMethod) const
static void GetPeripheralInfo (const CPeripheral *device, kodi::addon::Peripheral &peripheralInfo)
Helper functions.
static void GetJoystickInfo (const CPeripheral *device, kodi::addon::Joystick &joystickInfo)
static void SetJoystickInfo (CPeripheralJoystick &joystick, const kodi::addon::Joystick &joystickInfo)
static std::string GetDeviceName (PeripheralType type)
static std::string GetProvider (PeripheralType type)
static void cb_trigger_scan (void *kodiInstance)
Callback functions from addon to kodi.
static void cb_refresh_button_maps (void *kodiInstance, const char *deviceName, const char *controllerId)
static unsigned int cb_feature_count (void *kodiInstance, const char *controllerId, JOYSTICK_FEATURE_TYPE type)
static JOYSTICK_FEATURE_TYPE cb_feature_type (void *kodiInstance, const char *controllerId, const char *featureName)
Additional Inherited Members
Protected Attributes inherited from ADDON::IAddonInstanceHandler
KODI_ADDON_INSTANCE_INFO m_info {}
KODI_ADDON_INSTANCE_STRUCT m_ifc {}
Constructor & Destructor Documentation
CPeripheralAddon()
CPeripheralAddon::CPeripheralAddon (const ADDON::AddonInfoPtr & addonInfo, CPeripherals & manager) explicit
References m_bProvidesButtonMaps, m_bProvidesJoysticks, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, ADDON::PERIPHERALDLL, AddonInstance_Peripheral::props, ResetProperties(), AddonInstance_Peripheral::toAddon, and AddonInstance_Peripheral::toKodi.
~CPeripheralAddon()
CPeripheralAddon::~CPeripheralAddon (void) override
References DestroyAddon(), ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, AddonInstance_Peripheral::props, AddonInstance_Peripheral::toAddon, and AddonInstance_Peripheral::toKodi.
Member Function Documentation
cb_feature_count()
unsigned int CPeripheralAddon::cb_feature_count (void * kodiInstance, const char * controllerId, JOYSTICK_FEATURE_TYPE type) static private
References FeatureCount().
Referenced by ResetProperties().
cb_feature_type()
JOYSTICK_FEATURE_TYPE CPeripheralAddon::cb_feature_type (void * kodiInstance, const char * controllerId, const char * featureName) static private
References FeatureType(), and JOYSTICK_FEATURE_TYPE_UNKNOWN.
Referenced by ResetProperties().
cb_refresh_button_maps()
void CPeripheralAddon::cb_refresh_button_maps (void * kodiInstance, const char * deviceName, const char * controllerId) static private
References RefreshButtonMaps().
Referenced by ResetProperties().
cb_trigger_scan()
void CPeripheralAddon::cb_trigger_scan (void * kodiInstance) static private
Callback functions from addon to kodi.
References TriggerDeviceScan().
Referenced by ResetProperties().
CreateAddon()
bool CPeripheralAddon::CreateAddon (void)
Initialise the instance of this add-on.
References ADDON_STATUS_OK, XFILE::CDirectory::Create(), ADDON::IAddonInstanceHandler::CreateInstance(), ADDON::IAddonInstanceHandler::DestroyInstance(), XFILE::CDirectory::Exists(), GetAddonProperties(), CLog::Log(), LOGDEBUG, m_dllSection, m_strUserPath, ADDON::IAddonInstanceHandler::Name(), and ResetProperties().
DestroyAddon()
void CPeripheralAddon::DestroyAddon ()
Deinitialize the instance of this add-on.
References ADDON::IAddonInstanceHandler::DestroyInstance(), m_buttonMapMutex, m_buttonMaps, m_critSection, m_dllSection, and m_peripherals.
Referenced by ~CPeripheralAddon().
FeatureCount()
unsigned int CPeripheralAddon::FeatureCount (const std::string & controllerId, JOYSTICK_FEATURE_TYPE type) const private
References PERIPHERALS::CPeripherals::GetControllerProfiles(), m_manager, and PERIPHERALS::CPeripheralAddonTranslator::TranslateFeatureType().
Referenced by cb_feature_count().
FeatureType()
JOYSTICK_FEATURE_TYPE CPeripheralAddon::FeatureType (const std::string & controllerId, const std::string & featureName) const private
References PERIPHERALS::CPeripherals::GetControllerProfiles(), JOYSTICK_FEATURE_TYPE_UNKNOWN, m_manager, and PERIPHERALS::CPeripheralAddonTranslator::TranslateFeatureType().
Referenced by cb_feature_type().
GetAddonProperties()
bool CPeripheralAddon::GetAddonProperties (void) private
Retrieve add-on properties from the add-on.
References ADDON::IAddonInstanceHandler::Author(), CLog::Log(), LOGERROR, m_bProvidesButtonMaps, m_bProvidesJoysticks, m_bSupportsJoystickPowerOff, m_bSupportsJoystickRumble, ADDON::IAddonInstanceHandler::m_ifc, ADDON::IAddonInstanceHandler::Name(), KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERAL_CAPABILITIES::provides_buttonmaps, PERIPHERAL_CAPABILITIES::provides_joystick_power_off, PERIPHERAL_CAPABILITIES::provides_joystick_rumble, PERIPHERAL_CAPABILITIES::provides_joysticks, and AddonInstance_Peripheral::toAddon.
Referenced by CreateAddon().
GetAppearance()
bool CPeripheralAddon::GetAppearance (const CPeripheral * device, std::string & controllerId)
References kodi::addon::Joystick::FreeStruct(), GetJoystickInfo(), LogError(), m_bProvidesButtonMaps, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, and kodi::addon::Joystick::ToStruct().
GetByPath()
PeripheralPtr CPeripheralAddon::GetByPath (const std::string & strPath) const
References m_critSection, and m_peripherals.
GetDeviceName()
std::string CPeripheralAddon::GetDeviceName (PeripheralType type) static private
References KEYBOARD_BUTTON_MAP_NAME, MOUSE_BUTTON_MAP_NAME, PERIPHERALS::PERIPHERAL_KEYBOARD, and PERIPHERALS::PERIPHERAL_MOUSE.
Referenced by GetJoystickInfo().
GetDirectory()
void CPeripheralAddon::GetDirectory (const std::string & strPath, CFileItemList & items) const
References CFileItemList::Add(), PERIPHERALS::PeripheralTypeTranslator::BusTypeToString(), m_critSection, m_peripherals, and PERIPHERALS::PeripheralTypeTranslator::TypeToString().
GetFeatures() [1/2]
bool CPeripheralAddon::GetFeatures (const CPeripheral * device, const std::string & strControllerId, FeatureMap & features)
References kodi::addon::Joystick::FreeStruct(), GetJoystickInfo(), JOYSTICK_FEATURE_TYPE_UNKNOWN, LogError(), m_bProvidesButtonMaps, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, kodi::addon::JoystickFeature::Name(), KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, kodi::addon::Joystick::ToStruct(), and kodi::addon::JoystickFeature::Type().
GetFeatures() [2/2]
void CPeripheralAddon::GetFeatures (std::vector< PeripheralFeature > & features) const
References PERIPHERALS::FEATURE_JOYSTICK, and m_bProvidesJoysticks.
GetIgnoredPrimitives()
bool CPeripheralAddon::GetIgnoredPrimitives (const CPeripheral * device, PrimitiveVector & primitives)
References kodi::addon::Joystick::FreeStruct(), GetJoystickInfo(), LogError(), m_bProvidesButtonMaps, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, and kodi::addon::Joystick::ToStruct().
GetJoystickInfo()
void CPeripheralAddon::GetJoystickInfo (const CPeripheral * device, kodi::addon::Joystick & joystickInfo) static private
References PERIPHERALS::CPeripheralJoystick::AxisCount(), PERIPHERALS::CPeripheralJoystick::ButtonCount(), GetDeviceName(), GetPeripheralInfo(), GetProvider(), PERIPHERALS::CPeripheralJoystick::HatCount(), PERIPHERALS::CPeripheralJoystick::MotorCount(), PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERALS::PERIPHERAL_KEYBOARD, PERIPHERALS::PERIPHERAL_MOUSE, PERIPHERALS::CPeripheralJoystick::Provider(), kodi::addon::Joystick::SetAxisCount(), kodi::addon::Joystick::SetButtonCount(), kodi::addon::Joystick::SetHatCount(), kodi::addon::Joystick::SetMotorCount(), kodi::addon::Peripheral::SetName(), kodi::addon::Joystick::SetProvider(), kodi::addon::Joystick::SetSupportsPowerOff(), PERIPHERALS::CPeripheralJoystick::SupportsPowerOff(), and PERIPHERALS::CPeripheral::Type().
Referenced by GetAppearance(), GetFeatures(), GetIgnoredPrimitives(), MapFeature(), ResetButtonMap(), RevertButtonMap(), SaveButtonMap(), SetAppearance(), and SetIgnoredPrimitives().
GetJoystickProperties()
bool CPeripheralAddon::GetJoystickProperties (unsigned int index, CPeripheralJoystick & joystick)
References index(), LogError(), m_bProvidesJoysticks, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERAL_NO_ERROR, SetJoystickInfo(), and AddonInstance_Peripheral::toAddon.
GetNumberOfPeripherals()
unsigned int CPeripheralAddon::GetNumberOfPeripherals (void) const
References m_critSection, and m_peripherals.
GetNumberOfPeripheralsWithId()
unsigned int CPeripheralAddon::GetNumberOfPeripheralsWithId (const int iVendorId, const int iProductId) const
References m_critSection, and m_peripherals.
GetPeripheral()
PeripheralPtr CPeripheralAddon::GetPeripheral (unsigned int index) const
References index(), m_critSection, and m_peripherals.
Referenced by ProcessEvents().
GetPeripheralInfo()
void CPeripheralAddon::GetPeripheralInfo (const CPeripheral * device, kodi::addon::Peripheral & peripheralInfo) static private
Helper functions.
References PERIPHERALS::CPeripheral::DeviceName(), PERIPHERALS::CPeripheral::ProductId(), kodi::addon::Peripheral::SetName(), kodi::addon::Peripheral::SetProductID(), kodi::addon::Peripheral::SetType(), kodi::addon::Peripheral::SetVendorID(), PERIPHERALS::CPeripheralAddonTranslator::TranslateType(), PERIPHERALS::CPeripheral::Type(), and PERIPHERALS::CPeripheral::VendorId().
Referenced by GetJoystickInfo().
GetPeripheralsWithFeature()
unsigned int CPeripheralAddon::GetPeripheralsWithFeature (PeripheralVector & results, const PeripheralFeature feature) const
References m_critSection, and m_peripherals.
GetProvider()
std::string CPeripheralAddon::GetProvider (PeripheralType type) static private
References KEYBOARD_PROVIDER, MOUSE_PROVIDER, PERIPHERALS::PERIPHERAL_KEYBOARD, and PERIPHERALS::PERIPHERAL_MOUSE.
Referenced by GetJoystickInfo().
HasButtonMaps()
bool PERIPHERALS::CPeripheralAddon::HasButtonMaps (void) const inline
References m_bProvidesButtonMaps.
HasFeature()
bool CPeripheralAddon::HasFeature (const PeripheralFeature feature) const
References PERIPHERALS::FEATURE_JOYSTICK, and m_bProvidesJoysticks.
Referenced by PowerOffJoystick().
LogError()
bool CPeripheralAddon::LogError (const PERIPHERAL_ERROR error, const char * strMethod) const private
References CLog::Log(), LOGERROR, ADDON::IAddonInstanceHandler::Name(), PERIPHERAL_NO_ERROR, and PERIPHERALS::CPeripheralAddonTranslator::TranslateError().
Referenced by GetAppearance(), GetFeatures(), GetIgnoredPrimitives(), GetJoystickProperties(), MapFeature(), PerformDeviceScan(), ProcessEvents(), SetAppearance(), and SetIgnoredPrimitives().
MapFeature()
bool CPeripheralAddon::MapFeature (const CPeripheral * device, const std::string & strControllerId, const kodi::addon::JoystickFeature & feature)
References kodi::addon::JoystickFeature::FreeStruct(), kodi::addon::Joystick::FreeStruct(), GetJoystickInfo(), LogError(), m_bProvidesButtonMaps, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, kodi::addon::JoystickFeature::ToStruct(), and kodi::addon::Joystick::ToStruct().
PerformDeviceScan()
bool CPeripheralAddon::PerformDeviceScan (PeripheralScanResults & results)
References PERIPHERALS::PeripheralScanResults::ContainsResult(), ADDON::IAddonInstanceHandler::ID(), kodi::addon::Peripheral::Index(), LogError(), m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, PERIPHERALS::PeripheralScanResult::m_iProductId, PERIPHERALS::PeripheralScanResult::m_iSequence, PERIPHERALS::PeripheralScanResult::m_iVendorId, PERIPHERALS::PeripheralScanResult::m_mappedBusType, PERIPHERALS::PeripheralScanResult::m_mappedType, PERIPHERALS::PeripheralScanResults::m_results, PERIPHERALS::PeripheralScanResult::m_strDeviceName, PERIPHERALS::PeripheralScanResult::m_strLocation, PERIPHERALS::PeripheralScanResult::m_type, kodi::addon::Peripheral::Name(), KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERALS::PERIPHERAL_BUS_ADDON, PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERAL_NO_ERROR, PERIPHERAL_TYPE_JOYSTICK, kodi::addon::Peripheral::ProductID(), AddonInstance_Peripheral::toAddon, kodi::addon::Peripheral::Type(), and kodi::addon::Peripheral::VendorID().
PowerOffJoystick()
void CPeripheralAddon::PowerOffJoystick (unsigned int index)
References PERIPHERALS::FEATURE_JOYSTICK, PERIPHERALS::FEATURE_POWER_OFF, HasFeature(), index(), m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, SupportsFeature(), and AddonInstance_Peripheral::toAddon.
ProcessEvents()
bool CPeripheralAddon::ProcessEvents (void)
References kodi::addon::PeripheralEvent::AxisState(), kodi::addon::PeripheralEvent::DriverIndex(), GetPeripheral(), kodi::addon::PeripheralEvent::HatState(), JOYSTICK_STATE_BUTTON_PRESSED, LogError(), m_bProvidesJoysticks, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, m_peripherals, KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERAL_EVENT_TYPE_DRIVER_AXIS, PERIPHERAL_EVENT_TYPE_DRIVER_BUTTON, PERIPHERAL_EVENT_TYPE_DRIVER_HAT, PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERAL_NO_ERROR, kodi::addon::PeripheralEvent::PeripheralIndex(), AddonInstance_Peripheral::toAddon, PERIPHERALS::CPeripheralAddonTranslator::TranslateHatState(), and kodi::addon::PeripheralEvent::Type().
ProvidesButtonMaps()
bool CPeripheralAddon::ProvidesButtonMaps (const ADDON::AddonInfoPtr & addonInfo) static
References ADDON::PERIPHERALDLL.
ProvidesJoysticks()
bool CPeripheralAddon::ProvidesJoysticks (const ADDON::AddonInfoPtr & addonInfo) static
References ADDON::PERIPHERALDLL.
Referenced by PERIPHERALS::CPeripheralBusAddon::PromptEnableAddons().
RefreshButtonMaps()
void CPeripheralAddon::RefreshButtonMaps (const std::string & strDeviceName = "") private
References m_buttonMapMutex, and m_buttonMaps.
Referenced by cb_refresh_button_maps(), ResetButtonMap(), and SaveButtonMap().
Register()
bool CPeripheralAddon::Register (unsigned int peripheralIndex, const PeripheralPtr & peripheral)
References PERIPHERALS::PeripheralTypeTranslator::BusTypeToString(), CLog::Log(), LOGINFO, m_critSection, m_peripherals, PERIPHERALS::PERIPHERAL_BUS_ADDON, PERIPHERALS::PERIPHERAL_JOYSTICK, and PERIPHERALS::PeripheralTypeTranslator::TypeToString().
RegisterButtonMap()
void CPeripheralAddon::RegisterButtonMap (CPeripheral * device, KODI::JOYSTICK::IButtonMap * buttonMap)
References m_buttonMapMutex, m_buttonMaps, and UnregisterButtonMap().
ResetButtonMap()
void CPeripheralAddon::ResetButtonMap (const CPeripheral * device, const std::string & strControllerId)
References PERIPHERALS::CPeripheral::DeviceName(), kodi::addon::Joystick::FreeStruct(), GetJoystickInfo(), m_bProvidesButtonMaps, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, RefreshButtonMaps(), AddonInstance_Peripheral::toAddon, and kodi::addon::Joystick::ToStruct().
ResetProperties()
void CPeripheralAddon::ResetProperties (void) private
Reset all class members to their defaults. Called by the constructors.
References AddonProps_Peripheral::addon_path, cb_feature_count(), cb_feature_type(), cb_refresh_button_maps(), cb_trigger_scan(), AddonToKodiFuncTable_Peripheral::feature_count, AddonToKodiFuncTable_Peripheral::kodiInstance, ADDON::IAddonInstanceHandler::m_ifc, m_strClientPath, m_strUserPath, ADDON::IAddonInstanceHandler::Path(), KODI_ADDON_INSTANCE_STRUCT::peripheral, ADDON::IAddonInstanceHandler::Profile(), AddonInstance_Peripheral::props, AddonToKodiFuncTable_Peripheral::refresh_button_maps, AddonInstance_Peripheral::toAddon, AddonInstance_Peripheral::toKodi, CSpecialProtocol::TranslatePath(), AddonToKodiFuncTable_Peripheral::trigger_scan, and AddonProps_Peripheral::user_path.
Referenced by CPeripheralAddon(), and CreateAddon().
RevertButtonMap()
void CPeripheralAddon::RevertButtonMap (const CPeripheral * device)
References kodi::addon::Joystick::FreeStruct(), GetJoystickInfo(), m_bProvidesButtonMaps, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, AddonInstance_Peripheral::toAddon, and kodi::addon::Joystick::ToStruct().
SaveButtonMap()
void CPeripheralAddon::SaveButtonMap (const CPeripheral * device)
References PERIPHERALS::CPeripheral::DeviceName(), kodi::addon::Joystick::FreeStruct(), GetJoystickInfo(), m_bProvidesButtonMaps, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, RefreshButtonMaps(), AddonInstance_Peripheral::toAddon, and kodi::addon::Joystick::ToStruct().
SendRumbleEvent()
bool CPeripheralAddon::SendRumbleEvent (unsigned int index, unsigned int driverIndex, float magnitude)
References PERIPHERAL_EVENT::driver_index, m_bProvidesJoysticks, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, PERIPHERAL_EVENT::motor_state, KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERAL_EVENT_TYPE_SET_MOTOR, PERIPHERAL_EVENT::peripheral_index, AddonInstance_Peripheral::toAddon, and PERIPHERAL_EVENT::type.
SetAppearance()
bool CPeripheralAddon::SetAppearance (const CPeripheral * device, const std::string & controllerId)
References kodi::addon::Joystick::FreeStruct(), GetJoystickInfo(), LogError(), m_bProvidesButtonMaps, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, and kodi::addon::Joystick::ToStruct().
SetIgnoredPrimitives()
bool CPeripheralAddon::SetIgnoredPrimitives (const CPeripheral * device, const PrimitiveVector & primitives)
References kodi::addon::Joystick::FreeStruct(), kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::FreeStructs(), GetJoystickInfo(), LogError(), m_bProvidesButtonMaps, m_dllSection, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::peripheral, PERIPHERAL_NO_ERROR, AddonInstance_Peripheral::toAddon, kodi::addon::Joystick::ToStruct(), and kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::ToStructs().
SetJoystickInfo()
void CPeripheralAddon::SetJoystickInfo (CPeripheralJoystick & joystick, const kodi::addon::Joystick & joystickInfo) static private
References kodi::addon::Joystick::AxisCount(), kodi::addon::Joystick::ButtonCount(), kodi::addon::Joystick::HatCount(), kodi::addon::Joystick::MotorCount(), kodi::addon::Joystick::Provider(), kodi::addon::Joystick::RequestedPort(), PERIPHERALS::CPeripheralJoystick::SetAxisCount(), PERIPHERALS::CPeripheralJoystick::SetButtonCount(), PERIPHERALS::CPeripheralJoystick::SetHatCount(), PERIPHERALS::CPeripheralJoystick::SetMotorCount(), PERIPHERALS::CPeripheralJoystick::SetProvider(), PERIPHERALS::CPeripheralJoystick::SetRequestedPort(), PERIPHERALS::CPeripheralJoystick::SetSupportsPowerOff(), and kodi::addon::Joystick::SupportsPowerOff().
Referenced by GetJoystickProperties().
SupportsFeature()
bool CPeripheralAddon::SupportsFeature (PeripheralFeature feature) const
References PERIPHERALS::FEATURE_POWER_OFF, PERIPHERALS::FEATURE_RUMBLE, m_bSupportsJoystickPowerOff, and m_bSupportsJoystickRumble.
Referenced by PowerOffJoystick().
TriggerDeviceScan()
void CPeripheralAddon::TriggerDeviceScan () private
References m_manager, PERIPHERALS::PERIPHERAL_BUS_ADDON, and PERIPHERALS::CPeripherals::TriggerDeviceScan().
Referenced by cb_trigger_scan().
UnregisterButtonMap() [1/2]
void CPeripheralAddon::UnregisterButtonMap (CPeripheral * device) private
References m_buttonMapMutex, and m_buttonMaps.
UnregisterButtonMap() [2/2]
void CPeripheralAddon::UnregisterButtonMap (KODI::JOYSTICK::IButtonMap * buttonMap)
References m_buttonMapMutex, and m_buttonMaps.
Referenced by RegisterButtonMap(), and UnregisterRemovedDevices().
UnregisterRemovedDevices()
void CPeripheralAddon::UnregisterRemovedDevices (const PeripheralScanResults & results, PeripheralVector & removedPeripherals)
References PERIPHERALS::PeripheralScanResults::GetDeviceOnLocation(), index(), CLog::Log(), LOGINFO, m_critSection, m_peripherals, PERIPHERALS::PERIPHERAL_BUS_ADDON, PERIPHERALS::PeripheralTypeTranslator::TypeToString(), and UnregisterButtonMap().
Member Data Documentation
m_bProvidesButtonMaps
bool PERIPHERALS::CPeripheralAddon::m_bProvidesButtonMaps private
Referenced by CPeripheralAddon(), GetAddonProperties(), GetAppearance(), GetFeatures(), GetIgnoredPrimitives(), HasButtonMaps(), MapFeature(), ResetButtonMap(), RevertButtonMap(), SaveButtonMap(), SetAppearance(), and SetIgnoredPrimitives().
m_bProvidesJoysticks
bool PERIPHERALS::CPeripheralAddon::m_bProvidesJoysticks private
Referenced by CPeripheralAddon(), GetAddonProperties(), GetFeatures(), GetJoystickProperties(), HasFeature(), ProcessEvents(), and SendRumbleEvent().
m_bSupportsJoystickPowerOff
bool PERIPHERALS::CPeripheralAddon::m_bSupportsJoystickPowerOff = false private
Referenced by GetAddonProperties(), and SupportsFeature().
m_bSupportsJoystickRumble
bool PERIPHERALS::CPeripheralAddon::m_bSupportsJoystickRumble = false private
Referenced by GetAddonProperties(), and SupportsFeature().
m_buttonMapMutex
CCriticalSection PERIPHERALS::CPeripheralAddon::m_buttonMapMutex private
Referenced by DestroyAddon(), RefreshButtonMaps(), RegisterButtonMap(), UnregisterButtonMap(), and UnregisterButtonMap().
m_buttonMaps
std::vector<std::pair<CPeripheral*, KODI::JOYSTICK::IButtonMap*> > PERIPHERALS::CPeripheralAddon::m_buttonMaps private
Referenced by DestroyAddon(), RefreshButtonMaps(), RegisterButtonMap(), UnregisterButtonMap(), and UnregisterButtonMap().
m_critSection
CCriticalSection PERIPHERALS::CPeripheralAddon::m_critSection mutable private
Referenced by DestroyAddon(), GetByPath(), GetDirectory(), GetNumberOfPeripherals(), GetNumberOfPeripheralsWithId(), GetPeripheral(), GetPeripheralsWithFeature(), Register(), and UnregisterRemovedDevices().
m_dllSection
CSharedSection PERIPHERALS::CPeripheralAddon::m_dllSection private
Referenced by CreateAddon(), DestroyAddon(), GetAppearance(), GetFeatures(), GetIgnoredPrimitives(), GetJoystickProperties(), MapFeature(), PerformDeviceScan(), PowerOffJoystick(), ProcessEvents(), RevertButtonMap(), SaveButtonMap(), SendRumbleEvent(), SetAppearance(), and SetIgnoredPrimitives().
m_manager
CPeripherals& PERIPHERALS::CPeripheralAddon::m_manager private
Referenced by FeatureCount(), FeatureType(), and TriggerDeviceScan().
m_peripherals
std::map<unsigned int, PeripheralPtr> PERIPHERALS::CPeripheralAddon::m_peripherals private
Referenced by DestroyAddon(), GetByPath(), GetDirectory(), GetNumberOfPeripherals(), GetNumberOfPeripheralsWithId(), GetPeripheral(), GetPeripheralsWithFeature(), ProcessEvents(), Register(), and UnregisterRemovedDevices().
m_strClientPath
std::string PERIPHERALS::CPeripheralAddon::m_strClientPath private
translated path to this add-on
Referenced by ResetProperties().
m_strUserPath
std::string PERIPHERALS::CPeripheralAddon::m_strUserPath private
translated path to the user profile
Referenced by CreateAddon(), and ResetProperties().
The documentation for this class was generated from the following files:
PeripheralAddon.h
PeripheralAddon.cpp