Kodi Documentation: CArchive Class Reference
CArchive Class Reference
#include <Archive.h>
Public Types
enum Mode { load = 0 , store }
Public Member Functions
CArchive (XFILE::CFile *pFile, int mode)
~CArchive ()
CArchive & operator<< (float f)
CArchive & operator<< (double d)
CArchive & operator<< (short int s)
CArchive & operator<< (unsigned short int us)
CArchive & operator<< (int i)
CArchive & operator<< (unsigned int ui)
CArchive & operator<< (long int l)
CArchive & operator<< (unsigned long int ul)
CArchive & operator<< (long long int ll)
CArchive & operator<< (unsigned long long int ull)
CArchive & operator<< (bool b)
CArchive & operator<< (char c)
CArchive & operator<< (const std::string &str)
CArchive & operator<< (const std::wstring &wstr)
CArchive & operator<< (const KODI::TIME::SystemTime &time)
CArchive & operator<< (IArchivable &obj)
CArchive & operator<< (const CVariant &variant)
CArchive & operator<< (const std::vector< std::string > &strArray)
CArchive & operator<< (const std::vector< int > &iArray)
CArchive & operator>> (float &f)
CArchive & operator>> (double &d)
CArchive & operator>> (short int &s)
CArchive & operator>> (unsigned short int &us)
CArchive & operator>> (int &i)
CArchive & operator>> (unsigned int &ui)
CArchive & operator>> (long int &l)
CArchive & operator>> (unsigned long int &ul)
CArchive & operator>> (long long int &ll)
CArchive & operator>> (unsigned long long int &ull)
CArchive & operator>> (bool &b)
CArchive & operator>> (char &c)
CArchive & operator>> (std::string &str)
CArchive & operator>> (std::wstring &wstr)
CArchive & operator>> (KODI::TIME::SystemTime &time)
CArchive & operator>> (IArchivable &obj)
CArchive & operator>> (CVariant &variant)
CArchive & operator>> (std::vector< std::string > &strArray)
CArchive & operator>> (std::vector< int > &iArray)
bool IsLoading () const
bool IsStoring () const
void Close ()
Protected Member Functions
CArchive & streamout (const void *dataPtr, size_t size)
CArchive & streamin (void *dataPtr, size_t size)
Protected Attributes
XFILE::CFile * m_pFile
int m_iMode
std::unique_ptr< uint8_t[]> m_pBuffer
uint8_t * m_BufferPos
size_t m_BufferRemain
Private Member Functions
void FlushBuffer ()
CArchive & streamout_bufferwrap (const uint8_t *ptr, size_t size)
void FillBuffer ()
CArchive & streamin_bufferwrap (uint8_t *ptr, size_t size)
Member Enumeration Documentation
Mode
enum CArchive::Mode
Enumerator
load
store
Constructor & Destructor Documentation
CArchive()
CArchive::CArchive (XFILE::CFile * pFile, int mode)
References CARCHIVE_BUFFER_MAX, load, m_BufferPos, m_BufferRemain, m_iMode, m_pBuffer, and m_pFile.
~CArchive()
CArchive::~CArchive ()
References FlushBuffer().
Member Function Documentation
Close()
void CArchive::Close ()
References FlushBuffer().
Referenced by CFileItemList::Load(), MUSIC_INFO::CMusicInfoLoader::LoadCache(), CFileItemList::Save(), MUSIC_INFO::CMusicInfoLoader::SaveCache(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
FillBuffer()
void CArchive::FillBuffer () private
References CARCHIVE_BUFFER_MAX, load, m_BufferPos, m_BufferRemain, m_iMode, m_pBuffer, m_pFile, and XFILE::CFile::Read().
Referenced by streamin_bufferwrap().
FlushBuffer()
void CArchive::FlushBuffer () private
References CARCHIVE_BUFFER_MAX, CLog::Log(), LOGERROR, m_BufferPos, m_BufferRemain, m_iMode, m_pBuffer, m_pFile, store, and XFILE::CFile::Write().
Referenced by Close(), streamout_bufferwrap(), and ~CArchive().
IsLoading()
bool CArchive::IsLoading () const
References load, and m_iMode.
Referenced by TEST_F(), TEST_F(), and TEST_F().
IsStoring()
bool CArchive::IsStoring () const
References m_iMode, and store.
Referenced by CGUIListItem::Archive(), CVideoInfoTag::CAssetInfo::Archive(), CFileItem::Archive(), CFileItemList::Archive(), KODI::GAME::CGameInfoTag::Archive(), MUSIC_INFO::CMusicInfoTag::Archive(), CPictureInfoTag::Archive(), PVR::CPVRRadioRDSInfoTag::Archive(), EmbeddedArtInfo::Archive(), CSpeed::Archive(), CStreamDetailVideo::Archive(), CStreamDetailAudio::Archive(), CStreamDetailSubtitle::Archive(), CStreamDetails::Archive(), CTemperature::Archive(), CVideoInfoTag::Archive(), CDateTime::Archive(), TEST_F(), TEST_F(), and TEST_F().
operator<<() [1/19]
CArchive & CArchive::operator<< (bool b)
References streamout().
operator<<() [2/19]
CArchive & CArchive::operator<< (char c)
References streamout().
operator<<() [3/19]
CArchive & CArchive::operator<< (const CVariant & variant)
References CVariant::VariantTypeArray, CVariant::VariantTypeBoolean, CVariant::VariantTypeConstNull, CVariant::VariantTypeDouble, CVariant::VariantTypeInteger, CVariant::VariantTypeNull, CVariant::VariantTypeObject, CVariant::VariantTypeString, CVariant::VariantTypeUnsignedInteger, and CVariant::VariantTypeWideString.
operator<<() [4/19]
CArchive & CArchive::operator<< (const KODI::TIME::SystemTime & time)
References streamout().
operator<<() [5/19]
CArchive & CArchive::operator<< (const std::string & str)
References MAX_STRING_SIZE, and streamout().
operator<<() [6/19]
CArchive & CArchive::operator<< (const std::vector< int > & iArray)
operator<<() [7/19]
CArchive & CArchive::operator<< (const std::vector< std::string > & strArray)
operator<<() [8/19]
CArchive & CArchive::operator<< (const std::wstring & wstr)
References MAX_STRING_SIZE, and streamout().
operator<<() [9/19]
CArchive & CArchive::operator<< (double d)
References streamout().
operator<<() [10/19]
CArchive & CArchive::operator<< (float f)
References f, and streamout().
operator<<() [11/19]
CArchive & CArchive::operator<< (IArchivable & obj)
References IArchivable::Archive().
operator<<() [12/19]
CArchive & CArchive::operator<< (int i)
References streamout().
operator<<() [13/19]
CArchive & CArchive::operator<< (long int l)
References streamout().
operator<<() [14/19]
CArchive & CArchive::operator<< (long long int ll)
References streamout().
operator<<() [15/19]
CArchive & CArchive::operator<< (short int s)
References streamout().
operator<<() [16/19]
CArchive & CArchive::operator<< (unsigned int ui)
References streamout().
operator<<() [17/19]
CArchive & CArchive::operator<< (unsigned long int ul)
References streamout().
operator<<() [18/19]
CArchive & CArchive::operator<< (unsigned long long int ull)
References streamout().
operator<<() [19/19]
CArchive & CArchive::operator<< (unsigned short int us)
References streamout().
operator>>() [1/19]
CArchive & CArchive::operator>> (bool & b) inline
References streamin().
operator>>() [2/19]
CArchive & CArchive::operator>> (char & c) inline
References streamin().
operator>>() [3/19]
CArchive & CArchive::operator>> (CVariant & variant)
References int64_t(), name, value, CVariant::VariantTypeArray, CVariant::VariantTypeBoolean, CVariant::VariantTypeConstNull, CVariant::VariantTypeDouble, CVariant::VariantTypeInteger, CVariant::VariantTypeNull, CVariant::VariantTypeObject, CVariant::VariantTypeString, CVariant::VariantTypeUnsignedInteger, and CVariant::VariantTypeWideString.
operator>>() [4/19]
CArchive & CArchive::operator>> (double & d) inline
References streamin().
operator>>() [5/19]
CArchive & CArchive::operator>> (float & f) inline
References f, and streamin().
operator>>() [6/19]
CArchive & CArchive::operator>> (IArchivable & obj)
References IArchivable::Archive().
operator>>() [7/19]
CArchive & CArchive::operator>> (int & i) inline
References streamin().
operator>>() [8/19]
CArchive & CArchive::operator>> (KODI::TIME::SystemTime & time)
References streamin().
operator>>() [9/19]
CArchive & CArchive::operator>> (long int & l) inline
References streamin().
operator>>() [10/19]
CArchive & CArchive::operator>> (long long int & ll) inline
References streamin().
operator>>() [11/19]
CArchive & CArchive::operator>> (short int & s) inline
References streamin().
operator>>() [12/19]
CArchive & CArchive::operator>> (std::string & str)
References MAX_STRING_SIZE, and streamin().
operator>>() [13/19]
CArchive & CArchive::operator>> (std::vector< int > & iArray)
References index().
operator>>() [14/19]
CArchive & CArchive::operator>> (std::vector< std::string > & strArray)
References index().
operator>>() [15/19]
CArchive & CArchive::operator>> (std::wstring & wstr)
References MAX_STRING_SIZE, and streamin().
operator>>() [16/19]
CArchive & CArchive::operator>> (unsigned int & ui) inline
References streamin().
operator>>() [17/19]
CArchive & CArchive::operator>> (unsigned long int & ul) inline
References streamin().
operator>>() [18/19]
CArchive & CArchive::operator>> (unsigned long long int & ull) inline
References streamin().
operator>>() [19/19]
CArchive & CArchive::operator>> (unsigned short int & us) inline
References streamin().
streamin()
CArchive & CArchive::streamin (void * dataPtr, size_t size) inline protected
References m_BufferPos, m_BufferRemain, and streamin_bufferwrap().
Referenced by operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), and operator>>().
streamin_bufferwrap()
CArchive & CArchive::streamin_bufferwrap (uint8_t * ptr, size_t size) private
References CARCHIVE_BUFFER_MAX, FillBuffer(), CLog::Log(), LOGERROR, m_BufferPos, and m_BufferRemain.
Referenced by streamin().
streamout()
CArchive & CArchive::streamout (const void * dataPtr, size_t size) inline protected
References m_BufferPos, m_BufferRemain, and streamout_bufferwrap().
Referenced by operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), and operator<<().
streamout_bufferwrap()
CArchive & CArchive::streamout_bufferwrap (const uint8_t * ptr, size_t size) private
References FlushBuffer(), m_BufferPos, and m_BufferRemain.
Referenced by streamout().
Member Data Documentation
m_BufferPos
uint8_t* CArchive::m_BufferPos protected
Referenced by CArchive(), FillBuffer(), FlushBuffer(), streamin(), streamin_bufferwrap(), streamout(), and streamout_bufferwrap().
m_BufferRemain
size_t CArchive::m_BufferRemain protected
Referenced by CArchive(), FillBuffer(), FlushBuffer(), streamin(), streamin_bufferwrap(), streamout(), and streamout_bufferwrap().
m_iMode
int CArchive::m_iMode protected
Referenced by CArchive(), FillBuffer(), FlushBuffer(), IsLoading(), and IsStoring().
m_pBuffer
std::unique_ptr<uint8_t[]> CArchive::m_pBuffer protected
Referenced by CArchive(), FillBuffer(), and FlushBuffer().
m_pFile
XFILE::CFile* CArchive::m_pFile protected
Referenced by CArchive(), FillBuffer(), and FlushBuffer().
The documentation for this class was generated from the following files:
Archive.h
Archive.cpp