Kodi Documentation: jni::CJNIMainActivity Class Reference
jni::CJNIMainActivity Class Reference abstract
#include <JNIMainActivity.h>
Public Member Functions
CJNIMainActivity (const ANativeActivity *nativeActivity)
~CJNIMainActivity () override
CJNIRect getDisplayRect ()
Static Public Member Functions
static CJNIMainActivity * GetAppInstance ()
static void RegisterNatives (JNIEnv *env)
static void _onNewIntent (JNIEnv *env, jobject context, jobject intent)
static void _onActivityResult (JNIEnv *env, jobject context, jint requestCode, jint resultCode, jobject resultData)
static void _onVolumeChanged (JNIEnv *env, jobject context, jint volume)
static void _doFrame (JNIEnv *env, jobject context, jlong frameTimeNanos)
static void _onInputDeviceAdded (JNIEnv *env, jobject context, jint deviceId)
static void _onInputDeviceChanged (JNIEnv *env, jobject context, jint deviceId)
static void _onInputDeviceRemoved (JNIEnv *env, jobject context, jint deviceId)
static void _onVisibleBehindCanceled (JNIEnv *env, jobject context)
static void _callNative (JNIEnv *env, jobject context, jlong funcAddr, jlong variantAddr)
static void runNativeOnUiThread (void(*callback)(void *), void *variant)
static void registerMediaButtonEventReceiver ()
static void unregisterMediaButtonEventReceiver ()
Protected Member Functions
virtual void onNewIntent (CJNIIntent intent)=0
virtual void onActivityResult (int requestCode, int resultCode, CJNIIntent resultData)=0
virtual void onVolumeChanged (int volume)=0
virtual void doFrame (int64_t frameTimeNanos)=0
void onVisibleBehindCanceled () override=0
virtual void onDisplayAdded (int displayId)=0
virtual void onDisplayChanged (int displayId)=0
virtual void onDisplayRemoved (int displayId)=0
Static Private Attributes
static CJNIMainActivity * m_appInstance
Constructor & Destructor Documentation
CJNIMainActivity()
CJNIMainActivity::CJNIMainActivity (const ANativeActivity * nativeActivity) explicit
References m_appInstance.
~CJNIMainActivity()
CJNIMainActivity::~CJNIMainActivity () override
References m_appInstance.
Member Function Documentation
_callNative()
void CJNIMainActivity::_callNative (JNIEnv * env, jobject context, jlong funcAddr, jlong variantAddr) static
References void().
Referenced by RegisterNatives().
_doFrame()
void CJNIMainActivity::_doFrame (JNIEnv * env, jobject context, jlong frameTimeNanos) static
References doFrame(), m_appInstance, and void().
Referenced by RegisterNatives().
_onActivityResult()
void CJNIMainActivity::_onActivityResult (JNIEnv * env, jobject context, jint requestCode, jint resultCode, jobject resultData) static
References m_appInstance, onActivityResult(), and void().
Referenced by RegisterNatives().
_onInputDeviceAdded()
void CJNIMainActivity::_onInputDeviceAdded (JNIEnv * env, jobject context, jint deviceId) static
References m_appInstance.
Referenced by RegisterNatives().
_onInputDeviceChanged()
void CJNIMainActivity::_onInputDeviceChanged (JNIEnv * env, jobject context, jint deviceId) static
References m_appInstance.
Referenced by RegisterNatives().
_onInputDeviceRemoved()
void CJNIMainActivity::_onInputDeviceRemoved (JNIEnv * env, jobject context, jint deviceId) static
References m_appInstance.
Referenced by RegisterNatives().
_onNewIntent()
void CJNIMainActivity::_onNewIntent (JNIEnv * env, jobject context, jobject intent) static
References m_appInstance, onNewIntent(), and void().
Referenced by RegisterNatives().
_onVisibleBehindCanceled()
void CJNIMainActivity::_onVisibleBehindCanceled (JNIEnv * env, jobject context) static
References m_appInstance, onVisibleBehindCanceled(), and void().
Referenced by RegisterNatives().
_onVolumeChanged()
void CJNIMainActivity::_onVolumeChanged (JNIEnv * env, jobject context, jint volume) static
References m_appInstance, onVolumeChanged(), and void().
Referenced by RegisterNatives().
doFrame()
virtual void jni::CJNIMainActivity::doFrame (int64_t frameTimeNanos) protected pure virtual
Implemented in CXBMCApp.
Referenced by _doFrame().
GetAppInstance()
static CJNIMainActivity * jni::CJNIMainActivity::GetAppInstance () inline static
References m_appInstance.
getDisplayRect()
CJNIRect CJNIMainActivity::getDisplayRect ()
Referenced by CXBMCApp::MapRenderToDroid().
onActivityResult()
virtual void jni::CJNIMainActivity::onActivityResult (int requestCode, int resultCode, CJNIIntent resultData) protected pure virtual
Implemented in CXBMCApp.
Referenced by _onActivityResult().
onDisplayAdded()
virtual void jni::CJNIMainActivity::onDisplayAdded (int displayId) protected pure virtual
Implemented in CXBMCApp.
onDisplayChanged()
virtual void jni::CJNIMainActivity::onDisplayChanged (int displayId) protected pure virtual
Implemented in CXBMCApp.
onDisplayRemoved()
virtual void jni::CJNIMainActivity::onDisplayRemoved (int displayId) protected pure virtual
Implemented in CXBMCApp.
onNewIntent()
virtual void jni::CJNIMainActivity::onNewIntent (CJNIIntent intent) protected pure virtual
Implemented in CXBMCApp.
Referenced by _onNewIntent().
onVisibleBehindCanceled()
void jni::CJNIMainActivity::onVisibleBehindCanceled () override protected pure virtual
Implemented in CXBMCApp.
Referenced by _onVisibleBehindCanceled().
onVolumeChanged()
virtual void jni::CJNIMainActivity::onVolumeChanged (int volume) protected pure virtual
Implemented in CXBMCApp.
Referenced by _onVolumeChanged().
registerMediaButtonEventReceiver()
void CJNIMainActivity::registerMediaButtonEventReceiver () static
RegisterNatives()
void CJNIMainActivity::RegisterNatives (JNIEnv * env) static
References _callNative(), _doFrame(), _onActivityResult(), _onInputDeviceAdded(), _onInputDeviceChanged(), _onInputDeviceRemoved(), _onNewIntent(), _onVisibleBehindCanceled(), _onVolumeChanged(), and CCompileInfo::GetClass().
Referenced by JNI_OnLoad().
runNativeOnUiThread()
void CJNIMainActivity::runNativeOnUiThread (void(*)(void *) callback, void * variant) static
Referenced by CXBMCApp::KeepScreenOn(), CXBMCApp::onStart(), CXBMCApp::SetDisplayMode(), CXBMCApp::SetVideoLayoutBackgroundColor(), and CSpeechRecognitionAndroid::StartSpeechRecognition().
unregisterMediaButtonEventReceiver()
void CJNIMainActivity::unregisterMediaButtonEventReceiver () static
Member Data Documentation
m_appInstance
CJNIMainActivity * CJNIMainActivity::m_appInstance static private
Referenced by _doFrame(), _onActivityResult(), _onInputDeviceAdded(), _onInputDeviceChanged(), _onInputDeviceRemoved(), _onNewIntent(), _onVisibleBehindCanceled(), _onVolumeChanged(), CJNIMainActivity(), GetAppInstance(), and ~CJNIMainActivity().
The documentation for this class was generated from the following files:
JNIMainActivity.h
JNIMainActivity.cpp