Kodi Documentation: CInputCodingTableBasePY Class Reference
CInputCodingTableBasePY Class Reference
#include <InputCodingTableBasePY.h>
Public Member Functions
CInputCodingTableBasePY ()
~CInputCodingTableBasePY () override=default
bool GetWordListPage (const std::string &strCode, bool isFirstPage) override
std::vector< std::wstring > GetResponse (int) override
Public Member Functions inherited from IInputCodingTable
virtual int GetType ()
virtual ~IInputCodingTable ()=default
virtual void Initialize ()
Called for the active keyboard layout when it's loaded, stick any initialization here.
virtual void Deinitialize ()
Called for the active keyboard layout when it's unloaded, stick any cleanup here.
virtual bool IsInitialized () const
Can be overridden if initialization is expensive to avoid calling initialize more than needed.
const std::string & GetCodeChars () const
virtual void SetTextPrev (const std::string &strTextPrev)
virtual std::string ConvertString (const std::string &strCode)
Private Attributes
std::vector< std::wstring > m_words
Additional Inherited Members
Public Types inherited from IInputCodingTable
enum { TYPE_WORD_LIST , TYPE_CONVERT_STRING }
Protected Attributes inherited from IInputCodingTable
std::string m_codechars
Constructor & Destructor Documentation
CInputCodingTableBasePY()
CInputCodingTableBasePY::CInputCodingTableBasePY ()
References IInputCodingTable::m_codechars.
~CInputCodingTableBasePY()
CInputCodingTableBasePY::~CInputCodingTableBasePY () override default
Member Function Documentation
GetResponse()
std::vector< std::wstring > CInputCodingTableBasePY::GetResponse (int) override virtual
Implements IInputCodingTable.
References m_words.
GetWordListPage()
bool CInputCodingTableBasePY::GetWordListPage (const std::string & strCode, bool isFirstPage) override virtual
Implements IInputCodingTable.
References codemap, CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_CODINGTABLE_LOOKUP_COMPLETED, m_words, and CGUIMessage::SetStringParam().
Member Data Documentation
m_words
std::vector<std::wstring> CInputCodingTableBasePY::m_words private
Referenced by GetResponse(), and GetWordListPage().
The documentation for this class was generated from the following files:
InputCodingTableBasePY.h
InputCodingTableBasePY.cpp