Kodi Documentation: XFILE::CWin32SMBFile Class Reference
XFILE::CWin32SMBFile Class Reference
#include <Win32SMBFile.h>
Public Member Functions
CWin32SMBFile ()
virtual ~CWin32SMBFile ()
virtual bool Open (const CURL &url)
virtual bool OpenForWrite (const CURL &url, bool bOverWrite=false)
virtual bool Delete (const CURL &url)
virtual bool Rename (const CURL &urlCurrentName, const CURL &urlNewName)
virtual bool SetHidden (const CURL &url, bool hidden)
virtual bool Exists (const CURL &url)
virtual int Stat (const CURL &url, struct __stat64 *statData)
Public Member Functions inherited from XFILE::CWin32File
CWin32File ()
virtual ~CWin32File ()
virtual void Close ()
virtual ssize_t Read (void *lpBuf, size_t uiBufSize)
virtual ssize_t Write (const void *lpBuf, size_t uiBufSize)
virtual int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET)
virtual int Truncate (int64_t toSize)
virtual int64_t GetPosition ()
virtual int64_t GetLength ()
virtual void Flush ()
virtual int Stat (struct __stat64 *statData)
virtual int GetChunkSize ()
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual double GetDownloadSpeed ()
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Static Private Member Functions
static bool ConnectAndAuthenticate (const CURL &url)
Additional Inherited Members
Protected Member Functions inherited from XFILE::CWin32File
CWin32File (bool asSmbFile)
Protected Attributes inherited from XFILE::CWin32File
HANDLE m_hFile
int64_t m_filePos
bool m_allowWrite
std::wstring m_filepathnameW
const bool m_smbFile
unsigned long m_lastSMBFileErr
Constructor & Destructor Documentation
CWin32SMBFile()
CWin32SMBFile::CWin32SMBFile ()
~CWin32SMBFile()
CWin32SMBFile::~CWin32SMBFile () virtual
Member Function Documentation
ConnectAndAuthenticate()
bool CWin32SMBFile::ConnectAndAuthenticate (const CURL & url) static private
References XFILE::CWin32SMBDirectory::ConnectAndAuthenticate().
Referenced by Delete(), Exists(), Open(), OpenForWrite(), Rename(), SetHidden(), and Stat().
Delete()
bool CWin32SMBFile::Delete (const CURL & url) virtual
Reimplemented from XFILE::CWin32File.
References ConnectAndAuthenticate(), XFILE::CWin32File::Delete(), CURL::IsProtocol(), XFILE::CWin32File::m_lastSMBFileErr, and worthTryToConnect().
Exists()
bool CWin32SMBFile::Exists (const CURL & url) virtual
Reimplemented from XFILE::CWin32File.
References ConnectAndAuthenticate(), CWIN32Util::ConvertPathToWin32Form(), GetLastError(), CURL::IsProtocol(), and worthTryToConnect().
Open()
bool CWin32SMBFile::Open (const CURL & url) virtual
Reimplemented from XFILE::CWin32File.
References ConnectAndAuthenticate(), CURL::IsProtocol(), XFILE::CWin32File::m_lastSMBFileErr, XFILE::CWin32File::Open(), and worthTryToConnect().
OpenForWrite()
bool CWin32SMBFile::OpenForWrite (const CURL & url, bool bOverWrite = false) virtual
Reimplemented from XFILE::CWin32File.
References ConnectAndAuthenticate(), CURL::IsProtocol(), XFILE::CWin32File::m_lastSMBFileErr, XFILE::CWin32File::OpenForWrite(), and worthTryToConnect().
Rename()
bool CWin32SMBFile::Rename (const CURL & urlCurrentName, const CURL & urlNewName) virtual
Reimplemented from XFILE::CWin32File.
References ConnectAndAuthenticate(), CURL::IsProtocol(), XFILE::CWin32File::m_lastSMBFileErr, XFILE::CWin32File::Rename(), and worthTryToConnect().
SetHidden()
bool CWin32SMBFile::SetHidden (const CURL & url, bool hidden) virtual
Reimplemented from XFILE::CWin32File.
References ConnectAndAuthenticate(), CWIN32Util::ConvertPathToWin32Form(), GetLastError(), CURL::IsProtocol(), and worthTryToConnect().
Stat()
int CWin32SMBFile::Stat (const CURL & url, struct __stat64 * buffer) virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Reimplemented from XFILE::CWin32File.
References ConnectAndAuthenticate(), CURL::IsProtocol(), XFILE::CWin32File::m_lastSMBFileErr, XFILE::CWin32File::Stat(), and worthTryToConnect().
The documentation for this class was generated from the following files:
Win32SMBFile.h
Win32SMBFile.cpp