Kodi Documentation: CEGLContextUtils Class Reference
CEGLContextUtils Class Reference final
#include <EGLUtils.h>
Public Member Functions
CEGLContextUtils ()=default
CEGLContextUtils (EGLenum platform, std::string const &platformExtension)
~CEGLContextUtils ()
bool CreateDisplay (EGLNativeDisplayType nativeDisplay)
bool CreatePlatformDisplay (void *nativeDisplay, EGLNativeDisplayType nativeDisplayLegacy)
void SurfaceAttrib (EGLint attribute, EGLint value)
bool CreateSurface (EGLNativeWindowType nativeWindow, EGLint HDRcolorSpace=EGL_NONE)
bool CreatePlatformSurface (void *nativeWindow, EGLNativeWindowType nativeWindowLegacy)
bool InitializeDisplay (EGLint renderingApi)
bool ChooseConfig (EGLint renderableType, EGLint visualId=0, bool hdr=false)
bool CreateContext (CEGLAttributesVec contextAttribs)
bool BindContext ()
void Destroy ()
void DestroySurface ()
void DestroyContext ()
bool SetVSync (bool enable)
bool TrySwapBuffers ()
bool IsPlatformSupported () const
EGLint GetConfigAttrib (EGLint attribute) const
EGLDisplay GetEGLDisplay () const
EGLSurface GetEGLSurface () const
EGLContext GetEGLContext () const
EGLConfig GetEGLConfig () const
bool BindTextureUploadContext ()
bool UnbindTextureUploadContext ()
bool HasContext ()
Private Member Functions
void SurfaceAttrib ()
Private Attributes
EGLenum m_platform {EGL_NONE}
bool m_platformSupported {false}
EGLDisplay m_eglDisplay {EGL_NO_DISPLAY}
EGLSurface m_eglSurface {EGL_NO_SURFACE}
EGLContext m_eglContext {EGL_NO_CONTEXT}
EGLConfig m_eglConfig {}
EGLConfig m_eglHDRConfig {}
EGLContext m_eglUploadContext {EGL_NO_CONTEXT}
CCriticalSection m_textureUploadLock
Constructor & Destructor Documentation
CEGLContextUtils() [1/2]
CEGLContextUtils::CEGLContextUtils () default
CEGLContextUtils() [2/2]
CEGLContextUtils::CEGLContextUtils (EGLenum platform, std::string const & platformExtension)
Parameters
platform platform as constant from an extension building on EGL_EXT_platform_base
References EglErrorCallback(), CEGLUtils::HasClientExtension(), and m_platformSupported.
~CEGLContextUtils()
CEGLContextUtils::~CEGLContextUtils ()
References Destroy().
Member Function Documentation
BindContext()
bool CEGLContextUtils::BindContext ()
References CLog::Log(), LOGERROR, m_eglContext, m_eglDisplay, and m_eglSurface.
Referenced by CWinSystemAndroidGLESContext::CreateNewWindow(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::CreateNewWindow(), and CWinSystemAndroidGLESContext::SetHDR().
BindTextureUploadContext()
bool CEGLContextUtils::BindTextureUploadContext ()
References LOGERROR, m_eglDisplay, m_eglUploadContext, and m_textureUploadLock.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::BindTextureUploadContext(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::BindTextureUploadContext().
ChooseConfig()
bool CEGLContextUtils::ChooseConfig (EGLint renderableType, EGLint visualId = 0, bool hdr = false)
References CEGLAttributesVec::Add(), Destroy(), DIRTYREGION_SOLVER_COST_REDUCTION, DIRTYREGION_SOLVER_UNION, CEGLAttributesVec::Get(), CServiceBroker::GetSettingsComponent(), CLog::Log(), CEGLUtils::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_eglConfig, m_eglDisplay, m_eglHDRConfig, and value.
Referenced by CWinSystemAndroidGLESContext::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::InitWindowSystemEGL().
CreateContext()
bool CEGLContextUtils::CreateContext (CEGLAttributesVec contextAttribs)
References CEGLAttributesVec::Add(), CEGLAttributesVec::Get(), CServiceBroker::GetSettingsComponent(), CEGLUtils::HasExtension(), CLog::Log(), CEGLUtils::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_eglConfig, m_eglContext, m_eglDisplay, m_eglUploadContext, and value.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::CreateContext(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::CreateContext(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::CreateContext(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::CreateContext(), and CWinSystemAndroidGLESContext::InitWindowSystem().
CreateDisplay()
bool CEGLContextUtils::CreateDisplay (EGLNativeDisplayType nativeDisplay)
References CEGLUtils::Log(), LOGERROR, and m_eglDisplay.
Referenced by CreatePlatformDisplay(), and CWinSystemAndroidGLESContext::InitWindowSystem().
CreatePlatformDisplay()
bool CEGLContextUtils::CreatePlatformDisplay (void * nativeDisplay, EGLNativeDisplayType nativeDisplayLegacy)
Create EGLDisplay with EGL_EXT_platform_base
Falls back to CreateDisplay (with nativeDisplayLegacy) on failure. The native displays to use with the platform-based and the legacy approach may be defined to have different types and/or semantics, so this function takes both as separate parameters.
Parameters
nativeDisplay native display to use with eglGetPlatformDisplayEXT
nativeDisplayLegacy native display to use with eglGetDisplay
References CreateDisplay(), IsPlatformSupported(), CEGLUtils::Log(), LOGERROR, m_eglDisplay, and m_platform.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::InitWindowSystemEGL().
CreatePlatformSurface()
bool CEGLContextUtils::CreatePlatformSurface (void * nativeWindow, EGLNativeWindowType nativeWindowLegacy)
References CreateSurface(), IsPlatformSupported(), CEGLUtils::Log(), LOGERROR, m_eglConfig, m_eglDisplay, m_eglSurface, and SurfaceAttrib().
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::CreateNewWindow().
CreateSurface()
bool CEGLContextUtils::CreateSurface (EGLNativeWindowType nativeWindow, EGLint HDRcolorSpace = EGL_NONE)
References CEGLAttributesVec::Add(), CEGLAttributesVec::Get(), CEGLUtils::Log(), LOGERROR, m_eglConfig, m_eglDisplay, m_eglHDRConfig, m_eglSurface, and SurfaceAttrib().
Referenced by CreatePlatformSurface(), and CWinSystemAndroidGLESContext::CreateSurface().
Destroy()
void CEGLContextUtils::Destroy ()
References DestroyContext(), DestroySurface(), and m_eglDisplay.
Referenced by ChooseConfig(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::DestroyWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::DestroyWindowSystem(), InitializeDisplay(), and ~CEGLContextUtils().
DestroyContext()
void CEGLContextUtils::DestroyContext ()
References m_eglContext, m_eglDisplay, and m_eglUploadContext.
Referenced by Destroy().
DestroySurface()
void CEGLContextUtils::DestroySurface ()
References m_eglDisplay, and m_eglSurface.
Referenced by CWinSystemAndroidGLESContext::CreateNewWindow(), Destroy(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::DestroyWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::DestroyWindow(), and CWinSystemAndroidGLESContext::SetHDR().
GetConfigAttrib()
EGLint CEGLContextUtils::GetConfigAttrib (EGLint attribute) const
References CEGLUtils::Log(), LOGERROR, m_eglConfig, m_eglDisplay, and value.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow().
GetEGLConfig()
EGLConfig CEGLContextUtils::GetEGLConfig () const inline
References m_eglConfig.
Referenced by CWinSystemAndroidGLESContext::GetEGLConfig(), and KODI::WINDOWING::LINUX::CWinSystemEGL::GetEGLConfig().
GetEGLContext()
EGLContext CEGLContextUtils::GetEGLContext () const inline
References m_eglContext.
Referenced by CWinSystemAndroidGLESContext::GetEGLContext(), and KODI::WINDOWING::LINUX::CWinSystemEGL::GetEGLContext().
GetEGLDisplay()
EGLDisplay CEGLContextUtils::GetEGLDisplay () const inline
References m_eglDisplay.
Referenced by CWinSystemAndroidGLESContext::GetEGLDisplay(), KODI::WINDOWING::LINUX::CWinSystemEGL::GetEGLDisplay(), CWinSystemAndroidGLESContext::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::InitWindowSystem(), and KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL().
GetEGLSurface()
EGLSurface CEGLContextUtils::GetEGLSurface () const inline
References m_eglSurface.
Referenced by CWinSystemAndroidGLESContext::GetEGLSurface(), and KODI::WINDOWING::LINUX::CWinSystemEGL::GetEGLSurface().
HasContext()
bool CEGLContextUtils::HasContext ()
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::HasContext(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::HasContext().
InitializeDisplay()
bool CEGLContextUtils::InitializeDisplay (EGLint renderingApi)
References Destroy(), CLog::Log(), CEGLUtils::Log(), LOGERROR, LOGINFO, m_eglDisplay, and value.
Referenced by CWinSystemAndroidGLESContext::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::InitWindowSystemEGL().
IsPlatformSupported()
bool CEGLContextUtils::IsPlatformSupported () const
References m_platformSupported.
Referenced by CreatePlatformDisplay(), and CreatePlatformSurface().
SetVSync()
bool CEGLContextUtils::SetVSync (bool enable)
References m_eglDisplay.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::CreateNewWindow(), and CWinSystemAndroidGLESContext::SetVSyncImpl().
SurfaceAttrib() [1/2]
void CEGLContextUtils::SurfaceAttrib () private
References DIRTYREGION_SOLVER_COST_REDUCTION, DIRTYREGION_SOLVER_UNION, CServiceBroker::GetSettingsComponent(), CEGLUtils::Log(), LOGERROR, m_eglDisplay, and m_eglSurface.
Referenced by CreatePlatformSurface(), and CreateSurface().
SurfaceAttrib() [2/2]
void CEGLContextUtils::SurfaceAttrib (EGLint attribute, EGLint value)
References CEGLUtils::Log(), LOGERROR, m_eglDisplay, m_eglSurface, and value.
Referenced by CWinSystemAndroidGLESContext::CreateSurface().
TrySwapBuffers()
bool CEGLContextUtils::TrySwapBuffers ()
References m_eglDisplay, and m_eglSurface.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::PresentFrame(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender(), CWinSystemAndroidGLESContext::PresentRenderImpl(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::SetFullScreen(), and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::SetFullScreen().
UnbindTextureUploadContext()
bool CEGLContextUtils::UnbindTextureUploadContext ()
References LOGERROR, m_eglDisplay, m_eglUploadContext, and m_textureUploadLock.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::UnbindTextureUploadContext(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::UnbindTextureUploadContext().
Member Data Documentation
m_eglConfig
EGLConfig CEGLContextUtils::m_eglConfig {} private
Referenced by ChooseConfig(), CreateContext(), CreatePlatformSurface(), CreateSurface(), GetConfigAttrib(), and GetEGLConfig().
m_eglContext
EGLContext CEGLContextUtils::m_eglContext {EGL_NO_CONTEXT} private
Referenced by BindContext(), CreateContext(), DestroyContext(), and GetEGLContext().
m_eglDisplay
EGLDisplay CEGLContextUtils::m_eglDisplay {EGL_NO_DISPLAY} private
Referenced by BindContext(), BindTextureUploadContext(), ChooseConfig(), CreateContext(), CreateDisplay(), CreatePlatformDisplay(), CreatePlatformSurface(), CreateSurface(), Destroy(), DestroyContext(), DestroySurface(), GetConfigAttrib(), GetEGLDisplay(), InitializeDisplay(), SetVSync(), SurfaceAttrib(), SurfaceAttrib(), TrySwapBuffers(), and UnbindTextureUploadContext().
m_eglHDRConfig
EGLConfig CEGLContextUtils::m_eglHDRConfig {} private
Referenced by ChooseConfig(), and CreateSurface().
m_eglSurface
EGLSurface CEGLContextUtils::m_eglSurface {EGL_NO_SURFACE} private
Referenced by BindContext(), CreatePlatformSurface(), CreateSurface(), DestroySurface(), GetEGLSurface(), SurfaceAttrib(), SurfaceAttrib(), and TrySwapBuffers().
m_eglUploadContext
EGLContext CEGLContextUtils::m_eglUploadContext {EGL_NO_CONTEXT} private
Referenced by BindTextureUploadContext(), CreateContext(), DestroyContext(), and UnbindTextureUploadContext().
m_platform
EGLenum CEGLContextUtils::m_platform {EGL_NONE} private
Referenced by CreatePlatformDisplay().
m_platformSupported
bool CEGLContextUtils::m_platformSupported {false} private
Referenced by CEGLContextUtils(), and IsPlatformSupported().
m_textureUploadLock
CCriticalSection CEGLContextUtils::m_textureUploadLock mutable private
Referenced by BindTextureUploadContext(), and UnbindTextureUploadContext().
The documentation for this class was generated from the following files:
EGLUtils.h
EGLUtils.cpp