Kodi Documentation: CVideoBufferManager Class Reference
CVideoBufferManager Class Reference
#include <VideoBuffer.h>
Public Member Functions
CVideoBufferManager ()
void RegisterPool (const std::shared_ptr< IVideoBufferPool > &pool)
void RegisterPoolFactory (const std::string &id, CreatePoolFunc createFunc)
void ReleasePools ()
void ReleasePool (IVideoBufferPool *pool)
CVideoBuffer * Get (AVPixelFormat format, int size, IVideoBufferPool **pPool)
void ReadyForDisposal (IVideoBufferPool *pool)
Protected Attributes
CCriticalSection m_critSection
std::list< std::shared_ptr< IVideoBufferPool > > m_pools
std::list< std::shared_ptr< IVideoBufferPool > > m_discardedPools
std::map< std::string, CreatePoolFunc > m_poolFactories
Private Member Functions
CVideoBufferManager (const CVideoBufferManager &)=delete
CVideoBufferManager & operator= (const CVideoBufferManager &)=delete
Constructor & Destructor Documentation
CVideoBufferManager() [1/2]
CVideoBufferManager::CVideoBufferManager ()
References CVideoBufferPoolSysMem::CreatePool(), m_critSection, and RegisterPoolFactory().
CVideoBufferManager() [2/2]
CVideoBufferManager::CVideoBufferManager (const CVideoBufferManager &) private delete
Member Function Documentation
Get()
CVideoBuffer * CVideoBufferManager::Get (AVPixelFormat format, int size, IVideoBufferPool ** pPool)
References IVideoBufferPool::Get(), m_critSection, m_poolFactories, and m_pools.
Referenced by CDVDVideoCodecDRMPRIME::GetBuffer(), CAddonVideoCodec::GetFrameBuffer(), and CDVDVideoPPFFmpeg::Process().
operator=()
CVideoBufferManager & CVideoBufferManager::operator= (const CVideoBufferManager &) private delete
ReadyForDisposal()
void CVideoBufferManager::ReadyForDisposal (IVideoBufferPool * pool)
References m_critSection, m_discardedPools, and IVideoBufferPool::Released().
Referenced by ReleasePool(), and ReleasePools().
RegisterPool()
void CVideoBufferManager::RegisterPool (const std::shared_ptr< IVideoBufferPool > & pool)
References m_critSection, and m_pools.
Referenced by VIDEOPLAYER::CProcessInfoGBM::CProcessInfoGBM(), VIDEOPLAYER::CProcessInfoWayland::CProcessInfoWayland(), and CVideoBufferPoolDMA::Released().
RegisterPoolFactory()
void CVideoBufferManager::RegisterPoolFactory (const std::string & id, CreatePoolFunc createFunc)
References id, m_critSection, and m_poolFactories.
Referenced by CVideoBufferManager().
ReleasePool()
void CVideoBufferManager::ReleasePool (IVideoBufferPool * pool)
References IVideoBufferPool::Discard(), m_critSection, m_discardedPools, m_pools, and ReadyForDisposal().
ReleasePools()
void CVideoBufferManager::ReleasePools ()
References m_critSection, m_discardedPools, m_pools, and ReadyForDisposal().
Referenced by CVideoPlayerVideo::OpenStream().
Member Data Documentation
m_critSection
CCriticalSection CVideoBufferManager::m_critSection protected
Referenced by CVideoBufferManager(), Get(), ReadyForDisposal(), RegisterPool(), RegisterPoolFactory(), ReleasePool(), and ReleasePools().
m_discardedPools
std::list<std::shared_ptr<IVideoBufferPool> > CVideoBufferManager::m_discardedPools protected
Referenced by ReadyForDisposal(), ReleasePool(), and ReleasePools().
m_poolFactories
std::map<std::string, CreatePoolFunc> CVideoBufferManager::m_poolFactories protected
Referenced by Get(), and RegisterPoolFactory().
m_pools
std::list<std::shared_ptr<IVideoBufferPool> > CVideoBufferManager::m_pools protected
Referenced by Get(), RegisterPool(), ReleasePool(), and ReleasePools().
The documentation for this class was generated from the following files:
VideoBuffer.h
VideoBuffer.cpp