Kodi Documentation: CConvertMatrix Class Reference
CConvertMatrix Class Reference
Helper class used for YUV to RGB conversions. This class can take into account different source/destination primaries and various other parameters.
#include <ConversionMatrix.h>
Public Member Functions
CConvertMatrix ()=default
~CConvertMatrix ()=default
CConvertMatrix & SetSourceColorSpace (AVColorSpace colorSpace)
Set the source color space.
CConvertMatrix & SetSourceBitDepth (int bits)
Set the source bit depth.
CConvertMatrix & SetSourceLimitedRange (bool limited)
Set the source limited range boolean.
CConvertMatrix & SetSourceTextureBitDepth (int textureBits)
Set the source texture bit depth. This is need to normalize values when using > 8 bit texture formats in OpenGL/DirectX. For example GL_R16 is a 16 bit texture which needs to normalize the 10 bit format.
CConvertMatrix & SetSourceColorPrimaries (AVColorPrimaries src)
Set the source color primaries.
CConvertMatrix & SetDestinationColorPrimaries (AVColorPrimaries dst)
Set the destination color primaries.
CConvertMatrix & SetDestinationContrast (float contrast)
Set the destination contrast.
CConvertMatrix & SetDestinationBlack (float black)
Set the destination black level.
CConvertMatrix & SetDestinationLimitedRange (bool limited)
Set the destination limited range boolean.
Matrix4 GetYuvMat ()
Get the YUV Matrix for the YUV to RGB conversion.
Matrix3 GetPrimMat ()
Get the Primaries Matrix for the primaries conversion.
float GetGammaSrc ()
Get the gamma source value. Used for color primary conversion..
float GetGammaDst ()
Get the gamma destination value. Used for color primary conversion.
Static Public Member Functions
static Matrix3x1 GetRGBYuvCoefs (AVColorSpace colspace)
Get the YUV coeffecients used for tonemapping.
Private Member Functions
const CGlMatrix & GenMat ()
const CMatrix< 3 > & GenPrimMat ()
Private Attributes
std::unique_ptr< CGlMatrix > m_mat
std::unique_ptr< CMatrix< 3 > > m_matPrim
AVColorSpace m_colSpace = AVCOL_SPC_BT709
AVColorPrimaries m_colPrimariesSrc = AVCOL_PRI_BT709
float m_gammaSrc = 2.2f
bool m_limitedSrc = true
AVColorPrimaries m_colPrimariesDst = AVCOL_PRI_BT709
float m_gammaDst = 2.2f
bool m_limitedDst = false
int m_srcBits = 8
int m_srcTextureBits = 8
float m_contrast = 1.0
float m_black = 0.0
Detailed Description
Helper class used for YUV to RGB conversions. This class can take into account different source/destination primaries and various other parameters.
Constructor & Destructor Documentation
CConvertMatrix()
CConvertMatrix::CConvertMatrix () default
~CConvertMatrix()
CConvertMatrix::~CConvertMatrix () default
Member Function Documentation
GenMat()
const CGlMatrix & CConvertMatrix::GenMat () private
References m_colSpace, m_limitedSrc, m_mat, m_srcBits, and m_srcTextureBits.
Referenced by GetYuvMat().
GenPrimMat()
const CMatrix< 3 > & CConvertMatrix::GenPrimMat () private
References m_colPrimariesDst, m_colPrimariesSrc, m_gammaDst, m_gammaSrc, and m_matPrim.
Referenced by GetPrimMat().
GetGammaDst()
float CConvertMatrix::GetGammaDst ()
Get the gamma destination value. Used for color primary conversion.
References m_gammaDst.
Referenced by Shaders::GL::BaseYUV2RGBGLSLShader::OnEnabled(), Shaders::GLES::BaseYUV2RGBGLSLShader::OnEnabled(), and CYUV2RGBShader::SetShaderParameters().
GetGammaSrc()
float CConvertMatrix::GetGammaSrc ()
Get the gamma source value. Used for color primary conversion..
References m_gammaSrc.
Referenced by Shaders::GL::BaseYUV2RGBGLSLShader::OnEnabled(), Shaders::GLES::BaseYUV2RGBGLSLShader::OnEnabled(), and CYUV2RGBShader::SetShaderParameters().
GetPrimMat()
Matrix3 CConvertMatrix::GetPrimMat ()
Get the Primaries Matrix for the primaries conversion.
References GenPrimMat(), m_colPrimariesDst, and m_colPrimariesSrc.
Referenced by Shaders::GL::BaseYUV2RGBGLSLShader::OnEnabled(), Shaders::GLES::BaseYUV2RGBGLSLShader::OnEnabled(), CYUV2RGBShader::SetShaderParameters(), and TEST().
GetRGBYuvCoefs()
Matrix3x1 CConvertMatrix::GetRGBYuvCoefs (AVColorSpace colspace) static
Get the YUV coeffecients used for tonemapping.
References anonymous_namespace{ConversionMatrix.cpp}::ConvYCbCr::Kb, and anonymous_namespace{ConversionMatrix.cpp}::ConvYCbCr::Kr.
Referenced by COutputShader::ApplyEffectParameters(), Shaders::GL::BaseYUV2RGBGLSLShader::OnEnabled(), and Shaders::GLES::BaseYUV2RGBGLSLShader::OnEnabled().
GetYuvMat()
Matrix4 CConvertMatrix::GetYuvMat ()
Get the YUV Matrix for the YUV to RGB conversion.
References GenMat(), m_black, m_contrast, and m_limitedDst.
Referenced by Shaders::GL::BaseYUV2RGBGLSLShader::OnEnabled(), Shaders::GLES::BaseYUV2RGBGLSLShader::OnEnabled(), CYUV2RGBShader::SetShaderParameters(), and TEST().
SetDestinationBlack()
CConvertMatrix & CConvertMatrix::SetDestinationBlack (float black)
Set the destination black level.
References m_black.
Referenced by Shaders::GL::BaseYUV2RGBGLSLShader::OnEnabled(), Shaders::GLES::BaseYUV2RGBGLSLShader::OnEnabled(), CYUV2RGBShader::SetParams(), and TEST().
SetDestinationColorPrimaries()
CConvertMatrix & CConvertMatrix::SetDestinationColorPrimaries (AVColorPrimaries dst)
Set the destination color primaries.
References m_colPrimariesDst, and m_matPrim.
Referenced by Shaders::GL::BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader(), Shaders::GLES::BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader(), CYUV2RGBShader::Create(), and TEST().
SetDestinationContrast()
CConvertMatrix & CConvertMatrix::SetDestinationContrast (float contrast)
Set the destination contrast.
References m_contrast.
Referenced by Shaders::GL::BaseYUV2RGBGLSLShader::OnEnabled(), Shaders::GLES::BaseYUV2RGBGLSLShader::OnEnabled(), CYUV2RGBShader::SetParams(), and TEST().
SetDestinationLimitedRange()
CConvertMatrix & CConvertMatrix::SetDestinationLimitedRange (bool limited)
Set the destination limited range boolean.
References m_limitedDst.
Referenced by Shaders::GL::BaseYUV2RGBGLSLShader::OnEnabled(), Shaders::GLES::BaseYUV2RGBGLSLShader::OnEnabled(), CYUV2RGBShader::SetParams(), and TEST().
SetSourceBitDepth()
CConvertMatrix & CConvertMatrix::SetSourceBitDepth (int bits)
Set the source bit depth.
References m_mat, and m_srcBits.
Referenced by CYUV2RGBShader::SetColParams(), Shaders::GL::BaseYUV2RGBGLSLShader::SetColParams(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetColParams(), and TEST().
SetSourceColorPrimaries()
CConvertMatrix & CConvertMatrix::SetSourceColorPrimaries (AVColorPrimaries src)
Set the source color primaries.
References m_colPrimariesSrc, and m_matPrim.
Referenced by Shaders::GL::BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader(), Shaders::GLES::BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader(), CYUV2RGBShader::Create(), and TEST().
SetSourceColorSpace()
CConvertMatrix & CConvertMatrix::SetSourceColorSpace (AVColorSpace colorSpace)
Set the source color space.
References m_colSpace, and m_mat.
Referenced by CYUV2RGBShader::SetColParams(), Shaders::GL::BaseYUV2RGBGLSLShader::SetColParams(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetColParams(), and TEST().
SetSourceLimitedRange()
CConvertMatrix & CConvertMatrix::SetSourceLimitedRange (bool limited)
Set the source limited range boolean.
References m_limitedSrc, and m_mat.
Referenced by CYUV2RGBShader::SetColParams(), Shaders::GL::BaseYUV2RGBGLSLShader::SetColParams(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetColParams(), and TEST().
SetSourceTextureBitDepth()
CConvertMatrix & CConvertMatrix::SetSourceTextureBitDepth (int textureBits)
Set the source texture bit depth. This is need to normalize values when using > 8 bit texture formats in OpenGL/DirectX. For example GL_R16 is a 16 bit texture which needs to normalize the 10 bit format.
References m_mat, and m_srcTextureBits.
Referenced by CYUV2RGBShader::SetColParams(), Shaders::GL::BaseYUV2RGBGLSLShader::SetColParams(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetColParams(), and TEST().
Member Data Documentation
m_black
float CConvertMatrix::m_black = 0.0 private
Referenced by GetYuvMat(), and SetDestinationBlack().
m_colPrimariesDst
AVColorPrimaries CConvertMatrix::m_colPrimariesDst = AVCOL_PRI_BT709 private
Referenced by GenPrimMat(), GetPrimMat(), and SetDestinationColorPrimaries().
m_colPrimariesSrc
AVColorPrimaries CConvertMatrix::m_colPrimariesSrc = AVCOL_PRI_BT709 private
Referenced by GenPrimMat(), GetPrimMat(), and SetSourceColorPrimaries().
m_colSpace
AVColorSpace CConvertMatrix::m_colSpace = AVCOL_SPC_BT709 private
Referenced by GenMat(), and SetSourceColorSpace().
m_contrast
float CConvertMatrix::m_contrast = 1.0 private
Referenced by GetYuvMat(), and SetDestinationContrast().
m_gammaDst
float CConvertMatrix::m_gammaDst = 2.2f private
Referenced by GenPrimMat(), and GetGammaDst().
m_gammaSrc
float CConvertMatrix::m_gammaSrc = 2.2f private
Referenced by GenPrimMat(), and GetGammaSrc().
m_limitedDst
bool CConvertMatrix::m_limitedDst = false private
Referenced by GetYuvMat(), and SetDestinationLimitedRange().
m_limitedSrc
bool CConvertMatrix::m_limitedSrc = true private
Referenced by GenMat(), and SetSourceLimitedRange().
m_mat
std::unique_ptr<CGlMatrix> CConvertMatrix::m_mat private
Referenced by GenMat(), SetSourceBitDepth(), SetSourceColorSpace(), SetSourceLimitedRange(), and SetSourceTextureBitDepth().
m_matPrim
std::unique_ptr<CMatrix<3> > CConvertMatrix::m_matPrim private
Referenced by GenPrimMat(), SetDestinationColorPrimaries(), and SetSourceColorPrimaries().
m_srcBits
int CConvertMatrix::m_srcBits = 8 private
Referenced by GenMat(), and SetSourceBitDepth().
m_srcTextureBits
int CConvertMatrix::m_srcTextureBits = 8 private
Referenced by GenMat(), and SetSourceTextureBitDepth().
The documentation for this class was generated from the following files:
ConversionMatrix.h
ConversionMatrix.cpp