Kodi Documentation: KODI::GAME::CGUIDialogIgnoreInput Class Reference
KODI::GAME::CGUIDialogIgnoreInput Class Reference
Games
#include <GUIDialogIgnoreInput.h>
Public Member Functions
CGUIDialogIgnoreInput ()=default
~CGUIDialogIgnoreInput () override=default
bool AcceptsPrimitive (JOYSTICK::PRIMITIVE_TYPE type) const override
Return true if the button mapper accepts primitives of the given type.
Public Member Functions inherited from KODI::GAME::CGUIDialogButtonCapture
CGUIDialogButtonCapture ()
~CGUIDialogButtonCapture () override=default
std::string ControllerID () const override
The add-on ID of the game controller associated with this button mapper.
bool NeedsCooldown () const override
Return true if the button mapper wants a cooldown between button mapping commands.
bool MapPrimitive (JOYSTICK::IButtonMap *buttonMap, KEYMAP::IKeymap *keymap, const JOYSTICK::CDriverPrimitive &primitive) override
Handle button/hat press or axis threshold.
void OnEventFrame (const JOYSTICK::IButtonMap *buttonMap, bool bMotion) override
Called once per event frame to notify the implementation of motion status.
void OnLateAxis (const JOYSTICK::IButtonMap *buttonMap, unsigned int axisIndex) override
Called when an axis has been detected after mapping began.
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
void Show ()
Show the dialog.
Public Member Functions inherited from KODI::JOYSTICK::IButtonMapper
IButtonMapper ()=default
virtual ~IButtonMapper ()=default
void SetButtonMapCallback (const std::string &deviceLocation, IButtonMapCallback *callback)
void ResetButtonMapCallbacks (void)
std::map< std::string, IButtonMapCallback * > & ButtonMapCallbacks (void)
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Protected Member Functions
std::string GetDialogText () override
std::string GetDialogHeader () override
bool MapPrimitiveInternal (JOYSTICK::IButtonMap *buttonMap, KEYMAP::IKeymap *keymap, const JOYSTICK::CDriverPrimitive &primitive) override
void OnClose (bool bAccepted) override
Protected Member Functions inherited from KODI::GAME::CGUIDialogButtonCapture
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Member Functions
bool AddPrimitive (const JOYSTICK::CDriverPrimitive &primitive)
Private Attributes
std::string m_location
std::vector< JOYSTICK::CDriverPrimitive > m_capturedPrimitives
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Attributes inherited from KODI::GAME::CGUIDialogButtonCapture
CEvent m_captureEvent
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CGUIDialogIgnoreInput()
KODI::GAME::CGUIDialogIgnoreInput::CGUIDialogIgnoreInput () default
~CGUIDialogIgnoreInput()
KODI::GAME::CGUIDialogIgnoreInput::~CGUIDialogIgnoreInput () override default
Member Function Documentation
AcceptsPrimitive()
bool CGUIDialogIgnoreInput::AcceptsPrimitive (JOYSTICK::PRIMITIVE_TYPE type) const override virtual
Return true if the button mapper accepts primitives of the given type.
Parameters
type The primitive type
Returns
True if the button mapper can map the primitive type, false otherwise
Implements KODI::JOYSTICK::IButtonMapper.
References KODI::JOYSTICK::BUTTON, and KODI::JOYSTICK::SEMIAXIS.
AddPrimitive()
bool CGUIDialogIgnoreInput::AddPrimitive (const JOYSTICK::CDriverPrimitive & primitive) private
References KODI::JOYSTICK::BUTTON, KODI::JOYSTICK::CDriverPrimitive::Index(), m_capturedPrimitives, KODI::JOYSTICK::SEMIAXIS, and KODI::JOYSTICK::CDriverPrimitive::Type().
Referenced by MapPrimitiveInternal().
GetDialogHeader()
std::string CGUIDialogIgnoreInput::GetDialogHeader () override protected virtual
Implements KODI::GAME::CGUIDialogButtonCapture.
References g_localizeStrings, and CLocalizeStrings::Get().
GetDialogText()
std::string CGUIDialogIgnoreInput::GetDialogText () override protected virtual
Implements KODI::GAME::CGUIDialogButtonCapture.
References g_localizeStrings, CLocalizeStrings::Get(), and m_capturedPrimitives.
MapPrimitiveInternal()
bool CGUIDialogIgnoreInput::MapPrimitiveInternal (JOYSTICK::IButtonMap * buttonMap, KEYMAP::IKeymap * keymap, const JOYSTICK::CDriverPrimitive & primitive) override protected virtual
Implements KODI::GAME::CGUIDialogButtonCapture.
References AddPrimitive(), KODI::JOYSTICK::IButtonMap::ControllerID(), KODI::JOYSTICK::IButtonMap::Location(), CLog::Log(), LOGDEBUG, m_capturedPrimitives, KODI::GAME::CGUIDialogButtonCapture::m_captureEvent, m_location, CEvent::Set(), and KODI::JOYSTICK::IButtonMap::SetIgnoredPrimitives().
OnClose()
void CGUIDialogIgnoreInput::OnClose (bool bAccepted) override protected virtual
Implements KODI::GAME::CGUIDialogButtonCapture.
References KODI::JOYSTICK::IButtonMapper::ButtonMapCallbacks(), and m_location.
Member Data Documentation
m_capturedPrimitives
std::vector<JOYSTICK::CDriverPrimitive> KODI::GAME::CGUIDialogIgnoreInput::m_capturedPrimitives private
Referenced by AddPrimitive(), GetDialogText(), and MapPrimitiveInternal().
m_location
std::string KODI::GAME::CGUIDialogIgnoreInput::m_location private
Referenced by MapPrimitiveInternal(), and OnClose().
The documentation for this class was generated from the following files:
GUIDialogIgnoreInput.h
GUIDialogIgnoreInput.cpp