Kodi Documentation: anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction Class Reference
anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction Class Reference abstract
Public Member Functions
bool Execute (const CFileItem &item)
Protected Member Functions
AsyncRecordingAction ()=default
Private Member Functions
void Run () override
virtual bool DoRun (const std::shared_ptr< CFileItem > &item)=0
Private Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Private Attributes
std::shared_ptr< CFileItem > m_item
bool m_bSuccess = false
Constructor & Destructor Documentation
AsyncRecordingAction()
anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction::AsyncRecordingAction () protected default
Member Function Documentation
DoRun()
virtual bool anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction::DoRun (const std::shared_ptr< CFileItem > & item) private pure virtual
Implemented in anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRenameRecording, anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording, anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncEmptyRecordingsTrash, anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncUndeleteRecording, anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncSetRecordingPlayCount, and anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncSetRecordingLifetime.
Referenced by Run().
Execute()
bool anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction::Execute (const CFileItem & item)
References CGUIDialogBusy::Wait().
Run()
void anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction::Run () override private virtual
Implements IRunnable.
References DoRun(), CServiceBroker::GetPVRManager(), and PVR::CPVRManager::TriggerRecordingsUpdate().
Member Data Documentation
m_bSuccess
bool anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction::m_bSuccess = false private
m_item
std::shared_ptr<CFileItem> anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction::m_item private
The documentation for this class was generated from the following file:
PVRGUIActionsRecordings.cpp