Kodi Documentation: ADDON::Interface_GUIControlAddonRendering Struct Reference
ADDON::Interface_GUIControlAddonRendering Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Rendering.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void set_callbacks (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, KODI_GUI_CLIENT_HANDLE clienthandle, bool(*createCB)(KODI_GUI_CLIENT_HANDLE, int, int, int, int, ADDON_HARDWARE_CONTEXT), void(*renderCB)(KODI_GUI_CLIENT_HANDLE), void(*stopCB)(KODI_GUI_CLIENT_HANDLE), bool(*dirtyCB)(KODI_GUI_CLIENT_HANDLE))
callback functions from add-on to kodi
static void destroy (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold general gui functions and initialize also all other gui related types not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/controls/Rendering.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIControlAddonRendering::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_rendering, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
destroy()
void ADDON::Interface_GUIControlAddonRendering::destroy (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
Init()
void ADDON::Interface_GUIControlAddonRendering::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_rendering, destroy(), AddonToKodiFuncTable_kodi_gui_control_rendering::destroy, AddonToKodiFuncTable_Addon::kodi_gui, set_callbacks(), AddonToKodiFuncTable_kodi_gui_control_rendering::set_callbacks, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
set_callbacks()
void ADDON::Interface_GUIControlAddonRendering::set_callbacks (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, KODI_GUI_CLIENT_HANDLE clienthandle, bool(*)(KODI_GUI_CLIENT_HANDLE, int, int, int, int, ADDON_HARDWARE_CONTEXT) createCB, void(*)(KODI_GUI_CLIENT_HANDLE) renderCB, void(*)(KODI_GUI_CLIENT_HANDLE) stopCB, bool(*)(KODI_GUI_CLIENT_HANDLE) dirtyCB) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CGUIAddonRenderingControl::CBCreate, ADDON::CGUIAddonRenderingControl::CBDirty, ADDON::CGUIAddonRenderingControl::CBRender, ADDON::CGUIAddonRenderingControl::CBStop, ADDON::CAddon::ID(), CGUIRenderingControl::InitCallback(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::CGUIAddonRenderingControl::m_addon, ADDON::CGUIAddonRenderingControl::m_clientHandle, ADDON::CGUIAddonRenderingControl::m_control, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/controls/rendering.h
Rendering.cpp