Kodi Documentation: IAEWASAPIDevice Struct Reference
IAEWASAPIDevice Struct Reference abstract
#include <AESinkFactoryWin.h>
Public Member Functions
virtual int Release ()=0
virtual HRESULT Activate (IAudioClient **ppAudioClient)=0
virtual bool IsUSBDevice ()=0
Public Attributes
std::string deviceId
Member Function Documentation
Activate()
virtual HRESULT IAEWASAPIDevice::Activate (IAudioClient ** ppAudioClient) pure virtual
Implemented in AEWASAPIDeviceWin10, and AEWASAPIDeviceWin32.
Referenced by CAESinkWASAPI::EnumerateDevicesEx(), CAESinkWASAPI::Initialize(), and CAESinkWASAPI::InitializeExclusive().
IsUSBDevice()
virtual bool IAEWASAPIDevice::IsUSBDevice () pure virtual
Implemented in AEWASAPIDeviceWin10, and AEWASAPIDeviceWin32.
Referenced by CAESinkWASAPI::IsUSBDevice().
Release()
virtual int IAEWASAPIDevice::Release () pure virtual
Implemented in AEWASAPIDeviceWin10, and AEWASAPIDeviceWin32.
Member Data Documentation
deviceId
std::string IAEWASAPIDevice::deviceId
Referenced by AEWASAPIDeviceWin10::Activate(), and CAESinkFactoryWin::ActivateWASAPIDevice().
The documentation for this struct was generated from the following file:
AESinkFactoryWin.h