Kodi Documentation: NPT_XbmcFile Class Reference
NPT_XbmcFile Class Reference
Public Member Functions
NPT_XbmcFile (NPT_File &delegator)
~NPT_XbmcFile () override
NPT_Result Open (OpenMode mode) override
NPT_Result Close () override
NPT_Result GetInputStream (NPT_InputStreamReference &stream) override
NPT_Result GetOutputStream (NPT_OutputStreamReference &stream) override
Private Attributes
NPT_File & m_Delegator
OpenMode m_Mode = 0
NPT_XbmcFileReference m_FileReference
Constructor & Destructor Documentation
NPT_XbmcFile()
NPT_XbmcFile::NPT_XbmcFile (NPT_File & delegator) explicit
~NPT_XbmcFile()
NPT_XbmcFile::~NPT_XbmcFile () override
References Close().
Member Function Documentation
Close()
NPT_Result NPT_XbmcFile::Close () override
References m_FileReference, and m_Mode.
Referenced by ~NPT_XbmcFile().
GetInputStream()
NPT_Result NPT_XbmcFile::GetInputStream (NPT_InputStreamReference & stream) override
References m_FileReference, and m_Mode.
GetOutputStream()
NPT_Result NPT_XbmcFile::GetOutputStream (NPT_OutputStreamReference & stream) override
References m_FileReference, and m_Mode.
Open()
NPT_Result NPT_XbmcFile::Open (OpenMode mode) override
References CPasswordManager::AuthenticateURL(), XFILE::CFileFactory::CreateLoader(), CPasswordManager::GetInstance(), CURL::GetUserName(), m_Delegator, m_FileReference, m_Mode, name, and URIUtils::SubstitutePath().
Member Data Documentation
m_Delegator
NPT_File& NPT_XbmcFile::m_Delegator private
Referenced by Open().
m_FileReference
NPT_XbmcFileReference NPT_XbmcFile::m_FileReference private
Referenced by Close(), GetInputStream(), GetOutputStream(), and Open().
m_Mode
OpenMode NPT_XbmcFile::m_Mode = 0 private
Referenced by Close(), GetInputStream(), GetOutputStream(), and Open().
The documentation for this class was generated from the following file:
NptXbmcFile.cpp