Kodi Documentation: KODI::GAME::CAgentInput Class Reference
KODI::GAME::CAgentInput Class Reference
Games
Class to manage game-playing agents for a running game client.
#include <AgentInput.h>
Public Member Functions
CAgentInput (PERIPHERALS::CPeripherals &peripheralManager, CInputManager &inputManager)
virtual ~CAgentInput ()
void Start (GameClientPtr gameClient)
void Stop ()
void Refresh ()
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
bool OnKeyPress (const CKey &key) override
A key has been pressed.
void OnKeyRelease (const CKey &key) override
A key has been released.
bool OnPosition (int x, int y) override
Handle mouse position updates.
bool OnButtonPress (MOUSE::BUTTON_ID button) override
A mouse button has been pressed.
void OnButtonRelease (MOUSE::BUTTON_ID button) override
A mouse button has been released.
std::vector< std::shared_ptr< const CAgentController > > GetControllers () const
std::string GetPortAddress (JOYSTICK::IInputProvider *inputProvider) const
std::string GetKeyboardAddress (KEYBOARD::IKeyboardInputProvider *inputProvider) const
std::string GetMouseAddress (MOUSE::IMouseInputProvider *inputProvider) const
std::vector< std::string > GetGameInputPorts () const
float GetGamePortActivation (const std::string &address) const
float GetPeripheralActivation (const std::string &peripheralLocation) const
Public Member Functions inherited from Observable
Observable ()=default
virtual ~Observable ()=default
Observable & operator= (const Observable &observable)
virtual void RegisterObserver (Observer *obs)
Register an observer.
virtual void UnregisterObserver (Observer *obs)
Unregister an observer.
virtual void NotifyObservers (const ObservableMessage message=ObservableMessageNone)
Send a message to all observers when m_bObservableChanged is true.
virtual void SetChanged (bool bSetTo=true)
Mark an observable changed.
virtual bool IsObserving (const Observer &obs) const
Check whether this observable is being observed by an observer.
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Private Types
using PortAddress = std::string
using JoystickMap = std::map< PortAddress, std::shared_ptr< CGameClientJoystick > >
using PortMap = std::map< JOYSTICK::IInputProvider *, std::shared_ptr< CGameClientJoystick > >
using PeripheralLocation = std::string
using CurrentPortMap = std::map< PortAddress, PeripheralLocation >
using CurrentPeripheralMap = std::map< PeripheralLocation, PortAddress >
using ControllerAddress = std::string
using PeripheralMap = std::map< ControllerAddress, PERIPHERALS::PeripheralPtr >
Private Member Functions
void ProcessJoysticks (PERIPHERALS::EventLockHandlePtr &inputHandlingLock)
void ProcessKeyboard ()
void ProcessMouse ()
void ProcessAgentControllers (const PERIPHERALS::PeripheralVector &joysticks, PERIPHERALS::EventLockHandlePtr &inputHandlingLock)
void UpdateExpiredJoysticks (const PERIPHERALS::PeripheralVector &joysticks, PERIPHERALS::EventLockHandlePtr &inputHandlingLock)
void UpdateConnectedJoysticks (const PERIPHERALS::PeripheralVector &joysticks, const PortMap &newPortMap, PERIPHERALS::EventLockHandlePtr &inputHandlingLock, std::set< PERIPHERALS::PeripheralPtr > &disconnectedJoysticks)
Private Member Functions inherited from KODI::KEYBOARD::IKeyboardDriverHandler
virtual ~IKeyboardDriverHandler ()=default
Private Member Functions inherited from KODI::MOUSE::IMouseDriverHandler
virtual ~IMouseDriverHandler (void)=default
Static Private Member Functions
static PortMap MapJoysticks (const PERIPHERALS::PeripheralVector &peripheralJoysticks, const JoystickMap &gameClientjoysticks, CurrentPortMap &currentPorts, CurrentPeripheralMap &currentPeripherals, int playerLimit)
static void MapJoystick (PERIPHERALS::PeripheralPtr peripheralJoystick, std::shared_ptr< CGameClientJoystick > gameClientJoystick, PortMap &result)
static void LogPeripheralMap (const PeripheralMap &peripheralMap, const std::set< PERIPHERALS::PeripheralPtr > &disconnectedPeripherals)
Private Attributes
PERIPHERALS::CPeripherals & m_peripheralManager
CInputManager & m_inputManager
GameClientPtr m_gameClient
bool m_bHasKeyboard = false
bool m_bHasMouse = false
int m_initialMouseX {-1}
int m_initialMouseY {-1}
std::vector< std::shared_ptr< CAgentController > > m_controllers
std::mutex m_controllerMutex
PortMap m_portMap
Map of joystick input provider to joystick handler.
std::map< KEYBOARD::IKeyboardInputProvider *, PortAddress > m_keyboardPort
Map of keyboard input provider to keyboard port address.
std::map< MOUSE::IMouseInputProvider *, PortAddress > m_mousePort
Map of mouse input provider to mouse port address.
CurrentPortMap m_currentPorts
Map of the current ports to their peripheral.
CurrentPeripheralMap m_currentPeripherals
Map of the current peripherals to their port.
PeripheralMap m_peripheralMap
std::set< PERIPHERALS::PeripheralPtr > m_disconnectedPeripherals
Additional Inherited Members
Protected Member Functions inherited from Observable
void SendMessage (const ObservableMessage message)
Send a message to all observer when m_bObservableChanged is true.
Protected Attributes inherited from Observable
std::atomic< bool > m_bObservableChanged {false}
std::vector< Observer * > m_observers
CCriticalSection m_obsCritSection
Detailed Description
Class to manage game-playing agents for a running game client.
Currently, port mapping is controller-based and does not take into account the human belonging to the controller. In the future, humans and possibly bots will be managed here.
To map ports to controllers, a list of controllers is retrieved in ProcessJoysticks(). After expired controllers are removed, the port mapping occurs in the static function MapJoysticks(). The strategy is to simply sort controllers by heuristics and greedily assign to game ports.
Member Typedef Documentation
ControllerAddress
using KODI::GAME::CAgentInput::ControllerAddress = std::string private
CurrentPeripheralMap
using KODI::GAME::CAgentInput::CurrentPeripheralMap = std::map<PeripheralLocation, PortAddress> private
CurrentPortMap
using KODI::GAME::CAgentInput::CurrentPortMap = std::map<PortAddress, PeripheralLocation> private
JoystickMap
using KODI::GAME::CAgentInput::JoystickMap = std::map<PortAddress, std::shared_ptr<CGameClientJoystick> > private
PeripheralLocation
using KODI::GAME::CAgentInput::PeripheralLocation = std::string private
PeripheralMap
using KODI::GAME::CAgentInput::PeripheralMap = std::map<ControllerAddress, PERIPHERALS::PeripheralPtr> private
PortAddress
using KODI::GAME::CAgentInput::PortAddress = std::string private
Todo:
De-duplicate these types
PortMap
using KODI::GAME::CAgentInput::PortMap = std::map<JOYSTICK::IInputProvider*, std::shared_ptr<CGameClientJoystick> > private
Constructor & Destructor Documentation
CAgentInput()
CAgentInput::CAgentInput (PERIPHERALS::CPeripherals & peripheralManager, CInputManager & inputManager)
References m_inputManager, m_peripheralManager, CInputManager::RegisterKeyboardDriverHandler(), CInputManager::RegisterMouseDriverHandler(), and Observable::RegisterObserver().
~CAgentInput()
CAgentInput::~CAgentInput () virtual
References m_inputManager, m_peripheralManager, CInputManager::UnregisterKeyboardDriverHandler(), CInputManager::UnregisterMouseDriverHandler(), and Observable::UnregisterObserver().
Member Function Documentation
GetControllers()
std::vector< std::shared_ptr< const CAgentController > > CAgentInput::GetControllers () const
References m_controllerMutex, and m_controllers.
Referenced by KODI::GAME::CGUIAgentControllerList::OnControllerSelect(), KODI::GAME::CGUIAgentControllerList::Refresh(), and KODI::GAME::CGUIGameControllerList::UpdatePort().
GetGameInputPorts()
std::vector< std::string > CAgentInput::GetGameInputPorts () const
References KODI::GAME::CControllerHub::GetInputPorts(), and m_gameClient.
Referenced by KODI::GAME::CGUIGameControllerList::UpdateInfo().
GetGamePortActivation()
float CAgentInput::GetGamePortActivation (const std::string & address) const
References m_gameClient.
Referenced by KODI::GAME::CGUIGameController::DoProcess().
GetKeyboardAddress()
std::string CAgentInput::GetKeyboardAddress (KEYBOARD::IKeyboardInputProvider * inputProvider) const
References m_keyboardPort.
Referenced by KODI::GAME::CGUIGameControllerList::GetPortAddress().
GetMouseAddress()
std::string CAgentInput::GetMouseAddress (MOUSE::IMouseInputProvider * inputProvider) const
References m_mousePort.
Referenced by KODI::GAME::CGUIGameControllerList::GetPortAddress().
GetPeripheralActivation()
float CAgentInput::GetPeripheralActivation (const std::string & peripheralLocation) const
References m_controllerMutex, and m_controllers.
Referenced by KODI::GAME::CGUIGameController::DoProcess().
GetPortAddress()
std::string CAgentInput::GetPortAddress (JOYSTICK::IInputProvider * inputProvider) const
References m_portMap.
Referenced by KODI::GAME::CGUIGameControllerList::GetPortAddress().
LogPeripheralMap()
void CAgentInput::LogPeripheralMap (const PeripheralMap & peripheralMap, const std::set< PERIPHERALS::PeripheralPtr > & disconnectedPeripherals) static private
References CLog::Log(), and LOGDEBUG.
MapJoystick()
void CAgentInput::MapJoystick (PERIPHERALS::PeripheralPtr peripheralJoystick, std::shared_ptr< CGameClientJoystick > gameClientJoystick, PortMap & result) static private
Referenced by MapJoysticks().
MapJoysticks()
CAgentInput::PortMap CAgentInput::MapJoysticks (const PERIPHERALS::PeripheralVector & peripheralJoysticks, const JoystickMap & gameClientjoysticks, CurrentPortMap & currentPorts, CurrentPeripheralMap & currentPeripherals, int playerLimit) static private
References MapJoystick().
Notify()
void CAgentInput::Notify (const Observable & obs, const ObservableMessage msg) override virtual
Process a message from an observable.
Parameters
obs The observable that sends the message.
msg The message.
Implements Observer.
References ObservableMessageGamePortsChanged, ObservableMessagePeripheralsChanged, and Refresh().
OnButtonPress()
bool CAgentInput::OnButtonPress (MOUSE::BUTTON_ID button) override virtual
A mouse button has been pressed.
Parameters
button The index of the pressed button
Returns
True if the event was handled, otherwise false
Implements KODI::MOUSE::IMouseDriverHandler.
References m_bHasMouse, Observable::NotifyObservers(), ObservableMessageAgentControllersChanged, and ProcessMouse().
OnButtonRelease()
void KODI::GAME::CAgentInput::OnButtonRelease (MOUSE::BUTTON_ID button) inline override virtual
A mouse button has been released.
Parameters
button The index of the released button
Implements KODI::MOUSE::IMouseDriverHandler.
OnKeyPress()
bool CAgentInput::OnKeyPress (const CKey & key) override virtual
A key has been pressed.
Parameters
key The pressed key
Returns
True if the event was handled, false otherwise
Implements KODI::KEYBOARD::IKeyboardDriverHandler.
References m_bHasKeyboard, Observable::NotifyObservers(), ObservableMessageAgentControllersChanged, and ProcessKeyboard().
OnKeyRelease()
void KODI::GAME::CAgentInput::OnKeyRelease (const CKey & key) inline override virtual
A key has been released.
Parameters
key The released key
Implements KODI::KEYBOARD::IKeyboardDriverHandler.
OnPosition()
bool CAgentInput::OnPosition (int x, int y) override virtual
Handle mouse position updates.
Parameters
x The new x coordinate of the pointer
y The new y coordinate of the pointer
The mouse uses a left-handed (graphics) cartesian coordinate system. Positive X is right, positive Y is down.
Returns
True if the event was handled, false otherwise
Implements KODI::MOUSE::IMouseDriverHandler.
References m_bHasMouse, m_initialMouseX, m_initialMouseY, Observable::NotifyObservers(), ObservableMessageAgentControllersChanged, and ProcessMouse().
ProcessAgentControllers()
void CAgentInput::ProcessAgentControllers (const PERIPHERALS::PeripheralVector & joysticks, PERIPHERALS::EventLockHandlePtr & inputHandlingLock) private
References KODI::GAME::CAgentController::Deinitialize(), KODI::GAME::CAgentController::GetController(), if(), KODI::GAME::CAgentController::Initialize(), m_controllerMutex, m_controllers, m_gameClient, m_peripheralManager, PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERALS::PERIPHERAL_KEYBOARD, PERIPHERALS::PERIPHERAL_MOUSE, PERIPHERALS::CPeripherals::RegisterEventLock(), and Observable::SetChanged().
Referenced by ProcessKeyboard(), and ProcessMouse().
ProcessJoysticks()
void CAgentInput::ProcessJoysticks (PERIPHERALS::EventLockHandlePtr & inputHandlingLock) private
References PERIPHERALS::FEATURE_JOYSTICK, PERIPHERALS::CPeripherals::GetPeripheralsWithFeature(), and m_peripheralManager.
Referenced by Refresh().
ProcessKeyboard()
void CAgentInput::ProcessKeyboard () private
References PERIPHERALS::FEATURE_KEYBOARD, PERIPHERALS::CPeripherals::GetPeripheralsWithFeature(), KODI::GAME::CControllerHub::GetPorts(), m_gameClient, m_keyboardPort, m_peripheralManager, ProcessAgentControllers(), and Observable::SetChanged().
Referenced by OnKeyPress(), and Refresh().
ProcessMouse()
void CAgentInput::ProcessMouse () private
References PERIPHERALS::FEATURE_MOUSE, PERIPHERALS::CPeripherals::GetPeripheralsWithFeature(), KODI::GAME::CControllerHub::GetPorts(), m_gameClient, m_mousePort, m_peripheralManager, ProcessAgentControllers(), and Observable::SetChanged().
Referenced by OnButtonPress(), OnPosition(), and Refresh().
Refresh()
void CAgentInput::Refresh ()
References m_bHasKeyboard, m_bHasMouse, m_gameClient, Observable::NotifyObservers(), ObservableMessageAgentControllersChanged, ProcessJoysticks(), ProcessKeyboard(), and ProcessMouse().
Referenced by Notify(), and Start().
Start()
void CAgentInput::Start (GameClientPtr gameClient)
References m_gameClient, and Refresh().
Referenced by KODI::RETRO::CRenderContext::StartAgentInput().
Stop()
void CAgentInput::Stop ()
References m_disconnectedPeripherals, m_gameClient, m_keyboardPort, m_mousePort, m_peripheralManager, m_peripheralMap, m_portMap, Observable::NotifyObservers(), ObservableMessageAgentControllersChanged, PERIPHERALS::CPeripherals::RegisterEventLock(), and Observable::SetChanged().
Referenced by KODI::RETRO::CRenderContext::StopAgentInput().
UpdateConnectedJoysticks()
void CAgentInput::UpdateConnectedJoysticks (const PERIPHERALS::PeripheralVector & joysticks, const PortMap & newPortMap, PERIPHERALS::EventLockHandlePtr & inputHandlingLock, std::set< PERIPHERALS::PeripheralPtr > & disconnectedJoysticks) private
References m_peripheralManager, m_portMap, PERIPHERALS::CPeripherals::RegisterEventLock(), and Observable::SetChanged().
UpdateExpiredJoysticks()
void CAgentInput::UpdateExpiredJoysticks (const PERIPHERALS::PeripheralVector & joysticks, PERIPHERALS::EventLockHandlePtr & inputHandlingLock) private
References m_peripheralManager, m_portMap, PERIPHERALS::CPeripherals::RegisterEventLock(), and Observable::SetChanged().
Member Data Documentation
m_bHasKeyboard
bool KODI::GAME::CAgentInput::m_bHasKeyboard = false private
Referenced by OnKeyPress(), and Refresh().
m_bHasMouse
bool KODI::GAME::CAgentInput::m_bHasMouse = false private
Referenced by OnButtonPress(), OnPosition(), and Refresh().
m_controllerMutex
std::mutex KODI::GAME::CAgentInput::m_controllerMutex mutable private
Referenced by GetControllers(), GetPeripheralActivation(), and ProcessAgentControllers().
m_controllers
std::vector<std::shared_ptr<CAgentController> > KODI::GAME::CAgentInput::m_controllers private
Referenced by GetControllers(), GetPeripheralActivation(), and ProcessAgentControllers().
m_currentPeripherals
CurrentPeripheralMap KODI::GAME::CAgentInput::m_currentPeripherals private
Map of the current peripherals to their port.
This allows attempt to preserve player numbers.
m_currentPorts
CurrentPortMap KODI::GAME::CAgentInput::m_currentPorts private
Map of the current ports to their peripheral.
This allows attempt to preserve player numbers.
m_disconnectedPeripherals
std::set<PERIPHERALS::PeripheralPtr> KODI::GAME::CAgentInput::m_disconnectedPeripherals private
Collection of disconnected joysticks
Source peripherals are not exposed to the game.
Referenced by Stop().
m_gameClient
GameClientPtr KODI::GAME::CAgentInput::m_gameClient private
Referenced by GetGameInputPorts(), GetGamePortActivation(), ProcessAgentControllers(), ProcessKeyboard(), ProcessMouse(), Refresh(), Start(), and Stop().
m_initialMouseX
int KODI::GAME::CAgentInput::m_initialMouseX {-1} private
Referenced by OnPosition().
m_initialMouseY
int KODI::GAME::CAgentInput::m_initialMouseY {-1} private
Referenced by OnPosition().
m_inputManager
CInputManager& KODI::GAME::CAgentInput::m_inputManager private
Referenced by CAgentInput(), and ~CAgentInput().
m_keyboardPort
std::map<KEYBOARD::IKeyboardInputProvider*, PortAddress> KODI::GAME::CAgentInput::m_keyboardPort private
Map of keyboard input provider to keyboard port address.
Referenced by GetKeyboardAddress(), ProcessKeyboard(), and Stop().
m_mousePort
std::map<MOUSE::IMouseInputProvider*, PortAddress> KODI::GAME::CAgentInput::m_mousePort private
Map of mouse input provider to mouse port address.
Referenced by GetMouseAddress(), ProcessMouse(), and Stop().
m_peripheralManager
PERIPHERALS::CPeripherals& KODI::GAME::CAgentInput::m_peripheralManager private
Referenced by CAgentInput(), ProcessAgentControllers(), ProcessJoysticks(), ProcessKeyboard(), ProcessMouse(), Stop(), UpdateConnectedJoysticks(), UpdateExpiredJoysticks(), and ~CAgentInput().
m_peripheralMap
PeripheralMap KODI::GAME::CAgentInput::m_peripheralMap private
Map of controller address to source peripheral
Source peripherals are not exposed to the game.
Referenced by Stop().
m_portMap
PortMap KODI::GAME::CAgentInput::m_portMap private
Map of joystick input provider to joystick handler.
The input provider is a handle to agent input.
The joystick handler connects to joystick input of the game client.
This property remembers which joysticks are actually being controlled by agents.
Not exposed to the game.
Referenced by GetPortAddress(), Stop(), UpdateConnectedJoysticks(), and UpdateExpiredJoysticks().
The documentation for this class was generated from the following files:
AgentInput.h
AgentInput.cpp