Kodi Documentation: CNetworkMacOS Class Reference
CNetworkMacOS Class Reference
#include <NetworkMacOS.h>
Public Member Functions
CNetworkMacOS ()
~CNetworkMacOS () override=default
bool PingHost (unsigned long host, unsigned int timeout_ms=2000) override
std::vector< std::string > GetNameServers () override
Public Member Functions inherited from CNetworkPosix
virtual ~CNetworkPosix () override
std::vector< CNetworkInterface * > & GetInterfaceList () override
CNetworkInterface * GetFirstConnectedInterface () override
int GetSocket ()
Public Member Functions inherited from CNetworkBase
CNetworkBase ()
virtual ~CNetworkBase ()
CNetworkServices & GetServices ()
virtual bool GetHostName (std::string &hostname)
bool HasInterfaceForIP (unsigned long address)
bool IsAvailable (void)
bool IsConnected (void)
bool WakeOnLan (const char *mac)
bool PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms=2000, bool readability_check=false)
void NetworkMessage (EMESSAGE message, int param)
bool IsLocalHost (const std::string &hostname)
void WaitForNet ()
Private Member Functions
void GetMacAddress (const std::string &interfaceName, char macAddrRaw[6]) override
void queryInterfaceList () override
Additional Inherited Members
Public Types inherited from CNetworkBase
enum EMESSAGE { SERVICES_UP , SERVICES_DOWN }
Static Public Member Functions inherited from CNetworkBase
static std::unique_ptr< CNetworkBase > GetNetwork ()
static int ParseHex (char *str, unsigned char *addr)
static std::string GetIpStr (const sockaddr *sa)
IPv6/IPv4 compatible conversion of host IP address.
static std::string GetMaskByPrefixLength (uint8_t prefixLength)
convert prefix length of IPv4 address to IP mask representation
Public Attributes inherited from CNetworkBase
std::unique_ptr< CNetworkServices > m_services
Protected Member Functions inherited from CNetworkPosix
CNetworkPosix ()
Protected Attributes inherited from CNetworkPosix
std::vector< CNetworkInterface * > m_interfaces
Constructor & Destructor Documentation
CNetworkMacOS()
CNetworkMacOS::CNetworkMacOS ()
References queryInterfaceList().
~CNetworkMacOS()
CNetworkMacOS::~CNetworkMacOS () override default
Member Function Documentation
GetMacAddress()
void CNetworkMacOS::GetMacAddress (const std::string & interfaceName, char macAddrRaw[6]) override private virtual
Implements CNetworkPosix.
Referenced by queryInterfaceList().
GetNameServers()
std::vector< std::string > CNetworkMacOS::GetNameServers (void) override virtual
Implements CNetworkBase.
References CLog::Log(), and LOGWARNING.
PingHost()
bool CNetworkMacOS::PingHost (unsigned long host, unsigned int timeout_ms = 2000) override virtual
Implements CNetworkBase.
References CLog::Log(), and LOGERROR.
queryInterfaceList()
void CNetworkMacOS::queryInterfaceList () override private virtual
Implements CNetworkPosix.
References GetMacAddress(), and CNetworkPosix::m_interfaces.
Referenced by CNetworkMacOS().
The documentation for this class was generated from the following files:
NetworkMacOS.h
NetworkMacOS.mm