Kodi Documentation: WSDiscovery::CWSDiscoveryListenerUDP Class Reference
WSDiscovery::CWSDiscoveryListenerUDP Class Reference
#include <SMBWSDiscoveryListener.h>
Classes
struct Command
Public Member Functions
CWSDiscoveryListenerUDP ()
~CWSDiscoveryListenerUDP ()
void Start ()
void Stop ()
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Protected Member Functions
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Member Functions
bool DispatchCommand ()
void AddCommand (const std::string &message, const std::string &extraparameter="")
void ParseBuffer (const std::string &buffer)
bool buildSoapMessage (const std::string &action, std::string &msg, const std::string &extraparameter)
void Cleanup (bool aborted)
void UnicastGet (wsd_req_info &info)
template<std::size_t SIZE>
const std::string wsd_tag_find (const std::string &xml, const std::array< std::pair< std::string, std::string >, SIZE > &tag)
void PrintWSDInfo (const WSDiscovery::wsd_req_info &info)
bool equalsAddress (const WSDiscovery::wsd_req_info &lhs, const WSDiscovery::wsd_req_info &rhs) const
Private Attributes
int fd
std::vector< Command > m_commandbuffer
CCriticalSection crit_commandqueue
CCriticalSection crit_wsdqueue
std::vector< WSDiscovery::wsd_req_info > m_vecWSDInfo
const std::string wsd_instance_address
Static Private Attributes
static constexpr int retries {4}
static constexpr int UDPBUFFSIZE {65507}
static constexpr int wsdUDP {3702}
static constexpr char WDSIPv4MultiGroup [] {"239.255.255.250"}
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CWSDiscoveryListenerUDP()
WSDiscovery::CWSDiscoveryListenerUDP::CWSDiscoveryListenerUDP ()
~CWSDiscoveryListenerUDP()
WSDiscovery::CWSDiscoveryListenerUDP::~CWSDiscoveryListenerUDP ()
Member Function Documentation
AddCommand()
void WSDiscovery::CWSDiscoveryListenerUDP::AddCommand (const std::string & message, const std::string & extraparameter = "") private
References buildSoapMessage(), crit_commandqueue, CLog::Log(), LOGDEBUG, LOGWSDISCOVERY, m_commandbuffer, WDSIPv4MultiGroup, and wsdUDP.
Referenced by ParseBuffer(), and Process().
buildSoapMessage()
bool WSDiscovery::CWSDiscoveryListenerUDP::buildSoapMessage (const std::string & action, std::string & msg, const std::string & extraparameter) private
References WSDiscovery::bye_body, WSDiscovery::CWSDiscoveryPosix::GetInstanceID(), CServiceBroker::GetWSDiscovery(), WSDiscovery::hello_body, CLog::Log(), LOGDEBUG, LOGWSDISCOVERY, WSDiscovery::probe_body, WSDiscovery::resolve_body, WSDiscovery::soap_msg_templ, WSDiscovery::WSD_ACT_BYE, WSDiscovery::WSD_ACT_HELLO, WSDiscovery::WSD_ACT_PROBE, WSDiscovery::WSD_ACT_RESOLVE, and wsd_instance_address.
Referenced by AddCommand().
Cleanup()
void WSDiscovery::CWSDiscoveryListenerUDP::Cleanup (bool aborted) private
References fd, CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_SERVICES_WSDISCOVERY.
Referenced by Process().
DispatchCommand()
bool WSDiscovery::CWSDiscoveryListenerUDP::DispatchCommand () private
References WSDiscovery::CWSDiscoveryListenerUDP::Command::address, WSDiscovery::CWSDiscoveryListenerUDP::Command::commandMsg, crit_commandqueue, fd, CLog::Log(), LOGDEBUG, LOGWSDISCOVERY, CThread::m_bStop, m_commandbuffer, retries, and CThread::Sleep().
Referenced by Process().
equalsAddress()
bool WSDiscovery::CWSDiscoveryListenerUDP::equalsAddress (const WSDiscovery::wsd_req_info & lhs, const WSDiscovery::wsd_req_info & rhs) const private
References WSDiscovery::wsd_req_info::address.
ParseBuffer()
void WSDiscovery::CWSDiscoveryListenerUDP::ParseBuffer (const std::string & buffer) private
References WSDiscovery::action_tag, AddCommand(), WSDiscovery::address_tag, crit_wsdqueue, CServiceBroker::GetWSDiscovery(), CLog::Log(), LOGDEBUG, LOGWSDISCOVERY, m_vecWSDInfo, WSDiscovery::msgid_tag, PrintWSDInfo(), WSDiscovery::CWSDiscoveryPosix::SetItems(), types, WSDiscovery::types_tag, UnicastGet(), WSDiscovery::WSD_ACT_BYE, WSDiscovery::WSD_ACT_HELLO, WSDiscovery::WSD_ACT_PROBEMATCH, WSDiscovery::WSD_ACT_RESOLVE, WSDiscovery::WSD_ACT_RESOLVEMATCHES, wsd_tag_find(), and WSDiscovery::xaddrs_tag.
Referenced by Process().
PrintWSDInfo()
void WSDiscovery::CWSDiscoveryListenerUDP::PrintWSDInfo (const WSDiscovery::wsd_req_info & info) private
References CLog::Log(), LOGDEBUG, and LOGWSDISCOVERY.
Referenced by ParseBuffer().
Process()
void WSDiscovery::CWSDiscoveryListenerUDP::Process (void) override protected virtual
Reimplemented from CThread.
References AddCommand(), Cleanup(), DispatchCommand(), fd, CLog::Log(), LOGDEBUG, LOGWSDISCOVERY, CThread::m_bStop, ParseBuffer(), UDPBUFFSIZE, WDSIPv4MultiGroup, WSDiscovery::WSD_ACT_BYE, WSDiscovery::WSD_ACT_HELLO, WSDiscovery::WSD_ACT_PROBE, and wsdUDP.
Start()
void WSDiscovery::CWSDiscoveryListenerUDP::Start ()
References CThread::Create(), CServiceBroker::GetWSDiscovery(), CThread::IsRunning(), CLog::Log(), LOGINFO, LOWEST, m_vecWSDInfo, WSDiscovery::CWSDiscoveryPosix::SetItems(), and CThread::SetPriority().
Stop()
void WSDiscovery::CWSDiscoveryListenerUDP::Stop ()
References CLog::Log(), LOGINFO, and CThread::StopThread().
UnicastGet()
void WSDiscovery::CWSDiscoveryListenerUDP::UnicastGet (wsd_req_info & info) private
References WSDiscovery::computer_tag, WSDiscovery::get_msg, CLog::Log(), LOGDEBUG, LOGWSDISCOVERY, XFILE::CCurlFile::SetAcceptEncoding(), wsd_instance_address, and wsd_tag_find().
Referenced by ParseBuffer().
wsd_tag_find()
template<std::size_t SIZE> const std::string WSDiscovery::CWSDiscoveryListenerUDP::wsd_tag_find (const std::string & xml, const std::array< std::pair< std::string, std::string >, SIZE > & tag) private
Referenced by ParseBuffer(), and UnicastGet().
Member Data Documentation
crit_commandqueue
CCriticalSection WSDiscovery::CWSDiscoveryListenerUDP::crit_commandqueue private
Referenced by AddCommand(), and DispatchCommand().
crit_wsdqueue
CCriticalSection WSDiscovery::CWSDiscoveryListenerUDP::crit_wsdqueue private
Referenced by ParseBuffer().
fd
int WSDiscovery::CWSDiscoveryListenerUDP::fd private
Referenced by Cleanup(), DispatchCommand(), and Process().
m_commandbuffer
std::vector<Command> WSDiscovery::CWSDiscoveryListenerUDP::m_commandbuffer private
Referenced by AddCommand(), and DispatchCommand().
m_vecWSDInfo
std::vector<WSDiscovery::wsd_req_info> WSDiscovery::CWSDiscoveryListenerUDP::m_vecWSDInfo private
Referenced by ParseBuffer(), and Start().
retries
constexpr int WSDiscovery::CWSDiscoveryListenerUDP::retries {4} static constexpr private
Referenced by DispatchCommand().
UDPBUFFSIZE
constexpr int WSDiscovery::CWSDiscoveryListenerUDP::UDPBUFFSIZE {65507} static constexpr private
Referenced by Process().
WDSIPv4MultiGroup
constexpr char WSDiscovery::CWSDiscoveryListenerUDP::WDSIPv4MultiGroup[] {"239.255.255.250"} static constexpr private
Referenced by AddCommand(), and Process().
wsd_instance_address
const std::string WSDiscovery::CWSDiscoveryListenerUDP::wsd_instance_address private
Referenced by buildSoapMessage(), and UnicastGet().
wsdUDP
constexpr int WSDiscovery::CWSDiscoveryListenerUDP::wsdUDP {3702} static constexpr private
Referenced by AddCommand(), and Process().
The documentation for this class was generated from the following files:
SMBWSDiscoveryListener.h
SMBWSDiscoveryListener.cpp