Kodi Documentation: MUSIC_GRABBER::CMusicArtistInfo Class Reference
MUSIC_GRABBER::CMusicArtistInfo Class Reference
#include <MusicArtistInfo.h>
Public Member Functions
CMusicArtistInfo ()=default
CMusicArtistInfo (const std::string &strArtist, const CScraperUrl &strArtistURL)
virtual ~CMusicArtistInfo ()=default
bool Loaded () const
void SetLoaded ()
void SetArtist (const CArtist &artist)
const CArtist & GetArtist () const
CArtist & GetArtist ()
const CScraperUrl & GetArtistURL () const
bool Load (XFILE::CCurlFile &http, const ADDON::ScraperPtr &scraper, const std::string &strSearch)
Protected Attributes
CArtist m_artist
CScraperUrl m_artistURL
bool m_bLoaded = false
Constructor & Destructor Documentation
CMusicArtistInfo() [1/2]
MUSIC_GRABBER::CMusicArtistInfo::CMusicArtistInfo () default
CMusicArtistInfo() [2/2]
CMusicArtistInfo::CMusicArtistInfo (const std::string & strArtist, const CScraperUrl & strArtistURL)
References m_artist, m_bLoaded, and CArtist::strArtist.
~CMusicArtistInfo()
virtual MUSIC_GRABBER::CMusicArtistInfo::~CMusicArtistInfo () virtual default
Member Function Documentation
GetArtist() [1/2]
CArtist & MUSIC_GRABBER::CMusicArtistInfo::GetArtist () inline
References m_artist.
GetArtist() [2/2]
const CArtist & MUSIC_GRABBER::CMusicArtistInfo::GetArtist () const inline
References m_artist.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), ADDON::CScraper::FindArtist(), MUSIC_GRABBER::CMusicInfoScraper::LoadArtistInfo(), and MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo().
GetArtistURL()
const CScraperUrl & MUSIC_GRABBER::CMusicArtistInfo::GetArtistURL () const inline
References m_artistURL.
Load()
bool CMusicArtistInfo::Load (XFILE::CCurlFile & http, const ADDON::ScraperPtr & scraper, const std::string & strSearch)
References m_artist, m_artistURL, and m_bLoaded.
Referenced by MUSIC_GRABBER::CMusicInfoScraper::LoadArtistInfo().
Loaded()
bool MUSIC_GRABBER::CMusicArtistInfo::Loaded () const inline
References m_bLoaded.
SetArtist()
void CMusicArtistInfo::SetArtist (const CArtist & artist)
References m_artist, and m_bLoaded.
SetLoaded()
void MUSIC_GRABBER::CMusicArtistInfo::SetLoaded () inline
References m_bLoaded.
Referenced by MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo().
Member Data Documentation
m_artist
CArtist MUSIC_GRABBER::CMusicArtistInfo::m_artist protected
Referenced by CMusicArtistInfo(), GetArtist(), GetArtist(), Load(), and SetArtist().
m_artistURL
CScraperUrl MUSIC_GRABBER::CMusicArtistInfo::m_artistURL protected
Referenced by GetArtistURL(), and Load().
m_bLoaded
bool MUSIC_GRABBER::CMusicArtistInfo::m_bLoaded = false protected
Referenced by CMusicArtistInfo(), Load(), Loaded(), SetArtist(), and SetLoaded().
The documentation for this class was generated from the following files:
MusicArtistInfo.h
MusicArtistInfo.cpp