Kodi Documentation: anonymous_namespace{CSSUtils.cpp} Namespace Reference
anonymous_namespace{CSSUtils.cpp} Namespace Reference
Functions
bool isHexDigit (char c)
uint32_t convertHexDigit (char c)
bool isSurrogateCodePoint (uint32_t c)
bool isGreaterThanMaximumAllowedCodePoint (uint32_t c)
std::string escapeStringChunk (std::string &str, size_t &pos)
Function Documentation
convertHexDigit()
uint32_t anonymous_namespace{CSSUtils.cpp}::convertHexDigit (char c)
Referenced by escapeStringChunk().
escapeStringChunk()
std::string anonymous_namespace{CSSUtils.cpp}::escapeStringChunk (std::string & str, size_t & pos)
References convertHexDigit(), isGreaterThanMaximumAllowedCodePoint(), isHexDigit(), and isSurrogateCodePoint().
Referenced by UTILS::CSS::Escape().
isGreaterThanMaximumAllowedCodePoint()
bool anonymous_namespace{CSSUtils.cpp}::isGreaterThanMaximumAllowedCodePoint (uint32_t c)
Referenced by escapeStringChunk().
isHexDigit()
bool anonymous_namespace{CSSUtils.cpp}::isHexDigit (char c)
Referenced by escapeStringChunk().
isSurrogateCodePoint()
bool anonymous_namespace{CSSUtils.cpp}::isSurrogateCodePoint (uint32_t c)
Referenced by escapeStringChunk().