Kodi Documentation: audiodecoder.h File Reference
audiodecoder.h File Reference
#include "../addon_base.h"
#include "../audio_engine.h"
Classes
struct KODI_ADDON_AUDIODECODER_INFO_TAG
struct AddonToKodiFuncTable_AudioDecoder
struct KodiToAddonFuncTable_AudioDecoder
struct AddonInstance_AudioDecoder
Macros
#define KODI_ADDON_AUDIODECODER_TRACK_EXT "_adecstrm"
Identifier which is attached to stream files and with defined names in addon.xml (name="???") if addon supports "tracks" (set in addon.xml tracks="true").
#define KODI_ADDON_AUDIODECODER_GET_TRACK_EXT(name) "." name KODI_ADDON_AUDIODECODER_TRACK_EXT
Macro to get file extension to track supported files.
Typedefs
typedef KODI_ADDON_INSTANCE_HDL KODI_ADDON_AUDIODECODER_HDL
typedef enum AUDIODECODER_READ_RETURN AUDIODECODER_READ_RETURN
typedef const char * file
typedef const char unsigned int filecache
typedef const char unsigned int int * channels
typedef const char unsigned int int int * samplerate
typedef const char unsigned int int int int * bitspersample
typedef const char unsigned int int int int int64_t * totaltime
typedef const char unsigned int int int int int64_t int * bitrate
typedef const char unsigned int int int int int64_t int enum AudioEngineDataFormat * format
typedef const char unsigned int int int int int64_t int enum AudioEngineDataFormat enum AudioEngineChannel info[AUDIOENGINE_CH_MAX]
typedef uint8_t * buffer
typedef uint8_t size_t size
typedef uint8_t size_t size_t * actualsize
typedef int64_t time
typedef const char struct KODI_ADDON_AUDIODECODER_INFO_TAG * tag
typedef struct AddonToKodiFuncTable_AudioDecoder AddonToKodiFuncTable_AudioDecoder
typedef struct KodiToAddonFuncTable_AudioDecoder KodiToAddonFuncTable_AudioDecoder
typedef struct AddonInstance_AudioDecoder AddonInstance_AudioDecoder
Enumerations
enum AUDIODECODER_READ_RETURN { AUDIODECODER_READ_EOF = -1 , AUDIODECODER_READ_SUCCESS = 0 , AUDIODECODER_READ_ERROR = 1 }
Functions
typedef bool (ATTR_APIENTRYP PFN_KODI_ADDON_AUDIODECODER_SUPPORTS_FILE_V1)(const KODI_ADDON_AUDIODECODER_HDL hdl
typedef int (ATTR_APIENTRYP PFN_KODI_ADDON_AUDIODECODER_READ_PCM_V1)(const KODI_ADDON_AUDIODECODER_HDL hdl
typedef int64_t (ATTR_APIENTRYP PFN_KODI_ADDON_AUDIODECODER_SEEK_V1)(const KODI_ADDON_AUDIODECODER_HDL hdl
Typedef Documentation
actualsize
typedef uint8_t size_t size_t* actualsize
AddonInstance_AudioDecoder
typedef struct AddonInstance_AudioDecoder AddonInstance_AudioDecoder
AddonToKodiFuncTable_AudioDecoder
typedef struct AddonToKodiFuncTable_AudioDecoder AddonToKodiFuncTable_AudioDecoder
bitrate
typedef const char unsigned int int int int int64_t int* bitrate
bitspersample
typedef const char unsigned int int int int* bitspersample
buffer
typedef uint8_t* buffer
channels
typedef const char unsigned int int* channels
file
typedef const char * file
filecache
typedef const char unsigned int filecache
format
typedef const char unsigned int int int int int64_t int enum AudioEngineDataFormat* format
info
typedef const char unsigned int int int int int64_t int enum AudioEngineDataFormat enum AudioEngineChannel info[AUDIOENGINE_CH_MAX]
KODI_ADDON_AUDIODECODER_HDL
typedef KODI_ADDON_INSTANCE_HDL KODI_ADDON_AUDIODECODER_HDL
KodiToAddonFuncTable_AudioDecoder
typedef struct KodiToAddonFuncTable_AudioDecoder KodiToAddonFuncTable_AudioDecoder
samplerate
typedef const char unsigned int int int* samplerate
size
typedef uint8_t size_t size
tag
typedef const char struct KODI_ADDON_AUDIODECODER_INFO_TAG* tag
time
typedef int64_t time
totaltime
typedef const char unsigned int int int int int64_t* totaltime
Function Documentation
bool()
typedef bool (ATTR_APIENTRYP PFN_KODI_ADDON_AUDIODECODER_SUPPORTS_FILE_V1) const
Referenced by CAESinkFactoryWin::BuildWaveFormatExtensible(), CLinuxPowerSyscall::CreateInstance(), CMediaCodecVideoBuffer::HasSurfaceTexture(), and CDBusUtil::ParseType().
int()
typedef int (ATTR_APIENTRYP PFN_KODI_ADDON_AUDIODECODER_READ_PCM_V1) const
int64_t()
typedef int64_t (ATTR_APIENTRYP PFN_KODI_ADDON_AUDIODECODER_SEEK_V1) const
Referenced by CDVDClock::AbsoluteToSystem(), CDVDAudioCodecAndroidMediaCodec::AddData(), CDVDAudioCodecFFmpeg::AddData(), CDVDVideoCodecAndroidMediaCodec::AddData(), CDVDVideoCodecDRMPRIME::AddData(), CDVDVideoCodecFFmpeg::AddData(), CAESinkALSA::AddPackets(), CDVDDemuxFFmpeg::AddStream(), KODI::UTILS::StringUtils::AlphaNumericCollation(), kodi::tools::StringUtils::AlphaNumericCompare(), KODI::UTILS::StringUtils::AlphaNumericCompare(), UPNP::CUPnPRenderer::Announce(), CVariant::asBoolean(), CVariant::asDouble(), CVariant::asInteger(), CVariant::asString(), CVariant::asUnsignedInteger(), CVariant::asWideString(), kodi::vfs::CFile::AtEnd(), CZeroconfBrowserDarwin::BrowserCallback(), CDVDAudioCodecFFmpeg::BuildChannelMap(), XFILE::CDoubleCache::CachedDataEndPosIfSeekTo(), BitstreamStats::CalculateBitrate(), CGUIWindowFileManager::CalculateFolderSize(), Clamp(), DRM::CMediaDrmCryptoSession::CMediaDrmCryptoSession(), XFILE::CCurlFile::CReadState::Connect(), CUtil::ConvertSecsToMilliSecs(), CDVDDemuxFFmpeg::ConvertTimestamp(), CurrentHostCounter(), CurrentHostFrequency(), CVariant::CVariant(), CDVDOverlayCodecFFmpeg::Decode(), CZeroconfBrowserDarwin::doAddServiceType(), CFileOperationJob::DoProcessFile(), CZeroconfDarwin::doPublishService(), DVD_TIME_TO_MSEC(), ADDON::CAddonInstaller::EnumeratePackageFolder(), CDVDFileInfo::ExtractThumbToTexture(), CBlurayCallback::file_read(), CBlurayCallback::file_write(), VAAPI::CFFmpegPostproc::Filter(), CSeekHandler::FrameMove(), dbiplus::field_value::get_asInt64(), CDVDClock::GetAbsoluteClock(), NPT_XbmcFileInputStream::GetAvailable(), CVideoPlayer::GetCachingTimes(), CDVDDemuxFFmpeg::GetChapterPos(), CDVDClock::GetClock(), CDVDClock::GetClock(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetContentRanges(), CDVDAudioCodecFFmpeg::GetData(), CDVDAudioCodecAndroidMediaCodec::GetData(), CAESinkAUDIOTRACK::GetDelay(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CNFSDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), XFILE::CWinLibraryDirectory::GetDirectory(), KODI::VIDEO::CVideoInfoScanner::GetFastHash(), anonymous_namespace{PVRGUIDirectory.cpp}::GetGetRecordingsSubDirectories(), CTextureCacheJob::GetImageHash(), CDVDInputStreamBluray::GetLength(), CInputStreamMultiSource::GetLength(), XFILE::CFileCDDA::GetLength(), CXBMCApp::GetNextFrameTime(), CDVDVideoCodecAndroidMediaCodec::GetOutputPicture(), CVideoPlayer::GetPercentage(), UPNP::CUPnPPlayer::GetPercentage(), CDVDVideoCodecFFmpeg::GetPicture(), CDVDVideoCodecFFmpeg::GetPictureCommon(), CDataCacheCore::GetPlayPercentage(), XFILE::CWinLibraryFile::GetPosition(), XFILE::CFileCDDA::GetPosition(), CInputStreamPVRChannel::GetPVRStreamLength(), CInputStreamPVRRecording::GetPVRStreamLength(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), KODI::VIDEO::CVideoInfoScanner::GetRecursiveFastHash(), KODI::RETRO::CSavestateDatabase::GetSavestate(), CDVDDemuxCDDA::GetStreamLength(), CVideoReferenceClock::GetTime(), PAPlayer::GetTimeInternal(), CApplicationPlayer::GetTotalTime(), PAPlayer::GetTotalTime64(), XFILE::CBlurayDirectory::GetUserPlaylists(), CZipManager::GetZipList(), CVideoPlayer::HandleMessages(), CGUIListItem::IncrementProperty(), CGUIListItem::IncrementProperty(), VideoPlayerCodec::Init(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), XFILE::CPosixFile::IoControl(), CVideoSyncIos::IosVblankHandler(), CFileItem::IsResumable(), XFILE::CFile::LoadFile(), XBMCAddon::RetardedAsyncCallbackHandler::makePendingCalls(), mem_file_read(), mem_file_seek(), dbiplus::MysqlDatabase::mysqlVXPrintf(), CDVDDemux::NewGuid(), CApplication::OnMessage(), CGUIWindowFileManager::OnPopupMenu(), CGUIDialogVideoBookmarks::OnRefreshList(), UPNP::CUPnPRenderer::OnSeek(), UPNP::CUPnPRenderer::OnSetVolume(), CAndroidTouch::onTouchEvent(), XFILE::CSMBFile::Open(), CDVDDemuxFFmpeg::Open(), CVideoPlayer::OpenDemuxStream(), CArchive::operator>>(), CDVDDemuxClient::ParsePacket(), CDBusUtil::ParseType(), preliminarySort(), CVideoReferenceClock::Process(), XFILE::CFileCache::Process(), CDVDInputStreamNavigator::ProcessBlock(), CAirPlayServer::CTCPClient::ProcessRequest(), PAPlayer::ProcessStream(), ADDON::CAddonInstaller::PrunePackageCache(), anonymous_namespace{AESinkPipewire.cpp}::PWTimeToAEDelay(), PAPlayer::QueueNextFileEx(), CUDFBlockInput::Read(), XFILE::CFileCache::Read(), XFILE::CNFSFile::Read(), XFILE::CXbtFile::Read(), XFILE::CPosixFile::Read(), read_blocks(), XBMCAddon::xbmcvfs::File::readBytes(), XFILE::CCurlFile::CReadState::ReadCallback(), XFILE::CSimpleFileCache::ReadFromCache(), XFILE::IFile::ReadString(), CZeroconfDarwin::registerCallback(), CMediaCodecVideoBuffer::ReleaseOutputBuffer(), CVideoSyncD3D::Run(), KODI::WINDOWING::X11::CVideoSyncGLX::Run(), ActiveAE::CActiveAE::RunStages(), CVideoPlayer::Seek(), XFILE::CSimpleFileCache::Seek(), XFILE::CFileCache::Seek(), XFILE::CWinLibraryFile::Seek(), XFILE::CFileCDDA::Seek(), XFILE::CCurlFile::Seek(), XFILE::CNFSFile::Seek(), XFILE::CXbtFile::Seek(), XFILE::CZipFile::Seek(), XFILE::CPosixFile::Seek(), XFILE::CSMBFile::Seek(), CDVDInputStreamBluray::Seek(), CDVDInputStreamFile::Seek(), CDVDInputStreamStack::Seek(), CInputStreamPVRBase::Seek(), NPT_XbmcFileStream::Seek(), PVR::CPVRGUIActionsPlayback::SeekBackward(), PVR::CPVRGUIActionsPlayback::SeekForward(), XFILE::CFileStreamBuffer::seekoff(), KODI::RETRO::CRetroPlayer::SeekPercentage(), UPNP::CUPnPPlayer::SeekPercentage(), PAPlayer::SeekPercentage(), CVideoPlayer::SeekPercentage(), CInputStreamPVRChannel::SeekPVRStream(), CInputStreamPVRRecording::SeekPVRStream(), CSeekHandler::SeekSeconds(), CApplication::SeekTime(), CDVDDemuxCDDA::SeekTime(), CDVDDemuxFFmpeg::SeekTime(), CVideoPlayer::SeekTime(), PAPlayer::SeekTime(), CVideoPlayer::SeekTimeRelative(), CApplicationPlayer::SeekTimeRelative(), XBMCAddon::xbmcgui::ListItem::setInfo(), CDVDVideoCodecDRMPRIME::SetPictureParams(), CSeekHandler::SetSeekSize(), CDVDClock::SetSpeed(), KODI::UTILS::StringUtils::SplitMulti(), CFileItemList::StackFiles(), XFILE::CCurlFile::Stat(), ActiveAE::CActiveAESink::StateMachine(), CUtil::StatToStatI64(), str2int64(), str2int64(), CDVDClock::SystemToPlaying(), MUSIC_INFO::TagLibVFSStream::tell(), NPT_XbmcFileStream::Tell(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), CUtil::ToInt64(), MUSIC_INFO::CMusicInfoTag::ToSortable(), XFILE::CPosixFile::Truncate(), XFILE::CWin32File::Truncate(), CVideoSyncTVos::TVosVblankHandler(), CVideoReferenceClock::UpdateClockInternal(), PAPlayer::UpdateGUIData(), CGUIWindowFileManager::UpdateItemCounts(), CVideoPlayer::UpdatePlayState(), PVR::CPVRRecording::UpdateRecordingSize(), CXBMCApp::UpdateSessionState(), PAPlayer::UpdateStreamInfoPlayNextAtFrame(), PVR::CPVRGUITimesInfo::UpdateTimeshiftData(), CVideoSyncOsx::VblankHandler(), Pointer::velocity(), XFILE::CSimpleFileCache::WaitForData(), XFILE::CCircularCache::WaitForData(), XFILE::CCircularCache::WriteToCache(), and XFILE::XBTFFileToFileItem().