Kodi Documentation: JSONRPC::CPlaylistOperations Class Reference
JSONRPC::CPlaylistOperations Class Reference
#include <PlaylistOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetPlaylists (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetProperties (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetItems (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Add (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Remove (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Insert (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Clear (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Swap (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Static Public Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
Static Private Member Functions
static KODI::PLAYLIST::Id GetPlaylist (const CVariant &playlist)
static JSONRPC_STATUS GetPropertyValue (KODI::PLAYLIST::Id playlistId, const std::string &property, CVariant &result)
static bool CheckMediaParameter (KODI::PLAYLIST::Id playlistId, const CVariant &itemObject)
static bool HandleItemsParameter (KODI::PLAYLIST::Id playlistId, const CVariant &itemParam, CFileItemList &items)
Additional Inherited Members
Static Protected Member Functions inherited from JSONRPC::CFileItemHandler
static void FillDetails (const ISerializable *info, const std::shared_ptr< CFileItem > &item, std::set< std::string > &fields, CVariant &result, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, bool sortLimit=true)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, int size, bool sortLimit=true)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const CVariant &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const std::set< std::string > &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
Static Protected Member Functions inherited from JSONRPC::CJSONUtils
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Member Function Documentation
Add()
JSONRPC_STATUS CPlaylistOperations::Add (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CSlideShowDelegator::Add(), CServiceBroker::GetAppMessenger(), CFileItem::GetPath(), CFileItem::GetPictureInfoTag(), GetPlaylist(), CServiceBroker::GetSlideShowDelegator(), HandleItemsParameter(), index(), JSONRPC::InvalidParams, CPictureInfoTag::Load(), CFileItemList::Size(), and TMSG_PLAYLISTPLAYER_ADD.
CheckMediaParameter()
bool CPlaylistOperations::CheckMediaParameter (KODI::PLAYLIST::Id playlistId, const CVariant & itemObject) static private
References CVariant::asString(), and CVariant::isMember().
Referenced by HandleItemsParameter().
Clear()
JSONRPC_STATUS CPlaylistOperations::Clear (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
Todo:
: Stop should be a delegator method to void GUI coupling! Same goes for other player controls.
References JSONRPC::ACK, ACTION_STOP, CServiceBroker::GetAppMessenger(), GetPlaylist(), CServiceBroker::GetSlideShowDelegator(), CSlideShowDelegator::Reset(), TMSG_GUI_ACTION, TMSG_PLAYLISTPLAYER_CLEAR, and WINDOW_SLIDESHOW.
GetItems()
JSONRPC_STATUS CPlaylistOperations::GetItems (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CServiceBroker::GetAppMessenger(), GetPlaylist(), CSlideShowDelegator::GetSlideShowContents(), CServiceBroker::GetSlideShowDelegator(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::OK, and TMSG_PLAYLISTPLAYER_GET_ITEMS.
GetPlaylist()
PLAYLIST::Id CPlaylistOperations::GetPlaylist (const CVariant & playlist) static private
References playlist.
Referenced by Add(), Clear(), GetItems(), GetProperties(), Insert(), Remove(), and Swap().
GetPlaylists()
JSONRPC_STATUS CPlaylistOperations::GetPlaylists (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::append(), JSONRPC::OK, playlist, CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
GetProperties()
JSONRPC_STATUS CPlaylistOperations::GetProperties (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), GetPlaylist(), GetPropertyValue(), index(), JSONRPC::OK, and CVariant::size().
GetPropertyValue()
JSONRPC_STATUS CPlaylistOperations::GetPropertyValue (KODI::PLAYLIST::Id playlistId, const std::string & property, CVariant & result) static private
References CServiceBroker::GetAppMessenger(), CServiceBroker::GetSlideShowDelegator(), JSONRPC::InvalidParams, CSlideShowDelegator::NumSlides(), JSONRPC::OK, CFileItemList::Size(), and TMSG_PLAYLISTPLAYER_GET_ITEMS.
Referenced by GetProperties().
HandleItemsParameter()
bool CPlaylistOperations::HandleItemsParameter (KODI::PLAYLIST::Id playlistId, const CVariant & itemParam, CFileItemList & items) static private
References CVariant::begin_array(), CheckMediaParameter(), CVariant::end_array(), JSONRPC::CFileItemHandler::FillFileItemList(), CVariant::isArray(), CVariant::push_back(), and success.
Referenced by Add(), and Insert().
Insert()
JSONRPC_STATUS CPlaylistOperations::Insert (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), GetPlaylist(), HandleItemsParameter(), JSONRPC::InvalidParams, and TMSG_PLAYLISTPLAYER_INSERT.
Remove()
JSONRPC_STATUS CPlaylistOperations::Remove (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), JSONRPC::InvalidParams, and TMSG_PLAYLISTPLAYER_REMOVE.
Swap()
JSONRPC_STATUS CPlaylistOperations::Swap (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), GetPlaylist(), and TMSG_PLAYLISTPLAYER_SWAP.
The documentation for this class was generated from the following files:
PlaylistOperations.h
PlaylistOperations.cpp