Kodi Documentation: KODI::UTILS::StringUtils Class Reference
KODI::UTILS::StringUtils Class Reference
#include <StringUtils.h>
Static Public Member Functions
template<typename... Args>
static constexpr std::string Format (std::string_view format, Args &&... args)
Get a formatted string similar to sprintf.
template<typename... Args>
static constexpr std::wstring Format (std::wstring_view format, Args &&... args)
static std::string FormatV (PRINTF_FORMAT_STRING const char *fmt, va_list args)
static std::wstring FormatV (PRINTF_FORMAT_STRING const wchar_t *fmt, va_list args)
static std::string ToUpper (const std::string &str)
static std::wstring ToUpper (const std::wstring &str)
static void ToUpper (std::string &str)
static void ToUpper (std::wstring &str)
static std::string ToLower (const std::string &str)
static std::wstring ToLower (const std::wstring &str)
static void ToLower (std::string &str)
static void ToLower (std::wstring &str)
static void ToCapitalize (std::string &str)
static void ToCapitalize (std::wstring &str)
static bool EqualsNoCase (const std::string &str1, const std::string &str2)
static bool EqualsNoCase (const std::string &str1, const char *s2)
static bool EqualsNoCase (const char *s1, const char *s2)
static int CompareNoCase (const std::string &str1, const std::string &str2, size_t n=0)
static int CompareNoCase (const char *s1, const char *s2, size_t n=0)
static int ReturnDigits (const std::string &str)
static std::string Left (const std::string &str, size_t count)
static std::string Mid (const std::string &str, size_t first, size_t count=std::string::npos)
static std::string Right (const std::string &str, size_t count)
static std::string & Trim (std::string &str)
static std::string & Trim (std::string &str, const char *const chars)
static std::string & TrimLeft (std::string &str)
static std::string & TrimLeft (std::string &str, const char *const chars)
static std::string & TrimRight (std::string &str)
static std::string & TrimRight (std::string &str, const char *const chars)
static std::string & RemoveDuplicatedSpacesAndTabs (std::string &str)
static bool IsSpecialCharacter (char c)
Check if the character is a special character.
static std::string ReplaceSpecialCharactersWithSpace (const std::string &str)
static int Replace (std::string &str, char oldChar, char newChar)
static int Replace (std::string &str, const std::string &oldStr, const std::string &newStr)
static int Replace (std::wstring &str, const std::wstring &oldStr, const std::wstring &newStr)
static bool StartsWith (const std::string &str1, const std::string &str2)
static bool StartsWith (const std::string &str1, const char *s2)
static bool StartsWith (const char *s1, const char *s2)
static bool StartsWithNoCase (const std::string &str1, const std::string &str2)
static bool StartsWithNoCase (const std::string &str1, const char *s2)
static bool StartsWithNoCase (const char *s1, const char *s2)
static bool EndsWith (const std::string &str1, const std::string &str2)
static bool EndsWith (const std::string &str1, const char *s2)
static bool EndsWithNoCase (const std::string &str1, const std::string &str2)
static bool EndsWithNoCase (const std::string &str1, const char *s2)
template<typename CONTAINER >
static std::string Join (const CONTAINER &strings, const std::string &delimiter)
static std::vector< std::string > Split (const std::string &input, const std::string &delimiter, unsigned int iMaxStrings=0)
Splits the given input string using the given delimiter into separate strings.
static std::vector< std::string > Split (const std::string &input, const char delimiter, size_t iMaxStrings=0)
static std::vector< std::string > Split (const std::string &input, const std::vector< std::string > &delimiters)
template<typename OutputIt >
static OutputIt SplitTo (OutputIt d_first, const std::string &input, const std::string &delimiter, unsigned int iMaxStrings=0)
Splits the given input string using the given delimiter into separate strings.
template<typename OutputIt >
static OutputIt SplitTo (OutputIt d_first, const std::string &input, const char delimiter, size_t iMaxStrings=0)
template<typename OutputIt >
static OutputIt SplitTo (OutputIt d_first, const std::string &input, const std::vector< std::string > &delimiters)
static std::vector< std::string > SplitMulti (const std::vector< std::string > &input, const std::vector< std::string > &delimiters, size_t iMaxStrings=0)
Splits the given input strings using the given delimiters into further separate strings.
static int FindNumber (const std::string &strInput, const std::string &strFind)
static int64_t AlphaNumericCompare (const wchar_t *left, const wchar_t *right)
static int AlphaNumericCollation (int nKey1, const void *pKey1, int nKey2, const void *pKey2)
static long TimeStringToSeconds (const std::string &timeString)
static void RemoveCRLF (std::string &strLine)
static size_t utf8_strlen (const char *s)
utf8 version of strlen - skips any non-starting bytes in the count, thus returning the number of utf8 characters
static std::string SecondsToTimeString (long seconds, TIME_FORMAT format=TIME_FORMAT_GUESS)
convert a time in seconds to a string based on the given time format
static std::string MillisecondsToTimeString (std::chrono::milliseconds milliSeconds)
convert a milliseconds value to a time string in the TIME_FORMAT_HH_MM_SS format
static bool IsNaturalNumber (const std::string &str)
check whether a string is a natural number. Matches [ \t]*[0-9]+[ \t]*
static bool IsInteger (const std::string &str)
check whether a string is an integer. Matches [ \t]*[-]*[0-9]+[ \t]*
static bool isasciidigit (char chr)
static bool isasciixdigit (char chr)
static int asciidigitvalue (char chr)
static int asciixdigitvalue (char chr)
static bool isasciiuppercaseletter (char chr)
static bool isasciilowercaseletter (char chr)
static bool isasciialphanum (char chr)
static std::string SizeToString (int64_t size)
static size_t FindWords (const char *str, const char *wordLowerCase)
static int FindEndBracket (const std::string &str, char opener, char closer, int startPos=0)
static int DateStringToYYYYMMDD (const std::string &dateString)
static std::string ISODateToLocalizedDate (const std::string &strIsoDate)
static void WordToDigits (std::string &word)
static std::string CreateUUID ()
static bool ValidateUUID (const std::string &uuid)
static double CompareFuzzy (const std::string &left, const std::string &right)
static int FindBestMatch (const std::string &str, const std::vector< std::string > &strings, double &matchscore)
static bool ContainsKeyword (const std::string &str, const std::vector< std::string > &keywords)
static std::string BinaryStringToString (const std::string &in)
Convert the string of binary chars to the actual string.
static std::string ToHexadecimal (const std::string &in)
template<typename T >
static std::string FormatNumber (T num)
Format the string with locale separators.
static std::string Paramify (const std::string &param)
Escapes the given string to be able to be used as a parameter.
static std::string DeParamify (const std::string &param)
Unescapes the given string.
static std::vector< std::string > Tokenize (const std::string &input, const std::string &delimiters)
Split a string by the specified delimiters. Splits a string using one or more delimiting characters, ignoring empty tokens. Differs from Split() in two ways:
static void Tokenize (const std::string &input, std::vector< std::string > &tokens, const std::string &delimiters)
static std::vector< std::string > Tokenize (const std::string &input, const char delimiter)
static void Tokenize (const std::string &input, std::vector< std::string > &tokens, const char delimiter)
static uint32_t ToUint32 (std::string_view str, uint32_t fallback=0) noexcept
Converts a string to a unsigned int number.
static uint64_t ToUint64 (std::string_view str, uint64_t fallback=0) noexcept
Converts a string to a unsigned long long number.
static float ToFloat (std::string_view str, float fallback=0.0f) noexcept
Converts a string to a float number.
static std::string FormatFileSize (uint64_t bytes)
static std::string CreateFromCString (const char *cstr)
Converts a cstring pointer (const char*) to a std::string. In case nullptr is passed the result is an empty string.
static bool Contains (std::string_view str, std::string_view keyword, bool isCaseInsensitive=true)
Check if a keyword string is contained on another string.
Static Public Attributes
static const std::string Empty = ""
Static Private Member Functions
static const std::locale & GetOriginalLocale () noexcept
Member Function Documentation
AlphaNumericCollation()
int KODI::UTILS::StringUtils::AlphaNumericCollation (int nKey1, const void * pKey1, int nKey2, const void * pKey2) static
References g_langInfo, KODI::UTILS::GetCollationWeight(), int64_t(), and KODI::UTILS::UTF8ToUnicode().
AlphaNumericCompare()
int64_t KODI::UTILS::StringUtils::AlphaNumericCompare (const wchar_t * left, const wchar_t * right) static
References g_langInfo, KODI::UTILS::GetCollationWeight(), int64_t(), left, and right.
Referenced by SorterAscending(), SorterDescending(), SorterIgnoreFoldersAscending(), SorterIgnoreFoldersDescending(), and TEST().
asciidigitvalue()
int KODI::UTILS::StringUtils::asciidigitvalue (char chr) static
References isasciidigit().
Referenced by asciixdigitvalue().
asciixdigitvalue()
int KODI::UTILS::StringUtils::asciixdigitvalue (char chr) static
References asciidigitvalue().
BinaryStringToString()
std::string KODI::UTILS::StringUtils::BinaryStringToString (const std::string & in) static
Convert the string of binary chars to the actual string.
Convert the string representation of binary chars to the actual string. For example \1\2\3 is converted to a string with binary char \1, \2 and \3
Parameters
param String to convert
Returns
Converted string
References end().
CompareFuzzy()
double KODI::UTILS::StringUtils::CompareFuzzy (const std::string & left, const std::string & right) static
References left, and right.
Referenced by FindBestMatch(), and TEST().
CompareNoCase() [1/2]
int KODI::UTILS::StringUtils::CompareNoCase (const char * s1, const char * s2, size_t n = 0) static
References index().
CompareNoCase() [2/2]
int KODI::UTILS::StringUtils::CompareNoCase (const std::string & str1, const std::string & str2, size_t n = 0) static
References CompareNoCase().
Referenced by Cocoa_MountPoint2DeviceName(), CompareNoCase(), CompareSettingOptionAseconding(), CompareSettingOptionDeseconding(), CDVDSubtitlesLibass::Configure(), dll_getenv(), dll_putenv(), dll_stat(), dll_stat64(), find_string(), IsDecoderWhitelisted(), IsDownmixDecoder(), and KODI::UTILS::sortstringbyname::operator()().
Contains()
bool KODI::UTILS::StringUtils::Contains (std::string_view str, std::string_view keyword, bool isCaseInsensitive = true) static
Check if a keyword string is contained on another string.
Parameters
str The string in which to search for the keyword
keyword The string to search for
Returns
True if the keyword if found.
ContainsKeyword()
bool KODI::UTILS::StringUtils::ContainsKeyword (const std::string & str, const std::vector< std::string > & keywords) static
CreateFromCString()
std::string KODI::UTILS::StringUtils::CreateFromCString (const char * cstr) static
Converts a cstring pointer (const char*) to a std::string. In case nullptr is passed the result is an empty string.
Parameters
cstr the const pointer to char
Returns
the resulting std::string or ""
CreateUUID()
std::string KODI::UTILS::StringUtils::CreateUUID () static
Referenced by TEST(), and TEST().
DateStringToYYYYMMDD()
int KODI::UTILS::StringUtils::DateStringToYYYYMMDD (const std::string & dateString) static
References Split().
Referenced by TEST().
DeParamify()
std::string KODI::UTILS::StringUtils::DeParamify (const std::string & param) static
Unescapes the given string.
Unescapes backslashes and double-quotes and removes double-quotes around the whole string.
Parameters
param String to unescape/deparamify
Returns
Unescaped/Deparamified string
References EndsWith(), Replace(), and StartsWith().
EndsWith() [1/2]
bool KODI::UTILS::StringUtils::EndsWith (const std::string & str1, const char * s2) static
EndsWith() [2/2]
bool KODI::UTILS::StringUtils::EndsWith (const std::string & str1, const std::string & str2) static
Referenced by DeParamify(), and TEST().
EndsWithNoCase() [1/2]
bool KODI::UTILS::StringUtils::EndsWithNoCase (const std::string & str1, const char * s2) static
EndsWithNoCase() [2/2]
bool KODI::UTILS::StringUtils::EndsWithNoCase (const std::string & str1, const std::string & str2) static
Referenced by ClearPhotoAssetCache(), PlayerControl(), SinkInfoCallback(), TEST(), and TimeStringToSeconds().
EqualsNoCase() [1/3]
bool KODI::UTILS::StringUtils::EqualsNoCase (const char * s1, const char * s2) static
EqualsNoCase() [2/3]
bool KODI::UTILS::StringUtils::EqualsNoCase (const std::string & str1, const char * s2) static
References EqualsNoCase().
EqualsNoCase() [3/3]
bool KODI::UTILS::StringUtils::EqualsNoCase (const std::string & str1, const std::string & str2) static
References EqualsNoCase().
Referenced by AddHost(), AddHostFromDatabase(), addISetting(), AddOrReplace(), AddOrReplace(), anonymous_namespace{GUIBuiltins.cpp}::AlarmClock(), anonymous_namespace{GUIBuiltins.cpp}::CancelAlarm(), anonymous_namespace{SettingConditions.cpp}::CheckMasterLock(), CleanLibrary(), anonymous_namespace{GUIBuiltins.cpp}::CloseDialog(), DeserializeOptionsSort(), EqualsNoCase(), EqualsNoCase(), ExportLibrary(), ExportLibrary2(), InhibitIdle(), InhibitScreenSaver(), LoadProfile(), LoadStr2Mem(), LoadWithFallback(), PlayDVD(), PlayerControl(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), anonymous_namespace{SettingConditions.cpp}::ProfileHasSettingsLocked(), ReloadSkin(), anonymous_namespace{GUIBuiltins.cpp}::Screenshot(), SetBool(), SetFocus(), SetTheme(), SetVolume(), Slideshow(), TEST(), Update(), and UpdateLibrary().
FindBestMatch()
int KODI::UTILS::StringUtils::FindBestMatch (const std::string & str, const std::vector< std::string > & strings, double & matchscore) static
References CompareFuzzy().
Referenced by TEST().
FindEndBracket()
int KODI::UTILS::StringUtils::FindEndBracket (const std::string & str, char opener, char closer, int startPos = 0) static
Referenced by TEST().
FindNumber()
int KODI::UTILS::StringUtils::FindNumber (const std::string & strInput, const std::string & strFind) static
Referenced by TEST().
FindWords()
size_t KODI::UTILS::StringUtils::FindWords (const char * str, const char * wordLowerCase) static
References KODI::UTILS::IsUTF8Letter().
Referenced by TEST(), and TEST().
Format() [1/2]
template<typename... Args> static constexpr std::string KODI::UTILS::StringUtils::Format (std::string_view format, Args &&... args) inline static constexpr
Get a formatted string similar to sprintf.
Parameters
fmt Format of the resulting string
... variable number of value type arguments
Returns
Formatted string
References KODI::UTILS::EnumToInt().
Referenced by anonymous_namespace{DVDDemuxCC.cpp}::ApplyStyleModifiers(), ByAlbum(), ByArtist(), ByArtistThenYear(), ByAudioChannels(), ByAudioCodec(), ByAudioLanguage(), ByBPM(), ByDateAdded(), ByDriveType(), ByEpisodeNumber(), ByFile(), ByLastPlayed(), ByNumberOfEpisodes(), ByNumberOfWatchedEpisodes(), ByOrigDate(), ByPath(), ByPlaycount(), ByRating(), BySeason(), BySubtitleLanguage(), ByTop250(), ByTotalDiscs(), ByUserRating(), ByVideoAspectRatio(), ByVideoCodec(), ByVideoResolution(), ByVotes(), ByYear(), ComputeVideoModeId(), anonymous_namespace{VideoStreamSelectHelper.cpp}::ConvertFpsToString(), anonymous_namespace{DVDOverlayCodecTX3G.cpp}::ConvertStyleToTags(), KODI::UTILS::COLOR::ConvertToHexRGB(), fetchDisplayModes(), ff_avutil_log(), FormatFileSize(), anonymous_namespace{ImageMetadataParser.cpp}::GetGPSString(), GetIntegerOptions(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArtTypes(), anonymous_namespace{Util.cpp}::GetTrailingDiscNumberSegmentInfoFromPath(), GUIDToString(), MillisecondsToTimeString(), ADDON::CAddonSystemSettings::OnSettingAction(), RunAddon(), SecondsToTimeString(), ShowDiscoveryMessage(), CONTEXTMENU::ShowFor(), SizeToString(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), ToSettingTimeFormat(), ToTimeFormat(), and update_emu_environ().
Format() [2/2]
template<typename... Args> static constexpr std::wstring KODI::UTILS::StringUtils::Format (std::wstring_view format, Args &&... args) inline static constexpr
References KODI::UTILS::EnumToInt().
FormatFileSize()
std::string KODI::UTILS::StringUtils::FormatFileSize (uint64_t bytes) static
Returns bytes in a human readable format using the smallest unit that will fit bytes in at most three digits. The number of decimals are adjusted with significance such that 'small' numbers will have more decimals than larger ones.
For example: 1024 bytes will be formatted as "1.00kB", 10240 bytes as "10.0kB" and 102400 bytes as "100kB". See TestStringUtils for more examples.
References Format(), and value.
Referenced by TEST().
FormatNumber()
template<typename T > static std::string KODI::UTILS::StringUtils::FormatNumber (T num) inline static
Format the string with locale separators.
Format the string with locale separators. For example 10000.57 in en-us is '10,000.57' but in italian is '10.000,57'
Parameters
param String to format
Returns
Formatted string
References GetOriginalLocale().
FormatV() [1/2]
static std::string KODI::UTILS::StringUtils::FormatV (PRINTF_FORMAT_STRING const char * fmt, va_list args) static
Referenced by dllvprintf(), dvd_logger(), ff_avutil_log(), libass_log(), logFromMHD(), anonymous_namespace{LibInputKeyboard.cpp}::xkbLogger(), and anonymous_namespace{XkbcommonKeymap.cpp}::xkbLogger().
FormatV() [2/2]
static std::wstring KODI::UTILS::StringUtils::FormatV (PRINTF_FORMAT_STRING const wchar_t * fmt, va_list args) static
GetOriginalLocale()
const std::locale & KODI::UTILS::StringUtils::GetOriginalLocale () static private noexcept
Wrapper for CLangInfo::GetOriginalLocale() which allows us to avoid including LangInfo.h from this header.
References g_langInfo.
Referenced by FormatNumber().
isasciialphanum()
static bool KODI::UTILS::StringUtils::isasciialphanum (char chr) inline static
References isasciidigit(), isasciilowercaseletter(), and isasciiuppercaseletter().
isasciidigit()
static bool KODI::UTILS::StringUtils::isasciidigit (char chr) inline static
Referenced by asciidigitvalue(), and isasciialphanum().
isasciilowercaseletter()
static bool KODI::UTILS::StringUtils::isasciilowercaseletter (char chr) inline static
Referenced by isasciialphanum().
isasciiuppercaseletter()
static bool KODI::UTILS::StringUtils::isasciiuppercaseletter (char chr) inline static
Referenced by isasciialphanum().
isasciixdigit()
static bool KODI::UTILS::StringUtils::isasciixdigit (char chr) inline static
IsInteger()
bool KODI::UTILS::StringUtils::IsInteger (const std::string & str) static
check whether a string is an integer. Matches [ \t]*[-]*[0-9]+[ \t]*
Parameters
str the string to check
Returns
true if the string is an integer, false otherwise.
Referenced by anonymous_namespace{SettingConditions.cpp}::GreaterThan(), anonymous_namespace{SettingConditions.cpp}::GreaterThanOrEqual(), anonymous_namespace{SettingConditions.cpp}::LessThan(), anonymous_namespace{SettingConditions.cpp}::LessThanOrEqual(), and TEST().
IsNaturalNumber()
bool KODI::UTILS::StringUtils::IsNaturalNumber (const std::string & str) static
check whether a string is a natural number. Matches [ \t]*[0-9]+[ \t]*
Parameters
str the string to check
Returns
true if the string is a natural number, false otherwise.
Referenced by TEST().
ISODateToLocalizedDate()
std::string KODI::UTILS::StringUtils::ISODateToLocalizedDate (const std::string & strIsoDate) static
References CDateTime::GetAsLocalizedDate(), and CDateTime::SetFromDBDate().
IsSpecialCharacter()
bool KODI::UTILS::StringUtils::IsSpecialCharacter (char c) static
Check if the character is a special character.
A special character is not an alphanumeric character, and is not useful to provide information
Parameters
c Input character to be checked
Referenced by ReplaceSpecialCharactersWithSpace().
Join()
template<typename CONTAINER > static std::string KODI::UTILS::StringUtils::Join (const CONTAINER & strings, const std::string & delimiter) inline static
Referenced by ArrayToString(), ADDON::CAddonSystemSettings::OnSettingAction(), ParseSettingIdentifier(), RunAddon(), TEST(), URLDecodePath(), and URLEncodePath().
Left()
std::string KODI::UTILS::StringUtils::Left (const std::string & str, size_t count) static
Referenced by TEST().
Mid()
std::string KODI::UTILS::StringUtils::Mid (const std::string & str, size_t first, size_t count = std::string::npos) static
Referenced by TEST().
MillisecondsToTimeString()
std::string KODI::UTILS::StringUtils::MillisecondsToTimeString (std::chrono::milliseconds milliSeconds) static
convert a milliseconds value to a time string in the TIME_FORMAT_HH_MM_SS format
Parameters
milliSeconds time in milliseconds
Returns
the formatted time
See also
TIME_FORMAT
References Format(), SecondsToTimeString(), and TIME_FORMAT_HH_MM_SS.
Paramify()
std::string KODI::UTILS::StringUtils::Paramify (const std::string & param) static
Escapes the given string to be able to be used as a parameter.
Escapes backslashes and double-quotes with an additional backslash and adds double-quotes around the whole string.
Parameters
param String to escape/paramify
Returns
Escaped/Paramified string
References Replace().
Referenced by TEST().
RemoveCRLF()
void KODI::UTILS::StringUtils::RemoveCRLF (std::string & strLine) static
References TrimRight().
Referenced by TEST().
RemoveDuplicatedSpacesAndTabs()
std::string & KODI::UTILS::StringUtils::RemoveDuplicatedSpacesAndTabs (std::string & str) static
Replace() [1/3]
int KODI::UTILS::StringUtils::Replace (std::string & str, char oldChar, char newChar) static
Referenced by DeParamify(), dll_findfirst64i32(), Paramify(), SplitTo(), TEST(), TEST_P(), and anonymous_namespace{WebVTTHandler.cpp}::TranslateEscapeChars().
Replace() [2/3]
int KODI::UTILS::StringUtils::Replace (std::string & str, const std::string & oldStr, const std::string & newStr) static
References index().
Replace() [3/3]
int KODI::UTILS::StringUtils::Replace (std::wstring & str, const std::wstring & oldStr, const std::wstring & newStr) static
References index().
ReplaceSpecialCharactersWithSpace()
std::string KODI::UTILS::StringUtils::ReplaceSpecialCharactersWithSpace (const std::string & str) static
References IsSpecialCharacter().
ReturnDigits()
int KODI::UTILS::StringUtils::ReturnDigits (const std::string & str) static
Right()
std::string KODI::UTILS::StringUtils::Right (const std::string & str, size_t count) static
Referenced by TEST().
SecondsToTimeString()
std::string KODI::UTILS::StringUtils::SecondsToTimeString (long seconds, TIME_FORMAT format = TIME_FORMAT_GUESS) static
convert a time in seconds to a string based on the given time format
Parameters
seconds time in seconds
format the format we want the time in.
Returns
the formatted time
See also
TIME_FORMAT
References Format(), TIME_FORMAT_GUESS, TIME_FORMAT_H, TIME_FORMAT_HH, TIME_FORMAT_HH_MM_SS, TIME_FORMAT_HOURS, TIME_FORMAT_M, TIME_FORMAT_MINS, TIME_FORMAT_MM, TIME_FORMAT_MM_SS, TIME_FORMAT_SECS, and TIME_FORMAT_SS.
Referenced by MillisecondsToTimeString(), and TEST().
SizeToString()
std::string KODI::UTILS::StringUtils::SizeToString (int64_t size) static
References Format().
Referenced by TEST().
Split() [1/3]
std::vector< std::string > KODI::UTILS::StringUtils::Split (const std::string & input, const char delimiter, size_t iMaxStrings = 0) static
References SplitTo().
Split() [2/3]
std::vector< std::string > KODI::UTILS::StringUtils::Split (const std::string & input, const std::string & delimiter, unsigned int iMaxStrings = 0) static
Splits the given input string using the given delimiter into separate strings.
If the given input string is empty the result will be an empty array (not an array containing an empty string).
Parameters
input Input string to be split
delimiter Delimiter to be used to split the input string
iMaxStrings (optional) Maximum number of splitted strings
References SplitTo().
Referenced by DateStringToYYYYMMDD(), IsForeign(), KODI::UTILS::CDisplayInfo::IsValid(), ParseSettingIdentifier(), SelectBool(), SplitMulti(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TimeStringToSeconds(), URLDecodePath(), and URLEncodePath().
Split() [3/3]
std::vector< std::string > KODI::UTILS::StringUtils::Split (const std::string & input, const std::vector< std::string > & delimiters) static
References SplitTo().
SplitMulti()
std::vector< std::string > KODI::UTILS::StringUtils::SplitMulti (const std::vector< std::string > & input, const std::vector< std::string > & delimiters, size_t iMaxStrings = 0) static
Splits the given input strings using the given delimiters into further separate strings.
If the given input string vector is empty the result will be an empty array (not an array containing an empty string).
Delimiter strings are applied in order, so once the (optional) maximum number of items is produced no other delimiters are applied. This produces different results to applying all delimiters at once e.g. "a/b#c/d" becomes "a", "b#c", "d" rather than "a", "b", "c/d"
Parameters
input Input vector of strings each to be split
delimiters Delimiter strings to be used to split the input strings
iMaxStrings (optional) Maximum number of resulting split strings
References int64_t(), and Split().
SplitTo() [1/3]
template<typename OutputIt > static OutputIt KODI::UTILS::StringUtils::SplitTo (OutputIt d_first, const std::string & input, const char delimiter, size_t iMaxStrings = 0) inline static
References SplitTo().
SplitTo() [2/3]
template<typename OutputIt > static OutputIt KODI::UTILS::StringUtils::SplitTo (OutputIt d_first, const std::string & input, const std::string & delimiter, unsigned int iMaxStrings = 0) inline static
Splits the given input string using the given delimiter into separate strings.
If the given input string is empty nothing will be put into the target iterator.
Parameters
d_first the beginning of the destination range
input Input string to be split
delimiter Delimiter to be used to split the input string
iMaxStrings (optional) Maximum number of splitted strings
Returns
output iterator to the element in the destination range, one past the last element that was put there
Referenced by Split(), Split(), Split(), SplitTo(), and SplitTo().
SplitTo() [3/3]
template<typename OutputIt > static OutputIt KODI::UTILS::StringUtils::SplitTo (OutputIt d_first, const std::string & input, const std::vector< std::string > & delimiters) inline static
References Replace(), and SplitTo().
StartsWith() [1/3]
bool KODI::UTILS::StringUtils::StartsWith (const char * s1, const char * s2) static
StartsWith() [2/3]
bool KODI::UTILS::StringUtils::StartsWith (const std::string & str1, const char * s2) static
References StartsWith().
StartsWith() [3/3]
bool KODI::UTILS::StringUtils::StartsWith (const std::string & str1, const std::string & str2) static
Referenced by DeParamify(), anonymous_namespace{VideoDatabase.cpp}::GetBasicItemAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetBasicItemAvailableArtTypes(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArtTypes(), anonymous_namespace{TextureCacheJob.cpp}::IsPVROwnedImage(), RunAddon(), anonymous_namespace{TextureCacheJob.cpp}::ShouldCheckForChanges(), StartsWith(), and TEST().
StartsWithNoCase() [1/3]
bool KODI::UTILS::StringUtils::StartsWithNoCase (const char * s1, const char * s2) static
StartsWithNoCase() [2/3]
bool KODI::UTILS::StringUtils::StartsWithNoCase (const std::string & str1, const char * s2) static
References StartsWithNoCase().
StartsWithNoCase() [3/3]
bool KODI::UTILS::StringUtils::StartsWithNoCase (const std::string & str1, const std::string & str2) static
References StartsWithNoCase().
Referenced by ClearPhotoAssetCache(), anonymous_namespace{PVRBuiltins.cpp}::EpgGridControl(), PlayerControl(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), SetFile(), Slideshow(), StartsWithNoCase(), StartsWithNoCase(), and TEST().
TimeStringToSeconds()
long KODI::UTILS::StringUtils::TimeStringToSeconds (const std::string & timeString) static
References EndsWithNoCase(), Split(), and Trim().
Referenced by anonymous_namespace{GUIBuiltins.cpp}::AlarmClock(), and TEST().
ToCapitalize() [1/2]
void KODI::UTILS::StringUtils::ToCapitalize (std::string & str) static
References g_charsetConverter, and ToCapitalize().
Referenced by TEST(), and ToCapitalize().
ToCapitalize() [2/2]
void KODI::UTILS::StringUtils::ToCapitalize (std::wstring & str) static
References g_langInfo.
ToFloat()
float KODI::UTILS::StringUtils::ToFloat (std::string_view str, float fallback = 0.0f) static noexcept
Converts a string to a float number.
Parameters
str The string to convert
fallback [OPT] The number to return when the conversion fails
Returns
The converted number, otherwise fallback if conversion fails
ToHexadecimal()
std::string KODI::UTILS::StringUtils::ToHexadecimal (const std::string & in) static
Convert each character in the string to its hexadecimal representation and return the concatenated result
example: "abc\n" -> "6162630a"
Referenced by TEST().
Tokenize() [1/4]
std::vector< std::string > KODI::UTILS::StringUtils::Tokenize (const std::string & input, const char delimiter) static
References Tokenize().
Tokenize() [2/4]
std::vector< std::string > KODI::UTILS::StringUtils::Tokenize (const std::string & input, const std::string & delimiters) static
Split a string by the specified delimiters. Splits a string using one or more delimiting characters, ignoring empty tokens. Differs from Split() in two ways:
The delimiters are treated as individual characters, rather than a single delimiting string.
Empty tokens are ignored.
Returns
a vector of tokens
References Tokenize().
Referenced by debug_callback(), Tokenize(), and Tokenize().
Tokenize() [3/4]
void KODI::UTILS::StringUtils::Tokenize (const std::string & input, std::vector< std::string > & tokens, const char delimiter) static
Tokenize() [4/4]
void KODI::UTILS::StringUtils::Tokenize (const std::string & input, std::vector< std::string > & tokens, const std::string & delimiters) static
ToLower() [1/4]
std::string KODI::UTILS::StringUtils::ToLower (const std::string & str) static
References KODI::UTILS::transformString().
Referenced by anonymous_namespace{PVRBuiltins.cpp}::EpgGridControl(), anonymous_namespace{GameClient.cpp}::NormalizeExtension(), PlayerControl(), PlayOffset(), SetFile(), StringToSpeedUnit(), StringToTemperatureUnit(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), anonymous_namespace{DVDSubtitleTagSami.cpp}::TranslateColorValue(), and WordToDigits().
ToLower() [2/4]
std::wstring KODI::UTILS::StringUtils::ToLower (const std::wstring & str) static
References KODI::UTILS::tolowerUnicode(), and KODI::UTILS::transformString().
ToLower() [3/4]
void KODI::UTILS::StringUtils::ToLower (std::string & str) static
References KODI::UTILS::transformString().
ToLower() [4/4]
void KODI::UTILS::StringUtils::ToLower (std::wstring & str) static
References KODI::UTILS::tolowerUnicode(), and KODI::UTILS::transformString().
ToUint32()
uint32_t KODI::UTILS::StringUtils::ToUint32 (std::string_view str, uint32_t fallback = 0) static noexcept
Converts a string to a unsigned int number.
Parameters
str The string to convert
fallback [OPT] The number to return when the conversion fails
Returns
The converted number, otherwise fallback if conversion fails
ToUint64()
uint64_t KODI::UTILS::StringUtils::ToUint64 (std::string_view str, uint64_t fallback = 0) static noexcept
Converts a string to a unsigned long long number.
Parameters
str The string to convert
fallback [OPT] The number to return when the conversion fails
Returns
The converted number, otherwise fallback if conversion fails
ToUpper() [1/4]
std::string KODI::UTILS::StringUtils::ToUpper (const std::string & str) static
References KODI::UTILS::transformString().
Referenced by TEST().
ToUpper() [2/4]
std::wstring KODI::UTILS::StringUtils::ToUpper (const std::wstring & str) static
References KODI::UTILS::toupperUnicode(), and KODI::UTILS::transformString().
ToUpper() [3/4]
void KODI::UTILS::StringUtils::ToUpper (std::string & str) static
References KODI::UTILS::transformString().
ToUpper() [4/4]
void KODI::UTILS::StringUtils::ToUpper (std::wstring & str) static
References KODI::UTILS::toupperUnicode(), and KODI::UTILS::transformString().
Trim() [1/2]
std::string & KODI::UTILS::StringUtils::Trim (std::string & str) static
References TrimLeft(), and TrimRight().
Referenced by anonymous_namespace{ExecString.cpp}::SplitExecFunction(), TEST(), TEST(), TEST(), TEST(), and TimeStringToSeconds().
Trim() [2/2]
std::string & KODI::UTILS::StringUtils::Trim (std::string & str, const char *const chars) static
References TrimLeft(), and TrimRight().
TrimLeft() [1/2]
std::string & KODI::UTILS::StringUtils::TrimLeft (std::string & str) static
Referenced by TEST(), Trim(), and Trim().
TrimLeft() [2/2]
std::string & KODI::UTILS::StringUtils::TrimLeft (std::string & str, const char *const chars) static
TrimRight() [1/2]
std::string & KODI::UTILS::StringUtils::TrimRight (std::string & str) static
Referenced by PlayerControl(), RemoveCRLF(), TEST(), Trim(), Trim(), VAAPI::VaErrorCallback(), and VAAPI::VaInfoCallback().
TrimRight() [2/2]
std::string & KODI::UTILS::StringUtils::TrimRight (std::string & str, const char *const chars) static
utf8_strlen()
size_t KODI::UTILS::StringUtils::utf8_strlen (const char * s) static
utf8 version of strlen - skips any non-starting bytes in the count, thus returning the number of utf8 characters
Parameters
s c-string to find the length of.
Returns
the number of utf8 characters in the string.
Referenced by TEST().
ValidateUUID()
bool KODI::UTILS::StringUtils::ValidateUUID (const std::string & uuid) static
References KODI::UTILS::ADDON_GUID_RE, CRegExp::RegComp(), and CRegExp::RegFind().
Referenced by TEST().
WordToDigits()
void KODI::UTILS::StringUtils::WordToDigits (std::string & word) static
References ToLower().
Referenced by TEST().
Member Data Documentation
Empty
const std::string KODI::UTILS::StringUtils::Empty = "" static
Referenced by TEST(), and TypeToString().
The documentation for this class was generated from the following files:
utils/StringUtils.h
StringUtils.cpp