Kodi Documentation: CHDRCapabilities Class Reference
CHDRCapabilities Class Reference
#include <HDRCapabilities.h>
Public Member Functions
CHDRCapabilities ()=default
~CHDRCapabilities ()=default
bool SupportsHDR10 () const
bool SupportsHLG () const
bool SupportsHDR10Plus () const
bool SupportsDolbyVision () const
void SetHDR10 ()
void SetHLG ()
void SetHDR10Plus ()
void SetDolbyVision ()
Private Attributes
bool m_hdr10 = false
bool m_hlg = false
bool m_hdr10_plus = false
bool m_dolby_vision = false
Constructor & Destructor Documentation
CHDRCapabilities()
CHDRCapabilities::CHDRCapabilities () default
~CHDRCapabilities()
CHDRCapabilities::~CHDRCapabilities () default
Member Function Documentation
SetDolbyVision()
void CHDRCapabilities::SetDolbyVision () inline
References m_dolby_vision.
Referenced by CAndroidUtils::GetDisplayHDRCapabilities().
SetHDR10()
void CHDRCapabilities::SetHDR10 () inline
References m_hdr10.
Referenced by CAndroidUtils::GetDisplayHDRCapabilities(), and KODI::WINDOWING::GBM::CWinSystemGbm::GetDisplayHDRCapabilities().
SetHDR10Plus()
void CHDRCapabilities::SetHDR10Plus () inline
References m_hdr10_plus.
Referenced by CAndroidUtils::GetDisplayHDRCapabilities().
SetHLG()
void CHDRCapabilities::SetHLG () inline
References m_hlg.
Referenced by CAndroidUtils::GetDisplayHDRCapabilities(), and KODI::WINDOWING::GBM::CWinSystemGbm::GetDisplayHDRCapabilities().
SupportsDolbyVision()
bool CHDRCapabilities::SupportsDolbyVision () const inline
References m_dolby_vision.
Referenced by CAndroidUtils::GetDolbyVisionCapabilities(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), and anonymous_namespace{SettingConditions.cpp}::SupportsDolbyVision().
SupportsHDR10()
bool CHDRCapabilities::SupportsHDR10 () const inline
References m_hdr10.
SupportsHDR10Plus()
bool CHDRCapabilities::SupportsHDR10Plus () const inline
References m_hdr10_plus.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel().
SupportsHLG()
bool CHDRCapabilities::SupportsHLG () const inline
References m_hlg.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel().
Member Data Documentation
m_dolby_vision
bool CHDRCapabilities::m_dolby_vision = false private
Referenced by SetDolbyVision(), and SupportsDolbyVision().
m_hdr10
bool CHDRCapabilities::m_hdr10 = false private
Referenced by SetHDR10(), and SupportsHDR10().
m_hdr10_plus
bool CHDRCapabilities::m_hdr10_plus = false private
Referenced by SetHDR10Plus(), and SupportsHDR10Plus().
m_hlg
bool CHDRCapabilities::m_hlg = false private
Referenced by SetHLG(), and SupportsHLG().
The documentation for this class was generated from the following file:
HDRCapabilities.h