Kodi Documentation: OpticalBuiltins.cpp File Reference
OpticalBuiltins.cpp File Reference
#include "OpticalBuiltins.h"
#include "ServiceBroker.h"
Functions
static int Eject (const std::vector< std::string > &params)
Eject the tray of an optical drive.
static int RipCD (const std::vector< std::string > &params)
Rip currently inserted CD.
Function Documentation
Eject()
static int Eject (const std::vector< std::string > & params) static
Eject the tray of an optical drive.
Parameters
params (ignored)
References CServiceBroker::GetMediaManager(), and CMediaManager::ToggleTray().
Referenced by COpticalBuiltins::GetOperations().
RipCD()
static int RipCD (const std::vector< std::string > & params) static
Rip currently inserted CD.
Parameters
params (ignored)
References KODI::CDRIP::CCDDARipper::GetInstance(), and KODI::CDRIP::CCDDARipper::RipCD().
Referenced by COpticalBuiltins::GetOperations().