Kodi Documentation: CDRMPRIMETexture Class Reference
CDRMPRIMETexture Class Reference
#include <DRMPRIMEEGL.h>
Public Member Functions
CDRMPRIMETexture ()=default
~CDRMPRIMETexture ()
bool Map (CVideoBufferDRMPRIME *buffer)
void Unmap ()
void Init (EGLDisplay eglDisplay)
GLuint GetTexture ()
CSizeInt GetTextureSize ()
Protected Attributes
CVideoBufferDRMPRIME * m_primebuffer {nullptr}
std::unique_ptr< CEGLImage > m_eglImage
const GLenum m_textureTarget {GL_TEXTURE_EXTERNAL_OES}
GLuint m_texture {0}
int m_texWidth {0}
int m_texHeight {0}
Constructor & Destructor Documentation
CDRMPRIMETexture()
CDRMPRIMETexture::CDRMPRIMETexture () default
~CDRMPRIMETexture()
CDRMPRIMETexture::~CDRMPRIMETexture ()
References m_texture.
Member Function Documentation
GetTexture()
GLuint CDRMPRIMETexture::GetTexture () inline
References m_texture.
Referenced by CRendererDRMPRIMEGLES::Render().
GetTextureSize()
CSizeInt CDRMPRIMETexture::GetTextureSize () inline
References m_texHeight, and m_texWidth.
Init()
void CDRMPRIMETexture::Init (EGLDisplay eglDisplay)
References m_eglImage.
Map()
bool CDRMPRIMETexture::Map (CVideoBufferDRMPRIME * buffer)
References CVideoBuffer::Acquire(), CEGLImage::EglAttrs::colorRange, CEGLImage::EglAttrs::colorSpace, CEGLImage::EglAttrs::format, CEGLImage::EglAttrs::height, CLog::Log(), LOGERROR, m_eglImage, m_primebuffer, m_texHeight, m_texture, m_textureTarget, m_texWidth, CEGLImage::EglAttrs::planes, and CEGLImage::EglAttrs::width.
Referenced by CRendererDRMPRIMEGLES::Render().
Unmap()
void CDRMPRIMETexture::Unmap ()
References m_eglImage, m_primebuffer, CVideoBuffer::Release(), and CVideoBufferDRMPRIME::ReleaseDescriptor().
Referenced by CRendererDRMPRIMEGLES::AddVideoPicture(), and CRendererDRMPRIMEGLES::ReleaseBuffer().
Member Data Documentation
m_eglImage
std::unique_ptr<CEGLImage> CDRMPRIMETexture::m_eglImage protected
Referenced by Init(), Map(), and Unmap().
m_primebuffer
CVideoBufferDRMPRIME* CDRMPRIMETexture::m_primebuffer {nullptr} protected
Referenced by Map(), and Unmap().
m_texHeight
int CDRMPRIMETexture::m_texHeight {0} protected
Referenced by GetTextureSize(), and Map().
m_texture
GLuint CDRMPRIMETexture::m_texture {0} protected
Referenced by GetTexture(), Map(), and ~CDRMPRIMETexture().
m_textureTarget
const GLenum CDRMPRIMETexture::m_textureTarget {GL_TEXTURE_EXTERNAL_OES} protected
Referenced by Map().
m_texWidth
int CDRMPRIMETexture::m_texWidth {0} protected
Referenced by GetTextureSize(), and Map().
The documentation for this class was generated from the following files:
DRMPRIMEEGL.h
DRMPRIMEEGL.cpp