Kodi Documentation: XFILE::CVideoDatabaseDirectory Class Reference
XFILE::CVideoDatabaseDirectory Class Reference
#include <VideoDatabaseDirectory.h>
Public Member Functions
CVideoDatabaseDirectory (void)
~CVideoDatabaseDirectory (void) override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool Exists (const CURL &url) override
Check for directory existence.
bool AllowAll () const override
Whether to allow all files/folders to be listed.
void ClearDirectoryCache (const std::string &strDirectory)
bool ContainsMovies (const std::string &path)
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool Create (const CURL &url)
Create the directory.
virtual bool Remove (const CURL &url)
Removes the directory.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Static Public Member Functions
static VIDEODATABASEDIRECTORY::NODE_TYPE GetDirectoryChildType (const std::string &strPath)
static VIDEODATABASEDIRECTORY::NODE_TYPE GetDirectoryType (const std::string &strPath)
static VIDEODATABASEDIRECTORY::NODE_TYPE GetDirectoryParentType (const std::string &strPath)
static bool GetQueryParams (const std::string &strPath, VIDEODATABASEDIRECTORY::CQueryParams &params)
static bool IsAllItem (const std::string &strDirectory)
static bool GetLabel (const std::string &strDirectory, std::string &strLabel)
static std::string GetIcon (const std::string &strDirectory)
static bool CanCache (const std::string &path)
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Additional Inherited Members
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CVideoDatabaseDirectory()
CVideoDatabaseDirectory::CVideoDatabaseDirectory (void) default
~CVideoDatabaseDirectory()
CVideoDatabaseDirectory::~CVideoDatabaseDirectory (void) override default
Member Function Documentation
AllowAll()
bool XFILE::CVideoDatabaseDirectory::AllowAll () const inline override virtual
Whether to allow all files/folders to be listed.
Returns
Returns true if all files/folder should be listed.
Reimplemented from XFILE::IDirectory.
CanCache()
bool CVideoDatabaseDirectory::CanCache (const std::string & path) static
References XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateVideoDbPath().
Referenced by CFileItemList::AlwaysCache().
ClearDirectoryCache()
void CVideoDatabaseDirectory::ClearDirectoryCache (const std::string & strDirectory)
References Crc32::ComputeFromLowerCase(), XFILE::CFile::Delete(), URIUtils::RemoveSlashAtEnd(), and CLegacyPathTranslation::TranslateVideoDbPath().
ContainsMovies()
bool CVideoDatabaseDirectory::ContainsMovies (const std::string & path)
References GetDirectoryChildType(), XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MUSICVIDEOS, and XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_VIDEOVERSIONS.
Exists()
bool CVideoDatabaseDirectory::Exists (const CURL & url) override virtual
Check for directory existence.
Parameters
url Directory to check.
Returns
Returns true, if directory exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
References XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateVideoDbPath().
GetDirectory()
bool CVideoDatabaseDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References CVariant::asString(), CServiceBroker::GetGUI(), GetIcon(), CGUIListItem::GetProperty(), CGUIComponent::GetTextureManager(), CGUIListItem::HasProperty(), CGUITextureManager::HasTexture(), CFileItem::m_dwSize, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), CFileItemList::SetContent(), CFileItem::SetLabel(), CFileItem::SetPath(), CFileItemList::Size(), and CLegacyPathTranslation::TranslateVideoDbPath().
GetDirectoryChildType()
NODE_TYPE CVideoDatabaseDirectory::GetDirectoryChildType (const std::string & strPath) static
References XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateVideoDbPath().
Referenced by CGUIWindowVideoNav::ApplyWatchedFilter(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), ContainsMovies(), CGUIWindowVideoNav::GetContextButtons(), CGUIWindowMusicNav::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CGUIWindowVideoNav::GetFirstUnwatchedItemIndex(), CGUIWindowVideoBase::GetGroupedItems(), GetIcon(), CGUIWindowVideoNav::GetSettingSelectFirstUnwatchedItem(), CVideoDbUrl::parse(), and CGUIViewStateWindowVideoNav::SaveViewState().
GetDirectoryParentType()
NODE_TYPE CVideoDatabaseDirectory::GetDirectoryParentType (const std::string & strPath) static
References XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetChildType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetParent(), XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateVideoDbPath().
Referenced by KODI::VIDEO::UTILS::IsItemPlayable().
GetDirectoryType()
NODE_TYPE CVideoDatabaseDirectory::GetDirectoryType (const std::string & strPath) static
References XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateVideoDbPath().
Referenced by UPNP::BuildObject(), and CVideoDbUrl::parse().
GetIcon()
std::string CVideoDatabaseDirectory::GetIcon (const std::string & strDirectory) static
References GetDirectoryChildType(), CServiceBroker::GetSettingsComponent(), XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ACTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_COUNTRY, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_DIRECTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_INPROGRESS_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MOVIES_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_ALBUM, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SETS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_STUDIO, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TAGS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TVSHOWS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_VIDEOVERSIONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_YEAR, URIUtils::PathEquals(), CSettings::SETTING_MYVIDEOS_FLATTEN, and CLegacyPathTranslation::TranslateVideoDbPath().
Referenced by GetDirectory().
GetLabel()
bool CVideoDatabaseDirectory::GetLabel (const std::string & strDirectory, std::string & strLabel) static
References g_localizeStrings, CLocalizeStrings::Get(), CVideoDatabase::GetCountryById(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetCountryId(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), CVideoDatabase::GetGenreById(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetGenreId(), CVideoDatabase::GetSetById(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSetId(), CVideoDatabase::GetTagById(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetTagId(), CVideoDatabase::GetVideoVersionById(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetVideoVersionId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetYear(), XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ACTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_COUNTRY, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_DIRECTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_INPROGRESS_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MOVIES_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SEASONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SETS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_STUDIO, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TAGS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TVSHOWS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_VIDEOVERSIONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_YEAR, CVideoDatabase::Open(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateVideoDbPath().
Referenced by UPNP::CUPnPServer::Build(), and CGUIWindowVideoNav::UpdateButtons().
GetQueryParams()
bool CVideoDatabaseDirectory::GetQueryParams (const std::string & strPath, VIDEODATABASEDIRECTORY::CQueryParams & params) static
References XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateVideoDbPath().
Referenced by CGUIViewStateWindowVideoNav::AutoPlayNextItem(), CGUIDialogVideoInfo::CanDeleteVideoItem(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), CGUIWindowVideoNav::GetDirectory(), CGUIWindowVideoBase::GetGroupedItems(), CFileItem::GetVideoContentType(), CGUIWindowVideoNav::OnDeleteItem(), CVideoDbUrl::parse(), and CGUIViewStateWindowVideoNav::SaveViewState().
IsAllItem()
bool CVideoDatabaseDirectory::IsAllItem (const std::string & strDirectory) static
Referenced by CGUIDialogVideoInfo::CanDeleteVideoItem(), and CGUIWindowVideoNav::GetContextButtons().
The documentation for this class was generated from the following files:
VideoDatabaseDirectory.h
VideoDatabaseDirectory.cpp