Kodi Documentation: CDVDVideoCodecDRMPRIME Class Reference
CDVDVideoCodecDRMPRIME Class Reference
#include <DVDVideoCodecDRMPRIME.h>
Public Member Functions
CDVDVideoCodecDRMPRIME (CProcessInfo &processInfo)
~CDVDVideoCodecDRMPRIME () override
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
bool AddData (const DemuxPacket &packet) override
void Reset () override
CDVDVideoCodec::VCReturn GetPicture (VideoPicture *pVideoPicture) override
const char * GetName () override
unsigned GetAllowedReferences () override
void SetCodecControl (int flags) override
Public Member Functions inherited from CDVDVideoCodec
CDVDVideoCodec (CProcessInfo &processInfo)
virtual ~CDVDVideoCodec ()=default
virtual bool Reconfigure (CDVDStreamInfo &hints)
virtual void SetSpeed (int iSpeed)
virtual unsigned GetConvergeCount ()
virtual bool GetCodecStats (double &pts, int &droppedFrames, int &skippedPics)
virtual void Reopen ()
Static Public Member Functions
static std::unique_ptr< CDVDVideoCodec > Create (CProcessInfo &processInfo)
static void Register ()
Protected Member Functions
void Drain ()
void SetPictureParams (VideoPicture *pVideoPicture)
void UpdateProcessInfo (struct AVCodecContext *avctx, const enum AVPixelFormat fmt)
Static Protected Member Functions
static enum AVPixelFormat GetFormat (struct AVCodecContext *avctx, const enum AVPixelFormat *fmt)
static int GetBuffer (struct AVCodecContext *avctx, AVFrame *frame, int flags)
Protected Attributes
std::string m_name
int m_codecControlFlags = 0
CDVDStreamInfo m_hints
double m_DAR = 1.0
AVCodecContext * m_pCodecContext = nullptr
AVFrame * m_pFrame = nullptr
std::shared_ptr< IVideoBufferPool > m_videoBufferPool
Protected Attributes inherited from CDVDVideoCodec
CProcessInfo & m_processInfo
Additional Inherited Members
Public Types inherited from CDVDVideoCodec
enum VCReturn {
VC_NONE = 0 , VC_ERROR , VC_FATAL , VC_BUFFER ,
VC_PICTURE , VC_FLUSHED , VC_NOBUFFER , VC_REOPEN ,
VC_EOF
}
Constructor & Destructor Documentation
CDVDVideoCodecDRMPRIME()
CDVDVideoCodecDRMPRIME::CDVDVideoCodecDRMPRIME (CProcessInfo & processInfo) explicit
References m_pFrame, and m_videoBufferPool.
~CDVDVideoCodecDRMPRIME()
CDVDVideoCodecDRMPRIME::~CDVDVideoCodecDRMPRIME () override
References m_pCodecContext, and m_pFrame.
Member Function Documentation
AddData()
bool CDVDVideoCodecDRMPRIME::AddData (const DemuxPacket & packet) override virtual
add data, decoder has to consume the entire packet returns true if the packet was consumed or if resubmitting it is useless
Todo:
: properly handle avpkt side_data. this works around our improper use of the side_data
Implements CDVDVideoCodec.
References DEMUX_PACKET::dts, DVD_NOPTS_VALUE, DVD_TIME_BASE, err(), int64_t(), DEMUX_PACKET::iSideDataElems, DEMUX_PACKET::iSize, CLog::Log(), LOGERROR, m_pCodecContext, DEMUX_PACKET::pData, DEMUX_PACKET::pSideData, and DEMUX_PACKET::pts.
Create()
std::unique_ptr< CDVDVideoCodec > CDVDVideoCodecDRMPRIME::Create (CProcessInfo & processInfo) static
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOPLAYER_USEPRIMEDECODER.
Referenced by Register().
Drain()
void CDVDVideoCodecDRMPRIME::Drain () protected
References err(), CLog::Log(), LOGERROR, and m_pCodecContext.
Referenced by GetPicture(), and Reset().
GetAllowedReferences()
unsigned CDVDVideoCodecDRMPRIME::GetAllowedReferences () inline override virtual
Number of references to old pictures that are allowed to be retained when calling decode on the next demux packet
Reimplemented from CDVDVideoCodec.
GetBuffer()
int CDVDVideoCodecDRMPRIME::GetBuffer (struct AVCodecContext * avctx, AVFrame * frame, int flags) static protected
References CVideoBufferManager::Get(), CProcessInfo::GetVideoBufferManager(), IsSupportedSwFormat(), and CDVDVideoCodec::m_processInfo.
Referenced by Open().
GetFormat()
enum AVPixelFormat CDVDVideoCodecDRMPRIME::GetFormat (struct AVCodecContext * avctx, const enum AVPixelFormat * fmt) static protected
References formats, IsSupportedHwFormat(), IsSupportedSwFormat(), CLog::Log(), LOGERROR, and UpdateProcessInfo().
Referenced by Open().
GetName()
const char * CDVDVideoCodecDRMPRIME::GetName () inline override virtual
should return codecs name
Implements CDVDVideoCodec.
References m_name.
GetPicture()
CDVDVideoCodec::VCReturn CDVDVideoCodecDRMPRIME::GetPicture (VideoPicture * pVideoPicture) override virtual
GetPicture controls decoding. Player calls it on every cycle it can signal a picture, request a buffer, or return none, if nothing applies the data is valid until the next GetPicture return VC_PICTURE
Implements CDVDVideoCodec.
References Drain(), DVD_CODEC_CTRL_DRAIN, err(), IsSupportedHwFormat(), CLog::Log(), LOGDEBUG, LOGERROR, m_codecControlFlags, m_pCodecContext, m_pFrame, m_videoBufferPool, CVideoBuffer::Release(), SetCodecControl(), CVideoBufferDRMPRIME::SetPictureParams(), SetPictureParams(), CDVDVideoCodec::VC_BUFFER, CDVDVideoCodec::VC_EOF, CDVDVideoCodec::VC_ERROR, CDVDVideoCodec::VC_PICTURE, and VideoPicture::videoBuffer.
Open()
bool CDVDVideoCodecDRMPRIME::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Open the decoder, returns true on success Decoders not capable of running multiple instances should return false in case there is already a instance open
Todo:
: fix with proper device when dma-hints wayland protocol works
Implements CDVDVideoCodec.
References CDVDStreamInfo::aspect, CDVDStreamInfo::bitsperpixel, CDVDStreamInfo::codec, CODEC_FORCE_SOFTWARE, CDVDStreamInfo::codec_tag, CDVDStreamInfo::codecOptions, DVD_TIME_BASE, CDVDStreamInfo::extradata, FindDecoder(), FindHWConfig(), GetBuffer(), CServiceBroker::GetCPUInfo(), FFmpegExtraData::GetData(), KODI::WINDOWING::GBM::CWinSystemGbm::GetDrm(), GetFormat(), FFmpegExtraData::GetSize(), CServiceBroker::GetWinSystem(), CDVDStreamInfo::height, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_hints, m_pCodecContext, CDVDVideoCodec::m_processInfo, Open(), CProcessInfo::SetVideoDAR(), CProcessInfo::SetVideoDeintMethod(), UpdateProcessInfo(), and CDVDStreamInfo::width.
Referenced by Open().
Register()
void CDVDVideoCodecDRMPRIME::Register () static
References Create(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, LOGINFO, CDVDFactoryCodec::RegisterHWVideoCodec(), and CSettings::SETTING_VIDEOPLAYER_USEPRIMEDECODER.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::InitWindowSystem().
Reset()
void CDVDVideoCodecDRMPRIME::Reset () override virtual
Reset the decoder. Should be the same as calling Dispose and Open after each other
Implements CDVDVideoCodec.
References Drain(), err(), CLog::Log(), LOGDEBUG, LOGERROR, m_pCodecContext, and m_pFrame.
SetCodecControl()
void CDVDVideoCodecDRMPRIME::SetCodecControl (int flags) override virtual
Codec can be informed by player with the following flags:
DVD_CODEC_CTRL_NO_POSTPROC : if speed is not normal the codec can switch off postprocessing and de-interlacing
DVD_CODEC_CTRL_HURRY : codecs may do postprocessing and de-interlacing. If video buffers in RenderManager are about to run dry, this is signaled to codec. Codec can wait for post-proc to be finished instead of returning empty and getting another packet.
DVD_CODEC_CTRL_DRAIN : instruct decoder to deliver last pictures without requesting new packets
DVD_CODEC_CTRL_DROP : this packet is going to be dropped. decoder is free to use it for decoding
Reimplemented from CDVDVideoCodec.
References DVD_CODEC_CTRL_DROP_ANY, m_codecControlFlags, and m_pCodecContext.
Referenced by GetPicture().
SetPictureParams()
void CDVDVideoCodecDRMPRIME::SetPictureParams (VideoPicture * pVideoPicture) protected
References VideoPicture::chroma_position, VideoPicture::color_primaries, VideoPicture::color_range, VideoPicture::color_space, VideoPicture::color_transfer, VideoPicture::colorBits, CDVDStreamInfo::colorPrimaries, CDVDStreamInfo::colorRange, CDVDStreamInfo::colorSpace, CDVDStreamInfo::colorTransferCharacteristic, CDVDStreamInfo::contentLightMetadata, VideoPicture::displayMetadata, VideoPicture::dts, DVD_CODEC_CTRL_DROP, DVD_NOPTS_VALUE, DVD_TIME_BASE, DVP_FLAG_DROPPED, DVP_FLAG_INTERLACED, DVP_FLAG_TOP_FIELD_FIRST, VideoPicture::hasDisplayMetadata, VideoPicture::hasLightMetadata, VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iFlags, VideoPicture::iHeight, int64_t(), VideoPicture::iRepeatPicture, VideoPicture::iWidth, VideoPicture::lightMetadata, m_codecControlFlags, m_DAR, m_hints, m_pCodecContext, m_pFrame, CDVDVideoCodec::m_processInfo, CDVDStreamInfo::masteringMetadata, VideoPicture::pts, and CProcessInfo::SetVideoDAR().
Referenced by GetPicture().
UpdateProcessInfo()
void CDVDVideoCodecDRMPRIME::UpdateProcessInfo (struct AVCodecContext * avctx, const enum AVPixelFormat fmt) protected
References IsSupportedHwFormat(), m_name, CDVDVideoCodec::m_processInfo, CProcessInfo::SetVideoDecoderName(), CProcessInfo::SetVideoDimensions(), and CProcessInfo::SetVideoPixelFormat().
Referenced by GetFormat(), and Open().
Member Data Documentation
m_codecControlFlags
int CDVDVideoCodecDRMPRIME::m_codecControlFlags = 0 protected
Referenced by GetPicture(), SetCodecControl(), and SetPictureParams().
m_DAR
double CDVDVideoCodecDRMPRIME::m_DAR = 1.0 protected
Referenced by SetPictureParams().
m_hints
CDVDStreamInfo CDVDVideoCodecDRMPRIME::m_hints protected
Referenced by Open(), and SetPictureParams().
m_name
std::string CDVDVideoCodecDRMPRIME::m_name protected
Referenced by GetName(), and UpdateProcessInfo().
m_pCodecContext
AVCodecContext* CDVDVideoCodecDRMPRIME::m_pCodecContext = nullptr protected
Referenced by AddData(), Drain(), GetPicture(), Open(), Reset(), SetCodecControl(), SetPictureParams(), and ~CDVDVideoCodecDRMPRIME().
m_pFrame
AVFrame* CDVDVideoCodecDRMPRIME::m_pFrame = nullptr protected
Referenced by CDVDVideoCodecDRMPRIME(), GetPicture(), Reset(), SetPictureParams(), and ~CDVDVideoCodecDRMPRIME().
m_videoBufferPool
std::shared_ptr<IVideoBufferPool> CDVDVideoCodecDRMPRIME::m_videoBufferPool protected
Referenced by CDVDVideoCodecDRMPRIME(), and GetPicture().
The documentation for this class was generated from the following files:
DVDVideoCodecDRMPRIME.h
DVDVideoCodecDRMPRIME.cpp