Kodi Documentation: CHTTPImageTransformationHandler Class Reference
CHTTPImageTransformationHandler Class Reference
#include <HTTPImageTransformationHandler.h>
Public Member Functions
CHTTPImageTransformationHandler ()
~CHTTPImageTransformationHandler () override
IHTTPRequestHandler * Create (const HTTPRequest &request) const override
Creates a new HTTP request handler for the given request.
bool CanHandleRequest (const HTTPRequest &request) const override
Checks if the HTTP request handler can handle the given request.
MHD_RESULT HandleRequest () override
Handles the HTTP request.
bool CanHandleRanges () const override
Whether the HTTP response could also be provided in ranges.
bool CanBeCached () const override
Whether the HTTP response can be cached.
bool GetLastModifiedDate (CDateTime &lastModified) const override
Returns the last modification date of the response data.
HttpResponseRanges GetResponseData () const override
Returns the ranges with raw data belonging to the response.
int GetPriority () const override
Returns the priority of the HTTP request handler.
Public Member Functions inherited from IHTTPRequestHandler
virtual ~IHTTPRequestHandler ()=default
virtual int GetMaximumAgeForCaching () const
Returns the maximum age (in seconds) for which the response can be cached.
virtual std::string GetRedirectUrl () const
Returns the URL to which the request should be redirected.
virtual std::string GetResponseFile () const
Returns the path to the file that should be returned as the response.
const HTTPRequest & GetRequest () const
Returns the HTTP request handled by the HTTP request handler.
bool IsRequestRanged () const
Returns true if the HTTP request is ranged, otherwise false.
void SetRequestRanged (bool ranged)
Sets whether the HTTP request contains ranges or not.
void SetResponseStatus (int status)
Sets the response status of the HTTP response.
bool HasResponseHeader (const std::string &field) const
Checks if the given HTTP header field is part of the response details.
bool AddResponseHeader (const std::string &field, const std::string &value, bool allowMultiple=false)
Adds the given HTTP header field and value to the response details.
const HTTPResponseDetails & GetResponseDetails () const
Returns the HTTP response header details.
void AddPostField (const std::string &key, const std::string &value)
Adds the given key-value pair extracted from the HTTP POST data.
bool AddPostData (const char *data, size_t size)
Adds the given raw HTTP POST data.
Protected Member Functions
CHTTPImageTransformationHandler (const HTTPRequest &request)
Protected Member Functions inherited from IHTTPRequestHandler
IHTTPRequestHandler ()
IHTTPRequestHandler (const HTTPRequest &request)
virtual bool appendPostData (const char *data, size_t size)
bool GetRequestedRanges (uint64_t totalLength)
bool GetHostnameAndPort (std::string &hostname, uint16_t &port)
Private Attributes
std::string m_url
CDateTime m_lastModified
uint8_t * m_buffer
HttpResponseRanges m_responseData
Additional Inherited Members
Protected Attributes inherited from IHTTPRequestHandler
HTTPRequest m_request
HTTPResponseDetails m_response
std::map< std::string, std::string > m_postFields
Constructor & Destructor Documentation
CHTTPImageTransformationHandler() [1/2]
CHTTPImageTransformationHandler::CHTTPImageTransformationHandler ()
Referenced by Create().
~CHTTPImageTransformationHandler()
CHTTPImageTransformationHandler::~CHTTPImageTransformationHandler () override
References m_buffer, and m_responseData.
CHTTPImageTransformationHandler() [2/2]
CHTTPImageTransformationHandler::CHTTPImageTransformationHandler (const HTTPRequest & request) explicit protected
Todo:
determine the maximum age
References __stat64, HTTPResponseDetails::contentType, XFILE::CImageFile::Exists(), URIUtils::GetExtension(), CURL::GetHostName(), CMime::GetMimeType(), HTTPError, HTTPMemoryDownloadNoFreeCopy, ImageBasePath, m_lastModified, IHTTPRequestHandler::m_request, IHTTPRequestHandler::m_response, m_url, HTTPRequest::pathUrl, XFILE::CImageFile::Stat(), HTTPResponseDetails::status, and HTTPResponseDetails::type.
Member Function Documentation
CanBeCached()
bool CHTTPImageTransformationHandler::CanBeCached () const inline override virtual
Whether the HTTP response can be cached.
Reimplemented from IHTTPRequestHandler.
CanHandleRanges()
bool CHTTPImageTransformationHandler::CanHandleRanges () const inline override virtual
Whether the HTTP response could also be provided in ranges.
Reimplemented from IHTTPRequestHandler.
CanHandleRequest()
bool CHTTPImageTransformationHandler::CanHandleRequest (const HTTPRequest & request) const override virtual
Checks if the HTTP request handler can handle the given request.
Parameters
request HTTP request to be handled
Returns
True if the given HTTP request can be handled otherwise false.
Implements IHTTPRequestHandler.
References HTTPRequest::connection, GET, HTTPRequestHandlerUtils::GetRequestHeaderValues(), HEAD, ImageBasePath, HTTPRequest::method, HTTPRequest::pathUrl, TRANSFORMATION_OPTION_HEIGHT, and TRANSFORMATION_OPTION_WIDTH.
Create()
IHTTPRequestHandler * CHTTPImageTransformationHandler::Create (const HTTPRequest & request) const inline override virtual
Creates a new HTTP request handler for the given request.
This call is responsible for doing some preparation work like - depending on the supported features - determining whether the requested entity supports ranges, whether it can be cached and what it's last modified date is.
Parameters
request HTTP request to be handled
Implements IHTTPRequestHandler.
References CHTTPImageTransformationHandler().
GetLastModifiedDate()
bool CHTTPImageTransformationHandler::GetLastModifiedDate (CDateTime & lastModified) const override virtual
Returns the last modification date of the response data.
This is only used if the response can be cached.
Reimplemented from IHTTPRequestHandler.
References CDateTime::IsValid(), and m_lastModified.
GetPriority()
int CHTTPImageTransformationHandler::GetPriority () const inline override virtual
Returns the priority of the HTTP request handler.
The higher the priority the more important is the HTTP request handler.
Reimplemented from IHTTPRequestHandler.
GetResponseData()
HttpResponseRanges CHTTPImageTransformationHandler::GetResponseData () const inline override virtual
Returns the ranges with raw data belonging to the response.
This is only used if the response type is one of the HTTPMemoryDownload types.
Reimplemented from IHTTPRequestHandler.
References m_responseData.
HandleRequest()
MHD_RESULT CHTTPImageTransformationHandler::HandleRequest () override virtual
Handles the HTTP request.
Returns
MHD_NO if a severe error has occurred otherwise MHD_YES.
Implements IHTTPRequestHandler.
References CHttpRanges::Begin(), HTTPRequest::connection, CHttpRanges::End(), CPictureScalingAlgorithm::FromString(), IHTTPRequestHandler::GetRequestedRanges(), HTTPRequestHandlerUtils::GetRequestHeaderValues(), HTTPError, m_buffer, IHTTPRequestHandler::m_request, IHTTPRequestHandler::m_response, m_responseData, m_url, CPictureScalingAlgorithm::NoAlgorithm, HTTPRequest::ranges, CTextureCacheJob::ResizeTexture(), HTTPResponseDetails::status, HTTPResponseDetails::totalLength, TRANSFORMATION_OPTION_HEIGHT, TRANSFORMATION_OPTION_SCALING_ALGORITHM, TRANSFORMATION_OPTION_WIDTH, and HTTPResponseDetails::type.
Member Data Documentation
m_buffer
uint8_t* CHTTPImageTransformationHandler::m_buffer private
Referenced by HandleRequest(), and ~CHTTPImageTransformationHandler().
m_lastModified
CDateTime CHTTPImageTransformationHandler::m_lastModified private
Referenced by CHTTPImageTransformationHandler(), and GetLastModifiedDate().
m_responseData
HttpResponseRanges CHTTPImageTransformationHandler::m_responseData private
Referenced by GetResponseData(), HandleRequest(), and ~CHTTPImageTransformationHandler().
m_url
std::string CHTTPImageTransformationHandler::m_url private
Referenced by CHTTPImageTransformationHandler(), and HandleRequest().
The documentation for this class was generated from the following files:
HTTPImageTransformationHandler.h
HTTPImageTransformationHandler.cpp