Kodi Documentation: class PVRTypeStringValue
class PVRTypeStringValue
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General
PVR add-on string type value
Representation of a <std::string, std::string> value.
Modules
Value Help
Classes
class kodi::addon::PVRTypeStringValue
Functions
kodi::addon::PVRTypeStringValue::PVRTypeStringValue ()=default
Default class constructor.
kodi::addon::PVRTypeStringValue::PVRTypeStringValue (const std::string &value, const std::string &description)
Class constructor with integrated value set.
void kodi::addon::PVRTypeStringValue::SetValue (const std::string &value)
To set with the identification value.
std::string kodi::addon::PVRTypeStringValue::GetValue () const
To get with the identification value.
void kodi::addon::PVRTypeStringValue::SetDescription (const std::string &description)
To set with the description text of the value.
std::string kodi::addon::PVRTypeStringValue::GetDescription () const
To get with the description text of the value.
Detailed Description
PVR add-on string type value
Representation of a <std::string, std::string> value.
The following table contains values that can be set with class PVRTypeStringValue :
Name Type Set call Get call
Value std::string SetValue GetValue
Description std::string SetDescription GetDescription
Remarks
Further can there be used his class constructor to set values.
Function Documentation
GetDescription()
std::string kodi::addon::PVRTypeStringValue::GetDescription () const inline
To get with the description text of the value.
References kodi::addon::DynamicCStructHdl< PVRTypeStringValue, PVR_ATTRIBUTE_STRING_VALUE >::m_cStructure, and PVR_ATTRIBUTE_STRING_VALUE::strDescription.
GetValue()
std::string kodi::addon::PVRTypeStringValue::GetValue () const inline
To get with the identification value.
References kodi::addon::DynamicCStructHdl< PVRTypeStringValue, PVR_ATTRIBUTE_STRING_VALUE >::m_cStructure, and PVR_ATTRIBUTE_STRING_VALUE::strValue.
PVRTypeStringValue() [1/2]
kodi::addon::PVRTypeStringValue::PVRTypeStringValue () default
Default class constructor.
PVRTypeStringValue() [2/2]
kodi::addon::PVRTypeStringValue::PVRTypeStringValue (const std::string & value, const std::string & description) inline
Class constructor with integrated value set.
Parameters
[in] value Type identification value
[in] description Type description text
References kodi::addon::PVRTypeStringValue::SetDescription(), kodi::addon::PVRTypeStringValue::SetValue(), and value.
SetDescription()
void kodi::addon::PVRTypeStringValue::SetDescription (const std::string & description) inline
To set with the description text of the value.
References kodi::addon::DynamicCStructHdl< PVRTypeStringValue, PVR_ATTRIBUTE_STRING_VALUE >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_ATTRIBUTE_STRING_VALUE::strDescription.
Referenced by kodi::addon::PVRTypeStringValue::PVRTypeStringValue().
SetValue()
void kodi::addon::PVRTypeStringValue::SetValue (const std::string & value) inline
To set with the identification value.
References kodi::addon::DynamicCStructHdl< PVRTypeStringValue, PVR_ATTRIBUTE_STRING_VALUE >::m_cStructure, kodi::addon::ReallocAndCopyString(), PVR_ATTRIBUTE_STRING_VALUE::strValue, and value.
Referenced by kodi::addon::PVRTypeStringValue::PVRTypeStringValue().