Kodi Documentation: CEGLUtils Class Reference
CEGLUtils Class Reference
#include <EGLUtils.h>
Static Public Member Functions
static std::set< std::string > GetClientExtensions ()
static std::set< std::string > GetExtensions (EGLDisplay eglDisplay)
static bool HasExtension (EGLDisplay eglDisplay, std::string const &name)
static bool HasClientExtension (std::string const &name)
static void Log (int logLevel, std::string const &what)
template<typename T >
static T GetRequiredProcAddress (const char *procname)
Private Member Functions
CEGLUtils ()
Constructor & Destructor Documentation
CEGLUtils()
CEGLUtils::CEGLUtils () private
Member Function Documentation
GetClientExtensions()
std::set< std::string > CEGLUtils::GetClientExtensions () static
Referenced by HasClientExtension().
GetExtensions()
std::set< std::string > CEGLUtils::GetExtensions (EGLDisplay eglDisplay) static
Referenced by HasExtension().
GetRequiredProcAddress()
template<typename T > static T CEGLUtils::GetRequiredProcAddress (const char * procname) inline static
HasClientExtension()
bool CEGLUtils::HasClientExtension (std::string const & name) static
References GetClientExtensions(), and name.
Referenced by CEGLContextUtils::CEGLContextUtils().
HasExtension()
bool CEGLUtils::HasExtension (EGLDisplay eglDisplay, std::string const & name) static
References GetExtensions(), and name.
Referenced by CEGLContextUtils::CreateContext(), VAAPI::CVaapi2Texture::Init(), CWinSystemAndroidGLESContext::InitWindowSystem(), and KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL().
Log()
void CEGLUtils::Log (int logLevel, std::string const & what) static
References CLog::Log().
Referenced by CEGLContextUtils::ChooseConfig(), CEGLContextUtils::CreateContext(), CEGLContextUtils::CreateDisplay(), KODI::UTILS::EGL::CEGLFence::CreateFence(), CEGLContextUtils::CreatePlatformDisplay(), CEGLContextUtils::CreatePlatformSurface(), CEGLContextUtils::CreateSurface(), KODI::UTILS::EGL::CEGLFence::DestroyFence(), CEGLContextUtils::GetConfigAttrib(), CEGLContextUtils::InitializeDisplay(), KODI::UTILS::EGL::CEGLFence::IsSignaled(), VAAPI::CVaapi2Texture::Map(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::PresentFrame(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender(), CWinSystemAndroidGLESContext::PresentRenderImpl(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::SetFullScreen(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::SetFullScreen(), CEGLContextUtils::SurfaceAttrib(), and CEGLContextUtils::SurfaceAttrib().
The documentation for this class was generated from the following files:
EGLUtils.h
EGLUtils.cpp