Kodi Documentation: XBMCAddon::xbmcgui::WindowDialogMixin Class Reference
XBMCAddon::xbmcgui::WindowDialogMixin Class Reference
#include <WindowDialogMixin.h>
Public Member Functions
virtual ~WindowDialogMixin ()=default
SWIGHIDDENVIRTUAL void show ()
SWIGHIDDENVIRTUAL void close ()
SWIGHIDDENVIRTUAL bool IsDialogRunning () const
SWIGHIDDENVIRTUAL bool OnAction (const CAction &action)
Protected Member Functions
WindowDialogMixin (Window *window)
Private Attributes
Window * w
Constructor & Destructor Documentation
WindowDialogMixin()
XBMCAddon::xbmcgui::WindowDialogMixin::WindowDialogMixin (Window * window) inline explicit protected
~WindowDialogMixin()
virtual XBMCAddon::xbmcgui::WindowDialogMixin::~WindowDialogMixin () virtual default
Member Function Documentation
close()
void XBMCAddon::xbmcgui::WindowDialogMixin::close ()
References XBMCAddon::xbmcgui::Window::bModal, XBMCAddon::xbmcgui::InterceptorBase::get(), CServiceBroker::GetAppMessenger(), HACK_CUSTOM_ACTION_CLOSING, XBMCAddon::xbmcgui::Window::iOldWindowId, XBMCAddon::xbmcgui::Window::PulseActionEvent(), TMSG_GUI_PYTHON_DIALOG, w, XBMCAddon::xbmcgui::Window::window, and XBMC_TRACE.
Referenced by XBMCAddon::xbmcgui::WindowDialog::close(), and XBMCAddon::xbmcgui::WindowXMLDialog::close().
IsDialogRunning()
bool XBMCAddon::xbmcgui::WindowDialogMixin::IsDialogRunning () const
References XBMCAddon::xbmcgui::InterceptorBase::isActive(), w, XBMCAddon::xbmcgui::Window::window, and XBMC_TRACE.
Referenced by XBMCAddon::xbmcgui::WindowDialog::IsDialogRunning(), and XBMCAddon::xbmcgui::WindowXMLDialog::IsDialogRunning().
OnAction()
bool XBMCAddon::xbmcgui::WindowDialogMixin::OnAction (const CAction & action)
Todo:
Figure out how to clean up the CAction
References CGUIWindow::Close(), XBMCAddon::xbmcgui::InterceptorBase::get(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_WINDOW_INIT, HACK_CUSTOM_ACTION_CLOSING, HACK_CUSTOM_ACTION_OPENING, XBMCAddon::xbmcgui::Window::OnMessage(), XBMCAddon::xbmcgui::InterceptorBase::setActive(), w, XBMCAddon::xbmcgui::Window::window, and XBMC_TRACE.
Referenced by XBMCAddon::xbmcgui::WindowDialog::OnAction(), and XBMCAddon::xbmcgui::WindowXMLDialog::OnAction().
show()
void XBMCAddon::xbmcgui::WindowDialogMixin::show ()
References XBMCAddon::xbmcgui::InterceptorBase::get(), CServiceBroker::GetAppMessenger(), HACK_CUSTOM_ACTION_OPENING, TMSG_GUI_PYTHON_DIALOG, w, XBMCAddon::xbmcgui::Window::window, and XBMC_TRACE.
Referenced by XBMCAddon::xbmcgui::WindowDialog::show(), and XBMCAddon::xbmcgui::WindowXMLDialog::show().
Member Data Documentation
w
Window* XBMCAddon::xbmcgui::WindowDialogMixin::w private
Referenced by close(), IsDialogRunning(), OnAction(), and show().
The documentation for this class was generated from the following files:
WindowDialogMixin.h
WindowDialogMixin.cpp