Kodi Documentation: CMediaTypes Class Reference
CMediaTypes Class Reference
#include <MediaType.h>
Classes
struct MediaTypeInfo
Static Public Member Functions
static bool IsValidMediaType (const MediaType &mediaType)
static bool IsMediaType (const std::string &strMediaType, const MediaType &mediaType)
static MediaType FromString (const std::string &strMediaType)
static MediaType ToPlural (const MediaType &mediaType)
static bool IsContainer (const MediaType &mediaType)
static std::string GetLocalization (const MediaType &mediaType)
static std::string GetPluralLocalization (const MediaType &mediaType)
static std::string GetCapitalLocalization (const MediaType &mediaType)
static std::string GetCapitalPluralLocalization (const MediaType &mediaType)
Static Private Member Functions
static std::map< std::string, MediaTypeInfo >::const_iterator findMediaType (const std::string &mediaType)
Static Private Attributes
static std::map< std::string, MediaTypeInfo > m_mediaTypes = fillDefaultMediaTypes()
Member Function Documentation
findMediaType()
std::map< std::string, CMediaTypes::MediaTypeInfo >::const_iterator CMediaTypes::findMediaType (const std::string & mediaType) static private
References m_mediaTypes.
Referenced by FromString(), GetCapitalLocalization(), GetCapitalPluralLocalization(), GetLocalization(), GetPluralLocalization(), IsContainer(), IsMediaType(), IsValidMediaType(), and ToPlural().
FromString()
MediaType CMediaTypes::FromString (const std::string & strMediaType) static
References findMediaType(), m_mediaTypes, and MediaTypeNone.
Referenced by XFILE::CSmartPlaylistDirectory::GetDirectory(), KODI::PLAYLIST::CSmartPlaylistRule::GetField(), and CGUIDialogMediaFilter::GetRange().
GetCapitalLocalization()
std::string CMediaTypes::GetCapitalLocalization (const MediaType & mediaType) static
References findMediaType(), g_localizeStrings, CLocalizeStrings::Get(), and m_mediaTypes.
Referenced by anonymous_namespace{MusicUtils.cpp}::ShowToastNotification().
GetCapitalPluralLocalization()
std::string CMediaTypes::GetCapitalPluralLocalization (const MediaType & mediaType) static
References findMediaType(), g_localizeStrings, CLocalizeStrings::Get(), and m_mediaTypes.
GetLocalization()
std::string CMediaTypes::GetLocalization (const MediaType & mediaType) static
References findMediaType(), g_localizeStrings, CLocalizeStrings::Get(), and m_mediaTypes.
GetPluralLocalization()
std::string CMediaTypes::GetPluralLocalization (const MediaType & mediaType) static
References findMediaType(), g_localizeStrings, CLocalizeStrings::Get(), and m_mediaTypes.
IsContainer()
bool CMediaTypes::IsContainer (const MediaType & mediaType) static
References findMediaType(), and m_mediaTypes.
Referenced by CFileItem::GetBaseMoviePath().
IsMediaType()
bool CMediaTypes::IsMediaType (const std::string & strMediaType, const MediaType & mediaType) static
References findMediaType(), and m_mediaTypes.
Referenced by JSONRPC::CAudioLibrary::GetAdditionalDetails(), CGUIDialogVideoInfo::GetLocalizedVideoType(), and CVideoLibraryRefreshingJob::Work().
IsValidMediaType()
bool CMediaTypes::IsValidMediaType (const MediaType & mediaType) static
References findMediaType(), and m_mediaTypes.
Referenced by XBMCAddon::xbmc::InfoTagVideo::setMediaTypeRaw().
ToPlural()
MediaType CMediaTypes::ToPlural (const MediaType & mediaType) static
References findMediaType(), m_mediaTypes, and MediaTypeNone.
Referenced by CGUIDialogVideoManagerVersions::GetAllOtherMovies(), CVideoDatabase::GetSortedVideos(), CVideoDatabase::GetVideoVersions(), CGUIDialogVideoManager::Refresh(), and CGUIDialogVideoInfo::SetMovie().
Member Data Documentation
m_mediaTypes
std::map< std::string, CMediaTypes::MediaTypeInfo > CMediaTypes::m_mediaTypes = fillDefaultMediaTypes() static private
Referenced by findMediaType(), FromString(), GetCapitalLocalization(), GetCapitalPluralLocalization(), GetLocalization(), GetPluralLocalization(), IsContainer(), IsMediaType(), IsValidMediaType(), and ToPlural().
The documentation for this class was generated from the following files:
MediaType.h
MediaType.cpp