Kodi Documentation: KODI::WINDOWING::GBM::CDRMConnector Class Reference
KODI::WINDOWING::GBM::CDRMConnector Class Reference
#include <DRMConnector.h>
Classes
struct DrmModeConnectorDeleter
Public Member Functions
CDRMConnector (int fd, uint32_t connector)
CDRMConnector (const CDRMConnector &)=delete
CDRMConnector & operator= (const CDRMConnector &)=delete
~CDRMConnector ()=default
std::string GetType ()
std::string GetStatus ()
std::string GetName ()
uint32_t GetEncoderId () const
uint32_t * GetConnectorId () const
int GetModesCount () const
drmModeModeInfoPtr GetModeForIndex (int index) const
bool IsConnected ()
bool CheckConnector ()
std::vector< uint8_t > GetEDID () const
Public Member Functions inherited from KODI::WINDOWING::GBM::CDRMObject
CDRMObject (const CDRMObject &)=delete
CDRMObject & operator= (const CDRMObject &)=delete
virtual ~CDRMObject ()=default
std::string GetTypeName () const
std::string GetPropertyName (uint32_t propertyId) const
uint32_t GetId () const
uint32_t GetPropertyId (const std::string &name) const
std::optional< uint64_t > GetPropertyValue (std::string_view name, std::string_view valueName) const
bool SetProperty (const std::string &name, uint64_t value)
bool SupportsProperty (const std::string &name)
Private Attributes
std::unique_ptr< drmModeConnector, DrmModeConnectorDeleter > m_connector
Additional Inherited Members
Protected Member Functions inherited from KODI::WINDOWING::GBM::CDRMObject
CDRMObject (int fd)
bool GetProperties (uint32_t id, uint32_t type)
Protected Attributes inherited from KODI::WINDOWING::GBM::CDRMObject
std::unique_ptr< drmModeObjectProperties, DrmModeObjectPropertiesDeleter > m_props
std::vector< std::unique_ptr< drmModePropertyRes, DrmModePropertyResDeleter > > m_propsInfo
int m_fd {-1}
Constructor & Destructor Documentation
CDRMConnector() [1/2]
CDRMConnector::CDRMConnector (int fd, uint32_t connector) explicit
References KODI::WINDOWING::GBM::CDRMObject::GetProperties(), and m_connector.
CDRMConnector() [2/2]
KODI::WINDOWING::GBM::CDRMConnector::CDRMConnector (const CDRMConnector &) delete
~CDRMConnector()
KODI::WINDOWING::GBM::CDRMConnector::~CDRMConnector () default
Member Function Documentation
CheckConnector()
bool CDRMConnector::CheckConnector ()
References IsConnected(), CLog::Log(), LOGDEBUG, m_connector, KODI::WINDOWING::GBM::CDRMObject::m_fd, and KODI::TIME::Sleep().
Referenced by KODI::WINDOWING::GBM::CDRMUtils::SetMode().
GetConnectorId()
uint32_t * KODI::WINDOWING::GBM::CDRMConnector::GetConnectorId () const inline
References m_connector.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::FindEncoder(), KODI::WINDOWING::GBM::CDRMUtils::RestoreOriginalMode(), and KODI::WINDOWING::GBM::CDRMLegacy::SetVideoMode().
GetEDID()
std::vector< uint8_t > CDRMConnector::GetEDID () const
References data(), LOGDEBUG, m_connector, KODI::WINDOWING::GBM::CDRMObject::m_fd, KODI::WINDOWING::GBM::CDRMObject::m_props, and KODI::WINDOWING::GBM::CDRMObject::m_propsInfo.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbm::InitWindowSystem().
GetEncoderId()
uint32_t KODI::WINDOWING::GBM::CDRMConnector::GetEncoderId () const inline
References m_connector.
GetModeForIndex()
drmModeModeInfoPtr KODI::WINDOWING::GBM::CDRMConnector::GetModeForIndex (int index) const inline
References index(), and m_connector.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::FindPreferredMode(), KODI::WINDOWING::GBM::CDRMUtils::GetModes(), and KODI::WINDOWING::GBM::CDRMUtils::SetMode().
GetModesCount()
int KODI::WINDOWING::GBM::CDRMConnector::GetModesCount () const inline
References m_connector.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::FindPreferredMode(), and KODI::WINDOWING::GBM::CDRMUtils::GetModes().
GetName()
std::string CDRMConnector::GetName ()
References GetType(), and m_connector.
GetStatus()
std::string CDRMConnector::GetStatus ()
References m_connector.
GetType()
std::string CDRMConnector::GetType ()
References m_connector.
Referenced by GetName().
IsConnected()
bool KODI::WINDOWING::GBM::CDRMConnector::IsConnected () inline
References m_connector.
Referenced by CheckConnector().
operator=()
CDRMConnector & KODI::WINDOWING::GBM::CDRMConnector::operator= (const CDRMConnector &) delete
Member Data Documentation
m_connector
std::unique_ptr<drmModeConnector, DrmModeConnectorDeleter> KODI::WINDOWING::GBM::CDRMConnector::m_connector private
Referenced by CDRMConnector(), CheckConnector(), GetConnectorId(), GetEDID(), GetEncoderId(), GetModeForIndex(), GetModesCount(), GetName(), GetStatus(), GetType(), and IsConnected().
The documentation for this class was generated from the following files:
DRMConnector.h
DRMConnector.cpp