Kodi Documentation: JSONRPC::IClient Class Reference
JSONRPC::IClient Class Reference abstract
#include <IClient.h>
Public Member Functions
virtual ~IClient ()=default
virtual int GetPermissionFlags ()=0
virtual int GetAnnouncementFlags ()=0
virtual bool SetAnnouncementFlags (int flags)=0
Constructor & Destructor Documentation
~IClient()
virtual JSONRPC::IClient::~IClient () virtual default
Member Function Documentation
GetAnnouncementFlags()
virtual int JSONRPC::IClient::GetAnnouncementFlags () pure virtual
Implemented in CAddOnTransport::CAddOnClient, CHTTPJsonRpcHandler::CHTTPClient, JSONRPC::CTCPServer::CTCPClient, and jni::CJNIXBMCJsonHandler::CJNIClient.
Referenced by JSONRPC::CJSONRPC::GetConfiguration(), and JSONRPC::CJSONRPC::SetConfiguration().
GetPermissionFlags()
virtual int JSONRPC::IClient::GetPermissionFlags () pure virtual
Implemented in CAddOnTransport::CAddOnClient, CHTTPJsonRpcHandler::CHTTPClient, JSONRPC::CTCPServer::CTCPClient, and jni::CJNIXBMCJsonHandler::CJNIClient.
Referenced by JSONRPC::JsonRpcMethod::Check(), JSONRPC::CXBMCOperations::GetInfoBooleans(), JSONRPC::CSystemOperations::GetProperties(), JSONRPC::CJSONRPC::Permission(), and JSONRPC::CJSONServiceDescription::Print().
SetAnnouncementFlags()
virtual bool JSONRPC::IClient::SetAnnouncementFlags (int flags) pure virtual
Implemented in CAddOnTransport::CAddOnClient, CHTTPJsonRpcHandler::CHTTPClient, JSONRPC::CTCPServer::CTCPClient, and jni::CJNIXBMCJsonHandler::CJNIClient.
Referenced by JSONRPC::CJSONRPC::SetConfiguration().
The documentation for this class was generated from the following file:
IClient.h