Kodi Documentation: XFILE::CNFSFile Class Reference
XFILE::CNFSFile Class Reference
Public Member Functions
CNFSFile ()
~CNFSFile () override
void Close () override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int Stat (struct __stat64 *buffer) override
int64_t GetLength () override
int64_t GetPosition () override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
int Truncate (int64_t iSize) override
int IoControl (EIoControl request, void *param) override
int GetChunkSize () override
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
bool Delete (const CURL &url) override
bool Rename (const CURL &url, const CURL &urlnew) override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual double GetDownloadSpeed ()
virtual bool SetHidden (const CURL &url, bool hidden)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Protected Member Functions
bool IsValidFile (const std::string &strFileName)
Protected Attributes
CURL m_url
int64_t m_fileSize = 0
struct nfsfh * m_pFileHandle
struct nfs_context * m_pNfsContext
std::string m_exportPath
Constructor & Destructor Documentation
CNFSFile()
CNFSFile::CNFSFile ()
References CNfsConnection::AddActiveConnection(), and gNfsConnection.
~CNFSFile()
CNFSFile::~CNFSFile () override
References CNfsConnection::AddIdleConnection(), Close(), and gNfsConnection.
Member Function Documentation
Close()
void CNFSFile::Close () override virtual
Implements XFILE::IFile.
References CURL::GetFileName(), gNfsConnection, CLog::Log(), LOGDEBUG, LOGERROR, m_exportPath, m_fileSize, m_pFileHandle, m_pNfsContext, m_url, and CNfsConnection::removeFromKeepAliveList().
Referenced by Open(), OpenForWrite(), and ~CNFSFile().
Delete()
bool CNFSFile::Delete (const CURL & url) override virtual
Reimplemented from XFILE::IFile.
References CNfsConnection::Connect(), CNfsConnection::GetNfsContext(), gNfsConnection, CLog::Log(), and LOGERROR.
Exists()
bool CNFSFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References Stat().
GetChunkSize()
int XFILE::CNFSFile::GetChunkSize () inline override virtual
Reimplemented from XFILE::IFile.
References CNfsConnection::GetMaxReadChunkSize(), and gNfsConnection.
GetLength()
int64_t CNFSFile::GetLength () override virtual
Implements XFILE::IFile.
References m_fileSize, and m_pFileHandle.
GetPosition()
int64_t CNFSFile::GetPosition () override virtual
Implements XFILE::IFile.
References CNfsConnection::GetNfsContext(), gNfsConnection, CLog::Log(), LOGERROR, and m_pFileHandle.
IoControl()
int XFILE::CNFSFile::IoControl (EIoControl request, void * param) inline override virtual
Reimplemented from XFILE::IFile.
References XFILE::IOCTRL_SEEK_POSSIBLE.
IsValidFile()
bool CNFSFile::IsValidFile (const std::string & strFileName) protected
Referenced by Open(), and OpenForWrite().
Open()
bool CNFSFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References __stat64, Close(), CNfsConnection::Connect(), CNfsConnection::Deinit(), CNfsConnection::GetContextMapId(), CURL::GetFileName(), CNfsConnection::GetNfsContext(), gNfsConnection, IsValidFile(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_exportPath, m_fileSize, m_pFileHandle, m_pNfsContext, m_url, CURL::Reset(), and Stat().
OpenForWrite()
bool CNFSFile::OpenForWrite (const CURL & url, bool bOverWrite = false) override virtual
Reimplemented from XFILE::IFile.
References __stat64, Close(), CNfsConnection::Connect(), CNfsConnection::GetContextMapId(), CURL::GetFileName(), CNfsConnection::GetNfsContext(), gNfsConnection, IsValidFile(), CLog::Log(), LOGERROR, LOGWARNING, m_exportPath, m_fileSize, m_pFileHandle, m_pNfsContext, m_url, CURL::Reset(), and Stat().
Read()
ssize_t CNFSFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References gNfsConnection, int64_t(), CLog::Log(), LOGERROR, m_exportPath, m_pFileHandle, m_pNfsContext, CNfsConnection::resetKeepAlive(), and SSIZE_MAX.
Rename()
bool CNFSFile::Rename (const CURL & url, const CURL & urlnew) override virtual
Reimplemented from XFILE::IFile.
References CNfsConnection::Connect(), CNfsConnection::GetNfsContext(), gNfsConnection, CLog::Log(), LOGERROR, and CNfsConnection::splitUrlIntoExportAndPath().
Seek()
int64_t CNFSFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
References gNfsConnection, int64_t(), CLog::Log(), LOGERROR, m_fileSize, m_pFileHandle, and m_pNfsContext.
Stat() [1/2]
int CNFSFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References CNfsConnection::Connect(), CURL::GetFileName(), CNfsConnection::GetNfsContext(), gNfsConnection, CLog::Log(), and LOGERROR.
Referenced by Exists(), Open(), OpenForWrite(), and Stat().
Stat() [2/2]
int CNFSFile::Stat (struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about currently open file For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Reimplemented from XFILE::IFile.
References m_url, and Stat().
Truncate()
int CNFSFile::Truncate (int64_t iSize) override virtual
Reimplemented from XFILE::IFile.
References gNfsConnection, CLog::Log(), LOGERROR, m_fileSize, m_pFileHandle, and m_pNfsContext.
Write()
ssize_t CNFSFile::Write (const void * bufPtr, size_t bufSize) override virtual
Attempt to write bufSize bytes from buffer bufPtr into currently opened file.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully written bytes if any bytes were written, zero if no bytes were written and no detectable error occur, -1 in case of any explicit error
Bug:
libnfs < 2.0.0 isn't const correct
Reimplemented from XFILE::IFile.
References CURL::GetFileName(), CNfsConnection::GetMaxWriteChunkSize(), gNfsConnection, CLog::Log(), LOGERROR, m_pFileHandle, m_pNfsContext, and m_url.
Member Data Documentation
m_exportPath
std::string XFILE::CNFSFile::m_exportPath protected
Referenced by Close(), Open(), OpenForWrite(), and Read().
m_fileSize
int64_t XFILE::CNFSFile::m_fileSize = 0 protected
Referenced by Close(), GetLength(), Open(), OpenForWrite(), Seek(), and Truncate().
m_pFileHandle
struct nfsfh* XFILE::CNFSFile::m_pFileHandle protected
Referenced by Close(), GetLength(), GetPosition(), Open(), OpenForWrite(), Read(), Seek(), Truncate(), and Write().
m_pNfsContext
struct nfs_context* XFILE::CNFSFile::m_pNfsContext protected
Referenced by Close(), Open(), OpenForWrite(), Read(), Seek(), Truncate(), and Write().
m_url
CURL XFILE::CNFSFile::m_url protected
Referenced by Close(), Open(), OpenForWrite(), Stat(), and Write().
The documentation for this class was generated from the following files:
NFSFile.h
NFSFile.cpp