Kodi Documentation: KODI::ADDONS::CExtsMimeSupportList Class Reference
KODI::ADDONS::CExtsMimeSupportList Class Reference
Class to manage all available and activated add-ons and to release their types to the outside for selection.
#include <ExtsMimeSupportList.h>
Classes
struct SupportValue
Structure to store information about supported part.
struct SupportValues
Structure to store available data for related addon.
Public Types
enum class FilterSelect { all , hasTags , hasTracks }
Filter selection values.
Public Member Functions
CExtsMimeSupportList (ADDON::CAddonMgr &addonMgr)
~CExtsMimeSupportList ()
std::vector< SupportValues > GetSupportedAddonInfos (FilterSelect select)
Get list of all by audiodecoder supported parts.
bool IsExtensionSupported (const std::string &ext)
To query the desired file extension is supported in it.
std::vector< std::pair< ADDON::AddonType, std::shared_ptr< ADDON::CAddonInfo > > > GetExtensionSupportedAddonInfos (const std::string &ext, FilterSelect select)
To get a list of all compatible audio decoder add-ons for the file extension.
bool IsMimetypeSupported (const std::string &mimetype)
To query the desired file mimetype is supported in it.
std::vector< std::pair< ADDON::AddonType, std::shared_ptr< ADDON::CAddonInfo > > > GetMimetypeSupportedAddonInfos (const std::string &mimetype, FilterSelect select)
To get a list of all compatible audio decoder add-ons for the mimetype.
std::vector< KODI::ADDONS::AddonSupportEntry > GetSupportedExtsAndMimeTypes (const std::string &addonId) override
To give all file extensions and MIME types supported by the addon.
Public Member Functions inherited from KODI::ADDONS::IAddonSupportList
IAddonSupportList ()=default
virtual ~IAddonSupportList ()=default
Protected Member Functions
void Update (const std::string &id)
void OnEvent (const ADDON::AddonEvent &event)
Static Protected Member Functions
static SupportValues ScanAddonProperties (ADDON::AddonType type, const std::shared_ptr< ADDON::CAddonInfo > &addonInfo)
Protected Attributes
CCriticalSection m_critSection
std::vector< SupportValues > m_supportedList
ADDON::CAddonMgr & m_addonMgr
Detailed Description
Class to manage all available and activated add-ons and to release their types to the outside for selection.
Note
It may also make sense in the future to expand this class and design it globally in Kodi so that other addons can also be managed with it (all which have mimetypes and file extensions, e.g. vfs, audioencoder).
Member Enumeration Documentation
FilterSelect
enum class KODI::ADDONS::CExtsMimeSupportList::FilterSelect strong
Filter selection values.
Enumerator
all
To select all available
hasTags
To select only them where support tags
hasTracks
Get only where support tracks within
Constructor & Destructor Documentation
CExtsMimeSupportList()
CExtsMimeSupportList::CExtsMimeSupportList (ADDON::CAddonMgr & addonMgr)
References ADDON::CAddonMgr::Events(), ADDON::CAddonMgr::GetAddonInfos(), m_addonMgr, m_supportedList, OnEvent(), ScanAddonProperties(), and ADDON::types.
~CExtsMimeSupportList()
CExtsMimeSupportList::~CExtsMimeSupportList ()
References ADDON::CAddonMgr::Events(), and m_addonMgr.
Member Function Documentation
GetExtensionSupportedAddonInfos()
std::vector< std::pair< AddonType, std::shared_ptr< ADDON::CAddonInfo > > > CExtsMimeSupportList::GetExtensionSupportedAddonInfos (const std::string & ext, FilterSelect select)
To get a list of all compatible audio decoder add-ons for the file extension.
Parameters
[in] ext Extension name to check
[in] select To filter the listed information by type
Returns
List of ADDON::CAddonInfo where support related extension
References all, hasTags, hasTracks, m_critSection, and m_supportedList.
Referenced by CFileExtensionProvider::CanOperateExtension(), XFILE::CFileDirectoryFactory::Create(), CodecFactory::CreateCodec(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), and CPictureInfoTag::Load().
GetMimetypeSupportedAddonInfos()
std::vector< std::pair< AddonType, std::shared_ptr< CAddonInfo > > > CExtsMimeSupportList::GetMimetypeSupportedAddonInfos (const std::string & mimetype, FilterSelect select)
To get a list of all compatible audio decoder add-ons for the mimetype.
Parameters
[in] mimetype Mimetype name to check
[in] select To filter the listed information by type
Returns
List of ADDON::CAddonInfo where support related mimetype
References all, hasTags, hasTracks, m_critSection, and m_supportedList.
Referenced by CodecFactory::CreateCodecDemux(), and ImageFactory::CreateLoaderFromMimeType().
GetSupportedAddonInfos()
std::vector< CExtsMimeSupportList::SupportValues > CExtsMimeSupportList::GetSupportedAddonInfos (FilterSelect select)
Get list of all by audiodecoder supported parts.
Thought to use on planned new window about management about supported extensions and mimetypes in Kodi and to allow edit by user to enable or disable corresponding parts.
This function is also used to notify Kodi supported formats and to allow playback.
Parameters
[in] select To filter the listed information by type
Returns
List of the available types listed for the respective add-on
References all, hasTags, hasTracks, m_critSection, and m_supportedList.
Referenced by CFileExtensionProvider::SetAddonExtensions().
GetSupportedExtsAndMimeTypes()
std::vector< AddonSupportEntry > CExtsMimeSupportList::GetSupportedExtsAndMimeTypes (const std::string & addonId) override virtual
To give all file extensions and MIME types supported by the addon.
Parameters
[in] addonId Identifier about wanted addon
Returns
List of all supported parts on selected addon
See also
KODI::ADDONS::IAddonSupportList
Implements KODI::ADDONS::IAddonSupportList.
References KODI::ADDONS::Extension, g_localizeStrings, CLocalizeStrings::GetAddonString(), KODI::ADDONS::AddonSupportEntry::m_description, KODI::ADDONS::AddonSupportEntry::m_icon, KODI::ADDONS::AddonSupportEntry::m_name, m_supportedList, KODI::ADDONS::AddonSupportEntry::m_type, and KODI::ADDONS::Mimetype.
Referenced by CGUIDialogAddonInfo::ShowSupportList().
IsExtensionSupported()
bool CExtsMimeSupportList::IsExtensionSupported (const std::string & ext)
To query the desired file extension is supported in it.
Parameters
[in] ext Extension name to check
Returns
True if within supported, false if not
References m_critSection, and m_supportedList.
IsMimetypeSupported()
bool CExtsMimeSupportList::IsMimetypeSupported (const std::string & mimetype)
To query the desired file mimetype is supported in it.
Parameters
[in] mimetype Mimetype name to check
Returns
True if within supported, false if not
References m_critSection, and m_supportedList.
OnEvent()
void CExtsMimeSupportList::OnEvent (const ADDON::AddonEvent & event) protected
References ADDON::AddonEvent::addonId, ADDON::CAddonMgr::HasType(), m_addonMgr, and Update.
Referenced by CExtsMimeSupportList().
ScanAddonProperties()
CExtsMimeSupportList::SupportValues CExtsMimeSupportList::ScanAddonProperties (ADDON::AddonType type, const std::shared_ptr< ADDON::CAddonInfo > & addonInfo) static protected
References URIUtils::AddFileToFolder(), KODI_ADDON_AUDIODECODER_TRACK_EXT, name, and values.
Referenced by CExtsMimeSupportList(), and Update().
Update()
void CExtsMimeSupportList::Update (const std::string & id) protected
References ADDON::CAddonMgr::GetAddonInfo(), ADDON::CAddonMgr::IsAddonDisabled(), m_addonMgr, m_critSection, m_supportedList, ScanAddonProperties(), and values.
Member Data Documentation
m_addonMgr
ADDON::CAddonMgr& KODI::ADDONS::CExtsMimeSupportList::m_addonMgr protected
Referenced by CExtsMimeSupportList(), OnEvent(), Update(), and ~CExtsMimeSupportList().
m_critSection
CCriticalSection KODI::ADDONS::CExtsMimeSupportList::m_critSection protected
Referenced by GetExtensionSupportedAddonInfos(), GetMimetypeSupportedAddonInfos(), GetSupportedAddonInfos(), IsExtensionSupported(), IsMimetypeSupported(), and Update().
m_supportedList
std::vector<SupportValues> KODI::ADDONS::CExtsMimeSupportList::m_supportedList protected
Referenced by CExtsMimeSupportList(), GetExtensionSupportedAddonInfos(), GetMimetypeSupportedAddonInfos(), GetSupportedAddonInfos(), GetSupportedExtsAndMimeTypes(), IsExtensionSupported(), IsMimetypeSupported(), and Update().
The documentation for this class was generated from the following files:
ExtsMimeSupportList.h
ExtsMimeSupportList.cpp