Kodi Documentation: anonymous_namespace{DVDDemuxCC.cpp} Namespace Reference
anonymous_namespace{DVDDemuxCC.cpp} Namespace Reference
Enumerations
enum class ColorFormat { RGB , ARGB }
Color formats for CC color conversion.
Functions
constexpr COLOR::Color CCColorConversion (const uint8_t ccColor, ColorFormat format)
Given the color code from the close caption decoder, returns the corresponding color in rgb format (striping the alpha channel from argb)
void ApplyStyleModifiers (std::string &ccText, const cc_attribute_t &ccAttributes)
Given the current buffer cc text and cc style attributes, apply the modifiers.
Enumeration Type Documentation
ColorFormat
enum class anonymous_namespace{DVDDemuxCC.cpp}::ColorFormat strong
Color formats for CC color conversion.
Enumerator
RGB
ARGB
Function Documentation
ApplyStyleModifiers()
void anonymous_namespace{DVDDemuxCC.cpp}::ApplyStyleModifiers (std::string & ccText, const cc_attribute_t & ccAttributes)
Given the current buffer cc text and cc style attributes, apply the modifiers.
Parameters
[in,out] ccText - the text to display in the caption
[in] ccAttributes - The attributes (italic, color, underline) for the text
References CCColorConversion(), KODI::UTILS::COLOR::ConvertToHexRGB(), cc_attribute_s::foreground, KODI::UTILS::StringUtils::Format(), cc_attribute_s::italic, RGB, cc_attribute_s::underline, and WHITE.
CCColorConversion()
constexpr COLOR::Color anonymous_namespace{DVDDemuxCC.cpp}::CCColorConversion (const uint8_t ccColor, ColorFormat format) constexpr
Given the color code from the close caption decoder, returns the corresponding color in rgb format (striping the alpha channel from argb)
Parameters
[in] ccColor - a given color from the cc decoder
[in] format - the color format
Returns
the corresponding Color in rgb
References BLACK, KODI::UTILS::COLOR::BLACK, BLUE, KODI::UTILS::COLOR::BLUE, color, CYAN, KODI::UTILS::COLOR::CYAN, GREEN, KODI::UTILS::COLOR::GREEN, MAGENTA, KODI::UTILS::COLOR::MAGENTA, KODI::UTILS::COLOR::NONE, RED, KODI::UTILS::COLOR::RED, RGB, WHITE, KODI::UTILS::COLOR::WHITE, YELLOW, and KODI::UTILS::COLOR::YELLOW.
Referenced by ApplyStyleModifiers().