Kodi Documentation: AndroidUtils.cpp File Reference
AndroidUtils.cpp File Reference
#include "AndroidUtils.h"
#include "ServiceBroker.h"
#include "settings/DisplaySettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "settings/lib/SettingsManager.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include "windowing/GraphicContext.h"
#include "platform/android/activity/XBMCApp.h"
#include <androidjni/MediaCodecInfo.h>
#include <androidjni/MediaCodecList.h>
#include <androidjni/View.h>
#include <androidjni/Window.h>
Namespaces
namespace anonymous_namespace{AndroidUtils.cpp}
Functions
static void fetchDisplayModes ()
std::string anonymous_namespace{AndroidUtils.cpp}::HdrTypeString (int type)
Variables
static std::vector< RESOLUTION_INFO > s_res_displayModes
static RESOLUTION_INFO s_res_cur_displayMode
Function Documentation
fetchDisplayModes()
static void fetchDisplayModes () static
References RESOLUTION_INFO::bFullScreen, D3DPRESENTFLAG_INTERLACED, D3DPRESENTFLAG_PROGRESSIVE, RESOLUTION_INFO::dwFlags, KODI::UTILS::StringUtils::Format(), RESOLUTION_INFO::fPixelRatio, RESOLUTION_INFO::fRefreshRate, RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, CLog::Log(), LOGDEBUG, s_res_cur_displayMode, s_res_displayModes, RESOLUTION_INFO::strId, and RESOLUTION_INFO::strMode.
Referenced by CAndroidUtils::CAndroidUtils(), and CAndroidUtils::UpdateDisplayModes().
Variable Documentation
s_res_cur_displayMode
RESOLUTION_INFO s_res_cur_displayMode static
Referenced by fetchDisplayModes(), CAndroidUtils::GetNativeResolution(), and CAndroidUtils::SetNativeResolution().
s_res_displayModes
std::vector<RESOLUTION_INFO> s_res_displayModes static
Referenced by CAndroidUtils::CAndroidUtils(), fetchDisplayModes(), and CAndroidUtils::ProbeResolutions().