Kodi Documentation: ADDON::Interface_GUIControlSpin Struct Reference
ADDON::Interface_GUIControlSpin Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Spin.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
callback functions from add-on to kodi
static void set_enabled (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled)
static void set_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *text)
static void reset (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_type (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int type)
static void add_string_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *label, const char *value)
static void add_int_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *label, int value)
static void set_string_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *value)
static char * get_string_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_int_range (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int start, int end)
static void set_int_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int value)
static int get_int_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_float_range (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float start, float end)
static void set_float_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float value)
static float get_float_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_float_interval (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float interval)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold general gui functions and initialize also all other gui related types not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/controls/Spin.h"
Member Function Documentation
add_int_label()
void ADDON::Interface_GUIControlSpin::add_int_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * label, int value) static
References CGUISpinControl::AddLabel(), ADDON::CAddon::ID(), label, CLog::Log(), LOGERROR, and value.
Referenced by Init().
add_string_label()
void ADDON::Interface_GUIControlSpin::add_string_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * label, const char * value) static
References CGUISpinControl::AddLabel(), ADDON::CAddon::ID(), label, CLog::Log(), LOGERROR, and value.
Referenced by Init().
DeInit()
void ADDON::Interface_GUIControlSpin::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_spin, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
get_float_value()
float ADDON::Interface_GUIControlSpin::get_float_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUISpinControl::GetFloatValue(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_int_value()
int ADDON::Interface_GUIControlSpin::get_int_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUISpinControl::GetValue(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_string_value()
char * ADDON::Interface_GUIControlSpin::get_string_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUISpinControl::GetStringValue(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIControlSpin::Init (AddonGlobalInterface * addonInterface) static
References add_int_label(), AddonToKodiFuncTable_kodi_gui_control_spin::add_int_label, add_string_label(), AddonToKodiFuncTable_kodi_gui_control_spin::add_string_label, AddonToKodiFuncTable_kodi_gui::control_spin, get_float_value(), AddonToKodiFuncTable_kodi_gui_control_spin::get_float_value, get_int_value(), AddonToKodiFuncTable_kodi_gui_control_spin::get_int_value, get_string_value(), AddonToKodiFuncTable_kodi_gui_control_spin::get_string_value, AddonToKodiFuncTable_Addon::kodi_gui, reset(), AddonToKodiFuncTable_kodi_gui_control_spin::reset, set_enabled(), AddonToKodiFuncTable_kodi_gui_control_spin::set_enabled, set_float_interval(), AddonToKodiFuncTable_kodi_gui_control_spin::set_float_interval, set_float_range(), AddonToKodiFuncTable_kodi_gui_control_spin::set_float_range, set_float_value(), AddonToKodiFuncTable_kodi_gui_control_spin::set_float_value, set_int_range(), AddonToKodiFuncTable_kodi_gui_control_spin::set_int_range, set_int_value(), AddonToKodiFuncTable_kodi_gui_control_spin::set_int_value, set_string_value(), AddonToKodiFuncTable_kodi_gui_control_spin::set_string_value, set_text(), AddonToKodiFuncTable_kodi_gui_control_spin::set_text, set_type(), AddonToKodiFuncTable_kodi_gui_control_spin::set_type, set_visible(), AddonToKodiFuncTable_kodi_gui_control_spin::set_visible, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
reset()
void ADDON::Interface_GUIControlSpin::reset (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIControl::GetParentID(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_RESET, ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
set_enabled()
void ADDON::Interface_GUIControlSpin::set_enabled (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUISpinControlEx::SetEnabled().
Referenced by Init().
set_float_interval()
void ADDON::Interface_GUIControlSpin::set_float_interval (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float interval) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUISpinControl::SetFloatInterval().
Referenced by Init().
set_float_range()
void ADDON::Interface_GUIControlSpin::set_float_range (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float start, float end) static
References end(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUISpinControl::SetFloatRange().
Referenced by Init().
set_float_value()
void ADDON::Interface_GUIControlSpin::set_float_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float value) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUISpinControl::SetFloatValue(), and value.
Referenced by Init().
set_int_range()
void ADDON::Interface_GUIControlSpin::set_int_range (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int start, int end) static
References end(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUISpinControl::SetRange().
Referenced by Init().
set_int_value()
void ADDON::Interface_GUIControlSpin::set_int_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int value) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUISpinControl::SetValue(), and value.
Referenced by Init().
set_string_value()
void ADDON::Interface_GUIControlSpin::set_string_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * value) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUISpinControl::SetStringValue(), and value.
Referenced by Init().
set_text()
void ADDON::Interface_GUIControlSpin::set_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * text) static
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIControl::GetParentID(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_SET, ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUIMessage::SetLabel(), and text.
Referenced by Init().
set_type()
void ADDON::Interface_GUIControlSpin::set_type (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int type) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUISpinControl::SetType().
Referenced by Init().
set_visible()
void ADDON::Interface_GUIControlSpin::set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetVisible().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/controls/spin.h
Spin.cpp