Kodi Documentation: TestVariant.cpp File Reference
TestVariant.cpp File Reference
#include "utils/Variant.h"
#include <map>
#include <string>
#include <vector>
#include <gtest/gtest.h>
Functions
TEST (TestVariant, VariantTypeInteger)
TEST (TestVariant, VariantTypeUnsignedInteger)
TEST (TestVariant, VariantTypeBoolean)
TEST (TestVariant, VariantTypeString)
TEST (TestVariant, VariantTypeWideString)
TEST (TestVariant, VariantTypeDouble)
TEST (TestVariant, VariantTypeArray)
TEST (TestVariant, VariantTypeObject)
TEST (TestVariant, VariantTypeNull)
TEST (TestVariant, VariantFromMap)
TEST (TestVariant, operatorTest)
TEST (TestVariant, push_back)
TEST (TestVariant, append)
TEST (TestVariant, c_str)
TEST (TestVariant, swap)
TEST (TestVariant, iterator_array)
TEST (TestVariant, iterator_map)
TEST (TestVariant, size)
TEST (TestVariant, empty)
TEST (TestVariant, clear)
TEST (TestVariant, erase)
TEST (TestVariant, isMember)
TEST (TestVariant, asBoolean)
Function Documentation
TEST() [1/23]
TEST (TestVariant , append)
References CVariant::append(), EXPECT_EQ(), EXPECT_TRUE(), CVariant::isArray(), CVariant::type(), and CVariant::VariantTypeArray.
TEST() [2/23]
TEST (TestVariant , asBoolean)
References EXPECT_TRUE(), int64_t(), CVariant::VariantTypeArray, CVariant::VariantTypeConstNull, CVariant::VariantTypeNull, and CVariant::VariantTypeObject.
TEST() [3/23]
TEST (TestVariant , c_str)
References CVariant::c_str().
TEST() [4/23]
TEST (TestVariant , clear)
References CVariant::clear(), CVariant::empty(), and EXPECT_TRUE().
TEST() [5/23]
TEST (TestVariant , empty)
References EXPECT_TRUE(), CVariant::VariantTypeBoolean, CVariant::VariantTypeConstNull, CVariant::VariantTypeDouble, CVariant::VariantTypeInteger, and CVariant::VariantTypeUnsignedInteger.
TEST() [6/23]
TEST (TestVariant , erase)
References CVariant::erase().
TEST() [7/23]
TEST (TestVariant , isMember)
References EXPECT_TRUE(), and CVariant::isMember().
TEST() [8/23]
TEST (TestVariant , iterator_array)
References CVariant::begin_array(), CVariant::end_array(), EXPECT_EQ(), EXPECT_TRUE(), CVariant::isArray(), CVariant::type(), and CVariant::VariantTypeArray.
TEST() [9/23]
TEST (TestVariant , iterator_map)
References CVariant::begin_map(), CVariant::end_map(), EXPECT_EQ(), EXPECT_TRUE(), CVariant::isObject(), CVariant::type(), and CVariant::VariantTypeObject.
TEST() [10/23]
TEST (TestVariant , operatorTest)
References EXPECT_EQ(), EXPECT_TRUE(), CVariant::isArray(), CVariant::isObject(), CVariant::type(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
TEST() [11/23]
TEST (TestVariant , push_back)
References EXPECT_EQ(), EXPECT_TRUE(), CVariant::isArray(), CVariant::push_back(), CVariant::type(), and CVariant::VariantTypeArray.
TEST() [12/23]
TEST (TestVariant , size)
References EXPECT_EQ(), and CVariant::size().
TEST() [13/23]
TEST (TestVariant , swap)
References EXPECT_TRUE(), CVariant::isInteger(), and CVariant::isString().
TEST() [14/23]
TEST (TestVariant , VariantFromMap)
References EXPECT_EQ(), EXPECT_TRUE(), CVariant::isMember(), CVariant::isObject(), CVariant::size(), CVariant::type(), and CVariant::VariantTypeObject.
TEST() [15/23]
TEST (TestVariant , VariantTypeArray)
References EXPECT_EQ(), EXPECT_TRUE(), CVariant::isArray(), CVariant::type(), and CVariant::VariantTypeArray.
TEST() [16/23]
TEST (TestVariant , VariantTypeBoolean)
References CVariant::asBoolean(), EXPECT_EQ(), EXPECT_TRUE(), CVariant::isBoolean(), CVariant::type(), and CVariant::VariantTypeBoolean.
TEST() [17/23]
TEST (TestVariant , VariantTypeDouble)
References CVariant::asDouble(), EXPECT_EQ(), EXPECT_TRUE(), CVariant::isDouble(), CVariant::type(), and CVariant::VariantTypeDouble.
TEST() [18/23]
TEST (TestVariant , VariantTypeInteger)
References CVariant::asInteger(), EXPECT_EQ(), EXPECT_TRUE(), int64_t(), CVariant::isInteger(), CVariant::type(), and CVariant::VariantTypeInteger.
TEST() [19/23]
TEST (TestVariant , VariantTypeNull)
References EXPECT_EQ(), EXPECT_TRUE(), CVariant::isNull(), CVariant::type(), and CVariant::VariantTypeNull.
TEST() [20/23]
TEST (TestVariant , VariantTypeObject)
References EXPECT_EQ(), EXPECT_TRUE(), CVariant::isObject(), CVariant::type(), and CVariant::VariantTypeObject.
TEST() [21/23]
TEST (TestVariant , VariantTypeString)
References CVariant::asString(), EXPECT_EQ(), EXPECT_TRUE(), CVariant::isString(), CVariant::type(), and CVariant::VariantTypeString.
TEST() [22/23]
TEST (TestVariant , VariantTypeUnsignedInteger)
References CVariant::asUnsignedInteger(), EXPECT_EQ(), EXPECT_TRUE(), CVariant::isUnsignedInteger(), CVariant::type(), and CVariant::VariantTypeUnsignedInteger.
TEST() [23/23]
TEST (TestVariant , VariantTypeWideString)
References CVariant::asWideString(), EXPECT_EQ(), EXPECT_TRUE(), CVariant::isWideString(), CVariant::type(), and CVariant::VariantTypeWideString.