Kodi Documentation: CGUIDialogVideoInfo Class Reference
CGUIDialogVideoInfo Class Reference
#include <GUIDialogVideoInfo.h>
Public Member Functions
CGUIDialogVideoInfo (void)
~CGUIDialogVideoInfo (void) override
bool OnMessage (CGUIMessage &message) override
bool OnAction (const CAction &action) override
void SetMovie (const CFileItem *item)
bool NeedRefresh () const
bool RefreshAll () const
bool HasUpdatedThumb () const
bool HasUpdatedUserrating () const
bool HasUpdatedItems () const
std::string GetThumbnail () const
std::shared_ptr< CFileItem > GetCurrentListItem (int offset=0) override
const CFileItemList & CurrentDirectory () const
bool HasListItems () const override
Public Member Functions inherited from CGUIDialog
CGUIDialog (int id, const std::string &xmlFile, DialogModalityType modalityType=DialogModalityType::MODAL)
~CGUIDialog (void) override
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void Open (const std::string &param="")
void Open (bool bProcessRenderLoop, const std::string &param="")
bool OnBack (int actionID) override
bool IsDialogRunning () const override
bool IsDialog () const override
bool IsModalDialog () const override
virtual DialogModalityType GetModalityType () const
void SetAutoClose (unsigned int timeoutMs)
void ResetAutoClose (void)
void CancelAutoClose (void)
bool IsAutoClosed (void) const
void SetSound (bool OnOff)
bool IsSoundEnabled () const override
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
bool OnAction (const CAction &action) override
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool OnMessage (CGUIMessage &message) override
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsMediaWindow () const
virtual int GetViewContainerID () const
virtual int GetViewCount () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual CGUIControl * GetFirstFocusableControl (int id)
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Static Public Member Functions
static void AddItemPathToFileBrowserSources (std::vector< CMediaSource > &sources, const CFileItem &item)
static int ManageVideoItem (const std::shared_ptr< CFileItem > &item)
static bool UpdateVideoItemTitle (const std::shared_ptr< CFileItem > &pItem)
static bool CanDeleteVideoItem (const std::shared_ptr< CFileItem > &item)
static bool DeleteVideoItemFromDatabase (const std::shared_ptr< CFileItem > &item, bool unavailable=false)
static bool DeleteVideoItem (const std::shared_ptr< CFileItem > &item, bool unavailable=false)
static bool ManageMovieSets (const std::shared_ptr< CFileItem > &item)
static bool GetMoviesForSet (const CFileItem *setItem, CFileItemList &originalMovies, CFileItemList &selectedMovies)
static bool GetSetForMovie (const CFileItem *movieItem, std::shared_ptr< CFileItem > &selectedSet)
static bool SetMovieSet (const CFileItem *movieItem, const CFileItem *selectedSet)
static void ManageVideoVersions (const std::shared_ptr< CFileItem > &item)
static bool GetItemsForTag (const std::string &strHeading, const std::string &type, CFileItemList &items, int idTag=-1, bool showAll=true)
static bool AddItemsToTag (const std::shared_ptr< CFileItem > &tagItem)
static bool RemoveItemsFromTag (const std::shared_ptr< CFileItem > &tagItem)
static bool ChooseAndManageVideoItemArtwork (const std::shared_ptr< CFileItem > &item)
static bool ManageVideoItemArtwork (const std::shared_ptr< CFileItem > &item, const MediaType &type)
static std::string GetLocalizedVideoType (const std::string &strType)
static void ShowFor (const CFileItem &item)
Protected Member Functions
void OnInitWindow () override
Called on window open.
void Update ()
void SetLabel (int iControl, const std::string &strLabel)
void SetUserrating (int userrating) const
void ClearCastList ()
void OnSearch (std::string &strSearch)
Search the current directory for a string got from the virtual keyboard.
void DoSearch (std::string &strSearch, CFileItemList &items) const
Make the actual search for the OnSearch function.
void OnSearchItemFound (const CFileItem *pItem)
React on the selected search item.
bool OnManageVideoVersions ()
bool OnManageVideoExtras ()
void Play (bool resume=false)
void OnGetArt ()
void OnGetFanart ()
void OnSetUserrating () const
void PlayTrailer ()
Protected Member Functions inherited from CGUIDialog
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
void SetDefaults () override
void OnWindowLoaded () override
virtual void UpdateVisibility ()
virtual void Open_Internal (bool bProcessRenderLoop, const std::string &param="")
void OnDeinitWindow (int nextWindowID) override
void ProcessRenderLoop (bool renderOnly=false)
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void OnWindowUnload ()
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
virtual void SaveControlStates ()
virtual void RestoreControlStates ()
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Static Protected Member Functions
static bool UpdateVideoItemSortTitle (const std::shared_ptr< CFileItem > &pItem)
static bool LinkMovieToTvShow (const std::shared_ptr< CFileItem > &item, bool bRemove, CVideoDatabase &database)
Protected Attributes
std::shared_ptr< CFileItem > m_movieItem
CFileItemList * m_castList
bool m_bViewReview = false
bool m_bRefresh = false
bool m_bRefreshAll = true
bool m_hasUpdatedThumb = false
bool m_hasUpdatedUserrating = false
int m_startUserrating = -1
bool m_hasUpdatedItems {false}
Protected Attributes inherited from CGUIDialog
bool m_wasRunning
true if we were running during the last DoProcess()
bool m_autoClosing
bool m_enableSound
unsigned int m_showStartTime
unsigned int m_showDuration
bool m_bAutoClosed
DialogModalityType m_modalityType
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Private Member Functions
bool ChooseVideoVersion ()
Static Private Member Functions
static bool ManageVideoItemArtwork (const std::shared_ptr< CFileItem > &item, const MediaType &mediaType, const std::string &artType)
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIDialogVideoInfo()
CGUIDialogVideoInfo::CGUIDialogVideoInfo (void)
References CGUIWindow::KEEP_IN_MEMORY, and CGUIWindow::m_loadType.
~CGUIDialogVideoInfo()
CGUIDialogVideoInfo::~CGUIDialogVideoInfo (void) override
References m_castList.
Member Function Documentation
AddItemPathToFileBrowserSources()
static void CGUIDialogVideoInfo::AddItemPathToFileBrowserSources (std::vector< CMediaSource > & sources, const CFileItem & item) static
AddItemsToTag()
bool CGUIDialogVideoInfo::AddItemsToTag (const std::shared_ptr< CFileItem > & tagItem) static
References CVideoDatabase::AddTagToItem(), CDbUrl::FromString(), g_localizeStrings, CLocalizeStrings::Get(), GetItemsForTag(), CVideoDbUrl::GetItemType(), GetLocalizedVideoType(), CFileItem::GetVideoInfoTag(), index(), CVideoInfoTag::m_iDbId, CVideoDatabase::Open(), and CFileItemList::Size().
Referenced by ManageVideoItem().
CanDeleteVideoItem()
bool CGUIDialogVideoInfo::CanDeleteVideoItem (const std::shared_ptr< CFileItem > & item) static
References XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetEpisodeId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMovieId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMVideoId(), XFILE::CVideoDatabaseDirectory::GetQueryParams(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSeason(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSetId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetTvShowId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetVideoVersionId(), and XFILE::CVideoDatabaseDirectory::IsAllItem().
Referenced by DeleteVideoItemFromDatabase().
ChooseAndManageVideoItemArtwork()
bool CGUIDialogVideoInfo::ChooseAndManageVideoItemArtwork (const std::shared_ptr< CFileItem > & item) static
References ManageVideoItemArtwork().
Referenced by CGUIDialogVideoManager::ChooseArt(), ManageVideoItem(), CGUIWindowVideoNav::OnContextButton(), and OnGetArt().
ChooseVideoVersion()
bool CGUIDialogVideoInfo::ChooseVideoVersion () private
ClearCastList()
void CGUIDialogVideoInfo::ClearCastList () protected
References CFileItemList::Clear(), CONTROL_LIST, CGUIControl::GetID(), GUI_MSG_LABEL_RESET, m_castList, and OnMessage().
Referenced by OnMessage(), and SetMovie().
CurrentDirectory()
const CFileItemList & CGUIDialogVideoInfo::CurrentDirectory () const inline
References m_castList.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool().
DeleteVideoItem()
bool CGUIDialogVideoInfo::DeleteVideoItem (const std::shared_ptr< CFileItem > & item, bool unavailable = false) static
References CFileUtils::DeleteItemWithConfirm(), CUtil::DeleteVideoDatabaseDirectoryCache(), DeleteVideoItemFromDatabase(), g_passwordManager, URIUtils::GetDirectory(), URIUtils::GetFileName(), CServiceBroker::GetSettingsComponent(), URIUtils::HasSlashAtEnd(), CGUIPassword::IsMasterLockUnlocked(), LOCK_MODE_EVERYONE, URIUtils::RemoveSlashAtEnd(), CSettings::SETTING_FILELISTS_ALLOWFILEDELETION, and CUtil::SupportsWriteFileOperations().
Referenced by ManageVideoItem(), and CGUIWindowVideoNav::OnDeleteItem().
DeleteVideoItemFromDatabase()
bool CGUIDialogVideoInfo::DeleteVideoItemFromDatabase (const std::shared_ptr< CFileItem > & item, bool unavailable = false) static
References CanDeleteVideoItem(), CVideoDatabase::DeleteEpisode(), CVideoDatabase::DeleteMovie(), CVideoDatabase::DeleteMusicVideo(), CVideoDatabase::DeleteSet(), CVideoDatabase::DeleteTag(), CVideoDatabase::DeleteTvShow(), EPISODES, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CVideoLibraryQueue::GetInstance(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), MOVIE_SETS, MOVIES, MUSICVIDEOS, CVideoDatabase::Open(), CGUIDialog::Open(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), TVSHOWS, and WINDOW_DIALOG_YES_NO.
Referenced by DeleteVideoItem(), CGUIWindowMusicNav::OnContextButton(), and CGUIWindowVideoBase::PlayItem().
DoSearch()
void CGUIDialogVideoInfo::DoSearch (std::string & strSearch, CFileItemList & items) const protected
Make the actual search for the OnSearch function.
Parameters
strSearch The search string
items Items Found
References CGUIWindowVideoBase::AppendAndClearSearchItems(), CDatabase::Close(), g_localizeStrings, CLocalizeStrings::Get(), CVideoDatabase::GetEpisodesByActor(), CVideoDatabase::GetMoviesByActor(), CVideoDatabase::GetMusicVideosByArtist(), CServiceBroker::GetSettingsComponent(), CVideoDatabase::GetTvShowsByActor(), CFileItem::GetVideoInfoTag(), label, CVideoInfoTag::m_strShowTitle, CVideoInfoTag::m_strTitle, CVideoInfoTag::m_type, MediaTypeAlbum, CMusicDatabase::Open(), CVideoDatabase::Open(), CMusicDatabase::SearchAlbumsByArtistName(), CFileItem::SetLabel(), and CFileItemList::Size().
Referenced by OnSearch().
GetCurrentListItem()
std::shared_ptr< CFileItem > CGUIDialogVideoInfo::GetCurrentListItem (int offset = 0) inline override virtual
Reimplemented from CGUIWindow.
References m_movieItem.
Referenced by CGUIWindowVideoBase::ShowInfo().
GetItemsForTag()
bool CGUIDialogVideoInfo::GetItemsForTag (const std::string & strHeading, const std::string & type, CFileItemList & items, int idTag = -1, bool showAll = true) static
References CFileItemList::Add(), CDbUrl::AddOption(), CGUIDialogSelect::EnableButton(), CDbUrl::FromString(), CFileItemList::Get(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedItems(), CServiceBroker::GetSettingsComponent(), CVideoDatabase::GetSortedVideos(), CGUIComponent::GetWindowManager(), MediaTypeMovie, MediaTypeMusicVideo, MediaTypeNone, MediaTypeTvShow, CVideoDatabase::Open(), CGUIDialog::Open(), CDatabase::PrepareSQL(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CGUIDialogSelect::SetMultiSelection(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CFileItemList::Size(), CFileItemList::Sort(), SortAttributeIgnoreArticle, SortAttributeNone, SortByLabel, SortOrderAscending, CDbUrl::ToString(), CDatabase::Filter::where, and WINDOW_DIALOG_SELECT.
Referenced by AddItemsToTag(), CGUIWindowVideoNav::OnClick(), and RemoveItemsFromTag().
GetLocalizedVideoType()
std::string CGUIDialogVideoInfo::GetLocalizedVideoType (const std::string & strType) static
References g_localizeStrings, CLocalizeStrings::Get(), CMediaTypes::IsMediaType(), MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, and MediaTypeTvShow.
Referenced by AddItemsToTag(), ManageVideoItem(), CGUIWindowVideoNav::OnClick(), and RemoveItemsFromTag().
GetMoviesForSet()
bool CGUIDialogVideoInfo::GetMoviesForSet (const CFileItem * setItem, CFileItemList & originalMovies, CFileItemList & selectedMovies) static
References CFileItemList::Add(), XFILE::DIR_FLAG_DEFAULTS, CGUIDialogSelect::EnableButton(), g_localizeStrings, CFileItemList::Get(), CLocalizeStrings::Get(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedItems(), CServiceBroker::GetSettingsComponent(), CVideoDatabase::GetSortedVideos(), CFileItem::GetVideoInfoTag(), CGUIComponent::GetWindowManager(), CFileItem::HasVideoInfoTag(), CGUIDialogBoxBase::IsConfirmed(), CVideoInfoTag::m_iDbId, MediaTypeMovie, CVideoDatabase::Open(), CGUIDialog::Open(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CGUIDialogSelect::SetMultiSelection(), CGUIDialogSelect::SetSelected(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CFileItemList::Size(), CFileItemList::Sort(), SortAttributeIgnoreArticle, SortAttributeNone, SortByLabel, SortOrderAscending, and WINDOW_DIALOG_SELECT.
Referenced by ManageMovieSets().
GetSetForMovie()
bool CGUIDialogVideoInfo::GetSetForMovie (const CFileItem * movieItem, std::shared_ptr< CFileItem > & selectedSet) static
References CFileItemList::AddFront(), CVideoDatabase::AddSet(), XFILE::DIR_FLAG_DEFAULTS, CGUIDialogSelect::EnableButton(), g_localizeStrings, CFileItemList::Get(), CLocalizeStrings::Get(), CVideoDatabase::GetArtForItem(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedFileItem(), CVideoDatabase::GetSetById(), CServiceBroker::GetSettingsComponent(), CFileItem::GetVideoInfoTag(), CGUIComponent::GetWindowManager(), CFileItem::HasVideoInfoTag(), CVideoInfoTag::SetInfo::id, CGUIDialogSelect::IsButtonPressed(), CGUIDialogBoxBase::IsConfirmed(), CVideoInfoTag::m_iDbId, CVideoInfoTag::m_set, MediaTypeMovie, MediaTypeVideoCollection, CVideoDatabase::Open(), CGUIDialog::Open(), CFileItemList::Remove(), CGUIDialogSelect::Reset(), CVideoDatabase::SetArtForItem(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CGUIDialogSelect::SetSelected(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CGUIKeyboardFactory::ShowAndGetInput(), CFileItemList::Size(), CFileItemList::Sort(), SortAttributeIgnoreArticle, SortAttributeNone, SortByLabel, SortOrderAscending, and WINDOW_DIALOG_SELECT.
Referenced by ManageVideoItem().
GetThumbnail()
std::string CGUIDialogVideoInfo::GetThumbnail () const
References m_movieItem.
Referenced by CGUIWindowVideoBase::ShowInfo().
HasListItems()
bool CGUIDialogVideoInfo::HasListItems () const inline override virtual
Reimplemented from CGUIWindow.
HasUpdatedItems()
bool CGUIDialogVideoInfo::HasUpdatedItems () const inline
References m_hasUpdatedItems.
Referenced by CGUIWindowVideoBase::ShowInfo().
HasUpdatedThumb()
bool CGUIDialogVideoInfo::HasUpdatedThumb () const inline
References m_hasUpdatedThumb.
Referenced by CGUIWindowVideoBase::ShowInfo().
HasUpdatedUserrating()
bool CGUIDialogVideoInfo::HasUpdatedUserrating () const inline
References m_hasUpdatedUserrating.
Referenced by CGUIWindowVideoBase::ShowInfo().
LinkMovieToTvShow()
bool CGUIDialogVideoInfo::LinkMovieToTvShow (const std::shared_ptr< CFileItem > & item, bool bRemove, CVideoDatabase & database) static protected
References CFileItemList::Add(), CServiceBroker::GetGUI(), CVideoDatabase::GetLinksToTvShow(), CGUIDialogSelect::GetSelectedItem(), CServiceBroker::GetSettingsComponent(), CVideoDatabase::GetTvShowInfo(), CVideoDatabase::GetTvShowsNav(), CFileItem::GetVideoInfoTag(), CGUIComponent::GetWindowManager(), CFileItemList::IsEmpty(), CVideoDatabase::LinkMovieToTvshow(), CVideoInfoTag::m_iDbId, CGUIDialog::Open(), CFileItemList::Remove(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CFileItemList::Size(), CFileItemList::Sort(), SortAttributeIgnoreArticle, SortAttributeNone, SortByLabel, SortOrderAscending, VideoDbDetailsNone, and WINDOW_DIALOG_SELECT.
Referenced by ManageVideoItem().
ManageMovieSets()
bool CGUIDialogVideoInfo::ManageMovieSets (const std::shared_ptr< CFileItem > & item) static
References compFileItemsByDbId(), CFileItemList::GetList(), GetMoviesForSet(), SetMovieSet(), and CFileItemList::Size().
Referenced by ManageVideoItem().
ManageVideoItem()
int CGUIDialogVideoInfo::ManageVideoItem (const std::shared_ptr< CFileItem > & item) static
References CContextButtons::Add(), AddItemsToTag(), ChooseAndManageVideoItemArtwork(), CDatabase::Close(), CONTEXT_BUTTON_DELETE, CONTEXT_BUTTON_EDIT, CONTEXT_BUTTON_EDIT_SORTTITLE, CONTEXT_BUTTON_LINK_MOVIE, CONTEXT_BUTTON_MANAGE_VIDEOVERSIONS, CONTEXT_BUTTON_MOVIESET_ADD_REMOVE_ITEMS, CONTEXT_BUTTON_SET_ART, CONTEXT_BUTTON_SET_MOVIESET, CONTEXT_BUTTON_TAGS_ADD_ITEMS, CONTEXT_BUTTON_TAGS_REMOVE_ITEMS, CONTEXT_BUTTON_UNLINK_BOOKMARK, CONTEXT_BUTTON_UNLINK_MOVIE, CVideoDatabase::DeleteBookMarkForEpisode(), DeleteVideoItem(), CDbUrl::FromString(), g_localizeStrings, CLocalizeStrings::Get(), CContextMenuManager::GetAddonItems(), CServiceBroker::GetContextMenuManager(), CVideoDbUrl::GetItemType(), GetLocalizedVideoType(), GetSetForMovie(), CVideoDatabase::HasContent(), CVideoDatabase::IsLinkedToTvshow(), LinkMovieToTvShow(), CONTEXTMENU::LoopFrom(), CContextMenuManager::MANAGE, ManageMovieSets(), ManageVideoVersions(), MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSeason, MediaTypeTvShow, MediaTypeVideoCollection, CVideoDatabase::Open(), RemoveItemsFromTag(), SetMovieSet(), CGUIDialogContextMenu::ShowAndGetChoice(), TVSHOWS, UpdateVideoItemSortTitle(), and UpdateVideoItemTitle().
Referenced by CGUIWindowVideoNav::OnContextButton().
ManageVideoItemArtwork() [1/2]
bool CGUIDialogVideoInfo::ManageVideoItemArtwork (const std::shared_ptr< CFileItem > & item, const MediaType & mediaType, const std::string & artType) static private
Todo:
Do we need to clear the cached image?
References CFileItemList::Add(), KODI::VIDEO::CVideoInfoScanner::ApplyThumbToFolder(), KODI::VIDEO::IVideoItemArtworkHandlerFactory::Create(), CUtil::DeleteVideoDatabaseDirectoryCache(), IMAGE_FILES::CImageFileURL::FromFile(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CMediaSourceSettings::GetInstance(), CMediaManager::GetLocalDrives(), CServiceBroker::GetMediaManager(), CMediaSourceSettings::GetSources(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_REFRESH_THUMBS, index(), CGUIWindowManager::SendMessage(), and CGUIDialogFileBrowser::ShowAndGetImage().
ManageVideoItemArtwork() [2/2]
bool CGUIDialogVideoInfo::ManageVideoItemArtwork (const std::shared_ptr< CFileItem > & item, const MediaType & type) static
References ManageVideoItemArtwork().
Referenced by ChooseAndManageVideoItemArtwork(), ManageVideoItemArtwork(), and OnGetFanart().
ManageVideoVersions()
void CGUIDialogVideoInfo::ManageVideoVersions (const std::shared_ptr< CFileItem > & item) static
References CGUIDialogVideoManagerVersions::ManageVideoVersions().
Referenced by ManageVideoItem().
NeedRefresh()
bool CGUIDialogVideoInfo::NeedRefresh () const
References m_bRefresh.
Referenced by CGUIWindowVideoBase::ShowInfo().
OnAction()
bool CGUIDialogVideoInfo::OnAction (const CAction & action) override virtual
Reimplemented from CGUIDialog.
References ACTION_DECREASE_RATING, ACTION_INCREASE_RATING, ACTION_SHOW_INFO, Close(), m_movieItem, CGUIDialog::OnAction(), and SetUserrating().
OnGetArt()
void CGUIDialogVideoInfo::OnGetArt () protected
References ChooseAndManageVideoItemArtwork(), m_hasUpdatedThumb, m_movieItem, and Update().
Referenced by OnMessage().
OnGetFanart()
void CGUIDialogVideoInfo::OnGetFanart () protected
References m_hasUpdatedThumb, m_movieItem, ManageVideoItemArtwork(), and Update().
Referenced by OnMessage().
OnInitWindow()
void CGUIDialogVideoInfo::OnInitWindow (void) override protected virtual
Called on window open.
Restores the control state(s)
Sets initial visibility of controls
Queue WindowOpen animation
Set overlay state Override this function and do any window-specific initialisation such as filling control contents and setting control focus before calling the base method.
Reimplemented from CGUIWindow.
References CGUIPassword::bMasterUser, CONTROL_BTN_GET_FANART, CONTROL_BTN_GET_THUMB, CONTROL_BTN_REFRESH, CONTROL_BTN_USERRATING, CONTROL_DISABLE, CONTROL_ENABLE_ON_CONDITION, g_passwordManager, CServiceBroker::GetSettingsComponent(), m_bRefresh, m_bRefreshAll, m_bViewReview, m_hasUpdatedThumb, m_hasUpdatedUserrating, m_movieItem, MediaTypeVideoCollection, MOVIES, CGUIWindow::OnInitWindow(), TVSHOWS, and Update().
OnManageVideoExtras()
bool CGUIDialogVideoInfo::OnManageVideoExtras () protected
References m_movieItem, and CGUIDialogVideoManagerExtras::ManageVideoExtras().
Referenced by OnMessage().
OnManageVideoVersions()
bool CGUIDialogVideoInfo::OnManageVideoVersions () protected
References m_movieItem, and CGUIDialogVideoManagerVersions::ManageVideoVersions().
Referenced by OnMessage().
OnMessage()
bool CGUIDialogVideoInfo::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIDialog.
References ACTION_MOUSE_LEFT_CLICK, ACTION_SELECT_ITEM, ClearCastList(), CDatabase::Close(), Close(), CONTROL_BTN_DIRECTOR, CONTROL_BTN_GET_FANART, CONTROL_BTN_GET_THUMB, CONTROL_BTN_MANAGE_VIDEO_EXTRAS, CONTROL_BTN_MANAGE_VIDEO_VERSIONS, CONTROL_BTN_PLAY, CONTROL_BTN_PLAY_TRAILER, CONTROL_BTN_REFRESH, CONTROL_BTN_RESUME, CONTROL_BTN_TRACKS, CONTROL_BTN_USERRATING, CONTROL_LIST, CFileItemList::Get(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIMessage::GetItem(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIMessage::GetSenderId(), CGUIComponent::GetWindowManager(), GUI_MSG_CLICKED, GUI_MSG_ITEM_SELECTED, GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_ITEM, GUI_MSG_WINDOW_DEINIT, CGUIWindow::IsActive(), m_bRefresh, m_bRefreshAll, m_bViewReview, m_castList, m_hasUpdatedItems, m_hasUpdatedUserrating, m_movieItem, m_startUserrating, MediaTypeTvShow, MediaTypeVideoCollection, CGUIDialogYesNo::NO_TIMEOUT, OnGetArt(), OnGetFanart(), OnManageVideoExtras(), OnManageVideoVersions(), CGUIDialog::OnMessage(), OnMessage(), OnSearch(), OnSetUserrating(), CVideoDatabase::Open(), CGUIDialog::Open(), Play(), PlayTrailer(), CGUIDialogSelect::Reset(), SetMovie(), CVideoDatabase::SetPathHash(), CVideoDatabase::SetVideoUserRating(), CGUIDialogYesNo::ShowAndGetInput(), CFileItemList::Size(), Update(), and WINDOW_DIALOG_SELECT.
Referenced by ClearCastList(), OnMessage(), and Update().
OnSearch()
void CGUIDialogVideoInfo::OnSearch (std::string & strSearch) protected
Search the current directory for a string got from the virtual keyboard.
Parameters
strSearch The search string
References CGUIDialogSelect::Add(), CGUIWindow::Close(), DoSearch(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CVideoInfoTag::GetPlayCount(), CGUIDialogSelect::GetSelectedItem(), CFileItem::GetVideoInfoTag(), CGUIComponent::GetWindowManager(), CVideoThumbLoader::LoadItem(), OnSearchItemFound(), CGUIDialogProgress::Open(), CGUIDialog::Open(), CGUIDialogProgress::Progress(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CGUIDialogSelect::SetUseDetails(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), CFileItemList::Size(), WINDOW_DIALOG_PROGRESS, and WINDOW_DIALOG_SELECT.
Referenced by OnMessage().
OnSearchItemFound()
void CGUIDialogVideoInfo::OnSearchItemFound (const CFileItem * pItem) protected
React on the selected search item.
Parameters
pItem Search result item
References CDatabase::Close(), Close(), EPISODES, CVideoInfoTag::GetAssetInfo(), CVideoDatabase::GetEpisodeInfo(), CVideoInfoTag::CAssetInfo::GetId(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMusicVideoInfo(), CFileItem::GetPath(), CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetTvShowInfo(), CFileItem::GetVideoContentType(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iIdSeason, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_type, MediaTypeSeason, MOVIES, MUSICALBUMS, MUSICVIDEOS, CVideoDatabase::Open(), CGUIDialog::Open(), SetMovie(), CGUIDialogMusicInfo::ShowFor(), and TVSHOWS.
Referenced by OnSearch().
OnSetUserrating()
void CGUIDialogVideoInfo::OnSetUserrating () const protected
References CGUIDialogSelect::Add(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedItem(), CGUIComponent::GetWindowManager(), m_movieItem, CGUIDialog::Open(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetSelected(), SetUserrating(), and WINDOW_DIALOG_SELECT.
Referenced by OnMessage().
Play()
void CGUIDialogVideoInfo::Play (bool resume = false) protected
References KODI::VIDEO::GUILIB::ACTION_PLAY_FROM_BEGINNING, KODI::VIDEO::GUILIB::ACTION_RESUME, CGUIWindowManager::ActivateWindow(), Close(), CONTROL_BTN_RESUME, CGUIControlLookup::GetControl(), CServiceBroker::GetGUI(), CVideoInfoTag::GetPath(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iIdShow, CVideoInfoTag::m_iSeason, m_movieItem, CVideoInfoTag::m_type, MediaTypeSeason, MediaTypeTvShow, MediaTypeVideoCollection, CGUIDialog::Open(), CGUIWindowManager::SendMessage(), SetMovie(), CGUIMessage::SetStringParam(), and WINDOW_VIDEO_NAV.
Referenced by OnMessage().
PlayTrailer()
void CGUIDialogVideoInfo::PlayTrailer () protected
References Close(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAY_TRAILER, and m_movieItem.
Referenced by OnMessage().
RefreshAll()
bool CGUIDialogVideoInfo::RefreshAll () const
References m_bRefreshAll.
Referenced by CGUIWindowVideoBase::ShowInfo().
RemoveItemsFromTag()
bool CGUIDialogVideoInfo::RemoveItemsFromTag (const std::shared_ptr< CFileItem > & tagItem) static
References CDbUrl::FromString(), g_localizeStrings, CLocalizeStrings::Get(), GetItemsForTag(), CVideoDbUrl::GetItemType(), GetLocalizedVideoType(), CFileItem::GetVideoInfoTag(), index(), CVideoInfoTag::m_iDbId, CVideoDatabase::Open(), CVideoDatabase::RemoveTagFromItem(), and CFileItemList::Size().
Referenced by ManageVideoItem().
SetLabel()
void CGUIDialogVideoInfo::SetLabel (int iControl, const std::string & strLabel) protected
References SET_CONTROL_LABEL.
Referenced by Update().
SetMovie()
void CGUIDialogVideoInfo::SetMovie (const CFileItem * item)
References CFileItemList::Add(), ClearCastList(), CDatabase::Close(), CUtil::DeleteVideoDatabaseDirectoryCache(), KODI::VIDEO::UTILS::FindTrailer(), g_localizeStrings, CLocalizeStrings::Get(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtistByName(), CVideoDatabase::GetMoviesNav(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetTextureCache(), CScraperUrl::GetThumbUrl(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CVideoInfoTag::SetInfo::id, URIUtils::IsInternetStream(), CVideoThumbLoader::LoadItem(), m_castList, m_movieItem, CVideoInfoTag::m_set, m_startUserrating, CVideoInfoTag::m_type, MediaTypeArtist, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeVideoCollection, MOVIES, CMusicDatabase::Open(), CVideoDatabase::Open(), CFileItemList::SetContent(), CVideoDatabase::SetSingleValue(), CSettings::SETTING_VIDEOLIBRARY_ACTORTHUMBS, CSettings::SETTING_VIDEOLIBRARY_ARTWORK_LEVEL, CFileItemList::Sort(), SortBySortTitle, SortOrderDescending, CMediaTypes::ToPlural(), VIDEODB_ID_TRAILER, VideoDbDetailsAll, and CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_NONE.
Referenced by OnMessage(), OnSearchItemFound(), Play(), and CGUIWindowVideoBase::ShowInfo().
SetMovieSet()
bool CGUIDialogVideoInfo::SetMovieSet (const CFileItem * movieItem, const CFileItem * selectedSet) static
References CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CVideoInfoTag::m_iDbId, CVideoDatabase::Open(), and CVideoDatabase::SetMovieSet().
Referenced by ManageMovieSets(), and ManageVideoItem().
SetUserrating()
void CGUIDialogVideoInfo::SetUserrating (int userrating) const protected
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_ITEM, m_movieItem, and CGUIWindowManager::SendMessage().
Referenced by OnAction(), and OnSetUserrating().
ShowFor()
void CGUIDialogVideoInfo::ShowFor (const CFileItem & item) static
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIWindowVideoBase::OnItemInfo(), and WINDOW_VIDEO_NAV.
Referenced by CONTEXTMENU::CVideoInfo::Execute(), XBMCAddon::xbmcgui::Dialog::info(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoSelectActionProcessor::OnInfoSelected(), CGUIWindowMusicBase::OnItemInfo(), and KODI::UTILS::GUILIB::CGUIContentUtils::ShowInfoForItem().
Update()
void CGUIDialogVideoInfo::Update () protected
References CONTROL_BTN_PLAY, CONTROL_BTN_RESUME, CONTROL_BTN_TRACKS, CONTROL_DISABLE, CONTROL_ENABLE, CONTROL_IMAGE, CONTROL_LIST, CONTROL_TEXTAREA, CSettingUtils::FindIntInList(), CGUIImage::FreeResources(), g_localizeStrings, CLocalizeStrings::Get(), CGUIControlLookup::GetControl(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_BIND, GUI_MSG_NOTIFY_ALL, GUI_MSG_REFRESH_THUMBS, m_bViewReview, m_castList, m_hasUpdatedThumb, m_movieItem, MediaTypeEpisode, MediaTypeMovie, MediaTypeSeason, MediaTypeTvShow, MediaTypeVideoCollection, OnMessage(), CGUIWindowManager::SendMessage(), SET_CONTROL_HIDDEN, SET_CONTROL_LABEL, SET_CONTROL_VISIBLE, CGUIImage::SetFileName(), SetLabel(), CSettings::SETTING_VIDEOLIBRARY_SHOWUNWATCHEDPLOTS, CSettings::VIDEOLIBRARY_PLOTS_SHOW_UNWATCHED_MOVIES, and CSettings::VIDEOLIBRARY_PLOTS_SHOW_UNWATCHED_TVSHOWEPISODES.
Referenced by OnGetArt(), OnGetFanart(), OnInitWindow(), and OnMessage().
UpdateVideoItemSortTitle()
bool CGUIDialogVideoInfo::UpdateVideoItemSortTitle (const std::shared_ptr< CFileItem > & pItem) static protected
References g_localizeStrings, CLocalizeStrings::Get(), CVideoLibraryQueue::GetInstance(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetTvShowInfo(), MOVIES, CVideoDatabase::Open(), CGUIKeyboardFactory::ShowAndGetInput(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), TVSHOWS, CVideoDatabase::UpdateVideoSortTitle(), and VideoDbDetailsNone.
Referenced by ManageVideoItem().
UpdateVideoItemTitle()
bool CGUIDialogVideoInfo::UpdateVideoItemTitle (const std::shared_ptr< CFileItem > & pItem) static
References g_localizeStrings, CLocalizeStrings::Get(), CVideoDatabase::GetEpisodeInfo(), CVideoLibraryQueue::GetInstance(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMusicVideoInfo(), CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetSetInfo(), CVideoDatabase::GetTvShowInfo(), MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSeason, MediaTypeTvShow, MediaTypeVideoCollection, CVideoDatabase::Open(), CVideoDatabase::SetDetailsForSeason(), CGUIKeyboardFactory::ShowAndGetInput(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), CVideoDatabase::UpdateMovieTitle(), and VideoDbDetailsNone.
Referenced by ManageVideoItem(), and CGUIWindowMusicNav::OnContextButton().
Member Data Documentation
m_bRefresh
bool CGUIDialogVideoInfo::m_bRefresh = false protected
Referenced by NeedRefresh(), OnInitWindow(), and OnMessage().
m_bRefreshAll
bool CGUIDialogVideoInfo::m_bRefreshAll = true protected
Referenced by OnInitWindow(), OnMessage(), and RefreshAll().
m_bViewReview
bool CGUIDialogVideoInfo::m_bViewReview = false protected
Referenced by OnInitWindow(), OnMessage(), and Update().
m_castList
CFileItemList* CGUIDialogVideoInfo::m_castList protected
Referenced by ClearCastList(), CurrentDirectory(), OnMessage(), SetMovie(), Update(), and ~CGUIDialogVideoInfo().
m_hasUpdatedItems
bool CGUIDialogVideoInfo::m_hasUpdatedItems {false} protected
Referenced by HasUpdatedItems(), and OnMessage().
m_hasUpdatedThumb
bool CGUIDialogVideoInfo::m_hasUpdatedThumb = false protected
Referenced by HasUpdatedThumb(), OnGetArt(), OnGetFanart(), OnInitWindow(), and Update().
m_hasUpdatedUserrating
bool CGUIDialogVideoInfo::m_hasUpdatedUserrating = false protected
Referenced by HasUpdatedUserrating(), OnInitWindow(), and OnMessage().
m_movieItem
std::shared_ptr<CFileItem> CGUIDialogVideoInfo::m_movieItem protected
Referenced by GetCurrentListItem(), GetThumbnail(), OnAction(), OnGetArt(), OnGetFanart(), OnInitWindow(), OnManageVideoExtras(), OnManageVideoVersions(), OnMessage(), OnSetUserrating(), Play(), PlayTrailer(), SetMovie(), SetUserrating(), and Update().
m_startUserrating
int CGUIDialogVideoInfo::m_startUserrating = -1 protected
Referenced by OnMessage(), and SetMovie().
The documentation for this class was generated from the following files:
GUIDialogVideoInfo.h
GUIDialogVideoInfo.cpp