Kodi Documentation: AE::CAESinkFactory Class Reference
AE::CAESinkFactory Class Reference
#include <AESinkFactory.h>
Static Public Member Functions
static void RegisterSink (const AESinkRegEntry &regEntry)
static void ClearSinks ()
static bool HasSinks ()
static AESinkDevice ParseDevice (const std::string &device)
static std::unique_ptr< IAESink > Create (const std::string &device, AEAudioFormat &desiredFormat)
static void EnumerateEx (std::vector< AESinkInfo > &list, bool force, const std::string &driver)
static void Cleanup ()
Static Protected Attributes
static std::map< std::string, AESinkRegEntry > m_AESinkRegEntry
Member Function Documentation
Cleanup()
void CAESinkFactory::Cleanup () static
References m_AESinkRegEntry.
Referenced by ActiveAE::CActiveAESink::Dispose().
ClearSinks()
void CAESinkFactory::ClearSinks () static
References m_AESinkRegEntry.
Referenced by CWinSystemOSX::CWinSystemOSX(), CWinSystemWin10::CWinSystemWin10(), CWinSystemWin32::CWinSystemWin32(), and CXBMCApp::onStart().
Create()
std::unique_ptr< IAESink > CAESinkFactory::Create (const std::string & device, AEAudioFormat & desiredFormat) static
References AE::AESinkDevice::driver, m_AESinkRegEntry, AE::AESinkDevice::name, and ParseDevice().
Referenced by ActiveAE::CActiveAESink::OpenSink().
EnumerateEx()
void CAESinkFactory::EnumerateEx (std::vector< AESinkInfo > & list, bool force, const std::string & driver) static
References m_AESinkRegEntry, and AE::AESinkInfo::m_deviceInfoList.
Referenced by ActiveAE::CActiveAESink::EnumerateSinkList().
HasSinks()
bool CAESinkFactory::HasSinks () static
References m_AESinkRegEntry.
Referenced by ActiveAE::CActiveAESink::EnumerateSinkList(), and ActiveAE::CActiveAE::StateMachine().
ParseDevice()
AESinkDevice CAESinkFactory::ParseDevice (const std::string & device) static
References m_AESinkRegEntry, and AE::AESinkDevice::name.
Referenced by ActiveAE::CActiveAE::Configure(), Create(), ActiveAE::CActiveAESink::GetDeviceType(), ActiveAE::CActiveAESink::NeedIECPacking(), ActiveAE::CActiveAE::NeedReconfigureSink(), ActiveAE::CActiveAESink::OpenSink(), ActiveAE::CActiveAESink::SupportsFormat(), ActiveAE::CActiveAESink::ValidateOuputDevice(), and ActiveAE::CActiveAE::ValidateOutputDevices().
RegisterSink()
void CAESinkFactory::RegisterSink (const AESinkRegEntry & regEntry) static
References IAE::DeviceChange(), CServiceBroker::GetActiveAE(), m_AESinkRegEntry, and AE::AESinkRegEntry::sinkName.
Referenced by CAESinkALSA::Register(), CAESinkAUDIOTRACK::Register(), CAESinkDARWINIOS::Register(), CAESinkDARWINOSX::Register(), CAESinkDARWINTVOS::Register(), CAESinkDirectSound::Register(), CAESinkOSS::Register(), CAESinkSNDIO::Register(), CAESinkStarfish::Register(), CAESinkWASAPI::Register(), CAESinkXAudio::Register(), AE::SINK::CAESinkPipewire::Register(), and CAESinkPULSE::Register().
Member Data Documentation
m_AESinkRegEntry
std::map< std::string, AESinkRegEntry > CAESinkFactory::m_AESinkRegEntry static protected
Referenced by Cleanup(), ClearSinks(), Create(), EnumerateEx(), HasSinks(), ParseDevice(), and RegisterSink().
The documentation for this class was generated from the following files:
AESinkFactory.h
AESinkFactory.cpp