Kodi Documentation: XFILE::CMusicDatabaseDirectory Class Reference
XFILE::CMusicDatabaseDirectory Class Reference
#include <MusicDatabaseDirectory.h>
Public Member Functions
CMusicDatabaseDirectory (void)
~CMusicDatabaseDirectory (void) override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool AllowAll () const override
Whether to allow all files/folders to be listed.
bool Exists (const CURL &url) override
Check for directory existence.
bool IsArtistDir (const std::string &strDirectory)
void ClearDirectoryCache (const std::string &strDirectory)
bool ContainsSongs (const std::string &path)
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool Create (const CURL &url)
Create the directory.
virtual bool Remove (const CURL &url)
Removes the directory.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Static Public Member Functions
static MUSICDATABASEDIRECTORY::NODE_TYPE GetDirectoryChildType (const std::string &strPath)
static MUSICDATABASEDIRECTORY::NODE_TYPE GetDirectoryType (const std::string &strPath)
static MUSICDATABASEDIRECTORY::NODE_TYPE GetDirectoryParentType (const std::string &strPath)
static bool GetDirectoryNodeInfo (const std::string &strPath, MUSICDATABASEDIRECTORY::NODE_TYPE &type, MUSICDATABASEDIRECTORY::NODE_TYPE &childtype, MUSICDATABASEDIRECTORY::CQueryParams &params)
static bool IsAllItem (const std::string &strDirectory)
static bool GetLabel (const std::string &strDirectory, std::string &strLabel)
static bool CanCache (const std::string &strPath)
static std::string GetIcon (const std::string &strDirectory)
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Additional Inherited Members
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CMusicDatabaseDirectory()
CMusicDatabaseDirectory::CMusicDatabaseDirectory (void) default
~CMusicDatabaseDirectory()
CMusicDatabaseDirectory::~CMusicDatabaseDirectory (void) override default
Member Function Documentation
AllowAll()
bool XFILE::CMusicDatabaseDirectory::AllowAll () const inline override virtual
Whether to allow all files/folders to be listed.
Returns
Returns true if all files/folder should be listed.
Reimplemented from XFILE::IDirectory.
CanCache()
bool CMusicDatabaseDirectory::CanCache (const std::string & strPath) static
References XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateMusicDbPath().
Referenced by CFileItemList::AlwaysCache().
ClearDirectoryCache()
void CMusicDatabaseDirectory::ClearDirectoryCache (const std::string & strDirectory)
References Crc32::ComputeFromLowerCase(), XFILE::CFile::Delete(), URIUtils::RemoveSlashAtEnd(), and CLegacyPathTranslation::TranslateMusicDbPath().
ContainsSongs()
bool CMusicDatabaseDirectory::ContainsSongs (const std::string & path)
References GetDirectoryChildType(), XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_DISC, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SINGLES, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG, and XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG_TOP100.
Referenced by anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist().
Exists()
bool CMusicDatabaseDirectory::Exists (const CURL & url) override virtual
Check for directory existence.
Parameters
url Directory to check.
Returns
Returns true, if directory exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
References XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateMusicDbPath().
GetDirectory()
bool CMusicDatabaseDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References CDbUrl::AppendPath(), CDatabase::Close(), CDbUrl::FromString(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetAlbumId(), GetDirectoryNodeInfo(), CMusicDatabase::GetDiscsCount(), CServiceBroker::GetGUI(), GetIcon(), CGUIListItem::GetLabel(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetTextureManager(), CGUITextureManager::HasTexture(), CMusicDatabase::IsAlbumBoxset(), CFileItem::m_dwSize, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_DISC, CMusicDatabase::Open(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), CFileItem::SetLabel(), CFileItem::SetPath(), CSettings::SETTING_MUSICLIBRARY_SHOWDISCS, CFileItemList::Size(), CDbUrl::ToString(), and CLegacyPathTranslation::TranslateMusicDbPath().
Referenced by MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), and MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo().
GetDirectoryChildType()
NODE_TYPE CMusicDatabaseDirectory::GetDirectoryChildType (const std::string & strPath) static
References XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateMusicDbPath().
Referenced by CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), ContainsSongs(), MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), CGUIWindowMusicNav::GetDirectory(), GetIcon(), and CGUIViewStateMusicDatabase::SaveViewState().
GetDirectoryNodeInfo()
bool CMusicDatabaseDirectory::GetDirectoryNodeInfo (const std::string & strPath, MUSICDATABASEDIRECTORY::NODE_TYPE & type, MUSICDATABASEDIRECTORY::NODE_TYPE & childtype, MUSICDATABASEDIRECTORY::CQueryParams & params) static
References XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetNodeInfo(), and CLegacyPathTranslation::TranslateMusicDbPath().
Referenced by GetDirectory(), and CMusicDbUrl::parse().
GetDirectoryParentType()
NODE_TYPE CMusicDatabaseDirectory::GetDirectoryParentType (const std::string & strPath) static
References XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetChildType(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetParent(), XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateMusicDbPath().
Referenced by MUSIC_UTILS::IsItemPlayable().
GetDirectoryType()
NODE_TYPE CMusicDatabaseDirectory::GetDirectoryType (const std::string & strPath) static
References XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateMusicDbPath().
Referenced by UPNP::BuildObject(), CGUIWindowMusicNav::GetContextButtons(), and IsArtistDir().
GetIcon()
std::string CMusicDatabaseDirectory::GetIcon (const std::string & strDirectory) static
References GetDirectoryChildType(), XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ARTIST, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ROLE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SINGLES, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SOURCE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_TOP100, and XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_YEAR.
Referenced by GetDirectory().
GetLabel()
bool CMusicDatabaseDirectory::GetLabel (const std::string & strDirectory, std::string & strLabel) static
References g_localizeStrings, CLocalizeStrings::Get(), CMusicDatabase::GetAlbumById(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetAlbumId(), CMusicDatabase::GetArtistById(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetArtistId(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), CMusicDatabase::GetGenreById(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetGenreId(), XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ARTIST, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_OVERVIEW, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ROLE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SINGLES, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SOURCE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_YEAR, CMusicDatabase::Open(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), and CLegacyPathTranslation::TranslateMusicDbPath().
Referenced by UPNP::CUPnPServer::Build(), and CGUIWindowMusicNav::UpdateButtons().
IsAllItem()
bool CMusicDatabaseDirectory::IsAllItem (const std::string & strDirectory) static
References CURL::GetWithoutOptions().
Referenced by CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), and CGUIWindowMusicNav::GetContextButtons().
IsArtistDir()
bool CMusicDatabaseDirectory::IsArtistDir (const std::string & strDirectory)
References GetDirectoryType(), node, and XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ARTIST.
Referenced by CGUIWindowMusicNav::GetContextButtons(), and CGUIWindowMusicNav::OnAction().
The documentation for this class was generated from the following files:
MusicDatabaseDirectory.h
MusicDatabaseDirectory.cpp