Kodi Documentation: CVideoSyncTVos Class Reference
CVideoSyncTVos Class Reference
#include <VideoSyncTVos.h>
Public Member Functions
CVideoSyncTVos (CVideoReferenceClock *clock, CWinSystemTVOS &winSystem)
bool Setup () override
void Run (CEvent &stopEvent) override
void Cleanup () override
float GetFps () override
void OnResetDisplay () override
void TVosVblankHandler ()
Public Member Functions inherited from CVideoSync
CVideoSync (CVideoReferenceClock *clock)
virtual ~CVideoSync ()=default
virtual void RefreshChanged ()
Private Member Functions
virtual bool InitDisplayLink ()
virtual void DeinitDisplayLink ()
Private Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
virtual void OnLostDisplay ()
virtual void OnAppFocusChange (bool focus)
Private Attributes
int64_t m_LastVBlankTime = 0
CEvent m_abortEvent
CWinSystemTVOS & m_winSystem
Additional Inherited Members
Protected Attributes inherited from CVideoSync
float m_fps
CVideoReferenceClock * m_refClock
Constructor & Destructor Documentation
CVideoSyncTVos()
CVideoSyncTVos::CVideoSyncTVos (CVideoReferenceClock * clock, CWinSystemTVOS & winSystem) inline
Member Function Documentation
Cleanup()
void CVideoSyncTVos::Cleanup () override virtual
Implements CVideoSync.
References DeinitDisplayLink(), CLog::Log(), LOGDEBUG, m_winSystem, and CWinSystemTVOS::Unregister().
DeinitDisplayLink()
void CVideoSyncTVos::DeinitDisplayLink () private virtual
References CWinSystemTVOS::DeinitDisplayLink(), and m_winSystem.
Referenced by Cleanup().
GetFps()
float CVideoSyncTVos::GetFps () override virtual
Implements CVideoSync.
References CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, and CVideoSync::m_fps.
InitDisplayLink()
bool CVideoSyncTVos::InitDisplayLink () private virtual
References CWinSystemTVOS::InitDisplayLink(), CLog::Log(), LOGDEBUG, and m_winSystem.
Referenced by Setup().
OnResetDisplay()
void CVideoSyncTVos::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References m_abortEvent, and CEvent::Set().
Run()
void CVideoSyncTVos::Run (CEvent & stopEvent) override virtual
Implements CVideoSync.
References m_abortEvent.
Setup()
bool CVideoSyncTVos::Setup () override virtual
Implements CVideoSync.
References CurrentHostCounter(), InitDisplayLink(), CLog::Log(), LOGDEBUG, m_abortEvent, m_LastVBlankTime, m_winSystem, CWinSystemTVOS::Register(), and CEvent::Reset().
TVosVblankHandler()
void CVideoSyncTVos::TVosVblankHandler ()
References CurrentHostCounter(), CurrentHostFrequency(), int64_t(), CVideoSync::m_fps, m_LastVBlankTime, CVideoSync::m_refClock, MathUtils::round_int(), and CVideoReferenceClock::UpdateClock().
Member Data Documentation
m_abortEvent
CEvent CVideoSyncTVos::m_abortEvent private
Referenced by OnResetDisplay(), Run(), and Setup().
m_LastVBlankTime
int64_t CVideoSyncTVos::m_LastVBlankTime = 0 private
Referenced by Setup(), and TVosVblankHandler().
m_winSystem
CWinSystemTVOS& CVideoSyncTVos::m_winSystem private
Referenced by Cleanup(), DeinitDisplayLink(), InitDisplayLink(), and Setup().
The documentation for this class was generated from the following files:
VideoSyncTVos.h
VideoSyncTVos.cpp