Kodi Documentation: DXVA.cpp File Reference
DXVA.cpp File Reference
#include "DXVA.h"
#include "ServiceBroker.h"
#include "cores/VideoPlayer/DVDCodecs/DVDCodecUtils.h"
#include "cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.h"
#include "cores/VideoPlayer/Process/ProcessInfo.h"
#include "cores/VideoPlayer/VideoRenderers/RenderManager.h"
#include "rendering/dx/DeviceResources.h"
#include "rendering/dx/RenderContext.h"
#include "settings/AdvancedSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/CPUInfo.h"
#include "utils/StringUtils.h"
#include "utils/SystemInfo.h"
#include "utils/log.h"
#include "platform/win32/WIN32Util.h"
#include <algorithm>
#include <mutex>
#include <Windows.h>
#include <initguid.h>
#include <sdkddkver.h>
Classes
struct dxva2_mode_t
Namespaces
namespace anonymous_namespace{DXVA.cpp}
Macros
#define FF_API_OLD_SAMPLE_FMT 0
#define LIMIT_VIDEO_MEMORY_4K 2960ull
Functions
DEFINE_GUID (DXVADDI_Intel_ModeH264_A, 0x604F8E64, 0x4951, 0x4c54, 0x88, 0xFE, 0xAB, 0xD2, 0x5C, 0x15, 0xB3, 0xD6)
DEFINE_GUID (DXVADDI_Intel_ModeH264_C, 0x604F8E66, 0x4951, 0x4c54, 0x88, 0xFE, 0xAB, 0xD2, 0x5C, 0x15, 0xB3, 0xD6)
DEFINE_GUID (DXVADDI_Intel_ModeH264_E, 0x604F8E68, 0x4951, 0x4c54, 0x88, 0xFE, 0xAB, 0xD2, 0x5C, 0x15, 0xB3, 0xD6)
DEFINE_GUID (DXVADDI_Intel_ModeVC1_E, 0xBCC5DB6D, 0xA2B6, 0x4AF0, 0xAC, 0xE4, 0xAD, 0xB1, 0xF7, 0x87, 0xBC, 0x89)
DEFINE_GUID (DXVA_ModeH264_VLD_NoFGT_Flash, 0x4245F676, 0x2BBC, 0x4166, 0xa0, 0xBB, 0x54, 0xE7, 0xB8, 0x49, 0xC3, 0x80)
DEFINE_GUID (DXVA_Intel_VC1_ClearVideo_2, 0xE07EC519, 0xE651, 0x4CD6, 0xAC, 0x84, 0x13, 0x70, 0xCC, 0xEE, 0xC8, 0x51)
DEFINE_GUID (D3D11_DECODER_PROFILE_AV1_VLD_PROFILE0, 0xb8be4ccb, 0xcf53, 0x46ba, 0x8d, 0x59, 0xd6, 0xb8, 0xa6, 0xda, 0x5d, 0x2a)
DEFINE_GUID (D3D11_DECODER_PROFILE_AV1_VLD_PROFILE1, 0x6936ff0f, 0x45b1, 0x4163, 0x9c, 0xc1, 0x64, 0x6e, 0xf6, 0x94, 0x61, 0x08)
DEFINE_GUID (D3D11_DECODER_PROFILE_AV1_VLD_PROFILE2, 0x0c5f2aa1, 0xe541, 0x4089, 0xbb, 0x7b, 0x98, 0x11, 0x0a, 0x19, 0xd7, 0xc8)
DEFINE_GUID (DXVA_NoEncrypt, 0x1b81beD0, 0xa0c7, 0x11d3, 0xb9, 0x84, 0x00, 0xc0, 0x4f, 0x2e, 0x73, 0xc5)
static std::string GUIDToString (const GUID &guid)
static const dxva2_mode_t * dxva2_find_mode (const GUID *guid)
static bool CheckH264L41 (AVCodecContext *avctx)
static bool IsL41LimitedATI ()
static bool HasVP3WidthBug (AVCodecContext *avctx)
static bool HasATIMP2Bug (AVCodecContext *avctx)
static bool HasAMDH264SDiBug (AVCodecContext *avctx)
static bool CheckCompatibility (AVCodecContext *avctx)
Variables
constexpr int anonymous_namespace{DXVA.cpp}::PROFILES_MPEG2_SIMPLE [] = {FF_PROFILE_MPEG2_SIMPLE, FF_PROFILE_UNKNOWN}
constexpr int anonymous_namespace{DXVA.cpp}::PROFILES_MPEG2_MAIN []
constexpr int anonymous_namespace{DXVA.cpp}::PROFILES_H264_HIGH []
constexpr int anonymous_namespace{DXVA.cpp}::PROFILES_HEVC_MAIN [] = {FF_PROFILE_HEVC_MAIN, FF_PROFILE_UNKNOWN}
constexpr int anonymous_namespace{DXVA.cpp}::PROFILES_HEVC_MAIN10 []
constexpr int anonymous_namespace{DXVA.cpp}::PROFILES_VP9_0 [] = {FF_PROFILE_VP9_0, FF_PROFILE_UNKNOWN}
constexpr int anonymous_namespace{DXVA.cpp}::PROFILES_VP9_10_2 [] = {FF_PROFILE_VP9_2, FF_PROFILE_UNKNOWN}
constexpr int anonymous_namespace{DXVA.cpp}::PROFILES_AV1_MAIN [] = {FF_PROFILE_AV1_MAIN, FF_PROFILE_UNKNOWN}
constexpr int anonymous_namespace{DXVA.cpp}::PROFILES_AV1_HIGH [] = {FF_PROFILE_AV1_HIGH, FF_PROFILE_UNKNOWN}
constexpr int anonymous_namespace{DXVA.cpp}::PROFILES_AV1_PROFESSIONAL [] = {FF_PROFILE_AV1_PROFESSIONAL, FF_PROFILE_UNKNOWN}
static const std::vector< dxva2_mode_t > dxva2_modes
static const DXGI_FORMAT render_targets_dxgi []
static DWORD UVDDeviceID []
static DWORD VP3DeviceID []
Macro Definition Documentation
FF_API_OLD_SAMPLE_FMT
#define FF_API_OLD_SAMPLE_FMT 0
LIMIT_VIDEO_MEMORY_4K
#define LIMIT_VIDEO_MEMORY_4K 2960ull
Function Documentation
CheckCompatibility()
static bool CheckCompatibility (AVCodecContext * avctx) static
References CheckH264L41(), CServiceBroker::GetSettingsComponent(), HasAMDH264SDiBug(), HasATIMP2Bug(), HasVP3WidthBug(), IsL41LimitedATI(), CLog::Log(), and LOGWARNING.
Referenced by DXVA::CDecoder::Open().
CheckH264L41()
static bool CheckH264L41 (AVCodecContext * avctx) static
Referenced by CheckCompatibility().
DEFINE_GUID() [1/10]
DEFINE_GUID (D3D11_DECODER_PROFILE_AV1_VLD_PROFILE0 , 0xb8be4ccb , 0xcf53 , 0x46ba , 0x8d , 0x59 , 0xd6 , 0xb8 , 0xa6 , 0xda , 0x5d , 0x2a)
DEFINE_GUID() [2/10]
DEFINE_GUID (D3D11_DECODER_PROFILE_AV1_VLD_PROFILE1 , 0x6936ff0f , 0x45b1 , 0x4163 , 0x9c , 0xc1 , 0x64 , 0x6e , 0xf6 , 0x94 , 0x61 , 0x08)
DEFINE_GUID() [3/10]
DEFINE_GUID (D3D11_DECODER_PROFILE_AV1_VLD_PROFILE2 , 0x0c5f2aa1 , 0xe541 , 0x4089 , 0xbb , 0x7b , 0x98 , 0x11 , 0x0a , 0x19 , 0xd7 , 0xc8)
DEFINE_GUID() [4/10]
DEFINE_GUID (DXVA_Intel_VC1_ClearVideo_2 , 0xE07EC519 , 0xE651 , 0x4CD6 , 0xAC , 0x84 , 0x13 , 0x70 , 0xCC , 0xEE , 0xC8 , 0x51)
DEFINE_GUID() [5/10]
DEFINE_GUID (DXVA_ModeH264_VLD_NoFGT_Flash , 0x4245F676 , 0x2BBC , 0x4166 , 0xa0 , 0xBB , 0x54 , 0xE7 , 0xB8 , 0x49 , 0xC3 , 0x80)
DEFINE_GUID() [6/10]
DEFINE_GUID (DXVA_NoEncrypt , 0x1b81beD0 , 0xa0c7 , 0x11d3 , 0xb9 , 0x84 , 0x00 , 0xc0 , 0x4f , 0x2e , 0x73 , 0xc5)
DEFINE_GUID() [7/10]
DEFINE_GUID (DXVADDI_Intel_ModeH264_A , 0x604F8E64 , 0x4951 , 0x4c54 , 0x88 , 0xFE , 0xAB , 0xD2 , 0x5C , 0x15 , 0xB3 , 0xD6)
DEFINE_GUID() [8/10]
DEFINE_GUID (DXVADDI_Intel_ModeH264_C , 0x604F8E66 , 0x4951 , 0x4c54 , 0x88 , 0xFE , 0xAB , 0xD2 , 0x5C , 0x15 , 0xB3 , 0xD6)
DEFINE_GUID() [9/10]
DEFINE_GUID (DXVADDI_Intel_ModeH264_E , 0x604F8E68 , 0x4951 , 0x4c54 , 0x88 , 0xFE , 0xAB , 0xD2 , 0x5C , 0x15 , 0xB3 , 0xD6)
DEFINE_GUID() [10/10]
DEFINE_GUID (DXVADDI_Intel_ModeVC1_E , 0xBCC5DB6D , 0xA2B6 , 0x4AF0 , 0xAC , 0xE4 , 0xAD , 0xB1 , 0xF7 , 0x87 , 0xBC , 0x89)
dxva2_find_mode()
static const dxva2_mode_t * dxva2_find_mode (const GUID * guid) static
References dxva2_modes.
Referenced by DXVA::CDecoder::Open(), and DXVA::CContext::QueryCaps().
GUIDToString()
static std::string GUIDToString (const GUID & guid) static
References KODI::UTILS::StringUtils::Format().
Referenced by DXVA::CContext::QueryCaps().
HasAMDH264SDiBug()
static bool HasAMDH264SDiBug (AVCodecContext * avctx) static
References DX::DeviceResources::Get(), and PCIV_AMD.
Referenced by CheckCompatibility().
HasATIMP2Bug()
static bool HasATIMP2Bug (AVCodecContext * avctx) static
References DX::DeviceResources::Get(), and PCIV_AMD.
Referenced by CheckCompatibility().
HasVP3WidthBug()
static bool HasVP3WidthBug (AVCodecContext * avctx) static
References DX::DeviceResources::Get(), CDVDCodecUtils::IsVP3CompatibleWidth(), PCIV_NVIDIA, and VP3DeviceID.
Referenced by CheckCompatibility().
IsL41LimitedATI()
static bool IsL41LimitedATI () static
References DX::DeviceResources::Get(), PCIV_AMD, and UVDDeviceID.
Referenced by CheckCompatibility(), and DXVA::CDecoder::Open().
Variable Documentation
dxva2_modes
const std::vector<dxva2_mode_t> dxva2_modes static
Referenced by dxva2_find_mode(), and DXVA::CContext::GetFormatAndConfig().
render_targets_dxgi
const DXGI_FORMAT render_targets_dxgi[] static
Initial value:
= {
  DXGI_FORMAT_NV12,
  DXGI_FORMAT_P010,
  DXGI_FORMAT_P016,
  DXGI_FORMAT_UNKNOWN
}
Referenced by DXVA::CContext::GetFormatAndConfig().
UVDDeviceID
DWORD UVDDeviceID[] static
Initial value:
= {
  0x95C0,
  0x95C5,
  0x95C4,
  0x94C3,
  0x9589,
  0x9598,
  0x9591,
  0x9501,
  0x9505,
  0x9507,
  0x9513,
  0x950F,
  0x0000
}
Referenced by IsL41LimitedATI().
VP3DeviceID
DWORD VP3DeviceID[] static
Referenced by HasVP3WidthBug().