Kodi Documentation: PVR::CPVRGUIActionsEPG Class Reference
PVR::CPVRGUIActionsEPG Class Reference
#include <PVRGUIActionsEPG.h>
Public Member Functions
CPVRGUIActionsEPG ()=default
~CPVRGUIActionsEPG () override=default
bool ShowEPGInfo (const CFileItem &item) const
Open a dialog with epg information for a given item.
bool ShowChannelEPG (const CFileItem &item) const
Open a dialog with the epg list for a given item.
bool FindSimilar (const CFileItem &item) const
Open a window containing a list of epg tags 'similar' to a given item.
bool ExecuteSavedSearch (const CFileItem &item)
Execute a saved search. Displays result in search window if it is open.
bool EditSavedSearch (const CFileItem &item)
Edit a saved search. Opens the search dialog.
bool RenameSavedSearch (const CFileItem &item)
Rename a saved search. Opens a title input dialog.
bool ChooseIconForSavedSearch (const CFileItem &item)
Choose an icon for a saved search. Opens an art chooser dialog.
bool DuplicateSavedSearch (const CFileItem &item)
Duplicate a saved search.
bool DeleteSavedSearch (const CFileItem &item)
Delete a saved search. Opens confirmation dialog before deleting.
std::string GetTitleForEpgTag (const std::shared_ptr< const CPVREpgInfoTag > &tag)
Get the title for the given EPG tag, taking settings and parental controls into account.
Public Member Functions inherited from PVR::IPVRComponent
virtual ~IPVRComponent ()=default
Private Member Functions
CPVRGUIActionsEPG (const CPVRGUIActionsEPG &)=delete
CPVRGUIActionsEPG const & operator= (CPVRGUIActionsEPG const &)=delete
Constructor & Destructor Documentation
CPVRGUIActionsEPG() [1/2]
PVR::CPVRGUIActionsEPG::CPVRGUIActionsEPG () default
~CPVRGUIActionsEPG()
PVR::CPVRGUIActionsEPG::~CPVRGUIActionsEPG () override default
CPVRGUIActionsEPG() [2/2]
PVR::CPVRGUIActionsEPG::CPVRGUIActionsEPG (const CPVRGUIActionsEPG &) private delete
Member Function Documentation
ChooseIconForSavedSearch()
bool CPVRGUIActionsEPG::ChooseIconForSavedSearch (const CFileItem & item)
Choose an icon for a saved search. Opens an art chooser dialog.
Parameters
item The item containing a search filter.
Returns
True on success, false otherwise.
References CFileItemList::Add(), PVR::CPVRManager::EpgContainer(), g_localizeStrings, CLocalizeStrings::Get(), CFileItem::GetEPGSearchFilter(), CMediaManager::GetLocalDrives(), CServiceBroker::GetMediaManager(), CServiceBroker::GetPVRManager(), LOGERROR, PVR::CPVREpgContainer::PersistSavedSearch(), CGUIListItem::SetArt(), and CGUIDialogFileBrowser::ShowAndGetImage().
DeleteSavedSearch()
bool CPVRGUIActionsEPG::DeleteSavedSearch (const CFileItem & item)
Delete a saved search. Opens confirmation dialog before deleting.
Parameters
item The item containing a search filter.
Returns
True on success, false otherwise.
References PVR::CPVREpgContainer::DeleteSavedSearch(), PVR::CPVRManager::EpgContainer(), CFileItem::GetEPGSearchFilter(), CGUIListItem::GetLabel(), CServiceBroker::GetPVRManager(), LOGERROR, and CGUIDialogYesNo::ShowAndGetInput().
DuplicateSavedSearch()
bool CPVRGUIActionsEPG::DuplicateSavedSearch (const CFileItem & item)
Duplicate a saved search.
Parameters
item The item containing a search filter.
Returns
True on success, false otherwise.
References PVR::CPVRManager::EpgContainer(), g_localizeStrings, CLocalizeStrings::Get(), CFileItem::GetEPGSearchFilter(), CServiceBroker::GetPVRManager(), LOGERROR, PVR::CPVREpgContainer::PersistSavedSearch(), and PVR::PVR_EPG_SEARCH_INVALID_DATABASE_ID.
EditSavedSearch()
bool CPVRGUIActionsEPG::EditSavedSearch (const CFileItem & item)
Edit a saved search. Opens the search dialog.
Parameters
item The item containing a search filter.
Returns
True on success, false otherwise.
References CGUIWindowManager::ActivateWindow(), CFileItem::GetEPGSearchFilter(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), LOGERROR, PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), and PVR::CGUIDialogPVRGuideSearch::SEARCH.
ExecuteSavedSearch()
bool CPVRGUIActionsEPG::ExecuteSavedSearch (const CFileItem & item)
Execute a saved search. Displays result in search window if it is open.
Parameters
item The item containing a search filter.
Returns
True on success, false otherwise.
References CGUIWindowManager::ActivateWindow(), CFileItem::GetEPGSearchFilter(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), LOGERROR, and PVR::CGUIWindowPVRSearchBase::SetItemToSearch().
FindSimilar()
bool CPVRGUIActionsEPG::FindSimilar (const CFileItem & item) const
Open a window containing a list of epg tags 'similar' to a given item.
Parameters
item containing epg data for matching. item must be an epg tag, a channel or a recording.
Returns
true on success, false otherwise.
Todo:
If we want dialogs to spawn program search in a clean way - without having to force-close any
References CGUIWindowManager::ActivateWindow(), CGUIWindow::Close(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), LOGERROR, LOGWARNING, PVR::CGUIWindowPVRSearchBase::SetItemToSearch(), and WINDOW_INVALID.
GetTitleForEpgTag()
std::string CPVRGUIActionsEPG::GetTitleForEpgTag (const std::shared_ptr< const CPVREpgInfoTag > & tag)
Get the title for the given EPG tag, taking settings and parental controls into account.
Parameters
item The EPG tag.
Returns
"Parental locked" in case the access to the information is restricted by parental controls, "No information avilable" if the real EPG event title is empty and SETTING_EPG_HIDENOINFOAVAILABLE is false or tag is nullptr, the real EPG event title as given by the EPG data provider otherwise.
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_EPG_HIDENOINFOAVAILABLE.
operator=()
CPVRGUIActionsEPG const & PVR::CPVRGUIActionsEPG::operator= (CPVRGUIActionsEPG const &) private delete
RenameSavedSearch()
bool CPVRGUIActionsEPG::RenameSavedSearch (const CFileItem & item)
Rename a saved search. Opens a title input dialog.
Parameters
item The item containing a search filter.
Returns
True on success, false otherwise.
References PVR::CPVRManager::EpgContainer(), g_localizeStrings, CLocalizeStrings::Get(), CFileItem::GetEPGSearchFilter(), CServiceBroker::GetPVRManager(), LOGERROR, PVR::CPVREpgContainer::PersistSavedSearch(), and CGUIKeyboardFactory::ShowAndGetInput().
ShowChannelEPG()
bool CPVRGUIActionsEPG::ShowChannelEPG (const CFileItem & item) const
Open a dialog with the epg list for a given item.
Parameters
item containing channel info. item must be an epg tag, a channel or a timer.
Returns
true on success, false otherwise.
References CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), LOGERROR, PVR::CGUIDialogPVRChannelGuide::Open(), PVR::SUCCESS, and WINDOW_DIALOG_PVR_CHANNEL_GUIDE.
ShowEPGInfo()
bool CPVRGUIActionsEPG::ShowEPGInfo (const CFileItem & item) const
Open a dialog with epg information for a given item.
Parameters
item containing epg data to show. item must be an epg tag, a channel or a timer.
Returns
true on success, false otherwise.
References CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), LOGERROR, CGUIDialog::Open(), PVR::CGUIDialogPVRGuideInfo::SetProgInfo(), PVR::SUCCESS, and WINDOW_DIALOG_PVR_GUIDE_INFO.
The documentation for this class was generated from the following files:
PVRGUIActionsEPG.h
PVRGUIActionsEPG.cpp