Kodi Documentation: CONTEXTMENU::anonymous_namespace{ContextMenus.cpp} Namespace Reference
CONTEXTMENU::anonymous_namespace{ContextMenus.cpp} Namespace Reference
Classes
class CVideoPlayActionProcessor
class CVideoSelectActionProcessor
Enumerations
enum class PlayMode { PLAY , PLAY_USING , PLAY_VERSION_USING , RESUME }
Functions
int GetTargetWindowID (const CFileItem &item)
bool ExecuteAction (const CExecString &execute)
std::vector< std::string > GetPlayers (const CPlayerCoreFactory &playerCoreFactory, const CFileItem &item)
void SetPathAndPlay (const std::shared_ptr< CFileItem > &item, PlayMode mode)
void SelectNextItem (int windowID)
bool CanQueue (const CFileItem &item)
Enumeration Type Documentation
PlayMode
enum class CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::PlayMode strong protected
Enumerator
PLAY
PLAY_USING
PLAY_VERSION_USING
RESUME
Function Documentation
CanQueue()
bool CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CanQueue (const CFileItem & item) protected
References CFileItem::CanQueue(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and WINDOW_VIDEO_PLAYLIST.
ExecuteAction()
bool CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::ExecuteAction (const CExecString & execute)
References CExecString::GetExecString(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_EXECUTE, CGUIWindowManager::SendMessage(), and CGUIMessage::SetStringParam().
GetPlayers()
std::vector< std::string > CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::GetPlayers (const CPlayerCoreFactory & playerCoreFactory, const CFileItem & item) protected
Todo:
CPlayerCoreFactory and classes called from there do not handle dyn path correctly.
References CFileItem::GetDynPath(), CPlayerCoreFactory::GetPlayers(), and CFileItem::SetPath().
GetTargetWindowID()
int CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::GetTargetWindowID (const CFileItem & item)
References CVariant::asString(), CServiceBroker::GetGUI(), CGUIListItem::GetProperty(), GetTargetWindowID(), CGUIComponent::GetWindowManager(), CWindowTranslator::TranslateWindow(), and WINDOW_INVALID.
Referenced by GetTargetWindowID().
SelectNextItem()
void CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::SelectNextItem (int windowID) protected
References CServiceBroker::GetGUI(), CGUIMessage::GetParam1(), CGUIWindow::GetViewContainerID(), CGUIComponent::GetWindowManager(), GUI_MSG_ITEM_SELECT, and GUI_MSG_ITEM_SELECTED.
SetPathAndPlay()
void CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::SetPathAndPlay (const std::shared_ptr< CFileItem > & item, PlayMode mode) protected
Todo:
get rid of "videos with versions as folder" hack!
References KODI::VIDEO::GUILIB::ACTION_PLAY_FROM_BEGINNING, KODI::VIDEO::GUILIB::ACTION_RESUME, g_application, KODI::VIDEO::UTILS::GetItemResumeInformation(), KODI::VIDEO::UTILS::ResumeInformation::isResumable, KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::ProcessAction(), SetPathAndPlay(), and STARTOFFSET_RESUME.
Referenced by SetPathAndPlay().