Kodi Documentation: CScreenShot Class Reference
CScreenShot Class Reference
#include <Screenshot.h>
Static Public Member Functions
static void Register (const std::function< std::unique_ptr< IScreenshotSurface >()> &createFunc)
static void TakeScreenshot ()
static void TakeScreenshot (const std::string &filename, bool sync)
Static Private Attributes
static std::vector< std::function< std::unique_ptr< IScreenshotSurface >()> > m_screenShotSurfaces
Member Function Documentation
Register()
void CScreenShot::Register (const std::function< std::unique_ptr< IScreenshotSurface >()> & createFunc) static
References m_screenShotSurfaces.
Referenced by CScreenshotSurfaceWindows::Register(), CScreenshotSurfaceGL::Register(), and CScreenshotSurfaceGLES::Register().
TakeScreenshot() [1/2]
void CScreenShot::TakeScreenshot () static
References URIUtils::AddFileToFolder(), g_localizeStrings, CUtil::GetNextFilename(), CGUIControlButtonSetting::GetPath(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGWARNING, URIUtils::RemoveSlashAtEnd(), CSettings::SETTING_DEBUG_SCREENSHOTPATH, and TakeScreenshot().
Referenced by CApplication::OnAction(), anonymous_namespace{GUIBuiltins.cpp}::Screenshot(), and TakeScreenshot().
TakeScreenshot() [2/2]
void CScreenShot::TakeScreenshot (const std::string & filename, bool sync) static
References XFILE::CFile::Close(), CPicture::CreateThumbnailFromSurface(), CServiceBroker::GetJobManager(), CLog::Log(), LOGDEBUG, LOGERROR, and m_screenShotSurfaces.
Member Data Documentation
m_screenShotSurfaces
std::vector< std::function< std::unique_ptr< IScreenshotSurface >()> > CScreenShot::m_screenShotSurfaces static private
Referenced by Register(), and TakeScreenshot().
The documentation for this class was generated from the following files:
Screenshot.h
Screenshot.cpp