Kodi Documentation: CAppParamParser Class Reference
CAppParamParser Class Reference
#include <AppParamParser.h>
Public Member Functions
CAppParamParser ()
virtual ~CAppParamParser ()=default
void Parse (const char *const *argv, int nArgs)
std::shared_ptr< CAppParams > GetAppParams () const
Protected Member Functions
virtual void ParseArg (const std::string &arg)
virtual void DisplayHelp ()
Private Member Functions
void DisplayVersion ()
Private Attributes
std::shared_ptr< CAppParams > m_params
Constructor & Destructor Documentation
CAppParamParser()
CAppParamParser::CAppParamParser ()
~CAppParamParser()
virtual CAppParamParser::~CAppParamParser () virtual default
Member Function Documentation
DisplayHelp()
void CAppParamParser::DisplayHelp () protected virtual
Reimplemented in CAppParamParserLinux.
References CSysInfo::GetAppName().
Referenced by CAppParamParserLinux::DisplayHelp(), and ParseArg().
DisplayVersion()
void CAppParamParser::DisplayVersion () private
References CSysInfo::GetAppName(), CCompileInfo::GetCopyrightYears(), and CSysInfo::GetVersion().
Referenced by ParseArg().
GetAppParams()
std::shared_ptr< CAppParams > CAppParamParser::GetAppParams () const inline
References m_params.
Referenced by main(), CAppParamParserLinux::ParseArg(), ParseCommandLine(), and KODI::PLATFORM::WINDOWS10::App::Run().
Parse()
void CAppParamParser::Parse (const char *const * argv, int nArgs)
References m_params, and ParseArg().
Referenced by main(), ParseCommandLine(), and KODI::PLATFORM::WINDOWS10::App::Run().
ParseArg()
void CAppParamParser::ParseArg (const std::string & arg) protected virtual
Reimplemented in CAppParamParserLinux, and CAppParamParserWebOS.
References DisplayHelp(), DisplayVersion(), LOG_LEVEL_DEBUG, and m_params.
Referenced by Parse(), and CAppParamParserLinux::ParseArg().
Member Data Documentation
m_params
std::shared_ptr<CAppParams> CAppParamParser::m_params private
Referenced by GetAppParams(), Parse(), and ParseArg().
The documentation for this class was generated from the following files:
AppParamParser.h
AppParamParser.cpp