Kodi Documentation: CWeatherManager Class Reference
CWeatherManager Class Reference
#include <WeatherManager.h>
Public Member Functions
CWeatherManager (void)
~CWeatherManager (void) override
std::string GetLocation (int iLocation)
Retrieve the city name for the specified location from the settings.
const std::string & GetLastUpdateTime () const
const ForecastDay & GetForecast (int day) const
bool IsFetched ()
void Reset ()
void SetArea (int iLocation)
Saves the specified location index to the settings. Call Refresh() afterwards to update weather info for the new location.
int GetArea () const
Retrieves the current location index from the settings.
Public Member Functions inherited from CInfoLoader
CInfoLoader (unsigned int timeToRefresh=5 *60 *1000)
~CInfoLoader () override
std::string GetInfo (int info)
void Refresh ()
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Static Public Member Functions
static bool GetSearchResults (const std::string &strSearch, std::string &strResult)
Protected Member Functions
CJob * GetJob () const override
std::string TranslateInfo (int info) const override
std::string BusyInfo (int info) const override
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
Private Attributes
CWeatherInfo m_info
Constructor & Destructor Documentation
CWeatherManager()
CWeatherManager::CWeatherManager (void)
References CServiceBroker::GetSettingsComponent(), Reset(), CSettings::SETTING_WEATHER_ADDON, and CSettings::SETTING_WEATHER_ADDONSETTINGS.
~CWeatherManager()
CWeatherManager::~CWeatherManager (void) override
References CServiceBroker::GetSettingsComponent().
Member Function Documentation
BusyInfo()
std::string CWeatherManager::BusyInfo (int info) const override protected virtual
Reimplemented from CInfoLoader.
References URIUtils::AddFileToFolder(), CInfoLoader::BusyInfo(), ICON_ADDON_PATH, and WEATHER_IMAGE_CURRENT_ICON.
GetArea()
int CWeatherManager::GetArea () const
Retrieves the current location index from the settings.
Returns
the active location index (will be in the range [1..MAXLOCATION])
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_WEATHER_CURRENTLOCATION.
Referenced by GetJob(), CGUIWindowWeather::OnMessage(), CGUIWindowWeather::SetProperties(), and CGUIWindowWeather::UpdateLocations().
GetForecast()
const ForecastDay & CWeatherManager::GetForecast (int day) const
References day, CWeatherInfo::forecast, and m_info.
GetJob()
CJob * CWeatherManager::GetJob () const override protected virtual
Implements CInfoLoader.
References GetArea().
GetLastUpdateTime()
const std::string & CWeatherManager::GetLastUpdateTime () const inline
References CWeatherInfo::lastUpdateTime, and m_info.
GetLocation()
std::string CWeatherManager::GetLocation (int iLocation)
Retrieve the city name for the specified location from the settings.
Parameters
iLocation the location index (can be in the range [1..MAXLOCATION])
Returns
the city name (without the accompanying region area code)
References CVariant::asString(), CServiceBroker::GetGUI(), CGUIWindow::GetProperty(), CGUIComponent::GetWindowManager(), and WINDOW_WEATHER.
Referenced by CGUIWindowWeather::SetLocation(), and CGUIWindowWeather::UpdateLocations().
GetSearchResults()
static bool CWeatherManager::GetSearchResults (const std::string & strSearch, std::string & strResult) static
IsFetched()
bool CWeatherManager::IsFetched ()
References CInfoLoader::GetInfo(), CWeatherInfo::lastUpdateTime, and m_info.
Referenced by KODI::GUILIB::GUIINFO::CWeatherGUIInfo::GetBool().
OnJobComplete()
void CWeatherManager::OnJobComplete (unsigned int jobID, bool success, CJob * job) override protected virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Reimplemented from CInfoLoader.
References CInfoLoader::GetInfo(), m_info, CInfoLoader::OnJobComplete(), and success.
OnSettingAction()
void CWeatherManager::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override protected virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Todo:
maybe have ShowAndGetInput return a bool if settings changed, then only reset weather if true.
Reimplemented from ISettingCallback.
References CServiceBroker::GetAddonMgr(), CServiceBroker::GetSettingsComponent(), CInfoLoader::Refresh(), CSettings::SETTING_WEATHER_ADDON, CSettings::SETTING_WEATHER_ADDONSETTINGS, and CGUIDialogAddonSettings::ShowForAddon().
OnSettingChanged()
void CWeatherManager::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override protected virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CInfoLoader::Refresh(), CGUIWindow::SetProperty(), CSettings::SETTING_WEATHER_ADDON, and WINDOW_WEATHER.
Reset()
void CWeatherManager::Reset ()
References m_info, and CWeatherInfo::Reset().
Referenced by CWeatherManager(), and CGUIWindowWeather::OnMessage().
SetArea()
void CWeatherManager::SetArea (int iLocation)
Saves the specified location index to the settings. Call Refresh() afterwards to update weather info for the new location.
Parameters
iLocation the new location index (can be in the range [1..MAXLOCATION])
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_WEATHER_CURRENTLOCATION.
Referenced by CGUIWindowWeather::SetLocation(), and CGUIWindowWeather::UpdateLocations().
TranslateInfo()
std::string CWeatherManager::TranslateInfo (int info) const override protected virtual
Reimplemented from CInfoLoader.
References CWeatherInfo::currentConditions, CWeatherInfo::currentDewPoint, CWeatherInfo::currentFeelsLike, CWeatherInfo::currentHumidity, CWeatherInfo::currentIcon, CWeatherInfo::currentTemperature, CWeatherInfo::currentUVIndex, CWeatherInfo::currentWind, CWeatherInfo::location, m_info, WEATHER_IMAGE_CURRENT_ICON, WEATHER_LABEL_CURRENT_COND, WEATHER_LABEL_CURRENT_DEWP, WEATHER_LABEL_CURRENT_FEEL, WEATHER_LABEL_CURRENT_HUMI, WEATHER_LABEL_CURRENT_TEMP, WEATHER_LABEL_CURRENT_UVID, WEATHER_LABEL_CURRENT_WIND, and WEATHER_LABEL_LOCATION.
Member Data Documentation
m_info
CWeatherInfo CWeatherManager::m_info private
Referenced by GetForecast(), GetLastUpdateTime(), IsFetched(), OnJobComplete(), Reset(), and TranslateInfo().
The documentation for this class was generated from the following files:
WeatherManager.h
WeatherManager.cpp