Kodi Documentation: KODI::WINDOWING::X11::CVideoSyncGLX Class Reference
KODI::WINDOWING::X11::CVideoSyncGLX Class Reference
#include <VideoSyncGLX.h>
Public Member Functions
CVideoSyncGLX (CVideoReferenceClock *clock, CWinSystemX11GLContext &winSystem)
bool Setup () override
void Run (CEvent &stopEvent) override
void Cleanup () override
float GetFps () override
void OnLostDisplay () override
void OnResetDisplay () override
Public Member Functions inherited from CVideoSync
CVideoSync (CVideoReferenceClock *clock)
virtual ~CVideoSync ()=default
virtual void RefreshChanged ()
Private Attributes
int(* m_glXWaitVideoSyncSGI)(int, int, unsigned int *)
int(* m_glXGetVideoSyncSGI)(unsigned int *)
CWinSystemX11GLContext & m_winSystem
XVisualInfo * m_vInfo
Window m_Window
GLXContext m_Context
volatile bool m_displayLost
volatile bool m_displayReset
CEvent m_lostEvent
Static Private Attributes
static Display * m_Dpy = NULL
Additional Inherited Members
Protected Attributes inherited from CVideoSync
float m_fps
CVideoReferenceClock * m_refClock
Private Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
virtual void OnAppFocusChange (bool focus)
Constructor & Destructor Documentation
CVideoSyncGLX()
KODI::WINDOWING::X11::CVideoSyncGLX::CVideoSyncGLX (CVideoReferenceClock * clock, CWinSystemX11GLContext & winSystem) inline explicit
Member Function Documentation
Cleanup()
void CVideoSyncGLX::Cleanup () override virtual
Implements CVideoSync.
References CWinSystemBase::GetGfxContext(), CLog::Log(), LOGDEBUG, m_Context, m_Dpy, m_lostEvent, m_vInfo, m_Window, m_winSystem, CEvent::Set(), and KODI::WINDOWING::X11::CWinSystemX11::Unregister().
GetFps()
float CVideoSyncGLX::GetFps () override virtual
Implements CVideoSync.
References CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CVideoSync::m_fps, and m_winSystem.
OnLostDisplay()
void CVideoSyncGLX::OnLostDisplay () override virtual
Reimplemented from IDispResource.
References m_displayLost, m_lostEvent, and CEvent::Wait().
OnResetDisplay()
void CVideoSyncGLX::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References m_displayReset.
Run()
void CVideoSyncGLX::Run (CEvent & stopEvent) override virtual
Implements CVideoSync.
References CurrentHostCounter(), int64_t(), CLog::Log(), LOGDEBUG, m_Context, m_displayLost, m_displayReset, m_Dpy, m_glXGetVideoSyncSGI, m_glXWaitVideoSyncSGI, m_lostEvent, CVideoSync::m_refClock, m_Window, CEvent::Set(), CEvent::Signaled(), KODI::TIME::Sleep(), and CVideoReferenceClock::UpdateClock().
Setup()
bool CVideoSyncGLX::Setup () override virtual
Implements CVideoSync.
References CWinSystemBase::GetGfxContext(), KODI::WINDOWING::X11::CWinSystemX11::GetScreen(), KODI::WINDOWING::X11::CWinSystemX11GLContext::GetWindow(), CLog::Log(), LOGDEBUG, m_Context, m_displayLost, m_displayReset, m_Dpy, m_glXGetVideoSyncSGI, m_glXWaitVideoSyncSGI, m_lostEvent, m_vInfo, m_Window, m_winSystem, and CEvent::Reset().
Member Data Documentation
m_Context
GLXContext KODI::WINDOWING::X11::CVideoSyncGLX::m_Context private
Referenced by Cleanup(), Run(), and Setup().
m_displayLost
volatile bool KODI::WINDOWING::X11::CVideoSyncGLX::m_displayLost private
Referenced by OnLostDisplay(), Run(), and Setup().
m_displayReset
volatile bool KODI::WINDOWING::X11::CVideoSyncGLX::m_displayReset private
Referenced by OnResetDisplay(), Run(), and Setup().
m_Dpy
Display * CVideoSyncGLX::m_Dpy = NULL static private
Referenced by Cleanup(), Run(), and Setup().
m_glXGetVideoSyncSGI
int(* KODI::WINDOWING::X11::CVideoSyncGLX::m_glXGetVideoSyncSGI) (unsigned int *) private
Referenced by Run(), and Setup().
m_glXWaitVideoSyncSGI
int(* KODI::WINDOWING::X11::CVideoSyncGLX::m_glXWaitVideoSyncSGI) (int, int, unsigned int *) private
Referenced by Run(), and Setup().
m_lostEvent
CEvent KODI::WINDOWING::X11::CVideoSyncGLX::m_lostEvent private
Referenced by Cleanup(), OnLostDisplay(), Run(), and Setup().
m_vInfo
XVisualInfo* KODI::WINDOWING::X11::CVideoSyncGLX::m_vInfo private
Referenced by Cleanup(), and Setup().
m_Window
Window KODI::WINDOWING::X11::CVideoSyncGLX::m_Window private
Referenced by Cleanup(), Run(), and Setup().
m_winSystem
CWinSystemX11GLContext& KODI::WINDOWING::X11::CVideoSyncGLX::m_winSystem private
Referenced by Cleanup(), GetFps(), and Setup().
The documentation for this class was generated from the following files:
VideoSyncGLX.h
VideoSyncGLX.cpp