Kodi Documentation: CUPowerSource Class Reference
CUPowerSource Class Reference
#include <UPowerSyscall.h>
Public Member Functions
CUPowerSource (const char *powerSource)
~CUPowerSource ()
void Update ()
bool IsRechargeable ()
double BatteryLevel ()
Private Attributes
std::string m_powerSource
bool m_isRechargeable
double m_batteryLevel
Constructor & Destructor Documentation
CUPowerSource()
CUPowerSource::CUPowerSource (const char * powerSource)
References CVariant::asBoolean(), CDBusUtil::GetAll(), m_isRechargeable, m_powerSource, and Update().
~CUPowerSource()
CUPowerSource::~CUPowerSource () default
Member Function Documentation
BatteryLevel()
double CUPowerSource::BatteryLevel ()
References m_batteryLevel.
IsRechargeable()
bool CUPowerSource::IsRechargeable ()
References m_isRechargeable.
Update()
void CUPowerSource::Update ()
References CVariant::asDouble(), CDBusUtil::GetAll(), m_batteryLevel, and m_powerSource.
Referenced by CUPowerSource().
Member Data Documentation
m_batteryLevel
double CUPowerSource::m_batteryLevel private
Referenced by BatteryLevel(), and Update().
m_isRechargeable
bool CUPowerSource::m_isRechargeable private
Referenced by CUPowerSource(), and IsRechargeable().
m_powerSource
std::string CUPowerSource::m_powerSource private
Referenced by CUPowerSource(), and Update().
The documentation for this class was generated from the following files:
UPowerSyscall.h
UPowerSyscall.cpp