Kodi Documentation: KODI::RETRO::CRPRenderManager Class Reference
KODI::RETRO::CRPRenderManager Class Reference
Renders video frames provided by the game loop.
#include <RPRenderManager.h>
Public Member Functions
CRPRenderManager (CRPProcessInfo &processInfo)
~CRPRenderManager () override=default
void Initialize ()
void Deinitialize ()
CGUIRenderTargetFactory * GetGUIRenderTargetFactory ()
Access the factory for creating GUI render targets.
AVPixelFormat GetPixelFormat () const
unsigned int GetNominalWidth () const
unsigned int GetNominalHeight () const
unsigned int GetMaxWidth () const
unsigned int GetMaxHeight () const
float GetPixelAspectRatio () const
bool Configure (AVPixelFormat format, unsigned int nominalWidth, unsigned int nominalHeight, unsigned int maxWidth, unsigned int maxHeight, float pixelAspectRatio)
bool GetVideoBuffer (unsigned int width, unsigned int height, VideoStreamBuffer &buffer)
void AddFrame (const uint8_t *data, size_t size, unsigned int width, unsigned int height, unsigned int orientationDegCW)
void Flush ()
void SetSpeed (double speed)
void FrameMove ()
void RenderWindow (bool bClear, const RESOLUTION_INFO &coordsRes) override
Render a fullscreen window.
void RenderControl (bool bClear, bool bUseAlpha, const CRect &renderRegion, const IGUIRenderSettings *renderSettings) override
Render a game control.
void ClearBackground () override
Clear the background of a fullscreen window.
bool SupportsRenderFeature (RENDERFEATURE feature) const override
bool SupportsScalingMethod (SCALINGMETHOD method) const override
void SaveThumbnail (const std::string &thumbnailPath)
void CacheVideoFrame (const std::string &savestatePath)
void SaveVideoFrame (const std::string &savestatePath, ISavestate &savestate)
void ClearVideoFrame (const std::string &savestatePath)
Public Member Functions inherited from KODI::RETRO::IRenderManager
virtual ~IRenderManager ()=default
Public Member Functions inherited from KODI::RETRO::IRenderCallback
virtual ~IRenderCallback ()=default
Private Types
enum class RENDER_STATE { UNCONFIGURED , CONFIGURING , CONFIGURED }
Private Member Functions
std::shared_ptr< CRPBaseRenderer > GetRendererForSettings (const IGUIRenderSettings *renderSettings)
Get or create a renderer compatible with the given render settings.
std::shared_ptr< CRPBaseRenderer > GetRendererForPool (IRenderBufferPool *bufferPool, const CRenderSettings &renderSettings)
Get or create a renderer for the given buffer pool and render settings.
void RenderInternal (const std::shared_ptr< CRPBaseRenderer > &renderer, IRenderBuffer *renderBuffer, bool bClear, uint32_t alpha)
Render a frame using the given renderer.
bool HasRenderBuffer (IRenderBufferPool *bufferPool)
Return true if we have a render buffer belonging to the specified pool.
IRenderBuffer * GetRenderBuffer (IRenderBufferPool *bufferPool)
Get a render buffer belonging to the specified pool.
IRenderBuffer * GetRenderBufferForSavestate (const std::string &savestatePath, const IRenderBufferPool *bufferPool)
Get a render buffer containing pixels from the specified savestate.
void CreateRenderBuffer (IRenderBufferPool *bufferPool)
Create a render buffer for the specified pool from a cached frame.
IRenderBuffer * CreateFromCache (std::vector< uint8_t > &cachedFrame, unsigned int width, unsigned int height, IRenderBufferPool *bufferPool, CCriticalSection &mutex)
Create a render buffer and copy the cached data into it.
void CopyFrame (IRenderBuffer *renderBuffer, AVPixelFormat format, const uint8_t *data, size_t size, unsigned int width, unsigned int height)
Utility function to copy a frame and rescale pixels if necessary.
CRenderVideoSettings GetEffectiveSettings (const IGUIRenderSettings *settings) const
void CheckFlush ()
void GetVideoFrame (IRenderBuffer *&readableBuffer, std::vector< uint8_t > &cachedFrame)
void FreeVideoFrame (IRenderBuffer *readableBuffer, std::vector< uint8_t > cachedFrame)
void LoadVideoFrameAsync (const std::string &savestatePath)
void LoadVideoFrameSync (const std::string &savestatePath)
Private Attributes
CRPProcessInfo & m_processInfo
CRenderContext & m_renderContext
std::shared_ptr< IGUIRenderSettings > m_renderSettings
std::shared_ptr< CGUIRenderTargetFactory > m_renderControlFactory
AVPixelFormat m_format = AV_PIX_FMT_NONE
unsigned int m_nominalWidth {0}
unsigned int m_nominalHeight {0}
unsigned int m_maxWidth = 0
unsigned int m_maxHeight = 0
float m_pixelAspectRatio {1.0f}
std::set< std::shared_ptr< CRPBaseRenderer > > m_renderers
std::vector< IRenderBuffer * > m_pendingBuffers
std::vector< IRenderBuffer * > m_renderBuffers
std::map< AVPixelFormat, std::map< AVPixelFormat, SwsContext * > > m_scalers
std::vector< uint8_t > m_cachedFrame
unsigned int m_cachedWidth = 0
unsigned int m_cachedHeight = 0
unsigned int m_cachedRotationCCW {0}
std::map< std::string, std::vector< IRenderBuffer * > > m_savestateBuffers
std::vector< std::future< void > > m_savestateThreads
RENDER_STATE m_state = RENDER_STATE::UNCONFIGURED
bool m_bHasCachedFrame = false
std::set< std::string > m_failedShaderPresets
std::atomic< bool > m_bFlush = {false}
bool m_bDisplayScaleSet = false
std::atomic< double > m_speed = {1.0}
CCriticalSection m_stateMutex
CCriticalSection m_bufferMutex
Detailed Description
Renders video frames provided by the game loop.
Generally, buffer pools are registered by the windowing subsystem. A buffer pool provides a software or hardware buffer to store the added frame. When RenderManager is created, it instantiates all registered buffer pools.
When a frame arrives, it is copied into a buffer from each buffer pool with a visible renderer. For example, if a GLES and MMAL renderer are both visible in the GUI, then the frame will be copied into two buffers.
When it is time to render the frame, the GUI control or window calls into this class through the IRenderManager interface. RenderManager selects an appropriate renderer to use to render the frame. The renderer is then given the buffer that came from its buffer pool.
Special behavior is needed when the game is paused. As no new frames are delivered, a newly created renderer will stay black. For this scenario, when we detect a pause event, the frame is preemptively cached so that a newly created renderer will have something to display.
Member Enumeration Documentation
RENDER_STATE
enum class KODI::RETRO::CRPRenderManager::RENDER_STATE strong private
Enumerator
UNCONFIGURED
CONFIGURING
CONFIGURED
Constructor & Destructor Documentation
CRPRenderManager()
CRPRenderManager::CRPRenderManager (CRPProcessInfo & processInfo)
~CRPRenderManager()
KODI::RETRO::CRPRenderManager::~CRPRenderManager () override default
Member Function Documentation
AddFrame()
void CRPRenderManager::AddFrame (const uint8_t * data, size_t size, unsigned int width, unsigned int height, unsigned int orientationDegCW)
References CONFIGURED, CopyFrame(), data(), KODI::RETRO::CRPProcessInfo::GetBufferManager(), KODI::RETRO::CRenderBufferManager::GetBufferPools(), CLog::Log(), LOGDEBUG, m_bFlush, m_bHasCachedFrame, m_bufferMutex, m_cachedFrame, m_cachedHeight, m_cachedRotationCCW, m_cachedWidth, m_format, m_pendingBuffers, m_processInfo, m_renderBuffers, m_speed, and m_state.
Referenced by KODI::RETRO::CRetroPlayerVideo::AddStreamData().
CacheVideoFrame()
void CRPRenderManager::CacheVideoFrame (const std::string & savestatePath)
References m_bufferMutex, m_renderBuffers, and m_savestateBuffers.
Referenced by KODI::RETRO::CReversiblePlayback::CreateSavestate().
CheckFlush()
void CRPRenderManager::CheckFlush () private
References KODI::RETRO::CRenderBufferManager::FlushPools(), KODI::RETRO::CRPProcessInfo::GetBufferManager(), m_bFlush, m_bHasCachedFrame, m_bufferMutex, m_cachedFrame, m_cachedHeight, m_cachedWidth, m_processInfo, m_renderBuffers, and m_renderers.
Referenced by FrameMove().
ClearBackground()
void CRPRenderManager::ClearBackground () override virtual
Clear the background of a fullscreen window.
Implements KODI::RETRO::IRenderManager.
References KODI::RETRO::CRenderContext::Clear(), and m_renderContext.
ClearVideoFrame()
void CRPRenderManager::ClearVideoFrame (const std::string & savestatePath)
References m_bufferMutex, and m_savestateBuffers.
Configure()
bool CRPRenderManager::Configure (AVPixelFormat format, unsigned int nominalWidth, unsigned int nominalHeight, unsigned int maxWidth, unsigned int maxHeight, float pixelAspectRatio)
References CONFIGURING, CLog::Log(), LOGINFO, m_format, m_maxHeight, m_maxWidth, m_nominalHeight, m_nominalWidth, m_pixelAspectRatio, m_state, m_stateMutex, and KODI::RETRO::CRenderTranslator::TranslatePixelFormat().
Referenced by KODI::RETRO::CRetroPlayerVideo::OpenStream().
CopyFrame()
void CRPRenderManager::CopyFrame (IRenderBuffer * renderBuffer, AVPixelFormat format, const uint8_t * data, size_t size, unsigned int width, unsigned int height) private
Utility function to copy a frame and rescale pixels if necessary.
References data(), KODI::RETRO::IRenderBuffer::GetFormat(), KODI::RETRO::IRenderBuffer::GetFrameSize(), KODI::RETRO::IRenderBuffer::GetHeight(), KODI::RETRO::IRenderBuffer::GetMemory(), KODI::RETRO::IRenderBuffer::GetWidth(), m_scalers, KODI::RETRO::IRenderBuffer::ReleaseMemory(), and KODI::RETRO::CRenderTranslator::TranslateWidthToBytes().
Referenced by AddFrame(), CreateFromCache(), and LoadVideoFrameSync().
CreateFromCache()
IRenderBuffer * CRPRenderManager::CreateFromCache (std::vector< uint8_t > & cachedFrame, unsigned int width, unsigned int height, IRenderBufferPool * bufferPool, CCriticalSection & mutex) private
Create a render buffer and copy the cached data into it.
The cached frame is accessed by both the game and rendering threads, and therefore requires synchronization.
However, assuming the memory copy is expensive, we must avoid holding the mutex during the copy.
To allow for this, the function is permitted to invalidate its cachedFrame parameter, as long as it is restored upon exit. While the mutex is exited inside this function, cachedFrame is guaranteed to be empty.
Parameters
cachedFrame The cached frame
width The width of the cached frame
height The height of the cached frame
bufferPool The buffer pool used to create the render buffer
mutex The locked mutex, to be unlocked during memory copy
Returns
The render buffer if one was created from the cached frame, otherwise nullptr
References CopyFrame(), KODI::RETRO::IRenderBufferPool::GetBuffer(), CLog::Log(), LOGERROR, m_format, and mutex.
Referenced by CreateRenderBuffer().
CreateRenderBuffer()
void CRPRenderManager::CreateRenderBuffer (IRenderBufferPool * bufferPool) private
Create a render buffer for the specified pool from a cached frame.
References CONFIGURED, CreateFromCache(), HasRenderBuffer(), m_bFlush, m_bHasCachedFrame, m_bufferMutex, m_cachedFrame, m_cachedHeight, m_cachedWidth, m_renderBuffers, and m_state.
Referenced by GetRenderBuffer(), and GetRendererForPool().
Deinitialize()
void CRPRenderManager::Deinitialize ()
References CLog::Log(), LOGDEBUG, m_pendingBuffers, m_renderBuffers, m_renderers, m_savestateBuffers, m_savestateThreads, m_scalers, m_state, and UNCONFIGURED.
Referenced by KODI::RETRO::CRetroPlayerVideo::~CRetroPlayerVideo().
Flush()
void CRPRenderManager::Flush ()
References m_bFlush.
Referenced by KODI::RETRO::CRetroPlayerVideo::CloseStream().
FrameMove()
void CRPRenderManager::FrameMove ()
References CheckFlush(), CONFIGURED, CONFIGURING, CLog::Log(), LOGINFO, m_renderers, m_state, and m_stateMutex.
FreeVideoFrame()
void CRPRenderManager::FreeVideoFrame (IRenderBuffer * readableBuffer, std::vector< uint8_t > cachedFrame) private
References m_bufferMutex, m_cachedFrame, KODI::RETRO::IRenderBuffer::Release(), and KODI::RETRO::IRenderBuffer::ReleaseMemory().
Referenced by SaveThumbnail(), and SaveVideoFrame().
GetEffectiveSettings()
CRenderVideoSettings CRPRenderManager::GetEffectiveSettings (const IGUIRenderSettings * settings) const private
References KODI::RETRO::CRPProcessInfo::GetDefaultScalingMethod(), KODI::RETRO::CRenderVideoSettings::GetPixels(), KODI::RETRO::CRenderVideoSettings::GetRenderRotation(), KODI::RETRO::CRenderVideoSettings::GetRenderStretchMode(), KODI::RETRO::CRenderVideoSettings::GetScalingMethod(), KODI::RETRO::IGUIRenderSettings::GetSettings(), KODI::RETRO::CRenderVideoSettings::GetVideoFilter(), KODI::RETRO::IGUIRenderSettings::HasPixels(), KODI::RETRO::IGUIRenderSettings::HasRotation(), KODI::RETRO::CRPProcessInfo::HasScalingMethod(), KODI::RETRO::IGUIRenderSettings::HasStretchMode(), KODI::RETRO::IGUIRenderSettings::HasVideoFilter(), m_processInfo, m_renderSettings, KODI::RETRO::CRenderVideoSettings::SetPixels(), KODI::RETRO::CRenderVideoSettings::SetRenderRotation(), KODI::RETRO::CRenderVideoSettings::SetRenderStretchMode(), KODI::RETRO::CRenderVideoSettings::SetScalingMethod(), KODI::RETRO::CRenderVideoSettings::SetVideoFilter(), and KODI::RETRO::CRenderSettings::VideoSettings().
Referenced by GetRendererForSettings(), and RenderWindow().
GetGUIRenderTargetFactory()
CGUIRenderTargetFactory * KODI::RETRO::CRPRenderManager::GetGUIRenderTargetFactory () inline
Access the factory for creating GUI render targets.
References m_renderControlFactory.
GetMaxHeight()
unsigned int KODI::RETRO::CRPRenderManager::GetMaxHeight () const inline
References m_maxHeight.
GetMaxWidth()
unsigned int KODI::RETRO::CRPRenderManager::GetMaxWidth () const inline
References m_maxWidth.
GetNominalHeight()
unsigned int KODI::RETRO::CRPRenderManager::GetNominalHeight () const inline
References m_nominalHeight.
GetNominalWidth()
unsigned int KODI::RETRO::CRPRenderManager::GetNominalWidth () const inline
References m_nominalWidth.
GetPixelAspectRatio()
float KODI::RETRO::CRPRenderManager::GetPixelAspectRatio () const inline
References m_pixelAspectRatio.
GetPixelFormat()
AVPixelFormat KODI::RETRO::CRPRenderManager::GetPixelFormat () const inline
References m_format.
GetRenderBuffer()
IRenderBuffer * CRPRenderManager::GetRenderBuffer (IRenderBufferPool * bufferPool) private
Get a render buffer belonging to the specified pool.
References KODI::RETRO::IRenderBuffer::Acquire(), CONFIGURED, CreateRenderBuffer(), KODI::RETRO::IRenderBuffer::GetPool(), m_bFlush, m_bufferMutex, m_renderBuffers, and m_state.
Referenced by RenderControl(), and RenderWindow().
GetRenderBufferForSavestate()
IRenderBuffer * CRPRenderManager::GetRenderBufferForSavestate (const std::string & savestatePath, const IRenderBufferPool * bufferPool) private
Get a render buffer containing pixels from the specified savestate.
References KODI::RETRO::IRenderBuffer::Acquire(), LoadVideoFrameAsync(), m_bufferMutex, and m_savestateBuffers.
Referenced by RenderControl().
GetRendererForPool()
std::shared_ptr< CRPBaseRenderer > CRPRenderManager::GetRendererForPool (IRenderBufferPool * bufferPool, const CRenderSettings & renderSettings) private
Get or create a renderer for the given buffer pool and render settings.
References CreateRenderBuffer(), KODI::RETRO::CRPProcessInfo::CreateRenderer(), KODI::RETRO::CRPProcessInfo::GetRenderSystemName(), KODI::RETRO::IRenderBufferPool::IsCompatible(), CLog::Log(), LOGDEBUG, m_format, m_processInfo, m_renderers, and KODI::RETRO::CRenderSettings::VideoSettings().
Referenced by GetRendererForSettings().
GetRendererForSettings()
std::shared_ptr< CRPBaseRenderer > CRPRenderManager::GetRendererForSettings (const IGUIRenderSettings * renderSettings) private
Get or create a renderer compatible with the given render settings.
References KODI::RETRO::CRPProcessInfo::GetBufferManager(), KODI::RETRO::CRenderBufferManager::GetBufferPools(), GetEffectiveSettings(), KODI::RETRO::CRenderVideoSettings::GetPixels(), GetRendererForPool(), KODI::RETRO::CRenderVideoSettings::GetRenderRotation(), KODI::RETRO::CRenderVideoSettings::GetRenderStretchMode(), KODI::RETRO::CRenderVideoSettings::GetScalingMethod(), m_processInfo, m_state, m_stateMutex, UNCONFIGURED, and KODI::RETRO::CRenderSettings::VideoSettings().
Referenced by RenderControl(), and RenderWindow().
GetVideoBuffer()
bool CRPRenderManager::GetVideoBuffer (unsigned int width, unsigned int height, VideoStreamBuffer & buffer)
Todo:
De-prioritize buffer pools with write-only or unaligned memory
References CONFIGURED, KODI::RETRO::CRPProcessInfo::GetBufferManager(), KODI::RETRO::CRenderBufferManager::GetBufferPools(), KODI::RETRO::IRenderBuffer::GetFormat(), KODI::RETRO::IRenderBuffer::GetFrameSize(), KODI::RETRO::IRenderBuffer::GetMemory(), KODI::RETRO::IRenderBuffer::GetMemoryAccess(), KODI::RETRO::IRenderBuffer::GetMemoryAlignment(), CLog::Log(), LOGDEBUG, m_bFlush, m_pendingBuffers, m_processInfo, and m_state.
Referenced by KODI::RETRO::CRetroPlayerVideo::GetStreamBuffer().
GetVideoFrame()
void CRPRenderManager::GetVideoFrame (IRenderBuffer *& readableBuffer, std::vector< uint8_t > & cachedFrame) private
References KODI::RETRO::IRenderBuffer::Acquire(), m_bHasCachedFrame, m_bufferMutex, m_cachedFrame, m_renderBuffers, and m_speed.
Referenced by SaveThumbnail(), and SaveVideoFrame().
HasRenderBuffer()
bool CRPRenderManager::HasRenderBuffer (IRenderBufferPool * bufferPool) private
Return true if we have a render buffer belonging to the specified pool.
References m_bufferMutex, and m_renderBuffers.
Referenced by CreateRenderBuffer().
Initialize()
void CRPRenderManager::Initialize ()
References CLog::Log(), and LOGDEBUG.
Referenced by KODI::RETRO::CRetroPlayerVideo::CRetroPlayerVideo().
LoadVideoFrameAsync()
void CRPRenderManager::LoadVideoFrameAsync (const std::string & savestatePath) private
References LoadVideoFrameSync(), and m_savestateThreads.
Referenced by GetRenderBufferForSavestate().
LoadVideoFrameSync()
void CRPRenderManager::LoadVideoFrameSync (const std::string & savestatePath) private
References KODI::RETRO::CSavestateDatabase::AllocateSavestate(), CopyFrame(), data(), XFILE::CFile::Exists(), KODI::RETRO::CRPProcessInfo::GetBufferManager(), KODI::RETRO::CRenderBufferManager::GetBufferPools(), KODI::RETRO::CSavestateDatabase::GetSavestate(), CLog::Log(), LOGDEBUG, LOGERROR, m_bufferMutex, m_processInfo, m_savestateBuffers, savestate, and KODI::RETRO::IRenderBuffer::SetRotation().
Referenced by LoadVideoFrameAsync().
RenderControl()
void CRPRenderManager::RenderControl (bool bClear, bool bUseAlpha, const CRect & renderRegion, const IGUIRenderSettings * renderSettings) override virtual
Render a game control.
Parameters
bClear Whether the render area should be cleared
bUseAlpha Whether the graphics context's alpha should be used
renderRegion The region of the control being rendered
renderSettings The settings used to render the control
Implements KODI::RETRO::IRenderManager.
References KODI::UTILS::COLOR::BLACK, KODI::RETRO::CRenderContext::Clear(), KODI::RETRO::IGUIRenderSettings::GetDimensions(), GetRenderBuffer(), GetRenderBufferForSavestate(), GetRendererForSettings(), KODI::RETRO::CRenderContext::GetScissors(), CRectGen< T >::Intersect(), KODI::RETRO::CRenderContext::IsFullScreenVideo(), m_renderContext, KODI::RETRO::CRenderContext::MergeAlpha(), KODI::RETRO::CRenderContext::RemoveTransform(), RenderInternal(), KODI::RETRO::CRenderContext::SetFullScreenVideo(), KODI::RETRO::CRenderContext::SetScissors(), KODI::RETRO::CRenderContext::SetTransform(), KODI::RETRO::CRenderContext::SetViewWindow(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
RenderInternal()
void CRPRenderManager::RenderInternal (const std::shared_ptr< CRPBaseRenderer > & renderer, IRenderBuffer * renderBuffer, bool bClear, uint32_t alpha) private
Render a frame using the given renderer.
References KODI::RETRO::CRenderContext::GraphicsMutex(), KODI::RETRO::IRenderBuffer::IsLoaded(), m_renderContext, KODI::RETRO::IRenderBuffer::Release(), KODI::RETRO::IRenderBuffer::SetLoaded(), and KODI::RETRO::IRenderBuffer::UploadTexture().
Referenced by RenderControl(), and RenderWindow().
RenderWindow()
void CRPRenderManager::RenderWindow (bool bClear, const RESOLUTION_INFO & coordsRes) override virtual
Render a fullscreen window.
Parameters
bClear Whether the render area should be cleared
coordsRes Resolution that the window coordinates are in
Implements KODI::RETRO::IRenderManager.
References OVERSCAN::bottom, KODI::RETRO::CRenderContext::DisplayHardwareScalingEnabled(), GetEffectiveSettings(), KODI::RETRO::IRenderBuffer::GetHeight(), GetRenderBuffer(), GetRendererForSettings(), KODI::RETRO::CRenderVideoSettings::GetRenderStretchMode(), KODI::RETRO::CRenderContext::GetResInfo(), KODI::RETRO::CRenderVideoSettings::GetScalingMethod(), KODI::RETRO::CRenderContext::GetVideoResolution(), KODI::RETRO::IRenderBuffer::GetWidth(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iWidth, OVERSCAN::left, m_bDisplayScaleSet, m_renderContext, KODI::RETRO::NEAREST, KODI::RETRO::Original, RESOLUTION_INFO::Overscan, RenderInternal(), OVERSCAN::right, KODI::RETRO::CRenderContext::SetRenderingResolution(), OVERSCAN::top, and KODI::RETRO::CRenderContext::UpdateDisplayHardwareScaling().
SaveThumbnail()
void CRPRenderManager::SaveThumbnail (const std::string & thumbnailPath)
Todo:
rotate image by rotationCCW
References CPicture::CreateThumbnailFromSurface(), FreeVideoFrame(), KODI::RETRO::IRenderBuffer::GetFormat(), KODI::RETRO::IRenderBuffer::GetFrameSize(), KODI::RETRO::IRenderBuffer::GetHeight(), KODI::RETRO::IRenderBuffer::GetMemory(), KODI::RETRO::IRenderBuffer::GetRotation(), CPicture::GetScale(), GetVideoFrame(), KODI::RETRO::IRenderBuffer::GetWidth(), CLog::Log(), LOGERROR, m_cachedFrame, m_cachedHeight, m_cachedRotationCCW, m_cachedWidth, m_format, CPicture::ScaleImage(), KODI::RETRO::CRenderTranslator::TranslateWidthToBytes(), and void().
Referenced by KODI::RETRO::CReversiblePlayback::CommitSavestate().
SaveVideoFrame()
void CRPRenderManager::SaveVideoFrame (const std::string & savestatePath, ISavestate & savestate)
References FreeVideoFrame(), KODI::RETRO::IRenderBuffer::GetFormat(), KODI::RETRO::IRenderBuffer::GetFrameSize(), KODI::RETRO::IRenderBuffer::GetHeight(), KODI::RETRO::IRenderBuffer::GetMemory(), KODI::RETRO::IRenderBuffer::GetRotation(), GetVideoFrame(), KODI::RETRO::IRenderBuffer::GetWidth(), CLog::Log(), LOGERROR, m_cachedFrame, m_cachedHeight, m_cachedRotationCCW, m_cachedWidth, m_format, m_maxHeight, m_maxWidth, m_nominalHeight, m_nominalWidth, m_pixelAspectRatio, and savestate.
Referenced by KODI::RETRO::CReversiblePlayback::CommitSavestate().
SetSpeed()
void CRPRenderManager::SetSpeed (double speed)
References m_speed.
SupportsRenderFeature()
bool CRPRenderManager::SupportsRenderFeature (RENDERFEATURE feature) const override virtual
Todo:
Move to ProcessInfo
Implements KODI::RETRO::IRenderCallback.
References m_renderers.
SupportsScalingMethod()
bool CRPRenderManager::SupportsScalingMethod (SCALINGMETHOD method) const override virtual
Todo:
Move to ProcessInfo
Implements KODI::RETRO::IRenderCallback.
References KODI::RETRO::CRPProcessInfo::GetBufferManager(), KODI::RETRO::CRenderBufferManager::GetBufferPools(), m_processInfo, and KODI::RETRO::CRenderVideoSettings::SetScalingMethod().
Member Data Documentation
m_bDisplayScaleSet
bool KODI::RETRO::CRPRenderManager::m_bDisplayScaleSet = false private
Referenced by RenderWindow().
m_bFlush
std::atomic<bool> KODI::RETRO::CRPRenderManager::m_bFlush = {false} private
Referenced by AddFrame(), CheckFlush(), CreateRenderBuffer(), Flush(), GetRenderBuffer(), and GetVideoBuffer().
m_bHasCachedFrame
bool KODI::RETRO::CRPRenderManager::m_bHasCachedFrame = false private
Referenced by AddFrame(), CheckFlush(), CreateRenderBuffer(), and GetVideoFrame().
m_bufferMutex
CCriticalSection KODI::RETRO::CRPRenderManager::m_bufferMutex private
Referenced by AddFrame(), CacheVideoFrame(), CheckFlush(), ClearVideoFrame(), CreateRenderBuffer(), FreeVideoFrame(), GetRenderBuffer(), GetRenderBufferForSavestate(), GetVideoFrame(), HasRenderBuffer(), and LoadVideoFrameSync().
m_cachedFrame
std::vector<uint8_t> KODI::RETRO::CRPRenderManager::m_cachedFrame private
Referenced by AddFrame(), CheckFlush(), CreateRenderBuffer(), FreeVideoFrame(), GetVideoFrame(), SaveThumbnail(), and SaveVideoFrame().
m_cachedHeight
unsigned int KODI::RETRO::CRPRenderManager::m_cachedHeight = 0 private
Referenced by AddFrame(), CheckFlush(), CreateRenderBuffer(), SaveThumbnail(), and SaveVideoFrame().
m_cachedRotationCCW
unsigned int KODI::RETRO::CRPRenderManager::m_cachedRotationCCW {0} private
Referenced by AddFrame(), SaveThumbnail(), and SaveVideoFrame().
m_cachedWidth
unsigned int KODI::RETRO::CRPRenderManager::m_cachedWidth = 0 private
Referenced by AddFrame(), CheckFlush(), CreateRenderBuffer(), SaveThumbnail(), and SaveVideoFrame().
m_failedShaderPresets
std::set<std::string> KODI::RETRO::CRPRenderManager::m_failedShaderPresets private
m_format
AVPixelFormat KODI::RETRO::CRPRenderManager::m_format = AV_PIX_FMT_NONE private
Referenced by AddFrame(), Configure(), CreateFromCache(), GetPixelFormat(), GetRendererForPool(), SaveThumbnail(), and SaveVideoFrame().
m_maxHeight
unsigned int KODI::RETRO::CRPRenderManager::m_maxHeight = 0 private
Referenced by Configure(), GetMaxHeight(), and SaveVideoFrame().
m_maxWidth
unsigned int KODI::RETRO::CRPRenderManager::m_maxWidth = 0 private
Referenced by Configure(), GetMaxWidth(), and SaveVideoFrame().
m_nominalHeight
unsigned int KODI::RETRO::CRPRenderManager::m_nominalHeight {0} private
Referenced by Configure(), GetNominalHeight(), and SaveVideoFrame().
m_nominalWidth
unsigned int KODI::RETRO::CRPRenderManager::m_nominalWidth {0} private
Referenced by Configure(), GetNominalWidth(), and SaveVideoFrame().
m_pendingBuffers
std::vector<IRenderBuffer*> KODI::RETRO::CRPRenderManager::m_pendingBuffers private
Referenced by AddFrame(), Deinitialize(), and GetVideoBuffer().
m_pixelAspectRatio
float KODI::RETRO::CRPRenderManager::m_pixelAspectRatio {1.0f} private
Referenced by Configure(), GetPixelAspectRatio(), and SaveVideoFrame().
m_processInfo
CRPProcessInfo& KODI::RETRO::CRPRenderManager::m_processInfo private
Referenced by AddFrame(), CheckFlush(), GetEffectiveSettings(), GetRendererForPool(), GetRendererForSettings(), GetVideoBuffer(), LoadVideoFrameSync(), and SupportsScalingMethod().
m_renderBuffers
std::vector<IRenderBuffer*> KODI::RETRO::CRPRenderManager::m_renderBuffers private
Referenced by AddFrame(), CacheVideoFrame(), CheckFlush(), CreateRenderBuffer(), Deinitialize(), GetRenderBuffer(), GetVideoFrame(), and HasRenderBuffer().
m_renderContext
CRenderContext& KODI::RETRO::CRPRenderManager::m_renderContext private
Referenced by ClearBackground(), RenderControl(), RenderInternal(), and RenderWindow().
m_renderControlFactory
std::shared_ptr<CGUIRenderTargetFactory> KODI::RETRO::CRPRenderManager::m_renderControlFactory private
Referenced by GetGUIRenderTargetFactory().
m_renderers
std::set<std::shared_ptr<CRPBaseRenderer> > KODI::RETRO::CRPRenderManager::m_renderers private
Referenced by CheckFlush(), Deinitialize(), FrameMove(), GetRendererForPool(), and SupportsRenderFeature().
m_renderSettings
std::shared_ptr<IGUIRenderSettings> KODI::RETRO::CRPRenderManager::m_renderSettings private
Referenced by GetEffectiveSettings().
m_savestateBuffers
std::map<std::string, std::vector<IRenderBuffer*> > KODI::RETRO::CRPRenderManager::m_savestateBuffers private
Referenced by CacheVideoFrame(), ClearVideoFrame(), Deinitialize(), GetRenderBufferForSavestate(), and LoadVideoFrameSync().
m_savestateThreads
std::vector<std::future<void> > KODI::RETRO::CRPRenderManager::m_savestateThreads private
Referenced by Deinitialize(), and LoadVideoFrameAsync().
m_scalers
std::map<AVPixelFormat, std::map<AVPixelFormat, SwsContext*> > KODI::RETRO::CRPRenderManager::m_scalers private
Referenced by CopyFrame(), and Deinitialize().
m_speed
std::atomic<double> KODI::RETRO::CRPRenderManager::m_speed = {1.0} private
Referenced by AddFrame(), GetVideoFrame(), and SetSpeed().
m_state
RENDER_STATE KODI::RETRO::CRPRenderManager::m_state = RENDER_STATE::UNCONFIGURED private
Referenced by AddFrame(), Configure(), CreateRenderBuffer(), Deinitialize(), FrameMove(), GetRenderBuffer(), GetRendererForSettings(), and GetVideoBuffer().
m_stateMutex
CCriticalSection KODI::RETRO::CRPRenderManager::m_stateMutex private
Referenced by Configure(), FrameMove(), and GetRendererForSettings().
The documentation for this class was generated from the following files:
RPRenderManager.h
RPRenderManager.cpp