Kodi Documentation: WSDiscovery::CClientNotificationSink Class Reference
WSDiscovery::CClientNotificationSink Class Reference
#include <WSDiscoveryWin32.h>
Public Member Functions
CClientNotificationSink ()
~CClientNotificationSink ()
HRESULT STDMETHODCALLTYPE Add (IWSDiscoveredService *service)
HRESULT STDMETHODCALLTYPE Remove (IWSDiscoveredService *service)
HRESULT STDMETHODCALLTYPE SearchFailed (HRESULT hr, LPCWSTR tag)
HRESULT STDMETHODCALLTYPE SearchComplete (LPCWSTR tag)
HRESULT STDMETHODCALLTYPE QueryInterface (REFIID riid, void **object)
ULONG STDMETHODCALLTYPE AddRef ()
ULONG STDMETHODCALLTYPE Release ()
bool ThereAreServers ()
std::vector< std::wstring > GetServersIPs ()
Static Public Member Functions
static HRESULT Create (CClientNotificationSink **sink)
Private Attributes
std::vector< std::wstring > m_serversIPs
ULONG m_cRef
CCriticalSection m_criticalSection
Constructor & Destructor Documentation
CClientNotificationSink()
WSDiscovery::CClientNotificationSink::CClientNotificationSink ()
Referenced by Create().
~CClientNotificationSink()
WSDiscovery::CClientNotificationSink::~CClientNotificationSink ()
Member Function Documentation
Add()
HRESULT STDMETHODCALLTYPE WSDiscovery::CClientNotificationSink::Add (IWSDiscoveredService * service)
References CLog::Log(), LOGDEBUG, LOGWSDISCOVERY, m_criticalSection, and m_serversIPs.
AddRef()
ULONG STDMETHODCALLTYPE WSDiscovery::CClientNotificationSink::AddRef ()
References m_cRef.
Create()
HRESULT WSDiscovery::CClientNotificationSink::Create (CClientNotificationSink ** sink) static
References CClientNotificationSink().
Referenced by WSDiscovery::CWSDiscoveryWindows::StartServices().
GetServersIPs()
std::vector< std::wstring > WSDiscovery::CClientNotificationSink::GetServersIPs () inline
References m_serversIPs.
Referenced by WSDiscovery::CWSDiscoveryWindows::GetServersIPs(), and SearchComplete().
QueryInterface()
HRESULT STDMETHODCALLTYPE WSDiscovery::CClientNotificationSink::QueryInterface (REFIID riid, void ** object)
Release()
ULONG STDMETHODCALLTYPE WSDiscovery::CClientNotificationSink::Release ()
References m_cRef.
Referenced by WSDiscovery::CWSDiscoveryWindows::StopServices().
Remove()
HRESULT STDMETHODCALLTYPE WSDiscovery::CClientNotificationSink::Remove (IWSDiscoveredService * service)
References CLog::Log(), LOGDEBUG, LOGWSDISCOVERY, m_criticalSection, and m_serversIPs.
SearchComplete()
HRESULT STDMETHODCALLTYPE WSDiscovery::CClientNotificationSink::SearchComplete (LPCWSTR tag)
References GetServersIPs(), CLog::Log(), LOGDEBUG, m_criticalSection, and m_serversIPs.
SearchFailed()
HRESULT STDMETHODCALLTYPE WSDiscovery::CClientNotificationSink::SearchFailed (HRESULT hr, LPCWSTR tag)
References CLog::Log(), LOGWARNING, and m_criticalSection.
ThereAreServers()
bool WSDiscovery::CClientNotificationSink::ThereAreServers () inline
References m_serversIPs.
Referenced by WSDiscovery::CWSDiscoveryWindows::ThereAreServers().
Member Data Documentation
m_cRef
ULONG WSDiscovery::CClientNotificationSink::m_cRef private
Referenced by AddRef(), and Release().
m_criticalSection
CCriticalSection WSDiscovery::CClientNotificationSink::m_criticalSection private
Referenced by Add(), Remove(), SearchComplete(), and SearchFailed().
m_serversIPs
std::vector<std::wstring> WSDiscovery::CClientNotificationSink::m_serversIPs private
Referenced by Add(), GetServersIPs(), Remove(), SearchComplete(), and ThereAreServers().
The documentation for this class was generated from the following files:
WSDiscoveryWin32.h
WSDiscoveryWin32.cpp