Kodi Documentation: CWin32PowerSyscall Class Reference
CWin32PowerSyscall Class Reference
#include <Win32PowerSyscall.h>
Public Member Functions
CWin32PowerSyscall ()
~CWin32PowerSyscall ()
virtual bool Powerdown ()
virtual bool Suspend ()
virtual bool Hibernate ()
virtual bool Reboot ()
virtual bool CanPowerdown ()
virtual bool CanSuspend ()
virtual bool CanHibernate ()
virtual bool CanReboot ()
virtual int BatteryLevel ()
virtual bool PumpPowerEvents (IPowerEventsCallback *callback)
Pump power related events back to xbmc.
Public Member Functions inherited from CAbstractPowerSyscall
int CountPowerFeatures () override
Public Member Functions inherited from IPowerSyscall
virtual ~IPowerSyscall ()=default
Static Public Member Functions
static IPowerSyscall * CreateInstance ()
static void Register ()
static void SetOnResume ()
static void SetOnSuspend ()
static bool IsSuspending ()
Static Public Member Functions inherited from IPowerSyscall
static IPowerSyscall * CreateInstance ()
Called by power manager to create platform power system adapter.
static void RegisterPowerSyscall (CreatePowerSyscallFunc createFunc)
Private Attributes
BOOLEAN m_hascapabilities
SYSTEM_POWER_CAPABILITIES m_capabilities
CWin32PowerStateWorker m_worker
Static Private Attributes
static bool m_OnResume = false
static bool m_OnSuspend = false
Additional Inherited Members
Static Public Attributes inherited from IPowerSyscall
static const int MAX_COUNT_POWER_FEATURES = 4
Constructor & Destructor Documentation
CWin32PowerSyscall()
CWin32PowerSyscall::CWin32PowerSyscall ()
References CThread::Create(), m_capabilities, m_hascapabilities, and m_worker.
Referenced by CreateInstance().
~CWin32PowerSyscall()
CWin32PowerSyscall::~CWin32PowerSyscall ()
References CThread::IsRunning(), m_worker, and CThread::StopThread().
Member Function Documentation
BatteryLevel()
int CWin32PowerSyscall::BatteryLevel (void) virtual
Implements IPowerSyscall.
CanHibernate()
bool CWin32PowerSyscall::CanHibernate (void) virtual
Implements IPowerSyscall.
References m_capabilities, and m_hascapabilities.
CanPowerdown()
bool CWin32PowerSyscall::CanPowerdown (void) virtual
Implements IPowerSyscall.
CanReboot()
bool CWin32PowerSyscall::CanReboot (void) virtual
Implements IPowerSyscall.
CanSuspend()
bool CWin32PowerSyscall::CanSuspend (void) virtual
Implements IPowerSyscall.
References m_capabilities, and m_hascapabilities.
CreateInstance()
IPowerSyscall * CWin32PowerSyscall::CreateInstance () static
References CWin32PowerSyscall().
Referenced by Register().
Hibernate()
bool CWin32PowerSyscall::Hibernate (void) virtual
Implements IPowerSyscall.
References m_worker, POWERSTATE_HIBERNATE, and CWin32PowerStateWorker::QueryStateChange().
IsSuspending()
static bool CWin32PowerSyscall::IsSuspending () inline static
References m_OnSuspend.
Referenced by CMMNotificationClient::NotifyAE().
Powerdown()
bool CWin32PowerSyscall::Powerdown (void) virtual
Implements IPowerSyscall.
References m_worker, POWERSTATE_SHUTDOWN, and CWin32PowerStateWorker::QueryStateChange().
PumpPowerEvents()
bool CWin32PowerSyscall::PumpPowerEvents (IPowerEventsCallback * callback) virtual
Pump power related events back to xbmc.
PumpPowerEvents is called from Application Thread and the platform implementation may signal power related events back to xbmc through the callback.
return true if an event occurred and false if not.
Parameters
callback the callback to signal to
Implements IPowerSyscall.
References m_OnResume, and m_OnSuspend.
Reboot()
bool CWin32PowerSyscall::Reboot (void) virtual
Implements IPowerSyscall.
References m_worker, POWERSTATE_REBOOT, and CWin32PowerStateWorker::QueryStateChange().
Register()
void CWin32PowerSyscall::Register () static
References CreateInstance(), and IPowerSyscall::RegisterPowerSyscall().
Referenced by CPlatformWin32::InitStageOne().
SetOnResume()
static void CWin32PowerSyscall::SetOnResume () inline static
References m_OnResume.
Referenced by CWinEventsWin32::WndProc().
SetOnSuspend()
static void CWin32PowerSyscall::SetOnSuspend () inline static
References m_OnSuspend.
Referenced by CWinEventsWin32::WndProc().
Suspend()
bool CWin32PowerSyscall::Suspend (void) virtual
Implements IPowerSyscall.
References m_worker, POWERSTATE_SUSPEND, and CWin32PowerStateWorker::QueryStateChange().
Member Data Documentation
m_capabilities
SYSTEM_POWER_CAPABILITIES CWin32PowerSyscall::m_capabilities private
Referenced by CanHibernate(), CanSuspend(), and CWin32PowerSyscall().
m_hascapabilities
BOOLEAN CWin32PowerSyscall::m_hascapabilities private
Referenced by CanHibernate(), CanSuspend(), and CWin32PowerSyscall().
m_OnResume
bool CWin32PowerSyscall::m_OnResume = false static private
Referenced by PumpPowerEvents(), and SetOnResume().
m_OnSuspend
bool CWin32PowerSyscall::m_OnSuspend = false static private
Referenced by IsSuspending(), PumpPowerEvents(), and SetOnSuspend().
m_worker
CWin32PowerStateWorker CWin32PowerSyscall::m_worker private
Referenced by CWin32PowerSyscall(), Hibernate(), Powerdown(), Reboot(), Suspend(), and ~CWin32PowerSyscall().
The documentation for this class was generated from the following files:
Win32PowerSyscall.h
Win32PowerSyscall.cpp