Kodi Documentation: JSONRPC::CTCPServer Class Reference
JSONRPC::CTCPServer Class Reference
#include <TCPServer.h>
Classes
class CTCPClient
class CWebSocketClient
Public Member Functions
bool PrepareDownload (const char *path, CVariant &details, std::string &protocol) override
bool Download (const char *path, CVariant &result) override
int GetCapabilities () override
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
Public Member Functions inherited from JSONRPC::ITransportLayer
virtual ~ITransportLayer ()=default
Public Member Functions inherited from JSONRPC::IJSONRPCAnnouncer
~IJSONRPCAnnouncer () override=default
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Static Public Member Functions
static bool StartServer (int port, bool nonlocal)
static void StopServer (bool bWait)
static bool IsRunning ()
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Member Functions
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Member Functions
CTCPServer (int port, bool nonlocal)
bool Initialize ()
bool InitializeBlue ()
bool InitializeTCP ()
void Deinitialize ()
Private Attributes
std::vector< CTCPClient * > m_connections
std::vector< SOCKET > m_servers
int m_port
bool m_nonlocal
void * m_sdpd
Static Private Attributes
static CTCPServer * ServerInstance = NULL
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from JSONRPC::IJSONRPCAnnouncer
static std::string AnnouncementToJSONRPC (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &method, const CVariant &data, bool compactOutput)
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CTCPServer()
CTCPServer::CTCPServer (int port, bool nonlocal) private
References m_nonlocal, m_port, and m_sdpd.
Member Function Documentation
Announce()
void CTCPServer::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References JSONRPC::IJSONRPCAnnouncer::AnnouncementToJSONRPC(), data(), CServiceBroker::GetSettingsComponent(), and m_connections.
Deinitialize()
void CTCPServer::Deinitialize () private
References closesocket, CServiceBroker::GetAnnouncementManager(), m_connections, m_sdpd, and m_servers.
Referenced by Initialize(), InitializeTCP(), and Process().
Download()
bool CTCPServer::Download (const char * path, CVariant & result) override virtual
Implements JSONRPC::ITransportLayer.
GetCapabilities()
int CTCPServer::GetCapabilities () override virtual
Implements JSONRPC::ITransportLayer.
References JSONRPC::Announcing, and JSONRPC::Response.
Initialize()
bool CTCPServer::Initialize () private
References Deinitialize(), CServiceBroker::GetAnnouncementManager(), InitializeBlue(), InitializeTCP(), CLog::Log(), and LOGINFO.
Referenced by Process(), and StartServer().
InitializeBlue()
bool CTCPServer::InitializeBlue () private
References AF_BLUETOOTH, AF_BTH, BTHPROTO_RFCOMM, BTPROTO_RFCOMM, closesocket, INVALID_SOCKET, CLog::Log(), LOGERROR, LOGINFO, m_nonlocal, m_sdpd, m_servers, session, SOCKET_ERROR, KODI::PLATFORM::WINDOWS::ToW(), and WSAGetLastError.
Referenced by Initialize().
InitializeTCP()
bool CTCPServer::InitializeTCP () private
References CreateTCPServerSocket(), Deinitialize(), m_nonlocal, m_port, and m_servers.
Referenced by Initialize().
IsRunning()
bool CTCPServer::IsRunning () static
References IsRunning(), and ServerInstance.
Referenced by CNetworkServices::IsJSONRPCServerRunning(), and IsRunning().
PrepareDownload()
bool CTCPServer::PrepareDownload (const char * path, CVariant & details, std::string & protocol) override virtual
Implements JSONRPC::ITransportLayer.
Process()
void CTCPServer::Process (void) override protected virtual
Reimplemented from CThread.
References Deinitialize(), CWebSocketManager::Handle(), Initialize(), INVALID_SOCKET, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, JSONRPC::CTCPServer::CTCPClient::m_addrlen, CThread::m_bStop, JSONRPC::CTCPServer::CTCPClient::m_cliaddr, m_connections, m_servers, JSONRPC::CTCPServer::CTCPClient::m_socket, RECEIVEBUFFER, and CThread::Sleep().
StartServer()
bool CTCPServer::StartServer (int port, bool nonlocal) static
References CThread::Create(), Initialize(), ServerInstance, and StopServer().
Referenced by CNetworkServices::StartJSONRPCServer().
StopServer()
void CTCPServer::StopServer (bool bWait) static
References ServerInstance, and CThread::StopThread().
Referenced by StartServer(), and CNetworkServices::StopJSONRPCServer().
Member Data Documentation
m_connections
std::vector<CTCPClient*> JSONRPC::CTCPServer::m_connections private
Referenced by Announce(), Deinitialize(), and Process().
m_nonlocal
bool JSONRPC::CTCPServer::m_nonlocal private
Referenced by CTCPServer(), InitializeBlue(), and InitializeTCP().
m_port
int JSONRPC::CTCPServer::m_port private
Referenced by CTCPServer(), and InitializeTCP().
m_sdpd
void* JSONRPC::CTCPServer::m_sdpd private
Referenced by CTCPServer(), Deinitialize(), and InitializeBlue().
m_servers
std::vector<SOCKET> JSONRPC::CTCPServer::m_servers private
Referenced by Deinitialize(), InitializeBlue(), InitializeTCP(), and Process().
ServerInstance
CTCPServer * CTCPServer::ServerInstance = NULL static private
Referenced by IsRunning(), StartServer(), and StopServer().
The documentation for this class was generated from the following files:
TCPServer.h
TCPServer.cpp