Kodi Documentation: ADDON::CServiceAddonManager Class Reference
ADDON::CServiceAddonManager Class Reference
#include <Service.h>
Public Member Functions
CServiceAddonManager (CAddonMgr &addonMgr)
~CServiceAddonManager ()
void Start ()
void Start (const AddonPtr &addon)
void Start (const std::string &addonId)
void Stop ()
void Stop (const std::string &addonId)
Private Member Functions
void OnEvent (const AddonEvent &event)
void Stop (const std::map< std::string, int >::value_type &service)
Private Attributes
CAddonMgr & m_addonMgr
CCriticalSection m_criticalSection
std::map< std::string, int > m_services
Constructor & Destructor Documentation
CServiceAddonManager()
ADDON::CServiceAddonManager::CServiceAddonManager (CAddonMgr & addonMgr) explicit
~CServiceAddonManager()
ADDON::CServiceAddonManager::~CServiceAddonManager ()
References ADDON::CAddonMgr::Events(), m_addonMgr, and ADDON::CAddonMgr::UnloadEvents().
Member Function Documentation
OnEvent()
void ADDON::CServiceAddonManager::OnEvent (const AddonEvent & event) private
References ADDON::AddonEvent::addonId, Start(), and Stop().
Referenced by Start().
Start() [1/3]
void ADDON::CServiceAddonManager::Start ()
Start all services.
References addons, ADDON::CAddonMgr::Events(), ADDON::CAddonMgr::GetAddons(), m_addonMgr, OnEvent(), ADDON::SERVICE, Start(), and ADDON::CAddonMgr::UnloadEvents().
Referenced by CProfileManager::FinalizeLoadProfile(), CApplication::Initialize(), OnEvent(), Start(), and Start().
Start() [2/3]
void ADDON::CServiceAddonManager::Start (const AddonPtr & addon)
Start service by add-on id.
References CScriptInvocationManager::ExecuteAsync(), CScriptInvocationManager::GetInstance(), CLog::Log(), LOGDEBUG, LOGERROR, m_criticalSection, and m_services.
Start() [3/3]
void ADDON::CServiceAddonManager::Start (const std::string & addonId)
References ADDON::CHOICE_YES, ADDON::CAddonMgr::GetAddon(), m_addonMgr, ADDON::SERVICE, and Start().
Stop() [1/3]
void ADDON::CServiceAddonManager::Stop ()
Stop all services.
References ADDON::CAddonMgr::Events(), m_addonMgr, m_criticalSection, m_services, Stop(), and ADDON::CAddonMgr::UnloadEvents().
Referenced by OnEvent(), CProfileManager::PrepareLoadProfile(), Stop(), Stop(), Stop(), and CApplication::Stop().
Stop() [2/3]
void ADDON::CServiceAddonManager::Stop (const std::map< std::string, int >::value_type & service) private
References CScriptInvocationManager::GetInstance(), CLog::Log(), LOGDEBUG, LOGINFO, and Stop().
Stop() [3/3]
void ADDON::CServiceAddonManager::Stop (const std::string & addonId)
Stop service by add-on id.
References m_criticalSection, m_services, and Stop().
Member Data Documentation
m_addonMgr
CAddonMgr& ADDON::CServiceAddonManager::m_addonMgr private
Referenced by Start(), Start(), Stop(), and ~CServiceAddonManager().
m_criticalSection
CCriticalSection ADDON::CServiceAddonManager::m_criticalSection private
Referenced by Start(), Stop(), and Stop().
m_services
std::map<std::string, int> ADDON::CServiceAddonManager::m_services private
add-on id -> script id
Referenced by Start(), Stop(), and Stop().
The documentation for this class was generated from the following files:
Service.h
Service.cpp