Kodi Documentation: KODI::GAME::CPortNode Class Reference
KODI::GAME::CPortNode Class Reference
Games
Collection of nodes that can be connected to this port.
#include <PortNode.h>
Public Member Functions
CPortNode ()=default
CPortNode (const CPortNode &other)
CPortNode (CPortNode &&other)=default
CPortNode & operator= (const CPortNode &rhs)
CPortNode & operator= (CPortNode &&rhs) noexcept
~CPortNode ()
bool IsConnected () const
Connection state of the port.
void SetConnected (bool bConnected)
const CControllerNode & GetActiveController () const
The controller that is active on this port.
CControllerNode & GetActiveController ()
void SetActiveController (unsigned int controllerIndex)
bool SetActiveController (const std::string &controllerId)
PORT_TYPE GetPortType () const
The port type.
void SetPortType (PORT_TYPE type)
const std::string & GetPortID () const
The hardware or controller port ID.
void SetPortID (std::string portId)
const std::string & GetAddress () const
Address given to the node by the implementation.
void SetAddress (std::string address)
bool IsForceConnected () const
If true, prevents a disconnection option from being shown for this port.
void SetForceConnected (bool forceConnected)
const ControllerNodeVec & GetCompatibleControllers () const
Return the controller profiles that are compatible with this port.
ControllerNodeVec & GetCompatibleControllers ()
void SetCompatibleControllers (ControllerNodeVec controllers)
bool IsControllerAccepted (const std::string &controllerId) const
Check to see if a controller is compatible with this tree.
bool IsControllerAccepted (const std::string &portAddress, const std::string &controllerId) const
Check to see if a controller is compatible with this tree.
void GetInputPorts (std::vector< std::string > &inputPorts) const
Get a list of ports that accept player input.
Private Member Functions
void GetPort (CPhysicalPort &port) const
Private Attributes
bool m_bConnected = false
unsigned int m_active = 0
PORT_TYPE m_portType = PORT_TYPE::UNKNOWN
std::string m_portId
std::string m_address
bool m_forceConnected {true}
ControllerNodeVec m_controllers
Detailed Description
Collection of nodes that can be connected to this port.
Constructor & Destructor Documentation
CPortNode() [1/3]
KODI::GAME::CPortNode::CPortNode () default
CPortNode() [2/3]
KODI::GAME::CPortNode::CPortNode (const CPortNode & other) inline
CPortNode() [3/3]
KODI::GAME::CPortNode::CPortNode (CPortNode && other) default
~CPortNode()
CPortNode::~CPortNode () default
Member Function Documentation
GetActiveController() [1/2]
CControllerNode & CPortNode::GetActiveController ()
References KODI::GAME::CControllerNode::Clear(), m_active, m_bConnected, and m_controllers.
GetActiveController() [2/2]
const CControllerNode & CPortNode::GetActiveController () const
The controller that is active on this port.
Returns
The active controller, or invalid if port is disconnected
References m_active, m_bConnected, and m_controllers.
Referenced by KODI::GAME::CControllerGrid::AddController(), KODI::GAME::CGUIPortList::AddItems(), KODI::GAME::CGameClientInput::CloseJoysticks(), KODI::GAME::CGameClientInput::ConnectController(), GetInputPorts(), KODI::GAME::CGUIPortList::OnItemSelect(), and KODI::GAME::CPortManager::SerializePort().
GetAddress()
const std::string & KODI::GAME::CPortNode::GetAddress () const inline
Address given to the node by the implementation.
References m_address.
Referenced by KODI::GAME::CGUIPortList::AddItems(), KODI::GAME::CGameClientInput::CloseJoysticks(), KODI::GAME::CPortManager::ConnectController(), KODI::GAME::CGUIPortList::GetLabel(), KODI::GAME::CControllerHub::GetPortInternal(), KODI::GAME::CGUIPortList::OnControllerSelected(), and KODI::GAME::CPortManager::SerializePort().
GetCompatibleControllers() [1/2]
ControllerNodeVec & KODI::GAME::CPortNode::GetCompatibleControllers () inline
References m_controllers.
GetCompatibleControllers() [2/2]
const ControllerNodeVec & KODI::GAME::CPortNode::GetCompatibleControllers () const inline
Return the controller profiles that are compatible with this port.
Returns
The controller profiles, or empty if this port doesn't support any controller profiles
References m_controllers.
Referenced by KODI::GAME::CControllerGrid::AddController(), KODI::GAME::CPortManager::ConnectController(), KODI::GAME::CPortManager::DeserializePort(), KODI::GAME::CGUIPortList::OnItemSelect(), and KODI::GAME::CPortManager::SerializePort().
GetInputPorts()
void CPortNode::GetInputPorts (std::vector< std::string > & inputPorts) const
Get a list of ports that accept player input.
Parameters
[out] inputPorts The list of input ports
References GetActiveController(), KODI::GAME::CControllerNode::GetInputPorts(), and IsConnected().
Referenced by KODI::GAME::CControllerHub::GetInputPorts().
GetPort()
void CPortNode::GetPort (CPhysicalPort & port) const private
References m_controllers, m_portId, and node.
Referenced by KODI::GAME::CGameClientInput::ConnectController(), KODI::GAME::CGameClientInput::DisconnectController(), IsControllerAccepted(), IsControllerAccepted(), and KODI::GAME::CGUIPortList::OnItemSelect().
GetPortID()
const std::string & KODI::GAME::CPortNode::GetPortID () const inline
The hardware or controller port ID.
Returns
The port ID of the hardware port or controller port, or empty if the port is only identified by its type
References m_portId.
Referenced by KODI::GAME::CGUIPortList::GetLabel(), and KODI::GAME::CPortManager::SerializePort().
GetPortType()
PORT_TYPE KODI::GAME::CPortNode::GetPortType () const inline
The port type.
Returns
The port type, if known
References m_portType.
Referenced by KODI::GAME::CControllerGrid::AddController(), KODI::GAME::CControllerGrid::AddPorts(), and KODI::GAME::CGUIPortList::GetLabel().
IsConnected()
bool KODI::GAME::CPortNode::IsConnected () const inline
Connection state of the port.
Returns
True if a controller is connected, false otherwise
References m_bConnected.
Referenced by KODI::GAME::CControllerGrid::AddController(), KODI::GAME::CGUIPortList::AddItems(), GetInputPorts(), and KODI::GAME::CPortManager::SerializePort().
IsControllerAccepted() [1/2]
bool CPortNode::IsControllerAccepted (const std::string & controllerId) const
Check to see if a controller is compatible with this tree.
Parameters
controllerId The ID of the controller
Returns
True if the controller is compatible with the tree, false otherwise
References GetPort(), KODI::GAME::CPhysicalPort::IsCompatible(), m_controllers, and node.
Referenced by KODI::GAME::CGameClientInput::ConnectController().
IsControllerAccepted() [2/2]
bool CPortNode::IsControllerAccepted (const std::string & portAddress, const std::string & controllerId) const
Check to see if a controller is compatible with this tree.
Parameters
portAddress The port address
controllerId The ID of the controller
Returns
True if the controller is compatible with the tree, false otherwise
References GetPort(), KODI::GAME::CPhysicalPort::IsCompatible(), m_address, m_controllers, and node.
IsForceConnected()
bool KODI::GAME::CPortNode::IsForceConnected () const inline
If true, prevents a disconnection option from being shown for this port.
References m_forceConnected.
Referenced by KODI::GAME::CGUIPortList::OnItemSelect().
operator=() [1/2]
CPortNode & CPortNode::operator= (const CPortNode & rhs)
References m_active, m_address, m_bConnected, m_controllers, m_forceConnected, m_portId, and m_portType.
operator=() [2/2]
CPortNode & CPortNode::operator= (CPortNode && rhs) noexcept
References m_bConnected.
SetActiveController() [1/2]
bool CPortNode::SetActiveController (const std::string & controllerId)
References KODI::GAME::CControllerNode::GetController(), m_active, and m_controllers.
SetActiveController() [2/2]
void KODI::GAME::CPortNode::SetActiveController (unsigned int controllerIndex) inline
References m_active.
Referenced by KODI::GAME::CPortManager::ConnectController(), and KODI::GAME::CPortManager::DeserializePort().
SetAddress()
void CPortNode::SetAddress (std::string address)
References m_address.
Referenced by KODI::GAME::CGameClientTopology::GetPortNode().
SetCompatibleControllers()
void CPortNode::SetCompatibleControllers (ControllerNodeVec controllers)
References m_controllers.
Referenced by KODI::GAME::CGameClientTopology::GetPortNode().
SetConnected()
void KODI::GAME::CPortNode::SetConnected (bool bConnected) inline
References m_bConnected.
Referenced by KODI::GAME::CPortManager::ConnectController(), KODI::GAME::CPortManager::DeserializePort(), and KODI::GAME::CGameClientTopology::GetPortNode().
SetForceConnected()
void KODI::GAME::CPortNode::SetForceConnected (bool forceConnected) inline
References m_forceConnected.
Referenced by KODI::GAME::CGameClientTopology::GetPortNode().
SetPortID()
void CPortNode::SetPortID (std::string portId)
References m_portId.
Referenced by KODI::GAME::CGameClientTopology::GetPortNode().
SetPortType()
void KODI::GAME::CPortNode::SetPortType (PORT_TYPE type) inline
References m_portType.
Referenced by KODI::GAME::CGameClientTopology::GetPortNode().
Member Data Documentation
m_active
unsigned int KODI::GAME::CPortNode::m_active = 0 private
Referenced by GetActiveController(), GetActiveController(), operator=(), SetActiveController(), and SetActiveController().
m_address
std::string KODI::GAME::CPortNode::m_address private
Referenced by GetAddress(), IsControllerAccepted(), operator=(), and SetAddress().
m_bConnected
bool KODI::GAME::CPortNode::m_bConnected = false private
Referenced by GetActiveController(), GetActiveController(), IsConnected(), operator=(), operator=(), and SetConnected().
m_controllers
ControllerNodeVec KODI::GAME::CPortNode::m_controllers private
Referenced by GetActiveController(), GetActiveController(), GetCompatibleControllers(), GetCompatibleControllers(), GetPort(), IsControllerAccepted(), IsControllerAccepted(), operator=(), SetActiveController(), and SetCompatibleControllers().
m_forceConnected
bool KODI::GAME::CPortNode::m_forceConnected {true} private
Referenced by IsForceConnected(), operator=(), and SetForceConnected().
m_portId
std::string KODI::GAME::CPortNode::m_portId private
Referenced by GetPort(), GetPortID(), operator=(), and SetPortID().
m_portType
PORT_TYPE KODI::GAME::CPortNode::m_portType = PORT_TYPE::UNKNOWN private
Referenced by GetPortType(), operator=(), and SetPortType().
The documentation for this class was generated from the following files:
PortNode.h
PortNode.cpp