Kodi Documentation: PVR::CPVRChannelsPath Class Reference
PVR::CPVRChannelsPath Class Reference
#include <PVRChannelsPath.h>
Public Member Functions
CPVRChannelsPath (const std::string &strPath)
CPVRChannelsPath (bool bRadio, const std::string &strGroupName, int iGroupClientID)
CPVRChannelsPath (bool bRadio, bool bHidden, const std::string &strGroupName, int iGroupClientID)
CPVRChannelsPath (bool bRadio, const std::string &strGroupName, int iGroupClientID, const std::string &strAddonID, ADDON::AddonInstanceId instanceID, int iChannelUID)
operator std::string () const
bool operator== (const CPVRChannelsPath &right) const
bool operator!= (const CPVRChannelsPath &right) const
bool IsValid () const
bool IsEmpty () const
bool IsChannelsRoot () const
bool IsChannelGroup () const
bool IsChannel () const
bool IsHiddenChannelGroup () const
bool IsRadio () const
const std::string & GetGroupName () const
int GetGroupClientID () const
const std::string & GetAddonID () const
ADDON::AddonInstanceId GetInstanceID () const
int GetChannelUID () const
Static Public Attributes
static const std::string PATH_TV_CHANNELS = "pvr://channels/tv/"
static const std::string PATH_RADIO_CHANNELS = "pvr://channels/radio/"
Private Types
enum class Kind {
INVALID , PROTO , EMPTY , ROOT ,
GROUP , CHANNEL
}
Static Private Member Functions
static std::string TrimSlashes (const std::string &strString)
Private Attributes
Kind m_kind = Kind::INVALID
bool m_bRadio = false
std::string m_path
std::string m_groupName
int m_groupClientID {PVR_CLIENT_INVALID_UID}
std::string m_addonID
ADDON::AddonInstanceId m_instanceID {ADDON::ADDON_SINGLETON_INSTANCE_ID}
int m_iChannelUID = -1
Member Enumeration Documentation
Kind
enum class PVR::CPVRChannelsPath::Kind strong private
Enumerator
INVALID
PROTO
EMPTY
ROOT
GROUP
CHANNEL
Constructor & Destructor Documentation
CPVRChannelsPath() [1/4]
CPVRChannelsPath::CPVRChannelsPath (const std::string & strPath) explicit
References ADDON::ADDON_SINGLETON_INSTANCE_ID, CHANNEL, EMPTY, GROUP, INVALID, LOGERROR, m_addonID, m_bRadio, m_groupClientID, m_groupName, m_iChannelUID, m_instanceID, m_kind, m_path, PROTO, PVR::PVR_CLIENT_INVALID_UID, ROOT, URIUtils::SplitPath(), and TrimSlashes().
CPVRChannelsPath() [2/4]
CPVRChannelsPath::CPVRChannelsPath (bool bRadio, const std::string & strGroupName, int iGroupClientID)
References EMPTY, GROUP, m_groupClientID, m_groupName, m_kind, and m_path.
CPVRChannelsPath() [3/4]
CPVRChannelsPath::CPVRChannelsPath (bool bRadio, bool bHidden, const std::string & strGroupName, int iGroupClientID)
References EMPTY, GROUP, m_groupClientID, m_groupName, m_kind, and m_path.
CPVRChannelsPath() [4/4]
CPVRChannelsPath::CPVRChannelsPath (bool bRadio, const std::string & strGroupName, int iGroupClientID, const std::string & strAddonID, ADDON::AddonInstanceId instanceID, int iChannelUID)
References CHANNEL, m_addonID, m_groupClientID, m_groupName, m_iChannelUID, m_instanceID, m_kind, m_path, and PVR::PVR_CLIENT_INVALID_UID.
Member Function Documentation
GetAddonID()
const std::string & PVR::CPVRChannelsPath::GetAddonID () const inline
References m_addonID.
Referenced by PVR::CPVRChannelGroups::GetChannelGroupMemberByPath(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetChannelUID()
int PVR::CPVRChannelsPath::GetChannelUID () const inline
References m_iChannelUID.
Referenced by PVR::CPVRChannelGroups::GetChannelGroupMemberByPath(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetGroupClientID()
int PVR::CPVRChannelsPath::GetGroupClientID () const inline
References m_groupClientID.
Referenced by PVR::CPVRChannelGroups::GetChannelGroupMemberByPath(), anonymous_namespace{PVRGUIDirectory.cpp}::GetChannelGroupMembers(), PVR::CPVRManager::GetClient(), PVR::CPVRChannelGroup::GetClientID(), PVR::CPVRChannelGroup::SetClientID(), PVR::CPVRChannelGroup::SetGroupName(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetGroupName()
const std::string & PVR::CPVRChannelsPath::GetGroupName () const inline
References m_groupName.
Referenced by PVR::CPVRChannelGroupFactory::CreateGroup(), PVR::CPVRChannelGroups::GetChannelGroupMemberByPath(), anonymous_namespace{PVRGUIDirectory.cpp}::GetChannelGroupMembers(), PVR::CPVRChannelGroup::GroupName(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CPVRChannelGroup::SetClientID(), PVR::CPVRChannelGroup::SetGroupName(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetInstanceID()
ADDON::AddonInstanceId PVR::CPVRChannelsPath::GetInstanceID () const inline
References m_instanceID.
Referenced by PVR::CPVRChannelGroups::GetChannelGroupMemberByPath(), and TEST().
IsChannel()
bool PVR::CPVRChannelsPath::IsChannel () const inline
References CHANNEL, and m_kind.
Referenced by PVR::CPVRChannelGroups::GetChannelGroupMemberByPath(), URIUtils::IsPVRChannel(), URIUtils::IsPVRRadioChannel(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
IsChannelGroup()
bool PVR::CPVRChannelsPath::IsChannelGroup () const inline
References GROUP, and m_kind.
Referenced by PVR::CPVRGUIDirectory::GetChannelsDirectory(), PVR::CPVRChannelGroups::GetGroupByPath(), URIUtils::IsPVRChannelGroup(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
IsChannelsRoot()
bool PVR::CPVRChannelsPath::IsChannelsRoot () const inline
References m_kind, and ROOT.
Referenced by PVR::CPVRGUIDirectory::GetChannelsDirectory(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
IsEmpty()
bool PVR::CPVRChannelsPath::IsEmpty () const inline
References EMPTY, and m_kind.
Referenced by PVR::CPVRGUIDirectory::GetChannelsDirectory(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
IsHiddenChannelGroup()
bool CPVRChannelsPath::IsHiddenChannelGroup () const
References GROUP, m_groupName, and m_kind.
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetChannelGroupMembers(), PVR::CPVRGUIDirectory::GetChannelsDirectory(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
IsRadio()
bool PVR::CPVRChannelsPath::IsRadio () const inline
References m_bRadio.
Referenced by PVR::CPVRChannelGroupAllChannelsSingleClient::CreateMissingGroups(), PVR::CPVRChannelGroupMergedByName::CreateMissingGroups(), PVR::CPVRChannelGroupsContainer::GetChannelGroupMemberByPath(), anonymous_namespace{PVRGUIDirectory.cpp}::GetChannelGroupMembers(), PVR::CPVRGUIDirectory::GetChannelsDirectory(), PVR::CPVRChannelGroup::IsRadio(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CPVRChannelGroup::SetClientID(), PVR::CPVRChannelGroup::SetGroupName(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
IsValid()
bool PVR::CPVRChannelsPath::IsValid () const inline
References m_kind, and PROTO.
Referenced by PVR::CPVRChannelGroupsContainer::GetChannelGroupMemberByPath(), PVR::CPVRGUIDirectory::GetChannelsDirectory(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
operator std::string()
PVR::CPVRChannelsPath::operator std::string () const inline
References m_path.
operator!=()
bool PVR::CPVRChannelsPath::operator!= (const CPVRChannelsPath & right) const inline
References right.
operator==()
bool PVR::CPVRChannelsPath::operator== (const CPVRChannelsPath & right) const inline
References m_path, and right.
TrimSlashes()
std::string CPVRChannelsPath::TrimSlashes (const std::string & strString) static private
Referenced by CPVRChannelsPath().
Member Data Documentation
m_addonID
std::string PVR::CPVRChannelsPath::m_addonID private
Referenced by CPVRChannelsPath(), CPVRChannelsPath(), and GetAddonID().
m_bRadio
bool PVR::CPVRChannelsPath::m_bRadio = false private
Referenced by CPVRChannelsPath(), and IsRadio().
m_groupClientID
int PVR::CPVRChannelsPath::m_groupClientID {PVR_CLIENT_INVALID_UID} private
Referenced by CPVRChannelsPath(), CPVRChannelsPath(), CPVRChannelsPath(), CPVRChannelsPath(), and GetGroupClientID().
m_groupName
std::string PVR::CPVRChannelsPath::m_groupName private
Referenced by CPVRChannelsPath(), CPVRChannelsPath(), CPVRChannelsPath(), CPVRChannelsPath(), GetGroupName(), and IsHiddenChannelGroup().
m_iChannelUID
int PVR::CPVRChannelsPath::m_iChannelUID = -1 private
Referenced by CPVRChannelsPath(), CPVRChannelsPath(), and GetChannelUID().
m_instanceID
ADDON::AddonInstanceId PVR::CPVRChannelsPath::m_instanceID {ADDON::ADDON_SINGLETON_INSTANCE_ID} private
Referenced by CPVRChannelsPath(), CPVRChannelsPath(), and GetInstanceID().
m_kind
Kind PVR::CPVRChannelsPath::m_kind = Kind::INVALID private
Referenced by CPVRChannelsPath(), CPVRChannelsPath(), CPVRChannelsPath(), CPVRChannelsPath(), IsChannel(), IsChannelGroup(), IsChannelsRoot(), IsEmpty(), IsHiddenChannelGroup(), and IsValid().
m_path
std::string PVR::CPVRChannelsPath::m_path private
Referenced by CPVRChannelsPath(), CPVRChannelsPath(), CPVRChannelsPath(), CPVRChannelsPath(), operator std::string(), PVR::CPVRChannelGroup::operator==(), and operator==().
PATH_RADIO_CHANNELS
const std::string CPVRChannelsPath::PATH_RADIO_CHANNELS = "pvr://channels/radio/" static
Referenced by PVR::CPVRGUIDirectory::GetChannelsDirectory(), and anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory().
PATH_TV_CHANNELS
const std::string CPVRChannelsPath::PATH_TV_CHANNELS = "pvr://channels/tv/" static
Referenced by PVR::CPVRGUIDirectory::GetChannelsDirectory(), and anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory().
The documentation for this class was generated from the following files:
PVRChannelsPath.h
PVRChannelsPath.cpp