Kodi Documentation: CLogindUPowerSyscall Class Reference
CLogindUPowerSyscall Class Reference
#include <LogindUPowerSyscall.h>
Public Member Functions
CLogindUPowerSyscall ()
~CLogindUPowerSyscall () override
bool Powerdown () override
bool Suspend () override
bool Hibernate () override
bool Reboot () override
bool CanPowerdown () override
bool CanSuspend () override
bool CanHibernate () override
bool CanReboot () override
int BatteryLevel () override
bool PumpPowerEvents (IPowerEventsCallback *callback) override
Pump power related events back to xbmc.
Public Member Functions inherited from CAbstractPowerSyscall
int CountPowerFeatures () override
Public Member Functions inherited from IPowerSyscall
virtual ~IPowerSyscall ()=default
Static Public Member Functions
static bool HasLogind ()
Static Public Member Functions inherited from IPowerSyscall
static IPowerSyscall * CreateInstance ()
Called by power manager to create platform power system adapter.
static void RegisterPowerSyscall (CreatePowerSyscallFunc createFunc)
Private Member Functions
void UpdateBatteryLevel ()
void InhibitDelayLockSleep ()
void InhibitDelayLockShutdown ()
int InhibitDelayLock (const char *what)
void ReleaseDelayLockSleep ()
void ReleaseDelayLockShutdown ()
void ReleaseDelayLock (int lockFd, const char *what)
Static Private Member Functions
static bool LogindSetPowerState (const char *state)
static bool LogindCheckCapability (const char *capability)
Private Attributes
CDBusConnection m_connection
bool m_canPowerdown
bool m_canSuspend
bool m_canHibernate
bool m_canReboot
bool m_hasUPower
bool m_lowBattery
int m_batteryLevel
int m_delayLockSleepFd = -1
int m_delayLockShutdownFd = -1
Additional Inherited Members
Static Public Attributes inherited from IPowerSyscall
static const int MAX_COUNT_POWER_FEATURES = 4
Constructor & Destructor Documentation
CLogindUPowerSyscall()
CLogindUPowerSyscall::CLogindUPowerSyscall ()
References CDBusConnection::Connect(), CDBusConnection::Destroy(), InhibitDelayLockSleep(), CLog::Log(), CDBusError::Log(), LogindCheckCapability(), LOGINFO, m_batteryLevel, m_canHibernate, m_canPowerdown, m_canReboot, m_canSuspend, m_connection, m_hasUPower, m_lowBattery, CDBusMessage::SendSystem(), and UpdateBatteryLevel().
~CLogindUPowerSyscall()
CLogindUPowerSyscall::~CLogindUPowerSyscall () override
References ReleaseDelayLockShutdown(), and ReleaseDelayLockSleep().
Member Function Documentation
BatteryLevel()
int CLogindUPowerSyscall::BatteryLevel (void) override virtual
Implements IPowerSyscall.
References m_batteryLevel.
CanHibernate()
bool CLogindUPowerSyscall::CanHibernate (void) override virtual
Implements IPowerSyscall.
References m_canHibernate.
CanPowerdown()
bool CLogindUPowerSyscall::CanPowerdown (void) override virtual
Implements IPowerSyscall.
References m_canPowerdown.
CanReboot()
bool CLogindUPowerSyscall::CanReboot (void) override virtual
Implements IPowerSyscall.
References m_canReboot.
CanSuspend()
bool CLogindUPowerSyscall::CanSuspend (void) override virtual
Implements IPowerSyscall.
References m_canSuspend.
HasLogind()
bool CLogindUPowerSyscall::HasLogind () static
References CLog::Log(), LOGDEBUG, LOGIND_DEST, LOGIND_IFACE, LOGIND_PATH, and CDBusMessage::SendSystem().
Referenced by CLinuxPowerSyscall::CreateInstance().
Hibernate()
bool CLogindUPowerSyscall::Hibernate (void) override virtual
Implements IPowerSyscall.
References LogindSetPowerState().
InhibitDelayLock()
int CLogindUPowerSyscall::InhibitDelayLock (const char * what) private
References CDBusMessage::AppendArgument(), CLog::Log(), LOGDEBUG, LOGWARNING, and CDBusMessage::SendSystem().
Referenced by InhibitDelayLockShutdown(), and InhibitDelayLockSleep().
InhibitDelayLockShutdown()
void CLogindUPowerSyscall::InhibitDelayLockShutdown () private
References InhibitDelayLock(), and m_delayLockShutdownFd.
Referenced by Powerdown().
InhibitDelayLockSleep()
void CLogindUPowerSyscall::InhibitDelayLockSleep () private
References InhibitDelayLock(), and m_delayLockSleepFd.
Referenced by CLogindUPowerSyscall(), and PumpPowerEvents().
LogindCheckCapability()
bool CLogindUPowerSyscall::LogindCheckCapability (const char * capability) static private
References LOGIND_DEST, LOGIND_IFACE, LOGIND_PATH, and CDBusMessage::SendSystem().
Referenced by CLogindUPowerSyscall().
LogindSetPowerState()
bool CLogindUPowerSyscall::LogindSetPowerState (const char * state) static private
References CDBusMessage::AppendArgument(), LOGIND_DEST, LOGIND_IFACE, LOGIND_PATH, and CDBusMessage::SendSystem().
Referenced by Hibernate(), Powerdown(), Reboot(), and Suspend().
Powerdown()
bool CLogindUPowerSyscall::Powerdown (void) override virtual
Implements IPowerSyscall.
References InhibitDelayLockShutdown(), and LogindSetPowerState().
PumpPowerEvents()
bool CLogindUPowerSyscall::PumpPowerEvents (IPowerEventsCallback * callback) override virtual
Pump power related events back to xbmc.
PumpPowerEvents is called from Application Thread and the platform implementation may signal power related events back to xbmc through the callback.
return true if an event occurred and false if not.
Parameters
callback the callback to signal to
Implements IPowerSyscall.
References InhibitDelayLockSleep(), CLog::Log(), LOGDEBUG, m_connection, m_lowBattery, ReleaseDelayLockSleep(), and UpdateBatteryLevel().
Reboot()
bool CLogindUPowerSyscall::Reboot (void) override virtual
Implements IPowerSyscall.
References LogindSetPowerState().
ReleaseDelayLock()
void CLogindUPowerSyscall::ReleaseDelayLock (int lockFd, const char * what) private
References CLog::Log(), and LOGDEBUG.
Referenced by ReleaseDelayLockShutdown(), and ReleaseDelayLockSleep().
ReleaseDelayLockShutdown()
void CLogindUPowerSyscall::ReleaseDelayLockShutdown () private
References m_delayLockShutdownFd, and ReleaseDelayLock().
Referenced by ~CLogindUPowerSyscall().
ReleaseDelayLockSleep()
void CLogindUPowerSyscall::ReleaseDelayLockSleep () private
References m_delayLockSleepFd, and ReleaseDelayLock().
Referenced by PumpPowerEvents(), and ~CLogindUPowerSyscall().
Suspend()
bool CLogindUPowerSyscall::Suspend (void) override virtual
Implements IPowerSyscall.
References LogindSetPowerState().
UpdateBatteryLevel()
void CLogindUPowerSyscall::UpdateBatteryLevel () private
References CVariant::asBoolean(), CVariant::asDouble(), CDBusUtil::GetAll(), CDBusUtil::GetVariant(), CLog::Log(), LOGWARNING, m_batteryLevel, m_lowBattery, and CDBusMessage::SendSystem().
Referenced by CLogindUPowerSyscall(), and PumpPowerEvents().
Member Data Documentation
m_batteryLevel
int CLogindUPowerSyscall::m_batteryLevel private
Referenced by BatteryLevel(), CLogindUPowerSyscall(), and UpdateBatteryLevel().
m_canHibernate
bool CLogindUPowerSyscall::m_canHibernate private
Referenced by CanHibernate(), and CLogindUPowerSyscall().
m_canPowerdown
bool CLogindUPowerSyscall::m_canPowerdown private
Referenced by CanPowerdown(), and CLogindUPowerSyscall().
m_canReboot
bool CLogindUPowerSyscall::m_canReboot private
Referenced by CanReboot(), and CLogindUPowerSyscall().
m_canSuspend
bool CLogindUPowerSyscall::m_canSuspend private
Referenced by CanSuspend(), and CLogindUPowerSyscall().
m_connection
CDBusConnection CLogindUPowerSyscall::m_connection private
Referenced by CLogindUPowerSyscall(), and PumpPowerEvents().
m_delayLockShutdownFd
int CLogindUPowerSyscall::m_delayLockShutdownFd = -1 private
Referenced by InhibitDelayLockShutdown(), and ReleaseDelayLockShutdown().
m_delayLockSleepFd
int CLogindUPowerSyscall::m_delayLockSleepFd = -1 private
Referenced by InhibitDelayLockSleep(), and ReleaseDelayLockSleep().
m_hasUPower
bool CLogindUPowerSyscall::m_hasUPower private
Referenced by CLogindUPowerSyscall().
m_lowBattery
bool CLogindUPowerSyscall::m_lowBattery private
Referenced by CLogindUPowerSyscall(), PumpPowerEvents(), and UpdateBatteryLevel().
The documentation for this class was generated from the following files:
LogindUPowerSyscall.h
LogindUPowerSyscall.cpp