Kodi Documentation: CApplicationStackHelper Class Reference
CApplicationStackHelper Class Reference
#include <ApplicationStackHelper.h>
Classes
class StackPartInformation
Public Member Functions
CApplicationStackHelper (void)
~CApplicationStackHelper ()=default
void Clear ()
void OnPlayBackStarted (const CFileItem &item)
bool InitializeStack (const CFileItem &item)
Initialize stack.
std::optional< int64_t > InitializeStackStartPartAndOffset (const CFileItem &item)
Initialize stack times for each part, start & end, total time, and current part number if resume offset is specified.
int GetCurrentPartNumber () const
returns the current part number
bool IsPlayingISOStack () const
Returns true if Application is currently playing an ISO stack.
bool IsPlayingRegularStack () const
Returns true if Application is currently playing a Regular (non-ISO) stack.
bool HasNextStackPartFileItem () const
returns true if there is a next part available
const CFileItem & SetNextStackPartCurrentFileItem ()
sets the next stack part as the current and returns a reference to it
const CFileItem & SetStackPartCurrentFileItem (int partNumber)
sets a given stack part as the current and returns a reference to it
const CFileItem & GetCurrentStackPartFileItem () const
Returns the FileItem currently playing back as part of a (non-ISO) stack playback.
uint64_t GetStackPartEndTimeMs (int partNumber) const
Returns the end time of a FileItem part of a (non-ISO) stack playback.
uint64_t GetStackPartStartTimeMs (int partNumber) const
Returns the start time of a FileItem part of a (non-ISO) stack playback.
uint64_t GetCurrentStackPartStartTimeMs () const
Returns the start time of the current FileItem part of a (non-ISO) stack playback.
uint64_t GetStackTotalTimeMs () const
Returns the total time of a (non-ISO) stack playback.
int GetStackPartNumberAtTimeMs (uint64_t msecs)
Returns the stack part number corresponding to the given timestamp in a (non-ISO) stack playback.
void ClearAllRegisteredStackInformation ()
Clear all entries in the item-stack map. To be called upon playback stopped.
std::shared_ptr< const CFileItem > GetRegisteredStack (const CFileItem &item) const
Returns a smart pointer to the stack CFileItem.
bool HasRegisteredStack (const CFileItem &item) const
Returns true if there is a registered stack for the given CFileItem part.
void SetRegisteredStack (const CFileItem &item, std::shared_ptr< CFileItem > stackItem)
Stores a smart pointer to the stack CFileItem in the item-stack map.
int GetRegisteredStackPartNumber (const CFileItem &item)
Returns the part number of the part in the parameter.
void SetRegisteredStackPartNumber (const CFileItem &item, int partNumber)
Stores the part number in the item-stack map.
uint64_t GetRegisteredStackPartStartTimeMs (const CFileItem &item) const
Returns the start time of the part in the parameter.
void SetRegisteredStackPartStartTimeMs (const CFileItem &item, uint64_t startTimeMs)
Stores the part start time in the item-stack map.
uint64_t GetRegisteredStackTotalTimeMs (const CFileItem &item) const
Returns the total time of the stack associated to the part in the parameter.
void SetRegisteredStackTotalTimeMs (const CFileItem &item, uint64_t totalTimeMs)
Stores the stack's total time associated to the part in the item-stack map.
Public Member Functions inherited from IApplicationComponent
virtual ~IApplicationComponent ()=default
Public Attributes
CCriticalSection m_critSection
Protected Types
typedef std::shared_ptr< StackPartInformation > StackPartInformationPtr
typedef std::map< std::string, StackPartInformationPtr > Stackmap
Protected Member Functions
CFileItem & GetStackPartFileItem (int partNumber)
Returns a FileItem part of a (non-ISO) stack playback.
const CFileItem & GetStackPartFileItem (int partNumber) const
StackPartInformationPtr GetStackPartInformation (const std::string &key)
StackPartInformationPtr GetStackPartInformation (const std::string &key) const
Protected Attributes
Stackmap m_stackmap
std::unique_ptr< CFileItemList > m_currentStack
int m_currentStackPosition = 0
bool m_currentStackIsDiscImageStack = false
Member Typedef Documentation
Stackmap
typedef std::map<std::string, StackPartInformationPtr> CApplicationStackHelper::Stackmap protected
StackPartInformationPtr
typedef std::shared_ptr<StackPartInformation> CApplicationStackHelper::StackPartInformationPtr protected
Constructor & Destructor Documentation
CApplicationStackHelper()
CApplicationStackHelper::CApplicationStackHelper (void)
~CApplicationStackHelper()
CApplicationStackHelper::~CApplicationStackHelper () default
Member Function Documentation
Clear()
void CApplicationStackHelper::Clear ()
References m_currentStack, and m_currentStackPosition.
Referenced by InitializeStack().
ClearAllRegisteredStackInformation()
void CApplicationStackHelper::ClearAllRegisteredStackInformation ()
Clear all entries in the item-stack map. To be called upon playback stopped.
References m_stackmap.
GetCurrentPartNumber()
int CApplicationStackHelper::GetCurrentPartNumber () const inline
returns the current part number
References m_currentStackPosition.
GetCurrentStackPartFileItem()
const CFileItem & CApplicationStackHelper::GetCurrentStackPartFileItem () const inline
Returns the FileItem currently playing back as part of a (non-ISO) stack playback.
References GetStackPartFileItem(), and m_currentStackPosition.
GetCurrentStackPartStartTimeMs()
uint64_t CApplicationStackHelper::GetCurrentStackPartStartTimeMs () const inline
Returns the start time of the current FileItem part of a (non-ISO) stack playback.
References GetStackPartStartTimeMs(), and m_currentStackPosition.
GetRegisteredStack()
std::shared_ptr< const CFileItem > CApplicationStackHelper::GetRegisteredStack (const CFileItem & item) const
Returns a smart pointer to the stack CFileItem.
References CFileItem::GetDynPath(), and GetStackPartInformation().
Referenced by OnPlayBackStarted().
GetRegisteredStackPartNumber()
int CApplicationStackHelper::GetRegisteredStackPartNumber (const CFileItem & item)
Returns the part number of the part in the parameter.
Parameters
item the reference to the item that is part of a stack
References CFileItem::GetDynPath(), and GetStackPartInformation().
GetRegisteredStackPartStartTimeMs()
uint64_t CApplicationStackHelper::GetRegisteredStackPartStartTimeMs (const CFileItem & item) const
Returns the start time of the part in the parameter.
Parameters
item the reference to the item that is part of a stack
References CFileItem::GetDynPath(), and GetStackPartInformation().
GetRegisteredStackTotalTimeMs()
uint64_t CApplicationStackHelper::GetRegisteredStackTotalTimeMs (const CFileItem & item) const
Returns the total time of the stack associated to the part in the parameter.
Parameters
item the reference to the item that is part of a stack
References CFileItem::GetDynPath(), and GetStackPartInformation().
GetStackPartEndTimeMs()
uint64_t CApplicationStackHelper::GetStackPartEndTimeMs (int partNumber) const
Returns the end time of a FileItem part of a (non-ISO) stack playback.
Parameters
partNumber the requested part number in the stack
References CFileItem::GetEndOffset(), and GetStackPartFileItem().
Referenced by GetStackPartNumberAtTimeMs(), GetStackPartStartTimeMs(), and GetStackTotalTimeMs().
GetStackPartFileItem() [1/2]
CFileItem & CApplicationStackHelper::GetStackPartFileItem (int partNumber) protected
Returns a FileItem part of a (non-ISO) stack playback.
Parameters
partNumber the requested part number in the stack
Referenced by GetCurrentStackPartFileItem(), GetStackPartEndTimeMs(), InitializeStack(), InitializeStackStartPartAndOffset(), SetNextStackPartCurrentFileItem(), and SetStackPartCurrentFileItem().
GetStackPartFileItem() [2/2]
const CFileItem & CApplicationStackHelper::GetStackPartFileItem (int partNumber) const protected
GetStackPartInformation() [1/2]
CApplicationStackHelper::StackPartInformationPtr CApplicationStackHelper::GetStackPartInformation (const std::string & key) protected
References m_stackmap, and value.
Referenced by GetRegisteredStack(), GetRegisteredStackPartNumber(), GetRegisteredStackPartStartTimeMs(), GetRegisteredStackTotalTimeMs(), SetRegisteredStack(), SetRegisteredStackPartNumber(), SetRegisteredStackPartStartTimeMs(), and SetRegisteredStackTotalTimeMs().
GetStackPartInformation() [2/2]
CApplicationStackHelper::StackPartInformationPtr CApplicationStackHelper::GetStackPartInformation (const std::string & key) const protected
References m_stackmap.
GetStackPartNumberAtTimeMs()
int CApplicationStackHelper::GetStackPartNumberAtTimeMs (uint64_t msecs)
Returns the stack part number corresponding to the given timestamp in a (non-ISO) stack playback.
Parameters
msecs the requested timestamp in the stack (in milliseconds)
References GetStackPartEndTimeMs(), and m_currentStack.
Referenced by InitializeStackStartPartAndOffset().
GetStackPartStartTimeMs()
uint64_t CApplicationStackHelper::GetStackPartStartTimeMs (int partNumber) const inline
Returns the start time of a FileItem part of a (non-ISO) stack playback.
Parameters
partNumber the requested part number in the stack
References GetStackPartEndTimeMs().
Referenced by GetCurrentStackPartStartTimeMs(), and InitializeStackStartPartAndOffset().
GetStackTotalTimeMs()
uint64_t CApplicationStackHelper::GetStackTotalTimeMs () const
Returns the total time of a (non-ISO) stack playback.
References GetStackPartEndTimeMs(), and m_currentStack.
Referenced by InitializeStackStartPartAndOffset().
HasNextStackPartFileItem()
bool CApplicationStackHelper::HasNextStackPartFileItem () const
returns true if there is a next part available
References m_currentStack, and m_currentStackPosition.
HasRegisteredStack()
bool CApplicationStackHelper::HasRegisteredStack (const CFileItem & item) const
Returns true if there is a registered stack for the given CFileItem part.
Parameters
item the reference to the item that is part of a stack
References CFileItem::GetDynPath(), and m_stackmap.
Referenced by OnPlayBackStarted().
InitializeStack()
bool CApplicationStackHelper::InitializeStack (const CFileItem & item)
Initialize stack.
Parameters
item the FileItem object that is the stack
References Clear(), XFILE::CStackDirectory::GetDirectory(), CFileItem::GetDynPath(), GetStackPartFileItem(), URIUtils::IsDiscImageStack(), CFileItem::IsStack(), m_currentStack, m_currentStackIsDiscImageStack, SetRegisteredStack(), and SetRegisteredStackPartNumber().
InitializeStackStartPartAndOffset()
std::optional< int64_t > CApplicationStackHelper::InitializeStackStartPartAndOffset (const CFileItem & item)
Initialize stack times for each part, start & end, total time, and current part number if resume offset is specified.
Parameters
item the FileItem object that is the stack
Returns
the part offset if available, nullopt in case of errors
Todo:
If user changes the time speed (FPS via framerate conversion stuff) then these times will be wrong. Also, this is really just a hack for the slow load up times we have A much better solution is a fast reader of FPS and fileLength that we can use on a file to get it's time.
References CVariant::asString(), CDatabase::Close(), CUtil::ConvertSecsToMilliSecs(), CFileItem::GetDynPath(), CDVDFileInfo::GetFileDuration(), CGUIListItem::GetProperty(), CVideoDatabase::GetResumeBookMark(), GetStackPartFileItem(), GetStackPartNumberAtTimeMs(), GetStackPartStartTimeMs(), CVideoDatabase::GetStackTimes(), GetStackTotalTimeMs(), CFileItem::GetStartOffset(), CGUIListItem::HasProperty(), int64_t(), URIUtils::IsPlugin(), LOGERROR, LOGWARNING, m_currentStack, m_currentStackIsDiscImageStack, m_currentStackPosition, CFileItem::m_lStartPartNumber, CVideoDatabase::Open(), CBookmark::partNumber, CFileItem::SetEndOffset(), SetRegisteredStackPartStartTimeMs(), SetRegisteredStackTotalTimeMs(), CVideoDatabase::SetStackTimes(), STARTOFFSET_RESUME, and CBookmark::timeInSeconds.
IsPlayingISOStack()
bool CApplicationStackHelper::IsPlayingISOStack () const
Returns true if Application is currently playing an ISO stack.
References m_currentStack, and m_currentStackIsDiscImageStack.
Referenced by CPowerManager::StorePlayerState().
IsPlayingRegularStack()
bool CApplicationStackHelper::IsPlayingRegularStack () const
Returns true if Application is currently playing a Regular (non-ISO) stack.
References m_currentStack, and m_currentStackIsDiscImageStack.
OnPlayBackStarted()
void CApplicationStackHelper::OnPlayBackStarted (const CFileItem & item)
References GetRegisteredStack(), HasRegisteredStack(), m_critSection, and m_stackmap.
SetNextStackPartCurrentFileItem()
const CFileItem & CApplicationStackHelper::SetNextStackPartCurrentFileItem () inline
sets the next stack part as the current and returns a reference to it
References GetStackPartFileItem(), and m_currentStackPosition.
SetRegisteredStack()
void CApplicationStackHelper::SetRegisteredStack (const CFileItem & item, std::shared_ptr< CFileItem > stackItem)
Stores a smart pointer to the stack CFileItem in the item-stack map.
Parameters
item the reference to the item that is part of a stack
stackItem the smart pointer to the stack CFileItem
References CFileItem::GetDynPath(), and GetStackPartInformation().
Referenced by InitializeStack().
SetRegisteredStackPartNumber()
void CApplicationStackHelper::SetRegisteredStackPartNumber (const CFileItem & item, int partNumber)
Stores the part number in the item-stack map.
Parameters
item the reference to the item that is part of a stack
partNumber the part number of the part in other parameter
References CFileItem::GetDynPath(), and GetStackPartInformation().
Referenced by InitializeStack().
SetRegisteredStackPartStartTimeMs()
void CApplicationStackHelper::SetRegisteredStackPartStartTimeMs (const CFileItem & item, uint64_t startTimeMs)
Stores the part start time in the item-stack map.
Parameters
item the reference to the item that is part of a stack
startTime the start time of the part in other parameter
References CFileItem::GetDynPath(), and GetStackPartInformation().
Referenced by InitializeStackStartPartAndOffset().
SetRegisteredStackTotalTimeMs()
void CApplicationStackHelper::SetRegisteredStackTotalTimeMs (const CFileItem & item, uint64_t totalTimeMs)
Stores the stack's total time associated to the part in the item-stack map.
Parameters
item the reference to the item that is part of a stack
totalTime the total time of the stack
References CFileItem::GetDynPath(), and GetStackPartInformation().
Referenced by InitializeStackStartPartAndOffset().
SetStackPartCurrentFileItem()
const CFileItem & CApplicationStackHelper::SetStackPartCurrentFileItem (int partNumber) inline
sets a given stack part as the current and returns a reference to it
Parameters
partNumber the number of the part that needs to become the current one
References GetStackPartFileItem(), and m_currentStackPosition.
Member Data Documentation
m_critSection
CCriticalSection CApplicationStackHelper::m_critSection
Referenced by OnPlayBackStarted().
m_currentStack
std::unique_ptr<CFileItemList> CApplicationStackHelper::m_currentStack protected
Referenced by Clear(), GetStackPartNumberAtTimeMs(), GetStackTotalTimeMs(), HasNextStackPartFileItem(), InitializeStack(), InitializeStackStartPartAndOffset(), IsPlayingISOStack(), and IsPlayingRegularStack().
m_currentStackIsDiscImageStack
bool CApplicationStackHelper::m_currentStackIsDiscImageStack = false protected
Referenced by InitializeStack(), InitializeStackStartPartAndOffset(), IsPlayingISOStack(), and IsPlayingRegularStack().
m_currentStackPosition
int CApplicationStackHelper::m_currentStackPosition = 0 protected
Referenced by Clear(), GetCurrentPartNumber(), GetCurrentStackPartFileItem(), GetCurrentStackPartStartTimeMs(), HasNextStackPartFileItem(), InitializeStackStartPartAndOffset(), SetNextStackPartCurrentFileItem(), and SetStackPartCurrentFileItem().
m_stackmap
Stackmap CApplicationStackHelper::m_stackmap protected
Referenced by ClearAllRegisteredStackInformation(), GetStackPartInformation(), GetStackPartInformation(), HasRegisteredStack(), and OnPlayBackStarted().
The documentation for this class was generated from the following files:
ApplicationStackHelper.h
ApplicationStackHelper.cpp