Kodi Documentation: CTextureArray Class Reference
CTextureArray Class Reference
#include <TextureManager.h>
Public Member Functions
CTextureArray (int width, int height, int loops, bool texCoordsArePixels=false)
CTextureArray ()
virtual ~CTextureArray ()
void Reset ()
void Add (std::shared_ptr< CTexture > texture, int delay)
void Set (std::shared_ptr< CTexture > texture, int width, int height)
void Free ()
unsigned int size () const
Public Attributes
std::vector< std::shared_ptr< CTexture > > m_textures
std::vector< int > m_delays
int m_width
int m_height
int m_orientation
int m_loops
int m_texWidth
int m_texHeight
bool m_texCoordsArePixels
Constructor & Destructor Documentation
CTextureArray() [1/2]
CTextureArray::CTextureArray (int width, int height, int loops, bool texCoordsArePixels = false)
References m_height, m_loops, m_orientation, m_texCoordsArePixels, m_texHeight, m_texWidth, and m_width.
CTextureArray() [2/2]
CTextureArray::CTextureArray ()
References Reset().
~CTextureArray()
CTextureArray::~CTextureArray () virtual default
Member Function Documentation
Add()
void CTextureArray::Add (std::shared_ptr< CTexture > texture, int delay)
References m_delays, m_texCoordsArePixels, m_texHeight, m_textures, and m_texWidth.
Referenced by CTextureMap::Add(), and Set().
Free()
void CTextureArray::Free ()
References CServiceBroker::GetWinSystem(), and Reset().
Referenced by CTextureMap::FreeTexture().
Reset()
void CTextureArray::Reset ()
References m_delays, m_height, m_loops, m_orientation, m_texCoordsArePixels, m_texHeight, m_textures, m_texWidth, and m_width.
Referenced by CTextureArray(), Free(), and CGUITexture::FreeResources().
Set()
void CTextureArray::Set (std::shared_ptr< CTexture > texture, int width, int height)
References Add(), m_height, m_orientation, m_textures, and m_width.
size()
unsigned int CTextureArray::size () const
References m_textures.
Referenced by CGUITexture::AllocateOnDemand(), CGUITexture::AllocResources(), CGUITextureD3D::Begin(), CGUITextureGL::Begin(), CGUITextureGLES::Begin(), CGUITexture::CalculateSize(), CGUITextureD3D::Draw(), CGUITextureGL::Draw(), CGUITextureGLES::Draw(), CGUITextureGL::End(), CGUITextureGLES::End(), CGUITexture::FreeResources(), CGUILargeTextureManager::GetImage(), CGUITextureManager::Load(), CGUITexture::Process(), CGUITexture::ReadyToRender(), CGUITexture::Render(), CGUITexture::Render(), and CGUITexture::UpdateAnimFrame().
Member Data Documentation
m_delays
std::vector<int> CTextureArray::m_delays
Referenced by Add(), Reset(), and CGUITexture::UpdateAnimFrame().
m_height
int CTextureArray::m_height
Referenced by CGUITexture::AllocResources(), CGUITexture::CalculateSize(), CTextureArray(), Reset(), Set(), and CTextureMap::SetHeight().
m_loops
int CTextureArray::m_loops
Referenced by CTextureArray(), Reset(), and CGUITexture::UpdateAnimFrame().
m_orientation
int CTextureArray::m_orientation
Referenced by CTextureArray(), CGUITexture::GetOrientation(), Reset(), and Set().
m_texCoordsArePixels
bool CTextureArray::m_texCoordsArePixels
Referenced by Add(), CGUITexture::CalculateSize(), CTextureArray(), CGUITexture::Render(), and Reset().
m_texHeight
int CTextureArray::m_texHeight
Referenced by Add(), CGUITexture::CalculateSize(), CTextureArray(), and Reset().
m_textures
std::vector<std::shared_ptr<CTexture> > CTextureArray::m_textures
Referenced by Add(), CGUITextureD3D::Begin(), CGUITextureGL::Begin(), CGUITextureGLES::Begin(), CGUITextureD3D::Draw(), CTextureMap::Dump(), CTextureMap::IsEmpty(), CTextureMap::Release(), CGUITexture::Render(), Reset(), Set(), and size().
m_texWidth
int CTextureArray::m_texWidth
Referenced by Add(), CGUITexture::CalculateSize(), CTextureArray(), and Reset().
m_width
int CTextureArray::m_width
Referenced by CGUITexture::AllocResources(), CGUITexture::CalculateSize(), CTextureArray(), Reset(), Set(), and CTextureMap::SetWidth().
The documentation for this class was generated from the following files:
TextureManager.h
TextureManager.cpp