Kodi Documentation: KODI::GAME::CControllerNode Class Reference
KODI::GAME::CControllerNode Class Reference
Games
Node in the controller tree.
#include <ControllerNode.h>
Public Member Functions
CControllerNode ()
CControllerNode (const CControllerNode &other)
CControllerNode (CControllerNode &&other)=default
CControllerNode & operator= (const CControllerNode &rhs)
CControllerNode & operator= (CControllerNode &&rhs) noexcept
~CControllerNode ()
void Clear ()
const ControllerPtr & GetController () const
Controller profile of this code.
void SetController (ControllerPtr controller)
void GetControllers (ControllerVector &controllers) const
const std::string & GetPortAddress () const
Address given to the controller's port by the implementation.
void SetPortAddress (std::string portAddress)
const std::string & GetControllerAddress () const
Address given to the controller node by the implementation.
void SetControllerAddress (std::string controllerAddress)
const CControllerHub & GetHub () const
Collection of ports on this controller.
CControllerHub & GetHub ()
void SetHub (CControllerHub hub)
bool IsValid () const
Check if this node has a valid controller profile.
bool IsControllerAccepted (const std::string &controllerId) const
Check to see if a controller is compatible with a controller port.
bool IsControllerAccepted (const std::string &portAddress, const std::string &controllerId) const
Check to see if a controller is compatible with a controller port.
bool ProvidesInput () const
Check if this node provides input.
void GetInputPorts (std::vector< std::string > &activePorts) const
Get a list of ports that accept player input.
Private Attributes
ControllerPtr m_controller
std::string m_portAddress
std::string m_controllerAddress
std::unique_ptr< CControllerHub > m_hub
Detailed Description
Node in the controller tree.
The node identifies the controller profile, and optionally the available controller ports.
Constructor & Destructor Documentation
CControllerNode() [1/3]
CControllerNode::CControllerNode ()
CControllerNode() [2/3]
KODI::GAME::CControllerNode::CControllerNode (const CControllerNode & other) inline
CControllerNode() [3/3]
KODI::GAME::CControllerNode::CControllerNode (CControllerNode && other) default
~CControllerNode()
CControllerNode::~CControllerNode () default
Member Function Documentation
Clear()
void CControllerNode::Clear ()
References m_controller, m_controllerAddress, m_hub, and m_portAddress.
Referenced by KODI::GAME::CPortNode::GetActiveController().
GetController()
const ControllerPtr & KODI::GAME::CControllerNode::GetController () const inline
Controller profile of this code.
Returns
Controller profile, or empty if this node is invalid
See also
IsValid()
References m_controller.
Referenced by KODI::GAME::CControllerGrid::AddController(), KODI::GAME::CGUIPortList::AddItems(), KODI::GAME::CGUIPortList::OnItemSelect(), KODI::GAME::CPortManager::SerializeController(), KODI::GAME::CPortManager::SerializePort(), and KODI::GAME::CPortNode::SetActiveController().
GetControllerAddress()
const std::string & KODI::GAME::CControllerNode::GetControllerAddress () const inline
Address given to the controller node by the implementation.
References m_controllerAddress.
Referenced by KODI::GAME::CControllerGrid::AddController().
GetControllers()
void CControllerNode::GetControllers (ControllerVector & controllers) const
References m_controller, and m_hub.
GetHub() [1/2]
CControllerHub & KODI::GAME::CControllerNode::GetHub () inline
References m_hub.
GetHub() [2/2]
const CControllerHub & KODI::GAME::CControllerNode::GetHub () const inline
Collection of ports on this controller.
Returns
A hub with controller ports, or an empty hub if this controller has no available ports
References m_hub.
Referenced by KODI::GAME::CControllerGrid::AddController(), KODI::GAME::CGUIPortList::AddItems(), KODI::GAME::CGameClientInput::CloseJoysticks(), KODI::GAME::CPortManager::ConnectController(), KODI::GAME::CGameClientInput::ConnectController(), KODI::GAME::CPortManager::DeserializeController(), KODI::GAME::CPortManager::HasState(), and KODI::GAME::CPortManager::SerializeController().
GetInputPorts()
void CControllerNode::GetInputPorts (std::vector< std::string > & activePorts) const
Get a list of ports that accept player input.
Parameters
[out] inputPorts The list of input ports
References m_hub, m_portAddress, and ProvidesInput().
Referenced by KODI::GAME::CPortNode::GetInputPorts().
GetPortAddress()
const std::string & KODI::GAME::CControllerNode::GetPortAddress () const inline
Address given to the controller's port by the implementation.
References m_portAddress.
IsControllerAccepted() [1/2]
bool CControllerNode::IsControllerAccepted (const std::string & controllerId) const
Check to see if a controller is compatible with a controller port.
Parameters
controllerId The ID of the controller
Returns
True if the controller is compatible with a port, false otherwise
References m_hub.
IsControllerAccepted() [2/2]
bool CControllerNode::IsControllerAccepted (const std::string & portAddress, const std::string & controllerId) const
Check to see if a controller is compatible with a controller port.
Parameters
portAddress The port address
controllerId The ID of the controller
Returns
True if the controller is compatible with a port, false otherwise
References m_hub.
IsValid()
bool KODI::GAME::CControllerNode::IsValid () const inline
Check if this node has a valid controller profile.
References m_controller.
operator=() [1/2]
CControllerNode & CControllerNode::operator= (CControllerNode && rhs) noexcept
operator=() [2/2]
CControllerNode & CControllerNode::operator= (const CControllerNode & rhs)
References m_controller, m_controllerAddress, m_hub, and m_portAddress.
ProvidesInput()
bool CControllerNode::ProvidesInput () const
Check if this node provides input.
References m_controller.
Referenced by GetInputPorts().
SetController()
void CControllerNode::SetController (ControllerPtr controller)
References m_controller.
Referenced by KODI::GAME::CGameClientTopology::GetControllerNode().
SetControllerAddress()
void CControllerNode::SetControllerAddress (std::string controllerAddress)
References m_controllerAddress.
Referenced by KODI::GAME::CGameClientTopology::GetControllerNode().
SetHub()
void CControllerNode::SetHub (CControllerHub hub)
References m_hub.
Referenced by KODI::GAME::CGameClientTopology::GetControllerNode().
SetPortAddress()
void CControllerNode::SetPortAddress (std::string portAddress)
References m_portAddress.
Referenced by KODI::GAME::CGameClientTopology::GetControllerNode().
Member Data Documentation
m_controller
ControllerPtr KODI::GAME::CControllerNode::m_controller private
Referenced by Clear(), GetController(), GetControllers(), IsValid(), operator=(), ProvidesInput(), and SetController().
m_controllerAddress
std::string KODI::GAME::CControllerNode::m_controllerAddress private
Referenced by Clear(), GetControllerAddress(), operator=(), and SetControllerAddress().
m_hub
std::unique_ptr<CControllerHub> KODI::GAME::CControllerNode::m_hub private
Referenced by Clear(), GetControllers(), GetHub(), GetHub(), GetInputPorts(), IsControllerAccepted(), IsControllerAccepted(), operator=(), and SetHub().
m_portAddress
std::string KODI::GAME::CControllerNode::m_portAddress private
Referenced by Clear(), GetInputPorts(), GetPortAddress(), operator=(), and SetPortAddress().
The documentation for this class was generated from the following files:
ControllerNode.h
ControllerNode.cpp