Kodi Documentation: dbiplus::MysqlDatabase Class Reference
dbiplus::MysqlDatabase Class Reference
#include <mysqldataset.h>
Public Member Functions
MysqlDatabase ()
~MysqlDatabase () override
Dataset * CreateDataset () const override
MYSQL * getHandle ()
int status () override
int setErr (int err_code, const char *qry) override
const char * getErrorMsg () override
int connect (bool create) override
void disconnect () override
int create () override
int drop () override
bool exists () override
int copy (const char *backup_name) override
int drop_analytics (void) override
long nextid (const char *seq_name) override
void start_transaction () override
void commit_transaction () override
void rollback_transaction () override
std::string vprepare (const char *format, va_list args) override
Prepare a SQL statement for execution or querying using C printf nomenclature.
bool in_transaction () override
int query_with_reconnect (const char *query)
void configure_connection ()
Public Member Functions inherited from dbiplus::Database
Database ()
virtual ~Database ()
virtual void setHostName (const char *newHost)
const char * getHostName (void) const
void setPort (const char *newPort)
const char * getPort (void) const
virtual void setDatabase (const char *newDb)
const char * getDatabase (void) const
void setLogin (const char *newLogin)
const char * getLogin (void) const
void setPasswd (const char *newPasswd)
const char * getPasswd (void) const
virtual bool isActive (void) const
void setSequenceTable (const char *new_seq_table)
const char * getSequenceTable (void)
const char * getDefaultCharset (void)
virtual void setConfig (const char *newKey, const char *newCert, const char *newCA, const char *newCApath, const char *newCiphers, bool newCompression)
virtual int init (void)
virtual int connectFull (const char *newDb, const char *newHost=NULL, const char *newLogin=NULL, const char *newPasswd=NULL, const char *newPort=NULL, const char *newKey=NULL, const char *newCert=NULL, const char *newCA=NULL, const char *newCApath=NULL, const char *newCiphers=NULL, bool newCompression=false)
virtual int postconnect ()
virtual int reset (void)
virtual std::string prepare (const char *format,...)
Prepare a SQL statement for execution or querying using C printf nomenclature.
Protected Attributes
MYSQL * conn
bool _in_transaction
int last_err
Protected Attributes inherited from dbiplus::Database
bool active
bool compression
std::string error
std::string host
std::string port
std::string db
std::string login
std::string passwd
std::string sequence_table
std::string default_charset
std::string key
std::string cert
std::string ca
std::string capath
std::string ciphers
Private Types
typedef struct StrAccum StrAccum
Private Member Functions
char et_getdigit (double *val, int *cnt)
void appendSpace (StrAccum *pAccum, int N)
void mysqlVXPrintf (StrAccum *pAccum, int useExtended, const char *fmt, va_list ap)
bool mysqlStrAccumAppend (StrAccum *p, const char *z, int N)
char * mysqlStrAccumFinish (StrAccum *p)
void mysqlStrAccumReset (StrAccum *p)
void mysqlStrAccumInit (StrAccum *p, char *zBase, int n, int mx)
std::string mysql_vmprintf (const char *zFormat, va_list ap)
Member Typedef Documentation
StrAccum
typedef struct StrAccum dbiplus::MysqlDatabase::StrAccum private
Constructor & Destructor Documentation
MysqlDatabase()
dbiplus::MysqlDatabase::MysqlDatabase ()
References _in_transaction, dbiplus::Database::active, conn, dbiplus::Database::db, dbiplus::Database::default_charset, dbiplus::Database::error, dbiplus::Database::host, dbiplus::Database::login, dbiplus::Database::passwd, and dbiplus::Database::port.
~MysqlDatabase()
dbiplus::MysqlDatabase::~MysqlDatabase () override
References disconnect().
Member Function Documentation
appendSpace()
void dbiplus::MysqlDatabase::appendSpace (StrAccum * pAccum, int N) private
References mysqlStrAccumAppend().
Referenced by mysqlVXPrintf().
commit_transaction()
void dbiplus::MysqlDatabase::commit_transaction () override virtual
Reimplemented from dbiplus::Database.
References _in_transaction, dbiplus::Database::active, conn, LOGDATABASE, and LOGDEBUG.
configure_connection()
void dbiplus::MysqlDatabase::configure_connection ()
References conn, dbiplus::Database::db, CLog::Log(), LOGWARNING, and MYSQL_OK.
Referenced by connect().
connect()
int dbiplus::MysqlDatabase::connect (bool create) override virtual
Reimplemented from dbiplus::Database.
References dbiplus::Database::active, dbiplus::Database::ca, dbiplus::Database::capath, dbiplus::Database::cert, dbiplus::Database::ciphers, dbiplus::Database::compression, configure_connection(), conn, create(), dbiplus::Database::db, DB_CONNECTION_NONE, DB_CONNECTION_OK, dbiplus::Database::default_charset, disconnect(), ER_BAD_DB_ERROR, exists(), CWakeOnAccess::GetInstance(), GetLastError(), dbiplus::Database::host, dbiplus::Database::key, CLog::Log(), LOGDEBUG, LOGERROR, dbiplus::Database::login, LOGINFO, LOGWARNING, CDNSNameCache::Lookup(), MYSQL_OK, dbiplus::Database::passwd, dbiplus::Database::port, query_with_reconnect(), and CWakeOnAccess::WakeUpHost().
Referenced by create(), and query_with_reconnect().
copy()
int dbiplus::MysqlDatabase::copy (const char * backup_name) override virtual
Reimplemented from dbiplus::Database.
References dbiplus::Database::active, conn, dbiplus::Database::db, dbiplus::Database::host, LOGDEBUG, MYSQL_OK, and query_with_reconnect().
create()
int dbiplus::MysqlDatabase::create (void) override virtual
Reimplemented from dbiplus::Database.
References connect().
Referenced by connect().
CreateDataset()
Dataset * dbiplus::MysqlDatabase::CreateDataset () const override virtual
Implements dbiplus::Database.
disconnect()
void dbiplus::MysqlDatabase::disconnect (void) override virtual
Reimplemented from dbiplus::Database.
References dbiplus::Database::active, and conn.
Referenced by connect(), drop(), and ~MysqlDatabase().
drop()
int dbiplus::MysqlDatabase::drop (void) override virtual
Reimplemented from dbiplus::Database.
References dbiplus::Database::active, dbiplus::Database::db, DB_COMMAND_OK, disconnect(), MYSQL_OK, and query_with_reconnect().
drop_analytics()
int dbiplus::MysqlDatabase::drop_analytics (void) override virtual
Reimplemented from dbiplus::Database.
References dbiplus::Database::active, conn, dbiplus::Database::db, dbiplus::Database::host, LOGDATABASE, LOGDEBUG, MYSQL_OK, and query_with_reconnect().
et_getdigit()
char dbiplus::MysqlDatabase::et_getdigit (double * val, int * cnt) private
Referenced by mysqlVXPrintf().
exists()
bool dbiplus::MysqlDatabase::exists (void) override virtual
Reimplemented from dbiplus::Database.
References conn, dbiplus::Database::db, CLog::Log(), and LOGERROR.
Referenced by connect().
getErrorMsg()
const char * dbiplus::MysqlDatabase::getErrorMsg (void) override virtual
Reimplemented from dbiplus::Database.
References dbiplus::Database::error.
getHandle()
MYSQL * dbiplus::MysqlDatabase::getHandle () inline
References conn.
in_transaction()
bool dbiplus::MysqlDatabase::in_transaction () inline override virtual
Reimplemented from dbiplus::Database.
References _in_transaction.
mysql_vmprintf()
std::string dbiplus::MysqlDatabase::mysql_vmprintf (const char * zFormat, va_list ap) private
References MYSQL_MAX_LENGTH, MYSQL_PRINT_BUF_SIZE, mysqlStrAccumFinish(), mysqlStrAccumInit(), mysqlStrAccumReset(), and mysqlVXPrintf().
Referenced by vprepare().
mysqlStrAccumAppend()
bool dbiplus::MysqlDatabase::mysqlStrAccumAppend (StrAccum * p, const char * z, int N) private
References CLog::Log(), LOGDEBUG, and mysqlStrAccumReset().
Referenced by appendSpace(), and mysqlVXPrintf().
mysqlStrAccumFinish()
char * dbiplus::MysqlDatabase::mysqlStrAccumFinish (StrAccum * p) private
Referenced by mysql_vmprintf().
mysqlStrAccumInit()
void dbiplus::MysqlDatabase::mysqlStrAccumInit (StrAccum * p, char * zBase, int n, int mx) private
Referenced by mysql_vmprintf().
mysqlStrAccumReset()
void dbiplus::MysqlDatabase::mysqlStrAccumReset (StrAccum * p) private
Referenced by mysql_vmprintf(), and mysqlStrAccumAppend().
mysqlVXPrintf()
void dbiplus::MysqlDatabase::mysqlVXPrintf (StrAccum * pAccum, int useExtended, const char * fmt, va_list ap) private
References dbiplus::aDigits, appendSpace(), dbiplus::aPrefix, dbiplus::et_info::base, dbiplus::et_info::charset, conn, et_getdigit(), etBUFSIZE, etCHARX, etDYNSTRING, etEXP, etFLOAT, etGENERIC, etINVALID, etPERCENT, etPOINTER, etRADIX, etSIZE, etSQLESCAPE, etSQLESCAPE2, etSQLESCAPE3, etSTRING, FLAG_INTERN, FLAG_SIGNED, FLAG_STRING, dbiplus::et_info::flags, dbiplus::fmtinfo, int64_t(), mysqlStrAccumAppend(), dbiplus::et_info::prefix, and dbiplus::et_info::type.
Referenced by mysql_vmprintf().
nextid()
long dbiplus::MysqlDatabase::nextid (const char * seq_name) override virtual
Implements dbiplus::Database.
References dbiplus::Database::active, conn, DB_UNEXPECTED_RESULT, id, last_err, LOGDATABASE, LOGDEBUG, and query_with_reconnect().
query_with_reconnect()
int dbiplus::MysqlDatabase::query_with_reconnect (const char * query)
References dbiplus::Database::active, conn, connect(), CLog::Log(), LOGINFO, and MYSQL_OK.
Referenced by connect(), copy(), drop(), drop_analytics(), and nextid().
rollback_transaction()
void dbiplus::MysqlDatabase::rollback_transaction () override virtual
Reimplemented from dbiplus::Database.
References _in_transaction, dbiplus::Database::active, conn, LOGDATABASE, and LOGDEBUG.
setErr()
int dbiplus::MysqlDatabase::setErr (int err_code, const char * qry) override virtual
Implements dbiplus::Database.
References dbiplus::Database::db, err(), dbiplus::Database::error, and MYSQL_OK.
start_transaction()
void dbiplus::MysqlDatabase::start_transaction () override virtual
Reimplemented from dbiplus::Database.
References _in_transaction, dbiplus::Database::active, conn, LOGDATABASE, LOGDEBUG, and LOGERROR.
status()
int dbiplus::MysqlDatabase::status (void) override virtual
Reimplemented from dbiplus::Database.
References dbiplus::Database::active, DB_CONNECTION_NONE, and DB_CONNECTION_OK.
vprepare()
std::string dbiplus::MysqlDatabase::vprepare (const char * format, va_list args) override virtual
Prepare a SQL statement for execution or querying using C printf nomenclature.
Parameters
format - C printf compliant format string
args - va_list of variables for substitution in format string placeholders.
Returns
escaped and formatted string.
Implements dbiplus::Database.
References mysql_vmprintf().
Member Data Documentation
_in_transaction
bool dbiplus::MysqlDatabase::_in_transaction protected
Referenced by commit_transaction(), in_transaction(), MysqlDatabase(), rollback_transaction(), and start_transaction().
conn
MYSQL* dbiplus::MysqlDatabase::conn protected
Referenced by commit_transaction(), configure_connection(), connect(), copy(), disconnect(), drop_analytics(), exists(), getHandle(), MysqlDatabase(), mysqlVXPrintf(), nextid(), query_with_reconnect(), rollback_transaction(), and start_transaction().
last_err
int dbiplus::MysqlDatabase::last_err protected
Referenced by nextid().
The documentation for this class was generated from the following files:
mysqldataset.h
mysqldataset.cpp