Kodi Documentation: KODI::WINDOWING::CWindowSystemFactory Class Reference
KODI::WINDOWING::CWindowSystemFactory Class Reference
#include <WindowSystemFactory.h>
Static Public Member Functions
static std::unique_ptr< CWinSystemBase > CreateWindowSystem (const std::string &name)
static std::list< std::string > GetWindowSystems ()
static void RegisterWindowSystem (const std::function< std::unique_ptr< CWinSystemBase >()> &createFunction, const std::string &name="default")
Static Private Attributes
static std::list< std::pair< std::string, std::function< std::unique_ptr< CWinSystemBase >()> > > m_windowSystems
Member Function Documentation
CreateWindowSystem()
std::unique_ptr< CWinSystemBase > CWindowSystemFactory::CreateWindowSystem (const std::string & name) static
References m_windowSystems, and name.
Referenced by CApplication::CreateGUI().
GetWindowSystems()
std::list< std::string > CWindowSystemFactory::GetWindowSystems () static
References m_windowSystems.
Referenced by CApplication::CreateGUI().
RegisterWindowSystem()
void CWindowSystemFactory::RegisterWindowSystem (const std::function< std::unique_ptr< CWinSystemBase >()> & createFunction, const std::string & name = "default") static
References m_windowSystems, and name.
Referenced by CWinSystemAndroidGLESContext::Register(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::Register(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::Register(), CWinSystemIOS::Register(), CWinSystemOSXGL::Register(), CWinSystemTVOS::Register(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::Register(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::Register(), CWinSystemWin10DX::Register(), CWinSystemWin32DX::Register(), KODI::WINDOWING::X11::CWinSystemX11GLContext::Register(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::Register().
Member Data Documentation
m_windowSystems
std::list< std::pair< std::string, std::function< std::unique_ptr< CWinSystemBase >()> > > CWindowSystemFactory::m_windowSystems static private
Referenced by CreateWindowSystem(), GetWindowSystems(), and RegisterWindowSystem().
The documentation for this class was generated from the following files:
WindowSystemFactory.h
WindowSystemFactory.cpp