Kodi Documentation: CGUIDialogSimpleMenu Class Reference
CGUIDialogSimpleMenu Class Reference
#include <GUIDialogSimpleMenu.h>
Static Public Member Functions
static bool ShowPlaySelection (CFileItem &item, bool forceSelection=false)
Show dialog allowing selection of wanted playback item.
static bool ShowPlaySelection (CFileItem &item, const std::string &directory)
Static Protected Member Functions
static bool GetDirectoryItems (const std::string &path, CFileItemList &items, const XFILE::CDirectory::CHints &hints)
Member Function Documentation
GetDirectoryItems()
bool CGUIDialogSimpleMenu::GetDirectoryItems (const std::string & path, CFileItemList & items, const XFILE::CDirectory::CHints & hints) static protected
References CGUIDialogBusy::Wait().
Referenced by ShowPlaySelection().
ShowPlaySelection() [1/2]
bool CGUIDialogSimpleMenu::ShowPlaySelection (CFileItem & item, bool forceSelection = false) static
Show dialog allowing selection of wanted playback item.
References BD_PLAYBACK_SIMPLE_MENU, CFileUtils::Exists(), CURL::Get(), CFileItem::GetBlurayPath(), CFileItem::GetDynPath(), URIUtils::GetFileName(), URIUtils::GetParentPath(), CServiceBroker::GetSettingsComponent(), CFileItem::IsDiscImage(), URIUtils::RemoveSlashAtEnd(), root, CFileItem::SetDynPath(), CURL::SetFileName(), CURL::SetHostName(), CGUIListItem::SetProperty(), CSettings::SETTING_DISC_PLAYBACK, and ShowPlaySelection().
Referenced by CApplication::PlayFile(), and ShowPlaySelection().
ShowPlaySelection() [2/2]
bool CGUIDialogSimpleMenu::ShowPlaySelection (CFileItem & item, const std::string & directory) static
References CVariant::asString(), CFileItemList::Clear(), GetDirectoryItems(), CFileItem::GetDynPath(), CServiceBroker::GetGUI(), CGUIListItem::GetProperty(), CGUIDialogSelect::GetSelectedFileItem(), CGUIDialogSelect::GetSelectedItem(), CGUIComponent::GetWindowManager(), CGUIListItem::HasProperty(), CFileItemList::IsEmpty(), CLog::Log(), LOGDEBUG, LOGERROR, CGUIDialog::Open(), CGUIDialogSelect::Reset(), CFileItem::SetDynPath(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CGUIListItem::SetProperty(), CGUIDialogSelect::SetUseDetails(), and WINDOW_DIALOG_SELECT.
The documentation for this class was generated from the following files:
GUIDialogSimpleMenu.h
GUIDialogSimpleMenu.cpp