Kodi Documentation: TestStreamDetails.cpp File Reference
TestStreamDetails.cpp File Reference
#include "utils/StreamDetails.h"
#include <gtest/gtest.h>
Functions
TEST (TestStreamDetails, General)
TEST (TestStreamDetails, VideoDimsToResolutionDescription)
TEST (TestStreamDetails, VideoAspectToAspectDescription)
Function Documentation
TEST() [1/3]
TEST (TestStreamDetails , General)
References CStreamDetails::AddStream(), CStreamDetail::AUDIO, CStreamDetails::DetermineBestStreams(), EXPECT_EQ(), EXPECT_TRUE(), CStreamDetails::GetAudioStreamCount(), CStreamDetails::GetStereoMode(), CStreamDetails::GetStreamCount(), CStreamDetails::GetSubtitleStreamCount(), CStreamDetails::GetVideoAspect(), CStreamDetails::GetVideoCodec(), CStreamDetails::GetVideoDuration(), CStreamDetails::GetVideoHeight(), CStreamDetails::GetVideoStreamCount(), CStreamDetails::GetVideoWidth(), CStreamDetails::HasItems(), CStreamDetailVideo::m_fAspect, CStreamDetailAudio::m_iChannels, CStreamDetailVideo::m_iDuration, CStreamDetailVideo::m_iHeight, CStreamDetailVideo::m_iWidth, CStreamDetailVideo::m_strCodec, CStreamDetailAudio::m_strCodec, CStreamDetailVideo::m_strLanguage, CStreamDetailAudio::m_strLanguage, CStreamDetailSubtitle::m_strLanguage, CStreamDetailVideo::m_strStereoMode, CStreamDetail::SUBTITLE, and CStreamDetail::VIDEO.
TEST() [2/3]
TEST (TestStreamDetails , VideoAspectToAspectDescription)
References CStreamDetails::VideoAspectToAspectDescription().
TEST() [3/3]
TEST (TestStreamDetails , VideoDimsToResolutionDescription)
References CStreamDetails::VideoDimsToResolutionDescription().