Kodi Documentation: CGameSettings Class Reference
CGameSettings Class Reference
#include <GameSettings.h>
Public Member Functions
CGameSettings ()
CGameSettings (const CGameSettings &other)
CGameSettings & operator= (const CGameSettings &rhs)
void Reset ()
bool operator== (const CGameSettings &rhs) const
bool operator!= (const CGameSettings &rhs) const
const std::string & VideoFilter () const
void SetVideoFilter (const std::string &videoFilter)
KODI::RETRO::STRETCHMODE StretchMode () const
void SetStretchMode (KODI::RETRO::STRETCHMODE stretchMode)
unsigned int RotationDegCCW () const
void SetRotationDegCCW (unsigned int rotation)
Public Member Functions inherited from Observable
Observable ()=default
virtual ~Observable ()=default
Observable & operator= (const Observable &observable)
virtual void RegisterObserver (Observer *obs)
Register an observer.
virtual void UnregisterObserver (Observer *obs)
Unregister an observer.
virtual void NotifyObservers (const ObservableMessage message=ObservableMessageNone)
Send a message to all observers when m_bObservableChanged is true.
virtual void SetChanged (bool bSetTo=true)
Mark an observable changed.
virtual bool IsObserving (const Observer &obs) const
Check whether this observable is being observed by an observer.
Private Attributes
std::string m_videoFilter
KODI::RETRO::STRETCHMODE m_stretchMode
unsigned int m_rotationDegCCW
Additional Inherited Members
Protected Member Functions inherited from Observable
void SendMessage (const ObservableMessage message)
Send a message to all observer when m_bObservableChanged is true.
Protected Attributes inherited from Observable
std::atomic< bool > m_bObservableChanged {false}
std::vector< Observer * > m_observers
CCriticalSection m_obsCritSection
Constructor & Destructor Documentation
CGameSettings() [1/2]
CGameSettings::CGameSettings () inline
References Reset().
CGameSettings() [2/2]
CGameSettings::CGameSettings (const CGameSettings & other) inline
Member Function Documentation
operator!=()
bool CGameSettings::operator!= (const CGameSettings & rhs) const inline
operator=()
CGameSettings & CGameSettings::operator= (const CGameSettings & rhs)
References m_rotationDegCCW, m_stretchMode, and m_videoFilter.
operator==()
bool CGameSettings::operator== (const CGameSettings & rhs) const
References m_rotationDegCCW, m_stretchMode, and m_videoFilter.
Reset()
void CGameSettings::Reset ()
References m_rotationDegCCW, m_stretchMode, and m_videoFilter.
Referenced by CGameSettings(), and CMediaSettings::Load().
RotationDegCCW()
unsigned int CGameSettings::RotationDegCCW () const inline
References m_rotationDegCCW.
Referenced by CMediaSettings::Save(), and KODI::RETRO::CGUIGameSettings::UpdateSettings().
SetRotationDegCCW()
void CGameSettings::SetRotationDegCCW (unsigned int rotation)
References m_rotationDegCCW, and Observable::SetChanged().
Referenced by CMediaSettings::Load().
SetStretchMode()
void CGameSettings::SetStretchMode (KODI::RETRO::STRETCHMODE stretchMode)
References m_stretchMode, and Observable::SetChanged().
Referenced by CMediaSettings::Load().
SetVideoFilter()
void CGameSettings::SetVideoFilter (const std::string & videoFilter)
References m_videoFilter, and Observable::SetChanged().
Referenced by CMediaSettings::Load().
StretchMode()
KODI::RETRO::STRETCHMODE CGameSettings::StretchMode () const inline
References m_stretchMode.
Referenced by CMediaSettings::Save(), and KODI::RETRO::CGUIGameSettings::UpdateSettings().
VideoFilter()
const std::string & CGameSettings::VideoFilter () const inline
References m_videoFilter.
Referenced by CMediaSettings::Save(), and KODI::RETRO::CGUIGameSettings::UpdateSettings().
Member Data Documentation
m_rotationDegCCW
unsigned int CGameSettings::m_rotationDegCCW private
Referenced by operator=(), operator==(), Reset(), RotationDegCCW(), and SetRotationDegCCW().
m_stretchMode
KODI::RETRO::STRETCHMODE CGameSettings::m_stretchMode private
Referenced by operator=(), operator==(), Reset(), SetStretchMode(), and StretchMode().
m_videoFilter
std::string CGameSettings::m_videoFilter private
Referenced by operator=(), operator==(), Reset(), SetVideoFilter(), and VideoFilter().
The documentation for this class was generated from the following files:
settings/GameSettings.h
settings/GameSettings.cpp