Kodi Documentation: XBMCAddon::Python::PyGILLock Class Reference
XBMCAddon::Python::PyGILLock Class Reference
#include <PyContext.h>
Public Member Functions
PyGILLock ()
~PyGILLock ()
Static Public Member Functions
static void releaseGil ()
static void acquireGil ()
Detailed Description
This class supports recursive locking of the GIL. It assumes that all Python GIL manipulation is done through this class so that it can monitor the current owner.
Constructor & Destructor Documentation
PyGILLock()
XBMCAddon::Python::PyGILLock::PyGILLock () inline
References releaseGil().
~PyGILLock()
XBMCAddon::Python::PyGILLock::~PyGILLock () inline
References acquireGil().
Member Function Documentation
acquireGil()
void XBMCAddon::Python::PyGILLock::acquireGil () static
References XBMCAddon::Python::PyContextState::createdByGilRelease, XBMCAddon::Python::PyContextState::gilReleasedDepth, XBMCAddon::Python::PyContext::leaveContext(), XBMCAddon::Python::PyContextState::state, and XBMCAddon::Python::tlsPyContextState.
Referenced by XBMCAddon::Python::PythonLanguageHook::DelayedCallClose(), and ~PyGILLock().
releaseGil()
void XBMCAddon::Python::PyGILLock::releaseGil () static
References XBMCAddon::Python::PyContextState::createdByGilRelease, XBMCAddon::Python::PyContext::enterContext(), XBMCAddon::Python::PyContextState::gilReleasedDepth, XBMCAddon::Python::PyContextState::state, and XBMCAddon::Python::tlsPyContextState.
Referenced by XBMCAddon::Python::PythonLanguageHook::DelayedCallOpen(), and PyGILLock().
The documentation for this class was generated from the following files:
PyContext.h
PyContext.cpp