Kodi Documentation: TestMetadataExtraction.cpp File Reference
TestMetadataExtraction.cpp File Reference
#include "pictures/metadata/ImageMetadataParser.h"
#include "test/TestUtils.h"
#include <memory>
#include <gtest/gtest.h>
Classes
class TestMetadataExtraction
Functions
TEST_F (TestMetadataExtraction, TestGPSImage)
TEST_F (TestMetadataExtraction, TestIPTC)
Function Documentation
TEST_F() [1/2]
TEST_F (TestMetadataExtraction , TestGPSImage)
References EXPECT_EQ(), EXPECT_TRUE(), CImageMetadataParser::ExtractMetadata(), and XBMC_REF_FILE_PATH.
TEST_F() [2/2]
TEST_F (TestMetadataExtraction , TestIPTC)
References EXPECT_EQ(), EXPECT_TRUE(), CImageMetadataParser::ExtractMetadata(), and XBMC_REF_FILE_PATH.