Kodi Documentation: XBMCAddon::xbmcgui::WindowXML Class Reference
XBMCAddon::xbmcgui::WindowXML Class Reference
Python » Library - xbmcgui » Window » Subclass - WindowXML
#include <WindowXML.h>
Public Member Functions
WindowXML (const String &xmlFilename, const String &scriptPath, const String &defaultSkin="Default", const String &defaultRes="720p", bool isMedia=false)
~WindowXML () override
addItem (...)
Function: addItem(item[, position])
Add a new item to this Window List.
addItems (...)
Function: addItems(items)
Add a list of items to to the window list.
removeItem (...)
Function: removeItem(position)
Removes a specified item based on position, from the Window List.
getCurrentListPosition ()
Function: getCurrentListPosition()
Gets the current position in the Window List.
setCurrentListPosition (...)
Function: setCurrentListPosition(position)
Set the current position in the Window List.
getListItem (...)
Function: getListItem(position)
Returns a given ListItem in this Window List.
getListSize ()
Function: getListSize()
Returns the number of items in this Window List.
clearList ()
Function: clearList()
Clear the Window List.
setContainerProperty (...)
Function: setContainerProperty(key, value)
Sets a container property, similar to an infolabel.
setContent (...)
Function: setContent(value)
Sets the content type of the container.
getCurrentContainerId (...)
Function: getCurrentContainerId()
Get the id of the currently visible container.
bool OnMessage (CGUIMessage &message) override
bool OnAction (const CAction &action) override
SWIGHIDDENVIRTUAL void AllocResources (bool forceLoad=false)
SWIGHIDDENVIRTUAL void FreeResources (bool forceUnLoad=false)
SWIGHIDDENVIRTUAL bool OnClick (int iItem)
SWIGHIDDENVIRTUAL bool OnDoubleClick (int iItem)
SWIGHIDDENVIRTUAL void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions)
bool IsMediaWindow () const override
Public Member Functions inherited from XBMCAddon::xbmcgui::Window
Window (int existingWindowId=-1)
~Window () override
SWIGHIDDENVIRTUAL bool OnMessage (CGUIMessage &message)
SWIGHIDDENVIRTUAL bool OnAction (const CAction &action)
SWIGHIDDENVIRTUAL bool OnBack (int actionId)
SWIGHIDDENVIRTUAL void OnDeinitWindow (int nextWindowID)
SWIGHIDDENVIRTUAL bool IsDialogRunning () const
SWIGHIDDENVIRTUAL bool IsDialog () const
SWIGHIDDENVIRTUAL bool IsModalDialog () const
SWIGHIDDENVIRTUAL bool IsMediaWindow () const
SWIGHIDDENVIRTUAL void dispose ()
void interceptorClear ()
onAction (...)
Function: onAction(self, Action action)
onAction method.
void onControl (...)
Function: onControl(self, Control)
onControl method.
onClick (...)
Function: onClick(self, int controlId)
onClick method.
onDoubleClick (...)
Function: onDoubleClick(self, int controlId)
onDoubleClick method.
onFocus (...)
Function: onFocus(self, int controlId)
onFocus method.
onInit (...)
Function: onInit(self)
onInit method.
show ()
Function: show()
Show this window.
setFocus (...)
Function: setFocus(Control)
Give the supplied control focus.
setFocusId (...)
Function: setFocusId(ControlId)
Gives the control with the supplied focus.
getFocus ()
Function: getFocus(Control)
Returns the control which is focused.
getFocusId ()
Function: getFocusId(int)
Returns the id of the control which is focused.
removeControl (...)
Function: removeControl(Control)
Removes the control from this window.
removeControls (...)
Function: removeControls(List)
Removes a list of controls from this window.
getHeight ()
Function: getHeight()
Returns the height of this Window instance.
getWidth ()
Function: getWidth()
Returns the width of this Window instance.
setProperty (...)
Function: setProperty(key, value)
Sets a window property, similar to an infolabel.
getProperty (...)
Function: getProperty(key)
Returns a window property as a string, similar to an infolabel.
clearProperty (...)
Function: clearProperty(key)
Clears the specific window property.
clearProperties ()
Function: clearProperties()
Clears all window properties.
close ()
Function: close()
Closes this window.
doModal ()
Function: doModal()
Display this window until close() is called.
addControl (...)
Function: addControl(Control)
Add a Control to this window.
addControls (...)
Function: addControls(List)
Add a list of Controls to this window.
getControl (...)
Function: getControl(controlId)
Gets the control from this window.
Public Member Functions inherited from XBMCAddon::AddonCallback
~AddonCallback () override
void setHandler (CallbackHandler *_handler)
void invokeCallback (Callback *callback)
Public Member Functions inherited from XBMCAddon::AddonClass
AddonClass ()
virtual ~AddonClass ()
const char * GetClassname () const
LanguageHook * GetLanguageHook ()
bool isDeallocating ()
void Release () const
void Acquire () const
Protected Member Functions
SWIGHIDDENVIRTUAL bool LoadXML (const String &strPath, const String &strPathLower)
SWIGHIDDENVIRTUAL void GetContextButtons (int itemNumber, CContextButtons &buttons)
SWIGHIDDENVIRTUAL bool Update (const String &strPath)
void SetupShares ()
Protected Member Functions inherited from XBMCAddon::xbmcgui::Window
Window (bool discrim)
void deallocating () override
void setWindow (InterceptorBase *_window)
void popActiveWindowId ()
Control * GetControlById (int iControlId, CCriticalSection *gc)
SWIGHIDDENVIRTUAL void PulseActionEvent ()
SWIGHIDDENVIRTUAL bool WaitForActionEvent (unsigned int milliseconds)
Protected Member Functions inherited from XBMCAddon::AddonCallback
bool hasHandler ()
AddonCallback ()
Static Protected Member Functions
static int lockingGetNextAvailableWindowId ()
Static Protected Member Functions inherited from XBMCAddon::xbmcgui::Window
static int getNextAvailableWindowId ()
Static Protected Member Functions inherited from XBMCAddon::AddonClass
static short getNextClassIndex ()
Protected Attributes
WindowXMLInterceptor * interceptor
String m_scriptPath
String m_mediaDir
bool m_isMedia
Protected Attributes inherited from XBMCAddon::xbmcgui::Window
InterceptorBase * window
int iWindowId = -1
std::vector< AddonClass::Ref< Control > > vecControls
int iOldWindowId = 0
int iCurrentControlId = 3000
bool bModal = false
CEvent m_actionEvent
bool canPulse = false
bool existingWindow = true
bool destroyAfterDeInit = false
Protected Attributes inherited from XBMCAddon::AddonCallback
AddonClass::Ref< CallbackHandler > handler
Protected Attributes inherited from XBMCAddon::AddonClass
LanguageHook * languageHook
Private Attributes
std::string sFallBackPath
Friends
class WindowXMLInterceptor
Additional Inherited Members
Static Public Member Functions inherited from XBMCAddon::AddonClass
static short getNumAddonClasses ()
Constructor & Destructor Documentation
WindowXML()
XBMCAddon::xbmcgui::WindowXML::WindowXML (const String & xmlFilename, const String & scriptPath, const String & defaultSkin = "Default", const String & defaultRes = "720p", bool isMedia = false)
References URIUtils::AddFileToFolder(), CFileUtils::Exists(), g_SkinInfo, interceptor, lockingGetNextAvailableWindowId(), m_isMedia, m_scriptPath, XBMCAddon::xbmcgui::Window::setWindow(), ADDON::SKIN, ADDON::CSkinInfo::TranslateResolution(), WindowXMLInterceptor, and XBMC_TRACE.
~WindowXML()
XBMCAddon::xbmcgui::WindowXML::~WindowXML () override
References XBMCAddon::xbmcgui::Window::deallocating(), and XBMC_TRACE.
Member Function Documentation
AllocResources()
void XBMCAddon::xbmcgui::WindowXML::AllocResources (bool forceLoad = false)
References CGUITextureManager::AddTexturePath(), CGUIWindow::AllocResources(), URIUtils::GetDirectory(), CServiceBroker::GetGUI(), URIUtils::GetParentPath(), CGUIComponent::GetTextureManager(), m_mediaDir, URIUtils::RemoveSlashAtEnd(), CGUITextureManager::RemoveTexturePath(), XBMCAddon::xbmcgui::Window::window, and XBMC_TRACE.
FreeResources()
void XBMCAddon::xbmcgui::WindowXML::FreeResources (bool forceUnLoad = false)
References CGUIWindow::FreeResources(), XBMCAddon::xbmcgui::Window::window, and XBMC_TRACE.
GetContextButtons()
void XBMCAddon::xbmcgui::WindowXML::GetContextButtons (int itemNumber, CContextButtons & buttons) protected
References XBMC_TRACE.
Referenced by XBMCAddon::xbmcgui::WindowXMLInterceptor::GetContextButtons().
IsMediaWindow()
bool XBMCAddon::xbmcgui::WindowXML::IsMediaWindow () const inline override
References m_isMedia, and XBMC_TRACE.
LoadXML()
bool XBMCAddon::xbmcgui::WindowXML::LoadXML (const String & strPath, const String & strPathLower) protected
References A, CGUIWindow::LoadXML(), and XBMC_TRACE.
Referenced by XBMCAddon::xbmcgui::WindowXMLInterceptor::LoadXML(), and XBMCAddon::xbmcgui::WindowXMLDialog::LoadXML().
lockingGetNextAvailableWindowId()
int XBMCAddon::xbmcgui::WindowXML::lockingGetNextAvailableWindowId () static protected
This helper retrieves the next available id. It is doesn't assume that the global lock is already being held.
References XBMCAddon::xbmcgui::Window::getNextAvailableWindowId(), CServiceBroker::GetWinSystem(), and XBMC_TRACE.
Referenced by WindowXML().
OnAction()
bool XBMCAddon::xbmcgui::WindowXML::OnAction (const CAction & action) override
References XBMCAddon::AddonClass::Ref< T >::get(), XBMCAddon::AddonCallback::invokeCallback(), XBMCAddon::xbmcgui::Window::onAction(), CGUIWindow::OnAction(), XBMCAddon::xbmcgui::Window::PulseActionEvent(), XBMCAddon::xbmcgui::Window::window, and XBMC_TRACE.
Referenced by XBMCAddon::xbmcgui::WindowXMLDialog::OnAction().
OnClick()
bool XBMCAddon::xbmcgui::WindowXML::OnClick (int iItem)
References XBMC_TRACE.
OnDoubleClick()
bool XBMCAddon::xbmcgui::WindowXML::OnDoubleClick (int iItem)
References XBMC_TRACE.
OnMessage()
bool XBMCAddon::xbmcgui::WindowXML::OnMessage (CGUIMessage & message) override
Todo:
We shouldn't be dropping down to CGUIWindow in any of this ideally. We have to make up our minds about what python should be doing and what this side of things should be doing
References A, ACTION_CONTEXT_MENU, ACTION_MOUSE_DOUBLE_CLICK, ACTION_MOUSE_LEFT_CLICK, ACTION_MOUSE_RIGHT_CLICK, ACTION_SELECT_ITEM, CONTROL_BTNSORTASC, CONTROL_BTNSORTBY, XBMCAddon::AddonClass::Ref< T >::get(), CGUIMessage::GetControlId(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIMessage::GetSenderId(), GUI_MSG_CLICKED, GUI_MSG_FOCUSED, GUI_MSG_NOTIFY_ALL, GUI_MSG_PAGE_CHANGE, GUI_MSG_WINDOW_DEINIT, GUI_MSG_WINDOW_INIT, GUI_MSG_WINDOW_RESIZE, interceptor, XBMCAddon::AddonCallback::invokeCallback(), CGUIControl::IsContainer(), CLog::Log(), LOGDEBUG, LOGINFO, XBMCAddon::xbmcgui::Window::onAction(), XBMCAddon::xbmcgui::Window::onClick(), XBMCAddon::xbmcgui::Window::onDoubleClick(), XBMCAddon::xbmcgui::Window::onFocus(), XBMCAddon::xbmcgui::Window::onInit(), CGUIWindow::OnMessage(), CGUIMediaWindow::OnMessage(), XBMCAddon::xbmcgui::Window::PulseActionEvent(), XBMCAddon::xbmcgui::Window::window, and XBMC_TRACE.
Referenced by XBMCAddon::xbmcgui::WindowXMLDialog::OnMessage().
Process()
void XBMCAddon::xbmcgui::WindowXML::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions)
References CGUITextureManager::AddTexturePath(), CServiceBroker::GetGUI(), CGUIComponent::GetTextureManager(), m_mediaDir, CGUIControlGroup::Process(), CGUITextureManager::RemoveTexturePath(), XBMCAddon::xbmcgui::Window::window, and XBMC_TRACE.
SetupShares()
void XBMCAddon::xbmcgui::WindowXML::SetupShares () protected
References XBMC_TRACE.
Update()
bool XBMCAddon::xbmcgui::WindowXML::Update (const String & strPath) protected
References XBMC_TRACE.
Referenced by XBMCAddon::xbmcgui::WindowXMLInterceptor::Update().
Friends And Related Symbol Documentation
WindowXMLInterceptor
friend class WindowXMLInterceptor friend
Referenced by WindowXML().
Member Data Documentation
interceptor
WindowXMLInterceptor* XBMCAddon::xbmcgui::WindowXML::interceptor protected
Referenced by XBMCAddon::xbmcgui::WindowXMLDialog::OnDeinitWindow(), OnMessage(), and WindowXML().
m_isMedia
bool XBMCAddon::xbmcgui::WindowXML::m_isMedia protected
Referenced by IsMediaWindow(), and WindowXML().
m_mediaDir
String XBMCAddon::xbmcgui::WindowXML::m_mediaDir protected
Referenced by AllocResources(), and Process().
m_scriptPath
String XBMCAddon::xbmcgui::WindowXML::m_scriptPath protected
Referenced by WindowXML().
sFallBackPath
std::string XBMCAddon::xbmcgui::WindowXML::sFallBackPath private
The documentation for this class was generated from the following files:
WindowXML.h
WindowXML.cpp