Kodi Documentation: CONTEXTMENU::CMusicBrowse Struct Reference
CONTEXTMENU::CMusicBrowse Struct Reference
#include <ContextMenus.h>
Public Member Functions
CMusicBrowse ()
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Constructor & Destructor Documentation
CMusicBrowse()
CONTEXTMENU::CMusicBrowse::CMusicBrowse () inline
Member Function Documentation
Execute()
bool CMusicBrowse::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References EFILEFOLDER_MASK_ONBROWSE, CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE, CGUIMessage::SetStringParam(), and WINDOW_MUSIC_NAV.
IsVisible()
bool CMusicBrowse::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References EFILEFOLDER_MASK_ONBROWSE, CFileItem::IsFileFolder(), MUSIC_UTILS::IsItemPlayable(), and CGUIListItem::m_bIsFolder.
The documentation for this struct was generated from the following files:
music/ContextMenus.h
music/ContextMenus.cpp