Kodi Documentation: KODI::RETRO::CGameWindowFullScreenText Class Reference
KODI::RETRO::CGameWindowFullScreenText Class Reference
#include <GameWindowFullScreenText.h>
Public Member Functions
CGameWindowFullScreenText (CGUIWindow &fullscreenWindow)
~CGameWindowFullScreenText ()=default
void OnWindowLoaded ()
void FrameMove ()
const std::string & GetText (unsigned int lineIndex) const
Get a line of text.
void SetText (unsigned int lineIndex, std::string line)
Set a line of text.
const std::vector< std::string > & GetText () const
Get entire text.
void SetText (std::vector< std::string > text)
Set entire text.
Private Member Functions
void UploadText ()
void Show ()
void Hide ()
int GetID () const
bool OnMessage (CGUIMessage &message)
Static Private Member Functions
static int GetControlID (unsigned int lineIndex)
Translate line index to the control ID in the skin.
Private Attributes
CGUIWindow & m_fullscreenWindow
bool m_bShowText = false
bool m_bTextChanged = true
bool m_bTextVisibilityChanged = true
std::vector< std::string > m_lines
Constructor & Destructor Documentation
CGameWindowFullScreenText()
CGameWindowFullScreenText::CGameWindowFullScreenText (CGUIWindow & fullscreenWindow)
~CGameWindowFullScreenText()
KODI::RETRO::CGameWindowFullScreenText::~CGameWindowFullScreenText () default
Member Function Documentation
FrameMove()
void CGameWindowFullScreenText::FrameMove ()
References Hide(), m_bShowText, m_bTextChanged, m_bTextVisibilityChanged, Show(), and UploadText().
GetControlID()
int CGameWindowFullScreenText::GetControlID (unsigned int lineIndex) static private
Translate line index to the control ID in the skin.
Parameters
lineIndex The line in the string vector
Returns
The ID of the line's label control in the skin
References LABEL_ROW1, LABEL_ROW2, and LABEL_ROW3.
Referenced by UploadText().
GetID()
int CGameWindowFullScreenText::GetID () const private
Todo:
Change macros into functions
References CGUIControl::GetID(), and m_fullscreenWindow.
GetText() [1/2]
const std::vector< std::string > & CGameWindowFullScreenText::GetText () const
Get entire text.
References m_lines.
GetText() [2/2]
const std::string & CGameWindowFullScreenText::GetText (unsigned int lineIndex) const
Get a line of text.
References m_lines.
Hide()
void CGameWindowFullScreenText::Hide () private
References BLUE_BAR, LABEL_ROW1, LABEL_ROW2, LABEL_ROW3, and SET_CONTROL_HIDDEN.
Referenced by FrameMove().
OnMessage()
bool CGameWindowFullScreenText::OnMessage (CGUIMessage & message) private
References m_fullscreenWindow, and CGUIWindow::OnMessage().
OnWindowLoaded()
void CGameWindowFullScreenText::OnWindowLoaded ()
References m_bShowText, m_bTextChanged, m_bTextVisibilityChanged, and m_lines.
SetText() [1/2]
void CGameWindowFullScreenText::SetText (std::vector< std::string > text)
Set entire text.
References m_lines, and text.
SetText() [2/2]
void CGameWindowFullScreenText::SetText (unsigned int lineIndex, std::string line)
Set a line of text.
References m_lines.
Show()
void CGameWindowFullScreenText::Show () private
References BLUE_BAR, LABEL_ROW1, LABEL_ROW2, LABEL_ROW3, and SET_CONTROL_VISIBLE.
Referenced by FrameMove().
UploadText()
void CGameWindowFullScreenText::UploadText () private
References GetControlID(), m_lines, and SET_CONTROL_LABEL.
Referenced by FrameMove().
Member Data Documentation
m_bShowText
bool KODI::RETRO::CGameWindowFullScreenText::m_bShowText = false private
Referenced by FrameMove(), and OnWindowLoaded().
m_bTextChanged
bool KODI::RETRO::CGameWindowFullScreenText::m_bTextChanged = true private
Referenced by FrameMove(), and OnWindowLoaded().
m_bTextVisibilityChanged
bool KODI::RETRO::CGameWindowFullScreenText::m_bTextVisibilityChanged = true private
Referenced by FrameMove(), and OnWindowLoaded().
m_fullscreenWindow
CGUIWindow& KODI::RETRO::CGameWindowFullScreenText::m_fullscreenWindow private
Referenced by GetID(), and OnMessage().
m_lines
std::vector<std::string> KODI::RETRO::CGameWindowFullScreenText::m_lines private
Referenced by GetText(), GetText(), OnWindowLoaded(), SetText(), SetText(), and UploadText().
The documentation for this class was generated from the following files:
GameWindowFullScreenText.h
GameWindowFullScreenText.cpp