Kodi Documentation: AddonToKodiFuncTable_kodi_gui_listItem Struct Reference
AddonToKodiFuncTable_kodi_gui_listItem Struct Reference
#include <list_item.h>
Public Attributes
KODI_HANDLE kodiBase
KODI_HANDLE const char * label
KODI_HANDLE const char const char * label2
KODI_HANDLE const char const char const char * path
void(* destroy)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
char *(* get_label)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
void(* set_label)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *label)
char *(* get_label2)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
void(* set_label2)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *label)
char *(* get_art)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *type)
void(* set_art)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *type, const char *image)
char *(* get_path)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
void(* set_path)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *path)
char *(* get_property)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *key)
void(* set_property)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *key, const char *value)
void(* select)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, bool select)
bool(* is_selected)(KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
Member Data Documentation
destroy
void(* AddonToKodiFuncTable_kodi_gui_listItem::destroy) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
Referenced by ADDON::Interface_GUIListItem::Init().
get_art
char *(* AddonToKodiFuncTable_kodi_gui_listItem::get_art) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *type)
Referenced by ADDON::Interface_GUIListItem::Init().
get_label
char *(* AddonToKodiFuncTable_kodi_gui_listItem::get_label) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
Referenced by ADDON::Interface_GUIListItem::Init().
get_label2
char *(* AddonToKodiFuncTable_kodi_gui_listItem::get_label2) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
Referenced by ADDON::Interface_GUIListItem::Init().
get_path
char *(* AddonToKodiFuncTable_kodi_gui_listItem::get_path) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
Referenced by ADDON::Interface_GUIListItem::Init().
get_property
char *(* AddonToKodiFuncTable_kodi_gui_listItem::get_property) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *key)
Referenced by ADDON::Interface_GUIListItem::Init().
is_selected
bool(* AddonToKodiFuncTable_kodi_gui_listItem::is_selected) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
Referenced by ADDON::Interface_GUIListItem::Init().
kodiBase
KODI_HANDLE AddonToKodiFuncTable_kodi_gui_listItem::kodiBase
label
KODI_HANDLE const char* AddonToKodiFuncTable_kodi_gui_listItem::label
label2
KODI_HANDLE const char const char* AddonToKodiFuncTable_kodi_gui_listItem::label2
path
KODI_HANDLE const char const char const char* AddonToKodiFuncTable_kodi_gui_listItem::path
select
void(* AddonToKodiFuncTable_kodi_gui_listItem::select) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, bool select)
Referenced by ADDON::Interface_GUIListItem::Init().
set_art
void(* AddonToKodiFuncTable_kodi_gui_listItem::set_art) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *type, const char *image)
Referenced by ADDON::Interface_GUIListItem::Init().
set_label
void(* AddonToKodiFuncTable_kodi_gui_listItem::set_label) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *label)
Referenced by ADDON::Interface_GUIListItem::Init().
set_label2
void(* AddonToKodiFuncTable_kodi_gui_listItem::set_label2) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *label)
Referenced by ADDON::Interface_GUIListItem::Init().
set_path
void(* AddonToKodiFuncTable_kodi_gui_listItem::set_path) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *path)
Referenced by ADDON::Interface_GUIListItem::Init().
set_property
void(* AddonToKodiFuncTable_kodi_gui_listItem::set_property) (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *key, const char *value)
Referenced by ADDON::Interface_GUIListItem::Init().
The documentation for this struct was generated from the following file:
list_item.h