Kodi Documentation: KODI::RETRO::CWinRenderBuffer Class Reference
KODI::RETRO::CWinRenderBuffer Class Reference
#include <RPWinRenderer.h>
Public Member Functions
CWinRenderBuffer (AVPixelFormat pixFormat, DXGI_FORMAT dxFormat)
~CWinRenderBuffer () override
bool UploadTexture () override
CD3DTexture * GetTarget ()
Public Member Functions inherited from KODI::RETRO::CRenderBufferSysMem
CRenderBufferSysMem ()=default
~CRenderBufferSysMem () override=default
bool Allocate (AVPixelFormat format, unsigned int width, unsigned int height) override
size_t GetFrameSize () const override
uint8_t * GetMemory () override
Public Member Functions inherited from KODI::RETRO::CBaseRenderBuffer
CBaseRenderBuffer ()
~CBaseRenderBuffer () override=default
void Acquire () override
void Acquire (std::shared_ptr< IRenderBufferPool > pool) override
void Release () override
IRenderBufferPool * GetPool () override
DataAccess GetMemoryAccess () const override
DataAlignment GetMemoryAlignment () const override
Public Member Functions inherited from KODI::RETRO::IRenderBuffer
virtual ~IRenderBuffer ()=default
virtual void Update ()
virtual void ReleaseMemory ()
virtual void BindToUnit (unsigned int unit)
virtual void SetHeader (void *header)
AVPixelFormat GetFormat () const
unsigned int GetWidth () const
unsigned int GetHeight () const
bool IsLoaded () const
void SetLoaded (bool bLoaded)
bool IsRendered () const
void SetRendered (bool bRendered)
unsigned int GetRotation () const
void SetRotation (unsigned int rotationDegCCW)
Private Member Functions
bool CreateTexture ()
bool GetTexture (uint8_t *&data, unsigned int &stride)
bool ReleaseTexture ()
bool CreateScalingContext ()
void ScalePixels (const uint8_t *source, unsigned int sourceStride, uint8_t *target, unsigned int targetStride)
Static Private Member Functions
static AVPixelFormat GetPixFormat ()
Private Attributes
const AVPixelFormat m_pixFormat
const DXGI_FORMAT m_targetDxFormat
AVPixelFormat m_targetPixFormat
std::unique_ptr< CD3DTexture > m_intermediateTarget
SwsContext * m_swsContext = nullptr
Additional Inherited Members
Static Public Member Functions inherited from KODI::RETRO::CRenderBufferSysMem
static size_t GetBufferSize (AVPixelFormat format, unsigned int width, unsigned int height)
Protected Attributes inherited from KODI::RETRO::CRenderBufferSysMem
std::vector< uint8_t > m_data
Protected Attributes inherited from KODI::RETRO::CBaseRenderBuffer
std::atomic_int m_refCount
std::shared_ptr< IRenderBufferPool > m_pool
Protected Attributes inherited from KODI::RETRO::IRenderBuffer
AVPixelFormat m_format = AV_PIX_FMT_NONE
unsigned int m_width = 0
unsigned int m_height = 0
bool m_bLoaded = false
bool m_bRendered = false
unsigned int m_rotationDegCCW = 0
Constructor & Destructor Documentation
CWinRenderBuffer()
CWinRenderBuffer::CWinRenderBuffer (AVPixelFormat pixFormat, DXGI_FORMAT dxFormat)
~CWinRenderBuffer()
CWinRenderBuffer::~CWinRenderBuffer () override
References m_swsContext.
Member Function Documentation
CreateScalingContext()
bool CWinRenderBuffer::CreateScalingContext () private
References CLog::Log(), LOGERROR, KODI::RETRO::IRenderBuffer::m_height, m_pixFormat, m_swsContext, m_targetPixFormat, and KODI::RETRO::IRenderBuffer::m_width.
Referenced by UploadTexture().
CreateTexture()
bool CWinRenderBuffer::CreateTexture () private
References CLog::Log(), LOGERROR, KODI::RETRO::IRenderBuffer::m_height, m_intermediateTarget, m_targetDxFormat, and KODI::RETRO::IRenderBuffer::m_width.
Referenced by UploadTexture().
GetPixFormat()
AVPixelFormat CWinRenderBuffer::GetPixFormat () static private
GetTarget()
CD3DTexture * KODI::RETRO::CWinRenderBuffer::GetTarget () inline
References m_intermediateTarget.
GetTexture()
bool CWinRenderBuffer::GetTexture (uint8_t *& data, unsigned int & stride) private
References data(), CLog::Log(), LOGERROR, and m_intermediateTarget.
Referenced by UploadTexture().
ReleaseTexture()
bool CWinRenderBuffer::ReleaseTexture () private
References CLog::Log(), LOGERROR, and m_intermediateTarget.
Referenced by UploadTexture().
ScalePixels()
void CWinRenderBuffer::ScalePixels (const uint8_t * source, unsigned int sourceStride, uint8_t * target, unsigned int targetStride) private
References KODI::RETRO::IRenderBuffer::m_height, and m_swsContext.
Referenced by UploadTexture().
UploadTexture()
bool CWinRenderBuffer::UploadTexture () override virtual
Implements KODI::RETRO::IRenderBuffer.
References CreateScalingContext(), CreateTexture(), GetTexture(), CLog::Log(), LOGERROR, KODI::RETRO::CRenderBufferSysMem::m_data, KODI::RETRO::IRenderBuffer::m_height, m_intermediateTarget, m_targetDxFormat, ReleaseTexture(), and ScalePixels().
Member Data Documentation
m_intermediateTarget
std::unique_ptr<CD3DTexture> KODI::RETRO::CWinRenderBuffer::m_intermediateTarget private
Referenced by CreateTexture(), GetTarget(), GetTexture(), ReleaseTexture(), and UploadTexture().
m_pixFormat
const AVPixelFormat KODI::RETRO::CWinRenderBuffer::m_pixFormat private
Referenced by CreateScalingContext().
m_swsContext
SwsContext* KODI::RETRO::CWinRenderBuffer::m_swsContext = nullptr private
Referenced by CreateScalingContext(), ScalePixels(), and ~CWinRenderBuffer().
m_targetDxFormat
const DXGI_FORMAT KODI::RETRO::CWinRenderBuffer::m_targetDxFormat private
Referenced by CreateTexture(), and UploadTexture().
m_targetPixFormat
AVPixelFormat KODI::RETRO::CWinRenderBuffer::m_targetPixFormat private
Referenced by CreateScalingContext().
The documentation for this class was generated from the following files:
RPWinRenderer.h
RPWinRenderer.cpp