Kodi Documentation: IImage Class Reference
IImage Class Reference abstract
#include <iimage.h>
Public Member Functions
virtual ~IImage ()=default
virtual bool LoadImageFromMemory (unsigned char *buffer, unsigned int bufSize, unsigned int width, unsigned int height)=0
Load an image from memory with the format m_strMimeType to determine it's size and orientation.
virtual bool Decode (unsigned char *const pixels, unsigned int width, unsigned int height, unsigned int pitch, unsigned int format)=0
Decodes the previously loaded image data to the output buffer in 32 bit raw bits.
virtual bool CreateThumbnailFromSurface (unsigned char *bufferin, unsigned int width, unsigned int height, unsigned int format, unsigned int pitch, const std::string &destFile, unsigned char *&bufferout, unsigned int &bufferoutSize)=0
Encodes an thumbnail from raw bits of given memory location.
virtual void ReleaseThumbnailBuffer ()
Frees the output buffer allocated by CreateThumbnailFromSurface.
unsigned int Width () const
unsigned int Height () const
unsigned int originalWidth () const
unsigned int originalHeight () const
unsigned int Orientation () const
bool hasAlpha () const
Protected Attributes
unsigned int m_width = 0
unsigned int m_height = 0
unsigned int m_originalWidth = 0
original image width before scaling or cropping
unsigned int m_originalHeight = 0
original image height before scaling or cropping
unsigned int m_orientation = 0
bool m_hasAlpha = false
Constructor & Destructor Documentation
~IImage()
virtual IImage::~IImage () virtual default
Member Function Documentation
CreateThumbnailFromSurface()
virtual bool IImage::CreateThumbnailFromSurface (unsigned char * bufferin, unsigned int width, unsigned int height, unsigned int format, unsigned int pitch, const std::string & destFile, unsigned char *& bufferout, unsigned int & bufferoutSize) pure virtual
Encodes an thumbnail from raw bits of given memory location.
Remarks
Caller need to call ReleaseThumbnailBuffer() afterwards to free the output buffer
Parameters
bufferin The memory location where the image data can be found
width The width of the thumbnail
height The height of the thumbnail
format The format of the input buffer (JpegIO only)
pitch The pitch of the input texture stored in bufferin
destFile The destination path of the thumbnail to determine the image format from the extension
bufferout The output buffer (will be allocated inside the method)
bufferoutSize The output buffer size
Returns
true if the thumbnail was successfully created
Implemented in KODI::ADDONS::CImageDecoder, and CFFmpegImage.
Referenced by CPicture::CreateThumbnailFromSurface(), and CPicture::GetThumbnailFromSurface().
Decode()
virtual bool IImage::Decode (unsigned char *const pixels, unsigned int width, unsigned int height, unsigned int pitch, unsigned int format) pure virtual
Decodes the previously loaded image data to the output buffer in 32 bit raw bits.
Parameters
pixels The output buffer
width The width of the image
height The height of the image
pitch The pitch of the output buffer
format The format of the output buffer (JpegIO only)
Returns
true if the image data could be decoded to the output buffer
Implemented in KODI::ADDONS::CImageDecoder, and CFFmpegImage.
Referenced by CTexture::LoadIImage().
hasAlpha()
bool IImage::hasAlpha () const inline
References m_hasAlpha.
Referenced by CTexture::LoadIImage().
Height()
unsigned int IImage::Height () const inline
References m_height.
Referenced by CGUITextureManager::Load(), and CTexture::LoadIImage().
LoadImageFromMemory()
virtual bool IImage::LoadImageFromMemory (unsigned char * buffer, unsigned int bufSize, unsigned int width, unsigned int height) pure virtual
Load an image from memory with the format m_strMimeType to determine it's size and orientation.
Parameters
buffer The memory location where the image data can be found
bufSize The size of the buffer
width The ideal width of the texture
height The ideal height of the texture
Returns
true if the image could be loaded
Implemented in KODI::ADDONS::CImageDecoder, and CFFmpegImage.
Referenced by CTexture::LoadIImage().
Orientation()
unsigned int IImage::Orientation () const inline
References m_orientation.
Referenced by CTexture::LoadIImage().
originalHeight()
unsigned int IImage::originalHeight () const inline
References m_originalHeight.
Referenced by CTexture::LoadIImage().
originalWidth()
unsigned int IImage::originalWidth () const inline
References m_originalWidth.
Referenced by CTexture::LoadIImage().
ReleaseThumbnailBuffer()
virtual void IImage::ReleaseThumbnailBuffer () inline virtual
Frees the output buffer allocated by CreateThumbnailFromSurface.
Reimplemented in CFFmpegImage.
Referenced by CPicture::CreateThumbnailFromSurface(), and CPicture::GetThumbnailFromSurface().
Width()
unsigned int IImage::Width () const inline
References m_width.
Referenced by CGUITextureManager::Load(), and CTexture::LoadIImage().
Member Data Documentation
m_hasAlpha
bool IImage::m_hasAlpha = false protected
Referenced by CFFmpegImage::CFFmpegImage(), CFFmpegImage::ExtractFrame(), and hasAlpha().
m_height
unsigned int IImage::m_height = 0 protected
Referenced by KODI::ADDONS::CImageDecoder::Decode(), CFFmpegImage::Decode(), CFFmpegImage::DecodeFrame(), CFFmpegImage::ExtractFrame(), Height(), and KODI::ADDONS::CImageDecoder::LoadImageFromMemory().
m_orientation
unsigned int IImage::m_orientation = 0 protected
Referenced by CFFmpegImage::ExtractFrame(), and Orientation().
m_originalHeight
unsigned int IImage::m_originalHeight = 0 protected
original image height before scaling or cropping
Referenced by CFFmpegImage::DecodeFrame(), CFFmpegImage::ExtractFrame(), and originalHeight().
m_originalWidth
unsigned int IImage::m_originalWidth = 0 protected
original image width before scaling or cropping
Referenced by CFFmpegImage::DecodeFrame(), CFFmpegImage::ExtractFrame(), and originalWidth().
m_width
unsigned int IImage::m_width = 0 protected
Referenced by KODI::ADDONS::CImageDecoder::Decode(), CFFmpegImage::Decode(), CFFmpegImage::DecodeFrame(), CFFmpegImage::ExtractFrame(), KODI::ADDONS::CImageDecoder::LoadImageFromMemory(), and Width().
The documentation for this class was generated from the following file:
iimage.h