Kodi Documentation: CPlayerController Class Reference
CPlayerController Class Reference
Player controller class to handle user actions.
#include <PlayerController.h>
Public Member Functions
bool OnAction (const CAction &action) override
Perform a player control action if appropriate.
void OnSliderChange (void *data, CGUISliderControl *slider) override
Callback from the slider dialog.
Public Member Functions inherited from ISliderCallback
virtual ~ISliderCallback ()=default
Public Member Functions inherited from KODI::ACTION::IActionListener
virtual ~IActionListener ()=default
Static Public Member Functions
static CPlayerController & GetInstance ()
Protected Member Functions
CPlayerController ()
CPlayerController (const CPlayerController &)=delete
CPlayerController & operator= (CPlayerController const &)=delete
~CPlayerController () override
Private Member Functions
void ShowSlider (int action, int label, float value, float min, float delta, float max, bool modal=false)
pop up a slider dialog for a particular action
Private Attributes
int m_sliderAction = 0
set to the action id for a slider being displayed
KODI::UTILS::MOVING_SPEED::CMovingSpeed m_movingSpeed
Detailed Description
Player controller class to handle user actions.
Handles actions that are normally suited to fullscreen playback, such as altering subtitles and audio tracks, changing aspect ratio, subtitle placement, and placement of the video on screen.
Constructor & Destructor Documentation
CPlayerController() [1/2]
CPlayerController::CPlayerController () protected
References ACTION_SUBTITLE_VSHIFT_DOWN, ACTION_SUBTITLE_VSHIFT_UP, KODI::UTILS::MOVING_SPEED::CMovingSpeed::AddEventConfig(), and m_movingSpeed.
CPlayerController() [2/2]
CPlayerController::CPlayerController (const CPlayerController &) protected delete
~CPlayerController()
CPlayerController::~CPlayerController () override protected default
Member Function Documentation
GetInstance()
CPlayerController & CPlayerController::GetInstance () static
Referenced by CApplication::Initialize(), CApplication::Stop(), SubtitleShiftDown(), and SubtitleShiftUp().
OnAction()
bool CPlayerController::OnAction (const CAction & action) override virtual
Perform a player control action if appropriate.
Parameters
action the action to perform.
Returns
true if the action is considered handled, false if it should be handled elsewhere.
Implements KODI::ACTION::IActionListener.
References ACTION_AUDIO_DELAY, ACTION_AUDIO_DELAY_MIN, ACTION_AUDIO_DELAY_PLUS, ACTION_AUDIO_NEXT_LANGUAGE, ACTION_CYCLE_SUBTITLE, ACTION_DECREASE_PAR, ACTION_DIALOG_SELECT_AUDIO, ACTION_DIALOG_SELECT_SUBTITLE, ACTION_DIALOG_SELECT_VIDEO, ACTION_INCREASE_PAR, ACTION_NEXT_SUBTITLE, ACTION_PLAYER_PROGRAM_SELECT, ACTION_PLAYER_RESOLUTION_SELECT, ACTION_SHOW_SUBTITLES, ACTION_SUBTITLE_ALIGN, ACTION_SUBTITLE_DELAY, ACTION_SUBTITLE_DELAY_MIN, ACTION_SUBTITLE_DELAY_PLUS, ACTION_SUBTITLE_VSHIFT_DOWN, ACTION_SUBTITLE_VSHIFT_UP, ACTION_VIDEO_NEXT_STREAM, ACTION_VOLAMP, ACTION_VOLAMP_DOWN, ACTION_VOLAMP_UP, ACTION_VSHIFT_DOWN, ACTION_VSHIFT_UP, ACTION_ZOOM_IN, ACTION_ZOOM_OUT, CGUIDialogSelect::Add(), AUDIO_DELAY_STEP, OVERSCAN::bottom, CURRENT_STREAM, g_LangCodeExpander, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAppComponents(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResFromString(), CGraphicContext::GetResInfo(), CGUIDialogSelect::GetSelectedItem(), CServiceBroker::GetSettingsComponent(), KODI::UTILS::MOVING_SPEED::CMovingSpeed::GetUpdatedDistance(), CGraphicContext::GetVideoResolution(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iHeight, CGUIDialogKaiToast::Info, CLangCodeExpander::Lookup(), CVideoSettings::m_AudioDelay, CVideoSettings::m_CustomNonLinStretch, CVideoSettings::m_CustomPixelRatio, CVideoSettings::m_CustomVerticalShift, CVideoSettings::m_CustomZoomAmount, m_movingSpeed, CVideoSettings::m_SubtitleDelay, CVideoSettings::m_subtitleVerticalPosition, CVideoSettings::m_ViewMode, CVideoSettings::m_VolumeAmplification, CGUIDialog::Open(), KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream(), RESOLUTION_INFO::Overscan, CGUIDialogKaiToast::QueueNotification(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetSelected(), CSettings::SETTING_VIDEOSCREEN_WHITELIST, CGraphicContext::SetVideoResolution(), ShowSlider(), TOAST_DISPLAY_TIME, OVERSCAN::top, ViewModeCustom, VOLUME_DRC_MAXIMUM, VOLUME_DRC_MINIMUM, CGUIDialogKaiToast::Warning, and WINDOW_DIALOG_SELECT.
Referenced by SubtitleShiftDown(), and SubtitleShiftUp().
OnSliderChange()
void CPlayerController::OnSliderChange (void * data, CGUISliderControl * slider) override virtual
Callback from the slider dialog.
See also
CGUIDialogSlider
Implements ISliderCallback.
References ACTION_AUDIO_DELAY, ACTION_DECREASE_PAR, ACTION_INCREASE_PAR, ACTION_SUBTITLE_DELAY, ACTION_SUBTITLE_VSHIFT_DOWN, ACTION_SUBTITLE_VSHIFT_UP, ACTION_VOLAMP, ACTION_VOLAMP_DOWN, ACTION_VOLAMP_UP, ACTION_VSHIFT_DOWN, ACTION_VSHIFT_UP, ACTION_ZOOM_IN, ACTION_ZOOM_OUT, AUDIO_DELAY_STEP, CGUIDialogAudioSettings::FormatDecibel(), CGUIDialogAudioSettings::FormatDelay(), CServiceBroker::GetAppComponents(), CGUISliderControl::GetFloatValue(), m_sliderAction, CApplicationPlayer::SetAVDelay(), and CGUISliderControl::SetTextValue().
operator=()
CPlayerController & CPlayerController::operator= (CPlayerController const &) protected delete
ShowSlider()
void CPlayerController::ShowSlider (int action, int label, float value, float min, float delta, float max, bool modal = false) private
pop up a slider dialog for a particular action
Parameters
action id of the action the slider responds to
label id of the label to display
value value to set on the slider
min minimum value the slider may take
delta change value to advance the slider by with each click
max maximal value the slider may take
modal true if we should wait for the slider to finish. Defaults to false
References CGUIDialogSlider::Display(), g_localizeStrings, CLocalizeStrings::Get(), label, m_sliderAction, max, min, CGUIDialogSlider::ShowAndGetInput(), and value.
Referenced by OnAction().
Member Data Documentation
m_movingSpeed
KODI::UTILS::MOVING_SPEED::CMovingSpeed CPlayerController::m_movingSpeed private
Referenced by CPlayerController(), and OnAction().
m_sliderAction
int CPlayerController::m_sliderAction = 0 private
set to the action id for a slider being displayed
See also
ShowSlider
Referenced by OnSliderChange(), and ShowSlider().
The documentation for this class was generated from the following files:
PlayerController.h
PlayerController.cpp