Kodi Documentation: IMAGE_FILES Namespace Reference
IMAGE_FILES Namespace Reference
Classes
class CImageCacheCleaner
Clean old unused images from the image cache.
class CImageFileURL
A mostly-typed representation of a URL to any image, whether a simple path to an image file, embedded in another file, or generated in some way.
struct CleanerResult
class CSpecialImageLoaderFactory
class ISpecialImageFileLoader
An interface to load special image files into a texture for display.
Functions
std::string URLFromFile (const std::string &filePath, std::string specialType="")
Build an ImageFileURL string from a file path.
std::string ToCacheKey (const std::string &imageFileURL)
Build a cache key for an ImageFileURL string.
Function Documentation
ToCacheKey()
std::string IMAGE_FILES::ToCacheKey (const std::string & imageFileURL)
Build a cache key for an ImageFileURL string.
References IMAGE_FILES::CImageFileURL::ToCacheKey().
Referenced by jni::CJNIXBMCTextureCache::_unwrapImageURL(), CTextureCache::BackgroundCacheImage(), CTextureCache::CacheImage(), CTextureCache::ClearCachedImage(), CTextureRule::FormatParameter(), CTextureCache::GetCachedImage(), UPNP::CUPnPServer::ServeFile(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetArtistDetails(), JSONRPC::CAudioLibrary::SetSongDetails(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
URLFromFile()
std::string IMAGE_FILES::URLFromFile (const std::string & filePath, std::string specialType = "")
Build an ImageFileURL string from a file path.
Provide a 'specialType' parameter to specify a special image loader.
Parameters
specialType set a special image type - an implementation of ISpecialImageFileLoader
References IMAGE_FILES::CImageFileURL::FromFile(), and IMAGE_FILES::CImageFileURL::ToString().
Referenced by UPNP::BuildObject(), PVR::CPVRThumbLoader::CreateChannelGroupThumb(), KODI::VIDEO::TAGS::CVideoTagExtractionHelper::ExtractEmbeddedArtFor(), JSONRPC::CAddonsOperations::FillDetails(), CVideoThumbLoader::FillThumb(), MUSIC_INFO::CMusicInfoScanner::FindArtForAlbums(), JSONRPC::CAudioLibrary::GetAlbums(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), JSONRPC::CAudioLibrary::GetAvailableArt(), JSONRPC::CVideoLibrary::GetAvailableArt(), XFILE::CAudioBookFileDirectory::GetDirectory(), CVideoThumbLoader::GetEmbeddedThumbURL(), JSONRPC::CFileItemHandler::GetField(), UPNP::CUPnPRenderer::GetMetadata(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::GetRemoteArt(), JSONRPC::CAudioLibrary::GetSongs(), JSONRPC::CTextureOperations::GetTextures(), CPictureThumbLoader::LoadItemCached(), CMusicThumbLoader::LoadItemLookup(), CVideoThumbLoader::LoadItemLookup(), CPictureThumbLoader::ProcessFoldersAndArchives(), CGUIWindowSlideShow::RunSlideShow(), CVideoInfoTag::Serialize(), anonymous_namespace{TestImageFileURL.cpp}::TEST_P(), and PVR::CPVRCachedImage::UpdateLocalImage().