Kodi Documentation: CGUIImage Class Reference
CGUIImage Class Reference
Guilib classes » Window Reference » Controls
#include <GUIImage.h>
Classes
class CFadingTexture
Public Member Functions
CGUIImage (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo &texture)
CGUIImage (const CGUIImage &left)
~CGUIImage (void) override
CGUIImage * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void UpdateVisibility (const CGUIListItem *item=NULL) override
bool OnAction (const CAction &action) override
bool OnMessage (CGUIMessage &message) override
void AllocResources () override
void FreeResources (bool immediately=false) override
void DynamicResourceAlloc (bool bOnOff) override
bool IsDynamicallyAllocated () override
void SetInvalid () override
bool CanFocus () const override
void UpdateInfo (const CGUIListItem *item=NULL) override
virtual void SetInfo (const KODI::GUILIB::GUIINFO::CGUIInfoLabel &info)
virtual void SetFileName (const std::string &strFileName, bool setConstant=false, const bool useCache=true)
virtual void SetAspectRatio (const CAspectRatio &aspect)
void SetWidth (float width) override
void SetHeight (float height) override
void SetPosition (float posX, float posY) override
std::string GetDescription () const override
void SetCrossFade (unsigned int time)
const std::string & GetFileName () const
float GetTextureWidth () const
float GetTextureHeight () const
CRect CalcRenderRegion () const override
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
Perform a mouse action.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
virtual void AllocateOnDemand ()
virtual void FreeTextures (bool immediately=false)
void FreeResourcesButNotAnims ()
unsigned char GetFadeLevel (unsigned int time) const
std::string GetFallback (const std::string &currentName)
void ProcessState ()
void ProcessAllocation ()
void ProcessNoTransition (unsigned int currentTime)
void ProcessInstantTransition (unsigned int currentTime)
void ProcessFadingTransition (unsigned int currentTime)
void UpdateDiffuseColor (const CGUIListItem *item)
Update the diffuse color based on the current item infos.
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
bool m_bDynamicResourceAlloc
CTextureInfo m_image
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_info
bool m_isTransitioning {false}
bool m_hasNewStagingTexture {false}
std::unique_ptr< CGUITexture > m_textureCurrent
std::unique_ptr< CGUITexture > m_textureNext
std::string m_nameCurrent {}
std::string m_nameNext {}
std::string m_nameStaging {}
std::string m_currentFallback
unsigned int m_crossFadeTime
unsigned int m_currentFadeTime
unsigned int m_lastRenderTime
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIImage() [1/2]
CGUIImage::CGUIImage (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo & texture)
References CGUIControl::ControlType, CGUIControl::GUICONTROL_IMAGE, m_bDynamicResourceAlloc, m_crossFadeTime, m_currentFadeTime, m_lastRenderTime, and m_textureNext.
CGUIImage() [2/2]
CGUIImage::CGUIImage (const CGUIImage & left)
References CGUIControl::ControlType, CGUIControl::GUICONTROL_IMAGE, left, m_bDynamicResourceAlloc, m_crossFadeTime, m_currentFadeTime, and m_lastRenderTime.
~CGUIImage()
CGUIImage::~CGUIImage (void) override default
Member Function Documentation
AllocateOnDemand()
void CGUIImage::AllocateOnDemand () protected virtual
References AllocResources(), CGUIControl::DELAYED, FreeResourcesButNotAnims(), CGUIControl::IsVisible(), m_bDynamicResourceAlloc, m_textureCurrent, and CGUIControl::m_visible.
Referenced by UpdateVisibility().
AllocResources()
void CGUIImage::AllocResources () override virtual
Reimplemented from CGUIControl.
References CGUIControl::AllocResources(), and m_textureCurrent.
Referenced by AllocateOnDemand(), CGUIBorderedImage::AllocResources(), and KODI::GAME::CGUIFeatureSeparator::CGUIFeatureSeparator().
CalcRenderRegion()
CRect CGUIImage::CalcRenderRegion () const override virtual
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
Reimplemented from CGUIControl.
References CGUIControl::CalcRenderRegion(), CRectGen< T >::Intersect(), m_isTransitioning, m_textureCurrent, m_textureNext, and CRectGen< T >::Union().
Referenced by CGUIBorderedImage::CalcRenderRegion().
CanFocus()
bool CGUIImage::CanFocus () const override virtual
Reimplemented from CGUIControl.
Clone()
CGUIImage * CGUIImage::Clone (void) const inline override virtual
Implements CGUIControl.
DynamicResourceAlloc()
void CGUIImage::DynamicResourceAlloc (bool bOnOff) override virtual
Reimplemented from CGUIControl.
References CGUIControl::DynamicResourceAlloc(), m_bDynamicResourceAlloc, m_textureCurrent, and m_textureNext.
Referenced by CGUIBorderedImage::DynamicResourceAlloc().
FreeResources()
void CGUIImage::FreeResources (bool immediately = false) override virtual
Reimplemented from CGUIControl.
References CGUIControl::FreeResources(), and FreeTextures().
Referenced by CGUIBorderedImage::FreeResources(), CGUIMultiImage::FreeResources(), and CGUIDialogVideoInfo::Update().
FreeResourcesButNotAnims()
void CGUIImage::FreeResourcesButNotAnims () protected
References FreeTextures(), CGUIControl::m_bAllocated, and CGUIControl::m_hasProcessed.
Referenced by AllocateOnDemand().
FreeTextures()
void CGUIImage::FreeTextures (bool immediately = false) protected virtual
References KODI::GUILIB::GUIINFO::CGUIInfoLabel::IsConstant(), m_currentFadeTime, m_info, m_isTransitioning, m_lastRenderTime, m_nameCurrent, m_nameNext, m_textureCurrent, and m_textureNext.
Referenced by FreeResources(), FreeResourcesButNotAnims(), and OnMessage().
GetDescription()
std::string CGUIImage::GetDescription (void) const override virtual
Reimplemented from CGUIControl.
References GetFileName().
Referenced by CGUIMultiImage::GetDescription().
GetFadeLevel()
unsigned char CGUIImage::GetFadeLevel (unsigned int time) const protected
References m_crossFadeTime.
Referenced by ProcessFadingTransition().
GetFallback()
std::string CGUIImage::GetFallback (const std::string & currentName) protected
References KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetFallback(), m_currentFallback, and m_info.
Referenced by ProcessAllocation(), and ProcessState().
GetFileName()
const std::string & CGUIImage::GetFileName () const
References m_textureCurrent.
Referenced by GetDescription(), and OnMessage().
GetTextureHeight()
float CGUIImage::GetTextureHeight () const
References m_textureCurrent.
GetTextureWidth()
float CGUIImage::GetTextureWidth () const
References m_textureCurrent.
IsDynamicallyAllocated()
bool CGUIImage::IsDynamicallyAllocated () inline override virtual
Reimplemented from CGUIControl.
References m_bDynamicResourceAlloc.
OnAction()
bool CGUIImage::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControl.
OnMessage()
bool CGUIImage::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControl.
References FreeTextures(), GetFileName(), CGUIMessage::GetLabel(), CGUIMessage::GetMessage(), GUI_MSG_GET_FILENAME, GUI_MSG_REFRESH_THUMBS, GUI_MSG_SET_FILENAME, KODI::GUILIB::GUIINFO::CGUIInfoLabel::IsConstant(), m_info, CGUIControl::OnMessage(), SetFileName(), and CGUIMessage::SetLabel().
Process()
void CGUIImage::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
References m_crossFadeTime, m_isTransitioning, m_textureCurrent, m_textureNext, CGUIControl::Process(), ProcessAllocation(), ProcessFadingTransition(), ProcessInstantTransition(), ProcessNoTransition(), ProcessState(), and UpdateDiffuseColor().
Referenced by CGUIBorderedImage::Process().
ProcessAllocation()
void CGUIImage::ProcessAllocation () protected
References KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetFallback(), GetFallback(), m_info, m_isTransitioning, m_nameCurrent, m_nameNext, m_textureCurrent, and m_textureNext.
Referenced by Process().
ProcessFadingTransition()
void CGUIImage::ProcessFadingTransition (unsigned int currentTime) protected
References GetFadeLevel(), CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), m_crossFadeTime, m_currentFadeTime, m_isTransitioning, m_lastRenderTime, m_nameCurrent, m_nameNext, m_textureCurrent, m_textureNext, and CGUIControl::MarkDirtyRegion().
Referenced by Process().
ProcessInstantTransition()
void CGUIImage::ProcessInstantTransition (unsigned int currentTime) protected
References m_isTransitioning, m_nameCurrent, m_nameNext, m_textureCurrent, m_textureNext, and CGUIControl::MarkDirtyRegion().
Referenced by Process().
ProcessNoTransition()
void CGUIImage::ProcessNoTransition (unsigned int currentTime) protected
References m_textureCurrent, and CGUIControl::MarkDirtyRegion().
Referenced by Process().
ProcessState()
void CGUIImage::ProcessState () protected
References GetFallback(), m_crossFadeTime, m_currentFadeTime, m_hasNewStagingTexture, m_isTransitioning, m_nameCurrent, m_nameNext, m_nameStaging, m_textureCurrent, and m_textureNext.
Referenced by Process().
Render()
void CGUIImage::Render () override virtual
Reimplemented from CGUIControl.
References CGUIControl::IsVisible(), m_isTransitioning, m_textureCurrent, m_textureNext, and CGUIControl::Render().
Referenced by CGUIBorderedImage::Render(), and CGUIMultiImage::Render().
SetAspectRatio()
void CGUIImage::SetAspectRatio (const CAspectRatio & aspect) virtual
References m_textureCurrent, and m_textureNext.
Referenced by CGUIControlFactory::Create(), CGUIListItemLayout::CreateListControlLayouts(), and CGUIMultiImage::SetAspectRatio().
SetCrossFade()
void CGUIImage::SetCrossFade (unsigned int time)
References m_crossFadeTime.
Referenced by CGUIMultiImage::CGUIMultiImage(), and CGUIControlFactory::Create().
SetFileName()
void CGUIImage::SetFileName (const std::string & strFileName, bool setConstant = false, const bool useCache = true) virtual
References CGUIControl::GetParentID(), m_hasNewStagingTexture, m_info, m_nameStaging, and KODI::GUILIB::GUIINFO::CGUIInfoLabel::SetLabel().
Referenced by KODI::GAME::CGUIGameController::ActivateController(), CGUIMultiImage::OnDirectoryLoaded(), OnMessage(), CGUIMultiImage::Process(), ADDON::Interface_GUIControlImage::set_filename(), CGUIDialogVideoInfo::Update(), and UpdateInfo().
SetHeight()
void CGUIImage::SetHeight (float height) override virtual
Reimplemented from CGUIControl.
References m_textureCurrent, m_textureNext, and CGUIControl::SetHeight().
SetInfo()
void CGUIImage::SetInfo (const KODI::GUILIB::GUIINFO::CGUIInfoLabel & info) virtual
References KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::IsConstant(), m_info, m_nameCurrent, and m_textureCurrent.
Referenced by CGUIControlFactory::Create(), and CGUIListItemLayout::CreateListControlLayouts().
SetInvalid()
void CGUIImage::SetInvalid () override virtual
Reimplemented from CGUIControl.
References m_textureCurrent, m_textureNext, and CGUIControl::SetInvalid().
Referenced by CGUIMultiImage::SetInvalid().
SetPosition()
void CGUIImage::SetPosition (float posX, float posY) override virtual
Reimplemented from CGUIControl.
References m_textureCurrent, m_textureNext, and CGUIControl::SetPosition().
SetWidth()
void CGUIImage::SetWidth (float width) override virtual
Reimplemented from CGUIControl.
References m_textureCurrent, m_textureNext, and CGUIControl::SetWidth().
UpdateDiffuseColor()
void CGUIImage::UpdateDiffuseColor (const CGUIListItem * item) protected
Update the diffuse color based on the current item infos.
Parameters
item the item to for info resolution
References CGUIControl::m_diffuseColor, m_textureCurrent, m_textureNext, and CGUIControl::MarkDirtyRegion().
Referenced by Process(), KODI::GAME::CGUIGameController::SetActivation(), and UpdateInfo().
UpdateInfo()
void CGUIImage::UpdateInfo (const CGUIListItem * item = NULL) override virtual
Reimplemented from CGUIControl.
References ANIM_TYPE_HIDDEN, KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetItemLabel(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), CGUIControl::HasProcessed(), CGUIControl::IsAnimating(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::IsConstant(), CGUIControl::IsVisibleFromSkin(), m_currentFallback, m_info, CGUIControl::m_parentID, m_textureCurrent, SetFileName(), and UpdateDiffuseColor().
Referenced by KODI::GAME::CGUIGameController::UpdateInfo().
UpdateVisibility()
void CGUIImage::UpdateVisibility (const CGUIListItem * item = NULL) override virtual
Reimplemented from CGUIControl.
References AllocateOnDemand(), and CGUIControl::UpdateVisibility().
Member Data Documentation
m_bDynamicResourceAlloc
bool CGUIImage::m_bDynamicResourceAlloc protected
Referenced by AllocateOnDemand(), CGUIImage(), CGUIImage(), DynamicResourceAlloc(), and IsDynamicallyAllocated().
m_crossFadeTime
unsigned int CGUIImage::m_crossFadeTime protected
Referenced by CGUIImage(), CGUIImage(), GetFadeLevel(), Process(), ProcessFadingTransition(), ProcessState(), and SetCrossFade().
m_currentFadeTime
unsigned int CGUIImage::m_currentFadeTime protected
Referenced by CGUIImage(), CGUIImage(), FreeTextures(), ProcessFadingTransition(), and ProcessState().
m_currentFallback
std::string CGUIImage::m_currentFallback protected
Referenced by GetFallback(), and UpdateInfo().
m_hasNewStagingTexture
bool CGUIImage::m_hasNewStagingTexture {false} protected
Referenced by ProcessState(), and SetFileName().
m_image
CTextureInfo CGUIImage::m_image protected
m_info
KODI::GUILIB::GUIINFO::CGUIInfoLabel CGUIImage::m_info protected
Referenced by FreeTextures(), GetFallback(), OnMessage(), ProcessAllocation(), SetFileName(), SetInfo(), and UpdateInfo().
m_isTransitioning
bool CGUIImage::m_isTransitioning {false} protected
Referenced by CalcRenderRegion(), FreeTextures(), Process(), ProcessAllocation(), ProcessFadingTransition(), ProcessInstantTransition(), ProcessState(), and Render().
m_lastRenderTime
unsigned int CGUIImage::m_lastRenderTime protected
Referenced by CGUIImage(), CGUIImage(), FreeTextures(), and ProcessFadingTransition().
m_nameCurrent
std::string CGUIImage::m_nameCurrent {} protected
Referenced by FreeTextures(), ProcessAllocation(), ProcessFadingTransition(), ProcessInstantTransition(), ProcessState(), and SetInfo().
m_nameNext
std::string CGUIImage::m_nameNext {} protected
Referenced by FreeTextures(), ProcessAllocation(), ProcessFadingTransition(), ProcessInstantTransition(), and ProcessState().
m_nameStaging
std::string CGUIImage::m_nameStaging {} protected
Referenced by ProcessState(), and SetFileName().
m_textureCurrent
std::unique_ptr<CGUITexture> CGUIImage::m_textureCurrent protected
Referenced by AllocateOnDemand(), AllocResources(), CalcRenderRegion(), DynamicResourceAlloc(), FreeTextures(), GetFileName(), GetTextureHeight(), GetTextureWidth(), CGUIBorderedImage::Process(), Process(), ProcessAllocation(), ProcessFadingTransition(), ProcessInstantTransition(), ProcessNoTransition(), ProcessState(), CGUIBorderedImage::Render(), Render(), SetAspectRatio(), SetHeight(), SetInfo(), SetInvalid(), SetPosition(), SetWidth(), UpdateDiffuseColor(), and UpdateInfo().
m_textureNext
std::unique_ptr<CGUITexture> CGUIImage::m_textureNext protected
Referenced by CalcRenderRegion(), CGUIImage(), DynamicResourceAlloc(), FreeTextures(), Process(), ProcessAllocation(), ProcessFadingTransition(), ProcessInstantTransition(), ProcessState(), Render(), SetAspectRatio(), SetHeight(), SetInvalid(), SetPosition(), SetWidth(), and UpdateDiffuseColor().
The documentation for this class was generated from the following files:
GUIImage.h
GUIImage.cpp