Kodi Documentation: Control Slider
Control Slider
C++ » Interface - kodi::gui » 3. Windows » 3. GUI controls (kodi::gui::controls::C...)
Class: kodi::gui::controls::CSlider
Window control for moveable slider
The slider control is used for things where a sliding bar best represents the operation at hand (such as a volume control or seek control).
Functions
kodi::gui::controls::CSlider::CSlider (CWindow *window, int controlId)
Construct a new control.
kodi::gui::controls::CSlider::~CSlider () override=default
Destructor.
void kodi::gui::controls::CSlider::SetVisible (bool visible)
Set the control on window to visible.
void kodi::gui::controls::CSlider::SetEnabled (bool enabled)
Set's the control's enabled/disabled state.
void kodi::gui::controls::CSlider::Reset ()
To reset slider on defaults.
std::string kodi::gui::controls::CSlider::GetDescription () const
With GetDescription becomes a string value of position returned.
void kodi::gui::controls::CSlider::SetIntRange (int start, int end)
To set the the range as integer of slider, e.g. -10 is the slider start and e.g. +10 is the from here defined position where it reach the end.
void kodi::gui::controls::CSlider::SetIntValue (int value)
Set the slider position with the given integer value. The Range must be defined with a call from SetIntRange before.
int kodi::gui::controls::CSlider::GetIntValue () const
To get the current position as integer value.
void kodi::gui::controls::CSlider::SetIntInterval (int interval)
To set the interval steps of slider, as default is it 1. If it becomes changed with this function will a step of the user with the value fixed here be executed.
void kodi::gui::controls::CSlider::SetPercentage (float percent)
Sets the percent of the slider.
float kodi::gui::controls::CSlider::GetPercentage () const
Returns a float of the percent of the slider.
void kodi::gui::controls::CSlider::SetFloatRange (float start, float end)
To set the the range as float of slider, e.g. -25.0 is the slider start and e.g. +25.0 is the from here defined position where it reach the end.
void kodi::gui::controls::CSlider::SetFloatValue (float value)
Set the slider position with the given float value. The Range can be defined with a call from SetIntRange before, as default it is 0.0 to 1.0.
float kodi::gui::controls::CSlider::GetFloatValue () const
To get the current position as float value.
void kodi::gui::controls::CSlider::SetFloatInterval (float interval)
To set the interval steps of slider, as default is it 0.1 If it becomes changed with this function will a step of the user with the value fixed here be executed.
Detailed Description
Class: kodi::gui::controls::CSlider
Window control for moveable slider
The slider control is used for things where a sliding bar best represents the operation at hand (such as a volume control or seek control).
You can choose the position, size, and look of the slider control.
It has the header #include <kodi/gui/controls/Slider.h> be included to enjoy it.
Here you find the needed skin part for a slider control.
Note
The call of the control is only possible from the corresponding window as its class and identification number is required.
Function Documentation
CSlider()
kodi::gui::controls::CSlider::CSlider (CWindow * window, int controlId) inline
Construct a new control.
Parameters
[in] window Related window control class
[in] controlId Used skin xml control id
References ADDON_LOG_FATAL, kodi::Log(), and m_interface.
GetDescription()
std::string kodi::gui::controls::CSlider::GetDescription () const inline
With GetDescription becomes a string value of position returned.
Returns
Text string about current slider position
The following are the text definition returned from this:
Value Without range selection With range selection
float %2.2f [%2.2f, %2.2f]
integer i [i, i]
percent i%% [i%%, i%%]
References m_interface, and text.
GetFloatValue()
float kodi::gui::controls::CSlider::GetFloatValue () const inline
To get the current position as float value.
Returns
The position as float
References m_interface.
GetIntValue()
int kodi::gui::controls::CSlider::GetIntValue () const inline
To get the current position as integer value.
Returns
The position as integer
Note
Percent, floating point or integer are alone possible. Combining these different values can be not together and can, therefore, only one each can be used.
References m_interface.
GetPercentage()
float kodi::gui::controls::CSlider::GetPercentage () const inline
Returns a float of the percent of the slider.
Returns
float - Percent of slider
Note
Percent, floating point or integer are alone possible. Combining these different values can be not together and can, therefore, only one each can be used.
References m_interface.
Reset()
void kodi::gui::controls::CSlider::Reset () inline
To reset slider on defaults.
References m_interface.
SetEnabled()
void kodi::gui::controls::CSlider::SetEnabled (bool enabled) inline
Set's the control's enabled/disabled state.
Parameters
[in] enabled If true enabled, otherwise disabled
References m_interface.
SetFloatInterval()
void kodi::gui::controls::CSlider::SetFloatInterval (float interval) inline
To set the interval steps of slider, as default is it 0.1 If it becomes changed with this function will a step of the user with the value fixed here be executed.
Parameters
[in] interval Intervall step to set.
Note
Percent, floating point or integer are alone possible. Combining these different values can be not together and can, therefore, only one each can be used.
References m_interface.
SetFloatRange()
void kodi::gui::controls::CSlider::SetFloatRange (float start, float end) inline
To set the the range as float of slider, e.g. -25.0 is the slider start and e.g. +25.0 is the from here defined position where it reach the end.
As default is the range 0.0 to 1.0.
The float interval is as default 0.1 and can be changed with SetFloatInterval.
Parameters
[in] start Integer start value
[in] end Integer end value
Note
Percent, floating point or integer are alone possible. Combining these different values can be not together and can, therefore, only one each can be used.
References end(), and m_interface.
SetFloatValue()
void kodi::gui::controls::CSlider::SetFloatValue (float value) inline
Set the slider position with the given float value. The Range can be defined with a call from SetIntRange before, as default it is 0.0 to 1.0.
Parameters
[in] value Position in range to set with float
Note
Percent, floating point or integer are alone possible. Combining these different values can be not together and can, therefore, only one each can be used.
References m_interface, and value.
SetIntInterval()
void kodi::gui::controls::CSlider::SetIntInterval (int interval) inline
To set the interval steps of slider, as default is it 1. If it becomes changed with this function will a step of the user with the value fixed here be executed.
Parameters
[in] interval Intervall step to set.
Note
Percent, floating point or integer are alone possible. Combining these different values can be not together and can, therefore, only one each can be used.
References m_interface.
SetIntRange()
void kodi::gui::controls::CSlider::SetIntRange (int start, int end) inline
To set the the range as integer of slider, e.g. -10 is the slider start and e.g. +10 is the from here defined position where it reach the end.
Ad default is the range from 0 to 100.
The integer interval is as default 1 and can be changed with SetIntInterval.
Parameters
[in] start Integer start value
[in] end Integer end value
Note
Percent, floating point or integer are alone possible. Combining these different values can be not together and can, therefore, only one each can be used.
References end(), and m_interface.
SetIntValue()
void kodi::gui::controls::CSlider::SetIntValue (int value) inline
Set the slider position with the given integer value. The Range must be defined with a call from SetIntRange before.
Parameters
[in] value Position in range to set with integer
Note
Percent, floating point or integer are alone possible. Combining these different values can be not together and can, therefore, only one each can be used.
References m_interface, and value.
SetPercentage()
void kodi::gui::controls::CSlider::SetPercentage (float percent) inline
Sets the percent of the slider.
Parameters
[in] percent float - Percent value of slide
Note
Percent, floating point or integer are alone possible. Combining these different values can be not together and can, therefore, only one each can be used.
References m_interface.
SetVisible()
void kodi::gui::controls::CSlider::SetVisible (bool visible) inline
Set the control on window to visible.
Parameters
[in] visible If true visible, otherwise hidden
References m_interface.
~CSlider()
kodi::gui::controls::CSlider::~CSlider () override default
Destructor.