Kodi Documentation: CHttpRanges Class Reference
CHttpRanges Class Reference final
#include <HttpRangeUtils.h>
Public Member Functions
CHttpRanges ()
CHttpRanges (const HttpRanges &httpRanges)
const HttpRanges & Get () const
bool Get (size_t index, CHttpRange &range) const
bool GetFirst (CHttpRange &range) const
bool GetLast (CHttpRange &range) const
size_t Size () const
bool IsEmpty () const
bool GetFirstPosition (uint64_t &position) const
bool GetLastPosition (uint64_t &position) const
uint64_t GetLength () const
bool GetTotalRange (CHttpRange &range) const
void Add (const CHttpRange &range)
void Remove (size_t index)
void Clear ()
HttpRanges::const_iterator Begin () const
HttpRanges::const_iterator End () const
bool Parse (const std::string &header)
bool Parse (const std::string &header, uint64_t totalLength)
Protected Member Functions
void SortAndCleanup ()
Protected Attributes
HttpRanges m_ranges
Constructor & Destructor Documentation
CHttpRanges() [1/2]
CHttpRanges::CHttpRanges ()
CHttpRanges() [2/2]
CHttpRanges::CHttpRanges (const HttpRanges & httpRanges) explicit
References SortAndCleanup().
Member Function Documentation
Add()
void CHttpRanges::Add (const CHttpRange & range)
References CHttpRange::IsValid(), m_ranges, and SortAndCleanup().
Referenced by TEST().
Begin()
HttpRanges::const_iterator CHttpRanges::Begin () const inline
References m_ranges.
Referenced by CHTTPImageTransformationHandler::HandleRequest().
Clear()
void CHttpRanges::Clear ()
References m_ranges.
Referenced by HTTPRequestHandlerUtils::GetRequestedRanges(), IHTTPRequestHandler::GetRequestedRanges(), CWebServer::IsRequestRanged(), and TEST().
End()
HttpRanges::const_iterator CHttpRanges::End () const inline
References m_ranges.
Referenced by CHTTPImageTransformationHandler::HandleRequest().
Get() [1/2]
const HttpRanges & CHttpRanges::Get () const inline
References m_ranges.
Referenced by TestWebServer::CheckRangesTestFileResponse(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
Get() [2/2]
bool CHttpRanges::Get (size_t index, CHttpRange & range) const
References index(), m_ranges, and Size().
GetFirst()
bool CHttpRanges::GetFirst (CHttpRange & range) const
References m_ranges.
Referenced by TestWebServer::CheckRangesTestFileResponse(), CWebServer::ContentReaderCallback(), TEST(), TEST(), and TEST().
GetFirstPosition()
bool CHttpRanges::GetFirstPosition (uint64_t & position) const
References CHttpRange::GetFirstPosition(), and m_ranges.
Referenced by TestWebServer::CheckRangesTestFileResponse(), GetTotalRange(), TEST(), and TEST().
GetLast()
bool CHttpRanges::GetLast (CHttpRange & range) const
References m_ranges.
Referenced by TEST(), TEST(), and TEST().
GetLastPosition()
bool CHttpRanges::GetLastPosition (uint64_t & position) const
References m_ranges.
Referenced by TestWebServer::CheckRangesTestFileResponse(), GetTotalRange(), TEST(), and TEST().
GetLength()
uint64_t CHttpRanges::GetLength () const
References m_ranges.
Referenced by TEST(), and TEST().
GetTotalRange()
bool CHttpRanges::GetTotalRange (CHttpRange & range) const
References GetFirstPosition(), GetLastPosition(), CHttpRange::IsValid(), m_ranges, CHttpRange::SetFirstPosition(), and CHttpRange::SetLastPosition().
Referenced by TEST(), and TEST().
IsEmpty()
bool CHttpRanges::IsEmpty () const inline
References m_ranges.
Referenced by TestWebServer::CheckRangesTestFileResponse(), CWebServer::ContentReaderCallback(), CWebServer::CreateFileDownloadResponse(), CWebServer::CreateMemoryDownloadResponse(), and CWebServer::IsRequestRanged().
Parse() [1/2]
bool CHttpRanges::Parse (const std::string & header)
References Parse().
Referenced by HTTPRequestHandlerUtils::GetRequestedRanges(), CWebServer::IsRequestRanged(), Parse(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Parse() [2/2]
bool CHttpRanges::Parse (const std::string & header, uint64_t totalLength)
References end(), m_ranges, SortAndCleanup(), and str2uint64().
Remove()
void CHttpRanges::Remove (size_t index)
References index(), m_ranges, and Size().
Referenced by CWebServer::ContentReaderCallback(), and TEST().
Size()
size_t CHttpRanges::Size () const inline
References m_ranges.
Referenced by TestWebServer::CheckRangesTestFileResponse(), CWebServer::ContentReaderCallback(), CWebServer::CreateMemoryDownloadResponse(), Get(), Remove(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
SortAndCleanup()
void CHttpRanges::SortAndCleanup () protected
References m_ranges.
Referenced by Add(), CHttpRanges(), and Parse().
Member Data Documentation
m_ranges
HttpRanges CHttpRanges::m_ranges protected
Referenced by Add(), Begin(), Clear(), End(), Get(), Get(), GetFirst(), GetFirstPosition(), GetLast(), GetLastPosition(), GetLength(), GetTotalRange(), IsEmpty(), Parse(), Remove(), Size(), and SortAndCleanup().
The documentation for this class was generated from the following files:
HttpRangeUtils.h
HttpRangeUtils.cpp