Kodi Documentation: TestHttpRangeUtils.cpp File Reference
TestHttpRangeUtils.cpp File Reference
#include "utils/HttpRangeUtils.h"
#include <gtest/gtest.h>
Macros
#define RANGES_START "bytes="
Functions
TEST (TestHttpRange, FirstPosition)
TEST (TestHttpRange, LastPosition)
TEST (TestHttpRange, Length)
TEST (TestHttpRange, IsValid)
TEST (TestHttpRange, Ctor)
TEST (TestHttpResponseRange, SetData)
TEST (TestHttpRanges, Ctor)
TEST (TestHttpRanges, GetAll)
TEST (TestHttpRanges, GetIndex)
TEST (TestHttpRanges, GetFirst)
TEST (TestHttpRanges, GetLast)
TEST (TestHttpRanges, Size)
TEST (TestHttpRanges, GetFirstPosition)
TEST (TestHttpRanges, GetLastPosition)
TEST (TestHttpRanges, GetLength)
TEST (TestHttpRanges, GetTotalRange)
TEST (TestHttpRanges, Add)
TEST (TestHttpRanges, Remove)
TEST (TestHttpRanges, Clear)
TEST (TestHttpRanges, ParseInvalid)
TEST (TestHttpRanges, ParseStartOnly)
TEST (TestHttpRanges, ParseFromEnd)
TEST (TestHttpRanges, ParseSingle)
TEST (TestHttpRanges, ParseMulti)
TEST (TestHttpRanges, ParseOrderedNotOverlapping)
TEST (TestHttpRanges, ParseOrderedBackToBack)
TEST (TestHttpRanges, ParseOrderedOverlapping)
TEST (TestHttpRanges, ParseUnorderedNotOverlapping)
TEST (TestHttpRanges, ParseUnorderedBackToBack)
TEST (TestHttpRanges, ParseUnorderedOverlapping)
Variables
static const uint64_t DefaultFirstPosition = 1
static const uint64_t DefaultLastPosition = 0
static const uint64_t DefaultLength = 0
static const void * DefaultData = NULL
Macro Definition Documentation
RANGES_START
#define RANGES_START "bytes="
Function Documentation
TEST() [1/30]
TEST (TestHttpRange , Ctor)
References DefaultLength, EXPECT_EQ(), EXPECT_TRUE(), CHttpRange::GetFirstPosition(), CHttpRange::GetLastPosition(), CHttpRange::GetLength(), and CHttpRange::IsValid().
TEST() [2/30]
TEST (TestHttpRange , FirstPosition)
References DefaultFirstPosition, EXPECT_EQ(), CHttpRange::GetFirstPosition(), and CHttpRange::SetFirstPosition().
TEST() [3/30]
TEST (TestHttpRange , IsValid)
References EXPECT_TRUE(), CHttpRange::IsValid(), CHttpRange::SetFirstPosition(), and CHttpRange::SetLastPosition().
TEST() [4/30]
TEST (TestHttpRange , LastPosition)
References DefaultLastPosition, EXPECT_EQ(), CHttpRange::GetLastPosition(), and CHttpRange::SetLastPosition().
TEST() [5/30]
TEST (TestHttpRange , Length)
References DefaultLength, EXPECT_EQ(), CHttpRange::GetLastPosition(), CHttpRange::GetLength(), CHttpRange::SetFirstPosition(), CHttpRange::SetLastPosition(), and CHttpRange::SetLength().
TEST() [6/30]
TEST (TestHttpRanges , Add)
References CHttpRanges::Add(), EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::GetFirst(), CHttpRanges::GetLast(), and CHttpRanges::Size().
TEST() [7/30]
TEST (TestHttpRanges , Clear)
References CHttpRanges::Clear(), EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), and CHttpRanges::Size().
TEST() [8/30]
TEST (TestHttpRanges , Ctor)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::GetFirst(), CHttpRanges::GetFirstPosition(), CHttpRanges::GetLast(), CHttpRanges::GetLastPosition(), CHttpRanges::GetLength(), CHttpRanges::GetTotalRange(), and CHttpRanges::Size().
TEST() [9/30]
TEST (TestHttpRanges , GetAll)
References EXPECT_EQ(), and CHttpRanges::Get().
TEST() [10/30]
TEST (TestHttpRanges , GetFirst)
References EXPECT_EQ(), EXPECT_TRUE(), and CHttpRanges::GetFirst().
TEST() [11/30]
TEST (TestHttpRanges , GetFirstPosition)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRange::GetFirstPosition(), and CHttpRanges::GetFirstPosition().
TEST() [12/30]
TEST (TestHttpRanges , GetIndex)
References EXPECT_EQ(), EXPECT_TRUE(), and CHttpRanges::Get().
TEST() [13/30]
TEST (TestHttpRanges , GetLast)
References EXPECT_EQ(), EXPECT_TRUE(), and CHttpRanges::GetLast().
TEST() [14/30]
TEST (TestHttpRanges , GetLastPosition)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRange::GetLastPosition(), and CHttpRanges::GetLastPosition().
TEST() [15/30]
TEST (TestHttpRanges , GetLength)
References EXPECT_EQ(), CHttpRange::GetLength(), and CHttpRanges::GetLength().
TEST() [16/30]
TEST (TestHttpRanges , GetTotalRange)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRange::GetFirstPosition(), CHttpRange::GetLastPosition(), and CHttpRanges::GetTotalRange().
TEST() [17/30]
TEST (TestHttpRanges , ParseFromEnd)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Parse(), RANGES_START, and CHttpRanges::Size().
TEST() [18/30]
TEST (TestHttpRanges , ParseInvalid)
References CHttpRanges::Parse(), and RANGES_START.
TEST() [19/30]
TEST (TestHttpRanges , ParseMulti)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Parse(), RANGES_START, and CHttpRanges::Size().
TEST() [20/30]
TEST (TestHttpRanges , ParseOrderedBackToBack)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Parse(), RANGES_START, and CHttpRanges::Size().
TEST() [21/30]
TEST (TestHttpRanges , ParseOrderedNotOverlapping)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Parse(), RANGES_START, and CHttpRanges::Size().
TEST() [22/30]
TEST (TestHttpRanges , ParseOrderedOverlapping)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Parse(), RANGES_START, and CHttpRanges::Size().
TEST() [23/30]
TEST (TestHttpRanges , ParseSingle)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Parse(), RANGES_START, and CHttpRanges::Size().
TEST() [24/30]
TEST (TestHttpRanges , ParseStartOnly)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Parse(), RANGES_START, and CHttpRanges::Size().
TEST() [25/30]
TEST (TestHttpRanges , ParseUnorderedBackToBack)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Parse(), RANGES_START, and CHttpRanges::Size().
TEST() [26/30]
TEST (TestHttpRanges , ParseUnorderedNotOverlapping)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Parse(), RANGES_START, and CHttpRanges::Size().
TEST() [27/30]
TEST (TestHttpRanges , ParseUnorderedOverlapping)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Parse(), RANGES_START, and CHttpRanges::Size().
TEST() [28/30]
TEST (TestHttpRanges , Remove)
References EXPECT_EQ(), EXPECT_TRUE(), CHttpRanges::Get(), CHttpRanges::Remove(), and CHttpRanges::Size().
TEST() [29/30]
TEST (TestHttpRanges , Size)
References EXPECT_EQ(), and CHttpRanges::Size().
TEST() [30/30]
TEST (TestHttpResponseRange , SetData)
References DefaultData, EXPECT_EQ(), EXPECT_TRUE(), CHttpResponseRange::GetData(), CHttpRange::GetFirstPosition(), CHttpRange::GetLastPosition(), CHttpRange::GetLength(), CHttpResponseRange::IsValid(), and CHttpResponseRange::SetData().
Variable Documentation
DefaultData
const void* DefaultData = NULL static
Referenced by TEST().
DefaultFirstPosition
const uint64_t DefaultFirstPosition = 1 static
Referenced by TEST().
DefaultLastPosition
const uint64_t DefaultLastPosition = 0 static
Referenced by TEST().
DefaultLength
const uint64_t DefaultLength = 0 static
Referenced by TEST(), and TEST().