Kodi Documentation: KODI::KEYMAP::CCustomControllerTranslator Class Reference
KODI::KEYMAP::CCustomControllerTranslator Class Reference
#include <CustomControllerTranslator.h>
Public Member Functions
CCustomControllerTranslator ()=default
void MapActions (int windowID, const tinyxml2::XMLNode *pDevice) override
void Clear () override
bool TranslateCustomControllerString (int windowId, const std::string &controllerName, int buttonId, int &action, std::string &strAction)
Public Member Functions inherited from KODI::KEYMAP::IKeyMapper
virtual ~IKeyMapper ()=default
Private Types
using CustomControllerButtonMap = std::map< int, std::string >
using CustomControllerWindowMap = std::map< int, CustomControllerButtonMap >
Private Member Functions
bool TranslateString (int windowId, const std::string &controllerName, int buttonId, unsigned int &actionId, std::string &strAction)
Private Attributes
std::map< std::string, CustomControllerWindowMap > m_customControllersMap
Member Typedef Documentation
CustomControllerButtonMap
using KODI::KEYMAP::CCustomControllerTranslator::CustomControllerButtonMap = std::map<int, std::string> private
CustomControllerWindowMap
using KODI::KEYMAP::CCustomControllerTranslator::CustomControllerWindowMap = std::map<int, CustomControllerButtonMap> private
Constructor & Destructor Documentation
CCustomControllerTranslator()
KODI::KEYMAP::CCustomControllerTranslator::CCustomControllerTranslator () default
Member Function Documentation
Clear()
void CCustomControllerTranslator::Clear () override virtual
Implements KODI::KEYMAP::IKeyMapper.
References m_customControllersMap.
MapActions()
void CCustomControllerTranslator::MapActions (int windowID, const tinyxml2::XMLNode * pDevice) override virtual
Implements KODI::KEYMAP::IKeyMapper.
References id, CLog::Log(), LOGERROR, m_customControllersMap, and name.
TranslateCustomControllerString()
bool CCustomControllerTranslator::TranslateCustomControllerString (int windowId, const std::string & controllerName, int buttonId, int & action, std::string & strAction)
References ACTION_NONE, CWindowTranslator::GetFallbackWindow(), CWindowTranslator::GetVirtualWindow(), and TranslateString().
TranslateString()
bool CCustomControllerTranslator::TranslateString (int windowId, const std::string & controllerName, int buttonId, unsigned int & actionId, std::string & strAction) private
References ACTION_NONE, m_customControllersMap, and KODI::ACTION::CActionTranslator::TranslateString().
Referenced by TranslateCustomControllerString().
Member Data Documentation
m_customControllersMap
std::map<std::string, CustomControllerWindowMap> KODI::KEYMAP::CCustomControllerTranslator::m_customControllersMap private
Referenced by Clear(), MapActions(), and TranslateString().
The documentation for this class was generated from the following files:
CustomControllerTranslator.h
CustomControllerTranslator.cpp