Kodi Documentation: CNetworkAndroid Class Reference
CNetworkAndroid Class Reference
#include <NetworkAndroid.h>
Public Member Functions
CNetworkAndroid ()
~CNetworkAndroid () override
bool GetHostName (std::string &hostname) override
std::vector< CNetworkInterface * > & GetInterfaceList () override
CNetworkInterface * GetFirstConnectedInterface () override
std::vector< std::string > GetNameServers () override
bool PingHost (unsigned long remote_ip, unsigned int timeout_ms=2000) override
void onAvailable (const CJNINetwork network) override
void onLost (const CJNINetwork network) override
bool PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms=2000, bool readability_check=false)
virtual bool PingHost (unsigned long host, unsigned int timeout_ms=2000)=0
Public Member Functions inherited from CNetworkBase
CNetworkBase ()
virtual ~CNetworkBase ()
CNetworkServices & GetServices ()
bool HasInterfaceForIP (unsigned long address)
bool IsAvailable (void)
bool IsConnected (void)
bool WakeOnLan (const char *mac)
bool PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms=2000, bool readability_check=false)
void NetworkMessage (EMESSAGE message, int param)
bool IsLocalHost (const std::string &hostname)
void WaitForNet ()
Public Member Functions inherited from jni::CJNIXBMCConnectivityManagerNetworkCallback
CJNIXBMCConnectivityManagerNetworkCallback ()
~CJNIXBMCConnectivityManagerNetworkCallback () override
Protected Member Functions
void RetrieveInterfaces ()
Protected Attributes
std::vector< CNetworkInterface * > m_interfaces
std::vector< CNetworkInterface * > m_oldInterfaces
CCriticalSection m_refreshMutex
std::unique_ptr< CNetworkInterface > m_defaultInterface
Additional Inherited Members
Public Types inherited from CNetworkBase
enum EMESSAGE { SERVICES_UP , SERVICES_DOWN }
Static Public Member Functions inherited from CNetworkBase
static std::unique_ptr< CNetworkBase > GetNetwork ()
static int ParseHex (char *str, unsigned char *addr)
static std::string GetIpStr (const sockaddr *sa)
IPv6/IPv4 compatible conversion of host IP address.
static std::string GetMaskByPrefixLength (uint8_t prefixLength)
convert prefix length of IPv4 address to IP mask representation
Static Public Member Functions inherited from jni::CJNIXBMCConnectivityManagerNetworkCallback
static void RegisterNatives (JNIEnv *env)
Public Attributes inherited from CNetworkBase
std::unique_ptr< CNetworkServices > m_services
Static Protected Member Functions inherited from jni::CJNIXBMCConnectivityManagerNetworkCallback
static void _onAvailable (JNIEnv *env, jobject thiz, jobject network)
static void _onLost (JNIEnv *env, jobject thiz, jobject network)
Constructor & Destructor Documentation
CNetworkAndroid()
CNetworkAndroid::CNetworkAndroid ()
References RetrieveInterfaces().
~CNetworkAndroid()
CNetworkAndroid::~CNetworkAndroid () override
References m_interfaces, and m_oldInterfaces.
Member Function Documentation
GetFirstConnectedInterface()
CNetworkInterface * CNetworkAndroid::GetFirstConnectedInterface (void) override virtual
Reimplemented from CNetworkBase.
References m_defaultInterface, m_interfaces, and m_refreshMutex.
Referenced by GetHostName(), and GetNameServers().
GetHostName()
bool CNetworkAndroid::GetHostName (std::string & hostname) override virtual
Reimplemented from CNetworkBase.
References GetFirstConnectedInterface(), and CNetworkInterfaceAndroid::GetHostName().
GetInterfaceList()
std::vector< CNetworkInterface * > & CNetworkAndroid::GetInterfaceList (void) override virtual
Implements CNetworkBase.
References m_interfaces, and m_refreshMutex.
GetNameServers()
std::vector< std::string > CNetworkAndroid::GetNameServers (void) override virtual
Implements CNetworkBase.
References GetFirstConnectedInterface(), and CNetworkInterfaceAndroid::GetNameServers().
onAvailable()
void CNetworkAndroid::onAvailable (const CJNINetwork network) override virtual
Implements jni::CJNIXBMCConnectivityManagerNetworkCallback.
References CLog::Log(), LOGDEBUG, and m_defaultInterface.
onLost()
void CNetworkAndroid::onLost (const CJNINetwork network) override virtual
Implements jni::CJNIXBMCConnectivityManagerNetworkCallback.
References CLog::Log(), LOGDEBUG, and m_defaultInterface.
PingHost() [1/3]
virtual bool CNetworkBase::PingHost (unsigned long host, unsigned int timeout_ms = 2000) virtual
Implements CNetworkBase.
PingHost() [2/3]
bool CNetworkBase::PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms = 2000, bool readability_check = false)
PingHost() [3/3]
bool CNetworkAndroid::PingHost (unsigned long remote_ip, unsigned int timeout_ms = 2000) override virtual
Implements CNetworkBase.
References CLog::Log(), and LOGERROR.
RetrieveInterfaces()
void CNetworkAndroid::RetrieveInterfaces () protected
References CLog::Log(), LOGERROR, m_interfaces, m_oldInterfaces, and m_refreshMutex.
Referenced by CNetworkAndroid().
Member Data Documentation
m_defaultInterface
std::unique_ptr<CNetworkInterface> CNetworkAndroid::m_defaultInterface protected
Referenced by GetFirstConnectedInterface(), onAvailable(), and onLost().
m_interfaces
std::vector<CNetworkInterface*> CNetworkAndroid::m_interfaces protected
Referenced by GetFirstConnectedInterface(), GetInterfaceList(), RetrieveInterfaces(), and ~CNetworkAndroid().
m_oldInterfaces
std::vector<CNetworkInterface*> CNetworkAndroid::m_oldInterfaces protected
Referenced by RetrieveInterfaces(), and ~CNetworkAndroid().
m_refreshMutex
CCriticalSection CNetworkAndroid::m_refreshMutex protected
Referenced by GetFirstConnectedInterface(), GetInterfaceList(), and RetrieveInterfaces().
The documentation for this class was generated from the following files:
NetworkAndroid.h
NetworkAndroid.cpp