Kodi Documentation: CAbstractPowerSyscall Class Reference
CAbstractPowerSyscall Class Reference
#include <IPowerSyscall.h>
Public Member Functions
int CountPowerFeatures () override
Public Member Functions inherited from IPowerSyscall
virtual ~IPowerSyscall ()=default
virtual bool Powerdown ()=0
virtual bool Suspend ()=0
virtual bool Hibernate ()=0
virtual bool Reboot ()=0
virtual bool CanPowerdown ()=0
virtual bool CanSuspend ()=0
virtual bool CanHibernate ()=0
virtual bool CanReboot ()=0
virtual int BatteryLevel ()=0
virtual bool PumpPowerEvents (IPowerEventsCallback *callback)=0
Pump power related events back to xbmc.
Additional Inherited Members
Static Public Member Functions inherited from IPowerSyscall
static IPowerSyscall * CreateInstance ()
Called by power manager to create platform power system adapter.
static void RegisterPowerSyscall (CreatePowerSyscallFunc createFunc)
Static Public Attributes inherited from IPowerSyscall
static const int MAX_COUNT_POWER_FEATURES = 4
Member Function Documentation
CountPowerFeatures()
int CAbstractPowerSyscall::CountPowerFeatures () inline override virtual
Implements IPowerSyscall.
References IPowerSyscall::CanHibernate(), IPowerSyscall::CanPowerdown(), IPowerSyscall::CanReboot(), and IPowerSyscall::CanSuspend().
The documentation for this class was generated from the following file:
IPowerSyscall.h