Kodi Documentation: CRendererVAAPIGL Class Reference
CRendererVAAPIGL Class Reference
#include <RendererVAAPIGL.h>
Public Member Functions
CRendererVAAPIGL ()
~CRendererVAAPIGL () override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
bool ConfigChanged (const VideoPicture &picture) override
void ReleaseBuffer (int idx) override
bool NeedBuffer (int idx) override
bool Flush (bool saveBuffers) override
bool Supports (ERENDERFEATURE feature) const override
bool Supports (ESCALINGMETHOD method) const override
Public Member Functions inherited from CLinuxRendererGL
CLinuxRendererGL ()
~CLinuxRendererGL () override
bool IsConfigured () override
void AddVideoPicture (const VideoPicture &picture, int index) override
void UnInit () override
void SetBufferSize (int numBuffers) override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
void Update () override
bool RenderCapture (int index, CRenderCapture *capture) override
CRenderInfo GetRenderInfo () override
bool SupportsMultiPassRendering () override
CRenderCapture * GetRenderCapture () override
Public Member Functions inherited from CBaseRenderer
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool IsPictureHW (const VideoPicture &picture)
virtual bool IsGuiLayer ()
virtual bool WantsDoublePass ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
virtual DEBUG_INFO_VIDEO GetDebugInfo (int idx)
Static Public Member Functions
static CBaseRenderer * Create (CVideoBuffer *buffer)
static void Register (VAAPI::IVaapiWinSystem *winSystem, VADisplay vaDpy, EGLDisplay eglDisplay, bool &general, bool &deepColor)
Static Public Member Functions inherited from CLinuxRendererGL
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Static Public Member Functions inherited from CBaseRenderer
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
bool LoadShadersHook () override
bool RenderHook (int idx) override
void AfterRenderHook (int idx) override
bool UploadTexture (int index) override
void DeleteTexture (int index) override
bool CreateTexture (int index) override
EShaderFormat GetShaderFormat () override
Protected Member Functions inherited from CLinuxRendererGL
bool Render (unsigned int flags, int renderBuffer)
void ClearBackBuffer ()
void ClearBackBufferQuad ()
void DrawBlackBars ()
bool ValidateRenderer ()
virtual bool ValidateRenderTarget ()
virtual void LoadShaders (int field=FIELD_FULL)
void SetTextureFilter (GLenum method)
void UpdateVideoFilter ()
void CheckVideoParameters (int index)
AVColorPrimaries GetSrcPrimaries (AVColorPrimaries srcPrimaries, unsigned int width, unsigned int height)
bool UploadYV12Texture (int index)
void DeleteYV12Texture (int index)
bool CreateYV12Texture (int index)
bool UploadNV12Texture (int index)
void DeleteNV12Texture (int index)
bool CreateNV12Texture (int index)
bool UploadYUV422PackedTexture (int index)
void DeleteYUV422PackedTexture (int index)
bool CreateYUV422PackedTexture (int index)
void CalculateTextureSourceRects (int source, int num_planes)
void RenderToFBO (int renderBuffer, int field, bool weave=false)
void RenderFromFBO ()
void RenderSinglePass (int renderBuffer, int field)
void RenderRGB (int renderBuffer, int field)
void RenderProgressiveWeave (int renderBuffer, int field)
void BindPbo (CPictureBuffer &buff)
void UnBindPbo (CPictureBuffer &buff)
void LoadPlane (CYuvPlane &plane, int type, unsigned width, unsigned height, int stride, int bpp, void *data)
void GetPlaneTextureSize (CYuvPlane &plane)
GLint GetInternalFormat (GLint format, int bpp)
virtual bool CanSaveBuffers ()
bool LoadCLUT ()
void DeleteCLUT ()
Protected Member Functions inherited from CBaseRenderer
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ManageRenderArea ()
virtual void ReorderDrawPoints ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Protected Attributes
bool m_isVAAPIBuffer = true
std::unique_ptr< VAAPI::CVaapiTexture > m_vaapiTextures [NUM_BUFFERS]
GLsync m_fences [NUM_BUFFERS]
Protected Attributes inherited from CLinuxRendererGL
struct {
CFrameBufferObject fbo
float width
float height
} m_fbo
GLint m_intermediateFormat {GL_RGBA8}
GLint m_intermediateType {GL_UNSIGNED_BYTE}
bool m_intermediateGammaCorrection {false}
int m_iYV12RenderBuffer = 0
int m_NumYV12Buffers = 0
bool m_bConfigured = false
bool m_bValidated = false
GLenum m_textureTarget = GL_TEXTURE_2D
int m_renderMethod = RENDER_GLSL
RenderQuality m_renderQuality = RQ_SINGLEPASS
CRenderSystemGL * m_renderSystem = nullptr
int m_currentField = FIELD_FULL
int m_reloadShaders = 0
CPictureBuffer m_buffers [NUM_BUFFERS]
Shaders::GL::BaseYUV2RGBGLSLShader * m_pYUVShader = nullptr
Shaders::GL::BaseVideoFilterShader * m_pVideoFilterShader = nullptr
ESCALINGMETHOD m_scalingMethod = VS_SCALINGMETHOD_LINEAR
ESCALINGMETHOD m_scalingMethodGui = VS_SCALINGMETHOD_MAX
bool m_useDithering
unsigned int m_ditherDepth
bool m_fullRange
AVColorPrimaries m_srcPrimaries
bool m_toneMap = false
ETONEMAPMETHOD m_toneMapMethod = VS_TONEMAPMETHOD_OFF
float m_clearColour = 0.0f
bool m_pboSupported = true
bool m_pboUsed = false
bool m_nonLinStretch = false
bool m_nonLinStretchGui = false
float m_pixelRatio = 0.0f
CRect m_viewRect
std::unique_ptr< CColorManager > m_ColorManager
GLuint m_tCLUTTex
uint16_t * m_CLUT
int m_CLUTsize
int m_cmsToken
bool m_cmsOn
Protected Attributes inherited from CBaseRenderer
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Static Protected Attributes
static VAAPI::IVaapiWinSystem * m_pWinSystem = nullptr
Constructor & Destructor Documentation
CRendererVAAPIGL()
CRendererVAAPIGL::CRendererVAAPIGL () default
Referenced by Create().
~CRendererVAAPIGL()
CRendererVAAPIGL::~CRendererVAAPIGL () override
References DeleteTexture(), and NUM_BUFFERS.
Member Function Documentation
AfterRenderHook()
void CRendererVAAPIGL::AfterRenderHook (int idx) override protected virtual
Reimplemented from CLinuxRendererGL.
References m_fences.
ConfigChanged()
bool CRendererVAAPIGL::ConfigChanged (const VideoPicture & picture) override virtual
Reimplemented from CLinuxRendererGL.
References m_isVAAPIBuffer, VAAPI::CVaapiRenderPicture::procPic, VideoPicture::videoBuffer, and VAAPI::CVaapiProcessedPicture::videoSurface.
Configure()
bool CRendererVAAPIGL::Configure (const VideoPicture & picture, float fps, unsigned int orientation) override virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::Configure(), VAAPI::InteropInfo::eglCreateImageKHR, VAAPI::InteropInfo::eglDestroyImageKHR, VAAPI::InteropInfo::eglDisplay, VAAPI::IVaapiWinSystem::GetEGLDisplay(), VAAPI::InteropInfo::glEGLImageTargetTexture2DOES, m_fences, m_isVAAPIBuffer, m_pWinSystem, m_vaapiTextures, VAAPI::CVaapiRenderPicture::procPic, VAAPI::CVaapi2Texture::TestInteropGeneral(), VAAPI::InteropInfo::textureTarget, VAAPI::CVaapiRenderPicture::vadsp, VideoPicture::videoBuffer, and VAAPI::CVaapiProcessedPicture::videoSurface.
Create()
CBaseRenderer * CRendererVAAPIGL::Create (CVideoBuffer * buffer) static
References CRendererVAAPIGL().
Referenced by Register().
CreateTexture()
bool CRendererVAAPIGL::CreateTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::CreateNV12Texture(), YuvImage::cshift_x, YuvImage::cshift_y, DeleteTexture(), CLinuxRendererGL::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGL::CPictureBuffer::image, index(), CLinuxRendererGL::m_buffers, m_isVAAPIBuffer, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, YuvImage::MAX_PLANES, and YuvImage::width.
DeleteTexture()
void CRendererVAAPIGL::DeleteTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::DeleteNV12Texture(), FIELD_FULL, CLinuxRendererGL::CPictureBuffer::fields, CLinuxRendererGL::CYuvPlane::id, index(), CLinuxRendererGL::m_buffers, m_isVAAPIBuffer, and ReleaseBuffer().
Referenced by CreateTexture(), and ~CRendererVAAPIGL().
Flush()
bool CRendererVAAPIGL::Flush (bool saveBuffers) override virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::Flush(), m_isVAAPIBuffer, and m_vaapiTextures.
GetShaderFormat()
EShaderFormat CRendererVAAPIGL::GetShaderFormat () override protected virtual
Reimplemented from CBaseRenderer.
References SHADER_NV12.
LoadShadersHook()
bool CRendererVAAPIGL::LoadShadersHook () override protected virtual
Reimplemented from CLinuxRendererGL.
NeedBuffer()
bool CRendererVAAPIGL::NeedBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References m_fences.
Register()
void CRendererVAAPIGL::Register (VAAPI::IVaapiWinSystem * winSystem, VADisplay vaDpy, EGLDisplay eglDisplay, bool & general, bool & deepColor) static
References Create(), CLog::Log(), LOGDEBUG, m_pWinSystem, VIDEOPLAYER::CRendererFactory::RegisterRenderer(), VAAPI::CVaapi1Texture::TestInterop(), and VAAPI::CVaapi2Texture::TestInterop().
ReleaseBuffer()
void CRendererVAAPIGL::ReleaseBuffer (int idx) override virtual
Reimplemented from CLinuxRendererGL.
References m_fences, m_isVAAPIBuffer, m_vaapiTextures, and CLinuxRendererGL::ReleaseBuffer().
Referenced by DeleteTexture().
RenderHook()
bool CRendererVAAPIGL::RenderHook (int idx) override protected virtual
Reimplemented from CLinuxRendererGL.
Supports() [1/2]
bool CRendererVAAPIGL::Supports (ERENDERFEATURE feature) const override virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::Supports().
Supports() [2/2]
bool CRendererVAAPIGL::Supports (ESCALINGMETHOD method) const override virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::Supports().
UploadTexture()
bool CRendererVAAPIGL::UploadTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::BindPbo(), CLinuxRendererGL::CalculateTextureSourceRects(), CVideoBuffer::CopyNV12Picture(), YuvImage::cshift_x, YuvImage::cshift_y, CLinuxRendererGL::CPictureBuffer::fields, VAAPI::CVaapiRenderPicture::GetPlanes(), VAAPI::CVaapiRenderPicture::GetStrides(), CLinuxRendererGL::CPictureBuffer::image, index(), CLinuxRendererGL::m_buffers, m_isVAAPIBuffer, CLinuxRendererGL::m_textureTarget, m_vaapiTextures, YuvImage::plane, YuvImage::stride, CLinuxRendererGL::CYuvPlane::texwidth, CLinuxRendererGL::UnBindPbo(), CLinuxRendererGL::UploadNV12Texture(), VAAPI::CVaapiRenderPicture::valid, VerifyGLState, and CLinuxRendererGL::CPictureBuffer::videoBuffer.
Member Data Documentation
m_fences
GLsync CRendererVAAPIGL::m_fences[NUM_BUFFERS] protected
Referenced by AfterRenderHook(), Configure(), NeedBuffer(), and ReleaseBuffer().
m_isVAAPIBuffer
bool CRendererVAAPIGL::m_isVAAPIBuffer = true protected
Referenced by ConfigChanged(), Configure(), CreateTexture(), DeleteTexture(), Flush(), ReleaseBuffer(), and UploadTexture().
m_pWinSystem
IVaapiWinSystem * CRendererVAAPIGL::m_pWinSystem = nullptr static protected
Referenced by Configure(), and Register().
m_vaapiTextures
std::unique_ptr<VAAPI::CVaapiTexture> CRendererVAAPIGL::m_vaapiTextures[NUM_BUFFERS] protected
Referenced by Configure(), Flush(), ReleaseBuffer(), and UploadTexture().
The documentation for this class was generated from the following files:
RendererVAAPIGL.h
RendererVAAPIGL.cpp