Kodi Documentation: CEvent Class Reference
CEvent Class Reference
This is an Event class built from a ConditionVariable. The Event adds the state that the condition is gating as well as the mutex/lock.
#include <Event.h>
Public Member Functions
CEvent (bool manual=false, bool signaled_=false)
void Reset ()
void Set ()
bool Signaled ()
Returns true if Event has been triggered and not reset, false otherwise.
template<typename Rep , typename Period >
bool Wait (std::chrono::duration< Rep, Period > duration)
This will wait up to 'duration' for the Event to be triggered. The method will return 'true' if the Event was triggered. Otherwise it will return false.
bool Wait ()
This will wait for the Event to be triggered. The method will return 'true' if the Event was triggered. If it was either interrupted it will return false. Otherwise it will return false.
int getNumWaits ()
This is mostly for testing. It allows a thread to make sure there are the right amount of other threads waiting.
Private Member Functions
void addGroup (XbmcThreads::CEventGroup *group)
void removeGroup (XbmcThreads::CEventGroup *group)
bool prepReturn ()
CEvent (const CEvent &)=delete
CEvent & operator= (const CEvent &)=delete
Private Attributes
bool manualReset
volatile bool signaled
unsigned int numWaits = 0
CCriticalSection groupListMutex
std::unique_ptr< std::vector< XbmcThreads::CEventGroup * > > groups
XbmcThreads::ConditionVariable actualCv
CCriticalSection mutex
Friends
class XbmcThreads::CEventGroup
Detailed Description
This is an Event class built from a ConditionVariable. The Event adds the state that the condition is gating as well as the mutex/lock.
This Event can be 'interruptible' (even though there is only a single place in the code that uses this behavior).
This class manages 'spurious returns' from the condition variable.
Constructor & Destructor Documentation
CEvent() [1/2]
CEvent::CEvent (const CEvent &) private delete
CEvent() [2/2]
CEvent::CEvent (bool manual = false, bool signaled_ = false) inline
Member Function Documentation
addGroup()
void CEvent::addGroup (XbmcThreads::CEventGroup * group) private
References groupListMutex, and groups.
getNumWaits()
int CEvent::getNumWaits () inline
This is mostly for testing. It allows a thread to make sure there are the right amount of other threads waiting.
References mutex, and numWaits.
operator=()
CEvent & CEvent::operator= (const CEvent &) private delete
prepReturn()
bool CEvent::prepReturn () inline private
References manualReset, numWaits, and signaled.
Referenced by Wait(), and Wait().
removeGroup()
void CEvent::removeGroup (XbmcThreads::CEventGroup * group) private
References groupListMutex, and groups.
Reset()
void CEvent::Reset () inline
References mutex, and signaled.
Referenced by ADDON::CRepositoryUpdater::CheckForUpdates(), XFILE::Pipe::CheckStatus(), VDPAU::CDecoder::CheckStatus(), CRenderManager::Configure(), VAAPI::CDecoder::ConfigVAAPI(), VDPAU::CDecoder::ConfigVDPAU(), CThread::Create(), CVideoReferenceClock::CVideoReferenceClock(), PVR::CPVRClient::DoAddonCall(), ADDON::CAddonInstaller::DoInstall(), KODI::GAME::CGUIFeatureButton::DoPrompt(), PVR::CPVRRefreshTimelineItemsThread::DoRefresh(), CZeroconfBrowserMDNS::doResolveService(), CZeroconfBrowserAvahi::doResolveService(), PVR::CPVRManagerJobQueue::ExecutePendingJobs(), CRenderManager::Flush(), CDVDMessageQueue::Get(), PERIPHERALS::CEventScanner::HandleEvents(), PERIPHERALS::CPeripheralBus::Initialise(), ActiveAE::CActiveAE::InitSink(), ADDON::CAddonInstaller::InstallAddons(), DXVA::CDecoder::OnDestroyDevice(), VDPAU::CDecoder::OnLostDisplay(), CApplication::OnMessage(), KODI::GAME::CGUIConfigurationWizard::OnMotion(), XFILE::CFileCache::Open(), XFILE::Pipe::Pipe(), CRenderManager::PreInit(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::PrepareFramePresentation(), CVideoReferenceClock::Process(), XFILE::CFileCache::Process(), PVR::CPVRRefreshTimelineItemsThread::Process(), CWin32PowerStateWorker::Process(), PERIPHERALS::CPeripheralBus::Process(), ActiveAE::CActiveAE::Resume(), anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::RoundtripQueue(), KODI::GAME::CGUIConfigurationWizard::Run(), CScriptRunner::RunScriptInternal(), XFILE::CFileCache::Seek(), Actor::Protocol::SendOutMessageSync(), Actor::Protocol::SendOutMessageSync(), CXBMCApp::SetDisplayMode(), CGUIDialogMusicInfo::SetItem(), CCoreAudioStream::SetPhysicalFormat(), CGUIDialogSongInfo::SetSong(), CVideoSyncAndroid::Setup(), CVideoSyncIos::Setup(), CVideoSyncOsx::Setup(), CVideoSyncTVos::Setup(), KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::Setup(), CVideoSyncD3D::Setup(), KODI::WINDOWING::X11::CVideoSyncGLX::Setup(), CCoreAudioStream::SetVirtualFormat(), ActiveAE::CActiveAE::Start(), CRenderManager::StartRenderCapture(), PVR::CPVRManagerJobQueue::Stop(), jni::CJNIXBMCMainView::surfaceDestroyed(), jni::CJNIXBMCVideoView::surfaceDestroyed(), ActiveAE::CActiveAE::UnconfigureSink(), CRenderManager::UnInit(), XBMCAddon::xbmcgui::Window::WaitForActionEvent(), ADDON::CGUIAddonWindow::WaitForActionEvent(), XBPython::WaitForEvent(), PVR::CPVREpgContainer::WaitForUpdateFinish(), and CGUIMediaWindow::WaitGetDirectoryItems().
Set()
void CEvent::Set ()
References actualCv, groupListMutex, groups, mutex, XbmcThreads::ConditionVariable::notifyAll(), and signaled.
Referenced by CDVDMessageQueue::Abort(), CRunningScriptObserver::Abort(), KODI::GAME::CGUIConfigurationWizard::Abort(), XBMCAddon::xbmc::Monitor::AbortNotify(), KODI::GAME::CGUIDialogAxisDetection::AddAxis(), ANNOUNCEMENT::CAnnouncementManager::Announce(), PVR::CPVRManagerJobQueue::AppendJob(), ADDON::CAddonInstaller::Cancel(), CJobManager::CancelJobs(), DXVA::CDecoder::CDecoder(), XFILE::Pipe::CheckStatus(), CVideoSyncOsx::Cleanup(), CVideoSyncD3D::Cleanup(), KODI::WINDOWING::X11::CVideoSyncGLX::Cleanup(), PVR::CPVRManagerJobQueue::Clear(), PERIPHERALS::CPeripheralBus::Clear(), XFILE::Pipe::Close(), XFILE::CShoutcastFile::Close(), CRenderManager::Configure(), CThread::Create(), jni::CJNIXBMCVideoView::createVideoView(), ANNOUNCEMENT::CAnnouncementManager::Deinitialize(), ActiveAE::CActiveAE::Dispose(), ActiveAE::CActiveAESink::Dispose(), VAAPI::COutput::Dispose(), VDPAU::CMixer::Dispose(), VDPAU::COutput::Dispose(), PVR::CPVRClient::DoAddonCall(), CXBMCApp::doFrame(), ADDON::CAddonInstaller::DoInstall(), PVR::CPVRRefreshTimelineItemsThread::DoRefresh(), XFILE::CSimpleFileCache::EndOfInput(), XFILE::CShoutcastFile::ExtractTagInfo(), CGUIDialogMusicInfo::FetchComplete(), CGUIDialogSongInfo::FetchComplete(), CRenderManager::Flush(), CZeroconfBrowserMDNS::GetAddrInfoCallback(), PERIPHERALS::CEventScanner::HandleEvents(), KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::HandlePresentation(), CCoreAudioStream::HardwareStreamListener(), CBackgroundPicLoader::LoadPic(), CRenderManager::ManageCaptures(), KODI::GAME::CGUIConfigurationWizard::MapPrimitive(), KODI::GAME::CGUIDialogIgnoreInput::MapPrimitiveInternal(), CAirTunesServer::OnAction(), CTextureCache::OnCachingComplete(), DXVA::CDecoder::OnCreateDevice(), CXBMCApp::onDisplayChanged(), CPythonInvoker::onExecutionDone(), XFILE::CFileCache::OnExit(), CDVDMediaCodecOnFrameAvailable::onFrameAvailable(), ADDON::CAddonInstaller::OnJobComplete(), ADDON::CRepositoryUpdater::OnJobComplete(), PAPlayer::OnJobComplete(), CApplication::OnMessage(), KODI::GAME::CGUIConfigurationWizard::OnMotionless(), VDPAU::CDecoder::OnResetDisplay(), CVideoSyncAndroid::OnResetDisplay(), CVideoSyncIos::OnResetDisplay(), CVideoSyncTVos::OnResetDisplay(), CZeroconfBrowserAndroidResolve::onResolveFailed(), CZeroconfBrowserAndroidResolve::onServiceResolved(), XFILE::CShoutcastFile::Open(), PAPlayer::OpenFile(), XFILE::Pipe::Pipe(), CRenderManager::PreInit(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::PrepareFramePresentation(), XFILE::CFileCache::Process(), PERIPHERALS::CEventScanner::Process(), PVR::CPVRRefreshTimelineItemsThread::Process(), anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::Process(), ADDON::CGUIAddonWindow::PulseActionEvent(), XBMCAddon::xbmcgui::Window::PulseActionEvent(), XBPython::PulseGlobalEvent(), CDVDMessageQueue::Put(), CWin32PowerStateWorker::QueryStateChange(), XFILE::CCircularCache::ReadFromCache(), XFILE::CSimpleFileCache::ReadFromCache(), PVR::CPVRClient::ResetProperties(), CZeroconfBrowserAvahi::resolveCallback(), CZeroconfBrowserMDNS::ResolveCallback(), CTimer::RestartAsync(), CRunningScriptObserver::Run(), CVideoSyncOsx::Run(), CVideoSyncD3D::Run(), KODI::WINDOWING::X11::CVideoSyncGLX::Run(), RunMassEventTest(), XFILE::CSimpleFileCache::Seek(), XFILE::CFileCache::Seek(), Actor::Protocol::SendInMessage(), Actor::Protocol::SendInMessage(), Actor::Protocol::SendOutMessage(), Actor::Protocol::SendOutMessage(), CXBMCApp::SetDisplayModeCallback(), CScriptRunner::SetDone(), KODI::RETRO::CGameLoop::SetSpeed(), KODI::GAME::CGUIDialogButtonCapture::Show(), PVR::CPVRManagerJobQueue::Start(), CRenderManager::StartRenderCapture(), CJobManager::StartWorkers(), KODI::RETRO::CGameLoop::Stop(), PERIPHERALS::CEventScanner::Stop(), PVR::CPVRRefreshTimelineItemsThread::Stop(), CTimer::Stop(), CThread::StopThread(), XFILE::CFileCache::StopThread(), jni::CJNIXBMCMainView::surfaceCreated(), jni::CJNIXBMCVideoView::surfaceCreated(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), PERIPHERALS::CPeripheralBus::TriggerDeviceScan(), CRenderManager::UnInit(), PVR::CPVREpgContainer::UpdateEPG(), CGUIMediaWindow::WaitGetDirectoryItems(), XFILE::CCircularCache::WriteToCache(), XFILE::CSimpleFileCache::WriteToCache(), CIRServerSuite::~CIRServerSuite(), and CVideoReferenceClock::~CVideoReferenceClock().
Signaled()
bool CEvent::Signaled () inline
Returns true if Event has been triggered and not reset, false otherwise.
References mutex, and signaled.
Referenced by XBMCAddon::xbmc::Monitor::abortRequested(), jni::CJNIXBMCMainView::isActive(), jni::CJNIXBMCVideoView::isActive(), CVideoReferenceClock::Process(), CVideoSyncGbm::Run(), CVideoSyncOsx::Run(), CVideoSyncD3D::Run(), KODI::WINDOWING::X11::CVideoSyncGLX::Run(), KODI::WINDOWING::X11::CVideoSyncOML::Run(), Wait(), and Wait().
Wait() [1/2]
bool CEvent::Wait () inline
This will wait for the Event to be triggered. The method will return 'true' if the Event was triggered. If it was either interrupted it will return false. Otherwise it will return false.
References actualCv, mutex, numWaits, prepReturn(), Signaled(), and XbmcThreads::ConditionVariable::wait().
Wait() [2/2]
template<typename Rep , typename Period > bool CEvent::Wait (std::chrono::duration< Rep, Period > duration) inline
This will wait up to 'duration' for the Event to be triggered. The method will return 'true' if the Event was triggered. Otherwise it will return false.
References actualCv, mutex, numWaits, prepReturn(), Signaled(), and XbmcThreads::ConditionVariable::wait().
Referenced by ActiveAE::CActiveAEStream::AddData(), ADDON::CRepositoryUpdater::Await(), CTextureCache::CacheImage(), CGUIMediaWindow::CancelUpdateItems(), DXVA::CDecoder::Check(), VAAPI::CDecoder::Check(), VDPAU::CDecoder::Check(), PAPlayer::CloseFile(), CRenderManager::Configure(), CThread::Create(), VAAPI::CDecoder::Decode(), VDPAU::CDecoder::Decode(), PVR::CPVRClient::Destroy(), KODI::GAME::CGUIFeatureButton::DoPrompt(), CZeroconfBrowserMDNS::doResolveService(), CZeroconfBrowserAvahi::doResolveService(), CZeroconfBrowserAndroid::doResolveService(), ActiveAE::CActiveAEStream::Drain(), CRenderManager::Flush(), CDVDMessageQueue::Get(), CJobManager::GetNextJob(), PERIPHERALS::CEventScanner::HandleEvents(), CApplication::Initialize(), ADDON::CAddonInstaller::InstallAddons(), CVideoSyncOsx::OnLostDisplay(), CVideoSyncD3D::OnLostDisplay(), KODI::WINDOWING::X11::CVideoSyncGLX::OnLostDisplay(), CRenderManager::PreInit(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::PrepareFramePresentation(), ActiveAE::CActiveAE::Process(), ActiveAE::CActiveAESink::Process(), PAPlayer::Process(), KODI::RETRO::CGameLoop::Process(), VAAPI::COutput::Process(), VDPAU::CMixer::Process(), VDPAU::COutput::Process(), XFILE::CFileCache::Process(), XFILE::CShoutcastFile::Process(), KODI::GAME::CGUIDialogButtonCapture::Process(), KODI::GAME::CGUIConfigurationWizard::Process(), ANNOUNCEMENT::CAnnouncementManager::Process(), CAirTunesServer::Process(), PERIPHERALS::CEventScanner::Process(), PVR::CPVRRefreshTimelineItemsThread::Process(), CTimer::Process(), PERIPHERALS::CPeripheralBus::Process(), XFILE::Pipe::Read(), anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::RoundtripQueue(), CRunningScriptObserver::Run(), poll_mass_waiter::Run(), locker< L >::Run(), MUSIC_INFO::CMusicInfoScanner::ScannerWait(), XFILE::CFileCache::Seek(), Actor::Protocol::SendOutMessageSync(), Actor::Protocol::SendOutMessageSync(), CXBMCApp::SetDisplayMode(), CCoreAudioStream::SetPhysicalFormat(), CCoreAudioStream::SetVirtualFormat(), CThread::Sleep(), CPythonInvoker::stop(), CThread::StopThread(), TEST(), TEST(), TEST(), TEST(), TEST(), CRenderManager::UnInit(), CGUIDialogProgress::Wait(), XbmcThreads::CEventGroup::wait(), XBMCAddon::xbmc::Monitor::waitForAbort(), XBMCAddon::xbmcgui::Window::WaitForActionEvent(), ADDON::CGUIAddonWindow::WaitForActionEvent(), XFILE::CSimpleFileCache::WaitForData(), XFILE::CCircularCache::WaitForData(), PVR::CPVRManagerJobQueue::WaitForJobs(), jni::CJNIXBMCMainView::waitForSurface(), jni::CJNIXBMCVideoView::waitForSurface(), PVR::CPVREpgContainer::WaitForUpdateFinish(), CGUIMediaWindow::WaitGetDirectoryItems(), CGUIDialogProgress::WaitOnEvent(), CGUIDialogBusy::WaitOnEvent(), UPNP::WaitOnEvent(), CScriptRunner::WaitOnScriptResult(), CXBMCApp::WaitVSync(), and XFILE::Pipe::Write().
Friends And Related Symbol Documentation
XbmcThreads::CEventGroup
friend class XbmcThreads::CEventGroup friend
Member Data Documentation
actualCv
XbmcThreads::ConditionVariable CEvent::actualCv private
Referenced by Set(), Wait(), and Wait().
groupListMutex
CCriticalSection CEvent::groupListMutex private
Referenced by addGroup(), removeGroup(), and Set().
groups
std::unique_ptr<std::vector<XbmcThreads::CEventGroup*> > CEvent::groups private
Referenced by addGroup(), removeGroup(), and Set().
manualReset
bool CEvent::manualReset private
Referenced by prepReturn().
mutex
CCriticalSection CEvent::mutex private
Referenced by getNumWaits(), Reset(), Set(), Signaled(), Wait(), and Wait().
numWaits
unsigned int CEvent::numWaits = 0 private
Referenced by getNumWaits(), prepReturn(), Wait(), and Wait().
signaled
volatile bool CEvent::signaled private
Referenced by prepReturn(), Reset(), Set(), and Signaled().
The documentation for this class was generated from the following files:
Event.h
Event.cpp