Kodi Documentation: KODI::JOYSTICK::CButtonMapping Class Reference
KODI::JOYSTICK::CButtonMapping Class Reference
Input » Joystick
Generic implementation of a class that provides button mapping by translating driver events to button mapping commands.
#include <ButtonMapping.h>
Public Member Functions
CButtonMapping (IButtonMapper *buttonMapper, IButtonMap *buttonMap, KEYMAP::IKeymap *keymap)
Constructor for CButtonMapping.
~CButtonMapping () override=default
bool OnButtonMotion (unsigned int buttonIndex, bool bPressed) override
Handle button motion.
bool OnHatMotion (unsigned int hatIndex, HAT_STATE state) override
Handle hat motion.
bool OnAxisMotion (unsigned int axisIndex, float position, int center, unsigned int range) override
Handle axis motion.
void OnInputFrame () override
Handle buffered input motion for features that require multiple axes.
bool OnKeyPress (const CKey &key) override
A key has been pressed.
void OnKeyRelease (const CKey &key) override
A key has been released.
bool OnPosition (int x, int y) override
Handle mouse position updates.
bool OnButtonPress (MOUSE::BUTTON_ID button) override
A mouse button has been pressed.
void OnButtonRelease (MOUSE::BUTTON_ID button) override
A mouse button has been released.
void SaveButtonMap () override
Save the button map.
void ResetIgnoredPrimitives () override
Clear the list of ignored driver primitives.
void RevertButtonMap () override
Revert changes to the button map since the last time it was loaded or committed to disk.
bool MapPrimitive (const CDriverPrimitive &primitive)
Process the primitive mapping command.
Public Member Functions inherited from KODI::JOYSTICK::IDriverHandler
virtual ~IDriverHandler ()=default
Public Member Functions inherited from KODI::KEYBOARD::IKeyboardDriverHandler
virtual ~IKeyboardDriverHandler ()=default
Public Member Functions inherited from KODI::MOUSE::IMouseDriverHandler
virtual ~IMouseDriverHandler (void)=default
Public Member Functions inherited from KODI::JOYSTICK::IButtonMapCallback
virtual ~IButtonMapCallback ()=default
Private Member Functions
bool IsMapping () const
void OnLateDiscovery (unsigned int axisIndex)
CButtonDetector & GetButton (unsigned int buttonIndex)
CHatDetector & GetHat (unsigned int hatIndex)
CAxisDetector & GetAxis (unsigned int axisIndex, float position, const AxisConfiguration &initialConfig=AxisConfiguration())
CKeyDetector & GetKey (XBMCKey keycode)
CMouseButtonDetector & GetMouseButton (MOUSE::BUTTON_ID buttonIndex)
CPointerDetector & GetPointer ()
Private Attributes
IButtonMapper *const m_buttonMapper
IButtonMap *const m_buttonMap
KEYMAP::IKeymap *const m_keymap
std::map< unsigned int, CButtonDetector > m_buttons
std::map< unsigned int, CHatDetector > m_hats
std::map< unsigned int, CAxisDetector > m_axes
std::map< XBMCKey, CKeyDetector > m_keys
std::map< MOUSE::BUTTON_ID, CMouseButtonDetector > m_mouseButtons
std::unique_ptr< CPointerDetector > m_pointer
std::chrono::time_point< std::chrono::steady_clock > m_lastAction
uint64_t m_frameCount = 0
Detailed Description
Generic implementation of a class that provides button mapping by translating driver events to button mapping commands.
Button mapping commands are invoked instantly for buttons and hats.
Button mapping commands are deferred for a short while after an axis is activated, and only one button mapping command will be invoked per activation.
Constructor & Destructor Documentation
CButtonMapping()
CButtonMapping::CButtonMapping (IButtonMapper * buttonMapper, IButtonMap * buttonMap, KEYMAP::IKeymap * keymap)
Constructor for CButtonMapping.
Parameters
buttonMapper Carries out button-mapping commands using <buttonMap>
buttonMap The button map given to <buttonMapper> on each command
References ACTION_SELECT_ITEM, actions, KODI::JOYSTICK::AxisConfiguration::bKnown, KODI::JOYSTICK::CDriverPrimitive::Center(), KODI::JOYSTICK::AxisConfiguration::center, KODI::KEYMAP::IKeymap::ControllerID(), KODI::KEYMAP::IKeymap::GetActions(), GetAxis(), CServiceBroker::GetGameControllerManager(), KODI::JOYSTICK::IButtonMap::GetScalar(), KODI::JOYSTICK::CDriverPrimitive::Index(), m_buttonMap, m_buttonMapper, m_keymap, KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), KODI::JOYSTICK::CDriverPrimitive::Range(), KODI::JOYSTICK::AxisConfiguration::range, KODI::JOYSTICK::SEMIAXIS, KODI::JOYSTICK::CAxisDetector::SetEmitted(), and KODI::JOYSTICK::CDriverPrimitive::Type().
~CButtonMapping()
KODI::JOYSTICK::CButtonMapping::~CButtonMapping () override default
Member Function Documentation
GetAxis()
CAxisDetector & CButtonMapping::GetAxis (unsigned int axisIndex, float position, const AxisConfiguration & initialConfig = AxisConfiguration()) private
References KODI::JOYSTICK::AxisConfiguration::bLateDiscovery, CLog::Log(), LOGDEBUG, m_axes, m_frameCount, and OnLateDiscovery().
Referenced by CButtonMapping(), and OnAxisMotion().
GetButton()
CButtonDetector & CButtonMapping::GetButton (unsigned int buttonIndex) private
References m_buttons.
Referenced by OnButtonMotion().
GetHat()
CHatDetector & CButtonMapping::GetHat (unsigned int hatIndex) private
References m_hats.
Referenced by OnHatMotion().
GetKey()
CKeyDetector & CButtonMapping::GetKey (XBMCKey keycode) private
References m_keys.
Referenced by OnKeyPress().
GetMouseButton()
CMouseButtonDetector & CButtonMapping::GetMouseButton (MOUSE::BUTTON_ID buttonIndex) private
References m_mouseButtons.
Referenced by OnButtonPress(), and OnButtonRelease().
GetPointer()
CPointerDetector & CButtonMapping::GetPointer () private
References m_pointer.
Referenced by OnPosition().
IsMapping()
bool CButtonMapping::IsMapping () const private
References m_axes.
Referenced by OnInputFrame().
MapPrimitive()
bool CButtonMapping::MapPrimitive (const CDriverPrimitive & primitive)
Process the primitive mapping command.
First, this function checks if the input should be dropped. This can happen if the input is ignored or the cooldown period is active. If the input is dropped, this returns true with no effect, effectively absorbing the input. Otherwise, the mapping command is sent to m_buttonMapper.
Parameters
primitive The primitive being mapped
Returns
True if the mapping command was handled, false otherwise
References KODI::JOYSTICK::IButtonMapper::ControllerID(), KODI::JOYSTICK::IButtonMap::IsIgnored(), CLog::Log(), LOGDEBUG, m_buttonMap, m_buttonMapper, m_keymap, m_lastAction, MAPPING_COOLDOWN_MS, KODI::JOYSTICK::IButtonMapper::MapPrimitive(), and KODI::JOYSTICK::IButtonMapper::NeedsCooldown().
Referenced by KODI::JOYSTICK::CPrimitiveDetector::MapPrimitive().
OnAxisMotion()
bool CButtonMapping::OnAxisMotion (unsigned int axisIndex, float position, int center, unsigned int range) override virtual
Handle axis motion.
If a joystick feature requires multiple axes (analog sticks, accelerometers), they can be buffered for later processing.
Parameters
axisIndex The index of the axis as reported by the driver
position The position of the axis in the closed interval [-1.0, 1.0]
center The center point of the axis (either -1, 0 or 1)
range The maximum distance the axis can move (either 1 or 2)
Returns
True if the motion was handled, false otherwise
Implements KODI::JOYSTICK::IDriverHandler.
References KODI::JOYSTICK::IButtonMapper::AcceptsPrimitive(), GetAxis(), m_buttonMapper, KODI::JOYSTICK::CAxisDetector::OnMotion(), and KODI::JOYSTICK::SEMIAXIS.
OnButtonMotion()
bool CButtonMapping::OnButtonMotion (unsigned int buttonIndex, bool bPressed) override virtual
Handle button motion.
Parameters
buttonIndex The index of the button as reported by the driver
bPressed true for press motion, false for release motion
Returns
True if a press was handled, false otherwise
Implements KODI::JOYSTICK::IDriverHandler.
References KODI::JOYSTICK::IButtonMapper::AcceptsPrimitive(), KODI::JOYSTICK::BUTTON, GetButton(), m_buttonMapper, and KODI::JOYSTICK::CButtonDetector::OnMotion().
OnButtonPress()
bool CButtonMapping::OnButtonPress (MOUSE::BUTTON_ID button) override virtual
A mouse button has been pressed.
Parameters
button The index of the pressed button
Returns
True if the event was handled, otherwise false
Implements KODI::MOUSE::IMouseDriverHandler.
References KODI::JOYSTICK::IButtonMapper::AcceptsPrimitive(), GetMouseButton(), m_buttonMapper, KODI::JOYSTICK::MOUSE_BUTTON, and KODI::JOYSTICK::CMouseButtonDetector::OnMotion().
OnButtonRelease()
void CButtonMapping::OnButtonRelease (MOUSE::BUTTON_ID button) override virtual
A mouse button has been released.
Parameters
button The index of the released button
Implements KODI::MOUSE::IMouseDriverHandler.
References KODI::JOYSTICK::IButtonMapper::AcceptsPrimitive(), GetMouseButton(), m_buttonMapper, KODI::JOYSTICK::MOUSE_BUTTON, and KODI::JOYSTICK::CMouseButtonDetector::OnMotion().
OnHatMotion()
bool CButtonMapping::OnHatMotion (unsigned int hatIndex, HAT_STATE state) override virtual
Handle hat motion.
Parameters
hatIndex The index of the hat as reported by the driver
state The direction the hat is now being pressed
Returns
True if the new direction was handled, false otherwise
Implements KODI::JOYSTICK::IDriverHandler.
References KODI::JOYSTICK::IButtonMapper::AcceptsPrimitive(), GetHat(), KODI::JOYSTICK::HAT, m_buttonMapper, and KODI::JOYSTICK::CHatDetector::OnMotion().
OnInputFrame()
void CButtonMapping::OnInputFrame () override virtual
Handle buffered input motion for features that require multiple axes.
OnInputFrame() is called at the end of the frame when all axis motions have been reported. This has several uses, including:
Combining multiple axes into a single analog stick or accelerometer event
Imitating an analog feature with a digital button so that events can be dispatched every frame.
Implements KODI::JOYSTICK::IDriverHandler.
References IsMapping(), m_axes, m_buttonMap, m_buttonMapper, m_frameCount, and KODI::JOYSTICK::IButtonMapper::OnEventFrame().
OnKeyPress()
bool CButtonMapping::OnKeyPress (const CKey & key) override virtual
A key has been pressed.
Parameters
key The pressed key
Returns
True if the event was handled, false otherwise
Implements KODI::KEYBOARD::IKeyboardDriverHandler.
References KODI::JOYSTICK::IButtonMapper::AcceptsPrimitive(), GetKey(), CKey::GetKeycode(), KODI::JOYSTICK::KEY, m_buttonMapper, and KODI::JOYSTICK::CKeyDetector::OnMotion().
OnKeyRelease()
void KODI::JOYSTICK::CButtonMapping::OnKeyRelease (const CKey & key) inline override virtual
A key has been released.
Parameters
key The released key
Implements KODI::KEYBOARD::IKeyboardDriverHandler.
OnLateDiscovery()
void CButtonMapping::OnLateDiscovery (unsigned int axisIndex) private
References m_buttonMap, m_buttonMapper, and KODI::JOYSTICK::IButtonMapper::OnLateAxis().
Referenced by GetAxis().
OnPosition()
bool CButtonMapping::OnPosition (int x, int y) override virtual
Handle mouse position updates.
Parameters
x The new x coordinate of the pointer
y The new y coordinate of the pointer
The mouse uses a left-handed (graphics) cartesian coordinate system. Positive X is right, positive Y is down.
Returns
True if the event was handled, false otherwise
Implements KODI::MOUSE::IMouseDriverHandler.
References KODI::JOYSTICK::IButtonMapper::AcceptsPrimitive(), GetPointer(), m_buttonMapper, KODI::JOYSTICK::CPointerDetector::OnMotion(), and KODI::JOYSTICK::RELATIVE_POINTER.
ResetIgnoredPrimitives()
void CButtonMapping::ResetIgnoredPrimitives () override virtual
Clear the list of ignored driver primitives.
Called if the user begins capturing primitives to be ignored, and no primitives are captured before the dialog is accepted by the user.
In this case, the button mapper won't have been given access to the button map, so a callback is needed to indicate that no primitives were captured and the user accepted this.
Implements KODI::JOYSTICK::IButtonMapCallback.
References m_buttonMap, and KODI::JOYSTICK::IButtonMap::SetIgnoredPrimitives().
RevertButtonMap()
void CButtonMapping::RevertButtonMap () override virtual
Revert changes to the button map since the last time it was loaded or committed to disk.
Implements KODI::JOYSTICK::IButtonMapCallback.
References m_buttonMap, and KODI::JOYSTICK::IButtonMap::RevertButtonMap().
SaveButtonMap()
void CButtonMapping::SaveButtonMap () override virtual
Save the button map.
Implements KODI::JOYSTICK::IButtonMapCallback.
References m_buttonMap, and KODI::JOYSTICK::IButtonMap::SaveButtonMap().
Member Data Documentation
m_axes
std::map<unsigned int, CAxisDetector> KODI::JOYSTICK::CButtonMapping::m_axes private
Referenced by GetAxis(), IsMapping(), and OnInputFrame().
m_buttonMap
IButtonMap* const KODI::JOYSTICK::CButtonMapping::m_buttonMap private
Referenced by CButtonMapping(), MapPrimitive(), OnInputFrame(), OnLateDiscovery(), ResetIgnoredPrimitives(), RevertButtonMap(), and SaveButtonMap().
m_buttonMapper
IButtonMapper* const KODI::JOYSTICK::CButtonMapping::m_buttonMapper private
Referenced by CButtonMapping(), MapPrimitive(), OnAxisMotion(), OnButtonMotion(), OnButtonPress(), OnButtonRelease(), OnHatMotion(), OnInputFrame(), OnKeyPress(), OnLateDiscovery(), and OnPosition().
m_buttons
std::map<unsigned int, CButtonDetector> KODI::JOYSTICK::CButtonMapping::m_buttons private
Referenced by GetButton().
m_frameCount
uint64_t KODI::JOYSTICK::CButtonMapping::m_frameCount = 0 private
Referenced by GetAxis(), and OnInputFrame().
m_hats
std::map<unsigned int, CHatDetector> KODI::JOYSTICK::CButtonMapping::m_hats private
Referenced by GetHat().
m_keymap
KEYMAP::IKeymap* const KODI::JOYSTICK::CButtonMapping::m_keymap private
Referenced by CButtonMapping(), and MapPrimitive().
m_keys
std::map<XBMCKey, CKeyDetector> KODI::JOYSTICK::CButtonMapping::m_keys private
Referenced by GetKey().
m_lastAction
std::chrono::time_point<std::chrono::steady_clock> KODI::JOYSTICK::CButtonMapping::m_lastAction private
Referenced by MapPrimitive().
m_mouseButtons
std::map<MOUSE::BUTTON_ID, CMouseButtonDetector> KODI::JOYSTICK::CButtonMapping::m_mouseButtons private
Referenced by GetMouseButton().
m_pointer
std::unique_ptr<CPointerDetector> KODI::JOYSTICK::CButtonMapping::m_pointer private
Referenced by GetPointer().
The documentation for this class was generated from the following files:
ButtonMapping.h
ButtonMapping.cpp