Kodi Documentation: KODI::GAME::CPortInput Class Reference
KODI::GAME::CPortInput Class Reference
Games
#include <PortInput.h>
Public Member Functions
CPortInput (JOYSTICK::IInputHandler *gameInput)
~CPortInput () override
void RegisterInput (JOYSTICK::IInputProvider *provider)
void UnregisterInput (JOYSTICK::IInputProvider *provider)
float GetActivation () const
std::string ControllerID () const override
The add-on ID of the game controller associated with this input handler.
bool HasFeature (const std::string &feature) const override
Return true if the input handler accepts the given feature.
bool AcceptsInput (const std::string &feature) const override
Return true if the input handler is currently accepting input for the given feature.
bool OnButtonPress (const std::string &feature, bool bPressed) override
A digital button has been pressed or released.
void OnButtonHold (const std::string &feature, unsigned int holdTimeMs) override
A digital button has been pressed for more than one event frame.
bool OnButtonMotion (const std::string &feature, float magnitude, unsigned int motionTimeMs) override
An analog button (trigger or a pressure-sensitive button) has changed state.
bool OnAnalogStickMotion (const std::string &feature, float x, float y, unsigned int motionTimeMs) override
An analog stick has moved.
bool OnAccelerometerMotion (const std::string &feature, float x, float y, float z) override
An accelerometer's state has changed.
bool OnWheelMotion (const std::string &feature, float position, unsigned int motionTimeMs) override
A wheel has changed state.
bool OnThrottleMotion (const std::string &feature, float position, unsigned int motionTimeMs) override
A throttle has changed state.
void OnInputFrame () override
Called at the end of the frame that provided input.
int GetWindowID () const override
Get the window ID for which actions should be translated.
void SetWindowID (int windowId) override
Set the window ID.
int GetFallthrough (int windowId) const override
Get the fallthrough window to when a key definition is missing.
bool UseGlobalFallthrough () const override
Specify if the global keymap should be used when the window and fallback window are undefined.
bool UseEasterEgg () const override
Specify if the agent should monitor for easter egg presses.
Public Member Functions inherited from KODI::JOYSTICK::IInputHandler
virtual ~IInputHandler ()=default
void SetInputReceiver (IInputReceiver *receiver)
void ResetInputReceiver (void)
IInputReceiver * InputReceiver (void)
Public Member Functions inherited from KODI::KEYMAP::IKeymapEnvironment
virtual ~IKeymapEnvironment ()=default
Private Attributes
JOYSTICK::IInputHandler *const m_gameInput
std::unique_ptr< KEYMAP::CKeymapHandling > m_appInput
std::unique_ptr< JOYSTICK::IInputHandler > m_inputSink
std::unique_ptr< CControllerActivity > m_controllerActivity
Constructor & Destructor Documentation
CPortInput()
CPortInput::CPortInput (JOYSTICK::IInputHandler * gameInput)
~CPortInput()
CPortInput::~CPortInput () override default
Member Function Documentation
AcceptsInput()
bool CPortInput::AcceptsInput (const std::string & feature) const override virtual
Return true if the input handler is currently accepting input for the given feature.
Parameters
feature A feature belonging to the controller specified by ControllerID()
Returns
True if the feature is currently accepting input, false otherwise
This does not prevent the input events from being called, but can return false to indicate that input wasn't handled for the specified feature.
Implements KODI::JOYSTICK::IInputHandler.
References KODI::JOYSTICK::IInputHandler::AcceptsInput(), and m_gameInput.
ControllerID()
std::string CPortInput::ControllerID () const override virtual
The add-on ID of the game controller associated with this input handler.
Returns
The ID of the add-on extending kodi.game.controller
Implements KODI::JOYSTICK::IInputHandler.
References KODI::JOYSTICK::IInputHandler::ControllerID(), and m_gameInput.
GetActivation()
float CPortInput::GetActivation () const
References m_controllerActivity.
GetFallthrough()
int KODI::GAME::CPortInput::GetFallthrough (int windowId) const inline override virtual
Get the fallthrough window to when a key definition is missing.
Parameters
windowId The window ID
Returns
The window ID, or -1 for no fallthrough
Implements KODI::KEYMAP::IKeymapEnvironment.
GetWindowID()
int CPortInput::GetWindowID () const override virtual
Get the window ID for which actions should be translated.
Returns
The window ID
Implements KODI::KEYMAP::IKeymapEnvironment.
References WINDOW_FULLSCREEN_GAME.
HasFeature()
bool KODI::GAME::CPortInput::HasFeature (const std::string & feature) const inline override virtual
Return true if the input handler accepts the given feature.
Parameters
feature A feature belonging to the controller specified by ControllerID()
Returns
True if the feature is used for input, false otherwise
Implements KODI::JOYSTICK::IInputHandler.
OnAccelerometerMotion()
bool CPortInput::OnAccelerometerMotion (const std::string & feature, float x, float y, float z) override virtual
An accelerometer's state has changed.
Parameters
feature The accelerometer being accelerated
x The x coordinate in the closed interval [-1, 1]
y The y coordinate in the closed interval [-1, 1]
z The z coordinate in the closed interval [-1, 1]
Returns
True if the event was handled otherwise false
Reimplemented from KODI::JOYSTICK::IInputHandler.
References KODI::JOYSTICK::IInputHandler::AcceptsInput(), m_gameInput, and KODI::JOYSTICK::IInputHandler::OnAccelerometerMotion().
OnAnalogStickMotion()
bool CPortInput::OnAnalogStickMotion (const std::string & feature, float x, float y, unsigned int motionTimeMs) override virtual
An analog stick has moved.
Parameters
feature The analog stick being moved
x The x coordinate in the closed interval [-1, 1]
y The y coordinate in the closed interval [-1, 1]
motionTimeMs The time elapsed since this analog stick was centered, or 0 if the analog stick is centered
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References KODI::JOYSTICK::IInputHandler::AcceptsInput(), m_controllerActivity, m_gameInput, and KODI::JOYSTICK::IInputHandler::OnAnalogStickMotion().
OnButtonHold()
void CPortInput::OnButtonHold (const std::string & feature, unsigned int holdTimeMs) override virtual
A digital button has been pressed for more than one event frame.
Parameters
feature The feature being held
holdTimeMs The time elapsed since the initial press (ms)
If OnButtonPress() returns true for the initial press, then this callback is invoked on subsequent frames until the button is released.
Implements KODI::JOYSTICK::IInputHandler.
References m_controllerActivity, m_gameInput, and KODI::JOYSTICK::IInputHandler::OnButtonHold().
OnButtonMotion()
bool CPortInput::OnButtonMotion (const std::string & feature, float magnitude, unsigned int motionTimeMs) override virtual
An analog button (trigger or a pressure-sensitive button) has changed state.
Parameters
feature The feature changing state
magnitude The button pressure or trigger travel distance in the closed interval [0, 1]
motionTimeMs The time elapsed since the magnitude was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References KODI::JOYSTICK::IInputHandler::AcceptsInput(), m_controllerActivity, m_gameInput, and KODI::JOYSTICK::IInputHandler::OnButtonMotion().
OnButtonPress()
bool CPortInput::OnButtonPress (const std::string & feature, bool bPressed) override virtual
A digital button has been pressed or released.
Parameters
feature The feature being pressed
bPressed True if pressed, false if released
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References KODI::JOYSTICK::IInputHandler::AcceptsInput(), m_controllerActivity, m_gameInput, and KODI::JOYSTICK::IInputHandler::OnButtonPress().
OnInputFrame()
void CPortInput::OnInputFrame () override virtual
Called at the end of the frame that provided input.
Implements KODI::JOYSTICK::IInputHandler.
References m_controllerActivity.
OnThrottleMotion()
bool CPortInput::OnThrottleMotion (const std::string & feature, float position, unsigned int motionTimeMs) override virtual
A throttle has changed state.
Up is positive position, down is negative position.
Parameters
feature The wheel changing state
position The position in the closed interval [-1, 1]
motionTimeMs The time elapsed since the position was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References KODI::JOYSTICK::IInputHandler::AcceptsInput(), m_controllerActivity, m_gameInput, and KODI::JOYSTICK::IInputHandler::OnThrottleMotion().
OnWheelMotion()
bool CPortInput::OnWheelMotion (const std::string & feature, float position, unsigned int motionTimeMs) override virtual
A wheel has changed state.
Left is negative position, right is positive position
Parameters
feature The wheel changing state
position The position in the closed interval [-1, 1]
motionTimeMs The time elapsed since the position was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References KODI::JOYSTICK::IInputHandler::AcceptsInput(), m_controllerActivity, m_gameInput, and KODI::JOYSTICK::IInputHandler::OnWheelMotion().
RegisterInput()
void CPortInput::RegisterInput (JOYSTICK::IInputProvider * provider)
References m_appInput, m_inputSink, and KODI::JOYSTICK::IInputProvider::RegisterInputHandler().
SetWindowID()
void KODI::GAME::CPortInput::SetWindowID (int windowId) inline override virtual
Set the window ID.
Parameters
The window ID, used for translating actions
Implements KODI::KEYMAP::IKeymapEnvironment.
UnregisterInput()
void CPortInput::UnregisterInput (JOYSTICK::IInputProvider * provider)
References m_appInput, m_inputSink, and KODI::JOYSTICK::IInputProvider::UnregisterInputHandler().
UseEasterEgg()
bool KODI::GAME::CPortInput::UseEasterEgg () const inline override virtual
Specify if the agent should monitor for easter egg presses.
Implements KODI::KEYMAP::IKeymapEnvironment.
UseGlobalFallthrough()
bool KODI::GAME::CPortInput::UseGlobalFallthrough () const inline override virtual
Specify if the global keymap should be used when the window and fallback window are undefined.
Implements KODI::KEYMAP::IKeymapEnvironment.
Member Data Documentation
m_appInput
std::unique_ptr<KEYMAP::CKeymapHandling> KODI::GAME::CPortInput::m_appInput private
Referenced by RegisterInput(), and UnregisterInput().
m_controllerActivity
std::unique_ptr<CControllerActivity> KODI::GAME::CPortInput::m_controllerActivity private
Referenced by GetActivation(), OnAnalogStickMotion(), OnButtonHold(), OnButtonMotion(), OnButtonPress(), OnInputFrame(), OnThrottleMotion(), and OnWheelMotion().
m_gameInput
JOYSTICK::IInputHandler* const KODI::GAME::CPortInput::m_gameInput private
Referenced by AcceptsInput(), ControllerID(), OnAccelerometerMotion(), OnAnalogStickMotion(), OnButtonHold(), OnButtonMotion(), OnButtonPress(), OnThrottleMotion(), and OnWheelMotion().
m_inputSink
std::unique_ptr<JOYSTICK::IInputHandler> KODI::GAME::CPortInput::m_inputSink private
Referenced by RegisterInput(), and UnregisterInput().
The documentation for this class was generated from the following files:
PortInput.h
PortInput.cpp