Kodi Documentation: CThread Class Reference
CThread Class Reference
#include <Thread.h>
Public Member Functions
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Static Public Member Functions
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
virtual void Process ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes
std::atomic< bool > m_bStop
Private Member Functions
void Action ()
Private Attributes
bool m_bAutoDelete = false
CEvent m_StopEvent
CEvent m_StartEvent
CCriticalSection m_CriticalSection
IRunnable * m_pRunnable
std::string m_ThreadName
std::thread * m_thread = nullptr
std::future< bool > m_future
std::unique_ptr< IThreadImpl > m_impl
Member Enumeration Documentation
WaitResponse
enum CThread::WaitResponse protected
Enumerator
WAIT_INTERRUPTED
WAIT_SIGNALED
WAIT_TIMEDOUT
Constructor & Destructor Documentation
CThread() [1/2]
CThread::CThread (const char * ThreadName) explicit protected
References m_ThreadName.
CThread() [2/2]
CThread::CThread (IRunnable * pRunnable, const char * ThreadName)
References m_ThreadName.
~CThread()
CThread::~CThread () virtual
References m_thread, and StopThread().
Member Function Documentation
AbortableWait()
WaitResponse CThread::AbortableWait (CEvent & event, std::chrono::milliseconds duration = std::chrono::milliseconds(-1)) inline protected
This call will wait on a CEvent in an interruptible way such that if stop is called on the thread the wait will return with a response indicating what happened.
References m_StopEvent, WAIT_INTERRUPTED, WAIT_SIGNALED, and WAIT_TIMEDOUT.
Referenced by CIRServerSuite::Process(), XFILE::CFileCache::Process(), CBackgroundPicLoader::Process(), and CWin32PowerStateWorker::Process().
Action()
void CThread::Action () private
References IsAutoDelete(), OnExit(), OnStartup(), and Process().
Referenced by Create().
Create()
void CThread::Create (bool bAutoDelete = false)
References Action(), IThreadImpl::CreateThreadImpl(), currentThread, CLog::Log(), LOGDEBUG, LOGERROR, m_bAutoDelete, m_bStop, m_CriticalSection, m_future, m_impl, m_StartEvent, m_StopEvent, m_thread, m_ThreadName, CEvent::Reset(), CEvent::Set(), StopThread(), and CEvent::Wait().
Referenced by CRssReader::AddToQueue(), ADDON::CAddonStatusHandler::CAddonStatusHandler(), CGUIDialogCache::CGUIDialogCache(), CJobWorker::CJobWorker(), CUdpClient::Create(), CBackgroundPicLoader::Create(), KODI::RETRO::CRetroPlayerAutoSave::CRetroPlayerAutoSave(), CRunningScriptObserver::CRunningScriptObserver(), CWin32PowerSyscall::CWin32PowerSyscall(), CWinEventsAndroid::CWinEventsAndroid(), CWinEventsOSX::CWinEventsOSX(), CWinEventsTVOS::CWinEventsTVOS(), CZeroconfMDNS::CZeroconfMDNS(), KODI::JOYSTICK::CRumbleGenerator::DoTest(), CLanguageInvokerThread::execute(), MUSIC_GRABBER::CMusicInfoScraper::FindAlbumInfo(), MUSIC_GRABBER::CMusicInfoScraper::FindArtistInfo(), CVideoInfoDownloader::FindMovie(), CVideoInfoDownloader::GetDetails(), CVideoInfoDownloader::GetEpisodeDetails(), CVideoInfoDownloader::GetEpisodeList(), PERIPHERALS::CPeripheralBus::Initialise(), CIRServerSuite::Initialize(), KODI::GAME::CControllerSelect::Initialize(), XFILE::CShoutcastFile::IoControl(), CBackgroundInfoLoader::Load(), MUSIC_GRABBER::CMusicInfoScraper::LoadAlbumInfo(), MUSIC_GRABBER::CMusicInfoScraper::LoadArtistInfo(), KODI::JOYSTICK::CRumbleGenerator::NotifyUser(), CGUIDialogKeyboardTouch::OnInitWindow(), XFILE::CFileCache::Open(), CExternalPlayer::OpenFile(), PAPlayer::OpenFile(), CVideoPlayer::OpenFile(), UPNP::CUPnPPlayer::OpenFile(), CVideoPlayerVideo::OpenStream(), CVideoPlayerAudio::OpenStream(), CVideoPlayerAudioID3::OpenStream(), CDVDRadioRDSData::OpenStream(), CDVDTeletextData::OpenStream(), MUSIC_INFO::CMusicInfoScanner::Process(), CAirTunesServer::RegisterActionListener(), KODI::GAME::CGUIConfigurationWizard::Run(), KODI::GAME::CGUIDialogButtonCapture::Show(), KODI::JOYSTICK::CGUIDialogNewJoystick::ShowAsync(), ActiveAE::CActiveAESink::Start(), KODI::RETRO::CGameLoop::Start(), VAAPI::COutput::Start(), VDPAU::CMixer::Start(), VDPAU::COutput::Start(), CVideoReferenceClock::Start(), ANNOUNCEMENT::CAnnouncementManager::Start(), PERIPHERALS::CEventScanner::Start(), CLibInputHandler::Start(), CLirc::Start(), WSDiscovery::CWSDiscoveryListenerUDP::Start(), PVR::CPVREpgContainer::Start(), PVR::CPVRGUIInfo::Start(), PVR::CPVRManager::Start(), PVR::CPVRTimers::Start(), ActiveAE::CActiveAE::Start(), CAlarmClock::Start(), CTimer::Start(), CFDEventMonitor::StartMonitoring(), EVENTSERVER::CEventServer::StartServer(), CAirPlayServer::StartServer(), JSONRPC::CTCPServer::StartServer(), PVR::CPVRGUIProgressHandler::UpdateProgress(), CBusyWaiter::Wait(), and CWIN32Util::XBMCShellExecute().
GetCurrentThread()
CThread * CThread::GetCurrentThread () static
References currentThread.
Referenced by ff_avutil_log(), and CVideoSyncGbm::Run().
GetCurrentThreadId()
static const std::thread::id CThread::GetCurrentThreadId () inline static
Referenced by CApplication::Create(), KODI::MESSAGING::CApplicationMessenger::IsProcessThread(), and KODI::MESSAGING::CApplicationMessenger::SendMsg().
IsAutoDelete()
bool CThread::IsAutoDelete () const
References m_bAutoDelete.
Referenced by Action(), and CJobWorker::~CJobWorker().
IsCurrentThread()
bool CThread::IsCurrentThread () const
References currentThread.
Referenced by Join(), Sleep(), StopThread(), and CVideoPlayer::SynchronizeDemuxer().
IsRunning()
bool CThread::IsRunning () const
References m_future, and m_thread.
Referenced by KODI::JOYSTICK::CRumbleGenerator::DoTest(), CLanguageInvokerThread::execute(), CVideoInfoDownloader::FindMovie(), CVideoInfoDownloader::GetDetails(), CVideoInfoDownloader::GetEpisodeDetails(), CVideoInfoDownloader::GetEpisodeList(), PERIPHERALS::CPeripheralBus::Initialise(), VDPAU::CMixer::IsActive(), CTimer::IsRunning(), KODI::JOYSTICK::CRumbleGenerator::NotifyUser(), PAPlayer::OpenFile(), CVideoPlayer::OpenFile(), UPNP::CUPnPPlayer::OpenFile(), CWin32PowerStateWorker::QueryStateChange(), XFILE::CFileCache::Seek(), KODI::GAME::CGUIDialogButtonCapture::Show(), KODI::JOYSTICK::CGUIDialogNewJoystick::ShowAsync(), ActiveAE::CActiveAESink::Start(), CVideoReferenceClock::Start(), WSDiscovery::CWSDiscoveryListenerUDP::Start(), CFDEventMonitor::StartMonitoring(), CLanguageInvokerThread::stop(), and CWin32PowerSyscall::~CWin32PowerSyscall().
Join()
bool CThread::Join (std::chrono::milliseconds duration)
References IsCurrentThread(), m_CriticalSection, m_future, and m_thread.
Referenced by MUSIC_GRABBER::CMusicInfoScraper::Completed(), and StopThread().
OnException()
virtual void CThread::OnException () inline virtual
Reimplemented in CLanguageInvokerThread.
OnExit()
virtual void CThread::OnExit () inline protected virtual
Reimplemented in CWHelper, ADDON::CAddonStatusHandler, PAPlayer, VAAPI::COutput, VDPAU::CMixer, VDPAU::COutput, CVideoPlayer, CVideoPlayerAudio, CVideoPlayerAudioID3, CDVDRadioRDSData, CDVDTeletextData, CVideoPlayerVideo, XFILE::CFileCache, CLanguageInvokerThread, UPNP::CUPnPPlayer, and CRssReader.
Referenced by Action().
OnStartup()
virtual void CThread::OnStartup () inline protected virtual
Reimplemented in CWin32PowerStateWorker, CWHelper, ADDON::CAddonStatusHandler, PAPlayer, VAAPI::COutput, VDPAU::CMixer, VDPAU::COutput, CVideoPlayer, CVideoPlayerAudio, CLanguageInvokerThread, MUSIC_GRABBER::CMusicInfoScraper, and CUdpClient.
Referenced by Action().
Process()
void CThread::Process (void) protected virtual
Reimplemented in CZeroconfMDNS, CIRServerSuite, CWHelper, ADDON::CAddonStatusHandler, ActiveAE::CActiveAE, ActiveAE::CActiveAESink, CExternalPlayer, PAPlayer, KODI::RETRO::CGameLoop, KODI::RETRO::CRetroPlayerAutoSave, VAAPI::COutput, VDPAU::CMixer, VDPAU::COutput, CVideoPlayer, CVideoPlayerAudio, CVideoPlayerAudioID3, CDVDRadioRDSData, CDVDTeletextData, CVideoPlayerVideo, CVideoReferenceClock, CBusyWaiter, CGUIDialogCache, CGUIDialogKeyboardTouch, XFILE::CFileCache, XFILE::CShoutcastFile, KODI::GAME::CControllerInstaller, KODI::GAME::CControllerSelect, KODI::GAME::CGUIDialogButtonCapture, KODI::GAME::CGUIConfigurationWizard, KODI::JOYSTICK::CGUIDialogNewJoystick, KODI::JOYSTICK::CRumbleGenerator, ANNOUNCEMENT::CAnnouncementManager, CLanguageInvokerThread, KODI::MESSAGING::CDelayedMessage, MUSIC_GRABBER::CMusicInfoScraper, CAirPlayServer, CAirTunesServer, EVENTSERVER::CEventServer, JSONRPC::CTCPServer, CUdpClient, UPNP::CUPnPPlayer, PERIPHERALS::CEventScanner, CBackgroundPicLoader, CFDEventMonitor, CLibInputHandler, CLirc, WSDiscovery::CWSDiscoveryListenerUDP, PVR::CPVREpgContainer, PVR::CPVRGUIInfo, PVR::CPVRGUIProgressHandler, PVR::CPVRManager, PVR::CPVRTimers, PVR::CPVRRefreshTimelineItemsThread, CTimer, CAlarmClock, CJobWorker, CRssReader, CVideoInfoDownloader, CWinEventsAndroid, anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread, CWin32PowerStateWorker, PERIPHERALS::CPeripheralBus, and PERIPHERALS::CPeripheralBusUSB.
References m_pRunnable, and IRunnable::Run().
Referenced by Action(), and CBusyWaiter::Process().
SetPriority()
bool CThread::SetPriority (const ThreadPriority & priority)
Set the threads priority. This uses the platforms native threading library to do so.
References m_impl.
Referenced by PERIPHERALS::CPeripheralBus::Initialise(), CIRServerSuite::Initialize(), CBackgroundInfoLoader::Load(), CWin32PowerStateWorker::OnStartup(), ADDON::CAddonStatusHandler::OnStartup(), CUdpClient::OnStartup(), ANNOUNCEMENT::CAnnouncementManager::Process(), PVR::CPVREpgContainer::Process(), CJobWorker::Process(), CVideoSyncGbm::Run(), ActiveAE::CActiveAESink::Start(), CLibInputHandler::Start(), CLirc::Start(), WSDiscovery::CWSDiscoveryListenerUDP::Start(), PVR::CPVREpgContainer::Start(), PVR::CPVRGUIInfo::Start(), and PVR::CPVRManager::Start().
Sleep()
template<typename Rep , typename Period > void CThread::Sleep (std::chrono::duration< Rep, Period > duration) inline
References IsCurrentThread(), m_StopEvent, and CEvent::Wait().
Referenced by WSDiscovery::CWSDiscoveryListenerUDP::DispatchCommand(), ActiveAE::CActiveAESink::EnumerateSinkList(), CVideoInfoDownloader::FindMovie(), CVideoInfoDownloader::GetDetails(), CVideoInfoDownloader::GetEpisodeDetails(), CVideoInfoDownloader::GetEpisodeList(), CVideoPlayerVideo::OutputPicture(), ActiveAE::CActiveAESink::OutputSamples(), PAPlayer::PrepareStream(), CExternalPlayer::Process(), PAPlayer::Process(), KODI::RETRO::CRetroPlayerAutoSave::Process(), CVideoPlayer::Process(), CVideoPlayerAudio::Process(), CGUIDialogCache::Process(), XFILE::CShoutcastFile::Process(), KODI::JOYSTICK::CRumbleGenerator::Process(), KODI::MESSAGING::CDelayedMessage::Process(), CAirPlayServer::Process(), EVENTSERVER::CEventServer::Process(), JSONRPC::CTCPServer::Process(), CUdpClient::Process(), CLirc::Process(), PVR::CPVREpgContainer::Process(), PVR::CPVRGUIInfo::Process(), PVR::CPVRGUIProgressHandler::Process(), PVR::CPVRTimers::Process(), CAlarmClock::Process(), CRssReader::Process(), CWinEventsAndroid::Process(), PAPlayer::QueueNextFileEx(), PAPlayer::SoftStart(), PAPlayer::SoftStop(), ActiveAE::CActiveAESink::StateMachine(), PVR::CPVRManager::UpdateComponents(), and CVideoPlayer::~CVideoPlayer().
StopThread()
void CThread::StopThread (bool bWait = true) virtual
Reimplemented in XFILE::CFileCache.
References IsCurrentThread(), Join(), m_bStop, m_CriticalSection, m_StartEvent, m_StopEvent, m_thread, CEvent::Set(), and CEvent::Wait().
Referenced by CRunningScriptObserver::Abort(), KODI::GAME::CGUIConfigurationWizard::Abort(), KODI::JOYSTICK::CRumbleGenerator::AbortRumble(), CRssReader::AddToQueue(), PERIPHERALS::CPeripheralBus::Clear(), PERIPHERALS::CPeripheralBusUSB::Clear(), XFILE::CShoutcastFile::Close(), PAPlayer::CloseFile(), CVideoPlayer::CloseFile(), UPNP::CUPnPPlayer::CloseFile(), CVideoPlayerAudio::CloseStream(), CVideoPlayerAudioID3::CloseStream(), CDVDRadioRDSData::CloseStream(), CDVDTeletextData::CloseStream(), CVideoPlayerVideo::CloseStream(), CVideoInfoDownloader::CloseThread(), Create(), KODI::GAME::CControllerSelect::Deinitialize(), ANNOUNCEMENT::CAnnouncementManager::Deinitialize(), CUdpClient::Destroy(), ActiveAE::CActiveAE::Dispose(), ActiveAE::CActiveAESink::Dispose(), VAAPI::COutput::Dispose(), VDPAU::CMixer::Dispose(), VDPAU::COutput::Dispose(), KODI::JOYSTICK::CRumbleGenerator::DoTest(), MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), MUSIC_GRABBER::CMusicInfoScraper::FindAlbumInfo(), MUSIC_GRABBER::CMusicInfoScraper::FindArtistInfo(), CVideoInfoDownloader::FindMovie(), CVideoInfoDownloader::GetDetails(), CVideoInfoDownloader::GetEpisodeDetails(), CVideoInfoDownloader::GetEpisodeList(), MUSIC_GRABBER::CMusicInfoScraper::LoadAlbumInfo(), MUSIC_GRABBER::CMusicInfoScraper::LoadArtistInfo(), KODI::JOYSTICK::CRumbleGenerator::NotifyUser(), PAPlayer::OpenFile(), CVideoPlayerVideo::OpenStream(), MUSIC_INFO::CMusicInfoScanner::Process(), CFDEventMonitor::Process(), CAirTunesServer::RegisterActionListener(), KODI::GAME::CGUIDialogButtonCapture::Show(), MUSIC_INFO::CMusicInfoScanner::Start(), CAlarmClock::Start(), KODI::RETRO::CGameLoop::Stop(), PERIPHERALS::CEventScanner::Stop(), WSDiscovery::CWSDiscoveryListenerUDP::Stop(), PVR::CPVREpgContainer::Stop(), PVR::CPVRGUIInfo::Stop(), PVR::CPVRTimers::Stop(), PVR::CPVRRefreshTimelineItemsThread::Stop(), PVR::CPVRManager::Stop(), CLanguageInvokerThread::stop(), CTimer::Stop(), CApplication::Stop(), CAirPlayServer::StopServer(), EVENTSERVER::CEventServer::StopServer(), JSONRPC::CTCPServer::StopServer(), CBackgroundInfoLoader::StopThread(), XFILE::CFileCache::StopThread(), CWIN32Util::XBMCShellExecute(), ADDON::CAddonStatusHandler::~CAddonStatusHandler(), CBackgroundPicLoader::~CBackgroundPicLoader(), CBusyWaiter::~CBusyWaiter(), CDVDRadioRDSData::~CDVDRadioRDSData(), CDVDTeletextData::~CDVDTeletextData(), CFDEventMonitor::~CFDEventMonitor(), CIRServerSuite::~CIRServerSuite(), CJobWorker::~CJobWorker(), CLibInputHandler::~CLibInputHandler(), CLirc::~CLirc(), MUSIC_GRABBER::CMusicInfoScraper::~CMusicInfoScraper(), PVR::CPVRRefreshTimelineItemsThread::~CPVRRefreshTimelineItemsThread(), KODI::RETRO::CRetroPlayerAutoSave::~CRetroPlayerAutoSave(), CRssReader::~CRssReader(), ~CThread(), CVideoPlayerAudio::~CVideoPlayerAudio(), CVideoPlayerAudioID3::~CVideoPlayerAudioID3(), CVideoPlayerVideo::~CVideoPlayerVideo(), CVideoReferenceClock::~CVideoReferenceClock(), CWHelper::~CWHelper(), CWin32PowerSyscall::~CWin32PowerSyscall(), CWinEventsAndroid::~CWinEventsAndroid(), CWinEventsOSX::~CWinEventsOSX(), CWinEventsTVOS::~CWinEventsTVOS(), and CZeroconfMDNS::~CZeroconfMDNS().
Member Data Documentation
m_bAutoDelete
bool CThread::m_bAutoDelete = false private
Referenced by Create(), and IsAutoDelete().
m_bStop
std::atomic<bool> CThread::m_bStop protected
Referenced by KODI::GAME::CGUIConfigurationWizard::Abort(), EVENTSERVER::CEventServer::CEventServer(), CGUIDialogCache::Close(), CVideoPlayerAudio::CloseStream(), CUdpClient::Create(), Create(), ANNOUNCEMENT::CAnnouncementManager::Deinitialize(), WSDiscovery::CWSDiscoveryListenerUDP::DispatchCommand(), CUdpClient::DispatchNextCommand(), ActiveAE::CActiveAE::Dispose(), ActiveAE::CActiveAESink::Dispose(), VAAPI::COutput::Dispose(), VDPAU::CMixer::Dispose(), VDPAU::COutput::Dispose(), CVideoPlayer::FlushBuffers(), CVideoPlayer::GetGeneralInfo(), PVR::CPVREpgContainer::InterruptUpdate(), CVideoPlayer::IsPlaying(), KODI::GAME::CGUIDialogButtonCapture::MapPrimitive(), PAPlayer::OnExit(), CVideoPlayer::OnExit(), XFILE::CFileCache::OnExit(), KODI::GAME::CGUIConfigurationWizard::OnKeyPress(), CVideoPlayer::OpenDemuxStream(), CZeroconfMDNS::Process(), CIRServerSuite::Process(), CWHelper::Process(), ActiveAE::CActiveAE::Process(), ActiveAE::CActiveAESink::Process(), PAPlayer::Process(), KODI::RETRO::CGameLoop::Process(), KODI::RETRO::CRetroPlayerAutoSave::Process(), VAAPI::COutput::Process(), VDPAU::CMixer::Process(), VDPAU::COutput::Process(), CVideoPlayerAudio::Process(), CVideoPlayerAudioID3::Process(), CDVDRadioRDSData::Process(), CDVDTeletextData::Process(), CVideoPlayerVideo::Process(), CVideoReferenceClock::Process(), CGUIDialogCache::Process(), XFILE::CFileCache::Process(), XFILE::CShoutcastFile::Process(), KODI::GAME::CControllerSelect::Process(), KODI::GAME::CGUIDialogButtonCapture::Process(), KODI::GAME::CGUIConfigurationWizard::Process(), KODI::JOYSTICK::CRumbleGenerator::Process(), ANNOUNCEMENT::CAnnouncementManager::Process(), CLanguageInvokerThread::Process(), KODI::MESSAGING::CDelayedMessage::Process(), CAirPlayServer::Process(), CAirTunesServer::Process(), EVENTSERVER::CEventServer::Process(), JSONRPC::CTCPServer::Process(), CUdpClient::Process(), UPNP::CUPnPPlayer::Process(), PERIPHERALS::CEventScanner::Process(), CBackgroundPicLoader::Process(), CFDEventMonitor::Process(), CLibInputHandler::Process(), CLirc::Process(), WSDiscovery::CWSDiscoveryListenerUDP::Process(), PVR::CPVREpgContainer::Process(), PVR::CPVRGUIInfo::Process(), PVR::CPVRGUIProgressHandler::Process(), PVR::CPVRTimers::Process(), PVR::CPVRRefreshTimelineItemsThread::Process(), CTimer::Process(), CAlarmClock::Process(), CRssReader::Process(), CWinEventsAndroid::Process(), CWin32PowerStateWorker::Process(), PERIPHERALS::CPeripheralBus::Process(), PERIPHERALS::CPeripheralBusUSB::Process(), CDVDRadioRDSData::ProcessUECP(), CLanguageInvokerThread::Release(), CLanguageInvokerThread::Reuseable(), EVENTSERVER::CEventServer::Run(), CTimer::Stop(), StopThread(), XFILE::CFileCache::StopThread(), CVideoPlayer::SynchronizeDemuxer(), PERIPHERALS::CPeripheralBusUSB::WaitForUpdate(), CVideoReferenceClock::~CVideoReferenceClock(), CWinEventsAndroid::~CWinEventsAndroid(), CWinEventsOSX::~CWinEventsOSX(), and CWinEventsTVOS::~CWinEventsTVOS().
m_CriticalSection
CCriticalSection CThread::m_CriticalSection private
Referenced by Create(), Join(), and StopThread().
m_future
std::future<bool> CThread::m_future private
Referenced by Create(), IsRunning(), and Join().
m_impl
std::unique_ptr<IThreadImpl> CThread::m_impl private
Referenced by Create(), and SetPriority().
m_pRunnable
IRunnable* CThread::m_pRunnable private
Referenced by Process().
m_StartEvent
CEvent CThread::m_StartEvent private
Referenced by Create(), and StopThread().
m_StopEvent
CEvent CThread::m_StopEvent private
Referenced by AbortableWait(), Create(), Sleep(), and StopThread().
m_thread
std::thread* CThread::m_thread = nullptr private
Referenced by Create(), IsRunning(), Join(), StopThread(), and ~CThread().
m_ThreadName
std::string CThread::m_ThreadName private
Referenced by Create(), CThread(), and CThread().
The documentation for this class was generated from the following files:
threads/Thread.h
Thread.cpp