Kodi Documentation: CMusicDatabase Class Reference
CMusicDatabase Class Reference
Music info
Class to store and read tag information.
#include <MusicDatabase.h>
Public Member Functions
CMusicDatabase (void)
~CMusicDatabase (void) override
bool Open () override
bool CommitTransaction () override
void EmptyCache ()
void Clean ()
int Cleanup (CGUIDialogProgress *progressDialog=nullptr)
bool LookupCDDBInfo (bool bRequery=false)
void DeleteCDDBInfo ()
int AddSong (const int idSong, const CDateTime &dtDateNew, const int idAlbum, const std::string &strTitle, const std::string &strMusicBrainzTrackID, const std::string &strPathAndFileName, const std::string &strComment, const std::string &strMood, const std::string &strThumb, const std::string &artistDisp, const std::string &artistSort, const std::vector< std::string > &genres, int iTrack, int iDuration, const std::string &strReleaseDate, const std::string &strOrigReleaseDate, std::string &strDiscSubtitle, const int iTimesPlayed, int iStartOffset, int iEndOffset, const CDateTime &dtLastPlayed, float rating, int userrating, int votes, int iBPM, int iBitRate, int iSampleRate, int iChannels, const std::string &songVideoURL, const ReplayGain &replayGain)
Add a song to the database.
bool GetSong (int idSong, CSong &song)
bool UpdateSong (CSong &song, bool bArtists=true, bool bArtistLinks=true)
Update a song and all its nested entities (genres, artists, contributors)
int UpdateSong (int idSong, const std::string &strTitle, const std::string &strMusicBrainzTrackID, const std::string &strPathAndFileName, const std::string &strComment, const std::string &strMood, const std::string &strThumb, const std::string &artistDisp, const std::string &artistSort, const std::vector< std::string > &genres, int iTrack, int iDuration, const std::string &strReleaseDate, const std::string &strOrigReleaseDate, const std::string &strDiscSubtitle, int iTimesPlayed, int iStartOffset, int iEndOffset, const CDateTime &dtLastPlayed, float rating, int userrating, int votes, const ReplayGain &replayGain, int iBPM, int iBitRate, int iSampleRate, int iChannels, const std::string &songVideoURL)
Update a song in the database.
bool GetSongByFileName (const std::string &strFileName, CSong &song, int64_t startOffset=0)
bool GetSongsByPath (const std::string &strPath, MAPSONGS &songmap, bool bAppendToMap=false)
bool Search (const std::string &search, CFileItemList &items)
bool RemoveSongsFromPath (const std::string &path, MAPSONGS &songmap, bool exact=true)
void CheckArtistLinksChanged ()
bool SetSongUserrating (const std::string &filePath, int userrating)
bool SetSongUserrating (int idSong, int userrating)
bool SetSongVotes (const std::string &filePath, int votes)
int GetSongByArtistAndAlbumAndTitle (const std::string &strArtist, const std::string &strAlbum, const std::string &strTitle)
bool AddAlbum (CAlbum &album, int idSource)
Add an album and all its songs to the database.
bool UpdateAlbum (CAlbum &album)
Update an album and all its nested entities (artists, songs etc)
int AddAlbum (const std::string &strAlbum, const std::string &strMusicBrainzAlbumID, const std::string &strReleaseGroupMBID, const std::string &strArtist, const std::string &strArtistSort, const std::string &strGenre, const std::string &strReleaseDate, const std::string &strOrigReleaseDate, bool bBoxedSet, const std::string &strRecordLabel, const std::string &strType, const std::string &strReleaseStatus, bool bCompilation, CAlbum::ReleaseType releaseType)
Add an album to the database.
bool GetAlbum (int idAlbum, CAlbum &album, bool getSongs=true)
retrieve an album, optionally with all songs.
int UpdateAlbum (int idAlbum, const std::string &strAlbum, const std::string &strMusicBrainzAlbumID, const std::string &strReleaseGroupMBID, const std::string &strArtist, const std::string &strArtistSort, const std::string &strGenre, const std::string &strMoods, const std::string &strStyles, const std::string &strThemes, const std::string &strReview, const std::string &strImage, const std::string &strLabel, const std::string &strType, const std::string &strReleaseStatus, float fRating, int iUserrating, int iVotes, const std::string &strReleaseDate, const std::string &strOrigReleaseDate, bool bBoxedSet, bool bCompilation, CAlbum::ReleaseType releaseType, bool bScrapedMBID)
bool ClearAlbumLastScrapedTime (int idAlbum)
bool HasAlbumBeenScraped (int idAlbum)
bool AddAudioBook (const CFileItem &item)
bool SetResumeBookmarkForAudioBook (const CFileItem &item, int bookmark)
bool GetResumeBookmarkForAudioBook (const CFileItem &item, int &bookmark)
bool InsideScannedPath (const std::string &path)
Checks if the given path is inside a folder that has already been scanned into the library.
int GetAlbumIdByPath (const std::string &path)
bool GetAlbumFromSong (int idSong, CAlbum &album)
int GetAlbumByName (const std::string &strAlbum, const std::string &strArtist="")
int GetAlbumByName (const std::string &strAlbum, const std::vector< std::string > &artist)
bool GetMatchingMusicVideoAlbum (const std::string &strAlbum, const std::string &strArtist, int &idAlbum, std::string &strReview)
bool SearchAlbumsByArtistName (const std::string &strArtist, CFileItemList &items)
int GetAlbumByMatch (const CAlbum &album)
std::string GetAlbumById (int id)
std::string GetAlbumDiscTitle (int idAlbum, int idDisc)
bool SetAlbumUserrating (const int idAlbum, int userrating)
int GetAlbumDiscsCount (int idAlbum)
bool UpdateArtist (const CArtist &artist)
int AddArtist (const std::string &strArtist, const std::string &strMusicBrainzArtistID, const std::string &strSortName, bool bScrapedMBID=false)
int AddArtist (const std::string &strArtist, const std::string &strMusicBrainzArtistID, bool bScrapedMBID=false)
bool GetArtist (int idArtist, CArtist &artist, bool fetchAll=false)
bool GetArtistExists (int idArtist)
int GetLastArtist ()
int GetArtistFromMBID (const std::string &strMusicBrainzArtistID, std::string &artistname)
int UpdateArtist (int idArtist, const std::string &strArtist, const std::string &strSortName, const std::string &strMusicBrainzArtistID, bool bScrapedMBID, const std::string &strType, const std::string &strGender, const std::string &strDisambiguation, const std::string &strBorn, const std::string &strFormed, const std::string &strGenres, const std::string &strMoods, const std::string &strStyles, const std::string &strInstruments, const std::string &strBiography, const std::string &strDied, const std::string &strDisbanded, const std::string &strYearsActive, const std::string &strImage)
bool UpdateArtistScrapedMBID (int idArtist, const std::string &strMusicBrainzArtistID)
bool GetTranslateBlankArtist ()
void SetTranslateBlankArtist (bool translate)
bool HasArtistBeenScraped (int idArtist)
bool ClearArtistLastScrapedTime (int idArtist)
int AddArtistDiscography (int idArtist, const CDiscoAlbum &discoAlbum)
bool DeleteArtistDiscography (int idArtist)
bool GetArtistDiscography (int idArtist, CFileItemList &items)
bool AddArtistVideoLinks (const CArtist &artist)
bool DeleteArtistVideoLinks (const int idArtist)
std::string GetArtistById (int id)
int GetArtistByName (const std::string &strArtist)
int GetArtistByMatch (const CArtist &artist)
bool GetArtistFromSong (int idSong, CArtist &artist)
bool IsSongArtist (int idSong, int idArtist)
bool IsSongAlbumArtist (int idSong, int idArtist)
std::string GetRoleById (int id)
bool UpdateArtistSortNames (int idArtist=-1)
Propagate artist sort name into the concatenated artist sort name strings held for songs and albums.
int AddPath (const std::string &strPath)
bool GetPaths (std::set< std::string > &paths)
bool SetPathHash (const std::string &path, const std::string &hash)
bool GetPathHash (const std::string &path, std::string &hash)
bool GetAlbumPaths (int idAlbum, std::vector< std::pair< std::string, int > > &paths)
bool GetAlbumPath (int idAlbum, std::string &basePath)
int GetDiscnumberForPathID (int idPath)
bool GetOldArtistPath (int idArtist, std::string &path)
bool GetArtistPath (const CArtist &artist, std::string &path)
bool GetAlbumFolder (const CAlbum &album, const std::string &strAlbumPath, std::string &strFolder)
bool GetArtistFolderName (const CArtist &artist, std::string &strFolder)
bool GetArtistFolderName (const std::string &strArtist, const std::string &strMusicBrainzArtistID, std::string &strFolder)
bool UpdateSources ()
int AddSource (const std::string &strName, const std::string &strMultipath, const std::vector< std::string > &vecPaths, int id=-1)
int UpdateSource (const std::string &strOldName, const std::string &strName, const std::string &strMultipath, const std::vector< std::string > &vecPaths)
bool RemoveSource (const std::string &strName)
int GetSourceFromPath (const std::string &strPath)
bool AddAlbumSource (int idAlbum, int idSource)
bool AddAlbumSources (int idAlbum, const std::string &strPath)
bool DeleteAlbumSources (int idAlbum)
bool GetSources (CFileItemList &items)
bool GetSourcesByArtist (int idArtist, CFileItem *item)
bool GetSourcesByAlbum (int idAlbum, CFileItem *item)
bool GetSourcesBySong (int idSong, const std::string &strPath, CFileItem *item)
int GetSourceByName (const std::string &strSource)
std::string GetSourceById (int id)
int AddGenre (std::string &strGenre)
std::string GetGenreById (int id)
int GetGenreByName (const std::string &strGenre)
bool AddAlbumArtist (int idArtist, int idAlbum, const std::string &strArtist, int iOrder)
bool GetAlbumsByArtist (int idArtist, std::vector< int > &albums)
bool GetArtistsByAlbum (int idAlbum, CFileItem *item)
bool GetArtistsByAlbum (int idAlbum, std::vector< std::string > &artistIDs)
bool DeleteAlbumArtistsByAlbum (int idAlbum)
int AddRole (const std::string &strRole)
bool AddSongArtist (int idArtist, int idSong, const std::string &strRole, const std::string &strArtist, int iOrder)
bool AddSongArtist (int idArtist, int idSong, int idRole, const std::string &strArtist, int iOrder)
int AddSongContributor (int idSong, const std::string &strRole, const std::string &strArtist, const std::string &strSort)
void AddSongContributors (int idSong, const VECMUSICROLES &contributors, const std::string &strSort)
int GetRoleByName (const std::string &strRole)
bool GetRolesByArtist (int idArtist, CFileItem *item)
bool GetSongsByArtist (int idArtist, std::vector< int > &songs)
bool GetArtistsBySong (int idSong, std::vector< int > &artists)
bool DeleteSongArtistsBySong (int idSong)
bool AddSongGenres (int idSong, const std::vector< std::string > &genres)
bool GetGenresBySong (int idSong, std::vector< int > &genres)
bool GetGenresByAlbum (int idAlbum, CFileItem *item)
bool GetGenresByArtist (int idArtist, CFileItem *item)
bool GetIsAlbumArtist (int idArtist, CFileItem *item)
bool GetTop100 (const std::string &strBaseDir, CFileItemList &items)
bool GetTop100Albums (VECALBUMS &albums)
bool GetTop100AlbumSongs (const std::string &strBaseDir, CFileItemList &item)
bool GetRecentlyAddedAlbums (VECALBUMS &albums, unsigned int limit=0)
bool GetRecentlyAddedAlbumSongs (const std::string &strBaseDir, CFileItemList &item, unsigned int limit=0)
bool GetRecentlyPlayedAlbums (VECALBUMS &albums)
bool GetRecentlyPlayedAlbumSongs (const std::string &strBaseDir, CFileItemList &item)
int GetCompilationAlbumsCount ()
bool IsAlbumBoxset (int idAlbum)
int GetBoxsetsCount ()
int GetSinglesCount ()
int GetArtistCountForRole (int role)
int GetArtistCountForRole (const std::string &strRole)
void IncrementPlayCount (const CFileItem &item)
Increment the playcount of an item Increments the playcount and updates the last played date.
bool CleanupOrphanedItems ()
bool GetGenresNav (const std::string &strBaseDir, CFileItemList &items, const Filter &filter=Filter(), bool countOnly=false)
bool GetSourcesNav (const std::string &strBaseDir, CFileItemList &items, const Filter &filter=Filter(), bool countOnly=false)
bool GetYearsNav (const std::string &strBaseDir, CFileItemList &items, const Filter &filter=Filter())
bool GetRolesNav (const std::string &strBaseDir, CFileItemList &items, const Filter &filter=Filter())
bool GetArtistsNav (const std::string &strBaseDir, CFileItemList &items, bool albumArtistsOnly=false, int idGenre=-1, int idAlbum=-1, int idSong=-1, const Filter &filter=Filter(), const SortDescription &sortDescription=SortDescription(), bool countOnly=false)
bool GetCommonNav (const std::string &strBaseDir, const std::string &table, const std::string &labelField, CFileItemList &items, const Filter &filter, bool countOnly)
bool GetAlbumTypesNav (const std::string &strBaseDir, CFileItemList &items, const Filter &filter=Filter(), bool countOnly=false)
bool GetMusicLabelsNav (const std::string &strBaseDir, CFileItemList &items, const Filter &filter=Filter(), bool countOnly=false)
bool GetAlbumsNav (const std::string &strBaseDir, CFileItemList &items, int idGenre=-1, int idArtist=-1, const Filter &filter=Filter(), const SortDescription &sortDescription=SortDescription(), bool countOnly=false)
bool GetDiscsNav (const std::string &strBaseDir, CFileItemList &items, int idAlbum, const Filter &filter=Filter(), const SortDescription &sortDescription=SortDescription(), bool countOnly=false)
bool GetAlbumsByYear (const std::string &strBaseDir, CFileItemList &items, int year)
bool GetSongsNav (const std::string &strBaseDir, CFileItemList &items, int idGenre, int idArtist, int idAlbum, const SortDescription &sortDescription=SortDescription())
bool GetSongsByYear (const std::string &baseDir, CFileItemList &items, int year)
bool GetSongsByWhere (const std::string &baseDir, const Filter &filter, CFileItemList &items, const SortDescription &sortDescription=SortDescription())
bool GetSongsFullByWhere (const std::string &baseDir, const Filter &filter, CFileItemList &items, const SortDescription &sortDescription=SortDescription(), bool artistData=false)
bool GetAlbumsByWhere (const std::string &baseDir, const Filter &filter, CFileItemList &items, const SortDescription &sortDescription=SortDescription(), bool countOnly=false)
bool GetDiscsByWhere (const std::string &baseDir, const Filter &filter, CFileItemList &items, const SortDescription &sortDescription=SortDescription(), bool countOnly=false)
bool GetDiscsByWhere (CMusicDbUrl &musicUrl, const Filter &filter, CFileItemList &items, const SortDescription &sortDescription=SortDescription(), bool countOnly=false)
bool GetArtistsByWhere (const std::string &strBaseDir, const Filter &filter, CFileItemList &items, const SortDescription &sortDescription=SortDescription(), bool countOnly=false)
int GetDiscsCount (const std::string &baseDir, const Filter &filter=Filter())
int GetSongsCount (const Filter &filter=Filter())
bool GetFilter (CDbUrl &musicUrl, Filter &filter, SortDescription &sorting) override
int GetOrderFilter (const std::string &type, const SortDescription &sorting, Filter &filter)
unsigned int GetRandomSongIDs (const Filter &filter, std::vector< std::pair< int, int > > &songIDs)
Gets song IDs in random order that match the filter criteria.
bool GetGenresJSON (CFileItemList &items, bool bSources=false)
bool GetArtistsByWhereJSON (const std::set< std::string > &fields, const std::string &baseDir, CVariant &result, int &total, const SortDescription &sortDescription=SortDescription())
bool GetAlbumsByWhereJSON (const std::set< std::string > &fields, const std::string &baseDir, CVariant &result, int &total, const SortDescription &sortDescription=SortDescription())
bool GetSongsByWhereJSON (const std::set< std::string > &fields, const std::string &baseDir, CVariant &result, int &total, const SortDescription &sortDescription=SortDescription())
bool SetScraper (int id, const CONTENT_TYPE &content, const ADDON::ScraperPtr &scraper)
bool SetScraperAll (const std::string &strBaseDir, const ADDON::ScraperPtr &scraper)
bool GetScraper (int id, const CONTENT_TYPE &content, ADDON::ScraperPtr &scraper)
bool ScraperInUse (const std::string &scraperID) const
Check whether a given scraper is in use.
bool GetItems (const std::string &strBaseDir, CFileItemList &items, const Filter &filter=Filter(), const SortDescription &sortDescription=SortDescription())
bool GetItems (const std::string &strBaseDir, const std::string &itemType, CFileItemList &items, const Filter &filter=Filter(), const SortDescription &sortDescription=SortDescription())
std::string GetItemById (const std::string &itemType, int id)
void ExportToXML (const CLibExportSettings &settings, CGUIDialogProgress *progressDialog=nullptr)
bool ExportSongHistory (TiXmlNode *pNode, CGUIDialogProgress *progressDialog=nullptr)
void ImportFromXML (const std::string &xmlFile, CGUIDialogProgress *progressDialog=nullptr)
bool ImportSongHistory (const std::string &xmlFile, const int total, CGUIDialogProgress *progressDialog=nullptr)
void SetPropertiesForFileItem (CFileItem &item)
void SetItemUpdated (int mediaId, const std::string &mediaType)
void SetArtForItem (int mediaId, const std::string &mediaType, const std::string &artType, const std::string &url)
Sets art for a database item. Sets a single piece of art for a database item.
void SetArtForItem (int mediaId, const std::string &mediaType, const std::map< std::string, std::string > &art)
Sets art for a database item. Sets multiple pieces of art for a database item.
bool GetArtForItem (int songId, int albumId, int artistId, bool bPrimaryArtist, std::vector< ArtForThumbLoader > &art)
Fetch all related art for a database item. Fetches multiple pieces of art for a database item including that for related media types Given song id art for the related album, artist(s) and albumartist(s) will also be fetched, looking up the album and artist when ids are not provided. Given album id (and not song id) art for the related artist(s) will also be fetched, looking up the artist(s) when id are not provided.
bool GetArtForItem (int mediaId, const std::string &mediaType, std::map< std::string, std::string > &art)
Fetch art for a database item. Fetches multiple pieces of art for a database item.
std::string GetArtForItem (int mediaId, const std::string &mediaType, const std::string &artType)
Fetch art for a database item. Fetches a single piece of art for a database item.
bool RemoveArtForItem (int mediaId, const MediaType &mediaType, const std::string &artType)
Remove art for a database item. Removes a single piece of art for a database item.
bool RemoveArtForItem (int mediaId, const MediaType &mediaType, const std::set< std::string > &artTypes)
Remove art for a database item. Removes multiple pieces of art for a database item.
bool GetArtTypes (const MediaType &mediaType, std::vector< std::string > &artTypes)
Fetch the distinct types of art held in the database for a type of media.
std::vector< std::string > GetAvailableArtTypesForItem (int mediaId, const MediaType &mediaType)
Fetch the distinct types of available-but-unassigned art held in the database for a specific media item.
std::vector< CScraperUrl::SUrlEntry > GetAvailableArtForItem (int mediaId, const MediaType &mediaType, const std::string &artType)
Fetch the list of available-but-unassigned art URLs held in the database for a specific media item and art type.
virtual int GetMusicNeedsTagScan ()
Check if music files need all tags rescanning regardless of file being unchanged because the tag processing has changed (which may happen without db version changes) since they where last scanned.
void SetMusicNeedsTagScan (int version)
Set minimum version number of db needed when tag data scanned from music files.
void SetMusicTagScanVersion (int version=0)
Set the version number of tag data.
std::string GetLibraryLastUpdated ()
void SetLibraryLastUpdated ()
std::string GetLibraryLastCleaned ()
void SetLibraryLastCleaned ()
std::string GetArtistLinksUpdated ()
void SetArtistLinksUpdated ()
std::string GetGenresLastAdded ()
std::string GetSongsLastAdded ()
std::string GetAlbumsLastAdded ()
std::string GetArtistsLastAdded ()
std::string GetSongsLastModified ()
std::string GetAlbumsLastModified ()
std::string GetArtistsLastModified ()
std::vector< std::string > GetUsedImages (const std::vector< std::string > &imagesToCheck) const
Check the passed in list of images if used in this database. Used to clean the image cache.
Public Member Functions inherited from CDatabase
CDatabase ()
virtual ~CDatabase (void)
bool IsOpen ()
virtual void Close ()
bool Compress (bool bForce=true)
void Interrupt ()
bool Open (const DatabaseSettings &db)
void BeginTransaction ()
void RollbackTransaction ()
void CopyDB (const std::string &latestDb)
void DropAnalytics ()
std::string PrepareSQL (std::string strStmt,...) const
std::string GetSingleValue (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single value from a table.
std::string GetSingleValue (const std::string &query) const
std::string GetSingleValue (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single value from a query on a dataset.
int GetSingleValueInt (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single integer value from a table.
int GetSingleValueInt (const std::string &query) const
int GetSingleValueInt (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single integer value from a query on a dataset.
bool DeleteValues (const std::string &strTable, const Filter &filter=Filter())
Delete values from a table.
bool ExecuteQuery (const std::string &strQuery)
Execute a query that does not return any result. Note that if BeginMultipleExecute() has been called, the query will be queued until CommitMultipleExecute() is called.
bool ResultQuery (const std::string &strQuery) const
Execute a query that returns a result.
bool BeginMultipleExecute ()
Start a multiple execution queue. Any ExecuteQuery() function following this call will be queued rather than executed until CommitMultipleExecute() is performed. NOTE: Queries that rely on any queued execute query will not function as expected during this period!
bool CommitMultipleExecute ()
Commit the multiple execution queue to the database. Queries are performed within a transaction, and the transaction is rolled back should any one query fail.
bool QueueInsertQuery (const std::string &strQuery)
Put an INSERT or REPLACE query in the queue.
bool CommitInsertQueries ()
Commit all queries in the queue.
size_t GetInsertQueriesCount ()
Get the number of INSERT queries in the queue.
bool QueueDeleteQuery (const std::string &strQuery)
Put a DELETE query in the queue.
bool CommitDeleteQueries ()
Commit all queued DELETE queries.
size_t GetDeleteQueriesCount ()
Get the number of DELETE queries in the queue.
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl)
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl, SortDescription &sorting)
bool Connect (const std::string &dbName, const DatabaseSettings &db, bool create)
Static Public Member Functions
static void SetPropertiesFromArtist (CFileItem &item, const CArtist &artist)
static void SetPropertiesFromAlbum (CFileItem &item, const CAlbum &album)
Protected Member Functions
void CreateTables () override
void CreateAnalytics () override
int GetMinSchemaVersion () const override
int GetSchemaVersion () const override
const char * GetBaseDBName () const override
Protected Member Functions inherited from CDatabase
void Split (const std::string &strFileNameAndPath, std::string &strPath, std::string &strFileName)
bool CreateDatabase ()
Create database tables and analytics as needed. Calls CreateTables() and CreateAnalytics() on child classes.
int GetDBVersion ()
bool BuildSQL (const std::string &strQuery, const Filter &filter, std::string &strSQL) const
Protected Attributes
std::map< std::string, int > m_genreCache
std::map< std::string, int > m_pathCache
Protected Attributes inherited from CDatabase
bool m_sqlite
whether we use sqlite (defaults to true)
std::unique_ptr< dbiplus::Database > m_pDB
std::unique_ptr< dbiplus::Dataset > m_pDS
std::unique_ptr< dbiplus::Dataset > m_pDS2
const CProfileManager & m_profileManager
Private Types
enum _SongFields {
song_idSong = 0 , song_strArtists , song_strArtistSort , song_strGenres ,
song_strTitle , song_iTrack , song_iDuration , song_strReleaseDate ,
song_strOrigReleaseDate , song_strDiscSubtitle , song_strFileName , song_strMusicBrainzTrackID ,
song_iTimesPlayed , song_iStartOffset , song_iEndOffset , song_lastplayed ,
song_rating , song_userrating , song_votes , song_comment ,
song_idAlbum , song_strAlbum , song_strPath , song_strReleaseStatus ,
song_bCompilation , song_bBoxedSet , song_strAlbumArtists , song_strAlbumArtistSort ,
song_strAlbumReleaseType , song_mood , song_strReplayGain , song_iBPM ,
song_iBitRate , song_iSampleRate , song_iChannels , song_songVideoURL ,
song_iAlbumDuration , song_iDiscTotal , song_dateAdded , song_dateNew ,
song_dateModified , song_enumCount
}
enum _AlbumFields {
album_idAlbum = 0 , album_strAlbum , album_strMusicBrainzAlbumID , album_strReleaseGroupMBID ,
album_strArtists , album_strArtistSort , album_strGenres , album_strReleaseDate ,
album_strOrigReleaseDate , album_bBoxedSet , album_strMoods , album_strStyles ,
album_strThemes , album_strReview , album_strLabel , album_strType ,
album_strReleaseStatus , album_strThumbURL , album_fRating , album_iUserrating ,
album_iVotes , album_bCompilation , album_bScrapedMBID , album_lastScraped ,
album_dateAdded , album_dateNew , album_dateModified , album_iTimesPlayed ,
album_strReleaseType , album_iTotalDiscs , album_dtLastPlayed , album_iAlbumDuration ,
album_enumCount
}
enum _ArtistCreditFields {
artistCredit_idEntity = 0 , artistCredit_idArtist , artistCredit_idRole , artistCredit_strRole ,
artistCredit_strArtist , artistCredit_strSortName , artistCredit_strMusicBrainzArtistID , artistCredit_iOrder ,
artistCredit_enumCount
}
enum _ArtistFields {
artist_idArtist = 0 , artist_strArtist , artist_strSortName , artist_strMusicBrainzArtistID ,
artist_strType , artist_strGender , artist_strDisambiguation , artist_strBorn ,
artist_strFormed , artist_strGenres , artist_strMoods , artist_strStyles ,
artist_strInstruments , artist_strBiography , artist_strDied , artist_strDisbanded ,
artist_strYearsActive , artist_strImage , artist_bScrapedMBID , artist_lastScraped ,
artist_dateAdded , artist_dateNew , artist_dateModified , artist_enumCount
}
enum _JoinToArtistFields {
joinToArtist_isSong = 0 , joinToArtist_idSourceAlbum , joinToArtist_idSourceSong , joinToArtist_idSongGenreAlbum ,
joinToArtist_idSongGenreSong , joinToArtist_strSongGenreAlbum , joinToArtist_strSongGenreSong , joinToArtist_idArt ,
joinToArtist_artType , joinToArtist_artURL , joinToArtist_idRole , joinToArtist_strRole ,
joinToArtist_iOrderRole , joinToArtist_isalbumartist , joinToArtist_thumbnail , joinToArtist_fanart ,
joinToArtist_enumCount
}
enum _JoinToAlbumFields { joinToAlbum_idArtist = 0 , joinToAlbum_strArtist , joinToAlbum_strArtistMBID , joinToAlbum_enumCount }
enum _JoinToSongFields {
joinToSongs_idAlbumArtist = 0 , joinToSongs_strAlbumArtist , joinToSongs_strAlbumArtistMBID , joinToSongs_iOrderAlbumArtist ,
joinToSongs_idArtist , joinToSongs_strArtist , joinToSongs_strArtistMBID , joinToSongs_iOrderArtist ,
joinToSongs_idRole , joinToSongs_strRole , joinToSongs_iOrderRole , joinToSongs_idGenre ,
joinToSongs_iOrderGenre , joinToSongs_enumCount
}
Private Member Functions
virtual void CreateViews ()
(Re)Create the generic database views for songs and albums
void CreateNativeDBFunctions ()
void CreateRemovedLinkTriggers ()
void SplitPath (const std::string &strFileNameAndPath, std::string &strPath, std::string &strFileName)
CSong GetSongFromDataset ()
CSong GetSongFromDataset (const dbiplus::sql_record *const record, int offset=0)
CArtist GetArtistFromDataset (dbiplus::Dataset *pDS, int offset=0, bool needThumb=true)
CArtist GetArtistFromDataset (const dbiplus::sql_record *const record, int offset=0, bool needThumb=true)
CAlbum GetAlbumFromDataset (dbiplus::Dataset *pDS, int offset=0, bool imageURL=false)
CAlbum GetAlbumFromDataset (const dbiplus::sql_record *const record, int offset=0, bool imageURL=false)
CArtistCredit GetArtistCreditFromDataset (const dbiplus::sql_record *const record, int offset=0)
CMusicRole GetArtistRoleFromDataset (const dbiplus::sql_record *const record, int offset=0)
std::string GetMediaDateFromFile (const std::string &strFileNameAndPath)
void GetFileItemFromDataset (CFileItem *item, const CMusicDbUrl &baseUrl)
void GetFileItemFromDataset (const dbiplus::sql_record *const record, CFileItem *item, const CMusicDbUrl &baseUrl)
void GetFileItemFromArtistCredits (VECARTISTCREDITS &artistCredits, CFileItem *item)
bool DeleteRemovedLinks ()
bool CleanupSongs (CGUIDialogProgress *progressDialog=nullptr)
bool CleanupSongsByIds (const std::string &strSongIds)
bool CleanupPaths ()
bool CleanupAlbums ()
bool CleanupArtists ()
bool CleanupGenres ()
bool CleanupInfoSettings ()
bool CleanupRoles ()
void UpdateTables (int version) override
bool SearchArtists (const std::string &search, CFileItemList &artists)
bool SearchAlbums (const std::string &search, CFileItemList &albums)
bool SearchSongs (const std::string &strSearch, CFileItemList &songs)
int GetSongIDFromPath (const std::string &filePath)
void NormaliseSongDates (std::string &strRelease, std::string &strOriginal)
bool TrimImageURLs (std::string &strImage, const size_t space)
std::string GetIgnoreArticleSQL (const std::string &strField)
Build SQL for sort subquery from ignore article token list.
std::string SortnameBuildSQL (const std::string &strAlias, const SortAttribute &sortAttributes, const std::string &strField, const std::string &strSortField)
Build SQL for sort name scalar subquery from sort attributes and ignore article list.
std::string AlphanumericSortSQL (const std::string &strField, const SortOrder &sortOrder)
Build SQL for sorting field naturally and case-insensitively (in SQLite).
bool CheckSources (std::vector< CMediaSource > &sources)
Checks that source table matches sources.xml returns true when they do.
bool MigrateSources ()
Initially fills source table from sources.xml for use only at migration of db from an earlier version than 72 returns true when successfully done.
Private Attributes
bool m_translateBlankArtist
Static Private Attributes
static enum CMusicDatabase::_SongFields SongFields
static enum CMusicDatabase::_AlbumFields AlbumFields
static enum CMusicDatabase::_ArtistCreditFields ArtistCreditFields
static enum CMusicDatabase::_ArtistFields ArtistFields
static enum CMusicDatabase::_JoinToArtistFields JoinToArtistFields
static enum CMusicDatabase::_JoinToAlbumFields JoinToAlbumFields
static enum CMusicDatabase::_JoinToSongFields JoinToSongFields
Friends
class DatabaseUtils
class TestDatabaseUtilsHelper
Detailed Description
Class to store and read tag information.
CMusicDatabase can be used to read and store tag information for faster access. It is based on sqlite (http://www.sqlite.org).
Here is the database layout:
See also
CAlbum, CSong, VECSONGS, CMapSong, VECARTISTS, VECALBUMS, VECGENRES
Member Enumeration Documentation
_AlbumFields
enum CMusicDatabase::_AlbumFields private
Enumerator
album_idAlbum
album_strAlbum
album_strMusicBrainzAlbumID
album_strReleaseGroupMBID
album_strArtists
album_strArtistSort
album_strGenres
album_strReleaseDate
album_strOrigReleaseDate
album_bBoxedSet
album_strMoods
album_strStyles
album_strThemes
album_strReview
album_strLabel
album_strType
album_strReleaseStatus
album_strThumbURL
album_fRating
album_iUserrating
album_iVotes
album_bCompilation
album_bScrapedMBID
album_lastScraped
album_dateAdded
album_dateNew
album_dateModified
album_iTimesPlayed
album_strReleaseType
album_iTotalDiscs
album_dtLastPlayed
album_iAlbumDuration
album_enumCount
_ArtistCreditFields
enum CMusicDatabase::_ArtistCreditFields private
Enumerator
artistCredit_idEntity
artistCredit_idArtist
artistCredit_idRole
artistCredit_strRole
artistCredit_strArtist
artistCredit_strSortName
artistCredit_strMusicBrainzArtistID
artistCredit_iOrder
artistCredit_enumCount
_ArtistFields
enum CMusicDatabase::_ArtistFields private
Enumerator
artist_idArtist
artist_strArtist
artist_strSortName
artist_strMusicBrainzArtistID
artist_strType
artist_strGender
artist_strDisambiguation
artist_strBorn
artist_strFormed
artist_strGenres
artist_strMoods
artist_strStyles
artist_strInstruments
artist_strBiography
artist_strDied
artist_strDisbanded
artist_strYearsActive
artist_strImage
artist_bScrapedMBID
artist_lastScraped
artist_dateAdded
artist_dateNew
artist_dateModified
artist_enumCount
_JoinToAlbumFields
enum CMusicDatabase::_JoinToAlbumFields private
Enumerator
joinToAlbum_idArtist
joinToAlbum_strArtist
joinToAlbum_strArtistMBID
joinToAlbum_enumCount
_JoinToArtistFields
enum CMusicDatabase::_JoinToArtistFields private
Enumerator
joinToArtist_isSong
joinToArtist_idSourceAlbum
joinToArtist_idSourceSong
joinToArtist_idSongGenreAlbum
joinToArtist_idSongGenreSong
joinToArtist_strSongGenreAlbum
joinToArtist_strSongGenreSong
joinToArtist_idArt
joinToArtist_artType
joinToArtist_artURL
joinToArtist_idRole
joinToArtist_strRole
joinToArtist_iOrderRole
joinToArtist_isalbumartist
joinToArtist_thumbnail
joinToArtist_fanart
joinToArtist_enumCount
_JoinToSongFields
enum CMusicDatabase::_JoinToSongFields private
Enumerator
joinToSongs_idAlbumArtist
joinToSongs_strAlbumArtist
joinToSongs_strAlbumArtistMBID
joinToSongs_iOrderAlbumArtist
joinToSongs_idArtist
joinToSongs_strArtist
joinToSongs_strArtistMBID
joinToSongs_iOrderArtist
joinToSongs_idRole
joinToSongs_strRole
joinToSongs_iOrderRole
joinToSongs_idGenre
joinToSongs_iOrderGenre
joinToSongs_enumCount
_SongFields
enum CMusicDatabase::_SongFields private
Enumerator
song_idSong
song_strArtists
song_strArtistSort
song_strGenres
song_strTitle
song_iTrack
song_iDuration
song_strReleaseDate
song_strOrigReleaseDate
song_strDiscSubtitle
song_strFileName
song_strMusicBrainzTrackID
song_iTimesPlayed
song_iStartOffset
song_iEndOffset
song_lastplayed
song_rating
song_userrating
song_votes
song_comment
song_idAlbum
song_strAlbum
song_strPath
song_strReleaseStatus
song_bCompilation
song_bBoxedSet
song_strAlbumArtists
song_strAlbumArtistSort
song_strAlbumReleaseType
song_mood
song_strReplayGain
song_iBPM
song_iBitRate
song_iSampleRate
song_iChannels
song_songVideoURL
song_iAlbumDuration
song_iDiscTotal
song_dateAdded
song_dateNew
song_dateModified
song_enumCount
Constructor & Destructor Documentation
CMusicDatabase()
CMusicDatabase::CMusicDatabase (void)
References m_translateBlankArtist.
~CMusicDatabase()
CMusicDatabase::~CMusicDatabase (void) override
References EmptyCache().
Member Function Documentation
AddAlbum() [1/2]
bool CMusicDatabase::AddAlbum (CAlbum & album, int idSource)
Add an album and all its songs to the database.
Parameters
album the album to add
idSource the music source id
Returns
the id of the album
References AddAlbum(), AddAlbumArtist(), AddAlbumSource(), AddAlbumSources(), AddArtist(), AddSong(), AddSongArtist(), AddSongContributors(), CAlbum::art, CAlbum::artistCredits, CAlbum::bBoxedSet, CAlbum::bCompilation, CDatabase::BeginTransaction(), BLANKARTIST_ID, BLANKARTIST_NAME, CommitTransaction(), CAlbum::GetAlbumArtistSort(), CAlbum::GetAlbumArtistString(), GetArtistsByAlbum(), CAlbum::GetGenreString(), CDatabase::GetSingleValue(), CDatabase::GetSingleValueInt(), CAlbum::idAlbum, CDatabase::m_pDS, MediaTypeAlbum, CDatabase::PrepareSQL(), CAlbum::releaseType, ROLE_ARTIST, SetArtForItem(), SetLibraryLastUpdated(), CAlbum::songs, CAlbum::strAlbum, CAlbum::strLabel, CAlbum::strMusicBrainzAlbumID, CAlbum::strOrigReleaseDate, CAlbum::strPath, CAlbum::strReleaseDate, CAlbum::strReleaseGroupMBID, CAlbum::strReleaseStatus, and CAlbum::strType.
Referenced by AddAlbum(), and MUSIC_INFO::CMusicInfoScanner::RetrieveMusicInfo().
AddAlbum() [2/2]
int CMusicDatabase::AddAlbum (const std::string & strAlbum, const std::string & strMusicBrainzAlbumID, const std::string & strReleaseGroupMBID, const std::string & strArtist, const std::string & strArtistSort, const std::string & strGenre, const std::string & strReleaseDate, const std::string & strOrigReleaseDate, bool bBoxedSet, const std::string & strRecordLabel, const std::string & strType, const std::string & strReleaseStatus, bool bCompilation, CAlbum::ReleaseType releaseType)
Add an album to the database.
Parameters
strAlbum the album title
strMusicBrainzAlbumID the Musicbrainz Id
strArtist the album artist name(s) display string
strArtistSort the album artist name(s) sort string
strGenre the album genre(s)
strReleaseDate [in] the release date of the album ISO8601 format
strOrigReleaseDate [in] the original release date of the album ISO8601 format
bBoxedSet if the album is a boxset
strRecordLabel the recording label
strType album type (Musicbrainz release type e.g. "Broadcast, Soundtrack, live"),
strReleaseStatus (see https://musicbrainz.org/doc/Release#Status)
bCompilation if the album is a compilation
releaseType "album" or "single"
Returns
the id of the album
References DeleteAlbumArtistsByAlbum(), DeleteAlbumSources(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CAlbum::ReleaseTypeToString().
AddAlbumArtist()
bool CMusicDatabase::AddAlbumArtist (int idArtist, int idAlbum, const std::string & strArtist, int iOrder)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by AddAlbum(), and UpdateAlbum().
AddAlbumSource()
bool CMusicDatabase::AddAlbumSource (int idAlbum, int idSource)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by AddAlbum(), and AddAlbumSources().
AddAlbumSources()
bool CMusicDatabase::AddAlbumSources (int idAlbum, const std::string & strPath)
References AddAlbumSource(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by AddAlbum().
AddArtist() [1/2]
int CMusicDatabase::AddArtist (const std::string & strArtist, const std::string & strMusicBrainzArtistID, bool bScrapedMBID = false)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
AddArtist() [2/2]
int CMusicDatabase::AddArtist (const std::string & strArtist, const std::string & strMusicBrainzArtistID, const std::string & strSortName, bool bScrapedMBID = false)
References AddArtist(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddAlbum(), AddArtist(), AddSongContributor(), UpdateAlbum(), and UpdateSong().
AddArtistDiscography()
int CMusicDatabase::AddArtistDiscography (int idArtist, const CDiscoAlbum & discoAlbum)
References CDatabase::ExecuteQuery(), CDatabase::PrepareSQL(), CDiscoAlbum::strAlbum, CDiscoAlbum::strReleaseGroupMBID, and CDiscoAlbum::strYear.
Referenced by UpdateArtist().
AddArtistVideoLinks()
bool CMusicDatabase::AddArtistVideoLinks (const CArtist & artist)
References end(), CArtist::idArtist, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, MediaTypeSong, CDatabase::PrepareSQL(), and CArtist::videolinks.
Referenced by UpdateArtist().
AddAudioBook()
bool CMusicDatabase::AddAudioBook (const CFileItem & item)
References CDatabase::ExecuteQuery(), MUSIC_INFO::CMusicInfoTag::GetAlbum(), MUSIC_INFO::CMusicInfoTag::GetArtist(), CDateTime::GetAsDBDateTime(), CDateTime::GetCurrentDateTime(), CFileItem::GetDynPath(), CFileItem::GetMusicInfoTag(), and CDatabase::PrepareSQL().
Referenced by SetResumeBookmarkForAudioBook().
AddGenre()
int CMusicDatabase::AddGenre (std::string & strGenre)
References g_localizeStrings, CLocalizeStrings::Get(), CLog::Log(), LOGERROR, m_genreCache, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddSongGenres().
AddPath()
int CMusicDatabase::AddPath (const std::string & strPath)
References URIUtils::AddSlashAtEnd(), URIUtils::HasSlashAtEnd(), CLog::Log(), LOGERROR, m_pathCache, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddSong(), SetPathHash(), and UpdateSong().
AddRole()
int CMusicDatabase::AddRole (const std::string & strRole)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddSongArtist().
AddSong()
int CMusicDatabase::AddSong (const int idSong, const CDateTime & dtDateNew, const int idAlbum, const std::string & strTitle, const std::string & strMusicBrainzTrackID, const std::string & strPathAndFileName, const std::string & strComment, const std::string & strMood, const std::string & strThumb, const std::string & artistDisp, const std::string & artistSort, const std::vector< std::string > & genres, int iTrack, int iDuration, const std::string & strReleaseDate, const std::string & strOrigReleaseDate, std::string & strDiscSubtitle, const int iTimesPlayed, int iStartOffset, int iEndOffset, const CDateTime & dtLastPlayed, float rating, int userrating, int votes, int iBPM, int iBitRate, int iSampleRate, int iChannels, const std::string & songVideoURL, const ReplayGain & replayGain)
Add a song to the database.
Parameters
idSong [in] the original database ID of the song to reuse (-1 when new)
dtDateNew [in] the datetime the original ID was new
idAlbum [in] the database ID of the album for the song
strTitle [in] the title of the song (required to be non-empty)
strMusicBrainzTrackID [in] the MusicBrainz track ID of the song
strPathAndFileName [in] the path and filename to the song
strComment [in] the ids of the added songs
strMood [in] the mood of the added song
strThumb [in] the ids of the added songs
artistDisp [in] the assembled artist name(s) display string
artistSort [in] the artist name(s) sort string
genres [in] a vector of genres to which this song belongs
iTrack [in] the track number and disc number of the song
iDuration [in] the duration of the song
strReleaseDate [in] the release date of the song ISO8601 format
strOrigReleaseDate [in] the original release date of the song ISO8601 format
strDiscSubtitle [in] subtitle of a disc
iTimesPlayed [in] the number of times the song has been played
iStartOffset [in] the start offset of the song (when using a single audio file with a .cue)
iEndOffset [in] the end offset of the song (when using a single audio file with .cue)
dtLastPlayed [in] the time the song was last played
rating [in] a rating for the song
userrating [in] a userrating (my rating) for the song
votes [in] a vote counter for the song rating
songVideoURL [in] url to video of the song
replayGain [in] album and track replaygain and peak values
Returns
the id of the song
References AddPath(), AddSongGenres(), AnnounceUpdate(), g_localizeStrings, ReplayGain::Get(), CLocalizeStrings::Get(), CDateTime::GetAsDBDateTime(), GetMediaDateFromFile(), IsAlbumBoxset(), CDateTime::IsValid(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeSong, NormaliseSongDates(), CDatabase::PrepareSQL(), SetArtForItem(), and UpdateSong().
Referenced by AddAlbum().
AddSongArtist() [1/2]
bool CMusicDatabase::AddSongArtist (int idArtist, int idSong, const std::string & strRole, const std::string & strArtist, int iOrder)
References AddRole(), and AddSongArtist().
Referenced by AddAlbum(), AddSongArtist(), AddSongContributor(), and UpdateSong().
AddSongArtist() [2/2]
bool CMusicDatabase::AddSongArtist (int idArtist, int idSong, int idRole, const std::string & strArtist, int iOrder)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
AddSongContributor()
int CMusicDatabase::AddSongContributor (int idSong, const std::string & strRole, const std::string & strArtist, const std::string & strSort)
References AddArtist(), AddSongArtist(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddSongContributors().
AddSongContributors()
void CMusicDatabase::AddSongContributors (int idSong, const VECMUSICROLES & contributors, const std::string & strSort)
References AddSongContributor(), and CServiceBroker::GetSettingsComponent().
Referenced by AddAlbum(), and UpdateSong().
AddSongGenres()
bool CMusicDatabase::AddSongGenres (int idSong, const std::vector< std::string > & genres)
References AddGenre(), CDatabase::ExecuteQuery(), CServiceBroker::GetSettingsComponent(), index(), CLog::Log(), LOGERROR, and CDatabase::PrepareSQL().
Referenced by AddSong(), and UpdateSong().
AddSource()
int CMusicDatabase::AddSource (const std::string & strName, const std::string & strMultipath, const std::vector< std::string > & vecPaths, int id = -1)
References CDatabase::Filter::AppendJoin(), CDatabase::Filter::AppendWhere(), CDatabase::BeginTransaction(), CDatabase::BuildSQL(), CommitTransaction(), GetSourceByName(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::RollbackTransaction().
Referenced by UpdateSource(), and UpdateSources().
AlphanumericSortSQL()
std::string CMusicDatabase::AlphanumericSortSQL (const std::string & strField, const SortOrder & sortOrder) private
Build SQL for sorting field naturally and case-insensitively (in SQLite).
Parameters
strField field name
sortOrder the sort order
Returns
SQL string e.g. CASE WHEN CAST(strTitle AS INTEGER) = 0 THEN 100000000 ELSE CAST(strTitle AS INTEGER) END DESC, strTitle COLLATE NOCASE DESC
References CServiceBroker::GetSettingsComponent(), CDatabase::PrepareSQL(), and SortOrderDescending.
Referenced by GetOrderFilter().
CheckArtistLinksChanged()
void CMusicDatabase::CheckArtistLinksChanged ()
References DeleteRemovedLinks(), CDatabase::GetSingleValueInt(), CDatabase::m_pDS, and SetArtistLinksUpdated().
Referenced by CGUIWindowMusicBase::OnRemoveSource(), MUSIC_INFO::CMusicInfoScanner::Process(), UpdateAlbum(), and UpdateSong().
CheckSources()
bool CMusicDatabase::CheckSources (std::vector< CMediaSource > & sources) private
Checks that source table matches sources.xml returns true when they do.
References CDatabase::GetSingleValue(), CDatabase::GetSingleValueInt(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by UpdateSources().
Clean()
void CMusicDatabase::Clean ()
References Cleanup(), CDatabase::Close(), ERROR_OK, CMusicLibraryQueue::GetInstance(), Open(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and KODI::MESSAGING::HELPERS::ShowYesNoDialogText().
Cleanup()
int CMusicDatabase::Cleanup (CGUIDialogProgress * progressDialog = nullptr)
References ANNOUNCEMENT::AudioLibrary, CleanupAlbums(), CleanupArtists(), CleanupGenres(), CleanupInfoSettings(), CleanupPaths(), CleanupRoles(), CleanupSongs(), CGUIWindow::Close(), CommitTransaction(), CDatabase::Compress(), CreateRemovedLinkTriggers(), DeleteRemovedLinks(), ERROR_CANCEL, ERROR_COMPRESSING, ERROR_DATABASE, ERROR_OK, ERROR_REORG_ALBUM, ERROR_REORG_ARTIST, ERROR_REORG_OTHER, ERROR_REORG_PATH, ERROR_REORG_SONGS, ERROR_WRITING_CHANGES, CServiceBroker::GetAnnouncementManager(), CGUIDialogProgress::IsCanceled(), CLog::Log(), LOGINFO, CDatabase::m_pDB, CDatabase::m_pDS, CGUIDialogProgress::Progress(), CDatabase::RollbackTransaction(), SetLibraryLastCleaned(), CGUIDialogBoxBase::SetLine(), and CGUIDialogProgress::SetPercentage().
Referenced by Clean(), and CMusicLibraryCleaningJob::Work().
CleanupAlbums()
bool CMusicDatabase::CleanupAlbums () private
References CLog::Log(), LOGERROR, and CDatabase::m_pDS.
Referenced by Cleanup(), and CleanupOrphanedItems().
CleanupArtists()
bool CMusicDatabase::CleanupArtists () private
References BLANKARTIST_ID, CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by Cleanup(), and CleanupOrphanedItems().
CleanupGenres()
bool CMusicDatabase::CleanupGenres () private
References CLog::Log(), LOGERROR, and CDatabase::m_pDS.
Referenced by Cleanup(), and CleanupOrphanedItems().
CleanupInfoSettings()
bool CMusicDatabase::CleanupInfoSettings () private
References CLog::Log(), LOGERROR, and CDatabase::m_pDS.
Referenced by Cleanup(), CleanupOrphanedItems(), and SetScraperAll().
CleanupOrphanedItems()
bool CMusicDatabase::CleanupOrphanedItems ()
References CleanupAlbums(), CleanupArtists(), CleanupGenres(), CleanupInfoSettings(), CleanupRoles(), CDatabase::m_pDB, CDatabase::m_pDS, and SetLibraryLastUpdated().
Referenced by CGUIWindowMusicBase::OnRemoveSource(), and MUSIC_INFO::CMusicInfoScanner::Process().
CleanupPaths()
bool CMusicDatabase::CleanupPaths () private
References CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by Cleanup().
CleanupRoles()
bool CMusicDatabase::CleanupRoles () private
References CLog::Log(), LOGERROR, and CDatabase::m_pDS.
Referenced by Cleanup(), and CleanupOrphanedItems().
CleanupSongs()
bool CMusicDatabase::CleanupSongs (CGUIDialogProgress * progressDialog = nullptr) private
References CleanupSongsByIds(), CGUIDialogProgress::GetPercentage(), CDatabase::GetSingleValueInt(), CGUIDialogProgress::IsCanceled(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), CGUIDialogProgress::Progress(), and CGUIDialogProgress::SetPercentage().
Referenced by Cleanup().
CleanupSongsByIds()
bool CMusicDatabase::CleanupSongsByIds (const std::string & strSongIds) private
References URIUtils::AddFileToFolder(), XFILE::CFile::Exists(), URIUtils::GetDirectory(), URIUtils::GetExtension(), KODI_ADDON_AUDIODECODER_TRACK_EXT, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and URIUtils::RemoveSlashAtEnd().
Referenced by CleanupSongs().
ClearAlbumLastScrapedTime()
bool CMusicDatabase::ClearAlbumLastScrapedTime (int idAlbum)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by CRefreshInfoJob::DoWork(), and MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo().
ClearArtistLastScrapedTime()
bool CMusicDatabase::ClearArtistLastScrapedTime (int idArtist)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by CRefreshInfoJob::DoWork(), and MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo().
CommitTransaction()
bool CMusicDatabase::CommitTransaction () override virtual
Reimplemented from CDatabase.
References CDatabase::CommitTransaction(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetLibraryInfoProvider(), GetSongsCount(), LIBRARY_HAS_MUSIC, and KODI::GUILIB::GUIINFO::CLibraryGUIInfo::SetLibraryBool().
Referenced by AddAlbum(), AddSource(), Cleanup(), ImportFromXML(), ImportSongHistory(), SetScraper(), SetScraperAll(), and UpdateAlbum().
CreateAnalytics()
void CMusicDatabase::CreateAnalytics () override protected virtual
Implements CDatabase.
References CreateNativeDBFunctions(), CreateRemovedLinkTriggers(), CreateViews(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGINFO, and CDatabase::m_pDS.
CreateNativeDBFunctions()
void CMusicDatabase::CreateNativeDBFunctions () private
References CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGINFO, and CDatabase::m_pDS.
Referenced by CreateAnalytics().
CreateRemovedLinkTriggers()
void CMusicDatabase::CreateRemovedLinkTriggers () private
References CDatabase::m_pDS.
Referenced by Cleanup(), and CreateAnalytics().
CreateTables()
void CMusicDatabase::CreateTables () override protected virtual
Implements CDatabase.
References BLANKARTIST_FAKEMUSICBRAINZID, BLANKARTIST_ID, BLANKARTIST_NAME, GetSchemaVersion(), CLog::Log(), LOGINFO, CDatabase::m_pDS, and CDatabase::PrepareSQL().
CreateViews()
void CMusicDatabase::CreateViews () private virtual
(Re)Create the generic database views for songs and albums
References CLog::Log(), LOGINFO, and CDatabase::m_pDS.
Referenced by CreateAnalytics().
DeleteAlbumArtistsByAlbum()
bool CMusicDatabase::DeleteAlbumArtistsByAlbum (int idAlbum)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by AddAlbum(), and UpdateAlbum().
DeleteAlbumSources()
bool CMusicDatabase::DeleteAlbumSources (int idAlbum)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by AddAlbum().
DeleteArtistDiscography()
bool CMusicDatabase::DeleteArtistDiscography (int idArtist)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by UpdateArtist().
DeleteArtistVideoLinks()
bool CMusicDatabase::DeleteArtistVideoLinks (const int idArtist)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by UpdateArtist().
DeleteCDDBInfo()
void CMusicDatabase::DeleteCDDBInfo ()
References CGUIDialogSelect::Add(), URIUtils::AddFileToFolder(), XFILE::CFile::Delete(), XFILE::DIR_FLAG_NO_FILE_DIRS, g_localizeStrings, CLocalizeStrings::Get(), CProfileManager::GetCDDBFolder(), XFILE::CDirectory::GetDirectory(), CDDB::Xcddb::getDiskArtist(), CDDB::Xcddb::getDiskTitle(), URIUtils::GetFileName(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedFileItem(), CGUIDialogSelect::GetSelectedItem(), CGUIComponent::GetWindowManager(), CDatabase::m_profileManager, CGUIDialog::Open(), CDDB::Xcddb::queryCache(), CGUIDialogSelect::Reset(), CDDB::Xcddb::setCacheDir(), CGUIDialogBoxBase::SetHeading(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), CFileItemList::Size(), CGUIDialogSelect::Sort(), and WINDOW_DIALOG_SELECT.
DeleteRemovedLinks()
bool CMusicDatabase::DeleteRemovedLinks () private
References CLog::Log(), LOGERROR, and CDatabase::m_pDS.
Referenced by CheckArtistLinksChanged(), and Cleanup().
DeleteSongArtistsBySong()
bool CMusicDatabase::DeleteSongArtistsBySong (int idSong)
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by UpdateSong().
EmptyCache()
void CMusicDatabase::EmptyCache ()
References m_genreCache, and m_pathCache.
Referenced by MUSIC_INFO::CMusicInfoScanner::Process(), and ~CMusicDatabase().
ExportSongHistory()
bool CMusicDatabase::ExportSongHistory (TiXmlNode * pNode, CGUIDialogProgress * progressDialog = nullptr)
References CGUIDialogProgress::IsCanceled(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDS, XMLUtils::SetInt(), CGUIDialogBoxBase::SetLine(), CGUIDialogProgress::SetPercentage(), and XMLUtils::SetString().
Referenced by ExportToXML().
ExportToXML()
void CMusicDatabase::ExportToXML (const CLibExportSettings & settings, CGUIDialogProgress * progressDialog = nullptr)
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), CAlbum::Album, CDatabase::Filter::AppendWhere(), ANNOUNCEMENT::AudioLibrary, CDatabase::BuildSQL(), CGUIWindow::Close(), XFILE::CDirectory::Create(), data(), ELIBEXPORT_ALBUMARTISTS, ELIBEXPORT_ALBUMS, ELIBEXPORT_OTHERARTISTS, ELIBEXPORT_SONGARTISTS, ELIBEXPORT_SONGS, CGUIDialogKaiToast::Error, XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), ExportSongHistory(), g_localizeStrings, CLocalizeStrings::Get(), GetAlbum(), CAlbum::GetAlbumArtist(), GetAlbumFolder(), GetAlbumPath(), CServiceBroker::GetAnnouncementManager(), GetArtForItem(), GetArtist(), GetArtistFolderName(), CDateTime::GetCurrentDateTime(), URIUtils::GetDirectory(), CAlbum::GetMusicBrainzAlbumArtistID(), GetOldArtistPath(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetTextureCache(), URIUtils::HasSlashAtEnd(), CAlbum::idAlbum, CArtist::idArtist, CLibExportSettings::IsArtistFoldersOnly(), CLibExportSettings::IsArtists(), CGUIDialogProgress::IsCanceled(), CLibExportSettings::IsItemExported(), CLibExportSettings::IsSeparateFiles(), CLibExportSettings::IsSingleFile(), CLibExportSettings::IsToLibFolders(), CLog::Log(), LOGDEBUG, LOGERROR, CLibExportSettings::m_artwork, CLibExportSettings::m_overwrite, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, CLibExportSettings::m_skipnfo, CLibExportSettings::m_strPath, CLibExportSettings::m_unscraped, MediaTypeAlbum, MediaTypeArtist, CDatabase::PrepareSQL(), CGUIDialogKaiToast::QueueNotification(), CAlbum::ReleaseTypeToString(), CAlbum::Save(), CArtist::Save(), CXBMCTinyXML::SaveFile(), CGUIDialogBoxBase::SetLine(), CGUIDialogProgress::SetPercentage(), XMLUtils::SetString(), CSettings::SETTING_MUSICLIBRARY_ARTISTSFOLDER, KODI::MESSAGING::HELPERS::ShowOKDialogLines(), CAlbum::strAlbum, and CArtist::strArtist.
Referenced by CMusicLibraryExportJob::Work().
GetAlbum()
bool CMusicDatabase::GetAlbum (int idAlbum, CAlbum & album, bool getSongs = true)
retrieve an album, optionally with all songs.
Parameters
idAlbum the database id of the album.
album [out] the album to fill.
getSongs whether or not to retrieve songs, defaults to true.
Returns
true if the album is retrieved, false otherwise.
References album_enumCount, artistCredit_idRole, CAlbum::artistCredits, GetAlbumFromDataset(), GetArtistCreditFromDataset(), GetArtistRoleFromDataset(), GetSongFromDataset(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), ROLE_ARTIST, song_enumCount, song_idSong, and CAlbum::songs.
Referenced by UPNP::CUPnPServer::Build(), CGetInfoJob::DoWork(), ExportToXML(), JSONRPC::CAudioLibrary::FillFileItem(), JSONRPC::CAudioLibrary::GetAlbumDetails(), GetAvailableArtForItem(), GetAvailableArtTypesForItem(), ImportFromXML(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CGUIWindowMusicNav::OnContextButton(), MUSIC_INFO::CMusicInfoScanner::Process(), JSONRPC::CAudioLibrary::RefreshAlbum(), JSONRPC::CAudioLibrary::SetAlbumDetails(), and SetPropertiesForFileItem().
GetAlbumById()
std::string CMusicDatabase::GetAlbumById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetAlbumDiscTitle(), GetItemById(), XFILE::CMusicDatabaseDirectory::GetLabel(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed::GetLocalizedName(), and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100::GetLocalizedName().
GetAlbumByMatch()
int CMusicDatabase::GetAlbumByMatch (const CAlbum & album)
References CAlbum::GetAlbumArtistString(), GetAlbumByName(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), CAlbum::strAlbum, and CAlbum::strMusicBrainzAlbumID.
Referenced by ImportFromXML().
GetAlbumByName() [1/2]
int CMusicDatabase::GetAlbumByName (const std::string & strAlbum, const std::string & strArtist = "")
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by GetAlbumByMatch(), GetAlbumByName(), GetFilter(), CGUIWindowMusicNav::OnContextButton(), UPNP::CUPnPServer::OnSearchContainer(), and SetPropertiesForFileItem().
GetAlbumByName() [2/2]
int CMusicDatabase::GetAlbumByName (const std::string & strAlbum, const std::vector< std::string > & artist)
References GetAlbumByName(), and CServiceBroker::GetSettingsComponent().
GetAlbumDiscsCount()
int CMusicDatabase::GetAlbumDiscsCount (int idAlbum)
References CDatabase::GetSingleValueInt(), and CDatabase::PrepareSQL().
GetAlbumDiscTitle()
std::string CMusicDatabase::GetAlbumDiscTitle (int idAlbum, int idDisc)
References g_localizeStrings, CLocalizeStrings::Get(), GetAlbumById(), CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetLocalizedName().
GetAlbumFolder()
bool CMusicDatabase::GetAlbumFolder (const CAlbum & album, const std::string & strAlbumPath, std::string & strFolder)
References CAlbum::artistCredits, CDatabase::GetSingleValue(), LEGAL_WIN32_COMPAT, CDatabase::m_pDS2, CUtil::MakeLegalFileName(), CDatabase::PrepareSQL(), URIUtils::SplitPath(), CAlbum::strAlbum, and CAlbum::strMusicBrainzAlbumID.
Referenced by ExportToXML().
GetAlbumFromDataset() [1/2]
CAlbum CMusicDatabase::GetAlbumFromDataset (const dbiplus::sql_record *const record, int offset = 0, bool imageURL = false) private
References album_bBoxedSet, album_bCompilation, album_bScrapedMBID, album_dateAdded, album_dateModified, album_dateNew, album_dtLastPlayed, album_fRating, album_iAlbumDuration, album_idAlbum, album_iTimesPlayed, album_iTotalDiscs, album_iUserrating, album_iVotes, album_lastScraped, album_strAlbum, album_strArtists, album_strArtistSort, album_strGenres, album_strLabel, album_strMoods, album_strMusicBrainzAlbumID, album_strOrigReleaseDate, album_strReleaseDate, album_strReleaseGroupMBID, album_strReleaseStatus, album_strReleaseType, album_strReview, album_strStyles, album_strThemes, album_strThumbURL, album_strType, CAlbum::bBoxedSet, CAlbum::bCompilation, CAlbum::bScrapedMBID, CAlbum::fRating, g_localizeStrings, CAlbum::genre, CLocalizeStrings::Get(), CServiceBroker::GetSettingsComponent(), CAlbum::iAlbumDuration, CAlbum::idAlbum, CAlbum::iTimesPlayed, CAlbum::iTotalDiscs, CAlbum::iUserrating, CAlbum::iVotes, CAlbum::moods, CScraperUrl::ParseFromData(), CAlbum::SetDateAdded(), CAlbum::SetDateNew(), CAlbum::SetDateUpdated(), CAlbum::SetLastPlayed(), CAlbum::SetReleaseType(), CAlbum::strAlbum, CAlbum::strArtistDesc, CAlbum::strArtistSort, CAlbum::strLabel, CAlbum::strLastScraped, CAlbum::strMusicBrainzAlbumID, CAlbum::strOrigReleaseDate, CAlbum::strReleaseDate, CAlbum::strReleaseGroupMBID, CAlbum::strReleaseStatus, CAlbum::strReview, CAlbum::strType, CAlbum::styles, CAlbum::themes, and CAlbum::thumbURL.
GetAlbumFromDataset() [2/2]
CAlbum CMusicDatabase::GetAlbumFromDataset (dbiplus::Dataset * pDS, int offset = 0, bool imageURL = false) private
References dbiplus::Dataset::get_sql_record(), and GetAlbumFromDataset().
Referenced by GetAlbum(), GetAlbumFromDataset(), GetAlbumFromSong(), GetAlbumsByWhere(), GetDiscsByWhere(), GetRecentlyAddedAlbums(), GetRecentlyPlayedAlbums(), GetTop100Albums(), SearchAlbums(), and SearchAlbumsByArtistName().
GetAlbumFromSong()
bool CMusicDatabase::GetAlbumFromSong (int idSong, CAlbum & album)
References GetAlbumFromDataset(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by UPNP::CUPnPServer::Announce(), and MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo().
GetAlbumIdByPath()
int CMusicDatabase::GetAlbumIdByPath (const std::string & path)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by JSONRPC::CAudioLibrary::FillFileItem().
GetAlbumPath()
bool CMusicDatabase::GetAlbumPath (int idAlbum, std::string & basePath)
References GetAlbumPaths(), and URIUtils::GetCommonPath().
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), CGetInfoJob::DoWork(), CGetSongInfoJob::DoWork(), and ExportToXML().
GetAlbumPaths()
bool CMusicDatabase::GetAlbumPaths (int idAlbum, std::vector< std::pair< std::string, int > > & paths)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), and GetAlbumPath().
GetAlbumsByArtist()
bool CMusicDatabase::GetAlbumsByArtist (int idArtist, std::vector< int > & albums)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
GetAlbumsByWhere()
bool CMusicDatabase::GetAlbumsByWhere (const std::string & baseDir, const Filter & filter, CFileItemList & items, const SortDescription & sortDescription = SortDescription(), bool countOnly = false)
References CFileItemList::Add(), album_idAlbum, CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDbUrl::AppendPath(), DatabaseUtils::BuildLimitClauseOnly(), CDatabase::BuildSQL(), data(), end(), FieldRow, CDatabase::Filter::fields, fields, CDbUrl::FromString(), GetAlbumFromDataset(), DatabaseUtils::GetDatabaseResults(), GetFilter(), GetOrderFilter(), CServiceBroker::GetSettingsComponent(), CDatabase::GetSingleValueInt(), CDatabase::Filter::group, CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeAlbum, CDatabase::Filter::order, CFileItemList::Reserve(), CGUIListItem::SetProperty(), CFileItemList::SetSortMethod(), CFileItemList::SetSortOrder(), CSettings::SETTING_MUSICLIBRARY_USEARTISTSORTNAME, CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE, CFileItemList::Size(), SortDescription::sortAttributes, SortAttributeUseArtistSortName, SortDescription::sortBy, SortDescription::sortOrder, CDbUrl::ToString(), and CDatabase::Filter::where.
Referenced by GetAlbumsByYear(), GetAlbumsNav(), and GetItems().
GetAlbumsByWhereJSON()
bool CMusicDatabase::GetAlbumsByWhereJSON (const std::set< std::string > & fields, const std::string & baseDir, CVariant & result, int & total, const SortDescription & sortDescription = SortDescription())
References CDatabase::DatasetLayout::AdjustRecordNumbers(), CVariant::append(), CDatabase::Filter::AppendField(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDatabase::Filter::AppendOrder(), BLANKARTIST_ID, DatabaseUtils::BuildLimitClause(), CDatabase::BuildSQL(), CVariant::clear(), CVariant::empty(), end(), translateJSONField::fieldJSON, CDatabase::Filter::fields, fields, CDbUrl::FromString(), CDatabase::DatasetLayout::GetFetch(), CDatabase::DatasetLayout::GetFields(), GetFilter(), DatabaseUtils::GetLimitCount(), GetOrderFilter(), CDatabase::DatasetLayout::GetOutput(), CDatabase::DatasetLayout::GetRecNo(), CServiceBroker::GetSettingsComponent(), CDatabase::GetSingleValueInt(), CDatabase::DatasetLayout::HasFilterFields(), CVariant::isMember(), joinToAlbum_enumCount, joinToAlbum_idArtist, joinToAlbum_strArtist, joinToAlbum_strArtistMBID, JSONtoDBAlbum, CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeAlbum, NUM_ALBUM_FIELDS, CDatabase::Filter::order, CDatabase::PrepareSQL(), KODI::UTILS::RandomShuffle(), CVariant::reserve(), CDatabase::DatasetLayout::SetField(), CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE, SortDescription::sortBy, SortByRandom, IMAGE_FILES::URLFromFile(), values, CVariant::VariantTypeArray, and CDatabase::Filter::where.
Referenced by JSONRPC::CAudioLibrary::GetAlbums().
GetAlbumsByYear()
bool CMusicDatabase::GetAlbumsByYear (const std::string & strBaseDir, CFileItemList & items, int year)
References CDbUrl::AddOption(), CDbUrl::FromString(), GetAlbumsByWhere(), and CDbUrl::ToString().
GetAlbumsLastAdded()
std::string CMusicDatabase::GetAlbumsLastAdded ()
References CDatabase::GetSingleValue().
Referenced by JSONRPC::CAudioLibrary::GetProperties().
GetAlbumsLastModified()
std::string CMusicDatabase::GetAlbumsLastModified ()
References CDatabase::GetSingleValue().
Referenced by JSONRPC::CAudioLibrary::GetProperties().
GetAlbumsNav()
bool CMusicDatabase::GetAlbumsNav (const std::string & strBaseDir, CFileItemList & items, int idGenre = -1, int idArtist = -1, const Filter & filter = Filter(), const SortDescription & sortDescription = SortDescription(), bool countOnly = false)
References CDbUrl::AddOption(), CDbUrl::FromString(), GetAlbumsByWhere(), and CDbUrl::ToString().
Referenced by MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetContent(), CGUIDialogMediaFilter::GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetAlbumTypesNav()
bool CMusicDatabase::GetAlbumTypesNav (const std::string & strBaseDir, CFileItemList & items, const Filter & filter = Filter(), bool countOnly = false)
References GetCommonNav().
Referenced by CGUIDialogMediaFilter::GetItems().
GetArtForItem() [1/3]
std::string CMusicDatabase::GetArtForItem (int mediaId, const std::string & mediaType, const std::string & artType)
Fetch art for a database item. Fetches a single piece of art for a database item.
Parameters
mediaId the id in the media (song/artist/album) table.
mediaType the type of media, which corresponds to the table the item resides in (song/artist/album).
artType the type of art to retrieve, eg "thumb", "fanart".
Returns
the original URL to the piece of art, if available.
See also
SetArtForItem
References CDatabase::GetSingleValue(), CDatabase::m_pDS2, and CDatabase::PrepareSQL().
GetArtForItem() [2/3]
bool CMusicDatabase::GetArtForItem (int mediaId, const std::string & mediaType, std::map< std::string, std::string > & art)
Fetch art for a database item. Fetches multiple pieces of art for a database item.
Parameters
mediaId the id in the media (song/artist/album) table.
mediaType the type of media, which corresponds to the table the item resides in (song/artist/album).
art [out] a map of <type, url> where type is "thumb", "fanart", etc. and url is the original url of the art.
Returns
true if art is retrieved, false if no art is found.
See also
SetArtForItem
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
GetArtForItem() [3/3]
bool CMusicDatabase::GetArtForItem (int songId, int albumId, int artistId, bool bPrimaryArtist, std::vector< ArtForThumbLoader > & art)
Fetch all related art for a database item. Fetches multiple pieces of art for a database item including that for related media types Given song id art for the related album, artist(s) and albumartist(s) will also be fetched, looking up the album and artist when ids are not provided. Given album id (and not song id) art for the related artist(s) will also be fetched, looking up the artist(s) when id are not provided.
Parameters
songId the id in the song table, -1 when song art not being fetched
albumId the id in the album table, -1 when album art not being fetched
artistId the id in the artist table, -1 when artist not known
bPrimaryArtist true if art from only the first song artist or album artist is to be fetched
art [out] a vector, each element having media type e.g. "artist", "album" or "song", artType e.g. "thumb", "fanart", etc., prefix of "", "artist" or "albumartist" etc. giving the kind of artist relationship, and the original url of the art.
Returns
true if art is retrieved, false if no art is found.
See also
SetArtForItem
References CDatabase::Filter::AppendWhere(), ArtForThumbLoader::artType, CDatabase::BuildSQL(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, ArtForThumbLoader::mediaType, MediaTypeAlbum, MediaTypeArtist, MediaTypeSong, ArtForThumbLoader::prefix, CDatabase::PrepareSQL(), ROLE_ARTIST, and ArtForThumbLoader::url.
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), MUSIC_INFO::CMusicInfoScanner::AddArtistArtwork(), MUSIC_UTILS::AddCurrentArtTypes(), ExportToXML(), CMusicThumbLoader::FillLibraryArt(), CVideoThumbLoader::FillLibraryArt(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetCurrentArt(), CGUIWindowMusicBase::GetDirectory(), RemoveSongsFromPath(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetArtistDetails(), CGUIDialogVideoInfo::SetMovie(), JSONRPC::CAudioLibrary::SetSongDetails(), and CRecentlyAddedJob::UpdateMusic().
GetArtist()
bool CMusicDatabase::GetArtist (int idArtist, CArtist & artist, bool fetchAll = false)
References artist_enumCount, CArtist::discography, end(), GetArtistFromDataset(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, ArtistVideoLinks::mbTrackID, CDatabase::PrepareSQL(), CDiscoAlbum::strAlbum, CDiscoAlbum::strReleaseGroupMBID, CDiscoAlbum::strYear, ArtistVideoLinks::thumbURL, ArtistVideoLinks::title, CArtist::videolinks, and ArtistVideoLinks::videoURL.
Referenced by UPNP::CUPnPServer::Build(), CGetInfoJob::DoWork(), ExportToXML(), CVideoThumbLoader::FillLibraryArt(), GetAvailableArtForItem(), GetAvailableArtTypesForItem(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetLocalArt(), ImportFromXML(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CGUIWindowMusicNav::OnContextButton(), MUSIC_INFO::CMusicInfoScanner::Process(), JSONRPC::CAudioLibrary::SetArtistDetails(), and SetPropertiesForFileItem().
GetArtistById()
std::string CMusicDatabase::GetArtistById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetItemById(), XFILE::CMusicDatabaseDirectory::GetLabel(), and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetLocalizedName().
GetArtistByMatch()
int CMusicDatabase::GetArtistByMatch (const CArtist & artist)
References GetArtistByName(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), CArtist::strArtist, and CArtist::strMusicBrainzArtistID.
Referenced by ImportFromXML().
GetArtistByName()
int CMusicDatabase::GetArtistByName (const std::string & strArtist)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CMusicThumbLoader::FillLibraryArt(), CVideoThumbLoader::FillLibraryArt(), GetArtistByMatch(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetCurrentArt(), GetFilter(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetLocalArt(), CGUIWindowMusicNav::OnContextButton(), UPNP::CUPnPServer::OnSearchContainer(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::PersistArt(), CGUIDialogVideoInfo::SetMovie(), and SetPropertiesForFileItem().
GetArtistCountForRole() [1/2]
int CMusicDatabase::GetArtistCountForRole (const std::string & strRole)
References CDatabase::GetSingleValueInt(), and CDatabase::PrepareSQL().
GetArtistCountForRole() [2/2]
int CMusicDatabase::GetArtistCountForRole (int role)
References CDatabase::GetSingleValueInt(), and CDatabase::PrepareSQL().
Referenced by KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool().
GetArtistCreditFromDataset()
CArtistCredit CMusicDatabase::GetArtistCreditFromDataset (const dbiplus::sql_record *const record, int offset = 0) private
References artistCredit_idArtist, artistCredit_strArtist, artistCredit_strMusicBrainzArtistID, BLANKARTIST_ID, CArtistCredit::idArtist, CArtistCredit::m_strArtist, and CArtistCredit::m_strMusicBrainzArtistID.
Referenced by GetAlbum(), GetArtistsByAlbum(), GetRecentlyAddedAlbums(), GetRecentlyAddedAlbumSongs(), GetRecentlyPlayedAlbums(), GetRecentlyPlayedAlbumSongs(), GetSong(), GetSongsFullByWhere(), and GetTop100Albums().
GetArtistDiscography()
bool CMusicDatabase::GetArtistDiscography (int idArtist, CFileItemList & items)
References CFileItemList::Add(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeAlbum, and CDatabase::PrepareSQL().
Referenced by CGUIDialogMusicInfo::SetDiscography().
GetArtistExists()
bool CMusicDatabase::GetArtistExists (int idArtist)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by JSONRPC::CAudioLibrary::RefreshArtist(), and UpdateTables().
GetArtistFolderName() [1/2]
bool CMusicDatabase::GetArtistFolderName (const CArtist & artist, std::string & strFolder)
References GetArtistFolderName(), CArtist::strArtist, and CArtist::strMusicBrainzArtistID.
Referenced by ExportToXML(), GetArtistFolderName(), and GetArtistPath().
GetArtistFolderName() [2/2]
bool CMusicDatabase::GetArtistFolderName (const std::string & strArtist, const std::string & strMusicBrainzArtistID, std::string & strFolder)
References CDatabase::GetSingleValue(), LEGAL_WIN32_COMPAT, CDatabase::m_pDS2, CUtil::MakeLegalFileName(), and CDatabase::PrepareSQL().
GetArtistFromDataset() [1/2]
CArtist CMusicDatabase::GetArtistFromDataset (const dbiplus::sql_record *const record, int offset = 0, bool needThumb = true) private
References artist_bScrapedMBID, artist_dateAdded, artist_dateModified, artist_dateNew, artist_idArtist, artist_lastScraped, artist_strArtist, artist_strBiography, artist_strBorn, artist_strDied, artist_strDisambiguation, artist_strDisbanded, artist_strFormed, artist_strGender, artist_strGenres, artist_strImage, artist_strInstruments, artist_strMoods, artist_strMusicBrainzArtistID, artist_strSortName, artist_strStyles, artist_strType, artist_strYearsActive, BLANKARTIST_ID, CArtist::bScrapedMBID, g_localizeStrings, CArtist::genre, CLocalizeStrings::Get(), CServiceBroker::GetSettingsComponent(), CArtist::idArtist, CArtist::instruments, m_translateBlankArtist, CArtist::moods, CScraperUrl::ParseFromData(), CArtist::SetDateAdded(), CArtist::SetDateNew(), CArtist::SetDateUpdated(), CArtist::strArtist, CArtist::strBiography, CArtist::strBorn, CArtist::strDied, CArtist::strDisambiguation, CArtist::strDisbanded, CArtist::strFormed, CArtist::strGender, CArtist::strLastScraped, CArtist::strMusicBrainzArtistID, CArtist::strSortName, CArtist::strType, CArtist::styles, CArtist::thumbURL, and CArtist::yearsActive.
GetArtistFromDataset() [2/2]
CArtist CMusicDatabase::GetArtistFromDataset (dbiplus::Dataset * pDS, int offset = 0, bool needThumb = true) private
References dbiplus::Dataset::get_sql_record(), and GetArtistFromDataset().
Referenced by GetArtist(), GetArtistFromDataset(), GetArtistFromSong(), and GetArtistsByWhere().
GetArtistFromMBID()
int CMusicDatabase::GetArtistFromMBID (const std::string & strMusicBrainzArtistID, std::string & artistname)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by UpdateArtist(), and UpdateArtistScrapedMBID().
GetArtistFromSong()
bool CMusicDatabase::GetArtistFromSong (int idSong, CArtist & artist)
References GetArtistFromDataset(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo().
GetArtistLinksUpdated()
std::string CMusicDatabase::GetArtistLinksUpdated ()
References CDatabase::GetSingleValue().
Referenced by JSONRPC::CAudioLibrary::GetProperties().
GetArtistPath()
bool CMusicDatabase::GetArtistPath (const CArtist & artist, std::string & path)
References URIUtils::AddFileToFolder(), GetArtistFolderName(), CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_MUSICLIBRARY_ARTISTSFOLDER.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CGetInfoJob::DoWork(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetLocalArt(), MUSIC_INFO::CMusicInfoScanner::Process(), and MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo().
GetArtistRoleFromDataset()
CMusicRole CMusicDatabase::GetArtistRoleFromDataset (const dbiplus::sql_record *const record, int offset = 0) private
References artistCredit_idArtist, artistCredit_idRole, artistCredit_strArtist, and artistCredit_strRole.
Referenced by GetAlbum(), GetRecentlyAddedAlbumSongs(), GetRecentlyPlayedAlbumSongs(), GetSong(), and GetSongsFullByWhere().
GetArtistsByAlbum() [1/2]
bool CMusicDatabase::GetArtistsByAlbum (int idAlbum, CFileItem * item)
References GetArtistCreditFromDataset(), CFileItem::GetMusicInfoTag(), CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), CVariant::push_back(), MUSIC_INFO::CMusicInfoTag::SetAlbumArtist(), MUSIC_INFO::CMusicInfoTag::SetMusicBrainzAlbumArtistID(), CGUIListItem::SetProperty(), and CVariant::VariantTypeArray.
Referenced by AddAlbum(), and JSONRPC::CAudioLibrary::GetAdditionalSongDetails().
GetArtistsByAlbum() [2/2]
bool CMusicDatabase::GetArtistsByAlbum (int idAlbum, std::vector< std::string > & artistIDs)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
GetArtistsBySong()
bool CMusicDatabase::GetArtistsBySong (int idSong, std::vector< int > & artists)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
GetArtistsByWhere()
bool CMusicDatabase::GetArtistsByWhere (const std::string & strBaseDir, const Filter & filter, CFileItemList & items, const SortDescription & sortDescription = SortDescription(), bool countOnly = false)
References CFileItemList::Add(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDbUrl::AppendPath(), DatabaseUtils::BuildLimitClauseOnly(), CDatabase::BuildSQL(), data(), end(), FieldRow, CDatabase::Filter::fields, fields, CDbUrl::FromString(), GetArtistFromDataset(), DatabaseUtils::GetDatabaseResults(), GetFilter(), GetOrderFilter(), CServiceBroker::GetSettingsComponent(), CDatabase::GetSingleValueInt(), CDatabase::Filter::group, CArtist::idArtist, CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeArtist, CFileItemList::Reserve(), SetPropertiesFromArtist(), CGUIListItem::SetProperty(), CFileItemList::SetSortMethod(), CFileItemList::SetSortOrder(), CSettings::SETTING_MUSICLIBRARY_USEARTISTSORTNAME, CFileItemList::Size(), SortDescription::sortAttributes, SortAttributeUseArtistSortName, SortDescription::sortBy, SortDescription::sortOrder, CDbUrl::ToString(), and CDatabase::Filter::where.
Referenced by JSONRPC::CAudioLibrary::GetArtistDetails(), GetArtistsNav(), and CRecentlyAddedJob::UpdateTotal().
GetArtistsByWhereJSON()
bool CMusicDatabase::GetArtistsByWhereJSON (const std::set< std::string > & fields, const std::string & baseDir, CVariant & result, int & total, const SortDescription & sortDescription = SortDescription())
Todo:
: replace GetFilter to avoid exists as well as JOIn to albm_artist and song_artist tables
References CDatabase::DatasetLayout::AdjustRecordNumbers(), CVariant::append(), CDatabase::Filter::AppendField(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDatabase::Filter::AppendOrder(), CDatabase::Filter::AppendWhere(), DatabaseUtils::BuildLimitClause(), CDatabase::BuildSQL(), CVariant::clear(), CVariant::empty(), end(), translateJSONField::fieldJSON, CDatabase::Filter::fields, fields, CDbUrl::FromString(), CDatabase::DatasetLayout::GetFetch(), CDatabase::DatasetLayout::GetFields(), GetFilter(), DatabaseUtils::GetLimitCount(), CDbUrl::GetOptions(), GetOrderFilter(), CDatabase::DatasetLayout::GetOutput(), CDatabase::DatasetLayout::GetRecNo(), GetRoleByName(), CServiceBroker::GetSettingsComponent(), CDatabase::GetSingleValueInt(), CDatabase::Filter::group, CDatabase::DatasetLayout::HasFilterFields(), CVariant::isMember(), CDatabase::Filter::join, joinToArtist_artType, joinToArtist_artURL, joinToArtist_enumCount, joinToArtist_fanart, joinToArtist_idArt, joinToArtist_idRole, joinToArtist_idSongGenreAlbum, joinToArtist_idSongGenreSong, joinToArtist_idSourceAlbum, joinToArtist_idSourceSong, joinToArtist_isalbumartist, joinToArtist_isSong, joinToArtist_strRole, joinToArtist_strSongGenreAlbum, joinToArtist_strSongGenreSong, joinToArtist_thumbnail, JSONtoDBArtist, CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeArtist, NUM_ARTIST_FIELDS, CDatabase::Filter::order, CDatabase::PrepareSQL(), KODI::UTILS::RandomShuffle(), CVariant::reserve(), CDatabase::DatasetLayout::SetFetch(), CDatabase::DatasetLayout::SetField(), SortDescription::sortBy, SortByRandom, IMAGE_FILES::URLFromFile(), CVariant::VariantTypeArray, CVariant::VariantTypeObject, and CDatabase::Filter::where.
Referenced by JSONRPC::CAudioLibrary::GetArtists().
GetArtistsLastAdded()
std::string CMusicDatabase::GetArtistsLastAdded ()
References CDatabase::GetSingleValue().
Referenced by JSONRPC::CAudioLibrary::GetProperties().
GetArtistsLastModified()
std::string CMusicDatabase::GetArtistsLastModified ()
References CDatabase::GetSingleValue().
Referenced by JSONRPC::CAudioLibrary::GetProperties().
GetArtistsNav()
bool CMusicDatabase::GetArtistsNav (const std::string & strBaseDir, CFileItemList & items, bool albumArtistsOnly = false, int idGenre = -1, int idAlbum = -1, int idSong = -1, const Filter & filter = Filter(), const SortDescription & sortDescription = SortDescription(), bool countOnly = false)
References CDbUrl::AddOption(), CDbUrl::FromString(), GetArtistsByWhere(), CDbUrl::HasOption(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDbUrl::ToString().
Referenced by MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetContent(), CGUIDialogMediaFilter::GetItems(), GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetArtTypes()
bool CMusicDatabase::GetArtTypes (const MediaType & mediaType, std::vector< std::string > & artTypes)
Fetch the distinct types of art held in the database for a type of media.
Parameters
mediaType the type of media, which corresponds to the table the item resides in (song/artist/album).
artTypes [out] the types of art e.g. "thumb", "fanart", etc.
Returns
true if art is found, false if no art is found.
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by MUSIC_UTILS::AddMediaTypeArtTypes().
GetAvailableArtForItem()
std::vector< CScraperUrl::SUrlEntry > CMusicDatabase::GetAvailableArtForItem (int mediaId, const MediaType & mediaType, const std::string & artType)
Fetch the list of available-but-unassigned art URLs held in the database for a specific media item and art type.
Parameters
mediaId the id in the media (artist/album) table.
mediaType corresponds to the table the item resides in (artist/album).
artType e.g. "thumb", "fanart", etc.
Returns
list of URLs
References GetAlbum(), GetArtist(), CScraperUrl::GetUrls(), MediaTypeAlbum, MediaTypeArtist, CAlbum::thumbURL, and CArtist::thumbURL.
Referenced by JSONRPC::CAudioLibrary::GetAvailableArt().
GetAvailableArtTypesForItem()
std::vector< std::string > CMusicDatabase::GetAvailableArtTypesForItem (int mediaId, const MediaType & mediaType)
Fetch the distinct types of available-but-unassigned art held in the database for a specific media item.
Parameters
mediaId the id in the media (artist/album) table.
mediaType the type of media, which corresponds to the table the item resides in (artist/album).
Returns
the types of art e.g. "thumb", "fanart", etc.
References GetAlbum(), GetArtist(), CScraperUrl::GetUrls(), MediaTypeAlbum, MediaTypeArtist, CAlbum::thumbURL, and CArtist::thumbURL.
Referenced by MUSIC_UTILS::AddAvailableArtTypes(), and JSONRPC::CAudioLibrary::GetAvailableArtTypes().
GetBaseDBName()
const char * CMusicDatabase::GetBaseDBName () const inline override protected virtual
Implements CDatabase.
GetBoxsetsCount()
int CMusicDatabase::GetBoxsetsCount ()
References CDatabase::GetSingleValueInt().
Referenced by KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool().
GetCommonNav()
bool CMusicDatabase::GetCommonNav (const std::string & strBaseDir, const std::string & table, const std::string & labelField, CFileItemList & items, const Filter & filter, bool countOnly)
References CFileItemList::Add(), CDatabase::Filter::AppendGroup(), CDbUrl::AppendPath(), CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), CDatabase::Filter::fields, CDatabase::Filter::group, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::Filter::order, CDatabase::PrepareSQL(), table, and CDbUrl::ToString().
Referenced by GetAlbumTypesNav(), and GetMusicLabelsNav().
GetCompilationAlbumsCount()
int CMusicDatabase::GetCompilationAlbumsCount ()
References CDatabase::GetSingleValueInt().
Referenced by KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeOverview::GetContent().
GetDiscnumberForPathID()
int CMusicDatabase::GetDiscnumberForPathID (int idPath)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork().
GetDiscsByWhere() [1/2]
bool CMusicDatabase::GetDiscsByWhere (CMusicDbUrl & musicUrl, const Filter & filter, CFileItemList & items, const SortDescription & sortDescription = SortDescription(), bool countOnly = false)
References CFileItemList::Add(), CDbUrl::AddOption(), album_idAlbum, CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDbUrl::AppendPath(), DatabaseUtils::BuildLimitClause(), CDatabase::BuildSQL(), data(), end(), FieldRow, g_localizeStrings, CLocalizeStrings::Get(), GetAlbumFromDataset(), GetFilter(), CDatabase::GetSingleValueInt(), CAlbum::idAlbum, CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeAlbum, CDatabase::PrepareSQL(), CFileItemList::Reserve(), CGUIListItem::SetProperty(), CFileItemList::Size(), CFileItemList::Sort(), SortDescription::sortBy, SortByNone, SortByRandom, SortUtils::SortFromDataset(), CDbUrl::ToString(), and CDatabase::Filter::where.
GetDiscsByWhere() [2/2]
bool CMusicDatabase::GetDiscsByWhere (const std::string & baseDir, const Filter & filter, CFileItemList & items, const SortDescription & sortDescription = SortDescription(), bool countOnly = false)
References CDbUrl::FromString(), and GetDiscsByWhere().
Referenced by GetDiscsByWhere(), GetDiscsCount(), GetDiscsNav(), and GetItems().
GetDiscsCount()
int CMusicDatabase::GetDiscsCount (const std::string & baseDir, const Filter & filter = Filter())
References CVariant::asInteger32(), GetDiscsByWhere(), and CGUIListItem::GetProperty().
Referenced by XFILE::CMusicDatabaseDirectory::GetDirectory().
GetDiscsNav()
bool CMusicDatabase::GetDiscsNav (const std::string & strBaseDir, CFileItemList & items, int idAlbum, const Filter & filter = Filter(), const SortDescription & sortDescription = SortDescription(), bool countOnly = false)
References CDbUrl::AddOption(), CDbUrl::FromString(), and GetDiscsByWhere().
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetContent().
GetFileItemFromArtistCredits()
void CMusicDatabase::GetFileItemFromArtistCredits (VECARTISTCREDITS & artistCredits, CFileItem * item) private
References BLANKARTIST_ID, CFileItem::GetMusicInfoTag(), CVariant::push_back(), MUSIC_INFO::CMusicInfoTag::SetArtist(), MUSIC_INFO::CMusicInfoTag::SetMusicBrainzArtistID(), CGUIListItem::SetProperty(), and CVariant::VariantTypeArray.
Referenced by GetRecentlyAddedAlbumSongs(), GetRecentlyPlayedAlbumSongs(), and GetSongsFullByWhere().
GetFileItemFromDataset() [1/2]
void CMusicDatabase::GetFileItemFromDataset (CFileItem * item, const CMusicDbUrl & baseUrl) private
References GetFileItemFromDataset(), and CDatabase::m_pDS.
Referenced by GetFileItemFromDataset(), GetRecentlyAddedAlbumSongs(), GetRecentlyPlayedAlbumSongs(), GetSongsByWhere(), GetSongsFullByWhere(), GetTop100(), GetTop100AlbumSongs(), and SearchSongs().
GetFileItemFromDataset() [2/2]
void CMusicDatabase::GetFileItemFromDataset (const dbiplus::sql_record *const record, CFileItem * item, const CMusicDbUrl & baseUrl) private
References URIUtils::AddFileToFolder(), CDbUrl::AppendPath(), URIUtils::GetExtension(), CFileItem::GetMusicInfoTag(), CFileItem::GetStartOffset(), CDbUrl::IsValid(), MediaTypeSong, CAlbum::ReleaseTypeFromString(), ReplayGain::Set(), MUSIC_INFO::CMusicInfoTag::SetAlbum(), MUSIC_INFO::CMusicInfoTag::SetAlbumArtist(), MUSIC_INFO::CMusicInfoTag::SetAlbumId(), MUSIC_INFO::CMusicInfoTag::SetAlbumReleaseType(), MUSIC_INFO::CMusicInfoTag::SetArtistDesc(), MUSIC_INFO::CMusicInfoTag::SetArtistSort(), MUSIC_INFO::CMusicInfoTag::SetBitRate(), MUSIC_INFO::CMusicInfoTag::SetBoxset(), MUSIC_INFO::CMusicInfoTag::SetBPM(), MUSIC_INFO::CMusicInfoTag::SetComment(), MUSIC_INFO::CMusicInfoTag::SetCompilation(), MUSIC_INFO::CMusicInfoTag::SetDatabaseId(), MUSIC_INFO::CMusicInfoTag::SetDateAdded(), MUSIC_INFO::CMusicInfoTag::SetDateNew(), MUSIC_INFO::CMusicInfoTag::SetDateUpdated(), MUSIC_INFO::CMusicInfoTag::SetDiscSubtitle(), MUSIC_INFO::CMusicInfoTag::SetDuration(), CFileItem::SetDynPath(), CFileItem::SetEndOffset(), MUSIC_INFO::CMusicInfoTag::SetGenre(), CFileItem::SetLabel(), MUSIC_INFO::CMusicInfoTag::SetLastPlayed(), MUSIC_INFO::CMusicInfoTag::SetLoaded(), MUSIC_INFO::CMusicInfoTag::SetMood(), MUSIC_INFO::CMusicInfoTag::SetMusicBrainzTrackID(), MUSIC_INFO::CMusicInfoTag::SetNoOfChannels(), MUSIC_INFO::CMusicInfoTag::SetOriginalDate(), CFileItem::SetPath(), MUSIC_INFO::CMusicInfoTag::SetPlayCount(), CGUIListItem::SetProperty(), MUSIC_INFO::CMusicInfoTag::SetRating(), MUSIC_INFO::CMusicInfoTag::SetReleaseDate(), MUSIC_INFO::CMusicInfoTag::SetReplayGain(), MUSIC_INFO::CMusicInfoTag::SetSampleRate(), MUSIC_INFO::CMusicInfoTag::SetSongVideoURL(), CFileItem::SetStartOffset(), MUSIC_INFO::CMusicInfoTag::SetTitle(), MUSIC_INFO::CMusicInfoTag::SetTotalDiscs(), MUSIC_INFO::CMusicInfoTag::SetTrackAndDiscNumber(), MUSIC_INFO::CMusicInfoTag::SetURL(), MUSIC_INFO::CMusicInfoTag::SetUserrating(), MUSIC_INFO::CMusicInfoTag::SetVotes(), song_bBoxedSet, song_bCompilation, song_comment, song_dateAdded, song_dateModified, song_dateNew, song_iBitRate, song_iBPM, song_iChannels, song_idAlbum, song_iDiscTotal, song_idSong, song_iDuration, song_iEndOffset, song_iSampleRate, song_iStartOffset, song_iTimesPlayed, song_iTrack, song_lastplayed, song_mood, song_rating, song_songVideoURL, song_strAlbum, song_strAlbumArtists, song_strAlbumReleaseType, song_strArtists, song_strArtistSort, song_strDiscSubtitle, song_strFileName, song_strGenres, song_strMusicBrainzTrackID, song_strOrigReleaseDate, song_strPath, song_strReleaseDate, song_strReplayGain, song_strTitle, song_userrating, song_votes, and CDbUrl::ToString().
GetFilter()
bool CMusicDatabase::GetFilter (CDbUrl & musicUrl, Filter & filter, SortDescription & sorting) override virtual
Reimplemented from CDatabase.
References CAlbum::Album, CDatabase::ExistsSubQuery::AppendJoin(), CDatabase::Filter::AppendWhere(), CDatabase::ExistsSubQuery::AppendWhere(), CDatabase::ExistsSubQuery::BuildSQL(), GetAlbumByName(), GetArtistByName(), GetGenreByName(), KODI::PLAYLIST::CSmartPlaylist::GetGroup(), KODI::PLAYLIST::CSmartPlaylist::GetLimit(), CDbUrl::GetOptions(), KODI::PLAYLIST::CSmartPlaylist::GetOrder(), KODI::PLAYLIST::CSmartPlaylist::GetOrderAscending(), GetRoleByName(), CServiceBroker::GetSettingsComponent(), GetSourceByName(), CDbUrl::GetType(), KODI::PLAYLIST::CSmartPlaylist::GetType(), KODI::PLAYLIST::CSmartPlaylist::GetWhereClause(), KODI::PLAYLIST::CSmartPlaylist::IsGroupMixed(), CDbUrl::IsValid(), SortDescription::limitEnd, KODI::PLAYLIST::CSmartPlaylist::LoadFromJson(), CDatabase::ExistsSubQuery::param, CDatabase::PrepareSQL(), CAlbum::ReleaseTypeToString(), CDbUrl::RemoveOption(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE, CAlbum::Single, SortAttributeIgnoreArticle, SortDescription::sortAttributes, SortDescription::sortBy, SortByNone, SortDescription::sortOrder, SortOrderAscending, and SortOrderDescending.
Referenced by GetAlbumsByWhere(), GetAlbumsByWhereJSON(), GetArtistsByWhere(), GetArtistsByWhereJSON(), GetDiscsByWhere(), GetGenresNav(), GetRolesNav(), GetSongsByWhere(), GetSongsByWhereJSON(), GetSongsFullByWhere(), GetSourcesNav(), GetYearsNav(), and SetScraperAll().
GetGenreById()
std::string CMusicDatabase::GetGenreById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetItemById(), and XFILE::CMusicDatabaseDirectory::GetLabel().
GetGenreByName()
int CMusicDatabase::GetGenreByName (const std::string & strGenre)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by GetFilter(), and UPNP::CUPnPServer::OnSearchContainer().
GetGenresByAlbum()
bool CMusicDatabase::GetGenresByAlbum (int idAlbum, CFileItem * item)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), CVariant::push_back(), CGUIListItem::SetProperty(), and CVariant::VariantTypeArray.
Referenced by JSONRPC::CAudioLibrary::GetAdditionalAlbumDetails().
GetGenresByArtist()
bool CMusicDatabase::GetGenresByArtist (int idArtist, CFileItem * item)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), CVariant::push_back(), CGUIListItem::SetProperty(), and CVariant::VariantTypeArray.
Referenced by JSONRPC::CAudioLibrary::GetAdditionalArtistDetails().
GetGenresBySong()
bool CMusicDatabase::GetGenresBySong (int idSong, std::vector< int > & genres)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by JSONRPC::CAudioLibrary::GetAdditionalSongDetails().
GetGenresJSON()
bool CMusicDatabase::GetGenresJSON (CFileItemList & items, bool bSources = false)
References CFileItemList::Add(), CDatabase::Filter::AppendField(), CDatabase::Filter::AppendJoin(), CDatabase::Filter::AppendOrder(), CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), CVariant::clear(), CDatabase::Filter::fields, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), CVariant::push_back(), CFileItemList::Reserve(), CGUIListItem::SetProperty(), CFileItemList::Size(), and CVariant::VariantTypeArray.
Referenced by JSONRPC::CAudioLibrary::GetGenres().
GetGenresLastAdded()
std::string CMusicDatabase::GetGenresLastAdded ()
References CDatabase::GetSingleValue().
Referenced by JSONRPC::CAudioLibrary::GetProperties().
GetGenresNav()
bool CMusicDatabase::GetGenresNav (const std::string & strBaseDir, CFileItemList & items, const Filter & filter = Filter(), bool countOnly = false)
References CFileItemList::Add(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDbUrl::AppendPath(), CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), CDatabase::Filter::fields, CDbUrl::FromString(), GetFilter(), CDatabase::Filter::group, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::Filter::order, CDatabase::PrepareSQL(), CDbUrl::ToString(), and CDatabase::Filter::where.
Referenced by CGUIDialogMediaFilter::GetItems(), GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetIgnoreArticleSQL()
std::string CMusicDatabase::GetIgnoreArticleSQL (const std::string & strField) private
Build SQL for sort subquery from ignore article token list.
Parameters
strField original name or title field that articles could be removed from
Returns
SQL string e.g. WHEN strField LIKE 'the_' ESCAPE '_' THEN SUBSTR(strArtist, 5)
References g_langInfo, and CDatabase::PrepareSQL().
Referenced by SortnameBuildSQL().
GetIsAlbumArtist()
bool CMusicDatabase::GetIsAlbumArtist (int idArtist, CFileItem * item)
References CDatabase::GetSingleValueInt(), CLog::Log(), LOGERROR, CDatabase::PrepareSQL(), CGUIListItem::SetProperty(), and CVariant::VariantTypeBoolean.
Referenced by JSONRPC::CAudioLibrary::GetAdditionalArtistDetails().
GetItemById()
std::string CMusicDatabase::GetItemById (const std::string & itemType, int id)
References GetAlbumById(), GetArtistById(), GetGenreById(), GetRoleById(), and GetSourceById().
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped::GetLocalizedName().
GetItems() [1/2]
bool CMusicDatabase::GetItems (const std::string & strBaseDir, CFileItemList & items, const Filter & filter = Filter(), const SortDescription & sortDescription = SortDescription())
References CDbUrl::FromString(), GetItems(), and CDbUrl::GetType().
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped::GetContent(), XFILE::CSmartPlaylistDirectory::GetDirectory(), and GetItems().
GetItems() [2/2]
bool CMusicDatabase::GetItems (const std::string & strBaseDir, const std::string & itemType, CFileItemList & items, const Filter & filter = Filter(), const SortDescription & sortDescription = SortDescription())
References GetAlbumsByWhere(), GetArtistsNav(), GetDiscsByWhere(), GetGenresNav(), GetRolesNav(), CServiceBroker::GetSettingsComponent(), GetSongsFullByWhere(), GetSourcesNav(), GetYearsNav(), and CSettings::SETTING_MUSICLIBRARY_SHOWCOMPILATIONARTISTS.
GetLastArtist()
int CMusicDatabase::GetLastArtist ()
References CDatabase::GetSingleValue().
GetLibraryLastCleaned()
std::string CMusicDatabase::GetLibraryLastCleaned ()
References CDatabase::GetSingleValue().
Referenced by JSONRPC::CAudioLibrary::GetProperties().
GetLibraryLastUpdated()
std::string CMusicDatabase::GetLibraryLastUpdated ()
References CDatabase::GetSingleValue().
Referenced by JSONRPC::CAudioLibrary::GetProperties(), and UpdateTables().
GetMatchingMusicVideoAlbum()
bool CMusicDatabase::GetMatchingMusicVideoAlbum (const std::string & strAlbum, const std::string & strArtist, int & idAlbum, std::string & strReview)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CVideoThumbLoader::FillLibraryArt().
GetMediaDateFromFile()
std::string CMusicDatabase::GetMediaDateFromFile (const std::string & strFileNameAndPath) private
References CDateTime::GetAsDBDateTime(), CDateTime::GetCurrentDateTime(), CFileUtils::GetModificationDate(), CServiceBroker::GetSettingsComponent(), and CDateTime::IsValid().
Referenced by AddSong(), and UpdateSong().
GetMinSchemaVersion()
int CMusicDatabase::GetMinSchemaVersion () const inline override protected virtual
Reimplemented from CDatabase.
GetMusicLabelsNav()
bool CMusicDatabase::GetMusicLabelsNav (const std::string & strBaseDir, CFileItemList & items, const Filter & filter = Filter(), bool countOnly = false)
References GetCommonNav().
Referenced by CGUIDialogMediaFilter::GetItems().
GetMusicNeedsTagScan()
int CMusicDatabase::GetMusicNeedsTagScan () virtual
Check if music files need all tags rescanning regardless of file being unchanged because the tag processing has changed (which may happen without db version changes) since they where last scanned.
Returns
-1 if an error occurred, 0 if no scan is needed, or the version number of tags if not the same as current.
References CLog::Log(), LOGERROR, CDatabase::m_pDB, and CDatabase::m_pDS.
Referenced by CGUIWindowMusicBase::OnInitWindow().
GetOldArtistPath()
bool CMusicDatabase::GetOldArtistPath (int idArtist, std::string & path)
References URIUtils::GetCommonPath(), URIUtils::GetParentPath(), CDatabase::GetSingleValue(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CGetInfoJob::DoWork(), ExportToXML(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetLocalArt(), and MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo().
GetOrderFilter()
int CMusicDatabase::GetOrderFilter (const std::string & type, const SortDescription & sorting, Filter & filter)
References AlphanumericSortSQL(), CDatabase::Filter::AppendField(), CDatabase::Filter::AppendOrder(), DatabaseQueryPartSelect, CDatabase::Filter::fields, fields, FieldYear, DatabaseUtils::GetField(), SortUtils::GetFieldsForSQLSort(), name, CDatabase::PrepareSQL(), SortDescription::sortAttributes, SortDescription::sortBy, SortByRandom, SortnameBuildSQL(), SortDescription::sortOrder, SortOrderDescending, and table.
Referenced by GetAlbumsByWhere(), GetAlbumsByWhereJSON(), GetArtistsByWhere(), GetArtistsByWhereJSON(), GetSongsByWhereJSON(), and GetSongsFullByWhere().
GetPathHash()
bool CMusicDatabase::GetPathHash (const std::string & path, std::string & hash)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by MUSIC_INFO::CMusicInfoScanner::DoScan().
GetPaths()
bool CMusicDatabase::GetPaths (std::set< std::string > & paths)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, and CDatabase::m_pDS.
Referenced by MUSIC_INFO::CMusicInfoScanner::Start().
GetRandomSongIDs()
unsigned int CMusicDatabase::GetRandomSongIDs (const Filter & filter, std::vector< std::pair< int, int > > & songIDs)
Gets song IDs in random order that match the filter criteria.
Parameters
filter the criteria to apply in the query
songIDs a vector of <1, id> pairs suited to party mode use
Returns
count of song ids found.
References CDatabase::BuildSQL(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), song_idSong, and CDatabase::Filter::where.
Referenced by CPartyModeManager::Enable().
GetRecentlyAddedAlbums()
bool CMusicDatabase::GetRecentlyAddedAlbums (VECALBUMS & albums, unsigned int limit = 0)
References album_enumCount, album_idAlbum, GetAlbumFromDataset(), GetArtistCreditFromDataset(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded::GetContent(), JSONRPC::CAudioLibrary::GetRecentlyAddedAlbums(), and CRecentlyAddedJob::UpdateMusic().
GetRecentlyAddedAlbumSongs()
bool CMusicDatabase::GetRecentlyAddedAlbumSongs (const std::string & strBaseDir, CFileItemList & item, unsigned int limit = 0)
References CFileItemList::Add(), MUSIC_INFO::CMusicInfoTag::AppendArtistRole(), artistCredit_idRole, CDbUrl::FromString(), GetArtistCreditFromDataset(), GetArtistRoleFromDataset(), GetFileItemFromArtistCredits(), GetFileItemFromDataset(), CFileItem::GetMusicInfoTag(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), ROLE_ARTIST, CFileItemList::Size(), song_enumCount, and song_idSong.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAddedSong::GetContent(), JSONRPC::CAudioLibrary::GetRecentlyAddedSongs(), and CRecentlyAddedJob::UpdateMusic().
GetRecentlyPlayedAlbums()
bool CMusicDatabase::GetRecentlyPlayedAlbums (VECALBUMS & albums)
References CAlbum::Album, album_enumCount, album_idAlbum, end(), GetAlbumFromDataset(), GetArtistCreditFromDataset(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), RECENTLY_PLAYED_LIMIT, and CAlbum::ReleaseTypeToString().
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed::GetContent(), and JSONRPC::CAudioLibrary::GetRecentlyPlayedAlbums().
GetRecentlyPlayedAlbumSongs()
bool CMusicDatabase::GetRecentlyPlayedAlbumSongs (const std::string & strBaseDir, CFileItemList & item)
References CFileItemList::Add(), MUSIC_INFO::CMusicInfoTag::AppendArtistRole(), artistCredit_idRole, CDbUrl::FromString(), GetArtistCreditFromDataset(), GetArtistRoleFromDataset(), GetFileItemFromArtistCredits(), GetFileItemFromDataset(), CFileItem::GetMusicInfoTag(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), ROLE_ARTIST, CFileItemList::Size(), song_enumCount, and song_idSong.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayedSong::GetContent(), and JSONRPC::CAudioLibrary::GetRecentlyPlayedSongs().
GetResumeBookmarkForAudioBook()
bool CMusicDatabase::GetResumeBookmarkForAudioBook (const CFileItem & item, int & bookmark)
References CFileItem::GetDynPath(), CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIWindowMusicBase::OnSelect().
GetRoleById()
std::string CMusicDatabase::GetRoleById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetItemById().
GetRoleByName()
int CMusicDatabase::GetRoleByName (const std::string & strRole)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by GetArtistsByWhereJSON(), GetFilter(), and GetSongsByWhereJSON().
GetRolesByArtist()
bool CMusicDatabase::GetRolesByArtist (int idArtist, CFileItem * item)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), CVariant::push_back(), CGUIListItem::SetProperty(), and CVariant::VariantTypeArray.
Referenced by JSONRPC::CAudioLibrary::GetAdditionalArtistDetails().
GetRolesNav()
bool CMusicDatabase::GetRolesNav (const std::string & strBaseDir, CFileItemList & items, const Filter & filter = Filter())
References CFileItemList::Add(), CDbUrl::AddOption(), CDbUrl::AppendPath(), CDatabase::BuildSQL(), CDbUrl::FromString(), GetFilter(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDbUrl::ToString().
Referenced by GetItems(), JSONRPC::CAudioLibrary::GetRoles(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetSchemaVersion()
int CMusicDatabase::GetSchemaVersion () const override protected virtual
Implements CDatabase.
Referenced by CreateTables(), and SetMusicTagScanVersion().
GetScraper()
bool CMusicDatabase::GetScraper (int id, const CONTENT_TYPE & content, ADDON::ScraperPtr & scraper)
References ADDON::CHOICE_YES, CONTENT_ARTISTS, ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), ADDON::CAddonSystemSettings::GetInstance(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and ADDON::ScraperTypeFromContent().
Referenced by CRefreshInfoJob::DoWork(), CGUIWindowMusicNav::ManageInfoProvider(), and MUSIC_INFO::CMusicInfoScanner::Process().
GetSinglesCount()
int CMusicDatabase::GetSinglesCount ()
References GetSongsCount(), CDatabase::PrepareSQL(), CAlbum::ReleaseTypeToString(), and CAlbum::Single.
Referenced by KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeOverview::GetContent().
GetSong()
bool CMusicDatabase::GetSong (int idSong, CSong & song)
References CSong::AppendArtistRole(), artistCredit_idRole, CSong::artistCredits, CSong::Clear(), GetArtistCreditFromDataset(), GetArtistRoleFromDataset(), GetSongFromDataset(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), ROLE_ARTIST, and song_enumCount.
Referenced by AnnounceBridge(), UPNP::CUPnPServer::Build(), JSONRPC::CAudioLibrary::FillFileItemList(), GetSongByFileName(), JSONRPC::CAudioLibrary::GetSongDetails(), MUSIC_INFO::CMusicInfoTagLoaderDatabase::Load(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CGUIWindowVideoNav::OnContextButton(), JSONRPC::CAudioLibrary::SetSongDetails(), and XFILE::CMusicDatabaseFile::TranslateUrl().
GetSongByArtistAndAlbumAndTitle()
int CMusicDatabase::GetSongByArtistAndAlbumAndTitle (const std::string & strArtist, const std::string & strAlbum, const std::string & strTitle)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIWindowVideoNav::GetContextButtons(), and CGUIWindowVideoNav::OnContextButton().
GetSongByFileName()
bool CMusicDatabase::GetSongByFileName (const std::string & strFileName, CSong & song, int64_t startOffset = 0)
References URIUtils::AddSlashAtEnd(), CSong::Clear(), URIUtils::GetFileName(), CDatabase::GetSingleValueInt(), GetSong(), CURL::IsProtocol(), CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and URIUtils::RemoveExtension().
Referenced by ANNOUNCEMENT::CAnnouncementManager::DoAnnounce(), JSONRPC::CAudioLibrary::FillFileItem(), and CFileItem::LoadMusicTag().
GetSongFromDataset() [1/2]
CSong CMusicDatabase::GetSongFromDataset () private
References GetSongFromDataset(), and CDatabase::m_pDS.
Referenced by GetAlbum(), GetSong(), GetSongFromDataset(), GetSongsByPath(), and RemoveSongsFromPath().
GetSongFromDataset() [2/2]
CSong CMusicDatabase::GetSongFromDataset (const dbiplus::sql_record *const record, int offset = 0) private
References URIUtils::AddFileToFolder(), CSong::bCompilation, CSong::dateAdded, CSong::dateNew, CSong::dateUpdated, CSong::genre, CServiceBroker::GetSettingsComponent(), CSong::iBitRate, CSong::iBPM, CSong::iChannels, CSong::idAlbum, CSong::idSong, CSong::iDuration, CSong::iEndOffset, CSong::iSampleRate, CSong::iStartOffset, CSong::iTimesPlayed, CSong::iTrack, CSong::lastPlayed, CSong::rating, CSong::replayGain, ReplayGain::Set(), CDateTime::SetFromDBDateTime(), song_bCompilation, song_comment, song_dateAdded, song_dateModified, song_dateNew, song_iBitRate, song_iBPM, song_iChannels, song_idAlbum, song_idSong, song_iDuration, song_iEndOffset, song_iSampleRate, song_iStartOffset, song_iTimesPlayed, song_iTrack, song_lastplayed, song_mood, song_rating, song_songVideoURL, song_strAlbum, song_strArtists, song_strArtistSort, song_strDiscSubtitle, song_strFileName, song_strGenres, song_strMusicBrainzTrackID, song_strOrigReleaseDate, song_strPath, song_strReleaseDate, song_strReplayGain, song_strTitle, song_userrating, song_votes, CSong::songVideoURL, CSong::strAlbum, CSong::strArtistDesc, CSong::strArtistSort, CSong::strComment, CSong::strDiscSubtitle, CSong::strFileName, CSong::strMood, CSong::strMusicBrainzTrackID, CSong::strOrigReleaseDate, CSong::strReleaseDate, CSong::strTitle, CSong::userrating, and CSong::votes.
GetSongIDFromPath()
int CMusicDatabase::GetSongIDFromPath (const std::string & filePath) private
References URIUtils::AddSlashAtEnd(), URIUtils::GetFileName(), CURL::IsProtocol(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and URIUtils::RemoveExtension().
Referenced by IncrementPlayCount(), SetSongUserrating(), and SetSongVotes().
GetSongsByArtist()
bool CMusicDatabase::GetSongsByArtist (int idArtist, std::vector< int > & songs)
References CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
GetSongsByPath()
bool CMusicDatabase::GetSongsByPath (const std::string & strPath, MAPSONGS & songmap, bool bAppendToMap = false)
References URIUtils::AddSlashAtEnd(), GetSongFromDataset(), URIUtils::HasSlashAtEnd(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CSong::strFileName.
Referenced by MUSIC_INFO::CMusicInfoLoader::LoadItemLookup().
GetSongsByWhere()
bool CMusicDatabase::GetSongsByWhere (const std::string & baseDir, const Filter & filter, CFileItemList & items, const SortDescription & sortDescription = SortDescription())
References CFileItemList::Add(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), DatabaseUtils::BuildLimitClause(), CDatabase::BuildSQL(), data(), FieldRow, CDatabase::Filter::fields, CDbUrl::FromString(), GetFileItemFromDataset(), GetFilter(), CDatabase::GetSingleValueInt(), CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeSong, CDatabase::PrepareSQL(), CFileItemList::Reserve(), CGUIListItem::SetProperty(), CFileItemList::Size(), SortDescription::sortBy, SortByNone, SortUtils::SortFromDataset(), and CDatabase::Filter::where.
GetSongsByWhereJSON()
bool CMusicDatabase::GetSongsByWhereJSON (const std::set< std::string > & fields, const std::string & baseDir, CVariant & result, int & total, const SortDescription & sortDescription = SortDescription())
References CDatabase::DatasetLayout::AdjustRecordNumbers(), CVariant::append(), CDatabase::Filter::AppendField(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDatabase::Filter::AppendOrder(), BLANKARTIST_ID, DatabaseUtils::BuildLimitClause(), CDatabase::BuildSQL(), CVariant::clear(), CVariant::empty(), end(), CVariant::end_array(), translateJSONField::fieldJSON, CDatabase::Filter::fields, fields, CDbUrl::FromString(), CDatabase::DatasetLayout::GetFetch(), CDatabase::DatasetLayout::GetFields(), GetFilter(), DatabaseUtils::GetLimitCount(), GetOrderFilter(), CDatabase::DatasetLayout::GetOutput(), CDatabase::DatasetLayout::GetRecNo(), GetRoleByName(), CServiceBroker::GetSettingsComponent(), CDatabase::GetSingleValueInt(), CDatabase::DatasetLayout::HasFilterFields(), CVariant::isArray(), CVariant::isMember(), CDatabase::Filter::join, joinToSongs_enumCount, joinToSongs_idAlbumArtist, joinToSongs_idArtist, joinToSongs_idGenre, joinToSongs_idRole, joinToSongs_strAlbumArtist, joinToSongs_strAlbumArtistMBID, joinToSongs_strArtist, joinToSongs_strArtistMBID, joinToSongs_strRole, JSONtoDBSong, CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeSong, name, NUM_SONG_FIELDS, CDatabase::Filter::order, CDatabase::PrepareSQL(), KODI::UTILS::RandomShuffle(), CVariant::reserve(), CDatabase::DatasetLayout::SetField(), CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE, SortDescription::sortBy, SortByRandom, CVariant::VariantTypeArray, and CDatabase::Filter::where.
Referenced by JSONRPC::CAudioLibrary::GetSongs().
GetSongsByYear()
bool CMusicDatabase::GetSongsByYear (const std::string & baseDir, CFileItemList & items, int year)
References CDbUrl::AddOption(), CDbUrl::FromString(), and GetSongsFullByWhere().
GetSongsCount()
int CMusicDatabase::GetSongsCount (const Filter & filter = Filter())
References CDatabase::BuildSQL(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::Filter::where.
Referenced by CommitTransaction(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), and GetSinglesCount().
GetSongsFullByWhere()
bool CMusicDatabase::GetSongsFullByWhere (const std::string & baseDir, const Filter & filter, CFileItemList & items, const SortDescription & sortDescription = SortDescription(), bool artistData = false)
References CFileItemList::Add(), MUSIC_INFO::CMusicInfoTag::AppendArtistRole(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDatabase::Filter::AppendOrder(), artistCredit_idRole, DatabaseUtils::BuildLimitClauseOnly(), CDatabase::BuildSQL(), data(), end(), FieldRow, CDatabase::Filter::fields, fields, CDbUrl::FromString(), GetArtistCreditFromDataset(), GetArtistRoleFromDataset(), DatabaseUtils::GetDatabaseResults(), GetFileItemFromArtistCredits(), GetFileItemFromDataset(), GetFilter(), CFileItem::GetMusicInfoTag(), GetOrderFilter(), CServiceBroker::GetSettingsComponent(), CDatabase::GetSingleValueInt(), CDatabase::Filter::join, CDatabase::Filter::limit, SortDescription::limitEnd, SortDescription::limitStart, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeSong, CDatabase::Filter::order, CFileItemList::Reserve(), ROLE_ARTIST, CGUIListItem::SetProperty(), CFileItemList::SetSortMethod(), CFileItemList::SetSortOrder(), CSettings::SETTING_MUSICLIBRARY_USEARTISTSORTNAME, CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE, CFileItemList::Size(), song_enumCount, song_idSong, CFileItemList::Sort(), SortDescription::sortAttributes, SortAttributeUseArtistSortName, SortDescription::sortBy, SortByRandom, SortDescription::sortOrder, and CDatabase::Filter::where.
Referenced by CPartyModeManager::AddRandomSongs(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSingles::GetContent(), GetItems(), GetSongsByYear(), and GetSongsNav().
GetSongsLastAdded()
std::string CMusicDatabase::GetSongsLastAdded ()
References CDatabase::GetSingleValue().
Referenced by JSONRPC::CAudioLibrary::GetProperties().
GetSongsLastModified()
std::string CMusicDatabase::GetSongsLastModified ()
References CDatabase::GetSingleValue().
Referenced by JSONRPC::CAudioLibrary::GetProperties().
GetSongsNav()
bool CMusicDatabase::GetSongsNav (const std::string & strBaseDir, CFileItemList & items, int idGenre, int idArtist, int idAlbum, const SortDescription & sortDescription = SortDescription())
References CDbUrl::AddOption(), CDbUrl::FromString(), GetSongsFullByWhere(), and CDbUrl::ToString().
Referenced by JSONRPC::CAudioLibrary::FillFileItemList(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSong::GetContent(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetSourceById()
std::string CMusicDatabase::GetSourceById (int id)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by GetItemById().
GetSourceByName()
int CMusicDatabase::GetSourceByName (const std::string & strSource)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddSource(), and GetFilter().
GetSourceFromPath()
int CMusicDatabase::GetSourceFromPath (const std::string & strPath)
References URIUtils::AddSlashAtEnd(), URIUtils::HasSlashAtEnd(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by MUSIC_INFO::CMusicInfoScanner::Start().
GetSources()
bool CMusicDatabase::GetSources (CFileItemList & items)
References CFileItemList::Add(), CVariant::clear(), CVariant::empty(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CVariant::push_back(), CGUIListItem::SetProperty(), CFileItemList::Size(), and CVariant::VariantTypeArray.
Referenced by JSONRPC::CAudioLibrary::GetSources(), MigrateSources(), and UpdateSources().
GetSourcesByAlbum()
bool CMusicDatabase::GetSourcesByAlbum (int idAlbum, CFileItem * item)
Todo:
: handle singles, or don't waste time checking songs
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::m_pDS2, CDatabase::PrepareSQL(), CVariant::push_back(), CGUIListItem::SetProperty(), and CVariant::VariantTypeArray.
Referenced by JSONRPC::CAudioLibrary::GetAdditionalAlbumDetails().
GetSourcesByArtist()
bool CMusicDatabase::GetSourcesByArtist (int idArtist, CFileItem * item)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), CVariant::push_back(), CGUIListItem::SetProperty(), and CVariant::VariantTypeArray.
Referenced by JSONRPC::CAudioLibrary::GetAdditionalArtistDetails().
GetSourcesBySong()
bool CMusicDatabase::GetSourcesBySong (int idSong, const std::string & strPath, CFileItem * item)
References URIUtils::AddSlashAtEnd(), URIUtils::HasSlashAtEnd(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), CVariant::push_back(), CGUIListItem::SetProperty(), and CVariant::VariantTypeArray.
Referenced by JSONRPC::CAudioLibrary::GetAdditionalSongDetails().
GetSourcesNav()
bool CMusicDatabase::GetSourcesNav (const std::string & strBaseDir, CFileItemList & items, const Filter & filter = Filter(), bool countOnly = false)
References CFileItemList::Add(), CDbUrl::AddOption(), CDatabase::Filter::AppendGroup(), CDatabase::Filter::AppendJoin(), CDbUrl::AppendPath(), CDatabase::BuildSQL(), CDatabase::Filter::fields, CDbUrl::FromString(), GetFilter(), CDatabase::Filter::group, CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::Filter::order, CDatabase::PrepareSQL(), CDbUrl::ToString(), and CDatabase::Filter::where.
Referenced by CGUIDialogMediaFilter::GetItems(), GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
GetTop100()
bool CMusicDatabase::GetTop100 (const std::string & strBaseDir, CFileItemList & items)
References CFileItemList::Add(), CDbUrl::FromString(), GetFileItemFromDataset(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CFileItemList::Reserve().
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSongTop100::GetContent().
GetTop100Albums()
bool CMusicDatabase::GetTop100Albums (VECALBUMS & albums)
References album_enumCount, album_idAlbum, GetAlbumFromDataset(), GetArtistCreditFromDataset(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, and CDatabase::m_pDS.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100::GetContent().
GetTop100AlbumSongs()
bool CMusicDatabase::GetTop100AlbumSongs (const std::string & strBaseDir, CFileItemList & item)
References CFileItemList::Add(), CDbUrl::FromString(), GetFileItemFromDataset(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CFileItemList::Reserve().
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100Song::GetContent().
GetTranslateBlankArtist()
bool CMusicDatabase::GetTranslateBlankArtist () inline
References m_translateBlankArtist.
GetUsedImages()
std::vector< std::string > CMusicDatabase::GetUsedImages (const std::vector< std::string > & imagesToCheck) const
Check the passed in list of images if used in this database. Used to clean the image cache.
Parameters
imagesToCheck
Returns
a list of the passed in images used by this database.
References CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CSettings::MUSICLIBRARY_ARTWORK_LEVEL_BASIC, CSettings::MUSICLIBRARY_ARTWORK_LEVEL_NONE, CDatabase::PrepareSQL(), and CSettings::SETTING_MUSICLIBRARY_ARTWORKLEVEL.
GetYearsNav()
bool CMusicDatabase::GetYearsNav (const std::string & strBaseDir, CFileItemList & items, const Filter & filter = Filter())
References CFileItemList::Add(), CDbUrl::AddOption(), CDbUrl::AppendPath(), CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), CDbUrl::FromString(), GetFilter(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE, and CDbUrl::ToString().
Referenced by GetItems(), and CGUIDialogSmartPlaylistRule::OnBrowse().
HasAlbumBeenScraped()
bool CMusicDatabase::HasAlbumBeenScraped (int idAlbum)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by MUSIC_INFO::CMusicInfoScanner::Process().
HasArtistBeenScraped()
bool CMusicDatabase::HasArtistBeenScraped (int idArtist)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by MUSIC_INFO::CMusicInfoScanner::Process().
ImportFromXML()
void CMusicDatabase::ImportFromXML (const std::string & xmlFile, CGUIDialogProgress * progressDialog = nullptr)
References CDatabase::BeginTransaction(), CGUIWindow::Close(), CommitTransaction(), GetAlbum(), GetAlbumByMatch(), GetArtist(), GetArtistByMatch(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetLibraryInfoProvider(), ImportSongHistory(), CGUIDialogProgress::IsCanceled(), CAlbum::Load(), CArtist::Load(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGDEBUG, LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CAlbum::MergeScrapedAlbum(), CArtist::MergeScrapedArtist(), CGUIDialogProgress::Progress(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::ResetLibraryBools(), CDatabase::RollbackTransaction(), root, CGUIDialogBoxBase::SetLine(), CGUIDialogProgress::SetPercentage(), KODI::MESSAGING::HELPERS::ShowOKDialogLines(), CAlbum::strAlbum, CArtist::strArtist, UpdateAlbum(), and UpdateArtist().
Referenced by CMusicLibraryImportJob::Work().
ImportSongHistory()
bool CMusicDatabase::ImportSongHistory (const std::string & xmlFile, const int total, CGUIDialogProgress * progressDialog = nullptr)
References CDatabase::BeginTransaction(), CommitTransaction(), CDatabase::Compress(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetEventLog(), XMLUtils::GetFloat(), XMLUtils::GetInt(), CDatabase::GetSingleValueInt(), XMLUtils::GetString(), Information, CGUIDialogProgress::IsCanceled(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGERROR, LOGINFO, CDatabase::m_pDS, CDatabase::PrepareSQL(), CGUIDialogProgress::Progress(), CDatabase::RollbackTransaction(), root, MathUtils::round_int(), CGUIDialogBoxBase::SetLine(), and CGUIDialogProgress::SetPercentage().
Referenced by ImportFromXML().
IncrementPlayCount()
void CMusicDatabase::IncrementPlayCount (const CFileItem & item)
Increment the playcount of an item Increments the playcount and updates the last played date.
Parameters
item CFileItem to increment the playcount for
References CDateTime::GetAsDBDateTime(), CDateTime::GetCurrentDateTime(), CFileItem::GetPath(), GetSongIDFromPath(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CSaveFileState::DoWork().
InsideScannedPath()
bool CMusicDatabase::InsideScannedPath (const std::string & path)
Checks if the given path is inside a folder that has already been scanned into the library.
Parameters
path the path we want to check
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by KODI::CDRIP::CCDDARipper::OnJobComplete().
IsAlbumBoxset()
bool CMusicDatabase::IsAlbumBoxset (int idAlbum)
References CDatabase::GetSingleValueInt(), and CDatabase::PrepareSQL().
Referenced by AddSong(), XFILE::CMusicDatabaseDirectory::GetDirectory(), and UpdateAlbum().
IsSongAlbumArtist()
bool CMusicDatabase::IsSongAlbumArtist (int idSong, int idArtist)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by MUSIC_UTILS::CSetArtJob::HasSongExtraArtChanged().
IsSongArtist()
bool CMusicDatabase::IsSongArtist (int idSong, int idArtist)
References CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by MUSIC_UTILS::CSetArtJob::HasSongExtraArtChanged().
LookupCDDBInfo()
bool CMusicDatabase::LookupCDDBInfo (bool bRequery = false)
References URIUtils::AddFileToFolder(), CGUIWindow::Close(), XFILE::CFile::Delete(), E_NO_MATCH_FOUND, E_WAIT_FOR_INPUT, MEDIA_DETECT::CCdInfo::GetCddbDiscId(), CProfileManager::GetCDDBFolder(), CServiceBroker::GetGUI(), CDDB::Xcddb::getInexactArtist(), CDDB::Xcddb::getInexactTitle(), CDDB::Xcddb::getLastError(), CDDB::Xcddb::getLastErrorText(), CServiceBroker::GetMediaManager(), CServiceBroker::GetNetwork(), CServiceBroker::GetSettingsComponent(), MEDIA_DETECT::CCdInfo::GetTrackCount(), CGUIComponent::GetWindowManager(), MEDIA_DETECT::CCdInfo::HasCDDBInfo(), CDDB::Xcddb::isCDCached(), CDatabase::m_profileManager, CGUIDialogProgress::Open(), CDDB::Xcddb::queryCDinfo(), CDDB::Xcddb::setCacheDir(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), MEDIA_DETECT::CCdInfo::SetNoCDDBInfo(), CSettings::SETTING_AUDIOCDS_USECDDB, KODI::MESSAGING::HELPERS::ShowOKDialogLines(), CGUIDialogProgress::ShowProgressBar(), WINDOW_DIALOG_PROGRESS, and WINDOW_DIALOG_SELECT.
Referenced by XFILE::CCDDADirectory::GetDirectory(), and CGUIWindowMusicBase::OnContextButton().
MigrateSources()
bool CMusicDatabase::MigrateSources () private
Initially fills source table from sources.xml for use only at migration of db from an earlier version than 72 returns true when successfully done.
References CMediaSourceSettings::GetInstance(), GetSources(), CLog::Log(), LOGERROR, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by UpdateTables().
NormaliseSongDates()
void CMusicDatabase::NormaliseSongDates (std::string & strRelease, std::string & strOriginal) private
Referenced by AddSong(), and UpdateSong().
Open()
bool CMusicDatabase::Open () override virtual
Reimplemented from CDatabase.
References CServiceBroker::GetSettingsComponent(), and CDatabase::Open().
Referenced by CPartyModeManager::AddRandomSongs(), UPNP::CUPnPServer::Announce(), AnnounceBridge(), UPNP::CUPnPServer::Build(), Clean(), ANNOUNCEMENT::CAnnouncementManager::DoAnnounce(), CGUIDialogVideoInfo::DoSearch(), CGetInfoJob::DoWork(), CRefreshInfoJob::DoWork(), CGetSongInfoJob::DoWork(), CMusicLibraryJob::DoWork(), CSaveFileState::DoWork(), CSetUserratingJob::DoWork(), MUSIC_UTILS::CSetArtJob::DoWork(), MUSIC_UTILS::CSetSongRatingJob::DoWork(), CPartyModeManager::Enable(), MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), MUSIC_UTILS::FillArtTypesList(), JSONRPC::CAudioLibrary::FillFileItem(), JSONRPC::CAudioLibrary::FillFileItemList(), CMusicThumbLoader::FillLibraryArt(), CVideoThumbLoader::FillLibraryArt(), JSONRPC::CAudioLibrary::GetAdditionalAlbumDetails(), JSONRPC::CAudioLibrary::GetAdditionalArtistDetails(), JSONRPC::CAudioLibrary::GetAdditionalSongDetails(), JSONRPC::CAudioLibrary::GetAlbumDetails(), JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CAudioLibrary::GetArtistDetails(), JSONRPC::CAudioLibrary::GetArtists(), JSONRPC::CAudioLibrary::GetAvailableArt(), JSONRPC::CAudioLibrary::GetAvailableArtTypes(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAddedSong::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayedSong::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100Song::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeOverview::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSingles::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSong::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSongTop100::GetContent(), CGUIWindowVideoNav::GetContextButtons(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetCurrentArt(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CMusicSearchDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), JSONRPC::CAudioLibrary::GetGenres(), CGUIDialogMediaFilter::GetItems(), XFILE::CMusicDatabaseDirectory::GetLabel(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetLocalArt(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped::GetLocalizedName(), CGUIDialogMediaFilter::GetMinMax(), JSONRPC::CAudioLibrary::GetProperties(), JSONRPC::CAudioLibrary::GetRecentlyAddedAlbums(), JSONRPC::CAudioLibrary::GetRecentlyAddedSongs(), JSONRPC::CAudioLibrary::GetRecentlyPlayedAlbums(), JSONRPC::CAudioLibrary::GetRecentlyPlayedSongs(), JSONRPC::CAudioLibrary::GetRoles(), JSONRPC::CAudioLibrary::GetSongDetails(), JSONRPC::CAudioLibrary::GetSongs(), JSONRPC::CAudioLibrary::GetSources(), ADDON::CScraper::IsInUse(), MUSIC_INFO::CMusicInfoTagLoaderDatabase::Load(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CFileItem::LoadMusicTag(), CGUIWindowMusicBase::OnAssignContent(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIWindowVideoNav::OnContextButton(), KODI::CDRIP::CCDDARipper::OnJobComplete(), MUSIC_INFO::CMusicInfoLoader::OnLoaderStart(), CMusicThumbLoader::OnLoaderStart(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicBase::OnRemoveSource(), UPNP::CUPnPServer::OnSearchContainer(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::PersistArt(), MUSIC_INFO::CMusicInfoScanner::Process(), JSONRPC::CAudioLibrary::RefreshAlbum(), JSONRPC::CAudioLibrary::RefreshArtist(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetArtistDetails(), CGUIDialogVideoInfo::SetMovie(), JSONRPC::CAudioLibrary::SetSongDetails(), MUSIC_INFO::CMusicInfoScanner::Start(), XFILE::CMusicDatabaseFile::TranslateUrl(), MUSIC_INFO::CMusicInfoScanner::UpdateAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::UpdateArtistInfo(), CRecentlyAddedJob::UpdateMusic(), and CRecentlyAddedJob::UpdateTotal().
RemoveArtForItem() [1/2]
bool CMusicDatabase::RemoveArtForItem (int mediaId, const MediaType & mediaType, const std::set< std::string > & artTypes)
Remove art for a database item. Removes multiple pieces of art for a database item.
Parameters
mediaId the id in the media (song/artist/album) table.
mediaType the type of media, which corresponds to the table the item resides in (song/artist/album).
arttypes a set of types, e.g. "thumb", "fanart", etc. to be removed.
Returns
true if art is removed, false if no art is found.
See also
RemoveArtForItem
References RemoveArtForItem().
RemoveArtForItem() [2/2]
bool CMusicDatabase::RemoveArtForItem (int mediaId, const MediaType & mediaType, const std::string & artType)
Remove art for a database item. Removes a single piece of art for a database item.
Parameters
mediaId the id in the media (song/artist/album) table.
mediaType the type of media, which corresponds to the table the item resides in (song/artist/album).
artType the type of art to remove, eg "thumb", "fanart".
Returns
true if art is removed, false if no art is found.
See also
RemoveArtForItem
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
Referenced by MUSIC_UTILS::CSetArtJob::DoWork(), RemoveArtForItem(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetArtistDetails(), and JSONRPC::CAudioLibrary::SetSongDetails().
RemoveSongsFromPath()
bool CMusicDatabase::RemoveSongsFromPath (const std::string & path, MAPSONGS & songmap, bool exact = true)
Todo:
SQLite probably doesn't allow this, but can we rely on that??
Todo:
move this below the m_pDS->exec block, once UPnP doesn't rely on this anymore
References URIUtils::AddSlashAtEnd(), AnnounceRemove(), GetArtForItem(), GetSongFromDataset(), URIUtils::HasSlashAtEnd(), CSong::idSong, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeSong, CDatabase::PrepareSQL(), SetLibraryLastUpdated(), CSong::strFileName, and CSong::strThumb.
Referenced by CGUIWindowMusicBase::OnRemoveSource(), and MUSIC_INFO::CMusicInfoScanner::RetrieveMusicInfo().
RemoveSource()
bool CMusicDatabase::RemoveSource (const std::string & strName)
References CDatabase::ExecuteQuery(), CDatabase::PrepareSQL(), and SetLibraryLastCleaned().
Referenced by CGUIWindowMusicBase::OnRemoveSource().
ScraperInUse()
bool CMusicDatabase::ScraperInUse (const std::string & scraperID) const
Check whether a given scraper is in use.
Parameters
scraperID the scraper to check for.
Returns
true if the scraper is in use, false otherwise.
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by ADDON::CScraper::IsInUse().
Search()
bool CMusicDatabase::Search (const std::string & search, CFileItemList & items)
References end(), CLog::Log(), LOGDEBUG, SearchAlbums(), SearchArtists(), and SearchSongs().
Referenced by XFILE::CMusicSearchDirectory::GetDirectory().
SearchAlbums()
bool CMusicDatabase::SearchAlbums (const std::string & search, CFileItemList & albums) private
References CFileItemList::Add(), g_localizeStrings, CLocalizeStrings::Get(), GetAlbumFromDataset(), CAlbum::idAlbum, label, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MIN_FULL_SEARCH_LENGTH, CDatabase::PrepareSQL(), and CAlbum::strAlbum.
Referenced by Search().
SearchAlbumsByArtistName()
bool CMusicDatabase::SearchAlbumsByArtistName (const std::string & strArtist, CFileItemList & items)
References CFileItemList::Add(), GetAlbumFromDataset(), CAlbum::idAlbum, label, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CAlbum::strAlbum.
Referenced by CGUIDialogVideoInfo::DoSearch().
SearchArtists()
bool CMusicDatabase::SearchArtists (const std::string & search, CFileItemList & artists) private
References CFileItemList::Add(), g_localizeStrings, CLocalizeStrings::Get(), label, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeArtist, MIN_FULL_SEARCH_LENGTH, and CDatabase::PrepareSQL().
Referenced by Search().
SearchSongs()
bool CMusicDatabase::SearchSongs (const std::string & strSearch, CFileItemList & songs) private
References CFileItemList::Add(), CDbUrl::FromString(), GetFileItemFromDataset(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MIN_FULL_SEARCH_LENGTH, and CDatabase::PrepareSQL().
Referenced by Search().
SetAlbumUserrating()
bool CMusicDatabase::SetAlbumUserrating (const int idAlbum, int userrating)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CSetUserratingJob::DoWork().
SetArtForItem() [1/2]
void CMusicDatabase::SetArtForItem (int mediaId, const std::string & mediaType, const std::map< std::string, std::string > & art)
Sets art for a database item. Sets multiple pieces of art for a database item.
Parameters
mediaId the id in the media (song/artist/album) table.
mediaType the type of media, which corresponds to the table the item resides in (song/artist/album).
art a map of <type, url> where type is "thumb", "fanart", etc. and url is the original url of the art.
See also
GetArtForItem
References SetArtForItem().
SetArtForItem() [2/2]
void CMusicDatabase::SetArtForItem (int mediaId, const std::string & mediaType, const std::string & artType, const std::string & url)
Sets art for a database item. Sets a single piece of art for a database item.
Parameters
mediaId the id in the media (song/artist/album) table.
mediaType the type of media, which corresponds to the table the item resides in (song/artist/album).
artType the type of art to set, e.g. "thumb", "fanart"
url the url to the art (this is the original url, not a cached url).
See also
GetArtForItem
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddAlbum(), MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), MUSIC_INFO::CMusicInfoScanner::AddArtistArtwork(), AddSong(), MUSIC_UTILS::CSetArtJob::DoWork(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::PersistArt(), SetArtForItem(), JSONRPC::CAudioLibrary::SetSongDetails(), UpdateAlbum(), and UpdateArtist().
SetArtistLinksUpdated()
void CMusicDatabase::SetArtistLinksUpdated ()
References CDateTime::GetAsDBDateTime(), CDateTime::GetUTCDateTime(), CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CheckArtistLinksChanged().
SetItemUpdated()
void CMusicDatabase::SetItemUpdated (int mediaId, const std::string & mediaType)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, MediaTypeAlbum, MediaTypeArtist, MediaTypeSong, and CDatabase::PrepareSQL().
Referenced by MUSIC_UTILS::CSetArtJob::DoWork().
SetLibraryLastCleaned()
void CMusicDatabase::SetLibraryLastCleaned ()
References CDateTime::GetAsDBDateTime(), CDateTime::GetUTCDateTime(), CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by Cleanup(), and RemoveSource().
SetLibraryLastUpdated()
void CMusicDatabase::SetLibraryLastUpdated ()
References CDateTime::GetAsDBDateTime(), CDateTime::GetUTCDateTime(), CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by AddAlbum(), CleanupOrphanedItems(), RemoveSongsFromPath(), UpdateAlbum(), UpdateArtist(), and UpdateTables().
SetMusicNeedsTagScan()
void CMusicDatabase::SetMusicNeedsTagScan (int version)
Set minimum version number of db needed when tag data scanned from music files.
Parameters
version the version number of db
References CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by UpdateTables().
SetMusicTagScanVersion()
void CMusicDatabase::SetMusicTagScanVersion (int version = 0)
Set the version number of tag data.
Parameters
version the version number of db when tags last scanned, 0 (default) means current db version
References GetSchemaVersion(), CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIWindowMusicBase::OnInitWindow(), and UpdateTables().
SetPathHash()
bool CMusicDatabase::SetPathHash (const std::string & path, const std::string & hash)
References AddPath(), XFILE::CDirectory::Exists(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by MUSIC_INFO::CMusicInfoScanner::DoScan().
SetPropertiesForFileItem()
void CMusicDatabase::SetPropertiesForFileItem (CFileItem & item)
References CVariant::begin_array(), MUSIC_INFO::CMusicInfoTag::GetAlbum(), GetAlbum(), GetAlbumByName(), MUSIC_INFO::CMusicInfoTag::GetAlbumId(), GetArtist(), GetArtistByName(), MUSIC_INFO::CMusicInfoTag::GetArtistString(), CFileItem::GetMusicInfoTag(), CGUIListItem::GetProperty(), CFileItem::HasMusicInfoTag(), CGUIListItem::HasProperty(), CVariant::isArray(), SetPropertiesFromAlbum(), and SetPropertiesFromArtist().
Referenced by CPartyModeManager::AddRandomSongs(), and CGUIWindowMusicNav::OnClick().
SetPropertiesFromAlbum()
void CMusicDatabase::SetPropertiesFromAlbum (CFileItem & item, const CAlbum & album) static
References CAlbum::bBoxedSet, CAlbum::fRating, CAlbum::genre, CAlbum::GetAlbumArtist(), CAlbum::GetAlbumArtistString(), CServiceBroker::GetSettingsComponent(), CAlbum::iAlbumDuration, CAlbum::iTotalDiscs, CAlbum::iUserrating, CAlbum::iVotes, CAlbum::moods, CAlbum::releaseType, CAlbum::ReleaseTypeToString(), CGUIListItem::SetProperty(), CAlbum::strAlbum, CAlbum::strLabel, CAlbum::strReview, CAlbum::strType, CAlbum::styles, CAlbum::themes, and TIME_FORMAT_GUESS.
Referenced by CGetInfoJob::DoWork(), CRefreshInfoJob::DoWork(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CFileItem::SetFromAlbum(), and SetPropertiesForFileItem().
SetPropertiesFromArtist()
void CMusicDatabase::SetPropertiesFromArtist (CFileItem & item, const CArtist & artist) static
References CArtist::genre, CServiceBroker::GetSettingsComponent(), CArtist::instruments, CArtist::moods, CGUIListItem::SetProperty(), CArtist::strBiography, CArtist::strBorn, CArtist::strDied, CArtist::strDisambiguation, CArtist::strDisbanded, CArtist::strFormed, CArtist::strGender, CArtist::strSortName, CArtist::strType, CArtist::styles, and CArtist::yearsActive.
Referenced by CGetInfoJob::DoWork(), CRefreshInfoJob::DoWork(), GetArtistsByWhere(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), and SetPropertiesForFileItem().
SetResumeBookmarkForAudioBook()
bool CMusicDatabase::SetResumeBookmarkForAudioBook (const CFileItem & item, int bookmark)
References AddAudioBook(), CDatabase::ExecuteQuery(), CFileItem::GetDynPath(), CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CSaveFileState::DoWork().
SetScraper()
bool CMusicDatabase::SetScraper (int id, const CONTENT_TYPE & content, const ADDON::ScraperPtr & scraper)
References CDatabase::BeginTransaction(), CommitTransaction(), CONTENT_ARTISTS, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::RollbackTransaction().
Referenced by CGUIWindowMusicNav::ManageInfoProvider().
SetScraperAll()
bool CMusicDatabase::SetScraperAll (const std::string & strBaseDir, const ADDON::ScraperPtr & scraper)
References CDatabase::BeginTransaction(), CDatabase::BuildSQL(), CleanupInfoSettings(), CommitTransaction(), CONTENT_ALBUMS, CONTENT_ARTISTS, CONTENT_NONE, CDbUrl::FromString(), GetFilter(), CDbUrl::GetType(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::RollbackTransaction().
Referenced by CGUIWindowMusicNav::ManageInfoProvider().
SetSongUserrating() [1/2]
bool CMusicDatabase::SetSongUserrating (const std::string & filePath, int userrating)
References GetSongIDFromPath(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and SetSongUserrating().
Referenced by MUSIC_UTILS::CSetSongRatingJob::DoWork(), and SetSongUserrating().
SetSongUserrating() [2/2]
bool CMusicDatabase::SetSongUserrating (int idSong, int userrating)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
SetSongVotes()
bool CMusicDatabase::SetSongVotes (const std::string & filePath, int votes)
References GetSongIDFromPath(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
SetTranslateBlankArtist()
void CMusicDatabase::SetTranslateBlankArtist (bool translate) inline
References m_translateBlankArtist.
Referenced by JSONRPC::CAudioLibrary::GetArtists().
SortnameBuildSQL()
std::string CMusicDatabase::SortnameBuildSQL (const std::string & strAlias, const SortAttribute & sortAttributes, const std::string & strField, const std::string & strSortField) private
Build SQL for sort name scalar subquery from sort attributes and ignore article list.
Parameters
strAlias alias name of scalar subquery field
sortAttributes the sort attributes e.g. SortAttributeIgnoreArticle
strField original name or title field that articles could be removed from
strSortField sort name or title field to be used instead of original (when data not null)
Returns
SQL string e.g. CASE WHEN strArtistSort IS NOT NULL THEN strArtistSort WHEN strField LIKE 'the ' OR strField LIKE 'the_' ESCAPE '_' THEN SUBSTR(strArtist, 5) ELSE strField END AS strAlias
References GetIgnoreArticleSQL(), CDatabase::PrepareSQL(), SortAttributeIgnoreArticle, and SortAttributeUseArtistSortName.
Referenced by GetOrderFilter().
SplitPath()
void CMusicDatabase::SplitPath (const std::string & strFileNameAndPath, std::string & strPath, std::string & strFileName) private
References CURL::GetProtocolOptions(), URIUtils::IsURL(), and URIUtils::Split().
TrimImageURLs()
bool CMusicDatabase::TrimImageURLs (std::string & strImage, const size_t space) private
Referenced by UpdateAlbum(), UpdateArtist(), and UpdateTables().
UpdateAlbum() [1/2]
bool CMusicDatabase::UpdateAlbum (CAlbum & album)
Update an album and all its nested entities (artists, songs etc)
Parameters
album the album to update
Returns
true or false
References AddAlbumArtist(), AddArtist(), CAlbum::art, CAlbum::artistCredits, CAlbum::bArtistSongMerge, CAlbum::bBoxedSet, CAlbum::bCompilation, CDatabase::BeginTransaction(), BLANKARTIST_ID, BLANKARTIST_NAME, CAlbum::bScrapedMBID, CheckArtistLinksChanged(), CommitTransaction(), DeleteAlbumArtistsByAlbum(), CDatabase::ExecuteQuery(), CAlbum::fRating, g_localizeStrings, CLocalizeStrings::Get(), CAlbum::GetAlbumArtistSort(), CAlbum::GetAlbumArtistString(), CScraperUrl::GetData(), CAlbum::GetGenreString(), CServiceBroker::GetSettingsComponent(), CDatabase::GetSingleValue(), CDatabase::GetSingleValueInt(), CAlbum::idAlbum, IsAlbumBoxset(), CAlbum::iUserrating, CAlbum::iVotes, CLog::Log(), LOGINFO, CDatabase::m_pDS, MediaTypeAlbum, CAlbum::moods, CDatabase::PrepareSQL(), CAlbum::releaseType, SetArtForItem(), SetLibraryLastUpdated(), CAlbum::songs, CAlbum::strAlbum, CAlbum::strLabel, CAlbum::strMusicBrainzAlbumID, CAlbum::strOrigReleaseDate, CAlbum::strReleaseDate, CAlbum::strReleaseGroupMBID, CAlbum::strReleaseStatus, CAlbum::strReview, CAlbum::strType, CAlbum::styles, CAlbum::themes, CAlbum::thumbURL, UpdateAlbum(), UpdateArtistScrapedMBID(), and UpdateSong().
Referenced by ImportFromXML(), JSONRPC::CAudioLibrary::SetAlbumDetails(), UpdateAlbum(), and MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseAlbumInfo().
UpdateAlbum() [2/2]
int CMusicDatabase::UpdateAlbum (int idAlbum, const std::string & strAlbum, const std::string & strMusicBrainzAlbumID, const std::string & strReleaseGroupMBID, const std::string & strArtist, const std::string & strArtistSort, const std::string & strGenre, const std::string & strMoods, const std::string & strStyles, const std::string & strThemes, const std::string & strReview, const std::string & strImage, const std::string & strLabel, const std::string & strType, const std::string & strReleaseStatus, float fRating, int iUserrating, int iVotes, const std::string & strReleaseDate, const std::string & strOrigReleaseDate, bool bBoxedSet, bool bCompilation, CAlbum::ReleaseType releaseType, bool bScrapedMBID)
References AnnounceUpdate(), CDatabase::ExecuteQuery(), CDateTime::GetAsDBDateTime(), CServiceBroker::GetSettingsComponent(), CDateTime::GetUTCDateTime(), MediaTypeAlbum, CDatabase::PrepareSQL(), CAlbum::ReleaseTypeToString(), and TrimImageURLs().
UpdateArtist() [1/2]
bool CMusicDatabase::UpdateArtist (const CArtist & artist)
References AddArtistDiscography(), AddArtistVideoLinks(), CArtist::art, CArtist::bScrapedMBID, DeleteArtistDiscography(), DeleteArtistVideoLinks(), CArtist::discography, CArtist::genre, CScraperUrl::GetData(), CServiceBroker::GetSettingsComponent(), CArtist::idArtist, CArtist::instruments, CLog::Log(), LOGERROR, MediaTypeArtist, CArtist::moods, SetArtForItem(), SetLibraryLastUpdated(), CArtist::strArtist, CArtist::strBiography, CArtist::strBorn, CArtist::strDied, CArtist::strDisambiguation, CArtist::strDisbanded, CArtist::strFormed, CArtist::strGender, CArtist::strMusicBrainzArtistID, CArtist::strSortName, CArtist::strType, CArtist::styles, CArtist::thumbURL, UpdateArtist(), and CArtist::yearsActive.
Referenced by ImportFromXML(), JSONRPC::CAudioLibrary::SetArtistDetails(), UpdateArtist(), and MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo().
UpdateArtist() [2/2]
int CMusicDatabase::UpdateArtist (int idArtist, const std::string & strArtist, const std::string & strSortName, const std::string & strMusicBrainzArtistID, bool bScrapedMBID, const std::string & strType, const std::string & strGender, const std::string & strDisambiguation, const std::string & strBorn, const std::string & strFormed, const std::string & strGenres, const std::string & strMoods, const std::string & strStyles, const std::string & strInstruments, const std::string & strBiography, const std::string & strDied, const std::string & strDisbanded, const std::string & strYearsActive, const std::string & strImage)
References AnnounceUpdate(), CDatabase::ExecuteQuery(), GetArtistFromMBID(), CDateTime::GetAsDBDateTime(), CServiceBroker::GetSettingsComponent(), CDateTime::GetUTCDateTime(), CLog::Log(), LOGDEBUG, MediaTypeArtist, CDatabase::PrepareSQL(), and TrimImageURLs().
UpdateArtistScrapedMBID()
bool CMusicDatabase::UpdateArtistScrapedMBID (int idArtist, const std::string & strMusicBrainzArtistID)
References AnnounceUpdate(), CDatabase::ExecuteQuery(), GetArtistFromMBID(), CLog::Log(), LOGDEBUG, MediaTypeArtist, and CDatabase::PrepareSQL().
Referenced by UpdateAlbum().
UpdateArtistSortNames()
bool CMusicDatabase::UpdateArtistSortNames (int idArtist = -1)
Propagate artist sort name into the concatenated artist sort name strings held for songs and albums.
Parameters
int idArtist to propagate sort name for, -1 means all artists
References CDatabase::BeginMultipleExecute(), CDatabase::CommitMultipleExecute(), CDatabase::ExecuteQuery(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, LOGERROR, and CDatabase::PrepareSQL().
Referenced by MUSIC_INFO::CMusicInfoScanner::Process().
UpdateSong() [1/2]
bool CMusicDatabase::UpdateSong (CSong & song, bool bArtists = true, bool bArtistLinks = true)
Update a song and all its nested entities (genres, artists, contributors)
Parameters
song [in/out] the song to update, artist ids are returned in artist credits
bArtists to update artist credits and contributors, default is true
bArtists to check and log if artist links have changed, default is true
Returns
true if successful
References AddArtist(), AddSongArtist(), AddSongContributors(), AddSongGenres(), CSong::artistCredits, BLANKARTIST_ID, BLANKARTIST_NAME, CheckArtistLinksChanged(), DeleteSongArtistsBySong(), CSong::genre, CSong::GetArtistSort(), CSong::GetArtistString(), CSong::GetComposerSort(), CSong::GetContributors(), CSong::iBitRate, CSong::iBPM, CSong::iChannels, CSong::idSong, CSong::iDuration, CSong::iEndOffset, CSong::iSampleRate, CSong::iStartOffset, CSong::iTimesPlayed, CSong::iTrack, CSong::lastPlayed, CSong::rating, CSong::replayGain, ROLE_ARTIST, CSong::songVideoURL, CSong::strComment, CSong::strDiscSubtitle, CSong::strFileName, CSong::strMood, CSong::strMusicBrainzTrackID, CSong::strOrigReleaseDate, CSong::strReleaseDate, CSong::strThumb, CSong::strTitle, UpdateSong(), CSong::userrating, and CSong::votes.
Referenced by AddSong(), JSONRPC::CAudioLibrary::SetSongDetails(), UpdateAlbum(), and UpdateSong().
UpdateSong() [2/2]
int CMusicDatabase::UpdateSong (int idSong, const std::string & strTitle, const std::string & strMusicBrainzTrackID, const std::string & strPathAndFileName, const std::string & strComment, const std::string & strMood, const std::string & strThumb, const std::string & artistDisp, const std::string & artistSort, const std::vector< std::string > & genres, int iTrack, int iDuration, const std::string & strReleaseDate, const std::string & strOrigReleaseDate, const std::string & strDiscSubtitle, int iTimesPlayed, int iStartOffset, int iEndOffset, const CDateTime & dtLastPlayed, float rating, int userrating, int votes, const ReplayGain & replayGain, int iBPM, int iBitRate, int iSampleRate, int iChannels, const std::string & songVideoURL)
Update a song in the database.
Parameters
idSong [in] the database ID of the song to update
strTitle [in] the title of the song (required to be non-empty)
strMusicBrainzTrackID [in] the MusicBrainz track ID of the song
strPathAndFileName [in] the path and filename to the song
strComment [in] the ids of the added songs
strMood [in] the mood of the added song
strThumb [in] the ids of the added songs
artistDisp [in] the artist name(s) display string
artistSort [in] the artist name(s) sort string
genres [in] a vector of genres to which this song belongs
iTrack [in] the track number and disc number of the song
iDuration [in] the duration of the song
strReleaseDate [in] the release date of the song ISO8601 format
strOrigReleaseDate [in] the original release date of the song ISO8601 format
strDiscSubtitle [in] subtitle of a disc
iTimesPlayed [in] the number of times the song has been played
iStartOffset [in] the start offset of the song (when using a single audio file with a .cue)
iEndOffset [in] the end offset of the song (when using a single audio file with .cue)
dtLastPlayed [in] the time the song was last played
rating [in] a rating for the song
userrating [in] a userrating (my rating) for the song
votes [in] a vote counter for the song rating
replayGain [in] album and track replaygain and peak values
iBPM [in] the beats per minute of a song
iBitRate [in] the bitrate of the song file
iSampleRate [in] the sample rate of the song file
iChannels [in] the number of audio channels in the song file
songVideoURL [in] url link to a video of the song
Returns
the id of the song
References AddPath(), AnnounceUpdate(), CDatabase::ExecuteQuery(), ReplayGain::Get(), CDateTime::GetAsDBDateTime(), CDateTime::GetCurrentDateTime(), GetMediaDateFromFile(), CServiceBroker::GetSettingsComponent(), CDateTime::IsValid(), MediaTypeSong, NormaliseSongDates(), and CDatabase::PrepareSQL().
UpdateSource()
int CMusicDatabase::UpdateSource (const std::string & strOldName, const std::string & strName, const std::string & strMultipath, const std::vector< std::string > & vecPaths)
References AddSource(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::RollbackTransaction().
Referenced by CGUIWindowMusicBase::OnAssignContent().
UpdateSources()
bool CMusicDatabase::UpdateSources ()
References AddSource(), CheckSources(), CDatabase::ExecuteQuery(), CMediaSourceSettings::GetInstance(), GetSources(), CLog::Log(), and LOGERROR.
Referenced by MUSIC_INFO::CMusicInfoScanner::Start().
UpdateTables()
void CMusicDatabase::UpdateTables (int version) override private virtual
Reimplemented from CDatabase.
References CAlbum::Album, BLANKARTIST_FAKEMUSICBRAINZID, BLANKARTIST_ID, BLANKARTIST_NAME, CDatabase::ExecuteQuery(), GetArtistExists(), CDateTime::GetAsDBDateTime(), CDateTime::GetCurrentDateTime(), GetLibraryLastUpdated(), CServiceBroker::GetSettingsComponent(), CDatabase::GetSingleValueInt(), CDateTime::GetUTCDateTime(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, CDatabase::m_pDS, CDatabase::m_pDS2, MigrateSources(), CDatabase::PrepareSQL(), CAlbum::ReleaseTypeToString(), ROLE_ARTIST, SetLibraryLastUpdated(), SetMusicNeedsTagScan(), SetMusicTagScanVersion(), CAlbum::Single, CLegacyPathTranslation::TranslateMusicDbPath(), and TrimImageURLs().
Friends And Related Symbol Documentation
DatabaseUtils
friend class DatabaseUtils friend
TestDatabaseUtilsHelper
friend class TestDatabaseUtilsHelper friend
Member Data Documentation
AlbumFields
enum CMusicDatabase::_AlbumFields CMusicDatabase::AlbumFields static private
ArtistCreditFields
enum CMusicDatabase::_ArtistCreditFields CMusicDatabase::ArtistCreditFields static private
ArtistFields
enum CMusicDatabase::_ArtistFields CMusicDatabase::ArtistFields static private
JoinToAlbumFields
enum CMusicDatabase::_JoinToAlbumFields CMusicDatabase::JoinToAlbumFields static private
JoinToArtistFields
enum CMusicDatabase::_JoinToArtistFields CMusicDatabase::JoinToArtistFields static private
JoinToSongFields
enum CMusicDatabase::_JoinToSongFields CMusicDatabase::JoinToSongFields static private
m_genreCache
std::map<std::string, int> CMusicDatabase::m_genreCache protected
Referenced by AddGenre(), and EmptyCache().
m_pathCache
std::map<std::string, int> CMusicDatabase::m_pathCache protected
Referenced by AddPath(), and EmptyCache().
m_translateBlankArtist
bool CMusicDatabase::m_translateBlankArtist private
Referenced by CMusicDatabase(), GetArtistFromDataset(), GetTranslateBlankArtist(), and SetTranslateBlankArtist().
SongFields
enum CMusicDatabase::_SongFields CMusicDatabase::SongFields static private
The documentation for this class was generated from the following files:
MusicDatabase.h
MusicDatabase.cpp