Kodi Documentation: ADDON::Interface_Filesystem Struct Reference
ADDON::Interface_Filesystem Struct Reference
#include <Filesystem.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static unsigned int TranslateFileReadBitsToKodi (unsigned int addonFlags)
static bool can_open_directory (void *kodiBase, const char *url)
callback functions from add-on to kodi
static bool create_directory (void *kodiBase, const char *path)
static bool directory_exists (void *kodiBase, const char *path)
static bool remove_directory (void *kodiBase, const char *path)
static bool remove_directory_recursive (void *kodiBase, const char *path)
static bool get_directory (void *kodiBase, const char *path, const char *mask, struct VFSDirEntry **items, unsigned int *num_items)
static void free_directory (void *kodiBase, struct VFSDirEntry *items, unsigned int num_items)
static bool file_exists (void *kodiBase, const char *filename, bool useCache)
static bool stat_file (void *kodiBase, const char *filename, struct STAT_STRUCTURE *buffer)
static bool delete_file (void *kodiBase, const char *filename)
static bool rename_file (void *kodiBase, const char *filename, const char *newFileName)
static bool copy_file (void *kodiBase, const char *filename, const char *dest)
static char * get_file_md5 (void *kodiBase, const char *filename)
static char * get_cache_thumb_name (void *kodiBase, const char *filename)
static char * make_legal_filename (void *kodiBase, const char *filename)
static char * make_legal_path (void *kodiBase, const char *path)
static char * translate_special_protocol (void *kodiBase, const char *strSource)
static bool get_disk_space (void *kodiBase, const char *path, uint64_t *capacity, uint64_t *free, uint64_t *available)
static bool is_internet_stream (void *kodiBase, const char *path, bool strictCheck)
static bool is_on_lan (void *kodiBase, const char *path)
static bool is_remote (void *kodiBase, const char *path)
static bool is_local (void *kodiBase, const char *path)
static bool is_url (void *kodiBase, const char *path)
static bool get_http_header (void *kodiBase, const char *url, struct KODI_HTTP_HEADER *headers)
static bool get_mime_type (void *kodiBase, const char *url, char **content, const char *useragent)
static bool get_content_type (void *kodiBase, const char *url, char **content, const char *useragent)
static bool get_cookies (void *kodiBase, const char *url, char **cookies)
static bool http_header_create (void *kodiBase, struct KODI_HTTP_HEADER *headers)
Callback functions addon class kodi::vfs::CFile.
static void http_header_free (void *kodiBase, struct KODI_HTTP_HEADER *headers)
static char * http_header_get_value (void *kodiBase, void *handle, const char *param)
static char ** http_header_get_values (void *kodiBase, void *handle, const char *param, int *length)
static char * http_header_get_header (void *kodiBase, void *handle)
static char * http_header_get_mime_type (void *kodiBase, void *handle)
static char * http_header_get_charset (void *kodiBase, void *handle)
static char * http_header_get_proto_line (void *kodiBase, void *handle)
static void * open_file (void *kodiBase, const char *filename, unsigned int flags)
Callback functions addon class kodi::vfs::CFile.
static void * open_file_for_write (void *kodiBase, const char *filename, bool overwrite)
static ssize_t read_file (void *kodiBase, void *file, void *ptr, size_t size)
static bool read_file_string (void *kodiBase, void *file, char *szLine, int lineLength)
static ssize_t write_file (void *kodiBase, void *file, const void *ptr, size_t size)
static void flush_file (void *kodiBase, void *file)
static int64_t seek_file (void *kodiBase, void *file, int64_t position, int whence)
static int truncate_file (void *kodiBase, void *file, int64_t size)
static int64_t get_file_position (void *kodiBase, void *file)
static int64_t get_file_length (void *kodiBase, void *file)
static double get_file_download_speed (void *kodiBase, void *file)
static void close_file (void *kodiBase, void *file)
static int get_file_chunk_size (void *kodiBase, void *file)
static bool io_control_get_seek_possible (void *kodiBase, void *file)
static bool io_control_get_cache_status (void *kodiBase, void *file, struct VFS_CACHE_STATUS_DATA *status)
static bool io_control_set_cache_rate (void *kodiBase, void *file, uint32_t rate)
static bool io_control_set_retry (void *kodiBase, void *file, bool retry)
static char ** get_property_values (void *kodiBase, void *file, int type, const char *name, int *numValues)
static void * curl_create (void *kodiBase, const char *url)
static bool curl_add_option (void *kodiBase, void *file, int type, const char *name, const char *value)
static bool curl_open (void *kodiBase, void *file, unsigned int flags)
Member Function Documentation
can_open_directory()
bool ADDON::Interface_Filesystem::can_open_directory (void * kodiBase, const char * url) static
callback functions from add-on to kodi
Note
For add of new functions use the "_" style to identify direct a add-on callback function. Everything with CamelCase is only for the usage in Kodi only.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References XFILE::DIR_FLAG_BYPASS_CACHE, XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::GetDirectory(), CLog::Log(), and LOGERROR.
Referenced by Init().
close_file()
void ADDON::Interface_Filesystem::close_file (void * kodiBase, void * file) static
References Close(), CLog::Log(), and LOGERROR.
Referenced by Init().
copy_file()
bool ADDON::Interface_Filesystem::copy_file (void * kodiBase, const char * filename, const char * dest) static
References XFILE::CFile::Copy(), CLog::Log(), and LOGERROR.
Referenced by Init().
create_directory()
bool ADDON::Interface_Filesystem::create_directory (void * kodiBase, const char * path) static
References XFILE::CDirectory::Create(), CLog::Log(), and LOGERROR.
Referenced by Init().
curl_add_option()
bool ADDON::Interface_Filesystem::curl_add_option (void * kodiBase, void * file, int type, const char * name, const char * value) static
References ADDON_CURL_OPTION_CREDENTIALS, ADDON_CURL_OPTION_HEADER, ADDON_CURL_OPTION_OPTION, ADDON_CURL_OPTION_PROTOCOL, XFILE::CURL_OPTION_CREDENTIALS, XFILE::CURL_OPTION_HEADER, XFILE::CURL_OPTION_OPTION, XFILE::CURL_OPTION_PROTOCOL, CLog::Log(), LOGERROR, name, and value.
Referenced by Init().
curl_create()
void * ADDON::Interface_Filesystem::curl_create (void * kodiBase, const char * url) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
curl_open()
bool ADDON::Interface_Filesystem::curl_open (void * kodiBase, void * file, unsigned int flags) static
References CLog::Log(), LOGERROR, and TranslateFileReadBitsToKodi().
Referenced by Init().
DeInit()
void ADDON::Interface_Filesystem::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_Addon::kodi_filesystem, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_Base::DeInitInterface().
delete_file()
bool ADDON::Interface_Filesystem::delete_file (void * kodiBase, const char * filename) static
References XFILE::CFile::Delete(), CLog::Log(), and LOGERROR.
Referenced by Init().
directory_exists()
bool ADDON::Interface_Filesystem::directory_exists (void * kodiBase, const char * path) static
References XFILE::CDirectory::Exists(), CLog::Log(), and LOGERROR.
Referenced by Init().
file_exists()
bool ADDON::Interface_Filesystem::file_exists (void * kodiBase, const char * filename, bool useCache) static
References XFILE::CFile::Exists(), CLog::Log(), and LOGERROR.
Referenced by Init().
flush_file()
void ADDON::Interface_Filesystem::flush_file (void * kodiBase, void * file) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
free_directory()
void ADDON::Interface_Filesystem::free_directory (void * kodiBase, struct VFSDirEntry * items, unsigned int num_items) static
References label, CLog::Log(), and LOGERROR.
Referenced by Init().
get_cache_thumb_name()
char * ADDON::Interface_Filesystem::get_cache_thumb_name (void * kodiBase, const char * filename) static
References Crc32::ComputeFromLowerCase(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_content_type()
bool ADDON::Interface_Filesystem::get_content_type (void * kodiBase, const char * url, char ** content, const char * useragent) static
References ADDON::content, CURL, XFILE::CCurlFile::GetContentType(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_cookies()
bool ADDON::Interface_Filesystem::get_cookies (void * kodiBase, const char * url, char ** cookies) static
References CURL, XFILE::CCurlFile::GetCookies(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_directory()
bool ADDON::Interface_Filesystem::get_directory (void * kodiBase, const char * path, const char * mask, struct VFSDirEntry ** items, unsigned int * num_items) static
References ADDON::CFileItemListToVFSDirEntries(), XFILE::DIR_FLAG_BYPASS_CACHE, XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::GetDirectory(), CLog::Log(), LOGERROR, and CFileItemList::Size().
Referenced by Init().
get_disk_space()
bool ADDON::Interface_Filesystem::get_disk_space (void * kodiBase, const char * path, uint64_t * capacity, uint64_t * free, uint64_t * available) static
References CLog::Log(), LOGERROR, and CSpecialProtocol::TranslatePath().
Referenced by Init().
get_file_chunk_size()
int ADDON::Interface_Filesystem::get_file_chunk_size (void * kodiBase, void * file) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
get_file_download_speed()
double ADDON::Interface_Filesystem::get_file_download_speed (void * kodiBase, void * file) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
get_file_length()
int64_t ADDON::Interface_Filesystem::get_file_length (void * kodiBase, void * file) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
get_file_md5()
char * ADDON::Interface_Filesystem::get_file_md5 (void * kodiBase, const char * filename) static
References CUtil::GetFileDigest(), CLog::Log(), LOGERROR, and KODI::UTILITY::CDigest::MD5.
Referenced by Init().
get_file_position()
int64_t ADDON::Interface_Filesystem::get_file_position (void * kodiBase, void * file) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
get_http_header()
bool ADDON::Interface_Filesystem::get_http_header (void * kodiBase, const char * url, struct KODI_HTTP_HEADER * headers) static
References CURL, XFILE::CCurlFile::GetHttpHeader(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_mime_type()
bool ADDON::Interface_Filesystem::get_mime_type (void * kodiBase, const char * url, char ** content, const char * useragent) static
References ADDON::content, CURL, XFILE::CCurlFile::GetMimeType(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_property_values()
char ** ADDON::Interface_Filesystem::get_property_values (void * kodiBase, void * file, int type, const char * name, int * numValues) static
References ADDON_FILE_PROPERTY_CONTENT_CHARSET, ADDON_FILE_PROPERTY_CONTENT_TYPE, ADDON_FILE_PROPERTY_EFFECTIVE_URL, ADDON_FILE_PROPERTY_MIME_TYPE, ADDON_FILE_PROPERTY_RESPONSE_HEADER, ADDON_FILE_PROPERTY_RESPONSE_PROTOCOL, XFILE::FILE_PROPERTY_CONTENT_CHARSET, XFILE::FILE_PROPERTY_CONTENT_TYPE, XFILE::FILE_PROPERTY_EFFECTIVE_URL, XFILE::FILE_PROPERTY_MIME_TYPE, XFILE::FILE_PROPERTY_RESPONSE_HEADER, XFILE::FILE_PROPERTY_RESPONSE_PROTOCOL, CLog::Log(), LOGERROR, name, and values.
Referenced by Init().
http_header_create()
bool ADDON::Interface_Filesystem::http_header_create (void * kodiBase, struct KODI_HTTP_HEADER * headers) static
Callback functions addon class kodi::vfs::CFile.
References http_header_get_charset(), http_header_get_header(), http_header_get_mime_type(), http_header_get_proto_line(), http_header_get_value(), http_header_get_values(), CLog::Log(), and LOGERROR.
Referenced by Init().
http_header_free()
void ADDON::Interface_Filesystem::http_header_free (void * kodiBase, struct KODI_HTTP_HEADER * headers) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
http_header_get_charset()
char * ADDON::Interface_Filesystem::http_header_get_charset (void * kodiBase, void * handle) static
References CLog::Log(), and LOGERROR.
Referenced by http_header_create().
http_header_get_header()
char * ADDON::Interface_Filesystem::http_header_get_header (void * kodiBase, void * handle) static
References CLog::Log(), and LOGERROR.
Referenced by http_header_create().
http_header_get_mime_type()
char * ADDON::Interface_Filesystem::http_header_get_mime_type (void * kodiBase, void * handle) static
References CLog::Log(), and LOGERROR.
Referenced by http_header_create().
http_header_get_proto_line()
char * ADDON::Interface_Filesystem::http_header_get_proto_line (void * kodiBase, void * handle) static
References CLog::Log(), and LOGERROR.
Referenced by http_header_create().
http_header_get_value()
char * ADDON::Interface_Filesystem::http_header_get_value (void * kodiBase, void * handle, const char * param) static
References GetValue(), CLog::Log(), and LOGERROR.
Referenced by http_header_create().
http_header_get_values()
char ** ADDON::Interface_Filesystem::http_header_get_values (void * kodiBase, void * handle, const char * param, int * length) static
References CLog::Log(), LOGERROR, and values.
Referenced by http_header_create().
Init()
void ADDON::Interface_Filesystem::Init (AddonGlobalInterface * addonInterface) static
References can_open_directory(), AddonToKodiFuncTable_kodi_filesystem::can_open_directory, close_file(), AddonToKodiFuncTable_kodi_filesystem::close_file, copy_file(), AddonToKodiFuncTable_kodi_filesystem::copy_file, create_directory(), AddonToKodiFuncTable_kodi_filesystem::create_directory, curl_add_option(), AddonToKodiFuncTable_kodi_filesystem::curl_add_option, curl_create(), AddonToKodiFuncTable_kodi_filesystem::curl_create, curl_open(), AddonToKodiFuncTable_kodi_filesystem::curl_open, delete_file(), AddonToKodiFuncTable_kodi_filesystem::delete_file, directory_exists(), AddonToKodiFuncTable_kodi_filesystem::directory_exists, file_exists(), AddonToKodiFuncTable_kodi_filesystem::file_exists, flush_file(), AddonToKodiFuncTable_kodi_filesystem::flush_file, free_directory(), AddonToKodiFuncTable_kodi_filesystem::free_directory, get_cache_thumb_name(), AddonToKodiFuncTable_kodi_filesystem::get_cache_thumb_name, get_content_type(), AddonToKodiFuncTable_kodi_filesystem::get_content_type, get_cookies(), AddonToKodiFuncTable_kodi_filesystem::get_cookies, get_directory(), AddonToKodiFuncTable_kodi_filesystem::get_directory, get_disk_space(), AddonToKodiFuncTable_kodi_filesystem::get_disk_space, get_file_chunk_size(), AddonToKodiFuncTable_kodi_filesystem::get_file_chunk_size, get_file_download_speed(), AddonToKodiFuncTable_kodi_filesystem::get_file_download_speed, get_file_length(), AddonToKodiFuncTable_kodi_filesystem::get_file_length, get_file_md5(), AddonToKodiFuncTable_kodi_filesystem::get_file_md5, get_file_position(), AddonToKodiFuncTable_kodi_filesystem::get_file_position, get_http_header(), AddonToKodiFuncTable_kodi_filesystem::get_http_header, get_mime_type(), AddonToKodiFuncTable_kodi_filesystem::get_mime_type, get_property_values(), AddonToKodiFuncTable_kodi_filesystem::get_property_values, http_header_create(), AddonToKodiFuncTable_kodi_filesystem::http_header_create, http_header_free(), AddonToKodiFuncTable_kodi_filesystem::http_header_free, io_control_get_cache_status(), AddonToKodiFuncTable_kodi_filesystem::io_control_get_cache_status, io_control_get_seek_possible(), AddonToKodiFuncTable_kodi_filesystem::io_control_get_seek_possible, io_control_set_cache_rate(), AddonToKodiFuncTable_kodi_filesystem::io_control_set_cache_rate, io_control_set_retry(), AddonToKodiFuncTable_kodi_filesystem::io_control_set_retry, is_internet_stream(), AddonToKodiFuncTable_kodi_filesystem::is_internet_stream, is_local(), AddonToKodiFuncTable_kodi_filesystem::is_local, is_on_lan(), AddonToKodiFuncTable_kodi_filesystem::is_on_lan, is_remote(), AddonToKodiFuncTable_kodi_filesystem::is_remote, is_url(), AddonToKodiFuncTable_kodi_filesystem::is_url, AddonToKodiFuncTable_Addon::kodi_filesystem, make_legal_filename(), AddonToKodiFuncTable_kodi_filesystem::make_legal_filename, make_legal_path(), AddonToKodiFuncTable_kodi_filesystem::make_legal_path, open_file(), AddonToKodiFuncTable_kodi_filesystem::open_file, open_file_for_write(), AddonToKodiFuncTable_kodi_filesystem::open_file_for_write, read_file(), AddonToKodiFuncTable_kodi_filesystem::read_file, read_file_string(), AddonToKodiFuncTable_kodi_filesystem::read_file_string, remove_directory(), AddonToKodiFuncTable_kodi_filesystem::remove_directory, remove_directory_recursive(), AddonToKodiFuncTable_kodi_filesystem::remove_directory_recursive, rename_file(), AddonToKodiFuncTable_kodi_filesystem::rename_file, seek_file(), AddonToKodiFuncTable_kodi_filesystem::seek_file, stat_file(), AddonToKodiFuncTable_kodi_filesystem::stat_file, AddonGlobalInterface::toKodi, translate_special_protocol(), AddonToKodiFuncTable_kodi_filesystem::translate_special_protocol, truncate_file(), AddonToKodiFuncTable_kodi_filesystem::truncate_file, write_file(), and AddonToKodiFuncTable_kodi_filesystem::write_file.
Referenced by ADDON::Interface_Base::InitInterface().
io_control_get_cache_status()
bool ADDON::Interface_Filesystem::io_control_get_cache_status (void * kodiBase, void * file, struct VFS_CACHE_STATUS_DATA * status) static
References VFS_CACHE_STATUS_DATA::currate, data(), VFS_CACHE_STATUS_DATA::forward, CLog::Log(), LOGERROR, VFS_CACHE_STATUS_DATA::lowrate, and VFS_CACHE_STATUS_DATA::maxrate.
Referenced by Init().
io_control_get_seek_possible()
bool ADDON::Interface_Filesystem::io_control_get_seek_possible (void * kodiBase, void * file) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
io_control_set_cache_rate()
bool ADDON::Interface_Filesystem::io_control_set_cache_rate (void * kodiBase, void * file, uint32_t rate) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
io_control_set_retry()
bool ADDON::Interface_Filesystem::io_control_set_retry (void * kodiBase, void * file, bool retry) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
is_internet_stream()
bool ADDON::Interface_Filesystem::is_internet_stream (void * kodiBase, const char * path, bool strictCheck) static
References URIUtils::IsInternetStream(), CLog::Log(), and LOGERROR.
Referenced by Init().
is_local()
bool ADDON::Interface_Filesystem::is_local (void * kodiBase, const char * path) static
References CURL, CLog::Log(), and LOGERROR.
Referenced by Init().
is_on_lan()
bool ADDON::Interface_Filesystem::is_on_lan (void * kodiBase, const char * path) static
References URIUtils::IsOnLAN(), CLog::Log(), and LOGERROR.
Referenced by Init().
is_remote()
bool ADDON::Interface_Filesystem::is_remote (void * kodiBase, const char * path) static
References URIUtils::IsRemote(), CLog::Log(), and LOGERROR.
Referenced by Init().
is_url()
bool ADDON::Interface_Filesystem::is_url (void * kodiBase, const char * path) static
References URIUtils::IsURL(), CLog::Log(), and LOGERROR.
Referenced by Init().
make_legal_filename()
char * ADDON::Interface_Filesystem::make_legal_filename (void * kodiBase, const char * filename) static
References CLog::Log(), LOGERROR, and CUtil::MakeLegalFileName().
Referenced by Init().
make_legal_path()
char * ADDON::Interface_Filesystem::make_legal_path (void * kodiBase, const char * path) static
References CLog::Log(), LOGERROR, and CUtil::MakeLegalPath().
Referenced by Init().
open_file()
void * ADDON::Interface_Filesystem::open_file (void * kodiBase, const char * filename, unsigned int flags) static
Callback functions addon class kodi::vfs::CFile.
References CLog::Log(), LOGERROR, and TranslateFileReadBitsToKodi().
Referenced by Init().
open_file_for_write()
void * ADDON::Interface_Filesystem::open_file_for_write (void * kodiBase, const char * filename, bool overwrite) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
read_file()
ssize_t ADDON::Interface_Filesystem::read_file (void * kodiBase, void * file, void * ptr, size_t size) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
read_file_string()
bool ADDON::Interface_Filesystem::read_file_string (void * kodiBase, void * file, char * szLine, int lineLength) static
References CLog::Log(), LOGERROR, and ReadString().
Referenced by Init().
remove_directory()
bool ADDON::Interface_Filesystem::remove_directory (void * kodiBase, const char * path) static
References XFILE::CFile::Delete(), XFILE::DIR_FLAG_BYPASS_CACHE, XFILE::DIR_FLAG_NO_FILE_DIRS, CFileItemList::Get(), XFILE::CDirectory::GetDirectory(), CLog::Log(), LOGERROR, XFILE::CDirectory::Remove(), and CFileItemList::Size().
Referenced by Init().
remove_directory_recursive()
bool ADDON::Interface_Filesystem::remove_directory_recursive (void * kodiBase, const char * path) static
References CLog::Log(), LOGERROR, and XFILE::CDirectory::RemoveRecursive().
Referenced by Init().
rename_file()
bool ADDON::Interface_Filesystem::rename_file (void * kodiBase, const char * filename, const char * newFileName) static
References CLog::Log(), LOGERROR, and XFILE::CFile::Rename().
Referenced by Init().
seek_file()
int64_t ADDON::Interface_Filesystem::seek_file (void * kodiBase, void * file, int64_t position, int whence) static
References CLog::Log(), LOGERROR, and Seek().
Referenced by Init().
stat_file()
bool ADDON::Interface_Filesystem::stat_file (void * kodiBase, const char * filename, struct STAT_STRUCTURE * buffer) static
References __stat64, CLog::Log(), LOGERROR, S_ISBLK, S_ISCHR, S_ISDIR, S_ISFIFO, S_ISLNK, S_ISREG, S_ISSOCK, and XFILE::CFile::Stat().
Referenced by Init().
translate_special_protocol()
char * ADDON::Interface_Filesystem::translate_special_protocol (void * kodiBase, const char * strSource) static
References CLog::Log(), LOGERROR, and CSpecialProtocol::TranslatePath().
Referenced by Init().
TranslateFileReadBitsToKodi()
unsigned int ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi (unsigned int addonFlags) static
References ADDON_READ_AFTER_WRITE, ADDON_READ_AUDIO_VIDEO, ADDON_READ_BITRATE, ADDON_READ_CACHED, ADDON_READ_CHUNKED, ADDON_READ_MULTI_STREAM, ADDON_READ_NO_BUFFER, ADDON_READ_NO_CACHE, ADDON_READ_REOPEN, ADDON_READ_TRUNCATED, XFILE::READ_AFTER_WRITE, XFILE::READ_AUDIO_VIDEO, XFILE::READ_BITRATE, XFILE::READ_CACHED, XFILE::READ_CHUNKED, XFILE::READ_MULTI_STREAM, XFILE::READ_NO_BUFFER, XFILE::READ_NO_CACHE, XFILE::READ_REOPEN, and XFILE::READ_TRUNCATED.
Referenced by curl_open(), and open_file().
truncate_file()
int ADDON::Interface_Filesystem::truncate_file (void * kodiBase, void * file, int64_t size) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
write_file()
ssize_t ADDON::Interface_Filesystem::write_file (void * kodiBase, void * file, const void * ptr, size_t size) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
The documentation for this struct was generated from the following files:
addons/interfaces/Filesystem.h
addons/interfaces/Filesystem.cpp