Kodi Documentation: CDatabaseQueryRuleCombination Class Reference
CDatabaseQueryRuleCombination Class Reference
#include <DatabaseQuery.h>
Public Types
enum Combination { CombinationOr = 0 , CombinationAnd }
Public Member Functions
virtual ~CDatabaseQueryRuleCombination ()=default
void clear ()
virtual bool Load (const TiXmlNode *node, const std::string &encoding="UTF-8")
virtual bool Load (const CVariant &obj, const IDatabaseQueryRuleFactory *factory)
virtual bool Save (TiXmlNode *parent) const
virtual bool Save (CVariant &obj) const
std::string GetWhereClause (const CDatabase &db, const std::string &strType) const
std::string TranslateCombinationType () const
Combination GetType () const
void SetType (Combination combination)
bool empty () const
Protected Attributes
Combination m_type = CombinationAnd
CDatabaseQueryRuleCombinations m_combinations
CDatabaseQueryRules m_rules
Friends
class CGUIDialogSmartPlaylistEditor
class CGUIDialogMediaFilter
Member Enumeration Documentation
Combination
enum CDatabaseQueryRuleCombination::Combination
Enumerator
CombinationOr
CombinationAnd
Constructor & Destructor Documentation
~CDatabaseQueryRuleCombination()
virtual CDatabaseQueryRuleCombination::~CDatabaseQueryRuleCombination () virtual default
Member Function Documentation
clear()
void CDatabaseQueryRuleCombination::clear ()
References CombinationAnd, m_combinations, m_rules, and m_type.
Referenced by KODI::PLAYLIST::CSmartPlaylist::Reset().
empty()
bool CDatabaseQueryRuleCombination::empty () const inline
References m_combinations, and m_rules.
Referenced by KODI::PLAYLIST::CSmartPlaylist::IsEmpty().
GetType()
Combination CDatabaseQueryRuleCombination::GetType () const inline
References m_type.
Referenced by KODI::PLAYLIST::CSmartPlaylist::GetMatchAllRules(), CGUIDialogSmartPlaylistEditor::OnMatch(), KODI::PLAYLIST::CSmartPlaylist::Save(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
GetWhereClause()
std::string CDatabaseQueryRuleCombination::GetWhereClause (const CDatabase & db, const std::string & strType) const
References CombinationAnd, m_combinations, m_rules, and m_type.
Referenced by JSONRPC::CTextureOperations::GetTextures().
Load() [1/2]
bool CDatabaseQueryRuleCombination::Load (const CVariant & obj, const IDatabaseQueryRuleFactory * factory) virtual
References CVariant::begin_array(), CombinationAnd, CombinationOr, IDatabaseQueryRuleFactory::CreateCombination(), IDatabaseQueryRuleFactory::CreateRule(), CVariant::end_array(), CVariant::isArray(), CVariant::isMember(), CVariant::isObject(), m_combinations, m_rules, and m_type.
Load() [2/2]
virtual bool CDatabaseQueryRuleCombination::Load (const TiXmlNode * node, const std::string & encoding = "UTF-8") inline virtual
Referenced by JSONRPC::CTextureOperations::GetTextures(), and KODI::PLAYLIST::CSmartPlaylist::Load().
Save() [1/2]
bool CDatabaseQueryRuleCombination::Save (CVariant & obj) const virtual
References CVariant::isObject(), m_combinations, m_rules, CVariant::push_back(), TranslateCombinationType(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Save() [2/2]
bool CDatabaseQueryRuleCombination::Save (TiXmlNode * parent) const virtual
References m_rules.
Referenced by KODI::PLAYLIST::CSmartPlaylist::Save(), and KODI::PLAYLIST::CSmartPlaylist::Save().
SetType()
void CDatabaseQueryRuleCombination::SetType (Combination combination) inline
References m_type.
Referenced by KODI::PLAYLIST::CSmartPlaylist::LoadFromXML(), CGUIDialogSmartPlaylistEditor::OnMatch(), and KODI::PLAYLIST::CSmartPlaylist::SetMatchAllRules().
TranslateCombinationType()
std::string CDatabaseQueryRuleCombination::TranslateCombinationType () const
References CombinationAnd, and m_type.
Referenced by Save().
Friends And Related Symbol Documentation
CGUIDialogMediaFilter
friend class CGUIDialogMediaFilter friend
CGUIDialogSmartPlaylistEditor
friend class CGUIDialogSmartPlaylistEditor friend
Member Data Documentation
m_combinations
CDatabaseQueryRuleCombinations CDatabaseQueryRuleCombination::m_combinations protected
Referenced by clear(), empty(), KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetVirtualFolders(), GetWhereClause(), KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetWhereClause(), Load(), and Save().
m_rules
CDatabaseQueryRules CDatabaseQueryRuleCombination::m_rules protected
Referenced by KODI::PLAYLIST::CSmartPlaylistRuleCombination::AddRule(), CGUIDialogMediaFilter::AddRule(), clear(), CGUIDialogMediaFilter::DeleteRule(), empty(), CGUIDialogMediaFilter::GetItems(), KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetVirtualFolders(), GetWhereClause(), KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetWhereClause(), CGUIDialogMediaFilter::InitializeSettings(), Load(), CGUIDialogSmartPlaylistEditor::OnPopupMenu(), CGUIDialogSmartPlaylistEditor::OnRuleList(), CGUIDialogSmartPlaylistEditor::OnRuleRemove(), Save(), Save(), CGUIDialogSmartPlaylistEditor::UpdateButtons(), and CGUIDialogSmartPlaylistEditor::UpdateRuleControlButtons().
m_type
Combination CDatabaseQueryRuleCombination::m_type = CombinationAnd protected
Referenced by clear(), GetType(), GetWhereClause(), KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetWhereClause(), Load(), SetType(), and TranslateCombinationType().
The documentation for this class was generated from the following files:
DatabaseQuery.h
DatabaseQuery.cpp