Kodi Documentation: CLangInfo Class Reference
CLangInfo Class Reference
#include <LangInfo.h>
Classes
class CRegion
Public Member Functions
CLangInfo ()
~CLangInfo () override
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingsLoaded () override
Settings have been loaded.
LanguageResourcePtr GetLanguageAddon (const std::string &locale="") const
Returns the language addon for the given locale (or the current one).
std::string GetGuiCharSet () const
std::string GetSubtitleCharSet () const
const std::string & GetLanguageCode () const
std::string GetEnglishLanguageName (const std::string &locale="") const
Get the english language name from given locale, by searching in the installed language addons.
bool SetLanguage (std::string strLanguage="", bool reloadServices=true)
Sets and loads the given (or configured) language, its details and strings.
const std::string & GetAudioLanguage () const
void SetAudioLanguage (const std::string &language)
const std::string & GetSubtitleLanguage () const
void SetSubtitleLanguage (const std::string &language)
const std::string GetDVDMenuLanguage () const
const std::string GetDVDAudioLanguage () const
const std::string GetDVDSubtitleLanguage () const
const std::string & GetTimeZone () const
const std::string & GetRegionLocale () const
const std::locale & GetOriginalLocale () const
const CLocale & GetLocale () const
Returns the full locale of the current language.
const std::locale & GetSystemLocale () const
Returns the system's current locale.
bool ForceUnicodeFont () const
const std::string & GetDateFormat (bool bLongDate=false) const
void SetDateFormat (const std::string &dateFormat, bool bLongDate=false)
const std::string & GetShortDateFormat () const
void SetShortDateFormat (const std::string &shortDateFormat)
const std::string & GetLongDateFormat () const
void SetLongDateFormat (const std::string &longDateFormat)
const std::string & GetTimeFormat () const
void SetTimeFormat (const std::string &timeFormat)
bool Use24HourClock () const
void Set24HourClock (bool use24HourClock)
void Set24HourClock (const std::string &str24HourClock)
const std::string & GetMeridiemSymbol (MeridiemSymbol symbol) const
CTemperature::Unit GetTemperatureUnit () const
void SetTemperatureUnit (CTemperature::Unit temperatureUnit)
void SetTemperatureUnit (const std::string &temperatureUnit)
const std::string & GetTemperatureUnitString () const
std::string GetTemperatureAsString (const CTemperature &temperature) const
CSpeed::Unit GetSpeedUnit () const
void SetSpeedUnit (CSpeed::Unit speedUnit)
void SetSpeedUnit (const std::string &speedUnit)
const std::string & GetSpeedUnitString () const
std::string GetSpeedAsString (const CSpeed &speed) const
void GetRegionNames (std::vector< std::string > &array)
void SetCurrentRegion (const std::string &strName)
const std::string & GetCurrentRegion () const
std::set< std::string > GetSortTokens () const
bool UseLocaleCollation ()
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsUnloaded ()
Setting values have been unloaded.
virtual void OnSettingsCleared ()
Settings have been cleared.
Static Public Member Functions
static void GetAddonsLanguageCodes (std::map< std::string, std::string > &languages)
static std::string ConvertEnglishNameToAddonLocale (const std::string &langName)
Convert an english language name to an addon locale, by searching in the installed language addons.
static const std::string & MeridiemSymbolToString (MeridiemSymbol symbol)
static const std::string & GetTemperatureUnitString (CTemperature::Unit temperatureUnit)
static const std::string & GetSpeedUnitString (CSpeed::Unit speedUnit)
static std::string GetLanguagePath ()
static std::string GetLanguagePath (const std::string &language)
static std::string GetLanguageInfoPath (const std::string &language)
static void LoadTokens (const TiXmlNode *pTokens, std::set< std::string > &vecTokens)
static void SettingOptionsLanguageNamesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsAudioStreamLanguagesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsSubtitleStreamLanguagesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsSubtitleDownloadlanguagesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsISO6391LanguagesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsRegionsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsShortDateFormatsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsLongDateFormatsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsTimeFormatsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptions24HourClockFormatsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsTemperatureUnitsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsSpeedUnitsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
Protected Types
typedef std::map< std::string, CRegion > MAPREGIONS
typedef std::map< std::string, CRegion >::iterator ITMAPREGIONS
typedef std::pair< std::string, CRegion > PAIR_REGIONS
Protected Member Functions
void SetDefaults ()
bool Load (const std::string &strLanguage)
Static Protected Member Functions
static bool DetermineUse24HourClockFromTimeFormat (const std::string &timeFormat)
static bool DetermineUseMeridiemFromTimeFormat (const std::string &timeFormat)
static std::string PrepareTimeFormat (const std::string &timeFormat, bool use24HourClock)
static void AddLanguages (std::vector< StringSettingOption > &list)
Protected Attributes
MAPREGIONS m_regions
CRegion * m_currentRegion
CRegion m_defaultRegion
std::locale m_systemLocale
std::locale m_originalLocale
int m_collationtype
LanguageResourcePtr m_languageAddon
std::string m_strGuiCharSet
bool m_forceUnicodeFont
std::string m_strSubtitleCharSet
std::string m_strDVDMenuLanguage
std::string m_strDVDAudioLanguage
std::string m_strDVDSubtitleLanguage
std::set< std::string > m_sortTokens
std::string m_shortDateFormat
std::string m_longDateFormat
std::string m_timeFormat
bool m_use24HourClock
CTemperature::Unit m_temperatureUnit
CSpeed::Unit m_speedUnit
std::string m_audioLanguage
std::string m_subtitleLanguage
std::string m_languageCodeGeneral
Member Typedef Documentation
ITMAPREGIONS
typedef std::map<std::string,CRegion>::iterator CLangInfo::ITMAPREGIONS protected
MAPREGIONS
typedef std::map<std::string, CRegion> CLangInfo::MAPREGIONS protected
PAIR_REGIONS
typedef std::pair<std::string, CRegion> CLangInfo::PAIR_REGIONS protected
Constructor & Destructor Documentation
CLangInfo()
CLangInfo::CLangInfo ()
References DetermineUse24HourClockFromTimeFormat(), m_collationtype, m_defaultRegion, m_longDateFormat, m_shortDateFormat, CLangInfo::CRegion::m_speedUnit, m_speedUnit, CLangInfo::CRegion::m_strDateFormatLong, CLangInfo::CRegion::m_strDateFormatShort, CLangInfo::CRegion::m_strTimeFormat, m_temperatureUnit, CLangInfo::CRegion::m_tempUnit, m_timeFormat, m_use24HourClock, and SetDefaults().
~CLangInfo()
CLangInfo::~CLangInfo () override default
Member Function Documentation
AddLanguages()
void CLangInfo::AddLanguages (std::vector< StringSettingOption > & list) static protected
References g_LangCodeExpander, CLangCodeExpander::GetLanguageNames(), CLangCodeExpander::INCLUDE_ADDONS_USERDEFINED, and CLangCodeExpander::ISO_639_1.
Referenced by SettingOptionsAudioStreamLanguagesFiller(), SettingOptionsSubtitleDownloadlanguagesFiller(), and SettingOptionsSubtitleStreamLanguagesFiller().
ConvertEnglishNameToAddonLocale()
std::string CLangInfo::ConvertEnglishNameToAddonLocale (const std::string & langName) static
Convert an english language name to an addon locale, by searching in the installed language addons.
Parameters
langName [IN] The english language name
Returns
The locale for the given english name, or empty if not found
References addons, CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetAddons(), and ADDON::RESOURCE_LANGUAGE.
DetermineUse24HourClockFromTimeFormat()
bool CLangInfo::DetermineUse24HourClockFromTimeFormat (const std::string & timeFormat) static protected
Referenced by CLangInfo(), Set24HourClock(), and SettingOptions24HourClockFormatsFiller().
DetermineUseMeridiemFromTimeFormat()
bool CLangInfo::DetermineUseMeridiemFromTimeFormat (const std::string & timeFormat) static protected
ForceUnicodeFont()
bool CLangInfo::ForceUnicodeFont () const inline
References m_forceUnicodeFont.
GetAddonsLanguageCodes()
void CLangInfo::GetAddonsLanguageCodes (std::map< std::string, std::string > & languages) static
References addons, CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetAddons(), and ADDON::RESOURCE_LANGUAGE.
GetAudioLanguage()
const std::string & CLangInfo::GetAudioLanguage () const
References m_audioLanguage, and m_languageCodeGeneral.
GetCurrentRegion()
const std::string & CLangInfo::GetCurrentRegion () const
References m_currentRegion, and CLangInfo::CRegion::m_strName.
GetDateFormat()
const std::string & CLangInfo::GetDateFormat (bool bLongDate = false) const
References GetLongDateFormat(), and GetShortDateFormat().
GetDVDAudioLanguage()
const std::string CLangInfo::GetDVDAudioLanguage () const
References CLangCodeExpander::ConvertToISO6391(), g_LangCodeExpander, m_audioLanguage, and m_strDVDAudioLanguage.
GetDVDMenuLanguage()
const std::string CLangInfo::GetDVDMenuLanguage () const
References CLangCodeExpander::ConvertToISO6391(), g_LangCodeExpander, m_currentRegion, m_strDVDMenuLanguage, and CLangInfo::CRegion::m_strLangLocaleName.
GetDVDSubtitleLanguage()
const std::string CLangInfo::GetDVDSubtitleLanguage () const
References CLangCodeExpander::ConvertToISO6391(), g_LangCodeExpander, m_strDVDSubtitleLanguage, and m_subtitleLanguage.
GetEnglishLanguageName()
std::string CLangInfo::GetEnglishLanguageName (const std::string & locale = "") const
Get the english language name from given locale, by searching in the installed language addons.
Parameters
locale [OPT] Locale of the language (current if empty)
References GetLanguageAddon().
GetGuiCharSet()
std::string CLangInfo::GetGuiCharSet () const
References CServiceBroker::GetSettingsComponent(), m_strGuiCharSet, and CSettings::SETTING_LOCALE_CHARSET.
GetLanguageAddon()
LanguageResourcePtr CLangInfo::GetLanguageAddon (const std::string & locale = "") const
Returns the language addon for the given locale (or the current one).
Parameters
locale (optional) Locale of the language (current if empty)
Returns
Language addon for the given locale or NULL if the locale is invalid.
References ADDON::CHOICE_YES, ADDON::CLanguageResource::GetAddonId(), CServiceBroker::GetAddonMgr(), CServiceBroker::GetSettingsComponent(), m_languageAddon, ADDON::RESOURCE_LANGUAGE, and CSettings::SETTING_LOCALE_LANGUAGE.
Referenced by GetEnglishLanguageName(), GetLocale(), and Load().
GetLanguageCode()
const std::string & CLangInfo::GetLanguageCode () const inline
References m_languageCodeGeneral.
GetLanguageInfoPath()
std::string CLangInfo::GetLanguageInfoPath (const std::string & language) static
References URIUtils::AddFileToFolder(), and GetLanguagePath().
Referenced by Load().
GetLanguagePath() [1/2]
static std::string CLangInfo::GetLanguagePath () inline static
Referenced by GetLanguageInfoPath(), GetLanguagePath(), CWeatherJob::LoadLocalizedToken(), and SetLanguage().
GetLanguagePath() [2/2]
std::string CLangInfo::GetLanguagePath (const std::string & language) static
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), ADDON::CLanguageResource::GetAddonId(), and GetLanguagePath().
GetLocale()
const CLocale & CLangInfo::GetLocale () const
Returns the full locale of the current language.
References CLocale::Empty, and GetLanguageAddon().
GetLongDateFormat()
const std::string & CLangInfo::GetLongDateFormat () const
References m_longDateFormat.
Referenced by GetDateFormat().
GetMeridiemSymbol()
const std::string & CLangInfo::GetMeridiemSymbol (MeridiemSymbol symbol) const
References m_use24HourClock, and MeridiemSymbolToString().
GetOriginalLocale()
const std::locale & CLangInfo::GetOriginalLocale () const
References m_originalLocale.
GetRegionLocale()
const std::string & CLangInfo::GetRegionLocale () const
References m_currentRegion, and CLangInfo::CRegion::m_strRegionLocaleName.
GetRegionNames()
void CLangInfo::GetRegionNames (std::vector< std::string > & array)
References g_localizeStrings, CLocalizeStrings::Get(), and m_regions.
GetShortDateFormat()
const std::string & CLangInfo::GetShortDateFormat () const
References m_shortDateFormat.
Referenced by GetDateFormat().
GetSortTokens()
std::set< std::string > CLangInfo::GetSortTokens () const
References CServiceBroker::GetSettingsComponent(), m_sortTokens, and t.
GetSpeedAsString()
std::string CLangInfo::GetSpeedAsString (const CSpeed & speed) const
References g_localizeStrings, CLocalizeStrings::Get(), GetSpeedUnit(), GetSpeedUnitString(), CSpeed::IsValid(), and CSpeed::ToString().
GetSpeedUnit()
CSpeed::Unit CLangInfo::GetSpeedUnit () const
References m_speedUnit.
Referenced by GetSpeedAsString().
GetSpeedUnitString() [1/2]
const std::string & CLangInfo::GetSpeedUnitString () const
References GetSpeedUnitString(), and m_speedUnit.
Referenced by GetSpeedAsString(), GetSpeedUnitString(), and SettingOptionsSpeedUnitsFiller().
GetSpeedUnitString() [2/2]
const std::string & CLangInfo::GetSpeedUnitString (CSpeed::Unit speedUnit) static
References g_localizeStrings, CLocalizeStrings::Get(), and SPEED_UNIT_STRINGS.
GetSubtitleCharSet()
std::string CLangInfo::GetSubtitleCharSet () const
References CServiceBroker::GetSettingsComponent(), m_strSubtitleCharSet, and CSettings::SETTING_SUBTITLES_CHARSET.
GetSubtitleLanguage()
const std::string & CLangInfo::GetSubtitleLanguage () const
References m_languageCodeGeneral, and m_subtitleLanguage.
GetSystemLocale()
const std::locale & CLangInfo::GetSystemLocale () const inline
Returns the system's current locale.
References m_systemLocale.
GetTemperatureAsString()
std::string CLangInfo::GetTemperatureAsString (const CTemperature & temperature) const
References g_localizeStrings, CLocalizeStrings::Get(), GetTemperatureUnit(), GetTemperatureUnitString(), CTemperature::IsValid(), and CTemperature::ToString().
GetTemperatureUnit()
CTemperature::Unit CLangInfo::GetTemperatureUnit () const
References m_temperatureUnit.
Referenced by GetTemperatureAsString().
GetTemperatureUnitString() [1/2]
const std::string & CLangInfo::GetTemperatureUnitString () const
References GetTemperatureUnitString(), and m_temperatureUnit.
Referenced by GetTemperatureAsString(), GetTemperatureUnitString(), and SettingOptionsTemperatureUnitsFiller().
GetTemperatureUnitString() [2/2]
const std::string & CLangInfo::GetTemperatureUnitString (CTemperature::Unit temperatureUnit) static
References g_localizeStrings, CLocalizeStrings::Get(), and TEMP_UNIT_STRINGS.
GetTimeFormat()
const std::string & CLangInfo::GetTimeFormat () const
References m_timeFormat.
Referenced by OnSettingChanged().
GetTimeZone()
const std::string & CLangInfo::GetTimeZone () const
References m_currentRegion, and CLangInfo::CRegion::m_strTimeZone.
Load()
bool CLangInfo::Load (const std::string & strLanguage) protected
References CLangCodeExpander::ConvertISO6391ToISO6392B(), CLangCodeExpander::ConvertToISO6391(), CLangCodeExpander::ConvertToISO6392B(), g_charsetConverter, g_LangCodeExpander, g_localizeStrings, CLocalizeStrings::Get(), XMLUtils::GetAttribute(), GetLanguageAddon(), GetLanguageInfoPath(), CServiceBroker::GetSettingsComponent(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGERROR, CLangInfo::CRegion::m_cDecimalSep, CLangInfo::CRegion::m_cThousandsSep, m_defaultRegion, m_forceUnicodeFont, m_languageAddon, m_languageCodeGeneral, m_regions, m_sortTokens, CLangInfo::CRegion::m_strDateFormatLong, CLangInfo::CRegion::m_strDateFormatShort, m_strDVDAudioLanguage, m_strDVDMenuLanguage, m_strDVDSubtitleLanguage, CLangInfo::CRegion::m_strGrouping, m_strGuiCharSet, CLangInfo::CRegion::m_strLangLocaleCodeTwoChar, CLangInfo::CRegion::m_strLangLocaleName, CLangInfo::CRegion::m_strMeridiemSymbols, CLangInfo::CRegion::m_strName, CLangInfo::CRegion::m_strRegionLocaleName, m_strSubtitleCharSet, CLangInfo::CRegion::m_strTimeFormat, MeridiemSymbolAM, MeridiemSymbolPM, SetCurrentRegion(), SetDefaults(), CLangInfo::CRegion::SetSpeedUnit(), CLangInfo::CRegion::SetTemperatureUnit(), CLangInfo::CRegion::SetTimeZone(), and CSettings::SETTING_LOCALE_COUNTRY.
Referenced by SetLanguage().
LoadTokens()
void CLangInfo::LoadTokens (const TiXmlNode * pTokens, std::set< std::string > & vecTokens) static
Referenced by CAdvancedSettings::ParseSettingsFile().
MeridiemSymbolToString()
const std::string & CLangInfo::MeridiemSymbolToString (MeridiemSymbol symbol) static
References g_localizeStrings, CLocalizeStrings::Get(), MeridiemSymbolAM, and MeridiemSymbolPM.
Referenced by CDateTime::GetAsLocalizedTime(), and GetMeridiemSymbol().
OnSettingChanged()
void CLangInfo::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References CServiceBroker::GetSettingsComponent(), GetTimeFormat(), GetValue(), CLog::Log(), LOGERROR, m_use24HourClock, PrepareTimeFormat(), Set24HourClock(), SetAudioLanguage(), SetCurrentRegion(), SetLanguage(), SetLongDateFormat(), SetShortDateFormat(), SetSpeedUnit(), SetSubtitleLanguage(), SetTemperatureUnit(), SetTimeFormat(), CSettings::SETTING_LOCALE_AUDIOLANGUAGE, CSettings::SETTING_LOCALE_COUNTRY, CSettings::SETTING_LOCALE_LANGUAGE, CSettings::SETTING_LOCALE_LONGDATEFORMAT, CSettings::SETTING_LOCALE_SHORTDATEFORMAT, CSettings::SETTING_LOCALE_SPEEDUNIT, CSettings::SETTING_LOCALE_SUBTITLELANGUAGE, CSettings::SETTING_LOCALE_TEMPERATUREUNIT, CSettings::SETTING_LOCALE_TIMEFORMAT, and CSettings::SETTING_LOCALE_USE24HOURCLOCK.
OnSettingsLoaded()
void CLangInfo::OnSettingsLoaded () override virtual
Settings have been loaded.
This callback can be used to trigger loading other settings.
Reimplemented from ISettingsHandler.
References CServiceBroker::GetSettingsComponent(), Set24HourClock(), SetLongDateFormat(), SetShortDateFormat(), SetSpeedUnit(), SetTemperatureUnit(), SetTimeFormat(), CSettings::SETTING_LOCALE_LONGDATEFORMAT, CSettings::SETTING_LOCALE_SHORTDATEFORMAT, CSettings::SETTING_LOCALE_SPEEDUNIT, CSettings::SETTING_LOCALE_TEMPERATUREUNIT, CSettings::SETTING_LOCALE_TIMEFORMAT, and CSettings::SETTING_LOCALE_USE24HOURCLOCK.
PrepareTimeFormat()
std::string CLangInfo::PrepareTimeFormat (const std::string & timeFormat, bool use24HourClock) static protected
Referenced by OnSettingChanged(), and SetTimeFormat().
Set24HourClock() [1/2]
void CLangInfo::Set24HourClock (bool use24HourClock)
References m_use24HourClock.
Referenced by OnSettingChanged(), OnSettingsLoaded(), Set24HourClock(), and SetCurrentRegion().
Set24HourClock() [2/2]
void CLangInfo::Set24HourClock (const std::string & str24HourClock)
References DetermineUse24HourClockFromTimeFormat(), m_currentRegion, CLangInfo::CRegion::m_strTimeFormat, m_use24HourClock, Set24HourClock(), SETTING_REGIONAL_DEFAULT, TIME_FORMAT_12HOURS, and TIME_FORMAT_24HOURS.
SetAudioLanguage()
void CLangInfo::SetAudioLanguage (const std::string & language)
References CLangCodeExpander::ConvertToISO6392B(), g_LangCodeExpander, and m_audioLanguage.
Referenced by OnSettingChanged().
SetCurrentRegion()
void CLangInfo::SetCurrentRegion (const std::string & strName)
References CServiceBroker::GetSettingsComponent(), m_currentRegion, m_defaultRegion, m_regions, CLangInfo::CRegion::m_speedUnit, CLangInfo::CRegion::m_strDateFormatLong, CLangInfo::CRegion::m_strDateFormatShort, CLangInfo::CRegion::m_strTimeFormat, CLangInfo::CRegion::m_tempUnit, Set24HourClock(), CLangInfo::CRegion::SetGlobalLocale(), SetLongDateFormat(), SetShortDateFormat(), SetSpeedUnit(), SetTemperatureUnit(), SetTimeFormat(), CSettings::SETTING_LOCALE_LONGDATEFORMAT, CSettings::SETTING_LOCALE_SHORTDATEFORMAT, CSettings::SETTING_LOCALE_SPEEDUNIT, CSettings::SETTING_LOCALE_TEMPERATUREUNIT, CSettings::SETTING_LOCALE_TIMEFORMAT, CSettings::SETTING_LOCALE_USE24HOURCLOCK, and SETTING_REGIONAL_DEFAULT.
Referenced by Load(), and OnSettingChanged().
SetDateFormat()
void CLangInfo::SetDateFormat (const std::string & dateFormat, bool bLongDate = false)
References SetLongDateFormat(), and SetShortDateFormat().
SetDefaults()
void CLangInfo::SetDefaults () protected
References m_currentRegion, m_defaultRegion, m_forceUnicodeFont, m_languageCodeGeneral, m_regions, m_sortTokens, m_strDVDAudioLanguage, m_strDVDMenuLanguage, m_strDVDSubtitleLanguage, m_strGuiCharSet, m_strSubtitleCharSet, m_systemLocale, and CLangInfo::CRegion::SetDefaults().
Referenced by CLangInfo(), and Load().
SetLanguage()
bool CLangInfo::SetLanguage (std::string strLanguage = "", bool reloadServices = true)
Sets and loads the given (or configured) language, its details and strings.
Parameters
strLanguage (optional) Language to be loaded.
reloadServices (optional) Whether to reload services relying on localization.
Returns
True if the language has been successfully loaded, false otherwise.
References URIUtils::AddFileToFolder(), addons, ADDON::CHOICE_NO, ADDON::CHOICE_YES, g_localizeStrings, CServiceBroker::GetAddonMgr(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetDatabaseManager(), GetLanguagePath(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWeatherManager(), Load(), CLocalizeStrings::Load(), CLocalizeStrings::LoadAddonStrings(), CDatabaseManager::LocalizationChanged(), PVR::CPVRManager::LocalizationChanged(), CLog::Log(), LOGFATAL, LOGINFO, LOGWARNING, CInfoLoader::Refresh(), ADDON::RESOURCE_LANGUAGE, CSettings::SETTING_LOCALE_LANGUAGE, and TMSG_EXECUTE_BUILT_IN.
Referenced by OnSettingChanged().
SetLongDateFormat()
void CLangInfo::SetLongDateFormat (const std::string & longDateFormat)
References m_currentRegion, m_longDateFormat, CLangInfo::CRegion::m_strDateFormatShort, and SETTING_REGIONAL_DEFAULT.
Referenced by OnSettingChanged(), OnSettingsLoaded(), SetCurrentRegion(), and SetDateFormat().
SetShortDateFormat()
void CLangInfo::SetShortDateFormat (const std::string & shortDateFormat)
References m_currentRegion, m_shortDateFormat, CLangInfo::CRegion::m_strDateFormatShort, and SETTING_REGIONAL_DEFAULT.
Referenced by OnSettingChanged(), OnSettingsLoaded(), SetCurrentRegion(), and SetDateFormat().
SetSpeedUnit() [1/2]
void CLangInfo::SetSpeedUnit (const std::string & speedUnit)
References m_currentRegion, CLangInfo::CRegion::m_speedUnit, SetSpeedUnit(), SETTING_REGIONAL_DEFAULT, StringToSpeedUnit(), and CSpeed::UnitKilometresPerHour.
SetSpeedUnit() [2/2]
void CLangInfo::SetSpeedUnit (CSpeed::Unit speedUnit)
References CServiceBroker::GetWeatherManager(), CServiceBroker::IsServiceManagerUp(), m_speedUnit, and CInfoLoader::Refresh().
Referenced by OnSettingChanged(), OnSettingsLoaded(), SetCurrentRegion(), and SetSpeedUnit().
SetSubtitleLanguage()
void CLangInfo::SetSubtitleLanguage (const std::string & language)
References CLangCodeExpander::ConvertToISO6392B(), g_LangCodeExpander, and m_subtitleLanguage.
Referenced by OnSettingChanged().
SetTemperatureUnit() [1/2]
void CLangInfo::SetTemperatureUnit (const std::string & temperatureUnit)
References m_currentRegion, CLangInfo::CRegion::m_tempUnit, SetTemperatureUnit(), SETTING_REGIONAL_DEFAULT, StringToTemperatureUnit(), and CTemperature::UnitCelsius.
SetTemperatureUnit() [2/2]
void CLangInfo::SetTemperatureUnit (CTemperature::Unit temperatureUnit)
References CServiceBroker::GetWeatherManager(), CServiceBroker::IsServiceManagerUp(), m_temperatureUnit, and CInfoLoader::Refresh().
Referenced by OnSettingChanged(), OnSettingsLoaded(), SetCurrentRegion(), and SetTemperatureUnit().
SetTimeFormat()
void CLangInfo::SetTimeFormat (const std::string & timeFormat)
References m_currentRegion, CLangInfo::CRegion::m_strTimeFormat, m_timeFormat, m_use24HourClock, PrepareTimeFormat(), and SETTING_REGIONAL_DEFAULT.
Referenced by OnSettingChanged(), OnSettingsLoaded(), and SetCurrentRegion().
SettingOptions24HourClockFormatsFiller()
void CLangInfo::SettingOptions24HourClockFormatsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References DetermineUse24HourClockFromTimeFormat(), g_langInfo, g_localizeStrings, CLocalizeStrings::Get(), SETTING_REGIONAL_DEFAULT, TIME_FORMAT_12HOURS, and TIME_FORMAT_24HOURS.
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsAudioStreamLanguagesFiller()
void CLangInfo::SettingOptionsAudioStreamLanguagesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References AddLanguages(), g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsISO6391LanguagesFiller()
void CLangInfo::SettingOptionsISO6391LanguagesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References g_LangCodeExpander, CLangCodeExpander::GetLanguageNames(), CLangCodeExpander::INCLUDE_USERDEFINED, and CLangCodeExpander::ISO_639_1.
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsLanguageNamesFiller()
void CLangInfo::SettingOptionsLanguageNamesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References addons, CServiceBroker::GetAddonMgr(), and ADDON::RESOURCE_LANGUAGE.
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsLongDateFormatsFiller()
void CLangInfo::SettingOptionsLongDateFormatsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References g_langInfo, g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetCurrentDateTime(), longDateFormats, SETTING_REGIONAL_DEFAULT, and value.
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsRegionsFiller()
void CLangInfo::SettingOptionsRegionsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References g_langInfo, and GetValue().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsShortDateFormatsFiller()
void CLangInfo::SettingOptionsShortDateFormatsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References g_langInfo, g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetCurrentDateTime(), SETTING_REGIONAL_DEFAULT, shortDateFormats, and value.
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsSpeedUnitsFiller()
void CLangInfo::SettingOptionsSpeedUnitsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References g_langInfo, g_localizeStrings, CLocalizeStrings::Get(), GetSpeedUnitString(), SETTING_REGIONAL_DEFAULT, speedInfo, and value.
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsSubtitleDownloadlanguagesFiller()
void CLangInfo::SettingOptionsSubtitleDownloadlanguagesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References AddLanguages(), g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsSubtitleStreamLanguagesFiller()
void CLangInfo::SettingOptionsSubtitleStreamLanguagesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References AddLanguages(), g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsTemperatureUnitsFiller()
void CLangInfo::SettingOptionsTemperatureUnitsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References g_langInfo, g_localizeStrings, CLocalizeStrings::Get(), GetTemperatureUnitString(), SETTING_REGIONAL_DEFAULT, temperatureInfo, and value.
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsTimeFormatsFiller()
void CLangInfo::SettingOptionsTimeFormatsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References g_langInfo, g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetCurrentDateTime(), SETTING_REGIONAL_DEFAULT, TIME_FORMAT_DOUBLE_12, TIME_FORMAT_DOUBLE_24, TIME_FORMAT_SINGLE_12, TIME_FORMAT_SINGLE_24, ToSettingTimeFormat(), and ToTimeFormat().
Referenced by CSettings::InitializeOptionFillers().
Use24HourClock()
bool CLangInfo::Use24HourClock () const
References m_use24HourClock.
UseLocaleCollation()
bool CLangInfo::UseLocaleCollation ()
References CServiceBroker::GetSettingsComponent(), m_collationtype, and m_systemLocale.
Member Data Documentation
m_audioLanguage
std::string CLangInfo::m_audioLanguage protected
Referenced by GetAudioLanguage(), GetDVDAudioLanguage(), and SetAudioLanguage().
m_collationtype
int CLangInfo::m_collationtype protected
Referenced by CLangInfo(), and UseLocaleCollation().
m_currentRegion
CRegion* CLangInfo::m_currentRegion protected
Referenced by GetCurrentRegion(), GetDVDMenuLanguage(), GetRegionLocale(), GetTimeZone(), Set24HourClock(), SetCurrentRegion(), SetDefaults(), SetLongDateFormat(), SetShortDateFormat(), SetSpeedUnit(), SetTemperatureUnit(), and SetTimeFormat().
m_defaultRegion
CRegion CLangInfo::m_defaultRegion protected
Referenced by CLangInfo(), Load(), SetCurrentRegion(), and SetDefaults().
m_forceUnicodeFont
bool CLangInfo::m_forceUnicodeFont protected
Referenced by ForceUnicodeFont(), Load(), and SetDefaults().
m_languageAddon
LanguageResourcePtr CLangInfo::m_languageAddon protected
Referenced by GetLanguageAddon(), and Load().
m_languageCodeGeneral
std::string CLangInfo::m_languageCodeGeneral protected
Referenced by GetAudioLanguage(), GetLanguageCode(), GetSubtitleLanguage(), Load(), and SetDefaults().
m_longDateFormat
std::string CLangInfo::m_longDateFormat protected
Referenced by CLangInfo(), GetLongDateFormat(), and SetLongDateFormat().
m_originalLocale
std::locale CLangInfo::m_originalLocale protected
Referenced by GetOriginalLocale().
m_regions
MAPREGIONS CLangInfo::m_regions protected
Referenced by GetRegionNames(), Load(), SetCurrentRegion(), and SetDefaults().
m_shortDateFormat
std::string CLangInfo::m_shortDateFormat protected
Referenced by CLangInfo(), GetShortDateFormat(), and SetShortDateFormat().
m_sortTokens
std::set<std::string> CLangInfo::m_sortTokens protected
Referenced by GetSortTokens(), Load(), and SetDefaults().
m_speedUnit
CSpeed::Unit CLangInfo::m_speedUnit protected
Referenced by CLangInfo(), GetSpeedUnit(), GetSpeedUnitString(), CLangInfo::CRegion::SetDefaults(), CLangInfo::CRegion::SetSpeedUnit(), and SetSpeedUnit().
m_strDVDAudioLanguage
std::string CLangInfo::m_strDVDAudioLanguage protected
Referenced by GetDVDAudioLanguage(), Load(), and SetDefaults().
m_strDVDMenuLanguage
std::string CLangInfo::m_strDVDMenuLanguage protected
Referenced by GetDVDMenuLanguage(), Load(), and SetDefaults().
m_strDVDSubtitleLanguage
std::string CLangInfo::m_strDVDSubtitleLanguage protected
Referenced by GetDVDSubtitleLanguage(), Load(), and SetDefaults().
m_strGuiCharSet
std::string CLangInfo::m_strGuiCharSet protected
Referenced by GetGuiCharSet(), Load(), and SetDefaults().
m_strSubtitleCharSet
std::string CLangInfo::m_strSubtitleCharSet protected
Referenced by GetSubtitleCharSet(), Load(), and SetDefaults().
m_subtitleLanguage
std::string CLangInfo::m_subtitleLanguage protected
Referenced by GetDVDSubtitleLanguage(), GetSubtitleLanguage(), and SetSubtitleLanguage().
m_systemLocale
std::locale CLangInfo::m_systemLocale protected
Referenced by GetSystemLocale(), SetDefaults(), and UseLocaleCollation().
m_temperatureUnit
CTemperature::Unit CLangInfo::m_temperatureUnit protected
Referenced by CLangInfo(), GetTemperatureUnit(), GetTemperatureUnitString(), and SetTemperatureUnit().
m_timeFormat
std::string CLangInfo::m_timeFormat protected
Referenced by CLangInfo(), GetTimeFormat(), and SetTimeFormat().
m_use24HourClock
bool CLangInfo::m_use24HourClock protected
Referenced by CLangInfo(), GetMeridiemSymbol(), OnSettingChanged(), Set24HourClock(), Set24HourClock(), SetTimeFormat(), and Use24HourClock().
The documentation for this class was generated from the following files:
LangInfo.h
LangInfo.cpp