Kodi Documentation: KODI::GAME::CGameClientStreamAudio Class Reference
KODI::GAME::CGameClientStreamAudio Class Reference
Games
#include <GameClientStreamAudio.h>
Public Member Functions
CGameClientStreamAudio (double sampleRate)
~CGameClientStreamAudio () override
bool OpenStream (RETRO::IRetroPlayerStream *stream, const game_stream_properties &properties) override
Open the stream.
void CloseStream () override
Release the RetroPlayer stream resource.
void AddData (const game_stream_packet &packet) override
Add a data packet to a stream.
Public Member Functions inherited from KODI::GAME::IGameClientStream
virtual ~IGameClientStream ()=default
virtual bool GetBuffer (unsigned int width, unsigned int height, game_stream_buffer &buffer)
Get a buffer for zero-copy stream data.
virtual void ReleaseBuffer (game_stream_buffer &buffer)
Free an allocated buffer.
Static Private Member Functions
static RETRO::AudioStreamProperties * TranslateProperties (const game_stream_audio_properties &properties, double sampleRate)
Private Attributes
const double m_sampleRate
RETRO::IRetroPlayerStream * m_stream = nullptr
Constructor & Destructor Documentation
CGameClientStreamAudio()
CGameClientStreamAudio::CGameClientStreamAudio (double sampleRate)
~CGameClientStreamAudio()
KODI::GAME::CGameClientStreamAudio::~CGameClientStreamAudio () inline override
References CloseStream().
Member Function Documentation
AddData()
void CGameClientStreamAudio::AddData (const game_stream_packet & packet) override virtual
Add a data packet to a stream.
Parameters
packet The data packet
Implements KODI::GAME::IGameClientStream.
References KODI::RETRO::IRetroPlayerStream::AddStreamData(), game_stream_packet::audio, game_stream_audio_packet::data, GAME_STREAM_AUDIO, m_stream, game_stream_audio_packet::size, and game_stream_packet::type.
CloseStream()
void CGameClientStreamAudio::CloseStream () override virtual
Release the RetroPlayer stream resource.
Implements KODI::GAME::IGameClientStream.
References KODI::RETRO::IRetroPlayerStream::CloseStream(), and m_stream.
Referenced by ~CGameClientStreamAudio().
OpenStream()
bool CGameClientStreamAudio::OpenStream (RETRO::IRetroPlayerStream * stream, const game_stream_properties & properties) override virtual
Open the stream.
Parameters
stream The RetroPlayer resource to take ownership of
Returns
True if the stream was opened, false otherwise
Implements KODI::GAME::IGameClientStream.
References game_stream_properties::audio, CLog::Log(), LOGERROR, m_sampleRate, m_stream, KODI::RETRO::CRetroPlayerAudio::OpenStream(), and TranslateProperties().
TranslateProperties()
RETRO::AudioStreamProperties * CGameClientStreamAudio::TranslateProperties (const game_stream_audio_properties & properties, double sampleRate) static private
References KODI::RETRO::CH_NULL, game_stream_audio_properties::channel_map, channelMap, KODI::RETRO::FMT_UNKNOWN, game_stream_audio_properties::format, GAME_CH_NULL, CLog::Log(), LOGERROR, KODI::GAME::CGameClientTranslator::TranslateAudioChannel(), and KODI::GAME::CGameClientTranslator::TranslatePCMFormat().
Referenced by OpenStream().
Member Data Documentation
m_sampleRate
const double KODI::GAME::CGameClientStreamAudio::m_sampleRate private
Referenced by OpenStream().
m_stream
RETRO::IRetroPlayerStream* KODI::GAME::CGameClientStreamAudio::m_stream = nullptr private
Referenced by AddData(), CloseStream(), and OpenStream().
The documentation for this class was generated from the following files:
GameClientStreamAudio.h
GameClientStreamAudio.cpp