Kodi Documentation: CAEChannelInfo Class Reference
CAEChannelInfo Class Reference
#include <AEChannelInfo.h>
Public Member Functions
CAEChannelInfo ()
CAEChannelInfo (const enum AEChannel *rhs)
CAEChannelInfo (const enum AEStdChLayout rhs)
~CAEChannelInfo ()=default
CAEChannelInfo (const CAEChannelInfo &)=default
CAEChannelInfo & operator= (const CAEChannelInfo &rhs)
CAEChannelInfo & operator= (const enum AEChannel *rhs)
CAEChannelInfo & operator= (const enum AEStdChLayout rhs)
bool operator== (const CAEChannelInfo &rhs) const
bool operator!= (const CAEChannelInfo &rhs) const
CAEChannelInfo & operator+= (const enum AEChannel &rhs)
CAEChannelInfo & operator-= (const enum AEChannel &rhs)
enum AEChannel operator[] (unsigned int i) const
operator std::string () const
void ResolveChannels (const CAEChannelInfo &rhs)
void Reset ()
unsigned int Count () const
bool HasChannel (const enum AEChannel ch) const
bool IsChannelValid (const unsigned int pos)
bool IsLayoutValid ()
bool ContainsChannels (const CAEChannelInfo &rhs) const
void ReplaceChannel (const enum AEChannel from, const enum AEChannel to)
int BestMatch (const std::vector< CAEChannelInfo > &dsts, int *score=NULL) const
void AddMissingChannels (const CAEChannelInfo &rhs)
Static Public Member Functions
static const char * GetChName (const enum AEChannel ch)
Private Attributes
unsigned int m_channelCount
enum AEChannel m_channels [AE_CH_MAX]
Friends
class CHelper_libKODI_audioengine
Constructor & Destructor Documentation
CAEChannelInfo() [1/4]
CAEChannelInfo::CAEChannelInfo ()
References Reset().
CAEChannelInfo() [2/4]
CAEChannelInfo::CAEChannelInfo (const enum AEChannel * rhs) explicit
CAEChannelInfo() [3/4]
CAEChannelInfo::CAEChannelInfo (const enum AEStdChLayout rhs)
~CAEChannelInfo()
CAEChannelInfo::~CAEChannelInfo () default
CAEChannelInfo() [4/4]
CAEChannelInfo::CAEChannelInfo (const CAEChannelInfo &) default
Member Function Documentation
AddMissingChannels()
void CAEChannelInfo::AddMissingChannels (const CAEChannelInfo & rhs)
References Count(), and HasChannel().
Referenced by BestMatch(), and CAESinkALSA::EnumerateDevice().
BestMatch()
int CAEChannelInfo::BestMatch (const std::vector< CAEChannelInfo > & dsts, int * score = NULL) const
References AddMissingChannels(), Count(), HasChannel(), and ResolveChannels().
Referenced by CAESinkALSA::SelectALSAChannelMap().
ContainsChannels()
bool CAEChannelInfo::ContainsChannels (const CAEChannelInfo & rhs) const
References HasChannel(), m_channelCount, and m_channels.
Referenced by CAESinkALSA::SelectALSAChannelMap().
Count()
unsigned int CAEChannelInfo::Count () const inline
References m_channelCount.
Referenced by CDVDAudioCodecAndroidMediaCodec::AddData(), AddMissingChannels(), CAESinkALSA::AEChannelMapToALSAchmap(), anonymous_namespace{AESinkPipewire.cpp}::AEChannelMapToPWChannelMap(), ActiveAE::CActiveAE::ApplySettingsToFormat(), BestMatch(), CAEEncoderFFmpeg::BuildChannelLayout(), ActiveAE::CActiveAEBufferPoolResample::ChangeResampler(), ActiveAE::CActiveAE::Configure(), ActiveAE::CActiveAEBufferPoolResample::ConfigureResampler(), CAudioDecoder::Create(), CAudioSinkAE::Create(), ActiveAE::CActiveAEBufferPool::Create(), ActiveAE::CActiveAEBufferPoolResample::Create(), AE::SINK::CAESinkPipewire::EnumerateDevicesEx(), ADDON::Interface_AudioEngine::get_current_sink_format(), ActiveAE::CActiveAEStream::GetChannelCount(), CAESinkALSA::GetChannelLayout(), CAudioDecoder::GetChannels(), CDVDAudioCodecAndroidMediaCodec::GetData(), CDVDAudioCodecFFmpeg::GetData(), CDVDAudioCodecFFmpeg::GetData(), VideoPlayerCodec::Init(), ActiveAE::CActiveAEResampleFFMPEG::Init(), CAESinkDirectSound::Initialize(), CAESinkALSA::Initialize(), CAESinkAUDIOTRACK::Initialize(), CAESinkDARWINIOS::Initialize(), CAESinkWASAPI::InitializeExclusive(), CAESinkXAudio::InitializeInternal(), ActiveAE::CActiveAEStream::InitRemapper(), ActiveAE::CActiveAESink::OpenSink(), KODI::RETRO::CRetroPlayerAudio::OpenStream(), CVideoPlayerAudio::ProcessDecoderOutput(), PAPlayer::QueueData(), PAPlayer::QueueNextFileEx(), CAudioDecoder::ReadSamples(), ActiveAE::CActiveAE::ResampleSound(), CAESinkALSA::SelectALSAChannelMap(), SinkInfoRequestCallback(), and PAPlayer::UpdateGUIData().
GetChName()
const char * CAEChannelInfo::GetChName (const enum AEChannel ch) static
References AE_CH_MAX.
HasChannel()
bool CAEChannelInfo::HasChannel (const enum AEChannel ch) const
References m_channelCount, and m_channels.
Referenced by AddMissingChannels(), BestMatch(), ContainsChannels(), EnumerateDevices(), and ResolveChannels().
IsChannelValid()
bool CAEChannelInfo::IsChannelValid (const unsigned int pos)
References AE_CH_NULL, AE_CH_UNKNOWN1, m_channelCount, and m_channels.
Referenced by IsLayoutValid().
IsLayoutValid()
bool CAEChannelInfo::IsLayoutValid ()
References IsChannelValid(), and m_channelCount.
Referenced by KODI::RETRO::CRetroPlayerAudio::OpenStream().
operator std::string()
CAEChannelInfo::operator std::string () const
References m_channels.
operator!=()
bool CAEChannelInfo::operator!= (const CAEChannelInfo & rhs) const
operator+=()
CAEChannelInfo & CAEChannelInfo::operator+= (const enum AEChannel & rhs)
References AE_CH_MAX, AE_CH_NULL, m_channelCount, and m_channels.
operator-=()
CAEChannelInfo & CAEChannelInfo::operator-= (const enum AEChannel & rhs)
References AE_CH_MAX, AE_CH_NULL, m_channelCount, and m_channels.
operator=() [1/3]
CAEChannelInfo & CAEChannelInfo::operator= (const CAEChannelInfo & rhs)
References m_channelCount, and m_channels.
operator=() [2/3]
CAEChannelInfo & CAEChannelInfo::operator= (const enum AEChannel * rhs)
References AE_CH_MAX, AE_CH_NULL, m_channelCount, m_channels, and Reset().
operator=() [3/3]
CAEChannelInfo & CAEChannelInfo::operator= (const enum AEStdChLayout rhs)
References AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FR, AE_CH_LAYOUT_INVALID, AE_CH_LAYOUT_MAX, AE_CH_LFE, AE_CH_NULL, AE_CH_SL, AE_CH_SR, and layouts.
operator==()
bool CAEChannelInfo::operator== (const CAEChannelInfo & rhs) const
References m_channelCount, and m_channels.
operator[]()
enum AEChannel CAEChannelInfo::operator[] (unsigned int i) const
ReplaceChannel()
void CAEChannelInfo::ReplaceChannel (const enum AEChannel from, const enum AEChannel to)
References m_channelCount, and m_channels.
Referenced by ActiveAE::CActiveAE::ApplySettingsToFormat(), and CAESinkALSA::GetAlternateLayoutForm().
Reset()
void CAEChannelInfo::Reset ()
References AE_CH_NULL, m_channelCount, and m_channels.
Referenced by CAESinkFactoryWin::AEChannelsFromSpeakerMask(), CAESinkDirectSound::AEChannelsFromSpeakerMask(), CAEEncoderFFmpeg::BuildChannelLayout(), CDVDAudioCodecFFmpeg::BuildChannelMap(), ActiveAE::CActiveAEBufferPool::CActiveAEBufferPool(), ActiveAE::CActiveAEBufferPoolResample::CActiveAEBufferPoolResample(), CAEChannelInfo(), CAESinkDirectSound::CAESinkDirectSound(), CAESinkWASAPI::CAESinkWASAPI(), CAESinkDirectSound::EnumerateDevicesEx(), CAESinkWASAPI::EnumerateDevicesEx(), CAESinkXAudio::EnumerateDevicesEx(), CAESinkAUDIOTRACK::EnumerateDevicesEx(), CAEUtil::GetAEChannelLayout(), ActiveAE::CActiveAEStream::InitRemapper(), operator=(), PAChannelToAEChannelMap(), and ResolveChannels().
ResolveChannels()
void CAEChannelInfo::ResolveChannels (const CAEChannelInfo & rhs)
References AE_CH_BC, AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FR, AE_CH_SL, AE_CH_SR, HasChannel(), m_channelCount, m_channels, and Reset().
Referenced by ActiveAE::CActiveAE::ApplySettingsToFormat(), BestMatch(), and ActiveAE::CActiveAE::Configure().
Friends And Related Symbol Documentation
CHelper_libKODI_audioengine
friend class CHelper_libKODI_audioengine friend
Member Data Documentation
m_channelCount
unsigned int CAEChannelInfo::m_channelCount private
Referenced by ContainsChannels(), Count(), HasChannel(), IsChannelValid(), IsLayoutValid(), operator+=(), operator-=(), operator=(), operator=(), operator==(), ReplaceChannel(), Reset(), and ResolveChannels().
m_channels
enum AEChannel CAEChannelInfo::m_channels[AE_CH_MAX] private
Referenced by ActiveAE::CActiveAE::Configure(), ContainsChannels(), CAESinkALSA::EnumerateDevice(), HasChannel(), IsChannelValid(), operator+=(), operator-=(), operator=(), operator=(), operator==(), ReplaceChannel(), Reset(), and ResolveChannels().
The documentation for this class was generated from the following files:
AEChannelInfo.h
AEChannelInfo.cpp