Kodi Documentation: KODI::GAME::CGameSettings Class Reference
KODI::GAME::CGameSettings Class Reference
Games
#include <GameSettings.h>
Public Member Functions
CGameSettings ()
~CGameSettings () override
bool GamesEnabled ()
bool ShowOSDHelp ()
void SetShowOSDHelp (bool bShow)
void ToggleGames ()
bool AutosaveEnabled ()
bool RewindEnabled ()
unsigned int MaxRewindTimeSec ()
std::string GetRAUsername () const
std::string GetRAToken () const
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from Observable
Observable ()=default
virtual ~Observable ()=default
Observable & operator= (const Observable &observable)
virtual void RegisterObserver (Observer *obs)
Register an observer.
virtual void UnregisterObserver (Observer *obs)
Unregister an observer.
virtual void NotifyObservers (const ObservableMessage message=ObservableMessageNone)
Send a message to all observers when m_bObservableChanged is true.
virtual void SetChanged (bool bSetTo=true)
Mark an observable changed.
virtual bool IsObserving (const Observer &obs) const
Check whether this observable is being observed by an observer.
Private Member Functions
std::string LoginToRA (const std::string &username, const std::string &password, std::string token) const
bool IsAccountVerified (const std::string &username, const std::string &token) const
Private Attributes
std::shared_ptr< CSettings > m_settings
Additional Inherited Members
Protected Member Functions inherited from Observable
void SendMessage (const ObservableMessage message)
Send a message to all observer when m_bObservableChanged is true.
Protected Attributes inherited from Observable
std::atomic< bool > m_bObservableChanged {false}
std::vector< Observer * > m_observers
CCriticalSection m_obsCritSection
Constructor & Destructor Documentation
CGameSettings()
CGameSettings::CGameSettings ()
References CServiceBroker::GetSettingsComponent(), and m_settings.
~CGameSettings()
CGameSettings::~CGameSettings () override
References m_settings.
Member Function Documentation
AutosaveEnabled()
bool CGameSettings::AutosaveEnabled ()
References m_settings.
Referenced by KODI::RETRO::CRetroPlayer::CloseFile(), and KODI::RETRO::CRetroPlayerAutoSave::Process().
GamesEnabled()
bool CGameSettings::GamesEnabled ()
References m_settings.
Referenced by KODI::JOYSTICK::CJoystickEasterEgg::OnFinish().
GetRAToken()
std::string CGameSettings::GetRAToken () const
References m_settings.
Referenced by KODI::RETRO::CRetroPlayer::OpenFile().
GetRAUsername()
std::string CGameSettings::GetRAUsername () const
References m_settings.
Referenced by KODI::RETRO::CRetroPlayer::OpenFile().
IsAccountVerified()
bool CGameSettings::IsAccountVerified (const std::string & username, const std::string & token) const private
References data(), XFILE::CFile::LoadFile(), CJSONVariantParser::Parse(), SUCCESS, and CVariant::VariantTypeObject.
Referenced by LoginToRA().
LoginToRA()
std::string CGameSettings::LoginToRA (const std::string & username, const std::string & password, std::string token) const private
References CEventLog::AddWithNotification(), data(), Error, CServiceBroker::GetEventLog(), IsAccountVerified(), XFILE::CFile::LoadFile(), CLog::Log(), LOGERROR, CJSONVariantParser::Parse(), SUCCESS, and CVariant::VariantTypeObject.
Referenced by OnSettingChanged().
MaxRewindTimeSec()
unsigned int CGameSettings::MaxRewindTimeSec ()
References m_settings.
Referenced by KODI::RETRO::CReversiblePlayback::UpdateMemoryStream().
OnSettingChanged()
void CGameSettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References GetValue(), LoginToRA(), m_settings, Observable::NotifyObservers(), ObservableMessageSettingsChanged, and Observable::SetChanged().
RewindEnabled()
bool CGameSettings::RewindEnabled ()
References m_settings.
Referenced by KODI::RETRO::CReversiblePlayback::UpdateMemoryStream().
SetShowOSDHelp()
void CGameSettings::SetShowOSDHelp (bool bShow)
Todo:
Asynchronous save
References m_settings.
Referenced by KODI::GAME::CDialogGameOSD::OnAction(), KODI::GAME::CDialogGameOSD::OnDeinitWindow(), and KODI::RETRO::CGameWindowFullScreen::OnInitWindow().
ShowOSDHelp()
bool CGameSettings::ShowOSDHelp ()
References m_settings.
Referenced by KODI::GAME::CDialogGameOSD::OnAction(), and KODI::RETRO::CGameWindowFullScreen::OnInitWindow().
ToggleGames()
void CGameSettings::ToggleGames ()
References m_settings.
Referenced by KODI::JOYSTICK::CJoystickEasterEgg::OnFinish().
Member Data Documentation
m_settings
std::shared_ptr<CSettings> KODI::GAME::CGameSettings::m_settings private
Referenced by AutosaveEnabled(), CGameSettings(), GamesEnabled(), GetRAToken(), GetRAUsername(), MaxRewindTimeSec(), OnSettingChanged(), RewindEnabled(), SetShowOSDHelp(), ShowOSDHelp(), ToggleGames(), and ~CGameSettings().
The documentation for this class was generated from the following files:
games/GameSettings.h
games/GameSettings.cpp