Kodi Documentation: ADDON::CVFSEntry Class Reference
ADDON::CVFSEntry Class Reference
A virtual filesystem entry add-on.
#include <VFSEntry.h>
Classes
struct ProtocolInfo
A structure encapsulating properties of supplied protocol.
Public Member Functions
CVFSEntry (const AddonInfoPtr &addonInfo)
Construct from add-on properties.
~CVFSEntry () override
void * Open (const CURL &url)
void * OpenForWrite (const CURL &url, bool bOverWrite)
bool Exists (const CURL &url)
int Stat (const CURL &url, struct __stat64 *buffer)
ssize_t Read (void *ctx, void *lpBuf, size_t uiBufSize)
ssize_t Write (void *ctx, const void *lpBuf, size_t uiBufSize)
int64_t Seek (void *ctx, int64_t iFilePosition, int iWhence=SEEK_SET)
int Truncate (void *ctx, int64_t size)
void Close (void *ctx)
int64_t GetPosition (void *ctx)
int64_t GetLength (void *ctx)
int GetChunkSize (void *ctx)
int IoControl (void *ctx, XFILE::EIoControl request, void *param)
bool Delete (const CURL &url)
bool Rename (const CURL &url, const CURL &url2)
bool GetDirectory (const CURL &url, CFileItemList &items, void *ctx)
bool DirectoryExists (const CURL &url)
bool RemoveDirectory (const CURL &url)
bool CreateDirectory (const CURL &url)
void ClearOutIdle ()
void DisconnectAll ()
bool ContainsFiles (const CURL &url, CFileItemList &items)
const std::string & GetProtocols () const
const std::string & GetExtensions () const
bool HasFiles () const
bool HasDirectories () const
bool HasFileDirectories () const
const std::string & GetZeroconfType () const
const ProtocolInfo & GetProtocolInfo () const
Public Member Functions inherited from ADDON::IAddonInstanceHandler
IAddonInstanceHandler (ADDON_TYPE type, const AddonInfoPtr &addonInfo, AddonInstanceId instanceId=ADDON_INSTANCE_ID_UNUSED, KODI_HANDLE parentInstance=nullptr, const std::string &uniqueWorkID="")
Class constructor for handling add-on instance processes, allowing an add-on to handle multiple work simultaneously and independently.
virtual ~IAddonInstanceHandler ()
ADDON_TYPE UsedType () const
AddonInstanceId InstanceId () const
const std::string & UniqueWorkID ()
std::string ID () const
AddonInstanceId InstanceID () const
std::string Name () const
std::string Author () const
std::string Icon () const
std::string Path () const
std::string Profile () const
CAddonVersion Version () const
ADDON_STATUS CreateInstance ()
void DestroyInstance ()
const AddonDllPtr & Addon () const
AddonInfoPtr GetAddonInfo () const
virtual void OnPreInstall ()
virtual void OnPostInstall (bool update, bool modal)
virtual void OnPreUnInstall ()
virtual void OnPostUnInstall ()
Protected Attributes
std::string m_protocols
Protocols for VFS entry.
std::string m_extensions
Extensions for VFS entry.
std::string m_zeroconf
Zero conf announce string for VFS protocol.
bool m_files
Vfs entry can read files.
bool m_directories
VFS entry can list directories.
bool m_filedirectories
VFS entry contains file directories.
ProtocolInfo m_protocolInfo
Info about protocol for network dialog.
Protected Attributes inherited from ADDON::IAddonInstanceHandler
KODI_ADDON_INSTANCE_INFO m_info {}
KODI_ADDON_INSTANCE_STRUCT m_ifc {}
Detailed Description
A virtual filesystem entry add-on.
Constructor & Destructor Documentation
CVFSEntry()
ADDON::CVFSEntry::CVFSEntry (const AddonInfoPtr & addonInfo) explicit
Construct from add-on properties.
Parameters
addonInfo General addon properties
References ADDON_STATUS_OK, ADDON::IAddonInstanceHandler::CreateInstance(), AddonToKodiFuncTable_VFSEntry::kodiInstance, CLog::Log(), LOGFATAL, ADDON::IAddonInstanceHandler::m_ifc, m_protocolInfo, AddonInstance_VFSEntry::props, AddonInstance_VFSEntry::toAddon, AddonInstance_VFSEntry::toKodi, ADDON::CVFSEntry::ProtocolInfo::type, ADDON::VFS, and KODI_ADDON_INSTANCE_STRUCT::vfs.
~CVFSEntry()
ADDON::CVFSEntry::~CVFSEntry () override
References ADDON::IAddonInstanceHandler::DestroyInstance(), ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::props, AddonInstance_VFSEntry::toAddon, AddonInstance_VFSEntry::toKodi, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Member Function Documentation
ClearOutIdle()
void ADDON::CVFSEntry::ClearOutIdle ()
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Close()
void ADDON::CVFSEntry::Close (void * ctx)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
ContainsFiles()
bool ADDON::CVFSEntry::ContainsFiles (const CURL & url, CFileItemList & items)
References ADDON_STANDARD_STRING_LENGTH, ADDON::IAddonInstanceHandler::m_ifc, CFileItem::SetPath(), AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, KODI_ADDON_INSTANCE_STRUCT::vfs, and ADDON::VFSDirEntriesToCFileItemList().
CreateDirectory()
bool ADDON::CVFSEntry::CreateDirectory (const CURL & url)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Delete()
bool ADDON::CVFSEntry::Delete (const CURL & url)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, and KODI_ADDON_INSTANCE_STRUCT::vfs.
DirectoryExists()
bool ADDON::CVFSEntry::DirectoryExists (const CURL & url)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, and KODI_ADDON_INSTANCE_STRUCT::vfs.
DisconnectAll()
void ADDON::CVFSEntry::DisconnectAll ()
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Exists()
bool ADDON::CVFSEntry::Exists (const CURL & url)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, and KODI_ADDON_INSTANCE_STRUCT::vfs.
GetChunkSize()
int ADDON::CVFSEntry::GetChunkSize (void * ctx)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
GetDirectory()
bool ADDON::CVFSEntry::GetDirectory (const CURL & url, CFileItemList & items, void * ctx)
References VFSGetDirectoryCallbacks::ctx, ADDON::CVFSEntryIDirectoryWrapper::DoGetKeyboardInput(), ADDON::CVFSEntryIDirectoryWrapper::DoRequireAuthentication(), ADDON::CVFSEntryIDirectoryWrapper::DoSetErrorDialog(), ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, KODI_ADDON_INSTANCE_STRUCT::vfs, and ADDON::VFSDirEntriesToCFileItemList().
GetExtensions()
const std::string & ADDON::CVFSEntry::GetExtensions () const inline
References m_extensions.
GetLength()
int64_t ADDON::CVFSEntry::GetLength (void * ctx)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
GetPosition()
int64_t ADDON::CVFSEntry::GetPosition (void * ctx)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
GetProtocolInfo()
const ProtocolInfo & ADDON::CVFSEntry::GetProtocolInfo () const inline
References m_protocolInfo.
GetProtocols()
const std::string & ADDON::CVFSEntry::GetProtocols () const inline
References m_protocols.
GetZeroconfType()
const std::string & ADDON::CVFSEntry::GetZeroconfType () const inline
References m_zeroconf.
HasDirectories()
bool ADDON::CVFSEntry::HasDirectories () const inline
References m_directories.
HasFileDirectories()
bool ADDON::CVFSEntry::HasFileDirectories () const inline
References m_filedirectories.
HasFiles()
bool ADDON::CVFSEntry::HasFiles () const inline
References m_files.
IoControl()
int ADDON::CVFSEntry::IoControl (void * ctx, XFILE::EIoControl request, void * param)
References VFS_CACHE_STATUS_DATA::currate, XFILE::SCacheStatus::currate, VFS_CACHE_STATUS_DATA::forward, XFILE::SCacheStatus::forward, XFILE::IOCTRL_CACHE_SETRATE, XFILE::IOCTRL_CACHE_STATUS, XFILE::IOCTRL_NATIVE, XFILE::IOCTRL_SEEK_POSSIBLE, XFILE::IOCTRL_SET_CACHE, XFILE::IOCTRL_SET_RETRY, VFS_CACHE_STATUS_DATA::lowrate, XFILE::SCacheStatus::lowrate, ADDON::IAddonInstanceHandler::m_ifc, VFS_CACHE_STATUS_DATA::maxrate, XFILE::SCacheStatus::maxrate, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Open()
void * ADDON::CVFSEntry::Open (const CURL & url)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, and KODI_ADDON_INSTANCE_STRUCT::vfs.
OpenForWrite()
void * ADDON::CVFSEntry::OpenForWrite (const CURL & url, bool bOverWrite)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Read()
ssize_t ADDON::CVFSEntry::Read (void * ctx, void * lpBuf, size_t uiBufSize)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
RemoveDirectory()
bool ADDON::CVFSEntry::RemoveDirectory (const CURL & url)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Rename()
bool ADDON::CVFSEntry::Rename (const CURL & url, const CURL & url2)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Seek()
int64_t ADDON::CVFSEntry::Seek (void * ctx, int64_t iFilePosition, int iWhence = SEEK_SET)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Stat()
int ADDON::CVFSEntry::Stat (const CURL & url, struct __stat64 * buffer)
References STAT_STRUCTURE::accessTime, STAT_STRUCTURE::deviceId, STAT_STRUCTURE::fileSerialNumber, STAT_STRUCTURE::isBlock, STAT_STRUCTURE::isCharacter, STAT_STRUCTURE::isDirectory, STAT_STRUCTURE::isFifo, STAT_STRUCTURE::isRegular, STAT_STRUCTURE::isSocket, STAT_STRUCTURE::isSymLink, ADDON::IAddonInstanceHandler::m_ifc, STAT_STRUCTURE::modificationTime, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFLNK, S_IFREG, S_IFSOCK, STAT_STRUCTURE::size, STAT_STRUCTURE::statusTime, AddonInstance_VFSEntry::toAddon, ADDON::CVFSURLWrapper::url, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Truncate()
int ADDON::CVFSEntry::Truncate (void * ctx, int64_t size)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Write()
ssize_t ADDON::CVFSEntry::Write (void * ctx, const void * lpBuf, size_t uiBufSize)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VFSEntry::toAddon, and KODI_ADDON_INSTANCE_STRUCT::vfs.
Member Data Documentation
m_directories
bool ADDON::CVFSEntry::m_directories protected
VFS entry can list directories.
Referenced by HasDirectories().
m_extensions
std::string ADDON::CVFSEntry::m_extensions protected
Extensions for VFS entry.
Referenced by GetExtensions().
m_filedirectories
bool ADDON::CVFSEntry::m_filedirectories protected
VFS entry contains file directories.
Referenced by HasFileDirectories().
m_files
bool ADDON::CVFSEntry::m_files protected
Vfs entry can read files.
Referenced by HasFiles().
m_protocolInfo
ProtocolInfo ADDON::CVFSEntry::m_protocolInfo protected
Info about protocol for network dialog.
Referenced by CVFSEntry(), and GetProtocolInfo().
m_protocols
std::string ADDON::CVFSEntry::m_protocols protected
Protocols for VFS entry.
Referenced by GetProtocols().
m_zeroconf
std::string ADDON::CVFSEntry::m_zeroconf protected
Zero conf announce string for VFS protocol.
Referenced by GetZeroconfType().
The documentation for this class was generated from the following files:
VFSEntry.h
VFSEntry.cpp