Kodi Documentation: KODI::KEYBOARD::CKeyboardLayout Class Reference
KODI::KEYBOARD::CKeyboardLayout Class Reference
Input » Keyboard
#include <KeyboardLayout.h>
Public Types
enum ModifierKey { ModifierKeyNone = 0x00 , ModifierKeyShift = 0x01 , ModifierKeySymbol = 0x02 }
Public Member Functions
CKeyboardLayout ()=default
virtual ~CKeyboardLayout ()
IInputCodingTablePtr GetCodingTable ()
bool Load (const tinyxml2::XMLElement *element)
std::string GetIdentifier () const
std::string GetName () const
const std::string & GetLanguage () const
const std::string & GetLayout () const
std::string GetCharAt (unsigned int row, unsigned int column, unsigned int modifiers=0) const
Private Types
typedef std::vector< std::vector< std::string > > KeyboardRows
typedef std::map< unsigned int, KeyboardRows > Keyboards
Static Private Member Functions
static std::vector< std::string > BreakCharacters (const std::string &chars)
Private Attributes
std::string m_language
std::string m_layout
Keyboards m_keyboards
IInputCodingTablePtr m_codingtable
Member Typedef Documentation
KeyboardRows
typedef std::vector<std::vector<std::string> > KODI::KEYBOARD::CKeyboardLayout::KeyboardRows private
Keyboards
typedef std::map<unsigned int, KeyboardRows> KODI::KEYBOARD::CKeyboardLayout::Keyboards private
Member Enumeration Documentation
ModifierKey
enum KODI::KEYBOARD::CKeyboardLayout::ModifierKey
Enumerator
ModifierKeyNone
ModifierKeyShift
ModifierKeySymbol
Constructor & Destructor Documentation
CKeyboardLayout()
KODI::KEYBOARD::CKeyboardLayout::CKeyboardLayout () default
~CKeyboardLayout()
CKeyboardLayout::~CKeyboardLayout () virtual default
Member Function Documentation
BreakCharacters()
std::vector< std::string > CKeyboardLayout::BreakCharacters (const std::string & chars) static private
References g_charsetConverter.
Referenced by Load().
GetCharAt()
std::string CKeyboardLayout::GetCharAt (unsigned int row, unsigned int column, unsigned int modifiers = 0) const
References m_keyboards, and ModifierKeyNone.
Referenced by ADDON::Interface_General::get_keyboard_layout(), and CGUIDialogKeyboardGeneric::UpdateButtons().
GetCodingTable()
IInputCodingTablePtr KODI::KEYBOARD::CKeyboardLayout::GetCodingTable () inline
References m_codingtable.
Referenced by CGUIDialogKeyboardGeneric::UpdateButtons().
GetIdentifier()
std::string CKeyboardLayout::GetIdentifier () const
References m_language, and m_layout.
Referenced by KODI::KEYBOARD::CKeyboardLayoutManager::Load().
GetLanguage()
const std::string & KODI::KEYBOARD::CKeyboardLayout::GetLanguage () const inline
References m_language.
GetLayout()
const std::string & KODI::KEYBOARD::CKeyboardLayout::GetLayout () const inline
References m_layout.
GetName()
std::string CKeyboardLayout::GetName () const
References g_localizeStrings, CLocalizeStrings::Get(), m_language, and m_layout.
Referenced by ADDON::Interface_General::change_keyboard_layout(), ADDON::Interface_General::get_keyboard_layout(), CGUIDialogKeyboardGeneric::OnLayout(), and CGUIDialogKeyboardGeneric::UpdateButtons().
Load()
bool CKeyboardLayout::Load (const tinyxml2::XMLElement * element)
References BreakCharacters(), CInputCodingTableFactory::CreateCodingTable(), CLog::Log(), LOGWARNING, m_codingtable, m_keyboards, m_language, m_layout, ModifierKeyNone, ModifierKeyShift, ModifierKeySymbol, and push_back().
Referenced by KODI::KEYBOARD::CKeyboardLayoutManager::Load().
Member Data Documentation
m_codingtable
IInputCodingTablePtr KODI::KEYBOARD::CKeyboardLayout::m_codingtable private
Referenced by GetCodingTable(), and Load().
m_keyboards
Keyboards KODI::KEYBOARD::CKeyboardLayout::m_keyboards private
Referenced by GetCharAt(), and Load().
m_language
std::string KODI::KEYBOARD::CKeyboardLayout::m_language private
Referenced by GetIdentifier(), GetLanguage(), GetName(), and Load().
m_layout
std::string KODI::KEYBOARD::CKeyboardLayout::m_layout private
Referenced by GetIdentifier(), GetLayout(), GetName(), and Load().
The documentation for this class was generated from the following files:
KeyboardLayout.h
KeyboardLayout.cpp