Kodi Documentation: XFILE::CAudioBookFileDirectory Class Reference
XFILE::CAudioBookFileDirectory Class Reference
#include <AudioBookFileDirectory.h>
Public Member Functions
~CAudioBookFileDirectory (void) override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool Exists (const CURL &url) override
Check for directory existence.
bool ContainsFiles (const CURL &url) override
bool IsAllowed (const CURL &url) const override
Whether this file should be listed.
Public Member Functions inherited from XFILE::IFileDirectory
~IFileDirectory () override=default
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool Create (const CURL &url)
Create the directory.
virtual bool Remove (const CURL &url)
Removes the directory.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool AllowAll () const
Whether to allow all files/folders to be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Protected Attributes
AVIOContext * m_ioctx = nullptr
AVFormatContext * m_fctx = nullptr
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Additional Inherited Members
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
~CAudioBookFileDirectory()
CAudioBookFileDirectory::~CAudioBookFileDirectory (void) override
References m_fctx, and m_ioctx.
Member Function Documentation
ContainsFiles()
bool CAudioBookFileDirectory::ContainsFiles (const CURL & url) override virtual
Implements XFILE::IFileDirectory.
References cfile_file_read(), cfile_file_seek(), CURL::Get(), XFILE::IOCTRL_SEEK_POSSIBLE, m_fctx, and m_ioctx.
Referenced by Exists(), and GetDirectory().
Exists()
bool CAudioBookFileDirectory::Exists (const CURL & url) override virtual
Check for directory existence.
Parameters
url Directory to check.
Returns
Returns true, if directory exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
References ContainsFiles(), and XFILE::CFile::Exists().
GetDirectory()
bool CAudioBookFileDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References CFileItemList::Add(), ContainsFiles(), CUtil::ConvertMilliSecsToSecs(), CUtil::ConvertMilliSecsToSecsInt(), CUtil::ConvertSecsToMilliSecs(), g_localizeStrings, CURL::Get(), CLocalizeStrings::Get(), m_fctx, and IMAGE_FILES::URLFromFile().
IsAllowed()
bool XFILE::CAudioBookFileDirectory::IsAllowed (const CURL & url) const inline override virtual
Whether this file should be listed.
Test if file have an allowed extension, as specified with SetMask()
Parameters
url File to test.
Returns
Returns true if the file should be listed
Parameters
strFile File to test
Returns
true if file is allowed
Note
If extension is ".ifo", filename format must be "vide_ts.ifo" or "vts_##_0.ifo". If extension is ".dat", filename format must be "AVSEQ##(#).DAT", "ITEM###(#).DAT" or "MUSIC##(#).DAT".
Reimplemented from XFILE::IDirectory.
Member Data Documentation
m_fctx
AVFormatContext* XFILE::CAudioBookFileDirectory::m_fctx = nullptr protected
Referenced by ContainsFiles(), GetDirectory(), and ~CAudioBookFileDirectory().
m_ioctx
AVIOContext* XFILE::CAudioBookFileDirectory::m_ioctx = nullptr protected
Referenced by ContainsFiles(), and ~CAudioBookFileDirectory().
The documentation for this class was generated from the following files:
AudioBookFileDirectory.h
AudioBookFileDirectory.cpp