Kodi Documentation: ADDON::Interface_GUIDialogSelect Struct Reference
ADDON::Interface_GUIDialogSelect Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Select.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static int open (KODI_HANDLE kodiBase, const char *heading, const char *entries[], unsigned int size, int selected, unsigned int autoclose)
callback functions from add-on to kodi
static bool open_multi_select (KODI_HANDLE kodiBase, const char *heading, const char *entryIDs[], const char *entryNames[], bool entriesSelected[], unsigned int size, unsigned int autoclose)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/dialogs/Select.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIDialogSelect::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogSelect, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
Init()
void ADDON::Interface_GUIDialogSelect::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogSelect, AddonToKodiFuncTable_Addon::kodi_gui, open(), AddonToKodiFuncTable_kodi_gui_dialogSelect::open, open_multi_select(), AddonToKodiFuncTable_kodi_gui_dialogSelect::open_multi_select, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
open()
int ADDON::Interface_GUIDialogSelect::open (KODI_HANDLE kodiBase, const char * heading, const char * entries[], unsigned int size, int selected, unsigned int autoclose) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References CGUIDialogSelect::Add(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedItem(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUIDialog::Open(), CGUIDialogSelect::Reset(), CGUIDialog::SetAutoClose(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetSelected(), and WINDOW_DIALOG_SELECT.
Referenced by Init().
open_multi_select()
bool ADDON::Interface_GUIDialogSelect::open_multi_select (KODI_HANDLE kodiBase, const char * heading, const char * entryIDs[], const char * entryNames[], bool entriesSelected[], unsigned int size, unsigned int autoclose) static
References CGUIDialogSelect::Add(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedItems(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), CGUIDialogBoxBase::IsConfirmed(), CLog::Log(), LOGERROR, CGUIDialog::Open(), CGUIDialogSelect::Reset(), CGUIDialog::SetAutoClose(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetMultiSelection(), CGUIDialogSelect::SetSelected(), and WINDOW_DIALOG_SELECT.
Referenced by Init().
The documentation for this struct was generated from the following files:
addons/interfaces/gui/dialogs/select.h
Select.cpp