Kodi Documentation: CWinEventsWin32 Class Reference
CWinEventsWin32 Class Reference
#include <WinEventsWin32.h>
Public Member Functions
bool MessagePump () override
Public Member Functions inherited from IWinEvents
virtual ~IWinEvents ()=default
Static Public Member Functions
static LRESULT CALLBACK WndProc (HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
Static Private Member Functions
static void RegisterDeviceInterfaceToHwnd (GUID InterfaceClassGuid, HWND hWnd, HDEVNOTIFY *hDeviceNotify)
static void WindowFromScreenCoords (HWND hWnd, POINT *point)
static void OnGestureNotify (HWND hWnd, LPARAM lParam)
static void OnGesture (HWND hWnd, LPARAM lParam)
Static Private Attributes
static int m_originalZoomDistance = 0
static Pointer m_touchPointer
static CGenericTouchSwipeDetector * m_touchSwipeDetector = nullptr
Member Function Documentation
MessagePump()
bool CWinEventsWin32::MessagePump () override virtual
Implements IWinEvents.
OnGesture()
void CWinEventsWin32::OnGesture (HWND hWnd, LPARAM lParam) static private
References Pointer::current, Pointer::down, CGenericTouchActionHandler::GetInstance(), Pointer::last, LODWORD, m_originalZoomDistance, m_touchPointer, m_touchSwipeDetector, Pointer::moving, CGenericTouchActionHandler::OnRotate(), CGenericTouchActionHandler::OnTap(), CGenericTouchSwipeDetector::OnTouchDown(), CGenericTouchActionHandler::OnTouchGestureEnd(), CGenericTouchActionHandler::OnTouchGesturePan(), CGenericTouchActionHandler::OnTouchGestureStart(), CGenericTouchSwipeDetector::OnTouchMove(), CGenericTouchSwipeDetector::OnTouchUp(), CGenericTouchActionHandler::OnZoomPinch(), Pointer::reset(), ROTATE_ANGLE_DEGREE, Touch::time, Touch::valid(), Pointer::velocity(), WindowFromScreenCoords(), CVector::x, and CVector::y.
Referenced by WndProc().
OnGestureNotify()
void CWinEventsWin32::OnGestureNotify (HWND hWnd, LPARAM lParam) static private
References EVENT_RESULT_PAN_HORIZONTAL, EVENT_RESULT_PAN_HORIZONTAL_WITHOUT_INERTIA, EVENT_RESULT_PAN_VERTICAL, EVENT_RESULT_PAN_VERTICAL_WITHOUT_INERTIA, EVENT_RESULT_ROTATE, EVENT_RESULT_SWIPE, EVENT_RESULT_UNHANDLED, EVENT_RESULT_ZOOM, CGenericTouchActionHandler::GetInstance(), m_touchSwipeDetector, and WindowFromScreenCoords().
Referenced by WndProc().
RegisterDeviceInterfaceToHwnd()
void CWinEventsWin32::RegisterDeviceInterfaceToHwnd (GUID InterfaceClassGuid, HWND hWnd, HDEVNOTIFY * hDeviceNotify) static private
Referenced by WndProc().
WindowFromScreenCoords()
void CWinEventsWin32::WindowFromScreenCoords (HWND hWnd, POINT * point) static private
Referenced by OnGesture(), OnGestureNotify(), and WndProc().
WndProc()
LRESULT CALLBACK CWinEventsWin32::WndProc (HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam) static
References BONJOUR_BROWSER_EVENT, BONJOUR_EVENT, XBMC_MouseButtonEvent::button, XBMC_Event::button, KODI::WINDOWING::WINDOWS::DIB_InitOSKeymap(), EXTENDED_KEYMASK, CWIN32Util::FirstDriveFromMask(), KODI::PLATFORM::WINDOWS::FromW(), g_application, g_hWnd, g_sizeMoveHight, g_sizeMoveMoving, g_sizeMoveSizing, g_sizeMoveWidth, g_sizeMoveX, g_sizeMoveY, g_uQueryCancelAutoPlay, GET_X_LPARAM, GET_Y_LPARAM, CInputManager::GetAction(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetAppPort(), CServiceBroker::GetGUI(), CAction::GetID(), CServiceBroker::GetInputManager(), CZeroconf::GetInstance(), CZeroconfBrowser::GetInstance(), CServiceBroker::GetJobManager(), GetLastError(), CServiceBroker::GetMediaManager(), CAction::GetName(), CServiceBroker::GetPeripherals(), CApplicationPowerHandling::GetRenderGUI(), CGUIComponent::GetWindowManager(), XBMC_ResizeEvent::h, ID_TIMER_HDR, XBMC_Event::key, KEY_APPCOMMAND, XBMC_KeyboardEvent::keysym, CLog::Log(), LOGDEBUG, LOGINFO, LOGWINDOWING, CGUIWindowManager::MarkDirty(), MAX_PATH, XBMC_Event::motion, XBMC_Event::move, OnGesture(), OnGestureNotify(), PERIPHERALS::PERIPHERAL_BUS_USB, CZeroconf::ProcessResults(), CZeroconfBrowser::ProcessResults(), CInputManager::QueueAction(), RegisterDeviceInterfaceToHwnd(), CMediaManager::RemoveAutoSource(), REPEATED_KEYMASK, CApplicationPowerHandling::ResetScreenSaver(), XBMC_Event::resize, CWin32StorageProvider::SetEvent(), CWin32PowerSyscall::SetOnResume(), CWin32PowerSyscall::SetOnSuspend(), CApplicationPowerHandling::SetRenderGUI(), shcne, CMediaSource::strName, CMediaSource::strPath, TEXT, TMSG_TOGGLEFULLSCREEN, TranslateKey(), TRAY_ICON_NOTIFY, PERIPHERALS::CPeripherals::TriggerDeviceScan(), XBMC_Event::type, USB_HID_GUID, XBMC_ResizeEvent::w, WindowFromScreenCoords(), WM_MEDIA_CHANGE, XBMC_MouseMotionEvent::x, XBMC_MouseButtonEvent::x, XBMC_MoveEvent::x, XBMC_BUTTON_LEFT, XBMC_BUTTON_MIDDLE, XBMC_BUTTON_RIGHT, XBMC_BUTTON_WHEELDOWN, XBMC_BUTTON_WHEELUP, XBMC_KEYDOWN, XBMC_KEYUP, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, XBMC_MOUSEMOTION, XBMC_QUIT, XBMC_VIDEOMOVE, XBMC_VIDEORESIZE, XBMC_MouseMotionEvent::y, XBMC_MouseButtonEvent::y, and XBMC_MoveEvent::y.
Referenced by CWinSystemWin32::CreateNewWindow().
Member Data Documentation
m_originalZoomDistance
int CWinEventsWin32::m_originalZoomDistance = 0 static private
Referenced by OnGesture().
m_touchPointer
Pointer CWinEventsWin32::m_touchPointer static private
Referenced by OnGesture().
m_touchSwipeDetector
CGenericTouchSwipeDetector * CWinEventsWin32::m_touchSwipeDetector = nullptr static private
Referenced by OnGesture(), and OnGestureNotify().
The documentation for this class was generated from the following files:
WinEventsWin32.h
WinEventsWin32.cpp