Kodi Documentation: XFILE::CBlurayFile Class Reference
XFILE::CBlurayFile Class Reference
#include <BlurayFile.h>
Public Member Functions
CBlurayFile ()
~CBlurayFile () override
Public Member Functions inherited from XFILE::COverrideFile
COverrideFile (bool writable)
~COverrideFile () override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int Stat (struct __stat64 *buffer) override
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
bool Delete (const CURL &url) override
bool Rename (const CURL &url, const CURL &urlnew) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
void Close () override
int64_t GetPosition () override
int64_t GetLength () override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool SetHidden (const CURL &url, bool hidden)
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Protected Member Functions
std::string TranslatePath (const CURL &url) override
Additional Inherited Members
Protected Attributes inherited from XFILE::COverrideFile
CFile m_file
bool m_writable
Constructor & Destructor Documentation
CBlurayFile()
XFILE::CBlurayFile::CBlurayFile (void)
~CBlurayFile()
XFILE::CBlurayFile::~CBlurayFile () override default
Member Function Documentation
TranslatePath()
std::string XFILE::CBlurayFile::TranslatePath (const CURL & url) override protected virtual
Implements XFILE::COverrideFile.
References CURL::GetFileName(), CURL::GetHostName(), and CURL::IsProtocol().
The documentation for this class was generated from the following files:
BlurayFile.h
BlurayFile.cpp