Kodi Documentation: KODI::KEYMAP::CKeymapHandling Class Reference
KODI::KEYMAP::CKeymapHandling Class Reference
#include <KeymapHandling.h>
Public Member Functions
CKeymapHandling (JOYSTICK::IInputProvider *inputProvider, bool pPromiscuous, const IKeymapEnvironment *environment)
~CKeymapHandling () override
void UnregisterInputProvider ()
Unregister the input provider.
JOYSTICK::IInputReceiver * GetInputReceiver (const std::string &controllerId) const
IKeymap * GetKeymap (const std::string &controllerId) const
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Private Member Functions
void LoadKeymaps ()
void UnloadKeymaps ()
Private Attributes
JOYSTICK::IInputProvider * m_inputProvider
const bool m_pPromiscuous
const IKeymapEnvironment *const m_environment
std::vector< std::unique_ptr< IKeymap > > m_keymaps
std::vector< std::unique_ptr< JOYSTICK::IInputHandler > > m_inputHandlers
Constructor & Destructor Documentation
CKeymapHandling()
CKeymapHandling::CKeymapHandling (JOYSTICK::IInputProvider * inputProvider, bool pPromiscuous, const IKeymapEnvironment * environment)
References CServiceBroker::GetInputManager(), LoadKeymaps(), and Observable::RegisterObserver().
~CKeymapHandling()
CKeymapHandling::~CKeymapHandling () override
References CServiceBroker::GetInputManager(), UnloadKeymaps(), and Observable::UnregisterObserver().
Member Function Documentation
GetInputReceiver()
JOYSTICK::IInputReceiver * CKeymapHandling::GetInputReceiver (const std::string & controllerId) const
References m_inputHandlers.
GetKeymap()
IKeymap * CKeymapHandling::GetKeymap (const std::string & controllerId) const
References m_keymaps.
LoadKeymaps()
void CKeymapHandling::LoadKeymaps () private
References CServiceBroker::GetInputManager(), m_environment, m_inputHandlers, m_inputProvider, m_keymaps, m_pPromiscuous, KODI::JOYSTICK::IInputProvider::RegisterInputHandler(), and UnloadKeymaps().
Referenced by CKeymapHandling(), and Notify().
Notify()
void CKeymapHandling::Notify (const Observable & obs, const ObservableMessage msg) override virtual
Process a message from an observable.
Parameters
obs The observable that sends the message.
msg The message.
Implements Observer.
References LoadKeymaps(), and ObservableMessageButtonMapsChanged.
UnloadKeymaps()
void CKeymapHandling::UnloadKeymaps () private
References m_inputHandlers, m_inputProvider, m_keymaps, and KODI::JOYSTICK::IInputProvider::UnregisterInputHandler().
Referenced by LoadKeymaps(), and ~CKeymapHandling().
UnregisterInputProvider()
void KODI::KEYMAP::CKeymapHandling::UnregisterInputProvider () inline
Unregister the input provider.
Call this if the input provider is invalidated, such as if a user disconnects a controller. This prevents accessing the invalidated input provider when keymaps are unloaded upon destruction.
References m_inputProvider.
Member Data Documentation
m_environment
const IKeymapEnvironment* const KODI::KEYMAP::CKeymapHandling::m_environment private
Referenced by LoadKeymaps().
m_inputHandlers
std::vector<std::unique_ptr<JOYSTICK::IInputHandler> > KODI::KEYMAP::CKeymapHandling::m_inputHandlers private
Referenced by GetInputReceiver(), LoadKeymaps(), and UnloadKeymaps().
m_inputProvider
JOYSTICK::IInputProvider* KODI::KEYMAP::CKeymapHandling::m_inputProvider private
Referenced by LoadKeymaps(), UnloadKeymaps(), and UnregisterInputProvider().
m_keymaps
std::vector<std::unique_ptr<IKeymap> > KODI::KEYMAP::CKeymapHandling::m_keymaps private
Referenced by GetKeymap(), LoadKeymaps(), and UnloadKeymaps().
m_pPromiscuous
const bool KODI::KEYMAP::CKeymapHandling::m_pPromiscuous private
Referenced by LoadKeymaps().
The documentation for this class was generated from the following files:
KeymapHandling.h
KeymapHandling.cpp