Kodi Documentation: XBMCAddon::TupleBase Class Reference
XBMCAddon::TupleBase Class Reference
#include <Tuple.h>
Public Member Functions
int GetNumValuesSet () const
Protected Member Functions
TupleBase (int pnumValuesSet)
void nvs (int newSize)
Protected Attributes
int numValuesSet
Constructor & Destructor Documentation
TupleBase()
XBMCAddon::TupleBase::TupleBase (int pnumValuesSet) inline explicit protected
Member Function Documentation
GetNumValuesSet()
int XBMCAddon::TupleBase::GetNumValuesSet () const inline
References numValuesSet.
nvs()
void XBMCAddon::TupleBase::nvs (int newSize) inline protected
References numValuesSet.
Referenced by XBMCAddon::Tuple< T1, tuple_null_type, tuple_null_type, tuple_null_type, tuple_null_type >::first(), XBMCAddon::Tuple< T1, T2, T3, T4, tuple_null_type >::fourth(), XBMCAddon::Tuple< T1, T2, tuple_null_type, tuple_null_type, tuple_null_type >::second(), XBMCAddon::Tuple< T1, T2, T3, tuple_null_type, tuple_null_type >::third(), XBMCAddon::Tuple< T1, T2, tuple_null_type, tuple_null_type, tuple_null_type >::Tuple(), XBMCAddon::Tuple< T1, T2, T3, tuple_null_type, tuple_null_type >::Tuple(), and XBMCAddon::Tuple< T1, T2, T3, T4, tuple_null_type >::Tuple().
Member Data Documentation
numValuesSet
int XBMCAddon::TupleBase::numValuesSet protected
Referenced by GetNumValuesSet(), and nvs().
The documentation for this class was generated from the following file:
Tuple.h