Kodi Documentation: anonymous_namespace{GUIDialogVideoInfo.cpp} Namespace Reference
anonymous_namespace{GUIDialogVideoInfo.cpp} Namespace Reference
Classes
class CArtTypeChooser
class CAsyncGetArt
class CVideoPlayActionProcessor
Functions
void AddHardCodedAndExtendedArtTypes (std::vector< std::string > &artTypes, const CVideoInfoTag &tag)
void AddCurrentArtTypes (std::vector< std::string > &artTypes, const CVideoInfoTag &tag, CVideoDatabase &db)
void AddMediaTypeArtTypes (std::vector< std::string > &artTypes, const CVideoInfoTag &tag, CVideoDatabase &db)
void AddAvailableArtTypes (std::vector< std::string > &artTypes, const CVideoInfoTag &tag, CVideoDatabase &db)
std::vector< std::string > GetArtTypesList (const CVideoInfoTag &tag)
Function Documentation
AddAvailableArtTypes()
void anonymous_namespace{GUIDialogVideoInfo.cpp}::AddAvailableArtTypes (std::vector< std::string > & artTypes, const CVideoInfoTag & tag, CVideoDatabase & db) private
References CVideoDatabase::GetAvailableArtTypesForItem().
Referenced by GetArtTypesList().
AddCurrentArtTypes()
void anonymous_namespace{GUIDialogVideoInfo.cpp}::AddCurrentArtTypes (std::vector< std::string > & artTypes, const CVideoInfoTag & tag, CVideoDatabase & db) private
References CVideoDatabase::GetArtForAsset(), CVideoDatabase::GetArtForItem(), and NONE.
Referenced by GetArtTypesList().
AddHardCodedAndExtendedArtTypes()
void anonymous_namespace{GUIDialogVideoInfo.cpp}::AddHardCodedAndExtendedArtTypes (std::vector< std::string > & artTypes, const CVideoInfoTag & tag) private
References CVideoThumbLoader::GetArtTypes().
Referenced by GetArtTypesList().
AddMediaTypeArtTypes()
void anonymous_namespace{GUIDialogVideoInfo.cpp}::AddMediaTypeArtTypes (std::vector< std::string > & artTypes, const CVideoInfoTag & tag, CVideoDatabase & db) private
References CVideoDatabase::GetArtTypes().
Referenced by GetArtTypesList().
GetArtTypesList()
std::vector< std::string > anonymous_namespace{GUIDialogVideoInfo.cpp}::GetArtTypesList (const CVideoInfoTag & tag) private
References AddAvailableArtTypes(), AddCurrentArtTypes(), AddHardCodedAndExtendedArtTypes(), AddMediaTypeArtTypes(), CDatabase::Close(), and CVideoDatabase::Open().
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType().