Kodi Documentation: CGUIMediaWindow Class Reference
CGUIMediaWindow Class Reference
#include <GUIMediaWindow.h>
Classes
class CUpdateGuard
Public Member Functions
CGUIMediaWindow (int id, const char *xmlFile)
~CGUIMediaWindow (void) override
bool OnAction (const CAction &action) override
bool OnBack (int actionID) override
bool OnMessage (CGUIMessage &message) override
void OnWindowLoaded () override
void OnWindowUnload () override
void OnInitWindow () override
Called on window open.
bool IsMediaWindow () const override
int GetViewContainerID () const override
int GetViewCount () const override
bool HasListItems () const override
CFileItemPtr GetCurrentListItem (int offset=0) override
virtual bool CanFilterAdvanced ()
virtual bool IsFiltered ()
virtual bool IsSameStartFolder (const std::string &dir)
virtual std::string GetRootPath () const
const CFileItemList & CurrentDirectory () const
const CGUIViewState * GetViewState () const
virtual bool UseFileDirectories ()
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
bool OnAction (const CAction &action) override
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool OnMessage (CGUIMessage &message) override
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsDialog () const
virtual bool IsDialogRunning () const
virtual bool IsModalDialog () const
virtual bool IsSoundEnabled () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
virtual void OnDeinitWindow (int nextWindowID)
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
CGUIControl * GetFirstFocusableControl (int id) override
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
virtual void SetupShares ()
virtual bool GoParentFolder ()
Go one directory up on list items.
virtual bool OnClick (int iItem, const std::string &player="")
On click.
virtual bool OnSelect (int item)
virtual bool OnPopupMenu (int iItem)
virtual void GetContextButtons (int itemNumber, CContextButtons &buttons)
virtual bool OnContextButton (int itemNumber, CONTEXT_BUTTON button)
virtual bool OnAddMediaSource ()
virtual void FormatItemLabels (CFileItemList &items, const LABEL_MASKS &labelMasks)
Formats item labels.
virtual void UpdateButtons ()
Updates the states.
void SaveControlStates () override
void RestoreControlStates () override
virtual bool GetDirectory (const std::string &strDirectory, CFileItemList &items)
Overwrite to fill fileitems from a source.
virtual bool Update (const std::string &strDirectory, bool updateFilterPath=true)
Retrieves the items from the given path and updates the list.
virtual bool Refresh (bool clearCache=false)
Refreshes the current list by retrieving the lists's path.
virtual void FormatAndSort (CFileItemList &items)
Format and sort file items.
virtual void OnPrepareFileItems (CFileItemList &items)
On prepare file items.
virtual void OnCacheFileItems (CFileItemList &items)
On cache file items.
virtual void GetGroupedItems (CFileItemList &items)
void ClearFileItems ()
virtual void SortItems (CFileItemList &items)
Sort file items.
virtual bool CheckFilterAdvanced (CFileItemList &items) const
Check if the given list can be advance filtered or not.
virtual bool CanContainFilter (const std::string &strDirectory) const
Check if the given path can contain a "filter" parameter.
virtual void UpdateFilterPath (const std::string &strDirector, const CFileItemList &items, bool updateFilterPath)
virtual bool Filter (bool advanced=true)
void OnFilterItems (const std::string &filter)
virtual bool GetFilteredItems (const std::string &filter, CFileItemList &items)
virtual bool GetAdvanceFilteredItems (CFileItemList &items)
virtual bool HaveDiscOrConnection (const std::string &strPath, int iDriveType)
Check disc or connection present.
void ShowShareErrorMessage (CFileItem *pItem) const
Shows a standard error message for a given pItem.
void SaveSelectedItemInHistory ()
void RestoreSelectedItemFromHistory ()
void GetDirectoryHistoryString (const CFileItem *pItem, std::string &strHistoryString) const
Get history string for given file item.
void SetHistoryForPath (const std::string &strDirectory)
Set history for path.
virtual void LoadPlayList (const std::string &strFileName)
virtual bool OnPlayMedia (int iItem, const std::string &player="")
On media play.
virtual bool OnPlayAndQueueMedia (const CFileItemPtr &item, const std::string &player="")
On play and media queue.
void UpdateFileList ()
Update file list.
virtual void OnDeleteItem (int iItem)
void OnRenameItem (int iItem)
bool WaitForNetwork () const
bool GetDirectoryItems (CURL &url, CFileItemList &items, bool useDir)
bool WaitGetDirectoryItems (CGetDirectoryItems &items)
void CancelUpdateItems ()
virtual std::string GetStartFolder (const std::string &url)
Translate the folder to start in from the given quick path.
bool ProcessRenderLoop (bool renderOnly)
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void SetDefaults ()
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Static Protected Member Functions
static std::string RemoveParameterFromPath (const std::string &strDirectory, const std::string &strParameter)
Utility method to remove the given parameter from a path/URL.
Protected Attributes
XFILE::CVirtualDirectory m_rootDir
CGUIViewControl m_viewControl
CFileItemList * m_vecItems
CFileItemList * m_unfilteredItems
items prior to filtering using FilterItems()
CDirectoryHistory m_history
std::unique_ptr< CGUIViewState > m_guiState
std::atomic_bool m_vecItemsUpdating = {false}
CEvent m_updateEvent
std::atomic_bool m_updateAborted = {false}
std::atomic_bool m_updateJobActive = {false}
int m_iLastControl
std::string m_startDirectory
KODI::PLAYLIST::CSmartPlaylist m_filter
bool m_canFilterAdvanced
std::string m_strFilterPath
Contains the path used for filtering (including any active filter)
bool m_backgroundLoad = false
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIMediaWindow()
CGUIMediaWindow::CGUIMediaWindow (int id, const char * xmlFile)
References CGUIControl::GetID(), CGUIViewState::GetViewState(), CGUIWindow::KEEP_IN_MEMORY, m_canFilterAdvanced, m_guiState, m_iLastControl, CGUIWindow::m_loadType, m_unfilteredItems, m_vecItems, and CFileItem::SetPath().
~CGUIMediaWindow()
CGUIMediaWindow::~CGUIMediaWindow (void) override
References m_unfilteredItems, and m_vecItems.
Member Function Documentation
CancelUpdateItems()
void CGUIMediaWindow::CancelUpdateItems () protected
References XFILE::CVirtualDirectory::CancelDirectory(), CLog::Log(), LOGERROR, m_rootDir, m_updateAborted, m_updateEvent, m_updateJobActive, and CEvent::Wait().
Referenced by CGUIWindowMusicPlayList::OnBack(), OnBack(), and OnMessage().
CanContainFilter()
virtual bool CGUIMediaWindow::CanContainFilter (const std::string & strDirectory) const inline protected virtual
Check if the given path can contain a "filter" parameter.
Parameters
strDirectory Path to check
Returns
true if the given path can contain a "filter" parameter otherwise false
Reimplemented in CGUIWindowMusicBase, and CGUIWindowVideoBase.
Referenced by GetDirectoryHistoryString(), Update(), and UpdateFilterPath().
CanFilterAdvanced()
virtual bool CGUIMediaWindow::CanFilterAdvanced () inline virtual
References m_canFilterAdvanced.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool().
CheckFilterAdvanced()
virtual bool CGUIMediaWindow::CheckFilterAdvanced (CFileItemList & items) const inline protected virtual
Check if the given list can be advance filtered or not.
Parameters
items List of items to check
Returns
true if the list can be advance filtered otherwise false
Reimplemented in CGUIWindowMusicBase, and CGUIWindowVideoBase.
Referenced by Update().
ClearFileItems()
void CGUIMediaWindow::ClearFileItems () protected
References CFileItemList::Clear(), CGUIViewControl::Clear(), m_unfilteredItems, m_vecItems, and m_viewControl.
Referenced by ADDON::CGUIAddonWindow::ClearList(), CGUIWindowMusicPlayList::ClearPlayList(), CGUIWindowVideoPlaylist::ClearPlayList(), and OnMessage().
CurrentDirectory()
const CFileItemList & CGUIMediaWindow::CurrentDirectory () const
References m_vecItems.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), and PVR::CPVRRefreshTimelineItemsThread::Process().
Filter()
bool CGUIMediaWindow::Filter (bool advanced = true) protected virtual
References CVariant::asString(), CONTROL_BTN_FILTER, CGUIControlLookup::GetControl(), CGUIControl::GetControlType(), CGUIControl::GetID(), CGUIMessage::GetLabel(), CGUIWindow::GetProperty(), GUI_MSG_ITEM_SELECTED, CGUIControl::GUICONTROL_EDIT, m_canFilterAdvanced, m_filter, m_strFilterPath, OnFilterItems(), OnMessage(), CGUIWindow::SetProperty(), CGUIDialogMediaFilter::ShowAndEditMediaFilter(), CGUIKeyboardFactory::ShowAndGetFilter(), and UpdateButtons().
Referenced by OnAction(), and OnMessage().
FormatAndSort()
void CGUIMediaWindow::FormatAndSort (CFileItemList & items) protected virtual
Format and sort file items.
Prepares and adds the fileitems to list/thumb panel
Reimplemented in PVR::CGUIWindowPVRGuideBase.
References FormatItemLabels(), CGUIControl::GetID(), CGUIViewState::GetViewState(), and CFileItemList::Sort().
Referenced by CGUIWindowVideoNav::ApplyWatchedFilter(), OnFilterItems(), CGUIWindowAddonBrowser::OnMessage(), and UpdateFileList().
FormatItemLabels()
void CGUIMediaWindow::FormatItemLabels (CFileItemList & items, const LABEL_MASKS & labelMasks) protected virtual
Formats item labels.
This is based on the formatting provided by guiViewState.
References CFileItemList::ClearSortState(), CLabelFormatter::FormatLabels(), CFileItemList::GetSortMethod(), LABEL_MASKS::m_strLabel2File, LABEL_MASKS::m_strLabel2Folder, LABEL_MASKS::m_strLabelFile, LABEL_MASKS::m_strLabelFolder, CFileItemList::Size(), and SortByLabel.
Referenced by CGUIWindowMusicPlaylistEditor::AppendToPlaylist(), and FormatAndSort().
GetAdvanceFilteredItems()
bool CGUIMediaWindow::GetAdvanceFilteredItems (CFileItemList & items) protected virtual
References CFileItemList::Add(), CFileItemList::Append(), CFileItemList::ClearItems(), CFileItemList::Get(), XFILE::CSmartPlaylistDirectory::GetDirectory(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CURL::GetWithoutOptions(), CURL::HasOption(), CGUIListItem::HasProperty(), KODI::PLAYLIST::CSmartPlaylist::IsEmpty(), CLog::Log(), LOGWARNING, m_filter, m_strFilterPath, PROPERTY_PATH_DB, CFileItemList::Remove(), CFileItem::SetPath(), CGUIListItem::SetProperty(), and CFileItemList::Size().
Referenced by GetFilteredItems().
GetContextButtons()
virtual void CGUIMediaWindow::GetContextButtons (int itemNumber, CContextButtons & buttons) inline protected virtual
Reimplemented in ADDON::CGUIAddonWindow, CGUIWindowEventLog, KODI::GAME::CGUIWindowGames, CGUIWindowMusicBase, CGUIWindowMusicNav, CGUIWindowMusicPlayList, CGUIWindowPictures, CGUIWindowPrograms, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, CGUIWindowVideoBase, CGUIWindowVideoNav, and CGUIWindowVideoPlaylist.
Referenced by KODI::GAME::CGUIWindowGames::GetContextButtons(), XBMCAddon::xbmcgui::WindowXMLInterceptor::GetContextButtons(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowPictures::GetContextButtons(), CGUIWindowPrograms::GetContextButtons(), PVR::CGUIWindowPVRChannelsBase::GetContextButtons(), PVR::CGUIWindowPVRGuideBase::GetContextButtons(), PVR::CGUIWindowPVRRecordingsBase::GetContextButtons(), PVR::CGUIWindowPVRSearchBase::GetContextButtons(), CGUIWindowVideoBase::GetContextButtons(), and OnPopupMenu().
GetCurrentListItem()
CFileItemPtr CGUIMediaWindow::GetCurrentListItem (int offset = 0) override virtual
Reimplemented from CGUIWindow.
Reimplemented in PVR::CGUIWindowPVRGuideBase.
References CFileItemList::Get(), CGUIViewControl::GetSelectedItem(), m_vecItems, m_viewControl, and CFileItemList::Size().
Referenced by CGUIWindowMusicPlaylistEditor::OnSourcesContext().
GetDirectory()
bool CGUIMediaWindow::GetDirectory (const std::string & strDirectory, CFileItemList & items) protected virtual
Overwrite to fill fileitems from a source.
Parameters
[in] strDirectory Path to read
[out] items Fill with items specified in strDirectory
Returns
false if given directory not present
Todo:
Do we want to limit the directories we apply the video ones to?
Reimplemented in CGUIWindowAddonBrowser, CGUIWindowEventLog, KODI::GAME::CGUIWindowGames, CGUIWindowMusicBase, CGUIWindowMusicNav, CGUIWindowMusicPlaylistEditor, CGUIWindowPictures, PVR::CGUIWindowPVRGuideBase, CGUIWindowVideoBase, and CGUIWindowVideoNav.
References CFileItemList::AddFront(), CFileItemList::Assign(), CFileItemList::CacheToDiscIfSlow(), end(), CUtil::ExcludeFileOrFolder(), CServiceBroker::GetAddonMgr(), GetDirectoryItems(), CURL::GetHostName(), CGUIControl::GetID(), CDirectoryHistory::GetParentPath(), CFileItem::GetPath(), CFileItemList::GetReplaceListing(), GetRootPath(), CServiceBroker::GetSettingsComponent(), CGUIViewState::GetViewState(), CURL::IsProtocol(), CFileItemList::Load(), CLog::Log(), LOGDEBUG, m_canFilterAdvanced, m_filter, m_guiState, m_history, m_vecItems, CFileItemList::Remove(), CDirectoryHistory::RemoveParentPath(), KODI::PLAYLIST::CSmartPlaylist::Reset(), CFileItemList::Save(), CGUIWindow::SetProperty(), SetupShares(), CFileItemList::Size(), ADDON::CAddonMgr::UpdateLastUsed(), UseFileDirectories(), WINDOW_MUSIC_NAV, WINDOW_PICTURES, and WINDOW_VIDEO_NAV.
Referenced by CGUIWindowAddonBrowser::GetDirectory(), CGUIWindowEventLog::GetDirectory(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowPictures::GetDirectory(), CGUIWindowVideoBase::GetDirectory(), and Update().
GetDirectoryHistoryString()
void CGUIMediaWindow::GetDirectoryHistoryString (const CFileItem * pItem, std::string & strHistoryString) const protected
Get history string for given file item.
Note
Override the function to change the default behavior on how a selected item history should look like
References CanContainFilter(), CFileItem::GetEndOffset(), CGUIListItem::GetLabel(), CFileItem::GetPath(), CFileItem::GetStartOffset(), CFileItem::m_bIsShareOrDrive, CFileItem::m_iDriveType, RemoveParameterFromPath(), URIUtils::RemoveSlashAtEnd(), CMediaSource::SOURCE_TYPE_OPTICAL_DISC, and STARTOFFSET_RESUME.
Referenced by RestoreSelectedItemFromHistory(), CGUIWindowMusicPlayList::SavePlayList(), SaveSelectedItemInHistory(), and SetHistoryForPath().
GetDirectoryItems()
bool CGUIMediaWindow::GetDirectoryItems (CURL & url, CFileItemList & items, bool useDir) protected
References CServiceBroker::GetAppMessenger(), XFILE::CVirtualDirectory::GetDirectory(), XFILE::CVirtualDirectory::GetDirImpl(), m_backgroundLoad, m_rootDir, m_updateJobActive, XFILE::CVirtualDirectory::ReleaseDirImpl(), and WaitGetDirectoryItems().
Referenced by GetDirectory(), and SetHistoryForPath().
GetFilteredItems()
bool CGUIMediaWindow::GetFilteredItems (const std::string & filter, CFileItemList & items) protected virtual
Todo:
Need to update this to get all labels, ideally out of the displayed info (ie from m_layout and m_focusedLayout) though that isn't practical. Perhaps a better idea would be to just grab the info that we should filter on based on where we are in the library tree. Another idea is tying the filter string to the current level of the tree, so that going deeper disables the filter, but it's re-enabled on the way back out.
Reimplemented in PVR::CGUIWindowPVRRecordingsBase, and CGUIWindowVideoNav.
References CFileItemList::Add(), CFileItemList::Append(), CFileItemList::ClearItems(), CFileItemList::Get(), GetAdvanceFilteredItems(), CFileItemList::GetObjectCount(), CFileItem::GetPath(), m_canFilterAdvanced, and CFileItemList::Size().
Referenced by PVR::CGUIWindowPVRRecordingsBase::GetFilteredItems(), CGUIWindowVideoNav::GetFilteredItems(), and OnFilterItems().
GetFirstFocusableControl()
CGUIControl * CGUIMediaWindow::GetFirstFocusableControl (int id) override protected virtual
Reimplemented from CGUIControlGroup.
References CGUIViewControl::GetCurrentControl(), CGUIControlGroup::GetFirstFocusableControl(), CGUIViewControl::HasControl(), and m_viewControl.
GetGroupedItems()
virtual void CGUIMediaWindow::GetGroupedItems (CFileItemList & items) inline protected virtual
Reimplemented in CGUIWindowVideoBase.
Referenced by CGUIWindowVideoBase::GetGroupedItems(), and OnFilterItems().
GetRootPath()
virtual std::string CGUIMediaWindow::GetRootPath () const inline virtual
Reimplemented in CGUIWindowAddonBrowser, CGUIWindowEventLog, CGUIWindowFavourites, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRTVGuide, PVR::CGUIWindowPVRRadioGuide, PVR::CGUIWindowPVRTVProviders, PVR::CGUIWindowPVRRadioProviders, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRTVSearch, PVR::CGUIWindowPVRRadioSearch, PVR::CGUIWindowPVRTVTimerRules, PVR::CGUIWindowPVRRadioTimerRules, PVR::CGUIWindowPVRTVTimers, and PVR::CGUIWindowPVRRadioTimers.
Referenced by GetDirectory(), PVR::CGUIWindowPVRChannelsBase::GetRootPath(), GoParentFolder(), OnBack(), OnMessage(), and Update().
GetStartFolder()
std::string CGUIMediaWindow::GetStartFolder (const std::string & url) protected virtual
Translate the folder to start in from the given quick path.
Parameters
url the folder the user wants
Returns
the resulting path
Todo:
This ifdef block probably belongs somewhere else. Move it to a better place!
Reimplemented in CGUIWindowAddonBrowser, KODI::GAME::CGUIWindowGames, CGUIWindowMusicBase, CGUIWindowMusicPlaylistEditor, CGUIWindowPictures, CGUIWindowPrograms, PVR::CGUIWindowPVRTVSearch, PVR::CGUIWindowPVRRadioSearch, CGUIWindowVideoBase, CGUIWindowVideoNav, and CGUIWindowMusicNav.
References URIUtils::RemoveExtension(), and URIUtils::Split().
Referenced by CGUIWindowAddonBrowser::GetStartFolder(), KODI::GAME::CGUIWindowGames::GetStartFolder(), CGUIWindowMusicBase::GetStartFolder(), CGUIWindowPictures::GetStartFolder(), CGUIWindowPrograms::GetStartFolder(), CGUIWindowVideoBase::GetStartFolder(), IsSameStartFolder(), and OnMessage().
GetViewContainerID()
int CGUIMediaWindow::GetViewContainerID () const inline override virtual
Reimplemented from CGUIWindow.
References CGUIViewControl::GetCurrentControl(), and m_viewControl.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), and KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel().
GetViewCount()
int CGUIMediaWindow::GetViewCount () const inline override virtual
Reimplemented from CGUIWindow.
References CGUIViewControl::GetViewModeCount(), and m_viewControl.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel().
GetViewState()
const CGUIViewState * CGUIMediaWindow::GetViewState () const
References m_guiState.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), and FAVOURITES_UTILS::ShouldEnableMoveItems().
GoParentFolder()
bool CGUIMediaWindow::GoParentFolder () protected virtual
Go one directory up on list items.
The function goes up one level in the directory tree
Reimplemented in CGUIWindowMusicPlayList.
References g_localizeStrings, CLocalizeStrings::Get(), CDirectoryHistory::GetParentPath(), CFileItem::GetPath(), GetRootPath(), GoParentFolder(), CURL::HasOption(), CGUIDialogKaiToast::Info, KODI::PLAYLIST::CSmartPlaylist::IsEmpty(), CFileItem::IsVirtualDirectoryRoot(), m_filter, m_history, m_strFilterPath, m_unfilteredItems, m_vecItems, URIUtils::PathEquals(), CGUIDialogKaiToast::QueueNotification(), Refresh(), CDirectoryHistory::RemoveParentPath(), CFileItemList::Size(), and Update.
Referenced by PVR::CGUIWindowPVRSearchBase::ExecuteSearch(), GoParentFolder(), PVR::CGUIWindowPVRProvidersBase::OnAction(), PVR::CGUIWindowPVRRecordingsBase::OnAction(), PVR::CGUIWindowPVRSearchBase::OnAction(), PVR::CGUIWindowPVRTimersBase::OnAction(), OnAction(), OnBack(), OnClick(), PVR::CGUIWindowPVRRecordingsBase::Update(), PVR::CGUIWindowPVRSearchBase::Update(), and PVR::CGUIWindowPVRTimersBase::Update().
HasListItems()
bool CGUIMediaWindow::HasListItems () const inline override virtual
Reimplemented from CGUIWindow.
HaveDiscOrConnection()
bool CGUIMediaWindow::HaveDiscOrConnection (const std::string & strPath, int iDriveType) protected virtual
Check disc or connection present.
Checks if there is a disc in the dvd drive and whether the network is connected or not.
Todo:
Handle not connected to a remote share
References CServiceBroker::GetMediaManager(), CServiceBroker::GetNetwork(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), CMediaSource::SOURCE_TYPE_OPTICAL_DISC, and CMediaSource::SOURCE_TYPE_REMOTE.
Referenced by OnClick().
IsFiltered()
bool CGUIMediaWindow::IsFiltered () virtual
References CGUIWindow::GetProperty(), KODI::PLAYLIST::CSmartPlaylist::IsEmpty(), m_canFilterAdvanced, and m_filter.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), and OnCacheFileItems().
IsMediaWindow()
bool CGUIMediaWindow::IsMediaWindow () const inline override virtual
Reimplemented from CGUIWindow.
Reimplemented in XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >.
IsSameStartFolder()
bool CGUIMediaWindow::IsSameStartFolder (const std::string & dir) virtual
References CFileItem::GetPath(), GetStartFolder(), m_vecItems, and URIUtils::PathHasParent().
Load()
bool CGUIMediaWindow::Load (TiXmlElement * pRootElement) override protected virtual
Loads the window from the given XML element.
Parameters
pRootElement the XML element
Returns
true if the window is loaded from the given XML otherwise false.
Reimplemented from CGUIWindow.
References CGUIViewControl::AddView(), CONTROL_BTNVIEWASICONS, CGUIControlLookup::GetControl(), CGUIControl::GetID(), CGUIControl::IsContainer(), CGUIWindow::Load(), m_viewControl, CGUIViewControl::Reset(), CGUIViewControl::SetParentWindow(), and CGUIViewControl::SetViewControlID().
LoadPlayList()
virtual void CGUIMediaWindow::LoadPlayList (const std::string & strFileName) inline protected virtual
Reimplemented in CGUIWindowVideoBase, CGUIWindowMusicBase, and CGUIWindowPictures.
OnAction()
bool CGUIMediaWindow::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControlGroup.
Reimplemented in CGUIWindowFavourites, XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, CGUIWindowMusicBase, CGUIWindowMusicNav, CGUIWindowMusicPlayList, CGUIWindowMusicPlaylistEditor, PVR::CGUIWindowPVRBase, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRProvidersBase, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, PVR::CGUIWindowPVRTimersBase, CGUIWindowVideoBase, CGUIWindowVideoNav, and CGUIWindowVideoPlaylist.
References ACTION_BACKSPACE, ACTION_FILTER, ACTION_FILTER_CLEAR, ACTION_FILTER_SMS2, ACTION_FILTER_SMS9, ACTION_PARENT_DIR, Filter(), CGUIControl::GetID(), GoParentFolder(), GUI_MSG_FILTER_ITEMS, GUI_MSG_NOTIFY_ALL, CGUIWindow::OnAction(), OnMessage(), and CGUIMessage::SetStringParam().
Referenced by CGUIWindowFavourites::OnAction(), CGUIWindowMusicBase::OnAction(), PVR::CGUIWindowPVRBase::OnAction(), and CGUIWindowVideoBase::OnAction().
OnAddMediaSource()
virtual bool CGUIMediaWindow::OnAddMediaSource () inline protected virtual
Reimplemented in KODI::GAME::CGUIWindowGames, CGUIWindowMusicBase, CGUIWindowPictures, CGUIWindowPrograms, and CGUIWindowVideoNav.
Referenced by OnClick().
OnBack()
bool CGUIMediaWindow::OnBack (int actionID) override virtual
Reimplemented from CGUIWindow.
Reimplemented in XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, CGUIWindowMusicBase, CGUIWindowMusicPlayList, CGUIWindowMusicPlaylistEditor, and CGUIWindowVideoPlaylist.
References ACTION_NAV_BACK, CancelUpdateItems(), CFileItem::GetPath(), GetRootPath(), GoParentFolder(), CURL::HasOption(), CFileItem::IsVirtualDirectoryRoot(), m_canFilterAdvanced, m_startDirectory, m_strFilterPath, m_vecItems, CGUIControl::OnBack(), and URIUtils::PathEquals().
OnCacheFileItems()
void CGUIMediaWindow::OnCacheFileItems (CFileItemList & items) protected virtual
On cache file items.
This function will be called by Update() before any additional formatting, filtering or sorting is applied.
Note
Override this function to define a custom caching behaviour.
References CFileItemList::CacheToDiscAlways(), CGUIControl::GetID(), IsFiltered(), and CFileItemList::Save().
Referenced by Update().
OnClick()
bool CGUIMediaWindow::OnClick (int iItem, const std::string & player = "") protected virtual
On click.
With this function you can react on a users click in the list/thumb panel. It returns true, if the click is handled. This function calls OnPlayMedia()
Reimplemented in CGUIWindowAddonBrowser, KODI::GAME::CGUIWindowGames, CGUIWindowMusicNav, CGUIWindowMusicPlaylistEditor, CGUIWindowPictures, and CGUIWindowVideoNav.
References CGUIWindowManager::ActivateWindow(), CDirectoryHistory::AddPath(), CFileItemList::AlwaysCache(), ADDON::CPluginSource::AUDIO, XFILE::CFileDirectoryFactory::Create(), CGUIDialogSmartPlaylistEditor::EditPlaylist(), EFILEFOLDER_MASK_ONCLICK, CScriptInvocationManager::ExecuteAsync(), CFileUtils::Exists(), g_partyModeManager, g_passwordManager, CFileItemList::Get(), CServiceBroker::GetAddonMgr(), URIUtils::GetFileName(), CServiceBroker::GetGUI(), CURL::GetHostName(), CGUIControl::GetID(), CScriptInvocationManager::GetInstance(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), CGUIViewState::GetViewState(), CGUIComponent::GetWindowManager(), GoParentFolder(), HaveDiscOrConnection(), KODI::PLAYLIST::CSmartPlaylist::IsEmpty(), CPartyModeManager::IsEnabled(), CGUIPassword::IsItemUnlocked(), CGUIPassword::IsMasterLockUnlocked(), CFileItem::IsPlugin(), CGUIPassword::IsProfileLockUnlocked(), LOCK_MODE_EVERYONE, CLog::Log(), LOGDEBUG, LOGWARNING, m_canFilterAdvanced, m_filter, m_guiState, m_history, m_strFilterPath, m_vecItems, m_vecItemsUpdating, CGUIDialogSmartPlaylistEditor::NewPlaylist(), OnAddMediaSource(), OnPlayAndQueueMedia(), OnPlayMedia(), URIUtils::PathEquals(), Refresh(), CFileItemList::RemoveDiscCache(), CDirectoryHistory::RemoveParentPath(), XFILE::CPluginDirectory::RunScriptWithParams(), SaveSelectedItemInHistory(), ShowShareErrorMessage(), CFileItemList::Size(), CXBMCApp::StartActivity(), STARTOFFSET_RESUME, Update, ADDON::CAddonMgr::UpdateLastUsed(), and WINDOW_MUSIC_PLAYLIST_EDITOR.
Referenced by CGUIWindowAddonBrowser::OnClick(), KODI::GAME::CGUIWindowGames::OnClick(), XBMCAddon::xbmcgui::WindowXMLInterceptor::OnClick(), CGUIWindowMusicNav::OnClick(), CGUIWindowMusicPlaylistEditor::OnClick(), CGUIWindowPictures::OnClick(), CGUIWindowVideoNav::OnClick(), CGUIWindowVideoBase::OnRestartItem(), OnSelect(), and CGUIWindowMusicBase::PlayItem().
OnContextButton()
virtual bool CGUIMediaWindow::OnContextButton (int itemNumber, CONTEXT_BUTTON button) inline protected virtual
Reimplemented in ADDON::CGUIAddonWindow, CGUIWindowEventLog, KODI::GAME::CGUIWindowGames, CGUIWindowMusicBase, CGUIWindowMusicNav, CGUIWindowMusicPlayList, CGUIWindowPictures, CGUIWindowPrograms, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, CGUIWindowVideoBase, CGUIWindowVideoNav, and CGUIWindowVideoPlaylist.
Referenced by CGUIWindowEventLog::OnContextButton(), KODI::GAME::CGUIWindowGames::OnContextButton(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowPictures::OnContextButton(), CGUIWindowPrograms::OnContextButton(), PVR::CGUIWindowPVRChannelsBase::OnContextButton(), PVR::CGUIWindowPVRGuideBase::OnContextButton(), PVR::CGUIWindowPVRRecordingsBase::OnContextButton(), PVR::CGUIWindowPVRSearchBase::OnContextButton(), CGUIWindowVideoBase::OnContextButton(), and OnPopupMenu().
OnDeleteItem()
void CGUIMediaWindow::OnDeleteItem (int iItem) protected virtual
Reimplemented in CGUIWindowVideoBase.
References CFileUtils::DeleteItemWithConfirm(), g_passwordManager, CFileItemList::Get(), CServiceBroker::GetSettingsComponent(), CGUIPassword::IsMasterLockUnlocked(), KODI::PLAYLIST::IsPlayList(), LOCK_MODE_EVERYONE, m_vecItems, m_viewControl, Refresh(), CGUIViewControl::SetSelectedItem(), and CFileItemList::Size().
Referenced by KODI::GAME::CGUIWindowGames::OnClickMsg(), KODI::GAME::CGUIWindowGames::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowPictures::OnContextButton(), CGUIWindowMusicBase::OnMessage(), and CGUIWindowPictures::OnMessage().
OnFilterItems()
void CGUIMediaWindow::OnFilterItems (const std::string & filter) protected
References CFileItemList::AddFront(), CFileItemList::Append(), CVariant::asString(), CGUIViewControl::Clear(), CFileItemList::ClearItems(), CFileItemList::ClearSortState(), CFileItemList::Copy(), FormatAndSort(), CURL::Get(), CFileItemList::Get(), GetFilteredItems(), GetGroupedItems(), CURL::GetOption(), CDirectoryHistory::GetParentPath(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CGUIViewControl::GetSelectedItem(), CURL::HasOption(), CGUIListItem::HasProperty(), index(), CFileItemList::IsEmpty(), m_canFilterAdvanced, m_history, m_strFilterPath, m_unfilteredItems, m_vecItems, m_viewControl, PROPERTY_PATH_DB, CURL::RemoveOption(), CGUIViewControl::SetItems(), CURL::SetOption(), CGUIWindow::SetProperty(), CGUIViewControl::SetSelectedItem(), and CFileItemList::Size().
Referenced by Filter(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), OnMessage(), and Update().
OnInitWindow()
void CGUIMediaWindow::OnInitWindow (void) override virtual
Called on window open.
Restores the control state(s)
Sets initial visibility of controls
Queue WindowOpen animation
Set overlay state Override this function and do any window-specific initialisation such as filling control contents and setting control focus before calling the base method.
Reimplemented from CGUIWindow.
Reimplemented in CGUIWindowMusicBase, CGUIWindowPictures, PVR::CGUIWindowPVRBase, and PVR::CGUIWindowPVRGuideBase.
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CFileItem::GetPath(), CGUIComponent::GetWindowManager(), GUI_MSG_WINDOW_INIT, URIUtils::IsPlugin(), m_backgroundLoad, m_startDirectory, m_vecItems, CGUIWindow::OnInitWindow(), URIUtils::PathEquals(), PLUGIN_REFRESH_DELAY, Refresh(), SetHistoryForPath(), and WINDOW_INVALID.
Referenced by CGUIWindowMusicBase::OnInitWindow(), CGUIWindowPictures::OnInitWindow(), and PVR::CGUIWindowPVRBase::OnInitWindow().
OnMessage()
bool CGUIMediaWindow::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControlGroup.
Reimplemented in CGUIWindowAddonBrowser, CGUIWindowEventLog, CGUIWindowFavourites, KODI::GAME::CGUIWindowGames, XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, CGUIWindowMusicBase, CGUIWindowMusicNav, CGUIWindowMusicPlayList, CGUIWindowMusicPlaylistEditor, CGUIWindowPictures, CGUIWindowPrograms, PVR::CGUIWindowPVRBase, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRProvidersBase, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, PVR::CGUIWindowPVRTimersBase, CGUIWindowVideoBase, CGUIWindowVideoNav, and CGUIWindowVideoPlaylist.
References ACTION_CONTEXT_MENU, ACTION_MOUSE_LEFT_CLICK, ACTION_MOUSE_RIGHT_CLICK, ACTION_SELECT_ITEM, CVariant::asString(), CancelUpdateItems(), ClearFileItems(), CDirectoryHistory::ClearPathHistory(), CONTROL_BTN_FILTER, CONTROL_BTNSORTASC, CONTROL_BTNSORTBY, CONTROL_BTNVIEWASICONS, Filter(), CFileItemList::Get(), CGUIControlLookup::GetControl(), CGUIMessage::GetControlId(), CGUIControl::GetControlType(), CGUIViewControl::GetCurrentControl(), URIUtils::GetDirectory(), CGUIControlGroup::GetFocusedControlID(), CGUIControl::GetID(), CGUIMessage::GetItem(), CGUIMessage::GetMessage(), CGUIViewControl::GetNextViewMode(), CGUIMessage::GetNumStringParams(), CGUIMessage::GetParam1(), CGUIMessage::GetParam2(), CFileItem::GetPath(), CGUIWindow::GetProperty(), GetRootPath(), CGUIViewControl::GetSelectedItem(), CGUIMessage::GetSenderId(), GetStartFolder(), CGUIMessage::GetStringParam(), CGUIViewControl::GetViewModeByID(), CGUIViewControl::GetViewModeNumber(), GUI_MSG_CHANGE_SORT_DIRECTION, GUI_MSG_CHANGE_SORT_METHOD, GUI_MSG_CHANGE_VIEW_MODE, GUI_MSG_CLICKED, GUI_MSG_FILTER_ITEMS, GUI_MSG_FLAG_FORCE_UPDATE, GUI_MSG_FLAG_UPDATE_LIST, GUI_MSG_ITEM_SELECTED, GUI_MSG_NOTIFY_ALL, GUI_MSG_PLAYBACK_ENDED, GUI_MSG_PLAYBACK_STARTED, GUI_MSG_PLAYBACK_STOPPED, GUI_MSG_PLAYLIST_CHANGED, GUI_MSG_PLAYLISTPLAYER_CHANGED, GUI_MSG_PLAYLISTPLAYER_STARTED, GUI_MSG_PLAYLISTPLAYER_STOPPED, GUI_MSG_REFRESH_LIST, GUI_MSG_REFRESH_THUMBS, GUI_MSG_REMOVED_MEDIA, GUI_MSG_SETFOCUS, GUI_MSG_UPDATE, GUI_MSG_UPDATE_ITEM, GUI_MSG_UPDATE_PATH, GUI_MSG_UPDATE_SOURCES, GUI_MSG_WINDOW_DEINIT, GUI_MSG_WINDOW_INIT, GUI_MSG_WINDOW_RESET, CGUIControl::GUICONTROL_BUTTON, CGUIViewControl::HasControl(), XFILE::CMultiPathDirectory::HasPath(), CGUIWindow::IsActive(), XFILE::CVirtualDirectory::IsInSource(), CFileItem::IsMultiPath(), URIUtils::IsRemote(), CFileItem::IsRemovable(), CFileItem::IsSourcesPath(), CFileItem::IsVirtualDirectoryRoot(), CLog::Log(), LOGWARNING, m_canFilterAdvanced, m_filter, m_guiState, m_history, m_iLastControl, m_rootDir, m_startDirectory, m_strFilterPath, m_vecItems, m_vecItemsUpdating, m_viewControl, OnFilterItems(), CGUIWindow::OnMessage(), OnMessage(), OnPopupMenu(), OnSelect(), URIUtils::PathEquals(), PLUGIN_REFRESH_DELAY, Refresh(), CFileItemList::RemoveDiscCache(), CFileItemList::RemoveDiscCacheCRC(), KODI::PLAYLIST::CSmartPlaylist::Reset(), RestoreControlStates(), CGUIViewControl::SetFocused(), SetHistoryForPath(), CGUIWindow::SetInitialVisibility(), CFileItem::SetPath(), CGUIViewControl::SetSelectedItem(), CFileItemList::Size(), Update, UpdateButtons(), UpdateFileList(), CFileItemList::UpdateItem(), WaitForNetwork(), and WINDOW_INVALID.
Referenced by Filter(), OnAction(), CGUIWindowAddonBrowser::OnMessage(), ADDON::CGUIAddonWindow::OnMessage(), CGUIWindowEventLog::OnMessage(), CGUIWindowFavourites::OnMessage(), KODI::GAME::CGUIWindowGames::OnMessage(), XBMCAddon::xbmcgui::WindowXML::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIWindowPVRBase::OnMessage(), CGUIWindowVideoBase::OnMessage(), and OnMessage().
OnPlayAndQueueMedia()
bool CGUIMediaWindow::OnPlayAndQueueMedia (const CFileItemPtr & item, const std::string & player = "") protected virtual
On play and media queue.
Note
Override if you want to change the default behavior of what is done when the user clicks on a file in a "folder" with similar files.
This function is called by OnClick()
Reimplemented in CGUIWindowVideoBase.
References KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist(), KODI::PLAYLIST::CPlayList::FindOrder(), CFileItem::GetPath(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), KODI::MUSIC::IsAudioBook(), m_guiState, m_vecItems, KODI::PLAYLIST::CPlayListPlayer::Play(), playlist, KODI::PLAYLIST::CPlayListPlayer::Reset(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), and KODI::PLAYLIST::CPlayList::Swap().
Referenced by OnClick(), and CGUIWindowVideoBase::OnPlayAndQueueMedia().
OnPlayMedia()
bool CGUIMediaWindow::OnPlayMedia (int iItem, const std::string & player = "") protected virtual
On media play.
Note
Override if you want to change the default behavior, what is done when the user clicks on a file.
This function is called by OnClick()
Reimplemented in CGUIWindowPrograms, CGUIWindowMusicBase, CGUIWindowMusicPlayList, CGUIWindowPictures, CGUIWindowVideoBase, and CGUIWindowVideoPlaylist.
References g_application, CFileItemList::Get(), CServiceBroker::GetPlaylistPlayer(), KODI::NETWORK::IsInternetStream(), KODI::PLAYLIST::IsPlayList(), CLog::Log(), LOGDEBUG, m_guiState, m_vecItems, KODI::PLAYLIST::CPlayListPlayer::Reset(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), and STARTOFFSET_RESUME.
Referenced by OnClick(), CGUIWindowMusicBase::OnPlayMedia(), and CGUIWindowPictures::OnPlayMedia().
OnPopupMenu()
bool CGUIMediaWindow::OnPopupMenu (int iItem) protected virtual
Reimplemented in CGUIWindowMusicNav, PVR::CGUIWindowPVRRecordingsBase, and CGUIWindowVideoNav.
References CFileItemList::Get(), CContextMenuManager::GetAddonItems(), CServiceBroker::GetAppMessenger(), GetContextButtons(), CServiceBroker::GetContextMenuManager(), CContextMenuManager::GetItems(), CONTEXTMENU::LoopFrom(), m_backgroundLoad, m_vecItems, CContextMenuManager::MAIN, OnContextButton(), CGUIDialogContextMenu::Show(), CFileItemList::Size(), and TMSG_EXECUTE_BUILT_IN.
Referenced by PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), OnMessage(), CGUIWindowMusicNav::OnPopupMenu(), PVR::CGUIWindowPVRRecordingsBase::OnPopupMenu(), and CGUIWindowVideoNav::OnPopupMenu().
OnPrepareFileItems()
void CGUIMediaWindow::OnPrepareFileItems (CFileItemList & items) protected virtual
On prepare file items.
This function will be called by Update() before the labels of the fileitems are formatted.
Note
Override this function to set custom thumbs or load additional media info.
It's used to load tag info for music.
Reimplemented in CGUIWindowMusicBase, CGUIWindowMusicPlaylistEditor, CGUIWindowPictures, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, PVR::CGUIWindowPVRTimersBase, and CGUIWindowVideoPlaylist.
References CFileItemListModification::GetInstance(), and CFileItemListModification::Modify().
Referenced by CGUIWindowMusicBase::OnPrepareFileItems(), CGUIWindowPictures::OnPrepareFileItems(), PVR::CGUIWindowPVRRecordingsBase::OnPrepareFileItems(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), and Update().
OnRenameItem()
void CGUIMediaWindow::OnRenameItem (int iItem) protected
References g_passwordManager, CFileItemList::Get(), CServiceBroker::GetSettingsComponent(), CGUIPassword::IsMasterLockUnlocked(), LOCK_MODE_EVERYONE, m_vecItems, m_viewControl, Refresh(), CFileUtils::RenameFile(), CGUIViewControl::SetSelectedItem(), and CFileItemList::Size().
Referenced by KODI::GAME::CGUIWindowGames::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowPictures::OnContextButton(), and CGUIWindowVideoBase::OnContextButton().
OnSelect()
bool CGUIMediaWindow::OnSelect (int item) protected virtual
Reimplemented in CGUIWindowMusicBase, CGUIWindowVideoBase, CGUIWindowVideoPlaylist, CGUIWindowEventLog, and CGUIWindowFavourites.
References OnClick().
Referenced by OnMessage(), CGUIWindowMusicBase::OnSelect(), and CGUIWindowVideoBase::OnSelect().
OnWindowLoaded()
void CGUIMediaWindow::OnWindowLoaded () override virtual
Reimplemented from CGUIWindow.
Reimplemented in CGUIWindowMusicNav, and PVR::CGUIWindowPVRRecordingsBase.
References CONTROL_BTN_FILTER, GUI_MSG_SET_TYPE, CGUIEditControl::INPUT_TYPE_FILTER, CGUIWindow::OnWindowLoaded(), CGUIWindow::SendMessage(), and SetupShares().
OnWindowUnload()
void CGUIMediaWindow::OnWindowUnload () override virtual
Reimplemented from CGUIWindow.
References m_viewControl, CGUIWindow::OnWindowUnload(), and CGUIViewControl::Reset().
ProcessRenderLoop()
bool CGUIMediaWindow::ProcessRenderLoop (bool renderOnly) protected
References CServiceBroker::GetGUI(), and CGUIComponent::GetWindowManager().
Referenced by ADDON::CGUIAddonWindowDialog::Show_Internal(), and WaitGetDirectoryItems().
Refresh()
bool CGUIMediaWindow::Refresh (bool clearCache = false) protected virtual
Refreshes the current list by retrieving the lists's path.
Returns
true if the list was successfully refreshed otherwise false
See also
Update
GetDirectory
References CGUIControl::GetID(), CFileItem::GetPath(), m_vecItems, CFileItemList::RemoveDiscCache(), and Update.
Referenced by CGUIWindowMusicPlayList::ClearPlayList(), PVR::CGUIWindowPVRBase::DoRefresh(), PVR::CGUIWindowPVRSearchBase::ExecuteSearch(), GoParentFolder(), CGUIWindowMusicPlayList::MoveCurrentPlayListItem(), CGUIWindowVideoPlaylist::MoveCurrentPlayListItem(), CGUIWindowMusicPlayList::MoveItem(), CGUIWindowVideoPlaylist::MoveItem(), OnClick(), CGUIWindowAddonBrowser::OnClick(), CGUIWindowVideoNav::OnClick(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoBase::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), PVR::CGUIWindowPVRSearchBase::OnContextButtonClear(), PVR::CGUIWindowPVRChannelsBase::OnContextButtonManage(), OnDeleteItem(), CGUIWindowVideoBase::OnDeleteItem(), CGUIWindowEventLog::OnEventAdded(), CGUIWindowEventLog::OnEventRemoved(), OnInitWindow(), CGUIWindowAddonBrowser::OnMessage(), CGUIWindowEventLog::OnMessage(), CGUIWindowFavourites::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), PVR::CGUIWindowPVRBase::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), OnMessage(), OnRenameItem(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::RefreshContent(), PVR::CGUIWindowPVRGuideBase::RefreshView(), CGUIWindowMusicPlayList::RemovePlayListItem(), CGUIWindowVideoPlaylist::RemovePlayListItem(), CGUIWindowMusicPlayList::SavePlayList(), and CGUIWindowVideoBase::ShowInfoAndRefresh().
RemoveParameterFromPath()
std::string CGUIMediaWindow::RemoveParameterFromPath (const std::string & strDirectory, const std::string & strParameter) static protected
Utility method to remove the given parameter from a path/URL.
Parameters
strDirectory Path/URL from which to remove the given parameter
strParameter Parameter to remove from the given path/URL
Returns
Path/URL without the given parameter
References CURL::Get(), CURL::HasOption(), and CURL::RemoveOption().
Referenced by GetDirectoryHistoryString(), and Update().
RestoreControlStates()
void CGUIMediaWindow::RestoreControlStates () override protected virtual
Reimplemented from CGUIWindow.
References CGUIWindow::RestoreControlStates(), and RestoreSelectedItemFromHistory().
Referenced by OnMessage().
RestoreSelectedItemFromHistory()
void CGUIMediaWindow::RestoreSelectedItemFromHistory () protected
References CFileItemList::Get(), GetDirectoryHistoryString(), CFileItem::GetPath(), CDirectoryHistory::GetSelectedItem(), CDirectoryHistory::GetSelectedItemIndex(), m_history, m_vecItems, m_viewControl, CGUIViewControl::SetSelectedItem(), and CFileItemList::Size().
Referenced by RestoreControlStates(), and Update().
SaveControlStates()
void CGUIMediaWindow::SaveControlStates () override protected virtual
Reimplemented from CGUIWindow.
References CGUIWindow::SaveControlStates(), and SaveSelectedItemInHistory().
SaveSelectedItemInHistory()
void CGUIMediaWindow::SaveSelectedItemInHistory () protected
References CFileItemList::Get(), GetDirectoryHistoryString(), CFileItem::GetPath(), CGUIViewControl::GetSelectedItem(), m_history, m_vecItems, m_viewControl, and CDirectoryHistory::SetSelectedItem().
Referenced by OnClick(), CGUIWindowPictures::OnInitWindow(), SaveControlStates(), and Update().
SetHistoryForPath()
void CGUIMediaWindow::SetHistoryForPath (const std::string & strDirectory) protected
Set history for path.
Call this function to create a directory history for the path given by strDirectory.
References CDirectoryHistory::AddPathFront(), URIUtils::AddSlashAtEnd(), CDirectoryHistory::ClearPathHistory(), CURL::Get(), GetDirectoryHistoryString(), GetDirectoryItems(), URIUtils::GetParentPath(), URIUtils::IsVideoDb(), m_history, m_strFilterPath, URIUtils::PathEquals(), URIUtils::RemoveSlashAtEnd(), CURL::SetOptions(), CDirectoryHistory::SetSelectedItem(), SetupShares(), CFileItemList::Size(), and UseFileDirectories().
Referenced by OnInitWindow(), OnMessage(), and CGUIWindowVideoBase::OnSearchItemFound().
SetupShares()
void CGUIMediaWindow::SetupShares () protected virtual
Reimplemented in ADDON::CGUIAddonWindow, and KODI::GAME::CGUIWindowGames.
References CGUIViewState::GetExtensions(), CGUIControl::GetID(), CGUIViewState::GetSources(), CGUIViewState::GetViewState(), m_rootDir, XFILE::IDirectory::SetMask(), and XFILE::CVirtualDirectory::SetSources().
Referenced by GetDirectory(), CGUIWindowPictures::GetStartFolder(), CGUIWindowPrograms::GetStartFolder(), OnWindowLoaded(), SetHistoryForPath(), KODI::GAME::CGUIWindowGames::SetupShares(), and XBMCAddon::xbmcgui::WindowXMLInterceptor::SetupShares().
ShowShareErrorMessage()
void CGUIMediaWindow::ShowShareErrorMessage (CFileItem * pItem) const protected
Shows a standard error message for a given pItem.
References CURL::GetHostName(), CFileItem::GetPath(), CURL::IsProtocol(), URIUtils::IsRemote(), CFileItem::m_bIsShareOrDrive, CFileItem::m_iDriveType, KODI::MESSAGING::HELPERS::ShowOKDialogText(), and CMediaSource::SOURCE_TYPE_REMOTE.
Referenced by OnClick().
SortItems()
void CGUIMediaWindow::SortItems (CFileItemList & items) protected virtual
Sort file items.
This sorts file items based on the sort method and sort order provided by guiViewState.
References CVariant::asBoolean(), CVariant::asInteger(), CGUIControl::GetID(), CGUIListItem::GetProperty(), CServiceBroker::GetSettingsComponent(), CGUIViewState::GetViewState(), CGUIListItem::HasProperty(), PROPERTY_SORT_ASCENDING, PROPERTY_SORT_ORDER, CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CFileItemList::Sort(), SortAttributeIgnoreArticle, SortAttributeNone, SortDescription::sortAttributes, SortDescription::sortBy, SortByNone, SortByPlaylistOrder, SortByProgramCount, SortDescription::sortOrder, SortOrderAscending, and SortOrderDescending.
Update()
bool CGUIMediaWindow::Update (const std::string & strDirectory, bool updateFilterPath = true) protected virtual
Retrieves the items from the given path and updates the list.
Parameters
strDirectory The path to the directory to get the items from
updateFilterPath Whether to update the filter path in m_strFilterPath or not
Returns
true if the list was successfully updated otherwise false
See also
GetDirectory
m_vecItems
m_strFilterPath
Todo:
OnInitWindow calls Update() before window path has been set properly.
Reimplemented in CGUIWindowAddonBrowser, CGUIWindowFavourites, CGUIWindowMusicNav, CGUIWindowMusicPlayList, CGUIWindowMusicPlaylistEditor, CGUIWindowPictures, CGUIWindowPrograms, PVR::CGUIWindowPVRBase, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, PVR::CGUIWindowPVRTimersBase, CGUIWindowVideoBase, and CGUIWindowVideoNav.
References CFileItemList::Add(), CDirectoryHistory::AddPath(), CFileItemList::Assign(), CanContainFilter(), CheckFilterAdvanced(), CDirectoryHistory::ClearPathHistory(), URIUtils::CompareWithoutSlashAtEnd(), CFileItemList::FillInDefaultIcons(), g_localizeStrings, CLocalizeStrings::Get(), CFileItemList::GetContent(), GetDirectory(), CGUIControlGroup::GetFocusedControlID(), CGUIControl::GetID(), CGUIListItem::GetLabel(), CServiceBroker::GetMediaManager(), CFileItem::GetPath(), CGUIWindow::GetProperty(), CMediaManager::GetRemovableDrives(), GetRootPath(), CServiceBroker::GetSettingsComponent(), CUtil::GetTitleFromPath(), CFileItem::IsPath(), CLog::Log(), LOGERROR, m_canFilterAdvanced, m_filter, m_guiState, m_history, m_iLastControl, m_strFilterPath, m_unfilteredItems, m_vecItems, OnCacheFileItems(), OnFilterItems(), OnPrepareFileItems(), URIUtils::PathEquals(), RemoveParameterFromPath(), CDirectoryHistory::RemoveParentPath(), RestoreSelectedItemFromHistory(), SaveSelectedItemInHistory(), CFileItem::SetLabel(), KODI::PLAYLIST::CSmartPlaylist::SetType(), CFileItemList::Size(), SortSpecialOnBottom, SortSpecialOnTop, Update, UpdateButtons(), UpdateFilterPath(), WINDOW_FILES, WINDOW_GAMES, WINDOW_MUSIC_PLAYLIST_EDITOR, and WINDOW_PICTURES.
Referenced by CGUIWindowAddonBrowser::Update(), CGUIWindowFavourites::Update(), CGUIWindowMusicNav::Update(), CGUIWindowMusicPlayList::Update(), CGUIWindowMusicPlaylistEditor::Update(), CGUIWindowPictures::Update(), CGUIWindowPrograms::Update(), PVR::CGUIWindowPVRBase::Update(), CGUIWindowVideoBase::Update(), and XBMCAddon::xbmcgui::WindowXMLInterceptor::Update().
UpdateButtons()
void CGUIMediaWindow::UpdateButtons () protected virtual
Updates the states.
This updates the states (enable, disable, visible...) of the controls defined by this window.
Note
Override this function in a derived class to add new controls
Reimplemented in CGUIWindowAddonBrowser, CGUIWindowEventLog, CGUIWindowMusicBase, CGUIWindowMusicNav, CGUIWindowMusicPlayList, CGUIWindowMusicPlaylistEditor, CGUIWindowPictures, PVR::CGUIWindowPVRBase, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRProvidersBase, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, PVR::CGUIWindowPVRTimersBase, CGUIWindowVideoNav, and CGUIWindowVideoPlaylist.
References CONTROL_BTN_FILTER, CONTROL_BTNSORTASC, CONTROL_BTNSORTBY, CONTROL_DISABLE, CONTROL_ENABLE, CONTROL_LABELFILES, g_localizeStrings, CLocalizeStrings::Get(), CGUIControl::GetID(), CFileItemList::GetObjectCount(), CGUIWindow::GetProperty(), m_guiState, m_vecItems, m_viewControl, SET_CONTROL_LABEL, SET_CONTROL_LABEL2, SET_CONTROL_SELECTED, CGUIViewControl::SetCurrentView(), SortOrderAscending, and SortOrderNone.
Referenced by ADDON::CGUIAddonWindow::AddItem(), ADDON::CGUIAddonWindow::ClearList(), Filter(), OnMessage(), ADDON::CGUIAddonWindow::RemoveItem(), ADDON::CGUIAddonWindow::RemoveItem(), ADDON::CGUIAddonWindow::SetupShares(), Update(), CGUIWindowAddonBrowser::UpdateButtons(), CGUIWindowEventLog::UpdateButtons(), CGUIWindowMusicBase::UpdateButtons(), CGUIWindowPictures::UpdateButtons(), PVR::CGUIWindowPVRBase::UpdateButtons(), CGUIWindowVideoNav::UpdateButtons(), CGUIWindowVideoPlaylist::UpdateButtons(), and UpdateFileList().
UpdateFileList()
void CGUIMediaWindow::UpdateFileList () protected
Update file list.
Synchronize the fileitems with the playlistplayer also recreates the playlist of the playlistplayer based on the fileitems of the window
References KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist(), FormatAndSort(), CFileItemList::Get(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), CFileItem::GetPath(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), CGUIViewControl::GetSelectedItem(), CFileItem::GetStartOffset(), KODI::PLAYLIST::IsPlayList(), m_guiState, m_vecItems, m_viewControl, KODI::PLAYLIST::CPlayListPlayer::Reset(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentItemIdx(), CGUIViewControl::SetItems(), CGUIViewControl::SetSelectedItem(), CFileItemList::Size(), and UpdateButtons().
Referenced by OnMessage().
UpdateFilterPath()
void CGUIMediaWindow::UpdateFilterPath (const std::string & strDirector, const CFileItemList & items, bool updateFilterPath) protected virtual
References CVariant::asString(), CanContainFilter(), CURL::Get(), CURL::GetOption(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CURL::HasOption(), CGUIListItem::HasProperty(), KODI::PLAYLIST::CSmartPlaylist::LoadFromJson(), CLog::Log(), LOGWARNING, m_filter, m_strFilterPath, m_vecItems, PROPERTY_PATH_DB, KODI::PLAYLIST::CSmartPlaylist::Reset(), and CURL::SetOption().
Referenced by Update().
UseFileDirectories()
virtual bool CGUIMediaWindow::UseFileDirectories () inline virtual
Reimplemented in CGUIWindowAddonBrowser, and PVR::CGUIWindowPVRBase.
Referenced by GetDirectory(), and SetHistoryForPath().
WaitForNetwork()
bool CGUIMediaWindow::WaitForNetwork () const protected
References CGUIWindow::Close(), CServiceBroker::GetGUI(), CServiceBroker::GetNetwork(), CFileItem::GetPath(), CGUIComponent::GetWindowManager(), CURL::GetWithoutUserDetails(), CGUIDialogProgress::IsCanceled(), m_vecItems, CGUIDialogProgress::Open(), CGUIDialogProgress::Progress(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CGUIDialogProgress::ShowProgressBar(), and WINDOW_DIALOG_PROGRESS.
Referenced by OnMessage().
WaitGetDirectoryItems()
bool CGUIMediaWindow::WaitGetDirectoryItems (CGetDirectoryItems & items) protected
References CServiceBroker::GetGUI(), CServiceBroker::GetJobManager(), CGUIComponent::GetWindowManager(), CGUIDialog::IsDialogRunning(), LOGDEBUG, m_updateAborted, m_updateEvent, m_updateJobActive, CJob::PRIORITY_NORMAL, ProcessRenderLoop(), CEvent::Reset(), CEvent::Set(), CGUIDialogBusy::Wait(), CEvent::Wait(), and WINDOW_DIALOG_BUSY.
Referenced by GetDirectoryItems().
Member Data Documentation
m_backgroundLoad
bool CGUIMediaWindow::m_backgroundLoad = false protected
Referenced by GetDirectoryItems(), OnInitWindow(), and OnPopupMenu().
m_canFilterAdvanced
bool CGUIMediaWindow::m_canFilterAdvanced protected
Referenced by CanFilterAdvanced(), CGUIMediaWindow(), Filter(), GetDirectory(), GetFilteredItems(), IsFiltered(), OnBack(), OnClick(), OnFilterItems(), OnMessage(), and Update().
m_filter
KODI::PLAYLIST::CSmartPlaylist CGUIMediaWindow::m_filter protected
Referenced by Filter(), GetAdvanceFilteredItems(), GetDirectory(), GoParentFolder(), IsFiltered(), OnClick(), OnMessage(), Update(), and UpdateFilterPath().
m_guiState
std::unique_ptr<CGUIViewState> CGUIMediaWindow::m_guiState protected
Referenced by CGUIMediaWindow(), GetDirectory(), CGUIWindowMusicNav::GetSongsFromPlayList(), GetViewState(), CGUIWindowMusicBase::LoadPlayList(), CGUIWindowVideoBase::LoadPlayList(), PVR::CGUIWindowPVRGuideBase::NotifyEvent(), OnClick(), PVR::CGUIWindowPVRGuideBase::OnInitWindow(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoNav::OnMessage(), OnMessage(), OnPlayAndQueueMedia(), CGUIWindowVideoBase::OnPlayAndQueueMedia(), CGUIWindowVideoBase::OnPlayMedia(), OnPlayMedia(), CGUIWindowMusicBase::OnPlayMedia(), CGUIWindowMusicPlayList::OnPlayMedia(), CGUIWindowPictures::OnShowPictureRecursive(), CGUIWindowPictures::OnSlideShow(), CGUIWindowPictures::OnSlideShowRecursive(), CGUIWindowVideoBase::PlayItem(), PVR::CGUIWindowPVRGuideBase::RefreshTimelineItems(), Update(), UpdateButtons(), CGUIWindowPictures::UpdateButtons(), and UpdateFileList().
m_history
CDirectoryHistory CGUIMediaWindow::m_history protected
Referenced by GetDirectory(), CGUIWindowMusicNav::GetSongsFromPlayList(), GoParentFolder(), OnClick(), OnFilterItems(), OnMessage(), CGUIWindowMusicNav::OnSearchUpdate(), RestoreSelectedItemFromHistory(), CGUIWindowMusicPlayList::SavePlayList(), SaveSelectedItemInHistory(), SetHistoryForPath(), and Update().
m_iLastControl
int CGUIMediaWindow::m_iLastControl protected
Referenced by CGUIMediaWindow(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), OnMessage(), and Update().
m_rootDir
XFILE::CVirtualDirectory CGUIMediaWindow::m_rootDir protected
Referenced by CGUIWindowMusicNav::AddSearchFolder(), CancelUpdateItems(), CGUIWindowPrograms::CGUIWindowPrograms(), PVR::CGUIWindowPVRBase::CGUIWindowPVRBase(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowPictures::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), GetDirectoryItems(), KODI::GAME::CGUIWindowGames::GetStartFolder(), CGUIWindowPictures::GetStartFolder(), CGUIWindowPrograms::GetStartFolder(), KODI::GAME::CGUIWindowGames::OnClick(), KODI::GAME::CGUIWindowGames::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowVideoNav::OnMessage(), OnMessage(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), SetupShares(), and KODI::GAME::CGUIWindowGames::SetupShares().
m_startDirectory
std::string CGUIMediaWindow::m_startDirectory protected
Referenced by OnBack(), OnInitWindow(), and OnMessage().
m_strFilterPath
std::string CGUIMediaWindow::m_strFilterPath protected
Contains the path used for filtering (including any active filter)
When Update() is called with a path to e.g. a smartplaylist or a library node filter, that "original" path will be stored in m_vecItems->m_strPath. But the path used by XBMC to retrieve those items from the database (Videodb:// or musicdb://) is stored in this member variable to still have access to it because it is used for filtering by appending the currently active filter as a "filter" parameter to the filter path/URL.
See also
Update
Referenced by CGUIWindowMusicBase::CheckFilterAdvanced(), CGUIWindowVideoBase::CheckFilterAdvanced(), Filter(), GetAdvanceFilteredItems(), CGUIWindowVideoBase::GetGroupedItems(), GoParentFolder(), OnBack(), OnClick(), OnFilterItems(), OnMessage(), SetHistoryForPath(), Update(), and UpdateFilterPath().
m_unfilteredItems
CFileItemList* CGUIMediaWindow::m_unfilteredItems protected
items prior to filtering using FilterItems()
Referenced by CGUIMediaWindow(), ClearFileItems(), GoParentFolder(), OnFilterItems(), Update(), CGUIWindowMusicNav::Update(), and ~CGUIMediaWindow().
m_updateAborted
std::atomic_bool CGUIMediaWindow::m_updateAborted = {false} protected
Referenced by CancelUpdateItems(), and WaitGetDirectoryItems().
m_updateEvent
CEvent CGUIMediaWindow::m_updateEvent protected
Referenced by CancelUpdateItems(), and WaitGetDirectoryItems().
m_updateJobActive
std::atomic_bool CGUIMediaWindow::m_updateJobActive = {false} protected
Referenced by CancelUpdateItems(), GetDirectoryItems(), and WaitGetDirectoryItems().
m_vecItems
CFileItemList* CGUIMediaWindow::m_vecItems protected
Referenced by ADDON::CGUIAddonWindow::AddItem(), CGUIWindowVideoNav::ApplyWatchedFilter(), CGUIMediaWindow(), CGUIWindowMusicNav::CGUIWindowMusicNav(), ClearFileItems(), ADDON::CGUIAddonWindow::ClearList(), CGUIWindowVideoPlaylist::ClearPlayList(), CurrentDirectory(), PVR::CGUIWindowPVRSearchBase::ExecuteSearch(), CGUIWindowEventLog::GetContextButtons(), KODI::GAME::CGUIWindowGames::GetContextButtons(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowMusicPlayList::GetContextButtons(), CGUIWindowPictures::GetContextButtons(), CGUIWindowPrograms::GetContextButtons(), PVR::CGUIWindowPVRRecordingsBase::GetContextButtons(), PVR::CGUIWindowPVRSearchBase::GetContextButtons(), CGUIWindowVideoBase::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), CGUIWindowVideoPlaylist::GetContextButtons(), GetCurrentListItem(), GetDirectory(), PVR::CGUIWindowPVRChannelsBase::GetDirectoryPath(), PVR::CGUIWindowPVRTVProviders::GetDirectoryPath(), PVR::CGUIWindowPVRRadioProviders::GetDirectoryPath(), PVR::CGUIWindowPVRRecordingsBase::GetDirectoryPath(), PVR::CGUIWindowPVRTVSearch::GetDirectoryPath(), PVR::CGUIWindowPVRRadioSearch::GetDirectoryPath(), PVR::CGUIWindowPVRTVTimerRules::GetDirectoryPath(), PVR::CGUIWindowPVRRadioTimerRules::GetDirectoryPath(), PVR::CGUIWindowPVRTVTimers::GetDirectoryPath(), PVR::CGUIWindowPVRRadioTimers::GetDirectoryPath(), CGUIWindowVideoNav::GetFirstUnwatchedItemIndex(), ADDON::CGUIAddonWindow::GetListItem(), ADDON::CGUIAddonWindow::GetListSize(), PVR::CGUIWindowPVRRecordingsBase::GetRootPath(), CGUIWindowVideoBase::GetScraperForItem(), CGUIWindowVideoNav::GetSettingSelectFirstUnwatchedItem(), GoParentFolder(), PVR::CGUIWindowPVRBase::InitChannelGroup(), IsSameStartFolder(), CGUIWindowMusicNav::ManageInfoProvider(), CGUIWindowMusicPlayList::MoveItem(), CGUIWindowVideoPlaylist::MoveItem(), CGUIWindowFavourites::MoveItem(), CGUIWindowFavourites::OnAction(), CGUIWindowMusicBase::OnAction(), CGUIWindowMusicNav::OnAction(), PVR::CGUIWindowPVRProvidersBase::OnAction(), PVR::CGUIWindowPVRRecordingsBase::OnAction(), PVR::CGUIWindowPVRSearchBase::OnAction(), PVR::CGUIWindowPVRTimersBase::OnAction(), CGUIWindowVideoNav::OnAction(), OnBack(), OnClick(), CGUIWindowAddonBrowser::OnClick(), KODI::GAME::CGUIWindowGames::OnClick(), CGUIWindowMusicNav::OnClick(), CGUIWindowMusicPlaylistEditor::OnClick(), CGUIWindowPictures::OnClick(), CGUIWindowVideoNav::OnClick(), KODI::GAME::CGUIWindowGames::OnClickMsg(), CGUIWindowEventLog::OnContextButton(), KODI::GAME::CGUIWindowGames::OnContextButton(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowPictures::OnContextButton(), CGUIWindowPrograms::OnContextButton(), PVR::CGUIWindowPVRChannelsBase::OnContextButton(), PVR::CGUIWindowPVRGuideBase::OnContextButton(), PVR::CGUIWindowPVRRecordingsBase::OnContextButton(), PVR::CGUIWindowPVRSearchBase::OnContextButton(), CGUIWindowVideoBase::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), PVR::CGUIWindowPVRRecordingsBase::OnDeinitWindow(), CGUIWindowVideoBase::OnDeleteItem(), CGUIWindowVideoNav::OnDeleteItem(), OnDeleteItem(), CGUIWindowVideoBase::OnDeleteItem(), CGUIWindowEventLog::OnEventRemoved(), CGUIWindowVideoBase::OnFileAction(), OnFilterItems(), CGUIWindowPictures::OnInitWindow(), OnInitWindow(), PVR::CGUIWindowPVRChannelsBase::OnInputDone(), CGUIWindowMusicBase::OnItemInfo(), CGUIWindowPrograms::OnItemInfo(), CGUIWindowPictures::OnItemInfo(), CGUIWindowVideoBase::OnItemInfo(), KODI::GAME::CGUIWindowGames::OnItemInfo(), CGUIWindowMusicBase::OnItemInfoAll(), CGUIWindowAddonBrowser::OnMessage(), CGUIWindowEventLog::OnMessage(), CGUIWindowFavourites::OnMessage(), KODI::GAME::CGUIWindowGames::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowMusicPlaylistEditor::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), OnMessage(), CGUIWindowMusicPlayList::OnMove(), CGUIWindowVideoPlaylist::OnMove(), OnPlayAndQueueMedia(), CGUIWindowVideoBase::OnPlayMedia(), CGUIWindowPrograms::OnPlayMedia(), OnPlayMedia(), CGUIWindowMusicBase::OnPlayMedia(), CGUIWindowMusicPlayList::OnPlayMedia(), CGUIWindowPictures::OnPlayMedia(), CGUIWindowVideoBase::OnPlayMedia(), CGUIWindowVideoPlaylist::OnPlayMedia(), CGUIWindowVideoBase::OnPlayOrResumeItem(), OnPopupMenu(), CGUIWindowMusicNav::OnPopupMenu(), PVR::CGUIWindowPVRRecordingsBase::OnPopupMenu(), CGUIWindowVideoNav::OnPopupMenu(), PVR::CGUIWindowPVRTimersBase::OnPrepareFileItems(), CGUIWindowMusicBase::OnQueueItem(), CGUIWindowVideoBase::OnQueueItem(), CGUIWindowMusicPlaylistEditor::OnQueueItem(), CGUIWindowPictures::OnRegenerateThumbs(), CGUIWindowMusicBase::OnRemoveSource(), OnRenameItem(), CGUIWindowMusicBase::OnRipTrack(), CGUIWindowMusicBase::OnScan(), CGUIWindowVideoBase::OnSearchItemFound(), CGUIWindowMusicNav::OnSearchUpdate(), CGUIWindowMusicBase::OnSelect(), CGUIWindowVideoBase::OnSelect(), CGUIWindowEventLog::OnSelect(), CGUIWindowFavourites::OnSelect(), CGUIWindowPictures::OnSlideShow(), CGUIWindowPictures::OnSlideShowRecursive(), CGUIWindowMusicPlaylistEditor::OnSourcesContext(), PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::PlayItem(), CGUIWindowMusicNav::PlayItem(), CGUIWindowMusicPlaylistEditor::PlayItem(), Refresh(), CGUIWindowMusicBase::RefreshContent(), ADDON::CGUIAddonWindow::RemoveItem(), CGUIWindowFavourites::RemoveItem(), ADDON::CGUIAddonWindow::RemoveItem(), CGUIWindowMusicPlayList::RemovePlayListItem(), CGUIWindowVideoPlaylist::RemovePlayListItem(), RestoreSelectedItemFromHistory(), CGUIWindowMusicBase::RetrieveMusicInfo(), CGUIWindowMusicPlayList::SavePlayList(), CGUIWindowVideoPlaylist::SavePlayList(), SaveSelectedItemInHistory(), ADDON::CGUIAddonWindow::SetContainerContent(), ADDON::CGUIAddonWindow::SetContainerProperty(), PVR::CGUIWindowPVRBase::SetInvalid(), PVR::CGUIWindowPVRChannelsBase::ShowChannelManager(), CGUIWindowPictures::ShowPicture(), Update(), CGUIWindowAddonBrowser::Update(), CGUIWindowMusicPlayList::Update(), CGUIWindowMusicPlaylistEditor::Update(), CGUIWindowPictures::Update(), CGUIWindowPrograms::Update(), PVR::CGUIWindowPVRBase::Update(), PVR::CGUIWindowPVRChannelsBase::Update(), PVR::CGUIWindowPVRRecordingsBase::Update(), PVR::CGUIWindowPVRSearchBase::Update(), PVR::CGUIWindowPVRTimersBase::Update(), CGUIWindowVideoBase::Update(), UpdateButtons(), CGUIWindowAddonBrowser::UpdateButtons(), CGUIWindowEventLog::UpdateButtons(), CGUIWindowMusicBase::UpdateButtons(), CGUIWindowMusicNav::UpdateButtons(), CGUIWindowMusicPlayList::UpdateButtons(), CGUIWindowMusicPlaylistEditor::UpdateButtons(), CGUIWindowPictures::UpdateButtons(), PVR::CGUIWindowPVRChannelsBase::UpdateButtons(), PVR::CGUIWindowPVRProvidersBase::UpdateButtons(), PVR::CGUIWindowPVRRecordingsBase::UpdateButtons(), PVR::CGUIWindowPVRSearchBase::UpdateButtons(), CGUIWindowVideoNav::UpdateButtons(), CGUIWindowVideoPlaylist::UpdateButtons(), UpdateFileList(), UpdateFilterPath(), CGUIWindowVideoBase::UpdateVideoVersionItems(), CGUIWindowVideoBase::UpdateVideoVersionItemsLabel(), WaitForNetwork(), and ~CGUIMediaWindow().
m_vecItemsUpdating
std::atomic_bool CGUIMediaWindow::m_vecItemsUpdating = {false} protected
Referenced by OnClick(), CGUIWindowMusicPlayList::OnMessage(), and OnMessage().
m_viewControl
CGUIViewControl CGUIMediaWindow::m_viewControl protected
Referenced by ADDON::CGUIAddonWindow::AddItem(), ClearFileItems(), ADDON::CGUIAddonWindow::ClearList(), CGUIWindowVideoPlaylist::ClearPlayList(), ADDON::CGUIAddonWindow::GetCurrentContainerControlId(), GetCurrentListItem(), ADDON::CGUIAddonWindow::GetCurrentListPosition(), GetFirstFocusableControl(), PVR::CGUIWindowPVRGuideBase::GetGridControl(), GetViewContainerID(), GetViewCount(), PVR::CGUIWindowPVRBase::InitChannelGroup(), Load(), CGUIWindowFavourites::MoveItem(), CGUIWindowFavourites::OnAction(), CGUIWindowMusicBase::OnAction(), CGUIWindowMusicNav::OnAction(), CGUIWindowMusicPlayList::OnAction(), PVR::CGUIWindowPVRRecordingsBase::OnAction(), CGUIWindowVideoBase::OnAction(), CGUIWindowVideoNav::OnAction(), CGUIWindowVideoPlaylist::OnAction(), CGUIWindowMusicPlaylistEditor::OnBack(), KODI::GAME::CGUIWindowGames::OnClickMsg(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), CGUIWindowVideoNav::OnDeleteItem(), OnDeleteItem(), CGUIWindowVideoBase::OnDeleteItem(), CGUIWindowEventLog::OnEventRemoved(), OnFilterItems(), CGUIWindowPictures::OnInitWindow(), PVR::CGUIWindowPVRBase::OnInitWindow(), PVR::CGUIWindowPVRGuideBase::OnInitWindow(), PVR::CGUIWindowPVRChannelsBase::OnInputDone(), CGUIWindowAddonBrowser::OnMessage(), ADDON::CGUIAddonWindow::OnMessage(), CGUIWindowEventLog::OnMessage(), CGUIWindowFavourites::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIWindowPVRBase::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), OnMessage(), CGUIWindowVideoBase::OnQueueItem(), CGUIWindowMusicBase::OnQueueItem(), OnRenameItem(), CGUIWindowVideoBase::OnSearchItemFound(), CGUIWindowMusicPlaylistEditor::OnSourcesContext(), OnWindowUnload(), CGUIWindowVideoBase::PlayItem(), ADDON::CGUIAddonWindow::RemoveItem(), ADDON::CGUIAddonWindow::RemoveItem(), CGUIWindowMusicPlayList::RemovePlayListItem(), CGUIWindowVideoPlaylist::RemovePlayListItem(), RestoreSelectedItemFromHistory(), CGUIWindowMusicPlayList::SavePlayList(), SaveSelectedItemInHistory(), CGUIWindowVideoNav::SelectFirstUnwatched(), ADDON::CGUIAddonWindow::SetCurrentListPosition(), PVR::CGUIWindowPVRChannelsBase::ShowChannelManager(), CGUIWindowVideoBase::ShowInfoAndRefresh(), PVR::CGUIWindowPVRBase::Update(), UpdateButtons(), UpdateFileList(), and PVR::CGUIWindowPVRBase::UpdateSelectedItemPath().
The documentation for this class was generated from the following files:
GUIMediaWindow.h
GUIMediaWindow.cpp