Kodi Documentation: JSONRPC::CVideoLibrary Class Reference
JSONRPC::CVideoLibrary Class Reference
#include <VideoLibrary.h>
Static Public Member Functions
static JSONRPC_STATUS GetMovies (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetMovieDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetMovieSets (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetMovieSetDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetTVShows (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetTVShowDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetSeasons (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetSeasonDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetEpisodes (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetEpisodeDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetMusicVideos (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetMusicVideoDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetRecentlyAddedMovies (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetRecentlyAddedEpisodes (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetRecentlyAddedMusicVideos (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetInProgressTVShows (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetGenres (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetTags (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetAvailableArtTypes (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetAvailableArt (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetMovieDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetMovieSetDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetTVShowDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetSeasonDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetEpisodeDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetMusicVideoDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS RefreshMovie (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS RefreshTVShow (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS RefreshEpisode (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS RefreshMusicVideo (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS RemoveMovie (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS RemoveTVShow (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS RemoveEpisode (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS RemoveMusicVideo (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Scan (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Export (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Clean (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static bool FillFileItem (const std::string &strFilename, std::shared_ptr< CFileItem > &item, const CVariant &parameterObject=CVariant(CVariant::VariantTypeArray))
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
static void UpdateResumePoint (const CVariant &parameterObject, CVideoInfoTag &details, CVideoDatabase &videodatabase)
static int GetDetailsFromJsonParameters (const CVariant &parameterObject)
Provided the JSON-RPC parameter object compute the VideoDbDetails mask.
Static Public Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
Static Private Member Functions
static int RequiresAdditionalDetails (const MediaType &mediaType, const CVariant &parameterObject)
static JSONRPC_STATUS HandleItems (const char *idProperty, const char *resultName, CFileItemList &items, const CVariant &parameterObject, CVariant &result, bool limit=true)
static JSONRPC_STATUS RemoveVideo (const CVariant &parameterObject)
static void UpdateVideoTag (const CVariant &parameterObject, CVideoInfoTag &details, std::map< std::string, std::string > &artwork, std::set< std::string > &removedArtwork, std::set< std::string > &updatedDetails)
static void UpdateVideoTagField (const CVariant &parameterObject, const std::string &fieldName, std::vector< std::string > &fieldValue, std::set< std::string > &updatedDetails)
Additional Inherited Members
Static Protected Member Functions inherited from JSONRPC::CFileItemHandler
static void FillDetails (const ISerializable *info, const std::shared_ptr< CFileItem > &item, std::set< std::string > &fields, CVariant &result, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, bool sortLimit=true)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, int size, bool sortLimit=true)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const CVariant &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const std::set< std::string > &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
Static Protected Member Functions inherited from JSONRPC::CJSONUtils
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Member Function Documentation
Clean()
JSONRPC_STATUS CVideoLibrary::Clean (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asString(), CServiceBroker::GetAppMessenger(), and TMSG_EXECUTE_BUILT_IN.
Export()
JSONRPC_STATUS CVideoLibrary::Export (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CServiceBroker::GetAppMessenger(), and TMSG_EXECUTE_BUILT_IN.
FillFileItem()
bool CVideoLibrary::FillFileItem (const std::string & strFilename, std::shared_ptr< CFileItem > & item, const CVariant & parameterObject = CVariant(CVariant::VariantTypeArray)) static
References URIUtils::GetFileName(), CUtil::GetTitleFromPath(), CVideoDatabase::LoadVideoInfo(), and CVideoDatabase::Open().
Referenced by JSONRPC::CFileOperations::FillFileItem(), FillFileItemList(), and JSONRPC::CPlayerOperations::GetItem().
FillFileItemList()
bool CVideoLibrary::FillFileItemList (const CVariant & parameterObject, CFileItemList & list) static
Todo:
API support for video version id
References CFileItemList::Add(), CVariant::asInteger(), CVariant::asString(), FillFileItem(), CVideoDatabase::GetEpisodeInfo(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMusicVideoInfo(), JSONRPC::CPVROperations::GetRecordingFileItem(), CVideoInfoTag::IsEmpty(), CVideoDatabase::Open(), and success.
Referenced by JSONRPC::CFileItemHandler::FillFileItemList().
GetAvailableArt()
JSONRPC_STATUS CVideoLibrary::GetAvailableArt (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::append(), CVariant::asInteger32(), CVariant::asString(), CVideoDatabase::GetAvailableArtForItem(), JSONRPC::InternalError, JSONRPC::OK, CVideoDatabase::Open(), IMAGE_FILES::URLFromFile(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
GetAvailableArtTypes()
JSONRPC_STATUS CVideoLibrary::GetAvailableArtTypes (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::append(), CVariant::asInteger32(), CVideoDatabase::GetAvailableArtTypesForItem(), JSONRPC::InternalError, JSONRPC::OK, CVideoDatabase::Open(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
GetDetailsFromJsonParameters()
int CVideoLibrary::GetDetailsFromJsonParameters (const CVariant & parameterObject) static
Provided the JSON-RPC parameter object compute the VideoDbDetails mask.
Parameters
parameterObject the JSON parameter mask
Returns
the mask value for the requested properties
References CVariant::asString(), CVariant::begin_array(), CVariant::end_array(), VideoDbDetailsCast, VideoDbDetailsNone, VideoDbDetailsRating, VideoDbDetailsShowLink, VideoDbDetailsStream, VideoDbDetailsTag, and VideoDbDetailsUniqueID.
Referenced by JSONRPC::CFileOperations::GetDirectory(), and RequiresAdditionalDetails().
GetEpisodeDetails()
JSONRPC_STATUS CVideoLibrary::GetEpisodeDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetEpisodeInfo(), CVideoDatabase::GetTvShowForEpisode(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iIdShow, CVideoInfoTag::m_iSeason, MediaTypeEpisode, JSONRPC::OK, CVideoDatabase::Open(), and RequiresAdditionalDetails().
GetEpisodes()
JSONRPC_STATUS CVideoLibrary::GetEpisodes (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CDbUrl::AddOption(), CDbUrl::FromString(), CVideoDatabase::GetEpisodesByWhere(), JSONRPC::CJSONUtils::GetXspFiltering(), HandleItems(), CDbUrl::HasOption(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVariant::isMember(), CVariant::isObject(), SortDescription::limitEnd, SortDescription::limitStart, MediaTypeEpisode, CVideoDatabase::Open(), JSONRPC::CJSONUtils::ParseLimits(), JSONRPC::CJSONUtils::ParseSorting(), RequiresAdditionalDetails(), SortDescription::sortAttributes, SortDescription::sortBy, SortDescription::sortOrder, and CDbUrl::ToString().
GetGenres()
JSONRPC_STATUS CVideoLibrary::GetGenres (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), CVideoDatabase::GetGenresNav(), CGUIListItem::GetLabel(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InternalError, CFileItem::m_strTitle, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MOVIES, MUSICVIDEOS, JSONRPC::OK, CVideoDatabase::Open(), CFileItemList::Size(), TVSHOWS, and UNKNOWN.
GetInProgressTVShows()
JSONRPC_STATUS CVideoLibrary::GetInProgressTVShows (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetInProgressTvShowsNav(), HandleItems(), JSONRPC::InternalError, MediaTypeTvShow, CVideoDatabase::Open(), and RequiresAdditionalDetails().
GetMovieDetails()
JSONRPC_STATUS CVideoLibrary::GetMovieDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
Todo:
API support for video version id
References CVideoDatabase::GetMovieInfo(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, MediaTypeMovie, JSONRPC::OK, CVideoDatabase::Open(), and RequiresAdditionalDetails().
GetMovies()
JSONRPC_STATUS CVideoLibrary::GetMovies (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CDbUrl::AddOption(), CVariant::asInteger(), CVariant::asString(), CDbUrl::FromString(), CVideoDatabase::GetMoviesNav(), JSONRPC::CJSONUtils::GetXspFiltering(), HandleItems(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVariant::isMember(), CVariant::isObject(), SortDescription::limitEnd, SortDescription::limitStart, MediaTypeMovie, CVideoDatabase::Open(), JSONRPC::CJSONUtils::ParseLimits(), JSONRPC::CJSONUtils::ParseSorting(), RequiresAdditionalDetails(), SortDescription::sortAttributes, SortDescription::sortBy, SortDescription::sortOrder, and CDbUrl::ToString().
GetMovieSetDetails()
JSONRPC_STATUS CVideoLibrary::GetMovieSetDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetMoviesNav(), CVideoDatabase::GetSetInfo(), JSONRPC::CFileItemHandler::HandleFileItem(), HandleItems(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, MediaTypeMovie, CVideoDatabase::Open(), and RequiresAdditionalDetails().
GetMovieSets()
JSONRPC_STATUS CVideoLibrary::GetMovieSets (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetSetsNav(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InternalError, MOVIES, JSONRPC::OK, and CVideoDatabase::Open().
GetMusicVideoDetails()
JSONRPC_STATUS CVideoLibrary::GetMusicVideoDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetMusicVideoInfo(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, MediaTypeMusicVideo, JSONRPC::OK, CVideoDatabase::Open(), and RequiresAdditionalDetails().
GetMusicVideos()
JSONRPC_STATUS CVideoLibrary::GetMusicVideos (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CDbUrl::AddOption(), CVariant::asInteger(), CVariant::asString(), CDbUrl::FromString(), CVideoDatabase::GetMusicVideosNav(), JSONRPC::CJSONUtils::GetXspFiltering(), HandleItems(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVariant::isMember(), CVariant::isObject(), SortDescription::limitEnd, SortDescription::limitStart, MediaTypeMusicVideo, CVideoDatabase::Open(), JSONRPC::CJSONUtils::ParseLimits(), JSONRPC::CJSONUtils::ParseSorting(), RequiresAdditionalDetails(), SortDescription::sortAttributes, SortDescription::sortBy, SortDescription::sortOrder, and CDbUrl::ToString().
GetRecentlyAddedEpisodes()
JSONRPC_STATUS CVideoLibrary::GetRecentlyAddedEpisodes (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetRecentlyAddedEpisodesNav(), HandleItems(), JSONRPC::InternalError, MediaTypeEpisode, CVideoDatabase::Open(), and RequiresAdditionalDetails().
GetRecentlyAddedMovies()
JSONRPC_STATUS CVideoLibrary::GetRecentlyAddedMovies (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetRecentlyAddedMoviesNav(), HandleItems(), JSONRPC::InternalError, MediaTypeMovie, CVideoDatabase::Open(), and RequiresAdditionalDetails().
GetRecentlyAddedMusicVideos()
JSONRPC_STATUS CVideoLibrary::GetRecentlyAddedMusicVideos (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetRecentlyAddedMusicVideosNav(), HandleItems(), JSONRPC::InternalError, MediaTypeMusicVideo, CVideoDatabase::Open(), and RequiresAdditionalDetails().
GetSeasonDetails()
JSONRPC_STATUS CVideoLibrary::GetSeasonDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetSeasonInfo(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iIdShow, JSONRPC::OK, and CVideoDatabase::Open().
GetSeasons()
JSONRPC_STATUS CVideoLibrary::GetSeasons (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetSeasonsNav(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InternalError, JSONRPC::OK, and CVideoDatabase::Open().
GetTags()
JSONRPC_STATUS CVideoLibrary::GetTags (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), CGUIListItem::GetLabel(), CVideoDatabase::GetTagsNav(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InternalError, CFileItem::m_strTitle, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MOVIES, MUSICVIDEOS, JSONRPC::OK, CVideoDatabase::Open(), CFileItemList::Size(), TVSHOWS, and UNKNOWN.
GetTVShowDetails()
JSONRPC_STATUS CVideoLibrary::GetTVShowDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVideoDatabase::GetTvShowInfo(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, MediaTypeTvShow, JSONRPC::OK, CVideoDatabase::Open(), and RequiresAdditionalDetails().
GetTVShows()
JSONRPC_STATUS CVideoLibrary::GetTVShows (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CDbUrl::AddOption(), CDbUrl::FromString(), CVideoDatabase::GetTvShowsByWhere(), JSONRPC::CJSONUtils::GetXspFiltering(), HandleItems(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVariant::isMember(), CVariant::isObject(), SortDescription::limitEnd, SortDescription::limitStart, MediaTypeTvShow, CVideoDatabase::Open(), JSONRPC::CJSONUtils::ParseLimits(), JSONRPC::CJSONUtils::ParseSorting(), RequiresAdditionalDetails(), SortDescription::sortAttributes, SortDescription::sortBy, SortDescription::sortOrder, and CDbUrl::ToString().
HandleItems()
JSONRPC_STATUS CVideoLibrary::HandleItems (const char * idProperty, const char * resultName, CFileItemList & items, const CVariant & parameterObject, CVariant & result, bool limit = true) static private
References CVariant::asInteger(), CGUIListItem::GetProperty(), JSONRPC::CFileItemHandler::HandleFileItemList(), CGUIListItem::HasProperty(), JSONRPC::OK, and CFileItemList::Size().
Referenced by GetEpisodes(), GetInProgressTVShows(), GetMovies(), GetMovieSetDetails(), GetMusicVideos(), GetRecentlyAddedEpisodes(), GetRecentlyAddedMovies(), GetRecentlyAddedMusicVideos(), and GetTVShows().
RefreshEpisode()
JSONRPC_STATUS CVideoLibrary::RefreshEpisode (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asBoolean(), CVariant::asString(), CVideoDatabase::GetEpisodeInfo(), CVideoLibraryQueue::GetInstance(), CVideoDatabase::GetTvShowForEpisode(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iIdShow, CVideoDatabase::Open(), and CVideoLibraryQueue::RefreshItem().
RefreshMovie()
JSONRPC_STATUS CVideoLibrary::RefreshMovie (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
Todo:
API support for video version id
References JSONRPC::ACK, CVariant::asBoolean(), CVariant::asInteger(), CVariant::asString(), CVideoLibraryQueue::GetInstance(), CVideoDatabase::GetMovieInfo(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoDatabase::Open(), and CVideoLibraryQueue::RefreshItem().
RefreshMusicVideo()
JSONRPC_STATUS CVideoLibrary::RefreshMusicVideo (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asBoolean(), CVariant::asInteger(), CVariant::asString(), CVideoLibraryQueue::GetInstance(), CVideoDatabase::GetMusicVideoInfo(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoDatabase::Open(), and CVideoLibraryQueue::RefreshItem().
RefreshTVShow()
JSONRPC_STATUS CVideoLibrary::RefreshTVShow (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asBoolean(), CVariant::asInteger(), CVariant::asString(), CVideoLibraryQueue::GetInstance(), CVideoDatabase::GetTvShowInfo(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoDatabase::Open(), and CVideoLibraryQueue::RefreshItem().
RemoveEpisode()
JSONRPC_STATUS CVideoLibrary::RemoveEpisode (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References RemoveVideo().
RemoveMovie()
JSONRPC_STATUS CVideoLibrary::RemoveMovie (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References RemoveVideo().
RemoveMusicVideo()
JSONRPC_STATUS CVideoLibrary::RemoveMusicVideo (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References RemoveVideo().
RemoveTVShow()
JSONRPC_STATUS CVideoLibrary::RemoveTVShow (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References RemoveVideo().
RemoveVideo()
JSONRPC_STATUS CVideoLibrary::RemoveVideo (const CVariant & parameterObject) static private
References JSONRPC::ACK, CVideoDatabase::DeleteEpisode(), CVideoDatabase::DeleteMovie(), CVideoDatabase::DeleteMusicVideo(), CVideoDatabase::DeleteTvShow(), JSONRPC::InternalError, CVariant::isMember(), JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), and CVideoDatabase::Open().
Referenced by RemoveEpisode(), RemoveMovie(), RemoveMusicVideo(), and RemoveTVShow().
RequiresAdditionalDetails()
int CVideoLibrary::RequiresAdditionalDetails (const MediaType & mediaType, const CVariant & parameterObject) static private
References GetDetailsFromJsonParameters(), MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, and VideoDbDetailsNone.
Referenced by GetEpisodeDetails(), GetEpisodes(), GetInProgressTVShows(), GetMovieDetails(), GetMovies(), GetMovieSetDetails(), GetMusicVideoDetails(), GetMusicVideos(), GetRecentlyAddedEpisodes(), GetRecentlyAddedMovies(), GetRecentlyAddedMusicVideos(), GetTVShowDetails(), and GetTVShows().
Scan()
JSONRPC_STATUS CVideoLibrary::Scan (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asString(), CServiceBroker::GetAppMessenger(), and TMSG_EXECUTE_BUILT_IN.
SetEpisodeDetails()
JSONRPC_STATUS CVideoLibrary::SetEpisodeDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CDatabase::Close(), CVideoDatabase::GetArtForItem(), CVideoDatabase::GetEpisodeInfo(), CVideoInfoTag::GetPlayCount(), CVideoDatabase::GetTvShowForEpisode(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_type, MediaTypeEpisode, JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CVideoDatabase::Open(), CVideoDatabase::RemoveArtForItem(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetPlayCount(), CVideoInfoTag::SetPlayCount(), UpdateResumePoint(), and UpdateVideoTag().
SetMovieDetails()
JSONRPC_STATUS CVideoLibrary::SetMovieDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
Todo:
API support for video version id)
References JSONRPC::ACK, CVideoDatabase::GetArtForItem(), CVideoDatabase::GetMovieInfo(), CVideoInfoTag::GetPlayCount(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_type, MediaTypeMovie, JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CVideoDatabase::Open(), CVideoDatabase::RemoveArtForItem(), CVideoDatabase::SetPlayCount(), CVideoInfoTag::SetPlayCount(), CVideoDatabase::UpdateDetailsForMovie(), UpdateResumePoint(), and UpdateVideoTag().
SetMovieSetDetails()
JSONRPC_STATUS CVideoLibrary::SetMovieSetDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CDatabase::Close(), CVideoDatabase::GetArtForItem(), CVideoDatabase::GetSetInfo(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_type, JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CVideoDatabase::Open(), CVideoDatabase::RemoveArtForItem(), CVideoDatabase::SetDetailsForMovieSet(), and UpdateVideoTag().
SetMusicVideoDetails()
JSONRPC_STATUS CVideoLibrary::SetMusicVideoDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CDatabase::Close(), CVideoDatabase::GetArtForItem(), CVideoDatabase::GetMusicVideoInfo(), CVideoInfoTag::GetPlayCount(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_type, MediaTypeMusicVideo, JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CVideoDatabase::Open(), CVideoDatabase::RemoveArtForItem(), CVideoDatabase::RemoveTagsFromItem(), CVideoDatabase::SetDetailsForMusicVideo(), CVideoDatabase::SetPlayCount(), CVideoInfoTag::SetPlayCount(), UpdateResumePoint(), and UpdateVideoTag().
SetSeasonDetails()
JSONRPC_STATUS CVideoLibrary::SetSeasonDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CDatabase::Close(), CVideoDatabase::GetArtForItem(), CVideoDatabase::GetSeasonInfo(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iIdShow, CVideoInfoTag::m_type, MediaTypeSeason, JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CVideoDatabase::Open(), JSONRPC::CJSONUtils::ParameterNotNull(), CVideoDatabase::RemoveArtForItem(), CVideoDatabase::SetDetailsForSeason(), CVideoInfoTag::SetSortTitle(), and UpdateVideoTag().
SetTVShowDetails()
JSONRPC_STATUS CVideoLibrary::SetTVShowDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVideoDatabase::GetArtForItem(), CVideoDatabase::GetTvShowInfo(), CVideoDatabase::GetTvShowSeasonArt(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_type, MediaTypeTvShow, JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CVideoDatabase::Open(), CVideoDatabase::RemoveArtForItem(), CVideoDatabase::RemoveTagsFromItem(), CVideoDatabase::UpdateDetailsForTvShow(), and UpdateVideoTag().
UpdateResumePoint()
void CVideoLibrary::UpdateResumePoint (const CVariant & parameterObject, CVideoInfoTag & details, CVideoDatabase & videodatabase) static
References CVideoDatabase::AddBookMarkToFile(), CVideoDatabase::ClearBookMarksOfFile(), CVideoDatabase::GetResumeBookMark(), CStreamDetails::GetVideoDuration(), CVideoInfoTag::m_streamDetails, CVideoInfoTag::m_strFileNameAndPath, CBookmark::RESUME, CBookmark::timeInSeconds, and CBookmark::totalTimeInSeconds.
Referenced by SetEpisodeDetails(), JSONRPC::CFileOperations::SetFileDetails(), SetMovieDetails(), and SetMusicVideoDetails().
UpdateVideoTag()
void CVideoLibrary::UpdateVideoTag (const CVariant & parameterObject, CVideoInfoTag & details, std::map< std::string, std::string > & artwork, std::set< std::string > & removedArtwork, std::set< std::string > & updatedDetails) static private
References CVariant::asInteger(), CVariant::asString(), CVariant::begin_map(), CVariant::end_map(), CVideoInfoTag::GetDefaultUniqueID(), CVideoInfoTag::m_artist, CVideoInfoTag::m_country, CVideoInfoTag::m_dateAdded, CVideoInfoTag::m_director, CVideoInfoTag::m_firstAired, CVideoInfoTag::m_genre, CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_iTop250, CVideoInfoTag::m_iTrack, CVideoInfoTag::m_iUserRating, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_showLink, CVideoInfoTag::m_studio, CVideoInfoTag::m_tags, CVideoInfoTag::m_writingCredits, JSONRPC::CJSONUtils::ParameterNotNull(), CVideoInfoTag::RemoveRating(), CVideoInfoTag::RemoveUniqueID(), CVideoInfoTag::SetAlbum(), CVideoInfoTag::SetArtist(), CVideoInfoTag::SetCountry(), CVideoInfoTag::SetDirector(), CVideoInfoTag::SetDuration(), CVideoInfoTag::SetEpisodeGuide(), JSONRPC::CJSONUtils::SetFromDBDate(), JSONRPC::CJSONUtils::SetFromDBDateTime(), CVideoInfoTag::SetGenre(), CVideoInfoTag::SetMPAARating(), CVideoInfoTag::SetOriginalTitle(), CVideoInfoTag::SetPlayCount(), CVideoInfoTag::SetPlot(), CVideoInfoTag::SetPlotOutline(), CVideoInfoTag::SetPremiered(), CVideoInfoTag::SetProductionCode(), CVideoInfoTag::SetRating(), CVideoInfoTag::SetSet(), CVideoInfoTag::SetShowLink(), CVideoInfoTag::SetSortTitle(), CVideoInfoTag::SetStatus(), CVideoInfoTag::SetStudio(), CVideoInfoTag::SetTagLine(), CVideoInfoTag::SetTags(), CVideoInfoTag::SetTitle(), CVideoInfoTag::SetTrailer(), CVideoInfoTag::SetUniqueID(), CVideoInfoTag::SetVotes(), CVideoInfoTag::SetWritingCredits(), CVideoInfoTag::SetYear(), tags, IMAGE_FILES::ToCacheKey(), UpdateVideoTagField(), and value.
Referenced by SetEpisodeDetails(), SetMovieDetails(), SetMovieSetDetails(), SetMusicVideoDetails(), SetSeasonDetails(), and SetTVShowDetails().
UpdateVideoTagField()
void CVideoLibrary::UpdateVideoTagField (const CVariant & parameterObject, const std::string & fieldName, std::vector< std::string > & fieldValue, std::set< std::string > & updatedDetails) static private
References JSONRPC::CJSONUtils::CopyStringArray(), and JSONRPC::CJSONUtils::ParameterNotNull().
Referenced by UpdateVideoTag().
The documentation for this class was generated from the following files:
VideoLibrary.h
VideoLibrary.cpp