Kodi Documentation: KODI::WINDOWING::WAYLAND Namespace Reference
KODI::WINDOWING::WAYLAND Namespace Reference
Classes
class CConnection
class CCursorUtil
class CInputProcessorKeyboard
class CInputProcessorPointer
class CInputProcessorTouch
class COSScreenSaverIdleInhibitUnstableV1
class COSScreenSaverWebOS
class COutput
class CRegistry
class CSeat
class CSeatInputProcessing
class CSeatSelection
class CSeatWebOS
class CShellSurfaceWebOSShell
class CShellSurfaceWlShell
class CShellSurfaceXdgShell
class CShellSurfaceXdgShellUnstableV6
class CVaapiProxy
class CVideoSyncWpPresentation
class CWindowDecorator
class CWinEventsWayland
class CWinSystemWayland
class CWinSystemWaylandEGLContext
class CWinSystemWaylandEGLContextGL
class CWinSystemWaylandEGLContextGLES
class CWinSystemWaylandWebOS
class CXkbcommonContext
class CXkbcommonKeymap
class IInputHandler
class IInputHandlerKeyboard
class IInputHandlerPointer
class IRawInputHandlerKeyboard
class IRawInputHandlerPointer
class IRawInputHandlerTouch
class IShellSurface
class IShellSurfaceHandler
class IWindowDecorationHandler
struct KeyComposerStatus
struct WaylandCPtrCompare
Typedefs
using CWinSystemWaylandImpl = CWinSystemWayland
Enumerations
enum class InputType { POINTER , KEYBOARD , TOUCH }
enum SurfaceIndex {
SURFACE_TOP = 0 , SURFACE_RIGHT , SURFACE_BOTTOM , SURFACE_LEFT ,
SURFACE_COUNT
}
enum class KeyComposerState { IDLE , COMPOSING , FINISHED , CANCELLED }
Functions
CVaapiProxy * VaapiProxyCreate ()
void VaapiProxyDelete (CVaapiProxy *proxy)
void VaapiProxyConfig (CVaapiProxy *proxy, void *dpy, void *eglDpy)
void VAAPIRegister (CVaapiProxy *winSystem, bool deepColor)
Typedef Documentation
CWinSystemWaylandImpl
using KODI::WINDOWING::WAYLAND::CWinSystemWaylandImpl = typedef CWinSystemWayland
Enumeration Type Documentation
InputType
enum class KODI::WINDOWING::WAYLAND::InputType strong
Enumerator
POINTER
KEYBOARD
TOUCH
KeyComposerState
enum class KODI::WINDOWING::WAYLAND::KeyComposerState strong
A wrapper class around an xkbcommon keymap and state tracker.
This class knows about some common modifier combinations and keeps track of the currently pressed keys and modifiers. It also has some utility functions to transform hardware keycodes into a common representation.
Since this class is keeping track of all the pressed and depressed modifiers, IT MUST ALWAYS BE KEPT UP TO DATE WITH ANY NEWLY PRESSED MODIFIERS. Undefined behaviour will result if it is not kept up to date.
Instances can be easily created from keymap strings with CXkbcommonContext Abstracts the key composer key state
Enumerator
IDLE
Key composer is idle
COMPOSING
Key composer is busy composing a key
FINISHED
Key composer finished composing a key, it has a valid key in the buffer
CANCELLED
Key composer was cancelled
SurfaceIndex
enum KODI::WINDOWING::WAYLAND::SurfaceIndex
Enumerator
SURFACE_TOP
SURFACE_RIGHT
SURFACE_BOTTOM
SURFACE_LEFT
SURFACE_COUNT
Function Documentation
VaapiProxyConfig()
void KODI::WINDOWING::WAYLAND::VaapiProxyConfig (CVaapiProxy * proxy, void * dpy, void * eglDpy)
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::InitWindowSystem(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::InitWindowSystem().
VaapiProxyCreate()
CVaapiProxy * KODI::WINDOWING::WAYLAND::VaapiProxyCreate ()
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::InitWindowSystem(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::InitWindowSystem().
VaapiProxyDelete()
void KODI::WINDOWING::WAYLAND::VaapiProxyDelete (CVaapiProxy * proxy)
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::delete_CVaapiProxy::operator()(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::delete_CVaapiProxy::operator()().
VAAPIRegister()
void KODI::WINDOWING::WAYLAND::VAAPIRegister (CVaapiProxy * winSystem, bool deepColor)
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::InitWindowSystem(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::InitWindowSystem().