Kodi Documentation: CScroller Class Reference
CScroller Class Reference
#include <VisibleEffect.h>
Public Member Functions
CScroller (unsigned int duration=200, std::shared_ptr< Tweener > tweener=std::shared_ptr< Tweener >())
CScroller (const CScroller &right)
CScroller & operator= (const CScroller &src)
~CScroller ()
void ScrollTo (float endPos)
void Stop ()
bool Update (unsigned int time)
float GetValue () const
void SetValue (float scrollValue)
bool IsScrolling () const
bool IsScrollingUp () const
bool IsScrollingDown () const
unsigned int GetDuration () const
Private Member Functions
float Tween (float progress)
Private Attributes
float m_scrollValue
float m_delta
Brief distance that we have to travel during scroll.
float m_startPosition
Brief starting position of scroll.
bool m_hasResumePoint
Brief check if we should tween from middle of the tween.
unsigned int m_startTime
Brief starting time of scroll.
unsigned int m_duration
Brief duration of scroll.
std::shared_ptr< Tweener > m_pTweener
Detailed Description
Class used to handle scrolling, allow using tweeners. Usage: start scrolling using ScrollTo() method / stop scrolling using Stop() method update scroll value each frame with current time using Update() method get/set scroll value using GetValue()/SetValue()
Constructor & Destructor Documentation
CScroller() [1/2]
CScroller::CScroller (unsigned int duration = 200, std::shared_ptr< Tweener > tweener = std::shared_ptr<Tweener>())
References m_delta, m_duration, m_hasResumePoint, m_scrollValue, m_startPosition, and m_startTime.
CScroller() [2/2]
CScroller::CScroller (const CScroller & right)
References m_pTweener, and right.
~CScroller()
CScroller::~CScroller () default
Member Function Documentation
GetDuration()
unsigned int CScroller::GetDuration () const inline
References m_duration.
Referenced by CGUIBaseContainer::GetCondition().
GetValue()
float CScroller::GetValue () const inline
Value of scroll
References m_scrollValue.
Referenced by CGUIControlGroupList::GetCondition(), CGUIBaseContainer::GetListItem(), CGUIControlGroupList::IsControlOnScreen(), CGUIControlGroupList::OnMessage(), CGUIBaseContainer::OnMouseEvent(), CGUIControlGroupList::OnMouseEvent(), CGUIBaseContainer::Process(), CGUIControlGroupList::Process(), CGUIPanelContainer::Process(), CGUIBaseContainer::Render(), CGUIControlGroupList::Render(), CGUIPanelContainer::Render(), CGUIControlGroupList::ScrollPages(), CGUIBaseContainer::ScrollToOffset(), CGUIControlGroupList::SendMouseEvent(), CGUIControlGroupList::UnfocusFromPoint(), CGUIControlGroupList::ValidateOffset(), CGUIFixedListContainer::ValidateOffset(), CGUIListContainer::ValidateOffset(), and CGUIPanelContainer::ValidateOffset().
IsScrolling()
bool CScroller::IsScrolling () const inline
References m_delta.
Referenced by CGUIBaseContainer::Process(), CGUIControlGroupList::ScrollTo(), CGUIBaseContainer::ScrollToOffset(), CGUIBaseContainer::SetContainerMoving(), CGUIBaseContainer::UpdateAutoScrolling(), CGUIFixedListContainer::ValidateOffset(), CGUIListContainer::ValidateOffset(), and CGUIPanelContainer::ValidateOffset().
IsScrollingDown()
bool CScroller::IsScrollingDown () const inline
References m_delta.
Referenced by CGUIBaseContainer::GetCacheOffsets(), CGUIBaseContainer::Process(), CGUIPanelContainer::Process(), and CGUIBaseContainer::ScrollingDown().
IsScrollingUp()
bool CScroller::IsScrollingUp () const inline
References m_delta.
Referenced by CGUIBaseContainer::GetCacheOffsets(), and CGUIBaseContainer::ScrollingUp().
operator=()
CScroller & CScroller::operator= (const CScroller & src)
References m_delta, m_duration, m_hasResumePoint, m_pTweener, m_scrollValue, m_startPosition, m_startTime, and right.
ScrollTo()
void CScroller::ScrollTo (float endPos)
Set target value scroller will be scrolling to
Parameters
endPos target
References m_delta, m_hasResumePoint, m_pTweener, m_scrollValue, m_startPosition, and m_startTime.
Referenced by CGUIControlGroupList::ScrollTo(), and CGUIBaseContainer::ScrollToOffset().
SetValue()
void CScroller::SetValue (float scrollValue) inline
References m_scrollValue.
Referenced by CGUIBaseContainer::CalculateLayout(), CGUIPanelContainer::CalculateLayout(), CGUIControlGroupList::ClearAll(), CGUIListContainer::OnMessage(), CGUIBaseContainer::OnMouseEvent(), CGUIControlGroupList::OnMouseEvent(), CGUIBaseContainer::ScrollToOffset(), CGUIControlGroupList::ValidateOffset(), CGUIFixedListContainer::ValidateOffset(), CGUIListContainer::ValidateOffset(), and CGUIPanelContainer::ValidateOffset().
Stop()
void CScroller::Stop () inline
Immediately stop scrolling
References m_delta.
Referenced by CGUIBaseContainer::FreeResources().
Tween()
float CScroller::Tween (float progress) private
References m_hasResumePoint, and m_pTweener.
Referenced by Update().
Update()
bool CScroller::Update (unsigned int time)
Update the scroller to where it would be at the given time point, calculating a new Value.
Parameters
time time point
Returns
True if we are scrolling at given time point
References m_delta, m_duration, m_hasResumePoint, m_scrollValue, m_startPosition, m_startTime, and Tween().
Referenced by CGUIControlGroupList::Process(), CGUIBaseContainer::ScrollToOffset(), and CGUIBaseContainer::UpdateScrollOffset().
Member Data Documentation
m_delta
float CScroller::m_delta private
Brief distance that we have to travel during scroll.
Referenced by CScroller(), IsScrolling(), IsScrollingDown(), IsScrollingUp(), operator=(), ScrollTo(), Stop(), and Update().
m_duration
unsigned int CScroller::m_duration private
Brief duration of scroll.
Referenced by CScroller(), GetDuration(), operator=(), and Update().
m_hasResumePoint
bool CScroller::m_hasResumePoint private
Brief check if we should tween from middle of the tween.
Referenced by CScroller(), operator=(), ScrollTo(), Tween(), and Update().
m_pTweener
std::shared_ptr<Tweener> CScroller::m_pTweener private
Referenced by CScroller(), operator=(), ScrollTo(), and Tween().
m_scrollValue
float CScroller::m_scrollValue private
Referenced by CScroller(), GetValue(), operator=(), ScrollTo(), SetValue(), and Update().
m_startPosition
float CScroller::m_startPosition private
Brief starting position of scroll.
Referenced by CScroller(), operator=(), ScrollTo(), and Update().
m_startTime
unsigned int CScroller::m_startTime private
Brief starting time of scroll.
Referenced by CScroller(), operator=(), ScrollTo(), and Update().
The documentation for this class was generated from the following files:
VisibleEffect.h
VisibleEffect.cpp