Kodi Documentation: CAEPackIEC61937 Class Reference
CAEPackIEC61937 Class Reference
#include <AEPackIEC61937.h>
Public Types
typedef int(* PackFunc) (uint8_t *data, unsigned int size, uint8_t *dest)
Public Member Functions
CAEPackIEC61937 ()=default
Static Public Member Functions
static int PackAC3 (uint8_t *data, unsigned int size, uint8_t *dest)
static int PackEAC3 (uint8_t *data, unsigned int size, uint8_t *dest)
static int PackDTS_512 (uint8_t *data, unsigned int size, uint8_t *dest, bool littleEndian)
static int PackDTS_1024 (uint8_t *data, unsigned int size, uint8_t *dest, bool littleEndian)
static int PackDTS_2048 (uint8_t *data, unsigned int size, uint8_t *dest, bool littleEndian)
static int PackTrueHD (const uint8_t *data, unsigned int size, uint8_t *dest)
static int PackDTSHD (uint8_t *data, unsigned int size, uint8_t *dest, unsigned int period)
static int PackPause (uint8_t *dest, unsigned int millis, unsigned int framesize, unsigned int samplerate, unsigned int rep_period, unsigned int encodedRate)
Private Types
enum IEC61937DataType {
IEC61937_TYPE_NULL = 0x00 , IEC61937_TYPE_AC3 = 0x01 , IEC61937_TYPE_DTS1 = 0x0B , IEC61937_TYPE_DTS2 = 0x0C ,
IEC61937_TYPE_DTS3 = 0x0D , IEC61937_TYPE_DTSHD = 0x11 , IEC61937_TYPE_EAC3 = 0x15 , IEC61937_TYPE_TRUEHD = 0x16
}
Private Member Functions
__pragma (pack(push, 1)) struct IEC61937Packet
Static Private Member Functions
static int PackDTS (uint8_t *data, unsigned int size, uint8_t *dest, bool littleEndian, unsigned int frameSize, uint16_t type)
Member Typedef Documentation
PackFunc
typedef int(* CAEPackIEC61937::PackFunc) (uint8_t *data, unsigned int size, uint8_t *dest)
Member Enumeration Documentation
IEC61937DataType
enum CAEPackIEC61937::IEC61937DataType private
Enumerator
IEC61937_TYPE_NULL
IEC61937_TYPE_AC3
IEC61937_TYPE_DTS1
IEC61937_TYPE_DTS2
IEC61937_TYPE_DTS3
IEC61937_TYPE_DTSHD
IEC61937_TYPE_EAC3
IEC61937_TYPE_TRUEHD
Constructor & Destructor Documentation
CAEPackIEC61937()
CAEPackIEC61937::CAEPackIEC61937 () default
Member Function Documentation
__pragma()
CAEPackIEC61937::__pragma (pack(push, 1)) inline private
References IEC61937_DATA_OFFSET, and MAX_IEC61937_PACKET.
PackAC3()
int CAEPackIEC61937::PackAC3 (uint8_t * data, unsigned int size, uint8_t * dest) static
References AC3_FRAME_SIZE, data(), IEC61937_DATA_OFFSET, IEC61937_PREAMBLE1, IEC61937_PREAMBLE2, IEC61937_TYPE_AC3, OUT_FRAMESTOBYTES, and SwapEndian().
Referenced by CAEBitstreamPacker::Pack().
PackDTS()
int CAEPackIEC61937::PackDTS (uint8_t * data, unsigned int size, uint8_t * dest, bool littleEndian, unsigned int frameSize, uint16_t type) static private
References data(), IEC61937_DATA_OFFSET, IEC61937_PREAMBLE1, IEC61937_PREAMBLE2, and SwapEndian().
Referenced by PackDTS_1024(), PackDTS_2048(), and PackDTS_512().
PackDTS_1024()
int CAEPackIEC61937::PackDTS_1024 (uint8_t * data, unsigned int size, uint8_t * dest, bool littleEndian) static
References data(), DTS2_FRAME_SIZE, IEC61937_TYPE_DTS2, OUT_FRAMESTOBYTES, and PackDTS().
Referenced by CAEBitstreamPacker::Pack().
PackDTS_2048()
int CAEPackIEC61937::PackDTS_2048 (uint8_t * data, unsigned int size, uint8_t * dest, bool littleEndian) static
References data(), DTS3_FRAME_SIZE, IEC61937_TYPE_DTS3, OUT_FRAMESTOBYTES, and PackDTS().
Referenced by CAEBitstreamPacker::Pack().
PackDTS_512()
int CAEPackIEC61937::PackDTS_512 (uint8_t * data, unsigned int size, uint8_t * dest, bool littleEndian) static
References data(), DTS1_FRAME_SIZE, IEC61937_TYPE_DTS1, OUT_FRAMESTOBYTES, and PackDTS().
Referenced by CAEBitstreamPacker::Pack().
PackDTSHD()
int CAEPackIEC61937::PackDTSHD (uint8_t * data, unsigned int size, uint8_t * dest, unsigned int period) static
References data(), IEC61937_DATA_OFFSET, IEC61937_PREAMBLE1, IEC61937_PREAMBLE2, IEC61937_TYPE_DTSHD, and SwapEndian().
Referenced by CAEBitstreamPacker::PackDTSHD().
PackEAC3()
int CAEPackIEC61937::PackEAC3 (uint8_t * data, unsigned int size, uint8_t * dest) static
References data(), EAC3_FRAME_SIZE, IEC61937_DATA_OFFSET, IEC61937_PREAMBLE1, IEC61937_PREAMBLE2, IEC61937_TYPE_EAC3, OUT_FRAMESTOBYTES, and SwapEndian().
Referenced by CAEBitstreamPacker::PackEAC3().
PackPause()
int CAEPackIEC61937::PackPause (uint8_t * dest, unsigned int millis, unsigned int framesize, unsigned int samplerate, unsigned int rep_period, unsigned int encodedRate) static
References IEC61937_PREAMBLE1, IEC61937_PREAMBLE2, and MAX_IEC61937_PACKET.
Referenced by CAEBitstreamPacker::PackPause().
PackTrueHD()
int CAEPackIEC61937::PackTrueHD (const uint8_t * data, unsigned int size, uint8_t * dest) static
References data(), IEC61937_DATA_OFFSET, IEC61937_PREAMBLE1, IEC61937_PREAMBLE2, IEC61937_TYPE_TRUEHD, OUT_FRAMESTOBYTES, SwapEndian(), and TRUEHD_FRAME_SIZE.
Referenced by CAEBitstreamPacker::Pack().
The documentation for this class was generated from the following files:
AEPackIEC61937.h
AEPackIEC61937.cpp