Kodi Documentation: OVERLAY::CRenderer Class Reference
OVERLAY::CRenderer Class Reference
#include <OverlayRenderer.h>
Classes
struct SElement
Public Member Functions
CRenderer ()
virtual ~CRenderer ()
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
void AddOverlay (std::shared_ptr< CDVDOverlay > o, double pts, int index)
virtual void Render (int idx, float depth=0.0f)
void UnInit ()
Release resources.
void Flush ()
void Reset ()
Reset to default values.
void Release (int idx)
bool HasOverlay (int idx)
void SetVideoRect (CRect &source, CRect &dest, CRect &view)
void SetStereoMode (const std::string &stereomode)
void SetSubtitleVerticalPosition (const int value, bool save)
Set the subtitle vertical position, it depends on current screen resolution.
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Protected Types
enum PositonResInfoState { POSRESINFO_UNSET = -1 , POSRESINFO_SAVE_CHANGES = -2 }
Protected Member Functions
void ResetSubtitlePosition ()
Reset the subtitle position to default value.
void OnViewChange ()
Called when the screen resolution is changed.
void Render (COverlay *o)
std::shared_ptr< COverlay > Convert (CDVDOverlay &o, double pts)
std::shared_ptr< COverlay > ConvertLibass (CDVDOverlayLibass &o, double pts, bool updateStyle, const std::shared_ptr< struct KODI::SUBTITLES::STYLE::style > &overlayStyle)
Convert the overlay to a overlay renderer.
void CreateSubtitlesStyle ()
void Release (std::vector< SElement > &list)
void ReleaseCache ()
void ReleaseUnused ()
void LoadSettings ()
Load and store settings locally.
Protected Attributes
CCriticalSection m_section
std::vector< SElement > m_buffers [NUM_BUFFERS]
std::map< unsigned int, std::shared_ptr< COverlay > > m_textureCache
CRect m_rv
CRect m_rs
CRect m_rd
std::string m_stereomode
int m_subtitlePosition {0}
int m_subtitlePosResInfo {POSRESINFO_UNSET}
int m_subtitleVerticalMargin {0}
bool m_saveSubtitlePosition {false}
KODI::SUBTITLES::HorizontalAlign m_subtitleHorizontalAlign
KODI::SUBTITLES::Align m_subtitleAlign {KODI::SUBTITLES::Align::BOTTOM_OUTSIDE}
std::shared_ptr< struct KODI::SUBTITLES::STYLE::style > m_overlayStyle
std::atomic< bool > m_isSettingsChanged {false}
Static Protected Attributes
static unsigned int m_textureid = 1
Member Enumeration Documentation
PositonResInfoState
enum OVERLAY::CRenderer::PositonResInfoState protected
Enumerator
POSRESINFO_UNSET
POSRESINFO_SAVE_CHANGES
Constructor & Destructor Documentation
CRenderer()
CRenderer::CRenderer ()
References CServiceBroker::GetSettingsComponent().
~CRenderer()
CRenderer::~CRenderer () virtual
References Flush(), and CServiceBroker::GetSettingsComponent().
Member Function Documentation
AddOverlay()
void CRenderer::AddOverlay (std::shared_ptr< CDVDOverlay > o, double pts, int index)
References index(), m_buffers, m_section, OVERLAY::CRenderer::SElement::overlay_dvd, and OVERLAY::CRenderer::SElement::pts.
Referenced by CRenderManager::AddOverlay(), and CDebugRenderer::Initialize().
Convert()
std::shared_ptr< COverlay > CRenderer::Convert (CDVDOverlay & o, double pts) protected
References ConvertLibass(), OVERLAY::COverlay::Create(), CreateSubtitlesStyle(), DVDOVERLAY_TYPE_IMAGE, DVDOVERLAY_TYPE_SPU, DVDOVERLAY_TYPE_SSA, DVDOVERLAY_TYPE_TEXT, CDVDOverlayLibass::GetLibassHandler(), CDVDOverlay::IsOverlayType(), LoadSettings(), m_isSettingsChanged, m_overlayStyle, m_rs, m_textureCache, CDVDOverlay::m_textureid, and m_textureid.
Referenced by Render().
ConvertLibass()
std::shared_ptr< COverlay > CRenderer::ConvertLibass (CDVDOverlayLibass & o, double pts, bool updateStyle, const std::shared_ptr< struct KODI::SUBTITLES::STYLE::style > & overlayStyle) protected
Convert the overlay to a overlay renderer.
Parameters
o The overlay to convert
pts The current PTS time
subStyle The style to be used, MUST BE SET ONLY at the first call or when user change settings
Returns
True if success, false if error
References OVERLAY::COverlay::Create(), RESOLUTION_INFO::fPixelRatio, KODI::SUBTITLES::STYLE::renderOpts::frameHeight, KODI::SUBTITLES::STYLE::renderOpts::frameWidth, CWinSystemBase::GetGfxContext(), CDVDOverlayLibass::GetLibassHandler(), CGraphicContext::GetResInfo(), CServiceBroker::GetWinSystem(), CRectGen< T >::Height(), KODI::SUBTITLES::STYLE::renderOpts::horizontalAlignment, CDVDOverlay::IsForcedMargins(), CDVDOverlay::IsTextAlignEnabled(), RESOLUTION_INFO::iSubtitles, KODI::SUBTITLES::STYLE::renderOpts::m_par, m_rd, m_rs, m_rv, m_stereomode, m_subtitleAlign, m_subtitleHorizontalAlign, m_subtitlePosition, m_subtitlePosResInfo, m_subtitleVerticalMargin, m_textureCache, CDVDOverlay::m_textureid, m_textureid, KODI::SUBTITLES::STYLE::renderOpts::marginsMode, RESOLUTION_INFO::Overscan, KODI::SUBTITLES::STYLE::renderOpts::position, POSRESINFO_SAVE_CHANGES, ResetSubtitlePosition(), CGraphicContext::SetResInfo(), KODI::SUBTITLES::STYLE::renderOpts::sourceHeight, KODI::SUBTITLES::STYLE::renderOpts::sourceWidth, OVERSCAN::top, KODI::SUBTITLES::STYLE::renderOpts::videoHeight, KODI::SUBTITLES::STYLE::renderOpts::videoWidth, and CRectGen< T >::Width().
Referenced by Convert().
CreateSubtitlesStyle()
void CRenderer::CreateSubtitlesStyle () protected
References CServiceBroker::GetSettingsComponent(), m_overlayStyle, and KODI::SUBTITLES::STYLE::VIEWPORT_HEIGHT.
Referenced by Convert().
Flush()
void CRenderer::Flush ()
References m_buffers, m_section, Release(), ReleaseCache(), and Reset().
Referenced by CDebugRenderer::Dispose(), CRenderManager::Flush(), UnInit(), and ~CRenderer().
HasOverlay()
bool CRenderer::HasOverlay (int idx)
References m_buffers, and m_section.
Referenced by CRenderManager::IsGuiLayer(), and CRenderManager::Render().
LoadSettings()
void CRenderer::LoadSettings () protected
Load and store settings locally.
References CServiceBroker::GetSettingsComponent(), m_subtitleAlign, m_subtitleHorizontalAlign, and ResetSubtitlePosition().
Referenced by Convert().
Notify()
void CRenderer::Notify (const Observable & obs, const ObservableMessage msg) override virtual
Process a message from an observable.
Parameters
obs The observable that sends the message.
msg The message.
Implements Observer.
References m_isSettingsChanged, m_section, m_subtitlePosResInfo, ObservableMessagePositionChanged, ObservableMessageSettingsChanged, and POSRESINFO_UNSET.
OnViewChange()
void CRenderer::OnViewChange () protected
Called when the screen resolution is changed.
References m_isSettingsChanged.
Referenced by SetVideoRect().
Release() [1/2]
void CRenderer::Release (int idx)
References m_buffers, m_section, and Release().
Referenced by Flush(), CRenderManager::FrameMove(), Release(), and CRenderManager::WaitForBuffer().
Release() [2/2]
void CRenderer::Release (std::vector< SElement > & list) protected
ReleaseCache()
void CRenderer::ReleaseCache () protected
References m_textureCache, and m_textureid.
Referenced by Flush().
ReleaseUnused()
void CRenderer::ReleaseUnused () protected
References m_buffers, and m_textureCache.
Referenced by Render().
Render() [1/2]
void CRenderer::Render (COverlay * o) protected
References OVERLAY::COverlay::ALIGN_SCREEN, OVERLAY::COverlay::ALIGN_SCREEN_AR, OVERLAY::COverlay::ALIGN_SUBTITLE, OVERLAY::COverlay::ALIGN_VIDEO, CWinSystemBase::GetGfxContext(), CGraphicContext::GetResInfo(), OVERLAY::GetStereoscopicDepth(), CServiceBroker::GetWinSystem(), OVERLAY::SRenderState::height, CRectGen< T >::Height(), RESOLUTION_INFO::iSubtitles, OVERLAY::COverlay::m_align, OVERLAY::COverlay::m_height, OVERLAY::COverlay::m_pos, m_rd, m_rs, m_rv, OVERLAY::COverlay::m_source_height, OVERLAY::COverlay::m_source_width, OVERLAY::COverlay::m_width, OVERLAY::COverlay::m_x, OVERLAY::COverlay::m_y, RESOLUTION_INFO::Overscan, OVERLAY::COverlay::POSITION_ABSOLUTE, OVERLAY::COverlay::POSITION_RELATIVE, OVERLAY::COverlay::Render(), OVERSCAN::top, OVERLAY::SRenderState::width, CRectGen< T >::Width(), OVERLAY::SRenderState::x, CRectGen< T >::x1, OVERLAY::SRenderState::y, and CRectGen< T >::y1.
Render() [2/2]
void CRenderer::Render (int idx, float depth = 0.0f) virtual
Reimplemented in CDebugRenderer::CRenderer.
References Convert(), m_buffers, m_section, ReleaseUnused(), and Render().
Referenced by CRenderManager::Render(), Render(), and CDebugRenderer::CRenderer::Render().
Reset()
void CRenderer::Reset ()
Reset to default values.
References m_subtitlePosition, and m_subtitlePosResInfo.
Referenced by CRenderManager::Configure(), and Flush().
ResetSubtitlePosition()
void CRenderer::ResetSubtitlePosition () protected
Reset the subtitle position to default value.
References CServiceBroker::GetAppComponents(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetResInfo(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), CRectGen< T >::Height(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iSubtitles, m_rv, m_saveSubtitlePosition, m_subtitleAlign, m_subtitlePosResInfo, m_subtitleVerticalMargin, RESOLUTION_INFO::Overscan, CApplicationPlayer::SetSubtitleVerticalPosition(), and OVERSCAN::top.
Referenced by ConvertLibass(), and LoadSettings().
SetStereoMode()
void CRenderer::SetStereoMode (const std::string & stereomode)
References m_stereomode.
Referenced by CRenderManager::Configure().
SetSubtitleVerticalPosition()
void CRenderer::SetSubtitleVerticalPosition (const int value, bool save)
Set the subtitle vertical position, it depends on current screen resolution.
Parameters
value The subtitle position in pixels
save If true, the value will be saved to resolution info
References m_saveSubtitlePosition, m_section, m_subtitleAlign, m_subtitlePosition, m_subtitlePosResInfo, POSRESINFO_SAVE_CHANGES, and value.
Referenced by CRenderManager::SetSubtitleVerticalPosition().
SetVideoRect()
void CRenderer::SetVideoRect (CRect & source, CRect & dest, CRect & view)
References m_rd, m_rs, m_rv, and OnViewChange().
Referenced by CRenderManager::Render(), and CDebugRenderer::Render().
UnInit()
void CRenderer::UnInit ()
Release resources.
References Flush(), CDisplaySettings::GetInstance(), CServiceBroker::GetSettingsComponent(), m_saveSubtitlePosition, and CDisplaySettings::UpdateCalibrations().
Referenced by CRenderManager::UnInit().
Member Data Documentation
m_buffers
std::vector<SElement> OVERLAY::CRenderer::m_buffers[NUM_BUFFERS] protected
Referenced by AddOverlay(), Flush(), HasOverlay(), Release(), ReleaseUnused(), and Render().
m_isSettingsChanged
std::atomic<bool> OVERLAY::CRenderer::m_isSettingsChanged {false} protected
Referenced by Convert(), Notify(), and OnViewChange().
m_overlayStyle
std::shared_ptr<struct KODI::SUBTITLES::STYLE::style> OVERLAY::CRenderer::m_overlayStyle protected
Referenced by Convert(), and CreateSubtitlesStyle().
m_rd
CRect OVERLAY::CRenderer::m_rd protected
Referenced by ConvertLibass(), Render(), and SetVideoRect().
m_rs
CRect OVERLAY::CRenderer::m_rs protected
Referenced by Convert(), ConvertLibass(), Render(), and SetVideoRect().
m_rv
CRect OVERLAY::CRenderer::m_rv protected
Referenced by ConvertLibass(), Render(), ResetSubtitlePosition(), and SetVideoRect().
m_saveSubtitlePosition
bool OVERLAY::CRenderer::m_saveSubtitlePosition {false} protected
Referenced by ResetSubtitlePosition(), SetSubtitleVerticalPosition(), and UnInit().
m_section
CCriticalSection OVERLAY::CRenderer::m_section protected
Referenced by AddOverlay(), Flush(), HasOverlay(), Notify(), Release(), Render(), and SetSubtitleVerticalPosition().
m_stereomode
std::string OVERLAY::CRenderer::m_stereomode protected
Referenced by ConvertLibass(), and SetStereoMode().
m_subtitleAlign
KODI::SUBTITLES::Align OVERLAY::CRenderer::m_subtitleAlign {KODI::SUBTITLES::Align::BOTTOM_OUTSIDE} protected
Referenced by ConvertLibass(), LoadSettings(), ResetSubtitlePosition(), and SetSubtitleVerticalPosition().
m_subtitleHorizontalAlign
KODI::SUBTITLES::HorizontalAlign OVERLAY::CRenderer::m_subtitleHorizontalAlign protected
Initial value:
{
        KODI::SUBTITLES::HorizontalAlign::CENTER}
Referenced by ConvertLibass(), and LoadSettings().
m_subtitlePosition
int OVERLAY::CRenderer::m_subtitlePosition {0} protected
Referenced by ConvertLibass(), Reset(), and SetSubtitleVerticalPosition().
m_subtitlePosResInfo
int OVERLAY::CRenderer::m_subtitlePosResInfo {POSRESINFO_UNSET} protected
Referenced by ConvertLibass(), Notify(), Reset(), ResetSubtitlePosition(), and SetSubtitleVerticalPosition().
m_subtitleVerticalMargin
int OVERLAY::CRenderer::m_subtitleVerticalMargin {0} protected
Referenced by ConvertLibass(), and ResetSubtitlePosition().
m_textureCache
std::map<unsigned int, std::shared_ptr<COverlay> > OVERLAY::CRenderer::m_textureCache protected
Referenced by Convert(), ConvertLibass(), ReleaseCache(), and ReleaseUnused().
m_textureid
unsigned int CRenderer::m_textureid = 1 static protected
Referenced by Convert(), ConvertLibass(), and ReleaseCache().
The documentation for this class was generated from the following files:
OverlayRenderer.h
OverlayRenderer.cpp