Kodi Documentation: PVR::CPVRManager Class Reference
PVR::CPVRManager Class Reference
#include <PVRManager.h>
Public Member Functions
CPVRManager ()
Create a new CPVRManager instance, which handles all PVR related operations in XBMC.
~CPVRManager () override
Stop the PVRManager and destroy all objects it created.
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
template<class T >
T & Get ()
Get a PVR component.
std::shared_ptr< CPVRProviders > Providers () const
Get the providers container.
std::shared_ptr< CPVRChannelGroupsContainer > ChannelGroups () const
Get the channel groups container.
std::shared_ptr< CPVRRecordings > Recordings () const
Get the recordings container.
std::shared_ptr< CPVRTimers > Timers () const
Get the timers container.
std::shared_ptr< CPVRClients > Clients () const
Get the timers container.
std::shared_ptr< CPVRClient > GetClient (const CFileItem &item) const
Get the instance of a client that matches the given item.
std::shared_ptr< CPVRClient > GetClient (int iClientId) const
Get the instance of a client that matches the given id.
std::shared_ptr< CPVRPlaybackState > PlaybackState () const
Get access to the pvr playback state.
CPVREpgContainer & EpgContainer ()
Get access to the epg container.
void Init ()
Init PVRManager.
void Start ()
Start the PVRManager, which loads all PVR data and starts some threads to update the PVR data.
void Stop (bool bRestart=false)
Stop PVRManager.
void Unload ()
Stop PVRManager, unload data.
void Deinit ()
Deinit PVRManager, unload data, unload addons.
void OnSleep ()
Propagate event on system sleep.
void OnWake ()
Propagate event on system wake.
std::shared_ptr< CPVRDatabase > GetTVDatabase () const
Get the TV database.
bool IsStarted () const
Check whether the PVRManager has fully started.
void OnPlaybackStarted (const CFileItem &item)
Inform PVR manager that playback of an item just started.
void OnPlaybackStopped (const CFileItem &item)
Inform PVR manager that playback of an item was stopped due to user interaction.
void OnPlaybackEnded (const CFileItem &item)
Inform PVR manager that playback of an item has stopped without user interaction.
void TriggerRecordingsUpdate (int clientId)
Let the background thread update the recordings list.
void TriggerRecordingsUpdate ()
void TriggerRecordingsSizeInProgressUpdate ()
Let the background thread update the size for any in progress recordings.
void TriggerTimersUpdate (int clientId)
Let the background thread update the timer list.
void TriggerTimersUpdate ()
void TriggerChannelsUpdate (int clientId)
Let the background thread update the channel list.
void TriggerChannelsUpdate ()
void TriggerProvidersUpdate (int clientId)
Let the background thread update the provider list.
void TriggerProvidersUpdate ()
void TriggerChannelGroupsUpdate (int clientId)
Let the background thread update the channel groups list.
void TriggerChannelGroupsUpdate ()
void TriggerSearchMissingChannelIcons ()
Let the background thread search for all missing channel icons.
void TriggerCleanupCachedImages ()
Let the background thread erase stale texture db entries and image files.
void TriggerSearchMissingChannelIcons (const std::shared_ptr< CPVRChannelGroup > &group)
Let the background thread search for missing channel icons for channels contained in the given group.
void LocalizationChanged ()
Check whether names are still correct after the language settings changed.
bool IsParentalLocked (const std::shared_ptr< const CPVRChannel > &channel) const
Check if parental lock is overridden at the given moment.
bool IsParentalLocked (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
Check if parental lock is overridden at the given moment.
void RestartParentalTimer ()
Restart the parental timer.
void ConnectionStateChange (CPVRClient *client, const std::string &connectString, PVR_CONNECTION_STATE state, const std::string &message)
Signal a connection change of a client.
CEventStream< PVREvent > & Events ()
Query the events available for CEventStream.
void PublishEvent (PVREvent state)
Publish an event.
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Protected Member Functions
void Process () override
PVR update and control thread.
Private Types
enum class ManagerState {
STATE_ERROR = 0 , STATE_STOPPED , STATE_STARTING , STATE_STOPPING ,
STATE_INTERRUPTED , STATE_STARTED
}
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions
bool SetWakeupCommand ()
Executes "pvrpowermanagement.setwakeupcmd".
bool IsInitialising () const
bool IsStopped () const
Check whether the PVRManager has been stopped.
ManagerState GetState () const
Get the current state of the PVR manager.
void SetState (ManagerState state)
Set the current state of the PVR manager.
void UpdateComponents (ManagerState stateToCheck)
Wait until at least one client is up. Update all data from database and the given PVR clients.
bool UpdateComponents (ManagerState stateToCheck, const std::unique_ptr< CPVRGUIProgressHandler > &progressHandler)
Update all data from database and the given PVR clients.
void UnloadComponents ()
Unload all PVR data (recordings, timers, channelgroups).
bool IsKnownClient (int clientID) const
Check whether the given client id belongs to a known client.
void ResetProperties ()
Reset all properties.
void Clear ()
Destroy PVRManager's objects.
void TriggerPlayChannelOnStartup ()
Continue playback on the last played channel.
bool IsCurrentlyParentalLocked (const std::shared_ptr< const CPVRChannel > &channel, bool bGenerallyLocked) const
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Attributes
CEventSource< PVREvent > m_events
containers
std::shared_ptr< CPVRProviders > m_providers
std::shared_ptr< CPVRChannelGroupsContainer > m_channelGroups
std::shared_ptr< CPVRRecordings > m_recordings
std::shared_ptr< CPVRTimers > m_timers
std::shared_ptr< CPVRClients > m_addons
std::unique_ptr< CPVRGUIInfo > m_guiInfo
std::shared_ptr< CPVRComponentRegistration > m_components
std::unique_ptr< CPVREpgContainer > m_epgContainer
std::vector< std::shared_ptr< CPVRClient > > m_knownClients
std::unique_ptr< CPVRManagerJobQueue > m_pendingUpdates
std::shared_ptr< CPVRDatabase > m_database
CCriticalSection m_critSection
bool m_bFirstStart = true
CCriticalSection m_managerStateMutex
ManagerState m_managerState = ManagerState::STATE_STOPPED
std::unique_ptr< CStopWatch > m_parentalTimer
CCriticalSection m_startStopMutex
const std::shared_ptr< CPVRPlaybackState > m_playbackState
CPVRGUIActionListener m_actionListener
CPVRSettings m_settings
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Member Enumeration Documentation
ManagerState
enum class PVR::CPVRManager::ManagerState strong private
Enumerator
STATE_ERROR
STATE_STOPPED
STATE_STARTING
STATE_STOPPING
STATE_INTERRUPTED
STATE_STARTED
Constructor & Destructor Documentation
CPVRManager()
CPVRManager::CPVRManager ()
Create a new CPVRManager instance, which handles all PVR related operations in XBMC.
References CSettings::SETTING_PVRPARENTAL_DURATION, CSettings::SETTING_PVRPARENTAL_ENABLED, CSettings::SETTING_PVRPOWERMANAGEMENT_ENABLED, and CSettings::SETTING_PVRPOWERMANAGEMENT_SETWAKEUPCMD.
~CPVRManager()
CPVRManager::~CPVRManager () override
Stop the PVRManager and destroy all objects it created.
References PVR::CPVRGUIActionListener::Deinit(), CServiceBroker::GetAnnouncementManager(), LOGDEBUG, LOGPVR, and m_actionListener.
Member Function Documentation
Announce()
void CPVRManager::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References ANNOUNCEMENT::GUI, IsStarted(), and m_addons.
ChannelGroups()
std::shared_ptr< CPVRChannelGroupsContainer > CPVRManager::ChannelGroups () const
Get the channel groups container.
Returns
The groups container.
References m_channelGroups, and m_critSection.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonChannelGroups(), PVR::CGUIDialogPVRGroupManager::ActionButtonHideGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonNewGroup(), PVR::CGUIWindowPVRProvidersBase::ActivateChannelsWindow(), PVR::CGUIWindowPVRBase::ActivateNextChannelGroup(), PVR::CGUIWindowPVRBase::ActivatePreviousChannelGroup(), PVR::CPVRClient::cb_transfer_channel_group_member(), PVR::CPVRClient::cb_transfer_timer_entry(), PVR::CPVRRecording::Channel(), PVR::CGUIDialogPVRGroupManager::ClearGroupThumbnails(), PVR::CPVRTimerInfoTag::CreateFromEpg(), JSONRPC::CPVROperations::GetBroadcasts(), PVR::CPVRItem::GetChannel(), JSONRPC::CPVROperations::GetChannelDetails(), JSONRPC::CPVROperations::GetChannelGroupDetails(), PVR::CPVRGUIActionsChannels::GetChannelGroupMember(), anonymous_namespace{PVRGUIDirectory.cpp}::GetChannelGroupMembers(), JSONRPC::CPVROperations::GetChannelGroups(), PVR::CPVRGUIDirectory::GetChannelGroupsDirectory(), PVR::CPVRChannelSwitchingInputHandler::GetChannelNumbers(), JSONRPC::CPVROperations::GetChannels(), PVR::CPVRTimerInfoTag::GetEpgInfoTag(), anonymous_namespace{PVRGUIDirectory.cpp}::GetFirstMatchingGroupMember(), anonymous_namespace{PVRPlaybackState.cpp}::GetFirstNonDeletedAndNonHiddenChannelGroup(), anonymous_namespace{PVRGUIDirectory.cpp}::GetLastWatchedChannelGroupMember(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRItem::GetNextEpgInfoTag(), PVR::CPVRGUIDirectory::GetProvidersDirectory(), PVR::CPVRGUIActionsChannels::GetSelectedChannelPath(), PVR::CGUIWindowPVRGuideBase::GotoCurrentProgramme(), PVR::CGUIWindowPVRGuideBase::GotoPlayingChannel(), PVR::CPVRGUIActionsChannels::HideChannel(), PVR::CGUIWindowPVRBase::InitChannelGroup(), PVR::CGUIWindowPVRGuideBase::InitEpgGridControl(), PVR::CGUIPVRChannelGroupsSelector::Initialize(), PVR::CGUIDialogPVRTimerSettings::InitializeChannelsList(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadChannelItem(), PVR::CPVREpgSearchFilter::MatchChannelGroup(), PVR::CPVREpgSearchFilter::MatchFreeToAir(), PVR::CGUIDialogPVRChannelsOSD::OnAction(), PVR::CGUIDialogPVRChannelManager::OnContextButton(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CPVRGUIActionListener::OnSettingAction(), JSONRPC::CPlayerOperations::Open(), CInputStreamPVRChannel::OpenPVRStream(), PVR::CPVRGUIActionsPlayback::PlayChannelOnStartup(), PVR::CPVRGUIActionsPlayback::PlayMedia(), JSONRPC::CPVROperations::Record(), PVR::CPVRPlaybackState::ReInit(), PVR::CGUIDialogPVRChannelManager::SaveList(), PVR::CPVRPlaybackState::SetActiveChannelGroup(), PVR::CPVRChannelSwitchingInputHandler::SwitchToChannel(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), TriggerChannelGroupsUpdate(), TriggerChannelGroupsUpdate(), TriggerChannelsUpdate(), TriggerChannelsUpdate(), TriggerCleanupCachedImages(), TriggerSearchMissingChannelIcons(), PVR::CGUIDialogPVRChannelManager::Update(), PVR::CGUIDialogPVRGroupManager::Update(), anonymous_namespace{PVRGUIActionsChannels.cpp}::UpdateActiveGroup(), PVR::CGUIWindowPVRChannelsBase::UpdateButtons(), PVR::CGUIDialogPVRChannelManager::UpdateChannelData(), PVR::CGUIDialogPVRGuideSearch::UpdateChannelSpin(), PVR::CGUIDialogPVRGuideSearch::UpdateGroupsSpin(), PVR::CPVRPlaybackState::UpdateLastWatched(), PVR::CPVRGUIInfo::UpdateMisc(), and PVR::CPVRGUITimesInfo::UpdatePlayingTag().
Clear()
void CPVRManager::Clear () private
Destroy PVRManager's objects.
References m_channelGroups, m_critSection, m_database, m_guiInfo, m_parentalTimer, m_pendingUpdates, m_playbackState, m_providers, m_recordings, and m_timers.
Referenced by ResetProperties(), and Unload().
Clients()
std::shared_ptr< CPVRClients > CPVRManager::Clients () const
Get the timers container.
Returns
The timers container.
References m_addons.
Referenced by ConnectionStateChange(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncEmptyRecordingsTrash::DoRun(), PVR::CPVRTimerType::GetAllTypes(), JSONRPC::CPVROperations::GetClients(), PVR::CPVRChannelGroup::GetLastPlayedChannelGroupMember(), PVR::CPVRGUIInfo::GetPVRInt(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), Init(), PVR::CGUIDialogPVRTimerSettings::InitializeChannelsList(), PVR::CGUIDialogPVRClientPriorities::InitializeSettings(), PVR::CGUIDialogPVRTimerSettings::InitializeSettings(), PVR::CPVRSettings::IsSettingVisible(), PVR::CPVRChannelGroup::LoadFromDatabase(), PVR::CPVREpgSearchFilter::MatchChannel(), PVR::CPVRGUIActionListener::OnSettingChanged(), PVR::CPVRGUIActionsClients::ProcessSettingsMenuHooks(), PVR::CPVRGUIActionsChannels::StartChannelScan(), PVR::CPVRClient::StopRunningInstance(), PVR::CGUIDialogPVRTimerSettings::TypesFiller(), PVR::CGUIDialogPVRChannelManager::Update(), PVR::CPVRGUIInfo::UpdateBackendCache(), PVR::CPVRGUIInfo::UpdateDescrambleData(), PVR::CPVRProviders::UpdateFromClients(), PVR::CPVRRecordings::UpdateFromClients(), PVR::CPVRTimers::UpdateFromClients(), PVR::CPVRChannelGroupAllChannels::UpdateFromClients(), PVR::CPVRChannelGroupFromClient::UpdateFromClients(), PVR::CPVRChannelGroups::UpdateFromClients(), PVR::CPVRChannelGroup::UpdateMembersClientPriority(), PVR::CPVRGUIInfo::UpdateQualityData(), and PVR::CPVRChannelGroupSettings::UpdateUseBackendChannelNumbers().
ConnectionStateChange()
void CPVRManager::ConnectionStateChange (CPVRClient * client, const std::string & connectString, PVR_CONNECTION_STATE state, const std::string & message)
Signal a connection change of a client.
References Clients(), and CServiceBroker::GetJobManager().
Referenced by PVR::CPVRClient::cb_connection_state_change().
Deinit()
void CPVRManager::Deinit ()
Deinit PVRManager, unload data, unload addons.
References m_addons, SetWakeupCommand(), and Unload().
EpgContainer()
CPVREpgContainer & CPVRManager::EpgContainer ()
Get access to the epg container.
Returns
The epg container.
References m_epgContainer.
Referenced by JSONRPC::CPVROperations::AddTimer(), anonymous_namespace{PVRTimers.cpp}::AddTimerRuleToEpgMap(), PVR::CPVRClient::cb_epg_event_state_change(), PVR::CPVRClient::cb_trigger_epg_update(), PVR::CPVRGUIActionsEPG::ChooseIconForSavedSearch(), PVR::CPVRChannel::CreateEPG(), PVR::CPVRGUIActionsEPG::DeleteSavedSearch(), PVR::CPVRGUIActionsEPG::DuplicateSavedSearch(), PVR::CPVREpgSearch::Execute(), PVR::CGUIWindowPVRSearchBase::ExecuteSearch(), JSONRPC::CPVROperations::GetBroadcastDetails(), JSONRPC::CPVROperations::GetBroadcastIsPlayable(), anonymous_namespace{PVRTimers.cpp}::GetEpgTagsForTimerRule(), PVR::CGUIEPGGridContainerModel::GetGridStartPadding(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRPlaybackState::GetNextAutoplayItem(), PVR::CPVRGUIDirectory::GetSavedSearchesDirectory(), PVR::CPVRGUIDirectory::GetSavedSearchResults(), PVR::CGUIWindowPVRSearchBase::OnMessage(), JSONRPC::CPlayerOperations::Open(), PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), PVR::CGUIWindowPVRGuideBase::RefreshTimelineItems(), PVR::CPVRPlaybackState::ReInit(), PVR::CPVRChannelGroupAllChannels::RemoveDeletedGroupMembers(), PVR::CPVRGUIActionsEPG::RenameSavedSearch(), PVR::CPVRClient::ResetProperties(), PVR::CGUIWindowPVRSearchBase::SetSearchFilter(), JSONRPC::CPVROperations::ToggleTimer(), TriggerCleanupCachedImages(), PVR::CGUIDialogPVRGuideSearch::Update(), and PVR::CPVRTimers::UpdateEntries().
Events()
CEventStream< PVREvent > & PVR::CPVRManager::Events () inline
Query the events available for CEventStream.
References m_events.
Referenced by PVR::CGUIWindowPVRBase::CGUIWindowPVRBase(), PVR::CPVRGUIActionListener::Deinit(), PVR::CPVRGUIActionListener::Init(), PVR::CPVRChannelGroups::LoadFromDatabase(), CDirectoryProvider::Reset(), PVR::CPVRTimers::Start(), PVR::CPVRTimers::Stop(), PVR::CPVRChannelGroups::Unload(), PVR::CGUIDialogPVRChannelsOSD::Update(), CDirectoryProvider::UpdateURL(), and PVR::CGUIWindowPVRBase::~CGUIWindowPVRBase().
Get()
template<class T > T & PVR::CPVRManager::Get () inline
Get a PVR component.
Returns
The component.
References m_components.
Referenced by PVR::CGUIWindowPVRTimersBase::ActionShowTimer(), PVR::CPVRGUIActionsTimers::AnnounceReminder(), PVR::CGUIDialogPVRChannelsOSD::CGUIDialogPVRChannelsOSD(), PVR::CGUIWindowPVRChannelsBase::CGUIWindowPVRChannelsBase(), PVR::CGUIWindowPVRGuideBase::CGUIWindowPVRGuideBase(), PVR::CPVRSettings::CheckParentalPin(), CApplicationPowerHandling::CheckShutdown(), CSaveFileState::DoWork(), JSONRPC::CPVROperations::GetChannelDetails(), PVR::CPVRGUIInfo::GetFallbackLabel(), CFileItem::GetItemToPlay(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), JSONRPC::CPVROperations::GetPropertyValue(), CWindowTranslator::GetVirtualWindow(), PVR::CGUIDialogPVRChannelsOSD::GotoChannel(), KODI::UTILS::GUILIB::CGUIContentUtils::HasInfoForItem(), PVR::CGUIWindowPVRGuideBase::InitEpgGridControl(), CApplication::OnAction(), PVR::CPVRGUIActionListener::OnAction(), CGUIWindowLoginScreen::OnAction(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonFind(), PVR::CGUIDialogPVRRecordingInfo::OnClickButtonFind(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonPlay(), PVR::CGUIWindowPVRRecordingsBase::OnContextButtonDeleteAll(), PVR::CGUIDialogPVRChannelsOSD::OnDeinitWindow(), PVR::CPVRGUIActionsUtils::OnInfo(), anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnInfoSelected(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnPlaySelected(), anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoPlayActionProcessor::OnPlaySelected(), anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnResumeSelected(), anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoPlayActionProcessor::OnResumeSelected(), PVR::CPVRGUIActionListener::OnSettingAction(), JSONRPC::CPlayerOperations::Open(), PVR::CGUIPVRRecordingsPlayActionProcessor::Play(), PVR::CPVRGUIActionsPlayback::PlayEpgTag(), PlayerControl(), CApplication::PlayMedia(), PVR::CGUIDialogPVRItemsViewBase::ShowInfo(), KODI::UTILS::GUILIB::CGUIContentUtils::ShowInfoForItem(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), PVR::CPVRGUIChannelNavigator::SwitchToCurrentChannel(), ToggleRecordPlayingChannel(), JSONRPC::CPVROperations::ToggleTimer(), PVR::CGUIDialogPVRChannelsOSD::Update(), PVR::CGUIWindowPVRBase::UpdateSelectedItemPath(), PVR::CGUIWindowPVRGuideBase::UpdateSelectedItemPath(), CVideoLibraryMarkWatchedJob::Work(), PVR::CGUIWindowPVRChannelsBase::~CGUIWindowPVRChannelsBase(), and PVR::CGUIWindowPVRGuideBase::~CGUIWindowPVRGuideBase().
GetClient() [1/2]
std::shared_ptr< CPVRClient > CPVRManager::GetClient (const CFileItem & item) const
Get the instance of a client that matches the given item.
Parameters
item The item containing a PVR recording, a PVR channel, a PVR timer or a PVR EPG event.
Returns
the requested client on success, nullptr otherwise.
References GetClient(), CFileItem::GetEPGInfoTag(), PVR::CPVRChannelsPath::GetGroupClientID(), CFileItem::GetPath(), CFileItem::GetPVRChannelInfoTag(), CFileItem::GetPVRRecordingInfoTag(), CFileItem::GetPVRTimerInfoTag(), CFileItem::HasEPGInfoTag(), CFileItem::HasPVRChannelInfoTag(), CFileItem::HasPVRRecordingInfoTag(), CFileItem::HasPVRTimerInfoTag(), URIUtils::IsPVRChannel(), URIUtils::IsPVRChannelGroup(), URIUtils::IsPVRRecording(), m_channelGroups, m_recordings, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by anonymous_namespace{PVRGUIActionsTimers.cpp}::AddEventLogEntry(), PVR::CPVRTimerInfoTag::AddToClient(), PVR::CPVRGUIActionsTimers::AnnounceReminder(), PVR::CGUIDialogPVRRecordingSettings::CanEditRecording(), PVR::CPVRChannel::CanRecord(), PVR::CPVRRecording::CPVRRecording(), PVR::CPVRTimerInfoTag::CPVRTimerInfoTag(), PVR::CPVRTimerInfoTag::CPVRTimerInfoTag(), PVR::CPVRChannelGroupAllChannelsSingleClient::CreateMissingGroups(), PVR::CPVRRecording::Delete(), PVR::CPVRTimerInfoTag::DeleteFromClient(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncSetRecordingPlayCount::DoRun(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncSetRecordingLifetime::DoRun(), PVR::CPVRGUIActionsPowerManagement::EventOccursOnLocalBackend(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::Execute(), PVR::CPVRGUIDirectory::GetChannelsDirectory(), GetClient(), PVR::CPVRChannelGroup::GetClientPriority(), PVR::CPVREpgInfoTag::GetEdl(), PVR::CPVRRecording::GetEdl(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRProviders::GetProviders(), PVR::CPVRRecording::GetResumePoint(), PVR::CPVRRecording::IncrementPlayCount(), PVR::CGUIDialogPVRRecordingSettings::InitializeSettings(), PVR::CPVREpgInfoTag::IsPlayable(), PVR::CPVREpgInfoTag::IsRecordable(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible(), PVR::CGUIDialogPVRRecordingSettings::LifetimesFiller(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), PVR::CGUIDialogPVRChannelManager::OnContextButton(), PVR::CPVRPlaybackState::OnPlaybackStarted(), PVR::CPVRGUIActionsPlayback::PlayEpgTag(), CInputStreamPVRBase::ProvidesStreamForMetaDataExtraction(), PVR::CPVRRecording::Rename(), PVR::CGUIDialogPVRChannelManager::RenameChannel(), PVR::CPVRChannelGroupMember::SetGroupName(), PVR::CPVRRecording::SetPlayCount(), PVR::CPVRGUIActionsTimers::SetRecordingOnChannel(), PVR::CPVRRecording::SetResumePoint(), PVR::CPVRRecording::SetResumePoint(), PVR::CPVRPlaybackState::StartPlayback(), TriggerChannelGroupsUpdate(), TriggerChannelsUpdate(), TriggerProvidersUpdate(), TriggerRecordingsUpdate(), TriggerTimersUpdate(), PVR::CPVRRecording::Undelete(), PVR::CGUIDialogPVRChannelManager::Update(), PVR::CGUIDialogPVRGroupManager::Update(), PVR::CPVRTimers::UpdateEntries(), PVR::CPVRChannelGroupFromClient::UpdateFromClients(), PVR::CPVREpg::UpdateFromScraper(), PVR::CPVRTimerInfoTag::UpdateOnClient(), and PVR::CPVRRecording::UpdateRecordingSize().
GetClient() [2/2]
std::shared_ptr< CPVRClient > CPVRManager::GetClient (int iClientId) const
Get the instance of a client that matches the given id.
Parameters
iClientId The id of a PVR client.
Returns
the requested client on success, nullptr otherwise.
References m_addons.
GetState()
CPVRManager::ManagerState CPVRManager::GetState () const private
Get the current state of the PVR manager.
Returns
the state.
References m_managerState, and m_managerStateMutex.
Referenced by IsInitialising(), IsStarted(), IsStopped(), UpdateComponents(), and UpdateComponents().
GetTVDatabase()
std::shared_ptr< CPVRDatabase > CPVRManager::GetTVDatabase () const
Get the TV database.
Returns
The TV database.
References LOGERROR, m_critSection, and m_database.
Referenced by PVR::CPVRChannelGroup::Delete(), PVR::CPVRProvider::DeleteFromDatabase(), PVR::CPVRTimerInfoTag::DeleteFromDatabase(), PVR::CPVRChannelGroup::DeleteGroupMembersFromDb(), PVR::CPVRClient::GetDateTimeFirstChannelsAdded(), PVR::CPVRClient::GetPriority(), PVR::CPVRProviders::LoadFromDatabase(), PVR::CPVRTimers::LoadFromDatabase(), PVR::CPVRChannel::Persist(), PVR::CPVRTimerInfoTag::Persist(), PVR::CPVRProvider::Persist(), PVR::CPVRChannel::QueueDelete(), PVR::CPVRChannelGroupAllChannels::RemoveDeletedGroupMembers(), PVR::CPVRClient::SetDateTimeFirstChannelsAdded(), PVR::CPVRChannel::SetLastWatched(), and PVR::CPVRClient::SetPriority().
Init()
void CPVRManager::Init ()
Init PVRManager.
References Clients(), and CServiceBroker::GetJobManager().
Referenced by CProfileManager::FinalizeLoadProfile().
IsCurrentlyParentalLocked()
bool CPVRManager::IsCurrentlyParentalLocked (const std::shared_ptr< const CPVRChannel > & channel, bool bGenerallyLocked) const private
References PVR::CPVRSettings::GetBoolValue(), PVR::CPVRSettings::GetIntValue(), m_parentalTimer, m_playbackState, m_settings, CSettings::SETTING_PVRPARENTAL_DURATION, and CSettings::SETTING_PVRPARENTAL_ENABLED.
Referenced by IsParentalLocked(), and IsParentalLocked().
IsInitialising()
bool PVR::CPVRManager::IsInitialising () const inline private
Returns
True while the PVRManager is initialising.
References GetState(), and STATE_STARTING.
Referenced by Process(), and Start().
IsKnownClient()
bool CPVRManager::IsKnownClient (int clientID) const private
Check whether the given client id belongs to a known client.
Returns
True if the client is known, false otherwise.
References m_knownClients.
Referenced by TriggerChannelGroupsUpdate(), TriggerChannelsUpdate(), TriggerProvidersUpdate(), TriggerRecordingsUpdate(), TriggerTimersUpdate(), and UpdateComponents().
IsParentalLocked() [1/2]
bool CPVRManager::IsParentalLocked (const std::shared_ptr< const CPVRChannel > & channel) const
Check if parental lock is overridden at the given moment.
Parameters
channel The channel to check.
Returns
True if parental lock is overridden, false otherwise.
References IsCurrentlyParentalLocked().
Referenced by PVR::CPVREpgSearchFilter::MatchSearchTerm(), and PVR::CPVRGUIActionsTimers::SetRecordingOnChannel().
IsParentalLocked() [2/2]
bool CPVRManager::IsParentalLocked (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const
Check if parental lock is overridden at the given moment.
Parameters
epgTag The epg tag to check.
Returns
True if parental lock is overridden, false otherwise.
References IsCurrentlyParentalLocked(), and m_channelGroups.
IsStarted()
bool PVR::CPVRManager::IsStarted () const inline
Check whether the PVRManager has fully started.
Returns
True if started, false otherwise.
References GetState(), and STATE_STARTED.
Referenced by Announce(), JSONRPC::CPVROperations::GetPropertyValue(), PVR::CPVRGUIDirectory::HasDeletedRadioRecordings(), PVR::CPVRGUIDirectory::HasDeletedTVRecordings(), PVR::CPVRGUIDirectory::HasRadioRecordings(), PVR::CPVRGUIDirectory::HasTVRecordings(), LocalizationChanged(), CApplication::OnAction(), Process(), TriggerPlayChannelOnStartup(), and PVR::CPVRGUIInfo::UpdateMisc().
IsStopped()
bool PVR::CPVRManager::IsStopped () const inline private
Check whether the PVRManager has been stopped.
Returns
True if stopped, false otherwise.
References GetState(), and STATE_STOPPED.
Referenced by Stop().
LocalizationChanged()
void CPVRManager::LocalizationChanged ()
Check whether names are still correct after the language settings changed.
References IsStarted(), m_channelGroups, and m_critSection.
Referenced by CLangInfo::SetLanguage().
OnPlaybackEnded()
void CPVRManager::OnPlaybackEnded (const CFileItem & item)
Inform PVR manager that playback of an item has stopped without user interaction.
Parameters
item The item that ended to play.
References PVR::ChannelPlaybackStopped, m_epgContainer, m_playbackState, and PublishEvent().
Referenced by CApplication::OnMessage().
OnPlaybackStarted()
void CPVRManager::OnPlaybackStarted (const CFileItem & item)
Inform PVR manager that playback of an item just started.
Parameters
item The item that started to play.
References m_epgContainer, and m_playbackState.
Referenced by CApplication::OnMessage().
OnPlaybackStopped()
void CPVRManager::OnPlaybackStopped (const CFileItem & item)
Inform PVR manager that playback of an item was stopped due to user interaction.
Parameters
item The item that stopped to play.
References PVR::ChannelPlaybackStopped, m_epgContainer, m_playbackState, and PublishEvent().
Referenced by CApplication::OnMessage().
OnSleep()
void CPVRManager::OnSleep ()
Propagate event on system sleep.
References m_addons, m_epgContainer, PublishEvent(), SetWakeupCommand(), and PVR::SystemSleep.
Referenced by CPowerManager::OnSleep().
OnWake()
void CPVRManager::OnWake ()
Propagate event on system wake.
References m_addons, m_epgContainer, PublishEvent(), PVR::SystemWake, TriggerChannelGroupsUpdate(), TriggerChannelsUpdate(), TriggerPlayChannelOnStartup(), TriggerProvidersUpdate(), TriggerRecordingsUpdate(), TriggerSearchMissingChannelIcons(), and TriggerTimersUpdate().
Referenced by CPowerManager::OnWake().
PlaybackState()
std::shared_ptr< CPVRPlaybackState > CPVRManager::PlaybackState () const
Get access to the pvr playback state.
Returns
The playback state.
References m_playbackState.
Referenced by PVR::CPVRGUIInfo::CharInfoEncryption(), JSONRPC::CPlayerOperations::GetActivePlayers(), PVR::CPVRGUIActionsChannels::GetChannelGroupMember(), PVR::CPVRChannelSwitchingInputHandler::GetChannelNumbers(), JSONRPC::CPlayerOperations::GetCurrentEpg(), PVR::CPVREpgInfoTag::GetCurrentPlayingTime(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIChannelNavigator::GetNextOrPrevChannel(), JSONRPC::CPVROperations::GetPropertyValue(), PVR::CPVRGUIActionsChannels::GetSelectedChannelPath(), PVR::CGUIWindowPVRGuideBase::GotoCurrentProgramme(), PVR::CGUIWindowPVRGuideBase::GotoPlayingChannel(), PVR::CGUIWindowPVRBase::InitChannelGroup(), PVR::CGUIWindowPVRGuideBase::InitEpgGridControl(), JSONRPC::CPlayerOperations::IsPVRChannel(), PVR::CGUIDialogPVRChannelsOSD::OnAction(), PVR::CPVRGUIActionListener::OnAction(), PVR::CGUIDialogPVRChannelGuide::OnInitWindow(), PVR::CGUIDialogPVRRadioRDSInfo::OnMessage(), PVR::CPVRGUIActionsPlayback::PlayChannelOnStartup(), PVR::CPVRGUIActionsPlayback::PlayEpgTag(), PVR::CPVRGUIActionsPlayback::PlayRecording(), JSONRPC::CPVROperations::Record(), PVR::CPVREpgTagsCache::Refresh(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), PVR::CPVRGUIActionsPlayback::SeekBackward(), PVR::CPVRGUIActionsPlayback::SeekForward(), PVR::CGUIWindowPVRBase::SetChannelGroup(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), PVR::CPVRChannelSwitchingInputHandler::SwitchToChannel(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), PVR::CPVRChannelSwitchingInputHandler::SwitchToPreviousChannel(), PVR::CPVRGUIActionsTimers::ToggleRecordingOnPlayingChannel(), PVR::CGUIDialogPVRChannelsOSD::Update(), PVR::CGUIDialogPVRGroupManager::Update(), anonymous_namespace{PVRGUIActionsChannels.cpp}::UpdateActiveGroup(), PVR::CPVRGUIInfo::UpdateDescrambleData(), PVR::CGUIDialogPVRRadioRDSInfo::UpdateInfoControls(), PVR::CPVRGUIInfo::UpdateMisc(), PVR::CPVRGUITimesInfo::UpdatePlayingTag(), PVR::CPVRGUIInfo::UpdateQualityData(), and PVR::CPVRGUITimesInfo::UpdateTimeshiftData().
Process()
void CPVRManager::Process (void) override protected virtual
PVR update and control thread.
Reimplemented from CThread.
References IsInitialising(), IsStarted(), CLog::Log(), LOGERROR, LOGINFO, m_addons, m_bFirstStart, m_critSection, m_database, m_epgContainer, m_guiInfo, m_pendingUpdates, m_playbackState, m_timers, ResetProperties(), SetState(), STATE_INTERRUPTED, STATE_STARTED, STATE_STARTING, STATE_STOPPED, TriggerCleanupCachedImages(), TriggerPlayChannelOnStartup(), TriggerRecordingsSizeInProgressUpdate(), TriggerSearchMissingChannelIcons(), UnloadComponents(), and UpdateComponents().
Providers()
std::shared_ptr< CPVRProviders > CPVRManager::Providers () const
Get the providers container.
Returns
The providers container.
References m_critSection, and m_providers.
Referenced by PVR::CPVRChannel::GetDefaultProvider(), PVR::CPVRRecording::GetDefaultProvider(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRChannel::GetProvider(), PVR::CPVRRecording::GetProvider(), PVR::UTILS::GetProviderNameFromPath(), PVR::CPVRGUIDirectory::GetProvidersDirectory(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), TriggerCleanupCachedImages(), TriggerProvidersUpdate(), TriggerProvidersUpdate(), and PVR::CGUIWindowPVRProvidersBase::UpdateButtons().
PublishEvent()
void CPVRManager::PublishEvent (PVREvent state)
Publish an event.
Parameters
state the event
References m_events, and CEventSource< Event >::Publish().
Referenced by PVR::CPVRRecordings::ChangeRecordingsPlayCount(), PVR::CPVRChannelGroups::GroupStateChanged(), PVR::CPVRGUIInfo::InitCurrentItem(), PVR::CPVRTimers::NotifyTimersEvent(), PVR::CPVRThumbLoader::OnLoaderFinish(), OnPlaybackEnded(), OnPlaybackStopped(), OnSleep(), OnWake(), PVR::CPVRChannelGroups::ResetGroupPositions(), PVR::CPVRRecordings::ResetResumePoint(), PVR::CPVRClient::SetPriority(), SetState(), PVR::CPVRChannelGroups::SortGroups(), UpdateComponents(), PVR::CPVRTimers::UpdateEntries(), PVR::CPVRRecordings::UpdateFromClients(), PVR::CPVRChannelGroups::UpdateFromClients(), and PVR::CPVRRecordings::UpdateInProgressSize().
Recordings()
std::shared_ptr< CPVRRecordings > CPVRManager::Recordings () const
Get the recordings container.
Returns
The recordings container.
References m_critSection, and m_recordings.
Referenced by anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording::DoRun(), JSONRPC::CFileItemHandler::GetField(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIDirectory::GetProvidersDirectory(), PVR::CPVRItem::GetRecording(), JSONRPC::CPVROperations::GetRecordingDetails(), JSONRPC::CPVROperations::GetRecordingFileItem(), JSONRPC::CPVROperations::GetRecordings(), PVR::CPVRGUIDirectory::GetRecordingsDirectory(), PVR::CPVRGUIDirectory::HasDeletedRadioRecordings(), PVR::CPVRGUIDirectory::HasDeletedTVRecordings(), PVR::CPVRGUIDirectory::HasRadioRecordings(), PVR::CPVRGUIDirectory::HasTVRecordings(), JSONRPC::CPlayerOperations::Open(), CInputStreamPVRRecording::OpenPVRStream(), PVR::CPVRGUIActionsPlayback::PlayMedia(), PVR::CPVRPlaybackState::ReInit(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), TriggerCleanupCachedImages(), TriggerRecordingsSizeInProgressUpdate(), TriggerRecordingsUpdate(), TriggerRecordingsUpdate(), PVR::CGUIWindowPVRRecordingsBase::UpdateButtons(), PVR::CPVRGUIInfo::UpdateMisc(), and CVideoLibraryResetResumePointJob::Work().
ResetProperties()
void CPVRManager::ResetProperties () private
Reset all properties.
References Clear(), m_channelGroups, m_critSection, m_database, m_guiInfo, m_knownClients, m_parentalTimer, m_providers, m_recordings, and m_timers.
Referenced by Process().
RestartParentalTimer()
void CPVRManager::RestartParentalTimer ()
Restart the parental timer.
References m_parentalTimer.
Referenced by PVR::CPVRGUIActionsParentalControl::CheckParentalPIN().
SetState()
void CPVRManager::SetState (CPVRManager::ManagerState state) private
Set the current state of the PVR manager.
Parameters
state the new state.
References m_managerState, m_managerStateMutex, PVR::ManagerError, PVR::ManagerInterrupted, PVR::ManagerStarted, PVR::ManagerStarting, PVR::ManagerStopped, PublishEvent(), STATE_ERROR, STATE_INTERRUPTED, STATE_STARTED, STATE_STARTING, STATE_STOPPED, and STATE_STOPPING.
Referenced by Process(), Start(), and Stop().
SetWakeupCommand()
bool CPVRManager::SetWakeupCommand () private
Executes "pvrpowermanagement.setwakeupcmd".
References CDateTime::GetAsTime(), PVR::CPVRSettings::GetBoolValue(), PVR::CPVRSettings::GetStringValue(), CDateTime::IsValid(), LOGERROR, m_settings, m_timers, CSettings::SETTING_PVRPOWERMANAGEMENT_ENABLED, and CSettings::SETTING_PVRPOWERMANAGEMENT_SETWAKEUPCMD.
Referenced by Deinit(), and OnSleep().
Start()
void CPVRManager::Start ()
Start the PVRManager, which loads all PVR data and starts some threads to update the PVR data.
References BELOW_NORMAL, CThread::Create(), IsInitialising(), CLog::Log(), LOGINFO, m_addons, m_startStopMutex, CThread::SetPriority(), SetState(), STATE_STARTING, and Stop().
Referenced by PVR::CPVRGUIActionsDatabase::ResetDatabase(), and PVR::CPVRClients::UpdateClients().
Stop()
void CPVRManager::Stop (bool bRestart = false)
Stop PVRManager.
References CServiceBroker::GetAppMessenger(), IsStopped(), CLog::Log(), LOGDEBUG, LOGINFO, LOGPVR, m_playbackState, m_startStopMutex, SetState(), STATE_STOPPING, CThread::StopThread(), and TMSG_MEDIA_STOP.
Referenced by CProfileManager::LogOff(), CProfileManager::PrepareLoadProfile(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), Start(), PVR::CPVRClient::StopRunningInstance(), Unload(), and PVR::CPVRClients::UpdateClients().
Timers()
std::shared_ptr< CPVRTimers > CPVRManager::Timers () const
Get the timers container.
Returns
The timers container.
References m_critSection, and m_timers.
Referenced by PVR::CPVRGUIActionsTimers::AddTimer(), PVR::CPVRGUIActionsPowerManagement::AllLocalBackendsIdle(), PVR::CPVRGUIAnyTimerInfo::AmountActiveRecordings(), PVR::CPVRGUITVTimerInfo::AmountActiveRecordings(), PVR::CPVRGUIRadioTimerInfo::AmountActiveRecordings(), PVR::CPVRGUIAnyTimerInfo::AmountActiveTimers(), PVR::CPVRGUITVTimerInfo::AmountActiveTimers(), PVR::CPVRGUIRadioTimerInfo::AmountActiveTimers(), PVR::CPVRGUIActionsTimers::AnnounceReminders(), PVR::CPVRGUIActionsTimers::DeleteTimer(), PVR::CPVRGUIActionsTimers::DeleteTimer(), JSONRPC::CPVROperations::DeleteTimer(), PVR::CPVRGUIAnyTimerInfo::GetActiveRecordings(), PVR::CPVRGUITVTimerInfo::GetActiveRecordings(), PVR::CPVRGUIRadioTimerInfo::GetActiveRecordings(), JSONRPC::CFileItemHandler::GetField(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIAnyTimerInfo::GetNextActiveTimer(), PVR::CPVRGUITVTimerInfo::GetNextActiveTimer(), PVR::CPVRGUIRadioTimerInfo::GetNextActiveTimer(), PVR::CPVRRecording::GetRecordingTimer(), JSONRPC::CPVROperations::GetTimerDetails(), PVR::CPVRItem::GetTimerInfoTag(), PVR::CONTEXTMENUITEM::GetTimerInfoTagFromItem(), PVR::CPVRGUIActionsTimers::GetTimerRule(), JSONRPC::CPVROperations::GetTimers(), PVR::CPVRGUIDirectory::GetTimersDirectory(), PVR::CPVRPlaybackState::IsRecording(), PVR::CPVRPlaybackState::IsRecordingOnPlayingChannel(), JSONRPC::CPVROperations::Record(), PVR::CPVRGUIActionsTimers::SetRecordingOnChannel(), JSONRPC::CPVROperations::ToggleTimer(), TriggerTimersUpdate(), and TriggerTimersUpdate().
TriggerChannelGroupsUpdate() [1/2]
void CPVRManager::TriggerChannelGroupsUpdate ()
References ChannelGroups(), and m_pendingUpdates.
Referenced by OnWake().
TriggerChannelGroupsUpdate() [2/2]
void CPVRManager::TriggerChannelGroupsUpdate (int clientId)
Let the background thread update the channel groups list.
Parameters
clientId The id of the PVR client to update.
References ChannelGroups(), GetClient(), IsKnownClient(), and m_pendingUpdates.
Referenced by PVR::CPVRClient::cb_trigger_channel_groups_update().
TriggerChannelsUpdate() [1/2]
void CPVRManager::TriggerChannelsUpdate ()
References ChannelGroups(), and m_pendingUpdates.
Referenced by OnWake().
TriggerChannelsUpdate() [2/2]
void CPVRManager::TriggerChannelsUpdate (int clientId)
Let the background thread update the channel list.
Parameters
clientId The id of the PVR client to update.
References ChannelGroups(), GetClient(), IsKnownClient(), and m_pendingUpdates.
Referenced by PVR::CPVRClient::cb_trigger_channel_update().
TriggerCleanupCachedImages()
void CPVRManager::TriggerCleanupCachedImages ()
Let the background thread erase stale texture db entries and image files.
References ChannelGroups(), PVR::CPVREpgContainer::CleanupCachedImages(), EpgContainer(), CLog::Log(), LOGINFO, m_pendingUpdates, Providers(), and Recordings().
Referenced by Process().
TriggerPlayChannelOnStartup()
void CPVRManager::TriggerPlayChannelOnStartup () private
Continue playback on the last played channel.
References CServiceBroker::GetJobManager(), and IsStarted().
Referenced by OnWake(), and Process().
TriggerProvidersUpdate() [1/2]
void CPVRManager::TriggerProvidersUpdate ()
References m_pendingUpdates, and Providers().
Referenced by OnWake().
TriggerProvidersUpdate() [2/2]
void CPVRManager::TriggerProvidersUpdate (int clientId)
Let the background thread update the provider list.
Parameters
clientId The id of the PVR client to update.
References GetClient(), IsKnownClient(), m_pendingUpdates, and Providers().
Referenced by PVR::CPVRClient::cb_trigger_provider_update().
TriggerRecordingsSizeInProgressUpdate()
void CPVRManager::TriggerRecordingsSizeInProgressUpdate ()
Let the background thread update the size for any in progress recordings.
References m_pendingUpdates, and Recordings().
Referenced by Process().
TriggerRecordingsUpdate() [1/2]
void CPVRManager::TriggerRecordingsUpdate ()
References m_pendingUpdates, and Recordings().
Referenced by OnWake().
TriggerRecordingsUpdate() [2/2]
void CPVRManager::TriggerRecordingsUpdate (int clientId)
Let the background thread update the recordings list.
Parameters
clientId The id of the PVR client to update.
References GetClient(), IsKnownClient(), m_pendingUpdates, and Recordings().
Referenced by PVR::CPVRClient::cb_trigger_recording_update(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction::Run(), and PVR::CPVRGUIActionsTimers::StopRecording().
TriggerSearchMissingChannelIcons() [1/2]
void CPVRManager::TriggerSearchMissingChannelIcons ()
Let the background thread search for all missing channel icons.
References ChannelGroups(), m_pendingUpdates, and PVR::CPVRGUIChannelIconUpdater::SearchAndUpdateMissingChannelIcons().
Referenced by PVR::CPVRGUIActionListener::OnSettingAction(), OnWake(), Process(), SearchMissingIcons(), and PVR::CPVRChannelGroups::UpdateFromClients().
TriggerSearchMissingChannelIcons() [2/2]
void CPVRManager::TriggerSearchMissingChannelIcons (const std::shared_ptr< CPVRChannelGroup > & group)
Let the background thread search for missing channel icons for channels contained in the given group.
Parameters
group The channel group.
References m_pendingUpdates.
TriggerTimersUpdate() [1/2]
void CPVRManager::TriggerTimersUpdate ()
References m_pendingUpdates, and Timers().
Referenced by OnWake().
TriggerTimersUpdate() [2/2]
void CPVRManager::TriggerTimersUpdate (int clientId)
Let the background thread update the timer list.
Parameters
clientId The id of the PVR client to update.
References GetClient(), IsKnownClient(), m_pendingUpdates, and Timers().
Referenced by PVR::CPVRClient::cb_trigger_timer_update(), and PVR::CPVRTimers::Notify().
Unload()
void CPVRManager::Unload ()
Stop PVRManager, unload data.
References Clear(), and Stop().
Referenced by Deinit().
UnloadComponents()
void CPVRManager::UnloadComponents () private
Unload all PVR data (recordings, timers, channelgroups).
References m_channelGroups, m_epgContainer, m_providers, m_recordings, and m_timers.
Referenced by Process().
UpdateComponents() [1/2]
void CPVRManager::UpdateComponents (ManagerState stateToCheck) private
Wait until at least one client is up. Update all data from database and the given PVR clients.
Parameters
stateToCheck Required state of the PVR manager while this method gets called.
References g_localizeStrings, CLocalizeStrings::Get(), GetState(), m_addons, CThread::Sleep(), and UpdateComponents().
Referenced by Process(), and UpdateComponents().
UpdateComponents() [2/2]
bool CPVRManager::UpdateComponents (ManagerState stateToCheck, const std::unique_ptr< CPVRGUIProgressHandler > & progressHandler) private
Update all data from database and the given PVR clients.
Parameters
stateToCheck Required state of the PVR manager while this method gets called.
progressHandler The progress handler to use for showing the different stages.
Returns
True if at least one client is known and successfully loaded, false otherwise.
References PVR::ClientsInvalidated, g_localizeStrings, CLocalizeStrings::Get(), GetState(), IsKnownClient(), LOGDEBUG, LOGERROR, LOGPVR, m_addons, m_channelGroups, m_knownClients, m_playbackState, m_providers, m_recordings, m_timers, and PublishEvent().
Member Data Documentation
m_actionListener
CPVRGUIActionListener PVR::CPVRManager::m_actionListener private
Referenced by ~CPVRManager().
m_addons
std::shared_ptr<CPVRClients> PVR::CPVRManager::m_addons private
pointer to the pvr addon container
Referenced by Announce(), Clients(), Deinit(), GetClient(), OnSleep(), OnWake(), Process(), Start(), UpdateComponents(), and UpdateComponents().
m_bFirstStart
bool PVR::CPVRManager::m_bFirstStart = true private
true when the PVR manager was started first, false otherwise
Referenced by Process().
m_channelGroups
std::shared_ptr<CPVRChannelGroupsContainer> PVR::CPVRManager::m_channelGroups private
pointer to the channel groups container
Referenced by ChannelGroups(), Clear(), GetClient(), IsParentalLocked(), LocalizationChanged(), ResetProperties(), UnloadComponents(), and UpdateComponents().
m_components
std::shared_ptr<CPVRComponentRegistration> PVR::CPVRManager::m_components private
pointer to the PVR components
Referenced by Get().
m_critSection
CCriticalSection PVR::CPVRManager::m_critSection mutable private
critical section for all changes to this class, except for changes to triggers
Referenced by ChannelGroups(), Clear(), GetTVDatabase(), LocalizationChanged(), Process(), Providers(), Recordings(), ResetProperties(), and Timers().
m_database
std::shared_ptr<CPVRDatabase> PVR::CPVRManager::m_database private
the database for all PVR related data
Referenced by Clear(), GetTVDatabase(), Process(), and ResetProperties().
m_epgContainer
std::unique_ptr<CPVREpgContainer> PVR::CPVRManager::m_epgContainer private
the epg container
Referenced by EpgContainer(), OnPlaybackEnded(), OnPlaybackStarted(), OnPlaybackStopped(), OnSleep(), OnWake(), Process(), and UnloadComponents().
m_events
CEventSource<PVREvent> PVR::CPVRManager::m_events private
Referenced by Events(), and PublishEvent().
m_guiInfo
std::unique_ptr<CPVRGUIInfo> PVR::CPVRManager::m_guiInfo private
pointer to the guiinfo data
Referenced by Clear(), Process(), and ResetProperties().
m_knownClients
std::vector<std::shared_ptr<CPVRClient> > PVR::CPVRManager::m_knownClients private
vector with all known clients
Referenced by IsKnownClient(), ResetProperties(), and UpdateComponents().
m_managerState
ManagerState PVR::CPVRManager::m_managerState = ManagerState::STATE_STOPPED private
Referenced by GetState(), and SetState().
m_managerStateMutex
CCriticalSection PVR::CPVRManager::m_managerStateMutex mutable private
Referenced by GetState(), and SetState().
m_parentalTimer
std::unique_ptr<CStopWatch> PVR::CPVRManager::m_parentalTimer private
Referenced by Clear(), IsCurrentlyParentalLocked(), ResetProperties(), and RestartParentalTimer().
m_pendingUpdates
std::unique_ptr<CPVRManagerJobQueue> PVR::CPVRManager::m_pendingUpdates private
vector of pending pvr updates
Referenced by Clear(), Process(), TriggerChannelGroupsUpdate(), TriggerChannelGroupsUpdate(), TriggerChannelsUpdate(), TriggerChannelsUpdate(), TriggerCleanupCachedImages(), TriggerProvidersUpdate(), TriggerProvidersUpdate(), TriggerRecordingsSizeInProgressUpdate(), TriggerRecordingsUpdate(), TriggerRecordingsUpdate(), TriggerSearchMissingChannelIcons(), TriggerSearchMissingChannelIcons(), TriggerTimersUpdate(), and TriggerTimersUpdate().
m_playbackState
const std::shared_ptr<CPVRPlaybackState> PVR::CPVRManager::m_playbackState private
Referenced by Clear(), IsCurrentlyParentalLocked(), OnPlaybackEnded(), OnPlaybackStarted(), OnPlaybackStopped(), PlaybackState(), Process(), Stop(), and UpdateComponents().
m_providers
std::shared_ptr<CPVRProviders> PVR::CPVRManager::m_providers private
pointer to the providers container
Referenced by Clear(), Providers(), ResetProperties(), UnloadComponents(), and UpdateComponents().
m_recordings
std::shared_ptr<CPVRRecordings> PVR::CPVRManager::m_recordings private
pointer to the recordings container
Referenced by Clear(), GetClient(), Recordings(), ResetProperties(), UnloadComponents(), and UpdateComponents().
m_settings
CPVRSettings PVR::CPVRManager::m_settings private
Referenced by IsCurrentlyParentalLocked(), and SetWakeupCommand().
m_startStopMutex
CCriticalSection PVR::CPVRManager::m_startStopMutex private
Referenced by Start(), and Stop().
m_timers
std::shared_ptr<CPVRTimers> PVR::CPVRManager::m_timers private
pointer to the timers container
Referenced by Clear(), Process(), ResetProperties(), SetWakeupCommand(), Timers(), UnloadComponents(), and UpdateComponents().
The documentation for this class was generated from the following files:
PVRManager.h
PVRManager.cpp