Kodi Documentation: CNfoFile Class Reference
CNfoFile Class Reference
#include <NfoFile.h>
Public Member Functions
virtual ~CNfoFile ()
CInfoScanner::INFO_TYPE Create (const std::string &, const ADDON::ScraperPtr &, int episode=-1)
template<class T >
bool GetDetails (T &details, const char *document=NULL, bool prioritise=false)
void Close ()
void SetScraperInfo (ADDON::ScraperPtr info)
ADDON::ScraperPtr GetScraperInfo ()
const CScraperUrl & ScraperUrl () const
Static Public Member Functions
static int Scrape (ADDON::ScraperPtr &scraper, CScraperUrl &url, const std::string &content)
static std::vector< ADDON::ScraperPtr > GetScrapers (ADDON::AddonType type, const ADDON::ScraperPtr &selectedScraper)
Private Member Functions
int Load (const std::string &)
Private Attributes
std::string m_doc
size_t m_headPos = 0
ADDON::ScraperPtr m_info
ADDON::AddonType m_type {}
CScraperUrl m_scurl
Constructor & Destructor Documentation
~CNfoFile()
virtual CNfoFile::~CNfoFile () inline virtual
References Close().
Member Function Documentation
Close()
void CNfoFile::Close ()
References CScraperUrl::Clear(), m_doc, m_headPos, and m_scurl.
Referenced by Load(), and ~CNfoFile().
Create()
CInfoScanner::INFO_TYPE CNfoFile::Create (const std::string & strPath, const ADDON::ScraperPtr & info, int episode = -1)
References CInfoScanner::COMBINED_NFO, CInfoScanner::ERROR_NFO, CInfoScanner::FULL_NFO, GetDetails(), GetScrapers(), CScraperUrl::HasUrls(), Load(), m_doc, m_headPos, CVideoInfoTag::m_iEpisode, m_info, m_scurl, m_type, CInfoScanner::NO_NFO, CInfoScanner::OVERRIDE_NFO, CVideoInfoTag::Reset(), Scrape(), ADDON::ScraperTypeFromContent(), and CInfoScanner::URL_NFO.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CVideoTagLoaderNFO::Load(), and CVideoTagLoaderFFmpeg::LoadMKV().
GetDetails()
template<class T > bool CNfoFile::GetDetails (T & details, const char * document = NULL, bool prioritise = false) inline
References m_doc, m_headPos, and CXBMCTinyXML::Parse().
Referenced by Create(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CVideoTagLoaderNFO::Load(), and CVideoTagLoaderFFmpeg::LoadMKV().
GetScraperInfo()
ADDON::ScraperPtr CNfoFile::GetScraperInfo () inline
References m_info.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), and CVideoTagLoaderNFO::Load().
GetScrapers()
std::vector< ScraperPtr > CNfoFile::GetScrapers (ADDON::AddonType type, const ADDON::ScraperPtr & selectedScraper) static
References addons, CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetAddons(), and ADDON::CAddonSystemSettings::GetInstance().
Referenced by Create().
Load()
int CNfoFile::Load (const std::string & strFile) private
References Close(), m_doc, and m_headPos.
Referenced by Create().
Scrape()
int CNfoFile::Scrape (ADDON::ScraperPtr & scraper, CScraperUrl & url, const std::string & content) static
References ADDON::content, ADDON::CScraperError::FAborted(), CScraperUrl::HasUrls(), and CVideoInfoDownloader::ShowErrorDialog().
Referenced by Create().
ScraperUrl()
const CScraperUrl & CNfoFile::ScraperUrl () const inline
References m_scurl.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CVideoTagLoaderNFO::Load(), and CVideoTagLoaderFFmpeg::LoadMKV().
SetScraperInfo()
void CNfoFile::SetScraperInfo (ADDON::ScraperPtr info) inline
References m_info.
Member Data Documentation
m_doc
std::string CNfoFile::m_doc private
Referenced by Close(), Create(), GetDetails(), and Load().
m_headPos
size_t CNfoFile::m_headPos = 0 private
Referenced by Close(), Create(), GetDetails(), and Load().
m_info
ADDON::ScraperPtr CNfoFile::m_info private
Referenced by Create(), GetScraperInfo(), and SetScraperInfo().
m_scurl
CScraperUrl CNfoFile::m_scurl private
Referenced by Close(), Create(), and ScraperUrl().
m_type
ADDON::AddonType CNfoFile::m_type {} private
Referenced by Create().
The documentation for this class was generated from the following files:
NfoFile.h
NfoFile.cpp