Kodi Documentation: CONTEXTMENU::CVideoPlayUsing Struct Reference
CONTEXTMENU::CVideoPlayUsing Struct Reference
#include <ContextMenus.h>
Public Member Functions
CVideoPlayUsing ()
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &_item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Constructor & Destructor Documentation
CVideoPlayUsing()
CONTEXTMENU::CVideoPlayUsing::CVideoPlayUsing () inline
Member Function Documentation
Execute()
bool CONTEXTMENU::CVideoPlayUsing::Execute (const std::shared_ptr< CFileItem > & _item) const override virtual
Implements IContextMenuItem.
IsVisible()
bool CONTEXTMENU::CVideoPlayUsing::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References CServiceBroker::GetPlayerCoreFactory(), CServiceBroker::GetSettingsComponent(), CFileItem::HasVideoVersions(), KODI::VIDEO::UTILS::IsItemPlayable(), CFileItem::IsLiveTV(), and CSettings::SETTING_VIDEOLIBRARY_SHOWVIDEOVERSIONSASFOLDER.
The documentation for this struct was generated from the following files:
video/ContextMenus.h
video/ContextMenus.cpp