Kodi Documentation: CRemoteControlXbox Class Reference
CRemoteControlXbox Class Reference
#include <RemoteControlXbox.h>
Public Member Functions
CRemoteControlXbox ()
virtual ~CRemoteControlXbox ()
void Initialize ()
void Disconnect ()
bool IsRemoteDevice (const std::wstring &deviceId) const
Private Member Functions
void HandleAcceleratorKey (const winrt::Windows::UI::Core::CoreDispatcher &, const winrt::Windows::UI::Core::AcceleratorKeyEventArgs &)
void HandleMediaButton (const winrt::Windows::Media::SystemMediaTransportControlsButtonPressedEventArgs &)
int32_t TranslateVirtualKey (winrt::Windows::System::VirtualKey vk)
int32_t TranslateMediaKey (winrt::Windows::Media::SystemMediaTransportControlsButton mk)
Private Attributes
bool m_bInitialized
std::chrono::time_point< std::chrono::steady_clock > m_firstClickTime
uint32_t m_repeatCount
winrt::event_token m_token
winrt::event_token m_mediatoken
Constructor & Destructor Documentation
CRemoteControlXbox()
CRemoteControlXbox::CRemoteControlXbox ()
~CRemoteControlXbox()
CRemoteControlXbox::~CRemoteControlXbox () virtual
References Disconnect(), and m_bInitialized.
Member Function Documentation
Disconnect()
void CRemoteControlXbox::Disconnect ()
References m_bInitialized, m_mediatoken, and m_token.
Referenced by ~CRemoteControlXbox().
HandleAcceleratorKey()
void CRemoteControlXbox::HandleAcceleratorKey (const winrt::Windows::UI::Core::CoreDispatcher & , const winrt::Windows::UI::Core::AcceleratorKeyEventArgs &) private
References XBMC_ButtonEvent::button, CServiceBroker::GetAppPort(), CServiceBroker::GetSettingsComponent(), XBMC_ButtonEvent::holdtime, XBMC_Event::keybutton, m_firstClickTime, m_repeatCount, TranslateVirtualKey(), XBMC_Event::type, and XBMC_BUTTON.
Referenced by Initialize().
HandleMediaButton()
void CRemoteControlXbox::HandleMediaButton (const winrt::Windows::Media::SystemMediaTransportControlsButtonPressedEventArgs &) private
References XBMC_ButtonEvent::button, CServiceBroker::GetAppPort(), XBMC_ButtonEvent::holdtime, XBMC_Event::keybutton, TranslateMediaKey(), XBMC_Event::type, and XBMC_BUTTON.
Referenced by Initialize().
Initialize()
void CRemoteControlXbox::Initialize ()
References HandleAcceleratorKey(), HandleMediaButton(), IsRemoteDevice(), m_bInitialized, m_mediatoken, and m_token.
IsRemoteDevice()
bool CRemoteControlXbox::IsRemoteDevice (const std::wstring & deviceId) const
References XBOX_REMOTE_DEVICE_ID.
Referenced by Initialize().
TranslateMediaKey()
int32_t CRemoteControlXbox::TranslateMediaKey (winrt::Windows::Media::SystemMediaTransportControlsButton mk) private
References XINPUT_IR_REMOTE_CHANNEL_MINUS, XINPUT_IR_REMOTE_CHANNEL_PLUS, XINPUT_IR_REMOTE_FORWARD, XINPUT_IR_REMOTE_PAUSE, XINPUT_IR_REMOTE_PLAY, XINPUT_IR_REMOTE_RECORD, XINPUT_IR_REMOTE_REVERSE, XINPUT_IR_REMOTE_SKIP_MINUS, XINPUT_IR_REMOTE_SKIP_PLUS, and XINPUT_IR_REMOTE_STOP.
Referenced by HandleMediaButton().
TranslateVirtualKey()
int32_t CRemoteControlXbox::TranslateVirtualKey (winrt::Windows::System::VirtualKey vk) private
References LOGDEBUG, XINPUT_IR_REMOTE_0, XINPUT_IR_REMOTE_1, XINPUT_IR_REMOTE_2, XINPUT_IR_REMOTE_3, XINPUT_IR_REMOTE_4, XINPUT_IR_REMOTE_5, XINPUT_IR_REMOTE_6, XINPUT_IR_REMOTE_7, XINPUT_IR_REMOTE_8, XINPUT_IR_REMOTE_9, XINPUT_IR_REMOTE_BACK, XINPUT_IR_REMOTE_CHANNEL_MINUS, XINPUT_IR_REMOTE_CHANNEL_PLUS, XINPUT_IR_REMOTE_CLEAR, XINPUT_IR_REMOTE_CONTENTS_MENU, XINPUT_IR_REMOTE_DISPLAY, XINPUT_IR_REMOTE_DOWN, XINPUT_IR_REMOTE_INFO, XINPUT_IR_REMOTE_LEFT, XINPUT_IR_REMOTE_MENU, XINPUT_IR_REMOTE_RIGHT, XINPUT_IR_REMOTE_SELECT, XINPUT_IR_REMOTE_STAR, and XINPUT_IR_REMOTE_UP.
Referenced by HandleAcceleratorKey().
Member Data Documentation
m_bInitialized
bool CRemoteControlXbox::m_bInitialized private
Referenced by Disconnect(), Initialize(), and ~CRemoteControlXbox().
m_firstClickTime
std::chrono::time_point<std::chrono::steady_clock> CRemoteControlXbox::m_firstClickTime private
Referenced by HandleAcceleratorKey().
m_mediatoken
winrt::event_token CRemoteControlXbox::m_mediatoken private
Referenced by Disconnect(), and Initialize().
m_repeatCount
uint32_t CRemoteControlXbox::m_repeatCount private
Referenced by HandleAcceleratorKey().
m_token
winrt::event_token CRemoteControlXbox::m_token private
Referenced by Disconnect(), and Initialize().
The documentation for this class was generated from the following files:
RemoteControlXbox.h
RemoteControlXbox.cpp