Kodi Documentation: CGUIViewControl Class Reference
CGUIViewControl Class Reference
#include <GUIViewControl.h>
Public Member Functions
CGUIViewControl ()
virtual ~CGUIViewControl ()
void Reset ()
void SetParentWindow (int window)
void AddView (const CGUIControl *control)
void SetViewControlID (int control)
void SetCurrentView (int viewMode, bool bRefresh=false)
void SetItems (CFileItemList &items)
void SetSelectedItem (int item)
void SetSelectedItem (const std::string &itemPath)
int GetSelectedItem () const
std::string GetSelectedItemPath () const
void SetFocused ()
bool HasControl (int controlID) const
int GetNextViewMode (int direction=1) const
int GetViewModeNumber (int number) const
int GetViewModeCount () const
int GetViewModeByID (int id) const
int GetCurrentControl () const
void Clear ()
Protected Types
typedef std::vector< CGUIControl * >::const_iterator ciViews
Protected Member Functions
int GetSelectedItem (const CGUIControl *control) const
void UpdateContents (const CGUIControl *control, int currentItem) const
void UpdateView ()
void UpdateViewAsControl (const std::string &viewLabel)
void UpdateViewVisibility ()
int GetView (VIEW_TYPE type, int id) const
Protected Attributes
std::vector< CGUIControl * > m_allViews
std::vector< CGUIControl * > m_visibleViews
CFileItemList * m_fileItems
int m_viewAsControl
int m_parentWindow
int m_currentView
Member Typedef Documentation
ciViews
typedef std::vector<CGUIControl*>::const_iterator CGUIViewControl::ciViews protected
Constructor & Destructor Documentation
CGUIViewControl()
CGUIViewControl::CGUIViewControl (void)
References m_fileItems, m_parentWindow, m_viewAsControl, Reset(), and WINDOW_INVALID.
~CGUIViewControl()
CGUIViewControl::~CGUIViewControl () virtual default
Member Function Documentation
AddView()
void CGUIViewControl::AddView (const CGUIControl * control)
References CGUIControl::IsContainer(), and m_allViews.
Referenced by CGUIMediaWindow::Load(), CGUIDialogColorPicker::OnWindowLoaded(), CGUIDialogFileBrowser::OnWindowLoaded(), CGUIDialogSelect::OnWindowLoaded(), PVR::CGUIDialogPVRChannelManager::OnWindowLoaded(), PVR::CGUIDialogPVRGroupManager::OnWindowLoaded(), PVR::CGUIDialogPVRItemsViewBase::OnWindowLoaded(), CGUIDialogVideoBookmarks::OnWindowLoaded(), and CGUIWindowLoginScreen::OnWindowLoaded().
Clear()
void CGUIViewControl::Clear ()
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_RESET, m_currentView, m_parentWindow, m_visibleViews, and CGUIWindowManager::SendMessage().
Referenced by PVR::CGUIDialogPVRChannelManager::Clear(), PVR::CGUIDialogPVRGroupManager::Clear(), PVR::CGUIDialogPVRItemsViewBase::Clear(), CGUIDialogVideoBookmarks::Clear(), CGUIDialogFileBrowser::ClearFileItems(), CGUIMediaWindow::ClearFileItems(), CGUIDialogColorPicker::OnDeinitWindow(), CGUIDialogSelect::OnDeinitWindow(), and CGUIMediaWindow::OnFilterItems().
GetCurrentControl()
int CGUIViewControl::GetCurrentControl () const
References m_currentView, and m_visibleViews.
Referenced by ADDON::CGUIAddonWindow::GetCurrentContainerControlId(), CGUIDialogColorPicker::GetFirstFocusableControl(), CGUIDialogFileBrowser::GetFirstFocusableControl(), CGUIDialogSelect::GetFirstFocusableControl(), PVR::CGUIDialogPVRItemsViewBase::GetFirstFocusableControl(), CGUIDialogVideoBookmarks::GetFirstFocusableControl(), CGUIMediaWindow::GetFirstFocusableControl(), PVR::CGUIWindowPVRGuideBase::GetGridControl(), CGUIDialogFileBrowser::GetViewContainerID(), CGUIMediaWindow::GetViewContainerID(), CGUIWindowLoginScreen::GetViewContainerID(), ADDON::CGUIAddonWindow::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogSelect::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIMediaWindow::OnMessage(), and CGUIWindowLoginScreen::OnMessage().
GetNextViewMode()
int CGUIViewControl::GetNextViewMode (int direction = 1) const
References CGUIControl::GetID(), IGUIContainer::GetType(), m_currentView, and m_visibleViews.
Referenced by CGUIMediaWindow::OnMessage().
GetSelectedItem() [1/2]
int CGUIViewControl::GetSelectedItem () const
References GetSelectedItem(), m_currentView, and m_visibleViews.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonChannelGroups(), PVR::CGUIDialogPVRGroupManager::ActionButtonGroupMembers(), PVR::CGUIDialogPVRGroupManager::ActionButtonUngroupedChannels(), CGUIDialogFileBrowser::FrameMove(), CGUIWindowLoginScreen::FrameMove(), CGUIDialogFileBrowser::GetCurrentListItem(), CGUIMediaWindow::GetCurrentListItem(), CGUIWindowLoginScreen::GetCurrentListItem(), ADDON::CGUIAddonWindow::GetCurrentListPosition(), GetSelectedItem(), GetSelectedItemPath(), CGUIDialogFileBrowser::OnAction(), CGUIWindowFavourites::OnAction(), CGUIWindowMusicBase::OnAction(), CGUIWindowMusicNav::OnAction(), CGUIWindowMusicPlayList::OnAction(), PVR::CGUIDialogPVRChannelsOSD::OnAction(), PVR::CGUIDialogPVRItemsViewBase::OnAction(), PVR::CGUIWindowPVRRecordingsBase::OnAction(), CGUIDialogVideoBookmarks::OnAction(), CGUIWindowVideoBase::OnAction(), CGUIWindowVideoNav::OnAction(), CGUIWindowVideoPlaylist::OnAction(), PVR::CGUIDialogPVRChannelManager::OnActionMove(), PVR::CGUIDialogPVRGroupManager::OnActionMove(), PVR::CGUIDialogPVRChannelManager::OnClickListChannels(), KODI::GAME::CGUIWindowGames::OnClickMsg(), CGUIWindowVideoNav::OnDeleteItem(), CGUIWindowEventLog::OnEventRemoved(), CGUIMediaWindow::OnFilterItems(), CGUIWindowAddonBrowser::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogSelect::OnMessage(), CGUIWindowEventLog::OnMessage(), CGUIWindowFavourites::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowLoginScreen::OnMessage(), CGUIWindowLoginScreen::OnPopupMenu(), CGUIWindowMusicPlaylistEditor::OnSourcesContext(), CGUIWindowMusicPlayList::SavePlayList(), CGUIMediaWindow::SaveSelectedItemInHistory(), CGUIWindowVideoNav::SelectFirstUnwatched(), SetCurrentView(), PVR::CGUIWindowPVRChannelsBase::ShowChannelManager(), CGUIWindowVideoBase::ShowInfoAndRefresh(), PVR::CGUIDialogPVRGroupManager::Update(), CGUIDialogFileBrowser::Update(), PVR::CGUIWindowPVRBase::Update(), CGUIMediaWindow::UpdateFileList(), and UpdateView().
GetSelectedItem() [2/2]
int CGUIViewControl::GetSelectedItem (const CGUIControl * control) const protected
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIMessage::GetParam1(), CGUIComponent::GetWindowManager(), GUI_MSG_ITEM_SELECTED, m_fileItems, m_parentWindow, CGUIWindowManager::SendMessage(), and CFileItemList::Size().
GetSelectedItemPath()
std::string CGUIViewControl::GetSelectedItemPath () const
References CFileItemList::Get(), GetSelectedItem(), m_currentView, m_fileItems, and m_visibleViews.
Referenced by PVR::CGUIDialogPVRChannelsOSD::OnDeinitWindow(), PVR::CGUIDialogPVRChannelsOSD::SaveSelectedItemPath(), and PVR::CGUIWindowPVRBase::UpdateSelectedItemPath().
GetView()
int CGUIViewControl::GetView (VIEW_TYPE type, int id) const protected
References CGUIControl::GetID(), IGUIContainer::GetType(), id, m_visibleViews, and VIEW_TYPE_NONE.
Referenced by SetCurrentView().
GetViewModeByID()
int CGUIViewControl::GetViewModeByID (int id) const
References CGUIControl::GetID(), IGUIContainer::GetType(), id, and m_visibleViews.
Referenced by CGUIMediaWindow::OnMessage().
GetViewModeCount()
int CGUIViewControl::GetViewModeCount () const
References m_visibleViews.
Referenced by CGUIMediaWindow::GetViewCount().
GetViewModeNumber()
int CGUIViewControl::GetViewModeNumber (int number) const
References CGUIControl::GetID(), IGUIContainer::GetType(), and m_visibleViews.
Referenced by CGUIMediaWindow::OnMessage().
HasControl()
bool CGUIViewControl::HasControl (int controlID) const
References m_allViews.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonChannelGroups(), PVR::CGUIDialogPVRGroupManager::ActionButtonGroupMembers(), PVR::CGUIDialogPVRGroupManager::ActionButtonUngroupedChannels(), CGUIWindowLoginScreen::FrameMove(), CGUIDialogColorPicker::GetFirstFocusableControl(), CGUIDialogFileBrowser::GetFirstFocusableControl(), CGUIDialogSelect::GetFirstFocusableControl(), PVR::CGUIDialogPVRItemsViewBase::GetFirstFocusableControl(), CGUIDialogVideoBookmarks::GetFirstFocusableControl(), CGUIMediaWindow::GetFirstFocusableControl(), CGUIWindowMusicPlayList::OnAction(), PVR::CGUIDialogPVRChannelsOSD::OnAction(), PVR::CGUIDialogPVRItemsViewBase::OnAction(), CGUIWindowVideoPlaylist::OnAction(), CGUIWindowMusicPlaylistEditor::OnBack(), KODI::GAME::CGUIWindowGames::OnClickMsg(), CGUIWindowAddonBrowser::OnMessage(), ADDON::CGUIAddonWindow::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogSelect::OnMessage(), CGUIWindowEventLog::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowPrograms::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIMediaWindow::OnMessage(), and CGUIWindowLoginScreen::OnMessage().
Reset()
void CGUIViewControl::Reset ()
References m_allViews, m_currentView, and m_visibleViews.
Referenced by CGUIViewControl(), CGUIMediaWindow::Load(), CGUIDialogColorPicker::OnWindowLoaded(), CGUIDialogFileBrowser::OnWindowLoaded(), CGUIDialogSelect::OnWindowLoaded(), PVR::CGUIDialogPVRChannelManager::OnWindowLoaded(), PVR::CGUIDialogPVRGroupManager::OnWindowLoaded(), PVR::CGUIDialogPVRItemsViewBase::OnWindowLoaded(), CGUIDialogVideoBookmarks::OnWindowLoaded(), CGUIWindowLoginScreen::OnWindowLoaded(), CGUIDialogColorPicker::OnWindowUnload(), CGUIDialogFileBrowser::OnWindowUnload(), CGUIDialogSelect::OnWindowUnload(), PVR::CGUIDialogPVRChannelManager::OnWindowUnload(), PVR::CGUIDialogPVRGroupManager::OnWindowUnload(), PVR::CGUIDialogPVRItemsViewBase::OnWindowUnload(), CGUIDialogVideoBookmarks::OnWindowUnload(), CGUIMediaWindow::OnWindowUnload(), and CGUIWindowLoginScreen::OnWindowUnload().
SetCurrentView()
void CGUIViewControl::SetCurrentView (int viewMode, bool bRefresh = false)
References CServiceBroker::GetGUI(), CGUIControl::GetID(), GetSelectedItem(), GetView(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_RESET, GUI_MSG_SETFOCUS, CGUIControl::HasFocus(), m_allViews, m_currentView, m_parentWindow, m_visibleViews, CGUIControl::OnMessage(), CGUIWindowManager::SendMessage(), CGUIControl::SetVisible(), UpdateContents(), UpdateViewAsControl(), UpdateViewVisibility(), VIEW_TYPE_BIG_ICON, VIEW_TYPE_BIG_INFO, VIEW_TYPE_ICON, VIEW_TYPE_INFO, VIEW_TYPE_LIST, and VIEW_TYPE_NONE.
Referenced by PVR::CGUIDialogPVRItemsViewBase::Init(), CGUIDialogColorPicker::OnInitWindow(), CGUIDialogSelect::OnInitWindow(), PVR::CGUIWindowPVRGuideBase::OnInitWindow(), CGUIWindowLoginScreen::OnInitWindow(), PVR::CGUIDialogPVRChannelManager::Update(), PVR::CGUIDialogPVRGroupManager::Update(), CGUIDialogVideoBookmarks::Update(), CGUIDialogFileBrowser::Update(), and CGUIMediaWindow::UpdateButtons().
SetFocused()
void CGUIViewControl::SetFocused ()
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_SETFOCUS, m_currentView, m_parentWindow, m_visibleViews, and CGUIWindowManager::SendMessage().
Referenced by CGUIWindowLoginScreen::OnInitWindow(), ADDON::CGUIAddonWindow::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogSelect::OnMessage(), PVR::CGUIWindowPVRBase::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowLoginScreen::OnMessage(), and CGUIWindowVideoBase::OnSearchItemFound().
SetItems()
void CGUIViewControl::SetItems (CFileItemList & items)
References m_fileItems, and UpdateView().
Referenced by ADDON::CGUIAddonWindow::AddItem(), ADDON::CGUIAddonWindow::ClearList(), CGUIWindowVideoPlaylist::ClearPlayList(), PVR::CGUIDialogPVRChannelManager::OnActionMove(), PVR::CGUIDialogPVRGroupManager::OnActionMove(), CGUIMediaWindow::OnFilterItems(), CGUIDialogColorPicker::OnInitWindow(), CGUIDialogSelect::OnInitWindow(), PVR::CGUIDialogPVRChannelGuide::OnInitWindow(), PVR::CGUIDialogPVRChannelsOSD::OnMessage(), CGUIDialogVideoBookmarks::OnRefreshList(), ADDON::CGUIAddonWindow::RemoveItem(), ADDON::CGUIAddonWindow::RemoveItem(), CGUIDialogSelect::SetItems(), PVR::CGUIDialogPVRChannelManager::Update(), PVR::CGUIDialogPVRChannelsOSD::Update(), PVR::CGUIDialogPVRGroupManager::Update(), CGUIWindowLoginScreen::Update(), CGUIDialogFileBrowser::Update(), and CGUIMediaWindow::UpdateFileList().
SetParentWindow()
void CGUIViewControl::SetParentWindow (int window)
References m_parentWindow.
Referenced by CGUIMediaWindow::Load(), CGUIDialogColorPicker::OnWindowLoaded(), CGUIDialogFileBrowser::OnWindowLoaded(), CGUIDialogSelect::OnWindowLoaded(), PVR::CGUIDialogPVRChannelManager::OnWindowLoaded(), PVR::CGUIDialogPVRGroupManager::OnWindowLoaded(), PVR::CGUIDialogPVRItemsViewBase::OnWindowLoaded(), CGUIDialogVideoBookmarks::OnWindowLoaded(), and CGUIWindowLoginScreen::OnWindowLoaded().
SetSelectedItem() [1/2]
void CGUIViewControl::SetSelectedItem (const std::string & itemPath)
References m_fileItems, URIUtils::RemoveSlashAtEnd(), SetSelectedItem(), and CFileItemList::Size().
SetSelectedItem() [2/2]
void CGUIViewControl::SetSelectedItem (int item)
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_ITEM_SELECT, m_currentView, m_fileItems, m_parentWindow, m_visibleViews, CGUIWindowManager::SendMessage(), and CFileItemList::Size().
Referenced by PVR::CGUIWindowPVRBase::InitChannelGroup(), CGUIWindowFavourites::MoveItem(), PVR::CGUIDialogPVRChannelManager::OnActionMove(), PVR::CGUIDialogPVRGroupManager::OnActionMove(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), CGUIWindowVideoNav::OnDeleteItem(), CGUIMediaWindow::OnDeleteItem(), CGUIWindowVideoBase::OnDeleteItem(), CGUIWindowEventLog::OnEventRemoved(), CGUIMediaWindow::OnFilterItems(), CGUIDialogColorPicker::OnInitWindow(), CGUIDialogSelect::OnInitWindow(), CGUIWindowPictures::OnInitWindow(), PVR::CGUIDialogPVRChannelGuide::OnInitWindow(), PVR::CGUIDialogPVRChannelManager::OnInitWindow(), PVR::CGUIWindowPVRBase::OnInitWindow(), PVR::CGUIDialogPVRChannelsOSD::OnInputDone(), PVR::CGUIWindowPVRChannelsBase::OnInputDone(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowFavourites::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIDialogFileBrowser::OnPopupMenu(), CGUIWindowVideoBase::OnQueueItem(), CGUIWindowMusicBase::OnQueueItem(), CGUIDialogVideoBookmarks::OnRefreshList(), CGUIMediaWindow::OnRenameItem(), CGUIWindowVideoBase::OnSearchItemFound(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicPlayList::RemovePlayListItem(), CGUIWindowVideoPlaylist::RemovePlayListItem(), PVR::CGUIDialogPVRChannelsOSD::RestoreControlStates(), CGUIMediaWindow::RestoreSelectedItemFromHistory(), CGUIWindowVideoNav::SelectFirstUnwatched(), ADDON::CGUIAddonWindow::SetCurrentListPosition(), SetSelectedItem(), CGUIWindowVideoBase::ShowInfoAndRefresh(), PVR::CGUIDialogPVRChannelManager::Update(), PVR::CGUIDialogPVRChannelsOSD::Update(), PVR::CGUIDialogPVRGroupManager::Update(), CGUIWindowLoginScreen::Update(), CGUIDialogFileBrowser::Update(), PVR::CGUIWindowPVRBase::Update(), and CGUIMediaWindow::UpdateFileList().
SetViewControlID()
void CGUIViewControl::SetViewControlID (int control)
References m_viewAsControl.
Referenced by CGUIMediaWindow::Load().
UpdateContents()
void CGUIViewControl::UpdateContents (const CGUIControl * control, int currentItem) const protected
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_BIND, m_fileItems, m_parentWindow, and CGUIWindowManager::SendMessage().
Referenced by SetCurrentView(), and UpdateView().
UpdateView()
void CGUIViewControl::UpdateView () protected
References GetSelectedItem(), m_currentView, m_visibleViews, and UpdateContents().
Referenced by SetItems().
UpdateViewAsControl()
void CGUIViewControl::UpdateViewAsControl (const std::string & viewLabel) protected
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), IGUIContainer::GetLabel(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_SET, GUI_MSG_SET_LABELS, label, m_currentView, m_parentWindow, m_viewAsControl, m_visibleViews, CGUIWindowManager::SendMessage(), CGUIMessage::SetLabel(), and CGUIMessage::SetPointer().
Referenced by SetCurrentView().
UpdateViewVisibility()
void CGUIViewControl::UpdateViewVisibility () protected
References CServiceBroker::GetGUI(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetGUIControlsInfoProvider(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CGUIControl::HasVisibleCondition(), CGUIControl::IsVisibleFromSkin(), m_allViews, m_visibleViews, CGUIInfoManager::ResetCache(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::ResetContainerMovingCache(), and CGUIControl::UpdateVisibility().
Referenced by SetCurrentView().
Member Data Documentation
m_allViews
std::vector<CGUIControl*> CGUIViewControl::m_allViews protected
Referenced by AddView(), HasControl(), Reset(), SetCurrentView(), and UpdateViewVisibility().
m_currentView
int CGUIViewControl::m_currentView protected
Referenced by Clear(), GetCurrentControl(), GetNextViewMode(), GetSelectedItem(), GetSelectedItemPath(), Reset(), SetCurrentView(), SetFocused(), SetSelectedItem(), UpdateView(), and UpdateViewAsControl().
m_fileItems
CFileItemList* CGUIViewControl::m_fileItems protected
Referenced by CGUIViewControl(), GetSelectedItem(), GetSelectedItemPath(), SetItems(), SetSelectedItem(), SetSelectedItem(), and UpdateContents().
m_parentWindow
int CGUIViewControl::m_parentWindow protected
Referenced by CGUIViewControl(), Clear(), GetSelectedItem(), SetCurrentView(), SetFocused(), SetParentWindow(), SetSelectedItem(), UpdateContents(), and UpdateViewAsControl().
m_viewAsControl
int CGUIViewControl::m_viewAsControl protected
Referenced by CGUIViewControl(), SetViewControlID(), and UpdateViewAsControl().
m_visibleViews
std::vector<CGUIControl*> CGUIViewControl::m_visibleViews protected
Referenced by Clear(), GetCurrentControl(), GetNextViewMode(), GetSelectedItem(), GetSelectedItemPath(), GetView(), GetViewModeByID(), GetViewModeCount(), GetViewModeNumber(), Reset(), SetCurrentView(), SetFocused(), SetSelectedItem(), UpdateView(), UpdateViewAsControl(), and UpdateViewVisibility().
The documentation for this class was generated from the following files:
GUIViewControl.h
GUIViewControl.cpp