Kodi Documentation: kodi::gui Namespace Reference
kodi::gui Namespace Reference
Namespaces
namespace controls
namespace dialogs
namespace gl
Classes
class CAddonGUIControlBase
class CListItem
struct CRenderHelperStub
class CWindow
struct IRenderHelper
Typedefs
using CRenderHelper = CRenderHelperStub
using ClientHandle = KODI_GUI_CLIENT_HANDLE
Handler for addon-sided processing class
If the callback functions used by the window are not used directly in the CWindow class and are outside of it.
Functions
void ATTR_DLL_LOCAL Lock ()
Performs a graphical lock of rendering engine.
void ATTR_DLL_LOCAL Unlock ()
Performs a graphical unlock of previous locked rendering engine.
int ATTR_DLL_LOCAL GetScreenHeight ()
Return the the current screen height with pixel.
int ATTR_DLL_LOCAL GetScreenWidth ()
Return the the current screen width with pixel.
int ATTR_DLL_LOCAL GetVideoResolution ()
Return the the current screen rendering resolution.
int ATTR_DLL_LOCAL GetCurrentWindowDialogId ()
Returns the id for the current 'active' dialog as an integer.
int ATTR_DLL_LOCAL GetCurrentWindowId ()
Returns the id for the current 'active' window as an integer.
kodi::HardwareContext GetHWContext ()
To get hardware specific device context interface.
AdjustRefreshRateStatus ATTR_DLL_LOCAL GetAdjustRefreshRateStatus ()
Get Adjust refresh rate setting status.
std::shared_ptr< IRenderHelper > ATTR_DLL_LOCAL GetRenderHelper ()
Typedef Documentation
CRenderHelper
using kodi::gui::CRenderHelper = typedef CRenderHelperStub
Function Documentation
GetRenderHelper()
std::shared_ptr< IRenderHelper > ATTR_DLL_LOCAL kodi::gui::GetRenderHelper () inline
Referenced by kodi::addon::CInstanceScreensaver::ADDON_start(), kodi::addon::CInstanceVisualization::ADDON_start(), and kodi::gui::controls::CRendering::OnCreateCB().