Kodi Documentation: CConvolutionKernel Class Reference
CConvolutionKernel Class Reference
#include <ConvolutionKernels.h>
Public Member Functions
CConvolutionKernel (ESCALINGMETHOD method, int size)
~CConvolutionKernel ()
int GetSize ()
float * GetFloatPixels ()
uint8_t * GetIntFractPixels ()
uint8_t * GetUint8Pixels ()
Private Member Functions
CConvolutionKernel (const CConvolutionKernel &)=delete
CConvolutionKernel & operator= (const CConvolutionKernel &)=delete
void Lanczos2 ()
void Lanczos3Fast ()
void Lanczos3 ()
void Spline36Fast ()
void Spline36 ()
void Bicubic (double B, double C)
void ToIntFract ()
void ToUint8 ()
Static Private Member Functions
static double LanczosWeight (double x, double radius)
static double Spline36Weight (double x)
static double BicubicWeight (double x, double B, double C)
Private Attributes
int m_size
float * m_floatpixels
uint8_t * m_intfractpixels
uint8_t * m_uint8pixels
Constructor & Destructor Documentation
CConvolutionKernel() [1/2]
CConvolutionKernel::CConvolutionKernel (ESCALINGMETHOD method, int size)
References Bicubic(), Lanczos2(), Lanczos3(), Lanczos3Fast(), m_floatpixels, m_size, Spline36(), Spline36Fast(), ToIntFract(), ToUint8(), VS_SCALINGMETHOD_CUBIC_0_075, VS_SCALINGMETHOD_CUBIC_0_1, VS_SCALINGMETHOD_CUBIC_B_SPLINE, VS_SCALINGMETHOD_CUBIC_CATMULL, VS_SCALINGMETHOD_CUBIC_MITCHELL, VS_SCALINGMETHOD_LANCZOS2, VS_SCALINGMETHOD_LANCZOS3, VS_SCALINGMETHOD_LANCZOS3_FAST, VS_SCALINGMETHOD_SPLINE36, and VS_SCALINGMETHOD_SPLINE36_FAST.
~CConvolutionKernel()
CConvolutionKernel::~CConvolutionKernel ()
References m_floatpixels, m_intfractpixels, and m_uint8pixels.
CConvolutionKernel() [2/2]
CConvolutionKernel::CConvolutionKernel (const CConvolutionKernel &) private delete
Member Function Documentation
Bicubic()
void CConvolutionKernel::Bicubic (double B, double C) private
References B, BicubicWeight(), C, m_floatpixels, and m_size.
Referenced by CConvolutionKernel().
BicubicWeight()
double CConvolutionKernel::BicubicWeight (double x, double B, double C) static private
References B, and C.
Referenced by Bicubic().
GetFloatPixels()
float * CConvolutionKernel::GetFloatPixels () inline
References m_floatpixels.
Referenced by CConvolutionShader::CreateHQKernel(), Shaders::GL::ConvolutionFilterShader::OnCompiledAndLinked(), Shaders::GLES::ConvolutionFilterShader::OnCompiledAndLinked(), Shaders::GL::YUV2RGBFilterShader4::OnCompiledAndLinked(), and Shaders::GLES::YUV2RGBFilterShader::OnCompiledAndLinked().
GetIntFractPixels()
uint8_t * CConvolutionKernel::GetIntFractPixels () inline
References m_intfractpixels.
GetSize()
int CConvolutionKernel::GetSize () inline
References m_size.
Referenced by CConvolutionShader::CreateHQKernel(), Shaders::GL::ConvolutionFilterShader::OnCompiledAndLinked(), Shaders::GLES::ConvolutionFilterShader::OnCompiledAndLinked(), Shaders::GL::YUV2RGBFilterShader4::OnCompiledAndLinked(), and Shaders::GLES::YUV2RGBFilterShader::OnCompiledAndLinked().
GetUint8Pixels()
uint8_t * CConvolutionKernel::GetUint8Pixels () inline
References m_uint8pixels.
Referenced by CConvolutionShader::CreateHQKernel(), Shaders::GL::ConvolutionFilterShader::OnCompiledAndLinked(), and Shaders::GLES::ConvolutionFilterShader::OnCompiledAndLinked().
Lanczos2()
void CConvolutionKernel::Lanczos2 () private
References LanczosWeight(), m_floatpixels, and m_size.
Referenced by CConvolutionKernel().
Lanczos3()
void CConvolutionKernel::Lanczos3 () private
References LanczosWeight(), m_floatpixels, and m_size.
Referenced by CConvolutionKernel().
Lanczos3Fast()
void CConvolutionKernel::Lanczos3Fast () private
References LanczosWeight(), m_floatpixels, and m_size.
Referenced by CConvolutionKernel().
LanczosWeight()
double CConvolutionKernel::LanczosWeight (double x, double radius) static private
References SINC.
Referenced by Lanczos2(), Lanczos3(), and Lanczos3Fast().
operator=()
CConvolutionKernel & CConvolutionKernel::operator= (const CConvolutionKernel &) private delete
Spline36()
void CConvolutionKernel::Spline36 () private
References m_floatpixels, m_size, and Spline36Weight().
Referenced by CConvolutionKernel().
Spline36Fast()
void CConvolutionKernel::Spline36Fast () private
References m_floatpixels, m_size, and Spline36Weight().
Referenced by CConvolutionKernel().
Spline36Weight()
double CConvolutionKernel::Spline36Weight (double x) static private
Referenced by Spline36(), and Spline36Fast().
ToIntFract()
void CConvolutionKernel::ToIntFract () private
References m_floatpixels, m_intfractpixels, m_size, MathUtils::round_int(), and value.
Referenced by CConvolutionKernel().
ToUint8()
void CConvolutionKernel::ToUint8 () private
References m_floatpixels, m_size, m_uint8pixels, MathUtils::round_int(), and value.
Referenced by CConvolutionKernel().
Member Data Documentation
m_floatpixels
float* CConvolutionKernel::m_floatpixels private
Referenced by Bicubic(), CConvolutionKernel(), GetFloatPixels(), Lanczos2(), Lanczos3(), Lanczos3Fast(), Spline36(), Spline36Fast(), ToIntFract(), ToUint8(), and ~CConvolutionKernel().
m_intfractpixels
uint8_t* CConvolutionKernel::m_intfractpixels private
Referenced by GetIntFractPixels(), ToIntFract(), and ~CConvolutionKernel().
m_size
int CConvolutionKernel::m_size private
Referenced by Bicubic(), CConvolutionKernel(), GetSize(), Lanczos2(), Lanczos3(), Lanczos3Fast(), Spline36(), Spline36Fast(), ToIntFract(), and ToUint8().
m_uint8pixels
uint8_t* CConvolutionKernel::m_uint8pixels private
Referenced by GetUint8Pixels(), ToUint8(), and ~CConvolutionKernel().
The documentation for this class was generated from the following files:
ConvolutionKernels.h
ConvolutionKernels.cpp