Kodi Documentation: KODI::GAME::CControllerTranslator Class Reference
KODI::GAME::CControllerTranslator Class Reference
Games
#include <ControllerTranslator.h>
Static Public Member Functions
static const char * TranslateFeatureType (JOYSTICK::FEATURE_TYPE type)
static JOYSTICK::FEATURE_TYPE TranslateFeatureType (const std::string &strType)
static const char * TranslateFeatureCategory (JOYSTICK::FEATURE_CATEGORY category)
static JOYSTICK::FEATURE_CATEGORY TranslateFeatureCategory (const std::string &strCategory)
static const char * TranslateInputType (JOYSTICK::INPUT_TYPE type)
static JOYSTICK::INPUT_TYPE TranslateInputType (const std::string &strType)
Member Function Documentation
TranslateFeatureCategory() [1/2]
FEATURE_CATEGORY CControllerTranslator::TranslateFeatureCategory (const std::string & strCategory) static
References FEATURE_CATEGORY_ACCELEROMETER, FEATURE_CATEGORY_ANALOG_STICK, FEATURE_CATEGORY_FACE, FEATURE_CATEGORY_HAPTICS, FEATURE_CATEGORY_HARDWARE, FEATURE_CATEGORY_JOYSTICK, FEATURE_CATEGORY_KEY, FEATURE_CATEGORY_KEYPAD, FEATURE_CATEGORY_LIGHTGUN, FEATURE_CATEGORY_MOUSE_BUTTON, FEATURE_CATEGORY_OFFSCREEN, FEATURE_CATEGORY_PADDLE, FEATURE_CATEGORY_POINTER, FEATURE_CATEGORY_SHOULDER, FEATURE_CATEGORY_TRIGGER, and FEATURE_CATEGORY_WHEEL.
TranslateFeatureCategory() [2/2]
const char * CControllerTranslator::TranslateFeatureCategory (JOYSTICK::FEATURE_CATEGORY category) static
References FEATURE_CATEGORY_ACCELEROMETER, FEATURE_CATEGORY_ANALOG_STICK, FEATURE_CATEGORY_FACE, FEATURE_CATEGORY_HAPTICS, FEATURE_CATEGORY_HARDWARE, FEATURE_CATEGORY_JOYSTICK, FEATURE_CATEGORY_KEY, FEATURE_CATEGORY_KEYPAD, FEATURE_CATEGORY_LIGHTGUN, FEATURE_CATEGORY_MOUSE_BUTTON, FEATURE_CATEGORY_OFFSCREEN, FEATURE_CATEGORY_PADDLE, FEATURE_CATEGORY_POINTER, FEATURE_CATEGORY_SHOULDER, FEATURE_CATEGORY_TRIGGER, and FEATURE_CATEGORY_WHEEL.
Referenced by KODI::GAME::CControllerLayout::Deserialize().
TranslateFeatureType() [1/2]
FEATURE_TYPE CControllerTranslator::TranslateFeatureType (const std::string & strType) static
References LAYOUT_XML_ELM_ABSPOINTER, LAYOUT_XML_ELM_ACCELEROMETER, LAYOUT_XML_ELM_ANALOG_STICK, LAYOUT_XML_ELM_BUTTON, LAYOUT_XML_ELM_KEY, LAYOUT_XML_ELM_MOTOR, LAYOUT_XML_ELM_RELPOINTER, LAYOUT_XML_ELM_THROTTLE, and LAYOUT_XML_ELM_WHEEL.
TranslateFeatureType() [2/2]
static const char * KODI::GAME::CControllerTranslator::TranslateFeatureType (JOYSTICK::FEATURE_TYPE type) static
Referenced by KODI::GAME::CPhysicalFeature::Deserialize().
TranslateInputType() [1/2]
INPUT_TYPE CControllerTranslator::TranslateInputType (const std::string & strType) static
TranslateInputType() [2/2]
const char * CControllerTranslator::TranslateInputType (JOYSTICK::INPUT_TYPE type) static
Referenced by KODI::GAME::CPhysicalFeature::Deserialize().
The documentation for this class was generated from the following files:
ControllerTranslator.h
ControllerTranslator.cpp