Kodi Documentation: CGUISettingsSliderControl Class Reference
CGUISettingsSliderControl Class Reference
Guilib classes » Window Reference » Controls
#include <GUISettingsSliderControl.h>
Public Member Functions
CGUISettingsSliderControl (int parentID, int controlID, float posX, float posY, float width, float height, float sliderWidth, float sliderHeight, const CTextureInfo &textureFocus, const CTextureInfo &textureNoFocus, const CTextureInfo &backGroundTexture, const CTextureInfo &backGroundTextureDisabled, const CTextureInfo &nibTexture, const CTextureInfo &nibTextureFocus, const CTextureInfo &nibTextureDisabled, const CLabelInfo &labelInfo, int iType)
~CGUISettingsSliderControl () override=default
CGUISettingsSliderControl * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
bool OnAction (const CAction &action) override
void OnUnFocus () override
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
void SetActive ()
bool IsActive () const override
void AllocResources () override
void FreeResources (bool immediately=false) override
void DynamicResourceAlloc (bool bOnOff) override
void SetInvalid () override
void SetPosition (float posX, float posY) override
float GetWidth () const override
void SetWidth (float width) override
float GetHeight () const override
void SetHeight (float height) override
void SetEnabled (bool bEnable) override
void SetText (const std::string &label)
float GetXPosition () const override
float GetYPosition () const override
std::string GetDescription () const override
bool HitTest (const CPoint &point) const override
Used to test whether the point is inside a control.
Public Member Functions inherited from CGUISliderControl
CGUISliderControl (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo &backGroundTexture, const CTextureInfo &backGroundTextureDisabled, const CTextureInfo &mibTexture, const CTextureInfo &nibTextureFocus, const CTextureInfo &nibTextureDisabled, int iType, ORIENTATION orientationconst)
~CGUISliderControl () override=default
CGUISliderControl * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
bool OnAction (const CAction &action) override
void AllocResources () override
void FreeResources (bool immediately=false) override
void DynamicResourceAlloc (bool bOnOff) override
void SetInvalid () override
virtual void SetRange (int iStart, int iEnd)
virtual void SetFloatRange (float fStart, float fEnd)
bool OnMessage (CGUIMessage &message) override
bool ProcessSelector (CGUITexture *background, CGUITexture *nib, unsigned int currentTime, float fScale, RangeSelector selector)
void SetRangeSelection (bool rangeSelection)
bool GetRangeSelection () const
void SetRangeSelector (RangeSelector selector)
void SwitchRangeSelector ()
void SetInfo (int iInfo)
void SetPercentage (float iPercent, RangeSelector selector=RangeSelectorLower, bool updateCurrent=false)
float GetPercentage (RangeSelector selector=RangeSelectorLower) const
void SetIntValue (int iValue, RangeSelector selector=RangeSelectorLower, bool updateCurrent=false)
int GetIntValue (RangeSelector selector=RangeSelectorLower) const
void SetFloatValue (float fValue, RangeSelector selector=RangeSelectorLower, bool updateCurrent=false)
float GetFloatValue (RangeSelector selector=RangeSelectorLower) const
void SetIntInterval (int iInterval)
void SetFloatInterval (float fInterval)
void SetType (int iType)
int GetType () const
std::string GetDescription () const override
void SetTextValue (const std::string &textValue)
void SetAction (const std::string &action)
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual bool IsDynamicallyAllocated ()
virtual bool CanFocus () const
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetInitialVisibility ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
bool UpdateColors (const CGUIListItem *item) override
virtual void ProcessText ()
Protected Member Functions inherited from CGUISliderControl
CGUISliderControl (const CGUISliderControl &control)
bool HitTest (const CPoint &point) const override
Used to test whether the point is inside a control.
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
bool UpdateColors (const CGUIListItem *item) override
virtual void Move (int iNumSteps)
virtual void SetFromPosition (const CPoint &point, bool guessSelector=false)
float GetProportion (RangeSelector selector=RangeSelectorLower) const
Get the current position of the slider as a proportion.
void SendClick ()
Send a click message (and/or action) to the app in response to a slider move.
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Private Member Functions
CGUISettingsSliderControl (const CGUISettingsSliderControl &control)
Private Attributes
CGUIButtonControl m_buttonControl
CGUILabel m_label
bool m_active
Whether the slider has been activated by a click.
Additional Inherited Members
Public Types inherited from CGUISliderControl
enum RangeSelector { RangeSelectorLower = 0 , RangeSelectorUpper = 1 }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Attributes inherited from CGUISliderControl
std::unique_ptr< CGUITexture > m_guiBackground
std::unique_ptr< CGUITexture > m_guiBackgroundDisabled
std::unique_ptr< CGUITexture > m_guiSelectorLower
std::unique_ptr< CGUITexture > m_guiSelectorUpper
std::unique_ptr< CGUITexture > m_guiSelectorLowerFocus
std::unique_ptr< CGUITexture > m_guiSelectorUpperFocus
std::unique_ptr< CGUITexture > m_guiSelectorLowerDisabled
std::unique_ptr< CGUITexture > m_guiSelectorUpperDisabled
int m_iType
bool m_rangeSelection
RangeSelector m_currentSelector
std::array< float, 2 > m_percentValues
std::array< int, 2 > m_intValues
int m_iStart
int m_iInterval
int m_iEnd
std::array< float, 2 > m_floatValues
float m_fStart
float m_fInterval
float m_fEnd
int m_iInfoCode
std::string m_textValue
Allows overriding of the text value to be displayed (parent must update when the slider updates)
const SliderAction * m_action
Allows the skin to configure the action of a click on the slider.
bool m_dragging
Whether we're in a (mouse/touch) drag operation or not - some actions are sent only on release.
ORIENTATION m_orientation
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUISettingsSliderControl() [1/2]
CGUISettingsSliderControl::CGUISettingsSliderControl (int parentID, int controlID, float posX, float posY, float width, float height, float sliderWidth, float sliderHeight, const CTextureInfo & textureFocus, const CTextureInfo & textureNoFocus, const CTextureInfo & backGroundTexture, const CTextureInfo & backGroundTextureDisabled, const CTextureInfo & nibTexture, const CTextureInfo & nibTextureFocus, const CTextureInfo & nibTextureDisabled, const CLabelInfo & labelInfo, int iType)
References CLabelInfo::align, CGUIControl::ControlType, CGUIControl::GUICONTROL_SETTINGS_SLIDER, m_active, m_label, CGUILabel::SetAlign(), XBFONT_CENTER_Y, and XBFONT_RIGHT.
~CGUISettingsSliderControl()
CGUISettingsSliderControl::~CGUISettingsSliderControl () override default
CGUISettingsSliderControl() [2/2]
CGUISettingsSliderControl::CGUISettingsSliderControl (const CGUISettingsSliderControl & control) private
Member Function Documentation
AllocResources()
void CGUISettingsSliderControl::AllocResources () override virtual
Reimplemented from CGUIControl.
References CGUIButtonControl::AllocResources(), CGUISliderControl::AllocResources(), and m_buttonControl.
Clone()
CGUISettingsSliderControl * CGUISettingsSliderControl::Clone (void) const inline override virtual
Implements CGUIControl.
Referenced by CGUIDialogSettingsBase::AddSetting().
DynamicResourceAlloc()
void CGUISettingsSliderControl::DynamicResourceAlloc (bool bOnOff) override virtual
Reimplemented from CGUIControl.
References CGUIButtonControl::DynamicResourceAlloc(), CGUISliderControl::DynamicResourceAlloc(), and m_buttonControl.
FreeResources()
void CGUISettingsSliderControl::FreeResources (bool immediately = false) override virtual
Reimplemented from CGUIControl.
References CGUIButtonControl::FreeResources(), CGUISliderControl::FreeResources(), and m_buttonControl.
GetDescription()
std::string CGUISettingsSliderControl::GetDescription (void) const override virtual
Reimplemented from CGUIControl.
References CGUIButtonControl::GetDescription(), CGUISliderControl::GetDescription(), and m_buttonControl.
GetHeight()
float CGUISettingsSliderControl::GetHeight () const inline override virtual
Reimplemented from CGUIControl.
References CGUIControl::GetHeight(), and m_buttonControl.
GetWidth()
float CGUISettingsSliderControl::GetWidth () const inline override virtual
Reimplemented from CGUIControl.
References CGUIButtonControl::GetWidth(), and m_buttonControl.
GetXPosition()
float CGUISettingsSliderControl::GetXPosition () const inline override virtual
Reimplemented from CGUIControl.
References CGUIControl::GetXPosition(), and m_buttonControl.
GetYPosition()
float CGUISettingsSliderControl::GetYPosition () const inline override virtual
Reimplemented from CGUIControl.
References CGUIControl::GetYPosition(), and m_buttonControl.
HitTest()
bool CGUISettingsSliderControl::HitTest (const CPoint & point) const inline override virtual
Used to test whether the point is inside a control.
Parameters
point location to test
Returns
true if the point is inside the bounds of this control.
See also
SetHitRect
Reimplemented from CGUIControl.
References CGUIControl::HitTest(), and m_buttonControl.
IsActive()
bool CGUISettingsSliderControl::IsActive () const inline override virtual
Reimplemented from CGUISliderControl.
References m_active.
Referenced by OnAction().
OnAction()
bool CGUISettingsSliderControl::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControl.
References ACTION_SELECT_ITEM, IsActive(), m_active, CGUISliderControl::m_currentSelector, CGUISliderControl::m_rangeSelection, CGUISliderControl::OnAction(), CGUISliderControl::RangeSelectorLower, and CGUISliderControl::SwitchRangeSelector().
OnMouseEvent()
EVENT_RESULT CGUISettingsSliderControl::OnMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) override virtual
Perform a mouse action.
Mouse actions are sent from the window to all controls, and each control can react based on the event and location of the actions.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
SendMouseEvent, HitTest, CanFocusFromPoint, CMouseEvent
Reimplemented from CGUIControl.
References CGUISliderControl::OnMouseEvent(), and SetActive().
OnUnFocus()
void CGUISettingsSliderControl::OnUnFocus (void) override virtual
Reimplemented from CGUIControl.
References m_active.
Process()
void CGUISettingsSliderControl::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
References CGUIControl::DoProcess(), CGUIControl::GetHeight(), CGUIButtonControl::GetLabelInfo(), CGUIButtonControl::GetWidth(), CGUIControl::GetXPosition(), CGUIControl::GetYPosition(), CGUIControl::HasFocus(), CGUIControl::m_bInvalidated, m_buttonControl, CGUIControl::m_enabled, CGUIControl::m_height, CGUIControl::m_pulseOnSelect, CGUIControl::m_width, CLabelInfo::offsetX, CGUISliderControl::Process(), ProcessText(), CGUIControl::SetEnabled(), CGUIControl::SetFocus(), CGUIControl::SetPosition(), and CGUIControl::SetPulseOnSelect().
ProcessText()
void CGUISettingsSliderControl::ProcessText () protected virtual
References CGUILabel::COLOR_DISABLED, CGUILabel::COLOR_FOCUSED, CGUILabel::COLOR_TEXT, CGUISliderControl::GetDescription(), CGUIControl::GetHeight(), CGUIControl::GetXPosition(), CGUIControl::GetYPosition(), CGUIControl::HasFocus(), CGUIControl::IsDisabled(), m_buttonControl, m_label, CGUIControl::m_posX, CGUIControl::MarkDirtyRegion(), CGUILabel::SetColor(), CGUILabel::SetMaxRect(), and CGUILabel::SetText().
Referenced by Process().
Render()
void CGUISettingsSliderControl::Render () override virtual
Reimplemented from CGUIControl.
References CServiceBroker::GetWinSystem(), m_buttonControl, m_label, CGUILabel::Render(), CGUIButtonControl::Render(), CGUISliderControl::Render(), and RENDER_ORDER_FRONT_TO_BACK.
SetActive()
void CGUISettingsSliderControl::SetActive ()
References m_active.
Referenced by OnMouseEvent().
SetEnabled()
void CGUISettingsSliderControl::SetEnabled (bool bEnable) override virtual
Reimplemented from CGUIControl.
References m_buttonControl, and CGUIControl::SetEnabled().
Referenced by ADDON::Interface_GUIControlSettingsSlider::set_enabled().
SetHeight()
void CGUISettingsSliderControl::SetHeight (float height) override virtual
Reimplemented from CGUIControl.
References m_buttonControl, CGUIControl::SetHeight(), and CGUISliderControl::SetInvalid().
SetInvalid()
void CGUISettingsSliderControl::SetInvalid () override virtual
Reimplemented from CGUIControl.
References m_buttonControl, CGUIButtonControl::SetInvalid(), and CGUISliderControl::SetInvalid().
SetPosition()
void CGUISettingsSliderControl::SetPosition (float posX, float posY) override virtual
Reimplemented from CGUIControl.
References m_buttonControl, CGUISliderControl::SetInvalid(), and CGUIButtonControl::SetPosition().
SetText()
void CGUISettingsSliderControl::SetText (const std::string & label) inline
References label, m_buttonControl, and CGUIButtonControl::SetLabel().
SetWidth()
void CGUISettingsSliderControl::SetWidth (float width) override virtual
Reimplemented from CGUIControl.
References m_buttonControl, CGUISliderControl::SetInvalid(), and CGUIControl::SetWidth().
UpdateColors()
bool CGUISettingsSliderControl::UpdateColors (const CGUIListItem * item) override protected virtual
Reimplemented from CGUIControl.
References m_buttonControl, CGUIControl::m_diffuseColor, m_label, CGUIControl::SetColorDiffuse(), CGUILabel::UpdateColors(), CGUIButtonControl::UpdateColors(), and CGUISliderControl::UpdateColors().
Member Data Documentation
m_active
bool CGUISettingsSliderControl::m_active private
Whether the slider has been activated by a click.
Referenced by CGUISettingsSliderControl(), IsActive(), OnAction(), OnUnFocus(), and SetActive().
m_buttonControl
CGUIButtonControl CGUISettingsSliderControl::m_buttonControl private
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), GetDescription(), GetHeight(), GetWidth(), GetXPosition(), GetYPosition(), HitTest(), Process(), ProcessText(), Render(), SetEnabled(), SetHeight(), SetInvalid(), SetPosition(), SetText(), SetWidth(), and UpdateColors().
m_label
CGUILabel CGUISettingsSliderControl::m_label private
Referenced by CGUISettingsSliderControl(), ProcessText(), Render(), and UpdateColors().
The documentation for this class was generated from the following files:
GUISettingsSliderControl.h
GUISettingsSliderControl.cpp