Kodi Documentation: ZeroconfDirectory.cpp File Reference
ZeroconfDirectory.cpp File Reference
#include "ZeroconfDirectory.h"
#include "Directory.h"
#include "FileItem.h"
#include "FileItemList.h"
#include "URL.h"
#include "network/ZeroconfBrowser.h"
#include "utils/ArtUtils.h"
#include "utils/URIUtils.h"
#include "utils/log.h"
#include <cassert>
#include <stdexcept>
Namespaces
namespace anonymous_namespace{ZeroconfDirectory.cpp}
Functions
std::string anonymous_namespace{ZeroconfDirectory.cpp}::GetHumanReadableProtocol (std::string const &fcr_service_type)
bool anonymous_namespace{ZeroconfDirectory.cpp}::GetXBMCProtocol (std::string const &fcr_service_type, std::string &fr_protocol)
bool GetDirectoryFromTxtRecords (const CZeroconfBrowser::ZeroconfService &zeroconf_service, CURL &url, CFileItemList &items)
Function Documentation
GetDirectoryFromTxtRecords()
bool GetDirectoryFromTxtRecords (const CZeroconfBrowser::ZeroconfService & zeroconf_service, CURL & url, CFileItemList & items)
References CFileItemList::Add(), URIUtils::AddSlashAtEnd(), KODI::ART::FillInDefaultIcon(), CURL::Get(), URIUtils::GetFileName(), CZeroconfBrowser::ZeroconfService::GetTxtRecords(), URIUtils::RemoveSlashAtEnd(), CURL::SetPassword(), CURL::SetUserName(), TXT_RECORD_PASSWORD_KEY, TXT_RECORD_PATH_KEY, and TXT_RECORD_USERNAME_KEY.
Referenced by XFILE::CZeroconfDirectory::GetDirectory().