Kodi Documentation: LangInfo.cpp File Reference
LangInfo.cpp File Reference
#include "LangInfo.h"
#include "DatabaseManager.h"
#include "ServiceBroker.h"
#include "XBDateTime.h"
#include "addons/AddonInstaller.h"
#include "addons/AddonManager.h"
#include "addons/LanguageResource.h"
#include "addons/RepositoryUpdater.h"
#include "addons/addoninfo/AddonType.h"
#include "guilib/LocalizeStrings.h"
#include "messaging/ApplicationMessenger.h"
#include "pvr/PVRManager.h"
#include "settings/AdvancedSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "settings/lib/Setting.h"
#include "settings/lib/SettingDefinitions.h"
#include "utils/CharsetConverter.h"
#include "utils/LangCodeExpander.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/XBMCTinyXML.h"
#include "utils/XMLUtils.h"
#include "utils/log.h"
#include "weather/WeatherManager.h"
#include <algorithm>
#include <stdexcept>
Classes
struct TemperatureInfo
struct SpeedInfo
struct SortLanguage
Namespaces
namespace anonymous_namespace{LangInfo.cpp}
Macros
#define TIME_FORMAT_MM_SS ":mm:ss"
#define TIME_FORMAT_SINGLE_12 "h" TIME_FORMAT_MM_SS
#define TIME_FORMAT_DOUBLE_12 "hh" TIME_FORMAT_MM_SS
#define TIME_FORMAT_SINGLE_24 "H" TIME_FORMAT_MM_SS
#define TIME_FORMAT_DOUBLE_24 "HH" TIME_FORMAT_MM_SS
#define TIME_FORMAT_12HOURS "12hours"
#define TIME_FORMAT_24HOURS "24hours"
#define TEMP_UNIT_STRINGS 20027
#define SPEED_UNIT_STRINGS 20200
#define SETTING_REGIONAL_DEFAULT "regional"
Typedefs
typedef struct TemperatureInfo TemperatureInfo
typedef struct SpeedInfo SpeedInfo
Functions
std::string anonymous_namespace{LangInfo.cpp}::GetDateStringWithFormat (const CDateTime &date, const std::string &format)
static std::string ToTimeFormat (bool use24HourClock, bool singleHour, bool meridiem)
static std::string ToSettingTimeFormat (const CDateTime &time, const std::string &timeFormat)
static CTemperature::Unit StringToTemperatureUnit (const std::string &temperatureUnit)
static CSpeed::Unit StringToSpeedUnit (const std::string &speedUnit)
Variables
static std::string shortDateFormats []
static std::string longDateFormats []
static TemperatureInfo temperatureInfo []
static SpeedInfo speedInfo []
Macro Definition Documentation
SETTING_REGIONAL_DEFAULT
#define SETTING_REGIONAL_DEFAULT "regional"
SPEED_UNIT_STRINGS
#define SPEED_UNIT_STRINGS 20200
TEMP_UNIT_STRINGS
#define TEMP_UNIT_STRINGS 20027
TIME_FORMAT_12HOURS
#define TIME_FORMAT_12HOURS "12hours"
TIME_FORMAT_24HOURS
#define TIME_FORMAT_24HOURS "24hours"
TIME_FORMAT_DOUBLE_12
#define TIME_FORMAT_DOUBLE_12 "hh" TIME_FORMAT_MM_SS
TIME_FORMAT_DOUBLE_24
#define TIME_FORMAT_DOUBLE_24 "HH" TIME_FORMAT_MM_SS
TIME_FORMAT_MM_SS
#define TIME_FORMAT_MM_SS ":mm:ss"
TIME_FORMAT_SINGLE_12
#define TIME_FORMAT_SINGLE_12 "h" TIME_FORMAT_MM_SS
TIME_FORMAT_SINGLE_24
#define TIME_FORMAT_SINGLE_24 "H" TIME_FORMAT_MM_SS
Typedef Documentation
SpeedInfo
typedef struct SpeedInfo SpeedInfo
TemperatureInfo
typedef struct TemperatureInfo TemperatureInfo
Function Documentation
StringToSpeedUnit()
static CSpeed::Unit StringToSpeedUnit (const std::string & speedUnit) static
References speedInfo, KODI::UTILS::StringUtils::ToLower(), and CSpeed::UnitKilometresPerHour.
Referenced by CLangInfo::SetSpeedUnit(), and CLangInfo::CRegion::SetSpeedUnit().
StringToTemperatureUnit()
static CTemperature::Unit StringToTemperatureUnit (const std::string & temperatureUnit) static
References temperatureInfo, KODI::UTILS::StringUtils::ToLower(), and CTemperature::UnitCelsius.
Referenced by CLangInfo::CRegion::SetTemperatureUnit(), and CLangInfo::SetTemperatureUnit().
ToSettingTimeFormat()
static std::string ToSettingTimeFormat (const CDateTime & time, const std::string & timeFormat) static
References KODI::UTILS::StringUtils::Format(), g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CLangInfo::SettingOptionsTimeFormatsFiller().
ToTimeFormat()
static std::string ToTimeFormat (bool use24HourClock, bool singleHour, bool meridiem) static
References KODI::UTILS::StringUtils::Format(), g_localizeStrings, CLocalizeStrings::Get(), TIME_FORMAT_DOUBLE_12, TIME_FORMAT_DOUBLE_24, TIME_FORMAT_SINGLE_12, TIME_FORMAT_SINGLE_24, and ToTimeFormat().
Referenced by CLangInfo::SettingOptionsTimeFormatsFiller(), and ToTimeFormat().
Variable Documentation
longDateFormats
std::string longDateFormats[] static
Initial value:
= {
  "DDDD, D MMMM YYYY",
  "DDDD, DD MMMM YYYY",
  "DDDD, D. MMMM YYYY",
  "DDDD, DD. MMMM YYYY",
  "DDDD, MMMM D, YYYY",
  "DDDD, MMMM DD, YYYY",
  "DDDD D MMMM YYYY",
  "DDDD DD MMMM YYYY",
  "DDDD D. MMMM YYYY",
  "DDDD DD. MMMM YYYY",
  "D. MMMM YYYY",
  "DD. MMMM YYYY",
  "D. MMMM. YYYY",
  "DD. MMMM. YYYY",
  "YYYY. MMMM. D"
}
Referenced by CLangInfo::SettingOptionsLongDateFormatsFiller().
shortDateFormats
std::string shortDateFormats[] static
Initial value:
= {
  "DD/MM/YYYY",
  "MM/DD/YYYY",
  "YYYY/MM/DD",
  "D/M/YYYY",
  "DD-MM-YYYY",
  "MM-DD-YYYY",
  "YYYY-MM-DD",
  "YYYY-M-D",
  "DD.MM.YYYY",
  "DD.M.YYYY",
  "D.M.YYYY",
  "D. M. YYYY",
  "YYYY.MM.DD",
  "D-mmm-YY",
  "DD-mmm-YY",
  "D mmm YY",
  "DD mmm YY",
}
Referenced by CLangInfo::SettingOptionsShortDateFormatsFiller().
speedInfo
SpeedInfo speedInfo[] static
Initial value:
= {
  { CSpeed::UnitKilometresPerHour,    "kmh" },
  { CSpeed::UnitMetresPerMinute,      "mpmin" },
  { CSpeed::UnitMetresPerSecond,      "mps" },
  { CSpeed::UnitFeetPerHour,          "fth" },
  { CSpeed::UnitFeetPerMinute,        "ftm" },
  { CSpeed::UnitFeetPerSecond,        "fts" },
  { CSpeed::UnitMilesPerHour,         "mph" },
  { CSpeed::UnitKnots,                "kts" },
  { CSpeed::UnitBeaufort,             "beaufort" },
  { CSpeed::UnitInchPerSecond,        "inchs" },
  { CSpeed::UnitYardPerSecond,        "yards" },
  { CSpeed::UnitFurlongPerFortnight,  "fpf" }
}
Referenced by CLangInfo::SettingOptionsSpeedUnitsFiller(), and StringToSpeedUnit().
temperatureInfo
TemperatureInfo temperatureInfo[] static
Initial value:
= {
  { CTemperature::UnitFahrenheit, "f" },
  { CTemperature::UnitKelvin,     "k" },
  { CTemperature::UnitCelsius,    "c" },
  { CTemperature::UnitReaumur,    "re" },
  { CTemperature::UnitRankine,    "ra" },
  { CTemperature::UnitRomer,      "ro" },
  { CTemperature::UnitDelisle,    "de" },
  { CTemperature::UnitNewton,     "n" }
}
Referenced by CLangInfo::SettingOptionsTemperatureUnitsFiller(), and StringToTemperatureUnit().