Kodi Documentation: EmbeddedArt Class Reference
EmbeddedArt Class Reference
#include <EmbeddedArt.h>
Public Member Functions
EmbeddedArt ()=default
EmbeddedArt (const uint8_t *data, size_t size, const std::string &mime, const std::string &type="")
void Set (const uint8_t *data, size_t size, const std::string &mime, const std::string &type="")
Public Member Functions inherited from EmbeddedArtInfo
EmbeddedArtInfo ()=default
EmbeddedArtInfo (size_t size, const std::string &mime, const std::string &type="")
virtual ~EmbeddedArtInfo ()=default
void Archive (CArchive &ar) override
void Set (size_t size, const std::string &mime, const std::string &type="")
void Clear ()
bool Empty () const
bool Matches (const EmbeddedArtInfo &right) const
void SetType (const std::string &type)
Public Attributes
std::vector< uint8_t > m_data
Public Attributes inherited from EmbeddedArtInfo
size_t m_size = 0
std::string m_mime
std::string m_type
Additional Inherited Members
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Constructor & Destructor Documentation
EmbeddedArt() [1/2]
EmbeddedArt::EmbeddedArt () default
EmbeddedArt() [2/2]
EmbeddedArt::EmbeddedArt (const uint8_t * data, size_t size, const std::string & mime, const std::string & type = "")
References data(), and Set().
Member Function Documentation
Set()
void EmbeddedArt::Set (const uint8_t * data, size_t size, const std::string & mime, const std::string & type = "")
References data(), m_data, and EmbeddedArtInfo::Set().
Referenced by EmbeddedArt(), KODI::ADDONS::CAudioDecoder::Load(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), and anonymous_namespace{TagLoaderTagLib.cpp}::SetFlacArt().
Member Data Documentation
m_data
std::vector<uint8_t> EmbeddedArt::m_data
Referenced by MUSIC_INFO::CMusicEmbeddedImageFileLoader::Load(), KODI::VIDEO::CVideoEmbeddedImageFileLoader::Load(), and Set().
The documentation for this class was generated from the following files:
EmbeddedArt.h
EmbeddedArt.cpp