Kodi Documentation: PVR::CPVRChannelGroups Class Reference
PVR::CPVRChannelGroups Class Reference
#include <PVRChannelGroups.h>
Public Member Functions
CPVRChannelGroups (bool bRadio)
Create a new group container.
virtual ~CPVRChannelGroups ()
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void Unload ()
Remove all groups from this container.
bool LoadFromDatabase (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Load all channel groups and all channels from PVR database.
std::shared_ptr< CPVRChannelGroupFactory > GetGroupFactory () const
Get the channel group factory.
size_t Size () const
bool Update (const std::shared_ptr< CPVRChannelGroup > &group, bool bUpdateFromClient=false)
Update a group or add it if it's not in here yet.
bool UpdateFromClient (const std::shared_ptr< CPVRChannelGroup > &group)
Called by the add-on callback to add a new group.
std::shared_ptr< CPVRChannelGroupMember > GetChannelGroupMemberByPath (const CPVRChannelsPath &path) const
Get a channel group member given its path.
std::vector< std::shared_ptr< CPVRChannelGroupMember > > GetMembersAvailableForGroup (const std::shared_ptr< const CPVRChannelGroup > &group) const
Get all channel group members that could be added to the given group.
std::shared_ptr< CPVRChannelGroup > GetById (int iGroupId) const
Get a pointer to a channel group given its ID.
std::shared_ptr< CPVRChannelGroup > GetGroupByPath (const std::string &strPath) const
Get a channel group given its path.
std::shared_ptr< CPVRChannelGroup > GetByName (const std::string &strName, int clientID) const
Get a group given its name.
std::shared_ptr< CPVRChannelGroup > GetGroupAll () const
Get the group that contains all channels.
std::shared_ptr< CPVRChannelGroup > GetFirstGroup () const
std::shared_ptr< CPVRChannelGroup > GetLastGroup () const
GroupMemberPair GetLastAndPreviousToLastPlayedChannelGroupMember () const
std::shared_ptr< CPVRChannelGroup > GetLastOpenedGroup () const
std::vector< std::shared_ptr< CPVRChannelGroup > > GetMembers (bool bExcludeHidden=false) const
Get the list of groups.
std::shared_ptr< CPVRChannelGroup > GetPreviousGroup (const CPVRChannelGroup &group) const
Get the previous group in this container.
std::shared_ptr< CPVRChannelGroup > GetNextGroup (const CPVRChannelGroup &group) const
Get the next group in this container.
std::shared_ptr< CPVRChannelGroup > AddGroup (const std::string &strName)
Add a group to this container.
bool DeleteGroup (const std::shared_ptr< CPVRChannelGroup > &group)
Remove a group from this container and delete it from the database.
bool HideGroup (const std::shared_ptr< CPVRChannelGroup > &group, bool bHide)
Hide/unhide a group in this container.
bool SetGroupName (const std::shared_ptr< CPVRChannelGroup > &group, const std::string &newGroupName, bool isUserSetName)
Change the name of the given group.
bool AppendToGroup (const std::shared_ptr< CPVRChannelGroup > &group, const std::shared_ptr< const CPVRChannelGroupMember > &groupMember)
Append a channel group member to the given group.
bool RemoveFromGroup (const std::shared_ptr< CPVRChannelGroup > &group, const std::shared_ptr< CPVRChannelGroupMember > &groupMember)
Remove a channel group member from the given group.
bool ResetGroupPositions (const std::vector< std::string > &sortedGroupPaths)
Reset the position of the given groups, then resort groups.
bool PersistAll ()
Persist all changes in channel groups.
bool IsRadio () const
bool UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > &clients, bool bChannelsOnly=false)
Update data with groups and channels from the given clients, sync with local data.
bool UpdateChannelNumbersFromAllChannelsGroup ()
Update the channel numbers across the channel groups from the all channels group.
int CleanupCachedImages ()
Erase stale texture db entries and image files.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Private Types
enum class Exclude { NONE , IGNORED }
enum class GroupState { DELETED , CHANGED }
Private Member Functions
void SortGroups ()
void SortGroupsByBackendOrder ()
void SortGroupsByLocalOrder ()
bool HasValidDataForClients (const std::vector< std::shared_ptr< CPVRClient > > &clients) const
Check, whether data for given pvr clients are currently valid. For instance, data can be invalid because the client's backend was offline when data was last queried.
void OnPVRManagerEvent (const PVR::PVREvent &event)
int GetGroupClientPriority (const std::shared_ptr< const CPVRChannelGroup > &group) const
std::shared_ptr< CPVRChannelGroup > GetGroupByName (const std::string &name, int clientID, Exclude exclude) const
std::shared_ptr< CPVRChannelGroup > GetGroupById (int groupId, Exclude exclude) const
void GroupStateChanged (const std::shared_ptr< CPVRChannelGroup > &group, GroupState state=GroupState::CHANGED)
void UpdateSystemChannelGroups ()
Private Attributes
bool m_bRadio {false}
std::vector< std::shared_ptr< CPVRChannelGroup > > m_groups
CCriticalSection m_critSection
std::vector< int > m_failedClientsForChannelGroups
bool m_isSubscribed {false}
CPVRSettings m_settings
std::shared_ptr< CPVRChannelGroup > m_allChannelsGroup
std::shared_ptr< CPVRChannelGroupFactory > m_channelGroupFactory
Detailed Description
A container class for channel groups
Member Enumeration Documentation
Exclude
enum class PVR::CPVRChannelGroups::Exclude strong private
Enumerator
NONE
IGNORED
GroupState
enum class PVR::CPVRChannelGroups::GroupState strong private
Enumerator
DELETED
CHANGED
Constructor & Destructor Documentation
CPVRChannelGroups()
CPVRChannelGroups::CPVRChannelGroups (bool bRadio) explicit
Create a new group container.
Parameters
bRadio True if this is a container for radio channels, false if it is for tv channels.
References CSettings::SETTING_PVRMANAGER_BACKENDCHANNELGROUPSORDER.
~CPVRChannelGroups()
CPVRChannelGroups::~CPVRChannelGroups () virtual
References m_settings, Unload(), and PVR::CPVRSettings::UnregisterCallback().
Member Function Documentation
AddGroup()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::AddGroup (const std::string & strName)
Add a group to this container.
Parameters
strName The name of the group.
Returns
The new group on success, nullptr otherwise.
References GetGroupAll(), GetGroupByName(), GetGroupFactory(), GroupStateChanged(), IsRadio(), m_critSection, m_groups, NONE, PVR::PVR_GROUP_CLIENT_ID_LOCAL, and PVR::CPVRChannelGroup::USER.
AppendToGroup()
bool CPVRChannelGroups::AppendToGroup (const std::shared_ptr< CPVRChannelGroup > & group, const std::shared_ptr< const CPVRChannelGroupMember > & groupMember)
Append a channel group member to the given group.
Parameters
group The group.
groupMember The channel group member to append.
Returns
True if the channel group member was appended, false otherwise.
References GroupStateChanged(), LOGERROR, and UpdateChannelNumbersFromAllChannelsGroup().
CleanupCachedImages()
int CPVRChannelGroups::CleanupCachedImages ()
Erase stale texture db entries and image files.
Returns
number of cleaned up images.
References PVR::CPVRCachedImages::Cleanup(), GetGroupAll(), IsRadio(), m_critSection, and m_groups.
DeleteGroup()
bool CPVRChannelGroups::DeleteGroup (const std::shared_ptr< CPVRChannelGroup > & group)
Remove a group from this container and delete it from the database.
Parameters
group The group to delete.
Returns
True if it was deleted successfully, false if not.
References DELETED, GroupStateChanged(), LOGERROR, m_critSection, and m_groups.
GetById()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::GetById (int iGroupId) const
Get a pointer to a channel group given its ID.
Parameters
iGroupId The ID of the group.
Returns
The group or NULL if it wasn't found.
References GetGroupById(), and IGNORED.
GetByName()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::GetByName (const std::string & strName, int clientID) const
Get a group given its name.
Parameters
strName The name.
clientID The id of the client of the group to obtain or PVR_GROUP_CLIENT_ID_LOCAL for local groups.
Returns
The group or NULL if it wasn't found.
References GetGroupByName(), and IGNORED.
Referenced by GetChannelGroupMemberByPath().
GetChannelGroupMemberByPath()
std::shared_ptr< CPVRChannelGroupMember > CPVRChannelGroups::GetChannelGroupMemberByPath (const CPVRChannelsPath & path) const
Get a channel group member given its path.
Parameters
strPath The path to the channel group member
Returns
The channel group member, or nullptr if not found
References PVR::CPVRChannelsPath::GetAddonID(), GetByName(), PVR::CPVRChannelsPath::GetChannelUID(), PVR::CPVRChannelsPath::GetGroupClientID(), PVR::CPVRChannelsPath::GetGroupName(), PVR::CPVRChannelsPath::GetInstanceID(), PVR::CPVRClientUID::GetUID(), and PVR::CPVRChannelsPath::IsChannel().
GetFirstGroup()
std::shared_ptr< CPVRChannelGroup > PVR::CPVRChannelGroups::GetFirstGroup () const inline
Returns
The first group in this container, which always is the group with all channels.
References GetGroupAll().
Referenced by GetNextGroup().
GetGroupAll()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::GetGroupAll () const
Get the group that contains all channels.
Returns
The group that contains all channels.
References m_allChannelsGroup, and m_critSection.
Referenced by AddGroup(), PVR::CPVRClient::cb_transfer_channel_group(), CleanupCachedImages(), GetFirstGroup(), PVR::CPVRDatabase::GetGroups(), GetMembersAvailableForGroup(), Update(), and UpdateSystemChannelGroups().
GetGroupById()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::GetGroupById (int groupId, Exclude exclude) const private
References IGNORED, m_critSection, and m_groups.
Referenced by GetById(), and Update().
GetGroupByName()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::GetGroupByName (const std::string & name, int clientID, Exclude exclude) const private
References IGNORED, m_critSection, m_groups, and name.
Referenced by AddGroup(), and GetByName().
GetGroupByPath()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::GetGroupByPath (const std::string & strPath) const
Get a channel group given its path.
Parameters
strPath The path to the channel group
Returns
The channel group, or nullptr if not found
References PVR::CPVRChannelsPath::IsChannelGroup(), m_critSection, and m_groups.
Referenced by ResetGroupPositions().
GetGroupClientPriority()
int CPVRChannelGroups::GetGroupClientPriority (const std::shared_ptr< const CPVRChannelGroup > & group) const private
GetGroupFactory()
std::shared_ptr< CPVRChannelGroupFactory > PVR::CPVRChannelGroups::GetGroupFactory () const inline
Get the channel group factory.
Returns
The factory.
References m_channelGroupFactory.
Referenced by AddGroup(), PVR::CPVRClient::cb_transfer_channel_group(), PVR::CPVRDatabase::GetGroups(), LoadFromDatabase(), SortGroupsByBackendOrder(), and UpdateSystemChannelGroups().
GetLastAndPreviousToLastPlayedChannelGroupMember()
GroupMemberPair CPVRChannelGroups::GetLastAndPreviousToLastPlayedChannelGroupMember () const
Returns
The last and previous to last played channel group members. pair.first contains the last, pair.second the previous to last member.
References m_critSection, and m_groups.
GetLastGroup()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::GetLastGroup () const
Returns
The last group in this container.
References m_critSection, and m_groups.
Referenced by GetPreviousGroup().
GetLastOpenedGroup()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::GetLastOpenedGroup () const
Returns
The last opened group.
References m_critSection, and m_groups.
GetMembers()
std::vector< std::shared_ptr< CPVRChannelGroup > > CPVRChannelGroups::GetMembers (bool bExcludeHidden = false) const
Get the list of groups.
Parameters
groups The list to store the results in.
bExcludeHidden Whenever to exclude hidden channel groups.
Returns
The amount of items that were added.
References m_critSection, and m_groups.
GetMembersAvailableForGroup()
std::vector< std::shared_ptr< CPVRChannelGroupMember > > CPVRChannelGroups::GetMembersAvailableForGroup (const std::shared_ptr< const CPVRChannelGroup > & group) const
Get all channel group members that could be added to the given group.
Parameters
group The group
Returns
The channel group members that could be added to the group
References GetGroupAll(), and m_critSection.
GetNextGroup()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::GetNextGroup (const CPVRChannelGroup & group) const
Get the next group in this container.
Parameters
group The current group.
Returns
The next group or the group containing all channels if it wasn't found.
References GetFirstGroup(), m_critSection, and m_groups.
GetPreviousGroup()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroups::GetPreviousGroup (const CPVRChannelGroup & group) const
Get the previous group in this container.
Parameters
group The current group.
Returns
The previous group or the group containing all channels if it wasn't found.
References GetLastGroup(), m_critSection, and m_groups.
GroupStateChanged()
void CPVRChannelGroups::GroupStateChanged (const std::shared_ptr< CPVRChannelGroup > & group, GroupState state = GroupState::CHANGED) private
References PVR::ChannelGroupsInvalidated, DELETED, CServiceBroker::GetPVRManager(), PVR::CPVRManager::PublishEvent(), and UpdateSystemChannelGroups().
Referenced by AddGroup(), AppendToGroup(), DeleteGroup(), HideGroup(), RemoveFromGroup(), and SetGroupName().
HasValidDataForClients()
bool CPVRChannelGroups::HasValidDataForClients (const std::vector< std::shared_ptr< CPVRClient > > & clients) const private
Check, whether data for given pvr clients are currently valid. For instance, data can be invalid because the client's backend was offline when data was last queried.
Parameters
clients The clients to check. Check all active clients if vector is empty.
Returns
True, if data is currently valid, false otherwise.
References m_failedClientsForChannelGroups.
HideGroup()
bool CPVRChannelGroups::HideGroup (const std::shared_ptr< CPVRChannelGroup > & group, bool bHide)
Hide/unhide a group in this container.
Parameters
group The group to hide/unhide.
bHide True to hide the group, false to unhide it.
Returns
True on success, false otherwise.
References GroupStateChanged().
IsRadio()
bool PVR::CPVRChannelGroups::IsRadio () const inline
Returns
True when this container contains radio groups, false otherwise
References m_bRadio.
Referenced by AddGroup(), CleanupCachedImages(), PVR::CPVRDatabase::Get(), PVR::CPVRClient::GetChannelGroups(), PVR::CPVRDatabase::GetLocalGroups(), and LoadFromDatabase().
LoadFromDatabase()
bool CPVRChannelGroups::LoadFromDatabase (const std::vector< std::shared_ptr< CPVRClient > > & clients)
Load all channel groups and all channels from PVR database.
Parameters
clients The PVR clients data should be loaded for. Leave empty for all clients.
Returns
True on success, false otherwise.
References PVR::CPVRManager::Events(), GetGroupFactory(), CServiceBroker::GetPVRManager(), IsRadio(), LOGDEBUG, LOGERROR, LOGPVR, m_allChannelsGroup, m_bRadio, m_critSection, m_groups, m_isSubscribed, OnPVRManagerEvent(), SortGroups(), and CEventStream< Event >::Subscribe().
OnPVRManagerEvent()
void CPVRChannelGroups::OnPVRManagerEvent (const PVR::PVREvent & event) private
References PVR::ClientsPrioritiesInvalidated, m_critSection, m_groups, and SortGroups().
Referenced by LoadFromDatabase().
OnSettingChanged()
void CPVRChannelGroups::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References LOGERROR, CSettings::SETTING_PVRMANAGER_BACKENDCHANNELGROUPSORDER, and SortGroups().
PersistAll()
bool CPVRChannelGroups::PersistAll ()
Persist all changes in channel groups.
Returns
True if everything was persisted, false otherwise.
References LOGDEBUG, LOGPVR, m_critSection, m_groups, and success.
Referenced by ResetGroupPositions(), and UpdateFromClients().
RemoveFromGroup()
bool CPVRChannelGroups::RemoveFromGroup (const std::shared_ptr< CPVRChannelGroup > & group, const std::shared_ptr< CPVRChannelGroupMember > & groupMember)
Remove a channel group member from the given group.
Parameters
group The group.
groupMember The channel group member to remove.
Returns
True if the channel group member was removed, false otherwise.
References GroupStateChanged(), LOGERROR, and UpdateChannelNumbersFromAllChannelsGroup().
ResetGroupPositions()
bool CPVRChannelGroups::ResetGroupPositions (const std::vector< std::string > & sortedGroupPaths)
Reset the position of the given groups, then resort groups.
Parameters
sortedGroupPaths The paths of the groups to re-position.
Returns
True if any group position was changed, false otherwise.
References PVR::ChannelGroupsInvalidated, GetGroupByPath(), CServiceBroker::GetPVRManager(), LOGERROR, LOGPVR, PersistAll(), PVR::CPVRManager::PublishEvent(), SortGroups(), and success.
SetGroupName()
bool CPVRChannelGroups::SetGroupName (const std::shared_ptr< CPVRChannelGroup > & group, const std::string & newGroupName, bool isUserSetName)
Change the name of the given group.
Parameters
group The group.
newGroupName The new group name.
isUserSetName Whether the name was set by the user.
Returns
True if the group name was changed, false otherwise.
References GroupStateChanged().
Size()
size_t PVR::CPVRChannelGroups::Size () const inline
Returns
Amount of groups in this container
References m_critSection, and m_groups.
SortGroups()
void CPVRChannelGroups::SortGroups () private
References PVR::ChannelGroupsInvalidated, PVR::CPVRSettings::GetBoolValue(), CServiceBroker::GetPVRManager(), m_settings, PVR::CPVRManager::PublishEvent(), CSettings::SETTING_PVRMANAGER_BACKENDCHANNELGROUPSORDER, SortGroupsByBackendOrder(), and SortGroupsByLocalOrder().
Referenced by LoadFromDatabase(), OnPVRManagerEvent(), OnSettingChanged(), ResetGroupPositions(), UpdateFromClient(), and UpdateSystemChannelGroups().
SortGroupsByBackendOrder()
void CPVRChannelGroups::SortGroupsByBackendOrder () private
References GetGroupFactory(), m_critSection, and m_groups.
Referenced by SortGroups().
SortGroupsByLocalOrder()
void CPVRChannelGroups::SortGroupsByLocalOrder () private
References m_critSection, and m_groups.
Referenced by SortGroups().
Unload()
void CPVRChannelGroups::Unload ()
Remove all groups from this container.
References PVR::CPVRManager::Events(), CServiceBroker::GetPVRManager(), m_allChannelsGroup, m_channelGroupFactory, m_critSection, m_failedClientsForChannelGroups, m_groups, m_isSubscribed, and CEventStream< Event >::Unsubscribe().
Referenced by ~CPVRChannelGroups().
Update()
bool CPVRChannelGroups::Update (const std::shared_ptr< CPVRChannelGroup > & group, bool bUpdateFromClient = false)
Update a group or add it if it's not in here yet.
Parameters
group The group to update.
bUpdateFromClient True to save the changes in the db.
Returns
True if the group was added or update successfully, false otherwise.
Todo:
If a group was renamed in the backend, no chance to find it here! PVR API should be extended by a uuid for channel groups which never must change, not even after rename.
References GetGroupAll(), GetGroupById(), m_critSection, m_groups, and NONE.
Referenced by PVR::CPVRDatabase::GetGroups().
UpdateChannelNumbersFromAllChannelsGroup()
bool CPVRChannelGroups::UpdateChannelNumbersFromAllChannelsGroup ()
Update the channel numbers across the channel groups from the all channels group.
Returns
True if any channel number was changed, false otherwise.
References m_critSection, and m_groups.
Referenced by AppendToGroup(), RemoveFromGroup(), and UpdateFromClients().
UpdateFromClient()
bool CPVRChannelGroups::UpdateFromClient (const std::shared_ptr< CPVRChannelGroup > & group)
Called by the add-on callback to add a new group.
Parameters
group The group to add
Returns
True when updated, false otherwise
References LOGDEBUG, LOGPVR, SortGroups(), and Update.
Referenced by PVR::CPVRClient::cb_transfer_channel_group().
UpdateFromClients()
bool CPVRChannelGroups::UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > & clients, bool bChannelsOnly = false)
Update data with groups and channels from the given clients, sync with local data.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
bChannelsOnly Set to true to only update channels, not the groups themselves.
Returns
True on success, false otherwise.
References PVR::ChannelGroupsInvalidated, PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), LOGERROR, LOGPVR, m_critSection, m_failedClientsForChannelGroups, m_groups, PersistAll(), PVR::CPVRManager::PublishEvent(), PVR::CPVRManager::TriggerSearchMissingChannelIcons(), UpdateChannelNumbersFromAllChannelsGroup(), and UpdateSystemChannelGroups().
UpdateSystemChannelGroups()
void CPVRChannelGroups::UpdateSystemChannelGroups () private
References GetGroupAll(), GetGroupFactory(), m_critSection, m_groups, and SortGroups().
Referenced by GroupStateChanged(), and UpdateFromClients().
Member Data Documentation
m_allChannelsGroup
std::shared_ptr<CPVRChannelGroup> PVR::CPVRChannelGroups::m_allChannelsGroup private
Referenced by GetGroupAll(), LoadFromDatabase(), and Unload().
m_bRadio
bool PVR::CPVRChannelGroups::m_bRadio {false} private
Referenced by IsRadio(), and LoadFromDatabase().
m_channelGroupFactory
std::shared_ptr<CPVRChannelGroupFactory> PVR::CPVRChannelGroups::m_channelGroupFactory private
Referenced by GetGroupFactory(), and Unload().
m_critSection
CCriticalSection PVR::CPVRChannelGroups::m_critSection mutable private
Referenced by AddGroup(), CleanupCachedImages(), DeleteGroup(), GetGroupAll(), GetGroupById(), GetGroupByName(), GetGroupByPath(), GetLastAndPreviousToLastPlayedChannelGroupMember(), GetLastGroup(), GetLastOpenedGroup(), GetMembers(), GetMembersAvailableForGroup(), GetNextGroup(), GetPreviousGroup(), LoadFromDatabase(), OnPVRManagerEvent(), PersistAll(), Size(), SortGroupsByBackendOrder(), SortGroupsByLocalOrder(), Unload(), Update(), UpdateChannelNumbersFromAllChannelsGroup(), UpdateFromClients(), and UpdateSystemChannelGroups().
m_failedClientsForChannelGroups
std::vector<int> PVR::CPVRChannelGroups::m_failedClientsForChannelGroups private
Referenced by HasValidDataForClients(), Unload(), and UpdateFromClients().
m_groups
std::vector<std::shared_ptr<CPVRChannelGroup> > PVR::CPVRChannelGroups::m_groups private
Referenced by AddGroup(), CleanupCachedImages(), DeleteGroup(), GetGroupById(), GetGroupByName(), GetGroupByPath(), GetLastAndPreviousToLastPlayedChannelGroupMember(), GetLastGroup(), GetLastOpenedGroup(), GetMembers(), GetNextGroup(), GetPreviousGroup(), LoadFromDatabase(), OnPVRManagerEvent(), PersistAll(), Size(), SortGroupsByBackendOrder(), SortGroupsByLocalOrder(), Unload(), Update(), UpdateChannelNumbersFromAllChannelsGroup(), UpdateFromClients(), and UpdateSystemChannelGroups().
m_isSubscribed
bool PVR::CPVRChannelGroups::m_isSubscribed {false} private
Referenced by LoadFromDatabase(), and Unload().
m_settings
CPVRSettings PVR::CPVRChannelGroups::m_settings private
Referenced by SortGroups(), and ~CPVRChannelGroups().
The documentation for this class was generated from the following files:
PVRChannelGroups.h
PVRChannelGroups.cpp