Kodi Documentation: CVideoInfoTag::CAssetInfo Class Reference
CVideoInfoTag::CAssetInfo Class Reference
#include <VideoInfoTag.h>
Public Member Functions
void Clear ()
Clear all data.
void Archive (CArchive &ar)
Archive all data.
void Save (TiXmlNode *movie)
Store all data to XML.
void ParseNative (const TiXmlElement *movie)
Restore all data from XML.
void Merge (CAssetInfo &other)
Merge in all valid data from another asset info.
void Serialize (CVariant &value) const
Serialize all data.
const std::string & GetTitle () const
Get the video's asset title.
void SetTitle (const std::string &assetTitle)
Set this videos's asset title.
int GetId () const
Get the video's asset id.
void SetId (int assetId)
Set this videos's asset id.
VideoAssetType GetType () const
Get the video's asset type.
void SetType (VideoAssetType assetType)
Set this videos's asset type.
Private Attributes
std::string m_title
int m_id {-1}
VideoAssetType m_type {-1}
Member Function Documentation
Archive()
void CVideoInfoTag::CAssetInfo::Archive (CArchive & ar)
Archive all data.
Parameters
ar The archive to write the data to / to read the data from.
References CArchive::IsStoring(), and CVideoInfoTag::m_type.
Referenced by CVideoInfoTag::Archive().
Clear()
void CVideoInfoTag::CAssetInfo::Clear ()
Clear all data.
References m_id, m_title, m_type, and UNKNOWN.
Referenced by CVideoInfoTag::Reset().
GetId()
int CVideoInfoTag::CAssetInfo::GetId () const inline
Get the video's asset id.
Returns
The id or -1 if the item has no video asset.
References m_id.
Referenced by CGUIDialogVideoInfo::OnSearchItemFound(), and anonymous_namespace{VideoDatabase.cpp}::RewriteVideoVersionURL().
GetTitle()
const std::string & CVideoInfoTag::CAssetInfo::GetTitle () const inline
Get the video's asset title.
Returns
The title or an empty string if the item has no video asset.
References m_title.
Referenced by CVideoInfoTag::ToSortable().
GetType()
VideoAssetType CVideoInfoTag::CAssetInfo::GetType () const inline
Get the video's asset type.
Returns
The type or VideoAssetType::UNKNOWN if the item has no video asset.
References m_type.
Referenced by CVideoThumbLoader::FillLibraryArt().
Merge()
void CVideoInfoTag::CAssetInfo::Merge (CAssetInfo & other)
Merge in all valid data from another asset info.
Parameters
other The other asset info.
References m_id, m_title, m_type, CVideoInfoTag::m_type, and UNKNOWN.
Referenced by CVideoInfoTag::Merge().
ParseNative()
void CVideoInfoTag::CAssetInfo::ParseNative (const TiXmlElement * movie)
Restore all data from XML.
Parameters
movie The XML element containing the data.
References XMLUtils::GetInt(), XMLUtils::GetString(), CVideoInfoTag::m_type, and value.
Referenced by CVideoInfoTag::ParseNative().
Save()
void CVideoInfoTag::CAssetInfo::Save (TiXmlNode * movie)
Store all data to XML.
Parameters
movie The XML element to write the data to.
References CVideoInfoTag::m_type, XMLUtils::SetInt(), and XMLUtils::SetString().
Referenced by CVideoInfoTag::Save().
Serialize()
void CVideoInfoTag::CAssetInfo::Serialize (CVariant & value) const
Serialize all data.
Parameters
value The container to write the data to.
References CVideoInfoTag::m_type, and value.
Referenced by CVideoInfoTag::Serialize().
SetId()
void CVideoInfoTag::CAssetInfo::SetId (int assetId)
Set this videos's asset id.
Parameters
assetId The id.
Referenced by CVideoDatabase::GetDefaultVideoVersion(), CVideoDatabase::GetDetailsForMovie(), and CVideoDatabase::GetVideoVersions().
SetTitle()
void CVideoInfoTag::CAssetInfo::SetTitle (const std::string & assetTitle)
Set this videos's asset title.
Parameters
assetTitle The title.
Referenced by CVideoDatabase::GetDefaultVideoVersion(), CVideoDatabase::GetVideoVersions(), and XBMCAddon::xbmc::InfoTagVideo::setVideoAssetTitleRaw().
SetType()
void CVideoInfoTag::CAssetInfo::SetType (VideoAssetType assetType)
Set this videos's asset type.
Parameters
assetType The type.
References CVideoInfoTag::m_type.
Referenced by CVideoDatabase::GetDefaultVideoVersion(), and CVideoDatabase::GetVideoVersions().
Member Data Documentation
m_id
int CVideoInfoTag::CAssetInfo::m_id {-1} private
Referenced by Clear(), GetId(), and Merge().
m_title
std::string CVideoInfoTag::CAssetInfo::m_title private
Referenced by Clear(), GetTitle(), and Merge().
m_type
VideoAssetType CVideoInfoTag::CAssetInfo::m_type {-1} private
Referenced by Clear(), GetType(), and Merge().
The documentation for this class was generated from the following files:
VideoInfoTag.h
VideoInfoTag.cpp