Kodi Documentation: XFILE::CXbtManager Class Reference
XFILE::CXbtManager Class Reference
#include <XbtManager.h>
Classes
struct XBTFReader
Public Member Functions
~CXbtManager ()
bool HasFiles (const CURL &path) const
bool GetFiles (const CURL &path, std::vector< CXBTFFile > &files) const
bool GetReader (const CURL &path, CXBTFReaderPtr &reader) const
void Release (const CURL &path)
Static Public Member Functions
static CXbtManager & GetInstance ()
Private Types
using XBTFReaders = std::map< std::string, XBTFReader >
Private Member Functions
CXbtManager ()
CXbtManager (const CXbtManager &)=delete
CXbtManager & operator= (const CXbtManager &)=delete
XBTFReaders::iterator GetReader (const CURL &path) const
XBTFReaders::iterator GetReader (const std::string &path) const
void RemoveReader (XBTFReaders::iterator readerIterator) const
XBTFReaders::const_iterator ProcessFile (const CURL &path) const
Static Private Member Functions
static std::string NormalizePath (const CURL &path)
Private Attributes
XBTFReaders m_readers
CCriticalSection m_lock
Member Typedef Documentation
XBTFReaders
using XFILE::CXbtManager::XBTFReaders = std::map<std::string, XBTFReader> private
Constructor & Destructor Documentation
~CXbtManager()
XFILE::CXbtManager::~CXbtManager () default
CXbtManager() [1/2]
XFILE::CXbtManager::CXbtManager () private default
CXbtManager() [2/2]
XFILE::CXbtManager::CXbtManager (const CXbtManager &) private delete
Member Function Documentation
GetFiles()
bool XFILE::CXbtManager::GetFiles (const CURL & path, std::vector< CXBTFFile > & files) const
References m_lock, m_readers, and ProcessFile().
GetInstance()
CXbtManager & XFILE::CXbtManager::GetInstance () static
Referenced by CTextureBundleXBT::CloseBundle(), XFILE::CXbtDirectory::ContainsFiles(), XFILE::CXbtDirectory::GetDirectory(), XFILE::CXbtFile::GetReader(), ADDON::CImageResource::OnPreUnInstall(), and CTextureBundleXBT::OpenBundle().
GetReader() [1/3]
CXbtManager::XBTFReaders::iterator XFILE::CXbtManager::GetReader (const CURL & path) const private
References GetReader(), and NormalizePath().
GetReader() [2/3]
bool XFILE::CXbtManager::GetReader (const CURL & path, CXBTFReaderPtr & reader) const
References m_lock, m_readers, and ProcessFile().
Referenced by GetReader(), XFILE::CXbtFile::GetReader(), ProcessFile(), and Release().
GetReader() [3/3]
CXbtManager::XBTFReaders::iterator XFILE::CXbtManager::GetReader (const std::string & path) const private
References m_readers.
HasFiles()
bool XFILE::CXbtManager::HasFiles (const CURL & path) const
References m_lock, m_readers, and ProcessFile().
Referenced by XFILE::CXbtDirectory::ContainsFiles().
NormalizePath()
std::string XFILE::CXbtManager::NormalizePath (const CURL & path) static private
References CURL::Get(), CURL::GetHostName(), and CURL::IsProtocol().
Referenced by GetReader(), and ProcessFile().
operator=()
CXbtManager & XFILE::CXbtManager::operator= (const CXbtManager &) private delete
ProcessFile()
CXbtManager::XBTFReaders::const_iterator XFILE::CXbtManager::ProcessFile (const CURL & path) const private
References GetReader(), m_readers, NormalizePath(), and RemoveReader().
Referenced by GetFiles(), GetReader(), and HasFiles().
Release()
void XFILE::CXbtManager::Release (const CURL & path)
References GetReader(), m_lock, m_readers, and RemoveReader().
Referenced by CTextureBundleXBT::CloseBundle(), and ADDON::CImageResource::OnPreUnInstall().
RemoveReader()
void XFILE::CXbtManager::RemoveReader (XBTFReaders::iterator readerIterator) const private
References m_readers.
Referenced by ProcessFile(), and Release().
Member Data Documentation
m_lock
CCriticalSection XFILE::CXbtManager::m_lock mutable private
Referenced by GetFiles(), GetReader(), HasFiles(), and Release().
m_readers
XBTFReaders XFILE::CXbtManager::m_readers mutable private
Referenced by GetFiles(), GetReader(), GetReader(), HasFiles(), ProcessFile(), Release(), and RemoveReader().
The documentation for this class was generated from the following files:
XbtManager.h
XbtManager.cpp