Kodi Documentation: WeatherBuiltins.cpp File Reference
WeatherBuiltins.cpp File Reference
#include "WeatherBuiltins.h"
#include "ServiceBroker.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include <stdlib.h>
Functions
static int SetLocation (const std::vector< std::string > &params)
Switch to a given weather location.
template<int Direction>
static int SwitchLocation (const std::vector< std::string > &params)
Switch weather location or refresh current.
Function Documentation
SetLocation()
static int SetLocation (const std::vector< std::string > & params) static
Switch to a given weather location.
Parameters
params The parameters.
params[0] = 1, 2 or 3.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_ITEM_SELECT, CGUIWindowManager::SendMessage(), and WINDOW_WEATHER.
Referenced by CWeatherBuiltins::GetOperations().
SwitchLocation()
template<int Direction> static int SwitchLocation (const std::vector< std::string > & params) static
Switch weather location or refresh current.
Parameters
params (ignored)
The Direction template parameter can be -1 for previous location, 1 for next location or 0 to refresh current location.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_MOVE_OFFSET, CGUIWindowManager::SendMessage(), and WINDOW_WEATHER.
Referenced by CWeatherBuiltins::GetOperations().