Kodi Documentation: ADDON::Interface_GUIDialogTextViewer Struct Reference
ADDON::Interface_GUIDialogTextViewer Struct Reference
Global gui Add-on to Kodi callback functions.
#include <TextViewer.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void open (KODI_HANDLE kodiBase, const char *heading, const char *text)
callback functions from add-on to kodi
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/dialogs/TextViewer.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIDialogTextViewer::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogTextViewer, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
Init()
void ADDON::Interface_GUIDialogTextViewer::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogTextViewer, AddonToKodiFuncTable_Addon::kodi_gui, open(), AddonToKodiFuncTable_kodi_gui_dialogTextViewer::open, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
open()
void ADDON::Interface_GUIDialogTextViewer::open (KODI_HANDLE kodiBase, const char * heading, const char * text) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUIDialog::Open(), CGUIDialogTextViewer::SetHeading(), CGUIDialogTextViewer::SetText(), text, and WINDOW_DIALOG_TEXT_VIEWER.
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/dialogs/TextViewer.h
TextViewer.cpp