Kodi Documentation: CJobWorker Class Reference
CJobWorker Class Reference
#include <JobManager.h>
Public Member Functions
CJobWorker (CJobManager *manager)
~CJobWorker () override
void Process () override
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Attributes
CJobManager * m_jobManager
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CJobWorker()
CJobWorker::CJobWorker (CJobManager * manager) explicit
References CThread::Create(), and m_jobManager.
~CJobWorker()
CJobWorker::~CJobWorker () override
References CThread::IsAutoDelete(), m_jobManager, CJobManager::RemoveWorker(), and CThread::StopThread().
Member Function Documentation
Process()
void CJobWorker::Process (void) override virtual
Reimplemented from CThread.
References CJob::DoWork(), CJobManager::GetNextJob(), CJob::GetType(), CLog::Log(), LOGERROR, LOWEST, m_jobManager, CJobManager::OnJobComplete(), CThread::SetPriority(), and success.
Member Data Documentation
m_jobManager
CJobManager* CJobWorker::m_jobManager private
Referenced by CJobWorker(), Process(), and ~CJobWorker().
The documentation for this class was generated from the following files:
JobManager.h
JobManager.cpp