Kodi Documentation: KODI::GAME::CGUIFeatureFactory Class Reference
KODI::GAME::CGUIFeatureFactory Class Reference
Games
#include <GUIFeatureFactory.h>
Static Public Member Functions
static CGUIButtonControl * CreateButton (BUTTON_TYPE type, const CGUIButtonControl &buttonTemplate, IConfigurationWizard *wizard, const CPhysicalFeature &feature, unsigned int index)
Create a button of the specified type.
Member Function Documentation
CreateButton()
CGUIButtonControl * CGUIFeatureFactory::CreateButton (BUTTON_TYPE type, const CGUIButtonControl & buttonTemplate, IConfigurationWizard * wizard, const CPhysicalFeature & feature, unsigned int index) static
Create a button of the specified type.
Parameters
type The type of button control being created
Returns
A button control, or nullptr if type is invalid
References KODI::GAME::ANALOG_STICK, KODI::GAME::BUTTON, index(), KODI::GAME::RELATIVE_POINTER, KODI::GAME::SELECT_KEY, KODI::GAME::THROTTLE, and KODI::GAME::WHEEL.
Referenced by KODI::GAME::CGUIFeatureList::GetButtons(), and KODI::GAME::CGUIFeatureList::GetSelectKeyButton().
The documentation for this class was generated from the following files:
GUIFeatureFactory.h
GUIFeatureFactory.cpp