Kodi Documentation: SortUtils.cpp File Reference
SortUtils.cpp File Reference
#include "SortUtils.h"
#include "LangInfo.h"
#include "URL.h"
#include "Util.h"
#include "utils/CharsetConverter.h"
#include "utils/StringUtils.h"
#include "utils/Variant.h"
#include <algorithm>
#include <inttypes.h>
Classes
struct sort_map
Functions
std::string ArrayToString (SortAttribute attributes, const CVariant &variant, const std::string &separator=" / ")
std::string ByLabel (SortAttribute attributes, const SortItem &values)
std::string ByFile (SortAttribute attributes, const SortItem &values)
std::string ByPath (SortAttribute attributes, const SortItem &values)
std::string ByLastPlayed (SortAttribute attributes, const SortItem &values)
std::string ByPlaycount (SortAttribute attributes, const SortItem &values)
std::string ByDate (SortAttribute attributes, const SortItem &values)
std::string ByDateAdded (SortAttribute attributes, const SortItem &values)
std::string BySize (SortAttribute attributes, const SortItem &values)
std::string ByDriveType (SortAttribute attributes, const SortItem &values)
std::string ByTitle (SortAttribute attributes, const SortItem &values)
std::string ByAlbum (SortAttribute attributes, const SortItem &values)
std::string ByAlbumType (SortAttribute attributes, const SortItem &values)
std::string ByArtist (SortAttribute attributes, const SortItem &values)
std::string ByArtistThenYear (SortAttribute attributes, const SortItem &values)
std::string ByTrackNumber (SortAttribute attributes, const SortItem &values)
std::string ByTotalDiscs (SortAttribute attributes, const SortItem &values)
std::string ByTime (SortAttribute attributes, const SortItem &values)
std::string ByProgramCount (SortAttribute attributes, const SortItem &values)
std::string ByPlaylistOrder (SortAttribute attributes, const SortItem &values)
std::string ByGenre (SortAttribute attributes, const SortItem &values)
std::string ByCountry (SortAttribute attributes, const SortItem &values)
std::string ByYear (SortAttribute attributes, const SortItem &values)
std::string ByOrigDate (SortAttribute attributes, const SortItem &values)
std::string BySortTitle (SortAttribute attributes, const SortItem &values)
std::string ByOriginalTitle (SortAttribute attributes, const SortItem &values)
std::string ByRating (SortAttribute attributes, const SortItem &values)
std::string ByUserRating (SortAttribute attributes, const SortItem &values)
std::string ByVotes (SortAttribute attributes, const SortItem &values)
std::string ByTop250 (SortAttribute attributes, const SortItem &values)
std::string ByMPAA (SortAttribute attributes, const SortItem &values)
std::string ByStudio (SortAttribute attributes, const SortItem &values)
std::string ByEpisodeNumber (SortAttribute attributes, const SortItem &values)
std::string BySeason (SortAttribute attributes, const SortItem &values)
std::string ByNumberOfEpisodes (SortAttribute attributes, const SortItem &values)
std::string ByNumberOfWatchedEpisodes (SortAttribute attributes, const SortItem &values)
std::string ByTvShowStatus (SortAttribute attributes, const SortItem &values)
std::string ByTvShowTitle (SortAttribute attributes, const SortItem &values)
std::string ByProductionCode (SortAttribute attributes, const SortItem &values)
std::string ByVideoResolution (SortAttribute attributes, const SortItem &values)
std::string ByVideoCodec (SortAttribute attributes, const SortItem &values)
std::string ByVideoAspectRatio (SortAttribute attributes, const SortItem &values)
std::string ByAudioChannels (SortAttribute attributes, const SortItem &values)
std::string ByAudioCodec (SortAttribute attributes, const SortItem &values)
std::string ByAudioLanguage (SortAttribute attributes, const SortItem &values)
std::string BySubtitleLanguage (SortAttribute attributes, const SortItem &values)
std::string ByBitrate (SortAttribute attributes, const SortItem &values)
std::string ByListeners (SortAttribute attributes, const SortItem &values)
std::string ByRandom (SortAttribute attributes, const SortItem &values)
std::string ByChannel (SortAttribute attributes, const SortItem &values)
std::string ByChannelNumber (SortAttribute attributes, const SortItem &values)
std::string ByClientChannelOrder (SortAttribute attributes, const SortItem &values)
std::string ByProvider (SortAttribute attributes, const SortItem &values)
std::string ByUserPreference (SortAttribute attributes, const SortItem &values)
std::string ByDateTaken (SortAttribute attributes, const SortItem &values)
std::string ByRelevance (SortAttribute attributes, const SortItem &values)
std::string ByInstallDate (SortAttribute attributes, const SortItem &values)
std::string ByLastUpdated (SortAttribute attributes, const SortItem &values)
std::string ByLastUsed (SortAttribute attributes, const SortItem &values)
std::string ByBPM (SortAttribute attributes, const SortItem &values)
bool preliminarySort (const SortItem &left, const SortItem &right, bool handleFolder, bool &result, std::wstring &labelLeft, std::wstring &labelRight)
bool SorterAscending (const SortItem &left, const SortItem &right)
bool SorterDescending (const SortItem &left, const SortItem &right)
bool SorterIgnoreFoldersAscending (const SortItem &left, const SortItem &right)
bool SorterIgnoreFoldersDescending (const SortItem &left, const SortItem &right)
bool SorterIndirectAscending (const SortItemPtr &left, const SortItemPtr &right)
bool SorterIndirectDescending (const SortItemPtr &left, const SortItemPtr &right)
bool SorterIndirectIgnoreFoldersAscending (const SortItemPtr &left, const SortItemPtr &right)
bool SorterIndirectIgnoreFoldersDescending (const SortItemPtr &left, const SortItemPtr &right)
std::map< SortBy, SortUtils::SortPreparator > fillPreparators ()
std::map< SortBy, Fields > fillSortingFields ()
template<typename T >
T TypeFromString (const std::map< std::string, T > &typeMap, const std::string &name, const T &defaultType)
template<typename T >
const std::string & TypeToString (const std::map< std::string, T > &typeMap, const T &value)
Variables
const sort_map table []
const std::map< std::string, SortBy > sortMethods
Sort methods to translate string values to enum values.
const std::map< std::string, SortOrder > sortOrders
Function Documentation
ArrayToString()
std::string ArrayToString (SortAttribute attributes, const CVariant & variant, const std::string & separator = " / ")
References KODI::UTILS::StringUtils::Join(), SortUtils::RemoveArticles(), and SortAttributeIgnoreArticle.
Referenced by ByAlbum(), ByArtist(), ByArtistThenYear(), ByCountry(), ByGenre(), and ByStudio().
ByAlbum()
std::string ByAlbum (SortAttribute attributes, const SortItem & values)
References ArrayToString(), FieldAlbum, FieldArtist, FieldTrackNumber, KODI::UTILS::StringUtils::Format(), label, SortUtils::RemoveArticles(), SortAttributeIgnoreArticle, and values.
Referenced by fillPreparators().
ByAlbumType()
std::string ByAlbumType (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldAlbumType, and values.
Referenced by fillPreparators().
ByArtist()
std::string ByArtist (SortAttribute attributes, const SortItem & values)
References ArrayToString(), CVariant::asString(), FieldAlbum, FieldArtist, FieldArtistSort, FieldTrackNumber, KODI::UTILS::StringUtils::Format(), CVariant::isNull(), label, SortUtils::RemoveArticles(), SortAttributeUseArtistSortName, and values.
Referenced by fillPreparators().
ByArtistThenYear()
std::string ByArtistThenYear (SortAttribute attributes, const SortItem & values)
References ArrayToString(), CVariant::asInteger(), CVariant::asString(), FieldAlbum, FieldArtist, FieldArtistSort, FieldTrackNumber, FieldYear, KODI::UTILS::StringUtils::Format(), CVariant::isNull(), label, SortUtils::RemoveArticles(), SortAttributeUseArtistSortName, and values.
Referenced by fillPreparators().
ByAudioChannels()
std::string ByAudioChannels (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldAudioChannels, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByAudioCodec()
std::string ByAudioCodec (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldAudioCodec, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByAudioLanguage()
std::string ByAudioLanguage (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldAudioLanguage, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByBitrate()
std::string ByBitrate (SortAttribute attributes, const SortItem & values)
References FieldBitrate, and values.
Referenced by fillPreparators().
ByBPM()
std::string ByBPM (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldBPM, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByChannel()
std::string ByChannel (SortAttribute attributes, const SortItem & values)
References FieldChannelName, and values.
Referenced by fillPreparators().
ByChannelNumber()
std::string ByChannelNumber (SortAttribute attributes, const SortItem & values)
References FieldChannelNumber, and values.
Referenced by fillPreparators().
ByClientChannelOrder()
std::string ByClientChannelOrder (SortAttribute attributes, const SortItem & values)
References FieldClientChannelOrder, and values.
Referenced by fillPreparators().
ByCountry()
std::string ByCountry (SortAttribute attributes, const SortItem & values)
References ArrayToString(), FieldCountry, and values.
Referenced by fillPreparators().
ByDate()
std::string ByDate (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldDate, and values.
Referenced by fillPreparators().
ByDateAdded()
std::string ByDateAdded (SortAttribute attributes, const SortItem & values)
References FieldDateAdded, FieldId, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByDateTaken()
std::string ByDateTaken (SortAttribute attributes, const SortItem & values)
References FieldDateTaken, and values.
Referenced by fillPreparators().
ByDriveType()
std::string ByDriveType (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldDriveType, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByEpisodeNumber()
std::string ByEpisodeNumber (SortAttribute attributes, const SortItem & values)
References CVariant::asInteger(), ByLabel(), BySortTitle(), FieldEpisodeNumber, FieldEpisodeNumberSpecialSort, FieldMediaType, FieldSeason, FieldSeasonSpecialSort, KODI::UTILS::StringUtils::Format(), CVariant::isNull(), MediaTypeMovie, and values.
Referenced by fillPreparators().
ByFile()
std::string ByFile (SortAttribute attributes, const SortItem & values)
References FieldPath, FieldStartOffset, KODI::UTILS::StringUtils::Format(), CURL::GetFileNameWithoutPath(), and values.
Referenced by fillPreparators().
ByGenre()
std::string ByGenre (SortAttribute attributes, const SortItem & values)
References ArrayToString(), FieldGenre, and values.
Referenced by fillPreparators().
ByInstallDate()
std::string ByInstallDate (SortAttribute attributes, const SortItem & values)
References FieldInstallDate, and values.
Referenced by fillPreparators().
ByLabel()
std::string ByLabel (SortAttribute attributes, const SortItem & values)
References FieldLabel, SortUtils::RemoveArticles(), SortAttributeIgnoreArticle, and values.
Referenced by ByAlbumType(), ByAudioChannels(), ByAudioCodec(), ByAudioLanguage(), ByBPM(), ByDate(), ByDriveType(), ByEpisodeNumber(), ByLastPlayed(), ByMPAA(), ByNumberOfEpisodes(), ByNumberOfWatchedEpisodes(), ByOrigDate(), ByPlaycount(), ByRating(), BySeason(), BySubtitleLanguage(), ByTop250(), ByTotalDiscs(), ByTvShowStatus(), ByTvShowTitle(), ByUserRating(), ByVideoAspectRatio(), ByVideoCodec(), ByVideoResolution(), ByVotes(), ByYear(), and fillPreparators().
ByLastPlayed()
std::string ByLastPlayed (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldLastPlayed, KODI::UTILS::StringUtils::Format(), SortAttributeIgnoreLabel, and values.
Referenced by fillPreparators().
ByLastUpdated()
std::string ByLastUpdated (SortAttribute attributes, const SortItem & values)
References FieldLastUpdated, and values.
Referenced by fillPreparators().
ByLastUsed()
std::string ByLastUsed (SortAttribute attributes, const SortItem & values)
References FieldLastUsed, and values.
Referenced by fillPreparators().
ByListeners()
std::string ByListeners (SortAttribute attributes, const SortItem & values)
References FieldListeners, and values.
Referenced by fillPreparators().
ByMPAA()
std::string ByMPAA (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldMPAA, and values.
Referenced by fillPreparators().
ByNumberOfEpisodes()
std::string ByNumberOfEpisodes (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldNumberOfEpisodes, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByNumberOfWatchedEpisodes()
std::string ByNumberOfWatchedEpisodes (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldNumberOfWatchedEpisodes, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByOrigDate()
std::string ByOrigDate (SortAttribute attributes, const SortItem & values)
References CVariant::asString(), ByLabel(), FieldAlbum, FieldOrigDate, FieldTrackNumber, KODI::UTILS::StringUtils::Format(), CVariant::isNull(), label, SortUtils::RemoveArticles(), and values.
Referenced by fillPreparators().
ByOriginalTitle()
std::string ByOriginalTitle (SortAttribute attributes, const SortItem & values)
References FieldOriginalTitle, FieldSortTitle, FieldTitle, SortUtils::RemoveArticles(), SortAttributeIgnoreArticle, and values.
Referenced by fillPreparators().
ByPath()
std::string ByPath (SortAttribute attributes, const SortItem & values)
References FieldPath, FieldStartOffset, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByPlaycount()
std::string ByPlaycount (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldPlaycount, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByPlaylistOrder()
std::string ByPlaylistOrder (SortAttribute attributes, const SortItem & values)
Todo:
Playlist order is hacked into program count variable (not nice, but ok until 2.0)
References ByProgramCount(), and values.
Referenced by fillPreparators().
ByProductionCode()
std::string ByProductionCode (SortAttribute attributes, const SortItem & values)
References FieldProductionCode, and values.
Referenced by fillPreparators().
ByProgramCount()
std::string ByProgramCount (SortAttribute attributes, const SortItem & values)
References FieldProgramCount, and values.
Referenced by ByPlaylistOrder(), and fillPreparators().
ByProvider()
std::string ByProvider (SortAttribute attributes, const SortItem & values)
References FieldProvider, and values.
Referenced by fillPreparators().
ByRandom()
std::string ByRandom (SortAttribute attributes, const SortItem & values)
References CUtil::GetRandomNumber().
Referenced by fillPreparators().
ByRating()
std::string ByRating (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldRating, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByRelevance()
std::string ByRelevance (SortAttribute attributes, const SortItem & values)
References FieldRelevance, and values.
Referenced by fillPreparators().
BySeason()
std::string BySeason (SortAttribute attributes, const SortItem & values)
References CVariant::asInteger(), ByLabel(), FieldSeason, FieldSeasonSpecialSort, KODI::UTILS::StringUtils::Format(), CVariant::isNull(), and values.
Referenced by fillPreparators().
BySize()
std::string BySize (SortAttribute attributes, const SortItem & values)
References FieldSize, and values.
Referenced by fillPreparators().
BySortTitle()
std::string BySortTitle (SortAttribute attributes, const SortItem & values)
References FieldSortTitle, FieldTitle, SortUtils::RemoveArticles(), SortAttributeIgnoreArticle, and values.
Referenced by ByEpisodeNumber(), and fillPreparators().
ByStudio()
std::string ByStudio (SortAttribute attributes, const SortItem & values)
References ArrayToString(), FieldStudio, and values.
Referenced by fillPreparators().
BySubtitleLanguage()
std::string BySubtitleLanguage (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldSubtitleLanguage, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByTime()
std::string ByTime (SortAttribute attributes, const SortItem & values)
References FieldTime, label, and values.
Referenced by fillPreparators().
ByTitle()
std::string ByTitle (SortAttribute attributes, const SortItem & values)
References FieldTitle, SortUtils::RemoveArticles(), SortAttributeIgnoreArticle, and values.
Referenced by fillPreparators().
ByTop250()
std::string ByTop250 (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldTop250, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByTotalDiscs()
std::string ByTotalDiscs (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldTotalDiscs, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByTrackNumber()
std::string ByTrackNumber (SortAttribute attributes, const SortItem & values)
References FieldTrackNumber, and values.
Referenced by fillPreparators().
ByTvShowStatus()
std::string ByTvShowStatus (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldTvShowStatus, and values.
Referenced by fillPreparators().
ByTvShowTitle()
std::string ByTvShowTitle (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldTvShowTitle, and values.
Referenced by fillPreparators().
ByUserPreference()
std::string ByUserPreference (SortAttribute attributes, const SortItem & values)
References FieldUserPreference, and values.
Referenced by fillPreparators().
ByUserRating()
std::string ByUserRating (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldUserRating, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByVideoAspectRatio()
std::string ByVideoAspectRatio (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldVideoAspectRatio, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByVideoCodec()
std::string ByVideoCodec (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldVideoCodec, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByVideoResolution()
std::string ByVideoResolution (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldVideoResolution, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByVotes()
std::string ByVotes (SortAttribute attributes, const SortItem & values)
References ByLabel(), FieldVotes, KODI::UTILS::StringUtils::Format(), and values.
Referenced by fillPreparators().
ByYear()
std::string ByYear (SortAttribute attributes, const SortItem & values)
References CVariant::asString(), ByLabel(), FieldAirDate, FieldAlbum, FieldTrackNumber, FieldYear, KODI::UTILS::StringUtils::Format(), CVariant::isNull(), label, SortUtils::RemoveArticles(), and values.
Referenced by fillPreparators().
fillPreparators()
std::map< SortBy, SortUtils::SortPreparator > fillPreparators ()
References ByAlbum(), ByAlbumType(), ByArtist(), ByArtistThenYear(), ByAudioChannels(), ByAudioCodec(), ByAudioLanguage(), ByBitrate(), ByBPM(), ByChannel(), ByChannelNumber(), ByClientChannelOrder(), ByCountry(), ByDate(), ByDateAdded(), ByDateTaken(), ByDriveType(), ByEpisodeNumber(), ByFile(), ByGenre(), ByInstallDate(), ByLabel(), ByLastPlayed(), ByLastUpdated(), ByLastUsed(), ByListeners(), ByMPAA(), ByNumberOfEpisodes(), ByNumberOfWatchedEpisodes(), ByOrigDate(), ByOriginalTitle(), ByPath(), ByPlaycount(), ByPlaylistOrder(), ByProductionCode(), ByProgramCount(), ByProvider(), ByRandom(), ByRating(), ByRelevance(), BySeason(), BySize(), BySortTitle(), ByStudio(), BySubtitleLanguage(), ByTime(), ByTitle(), ByTop250(), ByTotalDiscs(), ByTrackNumber(), ByTvShowStatus(), ByTvShowTitle(), ByUserPreference(), ByUserRating(), ByVideoAspectRatio(), ByVideoCodec(), ByVideoResolution(), ByVotes(), ByYear(), SortByAlbum, SortByAlbumType, SortByArtist, SortByArtistThenYear, SortByAudioChannels, SortByAudioCodec, SortByAudioLanguage, SortByBitrate, SortByBPM, SortByChannel, SortByChannelNumber, SortByClientChannelOrder, SortByCountry, SortByDate, SortByDateAdded, SortByDateTaken, SortByDriveType, SortByEpisodeNumber, SortByFile, SortByGenre, SortByInstallDate, SortByLabel, SortByLastPlayed, SortByLastUpdated, SortByLastUsed, SortByListeners, SortByMPAA, SortByNone, SortByNumberOfEpisodes, SortByNumberOfWatchedEpisodes, SortByOrigDate, SortByOriginalTitle, SortByPath, SortByPlaycount, SortByPlaylistOrder, SortByProductionCode, SortByProgramCount, SortByProvider, SortByRandom, SortByRating, SortByRelevance, SortBySeason, SortBySize, SortBySortTitle, SortByStudio, SortBySubtitleLanguage, SortByTime, SortByTitle, SortByTop250, SortByTotalDiscs, SortByTrackNumber, SortByTvShowStatus, SortByTvShowTitle, SortByUserPreference, SortByUserRating, SortByVideoAspectRatio, SortByVideoCodec, SortByVideoResolution, SortByVotes, and SortByYear.
fillSortingFields()
std::map< SortBy, Fields > fillSortingFields ()
References FieldAirDate, FieldAlbum, FieldAlbumType, FieldArtist, FieldArtistSort, FieldAudioChannels, FieldAudioCodec, FieldAudioLanguage, FieldBitrate, FieldBPM, FieldChannelName, FieldChannelNumber, FieldClientChannelOrder, FieldCountry, FieldDate, FieldDateAdded, FieldDateTaken, FieldDriveType, FieldEpisodeNumber, FieldEpisodeNumberSpecialSort, FieldGenre, FieldId, FieldInstallDate, FieldLabel, FieldLastPlayed, FieldLastUpdated, FieldLastUsed, FieldListeners, FieldMPAA, FieldNumberOfEpisodes, FieldNumberOfWatchedEpisodes, FieldOrigDate, FieldOriginalTitle, FieldPath, FieldPlaycount, FieldProductionCode, FieldProgramCount, FieldProvider, FieldRating, FieldRelevance, FieldSeason, FieldSeasonSpecialSort, FieldSize, FieldSortTitle, FieldStartOffset, FieldStudio, FieldSubtitleLanguage, FieldTime, FieldTitle, FieldTop250, FieldTotalDiscs, FieldTrackNumber, FieldTvShowStatus, FieldTvShowTitle, FieldUserPreference, FieldUserRating, FieldVideoAspectRatio, FieldVideoCodec, FieldVideoResolution, FieldVotes, FieldYear, SortByAlbum, SortByAlbumType, SortByArtist, SortByArtistThenYear, SortByAudioChannels, SortByAudioCodec, SortByAudioLanguage, SortByBitrate, SortByBPM, SortByChannel, SortByChannelNumber, SortByClientChannelOrder, SortByCountry, SortByDate, SortByDateAdded, SortByDateTaken, SortByDriveType, SortByEpisodeNumber, SortByFile, SortByGenre, SortByInstallDate, SortByLabel, SortByLastPlayed, SortByLastUpdated, SortByLastUsed, SortByListeners, SortByMPAA, SortByNone, SortByNumberOfEpisodes, SortByNumberOfWatchedEpisodes, SortByOrigDate, SortByOriginalTitle, SortByPath, SortByPlaycount, SortByPlaylistOrder, SortByProductionCode, SortByProgramCount, SortByProvider, SortByRandom, SortByRating, SortByRelevance, SortBySeason, SortBySize, SortBySortTitle, SortByStudio, SortBySubtitleLanguage, SortByTime, SortByTitle, SortByTop250, SortByTotalDiscs, SortByTrackNumber, SortByTvShowStatus, SortByTvShowTitle, SortByUserPreference, SortByUserRating, SortByVideoAspectRatio, SortByVideoCodec, SortByVideoResolution, SortByVotes, and SortByYear.
preliminarySort()
bool preliminarySort (const SortItem & left, const SortItem & right, bool handleFolder, bool & result, std::wstring & labelLeft, std::wstring & labelRight)
References FieldFolder, FieldSort, FieldSortSpecial, int64_t(), left, right, SortSpecialNone, SortSpecialOnBottom, and SortSpecialOnTop.
Referenced by SorterAscending(), SorterDescending(), SorterIgnoreFoldersAscending(), and SorterIgnoreFoldersDescending().
SorterAscending()
bool SorterAscending (const SortItem & left, const SortItem & right)
References KODI::UTILS::StringUtils::AlphaNumericCompare(), left, preliminarySort(), and right.
Referenced by SortUtils::getSorter(), and SorterIndirectAscending().
SorterDescending()
bool SorterDescending (const SortItem & left, const SortItem & right)
References KODI::UTILS::StringUtils::AlphaNumericCompare(), left, preliminarySort(), and right.
Referenced by SortUtils::getSorter(), and SorterIndirectDescending().
SorterIgnoreFoldersAscending()
bool SorterIgnoreFoldersAscending (const SortItem & left, const SortItem & right)
References KODI::UTILS::StringUtils::AlphaNumericCompare(), left, preliminarySort(), and right.
Referenced by SortUtils::getSorter(), and SorterIndirectIgnoreFoldersAscending().
SorterIgnoreFoldersDescending()
bool SorterIgnoreFoldersDescending (const SortItem & left, const SortItem & right)
References KODI::UTILS::StringUtils::AlphaNumericCompare(), left, preliminarySort(), and right.
Referenced by SortUtils::getSorter(), and SorterIndirectIgnoreFoldersDescending().
SorterIndirectAscending()
bool SorterIndirectAscending (const SortItemPtr & left, const SortItemPtr & right)
References left, right, and SorterAscending().
Referenced by SortUtils::getSorterIndirect().
SorterIndirectDescending()
bool SorterIndirectDescending (const SortItemPtr & left, const SortItemPtr & right)
References left, right, and SorterDescending().
Referenced by SortUtils::getSorterIndirect().
SorterIndirectIgnoreFoldersAscending()
bool SorterIndirectIgnoreFoldersAscending (const SortItemPtr & left, const SortItemPtr & right)
References left, right, and SorterIgnoreFoldersAscending().
Referenced by SortUtils::getSorterIndirect().
SorterIndirectIgnoreFoldersDescending()
bool SorterIndirectIgnoreFoldersDescending (const SortItemPtr & left, const SortItemPtr & right)
References left, right, and SorterIgnoreFoldersDescending().
Referenced by SortUtils::getSorterIndirect().
TypeFromString()
template<typename T > T TypeFromString (const std::map< std::string, T > & typeMap, const std::string & name, const T & defaultType)
References name.
TypeToString()
template<typename T > const std::string & TypeToString (const std::map< std::string, T > & typeMap, const T & value)
References KODI::UTILS::StringUtils::Empty, and value.
Variable Documentation
sortMethods
const std::map<std::string, SortBy> sortMethods
Sort methods to translate string values to enum values.
Warning
On string changes, edit SortBy enumerator to have strings right for documentation!
Referenced by SortUtils::SortMethodFromString(), and SortUtils::SortMethodToString().
sortOrders
const std::map<std::string, SortOrder> sortOrders
Initial value:
= {
  { "ascending", SortOrderAscending },
  { "descending", SortOrderDescending }
}
Referenced by SortUtils::SortOrderFromString(), and SortUtils::SortOrderToString().
table
const sort_map table[]
Referenced by CVideoDatabase::AddToLinkTable(), CVideoDatabase::AddToTable(), CVideoDatabase::AppendIdLinkFilter(), CVideoDatabase::AppendLinkFilter(), CVideoDatabase::CleanMediaType(), CVideoDatabase::CreateForeignLinkIndex(), CVideoDatabase::CreateLinkIndex(), CFFmpegImage::CreateThumbnailFromSurface(), KODI::WINDOWING::WAYLAND::CXkbcommonKeymap::CXkbcommonKeymap(), CFFmpegImage::DecodeFrame(), dbiplus::MysqlDataset::dropIndex(), KODI::PLAYLIST::CSmartPlaylistRule::FormatLinkQuery(), KODI::PLAYLIST::CSmartPlaylistRule::FormatWhereClause(), CMusicDatabase::GetCommonNav(), CGUIDialogMediaFilter::GetMinMax(), CMusicDatabase::GetOrderFilter(), CGUIDialogMediaFilter::GetRange(), SortUtils::GetSortLabel(), CLibInputKeyboard::XkbComposeTableDeleter::operator()(), KODI::WINDOWING::WAYLAND::CXkbcommonKeymap::XkbComposeTableDeleter::operator()(), PVR::CPVREpgDatabase::QueueDeleteEpgQuery(), PVR::CPVREpgDatabase::QueueDeleteLastEpgScanTimeQuery(), CVideoDatabase::RemoveFromLinkTable(), Win32DllLoader::RestoreImports(), CVideoDatabase::SetSingleValue(), SortUtils::TranslateOldSortMethod(), SortUtils::TranslateOldSortMethod(), and CVideoDatabase::UpdateTables().