Kodi Documentation: KODI::UTILS::FONT Namespace Reference
KODI::UTILS::FONT Namespace Reference
Namespaces
namespace anonymous_namespace{FontUtils.cpp}
namespace FONTPATH
Functions
bool GetFontFamilyNames (const std::vector< uint8_t > &buffer, std::set< std::string > &familyNames)
Get the font family name from a font file, in case of font collection (.ttc) will take the family name of all fonts.
bool GetFontFamilyNames (const std::string &filepath, std::set< std::string > &familyNames)
Get the font family name from a font file, in case of font collection (.ttc) will take the family name of all fonts.
std::string GetFontFamily (std::vector< uint8_t > &buffer)
Get the font family name from a font file, in case of font collection (.ttc) will take the first available.
std::string GetFontFamily (const std::string &filepath)
Get the font family name from a font file, in case of font collection (.ttc) will take the first available.
bool IsSupportedFontExtension (const std::string &filepath)
Check if a filename have a supported font extension.
void ClearTemporaryFonts ()
Removes all temporary fonts, e.g.those extract from MKV containers that are only available during playback.
Variables
constexpr const char * SUPPORTED_EXTENSIONS_MASK = ".ttf|.ttc|.otf"
constexpr const char * FONT_DEFAULT_FILENAME = "arial.ttf"
Function Documentation
ClearTemporaryFonts()
void KODI::UTILS::FONT::ClearTemporaryFonts ()
Removes all temporary fonts, e.g.those extract from MKV containers that are only available during playback.
References XFILE::CFile::Delete(), XFILE::DIR_FLAG_BYPASS_CACHE, XFILE::DIR_FLAG_GET_HIDDEN, XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::Exists(), XFILE::CDirectory::GetDirectory(), SUPPORTED_EXTENSIONS_MASK, and KODI::UTILS::FONT::FONTPATH::TEMP.
Referenced by CVideoPlayer::OnStartup().
GetFontFamily() [1/2]
std::string KODI::UTILS::FONT::GetFontFamily (const std::string & filepath)
Get the font family name from a font file, in case of font collection (.ttc) will take the first available.
Parameters
filepath The path where read the font data
Returns
The font family name, otherwise empty if fails
References GetFontFamily(), LoadFile(), and LOGERROR.
GetFontFamily() [2/2]
std::string KODI::UTILS::FONT::GetFontFamily (std::vector< uint8_t > & buffer)
Get the font family name from a font file, in case of font collection (.ttc) will take the first available.
Parameters
buffer The font data
Returns
The font family name, otherwise empty if fails
References LOGERROR, and LOGWARNING.
Referenced by CDVDSubtitlesLibass::Configure(), GetFontFamily(), and KODI::SUBTITLES::CSubtitlesSettings::SettingOptionsSubtitleFontsFiller().
GetFontFamilyNames() [1/2]
bool KODI::UTILS::FONT::GetFontFamilyNames (const std::string & filepath, std::set< std::string > & familyNames)
Get the font family name from a font file, in case of font collection (.ttc) will take the family name of all fonts.
Parameters
filepath The path where read the font data
familyNames The font family names
Returns
True if success, otherwise false when an error occurs
References GetFontFamilyNames(), LoadFile(), and LOGERROR.
GetFontFamilyNames() [2/2]
bool KODI::UTILS::FONT::GetFontFamilyNames (const std::vector< uint8_t > & buffer, std::set< std::string > & familyNames)
Get the font family name from a font file, in case of font collection (.ttc) will take the family name of all fonts.
Parameters
buffer The font data
familyNames The font family names
Returns
True if success, otherwise false when an error occurs
References LOGERROR, and LOGWARNING.
Referenced by GetFontFamilyNames(), and GUIFontManager::LoadUserFonts().
IsSupportedFontExtension()
bool KODI::UTILS::FONT::IsSupportedFontExtension (const std::string & filepath)
Check if a filename have a supported font extension.
Parameters
filepath The font file path
Returns
True if it has a supported extension, otherwise false
References URIUtils::HasExtension(), and SUPPORTED_EXTENSIONS_MASK.
Referenced by anonymous_namespace{SettingConditions.cpp}::HasSubtitlesFontExtensions().
Variable Documentation
FONT_DEFAULT_FILENAME
constexpr const char* KODI::UTILS::FONT::FONT_DEFAULT_FILENAME = "arial.ttf" constexpr
Referenced by CDVDSubtitlesLibass::Configure(), and KODI::SUBTITLES::CSubtitlesSettings::SettingOptionsSubtitleFontsFiller().
SUPPORTED_EXTENSIONS_MASK
constexpr const char* KODI::UTILS::FONT::SUPPORTED_EXTENSIONS_MASK = ".ttf|.ttc|.otf" constexpr
Referenced by ClearTemporaryFonts(), CDVDSubtitlesLibass::Configure(), IsSupportedFontExtension(), GUIFontManager::LoadUserFonts(), and GUIFontManager::SettingOptionsFontsFiller().