Kodi Documentation: JSONRPC::CApplicationOperations Class Reference
JSONRPC::CApplicationOperations Class Reference
#include <ApplicationOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetProperties (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetVolume (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetMute (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Quit (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Static Private Member Functions
static JSONRPC_STATUS GetPropertyValue (const std::string &property, CVariant &result)
Static Private Member Functions inherited from JSONRPC::CFileItemHandler
static void FillDetails (const ISerializable *info, const std::shared_ptr< CFileItem > &item, std::set< std::string > &fields, CVariant &result, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, bool sortLimit=true)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, int size, bool sortLimit=true)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const CVariant &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const std::set< std::string > &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
Static Private Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Member Function Documentation
GetProperties()
JSONRPC_STATUS CApplicationOperations::GetProperties (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), GetPropertyValue(), index(), JSONRPC::OK, CVariant::size(), and CVariant::VariantTypeObject.
GetPropertyValue()
JSONRPC_STATUS CApplicationOperations::GetPropertyValue (const std::string & property, CVariant & result) static private
References CVariant::append(), g_langInfo, CServiceBroker::GetAppComponents(), CCompileInfo::GetAppName(), CCompileInfo::GetMajor(), CCompileInfo::GetMinor(), CCompileInfo::GetSCMID(), CCompileInfo::GetSuffix(), JSONRPC::InvalidParams, JSONRPC::OK, CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by GetProperties(), SetMute(), and SetVolume().
Quit()
JSONRPC_STATUS CApplicationOperations::Quit (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CServiceBroker::GetAppMessenger(), and TMSG_QUIT.
SetMute()
JSONRPC_STATUS CApplicationOperations::SetMute (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_MUTE, CVariant::asBoolean(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), GetPropertyValue(), JSONRPC::InvalidParams, CVariant::isBoolean(), TMSG_GUI_ACTION, and WINDOW_INVALID.
SetVolume()
JSONRPC_STATUS CApplicationOperations::SetVolume (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, ACTION_VOLUME_DOWN, ACTION_VOLUME_UP, CVariant::asInteger(), CVariant::asString(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), GetPropertyValue(), JSONRPC::InvalidParams, JSONRPC::OK, JSONRPC::CInputOperations::SendAction(), CApplicationVolumeHandling::SetVolume(), and TMSG_VOLUME_SHOW.
The documentation for this class was generated from the following files:
ApplicationOperations.h
ApplicationOperations.cpp