Kodi Documentation: KODI::WINDOWING::COSScreenSaverManager Class Reference
KODI::WINDOWING::COSScreenSaverManager Class Reference
#include <OSScreenSaver.h>
Public Member Functions
COSScreenSaverManager (std::unique_ptr< IOSScreenSaver > impl)
COSScreenSaverInhibitor CreateInhibitor ()
bool IsInhibited ()
Private Member Functions
void RemoveInhibitor ()
Private Attributes
unsigned int m_inhibitionCount {0u}
std::unique_ptr< IOSScreenSaver > m_impl
Friends
class COSScreenSaverInhibitor
Detailed Description
Manage the OS screen saver
This class keeps track of a number of COSScreenSaverInhibitor instances and keeps the OS screen saver inhibited as long as at least one of them exists and is active.
Constructor & Destructor Documentation
COSScreenSaverManager()
COSScreenSaverManager::COSScreenSaverManager (std::unique_ptr< IOSScreenSaver > impl) explicit
Create manager with backing OS-specific implementation
Member Function Documentation
CreateInhibitor()
COSScreenSaverInhibitor COSScreenSaverManager::CreateInhibitor ()
Create inhibitor that prevents the OS screen saver from becoming active as long as it is alive
References CLog::Log(), LOGDEBUG, m_impl, and m_inhibitionCount.
Referenced by CApplicationPowerHandling::CheckOSScreenSaverInhibitionSetting(), and CApplicationPowerHandling::CheckScreenSaverAndDPMS().
IsInhibited()
bool COSScreenSaverManager::IsInhibited ()
Check whether the OS screen saver is currently inhibited
References m_inhibitionCount.
Referenced by CXBMCApp::onResume().
RemoveInhibitor()
void COSScreenSaverManager::RemoveInhibitor () private
References CLog::Log(), LOGDEBUG, m_impl, and m_inhibitionCount.
Referenced by KODI::WINDOWING::COSScreenSaverInhibitor::Release().
Friends And Related Symbol Documentation
COSScreenSaverInhibitor
friend class COSScreenSaverInhibitor friend
Member Data Documentation
m_impl
std::unique_ptr<IOSScreenSaver> KODI::WINDOWING::COSScreenSaverManager::m_impl private
Referenced by CreateInhibitor(), and RemoveInhibitor().
m_inhibitionCount
unsigned int KODI::WINDOWING::COSScreenSaverManager::m_inhibitionCount {0u} private
Referenced by CreateInhibitor(), IsInhibited(), and RemoveInhibitor().
The documentation for this class was generated from the following files:
OSScreenSaver.h
OSScreenSaver.cpp