Kodi Documentation: VAAPI::CVideoSurfaces Class Reference
VAAPI::CVideoSurfaces Class Reference
#include <VAAPI.h>
Public Member Functions
void AddSurface (VASurfaceID surf)
void ClearReference (VASurfaceID surf)
bool MarkRender (VASurfaceID surf)
void ClearRender (VASurfaceID surf)
bool IsValid (VASurfaceID surf)
VASurfaceID GetFree (VASurfaceID surf)
VASurfaceID GetAtIndex (int idx)
VASurfaceID RemoveNext (bool skiprender=false)
void Reset ()
int Size ()
bool HasFree ()
bool HasRefs ()
int NumFree ()
Protected Attributes
std::map< VASurfaceID, int > m_state
std::list< VASurfaceID > m_freeSurfaces
CCriticalSection m_section
Member Function Documentation
AddSurface()
void CVideoSurfaces::AddSurface (VASurfaceID surf)
References m_freeSurfaces, m_section, and m_state.
Referenced by VAAPI::CDecoder::ConfigVAAPI(), and VAAPI::CVppPostproc::PreInit().
ClearReference()
void CVideoSurfaces::ClearReference (VASurfaceID surf)
References CLog::Log(), LOGWARNING, m_freeSurfaces, m_section, and m_state.
Referenced by VAAPI::CVppPostproc::ClearRef(), VAAPI::CDecoder::FFReleaseBuffer(), and VAAPI::CVppPostproc::Filter().
ClearRender()
void CVideoSurfaces::ClearRender (VASurfaceID surf)
References CLog::Log(), LOGWARNING, m_freeSurfaces, m_section, and m_state.
Referenced by VAAPI::CFFmpegPostproc::AddPicture(), VAAPI::CVppPostproc::Advance(), VAAPI::CSkipPostproc::ClearRef(), VAAPI::COutput::Flush(), VAAPI::CVppPostproc::Flush(), and VAAPI::COutput::ReleaseBufferPool().
GetAtIndex()
VASurfaceID CVideoSurfaces::GetAtIndex (int idx)
References m_state.
Referenced by VAAPI::CVppPostproc::Dispose(), VAAPI::CDecoder::Open(), and VAAPI::CFFmpegPostproc::PreInit().
GetFree()
VASurfaceID CVideoSurfaces::GetFree (VASurfaceID surf)
References CLog::Log(), LOGWARNING, m_freeSurfaces, m_section, m_state, and SURFACE_USED_FOR_REFERENCE.
Referenced by VAAPI::CDecoder::FFGetBuffer(), and VAAPI::CVppPostproc::Filter().
HasFree()
bool CVideoSurfaces::HasFree ()
References m_freeSurfaces, and m_section.
Referenced by VAAPI::CDecoder::Decode().
HasRefs()
bool CVideoSurfaces::HasRefs ()
References m_section, m_state, and SURFACE_USED_FOR_REFERENCE.
Referenced by VAAPI::CVppPostproc::ClearRef(), and VAAPI::CVppPostproc::Discard().
IsValid()
bool CVideoSurfaces::IsValid (VASurfaceID surf)
References m_section, and m_state.
Referenced by VAAPI::CDecoder::Decode().
MarkRender()
bool CVideoSurfaces::MarkRender (VASurfaceID surf)
References CLog::Log(), LOGWARNING, m_freeSurfaces, m_section, m_state, and SURFACE_USED_FOR_RENDER.
Referenced by VAAPI::CDecoder::Decode().
NumFree()
int CVideoSurfaces::NumFree ()
References m_freeSurfaces, and m_section.
Referenced by VAAPI::CVppPostproc::WantsPic().
RemoveNext()
VASurfaceID CVideoSurfaces::RemoveNext (bool skiprender = false)
References m_freeSurfaces, m_section, m_state, and SURFACE_USED_FOR_RENDER.
Referenced by VAAPI::CVppPostproc::Dispose(), VAAPI::CDecoder::FiniVAAPIOutput(), and VAAPI::CDecoder::Release().
Reset()
void CVideoSurfaces::Reset ()
References m_freeSurfaces, m_section, and m_state.
Referenced by VAAPI::CVppPostproc::Dispose(), and VAAPI::CDecoder::FiniVAAPIOutput().
Size()
int CVideoSurfaces::Size ()
References m_section, and m_state.
Referenced by VAAPI::CVppPostproc::Dispose(), VAAPI::CDecoder::FiniVAAPIOutput(), and VAAPI::CDecoder::Open().
Member Data Documentation
m_freeSurfaces
std::list<VASurfaceID> VAAPI::CVideoSurfaces::m_freeSurfaces protected
Referenced by AddSurface(), ClearReference(), ClearRender(), GetFree(), HasFree(), MarkRender(), NumFree(), RemoveNext(), and Reset().
m_section
CCriticalSection VAAPI::CVideoSurfaces::m_section protected
Referenced by AddSurface(), ClearReference(), ClearRender(), GetFree(), HasFree(), HasRefs(), IsValid(), MarkRender(), NumFree(), RemoveNext(), Reset(), and Size().
m_state
std::map<VASurfaceID, int> VAAPI::CVideoSurfaces::m_state protected
Referenced by AddSurface(), ClearReference(), ClearRender(), GetAtIndex(), GetFree(), HasRefs(), IsValid(), MarkRender(), RemoveNext(), Reset(), and Size().
The documentation for this class was generated from the following files:
VAAPI.h
VAAPI.cpp