Kodi Documentation: PVR::CPVRGUIActionsClients Class Reference
PVR::CPVRGUIActionsClients Class Reference
#include <PVRGUIActionsClients.h>
Public Member Functions
CPVRGUIActionsClients ()=default
~CPVRGUIActionsClients () override=default
bool ProcessSettingsMenuHooks ()
Select and invoke client-specific settings actions.
Public Member Functions inherited from PVR::IPVRComponent
virtual ~IPVRComponent ()=default
Private Member Functions
CPVRGUIActionsClients (const CPVRGUIActionsClients &)=delete
CPVRGUIActionsClients const & operator= (CPVRGUIActionsClients const &)=delete
Constructor & Destructor Documentation
CPVRGUIActionsClients() [1/2]
PVR::CPVRGUIActionsClients::CPVRGUIActionsClients () default
~CPVRGUIActionsClients()
PVR::CPVRGUIActionsClients::~CPVRGUIActionsClients () override default
CPVRGUIActionsClients() [2/2]
PVR::CPVRGUIActionsClients::CPVRGUIActionsClients (const CPVRGUIActionsClients &) private delete
Member Function Documentation
operator=()
CPVRGUIActionsClients const & PVR::CPVRGUIActionsClients::operator= (CPVRGUIActionsClients const &) private delete
ProcessSettingsMenuHooks()
bool CPVRGUIActionsClients::ProcessSettingsMenuHooks ()
Select and invoke client-specific settings actions.
Returns
true on success, false otherwise.
References CGUIDialogSelect::Add(), PVR::CPVRManager::Clients(), CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CGUIDialogSelect::GetSelectedItem(), CGUIComponent::GetWindowManager(), LOGERROR, CGUIDialog::Open(), PVR_ERROR_NO_ERROR, CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and WINDOW_DIALOG_SELECT.
The documentation for this class was generated from the following files:
PVRGUIActionsClients.h
PVRGUIActionsClients.cpp