Kodi Documentation: CScriptRunner Class Reference
CScriptRunner Class Reference abstract
#include <ScriptRunner.h>
Protected Member Functions
CScriptRunner ()
virtual ~CScriptRunner ()=default
virtual bool IsSuccessful () const =0
virtual bool IsCancelled () const =0
ADDON::AddonPtr GetAddon () const
bool StartScript (const ADDON::AddonPtr &addon, const std::string &path)
bool RunScript (const ADDON::AddonPtr &addon, const std::string &path, int handle, bool resume)
void SetDone ()
Static Protected Member Functions
static int ExecuteScript (const ADDON::AddonPtr &addon, const std::string &path, bool resume)
static int ExecuteScript (const ADDON::AddonPtr &addon, const std::string &path, int handle, bool resume)
Private Member Functions
bool RunScriptInternal (const ADDON::AddonPtr &addon, const std::string &path, int handle, bool resume, bool wait=true)
bool WaitOnScriptResult (int scriptId, const std::string &path, const std::string &name)
Private Attributes
ADDON::AddonPtr m_addon
CEvent m_scriptDone
Constructor & Destructor Documentation
CScriptRunner()
CScriptRunner::CScriptRunner () protected
~CScriptRunner()
virtual CScriptRunner::~CScriptRunner () protected virtual default
Member Function Documentation
ExecuteScript() [1/2]
int CScriptRunner::ExecuteScript (const ADDON::AddonPtr & addon, const std::string & path, bool resume) static protected
References ExecuteScript().
Referenced by ExecuteScript(), and RunScriptInternal().
ExecuteScript() [2/2]
int CScriptRunner::ExecuteScript (const ADDON::AddonPtr & addon, const std::string & path, int handle, bool resume) static protected
References CScriptInvocationManager::ExecuteAsync(), CURL::Get(), CScriptInvocationManager::GetInstance(), CURL::GetOptions(), CLog::Log(), LOGDEBUG, LOGERROR, and CURL::SetOptions().
GetAddon()
ADDON::AddonPtr CScriptRunner::GetAddon () const protected
IsCancelled()
virtual bool CScriptRunner::IsCancelled () const protected pure virtual
Implemented in XFILE::CPluginDirectory.
Referenced by WaitOnScriptResult().
IsSuccessful()
virtual bool CScriptRunner::IsSuccessful () const protected pure virtual
Implemented in XFILE::CPluginDirectory.
Referenced by WaitOnScriptResult().
RunScript()
bool CScriptRunner::RunScript (const ADDON::AddonPtr & addon, const std::string & path, int handle, bool resume) protected
References RunScriptInternal().
Referenced by CRunningScriptsHandler< TScript >::RunScript().
RunScriptInternal()
bool CScriptRunner::RunScriptInternal (const ADDON::AddonPtr & addon, const std::string & path, int handle, bool resume, bool wait = true) private
References ExecuteScript(), m_addon, m_scriptDone, CEvent::Reset(), and WaitOnScriptResult().
Referenced by RunScript(), and StartScript().
SetDone()
void CScriptRunner::SetDone () protected
References m_scriptDone, and CEvent::Set().
StartScript()
bool CScriptRunner::StartScript (const ADDON::AddonPtr & addon, const std::string & path) protected
References RunScriptInternal().
WaitOnScriptResult()
bool CScriptRunner::WaitOnScriptResult (int scriptId, const std::string & path, const std::string & name) private
References CRunningScriptObserver::Abort(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), CScriptInvocationManager::GetInstance(), CGUIComponent::GetWindowManager(), IsCancelled(), CScriptInvocationManager::IsRunning(), IsSuccessful(), CLog::Log(), LOGDEBUG, m_scriptDone, name, CScriptInvocationManager::Stop(), CEvent::Wait(), CGUIDialogBusy::WaitOnEvent(), and WINDOW_DIALOG_PROGRESS.
Referenced by RunScriptInternal().
Member Data Documentation
m_addon
ADDON::AddonPtr CScriptRunner::m_addon private
Referenced by RunScriptInternal().
m_scriptDone
CEvent CScriptRunner::m_scriptDone private
Referenced by RunScriptInternal(), SetDone(), and WaitOnScriptResult().
The documentation for this class was generated from the following files:
ScriptRunner.h
ScriptRunner.cpp