Kodi Documentation: CAppEnvironment Class Reference
CAppEnvironment Class Reference
#include <AppEnvironment.h>
Static Public Member Functions
static void SetUp (const std::shared_ptr< CAppParams > &appParams)
static void TearDown ()
Member Function Documentation
SetUp()
void CAppEnvironment::SetUp (const std::shared_ptr< CAppParams > & appParams) static
References CServiceBroker::CreateLogging(), CServiceBroker::RegisterAppParams(), and CServiceBroker::RegisterSettingsComponent().
Referenced by XBMCController::CallExit, main(), CXBMCApp::run(), KODI::PLATFORM::WINDOWS10::App::Run(), TestBasicEnvironment::SetUp(), and WinMain().
TearDown()
void CAppEnvironment::TearDown () static
References CLog::Deinitialize(), CServiceBroker::DestroyLogging(), CServiceBroker::GetLogging(), CServiceBroker::GetSettingsComponent(), CServiceBroker::UnregisterAppParams(), CLog::UnregisterFromSettings(), and CServiceBroker::UnregisterSettingsComponent().
Referenced by XBMCController::CallExit, main(), CXBMCApp::run(), KODI::PLATFORM::WINDOWS10::App::Run(), TestBasicEnvironment::TearDown(), and WinMain().
The documentation for this class was generated from the following files:
AppEnvironment.h
AppEnvironment.cpp