Kodi Documentation: CDemuxStreamClientInternal Class Reference
CDemuxStreamClientInternal Class Reference
Public Member Functions
~CDemuxStreamClientInternal ()
void DisposeParser ()
Public Attributes
AVCodecParserContext * m_parser = nullptr
AVCodecContext * m_context = nullptr
bool m_parser_split = false
Constructor & Destructor Documentation
~CDemuxStreamClientInternal()
CDemuxStreamClientInternal::~CDemuxStreamClientInternal () inline
References DisposeParser().
Member Function Documentation
DisposeParser()
void CDemuxStreamClientInternal::DisposeParser () inline
References m_context, and m_parser.
Referenced by CDVDDemuxClient::ParsePacket(), and ~CDemuxStreamClientInternal().
Member Data Documentation
m_context
AVCodecContext* CDemuxStreamClientInternal::m_context = nullptr
Referenced by DisposeParser(), and CDVDDemuxClient::ParsePacket().
m_parser
AVCodecParserContext* CDemuxStreamClientInternal::m_parser = nullptr
Referenced by DisposeParser(), and CDVDDemuxClient::ParsePacket().
m_parser_split
bool CDemuxStreamClientInternal::m_parser_split = false
Referenced by CDVDDemuxClient::ParsePacket().
The documentation for this class was generated from the following file:
DVDDemuxClient.cpp