Kodi Documentation: ActiveAE::CActiveAESound Class Reference
ActiveAE::CActiveAESound Class Reference
#include <ActiveAESound.h>
Public Member Functions
CActiveAESound (const std::string &filename, CActiveAE *ae)
~CActiveAESound () override
void Play () override
void Stop () override
bool IsPlaying () override
void SetChannel (AEChannel channel) override
AEChannel GetChannel () override
void SetVolume (float volume) override
float GetVolume () override
uint8_t ** InitSound (bool orig, SampleConfig config, int nb_samples)
bool StoreSound (bool orig, uint8_t **buffer, int samples, int linesize)
CSoundPacket * GetSound (bool orig)
bool IsConverted ()
void SetConverted (bool state)
bool Prepare ()
void Finish ()
int GetChunkSize ()
int GetFileSize ()
bool IsSeekPossible ()
Static Public Member Functions
static int Read (void *h, uint8_t *buf, int size)
static int64_t Seek (void *h, int64_t pos, int whence)
Protected Attributes
CActiveAE * m_activeAE
std::string m_filename
XFILE::CFile * m_pFile
bool m_isSeekPossible
int m_fileSize
float m_volume = 1.0f
AEChannel m_channel = AE_CH_NULL
CSoundPacket * m_orig_sound
CSoundPacket * m_dst_sound
bool m_isConverted
Additional Inherited Members
Protected Member Functions inherited from IAESound
IAESound (const std::string &filename)
virtual ~IAESound ()=default
Constructor & Destructor Documentation
CActiveAESound()
CActiveAESound::CActiveAESound (const std::string & filename, CActiveAE * ae)
References m_activeAE, m_dst_sound, m_fileSize, m_isConverted, m_isSeekPossible, m_orig_sound, and m_pFile.
~CActiveAESound()
CActiveAESound::~CActiveAESound () override
References Finish(), m_dst_sound, and m_orig_sound.
Member Function Documentation
Finish()
void CActiveAESound::Finish ()
References m_pFile.
Referenced by ~CActiveAESound().
GetChannel()
AEChannel ActiveAE::CActiveAESound::GetChannel () inline override virtual
Implements IAESound.
References m_channel.
Referenced by ActiveAE::CActiveAE::ResampleSound(), and ActiveAE::CActiveAE::SStopSound().
GetChunkSize()
int CActiveAESound::GetChunkSize ()
References XFILE::CFile::GetChunkSize(), and m_pFile.
GetFileSize()
int ActiveAE::CActiveAESound::GetFileSize () inline
References m_fileSize.
GetSound()
CSoundPacket * CActiveAESound::GetSound (bool orig)
References m_dst_sound, and m_orig_sound.
Referenced by ActiveAE::CActiveAE::ResampleSound().
GetVolume()
float ActiveAE::CActiveAESound::GetVolume () inline override virtual
Implements IAESound.
References m_volume.
InitSound()
uint8_t ** CActiveAESound::InitSound (bool orig, SampleConfig config, int nb_samples)
References m_dst_sound, m_isConverted, and m_orig_sound.
Referenced by ActiveAE::CActiveAE::ResampleSound().
IsConverted()
bool ActiveAE::CActiveAESound::IsConverted () inline
References m_isConverted.
IsPlaying()
bool CActiveAESound::IsPlaying () override virtual
Todo:
implement
Implements IAESound.
IsSeekPossible()
bool ActiveAE::CActiveAESound::IsSeekPossible () inline
References m_isSeekPossible.
Play()
void CActiveAESound::Play () override virtual
Implements IAESound.
References m_activeAE, and ActiveAE::CActiveAE::PlaySound().
Prepare()
bool CActiveAESound::Prepare ()
References XFILE::CFile::GetLength(), XFILE::CFile::IoControl(), XFILE::IOCTRL_SEEK_POSSIBLE, m_filename, m_fileSize, m_isSeekPossible, m_pFile, XFILE::CFile::Open(), XFILE::READ_CHUNKED, and XFILE::READ_TRUNCATED.
Read()
int CActiveAESound::Read (void * h, uint8_t * buf, int size) static
References m_pFile, and XFILE::CFile::Read().
Referenced by ActiveAE::CActiveAE::MakeSound().
Seek()
int64_t CActiveAESound::Seek (void * h, int64_t pos, int whence) static
References XFILE::CFile::GetLength(), m_pFile, and XFILE::CFile::Seek().
Referenced by ActiveAE::CActiveAE::MakeSound().
SetChannel()
void ActiveAE::CActiveAESound::SetChannel (AEChannel channel) inline override virtual
Implements IAESound.
References m_channel.
SetConverted()
void ActiveAE::CActiveAESound::SetConverted (bool state) inline
References m_isConverted.
Referenced by ActiveAE::CActiveAE::ResampleSound().
SetVolume()
void ActiveAE::CActiveAESound::SetVolume (float volume) inline override virtual
Implements IAESound.
References m_volume.
Stop()
void CActiveAESound::Stop () override virtual
Implements IAESound.
References m_activeAE, and ActiveAE::CActiveAE::StopSound().
StoreSound()
bool CActiveAESound::StoreSound (bool orig, uint8_t ** buffer, int samples, int linesize)
References CLog::Log(), LOGERROR, m_dst_sound, and m_orig_sound.
Member Data Documentation
m_activeAE
CActiveAE* ActiveAE::CActiveAESound::m_activeAE protected
Referenced by CActiveAESound(), Play(), and Stop().
m_channel
AEChannel ActiveAE::CActiveAESound::m_channel = AE_CH_NULL protected
Referenced by GetChannel(), and SetChannel().
m_dst_sound
CSoundPacket* ActiveAE::CActiveAESound::m_dst_sound protected
Referenced by CActiveAESound(), GetSound(), InitSound(), StoreSound(), and ~CActiveAESound().
m_filename
std::string ActiveAE::CActiveAESound::m_filename protected
Referenced by Prepare().
m_fileSize
int ActiveAE::CActiveAESound::m_fileSize protected
Referenced by CActiveAESound(), GetFileSize(), and Prepare().
m_isConverted
bool ActiveAE::CActiveAESound::m_isConverted protected
Referenced by CActiveAESound(), InitSound(), IsConverted(), and SetConverted().
m_isSeekPossible
bool ActiveAE::CActiveAESound::m_isSeekPossible protected
Referenced by CActiveAESound(), IsSeekPossible(), and Prepare().
m_orig_sound
CSoundPacket* ActiveAE::CActiveAESound::m_orig_sound protected
Referenced by CActiveAESound(), GetSound(), InitSound(), StoreSound(), and ~CActiveAESound().
m_pFile
XFILE::CFile* ActiveAE::CActiveAESound::m_pFile protected
Referenced by CActiveAESound(), Finish(), GetChunkSize(), Prepare(), Read(), and Seek().
m_volume
float ActiveAE::CActiveAESound::m_volume = 1.0f protected
Referenced by GetVolume(), and SetVolume().
The documentation for this class was generated from the following files:
ActiveAESound.h
ActiveAESound.cpp