Kodi Documentation: CExecString Class Reference
CExecString Class Reference
#include <ExecString.h>
Public Member Functions
CExecString ()=default
CExecString (const std::string &execString)
CExecString (const std::string &function, const std::vector< std::string > &params)
CExecString (const std::string &function, const CFileItem &target, const std::string &param)
CExecString (const CFileItem &item, const std::string &contextWindow)
virtual ~CExecString ()=default
const std::string & GetExecString () const
bool IsValid () const
const std::string & GetFunction () const
const std::vector< std::string > & GetParams () const
Private Member Functions
bool Parse (const std::string &execString)
bool Parse (const CFileItem &item, const std::string &contextWindow)
void Build (const std::string &function, const std::vector< std::string > &params)
void BuildPlayMedia (const CFileItem &item, const std::string &target)
void SetExecString ()
Private Attributes
bool m_valid {false}
std::string m_function
std::vector< std::string > m_params
std::string m_execString
Constructor & Destructor Documentation
CExecString() [1/5]
CExecString::CExecString () default
CExecString() [2/5]
CExecString::CExecString (const std::string & execString) explicit
References m_valid, and Parse().
CExecString() [3/5]
CExecString::CExecString (const std::string & function, const std::vector< std::string > & params)
References m_function, m_valid, and SetExecString().
CExecString() [4/5]
CExecString::CExecString (const std::string & function, const CFileItem & target, const std::string & param)
References CFileItem::GetPath(), CGUIListItem::m_bIsFolder, m_function, m_params, m_valid, and SetExecString().
CExecString() [5/5]
CExecString::CExecString (const CFileItem & item, const std::string & contextWindow)
References m_valid, and Parse().
~CExecString()
virtual CExecString::~CExecString () virtual default
Member Function Documentation
Build()
void CExecString::Build (const std::string & function, const std::vector< std::string > & params) private
References m_function, m_params, and SetExecString().
Referenced by BuildPlayMedia(), and Parse().
BuildPlayMedia()
void CExecString::BuildPlayMedia (const CFileItem & item, const std::string & target) private
References CVariant::asString(), Build(), CGUIListItem::GetProperty(), and CGUIListItem::HasProperty().
Referenced by Parse().
GetExecString()
const std::string & CExecString::GetExecString () const inline
References m_execString.
Referenced by FAVOURITES_UTILS::ExecuteAction(), anonymous_namespace{DirectoryProvider.cpp}::ExecuteAction(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::ExecuteAction(), CFavouritesURL::GetExecString(), TEST(), and TEST().
GetFunction()
const std::string & CExecString::GetFunction () const inline
References m_function.
Referenced by CInputManager::AlwaysProcess(), CFavouritesURL::CFavouritesURL(), CFavouritesURL::CFavouritesURL(), CFavouritesURL::CFavouritesURL(), CBuiltins::Execute(), XBMCAddon::xbmc::executebuiltin(), CBuiltins::HasCommand(), CBuiltins::IsSystemPowerdownCommand(), CDirectoryProvider::OnClick(), TEST(), and TEST().
GetParams()
const std::vector< std::string > & CExecString::GetParams () const inline
References m_params.
Referenced by CFavouritesURL::CFavouritesURL(), CFavouritesURL::CFavouritesURL(), CFavouritesURL::CFavouritesURL(), CBuiltins::Execute(), XBMCAddon::xbmc::executebuiltin(), CFavouritesURL::GetParams(), CBuiltins::HasCommand(), TEST(), and TEST().
IsValid()
bool CExecString::IsValid () const inline
References m_valid.
Referenced by CInputManager::AlwaysProcess(), CFavouritesURL::CFavouritesURL(), CFavouritesURL::CFavouritesURL(), CFavouritesURL::CFavouritesURL(), CFavouritesURL::CFavouritesURL(), CBuiltins::Execute(), XBMCAddon::xbmc::executebuiltin(), CBuiltins::HasCommand(), CBuiltins::IsSystemPowerdownCommand(), CFavouritesURL::IsValid(), TEST(), and TEST().
Parse() [1/2]
bool CExecString::Parse (const CFileItem & item, const std::string & contextWindow) private
References Build(), BuildPlayMedia(), CURL::GetFileName(), CURL::GetHostName(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), MUSIC_INFO::CMusicInfoTag::GetURL(), CFileItem::GetVideoInfoTag(), CFileItem::HasMusicInfoTag(), CFileItem::HasVideoInfoTag(), CFileItem::IsAddonsPath(), CFileItem::IsAndroidApp(), CFileItem::IsFavourite(), KODI::MUSIC::IsMusicDb(), CFileItem::IsPicture(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsScript(), KODI::PLAYLIST::IsSmartPlayList(), CGUIListItem::m_bIsFolder, CVideoInfoTag::m_strFileNameAndPath, and Parse().
Parse() [2/2]
bool CExecString::Parse (const std::string & execString) private
References m_execString, m_function, and m_params.
Referenced by CExecString(), CExecString(), and Parse().
SetExecString()
void CExecString::SetExecString () private
References m_execString, m_function, and m_params.
Referenced by Build(), CExecString(), and CExecString().
Member Data Documentation
m_execString
std::string CExecString::m_execString private
Referenced by GetExecString(), Parse(), and SetExecString().
m_function
std::string CExecString::m_function private
Referenced by Build(), CExecString(), CExecString(), GetFunction(), Parse(), and SetExecString().
m_params
std::vector<std::string> CExecString::m_params private
Referenced by Build(), CExecString(), GetParams(), Parse(), and SetExecString().
m_valid
bool CExecString::m_valid {false} private
Referenced by CExecString(), CExecString(), CExecString(), CExecString(), and IsValid().
The documentation for this class was generated from the following files:
ExecString.h
ExecString.cpp