Kodi Documentation: PVR::CPVRProvidersContainer Class Reference
PVR::CPVRProvidersContainer Class Reference
#include <PVRProviders.h>
Public Member Functions
bool UpdateFromClient (const std::shared_ptr< CPVRProvider > &provider)
Add a provider to this container or update the provider if already present in this container.
std::shared_ptr< CPVRProvider > GetByClient (int iClientId, int iUniqueId) const
Get the provider denoted by given client id and unique client provider id.
std::vector< std::shared_ptr< CPVRProvider > > GetProvidersList () const
Protected Member Functions
void InsertEntry (const std::shared_ptr< CPVRProvider > &newProvider, ProviderUpdateMode updateMode)
Protected Attributes
CCriticalSection m_critSection
int m_iLastId = 0
std::vector< std::shared_ptr< CPVRProvider > > m_providers
Member Function Documentation
GetByClient()
std::shared_ptr< CPVRProvider > CPVRProvidersContainer::GetByClient (int iClientId, int iUniqueId) const
Get the provider denoted by given client id and unique client provider id.
Parameters
iClientId The client id.
iUniqueId The client provider id.
Returns
the provider if found, null otherwise.
References m_critSection, and m_providers.
Referenced by PVR::CPVRProviders::CheckAndAddEntry(), PVR::CPVRProviders::CheckAndPersistEntry(), PVR::CPVRProviders::UpdateClientEntries(), PVR::CPVRProviders::UpdateDefaultEntries(), and UpdateFromClient().
GetProvidersList()
std::vector< std::shared_ptr< CPVRProvider > > CPVRProvidersContainer::GetProvidersList () const
Get all providers in this container
Returns
The list of all providers
References m_critSection, and m_providers.
Referenced by PVR::CPVRProviders::LoadFromDatabase(), PVR::CPVRProviders::UpdateClientEntries(), and PVR::CPVRProviders::UpdateDefaultEntries().
InsertEntry()
void CPVRProvidersContainer::InsertEntry (const std::shared_ptr< CPVRProvider > & newProvider, ProviderUpdateMode updateMode) protected
References m_providers.
Referenced by PVR::CPVRProviders::CheckAndAddEntry(), PVR::CPVRProviders::CheckAndPersistEntry(), and UpdateFromClient().
UpdateFromClient()
bool CPVRProvidersContainer::UpdateFromClient (const std::shared_ptr< CPVRProvider > & provider)
Add a provider to this container or update the provider if already present in this container.
Parameters
The provider
Returns
True, if the update was successful. False, otherwise.
References PVR::BY_CLIENT, GetByClient(), InsertEntry(), m_critSection, and m_iLastId.
Referenced by PVR::CPVRClient::cb_transfer_provider_entry().
Member Data Documentation
m_critSection
CCriticalSection PVR::CPVRProvidersContainer::m_critSection mutable protected
Referenced by PVR::CPVRProviders::CheckAndAddEntry(), PVR::CPVRProviders::CheckAndPersistEntry(), PVR::CPVRProviders::CleanupCachedImages(), GetByClient(), PVR::CPVRProviders::GetById(), PVR::CPVRProviders::GetNumProviders(), PVR::CPVRProviders::GetProviders(), GetProvidersList(), PVR::CPVRProviders::RemoveEntry(), PVR::CPVRProviders::Unload(), PVR::CPVRProviders::UpdateClientEntries(), PVR::CPVRProviders::UpdateDefaultEntries(), UpdateFromClient(), and PVR::CPVRProviders::UpdateFromClients().
m_iLastId
int PVR::CPVRProvidersContainer::m_iLastId = 0 protected
Referenced by PVR::CPVRProviders::CheckAndAddEntry(), PVR::CPVRProviders::CheckAndPersistEntry(), PVR::CPVRProviders::LoadFromDatabase(), and UpdateFromClient().
m_providers
std::vector<std::shared_ptr<CPVRProvider> > PVR::CPVRProvidersContainer::m_providers protected
Referenced by PVR::CPVRProviders::CleanupCachedImages(), GetByClient(), PVR::CPVRProviders::GetById(), PVR::CPVRProviders::GetProviders(), GetProvidersList(), InsertEntry(), PVR::CPVRProviders::RemoveEntry(), PVR::CPVRProviders::Unload(), PVR::CPVRProviders::UpdateClientEntries(), and PVR::CPVRProviders::UpdateDefaultEntries().
The documentation for this class was generated from the following files:
PVRProviders.h
PVRProviders.cpp