Kodi Documentation: KODI::anonymous_namespace{VideoGUIUtils.cpp} Namespace Reference
KODI::anonymous_namespace{VideoGUIUtils.cpp} Namespace Reference
Classes
class CAsyncGetItemsForPlaylist
Functions
SortDescription GetSortDescription (const CGUIViewState &state, const CFileItemList &items)
std::string GetVideoDbItemPath (const CFileItem &item)
void AddItemToPlayListAndPlay (const std::shared_ptr< CFileItem > &itemToQueue, const std::shared_ptr< CFileItem > &itemToPlay, const std::string &player)
Function Documentation
AddItemToPlayListAndPlay()
void KODI::anonymous_namespace{VideoGUIUtils.cpp}::AddItemToPlayListAndPlay (const std::shared_ptr< CFileItem > & itemToQueue, const std::shared_ptr< CFileItem > & itemToPlay, const std::string & player)
References KODI::PLAYLIST::CPlayList::FindOrder(), KODI::VIDEO::UTILS::GetItemsForPlayList(), CServiceBroker::GetPlaylistPlayer(), KODI::PLAYLIST::CPlayList::Swap(), and KODI::PLAYLIST::TYPE_VIDEO.
GetSortDescription()
SortDescription KODI::anonymous_namespace{VideoGUIUtils.cpp}::GetSortDescription (const CGUIViewState & state, const CFileItemList & items)
References CGUIViewState::GetSortDescriptions(), CGUIViewState::GetSortMethod(), SortDescription::sortBy, SortByDate, SortByEpisodeNumber, SortByNone, SortByYear, SortDescription::sortOrder, and SortOrderAscending.
GetVideoDbItemPath()
std::string KODI::anonymous_namespace{VideoGUIUtils.cpp}::GetVideoDbItemPath (const CFileItem & item)
References CVariant::asString(), CFileItem::GetPath(), CGUIListItem::GetProperty(), GetVideoDbItemPath(), and URIUtils::IsVideoDb().
Referenced by GetVideoDbItemPath().