Kodi Documentation: ADDON::CAddonType Class Reference
ADDON::CAddonType Class Reference
#include <AddonType.h>
Public Member Functions
CAddonType (AddonType type=AddonType::UNKNOWN)
AddonType Type () const
std::string LibPath () const
const std::string & LibName () const
bool ProvidesSubContent (const AddonType &content) const
bool ProvidesSeveralSubContents () const
size_t ProvidedSubContents () const
Public Member Functions inherited from ADDON::CAddonExtensions
CAddonExtensions ()=default
~CAddonExtensions ()=default
const SExtValue GetValue (const std::string &id) const
const EXT_VALUES & GetValues () const
const CAddonExtensions * GetElement (const std::string &id) const
const EXT_ELEMENTS GetElements (const std::string &id="") const
void Insert (const std::string &id, const std::string &value)
Static Public Member Functions
static bool IsDependencyType (AddonType type)
Indicates whether a given type is a dependency type (e.g. addons which the main type is a script.module)
Private Member Functions
void SetProvides (const std::string &content)
Private Attributes
AddonType m_type
std::string m_path
std::string m_libname
std::set< AddonType > m_providedSubContent
Friends
class CAddonInfoBuilder
class CAddonInfoBuilderFromDB
class CAddonDatabaseSerializer
Constructor & Destructor Documentation
CAddonType()
ADDON::CAddonType::CAddonType (AddonType type = AddonType::UNKNOWN) inline
Member Function Documentation
IsDependencyType()
bool CAddonType::IsDependencyType (AddonType type) static
Indicates whether a given type is a dependency type (e.g. addons which the main type is a script.module)
Parameters
[in] type the provided type
Returns
true if type is one of the dependency types
References ADDON::dependencyTypes.
Referenced by CApplication::ConfigureAndEnableAddons(), XFILE::GenerateMainCategoryListing(), ADDON::CAddonMgr::IsOrphaned(), XFILE::IsUserInstalled(), and CApplication::OnMessage().
LibName()
const std::string & ADDON::CAddonType::LibName () const inline
References m_libname.
LibPath()
std::string CAddonType::LibPath () const
References URIUtils::AddFileToFolder(), m_libname, and m_path.
ProvidedSubContents()
size_t ADDON::CAddonType::ProvidedSubContents () const inline
References m_providedSubContent.
Referenced by ADDON::CAddonInfo::ProvidesSeveralSubContents().
ProvidesSeveralSubContents()
bool ADDON::CAddonType::ProvidesSeveralSubContents () const inline
References m_providedSubContent.
ProvidesSubContent()
bool ADDON::CAddonType::ProvidesSubContent (const AddonType & content) const inline
References ADDON::content, m_providedSubContent, m_type, and ADDON::UNKNOWN.
SetProvides()
void CAddonType::SetProvides (const std::string & content) private
References ADDON::content, ADDON::CAddonExtensions::GetValue(), ADDON::CAddonExtensions::Insert(), m_providedSubContent, ADDON::CAddonInfo::TranslateSubContent(), and ADDON::UNKNOWN.
Referenced by ADDON::CAddonInfoBuilder::ParseXMLTypes(), and ADDON::CAddonInfoBuilderFromDB::SetExtensions().
Type()
AddonType ADDON::CAddonType::Type () const inline
References m_type.
Referenced by ADDON::CAddon::Type().
Friends And Related Symbol Documentation
CAddonDatabaseSerializer
friend class CAddonDatabaseSerializer friend
CAddonInfoBuilder
friend class CAddonInfoBuilder friend
CAddonInfoBuilderFromDB
friend class CAddonInfoBuilderFromDB friend
Member Data Documentation
m_libname
std::string ADDON::CAddonType::m_libname private
Referenced by LibName(), LibPath(), and ADDON::CAddonInfoBuilder::ParseXMLTypes().
m_path
std::string ADDON::CAddonType::m_path private
Referenced by LibPath(), and ADDON::CAddonInfoBuilder::ParseXMLTypes().
m_providedSubContent
std::set<AddonType> ADDON::CAddonType::m_providedSubContent private
Referenced by ProvidedSubContents(), ProvidesSeveralSubContents(), ProvidesSubContent(), and SetProvides().
m_type
AddonType ADDON::CAddonType::m_type private
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata(), ProvidesSubContent(), ADDON::CAddonInfoBuilderFromDB::SetExtensions(), and Type().
The documentation for this class was generated from the following files:
AddonType.h
AddonType.cpp