Kodi Documentation: CPosixMountProvider Class Reference
CPosixMountProvider Class Reference
#include <PosixMountProvider.h>
Public Member Functions
CPosixMountProvider ()
~CPosixMountProvider () override=default
void Initialize () override
void Stop () override
void GetLocalDrives (std::vector< CMediaSource > &localDrives) override
void GetRemovableDrives (std::vector< CMediaSource > &removableDrives) override
std::vector< std::string > GetDiskUsage () override
bool Eject (const std::string &mountpath) override
bool PumpDriveChangeEvents (IStorageEventsCallback *callback) override
Public Member Functions inherited from IStorageProvider
virtual ~IStorageProvider ()=default
virtual std::string GetFirstOpticalDeviceFileName ()
Private Member Functions
void GetDrives (std::vector< CMediaSource > &drives)
Private Attributes
unsigned int m_removableLength
Additional Inherited Members
Static Public Member Functions inherited from IStorageProvider
static std::unique_ptr< IStorageProvider > CreateInstance ()
Called by media manager to create platform storage provider.
Constructor & Destructor Documentation
CPosixMountProvider()
CPosixMountProvider::CPosixMountProvider ()
References m_removableLength, and PumpDriveChangeEvents().
~CPosixMountProvider()
CPosixMountProvider::~CPosixMountProvider () override default
Member Function Documentation
Eject()
bool CPosixMountProvider::Eject (const std::string & mountpath) override virtual
Implements IStorageProvider.
GetDiskUsage()
std::vector< std::string > CPosixMountProvider::GetDiskUsage (void) override virtual
Implements IStorageProvider.
Referenced by CUDevProvider::GetDiskUsage(), CUDisks2Provider::GetDiskUsage(), and CUDisksProvider::GetDiskUsage().
GetDrives()
void CPosixMountProvider::GetDrives (std::vector< CMediaSource > & drives) private
References URIUtils::GetFileName(), CRegExp::GetReplaceString(), CMediaSource::m_ignore, CRegExp::RegComp(), CRegExp::RegFind(), CMediaSource::strName, and CMediaSource::strPath.
Referenced by GetLocalDrives().
GetLocalDrives()
void CPosixMountProvider::GetLocalDrives (std::vector< CMediaSource > & localDrives) inline override virtual
Implements IStorageProvider.
References GetDrives().
GetRemovableDrives()
void CPosixMountProvider::GetRemovableDrives (std::vector< CMediaSource > & removableDrives) inline override virtual
Implements IStorageProvider.
Referenced by PumpDriveChangeEvents().
Initialize()
void CPosixMountProvider::Initialize () override virtual
Implements IStorageProvider.
References CLog::Log(), and LOGDEBUG.
PumpDriveChangeEvents()
bool CPosixMountProvider::PumpDriveChangeEvents (IStorageEventsCallback * callback) override virtual
Implements IStorageProvider.
References GetRemovableDrives(), and m_removableLength.
Referenced by CPosixMountProvider().
Stop()
void CPosixMountProvider::Stop () inline override virtual
Implements IStorageProvider.
Member Data Documentation
m_removableLength
unsigned int CPosixMountProvider::m_removableLength private
Referenced by CPosixMountProvider(), and PumpDriveChangeEvents().
The documentation for this class was generated from the following files:
PosixMountProvider.h
PosixMountProvider.cpp