Kodi Documentation: CMime Class Reference
CMime Class Reference
#include <Mime.h>
Public Types
enum EFileType {
FileTypeUnknown = 0 , FileTypeHtml , FileTypeXml , FileTypePlainText ,
FileTypeZip , FileTypeGZip , FileTypeRar , FileTypeBmp ,
FileTypeGif , FileTypePng , FileTypeJpeg
}
Static Public Member Functions
static std::string GetMimeType (const std::string &extension)
static std::string GetMimeType (const CFileItem &item)
static std::string GetMimeType (const CURL &url, bool lookup=true)
static EFileType GetFileTypeFromMime (const std::string &mimeType)
static EFileType GetFileTypeFromContent (const std::string &fileContent)
Static Private Member Functions
static bool parseMimeType (const std::string &mimeType, std::string &type, std::string &subtype)
Member Enumeration Documentation
EFileType
enum CMime::EFileType
Enumerator
FileTypeUnknown
FileTypeHtml
FileTypeXml
FileTypePlainText
FileTypeZip
FileTypeGZip
FileTypeRar
FileTypeBmp
FileTypeGif
FileTypePng
FileTypeJpeg
Member Function Documentation
GetFileTypeFromContent()
CMime::EFileType CMime::GetFileTypeFromContent (const std::string & fileContent) static
Todo:
add detection for text types
Todo:
add detection for other types if required
References FileTypeBmp, FileTypeGif, FileTypeGZip, FileTypeJpeg, FileTypePng, FileTypeRar, FileTypeUnknown, and FileTypeZip.
Referenced by CScraperUrl::Get().
GetFileTypeFromMime()
CMime::EFileType CMime::GetFileTypeFromMime (const std::string & mimeType) static
References FileTypeBmp, FileTypeGif, FileTypeGZip, FileTypeHtml, FileTypeJpeg, FileTypePlainText, FileTypePng, FileTypeRar, FileTypeUnknown, FileTypeXml, FileTypeZip, and parseMimeType().
Referenced by ADDON::CRepository::FetchIndex(), and CScraperUrl::Get().
GetMimeType() [1/3]
std::string CMime::GetMimeType (const CFileItem & item) static
References CFileItem::GetDynPath(), URIUtils::GetExtension(), GetMimeType(), CFileItem::GetMusicInfoTag(), CVideoInfoTag::GetPath(), MUSIC_INFO::CMusicInfoTag::GetURL(), CFileItem::GetVideoInfoTag(), CFileItem::HasMusicInfoTag(), and CFileItem::HasVideoInfoTag().
GetMimeType() [2/3]
std::string CMime::GetMimeType (const CURL & url, bool lookup = true) static
References CURL::GetFileType(), XFILE::CCurlFile::GetMimeType(), GetMimeType(), and CURL::IsProtocol().
GetMimeType() [3/3]
std::string CMime::GetMimeType (const std::string & extension) static
Referenced by CHTTPImageTransformationHandler::CHTTPImageTransformationHandler(), ImageFactory::CreateLoader(), CWebServer::CreateMimeTypeFromExtension(), CFileItem::FillInMimeType(), GetMimeType(), GetMimeType(), KODI::ADDONS::CAudioDecoder::Load(), CHTTPFileHandler::SetFile(), TEST(), and TEST().
parseMimeType()
bool CMime::parseMimeType (const std::string & mimeType, std::string & type, std::string & subtype) static private
Referenced by GetFileTypeFromMime().
The documentation for this class was generated from the following files:
Mime.h
Mime.cpp