Kodi Documentation: TestAddonVersion.cpp File Reference
TestAddonVersion.cpp File Reference
#include "addons/AddonVersion.h"
#include <gtest/gtest.h>
Classes
class TestAddonVersion
Functions
TEST_F (TestAddonVersion, Constructor)
TEST_F (TestAddonVersion, asString)
TEST_F (TestAddonVersion, Equals)
TEST_F (TestAddonVersion, LessThan)
TEST_F (TestAddonVersion, Equivalent)
Function Documentation
TEST_F() [1/5]
TEST_F (TestAddonVersion , asString)
References EXPECT_EQ().
TEST_F() [2/5]
TEST_F (TestAddonVersion , Constructor)
References EXPECT_EQ(), and EXPECT_TRUE().
TEST_F() [3/5]
TEST_F (TestAddonVersion , Equals)
References EXPECT_EQ().
TEST_F() [4/5]
TEST_F (TestAddonVersion , Equivalent)
References EXPECT_TRUE().
TEST_F() [5/5]
TEST_F (TestAddonVersion , LessThan)