Kodi Documentation: PVR::CPVRClient Class Reference
PVR::CPVRClient Class Reference
#include <PVRClient.h>
Public Member Functions
CPVRClient (const ADDON::AddonInfoPtr &addonInfo, ADDON::AddonInstanceId instanceId, int clientId)
~CPVRClient () override
void OnPreInstall () override
void OnPreUnInstall () override
PVR add-on methods
ADDON_STATUS Create ()
Initialise the instance of this add-on.
void Stop ()
Stop this add-on instance. No more client add-on access after this call.
void Continue ()
Continue this add-on instance. Client add-on access is okay again after this call.
void Destroy ()
Destroy the instance of this add-on.
void ReCreate ()
Destroy and recreate this add-on.
bool ReadyToUse () const
PVR_CONNECTION_STATE GetConnectionState () const
Gets the backend connection state.
void SetConnectionState (PVR_CONNECTION_STATE state)
Sets the backend connection state.
PVR_CONNECTION_STATE GetPreviousConnectionState () const
Gets the backend's previous connection state.
bool IgnoreClient () const
Check whether this client should be ignored.
bool IsEnabled () const
Check whether this client is enabled, according to its instance/add-on configuration.
int GetID () const
PVR server methods
const CPVRClientCapabilities & GetClientCapabilities () const
Query this add-on's capabilities.
PVR_ERROR GetStreamProperties (PVR_STREAM_PROPERTIES *pProperties) const
Get the stream properties of the stream that's currently being read.
PVR_ERROR StreamClosed () const
A stream was closed or has ended.
const std::string & GetBackendName () const
const std::string & GetBackendVersion () const
const std::string & GetBackendHostname () const
the ip address or alias of the pvr backend server
const std::string & GetConnectionString () const
std::string GetClientName () const
The name of the PVR client, as specified by the addon developer.
std::string GetInstanceName () const
The name of the PVR client addon instance, as specified by the user in the addon settings. Empty if addon does not support multiple instances.
std::string GetFullClientName () const
A name used to uniquely identify the client, inclusing addon name and instance name, if multiple instances are supported by the client implementation.
PVR_ERROR GetDriveSpace (uint64_t &iTotal, uint64_t &iUsed) const
Get the disk space reported by the server.
PVR_ERROR StartChannelScan ()
Start a channel scan on the server.
PVR_ERROR OpenDialogChannelAdd (const std::shared_ptr< const CPVRChannel > &channel)
Request the client to open dialog about given channel to add.
PVR_ERROR OpenDialogChannelSettings (const std::shared_ptr< const CPVRChannel > &channel)
Request the client to open dialog about given channel settings.
PVR_ERROR DeleteChannel (const std::shared_ptr< const CPVRChannel > &channel)
Request the client to delete given channel.
PVR_ERROR RenameChannel (const std::shared_ptr< const CPVRChannel > &channel)
Request the client to rename given channel.
PVR_ERROR IsRecordable (const std::shared_ptr< const CPVREpgInfoTag > &tag, bool &bIsRecordable) const
PVR_ERROR IsPlayable (const std::shared_ptr< const CPVREpgInfoTag > &tag, bool &bIsPlayable) const
PVR_ERROR GetEpgTagStreamProperties (const std::shared_ptr< const CPVREpgInfoTag > &tag, CPVRStreamProperties &props) const
Fill the given container with the properties required for playback of the given EPG tag. Values are obtained from the PVR backend.
PVR EPG methods
PVR_ERROR GetEPGForChannel (int iChannelUid, CPVREpg *epg, time_t start, time_t end) const
Request an EPG table for a channel from the client.
PVR_ERROR SetEPGMaxPastDays (int iPastDays)
Tell the client the past time frame to use when notifying epg events back to Kodi.
PVR_ERROR SetEPGMaxFutureDays (int iFutureDays)
Tell the client the future time frame to use when notifying epg events back to Kodi.
PVR channel group methods
PVR_ERROR GetChannelGroupsAmount (int &iGroups) const
Get the total amount of channel groups from the backend.
PVR_ERROR GetChannelGroups (CPVRChannelGroups *groups) const
Request the list of all channel groups from the backend.
PVR_ERROR GetChannelGroupMembers (CPVRChannelGroup *group, std::vector< std::shared_ptr< CPVRChannelGroupMember > > &groupMembers) const
Request the list of all group members from the backend.
PVR channel methods
PVR_ERROR GetChannelsAmount (int &iChannels) const
Get the total amount of channels from the backend.
PVR_ERROR GetChannels (bool bRadio, std::vector< std::shared_ptr< CPVRChannel > > &channels) const
Request the list of all channels from the backend.
PVR_ERROR GetProvidersAmount (int &iProviders) const
Get the total amount of providers from the backend.
PVR_ERROR GetProviders (CPVRProvidersContainer &providers) const
Request the list of all providers from the backend.
PVR recording methods
PVR_ERROR GetRecordingsAmount (bool deleted, int &iRecordings) const
Get the total amount of recordings from the backend.
PVR_ERROR GetRecordings (CPVRRecordings *results, bool deleted) const
Request the list of all recordings from the backend.
PVR_ERROR DeleteRecording (const CPVRRecording &recording)
Delete a recording on the backend.
PVR_ERROR UndeleteRecording (const CPVRRecording &recording)
Undelete a recording on the backend.
PVR_ERROR DeleteAllRecordingsFromTrash ()
Delete all recordings permanent which in the deleted folder on the backend.
PVR_ERROR RenameRecording (const CPVRRecording &recording)
Rename a recording on the backend.
PVR_ERROR SetRecordingLifetime (const CPVRRecording &recording)
Set the lifetime of a recording on the backend.
PVR_ERROR SetRecordingPlayCount (const CPVRRecording &recording, int count)
Set the play count of a recording on the backend.
PVR_ERROR SetRecordingLastPlayedPosition (const CPVRRecording &recording, int lastplayedposition)
Set the last watched position of a recording on the backend.
PVR_ERROR GetRecordingLastPlayedPosition (const CPVRRecording &recording, int &iPosition) const
Retrieve the last watched position of a recording on the backend.
PVR_ERROR GetRecordingEdl (const CPVRRecording &recording, std::vector< EDL::Edit > &edls) const
Retrieve the edit decision list (EDL) from the backend.
PVR_ERROR GetRecordingSize (const CPVRRecording &recording, int64_t &sizeInBytes) const
Retrieve the size of a recording on the backend.
PVR_ERROR GetEpgTagEdl (const std::shared_ptr< const CPVREpgInfoTag > &epgTag, std::vector< EDL::Edit > &edls) const
Retrieve the edit decision list (EDL) from the backend.
PVR timer methods
PVR_ERROR GetTimersAmount (int &iTimers) const
Get the total amount of timers from the backend.
PVR_ERROR GetTimers (CPVRTimersContainer *results) const
Request the list of all timers from the backend.
PVR_ERROR AddTimer (const CPVRTimerInfoTag &timer)
Add a timer on the backend.
PVR_ERROR DeleteTimer (const CPVRTimerInfoTag &timer, bool bForce=false)
Delete a timer on the backend.
PVR_ERROR UpdateTimer (const CPVRTimerInfoTag &timer)
Update the timer information on the server.
PVR_ERROR UpdateTimerTypes ()
Update all timer types supported by the backend.
const std::vector< std::shared_ptr< CPVRTimerType > > & GetTimerTypes () const
Get the timer types supported by the backend, without updating them from the backend.
PVR live stream methods
PVR_ERROR OpenLiveStream (const std::shared_ptr< const CPVRChannel > &channel)
Open a live stream on the server.
PVR_ERROR CloseLiveStream ()
Close an open live stream.
PVR_ERROR ReadLiveStream (void *lpBuf, int64_t uiBufSize, int &iRead)
Read from an open live stream.
PVR_ERROR SeekLiveStream (int64_t iFilePosition, int iWhence, int64_t &iPosition)
Seek in a live stream on a backend.
PVR_ERROR GetLiveStreamLength (int64_t &iLength) const
Get the length of the currently playing live stream, if any.
PVR_ERROR PauseStream (bool bPaused)
(Un)Pause a stream.
PVR_ERROR SignalQuality (int channelUid, CPVRSignalStatus &qualityinfo) const
Get the signal quality of the stream that's currently open.
PVR_ERROR GetDescrambleInfo (int channelUid, CPVRDescrambleInfo &descrambleinfo) const
Get the descramble information of the stream that's currently open.
PVR_ERROR GetChannelStreamProperties (const std::shared_ptr< const CPVRChannel > &channel, PVR_SOURCE source, CPVRStreamProperties &props) const
Fill the given container with the properties required for playback of the given channel. Values are obtained from the PVR backend.
PVR_ERROR CanPauseStream (bool &bCanPause) const
Check whether PVR backend supports pausing the currently playing stream.
PVR_ERROR CanSeekStream (bool &bCanSeek) const
Check whether PVR backend supports seeking for the currently playing stream.
PVR_ERROR SeekTime (double time, bool backwards, double *startpts)
Notify the pvr addon/demuxer that Kodi wishes to seek the stream by time.
PVR_ERROR SetSpeed (int speed)
Notify the pvr addon/demuxer that Kodi wishes to change playback speed.
PVR_ERROR FillBuffer (bool mode)
Notify the pvr addon/demuxer that Kodi wishes to fill demux queue.
PVR recording stream methods
PVR_ERROR OpenRecordedStream (const std::shared_ptr< const CPVRRecording > &recording, int64_t &streamId)
Open a recording on the server.
PVR_ERROR CloseRecordedStream (int64_t streamId)
Close an open recording stream.
PVR_ERROR ReadRecordedStream (int64_t streamId, void *lpBuf, int64_t uiBufSize, int &iRead)
Read from an open recording stream.
PVR_ERROR SeekRecordedStream (int64_t streamId, int64_t iFilePosition, int iWhence, int64_t &iPosition)
Seek in a recording stream on a backend.
PVR_ERROR GetRecordedStreamLength (int64_t streamId, int64_t &iLength) const
Get the length of the given stream.
PVR_ERROR IsRecordedStreamRealTime (int64_t streamId, bool &isRealTime) const
Check whether the given stream is a real-time stream.
PVR_ERROR PauseRecordedStream (int64_t streamId, bool paused)
(Un)Pause a stream.
PVR_ERROR GetRecordedStreamTimes (int64_t streamId, PVR_STREAM_TIMES *times) const
Get stream times for the given stream.
PVR_ERROR GetRecordingStreamProperties (const std::shared_ptr< const CPVRRecording > &recording, CPVRStreamProperties &props) const
Fill the given container with the properties required for playback of the given recording. Values are obtained from the PVR backend.
Public Member Functions inherited from ADDON::IAddonInstanceHandler
IAddonInstanceHandler (ADDON_TYPE type, const AddonInfoPtr &addonInfo, AddonInstanceId instanceId=ADDON_INSTANCE_ID_UNUSED, KODI_HANDLE parentInstance=nullptr, const std::string &uniqueWorkID="")
Class constructor for handling add-on instance processes, allowing an add-on to handle multiple work simultaneously and independently.
virtual ~IAddonInstanceHandler ()
ADDON_TYPE UsedType () const
AddonInstanceId InstanceId () const
const std::string & UniqueWorkID ()
std::string ID () const
AddonInstanceId InstanceID () const
std::string Name () const
std::string Author () const
std::string Icon () const
std::string Path () const
std::string Profile () const
CAddonVersion Version () const
ADDON_STATUS CreateInstance ()
void DestroyInstance ()
const AddonDllPtr & Addon () const
AddonInfoPtr GetAddonInfo () const
virtual void OnPostInstall (bool update, bool modal)
virtual void OnPostUnInstall ()
PVR demultiplexer methods
typedef AddonInstance_PVR AddonInstance
Wraps an addon function call in order to do common pre and post function invocation actions.
const int m_iClientId
std::atomic< bool > m_bReadyToUse
std::atomic< bool > m_bBlockAddonCalls
std::atomic< int > m_iAddonCalls
CEvent m_allAddonCallsFinished
PVR_CONNECTION_STATE m_connectionState
PVR_CONNECTION_STATE m_prevConnectionState
bool m_ignoreClient
std::vector< std::shared_ptr< CPVRTimerType > > m_timertypes
std::optional< int > m_priority
std::optional< CDateTime > m_firstChannelsAdded
std::string m_strBackendName
std::string m_strBackendVersion
std::string m_strConnectionString
std::string m_strBackendHostname
CPVRClientCapabilities m_clientCapabilities
std::shared_ptr< CPVRClientMenuHooks > m_menuhooks
std::string m_strUserPath
translated path to the user profile
std::string m_strClientPath
translated path to this add-on
CCriticalSection m_critSection
PVR_ERROR DemuxReset ()
Reset the demultiplexer in the add-on.
PVR_ERROR DemuxAbort ()
Abort the demultiplexer thread in the add-on.
PVR_ERROR DemuxFlush ()
Flush all data that's currently in the demultiplexer buffer in the add-on.
PVR_ERROR DemuxRead (DemuxPacket *&packet)
Read a packet from the demultiplexer.
PVR_ERROR IsRealTimeStream (bool &bRealTime) const
Check whether the currently playing stream, if any, is a real-time stream.
PVR_ERROR GetStreamTimes (PVR_STREAM_TIMES *times) const
Get Stream times for the currently playing stream, if any (will be moved to inputstream).
std::shared_ptr< CPVRClientMenuHooks > GetMenuHooks () const
Get the client's menu hooks.
PVR_ERROR CallEpgTagMenuHook (const CPVRClientMenuHook &hook, const std::shared_ptr< const CPVREpgInfoTag > &tag)
Call one of the EPG tag menu hooks of the client.
PVR_ERROR CallChannelMenuHook (const CPVRClientMenuHook &hook, const std::shared_ptr< const CPVRChannel > &channel)
Call one of the channel menu hooks of the client.
PVR_ERROR CallRecordingMenuHook (const CPVRClientMenuHook &hook, const std::shared_ptr< const CPVRRecording > &recording, bool bDeleted)
Call one of the recording menu hooks of the client.
PVR_ERROR CallTimerMenuHook (const CPVRClientMenuHook &hook, const std::shared_ptr< const CPVRTimerInfoTag > &timer)
Call one of the timer menu hooks of the client.
PVR_ERROR CallSettingsMenuHook (const CPVRClientMenuHook &hook)
Call one of the settings menu hooks of the client.
PVR_ERROR OnSystemSleep ()
Propagate power management events to this add-on.
PVR_ERROR OnSystemWake ()
PVR_ERROR OnPowerSavingActivated ()
PVR_ERROR OnPowerSavingDeactivated ()
int GetPriority () const
Get the priority of this client. Larger value means higher priority.
void SetPriority (int iPriority)
Set a new priority for this client.
const CDateTime & GetDateTimeFirstChannelsAdded () const
Get the date and time first channels were added for this client.
void SetDateTimeFirstChannelsAdded (const CDateTime &dateTime)
Set the date and time first channels were added for this client.
PVR_ERROR GetStreamReadChunkSize (int &iChunkSize) const
Obtain the chunk size to use when reading streams.
static const char * ToString (const PVR_ERROR error)
void ResetProperties ()
Resets all class members to their defaults, accept the client id.
bool GetAddonProperties ()
reads the client's properties.
bool GetAddonNameStringProperties ()
reads the client's name string properties
bool CanPlayChannel (const std::shared_ptr< const CPVRChannel > &channel) const
Whether a channel can be played by this add-on.
void StopRunningInstance ()
Stop this instance, if it is currently running.
PVR_ERROR DoAddonCall (const char *strFunctionName, const std::function< PVR_ERROR(const AddonInstance *)> &function, bool bIsImplemented=true, bool bCheckReadyToUse=true) const
static void WriteStreamProperties (PVR_NAMED_VALUE **properties, unsigned int iPropertyCount, CPVRStreamProperties &props)
Write the given addon properties to the given properties container.
static void HandleAddonCallback (const char *strFunctionName, void *kodiInstance, const std::function< void(CPVRClient *client)> &function, bool bForceCall=false)
Wraps an addon callback function call in order to do common pre and post function invocation actions.
static void cb_transfer_channel_group (void *kodiInstance, const PVR_HANDLE handle, const PVR_CHANNEL_GROUP *entry)
Callback functions from addon to kodi.
static void cb_transfer_channel_group_member (void *kodiInstance, const PVR_HANDLE handle, const PVR_CHANNEL_GROUP_MEMBER *entry)
Transfer a channel group member entry from the add-on to Kodi. The channel will be added to the group if the group can be found.
static void cb_transfer_epg_entry (void *kodiInstance, const PVR_HANDLE handle, const EPG_TAG *entry)
Transfer an EPG tag from the add-on to Kodi.
static void cb_transfer_channel_entry (void *kodiInstance, const PVR_HANDLE handle, const PVR_CHANNEL *entry)
Transfer a channel entry from the add-on to Kodi.
static void cb_transfer_provider_entry (void *kodiInstance, const PVR_HANDLE handle, const PVR_PROVIDER *entry)
Transfer a provider entry from the add-on to Kodi.
static void cb_transfer_timer_entry (void *kodiInstance, const PVR_HANDLE handle, const PVR_TIMER *entry)
Transfer a timer entry from the add-on to Kodi.
static void cb_transfer_recording_entry (void *kodiInstance, const PVR_HANDLE handle, const PVR_RECORDING *entry)
Transfer a recording entry from the add-on to Kodi.
static void cb_add_menu_hook (void *kodiInstance, const PVR_MENUHOOK *hook)
Add or replace a menu hook for the context menu for this add-on.
static void cb_recording_notification (void *kodiInstance, const char *strName, const char *strFileName, bool bOnOff)
Display a notification in Kodi that a recording started or stopped on the server.
static void cb_trigger_channel_update (void *kodiInstance)
Request Kodi to update it's list of channels.
static void cb_trigger_provider_update (void *kodiInstance)
Request Kodi to update it's list of providers.
static void cb_trigger_timer_update (void *kodiInstance)
Request Kodi to update it's list of timers.
static void cb_trigger_recording_update (void *kodiInstance)
Request Kodi to update it's list of recordings.
static void cb_trigger_channel_groups_update (void *kodiInstance)
Request Kodi to update it's list of channel groups.
static void cb_trigger_epg_update (void *kodiInstance, unsigned int iChannelUid)
Schedule an EPG update for the given channel channel.
static void cb_free_demux_packet (void *kodiInstance, DEMUX_PACKET *pPacket)
Free a packet that was allocated with AllocateDemuxPacket.
static DEMUX_PACKET * cb_allocate_demux_packet (void *kodiInstance, int iDataSize=0)
Allocate a demux packet. Free with FreeDemuxPacket.
static void cb_connection_state_change (void *kodiInstance, const char *strConnectionString, PVR_CONNECTION_STATE newState, const char *strMessage)
Notify a state change for a PVR backend connection.
static void cb_epg_event_state_change (void *kodiInstance, EPG_TAG *tag, EPG_EVENT_STATE newState)
Notify a state change for an EPG event.
static PVR_CODEC cb_get_codec_by_name (const void *kodiInstance, const char *strCodecName)
Additional Inherited Members
Protected Attributes inherited from ADDON::IAddonInstanceHandler
KODI_ADDON_INSTANCE_INFO m_info {}
KODI_ADDON_INSTANCE_STRUCT m_ifc {}
Detailed Description
Interface from Kodi to a PVR add-on.
Also translates Kodi's C++ structures to the add-on's C structures.
Member Typedef Documentation
AddonInstance
typedef AddonInstance_PVR PVR::CPVRClient::AddonInstance private
Wraps an addon function call in order to do common pre and post function invocation actions.
Parameters
strFunctionName The function name, for logging purposes.
function The function to wrap. It has to have return type PVR_ERROR and must take one parameter of type const AddonInstance*.
bIsImplemented If false, this method will return PVR_ERROR_NOT_IMPLEMENTED.
bCheckReadyToUse If true, this method will check whether this instance is ready for use and return PVR_ERROR_SERVER_ERROR if it is not.
Returns
PVR_ERROR_NO_ERROR on success, any other PVR_ERROR_* value otherwise.
Constructor & Destructor Documentation
CPVRClient()
PVR::CPVRClient::CPVRClient (const ADDON::AddonInfoPtr & addonInfo, ADDON::AddonInstanceId instanceId, int clientId)
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_PVR::props, KODI_ADDON_INSTANCE_STRUCT::pvr, ResetProperties(), AddonInstance_PVR::toAddon, and AddonInstance_PVR::toKodi.
~CPVRClient()
PVR::CPVRClient::~CPVRClient () override
References Destroy(), ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_PVR::props, KODI_ADDON_INSTANCE_STRUCT::pvr, AddonInstance_PVR::toAddon, and AddonInstance_PVR::toKodi.
Member Function Documentation
AddTimer()
PVR_ERROR PVR::CPVRClient::AddTimer (const CPVRTimerInfoTag & timer)
Add a timer on the backend.
Parameters
timer The timer to add.
Returns
PVR_ERROR_NO_ERROR if the timer has been added successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsTimers(), and AddonInstance_PVR::toAddon.
CallChannelMenuHook()
PVR_ERROR PVR::CPVRClient::CallChannelMenuHook (const CPVRClientMenuHook & hook, const std::shared_ptr< const CPVRChannel > & channel)
Call one of the channel menu hooks of the client.
Parameters
hook The hook to call.
tag The channel associated with the hook to be called.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References PVR_MENUHOOK::category, DoAddonCall(), PVR::CPVRClientMenuHook::GetId(), PVR::CPVRClientMenuHook::GetLabelId(), PVR_MENUHOOK::iHookId, PVR_MENUHOOK::iLocalizedStringId, PVR_MENUHOOK_CHANNEL, and AddonInstance_PVR::toAddon.
CallEpgTagMenuHook()
PVR_ERROR PVR::CPVRClient::CallEpgTagMenuHook (const CPVRClientMenuHook & hook, const std::shared_ptr< const CPVREpgInfoTag > & tag)
Call one of the EPG tag menu hooks of the client.
Parameters
hook The hook to call.
tag The EPG tag associated with the hook to be called.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References PVR_MENUHOOK::category, DoAddonCall(), PVR::CPVRClientMenuHook::GetId(), PVR::CPVRClientMenuHook::GetLabelId(), PVR_MENUHOOK::iHookId, PVR_MENUHOOK::iLocalizedStringId, PVR_MENUHOOK_EPG, and AddonInstance_PVR::toAddon.
CallRecordingMenuHook()
PVR_ERROR PVR::CPVRClient::CallRecordingMenuHook (const CPVRClientMenuHook & hook, const std::shared_ptr< const CPVRRecording > & recording, bool bDeleted)
Call one of the recording menu hooks of the client.
Parameters
hook The hook to call.
tag The recording associated with the hook to be called.
bDeleted True, if the recording is deleted (trashed), false otherwise
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References PVR_MENUHOOK::category, DoAddonCall(), PVR::CPVRClientMenuHook::GetId(), PVR::CPVRClientMenuHook::GetLabelId(), PVR_MENUHOOK::iHookId, PVR_MENUHOOK::iLocalizedStringId, PVR_MENUHOOK_DELETED_RECORDING, PVR_MENUHOOK_RECORDING, and AddonInstance_PVR::toAddon.
CallSettingsMenuHook()
PVR_ERROR PVR::CPVRClient::CallSettingsMenuHook (const CPVRClientMenuHook & hook)
Call one of the settings menu hooks of the client.
Parameters
hook The hook to call.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References PVR_MENUHOOK::category, DoAddonCall(), PVR::CPVRClientMenuHook::GetId(), PVR::CPVRClientMenuHook::GetLabelId(), PVR_MENUHOOK::iHookId, PVR_MENUHOOK::iLocalizedStringId, PVR_MENUHOOK_SETTING, and AddonInstance_PVR::toAddon.
CallTimerMenuHook()
PVR_ERROR PVR::CPVRClient::CallTimerMenuHook (const CPVRClientMenuHook & hook, const std::shared_ptr< const CPVRTimerInfoTag > & timer)
Call one of the timer menu hooks of the client.
Parameters
hook The hook to call.
tag The timer associated with the hook to be called.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References PVR_MENUHOOK::category, DoAddonCall(), PVR::CPVRClientMenuHook::GetId(), PVR::CPVRClientMenuHook::GetLabelId(), PVR_MENUHOOK::iHookId, PVR_MENUHOOK::iLocalizedStringId, PVR_MENUHOOK_TIMER, and AddonInstance_PVR::toAddon.
CanPauseStream()
PVR_ERROR PVR::CPVRClient::CanPauseStream (bool & bCanPause) const
Check whether PVR backend supports pausing the currently playing stream.
Parameters
bCanPause True if the stream can be paused, false otherwise.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
CanPlayChannel()
bool PVR::CPVRClient::CanPlayChannel (const std::shared_ptr< const CPVRChannel > & channel) const private
Whether a channel can be played by this add-on.
Parameters
channel The channel to check.
Returns
True when it can be played, false otherwise.
References m_bReadyToUse, m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRadio(), and PVR::CPVRClientCapabilities::SupportsTV().
Referenced by GetChannelStreamProperties(), and OpenLiveStream().
CanSeekStream()
PVR_ERROR PVR::CPVRClient::CanSeekStream (bool & bCanSeek) const
Check whether PVR backend supports seeking for the currently playing stream.
Parameters
bCanSeek True if the stream can be seeked, false otherwise.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
cb_add_menu_hook()
void PVR::CPVRClient::cb_add_menu_hook (void * kodiInstance, const PVR_MENUHOOK * hook) static private
Add or replace a menu hook for the context menu for this add-on.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
hook The hook to add.
References GetMenuHooks(), HandleAddonCallback(), and LOGERROR.
Referenced by ResetProperties().
cb_allocate_demux_packet()
DEMUX_PACKET * PVR::CPVRClient::cb_allocate_demux_packet (void * kodiInstance, int iDataSize = 0) static private
Allocate a demux packet. Free with FreeDemuxPacket.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class.
iDataSize The size of the data that will go into the packet
Returns
The allocated packet.
References CDVDDemuxUtils::AllocateDemuxPacket(), and HandleAddonCallback().
Referenced by ResetProperties().
cb_connection_state_change()
void PVR::CPVRClient::cb_connection_state_change (void * kodiInstance, const char * strConnectionString, PVR_CONNECTION_STATE newState, const char * strMessage) static private
Notify a state change for a PVR backend connection.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
strConnectionString The connection string reported by the backend that can be displayed in the UI.
newState The new state.
strMessage A localized addon-defined string representing the new state, that can be displayed in the UI or NULL if the Kodi-defined default string for the new state shall be displayed.
References PVR::CPVRManager::ConnectionStateChange(), GetConnectionState(), GetID(), CServiceBroker::GetPVRManager(), HandleAddonCallback(), LOGDEBUG, LOGERROR, LOGPVR, and SetConnectionState().
Referenced by ResetProperties().
cb_epg_event_state_change()
void PVR::CPVRClient::cb_epg_event_state_change (void * kodiInstance, EPG_TAG * tag, EPG_EVENT_STATE newState) static private
Notify a state change for an EPG event.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
tag The EPG event.
newState The new state.
newState The new state. For EPG_EVENT_CREATED and EPG_EVENT_UPDATED, tag must be filled with all available event data, not just a delta. For EPG_EVENT_DELETED, it is sufficient to fill EPG_TAG.iUniqueBroadcastId
References PVR::CPVRManager::EpgContainer(), GetID(), CServiceBroker::GetPVRManager(), HandleAddonCallback(), LOGERROR, and PVR::CPVREpgContainer::UpdateFromClient().
Referenced by ResetProperties().
cb_free_demux_packet()
void PVR::CPVRClient::cb_free_demux_packet (void * kodiInstance, DEMUX_PACKET * pPacket) static private
Free a packet that was allocated with AllocateDemuxPacket.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
pPacket The packet to free.
References CDVDDemuxUtils::FreeDemuxPacket(), and HandleAddonCallback().
Referenced by ResetProperties().
cb_get_codec_by_name()
PVR_CODEC PVR::CPVRClient::cb_get_codec_by_name (const void * kodiInstance, const char * strCodecName) static private
Todo:
remove the use complete from them, or add as generl function?! Returns the ffmpeg codec id from given ffmpeg codec string name
References PVR::CCodecIds::GetCodecByName(), PVR::CCodecIds::GetInstance(), HandleAddonCallback(), and PVR_INVALID_CODEC.
Referenced by ResetProperties().
cb_recording_notification()
void PVR::CPVRClient::cb_recording_notification (void * kodiInstance, const char * strName, const char * strFileName, bool bOnOff) static private
Display a notification in Kodi that a recording started or stopped on the server.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
strName The name of the recording to display
strFileName The filename of the recording
bOnOff True when recording started, false when it stopped
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetEventLog(), GetFullClientName(), GetID(), HandleAddonCallback(), ADDON::IAddonInstanceHandler::Icon(), CGUIDialogKaiToast::Info, LOGDEBUG, LOGERROR, LOGPVR, and CGUIDialogKaiToast::QueueNotification().
Referenced by ResetProperties().
cb_transfer_channel_entry()
void PVR::CPVRClient::cb_transfer_channel_entry (void * kodiInstance, const PVR_HANDLE handle, const PVR_CHANNEL * entry) static private
Transfer a channel entry from the add-on to Kodi.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
handle The handle parameter that Kodi used when requesting the channel list
entry The entry to transfer to Kodi
References PVR_HANDLE_STRUCT::dataAddress, GetID(), HandleAddonCallback(), and LOGERROR.
Referenced by ResetProperties().
cb_transfer_channel_group()
void PVR::CPVRClient::cb_transfer_channel_group (void * kodiInstance, const PVR_HANDLE handle, const PVR_CHANNEL_GROUP * entry) static private
Callback functions from addon to kodi.
Transfer a channel group from the add-on to Kodi. The group will be created if it doesn't exist.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
handle The handle parameter that Kodi used when requesting the channel groups list
entry The entry to transfer to Kodi
References PVR_HANDLE_STRUCT::dataAddress, PVR::CPVRChannelGroups::GetGroupAll(), PVR::CPVRChannelGroups::GetGroupFactory(), GetID(), HandleAddonCallback(), LOGERROR, and PVR::CPVRChannelGroups::UpdateFromClient().
Referenced by ResetProperties().
cb_transfer_channel_group_member()
void PVR::CPVRClient::cb_transfer_channel_group_member (void * kodiInstance, const PVR_HANDLE handle, const PVR_CHANNEL_GROUP_MEMBER * entry) static private
Transfer a channel group member entry from the add-on to Kodi. The channel will be added to the group if the group can be found.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
handle The handle parameter that Kodi used when requesting the channel group members list
entry The entry to transfer to Kodi
References PVR::CPVRManager::ChannelGroups(), PVR_HANDLE_STRUCT::dataAddress, GetID(), CServiceBroker::GetPVRManager(), HandleAddonCallback(), PVR_CHANNEL_GROUP_MEMBER::iChannelUniqueId, PVR_CHANNEL_GROUP_MEMBER::iOrder, LOGERROR, and PVR_CHANNEL_GROUP_MEMBER::strGroupName.
Referenced by ResetProperties().
cb_transfer_epg_entry()
void PVR::CPVRClient::cb_transfer_epg_entry (void * kodiInstance, const PVR_HANDLE handle, const EPG_TAG * entry) static private
Transfer an EPG tag from the add-on to Kodi.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
handle The handle parameter that Kodi used when requesting the EPG data
entry The entry to transfer to Kodi
References PVR_HANDLE_STRUCT::dataAddress, GetID(), HandleAddonCallback(), LOGERROR, and PVR::CPVREpg::UpdateEntry().
Referenced by ResetProperties().
cb_transfer_provider_entry()
void PVR::CPVRClient::cb_transfer_provider_entry (void * kodiInstance, const PVR_HANDLE handle, const PVR_PROVIDER * entry) static private
Transfer a provider entry from the add-on to Kodi.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
handle The handle parameter that Kodi used when requesting the channel list
entry The entry to transfer to Kodi
References PVR_HANDLE_STRUCT::dataAddress, GetID(), LOGERROR, and PVR::CPVRProvidersContainer::UpdateFromClient().
Referenced by ResetProperties().
cb_transfer_recording_entry()
void PVR::CPVRClient::cb_transfer_recording_entry (void * kodiInstance, const PVR_HANDLE handle, const PVR_RECORDING * entry) static private
Transfer a recording entry from the add-on to Kodi.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
handle The handle parameter that Kodi used when requesting the recordings list
entry The entry to transfer to Kodi
References PVR_HANDLE_STRUCT::dataAddress, GetID(), HandleAddonCallback(), LOGERROR, and PVR::CPVRRecordings::UpdateFromClient().
Referenced by ResetProperties().
cb_transfer_timer_entry()
void PVR::CPVRClient::cb_transfer_timer_entry (void * kodiInstance, const PVR_HANDLE handle, const PVR_TIMER * entry) static private
Transfer a timer entry from the add-on to Kodi.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
handle The handle parameter that Kodi used when requesting the timers list
entry The entry to transfer to Kodi
References PVR::CPVRManager::ChannelGroups(), PVR_HANDLE_STRUCT::dataAddress, GetID(), CServiceBroker::GetPVRManager(), HandleAddonCallback(), PVR_TIMER::iClientChannelUid, LOGERROR, and PVR::CPVRTimersContainer::UpdateFromClient().
Referenced by ResetProperties().
cb_trigger_channel_groups_update()
void PVR::CPVRClient::cb_trigger_channel_groups_update (void * kodiInstance) static private
Request Kodi to update it's list of channel groups.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
References GetID(), CServiceBroker::GetPVRManager(), HandleAddonCallback(), and PVR::CPVRManager::TriggerChannelGroupsUpdate().
Referenced by ResetProperties().
cb_trigger_channel_update()
void PVR::CPVRClient::cb_trigger_channel_update (void * kodiInstance) static private
Request Kodi to update it's list of channels.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
References GetID(), CServiceBroker::GetPVRManager(), HandleAddonCallback(), and PVR::CPVRManager::TriggerChannelsUpdate().
Referenced by ResetProperties().
cb_trigger_epg_update()
void PVR::CPVRClient::cb_trigger_epg_update (void * kodiInstance, unsigned int iChannelUid) static private
Schedule an EPG update for the given channel channel.
Parameters
kodiInstance A pointer to the add-on
iChannelUid The unique id of the channel for this add-on
References PVR::CPVRManager::EpgContainer(), GetID(), CServiceBroker::GetPVRManager(), HandleAddonCallback(), and PVR::CPVREpgContainer::UpdateRequest().
Referenced by ResetProperties().
cb_trigger_provider_update()
void PVR::CPVRClient::cb_trigger_provider_update (void * kodiInstance) static private
Request Kodi to update it's list of providers.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
References GetID(), CServiceBroker::GetPVRManager(), HandleAddonCallback(), and PVR::CPVRManager::TriggerProvidersUpdate().
Referenced by ResetProperties().
cb_trigger_recording_update()
void PVR::CPVRClient::cb_trigger_recording_update (void * kodiInstance) static private
Request Kodi to update it's list of recordings.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
References GetID(), CServiceBroker::GetPVRManager(), HandleAddonCallback(), and PVR::CPVRManager::TriggerRecordingsUpdate().
Referenced by ResetProperties().
cb_trigger_timer_update()
void PVR::CPVRClient::cb_trigger_timer_update (void * kodiInstance) static private
Request Kodi to update it's list of timers.
Parameters
kodiInstance Pointer to Kodi's CPVRClient class
References GetID(), CServiceBroker::GetPVRManager(), HandleAddonCallback(), and PVR::CPVRManager::TriggerTimersUpdate().
Referenced by ResetProperties().
CloseLiveStream()
PVR_ERROR PVR::CPVRClient::CloseLiveStream ()
Close an open live stream.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
Referenced by OpenLiveStream().
CloseRecordedStream()
PVR_ERROR PVR::CPVRClient::CloseRecordedStream (int64_t streamId)
Close an open recording stream.
Parameters
streamId The id of the stream to close, as returned by OpenRecordedStream.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
Referenced by OpenRecordedStream().
Continue()
void PVR::CPVRClient::Continue ()
Continue this add-on instance. Client add-on access is okay again after this call.
References m_bBlockAddonCalls.
Create()
ADDON_STATUS PVR::CPVRClient::Create ()
Initialise the instance of this add-on.
References ADDON_STATUS_OK, ADDON::IAddonInstanceHandler::CreateInstance(), GetAddonProperties(), GetConnectionState(), GetID(), ADDON::IAddonInstanceHandler::ID(), IgnoreClient(), ADDON::IAddonInstanceHandler::InstanceId(), LOGDEBUG, LOGERROR, LOGPVR, m_bReadyToUse, m_iClientId, and ResetProperties().
Referenced by ReCreate().
DeleteAllRecordingsFromTrash()
PVR_ERROR PVR::CPVRClient::DeleteAllRecordingsFromTrash ()
Delete all recordings permanent which in the deleted folder on the backend.
Returns
PVR_ERROR_NO_ERROR if the recordings has been deleted successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordingsUndelete(), and AddonInstance_PVR::toAddon.
DeleteChannel()
PVR_ERROR PVR::CPVRClient::DeleteChannel (const std::shared_ptr< const CPVRChannel > & channel)
Request the client to delete given channel.
Parameters
channel The channel to delete
Returns
PVR_ERROR_NO_ERROR if the delete has been fetched successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsChannelSettings(), and AddonInstance_PVR::toAddon.
DeleteRecording()
PVR_ERROR PVR::CPVRClient::DeleteRecording (const CPVRRecording & recording)
Delete a recording on the backend.
Parameters
recording The recording to delete.
Returns
PVR_ERROR_NO_ERROR if the recording has been deleted successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordings(), PVR::CPVRClientCapabilities::SupportsRecordingsDelete(), and AddonInstance_PVR::toAddon.
DeleteTimer()
PVR_ERROR PVR::CPVRClient::DeleteTimer (const CPVRTimerInfoTag & timer, bool bForce = false)
Delete a timer on the backend.
Parameters
timer The timer to delete.
bForce Set to true to delete a timer that is currently recording a program.
Returns
PVR_ERROR_NO_ERROR if the timer has been deleted successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsTimers(), and AddonInstance_PVR::toAddon.
DemuxAbort()
PVR_ERROR PVR::CPVRClient::DemuxAbort ()
Abort the demultiplexer thread in the add-on.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR::CPVRClientCapabilities::HandlesDemuxing(), m_clientCapabilities, PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
DemuxFlush()
PVR_ERROR PVR::CPVRClient::DemuxFlush ()
Flush all data that's currently in the demultiplexer buffer in the add-on.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR::CPVRClientCapabilities::HandlesDemuxing(), m_clientCapabilities, PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
DemuxRead()
PVR_ERROR PVR::CPVRClient::DemuxRead (DemuxPacket *& packet)
Read a packet from the demultiplexer.
Parameters
packet The packet read.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References KodiToAddonFuncTable_PVR::DemuxRead(), DoAddonCall(), PVR::CPVRClientCapabilities::HandlesDemuxing(), m_clientCapabilities, PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, and AddonInstance_PVR::toAddon.
DemuxReset()
PVR_ERROR PVR::CPVRClient::DemuxReset ()
Reset the demultiplexer in the add-on.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR::CPVRClientCapabilities::HandlesDemuxing(), m_clientCapabilities, PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
Destroy()
void PVR::CPVRClient::Destroy ()
Destroy the instance of this add-on.
References ADDON::IAddonInstanceHandler::DestroyInstance(), GetID(), LOGDEBUG, LOGPVR, m_allAddonCallsFinished, m_bBlockAddonCalls, m_bReadyToUse, m_menuhooks, ResetProperties(), and CEvent::Wait().
Referenced by ReCreate(), and ~CPVRClient().
DoAddonCall()
PVR_ERROR PVR::CPVRClient::DoAddonCall (const char * strFunctionName, const std::function< PVR_ERROR(const AddonInstance *)> & function, bool bIsImplemented = true, bool bCheckReadyToUse = true) const private
References GetID(), IgnoreClient(), CLog::Log(), LOGERROR, LOGWARNING, m_allAddonCallsFinished, m_bBlockAddonCalls, m_iAddonCalls, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::pvr, PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, PVR_ERROR_SERVER_ERROR, ReadyToUse(), CEvent::Reset(), CEvent::Set(), and ToString().
Referenced by AddTimer(), CallChannelMenuHook(), CallEpgTagMenuHook(), CallRecordingMenuHook(), CallSettingsMenuHook(), CallTimerMenuHook(), CanPauseStream(), CanSeekStream(), CloseLiveStream(), CloseRecordedStream(), DeleteAllRecordingsFromTrash(), DeleteChannel(), DeleteRecording(), DeleteTimer(), DemuxAbort(), DemuxFlush(), DemuxRead(), DemuxReset(), FillBuffer(), GetAddonNameStringProperties(), GetAddonProperties(), GetChannelGroupMembers(), GetChannelGroups(), GetChannelGroupsAmount(), GetChannels(), GetChannelsAmount(), GetChannelStreamProperties(), GetDescrambleInfo(), GetDriveSpace(), GetEPGForChannel(), GetEpgTagEdl(), GetEpgTagStreamProperties(), GetLiveStreamLength(), GetProviders(), GetProvidersAmount(), GetRecordedStreamLength(), GetRecordedStreamTimes(), GetRecordingEdl(), GetRecordingLastPlayedPosition(), GetRecordings(), GetRecordingsAmount(), GetRecordingSize(), GetRecordingStreamProperties(), GetStreamProperties(), GetStreamReadChunkSize(), GetStreamTimes(), GetTimers(), GetTimersAmount(), IsPlayable(), IsRealTimeStream(), IsRecordable(), IsRecordedStreamRealTime(), OnPowerSavingActivated(), OnPowerSavingDeactivated(), OnSystemSleep(), OnSystemWake(), OpenDialogChannelAdd(), OpenDialogChannelSettings(), OpenLiveStream(), OpenRecordedStream(), PauseRecordedStream(), PauseStream(), ReadLiveStream(), ReadRecordedStream(), RenameChannel(), RenameRecording(), SeekLiveStream(), SeekRecordedStream(), SeekTime(), SetEPGMaxFutureDays(), SetEPGMaxPastDays(), SetRecordingLastPlayedPosition(), SetRecordingLifetime(), SetRecordingPlayCount(), SetSpeed(), SignalQuality(), StartChannelScan(), StreamClosed(), UndeleteRecording(), UpdateTimer(), and UpdateTimerTypes().
FillBuffer()
PVR_ERROR PVR::CPVRClient::FillBuffer (bool mode)
Notify the pvr addon/demuxer that Kodi wishes to fill demux queue.
Parameters
mode for setting on/off
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
Remarks
Optional, and only used if addon has its own demuxer.
References DoAddonCall(), PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
GetAddonNameStringProperties()
bool PVR::CPVRClient::GetAddonNameStringProperties () private
reads the client's name string properties
Returns
True on success, false otherwise.
References DoAddonCall(), m_critSection, m_strBackendHostname, m_strBackendName, m_strBackendVersion, m_strConnectionString, PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, and AddonInstance_PVR::toAddon.
Referenced by GetAddonProperties(), and SetConnectionState().
GetAddonProperties()
bool PVR::CPVRClient::GetAddonProperties () private
reads the client's properties.
Returns
True on success, false otherwise.
References DoAddonCall(), GetAddonNameStringProperties(), m_clientCapabilities, m_critSection, PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
Referenced by Create(), and SetConnectionState().
GetBackendHostname()
const std::string & PVR::CPVRClient::GetBackendHostname () const
the ip address or alias of the pvr backend server
References m_strBackendHostname.
GetBackendName()
const std::string & PVR::CPVRClient::GetBackendName () const
Returns
The name reported by the backend.
References m_strBackendName.
GetBackendVersion()
const std::string & PVR::CPVRClient::GetBackendVersion () const
Returns
The version string reported by the backend.
References m_strBackendVersion.
GetChannelGroupMembers()
PVR_ERROR PVR::CPVRClient::GetChannelGroupMembers (CPVRChannelGroup * group, std::vector< std::shared_ptr< CPVRChannelGroupMember > > & groupMembers) const
Request the list of all group members from the backend.
Parameters
group The group to get the members for.
groupMembers The container for the group members.
Returns
PVR_ERROR_NO_ERROR if the list has been fetched successfully.
References PVR_HANDLE_STRUCT::callerAddress, PVR_HANDLE_STRUCT::dataAddress, DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsChannelGroups(), PVR::CPVRClientCapabilities::SupportsRadio(), PVR::CPVRClientCapabilities::SupportsTV(), and AddonInstance_PVR::toAddon.
GetChannelGroups()
PVR_ERROR PVR::CPVRClient::GetChannelGroups (CPVRChannelGroups * groups) const
Request the list of all channel groups from the backend.
Parameters
groups The groups container to get the groups for.
Returns
PVR_ERROR_NO_ERROR if the list has been fetched successfully.
References PVR_HANDLE_STRUCT::callerAddress, PVR_HANDLE_STRUCT::dataAddress, DoAddonCall(), PVR::CPVRChannelGroups::IsRadio(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsChannelGroups(), PVR::CPVRClientCapabilities::SupportsRadio(), PVR::CPVRClientCapabilities::SupportsTV(), and AddonInstance_PVR::toAddon.
GetChannelGroupsAmount()
PVR_ERROR PVR::CPVRClient::GetChannelGroupsAmount (int & iGroups) const
Get the total amount of channel groups from the backend.
Parameters
iGroups The total amount of channel groups on the server or -1 on error.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsChannelGroups(), and AddonInstance_PVR::toAddon.
GetChannels()
PVR_ERROR PVR::CPVRClient::GetChannels (bool bRadio, std::vector< std::shared_ptr< CPVRChannel > > & channels) const
Request the list of all channels from the backend.
Parameters
bRadio True to get the radio channels, false to get the TV channels.
channels The container for the channels.
Returns
PVR_ERROR_NO_ERROR if the list has been fetched successfully.
References PVR_HANDLE_STRUCT::callerAddress, PVR_HANDLE_STRUCT::dataAddress, DoAddonCall(), GetDateTimeFirstChannelsAdded(), CDateTime::GetUTCDateTime(), m_clientCapabilities, PVR_ERROR_NO_ERROR, SetDateTimeFirstChannelsAdded(), PVR::CPVRClientCapabilities::SupportsRadio(), PVR::CPVRClientCapabilities::SupportsTV(), and AddonInstance_PVR::toAddon.
GetChannelsAmount()
PVR_ERROR PVR::CPVRClient::GetChannelsAmount (int & iChannels) const
Get the total amount of channels from the backend.
Parameters
iChannels The total amount of channels on the server or -1 on error.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), and AddonInstance_PVR::toAddon.
GetChannelStreamProperties()
PVR_ERROR PVR::CPVRClient::GetChannelStreamProperties (const std::shared_ptr< const CPVRChannel > & channel, PVR_SOURCE source, CPVRStreamProperties & props) const
Fill the given container with the properties required for playback of the given channel. Values are obtained from the PVR backend.
Parameters
channel The channel.
source PVR_SOURCE_EPG_AS_LIVE if this call resulted from PVR_STREAM_PROPERTY_EPGPLAYBACKASLIVE being set from GetEPGTagStreamProperties(), DEFAULT otherwise.
props The container to be filled with the stream properties.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References CanPlayChannel(), DoAddonCall(), PVR_ERROR_NO_ERROR, AddonInstance_PVR::toAddon, and WriteStreamProperties().
GetClientCapabilities()
const CPVRClientCapabilities & PVR::CPVRClient::GetClientCapabilities () const inline
Query this add-on's capabilities.
Returns
The add-on's capabilities.
References m_clientCapabilities.
Referenced by PVR::CPVRRecording::Update(), and PVR::CPVRRecording::UpdateMetadata().
GetClientName()
std::string PVR::CPVRClient::GetClientName () const
The name of the PVR client, as specified by the addon developer.
Returns
string that can be used in log messages and the GUI.
References ADDON::IAddonInstanceHandler::Name().
GetConnectionState()
PVR_CONNECTION_STATE PVR::CPVRClient::GetConnectionState () const
Gets the backend connection state.
Returns
the backend connection state.
References m_connectionState, and m_critSection.
Referenced by cb_connection_state_change(), and Create().
GetConnectionString()
const std::string & PVR::CPVRClient::GetConnectionString () const
Returns
The connection string reported by the backend.
References m_strConnectionString.
GetDateTimeFirstChannelsAdded()
const CDateTime & PVR::CPVRClient::GetDateTimeFirstChannelsAdded () const
Get the date and time first channels were added for this client.
Returns
The date and time first channels were added.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), m_critSection, m_firstChannelsAdded, m_iClientId, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by GetChannels(), and PVR::CPVRDatabase::Persist().
GetDescrambleInfo()
PVR_ERROR PVR::CPVRClient::GetDescrambleInfo (int channelUid, CPVRDescrambleInfo & descrambleinfo) const
Get the descramble information of the stream that's currently open.
Parameters
channelUid Channel unique identifier
descrambleinfo The descramble information.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), m_clientCapabilities, PVR_ERROR_NO_ERROR, PVR::CPVRClientCapabilities::SupportsDescrambleInfo(), and AddonInstance_PVR::toAddon.
GetDriveSpace()
PVR_ERROR PVR::CPVRClient::GetDriveSpace (uint64_t & iTotal, uint64_t & iUsed) const
Get the disk space reported by the server.
Parameters
iTotal The total disk space.
iUsed The used disk space.
Returns
PVR_ERROR_NO_ERROR if the drive space has been fetched successfully.
References DoAddonCall(), PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
GetEPGForChannel()
PVR_ERROR PVR::CPVRClient::GetEPGForChannel (int iChannelUid, CPVREpg * epg, time_t start, time_t end) const
Request an EPG table for a channel from the client.
Parameters
iChannelUid The UID of the channel to get the EPG table for.
epg The table to write the data to.
start The start time to use.
end The end time to use.
Returns
PVR_ERROR_NO_ERROR if the table has been fetched successfully.
References PVR_HANDLE_STRUCT::callerAddress, PVR_HANDLE_STRUCT::dataAddress, DoAddonCall(), end(), CServiceBroker::GetSettingsComponent(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsEPG(), and AddonInstance_PVR::toAddon.
GetEpgTagEdl()
PVR_ERROR PVR::CPVRClient::GetEpgTagEdl (const std::shared_ptr< const CPVREpgInfoTag > & epgTag, std::vector< EDL::Edit > & edls) const
Retrieve the edit decision list (EDL) from the backend.
Parameters
epgTag The EPG tag.
edls The edit decision list (empty on error).
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), m_clientCapabilities, PVR_ERROR_NO_ERROR, PVR::CPVRClientCapabilities::SupportsEpgTagEdl(), and AddonInstance_PVR::toAddon.
GetEpgTagStreamProperties()
PVR_ERROR PVR::CPVRClient::GetEpgTagStreamProperties (const std::shared_ptr< const CPVREpgInfoTag > & tag, CPVRStreamProperties & props) const
Fill the given container with the properties required for playback of the given EPG tag. Values are obtained from the PVR backend.
Parameters
tag The EPG tag.
props The container to be filled with the stream properties.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, AddonInstance_PVR::toAddon, and WriteStreamProperties().
GetFullClientName()
std::string PVR::CPVRClient::GetFullClientName () const
A name used to uniquely identify the client, inclusing addon name and instance name, if multiple instances are supported by the client implementation.
Returns
string that can be used in log messages and the GUI.
References ADDON::IAddonInstanceHandler::Addon(), ADDON::ADDON_SETTING_INSTANCE_NAME_VALUE, ADDON::IAddonInstanceHandler::InstanceId(), and ADDON::IAddonInstanceHandler::Name().
Referenced by cb_recording_notification(), and PVR::CPVRClients::ConnectionStateChange().
GetID()
int PVR::CPVRClient::GetID () const
Returns
The ID of this instance.
References m_iClientId.
Referenced by cb_connection_state_change(), cb_epg_event_state_change(), cb_recording_notification(), cb_transfer_channel_entry(), cb_transfer_channel_group(), cb_transfer_channel_group_member(), cb_transfer_epg_entry(), cb_transfer_provider_entry(), cb_transfer_recording_entry(), cb_transfer_timer_entry(), cb_trigger_channel_groups_update(), cb_trigger_channel_update(), cb_trigger_epg_update(), cb_trigger_provider_update(), cb_trigger_recording_update(), cb_trigger_timer_update(), Create(), PVR::CPVRDatabase::Delete(), Destroy(), DoAddonCall(), PVR::CPVRDatabase::GetDateTimeFirstChannelsAdded(), PVR::CPVRDatabase::GetPriority(), OpenLiveStream(), PVR::CPVRDatabase::Persist(), and UpdateTimerTypes().
GetInstanceName()
std::string PVR::CPVRClient::GetInstanceName () const
The name of the PVR client addon instance, as specified by the user in the addon settings. Empty if addon does not support multiple instances.
Returns
string that can be used in log messages and the GUI.
References ADDON::IAddonInstanceHandler::Addon(), ADDON::ADDON_SETTING_INSTANCE_NAME_VALUE, and ADDON::IAddonInstanceHandler::InstanceId().
GetLiveStreamLength()
PVR_ERROR PVR::CPVRClient::GetLiveStreamLength (int64_t & iLength) const
Get the length of the currently playing live stream, if any.
Parameters
iLength The total length of the stream that's currently being read or -1 on error.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, and AddonInstance_PVR::toAddon.
GetMenuHooks()
std::shared_ptr< CPVRClientMenuHooks > PVR::CPVRClient::GetMenuHooks () const
Get the client's menu hooks.
Returns
The hooks. Guaranteed never to be nullptr.
References ADDON::IAddonInstanceHandler::ID(), and m_menuhooks.
Referenced by cb_add_menu_hook().
GetPreviousConnectionState()
PVR_CONNECTION_STATE PVR::CPVRClient::GetPreviousConnectionState () const
Gets the backend's previous connection state.
Returns
the backend's previous connection state.
References m_critSection, and m_prevConnectionState.
Referenced by PVR::CPVRClients::ConnectionStateChange().
GetPriority()
int PVR::CPVRClient::GetPriority () const
Get the priority of this client. Larger value means higher priority.
Returns
The priority.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), m_critSection, m_iClientId, m_priority, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by PVR::CPVRDatabase::Persist().
GetProviders()
PVR_ERROR PVR::CPVRClient::GetProviders (CPVRProvidersContainer & providers) const
Request the list of all providers from the backend.
Parameters
providers The providers list to add the providers to.
Returns
PVR_ERROR_NO_ERROR if the list has been fetched successfully.
References PVR_HANDLE_STRUCT::callerAddress, PVR_HANDLE_STRUCT::dataAddress, DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsProviders(), and AddonInstance_PVR::toAddon.
GetProvidersAmount()
PVR_ERROR PVR::CPVRClient::GetProvidersAmount (int & iProviders) const
Get the total amount of providers from the backend.
Parameters
iChannels The total amount of channels on the server or -1 on error.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), and AddonInstance_PVR::toAddon.
GetRecordedStreamLength()
PVR_ERROR PVR::CPVRClient::GetRecordedStreamLength (int64_t streamId, int64_t & iLength) const
Get the length of the given stream.
Parameters
streamId The id of the stream to get the length for, as returned by OpenRecordedStream.
iLength The total length of the stream that's currently being read or -1 on error.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, and AddonInstance_PVR::toAddon.
GetRecordedStreamTimes()
PVR_ERROR PVR::CPVRClient::GetRecordedStreamTimes (int64_t streamId, PVR_STREAM_TIMES * times) const
Get stream times for the given stream.
Parameters
streamId The id of the stream to get times for, as returned by OpenRecordedStream.
times The stream times.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), GetStreamTimes(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsMultipleRecordedStreams(), and AddonInstance_PVR::toAddon.
GetRecordingEdl()
PVR_ERROR PVR::CPVRClient::GetRecordingEdl (const CPVRRecording & recording, std::vector< EDL::Edit > & edls) const
Retrieve the edit decision list (EDL) from the backend.
Parameters
recording The recording.
edls The edit decision list (empty on error).
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), m_clientCapabilities, PVR_ERROR_NO_ERROR, PVR::CPVRClientCapabilities::SupportsRecordingsEdl(), and AddonInstance_PVR::toAddon.
GetRecordingLastPlayedPosition()
PVR_ERROR PVR::CPVRClient::GetRecordingLastPlayedPosition (const CPVRRecording & recording, int & iPosition) const
Retrieve the last watched position of a recording on the backend.
Parameters
recording The recording.
iPosition The last watched position in seconds or -1 on error
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordingsLastPlayedPosition(), and AddonInstance_PVR::toAddon.
GetRecordings()
PVR_ERROR PVR::CPVRClient::GetRecordings (CPVRRecordings * results, bool deleted) const
Request the list of all recordings from the backend.
Parameters
results The container to add the recordings to.
deleted True to return deleted recordings.
Returns
PVR_ERROR_NO_ERROR if the list has been fetched successfully.
References PVR_HANDLE_STRUCT::callerAddress, PVR_HANDLE_STRUCT::dataAddress, DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordings(), PVR::CPVRClientCapabilities::SupportsRecordingsUndelete(), and AddonInstance_PVR::toAddon.
GetRecordingsAmount()
PVR_ERROR PVR::CPVRClient::GetRecordingsAmount (bool deleted, int & iRecordings) const
Get the total amount of recordings from the backend.
Parameters
deleted True to return deleted recordings.
iRecordings The total amount of recordings on the server or -1 on error.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordings(), PVR::CPVRClientCapabilities::SupportsRecordingsUndelete(), and AddonInstance_PVR::toAddon.
GetRecordingSize()
PVR_ERROR PVR::CPVRClient::GetRecordingSize (const CPVRRecording & recording, int64_t & sizeInBytes) const
Retrieve the size of a recording on the backend.
Parameters
recording The recording.
sizeInBytes The size in bytes
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordingsSize(), and AddonInstance_PVR::toAddon.
GetRecordingStreamProperties()
PVR_ERROR PVR::CPVRClient::GetRecordingStreamProperties (const std::shared_ptr< const CPVRRecording > & recording, CPVRStreamProperties & props) const
Fill the given container with the properties required for playback of the given recording. Values are obtained from the PVR backend.
Parameters
recording The recording.
props The container to be filled with the stream properties.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), m_clientCapabilities, PVR_ERROR_NO_ERROR, PVR::CPVRClientCapabilities::SupportsRecordings(), AddonInstance_PVR::toAddon, and WriteStreamProperties().
GetStreamProperties()
PVR_ERROR PVR::CPVRClient::GetStreamProperties (PVR_STREAM_PROPERTIES * pProperties) const
Get the stream properties of the stream that's currently being read.
Parameters
pProperties The properties.
Returns
PVR_ERROR_NO_ERROR if the properties have been fetched successfully.
References DoAddonCall(), and AddonInstance_PVR::toAddon.
GetStreamReadChunkSize()
PVR_ERROR PVR::CPVRClient::GetStreamReadChunkSize (int & iChunkSize) const
Obtain the chunk size to use when reading streams.
Parameters
iChunkSize the chunk size in bytes.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR::CPVRClientCapabilities::HandlesInputStream(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordings(), and AddonInstance_PVR::toAddon.
GetStreamTimes()
PVR_ERROR PVR::CPVRClient::GetStreamTimes (PVR_STREAM_TIMES * times) const
Get Stream times for the currently playing stream, if any (will be moved to inputstream).
Parameters
times The stream times.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), and AddonInstance_PVR::toAddon.
Referenced by GetRecordedStreamTimes().
GetTimers()
PVR_ERROR PVR::CPVRClient::GetTimers (CPVRTimersContainer * results) const
Request the list of all timers from the backend.
Parameters
results The container to store the result in.
Returns
PVR_ERROR_NO_ERROR if the list has been fetched successfully.
References PVR_HANDLE_STRUCT::callerAddress, PVR_HANDLE_STRUCT::dataAddress, DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsTimers(), and AddonInstance_PVR::toAddon.
GetTimersAmount()
PVR_ERROR PVR::CPVRClient::GetTimersAmount (int & iTimers) const
Get the total amount of timers from the backend.
Parameters
iTimers The total amount of timers on the backend or -1 on error.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsTimers(), and AddonInstance_PVR::toAddon.
GetTimerTypes()
const std::vector< std::shared_ptr< CPVRTimerType > > & PVR::CPVRClient::GetTimerTypes () const
Get the timer types supported by the backend, without updating them from the backend.
Returns
the types.
References m_critSection, and m_timertypes.
HandleAddonCallback()
void PVR::CPVRClient::HandleAddonCallback (const char * strFunctionName, void * kodiInstance, const std::function< void(CPVRClient *client)> & function, bool bForceCall = false) static private
Wraps an addon callback function call in order to do common pre and post function invocation actions.
Parameters
strFunctionName The function name, for logging purposes.
kodiInstance The addon instance pointer.
function The function to wrap. It must take one parameter of type CPVRClient*.
bForceCall If true, make the call, ignoring client's state.
References ADDON::IAddonInstanceHandler::ID(), CLog::Log(), LOGERROR, LOGPVR, LOGWARNING, m_bBlockAddonCalls, and m_iAddonCalls.
Referenced by cb_add_menu_hook(), cb_allocate_demux_packet(), cb_connection_state_change(), cb_epg_event_state_change(), cb_free_demux_packet(), cb_get_codec_by_name(), cb_recording_notification(), cb_transfer_channel_entry(), cb_transfer_channel_group(), cb_transfer_channel_group_member(), cb_transfer_epg_entry(), cb_transfer_recording_entry(), cb_transfer_timer_entry(), cb_trigger_channel_groups_update(), cb_trigger_channel_update(), cb_trigger_epg_update(), cb_trigger_provider_update(), cb_trigger_recording_update(), and cb_trigger_timer_update().
IgnoreClient()
bool PVR::CPVRClient::IgnoreClient () const
Check whether this client should be ignored.
Returns
True if this client should be ignored, false otherwise.
References m_critSection, and m_ignoreClient.
Referenced by Create(), and DoAddonCall().
IsEnabled()
bool PVR::CPVRClient::IsEnabled () const
Check whether this client is enabled, according to its instance/add-on configuration.
Returns
True if this client is enabled, false otherwise.
References ADDON::IAddonInstanceHandler::Addon(), ADDON::ADDON_SETTING_INSTANCE_ENABLED_VALUE, ADDON::ADDON_SINGLETON_INSTANCE_ID, CServiceBroker::GetAddonMgr(), ADDON::IAddonInstanceHandler::ID(), ADDON::IAddonInstanceHandler::InstanceId(), and ADDON::CAddonMgr::IsAddonDisabled().
IsPlayable()
PVR_ERROR PVR::CPVRClient::IsPlayable (const std::shared_ptr< const CPVREpgInfoTag > & tag, bool & bIsPlayable) const
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsEPG(), and AddonInstance_PVR::toAddon.
IsRealTimeStream()
PVR_ERROR PVR::CPVRClient::IsRealTimeStream (bool & bRealTime) const
Check whether the currently playing stream, if any, is a real-time stream.
Parameters
bRealTime True if real-time, false otherwise.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
Referenced by IsRecordedStreamRealTime().
IsRecordable()
PVR_ERROR PVR::CPVRClient::IsRecordable (const std::shared_ptr< const CPVREpgInfoTag > & tag, bool & bIsRecordable) const
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsEPG(), PVR::CPVRClientCapabilities::SupportsRecordings(), and AddonInstance_PVR::toAddon.
IsRecordedStreamRealTime()
PVR_ERROR PVR::CPVRClient::IsRecordedStreamRealTime (int64_t streamId, bool & isRealTime) const
Check whether the given stream is a real-time stream.
Parameters
streamId The id of the stream to check, as returned by OpenRecordedStream.
isRealTime True if real-time, false otherwise.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), IsRealTimeStream(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsMultipleRecordedStreams(), and AddonInstance_PVR::toAddon.
OnPowerSavingActivated()
PVR_ERROR PVR::CPVRClient::OnPowerSavingActivated ()
References DoAddonCall(), and AddonInstance_PVR::toAddon.
OnPowerSavingDeactivated()
PVR_ERROR PVR::CPVRClient::OnPowerSavingDeactivated ()
References DoAddonCall(), and AddonInstance_PVR::toAddon.
OnPreInstall()
void PVR::CPVRClient::OnPreInstall () override virtual
Reimplemented from ADDON::IAddonInstanceHandler.
References StopRunningInstance().
OnPreUnInstall()
void PVR::CPVRClient::OnPreUnInstall () override virtual
Reimplemented from ADDON::IAddonInstanceHandler.
References StopRunningInstance().
OnSystemSleep()
PVR_ERROR PVR::CPVRClient::OnSystemSleep ()
Propagate power management events to this add-on.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), and AddonInstance_PVR::toAddon.
OnSystemWake()
PVR_ERROR PVR::CPVRClient::OnSystemWake ()
References DoAddonCall(), and AddonInstance_PVR::toAddon.
OpenDialogChannelAdd()
PVR_ERROR PVR::CPVRClient::OpenDialogChannelAdd (const std::shared_ptr< const CPVRChannel > & channel)
Request the client to open dialog about given channel to add.
Parameters
channel The channel to add
Returns
PVR_ERROR_NO_ERROR if the add has been fetched successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsChannelSettings(), and AddonInstance_PVR::toAddon.
OpenDialogChannelSettings()
PVR_ERROR PVR::CPVRClient::OpenDialogChannelSettings (const std::shared_ptr< const CPVRChannel > & channel)
Request the client to open dialog about given channel settings.
Parameters
channel The channel to edit
Returns
PVR_ERROR_NO_ERROR if the edit has been fetched successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsChannelSettings(), and AddonInstance_PVR::toAddon.
OpenLiveStream()
PVR_ERROR PVR::CPVRClient::OpenLiveStream (const std::shared_ptr< const CPVRChannel > & channel)
Open a live stream on the server.
Parameters
channel The channel to stream.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References CanPlayChannel(), CloseLiveStream(), DoAddonCall(), GetID(), LOGDEBUG, LOGPVR, PVR_ERROR_INVALID_PARAMETERS, PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, PVR_ERROR_SERVER_ERROR, and AddonInstance_PVR::toAddon.
OpenRecordedStream()
PVR_ERROR PVR::CPVRClient::OpenRecordedStream (const std::shared_ptr< const CPVRRecording > & recording, int64_t & streamId)
Open a recording on the server.
Parameters
recording The recording to open.
streamId The id of the stream opened.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References CloseRecordedStream(), DoAddonCall(), LOGDEBUG, LOGPVR, m_clientCapabilities, PVR_ERROR_INVALID_PARAMETERS, PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, PVR::CPVRClientCapabilities::SupportsMultipleRecordedStreams(), PVR::CPVRClientCapabilities::SupportsRecordings(), and AddonInstance_PVR::toAddon.
PauseRecordedStream()
PVR_ERROR PVR::CPVRClient::PauseRecordedStream (int64_t streamId, bool paused)
(Un)Pause a stream.
Parameters
streamId The id of the stream to (un)pause, as returned by OpenRecordedStream.
paused True to pause the stream, false to unpause.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), m_clientCapabilities, PauseStream(), PVR::CPVRClientCapabilities::SupportsMultipleRecordedStreams(), and AddonInstance_PVR::toAddon.
PauseStream()
PVR_ERROR PVR::CPVRClient::PauseStream (bool bPaused)
(Un)Pause a stream.
Parameters
bPaused True to pause the stream, false to unpause.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
Referenced by PauseRecordedStream().
ReadLiveStream()
PVR_ERROR PVR::CPVRClient::ReadLiveStream (void * lpBuf, int64_t uiBufSize, int & iRead)
Read from an open live stream.
Parameters
lpBuf The buffer to store the data in.
uiBufSize The amount of bytes to read.
iRead The amount of bytes that were actually read from the stream.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, and AddonInstance_PVR::toAddon.
ReadRecordedStream()
PVR_ERROR PVR::CPVRClient::ReadRecordedStream (int64_t streamId, void * lpBuf, int64_t uiBufSize, int & iRead)
Read from an open recording stream.
Parameters
streamId The id of the stream to read, as returned by OpenRecordedStream.
lpBuf The buffer to store the data in.
uiBufSize The amount of bytes to read.
iRead The amount of bytes that were actually read from the stream.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, and AddonInstance_PVR::toAddon.
ReadyToUse()
bool PVR::CPVRClient::ReadyToUse () const
Returns
True if this instance is initialised (ADDON_Create returned true), false otherwise.
References m_bReadyToUse.
Referenced by DoAddonCall().
ReCreate()
void PVR::CPVRClient::ReCreate ()
Destroy and recreate this add-on.
References Create(), and Destroy().
RenameChannel()
PVR_ERROR PVR::CPVRClient::RenameChannel (const std::shared_ptr< const CPVRChannel > & channel)
Request the client to rename given channel.
Parameters
channel The channel to rename
Returns
PVR_ERROR_NO_ERROR if the rename has been fetched successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsChannelSettings(), and AddonInstance_PVR::toAddon.
RenameRecording()
PVR_ERROR PVR::CPVRClient::RenameRecording (const CPVRRecording & recording)
Rename a recording on the backend.
Parameters
recording The recording to rename.
Returns
PVR_ERROR_NO_ERROR if the recording has been renamed successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordings(), and AddonInstance_PVR::toAddon.
ResetProperties()
void PVR::CPVRClient::ResetProperties () private
Resets all class members to their defaults, accept the client id.
References AddonToKodiFuncTable_PVR::AddMenuHook, AddonToKodiFuncTable_PVR::AllocateDemuxPacket, cb_add_menu_hook(), cb_allocate_demux_packet(), cb_connection_state_change(), cb_epg_event_state_change(), cb_free_demux_packet(), cb_get_codec_by_name(), cb_recording_notification(), cb_transfer_channel_entry(), cb_transfer_channel_group(), cb_transfer_channel_group_member(), cb_transfer_epg_entry(), cb_transfer_provider_entry(), cb_transfer_recording_entry(), cb_transfer_timer_entry(), cb_trigger_channel_groups_update(), cb_trigger_channel_update(), cb_trigger_epg_update(), cb_trigger_provider_update(), cb_trigger_recording_update(), cb_trigger_timer_update(), PVR::CPVRClientCapabilities::clear(), AddonToKodiFuncTable_PVR::ConnectionStateChange, DEFAULT_INFO_STRING_VALUE, PVR::CPVRManager::EpgContainer(), AddonToKodiFuncTable_PVR::EpgEventStateChange, AddonToKodiFuncTable_PVR::FreeDemuxPacket, AddonToKodiFuncTable_PVR::GetCodecByName, PVR::CPVREpgContainer::GetFutureDaysToDisplay(), PVR::CPVREpgContainer::GetPastDaysToDisplay(), CServiceBroker::GetPVRManager(), AddonProperties_PVR::iEpgMaxFutureDays, AddonProperties_PVR::iEpgMaxPastDays, AddonToKodiFuncTable_PVR::kodiInstance, m_allAddonCallsFinished, m_bBlockAddonCalls, m_bReadyToUse, m_clientCapabilities, m_connectionState, m_critSection, m_iAddonCalls, ADDON::IAddonInstanceHandler::m_ifc, m_ignoreClient, m_menuhooks, m_prevConnectionState, m_priority, m_strBackendHostname, m_strBackendName, m_strBackendVersion, m_strClientPath, m_strConnectionString, m_strUserPath, m_timertypes, ADDON::IAddonInstanceHandler::Path(), ADDON::IAddonInstanceHandler::Profile(), AddonInstance_PVR::props, KODI_ADDON_INSTANCE_STRUCT::pvr, PVR_CONNECTION_STATE_UNKNOWN, AddonToKodiFuncTable_PVR::RecordingNotification, CEvent::Set(), AddonProperties_PVR::strClientPath, AddonProperties_PVR::strUserPath, AddonInstance_PVR::toAddon, AddonInstance_PVR::toKodi, AddonToKodiFuncTable_PVR::TransferChannelEntry, AddonToKodiFuncTable_PVR::TransferChannelGroup, AddonToKodiFuncTable_PVR::TransferChannelGroupMember, AddonToKodiFuncTable_PVR::TransferEpgEntry, AddonToKodiFuncTable_PVR::TransferProviderEntry, AddonToKodiFuncTable_PVR::TransferRecordingEntry, AddonToKodiFuncTable_PVR::TransferTimerEntry, CSpecialProtocol::TranslatePath(), AddonToKodiFuncTable_PVR::TriggerChannelGroupsUpdate, AddonToKodiFuncTable_PVR::TriggerChannelUpdate, AddonToKodiFuncTable_PVR::TriggerEpgUpdate, AddonToKodiFuncTable_PVR::TriggerProvidersUpdate, AddonToKodiFuncTable_PVR::TriggerRecordingUpdate, and AddonToKodiFuncTable_PVR::TriggerTimerUpdate.
Referenced by CPVRClient(), Create(), and Destroy().
SeekLiveStream()
PVR_ERROR PVR::CPVRClient::SeekLiveStream (int64_t iFilePosition, int iWhence, int64_t & iPosition)
Seek in a live stream on a backend.
Parameters
iFilePosition The position to seek to.
iWhence ?
iPosition The new position or -1 on error.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, and AddonInstance_PVR::toAddon.
SeekRecordedStream()
PVR_ERROR PVR::CPVRClient::SeekRecordedStream (int64_t streamId, int64_t iFilePosition, int iWhence, int64_t & iPosition)
Seek in a recording stream on a backend.
Parameters
streamId The id of the stream to seek, as returned by OpenRecordedStream.
iFilePosition The position to seek to.
iWhence ?
iPosition The new position or -1 on error.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, and AddonInstance_PVR::toAddon.
SeekTime()
PVR_ERROR PVR::CPVRClient::SeekTime (double time, bool backwards, double * startpts)
Notify the pvr addon/demuxer that Kodi wishes to seek the stream by time.
Parameters
time The absolute time since stream start
backwards True to seek to keyframe BEFORE time, else AFTER
startpts can be updated to point to where display should start
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
Remarks
Optional, and only used if addon has its own demuxer.
References DoAddonCall(), PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, and AddonInstance_PVR::toAddon.
SetConnectionState()
void PVR::CPVRClient::SetConnectionState (PVR_CONNECTION_STATE state)
Sets the backend connection state.
Parameters
state the new backend connection state.
References GetAddonNameStringProperties(), GetAddonProperties(), LOGERROR, m_connectionState, m_critSection, m_ignoreClient, m_prevConnectionState, PVR_CONNECTION_STATE_CONNECTED, PVR_CONNECTION_STATE_CONNECTING, and PVR_CONNECTION_STATE_UNKNOWN.
Referenced by cb_connection_state_change().
SetDateTimeFirstChannelsAdded()
void PVR::CPVRClient::SetDateTimeFirstChannelsAdded (const CDateTime & dateTime)
Set the date and time first channels were added for this client.
Parameters
dateTime The date and time first channels were added.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), m_critSection, m_firstChannelsAdded, m_iClientId, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by GetChannels().
SetEPGMaxFutureDays()
PVR_ERROR PVR::CPVRClient::SetEPGMaxFutureDays (int iFutureDays)
Tell the client the future time frame to use when notifying epg events back to Kodi.
The client might push epg events asynchronously to Kodi using the callback function EpgEventStateChange. To be able to only push events that are actually of interest for Kodi, client needs to know about the future epg time frame Kodi uses.
Parameters
[in] iFutureDays number of days after "now". EPG_TIMEFRAME_UNLIMITED means that Kodi is interested in all epg events, regardless of event times.
Returns
PVR_ERROR_NO_ERROR if new value was successfully set.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsEPG(), and AddonInstance_PVR::toAddon.
SetEPGMaxPastDays()
PVR_ERROR PVR::CPVRClient::SetEPGMaxPastDays (int iPastDays)
Tell the client the past time frame to use when notifying epg events back to Kodi.
The client might push epg events asynchronously to Kodi using the callback function EpgEventStateChange. To be able to only push events that are actually of interest for Kodi, client needs to know about the past epg time frame Kodi uses.
Parameters
[in] iPastDays number of days before "now". EPG_TIMEFRAME_UNLIMITED means that Kodi is interested in all epg events, regardless of event times.
Returns
PVR_ERROR_NO_ERROR if new value was successfully set.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsEPG(), and AddonInstance_PVR::toAddon.
SetPriority()
void PVR::CPVRClient::SetPriority (int iPriority)
Set a new priority for this client.
Parameters
iPriority The new priority.
References PVR::ClientsPrioritiesInvalidated, CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), m_critSection, m_iClientId, m_priority, PVR::CPVRManager::PublishEvent(), and PVR::PVR_CLIENT_INVALID_UID.
SetRecordingLastPlayedPosition()
PVR_ERROR PVR::CPVRClient::SetRecordingLastPlayedPosition (const CPVRRecording & recording, int lastplayedposition)
Set the last watched position of a recording on the backend.
Parameters
recording The recording.
lastplayedposition The last watched position in seconds
Returns
PVR_ERROR_NO_ERROR if the position has been stored successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordingsLastPlayedPosition(), and AddonInstance_PVR::toAddon.
SetRecordingLifetime()
PVR_ERROR PVR::CPVRClient::SetRecordingLifetime (const CPVRRecording & recording)
Set the lifetime of a recording on the backend.
Parameters
recording The recording to set the lifetime for. recording.m_iLifetime contains the new lifetime value.
Returns
PVR_ERROR_NO_ERROR if the recording's lifetime has been set successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordingsLifetimeChange(), and AddonInstance_PVR::toAddon.
SetRecordingPlayCount()
PVR_ERROR PVR::CPVRClient::SetRecordingPlayCount (const CPVRRecording & recording, int count)
Set the play count of a recording on the backend.
Parameters
recording The recording to set the play count.
count Play count.
Returns
PVR_ERROR_NO_ERROR if the recording's play count has been set successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordingsPlayCount(), and AddonInstance_PVR::toAddon.
SetSpeed()
PVR_ERROR PVR::CPVRClient::SetSpeed (int speed)
Notify the pvr addon/demuxer that Kodi wishes to change playback speed.
Parameters
speed The requested playback speed
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
Remarks
Optional, and only used if addon has its own demuxer.
References DoAddonCall(), PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
SignalQuality()
PVR_ERROR PVR::CPVRClient::SignalQuality (int channelUid, CPVRSignalStatus & qualityinfo) const
Get the signal quality of the stream that's currently open.
Parameters
channelUid Channel unique identifier
qualityinfo The signal quality.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), PVR_ERROR_NO_ERROR, and AddonInstance_PVR::toAddon.
StartChannelScan()
PVR_ERROR PVR::CPVRClient::StartChannelScan ()
Start a channel scan on the server.
Returns
PVR_ERROR_NO_ERROR if the channel scan has been started successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsChannelScan(), and AddonInstance_PVR::toAddon.
Stop()
void PVR::CPVRClient::Stop ()
Stop this add-on instance. No more client add-on access after this call.
References m_bBlockAddonCalls, and m_priority.
StopRunningInstance()
void PVR::CPVRClient::StopRunningInstance () private
Stop this instance, if it is currently running.
References PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), m_iClientId, and PVR::CPVRManager::Stop().
Referenced by OnPreInstall(), and OnPreUnInstall().
StreamClosed()
PVR_ERROR PVR::CPVRClient::StreamClosed () const
A stream was closed or has ended.
Returns
PVR_ERROR_NO_ERROR on success, respective error code otherwise.
References DoAddonCall(), and AddonInstance_PVR::toAddon.
ToString()
const char * PVR::CPVRClient::ToString (const PVR_ERROR error) static
References PVR_ERROR_ALREADY_PRESENT, PVR_ERROR_FAILED, PVR_ERROR_INVALID_PARAMETERS, PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, PVR_ERROR_RECORDING_RUNNING, PVR_ERROR_REJECTED, PVR_ERROR_SERVER_ERROR, PVR_ERROR_SERVER_TIMEOUT, and PVR_ERROR_UNKNOWN.
Referenced by DoAddonCall(), PVR::CPVRGUIActionsPlayback::PlayEpgTag(), and PVR::CPVRPlaybackState::StartPlayback().
UndeleteRecording()
PVR_ERROR PVR::CPVRClient::UndeleteRecording (const CPVRRecording & recording)
Undelete a recording on the backend.
Parameters
recording The recording to undelete.
Returns
PVR_ERROR_NO_ERROR if the recording has been undeleted successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsRecordingsUndelete(), and AddonInstance_PVR::toAddon.
UpdateTimer()
PVR_ERROR PVR::CPVRClient::UpdateTimer (const CPVRTimerInfoTag & timer)
Update the timer information on the server.
Parameters
timer The timer to update.
Returns
PVR_ERROR_NO_ERROR if the timer has been updated successfully.
References DoAddonCall(), m_clientCapabilities, PVR::CPVRClientCapabilities::SupportsTimers(), and AddonInstance_PVR::toAddon.
UpdateTimerTypes()
PVR_ERROR PVR::CPVRClient::UpdateTimerTypes ()
Update all timer types supported by the backend.
Returns
PVR_ERROR_NO_ERROR if the list has been fetched successfully.
References DoAddonCall(), GetID(), PVR_TIMER_TYPE::iId, LOGERROR, LOGWARNING, m_clientCapabilities, m_critSection, m_iClientId, m_timertypes, ADDON::IAddonInstanceHandler::Name(), PVR_ERROR_NO_ERROR, PVR_ERROR_NOT_IMPLEMENTED, PVR_TIMER_TYPE_IS_MANUAL, PVR_TIMER_TYPE_IS_REPEATING, PVR_TIMER_TYPE_NONE, PVR_TIMER_TYPE_REQUIRES_EPG_TAG_ON_CREATE, PVR_TIMER_TYPE_SUPPORTS_CHANNELS, PVR_TIMER_TYPE_SUPPORTS_ENABLE_DISABLE, PVR_TIMER_TYPE_SUPPORTS_END_TIME, PVR_TIMER_TYPE_SUPPORTS_FIRST_DAY, PVR_TIMER_TYPE_SUPPORTS_LIFETIME, PVR_TIMER_TYPE_SUPPORTS_PRIORITY, PVR_TIMER_TYPE_SUPPORTS_RECORDING_FOLDERS, PVR_TIMER_TYPE_SUPPORTS_START_TIME, PVR_TIMER_TYPE_SUPPORTS_WEEKDAYS, PVR::CPVRClientCapabilities::SupportsEPG(), PVR::CPVRClientCapabilities::SupportsTimers(), and AddonInstance_PVR::toAddon.
WriteStreamProperties()
void PVR::CPVRClient::WriteStreamProperties (PVR_NAMED_VALUE ** properties, unsigned int iPropertyCount, CPVRStreamProperties & props) static private
Write the given addon properties to the given properties container.
Parameters
properties Pointer to an array of addon properties pointers.
iPropertyCount The number of properties contained in the addon properties array.
props The container the addon properties shall be written to.
Referenced by GetChannelStreamProperties(), GetEpgTagStreamProperties(), and GetRecordingStreamProperties().
Member Data Documentation
m_allAddonCallsFinished
CEvent PVR::CPVRClient::m_allAddonCallsFinished mutable private
fires after last in-progress addon call finished
Referenced by Destroy(), DoAddonCall(), and ResetProperties().
m_bBlockAddonCalls
std::atomic<bool> PVR::CPVRClient::m_bBlockAddonCalls private
true if no add-on API calls are allowed
Referenced by Continue(), Destroy(), DoAddonCall(), HandleAddonCallback(), ResetProperties(), and Stop().
m_bReadyToUse
std::atomic<bool> PVR::CPVRClient::m_bReadyToUse private
true if this add-on is initialised (ADDON_Create returned true), false otherwise
Referenced by CanPlayChannel(), Create(), Destroy(), ReadyToUse(), and ResetProperties().
m_clientCapabilities
CPVRClientCapabilities PVR::CPVRClient::m_clientCapabilities private
the cached add-on's capabilities
Referenced by AddTimer(), CanPlayChannel(), DeleteAllRecordingsFromTrash(), DeleteChannel(), DeleteRecording(), DeleteTimer(), DemuxAbort(), DemuxFlush(), DemuxRead(), DemuxReset(), GetAddonProperties(), GetChannelGroupMembers(), GetChannelGroups(), GetChannelGroupsAmount(), GetChannels(), GetClientCapabilities(), GetDescrambleInfo(), GetEPGForChannel(), GetEpgTagEdl(), GetProviders(), GetRecordedStreamTimes(), GetRecordingEdl(), GetRecordingLastPlayedPosition(), GetRecordings(), GetRecordingsAmount(), GetRecordingSize(), GetRecordingStreamProperties(), GetStreamReadChunkSize(), GetTimers(), GetTimersAmount(), IsPlayable(), IsRecordable(), IsRecordedStreamRealTime(), OpenDialogChannelAdd(), OpenDialogChannelSettings(), OpenRecordedStream(), PauseRecordedStream(), RenameChannel(), RenameRecording(), ResetProperties(), SetEPGMaxFutureDays(), SetEPGMaxPastDays(), SetRecordingLastPlayedPosition(), SetRecordingLifetime(), SetRecordingPlayCount(), StartChannelScan(), UndeleteRecording(), UpdateTimer(), and UpdateTimerTypes().
m_connectionState
PVR_CONNECTION_STATE PVR::CPVRClient::m_connectionState private
the backend connection state
Referenced by GetConnectionState(), ResetProperties(), and SetConnectionState().
m_critSection
CCriticalSection PVR::CPVRClient::m_critSection mutable private
Referenced by GetAddonNameStringProperties(), GetAddonProperties(), GetConnectionState(), GetDateTimeFirstChannelsAdded(), GetPreviousConnectionState(), GetPriority(), GetTimerTypes(), IgnoreClient(), ResetProperties(), SetConnectionState(), SetDateTimeFirstChannelsAdded(), SetPriority(), and UpdateTimerTypes().
m_firstChannelsAdded
std::optional<CDateTime> PVR::CPVRClient::m_firstChannelsAdded mutable private
date and time the first channels were added for this client
Referenced by GetDateTimeFirstChannelsAdded(), and SetDateTimeFirstChannelsAdded().
m_iAddonCalls
std::atomic<int> PVR::CPVRClient::m_iAddonCalls mutable private
number of in-progress addon calls
Referenced by DoAddonCall(), HandleAddonCallback(), and ResetProperties().
m_iClientId
const int PVR::CPVRClient::m_iClientId private
unique ID of the client
Referenced by Create(), GetDateTimeFirstChannelsAdded(), GetID(), GetPriority(), SetDateTimeFirstChannelsAdded(), SetPriority(), StopRunningInstance(), and UpdateTimerTypes().
m_ignoreClient
bool PVR::CPVRClient::m_ignoreClient private
signals to PVRManager to ignore this client until it has been connected
Referenced by IgnoreClient(), ResetProperties(), and SetConnectionState().
m_menuhooks
std::shared_ptr<CPVRClientMenuHooks> PVR::CPVRClient::m_menuhooks mutable private
the menu hooks for this add-on
Referenced by Destroy(), GetMenuHooks(), and ResetProperties().
m_prevConnectionState
PVR_CONNECTION_STATE PVR::CPVRClient::m_prevConnectionState private
the previous backend connection state
Referenced by GetPreviousConnectionState(), ResetProperties(), and SetConnectionState().
m_priority
std::optional<int> PVR::CPVRClient::m_priority mutable private
priority of the client
Referenced by GetPriority(), ResetProperties(), SetPriority(), and Stop().
m_strBackendHostname
std::string PVR::CPVRClient::m_strBackendHostname private
the cached backend hostname
Referenced by GetAddonNameStringProperties(), GetBackendHostname(), and ResetProperties().
m_strBackendName
std::string PVR::CPVRClient::m_strBackendName private
the cached backend version
Referenced by GetAddonNameStringProperties(), GetBackendName(), and ResetProperties().
m_strBackendVersion
std::string PVR::CPVRClient::m_strBackendVersion private
the cached backend version
Referenced by GetAddonNameStringProperties(), GetBackendVersion(), and ResetProperties().
m_strClientPath
std::string PVR::CPVRClient::m_strClientPath private
translated path to this add-on
Referenced by ResetProperties().
m_strConnectionString
std::string PVR::CPVRClient::m_strConnectionString private
the cached connection string
Referenced by GetAddonNameStringProperties(), GetConnectionString(), and ResetProperties().
m_strUserPath
std::string PVR::CPVRClient::m_strUserPath private
translated path to the user profile
Referenced by ResetProperties().
m_timertypes
std::vector<std::shared_ptr<CPVRTimerType> > PVR::CPVRClient::m_timertypes private
timer types supported by this backend
Referenced by GetTimerTypes(), ResetProperties(), and UpdateTimerTypes().
The documentation for this class was generated from the following files:
PVRClient.h
PVRClient.cpp