Kodi Documentation: cc_decoder708.cpp File Reference
cc_decoder708.cpp File Reference
#include "cc_decoder708.h"
#include "utils/log.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
unsigned char get_internal_from_G0 (unsigned char g0_char)
unsigned char get_internal_from_G1 (unsigned char g1_char)
unsigned char get_internal_from_G2 (unsigned char g2_char)
unsigned char get_internal_from_G3 (unsigned char g3_char)
void clearTV (cc708_service_decoder *decoder)
void clear_packet (cc708_service_decoder *decoder)
void cc708_service_reset (cc708_service_decoder *decoder)
void cc708_reset (cc708_service_decoder *decoders)
int compWindowsPriorities (const void *a, const void *b)
void printTVtoBuf (cc708_service_decoder *decoder)
void updateScreen (cc708_service_decoder *decoder)
void rollupWindow (cc708_service_decoder *decoder, int window)
int handle_708_C2 (cc708_service_decoder *decoder, unsigned char *data, int data_length)
int handle_708_C3 (cc708_service_decoder *decoder, unsigned char *data, int data_length)
int handle_708_extended_char (cc708_service_decoder *decoder, unsigned char *data, int data_length)
void process_cr (cc708_service_decoder *decoder)
int handle_708_C0 (cc708_service_decoder *decoder, unsigned char *data, int data_length)
void process_character (cc708_service_decoder *decoder, unsigned char internal_char)
int handle_708_G0 (cc708_service_decoder *decoder, unsigned char *data, int data_length)
int handle_708_G1 (cc708_service_decoder *decoder, unsigned char *data, int data_length)
void handle_708_CWx_SetCurrentWindow (cc708_service_decoder *decoder, int new_window)
void clearWindowText (e708Window *window)
void clearWindow (cc708_service_decoder *decoder, int window)
void handle_708_CLW_ClearWindows (cc708_service_decoder *decoder, int windows_bitmap)
void handle_708_DSW_DisplayWindows (cc708_service_decoder *decoder, int windows_bitmap)
void handle_708_HDW_HideWindows (cc708_service_decoder *decoder, int windows_bitmap)
void handle_708_TGW_ToggleWindows (cc708_service_decoder *decoder, int windows_bitmap)
void handle_708_DFx_DefineWindow (cc708_service_decoder *decoder, int window, unsigned char *data)
void handle_708_SWA_SetWindowAttributes (cc708_service_decoder *decoder, unsigned char *data)
void deleteWindow (cc708_service_decoder *decoder, int window)
void handle_708_DLW_DeleteWindows (cc708_service_decoder *decoder, int windows_bitmap)
void handle_708_SPA_SetPenAttributes (cc708_service_decoder *decoder, unsigned char *data)
void handle_708_SPC_SetPenColor (cc708_service_decoder *decoder, unsigned char *data)
void handle_708_SPL_SetPenLocation (cc708_service_decoder *decoder, unsigned char *data)
void handle_708_DLY_Delay (cc708_service_decoder *decoder, int tenths_of_sec)
void handle_708_DLC_DelayCancel (cc708_service_decoder *decoder)
int handle_708_C1 (cc708_service_decoder *decoder, unsigned char *data, int data_length)
void process_service_block (cc708_service_decoder *decoder, unsigned char *data, int data_length)
bool check_current_packet_complete (cc708_service_decoder *decoders)
void process_current_packet (cc708_service_decoder *decoders)
void decode_708 (const unsigned char *data, int datalength, cc708_service_decoder *decoders)
void ccx_decoders_708_init (cc708_service_decoder *decoders, void(*handler)(int service, void *userdata), void *userdata, CDecoderCC708 *parent)
Variables
const char * COMMANDS_C0 [32]
struct S_COMMANDS_C1 COMMANDS_C1 [32]
Function Documentation
cc708_reset()
void cc708_reset (cc708_service_decoder * decoders)
References cc708_service_reset(), CCX_DECODERS_708_MAX_SERVICES, clear_packet(), CDecoderCC708::m_last_seq, and cc708_service_decoder::parent.
Referenced by process_current_packet().
cc708_service_reset()
void cc708_service_reset (cc708_service_decoder * decoder)
References clearTV(), cc708_service_decoder::current_window, cc708_service_decoder::inited, and cc708_service_decoder::windows.
Referenced by cc708_reset(), ccx_decoders_708_init(), handle_708_C1(), and process_service_block().
ccx_decoders_708_init()
void ccx_decoders_708_init (cc708_service_decoder * decoders, void(*)(int service, void *userdata) handler, void * userdata, CDecoderCC708 * parent)
References cc_decoder_s::callback, cc708_service_decoder::callback, cc708_service_reset(), CCX_DECODERS_708_MAX_SERVICES, CDecoderCC708::m_cc608decoder, CDecoderCC708::m_current_packet_length, CDecoderCC708::m_last_seq, CDecoderCC708::m_seen608, CDecoderCC708::m_seen708, cc708_service_decoder::parent, cc708_service_decoder::service, cc708_service_decoder::srt_counter, cc_decoder_s::userdata, and cc708_service_decoder::userdata.
Referenced by CDecoderCC708::Init().
check_current_packet_complete()
bool check_current_packet_complete (cc708_service_decoder * decoders)
References CDecoderCC708::m_current_packet, and cc708_service_decoder::parent.
Referenced by decode_708().
clear_packet()
void clear_packet (cc708_service_decoder * decoder)
References CDecoderCC708::m_current_packet_length, and cc708_service_decoder::parent.
Referenced by cc708_reset(), and process_current_packet().
clearTV()
void clearTV (cc708_service_decoder * decoder)
References tvscreen::chars, I708_SCREENGRID_COLUMNS, and cc708_service_decoder::tv.
Referenced by cc708_service_reset(), and updateScreen().
clearWindow()
void clearWindow (cc708_service_decoder * decoder, int window)
References clearWindowText(), e708Window::is_defined, and cc708_service_decoder::windows.
Referenced by handle_708_CLW_ClearWindows().
clearWindowText()
void clearWindowText (e708Window * window)
References I708_MAX_COLUMNS, I708_MAX_ROWS, e708Window::is_empty, and e708Window::rows.
Referenced by clearWindow(), deleteWindow(), and handle_708_DFx_DefineWindow().
compWindowsPriorities()
int compWindowsPriorities (const void * a, const void * b)
References e708Window::priority.
Referenced by updateScreen().
decode_708()
void decode_708 (const unsigned char * data, int datalength, cc708_service_decoder * decoders)
References check_current_packet_complete(), data(), decode_cc(), CDecoderCC708::m_current_packet, CDecoderCC708::m_current_packet_length, cc708_service_decoder::parent, and process_current_packet().
Referenced by CDecoderCC708::Decode().
deleteWindow()
void deleteWindow (cc708_service_decoder * decoder, int window)
Todo:
Do the actual deletion (remove from display if needed, etc), mark as
References clearWindowText(), cc708_service_decoder::current_window, e708Window::is_defined, and cc708_service_decoder::windows.
Referenced by handle_708_DLW_DeleteWindows().
get_internal_from_G0()
unsigned char get_internal_from_G0 (unsigned char g0_char)
Referenced by handle_708_G0().
get_internal_from_G1()
unsigned char get_internal_from_G1 (unsigned char g1_char)
Referenced by handle_708_G1().
get_internal_from_G2()
unsigned char get_internal_from_G2 (unsigned char g2_char)
Todo:
Probably not right
Referenced by handle_708_extended_char().
get_internal_from_G3()
unsigned char get_internal_from_G3 (unsigned char g3_char)
Todo:
Probably not right
Referenced by handle_708_extended_char().
handle_708_C0()
int handle_708_C0 (cc708_service_decoder * decoder, unsigned char * data, int data_length)
Todo:
Process HDR
Todo:
Process FF
Todo:
Handle PE16
Todo:
Do something useful eventually
References COMMANDS_C0, data(), name, and process_cr().
Referenced by process_service_block().
handle_708_C1()
int handle_708_C1 (cc708_service_decoder * decoder, unsigned char * data, int data_length)
References cc708_service_reset(), CLW, S_COMMANDS_C1::code, COMMANDS_C1, CW0, CW1, CW2, CW3, CW4, CW5, CW6, CW7, data(), DF0, DF1, DF2, DF3, DF4, DF5, DF6, DF7, DLC, DLW, DLY, DSW, handle_708_CLW_ClearWindows(), handle_708_CWx_SetCurrentWindow(), handle_708_DFx_DefineWindow(), handle_708_DLC_DelayCancel(), handle_708_DLW_DeleteWindows(), handle_708_DLY_Delay(), handle_708_DSW_DisplayWindows(), handle_708_HDW_HideWindows(), handle_708_SPA_SetPenAttributes(), handle_708_SPC_SetPenColor(), handle_708_SPL_SetPenLocation(), handle_708_SWA_SetWindowAttributes(), handle_708_TGW_ToggleWindows(), HDW, S_COMMANDS_C1::length, RST, RSV93, RSV94, RSV95, RSV96, SPA, SPC, SPL, SWA, and TGW.
Referenced by process_service_block().
handle_708_C2()
int handle_708_C2 (cc708_service_decoder * decoder, unsigned char * data, int data_length)
Todo:
This code is completely untested due to lack of samples. Just following specs!
References data().
Referenced by handle_708_extended_char().
handle_708_C3()
int handle_708_C3 (cc708_service_decoder * decoder, unsigned char * data, int data_length)
Todo:
Implement if a sample ever appears
References data(), CLog::Log(), and LOGERROR.
Referenced by handle_708_extended_char().
handle_708_CLW_ClearWindows()
void handle_708_CLW_ClearWindows (cc708_service_decoder * decoder, int windows_bitmap)
References clearWindow().
Referenced by handle_708_C1().
handle_708_CWx_SetCurrentWindow()
void handle_708_CWx_SetCurrentWindow (cc708_service_decoder * decoder, int new_window)
References cc708_service_decoder::current_window, e708Window::is_defined, and cc708_service_decoder::windows.
Referenced by handle_708_C1(), and handle_708_DFx_DefineWindow().
handle_708_DFx_DefineWindow()
void handle_708_DFx_DefineWindow (cc708_service_decoder * decoder, int window, unsigned char * data)
Todo:
COLORS
Todo:
Warn somehow
References e708Window::anchor_horizontal, e708Window::anchor_point, e708Window::anchor_vertical, e708Window::attribs, clearWindowText(), e708Window::col_count, e708Window::col_lock, e708Window::commands, cc708_service_decoder::current_window, data(), handle_708_CWx_SetCurrentWindow(), I708_MAX_COLUMNS, I708_MAX_ROWS, I708_SCREENGRID_ROWS, e708Window::is_defined, e708Window::memory_reserved, e708Window::number, e708Window::pen_column, e708Window::pen_row, e708Window::pen_style, e708Window::priority, e708Window::relative_pos, e708Window::row_count, e708Window::row_lock, e708Window::rows, e708Window::visible, e708Window::win_style, and cc708_service_decoder::windows.
Referenced by handle_708_C1().
handle_708_DLC_DelayCancel()
void handle_708_DLC_DelayCancel (cc708_service_decoder * decoder)
Todo:
See above
Referenced by handle_708_C1().
handle_708_DLW_DeleteWindows()
void handle_708_DLW_DeleteWindows (cc708_service_decoder * decoder, int windows_bitmap)
References deleteWindow(), e708Window::is_defined, e708Window::is_empty, updateScreen(), e708Window::visible, and cc708_service_decoder::windows.
Referenced by handle_708_C1().
handle_708_DLY_Delay()
void handle_708_DLY_Delay (cc708_service_decoder * decoder, int tenths_of_sec)
Todo:
Probably ask for the current FTS and wait for this time before resuming -
Referenced by handle_708_C1().
handle_708_DSW_DisplayWindows()
void handle_708_DSW_DisplayWindows (cc708_service_decoder * decoder, int windows_bitmap)
References updateScreen(), and cc708_service_decoder::windows.
Referenced by handle_708_C1().
handle_708_extended_char()
int handle_708_extended_char (cc708_service_decoder * decoder, unsigned char * data, int data_length)
Todo:
This code is completely untested due to lack of samples. Just following specs!
Todo:
Something
References S_COMMANDS_C1::code, data(), get_internal_from_G2(), get_internal_from_G3(), handle_708_C2(), handle_708_C3(), and process_character().
Referenced by process_service_block().
handle_708_G0()
int handle_708_G0 (cc708_service_decoder * decoder, unsigned char * data, int data_length)
Todo:
Substitution of the music note character for the ASCII DEL character
References data(), get_internal_from_G0(), and process_character().
Referenced by process_service_block().
handle_708_G1()
int handle_708_G1 (cc708_service_decoder * decoder, unsigned char * data, int data_length)
References data(), get_internal_from_G1(), and process_character().
Referenced by process_service_block().
handle_708_HDW_HideWindows()
void handle_708_HDW_HideWindows (cc708_service_decoder * decoder, int windows_bitmap)
Todo:
Actually Hide Window
References updateScreen(), and cc708_service_decoder::windows.
Referenced by handle_708_C1().
handle_708_SPA_SetPenAttributes()
void handle_708_SPA_SetPenAttributes (cc708_service_decoder * decoder, unsigned char * data)
References cc708_service_decoder::current_window, data(), e708Pen_attribs::edge_type, e708Pen_attribs::font_tag, e708Pen_attribs::italic, e708Pen_attribs::offset, e708Window::pen, e708Pen_attribs::pen_size, e708Pen_attribs::text_tag, e708Pen_attribs::underline, and cc708_service_decoder::windows.
Referenced by handle_708_C1().
handle_708_SPC_SetPenColor()
void handle_708_SPC_SetPenColor (cc708_service_decoder * decoder, unsigned char * data)
References e708Pen_color::bg_color, e708Pen_color::bg_opacity, cc708_service_decoder::current_window, data(), e708Pen_color::edge_color, e708Pen_color::fg_color, e708Pen_color::fg_opacity, e708Window::pen_color, and cc708_service_decoder::windows.
Referenced by handle_708_C1().
handle_708_SPL_SetPenLocation()
void handle_708_SPL_SetPenLocation (cc708_service_decoder * decoder, unsigned char * data)
References cc708_service_decoder::current_window, data(), e708Window::pen_column, e708Window::pen_row, and cc708_service_decoder::windows.
Referenced by handle_708_C1().
handle_708_SWA_SetWindowAttributes()
void handle_708_SWA_SetWindowAttributes (cc708_service_decoder * decoder, unsigned char * data)
References e708Window::attribs, e708Window_attribs::border_color, e708Window_attribs::border_type, e708Window_attribs::border_type01, cc708_service_decoder::current_window, data(), e708Window_attribs::display_eff, e708Window_attribs::effect_dir, e708Window_attribs::effect_speed, e708Window_attribs::fill_color, e708Window_attribs::fill_opacity, e708Window_attribs::justify, e708Window_attribs::print_dir, e708Window_attribs::scroll_dir, cc708_service_decoder::windows, and e708Window_attribs::word_wrap.
Referenced by handle_708_C1().
handle_708_TGW_ToggleWindows()
void handle_708_TGW_ToggleWindows (cc708_service_decoder * decoder, int windows_bitmap)
References updateScreen(), and cc708_service_decoder::windows.
Referenced by handle_708_C1().
printTVtoBuf()
void printTVtoBuf (cc708_service_decoder * decoder)
References tvscreen::chars, f, I708_SCREENGRID_COLUMNS, cc708_service_decoder::text, cc708_service_decoder::textlen, and cc708_service_decoder::tv.
Referenced by updateScreen().
process_character()
void process_character (cc708_service_decoder * decoder, unsigned char internal_char)
References e708Window::attribs, e708Window::col_count, cc708_service_decoder::current_window, e708Window::is_defined, e708Window::is_empty, pd_bottom_to_top, pd_left_to_right, pd_right_to_left, pd_top_to_bottom, e708Window::pen_column, e708Window::pen_row, e708Window_attribs::print_dir, e708Window::row_count, e708Window::rows, and cc708_service_decoder::windows.
Referenced by handle_708_extended_char(), handle_708_G0(), and handle_708_G1().
process_cr()
void process_cr (cc708_service_decoder * decoder)
References e708Window::anchor_point, anchorpoint_bottom_center, anchorpoint_bottom_left, e708Window::attribs, e708Window::col_count, cc708_service_decoder::current_window, pd_bottom_to_top, pd_left_to_right, pd_right_to_left, pd_top_to_bottom, e708Window::pen_column, e708Window::pen_row, e708Window_attribs::print_dir, rollupWindow(), e708Window::row_count, updateScreen(), and cc708_service_decoder::windows.
Referenced by handle_708_C0().
process_current_packet()
void process_current_packet (cc708_service_decoder * decoders)
References cc708_reset(), clear_packet(), CDecoderCC708::m_current_packet, CDecoderCC708::m_last_seq, cc708_service_decoder::parent, and process_service_block().
Referenced by decode_708().
process_service_block()
void process_service_block (cc708_service_decoder * decoder, unsigned char * data, int data_length)
Todo:
Not sure if a local reset is going to be helpful here.
References anchorpoint_bottom_center, anchorpoint_bottom_left, cc708_service_reset(), data(), EXT1, handle_708_C0(), handle_708_C1(), handle_708_extended_char(), handle_708_G0(), handle_708_G1(), updateScreen(), and cc708_service_decoder::windows.
Referenced by process_current_packet().
rollupWindow()
void rollupWindow (cc708_service_decoder * decoder, int window)
References e708Window::col_count, e708Window::row_count, e708Window::rows, and cc708_service_decoder::windows.
Referenced by process_cr().
updateScreen()
void updateScreen (cc708_service_decoder * decoder)
References e708Window::anchor_horizontal, e708Window::anchor_vertical, anchorpoint_bottom_center, anchorpoint_bottom_left, anchorpoint_bottom_right, anchorpoint_middle_center, anchorpoint_middle_left, anchorpoint_middle_right, anchorpoint_top_center, anchorpoint_top_left, anchorpoint_top_right, cc708_service_decoder::callback, tvscreen::chars, clearTV(), e708Window::col_count, compWindowsPriorities(), I708_MAX_WINDOWS, I708_SCREENGRID_COLUMNS, I708_SCREENGRID_ROWS, left, printTVtoBuf(), e708Window::row_count, e708Window::rows, cc708_service_decoder::service, cc708_service_decoder::tv, cc708_service_decoder::userdata, and cc708_service_decoder::windows.
Referenced by handle_708_DLW_DeleteWindows(), handle_708_DSW_DisplayWindows(), handle_708_HDW_HideWindows(), handle_708_TGW_ToggleWindows(), process_cr(), and process_service_block().
Variable Documentation
COMMANDS_C0
const char* COMMANDS_C0[32]
Referenced by handle_708_C0().
COMMANDS_C1
struct S_COMMANDS_C1 COMMANDS_C1[32]
Referenced by handle_708_C1().