Kodi Documentation: dbiplus::field_value Class Reference
dbiplus::field_value Class Reference
#include <qry_dat.h>
Public Member Functions
field_value ()
field_value (const char *s)
field_value (const bool b)
field_value (const char c)
field_value (const short s)
field_value (const unsigned short us)
field_value (const int l)
field_value (const unsigned int ul)
field_value (const float f)
field_value (const double d)
field_value (const int64_t i)
field_value (const char *s, std::size_t len)
field_value (const field_value &fv)
field_value (field_value &&fv) noexcept
~field_value ()
fType get_fType () const
bool get_isNull () const
std::string get_asString () const &
std::string get_asString () &&
bool get_asBool () const
char get_asChar () const
short get_asShort () const
unsigned short get_asUShort () const
int get_asInt () const
unsigned int get_asUInt () const
float get_asFloat () const
double get_asDouble () const
int64_t get_asInt64 () const
field_value & operator= (const char *s)
field_value & operator= (const std::string &s)
field_value & operator= (std::string &&s)
field_value & operator= (const bool b)
field_value & operator= (const short s)
field_value & operator= (const unsigned short us)
field_value & operator= (const int l)
field_value & operator= (const unsigned int l)
field_value & operator= (const float f)
field_value & operator= (const double d)
field_value & operator= (const int64_t i)
field_value & operator= (const field_value &fv)
field_value & operator= (field_value &&fv) noexcept
void set_isNull ()
void set_asString (const char *s)
void set_asString (const char *s, std::size_t len)
void set_asString (const std::string &s)
void set_asString (std::string &&s)
void set_asBool (const bool b)
void set_asChar (const char c)
void set_asShort (const short s)
void set_asUShort (const unsigned short us)
void set_asInt (const int l)
void set_asUInt (const unsigned int l)
void set_asFloat (const float f)
void set_asDouble (const double d)
void set_asInt64 (const int64_t i)
fType get_field_type ()
std::string gft ()
Private Attributes
fType field_type
std::string str_value
union {
bool bool_value
char char_value
short short_value
unsigned short ushort_value
int int_value
unsigned int uint_value
float float_value
double double_value
int64_t int64_value
void * object_value
};
bool is_null
Friends
std::ostream & operator<< (std::ostream &os, const field_value &fv)
Constructor & Destructor Documentation
field_value() [1/14]
dbiplus::field_value::field_value ()
References field_type, dbiplus::ft_String, and is_null.
field_value() [2/14]
dbiplus::field_value::field_value (const char * s) explicit
References field_type, dbiplus::ft_String, and is_null.
field_value() [3/14]
dbiplus::field_value::field_value (const bool b) explicit
References bool_value, field_type, dbiplus::ft_Boolean, and is_null.
field_value() [4/14]
dbiplus::field_value::field_value (const char c) explicit
References char_value, field_type, dbiplus::ft_Char, and is_null.
field_value() [5/14]
dbiplus::field_value::field_value (const short s) explicit
References field_type, dbiplus::ft_Short, is_null, and short_value.
field_value() [6/14]
dbiplus::field_value::field_value (const unsigned short us) explicit
References field_type, dbiplus::ft_UShort, is_null, and ushort_value.
field_value() [7/14]
dbiplus::field_value::field_value (const int l) explicit
References field_type, dbiplus::ft_Int, int_value, and is_null.
field_value() [8/14]
dbiplus::field_value::field_value (const unsigned int ul) explicit
References field_type, dbiplus::ft_UInt, is_null, and uint_value.
field_value() [9/14]
dbiplus::field_value::field_value (const float f) explicit
References f, field_type, float_value, dbiplus::ft_Float, and is_null.
field_value() [10/14]
dbiplus::field_value::field_value (const double d) explicit
References double_value, field_type, dbiplus::ft_Double, and is_null.
field_value() [11/14]
dbiplus::field_value::field_value (const int64_t i) explicit
References field_type, dbiplus::ft_Int64, int64_value, and is_null.
field_value() [12/14]
dbiplus::field_value::field_value (const char * s, std::size_t len)
field_value() [13/14]
dbiplus::field_value::field_value (const field_value & fv)
References dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), get_fType(), get_isNull(), is_null, set_asBool(), set_asChar(), set_asDouble(), set_asFloat(), set_asInt(), set_asInt64(), set_asShort(), set_asString(), set_asUInt(), and set_asUShort().
field_value() [14/14]
dbiplus::field_value::field_value (field_value && fv) noexcept
~field_value()
dbiplus::field_value::~field_value () default
Member Function Documentation
get_asBool()
bool dbiplus::field_value::get_asBool () const
References bool_value, char_value, double_value, field_type, float_value, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, int64_value, int_value, short_value, str_value, uint_value, and ushort_value.
Referenced by field_value(), DatabaseUtils::GetFieldValue(), and operator=().
get_asChar()
char dbiplus::field_value::get_asChar () const
References bool_value, char_value, double_value, field_type, float_value, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, int64_value, int_value, short_value, str_value, t, uint_value, and ushort_value.
Referenced by field_value(), DatabaseUtils::GetFieldValue(), and operator=().
get_asDouble()
double dbiplus::field_value::get_asDouble () const
References bool_value, char_value, double_value, field_type, float_value, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, int64_value, int_value, short_value, str_value, uint_value, and ushort_value.
Referenced by field_value(), DatabaseUtils::GetFieldValue(), and operator=().
get_asFloat()
float dbiplus::field_value::get_asFloat () const
References bool_value, char_value, double_value, field_type, float_value, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, int64_value, int_value, short_value, str_value, uint_value, and ushort_value.
Referenced by field_value(), DatabaseUtils::GetFieldValue(), and operator=().
get_asInt()
int dbiplus::field_value::get_asInt () const
References bool_value, char_value, double_value, field_type, float_value, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, int64_value, int_value, short_value, str_value, uint_value, and ushort_value.
Referenced by field_value(), DatabaseUtils::GetFieldValue(), and operator=().
get_asInt64()
int64_t dbiplus::field_value::get_asInt64 () const
References bool_value, char_value, double_value, field_type, float_value, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, int64_t(), int64_value, int_value, short_value, str_value, uint_value, and ushort_value.
Referenced by field_value(), DatabaseUtils::GetFieldValue(), and operator=().
get_asShort()
short dbiplus::field_value::get_asShort () const
References bool_value, char_value, double_value, field_type, float_value, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, int64_value, int_value, short_value, str_value, uint_value, and ushort_value.
Referenced by field_value(), DatabaseUtils::GetFieldValue(), and operator=().
get_asString() [1/2]
std::string dbiplus::field_value::get_asString () &&
References dbiplus::ft_String.
get_asString() [2/2]
std::string dbiplus::field_value::get_asString () const &
References bool_value, char_value, double_value, field_type, float_value, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, int64_value, int_value, short_value, str_value, t, uint_value, and ushort_value.
Referenced by field_value(), dbiplus::Dataset::findNext(), DatabaseUtils::GetFieldValue(), dbiplus::Dataset::locate(), and operator=().
get_asUInt()
unsigned int dbiplus::field_value::get_asUInt () const
References bool_value, char_value, double_value, field_type, float_value, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, int64_value, int_value, short_value, str_value, uint_value, and ushort_value.
Referenced by field_value(), DatabaseUtils::GetFieldValue(), and operator=().
get_asUShort()
unsigned short dbiplus::field_value::get_asUShort () const
References bool_value, char_value, double_value, field_type, float_value, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, int64_value, int_value, short_value, str_value, uint_value, and ushort_value.
Referenced by field_value(), and operator=().
get_field_type()
fType dbiplus::field_value::get_field_type ()
References field_type.
get_fType()
fType dbiplus::field_value::get_fType () const inline
References field_type.
Referenced by field_value(), DatabaseUtils::GetFieldValue(), and operator=().
get_isNull()
bool dbiplus::field_value::get_isNull () const inline
References is_null.
Referenced by field_value(), DatabaseUtils::GetFieldValue(), operator=(), and operator=().
gft()
std::string dbiplus::field_value::gft ()
References field_type, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, and dbiplus::ft_String.
operator=() [1/13]
field_value & dbiplus::field_value::operator= (const bool b) inline
References set_asBool().
operator=() [2/13]
field_value & dbiplus::field_value::operator= (const char * s) inline
References set_asString().
operator=() [3/13]
field_value & dbiplus::field_value::operator= (const double d) inline
References set_asDouble().
operator=() [4/13]
field_value & dbiplus::field_value::operator= (const field_value & fv)
References dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), get_fType(), get_isNull(), is_null, set_asBool(), set_asChar(), set_asDouble(), set_asFloat(), set_asInt(), set_asInt64(), set_asShort(), set_asString(), set_asUInt(), and set_asUShort().
operator=() [5/13]
field_value & dbiplus::field_value::operator= (const float f) inline
References f, and set_asFloat().
operator=() [6/13]
field_value & dbiplus::field_value::operator= (const int l) inline
References set_asInt().
operator=() [7/13]
field_value & dbiplus::field_value::operator= (const int64_t i) inline
References set_asInt64().
operator=() [8/13]
field_value & dbiplus::field_value::operator= (const short s) inline
References set_asShort().
operator=() [9/13]
field_value & dbiplus::field_value::operator= (const std::string & s) inline
References set_asString().
operator=() [10/13]
field_value & dbiplus::field_value::operator= (const unsigned int l) inline
References set_asUInt().
operator=() [11/13]
field_value & dbiplus::field_value::operator= (const unsigned short us) inline
References set_asUShort().
operator=() [12/13]
field_value & dbiplus::field_value::operator= (field_value && fv) noexcept
References dbiplus::ft_String, and get_isNull().
operator=() [13/13]
field_value & dbiplus::field_value::operator= (std::string && s) inline
References set_asString().
set_asBool()
void dbiplus::field_value::set_asBool (const bool b)
References bool_value, field_type, and dbiplus::ft_Boolean.
Referenced by field_value(), operator=(), and operator=().
set_asChar()
void dbiplus::field_value::set_asChar (const char c)
References char_value, field_type, and dbiplus::ft_Char.
Referenced by field_value(), and operator=().
set_asDouble()
void dbiplus::field_value::set_asDouble (const double d)
References double_value, field_type, and dbiplus::ft_Double.
Referenced by field_value(), operator=(), operator=(), dbiplus::MysqlDataset::query(), and dbiplus::SqliteDataset::query().
set_asFloat()
void dbiplus::field_value::set_asFloat (const float f)
References f, field_type, float_value, and dbiplus::ft_Float.
Referenced by field_value(), operator=(), and operator=().
set_asInt()
void dbiplus::field_value::set_asInt (const int l)
References field_type, dbiplus::ft_Int, and int_value.
Referenced by field_value(), operator=(), operator=(), and dbiplus::MysqlDataset::query().
set_asInt64()
void dbiplus::field_value::set_asInt64 (const int64_t i)
References field_type, dbiplus::ft_Int64, and int64_value.
Referenced by field_value(), operator=(), operator=(), dbiplus::MysqlDataset::query(), and dbiplus::SqliteDataset::query().
set_asShort()
void dbiplus::field_value::set_asShort (const short s)
References field_type, dbiplus::ft_Short, and short_value.
Referenced by field_value(), operator=(), and operator=().
set_asString() [1/4]
void dbiplus::field_value::set_asString (const char * s)
References field_type, dbiplus::ft_String, and str_value.
Referenced by dbiplus::callback(), field_value(), operator=(), operator=(), operator=(), operator=(), dbiplus::MysqlDataset::query(), and dbiplus::SqliteDataset::query().
set_asString() [2/4]
void dbiplus::field_value::set_asString (const char * s, std::size_t len)
References field_type, dbiplus::ft_String, and str_value.
set_asString() [3/4]
void dbiplus::field_value::set_asString (const std::string & s)
References field_type, dbiplus::ft_String, and str_value.
set_asString() [4/4]
void dbiplus::field_value::set_asString (std::string && s)
References field_type, dbiplus::ft_String, and str_value.
set_asUInt()
void dbiplus::field_value::set_asUInt (const unsigned int l)
References field_type, dbiplus::ft_UInt, and int_value.
Referenced by field_value(), operator=(), and operator=().
set_asUShort()
void dbiplus::field_value::set_asUShort (const unsigned short us)
References field_type, dbiplus::ft_UShort, and ushort_value.
Referenced by field_value(), operator=(), and operator=().
set_isNull()
void dbiplus::field_value::set_isNull () inline
References is_null.
Referenced by dbiplus::callback(), dbiplus::MysqlDataset::query(), dbiplus::SqliteDataset::query(), and TEST().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const field_value & fv) friend
Member Data Documentation
[union]
union { ... } dbiplus::field_value
bool_value
bool dbiplus::field_value::bool_value
Referenced by field_value(), get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), and set_asBool().
char_value
char dbiplus::field_value::char_value
Referenced by field_value(), get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), and set_asChar().
double_value
double dbiplus::field_value::double_value
Referenced by field_value(), get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), and set_asDouble().
field_type
fType dbiplus::field_value::field_type private
Referenced by field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), get_field_type(), get_fType(), gft(), set_asBool(), set_asChar(), set_asDouble(), set_asFloat(), set_asInt(), set_asInt64(), set_asShort(), set_asString(), set_asString(), set_asString(), set_asString(), set_asUInt(), and set_asUShort().
float_value
float dbiplus::field_value::float_value
Referenced by field_value(), get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), and set_asFloat().
int64_value
int64_t dbiplus::field_value::int64_value
Referenced by field_value(), get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), and set_asInt64().
int_value
int dbiplus::field_value::int_value
Referenced by field_value(), get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), set_asInt(), and set_asUInt().
is_null
bool dbiplus::field_value::is_null private
Referenced by field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), field_value(), get_isNull(), operator=(), and set_isNull().
object_value
void* dbiplus::field_value::object_value
short_value
short dbiplus::field_value::short_value
Referenced by field_value(), get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), and set_asShort().
str_value
std::string dbiplus::field_value::str_value private
Referenced by get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), set_asString(), set_asString(), set_asString(), and set_asString().
uint_value
unsigned int dbiplus::field_value::uint_value
Referenced by field_value(), get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), and get_asUShort().
ushort_value
unsigned short dbiplus::field_value::ushort_value
Referenced by field_value(), get_asBool(), get_asChar(), get_asDouble(), get_asFloat(), get_asInt(), get_asInt64(), get_asShort(), get_asString(), get_asUInt(), get_asUShort(), and set_asUShort().
The documentation for this class was generated from the following files:
qry_dat.h
qry_dat.cpp