Kodi Documentation: class ImageDecoderInfoTag
class ImageDecoderInfoTag
C++ » Interface - kodi::addon » Addon type instances » Image Decoder » Definitions, structures and enumerators
Info tag data structure
Representation of available information of processed audio file.
Modules
Value Help
Classes
class kodi::addon::ImageDecoderInfoTag
Functions
void kodi::addon::ImageDecoderInfoTag::SetWidth (int width)
Set the camera manufacturer as string on info tag.
int kodi::addon::ImageDecoderInfoTag::GetWidth () const
Get image width as pixels.
void kodi::addon::ImageDecoderInfoTag::SetHeight (int height)
Set the image height as pixels.
int kodi::addon::ImageDecoderInfoTag::GetHeight () const
Get image height as pixels.
void kodi::addon::ImageDecoderInfoTag::SetDistance (int distance)
Set the image distance in meters.
int kodi::addon::ImageDecoderInfoTag::GetDistance () const
Get mage distance in meters.
void kodi::addon::ImageDecoderInfoTag::SetColor (ADDON_IMG_COLOR color)
Set the image color type.
ADDON_IMG_COLOR kodi::addon::ImageDecoderInfoTag::GetColor () const
Get image image color type.
void kodi::addon::ImageDecoderInfoTag::SetMeteringMode (ADDON_IMG_METERING_MODE metering_mode)
Set metering mode.
ADDON_IMG_METERING_MODE kodi::addon::ImageDecoderInfoTag::GetMeteringMode () const
Get metering mode.
void kodi::addon::ImageDecoderInfoTag::SetExposureTime (float exposure_time)
Set exposure time.
float kodi::addon::ImageDecoderInfoTag::GetExposureTime () const
Get exposure time.
void kodi::addon::ImageDecoderInfoTag::SetExposureBias (float exposure_bias)
Set exposure bias.
float kodi::addon::ImageDecoderInfoTag::GetExposureBias () const
Get exposure bias.
void kodi::addon::ImageDecoderInfoTag::SetExposureProgram (ADDON_IMG_EXPOSURE_PROGRAM exposure_program)
Set Exposure program.
ADDON_IMG_EXPOSURE_PROGRAM kodi::addon::ImageDecoderInfoTag::GetExposureProgram () const
Get Exposure program.
void kodi::addon::ImageDecoderInfoTag::SetExposureMode (ADDON_IMG_EXPOSURE_MODE exposure_mode)
Set Exposure mode.
ADDON_IMG_EXPOSURE_MODE kodi::addon::ImageDecoderInfoTag::GetExposureMode () const
Get Exposure mode.
void kodi::addon::ImageDecoderInfoTag::SetOrientation (ADDON_IMG_ORIENTATION orientation)
Set the orientation.
ADDON_IMG_ORIENTATION kodi::addon::ImageDecoderInfoTag::GetOrientation () const
Get image orientation.
void kodi::addon::ImageDecoderInfoTag::SetTimeCreated (time_t time_created)
Set the image creation time in time_t format (number of seconds elapsed since 00:00 hours, Jan 1, 1970 UTC).
time_t kodi::addon::ImageDecoderInfoTag::GetTimeCreated () const
Get image creation time.
void kodi::addon::ImageDecoderInfoTag::SetApertureFNumber (float aperture_f_number)
Set Aperture F number.
float kodi::addon::ImageDecoderInfoTag::GetApertureFNumber () const
Get Aperture F number.
void kodi::addon::ImageDecoderInfoTag::SetFlashUsed (ADDON_IMG_FLASH_TYPE flash_used)
Set to true if image was created with flash.
ADDON_IMG_FLASH_TYPE kodi::addon::ImageDecoderInfoTag::GetFlashUsed () const
Get info about image was created with flash.
void kodi::addon::ImageDecoderInfoTag::SetFocalLength (int focal_length)
Set focal length.
int kodi::addon::ImageDecoderInfoTag::GetFocalLength () const
Get focal length.
void kodi::addon::ImageDecoderInfoTag::SetLightSource (ADDON_IMG_LIGHT_SOURCE light_source)
Set light source.
ADDON_IMG_LIGHT_SOURCE kodi::addon::ImageDecoderInfoTag::GetLightSource () const
Get light source.
void kodi::addon::ImageDecoderInfoTag::SetFocalLengthIn35mmFormat (int focal_length_in_35mm_format)
Set focal length in 35 mm format.
int kodi::addon::ImageDecoderInfoTag::GetFocalLengthIn35mmFormat () const
Get focal length in 35 mm format.
void kodi::addon::ImageDecoderInfoTag::SetDigitalZoomRatio (float digital_zoom_ratio)
Set digital zoom ratio.
float kodi::addon::ImageDecoderInfoTag::GetDigitalZoomRatio () const
Get digital zoom ratio.
void kodi::addon::ImageDecoderInfoTag::SetISOSpeed (float iso_speed)
Set ISO sensitivity.
float kodi::addon::ImageDecoderInfoTag::GetISOSpeed () const
Get ISO sensitivity.
void kodi::addon::ImageDecoderInfoTag::SetGPSInfo (bool gps_info_present, char latitude_ref, float latitude[3], char longitude_ref, float longitude[3], int altitude_ref, float altitude)
Set GPS position information.
void kodi::addon::ImageDecoderInfoTag::GetGPSInfo (bool &gps_info_present, char &latitude_ref, float latitude[3], char &longitude_ref, float longitude[3], int &altitude_ref, float &altitude)
Get GPS position information.
void kodi::addon::ImageDecoderInfoTag::SetCameraManufacturer (const std::string &camera_manufacturer)
Set the camera manufacturer as string on info tag.
const std::string & kodi::addon::ImageDecoderInfoTag::GetCameraManufacturer () const
Get camera manufacturer.
void kodi::addon::ImageDecoderInfoTag::SetCameraModel (const std::string &camera_model)
Set camera model.
const std::string & kodi::addon::ImageDecoderInfoTag::GetCameraModel () const
Get camera model.
void kodi::addon::ImageDecoderInfoTag::SetAuthor (const std::string &author)
Set author.
const std::string & kodi::addon::ImageDecoderInfoTag::GetAuthor () const
Get author.
void kodi::addon::ImageDecoderInfoTag::SetDescription (const std::string &description)
Set description.
const std::string & kodi::addon::ImageDecoderInfoTag::GetDescription () const
Get description.
void kodi::addon::ImageDecoderInfoTag::SetCopyright (const std::string &copyright)
Set copyright.
const std::string & kodi::addon::ImageDecoderInfoTag::GetCopyright () const
Get copyright.
Detailed Description
Info tag data structure
Representation of available information of processed audio file.
This is used to get all the necessary data of audio stream and to have on created files by encoders.
The following table contains values that can be set with class ImageDecoderInfoTag :
Name Type Set call Get call
Width int SetWidth GetWidth
Height int SetHeight GetHeight
Distance float SetDistance GetDistance
Color enum ADDON_IMG_COLOR SetColor GetColor
Orientation enum ADDON_IMG_ORIENTATION SetOrientation GetOrientation
Metering mode enum ADDON_IMG_METERING_MODE SetMeteringMode GetMeteringMode
Exposure time float SetExposureTime GetExposureTime
Exposure bias float SetExposureBias GetExposureBias
Exposure program enum ADDON_IMG_EXPOSURE_PROGRAM SetExposureProgram GetExposureProgram
Exposure mode enum ADDON_IMG_EXPOSURE_MODE SetExposureMode GetExposureMode
Time created time_t SetTimeCreated GetTimeCreated
Aperture F number float SetApertureFNumber GetApertureFNumber
Flash used ADDON_IMG_FLASH_TYPE SetFlashUsed GetFlashUsed
Light source ADDON_IMG_LIGHT_SOURCE SetLightSource GetLightSource
Focal length int SetFocalLength GetFocalLength
Focal length in 35 mm format int SetFocalLengthIn35mmFormat GetFocalLengthIn35mmFormat
Digital zoom ratio float SetDigitalZoomRatio GetDigitalZoomRatio
ISO sensitivity float SetISOSpeed GetISOSpeed
Camera manufacturer std::string SetCameraManufacturer GetCameraManufacturer
GPS info bool, char, float[3], char, float[3], int, float SetGPSInfo GetGPSInfo
Camera model std::string SetCameraModel GetCameraModel
Author std::string SetAuthor GetAuthor
Description std::string SetDescription GetDescription
Copyright std::string SetCopyright GetCopyright
Function Documentation
GetApertureFNumber()
float kodi::addon::ImageDecoderInfoTag::GetApertureFNumber () const inline
Get Aperture F number.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetAuthor()
const std::string & kodi::addon::ImageDecoderInfoTag::GetAuthor () const inline
Get author.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetCameraManufacturer()
const std::string & kodi::addon::ImageDecoderInfoTag::GetCameraManufacturer () const inline
Get camera manufacturer.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetCameraModel()
const std::string & kodi::addon::ImageDecoderInfoTag::GetCameraModel () const inline
Get camera model.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetColor()
ADDON_IMG_COLOR kodi::addon::ImageDecoderInfoTag::GetColor () const inline
Get image image color type.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetCopyright()
const std::string & kodi::addon::ImageDecoderInfoTag::GetCopyright () const inline
Get copyright.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetDescription()
const std::string & kodi::addon::ImageDecoderInfoTag::GetDescription () const inline
Get description.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetDigitalZoomRatio()
float kodi::addon::ImageDecoderInfoTag::GetDigitalZoomRatio () const inline
Get digital zoom ratio.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetDistance()
int kodi::addon::ImageDecoderInfoTag::GetDistance () const inline
Get mage distance in meters.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetExposureBias()
float kodi::addon::ImageDecoderInfoTag::GetExposureBias () const inline
Get exposure bias.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetExposureMode()
ADDON_IMG_EXPOSURE_MODE kodi::addon::ImageDecoderInfoTag::GetExposureMode () const inline
Get Exposure mode.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetExposureProgram()
ADDON_IMG_EXPOSURE_PROGRAM kodi::addon::ImageDecoderInfoTag::GetExposureProgram () const inline
Get Exposure program.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetExposureTime()
float kodi::addon::ImageDecoderInfoTag::GetExposureTime () const inline
Get exposure time.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetFlashUsed()
ADDON_IMG_FLASH_TYPE kodi::addon::ImageDecoderInfoTag::GetFlashUsed () const inline
Get info about image was created with flash.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetFocalLength()
int kodi::addon::ImageDecoderInfoTag::GetFocalLength () const inline
Get focal length.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetFocalLengthIn35mmFormat()
int kodi::addon::ImageDecoderInfoTag::GetFocalLengthIn35mmFormat () const inline
Get focal length in 35 mm format.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetGPSInfo()
void kodi::addon::ImageDecoderInfoTag::GetGPSInfo (bool & gps_info_present, char & latitude_ref, float latitude[3], char & longitude_ref, float longitude[3], int & altitude_ref, float & altitude) inline
Get GPS position information.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetHeight()
int kodi::addon::ImageDecoderInfoTag::GetHeight () const inline
Get image height as pixels.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetISOSpeed()
float kodi::addon::ImageDecoderInfoTag::GetISOSpeed () const inline
Get ISO sensitivity.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetLightSource()
ADDON_IMG_LIGHT_SOURCE kodi::addon::ImageDecoderInfoTag::GetLightSource () const inline
Get light source.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetMeteringMode()
ADDON_IMG_METERING_MODE kodi::addon::ImageDecoderInfoTag::GetMeteringMode () const inline
Get metering mode.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetOrientation()
ADDON_IMG_ORIENTATION kodi::addon::ImageDecoderInfoTag::GetOrientation () const inline
Get image orientation.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetTimeCreated()
time_t kodi::addon::ImageDecoderInfoTag::GetTimeCreated () const inline
Get image creation time.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
GetWidth()
int kodi::addon::ImageDecoderInfoTag::GetWidth () const inline
Get image width as pixels.
Referenced by kodi::addon::CInstanceImageDecoder::ADDON_read_tag().
SetApertureFNumber()
void kodi::addon::ImageDecoderInfoTag::SetApertureFNumber (float aperture_f_number) inline
Set Aperture F number.
SetAuthor()
void kodi::addon::ImageDecoderInfoTag::SetAuthor (const std::string & author) inline
Set author.
SetCameraManufacturer()
void kodi::addon::ImageDecoderInfoTag::SetCameraManufacturer (const std::string & camera_manufacturer) inline
Set the camera manufacturer as string on info tag.
SetCameraModel()
void kodi::addon::ImageDecoderInfoTag::SetCameraModel (const std::string & camera_model) inline
Set camera model.
SetColor()
void kodi::addon::ImageDecoderInfoTag::SetColor (ADDON_IMG_COLOR color) inline
Set the image color type.
References color.
SetCopyright()
void kodi::addon::ImageDecoderInfoTag::SetCopyright (const std::string & copyright) inline
Set copyright.
SetDescription()
void kodi::addon::ImageDecoderInfoTag::SetDescription (const std::string & description) inline
Set description.
SetDigitalZoomRatio()
void kodi::addon::ImageDecoderInfoTag::SetDigitalZoomRatio (float digital_zoom_ratio) inline
Set digital zoom ratio.
SetDistance()
void kodi::addon::ImageDecoderInfoTag::SetDistance (int distance) inline
Set the image distance in meters.
SetExposureBias()
void kodi::addon::ImageDecoderInfoTag::SetExposureBias (float exposure_bias) inline
Set exposure bias.
SetExposureMode()
void kodi::addon::ImageDecoderInfoTag::SetExposureMode (ADDON_IMG_EXPOSURE_MODE exposure_mode) inline
Set Exposure mode.
In auto-bracketing mode, the camera shoots a series of frames of the same scene at different exposure settings.
SetExposureProgram()
void kodi::addon::ImageDecoderInfoTag::SetExposureProgram (ADDON_IMG_EXPOSURE_PROGRAM exposure_program) inline
Set Exposure program.
SetExposureTime()
void kodi::addon::ImageDecoderInfoTag::SetExposureTime (float exposure_time) inline
Set exposure time.
SetFlashUsed()
void kodi::addon::ImageDecoderInfoTag::SetFlashUsed (ADDON_IMG_FLASH_TYPE flash_used) inline
Set to true if image was created with flash.
SetFocalLength()
void kodi::addon::ImageDecoderInfoTag::SetFocalLength (int focal_length) inline
Set focal length.
SetFocalLengthIn35mmFormat()
void kodi::addon::ImageDecoderInfoTag::SetFocalLengthIn35mmFormat (int focal_length_in_35mm_format) inline
Set focal length in 35 mm format.
Note
Same as FocalLengthIn35mmFilm in EXIF standard, tag 0xa405.
SetGPSInfo()
void kodi::addon::ImageDecoderInfoTag::SetGPSInfo (bool gps_info_present, char latitude_ref, float latitude[3], char longitude_ref, float longitude[3], int altitude_ref, float altitude) inline
Set GPS position information.
SetHeight()
void kodi::addon::ImageDecoderInfoTag::SetHeight (int height) inline
Set the image height as pixels.
SetISOSpeed()
void kodi::addon::ImageDecoderInfoTag::SetISOSpeed (float iso_speed) inline
Set ISO sensitivity.
SetLightSource()
void kodi::addon::ImageDecoderInfoTag::SetLightSource (ADDON_IMG_LIGHT_SOURCE light_source) inline
Set light source.
SetMeteringMode()
void kodi::addon::ImageDecoderInfoTag::SetMeteringMode (ADDON_IMG_METERING_MODE metering_mode) inline
Set metering mode.
SetOrientation()
void kodi::addon::ImageDecoderInfoTag::SetOrientation (ADDON_IMG_ORIENTATION orientation) inline
Set the orientation.
SetTimeCreated()
void kodi::addon::ImageDecoderInfoTag::SetTimeCreated (time_t time_created) inline
Set the image creation time in time_t format (number of seconds elapsed since 00:00 hours, Jan 1, 1970 UTC).
SetWidth()
void kodi::addon::ImageDecoderInfoTag::SetWidth (int width) inline
Set the camera manufacturer as string on info tag.