Kodi Documentation: TestXMLUtils.cpp File Reference
TestXMLUtils.cpp File Reference
#include "XBDateTime.h"
#include "utils/StringUtils.h"
#include "utils/XBMCTinyXML.h"
#include "utils/XBMCTinyXML2.h"
#include "utils/XMLUtils.h"
#include <gtest/gtest.h>
Functions
TEST (TestXMLUtils, GetHex)
TEST (TestXMLUtils, GetUInt)
TEST (TestXMLUtils, GetLong)
TEST (TestXMLUtils, GetFloat)
TEST (TestXMLUtils, GetDouble)
TEST (TestXMLUtils, GetInt)
TEST (TestXMLUtils, GetBoolean)
TEST (TestXMLUtils, GetString)
TEST (TestXMLUtils, GetAdditiveString)
TEST (TestXMLUtils, GetStringArray)
TEST (TestXMLUtils, GetPath)
TEST (TestXMLUtils, GetDate)
TEST (TestXMLUtils, GetDateTime)
TEST (TestXMLUtils, SetString)
TEST (TestXMLUtils, SetAdditiveString)
TEST (TestXMLUtils, SetStringArray)
TEST (TestXMLUtils, SetInt)
TEST (TestXMLUtils, SetFloat)
TEST (TestXMLUtils, SetBoolean)
TEST (TestXMLUtils, SetHex)
TEST (TestXMLUtils, SetPath)
TEST (TestXMLUtils, SetLong)
TEST (TestXMLUtils, SetDate)
TEST (TestXMLUtils, SetDateTime)
Function Documentation
TEST() [1/24]
TEST (TestXMLUtils , GetAdditiveString)
References EXPECT_TRUE(), XMLUtils::GetAdditiveString(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [2/24]
TEST (TestXMLUtils , GetBoolean)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetBoolean(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [3/24]
TEST (TestXMLUtils , GetDate)
References EXPECT_TRUE(), XMLUtils::GetDate(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and CDateTime::SetDate().
TEST() [4/24]
TEST (TestXMLUtils , GetDateTime)
References EXPECT_TRUE(), XMLUtils::GetDateTime(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and CDateTime::SetDateTime().
TEST() [5/24]
TEST (TestXMLUtils , GetDouble)
References EXPECT_TRUE(), KODI::UTILS::StringUtils::Format(), XMLUtils::GetDouble(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [6/24]
TEST (TestXMLUtils , GetFloat)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetFloat(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [7/24]
TEST (TestXMLUtils , GetHex)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetHex(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [8/24]
TEST (TestXMLUtils , GetInt)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetInt(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [9/24]
TEST (TestXMLUtils , GetLong)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetLong(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [10/24]
TEST (TestXMLUtils , GetPath)
References EXPECT_TRUE(), XMLUtils::GetPath(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [11/24]
TEST (TestXMLUtils , GetString)
References EXPECT_TRUE(), XMLUtils::GetString(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [12/24]
TEST (TestXMLUtils , GetStringArray)
References EXPECT_TRUE(), XMLUtils::GetStringArray(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [13/24]
TEST (TestXMLUtils , GetUInt)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetUInt(), CXBMCTinyXML::Parse(), and CXBMCTinyXML2::Parse().
TEST() [14/24]
TEST (TestXMLUtils , SetAdditiveString)
References EXPECT_TRUE(), XMLUtils::GetAdditiveString(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and XMLUtils::SetAdditiveString().
TEST() [15/24]
TEST (TestXMLUtils , SetBoolean)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetBoolean(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and XMLUtils::SetBoolean().
TEST() [16/24]
TEST (TestXMLUtils , SetDate)
References EXPECT_TRUE(), XMLUtils::GetDate(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), CDateTime::SetDate(), and XMLUtils::SetDate().
TEST() [17/24]
TEST (TestXMLUtils , SetDateTime)
References EXPECT_TRUE(), XMLUtils::GetDateTime(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), CDateTime::SetDateTime(), and XMLUtils::SetDateTime().
TEST() [18/24]
TEST (TestXMLUtils , SetFloat)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetFloat(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and XMLUtils::SetFloat().
TEST() [19/24]
TEST (TestXMLUtils , SetHex)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetHex(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and XMLUtils::SetHex().
TEST() [20/24]
TEST (TestXMLUtils , SetInt)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetInt(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and XMLUtils::SetInt().
TEST() [21/24]
TEST (TestXMLUtils , SetLong)
References EXPECT_EQ(), EXPECT_TRUE(), XMLUtils::GetLong(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and XMLUtils::SetLong().
TEST() [22/24]
TEST (TestXMLUtils , SetPath)
References EXPECT_TRUE(), XMLUtils::GetPath(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and XMLUtils::SetPath().
TEST() [23/24]
TEST (TestXMLUtils , SetString)
References EXPECT_TRUE(), XMLUtils::GetString(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and XMLUtils::SetString().
TEST() [24/24]
TEST (TestXMLUtils , SetStringArray)
References EXPECT_TRUE(), XMLUtils::GetStringArray(), CXBMCTinyXML::Parse(), CXBMCTinyXML2::Parse(), and XMLUtils::SetStringArray().