Kodi Documentation: anonymous_namespace{PVRClient.cpp}::CAddonRecording Class Reference
anonymous_namespace{PVRClient.cpp}::CAddonRecording Class Reference
Public Member Functions
CAddonRecording (const CPVRRecording &recording)
virtual ~CAddonRecording ()=default
Private Attributes
const std::string m_recordingId
const std::string m_title
const std::string m_titleExtraInfo
const std::string m_episodeName
const std::string m_directory
const std::string m_plotOutline
const std::string m_plot
const std::string m_genreDescription
const std::string m_channelName
const std::string m_iconPath
const std::string m_thumbnailPath
const std::string m_fanartPath
const std::string m_firstAired
const std::string m_providerName
const std::string m_parentalRatingCode
const std::string m_parentalRatingIcon
const std::string m_parentalRatingSource
Additional Inherited Members
Public Attributes inherited from PVR_RECORDING
const char * strRecordingId
const char * strTitle
const char * strTitleExtraInfo
int iSeriesNumber
int iEpisodeNumber
int iEpisodePartNumber
const char * strEpisodeName
int iYear
const char * strDirectory
const char * strPlotOutline
const char * strPlot
const char * strGenreDescription
const char * strChannelName
const char * strIconPath
const char * strThumbnailPath
const char * strFanartPath
time_t recordingTime
int iDuration
int iPriority
int iLifetime
int iGenreType
int iGenreSubType
int iPlayCount
int iLastPlayedPosition
bool bIsDeleted
unsigned int iEpgEventId
int iChannelUid
enum PVR_RECORDING_CHANNEL_TYPE channelType
const char * strFirstAired
unsigned int iFlags
int64_t sizeInBytes
int iClientProviderUid
const char * strProviderName
unsigned int iParentalRating
const char * strParentalRatingCode
const char * strParentalRatingIcon
const char * strParentalRatingSource
Constructor & Destructor Documentation
CAddonRecording()
anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording (const CPVRRecording & recording) inline explicit
References PVR::CPVRRecording::BroadcastUid(), PVR::CPVRRecording::ChannelUid(), PVR::CPVRRecording::ClientProviderUid(), PVR::CPVRRecording::EpisodePart(), PVR::CPVRRecording::Flags(), PVR::CPVRRecording::GenreSubType(), PVR::CPVRRecording::GenreType(), CDateTime::GetAsTime(), CVideoInfoTag::GetDuration(), PVR::CPVRRecording::GetLocalPlayCount(), PVR::CPVRRecording::GetLocalResumePoint(), CServiceBroker::GetSettingsComponent(), PVR::CPVRRecording::GetSizeInBytes(), PVR::CPVRRecording::GetYear(), PVR::CPVRRecording::IsDeleted(), PVR::CPVRRecording::IsRadio(), PVR::CPVRRecording::LifeTime(), CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iSeason, PVR::CPVRRecording::Priority(), PVR_RECORDING_CHANNEL_TYPE_RADIO, PVR_RECORDING_CHANNEL_TYPE_TV, PVR::CPVRRecording::RecordingTimeAsUTC(), and CBookmark::timeInSeconds.
~CAddonRecording()
virtual anonymous_namespace{PVRClient.cpp}::CAddonRecording::~CAddonRecording () virtual default
Member Data Documentation
m_channelName
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_channelName private
m_directory
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_directory private
m_episodeName
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_episodeName private
m_fanartPath
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_fanartPath private
m_firstAired
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_firstAired private
m_genreDescription
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_genreDescription private
m_iconPath
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_iconPath private
m_parentalRatingCode
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_parentalRatingCode private
m_parentalRatingIcon
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_parentalRatingIcon private
m_parentalRatingSource
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_parentalRatingSource private
m_plot
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_plot private
m_plotOutline
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_plotOutline private
m_providerName
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_providerName private
m_recordingId
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_recordingId private
m_thumbnailPath
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_thumbnailPath private
m_title
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_title private
m_titleExtraInfo
const std::string anonymous_namespace{PVRClient.cpp}::CAddonRecording::m_titleExtraInfo private
The documentation for this class was generated from the following file:
PVRClient.cpp