Kodi Documentation: KODI::WINDOWING::WAYLAND::CWindowDecorator Class Reference
KODI::WINDOWING::WAYLAND::CWindowDecorator Class Reference final
#include <WindowDecorator.h>
Classes
struct BorderSurface
struct Buffer
struct Button
struct SeatState
struct Surface
Public Member Functions
CWindowDecorator (IWindowDecorationHandler &handler, CConnection &connection, wayland::surface_t const &mainSurface)
void SetState (CSizeInt size, int scale, IShellSurface::StateBitset state)
CSizeInt GetMainSurfaceSize () const
CRectInt GetWindowGeometry () const
CSizeInt CalculateMainSurfaceSize (CSizeInt size, IShellSurface::StateBitset state) const
CSizeInt CalculateFullSurfaceSize (CSizeInt mainSurfaceSize, IShellSurface::StateBitset state) const
bool IsDecorationActive () const
void AddSeat (CSeat *seat)
void RemoveSeat (CSeat *seat)
Private Member Functions
CWindowDecorator (CWindowDecorator const &other)=delete
CWindowDecorator & operator= (CWindowDecorator const &other)=delete
void OnTouchDown (CSeat *seat, std::uint32_t serial, std::uint32_t time, const wayland::surface_t &surface, std::int32_t id, double x, double y) override
void OnPointerEnter (CSeat *seat, std::uint32_t serial, const wayland::surface_t &surface, double surfaceX, double surfaceY) override
void OnPointerLeave (CSeat *seat, std::uint32_t serial, const wayland::surface_t &surface) override
void OnPointerMotion (CSeat *seat, std::uint32_t time, double surfaceX, double surfaceY) override
void OnPointerButton (CSeat *seat, std::uint32_t serial, std::uint32_t time, std::uint32_t button, wayland::pointer_button_state state) override
void Reset (bool reallocate)
void ResetButtons ()
void ResetSurfaces ()
void ResetShm ()
void ReattachSubsurfaces ()
void PositionButtons ()
void AllocateBuffers ()
void Repaint ()
void CommitAllBuffers ()
bool StateHasWindowDecorations (IShellSurface::StateBitset state) const
Buffer GetBuffer (CSizeInt size)
BorderSurface MakeBorderSurface ()
void LoadCursorTheme ()
void UpdateSeatCursor (SeatState &seatState)
void UpdateButtonHoverState ()
void HandleSeatClick (SeatState const &seatState, SurfaceIndex surface, std::uint32_t serial, std::uint32_t button, CPoint position)
Private Member Functions inherited from KODI::WINDOWING::WAYLAND::IRawInputHandlerTouch
virtual void OnTouchUp (CSeat *seat, std::uint32_t serial, std::uint32_t time, std::int32_t id)
virtual void OnTouchMotion (CSeat *seat, std::uint32_t time, std::int32_t id, double x, double y)
virtual void OnTouchCancel (CSeat *seat)
virtual void OnTouchShape (CSeat *seat, std::int32_t id, double major, double minor)
~IRawInputHandlerTouch ()=default
Private Member Functions inherited from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer
virtual void OnPointerAxis (CSeat *seat, std::uint32_t time, wayland::pointer_axis axis, double value)
~IRawInputHandlerPointer ()=default
Private Attributes
IWindowDecorationHandler & m_handler
CSizeInt m_mainSurfaceSize
int m_scale {1}
IShellSurface::StateBitset m_windowState
CRegistry m_registry
wayland::shm_t m_shm
wayland::shm_pool_t m_shmPool
wayland::compositor_t m_compositor
wayland::subcompositor_t m_subcompositor
wayland::surface_t m_mainSurface
std::unique_ptr< KODI::UTILS::POSIX::CSharedMemory > m_memory
std::size_t m_memoryAllocatedSize {}
CCriticalSection m_mutex
std::array< BorderSurface, 4 > m_borderSurfaces
std::set< wayland::buffer_t, WaylandCPtrCompare > m_pendingBuffers
CCriticalSection m_pendingBuffersMutex
std::map< std::uint32_t, SeatState > m_seats
std::vector< Button > m_buttons
wayland::cursor_theme_t m_cursorTheme
std::uint32_t m_buttonColor
Detailed Description
Paint decorations around windows with subcompositing
With Wayland, applications are responsible for drawing borders on their windows themselves (client-side decorations). To keep the impact on the overall architecture low, the Wayland platform implementation uses this very simple renderer to build ugly but fully functional decorations around the Kodi window. Since Kodi as a media center is usually not used in windowed mode anyway (except maybe for development), the impact of the visually not-so-pleasing decorations should be limited. Nice decorations would require more effort and external libraries for proper 2D drawing.
If more platforms decide that client-side decorations would be a good idea to implement, the decorations could also be integrated with the Kodi skin system. Then this class could be removed.
The decorations are positioned around the main surface automatically.
Constructor & Destructor Documentation
CWindowDecorator() [1/2]
CWindowDecorator::CWindowDecorator (IWindowDecorationHandler & handler, CConnection & connection, wayland::surface_t const & mainSurface)
Construct window decorator
Parameters
handler handler for window decoration events
connection connection to get Wayland globals
mainSurface main surface that decorations are constructed around
windowSize full size of the window including decorations
scale scale to use for buffers
state surface state for adjusting decoration appearance
References KODI::WINDOWING::WAYLAND::CRegistry::Bind(), m_borderSurfaces, m_compositor, m_registry, m_shm, m_subcompositor, KODI::WINDOWING::WAYLAND::CRegistry::RequestSingleton(), KODI::WINDOWING::WAYLAND::SURFACE_COUNT, and value.
CWindowDecorator() [2/2]
KODI::WINDOWING::WAYLAND::CWindowDecorator::CWindowDecorator (CWindowDecorator const & other) private delete
Member Function Documentation
AddSeat()
void CWindowDecorator::AddSeat (CSeat * seat)
References KODI::WINDOWING::WAYLAND::CSeat::AddRawInputHandlerPointer(), KODI::WINDOWING::WAYLAND::CSeat::AddRawInputHandlerTouch(), KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName(), and m_seats.
AllocateBuffers()
void CWindowDecorator::AllocateBuffers () private
References GetBuffer(), m_borderSurfaces, m_compositor, m_mainSurfaceSize, and m_scale.
Referenced by Reset().
CalculateFullSurfaceSize()
CSizeInt CWindowDecorator::CalculateFullSurfaceSize (CSizeInt mainSurfaceSize, IShellSurface::StateBitset state) const
Calculate size of full surface including decorations given the size of the main surface and a state
References StateHasWindowDecorations().
CalculateMainSurfaceSize()
CSizeInt CWindowDecorator::CalculateMainSurfaceSize (CSizeInt size, IShellSurface::StateBitset state) const
Calculate size of main surface given the size of the full area including decorations and a state
References StateHasWindowDecorations().
Referenced by SetState().
CommitAllBuffers()
void CWindowDecorator::CommitAllBuffers () private
References m_borderSurfaces, m_pendingBuffers, and m_pendingBuffersMutex.
Referenced by Repaint().
GetBuffer()
CWindowDecorator::Buffer CWindowDecorator::GetBuffer (CSizeInt size) private
References data(), m_memory, m_memoryAllocatedSize, and m_shmPool.
Referenced by AllocateBuffers().
GetMainSurfaceSize()
CSizeInt KODI::WINDOWING::WAYLAND::CWindowDecorator::GetMainSurfaceSize () const inline
Get calculated size of main surface
References m_mainSurfaceSize.
GetWindowGeometry()
CRectInt CWindowDecorator::GetWindowGeometry () const
Get full geometry of the window, including decorations if active
References IsDecorationActive(), m_borderSurfaces, and m_mainSurfaceSize.
HandleSeatClick()
void CWindowDecorator::HandleSeatClick (SeatState const & seatState, SurfaceIndex surface, std::uint32_t serial, std::uint32_t button, CPoint position) private
References KODI::WINDOWING::WAYLAND::CSeat::GetWlSeat(), m_buttons, m_handler, m_mainSurfaceSize, m_mutex, KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowMove(), KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowResize(), KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowShowContextMenu(), KODI::WINDOWING::WAYLAND::CWindowDecorator::SeatState::seat, and KODI::WINDOWING::WAYLAND::SURFACE_TOP.
Referenced by OnPointerButton(), and OnTouchDown().
IsDecorationActive()
bool CWindowDecorator::IsDecorationActive () const
References m_windowState, and StateHasWindowDecorations().
Referenced by GetWindowGeometry(), Reset(), ResetButtons(), ResetShm(), ResetSurfaces(), and SetState().
LoadCursorTheme()
void CWindowDecorator::LoadCursorTheme () private
References m_cursorTheme, m_mutex, m_scale, and m_shm.
Referenced by UpdateSeatCursor().
MakeBorderSurface()
CWindowDecorator::BorderSurface CWindowDecorator::MakeBorderSurface () private
References m_compositor, m_mainSurface, m_subcompositor, KODI::WINDOWING::WAYLAND::CWindowDecorator::BorderSurface::subsurface, KODI::WINDOWING::WAYLAND::CWindowDecorator::BorderSurface::surface, and KODI::WINDOWING::WAYLAND::CWindowDecorator::Surface::wlSurface.
Referenced by ResetSurfaces().
OnPointerButton()
void CWindowDecorator::OnPointerButton (CSeat * seat, std::uint32_t serial, std::uint32_t time, std::uint32_t button, wayland::pointer_button_state state) override private virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer.
References KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName(), HandleSeatClick(), m_seats, and KODI::WINDOWING::WAYLAND::SURFACE_COUNT.
OnPointerEnter()
void CWindowDecorator::OnPointerEnter (CSeat * seat, std::uint32_t serial, const wayland::surface_t & surface, double surfaceX, double surfaceY) override private virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer.
References KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName(), m_borderSurfaces, m_mutex, m_seats, KODI::WINDOWING::WAYLAND::SURFACE_COUNT, UpdateButtonHoverState(), and UpdateSeatCursor().
OnPointerLeave()
void CWindowDecorator::OnPointerLeave (CSeat * seat, std::uint32_t serial, const wayland::surface_t & surface) override private virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer.
References KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName(), m_seats, KODI::WINDOWING::WAYLAND::SURFACE_COUNT, and UpdateButtonHoverState().
OnPointerMotion()
void CWindowDecorator::OnPointerMotion (CSeat * seat, std::uint32_t time, double surfaceX, double surfaceY) override private virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer.
References KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName(), m_seats, KODI::WINDOWING::WAYLAND::SURFACE_COUNT, UpdateButtonHoverState(), and UpdateSeatCursor().
OnTouchDown()
void CWindowDecorator::OnTouchDown (CSeat * seat, std::uint32_t serial, std::uint32_t time, const wayland::surface_t & surface, std::int32_t id, double x, double y) override private virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerTouch.
References KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName(), HandleSeatClick(), m_borderSurfaces, m_mutex, and m_seats.
operator=()
CWindowDecorator & KODI::WINDOWING::WAYLAND::CWindowDecorator::operator= (CWindowDecorator const & other) private delete
PositionButtons()
void CWindowDecorator::PositionButtons () private
References m_borderSurfaces, m_buttons, and KODI::WINDOWING::WAYLAND::SURFACE_TOP.
Referenced by Reset().
ReattachSubsurfaces()
void CWindowDecorator::ReattachSubsurfaces () private
References m_borderSurfaces.
Referenced by Reset().
RemoveSeat()
void CWindowDecorator::RemoveSeat (CSeat * seat)
References KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName(), m_seats, KODI::WINDOWING::WAYLAND::CSeat::RemoveRawInputHandlerPointer(), KODI::WINDOWING::WAYLAND::CSeat::RemoveRawInputHandlerTouch(), and UpdateButtonHoverState().
Repaint()
void CWindowDecorator::Repaint () private
References CommitAllBuffers(), Endian_SwapLE32, m_borderSurfaces, m_buttonColor, m_buttons, KODI::WINDOWING::WAYLAND::SURFACE_BOTTOM, KODI::WINDOWING::WAYLAND::SURFACE_LEFT, KODI::WINDOWING::WAYLAND::SURFACE_RIGHT, and KODI::WINDOWING::WAYLAND::SURFACE_TOP.
Referenced by Reset().
Reset()
void CWindowDecorator::Reset (bool reallocate) private
References AllocateBuffers(), IsDecorationActive(), m_mutex, PositionButtons(), ReattachSubsurfaces(), Repaint(), ResetButtons(), ResetShm(), and ResetSurfaces().
ResetButtons()
void CWindowDecorator::ResetButtons () private
References KODI::WINDOWING::WAYLAND::CWindowDecorator::Button::draw, IsDecorationActive(), m_buttonColor, m_buttons, m_handler, KODI::WINDOWING::WAYLAND::CWindowDecorator::Button::onClick, KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowClose(), KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowMaximize(), and KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowMinimize().
Referenced by Reset().
ResetShm()
void CWindowDecorator::ResetShm () private
References IsDecorationActive(), m_borderSurfaces, m_mainSurfaceSize, m_memory, m_memoryAllocatedSize, m_scale, m_shm, and m_shmPool.
Referenced by Reset().
ResetSurfaces()
void CWindowDecorator::ResetSurfaces () private
References IsDecorationActive(), m_borderSurfaces, and MakeBorderSurface().
Referenced by Reset().
SetState()
void CWindowDecorator::SetState (CSizeInt size, int scale, IShellSurface::StateBitset state)
Set decoration state and size by providing full surface size including decorations
Calculates size of the main surface from size of all surfaces combined (including window decorations) by subtracting the decoration size
Decorations will be disabled if state includes STATE_FULLSCREEN
Call only from main thread
References CalculateMainSurfaceSize(), IsDecorationActive(), CLog::Log(), LOGDEBUG, m_buttonColor, m_cursorTheme, m_mainSurfaceSize, m_mutex, m_scale, m_seats, m_windowState, Reset(), KODI::WINDOWING::WAYLAND::IShellSurface::STATE_ACTIVATED, and UpdateSeatCursor().
StateHasWindowDecorations()
bool CWindowDecorator::StateHasWindowDecorations (IShellSurface::StateBitset state) const private
References m_subcompositor, and KODI::WINDOWING::WAYLAND::IShellSurface::STATE_FULLSCREEN.
Referenced by CalculateFullSurfaceSize(), CalculateMainSurfaceSize(), and IsDecorationActive().
UpdateButtonHoverState()
void CWindowDecorator::UpdateButtonHoverState () private
References m_buttons, m_mutex, m_seats, and KODI::WINDOWING::WAYLAND::SURFACE_TOP.
Referenced by OnPointerEnter(), OnPointerLeave(), OnPointerMotion(), and RemoveSeat().
UpdateSeatCursor()
void CWindowDecorator::UpdateSeatCursor (SeatState & seatState) private
References KODI::WINDOWING::WAYLAND::CWindowDecorator::SeatState::currentSurface, KODI::WINDOWING::WAYLAND::CWindowDecorator::SeatState::cursor, KODI::WINDOWING::WAYLAND::CWindowDecorator::SeatState::cursorName, LoadCursorTheme(), KODI::WINDOWING::WAYLAND::CCursorUtil::LoadFromTheme(), LOGERROR, m_compositor, m_cursorTheme, m_mainSurfaceSize, m_mutex, m_scale, KODI::WINDOWING::WAYLAND::CWindowDecorator::SeatState::pointerEnterSerial, KODI::WINDOWING::WAYLAND::CWindowDecorator::SeatState::seat, KODI::WINDOWING::WAYLAND::CSeat::SetCursor(), KODI::WINDOWING::WAYLAND::SURFACE_COUNT, and CRectGen< T >::ToSize().
Referenced by OnPointerEnter(), OnPointerMotion(), and SetState().
Member Data Documentation
m_borderSurfaces
std::array<BorderSurface, 4> KODI::WINDOWING::WAYLAND::CWindowDecorator::m_borderSurfaces private
Referenced by AllocateBuffers(), CommitAllBuffers(), CWindowDecorator(), GetWindowGeometry(), OnPointerEnter(), OnTouchDown(), PositionButtons(), ReattachSubsurfaces(), Repaint(), ResetShm(), and ResetSurfaces().
m_buttonColor
std::uint32_t KODI::WINDOWING::WAYLAND::CWindowDecorator::m_buttonColor private
Referenced by Repaint(), ResetButtons(), and SetState().
m_buttons
std::vector<Button> KODI::WINDOWING::WAYLAND::CWindowDecorator::m_buttons private
Referenced by HandleSeatClick(), PositionButtons(), Repaint(), ResetButtons(), and UpdateButtonHoverState().
m_compositor
wayland::compositor_t KODI::WINDOWING::WAYLAND::CWindowDecorator::m_compositor private
Referenced by AllocateBuffers(), CWindowDecorator(), MakeBorderSurface(), and UpdateSeatCursor().
m_cursorTheme
wayland::cursor_theme_t KODI::WINDOWING::WAYLAND::CWindowDecorator::m_cursorTheme private
Referenced by LoadCursorTheme(), SetState(), and UpdateSeatCursor().
m_handler
IWindowDecorationHandler& KODI::WINDOWING::WAYLAND::CWindowDecorator::m_handler private
Referenced by HandleSeatClick(), and ResetButtons().
m_mainSurface
wayland::surface_t KODI::WINDOWING::WAYLAND::CWindowDecorator::m_mainSurface private
Referenced by MakeBorderSurface().
m_mainSurfaceSize
CSizeInt KODI::WINDOWING::WAYLAND::CWindowDecorator::m_mainSurfaceSize private
Referenced by AllocateBuffers(), GetMainSurfaceSize(), GetWindowGeometry(), HandleSeatClick(), ResetShm(), SetState(), and UpdateSeatCursor().
m_memory
std::unique_ptr<KODI::UTILS::POSIX::CSharedMemory> KODI::WINDOWING::WAYLAND::CWindowDecorator::m_memory private
Referenced by GetBuffer(), and ResetShm().
m_memoryAllocatedSize
std::size_t KODI::WINDOWING::WAYLAND::CWindowDecorator::m_memoryAllocatedSize {} private
Referenced by GetBuffer(), and ResetShm().
m_mutex
CCriticalSection KODI::WINDOWING::WAYLAND::CWindowDecorator::m_mutex private
Mutex for all surface/button state that is accessed from the event pump thread via seat events and the main thread: m_surfaces, m_buttons, m_windowSize, m_cursorTheme
If size etc. is changing, mutex should be locked for the entire duration of the change until the internal state (surface, button size etc.) is consistent again.
Referenced by HandleSeatClick(), LoadCursorTheme(), OnPointerEnter(), OnTouchDown(), Reset(), SetState(), UpdateButtonHoverState(), and UpdateSeatCursor().
m_pendingBuffers
std::set<wayland::buffer_t, WaylandCPtrCompare> KODI::WINDOWING::WAYLAND::CWindowDecorator::m_pendingBuffers private
Referenced by CommitAllBuffers().
m_pendingBuffersMutex
CCriticalSection KODI::WINDOWING::WAYLAND::CWindowDecorator::m_pendingBuffersMutex private
Referenced by CommitAllBuffers().
m_registry
CRegistry KODI::WINDOWING::WAYLAND::CWindowDecorator::m_registry private
Referenced by CWindowDecorator().
m_scale
int KODI::WINDOWING::WAYLAND::CWindowDecorator::m_scale {1} private
Referenced by AllocateBuffers(), LoadCursorTheme(), ResetShm(), SetState(), and UpdateSeatCursor().
m_seats
std::map<std::uint32_t, SeatState> KODI::WINDOWING::WAYLAND::CWindowDecorator::m_seats private
Referenced by AddSeat(), OnPointerButton(), OnPointerEnter(), OnPointerLeave(), OnPointerMotion(), OnTouchDown(), RemoveSeat(), SetState(), and UpdateButtonHoverState().
m_shm
wayland::shm_t KODI::WINDOWING::WAYLAND::CWindowDecorator::m_shm private
Referenced by CWindowDecorator(), LoadCursorTheme(), and ResetShm().
m_shmPool
wayland::shm_pool_t KODI::WINDOWING::WAYLAND::CWindowDecorator::m_shmPool private
Referenced by GetBuffer(), and ResetShm().
m_subcompositor
wayland::subcompositor_t KODI::WINDOWING::WAYLAND::CWindowDecorator::m_subcompositor private
Referenced by CWindowDecorator(), MakeBorderSurface(), and StateHasWindowDecorations().
m_windowState
IShellSurface::StateBitset KODI::WINDOWING::WAYLAND::CWindowDecorator::m_windowState private
Referenced by IsDecorationActive(), and SetState().
The documentation for this class was generated from the following files:
WindowDecorator.h
WindowDecorator.cpp