Kodi Documentation: Font alignment flags
Font alignment flags
Python » Library - xbmcgui » Control » Subclass - ControlRadioButton
Flags for alignment.
Variables
constexpr int XBFONT_LEFT = 0
Align X left.
constexpr int XBFONT_RIGHT = (1 << 0)
Align X right.
constexpr int XBFONT_CENTER_X = (1 << 1)
Align X center.
constexpr int XBFONT_CENTER_Y = (1 << 2)
Align Y center.
constexpr int XBFONT_TRUNCATED = (1 << 3)
Truncated text from right (text end with ellipses)
constexpr int XBFONT_JUSTIFIED = (1 << 4)
Justify text.
constexpr int XBFONT_TRUNCATED_LEFT = (1 << 5)
Truncated text from left (text start with ellipses)
Detailed Description
Flags for alignment.
Flags are used as bits to have several together, e.g. XBFONT_LEFT | XBFONT_CENTER_Y
Variable Documentation
XBFONT_CENTER_X
constexpr int XBFONT_CENTER_X = (1 << 1) constexpr
Align X center.
Referenced by CGUIFont::ClippedRegionIsEmpty(), CGUIFontTTF::DrawTextInternal(), CGUIControlFactory::GetAlignment(), CGUIControlGroupList::GetAlignOffset(), CGUISpinControl::Process(), CGUIEditControl::ProcessText(), CGUILabel::Render(), CGUIFadeLabelControl::Render(), CGUISpinControl::Render(), CGUITextBox::Render(), CGUIWindowSlideShow::RenderErrorMessage(), CGUITextLayout::RenderOutline(), CGUIListLabel::SetWidth(), CRenderSystemBase::ShowSplash(), CGUILabel::UpdateRenderRect(), and anonymous_namespace{GUIFontTTF.cpp}::ValidateAlignments().
XBFONT_CENTER_Y
constexpr int XBFONT_CENTER_Y = (1 << 2) constexpr
Align Y center.
Referenced by CGUISpinControlEx::AllocResources(), CGUISettingsSliderControl::CGUISettingsSliderControl(), CGUIFont::ClippedRegionIsEmpty(), CGUIFontTTF::DrawTextInternal(), CGUIControlFactory::GetAlignmentY(), CGUIDialogKeyboardGeneric::OnWindowLoaded(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUILabel::Render(), CGUIFadeLabelControl::Render(), CGUITextBox::Render(), CGUITextLayout::Render(), CGUIWindowSlideShow::RenderErrorMessage(), CGUITextLayout::RenderOutline(), CGUITextLayout::RenderScrolling(), and CGUILabel::UpdateRenderRect().
XBFONT_JUSTIFIED
constexpr int XBFONT_JUSTIFIED = (1 << 4) constexpr
Justify text.
Referenced by CGUIControlGroupList::CalculateItemGap(), CGUIFontTTF::DrawTextInternal(), CGUIControlFactory::GetAlignment(), CGUIControlGroupList::GetAlignOffset(), CGUITextLayout::Render(), CGUITextLayout::RenderOutline(), and anonymous_namespace{GUIFontTTF.cpp}::ValidateAlignments().
XBFONT_LEFT
constexpr int XBFONT_LEFT = 0 constexpr
Align X left.
Referenced by CLabelInfo::CLabelInfo(), and CGUIControlFactory::GetAlignment().
XBFONT_RIGHT
constexpr int XBFONT_RIGHT = (1 << 0) constexpr
Align X right.
Referenced by CGUISpinControlEx::AllocResources(), CGUISettingsSliderControl::CGUISettingsSliderControl(), CGUILabel::CheckAndCorrectOverlap(), XBMCAddon::xbmcgui::ControlList::Create(), CGUIControlFactory::Create(), CGUIFontTTF::DrawTextInternal(), CGUIControlFactory::GetAlignment(), CGUIControlGroupList::GetAlignOffset(), CGUISpinControl::Process(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), KODI::GAME::CGUIActivePortList::Refresh(), CGUILabel::Render(), CGUISpinControl::Render(), CGUIListLabel::SetWidth(), KODI::GAME::CGUIGameControllerProvider::UpdateItems(), CGUILabel::UpdateRenderRect(), and anonymous_namespace{GUIFontTTF.cpp}::ValidateAlignments().
XBFONT_TRUNCATED
constexpr int XBFONT_TRUNCATED = (1 << 3) constexpr
Truncated text from right (text end with ellipses)
Referenced by CGUIControlFactory::Create(), CGUIFontTTF::DrawTextInternal(), CGUIButtonControl::ProcessText(), CGUILabel::Render(), and anonymous_namespace{GUIFontTTF.cpp}::ValidateAlignments().
XBFONT_TRUNCATED_LEFT
constexpr int XBFONT_TRUNCATED_LEFT = (1 << 5) constexpr
Truncated text from left (text start with ellipses)
Referenced by CGUIFontTTF::DrawTextInternal(), CGUILabel::Render(), and anonymous_namespace{GUIFontTTF.cpp}::ValidateAlignments().