Kodi Documentation: PVR::CPVRRadioRDSInfoTag::Info Class Reference
PVR::CPVRRadioRDSInfoTag::Info Class Reference
Public Member Functions
Info ()=delete
Info (size_t maxSize, bool prependData)
bool operator== (const Info &right) const
size_t Size () const
size_t MaxSize () const
void Clear ()
void Add (const std::string &text)
const std::string & GetText () const
std::string GetLine (unsigned int line) const
Private Attributes
const size_t m_maxSize = 10
const bool m_prependData = false
std::deque< std::string > m_data
std::string m_infoText
Constructor & Destructor Documentation
Info() [1/2]
PVR::CPVRRadioRDSInfoTag::Info::Info () delete
Info() [2/2]
PVR::CPVRRadioRDSInfoTag::Info::Info (size_t maxSize, bool prependData) inline
Member Function Documentation
Add()
void CPVRRadioRDSInfoTag::Info::Add (const std::string & text)
References data(), g_charsetConverter, CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_RADIOTEXT, text, and PVR::CPVRRadioRDSInfoTag::Trim().
Referenced by PVR::CPVRRadioRDSInfoTag::SetEditorialStaff(), PVR::CPVRRadioRDSInfoTag::SetInfoCinema(), PVR::CPVRRadioRDSInfoTag::SetInfoHoroscope(), PVR::CPVRRadioRDSInfoTag::SetInfoLottery(), PVR::CPVRRadioRDSInfoTag::SetInfoNews(), PVR::CPVRRadioRDSInfoTag::SetInfoNewsLocal(), PVR::CPVRRadioRDSInfoTag::SetInfoOther(), PVR::CPVRRadioRDSInfoTag::SetInfoSport(), PVR::CPVRRadioRDSInfoTag::SetInfoStock(), PVR::CPVRRadioRDSInfoTag::SetInfoWeather(), PVR::CPVRRadioRDSInfoTag::SetProgramServiceText(), and PVR::CPVRRadioRDSInfoTag::SetRadioText().
Clear()
void CPVRRadioRDSInfoTag::Info::Clear ()
Referenced by PVR::CPVRRadioRDSInfoTag::Clear().
GetLine()
std::string PVR::CPVRRadioRDSInfoTag::Info::GetLine (unsigned int line) const inline
References m_data.
Referenced by PVR::CPVRRadioRDSInfoTag::GetRadioText(), and PVR::CPVRRadioRDSInfoTag::SetProgramServiceText().
GetText()
const std::string & PVR::CPVRRadioRDSInfoTag::Info::GetText () const inline
References m_infoText.
Referenced by PVR::CPVRRadioRDSInfoTag::GetEditorialStaff(), PVR::CPVRRadioRDSInfoTag::GetInfoCinema(), PVR::CPVRRadioRDSInfoTag::GetInfoHoroscope(), PVR::CPVRRadioRDSInfoTag::GetInfoLottery(), PVR::CPVRRadioRDSInfoTag::GetInfoNews(), PVR::CPVRRadioRDSInfoTag::GetInfoNewsLocal(), PVR::CPVRRadioRDSInfoTag::GetInfoOther(), PVR::CPVRRadioRDSInfoTag::GetInfoSport(), PVR::CPVRRadioRDSInfoTag::GetInfoStock(), and PVR::CPVRRadioRDSInfoTag::GetInfoWeather().
MaxSize()
size_t PVR::CPVRRadioRDSInfoTag::Info::MaxSize () const inline
References m_maxSize.
Referenced by PVR::CPVRRadioRDSInfoTag::SetProgramServiceText().
operator==()
bool CPVRRadioRDSInfoTag::Info::operator== (const Info & right) const
References m_data, m_infoText, m_maxSize, m_prependData, and right.
Size()
size_t PVR::CPVRRadioRDSInfoTag::Info::Size () const inline
References m_data.
Referenced by PVR::CPVRRadioRDSInfoTag::GetRadioText().
Member Data Documentation
m_data
std::deque<std::string> PVR::CPVRRadioRDSInfoTag::Info::m_data private
Referenced by GetLine(), operator==(), and Size().
m_infoText
std::string PVR::CPVRRadioRDSInfoTag::Info::m_infoText private
Referenced by GetText(), and operator==().
m_maxSize
const size_t PVR::CPVRRadioRDSInfoTag::Info::m_maxSize = 10 private
Referenced by MaxSize(), and operator==().
m_prependData
const bool PVR::CPVRRadioRDSInfoTag::Info::m_prependData = false private
Referenced by operator==().
The documentation for this class was generated from the following files:
PVRRadioRDSInfoTag.h
PVRRadioRDSInfoTag.cpp