Kodi Documentation: ADDON::Interface_GUIDialogYesNo Struct Reference
ADDON::Interface_GUIDialogYesNo Struct Reference
Global gui Add-on to Kodi callback functions.
#include <YesNo.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static bool show_and_get_input_single_text (KODI_HANDLE kodiBase, const char *heading, const char *text, bool *canceled, const char *noLabel, const char *yesLabel)
callback functions from add-on to kodi
static bool show_and_get_input_line_text (KODI_HANDLE kodiBase, const char *heading, const char *line0, const char *line1, const char *line2, const char *noLabel, const char *yesLabel)
static bool show_and_get_input_line_button_text (KODI_HANDLE kodiBase, const char *heading, const char *line0, const char *line1, const char *line2, bool *canceled, const char *noLabel, const char *yesLabel)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/dialogs/YesNo.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIDialogYesNo::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogYesNo, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
Init()
void ADDON::Interface_GUIDialogYesNo::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogYesNo, AddonToKodiFuncTable_Addon::kodi_gui, show_and_get_input_line_button_text(), AddonToKodiFuncTable_kodi_gui_dialogYesNo::show_and_get_input_line_button_text, show_and_get_input_line_text(), AddonToKodiFuncTable_kodi_gui_dialogYesNo::show_and_get_input_line_text, show_and_get_input_single_text(), AddonToKodiFuncTable_kodi_gui_dialogYesNo::show_and_get_input_single_text, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
show_and_get_input_line_button_text()
bool ADDON::Interface_GUIDialogYesNo::show_and_get_input_line_button_text (KODI_HANDLE kodiBase, const char * heading, const char * line0, const char * line1, const char * line2, bool * canceled, const char * noLabel, const char * yesLabel) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and KODI::MESSAGING::HELPERS::ShowYesNoDialogLines().
Referenced by Init().
show_and_get_input_line_text()
bool ADDON::Interface_GUIDialogYesNo::show_and_get_input_line_text (KODI_HANDLE kodiBase, const char * heading, const char * line0, const char * line1, const char * line2, const char * noLabel, const char * yesLabel) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and KODI::MESSAGING::HELPERS::ShowYesNoDialogLines().
Referenced by Init().
show_and_get_input_single_text()
bool ADDON::Interface_GUIDialogYesNo::show_and_get_input_single_text (KODI_HANDLE kodiBase, const char * heading, const char * text, bool * canceled, const char * noLabel, const char * yesLabel) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, KODI::MESSAGING::HELPERS::ShowYesNoDialogText(), and text.
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/dialogs/YesNo.h
YesNo.cpp