Kodi Documentation: KODI::WINDOWING::WAYLAND::CConnection Class Reference
KODI::WINDOWING::WAYLAND::CConnection Class Reference
#include <Connection.h>
Public Member Functions
CConnection ()
bool HasDisplay () const
wayland::display_t & GetDisplay ()
Private Attributes
std::unique_ptr< wayland::display_t > m_display
Detailed Description
Connection to Wayland compositor
Constructor & Destructor Documentation
CConnection()
CConnection::CConnection ()
References err(), CLog::Log(), LOGERROR, and m_display.
Member Function Documentation
GetDisplay()
wayland::display_t & CConnection::GetDisplay ()
References m_display.
Referenced by KODI::WINDOWING::WAYLAND::CRegistry::Bind(), KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell::TryCreate(), and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6::TryCreate().
HasDisplay()
bool CConnection::HasDisplay () const
References m_display.
Member Data Documentation
m_display
std::unique_ptr<wayland::display_t> KODI::WINDOWING::WAYLAND::CConnection::m_display private
Referenced by CConnection(), GetDisplay(), and HasDisplay().
The documentation for this class was generated from the following files:
Connection.h
Connection.cpp