Kodi Documentation: CSpeechRecognitionAndroid Class Reference
CSpeechRecognitionAndroid Class Reference
#include <SpeechRecognitionAndroid.h>
Public Member Functions
CSpeechRecognitionAndroid (const CJNIContext &context)
~CSpeechRecognitionAndroid () override
void StartSpeechRecognition (const std::shared_ptr< speech::ISpeechRecognitionListener > &listener) override
void SpeechRecognitionDone (jni::CJNIXBMCSpeechRecognitionListener *listener) override
Public Member Functions inherited from ISpeechRecognitionCallback
virtual ~ISpeechRecognitionCallback ()=default
Public Member Functions inherited from speech::ISpeechRecognition
virtual ~ISpeechRecognition ()=default
Private Member Functions
CSpeechRecognitionAndroid ()=delete
Static Private Member Functions
static void RegisterSpeechRecognitionListener (void *thiz)
Private Attributes
const CJNIContext & m_context
CCriticalSection m_speechRecognitionListenersMutex
std::vector< std::unique_ptr< jni::CJNIXBMCSpeechRecognitionListener > > m_speechRecognitionListeners
Additional Inherited Members
Static Public Member Functions inherited from speech::ISpeechRecognition
static std::shared_ptr< speech::ISpeechRecognition > CreateInstance ()
Constructor & Destructor Documentation
CSpeechRecognitionAndroid() [1/2]
CSpeechRecognitionAndroid::CSpeechRecognitionAndroid (const CJNIContext & context) explicit
~CSpeechRecognitionAndroid()
CSpeechRecognitionAndroid::~CSpeechRecognitionAndroid () override
CSpeechRecognitionAndroid() [2/2]
CSpeechRecognitionAndroid::CSpeechRecognitionAndroid () private delete
Member Function Documentation
RegisterSpeechRecognitionListener()
void CSpeechRecognitionAndroid::RegisterSpeechRecognitionListener (void * thiz) static private
References m_context, m_speechRecognitionListeners, and m_speechRecognitionListenersMutex.
Referenced by StartSpeechRecognition().
SpeechRecognitionDone()
void CSpeechRecognitionAndroid::SpeechRecognitionDone (jni::CJNIXBMCSpeechRecognitionListener * listener) override virtual
Implements ISpeechRecognitionCallback.
References listener, m_speechRecognitionListeners, and m_speechRecognitionListenersMutex.
StartSpeechRecognition()
void CSpeechRecognitionAndroid::StartSpeechRecognition (const std::shared_ptr< speech::ISpeechRecognitionListener > & listener) override virtual
Implements speech::ISpeechRecognition.
References speech::RecognitionError::INSUFFICIENT_PERMISSIONS, listener, LOGERROR, m_context, m_speechRecognitionListeners, m_speechRecognitionListenersMutex, speech::ISpeechRecognitionListener::OnError(), RegisterSpeechRecognitionListener(), jni::CJNIMainActivity::runNativeOnUiThread(), and speech::RecognitionError::SERVICE_NOT_AVAILABLE.
Member Data Documentation
m_context
const CJNIContext& CSpeechRecognitionAndroid::m_context private
Referenced by RegisterSpeechRecognitionListener(), and StartSpeechRecognition().
m_speechRecognitionListeners
std::vector<std::unique_ptr<jni::CJNIXBMCSpeechRecognitionListener> > CSpeechRecognitionAndroid::m_speechRecognitionListeners private
Referenced by RegisterSpeechRecognitionListener(), SpeechRecognitionDone(), and StartSpeechRecognition().
m_speechRecognitionListenersMutex
CCriticalSection CSpeechRecognitionAndroid::m_speechRecognitionListenersMutex private
Referenced by RegisterSpeechRecognitionListener(), SpeechRecognitionDone(), and StartSpeechRecognition().
The documentation for this class was generated from the following files:
SpeechRecognitionAndroid.h
SpeechRecognitionAndroid.cpp