Kodi Documentation: kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT > Class Template Reference
kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT > Class Template Reference
#include <PeripheralUtils.h>
Static Public Member Functions
static void ToStructs (const std::vector< THE_CLASS > &vecObjects, THE_STRUCT **pStructs)
static void ToStructs (const std::vector< THE_CLASS * > &vecObjects, THE_STRUCT **pStructs)
static void ToStructs (const std::vector< std::shared_ptr< THE_CLASS > > &vecObjects, THE_STRUCT **pStructs)
static void FreeStructs (unsigned int structCount, THE_STRUCT *structs)
Detailed Description
template<class THE_CLASS, typename THE_STRUCT>
class kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >
Utility class to manipulate arrays of peripheral types.
Member Function Documentation
FreeStructs()
template<class THE_CLASS , typename THE_STRUCT > static void kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::FreeStructs (unsigned int structCount, THE_STRUCT * structs) inline static
References PERIPHERAL_SAFE_DELETE_ARRAY.
Referenced by kodi::addon::CInstancePeripheral::ADDON_FreeEvents(), kodi::addon::CInstancePeripheral::ADDON_FreeFeatures(), kodi::addon::CInstancePeripheral::ADDON_FreePrimitives(), kodi::addon::CInstancePeripheral::ADDON_FreeScanResults(), and PERIPHERALS::CPeripheralAddon::SetIgnoredPrimitives().
ToStructs() [1/3]
template<class THE_CLASS , typename THE_STRUCT > static void kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::ToStructs (const std::vector< std::shared_ptr< THE_CLASS > > & vecObjects, THE_STRUCT ** pStructs) inline static
ToStructs() [2/3]
template<class THE_CLASS , typename THE_STRUCT > static void kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::ToStructs (const std::vector< THE_CLASS * > & vecObjects, THE_STRUCT ** pStructs) inline static
ToStructs() [3/3]
template<class THE_CLASS , typename THE_STRUCT > static void kodi::addon::PeripheralVector< THE_CLASS, THE_STRUCT >::ToStructs (const std::vector< THE_CLASS > & vecObjects, THE_STRUCT ** pStructs) inline static
Referenced by kodi::addon::CInstancePeripheral::ADDON_GetEvents(), kodi::addon::CInstancePeripheral::ADDON_GetFeatures(), kodi::addon::CInstancePeripheral::ADDON_GetIgnoredPrimitives(), kodi::addon::CInstancePeripheral::ADDON_PerformDeviceScan(), and PERIPHERALS::CPeripheralAddon::SetIgnoredPrimitives().
The documentation for this class was generated from the following file:
PeripheralUtils.h