Kodi Documentation: COutputShader Class Reference
COutputShader Class Reference
#include <WinVideoFilter.h>
Classes
struct Vertex
Public Member Functions
COutputShader ()=default
~COutputShader ()=default
void ApplyEffectParameters (CD3DEffect &effect, unsigned sourceWidth, unsigned sourceHeight)
void GetDefines (DefinesMap &map) const
bool Create (bool useLUT, bool useDithering, int ditherDepth, bool toneMapping, ETONEMAPMETHOD toneMethod, bool HLGtoPQ)
void Render (CD3DTexture &sourceTexture, CRect sourceRect, const CPoint points[4], CD3DTexture &target, unsigned range=0, float contrast=0.5f, float brightness=0.5f)
void Render (CD3DTexture &sourceTexture, CRect sourceRect, CRect destRect, CD3DTexture &target, unsigned range=0, float contrast=0.5f, float brightness=0.5f)
void SetLUT (int lutSize, ID3D11ShaderResourceView *pLUTView)
void SetDisplayMetadata (bool hasDisplayMetadata, AVMasteringDisplayMetadata displayMetadata, bool hasLightMetadata, AVContentLightMetadata lightMetadata)
void SetToneMapParam (ETONEMAPMETHOD method, float param)
std::string GetDebugInfo ()
Static Public Member Functions
static bool CreateLUTView (int lutSize, uint16_t *lutData, bool isRGB, ID3D11ShaderResourceView **ppLUTView)
Private Member Functions
bool HasLUT () const
void PrepareParameters (unsigned sourceWidth, unsigned sourceHeight, CRect sourceRect, const CPoint points[4])
void SetShaderParameters (CD3DTexture &sourceTexture, unsigned range, float contrast, float brightness)
void CreateDitherView ()
Private Attributes
bool m_useLut = false
bool m_useDithering = false
bool m_toneMapping = false
bool m_useHLGtoPQ = false
bool m_hasDisplayMetadata = false
bool m_hasLightMetadata = false
unsigned m_sourceWidth = 0
unsigned m_sourceHeight = 0
int m_lutSize = 0
int m_ditherDepth = 0
ETONEMAPMETHOD m_toneMappingMethod = VS_TONEMAPMETHOD_OFF
float m_toneMappingParam = 1.0f
float m_toneMappingDebug = .0f
CRect m_sourceRect = {}
CPoint m_destPoints [4] = {}
Microsoft::WRL::ComPtr< ID3D11ShaderResourceView > m_pDitherView = nullptr
Microsoft::WRL::ComPtr< ID3D11ShaderResourceView > m_pLUTView = nullptr
AVMasteringDisplayMetadata m_displayMetadata = {}
AVContentLightMetadata m_lightMetadata = {}
Additional Inherited Members
Protected Member Functions inherited from CWinShader
CWinShader ()=default
virtual ~CWinShader ()=default
virtual bool CreateVertexBuffer (unsigned int vertCount, unsigned int vertSize)
virtual bool LockVertexBuffer (void **data)
virtual bool UnlockVertexBuffer ()
virtual bool LoadEffect (const std::string &filename, DefinesMap *defines)
virtual bool Execute (const std::vector< CD3DTexture * > &targets, unsigned int vertexIndexStep)
virtual void SetStepParams (unsigned stepIndex)
virtual bool CreateInputLayout (D3D11_INPUT_ELEMENT_DESC *layout, unsigned numElements)
Protected Attributes inherited from CWinShader
CD3DEffect m_effect
CD3DTexture * m_target = nullptr
Constructor & Destructor Documentation
COutputShader()
COutputShader::COutputShader () explicit default
~COutputShader()
COutputShader::~COutputShader () default
Member Function Documentation
ApplyEffectParameters()
void COutputShader::ApplyEffectParameters (CD3DEffect & effect, unsigned sourceWidth, unsigned sourceHeight)
References dither_size, CToneMappers::GetLuminanceValue(), CConvertMatrix::GetRGBYuvCoefs(), HasLUT(), m_displayMetadata, m_ditherDepth, m_hasDisplayMetadata, m_hasLightMetadata, m_lightMetadata, m_lutSize, m_pDitherView, m_pLUTView, m_toneMapping, m_toneMappingDebug, m_toneMappingMethod, m_toneMappingParam, m_useDithering, m_useLut, CD3DEffect::SetFloatArray(), CD3DEffect::SetResources(), CD3DEffect::SetScalar(), VS_TONEMAPMETHOD_ACES, VS_TONEMAPMETHOD_HABLE, and VS_TONEMAPMETHOD_REINHARD.
Referenced by SetShaderParameters().
Create()
bool COutputShader::Create (bool useLUT, bool useDithering, int ditherDepth, bool toneMapping, ETONEMAPMETHOD toneMethod, bool HLGtoPQ)
References CreateDitherView(), CWinShader::CreateInputLayout(), CWinShader::CreateVertexBuffer(), GetDefines(), CWinShader::LoadEffect(), LOGERROR, m_ditherDepth, m_toneMapping, m_toneMappingMethod, m_useHLGtoPQ, and m_useLut.
CreateDitherView()
void COutputShader::CreateDitherView () private
References dither_matrix, dither_size, FAILED, DX::DeviceResources::Get(), LOGDEBUG, m_pDitherView, and m_useDithering.
Referenced by Create().
CreateLUTView()
bool COutputShader::CreateLUTView (int lutSize, uint16_t * lutData, bool isRGB, ID3D11ShaderResourceView ** ppLUTView) static
References KODI::MEMORY::AlignedFree(), KODI::MEMORY::AlignedMalloc(), FAILED, DX::DeviceResources::Get(), and LOGDEBUG.
Referenced by CRendererBase::OnCMSConfigChanged().
GetDebugInfo()
std::string COutputShader::GetDebugInfo ()
References m_ditherDepth, m_lutSize, m_toneMapping, m_toneMappingDebug, m_toneMappingMethod, m_toneMappingParam, m_useDithering, m_useHLGtoPQ, m_useLut, VS_TONEMAPMETHOD_ACES, VS_TONEMAPMETHOD_HABLE, and VS_TONEMAPMETHOD_REINHARD.
GetDefines()
void COutputShader::GetDefines (DefinesMap & map) const
References m_toneMapping, m_toneMappingMethod, m_useDithering, m_useHLGtoPQ, m_useLut, VS_TONEMAPMETHOD_ACES, VS_TONEMAPMETHOD_HABLE, and VS_TONEMAPMETHOD_REINHARD.
Referenced by Create().
HasLUT()
bool COutputShader::HasLUT () const inline private
References m_lutSize, and m_pLUTView.
Referenced by ApplyEffectParameters().
PrepareParameters()
void COutputShader::PrepareParameters (unsigned sourceWidth, unsigned sourceHeight, CRect sourceRect, const CPoint points[4]) private
References CWinShader::LockVertexBuffer(), m_destPoints, m_sourceHeight, m_sourceRect, m_sourceWidth, COutputShader::Vertex::tu, COutputShader::Vertex::tv, CWinShader::UnlockVertexBuffer(), COutputShader::Vertex::x, CPointGen< T >::x, CRectGen< T >::x1, CRectGen< T >::x2, COutputShader::Vertex::y, CPointGen< T >::y, CRectGen< T >::y1, CRectGen< T >::y2, and COutputShader::Vertex::z.
Referenced by Render().
Render() [1/2]
void COutputShader::Render (CD3DTexture & sourceTexture, CRect sourceRect, const CPoint points[4], CD3DTexture & target, unsigned range = 0, float contrast = 0.5f, float brightness = 0.5f)
References CWinShader::Execute(), CD3DTexture::GetHeight(), CD3DTexture::GetWidth(), PrepareParameters(), and SetShaderParameters().
Referenced by Render().
Render() [2/2]
void COutputShader::Render (CD3DTexture & sourceTexture, CRect sourceRect, CRect destRect, CD3DTexture & target, unsigned range = 0, float contrast = 0.5f, float brightness = 0.5f)
References Render(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
SetDisplayMetadata()
void COutputShader::SetDisplayMetadata (bool hasDisplayMetadata, AVMasteringDisplayMetadata displayMetadata, bool hasLightMetadata, AVContentLightMetadata lightMetadata)
References m_displayMetadata, m_hasDisplayMetadata, m_hasLightMetadata, and m_lightMetadata.
SetLUT()
void COutputShader::SetLUT (int lutSize, ID3D11ShaderResourceView * pLUTView)
References m_lutSize, and m_pLUTView.
SetShaderParameters()
void COutputShader::SetShaderParameters (CD3DTexture & sourceTexture, unsigned range, float contrast, float brightness) private
References ApplyEffectParameters(), DX::DeviceResources::Get(), CD3DTexture::GetAddressOfSRV(), CD3DTexture::GetHeight(), CD3DTexture::GetWidth(), CWinShader::m_effect, CD3DEffect::SetFloatArray(), CD3DEffect::SetResources(), and CD3DEffect::SetTechnique().
Referenced by Render().
SetToneMapParam()
void COutputShader::SetToneMapParam (ETONEMAPMETHOD method, float param)
References m_toneMappingMethod, and m_toneMappingParam.
Member Data Documentation
m_destPoints
CPoint COutputShader::m_destPoints[4] = {} private
Referenced by PrepareParameters().
m_displayMetadata
AVMasteringDisplayMetadata COutputShader::m_displayMetadata = {} private
Referenced by ApplyEffectParameters(), and SetDisplayMetadata().
m_ditherDepth
int COutputShader::m_ditherDepth = 0 private
Referenced by ApplyEffectParameters(), Create(), and GetDebugInfo().
m_hasDisplayMetadata
bool COutputShader::m_hasDisplayMetadata = false private
Referenced by ApplyEffectParameters(), and SetDisplayMetadata().
m_hasLightMetadata
bool COutputShader::m_hasLightMetadata = false private
Referenced by ApplyEffectParameters(), and SetDisplayMetadata().
m_lightMetadata
AVContentLightMetadata COutputShader::m_lightMetadata = {} private
Referenced by ApplyEffectParameters(), and SetDisplayMetadata().
m_lutSize
int COutputShader::m_lutSize = 0 private
Referenced by ApplyEffectParameters(), GetDebugInfo(), HasLUT(), and SetLUT().
m_pDitherView
Microsoft::WRL::ComPtr<ID3D11ShaderResourceView> COutputShader::m_pDitherView = nullptr private
Referenced by ApplyEffectParameters(), and CreateDitherView().
m_pLUTView
Microsoft::WRL::ComPtr<ID3D11ShaderResourceView> COutputShader::m_pLUTView = nullptr private
Referenced by ApplyEffectParameters(), HasLUT(), and SetLUT().
m_sourceHeight
unsigned COutputShader::m_sourceHeight = 0 private
Referenced by PrepareParameters().
m_sourceRect
CRect COutputShader::m_sourceRect = {} private
Referenced by PrepareParameters().
m_sourceWidth
unsigned COutputShader::m_sourceWidth = 0 private
Referenced by PrepareParameters().
m_toneMapping
bool COutputShader::m_toneMapping = false private
Referenced by ApplyEffectParameters(), Create(), GetDebugInfo(), and GetDefines().
m_toneMappingDebug
float COutputShader::m_toneMappingDebug = .0f private
Referenced by ApplyEffectParameters(), and GetDebugInfo().
m_toneMappingMethod
ETONEMAPMETHOD COutputShader::m_toneMappingMethod = VS_TONEMAPMETHOD_OFF private
Referenced by ApplyEffectParameters(), Create(), GetDebugInfo(), GetDefines(), and SetToneMapParam().
m_toneMappingParam
float COutputShader::m_toneMappingParam = 1.0f private
Referenced by ApplyEffectParameters(), GetDebugInfo(), and SetToneMapParam().
m_useDithering
bool COutputShader::m_useDithering = false private
Referenced by ApplyEffectParameters(), CreateDitherView(), GetDebugInfo(), and GetDefines().
m_useHLGtoPQ
bool COutputShader::m_useHLGtoPQ = false private
Referenced by Create(), GetDebugInfo(), and GetDefines().
m_useLut
bool COutputShader::m_useLut = false private
Referenced by ApplyEffectParameters(), Create(), GetDebugInfo(), and GetDefines().
The documentation for this class was generated from the following files:
WinVideoFilter.h
WinVideoFilter.cpp