Kodi Documentation: MathUtils Namespace Reference
MathUtils Namespace Reference
Math utility class. Note that the test() routine should return true for all implementations.
Functions
int round_int (double x)
Round to nearest integer. This routine does fast rounding to the nearest integer. In the case (k + 0.5 for any integer k) we round up to k+1, and in all other instances we should return the nearest integer. Thus, { -1.5, -0.5, 0.5, 1.5 } is rounded to { -1, 0, 1, 2 }. It preserves the property that round(k) - round(k-1) = 1 for all doubles k.
int truncate_int (double x)
Truncate to nearest integer. This routine does fast truncation to an integer. It should simply drop the fractional portion of the floating point number.
int64_t abs (int64_t a)
unsigned bitcount (unsigned v)
void hack ()
template<typename FloatT >
bool FloatEquals (FloatT f1, FloatT f2, FloatT maxDelta)
template<typename T , std::enable_if_t< std::is_floating_point< T >::value, bool > = true>
T RoundF (const T value, const T multiple)
Round a floating point number to nearest multiple.
Detailed Description
Math utility class. Note that the test() routine should return true for all implementations.
See http://ldesoras.free.fr/doc/articles/rounding_en.pdf for an explanation of the technique used on x86.
Function Documentation
abs()
int64_t MathUtils::abs (int64_t a) inline
Referenced by hack(), and TEST().
bitcount()
unsigned MathUtils::bitcount (unsigned v) inline
Referenced by TEST().
FloatEquals()
template<typename FloatT > bool MathUtils::FloatEquals (FloatT f1, FloatT f2, FloatT maxDelta) inline
Compare two floating-point numbers for equality and regard them as equal if their difference is below a given threshold.
It is usually not useful to compare float numbers for equality with the standard operator== since very close numbers might have different representations.
Referenced by anonymous_namespace{TestConversionMatrix.cpp}::CompareMatrices(), anonymous_namespace{WinSystemWayland.cpp}::FindMatchingCustomResolution(), CResolutionUtils::FindResolutionFromWhitelist(), and CVideoPlayerVideo::OutputPicture().
hack()
void MathUtils::hack () inline
References abs(), round_int(), and truncate_int().
round_int()
int MathUtils::round_int (double x) inline
Round to nearest integer. This routine does fast rounding to the nearest integer. In the case (k + 0.5 for any integer k) we round up to k+1, and in all other instances we should return the nearest integer. Thus, { -1.5, -0.5, 0.5, 1.5 } is rounded to { -1, 0, 1, 2 }. It preserves the property that round(k) - round(k-1) = 1 for all doubles k.
Make sure MathUtils::test() returns true for each implementation.
See also
truncate_int, test
Referenced by CGUIFontTTF::CacheCharacter(), CBaseRenderer::CalcDestRect(), CVideoPlayerVideo::CalcFrameRate(), KODI::RETRO::CRenderUtils::CalcNormalRenderRect(), CGUIFontTTF::DrawTextInternal(), CVideoSyncAndroid::FrameCallback(), PVR::CGUIEPGGridContainer::GetChannelScrollOffset(), CGUISliderControl::GetDescription(), CFreeTypeLibrary::GetFont(), CGUISliderControl::GetIntValue(), PVR::CGUIEPGGridContainer::GetProgrammeScrollOffset(), CSeekHandler::GetSeekSize(), hack(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), CMusicDatabase::ImportSongHistory(), CVideoSyncIos::IosVblankHandler(), CGUIFontTTF::Load(), CAlbum::Load(), CGUIBaseContainer::OnMouseEvent(), PVR::CGUIEPGGridContainer::OnMouseEvent(), CGUITextBox::Process(), PVR::CGUIEPGGridContainer::Process(), CResolutionUtils::RefreshWeight(), CGUIFontTTF::RenderCharacter(), CVideoSyncD3D::Run(), CAELimiter::Run(), KODI::RETRO::CReversiblePlayback::SeekTimeMs(), CGUISliderControl::SendClick(), CRenderSystemDX::SetScissors(), CRenderSystemGL::SetScissors(), CRenderSystemGLES::SetScissors(), VDPAU::CDecoder::SetWidthHeight(), TEST(), CVideoReferenceClock::TimeOfNextVblank(), CConvolutionKernel::ToIntFract(), CConvolutionKernel::ToUint8(), CVideoSyncTVos::TVosVblankHandler(), CVideoReferenceClock::UpdateClockInternal(), CDVDClock::UpdateFramerate(), KODI::RETRO::CReversiblePlayback::UpdateMemoryStream(), KODI::RETRO::CReversiblePlayback::UpdatePlaybackStats(), and CVideoSyncOsx::VblankHandler().
RoundF()
template<typename T , std::enable_if_t< std::is_floating_point< T >::value, bool > = true> T MathUtils::RoundF (const T value, const T multiple) inline
Round a floating point number to nearest multiple.
Parameters
value The value to round
multiple The multiple
Returns
The rounded value
References value.
Referenced by KODI::UTILS::MOVING_SPEED::CMovingSpeed::GetUpdatedDistance(), JSONRPC::CPlayerOperations::SetAudioDelay(), and CGUISliderControl::SetFromPosition().
truncate_int()
int MathUtils::truncate_int (double x) inline
Truncate to nearest integer. This routine does fast truncation to an integer. It should simply drop the fractional portion of the floating point number.
Make sure MathUtils::test() returns true for each implementation.
See also
round_int, test
Referenced by hack(), CGUIFontTTF::RenderCharacter(), and TEST().