Kodi Documentation: XFILE::CFileDirectoryFactory Class Reference
XFILE::CFileDirectoryFactory Class Reference
#include <FileDirectoryFactory.h>
Public Member Functions
CFileDirectoryFactory (void)
virtual ~CFileDirectoryFactory (void)
Static Public Member Functions
static IFileDirectory * Create (const CURL &url, CFileItem *pItem, const std::string &strMask="")
Constructor & Destructor Documentation
CFileDirectoryFactory()
CFileDirectoryFactory::CFileDirectoryFactory (void) default
~CFileDirectoryFactory()
CFileDirectoryFactory::~CFileDirectoryFactory (void) virtual default
Member Function Documentation
Create()
IFileDirectory * CFileDirectoryFactory::Create (const CURL & url, CFileItem * pItem, const std::string & strMask = "") static
Check available binary addons which can contain files with underlaid folders / files. Currently in vfs and audiodecoder addons.
Note
The file extensions are absolutely necessary for these in order to identify the associated add-on.
Scan here about audiodecoder addons.
Note
: Do not check audio decoder files that are already open, they cannot contain any further sub-folders.
Scan here about VFS addons.
References ADDON::CVFSEntryIFileDirectoryWrapper::ContainsFiles(), URIUtils::CreateArchivePath(), XFILE::DIR_FLAG_DEFAULTS, XFILE::CISO9660Directory::Exists(), ADDON::CVFSAddonCache::GetAddonInstances(), XFILE::IDirectory::GetDirectory(), XFILE::CDirectory::GetDirectory(), CFileItem::GetEndOffset(), URIUtils::GetExtension(), KODI::ADDONS::CExtsMimeSupportList::GetExtensionSupportedAddonInfos(), CServiceBroker::GetExtsMimeSupportList(), CFileItem::GetPath(), CFileItem::GetURL(), CServiceBroker::GetVFSAddonCache(), CFileItem::HasMusicInfoTag(), URIUtils::HasSlashAtEnd(), CServiceBroker::IsAddonInterfaceUp(), KODI::MUSIC::IsAudioBook(), CFileItem::IsDiscImage(), CURL::IsFileType(), KODI::PLAYLIST::CPlayListFactory::IsPlaylist(), CURL::IsProtocol(), CFileItem::IsRSS(), KODI_ADDON_AUDIODECODER_TRACK_EXT, CLog::Log(), LOGINFO, CGUIListItem::m_bIsFolder, CFileItem::m_idepth, ADDON::CVFSEntryIFileDirectoryWrapper::m_items, playlist, CFileItem::SetLabel(), CFileItem::SetLabelPreformatted(), CFileItem::SetPath(), CFileItem::SetURL(), and CFileItemList::Size().
Referenced by XFILE::CDirectoryFactory::Create(), CFileOperationJob::DoProcessFolder(), XFILE::CDirectory::FilterFileDirectories(), XFILE::CSmartPlaylistDirectory::GetDirectory(), CGUIMediaWindow::OnClick(), and CGUIWindowFileManager::OnClick().
The documentation for this class was generated from the following files:
FileDirectoryFactory.h
FileDirectoryFactory.cpp