Kodi Documentation: KODI::KEYMAP::CIRTranslator Class Reference
KODI::KEYMAP::CIRTranslator Class Reference
#include <IRTranslator.h>
Public Member Functions
CIRTranslator ()=default
void Load (const std::string &irMapName)
Loads Lircmap.xml/IRSSmap.xml.
void Clear ()
Clears the map.
unsigned int TranslateButton (const std::string &szDevice, const std::string &szButton)
Static Public Member Functions
static uint32_t TranslateString (std::string strButton)
static uint32_t TranslateUniversalRemoteString (const std::string &szButton)
Private Types
using IRButtonMap = std::map< std::string, std::string >
Private Member Functions
bool LoadIRMap (const std::string &irMapPath)
void MapRemote (tinyxml2::XMLNode *pRemote, const std::string &szDevice)
Private Attributes
std::map< std::string, std::shared_ptr< IRButtonMap > > m_irRemotesMap
Member Typedef Documentation
IRButtonMap
using KODI::KEYMAP::CIRTranslator::IRButtonMap = std::map<std::string, std::string> private
Constructor & Destructor Documentation
CIRTranslator()
KODI::KEYMAP::CIRTranslator::CIRTranslator () default
Member Function Documentation
Clear()
void CIRTranslator::Clear ()
Clears the map.
References m_irRemotesMap.
Referenced by Load().
Load()
void CIRTranslator::Load (const std::string & irMapName)
Loads Lircmap.xml/IRSSmap.xml.
References URIUtils::AddFileToFolder(), Clear(), CFileUtils::Exists(), CServiceBroker::GetSettingsComponent(), LoadIRMap(), CLog::Log(), LOGDEBUG, LOGERROR, and success.
Referenced by CIRServerSuite::HandleRemoteEvent(), and CIRServerSuite::Process().
LoadIRMap()
bool CIRTranslator::LoadIRMap (const std::string & irMapPath) private
References URIUtils::GetFileName(), CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGERROR, LOGINFO, and MapRemote().
Referenced by Load().
MapRemote()
void CIRTranslator::MapRemote (tinyxml2::XMLNode * pRemote, const std::string & szDevice) private
References CLog::Log(), LOGINFO, and m_irRemotesMap.
Referenced by LoadIRMap().
TranslateButton()
unsigned int CIRTranslator::TranslateButton (const std::string & szDevice, const std::string & szButton)
References m_irRemotesMap, TranslateString(), and TranslateUniversalRemoteString().
Referenced by CIRServerSuite::HandleRemoteEvent().
TranslateString()
uint32_t CIRTranslator::TranslateString (std::string strButton) static
References CLog::Log(), LOGERROR, XINPUT_IR_REMOTE_0, XINPUT_IR_REMOTE_1, XINPUT_IR_REMOTE_2, XINPUT_IR_REMOTE_3, XINPUT_IR_REMOTE_4, XINPUT_IR_REMOTE_5, XINPUT_IR_REMOTE_6, XINPUT_IR_REMOTE_7, XINPUT_IR_REMOTE_8, XINPUT_IR_REMOTE_9, XINPUT_IR_REMOTE_BACK, XINPUT_IR_REMOTE_BLUE, XINPUT_IR_REMOTE_CHANNEL_MINUS, XINPUT_IR_REMOTE_CHANNEL_PLUS, XINPUT_IR_REMOTE_CLEAR, XINPUT_IR_REMOTE_CONTENTS_MENU, XINPUT_IR_REMOTE_DISPLAY, XINPUT_IR_REMOTE_DOWN, XINPUT_IR_REMOTE_DVD_MENU, XINPUT_IR_REMOTE_EJECT, XINPUT_IR_REMOTE_ENTER, XINPUT_IR_REMOTE_EPG_SEARCH, XINPUT_IR_REMOTE_FORWARD, XINPUT_IR_REMOTE_GREEN, XINPUT_IR_REMOTE_GUIDE, XINPUT_IR_REMOTE_HASH, XINPUT_IR_REMOTE_INFO, XINPUT_IR_REMOTE_LANGUAGE, XINPUT_IR_REMOTE_LEFT, XINPUT_IR_REMOTE_LIVE_RADIO, XINPUT_IR_REMOTE_LIVE_TV, XINPUT_IR_REMOTE_MENU, XINPUT_IR_REMOTE_MUTE, XINPUT_IR_REMOTE_MY_MUSIC, XINPUT_IR_REMOTE_MY_PICTURES, XINPUT_IR_REMOTE_MY_TV, XINPUT_IR_REMOTE_MY_VIDEOS, XINPUT_IR_REMOTE_PAUSE, XINPUT_IR_REMOTE_PLAY, XINPUT_IR_REMOTE_PLAYLIST, XINPUT_IR_REMOTE_POWER, XINPUT_IR_REMOTE_PRINT, XINPUT_IR_REMOTE_RECORD, XINPUT_IR_REMOTE_RECORDED_TV, XINPUT_IR_REMOTE_RED, XINPUT_IR_REMOTE_REVERSE, XINPUT_IR_REMOTE_RIGHT, XINPUT_IR_REMOTE_ROOT_MENU, XINPUT_IR_REMOTE_SELECT, XINPUT_IR_REMOTE_SKIP_MINUS, XINPUT_IR_REMOTE_SKIP_PLUS, XINPUT_IR_REMOTE_STAR, XINPUT_IR_REMOTE_START, XINPUT_IR_REMOTE_STOP, XINPUT_IR_REMOTE_SUBTITLE, XINPUT_IR_REMOTE_TELETEXT, XINPUT_IR_REMOTE_TITLE, XINPUT_IR_REMOTE_TOP_MENU, XINPUT_IR_REMOTE_UP, XINPUT_IR_REMOTE_VOLUME_MINUS, XINPUT_IR_REMOTE_VOLUME_PLUS, and XINPUT_IR_REMOTE_YELLOW.
Referenced by KODI::KEYMAP::CButtonTranslator::MapWindowActions(), TranslateButton(), and KODI::KEYMAP::CButtonTranslator::TranslateString().
TranslateUniversalRemoteString()
uint32_t CIRTranslator::TranslateUniversalRemoteString (const std::string & szButton) static
Referenced by KODI::KEYMAP::CButtonTranslator::MapWindowActions(), TranslateButton(), and KODI::KEYMAP::CButtonTranslator::TranslateString().
Member Data Documentation
m_irRemotesMap
std::map<std::string, std::shared_ptr<IRButtonMap> > KODI::KEYMAP::CIRTranslator::m_irRemotesMap private
Referenced by Clear(), MapRemote(), and TranslateButton().
The documentation for this class was generated from the following files:
IRTranslator.h
IRTranslator.cpp