Kodi Documentation: MediaSource.cpp File Reference
MediaSource.cpp File Reference
#include "MediaSource.h"
#include "URL.h"
#include "Util.h"
#include "filesystem/MultiPathDirectory.h"
#include "media/MediaLockState.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
Functions
void AddOrReplace (std::vector< CMediaSource > &sources, const std::vector< CMediaSource > &extras)
void AddOrReplace (std::vector< CMediaSource > &sources, const CMediaSource &source)
Function Documentation
AddOrReplace() [1/2]
void AddOrReplace (std::vector< CMediaSource > & sources, const CMediaSource & source)
References KODI::UTILS::StringUtils::EqualsNoCase(), and CMediaSource::strPath.
AddOrReplace() [2/2]
void AddOrReplace (std::vector< CMediaSource > & sources, const std::vector< CMediaSource > & extras)
References KODI::UTILS::StringUtils::EqualsNoCase().
Referenced by CStorageProvider::GetDrivesByType(), CWin32StorageProvider::GetDrivesByType(), and CGUIViewStateWindowPrograms::GetSources().