Kodi Documentation: CTextureUseCountJob Class Reference
CTextureUseCountJob Class Reference
#include <TextureCacheJob.h>
Public Member Functions
CTextureUseCountJob (const std::vector< CTextureDetails > &textures)
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
bool DoWork () override
Main workhorse function of CJob instances.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Private Attributes
std::vector< CTextureDetails > m_textures
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Constructor & Destructor Documentation
CTextureUseCountJob()
CTextureUseCountJob::CTextureUseCountJob (const std::vector< CTextureDetails > & textures) explicit
Member Function Documentation
DoWork()
bool CTextureUseCountJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CDatabase::BeginTransaction(), CDatabase::CommitTransaction(), CTextureDatabase::IncrementUseCount(), m_textures, and CTextureDatabase::Open().
GetType()
const char * CTextureUseCountJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CJob.
Referenced by operator==().
operator==()
bool CTextureUseCountJob::operator== (const CJob * job) const override virtual
Reimplemented from CJob.
References CJob::GetType(), GetType(), and m_textures.
Member Data Documentation
m_textures
std::vector<CTextureDetails> CTextureUseCountJob::m_textures private
Referenced by DoWork(), and operator==().
The documentation for this class was generated from the following files:
TextureCacheJob.h
TextureCacheJob.cpp