Kodi Documentation: KODI::MEMORY Namespace Reference
KODI::MEMORY Namespace Reference
Classes
struct MemoryStatus
Functions
void * AlignedMalloc (size_t s, size_t alignTo)
void AlignedFree (void *p)
void GetMemoryStatus (MemoryStatus *buffer)
Function Documentation
AlignedFree()
void KODI::MEMORY::AlignedFree (void * p)
Referenced by CTextureBase::Allocate(), COutputShader::CreateLUTView(), AERingBuffer::Dump(), CDVDDemuxUtils::FreeDemuxPacket(), ActiveAE::CActiveAESink::GenerateNoise(), CDXTexture::LoadToGPU(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), CRendererBase::OnCMSConfigChanged(), CGUIShaderDX::operator delete(), AERingBuffer::~AERingBuffer(), VAAPI::CFFmpegPostproc::~CFFmpegPostproc(), and CTexture::~CTexture().
AlignedMalloc()
void * KODI::MEMORY::AlignedMalloc (size_t s, size_t alignTo)
Referenced by CTextureBase::Allocate(), CDVDDemuxUtils::AllocateDemuxPacket(), AERingBuffer::Create(), COutputShader::CreateLUTView(), AERingBuffer::Dump(), ActiveAE::CActiveAESink::GenerateNoise(), CRendererBase::OnCMSConfigChanged(), CGUIShaderDX::operator new(), VAAPI::CFFmpegPostproc::PreInit(), and CTexture::UploadFromMemory().
GetMemoryStatus()
void KODI::MEMORY::GetMemoryStatus (MemoryStatus * buffer)
Referenced by ADDON::Interface_General::get_free_mem(), XBMCAddon::xbmc::getFreeMem(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetInt(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), and CGUIWindowDebugInfo::Process().