Kodi Documentation: CDDSImage Class Reference
CDDSImage Class Reference
#include <DDSImage.h>
Classes
struct ddcaps2
struct ddpixelformat
struct ddsurfacedesc2
Public Member Functions
CDDSImage ()
CDDSImage (unsigned int width, unsigned int height, XB_FMT format)
~CDDSImage ()
unsigned int GetWidth () const
unsigned int GetHeight () const
XB_FMT GetFormat () const
unsigned int GetSize () const
unsigned char * GetData () const
bool ReadFile (const std::string &file)
Private Types
enum {
ddsd_caps = 0x00000001 , ddsd_height = 0x00000002 , ddsd_width = 0x00000004 , ddsd_pitch = 0x00000008 ,
ddsd_pixelformat = 0x00001000 , ddsd_mipmapcount = 0x00020000 , ddsd_linearsize = 0x00080000 , ddsd_depth = 0x00800000
}
enum { ddpf_alphapixels = 0x00000001 , ddpf_fourcc = 0x00000004 , ddpf_rgb = 0x00000040 }
enum { ddscaps_complex = 0x00000008 , ddscaps_texture = 0x00001000 , ddscaps_mipmap = 0x00400000 }
Private Member Functions
void Allocate (unsigned int width, unsigned int height, XB_FMT format)
Static Private Member Functions
static const char * GetFourCC (XB_FMT format)
static unsigned int GetStorageRequirements (unsigned int width, unsigned int height, XB_FMT format)
Private Attributes
ddsurfacedesc2 m_desc
unsigned char * m_data
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
ddsd_caps
ddsd_height
ddsd_width
ddsd_pitch
ddsd_pixelformat
ddsd_mipmapcount
ddsd_linearsize
ddsd_depth
anonymous enum
anonymous enum private
Enumerator
ddpf_alphapixels
ddpf_fourcc
ddpf_rgb
anonymous enum
anonymous enum private
Enumerator
ddscaps_complex
ddscaps_texture
ddscaps_mipmap
Constructor & Destructor Documentation
CDDSImage() [1/2]
CDDSImage::CDDSImage ()
References m_data, and m_desc.
CDDSImage() [2/2]
CDDSImage::CDDSImage (unsigned int width, unsigned int height, XB_FMT format)
References Allocate(), and m_data.
~CDDSImage()
CDDSImage::~CDDSImage ()
References m_data.
Member Function Documentation
Allocate()
void CDDSImage::Allocate (unsigned int width, unsigned int height, XB_FMT format) private
References CDDSImage::ddsurfacedesc2::caps, ddpf_fourcc, ddscaps_texture, ddsd_caps, ddsd_height, ddsd_linearsize, ddsd_pixelformat, ddsd_width, CDDSImage::ddpixelformat::flags, CDDSImage::ddsurfacedesc2::flags, CDDSImage::ddcaps2::flags1, CDDSImage::ddpixelformat::fourcc, GetFourCC(), GetStorageRequirements(), CDDSImage::ddsurfacedesc2::height, CDDSImage::ddsurfacedesc2::linearSize, m_data, m_desc, CDDSImage::ddsurfacedesc2::pixelFormat, CDDSImage::ddpixelformat::size, CDDSImage::ddsurfacedesc2::size, and CDDSImage::ddsurfacedesc2::width.
Referenced by CDDSImage().
GetData()
unsigned char * CDDSImage::GetData () const
References m_data.
Referenced by CTexture::LoadFromFileInternal().
GetFormat()
XB_FMT CDDSImage::GetFormat () const
References DDPF_FOURCC, DDPF_RGB, CDDSImage::ddpixelformat::flags, CDDSImage::ddpixelformat::fourcc, m_desc, CDDSImage::ddsurfacedesc2::pixelFormat, XB_FMT_A8R8G8B8, XB_FMT_DXT1, XB_FMT_DXT3, XB_FMT_DXT5, and XB_FMT_UNKNOWN.
Referenced by CTexture::LoadFromFileInternal(), and ReadFile().
GetFourCC()
const char * CDDSImage::GetFourCC (XB_FMT format) static private
References XB_FMT_A8R8G8B8, XB_FMT_DXT1, XB_FMT_DXT3, and XB_FMT_DXT5.
Referenced by Allocate().
GetHeight()
unsigned int CDDSImage::GetHeight () const
References CDDSImage::ddsurfacedesc2::height, and m_desc.
Referenced by CTexture::LoadFromFileInternal().
GetSize()
unsigned int CDDSImage::GetSize () const
References CDDSImage::ddsurfacedesc2::linearSize, and m_desc.
GetStorageRequirements()
unsigned int CDDSImage::GetStorageRequirements (unsigned int width, unsigned int height, XB_FMT format) static private
References XB_FMT_A8R8G8B8, XB_FMT_DXT1, XB_FMT_DXT3, and XB_FMT_DXT5.
Referenced by Allocate().
GetWidth()
unsigned int CDDSImage::GetWidth () const
References m_desc, and CDDSImage::ddsurfacedesc2::width.
Referenced by CTexture::LoadFromFileInternal().
ReadFile()
bool CDDSImage::ReadFile (const std::string & file)
References XFILE::CFile::Close(), GetFormat(), CDDSImage::ddsurfacedesc2::linearSize, m_data, and m_desc.
Referenced by CTexture::LoadFromFileInternal().
Member Data Documentation
m_data
unsigned char* CDDSImage::m_data private
Referenced by Allocate(), CDDSImage(), CDDSImage(), GetData(), ReadFile(), and ~CDDSImage().
m_desc
ddsurfacedesc2 CDDSImage::m_desc private
Referenced by Allocate(), CDDSImage(), GetFormat(), GetHeight(), GetSize(), GetWidth(), and ReadFile().
The documentation for this class was generated from the following files:
DDSImage.h
DDSImage.cpp