Kodi Documentation: KODI::GAME::CGUIConfigurationWizard Class Reference
KODI::GAME::CGUIConfigurationWizard Class Reference
Games
#include <GUIConfigurationWizard.h>
Public Member Functions
CGUIConfigurationWizard ()
~CGUIConfigurationWizard () override
void Run (const std::string &strControllerId, const std::vector< IFeatureButton * > &buttons) override
Start the wizard for the specified buttons.
void OnUnfocus (IFeatureButton *button) override
Callback for feature losing focus.
bool Abort (bool bWait=true) override
Abort a running wizard.
void RegisterKey (const CPhysicalFeature &key) override
Register a key by its keycode.
void UnregisterKeys () override
Unregister all registered keys.
std::string ControllerID () const override
The add-on ID of the game controller associated with this button mapper.
bool NeedsCooldown () const override
Return true if the button mapper wants a cooldown between button mapping commands.
bool AcceptsPrimitive (JOYSTICK::PRIMITIVE_TYPE type) const override
Return true if the button mapper accepts primitives of the given type.
bool MapPrimitive (JOYSTICK::IButtonMap *buttonMap, KEYMAP::IKeymap *keymap, const JOYSTICK::CDriverPrimitive &primitive) override
Handle button/hat press or axis threshold.
void OnEventFrame (const JOYSTICK::IButtonMap *buttonMap, bool bMotion) override
Called once per event frame to notify the implementation of motion status.
void OnLateAxis (const JOYSTICK::IButtonMap *buttonMap, unsigned int axisIndex) override
Called when an axis has been detected after mapping began.
bool OnKeyPress (const CKey &key) override
A key has been pressed.
void OnKeyRelease (const CKey &key) override
A key has been released.
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
Public Member Functions inherited from KODI::GAME::IConfigurationWizard
virtual ~IConfigurationWizard ()=default
Public Member Functions inherited from KODI::JOYSTICK::IButtonMapper
IButtonMapper ()=default
virtual ~IButtonMapper ()=default
void SetButtonMapCallback (const std::string &deviceLocation, IButtonMapCallback *callback)
void ResetButtonMapCallbacks (void)
std::map< std::string, IButtonMapCallback * > & ButtonMapCallbacks (void)
Public Member Functions inherited from KODI::KEYBOARD::IKeyboardDriverHandler
virtual ~IKeyboardDriverHandler ()=default
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Protected Member Functions
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Member Functions
void InitializeState (void)
bool IsMapping () const
bool IsMapping (const std::string &location) const
void InstallHooks (void)
void RemoveHooks (void)
void OnMotion (const JOYSTICK::IButtonMap *buttonMap)
void OnMotionless (const JOYSTICK::IButtonMap *buttonMap)
bool OnAction (unsigned int actionId)
Private Attributes
std::string m_strControllerId
std::vector< IFeatureButton * > m_buttons
IFeatureButton * m_currentButton
INPUT::CARDINAL_DIRECTION m_cardinalDirection
JOYSTICK::WHEEL_DIRECTION m_wheelDirection
JOYSTICK::THROTTLE_DIRECTION m_throttleDirection
std::set< JOYSTICK::CDriverPrimitive > m_history
bool m_lateAxisDetected
std::string m_location
bool m_bIsKeyboard = false
CCriticalSection m_stateMutex
CEvent m_inputEvent
CEvent m_motionlessEvent
CCriticalSection m_motionMutex
std::set< const JOYSTICK::IButtonMap * > m_bInMotion
std::unique_ptr< KEYMAP::IKeyboardActionMap > m_actionMap
std::map< std::string, CPhysicalFeature > m_keyMap
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CGUIConfigurationWizard()
CGUIConfigurationWizard::CGUIConfigurationWizard ()
References InitializeState().
~CGUIConfigurationWizard()
CGUIConfigurationWizard::~CGUIConfigurationWizard () override default
Member Function Documentation
Abort()
bool CGUIConfigurationWizard::Abort (bool bWait = true) override virtual
Abort a running wizard.
Parameters
bWait True if the call should block until the wizard is fully aborted
Returns
true if aborted, or false if the wizard wasn't running
Implements KODI::GAME::IConfigurationWizard.
References CThread::m_bStop, m_inputEvent, m_motionlessEvent, CEvent::Set(), and CThread::StopThread().
Referenced by OnAction(), OnLateAxis(), OnUnfocus(), Process(), and Run().
AcceptsPrimitive()
bool KODI::GAME::CGUIConfigurationWizard::AcceptsPrimitive (JOYSTICK::PRIMITIVE_TYPE type) const inline override virtual
Return true if the button mapper accepts primitives of the given type.
Parameters
type The primitive type
Returns
True if the button mapper can map the primitive type, false otherwise
Implements KODI::JOYSTICK::IButtonMapper.
ControllerID()
std::string KODI::GAME::CGUIConfigurationWizard::ControllerID () const inline override virtual
The add-on ID of the game controller associated with this button mapper.
Returns
The ID of the add-on extending kodi.game.controller
Implements KODI::JOYSTICK::IButtonMapper.
References m_strControllerId.
InitializeState()
void CGUIConfigurationWizard::InitializeState (void) private
References m_cardinalDirection, m_currentButton, m_history, m_lateAxisDetected, m_location, m_throttleDirection, m_wheelDirection, KODI::INPUT::NONE, and KODI::JOYSTICK::NONE.
Referenced by CGUIConfigurationWizard(), Process(), and Run().
InstallHooks()
void CGUIConfigurationWizard::InstallHooks (void) private
References CServiceBroker::GetInputManager(), CServiceBroker::GetPeripherals(), PERIPHERALS::CPeripherals::RegisterJoystickButtonMapper(), CInputManager::RegisterKeyboardDriverHandler(), and Observable::RegisterObserver().
Referenced by Process().
IsMapping() [1/2]
bool CGUIConfigurationWizard::IsMapping () const private
References m_location.
Referenced by MapPrimitive(), and OnKeyPress().
IsMapping() [2/2]
bool CGUIConfigurationWizard::IsMapping (const std::string & location) const private
References m_location.
MapPrimitive()
bool CGUIConfigurationWizard::MapPrimitive (JOYSTICK::IButtonMap * buttonMap, KEYMAP::IKeymap * keyMap, const JOYSTICK::CDriverPrimitive & primitive) override virtual
Handle button/hat press or axis threshold.
Parameters
buttonMap The button map being manipulated
keymap An interface capable of translating features to Kodi actions
primitive The driver primitive
Called in the same thread as IButtonMapper::OnFrame.
Returns
True if driver primitive was mapped to a feature
Todo:
This only succeeds for game.controller.default; no actions are
Todo:
Handle multiple actions mapped to the same key
Todo:
Check if primitive is a cancel or motion action
Implements KODI::JOYSTICK::IButtonMapper.
References actions, KODI::KEYMAP::KeymapActionGroup::actions, KODI::JOYSTICK::IButtonMap::AddAnalogStick(), KODI::JOYSTICK::IButtonMap::AddKey(), KODI::JOYSTICK::IButtonMap::AddRelativePointer(), KODI::JOYSTICK::IButtonMap::AddScalar(), KODI::JOYSTICK::IButtonMap::AddThrottle(), KODI::JOYSTICK::IButtonMap::AddWheel(), KODI::GAME::IFeatureButton::Feature(), KODI::KEYMAP::IKeymap::GetActions(), KODI::JOYSTICK::IButtonMap::GetFeature(), KODI::JOYSTICK::IButtonMap::IsIgnored(), IsMapping(), KODI::JOYSTICK::CDriverPrimitive::Keycode(), KODI::JOYSTICK::IButtonMap::Location(), CLog::Log(), LOGDEBUG, m_bIsKeyboard, m_cardinalDirection, m_currentButton, m_history, m_inputEvent, m_keyMap, m_location, m_stateMutex, m_strControllerId, m_throttleDirection, m_wheelDirection, KODI::GAME::CPhysicalFeature::Name(), KODI::GAME::IFeatureButton::NeedsKey(), OnAction(), OnMotion(), CEvent::Set(), KODI::GAME::IFeatureButton::SetKey(), KODI::JOYSTICK::CDriverPrimitive::ToString(), KODI::KEYBOARD::CKeyboardTranslator::TranslateKeycode(), KODI::GAME::CPhysicalFeature::Type(), and KODI::JOYSTICK::CDriverPrimitive::Type().
NeedsCooldown()
bool KODI::GAME::CGUIConfigurationWizard::NeedsCooldown () const inline override virtual
Return true if the button mapper wants a cooldown between button mapping commands.
Returns
True to only send button mapping commands that occur after a small timeout from the previous command.
Implements KODI::JOYSTICK::IButtonMapper.
Notify()
void CGUIConfigurationWizard::Notify (const Observable & obs, const ObservableMessage msg) override virtual
Process a message from an observable.
Parameters
obs The observable that sends the message.
msg The message.
Implements Observer.
References CServiceBroker::GetPeripherals(), ObservableMessagePeripheralsChanged, PERIPHERALS::CPeripherals::RegisterJoystickButtonMapper(), and PERIPHERALS::CPeripherals::UnregisterJoystickButtonMapper().
OnAction()
bool CGUIConfigurationWizard::OnAction (unsigned int actionId) private
References Abort(), ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NAV_BACK, ACTION_PAGE_DOWN, ACTION_PAGE_UP, ACTION_PARENT_DIR, ACTION_PREVIOUS_MENU, and ACTION_STOP.
Referenced by MapPrimitive(), and OnKeyPress().
OnEventFrame()
void CGUIConfigurationWizard::OnEventFrame (const JOYSTICK::IButtonMap * buttonMap, bool bMotion) override virtual
Called once per event frame to notify the implementation of motion status.
Parameters
buttonMap The button map passed to MapPrimitive() (shall not be modified)
bMotion True if a previously-mapped axis is still in motion
This allows the implementer to wait for an axis to be centered before allowing it to be used as Kodi input.
If mapping finishes on an axis, then the axis will still be pressed and sending input every frame when the mapping ends. For example, when the right analog stick is the last feature to be mapped, it is still pressed when mapping ends and immediately sends Volume Down actions.
The fix is to allow implementers to wait until all axes are motionless before detaching themselves.
Called in the same thread as IButtonMapper::MapPrimitive.
Implements KODI::JOYSTICK::IButtonMapper.
References m_bInMotion, m_motionMutex, and OnMotionless().
OnKeyPress()
bool CGUIConfigurationWizard::OnKeyPress (const CKey & key) override virtual
A key has been pressed.
Parameters
key The pressed key
Returns
True if the event was handled, false otherwise
Implements KODI::KEYBOARD::IKeyboardDriverHandler.
References IsMapping(), m_actionMap, m_bIsKeyboard, CThread::m_bStop, and OnAction().
OnKeyRelease()
void KODI::GAME::CGUIConfigurationWizard::OnKeyRelease (const CKey & key) inline override virtual
A key has been released.
Parameters
key The released key
Implements KODI::KEYBOARD::IKeyboardDriverHandler.
OnLateAxis()
void CGUIConfigurationWizard::OnLateAxis (const JOYSTICK::IButtonMap * buttonMap, unsigned int axisIndex) override virtual
Called when an axis has been detected after mapping began.
Parameters
axisIndex The index of the axis being discovered
Some joystick drivers don't report an initial value for analog axes.
Called in the same thread as IButtonMapper::MapPrimitive.
Implements KODI::JOYSTICK::IButtonMapper.
References Abort(), m_lateAxisDetected, and m_stateMutex.
OnMotion()
void CGUIConfigurationWizard::OnMotion (const JOYSTICK::IButtonMap * buttonMap) private
References m_bInMotion, m_motionlessEvent, m_motionMutex, and CEvent::Reset().
Referenced by MapPrimitive().
OnMotionless()
void CGUIConfigurationWizard::OnMotionless (const JOYSTICK::IButtonMap * buttonMap) private
References m_bInMotion, m_motionlessEvent, and CEvent::Set().
Referenced by OnEventFrame().
OnUnfocus()
void CGUIConfigurationWizard::OnUnfocus (IFeatureButton * button) override virtual
Callback for feature losing focus.
Parameters
button The feature button losing focus
Implements KODI::GAME::IConfigurationWizard.
References Abort(), m_currentButton, and m_stateMutex.
Process()
void CGUIConfigurationWizard::Process (void) override protected virtual
Reimplemented from CThread.
References Abort(), KODI::JOYSTICK::IButtonMapper::ButtonMapCallbacks(), KODI::GAME::IFeatureButton::GetCardinalDirection(), InitializeState(), InstallHooks(), CLog::Log(), LOGDEBUG, m_bInMotion, CThread::m_bStop, m_buttons, m_cardinalDirection, m_currentButton, m_inputEvent, m_lateAxisDetected, m_motionlessEvent, m_motionMutex, m_stateMutex, m_strControllerId, m_throttleDirection, m_wheelDirection, RemoveHooks(), KODI::GAME::CGUIDialogButtonCapture::Show(), and CEvent::Wait().
RegisterKey()
void CGUIConfigurationWizard::RegisterKey (const CPhysicalFeature & key) override virtual
Register a key by its keycode.
Parameters
key A key with a valid keycode
This should be called before Run(). It allows the user to choose a key to map instead of scrolling through a long list.
Implements KODI::GAME::IConfigurationWizard.
References KODI::GAME::CPhysicalFeature::Keycode(), m_keyMap, KODI::KEYBOARD::CKeyboardTranslator::TranslateKeycode(), and XBMCK_UNKNOWN.
RemoveHooks()
void CGUIConfigurationWizard::RemoveHooks (void) private
References CServiceBroker::GetInputManager(), CServiceBroker::GetPeripherals(), PERIPHERALS::CPeripherals::UnregisterJoystickButtonMapper(), CInputManager::UnregisterKeyboardDriverHandler(), and Observable::UnregisterObserver().
Referenced by Process().
Run()
void CGUIConfigurationWizard::Run (const std::string & strControllerId, const std::vector< IFeatureButton * > & buttons) override virtual
Start the wizard for the specified buttons.
Parameters
controllerId The controller ID being mapped
buttons The buttons to map
Implements KODI::GAME::IConfigurationWizard.
References Abort(), CThread::Create(), InitializeState(), m_bInMotion, m_buttons, m_inputEvent, m_motionlessEvent, m_stateMutex, m_strControllerId, and CEvent::Reset().
UnregisterKeys()
void CGUIConfigurationWizard::UnregisterKeys () override virtual
Unregister all registered keys.
Implements KODI::GAME::IConfigurationWizard.
References m_keyMap.
Member Data Documentation
m_actionMap
std::unique_ptr<KEYMAP::IKeyboardActionMap> KODI::GAME::CGUIConfigurationWizard::m_actionMap private
Referenced by OnKeyPress().
m_bInMotion
std::set<const JOYSTICK::IButtonMap*> KODI::GAME::CGUIConfigurationWizard::m_bInMotion private
Referenced by OnEventFrame(), OnMotion(), OnMotionless(), Process(), and Run().
m_bIsKeyboard
bool KODI::GAME::CGUIConfigurationWizard::m_bIsKeyboard = false private
Referenced by MapPrimitive(), and OnKeyPress().
m_buttons
std::vector<IFeatureButton*> KODI::GAME::CGUIConfigurationWizard::m_buttons private
Referenced by Process(), and Run().
m_cardinalDirection
INPUT::CARDINAL_DIRECTION KODI::GAME::CGUIConfigurationWizard::m_cardinalDirection private
Referenced by InitializeState(), MapPrimitive(), and Process().
m_currentButton
IFeatureButton* KODI::GAME::CGUIConfigurationWizard::m_currentButton private
Referenced by InitializeState(), MapPrimitive(), OnUnfocus(), and Process().
m_history
std::set<JOYSTICK::CDriverPrimitive> KODI::GAME::CGUIConfigurationWizard::m_history private
Referenced by InitializeState(), and MapPrimitive().
m_inputEvent
CEvent KODI::GAME::CGUIConfigurationWizard::m_inputEvent private
Referenced by Abort(), MapPrimitive(), Process(), and Run().
m_keyMap
std::map<std::string, CPhysicalFeature> KODI::GAME::CGUIConfigurationWizard::m_keyMap private
Referenced by MapPrimitive(), RegisterKey(), and UnregisterKeys().
m_lateAxisDetected
bool KODI::GAME::CGUIConfigurationWizard::m_lateAxisDetected private
Referenced by InitializeState(), OnLateAxis(), and Process().
m_location
std::string KODI::GAME::CGUIConfigurationWizard::m_location private
Referenced by InitializeState(), IsMapping(), IsMapping(), and MapPrimitive().
m_motionlessEvent
CEvent KODI::GAME::CGUIConfigurationWizard::m_motionlessEvent private
Referenced by Abort(), OnMotion(), OnMotionless(), Process(), and Run().
m_motionMutex
CCriticalSection KODI::GAME::CGUIConfigurationWizard::m_motionMutex private
Referenced by OnEventFrame(), OnMotion(), and Process().
m_stateMutex
CCriticalSection KODI::GAME::CGUIConfigurationWizard::m_stateMutex private
Referenced by MapPrimitive(), OnLateAxis(), OnUnfocus(), Process(), and Run().
m_strControllerId
std::string KODI::GAME::CGUIConfigurationWizard::m_strControllerId private
Referenced by ControllerID(), MapPrimitive(), Process(), and Run().
m_throttleDirection
JOYSTICK::THROTTLE_DIRECTION KODI::GAME::CGUIConfigurationWizard::m_throttleDirection private
Referenced by InitializeState(), MapPrimitive(), and Process().
m_wheelDirection
JOYSTICK::WHEEL_DIRECTION KODI::GAME::CGUIConfigurationWizard::m_wheelDirection private
Referenced by InitializeState(), MapPrimitive(), and Process().
The documentation for this class was generated from the following files:
GUIConfigurationWizard.h
GUIConfigurationWizard.cpp