Kodi Documentation: CWin32DiscDriveHandler Class Reference
CWin32DiscDriveHandler Class Reference
#include <Win32DiscDriveHandler.h>
Public Member Functions
CWin32DiscDriveHandler ()=default
Win32 DiscDriveHandler constructor.
~CWin32DiscDriveHandler () override=default
Win32 DiscDriveHandler destructor.
DriveState GetDriveState (const std::string &devicePath) override
Get the optical drive state provided its device path.
TrayState GetTrayState (const std::string &devicePath) override
Get the optical drive tray state provided the drive device path.
void EjectDriveTray (const std::string &devicePath) override
Eject the provided drive device.
void CloseDriveTray (const std::string &devicePath) override
Close the provided drive device.
void ToggleDriveTray (const std::string &devicePath) override
Toggle the state of a given drive device.
Additional Inherited Members
Static Public Member Functions inherited from IDiscDriveHandler
static std::shared_ptr< IDiscDriveHandler > CreateInstance ()
Called to create platform-specific disc drive handler.
Protected Member Functions inherited from IDiscDriveHandler
virtual ~IDiscDriveHandler ()=default
IDiscDriveHandler ()=default
Constructor & Destructor Documentation
CWin32DiscDriveHandler()
CWin32DiscDriveHandler::CWin32DiscDriveHandler () default
Win32 DiscDriveHandler constructor.
~CWin32DiscDriveHandler()
CWin32DiscDriveHandler::~CWin32DiscDriveHandler () override default
Win32 DiscDriveHandler destructor.
Member Function Documentation
CloseDriveTray()
void CWin32DiscDriveHandler::CloseDriveTray (const std::string & devicePath) override virtual
Close the provided drive device.
Note
Some drives support closing appart from opening/eject
Parameters
devicePath the path for the device drive (e.g. D\://)
Implements IDiscDriveHandler.
References CWIN32Util::CloseTray(), and LOGERROR.
EjectDriveTray()
void CWin32DiscDriveHandler::EjectDriveTray (const std::string & devicePath) override virtual
Eject the provided drive device.
Parameters
devicePath the path for the device drive (e.g. D\://)
Implements IDiscDriveHandler.
References CWIN32Util::EjectTray(), and LOGERROR.
GetDriveState()
DriveState CWin32DiscDriveHandler::GetDriveState (const std::string & devicePath) override virtual
Get the optical drive state provided its device path.
Parameters
devicePath the path for the device drive (e.g. D\://)
Returns
The drive state
Implements IDiscDriveHandler.
References CLOSED_MEDIA_PRESENT, CLOSED_NO_MEDIA, CWIN32Util::GetDriveStatus(), LOGWARNING, NOT_READY, and OPEN.
Referenced by GetTrayState().
GetTrayState()
TrayState CWin32DiscDriveHandler::GetTrayState (const std::string & devicePath) override virtual
Get the optical drive tray state provided the drive device path.
Parameters
devicePath the path for the device drive (e.g. D\://)
Returns
The drive state
Implements IDiscDriveHandler.
References CLOSED_MEDIA_PRESENT, CLOSED_NO_MEDIA, GetDriveState(), LOGWARNING, OPEN, and UNDEFINED.
ToggleDriveTray()
void CWin32DiscDriveHandler::ToggleDriveTray (const std::string & devicePath) override virtual
Toggle the state of a given drive device.
Parameters
devicePath the path for the device drive (e.g. D\://)
Implements IDiscDriveHandler.
References LOGERROR, and CWIN32Util::ToggleTray().
The documentation for this class was generated from the following files:
Win32DiscDriveHandler.h
Win32DiscDriveHandler.cpp