Kodi Documentation: CPlayerUtils Class Reference
CPlayerUtils Class Reference
#include <PlayerUtils.h>
Static Public Member Functions
static bool IsItemPlayable (const CFileItem &item)
static void AdvanceTempoStep (const std::shared_ptr< CApplicationPlayer > &appPlayer, TempoStepChange change)
Member Function Documentation
AdvanceTempoStep()
void CPlayerUtils::AdvanceTempoStep (const std::shared_ptr< CApplicationPlayer > & appPlayer, TempoStepChange change) static
References DECREASE, and INCREASE.
Referenced by CApplication::OnAction(), PlayerControl(), and JSONRPC::CPlayerOperations::SetTempo().
IsItemPlayable()
bool CPlayerUtils::IsItemPlayable (const CFileItem & item) static
Todo:
add more types on demand.
References CVariant::asBoolean(), CFileItem::GetItemToPlay(), CGUIListItem::GetProperty(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), CFileItem::IsParentFolder(), and CFileItem::IsPlugin().
Referenced by CGUIWindowFavourites::OnAction(), and CDirectoryProvider::OnPlay().
The documentation for this class was generated from the following files:
PlayerUtils.h
PlayerUtils.cpp