Kodi Documentation: KODI::PIPEWIRE::CPipewireProxy Class Reference
KODI::PIPEWIRE::CPipewireProxy Class Reference
#include <PipewireProxy.h>
Classes
struct PipewireProxyDeleter
Public Member Functions
CPipewireProxy ()=delete
virtual ~CPipewireProxy ()
CPipewireRegistry & GetRegistry () const
Protected Member Functions
CPipewireProxy (CPipewireRegistry &registry, uint32_t id, const char *type, uint32_t version)
Protected Attributes
std::unique_ptr< pw_proxy, PipewireProxyDeleter > m_proxy
Static Private Member Functions
static void Bound (void *userdata, uint32_t id)
static void Removed (void *userdata)
static pw_proxy_events CreateProxyEvents ()
Private Attributes
CPipewireRegistry & m_registry
const pw_proxy_events m_proxyEvents
spa_hook m_proxyListener
Constructor & Destructor Documentation
CPipewireProxy() [1/2]
KODI::PIPEWIRE::CPipewireProxy::CPipewireProxy () delete
~CPipewireProxy()
CPipewireProxy::~CPipewireProxy () virtual
References m_proxyListener.
CPipewireProxy() [2/2]
CPipewireProxy::CPipewireProxy (CPipewireRegistry & registry, uint32_t id, const char * type, uint32_t version) explicit protected
References KODI::PIPEWIRE::CPipewireRegistry::Get(), CLog::Log(), LOGERROR, m_proxy, m_proxyEvents, and m_proxyListener.
Member Function Documentation
Bound()
void CPipewireProxy::Bound (void * userdata, uint32_t id) static private
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGDEBUG.
Referenced by CreateProxyEvents().
CreateProxyEvents()
pw_proxy_events CPipewireProxy::CreateProxyEvents () static private
References Bound(), and Removed().
GetRegistry()
CPipewireRegistry & KODI::PIPEWIRE::CPipewireProxy::GetRegistry () const inline
References m_registry.
Referenced by KODI::PIPEWIRE::CPipewireNode::Param().
Removed()
void CPipewireProxy::Removed (void * userdata) static private
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGDEBUG.
Referenced by CreateProxyEvents().
Member Data Documentation
m_proxy
std::unique_ptr<pw_proxy, PipewireProxyDeleter> KODI::PIPEWIRE::CPipewireProxy::m_proxy protected
Referenced by KODI::PIPEWIRE::CPipewireNode::CPipewireNode(), CPipewireProxy(), and KODI::PIPEWIRE::CPipewireNode::EnumerateFormats().
m_proxyEvents
const pw_proxy_events KODI::PIPEWIRE::CPipewireProxy::m_proxyEvents private
Referenced by CPipewireProxy().
m_proxyListener
spa_hook KODI::PIPEWIRE::CPipewireProxy::m_proxyListener private
Referenced by CPipewireProxy(), and ~CPipewireProxy().
m_registry
CPipewireRegistry& KODI::PIPEWIRE::CPipewireProxy::m_registry private
Referenced by GetRegistry().
The documentation for this class was generated from the following files:
PipewireProxy.h
PipewireProxy.cpp