Kodi Documentation: KODI::JOYSTICK::CPointerDetector Class Reference
KODI::JOYSTICK::CPointerDetector Class Reference
Input » Joystick
Detects when a mouse button should be mapped.
#include <ButtonMapping.h>
Public Member Functions
CPointerDetector (CButtonMapping *buttonMapping)
bool OnMotion (int x, int y)
Pointer position has been updated.
Static Private Member Functions
static INPUT::INTERCARDINAL_DIRECTION GetPointerDirection (int x, int y)
Private Attributes
bool m_bStarted = false
int m_startX = 0
int m_startY = 0
unsigned int m_frameCount = 0
Static Private Attributes
static const unsigned int MIN_FRAME_COUNT = 10
Additional Inherited Members
Protected Member Functions inherited from KODI::JOYSTICK::CPrimitiveDetector
CPrimitiveDetector (CButtonMapping *buttonMapping)
bool MapPrimitive (const CDriverPrimitive &primitive)
Dispatch a mapping event.
Detailed Description
Detects when a mouse button should be mapped.
Constructor & Destructor Documentation
CPointerDetector()
CPointerDetector::CPointerDetector (CButtonMapping * buttonMapping)
Member Function Documentation
GetPointerDirection()
KODI::INPUT::INTERCARDINAL_DIRECTION CPointerDetector::GetPointerDirection (int x, int y) static private
Referenced by OnMotion().
OnMotion()
bool CPointerDetector::OnMotion (int x, int y)
Pointer position has been updated.
Parameters
x The new x coordinate
y The new y coordinate
Returns
Always true - pointer motion events are always absorbed while button mapping
References GetPointerDirection(), KODI::JOYSTICK::CDriverPrimitive::IsValid(), m_bStarted, m_frameCount, m_startX, m_startY, KODI::JOYSTICK::CPrimitiveDetector::MapPrimitive(), and MIN_FRAME_COUNT.
Referenced by KODI::JOYSTICK::CButtonMapping::OnPosition().
Member Data Documentation
m_bStarted
bool KODI::JOYSTICK::CPointerDetector::m_bStarted = false private
Referenced by OnMotion().
m_frameCount
unsigned int KODI::JOYSTICK::CPointerDetector::m_frameCount = 0 private
Referenced by OnMotion().
m_startX
int KODI::JOYSTICK::CPointerDetector::m_startX = 0 private
Referenced by OnMotion().
m_startY
int KODI::JOYSTICK::CPointerDetector::m_startY = 0 private
Referenced by OnMotion().
MIN_FRAME_COUNT
const unsigned int KODI::JOYSTICK::CPointerDetector::MIN_FRAME_COUNT = 10 static private
Referenced by OnMotion().
The documentation for this class was generated from the following files:
ButtonMapping.h
ButtonMapping.cpp