Kodi Documentation: TestPOUtils.cpp File Reference
TestPOUtils.cpp File Reference
#include "test/TestUtils.h"
#include "utils/POUtils.h"
#include <gtest/gtest.h>
Functions
TEST (TestPOUtils, General)
Function Documentation
TEST()
TEST (TestPOUtils , General)
References EXPECT_EQ(), EXPECT_TRUE(), CPODocument::GetEntryID(), CPODocument::GetEntryType(), CPODocument::GetMsgctxt(), CPODocument::GetMsgid(), CPODocument::GetMsgstr(), CPODocument::GetNextEntry(), CPODocument::GetPlurMsgstr(), ID_FOUND, CPODocument::LoadFile(), CPODocument::ParseEntry(), and XBMC_REF_FILE_PATH.