Kodi Documentation: AE::SINK::CAESinkPipewire Class Reference
AE::SINK::CAESinkPipewire Class Reference
#include <AESinkPipewire.h>
Public Member Functions
CAESinkPipewire ()=default
~CAESinkPipewire () override=default
const char * GetName () override
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
double GetCacheTotal () override
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void Drain () override
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual double GetLatency ()
virtual void AddPause (unsigned int millis)
instruct the sink to add a pause
virtual bool HasVolume ()
virtual void SetVolume (float volume)
Static Public Member Functions
static bool Register ()
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
static void EnumerateDevicesEx (AEDeviceInfoList &list, bool force=false)
static void Destroy ()
Private Attributes
AEAudioFormat m_format
std::chrono::duration< double, std::ratio< 1 > > m_latency
std::unique_ptr< KODI::PIPEWIRE::CPipewireStream > m_stream
Constructor & Destructor Documentation
CAESinkPipewire()
AE::SINK::CAESinkPipewire::CAESinkPipewire () default
~CAESinkPipewire()
AE::SINK::CAESinkPipewire::~CAESinkPipewire () override default
Member Function Documentation
AddPackets()
unsigned int CAESinkPipewire::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References data(), m_format, AEAudioFormat::m_frameSize, AEAudioFormat::m_sampleRate, m_stream, and pipewire.
Create()
std::unique_ptr< IAESink > CAESinkPipewire::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
Deinitialize()
void CAESinkPipewire::Deinitialize () override virtual
Implements IAESink.
References m_stream, and pipewire.
Destroy()
void CAESinkPipewire::Destroy () static
References pipewire.
Referenced by Register().
Drain()
void CAESinkPipewire::Drain () override virtual
Reimplemented from IAESink.
References CLog::Log(), LOGDEBUG, m_stream, and pipewire.
EnumerateDevicesEx()
void CAESinkPipewire::EnumerateDevicesEx (AEDeviceInfoList & list, bool force = false) static
References AE_CH_LAYOUT_2_0, AE_DEVTYPE_HDMI, AE_DEVTYPE_IEC958, AE_DEVTYPE_PCM, AE_FMT_RAW, channelMap, CAEChannelInfo::Count(), CLog::Log(), LOGDEBUG, CAEDeviceInfo::m_channels, CAEDeviceInfo::m_dataFormats, CAEDeviceInfo::m_deviceName, CAEDeviceInfo::m_deviceType, CAEDeviceInfo::m_displayName, CAEDeviceInfo::m_displayNameExtra, CAEDeviceInfo::m_streamTypes, CAEDeviceInfo::m_wantsIECPassthrough, node, and pipewire.
Referenced by Register().
GetCacheTotal()
double CAESinkPipewire::GetCacheTotal () override virtual
Implements IAESink.
References m_latency.
GetDelay()
void CAESinkPipewire::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References m_format, AEAudioFormat::m_sampleRate, m_stream, pipewire, and AEDelayStatus::SetDelay().
GetName()
const char * AE::SINK::CAESinkPipewire::GetName () inline override virtual
Implements IAESink.
Initialize()
bool CAESinkPipewire::Initialize (AEAudioFormat & format, std::string & device) override virtual
Implements IAESink.
References AE_CH_LAYOUT_2_0, AE_CH_LAYOUT_7_1, AE_FMT_RAW, AE_FMT_S16NE, CCompileInfo::GetAppName(), id, index(), CLog::Log(), LOGDEBUG, m_format, m_latency, m_stream, pipewire, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Register()
bool CAESinkPipewire::Register () static
References AE::AESinkRegEntry::cleanupFunc, KODI::PIPEWIRE::CPipewire::Create(), Create(), AE::AESinkRegEntry::createFunc, Destroy(), EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, pipewire, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
Member Data Documentation
m_format
AEAudioFormat AE::SINK::CAESinkPipewire::m_format private
Referenced by AddPackets(), GetDelay(), and Initialize().
m_latency
std::chrono::duration<double, std::ratio<1> > AE::SINK::CAESinkPipewire::m_latency private
Referenced by GetCacheTotal(), and Initialize().
m_stream
std::unique_ptr<KODI::PIPEWIRE::CPipewireStream> AE::SINK::CAESinkPipewire::m_stream private
Referenced by AddPackets(), Deinitialize(), Drain(), GetDelay(), and Initialize().
The documentation for this class was generated from the following files:
AESinkPipewire.h
AESinkPipewire.cpp