Kodi Documentation: CRendererDRMPRIME Class Reference
CRendererDRMPRIME Class Reference
#include <RendererDRMPRIME.h>
Classes
struct BUFFER
Public Member Functions
CRendererDRMPRIME ()=default
~CRendererDRMPRIME () override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
bool IsConfigured () override
void AddVideoPicture (const VideoPicture &picture, int index) override
void UnInit () override
bool Flush (bool saveBuffers) override
void ReleaseBuffer (int idx) override
bool NeedBuffer (int idx) override
bool IsGuiLayer () override
CRenderInfo GetRenderInfo () override
void Update () override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
bool RenderCapture (int index, CRenderCapture *capture) override
bool ConfigChanged (const VideoPicture &picture) override
bool SupportsMultiPassRendering () override
bool Supports (ERENDERFEATURE feature) const override
bool Supports (ESCALINGMETHOD method) const override
Public Member Functions inherited from CBaseRenderer
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool IsPictureHW (const VideoPicture &picture)
virtual void SetBufferSize (int numBuffers)
virtual bool WantsDoublePass ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
virtual DEBUG_INFO_VIDEO GetDebugInfo (int idx)
virtual CRenderCapture * GetRenderCapture ()
Static Public Member Functions
static CBaseRenderer * Create (CVideoBuffer *buffer)
static void Register ()
Static Public Member Functions inherited from CBaseRenderer
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
void ManageRenderArea () override
Protected Member Functions inherited from CBaseRenderer
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ReorderDrawPoints ()
virtual EShaderFormat GetShaderFormat ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Private Attributes
bool m_bConfigured = false
int m_iLastRenderBuffer = -1
CRect m_planeDestRect
std::shared_ptr< CVideoLayerBridgeDRMPRIME > m_videoLayerBridge
struct CRendererDRMPRIME::BUFFER m_buffers [NUM_BUFFERS]
Additional Inherited Members
Protected Attributes inherited from CBaseRenderer
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Constructor & Destructor Documentation
CRendererDRMPRIME()
CRendererDRMPRIME::CRendererDRMPRIME () default
Referenced by Create().
~CRendererDRMPRIME()
CRendererDRMPRIME::~CRendererDRMPRIME () override
References Flush().
Member Function Documentation
AddVideoPicture()
void CRendererDRMPRIME::AddVideoPicture (const VideoPicture & picture, int index) override virtual
Implements CBaseRenderer.
References CVideoBuffer::Acquire(), index(), LOGERROR, m_buffers, CVideoBuffer::Release(), VideoPicture::videoBuffer, and CRendererDRMPRIME::BUFFER::videoBuffer.
ConfigChanged()
bool CRendererDRMPRIME::ConfigChanged (const VideoPicture & picture) override virtual
Implements CBaseRenderer.
References CVideoBuffer::GetFormat(), CBaseRenderer::m_format, and VideoPicture::videoBuffer.
Configure()
bool CRendererDRMPRIME::Configure (const VideoPicture & picture, float fps, unsigned int orientation) override virtual
Implements CBaseRenderer.
References CBaseRenderer::CalculateFrameAspectRatio(), VideoPicture::chroma_position, VideoPicture::color_primaries, VideoPicture::color_space, Flush(), GetFlagsChromaPosition(), GetFlagsColorMatrix(), GetFlagsColorPrimaries(), GetFlagsStereoMode(), CVideoBuffer::GetFormat(), VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iHeight, VideoPicture::iWidth, m_bConfigured, CBaseRenderer::m_format, CBaseRenderer::m_iFlags, CBaseRenderer::m_renderOrientation, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, CBaseRenderer::m_videoSettings, CVideoSettings::m_ViewMode, ManageRenderArea(), CBaseRenderer::SetViewMode(), VideoPicture::stereoMode, and VideoPicture::videoBuffer.
Create()
CBaseRenderer * CRendererDRMPRIME::Create (CVideoBuffer * buffer) static
References CRendererDRMPRIME(), KODI::WINDOWING::GBM::CDRMUtils::FourCCWithAlpha(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), and SETTING_VIDEOPLAYER_USEPRIMERENDERER.
Referenced by Register().
Flush()
bool CRendererDRMPRIME::Flush (bool saveBuffers) override virtual
Reimplemented from CBaseRenderer.
References m_iLastRenderBuffer, NUM_BUFFERS, and ReleaseBuffer().
Referenced by Configure(), and ~CRendererDRMPRIME().
GetRenderInfo()
CRenderInfo CRendererDRMPRIME::GetRenderInfo () override virtual
Reimplemented from CBaseRenderer.
References CRenderInfo::max_buffer_size, and NUM_BUFFERS.
IsConfigured()
bool CRendererDRMPRIME::IsConfigured () inline override virtual
Implements CBaseRenderer.
References m_bConfigured.
IsGuiLayer()
bool CRendererDRMPRIME::IsGuiLayer () inline override virtual
Reimplemented from CBaseRenderer.
ManageRenderArea()
void CRendererDRMPRIME::ManageRenderArea () override protected virtual
Reimplemented from CBaseRenderer.
References CBaseRenderer::CalcDestRect(), CBaseRenderer::GetAspectRatio(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CGraphicContext::GetResInfo(), CServiceBroker::GetWinSystem(), CBaseRenderer::m_destRect, m_planeDestRect, and CBaseRenderer::ManageRenderArea().
Referenced by Configure(), and Update().
NeedBuffer()
bool CRendererDRMPRIME::NeedBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References index(), and m_iLastRenderBuffer.
Register()
void CRendererDRMPRIME::Register () static
References Create(), KODI::WINDOWING::GBM::CWinSystemGbm::GetDrm(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), VIDEOPLAYER::CRendererFactory::RegisterRenderer(), and SETTING_VIDEOPLAYER_USEPRIMERENDERER.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem().
ReleaseBuffer()
void CRendererDRMPRIME::ReleaseBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References index(), m_buffers, CVideoBuffer::Release(), and CRendererDRMPRIME::BUFFER::videoBuffer.
Referenced by Flush().
RenderCapture()
bool CRendererDRMPRIME::RenderCapture (int index, CRenderCapture * capture) override virtual
Implements CBaseRenderer.
References CRenderCapture::BeginRender(), and CRenderCapture::EndRender().
RenderUpdate()
void CRendererDRMPRIME::RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override virtual
Implements CBaseRenderer.
References KODI::WINDOWING::GBM::CWinSystemGbm::GetDrm(), KODI::WINDOWING::GBM::CWinSystemGbm::GetVideoLayerBridge(), CServiceBroker::GetWinSystem(), index(), m_buffers, m_iLastRenderBuffer, m_planeDestRect, m_videoLayerBridge, KODI::WINDOWING::GBM::CWinSystemGbm::RegisterVideoLayerBridge(), and CRendererDRMPRIME::BUFFER::videoBuffer.
Supports() [1/2]
bool CRendererDRMPRIME::Supports (ERENDERFEATURE feature) const override virtual
Reimplemented from CBaseRenderer.
References RENDERFEATURE_PIXEL_RATIO, RENDERFEATURE_STRETCH, RENDERFEATURE_VERTICAL_SHIFT, and RENDERFEATURE_ZOOM.
Supports() [2/2]
bool CRendererDRMPRIME::Supports (ESCALINGMETHOD method) const override virtual
Implements CBaseRenderer.
SupportsMultiPassRendering()
bool CRendererDRMPRIME::SupportsMultiPassRendering () inline override virtual
Implements CBaseRenderer.
UnInit()
void CRendererDRMPRIME::UnInit () inline override virtual
Implements CBaseRenderer.
Update()
void CRendererDRMPRIME::Update () override virtual
Implements CBaseRenderer.
References m_bConfigured, and ManageRenderArea().
Member Data Documentation
m_bConfigured
bool CRendererDRMPRIME::m_bConfigured = false private
Referenced by Configure(), IsConfigured(), and Update().
m_buffers
struct CRendererDRMPRIME::BUFFER CRendererDRMPRIME::m_buffers[NUM_BUFFERS] private
Referenced by AddVideoPicture(), ReleaseBuffer(), and RenderUpdate().
m_iLastRenderBuffer
int CRendererDRMPRIME::m_iLastRenderBuffer = -1 private
Referenced by Flush(), NeedBuffer(), and RenderUpdate().
m_planeDestRect
CRect CRendererDRMPRIME::m_planeDestRect private
Referenced by ManageRenderArea(), and RenderUpdate().
m_videoLayerBridge
std::shared_ptr<CVideoLayerBridgeDRMPRIME> CRendererDRMPRIME::m_videoLayerBridge private
Referenced by RenderUpdate().
The documentation for this class was generated from the following files:
RendererDRMPRIME.h
RendererDRMPRIME.cpp