Kodi Documentation: CFileUtils Class Reference
CFileUtils Class Reference
#include <FileUtils.h>
Static Public Member Functions
static bool CheckFileAccessAllowed (const std::string &filePath)
static bool DeleteItem (const std::shared_ptr< CFileItem > &item)
static bool DeleteItem (const std::string &strPath)
static bool Exists (const std::string &strFileName, bool bUseCache=true)
static bool DeleteItemWithConfirm (const std::shared_ptr< CFileItem > &item)
Delete a file with or without gui confirmation unless setting is off.
static bool RenameFile (const std::string &strFile)
static bool RemoteAccessAllowed (const std::string &strPath)
static unsigned int LoadFile (const std::string &filename, void *&outputBuffer)
static CDateTime GetModificationDate (const std::string &strFileNameAndPath, const bool &bUseLatestDate)
Get the modified date of a file if its invalid it returns the creation date - this behavior changes when you set bUseLatestDate.
static CDateTime GetModificationDate (const int &code, const std::string &strFileNameAndPath)
Member Function Documentation
CheckFileAccessAllowed()
bool CFileUtils::CheckFileAccessAllowed (const std::string & filePath) static
References CWIN32Util::AddExtraLongPathPrefix(), g_charsetConverter, CURL::GetProtocol(), IMAGE_FILES::CImageFileURL::GetTargetFile(), CCompileInfo::GetWebserverExtraWhitelist(), URIUtils::IsProtocol(), CLog::Log(), LOGERROR, RemoteAccessAllowed(), CWIN32Util::RemoveExtraLongPathPrefix(), and CSpecialProtocol::TranslatePath().
Referenced by CHTTPImageHandler::CHTTPImageHandler(), CWebServer::CreateFileDownloadResponse(), and CHTTPWebinterfaceHandler::ResolveUrl().
DeleteItem() [1/2]
bool CFileUtils::DeleteItem (const std::shared_ptr< CFileItem > & item) static
References CFileOperationJob::ActionDelete, CFileItemList::Add(), and CFileOperationJob::DoWork().
Referenced by DeleteItem(), DeleteItemWithConfirm(), CProfileManager::DeleteProfile(), anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::DoWork(), ADDON::CAddonInstaller::PrunePackageCache(), XBMCAddon::xbmcvfs::rmdir(), TEST(), TEST(), TEST(), and TEST().
DeleteItem() [2/2]
bool CFileUtils::DeleteItem (const std::string & strPath) static
References DeleteItem(), and URIUtils::HasSlashAtEnd().
DeleteItemWithConfirm()
bool CFileUtils::DeleteItemWithConfirm (const std::shared_ptr< CFileItem > & item) static
Delete a file with or without gui confirmation unless setting is off.
References CGUIComponent::ConfirmDelete(), DeleteItem(), CServiceBroker::GetGUI(), CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_FILELISTS_CONFIRMFILEDELETION.
Referenced by CGUIDialogVideoInfo::DeleteVideoItem(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoBase::OnDeleteItem(), CGUIWindowVideoNav::OnDeleteItem(), and CGUIMediaWindow::OnDeleteItem().
Exists()
bool CFileUtils::Exists (const std::string & strFileName, bool bUseCache = true) static
References XFILE::CFile::Exists().
Referenced by CGUIDialogSubtitleSettings::BrowseForSubtitle(), DllDynamic::CanLoad(), CheckFont(), CHTTPVfsHandler::CHTTPVfsHandler(), ADDON::Interface_GUIWindow::create(), CDVDFactoryInputStream::CreateInputStream(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CPythonInvoker::Execute(), CScriptInvocationManager::ExecuteAsync(), CScriptInvocationManager::ExecuteAsync(), CScriptInvocationManager::ExecuteSync(), XFILE::CFavouritesDirectory::Exists(), JSONRPC::CAddonsOperations::FillDetails(), JSONRPC::CFileOperations::FillFileItem(), JSONRPC::CFileItemHandler::FillFileItemList(), ADDON::CAddonMgr::FindAddons(), CVideoTagLoaderNFO::FindNFO(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), CGUIWindowMusicBase::GetContextButtons(), XFILE::CSourcesDirectory::GetDirectory(), CMediaManager::GetDiscInfo(), JSONRPC::CFileOperations::GetFileDetails(), ADDON::CFontResource::GetFont(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetLocalArt(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkActorHandler::GetLocalArt(), CProgramThumbLoader::GetLocalThumb(), XFILE::CLibraryDirectory::GetNode(), KODI::VIDEO::UTILS::GetOpticalMediaPath(), CRenderSystemGL::GetShaderPath(), CRenderSystemGLES::GetShaderPath(), ADDON::CSkinInfo::GetSkinPath(), CVideoTagLoaderNFO::HasInfo(), CInfoScanner::HasNoMedia(), ADDON::CSkinInfo::HasSkinFile(), ADDON::CImageResource::HasXbt(), PERIPHERALS::CPeripheral::Initialise(), MUSIC_UTILS::anonymous_namespace{MusicUtils.cpp}::IsNonExistingUserPartyModePlaylist(), KODI::VIDEO::UTILS::anonymous_namespace{VideoGUIUtils.cpp}::IsNonExistingUserPartyModePlaylist(), KODI::VIDEO::IsProtectedBlurayDisc(), CPasswordManager::Load(), CRssManager::Load(), CUPnPSettings::Load(), CMediaSourceSettings::Load(), KODI::KEYMAP::CIRTranslator::Load(), CPlayerCoreFactory::LoadConfiguration(), KODI::GAME::CPortManager::LoadXML(), XFILE::CLibraryDirectory::LoadXML(), anonymous_namespace{GUIFontManager.cpp}::LoadXMLData(), CGUIMediaWindow::OnClick(), CGUIDialogContextMenu::OnContextButton(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSongInfo::OnGetArt(), CGUIDialogMediaSource::OnPathBrowse(), KODI::GAME::CGameClient::OpenFile(), CAdvancedSettings::ParseSettingsFile(), CGUIWindowMusicBase::PlayItem(), XBMCAddon::xbmc::playSFX(), CHTTPJsonRpcHandler::CHTTPTransportLayer::PrepareDownload(), CPictureThumbLoader::ProcessFoldersAndArchives(), MUSIC_UTILS::QueueItem(), CFavouritesService::ReInit(), CHTTPWebinterfaceHandler::ResolveUrl(), PVR::CPVRGUIChannelIconUpdater::SearchAndUpdateMissingChannelIcons(), CGUIInfoManager::SetCurrentAlbumThumb(), JSONRPC::CFileOperations::SetFileDetails(), KODI::SUBTITLES::CSubtitlesSettings::SettingOptionsSubtitleFontsFiller(), CGUIDialogSimpleMenu::ShowPlaySelection(), and XBMCAddon::xbmcgui::WindowXML::WindowXML().
GetModificationDate() [1/2]
CDateTime CFileUtils::GetModificationDate (const int & code, const std::string & strFileNameAndPath) static
References __stat64, XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetHostName(), URIUtils::IsInArchive(), URIUtils::IsStack(), CLog::Log(), LOGDEBUG, LOGERROR, and XFILE::CFile::Stat().
GetModificationDate() [2/2]
CDateTime CFileUtils::GetModificationDate (const std::string & strFileNameAndPath, const bool & bUseLatestDate) static
Get the modified date of a file if its invalid it returns the creation date - this behavior changes when you set bUseLatestDate.
Parameters
strFileNameAndPath path to the file
bUseLatestDate use the newer datetime of the files mtime and ctime
Returns
Returns the file date, can return a invalid date if problems occur
References GetModificationDate().
Referenced by CVideoDatabase::GetDateAdded(), CMusicDatabase::GetMediaDateFromFile(), and GetModificationDate().
LoadFile()
static unsigned int CFileUtils::LoadFile (const std::string & filename, void *& outputBuffer) static
RemoteAccessAllowed()
bool CFileUtils::RemoteAccessAllowed (const std::string & strPath) static
Todo:
Make sharing of auto-mounted sources user configurable
References CURL::GetHostName(), CMediaSourceSettings::GetInstance(), CUtil::GetMatchingSource(), CServiceBroker::GetMediaManager(), URIUtils::GetRealPath(), CMediaManager::GetRemovableDrives(), CServiceBroker::GetSettingsComponent(), CMediaSourceSettings::GetSources(), URIUtils::IsInArchive(), LOCK_STATE_LOCKED, URIUtils::RemoveSlashAtEnd(), and CSettings::SETTING_SYSTEM_PLAYLISTSPATH.
Referenced by CheckFileAccessAllowed(), JSONRPC::CFileOperations::GetDirectory(), JSONRPC::CFileOperations::GetFileDetails(), UPNP::ObjectIDValidate(), and JSONRPC::CFileOperations::SetFileDetails().
RenameFile()
bool CFileUtils::RenameFile (const std::string & strFile) static
References URIUtils::AddFileToFolder(), g_localizeStrings, CLocalizeStrings::Get(), URIUtils::GetDirectory(), URIUtils::GetFileName(), XFILE::CMultiPathDirectory::GetPaths(), URIUtils::IsMultiPath(), CLog::Log(), LOGINFO, URIUtils::RemoveSlashAtEnd(), XFILE::CFile::Rename(), CGUIKeyboardFactory::ShowAndGetInput(), and success.
Referenced by CGUIWindowFileManager::OnRename(), and CGUIMediaWindow::OnRenameItem().
The documentation for this class was generated from the following files:
FileUtils.h
FileUtils.cpp