Kodi Documentation: emu_msvcrt.cpp File Reference
emu_msvcrt.cpp File Reference
#include <math.h>
#include <mutex>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <io.h>
#include <direct.h>
#include <process.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <time.h>
#include <signal.h>
#include "CompileInfo.h"
#include "FileItem.h"
#include "FileItemList.h"
#include "ServiceBroker.h"
#include "URL.h"
#include "Util.h"
#include "emu_dummy.h"
#include "emu_msvcrt.h"
#include "filesystem/Directory.h"
#include "filesystem/File.h"
#include "filesystem/SpecialProtocol.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "util/EmuFileWrapper.h"
#include "utils/log.h"
#include "utils/CharsetConverter.h"
#include "utils/URIUtils.h"
#include <dlfcn.h>
#include "platform/Environment.h"
#include "utils/StringUtils.h"
#include "utils/XTimeUtils.h"
Classes
struct SDirData
Macros
#define MAX_OPEN_DIRS 10
#define EMU_MAX_ENVIRONMENT_ITEMS 100
Functions
void update_cache_dialog (const char *tmp)
void __stdcall init_emu_environ ()
void __stdcall update_emu_environ ()
void __stdcall cleanup_emu_environ ()
static int convert_fmode (const char *mode)
void dll_sleep (unsigned long imSec)
void dllReleaseAll ()
void * dllmalloc (size_t size)
void dllfree (void *pPtr)
void * dllcalloc (size_t num, size_t size)
void * dllrealloc (void *memblock, size_t size)
void dllexit (int iCode)
void dllabort ()
void * dll__dllonexit (PFV input, PFV **start, PFV **end)
_onexit_t dll_onexit (_onexit_t func)
int dllputs (const char *szLine)
int dllprintf (const char *format,...)
char * dll_fullpath (char *absPath, const char *relPath, size_t maxLength)
FILE * dll_popen (const char *command, const char *mode)
void * dll_dlopen (const char *filename, int flag)
int dll_pclose (FILE *stream)
FILE * dll_fdopen (int fd, const char *mode)
int dll_open (const char *szFileName, int iMode)
FILE * dll_freopen (const char *path, const char *mode, FILE *stream)
int dll_read (int fd, void *buffer, unsigned int uiSize)
int dll_write (int fd, const void *buffer, unsigned int uiSize)
int dll_fstat64 (int fd, struct __stat64 *buf)
int dll_close (int fd)
__off64_t dll_lseeki64 (int fd, __off64_t lPos, int iWhence)
__off_t dll_lseek (int fd, __off_t lPos, int iWhence)
void dll_rewind (FILE *stream)
void dll_flockfile (FILE *stream)
int dll_ftrylockfile (FILE *stream)
void dll_funlockfile (FILE *stream)
int dll_fclose (FILE *stream)
intptr_t dll_findfirst (const char *file, struct _finddata_t *data)
intptr_t dll_findfirst64i32 (const char *file, struct _finddata64i32_t *data)
int dll_findnext (intptr_t f, _finddata_t *data)
int dll_findnext64i32 (intptr_t f, _finddata64i32_t *data)
int dll_findclose (intptr_t handle)
void dll__security_error_handler (int code, void *data)
DIR * dll_opendir (const char *file)
struct dirent * dll_readdir (DIR *dirp)
int dll_closedir (DIR *dirp)
void dll_rewinddir (DIR *dirp)
char * dll_fgets (char *pszString, int num, FILE *stream)
int dll_feof (FILE *stream)
int dll_fread (void *buffer, size_t size, size_t count, FILE *stream)
int dll_fgetc (FILE *stream)
int dll_getc (FILE *stream)
FILE * dll_fopen (const char *filename, const char *mode)
int dll_fopen_s (FILE **pFile, const char *filename, const char *mode)
int dll_putc (int c, FILE *stream)
int dll_putchar (int c)
int dll_fputc (int character, FILE *stream)
int dll_fputs (const char *szLine, FILE *stream)
int dll_fseek64 (FILE *stream, off64_t offset, int origin)
int dll_fseek (FILE *stream, long offset, int origin)
int dll_ungetc (int c, FILE *stream)
long dll_ftell (FILE *stream)
off64_t dll_ftell64 (FILE *stream)
long dll_tell (int fd)
long long dll_telli64 (int fd)
size_t dll_fwrite (const void *buffer, size_t size, size_t count, FILE *stream)
int dll_fflush (FILE *stream)
int dll_ferror (FILE *stream)
int dllvprintf (const char *format, va_list va)
int dll_vfprintf (FILE *stream, const char *format, va_list va)
int dll_fscanf (FILE *stream, const char *format,...)
int dll_fprintf (FILE *stream, const char *format,...)
int dll_fgetpos (FILE *stream, fpos_t *pos)
int dll_fgetpos64 (FILE *stream, fpos64_t *pos)
int dll_fsetpos64 (FILE *stream, const fpos64_t *pos)
int dll_fsetpos (FILE *stream, const fpos_t *pos)
int dll_fileno (FILE *stream)
void dll_clearerr (FILE *stream)
char * dll_strdup (const char *str)
int dll_initterm (PFV *start, const PFV *end)
int dll_stat (const char *path, struct stat *buffer)
int dll_stati64 (const char *path, struct _stati64 *buffer)
int dll_stat64 (const char *path, struct __stat64 *buffer)
int dll_fstat (int fd, struct stat *buffer)
int dll_fstati64 (int fd, struct _stati64 *buffer)
int dll_setmode (int handle, int mode)
void dllperror (const char *s)
char * dllstrerror (int iErr)
int dll_mkdir (const char *dir)
const char * dll_getcwd (char *buffer, int maxlen)
int dll_putenv (const char *envstring)
char * dll_getenv (const char *szKey)
int dll_ctype (int i)
int dll_system (const char *command)
void (__cdecl *dll_signal(int sig, void(__cdecl *func)(int)))(int)
int dll_getpid ()
int dll__commit (int fd)
char *** dll___p__environ ()
int dll_setvbuf (FILE *stream, char *buf, int type, size_t size)
struct mntent * dll_getmntent (FILE *fp)
struct mntent * dll_getmntent_r (FILE *fp, struct mntent *result, char *buffer, int bufsize)
int __cdecl dll_open_osfhandle (intptr_t _OSFileHandle, int _Flags)
Variables
static SDirData vecDirsOpen [MAX_OPEN_DIRS]
bool bVecDirsInited = false
static char * dll__environ_imp [EMU_MAX_ENVIRONMENT_ITEMS+1]
char ** dll__environ = dll__environ_imp
CCriticalSection dll_cs_environ
Macro Definition Documentation
EMU_MAX_ENVIRONMENT_ITEMS
#define EMU_MAX_ENVIRONMENT_ITEMS 100
MAX_OPEN_DIRS
#define MAX_OPEN_DIRS 10
Function Documentation
cleanup_emu_environ()
void __stdcall cleanup_emu_environ ()
References dll__environ, and EMU_MAX_ENVIRONMENT_ITEMS.
Referenced by CApplication::Stop().
convert_fmode()
static int convert_fmode (const char * mode) static
References _O_RDONLY, _O_TRUNC, _O_WRONLY, and O_BINARY.
Referenced by dll_fdopen(), and dll_fopen().
dll___p__environ()
char *** dll___p__environ ()
References dll__environ, and t.
dll__commit()
int dll__commit (int fd)
References XFILE::CFile::Flush(), g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), and IS_STD_DESCRIPTOR.
dll__dllonexit()
void * dll__dllonexit (PFV input, PFV ** start, PFV ** end)
References end().
dll__security_error_handler()
void dll__security_error_handler (int code, void * data)
References CLog::Log(), and LOGERROR.
dll_clearerr()
void dll_clearerr (FILE * stream)
References g_emuFileWrapper, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_clearerr().
dll_close()
int dll_close (int fd)
References XFILE::CFile::Close(), g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGERROR, and CEmuFileWrapper::UnRegisterFileObjectByDescriptor().
Referenced by __wrap_close(), and dll_fclose().
dll_closedir()
int dll_closedir (DIR * dirp)
References CFileItemList::Clear(), closedir(), SDirData::curr_index, SDirData::items, SDirData::last_entry, and vecDirsOpen.
Referenced by __wrap_closedir().
dll_ctype()
int dll_ctype (int i)
References not_implement().
dll_dlopen()
void * dll_dlopen (const char * filename, int flag)
dll_fclose()
int dll_fclose (FILE * stream)
References dll_close(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), and LOGERROR.
Referenced by __wrap_fclose(), and dll_freopen().
dll_fdopen()
FILE * dll_fdopen (int fd, const char * mode)
References _fdopen, convert_fmode(), g_emuFileWrapper, CEmuFileWrapper::GetFileObjectByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGWARNING, stEmuFileObject::mode, not_implement(), and stEmuFileObject::used.
Referenced by __wrap_fdopen().
dll_feof()
int dll_feof (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), XFILE::CFile::GetLength(), XFILE::CFile::GetPosition(), CLog::Log(), and LOGERROR.
Referenced by __wrap_feof().
dll_ferror()
int dll_ferror (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), and IS_STD_STREAM.
Referenced by __wrap_ferror().
dll_fflush()
int dll_fflush (FILE * stream)
References XFILE::CFile::Flush(), g_emuFileWrapper, and CEmuFileWrapper::GetFileXbmcByStream().
Referenced by __wrap_fflush().
dll_fgetc()
int dll_fgetc (FILE * stream)
References dll_fread(), g_emuFileWrapper, CLog::Log(), LOGERROR, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_fgetc(), dll_getc(), and dll_ungetc().
dll_fgetpos()
int dll_fgetpos (FILE * stream, fpos_t * pos)
References dll_fgetpos64().
Referenced by __wrap_fgetpos().
dll_fgetpos64()
int dll_fgetpos64 (FILE * stream, fpos64_t * pos)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), XFILE::CFile::GetPosition(), CLog::Log(), and LOGERROR.
Referenced by __wrap_fgetpos64(), and dll_fgetpos().
dll_fgets()
char * dll_fgets (char * pszString, int num, FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), XFILE::CFile::GetLength(), XFILE::CFile::GetPosition(), CLog::Log(), LOGERROR, and XFILE::CFile::ReadString().
Referenced by __wrap_fgets().
dll_fileno()
int dll_fileno (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), IS_STDERR_STREAM, IS_STDIN_STREAM, and IS_STDOUT_STREAM.
Referenced by __wrap_fileno().
dll_findclose()
int dll_findclose (intptr_t handle)
References CFileItemList::Clear(), SDirData::curr_index, SDirData::items, MAX_OPEN_DIRS, and vecDirsOpen.
dll_findfirst()
intptr_t dll_findfirst (const char * file, struct _finddata_t * data)
References data(), and dll_findfirst64i32().
dll_findfirst64i32()
intptr_t dll_findfirst64i32 (const char * file, struct _finddata64i32_t * data)
References bVecDirsInited, CFileItemList::Clear(), SDirData::curr_index, data(), XFILE::DIR_FLAG_DEFAULTS, g_charsetConverter, CURL::Get(), XFILE::CDirectory::GetDirectory(), URIUtils::GetExtension(), CURL::GetFileName(), CGUIListItem::GetLabel(), CURL::IsLocal(), SDirData::items, CFileItem::m_dwSize, MAX_OPEN_DIRS, KODI::UTILS::StringUtils::Replace(), CURL::SetFileName(), CSpecialProtocol::TranslatePath(), CUtil::ValidatePath(), and vecDirsOpen.
Referenced by dll_findfirst().
dll_findnext()
int dll_findnext (intptr_t f, _finddata_t * data)
References data(), dll_findnext64i32(), and f.
dll_findnext64i32()
int dll_findnext64i32 (intptr_t f, _finddata64i32_t * data)
References CFileItemList::Clear(), SDirData::curr_index, data(), f, CGUIListItem::GetLabel(), SDirData::items, CFileItem::m_dwSize, MAX_OPEN_DIRS, and vecDirsOpen.
Referenced by dll_findnext().
dll_flockfile()
void dll_flockfile (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CEmuFileWrapper::LockFileObjectByDescriptor(), CLog::Log(), and LOGERROR.
Referenced by __wrap_flockfile().
dll_fopen()
FILE * dll_fopen (const char * filename, const char * mode)
References convert_fmode(), dll_open(), g_emuFileWrapper, CEmuFileWrapper::GetStreamByDescriptor(), CLog::Log(), and LOGINFO.
Referenced by __wrap_fopen(), __wrap_fopen64(), dll_fopen_s(), and dll_freopen().
dll_fopen_s()
int dll_fopen_s (FILE ** pFile, const char * filename, const char * mode)
References dll_fopen().
dll_fprintf()
int dll_fprintf (FILE * stream, const char * format, ...)
References dll_vfprintf().
dll_fputc()
int dll_fputc (int character, FILE * stream)
References dll_write(), dllputs(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), IS_STDERR_STREAM, IS_STDOUT_STREAM, IS_VALID_STREAM, CLog::Log(), LOGERROR, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_fputc(), and dll_putc().
dll_fputs()
int dll_fputs (const char * szLine, FILE * stream)
References dll_fwrite(), dllputs(), g_emuFileWrapper, IS_STDERR_STREAM, IS_STDOUT_STREAM, IS_VALID_STREAM, CLog::Log(), LOGERROR, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_fputs().
dll_fread()
int dll_fread (void * buffer, size_t size, size_t count, FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), CLog::Log(), LOGERROR, and XFILE::CFile::Read().
Referenced by __wrap_fread(), and dll_fgetc().
dll_freopen()
FILE * dll_freopen (const char * path, const char * mode, FILE * stream)
References dll_fclose(), dll_fopen(), g_emuFileWrapper, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_freopen().
dll_fscanf()
int dll_fscanf (FILE * stream, const char * format, ...)
References CLog::Log(), and LOGERROR.
dll_fseek()
int dll_fseek (FILE * stream, long offset, int origin)
References dll_fseek64().
Referenced by __wrap_fseek(), and dll_ungetc().
dll_fseek64()
int dll_fseek64 (FILE * stream, off64_t offset, int origin)
References dll_lseeki64(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), and LOGERROR.
Referenced by __wrap_fseeko64(), and dll_fseek().
dll_fsetpos()
int dll_fsetpos (FILE * stream, const fpos_t * pos)
References dll_fsetpos64(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), and LOGERROR.
Referenced by __wrap_fsetpos().
dll_fsetpos64()
int dll_fsetpos64 (FILE * stream, const fpos64_t * pos)
References dll_lseeki64(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), and LOGERROR.
Referenced by __wrap_fsetpos64(), and dll_fsetpos().
dll_fstat()
int dll_fstat (int fd, struct stat * buffer)
References __stat64, g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), IS_STD_DESCRIPTOR, XFILE::CFile::Stat(), and CUtil::Stat64ToStat().
dll_fstat64()
int dll_fstat64 (int fd, struct __stat64 * buf)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGERROR, and XFILE::CFile::Stat().
dll_fstati64()
int dll_fstati64 (int fd, struct _stati64 * buffer)
References _S_IFREG, g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), XFILE::CFile::GetLength(), IS_STD_DESCRIPTOR, CLog::Log(), LOGINFO, LOGWARNING, and CUtil::StatToStatI64().
dll_ftell()
long dll_ftell (FILE * stream)
References dll_ftell64().
Referenced by __wrap_ftell().
dll_ftell64()
off64_t dll_ftell64 (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), XFILE::CFile::GetPosition(), CLog::Log(), and LOGERROR.
Referenced by __wrap_ftello64(), and dll_ftell().
dll_ftrylockfile()
int dll_ftrylockfile (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), LOGERROR, and CEmuFileWrapper::TryLockFileObjectByDescriptor().
Referenced by __wrap_ftrylockfile().
dll_fullpath()
char * dll_fullpath (char * absPath, const char * relPath, size_t maxLength)
References dll_strdup(), and not_implement().
dll_funlockfile()
void dll_funlockfile (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), LOGERROR, and CEmuFileWrapper::UnlockFileObjectByDescriptor().
Referenced by __wrap_funlockfile().
dll_fwrite()
size_t dll_fwrite (const void * buffer, size_t size, size_t count, FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), IS_STDERR_STREAM, IS_STDOUT_STREAM, IS_VALID_STREAM, CLog::Log(), LOGDEBUG, LOGERROR, and XFILE::CFile::Write().
Referenced by __wrap_fwrite(), and dll_fputs().
dll_getc()
int dll_getc (FILE * stream)
References dll_fgetc(), g_emuFileWrapper, CLog::Log(), LOGERROR, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap__IO_getc(), __wrap__IO_getc_unlocked(), __wrap_getc(), and __wrap_getc_unlocked().
dll_getcwd()
const char * dll_getcwd (char * buffer, int maxlen)
References not_implement().
dll_getenv()
char * dll_getenv (const char * szKey)
References KODI::UTILS::StringUtils::CompareNoCase(), dll__environ, dll_cs_environ, EMU_MAX_ENVIRONMENT_ITEMS, update_emu_environ(), and value.
dll_getmntent()
struct mntent * dll_getmntent (FILE * fp)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), and LOGWARNING.
Referenced by __wrap_getmntent().
dll_getmntent_r()
struct mntent * dll_getmntent_r (FILE * fp, struct mntent * result, char * buffer, int bufsize)
Referenced by __wrap_getmntent_r().
dll_getpid()
int dll_getpid ()
dll_initterm()
int dll_initterm (PFV * start, const PFV * end)
References end().
dll_lseek()
__off_t dll_lseek (int fd, __off_t lPos, int iWhence)
References CEmuFileWrapper::DescriptorIsEmulatedFile(), dll_lseeki64(), g_emuFileWrapper, IS_STD_DESCRIPTOR, CLog::Log(), and LOGERROR.
Referenced by __wrap_lseek().
dll_lseeki64()
__off64_t dll_lseeki64 (int fd, __off64_t lPos, int iWhence)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGERROR, LOGWARNING, and XFILE::CFile::Seek().
Referenced by __wrap_lseek64(), dll_fseek64(), dll_fsetpos64(), dll_lseek(), and dll_rewind().
dll_mkdir()
int dll_mkdir (const char * dir)
References g_charsetConverter, mkdir(), CSpecialProtocol::TranslatePath(), and CUtil::ValidatePath().
dll_onexit()
_onexit_t dll_onexit (_onexit_t func)
References not_implement().
dll_open()
int dll_open (const char * szFileName, int iMode)
References _O_TRUNC, XFILE::CFile::Close(), f, g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), XFILE::CFile::Open(), XFILE::CFile::OpenForWrite(), XFILE::READ_TRUNCATED, CEmuFileWrapper::RegisterFileObject(), and CUtil::ValidatePath().
Referenced by __wrap_open(), __wrap_open64(), and dll_fopen().
dll_open_osfhandle()
int __cdecl dll_open_osfhandle (intptr_t _OSFileHandle, int _Flags)
dll_opendir()
DIR * dll_opendir (const char * file)
References bVecDirsInited, CFileItemList::Clear(), SDirData::curr_index, XFILE::DIR_FLAG_DEFAULTS, CURL::Get(), XFILE::CDirectory::GetDirectory(), CURL::IsLocal(), SDirData::items, CLog::Log(), LOGDEBUG, MAX_OPEN_DIRS, opendir(), CSpecialProtocol::TranslatePath(), CUtil::ValidatePath(), and vecDirsOpen.
Referenced by __wrap_opendir().
dll_pclose()
int dll_pclose (FILE * stream)
References not_implement().
dll_popen()
FILE * dll_popen (const char * command, const char * mode)
References not_implement().
Referenced by __wrap_popen().
dll_putc()
int dll_putc (int c, FILE * stream)
References dll_fputc(), g_emuFileWrapper, IS_STD_STREAM, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap__IO_putc(), and dll_putchar().
dll_putchar()
int dll_putchar (int c)
References dll_putc().
dll_putenv()
int dll_putenv (const char * envstring)
References KODI::UTILS::StringUtils::CompareNoCase(), dll__environ, dll_cs_environ, EMU_MAX_ENVIRONMENT_ITEMS, and value.
Referenced by init_emu_environ(), and update_emu_environ().
dll_read()
int dll_read (int fd, void * buffer, unsigned int uiSize)
References err(), g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGERROR, and XFILE::CFile::Read().
Referenced by __wrap_read().
dll_readdir()
struct dirent * dll_readdir (DIR * dirp)
References SDirData::curr_index, dirent::d_name, CGUIListItem::GetLabel(), SDirData::items, SDirData::last_entry, readdir(), CFileItemList::Size(), and vecDirsOpen.
Referenced by __wrap_readdir(), and __wrap_readdir64().
dll_rewind()
void dll_rewind (FILE * stream)
References dll_lseeki64(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), and LOGERROR.
Referenced by __wrap_rewind().
dll_rewinddir()
void dll_rewinddir (DIR * dirp)
References SDirData::curr_index, SDirData::last_entry, rewinddir(), and vecDirsOpen.
Referenced by __wrap_rewinddir().
dll_setmode()
int dll_setmode (int handle, int mode)
References not_implement().
dll_setvbuf()
int dll_setvbuf (FILE * stream, char * buf, int type, size_t size)
References CLog::Log(), and LOGWARNING.
Referenced by __wrap_setvbuf().
dll_sleep()
void dll_sleep (unsigned long imSec)
References KODI::TIME::Sleep().
dll_stat()
int dll_stat (const char * path, struct stat * buffer)
References __stat64, _S_IFDIR, KODI::UTILS::StringUtils::CompareNoCase(), S_IFDIR, XFILE::CFile::Stat(), and CUtil::Stat64ToStat().
dll_stat64()
int dll_stat64 (const char * path, struct __stat64 * buffer)
References _S_IFDIR, KODI::UTILS::StringUtils::CompareNoCase(), and XFILE::CFile::Stat().
Referenced by dll_stati64().
dll_stati64()
int dll_stati64 (const char * path, struct _stati64 * buffer)
References __stat64, dll_stat64(), and CUtil::Stat64ToStatI64().
dll_strdup()
char * dll_strdup (const char * str)
Referenced by dll_fullpath().
dll_system()
int dll_system (const char * command)
References not_implement().
dll_tell()
long dll_tell (int fd)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), XFILE::CFile::GetPosition(), IS_STD_DESCRIPTOR, CLog::Log(), and LOGERROR.
dll_telli64()
long long dll_telli64 (int fd)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), XFILE::CFile::GetPosition(), IS_STD_DESCRIPTOR, CLog::Log(), LOGERROR, and LOGWARNING.
dll_ungetc()
int dll_ungetc (int c, FILE * stream)
References dll_fgetc(), dll_fseek(), g_emuFileWrapper, CLog::Log(), LOGERROR, LOGWARNING, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_ungetc().
dll_vfprintf()
int dll_vfprintf (FILE * stream, const char * format, va_list va)
References _vsnprintf, g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), IS_STDERR_STREAM, IS_STDOUT_STREAM, IS_VALID_STREAM, CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, and XFILE::CFile::Write().
Referenced by __wrap_fprintf(), __wrap_printf(), __wrap_vfprintf(), and dll_fprintf().
dll_write()
int dll_write (int fd, const void * buffer, unsigned int uiSize)
References err(), g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGERROR, and XFILE::CFile::Write().
Referenced by __wrap_write(), and dll_fputc().
dllabort()
void dllabort ()
References not_implement().
dllcalloc()
void * dllcalloc (size_t num, size_t size)
References CLog::Log(), and LOGFATAL.
Referenced by __wrap_calloc().
dllexit()
void dllexit (int iCode)
References not_implement().
dllfree()
void dllfree (void * pPtr)
Referenced by __wrap_free().
dllmalloc()
void * dllmalloc (size_t size)
References CLog::Log(), and LOGFATAL.
Referenced by __wrap_malloc().
dllperror()
void dllperror (const char * s)
References CLog::Log(), and LOGERROR.
dllprintf()
int dllprintf (const char * format, ...)
References _vsnprintf, CLog::Log(), and LOGDEBUG.
dllputs()
int dllputs (const char * szLine)
References CLog::Log(), and LOGDEBUG.
Referenced by dll_fputc(), and dll_fputs().
dllrealloc()
void * dllrealloc (void * memblock, size_t size)
References CLog::Log(), and LOGFATAL.
Referenced by __wrap_realloc().
dllReleaseAll()
void dllReleaseAll ()
References bVecDirsInited, and vecDirsOpen.
dllstrerror()
char * dllstrerror (int iErr)
dllvprintf()
int dllvprintf (const char * format, va_list va)
References KODI::UTILS::StringUtils::FormatV(), CLog::Log(), and LOGDEBUG.
init_emu_environ()
void __stdcall init_emu_environ ()
References dll__environ, dll_putenv(), EMU_MAX_ENVIRONMENT_ITEMS, KODI::PLATFORM::WINDOWS::FromW(), CUtil::GetFrameworksPath(), CCompileInfo::GetPythonVersion(), and CSpecialProtocol::TranslatePath().
Referenced by CApplication::Create().
update_cache_dialog()
void update_cache_dialog (const char * tmp) extern
update_emu_environ()
void __stdcall update_emu_environ ()
References dll_putenv(), KODI::UTILS::StringUtils::Format(), CServiceBroker::GetSettingsComponent(), CEnvironment::setenv(), CSettings::SETTING_NETWORK_HTTPPROXYPASSWORD, CSettings::SETTING_NETWORK_HTTPPROXYPORT, CSettings::SETTING_NETWORK_HTTPPROXYSERVER, CSettings::SETTING_NETWORK_HTTPPROXYTYPE, CSettings::SETTING_NETWORK_HTTPPROXYUSERNAME, and CSettings::SETTING_NETWORK_USEHTTPPROXY.
Referenced by CApplication::Create(), and dll_getenv().
void()
void (__cdecl * dll_signalint sig, void(__cdecl *func)(int))
Variable Documentation
bVecDirsInited
bool bVecDirsInited = false
Referenced by dll_findfirst64i32(), dll_opendir(), and dllReleaseAll().
dll__environ
char ** dll__environ = dll__environ_imp
Referenced by cleanup_emu_environ(), dll___p__environ(), dll_getenv(), dll_putenv(), and init_emu_environ().
dll__environ_imp
char* dll__environ_imp[EMU_MAX_ENVIRONMENT_ITEMS+1] static
dll_cs_environ
CCriticalSection dll_cs_environ
Referenced by dll_getenv(), and dll_putenv().
vecDirsOpen
SDirData vecDirsOpen[MAX_OPEN_DIRS] static
Referenced by dll_closedir(), dll_findclose(), dll_findfirst64i32(), dll_findnext64i32(), dll_opendir(), dll_readdir(), dll_rewinddir(), and dllReleaseAll().