Kodi Documentation: anonymous_namespace{EpgTagsContainer.cpp} Namespace Reference
anonymous_namespace{EpgTagsContainer.cpp} Namespace Reference
Functions
void ResolveConflictingTags (const std::shared_ptr< CPVREpgInfoTag > &changedTag, std::vector< std::shared_ptr< CPVREpgInfoTag > > &tags)
bool FixOverlap (const std::shared_ptr< CPVREpgInfoTag > &previousTag, const std::shared_ptr< CPVREpgInfoTag > &currentTag)
Variables
const CDateTimeSpan ONE_SECOND (0, 0, 0, 1)
Function Documentation
FixOverlap()
bool anonymous_namespace{EpgTagsContainer.cpp}::FixOverlap (const std::shared_ptr< CPVREpgInfoTag > & previousTag, const std::shared_ptr< CPVREpgInfoTag > & currentTag)
References FixOverlap(), and LOGDEBUG.
Referenced by FixOverlap().
ResolveConflictingTags()
void anonymous_namespace{EpgTagsContainer.cpp}::ResolveConflictingTags (const std::shared_ptr< CPVREpgInfoTag > & changedTag, std::vector< std::shared_ptr< CPVREpgInfoTag > > & tags)
References ResolveConflictingTags(), and tags.
Referenced by ResolveConflictingTags().
Variable Documentation
ONE_SECOND
const CDateTimeSpan anonymous_namespace{EpgTagsContainer.cpp}::ONE_SECOND(0, 0, 0, 1) (0 , 0 , 0 , 1)