Kodi Documentation: XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSingles Class Reference
XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSingles Class Reference
#include <DirectoryNodeSingles.h>
Public Member Functions
CDirectoryNodeSingles (const std::string &strName, CDirectoryNode *pParent)
Public Member Functions inherited from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode
virtual ~CDirectoryNode ()
NODE_TYPE GetType () const
bool GetChilds (CFileItemList &items)
virtual NODE_TYPE GetChildType () const
virtual std::string GetLocalizedName () const
CDirectoryNode * GetParent () const
virtual bool CanCache () const
std::string BuildPath () const
Protected Member Functions
bool GetContent (CFileItemList &items) const override
Protected Member Functions inherited from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode
CDirectoryNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
void AddOptions (const std::string &options)
void CollectQueryParams (CQueryParams &params) const
const std::string & GetName () const
int GetID () const
void RemoveParent ()
Additional Inherited Members
Static Public Member Functions inherited from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode
static CDirectoryNode * ParseURL (const std::string &strPath)
static void GetDatabaseInfo (const std::string &strPath, CQueryParams &params)
static bool GetNodeInfo (const std::string &strPath, NODE_TYPE &type, NODE_TYPE &childtype, CQueryParams &params)
Static Protected Member Functions inherited from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode
static CDirectoryNode * CreateNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
Constructor & Destructor Documentation
CDirectoryNodeSingles()
CDirectoryNodeSingles::CDirectoryNodeSingles (const std::string & strName, CDirectoryNode * pParent)
Member Function Documentation
GetContent()
bool CDirectoryNodeSingles::GetContent (CFileItemList & items) const override protected virtual
Reimplemented from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode.
References XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::BuildPath(), CDatabase::Close(), CMusicDatabase::GetSongsFullByWhere(), and CMusicDatabase::Open().
The documentation for this class was generated from the following files:
DirectoryNodeSingles.h
DirectoryNodeSingles.cpp