Kodi Documentation: XBMCAddon::AddonCallback Class Reference
XBMCAddon::AddonCallback Class Reference
#include <AddonCallback.h>
Public Member Functions
~AddonCallback () override
void setHandler (CallbackHandler *_handler)
void invokeCallback (Callback *callback)
Public Member Functions inherited from XBMCAddon::AddonClass
AddonClass ()
virtual ~AddonClass ()
const char * GetClassname () const
LanguageHook * GetLanguageHook ()
bool isDeallocating ()
void Release () const
void Acquire () const
Protected Member Functions
bool hasHandler ()
AddonCallback ()
Protected Member Functions inherited from XBMCAddon::AddonClass
virtual void deallocating ()
Protected Attributes
AddonClass::Ref< CallbackHandler > handler
Protected Attributes inherited from XBMCAddon::AddonClass
LanguageHook * languageHook
Additional Inherited Members
Static Public Member Functions inherited from XBMCAddon::AddonClass
static short getNumAddonClasses ()
Static Protected Member Functions inherited from XBMCAddon::AddonClass
static short getNextClassIndex ()
Detailed Description
This class is the superclass for all API classes that are expected to be able to handle cross-language polymorphism.
Constructor & Destructor Documentation
AddonCallback()
XBMCAddon::AddonCallback::AddonCallback () inline protected
References XBMCAddon::LanguageHook::GetCallbackHandler(), XBMCAddon::AddonClass::languageHook, and setHandler().
~AddonCallback()
XBMCAddon::AddonCallback::~AddonCallback () override default
Member Function Documentation
hasHandler()
bool XBMCAddon::AddonCallback::hasHandler () inline protected
References handler.
Referenced by invokeCallback().
invokeCallback()
void XBMCAddon::AddonCallback::invokeCallback (Callback * callback)
References handler, and hasHandler().
Referenced by XBMCAddon::xbmcgui::Window::OnAction(), XBMCAddon::xbmcgui::WindowXML::OnAction(), XBMCAddon::xbmc::Monitor::OnCleanFinished(), XBMCAddon::xbmc::Monitor::OnCleanStarted(), XBMCAddon::xbmc::Monitor::OnDPMSActivated(), XBMCAddon::xbmc::Monitor::OnDPMSDeactivated(), XBMCAddon::xbmcgui::Window::OnMessage(), XBMCAddon::xbmcgui::WindowXML::OnMessage(), XBMCAddon::xbmc::Monitor::OnNotification(), XBMCAddon::xbmc::Monitor::OnScanFinished(), XBMCAddon::xbmc::Monitor::OnScanStarted(), XBMCAddon::xbmc::Monitor::OnScreensaverActivated(), XBMCAddon::xbmc::Monitor::OnScreensaverDeactivated(), and XBMCAddon::xbmc::Monitor::OnSettingsChanged().
setHandler()
void XBMCAddon::AddonCallback::setHandler (CallbackHandler * _handler) inline
References handler.
Referenced by AddonCallback().
Member Data Documentation
handler
AddonClass::Ref<CallbackHandler> XBMCAddon::AddonCallback::handler protected
Referenced by hasHandler(), invokeCallback(), and setHandler().
The documentation for this class was generated from the following files:
AddonCallback.h
AddonCallback.cpp