Kodi Documentation: XFILE::CFileFactory Class Reference
XFILE::CFileFactory Class Reference
#include <FileFactory.h>
Public Member Functions
CFileFactory ()
virtual ~CFileFactory ()
Static Public Member Functions
static IFile * CreateLoader (const std::string &strFileName)
static IFile * CreateLoader (const CURL &url)
Constructor & Destructor Documentation
CFileFactory()
CFileFactory::CFileFactory () default
~CFileFactory()
CFileFactory::~CFileFactory () virtual default
Member Function Documentation
CreateLoader() [1/2]
IFile * CFileFactory::CreateLoader (const CURL & url) static
References ADDON::CVFSAddonCache::GetAddonInstances(), CWakeOnAccess::GetInstance(), CURL::GetProtocol(), CURL::GetRedacted(), CServiceBroker::GetVFSAddonCache(), CServiceBroker::IsAddonInterfaceUp(), XFILE::CWinLibraryFile::IsInAccessList(), CURL::IsProtocol(), XFILE::CWinLibraryFile::IsValid(), CLog::Log(), LOGWARNING, and XFILE::CTVOSFile::WantsFile().
CreateLoader() [2/2]
IFile * CFileFactory::CreateLoader (const std::string & strFileName) static
References CreateLoader().
Referenced by CreateLoader(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), XFILE::CUPnPFile::Exists(), XFILE::CFile::Open(), XFILE::CFileStream::Open(), XFILE::CUPnPFile::Open(), NPT_XbmcFile::Open(), XFILE::CFile::OpenForWrite(), XFILE::CFile::Rename(), XFILE::CFile::SetHidden(), XFILE::CFile::Stat(), and XFILE::CUPnPFile::Stat().
The documentation for this class was generated from the following files:
FileFactory.h
FileFactory.cpp