Kodi Documentation: KODI::GAME::CControllerGrid Class Reference
KODI::GAME::CControllerGrid Class Reference
Games
Class to encapsulate grid operations.
#include <ControllerGrid.h>
Public Member Functions
CControllerGrid ()=default
CControllerGrid (const CControllerGrid &other)=default
~CControllerGrid ()
void SetControllerTree (const CControllerTree &controllerTree)
Create a grid from a controller tree.
unsigned int GetWidth () const
Get the width of the controller grid.
unsigned int GetHeight () const
Get the height (deepest controller) of the controller grid.
const ControllerGrid & GetGrid () const
Access the controller grid.
ControllerVector GetControllers (unsigned int playerIndex) const
Get the controllers in use by the specified player.
Private Types
enum class GRID_DIRECTION { RIGHT , DOWN }
Directions of vertex traversal.
Static Private Member Functions
static unsigned int AddPorts (const PortVec &ports, ControllerGrid &grid)
Add ports to the grid.
static unsigned int AddController (const CPortNode &port, unsigned int height, std::vector< ControllerVertex > &column, ControllerGrid &grid)
Draw a controller to the column at the specified height.
static unsigned int AddHub (const PortVec &ports, unsigned int height, bool bSkipFirst, ControllerGrid &grid)
Draw a series of controllers to the grid at the specified height.
static void AddInvisible (std::vector< ControllerVertex > &column)
Draw an invisible vertex to the column.
static void SetHeight (unsigned int height, ControllerGrid &grid)
Fill all columns with invisible vertices until the specified height.
static GRID_DIRECTION GetDirection (const CControllerNode &node)
Get the direction of traversal for the next vertex.
Private Attributes
ControllerGrid m_grid
unsigned int m_height = 0
Detailed Description
Class to encapsulate grid operations.
Member Enumeration Documentation
GRID_DIRECTION
enum class KODI::GAME::CControllerGrid::GRID_DIRECTION strong private
Directions of vertex traversal.
Enumerator
RIGHT
DOWN
Constructor & Destructor Documentation
CControllerGrid() [1/2]
KODI::GAME::CControllerGrid::CControllerGrid () default
CControllerGrid() [2/2]
KODI::GAME::CControllerGrid::CControllerGrid (const CControllerGrid & other) default
~CControllerGrid()
CControllerGrid::~CControllerGrid () default
Member Function Documentation
AddController()
unsigned int CControllerGrid::AddController (const CPortNode & port, unsigned int height, std::vector< ControllerVertex > & column, ControllerGrid & grid) static private
Draw a controller to the column at the specified height.
Parameters
port The controller's port node
height The height to draw the controller at
column[in/out] The column to draw to
grid[in/out] The grid to add additional columns to
Returns
The height of the grid
References AddController(), AddHub(), AddInvisible(), KODI::GAME::ControllerVertex::address, KODI::GAME::ControllerVertex::bConnected, KODI::GAME::ControllerVertex::bVisible, KODI::GAME::ControllerVertex::compatible, KODI::GAME::ControllerVertex::controller, DOWN, KODI::GAME::CPortNode::GetActiveController(), KODI::GAME::CPortNode::GetCompatibleControllers(), KODI::GAME::CControllerNode::GetController(), KODI::GAME::CControllerNode::GetControllerAddress(), GetDirection(), KODI::GAME::CControllerNode::GetHub(), KODI::GAME::CControllerHub::GetPorts(), KODI::GAME::CPortNode::GetPortType(), KODI::GAME::CPortNode::IsConnected(), node, KODI::GAME::ControllerVertex::portType, and RIGHT.
Referenced by AddController(), AddHub(), and AddPorts().
AddHub()
unsigned int CControllerGrid::AddHub (const PortVec & ports, unsigned int height, bool bSkipFirst, ControllerGrid & grid) static private
Draw a series of controllers to the grid at the specified height.
Parameters
ports The ports of the controllers to draw
height The height to start drawing the controllers at
bSkipFirst True if the first controller has already been drawn to a column, false to start drawing at the first controller
grid[in/out] The grid to add columns to
Returns
The height of the grid
References AddController(), and KODI::GAME::ControllerColumn::vertices.
Referenced by AddController().
AddInvisible()
void CControllerGrid::AddInvisible (std::vector< ControllerVertex > & column) static private
Draw an invisible vertex to the column.
Parameters
[in/out] column The column in a controller grid
References KODI::GAME::ControllerVertex::bVisible.
Referenced by AddController(), and SetHeight().
AddPorts()
unsigned int CControllerGrid::AddPorts (const PortVec & ports, ControllerGrid & grid) static private
Add ports to the grid.
Parameters
ports The ports on a console or controller
[out] grid The controller grid being created
Returns
The height of the grid determined by the maximum column height
References AddController(), KODI::GAME::CONTROLLER, KODI::GAME::CPortNode::GetPortType(), CLog::Log(), LOGERROR, and KODI::GAME::ControllerColumn::vertices.
Referenced by SetControllerTree().
GetControllers()
ControllerVector CControllerGrid::GetControllers (unsigned int playerIndex) const
Get the controllers in use by the specified player.
Parameters
playerIndex The column in the grid to get controllers from
References m_grid.
GetDirection()
CControllerGrid::GRID_DIRECTION CControllerGrid::GetDirection (const CControllerNode & node) static private
Get the direction of traversal for the next vertex.
Parameters
node The node in the controller tree being visited
Returns
The direction of the next vertex, or GRID_DIRECTION::UNKNOWN if unknown
References DOWN, node, and RIGHT.
Referenced by AddController().
GetGrid()
const ControllerGrid & KODI::GAME::CControllerGrid::GetGrid () const inline
Access the controller grid.
References m_grid.
GetHeight()
unsigned int KODI::GAME::CControllerGrid::GetHeight () const inline
Get the height (deepest controller) of the controller grid.
The height is cached when the controller grid is created to avoid iterating the grid
References m_height.
GetWidth()
unsigned int KODI::GAME::CControllerGrid::GetWidth () const inline
Get the width of the controller grid.
References m_grid.
SetControllerTree()
void CControllerGrid::SetControllerTree (const CControllerTree & controllerTree)
Create a grid from a controller tree.
References AddPorts(), KODI::GAME::CControllerHub::GetPorts(), m_grid, m_height, and SetHeight().
SetHeight()
void CControllerGrid::SetHeight (unsigned int height, ControllerGrid & grid) static private
Fill all columns with invisible vertices until the specified height.
Parameters
height The height to make all columns
[in/out] grid The grid to update
References AddInvisible().
Referenced by SetControllerTree().
Member Data Documentation
m_grid
ControllerGrid KODI::GAME::CControllerGrid::m_grid private
Referenced by GetControllers(), GetGrid(), GetWidth(), and SetControllerTree().
m_height
unsigned int KODI::GAME::CControllerGrid::m_height = 0 private
Referenced by GetHeight(), and SetControllerTree().
The documentation for this class was generated from the following files:
ControllerGrid.h
ControllerGrid.cpp