Kodi Documentation: KODI::CSignalRegistration Class Reference
KODI::CSignalRegistration Class Reference
#include <Signals.h>
Public Member Functions
CSignalRegistration () noexcept=default
CSignalRegistration (CSignalRegistration &&other) noexcept
CSignalRegistration & operator= (CSignalRegistration &&other) noexcept
~CSignalRegistration () noexcept
void Unregister ()
Private Member Functions
CSignalRegistration (std::shared_ptr< ISignalHandlerData > const &list, RegistrationIdentifierType registration)
CSignalRegistration (CSignalRegistration const &other)=delete
CSignalRegistration & operator= (CSignalRegistration const &other)=delete
Private Attributes
std::weak_ptr< ISignalHandlerData > m_list
RegistrationIdentifierType m_registration
Friends
template<typename ManagedT >
class CSignalHandlerList
Constructor & Destructor Documentation
CSignalRegistration() [1/4]
KODI::CSignalRegistration::CSignalRegistration (std::shared_ptr< ISignalHandlerData > const & list, RegistrationIdentifierType registration) inline private
CSignalRegistration() [2/4]
KODI::CSignalRegistration::CSignalRegistration (CSignalRegistration const & other) private delete
CSignalRegistration() [3/4]
KODI::CSignalRegistration::CSignalRegistration () default noexcept
CSignalRegistration() [4/4]
KODI::CSignalRegistration::CSignalRegistration (CSignalRegistration && other) inline noexcept
~CSignalRegistration()
KODI::CSignalRegistration::~CSignalRegistration () inline noexcept
References Unregister().
Member Function Documentation
operator=() [1/2]
CSignalRegistration & KODI::CSignalRegistration::operator= (CSignalRegistration && other) inline noexcept
References m_list, m_registration, and Unregister().
operator=() [2/2]
CSignalRegistration & KODI::CSignalRegistration::operator= (CSignalRegistration const & other) private delete
Unregister()
void KODI::CSignalRegistration::Unregister () inline
References m_list, and m_registration.
Referenced by operator=(), KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::Run(), and ~CSignalRegistration().
Friends And Related Symbol Documentation
CSignalHandlerList
template<typename ManagedT > friend class CSignalHandlerList friend
Member Data Documentation
m_list
std::weak_ptr<ISignalHandlerData> KODI::CSignalRegistration::m_list private
Referenced by operator=(), and Unregister().
m_registration
RegistrationIdentifierType KODI::CSignalRegistration::m_registration private
Referenced by operator=(), and Unregister().
The documentation for this class was generated from the following file:
Signals.h