Kodi Documentation: KODI::RETRO::CRenderBufferSysMem Class Reference
KODI::RETRO::CRenderBufferSysMem Class Reference
#include <RenderBufferSysMem.h>
Public Member Functions
CRenderBufferSysMem ()=default
~CRenderBufferSysMem () override=default
bool Allocate (AVPixelFormat format, unsigned int width, unsigned int height) override
size_t GetFrameSize () const override
uint8_t * GetMemory () override
Public Member Functions inherited from KODI::RETRO::CBaseRenderBuffer
CBaseRenderBuffer ()
~CBaseRenderBuffer () override=default
void Acquire () override
void Acquire (std::shared_ptr< IRenderBufferPool > pool) override
void Release () override
IRenderBufferPool * GetPool () override
DataAccess GetMemoryAccess () const override
DataAlignment GetMemoryAlignment () const override
Public Member Functions inherited from KODI::RETRO::IRenderBuffer
virtual ~IRenderBuffer ()=default
virtual void Update ()
virtual void ReleaseMemory ()
virtual bool UploadTexture ()=0
virtual void BindToUnit (unsigned int unit)
virtual void SetHeader (void *header)
AVPixelFormat GetFormat () const
unsigned int GetWidth () const
unsigned int GetHeight () const
bool IsLoaded () const
void SetLoaded (bool bLoaded)
bool IsRendered () const
void SetRendered (bool bRendered)
unsigned int GetRotation () const
void SetRotation (unsigned int rotationDegCCW)
Static Public Member Functions
static size_t GetBufferSize (AVPixelFormat format, unsigned int width, unsigned int height)
Protected Attributes
std::vector< uint8_t > m_data
Protected Attributes inherited from KODI::RETRO::CBaseRenderBuffer
std::atomic_int m_refCount
std::shared_ptr< IRenderBufferPool > m_pool
Protected Attributes inherited from KODI::RETRO::IRenderBuffer
AVPixelFormat m_format = AV_PIX_FMT_NONE
unsigned int m_width = 0
unsigned int m_height = 0
bool m_bLoaded = false
bool m_bRendered = false
unsigned int m_rotationDegCCW = 0
Constructor & Destructor Documentation
CRenderBufferSysMem()
KODI::RETRO::CRenderBufferSysMem::CRenderBufferSysMem () default
~CRenderBufferSysMem()
KODI::RETRO::CRenderBufferSysMem::~CRenderBufferSysMem () override default
Member Function Documentation
Allocate()
bool CRenderBufferSysMem::Allocate (AVPixelFormat format, unsigned int width, unsigned int height) override virtual
Implements KODI::RETRO::IRenderBuffer.
References GetBufferSize(), m_data, KODI::RETRO::IRenderBuffer::m_format, KODI::RETRO::IRenderBuffer::m_height, and KODI::RETRO::IRenderBuffer::m_width.
GetBufferSize()
size_t CRenderBufferSysMem::GetBufferSize (AVPixelFormat format, unsigned int width, unsigned int height) static
References KODI::RETRO::CRenderTranslator::TranslateWidthToBytes().
Referenced by Allocate().
GetFrameSize()
size_t CRenderBufferSysMem::GetFrameSize () const override virtual
Todo:
Remove me
Implements KODI::RETRO::IRenderBuffer.
References m_data.
Referenced by KODI::RETRO::CRenderBufferOpenGL::UploadTexture(), and KODI::RETRO::CRenderBufferOpenGLES::UploadTexture().
GetMemory()
uint8_t * CRenderBufferSysMem::GetMemory () override virtual
Implements KODI::RETRO::IRenderBuffer.
References m_data.
Member Data Documentation
m_data
std::vector<uint8_t> KODI::RETRO::CRenderBufferSysMem::m_data protected
Referenced by Allocate(), GetFrameSize(), GetMemory(), KODI::RETRO::CRenderBufferOpenGL::UploadTexture(), KODI::RETRO::CRenderBufferOpenGLES::UploadTexture(), and KODI::RETRO::CWinRenderBuffer::UploadTexture().
The documentation for this class was generated from the following files:
RenderBufferSysMem.h
RenderBufferSysMem.cpp