Kodi Documentation: CMediaSettings Class Reference
CMediaSettings Class Reference
#include <MediaSettings.h>
Public Member Functions
bool Load (const TiXmlNode *settings) override
Load settings from the given XML node.
bool Save (TiXmlNode *settings) const override
Save settings to the given XML node.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
const CVideoSettings & GetDefaultVideoSettings () const
CVideoSettings & GetDefaultVideoSettings ()
const CGameSettings & GetDefaultGameSettings () const
CGameSettings & GetDefaultGameSettings ()
const CGameSettings & GetCurrentGameSettings () const
CGameSettings & GetCurrentGameSettings ()
int GetWatchedMode (const std::string &content) const
Retrieve the watched mode for the given content type.
void SetWatchedMode (const std::string &content, WatchedMode mode)
Set the watched mode for the given content type.
void CycleWatchedMode (const std::string &content)
Cycle the watched mode for the given content type.
void SetMusicPlaylistRepeat (bool repeats)
void SetMusicPlaylistShuffled (bool shuffled)
void SetVideoPlaylistRepeat (bool repeats)
void SetVideoPlaylistShuffled (bool shuffled)
bool DoesMediaStartWindowed () const
void SetMediaStartWindowed (bool windowed)
int GetAdditionalSubtitleDirectoryChecked () const
void SetAdditionalSubtitleDirectoryChecked (int checked)
int GetMusicNeedsUpdate () const
void SetMusicNeedsUpdate (int version)
int GetVideoNeedsUpdate () const
void SetVideoNeedsUpdate (int version)
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual void OnSettingsLoaded ()
Settings have been loaded.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsUnloaded ()
Setting values have been unloaded.
virtual void OnSettingsCleared ()
Settings have been cleared.
Public Member Functions inherited from ISubSettings
virtual ~ISubSettings ()=default
virtual void Clear ()
Clear any loaded setting values.
Static Public Member Functions
static CMediaSettings & GetInstance ()
Protected Member Functions
CMediaSettings ()
CMediaSettings (const CMediaSettings &)=delete
CMediaSettings & operator= (CMediaSettings const &)=delete
~CMediaSettings () override
Static Protected Member Functions
static std::string GetWatchedContent (const std::string &content)
Private Types
typedef std::map< std::string, WatchedMode > WatchedModes
Private Attributes
CVideoSettings m_defaultVideoSettings
CGameSettings m_defaultGameSettings
CGameSettings m_currentGameSettings
WatchedModes m_watchedModes
bool m_musicPlaylistRepeat
bool m_musicPlaylistShuffle
bool m_videoPlaylistRepeat
bool m_videoPlaylistShuffle
bool m_mediaStartWindowed
int m_additionalSubtitleDirectoryChecked
int m_musicNeedsUpdate
if a database update means an update is required (set to the version number of the db)
int m_videoNeedsUpdate
if a database update means an update is required (set to the version number of the db)
CCriticalSection m_critical
Member Typedef Documentation
WatchedModes
typedef std::map<std::string, WatchedMode> CMediaSettings::WatchedModes private
Constructor & Destructor Documentation
CMediaSettings() [1/2]
CMediaSettings::CMediaSettings () protected
References m_additionalSubtitleDirectoryChecked, m_mediaStartWindowed, m_musicNeedsUpdate, m_musicPlaylistRepeat, m_musicPlaylistShuffle, m_videoNeedsUpdate, m_videoPlaylistRepeat, m_videoPlaylistShuffle, m_watchedModes, and WatchedModeAll.
CMediaSettings() [2/2]
CMediaSettings::CMediaSettings (const CMediaSettings &) protected delete
~CMediaSettings()
CMediaSettings::~CMediaSettings () override protected default
Member Function Documentation
CycleWatchedMode()
void CMediaSettings::CycleWatchedMode (const std::string & content)
Cycle the watched mode for the given content type.
Parameters
content Current content type
See also
GetWatchMode, SetWatchMode
References GetWatchedContent(), m_critical, m_watchedModes, WatchedModeAll, and WatchedModeWatched.
Referenced by PVR::CGUIWindowPVRRecordingsBase::OnMessage(), and CGUIWindowVideoNav::OnMessage().
DoesMediaStartWindowed()
bool CMediaSettings::DoesMediaStartWindowed () const inline
References m_mediaStartWindowed.
Referenced by CApplication::PlayFile().
GetAdditionalSubtitleDirectoryChecked()
int CMediaSettings::GetAdditionalSubtitleDirectoryChecked () const inline
References m_additionalSubtitleDirectoryChecked.
GetCurrentGameSettings() [1/2]
CGameSettings & CMediaSettings::GetCurrentGameSettings () inline
References m_currentGameSettings.
GetCurrentGameSettings() [2/2]
const CGameSettings & CMediaSettings::GetCurrentGameSettings () const inline
References m_currentGameSettings.
Referenced by KODI::GAME::CDialogGameStretchMode::GetFocusedItem(), KODI::GAME::CDialogGameVideoFilter::GetFocusedItem(), KODI::GAME::CDialogGameVideoRotation::GetFocusedItem(), KODI::RETRO::CRenderContext::GetGameSettings(), KODI::GUILIB::GUIINFO::CGamesGUIInfo::GetLabel(), KODI::GAME::CDialogGameStretchMode::OnItemFocus(), KODI::GAME::CDialogGameVideoFilter::OnItemFocus(), KODI::GAME::CDialogGameVideoRotation::OnItemFocus(), and KODI::GAME::CDialogGameVideoSelect::SaveSettings().
GetDefaultGameSettings() [1/2]
CGameSettings & CMediaSettings::GetDefaultGameSettings () inline
References m_defaultGameSettings.
GetDefaultGameSettings() [2/2]
const CGameSettings & CMediaSettings::GetDefaultGameSettings () const inline
References m_defaultGameSettings.
Referenced by KODI::RETRO::CRenderContext::GetDefaultGameSettings(), and KODI::GAME::CDialogGameVideoSelect::SaveSettings().
GetDefaultVideoSettings() [1/2]
CVideoSettings & CMediaSettings::GetDefaultVideoSettings () inline
References m_defaultVideoSettings.
GetDefaultVideoSettings() [2/2]
const CVideoSettings & CMediaSettings::GetDefaultVideoSettings () const inline
References m_defaultVideoSettings.
Referenced by CApplicationPlayerCallback::RequestVideoSettings(), CGUIDialogAudioSettings::Save(), CGUIDialogSubtitleSettings::Save(), and CGUIDialogVideoSettings::Save().
GetInstance()
CMediaSettings & CMediaSettings::GetInstance () static
Referenced by CGUIWindowVideoNav::ApplyWatchedFilter(), CGUIDialogSubtitleSettings::BrowseForSubtitle(), PVR::CPVRGUIActionsPlayback::CheckAndSwitchToFullscreen(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIWindowVideoNav::GetDirectory(), PVR::CGUIWindowPVRRecordingsBase::GetFilteredItems(), KODI::GAME::CDialogGameStretchMode::GetFocusedItem(), KODI::GAME::CDialogGameVideoFilter::GetFocusedItem(), KODI::GAME::CDialogGameVideoRotation::GetFocusedItem(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::GUILIB::GUIINFO::CGamesGUIInfo::GetLabel(), CSettings::InitializeISettingCallbacks(), CSettings::InitializeISettingsHandlers(), CSettings::InitializeISubSettings(), KODI::GAME::CDialogGameStretchMode::OnItemFocus(), KODI::GAME::CDialogGameVideoFilter::OnItemFocus(), KODI::GAME::CDialogGameVideoRotation::OnItemFocus(), CGUIWindowMusicPlayList::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), XBMCAddon::xbmc::Player::playCurrent(), PlayerControl(), CApplication::PlayFile(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), XBMCAddon::xbmc::Player::playPlaylist(), XBMCAddon::xbmc::Player::playStream(), CApplicationPlayerCallback::RequestVideoSettings(), CGUIDialogAudioSettings::Save(), CGUIDialogSubtitleSettings::Save(), CGUIDialogVideoSettings::Save(), KODI::GAME::CDialogGameVideoSelect::SaveSettings(), CUtil::ScanForExternalSubtitles(), CApplicationPlayerCallback::StoreVideoSettings(), CSettings::UninitializeISettingCallbacks(), CSettings::UninitializeISettingsHandlers(), CSettings::UninitializeISubSettings(), PVR::CGUIWindowPVRRecordingsBase::UpdateButtons(), and CGUIWindowVideoNav::UpdateButtons().
GetMusicNeedsUpdate()
int CMediaSettings::GetMusicNeedsUpdate () const inline
References m_musicNeedsUpdate.
GetVideoNeedsUpdate()
int CMediaSettings::GetVideoNeedsUpdate () const inline
References m_videoNeedsUpdate.
GetWatchedContent()
std::string CMediaSettings::GetWatchedContent (const std::string & content) static protected
Referenced by CycleWatchedMode(), GetWatchedMode(), and SetWatchedMode().
GetWatchedMode()
int CMediaSettings::GetWatchedMode (const std::string & content) const
Retrieve the watched mode for the given content type.
Parameters
content Current content type
Returns
the current watch mode for this content type, WATCH_MODE_ALL if the content type is unknown.
See also
SetWatchMode
References GetWatchedContent(), m_critical, m_watchedModes, and WatchedModeAll.
Referenced by CGUIWindowVideoNav::ApplyWatchedFilter(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIWindowVideoNav::GetDirectory(), PVR::CGUIWindowPVRRecordingsBase::GetFilteredItems(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), PVR::CGUIWindowPVRRecordingsBase::UpdateButtons(), and CGUIWindowVideoNav::UpdateButtons().
Load()
bool CMediaSettings::Load (const TiXmlNode * settings) override virtual
Load settings from the given XML node.
Parameters
settings XML node containing setting values
Returns
True if loading the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References XMLUtils::GetBoolean(), XMLUtils::GetFloat(), XMLUtils::GetInt(), CServiceBroker::GetPlaylistPlayer(), XMLUtils::GetString(), KODI::RETRO::CRetroPlayerUtils::IdentifierToStretchMode(), CVideoSettings::m_AudioDelay, CVideoSettings::m_Brightness, CVideoSettings::m_CenterMixLevel, CVideoSettings::m_Contrast, m_critical, CVideoSettings::m_CustomNonLinStretch, CVideoSettings::m_CustomPixelRatio, CVideoSettings::m_CustomVerticalShift, CVideoSettings::m_CustomZoomAmount, m_defaultGameSettings, m_defaultVideoSettings, CVideoSettings::m_Gamma, CVideoSettings::m_InterlaceMethod, m_musicNeedsUpdate, m_musicPlaylistRepeat, m_musicPlaylistShuffle, CVideoSettings::m_NoiseReduction, CVideoSettings::m_PostProcess, CVideoSettings::m_ScalingMethod, CVideoSettings::m_Sharpness, CVideoSettings::m_StereoMode, CVideoSettings::m_SubtitleDelay, CVideoSettings::m_SubtitleOn, CVideoSettings::m_ToneMapMethod, CVideoSettings::m_ToneMapParam, m_videoNeedsUpdate, m_videoPlaylistRepeat, m_videoPlaylistShuffle, CVideoSettings::m_ViewMode, CVideoSettings::m_VolumeAmplification, m_watchedModes, CGameSettings::Reset(), KODI::PLAYLIST::CPlayListPlayer::SetRepeat(), CGameSettings::SetRotationDegCCW(), KODI::PLAYLIST::CPlayListPlayer::SetShuffle(), CGameSettings::SetStretchMode(), CGameSettings::SetVideoFilter(), ViewModeNormal, ViewModeZoom110Width, VOLUME_DRC_MAXIMUM, VOLUME_DRC_MINIMUM, VS_INTERLACEMETHOD_MAX, VS_INTERLACEMETHOD_NONE, VS_SCALINGMETHOD_LINEAR, VS_SCALINGMETHOD_MAX, VS_SCALINGMETHOD_NEAREST, VS_TONEMAPMETHOD_HABLE, VS_TONEMAPMETHOD_MAX, VS_TONEMAPMETHOD_OFF, WatchedModeAll, and WatchedModeWatched.
OnSettingAction()
void CMediaSettings::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References CMusicLibraryQueue::CleanLibrary(), CDatabase::Close(), CBuiltins::Execute(), CMusicLibraryQueue::ExportLibrary(), g_localizeStrings, CLocalizeStrings::Get(), CBuiltins::GetInstance(), CMusicLibraryQueue::GetInstance(), CVideoLibraryQueue::GetInstance(), CMediaManager::GetLocalDrives(), CServiceBroker::GetMediaManager(), CMediaManager::GetNetworkLocations(), CMediaManager::GetRemovableDrives(), CServiceBroker::GetTextureCache(), CVideoDatabase::ImportFromXML(), CMusicLibraryQueue::ImportLibrary(), CVideoDatabase::Open(), CSettings::SETTING_MAINTENANCE_CLEANIMAGECACHE, CSettings::SETTING_MUSICLIBRARY_CLEANUP, CSettings::SETTING_MUSICLIBRARY_EXPORT, CSettings::SETTING_MUSICLIBRARY_IMPORT, CSettings::SETTING_VIDEOLIBRARY_CLEANUP, CSettings::SETTING_VIDEOLIBRARY_EXPORT, CSettings::SETTING_VIDEOLIBRARY_IMPORT, CGUIDialogLibExportSettings::Show(), CGUIDialogFileBrowser::ShowAndGetDirectory(), CGUIDialogFileBrowser::ShowAndGetFile(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and KODI::MESSAGING::HELPERS::ShowYesNoDialogText().
OnSettingChanged()
void CMediaSettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References CServiceBroker::GetAnnouncementManager(), CSettings::SETTING_VIDEOLIBRARY_SHOWUNWATCHEDPLOTS, and ANNOUNCEMENT::VideoLibrary.
operator=()
CMediaSettings & CMediaSettings::operator= (CMediaSettings const &) protected delete
Save()
bool CMediaSettings::Save (TiXmlNode * settings) const override virtual
Save settings to the given XML node.
Parameters
settings XML node in which the settings will be saved
Returns
True if saving the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References CVideoSettings::m_AudioDelay, CVideoSettings::m_Brightness, CVideoSettings::m_CenterMixLevel, CVideoSettings::m_Contrast, m_critical, CVideoSettings::m_CustomNonLinStretch, CVideoSettings::m_CustomPixelRatio, CVideoSettings::m_CustomVerticalShift, CVideoSettings::m_CustomZoomAmount, m_defaultGameSettings, m_defaultVideoSettings, CVideoSettings::m_Gamma, CVideoSettings::m_InterlaceMethod, m_musicNeedsUpdate, m_musicPlaylistRepeat, m_musicPlaylistShuffle, CVideoSettings::m_NoiseReduction, CVideoSettings::m_PostProcess, CVideoSettings::m_ScalingMethod, CVideoSettings::m_Sharpness, CVideoSettings::m_StereoMode, CVideoSettings::m_SubtitleDelay, CVideoSettings::m_SubtitleOn, CVideoSettings::m_ToneMapMethod, CVideoSettings::m_ToneMapParam, m_videoNeedsUpdate, m_videoPlaylistRepeat, m_videoPlaylistShuffle, CVideoSettings::m_ViewMode, CVideoSettings::m_VolumeAmplification, m_watchedModes, CGameSettings::RotationDegCCW(), XMLUtils::SetBoolean(), XMLUtils::SetFloat(), XMLUtils::SetInt(), XMLUtils::SetString(), CGameSettings::StretchMode(), KODI::RETRO::CRetroPlayerUtils::StretchModeToIdentifier(), and CGameSettings::VideoFilter().
SetAdditionalSubtitleDirectoryChecked()
void CMediaSettings::SetAdditionalSubtitleDirectoryChecked (int checked) inline
References m_additionalSubtitleDirectoryChecked.
Referenced by CUtil::ScanForExternalSubtitles().
SetMediaStartWindowed()
void CMediaSettings::SetMediaStartWindowed (bool windowed) inline
References m_mediaStartWindowed.
Referenced by PVR::CPVRGUIActionsPlayback::CheckAndSwitchToFullscreen(), XBMCAddon::xbmc::Player::playCurrent(), CApplication::PlayFile(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), XBMCAddon::xbmc::Player::playPlaylist(), and XBMCAddon::xbmc::Player::playStream().
SetMusicNeedsUpdate()
void CMediaSettings::SetMusicNeedsUpdate (int version) inline
References m_musicNeedsUpdate.
SetMusicPlaylistRepeat()
void CMediaSettings::SetMusicPlaylistRepeat (bool repeats) inline
References m_musicPlaylistRepeat.
Referenced by CGUIWindowMusicPlayList::OnMessage(), and PlayerControl().
SetMusicPlaylistShuffled()
void CMediaSettings::SetMusicPlaylistShuffled (bool shuffled) inline
References m_musicPlaylistShuffle.
Referenced by CGUIWindowMusicPlayList::OnMessage(), and PlayerControl().
SetVideoNeedsUpdate()
void CMediaSettings::SetVideoNeedsUpdate (int version) inline
References m_videoNeedsUpdate.
SetVideoPlaylistRepeat()
void CMediaSettings::SetVideoPlaylistRepeat (bool repeats) inline
References m_videoPlaylistRepeat.
Referenced by CGUIWindowVideoPlaylist::OnMessage(), and PlayerControl().
SetVideoPlaylistShuffled()
void CMediaSettings::SetVideoPlaylistShuffled (bool shuffled) inline
References m_videoPlaylistShuffle.
Referenced by CGUIWindowVideoPlaylist::OnMessage(), and PlayerControl().
SetWatchedMode()
void CMediaSettings::SetWatchedMode (const std::string & content, WatchedMode mode)
Set the watched mode for the given content type.
Parameters
content Current content type
value Watched mode to set
See also
GetWatchMode
References GetWatchedContent(), m_critical, and m_watchedModes.
Referenced by CGUIWindowVideoNav::OnMessage().
Member Data Documentation
m_additionalSubtitleDirectoryChecked
int CMediaSettings::m_additionalSubtitleDirectoryChecked private
Referenced by CMediaSettings(), GetAdditionalSubtitleDirectoryChecked(), and SetAdditionalSubtitleDirectoryChecked().
m_critical
CCriticalSection CMediaSettings::m_critical mutable private
Referenced by CycleWatchedMode(), GetWatchedMode(), Load(), Save(), and SetWatchedMode().
m_currentGameSettings
CGameSettings CMediaSettings::m_currentGameSettings private
Referenced by GetCurrentGameSettings(), and GetCurrentGameSettings().
m_defaultGameSettings
CGameSettings CMediaSettings::m_defaultGameSettings private
Referenced by GetDefaultGameSettings(), GetDefaultGameSettings(), Load(), and Save().
m_defaultVideoSettings
CVideoSettings CMediaSettings::m_defaultVideoSettings private
Referenced by GetDefaultVideoSettings(), GetDefaultVideoSettings(), Load(), and Save().
m_mediaStartWindowed
bool CMediaSettings::m_mediaStartWindowed private
Referenced by CMediaSettings(), DoesMediaStartWindowed(), and SetMediaStartWindowed().
m_musicNeedsUpdate
int CMediaSettings::m_musicNeedsUpdate private
if a database update means an update is required (set to the version number of the db)
Referenced by CMediaSettings(), GetMusicNeedsUpdate(), Load(), Save(), and SetMusicNeedsUpdate().
m_musicPlaylistRepeat
bool CMediaSettings::m_musicPlaylistRepeat private
Referenced by CMediaSettings(), Load(), Save(), and SetMusicPlaylistRepeat().
m_musicPlaylistShuffle
bool CMediaSettings::m_musicPlaylistShuffle private
Referenced by CMediaSettings(), Load(), Save(), and SetMusicPlaylistShuffled().
m_videoNeedsUpdate
int CMediaSettings::m_videoNeedsUpdate private
if a database update means an update is required (set to the version number of the db)
Referenced by CMediaSettings(), GetVideoNeedsUpdate(), Load(), Save(), and SetVideoNeedsUpdate().
m_videoPlaylistRepeat
bool CMediaSettings::m_videoPlaylistRepeat private
Referenced by CMediaSettings(), Load(), Save(), and SetVideoPlaylistRepeat().
m_videoPlaylistShuffle
bool CMediaSettings::m_videoPlaylistShuffle private
Referenced by CMediaSettings(), Load(), Save(), and SetVideoPlaylistShuffled().
m_watchedModes
WatchedModes CMediaSettings::m_watchedModes private
Referenced by CMediaSettings(), CycleWatchedMode(), GetWatchedMode(), Load(), Save(), and SetWatchedMode().
The documentation for this class was generated from the following files:
MediaSettings.h
MediaSettings.cpp