Kodi Documentation: CGPUInfo Class Reference
CGPUInfo Class Reference abstract
Class to concentrate all methods related to GPU information.
#include <GpuInfo.h>
Public Member Functions
CGPUInfo ()=default
virtual ~CGPUInfo ()=default
bool GetTemperature (CTemperature &temperature) const
Get the temperature of the GPU.
Static Public Member Functions
static std::unique_ptr< CGPUInfo > GetGPUInfo ()
Getter from the specific platform GPUInfo.
Protected Member Functions
virtual bool SupportsCustomTemperatureCommand () const
Checks if the specific platform implementation supports obtaining the GPU temperature via the execution of a custom command line command.
virtual bool SupportsPlatformTemperature () const
Checks if the specific platform implementation supports obtaining the GPU temperature from the platform SDK itself.
virtual bool GetGPUPlatformTemperature (CTemperature &temperature) const =0
Get the GPU temperature from the platform SDK.
virtual bool GetGPUTemperatureFromCommand (CTemperature &temperature, const std::string &cmd) const =0
Get the GPU temperature from a user provided command (advanced settings)
Detailed Description
Class to concentrate all methods related to GPU information.
This is used by the Info interface to obtain the current GPU temperature
Constructor & Destructor Documentation
CGPUInfo()
CGPUInfo::CGPUInfo () default
~CGPUInfo()
virtual CGPUInfo::~CGPUInfo () virtual default
Member Function Documentation
GetGPUInfo()
std::unique_ptr< CGPUInfo > CGPUInfo::GetGPUInfo () static
Getter from the specific platform GPUInfo.
Returns
the platform specific implementation of GPUInfo
GetGPUPlatformTemperature()
virtual bool CGPUInfo::GetGPUPlatformTemperature (CTemperature & temperature) const protected pure virtual
Get the GPU temperature from the platform SDK.
Note
platform implementations must override this. For this to take effect SupportsPlatformTemperature must be true.
Parameters
[in,out] temperature - the temperature to fill with the result
Returns
true if obtaining the GPU temperature succeeded, false otherwise
Implemented in CGPUInfoAndroid, CGPUInfoDarwinEmbed, CGPUInfoMacOS, CGPUInfoFreebsd, CGPUInfoLinux, CGPUInfoWin10, and CGPUInfoWin32.
Referenced by GetTemperature().
GetGPUTemperatureFromCommand()
virtual bool CGPUInfo::GetGPUTemperatureFromCommand (CTemperature & temperature, const std::string & cmd) const protected pure virtual
Get the GPU temperature from a user provided command (advanced settings)
Note
platform implementations must override this. For this to take effect SupportsCustomTemperatureCommand must be true.
Parameters
[in,out] temperature - the temperature to fill with the result
Returns
true if obtaining the GPU temperature succeeded, false otherwise
Implemented in CGPUInfoPosix, CGPUInfoWin10, and CGPUInfoWin32.
Referenced by GetTemperature().
GetTemperature()
bool CGPUInfo::GetTemperature (CTemperature & temperature) const
Get the temperature of the GPU.
Parameters
[in,out] temperature - the temperature to fill with the result
Returns
true if it was possible to obtain the GPU temperature, false otherwise
References GetGPUPlatformTemperature(), GetGPUTemperatureFromCommand(), CServiceBroker::GetSettingsComponent(), CTemperature::SetValid(), SupportsCustomTemperatureCommand(), and SupportsPlatformTemperature().
SupportsCustomTemperatureCommand()
virtual bool CGPUInfo::SupportsCustomTemperatureCommand () const inline protected virtual
Checks if the specific platform implementation supports obtaining the GPU temperature via the execution of a custom command line command.
Note
this is false on the base class but may be overridden by the specific platform implementation. Custom GPU command is defined in advancedsettings.
Returns
true if the implementation supports obtaining the GPU temperature from a custom command, false otherwise
Reimplemented in CGPUInfoPosix, CGPUInfoWin10, and CGPUInfoWin32.
Referenced by GetTemperature().
SupportsPlatformTemperature()
virtual bool CGPUInfo::SupportsPlatformTemperature () const inline protected virtual
Checks if the specific platform implementation supports obtaining the GPU temperature from the platform SDK itself.
Note
this is false on the base class but may be overridden by the specific platform implementation.
Returns
true if the implementation supports obtaining the GPU temperature from the platform SDK, false otherwise
Reimplemented in CGPUInfoAndroid, CGPUInfoDarwinEmbed, CGPUInfoMacOS, CGPUInfoFreebsd, CGPUInfoLinux, CGPUInfoWin10, and CGPUInfoWin32.
Referenced by GetTemperature().
The documentation for this class was generated from the following files:
GpuInfo.h
GPUInfoAndroid.cpp
GPUInfoDarwinEmbed.cpp
GPUInfoMacOS.cpp
GPUInfoFreebsd.cpp
GPUInfoLinux.cpp
GPUInfoWin10.cpp
GPUInfoWin32.cpp
GpuInfo.cpp