Kodi Documentation: class PVRStringSettingDefinition
class PVRStringSettingDefinition
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General
PVR add-on string setting definition
Representation of a string setting definition.
Classes
class kodi::addon::PVRStringSettingDefinition
Functions
kodi::addon::PVRStringSettingDefinition::PVRStringSettingDefinition (const std::vector< PVRTypeStringValue > &settingValues, const std::string &defaultValue, bool allowEmptyValue)
Class constructor with integrated values.
void kodi::addon::PVRStringSettingDefinition::SetValues (const std::vector< PVRTypeStringValue > &values, const std::string &defaultValue="")
optional
value definitions.
std::vector< PVRTypeStringValue > kodi::addon::PVRStringSettingDefinition::GetValues () const
To get with SetValues changed values.
void kodi::addon::PVRStringSettingDefinition::SetDefaultValue (const std::string &defaultValue)
optional
The default value for this setting.
std::string kodi::addon::PVRStringSettingDefinition::GetDefaultValue () const
To get with SetDefaultValue changed values.
void kodi::addon::PVRStringSettingDefinition::SetAllowEmptyValue (bool allowEmptyValue)
optional
The allow empty values flag for this setting.
bool kodi::addon::PVRStringSettingDefinition::GetAllowEmptyValue () const
To get with SetAllowEmptyValue changed values.
Detailed Description
PVR add-on string setting definition
Representation of a string setting definition.
Function Documentation
GetAllowEmptyValue()
bool kodi::addon::PVRStringSettingDefinition::GetAllowEmptyValue () const inline
To get with SetAllowEmptyValue changed values.
References PVR_STRING_SETTING_DEFINITION::bAllowEmptyValue, and kodi::addon::DynamicCStructHdl< PVRStringSettingDefinition, PVR_STRING_SETTING_DEFINITION >::m_cStructure.
GetDefaultValue()
std::string kodi::addon::PVRStringSettingDefinition::GetDefaultValue () const inline
To get with SetDefaultValue changed values.
References kodi::addon::DynamicCStructHdl< PVRStringSettingDefinition, PVR_STRING_SETTING_DEFINITION >::m_cStructure, and PVR_STRING_SETTING_DEFINITION::strDefaultValue.
GetValues()
std::vector< PVRTypeStringValue > kodi::addon::PVRStringSettingDefinition::GetValues () const inline
To get with SetValues changed values.
References PVR_STRING_SETTING_DEFINITION::iValuesSize, kodi::addon::DynamicCStructHdl< PVRStringSettingDefinition, PVR_STRING_SETTING_DEFINITION >::m_cStructure, PVR_ATTRIBUTE_STRING_VALUE::strDescription, PVR_ATTRIBUTE_STRING_VALUE::strValue, and PVR_STRING_SETTING_DEFINITION::values.
PVRStringSettingDefinition()
kodi::addon::PVRStringSettingDefinition::PVRStringSettingDefinition (const std::vector< PVRTypeStringValue > & settingValues, const std::string & defaultValue, bool allowEmptyValue) inline
Class constructor with integrated values.
Parameters
[in] settingValues possible setting values
[in] defaultValue default setting value
[in] allowEmptyValues allow empty values flag
References kodi::addon::PVRStringSettingDefinition::SetAllowEmptyValue(), kodi::addon::PVRStringSettingDefinition::SetDefaultValue(), and kodi::addon::PVRStringSettingDefinition::SetValues().
SetAllowEmptyValue()
void kodi::addon::PVRStringSettingDefinition::SetAllowEmptyValue (bool allowEmptyValue) inline
optional
The allow empty values flag for this setting.
References PVR_STRING_SETTING_DEFINITION::bAllowEmptyValue, and kodi::addon::DynamicCStructHdl< PVRStringSettingDefinition, PVR_STRING_SETTING_DEFINITION >::m_cStructure.
Referenced by kodi::addon::PVRStringSettingDefinition::PVRStringSettingDefinition().
SetDefaultValue()
void kodi::addon::PVRStringSettingDefinition::SetDefaultValue (const std::string & defaultValue) inline
optional
The default value for this setting.
References kodi::addon::DynamicCStructHdl< PVRStringSettingDefinition, PVR_STRING_SETTING_DEFINITION >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_STRING_SETTING_DEFINITION::strDefaultValue.
Referenced by kodi::addon::PVRSettingDefinition::GetStringDefinition(), and kodi::addon::PVRStringSettingDefinition::PVRStringSettingDefinition().
SetValues()
void kodi::addon::PVRStringSettingDefinition::SetValues (const std::vector< PVRTypeStringValue > & values, const std::string & defaultValue = "") inline
optional
value definitions.
Array containing the possible settings values. If left blank, any string value is accepted.
Parameters
[in] values List of possible values
[in] defaultValue [opt] The default value in list, can also be set by SetDefaultValue()
The following table contains values that can be set with class PVRTypeStringValue :
Name Type Set call Get call
Value std::string SetValue GetValue
Description std::string SetDescription GetDescription
Remarks
Further can there be used his class constructor to set values.
References PVR_STRING_SETTING_DEFINITION::iValuesSize, kodi::addon::DynamicCStructHdl< PVRStringSettingDefinition, PVR_STRING_SETTING_DEFINITION >::m_cStructure, kodi::addon::PVRTypeStringValue::ReallocAndCopyData(), kodi::addon::ReallocAndCopyString(), PVR_STRING_SETTING_DEFINITION::strDefaultValue, PVR_STRING_SETTING_DEFINITION::values, and values.
Referenced by kodi::addon::PVRSettingDefinition::GetStringDefinition(), and kodi::addon::PVRStringSettingDefinition::PVRStringSettingDefinition().