Kodi Documentation: KODI::RETRO::IGameCallback Class Reference
KODI::RETRO::IGameCallback Class Reference abstract
#include <IGameCallback.h>
Public Member Functions
virtual ~IGameCallback ()=default
virtual std::string GameClientID () const =0
Get the game client being used to play the game.
virtual std::string GetPlayingGame () const =0
Get the game that is being played.
virtual std::string CreateSavestate (bool autosave)=0
Creates a savestate.
virtual bool UpdateSavestate (const std::string &savestatePath)=0
Updates a savestate with the current game being played.
virtual bool LoadSavestate (const std::string &savestatePath)=0
Loads a savestate.
virtual void FreeSavestateResources (const std::string &savestatePath)=0
Frees resources allocated to the savestate, such as its video thumbnail.
virtual void CloseOSDCallback ()=0
Closes the OSD.
Constructor & Destructor Documentation
~IGameCallback()
virtual KODI::RETRO::IGameCallback::~IGameCallback () virtual default
Member Function Documentation
CloseOSDCallback()
virtual void KODI::RETRO::IGameCallback::CloseOSDCallback () pure virtual
Closes the OSD.
Implemented in KODI::RETRO::CRetroPlayer.
Referenced by KODI::RETRO::CGUIGameRenderManager::CloseOSD().
CreateSavestate()
virtual std::string KODI::RETRO::IGameCallback::CreateSavestate (bool autosave) pure virtual
Creates a savestate.
Parameters
autosave Whether the save type is auto
Returns
The path to the created savestate, or empty on error
Implemented in KODI::RETRO::CRetroPlayer.
Referenced by KODI::RETRO::CGUIGameRenderManager::CreateSavestate().
FreeSavestateResources()
virtual void KODI::RETRO::IGameCallback::FreeSavestateResources (const std::string & savestatePath) pure virtual
Frees resources allocated to the savestate, such as its video thumbnail.
Parameters
savestatePath The path to the savestate
Implemented in KODI::RETRO::CRetroPlayer.
Referenced by KODI::RETRO::CGUIGameRenderManager::FreeSavestateResources().
GameClientID()
virtual std::string KODI::RETRO::IGameCallback::GameClientID () const pure virtual
Get the game client being used to play the game.
Returns
The game client's ID, or empty if no game is being played
Implemented in KODI::RETRO::CRetroPlayer.
Referenced by KODI::RETRO::CGUIGameRenderManager::GameClientID().
GetPlayingGame()
virtual std::string KODI::RETRO::IGameCallback::GetPlayingGame () const pure virtual
Get the game that is being played.
Returns
The path to the game, or empty if no game is being played
Implemented in KODI::RETRO::CRetroPlayer.
Referenced by KODI::RETRO::CGUIGameRenderManager::GetPlayingGame().
LoadSavestate()
virtual bool KODI::RETRO::IGameCallback::LoadSavestate (const std::string & savestatePath) pure virtual
Loads a savestate.
Parameters
savestatePath The path to the savestate
Returns
True if the savestate was loaded, false on error
Implemented in KODI::RETRO::CRetroPlayer.
Referenced by KODI::RETRO::CGUIGameRenderManager::LoadSavestate().
UpdateSavestate()
virtual bool KODI::RETRO::IGameCallback::UpdateSavestate (const std::string & savestatePath) pure virtual
Updates a savestate with the current game being played.
Parameters
savestatePath The path to the savestate
Returns
True if the savestate was updated, false on error
Implemented in KODI::RETRO::CRetroPlayer.
Referenced by KODI::RETRO::CGUIGameRenderManager::UpdateSavestate().
The documentation for this class was generated from the following file:
IGameCallback.h