Kodi Documentation: KODI::VIDEO::CVideoInfoScanner Class Reference
KODI::VIDEO::CVideoInfoScanner Class Reference
#include <VideoInfoScanner.h>
Public Member Functions
CVideoInfoScanner ()
~CVideoInfoScanner () override
void Start (const std::string &strDirectory, bool scanAll=false)
Scan a folder using the background scanner.
void Stop ()
long AddVideo (CFileItem *pItem, const CONTENT_TYPE &content, bool videoFolder=false, bool useLocal=true, const CVideoInfoTag *showInfo=NULL, bool libraryImport=false)
Add an item to the database.
bool RetrieveVideoInfo (CFileItemList &items, bool bDirNames, CONTENT_TYPE content, bool useLocal=true, CScraperUrl *pURL=NULL, bool fetchEpisodes=true, CGUIDialogProgress *pDlgProgress=NULL)
Retrieve information for a list of items and add them to the database.
void GetArtwork (CFileItem *pItem, const CONTENT_TYPE &content, bool bApplyToDir=false, bool useLocal=true, const std::string &actorArtPath="")
Retrieve any artwork associated with an item.
bool EnumerateEpisodeItem (const CFileItem *item, EPISODELIST &episodeList)
Public Member Functions inherited from CInfoScanner
virtual ~CInfoScanner ()=default
Empty destructor.
bool HasNoMedia (const std::string &strDirectory) const
Check if the folder is excluded from scanning process.
void ShowDialog (bool show)
Set whether or not to show a progress dialog.
bool IsScanning () const
Returns whether or not a scan is in progress.
Static Public Member Functions
static void ApplyThumbToFolder (const std::string &folder, const std::string &imdbThumb)
static bool DownloadFailed (CGUIDialogProgress *pDlgProgress)
static void GetSeasonThumbs (const CVideoInfoTag &show, std::map< int, std::map< std::string, std::string > > &art, const std::vector< std::string > &artTypes, bool useLocal=true)
Get season thumbs for a tvshow. All seasons (regardless of whether the user has episodes) are added to the art map.
static std::string GetImage (const CScraperUrl::SUrlEntry &image, const std::string &itemPath)
static std::string GetMovieSetInfoFolder (const std::string &setTitle)
Protected Member Functions
virtual void Process ()
bool DoScan (const std::string &strDirectory) override
INFO_RET RetrieveInfoForTvShow (CFileItem *pItem, bool bDirNames, ADDON::ScraperPtr &scraper, bool useLocal, CScraperUrl *pURL, bool fetchEpisodes, CGUIDialogProgress *pDlgProgress)
INFO_RET RetrieveInfoForMovie (CFileItem *pItem, bool bDirNames, ADDON::ScraperPtr &scraper, bool useLocal, CScraperUrl *pURL, CGUIDialogProgress *pDlgProgress)
INFO_RET RetrieveInfoForMusicVideo (CFileItem *pItem, bool bDirNames, ADDON::ScraperPtr &scraper, bool useLocal, CScraperUrl *pURL, CGUIDialogProgress *pDlgProgress)
INFO_RET RetrieveInfoForEpisodes (CFileItem *item, long showID, const ADDON::ScraperPtr &scraper, bool useLocal, CGUIDialogProgress *progress=NULL)
bool ProgressCancelled (CGUIDialogProgress *progress, int heading, const std::string &line1)
Update the progress bar with the heading and line and check for cancellation.
int FindVideo (const std::string &title, int year, const ADDON::ScraperPtr &scraper, CScraperUrl &url, CGUIDialogProgress *progress)
Find a url for the given video using the given scraper.
int FindVideoUsingTag (CFileItem &item, const ADDON::ScraperPtr &scraper, CScraperUrl &url, CGUIDialogProgress *progress)
Find a url for the given video using the given scraper.
bool GetDetails (CFileItem *pItem, const std::unordered_map< std::string, std::string > &uniqueIDs, CScraperUrl &url, const ADDON::ScraperPtr &scraper, VIDEO::IVideoInfoTagLoader *nfoFile=nullptr, CGUIDialogProgress *pDialog=nullptr)
Retrieve detailed information for an item from an online source, optionally supplemented with local data.
bool GetEpisodeAndSeasonFromRegExp (CRegExp &reg, EPISODE &episodeInfo, int defaultSeason)
Extract episode and season numbers from a processed regexp.
bool GetAirDateFromRegExp (CRegExp &reg, EPISODE &episodeInfo)
Extract episode air-date from a processed regexp.
bool GetEpisodeTitleFromRegExp (CRegExp &reg, EPISODE &episodeInfo)
Extract episode title from a processed regexp.
void FetchActorThumbs (std::vector< SActorInfo > &actors, const std::string &strPath)
Fetch thumbs for actors Updates each actor with their thumb (local or online)
std::string GetFastHash (const std::string &directory, const std::vector< std::string > &excludes) const
Retrieve a "fast" hash of the given directory (if available) Performs a stat() on the directory, and uses modified time to create a "fast" hash of the folder. If no modified time is available, the create time is used, and if neither are available, an empty hash is returned. In case exclude from scan expressions are present, the string array will be appended to the md5 hash to ensure we're doing a re-scan whenever the user modifies those.
std::string GetRecursiveFastHash (const std::string &directory, const std::vector< std::string > &excludes) const
Retrieve a "fast" hash of the given directory recursively (if available) Performs a stat() on the directory, and uses modified time to create a "fast" hash of each folder. If no modified time is available, the create time is used, and if neither are available, an empty hash is returned. In case exclude from scan expressions are present, the string array will be appended to the md5 hash to ensure we're doing a re-scan whenever the user modifies those.
bool CanFastHash (const CFileItemList &items, const std::vector< std::string > &excludes) const
Decide whether a folder listing could use the "fast" hash Fast hashing can be done whenever the folder contains no scannable subfolders, as the fast hash technique uses modified time to determine when folder content changes, which is generally not propagated up the directory tree.
INFO_RET OnProcessSeriesFolder (EPISODELIST &files, const ADDON::ScraperPtr &scraper, bool useLocal, const CVideoInfoTag &showInfo, CGUIDialogProgress *pDlgProgress=NULL)
Process a series folder, filling in episode details and adding them to the database.
bool EnumerateSeriesFolder (CFileItem *item, EPISODELIST &episodeList)
bool ProcessItemByVideoInfoTag (const CFileItem *item, EPISODELIST &episodeList)
bool AddVideoExtras (CFileItemList &items, const CONTENT_TYPE &content, const std::string &path)
bool ProcessVideoVersion (VideoDbContentType itemType, int dbId)
Protected Member Functions inherited from CInfoScanner
CInfoScanner ()=default
Protected constructor to only allow subclass instances.
Static Protected Member Functions
static int GetPathHash (const CFileItemList &items, std::string &hash)
Protected Attributes
bool m_bStop
bool m_scanAll
bool m_ignoreVideoVersions {false}
bool m_ignoreVideoExtras {false}
std::string m_strStartDir
CVideoDatabase m_database
std::set< std::string > m_pathsToCount
std::set< int > m_pathsToClean
Protected Attributes inherited from CInfoScanner
std::set< std::string > m_pathsToScan
Set of paths to scan.
bool m_showDialog = false
Whether or not to show progress bar dialog.
CGUIDialogProgressBarHandle * m_handle = nullptr
Progress bar handle.
bool m_bRunning = false
Whether or not scanner is running.
bool m_bCanInterrupt = false
Whether or not scanner is currently interruptible.
bool m_bClean = false
Whether or not to perform cleaning during scanning.
Static Private Member Functions
static void AddLocalItemArtwork (CGUIListItem::ArtMap &itemArt, const std::vector< std::string > &wantedArtTypes, const std::string &itemPath, bool addAll, bool exactName)
static std::string GetArtTypeFromSize (unsigned int width, unsigned int height)
Retrieve the art type for an image from the given size.
Additional Inherited Members
Public Types inherited from CInfoScanner
enum INFO_RET {
INFO_CANCELLED , INFO_ERROR , INFO_NOT_NEEDED , INFO_HAVE_ALREADY ,
INFO_NOT_FOUND , INFO_ADDED
}
Return values from the information lookup functions.
enum INFO_TYPE {
NO_NFO = 0 , FULL_NFO = 1 , URL_NFO = 2 , OVERRIDE_NFO = 3 ,
COMBINED_NFO = 4 , ERROR_NFO = 5 , TITLE_NFO = 6
}
Constructor & Destructor Documentation
CVideoInfoScanner()
KODI::VIDEO::CVideoInfoScanner::CVideoInfoScanner ()
References CServiceBroker::GetSettingsComponent(), m_bStop, m_ignoreVideoExtras, m_ignoreVideoVersions, m_scanAll, CSettings::SETTING_VIDEOLIBRARY_IGNOREVIDEOEXTRAS, and CSettings::SETTING_VIDEOLIBRARY_IGNOREVIDEOVERSIONS.
~CVideoInfoScanner()
KODI::VIDEO::CVideoInfoScanner::~CVideoInfoScanner () override default
Member Function Documentation
AddLocalItemArtwork()
void KODI::VIDEO::CVideoInfoScanner::AddLocalItemArtwork (CGUIListItem::ArtMap & itemArt, const std::vector< std::string > & wantedArtTypes, const std::string & itemPath, bool addAll, bool exactName) static private
References XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, XFILE::DIR_FLAG_READ_CACHE, XFILE::CDirectory::GetDirectory(), URIUtils::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), URIUtils::GetFileName(), CServiceBroker::GetTextureCache(), CTextureDetails::height, CVideoThumbLoader::IsArtTypeInWhitelist(), CVideoThumbLoader::IsValidArtType(), URIUtils::RemoveExtension(), and CTextureDetails::width.
AddVideo()
long KODI::VIDEO::CVideoInfoScanner::AddVideo (CFileItem * pItem, const CONTENT_TYPE & content, bool videoFolder = false, bool useLocal = true, const CVideoInfoTag * showInfo = NULL, bool libraryImport = false)
Add an item to the database.
Parameters
pItem item to add to the database.
content content type of the item.
videoFolder whether the video is represented by a folder (single movie per folder). Defaults to false.
useLocal whether to use local information for artwork etc.
showInfo pointer to CVideoInfoTag details for the show if this is an episode. Defaults to NULL.
libraryImport Whether this call belongs to a full library import or not. Defaults to false.
Returns
database id of the added item, or -1 on failure.
References ADDON::content, CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_TVSHOWS, data(), CBookmark::episodeNumber, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAnnouncementManager(), CGUIListItem::GetArt(), CVideoThumbLoader::GetArtTypes(), CFileItem::GetBaseMoviePath(), CUtil::GetDiscNumberFromPath(), CDVDFileInfo::GetFileStreamDetails(), URIUtils::GetParentPath(), CFileItem::GetPath(), XFILE::CMultiPathDirectory::GetPaths(), CVideoInfoTag::GetPlayCount(), CVideoInfoTag::GetResumePoint(), CServiceBroker::GetSettingsComponent(), CFileItem::GetVideoInfoTag(), URIUtils::IsMultiPath(), CVideoInfoTag::IsPlayCountSet(), CFileItem::IsPlugin(), CBookmark::IsSet(), CDateTime::IsValid(), CLog::Log(), LOGDEBUG, CVideoInfoTag::m_basePath, CGUIListItem::m_bIsFolder, CVideoInfoTag::m_EpBookmark, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_parentPathID, CVideoInfoTag::m_set, CVideoInfoTag::m_showLink, CVideoInfoTag::m_streamDetails, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPath, CVideoInfoTag::m_strShowTitle, CVideoInfoTag::m_strTitle, CVideoInfoTag::m_strTrailer, CVideoInfoTag::m_type, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSeason, MediaTypeTvShow, MediaTypeVideoCollection, CBookmark::RESUME, CBookmark::seasonNumber, CVideoInfoTag::SetSet(), CSettings::SETTING_MYVIDEOS_EXTRACTFLAGS, CFileItemList::Size(), CBookmark::timeInSeconds, CVideoInfoTag::SetInfo::title, ADDON::TranslateContent(), and ANNOUNCEMENT::VideoLibrary.
Referenced by CVideoDatabase::ImportFromXML(), RetrieveInfoForMovie(), RetrieveInfoForMusicVideo(), and RetrieveInfoForTvShow().
AddVideoExtras()
bool KODI::VIDEO::CVideoInfoScanner::AddVideoExtras (CFileItemList & items, const CONTENT_TYPE & content, const std::string & path) protected
References AUTO, ADDON::content, CONTENT_MOVIES, KODI::VIDEO::ContentToVideoDbType(), XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::EnumerateDirectory(), EXTRA, CGUIDialogVideoManagerExtras::GenerateVideoExtra(), CServiceBroker::GetFileExtensionProvider(), CDVDFileInfo::GetFileStreamDetails(), CServiceBroker::GetSettingsComponent(), CFileExtensionProvider::GetVideoExtensions(), CLog::Log(), LOGDEBUG, LOGERROR, and CSettings::SETTING_MYVIDEOS_EXTRACTFLAGS.
Referenced by DoScan().
ApplyThumbToFolder()
void KODI::VIDEO::CVideoInfoScanner::ApplyThumbToFolder (const std::string & folder, const std::string & imdbThumb) static
References CThumbLoader::SetCachedImage().
Referenced by CGUIDialogVideoInfo::ManageVideoItemArtwork().
CanFastHash()
bool KODI::VIDEO::CVideoInfoScanner::CanFastHash (const CFileItemList & items, const std::vector< std::string > & excludes) const protected
Decide whether a folder listing could use the "fast" hash Fast hashing can be done whenever the folder contains no scannable subfolders, as the fast hash technique uses modified time to determine when folder content changes, which is generally not propagated up the directory tree.
Parameters
items the directory listing
excludes string array of exclude expressions
Returns
true if this directory listing can be fast hashed, false otherwise
References CUtil::ExcludeFileOrFolder(), CServiceBroker::GetSettingsComponent(), CFileItem::IsPlugin(), and CFileItemList::Size().
Referenced by DoScan().
DoScan()
bool KODI::VIDEO::CVideoInfoScanner::DoScan (const std::string & strDirectory) override protected virtual
Implements CInfoScanner.
References CFileItemList::Add(), AddVideoExtras(), CFileItemList::begin(), CanFastHash(), CFileItemList::Clear(), ADDON::content, CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_NONE, CONTENT_TVSHOWS, XFILE::DIR_FLAG_DEFAULTS, DoScan(), CFileItemList::end(), CFileItemList::erase(), CUtil::ExcludeFileOrFolder(), g_localizeStrings, CLocalizeStrings::Get(), XFILE::CDirectory::GetDirectory(), GetFastHash(), CServiceBroker::GetFileExtensionProvider(), URIUtils::GetFileName(), URIUtils::GetParentPath(), GetPathHash(), CVideoDatabase::GetPathHash(), CVideoDatabase::GetPathId(), CVideoDatabase::GetScraperForPath(), CServiceBroker::GetSettingsComponent(), CInfoScanner::HasNoMedia(), XFILE::CPluginDirectory::IsMediaLibraryScanningAllowed(), KODI::PLAYLIST::IsPlayList(), URIUtils::IsPlugin(), KODI::VIDEO::IsVideoExtrasFolder(), CLog::Log(), LOGDEBUG, LOGINFO, CInfoScanner::m_bClean, m_bStop, m_database, CInfoScanner::m_handle, m_ignoreVideoExtras, m_pathsToClean, CInfoScanner::m_pathsToScan, m_scanAll, KODI::VIDEO::SScanSettings::noupdate, KODI::VIDEO::OnDirectoryScanned(), KODI::VIDEO::SScanSettings::parent_name_root, KODI::VIDEO::SScanSettings::recurse, RetrieveVideoInfo(), CFileItem::SetPath(), CVideoDatabase::SetPathHash(), CGUIDialogProgressBarHandle::SetText(), CGUIDialogProgressBarHandle::SetTitle(), CFileItemList::Size(), CFileItemList::Stack(), and ADDON::TranslateContent().
Referenced by DoScan(), and Process().
DownloadFailed()
bool KODI::VIDEO::CVideoInfoScanner::DownloadFailed (CGUIDialogProgress * pDlgProgress) static
References CServiceBroker::GetSettingsComponent(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and KODI::MESSAGING::HELPERS::ShowYesNoDialogText().
Referenced by CVideoLibraryRefreshingJob::Work().
EnumerateEpisodeItem()
bool KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem (const CFileItem * item, EPISODELIST & episodeList)
References CRegExp::autoUtf8, KODI::VIDEO::EPISODE::cDate, CDateTime::GetAsLocalizedDate(), CFileItem::GetBaseMoviePath(), URIUtils::GetFileName(), CRegExp::GetFindLen(), CFileItem::GetLocalMetadataPath(), CRegExp::GetMatch(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), KODI::VIDEO::EPISODE::iEpisode, KODI::VIDEO::EPISODE::iSeason, KODI::VIDEO::EPISODE::isFolder, CFileItem::IsOpticalMediaFile(), CLog::Log(), LOGDEBUG, CRegExp::RegComp(), CRegExp::RegFind(), URIUtils::RemoveSlashAtEnd(), CDateTime::SetValid(), KODI::VIDEO::EPISODE::strPath, and KODI::VIDEO::EPISODE::strTitle.
Referenced by TEST(), and TEST_P().
EnumerateSeriesFolder()
bool KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder (CFileItem * item, EPISODELIST & episodeList) protected
References CFileItemList::Add(), CVariant::asString(), CFileItemList::begin(), XFILE::DIR_FLAG_DEFAULTS, XFILE::DIR_FLAG_NO_FILE_INFO, CFileItemList::end(), XFILE::CDirectory::EnumerateDirectory(), CFileItemList::erase(), URIUtils::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), URIUtils::GetParentPath(), CFileItem::GetPath(), GetPathHash(), CVideoDatabase::GetPathHash(), CVideoDatabase::GetPathId(), CVideoDatabase::GetPathsForTvShow(), CGUIListItem::GetProperty(), GetRecursiveFastHash(), CServiceBroker::GetSettingsComponent(), CVideoDatabase::GetTvShowId(), CFileExtensionProvider::GetVideoExtensions(), CInfoScanner::HasNoMedia(), CGUIListItem::HasProperty(), CFileItem::IsPlugin(), CLog::Log(), LOGDEBUG, CInfoScanner::m_bClean, CGUIListItem::m_bIsFolder, m_database, CInfoScanner::m_handle, m_pathsToClean, CInfoScanner::m_pathsToScan, KODI::VIDEO::OnDirectoryScanned(), CGUIListItem::SetProperty(), CFileItemList::Sort(), SortByPath, and SortOrderAscending.
Referenced by RetrieveInfoForEpisodes().
FetchActorThumbs()
void KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs (std::vector< SActorInfo > & actors, const std::string & strPath) protected
Fetch thumbs for actors Updates each actor with their thumb (local or online)
Parameters
actors - vector of SActorInfo
strPath - path on filesystem to look for local thumbs
References URIUtils::AddFileToFolder(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, XFILE::CDirectory::Exists(), XFILE::CDirectory::GetDirectory(), URIUtils::GetFileName(), CFileItem::GetPath(), CServiceBroker::GetTextureCache(), CScraperUrl::GetThumbUrl(), URIUtils::IsPlugin(), URIUtils::RemoveExtension(), and CFileItemList::Size().
FindVideo()
int KODI::VIDEO::CVideoInfoScanner::FindVideo (const std::string & title, int year, const ADDON::ScraperPtr & scraper, CScraperUrl & url, CGUIDialogProgress * progress) protected
Find a url for the given video using the given scraper.
Parameters
title title of the video to lookup
year year of the video to lookup
scraper scraper to use for the lookup
url [out] returned url from the scraper
progress CGUIDialogProgress bar
Returns
>0 on success, <0 on failure (cancellation), and 0 on no info found
References CVideoInfoDownloader::FindMovie().
Referenced by RetrieveInfoForMovie(), RetrieveInfoForMusicVideo(), and RetrieveInfoForTvShow().
FindVideoUsingTag()
int KODI::VIDEO::CVideoInfoScanner::FindVideoUsingTag (CFileItem & item, const ADDON::ScraperPtr & scraper, CScraperUrl & url, CGUIDialogProgress * progress) protected
Find a url for the given video using the given scraper.
Parameters
item the video to lookup
scraper scraper to use for the lookup
url [out] returned url from the scraper
progress CGUIDialogProgress bar
Returns
>0 on success, <0 on failure (cancellation), and 0 on no info found
GetAirDateFromRegExp()
bool KODI::VIDEO::CVideoInfoScanner::GetAirDateFromRegExp (CRegExp & reg, EPISODE & episodeInfo) protected
Extract episode air-date from a processed regexp.
Parameters
reg Regular expression object with at least 3 matches
episodeInfo Episode information to fill in.
Returns
true on success (3 matches), false on failure (fewer than 3 matches)
References KODI::VIDEO::EPISODE::cDate, CRegExp::GetMatch(), CDateTime::IsValid(), and CDateTime::SetDate().
GetArtTypeFromSize()
std::string KODI::VIDEO::CVideoInfoScanner::GetArtTypeFromSize (unsigned int width, unsigned int height) static private
Retrieve the art type for an image from the given size.
Parameters
width the width of the image.
height the height of the image.
Returns
"poster" if the aspect ratio is at most 4:5, "banner" if the aspect ratio is at least 1:4, "thumb" otherwise.
GetArtwork()
void KODI::VIDEO::CVideoInfoScanner::GetArtwork (CFileItem * pItem, const CONTENT_TYPE & content, bool bApplyToDir = false, bool useLocal = true, const std::string & actorArtPath = "")
Retrieve any artwork associated with an item.
Parameters
pItem item to find artwork for.
content content type of the item.
bApplyToDir whether we should apply any thumbs to a folder. Defaults to false.
useLocal whether we should use local thumbs. Defaults to true.
actorArtPath the path to search for actor thumbs. Defaults to empty.
References CDVDFileInfo::CanExtract(), ADDON::content, CONTENT_MOVIES, CONTENT_MUSICVIDEOS, KODI::VIDEO::ContentToMediaType(), CScraperUrl::General, CGUIListItem::GetArt(), CVideoThumbLoader::GetArtTypes(), URIUtils::GetBasePath(), URIUtils::GetDirectory(), CVideoThumbLoader::GetEmbeddedThumbURL(), CFanart::GetImageURL(), KODI::ART::GetLocalArtBaseFilename(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetTextureCache(), CScraperUrl::GetUrls(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CVideoThumbLoader::IsArtTypeInWhitelist(), CGUIListItem::m_bIsFolder, CVideoInfoTag::m_cast, CVideoInfoTag::m_coverArt, CVideoInfoTag::m_fanart, CVideoInfoTag::m_set, CVideoInfoTag::m_strPictureURL, MediaTypeEpisode, MediaTypeVideoCollection, CScraperUrl::Parse(), CGUIListItem::SetArt(), CSettings::SETTING_MYVIDEOS_EXTRACTTHUMB, CSettings::SETTING_VIDEOLIBRARY_ACTORTHUMBS, CSettings::SETTING_VIDEOLIBRARY_ARTWORK_LEVEL, CFileItem::SkipLocalArt(), CVideoInfoTag::SetInfo::title, CFanart::Unpack(), IMAGE_FILES::URLFromFile(), CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_ALL, CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_BASIC, and CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_NONE.
Referenced by CVideoDatabase::ImportFromXML().
GetDetails()
bool KODI::VIDEO::CVideoInfoScanner::GetDetails (CFileItem * pItem, const std::unordered_map< std::string, std::string > & uniqueIDs, CScraperUrl & url, const ADDON::ScraperPtr & scraper, VIDEO::IVideoInfoTagLoader * nfoFile = nullptr, CGUIDialogProgress * pDialog = nullptr) protected
Retrieve detailed information for an item from an online source, optionally supplemented with local data.
Todo:
sort out some better return codes.
Parameters
pItem item to retrieve online details for.
uniqueIDs Unique IDs for additional information for scrapers.
url URL to use to retrieve online details.
scraper Scraper that handles parsing the online data.
nfoFile if set, we override the online data with the locally supplied data. Defaults to NULL.
pDialog progress dialog to update and check for cancellation during processing. Defaults to NULL.
Returns
true if information is found, false if an error occurred, the lookup was cancelled, or no information was found.
References CVideoInfoDownloader::GetDetails(), CScraperUrl::GetTitle(), CFileItem::GetVideoInfoTag(), CGUIDialogBoxBase::HasText(), KODI::VIDEO::IVideoInfoTagLoader::Load(), CVideoInfoTag::m_strTitle, CGUIDialogProgress::Progress(), and CGUIDialogBoxBase::SetLine().
Referenced by RetrieveInfoForMovie(), RetrieveInfoForMusicVideo(), and RetrieveInfoForTvShow().
GetEpisodeAndSeasonFromRegExp()
bool KODI::VIDEO::CVideoInfoScanner::GetEpisodeAndSeasonFromRegExp (CRegExp & reg, EPISODE & episodeInfo, int defaultSeason) protected
Extract episode and season numbers from a processed regexp.
Parameters
reg Regular expression object with at least 2 matches
episodeInfo Episode information to fill in.
defaultSeason Season to use if not found in reg.
Returns
true on success (2 matches), false on failure (fewer than 2 matches)
References CRegExp::GetMatch(), KODI::VIDEO::EPISODE::iEpisode, KODI::VIDEO::EPISODE::iSeason, KODI::VIDEO::EPISODE::iSubepisode, and CUtil::TranslateRomanNumeral().
GetEpisodeTitleFromRegExp()
bool KODI::VIDEO::CVideoInfoScanner::GetEpisodeTitleFromRegExp (CRegExp & reg, EPISODE & episodeInfo) protected
Extract episode title from a processed regexp.
Parameters
reg Regular expression object with at least 1 match
episodeInfo Episode information to fill in.
Returns
true on success (1 match), false on failure (no matches)
References CRegExp::GetMatch(), and KODI::VIDEO::EPISODE::strTitle.
GetFastHash()
std::string KODI::VIDEO::CVideoInfoScanner::GetFastHash (const std::string & directory, const std::vector< std::string > & excludes) const protected
Retrieve a "fast" hash of the given directory (if available) Performs a stat() on the directory, and uses modified time to create a "fast" hash of the folder. If no modified time is available, the create time is used, and if neither are available, an empty hash is returned. In case exclude from scan expressions are present, the string array will be appended to the md5 hash to ensure we're doing a re-scan whenever the user modifies those.
Parameters
directory folder to hash
excludes string array of exclude expressions
Returns
the md5 hash of the folder"
References __stat64, int64_t(), XFILE::CFile::Stat(), and KODI::UTILITY::CDigest::Update().
Referenced by DoScan().
GetImage()
std::string KODI::VIDEO::CVideoInfoScanner::GetImage (const CScraperUrl::SUrlEntry & image, const std::string & itemPath) static
References URIUtils::AddFileToFolder(), URIUtils::GetDirectory(), and CScraperUrl::GetThumbUrl().
GetMovieSetInfoFolder()
std::string KODI::VIDEO::CVideoInfoScanner::GetMovieSetInfoFolder (const std::string & setTitle) static
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), XFILE::CDirectory::Exists(), CServiceBroker::GetSettingsComponent(), LEGAL_WIN32_COMPAT, CLog::Log(), LOGDEBUG, CUtil::MakeLegalFileName(), and CSettings::SETTING_VIDEOLIBRARY_MOVIESETSFOLDER.
Referenced by KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::AddItemPathToFileBrowserSources(), and KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::GetLocalArt().
GetPathHash()
int KODI::VIDEO::CVideoInfoScanner::GetPathHash (const CFileItemList & items, std::string & hash) static protected
References KODI::PLAYLIST::IsPlayList(), KODI::VIDEO::IsVideo(), and CFileItemList::Size().
Referenced by DoScan(), and EnumerateSeriesFolder().
GetRecursiveFastHash()
std::string KODI::VIDEO::CVideoInfoScanner::GetRecursiveFastHash (const std::string & directory, const std::vector< std::string > & excludes) const protected
Retrieve a "fast" hash of the given directory recursively (if available) Performs a stat() on the directory, and uses modified time to create a "fast" hash of each folder. If no modified time is available, the create time is used, and if neither are available, an empty hash is returned. In case exclude from scan expressions are present, the string array will be appended to the md5 hash to ensure we're doing a re-scan whenever the user modifies those.
Parameters
directory folder to hash (recursively)
excludes string array of exclude expressions
Returns
the md5 hash of the folder
Todo:
some filesystems may return the mtime/ctime inline, in which case this is unnecessarily expensive. Consider supporting Stat() in our directory cache?
References __stat64, CFileItemList::Add(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, CUtil::GetRecursiveDirsListing(), int64_t(), CFileItemList::Size(), XFILE::CFile::Stat(), and KODI::UTILITY::CDigest::Update().
Referenced by EnumerateSeriesFolder().
GetSeasonThumbs()
void KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs (const CVideoInfoTag & show, std::map< int, std::map< std::string, std::string > > & art, const std::vector< std::string > & artTypes, bool useLocal = true) static
Get season thumbs for a tvshow. All seasons (regardless of whether the user has episodes) are added to the art map.
Parameters
show tvshow info tag
art artwork map to which season thumbs are added.
useLocal whether to use local thumbs, defaults to true
References URIUtils::AddFileToFolder(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, XFILE::DIR_FLAG_READ_CACHE, XFILE::CDirectory::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), URIUtils::GetFileName(), CRegExp::GetMatch(), CFileExtensionProvider::GetPictureExtensions(), CServiceBroker::GetSettingsComponent(), CScraperUrl::GetThumbUrl(), CScraperUrl::GetUrls(), CVideoThumbLoader::IsArtTypeInWhitelist(), CVideoInfoTag::m_strPath, CVideoInfoTag::m_strPictureURL, name, CRegExp::RegComp(), CRegExp::RegFind(), CScraperUrl::Season, CSettings::SETTING_VIDEOLIBRARY_ARTWORK_LEVEL, CFileItemList::Size(), CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_ALL, and CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_BASIC.
Referenced by CVideoDatabase::ImportFromXML(), and RetrieveInfoForEpisodes().
OnProcessSeriesFolder()
CInfoScanner::INFO_RET KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder (EPISODELIST & files, const ADDON::ScraperPtr & scraper, bool useLocal, const CVideoInfoTag & showInfo, CGUIDialogProgress * pDlgProgress = NULL) protected
Process a series folder, filling in episode details and adding them to the database.
Todo:
Ideally we would return INFO_HAVE_ALREADY if we don't have to update any episodes and we should return INFO_NOT_FOUND only if no information is found for any of the episodes. INFO_ADDED then indicates we've added one or more episodes.
Parameters
files the episode files to process.
scraper scraper to use for finding online info
showInfo information for the show.
pDlgProcess progress dialog to update during processing. Defaults to NULL.
Returns
INFO_ERROR on failure, INFO_CANCELLED on cancellation, INFO_NOT_FOUND if an episode isn't found, or INFO_ADDED if all episodes are added.
Todo:
should we just skip to the next episode?
References CONTENT_TVSHOWS, CInfoScanner::FULL_NFO, g_localizeStrings, CLocalizeStrings::Get(), CVideoInfoDownloader::GetEpisodeDetails(), CVideoInfoDownloader::GetEpisodeList(), CFileItem::GetVideoInfoTag(), index(), CGUIDialogProgress::IsCanceled(), CLog::Log(), LOGDEBUG, LOGERROR, CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_strEpisodeGuide, CVideoInfoTag::m_strTitle, CInfoScanner::NO_NFO, CScraperUrl::ParseAndAppendUrlsFromEpisodeGuide(), CGUIDialogProgress::Progress(), CGUIDialogBoxBase::SetLine(), CFileItem::SetPath(), CGUIDialogProgress::SetPercentage(), and CGUIDialogProgress::ShowProgressBar().
Referenced by RetrieveInfoForEpisodes().
Process()
void KODI::VIDEO::CVideoInfoScanner::Process () protected virtual
References CVideoDatabase::CleanDatabase(), CDatabase::Close(), CDatabase::Compress(), DoScan(), end(), XFILE::CDirectory::Exists(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetGUI(), CGUIDialogExtendedProgressBar::GetHandle(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetLibraryInfoProvider(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, CInfoScanner::m_bCanInterrupt, CInfoScanner::m_bClean, CInfoScanner::m_bRunning, m_bStop, m_database, CInfoScanner::m_handle, m_pathsToClean, CInfoScanner::m_pathsToScan, CInfoScanner::m_showDialog, CGUIDialogProgressBarHandle::MarkFinished(), CVideoDatabase::Open(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::ResetLibraryBools(), CSettings::SETTING_VIDEOLIBRARY_BACKGROUNDUPDATE, CGUIDialogProgressBarHandle::SetTitle(), ANNOUNCEMENT::VideoLibrary, and WINDOW_DIALOG_EXT_PROGRESS.
Referenced by Start().
ProcessItemByVideoInfoTag()
bool KODI::VIDEO::CVideoInfoScanner::ProcessItemByVideoInfoTag (const CFileItem * item, EPISODELIST & episodeList) protected
References KODI::VIDEO::EPISODE::cDate, CDateTime::GetAsLocalizedDate(), CFileItem::GetPath(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), KODI::VIDEO::EPISODE::iEpisode, KODI::VIDEO::EPISODE::iSeason, KODI::VIDEO::EPISODE::isFolder, CFileItem::IsPlugin(), KODI::VIDEO::EPISODE::item, CLog::Log(), LOGDEBUG, CVideoInfoTag::m_firstAired, KODI::VIDEO::EPISODE::strPath, and KODI::VIDEO::EPISODE::strTitle.
ProcessVideoVersion()
bool KODI::VIDEO::CVideoInfoScanner::ProcessVideoVersion (VideoDbContentType itemType, int dbId) protected
References CGUIDialogVideoManagerVersions::ProcessVideoVersion().
Referenced by RetrieveInfoForMovie().
ProgressCancelled()
bool KODI::VIDEO::CVideoInfoScanner::ProgressCancelled (CGUIDialogProgress * progress, int heading, const std::string & line1) protected
Update the progress bar with the heading and line and check for cancellation.
Parameters
progress CGUIDialogProgress bar
heading string id of heading
line1 string to set for the first line
Returns
true if the user has cancelled the scanner, false otherwise
References CGUIDialogProgress::IsCanceled(), CGUIDialogProgress::Progress(), CGUIDialogBoxBase::SetHeading(), and CGUIDialogBoxBase::SetLine().
Referenced by RetrieveInfoForMovie(), RetrieveInfoForMusicVideo(), and RetrieveInfoForTvShow().
RetrieveInfoForEpisodes()
CInfoScanner::INFO_RET KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForEpisodes (CFileItem * item, long showID, const ADDON::ScraperPtr & scraper, bool useLocal, CGUIDialogProgress * progress = NULL) protected
References CVideoDatabase::AddSeason(), EnumerateSeriesFolder(), CVideoThumbLoader::GetArtTypes(), CVideoInfoDownloader::GetArtwork(), GetSeasonThumbs(), CVideoDatabase::GetTvShowInfo(), CVideoDatabase::GetTvShowSeasonArt(), CInfoScanner::INFO_ADDED, CInfoScanner::INFO_CANCELLED, CInfoScanner::INFO_HAVE_ALREADY, CInfoScanner::INFO_NOT_NEEDED, CGUIDialogProgress::IsCanceled(), CFileItem::IsPlugin(), m_bStop, m_database, MediaTypeSeason, OnProcessSeriesFolder(), and CVideoDatabase::SetArtForItem().
Referenced by RetrieveInfoForTvShow().
RetrieveInfoForMovie()
CInfoScanner::INFO_RET KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie (CFileItem * pItem, bool bDirNames, ADDON::ScraperPtr & scraper, bool useLocal, CScraperUrl * pURL, CGUIDialogProgress * pDlgProgress) protected
Todo:
This is not strictly correct as we could fail to download information here or error, or be cancelled
References AddVideo(), CInfoScanner::COMBINED_NFO, KODI::VIDEO::CVideoInfoTagLoaderFactory::CreateLoader(), FindVideo(), CInfoScanner::FULL_NFO, GetDetails(), CFileItem::GetDynPath(), CUtil::GetFilenameIdentifier(), CScraperUrl::GetFirstThumbUrl(), CGUIListItem::GetLabel(), CFileItem::GetMovieName(), CFileItem::GetPath(), CVideoInfoTag::GetTitle(), CFileItem::GetVideoInfoTag(), URIUtils::HasExtension(), CVideoDatabase::HasMovieInfo(), CScraperUrl::HasUrls(), CInfoScanner::INFO_ADDED, CInfoScanner::INFO_CANCELLED, CInfoScanner::INFO_ERROR, CInfoScanner::INFO_HAVE_ALREADY, CInfoScanner::INFO_NOT_FOUND, CInfoScanner::INFO_NOT_NEEDED, CFileItem::IsNFO(), KODI::PLAYLIST::IsPlayList(), KODI::VIDEO::IsVideo(), CLog::Log(), LOGDEBUG, CGUIListItem::m_bIsFolder, m_database, CInfoScanner::m_handle, m_ignoreVideoVersions, MOVIES, CInfoScanner::NO_NFO, CInfoScanner::OVERRIDE_NFO, ProcessVideoVersion(), ProgressCancelled(), CVideoInfoTag::Reset(), CGUIDialogProgressBarHandle::SetText(), CInfoScanner::TITLE_NFO, ADDON::TranslateContent(), and CInfoScanner::URL_NFO.
Referenced by RetrieveVideoInfo().
RetrieveInfoForMusicVideo()
CInfoScanner::INFO_RET KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo (CFileItem * pItem, bool bDirNames, ADDON::ScraperPtr & scraper, bool useLocal, CScraperUrl * pURL, CGUIDialogProgress * pDlgProgress) protected
Todo:
This is not strictly correct as we could fail to download information here or error, or be cancelled
References AddVideo(), CInfoScanner::COMBINED_NFO, KODI::VIDEO::CVideoInfoTagLoaderFactory::CreateLoader(), FindVideo(), CInfoScanner::FULL_NFO, GetDetails(), CUtil::GetFilenameIdentifier(), CScraperUrl::GetFirstThumbUrl(), CGUIListItem::GetLabel(), CFileItem::GetMovieName(), CFileItem::GetPath(), CVideoInfoTag::GetTitle(), CFileItem::GetVideoInfoTag(), URIUtils::HasExtension(), CVideoDatabase::HasMusicVideoInfo(), CScraperUrl::HasUrls(), CInfoScanner::INFO_ADDED, CInfoScanner::INFO_CANCELLED, CInfoScanner::INFO_ERROR, CInfoScanner::INFO_HAVE_ALREADY, CInfoScanner::INFO_NOT_FOUND, CInfoScanner::INFO_NOT_NEEDED, CFileItem::IsNFO(), KODI::PLAYLIST::IsPlayList(), KODI::VIDEO::IsVideo(), CLog::Log(), LOGDEBUG, CGUIListItem::m_bIsFolder, m_database, CInfoScanner::m_handle, CInfoScanner::NO_NFO, CInfoScanner::OVERRIDE_NFO, ProgressCancelled(), CVideoInfoTag::Reset(), CGUIDialogProgressBarHandle::SetText(), CInfoScanner::TITLE_NFO, ADDON::TranslateContent(), and CInfoScanner::URL_NFO.
Referenced by RetrieveVideoInfo().
RetrieveInfoForTvShow()
CInfoScanner::INFO_RET KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow (CFileItem * pItem, bool bDirNames, ADDON::ScraperPtr & scraper, bool useLocal, CScraperUrl * pURL, bool fetchEpisodes, CGUIDialogProgress * pDlgProgress) protected
References AddVideo(), CVariant::asString(), CInfoScanner::COMBINED_NFO, KODI::VIDEO::CVideoInfoTagLoaderFactory::CreateLoader(), FindVideo(), CInfoScanner::FULL_NFO, GetDetails(), URIUtils::GetDirectory(), CUtil::GetFilenameIdentifier(), CScraperUrl::GetFirstThumbUrl(), CFileItem::GetMovieName(), CFileItem::GetPath(), CVideoInfoTag::GetPath(), CGUIListItem::GetProperty(), CVideoDatabase::GetSeasonId(), CVideoInfoTag::GetTitle(), CVideoDatabase::GetTvShowId(), CVideoDatabase::GetTvShowInfo(), CFileItem::GetVideoInfoTag(), CScraperUrl::HasUrls(), CFileItem::HasVideoInfoTag(), CInfoScanner::INFO_ADDED, CInfoScanner::INFO_CANCELLED, CInfoScanner::INFO_ERROR, CInfoScanner::INFO_NOT_FOUND, CFileItem::IsPlugin(), CLog::Log(), LOGDEBUG, CGUIListItem::m_bIsFolder, m_database, CInfoScanner::m_handle, CVideoInfoTag::m_iIdShow, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_strShowTitle, CVideoInfoTag::m_strTitle, CVideoInfoTag::m_type, MediaTypeSeason, CInfoScanner::NO_NFO, CInfoScanner::OVERRIDE_NFO, ProgressCancelled(), CVideoInfoTag::Reset(), RetrieveInfoForEpisodes(), CVideoDatabase::SetPathHash(), CGUIDialogProgressBarHandle::SetText(), CInfoScanner::TITLE_NFO, ADDON::TranslateContent(), and CInfoScanner::URL_NFO.
Referenced by RetrieveVideoInfo().
RetrieveVideoInfo()
bool KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo (CFileItemList & items, bool bDirNames, CONTENT_TYPE content, bool useLocal = true, CScraperUrl * pURL = NULL, bool fetchEpisodes = true, CGUIDialogProgress * pDlgProgress = NULL)
Retrieve information for a list of items and add them to the database.
Parameters
items list of items to retrieve info for.
bDirNames whether we should use folder or file names for lookups.
content type of content to retrieve.
useLocal should local data (.nfo and art) be used. Defaults to true.
pURL an optional URL to use to retrieve online info. Defaults to NULL.
fetchEpisodes whether we are fetching episodes with shows. Defaults to true.
pDlgProgress progress dialog to update and check for cancellation during processing. Defaults to NULL.
Returns
true if we successfully found information for some items, false otherwise
References CDatabase::Close(), ADDON::content, CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_TVSHOWS, CUtil::ExcludeFileOrFolder(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetEventLog(), URIUtils::GetFileName(), CFileItem::GetPath(), CVideoDatabase::GetPathId(), CVideoDatabase::GetScraperForPath(), CServiceBroker::GetSettingsComponent(), CVideoDatabase::GetSubPaths(), CInfoScanner::HasNoMedia(), CInfoScanner::INFO_ADDED, CInfoScanner::INFO_CANCELLED, CInfoScanner::INFO_ERROR, CInfoScanner::INFO_HAVE_ALREADY, CInfoScanner::INFO_NOT_FOUND, CLog::Log(), LOGERROR, LOGWARNING, CInfoScanner::m_bClean, CGUIListItem::m_bIsFolder, m_database, CInfoScanner::m_handle, m_pathsToClean, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, CVideoDatabase::Open(), CGUIDialogProgress::Progress(), RetrieveInfoForMovie(), RetrieveInfoForMusicVideo(), RetrieveInfoForTvShow(), CGUIDialogProgressBarHandle::SetPercentage(), CGUIDialogProgress::SetPercentage(), CGUIDialogProgress::ShowProgressBar(), CFileItemList::Size(), and Warning.
Referenced by DoScan(), and CVideoLibraryRefreshingJob::Work().
Start()
void KODI::VIDEO::CVideoInfoScanner::Start (const std::string & strDirectory, bool scanAll = false)
Scan a folder using the background scanner.
Parameters
strDirectory path to scan
scanAll whether to scan everything not already scanned (regardless of whether the user normally doesn't want a folder scanned.) Defaults to false.
References CDatabase::Close(), XFILE::CMultiPathDirectory::GetPaths(), CVideoDatabase::GetPaths(), CServiceBroker::GetSettingsComponent(), CVideoDatabase::GetSubPaths(), URIUtils::IsMultiPath(), CInfoScanner::m_bClean, CInfoScanner::m_bRunning, m_database, m_pathsToClean, CInfoScanner::m_pathsToScan, m_scanAll, m_strStartDir, CVideoDatabase::Open(), and Process().
Referenced by CVideoLibraryScanningJob::Work().
Stop()
void KODI::VIDEO::CVideoInfoScanner::Stop ()
References CDatabase::Interrupt(), CInfoScanner::m_bCanInterrupt, m_bStop, and m_database.
Referenced by CVideoLibraryScanningJob::Cancel().
Member Data Documentation
m_bStop
bool KODI::VIDEO::CVideoInfoScanner::m_bStop protected
Referenced by CVideoInfoScanner(), DoScan(), Process(), RetrieveInfoForEpisodes(), and Stop().
m_database
CVideoDatabase KODI::VIDEO::CVideoInfoScanner::m_database protected
Referenced by DoScan(), EnumerateSeriesFolder(), Process(), RetrieveInfoForEpisodes(), RetrieveInfoForMovie(), RetrieveInfoForMusicVideo(), RetrieveInfoForTvShow(), RetrieveVideoInfo(), Start(), and Stop().
m_ignoreVideoExtras
bool KODI::VIDEO::CVideoInfoScanner::m_ignoreVideoExtras {false} protected
Referenced by CVideoInfoScanner(), and DoScan().
m_ignoreVideoVersions
bool KODI::VIDEO::CVideoInfoScanner::m_ignoreVideoVersions {false} protected
Referenced by CVideoInfoScanner(), and RetrieveInfoForMovie().
m_pathsToClean
std::set<int> KODI::VIDEO::CVideoInfoScanner::m_pathsToClean protected
Referenced by DoScan(), EnumerateSeriesFolder(), Process(), RetrieveVideoInfo(), and Start().
m_pathsToCount
std::set<std::string> KODI::VIDEO::CVideoInfoScanner::m_pathsToCount protected
m_scanAll
bool KODI::VIDEO::CVideoInfoScanner::m_scanAll protected
Referenced by CVideoInfoScanner(), DoScan(), and Start().
m_strStartDir
std::string KODI::VIDEO::CVideoInfoScanner::m_strStartDir protected
Referenced by Start().
The documentation for this class was generated from the following files:
VideoInfoScanner.h
VideoInfoScanner.cpp