Kodi Documentation: PVR::CPVRTimerRuleMatcher Class Reference
PVR::CPVRTimerRuleMatcher Class Reference
#include <PVRTimerRuleMatcher.h>
Public Member Functions
CPVRTimerRuleMatcher (const std::shared_ptr< CPVRTimerInfoTag > &timerRule, const CDateTime &start)
virtual ~CPVRTimerRuleMatcher ()
std::shared_ptr< CPVRTimerInfoTag > GetTimerRule () const
std::shared_ptr< const CPVRChannel > GetChannel () const
CDateTime GetNextTimerStart () const
bool Matches (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
Private Member Functions
bool MatchSeriesLink (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
bool MatchChannel (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
bool MatchStart (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
bool MatchEnd (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
bool MatchDayOfWeek (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
bool MatchSearchText (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
Private Attributes
const std::shared_ptr< CPVRTimerInfoTag > m_timerRule
CDateTime m_start
std::unique_ptr< CRegExp > m_textSearch
Constructor & Destructor Documentation
CPVRTimerRuleMatcher()
CPVRTimerRuleMatcher::CPVRTimerRuleMatcher (const std::shared_ptr< CPVRTimerInfoTag > & timerRule, const CDateTime & start)
~CPVRTimerRuleMatcher()
CPVRTimerRuleMatcher::~CPVRTimerRuleMatcher () virtual default
Member Function Documentation
GetChannel()
std::shared_ptr< const CPVRChannel > CPVRTimerRuleMatcher::GetChannel () const
References m_timerRule.
Referenced by anonymous_namespace{PVRTimers.cpp}::GetEpgTagsForTimerRule().
GetNextTimerStart()
CDateTime CPVRTimerRuleMatcher::GetNextTimerStart () const
References CDateTime::GetAsUTCDateTime(), CDateTime::GetDay(), CDateTime::GetDayOfWeek(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetYear(), m_start, m_timerRule, and PVR_WEEKDAY_ALLDAYS.
Referenced by PVR::CPVRTimers::AddLocalTimer(), and PVR::CPVRTimers::UpdateEntries().
GetTimerRule()
std::shared_ptr< CPVRTimerInfoTag > PVR::CPVRTimerRuleMatcher::GetTimerRule () const inline
References m_timerRule.
MatchChannel()
bool CPVRTimerRuleMatcher::MatchChannel (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const private
References m_timerRule, PVR_CHANNEL_INVALID_UID, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by Matches().
MatchDayOfWeek()
bool CPVRTimerRuleMatcher::MatchDayOfWeek (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const private
References PVR::CPVRTimerInfoTag::ConvertUTCToLocalTime(), CDateTime::GetDayOfWeek(), m_timerRule, and PVR_WEEKDAY_ALLDAYS.
Referenced by Matches().
MatchEnd()
bool CPVRTimerRuleMatcher::MatchEnd (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const private
References PVR::CPVRTimerInfoTag::ConvertUTCToLocalTime(), CDateTime::GetHour(), CDateTime::GetMinute(), and m_timerRule.
Referenced by Matches().
Matches()
bool CPVRTimerRuleMatcher::Matches (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const
References PVR::CPVRTimerInfoTag::ConvertUTCToLocalTime(), m_start, MatchChannel(), MatchDayOfWeek(), MatchEnd(), MatchSearchText(), MatchSeriesLink(), and MatchStart().
MatchSearchText()
bool CPVRTimerRuleMatcher::MatchSearchText (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const private
References m_textSearch, and m_timerRule.
Referenced by Matches().
MatchSeriesLink()
bool CPVRTimerRuleMatcher::MatchSeriesLink (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const private
References m_timerRule.
Referenced by Matches().
MatchStart()
bool CPVRTimerRuleMatcher::MatchStart (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const private
References PVR::CPVRTimerInfoTag::ConvertUTCToLocalTime(), CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetYear(), and m_timerRule.
Referenced by Matches().
Member Data Documentation
m_start
CDateTime PVR::CPVRTimerRuleMatcher::m_start private
Referenced by GetNextTimerStart(), and Matches().
m_textSearch
std::unique_ptr<CRegExp> PVR::CPVRTimerRuleMatcher::m_textSearch mutable private
Referenced by MatchSearchText().
m_timerRule
const std::shared_ptr<CPVRTimerInfoTag> PVR::CPVRTimerRuleMatcher::m_timerRule private
Referenced by GetChannel(), GetNextTimerStart(), GetTimerRule(), MatchChannel(), MatchDayOfWeek(), MatchEnd(), MatchSearchText(), MatchSeriesLink(), and MatchStart().
The documentation for this class was generated from the following files:
PVRTimerRuleMatcher.h
PVRTimerRuleMatcher.cpp