Kodi Documentation: PVR::CPVRChannel Class Reference
PVR::CPVRChannel Class Reference
#include <PVRChannel.h>
Public Member Functions
CPVRChannel (bool bRadio)
CPVRChannel (bool bRadio, const std::string &iconPath)
CPVRChannel (const PVR_CHANNEL &channel, unsigned int iClientId)
virtual ~CPVRChannel ()
bool operator== (const CPVRChannel &right) const
bool operator!= (const CPVRChannel &right) const
void Serialize (CVariant &value) const override
Kodi related channel methods
bool QueueDelete ()
Delete this channel from the database.
bool UpdateFromClient (const std::shared_ptr< const CPVRChannel > &channel)
Update this channel tag with the data of the given channel tag.
bool Persist ()
Persists the changes in the database.
int ChannelID () const
bool IsNew () const
bool SetChannelID (int iDatabaseId)
Set the identifier for this channel.
bool IsRadio () const
bool IsHidden () const
bool SetHidden (bool bIsHidden, bool bIsUserSetHidden=false)
Set to true to hide this channel. Set to false to unhide it.
bool IsLocked () const
bool SetLocked (bool bIsLocked)
Set to true to lock this channel. Set to false to unlock it.
std::shared_ptr< CPVRRadioRDSInfoTag > GetRadioRDSInfoTag () const
Obtain the Radio RDS data for this channel, if available.
void SetRadioRDSInfoTag (const std::shared_ptr< CPVRRadioRDSInfoTag > &tag)
Set the Radio RDS data for the channel.
bool HasArchive () const
bool SetArchive (bool bHasArchive)
Set the archive support flag for this channel.
std::string ClientIconPath () const
std::string IconPath () const
bool IsUserSetIcon () const
bool IsUserSetName () const
bool IsUserSetHidden () const
int LastWatchedGroupId () const
bool SetIconPath (const std::string &strIconPath, bool bIsUserSetIcon=false)
Set the path to the icon for this channel.
std::string ChannelName () const
bool SetChannelName (const std::string &strChannelName, bool bIsUserSetName=false)
Set the name for this channel used by XBMC.
time_t LastWatched () const
bool SetLastWatched (time_t lastWatched, int groupId)
Set the last time the channel has been watched and the channel group used to watch.
CDateTime DateTimeAdded () const
bool SetDateTimeAdded (const CDateTime &dateTimeAdded)
Set the date and time the channel was added to the TV database.
bool IsChanged () const
Check whether this channel has unpersisted data changes.
void Persisted ()
reset changed flag after persist
Client related channel methods
int UniqueID () const
A unique identifier for this channel.
int ClientID () const
bool SetClientID (int iClientId)
Set the identifier of the client that serves this channel.
const CPVRChannelNumber & ClientChannelNumber () const
std::string ClientChannelName () const
std::string MimeType () const
The stream input mime type.
void ToSortable (SortItem &sortable, Field field) const override
std::pair< int, int > StorageId () const
bool IsEncrypted () const
Return true if this channel is encrypted.
int EncryptionSystem () const
Return the encryption system ID for this channel. 0 for FTA.
std::string EncryptionName () const
Static Public Attributes
static const std::string IMAGE_OWNER_PATTERN = "pvrchannel_{}"
Private Attributes
Kodi related channel data
int m_iChannelId = -1
bool m_bIsRadio = false
bool m_bIsHidden = false
bool m_bIsUserSetName = false
bool m_bIsUserSetIcon = false
bool m_bIsUserSetHidden = false
bool m_bIsLocked = false
CPVRCachedImage m_iconPath
std::string m_strChannelName
time_t m_iLastWatched = 0
bool m_bChanged
std::shared_ptr< CPVRRadioRDSInfoTag > m_rdsTag
bool m_bHasArchive = false
EPG related channel data
int m_iEpgId = -1
bool m_bEPGEnabled = false
std::string m_strEPGScraper
std::shared_ptr< CPVREpg > m_epg
Client related channel data
int m_iUniqueId = -1
int m_iClientId
CPVRChannelNumber m_clientChannelNumber
std::string m_strClientChannelName
std::string m_strMimeType
int m_iClientEncryptionSystem
std::string m_strClientEncryptionName
int m_iClientOrder = 0
int m_iClientProviderUid
int m_lastWatchedGroupId
CDateTime m_dateTimeAdded
CCriticalSection m_critSection
Friends
class CPVRDatabase
EPG methods
int EpgID () const
bool CreateEPG ()
Create the EPG for this channel, if it does not yet exist.
std::shared_ptr< CPVREpg > GetEPG () const
Get the EPG table for this channel.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetEpgTags () const
Get the EPG tags for this channel.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetEPGTimeline (const CDateTime &timelineStart, const CDateTime &timelineEnd, const CDateTime &minEventEnd, const CDateTime &maxEventStart) const
Get all EPG tags for the given time frame, including "gap" tags.
std::shared_ptr< CPVREpgInfoTag > CreateEPGGapTag (const CDateTime &start, const CDateTime &end) const
Create a "gap" EPG tag.
std::shared_ptr< CPVREpgInfoTag > GetEPGNow () const
Get the EPG tag that is now active on this channel.
std::shared_ptr< CPVREpgInfoTag > GetEPGPrevious () const
Get the EPG tag that was previously active on this channel.
std::shared_ptr< CPVREpgInfoTag > GetEPGNext () const
Get the EPG tag that will be next active on this channel.
bool EPGEnabled () const
bool SetEPGEnabled (bool bEPGEnabled)
Set to true if an EPG should be used for this channel. Set to false otherwise.
std::string EPGScraper () const
Get the name of the scraper to be used for this channel.
bool SetEPGScraper (const std::string &strScraper)
Set the name of the scraper to be used for this channel.
bool CanRecord () const
int ClientOrder () const
Get the client order for this channel.
int ClientProviderUid () const
Get the uid of the provider on the client which this channel is from.
void Notify (const PVREvent &event)
CEventStream callback for PVR events.
void Lock ()
Lock the instance. No other thread gets access to this channel until Unlock was called.
void Unlock ()
Unlock the instance. Other threads may get access to this channel again.
std::shared_ptr< CPVRProvider > GetDefaultProvider () const
Get the default provider of this channel. The default provider represents the PVR add-on itself.
bool HasClientProvider () const
Whether or not this channel has a provider set by the client.
std::shared_ptr< CPVRProvider > GetProvider () const
Get the provider of this channel. This may be the default provider or a custom provider set by the client. If HasClientProvider() returns true the provider will be custom from the client, otherwise the default provider.
static std::string GetEncryptionName (int iCaid)
CPVRChannel ()=delete
CPVRChannel (const CPVRChannel &tag)=delete
CPVRChannel & operator= (const CPVRChannel &channel)=delete
void UpdateEncryptionName ()
Update the encryption name after SetEncryptionSystem() has been called.
void ResetEPG ()
Reset the EPG instance pointer.
bool SetClientProviderUid (int iClientProviderUid)
Set the client provider Uid for this channel.
Additional Inherited Members
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Protected Member Functions inherited from ISortable
~ISortable ()=default
Constructor & Destructor Documentation
CPVRChannel() [1/5]
CPVRChannel::CPVRChannel (bool bRadio) explicit
References UpdateEncryptionName().
CPVRChannel() [2/5]
CPVRChannel::CPVRChannel (bool bRadio, const std::string & iconPath)
References UpdateEncryptionName().
CPVRChannel() [3/5]
CPVRChannel::CPVRChannel (const PVR_CHANNEL & channel, unsigned int iClientId)
References g_localizeStrings, CLocalizeStrings::Get(), m_iUniqueId, m_strChannelName, and UpdateEncryptionName().
~CPVRChannel()
CPVRChannel::~CPVRChannel () virtual
References ResetEPG().
CPVRChannel() [4/5]
PVR::CPVRChannel::CPVRChannel () private delete
CPVRChannel() [5/5]
PVR::CPVRChannel::CPVRChannel (const CPVRChannel & tag) private delete
Member Function Documentation
CanRecord()
bool CPVRChannel::CanRecord () const
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), and m_iClientId.
ChannelID()
int CPVRChannel::ChannelID () const
Returns
The identifier given to this channel by the TV database.
References m_critSection, and m_iChannelId.
Referenced by PVR::CPVRDatabase::QueueDeleteQuery(), and PVR::CPVRDatabase::UpdateLastWatched().
ChannelName()
std::string CPVRChannel::ChannelName () const
Returns
The name for this channel used by XBMC.
References m_critSection, and m_strChannelName.
Referenced by PVR::CPVRDatabase::Persist(), and PVR::CPVRDatabase::QueueDeleteQuery().
ClientChannelName()
std::string CPVRChannel::ClientChannelName () const
Returns
The name of this channel on the client.
References m_critSection, and m_strClientChannelName.
ClientChannelNumber()
const CPVRChannelNumber & CPVRChannel::ClientChannelNumber () const
Get the channel number on the client.
Returns
The channel number on the client.
References m_clientChannelNumber, and m_critSection.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonChannel::CAddonChannel().
ClientIconPath()
std::string CPVRChannel::ClientIconPath () const
Returns
The path to the icon for this channel as given by the client.
References PVR::CPVRCachedImage::GetClientImage(), m_critSection, and m_iconPath.
Referenced by PVR::CPVRDatabase::Persist(), Serialize(), and SetIconPath().
ClientID()
int CPVRChannel::ClientID () const
Returns
The identifier of the client that serves this channel.
References m_critSection, and m_iClientId.
Referenced by PVR::CPVRDatabase::Persist().
ClientOrder()
int PVR::CPVRChannel::ClientOrder () const inline
Get the client order for this channel.
Returns
iOrder The order for this channel
References m_iClientOrder.
ClientProviderUid()
int PVR::CPVRChannel::ClientProviderUid () const inline
Get the uid of the provider on the client which this channel is from.
Returns
the client uid of the provider or PVR_PROVIDER_INVALID_UID
References m_iClientProviderUid.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonChannel::CAddonChannel(), and PVR::CPVRDatabase::Persist().
CreateEPG()
bool CPVRChannel::CreateEPG ()
Create the EPG for this channel, if it does not yet exist.
Returns
true if a new epg was created, false otherwise.
References PVR::CPVREpgContainer::CreateChannelEpg(), PVR::CPVRManager::EpgContainer(), CServiceBroker::GetPVRManager(), IsRadio(), LOGDEBUG, LOGPVR, m_bChanged, m_critSection, m_epg, m_iEpgId, m_strChannelName, m_strEPGScraper, and Notify().
Referenced by GetEPG().
CreateEPGGapTag()
std::shared_ptr< CPVREpgInfoTag > CPVRChannel::CreateEPGGapTag (const CDateTime & start, const CDateTime & end) const
Create a "gap" EPG tag.
Parameters
start Start of gap.
end End of gap.
Returns
The tag.
References end(), and GetEPG().
Referenced by GetEPGTimeline().
DateTimeAdded()
CDateTime CPVRChannel::DateTimeAdded () const
Returns
the date and time this channel was added to the TV database.
References m_critSection, and m_dateTimeAdded.
Referenced by PVR::CPVRDatabase::Persist().
EncryptionName()
std::string CPVRChannel::EncryptionName () const
Returns
A friendly name for the used encryption system.
References m_critSection, and m_strClientEncryptionName.
EncryptionSystem()
int CPVRChannel::EncryptionSystem () const
Return the encryption system ID for this channel. 0 for FTA.
Return the encryption system ID for this channel. 0 for FTA. The values are documented on: http://www.dvb.org/index.php?id=174.
Returns
Return the encryption system ID for this channel.
References m_critSection, and m_iClientEncryptionSystem.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonChannel::CAddonChannel().
EPGEnabled()
bool CPVRChannel::EPGEnabled () const
Returns
Don't use an EPG for this channel if set to false.
References m_bEPGEnabled, and m_critSection.
Referenced by PVR::CPVRDatabase::Persist().
EpgID()
int CPVRChannel::EpgID () const
Returns
The ID of the EPG table to use for this channel or -1 if it isn't set.
References m_critSection, and m_iEpgId.
Referenced by PVR::CPVRDatabase::Persist().
EPGScraper()
std::string CPVRChannel::EPGScraper () const
Get the name of the scraper to be used for this channel.
Get the name of the scraper to be used for this channel. The default is 'client', which means the EPG should be loaded from the backend.
Returns
The name of the scraper to be used for this channel.
References m_critSection, and m_strEPGScraper.
Referenced by PVR::CPVRDatabase::Persist().
GetDefaultProvider()
std::shared_ptr< CPVRProvider > CPVRChannel::GetDefaultProvider () const
Get the default provider of this channel. The default provider represents the PVR add-on itself.
Returns
The default provider of this channel
References CServiceBroker::GetPVRManager(), m_iClientId, PVR::CPVRManager::Providers(), and PVR_PROVIDER_INVALID_UID.
Referenced by GetProvider().
GetEncryptionName()
std::string CPVRChannel::GetEncryptionName (int iCaid) static
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by PVR::CPVRGUIInfo::CharInfoEncryption(), and UpdateEncryptionName().
GetEPG()
std::shared_ptr< CPVREpg > CPVRChannel::GetEPG () const
Get the EPG table for this channel.
Returns
The EPG for this channel.
References CreateEPG(), m_bEPGEnabled, m_bIsHidden, m_critSection, and m_epg.
Referenced by CreateEPGGapTag(), GetEPGNext(), GetEPGNow(), GetEPGPrevious(), GetEpgTags(), GetEPGTimeline(), QueueDelete(), SetChannelID(), SetChannelName(), SetIconPath(), and SetLocked().
GetEPGNext()
std::shared_ptr< CPVREpgInfoTag > CPVRChannel::GetEPGNext () const
Get the EPG tag that will be next active on this channel.
Get the EPG tag that will be next active on this channel. Will return an empty tag if there is none.
Returns
The EPG tag that will be next active.
References GetEPG().
Referenced by Serialize().
GetEPGNow()
std::shared_ptr< CPVREpgInfoTag > CPVRChannel::GetEPGNow () const
Get the EPG tag that is now active on this channel.
Get the EPG tag that is now active on this channel. Will return an empty tag if there is none.
Returns
The EPG tag that is now active.
References GetEPG().
Referenced by Serialize().
GetEPGPrevious()
std::shared_ptr< CPVREpgInfoTag > CPVRChannel::GetEPGPrevious () const
Get the EPG tag that was previously active on this channel.
Get the EPG tag that was previously active on this channel. Will return an empty tag if there is none.
Returns
The EPG tag that was previously active.
References GetEPG().
GetEpgTags()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVRChannel::GetEpgTags () const
Get the EPG tags for this channel.
Returns
The tags.
References GetEPG(), LOGDEBUG, LOGPVR, and m_strChannelName.
GetEPGTimeline()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVRChannel::GetEPGTimeline (const CDateTime & timelineStart, const CDateTime & timelineEnd, const CDateTime & minEventEnd, const CDateTime & maxEventStart) const
Get all EPG tags for the given time frame, including "gap" tags.
Parameters
timelineStart Start of time line.
timelineEnd End of time line.
minEventEnd The minimum end time of the events to return.
maxEventStart The maximum start time of the events to return.
Returns
The matching tags.
References CreateEPGGapTag(), and GetEPG().
GetProvider()
std::shared_ptr< CPVRProvider > CPVRChannel::GetProvider () const
Get the provider of this channel. This may be the default provider or a custom provider set by the client. If HasClientProvider() returns true the provider will be custom from the client, otherwise the default provider.
Returns
The provider of this channel
References GetDefaultProvider(), CServiceBroker::GetPVRManager(), m_iClientId, m_iClientProviderUid, and PVR::CPVRManager::Providers().
GetRadioRDSInfoTag()
std::shared_ptr< CPVRRadioRDSInfoTag > CPVRChannel::GetRadioRDSInfoTag () const
Obtain the Radio RDS data for this channel, if available.
Returns
The Radio RDS data or nullptr.
References m_critSection, and m_rdsTag.
HasArchive()
bool CPVRChannel::HasArchive () const
Returns
True if this channel has archive support, false otherwise
References m_bHasArchive, and m_critSection.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonChannel::CAddonChannel(), and PVR::CPVRDatabase::Persist().
HasClientProvider()
bool CPVRChannel::HasClientProvider () const
Whether or not this channel has a provider set by the client.
Returns
True if a provider was set by the client, false otherwise.
References m_critSection, m_iClientProviderUid, and PVR_PROVIDER_INVALID_UID.
IconPath()
std::string CPVRChannel::IconPath () const
Returns
The path to the icon for this channel.
References PVR::CPVRCachedImage::GetLocalImage(), m_critSection, and m_iconPath.
Referenced by PVR::CPVRDatabase::Persist(), SetIconPath(), and UpdateFromClient().
IsChanged()
bool CPVRChannel::IsChanged () const
Check whether this channel has unpersisted data changes.
Returns
True if this channel has changes to persist, false otherwise
References m_bChanged, and m_critSection.
IsEncrypted()
bool CPVRChannel::IsEncrypted () const
Return true if this channel is encrypted.
Return true if this channel is encrypted. Does not inform whether XBMC can play the file. Decryption should be done by the client.
Returns
Return true if this channel is encrypted.
References m_critSection, and m_iClientEncryptionSystem.
IsHidden()
bool CPVRChannel::IsHidden () const
Returns
True if this channel is hidden. False if not.
References m_bIsHidden, and m_critSection.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonChannel::CAddonChannel(), and PVR::CPVRDatabase::Persist().
IsLocked()
bool CPVRChannel::IsLocked () const
Returns
True if this channel is locked. False if not.
References m_bIsLocked, and m_critSection.
Referenced by PVR::CPVRDatabase::Persist().
IsNew()
bool CPVRChannel::IsNew () const
Returns
True when not persisted yet, false otherwise.
References m_critSection, and m_iChannelId.
IsRadio()
bool PVR::CPVRChannel::IsRadio () const inline
Returns
True if this channel is a radio channel, false if not.
References m_bIsRadio.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonChannel::CAddonChannel(), CreateEPG(), and PVR::CPVRDatabase::Persist().
IsUserSetHidden()
bool CPVRChannel::IsUserSetHidden () const
Returns
True if user changed the hidden flag via GUI, False if not
References m_bIsUserSetHidden, and m_critSection.
Referenced by PVR::CPVRDatabase::Persist(), and UpdateFromClient().
IsUserSetIcon()
bool CPVRChannel::IsUserSetIcon () const
Returns
True if this user changed icon via GUI. False if not.
References m_bIsUserSetIcon, and m_critSection.
Referenced by PVR::CPVRDatabase::Persist(), and UpdateFromClient().
IsUserSetName()
bool CPVRChannel::IsUserSetName () const
Returns
whether the user has changed the channel name through the GUI
References m_bIsUserSetName, and m_critSection.
Referenced by PVR::CPVRDatabase::Persist(), and UpdateFromClient().
LastWatched()
time_t CPVRChannel::LastWatched () const
Returns
Time channel has been watched last.
References m_critSection, and m_iLastWatched.
Referenced by PVR::CPVRDatabase::Persist(), and PVR::CPVRDatabase::UpdateLastWatched().
LastWatchedGroupId()
int CPVRChannel::LastWatchedGroupId () const
Returns
the id of the channel group the channel was watched from the last time; -1 if unknown.
References m_critSection, and m_lastWatchedGroupId.
Referenced by PVR::CPVRDatabase::Persist().
Lock()
void PVR::CPVRChannel::Lock () inline
Lock the instance. No other thread gets access to this channel until Unlock was called.
References m_critSection.
MimeType()
std::string CPVRChannel::MimeType () const
The stream input mime type.
The stream input type If it is empty, ffmpeg will try to scan the stream to find the right input format. See https://www.iana.org/assignments/media-types/media-types.xhtml for a list of the input formats.
Returns
The stream input type
References m_critSection, and m_strMimeType.
Notify()
void CPVRChannel::Notify (const PVREvent & event)
CEventStream callback for PVR events.
Parameters
event The event.
References PVR::EpgDeleted, and ResetEPG().
Referenced by CreateEPG().
operator!=()
bool CPVRChannel::operator!= (const CPVRChannel & right) const
References right.
operator=()
CPVRChannel & PVR::CPVRChannel::operator= (const CPVRChannel & channel) private delete
operator==()
bool CPVRChannel::operator== (const CPVRChannel & right) const
References m_bIsRadio, m_iClientId, m_iUniqueId, and right.
Persist()
bool CPVRChannel::Persist ()
Persists the changes in the database.
Returns
True if the changes were saved successfully, false otherwise.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), LOGDEBUG, LOGPVR, m_bChanged, m_critSection, m_iChannelId, and m_strChannelName.
Persisted()
void CPVRChannel::Persisted ()
reset changed flag after persist
References m_bChanged, and m_critSection.
QueueDelete()
bool CPVRChannel::QueueDelete ()
Delete this channel from the database.
Returns
True if it was deleted successfully, false otherwise.
References GetEPG(), CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), and ResetEPG().
ResetEPG()
void CPVRChannel::ResetEPG () private
Reset the EPG instance pointer.
References m_critSection, and m_epg.
Referenced by Notify(), QueueDelete(), and ~CPVRChannel().
Serialize()
void CPVRChannel::Serialize (CVariant & value) const override virtual
Implements ISerializable.
References ClientIconPath(), CDateTime::GetAsDBDate(), GetEPGNext(), GetEPGNow(), CDateTime::IsValid(), m_bHasArchive, m_bIsHidden, m_bIsLocked, m_bIsRadio, m_dateTimeAdded, m_iChannelId, m_iClientId, m_iLastWatched, m_iUniqueId, m_strChannelName, and value.
SetArchive()
bool CPVRChannel::SetArchive (bool bHasArchive)
Set the archive support flag for this channel.
Parameters
bHasArchive True to set the flag, false to reset.
Returns
True if the flag was changed, false otherwise.
References m_bChanged, m_bHasArchive, and m_critSection.
Referenced by UpdateFromClient().
SetChannelID()
bool CPVRChannel::SetChannelID (int iDatabaseId)
Set the identifier for this channel.
Parameters
iDatabaseId The new channel ID
Returns
True if something changed, false otherwise.
References GetEPG(), m_bChanged, m_critSection, and m_iChannelId.
SetChannelName()
bool CPVRChannel::SetChannelName (const std::string & strChannelName, bool bIsUserSetName = false)
Set the name for this channel used by XBMC.
Parameters
strChannelName The new channel name.
bIsUserSetName whether the change was triggered by the user directly
Returns
True if something changed, false otherwise.
References PVR::CPVRChannelNumber::FormattedChannelNumber(), g_localizeStrings, CLocalizeStrings::Get(), GetEPG(), m_bChanged, m_bIsUserSetName, m_clientChannelNumber, m_critSection, and m_strChannelName.
Referenced by UpdateFromClient().
SetClientID()
bool CPVRChannel::SetClientID (int iClientId)
Set the identifier of the client that serves this channel.
Parameters
iClientId The new ID.
Returns
True if something changed, false otherwise.
References m_bChanged, m_critSection, and m_iClientId.
Referenced by UpdateFromClient().
SetClientProviderUid()
bool CPVRChannel::SetClientProviderUid (int iClientProviderUid) private
Set the client provider Uid for this channel.
Parameters
iClientProviderUid The provider Uid for this channel
Returns
True if something changed, false otherwise.
References m_bChanged, m_critSection, and m_iClientProviderUid.
Referenced by UpdateFromClient().
SetDateTimeAdded()
bool CPVRChannel::SetDateTimeAdded (const CDateTime & dateTimeAdded)
Set the date and time the channel was added to the TV database.
Parameters
dateTimeAdded The date and time.
Returns
True if something changed, false otherwise.
References m_bChanged, m_critSection, and m_dateTimeAdded.
SetEPGEnabled()
bool CPVRChannel::SetEPGEnabled (bool bEPGEnabled)
Set to true if an EPG should be used for this channel. Set to false otherwise.
Parameters
bEPGEnabled The new value.
Returns
True if something changed, false otherwise.
References m_bChanged, m_bEPGEnabled, m_critSection, and m_epg.
SetEPGScraper()
bool CPVRChannel::SetEPGScraper (const std::string & strScraper)
Set the name of the scraper to be used for this channel.
Set the name of the scraper to be used for this channel. Set to "client" to load the EPG from the backend
Parameters
strScraper The new scraper name.
Returns
True if something changed, false otherwise.
References m_bChanged, m_critSection, m_epg, and m_strEPGScraper.
SetHidden()
bool CPVRChannel::SetHidden (bool bIsHidden, bool bIsUserSetHidden = false)
Set to true to hide this channel. Set to false to unhide it.
Set to true to hide this channel. Set to false to unhide it. The EPG of hidden channels won't be updated.
Parameters
bIsHidden The new setting.
bIsUserSetIcon true if user changed the hidden flag via GUI, false otherwise.
Returns
True if something changed, false otherwise.
References m_bChanged, m_bIsHidden, m_bIsUserSetHidden, m_critSection, and m_epg.
Referenced by UpdateFromClient().
SetIconPath()
bool CPVRChannel::SetIconPath (const std::string & strIconPath, bool bIsUserSetIcon = false)
Set the path to the icon for this channel.
Parameters
strIconPath The new path.
bIsUserSetIcon true if user changed the icon via GUI, false otherwise.
Returns
True if something changed, false otherwise.
References ClientIconPath(), GetEPG(), IconPath(), LOGERROR, m_bChanged, m_bIsUserSetIcon, m_critSection, m_iconPath, and PVR::CPVRCachedImage::SetClientImage().
Referenced by UpdateFromClient().
SetLastWatched()
bool CPVRChannel::SetLastWatched (time_t lastWatched, int groupId)
Set the last time the channel has been watched and the channel group used to watch.
Parameters
lastWatched The new last watched time value.
groupId the id of the group used to watch the channel.
Returns
True if something changed, false otherwise.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), m_critSection, m_iLastWatched, and m_lastWatchedGroupId.
SetLocked()
bool CPVRChannel::SetLocked (bool bIsLocked)
Set to true to lock this channel. Set to false to unlock it.
Set to true to lock this channel. Set to false to unlock it. Locked channels need can only be viewed if parental PIN entered.
Parameters
bIsLocked The new setting.
Returns
True if something changed, false otherwise.
References GetEPG(), m_bChanged, m_bIsLocked, and m_critSection.
SetRadioRDSInfoTag()
void CPVRChannel::SetRadioRDSInfoTag (const std::shared_ptr< CPVRRadioRDSInfoTag > & tag)
Set the Radio RDS data for the channel.
Parameters
tag The RDS data.
References m_critSection, and m_rdsTag.
StorageId()
std::pair< int, int > PVR::CPVRChannel::StorageId () const inline
Returns
Storage id for this channel in CPVRChannelGroup
References m_iClientId, and m_iUniqueId.
ToSortable()
void CPVRChannel::ToSortable (SortItem & sortable, Field field) const override virtual
Implements ISortable.
References FieldChannelName, FieldDateAdded, FieldLastPlayed, FieldProvider, CDateTime::GetAsDBDateTime(), CDateTime::IsValid(), m_critSection, m_dateTimeAdded, m_iClientId, m_iClientProviderUid, m_iLastWatched, and m_strChannelName.
UniqueID()
int CPVRChannel::UniqueID () const
A unique identifier for this channel.
A unique identifier for this channel. It can be used to find the same channel on different providers
Returns
The Unique ID.
References m_iUniqueId.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonChannel::CAddonChannel(), and PVR::CPVRDatabase::Persist().
Unlock()
void PVR::CPVRChannel::Unlock () inline
Unlock the instance. Other threads may get access to this channel again.
References m_critSection.
UpdateEncryptionName()
void CPVRChannel::UpdateEncryptionName () private
Update the encryption name after SetEncryptionSystem() has been called.
References GetEncryptionName(), m_critSection, m_iClientEncryptionSystem, and m_strClientEncryptionName.
Referenced by CPVRChannel(), CPVRChannel(), CPVRChannel(), and UpdateFromClient().
UpdateFromClient()
bool CPVRChannel::UpdateFromClient (const std::shared_ptr< const CPVRChannel > & channel)
Update this channel tag with the data of the given channel tag.
Parameters
channel The new channel data.
Returns
True if something changed, false otherwise.
References IconPath(), IsUserSetHidden(), IsUserSetIcon(), IsUserSetName(), m_bChanged, m_clientChannelNumber, m_critSection, m_iClientEncryptionSystem, m_strChannelName, m_strClientChannelName, m_strMimeType, SetArchive(), SetChannelName(), SetClientID(), SetClientProviderUid(), SetHidden(), SetIconPath(), and UpdateEncryptionName().
Friends And Related Symbol Documentation
CPVRDatabase
friend class CPVRDatabase friend
Member Data Documentation
IMAGE_OWNER_PATTERN
const std::string CPVRChannel::IMAGE_OWNER_PATTERN = "pvrchannel_{}" static
Referenced by PVR::CPVRChannelGroup::CleanupCachedImages().
m_bChanged
bool PVR::CPVRChannel::m_bChanged private
Initial value:
=
      false
true if anything in this entry was changed that needs to be persisted
Referenced by CreateEPG(), IsChanged(), Persist(), Persisted(), SetArchive(), SetChannelID(), SetChannelName(), SetClientID(), SetClientProviderUid(), SetDateTimeAdded(), SetEPGEnabled(), SetEPGScraper(), SetHidden(), SetIconPath(), SetLocked(), and UpdateFromClient().
m_bEPGEnabled
bool PVR::CPVRChannel::m_bEPGEnabled = false private
don't use an EPG for this channel if set to false
Referenced by EPGEnabled(), GetEPG(), and SetEPGEnabled().
m_bHasArchive
bool PVR::CPVRChannel::m_bHasArchive = false private
< the radio rds data, if available for the channel. true if this channel supports archive
Referenced by HasArchive(), Serialize(), and SetArchive().
m_bIsHidden
bool PVR::CPVRChannel::m_bIsHidden = false private
true if this channel is hidden, false if not
Referenced by GetEPG(), IsHidden(), Serialize(), and SetHidden().
m_bIsLocked
bool PVR::CPVRChannel::m_bIsLocked = false private
true if channel is locked, false if not
Referenced by IsLocked(), Serialize(), and SetLocked().
m_bIsRadio
bool PVR::CPVRChannel::m_bIsRadio = false private
true if this channel is a radio channel, false if not
Referenced by IsRadio(), operator==(), and Serialize().
m_bIsUserSetHidden
bool PVR::CPVRChannel::m_bIsUserSetHidden = false private
true if user set the hidden flag via GUI, false if not
Referenced by IsUserSetHidden(), and SetHidden().
m_bIsUserSetIcon
bool PVR::CPVRChannel::m_bIsUserSetIcon = false private
true if user set the icon via GUI, false if not
Referenced by IsUserSetIcon(), and SetIconPath().
m_bIsUserSetName
bool PVR::CPVRChannel::m_bIsUserSetName = false private
true if user set the channel name via GUI, false if not
Referenced by IsUserSetName(), and SetChannelName().
m_clientChannelNumber
CPVRChannelNumber PVR::CPVRChannel::m_clientChannelNumber private
the channel number on the client
Referenced by ClientChannelNumber(), SetChannelName(), and UpdateFromClient().
m_critSection
CCriticalSection PVR::CPVRChannel::m_critSection mutable private
Referenced by ChannelID(), ChannelName(), ClientChannelName(), ClientChannelNumber(), ClientIconPath(), ClientID(), CreateEPG(), DateTimeAdded(), EncryptionName(), EncryptionSystem(), EPGEnabled(), EpgID(), EPGScraper(), GetEPG(), GetRadioRDSInfoTag(), HasArchive(), HasClientProvider(), IconPath(), IsChanged(), IsEncrypted(), IsHidden(), IsLocked(), IsNew(), IsUserSetHidden(), IsUserSetIcon(), IsUserSetName(), LastWatched(), LastWatchedGroupId(), Lock(), MimeType(), Persist(), Persisted(), ResetEPG(), SetArchive(), SetChannelID(), SetChannelName(), SetClientID(), SetClientProviderUid(), SetDateTimeAdded(), SetEPGEnabled(), SetEPGScraper(), SetHidden(), SetIconPath(), SetLastWatched(), SetLocked(), SetRadioRDSInfoTag(), ToSortable(), Unlock(), UpdateEncryptionName(), and UpdateFromClient().
m_dateTimeAdded
CDateTime PVR::CPVRChannel::m_dateTimeAdded private
the date and time the channel was added to the TV datebase
Referenced by DateTimeAdded(), Serialize(), SetDateTimeAdded(), and ToSortable().
m_epg
std::shared_ptr<CPVREpg> PVR::CPVRChannel::m_epg private
Referenced by CreateEPG(), GetEPG(), ResetEPG(), SetEPGEnabled(), SetEPGScraper(), and SetHidden().
m_iChannelId
int PVR::CPVRChannel::m_iChannelId = -1 private
the identifier given to this channel by the TV database
Referenced by ChannelID(), IsNew(), Persist(), Serialize(), and SetChannelID().
m_iClientEncryptionSystem
int PVR::CPVRChannel::m_iClientEncryptionSystem private
Initial value:
=
      -1
the encryption system used by this channel. 0 for FreeToAir, -1 for unknown
Referenced by EncryptionSystem(), IsEncrypted(), UpdateEncryptionName(), and UpdateFromClient().
m_iClientId
int PVR::CPVRChannel::m_iClientId private
Initial value:
=
      PVR_CLIENT_INVALID_UID
the identifier of the client that serves this channel
Referenced by CanRecord(), ClientID(), GetDefaultProvider(), GetProvider(), operator==(), Serialize(), SetClientID(), StorageId(), and ToSortable().
m_iClientOrder
int PVR::CPVRChannel::m_iClientOrder = 0 private
the order from this channels group member
Referenced by ClientOrder().
m_iClientProviderUid
int PVR::CPVRChannel::m_iClientProviderUid private
Initial value:
=
      PVR_PROVIDER_INVALID_UID
the unique id for this provider from the client
Referenced by ClientProviderUid(), GetProvider(), HasClientProvider(), SetClientProviderUid(), and ToSortable().
m_iconPath
CPVRCachedImage PVR::CPVRChannel::m_iconPath private
the path to the icon for this channel
Referenced by ClientIconPath(), IconPath(), and SetIconPath().
m_iEpgId
int PVR::CPVRChannel::m_iEpgId = -1 private
the id of the EPG for this channel
Referenced by CreateEPG(), and EpgID().
m_iLastWatched
time_t PVR::CPVRChannel::m_iLastWatched = 0 private
last time channel has been watched
Referenced by LastWatched(), Serialize(), SetLastWatched(), and ToSortable().
m_iUniqueId
int PVR::CPVRChannel::m_iUniqueId = -1 private
the unique identifier for this channel
Referenced by CPVRChannel(), operator==(), Serialize(), StorageId(), and UniqueID().
m_lastWatchedGroupId
int PVR::CPVRChannel::m_lastWatchedGroupId private
Initial value:
{
      -1}
the id of the channel group the channel was watched from the last time
Referenced by LastWatchedGroupId(), and SetLastWatched().
m_rdsTag
std::shared_ptr<CPVRRadioRDSInfoTag> PVR::CPVRChannel::m_rdsTag private
Referenced by GetRadioRDSInfoTag(), and SetRadioRDSInfoTag().
m_strChannelName
std::string PVR::CPVRChannel::m_strChannelName private
the name for this channel used by Kodi
Referenced by ChannelName(), CPVRChannel(), CreateEPG(), GetEpgTags(), Persist(), Serialize(), SetChannelName(), ToSortable(), and UpdateFromClient().
m_strClientChannelName
std::string PVR::CPVRChannel::m_strClientChannelName private
the name of this channel on the client
Referenced by ClientChannelName(), and UpdateFromClient().
m_strClientEncryptionName
std::string PVR::CPVRChannel::m_strClientEncryptionName private
the name of the encryption system used by this channel
Referenced by EncryptionName(), and UpdateEncryptionName().
m_strEPGScraper
std::string PVR::CPVRChannel::m_strEPGScraper private
Initial value:
=
      "client"
the name of the scraper to be used for this channel
Referenced by CreateEPG(), EPGScraper(), and SetEPGScraper().
m_strMimeType
std::string PVR::CPVRChannel::m_strMimeType private
the stream input type based mime type, see https://www.iana.org/assignments/media-types/media-types.xhtml#video
Referenced by MimeType(), and UpdateFromClient().
The documentation for this class was generated from the following files:
PVRChannel.h
PVRChannel.cpp