Kodi Documentation: class PVRSettingKeyValuePair
class PVRSettingKeyValuePair
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General
Key-value pair of two ints
To hold a pair of two ints.
Modules
Value Help
Classes
class kodi::addon::PVRSettingKeyValuePair
Functions
kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair ()=default
Default class constructor.
kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair (unsigned int key, int value)
Class constructor with integrated value set.
kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair (unsigned int key, const std::string &value)
Class constructor with integrated value set.
kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair (unsigned int key, PVR_SETTING_TYPE eType, int intValue, const std::string &stringValue)
Class constructor with integrated value set.
void kodi::addon::PVRSettingKeyValuePair::SetKey (unsigned int key)
To set with the key.
unsigned kodi::addon::PVRSettingKeyValuePair::GetKey () const
To get with the key.
void kodi::addon::PVRSettingKeyValuePair::SetType (PVR_SETTING_TYPE eType)
required
This key value pair's type.
PVR_SETTING_TYPE kodi::addon::PVRSettingKeyValuePair::GetType () const
To get with SetType changed values.
void kodi::addon::PVRSettingKeyValuePair::SetIntValue (int value)
To set with the value.
int kodi::addon::PVRSettingKeyValuePair::GetIntValue () const
To get with the value.
void kodi::addon::PVRSettingKeyValuePair::SetStringValue (const std::string &value)
To set with the value.
std::string kodi::addon::PVRSettingKeyValuePair::GetStringValue () const
To get with the value.
Detailed Description
Key-value pair of two ints
To hold a pair of two ints.
The following table contains values that can be set with class PVRSettingKeyValuePair :
Name Type Set call Get call
Key unsigned int SetKey GetKey
| Type | PVR_SETTING_TYPE | SetType | GetType | required to set | Int Value | int | SetIntValue | GetIntValue | String Value | std::string | SetStringValue | GetStringValue
Function Documentation
GetIntValue()
int kodi::addon::PVRSettingKeyValuePair::GetIntValue () const inline
To get with the value.
References PVR_SETTING_KEY_VALUE_PAIR::iValue, and kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >::m_cStructure.
GetKey()
unsigned kodi::addon::PVRSettingKeyValuePair::GetKey () const inline
To get with the key.
References PVR_SETTING_KEY_VALUE_PAIR::iKey, and kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >::m_cStructure.
GetStringValue()
std::string kodi::addon::PVRSettingKeyValuePair::GetStringValue () const inline
To get with the value.
References kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >::m_cStructure, and PVR_SETTING_KEY_VALUE_PAIR::strValue.
GetType()
PVR_SETTING_TYPE kodi::addon::PVRSettingKeyValuePair::GetType () const inline
To get with SetType changed values.
References PVR_SETTING_KEY_VALUE_PAIR::eType, and kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >::m_cStructure.
PVRSettingKeyValuePair() [1/4]
kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair () default
Default class constructor.
PVRSettingKeyValuePair() [2/4]
kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair (unsigned int key, const std::string & value) inline
Class constructor with integrated value set.
Parameters
[in] key The key
[in] value The value
References kodi::addon::PVRSettingKeyValuePair::SetKey(), kodi::addon::PVRSettingKeyValuePair::SetStringValue(), kodi::addon::PVRSettingKeyValuePair::SetType(), and value.
PVRSettingKeyValuePair() [3/4]
kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair (unsigned int key, int value) inline
Class constructor with integrated value set.
Parameters
[in] key The key
[in] value The value
References kodi::addon::PVRSettingKeyValuePair::SetIntValue(), kodi::addon::PVRSettingKeyValuePair::SetKey(), kodi::addon::PVRSettingKeyValuePair::SetType(), and value.
PVRSettingKeyValuePair() [4/4]
kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair (unsigned int key, PVR_SETTING_TYPE eType, int intValue, const std::string & stringValue) inline
Class constructor with integrated value set.
Parameters
[in] key The key
[in] eType The type
[in] intValue The int value
[in] stringValue The string value
References kodi::addon::PVRSettingKeyValuePair::SetIntValue(), kodi::addon::PVRSettingKeyValuePair::SetKey(), kodi::addon::PVRSettingKeyValuePair::SetStringValue(), and kodi::addon::PVRSettingKeyValuePair::SetType().
SetIntValue()
void kodi::addon::PVRSettingKeyValuePair::SetIntValue (int value) inline
To set with the value.
References PVR_SETTING_KEY_VALUE_PAIR::iValue, kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >::m_cStructure, and value.
Referenced by kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair(), and kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair().
SetKey()
void kodi::addon::PVRSettingKeyValuePair::SetKey (unsigned int key) inline
To set with the key.
References PVR_SETTING_KEY_VALUE_PAIR::iKey, and kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >::m_cStructure.
Referenced by kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair(), kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair(), and kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair().
SetStringValue()
void kodi::addon::PVRSettingKeyValuePair::SetStringValue (const std::string & value) inline
To set with the value.
References kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >::m_cStructure, kodi::addon::ReallocAndCopyString(), PVR_SETTING_KEY_VALUE_PAIR::strValue, and value.
Referenced by kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair(), and kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair().
SetType()
void kodi::addon::PVRSettingKeyValuePair::SetType (PVR_SETTING_TYPE eType) inline
required
This key value pair's type.
References PVR_SETTING_KEY_VALUE_PAIR::eType, and kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >::m_cStructure.
Referenced by kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair(), kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair(), and kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair().