Kodi Documentation: PVR::CGUIPVRChannelGroupsSelector Class Reference
PVR::CGUIPVRChannelGroupsSelector Class Reference
Public Member Functions
virtual ~CGUIPVRChannelGroupsSelector ()=default
bool Initialize (CGUIWindow *parent, bool bRadio)
bool HasFocus () const
std::shared_ptr< CPVRChannelGroup > GetSelectedChannelGroup () const
bool SelectChannelGroup (const std::shared_ptr< CPVRChannelGroup > &newGroup)
Private Attributes
CGUIControl * m_control = nullptr
std::vector< std::shared_ptr< CPVRChannelGroup > > m_channelGroups
Constructor & Destructor Documentation
~CGUIPVRChannelGroupsSelector()
virtual PVR::CGUIPVRChannelGroupsSelector::~CGUIPVRChannelGroupsSelector () virtual default
Member Function Documentation
GetSelectedChannelGroup()
std::shared_ptr< CPVRChannelGroup > CGUIPVRChannelGroupsSelector::GetSelectedChannelGroup () const
References CONTROL_LSTCHANNELGROUPS, CGUIControl::GetID(), CGUIMessage::GetParam1(), GUI_MSG_ITEM_SELECTED, m_channelGroups, m_control, and CGUIControl::OnMessage().
HasFocus()
bool CGUIPVRChannelGroupsSelector::HasFocus () const
References CGUIControl::HasFocus(), and m_control.
Initialize()
bool CGUIPVRChannelGroupsSelector::Initialize (CGUIWindow * parent, bool bRadio)
References PVR::CPVRManager::ChannelGroups(), CONTROL_LSTCHANNELGROUPS, PVR::CPVRGUIDirectory::GetChannelGroupsDirectory(), CGUIControlLookup::GetControl(), CGUIControl::GetID(), CServiceBroker::GetPVRManager(), GUI_MSG_LABEL_BIND, CGUIControl::IsContainer(), m_channelGroups, m_control, and CGUIControl::OnMessage().
SelectChannelGroup()
bool CGUIPVRChannelGroupsSelector::SelectChannelGroup (const std::shared_ptr< CPVRChannelGroup > & newGroup)
References CONTROL_LSTCHANNELGROUPS, CGUIControl::GetID(), GUI_MSG_ITEM_SELECT, m_channelGroups, m_control, and CGUIControl::OnMessage().
Member Data Documentation
m_channelGroups
std::vector<std::shared_ptr<CPVRChannelGroup> > PVR::CGUIPVRChannelGroupsSelector::m_channelGroups private
Referenced by GetSelectedChannelGroup(), Initialize(), and SelectChannelGroup().
m_control
CGUIControl* PVR::CGUIPVRChannelGroupsSelector::m_control = nullptr private
Referenced by GetSelectedChannelGroup(), HasFocus(), Initialize(), and SelectChannelGroup().
The documentation for this class was generated from the following file:
GUIWindowPVRBase.cpp