Kodi Documentation: CZeroconfBrowser::ZeroconfService Class Reference
CZeroconfBrowser::ZeroconfService Class Reference
#include <ZeroconfBrowser.h>
Public Types
typedef std::map< std::string, std::string > tTxtRecordMap
Public Member Functions
ZeroconfService ()=default
ZeroconfService (const std::string &fcr_name, const std::string &fcr_type, const std::string &fcr_domain)
void SetName (const std::string &fcr_name)
const std::string & GetName () const
void SetType (const std::string &fcr_type)
const std::string & GetType () const
void SetDomain (const std::string &fcr_domain)
const std::string & GetDomain () const
void SetIP (const std::string &fcr_ip)
const std::string & GetIP () const
void SetHostname (const std::string &fcr_hostname)
const std::string & GetHostname () const
void SetPort (int f_port)
int GetPort () const
void SetTxtRecords (const tTxtRecordMap &txt_records)
const tTxtRecordMap & GetTxtRecords () const
Static Public Member Functions
static std::string toPath (const ZeroconfService &fcr_service)
static ZeroconfService fromPath (const std::string &fcr_path)
Private Attributes
std::string m_name
std::string m_type
std::string m_domain
std::string m_ip
int m_port = 0
std::string m_hostname
tTxtRecordMap m_txtrecords_map
Member Typedef Documentation
tTxtRecordMap
typedef std::map<std::string, std::string> CZeroconfBrowser::ZeroconfService::tTxtRecordMap
Constructor & Destructor Documentation
ZeroconfService() [1/2]
CZeroconfBrowser::ZeroconfService::ZeroconfService () default
ZeroconfService() [2/2]
CZeroconfBrowser::ZeroconfService::ZeroconfService (const std::string & fcr_name, const std::string & fcr_type, const std::string & fcr_domain)
References SetType().
Member Function Documentation
fromPath()
CZeroconfBrowser::ZeroconfService CZeroconfBrowser::ZeroconfService::fromPath (const std::string & fcr_path) static
Referenced by XFILE::CZeroconfDirectory::GetDirectory().
GetDomain()
const std::string & CZeroconfBrowser::ZeroconfService::GetDomain () const inline
References m_domain.
Referenced by CZeroconfBrowserDarwin::BrowserCallback(), CZeroconfBrowserMDNS::BrowserCallback(), CZeroconfBrowserMDNS::doResolveService(), CZeroconfBrowserDarwin::doResolveService(), CZeroconfBrowserAndroidDiscover::onServiceFound(), operator<(), operator<<(), and operator==().
GetHostname()
const std::string & CZeroconfBrowser::ZeroconfService::GetHostname () const inline
References m_hostname.
Referenced by CZeroconfBrowserMDNS::doResolveService().
GetIP()
const std::string & CZeroconfBrowser::ZeroconfService::GetIP () const inline
References m_ip.
Referenced by CZeroconfBrowserMDNS::doResolveService(), CZeroconfBrowserAvahi::doResolveService(), CZeroconfBrowserAndroid::doResolveService(), and XFILE::CZeroconfDirectory::GetDirectory().
GetName()
const std::string & CZeroconfBrowser::ZeroconfService::GetName () const inline
References m_name.
Referenced by CZeroconfBrowserDarwin::BrowserCallback(), CZeroconfBrowserMDNS::BrowserCallback(), CZeroconfBrowserMDNS::doResolveService(), CZeroconfBrowserDarwin::doResolveService(), CZeroconfBrowserAndroid::doResolveService(), XFILE::CZeroconfDirectory::GetDirectory(), CZeroconfBrowserAndroidDiscover::onServiceFound(), operator<(), operator<<(), and operator==().
GetPort()
int CZeroconfBrowser::ZeroconfService::GetPort () const inline
References m_port.
Referenced by XFILE::CZeroconfDirectory::GetDirectory().
GetTxtRecords()
const tTxtRecordMap & CZeroconfBrowser::ZeroconfService::GetTxtRecords () const inline
References m_txtrecords_map.
Referenced by GetDirectoryFromTxtRecords().
GetType()
const std::string & CZeroconfBrowser::ZeroconfService::GetType () const inline
References m_type.
Referenced by CZeroconfBrowserDarwin::BrowserCallback(), CZeroconfBrowserMDNS::BrowserCallback(), CZeroconfBrowserMDNS::doResolveService(), CZeroconfBrowserDarwin::doResolveService(), CZeroconfBrowserAndroid::doResolveService(), XFILE::CZeroconfDirectory::GetDirectory(), CZeroconfBrowserAndroidDiscover::onServiceFound(), operator<(), operator<<(), and operator==().
SetDomain()
void CZeroconfBrowser::ZeroconfService::SetDomain (const std::string & fcr_domain)
SetHostname()
void CZeroconfBrowser::ZeroconfService::SetHostname (const std::string & fcr_hostname)
Referenced by CZeroconfBrowserAndroid::doResolveService(), and CZeroconfBrowserMDNS::ResolveCallback().
SetIP()
void CZeroconfBrowser::ZeroconfService::SetIP (const std::string & fcr_ip)
access methods needed during resolve
Referenced by CZeroconfBrowserMDNS::doResolveService(), CZeroconfBrowserDarwin::doResolveService(), CZeroconfBrowserAndroid::doResolveService(), CZeroconfBrowserMDNS::GetAddrInfoCallback(), and CZeroconfBrowserAvahi::resolveCallback().
SetName()
void CZeroconfBrowser::ZeroconfService::SetName (const std::string & fcr_name)
general access methods
SetPort()
void CZeroconfBrowser::ZeroconfService::SetPort (int f_port)
Referenced by CZeroconfBrowserDarwin::doResolveService(), CZeroconfBrowserAndroid::doResolveService(), CZeroconfBrowserAvahi::resolveCallback(), and CZeroconfBrowserMDNS::ResolveCallback().
SetTxtRecords()
void CZeroconfBrowser::ZeroconfService::SetTxtRecords (const tTxtRecordMap & txt_records)
References CLog::Log(), and LOGDEBUG.
Referenced by CZeroconfBrowserDarwin::doResolveService(), CZeroconfBrowserAndroid::doResolveService(), CZeroconfBrowserAvahi::resolveCallback(), and CZeroconfBrowserMDNS::ResolveCallback().
SetType()
void CZeroconfBrowser::ZeroconfService::SetType (const std::string & fcr_type)
Referenced by ZeroconfService().
toPath()
std::string CZeroconfBrowser::ZeroconfService::toPath (const ZeroconfService & fcr_service) static
easy conversion to string and back (used in czeronfdiretory to store this service)
References m_domain, m_name, and m_type.
Referenced by XFILE::CZeroconfDirectory::GetDirectory().
Member Data Documentation
m_domain
std::string CZeroconfBrowser::ZeroconfService::m_domain private
Referenced by GetDomain(), and toPath().
m_hostname
std::string CZeroconfBrowser::ZeroconfService::m_hostname private
Referenced by GetHostname().
m_ip
std::string CZeroconfBrowser::ZeroconfService::m_ip private
Referenced by GetIP().
m_name
std::string CZeroconfBrowser::ZeroconfService::m_name private
Referenced by GetName(), and toPath().
m_port
int CZeroconfBrowser::ZeroconfService::m_port = 0 private
Referenced by GetPort().
m_txtrecords_map
tTxtRecordMap CZeroconfBrowser::ZeroconfService::m_txtrecords_map private
Referenced by GetTxtRecords().
m_type
std::string CZeroconfBrowser::ZeroconfService::m_type private
Referenced by GetType(), and toPath().
The documentation for this class was generated from the following files:
ZeroconfBrowser.h
ZeroconfBrowser.cpp