Kodi Documentation: URIUtils Class Reference
URIUtils Class Reference
#include <URIUtils.h>
Static Public Member Functions
static void RegisterAdvancedSettings (const CAdvancedSettings &advancedSettings)
static void UnregisterAdvancedSettings ()
static std::string GetDirectory (const std::string &strFilePath)
static std::string GetFileName (const CURL &url)
static std::string GetFileName (const std::string &strFileNameAndPath)
static std::string GetFileOrFolderName (const std::string &path)
static std::string GetExtension (const CURL &url)
static std::string GetExtension (const std::string &strFileName)
static bool HasPluginPath (const CFileItem &item)
Check if the CFileItem has a plugin path.
static bool HasExtension (const std::string &strFileName)
Check if there is a file extension.
static bool HasExtension (const std::string &strFileName, const std::string &strExtensions)
Check if filename have any of the listed extensions.
static bool HasExtension (const CURL &url, const std::string &strExtensions)
static void RemoveExtension (std::string &strFileName)
static std::string ReplaceExtension (const std::string &strFile, const std::string &strNewExtension)
static void Split (const std::string &strFileNameAndPath, std::string &strPath, std::string &strFileName)
static std::vector< std::string > SplitPath (const std::string &strPath)
static void GetCommonPath (std::string &strParent, const std::string &strPath)
static std::string GetParentPath (const std::string &strPath)
static bool GetParentPath (const std::string &strPath, std::string &strParent)
static std::string GetBasePath (const std::string &strPath)
Retrieve the base path, accounting for stacks and files in rars.
static std::string ChangeBasePath (const std::string &fromPath, const std::string &fromFile, const std::string &toPath, const bool &bAddPath=true)
static CURL SubstitutePath (const CURL &url, bool reverse=false)
static std::string SubstitutePath (const std::string &strPath, bool reverse=false)
static bool IsProtocol (const std::string &url, const std::string &type)
Check whether a URL is a given URL scheme. Comparison is case-insensitive as per RFC1738.
static bool PathHasParent (std::string path, std::string parent, bool translate=false)
Check whether a path has a given parent. Comparison is case-sensitive. Use IsProtocol() to compare the protocol portion only.
static bool PathEquals (std::string path1, std::string path2, bool ignoreTrailingSlash=false, bool ignoreURLOptions=false)
Check whether a path equals another path. Comparison is case-sensitive.
static bool IsAddonsPath (const std::string &strFile)
static bool IsSourcesPath (const std::string &strFile)
static bool IsCDDA (const std::string &strFile)
static bool IsDAV (const std::string &strFile)
static bool IsDOSPath (const std::string &path)
static bool IsDVD (const std::string &strFile)
static bool IsFTP (const std::string &strFile)
static bool IsHTTP (const std::string &strFile, bool bTranslate=false)
static bool IsUDP (const std::string &strFile)
static bool IsTCP (const std::string &strFile)
static bool IsHD (const std::string &strFileName)
static bool IsInArchive (const std::string &strFile)
static bool IsInRAR (const std::string &strFile)
static bool IsInternetStream (const std::string &path, bool bStrictCheck=false)
static bool IsInternetStream (const CURL &url, bool bStrictCheck=false)
static bool IsStreamedFilesystem (const std::string &strPath)
static bool IsNetworkFilesystem (const std::string &strPath)
static bool IsInAPK (const std::string &strFile)
static bool IsInZIP (const std::string &strFile)
static bool IsISO9660 (const std::string &strFile)
static bool IsLiveTV (const std::string &strFile)
static bool IsPVRRecording (const std::string &strFile)
static bool IsPVRRecordingFileOrFolder (const std::string &strFile)
static bool IsPVRTVRecordingFileOrFolder (const std::string &strFile)
static bool IsPVRRadioRecordingFileOrFolder (const std::string &strFile)
static bool IsMultiPath (const std::string &strPath)
static bool IsMusicDb (const std::string &strFile)
static bool IsNfs (const std::string &strFile)
static bool IsOnDVD (const std::string &strFile)
static bool IsOnLAN (const std::string &strFile, LanCheckMode lanCheckMode=LanCheckMode::ONLY_LOCAL_SUBNET)
static bool IsHostOnLAN (const std::string &hostName, LanCheckMode lanCheckMode=LanCheckMode::ONLY_LOCAL_SUBNET)
static bool IsPlugin (const std::string &strFile)
static bool IsScript (const std::string &strFile)
static bool IsRAR (const std::string &strFile)
static bool IsRemote (const std::string &strFile)
static bool IsSmb (const std::string &strFile)
static bool IsSpecial (const std::string &strFile)
static bool IsStack (const std::string &strFile)
static bool IsFavourite (const std::string &strFile)
static bool IsUPnP (const std::string &strFile)
static bool IsURL (const std::string &strFile)
static bool IsVideoDb (const std::string &strFile)
static bool IsAPK (const std::string &strFile)
static bool IsZIP (const std::string &strFile)
static bool IsArchive (const std::string &strFile)
static bool IsDiscImage (const std::string &file)
static bool IsDiscImageStack (const std::string &file)
static bool IsBluray (const std::string &strFile)
static bool IsAndroidApp (const std::string &strFile)
static bool IsLibraryFolder (const std::string &strFile)
static bool IsLibraryContent (const std::string &strFile)
static bool IsPVR (const std::string &strFile)
static bool IsPVRChannel (const std::string &strFile)
static bool IsPVRRadioChannel (const std::string &strFile)
static bool IsPVRChannelGroup (const std::string &strFile)
static bool IsPVRGuideItem (const std::string &strFile)
static std::string AppendSlash (std::string strFolder)
static void AddSlashAtEnd (std::string &strFolder)
static bool HasSlashAtEnd (const std::string &strFile, bool checkURL=false)
static void RemoveSlashAtEnd (std::string &strFolder)
static bool CompareWithoutSlashAtEnd (const std::string &strPath1, const std::string &strPath2)
static std::string FixSlashesAndDups (const std::string &path, const char slashCharacter='/', const size_t startFrom=0)
static std::string CanonicalizePath (const std::string &path, const char slashCharacter='\\')
static CURL CreateArchivePath (const std::string &type, const CURL &archiveUrl, const std::string &pathInArchive="", const std::string &password="")
static std::string AddFileToFolder (const std::string &strFolder, const std::string &strFile)
template<typename... T>
static std::string AddFileToFolder (const std::string &strFolder, const std::string &strFile, T... args)
static bool HasParentInHostname (const CURL &url)
static bool HasEncodedHostname (const CURL &url)
static bool HasEncodedFilename (const CURL &url)
static std::string GetRealPath (const std::string &path)
Cleans up the given path by resolving "." and ".." and returns it.
static bool UpdateUrlEncoding (std::string &strFilename)
Updates the URL encoded hostname of the given path.
Static Private Member Functions
static std::string resolvePath (const std::string &path)
Static Private Attributes
static const CAdvancedSettings * m_advancedSettings = nullptr
Member Function Documentation
AddFileToFolder() [1/2]
std::string URIUtils::AddFileToFolder (const std::string & strFolder, const std::string & strFile) static
References AddFileToFolder(), AddSlashAtEnd(), CURL::Get(), CURL::GetFileName(), IsDOSPath(), IsURL(), and CURL::SetFileName().
Referenced by CGUIDialogVideoBookmarks::AddBookmark(), AddFileToFolder(), AddFileToFolder(), CDbUrl::AppendPath(), CWeatherManager::BusyInfo(), ADDON::CContextMenuAddon::CContextMenuAddon(), ChangeBasePath(), CheckFont(), CMusicDatabase::CleanupSongsByIds(), ADDON::CScraper::ClearCache(), dbiplus::SqliteDatabase::connect(), CVideoDatabase::ConstructPath(), CWeatherJob::ConstructPath(), CUtil::CopyUserDataIfNeeded(), ADDON::Interface_GUIWindow::create(), KODI::CDRIP::CCDDARipper::CreateAlbumDir(), CUtil::CreateDirectoryEx(), CDVDFactoryInputStream::CreateInputStream(), CProfileManager::CreateProfileFolders(), CVideoTagLoaderNFO::CVideoTagLoaderNFO(), CMusicDatabase::DeleteCDDBInfo(), CProfileManager::DeleteProfile(), CBlurayCallback::dir_open(), XFILE::Directorize(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CVideoDatabase::DumpToDummyFiles(), CAddonManagementEvent::Execute(), XFILE::CFavouritesDirectory::Exists(), XFILE::CMultiPathFile::Exists(), CVideoDatabase::ExportActorThumbs(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs(), CBlurayCallback::file_open(), CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), ADDON::CAddonInfoBuilder::Generate(), XFILE::GenerateMainCategoryListing(), CScraperUrl::Get(), ADDON::Interface_Base::get_temp_path(), CMusicDatabase::GetArtistPath(), CProfileManager::GetBookmarksThumbFolder(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), CTextureCache::GetCachedPath(), CDDB::Xcddb::GetCacheFile(), CProfileManager::GetCDDBFolder(), CProfileManager::GetDatabaseFolder(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CResourceDirectory::GetDirectory(), XFILE::CSpecialProtocolDirectory::GetDirectory(), XFILE::CPosixDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), CTVOSNSUserDefaults::GetDirectoryContents(), CMediaManager::GetDiscInfo(), ADDON::CAddonDll::GetDllPath(), ADDON::CWebinterface::GetEntryPoint(), CMusicDatabase::GetFileItemFromDataset(), XFILE::CStackDirectory::GetFirstStackedFile(), KODI::ART::GetFolderThumb(), ADDON::CResource::GetFullPath(), ADDON::CImageResource::GetFullPath(), KODI::VIDEO::CVideoInfoScanner::GetImage(), CLangInfo::GetLanguageInfoPath(), CLangInfo::GetLanguagePath(), TestWebServer::GetLastModifiedOfTestFile(), CProfileManager::GetLibraryFolder(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkArtistHandler::GetLocalArt(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkActorHandler::GetLocalArt(), KODI::ART::GetLocalArt(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), KODI::VIDEO::CVideoInfoScanner::GetMovieSetInfoFolder(), XFILE::CLibraryDirectory::GetNode(), KODI::VIDEO::UTILS::GetOpticalMediaPath(), KODI::GAME::CGameClientInGameSaves::GetPath(), CWIN32Util::GetProfilePath(), CGUIDialogProfileSettings::GetProfilePath(), CProfileManager::GetProfileUserDataFolder(), CUtil::GetQualifiedFilename(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), ADDON::CResource::GetResourcePath(), XFILE::CBlurayDirectory::GetRoot(), CVideoDatabase::GetSafeFile(), CProfileManager::GetSavestatesFolder(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), ADDON::CSkinInfo::GetSkinPath(), ADDON::CSkinInfo::GetSkinPaths(), CUtil::GetSkinThemes(), CMusicDatabase::GetSongFromDataset(), GetSoundSkinPath(), CMediaSourceSettings::GetSourcesFile(), KODI::UTILS::FONT::FONTPATH::GetSystemFontPath(), KODI::ART::GetTBNFile(), CGUITextureManager::GetTexturePath(), CProfileManager::GetThumbnailsFolder(), TestHTTPDirectory::GetUrl(), TestWebServer::GetUrl(), TestHTTPDirectory::GetUrlOfTestFile(), TestWebServer::GetUrlOfTestFile(), CTVOSFileUtils::GetUserHomeDirectory(), XFILE::CBlurayDirectory::GetUserPlaylists(), CProfileManager::GetVideoThumbFolder(), CUtil::GetVobSubIdxFromSub(), CInfoScanner::HasNoMedia(), ADDON::CImageResource::HasXbt(), KODI::GAME::CControllerLayout::ImagePath(), CVideoDatabase::ImportFromXML(), CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), CSettingsComponent::InitDirectoriesWin32(), CLog::Initialize(), KODI::GAME::CPortManager::Initialize(), KODI::GAME::CGameClient::Initialize(), ADDON::CAddonSettings::InitializeFromOldSettingFileWithSource(), ADDON::CAddon::InitSettings(), CFilesystemInstaller::InstallToFilesystem(), KODI::VIDEO::IsProtectedBlurayDisc(), ADDON::CAddonType::LibPath(), ADDON::CAddon::LibPath(), CGUIAudioManager::Load(), CGUIColorManager::Load(), KODI::KEYMAP::CIRTranslator::Load(), CWeatherJob::LoadLocalizedToken(), CProfileManager::LoadProfile(), CApplicationSkinHandling::LoadSkin(), LoadStr2Mem(), GUIFontManager::LoadTTF(), GUIFontManager::LoadUserFonts(), CGUIAudioManager::LoadWindowSound(), CMusicDatabase::LookupCDDBInfo(), CUtil::MakeLegalPath(), KODI::RETRO::CSavestateDatabase::MakePath(), KODI::RETRO::CSavestateDatabase::MakeSavestatePath(), CUtil::MusicPlaylistsLocation(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), CGUIDialogSmartPlaylistEditor::OnOK(), CGUIWindowMusicPlaylistEditor::OnSavePlaylist(), DebugLogSharingPresenter::OnSettingAction(), CProfileManager::OnSettingsLoaded(), XFILE::CMultiPathFile::Open(), CTextureBundleXBT::OpenBundle(), ADDON::CContextMenuAddon::ParseMenu(), ADDON::CAddonInfoBuilder::ParseXML(), CFavouritesService::Persist(), CExternalPlayer::Process(), CPictureThumbLoader::ProcessFoldersAndArchives(), CXBMCTestUtils::ReferenceFilePath(), CFavouritesService::ReInit(), XFILE::CPosixDirectory::RemoveRecursive(), CFileUtils::RenameFile(), CHTTPWebinterfaceHandler::ResolveAddon(), CCueDocument::ResolvePath(), KODI::CDRIP::CCDDARipper::RipCD(), KODI::CDRIP::CCDDARipper::RipTrack(), CGUIWindowMusicPlayList::SavePlayList(), CGUIWindowVideoPlaylist::SavePlayList(), KODI::ADDONS::CExtsMimeSupportList::ScanAddonProperties(), anonymous_namespace{GUIBuiltins.cpp}::Screenshot(), CLangInfo::SetLanguage(), CXBMCTestUtils::SetReferenceFileBasePath(), CGUIDialogSubtitles::SetService(), ADDON::CSkinInfo::SettingOptionsSkinColorsFiller(), KODI::SUBTITLES::CSubtitlesSettings::SettingOptionsSubtitleFontsFiller(), CTVOSTopShelf::SetTopShelfItems(), CGUIDialogProfileSettings::ShowForProfile(), UPNP::CUPnP::StartRenderer(), UPNP::CUPnP::StartServer(), XFILE::CMultiPathFile::Stat(), CScreenShot::TakeScreenshot(), KODI::PLATFORM::FILESYSTEM::temp_file_path(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_P(), TEST_P(), TEST_P(), CSpecialProtocol::TranslatePath(), translatePathIntoKey(), CUtil::TranslateSpecialSource(), CFilesystemInstaller::UnInstallFromFilesystem(), CFanart::Unpack(), CUtil::VideoPlaylistsLocation(), XBMCAddon::xbmcgui::WindowXML::WindowXML(), win32_exception::write_minidump(), and win32_exception::write_stacktrace().
AddFileToFolder() [2/2]
template<typename... T> static std::string URIUtils::AddFileToFolder (const std::string & strFolder, const std::string & strFile, T... args) inline static
References AddFileToFolder().
AddSlashAtEnd()
void URIUtils::AddSlashAtEnd (std::string & strFolder) static
References AddSlashAtEnd(), CURL::Get(), CURL::GetFileName(), HasSlashAtEnd(), IsDOSPath(), IsURL(), and CURL::SetFileName().
Referenced by AddFileToFolder(), CMusicDatabase::AddPath(), CVideoDatabase::AddPath(), AddSlashAtEnd(), XFILE::CMultiPathDirectory::AddToMultiPath(), AppendSlash(), CGUIDialogSubtitleSettings::BrowseForSubtitle(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), ADDON::CScraper::ClearCache(), KODI::CDRIP::CCDDARipper::CreateAlbumDir(), CUtil::CreateDirectoryEx(), XFILE::Directorize(), CGUIMultiImage::CMultiImageJob::DoWork(), XFILE::CFTPDirectory::Exists(), XFILE::CDirectory::Exists(), CMusicDatabase::ExportToXML(), Extract(), DllLoaderContainer::FindModule(), GetCommonPath(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CFTPDirectory::GetDirectory(), XFILE::CISO9660Directory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMusicFileDirectory::GetDirectory(), XFILE::CNFSDirectory::GetDirectory(), XFILE::CUDFDirectory::GetDirectory(), XFILE::CUPnPDirectory::GetDirectory(), XFILE::CAPKDirectory::GetDirectory(), XFILE::CPosixDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), XFILE::CWinLibraryDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), XFILE::CNFSDirectory::GetDirectoryFromExportList(), GetDirectoryFromTxtRecords(), CLangInfo::GetLanguagePath(), KODI::VIDEO::CVideoInfoScanner::GetMovieSetInfoFolder(), GetParentPath(), CVideoDatabase::GetPathId(), CWIN32Util::GetProfilePath(), XFILE::CNFSDirectory::GetServerList(), CMusicDatabase::GetSongByFileName(), CMusicDatabase::GetSongIDFromPath(), CMusicDatabase::GetSongsByPath(), CMediaSourceSettings::GetSource(), CMusicDatabase::GetSourceFromPath(), CMusicDatabase::GetSourcesBySong(), CVideoDatabase::GetSubPaths(), CTextureBundleXBT::GetTexturesFromPath(), CViewDatabase::GetViewState(), CGUIDialogFileBrowser::GoParentFolder(), CVideoDatabase::ImportFromXML(), CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), CDirectoryHistory::IsInHistory(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CApplicationSkinHandling::LoadSkin(), CUtil::MakeLegalPath(), CGUIWindowMusicNav::ManageInfoProvider(), UPNP::CMediaBrowser::OnContainerChanged(), CGUIWindowFileManager::OnNewFolder(), CGUIDialogInfoProviderSettings::OnSettingAction(), CGUIDialogLibExportSettings::OnSettingAction(), CAdvancedSettings::ParseSettingsFile(), PathHasParent(), CMusicDatabase::RemoveSongsFromPath(), XFILE::CNFSDirectory::ResolveSymlink(), CHTTPWebinterfaceHandler::ResolveUrl(), CUtil::ScanForExternalSubtitles(), SetFile(), CFileItem::SetFromVideoInfoTag(), CGUIMediaWindow::SetHistoryForPath(), SetImage(), SetPath(), CViewDatabase::SetViewState(), CGUIDialogProfileSettings::ShowForProfile(), XFILE::CAPKFile::Stat(), TEST(), TEST_F(), TEST_P(), and TEST_P().
AppendSlash()
std::string URIUtils::AppendSlash (std::string strFolder) static
References AddSlashAtEnd().
Referenced by KODI::PLAYLIST::CPlayListXSPF::Load(), and KODI::PLATFORM::FILESYSTEM::temp_directory_path().
CanonicalizePath()
std::string URIUtils::CanonicalizePath (const std::string & path, const char slashCharacter = '\\') static
Convert path to form without duplicated slashes and without relative directories Strip duplicated slashes Resolve and remove relative directories ("/../" and "/./") Will ignore slashes with other direction than specified Will not resolve path starting from relative directory
Warning
Don't use with "protocol://path"-style URLs
Parameters
path string to process
slashCharacter character to use as directory delimiter
Returns
transformed path
Referenced by CWIN32Util::ConvertPathToWin32Form(), and CWIN32Util::ConvertPathToWin32Form().
ChangeBasePath()
std::string URIUtils::ChangeBasePath (const std::string & fromPath, const std::string & fromFile, const std::string & toPath, const bool & bAddPath = true) static
References AddFileToFolder(), HasEncodedFilename(), IsDOSPath(), URLDecodePath(), and URLEncodePath().
Referenced by CFileOperationJob::DoProcess(), CGUIDialogSubtitles::OnDownloadComplete(), and SubstitutePath().
CompareWithoutSlashAtEnd()
bool URIUtils::CompareWithoutSlashAtEnd (const std::string & strPath1, const std::string & strPath2) static
References RemoveSlashAtEnd().
Referenced by CGUIDialogContextMenu::GetShare(), CMediaManager::HasLocation(), CGUIDialogFileBrowser::OnPopupMenu(), CMediaManager::RemoveLocation(), CMediaManager::SetLocationPath(), and CGUIMediaWindow::Update().
CreateArchivePath()
CURL URIUtils::CreateArchivePath (const std::string & type, const CURL & archiveUrl, const std::string & pathInArchive = "", const std::string & password = "") static
References CURL::Get(), CURL::SetFileName(), CURL::SetHostName(), CURL::SetProtocol(), and CURL::SetUserName().
Referenced by XFILE::CFileDirectoryFactory::Create(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CZipManager::ExtractArchive(), XFILE::CXbtDirectory::GetDirectory(), XFILE::CZipDirectory::GetDirectory(), CUtil::GetVobSubSubFromIdx(), ADDON::CImageResource::HasXbt(), ADDON::CAddonInstaller::InstallFromZip(), CApplication::OnApplicationMessage(), CGUIWindowPictures::OnClick(), CGUIWindowFileManager::OnClick(), CPictureThumbLoader::ProcessFoldersAndArchives(), CUtil::ScanArchiveForAssociatedItems(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and CFilesystemInstaller::UnpackArchive().
FixSlashesAndDups()
std::string URIUtils::FixSlashesAndDups (const std::string & path, const char slashCharacter = '/', const size_t startFrom = 0) static
Referenced by CWIN32Util::ConvertPathToWin32Form(), CWIN32Util::ConvertPathToWin32Form(), XFILE::CWinLibraryFile::GetFile(), and XFILE::CWinLibraryDirectory::GetFolder().
GetBasePath()
std::string URIUtils::GetBasePath (const std::string & strPath) static
Retrieve the base path, accounting for stacks and files in rars.
Parameters
strPath path.
Returns
the folder that contains the item.
References GetDirectory(), GetFileName(), XFILE::CStackDirectory::GetFirstStackedFile(), GetParentPath(), IsInRAR(), IsStack(), and RemoveSlashAtEnd().
Referenced by KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CUtil::GetVideoBasePathAndFileName(), and CGUIPassword::IsMediaFileUnlocked().
GetCommonPath()
void URIUtils::GetCommonPath (std::string & strParent, const std::string & strPath) static
References AddSlashAtEnd(), GetDirectory(), and HasSlashAtEnd().
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), CMusicDatabase::GetAlbumPath(), CMusicDatabase::GetOldArtistPath(), GetParentPath(), and TEST_F().
GetDirectory()
std::string URIUtils::GetDirectory (const std::string & strFilePath) static
Referenced by XFILE::CDirectoryCache::AddFile(), KODI::VIDEO::CVideoInfoScanner::AddLocalItemArtwork(), XBMCAddon::xbmcgui::WindowXML::AllocResources(), ADDON::CGUIAddonWindow::AllocResources(), CGUIDialogSubtitleSettings::BrowseForSubtitle(), CVideoDatabase::CleanDatabase(), CMusicDatabase::CleanupSongsByIds(), XFILE::CDirectoryCache::ClearFile(), CGUIDialogCMSSettings::Cms3dLutsFiller(), XFILE::CFile::Copy(), CGUIDialogVideoInfo::DeleteVideoItem(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), CMediaLibraryEvent::Execute(), CPythonInvoker::execute(), CMusicDatabase::ExportToXML(), Extract(), XFILE::CDirectoryCache::FileExists(), CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), GetBasePath(), GetCommonPath(), CTVOSNSUserDefaults::GetDirectoryContents(), CUtil::GetDirectoryName(), JSONRPC::CFileOperations::GetFileDetails(), KODI::ART::GetFolderThumb(), KODI::VIDEO::CVideoInfoScanner::GetImage(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), CUtil::GetNextFilename(), GetParentPath(), CVideoDatabase::GetScraperForPath(), CVideoDatabase::GetSourcePath(), KODI::ART::GetTBNFile(), CTempFile::getTempFileDirectory(), XFILE::CVideoDatabaseFile::GetType(), CFileItem::GetUserMusicThumb(), CUtil::GetVobSubIdxFromSub(), KODI::VIDEO::UTILS::HasItemVideoDbInformation(), KODI::GAME::CControllerLayout::ImagePath(), XFILE::IDirectory::IsAllowed(), KODI::PLAYLIST::CPlayList::Load(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIWindowPictures::OnInitWindow(), CGUIWindowVideoBase::OnItemInfo(), KODI::CDRIP::CCDDARipper::OnJobComplete(), CGUIMediaWindow::OnMessage(), CGUIWindowVideoBase::OnSearchItemFound(), CDVDInputStreamBluray::Open(), CInputStreamAddon::Open(), ADDON::CAddonInfoBuilder::ParseXML(), CFileUtils::RenameFile(), CCueDocument::ResolvePath(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), ADDON::CAddon::SaveSettings(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_P(), and CVideoLibraryRefreshingJob::Work().
GetExtension() [1/2]
std::string URIUtils::GetExtension (const CURL & url) static
References GetExtension(), and CURL::GetFileName().
Referenced by CDVDFileInfo::AddExternalSubtitleToDetails(), CVideoPlayer::AddSubtitleFile(), UPNP::BuildObject(), CFileExtensionProvider::CanOperateExtension(), CHTTPImageTransformationHandler::CHTTPImageTransformationHandler(), CUtil::CleanString(), CMusicDatabase::CleanupSongsByIds(), KODI::RETRO::CCheevos::ConsoleID(), KODI::PLAYLIST::CPlayListFactory::Create(), XFILE::CFileDirectoryFactory::Create(), CWebServer::CreateFileDownloadResponse(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), ADDON::CScraper::CScraper(), dll_findfirst64i32(), CFileOperationJob::DoProcess(), CTextureCache::Export(), GetExtension(), GetExtension(), CUtil::GetExternalStreamDetailsFromFilename(), CMusicDatabase::GetFileItemFromDataset(), KODI::GAME::CGameUtils::GetGameClients(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CScriptInvocationManager::GetLanguageInvoker(), CMime::GetMimeType(), UPNP::GetMimeType(), UPNP::GetMimeType(), CGUIInfoManager::GetMultiInfoItemLabel(), CUtil::GetNextFilename(), CUtil::GetSkinThemes(), CVideoDatabase::GetStreamDetails(), KODI::GAME::CGameUtils::HasGameExtension(), CScriptInvocationManager::HasLanguageInvoker(), ADDON::CImageResource::IsAllowed(), KODI::VIDEO::IsBlurayPlaylist(), IsRAR(), CPictureInfoTag::Load(), KODI::PLAYLIST::CPlayListM3U::Load(), CTagLoaderTagLib::Load(), KODI::ADDONS::CAudioDecoder::Load(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIWindowMusicPlaylistEditor::OnSavePlaylist(), UPNP::PopulateObjectFromTag(), CDVDFileInfo::ProcessExternalSubtitles(), CEdl::ReadBeyondTV(), ReplaceExtension(), KODI::PLAYLIST::CPlayListM3U::Save(), CUtil::ScanArchiveForAssociatedItems(), CHTTPFileHandler::SetFile(), CFileItem::SetFromSong(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), TEST_F(), and XFILE::CMusicDatabaseFile::TranslateUrl().
GetExtension() [2/2]
std::string URIUtils::GetExtension (const std::string & strFileName) static
References GetExtension(), CURL::GetFileName(), and IsURL().
GetFileName() [1/2]
std::string URIUtils::GetFileName (const CURL & url) static
References CURL::GetFileName(), and GetFileName().
Referenced by MUSIC_INFO::CMusicInfoScanner::AddLocalArtwork(), KODI::VIDEO::CVideoInfoScanner::AddLocalItemArtwork(), CGUIDialogVideoManagerExtras::AddVideoExtra(), UPNP::CUPnPServer::BuildSafeResourceUri(), KODI::RETRO::CReversiblePlayback::CommitSavestate(), CMusicDatabase::DeleteCDDBInfo(), CUtil::DeleteDirectoryCache(), CGUIDialogVideoInfo::DeleteVideoItem(), CFileOperationJob::DoProcess(), KODI::VIDEO::CVideoInfoScanner::DoScan(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), CHTTPPythonWsgiInvoker::executeScript(), XFILE::CFileAndroidApp::Exists(), CVideoDatabase::ExportToXML(), KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs(), JSONRPC::CFileOperations::FillFileItem(), JSONRPC::CAudioLibrary::FillFileItem(), JSONRPC::CVideoLibrary::FillFileItem(), JSONRPC::CFileItemHandler::FillFileItemList(), CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), GetBasePath(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMusicFileDirectory::GetDirectory(), XFILE::CTVOSDirectory::GetDirectory(), GetDirectoryFromTxtRecords(), CUtil::GetDirectoryName(), CUDevProvider::GetDisks(), ADDON::CAddonDll::GetDllPath(), CPosixMountProvider::GetDrives(), CUtil::GetDVDIfoTitle(), CUtil::GetExternalStreamDetailsFromFilename(), KODI::GUILIB::GUIINFO::GetFileInfoLabelValueFromPath(), GetFileName(), GetFileName(), CURL::GetFileNameWithoutPath(), ADDON::CAddonInfo::GetKnownInstanceIds(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CWeatherGUIInfo::GetLabel(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::GetLocalArt(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), CFileItem::GetLocalMetadataPath(), CLabelFormatter::GetMaskContent(), CFileItem::GetMovieName(), CGUIInfoManager::GetMultiInfoItemLabel(), KODI::GAME::CGameClientInGameSaves::GetPath(), XFILE::CSmartPlaylistDirectory::GetPlaylistByName(), CAndroidStorageProvider::GetRemovableDrives(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), CUtil::GetSkinThemes(), CMusicDatabase::GetSongByFileName(), CMusicDatabase::GetSongIDFromPath(), XFILE::CStackDirectory::GetStackedTitlePath(), KODI::ART::GetTBNFile(), CUtil::GetTitleFromPath(), CUtil::GetVideoBasePathAndFileName(), XFILE::CVideoDatabaseFile::GetVideoTag(), CUtil::GetVobSubIdxFromSub(), CUtil::GetVobSubSubFromIdx(), CHTTPPythonHandler::HandleRequest(), KODI::CDRIP::CEncoderFFmpeg::Init(), XFILE::IDirectory::IsAllowed(), KODI::VIDEO::IsBDFile(), KODI::VIDEO::IsDVDFile(), XBMCAddon::xbmcvfs::listdir(), XBMCAddon::xbmc::PlayList::load(), KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListPLS::Load(), KODI::PLAYLIST::CPlayListURL::Load(), KODI::PLAYLIST::CPlayListXML::Load(), CApplicationSkinHandling::LoadCustomWindows(), KODI::PLAYLIST::CPlayListWPL::LoadData(), KODI::KEYMAP::CIRTranslator::LoadIRMap(), CFileItem::LoadMusicTag(), GUIFontManager::LoadTTF(), KODI::RETRO::CSavestateDatabase::MakePath(), CGUIMediaWindow::OnClick(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSmartPlaylistEditor::OnOK(), CGUIWindowMusicPlaylistEditor::OnSavePlaylist(), CDVDInputStreamBluray::Open(), CDVDInputStreamNavigator::Open(), CDVDSubtitleParserSami::Open(), XFILE::CZipFile::Open(), XFILE::CFileAndroidApp::Open(), CGUIVisualisationControl::Process(), CUDevProvider::PumpDriveChangeEvents(), CFileUtils::RenameFile(), CCueDocument::ResolvePath(), CHTTPWebinterfaceHandler::ResolveUrl(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), RunScript(), CUtil::ScanArchiveForAssociatedItems(), CUtil::ScanPathsForAssociatedItems(), PVR::CPVRGUIChannelIconUpdater::SearchAndUpdateMissingChannelIcons(), UPNP::CUPnPServer::ServeFile(), SetFile(), CGUIWindowWeather::SetProperties(), CTVOSTopShelf::SetTopShelfItems(), CGUIDialogTextViewer::ShowForFile(), CGUIDialogSimpleMenu::ShowPlaySelection(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_P(), XFILE::CVideoDatabaseFile::TranslatePath(), XFILE::CMusicDatabaseFile::TranslateUrl(), CGUIWindowVideoNav::UpdateButtons(), and CGUIDialogProfileSettings::UpdateProfileImage().
GetFileName() [2/2]
std::string URIUtils::GetFileName (const std::string & strFileNameAndPath) static
References CURL::GetFileName(), GetFileName(), and IsURL().
GetFileOrFolderName()
std::string URIUtils::GetFileOrFolderName (const std::string & path) static
Referenced by KODI::VIDEO::IsVideoExtrasFolder().
GetParentPath() [1/2]
std::string URIUtils::GetParentPath (const std::string & strPath) static
References GetParentPath().
Referenced by KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::AddItemPathToFileBrowserSources(), CGUIDialogMusicInfo::AddItemPathToFileBrowserSources(), CVideoDatabase::AddPath(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), XBMCAddon::xbmcgui::WindowXML::AllocResources(), ADDON::CGUIAddonWindow::AllocResources(), CGUIDialogVideoManager::AppendItemFolderToFileBrowserSources(), XFILE::CWinLibraryDirectory::Create(), KODI::VIDEO::CVideoInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), CVideoDatabase::ExportToXML(), KODI::VIDEO::UTILS::FindTrailer(), CFileItem::GetBaseMoviePath(), GetBasePath(), KODI::GUILIB::GUIINFO::GetFileInfoLabelValueFromPath(), KODI::ART::GetFolderThumb(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), CFileItem::GetLocalMetadataPath(), CGUIInfoManager::GetMultiInfoItemLabel(), CMusicDatabase::GetOldArtistPath(), GetParentPath(), GetParentPath(), CVideoDatabase::GetPathId(), CUtil::GetQualifiedFilename(), CVideoDatabase::GetScraperForPath(), CVideoDatabase::GetSourcePath(), XFILE::CStackDirectory::GetStackedTitlePath(), KODI::ART::GetTBNFile(), CVideoDatabase::GetTvShowId(), ADDON::Interface_GUIDialogFileBrowser::GetVECShares(), CUtil::GetVideoBasePathAndFileName(), CUtil::GetVobSubIdxFromSub(), GroupUtils::Group(), CVideoDatabase::InvalidatePathHash(), KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListPLS::Load(), KODI::PLAYLIST::CPlayListURL::Load(), KODI::PLAYLIST::CPlayListXML::Load(), KODI::PLAYLIST::CPlayListXSPF::Load(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadRecordingFileOrFolderItem(), UPNP::CUPnPServer::OnBrowseMetadata(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowVideoBase::OnSearchItemFound(), CGUIDialogNetworkSetup::OnServerBrowse(), CDVDInputStreamNavigator::Open(), XFILE::CWinLibraryFile::OpenIntenal(), MUSIC_UTILS::PlayItem(), KODI::VIDEO::UTILS::PlayItem(), PVR::CPVRGUIActionsPlayback::PlayRecording(), MUSIC_INFO::CMusicInfoScanner::RetrieveLocalArt(), anonymous_namespace{VideoDatabase.cpp}::RewriteVideoVersionURL(), CGUIMediaWindow::SetHistoryForPath(), CGUIWindowVideoBase::ShowInfo(), CGUIDialogSimpleMenu::ShowPlaySelection(), CVideoDatabase::SplitPath(), TEST_F(), CGUIDialogFileBrowser::Update(), CGUIWindowFileManager::Update(), CVideoDatabase::UpdateTables(), and CVideoLibraryRefreshingJob::Work().
GetParentPath() [2/2]
bool URIUtils::GetParentPath (const std::string & strPath, std::string & strParent) static
Todo:
Make a new python call to get the plugin content type and remove this temporary hack
References AddSlashAtEnd(), CURL::Get(), GetCommonPath(), XFILE::CStackDirectory::GetDirectory(), GetDirectory(), CURL::GetFileName(), XFILE::CMultiPathDirectory::GetFirstPath(), CURL::GetHostName(), CURL::GetOptions(), GetParentPath(), CURL::HasOption(), HasParentInHostname(), HasSlashAtEnd(), CURL::IsProtocol(), CFileItem::m_strDVDLabel, CURL::SetFileName(), CURL::SetHostName(), CURL::SetOptions(), CFileItem::SetPath(), and CFileItemList::Size().
GetRealPath()
std::string URIUtils::GetRealPath (const std::string & path) static
Cleans up the given path by resolving "." and ".." and returns it.
This methods goes through the given path and removes any "." (as it states "this directory") and resolves any ".." by removing the previous directory from the path. This is done for file paths and host names (in case of VFS paths).
Parameters
path Path to be cleaned up
Returns
Actual path without any "." or ".."
References CURL::Get(), CURL::GetFileName(), CURL::GetHostName(), GetRealPath(), resolvePath(), CURL::SetFileName(), and CURL::SetHostName().
Referenced by CHTTPVfsHandler::CHTTPVfsHandler(), GetRealPath(), KODI::PLAYLIST::CPlayListXSPF::Load(), CFileUtils::RemoteAccessAllowed(), CHTTPWebinterfaceHandler::ResolveAddon(), and TEST_F().
HasEncodedFilename()
bool URIUtils::HasEncodedFilename (const CURL & url) static
References CURL::GetTranslatedProtocol().
Referenced by ChangeBasePath(), XFILE::CStackDirectory::GetStackedTitlePath(), CFileItemList::StackFiles(), and TEST_F().
HasEncodedHostname()
bool URIUtils::HasEncodedHostname (const CURL & url) static
References HasParentInHostname(), and CURL::IsProtocol().
Referenced by CURL::GetWithoutFilename(), CURL::GetWithoutUserDetails(), CURL::Parse(), TEST_F(), and UpdateUrlEncoding().
HasExtension() [1/3]
bool URIUtils::HasExtension (const CURL & url, const std::string & strExtensions) static
References CURL::GetFileName(), and HasExtension().
HasExtension() [2/3]
bool URIUtils::HasExtension (const std::string & strFileName) static
Check if there is a file extension.
Parameters
strFileName Path or URL to check
Returns
true if strFileName have an extension.
Note
Returns false when strFileName is empty.
See also
GetExtension
References CURL::GetFileName(), HasExtension(), and IsURL().
Referenced by CGUIDialogSubtitleSettings::BrowseForSubtitle(), CFileOperationJob::DoProcess(), ADDON::CRepository::FetchIndex(), CVideoTagLoaderNFO::FindNFO(), CUtil::FindVobSubPair(), ADDON::CAddonBuilder::Generate(), XFILE::CLibraryDirectory::GetDirectory(), anonymous_namespace{UPnPInternal.cpp}::GetImageDLNAProfile(), UPNP::CUPnPRenderer::GetMetadata(), HasExtension(), HasExtension(), HasExtension(), IsAliasShortcut(), XFILE::IDirectory::IsAllowed(), ADDON::CUISoundsResource::IsAllowed(), IsAPK(), IsArchive(), KODI::MUSIC::IsAudio(), CFileItem::IsCBR(), CFileItem::IsCBZ(), KODI::MUSIC::IsCUESheet(), IsDiscImage(), KODI::VIDEO::IsDiscStub(), KODI::VIDEO::TAGS::CVideoTagExtractionHelper::IsExtractionSupportedFor(), KODI::MUSIC::IsLyrics(), CFileItem::IsNFO(), IsPathToMedia(), IsPathToThumbnail(), CUtil::IsPicture(), KODI::PLAYLIST::CPlayListFactory::IsPlaylist(), KODI::PLAYLIST::CPlayListFactory::IsPlaylist(), CFileItem::IsPythonScript(), CFileItem::IsRSS(), KODI::PLAYLIST::IsSmartPlayList(), KODI::VIDEO::IsSubtitle(), KODI::UTILS::FONT::IsSupportedFontExtension(), CFileItem::IsType(), XFILE::CFileCDDA::IsValidFile(), KODI::VIDEO::IsVideo(), CUtil::IsVobSub(), IsZIP(), CGUIColorManager::Load(), GUIFontManager::LoadFonts(), CTexture::LoadFromFileInternal(), CGUIWindowVideoBase::OnItemInfo(), CGUIWindowSlideShow::OnLoadPic(), CGUIDialogSmartPlaylistEditor::OnOK(), CDVDInputStreamBluray::Open(), CDVDSubtitleStream::Open(), CVideoPlayer::OpenInputStream(), KODI::PLAYLIST::CSmartPlaylist::readNameFromPath(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::CDRIP::CCDDARipper::RipTrack(), RunScript(), CUtil::ScanArchiveForAssociatedItems(), CUtil::ScanForExternalSubtitles(), ADDON::CSkinInfo::SettingOptionsSkinColorsFiller(), TEST_F(), XFILE::CMusicDatabaseFile::TranslateUrl(), and CGUIWindowFileManager::Update().
HasExtension() [3/3]
bool URIUtils::HasExtension (const std::string & strFileName, const std::string & strExtensions) static
Check if filename have any of the listed extensions.
Parameters
strFileName Path or URL to check
strExtensions List of '.' prefixed lowercase extensions separated with '|'
Returns
true if strFileName have any one of the extensions.
Note
The check is case insensitive for strFileName, but requires strExtensions to be lowercase. Returns false when strFileName or strExtensions is empty.
See also
GetExtension
References CURL::GetFileName(), HasExtension(), and IsURL().
HasParentInHostname()
bool URIUtils::HasParentInHostname (const CURL & url) static
References CFileExtensionProvider::EncodedHostName(), CServiceBroker::GetFileExtensionProvider(), CURL::GetProtocol(), CServiceBroker::IsAddonInterfaceUp(), and CURL::IsProtocol().
Referenced by GetParentPath(), CUtil::GetTitleFromPath(), CURL::GetWithoutUserDetails(), HasEncodedHostname(), IsDAV(), IsFTP(), IsHD(), IsHTTP(), IsNfs(), IsOnLAN(), IsRemote(), IsSmb(), and TEST_F().
HasPluginPath()
bool URIUtils::HasPluginPath (const CFileItem & item) static
Check if the CFileItem has a plugin path.
Parameters
item The CFileItem.
Returns
true if there is a plugin path, false otherwise.
References CFileItem::GetDynPath(), CFileItem::GetPath(), and IsPlugin().
Referenced by KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), and CApplication::PlayMedia().
HasSlashAtEnd()
bool URIUtils::HasSlashAtEnd (const std::string & strFile, bool checkURL = false) static
References CURL::GetFileName(), HasSlashAtEnd(), and IsURL().
Referenced by CMusicDatabase::AddPath(), AddSlashAtEnd(), CFileItem::CFileItem(), XFILE::CFileDirectoryFactory::Create(), CFileUtils::DeleteItem(), CGUIDialogVideoInfo::DeleteVideoItem(), CBlurayCallback::dir_open(), XFILE::Directorize(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), XBMCAddon::xbmcvfs::exists(), CMusicDatabase::ExportToXML(), GetCommonPath(), XFILE::CHTTPDirectory::GetDirectory(), CUtil::GetMatchingSource(), GetParentPath(), CMusicDatabase::GetSongsByPath(), CMusicDatabase::GetSourceFromPath(), CMusicDatabase::GetSourcesBySong(), CProfileManager::GetUserDataItem(), CURL::GetWithoutOptions(), HasSlashAtEnd(), ADDON::CImageResource::IsAllowed(), XBMCAddon::xbmcvfs::listdir(), CUtil::MakeLegalPath(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoBase::OnSearchItemFound(), XFILE::CWinLibraryFile::OpenIntenal(), CFavouritesURL::Parse(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), RemoveSlashAtEnd(), CMusicDatabase::RemoveSongsFromPath(), XFILE::CAPKFile::Stat(), XFILE::CWinLibraryFile::Stat(), SubstitutePath(), and TEST_F().
IsAddonsPath()
bool URIUtils::IsAddonsPath (const std::string & strFile) static
References CURL::IsProtocol().
Referenced by CFileItem::IsAddonsPath(), IsRemote(), and TEST_F().
IsAndroidApp()
bool URIUtils::IsAndroidApp (const std::string & strFile) static
References IsProtocol().
Referenced by JSONRPC::CFavouritesOperations::AddFavourite(), CFileItem::IsAndroidApp(), and IsRemote().
IsAPK()
bool URIUtils::IsAPK (const std::string & strFile) static
References HasExtension().
Referenced by CFileItem::IsAPK().
IsArchive()
bool URIUtils::IsArchive (const std::string & strFile) static
References HasExtension().
Referenced by KODI::ART::FillInDefaultIcon(), and KODI::GAME::CGUIWindowGames::OnClick().
IsBluray()
bool URIUtils::IsBluray (const std::string & strFile) static
References IsProtocol().
Referenced by CDVDFileInfo::CanExtract(), CSaveFileState::DoWork(), KODI::VIDEO::UTILS::FindTrailer(), KODI::ART::GetLocalFanart(), CFileItem::IsBluray(), CApplicationPlayerCallback::OnPlayBackStarted(), XFILE::CFile::Open(), and TEST_F().
IsCDDA()
bool URIUtils::IsCDDA (const std::string & strFile) static
References IsProtocol().
Referenced by CUtil::GetDVDDriveIcon(), KODI::MUSIC::IsCDDA(), IsRemote(), and TEST_F().
IsDAV()
bool URIUtils::IsDAV (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetHostName(), HasParentInHostname(), IsDAV(), IsProtocol(), IsSpecial(), IsStack(), and CSpecialProtocol::TranslatePath().
Referenced by IsDAV(), and CUtil::SupportsWriteFileOperations().
IsDiscImage()
bool URIUtils::IsDiscImage (const std::string & file) static
References HasExtension().
Referenced by CFileItem::IsDiscImage(), and IsDiscImageStack().
IsDiscImageStack()
bool URIUtils::IsDiscImageStack (const std::string & file) static
References XFILE::CStackDirectory::GetFirstStackedFile(), IsDiscImage(), and IsStack().
Referenced by CVideoDatabase::GetBookMarksForFile(), CGUIWindowVideoBase::GetContextButtons(), CVideoDatabase::GetResumePoint(), KODI::VIDEO::UTILS::GetStackPartResumeInformation(), CApplicationStackHelper::InitializeStack(), and CGUIWindowVideoBase::OnPlayStackPart().
IsDOSPath()
bool URIUtils::IsDOSPath (const std::string & path) static
Referenced by AddFileToFolder(), AddSlashAtEnd(), ChangeBasePath(), XFILE::CVirtualDirectory::IsSource(), TEST_F(), and CUtil::ValidatePath().
IsDVD()
bool URIUtils::IsDVD (const std::string & strFile) static
References IsOnDVD(), IsProtocol(), and KODI::PLATFORM::WINDOWS::ToW().
Referenced by CMediaSource::FromNameAndPaths(), CUtil::GetDVDDriveIcon(), CUtil::GetFileAndProtocol(), CGUIDialogContextMenu::GetShare(), CMediaManager::IsDiscInDrive(), CFileItem::IsDVD(), KODI::VIDEO::IsVideo(), XFILE::CFile::Open(), XFILE::CFile::ShouldUseStreamBuffer(), and TEST_F().
IsFavourite()
bool URIUtils::IsFavourite (const std::string & strFile) static
References IsProtocol().
Referenced by CFileItem::IsFavourite().
IsFTP()
bool URIUtils::IsFTP (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetHostName(), HasParentInHostname(), IsFTP(), IsProtocol(), IsSpecial(), IsStack(), and CSpecialProtocol::TranslatePath().
Referenced by CDVDFileInfo::CanExtract(), KODI::ART::GetLocalFanart(), CFileItem::GetUserMusicThumb(), IsFTP(), IsStreamedFilesystem(), CFileItem::SkipLocalArt(), and TEST_F().
IsHD()
bool URIUtils::IsHD (const std::string & strFileName) static
References XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetHostName(), CURL::GetProtocol(), HasParentInHostname(), IsHD(), CURL::IsProtocol(), IsSpecial(), IsStack(), and CSpecialProtocol::TranslatePath().
Referenced by CFileOperationJob::CanBeRenamed(), CGUITextureManager::CanLoad(), XFILE::CFile::Copy(), CUtil::CreateDirectoryEx(), CMediaSource::FromNameAndPaths(), CFileItem::IsHD(), IsHD(), CUtil::MakeLegalPath(), XFILE::CFile::Open(), CEdl::ReadEditDecisionLists(), CUtil::ScanForExternalSubtitles(), CUtil::SupportsWriteFileOperations(), and TEST_F().
IsHostOnLAN()
bool URIUtils::IsHostOnLAN (const std::string & hostName, LanCheckMode lanCheckMode = LanCheckMode::ONLY_LOCAL_SUBNET) static
References addr_match(), ANY_PRIVATE_SUBNET, CNetworkBase::GetFirstConnectedInterface(), CServiceBroker::GetNetwork(), CNetworkBase::HasInterfaceForIP(), and CDNSNameCache::Lookup().
Referenced by UPNP::ResourcePrioritySort::GetPriority(), ADDON::Interface_Network::is_host_on_lan(), IsOnLAN(), and CWakeOnAccess::QueueMACDiscoveryForHost().
IsHTTP()
bool URIUtils::IsHTTP (const std::string & strFile, bool bTranslate = false) static
References XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetHostName(), CURL::GetProtocol(), CURL::GetTranslatedProtocol(), HasParentInHostname(), IsHTTP(), IsSpecial(), IsStack(), and CSpecialProtocol::TranslatePath().
Referenced by CDVDFileInfo::CanExtract(), IsHTTP(), IsStreamedFilesystem(), and CGUIDialogSubtitles::OnDownloadComplete().
IsInAPK()
bool URIUtils::IsInAPK (const std::string & strFile) static
References CURL::GetFileName(), and CURL::IsProtocol().
Referenced by XFILE::CFile::Copy(), and IsInArchive().
IsInArchive()
bool URIUtils::IsInArchive (const std::string & strFile) static
References CURL::GetFileName(), IsInAPK(), IsInRAR(), IsInZIP(), and CURL::IsProtocol().
Referenced by CHTTPVfsHandler::CHTTPVfsHandler(), CVideoDatabase::CleanDatabase(), CVideoDatabase::ConstructPath(), DllLoaderContainer::FindModule(), CUtil::FindVobSubPair(), CFileItem::GetBaseMoviePath(), CUtil::GetExternalStreamDetailsFromFilename(), KODI::GUILIB::GUIINFO::GetFileInfoLabelValueFromPath(), CFileUtils::GetModificationDate(), CUtil::GetVobSubIdxFromSub(), CUtil::IsVobSub(), CFileUtils::RemoteAccessAllowed(), and TEST_F().
IsInRAR()
bool URIUtils::IsInRAR (const std::string & strFile) static
References CURL::GetFileName(), CURL::GetHostName(), CURL::IsProtocol(), and IsRAR().
Referenced by CGUIDialogSubtitleSettings::BrowseForSubtitle(), KODI::ART::FillInDefaultIcon(), CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), GetBasePath(), KODI::ART::GetFolderThumb(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), KODI::ART::GetTBNFile(), IsInArchive(), KODI::VIDEO::CVideoGeneratedImageFileLoader::Load(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIWindowSlideShow::OnLoadPic(), CFileItemList::StackFolders(), and TEST_F().
IsInternetStream() [1/2]
bool URIUtils::IsInternetStream (const CURL & url, bool bStrictCheck = false) static
References CURL::Get(), XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetProtocol(), IsInternetStream(), CURL::IsProtocol(), and IsStreamedFilesystem().
IsInternetStream() [2/2]
bool URIUtils::IsInternetStream (const std::string & path, bool bStrictCheck = false) static
References IsInternetStream().
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), ADDON::Interface_Filesystem::is_internet_stream(), KODI::NETWORK::IsInternetStream(), IsInternetStream(), IsInternetStream(), XFILE::CFile::Open(), CEdl::ReadEditDecisionLists(), CGUIDialogVideoInfo::SetMovie(), and TEST_F().
IsInZIP()
bool URIUtils::IsInZIP (const std::string & strFile) static
References CURL::GetFileName(), CURL::GetHostName(), CURL::IsProtocol(), and IsZIP().
Referenced by CGUIDialogSubtitleSettings::BrowseForSubtitle(), KODI::ART::FillInDefaultIcon(), KODI::VIDEO::UTILS::FindTrailer(), KODI::ART::GetFolderThumb(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), KODI::ART::GetTBNFile(), IsInArchive(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIWindowSlideShow::OnLoadPic(), CFileItemList::StackFolders(), and TEST_F().
IsISO9660()
bool URIUtils::IsISO9660 (const std::string & strFile) static
References IsProtocol().
Referenced by CMediaSource::FromNameAndPaths(), CUtil::GetDVDDriveIcon(), CFileItem::IsISO9660(), IsRemote(), and TEST_F().
IsLibraryContent()
bool URIUtils::IsLibraryContent (const std::string & strFile) static
References IsProtocol().
Referenced by CGUIWindowMusicNav::GetContextButtons().
IsLibraryFolder()
bool URIUtils::IsLibraryFolder (const std::string & strFile) static
References CURL::IsProtocol().
Referenced by CFileItem::IsLibraryFolder(), and IsRemote().
IsLiveTV()
bool URIUtils::IsLiveTV (const std::string & strFile) static
References RemoveSlashAtEnd().
Referenced by CGUIViewState::AddLiveTVSources(), CFileItem::IsLiveTV(), CGUIDialogMediaSource::OnMediaSourceChanged(), and TEST_F().
IsMultiPath()
bool URIUtils::IsMultiPath (const std::string & strPath) static
References IsProtocol().
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), CFileItem::Exists(), CMediaSource::FromNameAndPaths(), CVideoDatabase::GetItemsForPath(), CVideoDatabase::GetPlayCounts(), CVideoDatabase::GetScraperForPath(), CVideoDatabase::GetSourcePath(), CFileItem::IsMultiPath(), IsOnLAN(), IsRemote(), CGUIWindowVideoBase::LoadVideoInfo(), CUtil::MakeLegalPath(), CVideoDatabase::RemoveContentForPath(), CFileUtils::RenameFile(), CVideoDatabase::SetScraperForPath(), KODI::VIDEO::CVideoInfoScanner::Start(), CUtil::SupportsWriteFileOperations(), and TEST_F().
IsMusicDb()
bool URIUtils::IsMusicDb (const std::string & strFile) static
References IsProtocol().
Referenced by UPNP::CUPnPServer::BuildResponse(), CFavouritesService::GetFavourite(), anonymous_namespace{MusicUtils.cpp}::GetMusicDbItemPath(), KODI::MUSIC::IsMusicDb(), IsRemote(), UPNP::CUPnPServer::OnBrowseMetadata(), and TEST_F().
IsNetworkFilesystem()
bool URIUtils::IsNetworkFilesystem (const std::string & strPath) static
References XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetProtocol(), IsNetworkFilesystem(), IsNfs(), CURL::IsProtocol(), IsSmb(), and IsStreamedFilesystem().
Referenced by IsNetworkFilesystem(), and XFILE::CFile::Open().
IsNfs()
bool URIUtils::IsNfs (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetHostName(), HasParentInHostname(), IsNfs(), IsProtocol(), IsSpecial(), IsStack(), and CSpecialProtocol::TranslatePath().
Referenced by CUtil::CreateDirectoryEx(), IsNetworkFilesystem(), CFileItem::IsNfs(), IsNfs(), CUtil::MakeLegalPath(), CUtil::SupportsWriteFileOperations(), and TEST_F().
IsOnDVD()
bool URIUtils::IsOnDVD (const std::string & strFile) static
References IsProtocol(), CLog::Log(), LOGDEBUG, and KODI::PLATFORM::WINDOWS::ToW().
Referenced by CVideoDatabase::CleanDatabase(), CUtil::GetMatchingSource(), IsDVD(), XFILE::CVirtualDirectory::IsInSource(), CFileItem::IsOnDVD(), and TEST_F().
IsOnLAN()
bool URIUtils::IsOnLAN (const std::string & strFile, LanCheckMode lanCheckMode = LanCheckMode::ONLY_LOCAL_SUBNET) static
References XFILE::CMultiPathDirectory::GetFirstPath(), XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetHostName(), HasParentInHostname(), IsHostOnLAN(), IsMultiPath(), IsOnLAN(), IsPlugin(), IsRemote(), IsSpecial(), IsStack(), IsUPnP(), and CSpecialProtocol::TranslatePath().
Referenced by CDVDFileInfo::CanExtract(), CAudioDecoder::Create(), ADDON::Interface_Filesystem::is_on_lan(), IsOnLAN(), CEdl::ReadEditDecisionLists(), CUtil::ScanForExternalSubtitles(), CFileItemList::StackFolders(), and TEST_F().
IsPlugin()
bool URIUtils::IsPlugin (const std::string & strFile) static
References CURL::IsProtocol().
Referenced by CGUIDialogSubtitleSettings::BrowseForSubtitle(), CDVDFileInfo::CanExtract(), CVideoDatabase::CleanDatabase(), CVideoDatabase::ConstructPath(), KODI::VIDEO::CVideoInfoScanner::DoScan(), CSaveFileState::DoWork(), KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs(), CVideoDatabase::GetDateAdded(), anonymous_namespace{PluginDirectory.cpp}::GetOriginalPluginPath(), CVideoDatabase::GetPlayCounts(), XFILE::CPluginDirectory::GetResolvedPluginResult(), CInfoScanner::HasNoMedia(), HasPluginPath(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), CVideoDatabase::InvalidatePathHash(), IsOnLAN(), CFileItem::IsPlugin(), IsRemote(), CGUIMediaWindow::OnInitWindow(), CFavouritesURL::Parse(), CApplication::PlayFile(), CVideoDatabase::SetPlayCount(), CVideoDatabase::SplitPath(), TEST_F(), and CVideoLibraryRefreshingJob::Work().
IsProtocol()
bool URIUtils::IsProtocol (const std::string & url, const std::string & type) static
Check whether a URL is a given URL scheme. Comparison is case-insensitive as per RFC1738.
Parameters
url a std::string path.
type a lower-case scheme name, e.g. "smb".
Returns
true if the url is of the given scheme, false otherwise.
See also
PathHasParent, PathEquals
Referenced by CGUIWindowMusicBase::CanContainFilter(), CGUIWindowVideoBase::CanContainFilter(), CFileUtils::CheckFileAccessAllowed(), IMAGE_FILES::CImageFileURL::CImageFileURL(), CDVDFactoryInputStream::CreateInputStream(), IMAGE_FILES::CImageFileURL::FromFile(), XFILE::CSourcesDirectory::GetDirectory(), CTextureCacheJob::GetImageHash(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::GetRemoteArt(), IsAndroidApp(), IsBluray(), IsCDDA(), IsDAV(), IsDVD(), IsFavourite(), IsFTP(), IsISO9660(), IsLibraryContent(), IsMultiPath(), IsMusicDb(), IsNfs(), IsOnDVD(), IsPVR(), IsPVRChannel(), IsPVRChannelGroup(), IsPVRRadioChannel(), IsSmb(), IsSpecial(), IsStack(), IsTCP(), IsUDP(), IsUPnP(), IsVideoDb(), CONTEXTMENU::CAddRemoveFavourite::IsVisible(), CONTEXTMENU::CFavouriteContextMenuAction::IsVisible(), CDirectoryProvider::OnAddonEvent(), CDirectoryProvider::OnAddonRepositoryEvent(), CGUIWindowVideoNav::OnDeleteItem(), CDirectoryProvider::OnFavouritesEvent(), CDirectoryProvider::OnPVRManagerEvent(), CDVDInputStreamBluray::Open(), CFilesystemInstaller::UnpackArchive(), and KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::UpdateEmbeddedArt().
IsPVR()
bool URIUtils::IsPVR (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), IsProtocol(), IsPVR(), and IsStack().
Referenced by CDVDFileInfo::CanExtract(), PVR::CPVRItem::GetChannel(), PVR::CPVRItem::GetEpgInfoTag(), PVR::CPVRItem::GetNextEpgInfoTag(), PVR::CPVRItem::GetRecording(), PVR::CPVRItem::GetTimerInfoTag(), CFileItem::IsPVR(), IsPVR(), and PVR::CPVRItem::IsRadio().
IsPVRChannel()
bool URIUtils::IsPVRChannel (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), PVR::CPVRChannelsPath::IsChannel(), IsProtocol(), IsPVRChannel(), and IsStack().
Referenced by CDVDFactoryInputStream::CreateInputStream(), PVR::CPVRManager::GetClient(), IsPVRChannel(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadChannelItem(), JSONRPC::CPlayerOperations::Open(), and PVR::CPVRGUIActionsPlayback::PlayMedia().
IsPVRChannelGroup()
bool URIUtils::IsPVRChannelGroup (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), PVR::CPVRChannelsPath::IsChannelGroup(), IsProtocol(), IsPVRChannelGroup(), and IsStack().
Referenced by PVR::CPVRManager::GetClient(), CFileItem::IsPVRChannelGroup(), and IsPVRChannelGroup().
IsPVRGuideItem()
bool URIUtils::IsPVRGuideItem (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), IsPVRGuideItem(), and IsStack().
Referenced by KODI::ART::FillInDefaultIcon(), IsPVRGuideItem(), and RemoveSlashAtEnd().
IsPVRRadioChannel()
bool URIUtils::IsPVRRadioChannel (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), PVR::CPVRChannelsPath::IsChannel(), IsProtocol(), IsPVRRadioChannel(), and IsStack().
Referenced by KODI::ART::FillInDefaultIcon(), IsPVRRadioChannel(), and TEST_F().
IsPVRRadioRecordingFileOrFolder()
bool URIUtils::IsPVRRadioRecordingFileOrFolder (const std::string & strFile) static
Referenced by CONTEXTMENU::CVideoBrowse::Execute(), and KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist().
IsPVRRecording()
bool URIUtils::IsPVRRecording (const std::string & strFile) static
References RemoveSlashAtEnd().
Referenced by CDVDFactoryInputStream::CreateInputStream(), PVR::CPVRManager::GetClient(), CFileItem::GetMovieName(), JSONRPC::CPlayerOperations::Open(), PVR::CPVRGUIActionsPlayback::PlayMedia(), CInputStreamPVRBase::ProvidesStreamForMetaDataExtraction(), PVR::CPVRGUIDirectory::SupportsWriteFileOperations(), and CUtil::SupportsWriteFileOperations().
IsPVRRecordingFileOrFolder()
bool URIUtils::IsPVRRecordingFileOrFolder (const std::string & strFile) static
Referenced by anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), KODI::VIDEO::UTILS::IsItemPlayable(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), and PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadRecordingFileOrFolderItem().
IsPVRTVRecordingFileOrFolder()
bool URIUtils::IsPVRTVRecordingFileOrFolder (const std::string & strFile) static
Referenced by CONTEXTMENU::CVideoBrowse::Execute(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), and KODI::VIDEO::IsVideo().
IsRAR()
bool URIUtils::IsRAR (const std::string & strFile) static
References GetExtension().
Referenced by CGUIWindowSlideShow::AddItems(), IsInRAR(), CFileItem::IsRAR(), CApplication::OnApplicationMessage(), CUtil::ScanPathsForAssociatedItems(), CGUIWindowPictures::ShowPicture(), and TEST_F().
IsRemote()
bool URIUtils::IsRemote (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetHostName(), XFILE::CMultiPathDirectory::GetPaths(), HasParentInHostname(), IsAddonsPath(), IsAndroidApp(), IsCDDA(), IsISO9660(), IsLibraryFolder(), CURL::IsLocal(), IsMultiPath(), IsMusicDb(), IsPlugin(), IsRemote(), IsSourcesPath(), IsSpecial(), IsStack(), IsVideoDb(), and CSpecialProtocol::TranslatePath().
Referenced by UPNP::BuildObject(), CDVDFileInfo::CanExtract(), CMediaSource::FromNameAndPaths(), CUtil::GetFileAndProtocol(), ADDON::Interface_Filesystem::is_remote(), IsOnLAN(), KODI::NETWORK::IsRemote(), IsRemote(), CGUIMediaWindow::OnMessage(), CGUIWindowFileManager::ShowShareErrorMessage(), CGUIMediaWindow::ShowShareErrorMessage(), and TEST_F().
IsScript()
bool URIUtils::IsScript (const std::string & strFile) static
References CURL::IsProtocol().
Referenced by JSONRPC::CFavouritesOperations::AddFavourite(), CFileItem::IsScript(), and TEST_F().
IsSmb()
bool URIUtils::IsSmb (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetHostName(), HasParentInHostname(), IsProtocol(), IsSmb(), IsSpecial(), IsStack(), and CSpecialProtocol::TranslatePath().
Referenced by CFileOperationJob::CanBeRenamed(), CUtil::CreateDirectoryEx(), IsNetworkFilesystem(), CFileItem::IsSmb(), IsSmb(), CUtil::MakeLegalPath(), CUtil::SupportsWriteFileOperations(), and TEST_F().
IsSourcesPath()
bool URIUtils::IsSourcesPath (const std::string & strFile) static
References CURL::IsProtocol().
Referenced by IsRemote(), CFileItem::IsSourcesPath(), and TEST_F().
IsSpecial()
bool URIUtils::IsSpecial (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), IsProtocol(), IsSpecial(), and IsStack().
Referenced by CGUIWindowMusicNav::GetContextButtons(), IsDAV(), IsFTP(), IsHD(), IsHTTP(), IsNfs(), IsOnLAN(), IsRemote(), IsSmb(), IsSpecial(), CGUIDialogMusicInfo::ShowFor(), TEST_F(), and CSpecialProtocol::TranslatePath().
IsStack()
bool URIUtils::IsStack (const std::string & strFile) static
References IsProtocol().
Referenced by CVideoDatabase::AddPath(), CVideoDatabase::CleanDatabase(), CVideoDatabase::ConstructPath(), CDVDFileInfo::DemuxerToStreamDetails(), CFileItem::Exists(), GetBasePath(), CGUIWindowVideoBase::GetContextButtons(), CVideoThumbLoader::GetEmbeddedThumbURL(), CDVDFileInfo::GetFileStreamDetails(), UPNP::GetMimeType(), CFileUtils::GetModificationDate(), CFileItem::GetMovieName(), CVideoDatabase::GetPathId(), CMediaSourceSettings::GetSource(), IsDAV(), IsDiscImageStack(), IsFTP(), IsHD(), IsHTTP(), IsNfs(), IsOnLAN(), IsPVR(), IsPVRChannel(), IsPVRChannelGroup(), IsPVRGuideItem(), IsPVRRadioChannel(), IsRemote(), IsSmb(), IsSpecial(), CFileItem::IsStack(), IsTCP(), IsUDP(), CUtil::MakeLegalPath(), CGUIWindowVideoBase::OnPlayStackPart(), CVideoDatabase::SplitPath(), CUtil::SupportsWriteFileOperations(), TEST_F(), and UpdateUrlEncoding().
IsStreamedFilesystem()
bool URIUtils::IsStreamedFilesystem (const std::string & strPath) static
Todo:
sftp/ssh special case has to be handled by vfs addon
References XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetProtocol(), IsFTP(), IsHTTP(), CURL::IsProtocol(), IsStreamedFilesystem(), and IsUPnP().
Referenced by IsInternetStream(), IsNetworkFilesystem(), KODI::NETWORK::IsStreamedFilesystem(), and IsStreamedFilesystem().
IsTCP()
bool URIUtils::IsTCP (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), IsProtocol(), IsStack(), and IsTCP().
Referenced by IsTCP().
IsUDP()
bool URIUtils::IsUDP (const std::string & strFile) static
References XFILE::CStackDirectory::GetFirstStackedFile(), IsProtocol(), IsStack(), and IsUDP().
Referenced by IsUDP().
IsUPnP()
bool URIUtils::IsUPnP (const std::string & strFile) static
References IsProtocol().
Referenced by CDVDFileInfo::CanExtract(), CFileOperationJob::DoProcess(), CSaveFileState::DoWork(), JSONRPC::CFileOperations::FillFileItemList(), KODI::VIDEO::UTILS::FindTrailer(), CGUIWindowVideoNav::GetContextButtons(), JSONRPC::CFileOperations::GetDirectory(), JSONRPC::CFileOperations::GetFileDetails(), KODI::ART::GetLocalFanart(), CFileItem::GetUserMusicThumb(), IsOnLAN(), IsStreamedFilesystem(), CGUIWindowVideoNav::OnContextButton(), CApplication::OnMessage(), CVideoPlayer::OpenInputStream(), CFileItem::SkipLocalArt(), TEST_F(), CVideoLibraryMarkWatchedJob::Work(), and CVideoLibraryResetResumePointJob::Work().
IsURL()
bool URIUtils::IsURL (const std::string & strFile) static
Referenced by AddFileToFolder(), AddSlashAtEnd(), UPNP::DecodeObjectId(), JSONRPC::CFileItemHandler::FillFileItemList(), GetExtension(), GetFileName(), HasExtension(), HasExtension(), HasSlashAtEnd(), ADDON::Interface_Filesystem::is_url(), CFileItem::IsURL(), RemoveExtension(), RemoveSlashAtEnd(), ReplaceExtension(), UPNP::CUPnPServer::ServeFile(), Split(), CMusicDatabase::SplitPath(), CVideoDatabase::SplitPath(), TEST_F(), and CUtil::ValidatePath().
IsVideoDb()
bool URIUtils::IsVideoDb (const std::string & strFile) static
References IsProtocol().
Referenced by UPNP::CUPnPServer::BuildResponse(), CFavouritesService::GetFavourite(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::GetVideoDbItemPath(), IsRemote(), KODI::VIDEO::IsVideoDb(), UPNP::CUPnPServer::OnBrowseMetadata(), CGUIMediaWindow::SetHistoryForPath(), CUtil::SupportsReadFileOperations(), and TEST_F().
IsZIP()
bool URIUtils::IsZIP (const std::string & strFile) static
References HasExtension().
Referenced by CGUIWindowSlideShow::AddItems(), Extract(), IsInZIP(), CFileItem::IsZIP(), CApplication::OnApplicationMessage(), CUtil::ScanPathsForAssociatedItems(), CGUIWindowPictures::ShowPicture(), and TEST_F().
PathEquals()
bool URIUtils::PathEquals (std::string path1, std::string path2, bool ignoreTrailingSlash = false, bool ignoreURLOptions = false) static
Check whether a path equals another path. Comparison is case-sensitive.
Parameters
path1 a std::string path.
path2 the second path the path should be compared against.
ignoreTrailingSlash ignore any trailing slashes in both paths
Returns
true if the paths are equal, false otherwise.
See also
IsProtocol, PathHasParent
References CURL::GetWithoutOptions(), and RemoveSlashAtEnd().
Referenced by PVR::CGUIWindowPVRTimersBase::ActionShowTimer(), CGUIViewStateAddonBrowser::CGUIViewStateAddonBrowser(), CGUIDialogSmartPlaylistEditor::EditPlaylist(), XFILE::CDirectoryCache::FileExists(), CUtil::FindVobSubPair(), PVR::CPVRRecordings::GetByPath(), CGUIWindowMusicNav::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetIcon(), PVR::CPVRTimerInfoTag::GetStatus(), CGUIMediaWindow::GoParentFolder(), CFileItem::IsPath(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible(), CUtil::IsVobSub(), CGUIMediaWindow::OnBack(), CGUIMediaWindow::OnClick(), CGUIMediaWindow::OnInitWindow(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogSmartPlaylistEditor::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIMediaWindow::SetHistoryForPath(), and CGUIMediaWindow::Update().
PathHasParent()
bool URIUtils::PathHasParent (std::string path, std::string parent, bool translate = false) static
Check whether a path has a given parent. Comparison is case-sensitive. Use IsProtocol() to compare the protocol portion only.
Parameters
path a std::string path.
parent the string the parent of the path should be compared against.
translate whether to translate any special paths into real paths
Returns
true if the path has the given parent string, false otherwise.
See also
IsProtocol, PathEquals
References AddSlashAtEnd(), and CSpecialProtocol::TranslatePath().
Referenced by CHTTPPythonHandler::CHTTPPythonHandler(), CHTTPVfsHandler::CHTTPVfsHandler(), XFILE::CDirectoryCache::ClearSubPaths(), XFILE::CResourceDirectory::GetDirectory(), XFILE::CSpecialProtocolDirectory::GetDirectory(), PVR::CGUIWindowPVRChannelsBase::GetDirectoryPath(), PVR::CGUIWindowPVRTVProviders::GetDirectoryPath(), PVR::CGUIWindowPVRRadioProviders::GetDirectoryPath(), PVR::CGUIWindowPVRRecordingsBase::GetDirectoryPath(), PVR::CGUIWindowPVRTVSearch::GetDirectoryPath(), PVR::CGUIWindowPVRRadioSearch::GetDirectoryPath(), PVR::CGUIWindowPVRTVTimerRules::GetDirectoryPath(), PVR::CGUIWindowPVRRadioTimerRules::GetDirectoryPath(), PVR::CGUIWindowPVRTVTimers::GetDirectoryPath(), PVR::CGUIWindowPVRRadioTimers::GetDirectoryPath(), CTextureCache::IsCachedImage(), XFILE::CVirtualDirectory::IsInSource(), XFILE::CPluginDirectory::IsMediaLibraryScanningAllowed(), CGUIMediaWindow::IsSameStartFolder(), CHTTPWebinterfaceHandler::ResolveAddon(), CGUIWindowFileManager::SetInitialPath(), CGUIDialogProfileSettings::ShowForProfile(), CNfsConnection::splitUrlIntoExportAndPath(), XFILE::CAPKFile::Stat(), and TEST_F().
RegisterAdvancedSettings()
void URIUtils::RegisterAdvancedSettings (const CAdvancedSettings & advancedSettings) static
References m_advancedSettings.
Referenced by CSettingsComponent::Initialize().
RemoveExtension()
void URIUtils::RemoveExtension (std::string & strFileName) static
References CURL::Get(), CServiceBroker::GetFileExtensionProvider(), CURL::GetFileName(), CFileExtensionProvider::GetMusicExtensions(), CFileExtensionProvider::GetPictureExtensions(), CFileExtensionProvider::GetSubtitleExtensions(), CFileExtensionProvider::GetVideoExtensions(), IsURL(), RemoveExtension(), and CURL::SetFileName().
Referenced by KODI::VIDEO::CVideoInfoScanner::AddLocalItemArtwork(), UPNP::BuildObject(), CUtil::CleanString(), CHTTPPythonWsgiInvoker::executeScript(), KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs(), CFileItemList::FilterCueItems(), KODI::VIDEO::UTILS::FindTrailer(), CGUIDialogVideoManagerExtras::GenerateVideoExtra(), KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetBool(), XFILE::CMusicFileDirectory::GetDirectory(), CUtil::GetExternalStreamDetailsFromFilename(), ADDON::CAddonInfo::GetKnownInstanceIds(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CWeatherGUIInfo::GetLabel(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::GetLocalArt(), KODI::ART::GetLocalFanart(), CGUIInfoManager::GetMultiInfoItemLabel(), CMusicDatabase::GetSongByFileName(), CMusicDatabase::GetSongIDFromPath(), CGUIMediaWindow::GetStartFolder(), CUtil::GetTitleFromPath(), XFILE::CVideoDatabaseFile::GetVideoTag(), CFileItem::LoadMusicTag(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIDialogMusicInfo::OnGetArt(), CGUIWindowMusicPlaylistEditor::OnSavePlaylist(), CApplicationSkinHandling::OnSettingChanged(), KODI::PLAYLIST::CSmartPlaylist::readNameFromPath(), CFileItem::RemoveExtension(), RemoveExtension(), CUtil::ScanPathsForAssociatedItems(), PVR::CPVRGUIChannelIconUpdater::SearchAndUpdateMissingChannelIcons(), CGUIWindowWeather::SetProperties(), SetTheme(), ADDON::CSkinInfo::SettingOptionsSkinColorsFiller(), ADDON::CSkinInfo::SettingOptionsSkinThemesFiller(), CFileItemList::StackFiles(), TEST_F(), XFILE::CVideoDatabaseFile::TranslatePath(), and XFILE::CMusicDatabaseFile::TranslateUrl().
RemoveSlashAtEnd()
void URIUtils::RemoveSlashAtEnd (std::string & strFolder) static
References CURL::Get(), CURL::GetFileName(), CURL::GetHostName(), HasSlashAtEnd(), IsPVRGuideItem(), IsURL(), RemoveSlashAtEnd(), and CURL::SetFileName().
Referenced by XFILE::CDirectoryCache::AddFile(), CGUIWindowSlideShow::AddItems(), XBMCAddon::xbmcgui::WindowXML::AllocResources(), ADDON::CGUIAddonWindow::AllocResources(), UPNP::CUPnPServer::BuildSafeResourceUri(), CMusicDatabase::CleanupSongsByIds(), XFILE::CDirectoryCache::ClearDirectory(), XFILE::CMusicDatabaseDirectory::ClearDirectoryCache(), XFILE::CVideoDatabaseDirectory::ClearDirectoryCache(), XFILE::CDirectoryCache::ClearFile(), CompareWithoutSlashAtEnd(), XFILE::CFile::Copy(), XFILE::CNFSDirectory::Create(), CGUIDialogVideoInfo::DeleteVideoItem(), CBlurayCallback::dir_open(), CFileOperationJob::DoProcess(), CUDisks2Provider::Eject(), CUDisksProvider::Eject(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), CPythonInvoker::execute(), XFILE::CNFSDirectory::Exists(), XFILE::CDirectoryCache::FileExists(), CVideoTagLoaderNFO::FindNFO(), GetBasePath(), PVR::CPVRGUIDirectory::GetDirectory(), XFILE::CAddonsDirectory::GetDirectory(), XFILE::CBlurayDirectory::GetDirectory(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CRSSDirectory::GetDirectory(), XFILE::CSourcesDirectory::GetDirectory(), XFILE::CZeroconfDirectory::GetDirectory(), XFILE::CAndroidAppDirectory::GetDirectory(), XFILE::CDirectoryCache::GetDirectory(), XFILE::CNFSDirectory::GetDirectoryFromExportList(), GetDirectoryFromTxtRecords(), CGUIWindowFileManager::GetDirectoryHistoryString(), CGUIMediaWindow::GetDirectoryHistoryString(), CUtil::GetDirectoryName(), CFileItemList::GetDiscFileCache(), CURL::GetFileNameWithoutPath(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), KODI::GAME::CGameClientProperties::GetLibraryPath(), CFileItem::GetLocalMetadataPath(), CFileItem::GetMovieName(), CGUIInfoManager::GetMultiInfoItemLabel(), XFILE::CLibraryDirectory::GetNode(), CTVOSFileUtils::GetOSCachesDirectory(), KODI::GAME::CGameClientProperties::GetProfileDirectory(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), KODI::ART::GetTBNFile(), CUtil::GetTitleFromPath(), anonymous_namespace{Util.cpp}::GetTrailingDiscNumberSegmentInfoFromPath(), CURL::GetWithoutOptions(), XFILE::CMultiPathDirectory::HasPath(), CSMB::Init(), PVR::CPVRProvidersPath::Init(), PVR::CPVREpgSearchPath::Init(), PVR::CPVRTimersPath::Init(), CDarwinUtils::IsAliasShortcut(), XFILE::IDirectory::IsAllowed(), CGUIViewState::IsCurrentPlaylistDirectory(), IsLiveTV(), IsPVRRecording(), XBMCAddon::xbmcvfs::listdir(), CGUIDialogFileBrowser::OnAddNetworkLocation(), CGUIWindowFileManager::OnNewFolder(), CGUIDialogMediaSource::OnPath(), CGUIDialogMediaSource::OnPathBrowse(), CGUIDialogFileBrowser::OnPopupMenu(), CDVDInputStreamBluray::Open(), CDVDInputStreamNavigator::Open(), XFILE::CDAVDirectory::ParseResponse(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::ParseURL(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), PathEquals(), CDirectoryHistory::preparePath(), CFileUtils::RemoteAccessAllowed(), XFILE::CNFSDirectory::Remove(), RemoveSlashAtEnd(), CFileUtils::RenameFile(), XFILE::CDirectoryCache::SetDirectory(), CGUIMediaWindow::SetHistoryForPath(), CGUIWindowFileManager::SetInitialPath(), CGUIDialogNetworkSetup::SetPath(), CGUIViewState::SetPlaylistDirectory(), CGUIViewControl::SetSelectedItem(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogSimpleMenu::ShowPlaySelection(), CScreenShot::TakeScreenshot(), TEST_F(), CMediaManager::TranslateDevicePath(), anonymous_namespace{PVRGUIDirectory.cpp}::TrimSlashes(), and CGUIDialogFileBrowser::Update().
ReplaceExtension()
std::string URIUtils::ReplaceExtension (const std::string & strFile, const std::string & strNewExtension) static
References CURL::Get(), GetExtension(), CURL::GetFileName(), IsURL(), ReplaceExtension(), and CURL::SetFileName().
Referenced by CDVDFileInfo::AddExternalSubtitleToDetails(), CGUIDialogSubtitleSettings::BrowseForSubtitle(), CTextureCache::ClearCachedImage(), CTextureCache::ClearCachedImage(), CVideoDatabase::ExportToXML(), CFileItemList::FilterCueItems(), CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), CUtil::FindVobSubPair(), KODI::ART::GetLocalArt(), KODI::ART::GetLocalFanart(), KODI::ART::GetTBNFile(), CUtil::GetVideoBasePathAndFileName(), CUtil::GetVobSubIdxFromSub(), CUtil::GetVobSubSubFromIdx(), CUtil::IsVobSub(), KODI::RETRO::CSavestateDatabase::MakeThumbnailPath(), CGUIDialogSubtitles::OnDownloadComplete(), CTextureBundleXBT::OpenBundle(), CPictureThumbLoader::ProcessFoldersAndArchives(), CEdl::ReadBeyondTV(), CEdl::ReadComskip(), CEdl::ReadEdl(), CEdl::ReadVideoReDo(), ReplaceExtension(), and TEST_F().
resolvePath()
std::string URIUtils::resolvePath (const std::string & path) static private
Referenced by GetRealPath().
Split()
void URIUtils::Split (const std::string & strFileNameAndPath, std::string & strPath, std::string & strFileName) static
References IsURL().
Referenced by XFILE::CStackDirectory::ConstructStackPath(), XFILE::CStackDirectory::ConstructStackPath(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), XFILE::CMultiPathFile::Exists(), CUtil::FindVobSubPair(), XFILE::CStackDirectory::GetFirstStackedFile(), CGUIMediaWindow::GetStartFolder(), CUtil::IsVobSub(), XFILE::CMultiPathFile::Open(), CMusicDatabase::SplitPath(), CVideoDatabase::SplitPath(), CFileItemList::StackFiles(), XFILE::CMultiPathFile::Stat(), TEST_F(), CGUIWindowMusicNav::UpdateButtons(), and CGUIWindowVideoNav::UpdateButtons().
SplitPath()
std::vector< std::string > URIUtils::SplitPath (const std::string & strPath) static
References CURL::GetDirectorySeparator(), CURL::GetFileName(), and CURL::GetWithoutFilename().
Referenced by PVR::CPVRChannelsPath::CPVRChannelsPath(), PVR::CPVRRecordingsPath::CPVRRecordingsPath(), CUtil::CreateDirectoryEx(), CMusicDatabase::GetAlbumFolder(), PVR::CPVRProvidersPath::Init(), PVR::CPVREpgSearchPath::Init(), PVR::CPVRTimersPath::Init(), CUtil::MakeLegalPath(), TEST(), TEST_F(), and TEST_F().
SubstitutePath() [1/2]
CURL URIUtils::SubstitutePath (const CURL & url, bool reverse = false) static
References CURL::Get(), and SubstitutePath().
Referenced by jni::CJNIXBMCURIUtils::_substitutePath(), XFILE::CDirectory::Create(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), XFILE::CVirtualDirectory::GetDirectory(), XFILE::CDirectory::GetDirectory(), XFILE::CDirectory::GetDirectory(), KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListPLS::Load(), KODI::PLAYLIST::CPlayListB4S::LoadData(), KODI::PLAYLIST::CPlayListWPL::LoadData(), XFILE::CFile::Open(), XFILE::CFileStream::Open(), NPT_XbmcFile::Open(), XFILE::CFile::OpenForWrite(), XFILE::CDirectory::Remove(), XFILE::CDirectory::RemoveRecursive(), XFILE::CFile::Rename(), XFILE::CFile::SetHidden(), XFILE::CFile::Stat(), SubstitutePath(), and TEST_F().
SubstitutePath() [2/2]
std::string URIUtils::SubstitutePath (const std::string & strPath, bool reverse = false) static
References ChangeBasePath(), HasSlashAtEnd(), m_advancedSettings, and CAdvancedSettings::m_pathSubstitutions.
UnregisterAdvancedSettings()
void URIUtils::UnregisterAdvancedSettings () static
References m_advancedSettings.
Referenced by CSettingsComponent::Deinitialize().
UpdateUrlEncoding()
bool URIUtils::UpdateUrlEncoding (std::string & strFilename) static
Updates the URL encoded hostname of the given path.
This method must only be used to update paths encoded with the old (Eden) URL encoding implementation to the new (Frodo) URL encoding implementation (which does not URL encode -_.!().
Parameters
strFilename Path to update
Returns
True if the path has been updated/changed otherwise false
References XFILE::CStackDirectory::ConstructStackPath(), CURL::Get(), CURL::GetHostName(), XFILE::CStackDirectory::GetPaths(), HasEncodedHostname(), IsStack(), CURL::Parse(), CURL::SetHostName(), and UpdateUrlEncoding().
Referenced by TEST_F(), and UpdateUrlEncoding().
Member Data Documentation
m_advancedSettings
const CAdvancedSettings * URIUtils::m_advancedSettings = nullptr static private
Referenced by RegisterAdvancedSettings(), SubstitutePath(), and UnregisterAdvancedSettings().
The documentation for this class was generated from the following files:
URIUtils.h
URIUtils.cpp