Kodi Documentation: CGUIWindowSlideShow Class Reference
CGUIWindowSlideShow Class Reference
#include <GUIWindowSlideShow.h>
Public Member Functions
CGUIWindowSlideShow (void)
~CGUIWindowSlideShow () override
void Add (const CFileItem *picture) override
bool IsPlaying () const override
void Select (const std::string &picture) override
void GetSlideShowContents (CFileItemList &list) override
std::shared_ptr< const CFileItem > GetCurrentSlide () override
void StartSlideShow () override
void PlayPicture () override
bool InSlideShow () const override
int NumSlides () const override
int CurrentSlide () const override
bool IsPaused () const override
bool IsShuffled () const override
void Reset () override
void RunSlideShow (const std::string &strPath, bool bRecursive=false, bool bRandom=false, bool bNotRandom=false, const std::string &beginSlidePath="", bool startSlideShow=true, SortBy method=SortByLabel, SortOrder order=SortOrderAscending, SortAttribute sortAttributes=SortAttributeNone, const std::string &strExtensions="") override
void AddFromPath (const std::string &strPath, bool bRecursive, SortBy method=SortByLabel, SortOrder order=SortOrderAscending, SortAttribute sortAttributes=SortAttributeNone, const std::string &strExtensions="") override
void Shuffle () override
int GetDirection () const override
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
bool OnMessage (CGUIMessage &message) override
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
bool OnAction (const CAction &action) override
void Render () override
void RenderEx () override
void Process (unsigned int currentTime, CDirtyRegionList &regions) override
void OnDeinitWindow (int nextWindowID) override
void OnLoadPic (int iPic, int iSlideNumber, const std::string &strFileName, std::unique_ptr< CTexture > pTexture, bool bFullSize)
Public Member Functions inherited from CGUIDialog
CGUIDialog (int id, const std::string &xmlFile, DialogModalityType modalityType=DialogModalityType::MODAL)
~CGUIDialog (void) override
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Open (const std::string &param="")
void Open (bool bProcessRenderLoop, const std::string &param="")
bool OnBack (int actionID) override
bool IsDialogRunning () const override
bool IsDialog () const override
bool IsModalDialog () const override
virtual DialogModalityType GetModalityType () const
void SetAutoClose (unsigned int timeoutMs)
void ResetAutoClose (void)
void CancelAutoClose (void)
bool IsAutoClosed (void) const
void SetSound (bool OnOff)
bool IsSoundEnabled () const override
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsMediaWindow () const
virtual bool HasListItems () const
virtual CFileItemPtr GetCurrentListItem (int offset=0)
virtual int GetViewContainerID () const
virtual int GetViewCount () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual CGUIControl * GetFirstFocusableControl (int id)
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Public Member Functions inherited from ISlideShowDelegate
ISlideShowDelegate ()=default
virtual ~ISlideShowDelegate ()=default
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Static Public Member Functions
static void RunSlideShow (const std::vector< std::string > &paths, int start=0)
Private Types
typedef std::set< std::string > path_set
Private Member Functions
void ShowNext ()
void ShowPrevious ()
void SetDirection (int direction)
void AddItems (const std::string &strPath, path_set *recursivePaths, SortBy method=SortByLabel, SortOrder order=SortOrderAscending, SortAttribute sortAttributes=SortAttributeNone)
bool PlayVideo ()
CSlideShowPic::DISPLAY_EFFECT GetDisplayEffect (int iSlideNumber) const
void RenderPause ()
void RenderErrorMessage ()
void Rotate (float fAngle, bool immediate=false)
void Zoom (int iZoom)
void ZoomRelative (float fZoom, bool immediate=false)
void Move (float fX, float fY)
void GetCheckedSize (float width, float height, int &maxWidth, int &maxHeight)
std::string GetPicturePath (CFileItem *item)
int GetNextSlide ()
void AnnouncePlayerPlay (const CFileItemPtr &item)
void AnnouncePlayerPause (const CFileItemPtr &item)
void AnnouncePlayerStop (const CFileItemPtr &item)
void AnnouncePlaylistClear ()
void AnnouncePlaylistAdd (const CFileItemPtr &item, int pos)
void AnnouncePropertyChanged (const std::string &strProperty, const CVariant &value)
Private Attributes
int m_iCurrentSlide
int m_iNextSlide
int m_iDirection
float m_fRotate
float m_fInitialRotate
int m_iZoomFactor
float m_fZoom
float m_fInitialZoom
bool m_bShuffled
bool m_bSlideShow
bool m_bPause
bool m_bPlayingVideo
int m_iVideoSlide = -1
bool m_bErrorMessage
std::vector< CFileItemPtr > m_slides
std::unique_ptr< CSlideShowPic > m_Image [2]
int m_iCurrentPic
std::unique_ptr< CBackgroundPicLoader > m_pBackgroundLoader
int m_iLastFailedNextSlide
bool m_bLoadNextPic
RESOLUTION m_Resolution
CPoint m_firstGesturePoint
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Protected Member Functions inherited from CGUIDialog
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
void SetDefaults () override
void OnWindowLoaded () override
virtual void UpdateVisibility ()
virtual void Open_Internal (bool bProcessRenderLoop, const std::string &param="")
void ProcessRenderLoop (bool renderOnly=false)
Protected Member Functions inherited from CGUIWindow
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void OnWindowUnload ()
virtual void OnInitWindow ()
Called on window open.
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
virtual void SaveControlStates ()
virtual void RestoreControlStates ()
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes inherited from CGUIDialog
bool m_wasRunning
true if we were running during the last DoProcess()
bool m_autoClosing
bool m_enableSound
unsigned int m_showStartTime
unsigned int m_showDuration
bool m_bAutoClosed
DialogModalityType m_modalityType
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Typedef Documentation
path_set
typedef std::set<std::string> CGUIWindowSlideShow::path_set private
Constructor & Destructor Documentation
CGUIWindowSlideShow()
CGUIWindowSlideShow::CGUIWindowSlideShow (void)
References CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetSlideShowDelegator(), CGUIWindow::KEEP_IN_MEMORY, m_bLoadNextPic, CGUIWindow::m_loadType, ANNOUNCEMENT::Player, Reset(), and CSlideShowDelegator::SetDelegate().
~CGUIWindowSlideShow()
CGUIWindowSlideShow::~CGUIWindowSlideShow () override
References CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetSlideShowDelegator(), and CSlideShowDelegator::ResetDelegate().
Member Function Documentation
Add()
void CGUIWindowSlideShow::Add (const CFileItem * picture) override virtual
Implements ISlideShowDelegate.
References AnnouncePlaylistAdd(), KODI::VIDEO::IsVideo(), and m_slides.
Referenced by AddItems(), and OnMessage().
AddFromPath()
void CGUIWindowSlideShow::AddFromPath (const std::string & strPath, bool bRecursive, SortBy method = SortByLabel, SortOrder order = SortOrderAscending, SortAttribute sortAttributes = SortAttributeNone, const std::string & strExtensions = "") override virtual
Todo:
refactor to use an options struct. Methods with so many arguments are a sign of a bad design...
Implements ISlideShowDelegate.
References AddItems(), and Reset().
Referenced by RunSlideShow().
AddItems()
void CGUIWindowSlideShow::AddItems (const std::string & strPath, path_set * recursivePaths, SortBy method = SortByLabel, SortOrder order = SortOrderAscending, SortAttribute sortAttributes = SortAttributeNone) private
References Add(), AddItems(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::GetDirectory(), CGUIViewStateWindowPictures::GetExtensions(), URIUtils::IsRAR(), URIUtils::IsZIP(), URIUtils::RemoveSlashAtEnd(), CFileItemList::Size(), and CFileItemList::Sort().
Referenced by AddFromPath(), and AddItems().
Announce()
void CGUIWindowSlideShow::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References Close(), and data().
AnnouncePlayerPause()
void CGUIWindowSlideShow::AnnouncePlayerPause (const CFileItemPtr & item) private
References CServiceBroker::GetAnnouncementManager(), and ANNOUNCEMENT::Player.
Referenced by OnAction().
AnnouncePlayerPlay()
void CGUIWindowSlideShow::AnnouncePlayerPlay (const CFileItemPtr & item) private
References CServiceBroker::GetAnnouncementManager(), m_bPause, m_bSlideShow, and ANNOUNCEMENT::Player.
Referenced by OnAction(), OnMessage(), PlayPicture(), Process(), and StartSlideShow().
AnnouncePlayerStop()
void CGUIWindowSlideShow::AnnouncePlayerStop (const CFileItemPtr & item) private
References CServiceBroker::GetAnnouncementManager(), and ANNOUNCEMENT::Player.
Referenced by OnAction().
AnnouncePlaylistAdd()
void CGUIWindowSlideShow::AnnouncePlaylistAdd (const CFileItemPtr & item, int pos) private
References data(), CServiceBroker::GetAnnouncementManager(), and ANNOUNCEMENT::Playlist.
Referenced by Add().
AnnouncePlaylistClear()
void CGUIWindowSlideShow::AnnouncePlaylistClear () private
References data(), CServiceBroker::GetAnnouncementManager(), and ANNOUNCEMENT::Playlist.
Referenced by Reset().
AnnouncePropertyChanged()
void CGUIWindowSlideShow::AnnouncePropertyChanged (const std::string & strProperty, const CVariant & value) private
References data(), CServiceBroker::GetAnnouncementManager(), ANNOUNCEMENT::Player, and value.
Referenced by Shuffle().
CurrentSlide()
int CGUIWindowSlideShow::CurrentSlide () const override virtual
Implements ISlideShowDelegate.
References m_iCurrentSlide.
GetCheckedSize()
void CGUIWindowSlideShow::GetCheckedSize (float width, float height, int & maxWidth, int & maxHeight) private
References CRenderSystemBase::GetMaxTextureSize(), and CServiceBroker::GetRenderSystem().
Referenced by Process().
GetCurrentSlide()
std::shared_ptr< const CFileItem > CGUIWindowSlideShow::GetCurrentSlide () override virtual
Implements ISlideShowDelegate.
References m_iCurrentSlide, and m_slides.
GetDirection()
int CGUIWindowSlideShow::GetDirection () const inline override virtual
Implements ISlideShowDelegate.
References m_iDirection.
GetDisplayEffect()
CSlideShowPic::DISPLAY_EFFECT CGUIWindowSlideShow::GetDisplayEffect (int iSlideNumber) const private
References CSlideShowPic::EFFECT_NO_TIMEOUT, CSlideShowPic::EFFECT_NONE, CSlideShowPic::EFFECT_RANDOM, CServiceBroker::GetSettingsComponent(), KODI::VIDEO::IsVideo(), m_bPause, m_bSlideShow, m_slides, and CSettings::SETTING_SLIDESHOW_DISPLAYEFFECTS.
Referenced by OnAction(), OnLoadPic(), and Process().
GetNextSlide()
int CGUIWindowSlideShow::GetNextSlide () private
References m_iCurrentSlide, m_iDirection, and m_slides.
Referenced by OnMessage(), Process(), Select(), SetDirection(), ShowNext(), ShowPrevious(), and Shuffle().
GetPicturePath()
std::string CGUIWindowSlideShow::GetPicturePath (CFileItem * item) private
References CGUIListItem::GetArt(), CFileItem::GetDynPath(), CGUIListItem::HasProperty(), KODI::VIDEO::IsVideo(), CPictureThumbLoader::LoadItem(), and CGUIListItem::SetProperty().
Referenced by OnLoadPic(), and Process().
GetSlideShowContents()
void CGUIWindowSlideShow::GetSlideShowContents (CFileItemList & list) override virtual
Implements ISlideShowDelegate.
References CFileItemList::Add(), index(), and m_slides.
InSlideShow()
bool CGUIWindowSlideShow::InSlideShow () const override virtual
Implements ISlideShowDelegate.
References m_bSlideShow.
IsPaused()
bool CGUIWindowSlideShow::IsPaused () const inline override virtual
Implements ISlideShowDelegate.
References m_bPause.
IsPlaying()
bool CGUIWindowSlideShow::IsPlaying () const override virtual
Implements ISlideShowDelegate.
References m_iCurrentPic, and m_Image.
IsShuffled()
bool CGUIWindowSlideShow::IsShuffled () const inline override virtual
Implements ISlideShowDelegate.
References m_bShuffled.
Move()
void CGUIWindowSlideShow::Move (float fX, float fY) private
References m_iCurrentPic, and m_Image.
Referenced by OnAction(), and OnMouseEvent().
NumSlides()
int CGUIWindowSlideShow::NumSlides () const override virtual
Implements ISlideShowDelegate.
References m_slides.
Referenced by RunSlideShow().
OnAction()
bool CGUIWindowSlideShow::OnAction (const CAction & action) override virtual
Reimplemented from CGUIDialog.
References ACTION_ANALOG_MOVE, ACTION_ANALOG_MOVE_X_LEFT, ACTION_ANALOG_MOVE_X_RIGHT, ACTION_ANALOG_MOVE_Y_DOWN, ACTION_ANALOG_MOVE_Y_UP, ACTION_GESTURE_SWIPE_DOWN, ACTION_GESTURE_SWIPE_UP, ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NEXT_PICTURE, ACTION_PAUSE, ACTION_PLAYER_PLAY, ACTION_PREV_PICTURE, ACTION_ROTATE_PICTURE_CCW, ACTION_ROTATE_PICTURE_CW, ACTION_SHOW_INFO, ACTION_STOP, ACTION_ZOOM_IN, ACTION_ZOOM_LEVEL_1, ACTION_ZOOM_LEVEL_2, ACTION_ZOOM_LEVEL_3, ACTION_ZOOM_LEVEL_4, ACTION_ZOOM_LEVEL_5, ACTION_ZOOM_LEVEL_6, ACTION_ZOOM_LEVEL_7, ACTION_ZOOM_LEVEL_8, ACTION_ZOOM_LEVEL_9, ACTION_ZOOM_LEVEL_NORMAL, ACTION_ZOOM_OUT, AnnouncePlayerPause(), AnnouncePlayerPlay(), AnnouncePlayerStop(), Close(), CApplicationPlayer::ClosePlayer(), CServiceBroker::GetAppComponents(), GetDisplayEffect(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CGraphicContext::GetWidth(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), KODI::VIDEO::IsVideo(), m_bPause, m_bPlayingVideo, m_bSlideShow, m_iCurrentPic, m_iCurrentSlide, m_Image, m_iZoomFactor, m_slides, CGUIControl::MarkDirtyRegion(), Move(), CGUIDialog::OnAction(), CGUIDialog::Open(), PICTURE_MOVE_AMOUNT, PICTURE_MOVE_AMOUNT_ANALOG, PlayVideo(), Rotate(), SetDirection(), ShowNext(), ShowPrevious(), WINDOW_DIALOG_PICTURE_INFO, and Zoom().
Referenced by OnMouseEvent().
OnDeinitWindow()
void CGUIWindowSlideShow::OnDeinitWindow (int nextWindowID) override virtual
Reimplemented from CGUIDialog.
References CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CDisplaySettings::GetInstance(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetPicturesInfoProvider(), CLog::Log(), LOGDEBUG, m_bSlideShow, m_Image, m_pBackgroundLoader, m_Resolution, CGUIDialog::OnDeinitWindow(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::SetCurrentSlide(), KODI::TIME::Sleep(), WINDOW_FULLSCREEN_GAME, and WINDOW_FULLSCREEN_VIDEO.
OnLoadPic()
void CGUIWindowSlideShow::OnLoadPic (int iPic, int iSlideNumber, const std::string & strFileName, std::unique_ptr< CTexture > pTexture, bool bFullSize)
References GetDisplayEffect(), CURL::GetHostName(), GetPicturePath(), URIUtils::HasExtension(), URIUtils::IsInRAR(), URIUtils::IsInZIP(), CLog::Log(), LOGDEBUG, m_bErrorMessage, m_iCurrentPic, m_iCurrentSlide, m_Image, m_iNextSlide, m_slides, and CGUIControl::MarkDirtyRegion().
Referenced by CBackgroundPicLoader::Process().
OnMessage()
bool CGUIWindowSlideShow::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIDialog.
References Add(), AnnouncePlayerPlay(), CWinSystemBase::GetGfxContext(), CGUIMessage::GetMessage(), GetNextSlide(), CGUIMessage::GetParam1(), CServiceBroker::GetSettingsComponent(), CGUIMessage::GetStringParam(), CGraphicContext::GetVideoResolution(), CServiceBroker::GetWinSystem(), GUI_MSG_PLAYBACK_ENDED, GUI_MSG_PLAYBACK_STOPPED, GUI_MSG_PLAYLISTPLAYER_STOPPED, GUI_MSG_SHOW_PICTURE, GUI_MSG_START_SLIDESHOW, GUI_MSG_WINDOW_INIT, m_bPause, m_bPlayingVideo, m_bSlideShow, m_fRotate, m_fZoom, m_iCurrentPic, m_iCurrentSlide, m_Image, m_iNextSlide, m_iVideoSlide, m_iZoomFactor, m_Resolution, m_slides, CGUIDialog::OnMessage(), Reset(), RunSlideShow(), CSettings::SETTING_PICTURES_DISPLAYRESOLUTION, and CGraphicContext::SetVideoResolution().
OnMouseEvent()
EVENT_RESULT CGUIWindowSlideShow::OnMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) override virtual
Perform a mouse action.
Mouse actions are sent from the window to all controls, and each control can react based on the event and location of the actions.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
SendMouseEvent, HitTest, CanFocusFromPoint, CMouseEvent
Reimplemented from CGUIWindow.
References ACTION_GESTURE_ABORT, ACTION_GESTURE_BEGIN, ACTION_GESTURE_END, ACTION_GESTURE_NOTIFY, ACTION_GESTURE_PAN, ACTION_GESTURE_ROTATE, ACTION_GESTURE_SWIPE_LEFT, ACTION_GESTURE_SWIPE_RIGHT, ACTION_GESTURE_ZOOM, ACTION_NEXT_PICTURE, ACTION_PREV_PICTURE, EVENT_RESULT_HANDLED, EVENT_RESULT_PAN_HORIZONTAL, EVENT_RESULT_PAN_VERTICAL, EVENT_RESULT_ROTATE, EVENT_RESULT_SWIPE, EVENT_RESULT_UNHANDLED, EVENT_RESULT_ZOOM, m_fInitialRotate, m_fInitialZoom, m_firstGesturePoint, m_fRotate, m_fZoom, m_iCurrentPic, KODI::MOUSE::CMouseEvent::m_id, m_Image, m_iZoomFactor, KODI::MOUSE::CMouseEvent::m_offsetX, Move(), OnAction(), PICTURE_MOVE_AMOUNT_TOUCH, Rotate(), ROTATION_SNAP_RANGE, CPointGen< T >::x, CPointGen< T >::y, and ZoomRelative().
PlayPicture()
void CGUIWindowSlideShow::PlayPicture () override virtual
Implements ISlideShowDelegate.
References AnnouncePlayerPlay(), m_iCurrentSlide, and m_slides.
Referenced by RunSlideShow().
PlayVideo()
bool CGUIWindowSlideShow::PlayVideo () private
References g_application, KODI::VIDEO::IsVideo(), CLog::Log(), LOGDEBUG, LOGINFO, m_bPlayingVideo, m_iCurrentSlide, m_iVideoSlide, and m_slides.
Referenced by OnAction(), and Process().
Process()
void CGUIWindowSlideShow::Process (unsigned int currentTime, CDirtyRegionList & regions) override virtual
Reimplemented from CGUIControlGroup.
References AnnouncePlayerPlay(), CApplicationPlayer::ClosePlayer(), CServiceBroker::GetAppComponents(), GetCheckedSize(), GetDisplayEffect(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CGUIControl::GetHeight(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), GetNextSlide(), GetPicturePath(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetPicturesInfoProvider(), CGraphicContext::GetResInfo(), CGUIControl::GetWidth(), CServiceBroker::GetWinSystem(), CGUIControl::HasProcessed(), RESOLUTION_INFO::iHeight, IMMEDIATE_TRANSITION_TIME, CGUIWindow::IsAnimating(), KODI::VIDEO::IsVideo(), RESOLUTION_INFO::iWidth, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_bErrorMessage, m_bLoadNextPic, m_bPause, m_bPlayingVideo, m_bSlideShow, m_fRotate, m_fZoom, m_iCurrentPic, m_iCurrentSlide, m_iLastFailedNextSlide, m_Image, m_iNextSlide, m_iVideoSlide, m_iZoomFactor, m_pBackgroundLoader, CGUIControl::m_renderRegion, m_slides, CGUIControl::MarkDirtyRegion(), PlayVideo(), CGUIControl::Process(), RenderPause(), CApplicationPowerHandling::ResetScreenSaver(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::SetCurrentSlide(), and CRectGen< T >::SetRect().
Render()
void CGUIWindowSlideShow::Render () override virtual
Reimplemented from CGUIDialog.
References CGraphicContext::Clear(), CServiceBroker::GetAppComponents(), CWinSystemBase::GetGfxContext(), CGUIControl::GetRenderRegion(), CGraphicContext::GetScissors(), CGraphicContext::GetVideoResolution(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iHeight, CRectGen< T >::Intersect(), KODI::VIDEO::IsVideo(), RESOLUTION_INFO::iWidth, CGUIWindow::m_coordsRes, m_iCurrentPic, m_iCurrentSlide, m_Image, CGUIWindow::m_needsScaling, m_slides, CGraphicContext::MergeAlpha(), CGUIControl::Render(), RenderErrorMessage(), CGraphicContext::SetRenderingResolution(), CGraphicContext::SetScissors(), and CGraphicContext::SetViewWindow().
RenderErrorMessage()
void CGUIWindowSlideShow::RenderErrorMessage () private
References CGUITextLayout::DrawText(), g_localizeStrings, CLocalizeStrings::Get(), CGUIControlLookup::GetControl(), CGUIControl::GetControlType(), CGUIControl::GetHeight(), CGUIControl::GetWidth(), CServiceBroker::GetWinSystem(), CGUIControl::GUICONTROL_LABEL, LABEL_ROW1, m_bErrorMessage, XBFONT_CENTER_X, and XBFONT_CENTER_Y.
Referenced by Render().
RenderEx()
void CGUIWindowSlideShow::RenderEx () override virtual
Reimplemented from CGUIControlGroup.
References CServiceBroker::GetAppComponents(), KODI::VIDEO::IsVideo(), m_iCurrentSlide, m_slides, CApplicationPlayer::Render(), and CGUIControl::RenderEx().
RenderPause()
void CGUIWindowSlideShow::RenderPause () private
References CONTROL_PAUSE, m_bPause, SET_CONTROL_HIDDEN, and SET_CONTROL_VISIBLE.
Referenced by Process().
Reset()
void CGUIWindowSlideShow::Reset () override virtual
Implements ISlideShowDelegate.
References AnnouncePlaylistClear(), CSlideShowPic::CreateSlideShowPicture(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetVideoResolution(), CServiceBroker::GetWinSystem(), m_bErrorMessage, m_bPause, m_bPlayingVideo, m_bShuffled, m_bSlideShow, m_fInitialRotate, m_fInitialZoom, m_fRotate, m_fZoom, m_iCurrentPic, m_iCurrentSlide, m_iDirection, m_iLastFailedNextSlide, m_Image, m_iNextSlide, m_iZoomFactor, m_Resolution, and m_slides.
Referenced by AddFromPath(), CGUIWindowSlideShow(), OnMessage(), and RunSlideShow().
Rotate()
void CGUIWindowSlideShow::Rotate (float fAngle, bool immediate = false) private
References m_fRotate, m_iCurrentPic, and m_Image.
Referenced by OnAction(), and OnMouseEvent().
RunSlideShow() [1/2]
void CGUIWindowSlideShow::RunSlideShow (const std::string & strPath, bool bRecursive = false, bool bRandom = false, bool bNotRandom = false, const std::string & beginSlidePath = "", bool startSlideShow = true, SortBy method = SortByLabel, SortOrder order = SortOrderAscending, SortAttribute sortAttributes = SortAttributeNone, const std::string & strExtensions = "") override virtual
Todo:
refactor to use an options struct. Methods with so many arguments are a sign of a bad design...
Implements ISlideShowDelegate.
References CGUIWindowManager::ActivateWindow(), AddFromPath(), g_application, CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), NumSlides(), PlayPicture(), Select(), CSettings::SETTING_SLIDESHOW_SHUFFLE, Shuffle(), StartSlideShow(), and WINDOW_SLIDESHOW.
Referenced by CGUIDialogAddonInfo::OnMessage(), and OnMessage().
RunSlideShow() [2/2]
void CGUIWindowSlideShow::RunSlideShow (const std::vector< std::string > & paths, int start = 0) static
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), Reset(), IMAGE_FILES::URLFromFile(), and WINDOW_SLIDESHOW.
Select()
void CGUIWindowSlideShow::Select (const std::string & picture) override virtual
Implements ISlideShowDelegate.
References GetNextSlide(), m_bLoadNextPic, m_iCurrentPic, m_iCurrentSlide, m_iDirection, m_Image, m_iNextSlide, m_pBackgroundLoader, and m_slides.
Referenced by RunSlideShow().
SetDirection()
void CGUIWindowSlideShow::SetDirection (int direction) private
References GetNextSlide(), m_iDirection, and m_iNextSlide.
Referenced by OnAction().
ShowNext()
void CGUIWindowSlideShow::ShowNext () private
References GetNextSlide(), m_bLoadNextPic, m_fRotate, m_fZoom, m_iDirection, m_iNextSlide, m_iZoomFactor, and m_slides.
Referenced by OnAction().
ShowPrevious()
void CGUIWindowSlideShow::ShowPrevious () private
References GetNextSlide(), m_bLoadNextPic, m_fRotate, m_fZoom, m_iDirection, m_iNextSlide, m_iZoomFactor, and m_slides.
Referenced by OnAction().
Shuffle()
void CGUIWindowSlideShow::Shuffle () override virtual
Implements ISlideShowDelegate.
References AnnouncePropertyChanged(), GetNextSlide(), m_bShuffled, m_iCurrentSlide, m_iNextSlide, m_slides, and KODI::UTILS::RandomShuffle().
Referenced by RunSlideShow().
StartSlideShow()
void CGUIWindowSlideShow::StartSlideShow () override virtual
Implements ISlideShowDelegate.
References AnnouncePlayerPlay(), m_bSlideShow, m_iCurrentSlide, m_iDirection, and m_slides.
Referenced by RunSlideShow().
Zoom()
void CGUIWindowSlideShow::Zoom (int iZoom) private
References MAX_ZOOM_FACTOR, zoomamount, and ZoomRelative().
Referenced by OnAction().
ZoomRelative()
void CGUIWindowSlideShow::ZoomRelative (float fZoom, bool immediate = false) private
References m_fZoom, m_iCurrentPic, m_Image, m_iZoomFactor, MAX_ZOOM_FACTOR, and zoomamount.
Referenced by OnMouseEvent(), and Zoom().
Member Data Documentation
m_bErrorMessage
bool CGUIWindowSlideShow::m_bErrorMessage private
Referenced by OnLoadPic(), Process(), RenderErrorMessage(), and Reset().
m_bLoadNextPic
bool CGUIWindowSlideShow::m_bLoadNextPic private
Referenced by CGUIWindowSlideShow(), Process(), Select(), ShowNext(), and ShowPrevious().
m_bPause
bool CGUIWindowSlideShow::m_bPause private
Referenced by AnnouncePlayerPlay(), GetDisplayEffect(), IsPaused(), OnAction(), OnMessage(), Process(), RenderPause(), and Reset().
m_bPlayingVideo
bool CGUIWindowSlideShow::m_bPlayingVideo private
Referenced by OnAction(), OnMessage(), PlayVideo(), Process(), and Reset().
m_bShuffled
bool CGUIWindowSlideShow::m_bShuffled private
Referenced by IsShuffled(), Reset(), and Shuffle().
m_bSlideShow
bool CGUIWindowSlideShow::m_bSlideShow private
Referenced by AnnouncePlayerPlay(), GetDisplayEffect(), InSlideShow(), OnAction(), OnDeinitWindow(), OnMessage(), Process(), Reset(), and StartSlideShow().
m_fInitialRotate
float CGUIWindowSlideShow::m_fInitialRotate private
Referenced by OnMouseEvent(), and Reset().
m_fInitialZoom
float CGUIWindowSlideShow::m_fInitialZoom private
Referenced by OnMouseEvent(), and Reset().
m_firstGesturePoint
CPoint CGUIWindowSlideShow::m_firstGesturePoint private
Referenced by OnMouseEvent().
m_fRotate
float CGUIWindowSlideShow::m_fRotate private
Referenced by OnMessage(), OnMouseEvent(), Process(), Reset(), Rotate(), ShowNext(), and ShowPrevious().
m_fZoom
float CGUIWindowSlideShow::m_fZoom private
Referenced by OnMessage(), OnMouseEvent(), Process(), Reset(), ShowNext(), ShowPrevious(), and ZoomRelative().
m_iCurrentPic
int CGUIWindowSlideShow::m_iCurrentPic private
Referenced by IsPlaying(), Move(), OnAction(), OnLoadPic(), OnMessage(), OnMouseEvent(), Process(), Render(), Reset(), Rotate(), Select(), and ZoomRelative().
m_iCurrentSlide
int CGUIWindowSlideShow::m_iCurrentSlide private
Referenced by CurrentSlide(), GetCurrentSlide(), GetNextSlide(), OnAction(), OnLoadPic(), OnMessage(), PlayPicture(), PlayVideo(), Process(), Render(), RenderEx(), Reset(), Select(), Shuffle(), and StartSlideShow().
m_iDirection
int CGUIWindowSlideShow::m_iDirection private
Referenced by GetDirection(), GetNextSlide(), Reset(), Select(), SetDirection(), ShowNext(), ShowPrevious(), and StartSlideShow().
m_iLastFailedNextSlide
int CGUIWindowSlideShow::m_iLastFailedNextSlide private
Referenced by Process(), and Reset().
m_Image
std::unique_ptr<CSlideShowPic> CGUIWindowSlideShow::m_Image[2] private
Referenced by IsPlaying(), Move(), OnAction(), OnDeinitWindow(), OnLoadPic(), OnMessage(), OnMouseEvent(), Process(), Render(), Reset(), Rotate(), Select(), and ZoomRelative().
m_iNextSlide
int CGUIWindowSlideShow::m_iNextSlide private
Referenced by OnLoadPic(), OnMessage(), Process(), Reset(), Select(), SetDirection(), ShowNext(), ShowPrevious(), and Shuffle().
m_iVideoSlide
int CGUIWindowSlideShow::m_iVideoSlide = -1 private
Referenced by OnMessage(), PlayVideo(), and Process().
m_iZoomFactor
int CGUIWindowSlideShow::m_iZoomFactor private
Referenced by OnAction(), OnMessage(), OnMouseEvent(), Process(), Reset(), ShowNext(), ShowPrevious(), and ZoomRelative().
m_pBackgroundLoader
std::unique_ptr<CBackgroundPicLoader> CGUIWindowSlideShow::m_pBackgroundLoader private
Referenced by OnDeinitWindow(), Process(), and Select().
m_Resolution
RESOLUTION CGUIWindowSlideShow::m_Resolution private
Referenced by OnDeinitWindow(), OnMessage(), and Reset().
m_slides
std::vector<CFileItemPtr> CGUIWindowSlideShow::m_slides private
Referenced by Add(), GetCurrentSlide(), GetDisplayEffect(), GetNextSlide(), GetSlideShowContents(), NumSlides(), OnAction(), OnLoadPic(), OnMessage(), PlayPicture(), PlayVideo(), Process(), Render(), RenderEx(), Reset(), Select(), ShowNext(), ShowPrevious(), Shuffle(), and StartSlideShow().
The documentation for this class was generated from the following files:
GUIWindowSlideShow.h
GUIWindowSlideShow.cpp