Kodi Documentation: CWIN32Util Class Reference
CWIN32Util Class Reference
#include <WIN32Util.h>
Public Member Functions
CWIN32Util (void)
virtual ~CWIN32Util (void)
Static Public Member Functions
static char FirstDriveFromMask (ULONG unitmask)
static int GetDriveStatus (const std::string &strPath, bool bStatusEx=false)
static bool XBMCShellExecute (const std::string &strPath, bool bWaitForScriptExit=false)
static std::string GetResInfoString ()
static int GetDesktopColorDepth ()
static size_t GetSystemMemorySize ()
static std::string GetProfilePath (const bool platformDirectories)
static std::string UncToSmb (const std::string &strPath)
static std::string SmbToUnc (const std::string &strPath)
static bool AddExtraLongPathPrefix (std::wstring &path)
static bool RemoveExtraLongPathPrefix (std::wstring &path)
static std::wstring ConvertPathToWin32Form (const std::string &pathUtf8)
static std::wstring ConvertPathToWin32Form (const CURL &url)
static __time64_t fileTimeToTimeT (const __int64 ftimei64)
static __time64_t fileTimeToTimeT (const FILETIME &ftimeft)
static __time64_t fileTimeToTimeT (const LARGE_INTEGER &ftimeli)
static HRESULT ToggleTray (const char cDriveLetter='\0')
static HRESULT EjectTray (const char cDriveLetter='\0')
static HRESULT CloseTray (const char cDriveLetter='\0')
static BOOL IsCurrentUserLocalAdministrator ()
static void CropSource (CRect &src, CRect &dst, CRect target, UINT rotation=0)
static std::string WUSysMsg (DWORD dwError)
static bool SetThreadLocalLocale (bool enable=true)
static HDR_STATUS ToggleWindowsHDR (DXGI_MODE_DESC &modeDesc)
static HDR_STATUS GetWindowsHDRStatus ()
static bool GetSystemSdrWhiteLevel (const std::wstring &gdiDeviceName, float *sdrWhiteLevel)
Retrieve from the system the max luminance of SDR content in HDR.
static void PlatformSyslog ()
static VideoDriverInfo GetVideoDriverInfo (const UINT vendorId, const std::wstring &driverDesc)
static VideoDriverInfo GetVideoDriverInfoDX (const UINT vendorId, LUID adapterLuid)
static VideoDriverInfo FormatVideoDriverInfo (const UINT vendorId, uint64_t rawVersion)
static VideoDriverInfo FormatVideoDriverInfo (const UINT vendorId, const std::string version)
static std::wstring GetDisplayFriendlyName (const std::wstring &GdiDeviceName)
static bool SetThreadName (const HANDLE handle, const std::string &name)
Set the thread name using SetThreadDescription when available.
static bool IsDriverVersionAtLeast (const std::string &version1, const std::string &version2)
Compare two Windows driver versions (xx.xx.xx.xx string format)
static std::string FormatHRESULT (HRESULT hr)
Format a Windows HRESULT value into a string for logging.
Static Private Member Functions
static HDR_STATUS GetWindowsHDRStatusWin32 ()
Constructor & Destructor Documentation
CWIN32Util()
CWIN32Util::CWIN32Util (void)
~CWIN32Util()
CWIN32Util::~CWIN32Util (void) virtual
Member Function Documentation
AddExtraLongPathPrefix()
bool CWIN32Util::AddExtraLongPathPrefix (std::wstring & path) static
Referenced by CFileUtils::CheckFileAccessAllowed().
CloseTray()
HRESULT CWIN32Util::CloseTray (const char cDriveLetter = '\0') static
References GetDriveStatus(), CServiceBroker::GetMediaManager(), ToggleTray(), and CMediaManager::TranslateDevicePath().
Referenced by CWin32DiscDriveHandler::CloseDriveTray().
ConvertPathToWin32Form() [1/2]
std::wstring CWIN32Util::ConvertPathToWin32Form (const CURL & url) static
References URIUtils::CanonicalizePath(), URIUtils::FixSlashesAndDups(), g_charsetConverter, CURL::Get(), CURL::GetFileName(), CURL::GetHostName(), CURL::GetProtocol(), CURL::IsProtocol(), and LOGERROR.
ConvertPathToWin32Form() [2/2]
std::wstring CWIN32Util::ConvertPathToWin32Form (const std::string & pathUtf8) static
References URIUtils::CanonicalizePath(), URIUtils::FixSlashesAndDups(), g_charsetConverter, CLog::Log(), and LOGERROR.
Referenced by XFILE::CWin32File::Delete(), XFILE::CWin32File::Exists(), XFILE::CWin32SMBFile::Exists(), XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CWin32Directory::GetDirectory(), CWin32InterfaceForCLog::GetLogFilename(), XFILE::CWin32File::Open(), XFILE::CWin32File::OpenForWrite(), prepareWin32DirectoryName(), prepareWin32SMBDirectoryName(), XFILE::CWin32Directory::RemoveRecursive(), XFILE::CWin32File::Rename(), XFILE::CWin32File::SetHidden(), XFILE::CWin32SMBFile::SetHidden(), and XFILE::CWin32File::Stat().
CropSource()
void CWIN32Util::CropSource (CRect & src, CRect & dst, CRect target, UINT rotation = 0) static
References CRectGen< T >::Height(), CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CConvolutionShaderSeparable::PrepareParameters(), and CRendererDXVA::RenderImpl().
EjectTray()
HRESULT CWIN32Util::EjectTray (const char cDriveLetter = '\0') static
References GetDriveStatus(), CServiceBroker::GetMediaManager(), ToggleTray(), and CMediaManager::TranslateDevicePath().
Referenced by CWin32DiscDriveHandler::EjectDriveTray().
fileTimeToTimeT() [1/3]
static __time64_t CWIN32Util::fileTimeToTimeT (const __int64 ftimei64) inline static
Referenced by fileTimeToTimeT(), fileTimeToTimeT(), XFILE::CWin32File::Stat(), and XFILE::CWin32File::Stat().
fileTimeToTimeT() [2/3]
__time64_t CWIN32Util::fileTimeToTimeT (const FILETIME & ftimeft) static
References fileTimeToTimeT().
fileTimeToTimeT() [3/3]
__time64_t CWIN32Util::fileTimeToTimeT (const LARGE_INTEGER & ftimeli) static
References fileTimeToTimeT(), and _LARGE_INTEGER::QuadPart.
FirstDriveFromMask()
char CWIN32Util::FirstDriveFromMask (ULONG unitmask) static
Referenced by CWinEventsWin32::WndProc().
FormatHRESULT()
std::string CWIN32Util::FormatHRESULT (HRESULT hr) static
Format a Windows HRESULT value into a string for logging.
Parameters
hr The error code
Returns
Formatted string
References DXGetErrorDescriptionW(), and DXGetErrorStringW().
Referenced by AEWASAPIDeviceWin32::Activate(), CAESinkWASAPI::AddPackets(), CAESinkXAudio::AddPackets(), CRenderCaptureDX::BeginRender(), DXVA::CEnumeratorHD::CheckConversionInternal(), CAESinkDirectSound::CheckPlayStatus(), DXVA::CContext::CreateContext(), DX::DeviceResources::CreateDeviceResources(), DXVA::CContext::CreateSurfaces(), DXVA::CEnumeratorHD::CreateVideoProcessor(), DXVA::CEnumeratorHD::CreateVideoProcessorInputView(), DXVA::CEnumeratorHD::CreateVideoProcessorOutputView(), DXVA::CProcessorHD::EnableIntelVideoSuperResolution(), DXVA::CProcessorHD::EnableNvidiaRTXVideoSuperResolution(), CAESinkDirectSound::EnumerateDevicesEx(), CAESinkWASAPI::EnumerateDevicesEx(), CAESinkXAudio::EnumerateDevicesEx(), DXVA::CEnumeratorHD::GetProcessorFormats(), DXVA::CVideoBufferShared::GetResource(), DX::DeviceResources::GetSwapChainColorSpaces(), CWinRtUtil::GetWindowsHDRStatus(), CAESinkDirectSound::Initialize(), DXVA::CVideoBufferCopy::Initialize(), CAESinkWASAPI::InitializeExclusive(), DXVA::CVideoBufferShared::InitializeFence(), CAESinkXAudio::InitializeInternal(), DXVA::CProcessorHD::InitProcessor(), DXVA::CEnumeratorHD::LogSupportedConversions(), DXVA::CEnumeratorHD::OpenEnumerator(), DXVA::CEnumeratorHD::ProbeProcessorCaps(), DXVA::CProcessorHD::Render(), CVideoSyncD3D::Run(), and CAESinkDirectSound::UpdateCacheStatus().
FormatVideoDriverInfo() [1/2]
VideoDriverInfo CWIN32Util::FormatVideoDriverInfo (const UINT vendorId, const std::string version) static
References PCIV_NVIDIA, and VideoDriverInfo::valid.
FormatVideoDriverInfo() [2/2]
VideoDriverInfo CWIN32Util::FormatVideoDriverInfo (const UINT vendorId, uint64_t rawVersion) static
References FormatVideoDriverInfo().
Referenced by FormatVideoDriverInfo(), GetVideoDriverInfo(), GetVideoDriverInfoDX(), and DX::DeviceResources::GetVideoDriverVersion().
GetDesktopColorDepth()
int CWIN32Util::GetDesktopColorDepth () static
References LOGDEBUG.
GetDisplayFriendlyName()
std::wstring CWIN32Util::GetDisplayFriendlyName (const std::wstring & GdiDeviceName) static
Referenced by CWinSystemWin32::GetConnectedDisplays().
GetDriveStatus()
int CWIN32Util::GetDriveStatus (const std::string & strPath, bool bStatusEx = false) static
References _SCSI_PASS_THROUGH_DIRECT::Cdb, _SCSI_PASS_THROUGH_DIRECT::CdbLength, CloseHandle(), _SCSI_PASS_THROUGH_DIRECT::DataBuffer, _SCSI_PASS_THROUGH_DIRECT::DataIn, _SCSI_PASS_THROUGH_DIRECT::DataTransferLength, GetLastError(), INVALID_HANDLE_VALUE, IOCTL_SCSI_PASS_THROUGH_DIRECT, _SCSI_PASS_THROUGH_DIRECT::Length, LOGDEBUG, LOGERROR, _SCSI_PASS_THROUGH_DIRECT::Lun, MAX_SENSE_LEN, OPEN_EXISTING, _SCSI_PASS_THROUGH_DIRECT::PathId, SCSI_IOCTL_DATA_IN, _SCSI_PASS_THROUGH_DIRECT::SenseInfoLength, _SCSI_PASS_THROUGH_DIRECT::SenseInfoOffset, _SCSI_PASS_THROUGH_DIRECT_AND_SENSE_BUFFER::sptd, _SCSI_PASS_THROUGH_DIRECT::TargetId, _SCSI_PASS_THROUGH_DIRECT::TimeOutValue, and KODI::PLATFORM::WINDOWS::ToW().
Referenced by CloseTray(), EjectTray(), CWin32DiscDriveHandler::GetDriveState(), and ToggleTray().
GetProfilePath()
std::string CWIN32Util::GetProfilePath (const bool platformDirectories) static
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), KODI::PLATFORM::WINDOWS::FromW(), CCompileInfo::GetAppName(), and CUtil::GetHomePath().
Referenced by CSettingsComponent::InitDirectoriesWin32(), win32_exception::write_minidump(), and win32_exception::write_stacktrace().
GetResInfoString()
std::string CWIN32Util::GetResInfoString () static
Referenced by PlatformSyslog().
GetSystemMemorySize()
size_t CWIN32Util::GetSystemMemorySize () static
References KB.
Referenced by PlatformSyslog().
GetSystemSdrWhiteLevel()
bool CWIN32Util::GetSystemSdrWhiteLevel (const std::wstring & gdiDeviceName, float * sdrWhiteLevel) static
Retrieve from the system the max luminance of SDR content in HDR.
Retrieve from the system the max luminance of SDR content in HDR. Note: always returns 80 nits when the screen is in SDR mode.
Parameters
gdiDeviceName The screen to retrieve the information for
sdrWhiteLevel Max luminance in nits, clamped to 10000
Returns
true if a value could be read from the system and copied to sdrWhiteLevel, false otherwise
Referenced by CWinSystemWin10::CacheSystemSdrPeakLuminance(), CWinSystemWin32::CacheSystemSdrPeakLuminance(), CWinSystemWin10::HasSystemSdrPeakLuminance(), and CWinSystemWin32::HasSystemSdrPeakLuminance().
GetVideoDriverInfo()
VideoDriverInfo CWIN32Util::GetVideoDriverInfo (const UINT vendorId, const std::wstring & driverDesc) static
References FormatVideoDriverInfo(), KODI::PLATFORM::WINDOWS::FromW(), and index().
Referenced by DX::DeviceResources::GetVideoDriverVersion().
GetVideoDriverInfoDX()
VideoDriverInfo CWIN32Util::GetVideoDriverInfoDX (const UINT vendorId, LUID adapterLuid) static
References FormatVideoDriverInfo(), KODI::PLATFORM::WINDOWS::FromW(), and index().
Referenced by DX::DeviceResources::GetVideoDriverVersion().
GetWindowsHDRStatus()
HDR_STATUS CWIN32Util::GetWindowsHDRStatus () static
References CSysInfo::GetWindowsDeviceFamily(), CWinRtUtil::GetWindowsHDRStatus(), CWinRtUtil::GetWindowsHDRStatusUWP(), GetWindowsHDRStatusWin32(), HDR_UNKNOWN, HDR_UNSUPPORTED, CSysInfo::IsWindowsVersionAtLeast(), CSysInfo::WindowsVersionWin11_22H2, and CSysInfo::Xbox.
Referenced by CWinSystemWin10DX::GetOSHDRStatus(), CWinSystemWin32DX::GetOSHDRStatus(), CWinSystemWin10DX::IsHDRDisplay(), CWinSystemWin32DX::IsHDRDisplay(), PlatformSyslog(), and DX::DeviceResources::ResizeBuffers().
GetWindowsHDRStatusWin32()
HDR_STATUS CWIN32Util::GetWindowsHDRStatusWin32 () static private
References g_hWnd, HDR_OFF, HDR_ON, HDR_UNKNOWN, HDR_UNSUPPORTED, CServiceBroker::IsServiceManagerUp(), and LOGDEBUG.
Referenced by GetWindowsHDRStatus().
IsCurrentUserLocalAdministrator()
BOOL CWIN32Util::IsCurrentUserLocalAdministrator () static
Referenced by PlatformSyslog().
IsDriverVersionAtLeast()
bool CWIN32Util::IsDriverVersionAtLeast (const std::string & version1, const std::string & version2) static
Compare two Windows driver versions (xx.xx.xx.xx string format)
Parameters
version1 First version to compare
version2 Second version to compare
Returns
true when version1 is greater or equal to version2. Undefined results when the strings are not formatted properly.
References ParseVideoDriverInfo().
Referenced by DX::DeviceResources::IsGCNOrOlder().
PlatformSyslog()
void CWIN32Util::PlatformSyslog () static
References g_sysinfo, GetResInfoString(), GetSystemMemorySize(), GetWindowsHDRStatus(), HDR_ON, HDR_UNSUPPORTED, CSysInfo::IsAeroDisabled(), IsCurrentUserLocalAdministrator(), CLog::Log(), LOGINFO, and MB.
Referenced by CPlatformWin10::PlatformSyslog(), and CPlatformWin32::PlatformSyslog().
RemoveExtraLongPathPrefix()
bool CWIN32Util::RemoveExtraLongPathPrefix (std::wstring & path) static
Referenced by CFileUtils::CheckFileAccessAllowed().
SetThreadLocalLocale()
bool CWIN32Util::SetThreadLocalLocale (bool enable = true) static
Referenced by CPlatformWin10::InitStageOne(), CPlatformWin32::InitStageOne(), and CThreadImplWin::SetThreadInfo().
SetThreadName()
bool CWIN32Util::SetThreadName (const HANDLE handle, const std::string & name) static
Set the thread name using SetThreadDescription when available.
Parameters
handle handle of the thread
name name of the thread
Returns
true if the name was successfully set, false otherwise (API not supported or API failure)
References CSysInfo::GetWindowsVersion(), name, KODI::PLATFORM::WINDOWS::ToW(), and CSysInfo::WindowsVersionWin10_1607.
Referenced by CThreadImplWin::SetThreadInfo().
SmbToUnc()
std::string CWIN32Util::SmbToUnc (const std::string & strPath) static
Referenced by CWin32InterfaceForCLog::GetLogFilename(), win32_exception::write_minidump(), and win32_exception::write_stacktrace().
ToggleTray()
HRESULT CWIN32Util::ToggleTray (const char cDriveLetter = '\0') static
References CloseHandle(), GetDriveStatus(), GetLastError(), CServiceBroker::GetMediaManager(), INVALID_HANDLE_VALUE, LOGDEBUG, OPEN_EXISTING, CMediaManager::RemoveAutoSource(), CMediaSource::strName, CMediaSource::strPath, and CMediaManager::TranslateDevicePath().
Referenced by CloseTray(), EjectTray(), and CWin32DiscDriveHandler::ToggleDriveTray().
ToggleWindowsHDR()
HDR_STATUS CWIN32Util::ToggleWindowsHDR (DXGI_MODE_DESC & modeDesc) static
References g_hWnd, HDR_OFF, HDR_ON, HDR_TOGGLE_FAILED, LOGDEBUG, LOGERROR, LOGINFO, and Wait().
Referenced by DX::DeviceResources::ToggleHDR().
UncToSmb()
std::string CWIN32Util::UncToSmb (const std::string & strPath) static
WUSysMsg()
std::string CWIN32Util::WUSysMsg (DWORD dwError) static
References SS_DEFLANGID.
Referenced by CNetworkWin32::PingHost(), CNetworkWin10::PingHost(), and CNetworkBase::PingHost().
XBMCShellExecute()
bool CWIN32Util::XBMCShellExecute (const std::string & strPath, bool bWaitForScriptExit = false) static
Todo:
Pause music and video playback
References CThread::Create(), g_charsetConverter, g_hWnd, g_windowHelper, LOGDEBUG, CWHelper::SetHANDLE(), and CThread::StopThread().
Referenced by CApplication::OnApplicationMessage().
The documentation for this class was generated from the following files:
WIN32Util.h
WIN32Util.cpp