Kodi Documentation: XFILE::CWinLibraryDirectory Class Reference
XFILE::CWinLibraryDirectory Class Reference
#include <WinLibraryDirectory.h>
Public Member Functions
CWinLibraryDirectory ()
virtual ~CWinLibraryDirectory (void)
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
DIR_CACHE_TYPE GetCacheType (const CURL &url) const override
How this directory should be cached.
bool Create (const CURL &url) override
Create the directory.
bool Exists (const CURL &url) override
Check for directory existence.
bool Remove (const CURL &url) override
Removes the directory.
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual bool AllowAll () const
Whether to allow all files/folders to be listed.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Static Public Member Functions
static bool GetStoragePath (std::string library, std::string &path)
static bool IsValid (const CURL &url)
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Static Private Member Functions
static winrt::Windows::Storage::StorageFolder GetRootFolder (const CURL &url)
static winrt::Windows::Storage::StorageFolder GetFolder (const CURL &url)
static int StatDirectory (const CURL &url, struct __stat64 *statData)
Private Attributes
friend CWinLibraryFile
Additional Inherited Members
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CWinLibraryDirectory()
CWinLibraryDirectory::CWinLibraryDirectory () default
~CWinLibraryDirectory()
CWinLibraryDirectory::~CWinLibraryDirectory (void) virtual default
Member Function Documentation
Create()
bool CWinLibraryDirectory::Create (const CURL & url) override virtual
Create the directory.
Parameters
url Directory to create.
Returns
Returns true, if directory is created or if it already exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
References CURL::Get(), CURL::GetFileNameWithoutPath(), GetFolder(), URIUtils::GetParentPath(), KODI::PLATFORM::WINDOWS::ToW(), and Wait().
Exists()
bool CWinLibraryDirectory::Exists (const CURL & url) override virtual
Check for directory existence.
Parameters
url Directory to check.
Returns
Returns true, if directory exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
References GetFolder().
GetCacheType()
DIR_CACHE_TYPE XFILE::CWinLibraryDirectory::GetCacheType (const CURL & url) const inline override virtual
How this directory should be cached.
Parameters
url Directory at hand.
Returns
Returns the cache type.
Reimplemented from XFILE::IDirectory.
References XFILE::DIR_CACHE_ONCE.
GetDirectory()
bool CWinLibraryDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References CFileItemList::Add(), URIUtils::AddSlashAtEnd(), CFileItemList::Clear(), KODI::PLATFORM::WINDOWS::FromW(), CURL::Get(), GetFolder(), KODI::TIME::FileTime::highDateTime, int64_t(), KODI::TIME::FileTime::lowDateTime, and Wait().
GetFolder()
StorageFolder CWinLibraryDirectory::GetFolder (const CURL & url) static private
References URIUtils::FixSlashesAndDups(), KODI::PLATFORM::WINDOWS::FromW(), CURL::GetFileName(), CURL::GetRedacted(), GetRootFolder(), LOGERROR, KODI::PLATFORM::WINDOWS::ToW(), and Wait().
Referenced by Create(), Exists(), GetDirectory(), XFILE::CWinLibraryFile::OpenIntenal(), Remove(), XFILE::CWinLibraryFile::Rename(), and StatDirectory().
GetRootFolder()
StorageFolder CWinLibraryDirectory::GetRootFolder (const CURL & url) static private
References KODI::PLATFORM::WINDOWS::FromW(), CURL::GetHostName(), CURL::IsProtocol(), and LOGERROR.
Referenced by XFILE::CWinLibraryFile::GetFile(), and GetFolder().
GetStoragePath()
bool CWinLibraryDirectory::GetStoragePath (std::string library, std::string & path) static
References CURL::Get(), IsValid(), CURL::SetHostName(), and CURL::SetProtocol().
Referenced by CGUIDialogMediaSource::OnPathBrowse().
IsValid()
bool CWinLibraryDirectory::IsValid (const CURL & url) static
References CURL::GetHostName(), and CURL::IsProtocol().
Referenced by XFILE::CDirectoryFactory::Create(), XFILE::CWinLibraryFile::GetFile(), GetStoragePath(), and XFILE::CWinLibraryFile::IsValid().
Remove()
bool CWinLibraryDirectory::Remove (const CURL & url) override virtual
Removes the directory.
Parameters
url Directory to remove.
Returns
Returns false if not successful
Reimplemented from XFILE::IDirectory.
References exists(), KODI::PLATFORM::WINDOWS::FromW(), CURL::Get(), GetFolder(), LOGERROR, and Wait().
StatDirectory()
int CWinLibraryDirectory::StatDirectory (const CURL & url, struct __stat64 * statData) static private
References _S_IFDIR, GetFolder(), and Wait().
Referenced by XFILE::CWinLibraryFile::Stat().
Member Data Documentation
CWinLibraryFile
friend XFILE::CWinLibraryDirectory::CWinLibraryFile private
The documentation for this class was generated from the following files:
WinLibraryDirectory.h
WinLibraryDirectory.cpp