Kodi Documentation: CONTEXTMENU::CVideoQueue Struct Reference
CONTEXTMENU::CVideoQueue Struct Reference
#include <ContextMenus.h>
Public Member Functions
CVideoQueue ()
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Constructor & Destructor Documentation
CVideoQueue()
CONTEXTMENU::CVideoQueue::CVideoQueue () inline
Member Function Documentation
Execute()
bool CONTEXTMENU::CVideoQueue::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and KODI::VIDEO::UTILS::QueueItem().
IsVisible()
bool CONTEXTMENU::CVideoQueue::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References KODI::VIDEO::UTILS::IsItemPlayable().
The documentation for this struct was generated from the following files:
video/ContextMenus.h
video/ContextMenus.cpp