Kodi Documentation: KODI::VIDEO::CVideoInfoTagLoaderFactory Class Reference
KODI::VIDEO::CVideoInfoTagLoaderFactory Class Reference
#include <VideoInfoTagLoaderFactory.h>
Static Public Member Functions
static IVideoInfoTagLoader * CreateLoader (const CFileItem &item, const ADDON::ScraperPtr &info, bool lookInFolder, bool forceRefresh=false)
Returns a tag loader for the given item.
Protected Member Functions
CVideoInfoTagLoaderFactory (void)=delete
virtual ~CVideoInfoTagLoaderFactory ()=delete
Constructor & Destructor Documentation
CVideoInfoTagLoaderFactory()
KODI::VIDEO::CVideoInfoTagLoaderFactory::CVideoInfoTagLoaderFactory (void) protected delete
~CVideoInfoTagLoaderFactory()
virtual KODI::VIDEO::CVideoInfoTagLoaderFactory::~CVideoInfoTagLoaderFactory () protected virtual delete
Member Function Documentation
CreateLoader()
IVideoInfoTagLoader * KODI::VIDEO::CVideoInfoTagLoaderFactory::CreateLoader (const CFileItem & item, const ADDON::ScraperPtr & info, bool lookInFolder, bool forceRefresh = false) static
Returns a tag loader for the given item.
Parameters
item The item to find tag loader for
type Type of tag loader. In particular used for tvshows
References CVideoTagLoaderFFmpeg::HasInfo(), CVideoTagLoaderNFO::HasInfo(), CVideoTagLoaderPlugin::HasInfo(), KODI::VIDEO::TAGS::CVideoTagExtractionHelper::IsExtractionSupportedFor(), and CFileItem::IsPlugin().
Referenced by KODI::VIDEO::anonymous_namespace{VideoEmbeddedImageFileLoader.cpp}::GetEmbeddedThumb(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), and CVideoLibraryRefreshingJob::Work().
The documentation for this class was generated from the following files:
VideoInfoTagLoaderFactory.h
VideoInfoTagLoaderFactory.cpp