Kodi Documentation: ICallbackHWAccel Class Reference
ICallbackHWAccel Class Reference abstract
#include <DVDVideoCodec.h>
Public Member Functions
virtual ~ICallbackHWAccel ()=default
virtual IHardwareDecoder * GetHWAccel ()=0
virtual bool GetPictureCommon (VideoPicture *pVideoPicture)=0
Constructor & Destructor Documentation
~ICallbackHWAccel()
virtual ICallbackHWAccel::~ICallbackHWAccel () virtual default
Member Function Documentation
GetHWAccel()
virtual IHardwareDecoder * ICallbackHWAccel::GetHWAccel () pure virtual
Implemented in CDVDVideoCodecFFmpeg.
Referenced by VAAPI::CDecoder::FFGetBuffer(), VDPAU::CDecoder::FFGetBuffer(), and VDPAU::CDecoder::Render().
GetPictureCommon()
virtual bool ICallbackHWAccel::GetPictureCommon (VideoPicture * pVideoPicture) pure virtual
Implemented in CDVDVideoCodecFFmpeg.
The documentation for this class was generated from the following file:
DVDVideoCodec.h