Kodi Documentation: CFileOperationJob Class Reference
CFileOperationJob Class Reference
#include <FileOperationJob.h>
Classes
class CFileOperation
Public Types
enum FileAction {
ActionCopy = 1 , ActionMove , ActionDelete , ActionReplace ,
ActionCreateFolder , ActionDeleteFolder
}
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Public Member Functions
CFileOperationJob ()
CFileOperationJob (FileAction action, CFileItemList &items, const std::string &strDestFile, bool displayProgress=false, int errorHeading=0, int errorLine=0)
bool DoWork () override
Main workhorse function of CJob instances.
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
void SetFileOperation (FileAction action, const CFileItemList &items, const std::string &strDestFile)
const std::string & GetAverageSpeed () const
const std::string & GetCurrentOperation () const
const std::string & GetCurrentFile () const
const CFileItemList & GetItems () const
FileAction GetAction () const
int GetHeading () const
int GetLine () const
Public Member Functions inherited from CProgressJob
~CProgressJob () override
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
bool ShouldCancel (unsigned int progress, unsigned int total) const override
Function for longer jobs to report progress and check whether they have been cancelled.
bool DoModal ()
Executes the job showing a modal progress dialog.
void SetProgressIndicators (CGUIDialogProgressBarHandle *progressBar, CGUIDialogProgress *progressDialog, bool updateProgress=true, bool updateInformation=true)
Sets the given progress indicators to be used during execution of the job.
bool HasProgressIndicator () const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
Static Public Member Functions
static std::string GetActionString (FileAction action)
Private Types
typedef std::vector< CFileOperation > FileOperationList
Private Member Functions
bool DoProcess (FileAction action, const CFileItemList &items, const std::string &strDestFile, FileOperationList &fileOperations, double &totalTime)
bool DoProcessFolder (FileAction action, const std::string &strPath, const std::string &strDestFile, FileOperationList &fileOperations, double &totalTime)
bool DoProcessFile (FileAction action, const std::string &strFileA, const std::string &strFileB, FileOperationList &fileOperations, double &totalTime)
Static Private Member Functions
static bool CanBeRenamed (const std::string &strFileA, const std::string &strFileB)
Private Attributes
FileAction m_action = ActionCopy
CFileItemList m_items
std::string m_strDestFile
std::string m_avgSpeed
std::string m_currentOperation
std::string m_currentFile
bool m_displayProgress = false
int m_heading = 0
int m_line = 0
Friends
class CFileOperation
Additional Inherited Members
Protected Member Functions inherited from CProgressJob
CProgressJob ()
CProgressJob (CGUIDialogProgressBarHandle *progressBar)
bool IsModal () const
Whether the job is being run modally or in the background.
CGUIDialogProgressBarHandle * GetProgressBar () const
Returns the progress bar indicating the progress of the job.
void SetProgressBar (CGUIDialogProgressBarHandle *progress)
Sets the progress bar indicating the progress of the job.
CGUIDialogProgress * GetProgressDialog () const
Returns the progress dialog indicating the progress of the job.
void SetProgressDialog (CGUIDialogProgress *progressDialog)
Sets the progress bar indicating the progress of the job.
bool GetAutoClose ()
Whether to automatically close the progress indicator in MarkFinished().
void SetAutoClose (bool autoClose)
Set whether to automatically close the progress indicator in MarkFinished().
bool GetUpdateProgress ()
Whether to update the progress bar or not.
void SetUpdateProgress (bool updateProgress)
Set whether to update the progress bar or not.
bool GetUpdateInformation ()
Whether to update the progress information or not.
void SetUpdateInformation (bool updateInformation)
Set whether to update the progress information or not.
void ShowProgressDialog () const
Makes sure that the modal dialog is being shown.
void SetTitle (const std::string &title)
Sets the given title as the title of the progress bar.
void SetText (const std::string &text)
Sets the given text as the description of the progress bar.
void SetProgress (float percentage) const
Sets the progress of the progress bar to the given value in percentage.
void SetProgress (int currentStep, int totalSteps) const
Sets the progress of the progress bar to the given value.
void MarkFinished ()
Marks the progress as finished by setting it to 100%.
bool IsCancelled () const
Checks if the progress dialog has been cancelled.
Member Typedef Documentation
FileOperationList
typedef std::vector<CFileOperation> CFileOperationJob::FileOperationList private
Member Enumeration Documentation
FileAction
enum CFileOperationJob::FileAction
Enumerator
ActionCopy
ActionMove
ActionDelete
ActionReplace
Copy, emptying any existing destination directories first.
ActionCreateFolder
ActionDeleteFolder
Constructor & Destructor Documentation
CFileOperationJob() [1/2]
CFileOperationJob::CFileOperationJob ()
CFileOperationJob() [2/2]
CFileOperationJob::CFileOperationJob (FileAction action, CFileItemList & items, const std::string & strDestFile, bool displayProgress = false, int errorHeading = 0, int errorLine = 0)
References SetFileOperation().
Member Function Documentation
CanBeRenamed()
bool CFileOperationJob::CanBeRenamed (const std::string & strFileA, const std::string & strFileB) inline static private
References CURL::GetHostName(), CURL::GetShareName(), URIUtils::IsHD(), and URIUtils::IsSmb().
Referenced by DoProcessFile(), and CFileOperationJob::CFileOperation::ExecuteOperation().
DoProcess()
bool CFileOperationJob::DoProcess (FileAction action, const CFileItemList & items, const std::string & strDestFile, FileOperationList & fileOperations, double & totalTime) private
References ActionCopy, ActionCreateFolder, ActionDelete, ActionDeleteFolder, ActionReplace, URIUtils::ChangeBasePath(), DoProcessFile(), DoProcessFolder(), XFILE::CDirectory::Exists(), URIUtils::GetExtension(), URIUtils::GetFileName(), CFileItem::GetPath(), URIUtils::HasExtension(), URIUtils::IsUPnP(), CUtil::MakeLegalFileName(), URIUtils::RemoveSlashAtEnd(), and CFileItemList::Size().
Referenced by DoProcessFolder(), and DoWork().
DoProcessFile()
bool CFileOperationJob::DoProcessFile (FileAction action, const std::string & strFileA, const std::string & strFileB, FileOperationList & fileOperations, double & totalTime) private
References __stat64, ActionCopy, ActionMove, ActionReplace, CanBeRenamed(), data(), int64_t(), and XFILE::CFile::Stat().
Referenced by DoProcess().
DoProcessFolder()
bool CFileOperationJob::DoProcessFolder (FileAction action, const std::string & strPath, const std::string & strDestFile, FileOperationList & fileOperations, double & totalTime) private
References ActionDeleteFolder, ActionMove, XFILE::CFileDirectoryFactory::Create(), XFILE::DIR_FLAG_GET_HIDDEN, XFILE::DIR_FLAG_NO_FILE_DIRS, DoProcess(), XFILE::CDirectory::GetDirectory(), CFileItem::GetURL(), CLog::Log(), LOGERROR, CGUIListItem::Select(), and CFileItemList::Size().
Referenced by DoProcess().
DoWork()
bool CFileOperationJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References DoProcess(), GetActionString(), CServiceBroker::GetGUI(), CGUIDialogExtendedProgressBar::GetHandle(), CProgressJob::GetProgressDialog(), CGUIComponent::GetWindowManager(), m_action, m_displayProgress, m_items, m_strDestFile, CProgressJob::MarkFinished(), CProgressJob::SetProgressBar(), success, and WINDOW_DIALOG_EXT_PROGRESS.
Referenced by CFileUtils::DeleteItem(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoFileOperation(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and CFilesystemInstaller::UnpackArchive().
GetAction()
FileAction CFileOperationJob::GetAction () const inline
References m_action.
Referenced by operator==(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetActionString()
std::string CFileOperationJob::GetActionString (FileAction action) static
References ActionCopy, ActionCreateFolder, ActionDelete, ActionDeleteFolder, ActionMove, ActionReplace, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by DoWork(), and CFileOperationJob::CFileOperation::ExecuteOperation().
GetAverageSpeed()
const std::string & CFileOperationJob::GetAverageSpeed () const inline
References m_avgSpeed.
Referenced by TEST().
GetCurrentFile()
const std::string & CFileOperationJob::GetCurrentFile () const inline
References m_currentFile.
Referenced by CFileOperationJob::CFileOperation::ExecuteOperation(), and TEST().
GetCurrentOperation()
const std::string & CFileOperationJob::GetCurrentOperation () const inline
References m_currentOperation.
Referenced by TEST().
GetHeading()
int CFileOperationJob::GetHeading () const inline
References m_heading.
Referenced by CGUIWindowFileManager::OnJobComplete().
GetItems()
const CFileItemList & CFileOperationJob::GetItems () const inline
References m_items.
Referenced by TEST().
GetLine()
int CFileOperationJob::GetLine () const inline
References m_line.
Referenced by CGUIWindowFileManager::OnJobComplete().
GetType()
const char * CFileOperationJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CJob.
References m_displayProgress.
Referenced by operator==().
operator==()
bool CFileOperationJob::operator== (const CJob * job) const override virtual
Reimplemented from CJob.
References GetAction(), CFileItem::GetPath(), CJob::GetType(), GetType(), CGUIListItem::IsSelected(), m_items, m_strDestFile, and CFileItemList::Size().
SetFileOperation()
void CFileOperationJob::SetFileOperation (FileAction action, const CFileItemList & items, const std::string & strDestFile)
References CFileItemList::Add(), CFileItemList::Clear(), m_action, m_items, m_strDestFile, and CFileItemList::Size().
Referenced by CFileOperationJob(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoFileOperation(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
Friends And Related Symbol Documentation
CFileOperation
friend class CFileOperation friend
Member Data Documentation
m_action
FileAction CFileOperationJob::m_action = ActionCopy private
Referenced by DoWork(), CFileOperationJob::CFileOperation::ExecuteOperation(), GetAction(), and SetFileOperation().
m_avgSpeed
std::string CFileOperationJob::m_avgSpeed private
Referenced by GetAverageSpeed().
m_currentFile
std::string CFileOperationJob::m_currentFile private
Referenced by CFileOperationJob::CFileOperation::ExecuteOperation(), and GetCurrentFile().
m_currentOperation
std::string CFileOperationJob::m_currentOperation private
Referenced by CFileOperationJob::CFileOperation::ExecuteOperation(), and GetCurrentOperation().
m_displayProgress
bool CFileOperationJob::m_displayProgress = false private
Referenced by DoWork(), and GetType().
m_heading
int CFileOperationJob::m_heading = 0 private
Referenced by GetHeading().
m_items
CFileItemList CFileOperationJob::m_items private
Referenced by DoWork(), GetItems(), operator==(), and SetFileOperation().
m_line
int CFileOperationJob::m_line = 0 private
Referenced by GetLine().
m_strDestFile
std::string CFileOperationJob::m_strDestFile private
Referenced by DoWork(), operator==(), and SetFileOperation().
The documentation for this class was generated from the following files:
FileOperationJob.h
FileOperationJob.cpp