Kodi Documentation: PVR::IPVRSettingsContainer Class Reference
PVR::IPVRSettingsContainer Class Reference
#include <IPVRSettingsContainer.h>
Public Member Functions
virtual ~IPVRSettingsContainer ()=default
virtual void AddMultiIntSetting (const std::shared_ptr< CSettingGroup > &group, const std::string &settingName, int settingValue)
virtual void AddSingleIntSetting (const std::shared_ptr< CSettingGroup > &group, const std::string &settingName, int settingValue, int minValue, int step, int maxValue)
virtual void AddMultiStringSetting (const std::shared_ptr< CSettingGroup > &group, const std::string &settingName, const std::string &settingValue)
virtual void AddSingleStringSetting (const std::shared_ptr< CSettingGroup > &group, const std::string &settingName, const std::string &settingValue, bool allowEmptyValue)
Constructor & Destructor Documentation
~IPVRSettingsContainer()
virtual PVR::IPVRSettingsContainer::~IPVRSettingsContainer () virtual default
Member Function Documentation
AddMultiIntSetting()
virtual void PVR::IPVRSettingsContainer::AddMultiIntSetting (const std::shared_ptr< CSettingGroup > & group, const std::string & settingName, int settingValue) inline virtual
Reimplemented in PVR::CGUIDialogPVRTimerSettings.
Referenced by PVR::CPVRCustomTimerSettings::AddSettings().
AddMultiStringSetting()
virtual void PVR::IPVRSettingsContainer::AddMultiStringSetting (const std::shared_ptr< CSettingGroup > & group, const std::string & settingName, const std::string & settingValue) inline virtual
Reimplemented in PVR::CGUIDialogPVRTimerSettings.
Referenced by PVR::CPVRCustomTimerSettings::AddSettings().
AddSingleIntSetting()
virtual void PVR::IPVRSettingsContainer::AddSingleIntSetting (const std::shared_ptr< CSettingGroup > & group, const std::string & settingName, int settingValue, int minValue, int step, int maxValue) inline virtual
Reimplemented in PVR::CGUIDialogPVRTimerSettings.
Referenced by PVR::CPVRCustomTimerSettings::AddSettings().
AddSingleStringSetting()
virtual void PVR::IPVRSettingsContainer::AddSingleStringSetting (const std::shared_ptr< CSettingGroup > & group, const std::string & settingName, const std::string & settingValue, bool allowEmptyValue) inline virtual
Reimplemented in PVR::CGUIDialogPVRTimerSettings.
Referenced by PVR::CPVRCustomTimerSettings::AddSettings().
The documentation for this class was generated from the following file:
IPVRSettingsContainer.h