Kodi Documentation: CThumbLoader Class Reference
CThumbLoader Class Reference
#include <ThumbLoader.h>
Public Member Functions
CThumbLoader ()
~CThumbLoader () override
void OnLoaderStart () override
void OnLoaderFinish () override
virtual bool FillLibraryArt (CFileItem &item)
helper function to fill the art for a library item
virtual std::string GetCachedImage (const CFileItem &item, const std::string &type)
Checks whether the given item has an image listed in the texture database.
virtual void SetCachedImage (const CFileItem &item, const std::string &type, const std::string &image)
Associate an image with the given item in the texture database.
Public Member Functions inherited from CBackgroundInfoLoader
CBackgroundInfoLoader ()
~CBackgroundInfoLoader () override
void Load (CFileItemList &items)
bool IsLoading ()
void Run () override
void SetObserver (IBackgroundLoaderObserver *pObserver)
void SetProgressCallback (IProgressCallback *pCallback)
virtual bool LoadItem (CFileItem *pItem)
virtual bool LoadItemCached (CFileItem *pItem)
virtual bool LoadItemLookup (CFileItem *pItem)
void StopThread ()
void StopAsync ()
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Protected Attributes
CTextureDatabase * m_textureDatabase
Protected Attributes inherited from CBackgroundInfoLoader
CFileItemList * m_pVecItems {nullptr}
std::vector< CFileItemPtr > m_vecItems
CCriticalSection m_lock
volatile bool m_bIsLoading {false}
volatile bool m_bStop {true}
CThread * m_thread {nullptr}
IBackgroundLoaderObserver * m_pObserver {nullptr}
IProgressCallback * m_pProgressCallback {nullptr}
Additional Inherited Members
Constructor & Destructor Documentation
CThumbLoader()
CThumbLoader::CThumbLoader ()
References m_textureDatabase.
~CThumbLoader()
CThumbLoader::~CThumbLoader () override
References m_textureDatabase.
Member Function Documentation
FillLibraryArt()
virtual bool CThumbLoader::FillLibraryArt (CFileItem & item) inline virtual
helper function to fill the art for a library item
Parameters
item a CFileItem
Returns
true if we fill art, false otherwise
Reimplemented in CMusicThumbLoader, and CVideoThumbLoader.
Referenced by JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CFileItemHandler::GetField(), and JSONRPC::CAudioLibrary::GetSongs().
GetCachedImage()
std::string CThumbLoader::GetCachedImage (const CFileItem & item, const std::string & type) virtual
Checks whether the given item has an image listed in the texture database.
Parameters
item CFileItem to check
type the type of image to retrieve
Returns
the image associated with this item
References CDatabase::Close(), CFileItem::GetPath(), CTextureDatabase::GetTextureForPath(), m_textureDatabase, and CTextureDatabase::Open().
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), PVR::CPVRThumbLoader::FillThumb(), CProgramThumbLoader::FillThumb(), CVideoThumbLoader::FillThumb(), CMusicThumbLoader::FillThumb(), CMusicThumbLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemCached(), and CGUIWindowPictures::Update().
OnLoaderFinish()
void CThumbLoader::OnLoaderFinish () override virtual
Reimplemented from CBackgroundInfoLoader.
Reimplemented in CVideoThumbLoader.
References CDatabase::Close(), and m_textureDatabase.
Referenced by CMusicThumbLoader::OnLoaderFinish(), CPictureThumbLoader::OnLoaderFinish(), PVR::CPVRThumbLoader::OnLoaderFinish(), and CVideoThumbLoader::OnLoaderFinish().
OnLoaderStart()
void CThumbLoader::OnLoaderStart () override virtual
Reimplemented from CBackgroundInfoLoader.
Reimplemented in CVideoThumbLoader.
References m_textureDatabase, and CTextureDatabase::Open().
Referenced by JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CAudioLibrary::GetSongs(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::CFileItemHandler::HandleFileItemList(), CMusicThumbLoader::OnLoaderStart(), and CVideoThumbLoader::OnLoaderStart().
SetCachedImage()
void CThumbLoader::SetCachedImage (const CFileItem & item, const std::string & type, const std::string & image) virtual
Associate an image with the given item in the texture database.
Parameters
item CFileItem to associate the image with
type the type of image
image the URL of the image
References CDatabase::Close(), CFileItem::GetPath(), m_textureDatabase, CTextureDatabase::Open(), and CTextureDatabase::SetTextureForPath().
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), KODI::VIDEO::CVideoInfoScanner::ApplyThumbToFolder(), PVR::CPVRThumbLoader::FillThumb(), CProgramThumbLoader::FillThumb(), CVideoThumbLoader::FillThumb(), CMusicThumbLoader::FillThumb(), MUSIC_INFO::CMusicInfoScanner::FindArtForAlbums(), and CVideoThumbLoader::LoadItemLookup().
Member Data Documentation
m_textureDatabase
CTextureDatabase* CThumbLoader::m_textureDatabase protected
Referenced by PVR::CPVRThumbLoader::ClearCachedImage(), CThumbLoader(), GetCachedImage(), CPictureThumbLoader::LoadItemCached(), OnLoaderFinish(), OnLoaderStart(), SetCachedImage(), and ~CThumbLoader().
The documentation for this class was generated from the following files:
ThumbLoader.h
ThumbLoader.cpp