Kodi Documentation: PVR::CGUIDialogPVRRadioRDSInfo::InfoControl Class Reference
PVR::CGUIDialogPVRRadioRDSInfo::InfoControl Class Reference
Public Member Functions
InfoControl (uint32_t iSpinLabelId, uint32_t iSpinControlId)
void Init (CGUISpinControl *spin, CGUITextBox *textbox)
bool Update (const std::string &textboxValue)
Private Attributes
CGUISpinControl * m_spinControl = nullptr
uint32_t m_iSpinLabelId = 0
uint32_t m_iSpinControlId = 0
CGUITextBox * m_textbox = nullptr
bool m_bSpinLabelPresent = false
std::string m_textboxValue
Constructor & Destructor Documentation
InfoControl()
CGUIDialogPVRRadioRDSInfo::InfoControl::InfoControl (uint32_t iSpinLabelId, uint32_t iSpinControlId)
Member Function Documentation
Init()
void CGUIDialogPVRRadioRDSInfo::InfoControl::Init (CGUISpinControl * spin, CGUITextBox * textbox)
Referenced by PVR::CGUIDialogPVRRadioRDSInfo::InitInfoControls().
Update()
bool CGUIDialogPVRRadioRDSInfo::InfoControl::Update (const std::string & textboxValue)
References g_localizeStrings, CLocalizeStrings::Get(), and CGUITextBox::SetInfo().
Referenced by PVR::CGUIDialogPVRRadioRDSInfo::UpdateInfoControls().
Member Data Documentation
m_bSpinLabelPresent
bool PVR::CGUIDialogPVRRadioRDSInfo::InfoControl::m_bSpinLabelPresent = false private
m_iSpinControlId
uint32_t PVR::CGUIDialogPVRRadioRDSInfo::InfoControl::m_iSpinControlId = 0 private
m_iSpinLabelId
uint32_t PVR::CGUIDialogPVRRadioRDSInfo::InfoControl::m_iSpinLabelId = 0 private
m_spinControl
CGUISpinControl* PVR::CGUIDialogPVRRadioRDSInfo::InfoControl::m_spinControl = nullptr private
m_textbox
CGUITextBox* PVR::CGUIDialogPVRRadioRDSInfo::InfoControl::m_textbox = nullptr private
m_textboxValue
std::string PVR::CGUIDialogPVRRadioRDSInfo::InfoControl::m_textboxValue private
The documentation for this class was generated from the following files:
GUIDialogPVRRadioRDSInfo.h
GUIDialogPVRRadioRDSInfo.cpp