Kodi Documentation: CDVDDemuxSPU Class Reference
CDVDDemuxSPU Class Reference final
#include <DVDDemuxSPU.h>
Public Member Functions
CDVDDemuxSPU ()
~CDVDDemuxSPU ()
std::shared_ptr< CDVDOverlaySpu > AddData (uint8_t *data, int iSize, double pts)
std::shared_ptr< CDVDOverlaySpu > ParseRLE (std::shared_ptr< CDVDOverlaySpu > pSPU, uint8_t *pUnparsedData)
void Reset ()
void FlushCurrentPacket ()
Static Public Member Functions
static void FindSubtitleColor (int last_color, int stats[4], CDVDOverlaySpu &pSPU)
static bool CanDisplayWithAlphas (const int a[4], const int stats[4])
Public Attributes
uint8_t m_clut [16][3]
bool m_bHasClut
Protected Member Functions
std::shared_ptr< CDVDOverlaySpu > ParsePacket (SPUData *pSPUData)
Protected Attributes
SPUData m_spuData
Constructor & Destructor Documentation
CDVDDemuxSPU()
CDVDDemuxSPU::CDVDDemuxSPU ()
References m_bHasClut, m_clut, and m_spuData.
~CDVDDemuxSPU()
CDVDDemuxSPU::~CDVDDemuxSPU ()
References SPUData::data, and m_spuData.
Member Function Documentation
AddData()
std::shared_ptr< CDVDOverlaySpu > CDVDDemuxSPU::AddData (uint8_t * data, int iSize, double pts)
References ALIGN, SPUData::data, data(), DebugLog(), SPUData::iAllocatedSize, SPUData::iNeededSize, SPUData::iSize, m_spuData, ParsePacket(), and SPUData::pts.
Referenced by CVideoPlayerSubtitle::SendMessage().
CanDisplayWithAlphas()
bool CDVDDemuxSPU::CanDisplayWithAlphas (const int a[4], const int stats[4]) static
Referenced by ParseRLE().
FindSubtitleColor()
void CDVDDemuxSPU::FindSubtitleColor (int last_color, int stats[4], CDVDOverlaySpu & pSPU) static
References CDVDOverlaySpu::alpha, CDVDOverlaySpu::color, and DebugLog().
Referenced by ParseRLE().
FlushCurrentPacket()
void CDVDDemuxSPU::FlushCurrentPacket ()
References SPUData::data, and m_spuData.
Referenced by CVideoPlayerSubtitle::CloseStream(), and Reset().
ParsePacket()
std::shared_ptr< CDVDOverlaySpu > CDVDDemuxSPU::ParsePacket (SPUData * pSPUData) protected
References CHG_COLCON, CMD_END, SPUData::data, DebugLog(), DVD_TIME_BASE, FSTA_DSP, SPUData::iNeededSize, SPUData::iSize, m_bHasClut, m_clut, ParseRLE(), SPUData::pts, SET_COLOR, SET_CONTR, SET_DAREA, SET_DSPXA, STA_DSP, and STP_DSP.
Referenced by AddData().
ParseRLE()
std::shared_ptr< CDVDOverlaySpu > CDVDDemuxSPU::ParseRLE (std::shared_ptr< CDVDOverlaySpu > pSPU, uint8_t * pUnparsedData)
References AddNibble(), CanDisplayWithAlphas(), DebugLog(), FindSubtitleColor(), CLog::Log(), LOGERROR, and LOGINFO.
Referenced by ParsePacket().
Reset()
void CDVDDemuxSPU::Reset ()
References FlushCurrentPacket().
Referenced by CVideoPlayerSubtitle::SendMessage().
Member Data Documentation
m_bHasClut
bool CDVDDemuxSPU::m_bHasClut
Referenced by CDVDDemuxSPU(), CDVDInputStreamNavigator::GetCurrentButtonInfo(), ParsePacket(), and CVideoPlayerSubtitle::SendMessage().
m_clut
uint8_t CDVDDemuxSPU::m_clut[16][3]
Referenced by CDVDDemuxSPU(), CDVDInputStreamNavigator::GetCurrentButtonInfo(), ParsePacket(), and CVideoPlayerSubtitle::SendMessage().
m_spuData
SPUData CDVDDemuxSPU::m_spuData protected
Referenced by AddData(), CDVDDemuxSPU(), FlushCurrentPacket(), and ~CDVDDemuxSPU().
The documentation for this class was generated from the following files:
DVDDemuxSPU.h
DVDDemuxSPU.cpp