Kodi Documentation: CSMB Class Reference
CSMB Class Reference
#include <SMBFile.h>
Public Member Functions
CSMB ()
~CSMB ()
void Init ()
void Deinit ()
bool IsSmbValid () const
void CheckIfIdle ()
void SetActivityTime ()
void AddActiveConnection ()
void AddIdleConnection ()
std::string URLEncode (const std::string &value)
std::string URLEncode (const CURL &url)
DWORD ConvertUnixToNT (int error)
Static Public Member Functions
static CURL GetResolvedUrl (const CURL &url)
Private Attributes
SMBCCTX * m_context
int m_OpenConnections
unsigned int m_IdleTimeout
Static Private Attributes
static bool IsFirstInit = true
Constructor & Destructor Documentation
CSMB()
CSMB::CSMB ()
References m_context, m_IdleTimeout, and m_OpenConnections.
~CSMB()
CSMB::~CSMB ()
References Deinit().
Member Function Documentation
AddActiveConnection()
void CSMB::AddActiveConnection ()
References m_OpenConnections.
Referenced by XFILE::CSMBDirectory::CSMBDirectory(), and XFILE::CSMBFile::CSMBFile().
AddIdleConnection()
void CSMB::AddIdleConnection ()
References m_IdleTimeout, and m_OpenConnections.
Referenced by XFILE::CSMBDirectory::~CSMBDirectory(), and XFILE::CSMBFile::~CSMBFile().
CheckIfIdle()
void CSMB::CheckIfIdle ()
References Deinit(), CLog::Log(), LOGINFO, m_context, m_IdleTimeout, m_OpenConnections, and smb.
Referenced by CApplication::ProcessSlow().
ConvertUnixToNT()
DWORD CSMB::ConvertUnixToNT (int error)
Deinit()
void CSMB::Deinit ()
References m_context.
Referenced by CheckIfIdle(), CApplication::CloseNetworkShares(), CApplication::Stop(), and ~CSMB().
GetResolvedUrl()
CURL CSMB::GetResolvedUrl (const CURL & url) static
References CURL::GetHostName(), CDNSNameCache::Lookup(), and CURL::SetHostName().
Referenced by XFILE::CSMBDirectory::Create(), XFILE::CSMBFile::Delete(), XFILE::CSMBDirectory::Exists(), XFILE::CSMBFile::Exists(), XFILE::CSMBFile::GetAuthenticatedPath(), XFILE::CSMBDirectory::OpenDir(), XFILE::CSMBFile::OpenFile(), XFILE::CSMBFile::OpenForWrite(), XFILE::CSMBDirectory::Remove(), XFILE::CSMBFile::Rename(), and XFILE::CSMBFile::Stat().
Init()
void CSMB::Init ()
References CLog::CanLogComponent(), f, fclose(), CServiceBroker::GetLogging(), CServiceBroker::GetSettingsComponent(), IsFirstInit, LOGSAMBA, m_context, m_IdleTimeout, mkdir(), orig_cache, URIUtils::RemoveSlashAtEnd(), CSettings::SETTING_SMB_LEGACYSECURITY, CSettings::SETTING_SMB_MAXPROTOCOL, CSettings::SETTING_SMB_MINPROTOCOL, CSettings::SETTING_SMB_WINSSERVER, CSettings::SETTING_SMB_WORKGROUP, CSpecialProtocol::TranslatePath(), xb_smbc_auth(), xb_smbc_cache(), and xb_smbc_log().
Referenced by XFILE::CSMBDirectory::Create(), XFILE::CSMBFile::CSMBFile(), XFILE::CSMBFile::Delete(), XFILE::CSMBDirectory::Exists(), XFILE::CSMBFile::Exists(), XFILE::CSMBDirectory::GetDirectory(), XFILE::CSMBDirectory::Open(), XFILE::CSMBFile::OpenFile(), XFILE::CSMBDirectory::Remove(), XFILE::CSMBFile::Rename(), and XFILE::CSMBFile::Stat().
IsSmbValid()
bool CSMB::IsSmbValid () const inline
References m_context.
Referenced by XFILE::CSMBFile::Close(), XFILE::CSMBFile::Delete(), XFILE::CSMBFile::Exists(), XFILE::CSMBDirectory::GetDirectory(), XFILE::CSMBFile::GetPosition(), XFILE::CSMBFile::Open(), XFILE::CSMBDirectory::OpenDir(), XFILE::CSMBFile::OpenFile(), XFILE::CSMBFile::OpenForWrite(), XFILE::CSMBFile::Read(), XFILE::CSMBFile::Rename(), XFILE::CSMBFile::Seek(), XFILE::CSMBFile::Stat(), XFILE::CSMBFile::Stat(), and XFILE::CSMBFile::Write().
SetActivityTime()
void CSMB::SetActivityTime ()
References m_IdleTimeout.
Referenced by XFILE::CSMBFile::Read(), and XFILE::CSMBFile::Seek().
URLEncode() [1/2]
std::string CSMB::URLEncode (const CURL & url)
References CURL::GetDomain(), CURL::GetFileName(), CURL::GetHostName(), CURL::GetPassWord(), CURL::GetPort(), CURL::GetUserName(), CURL::HasPort(), and URLEncode().
URLEncode() [2/2]
std::string CSMB::URLEncode (const std::string & value)
References value.
Referenced by XFILE::CSMBDirectory::Create(), XFILE::CSMBDirectory::Exists(), XFILE::CSMBFile::GetAuthenticatedPath(), XFILE::CSMBDirectory::GetDirectory(), XFILE::CSMBDirectory::OpenDir(), XFILE::CSMBDirectory::Remove(), and URLEncode().
Member Data Documentation
IsFirstInit
bool CSMB::IsFirstInit = true static private
Referenced by Init().
m_context
SMBCCTX* CSMB::m_context private
Referenced by CheckIfIdle(), CSMB(), Deinit(), Init(), and IsSmbValid().
m_IdleTimeout
unsigned int CSMB::m_IdleTimeout private
Referenced by AddIdleConnection(), CheckIfIdle(), CSMB(), Init(), and SetActivityTime().
m_OpenConnections
int CSMB::m_OpenConnections private
Referenced by AddActiveConnection(), AddIdleConnection(), CheckIfIdle(), and CSMB().
The documentation for this class was generated from the following files:
SMBFile.h
SMBFile.cpp