Kodi Documentation: KODI::WINDOWING::X11::CWinSystemX11GLContext Class Reference
KODI::WINDOWING::X11::CWinSystemX11GLContext Class Reference
#include <WinSystemX11GLContext.h>
Classes
struct delete_CVaapiProxy
Public Member Functions
CWinSystemX11GLContext ()=default
~CWinSystemX11GLContext () override
CRenderSystemBase * GetRenderSystem () override
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
void FinishWindowResize (int newWidth, int newHeight) override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
bool DestroyWindowSystem () override
bool DestroyWindow () override
bool IsExtSupported (const char *extension) const override
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
float GetFrameLatencyAdjustment () override
Get time that should be subtracted from the display latency for this frame in milliseconds.
uint64_t GetVblankTiming (uint64_t &msc, uint64_t &interval)
XID GetWindow () const
void * GetGlxContext () const
EGLDisplay GetEGLDisplay () const
EGLSurface GetEGLSurface () const
EGLContext GetEGLContext () const
EGLConfig GetEGLConfig () const
bool BindTextureUploadContext () override
Binds a shared context to the current thread, in order to upload textures asynchronously.
bool UnbindTextureUploadContext () override
Unbinds the shared context.
bool HasContext () override
Checks if a graphics context is already bound to the current thread.
Public Member Functions inherited from KODI::WINDOWING::X11::CWinSystemX11
CWinSystemX11 ()
~CWinSystemX11 () override
const std::string GetName () override
bool InitWindowSystem () override
void UpdateResolutions () override
void ShowOSMouse (bool show) override
void NotifyAppActiveChange (bool bActivated) override
void NotifyAppFocusChange (bool bGaining) override
bool Minimize () override
bool Restore () override
bool Hide () override
bool Show (bool raise=true) override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
bool HasCalibration (const RESOLUTION_INFO &resInfo) override
bool UseLimitedColor () override
std::vector< std::string > GetConnectedOutputs () override
Display * GetDisplay ()
int GetScreen ()
void NotifyXRREvent ()
bool IsCurrentOutput (const std::string &output)
void RecreateWindow ()
int GetCrtc ()
bool MessagePump () override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual bool HasCursor ()
virtual bool HasInertialGestures ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual float GetDisplayLatency ()
Get average display latency.
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
virtual bool CanDoWindowed ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual std::string GetClipboardText (void)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual bool SetHDR (const VideoPicture *videoPicture)
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
virtual bool IsHDRDisplay ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual CHDRCapabilities GetDisplayHDRCapabilities () const
virtual float GetGuiSdrPeakLuminance () const
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
Public Member Functions inherited from CRenderSystemGL
CRenderSystemGL ()
~CRenderSystemGL () override
bool InitRenderSystem () override
bool DestroyRenderSystem () override
bool ResetRenderSystem (int width, int height) override
bool BeginRender () override
bool EndRender () override
void PresentRender (bool rendered, bool videoLayer) override
void InvalidateColorBuffer () override
bool ClearBuffers (KODI::UTILS::COLOR::Color color) override
void SetVSync (bool vsync)
void ResetVSync ()
void SetViewPort (const CRect &viewPort) override
void GetViewPort (CRect &viewPort) override
bool ScissorsCanEffectClipping () override
CRect ClipRectToScissorRect (const CRect &rect) override
void SetScissors (const CRect &rect) override
void ResetScissors () override
void SetDepthCulling (DEPTH_CULLING culling) override
void CaptureStateBlock () override
void ApplyStateBlock () override
void SetCameraPosition (const CPoint &camera, int screenWidth, int screenHeight, float stereoFactor=0.0f) override
void SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view) override
bool SupportsStereo (RENDER_STEREO_MODE mode) const override
bool SupportsNPOT (bool dxt) const override
void Project (float &x, float &y, float &z) override
std::string GetShaderPath (const std::string &filename) override
void GetGLVersion (int &major, int &minor)
void GetGLSLVersion (int &major, int &minor)
void ResetGLErrors ()
void EnableShader (ShaderMethodGL method)
void DisableShader ()
GLint ShaderGetPos ()
GLint ShaderGetCol ()
GLint ShaderGetCoord0 ()
GLint ShaderGetCoord1 ()
GLint ShaderGetDepth ()
GLint ShaderGetUniCol ()
GLint ShaderGetModel ()
GLint ShaderGetMatrix ()
GLint ShaderGetClip ()
GLint ShaderGetCoordStep ()
Public Member Functions inherited from CRenderSystemBase
CRenderSystemBase ()
virtual ~CRenderSystemBase ()
virtual void RestoreViewPort ()
void GetRenderVersion (unsigned int &major, unsigned int &minor) const
const std::string & GetRenderVendor () const
const std::string & GetRenderRenderer () const
const std::string & GetRenderVersionString () const
unsigned int GetMaxTextureSize () const
unsigned int GetMinDXTPitch () const
virtual void ShowSplash (const std::string &message)
Static Public Member Functions
static void Register ()
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Protected Member Functions
bool SetWindow (int width, int height, bool fullscreen, const std::string &output, int *winstate=NULL) override
void PresentRenderImpl (bool rendered) override
void SetVSyncImpl (bool enable) override
bool RefreshGLContext (bool force)
XVisualInfo * GetVisual () override
Protected Member Functions inherited from KODI::WINDOWING::X11::CWinSystemX11
std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl () override
void OnLostDevice ()
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
Protected Member Functions inherited from CRenderSystemGL
void CalculateMaxTexturesize ()
void InitialiseShaders ()
void ReleaseShaders ()
Protected Attributes
CGLContext * m_pGLContext = nullptr
bool m_newGlContext
std::unique_ptr< CVaapiProxy, delete_CVaapiProxy > m_vaapiProxy
Protected Attributes inherited from KODI::WINDOWING::X11::CWinSystemX11
Window m_glWindow = 0
Window m_mainWindow = 0
int m_screen = 0
Display * m_dpy
Cursor m_invisibleCursor = 0
Pixmap m_icon
bool m_bIsRotated
bool m_bWasFullScreenBeforeMinimize
bool m_minimized
bool m_bIgnoreNextFocusMessage
CCriticalSection m_resourceSection
std::vector< IDispResource * > m_resources
bool m_delayDispReset
XbmcThreads::EndTime m_dispResetTimer
std::string m_currentOutput
std::string m_userOutput
bool m_windowDirty
bool m_bIsInternalXrr
int m_MouseX
int m_MouseY
int m_crtc
CWinEventsX11 * m_winEventsX11
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Protected Attributes inherited from CRenderSystemGL
bool m_bVsyncInit = false
int m_width
int m_height
std::string m_RenderExtensions
int m_glslMajor = 0
int m_glslMinor = 0
GLint m_viewPort [4]
std::map< ShaderMethodGL, std::unique_ptr< CGLShader > > m_pShader
ShaderMethodGL m_method = ShaderMethodGL::SM_DEFAULT
GLuint m_vertexArray = GL_NONE
Protected Attributes inherited from CRenderSystemBase
bool m_bRenderCreated
bool m_bVSync
unsigned int m_maxTextureSize
unsigned int m_minDXTPitch
std::string m_RenderRenderer
std::string m_RenderVendor
std::string m_RenderVersion
int m_RenderVersionMinor
int m_RenderVersionMajor
RENDER_STEREO_VIEW m_stereoView = RENDER_STEREO_VIEW_OFF
RENDER_STEREO_MODE m_stereoMode = RENDER_STEREO_MODE_OFF
bool m_limitedColorRange = false
bool m_transferPQ {false}
std::unique_ptr< CGUIImage > m_splashImage
std::unique_ptr< CGUITextLayout > m_splashMessageLayout
Additional Inherited Members
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Constructor & Destructor Documentation
CWinSystemX11GLContext()
KODI::WINDOWING::X11::CWinSystemX11GLContext::CWinSystemX11GLContext () default
~CWinSystemX11GLContext()
CWinSystemX11GLContext::~CWinSystemX11GLContext () override
References m_pGLContext.
Member Function Documentation
BindTextureUploadContext()
bool CWinSystemX11GLContext::BindTextureUploadContext () override virtual
Binds a shared context to the current thread, in order to upload textures asynchronously.
Returns
Return true if a texture upload context exists and the binding succeeds.
Reimplemented from CWinSystemBase.
References BindTextureUploadContext(), and m_pGLContext.
Referenced by BindTextureUploadContext().
CreateNewWindow()
bool CWinSystemX11GLContext::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) override virtual
Reimplemented from KODI::WINDOWING::X11::CWinSystemX11.
References KODI::WINDOWING::X11::CWinSystemX11::CreateNewWindow(), m_pGLContext, name, and CGLContext::QueryExtensions().
CreateWinSystem()
std::unique_ptr< CWinSystemBase > CWinSystemX11GLContext::CreateWinSystem () static
Referenced by Register().
DestroyWindow()
bool CWinSystemX11GLContext::DestroyWindow () override virtual
Reimplemented from KODI::WINDOWING::X11::CWinSystemX11.
References KODI::WINDOWING::X11::CWinSystemX11::DestroyWindow(), CGLContext::Detach(), and m_pGLContext.
DestroyWindowSystem()
bool CWinSystemX11GLContext::DestroyWindowSystem () override virtual
Reimplemented from KODI::WINDOWING::X11::CWinSystemX11.
References CGLContext::Destroy(), KODI::WINDOWING::X11::CWinSystemX11::DestroyWindowSystem(), and m_pGLContext.
FinishWindowResize()
void CWinSystemX11GLContext::FinishWindowResize (int newWidth, int newHeight) override virtual
Reimplemented from KODI::WINDOWING::X11::CWinSystemX11.
References KODI::WINDOWING::X11::CWinSystemX11::FinishWindowResize(), CServiceBroker::GetAppComponents(), m_newGlContext, CApplicationSkinHandling::ReloadSkin(), and CRenderSystemGL::ResetRenderSystem().
GetEGLConfig()
EGLConfig CWinSystemX11GLContext::GetEGLConfig () const
References m_pGLContext.
GetEGLContext()
EGLContext CWinSystemX11GLContext::GetEGLContext () const
References m_pGLContext.
GetEGLDisplay()
EGLDisplay CWinSystemX11GLContext::GetEGLDisplay () const
References m_pGLContext.
GetEGLSurface()
EGLSurface CWinSystemX11GLContext::GetEGLSurface () const
References m_pGLContext.
GetFrameLatencyAdjustment()
float CWinSystemX11GLContext::GetFrameLatencyAdjustment () override virtual
Get time that should be subtracted from the display latency for this frame in milliseconds.
Contrary to GetDisplayLatency, this value is calculated ad-hoc for the frame currently being rendered and not a value that is calculated/ averaged from past frames and their presentation times
Reimplemented from CWinSystemBase.
References CGLContext::GetVblankTiming(), and m_pGLContext.
GetGlxContext()
void * CWinSystemX11GLContext::GetGlxContext () const
References KODI::WINDOWING::X11::GLXGetContext(), and m_pGLContext.
GetRenderSystem()
CRenderSystemBase * KODI::WINDOWING::X11::CWinSystemX11GLContext::GetRenderSystem () inline override virtual
Reimplemented from CWinSystemBase.
GetVblankTiming()
uint64_t CWinSystemX11GLContext::GetVblankTiming (uint64_t & msc, uint64_t & interval)
References CGLContext::GetVblankTiming(), and m_pGLContext.
Referenced by KODI::WINDOWING::X11::CVideoSyncOML::Run().
GetVideoSync()
std::unique_ptr< CVideoSync > CWinSystemX11GLContext::GetVideoSync (CVideoReferenceClock * clock) override virtual
Reimplemented from CWinSystemBase.
References KODI::WINDOWING::X11::GLXVideoSyncCreate(), and m_pGLContext.
GetVisual()
XVisualInfo * CWinSystemX11GLContext::GetVisual () override protected virtual
Implements KODI::WINDOWING::X11::CWinSystemX11.
References KODI::WINDOWING::X11::CWinSystemX11::m_dpy, and KODI::WINDOWING::X11::CWinSystemX11::m_screen.
GetWindow()
XID CWinSystemX11GLContext::GetWindow () const
References KODI::WINDOWING::X11::GLXGetWindow(), and m_pGLContext.
Referenced by KODI::WINDOWING::X11::CVideoSyncGLX::Setup().
HasContext()
bool CWinSystemX11GLContext::HasContext () override virtual
Checks if a graphics context is already bound to the current thread.
Returns
Return true if so.
Reimplemented from CWinSystemBase.
References HasContext(), and m_pGLContext.
Referenced by HasContext().
IsExtSupported()
bool CWinSystemX11GLContext::IsExtSupported (const char * extension) const override virtual
Reimplemented from CRenderSystemGL.
References CGLContext::ExtPrefix(), CGLContext::IsExtSupported(), CRenderSystemGL::IsExtSupported(), and m_pGLContext.
PresentRenderImpl()
void CWinSystemX11GLContext::PresentRenderImpl (bool rendered) override protected virtual
Implements CRenderSystemGL.
References KODI::WINDOWING::X11::CWinSystemX11::m_delayDispReset, KODI::WINDOWING::X11::CWinSystemX11::m_dispResetTimer, m_pGLContext, KODI::WINDOWING::X11::CWinSystemX11::m_resources, KODI::WINDOWING::X11::CWinSystemX11::m_resourceSection, and CGLContext::SwapBuffers().
RefreshGLContext()
bool CWinSystemX11GLContext::RefreshGLContext (bool force) protected
References CDVDFactoryCodec::ClearHWAccels(), VIDEOPLAYER::CRendererFactory::ClearRenderer(), CGLContext::CreatePB(), CRenderSystemGL::DestroyRenderSystem(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppParams(), KODI::WINDOWING::X11::CWinSystemX11::GetDisplay(), KODI::WINDOWING::X11::GLXContextCreate(), CRenderSystemGL::InitRenderSystem(), CWinSystemBase::m_dpms, KODI::WINDOWING::X11::CWinSystemX11::m_dpy, KODI::WINDOWING::X11::CWinSystemX11::m_glWindow, m_newGlContext, m_pGLContext, KODI::WINDOWING::X11::CWinSystemX11::m_screen, m_vaapiProxy, CGLContext::Refresh(), KODI::RETRO::CRPProcessInfoX11::Register(), VIDEOPLAYER::CProcessInfoX11::Register(), CLinuxRendererGL::Register(), CScreenshotSurfaceGL::Register(), KODI::RETRO::CRPProcessInfo::RegisterRendererFactory(), success, CApplicationSkinHandling::UnloadSkin(), KODI::WINDOWING::X11::VaapiProxyConfig(), KODI::WINDOWING::X11::VaapiProxyCreate(), KODI::WINDOWING::X11::VAAPIRegister(), KODI::WINDOWING::X11::VAAPIRegisterRenderGL(), KODI::WINDOWING::X11::VDPAURegister(), and KODI::WINDOWING::X11::VDPAURegisterRender().
Referenced by SetWindow().
Register()
void CWinSystemX11GLContext::Register () static
References CreateWinSystem(), and KODI::WINDOWING::CWindowSystemFactory::RegisterWindowSystem().
Referenced by CPlatformFreebsd::InitStageOne(), and CPlatformLinux::InitStageOne().
ResizeWindow()
bool CWinSystemX11GLContext::ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override virtual
Reimplemented from KODI::WINDOWING::X11::CWinSystemX11.
References CServiceBroker::GetAppComponents(), m_newGlContext, CApplicationSkinHandling::ReloadSkin(), CRenderSystemGL::ResetRenderSystem(), and KODI::WINDOWING::X11::CWinSystemX11::ResizeWindow().
SetFullScreen()
bool CWinSystemX11GLContext::SetFullScreen (bool fullScreen, RESOLUTION_INFO & res, bool blankOtherDisplays) override virtual
Reimplemented from KODI::WINDOWING::X11::CWinSystemX11.
References CServiceBroker::GetAppComponents(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, m_newGlContext, CApplicationSkinHandling::ReloadSkin(), CRenderSystemGL::ResetRenderSystem(), and KODI::WINDOWING::X11::CWinSystemX11::SetFullScreen().
SetVSyncImpl()
void CWinSystemX11GLContext::SetVSyncImpl (bool enable) override protected virtual
Implements CRenderSystemGL.
References m_pGLContext, and CGLContext::SetVSync().
SetWindow()
bool CWinSystemX11GLContext::SetWindow (int width, int height, bool fullscreen, const std::string & output, int * winstate = NULL) override protected virtual
Implements KODI::WINDOWING::X11::CWinSystemX11.
References CGraphicContext::Clear(), CGraphicContext::Flip(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), KODI::WINDOWING::X11::CWinSystemX11::m_bIsInternalXrr, KODI::WINDOWING::X11::CWinSystemX11::m_currentOutput, KODI::WINDOWING::X11::CWinSystemX11::m_delayDispReset, KODI::WINDOWING::X11::CWinSystemX11::m_dpy, KODI::WINDOWING::X11::CWinSystemX11::m_resources, KODI::WINDOWING::X11::CWinSystemX11::m_resourceSection, KODI::WINDOWING::X11::CWinSystemX11::m_windowDirty, RefreshGLContext(), CRenderSystemGL::ResetVSync(), and KODI::WINDOWING::X11::CWinSystemX11::SetWindow().
UnbindTextureUploadContext()
bool CWinSystemX11GLContext::UnbindTextureUploadContext () override virtual
Unbinds the shared context.
Returns
Return true if the texture upload context has been unbound.
Reimplemented from CWinSystemBase.
References m_pGLContext, and UnbindTextureUploadContext().
Referenced by UnbindTextureUploadContext().
Member Data Documentation
m_newGlContext
bool KODI::WINDOWING::X11::CWinSystemX11GLContext::m_newGlContext protected
Referenced by FinishWindowResize(), RefreshGLContext(), ResizeWindow(), and SetFullScreen().
m_pGLContext
CGLContext* KODI::WINDOWING::X11::CWinSystemX11GLContext::m_pGLContext = nullptr protected
Referenced by BindTextureUploadContext(), CreateNewWindow(), DestroyWindow(), DestroyWindowSystem(), GetEGLConfig(), GetEGLContext(), GetEGLDisplay(), GetEGLSurface(), GetFrameLatencyAdjustment(), GetGlxContext(), GetVblankTiming(), GetVideoSync(), GetWindow(), HasContext(), IsExtSupported(), PresentRenderImpl(), RefreshGLContext(), SetVSyncImpl(), UnbindTextureUploadContext(), and ~CWinSystemX11GLContext().
m_vaapiProxy
std::unique_ptr<CVaapiProxy, delete_CVaapiProxy> KODI::WINDOWING::X11::CWinSystemX11GLContext::m_vaapiProxy protected
Referenced by RefreshGLContext().
The documentation for this class was generated from the following files:
WinSystemX11GLContext.h
WinSystemX11GLContext.cpp