Kodi Documentation: KODI::UTILS::MOVING_SPEED::CMovingSpeed Class Reference
KODI::UTILS::MOVING_SPEED::CMovingSpeed Class Reference
Class to calculate the velocity for a motion effect. To ensure it works, the GetUpdatedDistance method must be called at each input received (e.g. continuous key press of same key on the keyboard). The motion effect will stop at the event ID change (different key pressed).
#include <MovingSpeed.h>
Classes
struct EventData
Public Member Functions
void AddEventConfig (uint32_t eventId, float acceleration, float maxVelocity, uint32_t resetTimeout)
Add the configuration for an event.
void AddEventConfig (uint32_t eventId, EventCfg event)
Add the configuration for an event.
void AddEventMapConfig (MapEventConfig &configs)
Add a map of events configuration.
void Reset ()
Reset stored velocity to all events.
void Reset (uint32_t eventId)
Reset stored velocity for a specific event.
float GetUpdatedDistance (uint32_t eventId)
Get the updated distance based on acceleration speed.
float GetUpdatedDistance (EventType eventType)
Get the updated distance based on acceleration speed.
Private Attributes
uint32_t m_currentEventId {0}
std::map< uint32_t, EventData > m_eventsData
Detailed Description
Class to calculate the velocity for a motion effect. To ensure it works, the GetUpdatedDistance method must be called at each input received (e.g. continuous key press of same key on the keyboard). The motion effect will stop at the event ID change (different key pressed).
Member Function Documentation
AddEventConfig() [1/2]
void KODI::UTILS::MOVING_SPEED::CMovingSpeed::AddEventConfig (uint32_t eventId, EventCfg event)
Add the configuration for an event.
Parameters
eventId The id for the event, must be unique
event The event configuration
References m_eventsData.
AddEventConfig() [2/2]
void KODI::UTILS::MOVING_SPEED::CMovingSpeed::AddEventConfig (uint32_t eventId, float acceleration, float maxVelocity, uint32_t resetTimeout)
Add the configuration for an event.
Parameters
eventId The id for the event, must be unique
acceleration Acceleration in pixels per second (px/sec)
maxVelocity Max movement speed, it depends from acceleration value, a suitable value could be (acceleration value)*3. Set 0 to disable it
resetTimeout Resets acceleration speed if idle for specified millisecs
References m_eventsData.
Referenced by AddEventMapConfig(), and CPlayerController::CPlayerController().
AddEventMapConfig()
void KODI::UTILS::MOVING_SPEED::CMovingSpeed::AddEventMapConfig (MapEventConfig & configs)
Add a map of events configuration.
Parameters
configs The map of events configuration where key value is event id,
References AddEventConfig().
Referenced by CGUIMoverControl::CGUIMoverControl(), and CGUIResizeControl::CGUIResizeControl().
GetUpdatedDistance() [1/2]
float KODI::UTILS::MOVING_SPEED::CMovingSpeed::GetUpdatedDistance (EventType eventType) inline
Get the updated distance based on acceleration speed.
Parameters
eventType The event type to handle
Returns
The distance
References GetUpdatedDistance().
GetUpdatedDistance() [2/2]
float KODI::UTILS::MOVING_SPEED::CMovingSpeed::GetUpdatedDistance (uint32_t eventId)
Get the updated distance based on acceleration speed.
Parameters
eventId The id for the event to handle
Returns
The distance
References CTimeUtils::GetFrameTime(), LOGDEBUG, KODI::UTILS::MOVING_SPEED::EventCfg::m_acceleration, KODI::UTILS::MOVING_SPEED::CMovingSpeed::EventData::m_config, m_currentEventId, KODI::UTILS::MOVING_SPEED::CMovingSpeed::EventData::m_currentVelocity, KODI::UTILS::MOVING_SPEED::EventCfg::m_delta, m_eventsData, KODI::UTILS::MOVING_SPEED::CMovingSpeed::EventData::m_lastFrameTime, KODI::UTILS::MOVING_SPEED::EventCfg::m_maxVelocity, KODI::UTILS::MOVING_SPEED::EventCfg::m_resetTimeout, Reset(), and MathUtils::RoundF().
Referenced by GetUpdatedDistance(), CPlayerController::OnAction(), CGUIMoverControl::OnDown(), CGUIResizeControl::OnDown(), CGUIMoverControl::OnLeft(), CGUIResizeControl::OnLeft(), CGUIMoverControl::OnRight(), CGUIResizeControl::OnRight(), CGUIMoverControl::OnUp(), and CGUIResizeControl::OnUp().
Reset() [1/2]
void KODI::UTILS::MOVING_SPEED::CMovingSpeed::Reset ()
Reset stored velocity to all events.
Parameters
event The event configuration
References m_currentEventId, m_eventsData, and Reset().
Referenced by GetUpdatedDistance(), and Reset().
Reset() [2/2]
void KODI::UTILS::MOVING_SPEED::CMovingSpeed::Reset (uint32_t eventId)
Reset stored velocity for a specific event.
Parameters
event The event ID
References LOGWARNING, KODI::UTILS::MOVING_SPEED::CMovingSpeed::EventData::m_currentVelocity, and m_eventsData.
Member Data Documentation
m_currentEventId
uint32_t KODI::UTILS::MOVING_SPEED::CMovingSpeed::m_currentEventId {0} private
Referenced by GetUpdatedDistance(), and Reset().
m_eventsData
std::map<uint32_t, EventData> KODI::UTILS::MOVING_SPEED::CMovingSpeed::m_eventsData private
Referenced by AddEventConfig(), AddEventConfig(), GetUpdatedDistance(), Reset(), and Reset().
The documentation for this class was generated from the following files:
MovingSpeed.h
MovingSpeed.cpp