Kodi Documentation: CEGLAttributes< AttributeCount > Class Template Reference
CEGLAttributes< AttributeCount > Class Template Reference
#include <EGLUtils.h>
Classes
struct EGLAttribute
Public Member Functions
CEGLAttributes ()
void Add (std::initializer_list< EGLAttribute > const &attributes)
void Add (EGLAttribute const &attribute)
EGLint const * Get () const
int Size () const
Private Attributes
std::array< EGLint, AttributeCount *2+1 > m_attributes
int m_writePosition {}
Detailed Description
template<std::size_t AttributeCount>
class CEGLAttributes< AttributeCount >
Convenience wrapper for stack-allocated EGL attribute arrays
The wrapper makes sure that the key/value pairs are always written in actual pairs, that the array is always terminated with EGL_NONE, and that the bounds of the array are not exceeded (checked on runtime).
Template Parameters
AttributeCount maximum number of attributes that can be added. Determines the size of the storage array.
Constructor & Destructor Documentation
CEGLAttributes()
template<std::size_t AttributeCount> CEGLAttributes< AttributeCount >::CEGLAttributes () inline
References CEGLAttributes< AttributeCount >::m_attributes.
Member Function Documentation
Add() [1/2]
template<std::size_t AttributeCount> void CEGLAttributes< AttributeCount >::Add (EGLAttribute const & attribute) inline
Add one attribute
The array is automatically terminated with EGL_NONE
Exceptions
std::out_of_range if more than AttributeCount attributes are added in total
References CEGLAttributes< AttributeCount >::Add().
Add() [2/2]
template<std::size_t AttributeCount> void CEGLAttributes< AttributeCount >::Add (std::initializer_list< EGLAttribute > const & attributes) inline
Add multiple attributes
The array is automatically terminated with EGL_NONE
Exceptions
std::out_of_range if more than AttributeCount attributes are added in total
References CEGLAttributes< AttributeCount >::m_attributes, and CEGLAttributes< AttributeCount >::m_writePosition.
Referenced by CEGLAttributes< AttributeCount >::Add(), CEGLImage::CreateImage(), and VAAPI::CVaapi2Texture::Map().
Get()
template<std::size_t AttributeCount> EGLint const * CEGLAttributes< AttributeCount >::Get () const inline
References CEGLAttributes< AttributeCount >::m_attributes.
Referenced by CEGLImage::CreateImage(), and VAAPI::CVaapi2Texture::Map().
Size()
template<std::size_t AttributeCount> int CEGLAttributes< AttributeCount >::Size () const inline
References CEGLAttributes< AttributeCount >::m_writePosition.
Referenced by CEGLImage::CreateImage().
Member Data Documentation
m_attributes
template<std::size_t AttributeCount> std::array<EGLint, AttributeCount * 2 + 1> CEGLAttributes< AttributeCount >::m_attributes private
Referenced by CEGLAttributes< AttributeCount >::Add(), CEGLAttributes< AttributeCount >::CEGLAttributes(), and CEGLAttributes< AttributeCount >::Get().
m_writePosition
template<std::size_t AttributeCount> int CEGLAttributes< AttributeCount >::m_writePosition {} private
Referenced by CEGLAttributes< AttributeCount >::Add(), and CEGLAttributes< AttributeCount >::Size().
The documentation for this class was generated from the following file:
EGLUtils.h