Kodi Documentation: CVariant Class Reference
CVariant Class Reference
#include <Variant.h>
Classes
struct ConstNull
struct Null
Public Types
enum VariantType {
VariantTypeNull , VariantTypeConstNull , VariantTypeInteger , VariantTypeUnsignedInteger ,
VariantTypeBoolean , VariantTypeDouble , VariantTypeString , VariantTypeWideString ,
VariantTypeArray , VariantTypeObject
}
typedef VariantArray::iterator iterator_array
typedef VariantArray::const_iterator const_iterator_array
typedef VariantMap::iterator iterator_map
typedef VariantMap::const_iterator const_iterator_map
Public Member Functions
CVariant ()
CVariant (VariantType type)
CVariant (int integer)
CVariant (int64_t integer)
CVariant (unsigned int unsignedinteger)
CVariant (uint64_t unsignedinteger)
CVariant (double value)
CVariant (float value)
CVariant (bool boolean)
CVariant (const char *str)
CVariant (const char *str, unsigned int length)
CVariant (const std::string &str)
CVariant (std::string &&str)
CVariant (const wchar_t *str)
CVariant (const wchar_t *str, unsigned int length)
CVariant (const std::wstring &str)
CVariant (std::wstring &&str)
CVariant (const std::vector< std::string > &strArray)
CVariant (std::vector< std::string > &&strArray)
CVariant (const std::map< std::string, std::string > &strMap)
CVariant (std::map< std::string, std::string > &&strMap)
CVariant (const std::map< std::string, CVariant > &variantMap)
CVariant (std::map< std::string, CVariant > &&variantMap)
CVariant (const CVariant &variant)
CVariant (CVariant &&rhs) noexcept
~CVariant ()
bool isInteger () const
bool isSignedInteger () const
bool isUnsignedInteger () const
bool isBoolean () const
bool isString () const
bool isWideString () const
bool isDouble () const
bool isArray () const
bool isObject () const
bool isNull () const
VariantType type () const
int64_t asInteger (int64_t fallback=0) const
int32_t asInteger32 (int32_t fallback=0) const
uint64_t asUnsignedInteger (uint64_t fallback=0u) const
uint32_t asUnsignedInteger32 (uint32_t fallback=0u) const
bool asBoolean (bool fallback=false) const
std::string asString (std::string_view="") const &
std::string asString (std::string_view="") &&
std::wstring asWideString (std::wstring_view=L"") const &
std::wstring asWideString (std::wstring_view=L"") &&
double asDouble (double fallback=0.0) const
float asFloat (float fallback=0.0f) const
CVariant & operator[] (const std::string &key) &
const CVariant & operator[] (const std::string &key) const &
CVariant operator[] (const std::string &key) &&
CVariant & operator[] (unsigned int position) &
const CVariant & operator[] (unsigned int position) const &
CVariant operator[] (unsigned int position) &&
CVariant & operator= (const CVariant &rhs)
CVariant & operator= (CVariant &&rhs) noexcept
bool operator== (const CVariant &rhs) const
bool operator!= (const CVariant &rhs) const
void reserve (size_t length)
void push_back (const CVariant &variant)
void push_back (CVariant &&variant)
void append (const CVariant &variant)
void append (CVariant &&variant)
const char * c_str () const
void swap (CVariant &rhs) noexcept
iterator_array begin_array ()
const_iterator_array begin_array () const
iterator_array end_array ()
const_iterator_array end_array () const
iterator_map begin_map ()
const_iterator_map begin_map () const
iterator_map end_map ()
const_iterator_map end_map () const
unsigned int size () const
bool empty () const
void clear ()
void erase (const std::string &key)
void erase (unsigned int position)
bool isMember (const std::string &key) const
Static Public Attributes
static CVariant ConstNullVariant = CVariant::VariantTypeConstNull
Private Types
typedef std::vector< CVariant > VariantArray
typedef std::map< std::string, CVariant > VariantMap
Private Member Functions
void cleanup ()
Private Attributes
std::variant< Null, ConstNull, int64_t, uint64_t, bool, double, std::string, std::wstring, VariantArray, VariantMap > m_data
Static Private Attributes
static VariantArray EMPTY_ARRAY
static VariantMap EMPTY_MAP
Member Typedef Documentation
const_iterator_array
typedef VariantArray::const_iterator CVariant::const_iterator_array
const_iterator_map
typedef VariantMap::const_iterator CVariant::const_iterator_map
iterator_array
typedef VariantArray::iterator CVariant::iterator_array
iterator_map
typedef VariantMap::iterator CVariant::iterator_map
VariantArray
typedef std::vector<CVariant> CVariant::VariantArray private
VariantMap
typedef std::map<std::string, CVariant> CVariant::VariantMap private
Member Enumeration Documentation
VariantType
enum CVariant::VariantType
Enumerator
VariantTypeNull
VariantTypeConstNull
VariantTypeInteger
VariantTypeUnsignedInteger
VariantTypeBoolean
VariantTypeDouble
VariantTypeString
VariantTypeWideString
VariantTypeArray
VariantTypeObject
Constructor & Destructor Documentation
CVariant() [1/25]
CVariant::CVariant ()
CVariant() [2/25]
CVariant::CVariant (VariantType type)
References int64_t(), m_data, type(), VariantTypeArray, VariantTypeBoolean, VariantTypeConstNull, VariantTypeDouble, VariantTypeInteger, VariantTypeNull, VariantTypeObject, VariantTypeString, VariantTypeUnsignedInteger, and VariantTypeWideString.
CVariant() [3/25]
CVariant::CVariant (int integer)
CVariant() [4/25]
CVariant::CVariant (int64_t integer)
CVariant() [5/25]
CVariant::CVariant (unsigned int unsignedinteger)
CVariant() [6/25]
CVariant::CVariant (uint64_t unsignedinteger)
CVariant() [7/25]
CVariant::CVariant (double value)
CVariant() [8/25]
CVariant::CVariant (float value)
CVariant() [9/25]
CVariant::CVariant (bool boolean)
CVariant() [10/25]
CVariant::CVariant (const char * str)
CVariant() [11/25]
CVariant::CVariant (const char * str, unsigned int length)
CVariant() [12/25]
CVariant::CVariant (const std::string & str)
CVariant() [13/25]
CVariant::CVariant (std::string && str)
CVariant() [14/25]
CVariant::CVariant (const wchar_t * str)
CVariant() [15/25]
CVariant::CVariant (const wchar_t * str, unsigned int length)
CVariant() [16/25]
CVariant::CVariant (const std::wstring & str)
CVariant() [17/25]
CVariant::CVariant (std::wstring && str)
CVariant() [18/25]
CVariant::CVariant (const std::vector< std::string > & strArray)
References m_data.
CVariant() [19/25]
CVariant::CVariant (std::vector< std::string > && strArray)
References m_data.
CVariant() [20/25]
CVariant::CVariant (const std::map< std::string, std::string > & strMap)
References m_data.
CVariant() [21/25]
CVariant::CVariant (std::map< std::string, std::string > && strMap)
References m_data.
CVariant() [22/25]
CVariant::CVariant (const std::map< std::string, CVariant > & variantMap)
CVariant() [23/25]
CVariant::CVariant (std::map< std::string, CVariant > && variantMap)
CVariant() [24/25]
CVariant::CVariant (const CVariant & variant)
CVariant() [25/25]
CVariant::CVariant (CVariant && rhs) noexcept
~CVariant()
CVariant::~CVariant ()
References cleanup().
Member Function Documentation
append() [1/2]
void CVariant::append (const CVariant & variant)
References push_back().
Referenced by JSONRPC::CPVROperations::FillChannelGroupDetails(), JSONRPC::CAddonsOperations::FillDetails(), JSONRPC::CPlayerOperations::GetActivePlayers(), CMusicDatabase::GetAlbumsByWhereJSON(), JSONRPC::CAudioLibrary::GetArtistDetails(), CMusicDatabase::GetArtistsByWhereJSON(), JSONRPC::CAudioLibrary::GetAvailableArt(), JSONRPC::CVideoLibrary::GetAvailableArt(), JSONRPC::CAudioLibrary::GetAvailableArtTypes(), JSONRPC::CVideoLibrary::GetAvailableArtTypes(), JSONRPC::CPVROperations::GetClients(), JSONRPC::CFileOperations::GetDirectory(), JSONRPC::CFavouritesOperations::GetFavourites(), JSONRPC::CFileOperations::GetFileDetails(), JSONRPC::CPlaylistOperations::GetPlaylists(), JSONRPC::CApplicationOperations::GetPropertyValue(), JSONRPC::CPlayerOperations::GetPropertyValue(), JSONRPC::CFileOperations::GetRootDirectory(), CMusicDatabase::GetSongsByWhereJSON(), JSONRPC::CAudioLibrary::GetSources(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::CJSONRPC::MethodCall(), JSONRPC::JSONSchemaTypeDefinition::Print(), JSONRPC::CJSONServiceDescription::Print(), JSONRPC::CJSONUtils::SchemaValueTypeToJson(), and TEST().
append() [2/2]
void CVariant::append (CVariant && variant)
References push_back().
asBoolean()
bool CVariant::asBoolean (bool fallback = false) const
References int64_t(), and m_data.
Referenced by CGUIViewState::AddPlaylistOrder(), CDVDInputStream::CDVDInputStream(), CUPowerSource::CUPowerSource(), ADDON::DetailsFromFileItem< CAlbum >(), CVideoThumbLoader::FillLibraryArt(), ADDON::Interface_GUIWindow::get_property_bool(), JSONRPC::CAddonsOperations::GetAddons(), JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CAudioLibrary::GetArtists(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), CGUIWindowVideoBase::GetGroupedItems(), CGUIInfoManager::GetMultiInfoBool(), PVR::CPVRPlaybackState::GetNextAutoplayItem(), XFILE::CPluginDirectory::GetPluginResult(), XFILE::CPluginDirectory::GetResolvedPluginResult(), JSONRPC::CAudioLibrary::GetSongs(), CPlayerUtils::IsItemPlayable(), KODI::PLAYLIST::IsSmartPlayList(), CONTEXTMENU::CAddRemoveFavourite::IsVisible(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), CXBMCApp::KeepScreenOnCallback(), KODI::PLAYLIST::CSmartPlaylist::Load(), CMusicThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), JSONRPC::CProfilesOperations::LoadProfile(), CGUIWindowVideoBase::LoadVideoInfo(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), JSONRPC::CPlayerOperations::Open(), CVideoPlayer::OpenInputStream(), PVR::CPVRGUIActionsPlayback::PlayMedia(), JSONRPC::CPlayerOperations::PlayPause(), JSONRPC::CVideoLibrary::RefreshEpisode(), JSONRPC::CVideoLibrary::RefreshMovie(), JSONRPC::CVideoLibrary::RefreshMusicVideo(), JSONRPC::CVideoLibrary::RefreshTVShow(), JSONRPC::CAddonsOperations::SetAddonEnabled(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CApplicationOperations::SetMute(), JSONRPC::CPlayerOperations::SetShuffle(), JSONRPC::CSettingsOperations::SetSkinSettingValue(), JSONRPC::CPlayerOperations::SetViewMode(), CGUIMediaWindow::SortItems(), TEST(), TEST(), JSONRPC::CPVROperations::ToggleTimer(), CUDiskDevice::Update(), CLogindUPowerSyscall::UpdateBatteryLevel(), and CUPowerSyscall::UpdateCapabilities().
asDouble()
double CVariant::asDouble (double fallback = 0.0) const
References int64_t(), m_data, and str2uint64().
Referenced by asFloat(), JSONRPC::JSONSchemaTypeDefinition::Check(), ADDON::FromFileItem< CScraperUrl >(), ADDON::Interface_GUIWindow::get_property_double(), GetNewValueForViewModeParameter(), CGUIListItem::IncrementProperty(), CApplication::PlayFile(), JSONRPC::CPlayerOperations::SetAudioDelay(), TEST(), TEST(), CUPowerSource::Update(), and CLogindUPowerSyscall::UpdateBatteryLevel().
asFloat()
float CVariant::asFloat (float fallback = 0.0f) const
References asDouble().
Referenced by ADDON::DetailsFromFileItem< CAlbum >(), ADDON::FromFileItem< CMusicAlbumInfo >(), CGUIDialogMediaFilter::InitializeSettings(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetSongDetails(), JSONRPC::CPlayerOperations::SetTempo(), CGUIDialogAudioSettings::SettingFormatterDelay(), CGUIDialogSubtitleSettings::SettingFormatterDelay(), and TEST().
asInteger()
int64_t CVariant::asInteger (int64_t fallback = 0) const
References int64_t(), m_data, and str2int64().
Referenced by CGUIViewState::AddPlaylistOrder(), AnnounceBridge(), asInteger32(), JSONRPC::CInputOperations::ButtonEvent(), ByArtistThenYear(), ByEpisodeNumber(), BySeason(), JSONRPC::CVideoLibrary::FillFileItemList(), ADDON::Interface_GUIWindow::get_property_int(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), ADDON::CScraper::GetEpisodeList(), JSONRPC::CFileItemHandler::GetField(), CGUIDialogBoxBase::GetLocalized(), JSONRPC::CVideoLibrary::GetMovies(), CGUIInfoManager::GetMultiInfoInt(), JSONRPC::CVideoLibrary::GetMusicVideos(), CDVDInputStreamFFmpeg::GetProxyPort(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), JSONRPC::CPlayerOperations::GoTo(), JSONRPC::CVideoLibrary::HandleItems(), CGUIListItem::IncrementProperty(), CGUIListItem::IncrementProperty(), CGUIDialogMediaFilter::InitializeSettings(), CFileItem::IsResumable(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CDVDDemuxFFmpeg::Open(), CApplication::PlayMedia(), JSONRPC::CVideoLibrary::RefreshMovie(), JSONRPC::CVideoLibrary::RefreshMusicVideo(), JSONRPC::CVideoLibrary::RefreshTVShow(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CPlayerOperations::SetAudioStream(), CXBMCApp::SetDisplayModeCallback(), JSONRPC::CFileOperations::SetFileDetails(), CGUIEditControl::SetInputType(), JSONRPC::CAudioLibrary::SetSongDetails(), JSONRPC::CPlayerOperations::SetSubtitle(), JSONRPC::CPlayerOperations::SetVideoStream(), CXBMCApp::SetViewBackgroundColorCallback(), JSONRPC::CApplicationOperations::SetVolume(), CGUIKeyboardFactory::ShowAndGetInput(), CGUIMediaWindow::SortItems(), TEST(), TEST(), TEST_F(), JSONRPC::CVideoLibrary::UpdateVideoTag(), and JSONRPC::CPlayerOperations::Zoom().
asInteger32()
int32_t CVariant::asInteger32 (int32_t fallback = 0) const
References asInteger().
Referenced by ADDON::DetailsFromFileItem< CAlbum >(), ADDON::DetailsFromFileItem< CArtist >(), JSONRPC::CAudioLibrary::GetAvailableArt(), JSONRPC::CVideoLibrary::GetAvailableArt(), JSONRPC::CAudioLibrary::GetAvailableArtTypes(), JSONRPC::CVideoLibrary::GetAvailableArtTypes(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), CMusicDatabase::GetDiscsCount(), JSONRPC::CPlayerOperations::GetPlayer(), JSONRPC::CPlayerOperations::Open(), and CGUIDialogMusicInfo::ShowFor().
asString() [1/2]
std::string CVariant::asString (std::string_view fallback = "") &&
asString() [2/2]
std::string CVariant::asString (std::string_view fallback = "") const &
References int64_t().
Referenced by JSONRPC::CFavouritesOperations::AddFavourite(), JSONRPC::CPlayerOperations::AddSubtitle(), CGUIWindow::AllocResources(), AnnounceBridge(), CExecString::BuildPlayMedia(), JSONRPC::CInputOperations::ButtonEvent(), ByArtist(), ByArtistThenYear(), ByOrigDate(), ByYear(), JSONRPC::CPlaylistOperations::CheckMediaParameter(), JSONRPC::CVideoLibrary::Clean(), CDVDFactoryInputStream::CreateInputStream(), XFILE::DependencyAddons(), CDirectoryJob::DoWork(), CSaveFileState::DoWork(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), JSONRPC::CAddonsOperations::ExecuteAddon(), XFILE::CShoutcastFile::ExtractTagInfo(), JSONRPC::CAddonsOperations::FillDetails(), JSONRPC::CAudioLibrary::FillFileItemList(), JSONRPC::CFileItemHandler::FillFileItemList(), JSONRPC::CFileOperations::FillFileItemList(), JSONRPC::CVideoLibrary::FillFileItemList(), CGUIMediaWindow::Filter(), ADDON::FromArray(), ADDON::FromFileItem< CMusicAlbumInfo >(), ADDON::FromFileItem< CMusicArtistInfo >(), ADDON::FromString(), ADDON::Interface_GUIWindow::get_property(), JSONRPC::CAddonsOperations::GetAddonDetails(), JSONRPC::CAudioLibrary::GetAvailableArt(), JSONRPC::CVideoLibrary::GetAvailableArt(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), JSONRPC::CSettingsOperations::GetCategories(), JSONRPC::CVideoLibrary::GetDetailsFromJsonParameters(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectory(), JSONRPC::CFileOperations::GetDirectory(), JSONRPC::CFavouritesOperations::GetFavourites(), JSONRPC::CFileOperations::GetFileDetails(), JSONRPC::CVideoLibrary::GetGenres(), CGUIWindowVideoBase::GetGroupedItems(), JSONRPC::CXBMCOperations::GetInfoBooleans(), JSONRPC::CXBMCOperations::GetInfoLabels(), XFILE::IDirectory::GetKeyboardInput(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CGUIDialogBoxBase::GetLocalized(), CWeatherManager::GetLocation(), CLabelFormatter::GetMaskContent(), JSONRPC::CVideoLibrary::GetMovies(), CGUIInfoManager::GetMultiInfoItemLabel(), anonymous_namespace{MusicUtils.cpp}::GetMusicDbItemPath(), JSONRPC::CVideoLibrary::GetMusicVideos(), CURL::GetOption(), CPlayerCoreFactory::GetPlayers(), JSONRPC::CPlayerOperations::GetPlayers(), KODI::GAME::CDialogGameVideoFilter::GetProperties(), JSONRPC::CApplicationOperations::GetProperties(), JSONRPC::CGUIOperations::GetProperties(), JSONRPC::CPlayerOperations::GetProperties(), JSONRPC::CPlaylistOperations::GetProperties(), JSONRPC::CPVROperations::GetProperties(), JSONRPC::CSystemOperations::GetProperties(), XBMCAddon::xbmcgui::Window::getProperty(), CURL::GetProtocolOption(), CDVDInputStreamFFmpeg::GetProxyHost(), CDVDInputStreamFFmpeg::GetProxyPassword(), CDVDInputStreamFFmpeg::GetProxyType(), CDVDInputStreamFFmpeg::GetProxyUser(), JSONRPC::CFileOperations::GetRootDirectory(), JSONRPC::CSettingsOperations::GetSections(), JSONRPC::CSettingsOperations::GetSettings(), JSONRPC::CSettingsOperations::GetSettingValue(), JSONRPC::CSettingsOperations::GetSkinSettingValue(), JSONRPC::CVideoLibrary::GetTags(), CDirectoryProvider::GetTarget(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::GetTargetWindowID(), JSONRPC::CTextureOperations::GetTextures(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::GetVideoDbItemPath(), JSONRPC::CPlayerOperations::GoTo(), JSONRPC::CJSONRPC::HandleMethodCall(), CUDisks2Provider::Initialize(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), KODI::PLAYLIST::CSmartPlaylist::Load(), JSONRPC::CProfilesOperations::LoadProfile(), JSONRPC::CPlayerOperations::Move(), CGUIMediaWindow::OnFilterItems(), KODI::GAME::CDialogGameSaves::OnFocus(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), CGUIMediaWindow::OnMessage(), KODI::GAME::CDialogInGameSaves::OnOverwrite(), CInputStreamAddon::Open(), JSONRPC::CPlayerOperations::Open(), CVideoPlayer::OpenInputStream(), ParseItem(), JSONRPC::CPlayerOperations::ParseRepeatState(), JSONRPC::CJSONUtils::ParseSorting(), CApplication::PlayFile(), PVR::CPVRGUIActionsPlayback::PlayRecording(), JSONRPC::CFileOperations::PrepareDownload(), CGUIWindowDebugInfo::Process(), XFILE::IDirectory::ProcessRequirements(), JSONRPC::CVideoLibrary::RefreshEpisode(), JSONRPC::CVideoLibrary::RefreshMovie(), JSONRPC::CVideoLibrary::RefreshMusicVideo(), JSONRPC::CVideoLibrary::RefreshTVShow(), JSONRPC::CSettingsOperations::ResetSettingValue(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), UPNP::CMediaBrowser::SaveFileState(), JSONRPC::CAudioLibrary::Scan(), JSONRPC::CVideoLibrary::Scan(), JSONRPC::CPlayerOperations::Seek(), JSONRPC::CAddonsOperations::SetAddonEnabled(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetArtistDetails(), JSONRPC::CPlayerOperations::SetAudioStream(), JSONRPC::CFileOperations::SetFileDetails(), JSONRPC::CJSONUtils::SetFromDBDate(), JSONRPC::CJSONUtils::SetFromDBDateTime(), CWeatherJob::SetFromProperties(), CGUIEditControl::SetInputType(), CVideoDatabase::SetPlayCount(), JSONRPC::CSettingsOperations::SetSettingValue(), JSONRPC::CPlayerOperations::SetShuffle(), JSONRPC::CSettingsOperations::SetSkinSettingValue(), JSONRPC::CAudioLibrary::SetSongDetails(), JSONRPC::CPlayerOperations::SetSubtitle(), JSONRPC::CPlayerOperations::SetVideoStream(), JSONRPC::CPlayerOperations::SetViewMode(), JSONRPC::CApplicationOperations::SetVolume(), CGUIKeyboardFactory::ShowAndGetInput(), JSONRPC::CGUIOperations::ShowNotification(), CGUIDialogSimpleMenu::ShowPlaySelection(), CInputStreamAddon::Supports(), TEST(), TEST(), TEST_F(), CFileItem::ToSortable(), CUDiskDevice::Update(), CGUIMediaWindow::UpdateFilterPath(), KODI::GAME::CGUIGameControllerList::UpdateInfo(), KODI::GAME::CGUIGameController::UpdateInfo(), ADDON::CAddonDatabase::UpdateTables(), JSONRPC::CVideoLibrary::UpdateVideoTag(), and JSONRPC::CPlayerOperations::Zoom().
asUnsignedInteger()
uint64_t CVariant::asUnsignedInteger (uint64_t fallback = 0u) const
References int64_t(), m_data, and str2uint64().
Referenced by asUnsignedInteger32(), KODI::PLAYLIST::CSmartPlaylist::Load(), TEST(), and CUDiskDevice::Update().
asUnsignedInteger32()
uint32_t CVariant::asUnsignedInteger32 (uint32_t fallback = 0u) const
References asUnsignedInteger().
asWideString() [1/2]
std::wstring CVariant::asWideString (std::wstring_view fallback = L"") &&
asWideString() [2/2]
std::wstring CVariant::asWideString (std::wstring_view fallback = L"") const &
References int64_t().
Referenced by TEST().
begin_array() [1/2]
CVariant::iterator_array CVariant::begin_array ()
References EMPTY_ARRAY, and m_data.
Referenced by JSONRPC::CAudioLibrary::CheckForAdditionalProperties(), JSONRPC::CJSONUtils::CopyStringArray(), JSONRPC::CAddonsOperations::ExecuteAddon(), JSONRPC::CVideoLibrary::GetDetailsFromJsonParameters(), JSONRPC::CTextureOperations::GetTextures(), JSONRPC::CPlaylistOperations::HandleItemsParameter(), CDatabaseQueryRuleCombination::Load(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), JSONRPC::CJSONRPC::MethodCall(), CMusicDatabase::SetPropertiesForFileItem(), and TEST().
begin_array() [2/2]
CVariant::const_iterator_array CVariant::begin_array () const
References EMPTY_ARRAY, and m_data.
begin_map() [1/2]
CVariant::iterator_map CVariant::begin_map ()
References EMPTY_MAP, and m_data.
Referenced by JSONRPC::CAddonsOperations::ExecuteAddon(), JSONRPC::CTextureOperations::GetTextures(), JSONRPC::CJSONServiceDescription::prepareDescription(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetArtistDetails(), JSONRPC::CAudioLibrary::SetSongDetails(), TEST(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
begin_map() [2/2]
CVariant::const_iterator_map CVariant::begin_map () const
References EMPTY_MAP, and m_data.
c_str()
const char * CVariant::c_str () const
References m_data.
Referenced by JSONRPC::JSONSchemaTypeDefinition::Check(), and TEST().
cleanup()
void CVariant::cleanup () private
References m_data.
Referenced by operator=(), and ~CVariant().
clear()
void CVariant::clear ()
References m_data.
Referenced by JSONRPC::CJSONServiceDescription::Cleanup(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetGenresJSON(), XFILE::IDirectory::GetKeyboardInput(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSources(), XFILE::IDirectory::ProcessRequirements(), XFILE::IDirectory::RequireAuthentication(), KODI::PLAYLIST::CSmartPlaylist::Save(), CStreamDetails::Serialize(), XFILE::IDirectory::SetErrorDialog(), and TEST().
empty()
bool CVariant::empty () const
References m_data.
Referenced by CGUIWindowMusicNav::AddSearchFolder(), JSONRPC::CAudioLibrary::CheckForAdditionalProperties(), JSONRPC::CAddonsOperations::ExecuteAddon(), JSONRPC::CFileItemHandler::FillDetails(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), JSONRPC::CSettingsOperations::GetCategories(), JSONRPC::CFileItemHandler::GetField(), CPlayerCoreFactory::GetPlayers(), JSONRPC::CSettingsOperations::GetSections(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSources(), JSONRPC::CTextureOperations::GetTextures(), CGUIDialogSettingsBase::OnMessage(), JSONRPC::CJSONUtils::SetFromDBDate(), JSONRPC::CJSONUtils::SetFromDBDateTime(), CDVDVideoCodecStarfish::SetHDR(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogYesNo::ShowAndGetInput(), and TEST().
end_array() [1/2]
CVariant::iterator_array CVariant::end_array ()
References EMPTY_ARRAY, and m_data.
Referenced by JSONRPC::CGUIOperations::ActivateWindow(), JSONRPC::CAudioLibrary::CheckForAdditionalProperties(), JSONRPC::CJSONUtils::CopyStringArray(), JSONRPC::CAddonsOperations::ExecuteAddon(), JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CAudioLibrary::GetArtists(), JSONRPC::CProfilesOperations::GetCurrentProfile(), JSONRPC::CVideoLibrary::GetDetailsFromJsonParameters(), JSONRPC::CFileOperations::GetDirectory(), JSONRPC::CFavouritesOperations::GetFavourites(), JSONRPC::CFileOperations::GetFileDetails(), JSONRPC::CPlayerOperations::GetItem(), JSONRPC::CProfilesOperations::GetProfiles(), JSONRPC::CAudioLibrary::GetProperties(), JSONRPC::CAudioLibrary::GetSongs(), CMusicDatabase::GetSongsByWhereJSON(), JSONRPC::CTextureOperations::GetTextures(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::CPlaylistOperations::HandleItemsParameter(), CDatabaseQueryRuleCombination::Load(), JSONRPC::CJSONRPC::MethodCall(), and TEST().
end_array() [2/2]
CVariant::const_iterator_array CVariant::end_array () const
References EMPTY_ARRAY, and m_data.
end_map() [1/2]
CVariant::iterator_map CVariant::end_map ()
References EMPTY_MAP, and m_data.
Referenced by JSONRPC::JSONSchemaTypeDefinition::Check(), JSONRPC::CAddonsOperations::ExecuteAddon(), JSONRPC::CTextureOperations::GetTextures(), JSONRPC::CJSONServiceDescription::prepareDescription(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetArtistDetails(), JSONRPC::CAudioLibrary::SetSongDetails(), TEST(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
end_map() [2/2]
CVariant::const_iterator_map CVariant::end_map () const
References EMPTY_MAP, and m_data.
erase() [1/2]
void CVariant::erase (const std::string & key)
References m_data.
Referenced by JSONRPC::JSONSchemaTypeDefinition::Check(), CGUIListItem::ClearProperty(), JSONRPC::CTextureOperations::GetTextures(), JSONRPC::CAudioLibrary::SetSongDetails(), and TEST().
erase() [2/2]
void CVariant::erase (unsigned int position)
References m_data.
isArray()
bool CVariant::isArray () const
References m_data.
Referenced by JSONRPC::CAudioLibrary::CheckForAdditionalProperties(), JSONRPC::CJSONUtils::CopyStringArray(), JSONRPC::CAddonsOperations::ExecuteAddon(), JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CAudioLibrary::GetArtists(), JSONRPC::CFavouritesOperations::GetFavourites(), JSONRPC::CJSONUtils::GetParameter(), JSONRPC::CAudioLibrary::GetSongs(), CMusicDatabase::GetSongsByWhereJSON(), JSONRPC::CTextureOperations::GetTextures(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::CPlaylistOperations::HandleItemsParameter(), JSONRPC::CJSONUtils::IsParameterType(), JSONRPC::CJSONRPC::IsProperJSONRPC(), CDatabaseQueryRule::Load(), CDatabaseQueryRuleCombination::Load(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), JSONRPC::CJSONRPC::MethodCall(), JSONRPC::CJSONUtils::ParameterExists(), JSONRPC::JsonRpcMethod::Parse(), CMusicDatabase::SetPropertiesForFileItem(), TEST(), TEST(), TEST(), TEST(), and TEST().
isBoolean()
bool CVariant::isBoolean () const
References m_data.
Referenced by JSONRPC::CFileOperations::FillFileItemList(), JSONRPC::CAddonsOperations::GetAddons(), KODI::PLAYLIST::CSmartPlaylist::Load(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), JSONRPC::CPlayerOperations::Open(), JSONRPC::CPlayerOperations::PlayPause(), JSONRPC::CApplicationOperations::SetMute(), JSONRPC::CPlayerOperations::SetShuffle(), JSONRPC::CPlayerOperations::SetViewMode(), TEST(), and TEST().
isDouble()
bool CVariant::isDouble () const
References m_data.
Referenced by GetNewValueForViewModeParameter(), JSONRPC::CPlayerOperations::Open(), TEST(), and TEST().
isInteger()
bool CVariant::isInteger () const
References isSignedInteger(), and isUnsignedInteger().
Referenced by CGUIDialogBoxBase::GetLocalized(), JSONRPC::CPlayerOperations::GoTo(), KODI::PLAYLIST::CSmartPlaylist::Load(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIEditControl::SetInputType(), CGUIKeyboardFactory::ShowAndGetInput(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and JSONRPC::CPlayerOperations::Zoom().
isMember()
bool CVariant::isMember (const std::string & key) const
References m_data.
Referenced by JSONRPC::CJSONRPC::BuildResponse(), JSONRPC::CPlaylistOperations::CheckMediaParameter(), JSONRPC::CFileItemHandler::FillDetails(), JSONRPC::CAddonsOperations::FillDetails(), JSONRPC::CFileOperations::FillFileItemList(), JSONRPC::CAudioLibrary::GetAlbums(), CMusicDatabase::GetAlbumsByWhereJSON(), JSONRPC::CAudioLibrary::GetArtistDetails(), JSONRPC::CAudioLibrary::GetArtists(), CMusicDatabase::GetArtistsByWhereJSON(), JSONRPC::CFileOperations::GetDirectory(), JSONRPC::CVideoLibrary::GetEpisodes(), JSONRPC::CFavouritesOperations::GetFavourites(), JSONRPC::CFileItemHandler::GetField(), JSONRPC::CFileOperations::GetFileDetails(), JSONRPC::CVideoLibrary::GetMovies(), JSONRPC::CVideoLibrary::GetMusicVideos(), JSONRPC::CSettingsOperations::GetSettings(), JSONRPC::CAudioLibrary::GetSongs(), CMusicDatabase::GetSongsByWhereJSON(), JSONRPC::CAudioLibrary::GetSources(), JSONRPC::CTextureOperations::GetTextures(), JSONRPC::CVideoLibrary::GetTVShows(), JSONRPC::CJSONUtils::GetXspFiltering(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::CJSONRPC::HandleMethodCall(), JSONRPC::CJSONRPC::IsProperJSONRPC(), CDatabaseQueryRule::Load(), KODI::PLAYLIST::CSmartPlaylist::Load(), CDatabaseQueryRuleCombination::Load(), JSONRPC::CJSONUtils::ParameterNotNull(), JSONRPC::JsonRpcMethod::Parse(), JSONRPC::CJSONServiceDescription::prepareDescription(), JSONRPC::CVideoLibrary::RemoveVideo(), JSONRPC::CPVROperations::Scan(), JSONRPC::CJSONRPC::SetConfiguration(), TEST(), TEST(), TEST_F(), and TEST_F().
isNull()
bool CVariant::isNull () const
References m_data.
Referenced by JSONRPC::CJSONRPC::BuildResponse(), ByArtist(), ByArtistThenYear(), ByEpisodeNumber(), ByOrigDate(), BySeason(), ByYear(), ANNOUNCEMENT::CAnnouncementManager::DoAnnounce(), JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CFavouritesOperations::GetFavourites(), JSONRPC::CAudioLibrary::GetSongs(), CGUIDialogMediaFilter::InitializeSettings(), JSONRPC::CJSONRPC::MethodCall(), CInputStreamAddon::Open(), CDVDDemuxFFmpeg::Open(), JSONRPC::CPlayerOperations::Open(), JSONRPC::CJSONUtils::ParameterNotNull(), CDBusUtil::ParseType(), JSONRPC::JSONSchemaTypeDefinition::ResolveReference(), CDatabaseQueryRule::Save(), JSONRPC::CPlayerOperations::SetViewMode(), CInputStreamAddon::Supports(), TEST(), TEST(), and CUDiskDevice::Update().
isObject()
bool CVariant::isObject () const
References m_data.
Referenced by JSONRPC::CAddonsOperations::ExecuteAddon(), JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CAudioLibrary::GetArtists(), JSONRPC::CVideoLibrary::GetEpisodes(), JSONRPC::CVideoLibrary::GetMovies(), JSONRPC::CVideoLibrary::GetMusicVideos(), JSONRPC::CAudioLibrary::GetSongs(), JSONRPC::CTextureOperations::GetTextures(), JSONRPC::CVideoLibrary::GetTVShows(), JSONRPC::CJSONUtils::GetXspFiltering(), JSONRPC::CJSONRPC::IsProperJSONRPC(), KODI::PLAYLIST::CSmartPlaylist::Load(), CDatabaseQueryRuleCombination::Load(), JSONRPC::CPlayerOperations::Open(), JSONRPC::CJSONServiceDescription::prepareDescription(), CDatabaseQueryRuleCombination::Save(), JSONRPC::CPlayerOperations::SetViewMode(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
isSignedInteger()
bool CVariant::isSignedInteger () const
References m_data.
Referenced by isInteger().
isString()
bool CVariant::isString () const
References m_data.
Referenced by JSONRPC::CAddonsOperations::ExecuteAddon(), CGUIDialogBoxBase::GetLocalized(), GetNewValueForViewModeParameter(), JSONRPC::CPlayerOperations::GoTo(), JSONRPC::CJSONRPC::IsProperJSONRPC(), CDatabaseQueryRule::Load(), KODI::PLAYLIST::CSmartPlaylist::Load(), CGUIDialogSettingsBase::OnMessage(), JSONRPC::CPlayerOperations::Open(), JSONRPC::JsonRpcMethod::Parse(), JSONRPC::CPlayerOperations::PlayPause(), JSONRPC::CJSONUtils::SetFromDBDate(), JSONRPC::CJSONUtils::SetFromDBDateTime(), CGUIEditControl::SetInputType(), JSONRPC::CPlayerOperations::SetPartymode(), JSONRPC::CPlayerOperations::SetShuffle(), JSONRPC::CPlayerOperations::SetViewMode(), CGUIKeyboardFactory::ShowAndGetInput(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and JSONRPC::CPlayerOperations::Zoom().
isUnsignedInteger()
bool CVariant::isUnsignedInteger () const
References m_data.
Referenced by isInteger(), KODI::PLAYLIST::CSmartPlaylist::Load(), and TEST().
isWideString()
bool CVariant::isWideString () const
References m_data.
Referenced by TEST().
operator!=()
bool CVariant::operator!= (const CVariant & rhs) const inline
operator=() [1/2]
CVariant & CVariant::operator= (const CVariant & rhs)
References cleanup(), m_data, type(), and VariantTypeConstNull.
operator=() [2/2]
CVariant & CVariant::operator= (CVariant && rhs) noexcept
operator==()
bool CVariant::operator== (const CVariant & rhs) const
References m_data.
operator[]() [1/6]
CVariant & CVariant::operator[] (const std::string & key) &
operator[]() [2/6]
CVariant CVariant::operator[] (const std::string & key) &&
operator[]() [3/6]
const CVariant & CVariant::operator[] (const std::string & key) const &
operator[]() [4/6]
CVariant & CVariant::operator[] (unsigned int position) &
References size().
operator[]() [5/6]
CVariant CVariant::operator[] (unsigned int position) &&
References size().
operator[]() [6/6]
const CVariant & CVariant::operator[] (unsigned int position) const &
References size().
push_back() [1/2]
void CVariant::push_back (const CVariant & variant)
References m_data, type(), VariantTypeArray, and VariantTypeNull.
Referenced by append(), append(), JSONRPC::JSONSchemaTypeDefinition::Check(), JSONRPC::CAudioLibrary::FillItemArtistIDs(), JSONRPC::CAudioLibrary::GetAdditionalSongDetails(), CMusicDatabase::GetArtistsByAlbum(), JSONRPC::CSettingsOperations::GetCategories(), PVR::CPVRClients::GetEnabledClientInfos(), JSONRPC::CFileItemHandler::GetField(), CMusicDatabase::GetFileItemFromArtistCredits(), CMusicDatabase::GetGenresByAlbum(), CMusicDatabase::GetGenresByArtist(), CMusicDatabase::GetGenresJSON(), JSONRPC::CXBMCOperations::GetInfoBooleans(), JSONRPC::CPlayerOperations::GetPlayers(), CMusicDatabase::GetRolesByArtist(), JSONRPC::CSettingsOperations::GetSections(), JSONRPC::CSettingsOperations::GetSettings(), JSONRPC::CSettingsOperations::GetSkinSettings(), CMusicDatabase::GetSources(), CMusicDatabase::GetSourcesByAlbum(), CMusicDatabase::GetSourcesByArtist(), CMusicDatabase::GetSourcesBySong(), JSONRPC::CTextureOperations::GetTextures(), CTextureDatabase::GetTextures(), JSONRPC::CJSONUtils::GetXspFiltering(), JSONRPC::CPlaylistOperations::HandleItemsParameter(), CAESinkStarfish::Initialize(), CDatabaseQueryRule::Load(), CDVDVideoCodecStarfish::OpenInternal(), JSONRPC::CJSONServiceDescription::Print(), CJSONVariantParserHandler::PushObject(), CDatabaseQueryRuleCombination::Save(), MUSIC_INFO::CMusicInfoTag::Serialize(), PVR::CPVRTimerInfoTag::Serialize(), JSONRPC::CSettingsOperations::SerializeSettingInt(), JSONRPC::CSettingsOperations::SerializeSettingListValues(), JSONRPC::CSettingsOperations::SerializeSettingString(), CSettingsValueFlatJsonSerializer::SerializeSettingValue(), TEST(), TEST(), TEST(), TEST_F(), and ADDON::CAddonDatabase::UpdateTables().
push_back() [2/2]
void CVariant::push_back (CVariant && variant)
References m_data, type(), VariantTypeArray, and VariantTypeNull.
reserve()
void CVariant::reserve (size_t length)
References m_data, type(), VariantTypeArray, and VariantTypeNull.
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetSongsByWhereJSON(), and JSONRPC::CFileItemHandler::HandleFileItemList().
size()
unsigned int CVariant::size () const
References m_data.
Referenced by JSONRPC::JsonRpcMethod::Check(), JSONRPC::JSONSchemaTypeDefinition::Check(), PVR::CPVRCachedImages::Cleanup(), JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CXBMCOperations::GetInfoBooleans(), JSONRPC::CXBMCOperations::GetInfoLabels(), JSONRPC::CJSONUtils::GetParameter(), JSONRPC::CApplicationOperations::GetProperties(), JSONRPC::CGUIOperations::GetProperties(), JSONRPC::CPlayerOperations::GetProperties(), JSONRPC::CPlaylistOperations::GetProperties(), JSONRPC::CPVROperations::GetProperties(), JSONRPC::CSystemOperations::GetProperties(), JSONRPC::CAudioLibrary::GetSongs(), JSONRPC::CJSONUtils::IsParameterType(), JSONRPC::CJSONRPC::MethodCall(), operator[](), operator[](), operator[](), JSONRPC::CJSONUtils::ParameterExists(), JSONRPC::CJSONServiceDescription::Print(), CJSONVariantParserHandler::PushObject(), JSONRPC::CJSONUtils::SchemaValueTypeToJson(), TEST(), and TEST().
swap()
void CVariant::swap (CVariant & rhs) noexcept
Referenced by JSONRPC::CJSONRPC::Ping().
type()
CVariant::VariantType CVariant::type () const
References m_data.
Referenced by JSONRPC::CJSONServiceDescription::AddEnum(), CVariant(), operator=(), push_back(), push_back(), reserve(), KODI::PLAYLIST::CSmartPlaylist::Save(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
Member Data Documentation
ConstNullVariant
CVariant CVariant::ConstNullVariant = CVariant::VariantTypeConstNull static
Referenced by DatabaseUtils::GetFieldValue(), CJSONVariantParserHandler::Null(), CSettingsValueFlatJsonSerializer::SerializeSettingValue(), SortUtils::Sort(), and SortUtils::Sort().
EMPTY_ARRAY
CVariant::VariantArray CVariant::EMPTY_ARRAY static private
Referenced by begin_array(), begin_array(), end_array(), and end_array().
EMPTY_MAP
CVariant::VariantMap CVariant::EMPTY_MAP static private
Referenced by begin_map(), begin_map(), end_map(), and end_map().
m_data
std::variant<Null, ConstNull, int64_t, uint64_t, bool, double, std::string, std::wstring, VariantArray, VariantMap> CVariant::m_data private
Referenced by asBoolean(), asDouble(), asInteger(), asUnsignedInteger(), begin_array(), begin_array(), begin_map(), begin_map(), c_str(), cleanup(), clear(), CVariant(), CVariant(), CVariant(), CVariant(), CVariant(), empty(), end_array(), end_array(), end_map(), end_map(), erase(), erase(), isArray(), isBoolean(), isDouble(), isMember(), isNull(), isObject(), isSignedInteger(), isString(), isUnsignedInteger(), isWideString(), operator=(), operator==(), push_back(), push_back(), reserve(), size(), and type().
The documentation for this class was generated from the following files:
Variant.h
Variant.cpp