Kodi Documentation: AddonToKodiFuncTable_kodi_gui_control_settings_slider Struct Reference
AddonToKodiFuncTable_kodi_gui_control_settings_slider Struct Reference
#include <settings_slider.h>
Public Attributes
void(* set_visible)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
void(* set_enabled)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled)
void(* set_text)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *label)
void(* reset)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
void(* set_int_range)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int start, int end)
void(* set_int_value)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int value)
int(* get_int_value)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
void(* set_int_interval)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int interval)
void(* set_percentage)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float percent)
float(* get_percentage)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
void(* set_float_range)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float start, float end)
void(* set_float_value)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float value)
float(* get_float_value)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
void(* set_float_interval)(KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float interval)
Member Data Documentation
get_float_value
float(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::get_float_value) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
get_int_value
int(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::get_int_value) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
get_percentage
float(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::get_percentage) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
reset
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::reset) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
set_enabled
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_enabled) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
set_float_interval
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_float_interval) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float interval)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
set_float_range
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_float_range) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float start, float end)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
set_float_value
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_float_value) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float value)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
set_int_interval
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_int_interval) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int interval)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
set_int_range
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_int_range) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int start, int end)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
set_int_value
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_int_value) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int value)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
set_percentage
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_percentage) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float percent)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
set_text
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_text) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *label)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
set_visible
void(* AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_visible) (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
Referenced by ADDON::Interface_GUIControlSettingsSlider::Init().
The documentation for this struct was generated from the following file:
settings_slider.h