Kodi Documentation: TestJobManager Class Reference
TestJobManager Class Reference
Protected Member Functions
TestJobManager ()
~TestJobManager () override
Constructor & Destructor Documentation
TestJobManager()
TestJobManager::TestJobManager () inline protected
References CServiceBroker::RegisterJobManager().
~TestJobManager()
TestJobManager::~TestJobManager () inline override protected
References CServiceBroker::GetJobManager(), and CServiceBroker::UnregisterJobManager().
The documentation for this class was generated from the following file:
TestJobManager.cpp