Kodi Documentation: XBMCController Class Reference
XBMCController Class Reference
#include <XBMCController.h>
Instance Methods
(void) - pauseAnimation
(void) - resumeAnimation
(void) - startAnimation
(void) - stopAnimation
(void) - enterBackground
(void) - enterForeground
(void) - becomeInactive
(void) - sendKey:
(void) - observeDefaultCenterStuff:
(CGRect) - fullscreenSubviewFrame
(void) - onXbmcAlive
(void) - setGUIInsetsFromMainThread:
(void) - setFramebuffer
(bool) - presentFramebuffer
(CGSize) - getScreenSize
(UIInterfaceOrientation) - getOrientation
(void) - createGestureRecognizers
(void) - activateKeyboard:
(void) - deactivateKeyboard:
(void) - nativeKeyboardActive:
(void) - disableNetworkAutoSuspend
(void) - enableNetworkAutoSuspend:
(void) - rescheduleNetworkAutoSuspend
(void) - disableSystemSleep
(void) - enableSystemSleep
(void) - disableScreenSaver
(void) - enableScreenSaver
(bool) - changeScreen:withMode:
(void) - activateScreen:withOrientation:
(id) - initWithFrame:withScreen:
(CVEAGLContext) - getEAGLContextObj
(void) - pauseAnimation
(void) - resumeAnimation
(void) - startAnimation
(void) - stopAnimation
(void) - enterBackground
(void) - enterForeground
(void) - setFramebuffer
(bool) - presentFramebuffer
(void) - activateKeyboard:
(void) - deactivateKeyboard:
(void) - nativeKeyboardActive:
(void) - beginEnterBackgroundTask
(void) - endEnterBackgroundTask
(void) - disableScreenSaver
(void) - enableScreenSaver
(bool) - resetSystemIdleTimer
(CGRect) - fullscreenSubviewFrame
((availability(tvos, introduced=11.2) - __attribute__
(EAGLContext *) - getEAGLContextObj
(void) - sendKeypressEvent: [implementation]
(BOOL) - hasText [implementation]
(void) - insertText: [implementation]
(void) - deleteBackward [implementation]
(UIInterfaceOrientationMask) - supportedInterfaceOrientations [implementation]
(BOOL) - gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer: [implementation]
(void) - addSwipeGesture:numTouches: [implementation]
(void) - addTapGesture: [implementation]
(void) - touchesBegan:withEvent: [implementation]
(void) - handlePinch: [implementation]
(void) - handleRotate: [implementation]
(IBAction) - handlePan: [implementation]
(IBAction) - handleSwipe: [implementation]
(IBAction) - handleTap: [implementation]
(IBAction) - handleSingleFingerSingleLongTap: [implementation]
(void) - loadView [implementation]
(void) - viewDidLoad [implementation]
(void) - dealloc [implementation]
(void) - viewWillAppear: [implementation]
(void) - viewDidAppear: [implementation]
(BOOL) - prefersHomeIndicatorAutoHidden [implementation]
(void) - viewWillDisappear: [implementation]
(UIView *) - inputView [implementation]
(BOOL) - canBecomeFirstResponder [implementation]
(void) - viewDidUnload [implementation]
(BOOL) - recreateOnReselect [implementation]
(void) - didReceiveMemoryWarning [implementation]
(void) - remoteControlReceivedWithEvent: [implementation]
(void) - runAnimation: [implementation]
(int) - KODI_Run [implementation]
(void) - CallExit [implementation]
(instancetype) - init [implementation]
Protected Attributes
UIWindow * m_window
IOSEAGLView * m_glView
int m_screensaverTimeout
CGSize screensize
CGPoint lastGesturePoint
CGFloat screenScale
bool touchBeginSignaled
int m_screenIdx
UIInterfaceOrientation orientation
bool m_isPlayingBeforeInactive
UIBackgroundTaskIdentifier m_bgTask
NSTimer * m_networkAutoSuspendTimer
bool nativeKeyboardActive
BOOL m_isPlayingBeforeInactive
UIBackgroundTaskIdentifier m_enterBackgroundTaskId
bool m_nativeKeyboardActive
BOOL m_pause
BOOL m_animating
NSConditionLock * m_animationThreadLock
NSThread * m_animationThread
std::unique_ptr< CFileItem > m_playingFileItemBeforeBackground
std::string m_lastUsedPlayer
std::unique_ptr< DebugLogSharingPresenter > m_debugLogSharingPresenter
Properties
BOOL animating
DarwinEmbedNowPlayingInfoManager * MPNPInfoManager
BOOL appAlive
TVOSDisplayManager * displayManager
TVOSEAGLView * glView
TVOSLibInputHandler * inputHandler
Method Documentation
__attribute__
- ((availability(tvos, introduced=11.2) __attribute__
activateKeyboard: [1/2]
- (void) activateKeyboard: (UIView *) view
activateKeyboard: [2/2]
- (void) activateKeyboard: (UIView *) view
activateScreen:withOrientation:
- (void) activateScreen: (UIScreen *) screen withOrientation: (UIInterfaceOrientation) newOrientation
addSwipeGesture:numTouches:
- (void) addSwipeGesture: (UISwipeGestureRecognizerDirection) direction numTouches: (NSUInteger) numTouches implementation
addTapGesture:
- (void) addTapGesture: (NSUInteger) numTouches implementation
becomeInactive
- (void) becomeInactive
beginEnterBackgroundTask
- (void) beginEnterBackgroundTask
References glView.
CallExit
- (void) CallExit implementation
References g_application, CAnnounceReceiver::GetInstance(), CServiceBroker::GetLogging(), CServiceBroker::GetSettingsComponent(), CAnnounceReceiver::Initialize(), CLog::Log(), LOG_LEVEL_DEBUG, LOG_LEVEL_NORMAL, LOGERROR, CLog::SetLogLevel(), CAppEnvironment::SetUp(), and CAppEnvironment::TearDown().
canBecomeFirstResponder
- (BOOL) canBecomeFirstResponder implementation
changeScreen:withMode:
- (bool) changeScreen: (unsigned int) screenIdx withMode: (UIScreenMode *) mode
createGestureRecognizers
- (void) createGestureRecognizers
deactivateKeyboard: [1/2]
- (void) deactivateKeyboard: (UIView *) view
deactivateKeyboard: [2/2]
- (void) deactivateKeyboard: (UIView *) view
dealloc
- (void) dealloc implementation
deleteBackward
- (void) deleteBackward implementation
didReceiveMemoryWarning
- (void) didReceiveMemoryWarning implementation
disableNetworkAutoSuspend
- (void) disableNetworkAutoSuspend
disableScreenSaver [1/2]
- (void) disableScreenSaver
disableScreenSaver [2/2]
- (void) disableScreenSaver
disableSystemSleep
- (void) disableSystemSleep
enableNetworkAutoSuspend:
- (void) enableNetworkAutoSuspend: (id) obj
enableScreenSaver [1/2]
- (void) enableScreenSaver
enableScreenSaver [2/2]
- (void) enableScreenSaver
enableSystemSleep
- (void) enableSystemSleep
endEnterBackgroundTask
- (void) endEnterBackgroundTask
enterBackground [1/2]
- (void) enterBackground
enterBackground [2/2]
- (void) enterBackground
enterForeground [1/2]
- (void) enterForeground
enterForeground [2/2]
- (void) enterForeground
fullscreenSubviewFrame [1/2]
- (CGRect) fullscreenSubviewFrame
fullscreenSubviewFrame [2/2]
- (CGRect) fullscreenSubviewFrame
gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:
- (BOOL) gestureRecognizer: (UIGestureRecognizer *) gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer: (UIGestureRecognizer *) otherGestureRecognizer implementation
getEAGLContextObj [1/2]
- (EAGLContext *) getEAGLContextObj
getEAGLContextObj [2/2]
- (EAGLContext *) getEAGLContextObj
getOrientation
- (UIInterfaceOrientation) getOrientation
getScreenSize
- (CGSize) getScreenSize
handlePan:
- (IBAction) handlePan: (UIPanGestureRecognizer *) sender implementation
handlePinch:
- (void) handlePinch: (UIPinchGestureRecognizer*) sender implementation
handleRotate:
- (void) handleRotate: (UIRotationGestureRecognizer*) sender implementation
handleSingleFingerSingleLongTap:
- (IBAction) handleSingleFingerSingleLongTap: (UIGestureRecognizer *) sender implementation
handleSwipe:
- (IBAction) handleSwipe: (UISwipeGestureRecognizer *) sender implementation
handleTap:
- (IBAction) handleTap: (UIGestureRecognizer *) sender implementation
hasText
- (BOOL) hasText implementation
init
- (instancetype) init implementation
initWithFrame:withScreen:
- (id) initWithFrame: (CGRect) frame withScreen: (UIScreen *) screen
inputView
- (UIView *) inputView implementation
insertText:
- (void) insertText: (NSString *) text implementation
KODI_Run
- (int) KODI_Run (bool) renderGUI implementation
Todo:
: proper params
Todo:
loadView
- (void) loadView implementation
nativeKeyboardActive: [1/2]
- (void) nativeKeyboardActive: (bool) active
nativeKeyboardActive: [2/2]
- (void) nativeKeyboardActive: (bool) active
observeDefaultCenterStuff:
- (void) observeDefaultCenterStuff: (NSNotification *) notification
onXbmcAlive
- (void) onXbmcAlive
pauseAnimation [1/2]
- (void) pauseAnimation
pauseAnimation [2/2]
- (void) pauseAnimation
prefersHomeIndicatorAutoHidden
- (BOOL) prefersHomeIndicatorAutoHidden implementation
presentFramebuffer [1/2]
- (bool) presentFramebuffer
presentFramebuffer [2/2]
- (bool) presentFramebuffer
recreateOnReselect
- (BOOL) recreateOnReselect implementation
remoteControlReceivedWithEvent:
- (void) remoteControlReceivedWithEvent: (UIEvent *) receivedEvent implementation
rescheduleNetworkAutoSuspend
- (void) rescheduleNetworkAutoSuspend
resetSystemIdleTimer
- (bool) resetSystemIdleTimer
resumeAnimation [1/2]
- (void) resumeAnimation
resumeAnimation [2/2]
- (void) resumeAnimation
runAnimation:
- (void) runAnimation: (id) arg implementation
sendKey:
- (void) sendKey: (XBMCKey) key
sendKeypressEvent:
- (void) sendKeypressEvent: (XBMC_Event) event implementation
setFramebuffer [1/2]
- (void) setFramebuffer
setFramebuffer [2/2]
- (void) setFramebuffer
setGUIInsetsFromMainThread:
- (void) setGUIInsetsFromMainThread: (BOOL) isMainThread
startAnimation [1/2]
- (void) startAnimation
startAnimation [2/2]
- (void) startAnimation
stopAnimation [1/2]
- (void) stopAnimation
stopAnimation [2/2]
- (void) stopAnimation
supportedInterfaceOrientations
- (UIInterfaceOrientationMask) supportedInterfaceOrientations implementation
touchesBegan:withEvent:
- (void) touchesBegan: (NSSet *) touches withEvent: (UIEvent *) event implementation
viewDidAppear:
- (void) viewDidAppear: (BOOL) animated implementation
viewDidLoad
- (void) viewDidLoad implementation
viewDidUnload
- (void) viewDidUnload implementation
viewWillAppear:
- (void) viewWillAppear: (BOOL) animated implementation
viewWillDisappear:
- (void) viewWillDisappear: (BOOL) animated implementation
Member Data Documentation
lastGesturePoint
- (CGPoint) lastGesturePoint read write protected
m_animating
- (BOOL) m_animating protected
m_animationThread
- (NSThread*) m_animationThread protected
m_animationThreadLock
- (NSConditionLock*) m_animationThreadLock protected
m_bgTask
- (UIBackgroundTaskIdentifier) m_bgTask protected
m_debugLogSharingPresenter
- (unique_ptr<DebugLogSharingPresenter> XBMCController()): protected
Provided by category XBMCController().
m_enterBackgroundTaskId
- (UIBackgroundTaskIdentifier) m_enterBackgroundTaskId protected
m_glView
- (IOSEAGLView*) m_glView protected
m_isPlayingBeforeInactive [1/2]
- (bool) m_isPlayingBeforeInactive protected
m_isPlayingBeforeInactive [2/2]
- (BOOL) m_isPlayingBeforeInactive protected
m_lastUsedPlayer
- (string) XBMCController: protected
m_nativeKeyboardActive
- (bool) m_nativeKeyboardActive protected
m_networkAutoSuspendTimer
- (NSTimer *) m_networkAutoSuspendTimer read write nonatomic strong protected
m_pause
- (BOOL) m_pause protected
m_playingFileItemBeforeBackground
- (unique_ptr<CFileItem>) XBMCController: protected
m_screenIdx
- (int) m_screenIdx read write protected
m_screensaverTimeout
- (int) m_screensaverTimeout protected
m_window
- (UIWindow*) m_window protected
nativeKeyboardActive
- (bool) nativeKeyboardActive read write protected
orientation
- (UIInterfaceOrientation) orientation protected
screenScale
- (CGFloat) screenScale read write protected
screensize
- (CGSize) screensize read write protected
touchBeginSignaled
- (bool) touchBeginSignaled read write protected
Property Documentation
animating
- (BOOL) animating read nonatomic assign
appAlive
- (BOOL) appAlive read write nonatomic assign
Referenced by TVOSLibInputTouch::createPanGestureRecognizers.
displayManager
- (TVOSDisplayManager*) displayManager read write nonatomic strong
glView
- (TVOSEAGLView*) glView read write nonatomic strong
Referenced by beginEnterBackgroundTask.
inputHandler
- (TVOSLibInputHandler*) inputHandler read write nonatomic strong
Referenced by CTVOSInputSettings::Initialize(), TVOSLibInputRemote::keyPressTimerCallback:, and CTVOSInputSettings::OnSettingChanged().
MPNPInfoManager
- (DarwinEmbedNowPlayingInfoManager *) MPNPInfoManager read write nonatomic strong
Referenced by AnnounceBridge().
The documentation for this class was generated from the following files:
ios/XBMCController.h
tvos/XBMCController.h
ios/XBMCController.mm
tvos/XBMCController.mm