Kodi Documentation: TestAddonDatabase.cpp File Reference
TestAddonDatabase.cpp File Reference
#include "addons/AddonDatabase.h"
#include "addons/addoninfo/AddonInfoBuilder.h"
#include "filesystem/SpecialProtocol.h"
#include "settings/AdvancedSettings.h"
#include <set>
#include <utility>
#include <gtest/gtest.h>
Classes
class AddonDatabaseTest
Functions
TEST_F (AddonDatabaseTest, TestFindById)
TEST_F (AddonDatabaseTest, TestFindByNonExistingId)
Function Documentation
TEST_F() [1/2]
TEST_F (AddonDatabaseTest , TestFindById)
References addons, EXPECT_EQ(), and EXPECT_TRUE().
TEST_F() [2/2]
TEST_F (AddonDatabaseTest , TestFindByNonExistingId)
References addons, EXPECT_EQ(), and EXPECT_TRUE().