Kodi Documentation: XFILE::CDAVCommon Class Reference
XFILE::CDAVCommon Class Reference
#include <DAVCommon.h>
Static Public Member Functions
static bool ValueWithoutNamespace (const tinyxml2::XMLNode *node, const std::string &value)
static std::string GetStatusTag (const tinyxml2::XMLElement *element)
Member Function Documentation
GetStatusTag()
std::string CDAVCommon::GetStatusTag (const tinyxml2::XMLElement * element) static
References ValueWithoutNamespace().
Referenced by XFILE::CDAVFile::Execute(), and XFILE::CDAVDirectory::ParseResponse().
ValueWithoutNamespace()
bool CDAVCommon::ValueWithoutNamespace (const tinyxml2::XMLNode * node, const std::string & value) static
References LOGERROR, node, and value.
Referenced by XFILE::CDAVFile::Execute(), XFILE::CDAVDirectory::GetDirectory(), GetStatusTag(), and XFILE::CDAVDirectory::ParseResponse().
The documentation for this class was generated from the following files:
DAVCommon.h
DAVCommon.cpp