Kodi Documentation: DXVA::CProcessorHD Class Reference
DXVA::CProcessorHD Class Reference
#include <DXVAHD.h>
Public Member Functions
CProcessorHD ()
~CProcessorHD ()
void UnInit ()
bool Open (const VideoPicture &picture, std::shared_ptr< DXVA::CEnumeratorHD > enumerator)
void Close ()
bool Render (CRect src, CRect dst, ID3D11Resource *target, CRenderBuffer **views, DWORD flags, UINT frameIdx, UINT rotation, float contrast, float brightness)
uint8_t PastRefs () const
bool SetConversion (const ProcessorConversion &conversion)
Configure the processor for the provided conversion.
void OnCreateDevice () override
void OnDestroyDevice (bool) override
void TryEnableVideoSuperResolution ()
bool IsVideoSuperResolutionEnabled () const
bool Supports (ERENDERFEATURE feature) const
Public Member Functions inherited from ID3DResource
virtual ~ID3DResource ()
Static Public Member Functions
static bool IsSuperResolutionSuitable (const VideoPicture &picture)
Protected Member Functions
bool ReInit ()
bool InitProcessor ()
bool CheckFormats () const
bool OpenProcessor ()
void ApplyFilter (D3D11_VIDEO_PROCESSOR_FILTER filter, int value, int min, int max, int def) const
ComPtr< ID3D11VideoProcessorInputView > GetInputView (CRenderBuffer *view) const
bool CheckVideoParameters (const CRect &src, const CRect &dst, const UINT &rotation, const float &contrast, const float &brightness, const CRenderBuffer &rb)
Apply new video settings if there was a change. Returns true if a parameter changed, false otherwise.
void EnableIntelVideoSuperResolution ()
void EnableNvidiaRTXVideoSuperResolution ()
Protected Member Functions inherited from ID3DResource
void Register ()
void Unregister ()
Protected Attributes
CCriticalSection m_section
ComPtr< ID3D11VideoDevice > m_pVideoDevice
ComPtr< ID3D11VideoContext > m_pVideoContext
ComPtr< ID3D11VideoProcessor > m_pVideoProcessor
std::shared_ptr< CEnumeratorHD > m_enumerator
AVColorPrimaries m_color_primaries {AVCOL_PRI_UNSPECIFIED}
AVColorTransferCharacteristic m_color_transfer {AVCOL_TRC_UNSPECIFIED}
ProcessorCapabilities m_procCaps
bool m_superResolutionEnabled {false}
ProcessorConversion m_conversion
bool m_isValidConversion {false}
bool m_configured {false}
true when at least one frame has been processed successfully since init
UINT m_lastInputFrameOrField {0}
UINT m_lastOutputIndex {0}
CRect m_lastSrc {}
CRect m_lastDst {}
UINT m_lastRotation {0}
float m_lastContrast {.0f}
float m_lastBrightness {.0f}
ProcessorConversion m_lastConversion {}
AVColorSpace m_lastColorSpace {AVCOL_SPC_UNSPECIFIED}
bool m_lastFullRange {false}
Protected Attributes inherited from ID3DResource
bool m_bRegistered = false
Constructor & Destructor Documentation
CProcessorHD()
CProcessorHD::CProcessorHD () explicit
~CProcessorHD()
CProcessorHD::~CProcessorHD ()
References UnInit().
Member Function Documentation
ApplyFilter()
void CProcessorHD::ApplyFilter (D3D11_VIDEO_PROCESSOR_FILTER filter, int value, int min, int max, int def) const protected
References DXVA::ProcAmpInfo::bSupported, DEFAULT_STREAM_INDEX, DXVA::ProcessorCapabilities::m_Filters, m_procCaps, m_pVideoContext, m_pVideoProcessor, max, min, DXVA::NUM_FILTERS, DXVA::ProcAmpInfo::Range, and value.
Referenced by CheckVideoParameters().
CheckFormats()
bool CProcessorHD::CheckFormats () const protected
References m_conversion, m_enumerator, m_isValidConversion, and DXVA::ProcessorConversion::m_outputFormat.
Referenced by ReInit().
CheckVideoParameters()
bool CProcessorHD::CheckVideoParameters (const CRect & src, const CRect & dst, const UINT & rotation, const float & contrast, const float & brightness, const CRenderBuffer & rb) protected
Apply new video settings if there was a change. Returns true if a parameter changed, false otherwise.
References ApplyFilter(), CRenderBuffer::color_space, DEFAULT_STREAM_INDEX, CRenderBuffer::full_range, m_configured, m_conversion, DXVA::ProcessorConversion::m_inputCS, m_lastBrightness, m_lastColorSpace, m_lastContrast, m_lastConversion, m_lastDst, m_lastFullRange, m_lastRotation, m_lastSrc, DXVA::ProcessorConversion::m_outputCS, m_pVideoContext, m_pVideoProcessor, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by Render().
Close()
void CProcessorHD::Close ()
References m_configured, m_pVideoContext, m_pVideoDevice, m_pVideoProcessor, m_section, and m_superResolutionEnabled.
Referenced by Open(), ReInit(), and UnInit().
EnableIntelVideoSuperResolution()
void CProcessorHD::EnableIntelVideoSuperResolution () protected
References FAILED, CWIN32Util::FormatHRESULT(), LOGINFO, LOGWARNING, m_pVideoContext, m_pVideoProcessor, and m_superResolutionEnabled.
Referenced by TryEnableVideoSuperResolution().
EnableNvidiaRTXVideoSuperResolution()
void CProcessorHD::EnableNvidiaRTXVideoSuperResolution () protected
References FAILED, CWIN32Util::FormatHRESULT(), LOGINFO, LOGWARNING, m_pVideoContext, m_pVideoProcessor, and m_superResolutionEnabled.
Referenced by TryEnableVideoSuperResolution().
GetInputView()
ComPtr< ID3D11VideoProcessorInputView > CProcessorHD::GetInputView (CRenderBuffer * view) const protected
References CRenderBuffer::GetResource(), and m_enumerator.
Referenced by Render().
InitProcessor()
bool CProcessorHD::InitProcessor () protected
References FAILED, CWIN32Util::FormatHRESULT(), DX::DeviceResources::Get(), LOGWARNING, m_enumerator, m_procCaps, m_pVideoContext, m_pVideoDevice, and DXVA::ProcessorCapabilities::m_valid.
Referenced by Open(), and ReInit().
IsSuperResolutionSuitable()
bool CProcessorHD::IsSuperResolutionSuitable (const VideoPicture & picture) static
References VideoPicture::color_primaries, VideoPicture::color_transfer, and VideoPicture::iWidth.
Referenced by CRendererDXVA::Configure().
IsVideoSuperResolutionEnabled()
bool DXVA::CProcessorHD::IsVideoSuperResolutionEnabled () const inline
References m_superResolutionEnabled.
OnCreateDevice()
void DXVA::CProcessorHD::OnCreateDevice (void) inline override virtual
Implements ID3DResource.
OnDestroyDevice()
void DXVA::CProcessorHD::OnDestroyDevice (bool) inline override virtual
Implements ID3DResource.
References m_section, and UnInit().
Open()
bool CProcessorHD::Open (const VideoPicture & picture, std::shared_ptr< DXVA::CEnumeratorHD > enumerator)
References Close(), VideoPicture::color_primaries, VideoPicture::color_transfer, InitProcessor(), m_color_primaries, m_color_transfer, m_enumerator, m_section, and OpenProcessor().
OpenProcessor()
bool CProcessorHD::OpenProcessor () protected
References color, DX::DeviceResources::Get(), LOGDEBUG, LOGWARNING, m_color_primaries, m_color_transfer, m_enumerator, DXVA::ProcessorCapabilities::m_hasMetadataHDR10Support, m_procCaps, DXVA::ProcessorCapabilities::m_procIndex, m_pVideoContext, m_pVideoDevice, m_pVideoProcessor, m_section, DXVA::ProcessorCapabilities::m_valid, PCIV_AMD, and ReInit().
Referenced by Open(), and Render().
PastRefs()
uint8_t DXVA::CProcessorHD::PastRefs () const inline
References m_procCaps, and DXVA::ProcessorCapabilities::m_rateCaps.
ReInit()
bool CProcessorHD::ReInit () protected
References CheckFormats(), Close(), InitProcessor(), and m_section.
Referenced by OpenProcessor().
Render()
bool CProcessorHD::Render (CRect src, CRect dst, ID3D11Resource * target, CRenderBuffer ** views, DWORD flags, UINT frameIdx, UINT rotation, float contrast, float brightness)
References CheckVideoParameters(), DEFAULT_STREAM_INDEX, end(), FAILED, CWIN32Util::FormatHRESULT(), GetInputView(), LOGERROR, LOGWARNING, m_configured, m_enumerator, m_lastInputFrameOrField, m_lastOutputIndex, m_procCaps, m_pVideoContext, m_pVideoProcessor, DXVA::ProcessorCapabilities::m_rateCaps, m_section, OpenProcessor(), RENDER_FLAG_BOT, RENDER_FLAG_FIELD0, RENDER_FLAG_FIELD1, and RENDER_FLAG_TOP.
SetConversion()
bool CProcessorHD::SetConversion (const ProcessorConversion & conversion)
Configure the processor for the provided conversion.
Parameters
conversion the conversion
Returns
success status, true = success, false = error
References LOGERROR, m_conversion, m_enumerator, DXVA::ProcessorConversion::m_inputCS, DXVA::ProcessorConversion::m_inputFormat, m_isValidConversion, DXVA::ProcessorConversion::m_outputCS, DXVA::ProcessorConversion::m_outputFormat, m_section, and DXVA::ProcessorConversion::ToString().
Supports()
bool CProcessorHD::Supports (ERENDERFEATURE feature) const
References DXVA::ProcAmpInfo::bSupported, DXVA::ProcessorCapabilities::m_Filters, m_procCaps, DXVA::ProcessorCapabilities::m_vcaps, RENDERFEATURE_BRIGHTNESS, RENDERFEATURE_CONTRAST, and RENDERFEATURE_ROTATION.
TryEnableVideoSuperResolution()
void CProcessorHD::TryEnableVideoSuperResolution ()
References EnableIntelVideoSuperResolution(), EnableNvidiaRTXVideoSuperResolution(), DX::DeviceResources::Get(), m_pVideoContext, m_pVideoProcessor, PCIV_Intel, and PCIV_NVIDIA.
UnInit()
void CProcessorHD::UnInit ()
References Close(), m_enumerator, and m_section.
Referenced by OnDestroyDevice(), and ~CProcessorHD().
Member Data Documentation
m_color_primaries
AVColorPrimaries DXVA::CProcessorHD::m_color_primaries {AVCOL_PRI_UNSPECIFIED} protected
Referenced by Open(), and OpenProcessor().
m_color_transfer
AVColorTransferCharacteristic DXVA::CProcessorHD::m_color_transfer {AVCOL_TRC_UNSPECIFIED} protected
Referenced by Open(), and OpenProcessor().
m_configured
bool DXVA::CProcessorHD::m_configured {false} protected
true when at least one frame has been processed successfully since init
Referenced by CheckVideoParameters(), Close(), and Render().
m_conversion
ProcessorConversion DXVA::CProcessorHD::m_conversion protected
Referenced by CheckFormats(), CheckVideoParameters(), and SetConversion().
m_enumerator
std::shared_ptr<CEnumeratorHD> DXVA::CProcessorHD::m_enumerator protected
Referenced by CheckFormats(), GetInputView(), InitProcessor(), Open(), OpenProcessor(), Render(), SetConversion(), and UnInit().
m_isValidConversion
bool DXVA::CProcessorHD::m_isValidConversion {false} protected
Referenced by CheckFormats(), and SetConversion().
m_lastBrightness
float DXVA::CProcessorHD::m_lastBrightness {.0f} protected
Referenced by CheckVideoParameters().
m_lastColorSpace
AVColorSpace DXVA::CProcessorHD::m_lastColorSpace {AVCOL_SPC_UNSPECIFIED} protected
Referenced by CheckVideoParameters().
m_lastContrast
float DXVA::CProcessorHD::m_lastContrast {.0f} protected
Referenced by CheckVideoParameters().
m_lastConversion
ProcessorConversion DXVA::CProcessorHD::m_lastConversion {} protected
Referenced by CheckVideoParameters().
m_lastDst
CRect DXVA::CProcessorHD::m_lastDst {} protected
Referenced by CheckVideoParameters().
m_lastFullRange
bool DXVA::CProcessorHD::m_lastFullRange {false} protected
Referenced by CheckVideoParameters().
m_lastInputFrameOrField
UINT DXVA::CProcessorHD::m_lastInputFrameOrField {0} protected
Referenced by Render().
m_lastOutputIndex
UINT DXVA::CProcessorHD::m_lastOutputIndex {0} protected
Referenced by Render().
m_lastRotation
UINT DXVA::CProcessorHD::m_lastRotation {0} protected
Referenced by CheckVideoParameters().
m_lastSrc
CRect DXVA::CProcessorHD::m_lastSrc {} protected
Referenced by CheckVideoParameters().
m_procCaps
ProcessorCapabilities DXVA::CProcessorHD::m_procCaps protected
Referenced by ApplyFilter(), InitProcessor(), OpenProcessor(), PastRefs(), Render(), and Supports().
m_pVideoContext
ComPtr<ID3D11VideoContext> DXVA::CProcessorHD::m_pVideoContext protected
Referenced by ApplyFilter(), CheckVideoParameters(), Close(), EnableIntelVideoSuperResolution(), EnableNvidiaRTXVideoSuperResolution(), InitProcessor(), OpenProcessor(), Render(), and TryEnableVideoSuperResolution().
m_pVideoDevice
ComPtr<ID3D11VideoDevice> DXVA::CProcessorHD::m_pVideoDevice protected
Referenced by Close(), InitProcessor(), and OpenProcessor().
m_pVideoProcessor
ComPtr<ID3D11VideoProcessor> DXVA::CProcessorHD::m_pVideoProcessor protected
Referenced by ApplyFilter(), CheckVideoParameters(), Close(), EnableIntelVideoSuperResolution(), EnableNvidiaRTXVideoSuperResolution(), OpenProcessor(), Render(), and TryEnableVideoSuperResolution().
m_section
CCriticalSection DXVA::CProcessorHD::m_section protected
Referenced by Close(), OnDestroyDevice(), Open(), OpenProcessor(), ReInit(), Render(), SetConversion(), and UnInit().
m_superResolutionEnabled
bool DXVA::CProcessorHD::m_superResolutionEnabled {false} protected
Referenced by Close(), EnableIntelVideoSuperResolution(), EnableNvidiaRTXVideoSuperResolution(), and IsVideoSuperResolutionEnabled().
The documentation for this class was generated from the following files:
DXVAHD.h
DXVAHD.cpp