Kodi Documentation: CSettingUpdate Class Reference
CSettingUpdate Class Reference
#include <SettingUpdate.h>
Public Member Functions
CSettingUpdate ()
virtual ~CSettingUpdate ()=default
bool operator< (const CSettingUpdate &rhs) const
virtual bool Deserialize (const TiXmlNode *node)
SettingUpdateType GetType () const
const std::string & GetValue () const
Private Member Functions
bool setType (const std::string &type)
Private Attributes
SettingUpdateType m_type = SettingUpdateType::Unknown
std::string m_value
Static Private Attributes
static Logger s_logger
Constructor & Destructor Documentation
CSettingUpdate()
CSettingUpdate::CSettingUpdate ()
References CLog::GetLogger(), CServiceBroker::GetLogging(), and s_logger.
~CSettingUpdate()
virtual CSettingUpdate::~CSettingUpdate () virtual default
Member Function Documentation
Deserialize()
bool CSettingUpdate::Deserialize (const TiXmlNode * node) virtual
References m_type, m_value, node, Rename, s_logger, SETTING_XML_ATTR_TYPE, and setType().
Referenced by CSetting::Deserialize().
GetType()
SettingUpdateType CSettingUpdate::GetType () const inline
References m_type.
Referenced by CSettingsManager::UpdateSetting().
GetValue()
const std::string & CSettingUpdate::GetValue () const inline
References m_value.
Referenced by CSettingsManager::UpdateSetting().
operator<()
bool CSettingUpdate::operator< (const CSettingUpdate & rhs) const inline
References m_type, and m_value.
setType()
bool CSettingUpdate::setType (const std::string & type) private
References Change, m_type, and Rename.
Referenced by Deserialize().
Member Data Documentation
m_type
SettingUpdateType CSettingUpdate::m_type = SettingUpdateType::Unknown private
Referenced by Deserialize(), GetType(), operator<(), and setType().
m_value
std::string CSettingUpdate::m_value private
Referenced by Deserialize(), GetValue(), and operator<().
s_logger
Logger CSettingUpdate::s_logger static private
Referenced by CSettingUpdate(), and Deserialize().
The documentation for this class was generated from the following files:
SettingUpdate.h
SettingUpdate.cpp