Kodi Documentation: KODI::GUILIB::GUIINFO::CWeatherGUIInfo Class Reference
KODI::GUILIB::GUIINFO::CWeatherGUIInfo Class Reference
#include <WeatherGUIInfo.h>
Public Member Functions
CWeatherGUIInfo ()=default
~CWeatherGUIInfo () override=default
bool InitCurrentItem (CFileItem *item) override
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) const override
Get a GUIInfoManager label string.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager integer value.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager bool value.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
CGUIInfoProvider ()=default
~CGUIInfoProvider () override=default
bool GetFallbackLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) override
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo) override
Set new audio/video stream info data.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::IGUIInfoProvider
virtual ~IGUIInfoProvider ()=default
Additional Inherited Members
Protected Attributes inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
VideoStreamInfo m_videoInfo
AudioStreamInfo m_audioInfo
SubtitleStreamInfo m_subtitleInfo
Constructor & Destructor Documentation
CWeatherGUIInfo()
KODI::GUILIB::GUIINFO::CWeatherGUIInfo::CWeatherGUIInfo () default
~CWeatherGUIInfo()
KODI::GUILIB::GUIINFO::CWeatherGUIInfo::~CWeatherGUIInfo () override default
Member Function Documentation
GetBool()
bool CWeatherGUIInfo::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager bool value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CServiceBroker::GetWeatherManager(), CWeatherManager::IsFetched(), value, and WEATHER_IS_FETCHED.
GetInt()
bool CWeatherGUIInfo::GetInt (int & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager integer value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
GetLabel()
bool CWeatherGUIInfo::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) const override virtual
Get a GUIInfoManager label string.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References g_langInfo, URIUtils::GetFileName(), CInfoLoader::GetInfo(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWeatherManager(), URIUtils::RemoveExtension(), CSettings::SETTING_WEATHER_ADDON, value, WEATHER_CONDITIONS_ICON, WEATHER_CONDITIONS_TEXT, WEATHER_FANART_CODE, WEATHER_IMAGE_CURRENT_ICON, WEATHER_LABEL_CURRENT_COND, WEATHER_LABEL_CURRENT_TEMP, WEATHER_LABEL_LOCATION, WEATHER_LOCATION, WEATHER_PLUGIN, and WEATHER_TEMPERATURE.
InitCurrentItem()
bool CWeatherGUIInfo::InitCurrentItem (CFileItem * item) override virtual
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by the provider, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
The documentation for this class was generated from the following files:
WeatherGUIInfo.h
WeatherGUIInfo.cpp