Kodi Documentation: CONTEXTMENU::CVideoResume Struct Reference
CONTEXTMENU::CVideoResume Struct Reference
#include <ContextMenus.h>
Public Member Functions
std::string GetLabel (const CFileItem &item) const override
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &_item) const override
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool IsGroup () const
virtual bool HasParent () const
Member Function Documentation
Execute()
bool CONTEXTMENU::CVideoResume::Execute (const std::shared_ptr< CFileItem > & _item) const override virtual
Implements IContextMenuItem.
References KODI::MUSIC::IsCDDA(), and STARTOFFSET_RESUME.
GetLabel()
std::string CONTEXTMENU::CVideoResume::GetLabel (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References CFileItem::GetItemToPlay(), and KODI::VIDEO::UTILS::GetResumeString().
IsVisible()
bool CONTEXTMENU::CVideoResume::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References KODI::VIDEO::UTILS::GetItemResumeInformation(), CFileItem::GetItemToPlay(), CFileItem::IsDeleted(), and KODI::VIDEO::UTILS::ResumeInformation::isResumable.
The documentation for this struct was generated from the following files:
video/ContextMenus.h
video/ContextMenus.cpp