Kodi Documentation: TestFileOperationJob.cpp File Reference
TestFileOperationJob.cpp File Reference
#include "filesystem/Directory.h"
#include "filesystem/File.h"
#include "test/TestUtils.h"
#include "utils/FileOperationJob.h"
#include "utils/URIUtils.h"
#include <gtest/gtest.h>
Functions
TEST (TestFileOperationJob, ActionCopy)
TEST (TestFileOperationJob, ActionMove)
TEST (TestFileOperationJob, ActionDelete)
TEST (TestFileOperationJob, ActionReplace)
TEST (TestFileOperationJob, ActionCreateFolder)
TEST (TestFileOperationJob, ActionDeleteFolder)
TEST (TestFileOperationJob, GetFunctions)
Function Documentation
TEST() [1/7]
TEST (TestFileOperationJob , ActionCopy)
References CFileOperationJob::ActionCopy, CFileItemList::Add(), URIUtils::AddFileToFolder(), ASSERT_NE(), XFILE::CFile::Close(), XFILE::CFile::Delete(), CFileOperationJob::DoWork(), XFILE::CFile::Exists(), EXPECT_EQ(), EXPECT_TRUE(), CFileOperationJob::GetAction(), URIUtils::GetDirectory(), URIUtils::GetFileName(), XFILE::CDirectory::Remove(), CFileOperationJob::SetFileOperation(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [2/7]
TEST (TestFileOperationJob , ActionCreateFolder)
References CFileOperationJob::ActionCreateFolder, CFileItemList::Add(), ASSERT_NE(), XFILE::CFile::Close(), CFileOperationJob::DoWork(), XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), EXPECT_EQ(), EXPECT_TRUE(), CFileOperationJob::GetAction(), CXBMCTestUtils::Instance(), XFILE::CDirectory::Remove(), CFileOperationJob::SetFileOperation(), CXBMCTestUtils::TempFileDirectory(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [3/7]
TEST (TestFileOperationJob , ActionDelete)
References CFileOperationJob::ActionCopy, CFileOperationJob::ActionDelete, CFileItemList::Add(), URIUtils::AddFileToFolder(), ASSERT_NE(), CFileItemList::Clear(), XFILE::CFile::Close(), CFileOperationJob::DoWork(), XFILE::CFile::Exists(), EXPECT_EQ(), EXPECT_TRUE(), CFileOperationJob::GetAction(), URIUtils::GetDirectory(), URIUtils::GetFileName(), XFILE::CDirectory::Remove(), CFileOperationJob::SetFileOperation(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [4/7]
TEST (TestFileOperationJob , ActionDeleteFolder)
References CFileOperationJob::ActionCreateFolder, CFileOperationJob::ActionDeleteFolder, CFileItemList::Add(), ASSERT_NE(), XFILE::CFile::Close(), CFileOperationJob::DoWork(), XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), EXPECT_EQ(), EXPECT_TRUE(), CFileOperationJob::GetAction(), CXBMCTestUtils::Instance(), CFileOperationJob::SetFileOperation(), CXBMCTestUtils::TempFileDirectory(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [5/7]
TEST (TestFileOperationJob , ActionMove)
References CFileOperationJob::ActionMove, CFileItemList::Add(), URIUtils::AddFileToFolder(), ASSERT_NE(), XFILE::CFile::Close(), XFILE::CDirectory::Create(), XFILE::CFile::Delete(), CFileOperationJob::DoWork(), XFILE::CFile::Exists(), EXPECT_EQ(), EXPECT_TRUE(), CFileOperationJob::GetAction(), URIUtils::GetDirectory(), URIUtils::GetFileName(), XFILE::CDirectory::Remove(), CFileOperationJob::SetFileOperation(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [6/7]
TEST (TestFileOperationJob , ActionReplace)
References CFileOperationJob::ActionCopy, CFileOperationJob::ActionReplace, CFileItemList::Add(), URIUtils::AddFileToFolder(), ASSERT_NE(), XFILE::CFile::Close(), XFILE::CFile::Delete(), CFileOperationJob::DoWork(), XFILE::CFile::Exists(), EXPECT_EQ(), EXPECT_TRUE(), CFileOperationJob::GetAction(), URIUtils::GetDirectory(), URIUtils::GetFileName(), XFILE::CDirectory::Remove(), CFileOperationJob::SetFileOperation(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.
TEST() [7/7]
TEST (TestFileOperationJob , GetFunctions)
References CFileOperationJob::ActionCopy, CFileItemList::Add(), URIUtils::AddFileToFolder(), ASSERT_NE(), XFILE::CFile::Close(), XFILE::CFile::Delete(), CFileOperationJob::DoWork(), XFILE::CFile::Exists(), EXPECT_EQ(), EXPECT_TRUE(), CFileOperationJob::GetAction(), CFileOperationJob::GetAverageSpeed(), CFileOperationJob::GetCurrentFile(), CFileOperationJob::GetCurrentOperation(), URIUtils::GetDirectory(), URIUtils::GetFileName(), CFileOperationJob::GetItems(), CFileItemList::IsEmpty(), XFILE::CDirectory::Remove(), CFileOperationJob::SetFileOperation(), XBMC_CREATETEMPFILE, XBMC_DELETETEMPFILE, and XBMC_TEMPFILEPATH.