Kodi Documentation: XFILE::CCacheStrategy Class Reference
XFILE::CCacheStrategy Class Reference abstract
#include <CacheStrategy.h>
Public Member Functions
virtual ~CCacheStrategy ()
virtual int Open ()=0
virtual void Close ()=0
virtual size_t GetMaxWriteSize (const size_t &iRequestSize)=0
virtual int WriteToCache (const char *pBuffer, size_t iSize)=0
virtual int ReadFromCache (char *pBuffer, size_t iMaxSize)=0
virtual int64_t WaitForData (uint32_t iMinAvail, std::chrono::milliseconds timeout)=0
virtual int64_t Seek (int64_t iFilePosition)=0
virtual bool Reset (int64_t iSourcePosition)=0
Reset cache position.
virtual void EndOfInput ()
virtual bool IsEndOfInput ()
virtual void ClearEndOfInput ()
virtual int64_t CachedDataEndPosIfSeekTo (int64_t iFilePosition)=0
virtual int64_t CachedDataStartPos ()=0
virtual int64_t CachedDataEndPos ()=0
virtual bool IsCachedPosition (int64_t iFilePosition)=0
virtual CCacheStrategy * CreateNew ()=0
Public Attributes
CEvent m_space
Protected Attributes
bool m_bEndOfInput = false
Constructor & Destructor Documentation
~CCacheStrategy()
CCacheStrategy::~CCacheStrategy () virtual default
Member Function Documentation
CachedDataEndPos()
virtual int64_t XFILE::CCacheStrategy::CachedDataEndPos () pure virtual
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::CachedDataEndPos(), and XFILE::CDoubleCache::Reset().
CachedDataEndPosIfSeekTo()
virtual int64_t XFILE::CCacheStrategy::CachedDataEndPosIfSeekTo (int64_t iFilePosition) pure virtual
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::CachedDataEndPosIfSeekTo().
CachedDataStartPos()
virtual int64_t XFILE::CCacheStrategy::CachedDataStartPos () pure virtual
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::CachedDataStartPos(), and XFILE::CDoubleCache::Reset().
ClearEndOfInput()
void CCacheStrategy::ClearEndOfInput () virtual
Reimplemented in XFILE::CDoubleCache.
References m_bEndOfInput.
Referenced by XFILE::CDoubleCache::ClearEndOfInput().
Close()
virtual void XFILE::CCacheStrategy::Close () pure virtual
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::Close().
CreateNew()
virtual CCacheStrategy * XFILE::CCacheStrategy::CreateNew () pure virtual
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::CreateNew(), and XFILE::CDoubleCache::Reset().
EndOfInput()
void CCacheStrategy::EndOfInput () virtual
Reimplemented in XFILE::CSimpleFileCache, and XFILE::CDoubleCache.
References m_bEndOfInput.
Referenced by XFILE::CSimpleFileCache::EndOfInput(), and XFILE::CDoubleCache::EndOfInput().
GetMaxWriteSize()
virtual size_t XFILE::CCacheStrategy::GetMaxWriteSize (const size_t & iRequestSize) pure virtual
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::GetMaxWriteSize().
IsCachedPosition()
virtual bool XFILE::CCacheStrategy::IsCachedPosition (int64_t iFilePosition) pure virtual
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::IsCachedPosition(), XFILE::CDoubleCache::Reset(), and XFILE::CDoubleCache::Seek().
IsEndOfInput()
bool CCacheStrategy::IsEndOfInput () virtual
Reimplemented in XFILE::CDoubleCache.
References m_bEndOfInput.
Referenced by XFILE::CDoubleCache::IsEndOfInput(), XFILE::CCircularCache::ReadFromCache(), XFILE::CSimpleFileCache::WaitForData(), and XFILE::CCircularCache::WaitForData().
Open()
virtual int XFILE::CCacheStrategy::Open () pure virtual
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::Open(), and XFILE::CDoubleCache::Reset().
ReadFromCache()
virtual int XFILE::CCacheStrategy::ReadFromCache (char * pBuffer, size_t iMaxSize) pure virtual
Implemented in XFILE::CCircularCache, XFILE::CSimpleFileCache, and XFILE::CDoubleCache.
Referenced by XFILE::CDoubleCache::ReadFromCache().
Reset()
virtual bool XFILE::CCacheStrategy::Reset (int64_t iSourcePosition) pure virtual
Reset cache position.
Parameters
iSourcePosition position to reset to
Returns
Whether a full reset was performed, or not (e.g. only cache swap)
See also
CCacheStrategy
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::Reset().
Seek()
virtual int64_t XFILE::CCacheStrategy::Seek (int64_t iFilePosition) pure virtual
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::Seek().
WaitForData()
virtual int64_t XFILE::CCacheStrategy::WaitForData (uint32_t iMinAvail, std::chrono::milliseconds timeout) pure virtual
Implemented in XFILE::CSimpleFileCache, XFILE::CDoubleCache, and XFILE::CCircularCache.
Referenced by XFILE::CDoubleCache::WaitForData().
WriteToCache()
virtual int XFILE::CCacheStrategy::WriteToCache (const char * pBuffer, size_t iSize) pure virtual
Implemented in XFILE::CCircularCache, XFILE::CSimpleFileCache, and XFILE::CDoubleCache.
Referenced by XFILE::CDoubleCache::WriteToCache().
Member Data Documentation
m_bEndOfInput
bool XFILE::CCacheStrategy::m_bEndOfInput = false protected
Referenced by ClearEndOfInput(), EndOfInput(), IsEndOfInput(), and XFILE::CSimpleFileCache::ReadFromCache().
m_space
CEvent XFILE::CCacheStrategy::m_space
Referenced by XFILE::CCircularCache::ReadFromCache(), XFILE::CSimpleFileCache::ReadFromCache(), and XFILE::CSimpleFileCache::Seek().
The documentation for this class was generated from the following files:
CacheStrategy.h
CacheStrategy.cpp