Kodi Documentation: dxerr.h File Reference
dxerr.h File Reference
#include <Windows.h>
#include <sal.h>
Macros
#define DXGetErrorString DXGetErrorStringW
#define DXGetErrorDescription DXGetErrorDescriptionW
#define DXTrace DXTraceW
#define DXTRACE_MSG(str) (0L)
#define DXTRACE_ERR(str, hr) (hr)
#define DXTRACE_ERR_MSGBOX(str, hr) (hr)
Functions
const WCHAR *WINAPI DXGetErrorStringW (_In_ HRESULT hr)
void WINAPI DXGetErrorDescriptionW (_In_ HRESULT hr, _Out_cap_(count) WCHAR *desc, _In_ size_t count)
HRESULT WINAPI DXTraceW (_In_z_ const WCHAR *strFile, _In_ DWORD dwLine, _In_ HRESULT hr, _In_opt_ const WCHAR *strMsg, _In_ bool bPopMsgBox)
Macro Definition Documentation
DXGetErrorDescription
#define DXGetErrorDescription DXGetErrorDescriptionW
DXGetErrorString
#define DXGetErrorString DXGetErrorStringW
DXTrace
#define DXTrace DXTraceW
DXTRACE_ERR
#define DXTRACE_ERR (str, hr) (hr)
DXTRACE_ERR_MSGBOX
#define DXTRACE_ERR_MSGBOX (str, hr) (hr)
DXTRACE_MSG
#define DXTRACE_MSG (str) (0L)
Function Documentation
DXGetErrorDescriptionW()
void WINAPI DXGetErrorDescriptionW (_In_ HRESULT hr, _Out_cap_(count) WCHAR * desc, _In_ size_t count)
References CHK_ERR, CHK_ERRA, DXUTERR_CREATINGDEVICE, DXUTERR_CREATINGDEVICEOBJECTS, DXUTERR_DEVICEREMOVED, DXUTERR_INCORRECTVERSION, DXUTERR_MEDIANOTFOUND, DXUTERR_NOCOMPATIBLEDEVICES, DXUTERR_NODIRECT3D, DXUTERR_NONZEROREFCOUNT, DXUTERR_RESETTINGDEVICE, DXUTERR_RESETTINGDEVICEOBJECTS, XAPO_E_FORMAT_UNSUPPORTED, XAUDIO2_E_DEVICE_INVALIDATED, XAUDIO2_E_INVALID_CALL, XAUDIO2_E_XAPO_CREATION_FAILED, and XAUDIO2_E_XMA_DECODER_ERROR.
Referenced by CWIN32Util::FormatHRESULT().
DXGetErrorStringW()
const WCHAR *WINAPI DXGetErrorStringW (_In_ HRESULT hr)
References CHK_ERR_WIN32_ONLY, CHK_ERR_WIN32A, CHK_ERRA, DXUTERR_CREATINGDEVICE, DXUTERR_CREATINGDEVICEOBJECTS, DXUTERR_DEVICEREMOVED, DXUTERR_INCORRECTVERSION, DXUTERR_MEDIANOTFOUND, DXUTERR_NOCOMPATIBLEDEVICES, DXUTERR_NODIRECT3D, DXUTERR_NONZEROREFCOUNT, DXUTERR_RESETTINGDEVICE, DXUTERR_RESETTINGDEVICEOBJECTS, WSAECONNRESET, XAPO_E_FORMAT_UNSUPPORTED, XAUDIO2_E_DEVICE_INVALIDATED, XAUDIO2_E_INVALID_CALL, XAUDIO2_E_XAPO_CREATION_FAILED, and XAUDIO2_E_XMA_DECODER_ERROR.
Referenced by DXTraceW(), and CWIN32Util::FormatHRESULT().
DXTraceW()
HRESULT WINAPI DXTraceW (_In_z_ const WCHAR * strFile, _In_ DWORD dwLine, _In_ HRESULT hr, _In_opt_ const WCHAR * strMsg, _In_ bool bPopMsgBox)
References BUFFER_SIZE, DXGetErrorStringW(), and MAX_PATH.