Kodi Documentation: JSONRPC::CSettingsOperations Class Reference
JSONRPC::CSettingsOperations Class Reference
#include <SettingsOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetSections (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetCategories (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetSettings (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetSettingValue (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetSettingValue (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ResetSettingValue (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetSkinSettings (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetSkinSettingValue (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetSkinSettingValue (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Static Private Member Functions
static SettingLevel ParseSettingLevel (const std::string &strLevel)
static bool SerializeISetting (const std::shared_ptr< const ISetting > &setting, CVariant &obj)
static bool SerializeSettingSection (const std::shared_ptr< const CSettingSection > &setting, CVariant &obj)
static bool SerializeSettingCategory (const std::shared_ptr< const CSettingCategory > &setting, CVariant &obj)
static bool SerializeSettingGroup (const std::shared_ptr< const CSettingGroup > &setting, CVariant &obj)
static bool SerializeSetting (const std::shared_ptr< const CSetting > &setting, CVariant &obj)
static bool SerializeSettingBool (const std::shared_ptr< const CSettingBool > &setting, CVariant &obj)
static bool SerializeSettingInt (const std::shared_ptr< const CSettingInt > &setting, CVariant &obj)
static bool SerializeSettingNumber (const std::shared_ptr< const CSettingNumber > &setting, CVariant &obj)
static bool SerializeSettingString (const std::shared_ptr< const CSettingString > &setting, CVariant &obj)
static bool SerializeSettingAction (const std::shared_ptr< const CSettingAction > &setting, CVariant &obj)
static bool SerializeSettingList (const std::shared_ptr< const CSettingList > &setting, CVariant &obj)
static bool SerializeSettingPath (const std::shared_ptr< const CSettingPath > &setting, CVariant &obj)
static bool SerializeSettingAddon (const std::shared_ptr< const CSettingAddon > &setting, CVariant &obj)
static bool SerializeSettingDate (const std::shared_ptr< const CSettingDate > &setting, CVariant &obj)
static bool SerializeSettingTime (const std::shared_ptr< const CSettingTime > &setting, CVariant &obj)
static bool SerializeSettingControl (const std::shared_ptr< const ISettingControl > &control, CVariant &obj)
static void SerializeSettingListValues (const std::vector< CVariant > &values, CVariant &obj)
Member Function Documentation
GetCategories()
JSONRPC_STATUS CSettingsOperations::GetCategories (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), CVariant::empty(), CServiceBroker::GetSettingsComponent(), JSONRPC::InvalidParams, JSONRPC::OK, ParseSettingLevel(), CVariant::push_back(), SerializeSetting(), SerializeSettingCategory(), SerializeSettingGroup(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
GetSections()
JSONRPC_STATUS CSettingsOperations::GetSections (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), CVariant::empty(), CServiceBroker::GetSettingsComponent(), JSONRPC::OK, ParseSettingLevel(), CVariant::push_back(), SerializeSettingCategory(), SerializeSettingSection(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
GetSettings()
JSONRPC_STATUS CSettingsOperations::GetSettings (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), CServiceBroker::GetSettingsComponent(), JSONRPC::InvalidParams, CVariant::isMember(), JSONRPC::OK, ParseSettingLevel(), CVariant::push_back(), SerializeSetting(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by GetSettingValue().
GetSettingValue()
JSONRPC_STATUS CSettingsOperations::GetSettingValue (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References Action, CVariant::asString(), Boolean, GetSettings(), CServiceBroker::GetSettingsComponent(), Integer, JSONRPC::InvalidParams, List, Number, JSONRPC::OK, SerializeSettingListValues(), String, Unknown, and value.
GetSkinSettings()
JSONRPC_STATUS CSettingsOperations::GetSkinSettings (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CSkinSettings::GetInstance(), CSkinSettings::GetSettings(), CServiceBroker::GetSettingsComponent(), JSONRPC::OK, CVariant::push_back(), CSettings::SETTING_LOOKANDFEEL_SKIN, CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
GetSkinSettingValue()
JSONRPC_STATUS CSettingsOperations::GetSkinSettingValue (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), CSkinSettings::GetInstance(), CSkinSettings::GetSetting(), JSONRPC::InvalidParams, JSONRPC::OK, and value.
ParseSettingLevel()
SettingLevel CSettingsOperations::ParseSettingLevel (const std::string & strLevel) static private
References Advanced, Basic, Expert, and Standard.
Referenced by GetCategories(), GetSections(), and GetSettings().
ResetSettingValue()
JSONRPC_STATUS CSettingsOperations::ResetSettingValue (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, Action, CVariant::asString(), Boolean, CServiceBroker::GetSettingsComponent(), Integer, JSONRPC::InvalidParams, List, Number, String, and Unknown.
SerializeISetting()
bool CSettingsOperations::SerializeISetting (const std::shared_ptr< const ISetting > & setting, CVariant & obj) static private
Referenced by SerializeSetting(), SerializeSettingCategory(), SerializeSettingGroup(), and SerializeSettingSection().
SerializeSetting()
bool CSettingsOperations::SerializeSetting (const std::shared_ptr< const CSetting > & setting, CVariant & obj) static private
References Action, Advanced, Basic, Boolean, Expert, g_localizeStrings, CLocalizeStrings::Get(), Integer, List, Number, SerializeISetting(), SerializeSettingAction(), SerializeSettingBool(), SerializeSettingControl(), SerializeSettingInt(), SerializeSettingList(), SerializeSettingNumber(), SerializeSettingString(), Standard, String, and CVariant::VariantTypeObject.
Referenced by GetCategories(), GetSettings(), and SerializeSettingList().
SerializeSettingAction()
bool CSettingsOperations::SerializeSettingAction (const std::shared_ptr< const CSettingAction > & setting, CVariant & obj) static private
Referenced by SerializeSetting().
SerializeSettingAddon()
bool CSettingsOperations::SerializeSettingAddon (const std::shared_ptr< const CSettingAddon > & setting, CVariant & obj) static private
References ADDON::CAddonInfo::TranslateType().
Referenced by SerializeSettingString().
SerializeSettingBool()
bool CSettingsOperations::SerializeSettingBool (const std::shared_ptr< const CSettingBool > & setting, CVariant & obj) static private
Referenced by SerializeSetting().
SerializeSettingCategory()
bool CSettingsOperations::SerializeSettingCategory (const std::shared_ptr< const CSettingCategory > & setting, CVariant & obj) static private
References g_localizeStrings, CLocalizeStrings::Get(), and SerializeISetting().
Referenced by GetCategories(), and GetSections().
SerializeSettingControl()
bool CSettingsOperations::SerializeSettingControl (const std::shared_ptr< const ISettingControl > & control, CVariant & obj) static private
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by SerializeSetting().
SerializeSettingDate()
bool CSettingsOperations::SerializeSettingDate (const std::shared_ptr< const CSettingDate > & setting, CVariant & obj) static private
Referenced by SerializeSettingString().
SerializeSettingGroup()
bool CSettingsOperations::SerializeSettingGroup (const std::shared_ptr< const CSettingGroup > & setting, CVariant & obj) static private
References SerializeISetting().
Referenced by GetCategories().
SerializeSettingInt()
bool CSettingsOperations::SerializeSettingInt (const std::shared_ptr< const CSettingInt > & setting, CVariant & obj) static private
References Dynamic, g_localizeStrings, CLocalizeStrings::Get(), CVariant::push_back(), Static, StaticTranslatable, Unknown, CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by SerializeSetting().
SerializeSettingList()
bool CSettingsOperations::SerializeSettingList (const std::shared_ptr< const CSettingList > & setting, CVariant & obj) static private
References CSettingUtils::GetList(), CSettingUtils::ListToValues(), SerializeSetting(), and SerializeSettingListValues().
Referenced by SerializeSetting().
SerializeSettingListValues()
void CSettingsOperations::SerializeSettingListValues (const std::vector< CVariant > & values, CVariant & obj) static private
References CVariant::push_back(), values, and CVariant::VariantTypeArray.
Referenced by GetSettingValue(), and SerializeSettingList().
SerializeSettingNumber()
bool CSettingsOperations::SerializeSettingNumber (const std::shared_ptr< const CSettingNumber > & setting, CVariant & obj) static private
Referenced by SerializeSetting().
SerializeSettingPath()
bool CSettingsOperations::SerializeSettingPath (const std::shared_ptr< const CSettingPath > & setting, CVariant & obj) static private
Referenced by SerializeSettingString().
SerializeSettingSection()
bool CSettingsOperations::SerializeSettingSection (const std::shared_ptr< const CSettingSection > & setting, CVariant & obj) static private
References g_localizeStrings, CLocalizeStrings::Get(), and SerializeISetting().
Referenced by GetSections().
SerializeSettingString()
bool CSettingsOperations::SerializeSettingString (const std::shared_ptr< const CSettingString > & setting, CVariant & obj) static private
References Dynamic, g_localizeStrings, CLocalizeStrings::Get(), CVariant::push_back(), SerializeSettingAddon(), SerializeSettingDate(), SerializeSettingPath(), SerializeSettingTime(), Static, StaticTranslatable, Unknown, CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by SerializeSetting().
SerializeSettingTime()
bool CSettingsOperations::SerializeSettingTime (const std::shared_ptr< const CSettingTime > & setting, CVariant & obj) static private
Referenced by SerializeSettingString().
SetSettingValue()
JSONRPC_STATUS CSettingsOperations::SetSettingValue (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References Action, CVariant::asString(), Boolean, CServiceBroker::GetSettingsComponent(), Integer, JSONRPC::InvalidParams, List, Number, JSONRPC::OK, String, Unknown, value, and values.
SetSkinSettingValue()
JSONRPC_STATUS CSettingsOperations::SetSkinSettingValue (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asBoolean(), CVariant::asString(), CSkinSettings::GetInstance(), CSkinSettings::GetSetting(), JSONRPC::InvalidParams, JSONRPC::OK, and value.
The documentation for this class was generated from the following files:
SettingsOperations.h
SettingsOperations.cpp