Kodi Documentation: PVR::CPVRChannelGroupImageFileLoader Class Reference
PVR::CPVRChannelGroupImageFileLoader Class Reference
Generates a thumbnail for a PVR channel group; tile up to 9 channel icons in the group.
#include <PVRChannelGroupImageFileLoader.h>
Public Member Functions
CPVRChannelGroupImageFileLoader ()=default
~CPVRChannelGroupImageFileLoader () override=default
bool CanLoad (const std::string &specialType) const override
std::unique_ptr< CTexture > Load (const IMAGE_FILES::CImageFileURL &imageFile) const override
Public Member Functions inherited from IMAGE_FILES::ISpecialImageFileLoader
virtual ~ISpecialImageFileLoader ()=default
Detailed Description
Generates a thumbnail for a PVR channel group; tile up to 9 channel icons in the group.
Constructor & Destructor Documentation
CPVRChannelGroupImageFileLoader()
PVR::CPVRChannelGroupImageFileLoader::CPVRChannelGroupImageFileLoader () default
~CPVRChannelGroupImageFileLoader()
PVR::CPVRChannelGroupImageFileLoader::~CPVRChannelGroupImageFileLoader () override default
Member Function Documentation
CanLoad()
bool PVR::CPVRChannelGroupImageFileLoader::CanLoad (const std::string & specialType) const override virtual
Implements IMAGE_FILES::ISpecialImageFileLoader.
Load()
std::unique_ptr< CTexture > PVR::CPVRChannelGroupImageFileLoader::Load (const IMAGE_FILES::CImageFileURL & imageFile) const override virtual
Implements IMAGE_FILES::ISpecialImageFileLoader.
References CPicture::CreateTiledThumb(), CGUIListItem::GetArt(), PVR::CPVRGUIDirectory::GetChannelsDirectory(), and IMAGE_FILES::CImageFileURL::GetTargetFile().
The documentation for this class was generated from the following files:
PVRChannelGroupImageFileLoader.h
PVRChannelGroupImageFileLoader.cpp