Kodi Documentation: CZeroconfBrowserMDNS Class Reference
CZeroconfBrowserMDNS Class Reference
#include <ZeroconfBrowserMDNS.h>
Public Member Functions
CZeroconfBrowserMDNS ()
~CZeroconfBrowserMDNS ()
Public Member Functions inherited from CZeroconfBrowser
void Start ()
void Stop ()
std::vector< ZeroconfService > GetFoundServices ()
bool ResolveService (ZeroconfService &fr_service, double f_timeout=1.0)
bool AddServiceType (const std::string &fcr_service_type)
bool RemoveServiceType (const std::string &fcr_service_type)
Private Types
typedef std::map< std::string, DNSServiceRef > tBrowserMap
typedef std::map< DNSServiceRef, std::vector< std::pair< ZeroconfService, unsigned int > > > tDiscoveredServicesMap
Private Member Functions
void addDiscoveredService (DNSServiceRef browser, CZeroconfBrowser::ZeroconfService const &fcr_service)
adds the service to list of found services
void removeDiscoveredService (DNSServiceRef browser, CZeroconfBrowser::ZeroconfService const &fcr_service)
removes the service from list of found services
void ProcessResults ()
virtual bool doAddServiceType (const std::string &fcr_service_type)
virtual bool doRemoveServiceType (const std::string &fcr_service_type)
virtual std::vector< CZeroconfBrowser::ZeroconfService > doGetFoundServices ()
virtual bool doResolveService (CZeroconfBrowser::ZeroconfService &fr_service, double f_timeout)
Static Private Member Functions
static void DNSSD_API BrowserCallback (DNSServiceRef browser, DNSServiceFlags flags, uint32_t interfaceIndex, DNSServiceErrorType errorCode, const char *serviceName, const char *regtype, const char *replyDomain, void *context)
browser callback
static void DNSSD_API GetAddrInfoCallback (DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t interfaceIndex, DNSServiceErrorType errorCode, const char *hostname, const struct sockaddr *address, uint32_t ttl, void *context)
GetAddrInfo callback.
static void DNSSD_API ResolveCallback (DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t interfaceIndex, DNSServiceErrorType errorCode, const char *fullname, const char *hosttarget, uint16_t port, uint16_t txtLen, const unsigned char *txtRecord, void *context)
resolve callback
Private Attributes
CCriticalSection m_data_guard
tBrowserMap m_service_browsers
tDiscoveredServicesMap m_discovered_services
DNSServiceRef m_browser
CZeroconfBrowser::ZeroconfService m_resolving_service
CEvent m_resolved_event
CEvent m_addrinfo_event
Additional Inherited Members
Static Public Member Functions inherited from CZeroconfBrowser
static CZeroconfBrowser * GetInstance ()
static void ReleaseInstance ()
static bool IsInstantiated ()
Protected Member Functions inherited from CZeroconfBrowser
CZeroconfBrowser (const CZeroconfBrowser &)=delete
CZeroconfBrowser & operator= (const CZeroconfBrowser &)=delete
Member Typedef Documentation
tBrowserMap
typedef std::map<std::string, DNSServiceRef> CZeroconfBrowserMDNS::tBrowserMap private
tDiscoveredServicesMap
typedef std::map<DNSServiceRef, std::vector<std::pair<ZeroconfService, unsigned int> > > CZeroconfBrowserMDNS::tDiscoveredServicesMap private
Constructor & Destructor Documentation
CZeroconfBrowserMDNS()
CZeroconfBrowserMDNS::CZeroconfBrowserMDNS ()
References m_browser.
~CZeroconfBrowserMDNS()
CZeroconfBrowserMDNS::~CZeroconfBrowserMDNS ()
References BONJOUR_BROWSER_EVENT, doRemoveServiceType(), g_hWnd, CLog::Log(), LOGDEBUG, m_browser, m_data_guard, and m_service_browsers.
Member Function Documentation
addDiscoveredService()
void CZeroconfBrowserMDNS::addDiscoveredService (DNSServiceRef browser, CZeroconfBrowser::ZeroconfService const & fcr_service) private
adds the service to list of found services
References m_data_guard, and m_discovered_services.
Referenced by BrowserCallback().
BrowserCallback()
void DNSSD_API CZeroconfBrowserMDNS::BrowserCallback (DNSServiceRef browser, DNSServiceFlags flags, uint32_t interfaceIndex, DNSServiceErrorType errorCode, const char * serviceName, const char * regtype, const char * replyDomain, void * context) static private
browser callback
References addDiscoveredService(), CServiceBroker::GetAnnouncementManager(), CZeroconfBrowser::ZeroconfService::GetDomain(), CZeroconfBrowser::ZeroconfService::GetName(), CZeroconfBrowser::ZeroconfService::GetType(), CLog::Log(), LOGDEBUG, LOGERROR, removeDiscoveredService(), and ANNOUNCEMENT::Sources.
Referenced by doAddServiceType().
doAddServiceType()
bool CZeroconfBrowserMDNS::doAddServiceType (const std::string & fcr_service_type) private virtual
implementation if CZeroconfBrowser interface
HAS_MDNS_EMBEDDED
Implements CZeroconfBrowser.
References BONJOUR_BROWSER_EVENT, BrowserCallback(), err(), g_hWnd, CLog::Log(), LOGERROR, m_browser, m_data_guard, and m_service_browsers.
doGetFoundServices()
std::vector< CZeroconfBrowser::ZeroconfService > CZeroconfBrowserMDNS::doGetFoundServices () private virtual
Implements CZeroconfBrowser.
References m_data_guard, and m_discovered_services.
doRemoveServiceType()
bool CZeroconfBrowserMDNS::doRemoveServiceType (const std::string & fcr_service_type) private virtual
Implements CZeroconfBrowser.
References m_data_guard, m_discovered_services, and m_service_browsers.
Referenced by ~CZeroconfBrowserMDNS().
doResolveService()
bool CZeroconfBrowserMDNS::doResolveService (CZeroconfBrowser::ZeroconfService & fr_service, double f_timeout) private virtual
Implements CZeroconfBrowser.
References err(), GetAddrInfoCallback(), CZeroconfBrowser::ZeroconfService::GetDomain(), CZeroconfBrowser::ZeroconfService::GetHostname(), CZeroconfBrowser::ZeroconfService::GetIP(), CZeroconfBrowser::ZeroconfService::GetName(), CZeroconfBrowser::ZeroconfService::GetType(), CLog::Log(), LOGERROR, LOGWARNING, CDNSNameCache::Lookup(), m_addrinfo_event, m_resolved_event, m_resolving_service, CEvent::Reset(), ResolveCallback(), CZeroconfBrowser::ZeroconfService::SetIP(), and CEvent::Wait().
GetAddrInfoCallback()
void DNSSD_API CZeroconfBrowserMDNS::GetAddrInfoCallback (DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t interfaceIndex, DNSServiceErrorType errorCode, const char * hostname, const struct sockaddr * address, uint32_t ttl, void * context) static private
GetAddrInfo callback.
References CLog::Log(), LOGERROR, m_addrinfo_event, m_resolving_service, CEvent::Set(), and CZeroconfBrowser::ZeroconfService::SetIP().
Referenced by doResolveService().
ProcessResults()
void CZeroconfBrowserMDNS::ProcessResults () private virtual
Reimplemented from CZeroconfBrowser.
References err(), CLog::Log(), LOGERROR, m_browser, and m_data_guard.
removeDiscoveredService()
void CZeroconfBrowserMDNS::removeDiscoveredService (DNSServiceRef browser, CZeroconfBrowser::ZeroconfService const & fcr_service) private
removes the service from list of found services
References m_data_guard, and m_discovered_services.
Referenced by BrowserCallback().
ResolveCallback()
void DNSSD_API CZeroconfBrowserMDNS::ResolveCallback (DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t interfaceIndex, DNSServiceErrorType errorCode, const char * fullname, const char * hosttarget, uint16_t port, uint16_t txtLen, const unsigned char * txtRecord, void * context) static private
resolve callback
References err(), CLog::Log(), LOGERROR, m_resolved_event, m_resolving_service, CEvent::Set(), CZeroconfBrowser::ZeroconfService::SetHostname(), CZeroconfBrowser::ZeroconfService::SetPort(), CZeroconfBrowser::ZeroconfService::SetTxtRecords(), and value.
Referenced by doResolveService().
Member Data Documentation
m_addrinfo_event
CEvent CZeroconfBrowserMDNS::m_addrinfo_event private
Referenced by doResolveService(), and GetAddrInfoCallback().
m_browser
DNSServiceRef CZeroconfBrowserMDNS::m_browser private
Referenced by CZeroconfBrowserMDNS(), doAddServiceType(), ProcessResults(), and ~CZeroconfBrowserMDNS().
m_data_guard
CCriticalSection CZeroconfBrowserMDNS::m_data_guard private
Referenced by addDiscoveredService(), doAddServiceType(), doGetFoundServices(), doRemoveServiceType(), ProcessResults(), removeDiscoveredService(), and ~CZeroconfBrowserMDNS().
m_discovered_services
tDiscoveredServicesMap CZeroconfBrowserMDNS::m_discovered_services private
Referenced by addDiscoveredService(), doGetFoundServices(), doRemoveServiceType(), and removeDiscoveredService().
m_resolved_event
CEvent CZeroconfBrowserMDNS::m_resolved_event private
Referenced by doResolveService(), and ResolveCallback().
m_resolving_service
CZeroconfBrowser::ZeroconfService CZeroconfBrowserMDNS::m_resolving_service private
Referenced by doResolveService(), GetAddrInfoCallback(), and ResolveCallback().
m_service_browsers
tBrowserMap CZeroconfBrowserMDNS::m_service_browsers private
Referenced by doAddServiceType(), doRemoveServiceType(), and ~CZeroconfBrowserMDNS().
The documentation for this class was generated from the following files:
ZeroconfBrowserMDNS.h
ZeroconfBrowserMDNS.cpp