Kodi Documentation: jni::CJNIXBMCSpeechRecognitionListener Class Reference
jni::CJNIXBMCSpeechRecognitionListener Class Reference
#include <JNIXBMCSpeechRecognitionListener.h>
Public Member Functions
CJNIXBMCSpeechRecognitionListener ()
~CJNIXBMCSpeechRecognitionListener () override
void onReadyForSpeech (CJNIBundle bundle) override
void onError (int error) override
void onResults (CJNIBundle bundle) override
Static Public Member Functions
static void RegisterNatives (JNIEnv *env)
Static Protected Member Functions
static void _onReadyForSpeech (JNIEnv *env, jobject thiz, jobject bundle)
static void _onError (JNIEnv *env, jobject thiz, jint i)
static void _onResults (JNIEnv *env, jobject thiz, jobject bundle)
Constructor & Destructor Documentation
CJNIXBMCSpeechRecognitionListener()
CJNIXBMCSpeechRecognitionListener::CJNIXBMCSpeechRecognitionListener ()
References s_className.
~CJNIXBMCSpeechRecognitionListener()
CJNIXBMCSpeechRecognitionListener::~CJNIXBMCSpeechRecognitionListener () override
Member Function Documentation
_onError()
void CJNIXBMCSpeechRecognitionListener::_onError (JNIEnv * env, jobject thiz, jint i) static protected
References LOGERROR, and onError().
Referenced by RegisterNatives().
_onReadyForSpeech()
void CJNIXBMCSpeechRecognitionListener::_onReadyForSpeech (JNIEnv * env, jobject thiz, jobject bundle) static protected
References LOGERROR, and onReadyForSpeech().
Referenced by RegisterNatives().
_onResults()
void CJNIXBMCSpeechRecognitionListener::_onResults (JNIEnv * env, jobject thiz, jobject bundle) static protected
References LOGERROR, and onResults().
Referenced by RegisterNatives().
onError()
void jni::CJNIXBMCSpeechRecognitionListener::onError (int error) inline override
Referenced by _onError().
onReadyForSpeech()
void jni::CJNIXBMCSpeechRecognitionListener::onReadyForSpeech (CJNIBundle bundle) inline override
Referenced by _onReadyForSpeech().
onResults()
void jni::CJNIXBMCSpeechRecognitionListener::onResults (CJNIBundle bundle) inline override
Referenced by _onResults().
RegisterNatives()
void CJNIXBMCSpeechRecognitionListener::RegisterNatives (JNIEnv * env) static
References _onError(), _onReadyForSpeech(), _onResults(), and s_className.
Referenced by JNI_OnLoad().
The documentation for this class was generated from the following files:
JNIXBMCSpeechRecognitionListener.h
JNIXBMCSpeechRecognitionListener.cpp