Kodi Documentation: CharVecBuffer Class Reference
CharVecBuffer Class Reference
Public Member Functions
CharVecBuffer (const Buffer &buf)
CharVecBuffer (const std::vector< char > &vec)
operator std::vector< char > () const
Public Member Functions inherited from XbmcCommons::Buffer
Buffer ()
Buffer (void *buffer_, size_t bufferSize)
Buffer (size_t bufferSize)
Buffer (const Buffer &buf)=default
Buffer & operator= (const Buffer &buf)
Buffer & allocate (size_t bufferSize)
Buffer & flip ()
Buffer & clear ()
Buffer & rewind ()
size_t remaining () const
Buffer & put (const void *src, size_t bytes)
Buffer & get (void *dest, size_t bytes)
unsigned char * data () const
unsigned char * curPosition () const
Buffer & setPosition (size_t position)
Buffer & forward (size_t positionIncrement)
size_t limit () const
size_t capacity () const
size_t position () const
DEFAULTBUFFERRELATIVERW (Bool, bool)
DEFAULTBUFFERRELATIVERW (Int, int)
DEFAULTBUFFERRELATIVERW (Char, char)
DEFAULTBUFFERRELATIVERW (Long, long)
DEFAULTBUFFERRELATIVERW (Float, float)
DEFAULTBUFFERRELATIVERW (Double, double)
DEFAULTBUFFERRELATIVERW (Pointer, void *)
DEFAULTBUFFERRELATIVERW (LongLong, long long)
Buffer & putString (const char *str)
Buffer & putString (const std::string &str)
std::string getString ()
std::string getString (size_t length)
char * getCharPointerDirect ()
Constructor & Destructor Documentation
CharVecBuffer() [1/2]
CharVecBuffer::CharVecBuffer (const Buffer & buf) inline
CharVecBuffer() [2/2]
CharVecBuffer::CharVecBuffer (const std::vector< char > & vec) inline
References XbmcCommons::Buffer::data().
Member Function Documentation
operator std::vector< char >()
CharVecBuffer::operator std::vector< char > () const inline
References XbmcCommons::Buffer::capacity(), and XbmcCommons::Buffer::data().
The documentation for this class was generated from the following file:
MediaDrmCryptoSession.cpp