Kodi Documentation: XFILE::CDoubleCache Class Reference
XFILE::CDoubleCache Class Reference
#include <CacheStrategy.h>
Public Member Functions
CDoubleCache (CCacheStrategy *impl)
~CDoubleCache () override
int Open () override
void Close () override
size_t GetMaxWriteSize (const size_t &iRequestSize) override
int WriteToCache (const char *pBuffer, size_t iSize) override
int ReadFromCache (char *pBuffer, size_t iMaxSize) override
int64_t WaitForData (uint32_t iMinAvail, std::chrono::milliseconds timeout) override
int64_t Seek (int64_t iFilePosition) override
bool Reset (int64_t iSourcePosition) override
Reset cache position.
void EndOfInput () override
bool IsEndOfInput () override
void ClearEndOfInput () override
int64_t CachedDataEndPosIfSeekTo (int64_t iFilePosition) override
int64_t CachedDataStartPos () override
int64_t CachedDataEndPos () override
bool IsCachedPosition (int64_t iFilePosition) override
CCacheStrategy * CreateNew () override
Public Member Functions inherited from XFILE::CCacheStrategy
virtual ~CCacheStrategy ()
Protected Attributes
CCacheStrategy * m_pCache
CCacheStrategy * m_pCacheOld
Protected Attributes inherited from XFILE::CCacheStrategy
bool m_bEndOfInput = false
Additional Inherited Members
Public Attributes inherited from XFILE::CCacheStrategy
CEvent m_space
Constructor & Destructor Documentation
CDoubleCache()
CDoubleCache::CDoubleCache (CCacheStrategy * impl) explicit
References m_pCache, and m_pCacheOld.
~CDoubleCache()
CDoubleCache::~CDoubleCache () override
References m_pCache, and m_pCacheOld.
Member Function Documentation
CachedDataEndPos()
int64_t CDoubleCache::CachedDataEndPos () override virtual
Implements XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::CachedDataEndPos(), and m_pCache.
CachedDataEndPosIfSeekTo()
int64_t CDoubleCache::CachedDataEndPosIfSeekTo (int64_t iFilePosition) override virtual
Implements XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::CachedDataEndPosIfSeekTo(), int64_t(), m_pCache, and m_pCacheOld.
CachedDataStartPos()
int64_t CDoubleCache::CachedDataStartPos () override virtual
Implements XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::CachedDataStartPos(), and m_pCache.
ClearEndOfInput()
void CDoubleCache::ClearEndOfInput () override virtual
Reimplemented from XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::ClearEndOfInput(), and m_pCache.
Close()
void CDoubleCache::Close () override virtual
Implements XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::Close(), m_pCache, and m_pCacheOld.
CreateNew()
CCacheStrategy * CDoubleCache::CreateNew () override virtual
Implements XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::CreateNew(), and m_pCache.
EndOfInput()
void CDoubleCache::EndOfInput () override virtual
Reimplemented from XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::EndOfInput(), and m_pCache.
GetMaxWriteSize()
size_t CDoubleCache::GetMaxWriteSize (const size_t & iRequestSize) override virtual
Implements XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::GetMaxWriteSize(), and m_pCache.
IsCachedPosition()
bool CDoubleCache::IsCachedPosition (int64_t iFilePosition) override virtual
Implements XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::IsCachedPosition(), m_pCache, and m_pCacheOld.
IsEndOfInput()
bool CDoubleCache::IsEndOfInput () override virtual
Reimplemented from XFILE::CCacheStrategy.
References XFILE::CCacheStrategy::IsEndOfInput(), and m_pCache.
Open()
int CDoubleCache::Open () override virtual
Implements XFILE::CCacheStrategy.
References m_pCache, and XFILE::CCacheStrategy::Open().
ReadFromCache()
int CDoubleCache::ReadFromCache (char * pBuffer, size_t iMaxSize) override virtual
Implements XFILE::CCacheStrategy.
References m_pCache, and XFILE::CCacheStrategy::ReadFromCache().
Reset()
bool CDoubleCache::Reset (int64_t iSourcePosition) override virtual
Reset cache position.
Parameters
iSourcePosition position to reset to
Returns
Whether a full reset was performed, or not (e.g. only cache swap)
See also
CCacheStrategy
Implements XFILE::CCacheStrategy.
References CACHE_RC_OK, XFILE::CCacheStrategy::CachedDataEndPos(), XFILE::CCacheStrategy::CachedDataStartPos(), XFILE::CCacheStrategy::CreateNew(), XFILE::CCacheStrategy::IsCachedPosition(), CLog::Log(), LOGDEBUG, m_pCache, m_pCacheOld, XFILE::CCacheStrategy::Open(), and XFILE::CCacheStrategy::Reset().
Seek()
int64_t CDoubleCache::Seek (int64_t iFilePosition) override virtual
Implements XFILE::CCacheStrategy.
References CACHE_RC_ERROR, XFILE::CCacheStrategy::IsCachedPosition(), m_pCache, m_pCacheOld, and XFILE::CCacheStrategy::Seek().
WaitForData()
int64_t CDoubleCache::WaitForData (uint32_t iMinAvail, std::chrono::milliseconds timeout) override virtual
Implements XFILE::CCacheStrategy.
References m_pCache, and XFILE::CCacheStrategy::WaitForData().
WriteToCache()
int CDoubleCache::WriteToCache (const char * pBuffer, size_t iSize) override virtual
Implements XFILE::CCacheStrategy.
References m_pCache, and XFILE::CCacheStrategy::WriteToCache().
Member Data Documentation
m_pCache
CCacheStrategy* XFILE::CDoubleCache::m_pCache protected
Referenced by CachedDataEndPos(), CachedDataEndPosIfSeekTo(), CachedDataStartPos(), CDoubleCache(), ClearEndOfInput(), Close(), CreateNew(), EndOfInput(), GetMaxWriteSize(), IsCachedPosition(), IsEndOfInput(), Open(), ReadFromCache(), Reset(), Seek(), WaitForData(), WriteToCache(), and ~CDoubleCache().
m_pCacheOld
CCacheStrategy* XFILE::CDoubleCache::m_pCacheOld protected
Referenced by CachedDataEndPosIfSeekTo(), CDoubleCache(), Close(), IsCachedPosition(), Reset(), Seek(), and ~CDoubleCache().
The documentation for this class was generated from the following files:
CacheStrategy.h
CacheStrategy.cpp