Kodi Documentation: CGUIMultiImage Class Reference
CGUIMultiImage Class Reference
Guilib classes » Window Reference » Controls
#include <GUIMultiImage.h>
Classes
class CMultiImageJob
Public Member Functions
CGUIMultiImage (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo &texture, unsigned int timePerImage, unsigned int fadeTime, bool randomized, bool loop, unsigned int timeToPauseAtEnd)
CGUIMultiImage (const CGUIMultiImage &from)
~CGUIMultiImage (void) override
CGUIMultiImage * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void UpdateVisibility (const CGUIListItem *item=NULL) override
void UpdateInfo (const CGUIListItem *item=NULL) override
bool OnAction (const CAction &action) override
bool OnMessage (CGUIMessage &message) override
void AllocResources () override
void FreeResources (bool immediately=false) override
void DynamicResourceAlloc (bool bOnOff) override
bool IsDynamicallyAllocated () override
void SetInvalid () override
bool CanFocus () const override
std::string GetDescription () const override
void SetInfo (const KODI::GUILIB::GUIINFO::CGUIInfoLabel &info)
void SetAspectRatio (const CAspectRatio &ratio)
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
Perform a mouse action.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Protected Types
enum DIRECTORY_STATUS { UNLOADED = 0 , LOADING , LOADED , READY }
Protected Member Functions
void LoadDirectory ()
void OnDirectoryLoaded ()
void CancelLoading ()
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_texturePath
std::string m_currentPath
unsigned int m_currentImage
CStopWatch m_imageTimer
unsigned int m_timePerImage
unsigned int m_timeToPauseAtEnd
bool m_randomized
bool m_loop
bool m_bDynamicResourceAlloc
std::vector< std::string > m_files
CGUIImage m_image
CCriticalSection m_section
DIRECTORY_STATUS m_directoryStatus
unsigned int m_jobID
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Enumeration Documentation
DIRECTORY_STATUS
enum CGUIMultiImage::DIRECTORY_STATUS protected
Enumerator
UNLOADED
LOADING
LOADED
READY
Constructor & Destructor Documentation
CGUIMultiImage() [1/2]
CGUIMultiImage::CGUIMultiImage (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo & texture, unsigned int timePerImage, unsigned int fadeTime, bool randomized, bool loop, unsigned int timeToPauseAtEnd)
References CGUIControl::ControlType, CGUIControl::GUICONTROL_MULTI_IMAGE, m_bDynamicResourceAlloc, m_currentImage, m_directoryStatus, m_image, m_jobID, m_loop, m_randomized, m_timePerImage, m_timeToPauseAtEnd, CGUIImage::SetCrossFade(), and UNLOADED.
CGUIMultiImage() [2/2]
CGUIMultiImage::CGUIMultiImage (const CGUIMultiImage & from)
References CGUIControl::ControlType, KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), CGUIControl::GUICONTROL_MULTI_IMAGE, KODI::GUILIB::GUIINFO::CGUIInfoLabel::IsConstant(), m_bDynamicResourceAlloc, m_currentImage, m_currentPath, m_directoryStatus, m_jobID, m_loop, m_randomized, m_texturePath, m_timePerImage, m_timeToPauseAtEnd, UNLOADED, and WINDOW_INVALID.
~CGUIMultiImage()
CGUIMultiImage::~CGUIMultiImage (void) override
References CancelLoading().
Member Function Documentation
AllocResources()
void CGUIMultiImage::AllocResources () override virtual
Reimplemented from CGUIControl.
References CGUIControl::AllocResources(), FreeResources(), LoadDirectory(), m_directoryStatus, and UNLOADED.
Referenced by UpdateVisibility().
CancelLoading()
void CGUIMultiImage::CancelLoading () protected
References CServiceBroker::GetJobManager(), LOADING, m_directoryStatus, m_jobID, m_section, and UNLOADED.
Referenced by FreeResources(), UpdateInfo(), and ~CGUIMultiImage().
CanFocus()
bool CGUIMultiImage::CanFocus () const override virtual
Reimplemented from CGUIControl.
Clone()
CGUIMultiImage * CGUIMultiImage::Clone (void) const inline override virtual
Implements CGUIControl.
DynamicResourceAlloc()
void CGUIMultiImage::DynamicResourceAlloc (bool bOnOff) override virtual
Reimplemented from CGUIControl.
References CGUIControl::DynamicResourceAlloc(), and m_bDynamicResourceAlloc.
FreeResources()
void CGUIMultiImage::FreeResources (bool immediately = false) override virtual
Reimplemented from CGUIControl.
References CancelLoading(), CGUIControl::FreeResources(), CGUIImage::FreeResources(), m_currentImage, m_files, and m_image.
Referenced by AllocResources(), OnMessage(), and UpdateVisibility().
GetDescription()
std::string CGUIMultiImage::GetDescription (void) const override virtual
Reimplemented from CGUIControl.
References CGUIImage::GetDescription(), and m_image.
IsDynamicallyAllocated()
bool CGUIMultiImage::IsDynamicallyAllocated () inline override virtual
Reimplemented from CGUIControl.
References m_bDynamicResourceAlloc.
LoadDirectory()
void CGUIMultiImage::LoadDirectory () protected
References CGUITextureManager::GetBundledTexturesFromPath(), CServiceBroker::GetGUI(), CServiceBroker::GetJobManager(), CServiceBroker::GetTextureCache(), CGUIComponent::GetTextureManager(), CFileItem::IsPicture(), LOADING, m_currentPath, m_directoryStatus, m_files, m_jobID, m_section, OnDirectoryLoaded(), and CJob::PRIORITY_NORMAL.
Referenced by AllocResources(), and UpdateVisibility().
OnAction()
bool CGUIMultiImage::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControl.
OnDirectoryLoaded()
void CGUIMultiImage::OnDirectoryLoaded () protected
References m_currentImage, m_directoryStatus, m_files, m_image, m_imageTimer, m_randomized, KODI::UTILS::RandomShuffle(), READY, CGUIImage::SetFileName(), and CStopWatch::StartZero().
Referenced by LoadDirectory(), and UpdateVisibility().
OnJobComplete()
void CGUIMultiImage::OnJobComplete (unsigned int jobID, bool success, CJob * job) override protected virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
References CJob::GetType(), LOADED, LOADING, m_directoryStatus, m_files, and m_section.
OnMessage()
bool CGUIMultiImage::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControl.
References FreeResources(), CGUIMessage::GetMessage(), GUI_MSG_REFRESH_THUMBS, KODI::GUILIB::GUIINFO::CGUIInfoLabel::IsConstant(), m_texturePath, and CGUIControl::OnMessage().
Process()
void CGUIMultiImage::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
References CGUIControl::DoProcess(), CStopWatch::GetElapsedMilliseconds(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CStopWatch::IsRunning(), LOADING, m_currentImage, CGUIControl::m_diffuseColor, m_directoryStatus, m_files, CGUIControl::m_height, m_image, m_imageTimer, m_loop, CGUIControl::m_posX, CGUIControl::m_posY, m_timePerImage, m_timeToPauseAtEnd, CGUIControl::m_width, CGUIControl::MarkDirtyRegion(), CGUIControl::Process(), READY, CGraphicContext::RestoreClipRegion(), CGUIControl::SetColorDiffuse(), CGUIImage::SetFileName(), and CStopWatch::StartZero().
Render()
void CGUIMultiImage::Render () override virtual
Reimplemented from CGUIControl.
References m_image, CGUIControl::Render(), and CGUIImage::Render().
SetAspectRatio()
void CGUIMultiImage::SetAspectRatio (const CAspectRatio & ratio)
References m_image, and CGUIImage::SetAspectRatio().
SetInfo()
void CGUIMultiImage::SetInfo (const KODI::GUILIB::GUIINFO::CGUIInfoLabel & info)
References KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::IsConstant(), m_currentPath, m_texturePath, and WINDOW_INVALID.
SetInvalid()
void CGUIMultiImage::SetInvalid () override virtual
Reimplemented from CGUIControl.
References m_image, CGUIControl::SetInvalid(), and CGUIImage::SetInvalid().
UpdateInfo()
void CGUIMultiImage::UpdateInfo (const CGUIListItem * item = NULL) override virtual
Reimplemented from CGUIControl.
References CancelLoading(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetItemLabel(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::IsConstant(), m_currentPath, CGUIControl::m_parentID, and m_texturePath.
UpdateVisibility()
void CGUIMultiImage::UpdateVisibility (const CGUIListItem * item = NULL) override virtual
Reimplemented from CGUIControl.
References AllocResources(), CGUIControl::DELAYED, FreeResources(), CGUIControl::IsVisible(), LoadDirectory(), LOADED, CGUIControl::m_bAllocated, m_bDynamicResourceAlloc, m_directoryStatus, CGUIControl::m_visible, OnDirectoryLoaded(), UNLOADED, and CGUIControl::UpdateVisibility().
Member Data Documentation
m_bDynamicResourceAlloc
bool CGUIMultiImage::m_bDynamicResourceAlloc protected
Referenced by CGUIMultiImage(), CGUIMultiImage(), DynamicResourceAlloc(), IsDynamicallyAllocated(), and UpdateVisibility().
m_currentImage
unsigned int CGUIMultiImage::m_currentImage protected
Referenced by CGUIMultiImage(), CGUIMultiImage(), FreeResources(), OnDirectoryLoaded(), and Process().
m_currentPath
std::string CGUIMultiImage::m_currentPath protected
Referenced by CGUIMultiImage(), LoadDirectory(), SetInfo(), and UpdateInfo().
m_directoryStatus
DIRECTORY_STATUS CGUIMultiImage::m_directoryStatus protected
Referenced by AllocResources(), CancelLoading(), CGUIMultiImage(), CGUIMultiImage(), LoadDirectory(), OnDirectoryLoaded(), OnJobComplete(), Process(), and UpdateVisibility().
m_files
std::vector<std::string> CGUIMultiImage::m_files protected
Referenced by CGUIMultiImage::CMultiImageJob::DoWork(), FreeResources(), LoadDirectory(), OnDirectoryLoaded(), OnJobComplete(), and Process().
m_image
CGUIImage CGUIMultiImage::m_image protected
Referenced by CGUIMultiImage(), FreeResources(), GetDescription(), OnDirectoryLoaded(), Process(), Render(), SetAspectRatio(), and SetInvalid().
m_imageTimer
CStopWatch CGUIMultiImage::m_imageTimer protected
Referenced by OnDirectoryLoaded(), and Process().
m_jobID
unsigned int CGUIMultiImage::m_jobID protected
Referenced by CancelLoading(), CGUIMultiImage(), CGUIMultiImage(), and LoadDirectory().
m_loop
bool CGUIMultiImage::m_loop protected
Referenced by CGUIMultiImage(), CGUIMultiImage(), and Process().
m_randomized
bool CGUIMultiImage::m_randomized protected
Referenced by CGUIMultiImage(), CGUIMultiImage(), and OnDirectoryLoaded().
m_section
CCriticalSection CGUIMultiImage::m_section protected
Referenced by CancelLoading(), LoadDirectory(), and OnJobComplete().
m_texturePath
KODI::GUILIB::GUIINFO::CGUIInfoLabel CGUIMultiImage::m_texturePath protected
Referenced by CGUIMultiImage(), OnMessage(), SetInfo(), and UpdateInfo().
m_timePerImage
unsigned int CGUIMultiImage::m_timePerImage protected
Referenced by CGUIMultiImage(), CGUIMultiImage(), and Process().
m_timeToPauseAtEnd
unsigned int CGUIMultiImage::m_timeToPauseAtEnd protected
Referenced by CGUIMultiImage(), CGUIMultiImage(), and Process().
The documentation for this class was generated from the following files:
GUIMultiImage.h
GUIMultiImage.cpp