Kodi Documentation: DVDDemuxSPU.cpp File Reference
DVDDemuxSPU.cpp File Reference
#include "DVDDemuxSPU.h"
#include "DVDCodecs/Overlay/DVDOverlaySpu.h"
#include "cores/VideoPlayer/Interface/TimingConstants.h"
#include "utils/log.h"
#include <locale.h>
#include <memory>
#include <stdlib.h>
Macros
#define ALIGN(value, alignment) (((value)+((alignment)-1))&~((alignment)-1))
#define CMD_END 0xFF
#define FSTA_DSP 0x00
#define STA_DSP 0x01
#define STP_DSP 0x02
#define SET_COLOR 0x03
#define SET_CONTR 0x04
#define SET_DAREA 0x05
#define SET_DSPXA 0x06
#define CHG_COLCON 0x07
Functions
void DebugLog (const char *format,...)
unsigned int AddNibble (unsigned int i_code, const uint8_t *p_src, unsigned int *pi_index)
Macro Definition Documentation
ALIGN
#define ALIGN (value, alignment) (((value)+((alignment)-1))&~((alignment)-1))
CHG_COLCON
#define CHG_COLCON 0x07
CMD_END
#define CMD_END 0xFF
FSTA_DSP
#define FSTA_DSP 0x00
SET_COLOR
#define SET_COLOR 0x03
SET_CONTR
#define SET_CONTR 0x04
SET_DAREA
#define SET_DAREA 0x05
SET_DSPXA
#define SET_DSPXA 0x06
STA_DSP
#define STA_DSP 0x01
STP_DSP
#define STP_DSP 0x02
Function Documentation
AddNibble()
unsigned int AddNibble (unsigned int i_code, const uint8_t * p_src, unsigned int * pi_index) inline
Referenced by CDVDDemuxSPU::ParseRLE().
DebugLog()
void DebugLog (const char * format, ...)
References _vsnprintf, CLog::Log(), and LOGDEBUG.
Referenced by CDVDDemuxSPU::AddData(), CDVDDemuxSPU::FindSubtitleColor(), CDVDDemuxSPU::ParsePacket(), and CDVDDemuxSPU::ParseRLE().