Kodi Documentation: KODI::PIPEWIRE::CPipewireStream Class Reference
KODI::PIPEWIRE::CPipewireStream Class Reference
#include <PipewireStream.h>
Classes
struct PipewireStreamDeleter
Public Member Functions
CPipewireStream (CPipewireCore &core)
CPipewireStream ()=delete
~CPipewireStream ()
pw_stream * Get () const
CPipewireCore & GetCore () const
bool Connect (uint32_t id, const pw_direction &direction, std::vector< const spa_pod * > &params, const pw_stream_flags &flags)
pw_stream_state GetState ()
void SetActive (bool active)
pw_buffer * DequeueBuffer ()
void QueueBuffer (pw_buffer *buffer)
bool TriggerProcess () const
void Flush (bool drain)
uint32_t GetNodeId ()
void UpdateProperties (spa_dict *dict)
pw_time GetTime () const
Static Private Member Functions
static void StateChanged (void *userdata, enum pw_stream_state old, enum pw_stream_state state, const char *error)
static void Process (void *userdata)
static void Drained (void *userdata)
static pw_stream_events CreateStreamEvents ()
Private Attributes
CPipewireCore & m_core
const pw_stream_events m_streamEvents
spa_hook m_streamListener
std::unique_ptr< pw_stream, PipewireStreamDeleter > m_stream
Constructor & Destructor Documentation
CPipewireStream() [1/2]
CPipewireStream::CPipewireStream (CPipewireCore & core) explicit
References KODI::PIPEWIRE::CPipewireCore::Get(), CLog::Log(), LOGERROR, m_stream, m_streamEvents, and m_streamListener.
CPipewireStream() [2/2]
KODI::PIPEWIRE::CPipewireStream::CPipewireStream () delete
~CPipewireStream()
CPipewireStream::~CPipewireStream ()
References m_streamListener.
Member Function Documentation
Connect()
bool CPipewireStream::Connect (uint32_t id, const pw_direction & direction, std::vector< const spa_pod * > & params, const pw_stream_flags & flags)
References CLog::Log(), LOGERROR, and m_stream.
CreateStreamEvents()
pw_stream_events CPipewireStream::CreateStreamEvents () static private
References Drained(), Process(), and StateChanged().
DequeueBuffer()
pw_buffer * CPipewireStream::DequeueBuffer ()
References m_stream.
Drained()
void CPipewireStream::Drained (void * userdata) static private
References KODI::PIPEWIRE::CPipewireCore::GetContext(), GetCore(), KODI::PIPEWIRE::CPipewireContext::GetThreadLoop(), CLog::Log(), and LOGDEBUG.
Referenced by CreateStreamEvents().
Flush()
void CPipewireStream::Flush (bool drain)
References m_stream.
Get()
pw_stream * KODI::PIPEWIRE::CPipewireStream::Get () const inline
References m_stream.
GetCore()
CPipewireCore & KODI::PIPEWIRE::CPipewireStream::GetCore () const inline
References m_core.
Referenced by Drained(), Process(), and StateChanged().
GetNodeId()
uint32_t CPipewireStream::GetNodeId ()
References m_stream.
GetState()
pw_stream_state CPipewireStream::GetState ()
References m_stream.
GetTime()
pw_time CPipewireStream::GetTime () const
References m_stream.
Process()
void CPipewireStream::Process (void * userdata) static private
References KODI::PIPEWIRE::CPipewireCore::GetContext(), GetCore(), KODI::PIPEWIRE::CPipewireContext::GetThreadLoop(), and KODI::PIPEWIRE::CPipewireThreadLoop::Signal().
Referenced by CreateStreamEvents().
QueueBuffer()
void CPipewireStream::QueueBuffer (pw_buffer * buffer)
References m_stream.
SetActive()
void CPipewireStream::SetActive (bool active)
References m_stream.
StateChanged()
void CPipewireStream::StateChanged (void * userdata, enum pw_stream_state old, enum pw_stream_state state, const char * error) static private
References KODI::PIPEWIRE::CPipewireCore::GetContext(), GetCore(), KODI::PIPEWIRE::CPipewireContext::GetThreadLoop(), CLog::Log(), and LOGDEBUG.
Referenced by CreateStreamEvents().
TriggerProcess()
bool CPipewireStream::TriggerProcess () const
References CLog::Log(), LOGERROR, and m_stream.
UpdateProperties()
void CPipewireStream::UpdateProperties (spa_dict * dict)
References m_stream.
Member Data Documentation
m_core
CPipewireCore& KODI::PIPEWIRE::CPipewireStream::m_core private
Referenced by GetCore().
m_stream
std::unique_ptr<pw_stream, PipewireStreamDeleter> KODI::PIPEWIRE::CPipewireStream::m_stream private
Referenced by Connect(), CPipewireStream(), DequeueBuffer(), Flush(), Get(), GetNodeId(), GetState(), GetTime(), QueueBuffer(), SetActive(), TriggerProcess(), and UpdateProperties().
m_streamEvents
const pw_stream_events KODI::PIPEWIRE::CPipewireStream::m_streamEvents private
Referenced by CPipewireStream().
m_streamListener
spa_hook KODI::PIPEWIRE::CPipewireStream::m_streamListener private
Referenced by CPipewireStream(), and ~CPipewireStream().
The documentation for this class was generated from the following files:
PipewireStream.h
PipewireStream.cpp