Kodi Documentation: CEventLoop Class Reference
CEventLoop Class Reference
#include <EventLoop.h>
Public Member Functions
CEventLoop (android_app *application)
void run (IActivityHandler &activityHandler, IInputHandler &inputHandler)
Protected Member Functions
void activate ()
void deactivate ()
void processActivity (int32_t command)
int32_t processInput (AInputEvent *event)
Static Private Member Functions
static void activityCallback (android_app *application, int32_t command)
static int32_t inputCallback (android_app *application, AInputEvent *event)
Private Attributes
bool m_enabled = false
android_app * m_application
IActivityHandler * m_activityHandler
IInputHandler * m_inputHandler
Constructor & Destructor Documentation
CEventLoop()
CEventLoop::CEventLoop (android_app * application)
References activityCallback(), inputCallback(), and m_application.
Member Function Documentation
activate()
void CEventLoop::activate () protected
activityCallback()
void CEventLoop::activityCallback (android_app * application, int32_t command) static private
References processActivity().
Referenced by CEventLoop().
deactivate()
void CEventLoop::deactivate () protected
inputCallback()
int32_t CEventLoop::inputCallback (android_app * application, AInputEvent * event) static private
References processInput().
Referenced by CEventLoop().
processActivity()
void CEventLoop::processActivity (int32_t command) protected
References CXBMCApp::Get(), m_activityHandler, m_application, m_inputHandler, IActivityHandler::onConfigurationChanged(), IActivityHandler::onCreateWindow(), IActivityHandler::onDestroy(), IActivityHandler::onDestroyWindow(), IActivityHandler::onGainFocus(), IActivityHandler::onLostFocus(), IActivityHandler::onLowMemory(), IActivityHandler::onPause(), IActivityHandler::onResizeWindow(), IActivityHandler::onResume(), IActivityHandler::onSaveState(), IActivityHandler::onStart(), IActivityHandler::onStop(), and IInputHandler::setDPI().
Referenced by activityCallback().
processInput()
int32_t CEventLoop::processInput (AInputEvent * event) protected
References IS_FROM_SOURCE, m_inputHandler, CAndroidJoyStick::onJoyStickEvent(), CAndroidKey::onKeyboardEvent(), CAndroidMouse::onMouseEvent(), and CAndroidTouch::onTouchEvent().
Referenced by inputCallback().
run()
void CEventLoop::run (IActivityHandler & activityHandler, IInputHandler & inputHandler)
References CXBMCApp::android_printf(), m_activityHandler, m_application, and m_inputHandler.
Referenced by android_main().
Member Data Documentation
m_activityHandler
IActivityHandler* CEventLoop::m_activityHandler private
Referenced by processActivity(), and run().
m_application
android_app* CEventLoop::m_application private
Referenced by CEventLoop(), processActivity(), and run().
m_enabled
bool CEventLoop::m_enabled = false private
m_inputHandler
IInputHandler* CEventLoop::m_inputHandler private
Referenced by processActivity(), processInput(), and run().
The documentation for this class was generated from the following files:
EventLoop.h
EventLoop.cpp