Kodi Documentation: anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer Class Reference
anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer Class Reference
Public Member Functions
AsyncUpdateTimer (const CPVRGUIActionsTimers &guiActions, const std::shared_ptr< CPVRTimerInfoTag > &oldTimer, const std::shared_ptr< CPVRTimerInfoTag > &newTimer)
bool Execute ()
Private Member Functions
void Run () override
Private Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Private Attributes
const CPVRGUIActionsTimers & m_guiActions
std::shared_ptr< CPVRTimerInfoTag > m_oldTimer
std::shared_ptr< CPVRTimerInfoTag > m_newTimer
bool m_success {false}
Constructor & Destructor Documentation
AsyncUpdateTimer()
anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer::AsyncUpdateTimer (const CPVRGUIActionsTimers & guiActions, const std::shared_ptr< CPVRTimerInfoTag > & oldTimer, const std::shared_ptr< CPVRTimerInfoTag > & newTimer) inline
Member Function Documentation
Execute()
bool anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer::Execute () inline
References CGUIDialogBusy::Wait().
Run()
void anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer::Run () inline override private virtual
Implements IRunnable.
References CServiceBroker::GetPVRManager(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and PVR::Timers.
Member Data Documentation
m_guiActions
const CPVRGUIActionsTimers& anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer::m_guiActions private
m_newTimer
std::shared_ptr<CPVRTimerInfoTag> anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer::m_newTimer private
m_oldTimer
std::shared_ptr<CPVRTimerInfoTag> anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer::m_oldTimer private
m_success
bool anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer::m_success {false} private
The documentation for this class was generated from the following file:
PVRGUIActionsTimers.cpp