Kodi Documentation: CDarwinUtils Class Reference
CDarwinUtils Class Reference
#include <DarwinUtils.h>
Static Public Member Functions
static const char * getIosPlatformString (void)
static const char * GetOSReleaseString (void)
static const char * GetOSVersionString (void)
static const char * GetVersionString ()
static std::string GetFrameworkPath (bool forPython)
static int GetExecutablePath (char *path, size_t *pathsize)
static void SetScheduling (bool realtime)
static bool CFStringRefToString (CFStringRef source, std::string &destination)
static bool CFStringRefToUTF8String (CFStringRef source, std::string &destination)
static const std::string & GetManufacturer (void)
static bool IsAliasShortcut (const std::string &path, bool isdirectory)
static void TranslateAliasShortcut (std::string &path)
static bool CreateAliasShortcut (const std::string &fromPath, const std::string &toPath)
Member Function Documentation
CFStringRefToString()
bool CDarwinUtils::CFStringRefToString (CFStringRef source, std::string & destination) static
References CFStringRefToStringWithEncoding().
CFStringRefToUTF8String()
bool CDarwinUtils::CFStringRefToUTF8String (CFStringRef source, std::string & destination) static
References CFStringRefToStringWithEncoding().
Referenced by CZeroconfBrowserDarwin::BrowserCallback(), PERIPHERALS::CPeripheralBusUSB::DeviceAttachCallback(), CCoreAudioDevice::GetDataSourceName(), CCoreAudioDevice::GetName(), CCoreAudioHardware::GetOutputDeviceName(), and anonymous_namespace{ZeroconfBrowserDarwin.cpp}::GetTxtRecords().
CreateAliasShortcut()
bool CDarwinUtils::CreateAliasShortcut (const std::string & fromPath, const std::string & toPath) static
Referenced by TEST(), and TEST().
GetExecutablePath()
int CDarwinUtils::GetExecutablePath (char * path, size_t * pathsize) static
Referenced by CUtil::ResolveExecutablePath().
GetFrameworkPath()
std::string CDarwinUtils::GetFrameworkPath (bool forPython) static
Referenced by CUtil::GetFrameworksPath().
getIosPlatformString()
const char * CDarwinUtils::getIosPlatformString (void) static
Referenced by CSysInfo::GetModelName().
GetManufacturer()
const std::string & CDarwinUtils::GetManufacturer (void) static
Referenced by CSysInfo::GetManufacturerName().
GetOSReleaseString()
const char * CDarwinUtils::GetOSReleaseString (void) static
GetOSVersionString()
const char * CDarwinUtils::GetOSVersionString (void) static
Referenced by CSysInfo::GetOsPrettyNameWithVersion().
GetVersionString()
const char * CDarwinUtils::GetVersionString () static
Referenced by CSysInfo::GetOsVersion().
IsAliasShortcut()
bool CDarwinUtils::IsAliasShortcut (const std::string & path, bool isdirectory) static
References URIUtils::RemoveSlashAtEnd().
Referenced by IsAliasShortcut().
SetScheduling()
void CDarwinUtils::SetScheduling (bool realtime) static
Referenced by CApplication::OnMessage(), and CApplication::PlaybackCleanup().
TranslateAliasShortcut()
void CDarwinUtils::TranslateAliasShortcut (std::string & path) static
Referenced by TranslateAliasShortcut().
The documentation for this class was generated from the following files:
DarwinUtils.h
DarwinUtils.mm