Kodi Documentation: MEDIA_DETECT::CLibcdio Class Reference
MEDIA_DETECT::CLibcdio Class Reference
#include <cdioSupport.h>
Public Member Functions
virtual ~CLibcdio ()
CdIo_t * cdio_open (const char *psz_source, driver_id_t driver_id)
CdIo_t * cdio_open_win32 (const char *psz_source)
void cdio_destroy (CdIo_t *p_cdio)
discmode_t cdio_get_discmode (CdIo_t *p_cdio)
CdioTrayStatus mmc_get_tray_status (const CdIo_t *p_cdio)
driver_return_code_t cdio_eject_media (CdIo_t **p_cdio)
track_t cdio_get_last_track_num (const CdIo_t *p_cdio)
lsn_t cdio_get_track_lsn (const CdIo_t *p_cdio, track_t i_track)
lsn_t cdio_get_track_last_lsn (const CdIo_t *p_cdio, track_t i_track)
driver_return_code_t cdio_read_audio_sectors (const CdIo_t *p_cdio, void *p_buf, lsn_t i_lsn, uint32_t i_blocks)
driver_return_code_t cdio_close_tray (const char *psz_source, driver_id_t *driver_id)
const char * cdio_driver_errmsg (driver_return_code_t drc)
char * GetDeviceFileName ()
Static Public Member Functions
static void ReleaseInstance ()
static std::shared_ptr< CLibcdio > GetInstance ()
Private Member Functions
CLibcdio ()
Private Attributes
char * s_defaultDevice
CCriticalSection m_critSection
Static Private Attributes
static std::shared_ptr< CLibcdio > m_pInstance
Constructor & Destructor Documentation
CLibcdio()
CLibcdio::CLibcdio () private
References cdio_log_handler().
Referenced by GetInstance().
~CLibcdio()
CLibcdio::~CLibcdio () virtual
References s_defaultDevice.
Member Function Documentation
cdio_close_tray()
driver_return_code_t CLibcdio::cdio_close_tray (const char * psz_source, driver_id_t * driver_id)
References cdio_close_tray().
Referenced by cdio_close_tray().
cdio_destroy()
void CLibcdio::cdio_destroy (CdIo_t * p_cdio)
References cdio_destroy().
Referenced by cdio_destroy(), and GetDeviceFileName().
cdio_driver_errmsg()
const char * CLibcdio::cdio_driver_errmsg (driver_return_code_t drc)
References cdio_driver_errmsg().
Referenced by cdio_driver_errmsg().
cdio_eject_media()
driver_return_code_t CLibcdio::cdio_eject_media (CdIo_t ** p_cdio)
References cdio_eject_media().
Referenced by cdio_eject_media().
cdio_get_discmode()
discmode_t CLibcdio::cdio_get_discmode (CdIo_t * p_cdio)
References cdio_get_discmode().
Referenced by cdio_get_discmode().
cdio_get_last_track_num()
track_t CLibcdio::cdio_get_last_track_num (const CdIo_t * p_cdio)
References cdio_get_last_track_num().
Referenced by cdio_get_last_track_num().
cdio_get_track_last_lsn()
lsn_t CLibcdio::cdio_get_track_last_lsn (const CdIo_t * p_cdio, track_t i_track)
References cdio_get_track_last_lsn().
Referenced by cdio_get_track_last_lsn().
cdio_get_track_lsn()
lsn_t CLibcdio::cdio_get_track_lsn (const CdIo_t * p_cdio, track_t i_track)
References cdio_get_track_lsn().
Referenced by cdio_get_track_lsn().
cdio_open()
CdIo_t * CLibcdio::cdio_open (const char * psz_source, driver_id_t driver_id)
References cdio_open().
Referenced by cdio_open(), and GetDeviceFileName().
cdio_open_win32()
CdIo_t * CLibcdio::cdio_open_win32 (const char * psz_source)
References cdio_open_win32().
Referenced by cdio_open_win32().
cdio_read_audio_sectors()
driver_return_code_t CLibcdio::cdio_read_audio_sectors (const CdIo_t * p_cdio, void * p_buf, lsn_t i_lsn, uint32_t i_blocks)
References cdio_read_audio_sectors().
Referenced by cdio_read_audio_sectors().
GetDeviceFileName()
char * CLibcdio::GetDeviceFileName ()
References cdio_destroy(), cdio_open(), CEnvironment::getenv(), and s_defaultDevice.
GetInstance()
std::shared_ptr< CLibcdio > CLibcdio::GetInstance () static
References CLibcdio(), and m_pInstance.
Referenced by CDiscDriveHandlerPosix::CloseDriveTray(), CDiscDriveHandlerPosix::EjectDriveTray(), CDiscDriveHandlerPosix::GetDriveState(), IStorageProvider::GetFirstOpticalDeviceFileName(), and CDiscDriveHandlerPosix::GetTrayState().
mmc_get_tray_status()
CdioTrayStatus CLibcdio::mmc_get_tray_status (const CdIo_t * p_cdio)
References MEDIA_DETECT::CLOSED, MEDIA_DETECT::DRIVER_ERROR, mmc_get_tray_status(), MEDIA_DETECT::OPEN, and MEDIA_DETECT::UNKNOWN.
Referenced by mmc_get_tray_status().
ReleaseInstance()
void CLibcdio::ReleaseInstance () static
References m_pInstance.
Member Data Documentation
m_critSection
CCriticalSection MEDIA_DETECT::CLibcdio::m_critSection private
m_pInstance
std::shared_ptr< CLibcdio > CLibcdio::m_pInstance static private
Referenced by GetInstance(), and ReleaseInstance().
s_defaultDevice
char* MEDIA_DETECT::CLibcdio::s_defaultDevice private
Referenced by GetDeviceFileName(), and ~CLibcdio().
The documentation for this class was generated from the following files:
cdioSupport.h
cdioSupport.cpp