Kodi Documentation: CGUILargeTextureManager Class Reference
CGUILargeTextureManager Class Reference
Guilib classes » Graphics and Screen » Textures and Fonts
Background texture loading manager.
#include <GUILargeTextureManager.h>
Classes
class CLargeTexture
Public Member Functions
CGUILargeTextureManager ()
~CGUILargeTextureManager () override
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
Callback from CImageLoader on completion of a loaded image.
bool GetImage (const std::string &path, CTextureArray &texture, bool firstRequest, bool useCache=true)
Request a texture to be loaded in the background.
void ReleaseImage (const std::string &path, bool immediately=false)
Request a texture to be unloaded.
void CleanupUnusedImages (bool immediately=false)
Cleanup images that are no longer in use.
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Private Types
typedef std::vector< CLargeTexture * >::iterator listIterator
typedef std::vector< std::pair< unsignedint, CLargeTexture * > >::iterator queueIterator
Private Member Functions
void QueueImage (const std::string &path, bool useCache=true)
Private Attributes
std::vector< std::pair< unsigned int, CLargeTexture * > > m_queued
std::vector< CLargeTexture * > m_allocated
CCriticalSection m_listSection
Detailed Description
Background texture loading manager.
Used to load textures for the user interface asynchronously, allowing fluid framerates while background loading textures.
See also
IJobCallback, CGUITexture
Member Typedef Documentation
listIterator
typedef std::vector<CLargeTexture*>::iterator CGUILargeTextureManager::listIterator private
queueIterator
typedef std::vector<std::pair<unsignedint,CLargeTexture*>>::iterator CGUILargeTextureManager::queueIterator private
Constructor & Destructor Documentation
CGUILargeTextureManager()
CGUILargeTextureManager::CGUILargeTextureManager () default
~CGUILargeTextureManager()
CGUILargeTextureManager::~CGUILargeTextureManager () override default
Member Function Documentation
CleanupUnusedImages()
void CGUILargeTextureManager::CleanupUnusedImages (bool immediately = false)
Cleanup images that are no longer in use.
Loaded textures are reference counted, and upon reaching reference count 0 through ReleaseImage() they are flagged as unused with the current time. After a delay they may be unloaded, hence CleanupUnusedImages() should be called periodically to ensure this occurs.
Parameters
immediately set to true to cleanup images regardless of whether the delay has passed
References CGUILargeTextureManager::CLargeTexture::DeleteIfRequired(), m_allocated, and m_listSection.
Referenced by CApplication::ProcessSlow(), and CApplicationSkinHandling::UnloadSkin().
GetImage()
bool CGUILargeTextureManager::GetImage (const std::string & path, CTextureArray & texture, bool firstRequest, bool useCache = true)
Request a texture to be loaded in the background.
Loaded textures are reference counted, hence this call may immediately return with the texture object filled if the texture has been previously loaded, else will return with an empty texture object if it is being loaded.
Parameters
path path of the image to load.
texture texture object to hold the resulting texture
orientation orientation of resulting texture
firstRequest true if this is the first time we are requesting this texture
Returns
true if the image exists, else false.
See also
CGUITextureArray and CGUITexture
References CGUILargeTextureManager::CLargeTexture::AddRef(), CGUILargeTextureManager::CLargeTexture::GetPath(), CGUILargeTextureManager::CLargeTexture::GetTexture(), m_allocated, m_listSection, QueueImage(), and CTextureArray::size().
OnJobComplete()
void CGUILargeTextureManager::OnJobComplete (unsigned int jobID, bool success, CJob * job) override virtual
Callback from CImageLoader on completion of a loaded image.
Transfers texture information from the loading job to our allocated texture list.
See also
CImageLoader, IJobCallback
Implements IJobCallback.
References m_allocated, m_listSection, m_queued, CImageLoader::m_texture, and CGUILargeTextureManager::CLargeTexture::SetTexture().
QueueImage()
void CGUILargeTextureManager::QueueImage (const std::string & path, bool useCache = true) private
References CGUILargeTextureManager::CLargeTexture::AddRef(), CServiceBroker::GetJobManager(), CGUILargeTextureManager::CLargeTexture::GetPath(), m_listSection, m_queued, and CJob::PRIORITY_NORMAL.
Referenced by GetImage().
ReleaseImage()
void CGUILargeTextureManager::ReleaseImage (const std::string & path, bool immediately = false)
Request a texture to be unloaded.
When textures are finished with, this function should be called. This decrements the texture's reference count, and schedules it to be unloaded once the reference count reaches zero. If the texture is still queued for loading, or is in the process of loading, the image load is cancelled.
Parameters
path path of the image to release.
immediately if set true the image is immediately unloaded once its reference count reaches zero rather than being unloaded after a delay.
References CGUILargeTextureManager::CLargeTexture::DecrRef(), CServiceBroker::GetJobManager(), CGUILargeTextureManager::CLargeTexture::GetPath(), m_allocated, m_listSection, and m_queued.
Referenced by CGUITexture::FreeResources().
Member Data Documentation
m_allocated
std::vector<CLargeTexture *> CGUILargeTextureManager::m_allocated private
Referenced by CleanupUnusedImages(), GetImage(), OnJobComplete(), and ReleaseImage().
m_listSection
CCriticalSection CGUILargeTextureManager::m_listSection private
Referenced by CleanupUnusedImages(), GetImage(), OnJobComplete(), QueueImage(), and ReleaseImage().
m_queued
std::vector< std::pair<unsigned int, CLargeTexture *> > CGUILargeTextureManager::m_queued private
Referenced by OnJobComplete(), QueueImage(), and ReleaseImage().
The documentation for this class was generated from the following files:
GUILargeTextureManager.h
GUILargeTextureManager.cpp