Kodi Documentation: CUDisks2Provider Class Reference
CUDisks2Provider Class Reference
#include <UDisks2Provider.h>
Classes
class Block
class Drive
class Filesystem
Public Member Functions
CUDisks2Provider ()
~CUDisks2Provider () override
void Initialize () override
bool PumpDriveChangeEvents (IStorageEventsCallback *callback) override
bool Eject (const std::string &mountpath) override
std::vector< std::string > GetDiskUsage () override
void GetLocalDrives (std::vector< CMediaSource > &localDrives) override
void GetRemovableDrives (std::vector< CMediaSource > &removableDrives) override
void Stop () override
Public Member Functions inherited from IStorageProvider
virtual ~IStorageProvider ()=default
virtual std::string GetFirstOpticalDeviceFileName ()
Static Public Member Functions
static bool HasUDisks2 ()
Static Public Member Functions inherited from IStorageProvider
static std::unique_ptr< IStorageProvider > CreateInstance ()
Called by media manager to create platform storage provider.
Private Types
typedef std::map< std::string, Drive * > DriveMap
typedef std::map< std::string, Block * > BlockMap
typedef std::map< std::string, Filesystem * > FilesystemMap
Private Member Functions
void GetDisks (std::vector< CMediaSource > &devices, bool enumerateRemovable)
void DriveAdded (Drive *drive)
bool DriveRemoved (const std::string &object)
void BlockAdded (Block *block, bool isNew=true)
bool BlockRemoved (const std::string &object)
void FilesystemAdded (Filesystem *fs, bool isNew=true)
bool FilesystemRemoved (const char *object, IStorageEventsCallback *callback)
bool HandleInterfacesRemoved (DBusMessage *msg, IStorageEventsCallback *callback)
void HandleInterfacesAdded (DBusMessage *msg)
bool HandlePropertiesChanged (DBusMessage *msg, IStorageEventsCallback *callback)
bool DrivePropertiesChanged (const char *object, DBusMessageIter *propsIter)
bool BlockPropertiesChanged (const char *object, DBusMessageIter *propsIter)
bool FilesystemPropertiesChanged (const char *object, DBusMessageIter *propsIter, IStorageEventsCallback *callback)
bool RemoveInterface (const char *path, const char *iface, IStorageEventsCallback *callback)
template<class Object , class Function >
void ParseProperties (Object *ref, DBusMessageIter *dictIter, Function f)
void ParseInterfaces (DBusMessageIter *dictIter)
void ParseDriveProperty (Drive *drive, const char *key, DBusMessageIter *varIter)
void ParseBlockProperty (Block *block, const char *key, DBusMessageIter *varIter)
void ParseFilesystemProperty (Filesystem *fs, const char *key, DBusMessageIter *varIter)
std::string ParseByteArray (DBusMessageIter *arrIter)
void HandleManagedObjects (DBusMessage *msg)
void ParseInterface (const char *object, const char *iface, DBusMessageIter *propsIter)
Static Private Member Functions
static void AppendEmptyOptions (DBusMessageIter *argsIter)
Private Attributes
CDBusConnection m_connection
DriveMap m_drives
BlockMap m_blocks
FilesystemMap m_filesystems
std::string m_daemonVersion
Member Typedef Documentation
BlockMap
typedef std::map<std::string, Block *> CUDisks2Provider::BlockMap private
DriveMap
typedef std::map<std::string, Drive *> CUDisks2Provider::DriveMap private
FilesystemMap
typedef std::map<std::string, Filesystem *> CUDisks2Provider::FilesystemMap private
Constructor & Destructor Documentation
CUDisks2Provider()
CUDisks2Provider::CUDisks2Provider ()
References CDBusConnection::Connect(), CDBusConnection::Destroy(), CDBusError::Log(), m_connection, and UDISKS2_MATCH_RULE.
~CUDisks2Provider()
CUDisks2Provider::~CUDisks2Provider () override
References m_blocks, m_drives, and m_filesystems.
Member Function Documentation
AppendEmptyOptions()
void CUDisks2Provider::AppendEmptyOptions (DBusMessageIter * argsIter) static private
Referenced by CUDisks2Provider::Filesystem::Mount(), and CUDisks2Provider::Filesystem::Unmount().
BlockAdded()
void CUDisks2Provider::BlockAdded (Block * block, bool isNew = true) private
References FilesystemAdded(), CLog::Log(), LOGDBUS, LOGDEBUG, LOGWARNING, m_blocks, CUDisks2Provider::Block::m_drive, CUDisks2Provider::Block::m_driveobject, m_drives, m_filesystems, CUDisks2Provider::Block::m_object, and CUDisks2Provider::Block::ToString().
Referenced by DriveAdded(), and ParseInterface().
BlockPropertiesChanged()
bool CUDisks2Provider::BlockPropertiesChanged (const char * object, DBusMessageIter * propsIter) private
References CLog::Log(), LOGDBUS, LOGDEBUG, m_blocks, ParseBlockProperty(), and ParseProperties().
Referenced by HandlePropertiesChanged().
BlockRemoved()
bool CUDisks2Provider::BlockRemoved (const std::string & object) private
References CLog::Log(), LOGDBUS, LOGDEBUG, m_blocks, and m_filesystems.
Referenced by RemoveInterface().
DriveAdded()
void CUDisks2Provider::DriveAdded (Drive * drive) private
References BlockAdded(), CLog::Log(), LOGDBUS, LOGDEBUG, LOGWARNING, m_blocks, m_drives, CUDisks2Provider::Drive::m_object, and CUDisks2Provider::Drive::ToString().
Referenced by ParseInterface().
DrivePropertiesChanged()
bool CUDisks2Provider::DrivePropertiesChanged (const char * object, DBusMessageIter * propsIter) private
References CLog::Log(), LOGDBUS, LOGDEBUG, m_drives, ParseDriveProperty(), and ParseProperties().
Referenced by HandlePropertiesChanged().
DriveRemoved()
bool CUDisks2Provider::DriveRemoved (const std::string & object) private
References CLog::Log(), LOGDBUS, LOGDEBUG, m_blocks, and m_drives.
Referenced by RemoveInterface().
Eject()
bool CUDisks2Provider::Eject (const std::string & mountpath) override virtual
Implements IStorageProvider.
References m_filesystems, and URIUtils::RemoveSlashAtEnd().
FilesystemAdded()
void CUDisks2Provider::FilesystemAdded (Filesystem * fs, bool isNew = true) private
References CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDBUS, LOGDEBUG, LOGWARNING, m_blocks, and m_filesystems.
Referenced by BlockAdded(), and ParseInterface().
FilesystemPropertiesChanged()
bool CUDisks2Provider::FilesystemPropertiesChanged (const char * object, DBusMessageIter * propsIter, IStorageEventsCallback * callback) private
References CLog::Log(), LOGDBUS, LOGDEBUG, LOGINFO, m_filesystems, ParseFilesystemProperty(), and ParseProperties().
Referenced by HandlePropertiesChanged().
FilesystemRemoved()
bool CUDisks2Provider::FilesystemRemoved (const char * object, IStorageEventsCallback * callback) private
References CLog::Log(), LOGDBUS, LOGDEBUG, and m_filesystems.
Referenced by RemoveInterface().
GetDisks()
void CUDisks2Provider::GetDisks (std::vector< CMediaSource > & devices, bool enumerateRemovable) private
References m_filesystems.
Referenced by GetLocalDrives(), and GetRemovableDrives().
GetDiskUsage()
std::vector< std::string > CUDisks2Provider::GetDiskUsage (void) override virtual
Implements IStorageProvider.
References CPosixMountProvider::GetDiskUsage().
GetLocalDrives()
void CUDisks2Provider::GetLocalDrives (std::vector< CMediaSource > & localDrives) inline override virtual
Implements IStorageProvider.
References GetDisks().
GetRemovableDrives()
void CUDisks2Provider::GetRemovableDrives (std::vector< CMediaSource > & removableDrives) inline override virtual
Implements IStorageProvider.
References GetDisks().
HandleInterfacesAdded()
void CUDisks2Provider::HandleInterfacesAdded (DBusMessage * msg) private
References ParseInterfaces().
Referenced by PumpDriveChangeEvents().
HandleInterfacesRemoved()
bool CUDisks2Provider::HandleInterfacesRemoved (DBusMessage * msg, IStorageEventsCallback * callback) private
References RemoveInterface().
Referenced by PumpDriveChangeEvents().
HandleManagedObjects()
void CUDisks2Provider::HandleManagedObjects (DBusMessage * msg) private
References ParseInterfaces().
Referenced by Initialize().
HandlePropertiesChanged()
bool CUDisks2Provider::HandlePropertiesChanged (DBusMessage * msg, IStorageEventsCallback * callback) private
References BlockPropertiesChanged(), DrivePropertiesChanged(), FilesystemPropertiesChanged(), UDISKS2_INTERFACE_BLOCK, UDISKS2_INTERFACE_DRIVE, and UDISKS2_INTERFACE_FILESYSTEM.
Referenced by PumpDriveChangeEvents().
HasUDisks2()
bool CUDisks2Provider::HasUDisks2 () static
References CDBusUtil::TryMethodCall(), UDISKS2_PATH_UDISKS2, and UDISKS2_SERVICE_UDISKS2.
Referenced by CLinuxStorageProvider::CLinuxStorageProvider().
Initialize()
void CUDisks2Provider::Initialize () override virtual
Implements IStorageProvider.
References CVariant::asString(), DBUS_INTERFACE_OBJECT_MANAGER, CDBusUtil::GetVariant(), HandleManagedObjects(), CLog::Log(), LOGDEBUG, m_daemonVersion, CDBusMessage::SendSystem(), UDISKS2_INTERFACE_MANAGER, UDISKS2_PATH_MANAGER, UDISKS2_PATH_UDISKS2, and UDISKS2_SERVICE_UDISKS2.
ParseBlockProperty()
void CUDisks2Provider::ParseBlockProperty (Block * block, const char * key, DBusMessageIter * varIter) private
References CUDisks2Provider::Block::m_device, CUDisks2Provider::Block::m_driveobject, CUDisks2Provider::Block::m_isSystem, CUDisks2Provider::Block::m_label, CUDisks2Provider::Block::m_size, ParseByteArray(), and value.
Referenced by BlockPropertiesChanged(), and ParseInterface().
ParseByteArray()
std::string CUDisks2Provider::ParseByteArray (DBusMessageIter * arrIter) private
References value.
Referenced by ParseBlockProperty(), and ParseFilesystemProperty().
ParseDriveProperty()
void CUDisks2Provider::ParseDriveProperty (Drive * drive, const char * key, DBusMessageIter * varIter) private
References CUDisks2Provider::Drive::m_isRemovable, CUDisks2Provider::Drive::m_mediaCompatibility, and value.
Referenced by DrivePropertiesChanged(), and ParseInterface().
ParseFilesystemProperty()
void CUDisks2Provider::ParseFilesystemProperty (Filesystem * fs, const char * key, DBusMessageIter * varIter) private
References ParseByteArray().
Referenced by FilesystemPropertiesChanged(), and ParseInterface().
ParseInterface()
void CUDisks2Provider::ParseInterface (const char * object, const char * iface, DBusMessageIter * propsIter) private
References BlockAdded(), DriveAdded(), f, FilesystemAdded(), ParseBlockProperty(), ParseDriveProperty(), ParseFilesystemProperty(), ParseProperties(), UDISKS2_INTERFACE_BLOCK, UDISKS2_INTERFACE_DRIVE, and UDISKS2_INTERFACE_FILESYSTEM.
Referenced by ParseInterfaces().
ParseInterfaces()
void CUDisks2Provider::ParseInterfaces (DBusMessageIter * dictIter) private
References ParseInterface().
Referenced by HandleInterfacesAdded(), and HandleManagedObjects().
ParseProperties()
template<class Object , class Function > void CUDisks2Provider::ParseProperties (Object * ref, DBusMessageIter * dictIter, Function f) private
References f.
Referenced by BlockPropertiesChanged(), DrivePropertiesChanged(), FilesystemPropertiesChanged(), and ParseInterface().
PumpDriveChangeEvents()
bool CUDisks2Provider::PumpDriveChangeEvents (IStorageEventsCallback * callback) override virtual
Implements IStorageProvider.
References DBUS_INTERFACE_OBJECT_MANAGER, HandleInterfacesAdded(), HandleInterfacesRemoved(), HandlePropertiesChanged(), CLog::Log(), LOGDBUS, LOGDEBUG, and m_connection.
RemoveInterface()
bool CUDisks2Provider::RemoveInterface (const char * path, const char * iface, IStorageEventsCallback * callback) private
References BlockRemoved(), DriveRemoved(), FilesystemRemoved(), UDISKS2_INTERFACE_BLOCK, UDISKS2_INTERFACE_DRIVE, and UDISKS2_INTERFACE_FILESYSTEM.
Referenced by HandleInterfacesRemoved().
Stop()
void CUDisks2Provider::Stop () inline override virtual
Implements IStorageProvider.
Member Data Documentation
m_blocks
BlockMap CUDisks2Provider::m_blocks private
Referenced by BlockAdded(), BlockPropertiesChanged(), BlockRemoved(), DriveAdded(), DriveRemoved(), FilesystemAdded(), and ~CUDisks2Provider().
m_connection
CDBusConnection CUDisks2Provider::m_connection private
Referenced by CUDisks2Provider(), and PumpDriveChangeEvents().
m_daemonVersion
std::string CUDisks2Provider::m_daemonVersion private
Referenced by Initialize().
m_drives
DriveMap CUDisks2Provider::m_drives private
Referenced by BlockAdded(), DriveAdded(), DrivePropertiesChanged(), DriveRemoved(), and ~CUDisks2Provider().
m_filesystems
FilesystemMap CUDisks2Provider::m_filesystems private
Referenced by BlockAdded(), BlockRemoved(), Eject(), FilesystemAdded(), FilesystemPropertiesChanged(), FilesystemRemoved(), GetDisks(), and ~CUDisks2Provider().
The documentation for this class was generated from the following files:
UDisks2Provider.h
UDisks2Provider.cpp