Kodi Documentation: KODI::VIDEO::GUILIB::CVideoVersionHelper Class Reference
KODI::VIDEO::GUILIB::CVideoVersionHelper Class Reference
#include <VideoVersionHelper.h>
Static Public Member Functions
static std::shared_ptr< CFileItem > ChooseVideoFromAssets (const std::shared_ptr< CFileItem > &item)
Member Function Documentation
ChooseVideoFromAssets()
std::shared_ptr< CFileItem > KODI::VIDEO::GUILIB::CVideoVersionHelper::ChooseVideoFromAssets (const std::shared_ptr< CFileItem > & item) static
References EXTRA, CVideoDatabase::GetDefaultVersionForVideo(), CServiceBroker::GetSettingsComponent(), LOGERROR, CVideoDatabase::Open(), CSettings::SETTING_MYVIDEOS_SELECTDEFAULTVERSION, UNKNOWN, and VERSION.
Referenced by KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::ProcessAction().
The documentation for this class was generated from the following files:
VideoVersionHelper.h
VideoVersionHelper.cpp