Kodi Documentation: Network.cpp File Reference
Network.cpp File Reference
#include <netdb.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include "Network.h"
#include "ServiceBroker.h"
#include "messaging/ApplicationMessenger.h"
#include "network/NetworkServices.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/log.h"
#include "utils/StringUtils.h"
#include "utils/XTimeUtils.h"
Functions
bool in_ether (const char *bufp, unsigned char *addr)
static const char * ConnectHostPort (SOCKET soc, const struct sockaddr_in &addr, struct timeval &timeOut, bool tryRead)
std::vector< SOCKET > CreateTCPServerSocket (const int port, const bool bindLocal, const int backlog, const char *callerName)
Function Documentation
ConnectHostPort()
static const char * ConnectHostPort (SOCKET soc, const struct sockaddr_in & addr, struct timeval & timeOut, bool tryRead) static
References ioctlsocket, and WSAGetLastError.
Referenced by CNetworkBase::PingHost().
CreateTCPServerSocket()
std::vector< SOCKET > CreateTCPServerSocket (const int port, const bool bindLocal, const int backlog, const char * callerName)
References closesocket, INVALID_SOCKET, CLog::Log(), LOGDEBUG, and LOGERROR.
Referenced by CAirPlayServer::Initialize(), and JSONRPC::CTCPServer::InitializeTCP().
in_ether()
bool in_ether (const char * bufp, unsigned char * addr)
Referenced by CNetworkBase::WakeOnLan().