Kodi Documentation: PVR::CEpgUpdateRequest Class Reference
PVR::CEpgUpdateRequest Class Reference
Public Member Functions
CEpgUpdateRequest ()
CEpgUpdateRequest (int iClientID, int iUniqueChannelID)
void Deliver (const std::shared_ptr< CPVREpg > &epg)
int GetClientID () const
int GetUniqueChannelID () const
Private Attributes
int m_iClientID
int m_iUniqueChannelID
Constructor & Destructor Documentation
CEpgUpdateRequest() [1/2]
PVR::CEpgUpdateRequest::CEpgUpdateRequest () inline
CEpgUpdateRequest() [2/2]
PVR::CEpgUpdateRequest::CEpgUpdateRequest (int iClientID, int iUniqueChannelID) inline
Member Function Documentation
Deliver()
void PVR::CEpgUpdateRequest::Deliver (const std::shared_ptr< CPVREpg > & epg)
Referenced by PVR::CPVREpgContainer::Process().
GetClientID()
int PVR::CEpgUpdateRequest::GetClientID () const inline
References m_iClientID.
Referenced by PVR::CPVREpgContainer::Process().
GetUniqueChannelID()
int PVR::CEpgUpdateRequest::GetUniqueChannelID () const inline
References m_iUniqueChannelID.
Referenced by PVR::CPVREpgContainer::Process().
Member Data Documentation
m_iClientID
int PVR::CEpgUpdateRequest::m_iClientID private
Referenced by GetClientID().
m_iUniqueChannelID
int PVR::CEpgUpdateRequest::m_iUniqueChannelID private
Referenced by GetUniqueChannelID().
The documentation for this class was generated from the following file:
EpgContainer.cpp