Kodi Documentation: NPT_XbmcFileOutputStream Class Reference
NPT_XbmcFileOutputStream Class Reference
Public Member Functions
NPT_XbmcFileOutputStream (NPT_XbmcFileReference &file)
NPT_Result Write (const void *buffer, NPT_Size bytes_to_write, NPT_Size *bytes_written) override
NPT_Result Seek (NPT_Position offset) override
NPT_Result Tell (NPT_Position &offset) override
NPT_Result Flush () override
Additional Inherited Members
Private Member Functions inherited from NPT_XbmcFileStream
NPT_XbmcFileStream (const NPT_XbmcFileReference &file)
NPT_Result Seek (NPT_Position offset)
NPT_Result Tell (NPT_Position &offset)
NPT_Result Flush ()
virtual ~NPT_XbmcFileStream ()=default
Private Attributes inherited from NPT_XbmcFileStream
NPT_XbmcFileReference m_FileReference
Constructor & Destructor Documentation
NPT_XbmcFileOutputStream()
NPT_XbmcFileOutputStream::NPT_XbmcFileOutputStream (NPT_XbmcFileReference & file) inline explicit
Member Function Documentation
Flush()
NPT_Result NPT_XbmcFileOutputStream::Flush () inline override
References NPT_XbmcFileStream::Flush().
Seek()
NPT_Result NPT_XbmcFileOutputStream::Seek (NPT_Position offset) inline override
References NPT_XbmcFileStream::Seek().
Tell()
NPT_Result NPT_XbmcFileOutputStream::Tell (NPT_Position & offset) inline override
References NPT_XbmcFileStream::Tell().
Write()
NPT_Result NPT_XbmcFileOutputStream::Write (const void * buffer, NPT_Size bytes_to_write, NPT_Size * bytes_written) override
References NPT_XbmcFileStream::m_FileReference.
The documentation for this class was generated from the following file:
NptXbmcFile.cpp