Kodi Documentation: KODI::WINDOWING::WAYLAND::CWinEventsWayland Class Reference
KODI::WINDOWING::WAYLAND::CWinEventsWayland Class Reference
#include <WinEventsWayland.h>
Public Member Functions
bool MessagePump () override
void MessagePush (XBMC_Event *ev)
Public Member Functions inherited from IWinEvents
virtual ~IWinEvents ()=default
Static Public Member Functions
static void Flush ()
Write buffered messages to the compositor.
static void RoundtripQueue (wayland::event_queue_t const &queue)
Do a roundtrip on the specified queue from the event processing thread.
Static Private Member Functions
static void SetDisplay (wayland::display_t *display)
Private Attributes
CCriticalSection m_queueMutex
std::queue< XBMC_Event > m_queue
Friends
class CWinSystemWayland
Member Function Documentation
Flush()
void CWinEventsWayland::Flush () static
Write buffered messages to the compositor.
Referenced by KODI::WINDOWING::WAYLAND::CSeatSelection::GetSelectionText().
MessagePump()
bool CWinEventsWayland::MessagePump () override virtual
Implements IWinEvents.
References CServiceBroker::GetAppPort(), m_queue, and m_queueMutex.
MessagePush()
void CWinEventsWayland::MessagePush (XBMC_Event * ev)
References m_queue, and m_queueMutex.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnEvent(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetResolutionInternal().
RoundtripQueue()
void CWinEventsWayland::RoundtripQueue (wayland::event_queue_t const & queue) static
Do a roundtrip on the specified queue from the event processing thread.
Referenced by KODI::WINDOWING::WAYLAND::CRegistry::Bind().
SetDisplay()
void CWinEventsWayland::SetDisplay (wayland::display_t * display) static private
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWayland::CreateNewWindow(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::DestroyWindow().
Friends And Related Symbol Documentation
CWinSystemWayland
friend class CWinSystemWayland friend
Member Data Documentation
m_queue
std::queue<XBMC_Event> KODI::WINDOWING::WAYLAND::CWinEventsWayland::m_queue private
Referenced by MessagePump(), and MessagePush().
m_queueMutex
CCriticalSection KODI::WINDOWING::WAYLAND::CWinEventsWayland::m_queueMutex private
Referenced by MessagePump(), and MessagePush().
The documentation for this class was generated from the following files:
WinEventsWayland.h
WinEventsWayland.cpp