Kodi Documentation: CGUIViewState Class Reference
CGUIViewState Class Reference abstract
#include <GUIViewState.h>
Public Member Functions
virtual ~CGUIViewState ()
void SetViewAsControl (int viewAsControl)
void SaveViewAsControl (int viewAsControl)
int GetViewAsControl () const
bool ChooseSortMethod ()
SortDescription SetNextSortMethod (int direction=1)
void SetCurrentSortMethod (int method)
SortDescription GetSortMethod () const
bool HasMultipleSortMethods () const
int GetSortMethodLabel () const
int GetSortOrderLabel () const
void GetSortMethodLabelMasks (LABEL_MASKS &masks) const
std::vector< SortDescription > GetSortDescriptions () const
SortOrder SetNextSortOrder ()
SortOrder GetSortOrder () const
virtual bool HideExtensions ()
virtual bool HideParentDirItems ()
virtual bool DisableAddSourceButtons ()
virtual KODI::PLAYLIST::Id GetPlaylist () const
const std::string & GetPlaylistDirectory ()
void SetPlaylistDirectory (const std::string &strDirectory)
bool IsCurrentPlaylistDirectory (const std::string &strDirectory)
virtual bool AutoPlayNextItem ()
virtual std::string GetLockType ()
virtual std::string GetExtensions ()
virtual std::vector< CMediaSource > & GetSources ()
Static Public Member Functions
static CGUIViewState * GetViewState (int windowId, const CFileItemList &items)
Protected Member Functions
CGUIViewState (const CFileItemList &items)
virtual void SaveViewState ()=0
virtual void SaveViewToDb (const std::string &path, int windowID, CViewState *viewState=NULL)
void LoadViewState (const std::string &path, int windowID)
void AddLiveTVSources ()
void AddPlaylistOrder (const CFileItemList &items, const LABEL_MASKS &label_masks)
Add the sort order defined in a smartplaylist Defaults to SORT_METHOD_PLAYLIST_ORDER if no order is defined.
void AddSortMethod (SortBy sortBy, int buttonLabel, const LABEL_MASKS &labelMasks, SortAttribute sortAttributes=SortAttributeNone, SortOrder sortOrder=SortOrderNone)
void AddSortMethod (SortBy sortBy, SortAttribute sortAttributes, int buttonLabel, const LABEL_MASKS &labelMasks, SortOrder sortOrder=SortOrderNone)
void AddSortMethod (SortDescription sortDescription, int buttonLabel, const LABEL_MASKS &labelMasks)
void SetSortMethod (SortBy sortBy, SortOrder sortOrder=SortOrderNone)
void SetSortMethod (SortDescription sortDescription)
void SetSortOrder (SortOrder sortOrder)
bool AutoPlayNextVideoItem () const
Protected Attributes
const CFileItemList & m_items
int m_currentViewAsControl
KODI::PLAYLIST::Id m_playlist
std::vector< GUIViewSortDetails > m_sortMethods
int m_currentSortMethod
Static Protected Attributes
static std::vector< CMediaSource > m_sources
static std::string m_strPlaylistDirectory
Constructor & Destructor Documentation
~CGUIViewState()
CGUIViewState::~CGUIViewState () virtual default
CGUIViewState()
CGUIViewState::CGUIViewState (const CFileItemList & items) explicit protected
References m_currentSortMethod, m_currentViewAsControl, and m_playlist.
Member Function Documentation
AddLiveTVSources()
void CGUIViewState::AddLiveTVSources () protected
References CMediaSource::FromNameAndPaths(), CMediaSourceSettings::GetInstance(), CMediaSourceSettings::GetSources(), URIUtils::IsLiveTV(), m_sources, CMediaSource::m_strThumbnailImage, CMediaSource::strName, CMediaSource::strPath, and CMediaSource::vecPaths.
Referenced by CGUIViewStateWindowVideo::GetSources().
AddPlaylistOrder()
void CGUIViewState::AddPlaylistOrder (const CFileItemList & items, const LABEL_MASKS & label_masks) protected
Add the sort order defined in a smartplaylist Defaults to SORT_METHOD_PLAYLIST_ORDER if no order is defined.
Parameters
items the list of items for the view state.
label_mask the label masks for formatting items.
References AddSortMethod(), CVariant::asBoolean(), CVariant::asInteger(), CGUIListItem::GetProperty(), SortUtils::GetSortLabel(), CGUIListItem::HasProperty(), PROPERTY_SORT_ASCENDING, PROPERTY_SORT_ORDER, SetSortMethod(), SortAttributeNone, SortByNone, SortByPlaylistOrder, SortOrderAscending, and SortOrderDescending.
Referenced by CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), and CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows().
AddSortMethod() [1/3]
void CGUIViewState::AddSortMethod (SortBy sortBy, int buttonLabel, const LABEL_MASKS & labelMasks, SortAttribute sortAttributes = SortAttributeNone, SortOrder sortOrder = SortOrderNone) protected
References AddSortMethod().
Referenced by AddPlaylistOrder(), AddSortMethod(), AddSortMethod(), CGUIViewStateAddonBrowser::CGUIViewStateAddonBrowser(), CGUIViewStateEventLog::CGUIViewStateEventLog(), CGUIViewStateFavourites::CGUIViewStateFavourites(), CGUIViewStateFromItems::CGUIViewStateFromItems(), CGUIViewStateGeneral::CGUIViewStateGeneral(), CGUIViewStateLibrary::CGUIViewStateLibrary(), CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), CGUIViewStateMusicPlaylist::CGUIViewStateMusicPlaylist(), CGUIViewStateMusicSearch::CGUIViewStateMusicSearch(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoPlaylist::CGUIViewStateVideoPlaylist(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), KODI::GAME::CGUIViewStateWindowGames::CGUIViewStateWindowGames(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowMusicPlaylist::CGUIViewStateWindowMusicPlaylist(), CGUIViewStateWindowPictures::CGUIViewStateWindowPictures(), CGUIViewStateWindowPrograms::CGUIViewStateWindowPrograms(), PVR::CGUIViewStateWindowPVRChannels::CGUIViewStateWindowPVRChannels(), PVR::CGUIViewStateWindowPVRGuide::CGUIViewStateWindowPVRGuide(), PVR::CGUIViewStateWindowPVRProviders::CGUIViewStateWindowPVRProviders(), PVR::CGUIViewStateWindowPVRRecordings::CGUIViewStateWindowPVRRecordings(), PVR::CGUIViewStateWindowPVRSearch::CGUIViewStateWindowPVRSearch(), PVR::CGUIViewStateWindowPVRTimers::CGUIViewStateWindowPVRTimers(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), and CGUIViewStateWindowVideoPlaylist::CGUIViewStateWindowVideoPlaylist().
AddSortMethod() [2/3]
void CGUIViewState::AddSortMethod (SortBy sortBy, SortAttribute sortAttributes, int buttonLabel, const LABEL_MASKS & labelMasks, SortOrder sortOrder = SortOrderNone) protected
References GUIViewSortDetails::m_buttonLabel, GUIViewSortDetails::m_labelMasks, GUIViewSortDetails::m_sortDescription, m_sortMethods, SortDescription::sortAttributes, SortDescription::sortBy, SortByBitrate, SortByDate, SortByLastPlayed, SortByListeners, SortByNone, SortByPlaycount, SortByProgramCount, SortByRating, SortBySize, SortByUserRating, SortDescription::sortOrder, SortOrderAscending, SortOrderDescending, and SortOrderNone.
AddSortMethod() [3/3]
void CGUIViewState::AddSortMethod (SortDescription sortDescription, int buttonLabel, const LABEL_MASKS & labelMasks) protected
References AddSortMethod(), SortDescription::sortAttributes, SortDescription::sortBy, and SortDescription::sortOrder.
AutoPlayNextItem()
bool CGUIViewState::AutoPlayNextItem () virtual
Reimplemented in CGUIViewStateWindowMusic, CGUIViewStateWindowMusicPlaylist, CGUIViewStateWindowVideo, CGUIViewStateWindowVideoNav, CGUIViewStateWindowVideoPlaylist, and CGUIViewStateFromItems.
AutoPlayNextVideoItem()
bool CGUIViewState::AutoPlayNextVideoItem () const protected
References CFileItemList::GetContent(), GetPlaylist(), KODI::VIDEO::UTILS::IsAutoPlayNextItem(), and m_items.
Referenced by CGUIViewStateWindowVideo::AutoPlayNextItem(), and CGUIViewStateFromItems::AutoPlayNextItem().
ChooseSortMethod()
bool CGUIViewState::ChooseSortMethod ()
References CGUIDialogSelect::Add(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedItem(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), m_currentSortMethod, m_sortMethods, CGUIDialog::Open(), CGUIDialogSelect::Reset(), SaveViewState(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetSelected(), and WINDOW_DIALOG_SELECT.
DisableAddSourceButtons()
bool CGUIViewState::DisableAddSourceButtons () virtual
Reimplemented in CGUIViewStateEventLog.
References CGUIPassword::bMasterUser, g_passwordManager, CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_FILELISTS_SHOWADDSOURCEBUTTONS.
GetExtensions()
std::string CGUIViewState::GetExtensions () virtual
Reimplemented in CGUIViewStateAddonBrowser, CGUIViewStateEventLog, KODI::GAME::CGUIViewStateWindowGames, CGUIViewStateWindowMusic, CGUIViewStateWindowPictures, CGUIViewStateWindowPrograms, and CGUIViewStateWindowVideo.
Referenced by CGUIWindowPictures::OnSlideShow(), CGUIWindowPictures::OnSlideShowRecursive(), and CGUIMediaWindow::SetupShares().
GetLockType()
std::string CGUIViewState::GetLockType () virtual
Reimplemented in KODI::GAME::CGUIViewStateWindowGames, CGUIViewStateWindowMusic, CGUIViewStateWindowPictures, CGUIViewStateWindowPrograms, and CGUIViewStateWindowVideo.
GetPlaylist()
PLAYLIST::Id CGUIViewState::GetPlaylist () const virtual
Reimplemented in CGUIViewStateWindowMusic, CGUIViewStateWindowMusicPlaylist, and CGUIViewStateWindowVideo.
References m_playlist.
Referenced by AutoPlayNextVideoItem(), and IsCurrentPlaylistDirectory().
GetPlaylistDirectory()
const std::string & CGUIViewState::GetPlaylistDirectory ()
References m_strPlaylistDirectory.
GetSortDescriptions()
std::vector< SortDescription > CGUIViewState::GetSortDescriptions () const
References m_sortMethods.
Referenced by anonymous_namespace{MusicUtils.cpp}::GetSortDescription(), and KODI::anonymous_namespace{VideoGUIUtils.cpp}::GetSortDescription().
GetSortMethod()
SortDescription CGUIViewState::GetSortMethod () const
References m_currentSortMethod, and m_sortMethods.
Referenced by UPNP::CUPnPServer::DefaultSortItems(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), anonymous_namespace{MusicUtils.cpp}::GetSortDescription(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::GetSortDescription(), SaveViewToDb(), SetNextSortMethod(), and FAVOURITES_UTILS::ShouldEnableMoveItems().
GetSortMethodLabel()
int CGUIViewState::GetSortMethodLabel () const
References m_currentSortMethod, and m_sortMethods.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel().
GetSortMethodLabelMasks()
void CGUIViewState::GetSortMethodLabelMasks (LABEL_MASKS & masks) const
References m_currentSortMethod, m_sortMethods, LABEL_MASKS::m_strLabel2File, LABEL_MASKS::m_strLabel2Folder, LABEL_MASKS::m_strLabelFile, and LABEL_MASKS::m_strLabelFolder.
GetSortOrder()
SortOrder CGUIViewState::GetSortOrder () const
References m_currentSortMethod, m_sortMethods, and SortOrderAscending.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), and SetNextSortOrder().
GetSortOrderLabel()
int CGUIViewState::GetSortOrderLabel () const
References m_currentSortMethod, m_sortMethods, and SortOrderDescending.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel().
GetSources()
std::vector< CMediaSource > & CGUIViewState::GetSources () virtual
Reimplemented in KODI::GAME::CGUIViewStateWindowGames, CGUIViewStateWindowMusic, CGUIViewStateWindowMusicNav, CGUIViewStateWindowMusicPlaylist, CGUIViewStateWindowPictures, CGUIViewStateWindowPrograms, CGUIViewStateWindowVideo, CGUIViewStateWindowVideoNav, and CGUIViewStateWindowVideoPlaylist.
References m_sources.
Referenced by CGUIWindowMusicNav::AddSearchFolder(), CGUIViewStateWindowMusic::GetSources(), CGUIViewStateWindowPrograms::GetSources(), CGUIViewStateWindowVideo::GetSources(), and CGUIMediaWindow::SetupShares().
GetViewAsControl()
int CGUIViewState::GetViewAsControl () const
References m_currentViewAsControl.
GetViewState()
CGUIViewState * CGUIViewState::GetViewState (int windowId, const CFileItemList & items) static
References CFileItemList::GetContent(), CServiceBroker::GetGUI(), CFileItem::GetPath(), CFileItem::GetURL(), GetViewState(), CFileItemList::HasSortDetails(), CFileItem::IsAddonsPath(), CFileItem::IsLibraryFolder(), KODI::PLAYLIST::IsPlayList(), CURL::IsProtocol(), KODI::PLAYLIST::IsSmartPlayList(), m_sources, WINDOW_ADDON_BROWSER, WINDOW_EVENT_LOG, WINDOW_FAVOURITES, WINDOW_GAMES, WINDOW_MUSIC_NAV, WINDOW_MUSIC_PLAYLIST, WINDOW_MUSIC_PLAYLIST_EDITOR, WINDOW_PICTURES, WINDOW_PROGRAMS, WINDOW_RADIO_CHANNELS, WINDOW_RADIO_GUIDE, WINDOW_RADIO_PROVIDERS, WINDOW_RADIO_RECORDINGS, WINDOW_RADIO_SEARCH, WINDOW_RADIO_TIMER_RULES, WINDOW_RADIO_TIMERS, WINDOW_TV_CHANNELS, WINDOW_TV_GUIDE, WINDOW_TV_PROVIDERS, WINDOW_TV_RECORDINGS, WINDOW_TV_SEARCH, WINDOW_TV_TIMER_RULES, WINDOW_TV_TIMERS, WINDOW_VIDEO_NAV, and WINDOW_VIDEO_PLAYLIST.
Referenced by CGUIWindowMusicNav::AddSearchFolder(), CGUIMediaWindow::CGUIMediaWindow(), UPNP::CUPnPServer::DefaultSortItems(), CGUIMediaWindow::FormatAndSort(), CGUIMediaWindow::GetDirectory(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), GetViewState(), CGUIMediaWindow::OnClick(), CGUIWindowPictures::OnSlideShow(), CGUIWindowPictures::OnSlideShowRecursive(), MUSIC_UTILS::QueueItem(), CGUIMediaWindow::SetupShares(), and CGUIMediaWindow::SortItems().
HasMultipleSortMethods()
bool CGUIViewState::HasMultipleSortMethods () const
References m_sortMethods.
HideExtensions()
bool CGUIViewState::HideExtensions () virtual
Reimplemented in CGUIViewStateEventLog, and CGUIViewStateWindowVideoPlaylist.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_FILELISTS_SHOWEXTENSIONS.
HideParentDirItems()
bool CGUIViewState::HideParentDirItems () virtual
Reimplemented in CGUIViewStateEventLog, CGUIViewStateFavourites, CGUIViewStateWindowMusicPlaylist, PVR::CGUIViewStatePVR, PVR::CGUIViewStateWindowPVRRecordings, PVR::CGUIViewStateWindowPVRTimers, PVR::CGUIViewStateWindowPVRSearch, PVR::CGUIViewStateWindowPVRProviders, and CGUIViewStateWindowVideoPlaylist.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_FILELISTS_SHOWPARENTDIRITEMS.
Referenced by PVR::CGUIViewStateWindowPVRRecordings::HideParentDirItems(), PVR::CGUIViewStateWindowPVRTimers::HideParentDirItems(), PVR::CGUIViewStateWindowPVRSearch::HideParentDirItems(), and PVR::CGUIViewStateWindowPVRProviders::HideParentDirItems().
IsCurrentPlaylistDirectory()
bool CGUIViewState::IsCurrentPlaylistDirectory (const std::string & strDirectory)
References GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), m_strPlaylistDirectory, and URIUtils::RemoveSlashAtEnd().
LoadViewState()
void CGUIViewState::LoadViewState (const std::string & path, int windowID) protected
References CServiceBroker::GetSettingsComponent(), CViewDatabase::GetViewState(), CViewState::m_sortDescription, CViewState::m_viewMode, CViewDatabase::Open(), SetSortMethod(), CSettings::SETTING_LOOKANDFEEL_SKIN, and SetViewAsControl().
Referenced by CGUIViewStateAddonBrowser::CGUIViewStateAddonBrowser(), CGUIViewStateEventLog::CGUIViewStateEventLog(), CGUIViewStateFavourites::CGUIViewStateFavourites(), CGUIViewStateFromItems::CGUIViewStateFromItems(), CGUIViewStateLibrary::CGUIViewStateLibrary(), CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), CGUIViewStateMusicPlaylist::CGUIViewStateMusicPlaylist(), CGUIViewStateMusicSearch::CGUIViewStateMusicSearch(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoPlaylist::CGUIViewStateVideoPlaylist(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), KODI::GAME::CGUIViewStateWindowGames::CGUIViewStateWindowGames(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowMusicPlaylist::CGUIViewStateWindowMusicPlaylist(), CGUIViewStateWindowPictures::CGUIViewStateWindowPictures(), CGUIViewStateWindowPrograms::CGUIViewStateWindowPrograms(), PVR::CGUIViewStateWindowPVRChannels::CGUIViewStateWindowPVRChannels(), PVR::CGUIViewStateWindowPVRGuide::CGUIViewStateWindowPVRGuide(), PVR::CGUIViewStateWindowPVRProviders::CGUIViewStateWindowPVRProviders(), PVR::CGUIViewStateWindowPVRRecordings::CGUIViewStateWindowPVRRecordings(), PVR::CGUIViewStateWindowPVRSearch::CGUIViewStateWindowPVRSearch(), PVR::CGUIViewStateWindowPVRTimers::CGUIViewStateWindowPVRTimers(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), and CGUIViewStateWindowVideoPlaylist::CGUIViewStateWindowVideoPlaylist().
SaveViewAsControl()
void CGUIViewState::SaveViewAsControl (int viewAsControl)
References SaveViewState(), and SetViewAsControl().
SaveViewState()
virtual void CGUIViewState::SaveViewState () protected pure virtual
Implemented in CGUIViewStateAddonBrowser, CGUIViewStateEventLog, CGUIViewStateFavourites, KODI::GAME::CGUIViewStateWindowGames, CGUIViewStateMusicSearch, CGUIViewStateMusicDatabase, CGUIViewStateMusicSmartPlaylist, CGUIViewStateMusicPlaylist, CGUIViewStateWindowMusicNav, CGUIViewStateWindowMusicPlaylist, CGUIViewStateWindowPictures, CGUIViewStateWindowPrograms, PVR::CGUIViewStateWindowPVRChannels, PVR::CGUIViewStateWindowPVRRecordings, PVR::CGUIViewStateWindowPVRGuide, PVR::CGUIViewStateWindowPVRTimers, PVR::CGUIViewStateWindowPVRSearch, PVR::CGUIViewStateWindowPVRProviders, CGUIViewStateVideoPlaylist, CGUIViewStateWindowVideoNav, CGUIViewStateWindowVideoPlaylist, CGUIViewStateVideoMovies, CGUIViewStateVideoMusicVideos, CGUIViewStateVideoTVShows, CGUIViewStateVideoEpisodes, CGUIViewStateGeneral, CGUIViewStateFromItems, and CGUIViewStateLibrary.
Referenced by ChooseSortMethod(), SaveViewAsControl(), SetCurrentSortMethod(), SetNextSortMethod(), and SetNextSortOrder().
SaveViewToDb()
void CGUIViewState::SaveViewToDb (const std::string & path, int windowID, CViewState * viewState = NULL) protected virtual
References CDatabase::Close(), CServiceBroker::GetSettingsComponent(), GetSortMethod(), m_currentViewAsControl, CViewDatabase::Open(), CSettings::SETTING_LOOKANDFEEL_SKIN, CViewDatabase::SetViewState(), SortDescription::sortAttributes, SortDescription::sortBy, and SortDescription::sortOrder.
Referenced by CGUIViewStateAddonBrowser::SaveViewState(), CGUIViewStateEventLog::SaveViewState(), CGUIViewStateFavourites::SaveViewState(), KODI::GAME::CGUIViewStateWindowGames::SaveViewState(), CGUIViewStateMusicSearch::SaveViewState(), CGUIViewStateMusicDatabase::SaveViewState(), CGUIViewStateMusicSmartPlaylist::SaveViewState(), CGUIViewStateMusicPlaylist::SaveViewState(), CGUIViewStateWindowMusicNav::SaveViewState(), CGUIViewStateWindowMusicPlaylist::SaveViewState(), CGUIViewStateWindowPictures::SaveViewState(), CGUIViewStateWindowPrograms::SaveViewState(), PVR::CGUIViewStateWindowPVRChannels::SaveViewState(), PVR::CGUIViewStateWindowPVRRecordings::SaveViewState(), PVR::CGUIViewStateWindowPVRGuide::SaveViewState(), PVR::CGUIViewStateWindowPVRTimers::SaveViewState(), PVR::CGUIViewStateWindowPVRSearch::SaveViewState(), PVR::CGUIViewStateWindowPVRProviders::SaveViewState(), CGUIViewStateVideoPlaylist::SaveViewState(), CGUIViewStateWindowVideoNav::SaveViewState(), CGUIViewStateWindowVideoPlaylist::SaveViewState(), CGUIViewStateVideoMovies::SaveViewState(), CGUIViewStateVideoMusicVideos::SaveViewState(), CGUIViewStateVideoTVShows::SaveViewState(), CGUIViewStateVideoEpisodes::SaveViewState(), CGUIViewStateFromItems::SaveViewState(), and CGUIViewStateLibrary::SaveViewState().
SetCurrentSortMethod()
void CGUIViewState::SetCurrentSortMethod (int method)
References SaveViewState(), SetSortMethod(), and SortByLastUsed.
SetNextSortMethod()
SortDescription CGUIViewState::SetNextSortMethod (int direction = 1)
References GetSortMethod(), m_currentSortMethod, m_sortMethods, and SaveViewState().
SetNextSortOrder()
SortOrder CGUIViewState::SetNextSortOrder ()
References GetSortOrder(), SaveViewState(), SetSortOrder(), SortOrderAscending, and SortOrderDescending.
SetPlaylistDirectory()
void CGUIViewState::SetPlaylistDirectory (const std::string & strDirectory)
References m_strPlaylistDirectory, and URIUtils::RemoveSlashAtEnd().
Referenced by MUSIC_UTILS::QueueItem().
SetSortMethod() [1/2]
void CGUIViewState::SetSortMethod (SortBy sortBy, SortOrder sortOrder = SortOrderNone) protected
References m_currentSortMethod, m_sortMethods, SetSortOrder(), and SortOrderNone.
Referenced by AddPlaylistOrder(), CGUIViewStateAddonBrowser::CGUIViewStateAddonBrowser(), CGUIViewStateEventLog::CGUIViewStateEventLog(), CGUIViewStateFavourites::CGUIViewStateFavourites(), CGUIViewStateGeneral::CGUIViewStateGeneral(), CGUIViewStateLibrary::CGUIViewStateLibrary(), CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), CGUIViewStateMusicPlaylist::CGUIViewStateMusicPlaylist(), CGUIViewStateMusicSearch::CGUIViewStateMusicSearch(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoPlaylist::CGUIViewStateVideoPlaylist(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), KODI::GAME::CGUIViewStateWindowGames::CGUIViewStateWindowGames(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowMusicPlaylist::CGUIViewStateWindowMusicPlaylist(), CGUIViewStateWindowPictures::CGUIViewStateWindowPictures(), CGUIViewStateWindowPrograms::CGUIViewStateWindowPrograms(), PVR::CGUIViewStateWindowPVRChannels::CGUIViewStateWindowPVRChannels(), PVR::CGUIViewStateWindowPVRGuide::CGUIViewStateWindowPVRGuide(), PVR::CGUIViewStateWindowPVRProviders::CGUIViewStateWindowPVRProviders(), PVR::CGUIViewStateWindowPVRRecordings::CGUIViewStateWindowPVRRecordings(), PVR::CGUIViewStateWindowPVRSearch::CGUIViewStateWindowPVRSearch(), PVR::CGUIViewStateWindowPVRTimers::CGUIViewStateWindowPVRTimers(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), CGUIViewStateWindowVideoPlaylist::CGUIViewStateWindowVideoPlaylist(), LoadViewState(), SetCurrentSortMethod(), and SetSortMethod().
SetSortMethod() [2/2]
void CGUIViewState::SetSortMethod (SortDescription sortDescription) protected
References SetSortMethod(), SortDescription::sortBy, and SortDescription::sortOrder.
SetSortOrder()
void CGUIViewState::SetSortOrder (SortOrder sortOrder) protected
References m_currentSortMethod, m_sortMethods, and SortOrderNone.
Referenced by CGUIViewStateEventLog::CGUIViewStateEventLog(), CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), CGUIViewStateMusicPlaylist::CGUIViewStateMusicPlaylist(), CGUIViewStateMusicSearch::CGUIViewStateMusicSearch(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoPlaylist::CGUIViewStateVideoPlaylist(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), KODI::GAME::CGUIViewStateWindowGames::CGUIViewStateWindowGames(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowMusicPlaylist::CGUIViewStateWindowMusicPlaylist(), CGUIViewStateWindowPictures::CGUIViewStateWindowPictures(), CGUIViewStateWindowPrograms::CGUIViewStateWindowPrograms(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), CGUIViewStateWindowVideoPlaylist::CGUIViewStateWindowVideoPlaylist(), SetNextSortOrder(), and SetSortMethod().
SetViewAsControl()
void CGUIViewState::SetViewAsControl (int viewAsControl)
References DEFAULT_VIEW_AUTO, CAutoSwitch::GetView(), m_currentViewAsControl, and m_items.
Referenced by CGUIViewStateAddonBrowser::CGUIViewStateAddonBrowser(), CGUIViewStateEventLog::CGUIViewStateEventLog(), CGUIViewStateFromItems::CGUIViewStateFromItems(), CGUIViewStateGeneral::CGUIViewStateGeneral(), CGUIViewStateLibrary::CGUIViewStateLibrary(), CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), CGUIViewStateMusicPlaylist::CGUIViewStateMusicPlaylist(), CGUIViewStateMusicSearch::CGUIViewStateMusicSearch(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoPlaylist::CGUIViewStateVideoPlaylist(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), KODI::GAME::CGUIViewStateWindowGames::CGUIViewStateWindowGames(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowMusicPlaylist::CGUIViewStateWindowMusicPlaylist(), CGUIViewStateWindowPictures::CGUIViewStateWindowPictures(), CGUIViewStateWindowPrograms::CGUIViewStateWindowPrograms(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), CGUIViewStateWindowVideoPlaylist::CGUIViewStateWindowVideoPlaylist(), LoadViewState(), and SaveViewAsControl().
Member Data Documentation
m_currentSortMethod
int CGUIViewState::m_currentSortMethod protected
Referenced by CGUIViewState(), CGUIViewStateFromItems::CGUIViewStateFromItems(), ChooseSortMethod(), GetSortMethod(), GetSortMethodLabel(), GetSortMethodLabelMasks(), GetSortOrder(), GetSortOrderLabel(), SetNextSortMethod(), SetSortMethod(), and SetSortOrder().
m_currentViewAsControl
int CGUIViewState::m_currentViewAsControl protected
Referenced by CGUIViewState(), GetViewAsControl(), SaveViewToDb(), and SetViewAsControl().
m_items
const CFileItemList& CGUIViewState::m_items protected
Referenced by CGUIViewStateWindowVideoNav::AutoPlayNextItem(), AutoPlayNextVideoItem(), PVR::CGUIViewStateWindowPVRProviders::CGUIViewStateWindowPVRProviders(), PVR::CGUIViewStateWindowPVRSearch::CGUIViewStateWindowPVRSearch(), PVR::CGUIViewStateWindowPVRRecordings::HideParentDirItems(), PVR::CGUIViewStateWindowPVRTimers::HideParentDirItems(), PVR::CGUIViewStateWindowPVRSearch::HideParentDirItems(), PVR::CGUIViewStateWindowPVRProviders::HideParentDirItems(), CGUIViewStateAddonBrowser::SaveViewState(), CGUIViewStateEventLog::SaveViewState(), CGUIViewStateFavourites::SaveViewState(), KODI::GAME::CGUIViewStateWindowGames::SaveViewState(), CGUIViewStateMusicSearch::SaveViewState(), CGUIViewStateMusicDatabase::SaveViewState(), CGUIViewStateMusicSmartPlaylist::SaveViewState(), CGUIViewStateMusicPlaylist::SaveViewState(), CGUIViewStateWindowMusicNav::SaveViewState(), CGUIViewStateWindowMusicPlaylist::SaveViewState(), CGUIViewStateWindowPictures::SaveViewState(), CGUIViewStateWindowPrograms::SaveViewState(), PVR::CGUIViewStateWindowPVRRecordings::SaveViewState(), PVR::CGUIViewStateWindowPVRSearch::SaveViewState(), PVR::CGUIViewStateWindowPVRProviders::SaveViewState(), CGUIViewStateVideoPlaylist::SaveViewState(), CGUIViewStateWindowVideoNav::SaveViewState(), CGUIViewStateWindowVideoPlaylist::SaveViewState(), CGUIViewStateVideoMovies::SaveViewState(), CGUIViewStateVideoMusicVideos::SaveViewState(), CGUIViewStateVideoTVShows::SaveViewState(), CGUIViewStateVideoEpisodes::SaveViewState(), CGUIViewStateFromItems::SaveViewState(), CGUIViewStateLibrary::SaveViewState(), and SetViewAsControl().
m_playlist
KODI::PLAYLIST::Id CGUIViewState::m_playlist protected
Referenced by CGUIViewState(), CGUIViewStateFromItems::CGUIViewStateFromItems(), and GetPlaylist().
m_sortMethods
std::vector<GUIViewSortDetails> CGUIViewState::m_sortMethods protected
Referenced by AddSortMethod(), ChooseSortMethod(), GetSortDescriptions(), GetSortMethod(), GetSortMethodLabel(), GetSortMethodLabelMasks(), GetSortOrder(), GetSortOrderLabel(), HasMultipleSortMethods(), SetNextSortMethod(), SetSortMethod(), and SetSortOrder().
m_sources
std::vector< CMediaSource > CGUIViewState::m_sources static protected
Referenced by AddLiveTVSources(), GetSources(), CGUIViewStateWindowMusicNav::GetSources(), CGUIViewStateWindowMusicPlaylist::GetSources(), CGUIViewStateWindowPrograms::GetSources(), CGUIViewStateWindowVideoNav::GetSources(), CGUIViewStateWindowVideoPlaylist::GetSources(), and GetViewState().
m_strPlaylistDirectory
std::string CGUIViewState::m_strPlaylistDirectory static protected
Referenced by GetPlaylistDirectory(), IsCurrentPlaylistDirectory(), and SetPlaylistDirectory().
The documentation for this class was generated from the following files:
GUIViewState.h
GUIViewState.cpp