Kodi Documentation: XFILE::CCurlFile Class Reference
XFILE::CCurlFile Class Reference
#include <CurlFile.h>
Classes
class CReadState
Public Member Functions
CCurlFile ()
~CCurlFile () override
bool Open (const CURL &url) override
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
bool ReOpen (const CURL &url) override
bool Exists (const CURL &url) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
int64_t GetPosition () override
int64_t GetLength () override
int Stat (const CURL &url, struct __stat64 *buffer) override
void Close () override
bool ReadString (char *szLine, int iLineLength) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const override
const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const override
int IoControl (EIoControl request, void *param) override
double GetDownloadSpeed () override
bool Post (const std::string &strURL, const std::string &strPostData, std::string &strHTML)
bool Get (const std::string &strURL, std::string &strHTML)
bool ReadData (std::string &strHTML)
bool Download (const std::string &strURL, const std::string &strFileName, unsigned int *pdwSize=NULL)
bool IsInternet ()
void Cancel ()
void Reset ()
void SetUserAgent (const std::string &sUserAgent)
void SetProxy (const std::string &type, const std::string &host, uint16_t port, const std::string &user, const std::string &password)
void SetCustomRequest (const std::string &request)
void SetAcceptEncoding (const std::string &encoding)
void SetAcceptCharset (const std::string &charset)
void SetTimeout (int connecttimeout)
void SetLowSpeedTime (int lowspeedtime)
void SetPostData (const std::string &postdata)
void SetReferer (const std::string &referer)
void SetCookie (const std::string &cookie)
void SetMimeType (const std::string &mimetype)
void SetRequestHeader (const std::string &header, const std::string &value)
void SetRequestHeader (const std::string &header, long value)
void ClearRequestHeaders ()
void SetBufferSize (unsigned int size)
const CHttpHeader & GetHttpHeader () const
const std::string & GetURL () const
std::string GetRedirectURL ()
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual int Stat (struct __stat64 *buffer)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual bool Delete (const CURL &url)
virtual bool Rename (const CURL &url, const CURL &urlnew)
virtual bool SetHidden (const CURL &url, bool hidden)
Static Public Member Functions
static bool GetHttpHeader (const CURL &url, CHttpHeader &headers)
static bool GetMimeType (const CURL &url, std::string &content, const std::string &useragent="")
static bool GetContentType (const CURL &url, std::string &content, const std::string &useragent="")
static bool GetCookies (const CURL &url, std::string &cookies)
Protected Types
typedef std::map< std::string, std::string > MAPHTTPHEADERS
Protected Member Functions
void ParseAndCorrectUrl (CURL &url)
void SetCommonOptions (CReadState *state, bool failOnError=true)
void SetRequestHeaders (CReadState *state)
void SetCorrectHeaders (CReadState *state)
bool Service (const std::string &strURL, std::string &strHTML)
std::string GetInfoString (int infoType)
Protected Attributes
CReadState * m_state
CReadState * m_oldState
unsigned int m_bufferSize
int64_t m_writeOffset = 0
std::string m_url
std::string m_userAgent
ProxyType m_proxytype = PROXY_HTTP
std::string m_proxyhost
uint16_t m_proxyport = 3128
std::string m_proxyuser
std::string m_proxypassword
std::string m_customrequest
std::string m_acceptencoding
std::string m_acceptCharset
std::string m_ftpauth
std::string m_ftpport
std::string m_binary
std::string m_postdata
std::string m_referer
std::string m_cookie
std::string m_username
std::string m_password
std::string m_httpauth
std::string m_cipherlist
bool m_ftppasvip
int m_connecttimeout
int m_redirectlimit
int m_lowspeedtime
bool m_opened
bool m_forWrite
bool m_inError
bool m_seekable
bool m_multisession
bool m_skipshout
bool m_postdataset
bool m_allowRetry
bool m_verifyPeer = true
bool m_failOnError = true
curl_slist * m_dnsCacheList = nullptr
CRingBuffer m_buffer
char * m_overflowBuffer
unsigned int m_overflowSize = 0
int m_stillRunning
MAPHTTPHEADERS m_requestheaders
long m_httpresponse
Private Types
enum ProxyType {
PROXY_HTTP = 0 , PROXY_SOCKS4 , PROXY_SOCKS4A , PROXY_SOCKS5 ,
PROXY_SOCKS5_REMOTE , PROXY_HTTPS
}
Member Typedef Documentation
MAPHTTPHEADERS
typedef std::map<std::string, std::string> XFILE::CCurlFile::MAPHTTPHEADERS protected
Member Enumeration Documentation
ProxyType
enum XFILE::CCurlFile::ProxyType private
Enumerator
PROXY_HTTP
PROXY_SOCKS4
PROXY_SOCKS4A
PROXY_SOCKS5
PROXY_SOCKS5_REMOTE
PROXY_HTTPS
Constructor & Destructor Documentation
CCurlFile()
CCurlFile::CCurlFile ()
References m_acceptCharset, m_acceptencoding, m_allowRetry, m_bufferSize, m_connecttimeout, m_forWrite, m_ftppasvip, m_httpresponse, m_inError, m_lowspeedtime, m_multisession, m_oldState, m_opened, m_postdataset, m_redirectlimit, m_seekable, m_skipshout, and m_state.
~CCurlFile()
CCurlFile::~CCurlFile () override
References Close(), m_oldState, and m_state.
Member Function Documentation
Cancel()
void CCurlFile::Cancel ()
References XFILE::CCurlFile::CReadState::m_cancelled, m_opened, m_state, and KODI::TIME::Sleep().
Referenced by MUSIC_GRABBER::CMusicInfoScraper::Cancel(), CVideoInfoDownloader::CloseThread(), and CRssReader::Process().
ClearRequestHeaders()
void CCurlFile::ClearRequestHeaders ()
References m_requestheaders.
Close()
void CCurlFile::Close () override virtual
Implements XFILE::IFile.
References XFILE::CCurlFile::CReadState::Disconnect(), g_curlInterface, m_cookie, m_dnsCacheList, m_forWrite, m_inError, m_oldState, m_opened, m_referer, m_state, m_url, XCURL::DllLibCurl::slist_free_all(), and Write().
Referenced by XFILE::CShoutcastFile::Close(), XFILE::CDAVDirectory::Create(), CDVDFactoryInputStream::CreateInputStream(), XFILE::CDAVFile::Delete(), XFILE::CDAVFile::Execute(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CHTTPDirectory::GetDirectory(), IsInternet(), XFILE::CDAVDirectory::Remove(), XFILE::CDAVFile::Rename(), ReOpen(), Service(), and ~CCurlFile().
Download()
bool CCurlFile::Download (const std::string & strURL, const std::string & strFileName, unsigned int * pdwSize = NULL)
References Get(), GetLastError(), CLog::Log(), LOGERROR, and LOGINFO.
Exists()
bool CCurlFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References XCURL::DllLibCurlGlobal::easy_acquire(), XCURL::DllLibCurl::easy_getinfo(), XCURL::DllLibCurl::easy_perform(), XCURL::DllLibCurlGlobal::easy_release(), XCURL::DllLibCurl::easy_setopt(), XCURL::DllLibCurl::easy_strerror(), g_curlInterface, CURL::GetFileName(), CURL::GetHostName(), CURL::GetProtocol(), CURL::GetRedacted(), CServiceBroker::GetSettingsComponent(), CURL::IsProtocol(), CLog::Log(), LOGERROR, LOGWARNING, XFILE::CCurlFile::CReadState::m_easyHandle, m_opened, m_state, ParseAndCorrectUrl(), SetCommonOptions(), SetRequestHeaders(), XCURL::DllLibCurl::slist_append(), XCURL::DllLibCurl::slist_free_all(), and transfer_abort_callback().
Referenced by XFILE::CDAVDirectory::Exists(), XFILE::CFTPDirectory::Exists(), XFILE::CRSSDirectory::Exists(), IsInternet(), OpenForWrite(), TEST_F(), TEST_F(), and TEST_F().
Get()
bool CCurlFile::Get (const std::string & strURL, std::string & strHTML)
References m_postdata, m_postdataset, and Service().
Referenced by Download(), XFILE::CShoutcastFile::ExtractTagInfo(), ADDON::CRepository::FetchIndex(), CScraperUrl::Get(), CRssReader::Process(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetContentType()
bool CCurlFile::GetContentType (const CURL & url, std::string & content, const std::string & useragent = "") static
References __stat64, _S_IFDIR, XFILE::FILE_PROPERTY_CONTENT_TYPE, CURL::GetRedacted(), CLog::Log(), LOGDEBUG, and SetUserAgent().
Referenced by ADDON::Interface_Filesystem::get_content_type(), and CDVDDemuxFFmpeg::GetL16Parameters().
GetCookies()
bool CCurlFile::GetCookies (const CURL & url, std::string & cookies) static
References XCURL::DllLibCurlGlobal::easy_acquire(), XCURL::DllLibCurl::easy_getinfo(), XCURL::DllLibCurlGlobal::easy_release(), g_curlInterface, CURL::GetHostName(), CURL::GetProtocol(), CURL::GetRedacted(), CLog::Log(), LOGERROR, and XCURL::DllLibCurl::slist_free_all().
Referenced by ADDON::Interface_Filesystem::get_cookies(), and CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput().
GetDownloadSpeed()
double CCurlFile::GetDownloadSpeed () override virtual
Reimplemented from XFILE::IFile.
References XCURL::DllLibCurl::easy_getinfo(), g_curlInterface, XFILE::CCurlFile::CReadState::m_easyHandle, and m_state.
GetHttpHeader() [1/2]
const CHttpHeader & XFILE::CCurlFile::GetHttpHeader () const inline
References XFILE::CCurlFile::CReadState::m_httpheader, and m_state.
Referenced by TestWebServer::CheckHtmlTestFileResponse(), TestWebServer::CheckRangesTestFileResponse(), TestWebServer::CheckRangesTestFileResponse(), XFILE::CShoutcastFile::ExtractTagInfo(), ADDON::Interface_Filesystem::get_http_header(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CShoutcastFile::Open(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetHttpHeader() [2/2]
bool CCurlFile::GetHttpHeader (const CURL & url, CHttpHeader & headers) static
References CURL::GetRedacted(), CLog::Log(), and LOGERROR.
GetInfoString()
std::string CCurlFile::GetInfoString (int infoType) protected
References XCURL::DllLibCurl::easy_getinfo(), g_curlInterface, CLog::Log(), LOGERROR, XFILE::CCurlFile::CReadState::m_easyHandle, m_state, and m_url.
Referenced by GetRedirectURL(), Open(), and OpenForWrite().
GetLength()
int64_t CCurlFile::GetLength () override virtual
Implements XFILE::IFile.
References XFILE::CCurlFile::CReadState::m_fileSize, m_opened, and m_state.
Referenced by Stat().
GetMimeType()
bool CCurlFile::GetMimeType (const CURL & url, std::string & content, const std::string & useragent = "") static
References __stat64, _S_IFDIR, XFILE::FILE_PROPERTY_MIME_TYPE, CURL::GetRedacted(), CLog::Log(), LOGDEBUG, and SetUserAgent().
Referenced by CFileItem::FillInMimeType(), ADDON::Interface_Filesystem::get_mime_type(), and CMime::GetMimeType().
GetPosition()
int64_t CCurlFile::GetPosition () override virtual
Implements XFILE::IFile.
References XFILE::CCurlFile::CReadState::m_filePos, m_opened, and m_state.
Referenced by XFILE::CShoutcastFile::ExtractTagInfo(), and XFILE::CShoutcastFile::GetPosition().
GetProperty()
const std::string CCurlFile::GetProperty (XFILE::FileProperty type, const std::string & name = "") const override virtual
Reimplemented from XFILE::IFile.
References XCURL::DllLibCurl::easy_getinfo(), XFILE::FILE_PROPERTY_CONTENT_CHARSET, XFILE::FILE_PROPERTY_CONTENT_TYPE, XFILE::FILE_PROPERTY_EFFECTIVE_URL, XFILE::FILE_PROPERTY_MIME_TYPE, XFILE::FILE_PROPERTY_RESPONSE_HEADER, XFILE::FILE_PROPERTY_RESPONSE_PROTOCOL, g_curlInterface, CHttpHeader::GetCharset(), CHttpHeader::GetMimeType(), CHttpHeader::GetProtoLine(), CHttpHeader::GetValue(), XFILE::CCurlFile::CReadState::m_easyHandle, XFILE::CCurlFile::CReadState::m_httpheader, m_state, and name.
Referenced by ADDON::CRepository::FetchIndex(), CScraperUrl::Get(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CHTTPDirectory::GetDirectory(), GetPropertyValues(), and XFILE::CShoutcastFile::Open().
GetPropertyValues()
const std::vector< std::string > CCurlFile::GetPropertyValues (XFILE::FileProperty type, const std::string & name = "") const override virtual
Reimplemented from XFILE::IFile.
References XFILE::FILE_PROPERTY_RESPONSE_HEADER, GetProperty(), CHttpHeader::GetValues(), XFILE::CCurlFile::CReadState::m_httpheader, m_state, name, value, and values.
GetRedirectURL()
std::string CCurlFile::GetRedirectURL ()
References GetInfoString().
GetURL()
const std::string & XFILE::CCurlFile::GetURL () const inline
References m_url.
Referenced by CDVDFactoryInputStream::CreateInputStream().
IoControl()
int CCurlFile::IoControl (EIoControl request, void * param) override virtual
Reimplemented from XFILE::IFile.
References XFILE::IOCTRL_SEEK_POSSIBLE, XFILE::IOCTRL_SET_RETRY, m_allowRetry, and m_seekable.
IsInternet()
bool CCurlFile::IsInternet ()
References Close(), Exists(), and CURL::Parse().
Referenced by CSysInfoJob::GetInternetState().
Open()
bool CCurlFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References XFILE::CCurlFile::CReadState::Connect(), XCURL::DllLibCurlGlobal::easy_acquire(), g_curlInterface, CURL::GetHostName(), GetInfoString(), CServiceBroker::GetLogging(), CURL::GetProtocol(), CHttpHeader::GetProtoLine(), CHttpHeader::GetValue(), CURL::IsProtocol(), CLog::Log(), LOGCURL, LOGDEBUG, LOGERROR, LOGWARNING, m_allowRetry, XFILE::CCurlFile::CReadState::m_bRetry, m_bufferSize, XFILE::CCurlFile::CReadState::m_easyHandle, m_failOnError, XFILE::CCurlFile::CReadState::m_fileSize, XFILE::CCurlFile::CReadState::m_httpheader, m_httpresponse, XFILE::CCurlFile::CReadState::m_multiHandle, m_multisession, m_opened, m_seekable, XFILE::CCurlFile::CReadState::m_sendRange, m_skipshout, m_state, m_url, ParseAndCorrectUrl(), ReadString(), SetCommonOptions(), SetCorrectHeaders(), and SetRequestHeaders().
Referenced by CDVDFactoryInputStream::CreateInputStream(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CFTPDirectory::GetDirectory(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CShoutcastFile::Open(), ReOpen(), and Service().
OpenForWrite()
bool CCurlFile::OpenForWrite (const CURL & url, bool bOverWrite = false) override virtual
Reimplemented from XFILE::IFile.
References XCURL::DllLibCurlGlobal::easy_acquire(), XCURL::DllLibCurl::easy_setopt(), Exists(), g_curlInterface, CURL::GetHostName(), GetInfoString(), CURL::GetProtocol(), CLog::Log(), LOGDEBUG, XFILE::CCurlFile::CReadState::m_easyHandle, m_forWrite, m_inError, XFILE::CCurlFile::CReadState::m_multiHandle, m_opened, m_state, m_url, m_writeOffset, XCURL::DllLibCurl::multi_add_handle(), ParseAndCorrectUrl(), SetCommonOptions(), XFILE::CCurlFile::CReadState::SetReadBuffer(), and SetRequestHeaders().
ParseAndCorrectUrl()
void CCurlFile::ParseAndCorrectUrl (CURL & url) protected
Todo:
create a tokenizer that doesn't skip empty's
References Base64::Decode(), g_charsetConverter, g_curlInterface, CURL::Get(), CDNSNameCache::GetCached(), CURL::GetFileName(), CURL::GetHostName(), CURL::GetOptions(), CURL::GetPassWord(), CURL::GetPort(), CURL::GetProtocolOption(), CURL::GetProtocolOptions(), CURL::GetRedacted(), CServiceBroker::GetSettingsComponent(), CURL::GetTranslatedProtocol(), CURL::GetUserName(), CURL::GetWithoutUserDetails(), CURL::HasProtocolOption(), CURL::IsLocalHost(), CURL::IsProtocol(), CLog::Log(), LOGCURL, LOGDEBUG, LOGWARNING, m_cipherlist, m_connecttimeout, m_dnsCacheList, m_failOnError, m_ftpauth, m_ftppasvip, m_ftpport, m_httpauth, m_password, m_postdata, m_postdataset, m_proxyhost, m_proxypassword, m_proxyport, m_proxytype, m_proxyuser, m_redirectlimit, m_seekable, m_skipshout, m_url, m_username, m_verifyPeer, name, proxyType2CUrlProxyType, SetAcceptCharset(), SetAcceptEncoding(), SetCookie(), SetCustomRequest(), CURL::SetFileName(), CURL::SetOptions(), CURL::SetProtocol(), CURL::SetProtocolOptions(), SetReferer(), SetRequestHeader(), CSettings::SETTING_NETWORK_HTTPPROXYPASSWORD, CSettings::SETTING_NETWORK_HTTPPROXYPORT, CSettings::SETTING_NETWORK_HTTPPROXYSERVER, CSettings::SETTING_NETWORK_HTTPPROXYTYPE, CSettings::SETTING_NETWORK_HTTPPROXYUSERNAME, CSettings::SETTING_NETWORK_USEHTTPPROXY, SetUserAgent(), XCURL::DllLibCurl::slist_append(), and value.
Referenced by XFILE::CDAVFile::Execute(), Exists(), Open(), OpenForWrite(), and Stat().
Post()
bool CCurlFile::Post (const std::string & strURL, const std::string & strPostData, std::string & strHTML)
References m_postdata, m_postdataset, and Service().
Referenced by CScraperUrl::Get(), KODI::RETRO::CCheevos::GetRichPresenceEvaluation(), TEST_F(), and TEST_F().
Read()
ssize_t XFILE::CCurlFile::Read (void * bufPtr, size_t bufSize) inline override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References m_state, and XFILE::CCurlFile::CReadState::Read().
Referenced by XFILE::CShoutcastFile::Read(), ReadData(), and XFILE::CShoutcastFile::ReadTruncated().
ReadData()
bool CCurlFile::ReadData (std::string & strHTML)
References XFILE::CCurlFile::CReadState::m_cancelled, m_state, and Read().
Referenced by XFILE::CDAVFile::Execute(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CHTTPDirectory::GetDirectory(), and Service().
ReadString()
bool XFILE::CCurlFile::ReadString (char * szLine, int iLineLength) inline override virtual
Reimplemented from XFILE::IFile.
References m_state, and XFILE::CCurlFile::CReadState::ReadString().
Referenced by XFILE::CFTPDirectory::GetDirectory(), and Open().
ReOpen()
bool CCurlFile::ReOpen (const CURL & url) override virtual
Reimplemented from XFILE::IFile.
References Close(), and Open().
Reset()
void CCurlFile::Reset ()
References XFILE::CCurlFile::CReadState::m_cancelled, and m_state.
Referenced by MUSIC_GRABBER::CMusicInfoScraper::Cancel(), and CVideoInfoDownloader::CloseThread().
Seek()
int64_t CCurlFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Todo:
daap is gone. is this needed for something else?
Implements XFILE::IFile.
References XFILE::CCurlFile::CReadState::Connect(), XFILE::CCurlFile::CReadState::Disconnect(), XCURL::DllLibCurlGlobal::easy_acquire(), g_curlInterface, CURL::GetHostName(), CURL::GetProtocol(), int64_t(), m_allowRetry, XFILE::CCurlFile::CReadState::m_bRetry, m_bufferSize, XFILE::CCurlFile::CReadState::m_easyHandle, XFILE::CCurlFile::CReadState::m_filePos, XFILE::CCurlFile::CReadState::m_fileSize, XFILE::CCurlFile::CReadState::m_multiHandle, m_multisession, m_oldState, m_seekable, XFILE::CCurlFile::CReadState::m_sendRange, m_state, m_url, Seek(), XFILE::CCurlFile::CReadState::Seek(), SetCommonOptions(), SetCorrectHeaders(), and SetRequestHeaders().
Referenced by Seek().
Service()
bool CCurlFile::Service (const std::string & strURL, std::string & strHTML) protected
References Close(), Open(), and ReadData().
Referenced by Get(), and Post().
SetAcceptCharset()
void XFILE::CCurlFile::SetAcceptCharset (const std::string & charset) inline
References m_acceptCharset.
Referenced by ParseAndCorrectUrl().
SetAcceptEncoding()
void XFILE::CCurlFile::SetAcceptEncoding (const std::string & encoding) inline
References m_acceptencoding.
Referenced by ParseAndCorrectUrl(), and WSDiscovery::CWSDiscoveryListenerUDP::UnicastGet().
SetBufferSize()
void CCurlFile::SetBufferSize (unsigned int size)
References m_bufferSize.
SetCommonOptions()
void CCurlFile::SetCommonOptions (CReadState * state, bool failOnError = true) protected
References CURL_OFF, CURL_ON, debug_callback(), XCURL::DllLibCurl::easy_reset(), XCURL::DllLibCurl::easy_setopt(), XFILE::CFile::Exists(), g_curlInterface, CServiceBroker::GetSettingsComponent(), header_callback(), LOG_LEVEL_DEBUG, m_acceptCharset, m_acceptencoding, m_cipherlist, m_connecttimeout, m_cookie, XFILE::CCurlFile::CReadState::m_curlAliasList, m_customrequest, m_dnsCacheList, XFILE::CCurlFile::CReadState::m_easyHandle, m_ftpauth, m_ftppasvip, m_ftpport, m_httpauth, m_lowspeedtime, m_password, m_postdata, m_postdataset, m_proxyhost, m_proxypassword, m_proxyport, m_proxytype, m_proxyuser, m_redirectlimit, m_referer, m_state, m_url, m_userAgent, m_username, m_verifyPeer, proxyType2CUrlProxyType, read_callback(), SetRequestHeader(), XCURL::DllLibCurl::slist_append(), CSpecialProtocol::TranslatePath(), and write_callback().
Referenced by XFILE::CDAVFile::Execute(), Exists(), Open(), OpenForWrite(), Seek(), and Stat().
SetCookie()
void XFILE::CCurlFile::SetCookie (const std::string & cookie) inline
References m_cookie.
Referenced by ParseAndCorrectUrl().
SetCorrectHeaders()
void CCurlFile::SetCorrectHeaders (CReadState * state) protected
References CHttpHeader::AddParam(), CHttpHeader::GetMimeType(), CHttpHeader::GetValue(), and XFILE::CCurlFile::CReadState::m_httpheader.
Referenced by Open(), Seek(), and Stat().
SetCustomRequest()
void XFILE::CCurlFile::SetCustomRequest (const std::string & request) inline
References m_customrequest.
Referenced by XFILE::CDAVDirectory::Create(), XFILE::CDAVFile::Delete(), XFILE::CDAVDirectory::Exists(), XFILE::CDAVDirectory::GetDirectory(), ParseAndCorrectUrl(), XFILE::CDAVDirectory::Remove(), and XFILE::CDAVFile::Rename().
SetLowSpeedTime()
void XFILE::CCurlFile::SetLowSpeedTime (int lowspeedtime) inline
References m_lowspeedtime.
SetMimeType()
void XFILE::CCurlFile::SetMimeType (const std::string & mimetype) inline
References SetRequestHeader().
Referenced by XFILE::CDAVDirectory::GetDirectory(), TEST_F(), and TEST_F().
SetPostData()
void XFILE::CCurlFile::SetPostData (const std::string & postdata) inline
References m_postdata.
Referenced by XFILE::CDAVDirectory::GetDirectory().
SetProxy()
void CCurlFile::SetProxy (const std::string & type, const std::string & host, uint16_t port, const std::string & user, const std::string & password)
References CLog::Log(), LOGERROR, m_proxyhost, m_proxypassword, m_proxyport, m_proxytype, m_proxyuser, m_url, PROXY_HTTP, PROXY_HTTPS, PROXY_SOCKS4, PROXY_SOCKS4A, PROXY_SOCKS5, and PROXY_SOCKS5_REMOTE.
SetReferer()
void XFILE::CCurlFile::SetReferer (const std::string & referer) inline
References m_referer.
Referenced by CScraperUrl::Get(), and ParseAndCorrectUrl().
SetRequestHeader() [1/2]
void CCurlFile::SetRequestHeader (const std::string & header, const std::string & value)
References m_requestheaders, and value.
Referenced by XFILE::CDAVDirectory::Exists(), XFILE::CDAVDirectory::GetDirectory(), ParseAndCorrectUrl(), XFILE::CDAVFile::Rename(), SetCommonOptions(), SetMimeType(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
SetRequestHeader() [2/2]
void CCurlFile::SetRequestHeader (const std::string & header, long value)
References m_requestheaders, and value.
SetRequestHeaders()
void CCurlFile::SetRequestHeaders (CReadState * state) protected
References XCURL::DllLibCurl::easy_setopt(), g_curlInterface, XFILE::CCurlFile::CReadState::m_curlHeaderList, XFILE::CCurlFile::CReadState::m_easyHandle, m_requestheaders, XCURL::DllLibCurl::slist_append(), and XCURL::DllLibCurl::slist_free_all().
Referenced by XFILE::CDAVFile::Execute(), Exists(), Open(), OpenForWrite(), Seek(), and Stat().
SetTimeout()
void XFILE::CCurlFile::SetTimeout (int connecttimeout) inline
References m_connecttimeout.
Referenced by CRssReader::Process().
SetUserAgent()
void XFILE::CCurlFile::SetUserAgent (const std::string & sUserAgent) inline
References m_userAgent.
Referenced by GetContentType(), GetMimeType(), ParseAndCorrectUrl(), and CRssReader::Process().
Stat()
int CCurlFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References _S_IFDIR, _S_IFREG, XCURL::DllLibCurlGlobal::easy_acquire(), XCURL::DllLibCurl::easy_getinfo(), XCURL::DllLibCurl::easy_perform(), XCURL::DllLibCurlGlobal::easy_release(), XCURL::DllLibCurl::easy_setopt(), XCURL::DllLibCurl::easy_strerror(), g_curlInterface, CURL::GetFileName(), CURL::GetHostName(), GetLength(), CHttpHeader::GetMimeType(), CURL::GetProtocol(), CURL::GetRedacted(), CServiceBroker::GetSettingsComponent(), int64_t(), CURL::IsProtocol(), CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, XFILE::CCurlFile::CReadState::m_easyHandle, XFILE::CCurlFile::CReadState::m_httpheader, m_opened, m_state, ParseAndCorrectUrl(), SetCommonOptions(), SetCorrectHeaders(), SetRequestHeaders(), and transfer_abort_callback().
Referenced by XFILE::CHTTPDirectory::Exists().
Write()
ssize_t CCurlFile::Write (const void * bufPtr, size_t bufSize) override virtual
Attempt to write bufSize bytes from buffer bufPtr into currently opened file.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully written bytes if any bytes were written, zero if no bytes were written and no detectable error occur, -1 in case of any explicit error
Reimplemented from XFILE::IFile.
References XCURL::DllLibCurl::easy_getinfo(), XCURL::DllLibCurl::easy_pause(), g_curlInterface, CLog::Log(), LOGERROR, XFILE::CCurlFile::CReadState::m_easyHandle, XFILE::CCurlFile::CReadState::m_filePos, m_forWrite, m_inError, XFILE::CCurlFile::CReadState::m_isPaused, XFILE::CCurlFile::CReadState::m_multiHandle, m_opened, m_state, m_stillRunning, m_url, m_writeOffset, XCURL::DllLibCurl::multi_perform(), and XFILE::CCurlFile::CReadState::SetReadBuffer().
Referenced by Close().
Member Data Documentation
m_acceptCharset
std::string XFILE::CCurlFile::m_acceptCharset protected
Referenced by CCurlFile(), SetAcceptCharset(), and SetCommonOptions().
m_acceptencoding
std::string XFILE::CCurlFile::m_acceptencoding protected
Referenced by CCurlFile(), SetAcceptEncoding(), and SetCommonOptions().
m_allowRetry
bool XFILE::CCurlFile::m_allowRetry protected
Referenced by CCurlFile(), IoControl(), Open(), and Seek().
m_binary
std::string XFILE::CCurlFile::m_binary protected
m_buffer
CRingBuffer XFILE::CCurlFile::m_buffer protected
Referenced by XFILE::CCurlFile::CReadState::Connect(), XFILE::CCurlFile::CReadState::Disconnect(), XFILE::CCurlFile::CReadState::FillBuffer(), XFILE::CCurlFile::CReadState::Read(), XFILE::CCurlFile::CReadState::Seek(), and XFILE::CCurlFile::CReadState::WriteCallback().
m_bufferSize
unsigned int XFILE::CCurlFile::m_bufferSize protected
Referenced by CCurlFile(), XFILE::CCurlFile::CReadState::Connect(), XFILE::CCurlFile::CReadState::CReadState(), XFILE::CCurlFile::CReadState::Disconnect(), XFILE::CDAVFile::Execute(), Open(), Seek(), XFILE::CCurlFile::CReadState::Seek(), and SetBufferSize().
m_cipherlist
std::string XFILE::CCurlFile::m_cipherlist protected
Referenced by ParseAndCorrectUrl(), and SetCommonOptions().
m_connecttimeout
int XFILE::CCurlFile::m_connecttimeout protected
Referenced by CCurlFile(), ParseAndCorrectUrl(), SetCommonOptions(), and SetTimeout().
m_cookie
std::string XFILE::CCurlFile::m_cookie protected
Referenced by Close(), SetCommonOptions(), and SetCookie().
m_customrequest
std::string XFILE::CCurlFile::m_customrequest protected
Referenced by SetCommonOptions(), and SetCustomRequest().
m_dnsCacheList
curl_slist* XFILE::CCurlFile::m_dnsCacheList = nullptr protected
Referenced by Close(), ParseAndCorrectUrl(), and SetCommonOptions().
m_failOnError
bool XFILE::CCurlFile::m_failOnError = true protected
Referenced by Open(), and ParseAndCorrectUrl().
m_forWrite
bool XFILE::CCurlFile::m_forWrite protected
Referenced by CCurlFile(), Close(), OpenForWrite(), and Write().
m_ftpauth
std::string XFILE::CCurlFile::m_ftpauth protected
Referenced by ParseAndCorrectUrl(), and SetCommonOptions().
m_ftppasvip
bool XFILE::CCurlFile::m_ftppasvip protected
Referenced by CCurlFile(), ParseAndCorrectUrl(), and SetCommonOptions().
m_ftpport
std::string XFILE::CCurlFile::m_ftpport protected
Referenced by ParseAndCorrectUrl(), and SetCommonOptions().
m_httpauth
std::string XFILE::CCurlFile::m_httpauth protected
Referenced by ParseAndCorrectUrl(), and SetCommonOptions().
m_httpresponse
long XFILE::CCurlFile::m_httpresponse protected
Referenced by CCurlFile(), and Open().
m_inError
bool XFILE::CCurlFile::m_inError protected
Referenced by CCurlFile(), Close(), OpenForWrite(), and Write().
m_lowspeedtime
int XFILE::CCurlFile::m_lowspeedtime protected
Referenced by CCurlFile(), SetCommonOptions(), and SetLowSpeedTime().
m_multisession
bool XFILE::CCurlFile::m_multisession protected
Referenced by CCurlFile(), Open(), and Seek().
m_oldState
CReadState* XFILE::CCurlFile::m_oldState protected
Referenced by CCurlFile(), Close(), Seek(), and ~CCurlFile().
m_opened
bool XFILE::CCurlFile::m_opened protected
Referenced by Cancel(), CCurlFile(), Close(), XFILE::CDAVFile::Delete(), Exists(), GetLength(), GetPosition(), Open(), OpenForWrite(), XFILE::CDAVFile::Rename(), Stat(), and Write().
m_overflowBuffer
char* XFILE::CCurlFile::m_overflowBuffer protected
Referenced by XFILE::CCurlFile::CReadState::CReadState(), XFILE::CCurlFile::CReadState::Disconnect(), XFILE::CCurlFile::CReadState::FillBuffer(), and XFILE::CCurlFile::CReadState::WriteCallback().
m_overflowSize
unsigned int XFILE::CCurlFile::m_overflowSize = 0 protected
Referenced by XFILE::CCurlFile::CReadState::CReadState(), XFILE::CCurlFile::CReadState::Disconnect(), XFILE::CCurlFile::CReadState::FillBuffer(), and XFILE::CCurlFile::CReadState::WriteCallback().
m_password
std::string XFILE::CCurlFile::m_password protected
Referenced by ParseAndCorrectUrl(), and SetCommonOptions().
m_postdata
std::string XFILE::CCurlFile::m_postdata protected
Referenced by Get(), ParseAndCorrectUrl(), Post(), SetCommonOptions(), and SetPostData().
m_postdataset
bool XFILE::CCurlFile::m_postdataset protected
Referenced by CCurlFile(), Get(), ParseAndCorrectUrl(), Post(), and SetCommonOptions().
m_proxyhost
std::string XFILE::CCurlFile::m_proxyhost protected
Referenced by ParseAndCorrectUrl(), SetCommonOptions(), and SetProxy().
m_proxypassword
std::string XFILE::CCurlFile::m_proxypassword protected
Referenced by ParseAndCorrectUrl(), SetCommonOptions(), and SetProxy().
m_proxyport
uint16_t XFILE::CCurlFile::m_proxyport = 3128 protected
Referenced by ParseAndCorrectUrl(), SetCommonOptions(), and SetProxy().
m_proxytype
ProxyType XFILE::CCurlFile::m_proxytype = PROXY_HTTP protected
Referenced by ParseAndCorrectUrl(), SetCommonOptions(), and SetProxy().
m_proxyuser
std::string XFILE::CCurlFile::m_proxyuser protected
Referenced by ParseAndCorrectUrl(), SetCommonOptions(), and SetProxy().
m_redirectlimit
int XFILE::CCurlFile::m_redirectlimit protected
Referenced by CCurlFile(), ParseAndCorrectUrl(), and SetCommonOptions().
m_referer
std::string XFILE::CCurlFile::m_referer protected
Referenced by Close(), SetCommonOptions(), and SetReferer().
m_requestheaders
MAPHTTPHEADERS XFILE::CCurlFile::m_requestheaders protected
Referenced by ClearRequestHeaders(), SetRequestHeader(), SetRequestHeader(), and SetRequestHeaders().
m_seekable
bool XFILE::CCurlFile::m_seekable protected
Referenced by CCurlFile(), IoControl(), Open(), ParseAndCorrectUrl(), and Seek().
m_skipshout
bool XFILE::CCurlFile::m_skipshout protected
Referenced by CCurlFile(), Open(), and ParseAndCorrectUrl().
m_state
CReadState* XFILE::CCurlFile::m_state protected
Referenced by Cancel(), CCurlFile(), Close(), XFILE::CDAVFile::Execute(), Exists(), GetDownloadSpeed(), GetHttpHeader(), GetInfoString(), GetLength(), GetPosition(), GetProperty(), GetPropertyValues(), Open(), OpenForWrite(), Read(), ReadData(), ReadString(), Reset(), Seek(), SetCommonOptions(), Stat(), Write(), and ~CCurlFile().
m_stillRunning
int XFILE::CCurlFile::m_stillRunning protected
Referenced by XFILE::CCurlFile::CReadState::Connect(), XFILE::CCurlFile::CReadState::CReadState(), XFILE::CCurlFile::CReadState::FillBuffer(), XFILE::CCurlFile::CReadState::Read(), and Write().
m_url
std::string XFILE::CCurlFile::m_url protected
Referenced by Close(), XFILE::CDAVFile::Execute(), GetInfoString(), GetURL(), Open(), OpenForWrite(), ParseAndCorrectUrl(), Seek(), SetCommonOptions(), SetProxy(), and Write().
m_userAgent
std::string XFILE::CCurlFile::m_userAgent protected
Referenced by SetCommonOptions(), and SetUserAgent().
m_username
std::string XFILE::CCurlFile::m_username protected
Referenced by ParseAndCorrectUrl(), and SetCommonOptions().
m_verifyPeer
bool XFILE::CCurlFile::m_verifyPeer = true protected
Referenced by ParseAndCorrectUrl(), and SetCommonOptions().
m_writeOffset
int64_t XFILE::CCurlFile::m_writeOffset = 0 protected
Referenced by OpenForWrite(), and Write().
The documentation for this class was generated from the following files:
CurlFile.h
CurlFile.cpp