Kodi Documentation: TestStacks.cpp File Reference
TestStacks.cpp File Reference
#include "FileItem.h"
#include "FileItemList.h"
#include "filesystem/Directory.h"
#include "test/TestUtils.h"
#include <string>
#include <gtest/gtest.h>
Classes
class TestStacks
Namespaces
namespace anonymous_namespace{TestStacks.cpp}
Functions
TEST_F (TestStacks, TestMovieFilesStackFilesAB)
TEST_F (TestStacks, TestMovieFilesStackFilesPart)
TEST_F (TestStacks, TestMovieFilesStackDvdIso)
Variables
const std::string anonymous_namespace{TestStacks.cpp}::VIDEO_EXTENSIONS = ".mpg|.mpeg|.mp4|.mkv|.mk3d|.iso"
Function Documentation
TEST_F() [1/3]
TEST_F (TestStacks , TestMovieFilesStackDvdIso)
References XFILE::DIR_FLAG_DEFAULTS, EXPECT_EQ(), CFileItemList::Get(), XFILE::CDirectory::GetDirectory(), CFileItemList::Size(), CFileItemList::Stack(), anonymous_namespace{TestStacks.cpp}::VIDEO_EXTENSIONS, and XBMC_REF_FILE_PATH.
TEST_F() [2/3]
TEST_F (TestStacks , TestMovieFilesStackFilesAB)
References XFILE::DIR_FLAG_DEFAULTS, EXPECT_EQ(), CFileItemList::Get(), XFILE::CDirectory::GetDirectory(), CFileItemList::Size(), CFileItemList::Stack(), anonymous_namespace{TestStacks.cpp}::VIDEO_EXTENSIONS, and XBMC_REF_FILE_PATH.
TEST_F() [3/3]
TEST_F (TestStacks , TestMovieFilesStackFilesPart)
References XFILE::DIR_FLAG_DEFAULTS, EXPECT_EQ(), CFileItemList::Get(), XFILE::CDirectory::GetDirectory(), CFileItemList::Size(), CFileItemList::Stack(), anonymous_namespace{TestStacks.cpp}::VIDEO_EXTENSIONS, and XBMC_REF_FILE_PATH.