Kodi Documentation: IRenderingCallback Class Reference
IRenderingCallback Class Reference abstract
#include <IRenderingCallback.h>
Public Member Functions
virtual ~IRenderingCallback ()=default
virtual bool Create (int x, int y, int w, int h, void *device)=0
virtual void Render ()=0
virtual void Stop ()=0
virtual bool IsDirty ()
Constructor & Destructor Documentation
~IRenderingCallback()
virtual IRenderingCallback::~IRenderingCallback () virtual default
Member Function Documentation
Create()
virtual bool IRenderingCallback::Create (int x, int y, int w, int h, void * device) pure virtual
Implemented in ADDON::CGUIAddonRenderingControl.
IsDirty()
virtual bool IRenderingCallback::IsDirty () inline virtual
Reimplemented in ADDON::CGUIAddonRenderingControl.
Referenced by CGUIRenderingControl::Process().
Render()
virtual void IRenderingCallback::Render () pure virtual
Implemented in ADDON::CGUIAddonRenderingControl.
Referenced by CGUIRenderingControl::Render().
Stop()
virtual void IRenderingCallback::Stop () pure virtual
Implemented in ADDON::CGUIAddonRenderingControl.
Referenced by CGUIRenderingControl::FreeResources().
The documentation for this class was generated from the following file:
IRenderingCallback.h