Kodi Documentation: kodi::addon::PVRProvider Class Reference
kodi::addon::PVRProvider Class Reference
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 7. Provider » class PVRProvider
#include <Providers.h>
Public Member Functions
void SetUniqueId (unsigned int uniqueId)
required
Unique identifier for this provider.
unsigned int GetUniqueId () const
To get with SetUniqueId changed values.
void SetName (const std::string &name)
required
Name given to this provider.
std::string GetName () const
To get with SetName changed values.
void SetType (PVR_PROVIDER_TYPE type)
optional
Provider type.
PVR_PROVIDER_TYPE GetType () const
To get with SetType changed values.
void SetIconPath (const std::string &iconPath)
optional
Path to the provider icon (if present).
std::string GetIconPath () const
To get with SetIconPath changed values.
void SetCountries (const std::vector< std::string > &countries)
optional
The country codes for the provider.
std::vector< std::string > GetCountries () const
To get with SetCountries changed values.
void SetLanguages (const std::vector< std::string > &languages)
optional
The language codes for the provider.
std::vector< std::string > GetLanguages () const
To get with SetLanguages changed values.
Public Member Functions inherited from kodi::addon::DynamicCStructHdl< PVRProvider, PVR_PROVIDER >
DynamicCStructHdl ()
DynamicCStructHdl (const DynamicCStructHdl &cppClass)
DynamicCStructHdl (const PVR_PROVIDER *cStructure)
DynamicCStructHdl (PVR_PROVIDER *cStructure)
const DynamicCStructHdl & operator= (const DynamicCStructHdl &right)
const DynamicCStructHdl & operator= (const PVR_PROVIDER &right)
virtual ~DynamicCStructHdl ()
operator PVR_PROVIDER * ()
operator const PVR_PROVIDER * () const
const PVR_PROVIDER * GetCStructure () const
PVR_PROVIDER * release ()
Static Public Member Functions
static void AllocResources (const PVR_PROVIDER *source, PVR_PROVIDER *target)
static void FreeResources (PVR_PROVIDER *target)
Private Member Functions
PVRProvider (const PVR_PROVIDER *provider)
PVRProvider (PVR_PROVIDER *provider)
Friends
class CInstancePVRClient
Additional Inherited Members
Protected Attributes inherited from kodi::addon::DynamicCStructHdl< PVRProvider, PVR_PROVIDER >
PVR_PROVIDER * m_cStructure
Constructor & Destructor Documentation
PVRProvider() [1/2]
kodi::addon::PVRProvider::PVRProvider (const PVR_PROVIDER * provider) inline private
PVRProvider() [2/2]
kodi::addon::PVRProvider::PVRProvider (PVR_PROVIDER * provider) inline private
Member Function Documentation
AllocResources()
static void kodi::addon::PVRProvider::AllocResources (const PVR_PROVIDER * source, PVR_PROVIDER * target) inline static
References kodi::addon::AllocAndCopyString(), PVR_PROVIDER::strCountries, PVR_PROVIDER::strIconPath, PVR_PROVIDER::strLanguages, and PVR_PROVIDER::strName.
FreeResources()
static void kodi::addon::PVRProvider::FreeResources (PVR_PROVIDER * target) inline static
References kodi::addon::FreeString(), PVR_PROVIDER::strCountries, PVR_PROVIDER::strIconPath, PVR_PROVIDER::strLanguages, and PVR_PROVIDER::strName.
GetCountries()
std::vector< std::string > kodi::addon::PVRProvider::GetCountries () const inline
To get with SetCountries changed values.
References kodi::addon::DynamicCStructHdl< PVRProvider, PVR_PROVIDER >::m_cStructure, PROVIDER_STRING_TOKEN_SEPARATOR, kodi::tools::StringUtils::Split(), and PVR_PROVIDER::strCountries.
GetLanguages()
std::vector< std::string > kodi::addon::PVRProvider::GetLanguages () const inline
To get with SetLanguages changed values.
References kodi::addon::DynamicCStructHdl< PVRProvider, PVR_PROVIDER >::m_cStructure, PROVIDER_STRING_TOKEN_SEPARATOR, kodi::tools::StringUtils::Split(), and PVR_PROVIDER::strLanguages.
SetCountries()
void kodi::addon::PVRProvider::SetCountries (const std::vector< std::string > & countries) inline
optional
The country codes for the provider.
Note
ISO 3166 country codes required (e.g 'GB,IE,CA').
References kodi::tools::StringUtils::Join(), kodi::addon::DynamicCStructHdl< PVRProvider, PVR_PROVIDER >::m_cStructure, PROVIDER_STRING_TOKEN_SEPARATOR, kodi::addon::ReallocAndCopyString(), and PVR_PROVIDER::strCountries.
SetLanguages()
void kodi::addon::PVRProvider::SetLanguages (const std::vector< std::string > & languages) inline
optional
The language codes for the provider.
Note
RFC 5646 standard codes required (e.g.: 'en_GB,fr_CA').
References kodi::tools::StringUtils::Join(), kodi::addon::DynamicCStructHdl< PVRProvider, PVR_PROVIDER >::m_cStructure, PROVIDER_STRING_TOKEN_SEPARATOR, kodi::addon::ReallocAndCopyString(), and PVR_PROVIDER::strLanguages.
Friends And Related Symbol Documentation
CInstancePVRClient
friend class CInstancePVRClient friend
The documentation for this class was generated from the following file:
Providers.h