Kodi Documentation: anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist Class Reference
anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist Class Reference
Public Member Functions
CAsyncGetItemsForPlaylist (const std::shared_ptr< CFileItem > &item, CFileItemList &queuedItems)
~CAsyncGetItemsForPlaylist () override=default
void Run () override
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Private Member Functions
void GetItemsForPlaylist (const std::shared_ptr< CFileItem > &item)
Private Attributes
const std::shared_ptr< CFileItem > m_item
CFileItemList & m_queuedItems
CMusicDatabase m_musicDatabase
Constructor & Destructor Documentation
CAsyncGetItemsForPlaylist()
anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::CAsyncGetItemsForPlaylist (const std::shared_ptr< CFileItem > & item, CFileItemList & queuedItems) inline
~CAsyncGetItemsForPlaylist()
anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::~CAsyncGetItemsForPlaylist () override default
Member Function Documentation
GetItemsForPlaylist()
void anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist (const std::shared_ptr< CFileItem > & item) private
References CDbUrl::AppendPath(), CFileItemList::ClearSortState(), XFILE::CMusicDatabaseDirectory::ContainsSongs(), KODI::PLAYLIST::CPlayListFactory::Create(), XFILE::DIR_FLAG_DEFAULTS, CLabelFormatter::FormatLabels(), CDbUrl::FromString(), g_passwordManager, XFILE::CDirectory::GetDirectory(), CServiceBroker::GetGUI(), GetItemsForPlaylist(), anonymous_namespace{MusicUtils.cpp}::GetSortDescription(), CGUIViewState::GetViewState(), CGUIComponent::GetWindowManager(), KODI::MUSIC::IsAudio(), KODI::NETWORK::IsInternetStream(), CGUIPassword::IsItemUnlocked(), KODI::MUSIC::IsMusicDb(), KODI::PLAYLIST::IsPlayList(), KODI::VIDEO::IsVideo(), CLog::Log(), LOGERROR, LABEL_MASKS::m_strLabel2File, LABEL_MASKS::m_strLabel2Folder, LABEL_MASKS::m_strLabelFile, LABEL_MASKS::m_strLabelFolder, CFileItemList::Sort(), SortDescription::sortBy, SortByLabel, CDbUrl::ToString(), and WINDOW_MUSIC_NAV.
Referenced by GetItemsForPlaylist().
Run()
void anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::Run () inline override virtual
Implements IRunnable.
Member Data Documentation
m_item
const std::shared_ptr<CFileItem> anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::m_item private
m_musicDatabase
CMusicDatabase anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::m_musicDatabase private
m_queuedItems
CFileItemList& anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::m_queuedItems private
The documentation for this class was generated from the following file:
MusicUtils.cpp