Kodi Documentation: SOCKETS::CBaseSocket Class Reference
SOCKETS::CBaseSocket Class Reference abstract
#include <Socket.h>
Public Member Functions
CBaseSocket ()
virtual ~CBaseSocket ()
virtual bool Bind (bool localOnly, int port, int range=0)=0
virtual bool Connect ()=0
virtual void Close ()
bool Ready ()
bool Bound ()
SocketType Type ()
int Port ()
virtual SOCKET Socket ()=0
Protected Member Functions
virtual void SetBound (bool set=true)
virtual void SetReady (bool set=true)
Protected Attributes
SocketType m_Type
bool m_bReady
bool m_bBound
int m_iPort
Constructor & Destructor Documentation
CBaseSocket()
SOCKETS::CBaseSocket::CBaseSocket () inline
References m_bBound, m_bReady, m_iPort, m_Type, and SOCKETS::ST_TCP.
~CBaseSocket()
virtual SOCKETS::CBaseSocket::~CBaseSocket () inline virtual
References Close().
Member Function Documentation
Bind()
virtual bool SOCKETS::CBaseSocket::Bind (bool localOnly, int port, int range = 0) pure virtual
Implemented in SOCKETS::CPosixUDPSocket.
Bound()
bool SOCKETS::CBaseSocket::Bound () inline
References m_bBound.
Referenced by SOCKETS::CPosixUDPSocket::Bind().
Close()
virtual void SOCKETS::CBaseSocket::Close () inline virtual
Reimplemented in SOCKETS::CPosixUDPSocket.
Referenced by ~CBaseSocket().
Connect()
virtual bool SOCKETS::CBaseSocket::Connect () pure virtual
Implemented in SOCKETS::CPosixUDPSocket.
Port()
int SOCKETS::CBaseSocket::Port () inline
References m_iPort.
Ready()
bool SOCKETS::CBaseSocket::Ready () inline
References m_bReady.
Referenced by SOCKETS::CSocketListener::AddSocket().
SetBound()
virtual void SOCKETS::CBaseSocket::SetBound (bool set = true) inline protected virtual
References m_bBound.
Referenced by SOCKETS::CPosixUDPSocket::Bind(), and SOCKETS::CPosixUDPSocket::Close().
SetReady()
virtual void SOCKETS::CBaseSocket::SetReady (bool set = true) inline protected virtual
References m_bReady.
Referenced by SOCKETS::CPosixUDPSocket::Bind(), and SOCKETS::CPosixUDPSocket::Close().
Socket()
virtual SOCKET SOCKETS::CBaseSocket::Socket () pure virtual
Implemented in SOCKETS::CPosixUDPSocket.
Referenced by SOCKETS::CSocketListener::AddSocket().
Type()
SocketType SOCKETS::CBaseSocket::Type () inline
References m_Type.
Member Data Documentation
m_bBound
bool SOCKETS::CBaseSocket::m_bBound protected
Referenced by Bound(), CBaseSocket(), and SetBound().
m_bReady
bool SOCKETS::CBaseSocket::m_bReady protected
Referenced by CBaseSocket(), Ready(), and SetReady().
m_iPort
int SOCKETS::CBaseSocket::m_iPort protected
Referenced by SOCKETS::CPosixUDPSocket::Bind(), CBaseSocket(), and Port().
m_Type
SocketType SOCKETS::CBaseSocket::m_Type protected
Referenced by CBaseSocket(), SOCKETS::CUDPSocket::CUDPSocket(), and Type().
The documentation for this class was generated from the following file:
network/Socket.h