Kodi Documentation: CGenericTouchInputHandler Class Reference
CGenericTouchInputHandler Class Reference
Input » Touch » Touch
Generic implementation of ITouchInputHandler to handle low level (raw) touch events and translate them into touch actions which are passed on to the registered ITouchActionHandler implementation.
#include <GenericTouchInputHandler.h>
Public Member Functions
bool HandleTouchInput (TouchInput event, float x, float y, int64_t time, int32_t pointer=0, float size=0.0f) override
Handle a touch event.
bool UpdateTouchPointer (int32_t pointer, float x, float y, int64_t time, float size=0.0f) override
Update the coordinates of a pointer.
Public Member Functions inherited from ITouchInputHandler
ITouchInputHandler ()
~ITouchInputHandler () override=default
void SetScreenDPI (float dpi)
float GetScreenDPI ()
Public Member Functions inherited from ITouchInputHandling
ITouchInputHandling ()
~ITouchInputHandling () override=default
void RegisterHandler (ITouchActionHandler *touchHandler)
Register a touch input handler.
void UnregisterHandler ()
Unregister the previously registered touch handler.
Static Public Member Functions
static CGenericTouchInputHandler & GetInstance ()
Get an instance of the touch input manager.
Static Public Attributes
static constexpr int MAX_POINTERS = 2
Private Types
enum TouchGestureState {
TouchGestureUnknown = 0 , TouchGestureSingleTouch , TouchGestureSingleTouchHold , TouchGesturePan ,
TouchGestureMultiTouchStart , TouchGestureMultiTouchHold , TouchGestureMultiTouch , TouchGestureMultiTouchDone
}
Private Member Functions
CGenericTouchInputHandler ()
~CGenericTouchInputHandler () override
CGenericTouchInputHandler (const CGenericTouchInputHandler &)=delete
CGenericTouchInputHandler const & operator= (CGenericTouchInputHandler const &)=delete
void OnTimeout () override
void saveLastTouch ()
void setGestureState (TouchGestureState gestureState)
void triggerDetectors (TouchInput event, int32_t pointer)
float AdjustPointerSize (float size)
Private Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Private Attributes
CCriticalSection m_critical
std::unique_ptr< CTimer > m_holdTimer
std::array< Pointer, MAX_POINTERS > m_pointers
std::set< std::unique_ptr< IGenericTouchGestureDetector > > m_detectors
TouchGestureState m_gestureState = TouchGestureUnknown
TouchGestureState m_gestureStateOld = TouchGestureUnknown
Additional Inherited Members
Protected Member Functions inherited from ITouchInputHandling
void OnTouchAbort () override
A touch action has been aborted.
bool OnSingleTouchStart (float x, float y) override
A single touch has started.
bool OnSingleTouchHold (float x, float y) override
A single touch has been held down for a certain amount of time.
bool OnSingleTouchMove (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY) override
A single touch has moved.
bool OnSingleTouchEnd (float x, float y) override
A single touch has been lifted.
bool OnMultiTouchDown (float x, float y, int32_t pointer) override
An additional touch has been performed.
bool OnMultiTouchHold (float x, float y, int32_t pointers=2) override
Multiple simultaneous touches have been held down for a certain amount of time.
bool OnMultiTouchMove (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY, int32_t pointer) override
A touch has moved.
bool OnMultiTouchUp (float x, float y, int32_t pointer) override
A touch has been lifted (but there are still active touches)
bool OnTouchGestureStart (float x, float y) override
A pan gesture with a single touch has been started.
bool OnTouchGesturePan (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY) override
A pan gesture with a single touch is in progress.
bool OnTouchGestureEnd (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY) override
A pan gesture with a single touch has ended.
void OnTap (float x, float y, int32_t pointers=1) override
A tap with a one or more touches has been performed.
void OnLongPress (float x, float y, int32_t pointers=1) override
One or more touches have been held down for a certain amount of time.
void OnSwipe (TouchMoveDirection direction, float xDown, float yDown, float xUp, float yUp, float velocityX, float velocityY, int32_t pointers=1) override
One or more touches has been moved quickly in a single direction in a short time.
void OnZoomPinch (float centerX, float centerY, float zoomFactor) override
Two simultaneous touches have been held down and moved to perform a zooming/pinching gesture.
void OnRotate (float centerX, float centerY, float angle) override
Two simultaneous touches have been held down and moved to perform a rotating gesture.
Protected Member Functions inherited from ITouchActionHandler
virtual ~ITouchActionHandler ()=default
Protected Attributes inherited from ITouchInputHandler
std::atomic< float > m_dpi
DPI value of the touch screen.
Detailed Description
Generic implementation of ITouchInputHandler to handle low level (raw) touch events and translate them into touch actions which are passed on to the registered ITouchActionHandler implementation.
The generic implementation supports single a double touch and hold actions and basic gesture recognition for panning, swiping, pinching/zooming and rotating.
See also
ITouchInputHandler
Member Enumeration Documentation
TouchGestureState
enum CGenericTouchInputHandler::TouchGestureState private
Enumerator
TouchGestureUnknown
TouchGestureSingleTouch
TouchGestureSingleTouchHold
TouchGesturePan
TouchGestureMultiTouchStart
TouchGestureMultiTouchHold
TouchGestureMultiTouch
TouchGestureMultiTouchDone
Constructor & Destructor Documentation
CGenericTouchInputHandler() [1/2]
CGenericTouchInputHandler::CGenericTouchInputHandler () private
~CGenericTouchInputHandler()
CGenericTouchInputHandler::~CGenericTouchInputHandler () override private default
CGenericTouchInputHandler() [2/2]
CGenericTouchInputHandler::CGenericTouchInputHandler (const CGenericTouchInputHandler &) private delete
Member Function Documentation
AdjustPointerSize()
float CGenericTouchInputHandler::AdjustPointerSize (float size) private
References ITouchInputHandler::m_dpi.
Referenced by HandleTouchInput(), and UpdateTouchPointer().
GetInstance()
CGenericTouchInputHandler & CGenericTouchInputHandler::GetInstance () static
Get an instance of the touch input manager.
Referenced by CAndroidTouch::CAndroidTouch(), CInertialScrollingHandler::CheckForInertialScrolling(), CLibInputTouch::CLibInputTouch(), CWinSystemWin10DX::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::DestroyWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::InitWindowSystem(), CWinEventsWin10::OnDpiChanged(), CWinEventsWin10::OnPointerExited(), CWinEventsWin10::OnPointerMoved(), CWinEventsWin10::OnPointerPressed(), CWinEventsWin10::OnPointerReleased(), CAndroidTouch::onTouchEvent(), CLibInputTouch::ProcessTouchCancel(), CLibInputTouch::ProcessTouchFrame(), CLibInputTouch::ProcessTouchMotion(), KODI::WINDOWING::WAYLAND::CInputProcessorTouch::SendTouchPointEvent(), CAndroidTouch::setDPI(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateTouchDpi(), KODI::WINDOWING::WAYLAND::CInputProcessorTouch::UpdateTouchPoint(), and CAndroidTouch::~CAndroidTouch().
HandleTouchInput()
bool CGenericTouchInputHandler::HandleTouchInput (TouchInput event, float x, float y, int64_t time, int32_t pointer = 0, float size = 0.0f) override virtual
Handle a touch event.
Handles the given touch event at the given location. This takes into account all the currently active pointers which need to be updated before calling this method to actually interpret and handle the changes in touch.
Parameters
event The actual touch event (abort, down, up, move)
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
time The time (in nanoseconds) when this touch occurred
pointer The number of the touch pointer which caused this event (default 0)
size The size of the touch pointer (with sub-pixel) (default 0.0)
Returns
True if the event was handled otherwise false.
See also
Update
Implements ITouchInputHandler.
References AdjustPointerSize(), CLog::Log(), LOGDEBUG, m_critical, m_detectors, ITouchInputHandler::m_dpi, m_gestureState, m_gestureStateOld, m_holdTimer, m_pointers, MAX_POINTERS, ITouchInputHandling::OnMultiTouchDown(), ITouchInputHandling::OnMultiTouchMove(), ITouchInputHandling::OnMultiTouchUp(), ITouchInputHandling::OnSingleTouchEnd(), ITouchInputHandling::OnSingleTouchMove(), ITouchInputHandling::OnSingleTouchStart(), ITouchInputHandling::OnTap(), ITouchInputHandling::OnTouchAbort(), ITouchInputHandling::OnTouchGestureEnd(), ITouchInputHandling::OnTouchGesturePan(), ITouchInputHandling::OnTouchGestureStart(), saveLastTouch(), setGestureState(), TouchGestureMultiTouch, TouchGestureMultiTouchDone, TouchGestureMultiTouchHold, TouchGestureMultiTouchStart, TouchGesturePan, TouchGestureSingleTouch, TouchGestureSingleTouchHold, TouchGestureUnknown, TouchInputAbort, TouchInputDown, TouchInputMove, TouchInputUp, and triggerDetectors().
Referenced by CWinEventsWin10::OnPointerExited(), CWinEventsWin10::OnPointerMoved(), CWinEventsWin10::OnPointerPressed(), CWinEventsWin10::OnPointerReleased(), CAndroidTouch::onTouchEvent(), CLibInputTouch::ProcessTouchCancel(), CLibInputTouch::ProcessTouchFrame(), and KODI::WINDOWING::WAYLAND::CInputProcessorTouch::SendTouchPointEvent().
OnTimeout()
void CGenericTouchInputHandler::OnTimeout () override private virtual
Implements ITimerCallback.
References m_critical, m_gestureState, m_pointers, ITouchInputHandling::OnLongPress(), ITouchInputHandling::OnMultiTouchHold(), ITouchInputHandling::OnSingleTouchHold(), setGestureState(), TouchGestureMultiTouchHold, TouchGestureMultiTouchStart, TouchGestureSingleTouch, and TouchGestureSingleTouchHold.
operator=()
CGenericTouchInputHandler const & CGenericTouchInputHandler::operator= (CGenericTouchInputHandler const &) private delete
saveLastTouch()
void CGenericTouchInputHandler::saveLastTouch () private
References m_pointers.
Referenced by HandleTouchInput().
setGestureState()
void CGenericTouchInputHandler::setGestureState (TouchGestureState gestureState) inline private
References m_gestureState, and m_gestureStateOld.
Referenced by HandleTouchInput(), and OnTimeout().
triggerDetectors()
void CGenericTouchInputHandler::triggerDetectors (TouchInput event, int32_t pointer) private
References m_detectors, m_pointers, TouchInputAbort, TouchInputDown, TouchInputMove, and TouchInputUp.
Referenced by HandleTouchInput().
UpdateTouchPointer()
bool CGenericTouchInputHandler::UpdateTouchPointer (int32_t pointer, float x, float y, int64_t time, float size = 0.0f) override virtual
Update the coordinates of a pointer.
Depending on how a platform handles touch input and provides the necessary events this method needs to be called at different times. If there's an event for every touch action this method does not need to be called at all. If there's only a touch event for the primary pointer (and no special events for any secondary pointers in a multi touch gesture) this method should be called for every active secondary pointer before calling Handle.
Parameters
pointer The number of the touch pointer which caused this event (default 0)
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
time The time (in nanoseconds) when this touch occurred
size The size of the touch pointer (with sub-pixel) (default 0.0)
Returns
True if the pointer was updated otherwise false.
See also
Handle
Reimplemented from ITouchInputHandler.
References AdjustPointerSize(), CVector::length(), m_critical, m_detectors, m_pointers, and MAX_POINTERS.
Referenced by CWinEventsWin10::OnPointerMoved(), CAndroidTouch::onTouchEvent(), CLibInputTouch::ProcessTouchMotion(), and KODI::WINDOWING::WAYLAND::CInputProcessorTouch::UpdateTouchPoint().
Member Data Documentation
m_critical
CCriticalSection CGenericTouchInputHandler::m_critical private
Referenced by HandleTouchInput(), OnTimeout(), and UpdateTouchPointer().
m_detectors
std::set<std::unique_ptr<IGenericTouchGestureDetector> > CGenericTouchInputHandler::m_detectors private
Referenced by HandleTouchInput(), triggerDetectors(), and UpdateTouchPointer().
m_gestureState
TouchGestureState CGenericTouchInputHandler::m_gestureState = TouchGestureUnknown private
Referenced by HandleTouchInput(), OnTimeout(), and setGestureState().
m_gestureStateOld
TouchGestureState CGenericTouchInputHandler::m_gestureStateOld = TouchGestureUnknown private
Referenced by HandleTouchInput(), and setGestureState().
m_holdTimer
std::unique_ptr<CTimer> CGenericTouchInputHandler::m_holdTimer private
Referenced by HandleTouchInput().
m_pointers
std::array<Pointer, MAX_POINTERS> CGenericTouchInputHandler::m_pointers private
Referenced by HandleTouchInput(), OnTimeout(), saveLastTouch(), triggerDetectors(), and UpdateTouchPointer().
MAX_POINTERS
constexpr int CGenericTouchInputHandler::MAX_POINTERS = 2 static constexpr
Referenced by HandleTouchInput(), KODI::WINDOWING::WAYLAND::CInputProcessorTouch::OnTouchDown(), CAndroidTouch::onTouchEvent(), and UpdateTouchPointer().
The documentation for this class was generated from the following files:
GenericTouchInputHandler.h
GenericTouchInputHandler.cpp