Kodi Documentation: XBMCAddonUtils::GuiLock Class Reference
XBMCAddonUtils::GuiLock Class Reference
#include <AddonUtils.h>
Public Member Functions
GuiLock (XBMCAddon::LanguageHook *languageHook, bool offScreen)
~GuiLock ()
Protected Attributes
XBMCAddon::LanguageHook * m_languageHook = nullptr
bool m_offScreen = false
Constructor & Destructor Documentation
GuiLock()
XBMCAddonUtils::GuiLock::GuiLock (XBMCAddon::LanguageHook * languageHook, bool offScreen)
References XBMCAddon::LanguageHook::DelayedCallOpen(), g_application, XBMCAddon::LanguageHook::GetLanguageHook(), m_languageHook, and m_offScreen.
~GuiLock()
XBMCAddonUtils::GuiLock::~GuiLock ()
References XBMCAddon::LanguageHook::DelayedCallClose(), g_application, m_languageHook, and m_offScreen.
Member Data Documentation
m_languageHook
XBMCAddon::LanguageHook* XBMCAddonUtils::GuiLock::m_languageHook = nullptr protected
Referenced by GuiLock(), and ~GuiLock().
m_offScreen
bool XBMCAddonUtils::GuiLock::m_offScreen = false protected
Referenced by GuiLock(), and ~GuiLock().
The documentation for this class was generated from the following files:
AddonUtils.h
AddonUtils.cpp