Kodi Documentation: CGFTestable Class Reference
CGFTestable Class Reference
Static Public Member Functions
static std::string GetType (const TiXmlElement *pControlNode)
static bool GetIntRange (const TiXmlNode *pRootNode, const char *strTag, int &iMinValue, int &iMaxValue, int &iIntervalValue)
static bool GetFloatRange (const TiXmlNode *pRootNode, const char *strTag, float &fMinValue, float &fMaxValue, float &fIntervalValue)
static bool GetPosition (const TiXmlNode *node, const char *tag, const float parentSize, float &value)
static bool GetDimension (const TiXmlNode *node, const char *strTag, const float parentSize, float &value, float &min)
static bool GetDimensions (const TiXmlNode *node, const char *leftTag, const char *rightTag, const char *centerLeftTag, const char *centerRightTag, const char *widthTag, const float parentSize, float &left, float &width, float &min_width)
static bool GetMovingSpeedConfig (const TiXmlNode *pRootNode, const char *strTag, UTILS::MOVING_SPEED::MapEventConfig &movingSpeedCfg)
static bool GetConditionalVisibility (const TiXmlNode *control, std::string &condition, std::string &allowHiddenFocus)
static bool GetString (const TiXmlNode *pRootNode, const char *strTag, std::string &strString)
Static Public Member Functions inherited from CGUIControlFactory
static CGUIControl::GUICONTROLTYPES TranslateControlType (const std::string &type)
translate from control name to control type
static std::string TranslateControlType (CGUIControl::GUICONTROLTYPES type)
translate from control type to control name
static bool GetAspectRatio (const TiXmlNode *pRootNode, const char *strTag, CAspectRatio &aspectRatio)
static bool GetInfoTexture (const TiXmlNode *pRootNode, const char *strTag, CTextureInfo &image, KODI::GUILIB::GUIINFO::CGUIInfoLabel &info, int parentID)
static bool GetTexture (const TiXmlNode *pRootNode, const char *strTag, CTextureInfo &image)
static bool GetAlignment (const TiXmlNode *pRootNode, const char *strTag, uint32_t &dwAlignment)
static bool GetAlignmentY (const TiXmlNode *pRootNode, const char *strTag, uint32_t &dwAlignment)
static bool GetAnimations (TiXmlNode *control, const CRect &rect, int context, std::vector< CAnimation > &animation)
static float ParsePosition (const char *pos, const float parentSize)
Create an info label from an XML element Processes XML elements of the form <xmltag fallback="fallback_value">info_value</xmltag> where info_value may use $INFO[], $LOCALIZE[], $NUMBER[] etc. If either the fallback_value or info_value are natural numbers they are interpreted as ids for lookup in strings.po. The fallback attribute is optional.
static bool GetInfoLabelFromElement (const TiXmlElement *element, KODI::GUILIB::GUIINFO::CGUIInfoLabel &infoLabel, int parentID)
static void GetInfoLabel (const TiXmlNode *pControlNode, const std::string &labelTag, KODI::GUILIB::GUIINFO::CGUIInfoLabel &infoLabel, int parentID)
static void GetInfoLabels (const TiXmlNode *pControlNode, const std::string &labelTag, std::vector< KODI::GUILIB::GUIINFO::CGUIInfoLabel > &infoLabels, int parentID)
static bool GetColor (const TiXmlNode *pRootNode, const char *strTag, KODI::UTILS::COLOR::Color &value)
static bool GetInfoColor (const TiXmlNode *pRootNode, const char *strTag, KODI::GUILIB::GUIINFO::CGUIInfoColor &value, int parentID)
static std::string FilterLabel (const std::string &label)
static bool GetConditionalVisibility (const TiXmlNode *control, std::string &condition)
static bool GetActions (const TiXmlNode *pRootNode, const char *strTag, CGUIAction &actions)
static void GetRectFromString (const std::string &string, CRect &rect)
static bool GetHitRect (const TiXmlNode *pRootNode, CRect &rect, const CRect &parentRect)
static bool GetScroller (const TiXmlNode *pControlNode, const std::string &scrollerTag, CScroller &scroller)
Additional Inherited Members
Public Member Functions inherited from CGUIControlFactory
CGUIControlFactory (void)
virtual ~CGUIControlFactory (void)
CGUIControl * Create (int parentID, const CRect &rect, TiXmlElement *pControlNode, bool insideContainer=false)
Static Protected Member Functions inherited from CGUIControlFactory
static std::string GetType (const TiXmlElement *pControlNode)
static bool GetMovingSpeedConfig (const TiXmlNode *pRootNode, const char *strTag, KODI::UTILS::MOVING_SPEED::MapEventConfig &movingSpeedCfg)
static bool GetConditionalVisibility (const TiXmlNode *control, std::string &condition, std::string &allowHiddenFocus)
static bool GetString (const TiXmlNode *pRootNode, const char *strTag, std::string &strString)
static bool GetFloatRange (const TiXmlNode *pRootNode, const char *strTag, float &iMinValue, float &iMaxValue, float &iIntervalValue)
static bool GetIntRange (const TiXmlNode *pRootNode, const char *strTag, int &iMinValue, int &iMaxValue, int &iIntervalValue)
static bool GetPosition (const TiXmlNode *node, const char *tag, const float parentSize, float &value)
Get the value of a position tag from XML Handles both absolute and relative values.
static bool GetDimension (const TiXmlNode *node, const char *strTag, const float parentSize, float &value, float &min)
grab a dimension out of the XML
static bool GetDimensions (const TiXmlNode *node, const char *leftTag, const char *rightTag, const char *centerLeftTag, const char *centerRightTag, const char *widthTag, const float parentSize, float &left, float &width, float &min_width)
Retrieve the dimensions for a control.
Member Function Documentation
GetConditionalVisibility()
static bool CGFTestable::GetConditionalVisibility (const TiXmlNode * control, std::string & condition, std::string & allowHiddenFocus) inline static
References CGUIControlFactory::GetConditionalVisibility().
GetDimension()
static bool CGFTestable::GetDimension (const TiXmlNode * node, const char * strTag, const float parentSize, float & value, float & min) inline static
References CGUIControlFactory::GetDimension(), min, node, and value.
Referenced by TEST_P().
GetDimensions()
static bool CGFTestable::GetDimensions (const TiXmlNode * node, const char * leftTag, const char * rightTag, const char * centerLeftTag, const char * centerRightTag, const char * widthTag, const float parentSize, float & left, float & width, float & min_width) inline static
References CGUIControlFactory::GetDimensions(), left, and node.
Referenced by TEST_P().
GetFloatRange()
static bool CGFTestable::GetFloatRange (const TiXmlNode * pRootNode, const char * strTag, float & fMinValue, float & fMaxValue, float & fIntervalValue) inline static
References CGUIControlFactory::GetFloatRange().
Referenced by TEST_P().
GetIntRange()
static bool CGFTestable::GetIntRange (const TiXmlNode * pRootNode, const char * strTag, int & iMinValue, int & iMaxValue, int & iIntervalValue) inline static
References CGUIControlFactory::GetIntRange().
Referenced by TEST_P().
GetMovingSpeedConfig()
static bool CGFTestable::GetMovingSpeedConfig (const TiXmlNode * pRootNode, const char * strTag, UTILS::MOVING_SPEED::MapEventConfig & movingSpeedCfg) inline static
References CGUIControlFactory::GetMovingSpeedConfig().
Referenced by TEST_P().
GetPosition()
static bool CGFTestable::GetPosition (const TiXmlNode * node, const char * tag, const float parentSize, float & value) inline static
References CGUIControlFactory::GetPosition(), node, and value.
Referenced by TEST_P().
GetString()
static bool CGFTestable::GetString (const TiXmlNode * pRootNode, const char * strTag, std::string & strString) inline static
References CGUIControlFactory::GetString().
Referenced by TEST_P().
GetType()
static std::string CGFTestable::GetType (const TiXmlElement * pControlNode) inline static
References CGUIControlFactory::GetType().
Referenced by TEST_P().
The documentation for this class was generated from the following file:
TestGUIControlFactory.cpp