Kodi Documentation: ADDON::CAddonSystemSettings Class Reference
ADDON::CAddonSystemSettings Class Reference
#include <AddonSystemSettings.h>
Public Member Functions
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
bool GetActive (AddonType type, AddonPtr &addon)
bool SetActive (AddonType type, const std::string &addonID)
bool IsActive (const IAddon &addon)
int GetAddonAutoUpdateMode () const
AddonRepoUpdateMode GetAddonRepoUpdateMode () const
bool UnsetActive (const AddonInfoPtr &addon)
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Static Public Member Functions
static CAddonSystemSettings & GetInstance ()
Private Member Functions
CAddonSystemSettings ()
CAddonSystemSettings (const CAddonSystemSettings &)=delete
CAddonSystemSettings & operator= (const CAddonSystemSettings &)=delete
~CAddonSystemSettings () override=default
Private Attributes
const std::map< AddonType, std::string > m_activeSettings
Constructor & Destructor Documentation
CAddonSystemSettings() [1/2]
ADDON::CAddonSystemSettings::CAddonSystemSettings () private
References ADDON::AUDIOENCODER, and CSettings::SETTING_AUDIOCDS_ENCODER.
CAddonSystemSettings() [2/2]
ADDON::CAddonSystemSettings::CAddonSystemSettings (const CAddonSystemSettings &) private delete
~CAddonSystemSettings()
ADDON::CAddonSystemSettings::~CAddonSystemSettings () override private default
Member Function Documentation
GetActive()
bool ADDON::CAddonSystemSettings::GetActive (AddonType type, AddonPtr & addon)
References ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), and CServiceBroker::GetSettingsComponent().
Referenced by CGUIDialogContentSettings::OnSettingAction().
GetAddonAutoUpdateMode()
int ADDON::CAddonSystemSettings::GetAddonAutoUpdateMode () const
Gets Kodi addon auto update mode
Returns
the autoupdate mode value
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_ADDONS_AUTOUPDATES.
Referenced by ADDON::CRepositoryUpdater::OnJobComplete().
GetAddonRepoUpdateMode()
AddonRepoUpdateMode ADDON::CAddonSystemSettings::GetAddonRepoUpdateMode () const
Gets Kodi preferred addon repository update mode
Returns
the preferred mode value
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_ADDONS_UPDATEMODE.
Referenced by ADDON::CAddonRepos::DoAddonUpdateCheck(), ADDON::CAddonRepos::FindDependency(), ADDON::CAddonRepos::GetLatestAddonVersionFromAllRepos(), ADDON::CAddonRepos::GetLatestAddonVersions(), and ADDON::CAddonRepos::GetLatestAddonVersionsFromAllRepos().
GetInstance()
CAddonSystemSettings & ADDON::CAddonSystemSettings::GetInstance () static
Referenced by ADDON::CAddonMgr::DisableIncompatibleAddons(), ADDON::CAddonRepos::DoAddonUpdateCheck(), ADDON::CAddonRepos::FindDependency(), ADDON::CAddonRepos::GetLatestAddonVersionFromAllRepos(), ADDON::CAddonRepos::GetLatestAddonVersions(), ADDON::CAddonRepos::GetLatestAddonVersionsFromAllRepos(), CMusicDatabase::GetScraper(), CNfoFile::GetScrapers(), CApplication::Initialize(), CSettings::InitializeISettingCallbacks(), CGUIWindowMusicNav::ManageInfoProvider(), CGUIDialogAddonInfo::OnInstall(), ADDON::CRepositoryUpdater::OnJobComplete(), CGUIDialogAddonInfo::OnSelect(), CGUIDialogContentSettings::OnSettingAction(), OpenDefaultSettings(), XFILE::OutdatedAddons(), CHTTPWebinterfaceHandler::ResolveAddon(), ADDON::CRepositoryUpdater::ScheduleUpdate(), MUSIC_INFO::CMusicInfoScanner::ScrapeInfoAddedAlbums(), SetDefaultAddon(), CGUIDialogInfoProviderSettings::Show(), and CGUIDialogAddonInfo::UpdateControls().
IsActive()
bool ADDON::CAddonSystemSettings::IsActive (const IAddon & addon)
References ADDON::IAddon::ID(), and ADDON::IAddon::Type().
Referenced by CGUIDialogAddonInfo::UpdateControls().
OnSettingAction()
void ADDON::CAddonSystemSettings::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References CGUIWindowManager::ActivateWindow(), KODI::UTILS::StringUtils::Format(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), KODI::UTILS::StringUtils::Join(), CSettings::SETTING_ADDONS_MANAGE_DEPENDENCIES, CSettings::SETTING_ADDONS_REMOVE_ORPHANED_DEPENDENCIES, CSettings::SETTING_ADDONS_SHOW_RUNNING, and WINDOW_ADDON_BROWSER.
OnSettingChanged()
void ADDON::CAddonSystemSettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_ADDONS_ALLOW_UNKNOWN_SOURCES.
operator=()
CAddonSystemSettings & ADDON::CAddonSystemSettings::operator= (const CAddonSystemSettings &) private delete
SetActive()
bool ADDON::CAddonSystemSettings::SetActive (AddonType type, const std::string & addonID)
References CServiceBroker::GetSettingsComponent().
Referenced by CGUIDialogAddonInfo::OnSelect(), and SetDefaultAddon().
UnsetActive()
bool ADDON::CAddonSystemSettings::UnsetActive (const AddonInfoPtr & addon)
Attempt to unset addon as active. Returns true if addon is no longer active, false if it could not be unset (e.g. if the addon is the default)
References CServiceBroker::GetSettingsComponent().
Member Data Documentation
m_activeSettings
const std::map<AddonType, std::string> ADDON::CAddonSystemSettings::m_activeSettings private
The documentation for this class was generated from the following files:
AddonSystemSettings.h
AddonSystemSettings.cpp