Kodi Documentation: GUIInfoLabel.cpp File Reference
GUIInfoLabel.cpp File Reference
#include "guilib/guiinfo/GUIInfoLabel.h"
#include "FileItem.h"
#include "GUIInfoManager.h"
#include "ServiceBroker.h"
#include "addons/Skin.h"
#include "games/GameServices.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIListItem.h"
#include "guilib/LocalizeStrings.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
Classes
struct infoformat
Enumerations
enum EINFOFORMAT {
NONE = 0 , FORMATINFO , FORMATESCINFO , FORMATVAR ,
FORMATESCVAR
}
Functions
std::string LocalizeReplacer (const std::string &str)
std::string AddonReplacer (const std::string &str)
std::string ControllerFeatureReplacer (const std::string &str)
std::string NumberReplacer (const std::string &str)
Variables
static const infoformat infoformatmap []
Enumeration Type Documentation
EINFOFORMAT
enum EINFOFORMAT
Enumerator
NONE
FORMATINFO
FORMATESCINFO
FORMATVAR
FORMATESCVAR
Function Documentation
AddonReplacer()
std::string AddonReplacer (const std::string & str)
References g_localizeStrings, and CLocalizeStrings::GetAddonString().
Referenced by KODI::GUILIB::GUIINFO::CGUIInfoLabel::ReplaceAddonStrings().
ControllerFeatureReplacer()
std::string ControllerFeatureReplacer (const std::string & str)
References CServiceBroker::GetGameServices(), and KODI::GAME::CGameServices::TranslateFeature().
Referenced by KODI::GUILIB::GUIINFO::CGUIInfoLabel::ReplaceControllerStrings().
LocalizeReplacer()
std::string LocalizeReplacer (const std::string & str)
References g_localizeStrings, g_localizeStringsTemp, and CLocalizeStrings::Get().
Referenced by KODI::GUILIB::GUIINFO::CGUIInfoLabel::ReplaceLocalize().
NumberReplacer()
std::string NumberReplacer (const std::string & str)
Referenced by KODI::GUILIB::GUIINFO::CGUIInfoLabel::ReplaceLocalize().
Variable Documentation
infoformatmap
const infoformat infoformatmap[] static
Initial value:
= {{ "$INFO[",    FORMATINFO},
                                           { "$ESCINFO[", FORMATESCINFO},
                                           { "$VAR[",     FORMATVAR},
                                           { "$ESCVAR[",  FORMATESCVAR}}
Referenced by KODI::GUILIB::GUIINFO::CGUIInfoLabel::Parse().