Kodi Documentation: ElasticTweener Class Reference
ElasticTweener Class Reference
#include <Tween.h>
Public Member Functions
ElasticTweener (float a=0.0, float p=0.0)
float Tween (float time, float start, float change, float duration) override
Public Member Functions inherited from Tweener
Tweener (TweenerType tweenerType=EASE_OUT)
virtual ~Tweener ()=default
void SetEasing (TweenerType type)
virtual bool HasResumePoint () const
Protected Member Functions
float easeIn (float time, float start, float change, float duration) const
float easeOut (float time, float start, float change, float duration) const
float easeInOut (float time, float start, float change, float duration) const
Protected Attributes
float _a
float _p
Protected Attributes inherited from Tweener
TweenerType m_tweenerType
Constructor & Destructor Documentation
ElasticTweener()
ElasticTweener::ElasticTweener (float a = 0.0, float p = 0.0) inline
References _a, and _p.
Member Function Documentation
easeIn()
float ElasticTweener::easeIn (float time, float start, float change, float duration) const inline protected
References _a, _p, and M_PI.
Referenced by Tween().
easeInOut()
float ElasticTweener::easeInOut (float time, float start, float change, float duration) const inline protected
References _a, _p, and M_PI.
Referenced by Tween().
easeOut()
float ElasticTweener::easeOut (float time, float start, float change, float duration) const inline protected
References _a, _p, and M_PI.
Referenced by Tween().
Tween()
float ElasticTweener::Tween (float time, float start, float change, float duration) inline override virtual
Implements Tweener.
References EASE_IN, EASE_INOUT, EASE_OUT, easeIn(), easeInOut(), easeOut(), and Tweener::m_tweenerType.
Member Data Documentation
_a
float ElasticTweener::_a protected
Referenced by easeIn(), easeInOut(), easeOut(), and ElasticTweener().
_p
float ElasticTweener::_p protected
Referenced by easeIn(), easeInOut(), easeOut(), and ElasticTweener().
The documentation for this class was generated from the following file:
Tween.h