Kodi Documentation: CGUIControlLookup Class Reference
CGUIControlLookup Class Reference
#include <GUIControlLookup.h>
Public Member Functions
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual CGUIControl * Clone () const =0
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void Render ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual bool OnAction (const CAction &action)
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
Perform a mouse action.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual bool OnMessage (CGUIMessage &message)
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual void AllocResources ()
virtual void FreeResources (bool immediately=false)
virtual void DynamicResourceAlloc (bool bOnOff)
virtual bool IsDynamicallyAllocated ()
virtual bool CanFocus () const
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Types
typedef std::multimap< int, CGUIControl * > LookupMap
Protected Member Functions
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Private Attributes
LookupMap m_lookup
Additional Inherited Members
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Typedef Documentation
LookupMap
typedef std::multimap<int, CGUIControl *> CGUIControlLookup::LookupMap protected
Constructor & Destructor Documentation
CGUIControlLookup() [1/3]
CGUIControlLookup::CGUIControlLookup () default
CGUIControlLookup() [2/3]
CGUIControlLookup::CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height) inline
CGUIControlLookup() [3/3]
CGUIControlLookup::CGUIControlLookup (const CGUIControlLookup & from) explicit
~CGUIControlLookup()
CGUIControlLookup::~CGUIControlLookup (void) override default
Member Function Documentation
AddLookup()
void CGUIControlLookup::AddLookup (CGUIControl * control) protected
References AddLookup(), CGUIControl::GetID(), GetLookup(), m_lookup, and CGUIControl::m_parentControl.
Referenced by CGUIControlGroup::AddControl(), and AddLookup().
ClearLookup()
void CGUIControlLookup::ClearLookup () inline protected
References m_lookup.
Referenced by CGUIControlGroup::ClearAll().
GetControl()
CGUIControl * CGUIControlLookup::GetControl (int id, std::vector< CGUIControl * > * idCollector = nullptr) override virtual
Reimplemented from CGUIControl.
References CGUIControl::IsVisible(), and m_lookup.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonHideGroup(), CGUIDialogSettingsBase::AddSettingControl(), CGUIDialogKeyboardGeneric::Backspace(), CGUIWindow::ControlGroupHasFocus(), CGUIDialogSettingsBase::CreateSettings(), KODI::GAME::CGUIActivePortList::DeinitializeGUI(), CGUIWindowSettingsScreenCalibration::DoProcess(), CGUIDialogKaiToast::DoWork(), CGUIMediaWindow::Filter(), CGUIDialogKaiToast::FrameMove(), CGUIDialogNumeric::FrameMove(), KODI::GAME::CGUIAgentControllerList::FrameMove(), KODI::GAME::CDialogGameSaves::FrameMove(), KODI::GAME::CDialogGameVideoSelect::FrameMove(), CGUIDialogSettingsBase::FreeControls(), CGUIDialogSettingsBase::FreeSettingsControls(), KODI::GUILIB::GUIINFO::GetActiveContainer(), ADDON::CGUIAddonWindow::GetAddonControl(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), KODI::GAME::CGUIFeatureList::GetButtonControl(), XBMCAddon::xbmcgui::Window::GetControlById(), PVR::CGUIWindowPVRGuideBase::GetGridControl(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GAME::CGUIControllerList::Initialize(), KODI::GAME::CGUIFeatureList::Initialize(), PVR::CGUIPVRChannelGroupsSelector::Initialize(), KODI::GAME::CGUIActivePortList::InitializeGUI(), PVR::CGUIDialogPVRRadioRDSInfo::InitInfoControls(), KODI::GAME::CDialogGameOSDHelp::IsVisible(), CGUIMediaWindow::Load(), CGUIDialogKeyboardGeneric::MoveCursor(), CGUIWindowSettingsScreenCalibration::NextControl(), CGUIDialogKeyboardGeneric::NormalCharacter(), CGUIDialogKeyboardGeneric::OnAction(), CGUIWindow::OnAction(), CGUIWindowVisualisation::OnAction(), CGUIDialogKeyboardGeneric::OnClickButton(), CGUIDialogContextMenu::OnDeinitWindow(), KODI::GAME::CGUIControllerList::OnFocus(), CGUIDialogBoxBase::OnInitWindow(), CGUIDialogKeyboardGeneric::OnInitWindow(), CGUIDialogNumeric::OnInitWindow(), CGUIDialogSmartPlaylistRule::OnInitWindow(), ADDON::CGUIAddonWindow::OnMessage(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIDialogSlider::OnMessage(), CGUIControlGroup::OnMessage(), CGUIWindow::OnMessage(), CGUIWindowVisualisation::OnMessage(), PVR::CGUIDialogPVRRadioRDSInfo::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindow::OnMouseAction(), CGUIWindow::OnMove(), CGUIWindowFileManager::OnPopupMenu(), CGUIDialogColorPicker::OnWindowLoaded(), CGUIDialogContextMenu::OnWindowLoaded(), CGUIDialogFileBrowser::OnWindowLoaded(), CGUIDialogKeyboardGeneric::OnWindowLoaded(), CGUIDialogProgress::OnWindowLoaded(), CGUIDialogSelect::OnWindowLoaded(), KODI::GAME::CGUIAgentControllerList::OnWindowLoaded(), KODI::GAME::CDialogGameSaves::OnWindowLoaded(), KODI::GAME::CDialogGameVideoSelect::OnWindowLoaded(), KODI::GAME::CGUIPortList::OnWindowLoaded(), CGUIWindowMusicNav::OnWindowLoaded(), PVR::CGUIDialogPVRChannelManager::OnWindowLoaded(), PVR::CGUIDialogPVRGroupManager::OnWindowLoaded(), PVR::CGUIDialogPVRItemsViewBase::OnWindowLoaded(), CGUIDialogVideoBookmarks::OnWindowLoaded(), CGUIWindowLoginScreen::OnWindowLoaded(), CGUIDialogVideoInfo::Play(), CGUIWindowSlideShow::RenderErrorMessage(), CGUIWindowSettingsScreenCalibration::ResetControls(), CGUIControlGroup::SendControlMessage(), ADDON::Interface_GUIWindow::set_focus_id(), CGUIDialogSettingsBase::SetControlLabel(), CGUIWindowPointer::SetPointer(), CGUIDialogSlider::SetSlider(), CGUIDialogContextMenu::SetupButtons(), CGUIDialogSettingsBase::SetupControls(), PVR::CGUIWindowPVRGuideBase::ShouldNavigateToGridContainer(), CGUIDialogVideoInfo::Update(), PVR::CGUIWindowPVRChannelsBase::UpdateButtons(), PVR::CGUIWindowPVRRecordingsBase::UpdateButtons(), and CGUIWindowSettingsScreenCalibration::UpdateFromControl().
GetLookup()
const LookupMap & CGUIControlLookup::GetLookup () const inline protected
References m_lookup.
Referenced by AddLookup(), and RemoveLookup().
GetLookupControls()
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > CGUIControlLookup::GetLookupControls (int controlId) const inline protected
References m_lookup.
Referenced by CGUIControlGroup::GetFocusedControl().
IsValidControl()
bool CGUIControlLookup::IsValidControl (const CGUIControl * control) const protected
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
Parameters
control to check
Returns
true if the control is valid, false otherwise.
References CGUIControl::GetID(), and m_lookup.
RemoveLookup() [1/2]
void CGUIControlLookup::RemoveLookup () protected
References m_lookup, CGUIControl::m_parentControl, and RemoveLookup().
Referenced by CGUIControlGroup::ClearAll(), and CGUIControlGroup::RemoveControl().
RemoveLookup() [2/2]
void CGUIControlLookup::RemoveLookup (CGUIControl * control) protected
References CGUIControl::GetID(), GetLookup(), m_lookup, CGUIControl::m_parentControl, and RemoveLookup().
Referenced by RemoveLookup(), and RemoveLookup().
Member Data Documentation
m_lookup
LookupMap CGUIControlLookup::m_lookup private
Referenced by AddLookup(), ClearLookup(), GetControl(), GetLookup(), GetLookupControls(), IsValidControl(), RemoveLookup(), and RemoveLookup().
The documentation for this class was generated from the following files:
GUIControlLookup.h
GUIControlLookup.cpp