Kodi Documentation: CD3DHelper Class Reference
CD3DHelper Class Reference
#include <D3DResource.h>
Static Public Member Functions
static void XMStoreColor (float *floats, DWORD dword)
static void XMStoreColor (DirectX::XMFLOAT4 *floats, DWORD dword)
static void XMStoreColor (float *floats, unsigned char a, unsigned char r, unsigned char g, unsigned char b)
static void XMStoreColor (DirectX::XMFLOAT4 *floats, unsigned char a, unsigned char r, unsigned char g, unsigned char b)
static void PSClearShaderResources (ID3D11DeviceContext *pContext)
static size_t BitsPerPixel (DXGI_FORMAT fmt)
Member Function Documentation
BitsPerPixel()
size_t CD3DHelper::BitsPerPixel (DXGI_FORMAT fmt) static
Referenced by CD3DBuffer::Create(), and CD3DTexture::CreateInternal().
PSClearShaderResources()
static void CD3DHelper::PSClearShaderResources (ID3D11DeviceContext * pContext) inline static
References KODI_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT.
Referenced by CWinShader::Execute(), and CRenderSystemDX::PresentRender().
XMStoreColor() [1/4]
static void CD3DHelper::XMStoreColor (DirectX::XMFLOAT4 * floats, DWORD dword) inline static
References XMStoreColor().
XMStoreColor() [2/4]
static void CD3DHelper::XMStoreColor (DirectX::XMFLOAT4 * floats, unsigned char a, unsigned char r, unsigned char g, unsigned char b) inline static
References XMStoreColor().
XMStoreColor() [3/4]
static void CD3DHelper::XMStoreColor (float * floats, DWORD dword) inline static
Referenced by CRenderSystemDX::ClearBuffers(), OVERLAY::COverlayQuadsDX::COverlayQuadsDX(), CGUITextureD3D::Draw(), CD3DTexture::DrawQuad(), CSlideShowPicDX::Render(), CGUIFontTTF::RenderCharacter(), KODI::RETRO::CRPRendererGuiTexture::RenderInternal(), XMStoreColor(), and XMStoreColor().
XMStoreColor() [4/4]
static void CD3DHelper::XMStoreColor (float * floats, unsigned char a, unsigned char r, unsigned char g, unsigned char b) inline static
The documentation for this class was generated from the following files:
D3DResource.h
D3DResource.cpp