Kodi Documentation: CGUIFontTTF Class Reference
CGUIFontTTF Class Reference abstract
#include <GUIFontTTF.h>
Classes
struct Character
struct CTranslatedVertices
struct Glyph
struct RunInfo
Public Member Functions
virtual ~CGUIFontTTF ()
void Clear ()
bool Load (const std::string &strFilename, float height=20.0f, float aspect=1.0f, float lineSpacing=1.0f, bool border=false)
void Begin ()
void End ()
virtual CVertexBuffer CreateVertexBuffer (const std::vector< SVertex > &vertices) const
virtual void DestroyVertexBuffer (CVertexBuffer &bufferHandle) const
const std::string & GetFontIdent () const
Static Public Member Functions
static CGUIFontTTF * CreateGUIFontTTF (const std::string &fontIdent)
Protected Member Functions
CGUIFontTTF (const std::string &fontIdent)
void AddReference ()
void RemoveReference ()
std::vector< Glyph > GetHarfBuzzShapedGlyphs (const vecText &text)
float GetTextWidthInternal (const vecText &text)
float GetTextWidthInternal (const vecText &text, const std::vector< Glyph > &glyph)
float GetCharWidthInternal (character_t ch)
float GetTextHeight (float lineSpacing, int numLines) const
float GetTextBaseLine () const
float GetLineHeight (float lineSpacing) const
float GetFontHeight () const
void DrawTextInternal (CGraphicContext &context, float x, float y, const std::vector< KODI::UTILS::COLOR::Color > &colors, const vecText &text, uint32_t alignment, float maxPixelWidth, bool scrolling, float dx=0.0f, float dy=0.0f)
Character * GetCharacter (character_t letter, FT_UInt glyphIndex)
bool CacheCharacter (FT_UInt glyphIndex, uint32_t style, Character *ch)
void RenderCharacter (CGraphicContext &context, float posX, float posY, const Character *ch, KODI::UTILS::COLOR::Color color, bool roundX, std::vector< SVertex > &vertices)
void ClearCharacterCache ()
virtual std::unique_ptr< CTexture > ReallocTexture (unsigned int &newHeight)=0
virtual bool CopyCharToTexture (FT_BitmapGlyph bitGlyph, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)=0
virtual void DeleteHardwareTexture ()=0
void SetGlyphStrength (FT_GlyphSlot slot, int glyphStrength)
unsigned int GetTextureLineHeight () const
the height of each line in the texture. Accounts for spacing between lines to avoid characters overlapping.
unsigned int GetMaxFontHeight () const
Static Protected Member Functions
static void ObliqueGlyph (FT_GlyphSlot slot)
Protected Attributes
float m_height {0.0f}
std::unique_ptr< CTexture > m_texture
unsigned int m_textureWidth {0}
unsigned int m_textureHeight {0}
int m_posX {0}
int m_posY {0}
KODI::UTILS::COLOR::Color m_color {KODI::UTILS::COLOR::NONE}
std::vector< Character > m_char
Character * m_charquick [LOOKUPTABLE_SIZE] {nullptr}
bool m_ellipseCached {false}
float m_ellipsesWidth {0.0f}
unsigned int m_cellBaseLine {0}
unsigned int m_cellHeight {0}
unsigned int m_maxFontHeight {0}
unsigned int m_nestedBeginCount {0}
FT_Face m_face {nullptr}
FT_Stroker m_stroker {nullptr}
hb_font_t * m_hbFont {nullptr}
float m_originX {0.0f}
float m_originY {0.0f}
unsigned int m_nTexture {0}
std::vector< CTranslatedVertices > m_vertexTrans
std::vector< SVertex > m_vertex
float m_textureScaleX {0.0f}
float m_textureScaleY {0.0f}
const std::string m_fontIdent
std::vector< uint8_t > m_fontFileInMemory
CGUIFontCache< CGUIFontCacheStaticPosition, CGUIFontCacheStaticValue > m_staticCache
CGUIFontCache< CGUIFontCacheDynamicPosition, CGUIFontCacheDynamicValue > m_dynamicCache
CRenderSystemBase * m_renderSystem
Private Member Functions
float GetTabSpaceLength ()
virtual bool FirstBegin ()=0
virtual void LastEnd ()=0
CGUIFontTTF (const CGUIFontTTF &)=delete
CGUIFontTTF & operator= (const CGUIFontTTF &)=delete
Private Attributes
int m_referenceCount {0}
Static Private Attributes
static constexpr int MAX_GLYPH_IDX = 4096
static constexpr size_t LOOKUPTABLE_SIZE = MAX_GLYPH_IDX * FONT_STYLES_COUNT
Friends
class CGUIFont
Constructor & Destructor Documentation
~CGUIFontTTF()
CGUIFontTTF::~CGUIFontTTF (void) virtual
References Clear().
CGUIFontTTF() [1/2]
CGUIFontTTF::CGUIFontTTF (const std::string & fontIdent) explicit protected
CGUIFontTTF() [2/2]
CGUIFontTTF::CGUIFontTTF (const CGUIFontTTF &) private delete
Member Function Documentation
AddReference()
void CGUIFontTTF::AddReference () protected
References m_referenceCount.
Referenced by CGUIFont::CGUIFont(), CGUIFontTTFDX::CreateVertexBuffer(), and CGUIFont::SetFont().
Begin()
void CGUIFontTTF::Begin ()
References FirstBegin(), m_nestedBeginCount, m_texture, m_vertex, and m_vertexTrans.
Referenced by CGUIFont::Begin(), DrawTextInternal(), and GetCharacter().
CacheCharacter()
bool CGUIFontTTF::CacheCharacter (FT_UInt glyphIndex, uint32_t style, Character * ch) protected
References CopyCharToTexture(), FONT_STYLE_BOLD, FONT_STYLE_ITALICS, FONT_STYLE_LIGHT, GetMaxFontHeight(), CRenderSystemBase::GetMaxTextureSize(), GetTextureLineHeight(), LOGDEBUG, CGUIFontTTF::Character::m_advance, CGUIFontTTF::Character::m_bottom, m_cellBaseLine, m_face, CGUIFontTTF::Character::m_glyphAndStyle, CGUIFontTTF::Character::m_glyphIndex, CGUIFontTTF::Character::m_left, m_maxFontHeight, CGUIFontTTF::Character::m_offsetX, CGUIFontTTF::Character::m_offsetY, m_posX, m_posY, m_renderSystem, CGUIFontTTF::Character::m_right, m_stroker, m_texture, m_textureHeight, m_textureWidth, CGUIFontTTF::Character::m_top, ObliqueGlyph(), ReallocTexture(), MathUtils::round_int(), and SetGlyphStrength().
Referenced by GetCharacter().
Clear()
void CGUIFontTTF::Clear ()
References g_freeTypeLibrary, m_charquick, m_face, m_fontFileInMemory, m_hbFont, m_nestedBeginCount, m_posX, m_posY, m_stroker, m_texture, m_vertex, and m_vertexTrans.
Referenced by ~CGUIFontTTF().
ClearCharacterCache()
void CGUIFontTTF::ClearCharacterCache () protected
References DeleteHardwareTexture(), GetTextureLineHeight(), m_char, m_charquick, m_posX, m_posY, m_texture, m_textureHeight, and m_textureWidth.
Referenced by GetCharacter().
CopyCharToTexture()
virtual bool CGUIFontTTF::CopyCharToTexture (FT_BitmapGlyph bitGlyph, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2) protected pure virtual
Implemented in CGUIFontTTFDX, CGUIFontTTFGL, and CGUIFontTTFGLES.
Referenced by CacheCharacter().
CreateGUIFontTTF()
CGUIFontTTF * CGUIFontTTF::CreateGUIFontTTF (const std::string & fontIdent) static
Referenced by GUIFontManager::LoadTTF(), and GUIFontManager::ReloadTTFFonts().
CreateVertexBuffer()
virtual CVertexBuffer CGUIFontTTF::CreateVertexBuffer (const std::vector< SVertex > & vertices) const inline virtual
Reimplemented in CGUIFontTTFDX, CGUIFontTTFGL, and CGUIFontTTFGLES.
Referenced by DrawTextInternal().
DeleteHardwareTexture()
virtual void CGUIFontTTF::DeleteHardwareTexture () protected pure virtual
Implemented in CGUIFontTTFDX, CGUIFontTTFGL, and CGUIFontTTFGLES.
Referenced by ClearCharacterCache().
DestroyVertexBuffer()
virtual void CGUIFontTTF::DestroyVertexBuffer (CVertexBuffer & bufferHandle) const inline virtual
Reimplemented in CGUIFontTTFDX, CGUIFontTTFGL, and CGUIFontTTFGLES.
Referenced by CVertexBuffer::clear().
DrawTextInternal()
void CGUIFontTTF::DrawTextInternal (CGraphicContext & context, float x, float y, const std::vector< KODI::UTILS::COLOR::Color > & colors, const vecText & text, uint32_t alignment, float maxPixelWidth, bool scrolling, float dx = 0.0f, float dy = 0.0f) protected
Todo:
: This validate is the last resort and can result in a bad rendered text because the alignment it is used also by caller components for other operations this inform the problem on the log, potentially can be improved by add validating alignments from each parent caller component
References Begin(), color, CreateVertexBuffer(), End(), GetCharacter(), CGraphicContext::GetClipRegion(), GetHarfBuzzShapedGlyphs(), GetTabSpaceLength(), GetTextWidthInternal(), CGUIFontCache< Position, Value >::Lookup(), CGUIFontTTF::Character::m_advance, m_cellHeight, m_dynamicCache, m_ellipseCached, m_ellipsesWidth, m_originX, m_originY, m_renderSystem, m_staticCache, m_vertex, m_vertexTrans, CGUIFontCacheDynamicPosition::m_x, CGUIFontCacheDynamicPosition::m_y, CGUIFontCacheDynamicPosition::m_z, RenderCharacter(), MathUtils::round_int(), CGraphicContext::ScaleFinalXCoord(), CGraphicContext::ScaleFinalYCoord(), CGraphicContext::ScaleFinalZCoord(), CRenderSystemBase::ScissorsCanEffectClipping(), text, XBFONT_CENTER_X, XBFONT_CENTER_Y, XBFONT_JUSTIFIED, XBFONT_RIGHT, XBFONT_TRUNCATED, and XBFONT_TRUNCATED_LEFT.
Referenced by CGUIFont::DrawScrollingText(), and CGUIFont::DrawText().
End()
void CGUIFontTTF::End ()
References LastEnd(), and m_nestedBeginCount.
Referenced by DrawTextInternal(), CGUIFont::End(), and GetCharacter().
FirstBegin()
virtual bool CGUIFontTTF::FirstBegin () private pure virtual
Implemented in CGUIFontTTFDX, CGUIFontTTFGL, and CGUIFontTTFGLES.
Referenced by Begin().
GetCharacter()
CGUIFontTTF::Character * CGUIFontTTF::GetCharacter (character_t letter, FT_UInt glyphIndex) protected
References Begin(), CacheCharacter(), ClearCharacterCache(), End(), LOGDEBUG, LOGERROR, LOOKUPTABLE_SIZE, m_char, m_charquick, m_face, m_nestedBeginCount, and MAX_GLYPH_IDX.
Referenced by DrawTextInternal(), GetCharWidthInternal(), GetTabSpaceLength(), and GetTextWidthInternal().
GetCharWidthInternal()
float CGUIFontTTF::GetCharWidthInternal (character_t ch) protected
References GetCharacter(), GetTabSpaceLength(), and CGUIFontTTF::Character::m_advance.
Referenced by CGUIFont::GetCharWidth().
GetFontHeight()
float CGUIFontTTF::GetFontHeight () const inline protected
References m_height.
Referenced by CGUIFont::GetScaleFactor().
GetFontIdent()
const std::string & CGUIFontTTF::GetFontIdent () const inline
References m_fontIdent.
GetHarfBuzzShapedGlyphs()
std::vector< CGUIFontTTF::Glyph > CGUIFontTTF::GetHarfBuzzShapedGlyphs (const vecText & text) protected
References m_hbFont, CGUIFontTTF::RunInfo::m_startOffset, and text.
Referenced by DrawTextInternal(), and GetTextWidthInternal().
GetLineHeight()
float CGUIFontTTF::GetLineHeight (float lineSpacing) const protected
References m_face.
Referenced by CGUIFont::ClippedRegionIsEmpty(), CGUIFont::GetLineHeight(), and GetTextHeight().
GetMaxFontHeight()
unsigned int CGUIFontTTF::GetMaxFontHeight () const protected
References m_maxFontHeight.
Referenced by CacheCharacter().
GetTabSpaceLength()
float CGUIFontTTF::GetTabSpaceLength () private
References GetCharacter(), and CGUIFontTTF::Character::m_advance.
Referenced by DrawTextInternal(), GetCharWidthInternal(), and GetTextWidthInternal().
GetTextBaseLine()
float CGUIFontTTF::GetTextBaseLine () const inline protected
References m_cellBaseLine.
Referenced by CGUIFont::GetTextBaseLine().
GetTextHeight()
float CGUIFontTTF::GetTextHeight (float lineSpacing, int numLines) const protected
References GetLineHeight(), and m_cellHeight.
Referenced by CGUIFont::ClippedRegionIsEmpty(), and CGUIFont::GetTextHeight().
GetTextureLineHeight()
unsigned int CGUIFontTTF::GetTextureLineHeight () const protected
the height of each line in the texture. Accounts for spacing between lines to avoid characters overlapping.
References m_cellHeight.
Referenced by CacheCharacter(), ClearCharacterCache(), and Load().
GetTextWidthInternal() [1/2]
float CGUIFontTTF::GetTextWidthInternal (const vecText & text) protected
References GetHarfBuzzShapedGlyphs(), GetTextWidthInternal(), and text.
Referenced by DrawTextInternal(), CGUIFont::GetTextWidth(), and GetTextWidthInternal().
GetTextWidthInternal() [2/2]
float CGUIFontTTF::GetTextWidthInternal (const vecText & text, const std::vector< Glyph > & glyph) protected
References GetCharacter(), GetTabSpaceLength(), CGUIFontTTF::Character::m_advance, CGUIFontTTF::Character::m_left, CGUIFontTTF::Character::m_offsetX, CGUIFontTTF::Character::m_right, and text.
LastEnd()
virtual void CGUIFontTTF::LastEnd () private pure virtual
Implemented in CGUIFontTTFDX, CGUIFontTTFGL, and CGUIFontTTFGLES.
Referenced by End().
Load()
bool CGUIFontTTF::Load (const std::string & strFilename, float height = 20.0f, float aspect = 1.0f, float lineSpacing = 1.0f, bool border = false)
References g_freeTypeLibrary, CRenderSystemBase::GetMaxTextureSize(), GetTextureLineHeight(), m_cellBaseLine, m_cellHeight, m_face, m_fontFileInMemory, m_hbFont, m_height, m_posX, m_posY, m_renderSystem, m_stroker, m_texture, m_textureHeight, m_textureScaleX, m_textureWidth, CTextureBase::PadPow2(), and MathUtils::round_int().
ObliqueGlyph()
void CGUIFontTTF::ObliqueGlyph (FT_GlyphSlot slot) static protected
Referenced by CacheCharacter().
operator=()
CGUIFontTTF & CGUIFontTTF::operator= (const CGUIFontTTF &) private delete
ReallocTexture()
virtual std::unique_ptr< CTexture > CGUIFontTTF::ReallocTexture (unsigned int & newHeight) protected pure virtual
Implemented in CGUIFontTTFDX, CGUIFontTTFGL, and CGUIFontTTFGLES.
Referenced by CacheCharacter().
RemoveReference()
void CGUIFontTTF::RemoveReference () protected
References g_fontManager, and m_referenceCount.
Referenced by CGUIFont::SetFont(), and CGUIFont::~CGUIFont().
RenderCharacter()
void CGUIFontTTF::RenderCharacter (CGraphicContext & context, float posX, float posY, const Character * ch, KODI::UTILS::COLOR::Color color, bool roundX, std::vector< SVertex > & vertices) protected
References SVertex::a, KODI::UTILS::GL::A, SVertex::b, KODI::UTILS::GL::B, CGraphicContext::ClipRect(), color, SVertex::g, KODI::UTILS::GL::G, KODI::UTILS::GL::GetChannelFromARGB(), CGraphicContext::GetGUIScaleX(), CGraphicContext::GetGUIScaleY(), CGUIFontTTF::Character::m_bottom, m_color, CGUIFontTTF::Character::m_left, CGUIFontTTF::Character::m_offsetX, CGUIFontTTF::Character::m_offsetY, m_originX, m_originY, m_renderSystem, CGUIFontTTF::Character::m_right, m_textureScaleX, m_textureScaleY, CGUIFontTTF::Character::m_top, SVertex::r, KODI::UTILS::GL::R, MathUtils::round_int(), CGraphicContext::ScaleFinalXCoord(), CGraphicContext::ScaleFinalYCoord(), CGraphicContext::ScaleFinalZCoord(), CRenderSystemBase::ScissorsCanEffectClipping(), MathUtils::truncate_int(), SVertex::u, SVertex::v, SVertex::x, CRectGen< T >::x1, CRectGen< T >::x2, CD3DHelper::XMStoreColor(), SVertex::y, CRectGen< T >::y1, CRectGen< T >::y2, and SVertex::z.
Referenced by DrawTextInternal().
SetGlyphStrength()
void CGUIFontTTF::SetGlyphStrength (FT_GlyphSlot slot, int glyphStrength) protected
References m_face.
Referenced by CacheCharacter().
Friends And Related Symbol Documentation
CGUIFont
friend class CGUIFont friend
Member Data Documentation
LOOKUPTABLE_SIZE
constexpr size_t CGUIFontTTF::LOOKUPTABLE_SIZE = MAX_GLYPH_IDX * FONT_STYLES_COUNT static constexpr private
Referenced by GetCharacter().
m_cellBaseLine
unsigned int CGUIFontTTF::m_cellBaseLine {0} protected
Referenced by CacheCharacter(), GetTextBaseLine(), and Load().
m_cellHeight
unsigned int CGUIFontTTF::m_cellHeight {0} protected
Referenced by DrawTextInternal(), GetTextHeight(), GetTextureLineHeight(), and Load().
m_char
std::vector<Character> CGUIFontTTF::m_char protected
Referenced by ClearCharacterCache(), and GetCharacter().
m_charquick
Character* CGUIFontTTF::m_charquick[LOOKUPTABLE_SIZE] {nullptr} protected
Referenced by Clear(), ClearCharacterCache(), and GetCharacter().
m_color
KODI::UTILS::COLOR::Color CGUIFontTTF::m_color {KODI::UTILS::COLOR::NONE} protected
Referenced by RenderCharacter().
m_dynamicCache
CGUIFontCache<CGUIFontCacheDynamicPosition, CGUIFontCacheDynamicValue> CGUIFontTTF::m_dynamicCache protected
Referenced by DrawTextInternal(), CGUIFontTTFDX::ReallocTexture(), CGUIFontTTFGL::ReallocTexture(), CGUIFontTTFGLES::ReallocTexture(), CGUIFontTTFGL::~CGUIFontTTFGL(), and CGUIFontTTFGLES::~CGUIFontTTFGLES().
m_ellipseCached
bool CGUIFontTTF::m_ellipseCached {false} protected
Referenced by DrawTextInternal().
m_ellipsesWidth
float CGUIFontTTF::m_ellipsesWidth {0.0f} protected
Referenced by DrawTextInternal().
m_face
FT_Face CGUIFontTTF::m_face {nullptr} protected
Referenced by CacheCharacter(), Clear(), GetCharacter(), GetLineHeight(), Load(), and SetGlyphStrength().
m_fontFileInMemory
std::vector<uint8_t> CGUIFontTTF::m_fontFileInMemory protected
Referenced by Clear(), and Load().
m_fontIdent
const std::string CGUIFontTTF::m_fontIdent protected
Referenced by GetFontIdent().
m_hbFont
hb_font_t* CGUIFontTTF::m_hbFont {nullptr} protected
Referenced by Clear(), GetHarfBuzzShapedGlyphs(), and Load().
m_height
float CGUIFontTTF::m_height {0.0f} protected
Referenced by GetFontHeight(), Load(), CGUIFontTTFGL::ReallocTexture(), and CGUIFontTTFGLES::ReallocTexture().
m_maxFontHeight
unsigned int CGUIFontTTF::m_maxFontHeight {0} protected
Referenced by CacheCharacter(), and GetMaxFontHeight().
m_nestedBeginCount
unsigned int CGUIFontTTF::m_nestedBeginCount {0} protected
Referenced by Begin(), Clear(), End(), and GetCharacter().
m_nTexture
unsigned int CGUIFontTTF::m_nTexture {0} protected
Referenced by CGUIFontTTFGL::DeleteHardwareTexture(), CGUIFontTTFGLES::DeleteHardwareTexture(), CGUIFontTTFGL::FirstBegin(), and CGUIFontTTFGLES::FirstBegin().
m_originX
float CGUIFontTTF::m_originX {0.0f} protected
Referenced by DrawTextInternal(), and RenderCharacter().
m_originY
float CGUIFontTTF::m_originY {0.0f} protected
Referenced by DrawTextInternal(), and RenderCharacter().
m_posX
int CGUIFontTTF::m_posX {0} protected
Referenced by CacheCharacter(), Clear(), ClearCharacterCache(), and Load().
m_posY
int CGUIFontTTF::m_posY {0} protected
Referenced by CacheCharacter(), Clear(), ClearCharacterCache(), and Load().
m_referenceCount
int CGUIFontTTF::m_referenceCount {0} private
Referenced by AddReference(), and RemoveReference().
m_renderSystem
CRenderSystemBase* CGUIFontTTF::m_renderSystem protected
Referenced by CacheCharacter(), DrawTextInternal(), Load(), and RenderCharacter().
m_staticCache
CGUIFontCache<CGUIFontCacheStaticPosition, CGUIFontCacheStaticValue> CGUIFontTTF::m_staticCache protected
Referenced by DrawTextInternal(), CGUIFontTTFDX::ReallocTexture(), CGUIFontTTFGL::ReallocTexture(), and CGUIFontTTFGLES::ReallocTexture().
m_stroker
FT_Stroker CGUIFontTTF::m_stroker {nullptr} protected
Referenced by CacheCharacter(), Clear(), and Load().
m_texture
std::unique_ptr<CTexture> CGUIFontTTF::m_texture protected
Referenced by Begin(), CacheCharacter(), Clear(), ClearCharacterCache(), CGUIFontTTFGL::CopyCharToTexture(), CGUIFontTTFGLES::CopyCharToTexture(), CGUIFontTTFGL::FirstBegin(), CGUIFontTTFGLES::FirstBegin(), Load(), CGUIFontTTFDX::ReallocTexture(), CGUIFontTTFGL::ReallocTexture(), and CGUIFontTTFGLES::ReallocTexture().
m_textureHeight
unsigned int CGUIFontTTF::m_textureHeight {0} protected
Referenced by CacheCharacter(), ClearCharacterCache(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), Load(), CGUIFontTTFDX::ReallocTexture(), CGUIFontTTFGL::ReallocTexture(), and CGUIFontTTFGLES::ReallocTexture().
m_textureScaleX
float CGUIFontTTF::m_textureScaleX {0.0f} protected
Referenced by Load(), CGUIFontTTFGL::ReallocTexture(), CGUIFontTTFGLES::ReallocTexture(), and RenderCharacter().
m_textureScaleY
float CGUIFontTTF::m_textureScaleY {0.0f} protected
Referenced by CGUIFontTTFDX::ReallocTexture(), CGUIFontTTFGL::ReallocTexture(), CGUIFontTTFGLES::ReallocTexture(), and RenderCharacter().
m_textureWidth
unsigned int CGUIFontTTF::m_textureWidth {0} protected
Referenced by CacheCharacter(), ClearCharacterCache(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), Load(), CGUIFontTTFDX::ReallocTexture(), CGUIFontTTFGL::ReallocTexture(), and CGUIFontTTFGLES::ReallocTexture().
m_vertex
std::vector<SVertex> CGUIFontTTF::m_vertex protected
Referenced by Begin(), Clear(), DrawTextInternal(), CGUIFontTTFDX::LastEnd(), CGUIFontTTFGL::LastEnd(), and CGUIFontTTFGLES::LastEnd().
m_vertexTrans
std::vector<CTranslatedVertices> CGUIFontTTF::m_vertexTrans protected
Referenced by Begin(), Clear(), DrawTextInternal(), CGUIFontTTFDX::LastEnd(), CGUIFontTTFGL::LastEnd(), and CGUIFontTTFGLES::LastEnd().
MAX_GLYPH_IDX
constexpr int CGUIFontTTF::MAX_GLYPH_IDX = 4096 static constexpr private
Referenced by GetCharacter().
The documentation for this class was generated from the following files:
GUIFontTTF.h
GUIFontTTF.cpp
GUIFontTTFDX.cpp
GUIFontTTFGL.cpp
GUIFontTTFGLES.cpp