Kodi Documentation: CGUIListItem Class Reference
CGUIListItem Class Reference
Guilib classes » Window Reference » Controls
#include <GUIListItem.h>
Classes
struct icompare
Public Types
enum GUIIconOverlay {
ICON_OVERLAY_NONE = 0 , ICON_OVERLAY_RAR , ICON_OVERLAY_ZIP , ICON_OVERLAY_LOCKED ,
ICON_OVERLAY_UNWATCHED , ICON_OVERLAY_WATCHED , ICON_OVERLAY_HD
}
typedef std::map< std::string, std::string > ArtMap
Public Member Functions
CGUIListItem (void)
CGUIListItem (const CGUIListItem &item)
CGUIListItem (const std::string &strLabel)
virtual ~CGUIListItem (void)
virtual CGUIListItem * Clone () const
CGUIListItem & operator= (const CGUIListItem &item)
virtual void SetLabel (const std::string &strLabel)
const std::string & GetLabel () const
void SetLabel2 (const std::string &strLabel)
const std::string & GetLabel2 () const
void SetOverlayImage (GUIIconOverlay icon)
std::string GetOverlayImage () const
void SetArt (const std::string &type, const std::string &url)
Set a particular art type for an item.
void SetArt (const ArtMap &art)
set artwork for an item
void AppendArt (const ArtMap &art, const std::string &prefix="")
append artwork to an item
void SetArtFallback (const std::string &from, const std::string &to)
set a fallback image for art
void ClearArt ()
clear art on an item
std::string GetArt (const std::string &type) const
Get a particular art type for an item.
const ArtMap & GetArt () const
get artwork for an item Retrieves artwork in a type:url map
bool HasArt (const std::string &type) const
Check whether an item has a particular piece of art Equivalent to !GetArt(type).empty()
void SetSortLabel (const std::string &label)
void SetSortLabel (const std::wstring &label)
const std::wstring & GetSortLabel () const
void Select (bool bOnOff)
bool IsSelected () const
bool HasOverlay () const
virtual bool IsFileItem () const
void SetLayout (std::unique_ptr< CGUIListItemLayout > layout)
CGUIListItemLayout * GetLayout ()
void SetFocusedLayout (std::unique_ptr< CGUIListItemLayout > layout)
CGUIListItemLayout * GetFocusedLayout ()
void FreeIcons ()
void FreeMemory (bool immediately=false)
void SetInvalid ()
void SetProperty (const std::string &strKey, const CVariant &value)
void IncrementProperty (const std::string &strKey, int nVal)
void IncrementProperty (const std::string &strKey, int64_t nVal)
void IncrementProperty (const std::string &strKey, double dVal)
void ClearProperties ()
void AppendProperties (const CGUIListItem &item)
Append the properties of one CGUIListItem to another. Any existing properties in the current item will be overridden if they are set in the passed in item.
void Archive (CArchive &ar)
void Serialize (CVariant &value)
bool HasProperty (const std::string &strKey) const
bool HasProperties () const
void ClearProperty (const std::string &strKey)
const CVariant & GetProperty (const std::string &strKey) const
void SetCurrentItem (unsigned int position)
Set the current item number within it's container Our container classes will set this member with the items position in the container starting at 1.
unsigned int GetCurrentItem () const
Get the current item number within it's container Retrieve the items position in a container, this is useful to show for example numbering in front of entities in an arbitrary list of entities, like songs of a playlist.
Public Attributes
bool m_bIsFolder
is item a folder or a file
Protected Types
typedef std::map< std::string, CVariant, icompare > PropertyMap
Protected Attributes
std::string m_strLabel2
GUIIconOverlay m_overlayIcon
std::unique_ptr< CGUIListItemLayout > m_layout
std::unique_ptr< CGUIListItemLayout > m_focusedLayout
bool m_bSelected
unsigned int m_currentItem
PropertyMap m_mapProperties
Private Attributes
std::wstring m_sortLabel
std::string m_strLabel
ArtMap m_art
ArtMap m_artFallbacks
Member Typedef Documentation
ArtMap
typedef std::map<std::string, std::string> CGUIListItem::ArtMap
PropertyMap
typedef std::map<std::string, CVariant, icompare> CGUIListItem::PropertyMap protected
Constructor & Destructor Documentation
CGUIListItem() [1/3]
CGUIListItem::CGUIListItem (void)
References ICON_OVERLAY_NONE, m_bIsFolder, m_bSelected, m_currentItem, and m_overlayIcon.
Referenced by Clone().
CGUIListItem() [2/3]
CGUIListItem::CGUIListItem (const CGUIListItem & item) explicit
References SetInvalid().
CGUIListItem() [3/3]
CGUIListItem::CGUIListItem (const std::string & strLabel) explicit
References ICON_OVERLAY_NONE, m_bIsFolder, m_bSelected, m_currentItem, m_overlayIcon, and SetSortLabel().
~CGUIListItem()
CGUIListItem::~CGUIListItem (void) virtual
References FreeMemory().
Member Function Documentation
AppendArt()
void CGUIListItem::AppendArt (const ArtMap & art, const std::string & prefix = "")
append artwork to an item
Parameters
art a type:url map for artwork
prefix a prefix for the art, if applicable.
See also
GetArt
References SetArt().
Referenced by CMusicThumbLoader::FillLibraryArt(), CVideoThumbLoader::FillLibraryArt(), CGUIWindowVideoNav::GetDirectory(), CVideoDatabase::ImportFromXML(), CVideoThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), and CFileItem::MergeInfo().
AppendProperties()
void CGUIListItem::AppendProperties (const CGUIListItem & item)
Append the properties of one CGUIListItem to another. Any existing properties in the current item will be overridden if they are set in the passed in item.
Parameters
item the item containing the properties to append.
References m_mapProperties, and SetProperty().
Referenced by CFileItem::MergeInfo(), and CFileItem::UpdateInfo().
Archive()
void CGUIListItem::Archive (CArchive & ar)
References CArchive::IsStoring(), m_art, m_artFallbacks, m_bIsFolder, m_bSelected, m_mapProperties, m_overlayIcon, m_sortLabel, m_strLabel, m_strLabel2, SetInvalid(), SetProperty(), and value.
Referenced by CFileItem::Archive().
ClearArt()
void CGUIListItem::ClearArt ()
clear art on an item
See also
SetArt
References m_art, m_artFallbacks, and SetProperty().
Referenced by FreeIcons(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), and CGUIWindowVideoBase::OnItemInfo().
ClearProperties()
void CGUIListItem::ClearProperties ()
References m_mapProperties, and SetInvalid().
Referenced by XFILE::CAddonsDirectory::GetDirectory(), XFILE::CEventsDirectory::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), and CFileItem::Reset().
ClearProperty()
void CGUIListItem::ClearProperty (const std::string & strKey)
References CVariant::erase(), m_mapProperties, and SetInvalid().
Referenced by CSaveFileState::DoWork(), CApplication::PlayFile(), and CApplication::PlayStack().
Clone()
virtual CGUIListItem * CGUIListItem::Clone () const inline virtual
Reimplemented in CFileItem, and CGUIStaticItem.
References CGUIListItem().
FreeIcons()
void CGUIListItem::FreeIcons ()
References ClearArt(), FreeMemory(), and SetInvalid().
Referenced by CFileItem::Reset().
FreeMemory()
void CGUIListItem::FreeMemory (bool immediately = false)
References m_focusedLayout, and m_layout.
Referenced by CFileItemList::ClearItems(), FreeIcons(), CFileItem::operator=(), operator=(), and ~CGUIListItem().
GetArt() [1/2]
const CGUIListItem::ArtMap & CGUIListItem::GetArt () const
get artwork for an item Retrieves artwork in a type:url map
Returns
a type:url map for artwork
See also
SetArt
References m_art.
Referenced by HasArt(), and CFileItem::SetFromMusicInfoTag().
GetArt() [2/2]
std::string CGUIListItem::GetArt (const std::string & type) const
Get a particular art type for an item.
Parameters
type type of art to fetch.
Returns
the art URL, if available, else empty.
References m_art, and m_artFallbacks.
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), UPNP::BuildObject(), FAVOURITES_UTILS::ChooseAndSetNewThumbnail(), PVR::CPVRThumbLoader::ClearCachedImage(), CVideoTagLoaderPlugin::CVideoTagLoaderPlugin(), MUSIC_UTILS::FillArtTypesList(), KODI::ART::FillInDefaultIcon(), CVideoThumbLoader::FillLibraryArt(), CProgramThumbLoader::FillThumb(), ADDON::FromFileItem< CMusicAlbumInfo >(), ContentUtils::GeneratePlayableTrailerItem(), JSONRPC::CAudioLibrary::GetAlbums(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), XFILE::CRSSDirectory::GetDirectory(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), UPNP::CUPnPRenderer::GetMetadata(), CGUIInfoManager::GetMultiInfoItemLabel(), CGUIWindowSlideShow::GetPicturePath(), ContentUtils::GetPreferredArtImage(), JSONRPC::CAudioLibrary::GetSongs(), CFileItem::GetThumbHideIfUnwatched(), CVideoDatabase::ImportFromXML(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::InitCurrentItem(), PVR::CPVRChannelGroupImageFileLoader::Load(), CPictureThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), CFileItem::MergeInfo(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSongInfo::OnGetArt(), TEST_P(), and CFileItem::UpdateInfo().
GetCurrentItem()
unsigned int CGUIListItem::GetCurrentItem () const
Get the current item number within it's container Retrieve the items position in a container, this is useful to show for example numbering in front of entities in an arbitrary list of entities, like songs of a playlist.
References m_currentItem.
Referenced by CGUIInfoManager::GetMultiInfoItemLabel(), and KODI::GAME::CGUIGameControllerList::UpdateInfo().
GetFocusedLayout()
CGUIListItemLayout * CGUIListItem::GetFocusedLayout ()
References m_focusedLayout.
Referenced by PVR::CGUIEPGGridContainer::AssignItemDepth(), CGUIBaseContainer::RenderItem(), and PVR::CGUIEPGGridContainer::RenderItem().
GetLabel()
const std::string & CGUIListItem::GetLabel () const
References m_strLabel.
Referenced by CFavouritesService::AddOrRemove(), CFileItemList::Assign(), UPNP::BuildObject(), FAVOURITES_UTILS::ChooseAndSetNewName(), CFileItem::CleanString(), PVR::CPVRGUIActionsRecordings::ConfirmDeleteRecording(), PVR::CPVRGUIActionsRecordings::ConfirmDeleteWatchedRecordings(), PVR::CPVRGUIActionsEPG::DeleteSavedSearch(), ADDON::DetailsFromFileItem< CAlbum >(), ADDON::DetailsFromFileItem< CArtist >(), CBlurayCallback::dir_read(), dll_findfirst64i32(), dll_findnext64i32(), dll_readdir(), CGUIDialogSubtitles::Download(), CVideoThumbLoader::FillLibraryArt(), ADDON::FromFileItem< CMusicAlbumInfo >(), ADDON::FromFileItem< CMusicArtistInfo >(), ADDON::FromFileItem< CScraperUrl >(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectory(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowPictures::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CGUIWindowFileManager::GetDirectoryHistoryString(), CGUIMediaWindow::GetDirectoryHistoryString(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetFallbackLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetFallbackLabel(), JSONRPC::CVideoLibrary::GetGenres(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel(), CLabelFormatter::GetMaskContent(), CFileItem::GetMovieName(), CGUIInfoManager::GetMultiInfoItemLabel(), CGUIDialogContextMenu::GetShare(), JSONRPC::CVideoLibrary::GetTags(), KODI::CDRIP::CCDDARipper::GetTrackName(), CGUIPassword::IsItemUnlocked(), CFileItem::MergeInfo(), CGUIDialogFileBrowser::OnEditMediaSource(), CGUIWindowMusicPlayList::OnItemLoaded(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), CApplication::PlayMedia(), CMediaManager::playStubFile(), CFileItem::RemoveExtension(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), CFileItem::SetFromMusicInfoTag(), PERIPHERALS::CGUIDialogPeripheralSettings::SetupView(), anonymous_namespace{MusicUtils.cpp}::ShowToastNotification(), CFileItem::ToSortable(), CGUIMediaWindow::Update(), and CFileItem::UpdateInfo().
GetLabel2()
const std::string & CGUIListItem::GetLabel2 () const
References m_strLabel2.
Referenced by CGUIInfoManager::GetMultiInfoItemLabel(), CFileItem::MergeInfo(), and CFileItem::UpdateInfo().
GetLayout()
CGUIListItemLayout * CGUIListItem::GetLayout ()
References m_layout.
Referenced by PVR::CGUIEPGGridContainer::AssignItemDepth(), CGUIBaseContainer::RenderItem(), and PVR::CGUIEPGGridContainer::RenderItem().
GetOverlayImage()
std::string CGUIListItem::GetOverlayImage () const
References ICON_OVERLAY_HD, ICON_OVERLAY_LOCKED, ICON_OVERLAY_RAR, ICON_OVERLAY_UNWATCHED, ICON_OVERLAY_WATCHED, ICON_OVERLAY_ZIP, and m_overlayIcon.
Referenced by CGUIInfoManager::GetMultiInfoItemLabel(), and TEST_P().
GetProperty()
const CVariant & CGUIListItem::GetProperty (const std::string & strKey) const
References m_mapProperties, and CVariant::VariantTypeNull.
Referenced by CGUIViewState::AddPlaylistOrder(), CExecString::BuildPlayMedia(), CDVDInputStream::CDVDInputStream(), CDVDFactoryInputStream::CreateInputStream(), XFILE::DependencyAddons(), ADDON::DetailsFromFileItem< CAlbum >(), ADDON::DetailsFromFileItem< CArtist >(), CDirectoryJob::DoWork(), CSaveFileState::DoWork(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), CVideoThumbLoader::FillLibraryArt(), ADDON::FromArray(), ADDON::FromFileItem< CMusicAlbumInfo >(), ADDON::FromFileItem< CMusicArtistInfo >(), ADDON::FromFileItem< CScraperUrl >(), ADDON::FromString(), CGUIMediaWindow::GetAdvanceFilteredItems(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectory(), CGUIWindowAddonBrowser::GetDirectory(), CMusicDatabase::GetDiscsCount(), ADDON::CScraper::GetEpisodeList(), CGUIWindowVideoBase::GetGroupedItems(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CLabelFormatter::GetMaskContent(), CGUIInfoManager::GetMultiInfoBool(), CGUIInfoManager::GetMultiInfoInt(), CGUIInfoManager::GetMultiInfoItemLabel(), anonymous_namespace{MusicUtils.cpp}::GetMusicDbItemPath(), PVR::CPVRPlaybackState::GetNextAutoplayItem(), CPlayerCoreFactory::GetPlayers(), XFILE::CPluginDirectory::GetPluginResult(), KODI::GAME::CDialogGameVideoFilter::GetProperties(), CDVDInputStream::GetProperty(), CDVDInputStreamFFmpeg::GetProxyHost(), CDVDInputStreamFFmpeg::GetProxyPassword(), CDVDInputStreamFFmpeg::GetProxyPort(), CDVDInputStreamFFmpeg::GetProxyType(), CDVDInputStreamFFmpeg::GetProxyUser(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), XFILE::CPluginDirectory::GetResolvedPluginResult(), CDirectoryProvider::GetTarget(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::GetTargetWindowID(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::GetVideoDbItemPath(), JSONRPC::CVideoLibrary::HandleItems(), IncrementProperty(), IncrementProperty(), IncrementProperty(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), CPlayerUtils::IsItemPlayable(), CFileItem::IsLibraryFolder(), CFileItem::IsResumable(), CFileItem::IsSamePath(), KODI::PLAYLIST::IsSmartPlayList(), CONTEXTMENU::CAddRemoveFavourite::IsVisible(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CMusicThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), CGUIWindowVideoBase::LoadVideoInfo(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CGUIMediaWindow::OnFilterItems(), KODI::GAME::CDialogGameSaves::OnFocus(), KODI::GAME::CDialogInGameSaves::OnOverwrite(), CInputStreamAddon::Open(), CVideoPlayer::OpenInputStream(), ParseItem(), CApplication::PlayFile(), CApplication::PlayMedia(), PVR::CPVRGUIActionsPlayback::PlayMedia(), PVR::CPVRGUIActionsPlayback::PlayRecording(), CApplication::PlayStack(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), UPNP::CMediaBrowser::SaveFileState(), CVideoDatabase::SetPlayCount(), CMusicDatabase::SetPropertiesForFileItem(), CGUIDialogMusicInfo::ShowFor(), CGUIDialogSimpleMenu::ShowPlaySelection(), CGUIMediaWindow::SortItems(), CInputStreamAddon::Supports(), CFileItem::ToSortable(), CGUIMediaWindow::UpdateFilterPath(), KODI::GAME::CGUIGameControllerList::UpdateInfo(), and KODI::GAME::CGUIGameController::UpdateInfo().
GetSortLabel()
const std::wstring & CGUIListItem::GetSortLabel () const
References m_sortLabel.
Referenced by CGUIInfoManager::GetMultiInfoItemLabel().
HasArt()
bool CGUIListItem::HasArt (const std::string & type) const
Check whether an item has a particular piece of art Equivalent to !GetArt(type).empty()
Parameters
type type of art to set.
Returns
true if the item has that art set, false otherwise.
References GetArt().
Referenced by FAVOURITES_UTILS::ChooseAndSetNewThumbnail(), MUSIC_UTILS::FillArtTypesList(), CVideoThumbLoader::FillLibraryArt(), CVideoThumbLoader::FillThumb(), CMusicThumbLoader::FillThumb(), JSONRPC::CAudioLibrary::GetAlbums(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), XFILE::CRSSDirectory::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), ContentUtils::GetPreferredArtImage(), JSONRPC::CAudioLibrary::GetSongs(), CFileItem::GetThumbHideIfUnwatched(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::InitCurrentItem(), CMusicThumbLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), CMusicThumbLoader::LoadItemLookup(), CVideoThumbLoader::LoadItemLookup(), and CPictureThumbLoader::ProcessFoldersAndArchives().
HasOverlay()
bool CGUIListItem::HasOverlay () const
References ICON_OVERLAY_NONE, and m_overlayIcon.
Referenced by KODI::ART::FillInDefaultIcon().
HasProperties()
bool CGUIListItem::HasProperties () const inline
References m_mapProperties.
HasProperty()
bool CGUIListItem::HasProperty (const std::string & strKey) const
References m_mapProperties.
Referenced by CGUIViewState::AddPlaylistOrder(), CExecString::BuildPlayMedia(), CDirectoryJob::DoWork(), CSaveFileState::DoWork(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), KODI::ART::FillInDefaultIcon(), ADDON::FromFileItem< CMusicAlbumInfo >(), ADDON::FromFileItem< CMusicArtistInfo >(), ADDON::FromFileItem< CScraperUrl >(), CGUIMediaWindow::GetAdvanceFilteredItems(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), XFILE::CVideoDatabaseDirectory::GetDirectory(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), CGUIWindowVideoBase::GetGroupedItems(), CLabelFormatter::GetMaskContent(), CGUIInfoManager::GetMultiInfoBool(), CGUIInfoManager::GetMultiInfoInt(), CGUIWindowSlideShow::GetPicturePath(), XFILE::CPluginDirectory::GetPluginResult(), CDVDInputStreamFFmpeg::GetProxyHost(), CDVDInputStreamFFmpeg::GetProxyPassword(), CDVDInputStreamFFmpeg::GetProxyPort(), CDVDInputStreamFFmpeg::GetProxyType(), CDVDInputStreamFFmpeg::GetProxyUser(), XFILE::CPluginDirectory::GetResolvedPluginResult(), JSONRPC::CVideoLibrary::HandleItems(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), KODI::NETWORK::IsInternetStream(), CFileItem::IsLibraryFolder(), CFileItem::IsResumable(), CFileItem::IsSamePath(), CONTEXTMENU::CMusicInfo::IsVisible(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadRecordingFileOrFolderItem(), KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::Modify(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CGUIMediaWindow::OnFilterItems(), CGUIWindowVideoBase::OnItemInfo(), CVideoPlayer::OpenInputStream(), ParseItem(), CApplication::PlayFile(), CApplication::PlayMedia(), PVR::CPVRGUIActionsPlayback::PlayMedia(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CApplication::PlayStack(), CVideoDatabase::SetPlayCount(), CMusicDatabase::SetPropertiesForFileItem(), CGUIDialogMusicInfo::ShowFor(), CGUIDialogSimpleMenu::ShowPlaySelection(), CGUIMediaWindow::SortItems(), CGUIMediaWindow::UpdateFilterPath(), and KODI::GAME::CGUIGameController::UpdateInfo().
IncrementProperty() [1/3]
void CGUIListItem::IncrementProperty (const std::string & strKey, double dVal)
References CVariant::asDouble(), GetProperty(), and SetProperty().
IncrementProperty() [2/3]
void CGUIListItem::IncrementProperty (const std::string & strKey, int nVal)
References CVariant::asInteger(), GetProperty(), int64_t(), and SetProperty().
Referenced by PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo().
IncrementProperty() [3/3]
void CGUIListItem::IncrementProperty (const std::string & strKey, int64_t nVal)
References CVariant::asInteger(), GetProperty(), int64_t(), and SetProperty().
IsFileItem()
virtual bool CGUIListItem::IsFileItem () const inline virtual
Reimplemented in CFileItem.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), PVR::CPVRGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetInt(), PVR::CPVRGUIInfo::GetInt(), CGUIInfoManager::GetItemBool(), CGUIInfoManager::GetItemImage(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetItemLabel(), CGUIInfoManager::GetMultiInfoBool(), CGUIListItemLayout::Process(), KODI::GUILIB::GUIINFO::CGUIInfoColor::Update(), and CGUIBaseContainer::UpdateListProvider().
IsSelected()
bool CGUIListItem::IsSelected () const
References m_bSelected.
Referenced by CGUIInfoManager::GetItemBool(), CFileOperationJob::operator==(), and CGUIListItemLayout::Process().
operator=()
CGUIListItem & CGUIListItem::operator= (const CGUIListItem & item)
References FreeMemory(), m_art, m_artFallbacks, m_bIsFolder, m_bSelected, m_mapProperties, m_overlayIcon, m_sortLabel, m_strLabel, m_strLabel2, and SetInvalid().
Referenced by CFileItem::operator=().
Select()
void CGUIListItem::Select (bool bOnOff)
References m_bSelected.
Referenced by CGUIDialogAddonInfo::AskForVersion(), CFileOperationJob::DoProcessFolder(), and anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DownloadPackage().
Serialize()
void CGUIListItem::Serialize (CVariant & value)
References m_art, m_bIsFolder, m_bSelected, m_mapProperties, m_sortLabel, m_strLabel, m_strLabel2, and value.
SetArt() [1/2]
void CGUIListItem::SetArt (const ArtMap & art)
set artwork for an item
Parameters
art a type:url map for artwork
See also
GetArt
References m_art, and SetInvalid().
SetArt() [2/2]
void CGUIListItem::SetArt (const std::string & type, const std::string & url)
Set a particular art type for an item.
Parameters
type type of art to set.
url the url of the art.
References m_art, and SetInvalid().
Referenced by JSONRPC::CFavouritesOperations::AddFavourite(), KODI::GAME::CGUIActivePortList::AddInputDisabled(), AppendArt(), CGUIDialogAddonInfo::AskForVersion(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CGUIStaticItem::CGUIStaticItem(), FAVOURITES_UTILS::ChooseAndSetNewThumbnail(), PVR::CPVRGUIActionsEPG::ChooseIconForSavedSearch(), PVR::CPVRThumbLoader::ClearCachedImage(), CDirectoryJob::DoWork(), KODI::ART::FillInDefaultIcon(), CVideoThumbLoader::FillLibraryArt(), PVR::CPVRThumbLoader::FillThumb(), CProgramThumbLoader::FillThumb(), CVideoThumbLoader::FillThumb(), CMusicThumbLoader::FillThumb(), CVideoDatabase::GetActorsNav(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CGUIWindowMusicBase::GetDirectory(), UPNP::GetResource(), KODI::RETRO::CSavestateDatabase::GetSavestateItem(), CVideoDatabase::ImportFromXML(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::InitCurrentItem(), KODI::GAME::CGameClientProperties::InstallDependencies(), CMusicThumbLoader::LoadItemCached(), CPictureInfoLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CMusicThumbLoader::LoadItemLookup(), CVideoThumbLoader::LoadItemLookup(), CFileItem::MergeInfo(), ParseItemBoxee(), ParseItemItunes(), ParseItemMRSS(), ParseItemVoddler(), CPictureThumbLoader::ProcessFoldersAndArchives(), CGUIInfoManager::SetCurrentAlbumThumb(), CFileItem::SetFromAlbum(), CFileItem::SetFromMusicInfoTag(), CFileItem::SetFromSong(), TEST_P(), CGUIWindowPictures::Update(), CFileItem::UpdateInfo(), and CGUIStaticItem::UpdateProperties().
SetArtFallback()
void CGUIListItem::SetArtFallback (const std::string & from, const std::string & to)
set a fallback image for art
Parameters
from the type to fallback from
to the type to fallback to
See also
SetArt
References m_artFallbacks.
Referenced by CMusicThumbLoader::FillLibraryArt(), CVideoThumbLoader::FillLibraryArt(), and CGUIWindowVideoNav::GetDirectory().
SetCurrentItem()
void CGUIListItem::SetCurrentItem (unsigned int position)
Set the current item number within it's container Our container classes will set this member with the items position in the container starting at 1.
Parameters
position Position of the item in the container starting at 1.
References m_currentItem.
SetFocusedLayout()
void CGUIListItem::SetFocusedLayout (std::unique_ptr< CGUIListItemLayout > layout)
References m_focusedLayout.
SetInvalid()
void CGUIListItem::SetInvalid ()
References m_focusedLayout, m_layout, and CGUIListItemLayout::SetInvalid().
Referenced by Archive(), CFileItem::Archive(), CGUIListItem(), ClearProperties(), ClearProperty(), FreeIcons(), CVideoThumbLoader::LoadItemCached(), CFileItem::MergeInfo(), operator=(), CFileItem::Reset(), SetArt(), SetArt(), SetLabel(), SetLabel2(), SetOverlayImage(), SetProperty(), and CFileItem::UpdateInfo().
SetLabel()
void CGUIListItem::SetLabel (const std::string & strLabel) virtual
Reimplemented in CFileItem.
References m_sortLabel, m_strLabel, SetInvalid(), and SetSortLabel().
Referenced by CFileItem::SetLabel().
SetLabel2()
void CGUIListItem::SetLabel2 (const std::string & strLabel)
References m_strLabel2, and SetInvalid().
Referenced by CGUIDialogAddonInfo::AskForVersion(), CGUIStaticItem::CGUIStaticItem(), CLabelFormatter::FormatLabel2(), KODI::RETRO::CSavestateDatabase::GetSavestateItem(), CGUIDialogColorPicker::LoadColors(), CFileItem::MergeInfo(), CGUIWindowMusicPlayList::OnItemLoaded(), ParseItem(), CFileItem::SetFileSizeLabel(), CFileItem::UpdateInfo(), and CGUIStaticItem::UpdateProperties().
SetLayout()
void CGUIListItem::SetLayout (std::unique_ptr< CGUIListItemLayout > layout)
References m_layout.
SetOverlayImage()
void CGUIListItem::SetOverlayImage (GUIIconOverlay icon)
References m_overlayIcon, and SetInvalid().
Referenced by CSaveFileState::DoWork(), KODI::ART::FillInDefaultIcon(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), CFileItem::MergeInfo(), and CFileItem::UpdateInfo().
SetProperty()
void CGUIListItem::SetProperty (const std::string & strKey, const CVariant & value)
References m_mapProperties, SetInvalid(), and value.
Referenced by CVideoFileItemListModifier::AddQueuingFolder(), AppendProperties(), Archive(), XFILE::Browse(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CGUIStaticItem::CGUIStaticItem(), ClearArt(), XFILE::DependencyAddons(), CVideoThumbLoader::DetectAndAddMissingItemData(), CDirectoryJob::DoWork(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), CMusicThumbLoader::FillLibraryArt(), CVideoThumbLoader::FillLibraryArt(), MUSIC_INFO::CMusicInfoScanner::FindArtForAlbums(), XFILE::GenerateCategoryListing(), CGUIMediaWindow::GetAdvanceFilteredItems(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetArtistsByAlbum(), CMusicDatabase::GetArtistsByWhere(), CVideoDatabase::GetDetailsForTvShow(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), JSONRPC::CFileOperations::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CMusicDatabase::GetDiscsByWhere(), CVideoDatabase::GetEpisodesByWhere(), CMusicDatabase::GetFileItemFromArtistCredits(), CMusicDatabase::GetFileItemFromDataset(), CMusicDatabase::GetGenresByAlbum(), CMusicDatabase::GetGenresByArtist(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetIsAlbumArtist(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideosByWhere(), CGUIWindowSlideShow::GetPicturePath(), XFILE::CPluginDirectory::GetPluginResult(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), UPNP::GetResource(), CMusicDatabase::GetRolesByArtist(), KODI::RETRO::CSavestateDatabase::GetSavestateItem(), CVideoDatabase::GetSeasonsByWhere(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsFullByWhere(), CMusicDatabase::GetSources(), CMusicDatabase::GetSourcesByAlbum(), CMusicDatabase::GetSourcesByArtist(), CMusicDatabase::GetSourcesBySong(), CVideoDatabase::GetTvShowsByWhere(), IncrementProperty(), IncrementProperty(), IncrementProperty(), CFileItem::IsSamePath(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CGUIWindowVideoBase::LoadVideoInfo(), UPNP::CMediaBrowser::MarkWatched(), KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::Modify(), CGUIWindowVideoBase::OnItemInfo(), CGUIWindowFavourites::OnSelect(), JSONRPC::CPlayerOperations::Open(), ParseItem(), ParseItemBoxee(), ParseItemItunes(), ParseItemMRSS(), ParseItemRSS(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CApplication::PlayStack(), CAirPlayServer::CTCPClient::ProcessRequest(), ADDON::CGUIAddonWindow::SetContainerProperty(), CFileItem::SetFromSong(), CFileItem::SetFromVideoInfoTag(), CMusicDatabase::SetPropertiesFromAlbum(), CMusicDatabase::SetPropertiesFromArtist(), CGUIDialogSimpleMenu::ShowPlaySelection(), CGUIDialogSimpleMenu::ShowPlaySelection(), CFileItemList::Stack(), TEST(), TEST(), TEST_P(), and CGUIStaticItem::UpdateProperties().
SetSortLabel() [1/2]
void CGUIListItem::SetSortLabel (const std::string & label)
References g_charsetConverter, label, and m_sortLabel.
Referenced by CGUIListItem(), and SetLabel().
SetSortLabel() [2/2]
void CGUIListItem::SetSortLabel (const std::wstring & label)
References label, and m_sortLabel.
Member Data Documentation
m_art
ArtMap CGUIListItem::m_art private
Referenced by Archive(), ClearArt(), GetArt(), GetArt(), operator=(), Serialize(), SetArt(), and SetArt().
m_artFallbacks
ArtMap CGUIListItem::m_artFallbacks private
Referenced by Archive(), ClearArt(), GetArt(), operator=(), and SetArtFallback().
m_bIsFolder
bool CGUIListItem::m_bIsFolder
is item a folder or a file
Referenced by CFavouritesService::AddOrRemove(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), UPNP::BuildObject(), CDVDFileInfo::CanExtract(), CExecString::CExecString(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), CFileItem::CFileItem(), ADDON::CFileItemListToVFSDirEntries(), CGUIDialogFileBrowser::CGUIDialogFileBrowser(), CGUIListItem(), CGUIListItem(), CGUIWindowFileManager::CGUIWindowFileManager(), PVR::CPVRGUIActionsRecordings::ConfirmDeleteRecording(), XFILE::CFileDirectoryFactory::Create(), CVideoTagLoaderNFO::CVideoTagLoaderNFO(), PVR::CPVRGUIActionsRecordings::DeleteRecording(), PVR::CPVRGUIActionsRecordings::DeleteWatchedRecordings(), CVideoThumbLoader::DetectAndAddMissingItemData(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), CFileItem::Exists(), KODI::ART::FillInDefaultIcon(), CFileItem::FillInMimeType(), CFileItem::FindLocalArt(), CVideoTagLoaderNFO::FindNFO(), CLabelFormatter::FormatLabel(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CFileItem::GetBaseMoviePath(), XFILE::CDAVDirectory::GetDirectory(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), CGUIInfoManager::GetItemBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CVideoThumbLoader::GetLocalArt(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), CFileItem::GetLocalMetadataPath(), CProgramThumbLoader::GetLocalThumb(), CLabelFormatter::GetMaskContent(), CGUIInfoManager::GetMultiInfoItemLabel(), KODI::ART::GetTBNFile(), CFileItem::GetUserMusicThumb(), ADDON::CAddonInstaller::InstallFromZip(), KODI::VIDEO::IsDiscStub(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), CGUIPassword::IsItemUnlocked(), CFileItem::IsResumable(), KODI::VIDEO::IsVideo(), KODI::VIDEO::IsVideoAssetFile(), KODI::VIDEO::IsVideoExtrasFolder(), CFileItem::IsVirtualDirectoryRoot(), CONTEXTMENU::CMusicBrowse::IsVisible(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible(), CONTEXTMENU::CVideoRemoveResumePoint::IsVisible(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), CONTEXTMENU::CVideoBrowse::IsVisible(), CVideoTagLoaderNFO::Load(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), MUSIC_INFO::CMusicInfoLoader::LoadItemCached(), CVideoThumbLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CPictureInfoLoader::LoadItemLookup(), CVideoThumbLoader::LoadItemLookup(), KODI::GAME::CGUIWindowGames::OnClick(), CGUIWindowVideoBase::OnItemInfo(), CGUIWindowFileManager::OnMessage(), CGUIWindowVideoBase::OnSearchItemFound(), operator=(), CExecString::Parse(), ParseItem(), XFILE::CDAVDirectory::ParseResponse(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), PVR::CPVRGUIActionsPlayback::PlayRecording(), PVR::CPVRGUIActionsPlayback::PlayRecordingFolder(), CPictureThumbLoader::ProcessFoldersAndArchives(), CFileItem::RemoveExtension(), CFileItem::Reset(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), RunPlugin(), Serialize(), CFileItem::SetFileSizeLabel(), CFileItem::SetFromAlbum(), CFileItem::SetFromVideoInfoTag(), CFileItem::SetLabel(), CGUIDialogMusicInfo::ShowFor(), CGUIDialogSongInfo::ShowFor(), CFileItemList::StackFolders(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), CFileItem::ToSortable(), and CFilesystemInstaller::UnpackArchive().
m_bSelected
bool CGUIListItem::m_bSelected protected
Referenced by Archive(), CGUIListItem(), CGUIListItem(), IsSelected(), operator=(), CFileItem::Reset(), Select(), and Serialize().
m_currentItem
unsigned int CGUIListItem::m_currentItem protected
Referenced by CGUIListItem(), CGUIListItem(), GetCurrentItem(), and SetCurrentItem().
m_focusedLayout
std::unique_ptr<CGUIListItemLayout> CGUIListItem::m_focusedLayout protected
Referenced by FreeMemory(), GetFocusedLayout(), SetFocusedLayout(), and SetInvalid().
m_layout
std::unique_ptr<CGUIListItemLayout> CGUIListItem::m_layout protected
Referenced by FreeMemory(), GetLayout(), SetInvalid(), and SetLayout().
m_mapProperties
PropertyMap CGUIListItem::m_mapProperties protected
Referenced by AppendProperties(), Archive(), CFileItemList::Assign(), ClearProperties(), ClearProperty(), CFileItemList::Copy(), GetProperty(), HasProperties(), HasProperty(), operator=(), Serialize(), CFileItem::Serialize(), and SetProperty().
m_overlayIcon
GUIIconOverlay CGUIListItem::m_overlayIcon protected
Referenced by Archive(), CGUIListItem(), CGUIListItem(), GetOverlayImage(), HasOverlay(), operator=(), CFileItem::Reset(), and SetOverlayImage().
m_sortLabel
std::wstring CGUIListItem::m_sortLabel private
Referenced by Archive(), GetSortLabel(), operator=(), Serialize(), SetLabel(), SetSortLabel(), and SetSortLabel().
m_strLabel
std::string CGUIListItem::m_strLabel private
Referenced by Archive(), GetLabel(), operator=(), Serialize(), and SetLabel().
m_strLabel2
std::string CGUIListItem::m_strLabel2 protected
Referenced by Archive(), GetLabel2(), operator=(), CFileItem::Reset(), Serialize(), CFileItem::SetFromAlbum(), and SetLabel2().
The documentation for this class was generated from the following files:
GUIListItem.h
GUIListItem.cpp