Kodi Documentation: CAirTunesServer Class Reference
CAirTunesServer Class Reference
#include <AirTunesServer.h>
Classes
class AudioOutputFunctions
Public Member Functions
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
void RegisterActionListener (bool doRegister)
bool OnAction (const CAction &action) override
Handle a GUI action.
void Process () override
bool IsRAOPRunningInternal ()
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Public Member Functions inherited from KODI::ACTION::IActionListener
virtual ~IActionListener ()=default
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Static Public Member Functions
static void EnableActionProcessing (bool enable)
static bool StartServer (int port, bool nonlocal, bool usePassword, const std::string &password="")
static void StopServer (bool bWait)
static bool IsRunning ()
static void SetMetadataFromBuffer (const char *buffer, unsigned int size)
static void SetCoverArtFromBuffer (const char *buffer, unsigned int size)
static void SetupRemoteControl ()
static void FreeDACPRemote ()
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Private Member Functions
CAirTunesServer (int port, bool nonlocal)
~CAirTunesServer () override
bool Initialize (const std::string &password)
void Deinitialize ()
Static Private Member Functions
static void RefreshCoverArt (const char *outputFilename=NULL)
static void RefreshMetadata ()
static void ResetMetadata ()
static void InformPlayerAboutPlayTimes ()
Private Attributes
int m_port
raop_t * m_pRaop = nullptr
XFILE::CPipeFile * m_pPipe
Static Private Attributes
static CAirTunesServer * ServerInstance = NULL
static std::string m_macAddress
static CCriticalSection m_metadataLock
static std::string m_metadata [3]
static bool m_streamStarted = false
static CCriticalSection m_dacpLock
static CDACP * m_pDACP = NULL
static std::string m_dacp_id
static std::string m_active_remote_header
static CCriticalSection m_actionQueueLock
static std::list< CAction > m_actionQueue
static CEvent m_processActions
static int m_sampleRate = 44100
static unsigned int m_cachedStartTime = 0
static unsigned int m_cachedEndTime = 0
static unsigned int m_cachedCurrentTime = 0
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CAirTunesServer()
CAirTunesServer::CAirTunesServer (int port, bool nonlocal) private
References m_port, and m_pPipe.
~CAirTunesServer()
CAirTunesServer::~CAirTunesServer () override private
References m_pPipe.
Member Function Documentation
Announce()
void CAirTunesServer::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References ANNOUNCEMENT::CAnnouncementManager::ANNOUNCEMENT_SENDER, m_dacpLock, m_pDACP, m_streamStarted, CDACP::Pause(), CDACP::Play(), RefreshCoverArt(), RefreshMetadata(), and CDACP::Stop().
Deinitialize()
void CAirTunesServer::Deinitialize () private
References m_pRaop, and RegisterActionListener().
Referenced by Initialize(), and StopServer().
EnableActionProcessing()
void CAirTunesServer::EnableActionProcessing (bool enable) static
References RegisterActionListener(), and ServerInstance.
Referenced by CAirTunesServer::AudioOutputFunctions::audio_destroy(), and CAirTunesServer::AudioOutputFunctions::audio_init().
FreeDACPRemote()
void CAirTunesServer::FreeDACPRemote () static
References m_dacpLock, and m_pDACP.
Referenced by CAirTunesServer::AudioOutputFunctions::audio_destroy().
InformPlayerAboutPlayTimes()
void CAirTunesServer::InformPlayerAboutPlayTimes () static private
References CServiceBroker::GetAppComponents(), m_cachedCurrentTime, m_cachedEndTime, m_cachedStartTime, m_sampleRate, and CApplicationPlayer::SetTime().
Referenced by CAirTunesServer::AudioOutputFunctions::audio_process(), and CAirTunesServer::AudioOutputFunctions::audio_set_progress().
Initialize()
bool CAirTunesServer::Initialize (const std::string & password) private
References CAirTunesServer::AudioOutputFunctions::audio_destroy(), CAirTunesServer::AudioOutputFunctions::audio_init(), CAirTunesServer::AudioOutputFunctions::audio_process(), CAirTunesServer::AudioOutputFunctions::audio_remote_control_id(), CAirTunesServer::AudioOutputFunctions::audio_set_coverart(), CAirTunesServer::AudioOutputFunctions::audio_set_metadata(), CAirTunesServer::AudioOutputFunctions::audio_set_progress(), CAirTunesServer::AudioOutputFunctions::audio_set_volume(), Deinitialize(), CNetworkBase::GetFirstConnectedInterface(), CServiceBroker::GetLogging(), CNetworkInterface::GetMacAddressRaw(), CServiceBroker::GetNetwork(), LOGAIRTUNES, m_port, m_pPipe, m_pRaop, RSA_KEY, and shairplay_log().
Referenced by StartServer().
IsRAOPRunningInternal()
bool CAirTunesServer::IsRAOPRunningInternal ()
References m_pRaop.
Referenced by IsRunning().
IsRunning()
bool CAirTunesServer::IsRunning () static
References IsRAOPRunningInternal(), and ServerInstance.
Referenced by CNetworkServices::IsAirTunesServerRunning().
OnAction()
bool CAirTunesServer::OnAction (const CAction & action) override virtual
Handle a GUI action.
Parameters
action The GUI action
Returns
True if the action was handled, false otherwise
Implements KODI::ACTION::IActionListener.
References ACTION_MUTE, ACTION_NEXT_ITEM, ACTION_PREV_ITEM, ACTION_VOLUME_DOWN, ACTION_VOLUME_UP, m_actionQueue, m_actionQueueLock, m_processActions, and CEvent::Set().
Process()
void CAirTunesServer::Process (void) override virtual
Reimplemented from CThread.
References ACTION_MUTE, ACTION_NEXT_ITEM, ACTION_PREV_ITEM, ACTION_VOLUME_DOWN, ACTION_VOLUME_UP, m_actionQueue, m_actionQueueLock, CThread::m_bStop, m_dacpLock, m_pDACP, m_processActions, m_streamStarted, CDACP::NextItem(), CDACP::PrevItem(), SetupRemoteControl(), CDACP::ToggleMute(), CDACP::VolumeDown(), CDACP::VolumeUp(), and CEvent::Wait().
RefreshCoverArt()
void CAirTunesServer::RefreshCoverArt (const char * outputFilename = NULL) static private
References CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_REFRESH_THUMBS, m_metadataLock, CGUIInfoManager::SetCurrentAlbumThumb(), and TMP_COVERART_PATH_JPG.
Referenced by Announce(), ResetMetadata(), and SetCoverArtFromBuffer().
RefreshMetadata()
void CAirTunesServer::RefreshMetadata () static private
References CServiceBroker::GetAppMessenger(), CGUIInfoManager::GetCurrentSongTag(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), m_metadata, m_metadataLock, MUSIC_INFO::CMusicInfoTag::SetAlbum(), and TMSG_UPDATE_CURRENT_ITEM.
Referenced by Announce(), ResetMetadata(), and SetMetadataFromBuffer().
RegisterActionListener()
void CAirTunesServer::RegisterActionListener (bool doRegister)
References CThread::Create(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppComponents(), ANNOUNCEMENT::Player, CApplicationActionListeners::RegisterActionListener(), ServerInstance, and CThread::StopThread().
Referenced by Deinitialize(), and EnableActionProcessing().
ResetMetadata()
void CAirTunesServer::ResetMetadata () static private
References XFILE::CFile::Delete(), m_metadata, m_metadataLock, RefreshCoverArt(), RefreshMetadata(), TMP_COVERART_PATH_JPG, and TMP_COVERART_PATH_PNG.
Referenced by CAirTunesServer::AudioOutputFunctions::audio_init().
SetCoverArtFromBuffer()
void CAirTunesServer::SetCoverArtFromBuffer (const char * buffer, unsigned int size) static
References XFILE::CFile::Close(), IsJPEG(), m_metadataLock, XFILE::CFile::OpenForWrite(), RefreshCoverArt(), TMP_COVERART_PATH_JPG, TMP_COVERART_PATH_PNG, and XFILE::CFile::Write().
Referenced by CAirTunesServer::AudioOutputFunctions::audio_set_coverart().
SetMetadataFromBuffer()
void CAirTunesServer::SetMetadataFromBuffer (const char * buffer, unsigned int size) static
References decodeDMAP(), m_metadata, m_metadataLock, and RefreshMetadata().
Referenced by CAirTunesServer::AudioOutputFunctions::audio_set_metadata().
SetupRemoteControl()
void CAirTunesServer::SetupRemoteControl () static
References DACP_NAME_PREFIX, CZeroconfBrowser::GetFoundServices(), CZeroconfBrowser::GetInstance(), m_active_remote_header, m_dacp_id, m_dacpLock, m_pDACP, CZeroconfBrowser::ResolveService(), and ZEROCONF_DACP_SERVICE.
Referenced by Process().
StartServer()
bool CAirTunesServer::StartServer (int port, bool nonlocal, bool usePassword, const std::string & password = "") static
References CSysInfo::GetDeviceName(), CNetworkBase::GetFirstConnectedInterface(), CZeroconf::GetInstance(), CNetworkInterface::GetMacAddress(), CServiceBroker::GetNetwork(), Initialize(), m_macAddress, CZeroconf::PublishService(), ServerInstance, StopServer(), and success.
Referenced by CNetworkServices::StartAirTunesServer().
StopServer()
void CAirTunesServer::StopServer (bool bWait) static
References Deinitialize(), CZeroconf::GetInstance(), CZeroconf::RemoveService(), and ServerInstance.
Referenced by StartServer(), and CNetworkServices::StopAirTunesServer().
Member Data Documentation
m_actionQueue
std::list< CAction > CAirTunesServer::m_actionQueue static private
Referenced by OnAction(), and Process().
m_actionQueueLock
CCriticalSection CAirTunesServer::m_actionQueueLock static private
Referenced by OnAction(), and Process().
m_active_remote_header
std::string CAirTunesServer::m_active_remote_header static private
Referenced by CAirTunesServer::AudioOutputFunctions::audio_destroy(), CAirTunesServer::AudioOutputFunctions::audio_remote_control_id(), and SetupRemoteControl().
m_cachedCurrentTime
unsigned int CAirTunesServer::m_cachedCurrentTime = 0 static private
Referenced by CAirTunesServer::AudioOutputFunctions::audio_set_progress(), and InformPlayerAboutPlayTimes().
m_cachedEndTime
unsigned int CAirTunesServer::m_cachedEndTime = 0 static private
Referenced by CAirTunesServer::AudioOutputFunctions::audio_set_progress(), and InformPlayerAboutPlayTimes().
m_cachedStartTime
unsigned int CAirTunesServer::m_cachedStartTime = 0 static private
Referenced by CAirTunesServer::AudioOutputFunctions::audio_set_progress(), and InformPlayerAboutPlayTimes().
m_dacp_id
std::string CAirTunesServer::m_dacp_id static private
Referenced by CAirTunesServer::AudioOutputFunctions::audio_destroy(), CAirTunesServer::AudioOutputFunctions::audio_remote_control_id(), and SetupRemoteControl().
m_dacpLock
CCriticalSection CAirTunesServer::m_dacpLock static private
Referenced by Announce(), FreeDACPRemote(), Process(), and SetupRemoteControl().
m_macAddress
std::string CAirTunesServer::m_macAddress static private
Referenced by StartServer().
m_metadata
std::string CAirTunesServer::m_metadata static private
Referenced by RefreshMetadata(), ResetMetadata(), and SetMetadataFromBuffer().
m_metadataLock
CCriticalSection CAirTunesServer::m_metadataLock static private
Referenced by RefreshCoverArt(), RefreshMetadata(), ResetMetadata(), SetCoverArtFromBuffer(), and SetMetadataFromBuffer().
m_pDACP
CDACP * CAirTunesServer::m_pDACP = NULL static private
Referenced by Announce(), FreeDACPRemote(), Process(), and SetupRemoteControl().
m_port
int CAirTunesServer::m_port private
Referenced by CAirTunesServer(), and Initialize().
m_pPipe
XFILE::CPipeFile* CAirTunesServer::m_pPipe private
Referenced by CAirTunesServer(), Initialize(), and ~CAirTunesServer().
m_pRaop
raop_t* CAirTunesServer::m_pRaop = nullptr private
Referenced by Deinitialize(), Initialize(), and IsRAOPRunningInternal().
m_processActions
CEvent CAirTunesServer::m_processActions static private
Referenced by OnAction(), and Process().
m_sampleRate
int CAirTunesServer::m_sampleRate = 44100 static private
Referenced by CAirTunesServer::AudioOutputFunctions::audio_init(), and InformPlayerAboutPlayTimes().
m_streamStarted
bool CAirTunesServer::m_streamStarted = false static private
Referenced by Announce(), CAirTunesServer::AudioOutputFunctions::audio_destroy(), CAirTunesServer::AudioOutputFunctions::audio_init(), and Process().
ServerInstance
CAirTunesServer * CAirTunesServer::ServerInstance = NULL static private
Referenced by EnableActionProcessing(), IsRunning(), RegisterActionListener(), StartServer(), and StopServer().
The documentation for this class was generated from the following files:
AirTunesServer.h
AirTunesServer.cpp