Kodi Documentation: KODI::JOYSTICK::CScalarFeature Class Reference
KODI::JOYSTICK::CScalarFeature Class Reference
Input » Joystick
#include <FeatureHandling.h>
Public Member Functions
CScalarFeature (const FeatureName &name, IInputHandler *handler, IButtonMap *buttonMap)
~CScalarFeature () override=default
bool OnDigitalMotion (const CDriverPrimitive &source, bool bPressed) override
A digital motion has occurred.
bool OnAnalogMotion (const CDriverPrimitive &source, float magnitude) override
An analog motion has occurred.
void ProcessMotions () override
Process the motions that have occurred since the last invocation.
Public Member Functions inherited from KODI::JOYSTICK::CJoystickFeature
CJoystickFeature (const FeatureName &name, IInputHandler *handler, IButtonMap *buttonMap)
virtual ~CJoystickFeature ()=default
bool AcceptsInput (bool bActivation)
Check if the input handler is accepting input.
Private Member Functions
bool OnDigitalMotion (bool bPressed)
bool OnAnalogMotion (float magnitude)
void ProcessDigitalMotion ()
void ProcessAnalogMotion ()
Private Attributes
INPUT_TYPE m_inputType = INPUT_TYPE::UNKNOWN
bool m_bDigitalState = false
bool m_bInitialPressHandled = false
float m_analogState = 0.0f
float m_bActivated = false
bool m_bDiscrete = true
Additional Inherited Members
Protected Member Functions inherited from KODI::JOYSTICK::CJoystickFeature
void ResetMotion ()
Reset motion timer.
void StartMotion ()
Start the motion timer.
bool InMotion () const
Check if the feature is in motion.
unsigned int MotionTimeMs () const
Get the time for which the feature has been in motion.
Protected Attributes inherited from KODI::JOYSTICK::CJoystickFeature
const FeatureName m_name
IInputHandler *const m_handler
IButtonMap *const m_buttonMap
const bool m_bEnabled
Constructor & Destructor Documentation
CScalarFeature()
CScalarFeature::CScalarFeature (const FeatureName & name, IInputHandler * handler, IButtonMap * buttonMap)
References KODI::JOYSTICK::IInputHandler::ControllerID(), KODI::GAME::CControllerManager::GetController(), CServiceBroker::GetGameControllerManager(), m_inputType, and name.
~CScalarFeature()
KODI::JOYSTICK::CScalarFeature::~CScalarFeature () override default
Member Function Documentation
OnAnalogMotion() [1/2]
bool CScalarFeature::OnAnalogMotion (const CDriverPrimitive & source, float magnitude) override virtual
An analog motion has occurred.
Parameters
source The source of the motion. Must be a semiaxis
magnitude The magnitude of the press or motion in the interval [0.0, 1.0]
For semiaxes, the magnitude is the force or travel distance in the direction of the semiaxis. If the value is in the opposite direction, the magnitude is 0.0.
For example, if the analog stick goes left, the negative semiaxis will have a value of 1.0 and the positive semiaxis will have a value of 0.0.
Implements KODI::JOYSTICK::CJoystickFeature.
References KODI::JOYSTICK::CJoystickFeature::AcceptsInput(), KODI::JOYSTICK::ANALOG, ANALOG_DIGITAL_THRESHOLD, KODI::JOYSTICK::DIGITAL, m_bActivated, m_bDiscrete, m_inputType, OnAnalogMotion(), and OnDigitalMotion().
Referenced by OnAnalogMotion(), and OnDigitalMotion().
OnAnalogMotion() [2/2]
bool CScalarFeature::OnAnalogMotion (float magnitude) private
References KODI::JOYSTICK::IInputHandler::ControllerID(), KODI::JOYSTICK::CJoystickFeature::InMotion(), CLog::Log(), LOGDEBUG, m_analogState, m_bDigitalState, KODI::JOYSTICK::CJoystickFeature::m_handler, KODI::JOYSTICK::CJoystickFeature::m_name, KODI::JOYSTICK::CJoystickFeature::ResetMotion(), and KODI::JOYSTICK::CJoystickFeature::StartMotion().
OnDigitalMotion() [1/2]
bool CScalarFeature::OnDigitalMotion (bool bPressed) private
References KODI::JOYSTICK::IInputHandler::ControllerID(), CLog::Log(), LOGDEBUG, m_bDigitalState, m_bInitialPressHandled, KODI::JOYSTICK::CJoystickFeature::m_handler, KODI::JOYSTICK::CJoystickFeature::m_name, KODI::JOYSTICK::IInputHandler::OnButtonPress(), and KODI::JOYSTICK::CJoystickFeature::ResetMotion().
OnDigitalMotion() [2/2]
bool CScalarFeature::OnDigitalMotion (const CDriverPrimitive & source, bool bPressed) override virtual
A digital motion has occurred.
Parameters
source The source of the motion. Must be digital (button or hat)
bPressed True for press motion, false for release motion
Returns
true if the motion was handled, false otherwise
Implements KODI::JOYSTICK::CJoystickFeature.
References KODI::JOYSTICK::CJoystickFeature::AcceptsInput(), KODI::JOYSTICK::ANALOG, KODI::JOYSTICK::DIGITAL, m_inputType, OnAnalogMotion(), and OnDigitalMotion().
Referenced by OnAnalogMotion(), and OnDigitalMotion().
ProcessAnalogMotion()
void CScalarFeature::ProcessAnalogMotion () private
References DISCRETE_ANALOG_RAMPUP_TIME_MS, DISCRETE_ANALOG_START_VALUE, m_analogState, m_bActivated, m_bDiscrete, KODI::JOYSTICK::CJoystickFeature::m_handler, KODI::JOYSTICK::CJoystickFeature::m_name, KODI::JOYSTICK::CJoystickFeature::MotionTimeMs(), and KODI::JOYSTICK::IInputHandler::OnButtonMotion().
Referenced by ProcessMotions().
ProcessDigitalMotion()
void CScalarFeature::ProcessDigitalMotion () private
References KODI::JOYSTICK::CJoystickFeature::InMotion(), KODI::JOYSTICK::CJoystickFeature::m_handler, KODI::JOYSTICK::CJoystickFeature::m_name, KODI::JOYSTICK::CJoystickFeature::MotionTimeMs(), KODI::JOYSTICK::IInputHandler::OnButtonHold(), and KODI::JOYSTICK::CJoystickFeature::StartMotion().
Referenced by ProcessMotions().
ProcessMotions()
void CScalarFeature::ProcessMotions () override virtual
Process the motions that have occurred since the last invocation.
This allows features with motion on multiple driver primitives to call their handler once all driver primitives are accounted for.
Implements KODI::JOYSTICK::CJoystickFeature.
References KODI::JOYSTICK::ANALOG, KODI::JOYSTICK::DIGITAL, m_bDigitalState, m_inputType, ProcessAnalogMotion(), and ProcessDigitalMotion().
Member Data Documentation
m_analogState
float KODI::JOYSTICK::CScalarFeature::m_analogState = 0.0f private
Referenced by OnAnalogMotion(), and ProcessAnalogMotion().
m_bActivated
float KODI::JOYSTICK::CScalarFeature::m_bActivated = false private
Referenced by OnAnalogMotion(), and ProcessAnalogMotion().
m_bDigitalState
bool KODI::JOYSTICK::CScalarFeature::m_bDigitalState = false private
Referenced by OnAnalogMotion(), OnDigitalMotion(), and ProcessMotions().
m_bDiscrete
bool KODI::JOYSTICK::CScalarFeature::m_bDiscrete = true private
Referenced by OnAnalogMotion(), and ProcessAnalogMotion().
m_bInitialPressHandled
bool KODI::JOYSTICK::CScalarFeature::m_bInitialPressHandled = false private
Referenced by OnDigitalMotion().
m_inputType
INPUT_TYPE KODI::JOYSTICK::CScalarFeature::m_inputType = INPUT_TYPE::UNKNOWN private
Referenced by CScalarFeature(), OnAnalogMotion(), OnDigitalMotion(), and ProcessMotions().
The documentation for this class was generated from the following files:
FeatureHandling.h
FeatureHandling.cpp