Kodi Documentation: GUIFontManager.cpp File Reference
GUIFontManager.cpp File Reference
#include "GUIFontManager.h"
#include "FileItemList.h"
#include "GUIComponent.h"
#include "GUIFontTTF.h"
#include "GUIWindowManager.h"
#include "addons/AddonManager.h"
#include "addons/FontResource.h"
#include "addons/Skin.h"
#include "addons/addoninfo/AddonType.h"
#include "filesystem/SpecialProtocol.h"
#include "windowing/GraphicContext.h"
#include <mutex>
#include "FileItem.h"
#include "GUIControlFactory.h"
#include "GUIFont.h"
#include "ServiceBroker.h"
#include "URL.h"
#include "filesystem/Directory.h"
#include "settings/lib/Setting.h"
#include "settings/lib/SettingDefinitions.h"
#include "utils/FileUtils.h"
#include "utils/FontUtils.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/XMLUtils.h"
#include "utils/log.h"
#include <algorithm>
#include <set>
Namespaces
namespace anonymous_namespace{GUIFontManager.cpp}
Functions
bool anonymous_namespace{GUIFontManager.cpp}::LoadXMLData (const std::string &filepath, CXBMCTinyXML &xmlDoc)
static bool CheckFont (std::string &strPath, const std::string &newPath, const std::string &filename)
Variables
constexpr const char * anonymous_namespace{GUIFontManager.cpp}::XML_FONTCACHE_FILENAME = "fontcache.xml"
Function Documentation
CheckFont()
static bool CheckFont (std::string & strPath, const std::string & newPath, const std::string & filename) static
References URIUtils::AddFileToFolder(), CFileUtils::Exists(), and CSpecialProtocol::TranslatePathConvertCase().
Referenced by GUIFontManager::LoadTTF().