Kodi Documentation: AddonToKodiFuncTable_kodi_addon Struct Reference
AddonToKodiFuncTable_kodi_addon Struct Reference
#include <addon_base.h>
Public Attributes
char *(* get_addon_path)(const KODI_ADDON_BACKEND_HDL hdl)
char *(* get_lib_path)(const KODI_ADDON_BACKEND_HDL hdl)
char *(* get_user_path)(const KODI_ADDON_BACKEND_HDL hdl)
char *(* get_temp_path)(const KODI_ADDON_BACKEND_HDL hdl)
char *(* get_localized_string)(const KODI_ADDON_BACKEND_HDL hdl, long label_id)
bool(* open_settings_dialog)(const KODI_ADDON_BACKEND_HDL hdl)
bool(* is_setting_using_default)(const KODI_ADDON_BACKEND_HDL hdl, const char *id)
bool(* get_setting_bool)(const KODI_ADDON_BACKEND_HDL hdl, const char *id, bool *value)
bool(* get_setting_int)(const KODI_ADDON_BACKEND_HDL hdl, const char *id, int *value)
bool(* get_setting_float)(const KODI_ADDON_BACKEND_HDL hdl, const char *id, float *value)
bool(* get_setting_string)(const KODI_ADDON_BACKEND_HDL hdl, const char *id, char **value)
bool(* set_setting_bool)(const KODI_ADDON_BACKEND_HDL hdl, const char *id, bool value)
bool(* set_setting_int)(const KODI_ADDON_BACKEND_HDL hdl, const char *id, int value)
bool(* set_setting_float)(const KODI_ADDON_BACKEND_HDL hdl, const char *id, float value)
bool(* set_setting_string)(const KODI_ADDON_BACKEND_HDL hdl, const char *id, const char *value)
char *(* get_addon_info)(const KODI_ADDON_BACKEND_HDL hdl, const char *id)
char *(* get_type_version)(const KODI_ADDON_BACKEND_HDL hdl, int type)
void *(* get_interface)(const KODI_ADDON_BACKEND_HDL hdl, const char *name, const char *version)
Member Data Documentation
get_addon_info
char *(* AddonToKodiFuncTable_kodi_addon::get_addon_info) (const KODI_ADDON_BACKEND_HDL hdl, const char *id)
Referenced by kodi::addon::GetAddonInfo(), and ADDON::Interface_Base::InitInterface().
get_addon_path
char *(* AddonToKodiFuncTable_kodi_addon::get_addon_path) (const KODI_ADDON_BACKEND_HDL hdl)
Referenced by kodi::addon::GetAddonPath(), and ADDON::Interface_Base::InitInterface().
get_interface
void *(* AddonToKodiFuncTable_kodi_addon::get_interface) (const KODI_ADDON_BACKEND_HDL hdl, const char *name, const char *version)
Referenced by kodi::addon::GetInterface(), and ADDON::Interface_Base::InitInterface().
get_lib_path
char *(* AddonToKodiFuncTable_kodi_addon::get_lib_path) (const KODI_ADDON_BACKEND_HDL hdl)
Referenced by kodi::addon::GetLibPath(), and ADDON::Interface_Base::InitInterface().
get_localized_string
char *(* AddonToKodiFuncTable_kodi_addon::get_localized_string) (const KODI_ADDON_BACKEND_HDL hdl, long label_id)
Referenced by kodi::addon::GetLocalizedString(), and ADDON::Interface_Base::InitInterface().
get_setting_bool
bool(* AddonToKodiFuncTable_kodi_addon::get_setting_bool) (const KODI_ADDON_BACKEND_HDL hdl, const char *id, bool *value)
Referenced by kodi::addon::CheckSettingBoolean(), and ADDON::Interface_Base::InitInterface().
get_setting_float
bool(* AddonToKodiFuncTable_kodi_addon::get_setting_float) (const KODI_ADDON_BACKEND_HDL hdl, const char *id, float *value)
Referenced by kodi::addon::CheckSettingFloat(), and ADDON::Interface_Base::InitInterface().
get_setting_int
bool(* AddonToKodiFuncTable_kodi_addon::get_setting_int) (const KODI_ADDON_BACKEND_HDL hdl, const char *id, int *value)
Referenced by kodi::addon::CheckSettingEnum(), kodi::addon::CheckSettingInt(), and ADDON::Interface_Base::InitInterface().
get_setting_string
bool(* AddonToKodiFuncTable_kodi_addon::get_setting_string) (const KODI_ADDON_BACKEND_HDL hdl, const char *id, char **value)
Referenced by kodi::addon::CheckSettingString(), and ADDON::Interface_Base::InitInterface().
get_temp_path
char *(* AddonToKodiFuncTable_kodi_addon::get_temp_path) (const KODI_ADDON_BACKEND_HDL hdl)
Referenced by kodi::addon::GetTempPath(), and ADDON::Interface_Base::InitInterface().
get_type_version
char *(* AddonToKodiFuncTable_kodi_addon::get_type_version) (const KODI_ADDON_BACKEND_HDL hdl, int type)
Referenced by kodi::addon::GetKodiTypeVersion(), and ADDON::Interface_Base::InitInterface().
get_user_path
char *(* AddonToKodiFuncTable_kodi_addon::get_user_path) (const KODI_ADDON_BACKEND_HDL hdl)
Referenced by kodi::addon::GetUserPath(), and ADDON::Interface_Base::InitInterface().
is_setting_using_default
bool(* AddonToKodiFuncTable_kodi_addon::is_setting_using_default) (const KODI_ADDON_BACKEND_HDL hdl, const char *id)
Referenced by ADDON::Interface_Base::InitInterface(), and kodi::addon::IsSettingUsingDefault().
open_settings_dialog
bool(* AddonToKodiFuncTable_kodi_addon::open_settings_dialog) (const KODI_ADDON_BACKEND_HDL hdl)
Referenced by ADDON::Interface_Base::InitInterface(), and kodi::addon::OpenSettings().
set_setting_bool
bool(* AddonToKodiFuncTable_kodi_addon::set_setting_bool) (const KODI_ADDON_BACKEND_HDL hdl, const char *id, bool value)
Referenced by ADDON::Interface_Base::InitInterface(), and kodi::addon::SetSettingBoolean().
set_setting_float
bool(* AddonToKodiFuncTable_kodi_addon::set_setting_float) (const KODI_ADDON_BACKEND_HDL hdl, const char *id, float value)
Referenced by ADDON::Interface_Base::InitInterface(), and kodi::addon::SetSettingFloat().
set_setting_int
bool(* AddonToKodiFuncTable_kodi_addon::set_setting_int) (const KODI_ADDON_BACKEND_HDL hdl, const char *id, int value)
Referenced by ADDON::Interface_Base::InitInterface(), kodi::addon::SetSettingEnum(), and kodi::addon::SetSettingInt().
set_setting_string
bool(* AddonToKodiFuncTable_kodi_addon::set_setting_string) (const KODI_ADDON_BACKEND_HDL hdl, const char *id, const char *value)
Referenced by ADDON::Interface_Base::InitInterface(), and kodi::addon::SetSettingString().
The documentation for this struct was generated from the following file:
addon_base.h