Kodi Documentation: CGUIViewStateWindowVideoNav Class Reference
CGUIViewStateWindowVideoNav Class Reference
#include <GUIViewStateVideo.h>
Public Member Functions
CGUIViewStateWindowVideoNav (const CFileItemList &items)
bool AutoPlayNextItem () override
Public Member Functions inherited from CGUIViewStateWindowVideo
CGUIViewStateWindowVideo (const CFileItemList &items)
Public Member Functions inherited from CGUIViewState
virtual ~CGUIViewState ()
void SetViewAsControl (int viewAsControl)
void SaveViewAsControl (int viewAsControl)
int GetViewAsControl () const
bool ChooseSortMethod ()
SortDescription SetNextSortMethod (int direction=1)
void SetCurrentSortMethod (int method)
SortDescription GetSortMethod () const
bool HasMultipleSortMethods () const
int GetSortMethodLabel () const
int GetSortOrderLabel () const
void GetSortMethodLabelMasks (LABEL_MASKS &masks) const
std::vector< SortDescription > GetSortDescriptions () const
SortOrder SetNextSortOrder ()
SortOrder GetSortOrder () const
virtual bool HideExtensions ()
virtual bool HideParentDirItems ()
virtual bool DisableAddSourceButtons ()
const std::string & GetPlaylistDirectory ()
void SetPlaylistDirectory (const std::string &strDirectory)
bool IsCurrentPlaylistDirectory (const std::string &strDirectory)
Protected Member Functions
void SaveViewState () override
std::vector< CMediaSource > & GetSources () override
Protected Member Functions inherited from CGUIViewStateWindowVideo
std::string GetLockType () override
KODI::PLAYLIST::Id GetPlaylist () const override
std::string GetExtensions () override
Protected Member Functions inherited from CGUIViewState
CGUIViewState (const CFileItemList &items)
virtual void SaveViewToDb (const std::string &path, int windowID, CViewState *viewState=NULL)
void LoadViewState (const std::string &path, int windowID)
void AddLiveTVSources ()
void AddPlaylistOrder (const CFileItemList &items, const LABEL_MASKS &label_masks)
Add the sort order defined in a smartplaylist Defaults to SORT_METHOD_PLAYLIST_ORDER if no order is defined.
void AddSortMethod (SortBy sortBy, int buttonLabel, const LABEL_MASKS &labelMasks, SortAttribute sortAttributes=SortAttributeNone, SortOrder sortOrder=SortOrderNone)
void AddSortMethod (SortBy sortBy, SortAttribute sortAttributes, int buttonLabel, const LABEL_MASKS &labelMasks, SortOrder sortOrder=SortOrderNone)
void AddSortMethod (SortDescription sortDescription, int buttonLabel, const LABEL_MASKS &labelMasks)
void SetSortMethod (SortBy sortBy, SortOrder sortOrder=SortOrderNone)
void SetSortMethod (SortDescription sortDescription)
void SetSortOrder (SortOrder sortOrder)
bool AutoPlayNextVideoItem () const
Additional Inherited Members
Static Public Member Functions inherited from CGUIViewState
static CGUIViewState * GetViewState (int windowId, const CFileItemList &items)
Protected Attributes inherited from CGUIViewState
const CFileItemList & m_items
int m_currentViewAsControl
KODI::PLAYLIST::Id m_playlist
std::vector< GUIViewSortDetails > m_sortMethods
int m_currentSortMethod
Static Protected Attributes inherited from CGUIViewState
static std::vector< CMediaSource > m_sources
static std::string m_strPlaylistDirectory
Constructor & Destructor Documentation
CGUIViewStateWindowVideoNav()
CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav (const CFileItemList & items) explicit
References CGUIViewState::AddSortMethod(), DEFAULT_VIEW_LIST, CViewStateSettings::Get(), XFILE::CVideoDatabaseDirectory::GetDirectoryChildType(), CViewStateSettings::GetInstance(), CFileItem::GetPath(), XFILE::CVideoDatabaseDirectory::GetQueryParams(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSeason(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSetId(), CServiceBroker::GetSettingsComponent(), CFileItem::IsVirtualDirectoryRoot(), CGUIViewState::LoadViewState(), CViewState::m_sortDescription, CViewState::m_viewMode, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ACTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_COUNTRY, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_DIRECTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_INPROGRESS_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MOVIES_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_ALBUM, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SEASONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SETS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_STUDIO, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TAGS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TVSHOWS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_VIDEOVERSIONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_YEAR, CGUIViewState::SetSortMethod(), CGUIViewState::SetSortOrder(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CSettings::SETTING_MUSICFILES_TRACKFORMAT, CGUIViewState::SetViewAsControl(), SortAttributeIgnoreArticle, SortAttributeNone, SortByAlbum, SortByArtist, SortByArtistThenYear, SortByDate, SortByDateAdded, SortByEpisodeNumber, SortByFile, SortByLabel, SortByLastPlayed, SortByMPAA, SortByNone, SortByNumberOfEpisodes, SortByOriginalTitle, SortByPlaycount, SortByProductionCode, SortByRating, SortByRelevance, SortBySize, SortBySortTitle, SortByTime, SortByTrackNumber, SortByUserRating, SortByYear, SortDescription::sortOrder, SortOrderAscending, SortOrderNone, and WINDOW_VIDEO_NAV.
Member Function Documentation
AutoPlayNextItem()
bool CGUIViewStateWindowVideoNav::AutoPlayNextItem () override virtual
Reimplemented from CGUIViewStateWindowVideo.
References CGUIViewStateWindowVideo::AutoPlayNextItem(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetContentType(), CFileItem::GetPath(), XFILE::CVideoDatabaseDirectory::GetQueryParams(), CServiceBroker::GetSettingsComponent(), CGUIViewState::m_items, MUSICVIDEOS, and CSettings::SETTING_MUSICPLAYER_AUTOPLAYNEXTITEM.
GetSources()
std::vector< CMediaSource > & CGUIViewStateWindowVideoNav::GetSources () override protected virtual
Reimplemented from CGUIViewStateWindowVideo.
References XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::GetDirectory(), CServiceBroker::GetSettingsComponent(), CGUIViewStateWindowVideo::GetSources(), CMediaSource::m_iDriveType, CGUIViewState::m_sources, CMediaSource::m_strThumbnailImage, CSettings::SETTING_MYVIDEOS_FLATTEN, CFileItemList::Size(), CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::strName, and CMediaSource::strPath.
SaveViewState()
void CGUIViewStateWindowVideoNav::SaveViewState () override protected virtual
Implements CGUIViewState.
References CViewStateSettings::Get(), XFILE::CVideoDatabaseDirectory::GetDirectoryChildType(), CViewStateSettings::GetInstance(), CFileItem::GetPath(), XFILE::CVideoDatabaseDirectory::GetQueryParams(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSetId(), CGUIViewState::m_items, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ACTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SEASONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_YEAR, CGUIViewState::SaveViewToDb(), and WINDOW_VIDEO_NAV.
The documentation for this class was generated from the following files:
GUIViewStateVideo.h
GUIViewStateVideo.cpp