Kodi Documentation: CDVDSubtitleStream Class Reference
CDVDSubtitleStream Class Reference
#include <DVDSubtitleStream.h>
Public Member Functions
CDVDSubtitleStream ()
virtual ~CDVDSubtitleStream ()
bool Open (const std::string &strFile)
bool IsIncompatible (CDVDInputStream *pInputStream, std::vector< uint8_t > &buf, size_t *bytesRead)
Checks if the subtitle associated with the pInputStream is known to be incompatible, e.g., vob sub files.
std::string Read (int length)
Read some data of specified length, from the current position.
bool Seek (int offset)
Change the current data position to the specified offset.
bool ReadLine (std::string &line)
Read a line of data.
const std::string & GetData ()
Get the full data.
Private Attributes
std::string m_subtitleData
CCharArrayParser m_arrayParser
Constructor & Destructor Documentation
CDVDSubtitleStream()
CDVDSubtitleStream::CDVDSubtitleStream () default
~CDVDSubtitleStream()
CDVDSubtitleStream::~CDVDSubtitleStream () virtual default
Member Function Documentation
GetData()
const std::string & CDVDSubtitleStream::GetData () inline
Get the full data.
Returns
The data
References m_subtitleData.
IsIncompatible()
bool CDVDSubtitleStream::IsIncompatible (CDVDInputStream * pInputStream, std::vector< uint8_t > & buf, size_t * bytesRead)
Checks if the subtitle associated with the pInputStream is known to be incompatible, e.g., vob sub files.
Parameters
[in] pInputStream The input stream for the subtitle to check.
References CDVDInputStream::Read().
Referenced by Open().
Open()
bool CDVDSubtitleStream::Open (const std::string & strFile)
References CDVDFactoryInputStream::CreateInputStream(), g_charsetConverter, CCharsetDetection::GetBomEncoding(), URIUtils::HasExtension(), IsIncompatible(), CUtf8Utils::isValidUtf8(), CLog::Log(), LOGDEBUG, m_arrayParser, m_subtitleData, CCharArrayParser::Reset(), and CFileItem::SetContentLookup().
Referenced by CUtil::ScanForExternalSubtitles().
Read()
std::string CDVDSubtitleStream::Read (int length)
Read some data of specified length, from the current position.
Parameters
length The length of data to be read
Returns
The string read
References m_arrayParser, and CCharArrayParser::ReadNextString().
ReadLine()
bool CDVDSubtitleStream::ReadLine (std::string & line)
Read a line of data.
Parameters
[OUT] line The data read
Returns
True if read, otherwise false if EOF
References m_arrayParser, and CCharArrayParser::ReadNextLine().
Referenced by CDVDSubtitleTagSami::LoadHead().
Seek()
bool CDVDSubtitleStream::Seek (int offset)
Change the current data position to the specified offset.
Parameters
offset The new position
Returns
True if success, otherwise false
References m_arrayParser, and CCharArrayParser::SetPosition().
Member Data Documentation
m_arrayParser
CCharArrayParser CDVDSubtitleStream::m_arrayParser private
Referenced by Open(), Read(), ReadLine(), and Seek().
m_subtitleData
std::string CDVDSubtitleStream::m_subtitleData private
Referenced by GetData(), and Open().
The documentation for this class was generated from the following files:
DVDSubtitleStream.h
DVDSubtitleStream.cpp