Kodi Documentation: kodi::addon::PVRStringSettingDefinition Class Reference
kodi::addon::PVRStringSettingDefinition Class Reference
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General » class PVRStringSettingDefinition
#include <General.h>
Public Member Functions
PVRStringSettingDefinition (const std::vector< PVRTypeStringValue > &settingValues, const std::string &defaultValue, bool allowEmptyValue)
Class constructor with integrated values.
void SetValues (const std::vector< PVRTypeStringValue > &values, const std::string &defaultValue="")
optional
value definitions.
std::vector< PVRTypeStringValue > GetValues () const
To get with SetValues changed values.
void SetDefaultValue (const std::string &defaultValue)
optional
The default value for this setting.
std::string GetDefaultValue () const
To get with SetDefaultValue changed values.
void SetAllowEmptyValue (bool allowEmptyValue)
optional
The allow empty values flag for this setting.
bool GetAllowEmptyValue () const
To get with SetAllowEmptyValue changed values.
Public Member Functions inherited from kodi::addon::DynamicCStructHdl< PVRStringSettingDefinition, PVR_STRING_SETTING_DEFINITION >
DynamicCStructHdl ()
DynamicCStructHdl (const DynamicCStructHdl &cppClass)
DynamicCStructHdl (const PVR_STRING_SETTING_DEFINITION *cStructure)
DynamicCStructHdl (PVR_STRING_SETTING_DEFINITION *cStructure)
const DynamicCStructHdl & operator= (const DynamicCStructHdl &right)
const DynamicCStructHdl & operator= (const PVR_STRING_SETTING_DEFINITION &right)
virtual ~DynamicCStructHdl ()
operator PVR_STRING_SETTING_DEFINITION * ()
operator const PVR_STRING_SETTING_DEFINITION * () const
const PVR_STRING_SETTING_DEFINITION * GetCStructure () const
PVR_STRING_SETTING_DEFINITION * release ()
Static Public Member Functions
static PVR_STRING_SETTING_DEFINITION * AllocAndCopyData (const PVRStringSettingDefinition &source)
static PVR_STRING_SETTING_DEFINITION * AllocAndCopyData (PVR_STRING_SETTING_DEFINITION *source)
static void AllocResources (const PVR_STRING_SETTING_DEFINITION *source, PVR_STRING_SETTING_DEFINITION *target)
static void FreeResources (PVR_STRING_SETTING_DEFINITION *target)
static void ReallocAndCopyData (PVR_STRING_SETTING_DEFINITION **source, const PVRStringSettingDefinition &def)
Private Member Functions
PVRStringSettingDefinition (const PVR_STRING_SETTING_DEFINITION *def)
PVRStringSettingDefinition (PVR_STRING_SETTING_DEFINITION *def)
Friends
class CInstancePVRClient
Additional Inherited Members
Protected Attributes inherited from kodi::addon::DynamicCStructHdl< PVRStringSettingDefinition, PVR_STRING_SETTING_DEFINITION >
PVR_STRING_SETTING_DEFINITION * m_cStructure
Constructor & Destructor Documentation
PVRStringSettingDefinition() [1/2]
kodi::addon::PVRStringSettingDefinition::PVRStringSettingDefinition (const PVR_STRING_SETTING_DEFINITION * def) inline private
PVRStringSettingDefinition() [2/2]
kodi::addon::PVRStringSettingDefinition::PVRStringSettingDefinition (PVR_STRING_SETTING_DEFINITION * def) inline private
Member Function Documentation
AllocAndCopyData() [1/2]
static PVR_STRING_SETTING_DEFINITION * kodi::addon::PVRStringSettingDefinition::AllocAndCopyData (const PVRStringSettingDefinition & source) inline static
References AllocResources(), PVR_STRING_SETTING_DEFINITION::bAllowEmptyValue, and kodi::addon::DynamicCStructHdl< CPP_CLASS, C_STRUCT >::GetCStructure().
Referenced by kodi::addon::PVRSettingDefinition::AllocResources(), and ReallocAndCopyData().
AllocAndCopyData() [2/2]
static PVR_STRING_SETTING_DEFINITION * kodi::addon::PVRStringSettingDefinition::AllocAndCopyData (PVR_STRING_SETTING_DEFINITION * source) inline static
References AllocResources(), and PVR_STRING_SETTING_DEFINITION::bAllowEmptyValue.
AllocResources()
static void kodi::addon::PVRStringSettingDefinition::AllocResources (const PVR_STRING_SETTING_DEFINITION * source, PVR_STRING_SETTING_DEFINITION * target) inline static
References kodi::addon::PVRTypeStringValue::AllocAndCopyData(), kodi::addon::AllocAndCopyString(), PVR_STRING_SETTING_DEFINITION::iValuesSize, PVR_STRING_SETTING_DEFINITION::strDefaultValue, and PVR_STRING_SETTING_DEFINITION::values.
Referenced by AllocAndCopyData(), and AllocAndCopyData().
FreeResources()
static void kodi::addon::PVRStringSettingDefinition::FreeResources (PVR_STRING_SETTING_DEFINITION * target) inline static
References kodi::addon::PVRTypeStringValue::FreeResources(), kodi::addon::FreeString(), PVR_STRING_SETTING_DEFINITION::iValuesSize, PVR_STRING_SETTING_DEFINITION::strDefaultValue, and PVR_STRING_SETTING_DEFINITION::values.
Referenced by kodi::addon::PVRSettingDefinition::FreeResources(), and ReallocAndCopyData().
ReallocAndCopyData()
static void kodi::addon::PVRStringSettingDefinition::ReallocAndCopyData (PVR_STRING_SETTING_DEFINITION ** source, const PVRStringSettingDefinition & def) inline static
References AllocAndCopyData(), and FreeResources().
Referenced by kodi::addon::PVRSettingDefinition::SetStringDefinition().
Friends And Related Symbol Documentation
CInstancePVRClient
friend class CInstancePVRClient friend
The documentation for this class was generated from the following file:
kodi-dev-kit/include/kodi/addon-instance/pvr/General.h