Kodi Documentation: CJSONVariantParser Class Reference
CJSONVariantParser Class Reference
#include <JSONVariantParser.h>
Public Member Functions
CJSONVariantParser ()=delete
Static Public Member Functions
static bool Parse (const char *json, CVariant &data)
static bool Parse (const std::string &json, CVariant &data)
Constructor & Destructor Documentation
CJSONVariantParser()
CJSONVariantParser::CJSONVariantParser () delete
Member Function Documentation
Parse() [1/2]
bool CJSONVariantParser::Parse (const char * json, CVariant & data) static
References data().
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata(), XFILE::CShoutcastFile::ExtractTagInfo(), KODI::GAME::CGameSettings::IsAccountVerified(), KODI::RETRO::CCheevos::LoadData(), KODI::PLAYLIST::CSmartPlaylist::LoadFromJson(), KODI::GAME::CGameSettings::LoginToRA(), JSONRPC::CJSONRPC::MethodCall(), NotifyAll(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::OnAppLifecycleEvent(), KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS::OnScreenSaverAboutToStart(), Parse(), JSONRPC::CJSONServiceDescription::prepareDescription(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and ADDON::CAddonDatabase::UpdateTables().
Parse() [2/2]
bool CJSONVariantParser::Parse (const std::string & json, CVariant & data) static
References data(), and Parse().
The documentation for this class was generated from the following files:
JSONVariantParser.h
JSONVariantParser.cpp