Kodi Documentation: XBMCAddon::Alternative< T1, T2 > Class Template Reference
XBMCAddon::Alternative< T1, T2 > Class Template Reference
#include <Alternative.h>
Public Member Functions
Alternative ()=default
WhichAlternative which () const
T1 & former ()
const T1 & former () const
T2 & later ()
const T2 & later () const
operator T1 & ()
operator const T1 & () const
operator T2 & ()
operator const T2 & () const
Private Attributes
WhichAlternative pos = none
T1 d1
T2 d2
Constructor & Destructor Documentation
Alternative()
template<typename T1 , typename T2 > XBMCAddon::Alternative< T1, T2 >::Alternative () default
Member Function Documentation
former() [1/2]
template<typename T1 , typename T2 > T1 & XBMCAddon::Alternative< T1, T2 >::former () inline
References XBMCAddon::Alternative< T1, T2 >::d1, XBMCAddon::first, XBMCAddon::none, and XBMCAddon::second.
Referenced by XBMCAddon::xbmcgui::ControlList::addItem(), XBMCAddon::xbmcgui::WindowXML::addItem(), XBMCAddon::xbmcgui::Dialog::browse(), XBMCAddon::xbmcgui::ListItem::getStringArray(), XBMCAddon::Alternative< T1, T2 >::operator const T1 &(), XBMCAddon::Alternative< T1, T2 >::operator T1 &(), XBMCAddon::xbmc::Player::play(), and XBMCAddon::xbmcgui::ListItem::setInfo().
former() [2/2]
template<typename T1 , typename T2 > const T1 & XBMCAddon::Alternative< T1, T2 >::former () const inline
References XBMCAddon::Alternative< T1, T2 >::d1, and XBMCAddon::first.
later() [1/2]
template<typename T1 , typename T2 > T2 & XBMCAddon::Alternative< T1, T2 >::later () inline
References XBMCAddon::Alternative< T1, T2 >::d2, XBMCAddon::first, XBMCAddon::none, and XBMCAddon::second.
Referenced by XBMCAddon::xbmcgui::ControlList::addItem(), XBMCAddon::xbmcgui::WindowXML::addItem(), XBMCAddon::xbmcgui::Dialog::browse(), XBMCAddon::xbmcgui::ListItem::getStringArray(), XBMCAddon::Alternative< T1, T2 >::operator const T2 &(), XBMCAddon::Alternative< T1, T2 >::operator T2 &(), XBMCAddon::xbmc::Player::play(), and XBMCAddon::xbmcgui::ListItem::setInfo().
later() [2/2]
template<typename T1 , typename T2 > const T2 & XBMCAddon::Alternative< T1, T2 >::later () const inline
References XBMCAddon::Alternative< T1, T2 >::d2, and XBMCAddon::second.
operator const T1 &()
template<typename T1 , typename T2 > XBMCAddon::Alternative< T1, T2 >::operator const T1 & () const inline
References XBMCAddon::Alternative< T1, T2 >::former().
operator const T2 &()
template<typename T1 , typename T2 > XBMCAddon::Alternative< T1, T2 >::operator const T2 & () const inline
References XBMCAddon::Alternative< T1, T2 >::later().
operator T1 &()
template<typename T1 , typename T2 > XBMCAddon::Alternative< T1, T2 >::operator T1 & () inline
References XBMCAddon::Alternative< T1, T2 >::former().
operator T2 &()
template<typename T1 , typename T2 > XBMCAddon::Alternative< T1, T2 >::operator T2 & () inline
References XBMCAddon::Alternative< T1, T2 >::later().
which()
template<typename T1 , typename T2 > WhichAlternative XBMCAddon::Alternative< T1, T2 >::which () const inline
References XBMCAddon::Alternative< T1, T2 >::pos.
Referenced by XBMCAddon::xbmcgui::ControlList::addItem(), XBMCAddon::xbmcgui::WindowXML::addItem(), XBMCAddon::xbmcgui::ListItem::getStringArray(), XBMCAddon::xbmc::Player::play(), and XBMCAddon::xbmcgui::ListItem::setInfo().
Member Data Documentation
d1
template<typename T1 , typename T2 > T1 XBMCAddon::Alternative< T1, T2 >::d1 private
Referenced by XBMCAddon::Alternative< T1, T2 >::former(), and XBMCAddon::Alternative< T1, T2 >::former().
d2
template<typename T1 , typename T2 > T2 XBMCAddon::Alternative< T1, T2 >::d2 private
Referenced by XBMCAddon::Alternative< T1, T2 >::later(), and XBMCAddon::Alternative< T1, T2 >::later().
pos
template<typename T1 , typename T2 > WhichAlternative XBMCAddon::Alternative< T1, T2 >::pos = none private
Referenced by XBMCAddon::Alternative< T1, T2 >::which().
The documentation for this class was generated from the following file:
Alternative.h