Kodi Documentation: AddonToKodiFuncTable_android_system Struct Reference
AddonToKodiFuncTable_android_system Struct Reference
#include <system.h>
Public Attributes
void *(* get_jni_env)()
int(* get_sdk_version)()
const char *(* get_class_name)()
Member Data Documentation
get_class_name
const char *(* AddonToKodiFuncTable_android_system::get_class_name) ()
Referenced by ADDON::Interface_Android::Register().
get_jni_env
void *(* AddonToKodiFuncTable_android_system::get_jni_env) ()
Referenced by ADDON::Interface_Android::Register().
get_sdk_version
int(* AddonToKodiFuncTable_android_system::get_sdk_version) ()
Referenced by ADDON::Interface_Android::Register().
The documentation for this struct was generated from the following file:
kodi-dev-kit/include/kodi/c-api/platform/android/system.h