Kodi Documentation: CExternalPlayer Class Reference
CExternalPlayer Class Reference
#include <ExternalPlayer.h>
Public Types
enum WARP_CURSOR {
WARP_NONE = 0 , WARP_TOP_LEFT , WARP_TOP_RIGHT , WARP_BOTTOM_RIGHT ,
WARP_BOTTOM_LEFT , WARP_CENTER
}
Public Member Functions
CExternalPlayer (IPlayerCallback &callback)
~CExternalPlayer () override
bool Initialize (TiXmlElement *pConfig) override
bool OpenFile (const CFileItem &file, const CPlayerOptions &options) override
bool CloseFile (bool reopen=false) override
bool IsPlaying () const override
void Pause () override
bool HasVideo () const override
bool HasAudio () const override
bool CanSeek () const override
void Seek (bool bPlus, bool bLargeStep, bool bChapterOverride) override
void SeekPercentage (float iPercent) override
void SetVolume (float volume) override
void SetDynamicRangeCompression (long drc) override
void SetAVDelay (float fValue=0.0f) override
float GetAVDelay () override
void SetSubTitleDelay (float fValue=0.0f) override
float GetSubTitleDelay () override
void SeekTime (int64_t iTime) override
void SetSpeed (float speed) override
bool SetPlayerState (const std::string &state) override
Public Member Functions inherited from IPlayer
IPlayer (IPlayerCallback &callback)
virtual ~IPlayer ()=default
virtual bool QueueNextFile (const CFileItem &file)
virtual void OnNothingToQueueNotify ()
virtual bool CanPause () const
virtual bool HasGame () const
virtual bool HasRDS () const
virtual bool HasID3 () const
virtual bool IsPassthrough () const
virtual bool SeekScene (Direction seekDirection)
virtual float GetCachePercentage () const
virtual void SetMute (bool bOnOff)
virtual int GetSubtitleCount () const
virtual int GetSubtitle ()
virtual void GetSubtitleStreamInfo (int index, SubtitleStreamInfo &info) const
virtual void SetSubtitle (int iStream)
virtual bool GetSubtitleVisible () const
virtual void SetSubtitleVisible (bool bVisible)
virtual void SetSubtitleVerticalPosition (int value, bool save)
Set the subtitle vertical position, it depends on current screen resolution.
virtual void AddSubtitle (const std::string &strSubPath)
Adds the subtitle(s) provided by the given file to the available player streams and actives the first of the added stream(s). E.g., vob subs can contain multiple streams.
virtual int GetAudioStreamCount () const
virtual int GetAudioStream ()
virtual void SetAudioStream (int iStream)
virtual void GetAudioStreamInfo (int index, AudioStreamInfo &info) const
virtual int GetVideoStream () const
virtual int GetVideoStreamCount () const
virtual void GetVideoStreamInfo (int streamId, VideoStreamInfo &info) const
virtual void SetVideoStream (int iStream)
virtual int GetPrograms (std::vector< ProgramInfo > &programs)
virtual void SetProgram (int progId)
virtual int GetProgramsCount () const
virtual bool HasTeletextCache () const
virtual std::shared_ptr< TextCacheStruct_t > GetTeletextCache ()
virtual void LoadPage (int p, int sp, unsigned char *buffer)
virtual int GetChapterCount () const
virtual int GetChapter () const
virtual void GetChapterName (std::string &strChapterName, int chapterIdx=-1) const
virtual int64_t GetChapterPos (int chapterIdx=-1) const
virtual int SeekChapter (int iChapter)
virtual bool SeekTimeRelative (int64_t iTime)
virtual void SetTime (int64_t time)
Sets the current time. This can be used for injecting the current time. This is not to be confused with a seek. It just can be used if endless streams contain multiple tracks in reality (like with airtunes)
virtual void SetTotalTime (int64_t time)
Set the total time in milliseconds this can be used for injecting the duration in case its not available in the underlaying decoder (airtunes for example)
virtual void SetTempo (float tempo)
virtual bool SupportsTempo () const
virtual void FrameAdvance (int frames)
virtual bool IsCaching () const
virtual int GetCacheLevel () const
virtual bool IsInMenu () const
virtual MenuType GetSupportedMenuType () const
Get the supported menu type.
virtual bool OnAction (const CAction &action)
virtual std::string GetPlayerState ()
virtual void GetAudioCapabilities (std::vector< IPlayerAudioCaps > &caps) const
Define the audio capabilities of the player.
virtual void GetSubtitleCapabilities (std::vector< IPlayerSubtitleCaps > &caps) const
Define the subtitle capabilities of the player.
virtual void Render (bool clear, uint32_t alpha=255, bool gui=true)
hook into render loop of render thread
virtual void FlushRenderer ()
virtual void SetRenderViewMode (int mode, float zoom, float par, float shift, bool stretch)
virtual float GetRenderAspectRatio () const
virtual void TriggerUpdateResolution ()
virtual bool IsRenderingVideo () const
virtual void GetRects (CRect &source, CRect &dest, CRect &view) const
virtual unsigned int GetOrientation () const
virtual bool Supports (EINTERLACEMETHOD method) const
virtual EINTERLACEMETHOD GetDeinterlacingMethodDefault () const
virtual bool Supports (ESCALINGMETHOD method) const
virtual bool Supports (ERENDERFEATURE feature) const
virtual unsigned int RenderCaptureAlloc ()
virtual void RenderCaptureRelease (unsigned int captureId)
virtual void RenderCapture (unsigned int captureId, unsigned int width, unsigned int height, int flags)
virtual bool RenderCaptureGetPixels (unsigned int captureId, unsigned int millis, uint8_t *buffer, unsigned int size)
virtual CVideoSettings GetVideoSettings () const
virtual void SetVideoSettings (CVideoSettings &settings)
virtual bool HasGameAgent () const
Check if any players are playing a game.
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Member Functions
void GetCustomRegexpReplacers (TiXmlElement *pRootElement, std::vector< std::string > &settings)
void Process () override
Private Attributes
bool m_bAbortRequest
bool m_bIsPlaying
std::chrono::time_point< std::chrono::steady_clock > m_playbackStartTime
float m_speed
int m_time
std::string m_launchFilename
CGUIDialogOK * m_dialog
std::string m_filename
std::string m_args
bool m_hideconsole
bool m_hidexbmc
bool m_islauncher
bool m_playOneStackItem
WARP_CURSOR m_warpcursor
int m_playCountMinTime
std::vector< std::string > m_filenameReplacers
CFileItem m_file
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Public Attributes inherited from IPlayer
std::string m_name
std::string m_type
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from IPlayer
IPlayerCallback & m_callback
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Member Enumeration Documentation
WARP_CURSOR
enum CExternalPlayer::WARP_CURSOR
Enumerator
WARP_NONE
WARP_TOP_LEFT
WARP_TOP_RIGHT
WARP_BOTTOM_RIGHT
WARP_BOTTOM_LEFT
WARP_CENTER
Constructor & Destructor Documentation
CExternalPlayer()
CExternalPlayer::CExternalPlayer (IPlayerCallback & callback) explicit
References DEFAULT_PLAYCOUNT_MIN_TIME, m_bAbortRequest, m_bIsPlaying, m_dialog, m_hideconsole, m_hidexbmc, m_islauncher, m_playCountMinTime, m_playOneStackItem, m_speed, m_time, m_warpcursor, and WARP_NONE.
~CExternalPlayer()
CExternalPlayer::~CExternalPlayer () override
References CloseFile().
Member Function Documentation
CanSeek()
bool CExternalPlayer::CanSeek () const override virtual
Reimplemented from IPlayer.
CloseFile()
bool CExternalPlayer::CloseFile (bool reopen = false) override virtual
Implements IPlayer.
References CGUIWindow::Close(), CServiceBroker::GetDataCacheCore(), CGUIWindow::IsActive(), m_bAbortRequest, m_bIsPlaying, m_dialog, and CDataCacheCore::Reset().
Referenced by ~CExternalPlayer().
GetAVDelay()
float CExternalPlayer::GetAVDelay () override virtual
Reimplemented from IPlayer.
GetCustomRegexpReplacers()
void CExternalPlayer::GetCustomRegexpReplacers (TiXmlElement * pRootElement, std::vector< std::string > & settings) private
References XMLUtils::GetString(), CLog::Log(), LOGDEBUG, and LOGERROR.
Referenced by Initialize().
GetSubTitleDelay()
float CExternalPlayer::GetSubTitleDelay () override virtual
Reimplemented from IPlayer.
HasAudio()
bool CExternalPlayer::HasAudio () const override virtual
Implements IPlayer.
HasVideo()
bool CExternalPlayer::HasVideo () const override virtual
Implements IPlayer.
Initialize()
bool CExternalPlayer::Initialize (TiXmlElement * pConfig) override virtual
Reimplemented from IPlayer.
References XMLUtils::GetBoolean(), GetCustomRegexpReplacers(), XMLUtils::GetInt(), XMLUtils::GetString(), CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, m_args, m_filename, m_filenameReplacers, m_hideconsole, m_hidexbmc, m_islauncher, m_playCountMinTime, m_playOneStackItem, m_warpcursor, WARP_BOTTOM_LEFT, WARP_BOTTOM_RIGHT, WARP_CENTER, WARP_TOP_LEFT, and WARP_TOP_RIGHT.
IsPlaying()
bool CExternalPlayer::IsPlaying () const override virtual
Reimplemented from IPlayer.
References m_bIsPlaying.
OpenFile()
bool CExternalPlayer::OpenFile (const CFileItem & file, const CPlayerOptions & options) override virtual
Reimplemented from IPlayer.
References CThread::Create(), CLog::Log(), LOGERROR, LOGINFO, m_bIsPlaying, m_file, m_launchFilename, m_playbackStartTime, and m_time.
Pause()
void CExternalPlayer::Pause () override virtual
Implements IPlayer.
Process()
void CExternalPlayer::Process (void) override private virtual
Reimplemented from CThread.
References URIUtils::AddFileToFolder(), CRegExp::autoUtf8, end(), g_application, g_hWnd, CURL::Get(), CServiceBroker::GetActiveAE(), CServiceBroker::GetAppComponents(), CCompileInfo::GetAppName(), CURL::GetFileName(), CRegExp::GetFindLen(), CServiceBroker::GetGUI(), CURL::GetHostName(), CRegExp::GetReplaceString(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), CWinSystemBase::Hide(), CURL::IsProtocol(), IAE::IsSuspended(), LAUNCHER_PROCESS_TIME, CLog::Log(), LOGDEBUG, LOGERROR, LOGFATAL, LOGINFO, m_args, m_bAbortRequest, m_bIsPlaying, IPlayer::m_callback, m_dialog, m_file, m_filename, m_filenameReplacers, m_hidexbmc, m_islauncher, m_launchFilename, IPlayer::m_name, m_playbackStartTime, m_playCountMinTime, m_playOneStackItem, m_warpcursor, IPlayerCallback::OnAVStarted(), IPlayerCallback::OnPlayBackEnded(), IPlayerCallback::OnPlayBackStarted(), IPlayerCallback::OnPlayBackStopped(), IPlayerCallback::OnPlayerCloseFile(), CGUIDialog::Open(), CBookmark::player, CRegExp::RegComp(), CRegExp::RegFind(), CApplicationPowerHandling::ResetScreenSaver(), CWinSystemBase::Restore(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CWinSystemBase::Show(), CThread::Sleep(), IAE::Suspend(), CBookmark::timeInSeconds, CBookmark::totalTimeInSeconds, XFILE::CMusicDatabaseFile::TranslateUrl(), WARP_BOTTOM_LEFT, WARP_BOTTOM_RIGHT, WARP_CENTER, WARP_TOP_RIGHT, and WINDOW_DIALOG_OK.
Seek()
void CExternalPlayer::Seek (bool bPlus, bool bLargeStep, bool bChapterOverride) override virtual
Implements IPlayer.
SeekPercentage()
void CExternalPlayer::SeekPercentage (float iPercent) override virtual
Reimplemented from IPlayer.
SeekTime()
void CExternalPlayer::SeekTime (int64_t iTime) override virtual
Reimplemented from IPlayer.
SetAVDelay()
void CExternalPlayer::SetAVDelay (float fValue = 0.0f) override virtual
Reimplemented from IPlayer.
SetDynamicRangeCompression()
void CExternalPlayer::SetDynamicRangeCompression (long drc) inline override virtual
Reimplemented from IPlayer.
SetPlayerState()
bool CExternalPlayer::SetPlayerState (const std::string & state) override virtual
Reimplemented from IPlayer.
SetSpeed()
void CExternalPlayer::SetSpeed (float speed) override virtual
Implements IPlayer.
References CDataCacheCore::GetInstance(), m_speed, and CDataCacheCore::SetSpeed().
SetSubTitleDelay()
void CExternalPlayer::SetSubTitleDelay (float fValue = 0.0f) override virtual
Reimplemented from IPlayer.
SetVolume()
void CExternalPlayer::SetVolume (float volume) inline override virtual
Reimplemented from IPlayer.
Member Data Documentation
m_args
std::string CExternalPlayer::m_args private
Referenced by Initialize(), and Process().
m_bAbortRequest
bool CExternalPlayer::m_bAbortRequest private
Referenced by CExternalPlayer(), CloseFile(), and Process().
m_bIsPlaying
bool CExternalPlayer::m_bIsPlaying private
Referenced by CExternalPlayer(), CloseFile(), IsPlaying(), OpenFile(), and Process().
m_dialog
CGUIDialogOK* CExternalPlayer::m_dialog private
Referenced by CExternalPlayer(), CloseFile(), and Process().
m_file
CFileItem CExternalPlayer::m_file private
Referenced by OpenFile(), and Process().
m_filename
std::string CExternalPlayer::m_filename private
Referenced by Initialize(), and Process().
m_filenameReplacers
std::vector<std::string> CExternalPlayer::m_filenameReplacers private
Referenced by Initialize(), and Process().
m_hideconsole
bool CExternalPlayer::m_hideconsole private
Referenced by CExternalPlayer(), and Initialize().
m_hidexbmc
bool CExternalPlayer::m_hidexbmc private
Referenced by CExternalPlayer(), Initialize(), and Process().
m_islauncher
bool CExternalPlayer::m_islauncher private
Referenced by CExternalPlayer(), Initialize(), and Process().
m_launchFilename
std::string CExternalPlayer::m_launchFilename private
Referenced by OpenFile(), and Process().
m_playbackStartTime
std::chrono::time_point<std::chrono::steady_clock> CExternalPlayer::m_playbackStartTime private
Referenced by OpenFile(), and Process().
m_playCountMinTime
int CExternalPlayer::m_playCountMinTime private
Referenced by CExternalPlayer(), Initialize(), and Process().
m_playOneStackItem
bool CExternalPlayer::m_playOneStackItem private
Referenced by CExternalPlayer(), Initialize(), and Process().
m_speed
float CExternalPlayer::m_speed private
Referenced by CExternalPlayer(), and SetSpeed().
m_time
int CExternalPlayer::m_time private
Referenced by CExternalPlayer(), and OpenFile().
m_warpcursor
WARP_CURSOR CExternalPlayer::m_warpcursor private
Referenced by CExternalPlayer(), Initialize(), and Process().
The documentation for this class was generated from the following files:
ExternalPlayer.h
ExternalPlayer.cpp