Kodi Documentation: CNfsConnection Class Reference
CNfsConnection Class Reference
#include <NFSFile.h>
Classes
struct contextTimeout
struct keepAliveStruct
Public Types
typedef std::map< struct nfsfh *, struct keepAliveStruct > tFileKeepAliveMap
typedef std::map< std::string, struct contextTimeout > tOpenContextMap
Public Member Functions
CNfsConnection ()
~CNfsConnection ()
bool Connect (const CURL &url, std::string &relativePath)
struct nfs_context * GetNfsContext ()
uint64_t GetMaxReadChunkSize ()
uint64_t GetMaxWriteChunkSize ()
std::list< std::string > GetExportList (const CURL &url)
bool splitUrlIntoExportAndPath (const CURL &url, std::string &exportPath, std::string &relativePath, std::list< std::string > &exportList)
bool splitUrlIntoExportAndPath (const CURL &url, std::string &exportPath, std::string &relativePath)
int stat (const CURL &url, nfs_stat_64 *statbuff)
void AddActiveConnection ()
void AddIdleConnection ()
void CheckIfIdle ()
void Deinit ()
void resetKeepAlive (const std::string &_exportPath, struct nfsfh *_pFileHandle)
void removeFromKeepAliveList (struct nfsfh *_pFileHandle)
const std::string & GetConnectedIp () const
const std::string & GetConnectedExport () const
const std::string GetContextMapId () const
Private Types
enum class ContextStatus { INVALID , NEW , CACHED }
Private Member Functions
void clearMembers ()
struct nfs_context * getContextFromMap (const std::string &exportname, bool forceCacheHit=false)
ContextStatus getContextForExport (const std::string &exportname)
void destroyOpenContexts ()
void destroyContext (const std::string &exportName)
void resolveHost (const CURL &url)
void keepAlive (const std::string &_exportPath, struct nfsfh *_pFileHandle)
Static Private Member Functions
static void setOptions (struct nfs_context *context)
Private Attributes
struct nfs_context * m_pNfsContext
std::string m_exportPath
std::string m_hostName
std::string m_resolvedHostName
uint64_t m_readChunkSize = 0
uint64_t m_writeChunkSize = 0
int m_OpenConnections = 0
std::chrono::time_point< std::chrono::steady_clock > m_IdleTimeout
tFileKeepAliveMap m_KeepAliveTimeouts
tOpenContextMap m_openContextMap
std::chrono::time_point< std::chrono::steady_clock > m_lastAccessedTime
std::list< std::string > m_exportList
CCriticalSection keepAliveLock
CCriticalSection openContextLock
Member Typedef Documentation
tFileKeepAliveMap
typedef std::map<struct nfsfh *, struct keepAliveStruct> CNfsConnection::tFileKeepAliveMap
tOpenContextMap
typedef std::map<std::string, struct contextTimeout> CNfsConnection::tOpenContextMap
Member Enumeration Documentation
ContextStatus
enum class CNfsConnection::ContextStatus strong private
Enumerator
INVALID
NEW
CACHED
Constructor & Destructor Documentation
CNfsConnection()
CNfsConnection::CNfsConnection ()
~CNfsConnection()
CNfsConnection::~CNfsConnection ()
References Deinit().
Member Function Documentation
AddActiveConnection()
void CNfsConnection::AddActiveConnection ()
References m_OpenConnections.
Referenced by XFILE::CNFSDirectory::CNFSDirectory(), and XFILE::CNFSFile::CNFSFile().
AddIdleConnection()
void CNfsConnection::AddIdleConnection ()
References m_IdleTimeout, and m_OpenConnections.
Referenced by XFILE::CNFSDirectory::~CNFSDirectory(), and XFILE::CNFSFile::~CNFSFile().
CheckIfIdle()
void CNfsConnection::CheckIfIdle ()
References Deinit(), gNfsConnection, keepAlive(), keepAliveLock, CLog::Log(), LOGINFO, m_IdleTimeout, m_KeepAliveTimeouts, m_OpenConnections, m_pNfsContext, and resetKeepAlive().
Referenced by CApplication::ProcessSlow().
clearMembers()
void CNfsConnection::clearMembers () private
References m_exportPath, m_hostName, m_pNfsContext, m_readChunkSize, and m_writeChunkSize.
Referenced by Deinit(), and getContextForExport().
Connect()
bool CNfsConnection::Connect (const CURL & url, std::string & relativePath)
References destroyContext(), getContextForExport(), CURL::GetHostName(), CServiceBroker::GetSettingsComponent(), INVALID, CLog::Log(), LOGDEBUG, LOGERROR, m_exportPath, m_hostName, m_lastAccessedTime, m_pNfsContext, m_readChunkSize, m_resolvedHostName, m_writeChunkSize, NEW, resolveHost(), and splitUrlIntoExportAndPath().
Referenced by XFILE::CNFSDirectory::Create(), XFILE::CNFSFile::Delete(), XFILE::CNFSDirectory::Exists(), XFILE::CNFSDirectory::GetDirectory(), XFILE::CNFSFile::Open(), XFILE::CNFSFile::OpenForWrite(), XFILE::CNFSDirectory::Remove(), XFILE::CNFSFile::Rename(), and XFILE::CNFSFile::Stat().
Deinit()
void CNfsConnection::Deinit ()
References clearMembers(), destroyOpenContexts(), m_KeepAliveTimeouts, and m_pNfsContext.
Referenced by CheckIfIdle(), CApplication::CloseNetworkShares(), XFILE::CNFSFile::Open(), and ~CNfsConnection().
destroyContext()
void CNfsConnection::destroyContext (const std::string & exportName) private
References m_openContextMap, and openContextLock.
Referenced by Connect().
destroyOpenContexts()
void CNfsConnection::destroyOpenContexts () private
References m_openContextMap, and openContextLock.
Referenced by Deinit().
GetConnectedExport()
const std::string & CNfsConnection::GetConnectedExport () const inline
References m_exportPath.
Referenced by XFILE::CNFSDirectory::ResolveSymlink().
GetConnectedIp()
const std::string & CNfsConnection::GetConnectedIp () const inline
References m_resolvedHostName.
Referenced by XFILE::CNFSDirectory::ResolveSymlink().
getContextForExport()
CNfsConnection::ContextStatus CNfsConnection::getContextForExport (const std::string & exportname) private
References CACHED, clearMembers(), getContextFromMap(), INVALID, CNfsConnection::contextTimeout::lastAccessedTime, CLog::Log(), LOGDEBUG, LOGERROR, m_lastAccessedTime, m_openContextMap, m_pNfsContext, NEW, openContextLock, CNfsConnection::contextTimeout::pContext, and setOptions().
Referenced by Connect().
getContextFromMap()
struct nfs_context * CNfsConnection::getContextFromMap (const std::string & exportname, bool forceCacheHit = false) private
References CLog::Log(), LOGDEBUG, m_openContextMap, and openContextLock.
Referenced by getContextForExport(), keepAlive(), and resetKeepAlive().
GetContextMapId()
const std::string CNfsConnection::GetContextMapId () const inline
References m_exportPath, and m_hostName.
Referenced by XFILE::CNFSFile::Open(), and XFILE::CNFSFile::OpenForWrite().
GetExportList()
std::list< std::string > CNfsConnection::GetExportList (const CURL & url)
References CServiceBroker::GetSettingsComponent(), and m_resolvedHostName.
Referenced by XFILE::CNFSDirectory::GetDirectoryFromExportList(), and splitUrlIntoExportAndPath().
GetMaxReadChunkSize()
uint64_t CNfsConnection::GetMaxReadChunkSize () inline
References m_readChunkSize.
Referenced by XFILE::CNFSFile::GetChunkSize().
GetMaxWriteChunkSize()
uint64_t CNfsConnection::GetMaxWriteChunkSize () inline
References m_writeChunkSize.
Referenced by XFILE::CNFSFile::Write().
GetNfsContext()
struct nfs_context * CNfsConnection::GetNfsContext () inline
References m_pNfsContext.
Referenced by XFILE::CNFSDirectory::Create(), XFILE::CNFSFile::Delete(), XFILE::CNFSDirectory::Exists(), XFILE::CNFSDirectory::GetDirectory(), XFILE::CNFSFile::GetPosition(), XFILE::CNFSFile::Open(), XFILE::CNFSFile::OpenForWrite(), XFILE::CNFSDirectory::Remove(), XFILE::CNFSFile::Rename(), XFILE::CNFSDirectory::ResolveSymlink(), and XFILE::CNFSFile::Stat().
keepAlive()
void CNfsConnection::keepAlive (const std::string & _exportPath, struct nfsfh * _pFileHandle) private
References getContextFromMap(), LOGDEBUG, LOGERROR, and m_pNfsContext.
Referenced by CheckIfIdle().
removeFromKeepAliveList()
void CNfsConnection::removeFromKeepAliveList (struct nfsfh * _pFileHandle)
References keepAliveLock, and m_KeepAliveTimeouts.
Referenced by XFILE::CNFSFile::Close().
resetKeepAlive()
void CNfsConnection::resetKeepAlive (const std::string & _exportPath, struct nfsfh * _pFileHandle)
References getContextFromMap(), keepAliveLock, m_KeepAliveTimeouts, m_lastAccessedTime, and m_pNfsContext.
Referenced by CheckIfIdle(), and XFILE::CNFSFile::Read().
resolveHost()
void CNfsConnection::resolveHost (const CURL & url) private
References CURL::GetHostName(), CDNSNameCache::Lookup(), and m_resolvedHostName.
Referenced by Connect(), and stat().
setOptions()
void CNfsConnection::setOptions (struct nfs_context * context) static private
References CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, and LOGERROR.
Referenced by getContextForExport(), and stat().
splitUrlIntoExportAndPath() [1/2]
bool CNfsConnection::splitUrlIntoExportAndPath (const CURL & url, std::string & exportPath, std::string & relativePath)
References GetExportList(), CURL::GetHostName(), CServiceBroker::GetSettingsComponent(), m_exportList, m_hostName, and splitUrlIntoExportAndPath().
splitUrlIntoExportAndPath() [2/2]
bool CNfsConnection::splitUrlIntoExportAndPath (const CURL & url, std::string & exportPath, std::string & relativePath, std::list< std::string > & exportList)
References exportList, CURL::GetFileName(), and URIUtils::PathHasParent().
Referenced by Connect(), XFILE::CNFSFile::Rename(), splitUrlIntoExportAndPath(), stat(), and TEST_P().
stat()
int CNfsConnection::stat (const CURL & url, nfs_stat_64 * statbuff)
References CURL::GetHostName(), CLog::Log(), LOGDEBUG, LOGERROR, m_pNfsContext, m_resolvedHostName, resolveHost(), setOptions(), and splitUrlIntoExportAndPath().
Referenced by XFILE::CNFSDirectory::ResolveSymlink().
Member Data Documentation
keepAliveLock
CCriticalSection CNfsConnection::keepAliveLock private
Referenced by CheckIfIdle(), removeFromKeepAliveList(), and resetKeepAlive().
m_exportList
std::list<std::string> CNfsConnection::m_exportList private
Referenced by splitUrlIntoExportAndPath().
m_exportPath
std::string CNfsConnection::m_exportPath private
Referenced by clearMembers(), Connect(), GetConnectedExport(), and GetContextMapId().
m_hostName
std::string CNfsConnection::m_hostName private
Referenced by clearMembers(), Connect(), GetContextMapId(), and splitUrlIntoExportAndPath().
m_IdleTimeout
std::chrono::time_point<std::chrono::steady_clock> CNfsConnection::m_IdleTimeout private
Referenced by AddIdleConnection(), and CheckIfIdle().
m_KeepAliveTimeouts
tFileKeepAliveMap CNfsConnection::m_KeepAliveTimeouts private
Referenced by CheckIfIdle(), Deinit(), removeFromKeepAliveList(), and resetKeepAlive().
m_lastAccessedTime
std::chrono::time_point<std::chrono::steady_clock> CNfsConnection::m_lastAccessedTime private
Referenced by Connect(), getContextForExport(), and resetKeepAlive().
m_OpenConnections
int CNfsConnection::m_OpenConnections = 0 private
Referenced by AddActiveConnection(), AddIdleConnection(), and CheckIfIdle().
m_openContextMap
tOpenContextMap CNfsConnection::m_openContextMap private
Referenced by destroyContext(), destroyOpenContexts(), getContextForExport(), and getContextFromMap().
m_pNfsContext
struct nfs_context* CNfsConnection::m_pNfsContext private
Referenced by CheckIfIdle(), clearMembers(), Connect(), Deinit(), getContextForExport(), GetNfsContext(), keepAlive(), resetKeepAlive(), and stat().
m_readChunkSize
uint64_t CNfsConnection::m_readChunkSize = 0 private
Referenced by clearMembers(), Connect(), and GetMaxReadChunkSize().
m_resolvedHostName
std::string CNfsConnection::m_resolvedHostName private
Referenced by Connect(), GetConnectedIp(), GetExportList(), resolveHost(), and stat().
m_writeChunkSize
uint64_t CNfsConnection::m_writeChunkSize = 0 private
Referenced by clearMembers(), Connect(), and GetMaxWriteChunkSize().
openContextLock
CCriticalSection CNfsConnection::openContextLock private
Referenced by destroyContext(), destroyOpenContexts(), getContextForExport(), and getContextFromMap().
The documentation for this class was generated from the following files:
NFSFile.h
NFSFile.cpp