Kodi Documentation: CDVDAudioCodecFFmpeg Class Reference
CDVDAudioCodecFFmpeg Class Reference
#include <DVDAudioCodecFFmpeg.h>
Public Member Functions
CDVDAudioCodecFFmpeg (CProcessInfo &processInfo)
~CDVDAudioCodecFFmpeg () override
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
void Dispose () override
bool AddData (const DemuxPacket &packet) override
void GetData (DVDAudioFrame &frame) override
void Reset () override
AEAudioFormat GetFormat () override
std::string GetName () override
enum AVMatrixEncoding GetMatrixEncoding () override
enum AVAudioServiceType GetAudioServiceType () override
int GetProfile () override
Public Member Functions inherited from CDVDAudioCodec
CDVDAudioCodec (CProcessInfo &processInfo)
virtual ~CDVDAudioCodec ()=default
virtual bool NeedPassthrough ()
virtual int GetBufferSize ()
Protected Member Functions
int GetData (uint8_t **dst)
enum AEDataFormat GetDataFormat ()
int GetSampleRate ()
int GetChannels ()
CAEChannelInfo GetChannelMap ()
int GetBitRate () override
void BuildChannelMap ()
Protected Attributes
AEAudioFormat m_format
AVCodecContext * m_pCodecContext
enum AVSampleFormat m_iSampleFormat = AV_SAMPLE_FMT_NONE
CAEChannelInfo m_channelLayout
enum AVMatrixEncoding m_matrixEncoding = AV_MATRIX_ENCODING_NONE
AVFrame * m_pFrame
AVDownmixInfo m_downmixInfo
bool m_hasDownmix = false
bool m_eof
int m_channels
uint64_t m_layout
std::string m_codecName
uint64_t m_hint_layout
Protected Attributes inherited from CDVDAudioCodec
CProcessInfo & m_processInfo
Constructor & Destructor Documentation
CDVDAudioCodecFFmpeg()
CDVDAudioCodecFFmpeg::CDVDAudioCodecFFmpeg (CProcessInfo & processInfo) explicit
References m_channels, m_eof, m_layout, m_pCodecContext, and m_pFrame.
~CDVDAudioCodecFFmpeg()
CDVDAudioCodecFFmpeg::~CDVDAudioCodecFFmpeg () override
References Dispose().
Member Function Documentation
AddData()
bool CDVDAudioCodecFFmpeg::AddData (const DemuxPacket & packet) override virtual
Todo:
: properly handle avpkt side_data. this works around our improper use of the side_data
Implements CDVDAudioCodec.
References DEMUX_PACKET::dts, DVD_NOPTS_VALUE, DVD_TIME_BASE, int64_t(), DEMUX_PACKET::iSideDataElems, DEMUX_PACKET::iSize, CLog::Log(), LOGERROR, m_eof, m_pCodecContext, DEMUX_PACKET::pData, DEMUX_PACKET::pSideData, DEMUX_PACKET::pts, and Reset().
BuildChannelMap()
void CDVDAudioCodecFFmpeg::BuildChannelMap () protected
References AE_CH_BC, AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, AE_CH_TFR, count_bits(), int64_t(), CLog::Log(), LOGINFO, m_channelLayout, m_channels, m_hint_layout, m_layout, m_pCodecContext, and CAEChannelInfo::Reset().
Referenced by GetChannelMap().
Dispose()
void CDVDAudioCodecFFmpeg::Dispose () override virtual
Implements CDVDAudioCodec.
References m_pCodecContext, and m_pFrame.
Referenced by Open(), and ~CDVDAudioCodecFFmpeg().
GetAudioServiceType()
enum AVAudioServiceType CDVDAudioCodecFFmpeg::GetAudioServiceType () override virtual
Reimplemented from CDVDAudioCodec.
References m_pCodecContext.
Referenced by GetData().
GetBitRate()
int CDVDAudioCodecFFmpeg::GetBitRate () override protected virtual
Reimplemented from CDVDAudioCodec.
References m_pCodecContext.
GetChannelMap()
CAEChannelInfo CDVDAudioCodecFFmpeg::GetChannelMap () protected
References BuildChannelMap(), and m_channelLayout.
Referenced by GetData().
GetChannels()
int CDVDAudioCodecFFmpeg::GetChannels () protected
References m_pCodecContext.
GetData() [1/2]
void CDVDAudioCodecFFmpeg::GetData (DVDAudioFrame & frame) override virtual
Implements CDVDAudioCodec.
References AE_IS_PLANAR, stDVDAudioFrame::audio_service_type, stDVDAudioFrame::bits_per_sample, stDVDAudioFrame::centerMixLevel, CAEChannelInfo::Count(), data(), stDVDAudioFrame::data, CAEUtil::DataFormatToBits(), stDVDAudioFrame::duration, DVD_NOPTS_VALUE, DVD_TIME_BASE, stDVDAudioFrame::format, stDVDAudioFrame::framesize, stDVDAudioFrame::framesOut, GetAudioServiceType(), GetData(), GetMatrixEncoding(), GetProfile(), stDVDAudioFrame::hasDownmix, int64_t(), AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, m_downmixInfo, m_format, m_hasDownmix, m_pFrame, AEAudioFormat::m_sampleRate, stDVDAudioFrame::matrix_encoding, stDVDAudioFrame::nb_frames, stDVDAudioFrame::passthrough, stDVDAudioFrame::planes, stDVDAudioFrame::profile, and stDVDAudioFrame::pts.
Referenced by GetData().
GetData() [2/2]
int CDVDAudioCodecFFmpeg::GetData (uint8_t ** dst) protected
References CAEChannelInfo::Count(), CAEUtil::DataFormatToBits(), GetChannelMap(), GetDataFormat(), GetSampleRate(), AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, m_downmixInfo, m_format, AEAudioFormat::m_frameSize, m_hasDownmix, m_matrixEncoding, m_pCodecContext, m_pFrame, and AEAudioFormat::m_sampleRate.
GetDataFormat()
enum AEDataFormat CDVDAudioCodecFFmpeg::GetDataFormat () protected
References AE_FMT_DOUBLE, AE_FMT_DOUBLEP, AE_FMT_FLOAT, AE_FMT_FLOATP, AE_FMT_INVALID, AE_FMT_S16NE, AE_FMT_S16NEP, AE_FMT_S32NE, AE_FMT_S32NEP, AE_FMT_U8, AE_FMT_U8P, CLog::Log(), LOGERROR, and m_pCodecContext.
Referenced by GetData().
GetFormat()
AEAudioFormat CDVDAudioCodecFFmpeg::GetFormat () inline override virtual
Implements CDVDAudioCodec.
References m_format.
GetMatrixEncoding()
enum AVMatrixEncoding CDVDAudioCodecFFmpeg::GetMatrixEncoding () override virtual
Reimplemented from CDVDAudioCodec.
References m_matrixEncoding.
Referenced by GetData().
GetName()
std::string CDVDAudioCodecFFmpeg::GetName () inline override virtual
Implements CDVDAudioCodec.
References m_codecName.
GetProfile()
int CDVDAudioCodecFFmpeg::GetProfile () override virtual
Reimplemented from CDVDAudioCodec.
References m_pCodecContext.
Referenced by GetData().
GetSampleRate()
int CDVDAudioCodecFFmpeg::GetSampleRate () protected
References m_pCodecContext.
Referenced by GetData().
Open()
bool CDVDAudioCodecFFmpeg::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Implements CDVDAudioCodec.
References CDVDStreamInfo::bitrate, CDVDStreamInfo::bitspersample, CDVDStreamInfo::blockalign, CDVDStreamInfo::channellayout, CDVDStreamInfo::channels, CDVDStreamInfo::codec, CDVDStreamInfo::cryptoSession, Dispose(), CDVDStreamInfo::extradata, FFmpegExtraData::GetData(), CServiceBroker::GetSettingsComponent(), FFmpegExtraData::GetSize(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_channels, m_codecName, m_hasDownmix, m_hint_layout, m_iSampleFormat, m_matrixEncoding, m_pCodecContext, m_pFrame, and CDVDStreamInfo::samplerate.
Reset()
void CDVDAudioCodecFFmpeg::Reset () override virtual
Implements CDVDAudioCodec.
References m_eof, and m_pCodecContext.
Referenced by AddData().
Member Data Documentation
m_channelLayout
CAEChannelInfo CDVDAudioCodecFFmpeg::m_channelLayout protected
Referenced by BuildChannelMap(), and GetChannelMap().
m_channels
int CDVDAudioCodecFFmpeg::m_channels protected
Referenced by BuildChannelMap(), CDVDAudioCodecFFmpeg(), and Open().
m_codecName
std::string CDVDAudioCodecFFmpeg::m_codecName protected
Referenced by GetName(), and Open().
m_downmixInfo
AVDownmixInfo CDVDAudioCodecFFmpeg::m_downmixInfo protected
Referenced by GetData(), and GetData().
m_eof
bool CDVDAudioCodecFFmpeg::m_eof protected
Referenced by AddData(), CDVDAudioCodecFFmpeg(), and Reset().
m_format
AEAudioFormat CDVDAudioCodecFFmpeg::m_format protected
Referenced by GetData(), GetData(), and GetFormat().
m_hasDownmix
bool CDVDAudioCodecFFmpeg::m_hasDownmix = false protected
Referenced by GetData(), GetData(), and Open().
m_hint_layout
uint64_t CDVDAudioCodecFFmpeg::m_hint_layout protected
Referenced by BuildChannelMap(), and Open().
m_iSampleFormat
enum AVSampleFormat CDVDAudioCodecFFmpeg::m_iSampleFormat = AV_SAMPLE_FMT_NONE protected
Referenced by Open().
m_layout
uint64_t CDVDAudioCodecFFmpeg::m_layout protected
Referenced by BuildChannelMap(), and CDVDAudioCodecFFmpeg().
m_matrixEncoding
enum AVMatrixEncoding CDVDAudioCodecFFmpeg::m_matrixEncoding = AV_MATRIX_ENCODING_NONE protected
Referenced by GetData(), GetMatrixEncoding(), and Open().
m_pCodecContext
AVCodecContext* CDVDAudioCodecFFmpeg::m_pCodecContext protected
Referenced by AddData(), BuildChannelMap(), CDVDAudioCodecFFmpeg(), Dispose(), GetAudioServiceType(), GetBitRate(), GetChannels(), GetData(), GetDataFormat(), GetProfile(), GetSampleRate(), Open(), and Reset().
m_pFrame
AVFrame* CDVDAudioCodecFFmpeg::m_pFrame protected
Referenced by CDVDAudioCodecFFmpeg(), Dispose(), GetData(), GetData(), and Open().
The documentation for this class was generated from the following files:
DVDAudioCodecFFmpeg.h
DVDAudioCodecFFmpeg.cpp