Kodi Documentation: CApplication Class Reference
CApplication Class Reference
#include <Application.h>
Public Member Functions
CApplication (void)
~CApplication (void) override
bool Create ()
bool Initialize ()
int Run ()
bool Cleanup ()
void FrameMove (bool processEvents, bool processGUI=true) override
void Render () override
bool IsInitialized () const
bool IsStopping () const
bool CreateGUI ()
bool InitWindow (RESOLUTION res=RES_INVALID)
bool Stop (int exitCode)
const std::string & CurrentFile ()
CFileItem & CurrentFileItem ()
std::shared_ptr< CFileItem > CurrentFileItemPtr ()
const CFileItem & CurrentUnstackedItem ()
bool OnMessage (CGUIMessage &message) override
std::string GetCurrentPlayer ()
int GetMessageMask () override
Should return the message mask that it wishes to receive messages for.
void OnApplicationMessage (KODI::MESSAGING::ThreadMessage *pMsg) override
This gets called whenever a message matching the registered message mask is processed.
bool PlayMedia (CFileItem &item, const std::string &player, KODI::PLAYLIST::Id playlistId)
bool ProcessAndStartPlaylist (const std::string &strPlayList, KODI::PLAYLIST::CPlayList &playlist, KODI::PLAYLIST::Id playlistId, int track=0)
bool PlayFile (CFileItem item, const std::string &player, bool bRestart=false, bool forceSelection=false)
void StopPlaying ()
void Restart (bool bSamePosition=true)
void DelayedPlayerRestart ()
void CheckDelayedPlayerRestart ()
bool IsPlayingFullScreenVideo () const
bool IsFullScreen ()
bool OnAction (const CAction &action)
void CloseNetworkShares ()
void ConfigureAndEnableAddons ()
void ShowAppMigrationMessage ()
void Process () override
void ProcessSlow ()
double GetTotalTime () const
Returns the total time in fractional seconds of the currently playing media.
double GetTime () const
Returns the current time in fractional seconds of the currently playing media.
float GetPercentage () const
float GetCachePercentage () const
void SeekPercentage (float percent)
void SeekTime (double dTime=0.0)
void UpdateLibraries ()
void UpdateCurrentPlayArt ()
bool ExecuteXBMCAction (std::string action, const std::shared_ptr< CGUIListItem > &item=NULL)
bool IsAppFocused () const
bool GetRenderGUI () const override
bool SetLanguage (const std::string &strLanguage)
bool LoadLanguage (bool reload)
void SetLoggingIn (bool switchingProfiles)
void LockFrameMoveGuard ()
Locks calls from outside kodi (e.g. python) until framemove is processed.
void UnlockFrameMoveGuard ()
Unlocks calls from outside kodi (e.g. python).
Public Member Functions inherited from IWindowManagerCallback
IWindowManagerCallback (void)
virtual ~IWindowManagerCallback (void)
Public Member Functions inherited from IMsgTargetCallback
virtual ~IMsgTargetCallback ()=default
Public Member Functions inherited from KODI::MESSAGING::IMessageTarget
virtual ~IMessageTarget ()=default
Public Member Functions inherited from CComponentContainer< BaseType >
template<class T >
std::shared_ptr< T > GetComponent ()
Obtain a component.
template<class T >
std::shared_ptr< const T > GetComponent () const
Obtain a component.
std::size_t size () const
Returns number of registered components.
Public Member Functions inherited from CApplicationPlayerCallback
CApplicationPlayerCallback ()
void OnPlayBackEnded () override
void OnPlayBackStarted (const CFileItem &file) override
void OnPlayerCloseFile (const CFileItem &file, const CBookmark &bookmark) override
void OnPlayBackPaused () override
void OnPlayBackResumed () override
void OnPlayBackStopped () override
void OnPlayBackError () override
void OnQueueNextItem () override
void OnPlayBackSeek (int64_t iTime, int64_t seekOffset) override
void OnPlayBackSeekChapter (int iChapter) override
void OnPlayBackSpeedChanged (int iSpeed) override
void OnAVChange () override
void OnAVStarted (const CFileItem &file) override
void RequestVideoSettings (const CFileItem &fileItem) override
void StoreVideoSettings (const CFileItem &fileItem, const CVideoSettings &vs) override
Public Member Functions inherited from IPlayerCallback
virtual ~IPlayerCallback ()=default
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual void OnSettingsLoaded ()
Settings have been loaded.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsUnloaded ()
Setting values have been unloaded.
virtual void OnSettingsCleared ()
Settings have been cleared.
Public Member Functions inherited from ISubSettings
virtual ~ISubSettings ()=default
virtual void Clear ()
Clear any loaded setting values.
Public Attributes
std::string m_strPlayListFile
std::unique_ptr< CServiceManager > m_ServiceManager
bool m_bStop {false}
bool m_AppFocused {true}
Static Public Attributes
static const unsigned int ACTION_PREV_ITEM_THRESHOLD = 3
Protected Member Functions
bool OnSettingsSaving () const override
Settings saving has been initiated.
void PlaybackCleanup ()
bool PlayStack (CFileItem &item, bool bRestart)
Protected Member Functions inherited from CComponentContainer< BaseType >
void RegisterComponent (const std::shared_ptr< BaseType > &component)
Register a new component instance.
void DeregisterComponent (const std::type_info &typeInfo)
Deregister a component.
Protected Member Functions inherited from CApplicationSettingsHandling
void RegisterSettings ()
void UnregisterSettings ()
bool Load (const TiXmlNode *settings) override
Load settings from the given XML node.
bool Save (TiXmlNode *settings) const override
Save settings to the given XML node.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode) override
The given setting needs to be updated.
Protected Attributes
std::shared_ptr< ANNOUNCEMENT::CAnnouncementManager > m_pAnnouncementManager
std::unique_ptr< CGUIComponent > m_pGUI
std::unique_ptr< CWinSystemBase > m_pWinSystem
std::unique_ptr< ActiveAE::CActiveAE > m_pActiveAE
std::shared_ptr< CAppInboundProtocol > m_pAppPort
CStopWatch m_restartPlayerTimer
CStopWatch m_frameTime
CStopWatch m_slowTimer
XbmcThreads::EndTime m_guiRefreshTimer
std::string m_prevMedia
bool m_bInitializing = true
int m_nextPlaylistItem = -1
std::chrono::time_point< std::chrono::steady_clock > m_lastRenderTime
bool m_skipGuiRender = false
std::unique_ptr< MUSIC_INFO::CMusicInfoScanner > m_musicInfoScanner
std::unique_ptr< CInertialScrollingHandler > m_pInertialScrollingHandler
std::vector< std::shared_ptr< ADDON::CAddonInfo > > m_incompatibleAddons
Private Member Functions
void PrintStartupLog ()
void ResetCurrentItem ()
Private Attributes
CCriticalSection m_critSection
CCriticalSection m_frameMoveGuard
std::atomic_uint m_WaitingExternalCalls
unsigned int m_ProcessedExternalCalls = 0
unsigned int m_ProcessedExternalDecay = 0
int m_ExitCode {EXITCODE_QUIT}
std::shared_ptr< CFileItem > m_itemCurrentFile
Currently playing file.
CEvent m_playerEvent
Constructor & Destructor Documentation
CApplication()
CApplication::CApplication (void)
References m_bInitializing, m_critSection, and CComponentContainer< BaseType >::RegisterComponent().
~CApplication()
CApplication::~CApplication (void) override
References CComponentContainer< BaseType >::DeregisterComponent().
Member Function Documentation
CheckDelayedPlayerRestart()
void CApplication::CheckDelayedPlayerRestart ()
References CStopWatch::GetElapsedSeconds(), m_restartPlayerTimer, CStopWatch::Reset(), Restart(), and CStopWatch::Stop().
Referenced by ProcessSlow().
Cleanup()
bool CApplication::Cleanup ()
References XFILE::CDirectoryCache::Clear(), CLocalizeStrings::Clear(), KODI::PLAYLIST::CPlayListPlayer::Clear(), CLangCodeExpander::Clear(), CRenderSystemBase::DestroyRenderSystem(), CWinSystemBase::DestroyWindow(), CWinSystemBase::DestroyWindowSystem(), CXHandle::DumpObjectTracker(), g_charsetConverter, g_directoryCache, g_LangCodeExpander, g_localizeStrings, CScriptInvocationManager::GetInstance(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetRenderSystem(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGERROR, LOGINFO, m_bInitializing, m_pAnnouncementManager, m_pGUI, m_pWinSystem, m_ServiceManager, EVENTSERVER::CEventServer::RemoveInstance(), ResetCurrentItem(), StopPlaying(), CScriptInvocationManager::Uninitialize(), CServiceBroker::UnregisterAnnouncementManager(), CServiceBroker::UnregisterAppMessenger(), CServiceBroker::UnregisterCPUInfo(), CServiceBroker::UnregisterJobManager(), CServiceBroker::UnregisterKeyboardLayoutManager(), CApplicationSettingsHandling::UnregisterSettings(), CServiceBroker::UnregisterSpeechRecognition(), CServiceBroker::UnregisterTextureCache(), and CServiceBroker::UnregisterWinSystem().
Referenced by Run().
CloseNetworkShares()
void CApplication::CloseNetworkShares ()
References CNfsConnection::Deinit(), CSMB::Deinit(), ADDON::CVFSAddonCache::GetAddonInstances(), CServiceBroker::GetVFSAddonCache(), gNfsConnection, CLog::Log(), LOGDEBUG, and smb.
ConfigureAndEnableAddons()
void CApplication::ConfigureAndEnableAddons ()
< Installed addons, but not auto-enabled via manifest
References CServiceBroker::GetAddonMgr(), ADDON::INCOMPATIBLE, ADDON::CAddonType::IsDependencyType(), CLog::Log(), LOGDEBUG, m_ServiceManager, ADDON::NONE, CGUIDialogAddonSettings::ShowForAddon(), KODI::MESSAGING::HELPERS::ShowYesNoDialogLines(), and ADDON::USER.
Referenced by OnMessage().
Create()
bool CApplication::Create ()
Todo:
Win32 has no special://home/ mapping by default, so we
References CUtil::CopyUserDataIfNeeded(), XFILE::CDirectory::Create(), XFILE::CFile::Exists(), ff_avutil_log(), CServiceBroker::GetAppParams(), CCPUInfo::GetCPUInfo(), CThread::GetCurrentThreadId(), CServiceBroker::GetLogging(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetSettingsComponent(), init_emu_environ(), CLog::Initialize(), CUtil::InitRandomSeed(), CLog::Log(), LOGDEBUG, LOGFATAL, LOGINFO, m_bStop, m_lastRenderTime, m_pActiveAE, m_pAnnouncementManager, m_pAppPort, m_ServiceManager, PrintStartupLog(), CServiceBroker::RegisterAE(), CServiceBroker::RegisterAnnouncementManager(), CServiceBroker::RegisterAppMessenger(), CServiceBroker::RegisterAppPort(), CServiceBroker::RegisterCPUInfo(), CServiceBroker::RegisterJobManager(), CServiceBroker::RegisterKeyboardLayoutManager(), CApplicationSettingsHandling::RegisterSettings(), CEnvironment::setenv(), CSettings::SETTING_AUDIOCDS_RECORDINGPATH, CSettings::SETTING_DEBUG_SCREENSHOTPATH, CSettings::SETTING_FILECACHE_BUFFERMODE, CSettings::SETTING_FILECACHE_CHUNKSIZE, CSettings::SETTING_FILECACHE_MEMORYSIZE, CSettings::SETTING_FILECACHE_READFACTOR, CSpecialProtocol::TranslatePath(), and update_emu_environ().
CreateGUI()
bool CApplication::CreateGUI ()
References KODI::WINDOWING::CWindowSystemFactory::CreateWindowSystem(), CServiceBroker::GetAppParams(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetInputManager(), CDisplaySettings::GetInstance(), CServiceBroker::GetRenderSystem(), CGraphicContext::GetResInfo(), CServiceBroker::GetSettingsComponent(), KODI::WINDOWING::CWindowSystemFactory::GetWindowSystems(), CServiceBroker::GetWinSystem(), InitWindow(), CLog::Log(), LOGDEBUG, LOGERROR, LOGFATAL, LOGINFO, m_frameMoveGuard, m_pGUI, m_pWinSystem, CServiceBroker::RegisterWinSystem(), RES_DESKTOP, RES_WINDOW, CDisplaySettings::SetCurrentResolution(), CSettings::SETTING_SCREENSAVER_MODE, CSettings::SETTING_WINDOW_HEIGHT, CSettings::SETTING_WINDOW_WIDTH, CWinSystemBase::SetWindowResolution(), CRenderSystemBase::ShowSplash(), and CServiceBroker::UnregisterWinSystem().
CurrentFile()
const std::string & CApplication::CurrentFile ()
References m_itemCurrentFile.
CurrentFileItem()
CFileItem & CApplication::CurrentFileItem ()
References m_itemCurrentFile.
Referenced by OnAction(), and ProcessSlow().
CurrentFileItemPtr()
std::shared_ptr< CFileItem > CApplication::CurrentFileItemPtr ()
References m_itemCurrentFile.
CurrentUnstackedItem()
const CFileItem & CApplication::CurrentUnstackedItem ()
References m_itemCurrentFile.
DelayedPlayerRestart()
void CApplication::DelayedPlayerRestart ()
References m_restartPlayerTimer, and CStopWatch::StartZero().
ExecuteXBMCAction()
bool CApplication::ExecuteXBMCAction (std::string action, const std::shared_ptr< CGUIListItem > & item = NULL)
References INFO::DEFAULT_CONTEXT, CBuiltins::Execute(), CScriptInvocationManager::ExecuteAsync(), CBuiltins::GetInstance(), CScriptInvocationManager::GetInstance(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetItemLabel(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), CFileItem::GetPath(), CServiceBroker::GetPVRManager(), KODI::MUSIC::IsAudio(), CFileItem::IsGame(), CFileItem::IsPythonScript(), LOGDEBUG, OnAction(), PlayFile(), and KODI::ACTION::CActionTranslator::TranslateString().
Referenced by OnMessage().
FrameMove()
void CApplication::FrameMove (bool processEvents, bool processGUI = true) override virtual
Todo:
look into the possibility to use this for GBM int fps = 0;
This code reduces rendering fps of the GUI layer when playing videos in fullscreen mode it makes only sense on architectures with multiple layers if (CServiceBroker::GetWinSystem()->GetGfxContext().IsFullScreenVideo() && !m_appPlayer.IsPausedPlayback() && m_appPlayer.IsRenderingVideoLayer()) fps = CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(CSettings::SETTING_VIDEOPLAYER_LIMITGUIUPDATE);
auto now = std::chrono::steady_clock::now();
auto frameTime = std::chrono::duration_cast<std::chrono::milliseconds>(now - m_lastRenderTime).count(); if (fps > 0 && frameTime * fps < 1000) m_skipGuiRender = true;
Implements IWindowManagerCallback.
References CGUIDialogKaiToast::DoWork(), CWinSystemBase::DriveRenderLoop(), CGUIWindowManager::FrameMove(), CStopWatch::GetElapsedSeconds(), CTimeUtils::GetFrameTime(), CServiceBroker::GetGUI(), CServiceBroker::GetInputManager(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), GUI_MSG_REFRESH_TIMER, CGUIDialog::IsDialogRunning(), m_bStop, m_frameMoveGuard, m_frameTime, m_guiRefreshTimer, m_pAppPort, m_pInertialScrollingHandler, m_ProcessedExternalCalls, m_ProcessedExternalDecay, m_skipGuiRender, m_WaitingExternalCalls, CGUIDialog::Open(), CInputManager::Process(), CGUIWindowManager::Process(), CGUIWindowManager::SendMessage(), KODI::TIME::Sleep(), CStopWatch::StartZero(), and WINDOW_DIALOG_KAI_TOAST.
Referenced by Run().
GetCachePercentage()
float CApplication::GetCachePercentage () const
References GetPercentage(), and GetTotalTime().
GetCurrentPlayer()
std::string CApplication::GetCurrentPlayer ()
GetMessageMask()
int CApplication::GetMessageMask () override virtual
Should return the message mask that it wishes to receive messages for.
The message mask is defined in "messaging/ApplicationMessenger.h" pick the next one available when creating a new
Implements KODI::MESSAGING::IMessageTarget.
References TMSG_MASK_APPLICATION.
GetPercentage()
float CApplication::GetPercentage () const
References GetTime(), GetTotalTime(), and m_itemCurrentFile.
Referenced by GetCachePercentage().
GetRenderGUI()
bool CApplication::GetRenderGUI () const override virtual
Reimplemented from IWindowManagerCallback.
GetTime()
double CApplication::GetTime () const
Returns the current time in fractional seconds of the currently playing media.
Beware that this method returns fractional seconds whereas IPlayer::GetTime() returns milliseconds.
Referenced by GetPercentage(), OnAction(), and Restart().
GetTotalTime()
double CApplication::GetTotalTime () const
Returns the total time in fractional seconds of the currently playing media.
Beware that this method returns fractional seconds whereas IPlayer::GetTotalTime() returns milliseconds.
Referenced by GetCachePercentage(), GetPercentage(), and SeekPercentage().
Initialize()
bool CApplication::Initialize ()
Todo:
Move GUIFontManager into service broker and drop the global reference
References CGUIWindowManager::ActivateWindow(), ADDON::AUTO_UPDATES_ON, Basic, CGUIPassword::CheckStartUpLock(), speech::ISpeechRecognition::CreateInstance(), CGUIWindowManager::CreateWindows(), ADDON::CAddonMgr::DisableIncompatibleAddons(), g_fontManager, g_localizeStrings, g_passwordManager, g_SkinInfo, g_sysinfo, CLocalizeStrings::Get(), CServiceBroker::GetActiveAE(), CServiceBroker::GetAddonMgr(), CSysInfo::GetAppName(), CServiceBroker::GetGUI(), ADDON::CAddonSystemSettings::GetInstance(), CPlayerController::GetInstance(), CServiceBroker::GetJobManager(), CServiceBroker::GetMediaManager(), CServiceBroker::GetRenderSystem(), CServiceBroker::GetRepositoryUpdater(), CServiceBroker::GetServiceAddons(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UI_READY, CDatabaseManager::Initialize(), GUIFontManager::Initialize(), JSONRPC::CJSONRPC::Initialize(), CDatabaseManager::IsUpgrading(), LoadLanguage(), CMediaManager::LoadSources(), LOCK_MODE_EVERYONE, CLog::Log(), LOGERROR, LOGFATAL, LOGINFO, LOGWARNING, m_incompatibleAddons, m_pActiveAE, m_ServiceManager, m_slowTimer, ADDON::CAddonMgr::MigrateAddons(), CJob::PRIORITY_DEDICATED, CInfoLoader::Refresh(), CServiceBroker::RegisterSpeechRecognition(), CServiceBroker::RegisterTextureCache(), CUtil::RemoveTempFiles(), SetLoggingIn(), IAE::SetMute(), CSettings::SETTING_LOOKANDFEEL_SKIN, CSettings::SETTING_MASTERLOCK_STARTUPLOCK, CRenderSystemBase::ShowSplash(), ADDON::CRepositoryUpdater::Start(), ADDON::CServiceAddonManager::Start(), CStopWatch::StartZero(), UpdateLibraries(), CEvent::Wait(), WINDOW_LOGIN_SCREEN, WINDOW_SPLASH, and WINDOW_STARTUP_ANIM.
InitWindow()
bool CApplication::InitWindow (RESOLUTION res = RES_INVALID)
References CSysInfo::GetAppName(), CDisplaySettings::GetCurrentResolution(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CServiceBroker::GetRenderSystem(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGFATAL, RES_INVALID, RES_WINDOW, and CGraphicContext::SetVideoResolution().
Referenced by CreateGUI(), and OnApplicationMessage().
IsAppFocused()
bool CApplication::IsAppFocused () const inline
References m_AppFocused.
IsFullScreen()
bool CApplication::IsFullScreen ()
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), IsPlayingFullScreenVideo(), WINDOW_SLIDESHOW, and WINDOW_VISUALISATION.
IsInitialized()
bool CApplication::IsInitialized () const inline
References m_bInitializing.
IsPlayingFullScreenVideo()
bool CApplication::IsPlayingFullScreenVideo () const
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), and CGraphicContext::IsFullScreenVideo().
Referenced by IsFullScreen().
IsStopping()
bool CApplication::IsStopping () const inline
References m_bStop.
LoadLanguage()
bool CApplication::LoadLanguage (bool reload)
References g_langInfo, CServiceBroker::GetSettingsComponent(), CSettings::SETTING_LOCALE_AUDIOLANGUAGE, and CSettings::SETTING_LOCALE_SUBTITLELANGUAGE.
Referenced by Initialize().
LockFrameMoveGuard()
void CApplication::LockFrameMoveGuard ()
Locks calls from outside kodi (e.g. python) until framemove is processed.
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), m_frameMoveGuard, m_ProcessedExternalCalls, and m_WaitingExternalCalls.
OnAction()
bool CApplication::OnAction (const CAction & action)
References ACTION_ANALOG_FORWARD, ACTION_ANALOG_REWIND, ACTION_BUILT_IN_FUNCTION, ACTION_CHANNEL_DOWN, ACTION_CHANNEL_UP, ACTION_CREATE_BOOKMARK, ACTION_CREATE_EPISODE_BOOKMARK, ACTION_CYCLE_TONEMAP_METHOD, ACTION_DECREASE_RATING, ACTION_GUIPROFILE_BEGIN, ACTION_HDR_TOGGLE, ACTION_INCREASE_RATING, ACTION_MUTE, ACTION_NEXT_ITEM, ACTION_PAUSE, ACTION_PLAYER_DECREASE_TEMPO, ACTION_PLAYER_FORWARD, ACTION_PLAYER_INCREASE_TEMPO, ACTION_PLAYER_PLAY, ACTION_PLAYER_PLAYPAUSE, ACTION_PLAYER_REWIND, ACTION_PREV_ITEM, ACTION_PREV_ITEM_THRESHOLD, ACTION_RELOAD_KEYMAPS, ACTION_SET_RATING, ACTION_SHOW_GUI, ACTION_SHOW_INFO, ACTION_SHOW_PLAYLIST, ACTION_STOP, ACTION_SWITCH_PLAYER, ACTION_TAKE_SCREENSHOT, ACTION_TOGGLE_DIGITAL_ANALOG, ACTION_TOGGLE_FULLSCREEN, ACTION_VOLUME_DOWN, ACTION_VOLUME_SET, ACTION_VOLUME_UP, CGUIWindowManager::ActivateWindow(), CPlayerUtils::AdvanceTempoStep(), PVR::CPVRGUIActionsPowerManagement::CanSystemPowerdown(), CDatabase::Close(), CUtil::ConvertSecsToMilliSecs(), CurrentFileItem(), DECREASE, CGUIAudioManager::Enable(), CBuiltins::Execute(), g_localizeStrings, PVR::CPVRManager::Get(), CLocalizeStrings::Get(), CGUIComponent::GetAudioManager(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CServiceBroker::GetInputManager(), CBuiltins::GetInstance(), CXBMCApp::GetMaxSystemVolume(), CServiceBroker::GetPeripherals(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetPlayerInfoProvider(), CPlayerCoreFactory::GetPlayers(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetPVRManager(), CPlayerCoreFactory::GetRemotePlayers(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetSlideShowDelegator(), GetTime(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_ITEM, GUI_MSG_WINDOW_INIT, HDR_OFF, HDR_ON, INCREASE, CGUIDialogKaiToast::Info, CSlideShowDelegator::InSlideShow(), CGUIControlProfiler::Instance(), CWinSystemBase::IsHDRDisplaySettingEnabled(), CSlideShowDelegator::IsPaused(), CFileItem::IsPVRChannel(), PVR::CPVRManager::IsStarted(), CLog::Log(), LOGDEBUG, m_itemCurrentFile, m_pInertialScrollingHandler, m_ServiceManager, CVideoSettings::m_ToneMapMethod, MAX_FFWD_SPEED, OnAction(), CGUIDialogVideoBookmarks::OnAddBookmark(), CGUIDialogVideoBookmarks::OnAddEpisodeBookmark(), CVideoDatabase::Open(), PlayFile(), CGUIDialogKaiToast::QueueNotification(), CInputManager::ReloadKeymaps(), SeekTime(), CPlayerCoreFactory::SelectPlayerDialog(), CGUIWindowManager::SendMessage(), CGUIInfoManager::SetCurrentItem(), CInputManager::SetMouseActive(), CGUIControlProfiler::SetOutputFile(), CFileItem::SetStartOffset(), CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_VOLUMESTEPS, CVideoDatabase::SetVideoUserRating(), MUSIC_UTILS::ShowSelectRatingDialog(), CGUIControlProfiler::Start(), StopPlaying(), CGUIWindowManager::SwitchToFullScreen(), CScreenShot::TakeScreenshot(), CGraphicContext::ToggleFullScreen(), CWinSystemBase::ToggleHDR(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::ToggleShowInfo(), CSpecialProtocol::TranslatePath(), MUSIC_UTILS::UpdateSongRatingJob(), CApplicationVolumeHandling::VOLUME_MAXIMUM, CApplicationVolumeHandling::VOLUME_MINIMUM, VS_TONEMAPMETHOD_ACES, VS_TONEMAPMETHOD_HABLE, VS_TONEMAPMETHOD_MAX, VS_TONEMAPMETHOD_OFF, VS_TONEMAPMETHOD_REINHARD, WINDOW_DIALOG_MUSIC_OSD, WINDOW_DIALOG_VIDEO_OSD, WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, WINDOW_INVALID, WINDOW_MUSIC_PLAYLIST, WINDOW_SETTINGS_SYSTEM, WINDOW_VIDEO_PLAYLIST, and WINDOW_VISUALISATION.
Referenced by ExecuteXBMCAction(), CAppInboundProtocol::HandleEvents(), and OnAction().
OnApplicationMessage()
void CApplication::OnApplicationMessage (KODI::MESSAGING::ThreadMessage * msg) override virtual
This gets called whenever a message matching the registered message mask is processed.
There are no ordering guarantees here so implementations should never rely on a certain ordering of messages.
Cleaning up any pointers stored in the message payload is not specified and is decided by the implementer of the message. In general prefer to delete any data in this method to keep the callsites cleaner and simpler but if data is to be passed back it's perfectly valid to handle it any way that fits the situation as long as it's documented along with the message.
To return a simple value the result parameter of
See also
ThreadMessage can be used as it will be used as the return value for
CApplicationMessenger::SendMsg. It is up to the implementer to decide if this is to be used and it should be documented along with any new message implemented.
Implements KODI::MESSAGING::IMessageTarget.
References CGUIWindowManager::ActivateWindow(), CSlideShowDelegator::Add(), URIUtils::CreateArchivePath(), CWinSystemBase::DestroyWindow(), XFILE::DIR_FLAG_NO_FILE_DIRS, KODI::MESSAGING::ThreadMessage::dwMessage, CBuiltins::Execute(), CScriptInvocationManager::ExecuteAsync(), EXITCODE_POWERDOWN, EXITCODE_QUIT, EXITCODE_REBOOT, EXITCODE_RESTARTAPP, CURL::Get(), CServiceBroker::GetActiveAE(), CServiceBroker::GetFileExtensionProvider(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CBuiltins::GetInstance(), CScriptInvocationManager::GetInstance(), CFileExtensionProvider::GetPictureExtensions(), CServiceBroker::GetPowerManager(), CServiceBroker::GetPVRManager(), CUtil::GetRecursiveListing(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetSlideShowDelegator(), CGraphicContext::GetVideoResolution(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), XBMC_ResizeEvent::h, CPowerManager::Hibernate(), InitWindow(), URIUtils::IsRAR(), URIUtils::IsZIP(), CLog::Log(), LOGERROR, LOGFATAL, LOGINFO, KODI::MESSAGING::ThreadMessage::lpVoid, m_itemCurrentFile, m_pAppPort, m_ServiceManager, CGUIWindowManager::MarkDirty(), CWinSystemBase::Minimize(), CWinSystemBase::MoveToScreen(), KODI::MESSAGING::ThreadMessage::param1, KODI::MESSAGING::ThreadMessage::param2, KODI::MESSAGING::ThreadMessage::param3, KODI::MESSAGING::ThreadMessage::params, CPowerManager::Powerdown(), CGUIWindowManager::PreviousWindow(), CPowerManager::Reboot(), CSlideShowDelegator::Reset(), XBMC_Event::resize, IAE::Resume(), CSlideShowDelegator::Select(), SetLanguage(), CSettings::SETTING_SCREENSAVER_MODE, CGraphicContext::SetVideoResolution(), CFileItemList::Size(), CXBMCApp::StartActivity(), CSlideShowDelegator::StartSlideShow(), Stop(), StopPlaying(), KODI::MESSAGING::ThreadMessage::strParam, CPowerManager::Suspend(), IAE::Suspend(), CGUIWindowManager::SwitchToFullScreen(), TMSG_ACTIVATESCREENSAVER, TMSG_DISPLAY_DESTROY, TMSG_DISPLAY_SETUP, TMSG_EVENT, TMSG_EXECUTE_BUILT_IN, TMSG_EXECUTE_OS, TMSG_EXECUTE_SCRIPT, TMSG_HIBERNATE, TMSG_INHIBITIDLESHUTDOWN, TMSG_INHIBITSCREENSAVER, TMSG_LOADPROFILE, TMSG_MINIMIZE, TMSG_MOVETOSCREEN, TMSG_NETWORKMESSAGE, TMSG_PICTURE_SHOW, TMSG_PICTURE_SLIDESHOW, TMSG_POWERDOWN, TMSG_QUIT, TMSG_RENDERER_FLUSH, TMSG_RESET, TMSG_RESETSCREENSAVER, TMSG_RESTART, TMSG_RESTARTAPP, TMSG_SET_MUTE, TMSG_SET_VOLUME, TMSG_SETLANGUAGE, TMSG_SETVIDEORESOLUTION, TMSG_SHUTDOWN, TMSG_START_ANDROID_ACTIVITY, TMSG_SUSPEND, TMSG_SWITCHTOFULLSCREEN, TMSG_SYSTEM_POWERDOWN, TMSG_TOGGLEFULLSCREEN, TMSG_UPDATE_PLAYER_ITEM, TMSG_VIDEORESIZE, TMSG_VOLUME_SHOW, CGraphicContext::ToggleFullScreen(), XBMC_Event::type, CGUIInfoManager::UpdateCurrentItem(), CFileItem::UpdateInfo(), XBMC_ResizeEvent::w, WINDOW_FULLSCREEN_VIDEO, WINDOW_SLIDESHOW, XBMC_VIDEORESIZE, and CWIN32Util::XBMCShellExecute().
OnMessage()
bool CApplication::OnMessage (CGUIMessage & message) override virtual
Implements IMsgTargetCallback.
References ConfigureAndEnableAddons(), data(), CGUIWindowManager::Delete(), ExecuteXBMCAction(), g_localizeStrings, g_partyModeManager, ContentUtils::GeneratePlayableTrailerItem(), CURL::Get(), CLocalizeStrings::Get(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CDataCacheCore::GetInstance(), CGUIMessage::GetItem(), CGUIMessage::GetMessage(), KODI::PLAYLIST::CPlayListPlayer::GetNextItemIdx(), CGUIMessage::GetNumStringParams(), CGUIMessage::GetParam1(), CGUIMessage::GetParam1AsI64(), CGUIMessage::GetParam2AsI64(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), XFILE::CPluginDirectory::GetPluginResult(), CServiceBroker::GetPVRManager(), XFILE::CUPnPDirectory::GetResource(), CGUIMessage::GetSenderId(), CGUIMessage::GetStringParam(), CGUIComponent::GetWindowManager(), CServiceBroker::GetXBPython(), GUI_MSG_EXECUTE, GUI_MSG_FULLSCREEN, GUI_MSG_NOTIFY_ALL, GUI_MSG_PLAY_TRAILER, GUI_MSG_PLAYBACK_AVCHANGE, GUI_MSG_PLAYBACK_AVSTARTED, GUI_MSG_PLAYBACK_ENDED, GUI_MSG_PLAYBACK_ERROR, GUI_MSG_PLAYBACK_PAUSED, GUI_MSG_PLAYBACK_RESUMED, GUI_MSG_PLAYBACK_SEEKED, GUI_MSG_PLAYBACK_SPEED_CHANGED, GUI_MSG_PLAYBACK_STARTED, GUI_MSG_PLAYBACK_STOPPED, GUI_MSG_PLAYLIST_CHANGED, GUI_MSG_PLAYLISTPLAYER_CHANGED, GUI_MSG_PLAYLISTPLAYER_STARTED, GUI_MSG_PLAYLISTPLAYER_STOPPED, GUI_MSG_QUEUE_NEXT_ITEM, GUI_MSG_REMOVED_MEDIA, GUI_MSG_UI_READY, GUI_MSG_UPDATE_ITEM, int64_t(), KODI::MUSIC::IsAudio(), ADDON::CAddonType::IsDependencyType(), CGUIDialog::IsDialogRunning(), KODI::PLAYLIST::IsPlayList(), CURL::IsProtocol(), URIUtils::IsUPnP(), LOGERROR, m_bInitializing, m_incompatibleAddons, m_itemCurrentFile, m_nextPlaylistItem, m_playerEvent, JSONRPC::CJSONUtils::MillisecondsToTimeObject(), XBPython::OnAVChange(), XBPython::OnAVStarted(), XBPython::OnPlayBackEnded(), PVR::CPVRManager::OnPlaybackEnded(), XBPython::OnPlayBackStarted(), PVR::CPVRManager::OnPlaybackStarted(), XBPython::OnPlayBackStopped(), PVR::CPVRManager::OnPlaybackStopped(), CPartyModeManager::OnSongChange(), PlaybackCleanup(), ANNOUNCEMENT::Player, PlayFile(), playlist, KODI::PLAYLIST::CPlayListPlayer::RemoveDVDItems(), CEvent::Reset(), ResetCurrentItem(), CDataCacheCore::SeekFinished(), CGUIWindowManager::SendMessage(), CEvent::Set(), CGUIInfoManager::SetCurrentItem(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentItemIdx(), CDarwinUtils::SetScheduling(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), KODI::PLAYLIST::CPlayList::size(), StopPlaying(), CGUIWindowManager::SwitchToFullScreen(), TMSG_MEDIA_PLAY, CGUIInfoManager::UpdateCurrentItem(), CVariant::VariantTypeObject, CApplicationVolumeHandling::VOLUME_MINIMUM, CGUIDialogBusy::WaitOnEvent(), WINDOW_DIALOG_BUSY, WINDOW_SETTINGS_PROFILES, and WINDOW_SPLASH.
OnSettingsSaving()
bool CApplication::OnSettingsSaving () const override protected virtual
Settings saving has been initiated.
Returns
True if the settings should be saved, false if the saving should be aborted.
Reimplemented from ISettingsHandler.
References m_bStop.
PlaybackCleanup()
void CApplication::PlaybackCleanup () protected
References CGUIAudioManager::Enable(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetAppParams(), CGUIComponent::GetAudioManager(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CServiceBroker::GetMediaManager(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), KODI::MUSIC::IsCDDA(), CMediaManager::IsDiscInDrive(), m_itemCurrentFile, m_ServiceManager, CGUIWindowManager::PreviousWindow(), CGraphicContext::SetFullScreenVideo(), CDarwinUtils::SetScheduling(), TMSG_QUIT, WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, and WINDOW_VISUALISATION.
Referenced by OnMessage().
PlayFile()
bool CApplication::PlayFile (CFileItem item, const std::string & player, bool bRestart = false, bool forceSelection = false)
Todo:
this will fail if user seeks back to first file in stack
References CVariant::asDouble(), CVariant::asString(), CGUIListItem::ClearProperty(), CUtil::ClearSubtitles(), CDatabase::Close(), CUtil::ConvertMilliSecsToSecs(), XFILE::CDirectoryFactory::Create(), CMediaSettings::DoesMediaStartWindowed(), CGUIAudioManager::Enable(), CFileItem::FillInMimeType(), CServiceBroker::GetActiveAE(), CGUIComponent::GetAudioManager(), CVideoDatabase::GetBookMarkForEpisode(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CFileItem::GetCurrentResumeTime(), CServiceBroker::GetGUI(), CMediaSettings::GetInstance(), CServiceBroker::GetMediaManager(), CFileItem::GetMimeType(), CFileItem::GetPath(), CServiceBroker::GetPlaylistPlayer(), CGUIListItem::GetProperty(), CVideoDatabase::GetResumeBookMark(), CVideoInfoTag::GetResumePoint(), CServiceBroker::GetSettingsComponent(), CFileItem::GetStartOffset(), CFileItem::GetVideoInfoTag(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYBACK_ENDED, GUI_MSG_PLAYBACK_STARTED, GUI_MSG_PLAYBACK_STOPPED, GUI_MSG_PLAYLIST_CHANGED, GUI_MSG_PLAYLISTPLAYER_CHANGED, GUI_MSG_PLAYLISTPLAYER_STARTED, GUI_MSG_PLAYLISTPLAYER_STOPPED, GUI_MSG_QUEUE_NEXT_ITEM, KODI::PLAYLIST::CPlayListPlayer::HasPlayedFirstFile(), CGUIListItem::HasProperty(), CFileItem::HasPVRChannelInfoTag(), IAE::HasStereoAudioChannelCount(), CFileItem::HasVideoInfoTag(), KODI::MUSIC::IsAudio(), CFileItem::IsDiscImage(), KODI::PLAYLIST::IsPlayList(), URIUtils::IsPlugin(), CFileItem::IsResumePointSet(), CFileItem::IsStack(), CVideoDatabase::LoadVideoInfo(), LOGDEBUG, m_nextPlaylistItem, m_ServiceManager, CVideoInfoTag::m_strFileNameAndPath, CVideoDatabase::Open(), CBookmark::playerState, PlayStack(), CMediaManager::playStubFile(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), CMediaSettings::SetMediaStartWindowed(), CFileItem::SetStartOffset(), CSettings::SETTING_MUSICFILES_SELECTACTION, CGUIDialogSimpleMenu::ShowPlaySelection(), CComponentContainer< BaseType >::size(), STARTOFFSET_RESUME, and CBookmark::timeInSeconds.
Referenced by ExecuteXBMCAction(), OnAction(), OnMessage(), PlayMedia(), PlayStack(), and Restart().
PlayMedia()
bool CApplication::PlayMedia (CFileItem & item, const std::string & player, KODI::PLAYLIST::Id playlistId)
References CVariant::asInteger(), CGUIDialogCache::Close(), XFILE::DIR_FLAG_NO_FILE_DIRS, g_localizeStrings, PVR::CPVRManager::Get(), CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), CURL::GetHostName(), CGUIListItem::GetLabel(), KODI::PLAYLIST::CSmartPlaylist::GetName(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CURL::GetProtocol(), CServiceBroker::GetPVRManager(), CUtil::GetRecursiveListing(), XFILE::CPluginDirectory::GetResolvedPluginResult(), KODI::PLAYLIST::CSmartPlaylist::GetType(), CFileItem::GetURL(), URIUtils::HasPluginPath(), CGUIListItem::HasProperty(), CGUIDialogCache::IsCanceled(), KODI::NETWORK::IsInternetStream(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsPVR(), KODI::PLAYLIST::IsSmartPlayList(), CLog::Log(), LOGWARNING, KODI::PLAYLIST::CSmartPlaylist::OpenAndReadName(), PlayFile(), playlist, PlayMedia(), ProcessAndStartPlaylist(), CFileItemList::Size(), and CGUIDialogBusy::Wait().
Referenced by PlayMedia().
PlayStack()
bool CApplication::PlayStack (CFileItem & item, bool bRestart) protected
References CGUIListItem::ClearProperty(), CFileItem::GetDynPath(), CGUIListItem::GetProperty(), CGUIListItem::HasProperty(), LOGERROR, PlayFile(), CGUIListItem::SetProperty(), and CFileItem::SetStartOffset().
Referenced by PlayFile().
PrintStartupLog()
void CApplication::PrintStartupLog () private
References CPU_FEATURE_NEON, g_sysinfo, CCompileInfo::GetAppName(), CSysInfo::GetAppName(), CSysInfo::GetBuildDate(), CSysInfo::GetBuildTargetCpuFamily(), CSysInfo::GetBuildTargetPlatformName(), CSysInfo::GetBuildTargetPlatformVersion(), CSysInfo::GetBuildTargetPlatformVersionDecoded(), CServiceBroker::GetCPUInfo(), CSysInfo::GetKernelBitness(), CSysInfo::GetKernelCpuFamily(), CSysInfo::GetKernelName(), CSysInfo::GetKernelVersionFull(), CSysInfo::GetManufacturerName(), CSysInfo::GetModelName(), CSysInfo::GetOsPrettyNameWithVersion(), CSysInfo::GetUsedCompilerNameAndVer(), CSysInfo::GetVersion(), CCompileInfo::GetWebserverExtraWhitelist(), CSysInfo::GetXbmcBitness(), CLog::Log(), CRegExp::LogCheckUtf8Support(), LOGINFO, CSpecialProtocol::LogPaths(), m_ServiceManager, CUtil::ResolveExecutablePath(), and CSpecialProtocol::TranslatePath().
Referenced by Create().
Process()
void CApplication::Process () override virtual
Implements IWindowManagerCallback.
References CServiceBroker::GetAppMessenger(), CStopWatch::GetElapsedMilliseconds(), CServiceBroker::GetGUI(), CScriptInvocationManager::GetInstance(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), m_bStop, m_frameMoveGuard, m_slowTimer, CScriptInvocationManager::Process(), ProcessSlow(), and CStopWatch::Reset().
Referenced by Run().
ProcessAndStartPlaylist()
bool CApplication::ProcessAndStartPlaylist (const std::string & strPlayList, KODI::PLAYLIST::CPlayList & playlist, KODI::PLAYLIST::Id playlistId, int track = 0)
References KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist(), CServiceBroker::GetPlaylistPlayer(), CLog::Log(), LOGDEBUG, m_strPlayListFile, KODI::PLAYLIST::CPlayListPlayer::Play(), playlist, KODI::PLAYLIST::CPlayListPlayer::Reset(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), and CComponentContainer< BaseType >::size().
Referenced by PlayMedia().
ProcessSlow()
void CApplication::ProcessSlow ()
References CheckDelayedPlayerRestart(), XCURL::DllLibCurlGlobal::CheckIdle(), CNfsConnection::CheckIfIdle(), CSMB::CheckIfIdle(), CGUILargeTextureManager::CleanupUnusedImages(), CurrentFileItem(), CGUITextureManager::FreeUnusedTextures(), g_curlInterface, CXBMCApp::Get(), ADDON::CVFSAddonCache::GetAddonInstances(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), UPNP::CUPnP::GetInstance(), CServiceBroker::GetJobManager(), CGUIComponent::GetLargeTextureManager(), CServiceBroker::GetMediaManager(), CServiceBroker::GetPowerManager(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetTextureManager(), CServiceBroker::GetVFSAddonCache(), CGUIComponent::GetWindowManager(), gNfsConnection, UPNP::CUPnP::IsInstantiated(), CLog::Log(), LOGINFO, CPowerManager::ProcessEvents(), CMediaManager::ProcessEvents(), CXBMCApp::ProcessSlow(), CSettings::SETTING_POWERMANAGEMENT_SHUTDOWNTIME, CSettings::SETTING_SERVICES_UPNP, smb, CPlatformPosix::TestQuitFlag(), TMSG_QUIT, CSectionLoader::UnloadDelayed(), UPNP::CUPnP::UpdateState(), WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, and WINDOW_SLIDESHOW.
Referenced by Process().
Render()
void CApplication::Render () override virtual
Implements IWindowManagerCallback.
References CGUIWindowManager::AfterRender(), CRenderSystemBase::EndRender(), CGraphicContext::Flip(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetGUIControlsInfoProvider(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CServiceBroker::GetRenderSystem(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetSystemInfoProvider(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), m_AppFocused, m_bStop, m_lastRenderTime, m_skipGuiRender, CGUIWindowManager::Render(), RENDER_STEREO_MODE_MONO, RENDER_STEREO_VIEW_LEFT, RENDER_STEREO_VIEW_OFF, RENDER_STEREO_VIEW_RIGHT, CGUIWindowManager::RenderEx(), CGUIInfoManager::ResetCache(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::ResetContainerMovingCache(), CGraphicContext::SetStereoView(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::UpdateFPS(), and CTimeUtils::UpdateFrameTime().
Referenced by Run().
ResetCurrentItem()
void CApplication::ResetCurrentItem () private
References m_itemCurrentFile, and m_pGUI.
Referenced by Cleanup(), and OnMessage().
Restart()
void CApplication::Restart (bool bSamePosition = true)
References CUtil::ConvertSecsToMilliSecs(), GetTime(), m_itemCurrentFile, and PlayFile().
Referenced by CheckDelayedPlayerRestart().
Run()
int CApplication::Run ()
References KODI::PLAYLIST::CPlayListPlayer::Add(), Cleanup(), FrameMove(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetAppParams(), CServiceBroker::GetPlaylistPlayer(), CLog::Log(), LOGINFO, m_bStop, m_ExitCode, playlist, Process(), Render(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), KODI::TIME::Sleep(), and TMSG_PLAYLISTPLAYER_PLAY.
SeekPercentage()
void CApplication::SeekPercentage (float percent)
References GetTotalTime(), and SeekTime().
SeekTime()
void CApplication::SeekTime (double dTime = 0.0)
References CServiceBroker::GetAppMessenger(), int64_t(), CFileItem::SetStartOffset(), and TMSG_MEDIA_PLAY.
Referenced by OnAction(), and SeekPercentage().
SetLanguage()
bool CApplication::SetLanguage (const std::string & strLanguage)
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_LOCALE_LANGUAGE.
Referenced by OnApplicationMessage().
SetLoggingIn()
void CApplication::SetLoggingIn (bool switchingProfiles)
Referenced by Initialize().
ShowAppMigrationMessage()
void CApplication::ShowAppMigrationMessage ()
Stop()
bool CApplication::Stop (int exitCode)
References CMusicLibraryQueue::CancelAllJobs(), CVideoLibraryQueue::CancelAllJobs(), cleanup_emu_environ(), CSMB::Deinit(), CGUIAudioManager::DeInitialize(), XFILE::CFile::Exists(), g_alarmClock, g_SkinInfo, g_sysinfo, CXBMCApp::Get(), ADDON::CVFSAddonCache::GetAddonInstances(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppMessenger(), CGUIComponent::GetAudioManager(), CTimeUtils::GetFrameTime(), CServiceBroker::GetGUI(), CScriptInvocationManager::GetInstance(), CMusicLibraryQueue::GetInstance(), CZeroconfBrowser::GetInstance(), XBMCHelper::GetInstance(), CPlayerController::GetInstance(), CVideoLibraryQueue::GetInstance(), CServiceBroker::GetJobManager(), CServiceBroker::GetServiceAddons(), CServiceBroker::GetSettingsComponent(), CSysInfo::GetTotalUptime(), CServiceBroker::GetVFSAddonCache(), XBMCHelper::IsAlwaysOn(), CZeroconfBrowser::IsInstantiated(), CLog::Log(), LOGERROR, LOGINFO, m_AppFocused, m_bStop, m_ExitCode, m_frameMoveGuard, m_pActiveAE, m_pAppPort, m_ServiceManager, CZeroconfBrowser::ReleaseInstance(), CNetworkBase::SERVICES_DOWN, CSysInfo::SetTotalUptime(), KODI::TIME::Sleep(), smb, ADDON::CServiceAddonManager::Stop(), CZeroconfBrowser::Stop(), XBMCHelper::Stop(), Stop(), CScriptInvocationManager::StopRunningScripts(), CThread::StopThread(), success, ANNOUNCEMENT::System, CServiceBroker::UnregisterAE(), CServiceBroker::UnregisterAppPort(), and CVariant::VariantTypeObject.
Referenced by OnApplicationMessage(), and Stop().
StopPlaying()
void CApplication::StopPlaying ()
References CPartyModeManager::Disable(), g_partyModeManager, CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), m_bStop, CGUIWindowManager::PreviousWindow(), WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, and WINDOW_VISUALISATION.
Referenced by Cleanup(), OnAction(), OnApplicationMessage(), and OnMessage().
UnlockFrameMoveGuard()
void CApplication::UnlockFrameMoveGuard ()
Unlocks calls from outside kodi (e.g. python).
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), m_frameMoveGuard, and m_WaitingExternalCalls.
UpdateCurrentPlayArt()
void CApplication::UpdateCurrentPlayArt ()
References CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CMusicThumbLoader::LoadItem(), m_itemCurrentFile, and CGUIInfoManager::SetCurrentItem().
UpdateLibraries()
void CApplication::UpdateLibraries ()
References CMusicLibraryQueue::GetInstance(), CVideoLibraryQueue::GetInstance(), CServiceBroker::GetSettingsComponent(), LOGINFO, MUSIC_INFO::CMusicInfoScanner::SCAN_NORMAL, CVideoLibraryQueue::ScanLibrary(), CMusicLibraryQueue::ScanLibrary(), CSettings::SETTING_MUSICLIBRARY_BACKGROUNDUPDATE, CSettings::SETTING_MUSICLIBRARY_UPDATEONSTARTUP, CSettings::SETTING_VIDEOLIBRARY_BACKGROUNDUPDATE, and CSettings::SETTING_VIDEOLIBRARY_UPDATEONSTARTUP.
Referenced by Initialize().
Member Data Documentation
ACTION_PREV_ITEM_THRESHOLD
const unsigned int CApplication::ACTION_PREV_ITEM_THRESHOLD = 3 static
Referenced by OnAction(), and PVR::CPVRGUIActionListener::OnAction().
m_AppFocused
bool CApplication::m_AppFocused {true}
Referenced by IsAppFocused(), Render(), and Stop().
m_bInitializing
bool CApplication::m_bInitializing = true protected
Referenced by CApplication(), Cleanup(), IsInitialized(), and OnMessage().
m_bStop
bool CApplication::m_bStop {false}
Referenced by Create(), FrameMove(), CAppInboundProtocol::HandleEvents(), IsStopping(), OnSettingsSaving(), Process(), Render(), Run(), Stop(), and StopPlaying().
m_critSection
CCriticalSection CApplication::m_critSection mutable private
critical section for all changes to this class, except for changes to triggers
Referenced by CApplication().
m_ExitCode
int CApplication::m_ExitCode {EXITCODE_QUIT} private
Referenced by Run(), and Stop().
m_frameMoveGuard
CCriticalSection CApplication::m_frameMoveGuard private
critical section for synchronizing GUI actions from inside and outside (python)
Referenced by CreateGUI(), FrameMove(), LockFrameMoveGuard(), Process(), Stop(), and UnlockFrameMoveGuard().
m_frameTime
CStopWatch CApplication::m_frameTime protected
Referenced by FrameMove().
m_guiRefreshTimer
XbmcThreads::EndTime CApplication::m_guiRefreshTimer protected
Referenced by FrameMove().
m_incompatibleAddons
std::vector<std::shared_ptr<ADDON::CAddonInfo> > CApplication::m_incompatibleAddons protected
Result of addon migration (incompatible addon infos)
Referenced by Initialize(), and OnMessage().
m_itemCurrentFile
std::shared_ptr<CFileItem> CApplication::m_itemCurrentFile private
Currently playing file.
Referenced by CurrentFile(), CurrentFileItem(), CurrentFileItemPtr(), CurrentUnstackedItem(), GetPercentage(), OnAction(), OnApplicationMessage(), OnMessage(), PlaybackCleanup(), ResetCurrentItem(), Restart(), and UpdateCurrentPlayArt().
m_lastRenderTime
std::chrono::time_point<std::chrono::steady_clock> CApplication::m_lastRenderTime protected
Referenced by Create(), and Render().
m_musicInfoScanner
std::unique_ptr<MUSIC_INFO::CMusicInfoScanner> CApplication::m_musicInfoScanner protected
m_nextPlaylistItem
int CApplication::m_nextPlaylistItem = -1 protected
Referenced by OnMessage(), and PlayFile().
m_pActiveAE
std::unique_ptr<ActiveAE::CActiveAE> CApplication::m_pActiveAE protected
Referenced by Create(), Initialize(), and Stop().
m_pAnnouncementManager
std::shared_ptr<ANNOUNCEMENT::CAnnouncementManager> CApplication::m_pAnnouncementManager protected
Referenced by Cleanup(), and Create().
m_pAppPort
std::shared_ptr<CAppInboundProtocol> CApplication::m_pAppPort protected
Referenced by Create(), FrameMove(), OnApplicationMessage(), and Stop().
m_pGUI
std::unique_ptr<CGUIComponent> CApplication::m_pGUI protected
Referenced by Cleanup(), CreateGUI(), and ResetCurrentItem().
m_pInertialScrollingHandler
std::unique_ptr<CInertialScrollingHandler> CApplication::m_pInertialScrollingHandler protected
Referenced by FrameMove(), and OnAction().
m_playerEvent
CEvent CApplication::m_playerEvent private
Referenced by OnMessage().
m_prevMedia
std::string CApplication::m_prevMedia protected
m_ProcessedExternalCalls
unsigned int CApplication::m_ProcessedExternalCalls = 0 private
counts calls which are processed during one "door open" cycle in FrameMove
Referenced by FrameMove(), and LockFrameMoveGuard().
m_ProcessedExternalDecay
unsigned int CApplication::m_ProcessedExternalDecay = 0 private
counts to close door after a few frames of no python activity
Referenced by FrameMove().
m_pWinSystem
std::unique_ptr<CWinSystemBase> CApplication::m_pWinSystem protected
Referenced by Cleanup(), and CreateGUI().
m_restartPlayerTimer
CStopWatch CApplication::m_restartPlayerTimer protected
Referenced by CheckDelayedPlayerRestart(), and DelayedPlayerRestart().
m_ServiceManager
std::unique_ptr<CServiceManager> CApplication::m_ServiceManager
Referenced by Cleanup(), ConfigureAndEnableAddons(), Create(), Initialize(), OnAction(), OnApplicationMessage(), PlaybackCleanup(), PlayFile(), PrintStartupLog(), and Stop().
m_skipGuiRender
bool CApplication::m_skipGuiRender = false protected
Referenced by FrameMove(), and Render().
m_slowTimer
CStopWatch CApplication::m_slowTimer protected
Referenced by Initialize(), and Process().
m_strPlayListFile
std::string CApplication::m_strPlayListFile
Referenced by ProcessAndStartPlaylist().
m_WaitingExternalCalls
std::atomic_uint CApplication::m_WaitingExternalCalls private
counts threads which are waiting to be processed in FrameMove
Referenced by FrameMove(), LockFrameMoveGuard(), and UnlockFrameMoveGuard().
The documentation for this class was generated from the following files:
Application.h
Application.cpp