Kodi Documentation: ADDON::CAddonExtensions Class Reference
ADDON::CAddonExtensions Class Reference
#include <AddonExtensions.h>
Public Member Functions
CAddonExtensions ()=default
~CAddonExtensions ()=default
const SExtValue GetValue (const std::string &id) const
const EXT_VALUES & GetValues () const
const CAddonExtensions * GetElement (const std::string &id) const
const EXT_ELEMENTS GetElements (const std::string &id="") const
void Insert (const std::string &id, const std::string &value)
Private Attributes
std::string m_point
EXT_VALUES m_values
EXT_ELEMENTS m_children
Friends
class CAddonInfoBuilder
class CAddonDatabaseSerializer
Constructor & Destructor Documentation
CAddonExtensions()
ADDON::CAddonExtensions::CAddonExtensions () default
~CAddonExtensions()
ADDON::CAddonExtensions::~CAddonExtensions () default
Member Function Documentation
GetElement()
const CAddonExtensions * CAddonExtensions::GetElement (const std::string & id) const
References m_children.
Referenced by ADDON::CContextMenuAddon::CContextMenuAddon(), and ADDON::CLanguageResource::CLanguageResource().
GetElements()
const EXT_ELEMENTS CAddonExtensions::GetElements (const std::string & id = "") const
References m_children.
Referenced by ADDON::CContextMenuAddon::ParseMenu().
GetValue()
const SExtValue CAddonExtensions::GetValue (const std::string & id) const
References m_values, value, and values.
Referenced by ADDON::CContextMenuAddon::CContextMenuAddon(), ADDON::CLanguageResource::CLanguageResource(), ADDON::CRepository::ParseDirConfiguration(), ADDON::CContextMenuAddon::ParseMenu(), ADDON::CAddonInfoBuilder::ParseXMLTypes(), ADDON::CAddonInfoBuilderFromDB::SetExtensions(), and ADDON::CAddonType::SetProvides().
GetValues()
const EXT_VALUES & CAddonExtensions::GetValues () const
References m_values.
Referenced by ADDON::CLanguageResource::CLanguageResource().
Insert()
void CAddonExtensions::Insert (const std::string & id, const std::string & value)
References m_values, and value.
Referenced by ADDON::CAddonType::SetProvides(), and TEST_F().
Friends And Related Symbol Documentation
CAddonDatabaseSerializer
friend class CAddonDatabaseSerializer friend
CAddonInfoBuilder
friend class CAddonInfoBuilder friend
Member Data Documentation
m_children
EXT_ELEMENTS ADDON::CAddonExtensions::m_children private
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeExtensions(), GetElement(), GetElements(), ADDON::CAddonInfoBuilder::ParseXMLExtension(), and ADDON::CAddonDatabaseSerializer::SerializeExtensions().
m_point
std::string ADDON::CAddonExtensions::m_point private
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeExtensions(), ADDON::CAddonDatabaseSerializer::DeserializeMetadata(), ADDON::CAddonInfoBuilder::ParseXMLExtension(), and ADDON::CAddonDatabaseSerializer::SerializeExtensions().
m_values
EXT_VALUES ADDON::CAddonExtensions::m_values private
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeExtensions(), GetValue(), GetValues(), Insert(), ADDON::CAddonInfoBuilder::ParseXMLExtension(), and ADDON::CAddonDatabaseSerializer::SerializeExtensions().
The documentation for this class was generated from the following files:
AddonExtensions.h
AddonExtensions.cpp