Kodi Documentation: KODI::WINDOWING::WAYLAND::IInputHandlerPointer Class Reference
KODI::WINDOWING::WAYLAND::IInputHandlerPointer Class Reference abstract
#include <InputProcessorPointer.h>
Public Member Functions
virtual void OnPointerEnter (std::uint32_t seatGlobalName, std::uint32_t serial)
virtual void OnPointerLeave ()
virtual void OnPointerEvent (XBMC_Event &event)=0
Protected Member Functions
~IInputHandlerPointer ()=default
Constructor & Destructor Documentation
~IInputHandlerPointer()
KODI::WINDOWING::WAYLAND::IInputHandlerPointer::~IInputHandlerPointer () protected default
Member Function Documentation
OnPointerEnter()
virtual void KODI::WINDOWING::WAYLAND::IInputHandlerPointer::OnPointerEnter (std::uint32_t seatGlobalName, std::uint32_t serial) inline virtual
Reimplemented in KODI::WINDOWING::WAYLAND::CSeatInputProcessing.
Referenced by KODI::WINDOWING::WAYLAND::CInputProcessorPointer::OnPointerEnter().
OnPointerEvent()
virtual void KODI::WINDOWING::WAYLAND::IInputHandlerPointer::OnPointerEvent (XBMC_Event & event) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CSeatInputProcessing.
Referenced by KODI::WINDOWING::WAYLAND::CInputProcessorPointer::SendMouseButton(), and KODI::WINDOWING::WAYLAND::CInputProcessorPointer::SendMouseMotion().
OnPointerLeave()
virtual void KODI::WINDOWING::WAYLAND::IInputHandlerPointer::OnPointerLeave () inline virtual
Reimplemented in KODI::WINDOWING::WAYLAND::CSeatInputProcessing.
Referenced by KODI::WINDOWING::WAYLAND::CInputProcessorPointer::OnPointerLeave().
The documentation for this class was generated from the following file:
InputProcessorPointer.h