Kodi Documentation: KODI::KEYBOARD::CKeyboardLayoutManager Class Reference
KODI::KEYBOARD::CKeyboardLayoutManager Class Reference
Input » Keyboard
#include <KeyboardLayoutManager.h>
Public Member Functions
CKeyboardLayoutManager ()=default
virtual ~CKeyboardLayoutManager ()
bool Load (const std::string &path="")
void Unload ()
const KeyboardLayouts & GetLayouts () const
bool GetLayout (const std::string &name, CKeyboardLayout &layout) const
Static Public Member Functions
static void SettingOptionsKeyboardLayoutsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
Private Member Functions
CKeyboardLayoutManager (const CKeyboardLayoutManager &)=delete
CKeyboardLayoutManager const & operator= (CKeyboardLayoutManager const &)=delete
Private Attributes
KeyboardLayouts m_layouts
Constructor & Destructor Documentation
CKeyboardLayoutManager() [1/2]
KODI::KEYBOARD::CKeyboardLayoutManager::CKeyboardLayoutManager () default
~CKeyboardLayoutManager()
CKeyboardLayoutManager::~CKeyboardLayoutManager () virtual
References Unload().
CKeyboardLayoutManager() [2/2]
KODI::KEYBOARD::CKeyboardLayoutManager::CKeyboardLayoutManager (const CKeyboardLayoutManager &) private delete
Member Function Documentation
GetLayout()
bool CKeyboardLayoutManager::GetLayout (const std::string & name, CKeyboardLayout & layout) const
References m_layouts, and name.
GetLayouts()
const KeyboardLayouts & KODI::KEYBOARD::CKeyboardLayoutManager::GetLayouts () const inline
References m_layouts.
Load()
bool CKeyboardLayoutManager::Load (const std::string & path = "")
References XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::Exists(), XFILE::CDirectory::GetDirectory(), KODI::KEYBOARD::CKeyboardLayout::GetIdentifier(), KEYBOARD_LAYOUTS_PATH, layouts, KODI::KEYBOARD::CKeyboardLayout::Load(), CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGDEBUG, LOGINFO, LOGWARNING, and m_layouts.
operator=()
CKeyboardLayoutManager const & KODI::KEYBOARD::CKeyboardLayoutManager::operator= (CKeyboardLayoutManager const &) private delete
SettingOptionsKeyboardLayoutsFiller()
void CKeyboardLayoutManager::SettingOptionsKeyboardLayoutsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References CServiceBroker::GetKeyboardLayoutManager(), and name.
Referenced by CSettings::InitializeOptionFillers().
Unload()
void CKeyboardLayoutManager::Unload ()
References m_layouts.
Referenced by ~CKeyboardLayoutManager().
Member Data Documentation
m_layouts
KeyboardLayouts KODI::KEYBOARD::CKeyboardLayoutManager::m_layouts private
Referenced by GetLayout(), GetLayouts(), Load(), and Unload().
The documentation for this class was generated from the following files:
KeyboardLayoutManager.h
KeyboardLayoutManager.cpp