Kodi Documentation: wrapper.c File Reference
wrapper.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdarg.h>
#include <dirent.h>
#include <dlfcn.h>
Functions
void * dllmalloc (size_t)
void * dllcalloc (size_t, size_t)
void * dllrealloc (void *, size_t)
void dllfree (void *)
int dll_open (const char *szFileName, int iMode)
int dll_write (int fd, const void *buffer, unsigned int uiSize)
int dll_read (int fd, void *buffer, unsigned int uiSize)
off_t dll_lseek (int fd, __off_t lPos, int iWhence)
__off64_t dll_lseeki64 (int fd, __off64_t lPos, int iWhence)
int dll_close (int fd)
FILE * dll_fopen (const char *filename, const char *mode)
FILE * dll_freopen (const char *path, const char *mode, FILE *stream)
FILE * dll_fdopen (int i, const char *file)
int dll_fclose (FILE *stream)
int dll_ferror (FILE *stream)
int dll_feof (FILE *stream)
int dll_fileno (FILE *stream)
void dll_clearerr (FILE *stream)
int dll_fread (void *buffer, size_t size, size_t count, FILE *stream)
size_t dll_fwrite (const void *buffer, size_t size, size_t count, FILE *stream)
int dll_fflush (FILE *stream)
int dll_fputc (int character, FILE *stream)
int dll_fputs (const char *szLine, FILE *stream)
int dll_putc (int c, FILE *stream)
int dll_fseek (FILE *stream, long offset, int origin)
int dll_fseek64 (FILE *stream, off64_t offset, int origin)
long dll_ftell (FILE *stream)
off64_t dll_ftell64 (FILE *stream)
void dll_rewind (FILE *stream)
int dll_fgetpos (FILE *stream, fpos_t *pos)
int dll_fgetpos64 (FILE *stream, fpos64_t *pos)
int dll_fsetpos (FILE *stream, const fpos_t *pos)
int dll_fsetpos64 (FILE *stream, const fpos64_t *pos)
DIR * dll_opendir (const char *name)
struct dirent * dll_readdir (DIR *dirp)
int dll_closedir (DIR *dirp)
void dll_rewinddir (DIR *dirp)
int dll_fprintf (FILE *stream, const char *format,...)
int dllprintf (const char *format,...)
int dll_vfprintf (FILE *stream, const char *format, va_list va)
int dll_fgetc (FILE *stream)
char * dll_fgets (char *pszString, int num, FILE *stream)
int dll_getc (FILE *stream)
int dll_ungetc (int c, FILE *stream)
int dll_ioctl (int d, unsigned long int request, va_list va)
int dll_stat (const char *path, struct _stat *buffer)
int dll_stat64 (const char *path, struct stat64 *buffer)
void dll_flockfile (FILE *file)
int dll_ftrylockfile (FILE *file)
void dll_funlockfile (FILE *file)
int dll_fstat64 (int fd, struct stat64 *buf)
int dll_fstat (int fd, struct _stat *buf)
FILE * dll_popen (const char *command, const char *mode)
void * dll_dlopen (const char *filename, int flag)
int dll_setvbuf (FILE *stream, char *buf, int type, size_t size)
struct mntent * dll_getmntent (FILE *fp)
struct mntent * dll_getmntent_r (FILE *fp, struct mntent *result, char *buffer, int bufsize)
void * __wrap_dlopen (const char *filename, int flag)
FILE * __wrap_popen (const char *command, const char *mode)
void * __wrap_calloc (size_t num, size_t size)
void * __wrap_malloc (size_t size)
void * __wrap_realloc (void *memblock, size_t size)
void __wrap_free (void *pPtr)
int __wrap_open (const char *file, int oflag,...)
int __wrap_open64 (const char *file, int oflag,...)
int __wrap_close (int fd)
ssize_t __wrap_write (int fd, const void *buf, size_t count)
ssize_t __wrap_read (int fd, void *buf, size_t count)
__off_t __wrap_lseek (int filedes, __off_t offset, int whence)
__off64_t __wrap_lseek64 (int filedes, __off64_t offset, int whence)
int __wrap_fclose (FILE *fp)
int __wrap_ferror (FILE *stream)
void __wrap_clearerr (FILE *stream)
int __wrap_feof (FILE *stream)
int __wrap_fileno (FILE *stream)
FILE * __wrap_fopen (const char *path, const char *mode)
FILE * __wrap_fopen64 (const char *path, const char *mode)
FILE * __wrap_fdopen (int filedes, const char *mode)
FILE * __wrap_freopen (const char *path, const char *mode, FILE *stream)
size_t __wrap_fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
size_t __wrap_fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
int __wrap_fflush (FILE *stream)
int __wrap_fputc (int c, FILE *stream)
int __wrap_fputs (const char *s, FILE *stream)
int __wrap__IO_putc (int c, FILE *stream)
int __wrap_fseek (FILE *stream, long offset, int whence)
int __wrap_fseeko64 (FILE *stream, off64_t offset, int whence)
long __wrap_ftell (FILE *stream)
off64_t __wrap_ftello64 (FILE *stream)
void __wrap_rewind (FILE *stream)
int __wrap_fgetpos (FILE *stream, fpos_t *pos)
int __wrap_fgetpos64 (FILE *stream, fpos64_t *pos)
int __wrap_fsetpos (FILE *stream, fpos_t *pos)
int __wrap_fsetpos64 (FILE *stream, fpos64_t *pos)
DIR * __wrap_opendir (const char *name)
struct dirent * __wrap_readdir (DIR *dirp)
struct dirent * __wrap_readdir64 (DIR *dirp)
int __wrap_closedir (DIR *dirp)
void __wrap_rewinddir (DIR *dirp)
int __wrap_fprintf (FILE *stream, const char *format,...)
int __wrap_vfprintf (FILE *stream, const char *format, va_list ap)
int __wrap_printf (const char *format,...)
int __wrap_fgetc (FILE *stream)
char * __wrap_fgets (char *s, int size, FILE *stream)
int __wrap__IO_getc (FILE *stream)
int __wrap__IO_getc_unlocked (FILE *stream)
int __wrap_getc_unlocked (FILE *stream)
int __wrap_ungetc (int c, FILE *stream)
int __wrap_getc (FILE *stream)
int __wrap_ioctl (int d, unsigned long int request,...)
int __wrap__stat (const char *path, struct _stat *buffer)
int __wrap_stat (const char *path, struct _stat *buffer)
int __wrap_stat64 (const char *path, struct stat64 *buffer)
int __wrap___xstat (int __ver, const char *__filename, struct stat *__stat_buf)
int __wrap___xstat64 (int __ver, const char *__filename, struct stat64 *__stat_buf)
int __wrap___lxstat64 (int __ver, const char *__filename, struct stat64 *__stat_buf)
void __wrap_flockfile (FILE *file)
int __wrap_ftrylockfile (FILE *file)
void __wrap_funlockfile (FILE *file)
int __wrap___fxstat64 (int ver, int fd, struct stat64 *buf)
int __wrap___fxstat (int ver, int fd, struct stat *buf)
int __wrap_fstat (int fd, struct _stat *buf)
int __wrap_fstat64 (int fd, struct stat64 *buf)
int __wrap_setvbuf (FILE *stream, char *buf, int type, size_t size)
struct mntent * __wrap_getmntent (FILE *fp)
struct mntent * __wrap_getmntent_r (FILE *fp, struct mntent *result, char *buffer, int bufsize)
Function Documentation
__wrap___fxstat()
int __wrap___fxstat (int ver, int fd, struct stat * buf)
References dll_fstat().
__wrap___fxstat64()
int __wrap___fxstat64 (int ver, int fd, struct stat64 * buf)
References dll_fstat64().
__wrap___lxstat64()
int __wrap___lxstat64 (int __ver, const char * __filename, struct stat64 * __stat_buf)
References dll_stat64().
__wrap___xstat()
int __wrap___xstat (int __ver, const char * __filename, struct stat * __stat_buf)
References dll_stat().
__wrap___xstat64()
int __wrap___xstat64 (int __ver, const char * __filename, struct stat64 * __stat_buf)
References dll_stat64().
__wrap__IO_getc()
int __wrap__IO_getc (FILE * stream)
References dll_getc().
__wrap__IO_getc_unlocked()
int __wrap__IO_getc_unlocked (FILE * stream)
References dll_getc().
__wrap__IO_putc()
int __wrap__IO_putc (int c, FILE * stream)
References dll_putc().
__wrap__stat()
int __wrap__stat (const char * path, struct _stat * buffer)
References dll_stat().
__wrap_calloc()
void * __wrap_calloc (size_t num, size_t size)
References dllcalloc().
__wrap_clearerr()
void __wrap_clearerr (FILE * stream)
References dll_clearerr().
__wrap_close()
int __wrap_close (int fd)
References dll_close().
__wrap_closedir()
int __wrap_closedir (DIR * dirp)
References dll_closedir().
__wrap_dlopen()
void * __wrap_dlopen (const char * filename, int flag)
__wrap_fclose()
int __wrap_fclose (FILE * fp)
References dll_fclose().
__wrap_fdopen()
FILE * __wrap_fdopen (int filedes, const char * mode)
References dll_fdopen().
__wrap_feof()
int __wrap_feof (FILE * stream)
References dll_feof().
__wrap_ferror()
int __wrap_ferror (FILE * stream)
References dll_ferror().
__wrap_fflush()
int __wrap_fflush (FILE * stream)
References dll_fflush().
__wrap_fgetc()
int __wrap_fgetc (FILE * stream)
References dll_fgetc().
__wrap_fgetpos()
int __wrap_fgetpos (FILE * stream, fpos_t * pos)
References dll_fgetpos().
__wrap_fgetpos64()
int __wrap_fgetpos64 (FILE * stream, fpos64_t * pos)
References dll_fgetpos64().
__wrap_fgets()
char * __wrap_fgets (char * s, int size, FILE * stream)
References dll_fgets().
__wrap_fileno()
int __wrap_fileno (FILE * stream)
References dll_fileno().
__wrap_flockfile()
void __wrap_flockfile (FILE * file)
References dll_flockfile().
__wrap_fopen()
FILE * __wrap_fopen (const char * path, const char * mode)
References dll_fopen().
__wrap_fopen64()
FILE * __wrap_fopen64 (const char * path, const char * mode)
References dll_fopen().
__wrap_fprintf()
int __wrap_fprintf (FILE * stream, const char * format, ...)
References dll_vfprintf().
__wrap_fputc()
int __wrap_fputc (int c, FILE * stream)
References dll_fputc().
__wrap_fputs()
int __wrap_fputs (const char * s, FILE * stream)
References dll_fputs().
__wrap_fread()
size_t __wrap_fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
References dll_fread().
__wrap_free()
void __wrap_free (void * pPtr)
References dllfree().
__wrap_freopen()
FILE * __wrap_freopen (const char * path, const char * mode, FILE * stream)
References dll_freopen().
__wrap_fseek()
int __wrap_fseek (FILE * stream, long offset, int whence)
References dll_fseek().
__wrap_fseeko64()
int __wrap_fseeko64 (FILE * stream, off64_t offset, int whence)
References dll_fseek64().
__wrap_fsetpos()
int __wrap_fsetpos (FILE * stream, fpos_t * pos)
References dll_fsetpos().
__wrap_fsetpos64()
int __wrap_fsetpos64 (FILE * stream, fpos64_t * pos)
References dll_fsetpos64().
__wrap_fstat()
int __wrap_fstat (int fd, struct _stat * buf)
References dll_fstat().
__wrap_fstat64()
int __wrap_fstat64 (int fd, struct stat64 * buf)
References dll_fstat64().
__wrap_ftell()
long __wrap_ftell (FILE * stream)
References dll_ftell().
__wrap_ftello64()
off64_t __wrap_ftello64 (FILE * stream)
References dll_ftell64().
__wrap_ftrylockfile()
int __wrap_ftrylockfile (FILE * file)
References dll_ftrylockfile().
__wrap_funlockfile()
void __wrap_funlockfile (FILE * file)
References dll_funlockfile().
__wrap_fwrite()
size_t __wrap_fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
References dll_fwrite().
__wrap_getc()
int __wrap_getc (FILE * stream)
References dll_getc().
__wrap_getc_unlocked()
int __wrap_getc_unlocked (FILE * stream)
References dll_getc().
__wrap_getmntent()
struct mntent * __wrap_getmntent (FILE * fp)
References dll_getmntent().
__wrap_getmntent_r()
struct mntent * __wrap_getmntent_r (FILE * fp, struct mntent * result, char * buffer, int bufsize)
References dll_getmntent_r().
__wrap_ioctl()
int __wrap_ioctl (int d, unsigned long int request, ...)
References dll_ioctl().
__wrap_lseek()
__off_t __wrap_lseek (int filedes, __off_t offset, int whence)
References dll_lseek().
__wrap_lseek64()
__off64_t __wrap_lseek64 (int filedes, __off64_t offset, int whence)
References dll_lseeki64().
__wrap_malloc()
void * __wrap_malloc (size_t size)
References dllmalloc().
__wrap_open()
int __wrap_open (const char * file, int oflag, ...)
References dll_open().
__wrap_open64()
int __wrap_open64 (const char * file, int oflag, ...)
References dll_open().
__wrap_opendir()
DIR * __wrap_opendir (const char * name)
References dll_opendir(), and name.
__wrap_popen()
FILE * __wrap_popen (const char * command, const char * mode)
References dll_popen().
__wrap_printf()
int __wrap_printf (const char * format, ...)
References dll_vfprintf().
__wrap_read()
ssize_t __wrap_read (int fd, void * buf, size_t count)
References dll_read().
__wrap_readdir()
struct dirent * __wrap_readdir (DIR * dirp)
References dll_readdir().
__wrap_readdir64()
struct dirent * __wrap_readdir64 (DIR * dirp)
References dll_readdir().
__wrap_realloc()
void * __wrap_realloc (void * memblock, size_t size)
References dllrealloc().
__wrap_rewind()
void __wrap_rewind (FILE * stream)
References dll_rewind().
__wrap_rewinddir()
void __wrap_rewinddir (DIR * dirp)
References dll_rewinddir().
__wrap_setvbuf()
int __wrap_setvbuf (FILE * stream, char * buf, int type, size_t size)
References dll_setvbuf().
__wrap_stat()
int __wrap_stat (const char * path, struct _stat * buffer)
References dll_stat().
__wrap_stat64()
int __wrap_stat64 (const char * path, struct stat64 * buffer)
References dll_stat64().
__wrap_ungetc()
int __wrap_ungetc (int c, FILE * stream)
References dll_ungetc().
__wrap_vfprintf()
int __wrap_vfprintf (FILE * stream, const char * format, va_list ap)
References dll_vfprintf().
__wrap_write()
ssize_t __wrap_write (int fd, const void * buf, size_t count)
References dll_write().
dll_clearerr()
void dll_clearerr (FILE * stream)
References g_emuFileWrapper, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_clearerr().
dll_close()
int dll_close (int fd)
References XFILE::CFile::Close(), g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGERROR, and CEmuFileWrapper::UnRegisterFileObjectByDescriptor().
Referenced by __wrap_close(), and dll_fclose().
dll_closedir()
int dll_closedir (DIR * dirp)
References CFileItemList::Clear(), closedir(), SDirData::curr_index, SDirData::items, SDirData::last_entry, and vecDirsOpen.
Referenced by __wrap_closedir().
dll_dlopen()
void * dll_dlopen (const char * filename, int flag)
dll_fclose()
int dll_fclose (FILE * stream)
References dll_close(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), and LOGERROR.
Referenced by __wrap_fclose(), and dll_freopen().
dll_fdopen()
FILE * dll_fdopen (int i, const char * file)
References _fdopen, convert_fmode(), g_emuFileWrapper, CEmuFileWrapper::GetFileObjectByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGWARNING, stEmuFileObject::mode, not_implement(), and stEmuFileObject::used.
Referenced by __wrap_fdopen().
dll_feof()
int dll_feof (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), XFILE::CFile::GetLength(), XFILE::CFile::GetPosition(), CLog::Log(), and LOGERROR.
Referenced by __wrap_feof().
dll_ferror()
int dll_ferror (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), and IS_STD_STREAM.
Referenced by __wrap_ferror().
dll_fflush()
int dll_fflush (FILE * stream)
References XFILE::CFile::Flush(), g_emuFileWrapper, and CEmuFileWrapper::GetFileXbmcByStream().
Referenced by __wrap_fflush().
dll_fgetc()
int dll_fgetc (FILE * stream)
References dll_fread(), g_emuFileWrapper, CLog::Log(), LOGERROR, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_fgetc(), dll_getc(), and dll_ungetc().
dll_fgetpos()
int dll_fgetpos (FILE * stream, fpos_t * pos)
References dll_fgetpos64().
Referenced by __wrap_fgetpos().
dll_fgetpos64()
int dll_fgetpos64 (FILE * stream, fpos64_t * pos)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), XFILE::CFile::GetPosition(), CLog::Log(), and LOGERROR.
Referenced by __wrap_fgetpos64(), and dll_fgetpos().
dll_fgets()
char * dll_fgets (char * pszString, int num, FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), XFILE::CFile::GetLength(), XFILE::CFile::GetPosition(), CLog::Log(), LOGERROR, and XFILE::CFile::ReadString().
Referenced by __wrap_fgets().
dll_fileno()
int dll_fileno (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), IS_STDERR_STREAM, IS_STDIN_STREAM, and IS_STDOUT_STREAM.
Referenced by __wrap_fileno().
dll_flockfile()
void dll_flockfile (FILE * file)
References g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CEmuFileWrapper::LockFileObjectByDescriptor(), CLog::Log(), and LOGERROR.
Referenced by __wrap_flockfile().
dll_fopen()
FILE * dll_fopen (const char * filename, const char * mode)
References convert_fmode(), dll_open(), g_emuFileWrapper, CEmuFileWrapper::GetStreamByDescriptor(), CLog::Log(), and LOGINFO.
Referenced by __wrap_fopen(), __wrap_fopen64(), dll_fopen_s(), and dll_freopen().
dll_fprintf()
int dll_fprintf (FILE * stream, const char * format, ...)
References dll_vfprintf().
dll_fputc()
int dll_fputc (int character, FILE * stream)
References dll_write(), dllputs(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), IS_STDERR_STREAM, IS_STDOUT_STREAM, IS_VALID_STREAM, CLog::Log(), LOGERROR, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_fputc(), and dll_putc().
dll_fputs()
int dll_fputs (const char * szLine, FILE * stream)
References dll_fwrite(), dllputs(), g_emuFileWrapper, IS_STDERR_STREAM, IS_STDOUT_STREAM, IS_VALID_STREAM, CLog::Log(), LOGERROR, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_fputs().
dll_fread()
int dll_fread (void * buffer, size_t size, size_t count, FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), CLog::Log(), LOGERROR, and XFILE::CFile::Read().
Referenced by __wrap_fread(), and dll_fgetc().
dll_freopen()
FILE * dll_freopen (const char * path, const char * mode, FILE * stream)
References dll_fclose(), dll_fopen(), g_emuFileWrapper, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_freopen().
dll_fseek()
int dll_fseek (FILE * stream, long offset, int origin)
References dll_fseek64().
Referenced by __wrap_fseek(), and dll_ungetc().
dll_fseek64()
int dll_fseek64 (FILE * stream, off64_t offset, int origin)
References dll_lseeki64(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), and LOGERROR.
Referenced by __wrap_fseeko64(), and dll_fseek().
dll_fsetpos()
int dll_fsetpos (FILE * stream, const fpos_t * pos)
References dll_fsetpos64(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), and LOGERROR.
Referenced by __wrap_fsetpos().
dll_fsetpos64()
int dll_fsetpos64 (FILE * stream, const fpos64_t * pos)
References dll_lseeki64(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), and LOGERROR.
Referenced by __wrap_fsetpos64(), and dll_fsetpos().
dll_fstat()
int dll_fstat (int fd, struct _stat * buf)
Referenced by __wrap___fxstat(), and __wrap_fstat().
dll_fstat64()
int dll_fstat64 (int fd, struct stat64 * buf)
Referenced by __wrap___fxstat64(), and __wrap_fstat64().
dll_ftell()
long dll_ftell (FILE * stream)
References dll_ftell64().
Referenced by __wrap_ftell().
dll_ftell64()
off64_t dll_ftell64 (FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), XFILE::CFile::GetPosition(), CLog::Log(), and LOGERROR.
Referenced by __wrap_ftello64(), and dll_ftell().
dll_ftrylockfile()
int dll_ftrylockfile (FILE * file)
References g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), LOGERROR, and CEmuFileWrapper::TryLockFileObjectByDescriptor().
Referenced by __wrap_ftrylockfile().
dll_funlockfile()
void dll_funlockfile (FILE * file)
References g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), LOGERROR, and CEmuFileWrapper::UnlockFileObjectByDescriptor().
Referenced by __wrap_funlockfile().
dll_fwrite()
size_t dll_fwrite (const void * buffer, size_t size, size_t count, FILE * stream)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), IS_STDERR_STREAM, IS_STDOUT_STREAM, IS_VALID_STREAM, CLog::Log(), LOGDEBUG, LOGERROR, and XFILE::CFile::Write().
Referenced by __wrap_fwrite(), and dll_fputs().
dll_getc()
int dll_getc (FILE * stream)
References dll_fgetc(), g_emuFileWrapper, CLog::Log(), LOGERROR, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap__IO_getc(), __wrap__IO_getc_unlocked(), __wrap_getc(), and __wrap_getc_unlocked().
dll_getmntent()
struct mntent * dll_getmntent (FILE * fp)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), and LOGWARNING.
Referenced by __wrap_getmntent().
dll_getmntent_r()
struct mntent * dll_getmntent_r (FILE * fp, struct mntent * result, char * buffer, int bufsize)
Referenced by __wrap_getmntent_r().
dll_ioctl()
int dll_ioctl (int d, unsigned long int request, va_list va)
Referenced by __wrap_ioctl().
dll_lseek()
off_t dll_lseek (int fd, __off_t lPos, int iWhence)
References CEmuFileWrapper::DescriptorIsEmulatedFile(), dll_lseeki64(), g_emuFileWrapper, IS_STD_DESCRIPTOR, CLog::Log(), and LOGERROR.
Referenced by __wrap_lseek().
dll_lseeki64()
__off64_t dll_lseeki64 (int fd, __off64_t lPos, int iWhence)
References g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGERROR, LOGWARNING, and XFILE::CFile::Seek().
Referenced by __wrap_lseek64(), dll_fseek64(), dll_fsetpos64(), dll_lseek(), and dll_rewind().
dll_open()
int dll_open (const char * szFileName, int iMode)
References _O_TRUNC, XFILE::CFile::Close(), f, g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), XFILE::CFile::Open(), XFILE::CFile::OpenForWrite(), XFILE::READ_TRUNCATED, CEmuFileWrapper::RegisterFileObject(), and CUtil::ValidatePath().
Referenced by __wrap_open(), __wrap_open64(), and dll_fopen().
dll_opendir()
DIR * dll_opendir (const char * name)
References bVecDirsInited, CFileItemList::Clear(), SDirData::curr_index, XFILE::DIR_FLAG_DEFAULTS, CURL::Get(), XFILE::CDirectory::GetDirectory(), CURL::IsLocal(), SDirData::items, CLog::Log(), LOGDEBUG, MAX_OPEN_DIRS, opendir(), CSpecialProtocol::TranslatePath(), CUtil::ValidatePath(), and vecDirsOpen.
Referenced by __wrap_opendir().
dll_popen()
FILE * dll_popen (const char * command, const char * mode)
References not_implement().
Referenced by __wrap_popen().
dll_putc()
int dll_putc (int c, FILE * stream)
References dll_fputc(), g_emuFileWrapper, IS_STD_STREAM, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap__IO_putc(), and dll_putchar().
dll_read()
int dll_read (int fd, void * buffer, unsigned int uiSize)
References err(), g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGERROR, and XFILE::CFile::Read().
Referenced by __wrap_read().
dll_readdir()
struct dirent * dll_readdir (DIR * dirp)
References SDirData::curr_index, dirent::d_name, CGUIListItem::GetLabel(), SDirData::items, SDirData::last_entry, readdir(), CFileItemList::Size(), and vecDirsOpen.
Referenced by __wrap_readdir(), and __wrap_readdir64().
dll_rewind()
void dll_rewind (FILE * stream)
References dll_lseeki64(), g_emuFileWrapper, CEmuFileWrapper::GetDescriptorByStream(), CLog::Log(), and LOGERROR.
Referenced by __wrap_rewind().
dll_rewinddir()
void dll_rewinddir (DIR * dirp)
References SDirData::curr_index, SDirData::last_entry, rewinddir(), and vecDirsOpen.
Referenced by __wrap_rewinddir().
dll_setvbuf()
int dll_setvbuf (FILE * stream, char * buf, int type, size_t size)
References CLog::Log(), and LOGWARNING.
Referenced by __wrap_setvbuf().
dll_stat()
int dll_stat (const char * path, struct _stat * buffer)
Referenced by __wrap___xstat(), __wrap__stat(), and __wrap_stat().
dll_stat64()
int dll_stat64 (const char * path, struct stat64 * buffer)
Referenced by __wrap___lxstat64(), __wrap___xstat64(), and __wrap_stat64().
dll_ungetc()
int dll_ungetc (int c, FILE * stream)
References dll_fgetc(), dll_fseek(), g_emuFileWrapper, CLog::Log(), LOGERROR, LOGWARNING, and CEmuFileWrapper::StreamIsEmulatedFile().
Referenced by __wrap_ungetc().
dll_vfprintf()
int dll_vfprintf (FILE * stream, const char * format, va_list va)
References _vsnprintf, g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByStream(), IS_STDERR_STREAM, IS_STDOUT_STREAM, IS_VALID_STREAM, CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, and XFILE::CFile::Write().
Referenced by __wrap_fprintf(), __wrap_printf(), __wrap_vfprintf(), and dll_fprintf().
dll_write()
int dll_write (int fd, const void * buffer, unsigned int uiSize)
References err(), g_emuFileWrapper, CEmuFileWrapper::GetFileXbmcByDescriptor(), IS_STD_DESCRIPTOR, CLog::Log(), LOGERROR, and XFILE::CFile::Write().
Referenced by __wrap_write(), and dll_fputc().
dllcalloc()
void * dllcalloc (size_t num, size_t size)
References CLog::Log(), and LOGFATAL.
Referenced by __wrap_calloc().
dllfree()
void dllfree (void * pPtr)
Referenced by __wrap_free().
dllmalloc()
void * dllmalloc (size_t size)
References CLog::Log(), and LOGFATAL.
Referenced by __wrap_malloc().
dllprintf()
int dllprintf (const char * format, ...)
References _vsnprintf, CLog::Log(), and LOGDEBUG.
dllrealloc()
void * dllrealloc (void * memblock, size_t size)
References CLog::Log(), and LOGFATAL.
Referenced by __wrap_realloc().