Kodi Documentation: CGUIControlGroupList Class Reference
CGUIControlGroupList Class Reference
Guilib classes » Window Reference » Controls
list of controls that is scrollable
#include <GUIControlGroupList.h>
Public Member Functions
CGUIControlGroupList (int parentID, int controlID, float posX, float posY, float width, float height, float itemGap, int pageControl, ORIENTATION orientation, bool useControlPositions, uint32_t alignment, const CScroller &scroller)
~CGUIControlGroupList (void) override
CGUIControlGroupList * Clone () const override
float GetWidth () const override
float GetHeight () const override
virtual float Size () const
void SetInvalid () override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
bool OnAction (const CAction &action) override
bool OnMessage (CGUIMessage &message) override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
void AddControl (CGUIControl *control, int position=-1) override
void ClearAll () override
virtual std::string GetLabel (int info) const
bool GetCondition (int condition, int data) const override
float GetTotalSize () const
ORIENTATION GetOrientation () const
void SetMinSize (float minWidth, float minHeight)
virtual CGUIControl * GetFirstFocusableControl (int id)
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
void AllocResources () override
void FreeResources (bool immediately=false) override
void DynamicResourceAlloc (bool bOnOff) override
bool CanFocus () const override
void AssignDepth () override
void SetInitialVisibility () override
bool IsAnimating (ANIMATION_TYPE anim) override
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
bool IsControlOnScreen (float pos, const CGUIControl *control) const
void ValidateOffset ()
void CalculateItemGap ()
float Size (const CGUIControl *control) const
void ScrollTo (float offset)
float GetAlignOffset () const
int GetNumItems () const
int GetSelectedItem () const
float GetControlOffset (const CGUIControl *control) const
Returns the position of the specified child control.
SGUIControlAndOffset GetFocusableControlAt (float target, int direction) const
Locate a visible and focusable child control at/close to the specified position.
void ScrollPages (float pages)
Scroll the list of controls, update the selected control and the pager.
void MoveTo (CGUIControl *control, float offset)
Change the selected control and scroll to the specified position.
CGUIControl * GetFirstFocusableControl () const
CGUIControl * GetLastFocusableControl () const
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
float m_itemGap
int m_pageControl
int m_focusedPosition
float m_totalSize
CScroller m_scroller
int m_lastScrollerValue
bool m_useControlPositions
ORIENTATION m_orientation
uint32_t m_alignment
float m_minSize
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Detailed Description
list of controls that is scrollable
Constructor & Destructor Documentation
CGUIControlGroupList()
CGUIControlGroupList::CGUIControlGroupList (int parentID, int controlID, float posX, float posY, float width, float height, float itemGap, int pageControl, ORIENTATION orientation, bool useControlPositions, uint32_t alignment, const CScroller & scroller)
References CGUIControl::ControlType, CGUIControl::GUICONTROL_GROUPLIST, m_alignment, m_focusedPosition, m_itemGap, m_lastScrollerValue, m_minSize, m_orientation, m_pageControl, m_totalSize, and m_useControlPositions.
~CGUIControlGroupList()
CGUIControlGroupList::~CGUIControlGroupList (void) override default
Member Function Documentation
AddControl()
void CGUIControlGroupList::AddControl (CGUIControl * control, int position = -1) override virtual
Reimplemented from CGUIControlGroup.
References ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NAV_BACK, CGUIControlGroup::AddControl(), CGUIControl::GetAction(), CGUIControl::GetID(), CGUIAction::GetNavigation(), GetTotalSize(), CGUIAction::HasActionsMeetingCondition(), CGUIControlGroup::m_children, m_orientation, m_totalSize, m_useControlPositions, CGUIControl::SetAction(), CGUIControl::SetPosition(), and VERTICAL.
Referenced by KODI::GAME::CGUIFeatureList::Load(), KODI::GAME::CGUIControllerList::Refresh(), and CGUIDialogContextMenu::SetupButtons().
CalculateItemGap()
void CGUIControlGroupList::CalculateItemGap () protected
References m_alignment, CGUIControlGroup::m_children, m_itemGap, Size(), and XBFONT_JUSTIFIED.
Referenced by ValidateOffset().
ClearAll()
void CGUIControlGroupList::ClearAll () override virtual
Reimplemented from CGUIControlGroup.
References CGUIControlGroup::ClearAll(), m_scroller, m_totalSize, and CScroller::SetValue().
Referenced by KODI::GAME::CGUIControllerList::CleanupButtons(), KODI::GAME::CGUIFeatureList::CleanupButtons(), CGUIDialogSettingsBase::FreeControls(), and CGUIDialogSettingsBase::FreeSettingsControls().
Clone()
CGUIControlGroupList * CGUIControlGroupList::Clone (void) const inline override virtual
Reimplemented from CGUIControlGroup.
GetAlignOffset()
float CGUIControlGroupList::GetAlignOffset () const protected
References m_alignment, m_totalSize, Size(), XBFONT_CENTER_X, XBFONT_JUSTIFIED, and XBFONT_RIGHT.
Referenced by Process(), Render(), SendMouseEvent(), and UnfocusFromPoint().
GetCondition()
bool CGUIControlGroupList::GetCondition (int condition, int data) const override virtual
Reimplemented from CGUIControl.
References CONTAINER_HAS_NEXT, CONTAINER_HAS_PREVIOUS, CONTAINER_POSITION, data(), CScroller::GetValue(), m_focusedPosition, m_scroller, m_totalSize, and Size().
GetControlOffset()
float CGUIControlGroupList::GetControlOffset (const CGUIControl * control) const protected
Returns the position of the specified child control.
Parameters
control The control to be located.
Returns
Position of the control. -1 for a control that is not visible or cannot be found.
References CGUIControlGroup::m_children, m_itemGap, and Size().
Referenced by ScrollPages().
GetFirstFocusableControl() [1/2]
CGUIControl * CGUIControlGroupList::GetFirstFocusableControl () const protected
Return the first visible and focusable child control.
References CGUIControl::CanFocus(), and CGUIControlGroup::m_children.
Referenced by OnAction(), and OnMessage().
GetFirstFocusableControl() [2/2]
CGUIControl * CGUIControlGroup::GetFirstFocusableControl (int id) virtual
Reimplemented from CGUIControlGroup.
GetFocusableControlAt()
SGUIControlAndOffset CGUIControlGroupList::GetFocusableControlAt (float target, int direction) const protected
Locate a visible and focusable child control at/close to the specified position.
Parameters
target Ideal position of the control
direction >0: Favor the control at or after the target for direction, otherwise the control before or at target.
Returns
Best match control & position. The control may be null and the offset 0 if there aren't any visible focusable controls in the list.
References CGUIControlGroup::m_children, m_itemGap, and Size().
Referenced by ScrollPages().
GetHeight()
float CGUIControlGroupList::GetHeight () const override virtual
Reimplemented from CGUIControl.
References CLAMP, CGUIControl::GetHeight(), CGUIControl::m_height, m_minSize, m_orientation, m_totalSize, and VERTICAL.
Referenced by CGUIDialogContextMenu::SetupButtons().
GetLabel()
std::string CGUIControlGroupList::GetLabel (int info) const virtual
References CONTAINER_CURRENT_ITEM, CONTAINER_NUM_ITEMS, CONTAINER_POSITION, GetNumItems(), GetSelectedItem(), and m_focusedPosition.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel().
GetLastFocusableControl()
CGUIControl * CGUIControlGroupList::GetLastFocusableControl () const protected
Return the last visible and focusable child control.
References CGUIControl::CanFocus(), and CGUIControlGroup::m_children.
Referenced by OnAction(), and OnMessage().
GetNumItems()
int CGUIControlGroupList::GetNumItems () const protected
References CGUIControlGroup::m_children.
Referenced by GetLabel().
GetOrientation()
ORIENTATION CGUIControlGroupList::GetOrientation () const inline
References m_orientation.
Referenced by CGUIDialogContextMenu::OnWindowLoaded(), and CGUIDialogContextMenu::SetupButtons().
GetSelectedItem()
int CGUIControlGroupList::GetSelectedItem () const protected
References index(), and CGUIControlGroup::m_children.
Referenced by GetLabel().
GetTotalSize()
float CGUIControlGroupList::GetTotalSize () const
Calculate total size of child controls area (including gaps between controls)
References CGUIControl::IsVisible(), CGUIControlGroup::m_children, m_itemGap, and Size().
Referenced by AddControl(), KODI::GAME::CGUIFeatureList::Load(), and ValidateOffset().
GetWidth()
float CGUIControlGroupList::GetWidth () const override virtual
Reimplemented from CGUIControl.
References CLAMP, CGUIControl::GetWidth(), HORIZONTAL, m_minSize, m_orientation, m_totalSize, and CGUIControl::m_width.
Referenced by CGUIDialogContextMenu::SetupButtons().
IsControlOnScreen()
bool CGUIControlGroupList::IsControlOnScreen (float pos, const CGUIControl * control) const protected
References CScroller::GetValue(), m_scroller, and Size().
Referenced by OnMessage(), Process(), SendMouseEvent(), and UnfocusFromPoint().
MoveTo()
void CGUIControlGroupList::MoveTo (CGUIControl * control, float offset) protected
Change the selected control and scroll to the specified position.
Parameters
control New selected control
offset Offset of the top of the visible view
References CGUIControlGroup::GetFocusedControl(), CGUIControl::GetID(), GUI_MSG_LOSTFOCUS, GUI_MSG_SETFOCUS, CGUIControl::OnMessage(), and ScrollTo().
Referenced by OnAction().
OnAction()
bool CGUIControlGroupList::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControlGroup.
References ACTION_FIRST_PAGE, ACTION_LAST_PAGE, ACTION_PAGE_DOWN, ACTION_PAGE_UP, GetFirstFocusableControl(), GetLastFocusableControl(), m_totalSize, MoveTo(), CGUIControlGroup::OnAction(), ScrollPages(), and Size().
OnMessage()
bool CGUIControlGroupList::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControlGroup.
References CGUIControl::CanFocus(), CGUIControl::GetControl(), CGUIMessage::GetControlId(), GetFirstFocusableControl(), CGUIControl::GetID(), GetLastFocusableControl(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIMessage::GetSenderId(), CScroller::GetValue(), GUI_MSG_FOCUSED, GUI_MSG_PAGE_CHANGE, GUI_MSG_SETFOCUS, IsControlOnScreen(), CGUIControl::IsVisible(), CGUIControlGroup::m_children, CGUIControlGroup::m_focusedControl, m_itemGap, m_pageControl, m_scroller, m_totalSize, CGUIControlGroup::OnMessage(), ScrollTo(), Size(), and ValidateOffset().
OnMouseEvent()
EVENT_RESULT CGUIControlGroupList::OnMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) override protected virtual
Perform a mouse action.
Mouse actions are sent from the window to all controls, and each control can react based on the event and location of the actions.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
SendMouseEvent, HitTest, CanFocusFromPoint, CMouseEvent
Reimplemented from CGUIControl.
References ACTION_GESTURE_ABORT, ACTION_GESTURE_BEGIN, ACTION_GESTURE_END, ACTION_GESTURE_PAN, ACTION_MOUSE_WHEEL_DOWN, ACTION_MOUSE_WHEEL_UP, CLAMP, EVENT_RESULT_HANDLED, EVENT_RESULT_UNHANDLED, CGUIControl::GetID(), CGUIControl::GetParentID(), CScroller::GetValue(), GUI_MSG_EXCLUSIVE_MOUSE, HORIZONTAL, CGUIControl::IsVisible(), CGUIControlGroup::m_children, KODI::MOUSE::CMouseEvent::m_id, m_itemGap, KODI::MOUSE::CMouseEvent::m_offsetX, m_orientation, m_scroller, m_totalSize, ScrollTo(), CGUIControl::SendWindowMessage(), SetInvalid(), CScroller::SetValue(), and Size().
Referenced by SendMouseEvent().
Process()
void CGUIControlGroupList::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControlGroup.
References CGUIControl::DoProcess(), GetAlignOffset(), CWinSystemBase::GetGfxContext(), CGUIControl::GetParentID(), CScroller::GetValue(), CServiceBroker::GetWinSystem(), GUI_MSG_ITEM_SELECT, GUI_MSG_LABEL_RESET, GUIPROFILER_VISIBILITY_BEGIN, GUIPROFILER_VISIBILITY_END, CGUIControl::HasFocus(), index(), IsControlOnScreen(), CGUIControl::IsVisible(), CGUIControlGroup::m_children, m_focusedPosition, m_itemGap, m_lastScrollerValue, m_orientation, m_pageControl, CGUIControl::m_posX, CGUIControl::m_posY, m_scroller, m_totalSize, CGUIControl::MarkDirtyRegion(), CGUIControl::Process(), CGraphicContext::RestoreOrigin(), CGUIControl::SendWindowMessage(), CGraphicContext::SetOrigin(), Size(), CScroller::Update(), CGUIControl::UpdateVisibility(), ValidateOffset(), and VERTICAL.
Render()
void CGUIControlGroupList::Render () override virtual
Reimplemented from CGUIControlGroup.
References CGUIControl::DoRender(), GetAlignOffset(), CWinSystemBase::GetGfxContext(), CScroller::GetValue(), CServiceBroker::GetWinSystem(), CGUIControl::HasFocus(), CGUIControl::IsVisible(), CGUIControlGroup::m_children, CGUIControl::m_height, m_itemGap, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, CGUIControlGroup::m_renderFocusedLast, m_scroller, CGUIControl::m_width, CGUIControl::Render(), CGraphicContext::RestoreClipRegion(), CGraphicContext::RestoreOrigin(), CGraphicContext::SetOrigin(), Size(), and VERTICAL.
ScrollPages()
void CGUIControlGroupList::ScrollPages (float pages) protected
Scroll the list of controls, update the selected control and the pager.
Parameters
pages direction and amount of scrolling. For example 1 to scroll down/right one page, -0.5 to scroll up/left half a page
References SGUIControlAndOffset::control, GetControlOffset(), GetFocusableControlAt(), CGUIControlGroup::GetFocusedControl(), CGUIControl::GetID(), CScroller::GetValue(), GUI_MSG_LOSTFOCUS, GUI_MSG_SETFOCUS, m_scroller, m_totalSize, SGUIControlAndOffset::offset, CGUIControl::OnMessage(), ScrollTo(), Size(), and ValidateOffset().
Referenced by OnAction().
ScrollTo()
void CGUIControlGroupList::ScrollTo (float offset) protected
References CScroller::IsScrolling(), m_scroller, CGUIControl::MarkDirtyRegion(), CScroller::ScrollTo(), and SetInvalid().
Referenced by MoveTo(), OnMessage(), OnMouseEvent(), and ScrollPages().
SendMouseEvent()
EVENT_RESULT CGUIControlGroupList::SendMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) override virtual
React to a mouse event.
Mouse events are sent from the window to all controls, and each control can react based on the event and location of the event.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
HitTest, CanFocusFromPoint, CMouseEvent, EVENT_RESULT
Reimplemented from CGUIControlGroup.
References CGUIControl::CanFocus(), EVENT_RESULT_UNHANDLED, GetAlignOffset(), CScroller::GetValue(), CGUIControl::HitTest(), TransformMatrix::InverseTransformPosition(), IsControlOnScreen(), CGUIControl::IsVisible(), CGUIControlGroup::m_children, CGUIControlGroup::m_focusedControl, m_itemGap, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, m_scroller, CGUIControl::m_transform, OnMouseEvent(), CGUIControl::SendMouseEvent(), Size(), VERTICAL, CPointGen< T >::x, and CPointGen< T >::y.
SetInvalid()
void CGUIControlGroupList::SetInvalid () override virtual
Reimplemented from CGUIControl.
References m_lastScrollerValue, and CGUIControl::SetInvalid().
Referenced by OnMouseEvent(), and ScrollTo().
SetMinSize()
void CGUIControlGroupList::SetMinSize (float minWidth, float minHeight)
References m_minSize, m_orientation, and VERTICAL.
Size() [1/2]
float CGUIControlGroupList::Size () const inline virtual
References CGUIControl::m_height, m_orientation, CGUIControl::m_width, and VERTICAL.
Referenced by CalculateItemGap(), GetAlignOffset(), GetCondition(), GetControlOffset(), GetFocusableControlAt(), GetTotalSize(), IsControlOnScreen(), OnAction(), OnMessage(), OnMouseEvent(), Process(), Render(), ScrollPages(), SendMouseEvent(), CGUIDialogContextMenu::SetupButtons(), UnfocusFromPoint(), and ValidateOffset().
Size() [2/2]
float CGUIControlGroupList::Size (const CGUIControl * control) const inline protected
References CGUIControl::GetHeight(), CGUIControl::GetWidth(), CGUIControl::GetXPosition(), CGUIControl::GetYPosition(), m_orientation, and VERTICAL.
UnfocusFromPoint()
void CGUIControlGroupList::UnfocusFromPoint (const CPoint & point) override virtual
Unfocus the control if the given point on screen is not within it's boundary.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
See also
CanFocusFromPoint
Reimplemented from CGUIControlGroup.
References GetAlignOffset(), CScroller::GetValue(), TransformMatrix::InverseTransformPosition(), IsControlOnScreen(), CGUIControl::IsVisible(), CGUIControlGroup::m_children, m_itemGap, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, m_scroller, CGUIControl::m_transform, Size(), CGUIControl::UnfocusFromPoint(), VERTICAL, CPointGen< T >::x, and CPointGen< T >::y.
ValidateOffset()
void CGUIControlGroupList::ValidateOffset () protected
References CalculateItemGap(), GetTotalSize(), CScroller::GetValue(), m_scroller, m_totalSize, CScroller::SetValue(), and Size().
Referenced by OnMessage(), Process(), and ScrollPages().
Member Data Documentation
m_alignment
uint32_t CGUIControlGroupList::m_alignment protected
Referenced by CalculateItemGap(), CGUIControlGroupList(), and GetAlignOffset().
m_focusedPosition
int CGUIControlGroupList::m_focusedPosition protected
Referenced by CGUIControlGroupList(), GetCondition(), GetLabel(), and Process().
m_itemGap
float CGUIControlGroupList::m_itemGap protected
Referenced by CalculateItemGap(), CGUIControlGroupList(), GetControlOffset(), GetFocusableControlAt(), GetTotalSize(), OnMessage(), OnMouseEvent(), Process(), Render(), SendMouseEvent(), and UnfocusFromPoint().
m_lastScrollerValue
int CGUIControlGroupList::m_lastScrollerValue protected
Referenced by CGUIControlGroupList(), Process(), and SetInvalid().
m_minSize
float CGUIControlGroupList::m_minSize protected
Referenced by CGUIControlGroupList(), GetHeight(), GetWidth(), and SetMinSize().
m_orientation
ORIENTATION CGUIControlGroupList::m_orientation protected
Referenced by AddControl(), CGUIControlGroupList(), GetHeight(), GetOrientation(), GetWidth(), OnMouseEvent(), Process(), Render(), SendMouseEvent(), SetMinSize(), Size(), Size(), and UnfocusFromPoint().
m_pageControl
int CGUIControlGroupList::m_pageControl protected
Referenced by CGUIControlGroupList(), OnMessage(), and Process().
m_scroller
CScroller CGUIControlGroupList::m_scroller protected
Referenced by ClearAll(), GetCondition(), IsControlOnScreen(), OnMessage(), OnMouseEvent(), Process(), Render(), ScrollPages(), ScrollTo(), SendMouseEvent(), UnfocusFromPoint(), and ValidateOffset().
m_totalSize
float CGUIControlGroupList::m_totalSize protected
Referenced by AddControl(), CGUIControlGroupList(), ClearAll(), GetAlignOffset(), GetCondition(), GetHeight(), GetWidth(), OnAction(), OnMessage(), OnMouseEvent(), Process(), ScrollPages(), and ValidateOffset().
m_useControlPositions
bool CGUIControlGroupList::m_useControlPositions protected
Referenced by AddControl(), and CGUIControlGroupList().
The documentation for this class was generated from the following files:
GUIControlGroupList.h
GUIControlGroupList.cpp