Kodi Documentation: KODI::PLATFORM::FILESYSTEM::anonymous_namespace{Filesystem.cpp} Namespace Reference
KODI::PLATFORM::FILESYSTEM::anonymous_namespace{Filesystem.cpp} Namespace Reference
Functions
std::wstring temp_directory_path_w (std::error_code &ec)
Function Documentation
temp_directory_path_w()
std::wstring KODI::PLATFORM::FILESYSTEM::anonymous_namespace{Filesystem.cpp}::temp_directory_path_w (std::error_code & ec)
References err(), GetLastError(), MAX_PATH, and temp_directory_path_w().
Referenced by temp_directory_path_w().