Kodi Documentation: CGUIControlColorButtonSetting Class Reference
CGUIControlColorButtonSetting Class Reference
#include <GUIControlSettings.h>
Public Member Functions
CGUIControlColorButtonSetting (CGUIColorButtonControl *pColorControl, int id, const std::shared_ptr< CSetting > &pSetting, ILocalizer *localizer)
~CGUIControlColorButtonSetting () override
void Select (bool bSelect)
CGUIControl * GetControl () override
bool OnClick () override
void Clear () override
Clears the attached control.
Public Member Functions inherited from CGUIControlBaseSetting
CGUIControlBaseSetting (int id, std::shared_ptr< CSetting > pSetting, ILocalizer *localizer)
~CGUIControlBaseSetting () override=default
int GetID () const
std::shared_ptr< CSetting > GetSetting ()
void SetDelayed ()
Specifies that this setting should update after a delay Useful for settings that have options to navigate through and may take a while, or require additional input to update once the final setting is chosen. Settings default to updating instantly.
bool IsDelayed () const
Returns whether this setting should have delayed update.
bool IsEnabled () const
Returns whether this setting is enabled or disabled This state is independent of the real enabled state of a setting control but represents the enabled state of the setting itself based on specific conditions.
bool IsValid () const
Returns whether the setting's value is valid or not.
void SetValid (bool valid)
void UpdateFromControl ()
void UpdateFromSetting (bool updateDisplayOnly=false)
Protected Member Functions
void Update (bool fromControl, bool updateDisplayOnly) override
Protected Member Functions inherited from CGUIControlBaseSetting
std::string Localize (std::uint32_t code) const override
Protected Member Functions inherited from ILocalizer
ILocalizer ()=default
virtual ~ILocalizer ()=default
Private Attributes
CGUIColorButtonControl * m_pColorButton
Additional Inherited Members
Protected Attributes inherited from CGUIControlBaseSetting
int m_id
std::shared_ptr< CSetting > m_pSetting
ILocalizer * m_localizer
bool m_delayed = false
bool m_valid = true
Constructor & Destructor Documentation
CGUIControlColorButtonSetting()
CGUIControlColorButtonSetting::CGUIControlColorButtonSetting (CGUIColorButtonControl * pColorControl, int id, const std::shared_ptr< CSetting > & pSetting, ILocalizer * localizer)
References m_pColorButton, and CGUIControl::SetID().
~CGUIControlColorButtonSetting()
CGUIControlColorButtonSetting::~CGUIControlColorButtonSetting () override default
Member Function Documentation
Clear()
void CGUIControlColorButtonSetting::Clear () inline override virtual
Clears the attached control.
Implements CGUIControlBaseSetting.
References m_pColorButton.
GetControl()
CGUIControl * CGUIControlColorButtonSetting::GetControl () inline override virtual
Reimplemented from CGUIControlBaseSetting.
References m_pColorButton.
OnClick()
bool CGUIControlColorButtonSetting::OnClick () override virtual
Reimplemented from CGUIControlBaseSetting.
References CServiceBroker::GetGUI(), CGUIDialogColorPicker::GetSelectedColor(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), CGUIControlBaseSetting::IsValid(), CGUIDialogColorPicker::LoadColors(), CGUIControlBaseSetting::Localize(), m_pColorButton, CGUIControlBaseSetting::m_pSetting, CGUIDialog::Open(), CGUIDialogColorPicker::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogColorPicker::SetSelectedColor(), CGUIControlBaseSetting::SetValid(), and WINDOW_DIALOG_COLOR_PICKER.
Select()
void CGUIControlColorButtonSetting::Select (bool bSelect)
Update()
void CGUIControlColorButtonSetting::Update (bool fromControl, bool updateDisplayOnly) override protected virtual
Reimplemented from CGUIControlBaseSetting.
References GetValue(), m_pColorButton, CGUIControlBaseSetting::m_pSetting, CGUIColorButtonControl::SetImageBoxColor(), and CGUIControlBaseSetting::Update().
Member Data Documentation
m_pColorButton
CGUIColorButtonControl* CGUIControlColorButtonSetting::m_pColorButton private
Referenced by CGUIControlColorButtonSetting(), Clear(), GetControl(), OnClick(), and Update().
The documentation for this class was generated from the following files:
GUIControlSettings.h
GUIControlSettings.cpp