Kodi Documentation: CDVDDemuxFFmpeg Class Reference
CDVDDemuxFFmpeg Class Reference
#include <DVDDemuxFFmpeg.h>
Public Member Functions
CDVDDemuxFFmpeg ()
~CDVDDemuxFFmpeg () override
bool Open (const std::shared_ptr< CDVDInputStream > &pInput, bool fileinfo)
void Dispose ()
bool Reset () override
void Flush () override
void Abort () override
void SetSpeed (int iSpeed) override
std::string GetFileName () override
DemuxPacket * Read () override
DemuxPacket * ReadInternal (bool keep)
bool SeekTime (double time, bool backwards=false, double *startpts=NULL) override
bool SeekByte (int64_t pos)
int GetStreamLength () override
CDemuxStream * GetStream (int iStreamId) const override
Finds stream based on unique id.
std::vector< CDemuxStream * > GetStreams () const override
int GetNrOfStreams () const override
int GetPrograms (std::vector< ProgramInfo > &programs) override
void SetProgram (int progId) override
bool SeekChapter (int chapter, double *startpts=NULL) override
int GetChapterCount () override
int GetChapter () override
void GetChapterName (std::string &strChapterName, int chapterIdx=-1) override
int64_t GetChapterPos (int chapterIdx=-1) override
std::string GetStreamCodecName (int iStreamId) override
bool Aborted ()
Public Member Functions inherited from CDVDDemux
CDVDDemux ()
virtual ~CDVDDemux ()=default
virtual void FillBuffer (bool mode)
virtual CDemuxStream * GetStream (int64_t demuxerId, int iStreamId) const
int GetNrOfSubtitleStreams ()
virtual std::string GetStreamCodecName (int64_t demuxerId, int iStreamId)
virtual void EnableStream (int64_t demuxerId, int id, bool enable)
virtual void OpenStream (int64_t demuxerId, int id)
virtual void SetVideoResolution (unsigned int width, unsigned int height)
int64_t GetDemuxerId ()
Public Attributes
AVFormatContext * m_pFormatContext
std::shared_ptr< CDVDInputStream > m_pInput
Protected Member Functions
CDemuxStream * AddStream (int streamIdx)
void AddStream (int streamIdx, CDemuxStream *stream)
Adds or updates a demux stream based in ffmpeg id.
void CreateStreams (unsigned int program=UINT_MAX)
void DisposeStreams ()
void ParsePacket (AVPacket *pkt)
TRANSPORT_STREAM_STATE TransportStreamAudioState ()
TRANSPORT_STREAM_STATE TransportStreamVideoState ()
bool IsTransportStreamReady ()
void ResetVideoStreams ()
AVDictionary * GetFFMpegOptionsFromInput ()
double ConvertTimestamp (int64_t pts, int den, int num)
bool IsProgramChange ()
unsigned int HLSSelectProgram ()
std::string GetStereoModeFromMetadata (AVDictionary *pMetadata)
std::string ConvertCodecToInternalStereoMode (const std::string &mode, const StereoModeConversionMap *conversionMap)
void GetL16Parameters (int &channels, int &samplerate)
double SelectAspect (AVStream *st, bool &forced)
StreamHdrType DetermineHdrType (AVStream *pStream)
Protected Member Functions inherited from CDVDDemux
virtual void EnableStream (int id, bool enable)
virtual void OpenStream (int id)
int GetNrOfStreams (StreamType streamType)
Protected Attributes
CCriticalSection m_critSection
std::map< int, CDemuxStream * > m_streams
std::map< int, std::unique_ptr< CDemuxParserFFmpeg > > m_parsers
AVIOContext * m_ioContext
double m_currentPts
bool m_bMatroska
bool m_bAVI
bool m_bSup
int m_speed
unsigned int m_program
unsigned int m_streamsInProgram
unsigned int m_newProgram
unsigned int m_initialProgramNumber
int m_seekStream
XbmcThreads::EndTime m_timeout
struct {
AVPacket pkt
int result
} m_pkt
bool m_streaminfo
bool m_reopen = false
bool m_checkTransportStream
int m_displayTime = 0
double m_dtsAtDisplayTime
bool m_seekToKeyFrame = false
double m_startTime = 0
Protected Attributes inherited from CDVDDemux
int64_t m_demuxerId
Friends
class CDemuxStreamAudioFFmpeg
class CDemuxStreamVideoFFmpeg
class CDemuxStreamSubtitleFFmpeg
Constructor & Destructor Documentation
CDVDDemuxFFmpeg()
CDVDDemuxFFmpeg::CDVDDemuxFFmpeg ()
References DVD_NOPTS_VALUE, DVD_PLAYSPEED_NORMAL, m_bAVI, m_bMatroska, m_bSup, m_checkTransportStream, m_currentPts, m_dtsAtDisplayTime, m_ioContext, m_pFormatContext, m_pkt, m_program, m_speed, and m_streaminfo.
~CDVDDemuxFFmpeg()
CDVDDemuxFFmpeg::~CDVDDemuxFFmpeg () override
References Dispose(), and ff_flush_avutil_log_buffers().
Member Function Documentation
Abort()
void CDVDDemuxFFmpeg::Abort () override virtual
Reimplemented from CDVDDemux.
References m_timeout.
Aborted()
bool CDVDDemuxFFmpeg::Aborted ()
References m_pInput, and m_timeout.
Referenced by interrupt_cb().
AddStream() [1/2]
CDemuxStream * CDVDDemuxFFmpeg::AddStream (int streamIdx) protected
Todo:
: temporary font file management should be completely removed, by sending font data to the subtitle renderer and using libass ass_add_font to add the fonts directly in memory.
@FIXME: Matroska v4 support BCP-47 language code with LanguageIETF element that have the priority over the Language element, but this is not currently implemented in to ffmpeg library. Since ffmpeg read only the Language element all tracks will be identified with same language (of Language element). As workaround to allow set the right language code we provide the possibility to set the language code in the title field, this allow to kodi to recognize the right language and select the right track to be played at playback starts.
References AddStream(), CDemuxStreamVideo::bForcedAspect, CDemuxStreamVideo::bitDepth, CDemuxStreamVideo::bPTSInvalid, CDemuxStreamVideo::bVFR, CDemuxStreamAudioFFmpeg, CDemuxStreamSubtitleFFmpeg, CDemuxStreamVideoFFmpeg, XFILE::CFile::Close(), CDemuxStream::codec, CDemuxStream::codec_fourcc, CDemuxStream::codecName, CDemuxStreamVideo::colorPrimaries, CDemuxStreamVideo::colorRange, CDemuxStreamVideo::colorSpace, CDemuxStreamVideo::colorTransferCharacteristic, CDemuxStreamVideo::contentLightMetaData, XFILE::CDirectory::Create(), XFILE::CFile::Delete(), CDemuxStream::demuxerId, DetermineHdrType(), CDemuxStreamVideo::dovi, CDemuxStream::dvdNavId, DVDSTREAM_TYPE_BLURAY, DVDSTREAM_TYPE_DVD, CDemuxStream::extraData, CDemuxStreamVideo::fAspect, CLangCodeExpander::FindLanguageCodeWithSubtag(), CDemuxStream::flags, g_LangCodeExpander, CServiceBroker::GetSettingsComponent(), GetStereoModeFromMetadata(), CDemuxStreamVideo::hdr_type, HDR_TYPE_DOLBYVISION, CDemuxStreamVideo::iBitRate, CDemuxStreamAudio::iBitRate, CDemuxStreamVideo::iBitsPerPixel, CDemuxStreamAudio::iBitsPerSample, CDemuxStreamAudio::iBlockAlign, CDemuxStreamAudio::iChannelLayout, CDemuxStreamAudio::iChannels, CDemuxStream::iDuration, CDemuxStreamVideo::iFpsRate, CDemuxStreamVideo::iFpsScale, CDemuxStreamVideo::iHeight, int64_t(), CDemuxStreamVideo::interlaced, CDemuxStreamVideo::iOrientation, CDemuxStreamAudio::iSampleRate, IsTransportStreamReady(), CDemuxStreamVideo::iWidth, CDemuxStream::language, LEGAL_WIN32_COMPAT, CDemuxStream::level, CLog::Log(), LOGDEBUG, LOGERROR, m_bAVI, m_bMatroska, CDemuxStreamAudio::m_channelLayoutName, CDVDDemux::m_demuxerId, CDemuxStreamVideoFFmpeg::m_description, CDemuxStreamAudioFFmpeg::m_description, CDemuxStreamSubtitleFFmpeg::m_description, m_pFormatContext, m_pInput, m_streaminfo, m_streams, CUtil::MakeLegalFileName(), CDemuxStreamVideo::masteringMetaData, CDemuxStream::pPrivate, CDemuxStream::profile, SelectAspect(), CSettings::SETTING_VIDEOPLAYER_TELETEXTENABLED, CDemuxStream::source, CDemuxStreamVideo::stereo_mode, STREAM_DATA, STREAM_NONE, STREAM_SOURCE_DEMUX, STREAM_TELETEXT, KODI::UTILS::FONT::FONTPATH::TEMP, CDemuxStream::type, and CDemuxStream::uniqueId.
Referenced by AddStream(), CreateStreams(), and ReadInternal().
AddStream() [2/2]
void CDVDDemuxFFmpeg::AddStream (int streamIdx, CDemuxStream * stream) protected
Adds or updates a demux stream based in ffmpeg id.
References CLog::Log(), LOGDEBUG, m_streams, and CDemuxStream::uniqueId.
ConvertCodecToInternalStereoMode()
std::string CDVDDemuxFFmpeg::ConvertCodecToInternalStereoMode (const std::string & mode, const StereoModeConversionMap * conversionMap) protected
References StereoModeConversionMap::mode, and name.
Referenced by GetStereoModeFromMetadata().
ConvertTimestamp()
double CDVDDemuxFFmpeg::ConvertTimestamp (int64_t pts, int den, int num) protected
References DVD_NOPTS_VALUE, DVD_TIME_BASE, int64_t(), m_bSup, m_checkTransportStream, m_pFormatContext, m_pInput, m_startTime, and NATIVE.
Referenced by GetChapter(), ReadInternal(), and SeekChapter().
CreateStreams()
void CDVDDemuxFFmpeg::CreateStreams (unsigned int program = UINT_MAX) protected
References AddStream(), DisposeStreams(), GetStream(), m_pFormatContext, m_program, and m_streamsInProgram.
Referenced by Open(), and ReadInternal().
DetermineHdrType()
StreamHdrType CDVDDemuxFFmpeg::DetermineHdrType (AVStream * pStream) protected
References HDR_TYPE_DOLBYVISION, HDR_TYPE_HDR10, HDR_TYPE_HLG, and HDR_TYPE_NONE.
Referenced by AddStream().
Dispose()
void CDVDDemuxFFmpeg::Dispose ()
References DisposeStreams(), DVD_PLAYSPEED_NORMAL, CLog::Log(), LOGWARNING, m_ioContext, m_pFormatContext, m_pInput, m_pkt, and m_speed.
Referenced by Open(), Reset(), and ~CDVDDemuxFFmpeg().
DisposeStreams()
void CDVDDemuxFFmpeg::DisposeStreams () protected
References m_parsers, and m_streams.
Referenced by CreateStreams(), and Dispose().
Flush()
void CDVDDemuxFFmpeg::Flush () override virtual
Implements CDVDDemux.
References DVD_NOPTS_VALUE, m_currentPts, m_displayTime, m_dtsAtDisplayTime, m_pFormatContext, m_pkt, and m_seekToKeyFrame.
Referenced by ReadInternal(), SeekChapter(), and SeekTime().
GetChapter()
int CDVDDemuxFFmpeg::GetChapter () override virtual
Reimplemented from CDVDDemux.
References ConvertTimestamp(), DVD_NOPTS_VALUE, m_currentPts, m_pFormatContext, and m_pInput.
Referenced by GetChapterName(), and GetChapterPos().
GetChapterCount()
int CDVDDemuxFFmpeg::GetChapterCount () override virtual
Reimplemented from CDVDDemux.
References m_pFormatContext, and m_pInput.
Referenced by GetChapterName(), and GetChapterPos().
GetChapterName()
void CDVDDemuxFFmpeg::GetChapterName (std::string & strChapterName, int chapterIdx = -1) override virtual
Reimplemented from CDVDDemux.
References GetChapter(), GetChapterCount(), m_pFormatContext, and m_pInput.
GetChapterPos()
int64_t CDVDDemuxFFmpeg::GetChapterPos (int chapterIdx = -1) override virtual
Reimplemented from CDVDDemux.
References GetChapter(), GetChapterCount(), int64_t(), m_pFormatContext, and m_pInput.
GetFFMpegOptionsFromInput()
AVDictionary * CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput () protected
References CURL, CURL::Get(), XFILE::CCurlFile::GetCookies(), CURL::GetProtocol(), CURL::GetProtocolOptions(), CServiceBroker::GetSettingsComponent(), CURL::IsProtocol(), CLog::Log(), LOGDEBUG, m_pInput, name, and value.
Referenced by Open().
GetFileName()
std::string CDVDDemuxFFmpeg::GetFileName () override virtual
Reimplemented from CDVDDemux.
References m_pInput.
GetL16Parameters()
void CDVDDemuxFFmpeg::GetL16Parameters (int & channels, int & samplerate) protected
References XFILE::CCurlFile::GetContentType(), CLog::Log(), LOGDEBUG, and m_pInput.
Referenced by Open().
GetNrOfStreams()
int CDVDDemuxFFmpeg::GetNrOfStreams () const override virtual
Implements CDVDDemux.
References m_streams.
Referenced by Open().
GetPrograms()
int CDVDDemuxFFmpeg::GetPrograms (std::vector< ProgramInfo > & programs) override virtual
Reimplemented from CDVDDemux.
References ProgramInfo::id, m_pFormatContext, m_program, ProgramInfo::name, and ProgramInfo::playing.
GetStereoModeFromMetadata()
std::string CDVDDemuxFFmpeg::GetStereoModeFromMetadata (AVDictionary * pMetadata) protected
References ConvertCodecToInternalStereoMode(), and WmvToInternalStereoModeMap.
Referenced by AddStream().
GetStream()
CDemuxStream * CDVDDemuxFFmpeg::GetStream (int iStreamId) const override virtual
Finds stream based on unique id.
Implements CDVDDemux.
References m_streams.
Referenced by CreateStreams(), GetStreamCodecName(), IsProgramChange(), ParsePacket(), and ReadInternal().
GetStreamCodecName()
std::string CDVDDemuxFFmpeg::GetStreamCodecName (int iStreamId) override virtual
Reimplemented from CDVDDemux.
References CDemuxStream::codec, GetStream(), and CDemuxStream::profile.
GetStreamLength()
int CDVDDemuxFFmpeg::GetStreamLength () override virtual
Reimplemented from CDVDDemux.
References m_pFormatContext.
GetStreams()
std::vector< CDemuxStream * > CDVDDemuxFFmpeg::GetStreams () const override virtual
Implements CDVDDemux.
References m_streams.
HLSSelectProgram()
unsigned int CDVDDemuxFFmpeg::HLSSelectProgram () protected
References CServiceBroker::GetSettingsComponent(), m_pFormatContext, and CSettings::SETTING_NETWORK_BANDWIDTH.
Referenced by Open().
IsProgramChange()
bool CDVDDemuxFFmpeg::IsProgramChange () protected
References CDemuxStream::codec, CDemuxStream::extraData, FFmpegExtraData::GetSize(), GetStream(), CDemuxStreamAudio::iChannels, m_initialProgramNumber, m_newProgram, m_pFormatContext, m_program, and m_streamsInProgram.
Referenced by ReadInternal().
IsTransportStreamReady()
bool CDVDDemuxFFmpeg::IsTransportStreamReady () protected
References m_checkTransportStream, m_pFormatContext, m_program, NONE, READY, TransportStreamAudioState(), and TransportStreamVideoState().
Referenced by AddStream(), ReadInternal(), and SeekTime().
Open()
bool CDVDDemuxFFmpeg::Open (const std::shared_ptr< CDVDInputStream > & pInput, bool fileinfo)
References CVariant::asInteger(), CreateStreams(), Dispose(), dvd_file_read(), dvd_file_seek(), DVD_NOPTS_VALUE, DVD_PLAYSPEED_NORMAL, DVDSTREAM_TYPE_BLURAY, DVDSTREAM_TYPE_DVD, DVDSTREAM_TYPE_FFMPEG, CURL::Get(), GetFFMpegOptionsFromInput(), GetL16Parameters(), GetNrOfStreams(), CServiceBroker::GetSettingsComponent(), HLSSelectProgram(), int64_t(), interrupt_cb(), CVariant::isNull(), CURL::IsProtocol(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_bAVI, m_bMatroska, m_bSup, m_checkTransportStream, m_currentPts, m_displayTime, m_dtsAtDisplayTime, m_initialProgramNumber, m_ioContext, m_newProgram, m_pFormatContext, m_pInput, m_program, m_reopen, m_seekStream, m_seekToKeyFrame, m_speed, m_startTime, m_streaminfo, m_timeout, Open(), ResetVideoStreams(), result, SEEK_POSSIBLE, CURL::SetProtocol(), and CURL::SetProtocolOptions().
Referenced by Open(), and Reset().
ParsePacket()
void CDVDDemuxFFmpeg::ParsePacket (AVPacket * pkt) protected
References GetPacketExtradata(), FFmpegExtraData::GetSize(), GetStream(), CLog::Log(), LOGERROR, m_parsers, m_pFormatContext, pkt, and FFmpegExtraData::TakeData().
Referenced by ReadInternal().
Read()
DemuxPacket * CDVDDemuxFFmpeg::Read () override virtual
Implements CDVDDemux.
References ReadInternal().
Referenced by dvd_file_read(), and SeekTime().
ReadInternal()
DemuxPacket * CDVDDemuxFFmpeg::ReadInternal (bool keep)
References AddStream(), CDVDDemuxUtils::AllocateDemuxPacket(), CDemuxStream::codec, ConvertTimestamp(), CreateStreams(), DEMUX_PACKET::demuxerId, DEMUX_PACKET::dispTime, DMX_SPECIALID_STREAMCHANGE, DEMUX_PACKET::dts, DEMUX_PACKET::duration, DVD_NOPTS_VALUE, DVD_SEC_TO_TIME(), DVD_TIME_TO_MSEC(), Flush(), CDVDDemuxUtils::FreeDemuxPacket(), GetStream(), CDVDInputStream::IDisplayTime::GetTime(), CDemuxStreamAudio::iChannels, CDemuxStreamVideo::iHeight, CDemuxStreamAudio::iSampleRate, DEMUX_PACKET::iSize, IsProgramChange(), IsTransportStreamReady(), DEMUX_PACKET::iStreamId, CLog::Log(), LOGERROR, LOGINFO, m_bAVI, m_critSection, m_currentPts, CDVDDemux::m_demuxerId, m_displayTime, m_dtsAtDisplayTime, m_pFormatContext, m_pInput, m_pkt, m_program, m_seekToKeyFrame, m_timeout, ParsePacket(), DEMUX_PACKET::pData, CDemuxStream::pPrivate, DEMUX_PACKET::pts, DEMUX_PACKET::recoveryPoint, CDVDDemuxUtils::StoreSideData(), STREAM_AUDIO, STREAM_VIDEO, CDemuxStream::type, and CDemuxStream::uniqueId.
Referenced by Read(), and SeekTime().
Reset()
bool CDVDDemuxFFmpeg::Reset () override virtual
Implements CDVDDemux.
References Dispose(), m_pInput, and Open().
ResetVideoStreams()
void CDVDDemuxFFmpeg::ResetVideoStreams () protected
References m_pFormatContext.
Referenced by Open().
SeekByte()
bool CDVDDemuxFFmpeg::SeekByte (int64_t pos)
References DVD_NOPTS_VALUE, m_critSection, m_currentPts, m_pFormatContext, and m_pkt.
SeekChapter()
bool CDVDDemuxFFmpeg::SeekChapter (int chapter, double * startpts = NULL) override virtual
Reimplemented from CDVDDemux.
References ConvertTimestamp(), DVD_SEC_TO_TIME(), DVD_TIME_TO_MSEC(), Flush(), CLog::Log(), LOGDEBUG, m_pFormatContext, m_pInput, and SeekTime().
SeekTime()
bool CDVDDemuxFFmpeg::SeekTime (double time, bool backwards = false, double * startpts = NULL) override virtual
Implements CDVDDemux.
References DVD_MSEC_TO_TIME(), DVD_NOPTS_VALUE, DVD_TIME_BASE, DVDSTREAM_TYPE_FFMPEG, Flush(), CDVDDemuxUtils::FreeDemuxPacket(), int64_t(), IsTransportStreamReady(), CLog::Log(), LOGDEBUG, LOGERROR, m_bSup, m_checkTransportStream, m_critSection, m_currentPts, m_pFormatContext, m_pInput, m_pkt, m_seekStream, m_seekToKeyFrame, m_startTime, pkt, CDVDInputStream::IPosTime::PosTime(), Read(), ReadInternal(), SEEK_POSSIBLE, and KODI::TIME::Sleep().
Referenced by SeekChapter().
SelectAspect()
double CDVDDemuxFFmpeg::SelectAspect (AVStream * st, bool & forced) protected
References m_bMatroska.
Referenced by AddStream().
SetProgram()
void CDVDDemuxFFmpeg::SetProgram (int progId) override virtual
Reimplemented from CDVDDemux.
References m_newProgram.
SetSpeed()
void CDVDDemuxFFmpeg::SetSpeed (int iSpeed) override virtual
Reimplemented from CDVDDemux.
References DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, m_pFormatContext, and m_speed.
TransportStreamAudioState()
TRANSPORT_STREAM_STATE CDVDDemuxFFmpeg::TransportStreamAudioState () protected
References m_pFormatContext, m_pkt, m_program, m_seekStream, m_startTime, NONE, NOTREADY, and READY.
Referenced by IsTransportStreamReady().
TransportStreamVideoState()
TRANSPORT_STREAM_STATE CDVDDemuxFFmpeg::TransportStreamVideoState () protected
References m_pFormatContext, m_pkt, m_program, m_seekStream, m_startTime, NONE, NOTREADY, and READY.
Referenced by IsTransportStreamReady().
Friends And Related Symbol Documentation
CDemuxStreamAudioFFmpeg
friend class CDemuxStreamAudioFFmpeg friend
Referenced by AddStream().
CDemuxStreamSubtitleFFmpeg
friend class CDemuxStreamSubtitleFFmpeg friend
Referenced by AddStream().
CDemuxStreamVideoFFmpeg
friend class CDemuxStreamVideoFFmpeg friend
Referenced by AddStream().
Member Data Documentation
m_bAVI
bool CDVDDemuxFFmpeg::m_bAVI protected
Referenced by AddStream(), CDVDDemuxFFmpeg(), Open(), and ReadInternal().
m_bMatroska
bool CDVDDemuxFFmpeg::m_bMatroska protected
Referenced by AddStream(), CDVDDemuxFFmpeg(), Open(), and SelectAspect().
m_bSup
bool CDVDDemuxFFmpeg::m_bSup protected
Referenced by CDVDDemuxFFmpeg(), ConvertTimestamp(), Open(), and SeekTime().
m_checkTransportStream
bool CDVDDemuxFFmpeg::m_checkTransportStream protected
Referenced by CDVDDemuxFFmpeg(), ConvertTimestamp(), IsTransportStreamReady(), Open(), and SeekTime().
m_critSection
CCriticalSection CDVDDemuxFFmpeg::m_critSection protected
Referenced by ReadInternal(), SeekByte(), and SeekTime().
m_currentPts
double CDVDDemuxFFmpeg::m_currentPts protected
Referenced by CDVDDemuxFFmpeg(), Flush(), GetChapter(), Open(), ReadInternal(), SeekByte(), and SeekTime().
m_displayTime
int CDVDDemuxFFmpeg::m_displayTime = 0 protected
Referenced by Flush(), Open(), and ReadInternal().
m_dtsAtDisplayTime
double CDVDDemuxFFmpeg::m_dtsAtDisplayTime protected
Referenced by CDVDDemuxFFmpeg(), Flush(), Open(), and ReadInternal().
m_initialProgramNumber
unsigned int CDVDDemuxFFmpeg::m_initialProgramNumber protected
Referenced by IsProgramChange(), and Open().
m_ioContext
AVIOContext* CDVDDemuxFFmpeg::m_ioContext protected
Referenced by CDVDDemuxFFmpeg(), Dispose(), and Open().
m_newProgram
unsigned int CDVDDemuxFFmpeg::m_newProgram protected
Referenced by IsProgramChange(), Open(), and SetProgram().
m_parsers
std::map<int, std::unique_ptr<CDemuxParserFFmpeg> > CDVDDemuxFFmpeg::m_parsers protected
Referenced by DisposeStreams(), and ParsePacket().
m_pFormatContext
AVFormatContext* CDVDDemuxFFmpeg::m_pFormatContext
Referenced by AddStream(), CDVDDemuxFFmpeg(), ConvertTimestamp(), CreateStreams(), Dispose(), Flush(), GetChapter(), GetChapterCount(), GetChapterName(), GetChapterPos(), GetPrograms(), GetStreamLength(), HLSSelectProgram(), IsProgramChange(), IsTransportStreamReady(), Open(), ParsePacket(), ReadInternal(), ResetVideoStreams(), SeekByte(), SeekChapter(), SeekTime(), SetSpeed(), TransportStreamAudioState(), and TransportStreamVideoState().
m_pInput
std::shared_ptr<CDVDInputStream> CDVDDemuxFFmpeg::m_pInput
Referenced by Aborted(), AddStream(), ConvertTimestamp(), Dispose(), GetChapter(), GetChapterCount(), GetChapterName(), GetChapterPos(), GetFFMpegOptionsFromInput(), GetFileName(), GetL16Parameters(), Open(), ReadInternal(), Reset(), SeekChapter(), and SeekTime().
[struct]
struct { ... } CDVDDemuxFFmpeg::m_pkt
Referenced by CDVDDemuxFFmpeg(), Dispose(), Flush(), ReadInternal(), SeekByte(), SeekTime(), TransportStreamAudioState(), and TransportStreamVideoState().
m_program
unsigned int CDVDDemuxFFmpeg::m_program protected
Referenced by CDVDDemuxFFmpeg(), CreateStreams(), GetPrograms(), IsProgramChange(), IsTransportStreamReady(), Open(), ReadInternal(), TransportStreamAudioState(), and TransportStreamVideoState().
m_reopen
bool CDVDDemuxFFmpeg::m_reopen = false protected
Referenced by Open().
m_seekStream
int CDVDDemuxFFmpeg::m_seekStream protected
Referenced by Open(), SeekTime(), TransportStreamAudioState(), and TransportStreamVideoState().
m_seekToKeyFrame
bool CDVDDemuxFFmpeg::m_seekToKeyFrame = false protected
Referenced by Flush(), Open(), ReadInternal(), and SeekTime().
m_speed
int CDVDDemuxFFmpeg::m_speed protected
Referenced by CDVDDemuxFFmpeg(), Dispose(), Open(), and SetSpeed().
m_startTime
double CDVDDemuxFFmpeg::m_startTime = 0 protected
Referenced by ConvertTimestamp(), Open(), SeekTime(), TransportStreamAudioState(), and TransportStreamVideoState().
m_streaminfo
bool CDVDDemuxFFmpeg::m_streaminfo protected
Referenced by AddStream(), CDVDDemuxFFmpeg(), and Open().
m_streams
std::map<int, CDemuxStream*> CDVDDemuxFFmpeg::m_streams protected
Referenced by AddStream(), AddStream(), DisposeStreams(), GetNrOfStreams(), GetStream(), and GetStreams().
m_streamsInProgram
unsigned int CDVDDemuxFFmpeg::m_streamsInProgram protected
Referenced by CreateStreams(), and IsProgramChange().
m_timeout
XbmcThreads::EndTime CDVDDemuxFFmpeg::m_timeout protected
Referenced by Abort(), Aborted(), Open(), and ReadInternal().
pkt
AVPacket CDVDDemuxFFmpeg::pkt
Referenced by ParsePacket(), and SeekTime().
result
int CDVDDemuxFFmpeg::result
Referenced by Open().
The documentation for this class was generated from the following files:
DVDDemuxFFmpeg.h
DVDDemuxFFmpeg.cpp