Kodi Documentation: CONTEXTMENU Namespace Reference
CONTEXTMENU Namespace Reference
Namespaces
namespace anonymous_namespace{ContextMenus.cpp}
Classes
struct CAddonInfo
struct CAddonSettings
struct CAddRemoveFavourite
struct CAlbumInfo
struct CArtistInfo
struct CCheckForUpdates
class CChooseThumbnailForFavourite
struct CDisableAddon
struct CEjectDisk
struct CEjectDrive
struct CEnableAddon
struct CEpisodeInfo
class CFavouriteContextMenuAction
class CFavouritesTargetBrowse
class CFavouritesTargetContextMenu
class CFavouritesTargetInfo
class CFavouritesTargetPlay
class CFavouritesTargetResume
class CMoveDownFavourite
class CMoveUpFavourite
struct CMovieInfo
struct CMovieSetInfo
struct CMusicBrowse
struct CMusicInfo
struct CMusicPlay
struct CMusicPlayNext
struct CMusicPlayUsing
struct CMusicQueue
struct CMusicVideoInfo
class CRemoveFavourite
class CRenameFavourite
struct CSeasonInfo
struct CSongInfo
struct CTVShowInfo
struct CVideoBrowse
struct CVideoChooseVersion
class CVideoInfo
struct CVideoMarkUnWatched
struct CVideoMarkWatched
struct CVideoPlay
struct CVideoPlayAndQueue
struct CVideoPlayNext
struct CVideoPlayUsing
struct CVideoPlayVersionUsing
struct CVideoQueue
struct CVideoRemoveResumePoint
struct CVideoResume
Functions
bool HasAnyMenuItemsFor (const std::shared_ptr< CFileItem > &fileItem, const CContextMenuItem &root)
Checks whether any context menu items are available for a file item.
bool ShowFor (const std::shared_ptr< CFileItem > &fileItem, const CContextMenuItem &root)
Starts the context menu loop for a file item.
bool LoopFrom (const IContextMenuItem &menu, const std::shared_ptr< CFileItem > &fileItem)
Shortcut for continuing the context menu loop from an existing menu item.
Function Documentation
HasAnyMenuItemsFor()
bool CONTEXTMENU::HasAnyMenuItemsFor (const std::shared_ptr< CFileItem > & fileItem, const CContextMenuItem & root) private
Checks whether any context menu items are available for a file item.
Parameters
fileItem the file item
root the root context menu item
Returns
true if any items are present, false otherwise
References CServiceBroker::GetContextMenuManager(), CContextMenuManager::HasAddonItems(), CContextMenuManager::HasItems(), and root.
Referenced by CONTEXTMENU::CFavouritesTargetContextMenu::IsVisible().
LoopFrom()
bool CONTEXTMENU::LoopFrom (const IContextMenuItem & menu, const std::shared_ptr< CFileItem > & fileItem) private
Shortcut for continuing the context menu loop from an existing menu item.
Parameters
menu the menu item
fileItem the file item
Returns
true on success, false otherwise
References IContextMenuItem::Execute(), IContextMenuItem::IsGroup(), and ShowFor().
Referenced by PVR::CGUIDialogPVRItemsViewBase::ContextMenu(), CGUIDialogVideoInfo::ManageVideoItem(), and CGUIMediaWindow::OnPopupMenu().
ShowFor()
bool CONTEXTMENU::ShowFor (const std::shared_ptr< CFileItem > & fileItem, const CContextMenuItem & root) private
Starts the context menu loop for a file item.
Parameters
fileItem the file item
root the root context menu item
Returns
true on success, false otherwise
References CContextButtons::Add(), KODI::UTILS::StringUtils::Format(), CContextMenuManager::GetAddonItems(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetContextMenuManager(), CContextMenuManager::GetItems(), root, CGUIDialogContextMenu::Show(), ShowFor(), and TMSG_EXECUTE_BUILT_IN.
Referenced by CONTEXTMENU::CFavouritesTargetContextMenu::Execute(), LoopFrom(), anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnChooseSelected(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoSelectActionProcessor::OnChooseSelected(), anonymous_namespace{GUIWindowVideoBase.cpp}::CVideoSelectActionProcessor::OnChooseSelected(), CDirectoryProvider::OnContextMenu(), and ShowFor().