Kodi Documentation: anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction Class Reference
anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction Class Reference
Public Member Functions
AsyncSearchAction ()=delete
AsyncSearchAction (CFileItemList *items, CPVREpgSearchFilter *filter)
bool Execute ()
Private Member Functions
void Run () override
Private Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Private Attributes
CFileItemList * m_items
CPVREpgSearchFilter * m_filter
Constructor & Destructor Documentation
AsyncSearchAction() [1/2]
anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction::AsyncSearchAction () delete
AsyncSearchAction() [2/2]
anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction::AsyncSearchAction (CFileItemList * items, CPVREpgSearchFilter * filter) inline
Member Function Documentation
Execute()
bool anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction::Execute ()
References CGUIDialogBusy::Wait().
Run()
void anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction::Run () override private virtual
Implements IRunnable.
References PVR::CPVREpgSearch::Execute(), PVR::CPVREpgSearch::GetResults(), and tags.
Member Data Documentation
m_filter
CPVREpgSearchFilter* anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction::m_filter private
m_items
CFileItemList* anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction::m_items private
The documentation for this class was generated from the following file:
GUIWindowPVRSearch.cpp