Kodi Documentation: PVR::CGUIEPGGridContainerModel Class Reference
PVR::CGUIEPGGridContainerModel Class Reference
#include <GUIEPGGridContainerModel.h>
Classes
struct EpgTags
struct GridCoordinates
struct GridCoordinatesHash
Public Member Functions
CGUIEPGGridContainerModel ()=default
virtual ~CGUIEPGGridContainerModel ()=default
void Initialize (const std::unique_ptr< CFileItemList > &items, const CDateTime &gridStart, const CDateTime &gridEnd, int iFirstChannel, int iChannelsPerPage, int iFirstBlock, int iBlocksPerPage, int iRulerUnit, float fBlockSize)
void SetInvalid ()
void FindChannelAndBlockIndex (int channelUid, unsigned int broadcastUid, int eventOffset, int &newChannelIndex, int &newBlockIndex) const
void FreeChannelMemory (int keepStart, int keepEnd)
bool FreeProgrammeMemory (int firstChannel, int lastChannel, int firstBlock, int lastBlock)
void FreeRulerMemory (int keepStart, int keepEnd)
std::shared_ptr< CFileItem > GetChannelItem (int iIndex) const
bool HasChannelItems () const
int ChannelItemsSize () const
int GetLastChannel () const
std::shared_ptr< CFileItem > GetRulerItem (int iIndex) const
int RulerItemsSize () const
int GridItemsSize () const
bool IsSameGridItem (int iChannel, int iBlock1, int iBlock2) const
std::shared_ptr< CFileItem > GetGridItem (int iChannel, int iBlock) const
int GetGridItemStartBlock (int iChannel, int iBlock) const
int GetGridItemEndBlock (int iChannel, int iBlock) const
CDateTime GetGridItemEndTime (int iChannel, int iBlock) const
float GetGridItemWidth (int iChannel, int iBlock) const
float GetGridItemOriginWidth (int iChannel, int iBlock) const
void DecreaseGridItemWidth (int iChannel, int iBlock, float fSize)
bool IsZeroGridDuration () const
const CDateTime & GetGridStart () const
const CDateTime & GetGridEnd () const
unsigned int GetGridStartPadding () const
unsigned int GetPageNowOffset () const
int GetNowBlock () const
int GetLastBlock () const
CDateTime GetStartTimeForBlock (int block) const
int GetBlock (const CDateTime &datetime) const
int GetFirstEventBlock (const std::shared_ptr< const CPVREpgInfoTag > &event) const
int GetLastEventBlock (const std::shared_ptr< const CPVREpgInfoTag > &event) const
bool IsEventMemberOfBlock (const std::shared_ptr< const CPVREpgInfoTag > &event, int iBlock) const
std::unique_ptr< CFileItemList > GetCurrentTimeLineItems (int firstChannel, int numChannels) const
Static Public Attributes
static constexpr int MINSPERBLOCK = 5
static const int INVALID_INDEX = -1
Private Types
using EpgTagsMap = std::unordered_map< int, EpgTags >
Private Member Functions
GridItem * GetGridItemPtr (int iChannel, int iBlock) const
std::shared_ptr< CFileItem > CreateGapItem (int iChannel) const
std::shared_ptr< CFileItem > GetItem (int iChannel, int iBlock) const
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetEPGTimeline (int iChannel, const CDateTime &minEventEnd, const CDateTime &maxEventStart) const
std::shared_ptr< CFileItem > CreateEpgTags (int iChannel, int iBlock) const
std::shared_ptr< CFileItem > GetEpgTags (EpgTagsMap::iterator &itEpg, int iChannel, int iBlock) const
std::shared_ptr< CFileItem > GetEpgTagsBefore (EpgTags &epgTags, int iChannel, int iBlock) const
std::shared_ptr< CFileItem > GetEpgTagsAfter (EpgTags &epgTags, int iChannel, int iBlock) const
Private Attributes
EpgTagsMap m_epgItems
CDateTime m_gridStart
CDateTime m_gridEnd
std::vector< std::shared_ptr< CFileItem > > m_channelItems
std::vector< std::shared_ptr< CFileItem > > m_rulerItems
std::unordered_map< GridCoordinates, GridItem, GridCoordinatesHash > m_gridIndex
int m_blocks = 0
float m_fBlockSize = 0.0f
int m_firstActiveChannel = 0
int m_lastActiveChannel = 0
int m_firstActiveBlock = 0
int m_lastActiveBlock = 0
Member Typedef Documentation
EpgTagsMap
using PVR::CGUIEPGGridContainerModel::EpgTagsMap = std::unordered_map<int, EpgTags> private
Constructor & Destructor Documentation
CGUIEPGGridContainerModel()
PVR::CGUIEPGGridContainerModel::CGUIEPGGridContainerModel () default
~CGUIEPGGridContainerModel()
virtual PVR::CGUIEPGGridContainerModel::~CGUIEPGGridContainerModel () virtual default
Member Function Documentation
ChannelItemsSize()
int PVR::CGUIEPGGridContainerModel::ChannelItemsSize () const inline
References m_channelItems.
Referenced by FreeChannelMemory(), and GetCurrentTimeLineItems().
CreateEpgTags()
std::shared_ptr< CFileItem > CGUIEPGGridContainerModel::CreateEpgTags (int iChannel, int iBlock) const private
References PVR::CGUIEPGGridContainerModel::EpgTags::firstBlock, GetEPGTimeline(), GetFirstEventBlock(), GetLastEventBlock(), GetStartTimeForBlock(), IsEventMemberOfBlock(), PVR::CGUIEPGGridContainerModel::EpgTags::lastBlock, m_epgItems, m_firstActiveBlock, m_lastActiveBlock, tags, and PVR::CGUIEPGGridContainerModel::EpgTags::tags.
Referenced by GetItem().
CreateGapItem()
std::shared_ptr< CFileItem > CGUIEPGGridContainerModel::CreateGapItem (int iChannel) const private
References m_channelItems, m_gridEnd, and m_gridStart.
Referenced by GetCurrentTimeLineItems().
DecreaseGridItemWidth()
void CGUIEPGGridContainerModel::DecreaseGridItemWidth (int iChannel, int iBlock, float fSize)
References m_gridIndex.
FindChannelAndBlockIndex()
void CGUIEPGGridContainerModel::FindChannelAndBlockIndex (int channelUid, unsigned int broadcastUid, int eventOffset, int & newChannelIndex, int & newBlockIndex) const
References GetFirstEventBlock(), INVALID_INDEX, and m_channelItems.
FreeChannelMemory()
void CGUIEPGGridContainerModel::FreeChannelMemory (int keepStart, int keepEnd)
References ChannelItemsSize(), and m_channelItems.
FreeProgrammeMemory()
bool CGUIEPGGridContainerModel::FreeProgrammeMemory (int firstChannel, int lastChannel, int firstBlock, int lastBlock)
References PVR::CGUIEPGGridContainerModel::EpgTags::firstBlock, GetEPGTimeline(), GetFirstEventBlock(), GetLastEventBlock(), GetStartTimeForBlock(), PVR::CGUIEPGGridContainerModel::EpgTags::lastBlock, m_epgItems, m_firstActiveBlock, m_firstActiveChannel, m_gridIndex, m_lastActiveBlock, m_lastActiveChannel, tags, and PVR::CGUIEPGGridContainerModel::EpgTags::tags.
FreeRulerMemory()
void CGUIEPGGridContainerModel::FreeRulerMemory (int keepStart, int keepEnd)
References m_rulerItems, and RulerItemsSize().
GetBlock()
int CGUIEPGGridContainerModel::GetBlock (const CDateTime & datetime) const
References m_gridEnd, m_gridStart, and MINSPERBLOCK.
Referenced by GetLastEventBlock(), GetNowBlock(), and Initialize().
GetChannelItem()
std::shared_ptr< CFileItem > PVR::CGUIEPGGridContainerModel::GetChannelItem (int iIndex) const inline
References m_channelItems.
GetCurrentTimeLineItems()
std::unique_ptr< CFileItemList > CGUIEPGGridContainerModel::GetCurrentTimeLineItems (int firstChannel, int numChannels) const
References ChannelItemsSize(), CreateGapItem(), and m_epgItems.
GetEpgTags()
std::shared_ptr< CFileItem > CGUIEPGGridContainerModel::GetEpgTags (EpgTagsMap::iterator & itEpg, int iChannel, int iBlock) const private
References PVR::CGUIEPGGridContainerModel::EpgTags::firstBlock, GetEpgTagsAfter(), GetEpgTagsBefore(), PVR::CGUIEPGGridContainerModel::EpgTags::lastBlock, and PVR::CGUIEPGGridContainerModel::EpgTags::tags.
Referenced by GetItem().
GetEpgTagsAfter()
std::shared_ptr< CFileItem > CGUIEPGGridContainerModel::GetEpgTagsAfter (EpgTags & epgTags, int iChannel, int iBlock) const private
References PVR::CGUIEPGGridContainerModel::EpgTags::firstBlock, GetEPGTimeline(), GetFirstEventBlock(), GetLastBlock(), GetLastEventBlock(), GetStartTimeForBlock(), IsEventMemberOfBlock(), PVR::CGUIEPGGridContainerModel::EpgTags::lastBlock, t, tags, and PVR::CGUIEPGGridContainerModel::EpgTags::tags.
Referenced by GetEpgTags().
GetEpgTagsBefore()
std::shared_ptr< CFileItem > CGUIEPGGridContainerModel::GetEpgTagsBefore (EpgTags & epgTags, int iChannel, int iBlock) const private
References PVR::CGUIEPGGridContainerModel::EpgTags::firstBlock, GetEPGTimeline(), GetFirstEventBlock(), GetLastEventBlock(), GetStartTimeForBlock(), IsEventMemberOfBlock(), PVR::CGUIEPGGridContainerModel::EpgTags::lastBlock, t, tags, and PVR::CGUIEPGGridContainerModel::EpgTags::tags.
Referenced by GetEpgTags().
GetEPGTimeline()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CGUIEPGGridContainerModel::GetEPGTimeline (int iChannel, const CDateTime & minEventEnd, const CDateTime & maxEventStart) const private
References m_channelItems, m_gridEnd, m_gridStart, max, min, and MINSPERBLOCK.
Referenced by CreateEpgTags(), FreeProgrammeMemory(), GetEpgTagsAfter(), and GetEpgTagsBefore().
GetFirstEventBlock()
int CGUIEPGGridContainerModel::GetFirstEventBlock (const std::shared_ptr< const CPVREpgInfoTag > & event) const
References m_gridStart, and MINSPERBLOCK.
Referenced by CreateEpgTags(), FindChannelAndBlockIndex(), FreeProgrammeMemory(), GetEpgTagsAfter(), GetEpgTagsBefore(), GetGridItemPtr(), and IsEventMemberOfBlock().
GetGridEnd()
const CDateTime & PVR::CGUIEPGGridContainerModel::GetGridEnd () const inline
References m_gridEnd.
GetGridItem()
std::shared_ptr< CFileItem > CGUIEPGGridContainerModel::GetGridItem (int iChannel, int iBlock) const
References GetGridItemPtr(), and PVR::GridItem::item.
GetGridItemEndBlock()
int CGUIEPGGridContainerModel::GetGridItemEndBlock (int iChannel, int iBlock) const
References PVR::GridItem::endBlock, and GetGridItemPtr().
GetGridItemEndTime()
CDateTime CGUIEPGGridContainerModel::GetGridItemEndTime (int iChannel, int iBlock) const
References GetGridItemPtr(), and PVR::GridItem::item.
GetGridItemOriginWidth()
float CGUIEPGGridContainerModel::GetGridItemOriginWidth (int iChannel, int iBlock) const
References GetGridItemPtr(), and PVR::GridItem::originWidth.
GetGridItemPtr()
GridItem * CGUIEPGGridContainerModel::GetGridItemPtr (int iChannel, int iBlock) const private
Todo:
it seems that this should be done somewhere else. CFileItem ctor maybe.
References GetFirstEventBlock(), GetItem(), GetLastEventBlock(), GetStartTimeForBlock(), LOGERROR, m_fBlockSize, m_gridEnd, m_gridIndex, and m_gridStart.
Referenced by GetGridItem(), GetGridItemEndBlock(), GetGridItemEndTime(), GetGridItemOriginWidth(), GetGridItemStartBlock(), GetGridItemWidth(), and IsSameGridItem().
GetGridItemStartBlock()
int CGUIEPGGridContainerModel::GetGridItemStartBlock (int iChannel, int iBlock) const
References GetGridItemPtr(), and PVR::GridItem::startBlock.
GetGridItemWidth()
float CGUIEPGGridContainerModel::GetGridItemWidth (int iChannel, int iBlock) const
References GetGridItemPtr(), and PVR::GridItem::width.
GetGridStart()
const CDateTime & PVR::CGUIEPGGridContainerModel::GetGridStart () const inline
References m_gridStart.
GetGridStartPadding()
unsigned int CGUIEPGGridContainerModel::GetGridStartPadding () const
References PVR::CPVRManager::EpgContainer(), PVR::CPVREpgContainer::GetPastDaysToDisplay(), CServiceBroker::GetPVRManager(), and GRID_START_PADDING.
Referenced by GetPageNowOffset(), and Initialize().
GetItem()
std::shared_ptr< CFileItem > CGUIEPGGridContainerModel::GetItem (int iChannel, int iBlock) const private
References CreateEpgTags(), GetEpgTags(), LOGERROR, and m_epgItems.
Referenced by GetGridItemPtr().
GetLastBlock()
int PVR::CGUIEPGGridContainerModel::GetLastBlock () const inline
References m_blocks.
Referenced by GetEpgTagsAfter(), and GetStartTimeForBlock().
GetLastChannel()
int PVR::CGUIEPGGridContainerModel::GetLastChannel () const inline
References m_channelItems.
GetLastEventBlock()
int CGUIEPGGridContainerModel::GetLastEventBlock (const std::shared_ptr< const CPVREpgInfoTag > & event) const
References GetBlock().
Referenced by CreateEpgTags(), FreeProgrammeMemory(), GetEpgTagsAfter(), GetEpgTagsBefore(), GetGridItemPtr(), and IsEventMemberOfBlock().
GetNowBlock()
int CGUIEPGGridContainerModel::GetNowBlock () const
References GetBlock(), GetPageNowOffset(), and CDateTime::GetUTCDateTime().
GetPageNowOffset()
unsigned int CGUIEPGGridContainerModel::GetPageNowOffset () const
References GetGridStartPadding(), and MINSPERBLOCK.
Referenced by GetNowBlock().
GetRulerItem()
std::shared_ptr< CFileItem > PVR::CGUIEPGGridContainerModel::GetRulerItem (int iIndex) const inline
References m_rulerItems.
GetStartTimeForBlock()
CDateTime CGUIEPGGridContainerModel::GetStartTimeForBlock (int block) const
References GetLastBlock(), GridItemsSize(), m_gridStart, and MINSPERBLOCK.
Referenced by CreateEpgTags(), FreeProgrammeMemory(), GetEpgTagsAfter(), GetEpgTagsBefore(), and GetGridItemPtr().
GridItemsSize()
int PVR::CGUIEPGGridContainerModel::GridItemsSize () const inline
References m_blocks.
Referenced by GetStartTimeForBlock().
HasChannelItems()
bool PVR::CGUIEPGGridContainerModel::HasChannelItems () const inline
References m_channelItems.
Initialize()
void CGUIEPGGridContainerModel::Initialize (const std::unique_ptr< CFileItemList > & items, const CDateTime & gridStart, const CDateTime & gridEnd, int iFirstChannel, int iChannelsPerPage, int iFirstBlock, int iBlocksPerPage, int iRulerUnit, float fBlockSize)
References CDateTime::GetAsLocalizedDate(), CDateTime::GetAsLocalizedTime(), GetBlock(), CDateTime::GetDay(), GetGridStartPadding(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetUTCDateTime(), CDateTime::GetYear(), LOGERROR, m_blocks, m_channelItems, m_fBlockSize, m_firstActiveBlock, m_firstActiveChannel, m_gridEnd, m_gridStart, m_lastActiveBlock, m_lastActiveChannel, m_rulerItems, MINSPERBLOCK, and CDateTime::SetFromUTCDateTime().
IsEventMemberOfBlock()
bool CGUIEPGGridContainerModel::IsEventMemberOfBlock (const std::shared_ptr< const CPVREpgInfoTag > & event, int iBlock) const
References GetFirstEventBlock(), and GetLastEventBlock().
Referenced by CreateEpgTags(), GetEpgTagsAfter(), and GetEpgTagsBefore().
IsSameGridItem()
bool CGUIEPGGridContainerModel::IsSameGridItem (int iChannel, int iBlock1, int iBlock2) const
References GetGridItemPtr().
IsZeroGridDuration()
bool PVR::CGUIEPGGridContainerModel::IsZeroGridDuration () const inline
References m_gridEnd, and m_gridStart.
RulerItemsSize()
int PVR::CGUIEPGGridContainerModel::RulerItemsSize () const inline
References m_rulerItems.
Referenced by FreeRulerMemory().
SetInvalid()
void CGUIEPGGridContainerModel::SetInvalid ()
References m_channelItems, m_gridIndex, and m_rulerItems.
Member Data Documentation
INVALID_INDEX
const int PVR::CGUIEPGGridContainerModel::INVALID_INDEX = -1 static
Referenced by FindChannelAndBlockIndex(), and PVR::CGUIEPGGridContainer::UpdateItems().
m_blocks
int PVR::CGUIEPGGridContainerModel::m_blocks = 0 private
Referenced by GetLastBlock(), GridItemsSize(), and Initialize().
m_channelItems
std::vector<std::shared_ptr<CFileItem> > PVR::CGUIEPGGridContainerModel::m_channelItems private
Referenced by ChannelItemsSize(), CreateGapItem(), FindChannelAndBlockIndex(), FreeChannelMemory(), GetChannelItem(), GetEPGTimeline(), GetLastChannel(), HasChannelItems(), Initialize(), and SetInvalid().
m_epgItems
EpgTagsMap PVR::CGUIEPGGridContainerModel::m_epgItems mutable private
Referenced by CreateEpgTags(), FreeProgrammeMemory(), GetCurrentTimeLineItems(), and GetItem().
m_fBlockSize
float PVR::CGUIEPGGridContainerModel::m_fBlockSize = 0.0f private
Referenced by GetGridItemPtr(), and Initialize().
m_firstActiveBlock
int PVR::CGUIEPGGridContainerModel::m_firstActiveBlock = 0 private
Referenced by CreateEpgTags(), FreeProgrammeMemory(), and Initialize().
m_firstActiveChannel
int PVR::CGUIEPGGridContainerModel::m_firstActiveChannel = 0 private
Referenced by FreeProgrammeMemory(), and Initialize().
m_gridEnd
CDateTime PVR::CGUIEPGGridContainerModel::m_gridEnd private
Referenced by CreateGapItem(), GetBlock(), GetEPGTimeline(), GetGridEnd(), GetGridItemPtr(), Initialize(), and IsZeroGridDuration().
m_gridIndex
std::unordered_map<GridCoordinates, GridItem, GridCoordinatesHash> PVR::CGUIEPGGridContainerModel::m_gridIndex mutable private
Referenced by DecreaseGridItemWidth(), FreeProgrammeMemory(), GetGridItemPtr(), and SetInvalid().
m_gridStart
CDateTime PVR::CGUIEPGGridContainerModel::m_gridStart private
Referenced by CreateGapItem(), GetBlock(), GetEPGTimeline(), GetFirstEventBlock(), GetGridItemPtr(), GetGridStart(), GetStartTimeForBlock(), Initialize(), and IsZeroGridDuration().
m_lastActiveBlock
int PVR::CGUIEPGGridContainerModel::m_lastActiveBlock = 0 private
Referenced by CreateEpgTags(), FreeProgrammeMemory(), and Initialize().
m_lastActiveChannel
int PVR::CGUIEPGGridContainerModel::m_lastActiveChannel = 0 private
Referenced by FreeProgrammeMemory(), and Initialize().
m_rulerItems
std::vector<std::shared_ptr<CFileItem> > PVR::CGUIEPGGridContainerModel::m_rulerItems private
Referenced by FreeRulerMemory(), GetRulerItem(), Initialize(), RulerItemsSize(), and SetInvalid().
MINSPERBLOCK
constexpr int PVR::CGUIEPGGridContainerModel::MINSPERBLOCK = 5 static constexpr
Referenced by GetBlock(), PVR::CGUIEPGGridContainer::GetCurrentTimePositionOnPage(), GetEPGTimeline(), GetFirstEventBlock(), GetPageNowOffset(), GetStartTimeForBlock(), Initialize(), and PVR::CGUIEPGGridContainer::OnAction().
The documentation for this class was generated from the following files:
GUIEPGGridContainerModel.h
GUIEPGGridContainerModel.cpp