Kodi Documentation: VAAPI::CVaapi1Texture Class Reference
VAAPI::CVaapi1Texture Class Reference
#include <VaapiEGL.h>
Classes
struct GLSurface
Public Member Functions
CVaapi1Texture ()=default
bool Map (CVaapiRenderPicture *pic) override
void Unmap () override
void Init (InteropInfo &interop) override
GLuint GetTextureY () override
GLuint GetTextureVU () override
CSizeInt GetTextureSize () override
Public Member Functions inherited from VAAPI::CVaapiTexture
CVaapiTexture ()=default
virtual ~CVaapiTexture ()=default
Static Public Member Functions
static void TestInterop (VADisplay vaDpy, EGLDisplay eglDisplay, bool &general, bool &deepColor)
Public Attributes
GLuint m_texture = 0
GLuint m_textureY = 0
GLuint m_textureVU = 0
int m_texWidth = 0
int m_texHeight = 0
Static Protected Member Functions
static bool TestInteropDeepColor (VADisplay vaDpy, EGLDisplay eglDisplay)
Protected Attributes
InteropInfo m_interop
CVaapiRenderPicture * m_vaapiPic = nullptr
struct VAAPI::CVaapi1Texture::GLSurface m_glSurface
Constructor & Destructor Documentation
CVaapi1Texture()
VAAPI::CVaapi1Texture::CVaapi1Texture () default
Member Function Documentation
GetTextureSize()
CSizeInt CVaapi1Texture::GetTextureSize () override virtual
Implements VAAPI::CVaapiTexture.
References m_texHeight, and m_texWidth.
GetTextureVU()
GLuint CVaapi1Texture::GetTextureVU () override virtual
Implements VAAPI::CVaapiTexture.
References m_textureVU.
GetTextureY()
GLuint CVaapi1Texture::GetTextureY () override virtual
Implements VAAPI::CVaapiTexture.
References m_textureY.
Init()
void CVaapi1Texture::Init (InteropInfo & interop) override virtual
Implements VAAPI::CVaapiTexture.
References m_interop.
Map()
bool CVaapi1Texture::Map (CVaapiRenderPicture * pic) override virtual
Implements VAAPI::CVaapiTexture.
References CVideoBuffer::Acquire(), VAAPI::InteropInfo::eglCreateImageKHR, VAAPI::InteropInfo::eglDisplay, VAAPI::CVaapi1Texture::GLSurface::eglImage, VAAPI::CVaapi1Texture::GLSurface::eglImageVU, VAAPI::CVaapi1Texture::GLSurface::eglImageY, err(), VAAPI::InteropInfo::glEGLImageTargetTexture2DOES, CLog::Log(), LOGERROR, m_glSurface, m_interop, m_texHeight, m_texture, m_textureVU, m_textureY, m_texWidth, m_vaapiPic, VAAPI::CVaapiRenderPicture::procPic, VAAPI::InteropInfo::textureTarget, VAAPI::CVaapiRenderPicture::vadsp, VAAPI::CVaapi1Texture::GLSurface::vaImage, VAAPI::CVaapi1Texture::GLSurface::vBufInfo, and VAAPI::CVaapiProcessedPicture::videoSurface.
TestInterop()
void CVaapi1Texture::TestInterop (VADisplay vaDpy, EGLDisplay eglDisplay, bool & general, bool & deepColor) static
References TestInteropDeepColor().
Referenced by CRendererVAAPIGL::Register(), and CRendererVAAPIGLES::Register().
TestInteropDeepColor()
bool CVaapi1Texture::TestInteropDeepColor (VADisplay vaDpy, EGLDisplay eglDisplay) static protected
Referenced by TestInterop().
Unmap()
void CVaapi1Texture::Unmap () override virtual
Implements VAAPI::CVaapiTexture.
References VAAPI::InteropInfo::eglDestroyImageKHR, VAAPI::InteropInfo::eglDisplay, VAAPI::CVaapi1Texture::GLSurface::eglImageVU, VAAPI::CVaapi1Texture::GLSurface::eglImageY, CLog::Log(), LOGERROR, m_glSurface, m_interop, m_textureVU, m_textureY, m_vaapiPic, CVideoBuffer::Release(), VAAPI::CVaapiRenderPicture::vadsp, and VAAPI::CVaapi1Texture::GLSurface::vaImage.
Member Data Documentation
m_glSurface
struct VAAPI::CVaapi1Texture::GLSurface VAAPI::CVaapi1Texture::m_glSurface protected
Referenced by Map(), and Unmap().
m_interop
InteropInfo VAAPI::CVaapi1Texture::m_interop protected
Referenced by Init(), Map(), and Unmap().
m_texHeight
int VAAPI::CVaapi1Texture::m_texHeight = 0
Referenced by GetTextureSize(), and Map().
m_texture
GLuint VAAPI::CVaapi1Texture::m_texture = 0
Referenced by Map().
m_textureVU
GLuint VAAPI::CVaapi1Texture::m_textureVU = 0
Referenced by GetTextureVU(), Map(), and Unmap().
m_textureY
GLuint VAAPI::CVaapi1Texture::m_textureY = 0
Referenced by GetTextureY(), Map(), and Unmap().
m_texWidth
int VAAPI::CVaapi1Texture::m_texWidth = 0
Referenced by GetTextureSize(), and Map().
m_vaapiPic
CVaapiRenderPicture* VAAPI::CVaapi1Texture::m_vaapiPic = nullptr protected
Referenced by Map(), and Unmap().
The documentation for this class was generated from the following files:
VaapiEGL.h
VaapiEGL.cpp