Kodi Documentation: OVERLAY::COverlayQuadsDX Class Reference
OVERLAY::COverlayQuadsDX Class Reference
#include <OverlayRendererDX.h>
Public Member Functions
COverlayQuadsDX (ASS_Image *images, float width, float height)
virtual ~COverlayQuadsDX ()
void Render (SRenderState &state)
Public Member Functions inherited from OVERLAY::COverlay
COverlay ()
virtual ~COverlay ()
Public Attributes
unsigned int m_count
CD3DTexture m_texture
CD3DBuffer m_vertex
Public Attributes inherited from OVERLAY::COverlay
enum OVERLAY::COverlay::EType m_type
enum OVERLAY::COverlay::EAlign m_align
enum OVERLAY::COverlay::EPosition m_pos
float m_x {0}
float m_y {0}
float m_width {1.0f}
float m_height {1.0f}
float m_source_width {0}
float m_source_height {0}
Additional Inherited Members
Public Types inherited from OVERLAY::COverlay
enum EType { TYPE_NONE , TYPE_TEXTURE }
enum EAlign { ALIGN_SCREEN , ALIGN_SCREEN_AR , ALIGN_VIDEO , ALIGN_SUBTITLE }
enum EPosition { POSITION_ABSOLUTE , POSITION_ABSOLUTE_SCREEN , POSITION_RELATIVE }
Static Public Member Functions inherited from OVERLAY::COverlay
static std::shared_ptr< COverlay > Create (const CDVDOverlayImage &o, CRect &rSource)
static std::shared_ptr< COverlay > Create (const CDVDOverlaySpu &o)
static std::shared_ptr< COverlay > Create (ASS_Image *images, float width, float height)
Protected Member Functions inherited from OVERLAY::COverlay
bool IsSquareResolution (float resRatio)
Given the resolution ratio determines if it is a 4/3 resolution.
Constructor & Destructor Documentation
COverlayQuadsDX()
COverlayQuadsDX::COverlayQuadsDX (ASS_Image * images, float width, float height)
References OVERLAY::SQuad::a, OVERLAY::COverlay::ALIGN_SCREEN, OVERLAY::SQuad::b, color, OVERLAY::convert_quad(), CD3DBuffer::Create(), OVERLAY::SQuad::g, OVERLAY::SQuad::h, LoadTexture(), CLog::Log(), LOGERROR, OVERLAY::COverlay::m_align, m_count, OVERLAY::COverlay::m_height, OVERLAY::COverlay::m_pos, m_texture, m_vertex, OVERLAY::COverlay::m_width, OVERLAY::COverlay::m_x, OVERLAY::COverlay::m_y, Vertex::pos, OVERLAY::COverlay::POSITION_RELATIVE, OVERLAY::SQuads::quad, OVERLAY::SQuad::r, CD3DTexture::Release(), OVERLAY::SQuads::size_x, OVERLAY::SQuads::size_y, Vertex::texCoord, Vertex::texCoord2, OVERLAY::SQuads::texture, OVERLAY::SQuad::u, OVERLAY::SQuad::v, OVERLAY::SQuad::w, OVERLAY::SQuad::x, CD3DHelper::XMStoreColor(), and OVERLAY::SQuad::y.
~COverlayQuadsDX()
COverlayQuadsDX::~COverlayQuadsDX () virtual
Member Function Documentation
Render()
void COverlayQuadsDX::Render (SRenderState & state) virtual
Implements OVERLAY::COverlay.
References CGUIShaderDX::Begin(), CGUIShaderDX::Draw(), DX::DeviceResources::Get(), CD3DBuffer::Get(), CD3DTexture::GetAddressOfSRV(), CServiceBroker::GetWinSystem(), CGUIShaderDX::GetWVP(), OVERLAY::SRenderState::height, CRectGen< T >::Height(), m_count, m_texture, m_vertex, RENDER_STEREO_MODE_SPLIT_HORIZONTAL, RENDER_STEREO_MODE_SPLIT_VERTICAL, CGUIShaderDX::RestoreBuffers(), CGUIShaderDX::SetShaderViews(), CGUIShaderDX::SetWorld(), CGUIShaderDX::SetWVP(), SHADER_METHOD_RENDER_FONT, OVERLAY::SRenderState::width, CRectGen< T >::Width(), OVERLAY::SRenderState::x, and OVERLAY::SRenderState::y.
Member Data Documentation
m_count
unsigned int OVERLAY::COverlayQuadsDX::m_count
Referenced by COverlayQuadsDX(), and Render().
m_texture
CD3DTexture OVERLAY::COverlayQuadsDX::m_texture
Referenced by COverlayQuadsDX(), and Render().
m_vertex
CD3DBuffer OVERLAY::COverlayQuadsDX::m_vertex
Referenced by COverlayQuadsDX(), and Render().
The documentation for this class was generated from the following files:
OverlayRendererDX.h
OverlayRendererDX.cpp