Kodi Documentation: PVR::CPVRRecordings Class Reference
PVR::CPVRRecordings Class Reference
#include <PVRRecordings.h>
Public Member Functions
CPVRRecordings ()
virtual ~CPVRRecordings ()
bool Update (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Update all recordings from the given PVR clients.
void Unload ()
unload all recordings.
bool UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Update data with recordings from the given clients, sync with local data.
void UpdateFromClient (const std::shared_ptr< CPVRRecording > &tag, const CPVRClient &client)
client has delivered a new/updated recording.
void UpdateInProgressSize ()
refresh the size of any in progress recordings from the clients.
int GetNumTVRecordings () const
bool HasDeletedTVRecordings () const
int GetNumRadioRecordings () const
bool HasDeletedRadioRecordings () const
bool MarkWatched (const std::shared_ptr< CPVRRecording > &recording, bool bWatched)
Set a recording's watched state.
bool ResetResumePoint (const std::shared_ptr< CPVRRecording > &recording)
Reset a recording's resume point, if any.
bool DeleteRecording (const std::shared_ptr< CPVRRecording > &recording)
Delete a recording in the backend, cleanup db enries.
std::vector< std::shared_ptr< CPVRRecording > > GetAll () const
Get a list of all recordings.
std::shared_ptr< CPVRRecording > GetByPath (const std::string &path) const
std::shared_ptr< CPVRRecording > GetById (int iClientId, const std::string &strRecordingId) const
std::shared_ptr< CPVRRecording > GetById (unsigned int iId) const
bool HasRecordingForProvider (bool isRadio, int clientId, int providerId) const
Check whether at least one recording is offered by the given provider.
unsigned int GetRecordingCountByProvider (bool isRadio, int clientId, int providerId) const
Get the total count of recordings offered by the given provider.
std::shared_ptr< CPVRRecording > GetRecordingForEpgTag (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
Get the recording for the given epg tag, if any.
int CleanupCachedImages ()
Erase stale texture db entries and image files.
Private Member Functions
CVideoDatabase & GetVideoDatabase ()
Get/Open the video database.
bool SetRecordingsPlayCount (const std::shared_ptr< CPVRRecording > &recording, int count)
Set a recording's play count.
bool IncrementRecordingsPlayCount (const std::shared_ptr< CPVRRecording > &recording)
Increment a recording's play count.
bool ChangeRecordingsPlayCount (const std::shared_ptr< CPVRRecording > &recording, int count)
change the play count of the given recording
Private Attributes
CCriticalSection m_critSection
bool m_bIsUpdating = false
std::map< CPVRRecordingUid, std::shared_ptr< CPVRRecording > > m_recordings
unsigned int m_iLastId = 0
std::unique_ptr< CVideoDatabase > m_database
bool m_bDeletedTVRecordings = false
bool m_bDeletedRadioRecordings = false
unsigned int m_iTVRecordings = 0
unsigned int m_iRadioRecordings = 0
Static Private Attributes
static const int INCREMENT_PLAY_COUNT = -1
special value for parameter count of method ChangeRecordingsPlayCount
Constructor & Destructor Documentation
CPVRRecordings()
CPVRRecordings::CPVRRecordings () default
~CPVRRecordings()
CPVRRecordings::~CPVRRecordings () virtual
References m_database.
Member Function Documentation
ChangeRecordingsPlayCount()
bool CPVRRecordings::ChangeRecordingsPlayCount (const std::shared_ptr< CPVRRecording > & recording, int count) private
change the play count of the given recording
Parameters
recording The recording
count The new play count or INCREMENT_PLAY_COUNT to denote that the current play count is to be incremented by one
Returns
true if the play count was changed successfully
References CVideoDatabase::ClearBookMarksOfFile(), CServiceBroker::GetPVRManager(), GetVideoDatabase(), INCREMENT_PLAY_COUNT, CDatabase::IsOpen(), m_critSection, PVR::CPVRManager::PublishEvent(), PVR::RecordingsInvalidated, and CBookmark::RESUME.
Referenced by IncrementRecordingsPlayCount(), and SetRecordingsPlayCount().
CleanupCachedImages()
int CPVRRecordings::CleanupCachedImages ()
Erase stale texture db entries and image files.
Returns
number of cleaned up images.
References PVR::CPVRCachedImages::Cleanup(), PVR::CPVRRecording::IMAGE_OWNER_PATTERN, m_critSection, and m_recordings.
DeleteRecording()
bool CPVRRecordings::DeleteRecording (const std::shared_ptr< CPVRRecording > & recording)
Delete a recording in the backend, cleanup db enries.
Parameters
recording The recording
Returns
True on success, false otherwise
References GetVideoDatabase(), and CDatabase::IsOpen().
GetAll()
std::vector< std::shared_ptr< CPVRRecording > > CPVRRecordings::GetAll () const
Get a list of all recordings.
Returns
the list of all recordings
References m_critSection, and m_recordings.
GetById() [1/2]
std::shared_ptr< CPVRRecording > CPVRRecordings::GetById (int iClientId, const std::string & strRecordingId) const
References m_critSection, and m_recordings.
Referenced by UpdateFromClient().
GetById() [2/2]
std::shared_ptr< CPVRRecording > CPVRRecordings::GetById (unsigned int iId) const
References m_critSection, and m_recordings.
GetByPath()
std::shared_ptr< CPVRRecording > CPVRRecordings::GetByPath (const std::string & path) const
References PVR::CPVRRecordingsPath::IsDeleted(), PVR::CPVRRecordingsPath::IsRadio(), PVR::CPVRRecordingsPath::IsValid(), m_critSection, m_recordings, and URIUtils::PathEquals().
GetNumRadioRecordings()
int CPVRRecordings::GetNumRadioRecordings () const
References m_critSection, and m_iRadioRecordings.
GetNumTVRecordings()
int CPVRRecordings::GetNumTVRecordings () const
References m_critSection, and m_iTVRecordings.
GetRecordingCountByProvider()
unsigned int CPVRRecordings::GetRecordingCountByProvider (bool isRadio, int clientId, int providerId) const
Get the total count of recordings offered by the given provider.
Parameters
isRadio Check radio or TV recordings.
clientId The clientId of the provider.
providerId The providerId.
Returns
The total count of matching recordings.
References m_critSection, and m_recordings.
GetRecordingForEpgTag()
std::shared_ptr< CPVRRecording > CPVRRecordings::GetRecordingForEpgTag (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const
Get the recording for the given epg tag, if any.
Parameters
epgTag The epg tag.
Returns
The requested recording, or an empty recordingptr if none was found.
References EPG_TAG_INVALID_UID, m_critSection, and m_recordings.
GetVideoDatabase()
CVideoDatabase & CPVRRecordings::GetVideoDatabase () private
Get/Open the video database.
Returns
A reference to the video database.
References LOGERROR, and m_database.
Referenced by ChangeRecordingsPlayCount(), DeleteRecording(), ResetResumePoint(), and UpdateFromClient().
HasDeletedRadioRecordings()
bool CPVRRecordings::HasDeletedRadioRecordings () const
References m_bDeletedRadioRecordings, and m_critSection.
HasDeletedTVRecordings()
bool CPVRRecordings::HasDeletedTVRecordings () const
References m_bDeletedTVRecordings, and m_critSection.
HasRecordingForProvider()
bool CPVRRecordings::HasRecordingForProvider (bool isRadio, int clientId, int providerId) const
Check whether at least one recording is offered by the given provider.
Parameters
isRadio Check radio or TV recordings.
clientId The clientId to check.
providerId The providerId to check.
Returns
True, if at least one matching recording is offered by the provider, false otherwise.
References m_critSection, and m_recordings.
IncrementRecordingsPlayCount()
bool CPVRRecordings::IncrementRecordingsPlayCount (const std::shared_ptr< CPVRRecording > & recording) private
Increment a recording's play count.
Parameters
recording The recording
Returns
True on success, false otherwise
References ChangeRecordingsPlayCount(), and INCREMENT_PLAY_COUNT.
Referenced by MarkWatched().
MarkWatched()
bool CPVRRecordings::MarkWatched (const std::shared_ptr< CPVRRecording > & recording, bool bWatched)
Set a recording's watched state.
Parameters
recording The recording
bWatched True to set watched, false to set unwatched state
Returns
True on success, false otherwise
References IncrementRecordingsPlayCount(), and SetRecordingsPlayCount().
ResetResumePoint()
bool CPVRRecordings::ResetResumePoint (const std::shared_ptr< CPVRRecording > & recording)
Reset a recording's resume point, if any.
Parameters
recording The recording
Returns
True on success, false otherwise
References CVideoDatabase::ClearBookMarksOfFile(), CServiceBroker::GetPVRManager(), GetVideoDatabase(), CDatabase::IsOpen(), m_critSection, PVR::CPVRManager::PublishEvent(), PVR::RecordingsInvalidated, and CBookmark::RESUME.
SetRecordingsPlayCount()
bool CPVRRecordings::SetRecordingsPlayCount (const std::shared_ptr< CPVRRecording > & recording, int count) private
Set a recording's play count.
Parameters
recording The recording
count The new play count
Returns
True on success, false otherwise
References ChangeRecordingsPlayCount().
Referenced by MarkWatched().
Unload()
void CPVRRecordings::Unload ()
unload all recordings.
References m_bDeletedRadioRecordings, m_bDeletedTVRecordings, m_critSection, m_iRadioRecordings, m_iTVRecordings, and m_recordings.
Update()
bool CPVRRecordings::Update (const std::vector< std::shared_ptr< CPVRClient > > & clients)
Update all recordings from the given PVR clients.
Parameters
clients The PVR clients data should be loaded for. Leave empty for all clients.
Returns
True on success, false otherwise.
References UpdateFromClients().
UpdateFromClient()
void CPVRRecordings::UpdateFromClient (const std::shared_ptr< CPVRRecording > & tag, const CPVRClient & client)
client has delivered a new/updated recording.
Parameters
tag The recording
client The client the recording belongs to.
References GetById(), GetVideoDatabase(), m_bDeletedRadioRecordings, m_bDeletedTVRecordings, m_critSection, m_iLastId, m_iRadioRecordings, m_iTVRecordings, and m_recordings.
Referenced by PVR::CPVRClient::cb_transfer_recording_entry().
UpdateFromClients()
bool CPVRRecordings::UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > & clients)
Update data with recordings from the given clients, sync with local data.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
Returns
True on success, false otherwise.
References PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), m_bIsUpdating, m_critSection, m_recordings, PVR::CPVRManager::PublishEvent(), and PVR::RecordingsInvalidated.
Referenced by Update().
UpdateInProgressSize()
void CPVRRecordings::UpdateInProgressSize ()
refresh the size of any in progress recordings from the clients.
References CServiceBroker::GetPVRManager(), m_bIsUpdating, m_critSection, m_recordings, PVR::CPVRManager::PublishEvent(), and PVR::RecordingsInvalidated.
Member Data Documentation
INCREMENT_PLAY_COUNT
const int PVR::CPVRRecordings::INCREMENT_PLAY_COUNT = -1 static private
special value for parameter count of method ChangeRecordingsPlayCount
Referenced by ChangeRecordingsPlayCount(), and IncrementRecordingsPlayCount().
m_bDeletedRadioRecordings
bool PVR::CPVRRecordings::m_bDeletedRadioRecordings = false private
Referenced by HasDeletedRadioRecordings(), Unload(), and UpdateFromClient().
m_bDeletedTVRecordings
bool PVR::CPVRRecordings::m_bDeletedTVRecordings = false private
Referenced by HasDeletedTVRecordings(), Unload(), and UpdateFromClient().
m_bIsUpdating
bool PVR::CPVRRecordings::m_bIsUpdating = false private
Referenced by UpdateFromClients(), and UpdateInProgressSize().
m_critSection
CCriticalSection PVR::CPVRRecordings::m_critSection mutable private
Referenced by ChangeRecordingsPlayCount(), CleanupCachedImages(), GetAll(), GetById(), GetById(), GetByPath(), GetNumRadioRecordings(), GetNumTVRecordings(), GetRecordingCountByProvider(), GetRecordingForEpgTag(), HasDeletedRadioRecordings(), HasDeletedTVRecordings(), HasRecordingForProvider(), ResetResumePoint(), Unload(), UpdateFromClient(), UpdateFromClients(), and UpdateInProgressSize().
m_database
std::unique_ptr<CVideoDatabase> PVR::CPVRRecordings::m_database private
Referenced by GetVideoDatabase(), and ~CPVRRecordings().
m_iLastId
unsigned int PVR::CPVRRecordings::m_iLastId = 0 private
Referenced by UpdateFromClient().
m_iRadioRecordings
unsigned int PVR::CPVRRecordings::m_iRadioRecordings = 0 private
Referenced by GetNumRadioRecordings(), Unload(), and UpdateFromClient().
m_iTVRecordings
unsigned int PVR::CPVRRecordings::m_iTVRecordings = 0 private
Referenced by GetNumTVRecordings(), Unload(), and UpdateFromClient().
m_recordings
std::map<CPVRRecordingUid, std::shared_ptr<CPVRRecording> > PVR::CPVRRecordings::m_recordings private
Referenced by CleanupCachedImages(), GetAll(), GetById(), GetById(), GetByPath(), GetRecordingCountByProvider(), GetRecordingForEpgTag(), HasRecordingForProvider(), Unload(), UpdateFromClient(), UpdateFromClients(), and UpdateInProgressSize().
The documentation for this class was generated from the following files:
PVRRecordings.h
PVRRecordings.cpp