Kodi Documentation: CAirPlayServer Class Reference
CAirPlayServer Class Reference
#include <AirPlayServer.h>
Classes
class CTCPClient
Public Member Functions
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Static Public Member Functions
static bool StartServer (int port, bool nonlocal)
static void StopServer (bool bWait)
static bool IsRunning ()
static bool SetCredentials (bool usePassword, const std::string &password)
static bool IsPlaying ()
static void backupVolume ()
static void restoreVolume ()
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Static Public Attributes
static int m_isPlaying = 0
Protected Member Functions
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Member Functions
CAirPlayServer (int port, bool nonlocal)
~CAirPlayServer () override
bool SetInternalCredentials (bool usePassword, const std::string &password)
bool Initialize ()
void Deinitialize ()
void AnnounceToClients (int state)
Private Attributes
CCriticalSection m_connectionLock
std::vector< CTCPClient > m_connections
std::map< std::string, int > m_reverseSockets
std::vector< SOCKET > m_ServerSockets
int m_port
bool m_nonlocal
bool m_usePassword
std::string m_password
int m_origVolume
Static Private Attributes
static CCriticalSection ServerInstanceLock
static CAirPlayServer * ServerInstance = NULL
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CAirPlayServer()
CAirPlayServer::CAirPlayServer (int port, bool nonlocal) private
References CServiceBroker::GetAnnouncementManager(), m_nonlocal, m_origVolume, m_port, m_usePassword, and ANNOUNCEMENT::Player.
~CAirPlayServer()
CAirPlayServer::~CAirPlayServer () override private
References CServiceBroker::GetAnnouncementManager().
Member Function Documentation
Announce()
void CAirPlayServer::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References ANNOUNCEMENT::CAnnouncementManager::ANNOUNCEMENT_SENDER, AnnounceToClients(), data(), EVENT_PAUSED, EVENT_PLAYING, EVENT_STOPPED, restoreVolume(), ServerInstance, and ServerInstanceLock.
AnnounceToClients()
void CAirPlayServer::AnnounceToClients (int state) private
References INVALID_SOCKET, m_connectionLock, m_connections, and m_reverseSockets.
Referenced by Announce(), and CAirPlayServer::CTCPClient::ProcessRequest().
backupVolume()
void CAirPlayServer::backupVolume () static
References CServiceBroker::GetAppComponents(), m_origVolume, ServerInstance, and ServerInstanceLock.
Referenced by CAirTunesServer::AudioOutputFunctions::audio_set_volume(), and CAirPlayServer::CTCPClient::ProcessRequest().
Deinitialize()
void CAirPlayServer::Deinitialize () private
References m_connectionLock, m_connections, m_reverseSockets, m_ServerSockets, SHUT_RDWR, and shutdown().
Referenced by Initialize(), and Process().
Initialize()
bool CAirPlayServer::Initialize () private
References CreateTCPServerSocket(), Deinitialize(), CLog::Log(), LOGINFO, m_nonlocal, m_port, and m_ServerSockets.
Referenced by Process(), and StartServer().
IsPlaying()
static bool CAirPlayServer::IsPlaying () inline static
References m_isPlaying.
Referenced by CAirTunesServer::AudioOutputFunctions::audio_destroy(), and CAirPlayServer::CTCPClient::ProcessRequest().
IsRunning()
bool CAirPlayServer::IsRunning () static
References IsRunning(), and ServerInstance.
Referenced by CNetworkServices::IsAirPlayServerRunning(), and IsRunning().
Process()
void CAirPlayServer::Process (void) override protected virtual
Reimplemented from CThread.
References Deinitialize(), handleZeroconfAnnouncement(), Initialize(), INVALID_SOCKET, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, CAirPlayServer::CTCPClient::m_addrlen, CThread::m_bStop, CAirPlayServer::CTCPClient::m_cliaddr, m_connectionLock, m_connections, m_reverseSockets, m_ServerSockets, CAirPlayServer::CTCPClient::m_sessionCounter, CAirPlayServer::CTCPClient::m_socket, RECEIVEBUFFER, and CThread::Sleep().
restoreVolume()
void CAirPlayServer::restoreVolume () static
References CServiceBroker::GetAppComponents(), CServiceBroker::GetSettingsComponent(), m_origVolume, ServerInstance, ServerInstanceLock, CSettings::SETTING_SERVICES_AIRPLAYVOLUMECONTROL, and CApplicationVolumeHandling::SetVolume().
Referenced by Announce().
SetCredentials()
bool CAirPlayServer::SetCredentials (bool usePassword, const std::string & password) static
References ServerInstance, ServerInstanceLock, and SetInternalCredentials().
Referenced by CNetworkServices::OnSettingChanging(), and CNetworkServices::StartAirPlayServer().
SetInternalCredentials()
bool CAirPlayServer::SetInternalCredentials (bool usePassword, const std::string & password) private
References m_password, and m_usePassword.
Referenced by SetCredentials().
StartServer()
bool CAirPlayServer::StartServer (int port, bool nonlocal) static
References CThread::Create(), Initialize(), ServerInstance, ServerInstanceLock, and StopServer().
Referenced by CNetworkServices::StartAirPlayServer().
StopServer()
void CAirPlayServer::StopServer (bool bWait) static
References ClearPhotoAssetCache(), ServerInstance, ServerInstanceLock, and CThread::StopThread().
Referenced by StartServer(), and CNetworkServices::StopAirPlayServer().
Member Data Documentation
m_connectionLock
CCriticalSection CAirPlayServer::m_connectionLock private
Referenced by AnnounceToClients(), Deinitialize(), and Process().
m_connections
std::vector<CTCPClient> CAirPlayServer::m_connections private
Referenced by AnnounceToClients(), Deinitialize(), and Process().
m_isPlaying
int CAirPlayServer::m_isPlaying = 0 static
Referenced by IsPlaying(), and CAirPlayServer::CTCPClient::ProcessRequest().
m_nonlocal
bool CAirPlayServer::m_nonlocal private
Referenced by CAirPlayServer(), and Initialize().
m_origVolume
int CAirPlayServer::m_origVolume private
Referenced by backupVolume(), CAirPlayServer(), and restoreVolume().
m_password
std::string CAirPlayServer::m_password private
Referenced by CAirPlayServer::CTCPClient::checkAuthorization(), and SetInternalCredentials().
m_port
int CAirPlayServer::m_port private
Referenced by CAirPlayServer(), and Initialize().
m_reverseSockets
std::map<std::string, int> CAirPlayServer::m_reverseSockets private
Referenced by AnnounceToClients(), Deinitialize(), and Process().
m_ServerSockets
std::vector<SOCKET> CAirPlayServer::m_ServerSockets private
Referenced by Deinitialize(), Initialize(), and Process().
m_usePassword
bool CAirPlayServer::m_usePassword private
Referenced by CAirPlayServer(), CAirPlayServer::CTCPClient::ProcessRequest(), and SetInternalCredentials().
ServerInstance
CAirPlayServer * CAirPlayServer::ServerInstance = NULL static private
Referenced by Announce(), backupVolume(), CAirPlayServer::CTCPClient::checkAuthorization(), IsRunning(), CAirPlayServer::CTCPClient::ProcessRequest(), restoreVolume(), SetCredentials(), StartServer(), and StopServer().
ServerInstanceLock
CCriticalSection CAirPlayServer::ServerInstanceLock static private
Referenced by Announce(), backupVolume(), restoreVolume(), SetCredentials(), StartServer(), and StopServer().
The documentation for this class was generated from the following files:
AirPlayServer.h
AirPlayServer.cpp