Kodi Documentation: CD3DTexture Class Reference
CD3DTexture Class Reference
#include <D3DResource.h>
Public Member Functions
CD3DTexture ()
virtual ~CD3DTexture ()
bool Create (UINT width, UINT height, UINT mipLevels, D3D11_USAGE usage, DXGI_FORMAT format, const void *pInitData=nullptr, unsigned int srcPitch=0)
void Release ()
bool GetDesc (D3D11_TEXTURE2D_DESC *desc) const
bool LockRect (UINT subresource, D3D11_MAPPED_SUBRESOURCE *res, D3D11_MAP mapType) const
bool UnlockRect (UINT subresource) const
ID3D11Texture2D * Get () const
ID3D11ShaderResourceView * GetShaderResource (DXGI_FORMAT format=DXGI_FORMAT_UNKNOWN)
ID3D11ShaderResourceView ** GetAddressOfSRV (DXGI_FORMAT format=DXGI_FORMAT_UNKNOWN)
ID3D11RenderTargetView * GetRenderTarget ()
ID3D11RenderTargetView ** GetAddressOfRTV ()
UINT GetWidth () const
UINT GetHeight () const
DXGI_FORMAT GetFormat () const
void GenerateMipmaps ()
void OnDestroyDevice (bool fatal) override
void OnCreateDevice () override
Public Member Functions inherited from ID3DResource
virtual ~ID3DResource ()
Static Public Member Functions
static void DrawQuad (const CPoint points[4], KODI::UTILS::COLOR::Color color, CD3DTexture *texture, const CRect *texCoords, SHADER_METHOD options=SHADER_METHOD_RENDER_TEXTURE_BLEND)
static void DrawQuad (const CPoint points[4], KODI::UTILS::COLOR::Color color, unsigned numViews, ID3D11ShaderResourceView **view, const CRect *texCoords, SHADER_METHOD options=SHADER_METHOD_RENDER_TEXTURE_BLEND)
static void DrawQuad (const CRect &coords, KODI::UTILS::COLOR::Color color, CD3DTexture *texture, const CRect *texCoords, SHADER_METHOD options=SHADER_METHOD_RENDER_TEXTURE_BLEND)
static void DrawQuad (const CRect &coords, KODI::UTILS::COLOR::Color color, unsigned numViews, ID3D11ShaderResourceView **view, const CRect *texCoords, SHADER_METHOD options=SHADER_METHOD_RENDER_TEXTURE_BLEND)
Protected Member Functions
ID3D11RenderTargetView * GetRenderTargetInternal (unsigned idx=0)
unsigned int GetMemoryUsage (unsigned int pitch) const
bool CreateInternal (const void *pInitData=nullptr, unsigned int srcPitch=0)
void SaveTexture ()
void RestoreTexture ()
Protected Member Functions inherited from ID3DResource
void Register ()
void Unregister ()
Protected Attributes
BYTE * m_data
UINT m_width
UINT m_height
UINT m_mipLevels
UINT m_pitch
UINT m_bindFlags
UINT m_cpuFlags
UINT m_viewIdx
D3D11_USAGE m_usage
DXGI_FORMAT m_format
Microsoft::WRL::ComPtr< ID3D11Texture2D > m_texture
Microsoft::WRL::ComPtr< ID3D11RenderTargetView > m_renderTargets [2]
std::map< DXGI_FORMAT, Microsoft::WRL::ComPtr< ID3D11ShaderResourceView > > m_views
Protected Attributes inherited from ID3DResource
bool m_bRegistered = false
Constructor & Destructor Documentation
CD3DTexture()
CD3DTexture::CD3DTexture ()
References m_bindFlags, m_cpuFlags, m_data, m_format, m_height, m_mipLevels, m_pitch, m_renderTargets, m_texture, m_usage, m_viewIdx, m_views, and m_width.
~CD3DTexture()
CD3DTexture::~CD3DTexture () virtual
References m_data, and Release().
Member Function Documentation
Create()
bool CD3DTexture::Create (UINT width, UINT height, UINT mipLevels, D3D11_USAGE usage, DXGI_FORMAT format, const void * pInitData = nullptr, unsigned int srcPitch = 0)
References CreateInternal(), DX::DXGIFormatToString(), LOGERROR, m_bindFlags, m_cpuFlags, m_format, m_height, m_mipLevels, m_usage, m_width, ID3DResource::Register(), Release(), and usage.
Referenced by CRenderCaptureDX::BeginRender(), CRenderSystemDX::CheckInterlacedStereoView(), CConvolutionShader::CreateHQKernel(), CConvolutionShaderSeparable::CreateIntermediateRenderTarget(), CRendererBase::CreateIntermediateTarget(), CDXTexture::CreateTextureObject(), CRendererDXVA::CRenderBufferImpl::CRenderBufferImpl(), LoadTexture(), and CDXTexture::LoadToGPU().
CreateInternal()
bool CD3DTexture::CreateInternal (const void * pInitData = nullptr, unsigned int srcPitch = 0) protected
References CD3DHelper::BitsPerPixel(), GenerateMipmaps(), DX::DeviceResources::Get(), m_bindFlags, m_cpuFlags, m_format, m_height, m_mipLevels, m_texture, m_usage, and m_width.
Referenced by Create(), and RestoreTexture().
DrawQuad() [1/4]
void CD3DTexture::DrawQuad (const CPoint points[4], KODI::UTILS::COLOR::Color color, CD3DTexture * texture, const CRect * texCoords, SHADER_METHOD options = SHADER_METHOD_RENDER_TEXTURE_BLEND) static
References color, DrawQuad(), and GetShaderResource().
Referenced by DrawQuad(), DrawQuad(), CGUITextureD3D::DrawQuad(), DrawQuad(), and CRenderSystemDX::PresentRender().
DrawQuad() [2/4]
void CD3DTexture::DrawQuad (const CPoint points[4], KODI::UTILS::COLOR::Color color, unsigned numViews, ID3D11ShaderResourceView ** view, const CRect * texCoords, SHADER_METHOD options = SHADER_METHOD_RENDER_TEXTURE_BLEND) static
References CGUIShaderDX::Begin(), color, CGUIShaderDX::DrawQuad(), CGUIShaderDX::SetShaderViews(), SHADER_METHOD_RENDER_DEFAULT, CRectGen< T >::x1, CRectGen< T >::x2, CD3DHelper::XMStoreColor(), CRectGen< T >::y1, and CRectGen< T >::y2.
DrawQuad() [3/4]
void CD3DTexture::DrawQuad (const CRect & coords, KODI::UTILS::COLOR::Color color, CD3DTexture * texture, const CRect * texCoords, SHADER_METHOD options = SHADER_METHOD_RENDER_TEXTURE_BLEND) static
References color, DrawQuad(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
DrawQuad() [4/4]
void CD3DTexture::DrawQuad (const CRect & coords, KODI::UTILS::COLOR::Color color, unsigned numViews, ID3D11ShaderResourceView ** view, const CRect * texCoords, SHADER_METHOD options = SHADER_METHOD_RENDER_TEXTURE_BLEND) static
References color, DrawQuad(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
GenerateMipmaps()
void CD3DTexture::GenerateMipmaps ()
References DX::DeviceResources::Get(), GetShaderResource(), and m_mipLevels.
Referenced by CreateInternal(), and CDXTexture::LoadToGPU().
Get()
ID3D11Texture2D * CD3DTexture::Get () const inline
References m_texture.
Referenced by CScreenshotSurfaceWindows::Capture(), CRenderSystemDX::CheckInterlacedStereoView(), CConvolutionShaderSeparable::CreateIntermediateRenderTarget(), CRendererBase::CreateIntermediateTarget(), CRenderCaptureDX::EndRender(), CRenderSystemDX::GetBackBuffer(), CDXTexture::GetTextureObject(), CDXTexture::LoadToGPU(), and CRendererDXVA::RenderImpl().
GetAddressOfRTV()
ID3D11RenderTargetView ** CD3DTexture::GetAddressOfRTV ()
References GetRenderTargetInternal(), m_renderTargets, and m_viewIdx.
Referenced by CRenderSystemDX::SetStereoMode(), and CWinShader::SetTarget().
GetAddressOfSRV()
ID3D11ShaderResourceView ** CD3DTexture::GetAddressOfSRV (DXGI_FORMAT format = DXGI_FORMAT_UNKNOWN)
References GetShaderResource(), m_format, and m_views.
Referenced by OVERLAY::COverlayQuadsDX::Render(), OVERLAY::COverlayImageDX::Render(), KODI::RETRO::CRPWinOutputShader::SetShaderParameters(), and COutputShader::SetShaderParameters().
GetDesc()
bool CD3DTexture::GetDesc (D3D11_TEXTURE2D_DESC * desc) const
References m_texture.
Referenced by CScreenshotSurfaceWindows::Capture(), LoadTexture(), and CDXTexture::LoadToGPU().
GetFormat()
DXGI_FORMAT CD3DTexture::GetFormat () const inline
References m_format.
Referenced by CRendererBase::CreateIntermediateTarget(), CRendererBase::GetDebugInfo(), and CRendererSoftware::RenderImpl().
GetHeight()
UINT CD3DTexture::GetHeight () const inline
References m_height.
Referenced by CRendererBase::CreateIntermediateTarget(), CRendererHQ::FinalOutput(), CRendererBase::GetDebugInfo(), CConvolutionShader1Pass::Render(), CConvolutionShaderSeparable::Render(), COutputShader::Render(), KODI::RETRO::CRPWinOutputShader::Render(), CRendererDXVA::RenderImpl(), CRendererShaders::RenderImpl(), CRendererSoftware::RenderImpl(), CConvolutionShader1Pass::SetShaderParameters(), CConvolutionShaderSeparable::SetShaderParameters(), COutputShader::SetShaderParameters(), and CConvolutionShaderSeparable::SetStepParams().
GetMemoryUsage()
unsigned int CD3DTexture::GetMemoryUsage (unsigned int pitch) const protected
References m_format, and m_height.
Referenced by SaveTexture().
GetRenderTarget()
ID3D11RenderTargetView * CD3DTexture::GetRenderTarget ()
References GetRenderTargetInternal(), and m_viewIdx.
Referenced by CRenderSystemDX::ClearBuffers(), and CConvolutionShaderSeparable::ClearIntermediateRenderTarget().
GetRenderTargetInternal()
ID3D11RenderTargetView * CD3DTexture::GetRenderTargetInternal (unsigned idx = 0) protected
References FAILED, DX::DeviceResources::Get(), LOGWARNING, m_format, m_renderTargets, and m_texture.
Referenced by GetAddressOfRTV(), and GetRenderTarget().
GetShaderResource()
ID3D11ShaderResourceView * CD3DTexture::GetShaderResource (DXGI_FORMAT format = DXGI_FORMAT_UNKNOWN)
References DX::DeviceResources::Get(), LOGWARNING, m_format, m_texture, and m_views.
Referenced by DrawQuad(), GenerateMipmaps(), GetAddressOfSRV(), CDXTexture::GetShaderResource(), and CD3DEffect::SetTexture().
GetWidth()
UINT CD3DTexture::GetWidth () const inline
References m_width.
Referenced by CRendererBase::CreateIntermediateTarget(), CRendererHQ::FinalOutput(), CRendererBase::GetDebugInfo(), CConvolutionShader1Pass::Render(), CConvolutionShaderSeparable::Render(), COutputShader::Render(), KODI::RETRO::CRPWinOutputShader::Render(), CRendererDXVA::RenderImpl(), CRendererShaders::RenderImpl(), CConvolutionShader1Pass::SetShaderParameters(), CConvolutionShaderSeparable::SetShaderParameters(), COutputShader::SetShaderParameters(), and CConvolutionShaderSeparable::SetStepParams().
LockRect()
bool CD3DTexture::LockRect (UINT subresource, D3D11_MAPPED_SUBRESOURCE * res, D3D11_MAP mapType) const
References DX::DeviceResources::Get(), m_texture, and m_usage.
Referenced by CDXTexture::LoadToGPU(), CRendererSoftware::RenderImpl(), and CRenderCaptureDX::SurfaceToBuffer().
OnCreateDevice()
void CD3DTexture::OnCreateDevice (void) override virtual
Implements ID3DResource.
References RestoreTexture().
OnDestroyDevice()
void CD3DTexture::OnDestroyDevice (bool fatal) override virtual
Implements ID3DResource.
References m_renderTargets, m_texture, m_views, and SaveTexture().
Release()
void CD3DTexture::Release ()
References m_renderTargets, m_texture, m_views, and ID3DResource::Unregister().
Referenced by CRenderCaptureDX::BeginRender(), CRenderSystemDX::CheckInterlacedStereoView(), CRenderCaptureDX::CleanupDX(), OVERLAY::COverlayQuadsDX::COverlayQuadsDX(), Create(), CConvolutionShaderSeparable::CreateIntermediateRenderTarget(), CRendererBase::CreateIntermediateTarget(), CRenderSystemDX::DestroyRenderSystem(), CDXTexture::DestroyTextureObject(), OVERLAY::COverlayImageDX::Load(), LoadTexture(), CDXTexture::LoadToGPU(), and ~CD3DTexture().
RestoreTexture()
void CD3DTexture::RestoreTexture () protected
References CreateInternal(), LOGERROR, m_data, m_pitch, and m_texture.
Referenced by OnCreateDevice().
SaveTexture()
void CD3DTexture::SaveTexture () protected
References FAILED, DX::DeviceResources::Get(), GetMemoryUsage(), LOGERROR, m_data, m_pitch, and m_texture.
Referenced by OnDestroyDevice().
UnlockRect()
bool CD3DTexture::UnlockRect (UINT subresource) const
References DX::DeviceResources::Get(), and m_texture.
Referenced by CDXTexture::LoadToGPU(), CRendererSoftware::RenderImpl(), and CRenderCaptureDX::SurfaceToBuffer().
Member Data Documentation
m_bindFlags
UINT CD3DTexture::m_bindFlags protected
Referenced by CD3DTexture(), Create(), and CreateInternal().
m_cpuFlags
UINT CD3DTexture::m_cpuFlags protected
Referenced by CD3DTexture(), Create(), and CreateInternal().
m_data
BYTE* CD3DTexture::m_data protected
Referenced by CD3DTexture(), RestoreTexture(), SaveTexture(), and ~CD3DTexture().
m_format
DXGI_FORMAT CD3DTexture::m_format protected
Referenced by DX::DeviceResources::CBackBuffer::Acquire(), CD3DTexture(), Create(), CreateInternal(), GetAddressOfSRV(), GetFormat(), GetMemoryUsage(), GetRenderTargetInternal(), and GetShaderResource().
m_height
UINT CD3DTexture::m_height protected
Referenced by DX::DeviceResources::CBackBuffer::Acquire(), CD3DTexture(), Create(), CreateInternal(), GetHeight(), and GetMemoryUsage().
m_mipLevels
UINT CD3DTexture::m_mipLevels protected
Referenced by CD3DTexture(), Create(), CreateInternal(), and GenerateMipmaps().
m_pitch
UINT CD3DTexture::m_pitch protected
Referenced by CD3DTexture(), RestoreTexture(), and SaveTexture().
m_renderTargets
Microsoft::WRL::ComPtr<ID3D11RenderTargetView> CD3DTexture::m_renderTargets[2] protected
Referenced by CD3DTexture(), GetAddressOfRTV(), GetRenderTargetInternal(), OnDestroyDevice(), and Release().
m_texture
Microsoft::WRL::ComPtr<ID3D11Texture2D> CD3DTexture::m_texture protected
Referenced by DX::DeviceResources::CBackBuffer::Acquire(), CD3DTexture(), CreateInternal(), Get(), GetDesc(), GetRenderTargetInternal(), GetShaderResource(), LockRect(), OnDestroyDevice(), Release(), RestoreTexture(), SaveTexture(), and UnlockRect().
m_usage
D3D11_USAGE CD3DTexture::m_usage protected
Referenced by DX::DeviceResources::CBackBuffer::Acquire(), CD3DTexture(), Create(), CreateInternal(), and LockRect().
m_viewIdx
UINT CD3DTexture::m_viewIdx protected
Referenced by CD3DTexture(), GetAddressOfRTV(), GetRenderTarget(), and DX::DeviceResources::CBackBuffer::SetViewIdx().
m_views
std::map<DXGI_FORMAT, Microsoft::WRL::ComPtr<ID3D11ShaderResourceView> > CD3DTexture::m_views protected
Referenced by CD3DTexture(), GetAddressOfSRV(), GetShaderResource(), OnDestroyDevice(), and Release().
m_width
UINT CD3DTexture::m_width protected
Referenced by DX::DeviceResources::CBackBuffer::Acquire(), CD3DTexture(), Create(), CreateInternal(), and GetWidth().
The documentation for this class was generated from the following files:
D3DResource.h
D3DResource.cpp