Kodi Documentation: KODI::GAME::CControllerLayout Class Reference
KODI::GAME::CControllerLayout Class Reference
Games
#include <ControllerLayout.h>
Public Member Functions
CControllerLayout ()
CControllerLayout (const CControllerLayout &other)
~CControllerLayout ()
void Reset (void)
int LabelID (void) const
const std::string & Icon (void) const
const std::string & Image (void) const
bool IsValid (bool bLog) const
Ensures the layout was deserialized correctly, and optionally logs if not.
std::string Label (void) const
Get the label of the primary layout used when mapping the controller.
std::string ImagePath (void) const
Get the image path of the primary layout used when mapping the controller.
const CPhysicalTopology & Topology (void) const
Get the physical topology of this controller.
void Deserialize (const tinyxml2::XMLElement *pLayoutElement, const CController *controller, std::vector< CPhysicalFeature > &features)
Deserialize the specified XML element.
Private Attributes
const CController * m_controller = nullptr
int m_labelId = -1
std::string m_icon
std::string m_strImage
std::unique_ptr< CPhysicalTopology > m_topology
Constructor & Destructor Documentation
CControllerLayout() [1/2]
CControllerLayout::CControllerLayout ()
CControllerLayout() [2/2]
CControllerLayout::CControllerLayout (const CControllerLayout & other)
~CControllerLayout()
CControllerLayout::~CControllerLayout () default
Member Function Documentation
Deserialize()
void CControllerLayout::Deserialize (const tinyxml2::XMLElement * pLayoutElement, const CController * controller, std::vector< CPhysicalFeature > & features)
Deserialize the specified XML element.
Parameters
pLayoutElement The XML element
controller The controller, used to obtain read-only properties
features The deserialized features, if any
References KODI::GAME::CPhysicalTopology::Deserialize(), KODI::GAME::CPhysicalFeature::Deserialize(), XMLUtils::GetAttribute(), ADDON::CAddon::Icon(), LAYOUT_XML_ATTR_CATEGORY_LABEL, LAYOUT_XML_ATTR_CATEGORY_NAME, LAYOUT_XML_ATTR_LAYOUT_ICON, LAYOUT_XML_ATTR_LAYOUT_IMAGE, LAYOUT_XML_ATTR_LAYOUT_LABEL, LAYOUT_XML_ELM_CATEGORY, LAYOUT_XML_ELM_TOPOLOGY, CLog::Log(), LOGDEBUG, m_controller, m_icon, m_labelId, m_strImage, m_topology, and KODI::GAME::CControllerTranslator::TranslateFeatureCategory().
Icon()
const std::string & KODI::GAME::CControllerLayout::Icon (void) const inline
References m_icon.
Image()
const std::string & KODI::GAME::CControllerLayout::Image (void) const inline
References m_strImage.
ImagePath()
std::string CControllerLayout::ImagePath (void) const
Get the image path of the primary layout used when mapping the controller.
Returns
The image path, or empty if unknown
References URIUtils::AddFileToFolder(), URIUtils::GetDirectory(), ADDON::CAddon::LibPath(), m_controller, and m_strImage.
IsValid()
bool CControllerLayout::IsValid (bool bLog) const
Ensures the layout was deserialized correctly, and optionally logs if not.
Parameters
bLog If true, output the cause of invalidness to the log
Returns
True if the layout is valid and can be used in the GUI, false otherwise
References LAYOUT_XML_ATTR_LAYOUT_IMAGE, LAYOUT_XML_ATTR_LAYOUT_LABEL, LAYOUT_XML_ROOT, CLog::Log(), LOGDEBUG, LOGERROR, m_labelId, and m_strImage.
Label()
std::string CControllerLayout::Label (void) const
Get the label of the primary layout used when mapping the controller.
Returns
The label, or empty if unknown
References g_localizeStrings, CLocalizeStrings::GetAddonString(), ADDON::CAddon::ID(), label, m_controller, and m_labelId.
LabelID()
int KODI::GAME::CControllerLayout::LabelID (void) const inline
References m_labelId.
Reset()
void CControllerLayout::Reset (void)
References m_controller, m_icon, m_labelId, m_strImage, and m_topology.
Topology()
const CPhysicalTopology & KODI::GAME::CControllerLayout::Topology (void) const inline
Get the physical topology of this controller.
The topology of a controller defines its ports and which controllers can physically be connected to them. Also, the topology defines if the controller can provide player input, which is false in the case of hubs.
Returns
The physical topology of the controller
References m_topology.
Member Data Documentation
m_controller
const CController* KODI::GAME::CControllerLayout::m_controller = nullptr private
Referenced by Deserialize(), ImagePath(), Label(), and Reset().
m_icon
std::string KODI::GAME::CControllerLayout::m_icon private
Referenced by Deserialize(), Icon(), and Reset().
m_labelId
int KODI::GAME::CControllerLayout::m_labelId = -1 private
Referenced by Deserialize(), IsValid(), Label(), LabelID(), and Reset().
m_strImage
std::string KODI::GAME::CControllerLayout::m_strImage private
Referenced by Deserialize(), Image(), ImagePath(), IsValid(), and Reset().
m_topology
std::unique_ptr<CPhysicalTopology> KODI::GAME::CControllerLayout::m_topology private
Referenced by Deserialize(), Reset(), and Topology().
The documentation for this class was generated from the following files:
ControllerLayout.h
ControllerLayout.cpp