Kodi Documentation: AEDelayStatus Struct Reference
AEDelayStatus Struct Reference
#include <AEUtil.h>
Public Member Functions
void SetDelay (double d)
double GetDelay () const
Public Attributes
double delay = 0.0
double maxcorrection = 0.0
int64_t tick = 0
Member Function Documentation
GetDelay()
double AEDelayStatus::GetDelay () const
References CurrentHostCounter(), CurrentHostFrequency(), delay, maxcorrection, and tick.
Referenced by CAESinkWASAPI::Drain(), ActiveAE::CActiveAEStream::GetDelay(), ActiveAE::CEngineStats::GetSyncInfo(), ActiveAE::CActiveAE::RunStages(), and ActiveAE::CActiveAE::StateMachine().
SetDelay()
void AEDelayStatus::SetDelay (double d)
References CurrentHostCounter(), delay, maxcorrection, and tick.
Referenced by CAESinkDirectSound::GetDelay(), CAESinkALSA::GetDelay(), CAESinkAUDIOTRACK::GetDelay(), CAESinkDARWINIOS::GetDelay(), CAESinkDARWINTVOS::GetDelay(), CAESinkOSS::GetDelay(), CAESinkPULSE::GetDelay(), CAESinkSNDIO::GetDelay(), CAESinkStarfish::GetDelay(), CAESinkWASAPI::GetDelay(), CAESinkXAudio::GetDelay(), AE::SINK::CAESinkPipewire::GetDelay(), ActiveAE::CActiveAESink::OutputSamples(), and ActiveAE::CEngineStats::Reset().
Member Data Documentation
delay
double AEDelayStatus::delay = 0.0
Referenced by GetDelay(), ActiveAE::CEngineStats::GetDelay(), CAAudioUnitSink::getDelay(), CAESinkDARWINOSX::GetDelay(), CAESinkWASAPI::GetDelay(), ActiveAE::CEngineStats::GetDelay(), ActiveAE::CEngineStats::GetSyncInfo(), ActiveAE::CActiveAESink::OutputSamples(), SetDelay(), and CAAudioUnitSink::updatedelay().
maxcorrection
double AEDelayStatus::maxcorrection = 0.0
Referenced by GetDelay(), and SetDelay().
tick
int64_t AEDelayStatus::tick = 0
Referenced by GetDelay(), CAAudioUnitSink::getDelay(), CAESinkDARWINOSX::GetDelay(), CAESinkWASAPI::GetDelay(), SetDelay(), and CAAudioUnitSink::updatedelay().
The documentation for this struct was generated from the following files:
AEUtil.h
AEUtil.cpp