Kodi Documentation: IInputHandler Class Reference
IInputHandler Class Reference
#include <IInputHandler.h>
Public Member Functions
IInputHandler ()
void setDPI (uint32_t dpi) override
Public Member Functions inherited from CAndroidKey
CAndroidKey ()=default
~CAndroidKey ()=default
bool onKeyboardEvent (AInputEvent *event)
Public Member Functions inherited from CAndroidMouse
CAndroidMouse ()=default
virtual ~CAndroidMouse ()=default
bool onMouseEvent (AInputEvent *event)
Public Member Functions inherited from CAndroidTouch
CAndroidTouch ()
virtual ~CAndroidTouch ()
bool onTouchEvent (AInputEvent *event)
Public Member Functions inherited from CAndroidJoyStick
CAndroidJoyStick ()=default
~CAndroidJoyStick ()=default
bool onJoyStickEvent (AInputEvent *event)
Additional Inherited Members
Static Public Member Functions inherited from CAndroidKey
static void SetHandleMediaKeys (bool enable)
static void SetHandleSearchKeys (bool enable)
static void XBMC_Key (uint8_t code, uint16_t key, uint16_t modifiers, uint16_t unicode, bool up)
Static Protected Attributes inherited from CAndroidKey
static bool m_handleMediaKeys = true
static bool m_handleSearchKeys = false
Constructor & Destructor Documentation
IInputHandler()
IInputHandler::IInputHandler () inline
Member Function Documentation
setDPI()
void IInputHandler::setDPI (uint32_t dpi) inline override virtual
Reimplemented from CAndroidTouch.
References CAndroidTouch::setDPI().
Referenced by CXBMCApp::onDisplayChanged(), CXBMCApp::onStart(), and CEventLoop::processActivity().
The documentation for this class was generated from the following file:
platform/android/activity/IInputHandler.h