Kodi Documentation: KODI::WINDOWING::WAYLAND::CInputProcessorTouch Class Reference
KODI::WINDOWING::WAYLAND::CInputProcessorTouch Class Reference final
#include <InputProcessorTouch.h>
Classes
struct TouchPoint
Public Member Functions
CInputProcessorTouch (wayland::surface_t const &surface)
~CInputProcessorTouch () noexcept
void SetCoordinateScale (std::int32_t scale)
void OnTouchDown (CSeat *seat, std::uint32_t serial, std::uint32_t time, const wayland::surface_t &surface, std::int32_t id, double x, double y) override
void OnTouchUp (CSeat *seat, std::uint32_t serial, std::uint32_t time, std::int32_t id) override
void OnTouchMotion (CSeat *seat, std::uint32_t time, std::int32_t id, double x, double y) override
void OnTouchCancel (CSeat *seat) override
void OnTouchShape (CSeat *seat, std::int32_t id, double major, double minor) override
Private Member Functions
CInputProcessorTouch (CInputProcessorTouch const &other)=delete
CInputProcessorTouch & operator= (CInputProcessorTouch const &other)=delete
void SendTouchPointEvent (TouchInput event, TouchPoint const &point)
void UpdateTouchPoint (TouchPoint const &point)
void AbortTouches ()
Private Attributes
wayland::surface_t m_surface
std::int32_t m_coordinateScale {1}
std::map< std::int32_t, TouchPoint > m_touchPoints
Map of wl_touch point id to data.
Additional Inherited Members
Protected Member Functions inherited from KODI::WINDOWING::WAYLAND::IRawInputHandlerTouch
~IRawInputHandlerTouch ()=default
Detailed Description
Touch input processor
Events go directly to CGenericTouchInputHandler, so no callbacks here
Constructor & Destructor Documentation
CInputProcessorTouch() [1/2]
CInputProcessorTouch::CInputProcessorTouch (wayland::surface_t const & surface)
~CInputProcessorTouch()
CInputProcessorTouch::~CInputProcessorTouch () noexcept
References AbortTouches().
CInputProcessorTouch() [2/2]
KODI::WINDOWING::WAYLAND::CInputProcessorTouch::CInputProcessorTouch (CInputProcessorTouch const & other) private delete
Member Function Documentation
AbortTouches()
void CInputProcessorTouch::AbortTouches () private
References m_touchPoints, SendTouchPointEvent(), and TouchInputAbort.
Referenced by OnTouchCancel(), and ~CInputProcessorTouch().
OnTouchCancel()
void CInputProcessorTouch::OnTouchCancel (CSeat * seat) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerTouch.
References AbortTouches().
OnTouchDown()
void CInputProcessorTouch::OnTouchDown (CSeat * seat, std::uint32_t serial, std::uint32_t time, const wayland::surface_t & surface, std::int32_t id, double x, double y) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerTouch.
References m_coordinateScale, m_surface, m_touchPoints, CGenericTouchInputHandler::MAX_POINTERS, SendTouchPointEvent(), and TouchInputDown.
OnTouchMotion()
void CInputProcessorTouch::OnTouchMotion (CSeat * seat, std::uint32_t time, std::int32_t id, double x, double y) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerTouch.
References m_coordinateScale, m_touchPoints, SendTouchPointEvent(), and TouchInputMove.
OnTouchShape()
void CInputProcessorTouch::OnTouchShape (CSeat * seat, std::int32_t id, double major, double minor) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerTouch.
References m_coordinateScale, m_touchPoints, and UpdateTouchPoint().
OnTouchUp()
void CInputProcessorTouch::OnTouchUp (CSeat * seat, std::uint32_t serial, std::uint32_t time, std::int32_t id) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerTouch.
References m_touchPoints, SendTouchPointEvent(), and TouchInputUp.
operator=()
CInputProcessorTouch & KODI::WINDOWING::WAYLAND::CInputProcessorTouch::operator= (CInputProcessorTouch const & other) private delete
SendTouchPointEvent()
void CInputProcessorTouch::SendTouchPointEvent (TouchInput event, TouchPoint const & point) private
References CGenericTouchInputHandler::GetInstance(), CGenericTouchInputHandler::HandleTouchInput(), KODI::WINDOWING::WAYLAND::CInputProcessorTouch::TouchPoint::kodiPointerNumber, KODI::WINDOWING::WAYLAND::CInputProcessorTouch::TouchPoint::lastEventTime, m_touchPoints, KODI::WINDOWING::WAYLAND::CInputProcessorTouch::TouchPoint::size, TouchInputMove, UpdateTouchPoint(), KODI::WINDOWING::WAYLAND::CInputProcessorTouch::TouchPoint::x, and KODI::WINDOWING::WAYLAND::CInputProcessorTouch::TouchPoint::y.
Referenced by AbortTouches(), OnTouchDown(), OnTouchMotion(), and OnTouchUp().
SetCoordinateScale()
void KODI::WINDOWING::WAYLAND::CInputProcessorTouch::SetCoordinateScale (std::int32_t scale) inline
References m_coordinateScale.
UpdateTouchPoint()
void CInputProcessorTouch::UpdateTouchPoint (TouchPoint const & point) private
References CGenericTouchInputHandler::GetInstance(), KODI::WINDOWING::WAYLAND::CInputProcessorTouch::TouchPoint::kodiPointerNumber, KODI::WINDOWING::WAYLAND::CInputProcessorTouch::TouchPoint::lastEventTime, KODI::WINDOWING::WAYLAND::CInputProcessorTouch::TouchPoint::size, CGenericTouchInputHandler::UpdateTouchPointer(), KODI::WINDOWING::WAYLAND::CInputProcessorTouch::TouchPoint::x, and KODI::WINDOWING::WAYLAND::CInputProcessorTouch::TouchPoint::y.
Referenced by OnTouchShape(), and SendTouchPointEvent().
Member Data Documentation
m_coordinateScale
std::int32_t KODI::WINDOWING::WAYLAND::CInputProcessorTouch::m_coordinateScale {1} private
Referenced by OnTouchDown(), OnTouchMotion(), OnTouchShape(), and SetCoordinateScale().
m_surface
wayland::surface_t KODI::WINDOWING::WAYLAND::CInputProcessorTouch::m_surface private
Referenced by OnTouchDown().
m_touchPoints
std::map<std::int32_t, TouchPoint> KODI::WINDOWING::WAYLAND::CInputProcessorTouch::m_touchPoints private
Map of wl_touch point id to data.
Referenced by AbortTouches(), OnTouchDown(), OnTouchMotion(), OnTouchShape(), OnTouchUp(), and SendTouchPointEvent().
The documentation for this class was generated from the following files:
InputProcessorTouch.h
InputProcessorTouch.cpp