Kodi Documentation: anonymous_namespace{GUIBuiltins.cpp} Namespace Reference
anonymous_namespace{GUIBuiltins.cpp} Namespace Reference
Functions
static int Action (const std::vector< std::string > &params)
Execute a GUI action.
template<bool Replace>
static int ActivateWindow (const std::vector< std::string > &params2)
Activate a window.
template<bool Replace>
static int ActivateAndFocus (const std::vector< std::string > &params)
Activate a window and give given controls focus.
static int AlarmClock (const std::vector< std::string > &params)
Start an alarm clock.
static int CancelAlarm (const std::vector< std::string > &params)
Cancel an alarm clock.
static int ClearProperty (const std::vector< std::string > &params)
Clear a property in a window.
static int CloseDialog (const std::vector< std::string > &params)
Close a dialog.
static int Notification (const std::vector< std::string > &params)
Send a notification.
static int RefreshRSS (const std::vector< std::string > &params)
Refresh RSS feed.
static int Screenshot (const std::vector< std::string > &params)
Take a screenshot.
static int SetLanguage (const std::vector< std::string > &params)
Set GUI language.
static int SetProperty (const std::vector< std::string > &params)
Set a property in a window.
static int SetStereoMode (const std::vector< std::string > &params)
Set GUI stereo mode.
static int ToggleDirty (const std::vector< std::string > &)
Toggle visualization of dirty regions.
Function Documentation
Action()
static int anonymous_namespace{GUIBuiltins.cpp}::Action (const std::vector< std::string > & params) static
Execute a GUI action.
Parameters
params The parameters.
params[0] = Action to execute. params[1] = Window to send action to (optional).
References CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, KODI::ACTION::CActionTranslator::TranslateString(), CWindowTranslator::TranslateWindow(), and WINDOW_INVALID.
ActivateAndFocus()
template<bool Replace> static int anonymous_namespace{GUIBuiltins.cpp}::ActivateAndFocus (const std::vector< std::string > & params) static
Activate a window and give given controls focus.
Parameters
params The parameters.
params[0] = The window name. params[1,...] = Pair of (container ID, focus item).
Set the Replace template parameter to true to replace current window in history.
References CGUIWindowManager::ActivateWindow(), CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_SETFOCUS, CLog::Log(), LOGERROR, CGUIWindowManager::SendMessage(), CWindowTranslator::TranslateWindow(), CApplicationPowerHandling::WakeUpScreenSaverAndDPMS(), and WINDOW_INVALID.
ActivateWindow()
template<bool Replace> static int anonymous_namespace{GUIBuiltins.cpp}::ActivateWindow (const std::vector< std::string > & params2) static
Activate a window.
Parameters
params The parameters.
params[0] = The window name. params[1] = Window starting folder (optional).
Set the Replace template parameter to true to replace current window in history.
References CGUIWindowManager::ActivateWindow(), CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIWindow::IsMediaWindow(), CLog::Log(), LOGERROR, CWindowTranslator::TranslateWindow(), CApplicationPowerHandling::WakeUpScreenSaverAndDPMS(), and WINDOW_INVALID.
AlarmClock()
static int anonymous_namespace{GUIBuiltins.cpp}::AlarmClock (const std::vector< std::string > & params) static
Start an alarm clock.
Parameters
params The parameters.
param[0] = name param[1] = command param[2] = Length in seconds (optional). param[3] = "silent" to suppress notifications. param[3] = "loop" to loop the alarm.
References KODI::UTILS::StringUtils::EqualsNoCase(), g_alarmClock, g_localizeStrings, CLocalizeStrings::Get(), CAlarmClock::IsRunning(), CGUIDialogNumeric::ShowAndGetNumber(), CAlarmClock::Start(), CAlarmClock::Stop(), and KODI::UTILS::StringUtils::TimeStringToSeconds().
CancelAlarm()
static int anonymous_namespace{GUIBuiltins.cpp}::CancelAlarm (const std::vector< std::string > & params) static
Cancel an alarm clock.
Parameters
params The parameters.
params[0] = "true" to silently cancel alarm (optional).
References KODI::UTILS::StringUtils::EqualsNoCase(), g_alarmClock, and CAlarmClock::Stop().
ClearProperty()
static int anonymous_namespace{GUIBuiltins.cpp}::ClearProperty (const std::vector< std::string > & params) static
Clear a property in a window.
Parameters
params The parameters.
params[0] = The property to clear. params[1] = The window to clear property in (optional).
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIWindow::SetProperty(), and CWindowTranslator::TranslateWindow().
CloseDialog()
static int anonymous_namespace{GUIBuiltins.cpp}::CloseDialog (const std::vector< std::string > & params) static
Close a dialog.
Parameters
params The parameters.
params[0] = "all" to close all dialogs, or dialog name. params[1] = "true" to force close (skip animations) (optional).
References Close(), CGUIWindowManager::CloseDialogs(), KODI::UTILS::StringUtils::EqualsNoCase(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIWindow::IsDialog(), and CWindowTranslator::TranslateWindow().
Notification()
static int anonymous_namespace{GUIBuiltins.cpp}::Notification (const std::vector< std::string > & params) static
Send a notification.
Parameters
params The parameters.
params[0] = Notification title. params[1] = Notification text. params[2] = Display time in milliseconds (optional). params[3] = Notification icon (optional).
References CGUIDialogKaiToast::QueueNotification().
RefreshRSS()
static int anonymous_namespace{GUIBuiltins.cpp}::RefreshRSS (const std::vector< std::string > & params) static
Refresh RSS feed.
Parameters
params (ignored)
References CRssManager::GetInstance(), and CRssManager::Reload().
Screenshot()
static int anonymous_namespace{GUIBuiltins.cpp}::Screenshot (const std::vector< std::string > & params) static
Take a screenshot.
Parameters
params The parameters.
params[0] = URL to save file to. Blank to use default. params[1] = "sync" to run synchronously (optional).
References URIUtils::AddFileToFolder(), KODI::UTILS::StringUtils::EqualsNoCase(), XFILE::CDirectory::Exists(), CUtil::GetNextFilename(), CLog::Log(), LOGWARNING, and CScreenShot::TakeScreenshot().
SetLanguage()
static int anonymous_namespace{GUIBuiltins.cpp}::SetLanguage (const std::vector< std::string > & params) static
Set GUI language.
Parameters
params The parameters.
params[0] = The language to use.
References CServiceBroker::GetAppMessenger(), and TMSG_SETLANGUAGE.
SetProperty()
static int anonymous_namespace{GUIBuiltins.cpp}::SetProperty (const std::vector< std::string > & params) static
Set a property in a window.
Parameters
params The parameters.
params[0] = The property to set. params[1] = The property value. params[2] = The window to set property in (optional).
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIWindow::SetProperty(), and CWindowTranslator::TranslateWindow().
SetStereoMode()
static int anonymous_namespace{GUIBuiltins.cpp}::SetStereoMode (const std::vector< std::string > & params) static
Set GUI stereo mode.
Parameters
params The parameters.
param[0] = Stereo mode identifier.
References ACTION_NONE, CStereoscopicsManager::ConvertActionCommandToAction(), CServiceBroker::GetAppMessenger(), CLog::Log(), LOGERROR, TMSG_GUI_ACTION, and WINDOW_INVALID.
ToggleDirty()
static int anonymous_namespace{GUIBuiltins.cpp}::ToggleDirty (const std::vector< std::string > &) static
Toggle visualization of dirty regions.
Parameters
params Ignored.
References CServiceBroker::GetSettingsComponent().