Kodi Documentation: XFILE::CAPKFile Class Reference
XFILE::CAPKFile Class Reference
#include <APKFile.h>
Public Member Functions
CAPKFile ()
~CAPKFile () override=default
bool Open (const CURL &url) override
void Close () override
bool Exists (const CURL &url) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
int Stat (struct __stat64 *buffer) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int64_t GetLength () override
int64_t GetPosition () override
int GetChunkSize () override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool OpenForWrite (const CURL &url, bool bOverWrite=false)
virtual bool ReOpen (const CURL &url)
virtual ssize_t Write (const void *bufPtr, size_t bufSize)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual double GetDownloadSpeed ()
virtual bool Delete (const CURL &url)
virtual bool Rename (const CURL &url, const CURL &urlnew)
virtual bool SetHidden (const CURL &url, bool hidden)
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Protected Attributes
CURL m_url
int m_zip_index
int64_t m_file_pos
int64_t m_file_size
struct zip_file * m_zip_file
struct zip * m_zip_archive
Constructor & Destructor Documentation
CAPKFile()
CAPKFile::CAPKFile ()
References m_file_pos, m_file_size, m_zip_archive, m_zip_file, and m_zip_index.
~CAPKFile()
XFILE::CAPKFile::~CAPKFile () override default
Member Function Documentation
Close()
void CAPKFile::Close () override virtual
Implements XFILE::IFile.
References m_file_pos, m_file_size, m_zip_archive, m_zip_file, and m_zip_index.
Referenced by Open().
Exists()
bool CAPKFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References __stat64, and Stat().
Referenced by XFILE::CAPKDirectory::Exists().
GetChunkSize()
int CAPKFile::GetChunkSize () override virtual
Reimplemented from XFILE::IFile.
GetLength()
int64_t CAPKFile::GetLength () override virtual
Implements XFILE::IFile.
References m_file_size.
GetPosition()
int64_t CAPKFile::GetPosition () override virtual
Implements XFILE::IFile.
References m_file_pos.
Open()
bool CAPKFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References Close(), CURL::GetFileName(), CURL::GetHostName(), CLog::Log(), LOGDEBUG, LOGERROR, m_file_pos, m_file_size, m_url, m_zip_archive, m_zip_file, and m_zip_index.
Read()
ssize_t CAPKFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References m_file_pos, m_file_size, m_zip_archive, m_zip_file, and SSIZE_MAX.
Seek()
int64_t CAPKFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
References m_file_pos, m_file_size, m_zip_archive, m_zip_file, and m_zip_index.
Stat() [1/2]
int CAPKFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References __stat64, _S_IFDIR, _S_IFREG, URIUtils::AddSlashAtEnd(), CURL::GetFileName(), CURL::GetHostName(), URIUtils::HasSlashAtEnd(), CLog::Log(), LOGERROR, name, and URIUtils::PathHasParent().
Stat() [2/2]
int CAPKFile::Stat (struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about currently open file For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Reimplemented from XFILE::IFile.
References m_url, and Stat().
Referenced by Exists(), and Stat().
Member Data Documentation
m_file_pos
int64_t XFILE::CAPKFile::m_file_pos protected
Referenced by CAPKFile(), Close(), GetPosition(), Open(), Read(), and Seek().
m_file_size
int64_t XFILE::CAPKFile::m_file_size protected
Referenced by CAPKFile(), Close(), GetLength(), Open(), Read(), and Seek().
m_url
CURL XFILE::CAPKFile::m_url protected
Referenced by Open(), and Stat().
m_zip_archive
struct zip* XFILE::CAPKFile::m_zip_archive protected
Referenced by CAPKFile(), Close(), Open(), Read(), and Seek().
m_zip_file
struct zip_file* XFILE::CAPKFile::m_zip_file protected
Referenced by CAPKFile(), Close(), Open(), Read(), and Seek().
m_zip_index
int XFILE::CAPKFile::m_zip_index protected
Referenced by CAPKFile(), Close(), Open(), and Seek().
The documentation for this class was generated from the following files:
APKFile.h
APKFile.cpp