Kodi Documentation: ADDON::Interface_GUIDialogNumeric Struct Reference
ADDON::Interface_GUIDialogNumeric Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Numeric.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static bool show_and_verify_new_password (KODI_HANDLE kodiBase, char **password)
callback functions from add-on to kodi
static int show_and_verify_password (KODI_HANDLE kodiBase, const char *password, const char *heading, int retries)
static bool show_and_verify_input (KODI_HANDLE kodiBase, const char *verify_in, char **verify_out, const char *heading, bool verify_input)
static bool show_and_get_time (KODI_HANDLE kodiBase, tm *time, const char *heading)
static bool show_and_get_date (KODI_HANDLE kodiBase, tm *date, const char *heading)
static bool show_and_get_ip_address (KODI_HANDLE kodiBase, const char *ip_address_in, char **ip_address_out, const char *heading)
static bool show_and_get_number (KODI_HANDLE kodiBase, const char *number_in, char **number_out, const char *heading, unsigned int auto_close_ms)
static bool show_and_get_seconds (KODI_HANDLE kodiBase, const char *time_in, char **time_out, const char *heading)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/dialogs/Numeric.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIDialogNumeric::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogNumeric, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
Init()
void ADDON::Interface_GUIDialogNumeric::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogNumeric, AddonToKodiFuncTable_Addon::kodi_gui, show_and_get_date(), AddonToKodiFuncTable_kodi_gui_dialogNumeric::show_and_get_date, show_and_get_ip_address(), AddonToKodiFuncTable_kodi_gui_dialogNumeric::show_and_get_ip_address, show_and_get_number(), AddonToKodiFuncTable_kodi_gui_dialogNumeric::show_and_get_number, show_and_get_seconds(), AddonToKodiFuncTable_kodi_gui_dialogNumeric::show_and_get_seconds, show_and_get_time(), AddonToKodiFuncTable_kodi_gui_dialogNumeric::show_and_get_time, show_and_verify_input(), AddonToKodiFuncTable_kodi_gui_dialogNumeric::show_and_verify_input, show_and_verify_new_password(), AddonToKodiFuncTable_kodi_gui_dialogNumeric::show_and_verify_new_password, show_and_verify_password(), AddonToKodiFuncTable_kodi_gui_dialogNumeric::show_and_verify_password, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
show_and_get_date()
bool ADDON::Interface_GUIDialogNumeric::show_and_get_date (KODI_HANDLE kodiBase, tm * date, const char * heading) static
References CDateTime::GetAsSystemTime(), CDateTime::GetAsTm(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogNumeric::ShowAndGetDate().
Referenced by Init().
show_and_get_ip_address()
bool ADDON::Interface_GUIDialogNumeric::show_and_get_ip_address (KODI_HANDLE kodiBase, const char * ip_address_in, char ** ip_address_out, const char * heading) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogNumeric::ShowAndGetIPAddress().
Referenced by Init().
show_and_get_number()
bool ADDON::Interface_GUIDialogNumeric::show_and_get_number (KODI_HANDLE kodiBase, const char * number_in, char ** number_out, const char * heading, unsigned int auto_close_ms) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogNumeric::ShowAndGetNumber().
Referenced by Init().
show_and_get_seconds()
bool ADDON::Interface_GUIDialogNumeric::show_and_get_seconds (KODI_HANDLE kodiBase, const char * time_in, char ** time_out, const char * heading) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogNumeric::ShowAndGetSeconds().
Referenced by Init().
show_and_get_time()
bool ADDON::Interface_GUIDialogNumeric::show_and_get_time (KODI_HANDLE kodiBase, tm * time, const char * heading) static
References CDateTime::GetAsSystemTime(), CDateTime::GetAsTm(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogNumeric::ShowAndGetTime().
Referenced by Init().
show_and_verify_input()
bool ADDON::Interface_GUIDialogNumeric::show_and_verify_input (KODI_HANDLE kodiBase, const char * verify_in, char ** verify_out, const char * heading, bool verify_input) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUIDialogNumeric::ShowAndVerifyInput(), and SUCCESS.
Referenced by Init().
show_and_verify_new_password()
bool ADDON::Interface_GUIDialogNumeric::show_and_verify_new_password (KODI_HANDLE kodiBase, char ** password) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References CLog::Log(), LOGERROR, and CGUIDialogNumeric::ShowAndVerifyNewPassword().
Referenced by Init().
show_and_verify_password()
int ADDON::Interface_GUIDialogNumeric::show_and_verify_password (KODI_HANDLE kodiBase, const char * password, const char * heading, int retries) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogNumeric::ShowAndVerifyPassword().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/dialogs/numeric.h
Numeric.cpp