Kodi Documentation: WinSystemWin32DX.cpp File Reference
WinSystemWin32DX.cpp File Reference
#include "WinSystemWin32DX.h"
#include "commons/ilog.h"
#include "rendering/dx/RenderContext.h"
#include "settings/DisplaySettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/SystemInfo.h"
#include "utils/XTimeUtils.h"
#include "utils/log.h"
#include "windowing/GraphicContext.h"
#include "windowing/WindowSystemFactory.h"
#include "platform/win32/CharsetConverter.h"
#include "platform/win32/WIN32Util.h"
#include <windows.h>
#include <winnt.h>
#include <winternl.h>
#include <d3d10umddi.h>
#include <detours.h>
Functions
void APIENTRY HookCreateResource (D3D10DDI_HDEVICE hDevice, const D3D10DDIARG_CREATERESOURCE *pResource, D3D10DDI_HRESOURCE hResource, D3D10DDI_HRTRESOURCE hRtResource)
HRESULT APIENTRY HookCreateDevice (D3D10DDI_HADAPTER hAdapter, D3D10DDIARG_CREATEDEVICE *pCreateData)
HRESULT APIENTRY HookOpenAdapter10_2 (D3D10DDIARG_OPENADAPTER *pOpenData)
Variables
static PFND3D10DDI_OPENADAPTER s_fnOpenAdapter10_2 { nullptr }
static PFND3D10DDI_CREATEDEVICE s_fnCreateDeviceOrig { nullptr }
static PFND3D10DDI_CREATERESOURCE s_fnCreateResourceOrig { nullptr }
Function Documentation
HookCreateDevice()
HRESULT APIENTRY HookCreateDevice (D3D10DDI_HADAPTER hAdapter, D3D10DDIARG_CREATEDEVICE * pCreateData)
References HookCreateResource(), LOGDEBUG, s_fnCreateDeviceOrig, and s_fnCreateResourceOrig.
Referenced by HookOpenAdapter10_2().
HookCreateResource()
void APIENTRY HookCreateResource (D3D10DDI_HDEVICE hDevice, const D3D10DDIARG_CREATERESOURCE * pResource, D3D10DDI_HRESOURCE hResource, D3D10DDI_HRTRESOURCE hRtResource)
References s_fnCreateResourceOrig.
Referenced by HookCreateDevice().
HookOpenAdapter10_2()
HRESULT APIENTRY HookOpenAdapter10_2 (D3D10DDIARG_OPENADAPTER * pOpenData)
References HookCreateDevice(), LOGDEBUG, s_fnCreateDeviceOrig, and s_fnOpenAdapter10_2.
Referenced by CWinSystemWin32DX::InitHooks(), and CWinSystemWin32DX::UninitHooks().
Variable Documentation
s_fnCreateDeviceOrig
PFND3D10DDI_CREATEDEVICE s_fnCreateDeviceOrig { nullptr } static
Referenced by HookCreateDevice(), and HookOpenAdapter10_2().
s_fnCreateResourceOrig
PFND3D10DDI_CREATERESOURCE s_fnCreateResourceOrig { nullptr } static
Referenced by HookCreateDevice(), and HookCreateResource().
s_fnOpenAdapter10_2
PFND3D10DDI_OPENADAPTER s_fnOpenAdapter10_2 { nullptr } static
Referenced by HookOpenAdapter10_2(), CWinSystemWin32DX::InitHooks(), and CWinSystemWin32DX::UninitHooks().