Kodi Documentation: Shaders::GL::ConvolutionFilterShader Class Reference
Shaders::GL::ConvolutionFilterShader Class Reference
#include <VideoFilterShaderGL.h>
Public Member Functions
ConvolutionFilterShader (ESCALINGMETHOD method, bool stretch, bool gammaCorrection, GLSLOutput *output=NULL)
~ConvolutionFilterShader () override
void OnCompiledAndLinked () override
bool OnEnabled () override
void OnDisabled () override
void Free ()
bool GetTextureFilter (GLint &filter) override
Public Member Functions inherited from Shaders::GL::BaseVideoFilterShader
BaseVideoFilterShader ()
~BaseVideoFilterShader () override
void SetSourceTexture (GLint ytex)
void SetWidth (int w)
void SetHeight (int h)
void SetNonLinStretch (float stretch)
void SetAlpha (GLfloat alpha)
GLint GetVertexLoc ()
GLint GetCoordLoc ()
void SetMatrices (const GLfloat *p, const GLfloat *m)
Public Member Functions inherited from Shaders::CGLSLShaderProgram
CGLSLShaderProgram ()
CGLSLShaderProgram (const std::string &vert, const std::string &frag)
~CGLSLShaderProgram () override
bool Enable () override
void Disable () override
bool CompileAndLink () override
Public Member Functions inherited from Shaders::CShaderProgram
CShaderProgram ()=default
virtual ~CShaderProgram ()
bool OK () const
CVertexShader * VertexShader ()
CPixelShader * PixelShader ()
virtual GLuint ProgramHandle ()
Protected Attributes
GLuint m_kernelTex1 = 0
GLint m_hKernTex
ESCALINGMETHOD m_method
bool m_floattex
GLint m_internalformat
GLSLOutput * m_glslOutput
Protected Attributes inherited from Shaders::GL::BaseVideoFilterShader
int m_width
int m_height
float m_stepX
float m_stepY
float m_stretch
GLfloat m_alpha
GLint m_sourceTexUnit = 0
const GLfloat * m_proj = nullptr
const GLfloat * m_model = nullptr
GLint m_hSourceTex = 0
GLint m_hStepXY = 0
GLint m_hStretch = -1
GLint m_hAlpha = -1
GLint m_hVertex = -1
GLint m_hCoord = -1
GLint m_hProj = -1
GLint m_hModel = -1
Protected Attributes inherited from Shaders::CGLSLShaderProgram
GLint m_lastProgram
bool m_validated = false
Protected Attributes inherited from Shaders::CShaderProgram
CVertexShader * m_pVP = nullptr
CPixelShader * m_pFP = nullptr
GLuint m_shaderProgram = 0
bool m_ok = false
Additional Inherited Members
Protected Member Functions inherited from Shaders::CGLSLShaderProgram
void Free ()
Constructor & Destructor Documentation
ConvolutionFilterShader()
ConvolutionFilterShader::ConvolutionFilterShader (ESCALINGMETHOD method, bool stretch, bool gammaCorrection, GLSLOutput * output = NULL)
References Shaders::CShader::AppendSource(), Shaders::GLSLOutput::GetDefines(), CServiceBroker::GetRenderSystem(), CRenderSystemBase::IsExtSupported(), Shaders::CShader::LoadSource(), CLog::Log(), LOGDEBUG, m_floattex, m_glslOutput, m_internalformat, m_method, Shaders::CShaderProgram::PixelShader(), VS_SCALINGMETHOD_CUBIC_0_075, VS_SCALINGMETHOD_CUBIC_0_1, VS_SCALINGMETHOD_CUBIC_B_SPLINE, VS_SCALINGMETHOD_CUBIC_CATMULL, VS_SCALINGMETHOD_CUBIC_MITCHELL, VS_SCALINGMETHOD_LANCZOS2, VS_SCALINGMETHOD_LANCZOS3, VS_SCALINGMETHOD_LANCZOS3_FAST, VS_SCALINGMETHOD_SPLINE36, and VS_SCALINGMETHOD_SPLINE36_FAST.
~ConvolutionFilterShader()
ConvolutionFilterShader::~ConvolutionFilterShader () override
References Free(), and m_glslOutput.
Member Function Documentation
Free()
void ConvolutionFilterShader::Free ()
References Shaders::GLSLOutput::Free(), Shaders::CGLSLShaderProgram::Free(), m_glslOutput, and m_kernelTex1.
Referenced by ~ConvolutionFilterShader().
GetTextureFilter()
bool Shaders::GL::ConvolutionFilterShader::GetTextureFilter (GLint & filter) inline override virtual
Reimplemented from Shaders::GL::BaseVideoFilterShader.
OnCompiledAndLinked()
void ConvolutionFilterShader::OnCompiledAndLinked () override virtual
Reimplemented from Shaders::CShaderProgram.
References data(), CConvolutionKernel::GetFloatPixels(), CConvolutionKernel::GetSize(), CConvolutionKernel::GetUint8Pixels(), CLog::Log(), LOGERROR, m_floattex, m_glslOutput, Shaders::GL::BaseVideoFilterShader::m_hAlpha, Shaders::GL::BaseVideoFilterShader::m_hCoord, m_hKernTex, Shaders::GL::BaseVideoFilterShader::m_hModel, Shaders::GL::BaseVideoFilterShader::m_hProj, Shaders::GL::BaseVideoFilterShader::m_hSourceTex, Shaders::GL::BaseVideoFilterShader::m_hStepXY, Shaders::GL::BaseVideoFilterShader::m_hStretch, Shaders::GL::BaseVideoFilterShader::m_hVertex, m_internalformat, m_kernelTex1, m_method, Shaders::GLSLOutput::OnCompiledAndLinked(), Shaders::CShaderProgram::ProgramHandle(), TEXTARGET, and VerifyGLState.
OnDisabled()
void ConvolutionFilterShader::OnDisabled () override virtual
Reimplemented from Shaders::CShaderProgram.
References m_glslOutput, and Shaders::GLSLOutput::OnDisabled().
OnEnabled()
bool ConvolutionFilterShader::OnEnabled () override virtual
Reimplemented from Shaders::CShaderProgram.
References Shaders::GL::BaseVideoFilterShader::m_alpha, m_glslOutput, Shaders::GL::BaseVideoFilterShader::m_hAlpha, m_hKernTex, Shaders::GL::BaseVideoFilterShader::m_hModel, Shaders::GL::BaseVideoFilterShader::m_hProj, Shaders::GL::BaseVideoFilterShader::m_hSourceTex, Shaders::GL::BaseVideoFilterShader::m_hStepXY, Shaders::GL::BaseVideoFilterShader::m_hStretch, m_kernelTex1, Shaders::GL::BaseVideoFilterShader::m_model, Shaders::GL::BaseVideoFilterShader::m_proj, Shaders::GL::BaseVideoFilterShader::m_sourceTexUnit, Shaders::GL::BaseVideoFilterShader::m_stepX, Shaders::GL::BaseVideoFilterShader::m_stepY, Shaders::GL::BaseVideoFilterShader::m_stretch, Shaders::GLSLOutput::OnEnabled(), TEXTARGET, and VerifyGLState.
Member Data Documentation
m_floattex
bool Shaders::GL::ConvolutionFilterShader::m_floattex protected
Referenced by ConvolutionFilterShader(), and OnCompiledAndLinked().
m_glslOutput
GLSLOutput* Shaders::GL::ConvolutionFilterShader::m_glslOutput protected
Referenced by ConvolutionFilterShader(), Free(), OnCompiledAndLinked(), OnDisabled(), OnEnabled(), and ~ConvolutionFilterShader().
m_hKernTex
GLint Shaders::GL::ConvolutionFilterShader::m_hKernTex protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_internalformat
GLint Shaders::GL::ConvolutionFilterShader::m_internalformat protected
Referenced by ConvolutionFilterShader(), and OnCompiledAndLinked().
m_kernelTex1
GLuint Shaders::GL::ConvolutionFilterShader::m_kernelTex1 = 0 protected
Referenced by Free(), OnCompiledAndLinked(), and OnEnabled().
m_method
ESCALINGMETHOD Shaders::GL::ConvolutionFilterShader::m_method protected
Referenced by ConvolutionFilterShader(), and OnCompiledAndLinked().
The documentation for this class was generated from the following files:
VideoFilterShaderGL.h
VideoFilterShaderGL.cpp