Kodi Documentation: TestHelpers.h File Reference
TestHelpers.h File Reference
#include "threads/Thread.h"
#include <memory>
#include <mutex>
#include <gtest/gtest.h>
Classes
class AtomicGuard
class thread
Functions
template<class E >
static bool waitForWaiters (E &event, int numWaiters, std::chrono::milliseconds duration)
static bool waitForThread (std::atomic< long > &mutex, int numWaiters, std::chrono::milliseconds duration)
Function Documentation
waitForThread()
static bool waitForThread (std::atomic< long > & mutex, int numWaiters, std::chrono::milliseconds duration) inline static
References mutex.
Referenced by RunMassEventTest(), TEST(), TEST(), and TEST().
waitForWaiters()
template<class E > static bool waitForWaiters (E & event, int numWaiters, std::chrono::milliseconds duration) inline static
Referenced by RunMassEventTest(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().