Kodi Documentation: KODI::RETRO::CGUIGameMessenger Class Reference
KODI::RETRO::CGUIGameMessenger Class Reference
Class to send messages to the GUI, if a GUI is present.
#include <GUIGameMessenger.h>
Public Member Functions
CGUIGameMessenger (CRPProcessInfo &processInfo)
void RefreshSavestates (const std::string &savestatePath="", ISavestate *savestate=nullptr)
Refresh savestate GUI elements being displayed.
Private Attributes
CGUIComponent *const m_guiComponent
Detailed Description
Class to send messages to the GUI, if a GUI is present.
Constructor & Destructor Documentation
CGUIGameMessenger()
CGUIGameMessenger::CGUIGameMessenger (CRPProcessInfo & processInfo)
Member Function Documentation
RefreshSavestates()
void CGUIGameMessenger::RefreshSavestates (const std::string & savestatePath = "", ISavestate * savestate = nullptr)
Refresh savestate GUI elements being displayed.
Parameters
savestatePath The savestate to refresh, or empty to refresh all savestates
savestate Optional savestate info to send with the message
References KODI::RETRO::CSavestateDatabase::GetSavestateItem(), CGUIComponent::GetWindowManager(), GUI_MSG_REFRESH_THUMBS, m_guiComponent, savestate, CGUIMessage::SetItem(), CGUIMessage::SetStringParam(), and WINDOW_DIALOG_IN_GAME_SAVES.
Referenced by KODI::RETRO::CReversiblePlayback::CommitSavestate().
Member Data Documentation
m_guiComponent
CGUIComponent* const KODI::RETRO::CGUIGameMessenger::m_guiComponent private
Referenced by RefreshSavestates().
The documentation for this class was generated from the following files:
GUIGameMessenger.h
GUIGameMessenger.cpp