Kodi Documentation: IListProvider Class Reference
IListProvider Class Reference abstract
Listproviders
An interface for providing lists to UI containers.
#include <IListProvider.h>
Public Member Functions
IListProvider (int parentID)
IListProvider (const IListProvider &other)=default
virtual ~IListProvider ()=default
virtual std::unique_ptr< IListProvider > Clone ()=0
Create an instance of the derived class. Allows for polymorphic copies.
virtual bool Update (bool forceRefresh)=0
Update the list content.
virtual void Fetch (std::vector< std::shared_ptr< CGUIListItem > > &items)=0
Fetch the current list of items.
virtual bool IsUpdating () const
Check whether the list provider is updating content.
virtual void Reset ()
Reset the current list of items. Derived classes may choose to ignore this.
virtual void FreeResources (bool immediately)
Free all GUI resources allocated by the items.
virtual bool OnClick (const std::shared_ptr< CGUIListItem > &item)=0
Click event on an item.
virtual bool OnPlay (const std::shared_ptr< CGUIListItem > &item)
Play event on an item.
virtual bool OnInfo (const std::shared_ptr< CGUIListItem > &item)=0
Open the info dialog for an item provided by this IListProvider.
virtual bool OnContextMenu (const std::shared_ptr< CGUIListItem > &item)=0
Open the context menu for an item provided by this IListProvider.
virtual void SetDefaultItem (int item, bool always)
Set the default item to focus. For backwards compatibility.
virtual int GetDefaultItem () const
The default item to focus.
virtual bool AlwaysFocusDefaultItem () const
Whether to always focus the default item.
Static Public Member Functions
static std::unique_ptr< IListProvider > Create (const TiXmlNode *parent, int parentID)
Factory to create list providers.
static std::unique_ptr< IListProvider > CreateSingle (const TiXmlNode *content, int parentID)
Factory to create list providers. Cannot create a multi-provider.
Protected Attributes
int m_parentID
Detailed Description
An interface for providing lists to UI containers.
Constructor & Destructor Documentation
IListProvider() [1/2]
IListProvider::IListProvider (int parentID) inline explicit
IListProvider() [2/2]
IListProvider::IListProvider (const IListProvider & other) explicit default
~IListProvider()
virtual IListProvider::~IListProvider () virtual default
Member Function Documentation
AlwaysFocusDefaultItem()
virtual bool IListProvider::AlwaysFocusDefaultItem () const inline virtual
Whether to always focus the default item.
Returns
true if the default item should always be the one to receive focus.
See also
GetDefaultItem, SetDefaultItem
Reimplemented in KODI::GAME::CGUIGameControllerProvider, and CStaticListProvider.
Clone()
virtual std::unique_ptr< IListProvider > IListProvider::Clone () pure virtual
Create an instance of the derived class. Allows for polymorphic copies.
Implemented in KODI::GAME::CGUIGameControllerProvider, CDirectoryProvider, CMultiProvider, and CStaticListProvider.
Referenced by CMultiProvider::CMultiProvider().
Create()
std::unique_ptr< IListProvider > IListProvider::Create (const TiXmlNode * parent, int parentID) static
Factory to create list providers.
Parameters
parent a parent TiXmlNode for the container.
parentID id of parent window for context.
Returns
the list provider, empty pointer if none.
References CreateSingle(), node, and root.
Referenced by CGUIBaseContainer::LoadListProvider().
CreateSingle()
std::unique_ptr< IListProvider > IListProvider::CreateSingle (const TiXmlNode * content, int parentID) static
Factory to create list providers. Cannot create a multi-provider.
Parameters
content the TiXmlNode for the content to create.
parentID id of parent window for context.
Returns
the list provider, empty pointer if none.
Referenced by CMultiProvider::CMultiProvider(), and Create().
Fetch()
virtual void IListProvider::Fetch (std::vector< std::shared_ptr< CGUIListItem > > & items) pure virtual
Fetch the current list of items.
Parameters
items [out] the list to be filled.
Implemented in KODI::GAME::CGUIGameControllerProvider, CDirectoryProvider, CMultiProvider, and CStaticListProvider.
FreeResources()
virtual void IListProvider::FreeResources (bool immediately) inline virtual
Free all GUI resources allocated by the items.
Parameters
immediately true to free resources immediately, free resources async later otherwise.
Reimplemented in CDirectoryProvider.
GetDefaultItem()
virtual int IListProvider::GetDefaultItem () const inline virtual
The default item to focus.
Returns
the item to focus by default. -1 for none.
See also
SetDefaultItem, AlwaysFocusDefaultItem
Reimplemented in KODI::GAME::CGUIGameControllerProvider, and CStaticListProvider.
IsUpdating()
virtual bool IListProvider::IsUpdating () const inline virtual
Check whether the list provider is updating content.
Returns
true if in the processing of updating, false otherwise.
Reimplemented in CDirectoryProvider, and CMultiProvider.
OnClick()
virtual bool IListProvider::OnClick (const std::shared_ptr< CGUIListItem > & item) pure virtual
Click event on an item.
Parameters
item the item that was clicked.
Returns
true if the click was handled, false otherwise.
Implemented in KODI::GAME::CGUIGameControllerProvider, CDirectoryProvider, CMultiProvider, and CStaticListProvider.
OnContextMenu()
virtual bool IListProvider::OnContextMenu (const std::shared_ptr< CGUIListItem > & item) pure virtual
Open the context menu for an item provided by this IListProvider.
Parameters
item the item that was clicked.
Returns
true if the click was handled, false otherwise.
Implemented in KODI::GAME::CGUIGameControllerProvider, CDirectoryProvider, CMultiProvider, and CStaticListProvider.
OnInfo()
virtual bool IListProvider::OnInfo (const std::shared_ptr< CGUIListItem > & item) pure virtual
Open the info dialog for an item provided by this IListProvider.
Parameters
item the item that was clicked.
Returns
true if the dialog was shown, false otherwise.
Implemented in KODI::GAME::CGUIGameControllerProvider, CDirectoryProvider, CMultiProvider, and CStaticListProvider.
OnPlay()
virtual bool IListProvider::OnPlay (const std::shared_ptr< CGUIListItem > & item) inline virtual
Play event on an item.
Parameters
item the item to play.
Returns
true if the event was handled, false otherwise.
Reimplemented in CDirectoryProvider.
Reset()
virtual void IListProvider::Reset () inline virtual
Reset the current list of items. Derived classes may choose to ignore this.
Reimplemented in CDirectoryProvider, and CMultiProvider.
SetDefaultItem()
virtual void IListProvider::SetDefaultItem (int item, bool always) inline virtual
Set the default item to focus. For backwards compatibility.
Parameters
item the item to focus.
always whether this item should always be used on first focus.
See also
GetDefaultItem, AlwaysFocusDefaultItem
Reimplemented in KODI::GAME::CGUIGameControllerProvider, and CStaticListProvider.
Update()
virtual bool IListProvider::Update (bool forceRefresh) pure virtual
Update the list content.
Returns
true if the content has changed, false otherwise.
Implemented in KODI::GAME::CGUIGameControllerProvider, CDirectoryProvider, CMultiProvider, and CStaticListProvider.
Member Data Documentation
m_parentID
int IListProvider::m_parentID protected
Referenced by CDirectoryProvider::GetTarget(), CStaticListProvider::OnClick(), CDirectoryProvider::Update(), CStaticListProvider::Update(), CDirectoryProvider::UpdateBrowse(), CDirectoryProvider::UpdateLimit(), CDirectoryProvider::UpdateSort(), and CDirectoryProvider::UpdateURL().
The documentation for this class was generated from the following files:
IListProvider.h
IListProvider.cpp