Kodi Documentation: CSubtitlesAdapter Class Reference
CSubtitlesAdapter Class Reference
#include <SubtitlesAdapter.h>
Public Member Functions
CSubtitlesAdapter ()
virtual ~CSubtitlesAdapter ()
bool Initialize ()
Initialize the subtitles adapter.
int AddSubtitle (std::string &text, double startTime, double stopTime)
Add a subtitle.
int AddSubtitle (std::string &text, double startTime, double stopTime, KODI::SUBTITLES::STYLE::subtitleOpts *opts)
Add a subtitle with supplementary options.
void AppendToSubtitle (int subtitleId, const char *text)
Append text to the specified subtitle ID.
int DeleteSubtitles (int nSubtitles, int threshold)
Delete old subtitles only if the total number of subtitles added reaches the threshold.
void ChangeSubtitleStopTime (int subtitleId, double stopTime)
Change the stop time of a subtitle ID with the specified time.
void FlushSubtitles ()
std::shared_ptr< CDVDOverlay > CreateOverlay ()
Protected Member Functions
virtual void PostProcess (std::string &text)
Post processing of subtitle, will be called before processing AddSubtitle method.
Private Attributes
std::shared_ptr< CDVDSubtitlesLibass > m_libass
Constructor & Destructor Documentation
CSubtitlesAdapter()
CSubtitlesAdapter::CSubtitlesAdapter ()
References m_libass.
~CSubtitlesAdapter()
CSubtitlesAdapter::~CSubtitlesAdapter () virtual
Member Function Documentation
AddSubtitle() [1/2]
int CSubtitlesAdapter::AddSubtitle (std::string & text, double startTime, double stopTime)
Add a subtitle.
Parameters
text The subtitle text
startTime The PTS start time of the subtitle
stopTime The PTS stop time of the subtitle
Returns
Return the subtitle ID, otherwise NO_SUBTITLE_ID if fails
References AddSubtitle(), and text.
Referenced by AddSubtitle(), CDVDOverlayCodecCCText::Decode(), CDVDOverlayCodecText::Decode(), CDVDOverlayCodecTX3G::Decode(), COverlayCodecWebVTT::Decode(), CDVDSubtitleParserMicroDVD::Open(), CDVDSubtitleParserMPL2::Open(), CDVDSubtitleParserSami::Open(), CDVDSubtitleParserSubrip::Open(), CDVDSubtitleParserVplayer::Open(), CSubtitleParserWebVTT::Open(), CDebugRenderer::SetInfo(), and CDebugRenderer::SetInfo().
AddSubtitle() [2/2]
int CSubtitlesAdapter::AddSubtitle (std::string & text, double startTime, double stopTime, KODI::SUBTITLES::STYLE::subtitleOpts * opts)
Add a subtitle with supplementary options.
Parameters
text The subtitle text
startTime The PTS start time of the subtitle
stopTime The PTS stop time of the subtitle
opts Subtitle options
Returns
Return the subtitle ID, otherwise NO_SUBTITLE_ID if fails
References ASS_NO_ID, m_libass, NO_SUBTITLE_ID, PostProcess(), and text.
AppendToSubtitle()
void CSubtitlesAdapter::AppendToSubtitle (int subtitleId, const char * text)
Append text to the specified subtitle ID.
Parameters
subtitleId The subtitle ID
text The text to append
References ASS_NO_ID, m_libass, NO_SUBTITLE_ID, and text.
Referenced by CDVDSubtitleParserSami::Open().
ChangeSubtitleStopTime()
void CSubtitlesAdapter::ChangeSubtitleStopTime (int subtitleId, double stopTime)
Change the stop time of a subtitle ID with the specified time.
Parameters
subtitleId The subtitle ID
stopTime The PTS stop time
References ASS_NO_ID, m_libass, and NO_SUBTITLE_ID.
Referenced by CDVDOverlayCodecCCText::Decode(), CDVDOverlayCodecText::Decode(), COverlayCodecWebVTT::Decode(), CDVDSubtitleParserSami::Open(), and CDVDSubtitleParserVplayer::Open().
CreateOverlay()
std::shared_ptr< CDVDOverlay > CSubtitlesAdapter::CreateOverlay ()
References DVD_NOPTS_VALUE, and m_libass.
Referenced by CDVDOverlayCodecCCText::GetOverlay(), CDVDOverlayCodecText::GetOverlay(), CDVDOverlayCodecTX3G::GetOverlay(), COverlayCodecWebVTT::GetOverlay(), CDebugRenderer::Initialize(), CDVDSubtitleParserMicroDVD::Open(), CDVDSubtitleParserMPL2::Open(), CDVDSubtitleParserSami::Open(), CDVDSubtitleParserSubrip::Open(), CDVDSubtitleParserVplayer::Open(), and CSubtitleParserWebVTT::Open().
DeleteSubtitles()
int CSubtitlesAdapter::DeleteSubtitles (int nSubtitles, int threshold)
Delete old subtitles only if the total number of subtitles added reaches the threshold.
Parameters
nSubtitles The number of subtitles to delete
threshold Start deleting only when the number of subtitles is reached
Returns
The updated ID of the last subtitle, otherwise NO_SUBTITLE_ID if error or no subtitles
References ASS_NO_ID, m_libass, and NO_SUBTITLE_ID.
Referenced by CDVDOverlayCodecCCText::Decode().
FlushSubtitles()
void CSubtitlesAdapter::FlushSubtitles ()
References m_libass.
Referenced by CDebugRenderer::Flush(), CDVDOverlayCodecCCText::Flush(), CDVDOverlayCodecText::Flush(), CDVDOverlayCodecTX3G::Flush(), COverlayCodecWebVTT::Flush(), CDebugRenderer::SetInfo(), and CDebugRenderer::SetInfo().
Initialize()
bool CSubtitlesAdapter::Initialize ()
Initialize the subtitles adapter.
Returns
True if success, false if error
References ADAPTED, and m_libass.
Referenced by CDebugRenderer::Initialize(), CDVDSubtitleParserMicroDVD::Open(), CDVDSubtitleParserMPL2::Open(), CDVDSubtitleParserSami::Open(), CDVDSubtitleParserSubrip::Open(), CDVDSubtitleParserVplayer::Open(), CSubtitleParserWebVTT::Open(), CDVDOverlayCodecCCText::Open(), CDVDOverlayCodecText::Open(), CDVDOverlayCodecTX3G::Open(), and COverlayCodecWebVTT::Open().
PostProcess()
virtual void CSubtitlesAdapter::PostProcess (std::string & text) inline protected virtual
Post processing of subtitle, will be called before processing AddSubtitle method.
Parameters
text The subtitle text
Reimplemented in CDVDOverlayCodecCCText, CDVDOverlayCodecText, and CDVDOverlayCodecTX3G.
Referenced by AddSubtitle(), CDVDOverlayCodecCCText::PostProcess(), CDVDOverlayCodecText::PostProcess(), and CDVDOverlayCodecTX3G::PostProcess().
Member Data Documentation
m_libass
std::shared_ptr<CDVDSubtitlesLibass> CSubtitlesAdapter::m_libass private
Referenced by AddSubtitle(), AppendToSubtitle(), ChangeSubtitleStopTime(), CreateOverlay(), CSubtitlesAdapter(), DeleteSubtitles(), FlushSubtitles(), and Initialize().
The documentation for this class was generated from the following files:
SubtitlesAdapter.h
SubtitlesAdapter.cpp