Kodi Documentation: AddonDatabaseTest Class Reference
AddonDatabaseTest Class Reference
Protected Member Functions
void SetUp () override
void CreateAddon (std::vector< AddonInfoPtr > &addons, std::string id, const std::string &version)
void TearDown () override
Protected Attributes
DatabaseSettings settings
CAddonDatabase database
Member Function Documentation
CreateAddon()
void AddonDatabaseTest::CreateAddon (std::vector< AddonInfoPtr > & addons, std::string id, const std::string & version) inline protected
References addons, ADDON::CAddonInfoBuilderFromDB::get(), ADDON::CAddonInfoBuilderFromDB::SetId(), and ADDON::CAddonInfoBuilderFromDB::SetVersion().
Referenced by SetUp().
SetUp()
void AddonDatabaseTest::SetUp () inline override protected
References addons, CDatabase::Connect(), CreateAddon(), database, DatabaseSettings::host, DatabaseSettings::name, ADDON::CAddonDatabase::SetRepoUpdateData(), settings, ADDON::CAddonDatabase::SyncInstalled(), CSpecialProtocol::TranslatePath(), DatabaseSettings::type, and ADDON::CAddonDatabase::UpdateRepositoryContent().
TearDown()
void AddonDatabaseTest::TearDown () inline override protected
References CDatabase::Close(), and database.
Member Data Documentation
database
CAddonDatabase AddonDatabaseTest::database protected
Referenced by SetUp(), and TearDown().
settings
DatabaseSettings AddonDatabaseTest::settings protected
Referenced by SetUp().
The documentation for this class was generated from the following file:
TestAddonDatabase.cpp