Kodi Documentation: PVR::CPVRGUITimerInfo Class Reference
PVR::CPVRGUITimerInfo Class Reference abstract
#include <PVRGUITimerInfo.h>
Public Member Functions
CPVRGUITimerInfo ()
virtual ~CPVRGUITimerInfo ()=default
void ResetProperties ()
void UpdateTimersCache ()
void UpdateTimersToggle ()
void UpdateNextTimer ()
const std::string & GetActiveTimerTitle () const
const std::string & GetActiveTimerChannelName () const
const std::string & GetActiveTimerChannelIcon () const
const std::string & GetActiveTimerDateTime () const
const std::string & GetNextTimerTitle () const
const std::string & GetNextTimerChannelName () const
const std::string & GetNextTimerChannelIcon () const
const std::string & GetNextTimerDateTime () const
const std::string & GetNextTimer () const
bool HasTimers () const
bool HasRecordingTimers () const
bool HasNonRecordingTimers () const
Private Member Functions
bool TimerInfoToggle ()
virtual int AmountActiveTimers ()=0
virtual int AmountActiveRecordings ()=0
virtual std::vector< std::shared_ptr< CPVRTimerInfoTag > > GetActiveRecordings ()=0
virtual std::shared_ptr< CPVRTimerInfoTag > GetNextActiveTimer ()=0
Private Attributes
unsigned int m_iTimerAmount
unsigned int m_iRecordingTimerAmount
std::string m_strActiveTimerTitle
std::string m_strActiveTimerChannelName
std::string m_strActiveTimerChannelIcon
std::string m_strActiveTimerTime
std::string m_strNextRecordingTitle
std::string m_strNextRecordingChannelName
std::string m_strNextRecordingChannelIcon
std::string m_strNextRecordingTime
std::string m_strNextTimerInfo
std::chrono::time_point< std::chrono::steady_clock > m_iTimerInfoToggleStart
unsigned int m_iTimerInfoToggleCurrent
CCriticalSection m_critSection
Constructor & Destructor Documentation
CPVRGUITimerInfo()
CPVRGUITimerInfo::CPVRGUITimerInfo ()
References ResetProperties().
~CPVRGUITimerInfo()
virtual PVR::CPVRGUITimerInfo::~CPVRGUITimerInfo () virtual default
Member Function Documentation
AmountActiveRecordings()
virtual int PVR::CPVRGUITimerInfo::AmountActiveRecordings () private pure virtual
Implemented in PVR::CPVRGUIAnyTimerInfo, PVR::CPVRGUITVTimerInfo, and PVR::CPVRGUIRadioTimerInfo.
Referenced by UpdateTimersCache().
AmountActiveTimers()
virtual int PVR::CPVRGUITimerInfo::AmountActiveTimers () private pure virtual
Implemented in PVR::CPVRGUIAnyTimerInfo, PVR::CPVRGUITVTimerInfo, and PVR::CPVRGUIRadioTimerInfo.
Referenced by UpdateTimersCache().
GetActiveRecordings()
virtual std::vector< std::shared_ptr< CPVRTimerInfoTag > > PVR::CPVRGUITimerInfo::GetActiveRecordings () private pure virtual
Implemented in PVR::CPVRGUIAnyTimerInfo, PVR::CPVRGUITVTimerInfo, and PVR::CPVRGUIRadioTimerInfo.
Referenced by UpdateTimersToggle().
GetActiveTimerChannelIcon()
const std::string & CPVRGUITimerInfo::GetActiveTimerChannelIcon () const
References m_critSection, and m_strActiveTimerChannelIcon.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetActiveTimerChannelName()
const std::string & CPVRGUITimerInfo::GetActiveTimerChannelName () const
References m_critSection, and m_strActiveTimerChannelName.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetActiveTimerDateTime()
const std::string & CPVRGUITimerInfo::GetActiveTimerDateTime () const
References m_critSection, and m_strActiveTimerTime.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetActiveTimerTitle()
const std::string & CPVRGUITimerInfo::GetActiveTimerTitle () const
References m_critSection, and m_strActiveTimerTitle.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetNextActiveTimer()
virtual std::shared_ptr< CPVRTimerInfoTag > PVR::CPVRGUITimerInfo::GetNextActiveTimer () private pure virtual
Implemented in PVR::CPVRGUIAnyTimerInfo, PVR::CPVRGUITVTimerInfo, and PVR::CPVRGUIRadioTimerInfo.
Referenced by UpdateNextTimer().
GetNextTimer()
const std::string & CPVRGUITimerInfo::GetNextTimer () const
References m_critSection, and m_strNextTimerInfo.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetNextTimerChannelIcon()
const std::string & CPVRGUITimerInfo::GetNextTimerChannelIcon () const
References m_critSection, and m_strNextRecordingChannelIcon.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetNextTimerChannelName()
const std::string & CPVRGUITimerInfo::GetNextTimerChannelName () const
References m_critSection, and m_strNextRecordingChannelName.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetNextTimerDateTime()
const std::string & CPVRGUITimerInfo::GetNextTimerDateTime () const
References m_critSection, and m_strNextRecordingTime.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
GetNextTimerTitle()
const std::string & CPVRGUITimerInfo::GetNextTimerTitle () const
References m_critSection, and m_strNextRecordingTitle.
Referenced by PVR::CPVRGUIInfo::GetPVRLabel().
HasNonRecordingTimers()
bool PVR::CPVRGUITimerInfo::HasNonRecordingTimers () const inline
References m_iRecordingTimerAmount, and m_iTimerAmount.
Referenced by PVR::CPVRGUIInfo::GetPVRBool().
HasRecordingTimers()
bool PVR::CPVRGUITimerInfo::HasRecordingTimers () const inline
References m_iRecordingTimerAmount.
Referenced by PVR::CPVRGUIInfo::GetPVRBool().
HasTimers()
bool PVR::CPVRGUITimerInfo::HasTimers () const inline
References m_iTimerAmount.
Referenced by PVR::CPVRGUIInfo::GetPVRBool().
ResetProperties()
void CPVRGUITimerInfo::ResetProperties ()
References m_critSection, m_iRecordingTimerAmount, m_iTimerAmount, m_iTimerInfoToggleCurrent, m_iTimerInfoToggleStart, m_strActiveTimerChannelIcon, m_strActiveTimerChannelName, m_strActiveTimerTime, m_strActiveTimerTitle, m_strNextRecordingChannelIcon, m_strNextRecordingChannelName, m_strNextRecordingTime, m_strNextRecordingTitle, and m_strNextTimerInfo.
Referenced by CPVRGUITimerInfo(), and PVR::CPVRGUIInfo::ResetProperties().
TimerInfoToggle()
bool CPVRGUITimerInfo::TimerInfoToggle () private
References CServiceBroker::GetSettingsComponent(), m_critSection, m_iRecordingTimerAmount, m_iTimerAmount, m_iTimerInfoToggleCurrent, and m_iTimerInfoToggleStart.
Referenced by UpdateTimersToggle().
UpdateNextTimer()
void CPVRGUITimerInfo::UpdateNextTimer ()
References g_localizeStrings, CLocalizeStrings::Get(), GetNextActiveTimer(), m_critSection, m_strNextRecordingChannelIcon, m_strNextRecordingChannelName, m_strNextRecordingTime, m_strNextRecordingTitle, and m_strNextTimerInfo.
Referenced by PVR::CPVRGUIInfo::UpdateNextTimer().
UpdateTimersCache()
void CPVRGUITimerInfo::UpdateTimersCache ()
References AmountActiveRecordings(), AmountActiveTimers(), m_critSection, m_iRecordingTimerAmount, m_iTimerAmount, m_iTimerInfoToggleStart, and UpdateTimersToggle().
Referenced by PVR::CPVRGUIInfo::UpdateTimersCache().
UpdateTimersToggle()
void CPVRGUITimerInfo::UpdateTimersToggle ()
References GetActiveRecordings(), m_critSection, m_iRecordingTimerAmount, m_iTimerInfoToggleCurrent, m_strActiveTimerChannelIcon, m_strActiveTimerChannelName, m_strActiveTimerTime, m_strActiveTimerTitle, and TimerInfoToggle().
Referenced by UpdateTimersCache(), and PVR::CPVRGUIInfo::UpdateTimersToggle().
Member Data Documentation
m_critSection
CCriticalSection PVR::CPVRGUITimerInfo::m_critSection mutable private
Referenced by GetActiveTimerChannelIcon(), GetActiveTimerChannelName(), GetActiveTimerDateTime(), GetActiveTimerTitle(), GetNextTimer(), GetNextTimerChannelIcon(), GetNextTimerChannelName(), GetNextTimerDateTime(), GetNextTimerTitle(), ResetProperties(), TimerInfoToggle(), UpdateNextTimer(), UpdateTimersCache(), and UpdateTimersToggle().
m_iRecordingTimerAmount
unsigned int PVR::CPVRGUITimerInfo::m_iRecordingTimerAmount private
Referenced by HasNonRecordingTimers(), HasRecordingTimers(), ResetProperties(), TimerInfoToggle(), UpdateTimersCache(), and UpdateTimersToggle().
m_iTimerAmount
unsigned int PVR::CPVRGUITimerInfo::m_iTimerAmount private
Referenced by HasNonRecordingTimers(), HasTimers(), ResetProperties(), TimerInfoToggle(), and UpdateTimersCache().
m_iTimerInfoToggleCurrent
unsigned int PVR::CPVRGUITimerInfo::m_iTimerInfoToggleCurrent private
Referenced by ResetProperties(), TimerInfoToggle(), and UpdateTimersToggle().
m_iTimerInfoToggleStart
std::chrono::time_point<std::chrono::steady_clock> PVR::CPVRGUITimerInfo::m_iTimerInfoToggleStart private
Referenced by ResetProperties(), TimerInfoToggle(), and UpdateTimersCache().
m_strActiveTimerChannelIcon
std::string PVR::CPVRGUITimerInfo::m_strActiveTimerChannelIcon private
Referenced by GetActiveTimerChannelIcon(), ResetProperties(), and UpdateTimersToggle().
m_strActiveTimerChannelName
std::string PVR::CPVRGUITimerInfo::m_strActiveTimerChannelName private
Referenced by GetActiveTimerChannelName(), ResetProperties(), and UpdateTimersToggle().
m_strActiveTimerTime
std::string PVR::CPVRGUITimerInfo::m_strActiveTimerTime private
Referenced by GetActiveTimerDateTime(), ResetProperties(), and UpdateTimersToggle().
m_strActiveTimerTitle
std::string PVR::CPVRGUITimerInfo::m_strActiveTimerTitle private
Referenced by GetActiveTimerTitle(), ResetProperties(), and UpdateTimersToggle().
m_strNextRecordingChannelIcon
std::string PVR::CPVRGUITimerInfo::m_strNextRecordingChannelIcon private
Referenced by GetNextTimerChannelIcon(), ResetProperties(), and UpdateNextTimer().
m_strNextRecordingChannelName
std::string PVR::CPVRGUITimerInfo::m_strNextRecordingChannelName private
Referenced by GetNextTimerChannelName(), ResetProperties(), and UpdateNextTimer().
m_strNextRecordingTime
std::string PVR::CPVRGUITimerInfo::m_strNextRecordingTime private
Referenced by GetNextTimerDateTime(), ResetProperties(), and UpdateNextTimer().
m_strNextRecordingTitle
std::string PVR::CPVRGUITimerInfo::m_strNextRecordingTitle private
Referenced by GetNextTimerTitle(), ResetProperties(), and UpdateNextTimer().
m_strNextTimerInfo
std::string PVR::CPVRGUITimerInfo::m_strNextTimerInfo private
Referenced by GetNextTimer(), ResetProperties(), and UpdateNextTimer().
The documentation for this class was generated from the following files:
PVRGUITimerInfo.h
PVRGUITimerInfo.cpp