Kodi Documentation: KODI::JOYSTICK::CDriverPrimitive Class Reference
KODI::JOYSTICK::CDriverPrimitive Class Reference
Input » Joystick
Basic driver element associated with input events.
#include <DriverPrimitive.h>
Public Member Functions
CDriverPrimitive (void)
Construct an invalid driver primitive.
CDriverPrimitive (PRIMITIVE_TYPE type, unsigned int index)
Construct a driver primitive representing a button or motor.
CDriverPrimitive (unsigned int hatIndex, HAT_DIRECTION direction)
Construct a driver primitive representing one of the four direction arrows on a dpad.
CDriverPrimitive (unsigned int axisIndex, int center, SEMIAXIS_DIRECTION direction, unsigned int range)
Construct a driver primitive representing the positive or negative half of an axis.
CDriverPrimitive (KEYBOARD::XBMCKey keycode)
Construct a driver primitive representing a key on a keyboard.
CDriverPrimitive (MOUSE::BUTTON_ID index)
Construct a driver primitive representing a mouse button.
CDriverPrimitive (RELATIVE_POINTER_DIRECTION direction)
Construct a driver primitive representing a relative pointer.
bool operator== (const CDriverPrimitive &rhs) const
bool operator< (const CDriverPrimitive &rhs) const
bool operator!= (const CDriverPrimitive &rhs) const
bool operator> (const CDriverPrimitive &rhs) const
bool operator<= (const CDriverPrimitive &rhs) const
bool operator>= (const CDriverPrimitive &rhs) const
PRIMITIVE_TYPE Type (void) const
The type of driver primitive.
unsigned int Index (void) const
The index used by the joystick driver.
HAT_DIRECTION HatDirection (void) const
The direction arrow (valid for hat directions)
int Center () const
The location of the zero point of the semiaxis.
SEMIAXIS_DIRECTION SemiAxisDirection (void) const
The semiaxis direction (valid for semiaxes)
unsigned int Range () const
The distance between the center and the farthest valid value (valid for semiaxes)
KEYBOARD::XBMCKey Keycode () const
The keyboard symbol (valid for keys)
MOUSE::BUTTON_ID MouseButton () const
The mouse button ID (valid for mouse buttons)
RELATIVE_POINTER_DIRECTION PointerDirection () const
The relative pointer direction (valid for relative pointers)
bool IsValid (void) const
Test if an driver primitive is valid.
std::string ToString () const
Convert primitive to a string suitable for logging.
Private Attributes
PRIMITIVE_TYPE m_type = PRIMITIVE_TYPE::UNKNOWN
unsigned int m_driverIndex = 0
HAT_DIRECTION m_hatDirection = HAT_DIRECTION::NONE
int m_center = 0
SEMIAXIS_DIRECTION m_semiAxisDirection = SEMIAXIS_DIRECTION::ZERO
unsigned int m_range = 1
KEYBOARD::XBMCKey m_keycode = KEYBOARD::XBMCKey::XBMCK_UNKNOWN
RELATIVE_POINTER_DIRECTION m_pointerDirection = RELATIVE_POINTER_DIRECTION::NONE
Detailed Description
Basic driver element associated with input events.
Driver input (bools, floats and enums) is split into primitives that better map to the physical features on a joystick.
A bool obviously only maps to a single feature, so it is a driver primitive. Here, these are called "buttons".
A hat enum encodes the state of the four hat directions. Each direction can map to a different feature, so a hat enum consists of four driver primitives called "hat directions".
A float is a little trickier. Trivially, it can map to an analog stick or trigger. However, DirectInput combines two triggers onto a single axis. Therefore, the axis is split into two primitives called "semiaxes".
The type determines the fields in use:
Button:
driver index
Hat direction:
driver index
hat direction (up/right/down/left)
Semiaxis:
driver index
center (-1, 0 or 1)
semiaxis direction (positive/negative)
range (1 or 2)
Motor:
driver index
Key:
keycode
Mouse button:
driver index
Relative pointer:
pointer direction
For more info, see "Chapter 2. Joystick drivers" in the documentation thread: http://forum.kodi.tv/showthread.php?tid=257764
Constructor & Destructor Documentation
CDriverPrimitive() [1/7]
CDriverPrimitive::CDriverPrimitive (void) default
Construct an invalid driver primitive.
CDriverPrimitive() [2/7]
CDriverPrimitive::CDriverPrimitive (PRIMITIVE_TYPE type, unsigned int index)
Construct a driver primitive representing a button or motor.
CDriverPrimitive() [3/7]
CDriverPrimitive::CDriverPrimitive (unsigned int hatIndex, HAT_DIRECTION direction)
Construct a driver primitive representing one of the four direction arrows on a dpad.
CDriverPrimitive() [4/7]
CDriverPrimitive::CDriverPrimitive (unsigned int axisIndex, int center, SEMIAXIS_DIRECTION direction, unsigned int range)
Construct a driver primitive representing the positive or negative half of an axis.
CDriverPrimitive() [5/7]
CDriverPrimitive::CDriverPrimitive (KEYBOARD::XBMCKey keycode)
Construct a driver primitive representing a key on a keyboard.
CDriverPrimitive() [6/7]
CDriverPrimitive::CDriverPrimitive (MOUSE::BUTTON_ID index)
Construct a driver primitive representing a mouse button.
CDriverPrimitive() [7/7]
CDriverPrimitive::CDriverPrimitive (RELATIVE_POINTER_DIRECTION direction)
Construct a driver primitive representing a relative pointer.
Member Function Documentation
Center()
int KODI::JOYSTICK::CDriverPrimitive::Center () const inline
The location of the zero point of the semiaxis.
References m_center.
Referenced by KODI::JOYSTICK::CButtonMapping::CButtonMapping(), PERIPHERALS::CAddonButtonMap::GetAxisProperties(), KODI::JOYSTICK::CAxisDetector::ProcessMotion(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
HatDirection()
HAT_DIRECTION KODI::JOYSTICK::CDriverPrimitive::HatDirection (void) const inline
The direction arrow (valid for hat directions)
References m_hatDirection.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
Index()
unsigned int KODI::JOYSTICK::CDriverPrimitive::Index (void) const inline
The index used by the joystick driver.
Valid for:
buttons
hats
semiaxes
motors
References m_driverIndex.
Referenced by KODI::GAME::CGUIDialogIgnoreInput::AddPrimitive(), KODI::JOYSTICK::CButtonMapping::CButtonMapping(), PERIPHERALS::CAddonButtonMap::CreateLookupTable(), PERIPHERALS::CAddonButtonMap::GetAxisProperties(), KODI::JOYSTICK::CDeadzoneFilter::GetDeadzone(), KODI::JOYSTICK::CJoystickTranslator::GetPrimitiveName(), KODI::GAME::CGUIDialogAxisDetection::MapPrimitiveInternal(), KODI::JOYSTICK::CAxisDetector::ProcessMotion(), KODI::JOYSTICK::CDriverReceiving::SetRumbleState(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
IsValid()
bool CDriverPrimitive::IsValid (void) const
Test if an driver primitive is valid.
A driver primitive is valid if it has a known type and:
1) for hats, it is a cardinal direction 2) for semi-axes, it is a positive or negative direction 3) for keys, the keycode is non-empty
References KODI::JOYSTICK::BUTTON, KODI::JOYSTICK::HAT, KODI::JOYSTICK::KEY, m_center, m_hatDirection, m_keycode, m_pointerDirection, m_range, m_semiAxisDirection, m_type, KODI::JOYSTICK::MOTOR, KODI::JOYSTICK::MOUSE_BUTTON, KODI::JOYSTICK::NEGATIVE, KODI::JOYSTICK::POSITIVE, KODI::JOYSTICK::RELATIVE_POINTER, KODI::JOYSTICK::SEMIAXIS, and XBMCK_UNKNOWN.
Referenced by PERIPHERALS::CAddonButtonMap::GetAnalogStick(), PERIPHERALS::CAddonButtonMap::GetRelativePointer(), PERIPHERALS::CAddonButtonMap::GetThrottle(), PERIPHERALS::CAddonButtonMap::GetWheel(), KODI::JOYSTICK::CPrimitiveDetector::MapPrimitive(), and KODI::JOYSTICK::CPointerDetector::OnMotion().
Keycode()
KEYBOARD::XBMCKey KODI::JOYSTICK::CDriverPrimitive::Keycode () const inline
The keyboard symbol (valid for keys)
References m_keycode.
Referenced by KODI::GAME::CDefaultButtonMap::GetFeature(), KODI::GAME::CGUIConfigurationWizard::MapPrimitive(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
MouseButton()
MOUSE::BUTTON_ID KODI::JOYSTICK::CDriverPrimitive::MouseButton () const inline
The mouse button ID (valid for mouse buttons)
References m_driverIndex.
Referenced by KODI::GAME::CDefaultButtonMap::GetFeature(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
operator!=()
bool KODI::JOYSTICK::CDriverPrimitive::operator!= (const CDriverPrimitive & rhs) const inline
References operator==().
operator<()
bool CDriverPrimitive::operator< (const CDriverPrimitive & rhs) const
References KODI::JOYSTICK::BUTTON, KODI::JOYSTICK::HAT, KODI::JOYSTICK::KEY, m_center, m_driverIndex, m_hatDirection, m_keycode, m_pointerDirection, m_range, m_semiAxisDirection, m_type, KODI::JOYSTICK::MOTOR, KODI::JOYSTICK::MOUSE_BUTTON, KODI::JOYSTICK::RELATIVE_POINTER, and KODI::JOYSTICK::SEMIAXIS.
Referenced by operator<=(), operator>(), and operator>=().
operator<=()
bool KODI::JOYSTICK::CDriverPrimitive::operator<= (const CDriverPrimitive & rhs) const inline
References operator<(), and operator==().
operator==()
bool CDriverPrimitive::operator== (const CDriverPrimitive & rhs) const
References KODI::JOYSTICK::BUTTON, KODI::JOYSTICK::HAT, KODI::JOYSTICK::KEY, m_center, m_driverIndex, m_hatDirection, m_keycode, m_pointerDirection, m_range, m_semiAxisDirection, m_type, KODI::JOYSTICK::MOTOR, KODI::JOYSTICK::MOUSE_BUTTON, KODI::JOYSTICK::RELATIVE_POINTER, and KODI::JOYSTICK::SEMIAXIS.
Referenced by operator!=(), operator<=(), and operator>().
operator>()
bool KODI::JOYSTICK::CDriverPrimitive::operator> (const CDriverPrimitive & rhs) const inline
References operator<(), and operator==().
operator>=()
bool KODI::JOYSTICK::CDriverPrimitive::operator>= (const CDriverPrimitive & rhs) const inline
References operator<().
PointerDirection()
RELATIVE_POINTER_DIRECTION KODI::JOYSTICK::CDriverPrimitive::PointerDirection () const inline
The relative pointer direction (valid for relative pointers)
References m_pointerDirection.
Referenced by KODI::GAME::CDefaultButtonMap::GetFeature(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
Range()
unsigned int KODI::JOYSTICK::CDriverPrimitive::Range () const inline
The distance between the center and the farthest valid value (valid for semiaxes)
References m_range.
Referenced by KODI::JOYSTICK::CButtonMapping::CButtonMapping(), PERIPHERALS::CAddonButtonMap::GetAxisProperties(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
SemiAxisDirection()
SEMIAXIS_DIRECTION KODI::JOYSTICK::CDriverPrimitive::SemiAxisDirection (void) const inline
The semiaxis direction (valid for semiaxes)
References m_semiAxisDirection.
Referenced by PERIPHERALS::CAddonButtonMap::CreateLookupTable(), KODI::JOYSTICK::CAxisDetector::OnMotion(), KODI::JOYSTICK::CAxisDetector::ProcessMotion(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
ToString()
std::string CDriverPrimitive::ToString () const
Convert primitive to a string suitable for logging.
Returns
The primitive as described by a short string, or empty if invalid
References KODI::JOYSTICK::BUTTON, KODI::JOYSTICK::HAT, KODI::JOYSTICK::KEY, m_driverIndex, m_hatDirection, m_keycode, m_pointerDirection, m_semiAxisDirection, m_type, KODI::JOYSTICK::MOTOR, KODI::JOYSTICK::MOUSE_BUTTON, KODI::JOYSTICK::NEGATIVE, KODI::JOYSTICK::POSITIVE, KODI::JOYSTICK::RELATIVE_POINTER, KODI::JOYSTICK::SEMIAXIS, and KODI::KEYBOARD::CKeyboardTranslator::TranslateKeycode().
Referenced by KODI::GAME::CGUIConfigurationWizard::MapPrimitive().
Type()
PRIMITIVE_TYPE KODI::JOYSTICK::CDriverPrimitive::Type (void) const inline
The type of driver primitive.
References m_type.
Referenced by KODI::GAME::CGUIDialogIgnoreInput::AddPrimitive(), PERIPHERALS::CAddonButtonMap::AddScalar(), KODI::JOYSTICK::CButtonMapping::CButtonMapping(), PERIPHERALS::CAddonButtonMap::GetAxisProperties(), KODI::JOYSTICK::CDeadzoneFilter::GetDeadzone(), KODI::GAME::CDefaultButtonMap::GetFeature(), KODI::JOYSTICK::CJoystickTranslator::GetPrimitiveName(), KODI::GAME::CGUIConfigurationWizard::MapPrimitive(), KODI::GAME::CGUIDialogAxisDetection::MapPrimitiveInternal(), KODI::JOYSTICK::CDriverReceiving::SetRumbleState(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
Member Data Documentation
m_center
int KODI::JOYSTICK::CDriverPrimitive::m_center = 0 private
Referenced by Center(), IsValid(), operator<(), and operator==().
m_driverIndex
unsigned int KODI::JOYSTICK::CDriverPrimitive::m_driverIndex = 0 private
Referenced by Index(), MouseButton(), operator<(), operator==(), and ToString().
m_hatDirection
HAT_DIRECTION KODI::JOYSTICK::CDriverPrimitive::m_hatDirection = HAT_DIRECTION::NONE private
Referenced by HatDirection(), IsValid(), operator<(), operator==(), and ToString().
m_keycode
KEYBOARD::XBMCKey KODI::JOYSTICK::CDriverPrimitive::m_keycode = KEYBOARD::XBMCKey::XBMCK_UNKNOWN private
Referenced by IsValid(), Keycode(), operator<(), operator==(), and ToString().
m_pointerDirection
RELATIVE_POINTER_DIRECTION KODI::JOYSTICK::CDriverPrimitive::m_pointerDirection = RELATIVE_POINTER_DIRECTION::NONE private
Referenced by IsValid(), operator<(), operator==(), PointerDirection(), and ToString().
m_range
unsigned int KODI::JOYSTICK::CDriverPrimitive::m_range = 1 private
Referenced by IsValid(), operator<(), operator==(), and Range().
m_semiAxisDirection
SEMIAXIS_DIRECTION KODI::JOYSTICK::CDriverPrimitive::m_semiAxisDirection = SEMIAXIS_DIRECTION::ZERO private
Referenced by IsValid(), operator<(), operator==(), SemiAxisDirection(), and ToString().
m_type
PRIMITIVE_TYPE KODI::JOYSTICK::CDriverPrimitive::m_type = PRIMITIVE_TYPE::UNKNOWN private
Referenced by IsValid(), operator<(), operator==(), ToString(), and Type().
The documentation for this class was generated from the following files:
DriverPrimitive.h
DriverPrimitive.cpp