Kodi Documentation: XFILE Namespace Reference
XFILE Namespace Reference
Namespaces
namespace MUSICDATABASEDIRECTORY
namespace VIDEODATABASEDIRECTORY
Classes
class CAddonsDirectory
Get access to shares and it's directories.
class CAndroidAppDirectory
class CAPKDirectory
class CAPKFile
class CAudioBookFileDirectory
class CBlurayDirectory
class CBlurayFile
class CCacheStrategy
class CCDDADirectory
class CCircularCache
class CCurlFile
class CDAVCommon
class CDAVDirectory
class CDAVFile
class CDirectory
Wrappers for IDirectory.
class CDirectoryCache
class CDirectoryFactory
Get access to a directory of a file system.
class CDoubleCache
class CDVDDirectory
Abstracts a DVD virtual directory (dvd://) which in turn points to the actual physical drive.
class CEventsDirectory
class CFavouritesDirectory
class CFile
class CFileAndroidApp
class CFileCache
class CFileCDDA
class CFileDirectoryFactory
class CFileFactory
class CFileStream
class CFileStreamBuffer
class CFTPDirectory
class CHTTPDirectory
class CImageFile
class CISO9660Directory
class CISO9660File
class CLibraryDirectory
class CMultiPathDirectory
class CMultiPathFile
class CMusicDatabaseDirectory
class CMusicDatabaseFile
class CMusicFileDirectory
class CMusicSearchDirectory
class CNFSDirectory
class CNFSFile
class COverrideDirectory
class COverrideFile
class CPipeFile
class CPlaylistDirectory
class CPlaylistFileDirectory
class CPluginDirectory
class CPluginFile
class CPosixDirectory
class CPosixFile
class CPVRDirectory
class CRedirectException
class CResourceDirectory
class CResourceFile
class CRSSDirectory
class CShoutcastFile
class CSimpleFileCache
class CSmartPlaylistDirectory
class CSMBDirectory
class CSMBFile
class CSourcesDirectory
class CSpecialProtocolDirectory
class CSpecialProtocolFile
class CStackDirectory
class CTVOSDirectory
class CTVOSFile
class CUDFDirectory
class CUDFFile
class CUPnPDirectory
class CUPnPFile
class CVideoDatabaseDirectory
class CVideoDatabaseFile
class CVirtualDirectory
Get access to shares and it's directories.
class CWin32Directory
class CWin32File
class CWin32SMBDirectory
class CWin32SMBFile
class CWinLibraryDirectory
class CWinLibraryFile
class CXbtDirectory
class CXbtFile
class CXbtManager
class CZeroconfDirectory
class CZipDirectory
class CZipFile
class IDirectory
Interface to the directory on a file system.
class IFile
class IFileCallback
class IFileDirectory
class IPipeListener
class Pipe
class PipesManager
struct SCacheStatus
struct SNativeIoControl
Typedefs
template<class TEntry >
using DirectorizeEntryToFileItemFunction = CFileItemPtr(*)(const TEntry &entry, const std::string &label, const std::string &path, bool isFolder)
Method definition to convert an entry to a CFileItemPtr.
template<class TEntry >
using DirectorizeEntry = std::pair< std::string, TEntry >
template<class TEntry >
using DirectorizeEntries = std::vector< DirectorizeEntry< TEntry > >
Enumerations
enum DIR_CACHE_TYPE { DIR_CACHE_NEVER = 0 , DIR_CACHE_ONCE , DIR_CACHE_ALWAYS }
enum DIR_FLAG {
DIR_FLAG_DEFAULTS = 0 , DIR_FLAG_NO_FILE_DIRS = (2 << 0) , DIR_FLAG_ALLOW_PROMPT = (2 << 1) , DIR_FLAG_NO_FILE_INFO = (2 << 2) ,
DIR_FLAG_GET_HIDDEN = (2 << 3) , DIR_FLAG_READ_CACHE = (2 << 4) , DIR_FLAG_BYPASS_CACHE = (2 << 5)
}
Available directory flags The defaults are to allow file directories, no prompting, retrieve file information, hide hidden files, and utilise the directory cache based on the implementation's wishes.
enum CACHE_BUFFER_MODES {
CACHE_BUFFER_MODE_INTERNET = 0 , CACHE_BUFFER_MODE_ALL = 1 , CACHE_BUFFER_MODE_TRUE_INTERNET = 2 , CACHE_BUFFER_MODE_NONE = 3 ,
CACHE_BUFFER_MODE_NETWORK = 4
}
enum EIoControl {
IOCTRL_NATIVE = 1 , IOCTRL_SEEK_POSSIBLE = 2 , IOCTRL_CACHE_STATUS = 3 , IOCTRL_CACHE_SETRATE = 4 ,
IOCTRL_SET_CACHE = 8 , IOCTRL_SET_RETRY = 16
}
enum CURLOPTIONTYPE { CURL_OPTION_OPTION , CURL_OPTION_PROTOCOL , CURL_OPTION_CREDENTIALS , CURL_OPTION_HEADER }
enum FileProperty {
FILE_PROPERTY_RESPONSE_PROTOCOL , FILE_PROPERTY_RESPONSE_HEADER , FILE_PROPERTY_CONTENT_TYPE , FILE_PROPERTY_CONTENT_CHARSET ,
FILE_PROPERTY_MIME_TYPE , FILE_PROPERTY_EFFECTIVE_URL
}
Functions
static bool IsInfoProviderType (AddonType type)
static bool IsInfoProviderTypeAddon (const AddonPtr &addon)
static bool IsLookAndFeelType (AddonType type)
static bool IsLookAndFeelTypeAddon (const AddonPtr &addon)
static bool IsGameType (AddonType type)
static bool IsStandaloneGame (const AddonPtr &addon)
static bool IsEmulator (const AddonPtr &addon)
static bool IsGameProvider (const AddonPtr &addon)
static bool IsGameResource (const AddonPtr &addon)
static bool IsGameSupportAddon (const AddonPtr &addon)
static bool IsGameAddon (const AddonPtr &addon)
static bool IsUserInstalled (const AddonPtr &addon)
static void GenerateTypeListing (const CURL &path, const std::set< AddonType > &types, const VECADDONS &addons, CFileItemList &items)
static void GenerateGameListing (const CURL &path, const VECADDONS &addons, CFileItemList &items)
static void GenerateMainCategoryListing (const CURL &path, const VECADDONS &addons, CFileItemList &items)
static void GenerateCategoryListing (const CURL &path, VECADDONS &addons, CFileItemList &items)
static void UserInstalledAddons (const CURL &path, CFileItemList &items)
static void DependencyAddons (const CURL &path, CFileItemList &items)
static void OutdatedAddons (const CURL &path, CFileItemList &items)
static void RunningAddons (const CURL &path, CFileItemList &items)
static bool Browse (const CURL &path, CFileItemList &items)
static bool GetRecentlyUpdatedAddons (VECADDONS &addons)
static bool HasRecentlyUpdatedAddons ()
static bool Repos (const CURL &path, CFileItemList &items)
static void RootDirectory (CFileItemList &items)
template<class TEntry >
static void Directorize (const CURL &url, const DirectorizeEntries< TEntry > &entries, DirectorizeEntryToFileItemFunction< TEntry > converter, CFileItemList &items)
Analyzes the given entry list from the given URL and turns them into files and directories on one directory hierarchy.
static std::string GetContentMapping (NPT_String &objectClass)
static bool FindDeviceWait (CUPnP *upnp, const char *uuid, PLT_DeviceDataReference &device)
static CFileItemPtr XBTFFileToFileItem (const CXBTFFile &entry, const std::string &label, const std::string &path, bool isFolder)
static CFileItemPtr ZipEntryToFileItem (const SZipEntry &entry, const std::string &label, const std::string &path, bool isFolder)
Variables
const auto CATEGORY_INFO_PROVIDERS = "category.infoproviders"
const auto CATEGORY_LOOK_AND_FEEL = "category.lookandfeel"
const auto CATEGORY_GAME_ADDONS = "category.gameaddons"
const auto CATEGORY_EMULATORS = "category.emulators"
const auto CATEGORY_STANDALONE_GAMES = "category.standalonegames"
const auto CATEGORY_GAME_PROVIDERS = "category.gameproviders"
const auto CATEGORY_GAME_RESOURCES = "category.gameresources"
const auto CATEGORY_GAME_SUPPORT_ADDONS = "category.gamesupport"
const std::set< AddonType > infoProviderTypes
const std::set< AddonType > lookAndFeelTypes
const std::set< AddonType > gameTypes
static const unsigned int READ_TRUNCATED = 0x01
static const unsigned int READ_CHUNKED = 0x02
static const unsigned int READ_CACHED = 0x04
static const unsigned int READ_NO_CACHE = 0x08
static const unsigned int READ_BITRATE = 0x10
static const unsigned int READ_MULTI_STREAM = 0x20
static const unsigned int READ_AUDIO_VIDEO = 0x40
static const unsigned int READ_AFTER_WRITE = 0x80
static const unsigned int READ_REOPEN = 0x100
static const unsigned int READ_NO_BUFFER = 0x200
Typedef Documentation
DirectorizeEntries
template<class TEntry > using XFILE::DirectorizeEntries = typedef std::vector<DirectorizeEntry<TEntry> >
DirectorizeEntry
template<class TEntry > using XFILE::DirectorizeEntry = typedef std::pair<std::string, TEntry>
DirectorizeEntryToFileItemFunction
template<class TEntry > using XFILE::DirectorizeEntryToFileItemFunction = typedef CFileItemPtr(*)(const TEntry& entry, const std::string& label, const std::string& path, bool isFolder)
Method definition to convert an entry to a CFileItemPtr.
Parameters
entry The entry to convert to a CFileItemPtr
label The label of the entry
path The path of the entry
isFolder Whether the entry is a folder or not
Returns
The CFileItemPtr object created from the given entry and data.
Enumeration Type Documentation
CACHE_BUFFER_MODES
enum XFILE::CACHE_BUFFER_MODES
Enumerator
CACHE_BUFFER_MODE_INTERNET
CACHE_BUFFER_MODE_ALL
CACHE_BUFFER_MODE_TRUE_INTERNET
CACHE_BUFFER_MODE_NONE
CACHE_BUFFER_MODE_NETWORK
CURLOPTIONTYPE
enum XFILE::CURLOPTIONTYPE
Enumerator
CURL_OPTION_OPTION
Set a general option
CURL_OPTION_PROTOCOL
Set a protocol option (see below)
CURL_OPTION_CREDENTIALS
Set User and password
CURL_OPTION_HEADER
Add a Header
DIR_CACHE_TYPE
enum XFILE::DIR_CACHE_TYPE
Enumerator
DIR_CACHE_NEVER
Never cache this directory to memory.
DIR_CACHE_ONCE
Cache this directory to memory for each fetch (so that FileExists() checks are fast)
DIR_CACHE_ALWAYS
Always cache this directory to memory, so that each additional fetch of this folder will utilize the cache (until it's cleared)
DIR_FLAG
enum XFILE::DIR_FLAG
Available directory flags The defaults are to allow file directories, no prompting, retrieve file information, hide hidden files, and utilise the directory cache based on the implementation's wishes.
Enumerator
DIR_FLAG_DEFAULTS
DIR_FLAG_NO_FILE_DIRS
Don't convert files (zip, rar etc.) to directories.
DIR_FLAG_ALLOW_PROMPT
Allow prompting for further info (passwords etc.)
DIR_FLAG_NO_FILE_INFO
Don't read additional file info (stat for example)
DIR_FLAG_GET_HIDDEN
Get hidden files.
DIR_FLAG_READ_CACHE
Force reading from the directory cache (if available)
DIR_FLAG_BYPASS_CACHE
Completely bypass the directory cache (no reading, no writing)
EIoControl
enum XFILE::EIoControl
Enumerator
IOCTRL_NATIVE
SNativeIoControl structure, containing what should be passed to native ioctrl
IOCTRL_SEEK_POSSIBLE
return 0 if known not to work, 1 if it should work
IOCTRL_CACHE_STATUS
SCacheStatus structure
IOCTRL_CACHE_SETRATE
unsigned int with speed limit for caching in bytes per second
IOCTRL_SET_CACHE
CFileCache
IOCTRL_SET_RETRY
Enable/disable retry within the protocol handler (if supported)
FileProperty
enum XFILE::FileProperty
The following names for CURL_OPTION_PROTOCOL are possible:
accept-charset: Set the "accept-charset" header acceptencoding or encoding: Set the "accept-encoding" header active-remote: Set the "active-remote" header auth: Set the authentication method. Possible values: any, anysafe, digest, ntlm connection-timeout: Set the connection timeout in seconds cookie: Set the "cookie" header customrequest: Set a custom HTTP request like DELETE noshout: Set to true if kodi detects a stream as shoutcast by mistake. postdata: Set the post body (value needs to be base64 encoded). (Implicitly sets the request to POST) referer: Set the "referer" header user-agent: Set the "user-agent" header seekable: Set the stream seekable. 1: enable, 0: disable sslcipherlist: Set list of accepted SSL ciphers.
Enumerator
FILE_PROPERTY_RESPONSE_PROTOCOL
Get response protocol line
FILE_PROPERTY_RESPONSE_HEADER
Get response Header value
FILE_PROPERTY_CONTENT_TYPE
Get file content-type
FILE_PROPERTY_CONTENT_CHARSET
Get file content charset
FILE_PROPERTY_MIME_TYPE
Get file mime type
FILE_PROPERTY_EFFECTIVE_URL
Get effective URL for redirected streams
Function Documentation
Browse()
static bool XFILE::Browse (const CURL & path, CFileItemList & items) static
References addons, g_localizeStrings, GenerateCategoryListing(), GenerateMainCategoryListing(), CURL::Get(), CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), CURL::GetFileName(), CURL::GetHostName(), ADDON::CAddonRepos::GetLatestAddonVersions(), ADDON::CAddonRepos::GetLatestAddonVersionsFromAllRepos(), ADDON::CAddonRepos::IsValid(), CFileItem::SetLabel(), CFileItem::SetPath(), and CGUIListItem::SetProperty().
Referenced by XFILE::CAddonsDirectory::GetDirectory(), and Repos().
DependencyAddons()
static void XFILE::DependencyAddons (const CURL & path, CFileItemList & items) static
References CVariant::asString(), g_localizeStrings, XFILE::CAddonsDirectory::GenerateAddonListing(), CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetInstalledAddons(), CGUIListItem::GetProperty(), ADDON::CAddonMgr::IsOrphaned(), CGUIListItem::SetProperty(), and CFileItemList::Size().
Referenced by XFILE::CAddonsDirectory::GetDirectory().
Directorize()
template<class TEntry > static void XFILE::Directorize (const CURL & url, const DirectorizeEntries< TEntry > & entries, DirectorizeEntryToFileItemFunction< TEntry > converter, CFileItemList & items) static
Analyzes the given entry list from the given URL and turns them into files and directories on one directory hierarchy.
Parameters
url URL of the directory hierarchy to build
entries Entries to analyze and turn into files and directories
converter Converter function to convert an entry into a CFileItemPtr
items Resulting item list
References CFileItemList::Add(), URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), CFileItemList::Contains(), g_charsetConverter, CURL::Get(), CFileItemList::GetFastLookup(), CURL::GetFileName(), CURL::GetOptions(), URIUtils::HasSlashAtEnd(), label, CFileItemList::SetFastLookup(), CURL::SetFileName(), and CURL::SetOptions().
Referenced by XFILE::CXbtDirectory::GetDirectory(), and XFILE::CZipDirectory::GetDirectory().
FindDeviceWait()
static bool XFILE::FindDeviceWait (CUPnP * upnp, const char * uuid, PLT_DeviceDataReference & device) static
References UPNP::CUPnP::IsClientStarted(), UPNP::CUPnP::m_MediaBrowser, and UPNP::CUPnP::StartClient().
Referenced by XFILE::CUPnPDirectory::GetDirectory(), XFILE::CUPnPDirectory::GetFriendlyName(), and XFILE::CUPnPDirectory::GetResource().
GenerateCategoryListing()
static void XFILE::GenerateCategoryListing (const CURL & path, VECADDONS & addons, CFileItemList & items) static
References addons, CATEGORY_EMULATORS, CATEGORY_GAME_ADDONS, CATEGORY_GAME_PROVIDERS, CATEGORY_GAME_RESOURCES, CATEGORY_GAME_SUPPORT_ADDONS, CATEGORY_INFO_PROVIDERS, CATEGORY_LOOK_AND_FEEL, CATEGORY_STANDALONE_GAMES, g_localizeStrings, XFILE::CAddonsDirectory::GenerateAddonListing(), GenerateGameListing(), GenerateTypeListing(), CLocalizeStrings::Get(), CURL::GetFileName(), infoProviderTypes, lookAndFeelTypes, CFileItem::SetLabel(), CGUIListItem::SetProperty(), and ADDON::CAddonInfo::TranslateType().
Referenced by Browse(), and UserInstalledAddons().
GenerateGameListing()
static void XFILE::GenerateGameListing (const CURL & path, const VECADDONS & addons, CFileItemList & items) static
References CFileItemList::Add(), addons, CATEGORY_EMULATORS, CATEGORY_GAME_PROVIDERS, CATEGORY_GAME_RESOURCES, CATEGORY_GAME_SUPPORT_ADDONS, CATEGORY_STANDALONE_GAMES, g_localizeStrings, CURL::Get(), CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIComponent::GetTextureManager(), CGUITextureManager::HasTexture(), IsEmulator(), IsGameProvider(), IsGameResource(), IsGameSupportAddon(), IsStandaloneGame(), CURL::SetFileName(), ADDON::CAddonInfo::TranslateIconType(), and ADDON::CAddonInfo::TranslateType().
Referenced by GenerateCategoryListing().
GenerateMainCategoryListing()
static void XFILE::GenerateMainCategoryListing (const CURL & path, const VECADDONS & addons, CFileItemList & items) static
References CFileItemList::Add(), URIUtils::AddFileToFolder(), addons, CATEGORY_GAME_ADDONS, CATEGORY_INFO_PROVIDERS, CATEGORY_LOOK_AND_FEEL, g_localizeStrings, GenerateTypeListing(), CURL::Get(), CLocalizeStrings::Get(), CServiceBroker::GetGUI(), ADDON::CAddonType::IsDependencyType(), IsGameAddon(), IsGameType(), IsInfoProviderType(), IsInfoProviderTypeAddon(), IsLookAndFeelType(), IsLookAndFeelTypeAddon(), ADDON::CAddonInfo::TranslateIconType(), and ADDON::CAddonInfo::TranslateType().
Referenced by Browse(), and UserInstalledAddons().
GenerateTypeListing()
static void XFILE::GenerateTypeListing (const CURL & path, const std::set< AddonType > & types, const VECADDONS & addons, CFileItemList & items) static
References CFileItemList::Add(), addons, CURL::Get(), CServiceBroker::GetGUI(), CGUIComponent::GetTextureManager(), CGUITextureManager::HasTexture(), CURL::SetFileName(), ADDON::CAddonInfo::TranslateIconType(), ADDON::CAddonInfo::TranslateType(), and ADDON::types.
Referenced by GenerateCategoryListing(), and GenerateMainCategoryListing().
GetContentMapping()
static std::string XFILE::GetContentMapping (NPT_String & objectClass) static
Referenced by XFILE::CUPnPDirectory::GetDirectory().
GetRecentlyUpdatedAddons()
static bool XFILE::GetRecentlyUpdatedAddons (VECADDONS & addons) static
References addons, CServiceBroker::GetAddonMgr(), and CDateTime::GetCurrentDateTime().
Referenced by XFILE::CAddonsDirectory::GetDirectory(), and HasRecentlyUpdatedAddons().
HasRecentlyUpdatedAddons()
static bool XFILE::HasRecentlyUpdatedAddons () static
References addons, and GetRecentlyUpdatedAddons().
Referenced by RootDirectory().
IsEmulator()
static bool XFILE::IsEmulator (const AddonPtr & addon) static
Referenced by GenerateGameListing().
IsGameAddon()
static bool XFILE::IsGameAddon (const AddonPtr & addon) static
References IsGameProvider(), IsGameResource(), IsGameSupportAddon(), IsGameType(), and IsStandaloneGame().
Referenced by GenerateMainCategoryListing().
IsGameProvider()
static bool XFILE::IsGameProvider (const AddonPtr & addon) static
Referenced by GenerateGameListing(), and IsGameAddon().
IsGameResource()
static bool XFILE::IsGameResource (const AddonPtr & addon) static
Referenced by GenerateGameListing(), and IsGameAddon().
IsGameSupportAddon()
static bool XFILE::IsGameSupportAddon (const AddonPtr & addon) static
Referenced by GenerateGameListing(), and IsGameAddon().
IsGameType()
static bool XFILE::IsGameType (AddonType type) static
References gameTypes.
Referenced by GenerateMainCategoryListing(), and IsGameAddon().
IsInfoProviderType()
static bool XFILE::IsInfoProviderType (AddonType type) static
References infoProviderTypes.
Referenced by GenerateMainCategoryListing(), and IsInfoProviderTypeAddon().
IsInfoProviderTypeAddon()
static bool XFILE::IsInfoProviderTypeAddon (const AddonPtr & addon) static
References IsInfoProviderType().
Referenced by GenerateMainCategoryListing().
IsLookAndFeelType()
static bool XFILE::IsLookAndFeelType (AddonType type) static
References lookAndFeelTypes.
Referenced by GenerateMainCategoryListing(), and IsLookAndFeelTypeAddon().
IsLookAndFeelTypeAddon()
static bool XFILE::IsLookAndFeelTypeAddon (const AddonPtr & addon) static
References IsLookAndFeelType().
Referenced by GenerateMainCategoryListing().
IsStandaloneGame()
static bool XFILE::IsStandaloneGame (const AddonPtr & addon) static
References KODI::GAME::CGameUtils::IsStandaloneGame().
Referenced by GenerateGameListing(), XFILE::CAddonsDirectory::GetScriptsAndPlugins(), and IsGameAddon().
IsUserInstalled()
static bool XFILE::IsUserInstalled (const AddonPtr & addon) static
References ADDON::CAddonType::IsDependencyType().
OutdatedAddons()
static void XFILE::OutdatedAddons (const CURL & path, CFileItemList & items) static
References CFileItemList::Add(), addons, ADDON::AUTO_UPDATES_ON, g_localizeStrings, XFILE::CAddonsDirectory::GenerateAddonListing(), CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetAvailableUpdates(), ADDON::CAddonSystemSettings::GetInstance(), CFileItemList::IsEmpty(), and SortSpecialOnTop.
Referenced by XFILE::CAddonsDirectory::GetDirectory().
Repos()
static bool XFILE::Repos (const CURL & path, CFileItemList & items) static
References CFileItemList::Add(), addons, Browse(), XFILE::CAddonsDirectory::FileItemFromAddon(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetAddons(), ID, CFileItemList::SetContent(), CFileItem::SetLabel(), and SortSpecialOnTop.
Referenced by XFILE::CAddonsDirectory::GetDirectory().
RootDirectory()
static void XFILE::RootDirectory (CFileItemList & items) static
References CFileItemList::Add(), ADDON::AUTO_UPDATES_ON, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), ADDON::CAddonInstaller::GetInstance(), CServiceBroker::GetSettingsComponent(), HasRecentlyUpdatedAddons(), CFileItem::SetLabel(), and CSettings::SETTING_ADDONS_AUTOUPDATES.
Referenced by XFILE::CAddonsDirectory::GetDirectory().
RunningAddons()
static void XFILE::RunningAddons (const CURL & path, CFileItemList & items) static
References addons, g_localizeStrings, XFILE::CAddonsDirectory::GenerateAddonListing(), CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), and ADDON::CAddonMgr::GetAddons().
Referenced by XFILE::CAddonsDirectory::GetDirectory().
UserInstalledAddons()
static void XFILE::UserInstalledAddons (const CURL & path, CFileItemList & items) static
References CFileItemList::Add(), addons, CFileItemList::ClearItems(), g_localizeStrings, XFILE::CAddonsDirectory::GenerateAddonListing(), GenerateCategoryListing(), GenerateMainCategoryListing(), CURL::Get(), CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), CURL::GetFileName(), ADDON::CAddonMgr::GetInstalledAddons(), CURL::SetFileName(), CFileItem::SetLabel(), and SortSpecialOnTop.
Referenced by XFILE::CAddonsDirectory::GetDirectory().
XBTFFileToFileItem()
static CFileItemPtr XFILE::XBTFFileToFileItem (const CXBTFFile & entry, const std::string & label, const std::string & path, bool isFolder) static
References CXBTFFile::GetUnpackedSize(), int64_t(), and label.
Referenced by XFILE::CXbtDirectory::GetDirectory().
ZipEntryToFileItem()
static CFileItemPtr XFILE::ZipEntryToFileItem (const SZipEntry & entry, const std::string & label, const std::string & path, bool isFolder) static
References label, SZipEntry::method, and SZipEntry::usize.
Referenced by XFILE::CZipDirectory::GetDirectory().
Variable Documentation
CATEGORY_EMULATORS
const auto XFILE::CATEGORY_EMULATORS = "category.emulators"
Referenced by GenerateCategoryListing(), and GenerateGameListing().
CATEGORY_GAME_ADDONS
const auto XFILE::CATEGORY_GAME_ADDONS = "category.gameaddons"
Referenced by GenerateCategoryListing(), and GenerateMainCategoryListing().
CATEGORY_GAME_PROVIDERS
const auto XFILE::CATEGORY_GAME_PROVIDERS = "category.gameproviders"
Referenced by GenerateCategoryListing(), and GenerateGameListing().
CATEGORY_GAME_RESOURCES
const auto XFILE::CATEGORY_GAME_RESOURCES = "category.gameresources"
Referenced by GenerateCategoryListing(), and GenerateGameListing().
CATEGORY_GAME_SUPPORT_ADDONS
const auto XFILE::CATEGORY_GAME_SUPPORT_ADDONS = "category.gamesupport"
Referenced by GenerateCategoryListing(), and GenerateGameListing().
CATEGORY_INFO_PROVIDERS
const auto XFILE::CATEGORY_INFO_PROVIDERS = "category.infoproviders"
Referenced by GenerateCategoryListing(), and GenerateMainCategoryListing().
CATEGORY_LOOK_AND_FEEL
const auto XFILE::CATEGORY_LOOK_AND_FEEL = "category.lookandfeel"
Referenced by GenerateCategoryListing(), and GenerateMainCategoryListing().
CATEGORY_STANDALONE_GAMES
const auto XFILE::CATEGORY_STANDALONE_GAMES = "category.standalonegames"
Referenced by GenerateCategoryListing(), and GenerateGameListing().
gameTypes
const std::set<AddonType> XFILE::gameTypes
Initial value:
= {
    AddonType::GAME_CONTROLLER,
    AddonType::GAMEDLL,
    AddonType::GAME,
    AddonType::RESOURCE_GAMES,
}
Referenced by IsGameType().
infoProviderTypes
const std::set<AddonType> XFILE::infoProviderTypes
Initial value:
= {
    AddonType::SCRAPER_ALBUMS,      AddonType::SCRAPER_ARTISTS, AddonType::SCRAPER_MOVIES,
    AddonType::SCRAPER_MUSICVIDEOS, AddonType::SCRAPER_TVSHOWS,
}
Referenced by GenerateCategoryListing(), and IsInfoProviderType().
lookAndFeelTypes
const std::set<AddonType> XFILE::lookAndFeelTypes
Initial value:
= {
    AddonType::SKIN,
    AddonType::SCREENSAVER,
    AddonType::RESOURCE_IMAGES,
    AddonType::RESOURCE_LANGUAGE,
    AddonType::RESOURCE_UISOUNDS,
    AddonType::RESOURCE_FONT,
    AddonType::VISUALIZATION,
}
Referenced by GenerateCategoryListing(), and IsLookAndFeelType().
READ_AFTER_WRITE
const unsigned int XFILE::READ_AFTER_WRITE = 0x80 static
Referenced by ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi().
READ_AUDIO_VIDEO
const unsigned int XFILE::READ_AUDIO_VIDEO = 0x40 static
Referenced by CDVDInputStreamFile::Open(), XFILE::CFile::Open(), XFILE::CFileCache::Open(), and ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi().
READ_BITRATE
const unsigned int XFILE::READ_BITRATE = 0x10 static
Referenced by CDVDFactoryInputStream::CreateInputStream(), CDVDInputStreamNavigator::Open(), XFILE::CFile::Open(), CDVDInputStreamBluray::OpenStream(), and ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi().
READ_CACHED
const unsigned int XFILE::READ_CACHED = 0x04 static
Referenced by KODI::CDRIP::CCDDARipJob::DoWork(), XFILE::CFile::Open(), and ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi().
READ_CHUNKED
const unsigned int XFILE::READ_CHUNKED = 0x02 static
Referenced by XFILE::CFile::Copy(), CDVDFactoryInputStream::CreateInputStream(), CDVDInputStreamNavigator::Open(), CDVDInputStreamBluray::OpenStream(), ActiveAE::CActiveAESound::Prepare(), XFILE::CFile::ShouldUseStreamBuffer(), and ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi().
READ_MULTI_STREAM
const unsigned int XFILE::READ_MULTI_STREAM = 0x20 static
Referenced by CDVDInputStreamFile::Open(), XFILE::CFileCache::Open(), and ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi().
READ_NO_BUFFER
const unsigned int XFILE::READ_NO_BUFFER = 0x200 static
Referenced by CDVDInputStreamFile::Open(), XFILE::CFileCache::Open(), XFILE::CFile::ShouldUseStreamBuffer(), and ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi().
READ_NO_CACHE
const unsigned int XFILE::READ_NO_CACHE = 0x08 static
Referenced by CWebServer::CreateFileDownloadResponse(), XBMCAddon::xbmcvfs::File::File(), TestWebServer::GetLastModifiedOfTestFile(), XFILE::CFile::Open(), XFILE::CFileCache::Open(), CDVDInputStreamBluray::OpenStream(), CHTTPFileHandler::SetFile(), and ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi().
READ_REOPEN
const unsigned int XFILE::READ_REOPEN = 0x100 static
Referenced by XFILE::CFile::Open(), and ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi().
READ_TRUNCATED
const unsigned int XFILE::READ_TRUNCATED = 0x01 static
Referenced by XFILE::CFile::Copy(), CDVDFactoryInputStream::CreateInputStream(), dll_open(), KODI::RETRO::CSavestateDatabase::GetSavestate(), XFILE::CFile::LoadFile(), CDVDInputStreamNavigator::Open(), CDVDInputStreamStack::Open(), XFILE::CFileCache::Open(), CDVDInputStreamBluray::OpenStream(), ActiveAE::CActiveAESound::Prepare(), XFILE::CFile::Read(), and ADDON::Interface_Filesystem::TranslateFileReadBitsToKodi().