Kodi Documentation: ADDON::Interface_GUIControlLabel Struct Reference
ADDON::Interface_GUIControlLabel Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Label.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
callback functions from add-on to kodi
static void set_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *label)
static char * get_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold general gui functions and initialize also all other gui related types not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/controls/Label.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIControlLabel::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_label, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
get_label()
char * ADDON::Interface_GUIControlLabel::get_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUILabelControl::GetDescription(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIControlLabel::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_label, get_label(), AddonToKodiFuncTable_kodi_gui_control_label::get_label, AddonToKodiFuncTable_Addon::kodi_gui, set_label(), AddonToKodiFuncTable_kodi_gui_control_label::set_label, set_visible(), AddonToKodiFuncTable_kodi_gui_control_label::set_visible, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
set_label()
void ADDON::Interface_GUIControlLabel::set_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * label) static
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIControl::GetParentID(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_SET, ADDON::CAddon::ID(), label, CLog::Log(), LOGERROR, and CGUIMessage::SetLabel().
Referenced by Init().
set_visible()
void ADDON::Interface_GUIControlLabel::set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetVisible().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/controls/label.h
Label.cpp