Kodi Documentation: Shaders::GLES::YUV2RGBFilterShader Class Reference
Shaders::GLES::YUV2RGBFilterShader Class Reference
#include <YUV2RGBShaderGLES.h>
Public Member Functions
YUV2RGBFilterShader (EShaderFormat format, AVColorPrimaries dstPrimaries, AVColorPrimaries srcPrimaries, bool toneMap, ETONEMAPMETHOD toneMapMethod, ESCALINGMETHOD method)
~YUV2RGBFilterShader () override
Public Member Functions inherited from Shaders::GLES::BaseYUV2RGBGLSLShader
BaseYUV2RGBGLSLShader (EShaderFormat format, AVColorPrimaries dst, AVColorPrimaries src, bool toneMap, ETONEMAPMETHOD toneMapMethod)
~BaseYUV2RGBGLSLShader () override
void SetField (int field)
void SetWidth (int w)
void SetHeight (int h)
void SetColParams (AVColorSpace colSpace, int bits, bool limited, int textureBits)
void SetBlack (float black)
void SetContrast (float contrast)
void SetConvertFullColorRange (bool convertFullRange)
void SetDisplayMetadata (bool hasDisplayMetadata, const AVMasteringDisplayMetadata &displayMetadata, bool hasLightMetadata, AVContentLightMetadata lightMetadata)
void SetToneMapParam (float param)
GLint GetVertexLoc ()
GLint GetYcoordLoc ()
GLint GetUcoordLoc ()
GLint GetVcoordLoc ()
void SetMatrices (const GLfloat *p, const GLfloat *m)
void SetAlpha (GLfloat alpha)
Public Member Functions inherited from Shaders::CGLSLShaderProgram
CGLSLShaderProgram ()
CGLSLShaderProgram (const std::string &vert, const std::string &frag)
~CGLSLShaderProgram () override
bool Enable () override
void Disable () override
bool CompileAndLink () override
Public Member Functions inherited from Shaders::CShaderProgram
CShaderProgram ()=default
virtual ~CShaderProgram ()
bool OK () const
CVertexShader * VertexShader ()
CPixelShader * PixelShader ()
virtual GLuint ProgramHandle ()
Protected Member Functions
void OnCompiledAndLinked () override
bool OnEnabled () override
Protected Member Functions inherited from Shaders::GLES::BaseYUV2RGBGLSLShader
void OnDisabled () override
void Free ()
Protected Member Functions inherited from Shaders::CGLSLShaderProgram
void Free ()
Protected Attributes
GLuint m_kernelTex = 0
GLint m_hKernTex = -1
ESCALINGMETHOD m_scaling = VS_SCALINGMETHOD_LANCZOS3_FAST
Protected Attributes inherited from Shaders::GLES::BaseYUV2RGBGLSLShader
EShaderFormat m_format
int m_width
int m_height
int m_field
bool m_hasDisplayMetadata {false}
AVMasteringDisplayMetadata m_displayMetadata
bool m_hasLightMetadata {false}
AVContentLightMetadata m_lightMetadata
bool m_toneMapping {false}
ETONEMAPMETHOD m_toneMappingMethod {VS_TONEMAPMETHOD_OFF}
float m_toneMappingParam {1.0}
bool m_colorConversion {false}
float m_black
float m_contrast
std::string m_defines
CConvertMatrix m_convMatrix
GLint m_hYTex {-1}
GLint m_hUTex {-1}
GLint m_hVTex {-1}
GLint m_hYuvMat {-1}
GLint m_hStep {-1}
GLint m_hGammaSrc {-1}
GLint m_hGammaDstInv {-1}
GLint m_hPrimMat {-1}
GLint m_hToneP1 {-1}
GLint m_hCoefsDst {-1}
GLint m_hLuminance = -1
GLint m_hVertex {-1}
GLint m_hYcoord {-1}
GLint m_hUcoord {-1}
GLint m_hVcoord {-1}
GLint m_hProj {-1}
GLint m_hModel {-1}
GLint m_hAlpha {-1}
const GLfloat * m_proj {nullptr}
const GLfloat * m_model {nullptr}
GLfloat m_alpha {1.0f}
bool m_convertFullRange
Protected Attributes inherited from Shaders::CGLSLShaderProgram
GLint m_lastProgram
bool m_validated = false
Protected Attributes inherited from Shaders::CShaderProgram
CVertexShader * m_pVP = nullptr
CPixelShader * m_pFP = nullptr
GLuint m_shaderProgram = 0
bool m_ok = false
Constructor & Destructor Documentation
YUV2RGBFilterShader()
YUV2RGBFilterShader::YUV2RGBFilterShader (EShaderFormat format, AVColorPrimaries dstPrimaries, AVColorPrimaries srcPrimaries, bool toneMap, ETONEMAPMETHOD toneMapMethod, ESCALINGMETHOD method)
References Shaders::CShader::AppendSource(), Shaders::CShader::InsertSource(), Shaders::CShader::LoadSource(), Shaders::GLES::BaseYUV2RGBGLSLShader::m_defines, m_scaling, Shaders::CShaderProgram::PixelShader(), and Shaders::CShaderProgram::VertexShader().
~YUV2RGBFilterShader()
YUV2RGBFilterShader::~YUV2RGBFilterShader () override
References m_kernelTex.
Member Function Documentation
OnCompiledAndLinked()
void YUV2RGBFilterShader::OnCompiledAndLinked () override protected virtual
Reimplemented from Shaders::GLES::BaseYUV2RGBGLSLShader.
References data(), CConvolutionKernel::GetFloatPixels(), CConvolutionKernel::GetSize(), m_hKernTex, m_kernelTex, m_scaling, Shaders::GLES::BaseYUV2RGBGLSLShader::OnCompiledAndLinked(), Shaders::CShaderProgram::ProgramHandle(), VerifyGLState, VS_SCALINGMETHOD_LANCZOS3_FAST, and VS_SCALINGMETHOD_SPLINE36_FAST.
OnEnabled()
bool YUV2RGBFilterShader::OnEnabled () override protected virtual
Reimplemented from Shaders::GLES::BaseYUV2RGBGLSLShader.
References m_hKernTex, m_kernelTex, and Shaders::GLES::BaseYUV2RGBGLSLShader::OnEnabled().
Member Data Documentation
m_hKernTex
GLint Shaders::GLES::YUV2RGBFilterShader::m_hKernTex = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_kernelTex
GLuint Shaders::GLES::YUV2RGBFilterShader::m_kernelTex = 0 protected
Referenced by OnCompiledAndLinked(), OnEnabled(), and ~YUV2RGBFilterShader().
m_scaling
ESCALINGMETHOD Shaders::GLES::YUV2RGBFilterShader::m_scaling = VS_SCALINGMETHOD_LANCZOS3_FAST protected
Referenced by OnCompiledAndLinked(), and YUV2RGBFilterShader().
The documentation for this class was generated from the following files:
YUV2RGBShaderGLES.h
YUV2RGBShaderGLES.cpp