Kodi Documentation: CWakeOnAccess Class Reference
CWakeOnAccess Class Reference
#include <WakeOnAccess.h>
Classes
struct WakeUpEntry
Public Member Functions
bool WakeUpHost (const CURL &fileUrl)
bool WakeUpHost (const std::string &hostName, const std::string &customMessage)
void QueueMACDiscoveryForAllRemotes ()
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingsLoaded () override
Settings have been loaded.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsUnloaded ()
Setting values have been unloaded.
virtual void OnSettingsCleared ()
Settings have been cleared.
Static Public Member Functions
static CWakeOnAccess & GetInstance ()
Private Types
typedef std::vector< WakeUpEntry > EntriesVector
Private Member Functions
CWakeOnAccess ()
std::string GetSettingFile ()
void LoadFromXML ()
void SaveToXML ()
void SetEnabled (bool enabled)
bool IsEnabled () const
void QueueMACDiscoveryForHost (const std::string &host)
void SaveMACDiscoveryResult (const std::string &host, const std::string &mac)
bool FindOrTouchHostEntry (const std::string &hostName, bool upnpMode, WakeUpEntry &server)
void TouchHostEntry (const std::string &hostName, bool upnpMode)
bool WakeUpHost (const std::string &hostName, const std::string &customMessage, bool upnpMode)
bool WakeUpHost (const WakeUpEntry &server)
Private Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Private Attributes
EntriesVector m_entries
CCriticalSection m_entrylist_protect
unsigned int m_netinit_sec
unsigned int m_netsettle_ms
bool m_enabled = false
std::vector< struct UPnPServer > m_UPnPServers
Member Typedef Documentation
EntriesVector
typedef std::vector<WakeUpEntry> CWakeOnAccess::EntriesVector private
Constructor & Destructor Documentation
CWakeOnAccess()
CWakeOnAccess::CWakeOnAccess () private
Member Function Documentation
FindOrTouchHostEntry()
bool CWakeOnAccess::FindOrTouchHostEntry (const std::string & hostName, bool upnpMode, WakeUpEntry & server) private
References CWakeOnAccess::WakeUpEntry::friendlyName, CDateTime::GetCurrentDateTime(), LookupUPnPServer(), m_entries, m_entrylist_protect, UPnPServer::m_mac, UPnPServer::m_name, UPnPServer::m_nextWake, m_UPnPServers, UPnPServer::m_uuid, and CWakeOnAccess::WakeUpEntry::upnpUuid.
Referenced by WakeUpHost().
GetInstance()
CWakeOnAccess & CWakeOnAccess::GetInstance () static
Referenced by dbiplus::MysqlDatabase::connect(), XFILE::CDirectoryFactory::Create(), XFILE::CFileFactory::CreateLoader(), CSettings::InitializeISettingCallbacks(), CSettings::InitializeISettingsHandlers(), CMediaSourceSettings::Save(), CSettings::UninitializeISettingCallbacks(), and CSettings::UninitializeISettingsHandlers().
GetSettingFile()
std::string CWakeOnAccess::GetSettingFile () private
References CSpecialProtocol::TranslatePath().
Referenced by LoadFromXML(), and SaveToXML().
IsEnabled()
bool CWakeOnAccess::IsEnabled () const inline private
References m_enabled.
Referenced by OnJobComplete(), QueueMACDiscoveryForHost(), and WakeUpHost().
LoadFromXML()
void CWakeOnAccess::LoadFromXML () private
References XMLUtils::GetInt(), GetSettingFile(), CServiceBroker::GetSettingsComponent(), XMLUtils::GetString(), GetTotalSeconds(), CWakeOnAccess::WakeUpEntry::host, CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGERROR, LOGINFO, m_entries, UPnPServer::m_mac, UPnPServer::m_name, m_netinit_sec, m_netsettle_ms, m_UPnPServers, UPnPServer::m_uuid, CWakeOnAccess::WakeUpEntry::mac, CWakeOnAccess::WakeUpEntry::ping_mode, CWakeOnAccess::WakeUpEntry::ping_port, CDateTimeSpan::SetDateTimeSpan(), SetEnabled(), CSettings::SETTING_POWERMANAGEMENT_WAKEONACCESS, CWakeOnAccess::WakeUpEntry::timeout, CWakeOnAccess::WakeUpEntry::wait_online1_sec, CWakeOnAccess::WakeUpEntry::wait_online2_sec, and CWakeOnAccess::WakeUpEntry::wait_services_sec.
Referenced by OnSettingsLoaded().
OnJobComplete()
void CWakeOnAccess::OnJobComplete (unsigned int jobID, bool success, CJob * job) override virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
References CGUIDialogKaiToast::Error, CMACDiscoveryJob::GetHost(), CMACDiscoveryJob::GetMAC(), IsEnabled(), LOCALIZED, CLog::Log(), LOGERROR, m_entrylist_protect, CGUIDialogKaiToast::QueueNotification(), SaveMACDiscoveryResult(), and success.
OnSettingChanged()
void CWakeOnAccess::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References QueueMACDiscoveryForAllRemotes(), SetEnabled(), and CSettings::SETTING_POWERMANAGEMENT_WAKEONACCESS.
OnSettingsLoaded()
void CWakeOnAccess::OnSettingsLoaded () override virtual
Settings have been loaded.
This callback can be used to trigger loading other settings.
Reimplemented from ISettingsHandler.
References LoadFromXML(), and m_entrylist_protect.
QueueMACDiscoveryForAllRemotes()
void CWakeOnAccess::QueueMACDiscoveryForAllRemotes ()
References AddHost(), AddHostFromDatabase(), AddHostsFromVecSource(), CURL::GetHostName(), CMediaSourceSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CMediaSourceSettings::GetSources(), and QueueMACDiscoveryForHost().
Referenced by OnSettingChanged(), and CMediaSourceSettings::Save().
QueueMACDiscoveryForHost()
void CWakeOnAccess::QueueMACDiscoveryForHost (const std::string & host) private
References ANY_PRIVATE_SUBNET, CServiceBroker::GetJobManager(), IsEnabled(), URIUtils::IsHostOnLAN(), CLog::Log(), and LOGINFO.
Referenced by QueueMACDiscoveryForAllRemotes().
SaveMACDiscoveryResult()
void CWakeOnAccess::SaveMACDiscoveryResult (const std::string & host, const std::string & mac) private
References AddMatchingUPnPServers(), CWakeOnAccess::WakeUpEntry::host, CLog::Log(), LOGINFO, m_entries, m_UPnPServers, CWakeOnAccess::WakeUpEntry::mac, SaveToXML(), ShowDiscoveryMessage(), and CWakeOnAccess::WakeUpEntry::timeout.
Referenced by OnJobComplete().
SaveToXML()
void CWakeOnAccess::SaveToXML () private
References GetSettingFile(), GetTotalSeconds(), m_entries, m_netinit_sec, m_netsettle_ms, m_UPnPServers, root, CXBMCTinyXML2::SaveFile(), XMLUtils::SetInt(), and XMLUtils::SetString().
Referenced by SaveMACDiscoveryResult().
SetEnabled()
void CWakeOnAccess::SetEnabled (bool enabled) private
References CLog::Log(), LOGINFO, and m_enabled.
Referenced by LoadFromXML(), and OnSettingChanged().
TouchHostEntry()
void CWakeOnAccess::TouchHostEntry (const std::string & hostName, bool upnpMode) private
References CDateTime::GetCurrentDateTime(), LookupUPnPServer(), m_entries, m_entrylist_protect, UPnPServer::m_mac, UPnPServer::m_nextWake, and m_UPnPServers.
Referenced by WakeUpHost().
WakeUpHost() [1/4]
bool CWakeOnAccess::WakeUpHost (const CURL & fileUrl)
References CURL::Get(), CURL::GetHostName(), CURL::IsProtocol(), and WakeUpHost().
Referenced by dbiplus::MysqlDatabase::connect(), WakeUpHost(), WakeUpHost(), and WakeUpHost().
WakeUpHost() [2/4]
bool CWakeOnAccess::WakeUpHost (const std::string & hostName, const std::string & customMessage)
References WakeUpHost().
WakeUpHost() [3/4]
bool CWakeOnAccess::WakeUpHost (const std::string & hostName, const std::string & customMessage, bool upnpMode) private
References FindOrTouchHostEntry(), CWakeOnAccess::WakeUpEntry::friendlyName, IsEnabled(), NestDetect::IsNested(), NestDetect::Level(), CLog::Log(), LOGINFO, LOGWARNING, TouchHostEntry(), and WakeUpHost().
WakeUpHost() [4/4]
bool CWakeOnAccess::WakeUpHost (const WakeUpEntry & server) private
References CGUIDialogKaiToast::Error, CWakeOnAccess::WakeUpEntry::friendlyName, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetNetwork(), ProgressDialogHelper::HasDialog(), CWakeOnAccess::WakeUpEntry::host, HostToIP(), LOCALIZED, CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, m_netinit_sec, m_netsettle_ms, CWakeOnAccess::WakeUpEntry::mac, PingResponseWaiter::Ping(), CGUIDialogKaiToast::QueueNotification(), ProgressDialogHelper::ShowAndWait(), ProgressDialogHelper::Success, ProgressDialogHelper::TimedOut, CWakeOnAccess::WakeUpEntry::wait_online1_sec, CWakeOnAccess::WakeUpEntry::wait_online2_sec, and CWakeOnAccess::WakeUpEntry::wait_services_sec.
Member Data Documentation
m_enabled
bool CWakeOnAccess::m_enabled = false private
Referenced by IsEnabled(), and SetEnabled().
m_entries
EntriesVector CWakeOnAccess::m_entries private
Referenced by FindOrTouchHostEntry(), LoadFromXML(), SaveMACDiscoveryResult(), SaveToXML(), and TouchHostEntry().
m_entrylist_protect
CCriticalSection CWakeOnAccess::m_entrylist_protect private
Referenced by FindOrTouchHostEntry(), OnJobComplete(), OnSettingsLoaded(), and TouchHostEntry().
m_netinit_sec
unsigned int CWakeOnAccess::m_netinit_sec private
Referenced by LoadFromXML(), SaveToXML(), and WakeUpHost().
m_netsettle_ms
unsigned int CWakeOnAccess::m_netsettle_ms private
Referenced by LoadFromXML(), SaveToXML(), and WakeUpHost().
m_UPnPServers
std::vector<struct UPnPServer> CWakeOnAccess::m_UPnPServers private
Referenced by FindOrTouchHostEntry(), LoadFromXML(), SaveMACDiscoveryResult(), SaveToXML(), and TouchHostEntry().
The documentation for this class was generated from the following files:
WakeOnAccess.h
WakeOnAccess.cpp