Kodi Documentation: KODI::PLATFORM::FILESYSTEM Namespace Reference
KODI::PLATFORM::FILESYSTEM Namespace Reference
Namespaces
namespace anonymous_namespace{Filesystem.cpp}
Classes
struct space_info
Functions
space_info space (const std::string &path, std::error_code &ec)
std::string temp_directory_path (std::error_code &ec)
std::string create_temp_directory (std::error_code &ec)
std::string temp_file_path (const std::string &suffix, std::error_code &ec)
Function Documentation
create_temp_directory()
std::string KODI::PLATFORM::FILESYSTEM::create_temp_directory (std::error_code & ec)
References PATH_MAX, and temp_directory_path().
Referenced by TestBasicEnvironment::SetUp(), temp_file_path(), TEST_P(), and TEST_P().
space()
space_info KODI::PLATFORM::FILESYSTEM::space (const std::string & path, std::error_code & ec)
References KODI::PLATFORM::FILESYSTEM::space_info::available, KODI::PLATFORM::FILESYSTEM::space_info::capacity, KODI::PLATFORM::FILESYSTEM::space_info::free, and CSpecialProtocol::TranslatePath().
temp_directory_path()
std::string KODI::PLATFORM::FILESYSTEM::temp_directory_path (std::error_code & ec)
References URIUtils::AppendSlash().
Referenced by create_temp_directory(), TEST(), and TEST_P().
temp_file_path()
std::string KODI::PLATFORM::FILESYSTEM::temp_file_path (const std::string & suffix, std::error_code & ec)
References URIUtils::AddFileToFolder(), create_temp_directory(), and PATH_MAX.
Referenced by CTempFile::Create().