Kodi Documentation: ConditionPoll Namespace Reference
ConditionPoll Namespace Reference
Functions
template<typename L >
bool poll (unsigned int timeoutMillis, L lambda)
template<typename L >
bool poll (L lambda)
Variables
constexpr unsigned int defaultTimeout {20000}
Function Documentation
poll() [1/2]
template<typename L > bool ConditionPoll::poll (L lambda) inline
poll until the lambda returns true or the defaultTimeout occurs. If the timeout occurs then the function will return false. Otherwise it will return true.
References defaultTimeout, and poll().
poll() [2/2]
template<typename L > bool ConditionPoll::poll (unsigned int timeoutMillis, L lambda) inline
poll until the lambda returns true or the timeout occurs. If the timeout occurs then the function will return false. Otherwise it will return true.
Referenced by poll(), TEST_F(), and TEST_F().
Variable Documentation
defaultTimeout
constexpr unsigned int ConditionPoll::defaultTimeout {20000} constexpr
This is usually enough time for the condition to have occurred in a test.
Referenced by poll().