Kodi Documentation: KODI::JOYSTICK::CJoystickMonitor Class Reference
KODI::JOYSTICK::CJoystickMonitor Class Reference
Input » Joystick
Monitors joystick input and resets screensaver/shutdown timers whenever motion occurs.
#include <JoystickMonitor.h>
Public Member Functions
std::string ControllerID () const override
The add-on ID of the game controller associated with this input handler.
bool HasFeature (const FeatureName &feature) const override
Return true if the input handler accepts the given feature.
bool AcceptsInput (const FeatureName &feature) const override
Return true if the input handler is currently accepting input for the given feature.
bool OnButtonPress (const FeatureName &feature, bool bPressed) override
A digital button has been pressed or released.
void OnButtonHold (const FeatureName &feature, unsigned int holdTimeMs) override
A digital button has been pressed for more than one event frame.
bool OnButtonMotion (const FeatureName &feature, float magnitude, unsigned int motionTimeMs) override
An analog button (trigger or a pressure-sensitive button) has changed state.
bool OnAnalogStickMotion (const FeatureName &feature, float x, float y, unsigned int motionTimeMs) override
An analog stick has moved.
bool OnAccelerometerMotion (const FeatureName &feature, float x, float y, float z) override
An accelerometer's state has changed.
bool OnWheelMotion (const FeatureName &feature, float position, unsigned int motionTimeMs) override
A wheel has changed state.
bool OnThrottleMotion (const FeatureName &feature, float position, unsigned int motionTimeMs) override
A throttle has changed state.
void OnInputFrame () override
Called at the end of the frame that provided input.
Public Member Functions inherited from KODI::JOYSTICK::IInputHandler
virtual ~IInputHandler ()=default
void SetInputReceiver (IInputReceiver *receiver)
void ResetInputReceiver (void)
IInputReceiver * InputReceiver (void)
Private Member Functions
bool ResetTimers (void)
Reset screensaver and shutdown timers.
Detailed Description
Monitors joystick input and resets screensaver/shutdown timers whenever motion occurs.
Member Function Documentation
AcceptsInput()
bool CJoystickMonitor::AcceptsInput (const FeatureName & feature) const override virtual
Return true if the input handler is currently accepting input for the given feature.
Parameters
feature A feature belonging to the controller specified by ControllerID()
Returns
True if the feature is currently accepting input, false otherwise
This does not prevent the input events from being called, but can return false to indicate that input wasn't handled for the specified feature.
Implements KODI::JOYSTICK::IInputHandler.
References CServiceBroker::GetAppComponents(), and CApplicationPowerHandling::IsInScreenSaver().
ControllerID()
std::string CJoystickMonitor::ControllerID () const override virtual
The add-on ID of the game controller associated with this input handler.
Returns
The ID of the add-on extending kodi.game.controller
Implements KODI::JOYSTICK::IInputHandler.
References DEFAULT_CONTROLLER_ID.
HasFeature()
bool KODI::JOYSTICK::CJoystickMonitor::HasFeature (const FeatureName & feature) const inline override virtual
Return true if the input handler accepts the given feature.
Parameters
feature A feature belonging to the controller specified by ControllerID()
Returns
True if the feature is used for input, false otherwise
Implements KODI::JOYSTICK::IInputHandler.
OnAccelerometerMotion()
bool KODI::JOYSTICK::CJoystickMonitor::OnAccelerometerMotion (const FeatureName & feature, float x, float y, float z) inline override virtual
An accelerometer's state has changed.
Parameters
feature The accelerometer being accelerated
x The x coordinate in the closed interval [-1, 1]
y The y coordinate in the closed interval [-1, 1]
z The z coordinate in the closed interval [-1, 1]
Returns
True if the event was handled otherwise false
Reimplemented from KODI::JOYSTICK::IInputHandler.
OnAnalogStickMotion()
bool CJoystickMonitor::OnAnalogStickMotion (const FeatureName & feature, float x, float y, unsigned int motionTimeMs) override virtual
An analog stick has moved.
Parameters
feature The analog stick being moved
x The x coordinate in the closed interval [-1, 1]
y The y coordinate in the closed interval [-1, 1]
motionTimeMs The time elapsed since this analog stick was centered, or 0 if the analog stick is centered
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References CServiceBroker::GetInputManager(), ResetTimers(), and CInputManager::SetMouseActive().
OnButtonHold()
void KODI::JOYSTICK::CJoystickMonitor::OnButtonHold (const FeatureName & feature, unsigned int holdTimeMs) inline override virtual
A digital button has been pressed for more than one event frame.
Parameters
feature The feature being held
holdTimeMs The time elapsed since the initial press (ms)
If OnButtonPress() returns true for the initial press, then this callback is invoked on subsequent frames until the button is released.
Implements KODI::JOYSTICK::IInputHandler.
OnButtonMotion()
bool CJoystickMonitor::OnButtonMotion (const FeatureName & feature, float magnitude, unsigned int motionTimeMs) override virtual
An analog button (trigger or a pressure-sensitive button) has changed state.
Parameters
feature The feature changing state
magnitude The button pressure or trigger travel distance in the closed interval [0, 1]
motionTimeMs The time elapsed since the magnitude was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References AXIS_DEADZONE, CServiceBroker::GetInputManager(), ResetTimers(), and CInputManager::SetMouseActive().
OnButtonPress()
bool CJoystickMonitor::OnButtonPress (const FeatureName & feature, bool bPressed) override virtual
A digital button has been pressed or released.
Parameters
feature The feature being pressed
bPressed True if pressed, false if released
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References CServiceBroker::GetInputManager(), ResetTimers(), and CInputManager::SetMouseActive().
OnInputFrame()
void KODI::JOYSTICK::CJoystickMonitor::OnInputFrame () inline override virtual
Called at the end of the frame that provided input.
Implements KODI::JOYSTICK::IInputHandler.
OnThrottleMotion()
bool CJoystickMonitor::OnThrottleMotion (const FeatureName & feature, float position, unsigned int motionTimeMs) override virtual
A throttle has changed state.
Up is positive position, down is negative position.
Parameters
feature The wheel changing state
position The position in the closed interval [-1, 1]
motionTimeMs The time elapsed since the position was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References AXIS_DEADZONE, CServiceBroker::GetInputManager(), ResetTimers(), and CInputManager::SetMouseActive().
OnWheelMotion()
bool CJoystickMonitor::OnWheelMotion (const FeatureName & feature, float position, unsigned int motionTimeMs) override virtual
A wheel has changed state.
Left is negative position, right is positive position
Parameters
feature The wheel changing state
position The position in the closed interval [-1, 1]
motionTimeMs The time elapsed since the position was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References AXIS_DEADZONE, CServiceBroker::GetInputManager(), ResetTimers(), and CInputManager::SetMouseActive().
ResetTimers()
bool CJoystickMonitor::ResetTimers (void) private
Reset screensaver and shutdown timers.
Returns
True if the application was woken from screensaver
References CServiceBroker::GetAppComponents(), and CApplicationPowerHandling::ResetSystemIdleTimer().
Referenced by OnAnalogStickMotion(), OnButtonMotion(), OnButtonPress(), OnThrottleMotion(), and OnWheelMotion().
The documentation for this class was generated from the following files:
JoystickMonitor.h
JoystickMonitor.cpp