Kodi Documentation: TestBase64.cpp File Reference
TestBase64.cpp File Reference
#include "utils/Base64.h"
#include <gtest/gtest.h>
Functions
TEST (TestBase64, Encode_1)
TEST (TestBase64, Encode_2)
TEST (TestBase64, Encode_3)
TEST (TestBase64, Encode_4)
TEST (TestBase64, Decode_1)
TEST (TestBase64, Decode_2)
TEST (TestBase64, Decode_3)
TEST (TestBase64, Decode_4)
Variables
static const char refdata []
static const char refbase64data []
Function Documentation
TEST() [1/8]
TEST (TestBase64 , Decode_1)
References Base64::Decode(), refbase64data, and refdata.
TEST() [2/8]
TEST (TestBase64 , Decode_2)
References Base64::Decode(), refbase64data, and refdata.
TEST() [3/8]
TEST (TestBase64 , Decode_3)
References Base64::Decode(), refbase64data, and refdata.
TEST() [4/8]
TEST (TestBase64 , Decode_4)
References Base64::Decode(), refbase64data, and refdata.
TEST() [5/8]
TEST (TestBase64 , Encode_1)
References Base64::Encode(), refbase64data, and refdata.
TEST() [6/8]
TEST (TestBase64 , Encode_2)
References Base64::Encode(), refbase64data, and refdata.
TEST() [7/8]
TEST (TestBase64 , Encode_3)
References Base64::Encode(), refbase64data, and refdata.
TEST() [8/8]
TEST (TestBase64 , Encode_4)
References Base64::Encode(), refbase64data, and refdata.
Variable Documentation
refbase64data
const char refbase64data[] static
Initial value:
= "AQIDBAUGBwgJCgsMDQ4PEBESExQVFhcY"
                                    "GRobHB0eHyAhIiMkJSYnKCkqKywtLi8w"
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
refdata
const char refdata[] static
Initial value:
= "\x01\x02\x03\x04\x05\x06\x07\x08"
                              "\x09\x0a\x0b\x0c\x0d\x0e\x0f\x10"
                              "\x11\x12\x13\x14\x15\x16\x17\x18"
                              "\x19\x1a\x1b\x1c\x1d\x1e\x1f\x20"
                              "\x21\x22\x23\x24\x25\x26\x27\x28"
                              "\x29\x2a\x2b\x2c\x2d\x2e\x2f\x30"
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().