Kodi Documentation: XFILE::CFileStream Class Reference
XFILE::CFileStream Class Reference
#include <File.h>
Public Member Functions
CFileStream (int backsize=0)
~CFileStream () override
bool Open (const std::string &filename)
bool Open (const CURL &filename)
void Close ()
int64_t GetLength ()
Private Attributes
CFileStreamBuffer m_buffer
std::unique_ptr< IFile > m_file
Constructor & Destructor Documentation
CFileStream()
CFileStream::CFileStream (int backsize = 0) explicit
~CFileStream()
CFileStream::~CFileStream () override
References Close().
Member Function Documentation
Close()
void CFileStream::Close ()
References XFILE::CFileStreamBuffer::Detach(), m_buffer, and m_file.
Referenced by Open(), and ~CFileStream().
GetLength()
int64_t CFileStream::GetLength ()
References m_file.
Open() [1/2]
bool CFileStream::Open (const CURL & filename)
References XFILE::CFileStreamBuffer::Attach(), CPasswordManager::AuthenticateURL(), Close(), XFILE::CFileFactory::CreateLoader(), CPasswordManager::GetInstance(), CURL::GetUserName(), m_buffer, m_file, and URIUtils::SubstitutePath().
Open() [2/2]
bool CFileStream::Open (const std::string & filename)
References Open().
Referenced by Open().
Member Data Documentation
m_buffer
CFileStreamBuffer XFILE::CFileStream::m_buffer private
Referenced by Close(), and Open().
m_file
std::unique_ptr<IFile> XFILE::CFileStream::m_file private
Referenced by Close(), GetLength(), and Open().
The documentation for this class was generated from the following files:
filesystem/File.h
filesystem/File.cpp