Kodi Documentation: CGUIKeyboardFactory Class Reference
CGUIKeyboardFactory Class Reference
#include <GUIKeyboardFactory.h>
Public Member Functions
CGUIKeyboardFactory (void)
virtual ~CGUIKeyboardFactory (void)
Static Public Member Functions
static bool ShowAndGetInput (std::string &aTextString, bool allowEmptyResult, unsigned int autoCloseMs=0)
static bool ShowAndGetInput (std::string &aTextString, const CVariant &heading, bool allowEmptyResult, bool hiddenInput=false, unsigned int autoCloseMs=0)
static bool ShowAndGetNewPassword (std::string &strNewPassword, unsigned int autoCloseMs=0)
static bool ShowAndGetNewPassword (std::string &newPassword, const CVariant &heading, bool allowEmpty, unsigned int autoCloseMs=0)
static bool ShowAndVerifyNewPassword (std::string &strNewPassword, unsigned int autoCloseMs=0)
static bool ShowAndVerifyNewPassword (std::string &newPassword, const CVariant &heading, bool allowEmpty, unsigned int autoCloseMs=0)
static int ShowAndVerifyPassword (std::string &strPassword, const std::string &strHeading, int iRetries, unsigned int autoCloseMs=0)
static bool ShowAndGetFilter (std::string &aTextString, bool searching, unsigned int autoCloseMs=0)
static bool SendTextToActiveKeyboard (const std::string &aTextString, bool closeKeyboard=false)
static bool isKeyboardActivated ()
Static Private Member Functions
static void keyTypedCB (CGUIKeyboard *ref, const std::string &typedString)
Static Private Attributes
static CGUIKeyboard * g_activeKeyboard = NULL
static FILTERING m_filtering = FILTERING_NONE
Constructor & Destructor Documentation
CGUIKeyboardFactory()
CGUIKeyboardFactory::CGUIKeyboardFactory (void) default
~CGUIKeyboardFactory()
CGUIKeyboardFactory::~CGUIKeyboardFactory (void) virtual default
Member Function Documentation
isKeyboardActivated()
static bool CGUIKeyboardFactory::isKeyboardActivated () inline static
References g_activeKeyboard.
Referenced by ADDON::Interface_GUIDialogKeyboard::is_keyboard_activated().
keyTypedCB()
void CGUIKeyboardFactory::keyTypedCB (CGUIKeyboard * ref, const std::string & typedString) static private
References FILTERING_CURRENT, FILTERING_NONE, FILTERING_SEARCH, CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), CGUIKeyboard::GetWindowId(), GUI_MSG_FILTER_ITEMS, GUI_MSG_NOTIFY_ALL, GUI_MSG_SEARCH_UPDATE, m_filtering, CGUIKeyboard::resetAutoCloseTimer(), CGUIMessage::SetParam1(), and CGUIMessage::SetStringParam().
Referenced by ShowAndGetInput().
SendTextToActiveKeyboard()
bool CGUIKeyboardFactory::SendTextToActiveKeyboard (const std::string & aTextString, bool closeKeyboard = false) static
References g_activeKeyboard, and CGUIKeyboard::SetTextToKeyboard().
Referenced by ADDON::Interface_GUIDialogKeyboard::send_text_to_active_keyboard(), and JSONRPC::CInputOperations::SendText().
ShowAndGetFilter()
bool CGUIKeyboardFactory::ShowAndGetFilter (std::string & aTextString, bool searching, unsigned int autoCloseMs = 0) static
References FILTERING_CURRENT, FILTERING_NONE, FILTERING_SEARCH, m_filtering, and ShowAndGetInput().
Referenced by CGUIMediaWindow::Filter(), CGUIEditControl::OnClick(), CGUIWindowMusicNav::OnClick(), CGUIWindowMusicNav::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), and ADDON::Interface_GUIDialogKeyboard::show_and_get_filter().
ShowAndGetInput() [1/2]
bool CGUIKeyboardFactory::ShowAndGetInput (std::string & aTextString, bool allowEmptyResult, unsigned int autoCloseMs = 0) static
References ShowAndGetInput().
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonNewGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonRenameGroup(), FAVOURITES_UTILS::ChooseAndSetNewName(), anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), CGUIDialogVideoManager::ChooseVideoAsset(), XBMCAddon::xbmc::Keyboard::doModal(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CGUIDialogVideoInfo::GetSetForMovie(), XBMCAddon::xbmcgui::Dialog::input(), CGUIEditControl::OnClick(), CGUIControlListSetting::OnClick(), CGUIWindowVideoNav::OnClick(), CGUIDialogFileBrowser::OnMessage(), PVR::CGUIDialogPVRGuideSearch::OnMessage(), CGUIDialogSubtitles::OnMessage(), CGUIDialogSmartPlaylistEditor::OnName(), CGUIWindowFileManager::OnNewFolder(), CGUIDialogSmartPlaylistEditor::OnOK(), CGUIDialogMediaSource::OnPath(), KODI::GAME::CDialogInGameSaves::OnRename(), KODI::GAME::CDialogGameSaves::OnRename(), CGUIWindowMusicPlaylistEditor::OnSavePlaylist(), CGUIWindowVideoBase::OnSearch(), XFILE::IDirectory::ProcessRequirements(), CFileUtils::RenameFile(), PVR::CPVRGUIActionsEPG::RenameSavedSearch(), CGUIWindowMusicPlayList::SavePlayList(), CGUIWindowVideoPlaylist::SavePlayList(), SetString(), ADDON::Interface_GUIDialogKeyboard::show_and_get_input(), ADDON::Interface_GUIDialogKeyboard::show_and_get_input_with_head(), ShowAndGetFilter(), ShowAndGetInput(), ShowAndGetNewPassword(), ShowAndVerifyNewPassword(), ShowAndVerifyPassword(), CGUIDialogProfileSettings::ShowForProfile(), MUSIC_UTILS::ShowSelectArtTypeDialog(), MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo(), CGUIDialogVideoInfo::UpdateVideoItemSortTitle(), CGUIDialogVideoInfo::UpdateVideoItemTitle(), and CVideoLibraryRefreshingJob::Work().
ShowAndGetInput() [2/2]
bool CGUIKeyboardFactory::ShowAndGetInput (std::string & aTextString, const CVariant & heading, bool allowEmptyResult, bool hiddenInput = false, unsigned int autoCloseMs = 0) static
References CVariant::asInteger(), CVariant::asString(), g_activeKeyboard, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CDarwinEmbedKeyboard::hasExternalKeyboard(), CVariant::isInteger(), CVariant::isString(), keyTypedCB(), CSettings::SETTING_INPUT_TVOSUSEKODIKEYBOARD, CGUIKeyboard::ShowAndGetInput(), CGUIKeyboard::startAutoCloseTimer(), WINDOW_DIALOG_KEYBOARD, and WINDOW_DIALOG_KEYBOARD_TOUCH.
ShowAndGetNewPassword() [1/2]
bool CGUIKeyboardFactory::ShowAndGetNewPassword (std::string & newPassword, const CVariant & heading, bool allowEmpty, unsigned int autoCloseMs = 0) static
References ShowAndGetInput().
ShowAndGetNewPassword() [2/2]
bool CGUIKeyboardFactory::ShowAndGetNewPassword (std::string & strNewPassword, unsigned int autoCloseMs = 0) static
References ShowAndGetNewPassword().
Referenced by ADDON::Interface_GUIDialogKeyboard::show_and_get_new_password(), ADDON::Interface_GUIDialogKeyboard::show_and_get_new_password_with_head(), and ShowAndGetNewPassword().
ShowAndVerifyNewPassword() [1/2]
bool CGUIKeyboardFactory::ShowAndVerifyNewPassword (std::string & newPassword, const CVariant & heading, bool allowEmpty, unsigned int autoCloseMs = 0) static
References ShowAndGetInput(), and KODI::MESSAGING::HELPERS::ShowOKDialogText().
ShowAndVerifyNewPassword() [2/2]
bool CGUIKeyboardFactory::ShowAndVerifyNewPassword (std::string & strNewPassword, unsigned int autoCloseMs = 0) static
References g_localizeStrings, CLocalizeStrings::Get(), and ShowAndVerifyNewPassword().
Referenced by XBMCAddon::xbmcgui::Dialog::input(), CGUIDialogLockSettings::OnSettingAction(), ADDON::Interface_GUIDialogKeyboard::show_and_verify_new_password(), ADDON::Interface_GUIDialogKeyboard::show_and_verify_new_password_with_head(), and ShowAndVerifyNewPassword().
ShowAndVerifyPassword()
int CGUIKeyboardFactory::ShowAndVerifyPassword (std::string & strPassword, const std::string & strHeading, int iRetries, unsigned int autoCloseMs = 0) static
Todo:
GUI Setting to enable disable this feature y/n?
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetSettingsComponent(), CSettings::SETTING_MASTERLOCK_MAXRETRIES, and ShowAndGetInput().
Referenced by XBMCAddon::xbmcgui::Dialog::input(), ADDON::Interface_GUIDialogKeyboard::show_and_verify_password(), and CGUIPassword::VerifyPassword().
Member Data Documentation
g_activeKeyboard
CGUIKeyboard * CGUIKeyboardFactory::g_activeKeyboard = NULL static private
Referenced by isKeyboardActivated(), SendTextToActiveKeyboard(), and ShowAndGetInput().
m_filtering
FILTERING CGUIKeyboardFactory::m_filtering = FILTERING_NONE static private
Referenced by keyTypedCB(), and ShowAndGetFilter().
The documentation for this class was generated from the following files:
GUIKeyboardFactory.h
GUIKeyboardFactory.cpp