Kodi Documentation: ILanguageInvoker Class Reference
ILanguageInvoker Class Reference abstract
#include <ILanguageInvoker.h>
Public Member Functions
ILanguageInvoker (ILanguageInvocationHandler *invocationHandler)
virtual ~ILanguageInvoker ()
virtual bool Execute (const std::string &script, const std::vector< std::string > &arguments=std::vector< std::string >())
virtual bool Stop (bool abort=false)
virtual bool IsStopping () const
void SetId (int id)
int GetId () const
const ADDON::AddonPtr & GetAddon () const
void SetAddon (const ADDON::AddonPtr &addon)
InvokerState GetState () const
bool IsActive () const
bool IsRunning () const
void Reset ()
Protected Member Functions
virtual void AbortNotification ()
virtual bool execute (const std::string &script, const std::vector< std::string > &arguments)=0
virtual bool stop (bool abort)=0
virtual void pulseGlobalEvent ()
virtual bool onExecutionInitialized ()
virtual void onExecutionFailed ()
virtual void onExecutionDone ()
virtual void onExecutionFinalized ()
void setState (InvokerState state)
Protected Attributes
ADDON::AddonPtr m_addon
Private Attributes
int m_id = -1
InvokerState m_state = InvokerStateUninitialized
ILanguageInvocationHandler * m_invocationHandler
Friends
class CLanguageInvokerThread
Constructor & Destructor Documentation
ILanguageInvoker()
ILanguageInvoker::ILanguageInvoker (ILanguageInvocationHandler * invocationHandler) explicit
~ILanguageInvoker()
ILanguageInvoker::~ILanguageInvoker () virtual default
Member Function Documentation
AbortNotification()
void ILanguageInvoker::AbortNotification () protected virtual
Called to notify the script is aborting.
References m_invocationHandler, and ILanguageInvocationHandler::NotifyScriptAborting().
Referenced by CPythonInvoker::stop().
execute()
virtual bool ILanguageInvoker::execute (const std::string & script, const std::vector< std::string > & arguments) protected pure virtual
Implemented in CLanguageInvokerThread, and CPythonInvoker.
Referenced by Execute().
Execute()
bool ILanguageInvoker::Execute (const std::string & script, const std::vector< std::string > & arguments = std::vector<std::string>()) virtual
Reimplemented in CPythonInvoker.
References execute(), m_invocationHandler, and ILanguageInvocationHandler::OnScriptStarted().
Referenced by CPythonInvoker::Execute().
GetAddon()
const ADDON::AddonPtr & ILanguageInvoker::GetAddon () const inline
References m_addon.
GetId()
int ILanguageInvoker::GetId () const inline
References m_id.
Referenced by CPythonInvoker::Execute(), CPythonInvoker::execute(), XBPython::NotifyScriptAborting(), CLanguageInvokerThread::OnException(), CPythonInvoker::onExecutionDone(), XBPython::OnExecutionEnded(), CPythonInvoker::onExecutionFailed(), CLanguageInvokerThread::OnExit(), CPythonInvoker::onInitialization(), CPythonInvoker::onPythonModuleInitialization(), CContextItemAddonInvoker::onPythonModuleInitialization(), XBPython::OnScriptStarted(), CLanguageInvokerThread::OnStartup(), CPythonInvoker::stop(), and CPythonInvoker::~CPythonInvoker().
GetState()
InvokerState ILanguageInvoker::GetState () const inline
References m_state.
Referenced by IsActive(), IsRunning(), IsStopping(), and CPythonInvoker::~CPythonInvoker().
IsActive()
bool ILanguageInvoker::IsActive () const
References GetState(), InvokerStateScriptDone, and InvokerStateUninitialized.
IsRunning()
bool ILanguageInvoker::IsRunning () const
References GetState(), and InvokerStateRunning.
Referenced by CPythonInvoker::stop().
IsStopping()
bool ILanguageInvoker::IsStopping () const virtual
Reimplemented in CPythonInvoker.
References GetState(), and InvokerStateStopping.
Referenced by CPythonInvoker::IsStopping().
onExecutionDone()
void ILanguageInvoker::onExecutionDone () protected virtual
Reimplemented in CPythonInvoker.
References m_invocationHandler, and ILanguageInvocationHandler::OnExecutionEnded().
Referenced by CPythonInvoker::onExecutionDone().
onExecutionFailed()
void ILanguageInvoker::onExecutionFailed () protected virtual
Reimplemented in CPythonInvoker.
References m_invocationHandler, and ILanguageInvocationHandler::OnExecutionEnded().
Referenced by CPythonInvoker::onExecutionFailed().
onExecutionFinalized()
void ILanguageInvoker::onExecutionFinalized () protected virtual
References m_invocationHandler, and ILanguageInvocationHandler::OnScriptFinalized().
Referenced by CPythonInvoker::~CPythonInvoker().
onExecutionInitialized()
bool ILanguageInvoker::onExecutionInitialized () protected virtual
References m_invocationHandler, and ILanguageInvocationHandler::OnScriptInitialized().
Referenced by CPythonInvoker::Execute().
pulseGlobalEvent()
void ILanguageInvoker::pulseGlobalEvent () protected virtual
References m_invocationHandler, and ILanguageInvocationHandler::PulseGlobalEvent().
Referenced by CPythonInvoker::stop(), and CPythonInvoker::~CPythonInvoker().
Reset()
void ILanguageInvoker::Reset () inline
References InvokerStateUninitialized, and m_state.
SetAddon()
void ILanguageInvoker::SetAddon (const ADDON::AddonPtr & addon) inline
References m_addon.
SetId()
void ILanguageInvoker::SetId (int id) inline
References id, and m_id.
setState()
void ILanguageInvoker::setState (InvokerState state) protected
References m_state.
Referenced by CPythonInvoker::execute(), CPythonInvoker::onExecutionDone(), CPythonInvoker::onExecutionFailed(), and CPythonInvoker::stop().
stop()
virtual bool ILanguageInvoker::stop (bool abort) protected pure virtual
Implemented in CPythonInvoker, and CLanguageInvokerThread.
Referenced by Stop().
Stop()
bool ILanguageInvoker::Stop (bool abort = false) virtual
References stop().
Referenced by CLanguageInvokerThread::~CLanguageInvokerThread(), and CPythonInvoker::~CPythonInvoker().
Friends And Related Symbol Documentation
CLanguageInvokerThread
friend class CLanguageInvokerThread friend
Member Data Documentation
m_addon
ADDON::AddonPtr ILanguageInvoker::m_addon protected
Referenced by CPythonInvoker::execute(), CHTTPPythonWsgiInvoker::executeScript(), GetAddon(), CPythonInvoker::onError(), CPythonInvoker::onPythonModuleInitialization(), CLanguageInvokerThread::OnStartup(), SetAddon(), and CPythonInvoker::stop().
m_id
int ILanguageInvoker::m_id = -1 private
Referenced by GetId(), and SetId().
m_invocationHandler
ILanguageInvocationHandler* ILanguageInvoker::m_invocationHandler private
Referenced by AbortNotification(), Execute(), onExecutionDone(), onExecutionFailed(), onExecutionFinalized(), onExecutionInitialized(), and pulseGlobalEvent().
m_state
InvokerState ILanguageInvoker::m_state = InvokerStateUninitialized private
Referenced by GetState(), Reset(), and setState().
The documentation for this class was generated from the following files:
ILanguageInvoker.h
ILanguageInvoker.cpp