Kodi Documentation: CPyThreadState Class Reference
CPyThreadState Class Reference
#include <pythreadstate.h>
Public Member Functions
CPyThreadState (bool save=true)
~CPyThreadState ()
void Save ()
void Restore ()
Private Attributes
PyThreadState * m_threadState
Constructor & Destructor Documentation
CPyThreadState()
CPyThreadState::CPyThreadState (bool save = true) inline explicit
References m_threadState, and Save().
~CPyThreadState()
CPyThreadState::~CPyThreadState () inline
References Restore().
Member Function Documentation
Restore()
void CPyThreadState::Restore () inline
References m_threadState.
Referenced by CPythonInvoker::execute(), GilSafeSingleLock::GilSafeSingleLock(), and ~CPyThreadState().
Save()
void CPyThreadState::Save () inline
References m_threadState.
Referenced by CPyThreadState().
Member Data Documentation
m_threadState
PyThreadState* CPyThreadState::m_threadState private
Referenced by CPyThreadState(), Restore(), and Save().
The documentation for this class was generated from the following file:
pythreadstate.h