Kodi Documentation: CFilesystemInstaller Class Reference
CFilesystemInstaller Class Reference
#include <FilesystemInstaller.h>
Public Member Functions
CFilesystemInstaller ()
bool InstallToFilesystem (const std::string &archive, const std::string &addonId)
bool UnInstallFromFilesystem (const std::string &addonPath)
Static Private Member Functions
static bool UnpackArchive (std::string path, const std::string &dest)
Private Attributes
std::string m_addonFolder
std::string m_tempFolder
Detailed Description
Responsible for safely unpacking/copying/removing addon files from/to the addon folder.
Constructor & Destructor Documentation
CFilesystemInstaller()
CFilesystemInstaller::CFilesystemInstaller ()
Member Function Documentation
InstallToFilesystem()
bool CFilesystemInstaller::InstallToFilesystem (const std::string & archive, const std::string & addonId)
Parameters
archive Absolute path to zip file to install.
addonId
Returns
true on success, otherwise false.
References URIUtils::AddFileToFolder(), XFILE::CDirectory::Create(), XFILE::CDirectory::Exists(), CLog::Log(), LOGERROR, LOGWARNING, m_addonFolder, m_tempFolder, XFILE::CDirectory::RemoveRecursive(), XFILE::CFile::Rename(), and UnpackArchive().
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install().
UnInstallFromFilesystem()
bool CFilesystemInstaller::UnInstallFromFilesystem (const std::string & addonPath)
References URIUtils::AddFileToFolder(), CLog::Log(), LOGERROR, LOGWARNING, m_tempFolder, XFILE::CDirectory::RemoveRecursive(), and XFILE::CFile::Rename().
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::DoWork().
UnpackArchive()
bool CFilesystemInstaller::UnpackArchive (std::string path, const std::string & dest) static private
References CFileOperationJob::ActionCopy, CFileItemList::Clear(), URIUtils::CreateArchivePath(), XFILE::DIR_FLAG_DEFAULTS, CFileOperationJob::DoWork(), CURL::Get(), XFILE::CDirectory::GetDirectory(), CFileItem::GetPath(), URIUtils::IsProtocol(), CLog::Log(), LOGDEBUG, CGUIListItem::m_bIsFolder, and CFileItemList::Size().
Referenced by InstallToFilesystem().
Member Data Documentation
m_addonFolder
std::string CFilesystemInstaller::m_addonFolder private
Referenced by InstallToFilesystem().
m_tempFolder
std::string CFilesystemInstaller::m_tempFolder private
Referenced by InstallToFilesystem(), and UnInstallFromFilesystem().
The documentation for this class was generated from the following files:
FilesystemInstaller.h
FilesystemInstaller.cpp