Kodi Documentation: KODI::RETRO::CRPProcessInfoWin Class Reference
KODI::RETRO::CRPProcessInfoWin Class Reference
#include <RPProcessInfoWin.h>
Public Member Functions
CRPProcessInfoWin ()
Public Member Functions inherited from KODI::RETRO::CRPProcessInfo
virtual ~CRPProcessInfo ()
const std::string & GetPlatformName () const
Get the descriptive name of the platform.
std::string GetRenderSystemName (IRenderBufferPool *renderBufferPool) const
Get the descriptive name of the rendering system.
CRPBaseRenderer * CreateRenderer (IRenderBufferPool *renderBufferPool, const CRenderSettings &renderSettings)
Create a renderer.
void SetDataCache (CDataCacheCore *cache)
Set data cache.
void ResetInfo ()
Reset data cache info.
CRenderContext & GetRenderContext ()
Get the context shared by the rendering system.
CRenderBufferManager & GetBufferManager ()
Get the buffer manager that owns the buffer pools.
bool HasScalingMethod (SCALINGMETHOD scalingMethod) const
Check if a buffer pool supports the given scaling method.
SCALINGMETHOD GetDefaultScalingMethod () const
Get the default scaling method for this rendering system.
void SetVideoPixelFormat (AVPixelFormat pixFormat)
void SetVideoDimensions (int width, int height)
void SetVideoFps (float fps)
void SetAudioChannels (const std::string &channels)
void SetAudioSampleRate (int sampleRate)
void SetAudioBitsPerSample (int bitsPerSample)
void SetSpeed (float speed)
void SetPlayTimes (time_t start, int64_t current, int64_t min, int64_t max)
Static Public Member Functions
static std::unique_ptr< CRPProcessInfo > Create ()
static void Register ()
Static Public Member Functions inherited from KODI::RETRO::CRPProcessInfo
static std::unique_ptr< CRPProcessInfo > CreateInstance ()
static void RegisterProcessControl (const CreateRPProcessControl &createFunc)
static void RegisterRendererFactory (IRendererFactory *factory)
Additional Inherited Members
Protected Member Functions inherited from KODI::RETRO::CRPProcessInfo
CRPProcessInfo (std::string platformName)
}
Static Protected Member Functions inherited from KODI::RETRO::CRPProcessInfo
static std::vector< SCALINGMETHOD > GetScalingMethods ()
Get all scaling methods available to the rendering system.
Protected Attributes inherited from KODI::RETRO::CRPProcessInfo
const std::string m_platformName
CDataCacheCore * m_dataCache = nullptr
std::unique_ptr< CRenderBufferManager > m_renderBufferManager
Static Protected Attributes inherited from KODI::RETRO::CRPProcessInfo
static CreateRPProcessControl m_processControl = nullptr
static std::vector< std::unique_ptr< IRendererFactory > > m_rendererFactories
static CCriticalSection m_createSection
Constructor & Destructor Documentation
CRPProcessInfoWin()
CRPProcessInfoWin::CRPProcessInfoWin ()
Member Function Documentation
Create()
std::unique_ptr< CRPProcessInfo > CRPProcessInfoWin::Create () static
Referenced by Register().
Register()
void CRPProcessInfoWin::Register () static
References Create(), and KODI::RETRO::CRPProcessInfo::RegisterProcessControl().
Referenced by CRenderSystemDX::InitRenderSystem().
The documentation for this class was generated from the following files:
RPProcessInfoWin.h
RPProcessInfoWin.cpp