Kodi Documentation: CSaveFileState Class Reference
CSaveFileState Class Reference
#include <SaveFileStateJob.h>
Static Public Member Functions
static void DoWork (CFileItem &item, CBookmark &bookmark, bool updatePlayCount)
Member Function Documentation
DoWork()
void CSaveFileState::DoWork (CFileItem & item, CBookmark & bookmark, bool updatePlayCount) static
Todo:
check possible failure of BeginTransaction
Todo:
handle db failures to maintain data integrity
References CVideoDatabase::AddBookMarkToFile(), CVariant::asString(), ANNOUNCEMENT::AudioLibrary, CDatabase::BeginTransaction(), CVideoDatabase::ClearBookMarksOfFile(), CGUIListItem::ClearProperty(), CDatabase::Close(), CVideoDatabase::CommitTransaction(), CUtil::ConvertSecsToMilliSecs(), data(), CUtil::DeleteVideoDatabaseDirectoryCache(), EPISODES, PVR::CPVRManager::Get(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppComponents(), MUSIC_INFO::CMusicInfoTag::GetDatabaseId(), CFileItem::GetDynPath(), CServiceBroker::GetGUI(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CServiceBroker::GetPVRManager(), CVideoInfoTag::GetResumePoint(), CVideoDatabase::GetResumePoint(), CFileItem::GetStartOffset(), CVideoDatabase::GetStreamDetails(), MUSIC_INFO::CMusicInfoTag::GetType(), CFileItem::GetVideoContentType(), CFileItem::GetVideoInfoTag(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_ITEM, CGUIListItem::HasProperty(), CVideoInfoTag::HasStreamDetails(), CFileItem::HasVideoInfoTag(), CGUIListItem::ICON_OVERLAY_WATCHED, CVideoInfoTag::IncrementPlayCount(), CMusicDatabase::IncrementPlayCount(), CVideoDatabase::IncrementPlayCount(), KODI::MUSIC::IsAudio(), KODI::MUSIC::IsAudioBook(), URIUtils::IsBluray(), KODI::VIDEO::IsBlurayPlaylist(), CFileItem::IsInProgressPVRRecording(), CFileItem::IsLiveTV(), KODI::MUSIC::IsMusicDb(), URIUtils::IsPlugin(), CFileItem::IsPVRRecording(), URIUtils::IsUPnP(), CDateTime::IsValid(), KODI::VIDEO::IsVideo(), KODI::VIDEO::IsVideoDb(), CVideoDatabase::LoadVideoInfo(), CLog::Log(), LOGDEBUG, LOGWARNING, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_streamDetails, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_type, MOVIES, CMusicDatabase::Open(), CVideoDatabase::Open(), CBookmark::RESUME, CDatabase::RollbackTransaction(), UPNP::CUPnP::SaveFileState(), CVideoDatabase::SetFileForEpisode(), CVideoDatabase::SetFileForMovie(), CGUIListItem::SetOverlayImage(), CFileItem::SetPath(), CMusicDatabase::SetResumeBookmarkForAudioBook(), CVideoInfoTag::SetResumePoint(), CVideoDatabase::SetStreamDetailsForFile(), CBookmark::timeInSeconds, CVideoDatabase::UpdateLastPlayed(), and ANNOUNCEMENT::VideoLibrary.
Referenced by CApplicationPlayerCallback::OnPlayerCloseFile().
The documentation for this class was generated from the following files:
SaveFileStateJob.h
SaveFileStateJob.cpp