Kodi Documentation: CoreAudioHelpers.cpp File Reference
CoreAudioHelpers.cpp File Reference
#include "CoreAudioHelpers.h"
#include <sstream>
Functions
std::string GetError (OSStatus error)
const char * StreamDescriptionToString (AudioStreamBasicDescription desc, std::string &str)
Function Documentation
GetError()
std::string GetError (OSStatus error)
Referenced by CCoreAudioDevice::AddIOProc(), CCoreAudioHardware::FindAudioDevice(), CCoreAudioHardware::GetAutoHogMode(), CCoreAudioDevice::GetBufferSize(), CCoreAudioHardware::GetDefaultOutputDevice(), CCoreAudioDevice::GetMixingSupport(), CCoreAudioDevice::GetName(), CCoreAudioDevice::GetNominalSampleRate(), CCoreAudioDevice::GetNumChannelsOfStream(), CCoreAudioHardware::GetOutputDevices(), CCoreAudioDevice::GetPreferredChannelLayout(), CCoreAudioDevice::GetPreferredChannelLayoutForStereo(), CCoreAudioDevice::GetTotalOutputChannels(), CCoreAudioDevice::RemoveIOProc(), CCoreAudioDevice::RemoveObjectListenerProc(), CCoreAudioHardware::SetAutoHogMode(), CCoreAudioDevice::SetBufferSize(), CCoreAudioDevice::SetCurrentVolume(), CCoreAudioDevice::SetHogStatus(), CCoreAudioDevice::SetMixingSupport(), CCoreAudioDevice::SetNominalSampleRate(), CCoreAudioDevice::SetObjectListenerProc(), CCoreAudioStream::SetPhysicalFormat(), CCoreAudioStream::SetVirtualFormat(), CCoreAudioDevice::Start(), and CCoreAudioDevice::Stop().
StreamDescriptionToString()
const char * StreamDescriptionToString (AudioStreamBasicDescription desc, std::string & str)
Referenced by CCoreAudioStream::Close(), AEDeviceEnumerationOSX::FindSuitableFormatForStream(), CCoreAudioStream::HardwareStreamListener(), CAESinkDARWINOSX::Initialize(), CAESinkDARWINTVOS::Initialize(), CCoreAudioStream::SetPhysicalFormat(), CAAudioUnitSink::setupAudio(), and CCoreAudioStream::SetVirtualFormat().