Kodi Documentation: CGUITextureGL Class Reference
CGUITextureGL Class Reference
#include <GUITextureGL.h>
Classes
struct PackedVertex
Public Member Functions
CGUITextureGL (float posX, float posY, float width, float height, const CTextureInfo &texture)
~CGUITextureGL () override=default
CGUITextureGL * Clone () const override
Public Member Functions inherited from CGUITexture
virtual ~CGUITexture ()=default
bool Process (unsigned int currentTime)
void Render (int32_t depthOffset=0, int32_t overrideDepth=-1)
void DynamicResourceAlloc (bool bOnOff)
bool AllocResources ()
void FreeResources (bool immediately=false)
void SetInvalid ()
bool SetVisible (bool visible)
bool SetAlpha (unsigned char alpha)
bool SetDiffuseColor (KODI::UTILS::COLOR::Color color, const CGUIListItem *item=nullptr)
bool SetPosition (float x, float y)
bool SetWidth (float width)
bool SetHeight (float height)
bool SetFileName (const std::string &filename)
void SetUseCache (const bool useCache=true)
bool SetAspectRatio (const CAspectRatio &aspect)
const std::string & GetFileName () const
float GetTextureWidth () const
float GetTextureHeight () const
float GetWidth () const
float GetHeight () const
float GetXPosition () const
float GetYPosition () const
int GetOrientation () const
const CRect & GetRenderRect () const
bool IsLazyLoaded () const
KODI::GUILIB::GUIINFO::CGUIInfoColor GetDiffuseColor () const
Get the diffuse color (info color) associated to this texture.
bool HitTest (const CPoint &point) const
bool IsAllocated () const
bool FailedToAlloc () const
bool ReadyToRender () const
Static Public Member Functions
static void Register ()
static CGUITexture * CreateTexture (float posX, float posY, float width, float height, const CTextureInfo &texture)
static void DrawQuad (const CRect &coords, KODI::UTILS::COLOR::Color color, CTexture *texture=nullptr, const CRect *texCoords=nullptr, const float depth=1.0, const bool blending=true)
Static Public Member Functions inherited from CGUITexture
static void Register (const CreateGUITextureFunc &createFunction, const DrawQuadFunc &drawQuadFunction)
static CGUITexture * CreateTexture (float posX, float posY, float width, float height, const CTextureInfo &texture)
static void DrawQuad (const CRect &coords, KODI::UTILS::COLOR::Color color, CTexture *texture=nullptr, const CRect *texCoords=nullptr, const float depth=1.0, const bool blending=true)
Protected Member Functions
void Begin (KODI::UTILS::COLOR::Color color) override
called after our textures have been freed
void Draw (float *x, float *y, float *z, const CRect &texture, const CRect &diffuse, int orientation) override
void End () override
Protected Member Functions inherited from CGUITexture
CGUITexture (float posX, float posY, float width, float height, const CTextureInfo &texture)
CGUITexture (const CGUITexture &left)
bool CalculateSize ()
bool AllocateOnDemand ()
bool UpdateAnimFrame (unsigned int currentTime)
void Render (float left, float top, float right, float bottom, float u1, float v1, float u2, float v2, float u3, float v3)
void ResetAnimState ()
virtual void Allocate ()
virtual void Free ()
called after our textures have been allocated
Private Member Functions
CGUITextureGL (const CGUITextureGL &texture)=default
Private Attributes
std::array< GLubyte, 4 > m_col
std::vector< PackedVertex > m_packedVertices
std::vector< GLushort > m_idx
CRenderSystemGL * m_renderSystem
Additional Inherited Members
Protected Types inherited from CGUITexture
enum ALLOCATE_TYPE {
NO = 0 , NORMAL , LARGE , NORMAL_FAILED ,
LARGE_FAILED
}
Static Protected Member Functions inherited from CGUITexture
static void OrientateTexture (CRect &rect, float width, float height, int orientation)
Protected Attributes inherited from CGUITexture
bool m_visible
KODI::UTILS::COLOR::Color m_diffuseColor
float m_posX
float m_posY
float m_width
float m_height
float m_depth {0}
CRect m_vertex
bool m_invalid
bool m_use_cache
unsigned char m_alpha
float m_frameWidth
float m_frameHeight
float m_texCoordsScaleU
float m_texCoordsScaleV
int m_currentLoop
unsigned int m_currentFrame
uint32_t m_lasttime
float m_diffuseU
float m_diffuseV
float m_diffuseScaleU
float m_diffuseScaleV
CPoint m_diffuseOffset
bool m_allocateDynamically
ALLOCATE_TYPE m_isAllocated
CTextureInfo m_info
CAspectRatio m_aspect
CTextureArray m_diffuse
CTextureArray m_texture
Constructor & Destructor Documentation
CGUITextureGL() [1/2]
CGUITextureGL::CGUITextureGL (float posX, float posY, float width, float height, const CTextureInfo & texture)
References CServiceBroker::GetRenderSystem(), and m_renderSystem.
~CGUITextureGL()
CGUITextureGL::~CGUITextureGL () override default
CGUITextureGL() [2/2]
CGUITextureGL::CGUITextureGL (const CGUITextureGL & texture) private default
Member Function Documentation
Begin()
void CGUITextureGL::Begin (KODI::UTILS::COLOR::Color color) override protected virtual
called after our textures have been freed
Implements CGUITexture.
References KODI::UTILS::GL::A, KODI::UTILS::GL::B, CTexture::BindToUnit(), color, CRenderSystemGL::EnableShader(), KODI::UTILS::GL::G, KODI::UTILS::GL::GetChannelFromARGB(), CTexture::LoadToGPU(), m_col, CGUITexture::m_currentFrame, CGUITexture::m_diffuse, m_idx, m_packedVertices, m_renderSystem, CGUITexture::m_texture, CTextureArray::m_textures, KODI::UTILS::GL::R, CTextureArray::size(), SM_MULTI, SM_MULTI_BLENDCOLOR, SM_TEXTURE, and SM_TEXTURE_NOBLEND.
Clone()
CGUITextureGL * CGUITextureGL::Clone () const override virtual
Implements CGUITexture.
CreateTexture()
CGUITexture * CGUITextureGL::CreateTexture (float posX, float posY, float width, float height, const CTextureInfo & texture) static
Referenced by Register().
Draw()
void CGUITextureGL::Draw (float * x, float * y, float * z, const CRect & texture, const CRect & diffuse, int orientation) override protected virtual
Implements CGUITexture.
References CGUITexture::m_diffuse, m_idx, CGUITexture::m_info, m_packedVertices, CTextureInfo::orientation, CTextureArray::size(), CGUITextureGL::PackedVertex::u1, CGUITextureGL::PackedVertex::u2, CGUITextureGL::PackedVertex::v1, CGUITextureGL::PackedVertex::v2, CGUITextureGL::PackedVertex::x, CRectGen< T >::x1, CRectGen< T >::x2, CGUITextureGL::PackedVertex::y, CRectGen< T >::y1, CRectGen< T >::y2, and CGUITextureGL::PackedVertex::z.
DrawQuad()
void CGUITextureGL::DrawQuad (const CRect & coords, KODI::UTILS::COLOR::Color color, CTexture * texture = nullptr, const CRect * texCoords = nullptr, const float depth = 1.0, const bool blending = true) static
References KODI::UTILS::GL::A, KODI::UTILS::GL::B, CTexture::BindToUnit(), color, CRenderSystemGL::DisableShader(), CRenderSystemGL::EnableShader(), KODI::UTILS::GL::G, KODI::UTILS::GL::GetChannelFromARGB(), CServiceBroker::GetRenderSystem(), CTexture::LoadToGPU(), KODI::UTILS::GL::R, CRenderSystemGL::ShaderGetCoord0(), CRenderSystemGL::ShaderGetDepth(), CRenderSystemGL::ShaderGetPos(), CRenderSystemGL::ShaderGetUniCol(), SM_DEFAULT, SM_TEXTURE, CGUITextureGL::PackedVertex::u1, CGUITextureGL::PackedVertex::v1, VerifyGLState, CGUITextureGL::PackedVertex::x, CRectGen< T >::x1, CRectGen< T >::x2, CGUITextureGL::PackedVertex::y, CRectGen< T >::y1, CRectGen< T >::y2, and CGUITextureGL::PackedVertex::z.
Referenced by Register().
End()
void CGUITextureGL::End () override protected virtual
Implements CGUITexture.
References CRenderSystemGL::DisableShader(), m_col, CGUITexture::m_depth, CGUITexture::m_diffuse, m_idx, m_packedVertices, m_renderSystem, CRenderSystemGL::ShaderGetCoord0(), CRenderSystemGL::ShaderGetCoord1(), CRenderSystemGL::ShaderGetDepth(), CRenderSystemGL::ShaderGetPos(), CRenderSystemGL::ShaderGetUniCol(), and CTextureArray::size().
Register()
void CGUITextureGL::Register () static
References CreateTexture(), DrawQuad(), and CGUITexture::Register().
Referenced by CRenderSystemGL::InitRenderSystem().
Member Data Documentation
m_col
std::array<GLubyte, 4> CGUITextureGL::m_col private
Referenced by Begin(), and End().
m_idx
std::vector<GLushort> CGUITextureGL::m_idx private
Referenced by Begin(), Draw(), and End().
m_packedVertices
std::vector<PackedVertex> CGUITextureGL::m_packedVertices private
Referenced by Begin(), Draw(), and End().
m_renderSystem
CRenderSystemGL* CGUITextureGL::m_renderSystem private
Referenced by Begin(), CGUITextureGL(), and End().
The documentation for this class was generated from the following files:
GUITextureGL.h
GUITextureGL.cpp