Kodi Documentation: HTML::CHTMLUtil Class Reference
HTML::CHTMLUtil Class Reference
#include <HTMLUtil.h>
Public Member Functions
CHTMLUtil (void)
virtual ~CHTMLUtil (void)
Static Public Member Functions
static void RemoveTags (std::string &strHTML)
static void ConvertHTMLToW (const std::wstring &strHTML, std::wstring &strStripped)
Constructor & Destructor Documentation
CHTMLUtil()
CHTMLUtil::CHTMLUtil (void) default
~CHTMLUtil()
CHTMLUtil::~CHTMLUtil (void) virtual default
Member Function Documentation
ConvertHTMLToW()
void CHTMLUtil::ConvertHTMLToW (const std::wstring & strHTML, std::wstring & strStripped) static
Todo:
STRING_CLEANUP
References mappings.
Referenced by CScraperParser::Clean(), CDVDSubtitleTagSami::ConvertLine(), XFILE::CShoutcastFile::DecodeToUTF8(), XFILE::CHTTPDirectory::GetDirectory(), CRssReader::GetNewsItems(), and TEST().
RemoveTags()
void CHTMLUtil::RemoveTags (std::string & strHTML) static
Referenced by CWebVTTHandler::CalculateTextPosition(), CScraperParser::Clean(), ParseItemMRSS(), ParseItemRSS(), and TEST().
The documentation for this class was generated from the following files:
HTMLUtil.h
HTMLUtil.cpp