Kodi Documentation: KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL Class Reference
KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL Class Reference
#include <WinSystemWaylandEGLContextGL.h>
Classes
struct delete_CVaapiProxy
Public Member Functions
CRenderSystemBase * GetRenderSystem () override
bool InitWindowSystem () override
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext
CWinSystemWaylandEGLContext ()
~CWinSystemWaylandEGLContext () override=default
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override
bool DestroyWindow () override
bool DestroyWindowSystem () override
bool BindTextureUploadContext () override
Binds a shared context to the current thread, in order to upload textures asynchronously.
bool UnbindTextureUploadContext () override
Unbinds the shared context.
bool HasContext () override
Checks if a graphics context is already bound to the current thread.
Public Member Functions inherited from KODI::WINDOWING::LINUX::CWinSystemEGL
CWinSystemEGL (EGLenum platform, std::string const &platformExtension)
~CWinSystemEGL ()=default
EGLDisplay GetEGLDisplay () const
EGLSurface GetEGLSurface () const
EGLContext GetEGLContext () const
EGLConfig GetEGLConfig () const
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::CWinSystemWayland
CWinSystemWayland ()
~CWinSystemWayland () noexcept override
const std::string GetName () override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
void FinishModeChange (RESOLUTION res) override
void FinishWindowResize (int newWidth, int newHeight) override
bool UseLimitedColor () override
void UpdateResolutions () override
bool CanDoWindowed () override
bool Minimize () override
bool HasCursor () override
void ShowOSMouse (bool show) override
std::string GetClipboardText () override
float GetSyncOutputRefreshRate ()
float GetDisplayLatency () override
Get average display latency.
float GetFrameLatencyAdjustment () override
Get time that should be subtracted from the display latency for this frame in milliseconds.
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
CSignalRegistration RegisterOnPresentationFeedback (const PresentationFeedbackHandler &handler)
std::vector< std::string > GetConnectedOutputs () override
bool MessagePump () override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppFocusChange (bool bGaining)
virtual void NotifyAppActiveChange (bool bActivated)
virtual bool HasInertialGestures ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual bool Restore ()
virtual bool Hide ()
virtual bool Show (bool raise=true)
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual bool SetHDR (const VideoPicture *videoPicture)
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
virtual bool IsHDRDisplay ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual CHDRCapabilities GetDisplayHDRCapabilities () const
virtual float GetGuiSdrPeakLuminance () const
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::IInputHandler
virtual ~IInputHandler ()=default
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::IWindowDecorationHandler
virtual ~IWindowDecorationHandler ()=default
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::IShellSurfaceHandler
virtual ~IShellSurfaceHandler ()=default
Public Member Functions inherited from CRenderSystemGL
CRenderSystemGL ()
~CRenderSystemGL () override
bool InitRenderSystem () override
bool DestroyRenderSystem () override
bool ResetRenderSystem (int width, int height) override
bool BeginRender () override
bool EndRender () override
void PresentRender (bool rendered, bool videoLayer) override
void InvalidateColorBuffer () override
bool ClearBuffers (KODI::UTILS::COLOR::Color color) override
bool IsExtSupported (const char *extension) const override
void SetVSync (bool vsync)
void ResetVSync ()
void SetViewPort (const CRect &viewPort) override
void GetViewPort (CRect &viewPort) override
bool ScissorsCanEffectClipping () override
CRect ClipRectToScissorRect (const CRect &rect) override
void SetScissors (const CRect &rect) override
void ResetScissors () override
void SetDepthCulling (DEPTH_CULLING culling) override
void CaptureStateBlock () override
void ApplyStateBlock () override
void SetCameraPosition (const CPoint &camera, int screenWidth, int screenHeight, float stereoFactor=0.0f) override
void SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view) override
bool SupportsStereo (RENDER_STEREO_MODE mode) const override
bool SupportsNPOT (bool dxt) const override
void Project (float &x, float &y, float &z) override
std::string GetShaderPath (const std::string &filename) override
void GetGLVersion (int &major, int &minor)
void GetGLSLVersion (int &major, int &minor)
void ResetGLErrors ()
void EnableShader (ShaderMethodGL method)
void DisableShader ()
GLint ShaderGetPos ()
GLint ShaderGetCol ()
GLint ShaderGetCoord0 ()
GLint ShaderGetCoord1 ()
GLint ShaderGetDepth ()
GLint ShaderGetUniCol ()
GLint ShaderGetModel ()
GLint ShaderGetMatrix ()
GLint ShaderGetClip ()
GLint ShaderGetCoordStep ()
Public Member Functions inherited from CRenderSystemBase
CRenderSystemBase ()
virtual ~CRenderSystemBase ()
virtual void RestoreViewPort ()
void GetRenderVersion (unsigned int &major, unsigned int &minor) const
const std::string & GetRenderVendor () const
const std::string & GetRenderRenderer () const
const std::string & GetRenderVersionString () const
unsigned int GetMaxTextureSize () const
unsigned int GetMinDXTPitch () const
virtual void ShowSplash (const std::string &message)
Static Public Member Functions
static void Register ()
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Protected Member Functions
bool CreateContext () override
void SetContextSize (CSizeInt size) override
void SetVSyncImpl (bool enable) override
void PresentRenderImpl (bool rendered) override
Protected Member Functions inherited from KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext
bool InitWindowSystemEGL (EGLint renderableType, EGLint apiType)
CSizeInt GetNativeWindowAttachedSize ()
void PresentFrame (bool rendered)
Protected Member Functions inherited from KODI::WINDOWING::WAYLAND::CWinSystemWayland
std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl () override
CSizeInt GetBufferSize () const
std::unique_ptr< CConnection > const & GetConnection ()
wayland::surface_t GetMainSurface ()
IShellSurface * GetShellSurface ()
void PrepareFramePresentation ()
void FinishFramePresentation ()
virtual IShellSurface * CreateShellSurface (const std::string &name)
void OnConfigure (std::uint32_t serial, CSizeInt size, IShellSurface::StateBitset state) override
void OnClose () override
virtual std::unique_ptr< CSeat > CreateSeat (std::uint32_t name, wayland::seat_t &seat)
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
Protected Member Functions inherited from CRenderSystemGL
void CalculateMaxTexturesize ()
void InitialiseShaders ()
void ReleaseShaders ()
Protected Attributes
std::unique_ptr< CVaapiProxy, delete_CVaapiProxy > m_vaapiProxy
Protected Attributes inherited from KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext
wayland::egl_window_t m_nativeWindow
Protected Attributes inherited from KODI::WINDOWING::LINUX::CWinSystemEGL
CEGLContextUtils m_eglContext
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Protected Attributes inherited from CRenderSystemGL
bool m_bVsyncInit = false
int m_width
int m_height
std::string m_RenderExtensions
int m_glslMajor = 0
int m_glslMinor = 0
GLint m_viewPort [4]
std::map< ShaderMethodGL, std::unique_ptr< CGLShader > > m_pShader
ShaderMethodGL m_method = ShaderMethodGL::SM_DEFAULT
GLuint m_vertexArray = GL_NONE
Protected Attributes inherited from CRenderSystemBase
bool m_bRenderCreated
bool m_bVSync
unsigned int m_maxTextureSize
unsigned int m_minDXTPitch
std::string m_RenderRenderer
std::string m_RenderVendor
std::string m_RenderVersion
int m_RenderVersionMinor
int m_RenderVersionMajor
RENDER_STEREO_VIEW m_stereoView = RENDER_STEREO_VIEW_OFF
RENDER_STEREO_MODE m_stereoMode = RENDER_STEREO_MODE_OFF
bool m_limitedColorRange = false
bool m_transferPQ {false}
std::unique_ptr< CGUIImage > m_splashImage
std::unique_ptr< CGUITextLayout > m_splashMessageLayout
Additional Inherited Members
Public Types inherited from KODI::WINDOWING::WAYLAND::CWinSystemWayland
using PresentationFeedbackHandler = std::function< void(timespec, std::uint32_t, std::uint32_t, float, std::uint64_t)>
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Member Function Documentation
CreateContext()
bool CWinSystemWaylandEGLContextGL::CreateContext () override protected virtual
Implements KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext.
References CEGLAttributesVec::Add(), CEGLContextUtils::CreateContext(), CLog::Log(), LOGERROR, LOGWARNING, and KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext.
CreateWinSystem()
std::unique_ptr< CWinSystemBase > CWinSystemWaylandEGLContextGL::CreateWinSystem () static
Referenced by Register().
GetRenderSystem()
CRenderSystemBase * KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::GetRenderSystem () inline override virtual
Reimplemented from CWinSystemBase.
InitWindowSystem()
bool CWinSystemWaylandEGLContextGL::InitWindowSystem () override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::CWinSystemWayland.
References CBufferObjectFactory::ClearBufferObjects(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetConnection(), CEGLContextUtils::GetEGLDisplay(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::InitWindowSystemEGL(), KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext, m_vaapiProxy, CLinuxRendererGL::Register(), CScreenshotSurfaceGL::Register(), CDMAHeapBufferObject::Register(), CUDMABufferObject::Register(), KODI::RETRO::CRPProcessInfo::RegisterRendererFactory(), KODI::WINDOWING::WAYLAND::VaapiProxyConfig(), KODI::WINDOWING::WAYLAND::VaapiProxyCreate(), and KODI::WINDOWING::WAYLAND::VAAPIRegister().
PresentRenderImpl()
void CWinSystemWaylandEGLContextGL::PresentRenderImpl (bool rendered) override protected virtual
Implements CRenderSystemGL.
References KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::PresentFrame().
Register()
void CWinSystemWaylandEGLContextGL::Register () static
References CreateWinSystem(), and KODI::WINDOWING::CWindowSystemFactory::RegisterWindowSystem().
Referenced by CPlatformFreebsd::InitStageOne(), and CPlatformLinux::InitStageOne().
SetContextSize()
void CWinSystemWaylandEGLContextGL::SetContextSize (CSizeInt size) override protected virtual
Reimplemented from KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext.
References LOGDEBUG, CRenderSystemGL::m_height, CRenderSystemGL::m_width, CRenderSystemGL::ResetRenderSystem(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::SetContextSize().
SetVSyncImpl()
void CWinSystemWaylandEGLContextGL::SetVSyncImpl (bool enable) override protected virtual
Implements CRenderSystemGL.
Member Data Documentation
m_vaapiProxy
std::unique_ptr<CVaapiProxy, delete_CVaapiProxy> KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::m_vaapiProxy protected
Referenced by InitWindowSystem().
The documentation for this class was generated from the following files:
WinSystemWaylandEGLContextGL.h
WinSystemWaylandEGLContextGL.cpp