Kodi Documentation: ADDON::CAddonInfo Class Reference
ADDON::CAddonInfo Class Reference
#include <AddonInfo.h>
Public Member Functions
CAddonInfo ()=default
CAddonInfo (std::string id, AddonType type)
void SetMainType (AddonType type)
void SetBinary (bool isBinary)
void SetLibName (const std::string &libname)
void SetPath (const std::string &path)
void AddExtraInfo (const std::string &idName, const std::string &value)
void SetLastUsed (const CDateTime &dateTime)
const std::string & ID () const
AddonType MainType () const
To get the main type of this addon.
bool HasType (AddonType type, bool mainOnly=false) const
To check addon contains a type.
const std::vector< CAddonType > & Types () const
To get all available types inside the addon.
const CAddonType * Type (AddonType type) const
The get for given addon type information and extension data.
bool ProvidesSubContent (AddonType content, AddonType mainType) const
bool ProvidesSeveralSubContents () const
const CAddonVersion & Version () const
const CAddonVersion & MinVersion () const
bool IsBinary () const
const CAddonVersion & DependencyMinVersion (const std::string &dependencyID) const
const CAddonVersion & DependencyVersion (const std::string &dependencyID) const
const std::string & Name () const
const std::string & License () const
const std::string & Summary () const
const std::string & Description () const
const std::string & LibName () const
const std::string & Author () const
const std::string & Source () const
const std::string & Website () const
const std::string & Forum () const
const std::string & EMail () const
const std::string & Path () const
const std::string & ProfilePath () const
const std::string & ChangeLog () const
const std::string & Icon () const
const ArtMap & Art () const
const std::vector< std::string > & Screenshots () const
const std::string & Disclaimer () const
const std::vector< DependencyInfo > & GetDependencies () const
AddonLifecycleState LifecycleState () const
const std::string & LifecycleStateDescription () const
const std::string & Origin () const
const std::string & OriginName () const
const InfoMap & ExtraInfo () const
bool MeetsVersion (const CAddonVersion &versionMin, const CAddonVersion &version) const
uint64_t PackageSize () const
CDateTime InstallDate () const
CDateTime LastUpdated () const
CDateTime LastUsed () const
bool SupportsMultipleInstances () const
AddonInstanceSupport InstanceUseType () const
bool SupportsAddonSettings () const
bool SupportsInstanceSettings () const
std::vector< AddonInstanceId > GetKnownInstanceIds () const
Static Public Member Functions
static std::string TranslateType (AddonType type, bool pretty=false)
Utilities to translate add-on parts to his requested part.
static std::string TranslateIconType (AddonType type)
static AddonType TranslateType (const std::string &string)
static AddonType TranslateSubContent (const std::string &content)
static AddonInstanceSupport InstanceSupportType (AddonType type)
Private Member Functions
const std::string & GetTranslatedText (const std::unordered_map< std::string, std::string > &locales) const
Private Attributes
std::string m_id
AddonType m_mainType {}
std::vector< CAddonType > m_types
CAddonVersion m_version
CAddonVersion m_minversion
bool m_isBinary = false
std::string m_name
std::string m_license
std::unordered_map< std::string, std::string > m_summary
std::unordered_map< std::string, std::string > m_description
std::string m_author
std::string m_source
std::string m_website
std::string m_forum
std::string m_email
std::string m_path
std::string m_profilePath
std::unordered_map< std::string, std::string > m_changelog
std::string m_icon
ArtMap m_art
std::vector< std::string > m_screenshots
std::unordered_map< std::string, std::string > m_disclaimer
std::vector< DependencyInfo > m_dependencies
AddonLifecycleState m_lifecycleState = AddonLifecycleState::NORMAL
std::unordered_map< std::string, std::string > m_lifecycleStateDescription
CDateTime m_installDate
CDateTime m_lastUpdated
CDateTime m_lastUsed
std::string m_origin
std::unique_ptr< std::string > m_originName
uint64_t m_packageSize = 0
std::string m_libname
InfoMap m_extrainfo
std::vector< std::string > m_platforms
AddonInstanceSupport m_addonInstanceSupportType {AddonInstanceSupport::SUPPORT_NONE}
bool m_supportsAddonSettings {false}
bool m_supportsInstanceSettings {false}
Friends
class CAddonInfoBuilder
class CAddonInfoBuilderFromDB
Constructor & Destructor Documentation
CAddonInfo() [1/2]
ADDON::CAddonInfo::CAddonInfo () default
CAddonInfo() [2/2]
ADDON::CAddonInfo::CAddonInfo (std::string id, AddonType type)
Member Function Documentation
AddExtraInfo()
void ADDON::CAddonInfo::AddExtraInfo (const std::string & idName, const std::string & value) inline
References m_extrainfo, and value.
Art()
const ArtMap & ADDON::CAddonInfo::Art () const inline
References m_art.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
Author()
const std::string & ADDON::CAddonInfo::Author () const inline
References m_author.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
ChangeLog()
const std::string & ADDON::CAddonInfo::ChangeLog () const inline
References GetTranslatedText(), and m_changelog.
DependencyMinVersion()
const CAddonVersion & ADDON::CAddonInfo::DependencyMinVersion (const std::string & dependencyID) const
References m_dependencies.
DependencyVersion()
const CAddonVersion & ADDON::CAddonInfo::DependencyVersion (const std::string & dependencyID) const
References m_dependencies.
Description()
const std::string & ADDON::CAddonInfo::Description () const inline
References GetTranslatedText(), and m_description.
Disclaimer()
const std::string & ADDON::CAddonInfo::Disclaimer () const inline
References GetTranslatedText(), and m_disclaimer.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
EMail()
const std::string & ADDON::CAddonInfo::EMail () const inline
References m_email.
ExtraInfo()
const InfoMap & ADDON::CAddonInfo::ExtraInfo () const inline
References m_extrainfo.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
Forum()
const std::string & ADDON::CAddonInfo::Forum () const inline
References m_forum.
GetDependencies()
const std::vector< DependencyInfo > & ADDON::CAddonInfo::GetDependencies () const inline
References m_dependencies.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
GetKnownInstanceIds()
std::vector< AddonInstanceId > ADDON::CAddonInfo::GetKnownInstanceIds () const
References ADDON::ADDON_FIRST_INSTANCE_ID, ADDON::ADDON_SINGLETON_INSTANCE_ID, XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::Exists(), XFILE::CDirectory::GetDirectory(), URIUtils::GetFileName(), m_id, m_supportsInstanceSettings, and URIUtils::RemoveExtension().
GetTranslatedText()
const std::string & ADDON::CAddonInfo::GetTranslatedText (const std::unordered_map< std::string, std::string > & locales) const private
References g_langInfo, and ADDON::KODI_ADDON_DEFAULT_LANGUAGE_CODE.
Referenced by ChangeLog(), Description(), Disclaimer(), LifecycleStateDescription(), and Summary().
HasType()
bool ADDON::CAddonInfo::HasType (AddonType type, bool mainOnly = false) const
To check addon contains a type.
Parameters
[in] type The to checked type identifier
[in] mainOnly to check only in first defined main addon inside addon.xml
Returns
true in case the wanted type is supported, false if not
References m_mainType, ProvidesSubContent(), and ADDON::UNKNOWN.
Icon()
const std::string & ADDON::CAddonInfo::Icon () const inline
References m_icon.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
ID()
const std::string & ADDON::CAddonInfo::ID () const inline
References m_id.
InstallDate()
CDateTime ADDON::CAddonInfo::InstallDate () const inline
References m_installDate.
InstanceSupportType()
AddonInstanceSupport ADDON::CAddonInfo::InstanceSupportType (AddonType type) static
References ADDON::SUPPORT_NONE, and ADDON::types.
Referenced by ADDON::CAddonInfoBuilder::ParseXML().
InstanceUseType()
AddonInstanceSupport ADDON::CAddonInfo::InstanceUseType () const inline
References m_addonInstanceSupportType.
IsBinary()
bool ADDON::CAddonInfo::IsBinary () const inline
References m_isBinary.
LastUpdated()
CDateTime ADDON::CAddonInfo::LastUpdated () const inline
References m_lastUpdated.
LastUsed()
CDateTime ADDON::CAddonInfo::LastUsed () const inline
References m_lastUsed.
LibName()
const std::string & ADDON::CAddonInfo::LibName () const inline
References m_libname.
License()
const std::string & ADDON::CAddonInfo::License () const inline
References m_license.
LifecycleState()
AddonLifecycleState ADDON::CAddonInfo::LifecycleState () const inline
References m_lifecycleState.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
LifecycleStateDescription()
const std::string & ADDON::CAddonInfo::LifecycleStateDescription () const inline
References GetTranslatedText(), and m_lifecycleStateDescription.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
MainType()
AddonType ADDON::CAddonInfo::MainType () const inline
To get the main type of this addon.
This is the first type defined in addon.xml.
Returns
The used main type of addon
References m_mainType.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
MeetsVersion()
bool ADDON::CAddonInfo::MeetsVersion (const CAddonVersion & versionMin, const CAddonVersion & version) const
References m_minversion, and m_version.
MinVersion()
const CAddonVersion & ADDON::CAddonInfo::MinVersion () const inline
References m_minversion.
Name()
const std::string & ADDON::CAddonInfo::Name () const inline
References m_name.
Origin()
const std::string & ADDON::CAddonInfo::Origin () const inline
References m_origin.
OriginName()
const std::string & ADDON::CAddonInfo::OriginName () const
References ADDON::CHOICE_NO, CServiceBroker::GetAddonMgr(), m_origin, and m_originName.
PackageSize()
uint64_t ADDON::CAddonInfo::PackageSize () const inline
References m_packageSize.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
Path()
const std::string & ADDON::CAddonInfo::Path () const inline
References m_path.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
ProfilePath()
const std::string & ADDON::CAddonInfo::ProfilePath () const inline
References m_profilePath.
ProvidesSeveralSubContents()
bool ADDON::CAddonInfo::ProvidesSeveralSubContents () const
References m_types, and ADDON::CAddonType::ProvidedSubContents().
ProvidesSubContent()
bool ADDON::CAddonInfo::ProvidesSubContent (AddonType content, AddonType mainType) const
References ADDON::content, m_types, and ADDON::UNKNOWN.
Referenced by HasType().
Screenshots()
const std::vector< std::string > & ADDON::CAddonInfo::Screenshots () const inline
References m_screenshots.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
SetBinary()
void ADDON::CAddonInfo::SetBinary (bool isBinary) inline
References m_isBinary.
SetLastUsed()
void ADDON::CAddonInfo::SetLastUsed (const CDateTime & dateTime) inline
References m_lastUsed.
SetLibName()
void ADDON::CAddonInfo::SetLibName (const std::string & libname) inline
References m_libname.
SetMainType()
void ADDON::CAddonInfo::SetMainType (AddonType type) inline
References m_mainType.
SetPath()
void ADDON::CAddonInfo::SetPath (const std::string & path) inline
References m_path.
Source()
const std::string & ADDON::CAddonInfo::Source () const inline
References m_source.
Summary()
const std::string & ADDON::CAddonInfo::Summary () const inline
References GetTranslatedText(), and m_summary.
SupportsAddonSettings()
bool ADDON::CAddonInfo::SupportsAddonSettings () const inline
References m_supportsAddonSettings.
SupportsInstanceSettings()
bool ADDON::CAddonInfo::SupportsInstanceSettings () const inline
References m_supportsInstanceSettings.
SupportsMultipleInstances()
bool ADDON::CAddonInfo::SupportsMultipleInstances () const
References m_addonInstanceSupportType, m_supportsInstanceSettings, ADDON::SUPPORT_MANDATORY, ADDON::SUPPORT_NONE, ADDON::SUPPORT_OPTIONAL, and ADDON::SUPPORT_SETTINGS.
TranslateIconType()
std::string ADDON::CAddonInfo::TranslateIconType (AddonType type) static
References ADDON::types.
Referenced by XFILE::GenerateGameListing(), XFILE::GenerateMainCategoryListing(), and XFILE::GenerateTypeListing().
TranslateSubContent()
AddonType ADDON::CAddonInfo::TranslateSubContent (const std::string & content) static
References ADDON::AUDIO, ADDON::content, ADDON::EXECUTABLE, ADDON::GAME, ADDON::IMAGE, ADDON::UNKNOWN, and ADDON::VIDEO.
Referenced by ADDON::CAddonType::SetProvides().
TranslateType() [1/2]
std::string ADDON::CAddonInfo::TranslateType (AddonType type, bool pretty = false) static
Utilities to translate add-on parts to his requested part.
static public helper functions
References g_localizeStrings, CLocalizeStrings::Get(), and ADDON::types.
Referenced by ADDON::CAddonDll::Create(), ADDON::Interface_GUIWindow::create(), CSettingAddon::Deserialize(), ADDON::CAddonDatabaseSerializer::DeserializeMetadata(), XFILE::CAddonsDirectory::FileItemFromAddon(), XFILE::GenerateCategoryListing(), XFILE::GenerateGameListing(), XFILE::GenerateMainCategoryListing(), XFILE::GenerateTypeListing(), ADDON::Interface_Base::get_addon_info(), XBMCAddon::xbmcaddon::Addon::getAddonInfo(), JSONRPC::CAddonsOperations::GetAddons(), XFILE::CAddonsDirectory::GetDirectory(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetLabel(), PERIPHERALS::CPeripherals::GetSettingsFromMappingsFile(), JSONRPC::CJSONRPC::Initialize(), ADDON::CAddonSettings::InitializeFromOldSettingAddon(), ADDON::CAddonDll::LoadDll(), OpenDefaultSettings(), ADDON::CAddonInfoBuilder::ParseXML(), ADDON::CAddonStatusHandler::Process(), CGUIWindowAddonBrowser::SelectAddonID(), Serialize(), JSONRPC::CSettingsOperations::SerializeSettingAddon(), SetAddon(), SetDefaultAddon(), SetFile(), and CGUIDialogAddonSettings::SetupView().
TranslateType() [2/2]
AddonType ADDON::CAddonInfo::TranslateType (const std::string & string) static
References ADDON::types, and ADDON::UNKNOWN.
Type()
const CAddonType * ADDON::CAddonInfo::Type (AddonType type) const
The get for given addon type information and extension data.
Parameters
[in] type The wanted type data
Returns
addon type class with CAddonExtensions as information
Note
This function return never a "nullptr", in case the wanted type is not supported, becomes a dummy of CAddonType given.
Example:
// To get <extension ... name="blablabla" /> from addon.xml
std::string name = Type(ADDON_...)->GetValue("@name").asString();
References m_types, and ADDON::UNKNOWN.
Referenced by ADDON::CAddonDatabaseSerializer::SerializeMetadata().
Types()
const std::vector< CAddonType > & ADDON::CAddonInfo::Types () const inline
To get all available types inside the addon.
To have all <extension point="..." /> defined in addon.xml inside a list.
Returns
List of all supported types
References m_types.
Version()
const CAddonVersion & ADDON::CAddonInfo::Version () const inline
References m_version.
Website()
const std::string & ADDON::CAddonInfo::Website () const inline
References m_website.
Friends And Related Symbol Documentation
CAddonInfoBuilder
friend class CAddonInfoBuilder friend
CAddonInfoBuilderFromDB
friend class CAddonInfoBuilderFromDB friend
Member Data Documentation
m_addonInstanceSupportType
AddonInstanceSupport ADDON::CAddonInfo::m_addonInstanceSupportType {AddonInstanceSupport::SUPPORT_NONE} private
Referenced by InstanceUseType(), and SupportsMultipleInstances().
m_art
ArtMap ADDON::CAddonInfo::m_art private
Referenced by Art().
m_author
std::string ADDON::CAddonInfo::m_author private
Referenced by Author().
m_changelog
std::unordered_map<std::string, std::string> ADDON::CAddonInfo::m_changelog private
Referenced by ChangeLog().
m_dependencies
std::vector<DependencyInfo> ADDON::CAddonInfo::m_dependencies private
Referenced by DependencyMinVersion(), DependencyVersion(), and GetDependencies().
m_description
std::unordered_map<std::string, std::string> ADDON::CAddonInfo::m_description private
Referenced by Description().
m_disclaimer
std::unordered_map<std::string, std::string> ADDON::CAddonInfo::m_disclaimer private
Referenced by Disclaimer().
m_email
std::string ADDON::CAddonInfo::m_email private
Referenced by EMail().
m_extrainfo
InfoMap ADDON::CAddonInfo::m_extrainfo private
Referenced by AddExtraInfo(), and ExtraInfo().
m_forum
std::string ADDON::CAddonInfo::m_forum private
Referenced by Forum().
m_icon
std::string ADDON::CAddonInfo::m_icon private
Referenced by Icon().
m_id
std::string ADDON::CAddonInfo::m_id private
Referenced by GetKnownInstanceIds(), and ID().
m_installDate
CDateTime ADDON::CAddonInfo::m_installDate private
Referenced by InstallDate().
m_isBinary
bool ADDON::CAddonInfo::m_isBinary = false private
Referenced by IsBinary(), and SetBinary().
m_lastUpdated
CDateTime ADDON::CAddonInfo::m_lastUpdated private
Referenced by LastUpdated().
m_lastUsed
CDateTime ADDON::CAddonInfo::m_lastUsed private
Referenced by LastUsed(), and SetLastUsed().
m_libname
std::string ADDON::CAddonInfo::m_libname private
Referenced by LibName(), and SetLibName().
m_license
std::string ADDON::CAddonInfo::m_license private
Referenced by License().
m_lifecycleState
AddonLifecycleState ADDON::CAddonInfo::m_lifecycleState = AddonLifecycleState::NORMAL private
Referenced by LifecycleState().
m_lifecycleStateDescription
std::unordered_map<std::string, std::string> ADDON::CAddonInfo::m_lifecycleStateDescription private
Referenced by LifecycleStateDescription().
m_mainType
AddonType ADDON::CAddonInfo::m_mainType {} private
Referenced by HasType(), MainType(), and SetMainType().
m_minversion
CAddonVersion ADDON::CAddonInfo::m_minversion private
Referenced by MeetsVersion(), and MinVersion().
m_name
std::string ADDON::CAddonInfo::m_name private
Referenced by Name().
m_origin
std::string ADDON::CAddonInfo::m_origin private
Referenced by Origin(), and OriginName().
m_originName
std::unique_ptr<std::string> ADDON::CAddonInfo::m_originName mutable private
Referenced by OriginName().
m_packageSize
uint64_t ADDON::CAddonInfo::m_packageSize = 0 private
Referenced by PackageSize().
m_path
std::string ADDON::CAddonInfo::m_path private
Referenced by Path(), and SetPath().
m_platforms
std::vector<std::string> ADDON::CAddonInfo::m_platforms private
m_profilePath
std::string ADDON::CAddonInfo::m_profilePath private
Referenced by ProfilePath().
m_screenshots
std::vector<std::string> ADDON::CAddonInfo::m_screenshots private
Referenced by Screenshots().
m_source
std::string ADDON::CAddonInfo::m_source private
Referenced by Source().
m_summary
std::unordered_map<std::string, std::string> ADDON::CAddonInfo::m_summary private
Referenced by Summary().
m_supportsAddonSettings
bool ADDON::CAddonInfo::m_supportsAddonSettings {false} private
Referenced by SupportsAddonSettings().
m_supportsInstanceSettings
bool ADDON::CAddonInfo::m_supportsInstanceSettings {false} private
Referenced by GetKnownInstanceIds(), SupportsInstanceSettings(), and SupportsMultipleInstances().
m_types
std::vector<CAddonType> ADDON::CAddonInfo::m_types private
Referenced by ProvidesSeveralSubContents(), ProvidesSubContent(), Type(), and Types().
m_version
CAddonVersion ADDON::CAddonInfo::m_version private
Referenced by MeetsVersion(), and Version().
m_website
std::string ADDON::CAddonInfo::m_website private
Referenced by Website().
The documentation for this class was generated from the following files:
AddonInfo.h
AddonInfo.cpp