Kodi Documentation: XFILE::CTVOSFile Class Reference
XFILE::CTVOSFile Class Reference
#include <TVOSFile.h>
Public Member Functions
CTVOSFile ()
~CTVOSFile ()
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int Stat (struct __stat64 *buffer) override
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
bool Delete (const CURL &url) override
bool Rename (const CURL &url, const CURL &urlnew) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
void Close () override
int64_t GetPosition () override
int64_t GetLength () override
int GetChunkSize () override
int IoControl (EIoControl request, void *param) override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual double GetDownloadSpeed ()
virtual bool SetHidden (const CURL &url, bool hidden)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Static Public Member Functions
static bool WantsFile (const CURL &url)
Protected Member Functions
int CacheStat (const CURL &url, struct __stat64 *buffer)
Protected Attributes
CURL m_url
int64_t m_position = -1
CPosixFile * m_pFallbackFile = nullptr
struct __stat64 m_cachedStat
Constructor & Destructor Documentation
CTVOSFile()
XFILE::CTVOSFile::CTVOSFile () inline
~CTVOSFile()
CTVOSFile::~CTVOSFile ()
References Close().
Member Function Documentation
CacheStat()
int CTVOSFile::CacheStat (const CURL & url, struct __stat64 * buffer) protected
References __stat64, CURL::Get(), CTVOSNSUserDefaults::GetKeyDataFromPath(), and S_IFREG.
Referenced by Open(), Stat(), and Write().
Close()
void CTVOSFile::Close () override virtual
Implements XFILE::IFile.
References XFILE::CPosixFile::Close(), m_cachedStat, m_pFallbackFile, m_position, m_url, and CURL::Reset().
Referenced by CPreflightHandler::MigrateUserdataXMLToNSUserDefaults(), and ~CTVOSFile().
Delete()
bool CTVOSFile::Delete (const CURL & url) override virtual
Reimplemented from XFILE::IFile.
References XFILE::CPosixFile::Delete(), CTVOSNSUserDefaults::DeleteKeyFromPath(), and CURL::Get().
Referenced by Rename().
Exists()
bool CTVOSFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References XFILE::CPosixFile::Exists(), CURL::Get(), and CTVOSNSUserDefaults::KeyFromPathExists().
Referenced by Rename().
GetChunkSize()
int CTVOSFile::GetChunkSize () override virtual
Reimplemented from XFILE::IFile.
References XFILE::IFile::GetChunkSize(), GetLength(), and m_pFallbackFile.
GetLength()
int64_t CTVOSFile::GetLength () override virtual
Implements XFILE::IFile.
References XFILE::CPosixFile::GetLength(), m_cachedStat, and m_pFallbackFile.
Referenced by GetChunkSize(), and Read().
GetPosition()
int64_t CTVOSFile::GetPosition () override virtual
Implements XFILE::IFile.
References XFILE::CPosixFile::GetPosition(), and m_pFallbackFile.
IoControl()
int CTVOSFile::IoControl (EIoControl request, void * param) override virtual
Reimplemented from XFILE::IFile.
References XFILE::CPosixFile::IoControl(), XFILE::IOCTRL_SEEK_POSSIBLE, and m_pFallbackFile.
Open()
bool CTVOSFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References CacheStat(), CURL::Get(), CTVOSNSUserDefaults::KeyFromPathExists(), m_cachedStat, m_pFallbackFile, m_position, m_url, and XFILE::CPosixFile::Open().
OpenForWrite()
bool CTVOSFile::OpenForWrite (const CURL & url, bool bOverWrite = false) override virtual
Reimplemented from XFILE::IFile.
References CURL::Get(), CTVOSNSUserDefaults::KeyFromPathExists(), m_position, m_url, and WantsFile().
Referenced by CPreflightHandler::MigrateUserdataXMLToNSUserDefaults().
Read()
ssize_t CTVOSFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References CURL::Get(), CTVOSNSUserDefaults::GetKeyDataFromPath(), GetLength(), m_pFallbackFile, m_position, m_url, and XFILE::CPosixFile::Read().
Rename()
bool CTVOSFile::Rename (const CURL & url, const CURL & urlnew) override virtual
Reimplemented from XFILE::IFile.
References Delete(), Exists(), CURL::Get(), CTVOSNSUserDefaults::GetKeyDataFromPath(), XFILE::CPosixFile::Rename(), CTVOSNSUserDefaults::SetKeyDataFromPath(), and WantsFile().
Seek()
int64_t CTVOSFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
References m_pFallbackFile, and XFILE::CPosixFile::Seek().
Stat() [1/2]
int CTVOSFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References CacheStat(), and XFILE::CPosixFile::Stat().
Stat() [2/2]
int CTVOSFile::Stat (struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about currently open file For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Reimplemented from XFILE::IFile.
References __stat64, and m_cachedStat.
WantsFile()
bool CTVOSFile::WantsFile (const CURL & url) static
References CURL::Get(), CURL::GetFileNameWithoutPath(), CURL::GetFileType(), and CTVOSNSUserDefaults::IsKeyFromPath().
Referenced by XFILE::CFileFactory::CreateLoader(), OpenForWrite(), and Rename().
Write()
ssize_t CTVOSFile::Write (const void * bufPtr, size_t bufSize) override virtual
Attempt to write bufSize bytes from buffer bufPtr into currently opened file.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully written bytes if any bytes were written, zero if no bytes were written and no detectable error occur, -1 in case of any explicit error
Reimplemented from XFILE::IFile.
References CacheStat(), CURL::Get(), m_cachedStat, m_pFallbackFile, m_position, m_url, CTVOSNSUserDefaults::SetKeyDataFromPath(), and XFILE::CPosixFile::Write().
Referenced by CPreflightHandler::MigrateUserdataXMLToNSUserDefaults().
Member Data Documentation
m_cachedStat
struct __stat64 XFILE::CTVOSFile::m_cachedStat protected
Referenced by Close(), GetLength(), Open(), Stat(), and Write().
m_pFallbackFile
CPosixFile* XFILE::CTVOSFile::m_pFallbackFile = nullptr protected
Referenced by Close(), GetChunkSize(), GetLength(), GetPosition(), IoControl(), Open(), Read(), Seek(), and Write().
m_position
int64_t XFILE::CTVOSFile::m_position = -1 protected
Referenced by Close(), Open(), OpenForWrite(), Read(), and Write().
m_url
CURL XFILE::CTVOSFile::m_url protected
Referenced by Close(), Open(), OpenForWrite(), Read(), and Write().
The documentation for this class was generated from the following files:
TVOSFile.h
TVOSFile.cpp