Kodi Documentation: PERIPHERALS::CPeripherals Class Reference
PERIPHERALS::CPeripherals Class Reference
#include <Peripherals.h>
Public Member Functions
CPeripherals (CInputManager &inputManager, KODI::GAME::CControllerManager &controllerProfiles)
~CPeripherals () override
void Initialise ()
Initialise the peripherals manager.
void Clear ()
Clear all data known by the peripherals manager.
PeripheralPtr GetPeripheralAtLocation (const std::string &strLocation, PeripheralBusType busType=PERIPHERAL_BUS_UNKNOWN) const
Get the instance of the peripheral at the given location.
bool HasPeripheralAtLocation (const std::string &strLocation, PeripheralBusType busType=PERIPHERAL_BUS_UNKNOWN) const
Check whether a peripheral is present at the given location.
PeripheralBusPtr GetBusWithDevice (const std::string &strLocation) const
Get the bus that holds the device with the given location.
bool SupportsFeature (PeripheralFeature feature) const
Check if any busses support the given feature.
int GetPeripheralsWithFeature (PeripheralVector &results, const PeripheralFeature feature, PeripheralBusType busType=PERIPHERAL_BUS_UNKNOWN) const
Get all peripheral instances that have the given feature.
size_t GetNumberOfPeripherals () const
bool HasPeripheralWithFeature (const PeripheralFeature feature, PeripheralBusType busType=PERIPHERAL_BUS_UNKNOWN) const
Check whether there is at least one device present with the given feature.
void OnDeviceAdded (const CPeripheralBus &bus, const CPeripheral &peripheral)
Called when a device has been added to a bus.
void OnDeviceDeleted (const CPeripheralBus &bus, const CPeripheral &peripheral)
Called when a device has been deleted from a bus.
void CreatePeripheral (CPeripheralBus &bus, const PeripheralScanResult &result)
Creates a new instance of a peripheral.
void GetSettingsFromMapping (CPeripheral &peripheral) const
Add the settings that are defined in the mappings file to the peripheral (if there is anything defined).
void TriggerDeviceScan (const PeripheralBusType type=PERIPHERAL_BUS_UNKNOWN)
Trigger a device scan on all known busses.
PeripheralBusPtr GetBusByType (const PeripheralBusType type) const
Get the instance of a bus given it's type.
void GetDirectory (const std::string &strPath, CFileItemList &items) const
Get all fileitems for a path.
PeripheralPtr GetByPath (const std::string &strPath) const
Get the instance of a peripheral given it's path.
bool OnAction (const CAction &action)
Try to let one of the peripherals handle an action.
bool IsMuted ()
Check whether there's a peripheral that reports to be muted.
bool ToggleMute ()
Try to toggle the mute status via a peripheral.
bool ToggleDeviceState (const CecStateChange mode=STATE_SWITCH_TOGGLE)
Try to toggle the playing device state via a peripheral.
bool Mute ()
Try to mute the audio via a peripheral.
bool UnMute ()
Try to unmute the audio via a peripheral.
bool GetNextKeypress (float frameTime, CKey &key)
Try to get a keypress from a peripheral.
EventPollHandlePtr RegisterEventPoller ()
Register with the event scanner to control scan timing.
EventLockHandlePtr RegisterEventLock ()
Register with the event scanner to disable event processing.
void OnUserNotification ()
void TestFeature (PeripheralFeature feature)
Request peripherals with the specified feature to perform a quick test.
void PowerOffDevices ()
Request all devices with power-off support to power down.
bool SupportsCEC () const
void ProcessEvents (void) override
void EnableButtonMapping ()
Initialize button mapping.
PeripheralAddonPtr GetAddonWithButtonMap (const CPeripheral *device)
Get an add-on that can provide button maps for a device.
void ResetButtonMaps (const std::string &controllerId)
Reset all button maps to the defaults for all devices and the given controller.
void RegisterJoystickButtonMapper (KODI::JOYSTICK::IButtonMapper *mapper)
Register a button mapper interface.
void UnregisterJoystickButtonMapper (KODI::JOYSTICK::IButtonMapper *mapper)
Unregister a button mapper interface.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
void OnApplicationMessage (KODI::MESSAGING::ThreadMessage *pMsg) override
This gets called whenever a message matching the registered message mask is processed.
int GetMessageMask () override
Should return the message mask that it wishes to receive messages for.
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
CInputManager & GetInputManager ()
Access the input manager passed to the constructor.
KODI::GAME::CControllerManager & GetControllerProfiles ()
Access controller profiles through the construction parameter.
CCriticalSection & GetAddonInstallMutex ()
Get a mutex that allows for add-on install tasks to block on each other.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from Observable
Observable ()=default
virtual ~Observable ()=default
Observable & operator= (const Observable &observable)
virtual void RegisterObserver (Observer *obs)
Register an observer.
virtual void UnregisterObserver (Observer *obs)
Unregister an observer.
virtual void NotifyObservers (const ObservableMessage message=ObservableMessageNone)
Send a message to all observers when m_bObservableChanged is true.
virtual void SetChanged (bool bSetTo=true)
Mark an observable changed.
virtual bool IsObserving (const Observer &obs) const
Check whether this observable is being observed by an observer.
Public Member Functions inherited from KODI::MESSAGING::IMessageTarget
virtual ~IMessageTarget ()=default
Public Member Functions inherited from PERIPHERALS::IEventScannerCallback
virtual ~IEventScannerCallback (void)=default
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Private Member Functions
bool LoadMappings ()
bool GetMappingForDevice (const CPeripheralBus &bus, PeripheralScanResult &result) const
void OnDeviceChanged ()
Static Private Member Functions
static void GetSettingsFromMappingsFile (tinyxml2::XMLElement *xmlNode, std::map< std::string, PeripheralDeviceSetting > &m_settings)
Private Attributes
CInputManager & m_inputManager
KODI::GAME::CControllerManager & m_controllerProfiles
bool m_bMissingLibCecWarningDisplayed = false
std::vector< PeripheralBusPtr > m_busses
std::vector< PeripheralDeviceMapping > m_mappings
std::unique_ptr< CEventScanner > m_eventScanner
CCriticalSection m_critSectionBusses
CCriticalSection m_critSectionMappings
CCriticalSection m_addonInstallMutex
Additional Inherited Members
Protected Member Functions inherited from Observable
void SendMessage (const ObservableMessage message)
Send a message to all observer when m_bObservableChanged is true.
Protected Attributes inherited from Observable
std::atomic< bool > m_bObservableChanged {false}
std::vector< Observer * > m_observers
CCriticalSection m_obsCritSection
Constructor & Destructor Documentation
CPeripherals()
CPeripherals::CPeripherals (CInputManager & inputManager, KODI::GAME::CControllerManager & controllerProfiles) explicit
References CServiceBroker::GetSettingsComponent(), CSettings::SETTING_INPUT_CONTROLLERCONFIG, CSettings::SETTING_INPUT_PERIPHERALLIBRARIES, CSettings::SETTING_INPUT_PERIPHERALS, CSettings::SETTING_INPUT_TESTRUMBLE, and CSettings::SETTING_LOCALE_LANGUAGE.
~CPeripherals()
CPeripherals::~CPeripherals () override
References Clear(), and CServiceBroker::GetSettingsComponent().
Member Function Documentation
Announce()
void CPeripherals::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References ANNOUNCEMENT::CAnnouncementManager::ANNOUNCEMENT_SENDER, CServiceBroker::GetSettingsComponent(), PowerOffDevices(), and CSettings::SETTING_INPUT_CONTROLLERPOWEROFF.
Clear()
void CPeripherals::Clear ()
Clear all data known by the peripherals manager.
References CServiceBroker::GetAnnouncementManager(), m_bMissingLibCecWarningDisplayed, m_busses, m_critSectionBusses, m_critSectionMappings, m_eventScanner, and m_mappings.
Referenced by Initialise(), and ~CPeripherals().
CreatePeripheral()
void CPeripherals::CreatePeripheral (CPeripheralBus & bus, const PeripheralScanResult & result)
Creates a new instance of a peripheral.
Parameters
bus The bus on which this peripheral is present.
result The scan result from the device scanning code.
Returns
The new peripheral or NULL if it could not be created.
References g_localizeStrings, CLocalizeStrings::Get(), GetMappingForDevice(), CLog::Log(), LOGDEBUG, LOGWARNING, m_bMissingLibCecWarningDisplayed, PERIPHERALS::PeripheralScanResult::m_busType, PERIPHERALS::PeripheralScanResult::m_mappedType, PERIPHERALS::PeripheralScanResult::m_strLocation, PERIPHERALS::PERIPHERAL_BLUETOOTH, PERIPHERALS::PERIPHERAL_BUS_CEC, PERIPHERALS::PERIPHERAL_BUS_UNKNOWN, PERIPHERALS::PERIPHERAL_CEC, PERIPHERALS::PERIPHERAL_DISK, PERIPHERALS::PERIPHERAL_HID, PERIPHERALS::PERIPHERAL_IMON, PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERALS::PERIPHERAL_KEYBOARD, PERIPHERALS::PERIPHERAL_MOUSE, PERIPHERALS::PERIPHERAL_NIC, PERIPHERALS::PERIPHERAL_NYXBOARD, PERIPHERALS::PERIPHERAL_TUNER, CGUIDialogKaiToast::QueueNotification(), PERIPHERALS::CPeripheralBus::Register(), PERIPHERALS::CPeripheralBus::Type(), and CGUIDialogKaiToast::Warning.
Referenced by PERIPHERALS::CPeripheralBus::RegisterNewDevices().
EnableButtonMapping()
void CPeripherals::EnableButtonMapping ()
Initialize button mapping.
This command enables button mapping on all busses. Button maps allow connect events from the driver to the higher-level features used by controller profiles.
If user input is required, a blocking dialog may be shown.
References m_busses, and m_critSectionBusses.
Referenced by KODI::GAME::CGUIControllerWindow::OnInitWindow().
GetAddonInstallMutex()
CCriticalSection & PERIPHERALS::CPeripherals::GetAddonInstallMutex () inline
Get a mutex that allows for add-on install tasks to block on each other.
References m_addonInstallMutex.
Referenced by PERIPHERALS::CPeripheralJoystick::InstallAsync().
GetAddonWithButtonMap()
PeripheralAddonPtr CPeripherals::GetAddonWithButtonMap (const CPeripheral * device)
Get an add-on that can provide button maps for a device.
Returns
An add-on that provides button maps, or empty if no add-on is found
References GetBusByType(), and PERIPHERALS::PERIPHERAL_BUS_ADDON.
Referenced by PERIPHERALS::CAddonButtonMapping::CAddonButtonMapping(), PERIPHERALS::CPeripheralJoystick::InitialiseFeature(), PERIPHERALS::CPeripheral::RegisterInputHandler(), PERIPHERALS::CPeripheral::RegisterKeyboardHandler(), and PERIPHERALS::CPeripheral::RegisterMouseHandler().
GetBusByType()
PeripheralBusPtr CPeripherals::GetBusByType (const PeripheralBusType type) const
Get the instance of a bus given it's type.
Parameters
type The bus type.
Returns
The bus or NULL if it wasn't found.
References m_busses, and m_critSectionBusses.
Referenced by GetAddonWithButtonMap(), PERIPHERALS::CAddonButtonMap::Load(), and ResetButtonMaps().
GetBusWithDevice()
PeripheralBusPtr CPeripherals::GetBusWithDevice (const std::string & strLocation) const
Get the bus that holds the device with the given location.
Parameters
strLocation The location.
Returns
The bus or NULL if no device was found.
References m_busses, and m_critSectionBusses.
GetByPath()
PeripheralPtr CPeripherals::GetByPath (const std::string & strPath) const
Get the instance of a peripheral given it's path.
Parameters
strPath The path to the peripheral.
Returns
The peripheral or NULL if it wasn't found.
References PERIPHERALS::PeripheralTypeTranslator::BusTypeToString(), m_busses, and m_critSectionBusses.
Referenced by PERIPHERALS::CGUIDialogPeripheralSettings::InitializeSettings(), PERIPHERALS::CGUIDialogPeripheralSettings::OnResetSettings(), PERIPHERALS::CGUIDialogPeripheralSettings::OnSettingChanged(), PERIPHERALS::CGUIDialogPeripheralSettings::Save(), and PERIPHERALS::CGUIDialogPeripherals::Show().
GetControllerProfiles()
KODI::GAME::CControllerManager & PERIPHERALS::CPeripherals::GetControllerProfiles () inline
Access controller profiles through the construction parameter.
References m_controllerProfiles.
Referenced by PERIPHERALS::CPeripheralJoystick::ControllerProfile(), PERIPHERALS::CPeripheralKeyboard::ControllerProfile(), PERIPHERALS::CPeripheralMouse::ControllerProfile(), PERIPHERALS::CPeripheralAddon::FeatureCount(), PERIPHERALS::CPeripheralAddon::FeatureType(), PERIPHERALS::CPeripheralJoystick::InitializeControllerProfile(), PERIPHERALS::CPeripheralJoystick::InstallAsync(), and PERIPHERALS::CGUIDialogPeripheralSettings::OnSettingChanged().
GetDirectory()
void CPeripherals::GetDirectory (const std::string & strPath, CFileItemList & items) const
Get all fileitems for a path.
Parameters
strPath The path to the directory to get the items from.
items The item list.
References PERIPHERALS::PeripheralTypeTranslator::BusTypeToString(), m_busses, and m_critSectionBusses.
Referenced by KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), and PERIPHERALS::CGUIDialogPeripherals::UpdatePeripheralsSync().
GetInputManager()
CInputManager & PERIPHERALS::CPeripherals::GetInputManager () inline
Access the input manager passed to the constructor.
References m_inputManager.
Referenced by PERIPHERALS::CPeripheralHID::InitialiseFeature(), PERIPHERALS::CPeripheralJoystick::InitialiseFeature(), PERIPHERALS::CPeripheralKeyboard::InitialiseFeature(), PERIPHERALS::CPeripheralMouse::InitialiseFeature(), PERIPHERALS::CPeripheralJoystick::OnAxisMotion(), PERIPHERALS::CPeripheralJoystick::OnButtonMotion(), PERIPHERALS::CPeripheralJoystick::OnHatMotion(), PERIPHERALS::CPeripheralHID::~CPeripheralHID(), PERIPHERALS::CPeripheralKeyboard::~CPeripheralKeyboard(), and PERIPHERALS::CPeripheralMouse::~CPeripheralMouse().
GetMappingForDevice()
bool CPeripherals::GetMappingForDevice (const CPeripheralBus & bus, PeripheralScanResult & result) const private
References PERIPHERALS::PeripheralTypeTranslator::FormatHexString(), CLog::Log(), LOGDEBUG, m_critSectionMappings, PERIPHERALS::PeripheralScanResult::m_iProductId, PERIPHERALS::PeripheralScanResult::m_iVendorId, PERIPHERALS::PeripheralScanResult::m_mappedType, m_mappings, PERIPHERALS::PeripheralScanResult::m_strDeviceName, PERIPHERALS::PeripheralScanResult::m_type, PERIPHERALS::PERIPHERAL_BUS_UNKNOWN, PERIPHERALS::PERIPHERAL_UNKNOWN, PERIPHERALS::CPeripheralBus::Type(), and PERIPHERALS::PeripheralTypeTranslator::TypeToString().
Referenced by CreatePeripheral().
GetMessageMask()
int CPeripherals::GetMessageMask () override virtual
Should return the message mask that it wishes to receive messages for.
The message mask is defined in "messaging/ApplicationMessenger.h" pick the next one available when creating a new
Implements KODI::MESSAGING::IMessageTarget.
References TMSG_MASK_PERIPHERALS.
GetNextKeypress()
bool CPeripherals::GetNextKeypress (float frameTime, CKey & key)
Try to get a keypress from a peripheral.
Todo:
CEC only supports toggling the mute status at this time
Parameters
frameTime The current frametime.
key The fetched key.
Returns
True when a keypress was fetched, false otherwise.
References PERIPHERALS::FEATURE_CEC, GetPeripheralsWithFeature(), and SupportsCEC().
GetNumberOfPeripherals()
size_t CPeripherals::GetNumberOfPeripherals () const
References m_busses, and m_critSectionBusses.
Referenced by anonymous_namespace{SettingConditions.cpp}::HasPeripherals().
GetPeripheralAtLocation()
PeripheralPtr CPeripherals::GetPeripheralAtLocation (const std::string & strLocation, PeripheralBusType busType = PERIPHERAL_BUS_UNKNOWN) const
Get the instance of the peripheral at the given location.
Parameters
strLocation The location.
busType The bus to query. Default (PERIPHERAL_BUS_UNKNOWN) searches all busses.
Returns
The peripheral or NULL if it wasn't found.
References m_busses, m_critSectionBusses, and PERIPHERALS::PERIPHERAL_BUS_UNKNOWN.
Referenced by HasPeripheralAtLocation().
GetPeripheralsWithFeature()
int CPeripherals::GetPeripheralsWithFeature (PeripheralVector & results, const PeripheralFeature feature, PeripheralBusType busType = PERIPHERAL_BUS_UNKNOWN) const
Get all peripheral instances that have the given feature.
Parameters
results The list of results.
feature The feature to search for.
busType The bus to query. Default (PERIPHERAL_BUS_UNKNOWN) searches all busses.
Returns
The number of devices that have been found.
References m_busses, m_critSectionBusses, and PERIPHERALS::PERIPHERAL_BUS_UNKNOWN.
Referenced by GetNextKeypress(), HasPeripheralWithFeature(), IsMuted(), OnAction(), OnSettingChanged(), OnUserNotification(), KODI::GAME::CAgentInput::ProcessJoysticks(), KODI::GAME::CAgentInput::ProcessKeyboard(), KODI::GAME::CAgentInput::ProcessMouse(), RegisterJoystickButtonMapper(), ResetButtonMaps(), TestFeature(), ToggleDeviceState(), ToggleMute(), and UnregisterJoystickButtonMapper().
GetSettingsFromMapping()
void CPeripherals::GetSettingsFromMapping (CPeripheral & peripheral) const
Add the settings that are defined in the mappings file to the peripheral (if there is anything defined).
Parameters
peripheral The peripheral to get the settings for.
References PERIPHERALS::CPeripheral::AddSetting(), PERIPHERALS::CPeripheral::GetBusType(), m_critSectionMappings, m_mappings, PERIPHERALS::PERIPHERAL_BUS_UNKNOWN, PERIPHERALS::PERIPHERAL_UNKNOWN, PERIPHERALS::CPeripheral::ProductId(), PERIPHERALS::CPeripheral::Type(), and PERIPHERALS::CPeripheral::VendorId().
Referenced by PERIPHERALS::CPeripheral::Initialise(), and PERIPHERALS::CPeripheral::ResetDefaultSettings().
GetSettingsFromMappingsFile()
void CPeripherals::GetSettingsFromMappingsFile (tinyxml2::XMLElement * xmlNode, std::map< std::string, PeripheralDeviceSetting > & m_settings) static private
Todo:
add more types if needed
References XMLUtils::GetAttribute(), PERIPHERALS::PeripheralDeviceSetting::m_order, CSettingAddon::SetAddonType(), ADDON::CAddonInfo::TranslateType(), and value.
Referenced by LoadMappings().
HasPeripheralAtLocation()
bool CPeripherals::HasPeripheralAtLocation (const std::string & strLocation, PeripheralBusType busType = PERIPHERAL_BUS_UNKNOWN) const
Check whether a peripheral is present at the given location.
Parameters
strLocation The location.
busType The bus to query. Default (PERIPHERAL_BUS_UNKNOWN) searches all busses.
Returns
True when a peripheral was found, false otherwise.
References GetPeripheralAtLocation().
HasPeripheralWithFeature()
bool CPeripherals::HasPeripheralWithFeature (const PeripheralFeature feature, PeripheralBusType busType = PERIPHERAL_BUS_UNKNOWN) const
Check whether there is at least one device present with the given feature.
Parameters
feature The feature to check for.
busType The bus to query. Default (PERIPHERAL_BUS_UNKNOWN) searches all busses.
Returns
True when at least one device was found with this feature, false otherwise.
References GetPeripheralsWithFeature().
Referenced by anonymous_namespace{SettingConditions.cpp}::HasRumbleController().
Initialise()
void CPeripherals::Initialise ()
Initialise the peripherals manager.
References Clear(), XFILE::CDirectory::Create(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppMessenger(), LoadMappings(), m_busses, m_critSectionBusses, m_eventScanner, and ANNOUNCEMENT::Player.
IsMuted()
bool CPeripherals::IsMuted ()
Check whether there's a peripheral that reports to be muted.
Returns
True when at least one peripheral reports to be muted, false otherwise.
References PERIPHERALS::FEATURE_CEC, GetPeripheralsWithFeature(), and SupportsCEC().
LoadMappings()
bool CPeripherals::LoadMappings () private
References XMLUtils::GetAttribute(), PERIPHERALS::PeripheralTypeTranslator::GetBusTypeFromString(), GetSettingsFromMappingsFile(), PERIPHERALS::PeripheralTypeTranslator::GetTypeFromString(), PERIPHERALS::PeripheralTypeTranslator::HexStringToInt(), id, CXBMCTinyXML2::LoadFile(), LOGDEBUG, LOGERROR, LOGWARNING, PERIPHERALS::PeripheralDeviceMapping::m_busType, PERIPHERALS::PeripheralDeviceMapping::m_class, m_critSectionMappings, PERIPHERALS::PeripheralDeviceMapping::m_mappedTo, m_mappings, PERIPHERALS::PeripheralDeviceMapping::m_PeripheralID, PERIPHERALS::PeripheralDeviceMapping::m_settings, and PERIPHERALS::PeripheralDeviceMapping::m_strDeviceName.
Referenced by Initialise().
Mute()
bool PERIPHERALS::CPeripherals::Mute () inline
Try to mute the audio via a peripheral.
Returns
True when this change was handled by a peripheral (and should not be handled by anything else), false otherwise.
References ToggleMute().
OnAction()
bool CPeripherals::OnAction (const CAction & action)
Try to let one of the peripherals handle an action.
Parameters
action The change to handle.
Returns
True when this change was handled by a peripheral (and should not be handled by anything else), false otherwise.
References ACTION_MUTE, ACTION_VOLUME_DOWN, ACTION_VOLUME_UP, PERIPHERALS::FEATURE_CEC, GetPeripheralsWithFeature(), SupportsCEC(), and ToggleMute().
OnApplicationMessage()
void CPeripherals::OnApplicationMessage (KODI::MESSAGING::ThreadMessage * msg) override virtual
This gets called whenever a message matching the registered message mask is processed.
There are no ordering guarantees here so implementations should never rely on a certain ordering of messages.
Cleaning up any pointers stored in the message payload is not specified and is decided by the implementer of the message. In general prefer to delete any data in this method to keep the callsites cleaner and simpler but if data is to be passed back it's perfectly valid to handle it any way that fits the situation as long as it's documented along with the message.
To return a simple value the result parameter of
See also
ThreadMessage can be used as it will be used as the return value for
CApplicationMessenger::SendMsg. It is up to the implementer to decide if this is to be used and it should be documented along with any new message implemented.
Implements KODI::MESSAGING::IMessageTarget.
References KODI::MESSAGING::ThreadMessage::dwMessage, KODI::MESSAGING::ThreadMessage::lpVoid, PERIPHERALS::STATE_ACTIVATE_SOURCE, PERIPHERALS::STATE_STANDBY, PERIPHERALS::STATE_SWITCH_TOGGLE, TMSG_CECACTIVATESOURCE, TMSG_CECSTANDBY, TMSG_CECTOGGLESTATE, and ToggleDeviceState().
OnDeviceAdded()
void CPeripherals::OnDeviceAdded (const CPeripheralBus & bus, const CPeripheral & peripheral)
Called when a device has been added to a bus.
Parameters
bus The bus the device was added to.
peripheral The peripheral that has been added.
Todo:
Improve device notifications in v18
References PERIPHERALS::CPeripheral::DeviceName(), g_localizeStrings, CLocalizeStrings::Get(), CGUIDialogKaiToast::Info, OnDeviceChanged(), and CGUIDialogKaiToast::QueueNotification().
Referenced by PERIPHERALS::CPeripheralBus::Register(), and PERIPHERALS::CPeripheralBusAddon::Register().
OnDeviceChanged()
void CPeripherals::OnDeviceChanged () private
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_UPDATE, Observable::SetChanged(), and WINDOW_SETTINGS_SYSTEM.
Referenced by OnDeviceAdded(), and OnDeviceDeleted().
OnDeviceDeleted()
void CPeripherals::OnDeviceDeleted (const CPeripheralBus & bus, const CPeripheral & peripheral)
Called when a device has been deleted from a bus.
Parameters
bus The bus from which the device removed.
peripheral The peripheral that has been removed.
Todo:
Improve device notifications in v18
References PERIPHERALS::CPeripheral::DeviceName(), g_localizeStrings, CLocalizeStrings::Get(), CGUIDialogKaiToast::Info, OnDeviceChanged(), and CGUIDialogKaiToast::QueueNotification().
Referenced by PERIPHERALS::CPeripheralBus::UnregisterRemovedDevices(), and PERIPHERALS::CPeripheralBusAddon::UnregisterRemovedDevices().
OnSettingAction()
void CPeripherals::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References CGUIWindowManager::ActivateWindow(), ADDON::CHOICE_YES, PERIPHERALS::FEATURE_RUMBLE, CServiceBroker::GetAddonMgr(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), ADDON::PERIPHERALDLL, CGUIWindowAddonBrowser::SelectAddonID(), CSettings::SETTING_INPUT_CONTROLLERCONFIG, CSettings::SETTING_INPUT_PERIPHERALLIBRARIES, CSettings::SETTING_INPUT_PERIPHERALS, CSettings::SETTING_INPUT_TESTRUMBLE, PERIPHERALS::CGUIDialogPeripherals::Show(), CGUIDialogAddonSettings::ShowForAddon(), TestFeature(), and WINDOW_DIALOG_GAME_CONTROLLERS.
OnSettingChanged()
void CPeripherals::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References PERIPHERALS::FEATURE_CEC, GetPeripheralsWithFeature(), and CSettings::SETTING_LOCALE_LANGUAGE.
OnUserNotification()
void CPeripherals::OnUserNotification ()
References PERIPHERALS::FEATURE_RUMBLE, GetPeripheralsWithFeature(), CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_INPUT_RUMBLENOTIFY.
Referenced by CGUIDialogKaiToast::DoWork().
PowerOffDevices()
void CPeripherals::PowerOffDevices ()
Request all devices with power-off support to power down.
References PERIPHERALS::FEATURE_POWER_OFF, and TestFeature().
Referenced by Announce().
ProcessEvents()
void CPeripherals::ProcessEvents (void) override virtual
Implements PERIPHERALS::IEventScannerCallback.
References m_busses, and m_critSectionBusses.
RegisterEventLock()
EventLockHandlePtr CPeripherals::RegisterEventLock ()
Register with the event scanner to disable event processing.
Returns
A handle that unregisters itself when expired
References m_eventScanner.
Referenced by KODI::GAME::CGameClientInput::CloseJoystick(), KODI::GAME::CAgentInput::ProcessAgentControllers(), KODI::GAME::CAgentInput::Stop(), KODI::GAME::CAgentInput::UpdateConnectedJoysticks(), and KODI::GAME::CAgentInput::UpdateExpiredJoysticks().
RegisterEventPoller()
EventPollHandlePtr CPeripherals::RegisterEventPoller ()
Register with the event scanner to control scan timing.
Returns
A handle that unregisters itself when expired
References m_eventScanner.
Referenced by KODI::RETRO::CRetroPlayerInput::CRetroPlayerInput().
RegisterJoystickButtonMapper()
void CPeripherals::RegisterJoystickButtonMapper (KODI::JOYSTICK::IButtonMapper * mapper)
Register a button mapper interface.
Parameters
mapper The button mapper
Clients implementing the IButtonMapper interface call CPeripherals::RegisterJoystickButtonMapper to register themselves as eligible for button mapping commands.
When registering the mapper is forwarded to all peripherals. See CPeripheral::RegisterJoystickButtonMapper for what is done to the mapper after being given to the peripheral.
References PERIPHERALS::FEATURE_JOYSTICK, PERIPHERALS::FEATURE_KEYBOARD, PERIPHERALS::FEATURE_MOUSE, and GetPeripheralsWithFeature().
Referenced by KODI::GAME::CGUIDialogButtonCapture::InstallHooks(), KODI::GAME::CGUIConfigurationWizard::InstallHooks(), KODI::GAME::CGUIDialogButtonCapture::Notify(), and KODI::GAME::CGUIConfigurationWizard::Notify().
ResetButtonMaps()
void CPeripherals::ResetButtonMaps (const std::string & controllerId)
Reset all button maps to the defaults for all devices and the given controller.
Parameters
controllerId The controller profile to reset
Todo:
Add a device parameter to allow resetting button maps per-device
References PERIPHERALS::FEATURE_JOYSTICK, GetBusByType(), GetPeripheralsWithFeature(), PERIPHERALS::PERIPHERAL_BUS_ADDON, and PERIPHERALS::CAddonButtonMap::Reset().
Referenced by KODI::GAME::CGUIControllerList::ResetController().
SupportsCEC()
bool PERIPHERALS::CPeripherals::SupportsCEC () const inline
Referenced by GetNextKeypress(), IsMuted(), OnAction(), ToggleDeviceState(), and ToggleMute().
SupportsFeature()
bool CPeripherals::SupportsFeature (PeripheralFeature feature) const
Check if any busses support the given feature.
Parameters
feature The feature to check for
Returns
True if a bus supports the feature, false otherwise
References m_busses, and m_critSectionBusses.
Referenced by anonymous_namespace{SettingConditions.cpp}::HasPowerOffFeature(), and anonymous_namespace{SettingConditions.cpp}::HasRumbleFeature().
TestFeature()
void CPeripherals::TestFeature (PeripheralFeature feature)
Request peripherals with the specified feature to perform a quick test.
Returns
true if any peripherals support the feature, false otherwise
References PERIPHERALS::PeripheralTypeTranslator::FeatureToString(), GetPeripheralsWithFeature(), CLog::Log(), and LOGDEBUG.
Referenced by OnSettingAction(), and PowerOffDevices().
ToggleDeviceState()
bool CPeripherals::ToggleDeviceState (const CecStateChange mode = STATE_SWITCH_TOGGLE)
Try to toggle the playing device state via a peripheral.
Parameters
mode Whether to activate, put on standby or toggle the source.
Returns
True when the playing device has been switched on, false otherwise.
References PERIPHERALS::FEATURE_CEC, GetPeripheralsWithFeature(), and SupportsCEC().
Referenced by OnApplicationMessage().
ToggleMute()
bool CPeripherals::ToggleMute ()
Try to toggle the mute status via a peripheral.
Returns
True when this change was handled by a peripheral (and should not be handled by anything else), false otherwise.
References PERIPHERALS::FEATURE_CEC, GetPeripheralsWithFeature(), and SupportsCEC().
Referenced by Mute(), OnAction(), and UnMute().
TriggerDeviceScan()
void CPeripherals::TriggerDeviceScan (const PeripheralBusType type = PERIPHERAL_BUS_UNKNOWN)
Trigger a device scan on all known busses.
References m_busses, m_critSectionBusses, PERIPHERALS::PERIPHERAL_BUS_ADDON, and PERIPHERALS::PERIPHERAL_BUS_UNKNOWN.
Referenced by PERIPHERALS::CPeripheralAddon::TriggerDeviceScan(), and CWinEventsWin32::WndProc().
UnMute()
bool PERIPHERALS::CPeripherals::UnMute () inline
Try to unmute the audio via a peripheral.
Todo:
CEC only supports toggling the mute status at this time
Returns
True when this change was handled by a peripheral (and should not be handled by anything else), false otherwise.
References ToggleMute().
UnregisterJoystickButtonMapper()
void CPeripherals::UnregisterJoystickButtonMapper (KODI::JOYSTICK::IButtonMapper * mapper)
Unregister a button mapper interface.
Parameters
mapper The button mapper
References PERIPHERALS::FEATURE_JOYSTICK, PERIPHERALS::FEATURE_KEYBOARD, PERIPHERALS::FEATURE_MOUSE, GetPeripheralsWithFeature(), and KODI::JOYSTICK::IButtonMapper::ResetButtonMapCallbacks().
Referenced by KODI::GAME::CGUIDialogButtonCapture::Notify(), KODI::GAME::CGUIConfigurationWizard::Notify(), KODI::GAME::CGUIDialogButtonCapture::RemoveHooks(), and KODI::GAME::CGUIConfigurationWizard::RemoveHooks().
Member Data Documentation
m_addonInstallMutex
CCriticalSection PERIPHERALS::CPeripherals::m_addonInstallMutex private
Referenced by GetAddonInstallMutex().
m_bMissingLibCecWarningDisplayed
bool PERIPHERALS::CPeripherals::m_bMissingLibCecWarningDisplayed = false private
Referenced by Clear(), and CreatePeripheral().
m_busses
std::vector<PeripheralBusPtr> PERIPHERALS::CPeripherals::m_busses private
Referenced by Clear(), EnableButtonMapping(), GetBusByType(), GetBusWithDevice(), GetByPath(), GetDirectory(), GetNumberOfPeripherals(), GetPeripheralAtLocation(), GetPeripheralsWithFeature(), Initialise(), ProcessEvents(), SupportsFeature(), and TriggerDeviceScan().
m_controllerProfiles
KODI::GAME::CControllerManager& PERIPHERALS::CPeripherals::m_controllerProfiles private
Referenced by GetControllerProfiles().
m_critSectionBusses
CCriticalSection PERIPHERALS::CPeripherals::m_critSectionBusses mutable private
Referenced by Clear(), EnableButtonMapping(), GetBusByType(), GetBusWithDevice(), GetByPath(), GetDirectory(), GetNumberOfPeripherals(), GetPeripheralAtLocation(), GetPeripheralsWithFeature(), Initialise(), ProcessEvents(), SupportsFeature(), and TriggerDeviceScan().
m_critSectionMappings
CCriticalSection PERIPHERALS::CPeripherals::m_critSectionMappings mutable private
Referenced by Clear(), GetMappingForDevice(), GetSettingsFromMapping(), and LoadMappings().
m_eventScanner
std::unique_ptr<CEventScanner> PERIPHERALS::CPeripherals::m_eventScanner private
Referenced by Clear(), Initialise(), RegisterEventLock(), and RegisterEventPoller().
m_inputManager
CInputManager& PERIPHERALS::CPeripherals::m_inputManager private
Referenced by GetInputManager().
m_mappings
std::vector<PeripheralDeviceMapping> PERIPHERALS::CPeripherals::m_mappings private
Referenced by Clear(), GetMappingForDevice(), GetSettingsFromMapping(), and LoadMappings().
The documentation for this class was generated from the following files:
Peripherals.h
Peripherals.cpp