Kodi Documentation: CDVDMsgGeneralSynchronize Class Reference
CDVDMsgGeneralSynchronize Class Reference
#include <DVDMessage.h>
Public Member Functions
CDVDMsgGeneralSynchronize (std::chrono::milliseconds timeout, unsigned int sources)
~CDVDMsgGeneralSynchronize () override
bool Wait (std::chrono::milliseconds ms, unsigned int source)
void Wait (std::atomic< bool > &abort, unsigned int source)
Public Member Functions inherited from CDVDMsg
CDVDMsg (Message msg)
virtual ~CDVDMsg ()=default
bool IsType (Message msg)
Message GetMessageType ()
Private Attributes
class CDVDMsgGeneralSynchronizePriv * m_p
Additional Inherited Members
Public Types inherited from CDVDMsg
enum Message {
NONE = 1000 , GENERAL_RESYNC , GENERAL_FLUSH , GENERAL_RESET ,
GENERAL_PAUSE , GENERAL_STREAMCHANGE , GENERAL_SYNCHRONIZE , GENERAL_GUI_ACTION ,
GENERAL_EOF , PLAYER_SET_AUDIOSTREAM , PLAYER_SET_VIDEOSTREAM , PLAYER_SET_SUBTITLESTREAM ,
PLAYER_SET_SUBTITLESTREAM_VISIBLE , PLAYER_SET_STATE , PLAYER_SET_PROGRAM , PLAYER_SET_UPDATE_STREAM_DETAILS ,
PLAYER_SEEK , PLAYER_SEEK_CHAPTER , PLAYER_SETSPEED , PLAYER_REQUEST_STATE ,
PLAYER_OPENFILE , PLAYER_STARTED , PLAYER_AVCHANGE , PLAYER_ABORT ,
PLAYER_REPORT_STATE , PLAYER_FRAME_ADVANCE , PLAYER_DISPLAY_RESET , DEMUXER_PACKET ,
DEMUXER_RESET , VIDEO_SET_ASPECT , VIDEO_DRAIN , SUBTITLE_CLUTCHANGE ,
SUBTITLE_ADDFILE
}
Constructor & Destructor Documentation
CDVDMsgGeneralSynchronize()
CDVDMsgGeneralSynchronize::CDVDMsgGeneralSynchronize (std::chrono::milliseconds timeout, unsigned int sources)
CDVDMsgGeneralSynchronize — GENERAL_SYNCRONIZR
~CDVDMsgGeneralSynchronize()
CDVDMsgGeneralSynchronize::~CDVDMsgGeneralSynchronize () override
References CDVDMsgGeneralSynchronizePriv::condition, m_p, and XbmcThreads::ConditionVariable::notifyAll().
Member Function Documentation
Wait() [1/2]
void CDVDMsgGeneralSynchronize::Wait (std::atomic< bool > & abort, unsigned int source)
References Wait().
Wait() [2/2]
bool CDVDMsgGeneralSynchronize::Wait (std::chrono::milliseconds ms, unsigned int source)
References CDVDMsgGeneralSynchronizePriv::condition, CLog::Log(), LOGDEBUG, m_p, CDVDMsgGeneralSynchronizePriv::m_timer, XbmcThreads::ConditionVariable::notifyAll(), CDVDMsgGeneralSynchronizePriv::reached, CDVDMsgGeneralSynchronizePriv::section, CDVDMsgGeneralSynchronizePriv::sources, SYNCSOURCE_ANY, and XbmcThreads::ConditionVariable::wait().
Referenced by Wait().
Member Data Documentation
m_p
class CDVDMsgGeneralSynchronizePriv* CDVDMsgGeneralSynchronize::m_p private
Referenced by Wait(), and ~CDVDMsgGeneralSynchronize().
The documentation for this class was generated from the following files:
DVDMessage.h
DVDMessage.cpp