Kodi Documentation: TVOSLibInputHandler Class Reference
TVOSLibInputHandler Class Reference
#include <LibInputHandler.h>
Instance Methods
(void) - sendButtonPressed:
@Todo: factor out siriremote customcontroller to a setting?
(instancetype) - init
Properties
TVOSLibInputRemote * inputRemote
TVOSLibInputSettings * inputSettings
TVOSLibInputTouch * inputTouch
Method Documentation
init
- (instancetype) init
References CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CServiceBroker::GetInputManager(), CLog::Log(), LOGDEBUG, CInputManager::QueueAction(), and CApplicationPowerHandling::ResetSystemIdleTimer().
sendButtonPressed:
- (void) sendButtonPressed: (int) buttonId
@Todo: factor out siriremote customcontroller to a setting?
Property Documentation
inputRemote
- (TVOSLibInputRemote*) inputRemote read write nonatomic strong
inputSettings
- (TVOSLibInputSettings*) inputSettings read write nonatomic strong
Referenced by CTVOSInputSettings::Initialize(), TVOSLibInputRemote::keyPressTimerCallback:, and CTVOSInputSettings::OnSettingChanged().
inputTouch
- (TVOSLibInputTouch*) inputTouch read write nonatomic strong
The documentation for this class was generated from the following files:
darwin/tvos/input/LibInputHandler.h
LibInputHandler.mm