Kodi Documentation: SoLoader Class Reference
SoLoader Class Reference
#include <SoLoader.h>
Public Member Functions
SoLoader (const std::string &so, bool bGlobal=false)
~SoLoader () override
bool Load () override
void Unload () override
int ResolveExport (const char *symbol, void **ptr, bool logging=true) override
bool IsSystemDll () override
HMODULE GetHModule () override
bool HasSymbols () override
Public Member Functions inherited from LibraryLoader
LibraryLoader (const std::string &libraryFile)
virtual ~LibraryLoader ()
virtual int ResolveOrdinal (unsigned long ordinal, void **ptr)
const char * GetName () const
const char * GetFileName () const
const char * GetPath () const
int IncrRef ()
int DecrRef ()
int GetRef ()
Private Attributes
void * m_soHandle
bool m_bGlobal
bool m_bLoaded
Constructor & Destructor Documentation
SoLoader()
SoLoader::SoLoader (const std::string & so, bool bGlobal = false)
References m_bGlobal, m_bLoaded, and m_soHandle.
~SoLoader()
SoLoader::~SoLoader () override
References m_bLoaded, and Unload().
Member Function Documentation
GetHModule()
HMODULE SoLoader::GetHModule () override virtual
Implements LibraryLoader.
References m_soHandle.
HasSymbols()
bool SoLoader::HasSymbols () override virtual
Implements LibraryLoader.
IsSystemDll()
bool SoLoader::IsSystemDll () override virtual
Implements LibraryLoader.
Load()
bool SoLoader::Load () override virtual
Implements LibraryLoader.
References LibraryLoader::GetFileName(), CLog::Log(), LOGDEBUG, LOGERROR, m_bLoaded, m_soHandle, and CSpecialProtocol::TranslatePath().
Referenced by ResolveExport().
ResolveExport()
int SoLoader::ResolveExport (const char * symbol, void ** ptr, bool logging = true) override virtual
Implements LibraryLoader.
References f, LibraryLoader::GetName(), Load(), CLog::Log(), LOGWARNING, m_bLoaded, and m_soHandle.
Unload()
void SoLoader::Unload () override virtual
Implements LibraryLoader.
References LibraryLoader::GetName(), CLog::Log(), LOGERROR, m_bLoaded, and m_soHandle.
Referenced by ~SoLoader().
Member Data Documentation
m_bGlobal
bool SoLoader::m_bGlobal private
Referenced by SoLoader().
m_bLoaded
bool SoLoader::m_bLoaded private
Referenced by Load(), ResolveExport(), SoLoader(), Unload(), and ~SoLoader().
m_soHandle
void* SoLoader::m_soHandle private
Referenced by GetHModule(), Load(), ResolveExport(), SoLoader(), and Unload().
The documentation for this class was generated from the following files:
SoLoader.h
SoLoader.cpp