Kodi Documentation: CSizeGen< T > Class Template Reference
CSizeGen< T > Class Template Reference
#include <Geometry.h>
Public Types
typedef CSizeGen< T > this_type
Public Member Functions
CSizeGen () noexcept=default
CSizeGen (T width, T height)
T Width () const
T Height () const
void SetWidth (T width)
void SetHeight (T height)
void Set (T width, T height)
bool IsZero () const
T Area () const
CPointGen< T > ToPoint () const
template<class U >
CSizeGen (const CSizeGen< U > &rhs)
this_type operator+ (const this_type &size) const
this_type & operator+= (const this_type &size)
this_type operator- (const this_type &size) const
this_type & operator-= (const this_type &size)
this_type operator* (T factor) const
this_type & operator*= (T factor)
this_type operator/ (T factor) const
this_type & operator/= (T factor)
Private Member Functions
void CheckSet (T width, T height)
Private Attributes
T m_w {}
T m_h {}
Detailed Description
template<typename T>
class CSizeGen< T >
Generic two-dimensional size representation
Class invariant: width and height are both non-negative Throws std::out_of_range if invariant would be violated. The class is exception-safe. If modification would violate the invariant, the size is not changed.
Member Typedef Documentation
this_type
template<typename T > typedef CSizeGen<T> CSizeGen< T >::this_type
Constructor & Destructor Documentation
CSizeGen() [1/3]
template<typename T > CSizeGen< T >::CSizeGen () default noexcept
CSizeGen() [2/3]
template<typename T > CSizeGen< T >::CSizeGen (T width, T height) inline
References CSizeGen< T >::CheckSet().
CSizeGen() [3/3]
template<typename T > template<class U > CSizeGen< T >::CSizeGen (const CSizeGen< U > & rhs) inline explicit
References CSizeGen< T >::CheckSet(), CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
Member Function Documentation
Area()
template<typename T > T CSizeGen< T >::Area () const inline
References CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
CheckSet()
template<typename T > void CSizeGen< T >::CheckSet (T width, T height) inline private
References CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
Referenced by CSizeGen< T >::CSizeGen(), CSizeGen< T >::CSizeGen(), CSizeGen< T >::operator*=(), CSizeGen< T >::operator+=(), CSizeGen< T >::operator-=(), CSizeGen< T >::operator/=(), CSizeGen< T >::Set(), CSizeGen< T >::SetHeight(), and CSizeGen< T >::SetWidth().
Height()
template<typename T > T CSizeGen< T >::Height () const inline
References CSizeGen< T >::m_h.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWayland::ApplyOpaqueRegion(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::CreateNewWindow(), KODI::WINDOWING::WAYLAND::COutput::GetDpiForMode(), KODI::WINDOWING::WAYLAND::COutput::GetPixelRatioForMode(), VAAPI::CVaapi2Texture::Map(), anonymous_namespace{WindowDecorator.cpp}::ResizeEdgeForPosition(), anonymous_namespace{WindowDecorator.cpp}::SurfaceGeometry(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateSizeVariables().
IsZero()
template<typename T > bool CSizeGen< T >::IsZero () const inline
References CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
Referenced by KODI::WINDOWING::WAYLAND::COutput::GetDpiForMode(), and KODI::WINDOWING::WAYLAND::COutput::GetPixelRatioForMode().
operator*()
template<typename T > this_type CSizeGen< T >::operator* (T factor) const inline
References CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
operator*=()
template<typename T > this_type & CSizeGen< T >::operator*= (T factor) inline
References CSizeGen< T >::CheckSet(), CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
operator+()
template<typename T > this_type CSizeGen< T >::operator+ (const this_type & size) const inline
References CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
operator+=()
template<typename T > this_type & CSizeGen< T >::operator+= (const this_type & size) inline
References CSizeGen< T >::CheckSet(), CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
operator-()
template<typename T > this_type CSizeGen< T >::operator- (const this_type & size) const inline
References CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
operator-=()
template<typename T > this_type & CSizeGen< T >::operator-= (const this_type & size) inline
References CSizeGen< T >::CheckSet(), CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
operator/()
template<typename T > this_type CSizeGen< T >::operator/ (T factor) const inline
References CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
operator/=()
template<typename T > this_type & CSizeGen< T >::operator/= (T factor) inline
References CSizeGen< T >::CheckSet(), CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
Set()
template<typename T > void CSizeGen< T >::Set (T width, T height) inline
References CSizeGen< T >::CheckSet().
Referenced by KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell::CShellSurfaceXdgShell(), KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6::CShellSurfaceXdgShellUnstableV6(), and VAAPI::CVaapi2Texture::Map().
SetHeight()
template<typename T > void CSizeGen< T >::SetHeight (T height) inline
References CSizeGen< T >::CheckSet(), and CSizeGen< T >::m_w.
SetWidth()
template<typename T > void CSizeGen< T >::SetWidth (T width) inline
References CSizeGen< T >::CheckSet(), and CSizeGen< T >::m_h.
ToPoint()
template<typename T > CPointGen< T > CSizeGen< T >::ToPoint () const inline
References CSizeGen< T >::m_h, and CSizeGen< T >::m_w.
Width()
template<typename T > T CSizeGen< T >::Width () const inline
References CSizeGen< T >::m_w.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWayland::ApplyOpaqueRegion(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::CreateNewWindow(), anonymous_namespace{WindowDecorator.cpp}::DrawAngledLine(), KODI::WINDOWING::WAYLAND::COutput::GetDpiForMode(), KODI::WINDOWING::WAYLAND::COutput::GetPixelRatioForMode(), VAAPI::CVaapi2Texture::Map(), anonymous_namespace{WindowDecorator.cpp}::ResizeEdgeForPosition(), anonymous_namespace{WindowDecorator.cpp}::SurfaceGeometry(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateSizeVariables().
Member Data Documentation
m_h
template<typename T > T CSizeGen< T >::m_h {} private
Referenced by CSizeGen< T >::Area(), CSizeGen< T >::CheckSet(), CSizeGen< T >::CSizeGen(), CSizeGen< T >::Height(), CSizeGen< T >::IsZero(), CSizeGen< T >::operator*(), CSizeGen< T >::operator*=(), CSizeGen< T >::operator+(), CSizeGen< T >::operator+=(), CSizeGen< T >::operator-(), CSizeGen< T >::operator-=(), CSizeGen< T >::operator/(), CSizeGen< T >::operator/=(), CSizeGen< T >::SetWidth(), and CSizeGen< T >::ToPoint().
m_w
template<typename T > T CSizeGen< T >::m_w {} private
Referenced by CSizeGen< T >::Area(), CSizeGen< T >::CheckSet(), CSizeGen< T >::CSizeGen(), CSizeGen< T >::IsZero(), CSizeGen< T >::operator*(), CSizeGen< T >::operator*=(), CSizeGen< T >::operator+(), CSizeGen< T >::operator+=(), CSizeGen< T >::operator-(), CSizeGen< T >::operator-=(), CSizeGen< T >::operator/(), CSizeGen< T >::operator/=(), CSizeGen< T >::SetHeight(), CSizeGen< T >::ToPoint(), and CSizeGen< T >::Width().
The documentation for this class was generated from the following file:
Geometry.h