Kodi Documentation: CDVDDemuxCDDA Class Reference
CDVDDemuxCDDA Class Reference
#include <DVDDemuxCDDA.h>
Public Member Functions
CDVDDemuxCDDA ()
~CDVDDemuxCDDA () override
bool Open (const std::shared_ptr< CDVDInputStream > &pInput)
void Dispose ()
bool Reset () override
void Abort () override
void Flush () override
DemuxPacket * Read () override
bool SeekTime (double time, bool backwards=false, double *startpts=NULL) override
int GetStreamLength () override
CDemuxStream * GetStream (int iStreamId) const override
std::vector< CDemuxStream * > GetStreams () const override
int GetNrOfStreams () const override
std::string GetFileName () override
std::string GetStreamCodecName (int iStreamId) override
Public Member Functions inherited from CDVDDemux
CDVDDemux ()
virtual ~CDVDDemux ()=default
virtual bool SeekChapter (int chapter, double *startpts=NULL)
virtual int GetChapterCount ()
virtual int GetChapter ()
virtual void GetChapterName (std::string &strChapterName, int chapterIdx=-1)
virtual int64_t GetChapterPos (int chapterIdx=-1)
virtual void SetSpeed (int iSpeed)
virtual void FillBuffer (bool mode)
virtual CDemuxStream * GetStream (int64_t demuxerId, int iStreamId) const
virtual int GetPrograms (std::vector< ProgramInfo > &programs)
virtual void SetProgram (int progId)
int GetNrOfSubtitleStreams ()
virtual std::string GetStreamCodecName (int64_t demuxerId, int iStreamId)
virtual void EnableStream (int64_t demuxerId, int id, bool enable)
virtual void OpenStream (int64_t demuxerId, int id)
virtual void SetVideoResolution (unsigned int width, unsigned int height)
int64_t GetDemuxerId ()
Protected Attributes
std::shared_ptr< CDVDInputStream > m_pInput
int64_t m_bytes
CDemuxStreamAudioCDDA * m_stream
Protected Attributes inherited from CDVDDemux
int64_t m_demuxerId
Friends
class CDemuxStreamAudioCDDA
Additional Inherited Members
Protected Member Functions inherited from CDVDDemux
virtual void EnableStream (int id, bool enable)
virtual void OpenStream (int id)
int GetNrOfStreams (StreamType streamType)
Constructor & Destructor Documentation
CDVDDemuxCDDA()
CDVDDemuxCDDA::CDVDDemuxCDDA ()
References m_bytes, and m_stream.
~CDVDDemuxCDDA()
CDVDDemuxCDDA::~CDVDDemuxCDDA () override
References Dispose().
Member Function Documentation
Abort()
void CDVDDemuxCDDA::Abort () override virtual
Reimplemented from CDVDDemux.
References m_pInput.
Referenced by Open().
Dispose()
void CDVDDemuxCDDA::Dispose ()
References m_bytes, m_pInput, and m_stream.
Referenced by Open(), Reset(), and ~CDVDDemuxCDDA().
Flush()
void CDVDDemuxCDDA::Flush () override virtual
Implements CDVDDemux.
GetFileName()
std::string CDVDDemuxCDDA::GetFileName () override virtual
Reimplemented from CDVDDemux.
References m_pInput.
GetNrOfStreams()
int CDVDDemuxCDDA::GetNrOfStreams () const override virtual
Implements CDVDDemux.
References m_stream.
GetStream()
CDemuxStream * CDVDDemuxCDDA::GetStream (int iStreamId) const override virtual
Implements CDVDDemux.
References m_stream.
GetStreamCodecName()
std::string CDVDDemuxCDDA::GetStreamCodecName (int iStreamId) override virtual
Reimplemented from CDVDDemux.
References m_stream.
GetStreamLength()
int CDVDDemuxCDDA::GetStreamLength () override virtual
Reimplemented from CDVDDemux.
References CDemuxStreamAudio::iBitRate, int64_t(), m_pInput, and m_stream.
GetStreams()
std::vector< CDemuxStream * > CDVDDemuxCDDA::GetStreams () const override virtual
Implements CDVDDemux.
References m_stream.
Open()
bool CDVDDemuxCDDA::Open (const std::shared_ptr< CDVDInputStream > & pInput)
References Abort(), CDemuxStreamAudioCDDA, CDemuxStream::codec, Dispose(), DVDSTREAM_TYPE_FILE, CDemuxStreamAudio::iBitRate, CDemuxStreamAudio::iBitsPerSample, CDemuxStreamAudio::iChannels, CDemuxStreamAudio::iSampleRate, m_pInput, m_stream, STREAM_AUDIO, and CDemuxStream::type.
Referenced by Reset().
Read()
DemuxPacket * CDVDDemuxCDDA::Read () override virtual
Implements CDVDDemux.
References CDVDDemuxUtils::AllocateDemuxPacket(), CDDA_READ_SIZE, DEMUX_PACKET::dts, DVD_NOPTS_VALUE, DVD_TIME_BASE, CDemuxStreamAudio::iBitRate, DEMUX_PACKET::iSize, DEMUX_PACKET::iStreamId, m_bytes, m_pInput, m_stream, DEMUX_PACKET::pData, and DEMUX_PACKET::pts.
Reset()
bool CDVDDemuxCDDA::Reset () override virtual
Implements CDVDDemux.
References Dispose(), m_pInput, and Open().
SeekTime()
bool CDVDDemuxCDDA::SeekTime (double time, bool backwards = false, double * startpts = NULL) override virtual
Implements CDVDDemux.
References DVD_TIME_BASE, CDemuxStreamAudio::iBitRate, CDemuxStreamAudio::iBitsPerSample, CDemuxStreamAudio::iChannels, int64_t(), m_bytes, m_pInput, and m_stream.
Friends And Related Symbol Documentation
CDemuxStreamAudioCDDA
friend class CDemuxStreamAudioCDDA friend
Referenced by Open().
Member Data Documentation
m_bytes
int64_t CDVDDemuxCDDA::m_bytes protected
Referenced by CDVDDemuxCDDA(), Dispose(), Read(), and SeekTime().
m_pInput
std::shared_ptr<CDVDInputStream> CDVDDemuxCDDA::m_pInput protected
Referenced by Abort(), Dispose(), GetFileName(), GetStreamLength(), Open(), Read(), Reset(), and SeekTime().
m_stream
CDemuxStreamAudioCDDA* CDVDDemuxCDDA::m_stream protected
Referenced by CDVDDemuxCDDA(), Dispose(), GetNrOfStreams(), GetStream(), GetStreamCodecName(), GetStreamLength(), GetStreams(), Open(), Read(), and SeekTime().
The documentation for this class was generated from the following files:
DVDDemuxCDDA.h
DVDDemuxCDDA.cpp