Kodi Documentation: CAEBitstreamPacker Class Reference
CAEBitstreamPacker Class Reference
#include <AEBitstreamPacker.h>
Public Member Functions
CAEBitstreamPacker ()
~CAEBitstreamPacker ()
void Pack (CAEStreamInfo &info, uint8_t *data, int size)
bool PackPause (CAEStreamInfo &info, unsigned int millis, bool iecBursts)
void Reset ()
uint8_t * GetBuffer ()
unsigned int GetSize () const
Static Public Member Functions
static unsigned int GetOutputRate (const CAEStreamInfo &info)
static CAEChannelInfo GetOutputChannelMap (const CAEStreamInfo &info)
Private Member Functions
void PackDTSHD (CAEStreamInfo &info, uint8_t *data, int size)
void PackEAC3 (CAEStreamInfo &info, uint8_t *data, int size)
Private Attributes
std::vector< uint8_t > m_dtsHD
unsigned int m_dtsHDSize = 0
std::vector< uint8_t > m_eac3
unsigned int m_eac3Size = 0
unsigned int m_eac3FramesCount = 0
unsigned int m_eac3FramesPerBurst = 0
unsigned int m_dataSize = 0
uint8_t m_packedBuffer [MAX_IEC61937_PACKET]
unsigned int m_pauseDuration = 0
Constructor & Destructor Documentation
CAEBitstreamPacker()
CAEBitstreamPacker::CAEBitstreamPacker ()
References Reset().
~CAEBitstreamPacker()
CAEBitstreamPacker::~CAEBitstreamPacker ()
Member Function Documentation
GetBuffer()
uint8_t * CAEBitstreamPacker::GetBuffer ()
References m_packedBuffer.
GetOutputChannelMap()
CAEChannelInfo CAEBitstreamPacker::GetOutputChannelMap (const CAEStreamInfo & info) static
References AE_CH_RAW, channelMap, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Referenced by ActiveAE::CActiveAESink::OpenSink(), and PackPause().
GetOutputRate()
unsigned int CAEBitstreamPacker::GetOutputRate (const CAEStreamInfo & info) static
References CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Referenced by ActiveAE::CActiveAESink::OpenSink(), and PackPause().
GetSize()
unsigned int CAEBitstreamPacker::GetSize () const
References m_dataSize.
Pack()
void CAEBitstreamPacker::Pack (CAEStreamInfo & info, uint8_t * data, int size)
References data(), IEC61937_DATA_OFFSET, CLog::Log(), LOGERROR, m_dataSize, m_packedBuffer, m_pauseDuration, CAEPackIEC61937::PackAC3(), CAEPackIEC61937::PackDTS_1024(), CAEPackIEC61937::PackDTS_2048(), CAEPackIEC61937::PackDTS_512(), PackDTSHD(), PackEAC3(), CAEPackIEC61937::PackTrueHD(), CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
PackDTSHD()
void CAEBitstreamPacker::PackDTSHD (CAEStreamInfo & info, uint8_t * data, int size) private
References data(), m_dataSize, m_dtsHD, m_dtsHDSize, m_packedBuffer, and CAEPackIEC61937::PackDTSHD().
Referenced by Pack().
PackEAC3()
void CAEBitstreamPacker::PackEAC3 (CAEStreamInfo & info, uint8_t * data, int size) private
References data(), m_dataSize, m_eac3, m_eac3FramesCount, m_eac3FramesPerBurst, m_eac3Size, m_packedBuffer, and CAEPackIEC61937::PackEAC3().
Referenced by Pack().
PackPause()
bool CAEBitstreamPacker::PackPause (CAEStreamInfo & info, unsigned int millis, bool iecBursts)
References GetOutputChannelMap(), GetOutputRate(), CLog::Log(), LOGERROR, m_dataSize, m_packedBuffer, m_pauseDuration, CAEPackIEC61937::PackPause(), CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Reset()
void CAEBitstreamPacker::Reset ()
References m_dataSize, m_packedBuffer, and m_pauseDuration.
Referenced by CAEBitstreamPacker().
Member Data Documentation
m_dataSize
unsigned int CAEBitstreamPacker::m_dataSize = 0 private
Referenced by GetSize(), Pack(), PackDTSHD(), PackEAC3(), PackPause(), and Reset().
m_dtsHD
std::vector<uint8_t> CAEBitstreamPacker::m_dtsHD private
Referenced by PackDTSHD().
m_dtsHDSize
unsigned int CAEBitstreamPacker::m_dtsHDSize = 0 private
Referenced by PackDTSHD().
m_eac3
std::vector<uint8_t> CAEBitstreamPacker::m_eac3 private
Referenced by PackEAC3().
m_eac3FramesCount
unsigned int CAEBitstreamPacker::m_eac3FramesCount = 0 private
Referenced by PackEAC3().
m_eac3FramesPerBurst
unsigned int CAEBitstreamPacker::m_eac3FramesPerBurst = 0 private
Referenced by PackEAC3().
m_eac3Size
unsigned int CAEBitstreamPacker::m_eac3Size = 0 private
Referenced by PackEAC3().
m_packedBuffer
uint8_t CAEBitstreamPacker::m_packedBuffer[MAX_IEC61937_PACKET] private
Referenced by GetBuffer(), Pack(), PackDTSHD(), PackEAC3(), PackPause(), and Reset().
m_pauseDuration
unsigned int CAEBitstreamPacker::m_pauseDuration = 0 private
Referenced by Pack(), PackPause(), and Reset().
The documentation for this class was generated from the following files:
AEBitstreamPacker.h
AEBitstreamPacker.cpp