Kodi Documentation: KODI::WINDOWING::GBM::CDRMPlane Class Reference
KODI::WINDOWING::GBM::CDRMPlane Class Reference
#include <DRMPlane.h>
Classes
struct DrmModePlaneDeleter
Public Member Functions
CDRMPlane (int fd, uint32_t plane)
CDRMPlane (const CDRMPlane &)=delete
CDRMPlane & operator= (const CDRMPlane &)=delete
~CDRMPlane ()=default
uint32_t GetPlaneId () const
uint32_t GetPossibleCrtcs () const
void FindModifiers ()
void SetFormat (const uint32_t newFormat)
uint32_t GetFormat () const
std::vector< uint64_t > & GetModifiersForFormat (uint32_t format)
bool SupportsFormat (uint32_t format)
bool SupportsFormatAndModifier (uint32_t format, uint64_t modifier)
Public Member Functions inherited from KODI::WINDOWING::GBM::CDRMObject
CDRMObject (const CDRMObject &)=delete
CDRMObject & operator= (const CDRMObject &)=delete
virtual ~CDRMObject ()=default
std::string GetTypeName () const
std::string GetPropertyName (uint32_t propertyId) const
uint32_t GetId () const
uint32_t GetPropertyId (const std::string &name) const
std::optional< uint64_t > GetPropertyValue (std::string_view name, std::string_view valueName) const
bool SetProperty (const std::string &name, uint64_t value)
bool SupportsProperty (const std::string &name)
Private Attributes
std::unique_ptr< drmModePlane, DrmModePlaneDeleter > m_plane
std::map< uint32_t, std::vector< uint64_t > > m_modifiers_map
uint32_t m_format {DRM_FORMAT_XRGB8888}
Additional Inherited Members
Protected Member Functions inherited from KODI::WINDOWING::GBM::CDRMObject
CDRMObject (int fd)
bool GetProperties (uint32_t id, uint32_t type)
Protected Attributes inherited from KODI::WINDOWING::GBM::CDRMObject
std::unique_ptr< drmModeObjectProperties, DrmModeObjectPropertiesDeleter > m_props
std::vector< std::unique_ptr< drmModePropertyRes, DrmModePropertyResDeleter > > m_propsInfo
int m_fd {-1}
Constructor & Destructor Documentation
CDRMPlane() [1/2]
CDRMPlane::CDRMPlane (int fd, uint32_t plane) explicit
References KODI::WINDOWING::GBM::CDRMObject::GetProperties(), and m_plane.
CDRMPlane() [2/2]
KODI::WINDOWING::GBM::CDRMPlane::CDRMPlane (const CDRMPlane &) delete
~CDRMPlane()
KODI::WINDOWING::GBM::CDRMPlane::~CDRMPlane () default
Member Function Documentation
FindModifiers()
void CDRMPlane::FindModifiers ()
References formats, KODI::WINDOWING::GBM::CDRMObject::m_fd, m_modifiers_map, KODI::WINDOWING::GBM::CDRMObject::m_props, and KODI::WINDOWING::GBM::CDRMObject::m_propsInfo.
GetFormat()
uint32_t KODI::WINDOWING::GBM::CDRMPlane::GetFormat () const inline
References m_format.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::DrmFbGetFromBo(), and KODI::WINDOWING::GBM::CDRMAtomic::FlipPage().
GetModifiersForFormat()
std::vector< uint64_t > & KODI::WINDOWING::GBM::CDRMPlane::GetModifiersForFormat (uint32_t format) inline
References m_modifiers_map.
GetPlaneId()
uint32_t KODI::WINDOWING::GBM::CDRMPlane::GetPlaneId () const inline
References m_plane.
GetPossibleCrtcs()
uint32_t KODI::WINDOWING::GBM::CDRMPlane::GetPossibleCrtcs () const inline
References m_plane.
operator=()
CDRMPlane & KODI::WINDOWING::GBM::CDRMPlane::operator= (const CDRMPlane &) delete
SetFormat()
void KODI::WINDOWING::GBM::CDRMPlane::SetFormat (const uint32_t newFormat) inline
References m_format.
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::FlipPage().
SupportsFormat()
bool CDRMPlane::SupportsFormat (uint32_t format)
References m_plane.
Referenced by SupportsFormatAndModifier().
SupportsFormatAndModifier()
bool CDRMPlane::SupportsFormatAndModifier (uint32_t format, uint64_t modifier)
References DRMHELPERS::FourCCToString(), CLog::Log(), LOGDEBUG, m_modifiers_map, DRMHELPERS::ModifierToString(), and SupportsFormat().
Member Data Documentation
m_format
uint32_t KODI::WINDOWING::GBM::CDRMPlane::m_format {DRM_FORMAT_XRGB8888} private
Referenced by GetFormat(), and SetFormat().
m_modifiers_map
std::map<uint32_t, std::vector<uint64_t> > KODI::WINDOWING::GBM::CDRMPlane::m_modifiers_map private
Referenced by FindModifiers(), GetModifiersForFormat(), and SupportsFormatAndModifier().
m_plane
std::unique_ptr<drmModePlane, DrmModePlaneDeleter> KODI::WINDOWING::GBM::CDRMPlane::m_plane private
Referenced by CDRMPlane(), GetPlaneId(), GetPossibleCrtcs(), and SupportsFormat().
The documentation for this class was generated from the following files:
DRMPlane.h
DRMPlane.cpp