Kodi Documentation: KODI::GUILIB::GUIINFO::CVideoGUIInfo Class Reference
KODI::GUILIB::GUIINFO::CVideoGUIInfo Class Reference
#include <VideoGUIInfo.h>
Public Member Functions
CVideoGUIInfo ()
~CVideoGUIInfo () override=default
bool InitCurrentItem (CFileItem *item) override
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) const override
Get a GUIInfoManager label string.
bool GetFallbackLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) override
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager integer value.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager bool value.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
CGUIInfoProvider ()=default
~CGUIInfoProvider () override=default
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo) override
Set new audio/video stream info data.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::IGUIInfoProvider
virtual ~IGUIInfoProvider ()=default
Private Member Functions
int GetPercentPlayed (const CVideoInfoTag *tag) const
bool GetPlaylistInfo (std::string &value, const CGUIInfo &info) const
Private Attributes
const std::shared_ptr< CApplicationPlayer > m_appPlayer
Additional Inherited Members
Protected Attributes inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
VideoStreamInfo m_videoInfo
AudioStreamInfo m_audioInfo
SubtitleStreamInfo m_subtitleInfo
Constructor & Destructor Documentation
CVideoGUIInfo()
CVideoGUIInfo::CVideoGUIInfo ()
~CVideoGUIInfo()
KODI::GUILIB::GUIINFO::CVideoGUIInfo::~CVideoGUIInfo () override default
Member Function Documentation
GetBool()
bool CVideoGUIInfo::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager bool value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CVariant::asString(), EXTRA, CServiceBroker::GetDataCacheCore(), CServiceBroker::GetGUI(), CGUIListItem::GetProperty(), CServiceBroker::GetSettingsComponent(), CFileItem::GetVideoInfoTag(), CDataCacheCore::GetVideoStereoMode(), CGUIComponent::GetWindowManager(), CVideoInfoTag::IsEmpty(), CGUIListItem::IsFileItem(), CFileItem::IsResumable(), LISTITEM_HASVIDEOEXTRAS, LISTITEM_HASVIDEOVERSIONS, LISTITEM_IS_COLLECTION, LISTITEM_IS_RESUMABLE, LISTITEM_IS_STEREOSCOPIC, LISTITEM_ISVIDEOEXTRA, m_appPlayer, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeVideoCollection, NONE, CStereoscopicsManager::NormalizeStereoMode(), RENDER_OVERLAYS, CSettings::SETTING_VIDEOPLAYER_RENDERMETHOD, value, VIDEOPLAYER_CONTENT, VIDEOPLAYER_HAS_INFO, VIDEOPLAYER_HAS_VIDEOVERSIONS, VIDEOPLAYER_HASMENU, VIDEOPLAYER_HASSUBTITLES, VIDEOPLAYER_HASTELETEXT, VIDEOPLAYER_IS_STEREOSCOPIC, VIDEOPLAYER_ISFULLSCREEN, VIDEOPLAYER_SUBTITLESENABLED, VIDEOPLAYER_USING_OVERLAYS, WINDOW_FULLSCREEN_GAME, and WINDOW_FULLSCREEN_VIDEO.
GetFallbackLabel()
bool CVideoGUIInfo::GetFallbackLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) override virtual
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Reimplemented from KODI::GUILIB::GUIINFO::CGUIInfoProvider.
References CGUIListItem::GetLabel(), CFileItem::GetPath(), CUtil::GetTitleFromPath(), CFileItem::GetVideoInfoTag(), PLAYER_OFFSET_POSITION_FIRST, PLAYER_OFFSET_POSITION_LAST, value, VIDEOPLAYER_OFFSET_POSITION_FIRST, VIDEOPLAYER_OFFSET_POSITION_LAST, and VIDEOPLAYER_TITLE.
GetInt()
bool CVideoGUIInfo::GetInt (int & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager integer value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References GetPercentPlayed(), CFileItem::GetVideoInfoTag(), CGUIListItem::IsFileItem(), LISTITEM_PERCENT_PLAYED, m_appPlayer, value, VIDEOPLAYER_AUDIOSTREAMCOUNT, and VIDEOPLAYER_VIDEOSTREAMCOUNT.
GetLabel()
bool CVideoGUIInfo::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) const override virtual
Get a GUIInfoManager label string.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Todo:
get rid of "videos with versions as folder" hack!
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CVariant::asString(), StreamInfo::bitrate, AudioStreamInfo::channels, StreamInfo::codecName, CSettingUtils::FindIntInList(), g_localizeStrings, CLocalizeStrings::Get(), CGUIListItem::GetArt(), CDateTime::GetAsLocalizedDate(), CDateTime::GetCurrentDateTime(), CServiceBroker::GetDataCacheCore(), URIUtils::GetExtension(), KODI::GUILIB::GUIINFO::GetFileInfoLabelValueFromPath(), URIUtils::GetFileName(), CServiceBroker::GetGUI(), URIUtils::GetParentPath(), CFileItem::GetPath(), GetPercentPlayed(), GetPlaylistInfo(), KODI::GUILIB::GUIINFO::GetPlaylistLabel(), CServiceBroker::GetPlaylistPlayer(), CGUIListItem::GetProperty(), CServiceBroker::GetSettingsComponent(), CFileItem::GetVideoInfoTag(), CDataCacheCore::GetVideoStereoMode(), CGUIComponent::GetWindowManager(), CURL::GetWithoutUserDetails(), CGUIListItem::HasArt(), CFileItem::HasMusicInfoTag(), CFileItem::HasVideoVersions(), VideoStreamInfo::hdrType, CStreamDetails::HdrTypeToString(), VideoStreamInfo::height, CDateTime::IsValid(), KODI::VIDEO::IsVideoDb(), StreamInfo::language, LISTITEM_ALBUM, LISTITEM_APPEARANCES, LISTITEM_ARTIST, LISTITEM_AUDIO_CHANNELS, LISTITEM_AUDIO_CODEC, LISTITEM_AUDIO_LANGUAGE, LISTITEM_CAST, LISTITEM_CAST_AND_ROLE, LISTITEM_COUNTRY, LISTITEM_DATE_ADDED, LISTITEM_DBID, LISTITEM_DBTYPE, LISTITEM_DIRECTOR, LISTITEM_DURATION, LISTITEM_ENDTIME, LISTITEM_ENDTIME_RESUME, LISTITEM_EPISODE, LISTITEM_FILE_EXTENSION, LISTITEM_FILENAME, LISTITEM_FILENAME_AND_PATH, LISTITEM_FOLDERNAME, LISTITEM_GENRE, LISTITEM_IMDBNUMBER, LISTITEM_LABEL, LISTITEM_LASTPLAYED, LISTITEM_MPAA, LISTITEM_ORIGINALTITLE, LISTITEM_PATH, LISTITEM_PERCENT_PLAYED, LISTITEM_PLAYCOUNT, LISTITEM_PLOT, LISTITEM_PLOT_OUTLINE, LISTITEM_PREMIERED, LISTITEM_RATING, LISTITEM_RATING_AND_VOTES, LISTITEM_SEASON, LISTITEM_SET, LISTITEM_SETID, LISTITEM_STATUS, LISTITEM_STEREOSCOPIC_MODE, LISTITEM_STUDIO, LISTITEM_SUBTITLE_LANGUAGE, LISTITEM_TAG, LISTITEM_TAGLINE, LISTITEM_TITLE, LISTITEM_TOP250, LISTITEM_TRACKNUMBER, LISTITEM_TRAILER, LISTITEM_TVSHOW, LISTITEM_TVSHOWDBID, LISTITEM_UNIQUEID, LISTITEM_USER_RATING, LISTITEM_VIDEO_ASPECT, LISTITEM_VIDEO_CODEC, LISTITEM_VIDEO_HDR_TYPE, LISTITEM_VIDEO_HEIGHT, LISTITEM_VIDEO_RESOLUTION, LISTITEM_VIDEO_WIDTH, LISTITEM_VIDEOVERSION_NAME, LISTITEM_VOTES, LISTITEM_WRITER, LISTITEM_YEAR, m_appPlayer, KODI::GUILIB::GUIINFO::CGUIInfoProvider::m_audioInfo, CGUIListItem::m_bIsFolder, KODI::GUILIB::GUIINFO::CGUIInfoProvider::m_subtitleInfo, KODI::GUILIB::GUIINFO::CGUIInfoProvider::m_videoInfo, MediaTypeEpisode, MediaTypeMovie, MediaTypeTvShow, MediaTypeVideoCollection, CStereoscopicsManager::NormalizeStereoMode(), PLAYER_FILENAME, PLAYER_FILEPATH, PLAYER_OFFSET_POSITION_FIRST, PLAYER_OFFSET_POSITION_LAST, PLAYER_PATH, PLAYER_TITLE, PLAYLIST_LENGTH, PLAYLIST_POSITION, CRating::rating, URIUtils::RemoveSlashAtEnd(), CSettings::SETTING_VIDEOLIBRARY_SHOWUNWATCHEDPLOTS, KODI::PLAYLIST::TYPE_VIDEO, value, VERSION, CStreamDetails::VideoAspectToAspectDescription(), CStreamDetails::VideoDimsToResolutionDescription(), CSettings::VIDEOLIBRARY_PLOTS_SHOW_UNWATCHED_MOVIES, CSettings::VIDEOLIBRARY_PLOTS_SHOW_UNWATCHED_TVSHOWEPISODES, VIDEOPLAYER_ALBUM, VIDEOPLAYER_ART, VIDEOPLAYER_ARTIST, VIDEOPLAYER_AUDIO_BITRATE, VIDEOPLAYER_AUDIO_CHANNELS, VIDEOPLAYER_AUDIO_CODEC, VIDEOPLAYER_AUDIO_LANG, VIDEOPLAYER_CAST, VIDEOPLAYER_CAST_AND_ROLE, VIDEOPLAYER_COUNTRY, VIDEOPLAYER_COVER, VIDEOPLAYER_DBID, VIDEOPLAYER_DIRECTOR, VIDEOPLAYER_EPISODE, VIDEOPLAYER_GENRE, VIDEOPLAYER_HDR_TYPE, VIDEOPLAYER_IMDBNUMBER, VIDEOPLAYER_LASTPLAYED, VIDEOPLAYER_MPAA, VIDEOPLAYER_OFFSET_POSITION_FIRST, VIDEOPLAYER_OFFSET_POSITION_LAST, VIDEOPLAYER_ORIGINALTITLE, VIDEOPLAYER_PLAYCOUNT, VIDEOPLAYER_PLAYLISTLEN, VIDEOPLAYER_PLAYLISTPOS, VIDEOPLAYER_PLOT, VIDEOPLAYER_PLOT_OUTLINE, VIDEOPLAYER_PREMIERED, VIDEOPLAYER_RATING, VIDEOPLAYER_RATING_AND_VOTES, VIDEOPLAYER_SEASON, VIDEOPLAYER_STEREOSCOPIC_MODE, VIDEOPLAYER_STUDIO, VIDEOPLAYER_SUBTITLES_LANG, VIDEOPLAYER_TAGLINE, VIDEOPLAYER_TITLE, VIDEOPLAYER_TOP250, VIDEOPLAYER_TRAILER, VIDEOPLAYER_TVSHOW, VIDEOPLAYER_TVSHOWDBID, VIDEOPLAYER_UNIQUEID, VIDEOPLAYER_USER_RATING, VIDEOPLAYER_VIDEO_ASPECT, VIDEOPLAYER_VIDEO_BITRATE, VIDEOPLAYER_VIDEO_CODEC, VIDEOPLAYER_VIDEO_RESOLUTION, VIDEOPLAYER_VIDEOVERSION_NAME, VIDEOPLAYER_VOTES, VIDEOPLAYER_WRITER, VIDEOPLAYER_YEAR, CRating::votes, VideoStreamInfo::width, and WINDOW_VIDEO_NAV.
Referenced by GetPlaylistInfo().
GetPercentPlayed()
int CVideoGUIInfo::GetPercentPlayed (const CVideoInfoTag * tag) const private
References CBookmark::IsPartWay(), CBookmark::timeInSeconds, and CBookmark::totalTimeInSeconds.
Referenced by GetInt(), and GetLabel().
GetPlaylistInfo()
bool CVideoGUIInfo::GetPlaylistInfo (std::string & value, const CGUIInfo & info) const private
References GetLabel(), KODI::PLAYLIST::CPlayListPlayer::GetNextItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), index(), CVideoThumbLoader::LoadItem(), playlist, KODI::PLAYLIST::TYPE_VIDEO, value, VIDEOPLAYER_ART, VIDEOPLAYER_COVER, and VIDEOPLAYER_PLAYLISTPOS.
Referenced by GetLabel().
InitCurrentItem()
bool CVideoGUIInfo::InitCurrentItem (CFileItem * item) override virtual
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by the provider, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CVideoThumbLoader::FillThumb(), g_application, CGUIListItem::GetArt(), CFileItem::GetPath(), CGUIListItem::HasArt(), KODI::NETWORK::IsInternetStream(), KODI::VIDEO::IsVideo(), CVideoThumbLoader::LoadItem(), CLog::Log(), LOGDEBUG, m_appPlayer, and CGUIListItem::SetArt().
Member Data Documentation
m_appPlayer
const std::shared_ptr<CApplicationPlayer> KODI::GUILIB::GUIINFO::CVideoGUIInfo::m_appPlayer private
Referenced by GetBool(), GetInt(), GetLabel(), and InitCurrentItem().
The documentation for this class was generated from the following files:
VideoGUIInfo.h
VideoGUIInfo.cpp