Kodi Documentation: CNetworkWin32 Class Reference
CNetworkWin32 Class Reference
#include <NetworkWin32.h>
Public Member Functions
CNetworkWin32 ()
~CNetworkWin32 (void) override
virtual std::vector< CNetworkInterface * > & GetInterfaceList (void) override
bool PingHost (unsigned long host, unsigned int timeout_ms=2000) override
bool PingHost (const struct sockaddr &host, unsigned int timeout_ms=2000)
std::vector< std::string > GetNameServers (void) override
bool PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms=2000, bool readability_check=false)
virtual bool PingHost (unsigned long host, unsigned int timeout_ms=2000)=0
Public Member Functions inherited from CNetworkBase
CNetworkBase ()
virtual ~CNetworkBase ()
CNetworkServices & GetServices ()
virtual bool GetHostName (std::string &hostname)
virtual CNetworkInterface * GetFirstConnectedInterface (void)
bool HasInterfaceForIP (unsigned long address)
bool IsAvailable (void)
bool IsConnected (void)
bool WakeOnLan (const char *mac)
bool PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms=2000, bool readability_check=false)
void NetworkMessage (EMESSAGE message, int param)
bool IsLocalHost (const std::string &hostname)
void WaitForNet ()
Private Member Functions
int GetSocket ()
void queryInterfaceList ()
void CleanInterfaceList ()
Private Attributes
std::vector< CNetworkInterface * > m_interfaces
int m_sock
CStopWatch m_netrefreshTimer
CCriticalSection m_critSection
std::vector< uint8_t > m_adapterAddresses
Friends
class CNetworkInterfaceWin32
Additional Inherited Members
Public Types inherited from CNetworkBase
enum EMESSAGE { SERVICES_UP , SERVICES_DOWN }
Static Public Member Functions inherited from CNetworkBase
static std::unique_ptr< CNetworkBase > GetNetwork ()
static int ParseHex (char *str, unsigned char *addr)
static std::string GetIpStr (const sockaddr *sa)
IPv6/IPv4 compatible conversion of host IP address.
static std::string GetMaskByPrefixLength (uint8_t prefixLength)
convert prefix length of IPv4 address to IP mask representation
Public Attributes inherited from CNetworkBase
std::unique_ptr< CNetworkServices > m_services
Constructor & Destructor Documentation
CNetworkWin32()
CNetworkWin32::CNetworkWin32 ()
References queryInterfaceList().
~CNetworkWin32()
CNetworkWin32::~CNetworkWin32 (void) override
References CleanInterfaceList(), m_netrefreshTimer, and CStopWatch::Stop().
Member Function Documentation
CleanInterfaceList()
void CNetworkWin32::CleanInterfaceList () private
References m_interfaces.
Referenced by queryInterfaceList(), and ~CNetworkWin32().
GetInterfaceList()
std::vector< CNetworkInterface * > & CNetworkWin32::GetInterfaceList (void) override virtual
Implements CNetworkBase.
References CStopWatch::GetElapsedSeconds(), m_critSection, m_interfaces, m_netrefreshTimer, and queryInterfaceList().
GetNameServers()
std::vector< std::string > CNetworkWin32::GetNameServers (void) override virtual
Implements CNetworkBase.
References CNetworkBase::GetIpStr().
GetSocket()
int CNetworkWin32::GetSocket () inline private
References m_sock.
PingHost() [1/4]
bool CNetworkWin32::PingHost (const struct sockaddr & host, unsigned int timeout_ms = 2000)
References GetLastError(), IP_REQ_TIMED_OUT, IP_SUCCESS, CLog::Log(), LOGERROR, SetLastError(), icmp_echo_reply::Status, and CWIN32Util::WUSysMsg().
PingHost() [2/4]
bool CNetworkWin32::PingHost (unsigned long host, unsigned int timeout_ms = 2000) override virtual
Implements CNetworkBase.
References PingHost().
Referenced by PingHost().
PingHost() [3/4]
virtual bool CNetworkBase::PingHost (unsigned long host, unsigned int timeout_ms = 2000) virtual
Implements CNetworkBase.
PingHost() [4/4]
bool CNetworkBase::PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms = 2000, bool readability_check = false)
queryInterfaceList()
void CNetworkWin32::queryInterfaceList () private
References CleanInterfaceList(), CNetworkInterfaceWin32, CLog::Log(), LOGDEBUG, m_adapterAddresses, m_interfaces, m_netrefreshTimer, and CStopWatch::StartZero().
Referenced by CNetworkWin32(), and GetInterfaceList().
Friends And Related Symbol Documentation
CNetworkInterfaceWin32
friend class CNetworkInterfaceWin32 friend
Referenced by queryInterfaceList().
Member Data Documentation
m_adapterAddresses
std::vector<uint8_t> CNetworkWin32::m_adapterAddresses private
Referenced by queryInterfaceList().
m_critSection
CCriticalSection CNetworkWin32::m_critSection private
Referenced by GetInterfaceList().
m_interfaces
std::vector<CNetworkInterface*> CNetworkWin32::m_interfaces private
Referenced by CleanInterfaceList(), GetInterfaceList(), and queryInterfaceList().
m_netrefreshTimer
CStopWatch CNetworkWin32::m_netrefreshTimer private
Referenced by GetInterfaceList(), queryInterfaceList(), and ~CNetworkWin32().
m_sock
int CNetworkWin32::m_sock private
Referenced by GetSocket().
The documentation for this class was generated from the following files:
NetworkWin32.h
NetworkWin32.cpp