Kodi Documentation: KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkActorHandler Class Reference
KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkActorHandler Class Reference
Public Member Functions
CVideoItemArtworkActorHandler (const std::shared_ptr< CFileItem > &item, const std::string &artType)
std::string GetCurrentArt () const override
std::string GetLocalArt () const override
std::string GetDefaultIcon () const override
Public Member Functions inherited from KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler
CVideoItemArtworkHandler (const std::shared_ptr< CFileItem > &item, const std::string &artType)
std::string GetCurrentArt () const override
std::string GetEmbeddedArt () const override
std::vector< std::string > GetRemoteArt () const override
std::string GetLocalArt () const override
std::string GetDefaultIcon () const override
void AddItemPathToFileBrowserSources (std::vector< CMediaSource > &sources) override
void PersistArt (const std::string &art) override
Public Member Functions inherited from KODI::VIDEO::IVideoItemArtworkHandler
virtual ~IVideoItemArtworkHandler ()=default
virtual bool SupportsFlippedArt () const
virtual std::string UpdateEmbeddedArt (const std::string &art)
virtual std::string UpdateRemoteArt (const std::vector< std::string > &art, int index)
Additional Inherited Members
Protected Member Functions inherited from KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler
void AddItemPathStringToFileBrowserSources (std::vector< CMediaSource > &sources, const std::string &itemDir, const std::string &label)
Protected Attributes inherited from KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler
const std::shared_ptr< CFileItem > m_item
const std::string m_artType
Constructor & Destructor Documentation
CVideoItemArtworkActorHandler()
KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkActorHandler::CVideoItemArtworkActorHandler (const std::shared_ptr< CFileItem > & item, const std::string & artType) inline explicit
Member Function Documentation
GetCurrentArt()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkActorHandler::GetCurrentArt () const override virtual
Implements KODI::VIDEO::IVideoItemArtworkHandler.
References CVideoDatabase::GetArtForItem(), LOGERROR, and CVideoDatabase::Open().
GetDefaultIcon()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkActorHandler::GetDefaultIcon () const inline override virtual
Implements KODI::VIDEO::IVideoItemArtworkHandler.
GetLocalArt()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkActorHandler::GetLocalArt () const override virtual
Reimplemented from KODI::VIDEO::IVideoItemArtworkHandler.
References URIUtils::AddFileToFolder(), and CFileUtils::Exists().
The documentation for this class was generated from the following file:
VideoItemArtworkHandler.cpp