Kodi Documentation: XFILE::CPosixFile Class Reference
XFILE::CPosixFile Class Reference
#include <PosixFile.h>
Public Member Functions
~CPosixFile () override
bool Open (const CURL &url) override
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
void Close () override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
int Truncate (int64_t size) override
int64_t GetPosition () override
int64_t GetLength () override
void Flush () override
int IoControl (EIoControl request, void *param) override
bool Delete (const CURL &url) override
bool Rename (const CURL &url, const CURL &urlnew) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int Stat (struct __stat64 *buffer) override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool SetHidden (const CURL &url, bool hidden)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Protected Attributes
int m_fd = -1
int64_t m_filePos = -1
int64_t m_lastDropPos = -1
bool m_allowWrite = false
Constructor & Destructor Documentation
~CPosixFile()
CPosixFile::~CPosixFile () override
References m_fd.
Member Function Documentation
Close()
void CPosixFile::Close () override virtual
Implements XFILE::IFile.
References m_allowWrite, m_fd, m_filePos, and m_lastDropPos.
Referenced by XFILE::CTVOSFile::Close(), and CPreflightHandler::MigrateUserdataXMLToNSUserDefaults().
Delete()
bool CPosixFile::Delete (const CURL & url) override virtual
Reimplemented from XFILE::IFile.
References getFilename(), and LOGWARNING.
Referenced by XFILE::CTVOSFile::Delete(), and CPreflightHandler::MigrateUserdataXMLToNSUserDefaults().
Exists()
bool CPosixFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References getFilename(), and S_ISDIR.
Referenced by XFILE::CTVOSFile::Exists().
Flush()
void CPosixFile::Flush () override virtual
Reimplemented from XFILE::IFile.
References m_fd.
GetLength()
int64_t CPosixFile::GetLength () override virtual
Implements XFILE::IFile.
References m_fd.
Referenced by XFILE::CTVOSFile::GetLength(), and IoControl().
GetPosition()
int64_t CPosixFile::GetPosition () override virtual
Implements XFILE::IFile.
References m_fd, and m_filePos.
Referenced by XFILE::CTVOSFile::GetPosition(), and IoControl().
IoControl()
int CPosixFile::IoControl (EIoControl request, void * param) override virtual
Reimplemented from XFILE::IFile.
References GetLength(), GetPosition(), int64_t(), XFILE::IOCTRL_NATIVE, XFILE::IOCTRL_SEEK_POSSIBLE, m_fd, m_filePos, and Seek().
Referenced by XFILE::CTVOSFile::IoControl().
Open()
bool CPosixFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References getFilename(), m_fd, and m_filePos.
Referenced by CPreflightHandler::MigrateUserdataXMLToNSUserDefaults(), and XFILE::CTVOSFile::Open().
OpenForWrite()
bool CPosixFile::OpenForWrite (const CURL & url, bool bOverWrite = false) override virtual
Reimplemented from XFILE::IFile.
References getFilename(), m_allowWrite, m_fd, and m_filePos.
Read()
ssize_t CPosixFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References int64_t(), m_fd, m_filePos, m_lastDropPos, Seek(), and SSIZE_MAX.
Referenced by CPreflightHandler::MigrateUserdataXMLToNSUserDefaults(), and XFILE::CTVOSFile::Read().
Rename()
bool CPosixFile::Rename (const CURL & url, const CURL & urlnew) override virtual
Reimplemented from XFILE::IFile.
References XFILE::CFile::Copy(), XFILE::CFile::Delete(), getFilename(), LOGDEBUG, LOGWARNING, name, and rename().
Referenced by XFILE::CTVOSFile::Rename().
Seek()
int64_t CPosixFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
References int64_t(), m_fd, and m_filePos.
Referenced by IoControl(), Read(), XFILE::CTVOSFile::Seek(), and Write().
Stat() [1/2]
int CPosixFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References getFilename().
Referenced by XFILE::CTVOSFile::Stat().
Stat() [2/2]
int CPosixFile::Stat (struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about currently open file For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Reimplemented from XFILE::IFile.
References m_fd.
Truncate()
int CPosixFile::Truncate (int64_t size) override virtual
Reimplemented from XFILE::IFile.
References int64_t(), and m_fd.
Write()
ssize_t CPosixFile::Write (const void * bufPtr, size_t bufSize) override virtual
Attempt to write bufSize bytes from buffer bufPtr into currently opened file.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully written bytes if any bytes were written, zero if no bytes were written and no detectable error occur, -1 in case of any explicit error
Reimplemented from XFILE::IFile.
References m_allowWrite, m_fd, m_filePos, Seek(), and SSIZE_MAX.
Referenced by XFILE::CTVOSFile::Write().
Member Data Documentation
m_allowWrite
bool XFILE::CPosixFile::m_allowWrite = false protected
Referenced by Close(), OpenForWrite(), and Write().
m_fd
int XFILE::CPosixFile::m_fd = -1 protected
Referenced by Close(), Flush(), GetLength(), GetPosition(), IoControl(), Open(), OpenForWrite(), Read(), Seek(), Stat(), Truncate(), Write(), and ~CPosixFile().
m_filePos
int64_t XFILE::CPosixFile::m_filePos = -1 protected
Referenced by Close(), GetPosition(), IoControl(), Open(), OpenForWrite(), Read(), Seek(), and Write().
m_lastDropPos
int64_t XFILE::CPosixFile::m_lastDropPos = -1 protected
Referenced by Close(), and Read().
The documentation for this class was generated from the following files:
PosixFile.h
PosixFile.cpp