Kodi Documentation: CONTEXTMENU::CVideoBrowse Struct Reference
CONTEXTMENU::CVideoBrowse Struct Reference
#include <ContextMenus.h>
Public Member Functions
CVideoBrowse ()
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Constructor & Destructor Documentation
CVideoBrowse()
CONTEXTMENU::CVideoBrowse::CVideoBrowse () inline
Member Function Documentation
Execute()
bool CONTEXTMENU::CVideoBrowse::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References EFILEFOLDER_MASK_ONBROWSE, CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE, URIUtils::IsPVRRadioRecordingFileOrFolder(), URIUtils::IsPVRTVRecordingFileOrFolder(), CGUIMessage::SetStringParam(), WINDOW_INVALID, WINDOW_RADIO_RECORDINGS, WINDOW_TV_RECORDINGS, and WINDOW_VIDEO_NAV.
IsVisible()
bool CONTEXTMENU::CVideoBrowse::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References EFILEFOLDER_MASK_ONBROWSE, CFileItem::IsFileFolder(), KODI::VIDEO::UTILS::IsItemPlayable(), and CGUIListItem::m_bIsFolder.
The documentation for this struct was generated from the following files:
video/ContextMenus.h
video/ContextMenus.cpp