Kodi Documentation: kodi::addon::PVRRecording Class Reference
kodi::addon::PVRRecording Class Reference
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 5. Recording » class PVRRecording
#include <Recordings.h>
Public Member Functions
void SetRecordingId (const std::string &recordingId)
required
Unique identifier of the recording on the client.
std::string GetRecordingId () const
To get with SetRecordingId changed values.
void SetTitle (const std::string &title)
required
The title of this recording.
std::string GetTitle () const
To get with SetTitle changed values.
void SetTitleExtraInfo (const std::string &titleExtraInfo)
optional
The title extra information of this recording.
std::string GetTitleExtraInfo () const
To get with SetTitleExtraInfo changed values.
void SetEpisodeName (const std::string &episodeName)
optional
Episode name (also known as subtitle).
std::string GetEpisodeName () const
To get with SetEpisodeName changed values.
void SetSeriesNumber (int seriesNumber)
optional
Series number (usually called season).
int GetSeriesNumber () const
To get with SetSeriesNumber changed values.
void SetEpisodeNumber (int episodeNumber)
optional
Eepisode number within the "iSeriesNumber" season.
int GetEpisodeNumber () const
To get with SetEpisodeNumber changed values.
void SetEpisodePartNumber (int episodePartNumber)
optional
Episode part number.
int GetEpisodePartNumber () const
To get with SetEpisodePartNumber changed values.
void SetYear (int year)
optional
Year of first release (use to identify a specific movie re-make) / first airing for TV shows.
int GetYear () const
To get with SetYear changed values.
void SetDirectory (const std::string &directory)
optional
std::string GetDirectory () const
To get with SetDirectory changed values.
void SetPlotOutline (const std::string &plotOutline)
optional
Plot outline name.
std::string GetPlotOutline () const
To get with SetPlotOutline changed values.
void SetPlot (const std::string &plot)
optional
Plot name.
std::string GetPlot () const
To get with SetPlot changed values.
void SetChannelName (const std::string &channelName)
optional
Channel name.
std::string GetChannelName () const
To get with SetChannelName changed values.
void SetIconPath (const std::string &iconPath)
optional
Channel logo (icon) path.
std::string GetIconPath () const
To get with SetIconPath changed values.
void SetThumbnailPath (const std::string &thumbnailPath)
optional
Thumbnail path.
std::string GetThumbnailPath () const
To get with SetThumbnailPath changed values.
void SetFanartPath (const std::string &fanartPath)
optional
Fanart path.
std::string GetFanartPath () const
To get with SetFanartPath changed values.
void SetRecordingTime (time_t recordingTime)
optional
Start time of the recording.
time_t GetRecordingTime () const
To get with SetRecordingTime changed values.
void SetDuration (int duration)
optional
Duration of the recording in seconds.
int GetDuration () const
To get with SetDuration changed values.
void SetPriority (int priority)
optional
Priority of this recording (from 0 - 100).
int GetPriority () const
To get with SetPriority changed values.
void SetLifetime (int lifetime)
optional
Life time in days of this recording.
int GetLifetime () const
To get with SetLifetime changed values.
void SetGenreType (int genreType)
optional
Genre type.
int GetGenreType () const
To get with SetGenreType changed values.
void SetGenreSubType (int genreSubType)
optional
Genre sub type.
int GetGenreSubType () const
To get with SetGenreSubType changed values.
void SetGenreDescription (const std::string &genreDescription)
optional
To set own genre description name.
std::string GetGenreDescription () const
To get with SetGenreDescription changed values.
void SetPlayCount (int playCount)
optional
Play count of this recording on the client.
int GetPlayCount () const
To get with SetPlayCount changed values.
void SetLastPlayedPosition (int lastPlayedPosition)
optional
Last played position of this recording on the client.
int GetLastPlayedPosition () const
To get with SetLastPlayedPosition changed values.
void SetIsDeleted (int isDeleted)
optional
Shows this recording is deleted and can be undelete.
int GetIsDeleted () const
To get with SetIsDeleted changed values.
void SetEPGEventId (unsigned int epgEventId)
optional
EPG event id associated with this recording. Valid ids must be greater than EPG_TAG_INVALID_UID.
unsigned int GetEPGEventId () const
To get with SetEPGEventId changed values.
void SetChannelUid (int channelUid)
optional
Unique identifier of the channel for this recording. PVR_CHANNEL_INVALID_UID denotes that channel uid is not available.
int GetChannelUid () const
To get with SetChannelUid changed values.
void SetChannelType (PVR_RECORDING_CHANNEL_TYPE channelType)
optional
Channel type.
PVR_RECORDING_CHANNEL_TYPE GetChannelType () const
To get with SetChannelType changed values.
void SetFirstAired (const std::string &firstAired)
optional
First aired date of this recording.
std::string GetFirstAired () const
To get with SetFirstAired changed values.
void SetFlags (unsigned int flags)
optional
Bit field of independent flags associated with the recording.
unsigned int GetFlags () const
To get with SetFlags changed values.
void SetSizeInBytes (int64_t sizeInBytes)
optional
Size of the recording in bytes.
int64_t GetSizeInBytes () const
To get with SetSizeInBytes changed values.
void SetClientProviderUid (int iClientProviderUid)
optional
Unique identifier of the provider this channel belongs to.
int GetClientProviderUid () const
To get with SetClientProviderUid changed values.
void SetProviderName (const std::string &providerName)
optional
Name for the provider of this channel.
std::string GetProviderName () const
To get with SetProviderName changed values.
void SetParentalRating (unsigned int iParentalRating)
optional
Age rating for the recording.
unsigned int GetParentalRating () const
To get with SetParentalRating changed values.
void SetParentalRatingCode (const std::string &ratingCode)
optional
Parental rating code for this recording.
std::string GetParentalRatingCode () const
To get with SetParentalRatingCode changed values.
void SetParentalRatingIcon (const std::string &ratingIcon)
optional
Parental rating icon for this recording.
std::string GetParentalRatingIcon () const
To get with SetParentalRatingIcon changed values.
void SetParentalRatingSource (const std::string &ratingSource)
optional
Parental rating source for this recording.
std::string GetParentalRatingSource () const
To get with SetParentalRatingSource changed values.
Public Member Functions inherited from kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >
DynamicCStructHdl ()
DynamicCStructHdl (const DynamicCStructHdl &cppClass)
DynamicCStructHdl (const PVR_RECORDING *cStructure)
DynamicCStructHdl (PVR_RECORDING *cStructure)
const DynamicCStructHdl & operator= (const DynamicCStructHdl &right)
const DynamicCStructHdl & operator= (const PVR_RECORDING &right)
virtual ~DynamicCStructHdl ()
operator PVR_RECORDING * ()
operator const PVR_RECORDING * () const
const PVR_RECORDING * GetCStructure () const
PVR_RECORDING * release ()
Static Public Member Functions
static void AllocResources (const PVR_RECORDING *source, PVR_RECORDING *target)
static void FreeResources (PVR_RECORDING *target)
Private Member Functions
PVRRecording (const PVR_RECORDING *recording)
PVRRecording (PVR_RECORDING *recording)
Friends
class CInstancePVRClient
Additional Inherited Members
Protected Attributes inherited from kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >
PVR_RECORDING * m_cStructure
Constructor & Destructor Documentation
PVRRecording() [1/2]
kodi::addon::PVRRecording::PVRRecording (const PVR_RECORDING * recording) inline private
PVRRecording() [2/2]
kodi::addon::PVRRecording::PVRRecording (PVR_RECORDING * recording) inline private
Member Function Documentation
AllocResources()
static void kodi::addon::PVRRecording::AllocResources (const PVR_RECORDING * source, PVR_RECORDING * target) inline static
References kodi::addon::AllocAndCopyString(), PVR_RECORDING::strChannelName, PVR_RECORDING::strDirectory, PVR_RECORDING::strEpisodeName, PVR_RECORDING::strFanartPath, PVR_RECORDING::strFirstAired, PVR_RECORDING::strGenreDescription, PVR_RECORDING::strIconPath, PVR_RECORDING::strParentalRatingCode, PVR_RECORDING::strParentalRatingIcon, PVR_RECORDING::strParentalRatingSource, PVR_RECORDING::strPlot, PVR_RECORDING::strPlotOutline, PVR_RECORDING::strProviderName, PVR_RECORDING::strRecordingId, PVR_RECORDING::strThumbnailPath, PVR_RECORDING::strTitle, and PVR_RECORDING::strTitleExtraInfo.
FreeResources()
static void kodi::addon::PVRRecording::FreeResources (PVR_RECORDING * target) inline static
References kodi::addon::FreeString(), PVR_RECORDING::strChannelName, PVR_RECORDING::strDirectory, PVR_RECORDING::strEpisodeName, PVR_RECORDING::strFanartPath, PVR_RECORDING::strFirstAired, PVR_RECORDING::strGenreDescription, PVR_RECORDING::strIconPath, PVR_RECORDING::strParentalRatingCode, PVR_RECORDING::strParentalRatingIcon, PVR_RECORDING::strParentalRatingSource, PVR_RECORDING::strPlot, PVR_RECORDING::strPlotOutline, PVR_RECORDING::strProviderName, PVR_RECORDING::strRecordingId, PVR_RECORDING::strThumbnailPath, PVR_RECORDING::strTitle, and PVR_RECORDING::strTitleExtraInfo.
GetClientProviderUid()
int kodi::addon::PVRRecording::GetClientProviderUid () const inline
To get with SetClientProviderUid changed values.
References PVR_RECORDING::iClientProviderUid, and kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure.
GetParentalRating()
unsigned int kodi::addon::PVRRecording::GetParentalRating () const inline
To get with SetParentalRating changed values.
References PVR_RECORDING::iParentalRating, and kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure.
GetParentalRatingCode()
std::string kodi::addon::PVRRecording::GetParentalRatingCode () const inline
To get with SetParentalRatingCode changed values.
References kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure, and PVR_RECORDING::strParentalRatingCode.
GetParentalRatingIcon()
std::string kodi::addon::PVRRecording::GetParentalRatingIcon () const inline
To get with SetParentalRatingIcon changed values.
References kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure, and PVR_RECORDING::strParentalRatingIcon.
GetParentalRatingSource()
std::string kodi::addon::PVRRecording::GetParentalRatingSource () const inline
To get with SetParentalRatingSource changed values.
References kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure, and PVR_RECORDING::strParentalRatingSource.
GetProviderName()
std::string kodi::addon::PVRRecording::GetProviderName () const inline
To get with SetProviderName changed values.
References kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure, and PVR_RECORDING::strProviderName.
SetClientProviderUid()
void kodi::addon::PVRRecording::SetClientProviderUid (int iClientProviderUid) inline
optional
Unique identifier of the provider this channel belongs to.
PVR_PROVIDER_INVALID_UID denotes that provider uid is not available.
References PVR_RECORDING::iClientProviderUid, and kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure.
SetParentalRating()
void kodi::addon::PVRRecording::SetParentalRating (unsigned int iParentalRating) inline
optional
Age rating for the recording.
References PVR_RECORDING::iParentalRating, and kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure.
SetParentalRatingCode()
void kodi::addon::PVRRecording::SetParentalRatingCode (const std::string & ratingCode) inline
optional
Parental rating code for this recording.
References kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_RECORDING::strParentalRatingCode.
SetParentalRatingIcon()
void kodi::addon::PVRRecording::SetParentalRatingIcon (const std::string & ratingIcon) inline
optional
Parental rating icon for this recording.
References kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_RECORDING::strParentalRatingIcon.
SetParentalRatingSource()
void kodi::addon::PVRRecording::SetParentalRatingSource (const std::string & ratingSource) inline
optional
Parental rating source for this recording.
References kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_RECORDING::strParentalRatingSource.
SetProviderName()
void kodi::addon::PVRRecording::SetProviderName (const std::string & providerName) inline
optional
Name for the provider of this channel.
References kodi::addon::DynamicCStructHdl< PVRRecording, PVR_RECORDING >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_RECORDING::strProviderName.
Friends And Related Symbol Documentation
CInstancePVRClient
friend class CInstancePVRClient friend
The documentation for this class was generated from the following file:
Recordings.h