Kodi Documentation: CProfileManager Class Reference
CProfileManager Class Reference
#include <ProfileManager.h>
Public Member Functions
CProfileManager ()
CProfileManager (const CProfileManager &)=delete
CProfileManager & operator= (CProfileManager const &)=delete
~CProfileManager () override
void Initialize (const std::shared_ptr< CSettings > &settings)
void Uninitialize ()
void OnSettingsLoaded () override
Settings have been loaded.
void OnSettingsSaved () const override
Settings have been saved.
void OnSettingsCleared () override
Settings have been cleared.
bool Load ()
bool Save () const
Load the user profile information from disk Loads the profiles.xml file and creates the list of profiles. If no profiles exist, a master user is created. Should be called after special://masterprofile/ has been defined.
void Clear ()
Save the user profile information to disk Saves the list of profiles to the profiles.xml file.
bool LoadProfile (unsigned int index)
void LogOff ()
bool DeleteProfile (unsigned int index)
void CreateProfileFolders ()
const CProfile & GetMasterProfile () const
Retrieve the master profile.
const CProfile & GetCurrentProfile () const
Retrieve the current profile.
const CProfile * GetProfile (unsigned int index) const
Retrieve the profile from an index.
CProfile * GetProfile (unsigned int index)
Retrieve the profile from an index.
int GetProfileIndex (const std::string &name) const
Retrieve index of a particular profile by name.
size_t GetNumberOfProfiles () const
Retrieve the number of profiles.
void AddProfile (const CProfile &profile)
Add a new profile.
bool UsingLoginScreen () const
Are we using the login screen?
void ToggleLoginScreen ()
Toggle login screen use on and off Toggles the login screen state.
bool IsMasterProfile () const
Are we the master user?
void UpdateCurrentProfileDate ()
Update the date of the current profile.
void LoadMasterProfileForLogin ()
Load the master user for the purposes of logging in Loads the master user. Identical to LoadProfile(0) but doesn't update the last logged in details.
uint32_t GetLastUsedProfileIndex () const
Retrieve the last used profile index.
uint32_t GetCurrentProfileIndex () const
Retrieve the current profile index.
int GetNextProfileId () const
Retrieve the next id to use for a new profile.
int GetCurrentProfileId () const
int GetAutoLoginProfileId () const
Retrieve the autologin profile id Retrieves the autologin profile id. When set to -1, then the last used profile will be loaded.
void SetAutoLoginProfileId (const int profileId)
Retrieve the autologin profile id Retrieves the autologin profile id. When set to -1, then the last used profile will be loaded.
bool GetProfileName (const unsigned int profileId, std::string &name) const
Retrieve the name of a particular profile by index.
std::string GetUserDataFolder () const
std::string GetProfileUserDataFolder () const
std::string GetDatabaseFolder () const
std::string GetCDDBFolder () const
std::string GetThumbnailsFolder () const
std::string GetVideoThumbFolder () const
std::string GetBookmarksThumbFolder () const
std::string GetLibraryFolder () const
std::string GetSavestatesFolder () const
std::string GetSettingsFile () const
std::string GetUserDataItem (const std::string &strFile) const
CEventLog & GetEventLog ()
Protected Member Functions
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
Protected Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsUnloaded ()
Setting values have been unloaded.
Protected Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingChanged (const std::shared_ptr< const CSetting > &setting)
The value of the given setting has changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Private Member Functions
void SetCurrentProfileId (unsigned int profileId)
Set the current profile id and update the special://profile path.
void PrepareLoadProfile (unsigned int profileIndex)
void FinalizeLoadProfile ()
Private Attributes
std::shared_ptr< CSettings > m_settings
std::vector< CProfile > m_profiles
bool m_usingLoginScreen = false
bool m_profileLoadedForLogin = false
bool m_previousProfileLoadedForLogin = false
int m_autoLoginProfile = -1
unsigned int m_lastUsedProfile = 0
unsigned int m_currentProfile
int m_nextProfileId
CCriticalSection m_critical
std::unique_ptr< CEventLogManager > m_eventLogs
Constructor & Destructor Documentation
CProfileManager() [1/2]
CProfileManager::CProfileManager ()
CProfileManager() [2/2]
CProfileManager::CProfileManager (const CProfileManager &) delete
~CProfileManager()
CProfileManager::~CProfileManager () override default
Member Function Documentation
AddProfile()
void CProfileManager::AddProfile (const CProfile & profile)
Add a new profile.
Parameters
profile CProfile to add
References CProfile::getId(), m_critical, m_nextProfileId, m_profiles, and Save().
Referenced by Load().
Clear()
void CProfileManager::Clear ()
Save the user profile information to disk Saves the list of profiles to the profiles.xml file.
Parameters
file XML file to save.
Returns
true on success, false on failure to save
References m_critical, m_lastUsedProfile, m_nextProfileId, m_previousProfileLoadedForLogin, m_profileLoadedForLogin, m_profiles, m_usingLoginScreen, and SetCurrentProfileId().
Referenced by OnSettingsCleared().
CreateProfileFolders()
void CProfileManager::CreateProfileFolders ()
References URIUtils::AddFileToFolder(), XFILE::CDirectory::Create(), GetBookmarksThumbFolder(), GetCDDBFolder(), GetDatabaseFolder(), GetLibraryFolder(), GetSavestatesFolder(), GetThumbnailsFolder(), and GetVideoThumbFolder().
Referenced by LoadProfile().
DeleteProfile()
bool CProfileManager::DeleteProfile (unsigned int index)
References URIUtils::AddFileToFolder(), CGUIComponent::ConfirmDelete(), CFileUtils::DeleteItem(), g_localizeStrings, CLocalizeStrings::Get(), CProfile::getDirectory(), CServiceBroker::GetGUI(), CProfile::getName(), GetProfile(), GetUserDataFolder(), CGUIComponent::GetWindowManager(), index(), CGUIDialogBoxBase::IsConfirmed(), LoadProfile(), m_autoLoginProfile, m_critical, m_currentProfile, m_profiles, m_settings, CGUIDialog::Open(), Save(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), and WINDOW_DIALOG_YES_NO.
FinalizeLoadProfile()
void CProfileManager::FinalizeLoadProfile () private
References CGUIWindowManager::ChangeActiveWindow(), KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist(), g_application, g_SkinInfo, CServiceBroker::GetAddonMgr(), CServiceBroker::GetContextMenuManager(), GetCurrentProfile(), CServiceBroker::GetFavouritesService(), CServiceBroker::GetGUI(), CServiceBroker::GetNetwork(), CServiceBroker::GetPlaylistPlayer(), GetProfileUserDataFolder(), CServiceBroker::GetPVRManager(), CServiceBroker::GetServiceAddons(), CGUIComponent::GetStereoscopicsManager(), CServiceBroker::GetWeatherManager(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UI_READY, CContextMenuManager::Init(), PVR::CPVRManager::Init(), CStereoscopicsManager::Initialize(), JSONRPC::CJSONRPC::Initialize(), CLog::Log(), LOGFATAL, m_currentProfile, m_lastUsedProfile, m_previousProfileLoadedForLogin, m_profileLoadedForLogin, CNetworkBase::NetworkMessage(), CInfoLoader::Refresh(), ADDON::CAddonMgr::ReInit(), CFavouritesService::ReInit(), CNetworkBase::SERVICES_UP, KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), ADDON::CServiceAddonManager::Start(), and WINDOW_SETTINGS_PROFILES.
Referenced by LoadProfile().
GetAutoLoginProfileId()
int CProfileManager::GetAutoLoginProfileId () const inline
Retrieve the autologin profile id Retrieves the autologin profile id. When set to -1, then the last used profile will be loaded.
Returns
the id to the autologin profile
References m_autoLoginProfile.
GetBookmarksThumbFolder()
std::string CProfileManager::GetBookmarksThumbFolder () const
References URIUtils::AddFileToFolder(), and GetVideoThumbFolder().
Referenced by CreateProfileFolders().
GetCDDBFolder()
std::string CProfileManager::GetCDDBFolder () const
References URIUtils::AddFileToFolder(), and GetDatabaseFolder().
Referenced by CreateProfileFolders(), CMusicDatabase::DeleteCDDBInfo(), and CMusicDatabase::LookupCDDBInfo().
GetCurrentProfile()
const CProfile & CProfileManager::GetCurrentProfile () const
Retrieve the current profile.
Returns
const reference to the current profile
References EmptyProfile, CLog::Log(), LOGERROR, m_critical, m_currentProfile, and m_profiles.
Referenced by FinalizeLoadProfile(), CSettingConditions::GetCurrentProfile(), GetCurrentProfileId(), GetDatabaseFolder(), GetLibraryFolder(), GetProfileUserDataFolder(), GetSavestatesFolder(), and GetThumbnailsFolder().
GetCurrentProfileId()
int CProfileManager::GetCurrentProfileId () const inline
References GetCurrentProfile(), and CProfile::getId().
Referenced by GetEventLog().
GetCurrentProfileIndex()
uint32_t CProfileManager::GetCurrentProfileIndex () const inline
Retrieve the current profile index.
Returns
the index of the currently logged in profile.
References m_currentProfile.
GetDatabaseFolder()
std::string CProfileManager::GetDatabaseFolder () const
References URIUtils::AddFileToFolder(), GetCurrentProfile(), GetProfileUserDataFolder(), and GetUserDataFolder().
Referenced by CreateProfileFolders(), GetCDDBFolder(), CDatabase::InitSettings(), and CSpecialProtocol::TranslatePath().
GetEventLog()
CEventLog & CProfileManager::GetEventLog ()
References GetCurrentProfileId(), and m_eventLogs.
Referenced by OnSettingAction().
GetLastUsedProfileIndex()
uint32_t CProfileManager::GetLastUsedProfileIndex () const inline
Retrieve the last used profile index.
Returns
the last used profile that logged in. Does not count the master user during login.
References m_lastUsedProfile.
GetLibraryFolder()
std::string CProfileManager::GetLibraryFolder () const
References URIUtils::AddFileToFolder(), GetCurrentProfile(), GetProfileUserDataFolder(), and GetUserDataFolder().
Referenced by CreateProfileFolders(), and XFILE::CLibraryDirectory::GetNode().
GetMasterProfile()
const CProfile & CProfileManager::GetMasterProfile () const
Retrieve the master profile.
Returns
const reference to the master profile
References EmptyProfile, CLog::Log(), LOGERROR, m_critical, and m_profiles.
Referenced by XFILE::CSourcesDirectory::GetDirectory(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetMatchingMusicVideo(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), GetUserDataFolder(), and CVideoDatabase::GetYearsNav().
GetNextProfileId()
int CProfileManager::GetNextProfileId () const inline
Retrieve the next id to use for a new profile.
Returns
the unique <id> to be used when creating a new profile
References m_nextProfileId.
Referenced by Load().
GetNumberOfProfiles()
size_t CProfileManager::GetNumberOfProfiles () const inline
Retrieve the number of profiles.
Returns
number of profiles
References m_profiles.
GetProfile() [1/2]
CProfile * CProfileManager::GetProfile (unsigned int index)
Retrieve the profile from an index.
Parameters
unsigned index of the profile to retrieve
Returns
pointer to the profile, NULL if the index is invalid
References index(), m_critical, and m_profiles.
GetProfile() [2/2]
const CProfile * CProfileManager::GetProfile (unsigned int index) const
Retrieve the profile from an index.
Parameters
unsigned index of the profile to retrieve
Returns
const pointer to the profile, NULL if the index is invalid
References index(), m_critical, and m_profiles.
Referenced by DeleteProfile(), and GetProfileName().
GetProfileIndex()
int CProfileManager::GetProfileIndex (const std::string & name) const
Retrieve index of a particular profile by name.
Parameters
name name of the profile index to retrieve
Returns
index of this profile, -1 if invalid.
References m_critical, m_profiles, and name.
GetProfileName()
bool CProfileManager::GetProfileName (const unsigned int profileId, std::string & name) const
Retrieve the name of a particular profile by index.
Parameters
profileId profile index for which to retrieve the name
name will hold the name of the profile when a valid profile index has been provided
Returns
false if profileId is an invalid index, true if the name parameter is set
References CProfile::getName(), GetProfile(), m_critical, and name.
GetProfileUserDataFolder()
std::string CProfileManager::GetProfileUserDataFolder () const
References URIUtils::AddFileToFolder(), GetCurrentProfile(), GetUserDataFolder(), and m_currentProfile.
Referenced by XFILE::CFavouritesDirectory::Exists(), FinalizeLoadProfile(), GetDatabaseFolder(), GetLibraryFolder(), GetSavestatesFolder(), GetThumbnailsFolder(), and SetCurrentProfileId().
GetSavestatesFolder()
std::string CProfileManager::GetSavestatesFolder () const
References URIUtils::AddFileToFolder(), GetCurrentProfile(), GetProfileUserDataFolder(), and GetUserDataFolder().
Referenced by CreateProfileFolders(), and KODI::GAME::CGameServices::GetSavestatesFolder().
GetSettingsFile()
std::string CProfileManager::GetSettingsFile () const
References m_currentProfile.
GetThumbnailsFolder()
std::string CProfileManager::GetThumbnailsFolder () const
References URIUtils::AddFileToFolder(), GetCurrentProfile(), GetProfileUserDataFolder(), and GetUserDataFolder().
Referenced by CreateProfileFolders(), GetVideoThumbFolder(), and CSpecialProtocol::TranslatePath().
GetUserDataFolder()
std::string CProfileManager::GetUserDataFolder () const
References CProfile::getDirectory(), and GetMasterProfile().
Referenced by DeleteProfile(), GetDatabaseFolder(), GetLibraryFolder(), GetProfileUserDataFolder(), GetSavestatesFolder(), GetThumbnailsFolder(), LoadProfile(), and CSpecialProtocol::TranslatePath().
GetUserDataItem()
std::string CProfileManager::GetUserDataItem (const std::string & strFile) const
References XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), and URIUtils::HasSlashAtEnd().
Referenced by CAdvancedSettings::Load(), and CPlayerCoreFactory::OnSettingsLoaded().
GetVideoThumbFolder()
std::string CProfileManager::GetVideoThumbFolder () const
References URIUtils::AddFileToFolder(), and GetThumbnailsFolder().
Referenced by CreateProfileFolders(), and GetBookmarksThumbFolder().
Initialize()
void CProfileManager::Initialize (const std::shared_ptr< CSettings > & settings)
References m_settings, OnSettingsLoaded(), and CSettings::SETTING_EVENTLOG_SHOW.
IsMasterProfile()
bool CProfileManager::IsMasterProfile () const inline
Are we the master user?
Returns
true if the current profile is the master user, false otherwise
References m_currentProfile.
Referenced by LoadProfile(), and PrepareLoadProfile().
Load()
bool CProfileManager::Load ()
References AddProfile(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), XMLUtils::GetBoolean(), XMLUtils::GetInt(), GetNextProfileId(), XMLUtils::GetUInt(), CProfile::Load(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGERROR, m_autoLoginProfile, m_critical, m_lastUsedProfile, m_nextProfileId, m_profiles, m_usingLoginScreen, PROFILES_FILE, SetCurrentProfileId(), XML_AUTO_LOGIN, XML_LAST_LOADED, XML_LOGIN_SCREEN, XML_NEXTID, XML_PROFILE, and XML_PROFILES.
LoadMasterProfileForLogin()
void CProfileManager::LoadMasterProfileForLogin ()
Load the master user for the purposes of logging in Loads the master user. Identical to LoadProfile(0) but doesn't update the last logged in details.
References LoadProfile(), m_critical, m_currentProfile, m_lastUsedProfile, m_previousProfileLoadedForLogin, and m_profileLoadedForLogin.
Referenced by LogOff().
LoadProfile()
bool CProfileManager::LoadProfile (unsigned int index)
References URIUtils::AddFileToFolder(), XFILE::CDirectoryCache::Clear(), CPasswordManager::Clear(), CreateProfileFolders(), CUtil::DeleteDirectoryCache(), FinalizeLoadProfile(), g_directoryCache, g_SkinInfo, CServiceBroker::GetDatabaseManager(), CServiceBroker::GetGUI(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetGUIControlsInfoProvider(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CServiceBroker::GetInputManager(), CPasswordManager::GetInstance(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetLibraryInfoProvider(), CServiceBroker::GetSettingsComponent(), GetUserDataFolder(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_WINDOW_RESET, index(), CDatabaseManager::Initialize(), IsMasterProfile(), CXBMCTinyXML::LoadFile(), CInputManager::LoadKeymaps(), CLog::Log(), LOGFATAL, m_critical, m_currentProfile, m_previousProfileLoadedForLogin, m_profileLoadedForLogin, m_profiles, PrepareLoadProfile(), CGUIInfoManager::ResetCache(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::ResetContainerMovingCache(), CGUIWindow::ResetControlStates(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::ResetLibraryBools(), CGUIWindowManager::SendMessage(), SetCurrentProfileId(), CInputManager::SetMouseEnabled(), CSettings::SETTING_INPUT_ENABLEMOUSE, CSettings::SETTING_MASTERLOCK_MAXRETRIES, CSettings::SETTING_MASTERLOCK_STARTUPLOCK, UpdateCurrentProfileDate(), and WINDOW_HOME.
Referenced by DeleteProfile(), and LoadMasterProfileForLogin().
LogOff()
void CProfileManager::LogOff ()
References CGUIWindowManager::ActivateWindow(), CGUIPassword::bMasterUser, CVideoLibraryQueue::CancelAllJobs(), g_application, g_localizeStrings, g_passwordManager, CLocalizeStrings::Get(), CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CMusicLibraryQueue::GetInstance(), CVideoLibraryQueue::GetInstance(), CServiceBroker::GetNetwork(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), LoadMasterProfileForLogin(), CNetworkBase::NetworkMessage(), CGUIDialogKaiToast::QueueNotification(), CNetworkBase::SERVICES_DOWN, PVR::CPVRManager::Stop(), CMusicLibraryQueue::StopLibraryScanning(), CApplicationPowerHandling::WakeUpScreenSaverAndDPMS(), CGUIDialogKaiToast::Warning, and WINDOW_LOGIN_SCREEN.
OnSettingAction()
void CProfileManager::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override protected virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References GetEventLog(), CSettings::SETTING_EVENTLOG_SHOW, and CEventLog::ShowFullEventLog().
OnSettingsCleared()
void CProfileManager::OnSettingsCleared () override virtual
Settings have been cleared.
This callback can be used to trigger clearing any state variables.
Reimplemented from ISettingsHandler.
References Clear().
OnSettingsLoaded()
void CProfileManager::OnSettingsLoaded () override virtual
Settings have been loaded.
This callback can be used to trigger loading other settings.
Reimplemented from ISettingsHandler.
References URIUtils::AddFileToFolder(), XFILE::CDirectory::Create(), m_settings, and CSettings::SETTING_SYSTEM_PLAYLISTSPATH.
Referenced by Initialize().
OnSettingsSaved()
void CProfileManager::OnSettingsSaved () const override virtual
Settings have been saved.
This callback can be used to trigger saving other settings.
Reimplemented from ISettingsHandler.
References Save().
operator=()
CProfileManager & CProfileManager::operator= (CProfileManager const &) delete
PrepareLoadProfile()
void CProfileManager::PrepareLoadProfile (unsigned int profileIndex) private
References CContextMenuManager::Deinit(), CServiceBroker::GetContextMenuManager(), CServiceBroker::GetNetwork(), CServiceBroker::GetPVRManager(), CServiceBroker::GetServiceAddons(), IsMasterProfile(), CNetworkBase::NetworkMessage(), CNetworkBase::SERVICES_DOWN, ADDON::CServiceAddonManager::Stop(), and PVR::CPVRManager::Stop().
Referenced by LoadProfile().
Save()
bool CProfileManager::Save () const
Load the user profile information from disk Loads the profiles.xml file and creates the list of profiles. If no profiles exist, a master user is created. Should be called after special://masterprofile/ has been defined.
Parameters
file XML file to load.
References m_autoLoginProfile, m_critical, m_currentProfile, m_nextProfileId, m_profiles, m_usingLoginScreen, PROFILES_FILE, CXBMCTinyXML::SaveFile(), XMLUtils::SetBoolean(), XMLUtils::SetInt(), XML_AUTO_LOGIN, XML_LAST_LOADED, XML_LOGIN_SCREEN, XML_NEXTID, and XML_PROFILES.
Referenced by AddProfile(), DeleteProfile(), OnSettingsSaved(), SetAutoLoginProfileId(), SetCurrentProfileId(), ToggleLoginScreen(), and UpdateCurrentProfileDate().
SetAutoLoginProfileId()
void CProfileManager::SetAutoLoginProfileId (const int profileId) inline
Retrieve the autologin profile id Retrieves the autologin profile id. When set to -1, then the last used profile will be loaded.
Returns
the id to the autologin profile
References m_autoLoginProfile, and Save().
SetCurrentProfileId()
void CProfileManager::SetCurrentProfileId (unsigned int profileId) private
Set the current profile id and update the special://profile path.
Parameters
profileId profile index
References GetProfileUserDataFolder(), m_critical, m_currentProfile, Save(), and CSpecialProtocol::SetProfilePath().
Referenced by Clear(), Load(), and LoadProfile().
ToggleLoginScreen()
void CProfileManager::ToggleLoginScreen () inline
Toggle login screen use on and off Toggles the login screen state.
References m_usingLoginScreen, and Save().
Uninitialize()
void CProfileManager::Uninitialize ()
References m_settings.
UpdateCurrentProfileDate()
void CProfileManager::UpdateCurrentProfileDate ()
Update the date of the current profile.
References m_critical, m_currentProfile, m_profiles, and Save().
Referenced by LoadProfile().
UsingLoginScreen()
bool CProfileManager::UsingLoginScreen () const inline
Are we using the login screen?
Returns
true if we're using the login screen, false otherwise
References m_usingLoginScreen.
Member Data Documentation
m_autoLoginProfile
int CProfileManager::m_autoLoginProfile = -1 private
Referenced by DeleteProfile(), GetAutoLoginProfileId(), Load(), Save(), and SetAutoLoginProfileId().
m_critical
CCriticalSection CProfileManager::m_critical mutable private
Referenced by AddProfile(), Clear(), DeleteProfile(), GetCurrentProfile(), GetMasterProfile(), GetProfile(), GetProfile(), GetProfileIndex(), GetProfileName(), Load(), LoadMasterProfileForLogin(), LoadProfile(), Save(), SetCurrentProfileId(), and UpdateCurrentProfileDate().
m_currentProfile
unsigned int CProfileManager::m_currentProfile private
Initial value:
=
      0
Referenced by DeleteProfile(), FinalizeLoadProfile(), GetCurrentProfile(), GetCurrentProfileIndex(), GetProfileUserDataFolder(), GetSettingsFile(), IsMasterProfile(), LoadMasterProfileForLogin(), LoadProfile(), Save(), SetCurrentProfileId(), and UpdateCurrentProfileDate().
m_eventLogs
std::unique_ptr<CEventLogManager> CProfileManager::m_eventLogs private
Referenced by GetEventLog().
m_lastUsedProfile
unsigned int CProfileManager::m_lastUsedProfile = 0 private
Referenced by Clear(), FinalizeLoadProfile(), GetLastUsedProfileIndex(), Load(), and LoadMasterProfileForLogin().
m_nextProfileId
int CProfileManager::m_nextProfileId private
Initial value:
=
      0
Referenced by AddProfile(), Clear(), GetNextProfileId(), Load(), and Save().
m_previousProfileLoadedForLogin
bool CProfileManager::m_previousProfileLoadedForLogin = false private
Referenced by Clear(), FinalizeLoadProfile(), LoadMasterProfileForLogin(), and LoadProfile().
m_profileLoadedForLogin
bool CProfileManager::m_profileLoadedForLogin = false private
Referenced by Clear(), FinalizeLoadProfile(), LoadMasterProfileForLogin(), and LoadProfile().
m_profiles
std::vector<CProfile> CProfileManager::m_profiles private
Referenced by AddProfile(), Clear(), DeleteProfile(), GetCurrentProfile(), GetMasterProfile(), GetNumberOfProfiles(), GetProfile(), GetProfile(), GetProfileIndex(), Load(), LoadProfile(), Save(), and UpdateCurrentProfileDate().
m_settings
std::shared_ptr<CSettings> CProfileManager::m_settings private
Referenced by DeleteProfile(), Initialize(), OnSettingsLoaded(), and Uninitialize().
m_usingLoginScreen
bool CProfileManager::m_usingLoginScreen = false private
Referenced by Clear(), Load(), Save(), ToggleLoginScreen(), and UsingLoginScreen().
The documentation for this class was generated from the following files:
ProfileManager.h
ProfileManager.cpp