Kodi Documentation: XFILE::CPluginDirectory Class Reference
XFILE::CPluginDirectory Class Reference
#include <PluginDirectory.h>
Public Member Functions
CPluginDirectory ()
~CPluginDirectory (void) override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool Resolve (CFileItem &item) const override
Resolves a given item to a playable item.
bool AllowAll () const override
Whether to allow all files/folders to be listed.
bool Exists (const CURL &url) override
Check for directory existence.
float GetProgress () const override
Retrieve the progress of the current directory fetch (if possible).
void CancelDirectory () override
Cancel the current directory fetch (if possible).
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual bool Create (const CURL &url)
Create the directory.
virtual bool Remove (const CURL &url)
Removes the directory.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
Static Public Member Functions
static bool RunScriptWithParams (const std::string &strPath, bool resume)
static bool GetResolvedPluginResult (CFileItem &resultItem)
Get a reproducible CFileItem by trying to recursively resolve the plugin paths up to a maximum allowed limit. If no plugin paths exist it will be ignored.
static bool GetPluginResult (const std::string &strPath, CFileItem &resultItem, bool resume)
static bool IsMediaLibraryScanningAllowed (const std::string &content, const std::string &strPath)
Check whether a plugin supports media library scanning.
static bool CheckExists (const std::string &content, const std::string &strPath)
Check whether a plugin url exists by calling the plugin and checking result. Applies only to plugins that support media library scanning.
static bool AddItem (int handle, const CFileItem *item, int totalItems)
static bool AddItems (int handle, const CFileItemList *items, int totalItems)
static void EndOfDirectory (int handle, bool success, bool replaceListing, bool cacheToDisc)
static void AddSortMethod (int handle, SORT_METHOD sortMethod, const std::string &labelMask, const std::string &label2Mask)
static std::string GetSetting (int handle, const std::string &key)
static void SetSetting (int handle, const std::string &key, const std::string &value)
static void SetContent (int handle, const std::string &strContent)
static void SetProperty (int handle, const std::string &strProperty, const std::string &strValue)
static void SetResolvedUrl (int handle, bool success, const CFileItem *resultItem)
static void SetLabel2 (int handle, const std::string &ident)
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Protected Member Functions
bool IsSuccessful () const override
bool IsCancelled () const override
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Member Functions inherited from CRunningScriptsHandler< CPluginDirectory >
CRunningScriptsHandler ()=default
virtual ~CRunningScriptsHandler ()=default
bool RunScript (CPluginDirectory *script, const ADDON::AddonPtr &addon, const std::string &path, bool resume)
ADDON::AddonPtr GetAddon () const
void SetDone ()
bool StartScript (const ADDON::AddonPtr &addon, const std::string &path)
Protected Member Functions inherited from CScriptRunner
CScriptRunner ()
virtual ~CScriptRunner ()=default
ADDON::AddonPtr GetAddon () const
bool StartScript (const ADDON::AddonPtr &addon, const std::string &path)
bool RunScript (const ADDON::AddonPtr &addon, const std::string &path, int handle, bool resume)
void SetDone ()
Private Member Functions
bool StartScript (const std::string &strPath, bool resume)
Private Attributes
std::unique_ptr< CFileItemList > m_listItems
std::unique_ptr< CFileItem > m_fileResult
std::atomic< bool > m_cancelled
bool m_success = false
int m_totalItems = 0
Additional Inherited Members
Protected Types inherited from CRunningScriptsHandler< CPluginDirectory >
using HandleType = int
Static Protected Member Functions inherited from CRunningScriptsHandler< CPluginDirectory >
static HandleType GetNewScriptHandle (CPluginDirectory *script)
static void ReuseScriptHandle (HandleType handle, CPluginDirectory *script)
static void RemoveScriptHandle (HandleType handle)
static CPluginDirectory * GetScriptFromHandle (HandleType handle)
static CCriticalSection & GetScriptsLock ()
static int ExecuteScript (const ADDON::AddonPtr &addon, const std::string &path, bool resume)
static int ExecuteScript (const ADDON::AddonPtr &addon, const std::string &path, int handle, bool resume)
Static Protected Member Functions inherited from CScriptRunner
static int ExecuteScript (const ADDON::AddonPtr &addon, const std::string &path, bool resume)
static int ExecuteScript (const ADDON::AddonPtr &addon, const std::string &path, int handle, bool resume)
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CPluginDirectory()
CPluginDirectory::CPluginDirectory ()
~CPluginDirectory()
CPluginDirectory::~CPluginDirectory (void) override
Member Function Documentation
AddItem()
bool CPluginDirectory::AddItem (int handle, const CFileItem * item, int totalItems) static
References CRunningScriptsHandler< CPluginDirectory >::GetScriptFromHandle(), CRunningScriptsHandler< CPluginDirectory >::GetScriptsLock(), m_cancelled, m_listItems, and m_totalItems.
Referenced by XBMCAddon::xbmcplugin::addDirectoryItem().
AddItems()
bool CPluginDirectory::AddItems (int handle, const CFileItemList * items, int totalItems) static
References CFileItemList::Copy(), CRunningScriptsHandler< CPluginDirectory >::GetScriptFromHandle(), CRunningScriptsHandler< CPluginDirectory >::GetScriptsLock(), m_cancelled, m_listItems, and m_totalItems.
Referenced by XBMCAddon::xbmcplugin::addDirectoryItems().
AddSortMethod()
void CPluginDirectory::AddSortMethod (int handle, SORT_METHOD sortMethod, const std::string & labelMask, const std::string & label2Mask) static
Todo:
Add all sort methods and fix which labels go on the right or left
References CRunningScriptsHandler< CPluginDirectory >::GetScriptFromHandle(), CRunningScriptsHandler< CPluginDirectory >::GetScriptsLock(), CServiceBroker::GetSettingsComponent(), m_listItems, CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CSettings::SETTING_MUSICFILES_TRACKFORMAT, SORT_METHOD_ALBUM, SORT_METHOD_ALBUM_IGNORE_THE, SORT_METHOD_ARTIST, SORT_METHOD_ARTIST_IGNORE_THE, SORT_METHOD_BITRATE, SORT_METHOD_CHANNEL, SORT_METHOD_COUNTRY, SORT_METHOD_DATE, SORT_METHOD_DATEADDED, SORT_METHOD_DRIVE_TYPE, SORT_METHOD_DURATION, SORT_METHOD_EPISODE, SORT_METHOD_FILE, SORT_METHOD_FULLPATH, SORT_METHOD_GENRE, SORT_METHOD_LABEL, SORT_METHOD_LABEL_IGNORE_FOLDERS, SORT_METHOD_LABEL_IGNORE_THE, SORT_METHOD_LASTPLAYED, SORT_METHOD_LISTENERS, SORT_METHOD_MPAA_RATING, SORT_METHOD_NONE, SORT_METHOD_PLAYCOUNT, SORT_METHOD_PLAYLIST_ORDER, SORT_METHOD_PRODUCTIONCODE, SORT_METHOD_PROGRAM_COUNT, SORT_METHOD_SIZE, SORT_METHOD_SONG_RATING, SORT_METHOD_STUDIO, SORT_METHOD_STUDIO_IGNORE_THE, SORT_METHOD_TITLE, SORT_METHOD_TITLE_IGNORE_THE, SORT_METHOD_TRACKNUM, SORT_METHOD_UNSORTED, SORT_METHOD_VIDEO_ORIGINAL_TITLE, SORT_METHOD_VIDEO_ORIGINAL_TITLE_IGNORE_THE, SORT_METHOD_VIDEO_RATING, SORT_METHOD_VIDEO_RUNTIME, SORT_METHOD_VIDEO_SORT_TITLE, SORT_METHOD_VIDEO_SORT_TITLE_IGNORE_THE, SORT_METHOD_VIDEO_TITLE, SORT_METHOD_YEAR, SortAttributeIgnoreArticle, SortAttributeIgnoreFolders, SortAttributeNone, SortByAlbum, SortByArtist, SortByBitrate, SortByChannel, SortByCountry, SortByDate, SortByDateAdded, SortByDriveType, SortByEpisodeNumber, SortByFile, SortByGenre, SortByLabel, SortByLastPlayed, SortByListeners, SortByMPAA, SortByNone, SortByOriginalTitle, SortByPath, SortByPlaycount, SortByPlaylistOrder, SortByProductionCode, SortByProgramCount, SortByRating, SortBySize, SortBySortTitle, SortByStudio, SortByTime, SortByTitle, SortByTrackNumber, and SortByYear.
Referenced by XBMCAddon::xbmcplugin::addSortMethod().
AllowAll()
bool XFILE::CPluginDirectory::AllowAll () const inline override virtual
Whether to allow all files/folders to be listed.
Returns
Returns true if all files/folder should be listed.
Reimplemented from XFILE::IDirectory.
CancelDirectory()
void CPluginDirectory::CancelDirectory () override virtual
Cancel the current directory fetch (if possible).
See also
GetDirectory
Reimplemented from XFILE::IDirectory.
References m_cancelled.
CheckExists()
bool CPluginDirectory::CheckExists (const std::string & content, const std::string & strPath) static
Check whether a plugin url exists by calling the plugin and checking result. Applies only to plugins that support media library scanning.
Parameters
content content type - movies, tvshows, musicvideos.
strPath full plugin url.
Returns
true if the plugin supports scanning and specified url exists, false otherwise.
References ADDON::content, CURL::Get(), GetPluginResult(), IsMediaLibraryScanningAllowed(), and CURL::SetOption().
Referenced by CVideoDatabase::CleanDatabase().
EndOfDirectory()
void CPluginDirectory::EndOfDirectory (int handle, bool success, bool replaceListing, bool cacheToDisc) static
References CFileItemList::CACHE_IF_SLOW, CFileItemList::CACHE_NEVER, CRunningScriptsHandler< CPluginDirectory >::GetScriptFromHandle(), CRunningScriptsHandler< CPluginDirectory >::GetScriptsLock(), m_listItems, m_success, CRunningScriptsHandler< TScript >::SetDone(), SortByNone, and success.
Referenced by XBMCAddon::xbmcplugin::endOfDirectory().
Exists()
bool XFILE::CPluginDirectory::Exists (const CURL & url) inline override virtual
Check for directory existence.
Parameters
url Directory to check.
Returns
Returns true, if directory exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
GetDirectory()
bool CPluginDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References CFileItemList::Assign(), CURL::Get(), m_listItems, StartScript(), and success.
Referenced by CVideoTagLoaderPlugin::Load().
GetPluginResult()
bool CPluginDirectory::GetPluginResult (const std::string & strPath, CFileItem & resultItem, bool resume) static
References CVariant::asBoolean(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CGUIListItem::HasProperty(), m_fileResult, CFileItem::MergeInfo(), CFileItem::SetContentLookup(), CFileItem::SetDynPath(), CFileItem::SetMimeType(), CGUIListItem::SetProperty(), CFileItem::SetStartOffset(), STARTOFFSET_RESUME, StartScript(), success, and CFileItem::UpdateInfo().
Referenced by CheckExists(), GetResolvedPluginResult(), CApplication::OnMessage(), ADDON::PythonDetails(), and ADDON::CScraper::ResolveIDToUrl().
GetProgress()
float CPluginDirectory::GetProgress () const override virtual
Retrieve the progress of the current directory fetch (if possible).
Returns
the progress as a float in the range 0..100.
See also
GetDirectory, CancelDirectory
Reimplemented from XFILE::IDirectory.
References m_listItems, and m_totalItems.
GetResolvedPluginResult()
bool CPluginDirectory::GetResolvedPluginResult (CFileItem & resultItem) static
Get a reproducible CFileItem by trying to recursively resolve the plugin paths up to a maximum allowed limit. If no plugin paths exist it will be ignored.
Parameters
resultItem the CFileItem with plugin paths to be resolved.
Returns
false if the plugin path cannot be resolved, true otherwise.
References CVariant::asBoolean(), CFileItem::GetDynPath(), CFileItem::GetPath(), GetPluginResult(), CGUIListItem::GetProperty(), CFileItem::GetStartOffset(), CGUIListItem::HasProperty(), URIUtils::IsPlugin(), and STARTOFFSET_RESUME.
Referenced by KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CApplication::PlayMedia(), and Resolve().
GetSetting()
std::string CPluginDirectory::GetSetting (int handle, const std::string & key) static
References CRunningScriptsHandler< TScript >::GetAddon(), CRunningScriptsHandler< CPluginDirectory >::GetScriptFromHandle(), and CRunningScriptsHandler< CPluginDirectory >::GetScriptsLock().
Referenced by XBMCAddon::xbmcplugin::getSetting().
IsCancelled()
bool XFILE::CPluginDirectory::IsCancelled () const inline override protected virtual
Implements CScriptRunner.
References m_cancelled.
IsMediaLibraryScanningAllowed()
bool CPluginDirectory::IsMediaLibraryScanningAllowed (const std::string & content, const std::string & strPath) static
Check whether a plugin supports media library scanning.
Parameters
content content type - movies, tvshows, musicvideos.
strPath full plugin url.
Returns
true if scanning at specified url is allowed, false otherwise.
References ADDON::content, CRunningScriptsHandler< CPluginDirectory >::GetAddon(), CServiceBroker::GetAddonMgr(), CURL::GetFileName(), CURL::GetHostName(), CLog::Log(), LOGERROR, ADDON::CPluginSource::MediaLibraryScanPaths(), and URIUtils::PathHasParent().
Referenced by CheckExists(), KODI::VIDEO::CVideoInfoScanner::DoScan(), and CVideoLibraryRefreshingJob::Work().
IsSuccessful()
bool XFILE::CPluginDirectory::IsSuccessful () const inline override protected virtual
Implements CScriptRunner.
References m_success.
Resolve()
bool CPluginDirectory::Resolve (CFileItem & item) const override virtual
Resolves a given item to a playable item.
Note
Some directories (e.g. dvd, bluray, plugins etc) need to be translated/resolved to the actual playback url
Parameters
item The item being manipulated (which the path points to a vfs protocol implementation)
Returns
true if the item was resolved, false if it failed to resolve
Reimplemented from XFILE::IDirectory.
References GetResolvedPluginResult().
RunScriptWithParams()
bool CPluginDirectory::RunScriptWithParams (const std::string & strPath, bool resume) static
References CRunningScriptsHandler< CPluginDirectory >::ExecuteScript(), CRunningScriptsHandler< CPluginDirectory >::GetAddon(), CServiceBroker::GetAddonMgr(), CURL::GetHostName(), ADDON::CAddonInstaller::GetInstance(), ADDON::CAddonInstaller::InstallModal(), CLog::Log(), and LOGERROR.
Referenced by CGUIMediaWindow::OnClick(), and RunPlugin().
SetContent()
void CPluginDirectory::SetContent (int handle, const std::string & strContent) static
References CRunningScriptsHandler< CPluginDirectory >::GetScriptFromHandle(), CRunningScriptsHandler< CPluginDirectory >::GetScriptsLock(), and m_listItems.
Referenced by XBMCAddon::xbmcplugin::setContent().
SetLabel2()
static void XFILE::CPluginDirectory::SetLabel2 (int handle, const std::string & ident) static
SetProperty()
void CPluginDirectory::SetProperty (int handle, const std::string & strProperty, const std::string & strValue) static
References CRunningScriptsHandler< CPluginDirectory >::GetScriptFromHandle(), CRunningScriptsHandler< CPluginDirectory >::GetScriptsLock(), and m_listItems.
Referenced by XBMCAddon::xbmcplugin::setPluginCategory(), XBMCAddon::xbmcplugin::setPluginFanart(), and XBMCAddon::xbmcplugin::setProperty().
SetResolvedUrl()
void CPluginDirectory::SetResolvedUrl (int handle, bool success, const CFileItem * resultItem) static
References CRunningScriptsHandler< CPluginDirectory >::GetScriptFromHandle(), CRunningScriptsHandler< CPluginDirectory >::GetScriptsLock(), m_fileResult, m_success, CRunningScriptsHandler< TScript >::SetDone(), and success.
Referenced by XBMCAddon::xbmcplugin::setResolvedUrl().
SetSetting()
void CPluginDirectory::SetSetting (int handle, const std::string & key, const std::string & value) static
References CRunningScriptsHandler< TScript >::GetAddon(), CRunningScriptsHandler< CPluginDirectory >::GetScriptFromHandle(), CRunningScriptsHandler< CPluginDirectory >::GetScriptsLock(), and value.
Referenced by XBMCAddon::xbmcplugin::setSetting().
StartScript()
bool CPluginDirectory::StartScript (const std::string & strPath, bool resume) private
References CRunningScriptsHandler< CPluginDirectory >::GetAddon(), ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), CURL::GetHostName(), ADDON::CAddonInstaller::GetInstance(), ADDON::CAddonInstaller::InstallModal(), CLog::Log(), LOGERROR, m_cancelled, m_fileResult, m_listItems, m_success, m_totalItems, and CRunningScriptsHandler< CPluginDirectory >::RunScript().
Referenced by GetDirectory(), and GetPluginResult().
Member Data Documentation
m_cancelled
std::atomic<bool> XFILE::CPluginDirectory::m_cancelled private
Referenced by AddItem(), AddItems(), CancelDirectory(), IsCancelled(), and StartScript().
m_fileResult
std::unique_ptr<CFileItem> XFILE::CPluginDirectory::m_fileResult private
Referenced by GetPluginResult(), SetResolvedUrl(), and StartScript().
m_listItems
std::unique_ptr<CFileItemList> XFILE::CPluginDirectory::m_listItems private
Referenced by AddItem(), AddItems(), AddSortMethod(), EndOfDirectory(), GetDirectory(), GetProgress(), SetContent(), SetProperty(), and StartScript().
m_success
bool XFILE::CPluginDirectory::m_success = false private
Referenced by EndOfDirectory(), IsSuccessful(), SetResolvedUrl(), and StartScript().
m_totalItems
int XFILE::CPluginDirectory::m_totalItems = 0 private
Referenced by AddItem(), AddItems(), GetProgress(), and StartScript().
The documentation for this class was generated from the following files:
PluginDirectory.h
PluginDirectory.cpp