Kodi Documentation: KODI::RETRO::CRenderVideoSettings Class Reference
KODI::RETRO::CRenderVideoSettings Class Reference
Video settings provided by the rendering system.
#include <RenderVideoSettings.h>
Public Member Functions
CRenderVideoSettings ()
void Reset ()
bool operator== (const CRenderVideoSettings &rhs) const
bool operator!= (const CRenderVideoSettings &rhs) const
bool operator< (const CRenderVideoSettings &rhs) const
bool operator> (const CRenderVideoSettings &rhs) const
std::string GetVideoFilter () const
Get a string representation of the video filter parameters.
void SetVideoFilter (const std::string &videoFilter)
SCALINGMETHOD GetScalingMethod () const
void SetScalingMethod (SCALINGMETHOD method)
STRETCHMODE GetRenderStretchMode () const
void SetRenderStretchMode (STRETCHMODE mode)
unsigned int GetRenderRotation () const
void SetRenderRotation (unsigned int rotationDegCCW)
const std::string & GetPixels () const
void SetPixels (const std::string &pixelPath)
void ResetPixels ()
Private Attributes
SCALINGMETHOD m_scalingMethod
STRETCHMODE m_stretchMode
unsigned int m_rotationDegCCW
std::string m_pixelPath
Detailed Description
Video settings provided by the rendering system.
Constructor & Destructor Documentation
CRenderVideoSettings()
KODI::RETRO::CRenderVideoSettings::CRenderVideoSettings () inline
References Reset().
Member Function Documentation
GetPixels()
const std::string & KODI::RETRO::CRenderVideoSettings::GetPixels () const inline
References m_pixelPath.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), and KODI::RETRO::CRPRenderManager::GetRendererForSettings().
GetRenderRotation()
unsigned int KODI::RETRO::CRenderVideoSettings::GetRenderRotation () const inline
References m_rotationDegCCW.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), KODI::RETRO::CRPRenderManager::GetRendererForSettings(), and KODI::RETRO::CRPBaseRenderer::ManageRenderArea().
GetRenderStretchMode()
STRETCHMODE KODI::RETRO::CRenderVideoSettings::GetRenderStretchMode () const inline
References m_stretchMode.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), KODI::RETRO::CRPRenderManager::GetRendererForSettings(), KODI::RETRO::CRPBaseRenderer::ManageRenderArea(), and KODI::RETRO::CRPRenderManager::RenderWindow().
GetScalingMethod()
SCALINGMETHOD KODI::RETRO::CRenderVideoSettings::GetScalingMethod () const inline
References m_scalingMethod.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), KODI::RETRO::CRPRenderManager::GetRendererForSettings(), KODI::RETRO::CRenderBufferPoolDMA::IsCompatible(), KODI::RETRO::CRenderBufferPoolOpenGL::IsCompatible(), KODI::RETRO::CRenderBufferPoolOpenGLES::IsCompatible(), KODI::RETRO::CRenderBufferPoolGuiTexture::IsCompatible(), KODI::RETRO::CWinRenderBufferPool::IsCompatible(), KODI::RETRO::CRPBaseRenderer::ManageRenderArea(), KODI::RETRO::CRPWinRenderer::Render(), and KODI::RETRO::CRPRenderManager::RenderWindow().
GetVideoFilter()
std::string CRenderVideoSettings::GetVideoFilter () const
Get a string representation of the video filter parameters.
References KODI::RETRO::LINEAR, m_scalingMethod, KODI::RETRO::NEAREST, VIDEO_FILTER_LINEAR, and VIDEO_FILTER_NEAREST.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), and KODI::GAME::CDialogGameVideoFilter::InitVideoFilters().
operator!=()
bool KODI::RETRO::CRenderVideoSettings::operator!= (const CRenderVideoSettings & rhs) const inline
operator<()
bool CRenderVideoSettings::operator< (const CRenderVideoSettings & rhs) const
References m_pixelPath, m_rotationDegCCW, m_scalingMethod, and m_stretchMode.
operator==()
bool CRenderVideoSettings::operator== (const CRenderVideoSettings & rhs) const
References m_pixelPath, m_rotationDegCCW, m_scalingMethod, and m_stretchMode.
operator>()
bool KODI::RETRO::CRenderVideoSettings::operator> (const CRenderVideoSettings & rhs) const inline
Reset()
void CRenderVideoSettings::Reset ()
References KODI::RETRO::AUTO, m_pixelPath, m_rotationDegCCW, m_scalingMethod, m_stretchMode, and KODI::RETRO::Normal.
Referenced by CRenderVideoSettings(), and KODI::RETRO::CRenderSettings::Reset().
ResetPixels()
void CRenderVideoSettings::ResetPixels ()
References m_pixelPath.
SetPixels()
void KODI::RETRO::CRenderVideoSettings::SetPixels (const std::string & pixelPath) inline
References m_pixelPath.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), KODI::RETRO::CGUIRenderSettings::SetPixels(), and KODI::RETRO::CRPBaseRenderer::SetPixels().
SetRenderRotation()
void KODI::RETRO::CRenderVideoSettings::SetRenderRotation (unsigned int rotationDegCCW) inline
References m_rotationDegCCW.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), KODI::RETRO::CRPBaseRenderer::SetRenderRotation(), KODI::RETRO::CGUIRenderSettings::SetRotationDegCCW(), and KODI::RETRO::CGUIGameSettings::UpdateSettings().
SetRenderStretchMode()
void KODI::RETRO::CRenderVideoSettings::SetRenderStretchMode (STRETCHMODE mode) inline
References m_stretchMode.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), KODI::RETRO::CGUIRenderSettings::SetStretchMode(), KODI::RETRO::CRPBaseRenderer::SetStretchMode(), and KODI::RETRO::CGUIGameSettings::UpdateSettings().
SetScalingMethod()
void KODI::RETRO::CRenderVideoSettings::SetScalingMethod (SCALINGMETHOD method) inline
References m_scalingMethod.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), KODI::RETRO::CRenderBufferManager::HasScalingMethod(), KODI::GAME::CDialogGameVideoFilter::InitVideoFilters(), KODI::RETRO::CRPBaseRenderer::SetScalingMethod(), and KODI::RETRO::CRPRenderManager::SupportsScalingMethod().
SetVideoFilter()
void CRenderVideoSettings::SetVideoFilter (const std::string & videoFilter)
References KODI::RETRO::AUTO, KODI::RETRO::LINEAR, m_scalingMethod, KODI::RETRO::NEAREST, VIDEO_FILTER_LINEAR, and VIDEO_FILTER_NEAREST.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), KODI::RETRO::CGUIRenderSettings::SetVideoFilter(), and KODI::RETRO::CGUIGameSettings::UpdateSettings().
Member Data Documentation
m_pixelPath
std::string KODI::RETRO::CRenderVideoSettings::m_pixelPath private
Referenced by GetPixels(), operator<(), operator==(), Reset(), ResetPixels(), and SetPixels().
m_rotationDegCCW
unsigned int KODI::RETRO::CRenderVideoSettings::m_rotationDegCCW private
Referenced by GetRenderRotation(), operator<(), operator==(), Reset(), and SetRenderRotation().
m_scalingMethod
SCALINGMETHOD KODI::RETRO::CRenderVideoSettings::m_scalingMethod private
Referenced by GetScalingMethod(), GetVideoFilter(), operator<(), operator==(), Reset(), SetScalingMethod(), and SetVideoFilter().
m_stretchMode
STRETCHMODE KODI::RETRO::CRenderVideoSettings::m_stretchMode private
Referenced by GetRenderStretchMode(), operator<(), operator==(), Reset(), and SetRenderStretchMode().
The documentation for this class was generated from the following files:
RenderVideoSettings.h
RenderVideoSettings.cpp