Kodi Documentation: OVERLAY::COverlayGlyphGLES Class Reference
OVERLAY::COverlayGlyphGLES Class Reference
#include <OverlayRendererGLES.h>
Classes
struct VERTEX
Public Member Functions
COverlayGlyphGLES (ASS_Image *images, float width, float height)
~COverlayGlyphGLES () override
void Render (SRenderState &state) override
Public Member Functions inherited from OVERLAY::COverlay
COverlay ()
virtual ~COverlay ()
Public Attributes
std::vector< VERTEX > m_vertex
GLuint m_texture = 0
float m_u
float m_v
Public Attributes inherited from OVERLAY::COverlay
enum OVERLAY::COverlay::EType m_type
enum OVERLAY::COverlay::EAlign m_align
enum OVERLAY::COverlay::EPosition m_pos
float m_x {0}
float m_y {0}
float m_width {1.0f}
float m_height {1.0f}
float m_source_width {0}
float m_source_height {0}
Additional Inherited Members
Public Types inherited from OVERLAY::COverlay
enum EType { TYPE_NONE , TYPE_TEXTURE }
enum EAlign { ALIGN_SCREEN , ALIGN_SCREEN_AR , ALIGN_VIDEO , ALIGN_SUBTITLE }
enum EPosition { POSITION_ABSOLUTE , POSITION_ABSOLUTE_SCREEN , POSITION_RELATIVE }
Static Public Member Functions inherited from OVERLAY::COverlay
static std::shared_ptr< COverlay > Create (const CDVDOverlayImage &o, CRect &rSource)
static std::shared_ptr< COverlay > Create (const CDVDOverlaySpu &o)
static std::shared_ptr< COverlay > Create (ASS_Image *images, float width, float height)
Protected Member Functions inherited from OVERLAY::COverlay
bool IsSquareResolution (float resRatio)
Given the resolution ratio determines if it is a 4/3 resolution.
Constructor & Destructor Documentation
COverlayGlyphGLES()
COverlayGlyphGLES::COverlayGlyphGLES (ASS_Image * images, float width, float height)
References OVERLAY::COverlayGlyphGLES::VERTEX::a, OVERLAY::SQuad::a, OVERLAY::COverlay::ALIGN_SCREEN, OVERLAY::COverlayGlyphGLES::VERTEX::b, OVERLAY::SQuad::b, OVERLAY::convert_quad(), OVERLAY::COverlayGlyphGLES::VERTEX::g, OVERLAY::SQuad::g, OVERLAY::SQuad::h, LoadTexture(), OVERLAY::COverlay::m_align, OVERLAY::COverlay::m_height, OVERLAY::COverlay::m_pos, m_texture, m_u, m_v, m_vertex, OVERLAY::COverlay::m_width, OVERLAY::COverlay::m_x, OVERLAY::COverlay::m_y, OVERLAY::COverlay::POSITION_RELATIVE, OVERLAY::SQuads::quad, OVERLAY::COverlayGlyphGLES::VERTEX::r, OVERLAY::SQuad::r, OVERLAY::SQuads::size_x, OVERLAY::SQuads::size_y, OVERLAY::SQuads::texture, OVERLAY::COverlayGlyphGLES::VERTEX::u, OVERLAY::SQuad::u, OVERLAY::COverlayGlyphGLES::VERTEX::v, OVERLAY::SQuad::v, OVERLAY::SQuad::w, OVERLAY::COverlayGlyphGLES::VERTEX::x, OVERLAY::SQuad::x, OVERLAY::COverlayGlyphGLES::VERTEX::y, OVERLAY::SQuad::y, and OVERLAY::COverlayGlyphGLES::VERTEX::z.
~COverlayGlyphGLES()
COverlayGlyphGLES::~COverlayGlyphGLES () override
References m_texture.
Member Function Documentation
Render()
void COverlayGlyphGLES::Render (SRenderState & state) override virtual
Implements OVERLAY::COverlay.
References CRenderSystemGLES::DisableGUIShader(), CRenderSystemGLES::EnableGUIShader(), CMatrixGLStack::Get(), CServiceBroker::GetRenderSystem(), glMatrixModview, glMatrixProject, CRenderSystemGLES::GUIShaderGetCol(), CRenderSystemGLES::GUIShaderGetCoord0(), CRenderSystemGLES::GUIShaderGetDepth(), CRenderSystemGLES::GUIShaderGetMatrix(), CRenderSystemGLES::GUIShaderGetPos(), OVERLAY::SRenderState::height, CMatrixGLStack::Load(), m_texture, m_vertex, CMatrixGL::MultMatrixf(), CMatrixGLStack::PopLoad(), CMatrixGLStack::Push(), CMatrixGL::Scalef(), SM_FONTS, CMatrixGL::Translatef(), OVERLAY::SRenderState::width, OVERLAY::SRenderState::x, and OVERLAY::SRenderState::y.
Member Data Documentation
m_texture
GLuint OVERLAY::COverlayGlyphGLES::m_texture = 0
Referenced by COverlayGlyphGLES(), Render(), and ~COverlayGlyphGLES().
m_u
float OVERLAY::COverlayGlyphGLES::m_u
Referenced by COverlayGlyphGLES().
m_v
float OVERLAY::COverlayGlyphGLES::m_v
Referenced by COverlayGlyphGLES().
m_vertex
std::vector<VERTEX> OVERLAY::COverlayGlyphGLES::m_vertex
Referenced by COverlayGlyphGLES(), and Render().
The documentation for this class was generated from the following files:
OverlayRendererGLES.h
OverlayRendererGLES.cpp