Kodi Documentation: KODI::GAME::CGUIDialogSelectSavestate Class Reference
KODI::GAME::CGUIDialogSelectSavestate Class Reference
Games
#include <GUIDialogSelectSavestate.h>
Static Public Member Functions
static bool ShowAndGetSavestate (const std::string &gamePath, std::string &savestatePath)
Static Private Member Functions
static CDialogGameSaves * GetDialog ()
Member Function Documentation
GetDialog()
CDialogGameSaves * CGUIDialogSelectSavestate::GetDialog () static private
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), KODI::GAME::CDialogGameSaves::Reset(), and WINDOW_DIALOG_GAME_SAVES.
Referenced by ShowAndGetSavestate().
ShowAndGetSavestate()
bool CGUIDialogSelectSavestate::ShowAndGetSavestate (const std::string & gamePath, std::string & savestatePath) static
References GetDialog(), KODI::GAME::CDialogGameSaves::GetSelectedItemPath(), KODI::GAME::CDialogGameSaves::IsConfirmed(), KODI::GAME::CDialogGameSaves::IsNewPressed(), CLog::Log(), LOGDEBUG, and KODI::GAME::CDialogGameSaves::Open().
Referenced by KODI::GAME::CGameUtils::FillInGameClient().
The documentation for this class was generated from the following files:
GUIDialogSelectSavestate.h
GUIDialogSelectSavestate.cpp