Kodi Documentation: CDataCacheCore Class Reference
CDataCacheCore Class Reference
#include <DataCacheCore.h>
Classes
struct SContentInfo
struct SPlayerAudioInfo
struct SPlayerVideoInfo
struct SRenderInfo
struct SStateInfo
struct STimeInfo
Public Member Functions
CDataCacheCore ()
virtual ~CDataCacheCore ()
void Reset ()
bool HasAVInfoChanges ()
void SignalVideoInfoChange ()
void SignalAudioInfoChange ()
void SignalSubtitleInfoChange ()
void SetVideoDecoderName (std::string name, bool isHw)
std::string GetVideoDecoderName ()
bool IsVideoHwDecoder ()
void SetVideoDeintMethod (std::string method)
std::string GetVideoDeintMethod ()
void SetVideoPixelFormat (std::string pixFormat)
std::string GetVideoPixelFormat ()
void SetVideoStereoMode (std::string mode)
std::string GetVideoStereoMode ()
void SetVideoDimensions (int width, int height)
int GetVideoWidth ()
int GetVideoHeight ()
void SetVideoFps (float fps)
float GetVideoFps ()
void SetVideoDAR (float dar)
float GetVideoDAR ()
void SetVideoInterlaced (bool isInterlaced)
Set if the video is interlaced in cache.
bool IsVideoInterlaced ()
Check if the video is interlaced from cache.
void SetAudioDecoderName (std::string name)
std::string GetAudioDecoderName ()
void SetAudioChannels (std::string channels)
std::string GetAudioChannels ()
void SetAudioSampleRate (int sampleRate)
int GetAudioSampleRate ()
void SetAudioBitsPerSample (int bitsPerSample)
int GetAudioBitsPerSample ()
void SetEditList (const std::vector< EDL::Edit > &editList)
Set the EDL edit list to cache.
const std::vector< EDL::Edit > & GetEditList () const
Get the EDL edit list in cache.
void SetCuts (const std::vector< std::chrono::milliseconds > &cuts)
Set the list of cut markers in cache.
const std::vector< std::chrono::milliseconds > & GetCuts () const
Get the list of cut markers from cache.
void SetSceneMarkers (const std::vector< std::chrono::milliseconds > &sceneMarkers)
Set the list of scene markers in cache.
const std::vector< std::chrono::milliseconds > & GetSceneMarkers () const
Get the list of scene markers markers from cache.
void SetChapters (const std::vector< std::pair< std::string, int64_t > > &chapters)
const std::vector< std::pair< std::string, int64_t > > & GetChapters () const
Get the chapter list in cache.
void SetRenderClockSync (bool enabled)
bool IsRenderClockSync ()
void SeekFinished (int64_t offset)
Notifies the cache core that a seek operation has finished.
void SetStateSeeking (bool active)
bool IsSeeking ()
bool HasPerformedSeek (int64_t lastSecondInterval) const
Checks if a seek has been performed in the last provided seconds interval.
int64_t GetSeekOffSet () const
Gets the last seek offset.
void SetSpeed (float tempo, float speed)
float GetSpeed ()
float GetTempo ()
void SetFrameAdvance (bool fa)
bool IsFrameAdvance ()
bool IsPlayerStateChanged ()
void SetGuiRender (bool gui)
bool GetGuiRender ()
void SetVideoRender (bool video)
bool GetVideoRender ()
void SetPlayTimes (time_t start, int64_t current, int64_t min, int64_t max)
void GetPlayTimes (time_t &start, int64_t &current, int64_t &min, int64_t &max)
time_t GetStartTime ()
Get the start time.
int64_t GetPlayTime ()
Get the current time of playback.
float GetPlayPercentage ()
Get the current percentage of playback if a playback buffer is available.
int64_t GetMinTime ()
Get the minimum time.
int64_t GetMaxTime ()
Get the maximum time.
Static Public Member Functions
static CDataCacheCore & GetInstance ()
Protected Attributes
std::atomic_bool m_hasAVInfoChanges = false
CCriticalSection m_videoPlayerSection
struct CDataCacheCore::SPlayerVideoInfo m_playerVideoInfo
CCriticalSection m_audioPlayerSection
struct CDataCacheCore::SPlayerAudioInfo m_playerAudioInfo
CCriticalSection m_contentSection
struct CDataCacheCore::SContentInfo m_contentInfo
CCriticalSection m_renderSection
struct CDataCacheCore::SRenderInfo m_renderInfo
CCriticalSection m_stateSection
bool m_playerStateChanged = false
struct CDataCacheCore::SStateInfo m_stateInfo
struct CDataCacheCore::STimeInfo m_timeInfo = {}
Constructor & Destructor Documentation
CDataCacheCore()
CDataCacheCore::CDataCacheCore ()
~CDataCacheCore()
CDataCacheCore::~CDataCacheCore () virtual default
Member Function Documentation
GetAudioBitsPerSample()
int CDataCacheCore::GetAudioBitsPerSample ()
References CDataCacheCore::SPlayerAudioInfo::bitsPerSample, m_audioPlayerSection, and m_playerAudioInfo.
GetAudioChannels()
std::string CDataCacheCore::GetAudioChannels ()
References CDataCacheCore::SPlayerAudioInfo::channels, m_audioPlayerSection, and m_playerAudioInfo.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel().
GetAudioDecoderName()
std::string CDataCacheCore::GetAudioDecoderName ()
References CDataCacheCore::SPlayerAudioInfo::decoderName, m_audioPlayerSection, and m_playerAudioInfo.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel().
GetAudioSampleRate()
int CDataCacheCore::GetAudioSampleRate ()
References m_audioPlayerSection, m_playerAudioInfo, and CDataCacheCore::SPlayerAudioInfo::sampleRate.
GetChapters()
const std::vector< std::pair< std::string, int64_t > > & CDataCacheCore::GetChapters () const
Get the chapter list in cache.
Returns
The list of chapters or an empty vector if no chapters exist.
References CDataCacheCore::SContentInfo::GetChapters(), m_contentInfo, and m_contentSection.
GetCuts()
const std::vector< std::chrono::milliseconds > & CDataCacheCore::GetCuts () const
Get the list of cut markers from cache.
Returns
The list of cut markers or an empty vector if no cuts exist.
References CDataCacheCore::SContentInfo::GetCuts(), m_contentInfo, and m_contentSection.
GetEditList()
const std::vector< EDL::Edit > & CDataCacheCore::GetEditList () const
Get the EDL edit list in cache.
Returns
The EDL edits or an empty vector if no edits exist.
References CDataCacheCore::SContentInfo::GetEditList(), m_contentInfo, and m_contentSection.
GetGuiRender()
bool CDataCacheCore::GetGuiRender ()
References CDataCacheCore::SStateInfo::m_renderGuiLayer, m_stateInfo, and m_stateSection.
Referenced by CApplicationPlayer::IsRenderingGuiLayer().
GetInstance()
CDataCacheCore & CDataCacheCore::GetInstance () static
References CServiceBroker::GetDataCacheCore().
Referenced by CApplicationPlayer::CreatePlayer(), CApplicationPlayer::FrameMove(), CApplicationPlayer::GetMaxTime(), CApplicationPlayer::GetMinTime(), CApplicationPlayer::GetPercentage(), CApplicationPlayer::GetPlaySpeed(), CApplicationPlayer::GetPlayTempo(), CApplicationPlayer::GetStartTime(), CApplicationPlayer::GetTime(), PAPlayer::GetTimeInternal(), CApplicationPlayer::GetTotalTime(), CApplication::OnMessage(), UPNP::CUPnPPlayer::Pause(), UPNP::CUPnPPlayer::Process(), PAPlayer::ProcessStream(), UPNP::CUPnPPlayer::SeekTime(), CExternalPlayer::SetSpeed(), PAPlayer::SetSpeed(), and UPNP::CUPnPPlayer::SetSpeed().
GetMaxTime()
int64_t CDataCacheCore::GetMaxTime ()
Get the maximum time.
This is the maximum time, in ms, that the player can skip forward. For a typical video, this will be the total length. For live TV without timeshift this is zero, and for live TV with timeshift this will be the buffer ahead.
References m_stateSection, m_timeInfo, and CDataCacheCore::STimeInfo::m_timeMax.
Referenced by CApplicationPlayer::GetMaxTime(), CApplicationPlayer::GetTotalTime(), and PVR::CPVRGUIActionsPlayback::SeekForward().
GetMinTime()
int64_t CDataCacheCore::GetMinTime ()
Get the minimum time.
This will be zero for a typical video. With timeshift, this is the time, in ms, that the player can go back. This can be before the start time.
References m_stateSection, m_timeInfo, and CDataCacheCore::STimeInfo::m_timeMin.
Referenced by CApplicationPlayer::GetMinTime(), CApplicationPlayer::GetTotalTime(), and PVR::CPVRGUIActionsPlayback::SeekBackward().
GetPlayPercentage()
float CDataCacheCore::GetPlayPercentage ()
Get the current percentage of playback if a playback buffer is available.
If there is no playback buffer, percentage will be 0.
References int64_t(), m_stateSection, CDataCacheCore::STimeInfo::m_time, m_timeInfo, CDataCacheCore::STimeInfo::m_timeMax, and CDataCacheCore::STimeInfo::m_timeMin.
Referenced by CApplicationPlayer::GetPercentage().
GetPlayTime()
int64_t CDataCacheCore::GetPlayTime ()
Get the current time of playback.
This is the time elapsed, in ms, since the start time.
References m_stateSection, CDataCacheCore::STimeInfo::m_time, and m_timeInfo.
Referenced by CApplicationPlayer::GetTime(), and PVR::CPVRGUIActionsPlayback::SeekBackward().
GetPlayTimes()
void CDataCacheCore::GetPlayTimes (time_t & start, int64_t & current, int64_t & min, int64_t & max)
References CDataCacheCore::STimeInfo::m_startTime, m_stateSection, CDataCacheCore::STimeInfo::m_time, m_timeInfo, CDataCacheCore::STimeInfo::m_timeMax, CDataCacheCore::STimeInfo::m_timeMin, max, and min.
Referenced by PVR::CPVRGUITimesInfo::UpdateTimeshiftData().
GetSceneMarkers()
const std::vector< std::chrono::milliseconds > & CDataCacheCore::GetSceneMarkers () const
Get the list of scene markers markers from cache.
Returns
The list of scene markers or an empty vector if no scene exist.
References CDataCacheCore::SContentInfo::GetSceneMarkers(), m_contentInfo, and m_contentSection.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool().
GetSeekOffSet()
int64_t CDataCacheCore::GetSeekOffSet () const
Gets the last seek offset.
Returns
the last seek offset
References CDataCacheCore::SStateInfo::m_lastSeekOffset, m_stateInfo, and m_stateSection.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel().
GetSpeed()
float CDataCacheCore::GetSpeed ()
References CDataCacheCore::SStateInfo::m_speed, m_stateInfo, and m_stateSection.
Referenced by CApplicationPlayer::GetPlaySpeed(), UPNP::CUPnPPlayer::Process(), and PVR::CPVRGUITimesInfo::UpdateTimeshiftData().
GetStartTime()
time_t CDataCacheCore::GetStartTime ()
Get the start time.
For a typical video this will be zero. For live TV, this is a reference time in units of time_t (UTC) from which time elapsed starts. Ideally this would be the start of the tv show but can be any other time as well.
References CDataCacheCore::STimeInfo::m_startTime, m_stateSection, and m_timeInfo.
Referenced by PVR::CPVRPlaybackState::GetChannelPlaybackTime(), CApplicationPlayer::GetStartTime(), PVR::CPVRGUIActionsPlayback::SeekBackward(), and PVR::CPVRGUIActionsPlayback::SeekForward().
GetTempo()
float CDataCacheCore::GetTempo ()
References m_stateInfo, m_stateSection, and CDataCacheCore::SStateInfo::m_tempo.
Referenced by CApplicationPlayer::GetPlayTempo().
GetVideoDAR()
float CDataCacheCore::GetVideoDAR ()
References CDataCacheCore::SPlayerVideoInfo::dar, m_playerVideoInfo, and m_videoPlayerSection.
GetVideoDecoderName()
std::string CDataCacheCore::GetVideoDecoderName ()
References CDataCacheCore::SPlayerVideoInfo::decoderName, m_playerVideoInfo, and m_videoPlayerSection.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel().
GetVideoDeintMethod()
std::string CDataCacheCore::GetVideoDeintMethod ()
References CDataCacheCore::SPlayerVideoInfo::deintMethod, m_playerVideoInfo, and m_videoPlayerSection.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel().
GetVideoFps()
float CDataCacheCore::GetVideoFps ()
References CDataCacheCore::SPlayerVideoInfo::fps, m_playerVideoInfo, and m_videoPlayerSection.
GetVideoHeight()
int CDataCacheCore::GetVideoHeight ()
References CDataCacheCore::SPlayerVideoInfo::height, m_playerVideoInfo, and m_videoPlayerSection.
GetVideoPixelFormat()
std::string CDataCacheCore::GetVideoPixelFormat ()
References m_playerVideoInfo, m_videoPlayerSection, and CDataCacheCore::SPlayerVideoInfo::pixFormat.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel().
GetVideoRender()
bool CDataCacheCore::GetVideoRender ()
References CDataCacheCore::SStateInfo::m_renderVideoLayer, m_stateInfo, and m_stateSection.
Referenced by CApplicationPlayer::IsRenderingVideoLayer().
GetVideoStereoMode()
std::string CDataCacheCore::GetVideoStereoMode ()
References m_playerVideoInfo, m_videoPlayerSection, and CDataCacheCore::SPlayerVideoInfo::stereoMode.
Referenced by KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), and CStereoscopicsManager::GetVideoStereoMode().
GetVideoWidth()
int CDataCacheCore::GetVideoWidth ()
References m_playerVideoInfo, m_videoPlayerSection, and CDataCacheCore::SPlayerVideoInfo::width.
HasAVInfoChanges()
bool CDataCacheCore::HasAVInfoChanges ()
References m_hasAVInfoChanges.
HasPerformedSeek()
bool CDataCacheCore::HasPerformedSeek (int64_t lastSecondInterval) const
Checks if a seek has been performed in the last provided seconds interval.
Parameters
lastSecondInterval - the last elapsed second interval to check for a seek operation
Returns
true if a seek was performed in the lastSecondInterval, false otherwise
References CDataCacheCore::SStateInfo::m_lastSeekTime, m_stateInfo, and m_stateSection.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool().
IsFrameAdvance()
bool CDataCacheCore::IsFrameAdvance ()
References CDataCacheCore::SStateInfo::m_frameAdvance, m_stateInfo, and m_stateSection.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool().
IsPlayerStateChanged()
bool CDataCacheCore::IsPlayerStateChanged ()
References m_playerStateChanged, and m_stateSection.
IsRenderClockSync()
bool CDataCacheCore::IsRenderClockSync ()
References CDataCacheCore::SRenderInfo::m_isClockSync, m_renderInfo, and m_renderSection.
IsSeeking()
bool CDataCacheCore::IsSeeking ()
References m_stateInfo, m_stateSection, and CDataCacheCore::SStateInfo::m_stateSeeking.
Referenced by CSeekHandler::InProgress().
IsVideoHwDecoder()
bool CDataCacheCore::IsVideoHwDecoder ()
References CDataCacheCore::SPlayerVideoInfo::isHwDecoder, m_playerVideoInfo, and m_videoPlayerSection.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool().
IsVideoInterlaced()
bool CDataCacheCore::IsVideoInterlaced ()
Check if the video is interlaced from cache.
Returns
True if interlaced, otherwise false
References CDataCacheCore::SPlayerVideoInfo::m_isInterlaced, m_playerVideoInfo, and m_videoPlayerSection.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel().
Reset()
void CDataCacheCore::Reset ()
References m_audioPlayerSection, m_contentInfo, m_contentSection, m_hasAVInfoChanges, m_playerAudioInfo, m_playerStateChanged, m_playerVideoInfo, m_renderInfo, m_renderSection, m_stateInfo, m_stateSection, m_timeInfo, m_videoPlayerSection, and CDataCacheCore::SContentInfo::Reset().
Referenced by CExternalPlayer::CloseFile(), PAPlayer::CloseFile(), CVideoPlayer::CloseFile(), UPNP::CUPnPPlayer::CloseFile(), CApplicationPlayer::CreatePlayer(), and KODI::RETRO::CRPProcessInfo::ResetInfo().
SeekFinished()
void CDataCacheCore::SeekFinished (int64_t offset)
Notifies the cache core that a seek operation has finished.
Parameters
offset - the seek offset
References CDataCacheCore::SStateInfo::m_lastSeekOffset, CDataCacheCore::SStateInfo::m_lastSeekTime, m_stateInfo, and m_stateSection.
Referenced by CApplication::OnMessage(), CProcessInfo::SeekFinished(), and UPNP::CUPnPPlayer::SeekTime().
SetAudioBitsPerSample()
void CDataCacheCore::SetAudioBitsPerSample (int bitsPerSample)
References CDataCacheCore::SPlayerAudioInfo::bitsPerSample, m_audioPlayerSection, and m_playerAudioInfo.
Referenced by CProcessInfo::ResetAudioCodecInfo(), KODI::RETRO::CRPProcessInfo::SetAudioBitsPerSample(), and CProcessInfo::SetAudioBitsPerSample().
SetAudioChannels()
void CDataCacheCore::SetAudioChannels (std::string channels)
References CDataCacheCore::SPlayerAudioInfo::channels, m_audioPlayerSection, and m_playerAudioInfo.
Referenced by CProcessInfo::ResetAudioCodecInfo(), KODI::RETRO::CRPProcessInfo::SetAudioChannels(), and CProcessInfo::SetAudioChannels().
SetAudioDecoderName()
void CDataCacheCore::SetAudioDecoderName (std::string name)
References CDataCacheCore::SPlayerAudioInfo::decoderName, m_audioPlayerSection, m_playerAudioInfo, and name.
Referenced by CProcessInfo::ResetAudioCodecInfo(), and CProcessInfo::SetAudioDecoderName().
SetAudioSampleRate()
void CDataCacheCore::SetAudioSampleRate (int sampleRate)
References m_audioPlayerSection, m_playerAudioInfo, and CDataCacheCore::SPlayerAudioInfo::sampleRate.
Referenced by CProcessInfo::ResetAudioCodecInfo(), KODI::RETRO::CRPProcessInfo::SetAudioSampleRate(), and CProcessInfo::SetAudioSampleRate().
SetChapters()
void CDataCacheCore::SetChapters (const std::vector< std::pair< std::string, int64_t > > & chapters)
References m_contentInfo, m_contentSection, and CDataCacheCore::SContentInfo::SetChapters().
Referenced by CVideoPlayer::UpdatePlayState().
SetCuts()
void CDataCacheCore::SetCuts (const std::vector< std::chrono::milliseconds > & cuts)
Set the list of cut markers in cache.
Returns
The list of cuts or an empty list if no cuts exist
References m_contentInfo, m_contentSection, and CDataCacheCore::SContentInfo::SetCuts().
Referenced by CVideoPlayer::OpenVideoStream().
SetEditList()
void CDataCacheCore::SetEditList (const std::vector< EDL::Edit > & editList)
Set the EDL edit list to cache.
Parameters
editList The vector of edits to fill.
References m_contentInfo, m_contentSection, and CDataCacheCore::SContentInfo::SetEditList().
Referenced by CVideoPlayer::OpenVideoStream().
SetFrameAdvance()
void CDataCacheCore::SetFrameAdvance (bool fa)
References CDataCacheCore::SStateInfo::m_frameAdvance, m_stateInfo, and m_stateSection.
Referenced by CProcessInfo::SetFrameAdvance().
SetGuiRender()
void CDataCacheCore::SetGuiRender (bool gui)
References m_playerStateChanged, CDataCacheCore::SStateInfo::m_renderGuiLayer, m_stateInfo, and m_stateSection.
Referenced by CProcessInfo::SetDataCache(), and CProcessInfo::SetGuiRender().
SetPlayTimes()
void CDataCacheCore::SetPlayTimes (time_t start, int64_t current, int64_t min, int64_t max)
References CDataCacheCore::STimeInfo::m_startTime, m_stateSection, CDataCacheCore::STimeInfo::m_time, m_timeInfo, CDataCacheCore::STimeInfo::m_timeMax, CDataCacheCore::STimeInfo::m_timeMin, max, and min.
Referenced by PAPlayer::GetTimeInternal(), UPNP::CUPnPPlayer::Process(), PAPlayer::ProcessStream(), KODI::RETRO::CRPProcessInfo::SetPlayTimes(), and CProcessInfo::SetPlayTimes().
SetRenderClockSync()
void CDataCacheCore::SetRenderClockSync (bool enabled)
References CDataCacheCore::SRenderInfo::m_isClockSync, m_renderInfo, and m_renderSection.
Referenced by CProcessInfo::SetRenderClockSync().
SetSceneMarkers()
void CDataCacheCore::SetSceneMarkers (const std::vector< std::chrono::milliseconds > & sceneMarkers)
Set the list of scene markers in cache.
Returns
The list of scene markers or an empty list if no scene markers exist
References m_contentInfo, m_contentSection, and CDataCacheCore::SContentInfo::SetSceneMarkers().
Referenced by CVideoPlayer::OpenVideoStream().
SetSpeed()
void CDataCacheCore::SetSpeed (float tempo, float speed)
References CDataCacheCore::SStateInfo::m_speed, m_stateInfo, m_stateSection, and CDataCacheCore::SStateInfo::m_tempo.
Referenced by UPNP::CUPnPPlayer::Pause(), UPNP::CUPnPPlayer::Process(), CProcessInfo::SetNewSpeed(), CProcessInfo::SetNewTempo(), KODI::RETRO::CRPProcessInfo::SetSpeed(), CProcessInfo::SetSpeed(), CExternalPlayer::SetSpeed(), PAPlayer::SetSpeed(), UPNP::CUPnPPlayer::SetSpeed(), and CProcessInfo::SetTempo().
SetStateSeeking()
void CDataCacheCore::SetStateSeeking (bool active)
References m_playerStateChanged, m_stateInfo, m_stateSection, and CDataCacheCore::SStateInfo::m_stateSeeking.
Referenced by CProcessInfo::ResetVideoCodecInfo(), and CProcessInfo::SetStateSeeking().
SetVideoDAR()
void CDataCacheCore::SetVideoDAR (float dar)
References CDataCacheCore::SPlayerVideoInfo::dar, m_playerVideoInfo, and m_videoPlayerSection.
Referenced by CProcessInfo::ResetVideoCodecInfo(), and CProcessInfo::SetVideoDAR().
SetVideoDecoderName()
void CDataCacheCore::SetVideoDecoderName (std::string name, bool isHw)
References CDataCacheCore::SPlayerVideoInfo::decoderName, CDataCacheCore::SPlayerVideoInfo::isHwDecoder, m_playerVideoInfo, m_videoPlayerSection, and name.
Referenced by CProcessInfo::ResetVideoCodecInfo(), and CProcessInfo::SetVideoDecoderName().
SetVideoDeintMethod()
void CDataCacheCore::SetVideoDeintMethod (std::string method)
References CDataCacheCore::SPlayerVideoInfo::deintMethod, m_playerVideoInfo, and m_videoPlayerSection.
Referenced by CProcessInfo::ResetVideoCodecInfo(), and CProcessInfo::SetVideoDeintMethod().
SetVideoDimensions()
void CDataCacheCore::SetVideoDimensions (int width, int height)
References CDataCacheCore::SPlayerVideoInfo::height, m_playerVideoInfo, m_videoPlayerSection, and CDataCacheCore::SPlayerVideoInfo::width.
Referenced by CProcessInfo::ResetVideoCodecInfo(), KODI::RETRO::CRPProcessInfo::SetVideoDimensions(), and CProcessInfo::SetVideoDimensions().
SetVideoFps()
void CDataCacheCore::SetVideoFps (float fps)
References CDataCacheCore::SPlayerVideoInfo::fps, m_playerVideoInfo, and m_videoPlayerSection.
Referenced by CProcessInfo::ResetVideoCodecInfo(), KODI::RETRO::CRPProcessInfo::SetVideoFps(), and CProcessInfo::SetVideoFps().
SetVideoInterlaced()
void CDataCacheCore::SetVideoInterlaced (bool isInterlaced)
Set if the video is interlaced in cache.
Parameters
isInterlaced Set true when the video is interlaced
References CDataCacheCore::SPlayerVideoInfo::m_isInterlaced, m_playerVideoInfo, and m_videoPlayerSection.
Referenced by CProcessInfo::SetVideoInterlaced().
SetVideoPixelFormat()
void CDataCacheCore::SetVideoPixelFormat (std::string pixFormat)
References m_playerVideoInfo, m_videoPlayerSection, and CDataCacheCore::SPlayerVideoInfo::pixFormat.
Referenced by CProcessInfo::ResetVideoCodecInfo(), KODI::RETRO::CRPProcessInfo::SetVideoPixelFormat(), and CProcessInfo::SetVideoPixelFormat().
SetVideoRender()
void CDataCacheCore::SetVideoRender (bool video)
References m_playerStateChanged, CDataCacheCore::SStateInfo::m_renderVideoLayer, m_stateInfo, and m_stateSection.
Referenced by CProcessInfo::SetDataCache(), and CProcessInfo::SetVideoRender().
SetVideoStereoMode()
void CDataCacheCore::SetVideoStereoMode (std::string mode)
References m_playerVideoInfo, m_videoPlayerSection, and CDataCacheCore::SPlayerVideoInfo::stereoMode.
Referenced by CProcessInfo::ResetVideoCodecInfo(), and CProcessInfo::SetVideoStereoMode().
SignalAudioInfoChange()
void CDataCacheCore::SignalAudioInfoChange ()
References m_hasAVInfoChanges.
Referenced by CVideoPlayer::CloseDemuxer(), CVideoPlayer::HandleMessages(), CVideoPlayer::OpenStream(), CSelectionStreams::Update(), and PAPlayer::UpdateGUIData().
SignalSubtitleInfoChange()
void CDataCacheCore::SignalSubtitleInfoChange ()
References m_hasAVInfoChanges.
Referenced by CVideoPlayer::CloseDemuxer(), CVideoPlayer::HandleMessages(), CVideoPlayer::OpenStream(), CVideoPlayer::SetSubtitleVisibleInternal(), and CSelectionStreams::Update().
SignalVideoInfoChange()
void CDataCacheCore::SignalVideoInfoChange ()
References m_hasAVInfoChanges.
Referenced by CVideoPlayer::CloseDemuxer(), CVideoPlayer::HandleMessages(), CVideoPlayer::OpenStream(), and CSelectionStreams::Update().
Member Data Documentation
m_audioPlayerSection
CCriticalSection CDataCacheCore::m_audioPlayerSection protected
Referenced by GetAudioBitsPerSample(), GetAudioChannels(), GetAudioDecoderName(), GetAudioSampleRate(), Reset(), SetAudioBitsPerSample(), SetAudioChannels(), SetAudioDecoderName(), and SetAudioSampleRate().
m_contentInfo
struct CDataCacheCore::SContentInfo CDataCacheCore::m_contentInfo protected
Referenced by GetChapters(), GetCuts(), GetEditList(), GetSceneMarkers(), Reset(), SetChapters(), SetCuts(), SetEditList(), and SetSceneMarkers().
m_contentSection
CCriticalSection CDataCacheCore::m_contentSection mutable protected
Referenced by GetChapters(), GetCuts(), GetEditList(), GetSceneMarkers(), Reset(), SetChapters(), SetCuts(), SetEditList(), and SetSceneMarkers().
m_hasAVInfoChanges
std::atomic_bool CDataCacheCore::m_hasAVInfoChanges = false protected
Referenced by HasAVInfoChanges(), Reset(), SignalAudioInfoChange(), SignalSubtitleInfoChange(), and SignalVideoInfoChange().
m_playerAudioInfo
struct CDataCacheCore::SPlayerAudioInfo CDataCacheCore::m_playerAudioInfo protected
Referenced by GetAudioBitsPerSample(), GetAudioChannels(), GetAudioDecoderName(), GetAudioSampleRate(), Reset(), SetAudioBitsPerSample(), SetAudioChannels(), SetAudioDecoderName(), and SetAudioSampleRate().
m_playerStateChanged
bool CDataCacheCore::m_playerStateChanged = false protected
Referenced by IsPlayerStateChanged(), Reset(), SetGuiRender(), SetStateSeeking(), and SetVideoRender().
m_playerVideoInfo
struct CDataCacheCore::SPlayerVideoInfo CDataCacheCore::m_playerVideoInfo protected
Referenced by GetVideoDAR(), GetVideoDecoderName(), GetVideoDeintMethod(), GetVideoFps(), GetVideoHeight(), GetVideoPixelFormat(), GetVideoStereoMode(), GetVideoWidth(), IsVideoHwDecoder(), IsVideoInterlaced(), Reset(), SetVideoDAR(), SetVideoDecoderName(), SetVideoDeintMethod(), SetVideoDimensions(), SetVideoFps(), SetVideoInterlaced(), SetVideoPixelFormat(), and SetVideoStereoMode().
m_renderInfo
struct CDataCacheCore::SRenderInfo CDataCacheCore::m_renderInfo protected
Referenced by IsRenderClockSync(), Reset(), and SetRenderClockSync().
m_renderSection
CCriticalSection CDataCacheCore::m_renderSection protected
Referenced by IsRenderClockSync(), Reset(), and SetRenderClockSync().
m_stateInfo
struct CDataCacheCore::SStateInfo CDataCacheCore::m_stateInfo protected
Referenced by GetGuiRender(), GetSeekOffSet(), GetSpeed(), GetTempo(), GetVideoRender(), HasPerformedSeek(), IsFrameAdvance(), IsSeeking(), Reset(), SeekFinished(), SetFrameAdvance(), SetGuiRender(), SetSpeed(), SetStateSeeking(), and SetVideoRender().
m_stateSection
CCriticalSection CDataCacheCore::m_stateSection mutable protected
Referenced by GetGuiRender(), GetMaxTime(), GetMinTime(), GetPlayPercentage(), GetPlayTime(), GetPlayTimes(), GetSeekOffSet(), GetSpeed(), GetStartTime(), GetTempo(), GetVideoRender(), HasPerformedSeek(), IsFrameAdvance(), IsPlayerStateChanged(), IsSeeking(), Reset(), SeekFinished(), SetFrameAdvance(), SetGuiRender(), SetPlayTimes(), SetSpeed(), SetStateSeeking(), and SetVideoRender().
m_timeInfo
struct CDataCacheCore::STimeInfo CDataCacheCore::m_timeInfo = {} protected
Referenced by GetMaxTime(), GetMinTime(), GetPlayPercentage(), GetPlayTime(), GetPlayTimes(), GetStartTime(), Reset(), and SetPlayTimes().
m_videoPlayerSection
CCriticalSection CDataCacheCore::m_videoPlayerSection protected
Referenced by GetVideoDAR(), GetVideoDecoderName(), GetVideoDeintMethod(), GetVideoFps(), GetVideoHeight(), GetVideoPixelFormat(), GetVideoStereoMode(), GetVideoWidth(), IsVideoHwDecoder(), IsVideoInterlaced(), Reset(), SetVideoDAR(), SetVideoDecoderName(), SetVideoDeintMethod(), SetVideoDimensions(), SetVideoFps(), SetVideoInterlaced(), SetVideoPixelFormat(), and SetVideoStereoMode().
The documentation for this class was generated from the following files:
DataCacheCore.h
DataCacheCore.cpp