Kodi Documentation: TestTagLoaderTagLib.cpp File Reference
TestTagLoaderTagLib.cpp File Reference
#include "music/tags/MusicInfoTag.h"
#include "music/tags/TagLoaderTagLib.h"
#include <gtest/gtest.h>
#include <taglib/apetag.h>
#include <taglib/asftag.h>
#include <taglib/id3v1genres.h>
#include <taglib/id3v1tag.h>
#include <taglib/id3v2tag.h>
#include <taglib/mp4tag.h>
#include <taglib/tpropertymap.h>
#include <taglib/xiphcomment.h>
Classes
class TestTagParser< T >
class EmptyTagParser< T >
class TestTagLoaderTagLib
Typedefs
typedef ::testing::Types< ID3v2::Tag, ID3v1::Tag, ASF::Tag, APE::Tag, Ogg::XiphComment, MP4::Tag > TagTypes
typedef ::testing::Types< ID3v2::Tag, ID3v1::Tag, ASF::Tag, APE::Tag, Ogg::XiphComment > EmptyPropertiesTagTypes
Functions
TYPED_TEST_SUITE (TestTagParser, TagTypes)
TYPED_TEST (TestTagParser, ParsesBasicTag)
TYPED_TEST (TestTagParser, HandleNullTag)
template<typename T , size_t N>
T * end (T(&ra)[N])
TYPED_TEST_SUITE (EmptyTagParser, EmptyPropertiesTagTypes)
TYPED_TEST (EmptyTagParser, EmptyProperties)
TYPED_TEST (TestTagParser, FooProperties)
TEST_F (TestTagLoaderTagLib, SetGenre)
TEST_F (TestTagLoaderTagLib, SplitMBID)
Variables
const char * tags []
Typedef Documentation
EmptyPropertiesTagTypes
typedef ::testing::Types<ID3v2::Tag, ID3v1::Tag, ASF::Tag, APE::Tag, Ogg::XiphComment> EmptyPropertiesTagTypes
TagTypes
typedef ::testing::Types<ID3v2::Tag, ID3v1::Tag, ASF::Tag, APE::Tag, Ogg::XiphComment, MP4::Tag> TagTypes
Function Documentation
end()
template<typename T , size_t N> T * end (T(&) ra[N])
Referenced by CMusicDatabase::AddArtistVideoLinks(), CDDB::Xcddb::addInexactList(), kodi::addon::CInstancePVRClient::ADDON_GetEPGForChannel(), CGUIWindow::AllocResources(), CAirTunesServer::AudioOutputFunctions::audio_set_progress(), avc_find_startcode(), avc_find_startcode_internal(), CBitstreamConverter::avc_parse_nal_units(), kodi::tools::StringUtils::BinaryStringToString(), KODI::UTILS::StringUtils::BinaryStringToString(), DatabaseUtils::BuildLimitClause(), DatabaseUtils::BuildLimitClauseOnly(), anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer(), CJobManager::CancelJob(), CJobManager::CancelJobs(), CFadeEffect::CFadeEffect(), CFadeEffect::CFadeEffect(), CGUIString::CGUIString(), CVideoPlayer::CheckAutoSceneSkip(), CVideoDatabase::CleanDatabase(), CLocalizeStrings::Clear(), CMap< Key, Value, Size >::CMap(), CWebServer::ContentReaderCallback(), CBitstreamConverter::Convert(), XFILE::CFile::Copy(), PVR::CPVREpgInfoTag::CPVREpgInfoTag(), CGUIControlFactory::Create(), PVR::CPVRChannel::CreateEPGGapTag(), PVR::CPVREpgDatabase::CreateEpgSearchFilter(), CAnimation::CreateFader(), PVR::CPVREpgTagsContainer::CreateGapTag(), CZoomEffect::CZoomEffect(), CDVDOverlayCodecSSA::Decode(), CDVDOverlayCodecText::Decode(), dll__dllonexit(), dll_initterm(), CImageLoader::DoWork(), CPartyModeManager::Enable(), dbiplus::MysqlDataset::exec(), dbiplus::SqliteDataset::exec(), CDVDFileInfo::ExtractThumbToTexture(), find_start_code(), CGUIDialogNumeric::FrameMove(), CSettingNumber::fromString(), CSettingInt::fromString(), HttpRangeUtils::GenerateContentRangeHeaderValue(), TestWebServer::GenerateRangeHeaderValue(), JSONRPC::CAddonsOperations::GetAddons(), ADDON::CAddonMgr::GetAddonsWithAvailableUpdate(), JSONRPC::CAudioLibrary::GetAlbums(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CGUIControlFactory::GetAnimations(), CMusicDatabase::GetArtist(), JSONRPC::CAudioLibrary::GetArtists(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), ADDON::CAddonMgr::GetAvailableUpdatesOrOutdatedAddons(), JSONRPC::CPVROperations::GetChannelGroups(), JSONRPC::CPVROperations::GetClients(), ADDON::CAddonMgr::GetCompatibleVersions(), CGUIFixedListContainer::GetCursorFromPoint(), XFILE::CMusicSearchDirectory::GetDirectory(), CGUIMediaWindow::GetDirectory(), CMusicDatabase::GetDiscsByWhere(), PVR::CPVREpgInfoTag::GetDuration(), PVR::CPVRTimerInfoTag::GetDuration(), PVR::CPVRClient::GetEPGForChannel(), JSONRPC::CFavouritesOperations::GetFavourites(), CSysInfo::GetKernelVersionFull(), DatabaseUtils::GetLimitCount(), CVideoDatabase::GetPeopleNav(), CMusicDatabase::GetRecentlyPlayedAlbums(), ADDON::CAddonDatabase::GetRepositoryContent(), JSONRPC::CAudioLibrary::GetSongs(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsFullByWhere(), PVR::CPVREpgTagsContainer::GetTagBetween(), gpu_memcpy(), PVR::CGUIEPGGridContainer::HandleChannels(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::CJSONUtils::HandleLimits(), PVR::CGUIEPGGridContainer::HandleRuler(), has_sei_recovery_point(), CEdl::InEdit(), CBitstreamConverter::isom_write_avcc(), CGUIWindow::Load(), CGUITextureManager::Load(), CApplicationSkinHandling::LoadSkin(), memcpy_aligned(), XFILE::CMultiPathDirectory::MergeItems(), CEdl::MergeShortCommBreaks(), CBitstreamConverter::mpeg2_sequence_header(), UPNP::CUPnPServer::OnBrowseDirectChildren(), PVR::CGUIWindowPVRGuideBase::OnMessage(), CGUIWindowPictures::OnPrepareFileItems(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), CHttpRanges::Parse(), CGUIControlFactory::ParsePosition(), CGUITextLayout::ParseText(), CNetworkLinux::PingHost(), KODI::VIDEO::CVideoInfoScanner::Process(), CExternalPlayer::Process(), CBackgroundPicLoader::Process(), CGUIBaseContainer::Process(), CGUIPanelContainer::Process(), CGUIRSSControl::Process(), CLirc::ProcessCode(), CAirPlayServer::CTCPClient::ProcessRequest(), KODI::UTILS::RandomShuffle(), CEdl::ReadBeyondTV(), CGUIBaseContainer::Render(), CGUIPanelContainer::Render(), DXVA::CProcessorHD::Render(), CGUIWindowMusicBase::RetrieveMusicInfo(), CVideoDatabase::RunQuery(), CUtil::ScanForExternalSubtitles(), CMusicDatabase::Search(), CGUIFixedListContainer::SelectItemFromPoint(), CGUIWrappingListContainer::SelectItemFromPoint(), ADDON::Interface_GUIControlSettingsSlider::set_float_range(), ADDON::Interface_GUIControlSlider::set_float_range(), ADDON::Interface_GUIControlSpin::set_float_range(), ADDON::Interface_GUIControlSettingsSlider::set_int_range(), ADDON::Interface_GUIControlSlider::set_int_range(), ADDON::Interface_GUIControlSpin::set_int_range(), kodi::addon::PVREDLEntry::SetEnd(), PVR::CPVRTimerInfoTag::SetEndFromLocalTime(), PVR::CPVREpgInfoTag::SetEndFromUTC(), PVR::CPVRTimerInfoTag::SetEndFromUTC(), kodi::gui::controls::CSettingsSlider::SetFloatRange(), kodi::gui::controls::CSlider::SetFloatRange(), kodi::gui::controls::CSpin::SetFloatRange(), CGUILabelControl::SetHighlight(), kodi::gui::controls::CSettingsSlider::SetIntRange(), kodi::gui::controls::CSlider::SetIntRange(), kodi::gui::controls::CSpin::SetIntRange(), ADDON::CAddonDatabase::SetLastUsed(), CGUILabelControl::SetSelection(), PVR::CPVRGUIActionsChannels::StartChannelScan(), str2double(), str2double(), str2int64(), str2uint64(), TEST_F(), KODI::LINUX::TimespecDifference(), TYPED_TEST(), TYPED_TEST(), PVR::CPVREpg::Update(), PVR::CPVREpgContainer::UpdateEPG(), PVR::CPVREpg::UpdateFromScraper(), PVR::CGUIDialogPVRGuideSearch::UpdateSearchFilter(), PVR::CPVRGUITimesInfo::UpdateTimeshiftProgressData(), KODI::PLAYLIST::CSmartPlaylistRule::ValidateRating(), and CBusyWaiter::Wait().
TEST_F() [1/2]
TEST_F (TestTagLoaderTagLib , SetGenre)
References end(), EXPECT_EQ(), MUSIC_INFO::CMusicInfoTag::GetGenre(), and CTagLoaderTagLib::SetGenre().
TEST_F() [2/2]
TEST_F (TestTagLoaderTagLib , SplitMBID)
References EXPECT_EQ(), EXPECT_TRUE(), CTagLoaderTagLib::SplitMBID(), and values.
TYPED_TEST() [1/4]
TYPED_TEST (EmptyTagParser , EmptyProperties)
References end(), EXPECT_TRUE(), and tags.
TYPED_TEST() [2/4]
TYPED_TEST (TestTagParser , FooProperties)
References end(), EXPECT_EQ(), EXPECT_TRUE(), String, and tags.
TYPED_TEST() [3/4]
TYPED_TEST (TestTagParser , HandleNullTag)
TYPED_TEST() [4/4]
TYPED_TEST (TestTagParser , ParsesBasicTag)
References EXPECT_EQ(), and EXPECT_TRUE().
TYPED_TEST_SUITE() [1/2]
TYPED_TEST_SUITE (EmptyTagParser , EmptyPropertiesTagTypes)
TYPED_TEST_SUITE() [2/2]
TYPED_TEST_SUITE (TestTagParser , TagTypes)
Variable Documentation
tags
const char* tags[]
Initial value:
= { "APIC", "ASPI", "COMM", "COMR", "ENCR", "EQU2",
  "ETCO", "GEOB", "GRID", "LINK", "MCDI", "MLLT", "OWNE", "PRIV", "PCNT",
  "POPM", "POSS", "RBUF", "RVA2", "RVRB", "SEEK", "SIGN", "SYLT",
  "SYTC", "TALB", "TBPM", "TCOM", "TCON", "TCOP", "TDEN", "TDLY", "TDOR",
  "TDRC", "TDRL", "TDTG", "TENC", "TEXT", "TFLT", "TIPL", "TIT1", "TIT2",
  "TIT3", "TKEY", "TLAN", "TLEN", "TMCL", "TMED", "TMOO", "TOAL", "TOFN",
  "TOLY", "TOPE", "TOWN", "TPE1", "TPE2", "TPE3", "TPE4", "TPOS", "TPRO",
  "TPUB", "TRCK", "TRSN", "TRSO", "TSOA", "TSOP", "TSOT", "TSRC", "TSSE",
  "TSST", "TXXX", "UFID", "USER", "USLT", "WCOM", "WCOP", "WOAF", "WOAR",
  "WOAS", "WORS", "WPAY", "WPUB", "WXXX",  "ARTIST", "ARTISTS",
  "ALBUMARTIST" , "ALBUM ARTIST", "ALBUMARTISTS" , "ALBUM ARTISTS", "ALBUM",
  "TITLE", "TRACKNUMBER" "TRACK", "DISCNUMBER" "DISC", "YEAR", "GENRE",
  "COMMENT", "CUESHEET", "ENCODEDBY", "COMPILATION", "LYRICS",
  "REPLAYGAIN_TRACK_GAIN", "REPLAYGAIN_ALBUM_GAIN", "REPLAYGAIN_TRACK_PEAK",
  "REPLAYGAIN_ALBUM_PEAK", "MUSICBRAINZ_ARTISTID",
  "MUSICBRAINZ_ALBUMARTISTID", "RATING", "MUSICBRAINZ_ALBUMARTIST",
  "MUSICBRAINZ_ALBUMID", "MUSICBRAINZ_TRACKID", "METADATA_BLOCK_PICTURE",
  "COVERART"
}
Referenced by anonymous_namespace{WebVTTHandler.cpp}::ConvertStyleToCloseTags(), anonymous_namespace{WebVTTHandler.cpp}::ConvertStyleToOpenTags(), PVR::CPVREpgTagsContainer::CreateEntries(), PVR::CGUIEPGGridContainerModel::CreateEpgTags(), PVR::CPVREpgSearch::Execute(), PVR::CPVREpgTagsContainer::FixOverlappingEvents(), PVR::CPVREpgTagsContainer::FixOverlappingEvents(), PVR::CGUIEPGGridContainerModel::FreeProgrammeMemory(), PVR::CPVRTimers::GetActiveRecordings(), PVR::CPVRTimers::GetActiveTimers(), PVR::CPVREpgDatabase::GetAllEpgTags(), PVR::CPVREpgTagsContainer::GetAllTags(), JSONRPC::CPVROperations::GetBroadcasts(), PVR::CPVREpgDatabase::GetEpgTags(), PVR::CGUIEPGGridContainerModel::GetEpgTagsAfter(), PVR::CGUIEPGGridContainerModel::GetEpgTagsBefore(), PVR::CPVREpgDatabase::GetEpgTagsByMinEndMaxStartTime(), PVR::CPVREpgDatabase::GetEpgTagsByMinStartMaxEndTime(), anonymous_namespace{PVRTimers.cpp}::GetEpgTagsForTimerRule(), PVR::CPVRPlaybackState::GetNextAutoplayItem(), PVR::CPVRGUIDirectory::GetSavedSearchResults(), PVR::CPVREpgTagsContainer::GetTagBetween(), CVideoDatabase::GetTags(), PVR::CPVREpgTagsContainer::GetTimeline(), JSONRPC::CPVROperations::GetTimers(), CWebVTTHandler::InsertCssStyleCloseTag(), CWebVTTHandler::InsertCssStyleStartTag(), PVR::CPVREpgTagsContainer::MergeTags(), PVR::CGUIDialogPVRChannelGuide::OnInitWindow(), CVideoInfoTag::ParseNative(), CGUIRSSControl::Process(), PVR::CPVREpgTagsCache::Refresh(), anonymous_namespace{EpgTagsContainer.cpp}::ResolveConflictingTags(), anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction::Run(), XBMCAddon::xbmc::InfoTagVideo::setTags(), CVideoInfoTag::SetTags(), XBMCAddon::xbmc::InfoTagVideo::setTagsRaw(), TYPED_TEST(), TYPED_TEST(), PVR::CPVREpgTagsContainer::UpdateEntries(), and JSONRPC::CVideoLibrary::UpdateVideoTag().