Kodi Documentation: PERIPHERALS::PeripheralScanResults Struct Reference
PERIPHERALS::PeripheralScanResults Struct Reference
#include <PeripheralTypes.h>
Public Member Functions
bool GetDeviceOnLocation (const std::string &strLocation, PeripheralScanResult *result) const
bool ContainsResult (const PeripheralScanResult &result) const
Public Attributes
std::vector< PeripheralScanResult > m_results
Member Function Documentation
ContainsResult()
bool PERIPHERALS::PeripheralScanResults::ContainsResult (const PeripheralScanResult & result) const inline
References m_results.
Referenced by PERIPHERALS::CPeripheralBusUSB::DeviceAttachCallback(), PERIPHERALS::CPeripheralAddon::PerformDeviceScan(), PERIPHERALS::CPeripheralBusApplication::PerformDeviceScan(), and PERIPHERALS::CPeripheralBusCEC::PerformDeviceScan().
GetDeviceOnLocation()
bool PERIPHERALS::PeripheralScanResults::GetDeviceOnLocation (const std::string & strLocation, PeripheralScanResult * result) const inline
References m_results.
Referenced by PERIPHERALS::CPeripheralBus::UnregisterRemovedDevices(), and PERIPHERALS::CPeripheralAddon::UnregisterRemovedDevices().
Member Data Documentation
m_results
std::vector<PeripheralScanResult> PERIPHERALS::PeripheralScanResults::m_results
Referenced by ContainsResult(), PERIPHERALS::CPeripheralBusUSB::DeviceAttachCallback(), PERIPHERALS::CPeripheralBusUSB::DeviceDetachCallback(), GetDeviceOnLocation(), PERIPHERALS::CPeripheralBusAndroid::GetInputDevices(), PERIPHERALS::CPeripheralBusAndroid::OnInputDeviceAdded(), PERIPHERALS::CPeripheralBusAndroid::OnInputDeviceChanged(), PERIPHERALS::CPeripheralBusAndroid::OnInputDeviceRemoved(), PERIPHERALS::CPeripheralAddon::PerformDeviceScan(), PERIPHERALS::CPeripheralBusApplication::PerformDeviceScan(), PERIPHERALS::CPeripheralBusCEC::PerformDeviceScan(), and PERIPHERALS::CPeripheralBus::RegisterNewDevices().
The documentation for this struct was generated from the following file:
PeripheralTypes.h