Kodi Documentation: PERIPHERALS::CEventScanner Class Reference
PERIPHERALS::CEventScanner Class Reference
Class to scan for peripheral events.
#include <EventScanner.h>
Public Member Functions
CEventScanner (IEventScannerCallback &callback)
~CEventScanner () override=default
void Start ()
void Stop ()
EventPollHandlePtr RegisterPollHandle ()
EventLockHandlePtr RegisterLock ()
Acquire a lock that prevents event processing while held.
void Activate (CEventPollHandle &handle) override
void Deactivate (CEventPollHandle &handle) override
void HandleEvents (bool bWait) override
void Release (CEventPollHandle &handle) override
void ReleaseLock (CEventLockHandle &handle) override
Public Member Functions inherited from PERIPHERALS::IEventPollCallback
virtual ~IEventPollCallback (void)=default
Public Member Functions inherited from PERIPHERALS::IEventLockCallback
virtual ~IEventLockCallback (void)=default
Protected Member Functions
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Member Functions
std::chrono::milliseconds GetScanIntervalMs () const
Private Attributes
IEventScannerCallback & m_callback
std::set< void * > m_activeHandles
std::set< void * > m_activeLocks
CEvent m_scanEvent
CEvent m_scanFinishedEvent
CCriticalSection m_handleMutex
CCriticalSection m_lockMutex
CCriticalSection m_pollMutex
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Detailed Description
Class to scan for peripheral events.
By default, a rate of 60 Hz is used. A client can obtain control over when input is handled by registering for a polling handle.
Constructor & Destructor Documentation
CEventScanner()
CEventScanner::CEventScanner (IEventScannerCallback & callback) explicit
~CEventScanner()
PERIPHERALS::CEventScanner::~CEventScanner () override default
Member Function Documentation
Activate()
void CEventScanner::Activate (CEventPollHandle & handle) override virtual
Implements PERIPHERALS::IEventPollCallback.
References CLog::Log(), LOGDEBUG, m_activeHandles, and m_handleMutex.
Deactivate()
void CEventScanner::Deactivate (CEventPollHandle & handle) override virtual
Implements PERIPHERALS::IEventPollCallback.
References CLog::Log(), LOGDEBUG, m_activeHandles, and m_handleMutex.
GetScanIntervalMs()
std::chrono::milliseconds CEventScanner::GetScanIntervalMs () const private
References DEFAULT_SCAN_RATE_HZ, m_activeHandles, m_handleMutex, and WATCHDOG_TIMEOUT_MS.
Referenced by Process().
HandleEvents()
void CEventScanner::HandleEvents (bool bWait) override virtual
Implements PERIPHERALS::IEventPollCallback.
References m_pollMutex, m_scanEvent, m_scanFinishedEvent, CEvent::Reset(), CEvent::Set(), and CEvent::Wait().
Process()
void CEventScanner::Process (void) override protected virtual
Reimplemented from CThread.
References GetScanIntervalMs(), m_activeLocks, CThread::m_bStop, m_callback, m_lockMutex, m_scanEvent, m_scanFinishedEvent, PERIPHERALS::IEventScannerCallback::ProcessEvents(), CEvent::Set(), and CEvent::Wait().
RegisterLock()
EventLockHandlePtr CEventScanner::RegisterLock ()
Acquire a lock that prevents event processing while held.
References CLog::Log(), LOGDEBUG, m_activeLocks, and m_lockMutex.
RegisterPollHandle()
EventPollHandlePtr CEventScanner::RegisterPollHandle ()
References CLog::Log(), LOGDEBUG, m_activeHandles, and m_handleMutex.
Release()
void CEventScanner::Release (CEventPollHandle & handle) override virtual
Implements PERIPHERALS::IEventPollCallback.
References CLog::Log(), LOGDEBUG, m_activeHandles, and m_handleMutex.
ReleaseLock()
void CEventScanner::ReleaseLock (CEventLockHandle & handle) override virtual
Implements PERIPHERALS::IEventLockCallback.
References CLog::Log(), LOGDEBUG, m_activeLocks, and m_lockMutex.
Start()
void CEventScanner::Start ()
References CThread::Create().
Stop()
void CEventScanner::Stop ()
References m_scanEvent, CEvent::Set(), and CThread::StopThread().
Member Data Documentation
m_activeHandles
std::set<void*> PERIPHERALS::CEventScanner::m_activeHandles private
Referenced by Activate(), Deactivate(), GetScanIntervalMs(), RegisterPollHandle(), and Release().
m_activeLocks
std::set<void*> PERIPHERALS::CEventScanner::m_activeLocks private
Referenced by Process(), RegisterLock(), and ReleaseLock().
m_callback
IEventScannerCallback& PERIPHERALS::CEventScanner::m_callback private
Referenced by Process().
m_handleMutex
CCriticalSection PERIPHERALS::CEventScanner::m_handleMutex mutable private
Referenced by Activate(), Deactivate(), GetScanIntervalMs(), RegisterPollHandle(), and Release().
m_lockMutex
CCriticalSection PERIPHERALS::CEventScanner::m_lockMutex private
Referenced by Process(), RegisterLock(), and ReleaseLock().
m_pollMutex
CCriticalSection PERIPHERALS::CEventScanner::m_pollMutex private
Referenced by HandleEvents().
m_scanEvent
CEvent PERIPHERALS::CEventScanner::m_scanEvent private
Referenced by HandleEvents(), Process(), and Stop().
m_scanFinishedEvent
CEvent PERIPHERALS::CEventScanner::m_scanFinishedEvent private
Referenced by HandleEvents(), and Process().
The documentation for this class was generated from the following files:
EventScanner.h
EventScanner.cpp