Kodi Documentation: CAndroidStorageProvider Class Reference
CAndroidStorageProvider Class Reference
#include <AndroidStorageProvider.h>
Public Member Functions
CAndroidStorageProvider ()
~CAndroidStorageProvider () override=default
void Initialize () override
void Stop () override
bool Eject (const std::string &mountpath) override
void GetLocalDrives (std::vector< CMediaSource > &localDrives) override
void GetRemovableDrives (std::vector< CMediaSource > &removableDrives) override
std::vector< std::string > GetDiskUsage () override
bool PumpDriveChangeEvents (IStorageEventsCallback *callback) override
Public Member Functions inherited from IStorageProvider
virtual ~IStorageProvider ()=default
virtual std::string GetFirstOpticalDeviceFileName ()
Static Public Member Functions
static bool GetExternalStorage (std::string &path, const std::string &type="")
If external storage is available, it returns the path for the external storage (for the specified type)
Static Public Member Functions inherited from IStorageProvider
static std::unique_ptr< IStorageProvider > CreateInstance ()
Called by media manager to create platform storage provider.
Private Member Functions
std::string unescape (const std::string &str)
bool GetStorageUsage (const std::string &path, std::string &usage)
Static Private Member Functions
static std::set< std::string > GetRemovableDrives ()
static std::set< std::string > GetRemovableDrivesLinux ()
Private Attributes
std::vector< CMediaSource > m_removableDrives
unsigned int m_removableLength
Constructor & Destructor Documentation
CAndroidStorageProvider()
CAndroidStorageProvider::CAndroidStorageProvider ()
References PumpDriveChangeEvents().
~CAndroidStorageProvider()
CAndroidStorageProvider::~CAndroidStorageProvider () override default
Member Function Documentation
Eject()
bool CAndroidStorageProvider::Eject (const std::string & mountpath) inline override virtual
Implements IStorageProvider.
GetDiskUsage()
std::vector< std::string > CAndroidStorageProvider::GetDiskUsage (void) override virtual
Implements IStorageProvider.
References GetExternalStorage(), GetRemovableDrives(), GetStorageUsage(), and usage.
GetExternalStorage()
bool CAndroidStorageProvider::GetExternalStorage (std::string & path, const std::string & type = "") static
If external storage is available, it returns the path for the external storage (for the specified type)
Parameters
path will contain the path of the external storage (for the specified type)
type optional type. Possible values are "", "files", "music", "videos", "pictures", "photos, "downloads"
Returns
true if external storage is available and a valid path has been stored in the path parameter
Referenced by GetDiskUsage(), GetLocalDrives(), CGUIDialogMediaSource::OnPathBrowse(), and CPlatformAndroid::PlatformSyslog().
GetLocalDrives()
void CAndroidStorageProvider::GetLocalDrives (std::vector< CMediaSource > & localDrives) override virtual
Implements IStorageProvider.
References XFILE::CDirectory::Exists(), g_localizeStrings, CLocalizeStrings::Get(), GetExternalStorage(), CMediaSource::m_ignore, CMediaSource::strName, and CMediaSource::strPath.
GetRemovableDrives() [1/2]
static std::set< std::string > CAndroidStorageProvider::GetRemovableDrives () static private
Referenced by GetDiskUsage(), and PumpDriveChangeEvents().
GetRemovableDrives() [2/2]
void CAndroidStorageProvider::GetRemovableDrives (std::vector< CMediaSource > & removableDrives) override virtual
Implements IStorageProvider.
References XFILE::CDirectory::Exists(), URIUtils::GetFileName(), GetRemovableDrivesLinux(), CMediaSource::m_ignore, CMediaSource::strName, CMediaSource::strPath, and unescape().
GetRemovableDrivesLinux()
std::set< std::string > CAndroidStorageProvider::GetRemovableDrivesLinux () static private
References fclose(), CRegExp::GetReplaceString(), CLog::Log(), LOGERROR, CRegExp::RegComp(), and CRegExp::RegFind().
Referenced by GetRemovableDrives().
GetStorageUsage()
bool CAndroidStorageProvider::GetStorageUsage (const std::string & path, std::string & usage) private
References usage.
Referenced by GetDiskUsage().
Initialize()
void CAndroidStorageProvider::Initialize () inline override virtual
Implements IStorageProvider.
PumpDriveChangeEvents()
bool CAndroidStorageProvider::PumpDriveChangeEvents (IStorageEventsCallback * callback) override virtual
Implements IStorageProvider.
References GetRemovableDrives(), and m_removableDrives.
Referenced by CAndroidStorageProvider().
Stop()
void CAndroidStorageProvider::Stop () inline override virtual
Implements IStorageProvider.
unescape()
std::string CAndroidStorageProvider::unescape (const std::string & str) private
Todo:
implement
Referenced by GetRemovableDrives().
Member Data Documentation
m_removableDrives
std::vector<CMediaSource> CAndroidStorageProvider::m_removableDrives private
Referenced by PumpDriveChangeEvents().
m_removableLength
unsigned int CAndroidStorageProvider::m_removableLength private
The documentation for this class was generated from the following files:
AndroidStorageProvider.h
AndroidStorageProvider.cpp