Kodi Documentation: CGUIComponent Class Reference
CGUIComponent Class Reference
#include <GUIComponent.h>
Public Member Functions
CGUIComponent ()
CGUIComponent (bool)
virtual ~CGUIComponent ()
void Init ()
void Deinit ()
CGUIWindowManager & GetWindowManager ()
CGUITextureManager & GetTextureManager ()
CGUILargeTextureManager & GetLargeTextureManager ()
CStereoscopicsManager & GetStereoscopicsManager ()
CGUIInfoManager & GetInfoManager ()
CGUIColorManager & GetColorManager ()
CGUIAudioManager & GetAudioManager ()
bool ConfirmDelete (const std::string &path)
Protected Attributes
std::unique_ptr< CGUIWindowManager > m_pWindowManager
std::unique_ptr< CGUITextureManager > m_pTextureManager
std::unique_ptr< CGUILargeTextureManager > m_pLargeTextureManager
std::unique_ptr< CStereoscopicsManager > m_stereoscopicsManager
std::unique_ptr< CGUIInfoManager > m_guiInfoManager
std::unique_ptr< CGUIColorManager > m_guiColorManager
std::unique_ptr< CGUIAudioManager > m_guiAudioManager
std::unique_ptr< CGUIAnnouncementHandlerContainer > m_announcementHandlerContainer
Constructor & Destructor Documentation
CGUIComponent() [1/2]
CGUIComponent::CGUIComponent ()
CGUIComponent() [2/2]
CGUIComponent::CGUIComponent (bool) explicit
~CGUIComponent()
CGUIComponent::~CGUIComponent () virtual
References Deinit().
Member Function Documentation
ConfirmDelete()
bool CGUIComponent::ConfirmDelete (const std::string & path)
References CURL, GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), CGUIDialog::Open(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), and WINDOW_DIALOG_YES_NO.
Referenced by CFileUtils::DeleteItemWithConfirm(), and CProfileManager::DeleteProfile().
Deinit()
void CGUIComponent::Deinit ()
References m_pWindowManager, and CServiceBroker::UnregisterGUI().
Referenced by ~CGUIComponent().
GetAudioManager()
CGUIAudioManager & CGUIComponent::GetAudioManager ()
References m_guiAudioManager.
Referenced by CGUIWindow::Close_Internal(), XBMCAddon::xbmc::enableNavSounds(), CInputManager::ExecuteInputAction(), EVENTSERVER::CEventServer::ExecuteNextAction(), CApplicationSkinHandling::LoadSkin(), CApplication::OnAction(), KODI::JOYSTICK::CJoystickEasterEgg::OnFinish(), CGUIWindow::OnInitWindow(), ADDON::CUISoundsResource::OnPostInstall(), CApplication::PlaybackCleanup(), CApplication::PlayFile(), XBMCAddon::xbmc::playSFX(), JSONRPC::CInputOperations::SendAction(), CApplication::Stop(), XBMCAddon::xbmc::stopSFX(), and CApplicationSkinHandling::UnloadSkin().
GetColorManager()
CGUIColorManager & CGUIComponent::GetColorManager ()
References m_guiColorManager.
Referenced by CGUIControlFactory::GetColor(), CApplicationSkinHandling::LoadSkin(), KODI::GUILIB::GUIINFO::CGUIInfoColor::Parse(), CGUITextLayout::ParseText(), CApplicationSkinHandling::UnloadSkin(), and KODI::GUILIB::GUIINFO::CGUIInfoColor::Update().
GetInfoManager()
CGUIInfoManager & CGUIComponent::GetInfoManager ()
References m_guiInfoManager.
Referenced by CMusicDatabase::CommitTransaction(), CVideoDatabase::CommitTransaction(), CAnimation::Create(), CGUIControlFactory::Create(), INFO::CSkinVariable::CreateFromXML(), CGUIAction::ExecuteActions(), CGUIWindowManager::FrameMove(), CGUIWindowVisualisation::FrameMove(), CGUIDialogPictureInfo::FrameMove(), CGUIWindowSystemInfo::FrameMove(), XBMCAddon::xbmc::getCondVisibility(), CGUIDialogSeekBar::GetEpgEventProgress(), XBMCAddon::xbmc::Player::getGameInfoTag(), XBMCAddon::xbmc::getInfoImage(), XBMCAddon::xbmc::getInfoLabel(), JSONRPC::CPlayerOperations::GetItem(), UPNP::CUPnPRenderer::GetMetadata(), XBMCAddon::xbmc::Player::getMusicInfoTag(), CGUIAction::GetNavigation(), CGUIDialogSeekBar::GetProgress(), JSONRPC::CGUIOperations::GetPropertyValue(), CGUIDialogSeekBar::GetTimeshiftProgress(), XBMCAddon::xbmc::Player::getVideoInfoTag(), CGUIAction::HasActionsMeetingCondition(), PVR::CPVRGUIChannelNavigator::HideInfo(), CMusicDatabase::ImportFromXML(), anonymous_namespace{AddonSettings.cpp}::InfoBool(), CContextMenuItem::IsVisible(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::ItemLabelNeedsUpdate(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::LabelNeedsUpdate(), CGUIWindow::Load(), CGUIListItemLayout::LoadLayout(), CProfileManager::LoadProfile(), XFILE::CLibraryDirectory::LoadXML(), CGUIWindow::NeedLoad(), CApplication::OnAction(), CGUIWindowVisualisation::OnAction(), CGUIWindowFullScreen::OnAction(), CApplication::OnApplicationMessage(), CGUIWindowSlideShow::OnDeinitWindow(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), CApplication::OnMessage(), CGUIWindowVisualisation::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowMusicBase::OnRemoveSource(), KODI::GUILIB::GUIINFO::CGUIInfoBool::Parse(), KODI::GUILIB::GUIINFO::CGUIInfoColor::Parse(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::Parse(), CGUIWindowManager::PreviousWindow(), MUSIC_INFO::CMusicInfoScanner::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), PVR::CPVRGUIInfo::Process(), CGUIVisualisationControl::Process(), CGUIWindowDebugInfo::Process(), CGUIWindowSlideShow::Process(), CVideoPlayerAudioID3::ProcessID3v1(), CVideoPlayerAudioID3::ProcessID3v2(), CDVDRadioRDSData::ProcessUECP(), CAirTunesServer::RefreshCoverArt(), CAirTunesServer::RefreshMetadata(), CApplication::Render(), CSkinSettings::Reset(), SeekPercentage(), PVR::CPVRGUIChannelNavigator::SelectChannel(), CGUIBaseContainer::SetAutoScrolling(), CGUITextBox::SetAutoScrolling(), CGUITextBox::SetAutoScrolling(), CGUIBaseContainer::SetContainerMoving(), CGUIWindowSystemInfo::SetControlLabel(), CGUIControl::SetEnableCondition(), CGUIWindow::SetInitialVisibility(), CGUIDialogPictureInfo::SetPicture(), PVR::CPVRGUIChannelNavigator::SetPlayingChannel(), CGUIRadioButtonControl::SetToggleSelect(), CGUIToggleButtonControl::SetToggleSelect(), CGUIStaticItem::SetVisibleCondition(), CGUIControl::SetVisibleCondition(), PVR::CPVRGUIChannelNavigator::ShowInfo(), PVR::CPVRGUIInfo::Stop(), PVR::CPVRGUIChannelNavigator::SubscribeToShowInfoEventStream(), CApplicationSkinHandling::UnloadSkin(), KODI::GUILIB::GUIINFO::CGUIInfoColor::Update(), CApplication::UpdateCurrentPlayArt(), CGUIRangesControl::UpdateInfo(), CGUIDialogPictureInfo::UpdatePictureInfo(), CXBMCApp::UpdateSessionMetadata(), UPNP::CUPnPRenderer::UpdateState(), CGUIVisualisationControl::UpdateTrack(), and CGUIViewControl::UpdateViewVisibility().
GetLargeTextureManager()
CGUILargeTextureManager & CGUIComponent::GetLargeTextureManager ()
References m_pLargeTextureManager.
Referenced by CGUITexture::FreeResources(), CApplication::ProcessSlow(), and CApplicationSkinHandling::UnloadSkin().
GetStereoscopicsManager()
CStereoscopicsManager & CGUIComponent::GetStereoscopicsManager ()
References m_stereoscopicsManager.
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), CProfileManager::FinalizeLoadProfile(), JSONRPC::CGUIOperations::GetPropertyValue(), JSONRPC::CGUIOperations::GetStereoModeObjectFromGuiMode(), CApplicationPlayerCallback::OnAVChange(), CVideoPlayer::OpenVideoStream(), CDisplaySettings::SettingOptionsPreferredStereoscopicViewModesFiller(), and CDisplaySettings::SettingOptionsStereoscopicModesFiller().
GetTextureManager()
CGUITextureManager & CGUIComponent::GetTextureManager ()
References m_pTextureManager.
Referenced by CGUITexture::AllocResources(), XBMCAddon::xbmcgui::WindowXML::AllocResources(), ADDON::CGUIAddonWindow::AllocResources(), CGUIFontTTFGL::DeleteHardwareTexture(), CGUIFontTTFGLES::DeleteHardwareTexture(), CGLTexture::DestroyTextureObject(), CGLESTexture::DestroyTextureObject(), CImageLoader::DoWork(), CGUIMultiImage::CMultiImageJob::DoWork(), CGUIFontTTFGL::FirstBegin(), CGUIFontTTFGLES::FirstBegin(), CGUITexture::FreeResources(), XFILE::GenerateGameListing(), XFILE::GenerateTypeListing(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectory(), XFILE::CSourcesDirectory::GetDirectory(), CGUIMultiImage::LoadDirectory(), XBMCAddon::xbmcgui::WindowXML::Process(), CApplication::ProcessSlow(), ADDON::CGUIAddonWindow::Render(), CGraphicContext::SetMediaDir(), XBMCAddon::xbmc::skinHasImage(), and CApplicationSkinHandling::UnloadSkin().
GetWindowManager()
CGUIWindowManager & CGUIComponent::GetWindowManager ()
References m_pWindowManager.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonDeleteGroup(), anonymous_namespace{GUIBuiltins.cpp}::ActivateAndFocus(), PVR::CGUIWindowPVRProvidersBase::ActivateChannelsWindow(), PVR::CGUIWindowPVRProvidersBase::ActivateRecordingsWindow(), CApplicationPowerHandling::ActivateScreenSaver(), anonymous_namespace{GUIBuiltins.cpp}::ActivateWindow(), PVR::CPVRRadioRDSInfoTag::Info::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), CMediaManager::AddAutoSource(), XBMCAddon::xbmcgui::ControlFadeLabel::addLabel(), CGUIDialogVideoManagerVersions::AddVideoVersion(), KODI::GAME::CDialogGameVolume::Announce(), CGUIPlayerAnnouncementHandler::Announce(), CGUISourcesAnnouncementHandler::Announce(), CGUIWindowHome::Announce(), PVR::CPVRGUIActionsTimers::AnnounceReminder(), CGraphicContext::ApplyVideoResolution(), CGUIDialogAddonInfo::AskForVersion(), CZeroconfBrowserAvahi::browseCallback(), anonymous_namespace{ContextMenus.cpp}::CanQueue(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CanQueue(), CScreenshotSurfaceWindows::Capture(), CScreenshotSurfaceGL::Capture(), CScreenshotSurfaceGLES::Capture(), CGUIDialogCache::CGUIDialogCache(), CGUIViewStateFromItems::CGUIViewStateFromItems(), CGUIViewStateLibrary::CGUIViewStateLibrary(), ChangeSortMethod(), ChangeViewMode(), PVR::CPVRGUIActionsPlayback::CheckAndSwitchToFullscreen(), CInertialScrollingHandler::CheckForInertialScrolling(), CGUIPassword::CheckMenuLock(), CGUIPassword::CheckSettingLevelLock(), CApplicationPowerHandling::CheckShutdown(), anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), CGUIViewState::ChooseSortMethod(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::ChooseStackItemPartNumber(), CGUIDialogVideoManagerVersions::ChooseVideoAndConvertToVideoVersion(), CGUIDialogVideoManager::ChooseVideoAsset(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideoExtra(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideoVersion(), CTextureCache::CleanAllUnusedImages(), CVideoDatabase::CleanDatabase(), CMusicLibraryQueue::CleanLibrary(), CVideoDatabase::CleanMediaType(), CGUIViewControl::Clear(), CGUIWindowFileManager::ClearFileItems(), CGUIWindowSettingsProfile::ClearListItems(), KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist(), anonymous_namespace{GUIBuiltins.cpp}::ClearProperty(), CZeroconfBrowserAvahi::clientCallback(), ADDON::Interface_GUIWindow::close(), CGUIDialogVideoManager::CloseAll(), anonymous_namespace{GUIBuiltins.cpp}::CloseDialog(), KODI::RETRO::CRetroPlayer::CloseOSD(), XBMCAddon::xbmcgui::Dialog::colorpicker(), ConfirmDelete(), XBMCAddon::xbmcgui::Dialog::contextmenu(), ControlMove(), XBMCAddon::xbmcgui::ControlEdit::Create(), XBMCAddon::xbmcgui::DialogProgress::create(), XBMCAddon::xbmcgui::DialogProgressBG::create(), ADDON::Interface_GUIWindow::create(), CGUIVisualisationControl::DeInitVisualization(), CMusicDatabase::DeleteCDDBInfo(), CProfileManager::DeleteProfile(), CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), ADDON::Interface_GUIWindow::destroy(), CGUIDialogSlider::Display(), XBMCAddon::xbmcgui::Window::dispose(), ADDON::Interface_GUIWindow::do_modal(), CProgressJob::DoModal(), CGUIDialogBusy::DoProcess(), CGUIDialogBusyNoCancel::DoProcess(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), KODI::CDRIP::CCDDARipJob::DoWork(), CGetInfoJob::DoWork(), CRefreshInfoJob::DoWork(), CGetSongInfoJob::DoWork(), CAutorunMediaJob::DoWork(), CFileOperationJob::DoWork(), CWeatherJob::DoWork(), CSaveFileState::DoWork(), CGUIDialogSmartPlaylistEditor::EditPlaylist(), CGUIDialogSmartPlaylistRule::EditRule(), PVR::CPVRGUIActionsEPG::EditSavedSearch(), CPartyModeManager::Enable(), anonymous_namespace{PVRBuiltins.cpp}::EpgGridControl(), CMediaLibraryEvent::Execute(), CONTEXTMENU::CMusicBrowse::Execute(), CONTEXTMENU::CMusicQueue::Execute(), CONTEXTMENU::CVideoBrowse::Execute(), CONTEXTMENU::CVideoQueue::Execute(), CONTEXTMENU::CVideoPlayAndQueue::Execute(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::ExecuteAction(), FAVOURITES_UTILS::anonymous_namespace{FavouritesUtils.cpp}::ExecuteAction(), anonymous_namespace{DirectoryProvider.cpp}::ExecuteAction(), CGUIAction::ExecuteActions(), PVR::CPVRGUIActionsEPG::ExecuteSavedSearch(), CMusicLibraryQueue::ExportLibrary(), CVideoDatabase::ExportToXML(), CProfileManager::FinalizeLoadProfile(), PVR::CPVRGUIActionsEPG::FindSimilar(), CGraphicContext::Flip(), CApplicationPlayer::FrameMove(), CSeekHandler::FrameMove(), KODI::RETRO::CGUIPlaybackControl::FrameMove(), CGUIWindowSettingsScreenCalibration::FrameMove(), CApplication::FrameMove(), ADDON::Interface_GUIGeneral::get_current_window_dialog_id(), ADDON::Interface_GUIGeneral::get_current_window_id(), JSONRPC::CPlayerOperations::GetActivePlayers(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetBool(), PVR::CPVRGUIActionsChannels::GetChannelGroupMember(), PVR::CPVRGUIActionsChannels::GetChannelNumberInputHandler(), XBMCAddon::xbmc::getCondVisibility(), XBMCAddon::xbmcgui::getCurrentWindowDialogId(), XBMCAddon::xbmcgui::getCurrentWindowId(), KODI::GAME::CGUIDialogSelectSavestate::GetDialog(), KODI::GAME::CGUIDialogSelectGameClient::GetDialog(), XFILE::CMultiPathDirectory::GetDirectory(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetInt(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CGUIDialogVideoInfo::GetItemsForTag(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetLabel(), CWeatherManager::GetLocation(), CGUIDialogVideoInfo::GetMoviesForSet(), KODI::PLAYLIST::CPlayListPlayer::GetNextItemIdx(), KODI::RETRO::CGameWindowFullScreen::GetOSD(), CGUIWindowFullScreen::GetOSD(), JSONRPC::CGUIOperations::GetPropertyValue(), anonymous_namespace{PVRGUIActionsEPG.cpp}::GetSearchWindow(), CGUIWindowSettingsProfile::GetSelectedItem(), CGUIViewControl::GetSelectedItem(), CGUIDialogVideoInfo::GetSetForMovie(), CStereoscopicsManager::GetStereoModeByUserChoice(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::GetTargetWindowID(), XBMCAddon::xbmcgui::ControlEdit::getText(), CAutoSwitch::GetView(), KODI::GUILIB::GUIINFO::anonymous_namespace{GUIInfoHelper.cpp}::GetWindowWithCondition(), CInputCodingTableBasePY::GetWordListPage(), KODI::GAME::CDialogGameSaves::HandleCaption(), KODI::GAME::CDialogGameSaves::HandleGameClient(), CInputManager::HandleKey(), PVR::CPVRGUIActionsChannels::HideChannel(), CVideoDatabase::ImportFromXML(), CMusicLibraryQueue::ImportLibrary(), CApplication::Initialize(), KODI::PLAYLIST::CPlayListPlayer::Insert(), KODI::GAME::CGameClientProperties::InstallDependencies(), CGUIWindowAddonBrowser::InstallFromZip(), CGUIWindow::IsActive(), CGUIPassword::IsDatabasePathUnlocked(), CApplication::IsFullScreen(), CONTEXTMENU::CVideoPlayAndQueue::IsVisible(), CGUIDialogVideoInfo::LinkMovieToTvShow(), CApplicationSkinHandling::LoadCustomWindows(), CGUIWindowMusicBase::LoadPlayList(), CGUIWindowPictures::LoadPlayList(), CProfileManager::LoadProfile(), CApplicationSkinHandling::LoadSkin(), CGUIPassword::LockSource(), CGUIPassword::LockSources(), CProfileManager::LogOff(), CMusicDatabase::LookupCDDBInfo(), CGUIDialogVideoManagerExtras::ManageVideoExtras(), CGUIDialogVideoInfo::ManageVideoItemArtwork(), CGUIDialogVideoManagerVersions::ManageVideoVersions(), CBaseRenderer::MarkDirty(), MasterMode(), CWinEventsAndroid::MessagePump(), CWinEventsWin10::MessagePump(), KODI::WINDOWING::X11::CWinEventsX11::MessagePump(), XBMCAddon::xbmcgui::Dialog::multiselect(), ADDON::Interface_GUIDialogProgress::new_dialog(), ADDON::Interface_GUIDialogExtendedProgress::new_dialog(), CGUIDialogSmartPlaylistEditor::NewPlaylist(), JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CApplication::OnAction(), XBMCAddon::xbmcgui::WindowDialogMixin::OnAction(), KODI::RETRO::CGameWindowFullScreen::OnAction(), CGUIWindowMusicBase::OnAction(), CGUIWindowMusicPlayList::OnAction(), CGUIWindowVisualisation::OnAction(), CGUIDialogPictureInfo::OnAction(), CGUIWindowSlideShow::OnAction(), CGUIWindowSettingsScreenCalibration::OnAction(), CPlayerController::OnAction(), CGUIWindowFullScreen::OnAction(), CGUIWindowVideoBase::OnAction(), CGUIWindowVideoPlaylist::OnAction(), CGUIWindowHome::OnAction(), CGUIDialogVideoBookmarks::OnAddBookmark(), CGUIDialogVideoBookmarks::OnAddEpisodeBookmark(), CApplication::OnApplicationMessage(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CApplicationPlayerCallback::OnAVChange(), CApplicationPlayerCallback::OnAVStarted(), CGUIWindow::OnBack(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIControlColorButtonSetting::OnClick(), CGUIControlListSetting::OnClick(), CGUIMediaWindow::OnClick(), PVR::CGUIDialogPVRChannelManager::OnClickButtonGroupManager(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRefreshChannelLogos(), CGUIDialogContextMenu::OnContextButton(), PVR::CGUIDialogPVRChannelManager::OnContextButton(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), PVR::CGUIWindowPVRGuideBase::OnContextButtonNavigate(), XBMCAddon::xbmcgui::Window::OnDeinitWindow(), KODI::RETRO::CGameWindowFullScreen::OnDeinitWindow(), KODI::GAME::CDialogGameVolume::OnDeinitWindow(), CGUIDialog::OnDeinitWindow(), XBMCAddon::xbmcgui::WindowDialog::OnDeinitWindow(), XBMCAddon::xbmcgui::WindowXMLDialog::OnDeinitWindow(), PVR::CGUIWindowPVRGuideBase::OnDeinitWindow(), CGUIWindowStartup::OnDeinitWindow(), CGUIWindowVideoNav::OnDeleteItem(), KODI::GAME::CDialogGameVideoSelect::OnDescriptionChange(), PERIPHERALS::CPeripherals::OnDeviceChanged(), OnDirectoryScanned(), KODI::VIDEO::OnDirectoryScanned(), CGUIDialogSubtitles::OnDownloadComplete(), CPythonInvoker::onError(), CGUIWindowAddonBrowser::OnEvent(), CGUIWindowAddonBrowser::OnEvent(), CInputManager::OnEvent(), CGUIDialogSmartPlaylistRule::OnField(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSongInfo::OnGetArt(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), KODI::GAME::CDialogGameVolume::OnInitWindow(), CGUIDialogVisualisationPresetList::OnInitWindow(), CGUIMediaWindow::OnInitWindow(), CGUIWindowPictures::OnItemInfo(), ADDON::CAddonInstaller::OnJobComplete(), ADDON::CAddonInstaller::OnJobProgress(), CInputManager::OnKey(), CGUIDialogSmartPlaylistEditor::OnLimit(), CPictureThumbLoader::OnLoaderFinish(), CGUIWindowAddonBrowser::OnMessage(), CApplication::OnMessage(), KODI::GAME::CGUIWindowGames::OnMessage(), GUIFontManager::OnMessage(), CGUIDialogMusicInfo::OnMessage(), CGUIDialogMusicOSD::OnMessage(), CGUIDialogSongInfo::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowVisualisation::OnMessage(), CGUIWindowPictures::OnMessage(), KODI::PLAYLIST::CPlayListPlayer::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIDialogVideoOSD::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIVideoControl::OnMouseEvent(), CGUIWindowVisualisation::OnMouseEvent(), CGUIDialogLibExportSettings::OnOK(), CGUIDialogSmartPlaylistRule::OnOperator(), CGUIDialogSmartPlaylistEditor::OnOrder(), CXBMCApp::onPause(), CApplicationPlayerCallback::OnPlayBackEnded(), CApplicationPlayerCallback::OnPlayBackError(), CApplicationPlayerCallback::OnPlayBackPaused(), CApplicationPlayerCallback::OnPlayBackResumed(), CApplicationPlayerCallback::OnPlayBackSeek(), CApplicationPlayerCallback::OnPlayBackSpeedChanged(), CApplicationPlayerCallback::OnPlayBackStarted(), CApplicationPlayerCallback::OnPlayBackStopped(), CGUIWindowFileManager::OnPopupMenu(), ADDON::CSkinInfo::OnPostInstall(), CGUIWindowPictures::OnPrepareFileItems(), CApplicationPlayerCallback::OnQueueNextItem(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), CGUIWindowVideoBase::OnSearch(), CGUIDialogVideoInfo::OnSearch(), ADDON::CAddonSystemSettings::OnSettingAction(), CApplicationSettingsHandling::OnSettingAction(), PERIPHERALS::CPeripherals::OnSettingAction(), CGUIDialogLockSettings::OnSettingAction(), PVR::CPVRGUIActionListener::OnSettingAction(), CGUIDialogContentSettings::OnSettingAction(), CGUIDialogSubtitleSettings::OnSettingAction(), CGUIDialogVideoSettings::OnSettingAction(), CApplicationSkinHandling::OnSettingChanged(), CGUIDialogMediaFilter::OnSettingChanged(), CWeatherManager::OnSettingChanged(), CGUIDialogVideoInfo::OnSetUserrating(), CGUIWindowPictures::OnShowPictureRecursive(), CPowerManager::OnSleep(), CGUIWindowFileManager::OnStart(), CStereoscopicsManager::OnStreamChange(), CGUIDialogSmartPlaylistEditor::OnType(), CGUIWindowVideoBase::OnUnAssignContent(), UPNP::CUPnPServer::OnUpdateObject(), CPowerManager::OnWake(), ADDON::Interface_GUIDialogContextMenu::open(), ADDON::Interface_GUIDialogSelect::open(), ADDON::Interface_GUIDialogTextViewer::open(), CGUIDialog::Open_Internal(), ADDON::Interface_GUIDialogSelect::open_multi_select(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), OpenDefaultSettings(), PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream(), KODI::RETRO::CRetroPlayer::OpenOSD(), CGUIDialogVideoInfo::Play(), KODI::PLAYLIST::CPlayListPlayer::Play(), CApplication::PlaybackCleanup(), PVR::CPVRGUIActionsPlayback::PlayEpgTag(), PlayerControl(), CApplication::PlayFile(), KODI::PLAYLIST::CPlayListPlayer::PlayNext(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), PVR::CPVRGUIActionsPlayback::PlayRecording(), CGUIDialogVideoInfo::PlayTrailer(), CGUIDialogContextMenu::PositionAtCurrentFocus(), CPowerManager::Powerdown(), MUSIC_INFO::CMusicInfoScanner::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), ADDON::CAddonStatusHandler::Process(), CApplication::Process(), CExternalPlayer::Process(), CGUIDialogCache::Process(), KODI::GAME::CControllerInstaller::Process(), KODI::GAME::CControllerSelect::Process(), KODI::JOYSTICK::CGUIDialogNewJoystick::Process(), PVR::CPVRGUIProgressHandler::Process(), CGUIWindowDebugInfo::Process(), CMediaManager::ProcessEvents(), CGUIMediaWindow::ProcessRenderLoop(), CGUIDialog::ProcessRenderLoop(), PVR::CPVRGUIActionsClients::ProcessSettingsMenuHooks(), CApplication::ProcessSlow(), ProgressDialogHelper::ProgressDialogHelper(), PVR::CGUIDialogPVRChannelManager::PromptAndSaveList(), MUSIC_UTILS::QueueItem(), CPowerManager::Reboot(), CMusicLibraryQueue::Refresh(), CVideoLibraryQueue::Refresh(), Refresh(), CAirTunesServer::RefreshCoverArt(), CGUIDialogMusicInfo::RefreshInfo(), KODI::GAME::CDialogGameVideoSelect::RefreshList(), KODI::RETRO::CGUIGameMessenger::RefreshSavestates(), CApplicationSkinHandling::ReloadSkin(), KODI::PLAYLIST::CPlayListPlayer::Remove(), CMediaManager::RemoveAutoSource(), CGUIPassword::RemoveSourceLocks(), CApplication::Render(), XBMCAddon::xbmcgui::ControlList::reset(), XBMCAddon::xbmcgui::ControlFadeLabel::reset(), XBMCAddon::xbmcgui::ControlTextBox::reset(), KODI::PLAYLIST::CPlayListPlayer::Reset(), ADDON::Interface_GUIControlSettingsSlider::reset(), ADDON::Interface_GUIControlSlider::reset(), ADDON::Interface_GUIControlSpin::reset(), ADDON::Interface_GUIControlTextBox::reset(), CGUIWindowSettingsScreenCalibration::ResetCalibration(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), CDVDRadioRDSData::ResetRDSCache(), CGUIWindowSlideShow::RunSlideShow(), CGUIWindowSlideShow::RunSlideShow(), CGUIDialogAddonSettings::SaveAndClose(), PVR::CGUIDialogPVRChannelManager::SaveList(), CGUIViewStateFromItems::SaveViewState(), CGUIViewStateLibrary::SaveViewState(), SearchVideoLibrary(), anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::Select(), XBMCAddon::xbmcgui::Dialog::select(), CGUIWindowAddonBrowser::SelectAddonID(), SelectBool(), XBMCAddon::xbmcgui::ControlList::selectItem(), anonymous_namespace{ContextMenus.cpp}::SelectNextItem(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::SelectNextItem(), CGUISliderControl::SendClick(), SendClick(), XBMCAddon::xbmcgui::ControlList::sendLabelBind(), CEventLog::SendMessage(), SendMessage(), JSONRPC::CInputOperations::SendText(), CPartyModeManager::SendUpdateMessage(), CGUIControl::SendWindowMessage(), ADDON::Interface_GUIControlLabel::set_label(), ADDON::Interface_GUIControlSettingsSlider::set_text(), ADDON::Interface_GUIControlSpin::set_text(), ADDON::Interface_GUIControlTextBox::set_text(), SetColor(), CGUIViewControl::SetCurrentView(), SetDefaultAddon(), CGUIDialogVideoManagerVersions::SetDefaultVideoVersion(), XBMCAddon::xbmcgui::Window::setFocus(), SetFocus(), CGUIViewControl::SetFocused(), XBMCAddon::xbmcgui::Window::setFocusId(), CWeatherJob::SetFromProperties(), SetHidden(), XBMCAddon::xbmcgui::ControlLabel::setLabel(), XBMCAddon::xbmcgui::ControlEdit::setLabel(), SetLocation(), ADDON::SetProgressIndicator(), anonymous_namespace{GUIBuiltins.cpp}::SetProperty(), KODI::PLAYLIST::CPlayListPlayer::SetRepeat(), CGUIViewControl::SetSelectedItem(), KODI::PLAYLIST::CPlayListPlayer::SetShuffle(), SetSortMethod(), KODI::RETRO::CRetroPlayer::SetSpeed(), XBMCAddon::xbmcgui::ControlEdit::setText(), XBMCAddon::xbmcgui::ControlTextBox::setText(), CGUIDialogVideoInfo::SetUserrating(), CGraphicContext::SetVideoResolutionInternal(), SetViewMode(), SetVisible(), XBMCAddon::xbmcgui::Window::setWindow(), ShiftPage(), FAVOURITES_UTILS::ShouldEnableMoveItems(), CGUIDialogInfoProviderSettings::Show(), CGUIDialogInfoProviderSettings::Show(), CGUIDialogLibExportSettings::Show(), CGUIDialogContextMenu::Show(), Show(), PERIPHERALS::CGUIDialogPeripherals::Show(), ADDON::Interface_GUIWindow::show(), ADDON::CGUIAddonWindowDialog::Show_Internal(), CGUIDialogMediaSource::ShowAndAddMediaSource(), CGUIDialogMediaFilter::ShowAndEditMediaFilter(), CGUIDialogMediaSource::ShowAndEditMediaSource(), CGUIDialogContextMenu::ShowAndGetChoice(), CGUIDialogNumeric::ShowAndGetDate(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFileList(), CGUIDialogFileBrowser::ShowAndGetImage(), CGUIDialogKeyboardGeneric::ShowAndGetInput(), CGUIDialogOK::ShowAndGetInput(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogOK::ShowAndGetInput(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogSlider::ShowAndGetInput(), CGUIDialogPlayEject::ShowAndGetInput(), CGUIKeyboardFactory::ShowAndGetInput(), CGUIDialogNumeric::ShowAndGetIPAddress(), CGUIDialogLockSettings::ShowAndGetLock(), CGUIDialogNetworkSetup::ShowAndGetNetworkAddress(), CGUIDialogNumeric::ShowAndGetNumber(), CGUIDialogNumeric::ShowAndGetSeconds(), CGUIDialogFileBrowser::ShowAndGetSource(), CGUIDialogNumeric::ShowAndGetTime(), CGUIDialogLockSettings::ShowAndGetUserAndPassword(), CGUIDialogGamepad::ShowAndVerifyInput(), CGUIDialogNumeric::ShowAndVerifyInput(), PVR::CPVRGUIActionsEPG::ShowChannelEPG(), PVR::CGUIWindowPVRChannelsBase::ShowChannelManager(), KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), CGUIDialogAddonInfo::ShowDependencyList(), PVR::CPVRGUIActionsEPG::ShowEPGInfo(), CGUIDialogMusicInfo::ShowFor(), CGUIDialogSongInfo::ShowFor(), CGUIDialogVideoInfo::ShowFor(), CGUIDialogAddonSettings::ShowForAddon(), CGUIDialogTextViewer::ShowForFile(), CGUIDialogAddonInfo::ShowForItem(), CGUIDialogAddonSettings::ShowForMultipleInstances(), CGUIDialogProfileSettings::ShowForProfile(), CGUIDialogAddonSettings::ShowForSingleInstance(), CEventLog::ShowFullEventLog(), PVR::CGUIWindowPVRChannelsBase::ShowGroupManager(), CGUIWindowVideoBase::ShowInfo(), CGUIWindowPictures::ShowPicture(), CGUIDialogSimpleMenu::ShowPlaySelection(), PVR::CGUIWindowPVRBase::ShowProgressDialog(), PVR::CPVRGUIActionsRecordings::ShowRecordingInfo(), PVR::CPVRGUIActionsRecordings::ShowRecordingSettings(), MUSIC_UTILS::ShowSelectArtTypeDialog(), MUSIC_UTILS::ShowSelectRatingDialog(), CGUIDialogAddonInfo::ShowSupportList(), PVR::CPVRGUIActionsTimers::ShowTimerSettings(), CApplicationVolumeHandling::ShowVolumeBar(), Slideshow(), CNetworkServices::Start(), PVR::CPVRGUIActionsChannels::StartChannelScan(), CApplication::StopPlaying(), KODI::PLAYLIST::CPlayListPlayer::Swap(), SwitchLocation(), CGUIDialogContextMenu::SwitchMedia(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), XBMCAddon::xbmcgui::Dialog::textviewer(), ToggleSortDirection(), CGUIDialogMediaFilter::TriggerFilter(), CApplicationSkinHandling::UnloadSkin(), CGUIDialogVideoInfo::Update(), Update(), CGUIViewControl::UpdateContents(), CGUIWindowFileManager::UpdateControl(), XBMCAddon::xbmc::Player::updateInfoTag(), CRecentlyAddedJob::UpdateMusic(), CGUIDialogSettingsBase::UpdateSettingControl(), ADDON::Interface_Base::UpdateSettingInActiveDialog(), XBMCAddon::xbmcaddon::Addon::UpdateSettingInActiveDialog(), CRecentlyAddedJob::UpdateTotal(), CRecentlyAddedJob::UpdateVideo(), CGUIViewControl::UpdateViewAsControl(), CGUIMediaWindow::WaitForNetwork(), CGUIMediaWindow::WaitGetDirectoryItems(), CGUIDialogBusy::WaitOnEvent(), CScriptRunner::WaitOnScriptResult(), CApplicationPowerHandling::WakeUpScreenSaver(), XBMCAddon::xbmcgui::Window::Window(), CWinEventsWin32::WndProc(), and CVideoLibraryRefreshingJob::Work().
Init()
void CGUIComponent::Init ()
References m_guiInfoManager, m_pWindowManager, m_stereoscopicsManager, and CServiceBroker::RegisterGUI().
Member Data Documentation
m_announcementHandlerContainer
std::unique_ptr<CGUIAnnouncementHandlerContainer> CGUIComponent::m_announcementHandlerContainer protected
m_guiAudioManager
std::unique_ptr<CGUIAudioManager> CGUIComponent::m_guiAudioManager protected
Referenced by GetAudioManager().
m_guiColorManager
std::unique_ptr<CGUIColorManager> CGUIComponent::m_guiColorManager protected
Referenced by GetColorManager().
m_guiInfoManager
std::unique_ptr<CGUIInfoManager> CGUIComponent::m_guiInfoManager protected
Referenced by GetInfoManager(), and Init().
m_pLargeTextureManager
std::unique_ptr<CGUILargeTextureManager> CGUIComponent::m_pLargeTextureManager protected
Referenced by GetLargeTextureManager().
m_pTextureManager
std::unique_ptr<CGUITextureManager> CGUIComponent::m_pTextureManager protected
Referenced by GetTextureManager().
m_pWindowManager
std::unique_ptr<CGUIWindowManager> CGUIComponent::m_pWindowManager protected
Referenced by Deinit(), GetWindowManager(), and Init().
m_stereoscopicsManager
std::unique_ptr<CStereoscopicsManager> CGUIComponent::m_stereoscopicsManager protected
Referenced by GetStereoscopicsManager(), and Init().
The documentation for this class was generated from the following files:
GUIComponent.h
GUIComponent.cpp