Kodi Documentation: KODI::JOYSTICK::CJoystickEasterEgg Class Reference
KODI::JOYSTICK::CJoystickEasterEgg Class Reference
Input » Joystick
Hush!!!
#include <JoystickEasterEgg.h>
Public Member Functions
CJoystickEasterEgg (const std::string &controllerId)
~CJoystickEasterEgg () override=default
bool OnButtonPress (const FeatureName &feature) override
bool IsCapturing () override
Returns true if a sequence is being captured to prevent input from falling through to the application.
Public Member Functions inherited from KODI::JOYSTICK::IButtonSequence
virtual ~IButtonSequence ()=default
Static Public Member Functions
static void OnFinish (void)
Private Attributes
const std::string m_controllerId
unsigned int m_state = 0
Static Private Attributes
static const std::map< std::string, std::vector< FeatureName > > m_sequence
Detailed Description
Hush!!!
Constructor & Destructor Documentation
CJoystickEasterEgg()
CJoystickEasterEgg::CJoystickEasterEgg (const std::string & controllerId) explicit
~CJoystickEasterEgg()
KODI::JOYSTICK::CJoystickEasterEgg::~CJoystickEasterEgg () override default
Member Function Documentation
IsCapturing()
bool CJoystickEasterEgg::IsCapturing () override virtual
Returns true if a sequence is being captured to prevent input from falling through to the application.
Implements KODI::JOYSTICK::IButtonSequence.
References m_state.
Referenced by OnButtonPress().
OnButtonPress()
bool CJoystickEasterEgg::OnButtonPress (const FeatureName & feature) override virtual
Implements KODI::JOYSTICK::IButtonSequence.
References IsCapturing(), m_controllerId, m_sequence, m_state, and OnFinish().
OnFinish()
void CJoystickEasterEgg::OnFinish (void) static
Todo:
Shake screen
References KODI::GAME::CGameSettings::GamesEnabled(), KODI::GAME::CGameServices::GameSettings(), CGUIComponent::GetAudioManager(), CServiceBroker::GetGameServices(), CServiceBroker::GetGUI(), CGUIAudioManager::PlayWindowSound(), SOUND_DEINIT, SOUND_INIT, KODI::GAME::CGameSettings::ToggleGames(), and WINDOW_DIALOG_KAI_TOAST.
Referenced by OnButtonPress(), and KODI::KEYBOARD::CKeyboardEasterEgg::OnKeyPress().
Member Data Documentation
m_controllerId
const std::string KODI::JOYSTICK::CJoystickEasterEgg::m_controllerId private
Referenced by OnButtonPress().
m_sequence
const std::map< std::string, std::vector< FeatureName > > CJoystickEasterEgg::m_sequence static private
Referenced by OnButtonPress().
m_state
unsigned int KODI::JOYSTICK::CJoystickEasterEgg::m_state = 0 private
Referenced by IsCapturing(), and OnButtonPress().
The documentation for this class was generated from the following files:
JoystickEasterEgg.h
JoystickEasterEgg.cpp