Kodi Documentation: KODI::NETWORK Namespace Reference
KODI::NETWORK Namespace Reference
Functions
bool IsInternetStream (const CFileItem &item)
Check whether an item is a an internet stream.
bool IsRemote (const CFileItem &item)
Check whether an item is on a remote location.
bool IsStreamedFilesystem (const CFileItem &item)
Check whether an item is on a streamed filesystem.
Function Documentation
IsInternetStream()
bool KODI::NETWORK::IsInternetStream (const CFileItem & item)
Check whether an item is a an internet stream.
References CFileItem::GetDynPath(), CGUIListItem::HasProperty(), and URIUtils::IsInternetStream().
Referenced by CDVDFileInfo::CanExtract(), KODI::PLAYLIST::CPlayListFactory::Create(), CDVDFactoryInputStream::CreateInputStream(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), CFileItem::Exists(), KODI::VIDEO::UTILS::FindTrailer(), CGUIWindowMusicNav::GetContextButtons(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::ART::GetLocalFanart(), CPlayerSelectionRule::GetPlayers(), CFileItem::GetUserMusicThumb(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::InitCurrentItem(), CFileItem::IsFileFolder(), KODI::PLAYLIST::CPlayListFactory::IsPlaylist(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), MUSIC_INFO::CMusicInfoLoader::LoadItemCached(), CPictureInfoLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CPictureInfoLoader::LoadItemLookup(), CApplicationPlayerCallback::OnPlayBackStarted(), CGUIMediaWindow::OnPlayMedia(), CGUIWindowMusicBase::OnPlayMedia(), CApplication::PlayMedia(), CUtil::ScanForExternalAudio(), CUtil::ScanForExternalSubtitles(), CFileItem::SetMimeTypeForInternetFile(), CFileItem::SkipLocalArt(), CGUIWindowVideoBase::StackingAvailable(), TEST(), and TEST_P().
IsRemote()
bool KODI::NETWORK::IsRemote (const CFileItem & item)
Check whether an item is on a remote location.
References CFileItem::GetPath(), and URIUtils::IsRemote().
Referenced by KODI::CDRIP::CCDDARipJob::DoWork(), XFILE::CSourcesDirectory::GetDirectory(), CPlayerSelectionRule::GetPlayers(), CFileItem::GetUserMusicThumb(), CVideoPlayer::OpenDefaultStreams(), CFileItemList::StackFolders(), and TEST_P().
IsStreamedFilesystem()
bool KODI::NETWORK::IsStreamedFilesystem (const CFileItem & item)
Check whether an item is on a streamed filesystem.
References CFileItem::GetDynPath(), and URIUtils::IsStreamedFilesystem().
Referenced by CVideoThumbLoader::GetLocalArt(), TEST(), and TEST_P().