Kodi Documentation: PVR::CPVRSignalStatus Class Reference
PVR::CPVRSignalStatus Class Reference
#include <PVRSignalStatus.h>
Public Member Functions
CPVRSignalStatus ()=default
CPVRSignalStatus (const std::string &adapterName, const std::string &adapterStatus)
CPVRSignalStatus (const PVR_SIGNAL_STATUS &status)
virtual ~CPVRSignalStatus ()=default
int Signal () const
int SNR () const
long UNC () const
long BER () const
const std::string & AdapterName () const
const std::string & AdapterStatus () const
const std::string & ServiceName () const
const std::string & ProviderName () const
const std::string & MuxName () const
Private Attributes
PVR_SIGNAL_STATUS m_status {}
std::string m_adapterName
std::string m_adapterStatus
std::string m_serviceName
std::string m_providerName
std::string m_muxName
Constructor & Destructor Documentation
CPVRSignalStatus() [1/3]
PVR::CPVRSignalStatus::CPVRSignalStatus () default
CPVRSignalStatus() [2/3]
PVR::CPVRSignalStatus::CPVRSignalStatus (const std::string & adapterName, const std::string & adapterStatus) inline
CPVRSignalStatus() [3/3]
PVR::CPVRSignalStatus::CPVRSignalStatus (const PVR_SIGNAL_STATUS & status) inline explicit
~CPVRSignalStatus()
virtual PVR::CPVRSignalStatus::~CPVRSignalStatus () virtual default
Member Function Documentation
AdapterName()
const std::string & PVR::CPVRSignalStatus::AdapterName () const inline
References m_adapterName.
Referenced by PVR::CPVRGUIInfo::CharInfoFrontendName().
AdapterStatus()
const std::string & PVR::CPVRSignalStatus::AdapterStatus () const inline
References m_adapterStatus.
Referenced by PVR::CPVRGUIInfo::CharInfoFrontendStatus().
BER()
long PVR::CPVRSignalStatus::BER () const inline
References PVR_SIGNAL_STATUS::iBER, and m_status.
Referenced by PVR::CPVRGUIInfo::CharInfoBER().
MuxName()
const std::string & PVR::CPVRSignalStatus::MuxName () const inline
References m_muxName.
Referenced by PVR::CPVRGUIInfo::CharInfoMux().
ProviderName()
const std::string & PVR::CPVRSignalStatus::ProviderName () const inline
References m_providerName.
Referenced by PVR::CPVRGUIInfo::CharInfoProvider().
ServiceName()
const std::string & PVR::CPVRSignalStatus::ServiceName () const inline
References m_serviceName.
Referenced by PVR::CPVRGUIInfo::CharInfoService().
Signal()
int PVR::CPVRSignalStatus::Signal () const inline
References PVR_SIGNAL_STATUS::iSignal, and m_status.
Referenced by PVR::CPVRGUIInfo::CharInfoSignal(), and PVR::CPVRGUIInfo::GetPVRInt().
SNR()
int PVR::CPVRSignalStatus::SNR () const inline
References PVR_SIGNAL_STATUS::iSNR, and m_status.
Referenced by PVR::CPVRGUIInfo::CharInfoSNR(), and PVR::CPVRGUIInfo::GetPVRInt().
UNC()
long PVR::CPVRSignalStatus::UNC () const inline
References PVR_SIGNAL_STATUS::iUNC, and m_status.
Referenced by PVR::CPVRGUIInfo::CharInfoUNC().
Member Data Documentation
m_adapterName
std::string PVR::CPVRSignalStatus::m_adapterName private
Referenced by AdapterName().
m_adapterStatus
std::string PVR::CPVRSignalStatus::m_adapterStatus private
Referenced by AdapterStatus().
m_muxName
std::string PVR::CPVRSignalStatus::m_muxName private
Referenced by MuxName().
m_providerName
std::string PVR::CPVRSignalStatus::m_providerName private
Referenced by ProviderName().
m_serviceName
std::string PVR::CPVRSignalStatus::m_serviceName private
Referenced by ServiceName().
m_status
PVR_SIGNAL_STATUS PVR::CPVRSignalStatus::m_status {} private
Referenced by BER(), Signal(), SNR(), and UNC().
The documentation for this class was generated from the following file:
PVRSignalStatus.h