Kodi Documentation: VAAPI::COutput Class Reference
VAAPI::COutput Class Reference
#include <VAAPI.h>
Public Member Functions
COutput (CDecoder &decoder, CEvent *inMsgEvent)
~COutput () override
void Start ()
void Dispose ()
Public Attributes
COutputControlProtocol m_controlPort
COutputDataProtocol m_dataPort
Protected Member Functions
void OnStartup () override
void OnExit () override
void Process () override
void StateMachine (int signal, Protocol *port, Message *msg)
bool HasWork ()
bool PreferPP ()
void InitCycle ()
CVaapiRenderPicture * ProcessPicture (CVaapiProcessedPicture &pic)
void QueueReturnPicture (CVaapiRenderPicture *pic)
void ProcessReturnPicture (CVaapiRenderPicture *pic)
void ProcessReturnProcPicture (int id)
void ProcessSyncPicture ()
void ReleaseProcessedPicture (CVaapiProcessedPicture &pic)
bool Init ()
bool Uninit ()
void Flush ()
void EnsureBufferPool ()
void ReleaseBufferPool (bool precleanup=false)
void ReadyForDisposal (CPostproc *pp)
Protected Attributes
CEvent m_outMsgEvent
CEvent * m_inMsgEvent
int m_state
bool m_bStateMachineSelfTrigger
CDecoder & m_vaapi
std::chrono::milliseconds m_extTimeout = std::chrono::milliseconds::zero()
bool m_seenInterlaced
Whether at least one interlaced frame was encountered in the video stream (indicating that more interlaced frames could potentially follow)
CVaapiConfig m_config
std::shared_ptr< CVaapiBufferPool > m_bufferPool
CVaapiDecodedPicture m_currentPicture
CPostproc * m_pp
std::list< std::shared_ptr< CPostproc > > m_discardedPostprocs
SDiMethods m_diMethods
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
COutput()
COutput::COutput (CDecoder & decoder, CEvent * inMsgEvent)
References m_inMsgEvent.
~COutput()
COutput::~COutput () override
References Dispose().
Member Function Documentation
Dispose()
void COutput::Dispose ()
References CServiceBroker::GetWinSystem(), CThread::m_bStop, m_controlPort, m_dataPort, m_outMsgEvent, Actor::Protocol::Purge(), CEvent::Set(), and CThread::StopThread().
Referenced by VAAPI::CDecoder::ConfigVAAPI(), VAAPI::CDecoder::FiniVAAPIOutput(), and ~COutput().
EnsureBufferPool()
void COutput::EnsureBufferPool () protected
References m_bufferPool.
Referenced by StateMachine().
Flush()
void COutput::Flush () protected
References VAAPI::CVideoSurfaces::ClearRender(), Actor::Message::data, VAAPI::CPostproc::Flush(), Actor::CPayloadWrap< Payload >::GetPlayload(), m_bufferPool, m_config, m_dataPort, m_pp, VAAPI::COutputDataProtocol::NEWFRAME, Actor::Message::payloadObj, VAAPI::COutputDataProtocol::PICTURE, QueueReturnPicture(), Actor::Protocol::ReceiveInMessage(), Actor::Protocol::ReceiveOutMessage(), CVideoBuffer::Release(), Actor::Message::Release(), ReleaseProcessedPicture(), VAAPI::COutputDataProtocol::RETURNPIC, Actor::Message::signal, VAAPI::CVaapiDecodedPicture::videoSurface, and VAAPI::CVaapiConfig::videoSurfaces.
Referenced by Process(), and StateMachine().
HasWork()
bool COutput::HasWork () protected
References m_bufferPool, m_pp, and VAAPI::CPostproc::WantsPic().
Referenced by StateMachine().
Init()
bool COutput::Init () protected
References VAAPI::SDiMethods::diMethods, m_config, m_diMethods, m_pp, m_seenInterlaced, VAAPI::SDiMethods::numDiMethods, VAAPI::CPostproc::PreInit(), VAAPI::CVaapiConfig::processInfo, CProcessInfo::SetDeinterlacingMethodDefault(), CProcessInfo::UpdateDeinterlacingMethods(), and VS_INTERLACEMETHOD_VAAPI_BOB.
Referenced by StateMachine().
InitCycle()
void COutput::InitCycle () protected
References VAAPI::CPostproc::Discard(), VAAPI::CVaapiConfig::driverIsMesa, DVD_CODEC_CTRL_NO_POSTPROC, VAAPI::CVaapiDecodedPicture::DVDPic, DVP_FLAG_INTERLACED, VAAPI::CVaapiBufferStats::GetParams(), CServiceBroker::GetSettingsComponent(), CProcessInfo::GetVideoSettings(), VideoPicture::iFlags, VAAPI::CPostproc::Init(), CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, m_config, m_currentPicture, m_discardedPostprocs, CVideoSettings::m_InterlaceMethod, m_pp, m_seenInterlaced, VAAPI::CPostproc::PreInit(), VAAPI::CVaapiConfig::processInfo, ReadyForDisposal(), VAAPI::CVaapiBufferStats::SetCanSkipDeint(), SETTING_VIDEOPLAYER_PREFERVAAPIRENDER, CProcessInfo::SetVideoDeintMethod(), VAAPI::CVaapiBufferStats::SetVpp(), VAAPI::CVaapiConfig::stats, CProcessInfo::Supports(), VAAPI::CPostproc::UpdateDeintMethod(), VAAPI::CVaapiConfig::vidHeight, VAAPI::CVaapiConfig::vidWidth, VS_INTERLACEMETHOD_DEINTERLACE, VS_INTERLACEMETHOD_NONE, VS_INTERLACEMETHOD_RENDER_BOB, and VS_INTERLACEMETHOD_VAAPI_BOB.
Referenced by StateMachine().
OnExit()
void COutput::OnExit () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
OnStartup()
void COutput::OnStartup () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
PreferPP()
bool COutput::PreferPP () protected
References VAAPI::CPostproc::DoesSync(), m_bufferPool, m_pp, and VAAPI::CPostproc::WantsPic().
Referenced by StateMachine().
Process()
void COutput::Process (void) override protected virtual
Reimplemented from CThread.
References Flush(), Actor::Protocol::GetMessage(), m_bStateMachineSelfTrigger, CThread::m_bStop, m_controlPort, m_dataPort, m_extTimeout, m_outMsgEvent, m_state, O_TOP_UNCONFIGURED, Actor::Protocol::ReceiveOutMessage(), Actor::Message::Release(), Actor::Message::signal, StateMachine(), VAAPI::COutputControlProtocol::TIMEOUT, Uninit(), and CEvent::Wait().
ProcessPicture()
CVaapiRenderPicture * COutput::ProcessPicture (CVaapiProcessedPicture & pic) protected
References VAAPI::CVaapiRenderPicture::avFrame, VAAPI::CPostproc::ClearRef(), VAAPI::CVaapiConfig::dpy, VideoPicture::dts, DVD_NOPTS_VALUE, VAAPI::CVaapiProcessedPicture::DVDPic, VAAPI::CVaapiRenderPicture::DVDPic, VAAPI::CVaapiProcessedPicture::frame, VAAPI::CVaapiProcessedPicture::id, VideoPicture::iHeight, VideoPicture::iWidth, CLog::Log(), LOGERROR, m_bufferPool, m_config, VAAPI::CVaapiRenderPicture::procPic, CVideoBuffer::Release(), VideoPicture::SetParams(), VAAPI::CVaapiProcessedPicture::source, VAAPI::CPostproc::UseVideoSurface(), VAAPI::CVaapiRenderPicture::vadsp, VAAPI::CVaapiRenderPicture::valid, VAAPI::CVaapiProcessedPicture::videoSurface, VAAPI::CVaapiConfig::vidHeight, and VAAPI::CVaapiConfig::vidWidth.
Referenced by StateMachine().
ProcessReturnPicture()
void COutput::ProcessReturnPicture (CVaapiRenderPicture * pic) protected
References VAAPI::CVaapiRenderPicture::avFrame, VAAPI::CVaapiProcessedPicture::id, ProcessReturnProcPicture(), VAAPI::CVaapiRenderPicture::procPic, and VAAPI::CVaapiRenderPicture::valid.
Referenced by ProcessSyncPicture().
ProcessReturnProcPicture()
void COutput::ProcessReturnProcPicture (int id) protected
References m_bufferPool, and ReleaseProcessedPicture().
Referenced by ProcessReturnPicture(), and StateMachine().
ProcessSyncPicture()
void COutput::ProcessSyncPicture () protected
References m_bufferPool, and ProcessReturnPicture().
Referenced by QueueReturnPicture(), ReleaseBufferPool(), StateMachine(), and Uninit().
QueueReturnPicture()
void COutput::QueueReturnPicture (CVaapiRenderPicture * pic) protected
References m_bufferPool, and ProcessSyncPicture().
Referenced by Flush(), and StateMachine().
ReadyForDisposal()
void COutput::ReadyForDisposal (CPostproc * pp) protected
References m_discardedPostprocs.
Referenced by InitCycle(), and Uninit().
ReleaseBufferPool()
void COutput::ReleaseBufferPool (bool precleanup = false) protected
References VAAPI::CVideoSurfaces::ClearRender(), m_bufferPool, m_config, ProcessSyncPicture(), ReleaseProcessedPicture(), and VAAPI::CVaapiConfig::videoSurfaces.
Referenced by StateMachine(), and Uninit().
ReleaseProcessedPicture()
void COutput::ReleaseProcessedPicture (CVaapiProcessedPicture & pic) protected
References VAAPI::CPostproc::ClearRef(), and VAAPI::CVaapiProcessedPicture::source.
Referenced by Flush(), ProcessReturnProcPicture(), and ReleaseBufferPool().
Start()
void COutput::Start ()
References CThread::Create().
Referenced by VAAPI::CDecoder::ConfigVAAPI().
StateMachine()
void COutput::StateMachine (int signal, Protocol * port, Message * msg) protected
References VAAPI::COutputControlProtocol::ACC, VAAPI::CPostproc::AddPicture(), Actor::Message::data, data(), VAAPI::CVaapiBufferStats::DecDecoded(), VAAPI::CVaapiBufferStats::DecProcessed(), EnsureBufferPool(), VAAPI::CPostproc::Filter(), VAAPI::COutputControlProtocol::FLUSH, Flush(), Actor::CPayloadWrap< Payload >::GetPlayload(), HasWork(), id, VAAPI::CVaapiBufferStats::IncProcessed(), VAAPI::CVaapiBufferStats::IncRender(), VAAPI::COutputControlProtocol::INIT, Init(), InitCycle(), CLog::Log(), LOGERROR, LOGWARNING, m_bufferPool, m_config, m_controlPort, m_currentPicture, m_dataPort, m_extTimeout, m_pp, m_state, VAAPI::COutputDataProtocol::NEWFRAME, O_TOP, O_TOP_CONFIGURED, O_TOP_CONFIGURED_IDLE, O_TOP_CONFIGURED_OUTPUT, O_TOP_CONFIGURED_STEP1, O_TOP_CONFIGURED_STEP2, O_TOP_CONFIGURED_WORK, O_TOP_ERROR, O_TOP_UNCONFIGURED, Actor::Message::payloadObj, VAAPI::COutputDataProtocol::PICTURE, Actor::Protocol::portName, VAAPI::COutputControlProtocol::PRECLEANUP, PreferPP(), ProcessPicture(), ProcessReturnProcPicture(), ProcessSyncPicture(), QueueReturnPicture(), ReleaseBufferPool(), Actor::Message::Reply(), VAAPI::COutputDataProtocol::RETURNPIC, VAAPI::COutputDataProtocol::RETURNPROCPIC, Actor::Protocol::SendInMessage(), VAAPI::CVaapiConfig::stats, VAAPI::COutputControlProtocol::STATS, VAAPI::COutputControlProtocol::TIMEOUT, and VAAPI_OUTPUT_parentStates.
Referenced by Process().
Uninit()
bool COutput::Uninit () protected
References VAAPI::CPostproc::Discard(), CLog::Log(), LOGERROR, m_discardedPostprocs, m_pp, ProcessSyncPicture(), ReadyForDisposal(), and ReleaseBufferPool().
Referenced by Process().
Member Data Documentation
m_bStateMachineSelfTrigger
bool VAAPI::COutput::m_bStateMachineSelfTrigger protected
Referenced by Process().
m_bufferPool
std::shared_ptr<CVaapiBufferPool> VAAPI::COutput::m_bufferPool protected
Referenced by EnsureBufferPool(), Flush(), HasWork(), PreferPP(), ProcessPicture(), ProcessReturnProcPicture(), ProcessSyncPicture(), QueueReturnPicture(), ReleaseBufferPool(), and StateMachine().
m_config
CVaapiConfig VAAPI::COutput::m_config protected
Referenced by Flush(), Init(), InitCycle(), ProcessPicture(), ReleaseBufferPool(), and StateMachine().
m_controlPort
COutputControlProtocol VAAPI::COutput::m_controlPort
Referenced by VAAPI::CDecoder::ConfigVAAPI(), VAAPI::CDecoder::Decode(), Dispose(), Process(), VAAPI::CDecoder::Release(), VAAPI::CDecoder::Reset(), and StateMachine().
m_currentPicture
CVaapiDecodedPicture VAAPI::COutput::m_currentPicture protected
Referenced by InitCycle(), and StateMachine().
m_dataPort
COutputDataProtocol VAAPI::COutput::m_dataPort
Referenced by VAAPI::CDecoder::Decode(), Dispose(), Flush(), Process(), VAAPI::CDecoder::ReturnRenderPicture(), and StateMachine().
m_diMethods
SDiMethods VAAPI::COutput::m_diMethods protected
Referenced by Init().
m_discardedPostprocs
std::list<std::shared_ptr<CPostproc> > VAAPI::COutput::m_discardedPostprocs protected
Referenced by InitCycle(), ReadyForDisposal(), and Uninit().
m_extTimeout
std::chrono::milliseconds VAAPI::COutput::m_extTimeout = std::chrono::milliseconds::zero() protected
Referenced by Process(), and StateMachine().
m_inMsgEvent
CEvent* VAAPI::COutput::m_inMsgEvent protected
Referenced by COutput().
m_outMsgEvent
CEvent VAAPI::COutput::m_outMsgEvent protected
Referenced by Dispose(), and Process().
m_pp
CPostproc* VAAPI::COutput::m_pp protected
Referenced by Flush(), HasWork(), Init(), InitCycle(), PreferPP(), StateMachine(), and Uninit().
m_seenInterlaced
bool VAAPI::COutput::m_seenInterlaced protected
Whether at least one interlaced frame was encountered in the video stream (indicating that more interlaced frames could potentially follow)
Referenced by Init(), and InitCycle().
m_state
int VAAPI::COutput::m_state protected
Referenced by Process(), and StateMachine().
m_vaapi
CDecoder& VAAPI::COutput::m_vaapi protected
The documentation for this class was generated from the following files:
VAAPI.h
VAAPI.cpp