Kodi Documentation: UPNP::CUPnPServer Class Reference
UPNP::CUPnPServer Class Reference
#include <UPnPServer.h>
Public Member Functions
CUPnPServer (const char *friendly_name, const char *uuid=NULL, int port=0)
~CUPnPServer () override
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
NPT_Result OnBrowseMetadata (PLT_ActionReference &action, const char *object_id, const char *filter, NPT_UInt32 starting_index, NPT_UInt32 requested_count, const char *sort_criteria, const PLT_HttpRequestContext &context) override
NPT_Result OnBrowseDirectChildren (PLT_ActionReference &action, const char *object_id, const char *filter, NPT_UInt32 starting_index, NPT_UInt32 requested_count, const char *sort_criteria, const PLT_HttpRequestContext &context) override
NPT_Result OnSearchContainer (PLT_ActionReference &action, const char *container_id, const char *search_criteria, const char *filter, NPT_UInt32 starting_index, NPT_UInt32 requested_count, const char *sort_criteria, const PLT_HttpRequestContext &context) override
NPT_Result OnUpdateObject (PLT_ActionReference &action, const char *object_id, NPT_Map< NPT_String, NPT_String > &current_vals, NPT_Map< NPT_String, NPT_String > &new_vals, const PLT_HttpRequestContext &context) override
NPT_Result ServeFile (const NPT_HttpRequest &request, const NPT_HttpRequestContext &context, NPT_HttpResponse &response, const NPT_String &file_path) override
NPT_Result ProcessGetSCPD (PLT_Service *service, NPT_HttpRequest &request, const NPT_HttpRequestContext &context, NPT_HttpResponse &response) override
NPT_Result SetupServices () override
NPT_Result SetupIcons () override
NPT_String BuildSafeResourceUri (const NPT_HttpUrl &rooturi, const char *host, const char *file_path)
void AddSafeResourceUri (PLT_MediaObject *object, const NPT_HttpUrl &rooturi, const NPT_List< NPT_IpAddress > &ips, const char *file_path, const NPT_String &info)
NPT_Result AddSubtitleUriForSecResponse (const NPT_String &movie_md5, const NPT_String &subtitle_uri)
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Static Public Attributes
static NPT_UInt32 m_MaxReturnedItems = 0
Private Member Functions
void OnScanCompleted (int type)
void UpdateContainer (const std::string &id)
void PropagateUpdates ()
PLT_MediaObject * Build (const std::shared_ptr< CFileItem > &item, bool with_count, const PLT_HttpRequestContext &context, NPT_Reference< CThumbLoader > &thumbLoader, const char *parent_id=NULL)
NPT_Result BuildResponse (PLT_ActionReference &action, CFileItemList &items, const char *filter, NPT_UInt32 starting_index, NPT_UInt32 requested_count, const char *sort_criteria, const PLT_HttpRequestContext &context, const char *parent_id)
Static Private Member Functions
static void DefaultSortItems (CFileItemList &items)
static NPT_String GetParentFolder (const NPT_String &file_path)
static int GetRequiredVideoDbDetails (const NPT_String &filter)
Private Attributes
NPT_Mutex m_CacheMutex
NPT_Mutex m_FileMutex
NPT_Map< NPT_String, NPT_String > m_FileMap
std::map< std::string, std::pair< bool, unsigned long > > m_UpdateIDs
bool m_scanning
Logger m_logger
Constructor & Destructor Documentation
CUPnPServer()
UPNP::CUPnPServer::CUPnPServer (const char * friendly_name, const char * uuid = NULL, int port = 0)
~CUPnPServer()
UPNP::CUPnPServer::~CUPnPServer () override
References CServiceBroker::GetAnnouncementManager().
Member Function Documentation
AddSafeResourceUri()
void UPNP::CUPnPServer::AddSafeResourceUri (PLT_MediaObject * object, const NPT_HttpUrl & rooturi, const NPT_List< NPT_IpAddress > & ips, const char * file_path, const NPT_String & info) inline
References BuildSafeResourceUri().
Referenced by UPNP::BuildObject().
AddSubtitleUriForSecResponse()
NPT_Result UPNP::CUPnPServer::AddSubtitleUriForSecResponse (const NPT_String & movie_md5, const NPT_String & subtitle_uri)
References m_FileMap, and m_FileMutex.
Referenced by UPNP::BuildObject().
Announce()
void UPNP::CUPnPServer::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References ANNOUNCEMENT::CAnnouncementManager::ANNOUNCEMENT_SENDER, ANNOUNCEMENT::AudioLibrary, data(), CMusicDatabase::GetAlbumFromSong(), CVideoDatabase::GetSeasonForEpisode(), CVideoDatabase::GetTvShowForEpisode(), CAlbum::idAlbum, m_scanning, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSong, MediaTypeTvShow, OnScanCompleted(), CMusicDatabase::Open(), CVideoDatabase::Open(), UpdateContainer(), and ANNOUNCEMENT::VideoLibrary.
Build()
PLT_MediaObject * UPNP::CUPnPServer::Build (const std::shared_ptr< CFileItem > & item, bool with_count, const PLT_HttpRequestContext & context, NPT_Reference< CThumbLoader > & thumbLoader, const char * parent_id = NULL) private
References UPNP::BuildObject(), UPNP::EncodeObjectId(), XFILE::CDirectory::Exists(), CMusicDatabase::GetAlbum(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetAlbumId(), CMusicDatabase::GetArtist(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetArtistId(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetEpisodeId(), CVideoDatabase::GetEpisodeInfo(), XFILE::CMusicDatabaseDirectory::GetLabel(), XFILE::CVideoDatabaseDirectory::GetLabel(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMovieId(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMusicVideoInfo(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMVideoId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSeason(), CVideoDatabase::GetSeasonId(), CVideoDatabase::GetSeasonInfo(), CMusicDatabase::GetSong(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetSongId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetTvShowId(), CVideoDatabase::GetTvShowInfo(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetVideoVersionId(), KODI::MUSIC::IsAudio(), KODI::PLAYLIST::IsPlayList(), KODI::PLAYLIST::IsSmartPlayList(), label, m_logger, MediaTypeSeason, MediaTypeSong, MediaTypeTvShow, CMusicDatabase::Open(), CVideoDatabase::Open(), and UPNP::UPnPContentDirectory.
Referenced by BuildResponse(), and OnBrowseMetadata().
BuildResponse()
NPT_Result UPNP::CUPnPServer::BuildResponse (PLT_ActionReference & action, CFileItemList & items, const char * filter, NPT_UInt32 starting_index, NPT_UInt32 requested_count, const char * sort_criteria, const PLT_HttpRequestContext & context, const char * parent_id) private
References Build(), CFileItem::GetPath(), URIUtils::IsMusicDb(), URIUtils::IsVideoDb(), m_logger, m_MaxReturnedItems, CFileItemList::Remove(), and CFileItemList::Size().
Referenced by OnBrowseDirectChildren(), and OnSearchContainer().
BuildSafeResourceUri()
NPT_String UPNP::CUPnPServer::BuildSafeResourceUri (const NPT_HttpUrl & rooturi, const char * host, const char * file_path)
References URIUtils::GetFileName(), CURL::GetHostName(), CURL::IsProtocol(), m_FileMap, m_FileMutex, and URIUtils::RemoveSlashAtEnd().
Referenced by AddSafeResourceUri(), UPNP::BuildObject(), and ServeFile().
DefaultSortItems()
void UPNP::CUPnPServer::DefaultSortItems (CFileItemList & items) static private
References CGUIViewState::GetSortMethod(), CGUIViewState::GetViewState(), KODI::VIDEO::IsVideoDb(), CFileItemList::Sort(), SortDescription::sortAttributes, SortDescription::sortBy, SortDescription::sortOrder, and WINDOW_VIDEO_NAV.
Referenced by OnBrowseDirectChildren().
GetParentFolder()
static NPT_String UPNP::CUPnPServer::GetParentFolder (const NPT_String & file_path) inline static private
References index().
GetRequiredVideoDbDetails()
int UPNP::CUPnPServer::GetRequiredVideoDbDetails (const NPT_String & filter) static private
References VideoDbDetailsCast, VideoDbDetailsRating, and VideoDbDetailsStream.
Referenced by OnSearchContainer().
OnBrowseDirectChildren()
NPT_Result UPNP::CUPnPServer::OnBrowseDirectChildren (PLT_ActionReference & action, const char * object_id, const char * filter, NPT_UInt32 starting_index, NPT_UInt32 requested_count, const char * sort_criteria, const PLT_HttpRequestContext & context) override
References CFileItemList::Add(), BuildResponse(), CFileItemList::CacheToDiscAlways(), CFileItemList::CacheToDiscIfSlow(), UPNP::DecodeObjectId(), DefaultSortItems(), XFILE::DIR_FLAG_DEFAULTS, end(), g_localizeStrings, CLocalizeStrings::Get(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), CFileExtensionProvider::GetMusicExtensions(), CFileItem::GetPath(), CFileExtensionProvider::GetPictureExtensions(), CFileExtensionProvider::GetVideoExtensions(), CVideoDatabase::HasContent(), CFileItemList::Load(), m_CacheMutex, m_logger, MUSICVIDEOS, UPNP::ObjectIDValidate(), CVideoDatabase::Open(), CFileItemList::Save(), CFileItem::SetPath(), CFileItemList::Sort(), SortByLabel, SortOrderAscending, and UPNP::TranslateWMPObjectId().
Referenced by OnSearchContainer().
OnBrowseMetadata()
NPT_Result UPNP::CUPnPServer::OnBrowseMetadata (PLT_ActionReference & action, const char * object_id, const char * filter, NPT_UInt32 starting_index, NPT_UInt32 requested_count, const char * sort_criteria, const PLT_HttpRequestContext & context) override
Todo:
We need to keep track of the overall SystemUpdateID of the CDS
References Build(), UPNP::DecodeObjectId(), UPNP::EncodeObjectId(), URIUtils::GetParentPath(), KODI::MUSIC::IsMusicDb(), URIUtils::IsMusicDb(), KODI::VIDEO::IsVideoDb(), URIUtils::IsVideoDb(), m_logger, UPNP::ObjectIDValidate(), and UPNP::TranslateWMPObjectId().
OnScanCompleted()
void UPNP::CUPnPServer::OnScanCompleted (int type) private
References UPNP::audio_containers, ANNOUNCEMENT::AudioLibrary, m_scanning, PropagateUpdates(), UpdateContainer(), UPNP::video_containers, and ANNOUNCEMENT::VideoLibrary.
Referenced by Announce(), and SetupServices().
OnSearchContainer()
NPT_Result UPNP::CUPnPServer::OnSearchContainer (PLT_ActionReference & action, const char * container_id, const char * search_criteria, const char * filter, NPT_UInt32 starting_index, NPT_UInt32 requested_count, const char * sort_criteria, const PLT_HttpRequestContext & context) override
References CFileItemList::Append(), BuildResponse(), CFileItemList::Clear(), UPNP::DecodeObjectId(), UPNP::FindSubCriteria(), CMusicDatabase::GetAlbumByName(), CMusicDatabase::GetArtistByName(), CVideoDatabase::GetEpisodesByWhere(), CMusicDatabase::GetGenreByName(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideosByWhere(), GetRequiredVideoDbDetails(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetTvShowsByWhere(), m_logger, OnBrowseDirectChildren(), CMusicDatabase::Open(), CVideoDatabase::Open(), and CFileItem::SetPath().
OnUpdateObject()
NPT_Result UPNP::CUPnPServer::OnUpdateObject (PLT_ActionReference & action, const char * object_id, NPT_Map< NPT_String, NPT_String > & current_vals, NPT_Map< NPT_String, NPT_String > & new_vals, const PLT_HttpRequestContext & context) override
TODO: we should find a way to avoid obtaining the artwork just to
Todo:
implement this
References CVideoDatabase::AddBookMarkToFile(), CVideoDatabase::ClearBookMarksOfFile(), data(), UPNP::DecodeObjectId(), CUtil::DeleteMusicDatabaseDirectoryCache(), CUtil::DeleteVideoDatabaseDirectoryCache(), EPISODES, err(), CVideoThumbLoader::FillLibraryArt(), CServiceBroker::GetAnnouncementManager(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetEpisodeId(), CVideoDatabase::GetFilePathById(), CServiceBroker::GetGUI(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMovieId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMVideoId(), CFileItem::GetVideoInfoTag(), CGUIComponent::GetWindowManager(), GUI_MSG_FLAG_UPDATE_LIST, GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_ITEM, KODI::MUSIC::IsMusicDb(), KODI::VIDEO::IsVideoDb(), CVideoDatabase::LoadVideoInfo(), CVideoInfoTag::m_iDbId, m_logger, CVideoInfoTag::m_type, MOVIES, MUSICVIDEOS, CVideoDatabase::Open(), CBookmark::playerState, CBookmark::RESUME, CFileItem::SetFromVideoInfoTag(), CDateTime::SetFromW3CDateTime(), CFileItem::SetPath(), CVideoDatabase::SetPlayCount(), CBookmark::timeInSeconds, CBookmark::totalTimeInSeconds, and ANNOUNCEMENT::VideoLibrary.
ProcessGetSCPD()
NPT_Result UPNP::CUPnPServer::ProcessGetSCPD (PLT_Service * service, NPT_HttpRequest & request, const NPT_HttpRequestContext & context, NPT_HttpResponse & response) override
PropagateUpdates()
void UPNP::CUPnPServer::PropagateUpdates () private
References UPNP::EncodeObjectId(), CServiceBroker::GetSettingsComponent(), m_logger, m_scanning, m_UpdateIDs, and CSettings::SETTING_SERVICES_UPNPANNOUNCE.
Referenced by OnScanCompleted(), and UpdateContainer().
ServeFile()
NPT_Result UPNP::CUPnPServer::ServeFile (const NPT_HttpRequest & request, const NPT_HttpRequestContext & context, NPT_HttpResponse & response, const NPT_String & file_path) override
References BuildSafeResourceUri(), URIUtils::GetFileName(), URIUtils::IsURL(), m_FileMap, m_FileMutex, m_logger, and IMAGE_FILES::ToCacheKey().
SetupIcons()
NPT_Result UPNP::CUPnPServer::SetupIcons () override
References CSpecialProtocol::TranslatePath().
SetupServices()
NPT_Result UPNP::CUPnPServer::SetupServices () override
References ANNOUNCEMENT::AudioLibrary, CServiceBroker::GetAnnouncementManager(), m_scanning, OnScanCompleted(), and ANNOUNCEMENT::VideoLibrary.
UpdateContainer()
void UPNP::CUPnPServer::UpdateContainer (const std::string & id) private
References id, m_UpdateIDs, and PropagateUpdates().
Referenced by Announce(), and OnScanCompleted().
Member Data Documentation
m_CacheMutex
NPT_Mutex UPNP::CUPnPServer::m_CacheMutex private
Referenced by OnBrowseDirectChildren().
m_FileMap
NPT_Map<NPT_String, NPT_String> UPNP::CUPnPServer::m_FileMap private
Referenced by AddSubtitleUriForSecResponse(), BuildSafeResourceUri(), and ServeFile().
m_FileMutex
NPT_Mutex UPNP::CUPnPServer::m_FileMutex private
Referenced by AddSubtitleUriForSecResponse(), BuildSafeResourceUri(), and ServeFile().
m_logger
Logger UPNP::CUPnPServer::m_logger private
Referenced by Build(), BuildResponse(), OnBrowseDirectChildren(), OnBrowseMetadata(), OnSearchContainer(), OnUpdateObject(), PropagateUpdates(), and ServeFile().
m_MaxReturnedItems
NPT_UInt32 UPNP::CUPnPServer::m_MaxReturnedItems = 0 static
Referenced by BuildResponse(), and UPNP::CUPnP::StartServer().
m_scanning
bool UPNP::CUPnPServer::m_scanning private
Referenced by Announce(), OnScanCompleted(), PropagateUpdates(), and SetupServices().
m_UpdateIDs
std::map<std::string, std::pair<bool, unsigned long> > UPNP::CUPnPServer::m_UpdateIDs private
Referenced by PropagateUpdates(), and UpdateContainer().
The documentation for this class was generated from the following files:
UPnPServer.h
UPnPServer.cpp