Kodi Documentation: CApplicationVolumeHandling Class Reference
CApplicationVolumeHandling Class Reference
Class handling application support for audio volume management.
#include <ApplicationVolumeHandling.h>
Classes
struct ReplayGainSettings
Public Member Functions
float GetVolumePercent () const
float GetVolumeRatio () const
bool IsMuted () const
void SetVolume (float iValue, bool isPercentage=true)
void SetMute (bool mute)
void ToggleMute (void)
const ReplayGainSettings & GetReplayGainSettings () const
bool Load (const TiXmlNode *settings)
bool Save (TiXmlNode *settings) const
bool OnSettingChanged (const CSetting &setting)
Public Member Functions inherited from IApplicationComponent
virtual ~IApplicationComponent ()=default
Static Public Attributes
static constexpr float VOLUME_MINIMUM = 0.0f
static constexpr float VOLUME_MAXIMUM = 1.0f
static constexpr float VOLUME_DYNAMIC_RANGE = 90.0f
Protected Member Functions
bool IsMutedInternal () const
void ShowVolumeBar (const CAction *action=nullptr)
void CacheReplayGainSettings (const CSettings &settings)
void Mute ()
void UnMute ()
void SetHardwareVolume (float hardwareVolume)
void VolumeChanged ()
Protected Attributes
bool m_muted = false
float m_volumeLevel = VOLUME_MAXIMUM
ReplayGainSettings m_replayGainSettings
Friends
class CApplication
Detailed Description
Class handling application support for audio volume management.
Member Function Documentation
CacheReplayGainSettings()
void CApplicationVolumeHandling::CacheReplayGainSettings (const CSettings & settings) protected
References CApplicationVolumeHandling::ReplayGainSettings::bAvoidClipping, CSettings::GetBool(), CSettingsBase::GetInt(), CApplicationVolumeHandling::ReplayGainSettings::iNoGainPreAmp, CApplicationVolumeHandling::ReplayGainSettings::iPreAmp, CApplicationVolumeHandling::ReplayGainSettings::iType, m_replayGainSettings, CSettings::SETTING_MUSICPLAYER_REPLAYGAINAVOIDCLIPPING, CSettings::SETTING_MUSICPLAYER_REPLAYGAINNOGAINPREAMP, CSettings::SETTING_MUSICPLAYER_REPLAYGAINPREAMP, and CSettings::SETTING_MUSICPLAYER_REPLAYGAINTYPE.
GetReplayGainSettings()
const ReplayGainSettings & CApplicationVolumeHandling::GetReplayGainSettings () const inline
References m_replayGainSettings.
Referenced by CAudioDecoder::GetReplayGain().
GetVolumePercent()
float CApplicationVolumeHandling::GetVolumePercent () const
References m_volumeLevel.
Referenced by CDVDRadioRDSData::DecodeTA_TP(), KODI::GAME::CDialogGameVolume::GetVolumePercent(), CAirPlayServer::CTCPClient::ProcessRequest(), SetVolume(), and VolumeChanged().
GetVolumeRatio()
float CApplicationVolumeHandling::GetVolumeRatio () const
References m_volumeLevel.
Referenced by CGUIDialogAudioSettings::FrameMove(), and CGUIDialogAudioSettings::InitializeSettings().
IsMuted()
bool CApplicationVolumeHandling::IsMuted () const
References CServiceBroker::GetActiveAE(), CServiceBroker::GetPeripherals(), IsMuted(), and IAE::IsMuted().
Referenced by IsMuted().
IsMutedInternal()
bool CApplicationVolumeHandling::IsMutedInternal () const inline protected
References m_muted.
Load()
bool CApplicationVolumeHandling::Load (const TiXmlNode * settings)
References XMLUtils::GetBoolean(), XMLUtils::GetFloat(), m_muted, m_volumeLevel, VOLUME_MAXIMUM, and VOLUME_MINIMUM.
Referenced by CApplicationSettingsHandling::Load().
Mute()
void CApplicationVolumeHandling::Mute () protected
References CServiceBroker::GetActiveAE(), CServiceBroker::GetPeripherals(), m_muted, Mute(), IAE::SetMute(), and VolumeChanged().
Referenced by Mute(), and ToggleMute().
OnSettingChanged()
bool CApplicationVolumeHandling::OnSettingChanged (const CSetting & setting)
References CApplicationVolumeHandling::ReplayGainSettings::bAvoidClipping, ISetting::GetId(), CSettingBool::GetValue(), CSettingInt::GetValue(), GetValue(), CApplicationVolumeHandling::ReplayGainSettings::iNoGainPreAmp, CApplicationVolumeHandling::ReplayGainSettings::iPreAmp, CApplicationVolumeHandling::ReplayGainSettings::iType, m_replayGainSettings, CSettings::SETTING_MUSICPLAYER_REPLAYGAINAVOIDCLIPPING, CSettings::SETTING_MUSICPLAYER_REPLAYGAINNOGAINPREAMP, CSettings::SETTING_MUSICPLAYER_REPLAYGAINPREAMP, and CSettings::SETTING_MUSICPLAYER_REPLAYGAINTYPE.
Save()
bool CApplicationVolumeHandling::Save (TiXmlNode * settings) const
References m_muted, m_volumeLevel, XMLUtils::SetBoolean(), and XMLUtils::SetFloat().
Referenced by CApplicationSettingsHandling::Save().
SetHardwareVolume()
void CApplicationVolumeHandling::SetHardwareVolume (float hardwareVolume) protected
References CServiceBroker::GetActiveAE(), m_volumeLevel, IAE::SetVolume(), VOLUME_MAXIMUM, and VOLUME_MINIMUM.
Referenced by SetVolume().
SetMute()
void CApplicationVolumeHandling::SetMute (bool mute)
References m_muted, and ToggleMute().
SetVolume()
void CApplicationVolumeHandling::SetVolume (float iValue, bool isPercentage = true)
References SetHardwareVolume(), and VolumeChanged().
Referenced by CAirTunesServer::AudioOutputFunctions::audio_set_volume(), CDVDRadioRDSData::DecodeTA_TP(), CGUIDialogAudioSettings::OnSettingChanged(), KODI::GAME::CDialogGameVolume::OnSliderChange(), CAirPlayServer::restoreVolume(), JSONRPC::CApplicationOperations::SetVolume(), and CAESinkPULSE::SetVolume().
ShowVolumeBar()
void CApplicationVolumeHandling::ShowVolumeBar (const CAction * action = nullptr) protected
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialog::Open(), and WINDOW_DIALOG_VOLUME_BAR.
ToggleMute()
void CApplicationVolumeHandling::ToggleMute (void)
References m_muted, Mute(), and UnMute().
Referenced by Mute(), and SetMute().
UnMute()
void CApplicationVolumeHandling::UnMute () protected
References CServiceBroker::GetActiveAE(), CServiceBroker::GetPeripherals(), m_muted, IAE::SetMute(), UnMute(), and VolumeChanged().
Referenced by ToggleMute(), and UnMute().
VolumeChanged()
void CApplicationVolumeHandling::VolumeChanged () protected
References ANNOUNCEMENT::Application, data(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppComponents(), GetVolumePercent(), m_muted, m_volumeLevel, CApplicationPlayer::SetVolume(), and CVariant::VariantTypeObject.
Referenced by Mute(), SetVolume(), and UnMute().
Friends And Related Symbol Documentation
CApplication
friend class CApplication friend
Member Data Documentation
m_muted
bool CApplicationVolumeHandling::m_muted = false protected
Referenced by IsMutedInternal(), Load(), Mute(), Save(), SetMute(), ToggleMute(), UnMute(), and VolumeChanged().
m_replayGainSettings
ReplayGainSettings CApplicationVolumeHandling::m_replayGainSettings protected
Referenced by CacheReplayGainSettings(), GetReplayGainSettings(), and OnSettingChanged().
m_volumeLevel
float CApplicationVolumeHandling::m_volumeLevel = VOLUME_MAXIMUM protected
Referenced by GetVolumePercent(), GetVolumeRatio(), Load(), Save(), SetHardwareVolume(), and VolumeChanged().
VOLUME_DYNAMIC_RANGE
constexpr float CApplicationVolumeHandling::VOLUME_DYNAMIC_RANGE = 90.0f static constexpr
VOLUME_MAXIMUM
constexpr float CApplicationVolumeHandling::VOLUME_MAXIMUM = 1.0f static constexpr
Referenced by CGUIDialogAudioSettings::InitializeSettings(), Load(), CApplication::OnAction(), and SetHardwareVolume().
VOLUME_MINIMUM
constexpr float CApplicationVolumeHandling::VOLUME_MINIMUM = 0.0f static constexpr
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), CGUIDialogAudioSettings::InitializeSettings(), Load(), CApplication::OnAction(), CGUIDialogVolumeBar::OnAction(), CApplication::OnMessage(), and SetHardwareVolume().
The documentation for this class was generated from the following files:
ApplicationVolumeHandling.h
ApplicationVolumeHandling.cpp