Kodi Documentation: CPythonInvoker Class Reference
CPythonInvoker Class Reference abstract
#include <PythonInvoker.h>
Classes
struct PyObjectDeleter
Public Types
typedef std::unique_ptr< PyObject, PyObjectDeleter > PyObjectPtr
Public Member Functions
CPythonInvoker (ILanguageInvocationHandler *invocationHandler)
~CPythonInvoker () override
bool Execute (const std::string &script, const std::vector< std::string > &arguments=std::vector< std::string >()) override
bool IsStopping () const override
Public Member Functions inherited from ILanguageInvoker
ILanguageInvoker (ILanguageInvocationHandler *invocationHandler)
virtual ~ILanguageInvoker ()
virtual bool Stop (bool abort=false)
void SetId (int id)
int GetId () const
const ADDON::AddonPtr & GetAddon () const
void SetAddon (const ADDON::AddonPtr &addon)
InvokerState GetState () const
bool IsActive () const
bool IsRunning () const
void Reset ()
Protected Member Functions
bool execute (const std::string &script, const std::vector< std::string > &arguments) override
virtual void executeScript (FILE *fp, const std::string &script, PyObject *moduleDict)
bool stop (bool abort) override
void onExecutionDone () override
void onExecutionFailed () override
virtual const char * getInitializationScript () const =0
virtual void onInitialization ()
virtual void onPythonModuleInitialization (void *moduleDict)
virtual void onDeinitialization ()
virtual void onSuccess ()
virtual void onAbort ()
virtual void onError (const std::string &exceptionType="", const std::string &exceptionValue="", const std::string &exceptionTraceback="")
Protected Member Functions inherited from ILanguageInvoker
virtual void AbortNotification ()
virtual void pulseGlobalEvent ()
virtual bool onExecutionInitialized ()
virtual void onExecutionFinalized ()
void setState (InvokerState state)
Protected Attributes
std::string m_sourceFile
CCriticalSection m_critical
Protected Attributes inherited from ILanguageInvoker
ADDON::AddonPtr m_addon
Private Member Functions
void getAddonModuleDeps (const ADDON::AddonPtr &addon, std::set< std::string > &paths)
bool execute (const std::string &script, std::vector< std::wstring > &arguments)
FILE * PyFile_AsFileWithMode (PyObject *py_file, const char *mode)
Private Attributes
PyThreadState * m_threadState
bool m_stop = false
CEvent m_stoppedEvent
XBMCAddon::AddonClass::Ref< XBMCAddon::Python::PythonLanguageHook > m_languageHook
bool m_systemExitThrown = false
Static Private Attributes
static CCriticalSection s_critical
Member Typedef Documentation
PyObjectPtr
typedef std::unique_ptr<PyObject, PyObjectDeleter> CPythonInvoker::PyObjectPtr
Constructor & Destructor Documentation
CPythonInvoker()
CPythonInvoker::CPythonInvoker (ILanguageInvocationHandler * invocationHandler) explicit
~CPythonInvoker()
CPythonInvoker::~CPythonInvoker () override
References ILanguageInvoker::GetId(), ILanguageInvoker::GetState(), InvokerStateExecutionDone, CLog::Log(), LOGDEBUG, m_sourceFile, ILanguageInvoker::onExecutionFinalized(), ILanguageInvoker::pulseGlobalEvent(), and ILanguageInvoker::Stop().
Member Function Documentation
execute() [1/2]
bool CPythonInvoker::execute (const std::string & script, const std::vector< std::string > & arguments) override protected virtual
Implements ILanguageInvoker.
References execute(), and g_charsetConverter.
Referenced by execute().
Execute()
bool CPythonInvoker::Execute (const std::string & script, const std::vector< std::string > & arguments = std::vector<std::string>()) override virtual
Reimplemented from ILanguageInvoker.
References ILanguageInvoker::Execute(), CFileUtils::Exists(), ILanguageInvoker::GetId(), CLog::Log(), LOGERROR, ILanguageInvoker::onExecutionInitialized(), and CSpecialProtocol::TranslatePath().
execute() [2/2]
bool CPythonInvoker::execute (const std::string & script, std::vector< std::wstring > & arguments) private
References addons, XBMCAddon::RetardedAsyncCallbackHandler::clearPendingCalls(), executeScript(), f, CServiceBroker::GetAddonMgr(), getAddonModuleDeps(), ADDON::CAddonMgr::GetAddons(), URIUtils::GetDirectory(), ILanguageInvoker::GetId(), index(), InvokerStateFailed, InvokerStateInitialized, InvokerStateRunning, InvokerStateScriptDone, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, XbmcCommons::Exception::LogThrowMessage(), LOGWARNING, ILanguageInvoker::m_addon, m_critical, m_languageHook, m_sourceFile, m_stop, m_systemExitThrown, m_threadState, onAbort(), onError(), onInitialization(), onPythonModuleInitialization(), onSuccess(), PythonBindings::PythonToCppException::ParsePythonException(), XBMCAddon::Python::PythonLanguageHook::RegisterMe(), URIUtils::RemoveSlashAtEnd(), CPyThreadState::Restore(), savestate, ADDON::SCRIPT_MODULE, ILanguageInvoker::setState(), KODI::TIME::Sleep(), and CSpecialProtocol::TranslatePath().
executeScript()
void CPythonInvoker::executeScript (FILE * fp, const std::string & script, PyObject * moduleDict) protected virtual
Reimplemented in CHTTPPythonWsgiInvoker.
Referenced by execute().
getAddonModuleDeps()
void CPythonInvoker::getAddonModuleDeps (const ADDON::AddonPtr & addon, std::set< std::string > & paths) private
References ADDON::CHOICE_YES, ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), getAddonModuleDeps(), ADDON::SCRIPT_MODULE, and CSpecialProtocol::TranslatePath().
Referenced by execute(), and getAddonModuleDeps().
getInitializationScript()
virtual const char * CPythonInvoker::getInitializationScript () const protected pure virtual
Implemented in CAddonPythonInvoker, and CHTTPPythonWsgiInvoker.
Referenced by onInitialization().
IsStopping()
bool CPythonInvoker::IsStopping () const inline override virtual
Reimplemented from ILanguageInvoker.
References ILanguageInvoker::IsStopping(), and m_stop.
onAbort()
virtual void CPythonInvoker::onAbort () inline protected virtual
Reimplemented in CHTTPPythonInvoker.
Referenced by execute().
onDeinitialization()
void CPythonInvoker::onDeinitialization () protected virtual
References XBMC_TRACE.
Referenced by onExecutionDone().
onError()
void CPythonInvoker::onError (const std::string & exceptionType = "", const std::string & exceptionValue = "", const std::string & exceptionTraceback = "") protected virtual
Reimplemented in CHTTPPythonInvoker.
References CGUIDialogKaiToast::Error, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), ILanguageInvoker::m_addon, CGUIDialogKaiToast::QueueNotification(), and WINDOW_DIALOG_KAI_TOAST.
Referenced by execute().
onExecutionDone()
void CPythonInvoker::onExecutionDone () override protected virtual
Reimplemented from ILanguageInvoker.
References GC_SCRIPT, ILanguageInvoker::GetId(), getListOfAddonClassesAsString(), XBMCAddon::Python::PythonLanguageHook::HasRegisteredAddonClasses(), InvokerStateExecutionDone, CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_critical, m_languageHook, m_sourceFile, m_stop, m_stoppedEvent, m_systemExitThrown, m_threadState, onDeinitialization(), ILanguageInvoker::onExecutionDone(), CEvent::Set(), ILanguageInvoker::setState(), and XBMCAddon::Python::PythonLanguageHook::UnregisterMe().
onExecutionFailed()
void CPythonInvoker::onExecutionFailed () override protected virtual
Reimplemented from ILanguageInvoker.
References ILanguageInvoker::GetId(), InvokerStateFailed, CLog::Log(), LOGERROR, m_critical, m_sourceFile, m_threadState, ILanguageInvoker::onExecutionFailed(), and ILanguageInvoker::setState().
onInitialization()
void CPythonInvoker::onInitialization () protected virtual
References ILanguageInvoker::GetId(), getInitializationScript(), CLog::Log(), LOGFATAL, m_sourceFile, and XBMC_TRACE.
Referenced by execute().
onPythonModuleInitialization()
void CPythonInvoker::onPythonModuleInitialization (void * moduleDict) protected virtual
Reimplemented in CContextItemAddonInvoker.
References ADDON::CAddonVersion::asString(), ILanguageInvoker::GetId(), CLog::Log(), LOGDEBUG, ILanguageInvoker::m_addon, and m_sourceFile.
Referenced by execute(), and CContextItemAddonInvoker::onPythonModuleInitialization().
onSuccess()
virtual void CPythonInvoker::onSuccess () inline protected virtual
Referenced by execute().
PyFile_AsFileWithMode()
FILE * CPythonInvoker::PyFile_AsFileWithMode (PyObject * py_file, const char * mode) private
References f.
stop()
bool CPythonInvoker::stop (bool abort) override protected virtual
Implements ILanguageInvoker.
References ILanguageInvoker::AbortNotification(), CServiceBroker::GetAppMessenger(), ILanguageInvoker::GetId(), InvokerStateExecutionDone, InvokerStateFailed, InvokerStateStopping, ILanguageInvoker::IsRunning(), CLog::Log(), LOGDEBUG, LOGERROR, ILanguageInvoker::m_addon, m_critical, m_sourceFile, m_stop, m_stoppedEvent, m_threadState, ILanguageInvoker::pulseGlobalEvent(), PYTHON_SCRIPT_TIMEOUT, ILanguageInvoker::setState(), and CEvent::Wait().
Member Data Documentation
m_critical
CCriticalSection CPythonInvoker::m_critical protected
Referenced by execute(), onExecutionDone(), onExecutionFailed(), and stop().
m_languageHook
XBMCAddon::AddonClass::Ref<XBMCAddon::Python::PythonLanguageHook> CPythonInvoker::m_languageHook private
Referenced by execute(), and onExecutionDone().
m_sourceFile
std::string CPythonInvoker::m_sourceFile protected
Referenced by execute(), onExecutionDone(), onExecutionFailed(), onInitialization(), onPythonModuleInitialization(), CContextItemAddonInvoker::onPythonModuleInitialization(), stop(), and ~CPythonInvoker().
m_stop
bool CPythonInvoker::m_stop = false private
Referenced by execute(), IsStopping(), onExecutionDone(), and stop().
m_stoppedEvent
CEvent CPythonInvoker::m_stoppedEvent private
Referenced by onExecutionDone(), and stop().
m_systemExitThrown
bool CPythonInvoker::m_systemExitThrown = false private
Referenced by execute(), and onExecutionDone().
m_threadState
PyThreadState* CPythonInvoker::m_threadState private
Referenced by execute(), onExecutionDone(), onExecutionFailed(), and stop().
s_critical
CCriticalSection CPythonInvoker::s_critical static private
The documentation for this class was generated from the following files:
PythonInvoker.h
PythonInvoker.cpp