Kodi Documentation: CServiceBroker Class Reference
CServiceBroker Class Reference
#include <ServiceBroker.h>
Public Member Functions
CServiceBroker ()
~CServiceBroker ()
Static Public Member Functions
static std::shared_ptr< CAppParams > GetAppParams ()
static void RegisterAppParams (const std::shared_ptr< CAppParams > &appParams)
static void UnregisterAppParams ()
static CLog & GetLogging ()
static void CreateLogging ()
static bool IsLoggingUp ()
static void DestroyLogging ()
static std::shared_ptr< ANNOUNCEMENT::CAnnouncementManager > GetAnnouncementManager ()
static void RegisterAnnouncementManager (std::shared_ptr< ANNOUNCEMENT::CAnnouncementManager > announcementManager)
static void UnregisterAnnouncementManager ()
static ADDON::CAddonMgr & GetAddonMgr ()
static ADDON::CBinaryAddonManager & GetBinaryAddonManager ()
static ADDON::CBinaryAddonCache & GetBinaryAddonCache ()
static KODI::ADDONS::CExtsMimeSupportList & GetExtsMimeSupportList ()
static ADDON::CVFSAddonCache & GetVFSAddonCache ()
static XBPython & GetXBPython ()
static WSDiscovery::IWSDiscovery & GetWSDiscovery ()
static MEDIA_DETECT::CDetectDVDMedia & GetDetectDVDMedia ()
static PVR::CPVRManager & GetPVRManager ()
static CContextMenuManager & GetContextMenuManager ()
static CDataCacheCore & GetDataCacheCore ()
static CPlatform & GetPlatform ()
static KODI::PLAYLIST::CPlayListPlayer & GetPlaylistPlayer ()
static CSlideShowDelegator & GetSlideShowDelegator ()
static KODI::GAME::CControllerManager & GetGameControllerManager ()
static KODI::GAME::CGameServices & GetGameServices ()
static KODI::RETRO::CGUIGameRenderManager & GetGameRenderManager ()
static PERIPHERALS::CPeripherals & GetPeripherals ()
static CFavouritesService & GetFavouritesService ()
static ADDON::CServiceAddonManager & GetServiceAddons ()
static ADDON::CRepositoryUpdater & GetRepositoryUpdater ()
static CInputManager & GetInputManager ()
static CFileExtensionProvider & GetFileExtensionProvider ()
static bool IsAddonInterfaceUp ()
static bool IsServiceManagerUp ()
static CNetworkBase & GetNetwork ()
static CPowerManager & GetPowerManager ()
static CWeatherManager & GetWeatherManager ()
static CPlayerCoreFactory & GetPlayerCoreFactory ()
static CDatabaseManager & GetDatabaseManager ()
static CEventLog * GetEventLog ()
static CMediaManager & GetMediaManager ()
static CComponentContainer< IApplicationComponent > & GetAppComponents ()
static CGUIComponent * GetGUI ()
static void RegisterGUI (CGUIComponent *gui)
static void UnregisterGUI ()
static void RegisterSettingsComponent (const std::shared_ptr< CSettingsComponent > &settings)
static void UnregisterSettingsComponent ()
static std::shared_ptr< CSettingsComponent > GetSettingsComponent ()
static void RegisterWinSystem (CWinSystemBase *winsystem)
static void UnregisterWinSystem ()
static CWinSystemBase * GetWinSystem ()
static CRenderSystemBase * GetRenderSystem ()
static IAE * GetActiveAE ()
static void RegisterAE (IAE *ae)
static void UnregisterAE ()
static std::shared_ptr< CAppInboundProtocol > GetAppPort ()
static void RegisterAppPort (std::shared_ptr< CAppInboundProtocol > port)
static void UnregisterAppPort ()
static void RegisterDecoderFilterManager (CDecoderFilterManager *manager)
static CDecoderFilterManager * GetDecoderFilterManager ()
static std::shared_ptr< CCPUInfo > GetCPUInfo ()
static void RegisterCPUInfo (std::shared_ptr< CCPUInfo > cpuInfo)
static void UnregisterCPUInfo ()
static void RegisterTextureCache (const std::shared_ptr< CTextureCache > &cache)
static void UnregisterTextureCache ()
static std::shared_ptr< CTextureCache > GetTextureCache ()
static void RegisterJobManager (const std::shared_ptr< CJobManager > &jobManager)
static void UnregisterJobManager ()
static std::shared_ptr< CJobManager > GetJobManager ()
static void RegisterAppMessenger (const std::shared_ptr< KODI::MESSAGING::CApplicationMessenger > &appMessenger)
static void UnregisterAppMessenger ()
static std::shared_ptr< KODI::MESSAGING::CApplicationMessenger > GetAppMessenger ()
static void RegisterKeyboardLayoutManager (const std::shared_ptr< KODI::KEYBOARD::CKeyboardLayoutManager > &keyboardLayoutManager)
static void UnregisterKeyboardLayoutManager ()
static std::shared_ptr< KODI::KEYBOARD::CKeyboardLayoutManager > GetKeyboardLayoutManager ()
static void RegisterSpeechRecognition (const std::shared_ptr< speech::ISpeechRecognition > &speechRecognition)
static void UnregisterSpeechRecognition ()
static std::shared_ptr< speech::ISpeechRecognition > GetSpeechRecognition ()
Private Attributes
std::shared_ptr< CAppParams > m_appParams
std::unique_ptr< CLog > m_logging
std::shared_ptr< ANNOUNCEMENT::CAnnouncementManager > m_pAnnouncementManager
CGUIComponent * m_pGUI = nullptr
CWinSystemBase * m_pWinSystem = nullptr
IAE * m_pActiveAE = nullptr
std::shared_ptr< CAppInboundProtocol > m_pAppPort
std::shared_ptr< CSettingsComponent > m_pSettingsComponent
CDecoderFilterManager * m_decoderFilterManager = nullptr
std::shared_ptr< CCPUInfo > m_cpuInfo
std::shared_ptr< CTextureCache > m_textureCache
std::shared_ptr< CJobManager > m_jobManager
std::shared_ptr< KODI::MESSAGING::CApplicationMessenger > m_appMessenger
std::shared_ptr< KODI::KEYBOARD::CKeyboardLayoutManager > m_keyboardLayoutManager
std::shared_ptr< speech::ISpeechRecognition > m_speechRecognition
std::shared_ptr< CSlideShowDelegator > m_slideshowDelegator
Constructor & Destructor Documentation
CServiceBroker()
CServiceBroker::CServiceBroker ()
~CServiceBroker()
CServiceBroker::~CServiceBroker ()
Member Function Documentation
CreateLogging()
void CServiceBroker::CreateLogging () static
References g_serviceBroker.
Referenced by CAppEnvironment::SetUp().
DestroyLogging()
void CServiceBroker::DestroyLogging () static
References g_serviceBroker.
Referenced by CAppEnvironment::TearDown().
GetActiveAE()
IAE * CServiceBroker::GetActiveAE () static
References g_serviceBroker.
Referenced by ADDON::Interface_AudioEngine::aestream_add_data(), ADDON::Interface_AudioEngine::aestream_drain(), ADDON::Interface_AudioEngine::aestream_flush(), ADDON::Interface_AudioEngine::aestream_get_amplification(), ADDON::Interface_AudioEngine::aestream_get_cache_time(), ADDON::Interface_AudioEngine::aestream_get_cache_total(), ADDON::Interface_AudioEngine::aestream_get_channel_count(), ADDON::Interface_AudioEngine::aestream_get_data_format(), ADDON::Interface_AudioEngine::aestream_get_delay(), ADDON::Interface_AudioEngine::aestream_get_frame_size(), ADDON::Interface_AudioEngine::aestream_get_resample_ratio(), ADDON::Interface_AudioEngine::aestream_get_sample_rate(), ADDON::Interface_AudioEngine::aestream_get_volume(), ADDON::Interface_AudioEngine::aestream_is_buffering(), ADDON::Interface_AudioEngine::aestream_is_drained(), ADDON::Interface_AudioEngine::aestream_is_draining(), ADDON::Interface_AudioEngine::aestream_pause(), ADDON::Interface_AudioEngine::aestream_set_amplification(), ADDON::Interface_AudioEngine::aestream_set_resample_ratio(), ADDON::Interface_AudioEngine::aestream_set_volume(), ADDON::Interface_AudioEngine::audioengine_free_stream(), ADDON::Interface_AudioEngine::audioengine_make_stream(), XBMCAddon::xbmc::audioResume(), XBMCAddon::xbmc::audioSuspend(), KODI::PIPEWIRE::CPipewireProxy::Bound(), PAPlayer::CloseFile(), CVideoPlayerAudio::CloseStream(), CAudioSinkAE::Create(), CGUIVisualisationControl::DeInitVisualization(), deviceChangedCB(), CALSADeviceMonitor::FDEventCallback(), ADDON::Interface_AudioEngine::get_current_sink_format(), VideoPlayerCodec::GetPassthroughStreamType(), CAudioSinkAE::GetPassthroughStreamType(), CALSAHControlMonitor::HCTLCallback(), CApplication::Initialize(), CGUIVisualisationControl::InitVisualization(), CApplicationVolumeHandling::IsMuted(), CGUIAudioManager::LoadSound(), KODI::WINDOWING::X11::CWinEventsX11::MessagePump(), CApplicationVolumeHandling::Mute(), CMMNotificationClient::NotifyAE(), CApplication::OnApplicationMessage(), CXBMCApp::onReceive(), CPowerManager::OnSleep(), CPowerManager::OnWake(), CDVDAudioCodecAndroidMediaCodec::Open(), KODI::RETRO::CRetroPlayerAudio::OpenStream(), CApplication::PlayFile(), PAPlayer::PrepareStream(), CExternalPlayer::Process(), AE::CAESinkFactory::RegisterSink(), KODI::PIPEWIRE::CPipewireProxy::Removed(), CApplicationVolumeHandling::SetHardwareVolume(), SinkCallback(), PAPlayer::SoftStop(), and CApplicationVolumeHandling::UnMute().
GetAddonMgr()
ADDON::CAddonMgr & CServiceBroker::GetAddonMgr () static
References g_application.
Referenced by CApplicationPowerHandling::ActivateScreenSaver(), XBMCAddon::xbmcaddon::Addon::Addon(), anonymous_namespace{SettingConditions.cpp}::AddonHasSettings(), AddonSettings(), CGUIDialogAddonInfo::AskForVersion(), XFILE::Browse(), CGUIDialogAddonInfo::BuildDependencyList(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::CAddonInstallJob(), ADDON::CAddonStatusHandler::CAddonStatusHandler(), PVR::CGUIWindowPVRBase::CanBeActivated(), CGUIViewStateFromItems::CGUIViewStateFromItems(), ADDON::CAddonInstaller::CheckDependencies(), CApplication::ConfigureAndEnableAddons(), CLangInfo::ConvertEnglishNameToAddonLocale(), PERIPHERALS::CPeripheralBusAddon::CPeripheralBusAddon(), PVR::CPVRClients::CPVRClients(), CDVDFactoryInputStream::CreateInputStream(), ADDON::CRepository::CRepository(), ADDON::CBinaryAddonCache::Deinit(), ADDON::CVFSAddonCache::Deinit(), KODI::GAME::CGUIAgentControllerList::Deinitialize(), KODI::GAME::CGUIControllerList::Deinitialize(), KODI::GAME::CGUIActivePortList::Deinitialize(), KODI::GAME::CGUIPortList::Deinitialize(), XFILE::DependencyAddons(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::DoWork(), ADDON::CRepositoryUpdateJob::DoWork(), CWeatherJob::DoWork(), KODI::GAME::CGameUtils::Enable(), EnableAddon(), PERIPHERALS::CPeripheralBusAddon::EnableButtonMapping(), PVR::CPVRClients::EnabledClientAmount(), CONTEXTMENU::CAddonSettings::Execute(), CONTEXTMENU::CCheckForUpdates::Execute(), CONTEXTMENU::CEnableAddon::Execute(), CONTEXTMENU::CDisableAddon::Execute(), CContextMenuItem::Execute(), CPythonInvoker::execute(), JSONRPC::CAddonsOperations::ExecuteAddon(), ADDON::CRepository::FetchIndex(), JSONRPC::CAddonsOperations::FillDetails(), CGUIDialogSubtitles::FillServices(), CProfileManager::FinalizeLoadProfile(), ADDON::CLanguageResource::FindLegacyLanguage(), PVR::CPVRDatabase::FixupClientIDs(), XFILE::CAddonsDirectory::GenerateAddonListing(), ADDON::Interface_Base::get_temp_path(), ADDON::CAddonSystemSettings::GetActive(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::GetAddon(), JSONRPC::CAddonsOperations::GetAddonDetails(), CPythonInvoker::getAddonModuleDeps(), JSONRPC::CAddonsOperations::GetAddons(), ADDON::CBinaryAddonCache::GetAddons(), CLangInfo::GetAddonsLanguageCodes(), PVR::CPVRClients::GetAddonsWithStatus(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), PVR::CPVRClients::GetCallableClients(), PVR::CPVRClients::GetClientProviderInfos(), anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetController(), anonymous_namespace{TestDefaultMouseTranslator.cpp}::GetController(), XFILE::CAddonsDirectory::GetDirectory(), CGUIMediaWindow::GetDirectory(), CGUIWindowAddonBrowser::GetDirectory(), ADDON::CBinaryAddonCache::GetDisabledAddons(), PVR::CPVRClients::GetEnabledClientInfos(), KODI::GAME::CGameUtils::GetGameClients(), KODI::GAME::CGameUtils::GetGameExtensions(), ADDON::CAddonInstaller::GetInstallList(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetInt(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetLabel(), CLangInfo::GetLanguageAddon(), KODI::GAME::CGameClient::GetMissingResource(), JSONRPC::CGUIOperations::GetPropertyValue(), KODI::GAME::CGameClientProperties::GetProxyAddons(), XFILE::GetRecentlyUpdatedAddons(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), CMusicDatabase::GetScraper(), CVideoDatabase::GetScraperForPath(), CNfoFile::GetScrapers(), XFILE::CAddonsDirectory::GetScriptsAndPlugins(), GetSoundSkinPath(), KODI::CDRIP::CCDDARipper::GetTrackName(), KODI::GAME::CDialogGameSaves::HandleGameClient(), CHTTPWebinterfaceAddonsHandler::HandleRequest(), KODI::GAME::CGameUtils::HasGameExtension(), anonymous_namespace{SettingConditions.cpp}::HasPeripheralLibraries(), CVideoDatabase::ImportFromXML(), ADDON::CBinaryAddonCache::Init(), ADDON::CVFSAddonCache::Init(), KODI::CDRIP::CEncoderFFmpeg::Init(), CApplication::Initialize(), KODI::GAME::CGUIControllerList::Initialize(), KODI::GAME::CGUIAgentControllerList::Initialize(), KODI::GAME::CGUIActivePortList::Initialize(), KODI::GAME::CGUIPortList::Initialize(), CGUIDialogContentSettings::InitializeSettings(), CGUIVisualisationControl::InitVisualization(), ADDON::CAddonInstaller::Install(), KODI::GAME::CGameUtils::Install(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), KODI::GAME::CGameClientProperties::InstallDependencies(), ADDON::CAddonInstaller::InstallFromZip(), ADDON::CAddonInstaller::InstallModal(), PERIPHERALS::CPeripheralJoystick::InstallSync(), ADDON::Interface_General::is_addon_avilable(), PVR::CPVRClient::IsEnabled(), PVR::CPVRClients::IsEnabledClient(), XFILE::CPluginDirectory::IsMediaLibraryScanningAllowed(), ADDON::CAddonMgr::IsOrphaned(), XFILE::CAddonsDirectory::IsRepoDirectory(), CONTEXTMENU::CAddonSettings::IsVisible(), CONTEXTMENU::CEnableAddon::IsVisible(), CONTEXTMENU::CDisableAddon::IsVisible(), ADDON::CScraper::Load(), CApplicationSkinHandling::LoadSkin(), GUIFontManager::LoadTTF(), PVR::CPVRClients::OnAddonEvent(), CGUIMediaWindow::OnClick(), KODI::GAME::CGUIControllerWindow::OnDeinitWindow(), CGUIDialogAddonInfo::OnEnableDisable(), KODI::GAME::CGUIControllerWindow::OnEvent(), PERIPHERALS::CPeripheralBusAddon::OnEvent(), ADDON::CBinaryAddonCache::OnEvent(), ADDON::CVFSAddonCache::OnEvent(), KODI::GAME::CGUIAgentWindow::OnInitWindow(), KODI::GAME::CGUIControllerWindow::OnInitWindow(), KODI::GAME::CDialogGameSaves::OnInitWindow(), KODI::GAME::CGUIPortWindow::OnInitWindow(), CGUIDialogAddonInfo::OnMessage(), CGUIWindowAddonBrowser::OnMessage(), KODI::GAME::CDialogGameAdvancedSettings::OnMessage(), CGUIWindowScreensaver::OnMessage(), ADDON::CFontResource::OnPostInstall(), CGUIDialogAddonInfo::OnSelectVersion(), CApplicationPowerHandling::OnSettingAction(), CApplicationSettingsHandling::OnSettingAction(), CGUIDialogInfoProviderSettings::OnSettingAction(), PERIPHERALS::CPeripherals::OnSettingAction(), CGUIDialogContentSettings::OnSettingAction(), CRssManager::OnSettingAction(), CWeatherManager::OnSettingAction(), CGUIDialogSubtitles::OnSubtitleServiceContextMenu(), CGUIDialogAddonInfo::OnToggleAutoUpdates(), ADDON::Interface_Base::open_settings_dialog(), KODI::RETRO::CRetroPlayer::OpenFile(), ADDON::CAddonInfo::OriginName(), XFILE::OutdatedAddons(), CFavouritesURL::Parse(), CApplication::PlayMedia(), ADDON::CAddonStatusHandler::Process(), KODI::GAME::CControllerInstaller::Process(), PERIPHERALS::CPeripheralBusAddon::PromptEnableAddons(), CGUIDialogAddonInfo::PromptIfDependency(), ADDON::CAddonInstaller::RemoveOrphanedDepsRecursively(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::ReportInstallError(), XFILE::Repos(), CDirectoryProvider::Reset(), CHTTPWebinterfaceHandler::ResolveAddon(), ADDON::ResolveDependencies(), XFILE::RootDirectory(), UpdateAddons::Run(), UpdateAllowedAddons::Run(), RunAddon(), XFILE::RunningAddons(), RunScript(), XFILE::CPluginDirectory::RunScriptWithParams(), ADDON::CAddon::SaveSettings(), CGUIWindowAddonBrowser::SelectAddonID(), JSONRPC::CAddonsOperations::SetAddonEnabled(), CGUIDialogAddonInfo::SetItem(), CLangInfo::SetLanguage(), CLangInfo::SettingOptionsLanguageNamesFiller(), KODI::CDRIP::CCDDARipJob::SetupEncoder(), CGUIDialogInfoProviderSettings::SetupView(), CGUIDialogContentSettings::SetupView(), CGUIDialogInfoProviderSettings::Show(), CGUIDialogAddonInfo::ShowDependencyList(), CGUIDialogAddonSettings::ShowForMultipleInstances(), XFILE::CPluginDirectory::StartScript(), StopScript(), TEST(), XFILE::CResourceFile::TranslatePath(), ADDON::CBinaryAddonCache::Update(), CGUIControlButtonSetting::Update(), ADDON::CVFSAddonCache::Update(), PERIPHERALS::CPeripheralBusAddon::UpdateAddons(), KODI::GAME::CGUIControllerWindow::UpdateButtons(), PVR::CPVRClients::UpdateClients(), CGUIDialogAddonInfo::UpdateControls(), UpdateLocals(), CDirectoryProvider::UpdateURL(), CGUIWindowScreensaverDim::UpdateVisibility(), XFILE::UserInstalledAddons(), XBMCAddon::xbmcaddon::Addon::~Addon(), PERIPHERALS::CPeripheralBusAddon::~CPeripheralBusAddon(), and PVR::CPVRClients::~CPVRClients().
GetAnnouncementManager()
std::shared_ptr< ANNOUNCEMENT::CAnnouncementManager > CServiceBroker::GetAnnouncementManager () static
References g_serviceBroker.
Referenced by CApplicationPowerHandling::ActivateScreenSaver(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), CPartyModeManager::Announce(), KODI::PLAYLIST::CPlayList::AnnounceAdd(), KODI::PLAYLIST::CPlayList::AnnounceClear(), CGUIWindowSlideShow::AnnouncePlayerPause(), CGUIWindowSlideShow::AnnouncePlayerPlay(), CGUIWindowSlideShow::AnnouncePlayerStop(), CGUIWindowSlideShow::AnnouncePlaylistAdd(), CGUIWindowSlideShow::AnnouncePlaylistClear(), CGUIWindowSlideShow::AnnouncePropertyChanged(), KODI::PLAYLIST::CPlayListPlayer::AnnouncePropertyChanged(), AnnounceRemove(), CVideoDatabase::AnnounceRemove(), KODI::PLAYLIST::CPlayList::AnnounceRemove(), CVideoDatabase::AnnounceUpdate(), AnnounceUpdate(), CZeroconfBrowserDarwin::BrowserCallback(), CZeroconfBrowserMDNS::BrowserCallback(), CAirPlayServer::CAirPlayServer(), CGUIPlayerAnnouncementHandler::CGUIPlayerAnnouncementHandler(), CGUISourcesAnnouncementHandler::CGUISourcesAnnouncementHandler(), CGUIWindowHome::CGUIWindowHome(), CGUIWindowSlideShow::CGUIWindowSlideShow(), CVideoPlayer::CheckAutoSceneSkip(), CHotKeyController::CHotKeyController(), CVideoDatabase::CleanDatabase(), CMusicDatabase::Cleanup(), PERIPHERALS::CPeripherals::Clear(), CLibInputHandler::CLibInputHandler(), UPNP::CUPnPRenderer::CUPnPRenderer(), CDVDRadioRDSData::DecodeRTC(), CDVDRadioRDSData::DecodeTA_TP(), JSONRPC::CTCPServer::Deinitialize(), CAnnounceReceiver::DeInitialize(), CSaveFileState::DoWork(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), CVideoPlayer::HandlePlaySpeed(), CWinEventsWin10::InitEventHandlers(), PERIPHERALS::CPeripherals::Initialise(), JSONRPC::CTCPServer::Initialize(), CXBMCApp::Initialize(), CAnnounceReceiver::Initialize(), JSONRPC::CJSONRPC::NotifyAll(), NotifyAll(), CVideoPlayer::OnAction(), UPNP::CMediaBrowser::OnContainerChanged(), CGUIDialogKeyboardGeneric::OnDeinitWindow(), CGUIDialogNumeric::OnDeinitWindow(), KODI::GAME::CDialogGameVolume::OnDeinitWindow(), CXBMCApp::onDestroy(), CVideoPlayer::OnDiscNavResult(), CGUIDialogKeyboardGeneric::OnInitWindow(), CGUIDialogNumeric::OnInitWindow(), KODI::GAME::CDialogGameVolume::OnInitWindow(), CPowerManager::OnLowBattery(), CApplication::OnMessage(), UPNP::CMediaBrowser::OnMSAdded(), UPNP::CMediaBrowser::OnMSRemoved(), CZeroconfBrowserAndroidDiscover::onServiceFound(), CMediaSettings::OnSettingChanged(), CPowerManager::OnSleep(), UPNP::CUPnPServer::OnUpdateObject(), CPowerManager::OnWake(), CVideoPlayer::Prepare(), MUSIC_INFO::CMusicInfoScanner::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), CPowerManager::Reboot(), CAirTunesServer::RegisterActionListener(), CDirectoryProvider::Reset(), CDVDRadioRDSData::SendTMCSignal(), CGUIInfoManager::SetCurrentItem(), CVideoDatabase::SetPlayCount(), UPNP::CUPnPServer::SetupServices(), CApplication::Stop(), CApplicationPowerHandling::ToggleDPMS(), XBPython::Uninitialize(), CDirectoryProvider::UpdateURL(), CApplicationVolumeHandling::VolumeChanged(), CApplicationPowerHandling::WakeUpScreenSaverAndDPMS(), XBPython::XBPython(), CAirPlayServer::~CAirPlayServer(), CGUIPlayerAnnouncementHandler::~CGUIPlayerAnnouncementHandler(), CGUISourcesAnnouncementHandler::~CGUISourcesAnnouncementHandler(), CGUIWindowHome::~CGUIWindowHome(), CGUIWindowSlideShow::~CGUIWindowSlideShow(), CHotKeyController::~CHotKeyController(), CLibInputHandler::~CLibInputHandler(), PVR::CPVRManager::~CPVRManager(), UPNP::CUPnPRenderer::~CUPnPRenderer(), UPNP::CUPnPServer::~CUPnPServer(), and XBPython::~XBPython().
GetAppComponents()
CApplicationComponents & CServiceBroker::GetAppComponents () static
References g_application.
Referenced by KODI::JOYSTICK::CJoystickMonitor::AcceptsInput(), anonymous_namespace{GUIBuiltins.cpp}::ActivateAndFocus(), CApplicationPowerHandling::ActivateScreenSaver(), anonymous_namespace{GUIBuiltins.cpp}::ActivateWindow(), CGUIDialogAudioSettings::AddAudioStreams(), CGUIDialogVideoBookmarks::AddBookmark(), JSONRPC::CPlayerOperations::AddSubtitle(), CGUIDialogSubtitleSettings::AddSubtitleStreams(), CGUIDialogVideoSettings::AddVideoStreams(), CPartyModeManager::Announce(), KODI::PLAYLIST::CPlayListPlayer::AnnouncePropertyChanged(), CAirTunesServer::AudioOutputFunctions::audio_set_progress(), CAirTunesServer::AudioOutputFunctions::audio_set_volume(), CGUIDialogAudioSettings::AudioStreamsOptionFiller(), CAirPlayServer::backupVolume(), XBMCAddon::xbmc::RenderCapture::capture(), CInertialScrollingHandler::CheckForInertialScrolling(), CApplicationPowerHandling::CheckScreenSaverAndDPMS(), CApplicationPowerHandling::CheckShutdown(), CGUIWindowFullScreen::ClearBackground(), XFILE::CFile::Copy(), PVR::CPVRGUIActionListener::CPVRGUIActionListener(), CTeletextDecoder::Decode_ADIP(), CTeletextDecoder::Decode_BTT(), CTeletextDecoder::DecodePage(), CDVDRadioRDSData::DecodeTA_TP(), CAutorunMediaJob::DoWork(), CSaveFileState::DoWork(), MUSIC_UTILS::CSetArtJob::DoWork(), CTeletextDecoder::Eval_l25(), CTeletextDecoder::Eval_NumberedObject(), KODI::WINDOWING::X11::CWinSystemX11GLContext::FinishWindowResize(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::FinishWindowResize(), CSeekHandler::FrameMove(), CGUIDialogSeekBar::FrameMove(), CGUIDialogAudioSettings::FrameMove(), CGUIDialogSubtitleSettings::FrameMove(), CGUIWindowFullScreen::FrameMove(), ADDON::Interface_General::get_global_idle_time(), JSONRPC::CPlayerOperations::GetActivePlayers(), anonymous_namespace{Player.cpp}::getAppPlayer(), anonymous_namespace{Player.cpp}::getAppPlayerMut(), JSONRPC::CPlayerOperations::GetAudioDelay(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIDialogSeekBar::GetEpgEventProgress(), XBMCAddon::xbmc::getGlobalIdleTime(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), XBMCAddon::xbmc::RenderCapture::GetPixels(), JSONRPC::CPlayerOperations::GetPlaylist(), CGUIDialogSeekBar::GetProgress(), JSONRPC::CApplicationOperations::GetPropertyValue(), JSONRPC::CPlayerOperations::GetPropertyValue(), PVR::CPVRGUIInfo::GetPVRLabel(), PVR::CPVRGUIInfo::GetRadioRDSBool(), CAudioDecoder::GetReplayGain(), PVR::CPVRGUIInfo::GetTimeShiftSeekPercent(), CStereoscopicsManager::GetVideoStereoMode(), JSONRPC::CPlayerOperations::GetViewMode(), CWindowTranslator::GetVirtualWindow(), KODI::GAME::CDialogGameVolume::GetVolumePercent(), CGUIDialogVideoBookmarks::GotoBookmark(), CInputManager::HandleKey(), JSONRPC::CInputOperations::handleScreenSaver(), CAirTunesServer::InformPlayerAboutPlayTimes(), TVOSLibInputHandler::init, KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), CTeletextDecoder::InitDecoder(), CGUIDialogAudioSettings::InitializeSettings(), CGUIDialogSubtitleSettings::InitializeSettings(), CGUIDialogVideoSettings::InitializeSettings(), CGUIDialogAudioSettings::IsPlayingPassthrough(), CApplicationSettingsHandling::Load(), CGUIWindowPictures::LoadPlayList(), CApplicationSkinHandling::LoadSkin(), CProfileManager::LogOff(), CGUIWindowMusicPlayList::MoveCurrentPlayListItem(), CGUIWindowVideoPlaylist::MoveCurrentPlayListItem(), Mute(), CGUIDialogVolumeBar::OnAction(), CGUIWindowSlideShow::OnAction(), CSeekHandler::OnAction(), CPlayerController::OnAction(), CGUIWindowFullScreen::OnAction(), CGUIWindowHome::OnAction(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::OnConfigure(), jni::CJNIXBMCMediaSession::OnForwardRequested(), CXBMCApp::onGainFocus(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), CGUIDialogSubtitles::OnInitWindow(), CApplication::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVisualisation::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIDialogSubtitles::OnMessage(), CGUIDialogTeletext::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIWindowScreensaver::OnMessage(), CGUIVideoControl::OnMouseEvent(), jni::CJNIXBMCMediaSession::OnNextRequested(), CXBMCApp::onPause(), jni::CJNIXBMCMediaSession::OnPauseRequested(), CXBMCApp::OnPlayBackStarted(), CApplicationPlayerCallback::OnPlayBackStarted(), CApplicationPlayerCallback::OnPlayerCloseFile(), CGUIWindowVideoBase::OnPlayMedia(), jni::CJNIXBMCMediaSession::OnPlayRequested(), jni::CJNIXBMCMediaSession::OnPreviousRequested(), CXBMCApp::onReceive(), CGUIDialogVideoBookmarks::OnRefreshList(), CXBMCApp::onResume(), jni::CJNIXBMCMediaSession::OnRewindRequested(), CGUIDialogSubtitles::OnSearchComplete(), CApplicationSettingsHandling::OnSettingAction(), CGUIDialogSubtitleSettings::OnSettingAction(), CApplicationSettingsHandling::OnSettingChanged(), CGUIDialogAudioSettings::OnSettingChanged(), CGUIDialogSubtitleSettings::OnSettingChanged(), CGUIDialogVideoSettings::OnSettingChanged(), CGUIWindowPictures::OnShowPictureRecursive(), CPowerManager::OnSleep(), KODI::GAME::CDialogGameVolume::OnSliderChange(), CPlayerController::OnSliderChange(), CGUIWindowFileManager::OnStart(), jni::CJNIXBMCMediaSession::OnStopRequested(), CPowerManager::OnWake(), CXBMCApp::OnWakeup(), KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream(), PlayerControl(), KODI::PLAYLIST::CPlayListPlayer::PlayNext(), PlayOffset(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), JSONRPC::CPlayerOperations::PlayPause(), CExternalPlayer::Process(), CGUIWindowFullScreen::Process(), CGUIVideoControl::Process(), CGUIVisualisationControl::Process(), CGUIWindowSlideShow::Process(), CInputManager::ProcessEventServer(), CInputManager::ProcessMouse(), CAirPlayServer::CTCPClient::ProcessRequest(), MUSIC_UTILS::QueueItem(), KODI::VIDEO::UTILS::QueueItem(), KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext(), CAirTunesServer::RegisterActionListener(), CApplicationSettingsHandling::RegisterSettings(), ReloadSkin(), CGUIWindowMusicPlayList::RemovePlayListItem(), CGUIWindowVideoPlaylist::RemovePlayListItem(), CGUIVideoControl::Render(), CGUIWindowSlideShow::Render(), CGUIWindowFullScreen::Render(), CTeletextDecoder::RenderChar(), CGUIVideoControl::RenderEx(), CGUIWindowSlideShow::RenderEx(), CGUIWindowFullScreen::RenderEx(), CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGL::RenderSinglePass(), CApplicationPlayerCallback::RequestVideoSettings(), OVERLAY::CRenderer::ResetSubtitlePosition(), KODI::JOYSTICK::CJoystickMonitor::ResetTimers(), KODI::PLAYLIST::CPlayListPlayer::ReShuffle(), KODI::WINDOWING::X11::CWinSystemX11GLContext::ResizeWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::ResizeWindow(), CAirPlayServer::restoreVolume(), CGUIWindowSlideShow::RunSlideShow(), CGUIDialogAudioSettings::Save(), CGUIDialogSubtitleSettings::Save(), CGUIDialogVideoSettings::Save(), CApplicationSettingsHandling::Save(), CGUIDialogSubtitles::Search(), JSONRPC::CPlayerOperations::Seek(), Seek(), CGUIWindowFullScreen::SeekChapter(), SeekPercentage(), CSeekHandler::SeekSeconds(), JSONRPC::CInputOperations::SendAction(), JSONRPC::CPlayerOperations::SetAudioDelay(), JSONRPC::CPlayerOperations::SetAudioStream(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetFullScreen(), CGraphicContext::SetFullScreenVideo(), JSONRPC::CApplicationOperations::SetMute(), CAppInboundProtocol::SetRenderGUI(), CSeekHandler::SetSeekSize(), CGUIDialogSubtitles::SetService(), JSONRPC::CPlayerOperations::SetSpeed(), JSONRPC::CPlayerOperations::SetSubtitle(), CGUIDialogSubtitles::SetSubtitles(), JSONRPC::CPlayerOperations::SetTempo(), JSONRPC::CPlayerOperations::SetVideoStream(), JSONRPC::CPlayerOperations::SetViewMode(), JSONRPC::CApplicationOperations::SetVolume(), SetVolume(), CAESinkPULSE::SetVolume(), CGUIWindowPictures::ShowPicture(), JSONRPC::CPlayerOperations::StartSlideshow(), CWinIdleTimer::StartZero(), CPowerManager::StorePlayerState(), CGUIDialogSubtitleSettings::SubtitleStreamsOptionFiller(), CXBMCApp::surfaceCreated(), CXBMCApp::surfaceDestroyed(), CGUIWindowManager::SwitchToFullScreen(), ToggleDPMS(), CGUIWindowFullScreen::TriggerOSD(), UnloadSkin(), CApplicationSettingsHandling::UnregisterSettings(), CGUIInfoManager::UpdateAVInfo(), CGUIWindowMusicPlayList::UpdateButtons(), CGUIWindowVideoPlaylist::UpdateButtons(), CXBMCApp::UpdateSessionMetadata(), CXBMCApp::UpdateSessionState(), CGUIWindowScreensaver::UpdateVisibility(), CGUIWindowScreensaverDim::UpdateVisibility(), CGUIDialogVideoSettings::VideoStreamsOptionFiller(), CApplicationVolumeHandling::VolumeChanged(), CWakeOnAccess::WakeUpHost(), CWinEventsWin32::WndProc(), PVR::CPVRGUIActionListener::~CPVRGUIActionListener(), and XBMCAddon::xbmc::RenderCapture::~RenderCapture().
GetAppMessenger()
std::shared_ptr< KODI::MESSAGING::CApplicationMessenger > CServiceBroker::GetAppMessenger () static
References g_serviceBroker.
Referenced by anonymous_namespace{GUIBuiltins.cpp}::Action(), JSONRPC::CGUIOperations::ActivateScreenSaver(), ActivateScreensaver(), ActivateSource(), JSONRPC::CGUIOperations::ActivateWindow(), CGUIWindowManager::ActivateWindow(), JSONRPC::CInputOperations::activateWindow(), JSONRPC::CPlaylistOperations::Add(), CAirTunesServer::AudioOutputFunctions::audio_destroy(), CAirTunesServer::AudioOutputFunctions::audio_init(), JSONRPC::CInputOperations::ButtonEvent(), KODI::GAME::CGameClient::cb_close_game(), CApplicationPowerHandling::CheckShutdown(), CGUIPassword::CheckStartUpLock(), JSONRPC::CAudioLibrary::Clean(), JSONRPC::CVideoLibrary::Clean(), JSONRPC::CPlaylistOperations::Clear(), XBMCAddon::xbmcgui::Window::close(), XBMCAddon::xbmcgui::WindowDialogMixin::close(), CGUIDialogCache::Close(), CGUIWindow::Close(), CNetworkBase::CNetworkBase(), XBMCAddon::xbmcgui::Window::dispose(), XBMCAddon::xbmcgui::Window::doAddControl(), KODI::GAME::CGUIFeatureButton::DoPrompt(), XBMCAddon::xbmcgui::Window::doRemoveControl(), Exec(), JSONRPC::CAddonsOperations::ExecuteAddon(), XBMCAddon::xbmc::executebuiltin(), XBMCAddon::xbmc::executescript(), JSONRPC::CAudioLibrary::Export(), JSONRPC::CVideoLibrary::Export(), CRenderManager::Flush(), CGUIWindowManager::FrameMove(), XFILE::CDirectory::GetDirectory(), CGUIMediaWindow::GetDirectoryItems(), JSONRPC::CXBMCOperations::GetInfoBooleans(), JSONRPC::CXBMCOperations::GetInfoLabels(), JSONRPC::CPlaylistOperations::GetItems(), JSONRPC::CPlaylistOperations::GetPropertyValue(), JSONRPC::CPlayerOperations::GoTo(), DX::DeviceResources::HandleDeviceLost(), CAppInboundProtocol::HandleEvents(), CInputManager::HandleKey(), CVideoPlayer::HandlePlaySpeed(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), CApplicationPowerHandling::HandleShutdownMessage(), JSONRPC::CSystemOperations::Hibernate(), Hibernate(), InhibitIdle(), InhibitScreenSaver(), PERIPHERALS::CPeripherals::Initialise(), CGUIInfoManager::Initialize(), CGUIWindow::Initialize(), CGUIWindowManager::Initialize(), CDVDVideoCodecAndroidMediaCodec::InitSurfaceTexture(), JSONRPC::CPlaylistOperations::Insert(), CGUIKeyboardFactory::keyTypedCB(), LaunchAndroidActivity(), KODI::RETRO::CCheevos::LoadData(), JSONRPC::CProfilesOperations::LoadProfile(), LoadProfile(), KODI::WINDOWING::X11::CWinEventsX11::MessagePump(), CWinSystemIOS::Minimize(), CWinSystemTVOS::Minimize(), KODI::WINDOWING::X11::CWinSystemX11::Minimize(), Minimize(), JSONRPC::CPlayerOperations::Move(), CWinSystemOSX::MoveToScreen(), KODI::GAME::CGUIAgentControllerList::Notify(), KODI::GAME::CGUIActivePortList::Notify(), PVR::CGUIDialogPVRChannelsOSD::Notify(), CWinSystemIOS::NotifyAppActiveChange(), CWinSystemTVOS::NotifyAppActiveChange(), KODI::WINDOWING::X11::CWinSystemX11::NotifyAppActiveChange(), KODI::WINDOWING::X11::CWinSystemX11::NotifyAppFocusChange(), PVR::CGUIWindowPVRBase::NotifyEvent(), CVideoPlayer::OnAction(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CXBMCApp::onAudioFocusChange(), CWinEventsWin10::OnBackRequested(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnClose(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::OnConfigure(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), KODI::GAME::CGUIPortList::OnControllerSelected(), KODI::GAME::CGUIAgentControllerList::OnEvent(), KODI::GAME::CGUIControllerList::OnEvent(), KODI::GAME::CGUIActivePortList::OnEvent(), KODI::GAME::CGUIPortList::OnEvent(), CInputManager::OnEvent(), CGUIWindowFavourites::OnFavouritesEvent(), jni::CJNIXBMCMediaSession::OnForwardRequested(), CGUIWindowFileManager::OnJobComplete(), CApplication::OnMessage(), CGUIWindowLoginScreen::OnMessage(), CWinSystemOSX::OnMove(), CXBMCApp::onNewIntent(), UPNP::CUPnPRenderer::OnNext(), jni::CJNIXBMCMediaSession::OnNextRequested(), CXBMCApp::onPause(), UPNP::CUPnPRenderer::OnPause(), jni::CJNIXBMCMediaSession::OnPauseRequested(), UPNP::CUPnPRenderer::OnPlay(), jni::CJNIXBMCMediaSession::OnPlayRequested(), CGUIWindowSettingsProfile::OnPopupMenu(), CGUIMediaWindow::OnPopupMenu(), CGUIWindowLoginScreen::OnPopupMenu(), ADDON::CFontResource::OnPostInstall(), ADDON::CSkinInfo::OnPostInstall(), ADDON::CSkinInfo::OnPreInstall(), UPNP::CUPnPRenderer::OnPrevious(), jni::CJNIXBMCMediaSession::OnPreviousRequested(), PVR::CPVRGUIActionListener::OnPVRManagerEvent(), CXBMCApp::onReceive(), CSpeechRecognitionListener::OnResults(), CXBMCApp::onResume(), jni::CJNIXBMCMediaSession::OnRewindRequested(), UPNP::CUPnPRenderer::OnSeek(), UPNP::CUPnPRenderer::OnSetMute(), UPNP::CUPnPRenderer::OnSetNextAVTransportURI(), ADDON::CAddonSettings::OnSettingAction(), CApplicationSkinHandling::OnSettingChanged(), CApplicationSettingsHandling::OnSettingChanged(), CNetworkServices::OnSettingChanged(), UPNP::CUPnPRenderer::OnSetVolume(), CXBMCApp::onStop(), UPNP::CUPnPRenderer::OnStop(), jni::CJNIXBMCMediaSession::OnStopRequested(), CStereoscopicsManager::OnStreamChange(), CWinEventsWin10::OnSystemMediaButtonPressed(), CXBMCApp::onVisibleBehindCanceled(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnWindowClose(), CGUIDialog::Open(), JSONRPC::CPlayerOperations::Open(), KODI::RETRO::CRetroPlayer::OpenFile(), XBMCAddon::xbmc::Player::pause(), CApplication::PlaybackCleanup(), XBMCAddon::xbmc::Player::playCurrent(), UPNP::CUPnPRenderer::PlayMedia(), XBMCAddon::xbmc::Player::playnext(), JSONRPC::CPlayerOperations::PlayPause(), XBMCAddon::xbmc::Player::playPlaylist(), XBMCAddon::xbmc::Player::playprevious(), PVR::CPVRGUIActionsPlayback::PlayRecording(), PVR::CPVRGUIActionsPlayback::PlayRecordingFolder(), XBMCAddon::xbmc::Player::playselected(), XBMCAddon::xbmc::Player::playStream(), Powerdown(), CRenderManager::PreInit(), CApplication::Process(), XFILE::CShoutcastFile::Process(), KODI::MESSAGING::CDelayedMessage::Process(), PVR::CPVRRefreshTimelineItemsThread::Process(), CGUIWindowManager::Process(), CAirPlayServer::CTCPClient::ProcessRequest(), CApplication::ProcessSlow(), PAPlayer::ProcessStream(), ProgressDialogHelper::ProgressDialogHelper(), CXBMCApp::Quit(), JSONRPC::CApplicationOperations::Quit(), Quit(), JSONRPC::CSystemOperations::Reboot(), Reboot(), CAirTunesServer::RefreshMetadata(), JSONRPC::CPlaylistOperations::Remove(), CGUIWindowManager::Render(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), KODI::GAME::CGUIPortList::ResetPorts(), ResetScreensaver(), XBMCAddon::xbmc::restart(), RestartApp(), CApplication::Run(), CTVOSTopShelf::RunTopShelf(), JSONRPC::CAudioLibrary::Scan(), JSONRPC::CVideoLibrary::Scan(), PVR::CPVRGUIActionsPlayback::SeekBackward(), PVR::CPVRGUIActionsPlayback::SeekForward(), CApplication::SeekTime(), JSONRPC::CInputOperations::SendAction(), JSONRPC::CPlayerOperations::SendSlideshowAction(), JSONRPC::CInputOperations::SendText(), JSONRPC::CGUIOperations::SetFullscreen(), anonymous_namespace{GUIBuiltins.cpp}::SetLanguage(), CLangInfo::SetLanguage(), JSONRPC::CApplicationOperations::SetMute(), JSONRPC::CPlayerOperations::SetPartymode(), JSONRPC::CPlayerOperations::SetRepeat(), JSONRPC::CPlayerOperations::SetShuffle(), anonymous_namespace{GUIBuiltins.cpp}::SetStereoMode(), JSONRPC::CGUIOperations::SetStereoscopicMode(), CGraphicContext::SetVideoResolution(), JSONRPC::CApplicationOperations::SetVolume(), SetVolume(), XBMCAddon::xbmcgui::Window::show(), XBMCAddon::xbmcgui::WindowDialogMixin::show(), ADDON::CGUIAddonWindowDialog::Show(), CONTEXTMENU::ShowFor(), KODI::MESSAGING::HELPERS::ShowOKDialogLines(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), KODI::MESSAGING::HELPERS::ShowYesNoCustomDialog(), KODI::MESSAGING::HELPERS::ShowYesNoDialogLines(), XBMCAddon::xbmc::shutdown(), JSONRPC::CSystemOperations::Shutdown(), Shutdown(), CWinSystemOSX::SignalFullScreenStateChanged(), Standby(), PVR::CPVRPlaybackState::StartPlayback(), CRenderManager::StartRenderCapture(), JSONRPC::CPlayerOperations::StartSlideshow(), XBMCAddon::xbmc::Player::stop(), CPythonInvoker::stop(), PVR::CPVRManager::Stop(), JSONRPC::CPlayerOperations::Stop(), CAlarmClock::Stop(), CApplication::Stop(), PVR::CPVRClients::StopClient(), JSONRPC::CSystemOperations::Suspend(), Suspend(), JSONRPC::CPlaylistOperations::Swap(), ToggleState(), anonymous_namespace{PVRGUIActionsChannels.cpp}::TriggerChannelSwitchAction(), CRenderManager::UnInit(), KODI::MESSAGING::HELPERS::UpdateOKDialogText(), PERIPHERALS::CGUIDialogPeripherals::UpdatePeripheralsAsync(), CTexture::UploadFromMemory(), CScriptRunner::WaitOnScriptResult(), CWakeOnAccess::WakeUpHost(), CApplicationPowerHandling::WakeUpScreenSaver(), CWinEventsWin32::WndProc(), CXBMCApp::XBMC_DestroyDisplay(), CXBMCApp::XBMC_SetupDisplay(), and CNetworkBase::~CNetworkBase().
GetAppParams()
std::shared_ptr< CAppParams > CServiceBroker::GetAppParams () static
References g_serviceBroker.
Referenced by CPosixInterfaceForCLog::AddSinks(), CApplication::Create(), CApplication::CreateGUI(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CAdvancedSettings::Initialize(), CSettingConditions::Initialize(), CSettingsComponent::Initialize(), CAdvancedSettings::Initialize(), CSettings::InitializeDefaults(), CPlatformFreebsd::InitStageOne(), CPlatformLinux::InitStageOne(), CApplication::PlaybackCleanup(), KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext(), CApplication::Run(), CPowerManager::SetDefaults(), and CPowerManager::SettingOptionsShutdownStatesFiller().
GetAppPort()
std::shared_ptr< CAppInboundProtocol > CServiceBroker::GetAppPort () static
References g_serviceBroker.
Referenced by CGenericTouchActionHandler::focusControl(), CRemoteControlXbox::HandleAcceleratorKey(), CRemoteControlXbox::HandleMediaButton(), CIRServerSuite::HandleRemoteEvent(), CLibInputKeyboard::KeyRepeatTimeout(), CWinEventsTVOS::MessagePump(), CWinEventsAndroid::MessagePump(), CWinEventsIOS::MessagePump(), KODI::WINDOWING::WAYLAND::CWinEventsWayland::MessagePump(), CWinEventsWin10::MessagePump(), KODI::WINDOWING::X11::CWinEventsX11::MessagePump(), CWinEventsWin10::MessagePush(), CAndroidMouse::MouseButton(), CAndroidMouse::MouseMove(), CAndroidMouse::MouseWheel(), CLibInputKeyboard::NotifyKeyComposingEvent(), CWinEventsWin10::OnVisibilityChanged(), CWinEventsWin10::OnWindowActivationChanged(), CLibInputPointer::ProcessAxis(), CLibInputPointer::ProcessButton(), CLirc::ProcessCode(), CInputManager::ProcessEventServer(), CLibInputKeyboard::ProcessKey(), KODI::WINDOWING::X11::CWinEventsX11::ProcessKey(), CLibInputPointer::ProcessMotion(), CLibInputPointer::ProcessMotionAbsolute(), CGenericTouchActionHandler::sendEvent(), and CWinEventsWin32::WndProc().
GetBinaryAddonCache()
ADDON::CBinaryAddonCache & CServiceBroker::GetBinaryAddonCache () static
References g_application.
Referenced by KODI::GAME::CGameUtils::GetGameClients(), KODI::GAME::CGameUtils::GetGameExtensions(), KODI::GAME::CGameClient::GetRunningInstance(), and KODI::GAME::CGameUtils::HasGameExtension().
GetBinaryAddonManager()
ADDON::CBinaryAddonManager & CServiceBroker::GetBinaryAddonManager () static
References g_application.
Referenced by ADDON::CAddonDll::GetRunningInstance(), ADDON::IAddonInstanceHandler::IAddonInstanceHandler(), and ADDON::IAddonInstanceHandler::~IAddonInstanceHandler().
GetContextMenuManager()
CContextMenuManager & CServiceBroker::GetContextMenuManager () static
References g_application.
Referenced by PVR::CGUIDialogPVRItemsViewBase::ContextMenu(), CProfileManager::FinalizeLoadProfile(), CONTEXTMENU::HasAnyMenuItemsFor(), CGUIDialogVideoInfo::ManageVideoItem(), CGUIMediaWindow::OnPopupMenu(), CProfileManager::PrepareLoadProfile(), and CONTEXTMENU::ShowFor().
GetCPUInfo()
std::shared_ptr< CCPUInfo > CServiceBroker::GetCPUInfo () static
References g_serviceBroker.
Referenced by CSysInfoJob::DoWork(), CGUIWindowSystemInfo::FrameMove(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetInt(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), CSysInfo::GetManufacturerName(), CSysInfo::GetModelName(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetSystemHeatInfo(), CMatrixGL::MultMatrixf(), DXVA::CDecoder::Open(), CDVDVideoCodecDRMPRIME::Open(), CDVDVideoCodecFFmpeg::Open(), PPCPUFlags(), CApplication::PrintStartupLog(), CGUIWindowDebugInfo::Process(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and CRendererShaders::CRenderBufferImpl::UploadFromGPU().
GetDatabaseManager()
CDatabaseManager & CServiceBroker::GetDatabaseManager () static
References g_application.
Referenced by CProfileManager::LoadProfile(), CDatabase::Open(), and CLangInfo::SetLanguage().
GetDataCacheCore()
CDataCacheCore & CServiceBroker::GetDataCacheCore () static
References g_application.
Referenced by CVideoPlayer::CloseDemuxer(), CExternalPlayer::CloseFile(), PAPlayer::CloseFile(), CVideoPlayer::CloseFile(), UPNP::CUPnPPlayer::CloseFile(), CVideoPlayer::CVideoPlayer(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), PVR::CPVRPlaybackState::GetChannelPlaybackTime(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetContentRanges(), CDataCacheCore::GetInstance(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), PVR::CPVRPlaybackState::GetPlaybackTime(), CStereoscopicsManager::GetVideoStereoMode(), CVideoPlayer::HandleMessages(), CSeekHandler::InProgress(), CApplicationPlayer::IsRenderingGuiLayer(), CApplicationPlayer::IsRenderingVideoLayer(), KODI::RETRO::CRetroPlayer::OpenFile(), CVideoPlayer::OpenStream(), CVideoPlayer::OpenVideoStream(), PAPlayer::PAPlayer(), PVR::CPVRGUIActionsPlayback::SeekBackward(), PVR::CPVRGUIActionsPlayback::SeekForward(), CVideoPlayer::SetSubtitleVisibleInternal(), CSelectionStreams::Update(), CGUIInfoManager::UpdateAVInfo(), PAPlayer::UpdateGUIData(), CVideoPlayer::UpdatePlayState(), and PVR::CPVRGUITimesInfo::UpdateTimeshiftData().
GetDecoderFilterManager()
CDecoderFilterManager * CServiceBroker::GetDecoderFilterManager () static
References g_serviceBroker.
Referenced by CDVDVideoCodecAndroidMediaCodec::Open().
GetDetectDVDMedia()
static MEDIA_DETECT::CDetectDVDMedia & CServiceBroker::GetDetectDVDMedia () static
GetEventLog()
CEventLog * CServiceBroker::GetEventLog () static
References g_serviceBroker.
Referenced by PVR::CPVRClient::cb_recording_notification(), ADDON::CAddonDll::CheckAPIVersion(), ADDON::CAddonMgr::DisableAddon(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::DoWork(), PVR::CPVREventLogJob::DoWork(), ADDON::CAddonMgr::EnableSingle(), CGUIWindowEventLog::GetContextButtons(), XFILE::CEventsDirectory::GetDirectory(), CMusicDatabase::ImportSongHistory(), ADDON::CAddonInstaller::InstallFromZip(), KODI::GAME::CGameSettings::LoginToRA(), CGUIWindowEventLog::OnDelete(), CGUIWindowEventLog::OnExecute(), ADDON::CRepositoryUpdater::OnJobComplete(), CGUIWindowEventLog::OnMessage(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::ReportInstallError(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), CAlarmClock::Start(), CAlarmClock::Stop(), MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseAlbumInfo(), and MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo().
GetExtsMimeSupportList()
ADDONS::CExtsMimeSupportList & CServiceBroker::GetExtsMimeSupportList () static
References g_application.
Referenced by CFileExtensionProvider::CanOperateExtension(), XFILE::CFileDirectoryFactory::Create(), CodecFactory::CreateCodec(), CodecFactory::CreateCodecDemux(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), ImageFactory::CreateLoaderFromMimeType(), CPictureInfoTag::Load(), CFileExtensionProvider::SetAddonExtensions(), and CGUIDialogAddonInfo::ShowSupportList().
GetFavouritesService()
CFavouritesService & CServiceBroker::GetFavouritesService () static
References g_application.
Referenced by JSONRPC::CFavouritesOperations::AddFavourite(), CGUIWindowFavourites::CGUIWindowFavourites(), anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::ClearFavourites(), CONTEXTMENU::CAddRemoveFavourite::Execute(), CONTEXTMENU::CFavouriteContextMenuAction::Execute(), CProfileManager::FinalizeLoadProfile(), XFILE::CFavouritesDirectory::GetDirectory(), JSONRPC::CFavouritesOperations::GetFavourites(), CONTEXTMENU::CAddRemoveFavourite::GetLabel(), CGUIPassword::IsItemUnlocked(), MasterMode(), CGUIWindowFavourites::MoveItem(), CGUIWindowFavourites::OnAction(), CDirectoryProvider::OnClick(), CGUIDialogContextMenu::OnContextButton(), CDirectoryProvider::OnInfo(), CDirectoryProvider::OnPlay(), CGUIWindowFileManager::OnPopupMenu(), CGUIWindowFavourites::OnSelect(), CGUIWindowFavourites::RemoveItem(), CDirectoryProvider::Reset(), anonymous_namespace{ContextMenus.cpp}::ResolveFavouriteItem(), FAVOURITES_UTILS::ShouldEnableMoveItems(), CGUIDialogLockSettings::ShowAndGetLock(), CDirectoryProvider::UpdateURL(), and CGUIWindowFavourites::~CGUIWindowFavourites().
GetFileExtensionProvider()
CFileExtensionProvider & CServiceBroker::GetFileExtensionProvider () static
References g_application.
Referenced by MUSIC_INFO::CMusicInfoScanner::AddLocalArtwork(), KODI::VIDEO::CVideoInfoScanner::AddLocalItemArtwork(), CGUIDialogVideoManagerExtras::AddVideoExtra(), KODI::VIDEO::CVideoInfoScanner::AddVideoExtras(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), MUSIC_INFO::CMusicInfoScanner::CountFilesRecursively(), MUSIC_INFO::CMusicInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::DoScan(), CGUIMultiImage::CMultiImageJob::DoWork(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), ADDON::CAddonSettings::FileEnumSettingOptionsFiller(), JSONRPC::CFileOperations::FillFileItemList(), CFileItemList::FilterCueItems(), KODI::VIDEO::UTILS::FindTrailer(), JSONRPC::CFileOperations::GetDirectory(), CGUIViewStateWindowMusic::GetExtensions(), CGUIViewStateWindowPictures::GetExtensions(), CGUIViewStateWindowVideo::GetExtensions(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::GetLocalArt(), KODI::ART::GetLocalFanart(), CGUIControlButtonSetting::GetPath(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), XBMCAddon::xbmc::getSupportedMedia(), URIUtils::HasParentInHostname(), ADDON::CAddonSettings::InitializeFromOldSettingPath(), KODI::MUSIC::IsAudio(), KODI::VIDEO::IsDiscStub(), CFileItem::IsFileFolder(), IsPathToMedia(), IsPathToThumbnail(), CUtil::IsPicture(), KODI::VIDEO::IsSubtitle(), KODI::VIDEO::IsVideo(), CPictureFolderImageFileLoader::Load(), CApplication::OnApplicationMessage(), UPNP::CUPnPServer::OnBrowseDirectChildren(), CGUIDialogMusicInfo::OnGetArt(), CGUIWindowVideoBase::OnItemInfo(), CPictureThumbLoader::ProcessFoldersAndArchives(), URIUtils::RemoveExtension(), CUtil::ScanForExternalAudio(), CUtil::ScanForExternalSubtitles(), CGUIDialogFileBrowser::ShowAndGetImage(), CGUIDialogFileBrowser::ShowAndGetImageList(), CFileItemList::StackFolders(), TEST(), TEST(), and TEST().
GetGameControllerManager()
GAME::CControllerManager & CServiceBroker::GetGameControllerManager () static
References g_application.
Referenced by KODI::JOYSTICK::CButtonMapping::CButtonMapping(), KODI::JOYSTICK::CScalarFeature::CScalarFeature(), and KODI::JOYSTICK::CRumbleGenerator::GetMotors().
GetGameRenderManager()
KODI::RETRO::CGUIGameRenderManager & CServiceBroker::GetGameRenderManager () static
References g_application.
Referenced by KODI::GAME::CDialogInGameSaves::InitSavedGames(), KODI::GAME::CDialogInGameSaves::OnDelete(), KODI::GAME::CGUIAgentWindow::OnInitWindow(), KODI::GAME::CGUIControllerWindow::OnInitWindow(), KODI::GAME::CGUIPortWindow::OnInitWindow(), KODI::GAME::CDialogInGameSaves::OnLoad(), KODI::GAME::CDialogGameAdvancedSettings::OnMessage(), KODI::GAME::CDialogInGameSaves::OnNewSave(), KODI::GAME::CDialogInGameSaves::OnOverwrite(), KODI::RETRO::CGUIGameControl::RegisterControl(), KODI::GAME::CDialogGameVideoSelect::RegisterDialog(), and KODI::RETRO::CGameWindowFullScreen::RegisterWindow().
GetGameServices()
GAME::CGameServices & CServiceBroker::GetGameServices () static
References g_application.
Referenced by KODI::GAME::CGUIGameController::ActivateController(), ControllerFeatureReplacer(), KODI::RETRO::CReversiblePlayback::CReversiblePlayback(), KODI::GAME::CGUIAgentControllerList::Deinitialize(), KODI::GAME::CGUIGameController::DoProcess(), KODI::GAME::CGameClientDevice::GetController(), KODI::GAME::CGameClientInput::GetControllers(), KODI::GAME::CGameClientInGameSaves::GetPath(), KODI::GAME::CGUIGameControllerList::GetPortAddress(), KODI::GAME::CGUIAgentControllerList::Initialize(), KODI::GAME::CGameClient::Initialize(), KODI::GAME::CDialogGameOSD::OnAction(), KODI::GAME::CGUIAgentControllerList::OnControllerSelect(), KODI::GAME::CDialogGameOSD::OnDeinitWindow(), KODI::JOYSTICK::CJoystickEasterEgg::OnFinish(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), KODI::GAME::CGUIAgentControllerList::Refresh(), KODI::GAME::CGUIControllerList::RefreshControllers(), KODI::GAME::CGUIGameControllerList::UpdateInfo(), KODI::RETRO::CReversiblePlayback::UpdateMemoryStream(), KODI::GAME::CGUIGameControllerList::UpdatePort(), and KODI::RETRO::CReversiblePlayback::~CReversiblePlayback().
GetGUI()
CGUIComponent * CServiceBroker::GetGUI () static
References g_serviceBroker.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonDeleteGroup(), anonymous_namespace{GUIBuiltins.cpp}::ActivateAndFocus(), PVR::CGUIWindowPVRProvidersBase::ActivateChannelsWindow(), PVR::CGUIWindowPVRProvidersBase::ActivateRecordingsWindow(), CApplicationPowerHandling::ActivateScreenSaver(), anonymous_namespace{GUIBuiltins.cpp}::ActivateWindow(), PVR::CPVRRadioRDSInfoTag::Info::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), CMediaManager::AddAutoSource(), XBMCAddon::xbmcgui::ControlFadeLabel::addLabel(), CGUIDialogVideoManagerVersions::AddVideoVersion(), CGUITexture::AllocResources(), XBMCAddon::xbmcgui::WindowXML::AllocResources(), ADDON::CGUIAddonWindow::AllocResources(), KODI::GAME::CDialogGameVolume::Announce(), CGUIPlayerAnnouncementHandler::Announce(), CGUISourcesAnnouncementHandler::Announce(), CGUIWindowHome::Announce(), PVR::CPVRGUIActionsTimers::AnnounceReminder(), CGraphicContext::ApplyVideoResolution(), CGUIDialogAddonInfo::AskForVersion(), CZeroconfBrowserAvahi::browseCallback(), anonymous_namespace{ContextMenus.cpp}::CanQueue(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CanQueue(), CScreenshotSurfaceWindows::Capture(), CScreenshotSurfaceGL::Capture(), CScreenshotSurfaceGLES::Capture(), CFadeEffect::CFadeEffect(), CGUIDialogCache::CGUIDialogCache(), CGUIViewStateFromItems::CGUIViewStateFromItems(), CGUIViewStateLibrary::CGUIViewStateLibrary(), ChangeSortMethod(), ChangeViewMode(), PVR::CPVRGUIActionsPlayback::CheckAndSwitchToFullscreen(), ADDON::CAddonDll::CheckAPIVersion(), CInertialScrollingHandler::CheckForInertialScrolling(), CGUIPassword::CheckMenuLock(), CApplicationPowerHandling::CheckScreenSaverAndDPMS(), CGUIPassword::CheckSettingLevelLock(), CApplicationPowerHandling::CheckShutdown(), anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType(), CGUIViewState::ChooseSortMethod(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::ChooseStackItemPartNumber(), CGUIDialogVideoManagerVersions::ChooseVideoAndConvertToVideoVersion(), CGUIDialogVideoManager::ChooseVideoAsset(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideoExtra(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideoVersion(), CTextureCache::CleanAllUnusedImages(), CVideoDatabase::CleanDatabase(), CMusicLibraryQueue::CleanLibrary(), CVideoDatabase::CleanMediaType(), CGUIViewControl::Clear(), CGUIWindowFileManager::ClearFileItems(), CGUIWindowSettingsProfile::ClearListItems(), KODI::PLAYLIST::CPlayListPlayer::ClearPlaylist(), anonymous_namespace{GUIBuiltins.cpp}::ClearProperty(), CZeroconfBrowserAvahi::clientCallback(), ADDON::Interface_GUIWindow::close(), CGUIWindow::Close_Internal(), CGUIDialogVideoManager::CloseAll(), anonymous_namespace{GUIBuiltins.cpp}::CloseDialog(), KODI::RETRO::CRetroPlayer::CloseOSD(), XBMCAddon::xbmcgui::Dialog::colorpicker(), CMusicDatabase::CommitTransaction(), CVideoDatabase::CommitTransaction(), XBMCAddon::xbmcgui::Dialog::contextmenu(), ControlMove(), XBMCAddon::xbmcgui::ControlEdit::Create(), XBMCAddon::xbmcgui::DialogProgress::create(), XBMCAddon::xbmcgui::DialogProgressBG::create(), CAnimation::Create(), CGUIControlFactory::Create(), ADDON::Interface_GUIWindow::create(), INFO::CSkinVariable::CreateFromXML(), CGUIVisualisationControl::DeInitVisualization(), CMusicDatabase::DeleteCDDBInfo(), CGUIFontTTFGL::DeleteHardwareTexture(), CGUIFontTTFGLES::DeleteHardwareTexture(), CFileUtils::DeleteItemWithConfirm(), CProfileManager::DeleteProfile(), CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), ADDON::Interface_GUIWindow::destroy(), CGLTexture::DestroyTextureObject(), CGLESTexture::DestroyTextureObject(), CVideoThumbLoader::DetectAndAddMissingItemData(), CGUIDialogSlider::Display(), XBMCAddon::xbmcgui::Window::dispose(), ADDON::Interface_GUIWindow::do_modal(), CProgressJob::DoModal(), CGUIDialogBusy::DoProcess(), CGUIDialogBusyNoCancel::DoProcess(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), KODI::CDRIP::CCDDARipJob::DoWork(), CImageLoader::DoWork(), CGUIMultiImage::CMultiImageJob::DoWork(), CGetInfoJob::DoWork(), CRefreshInfoJob::DoWork(), CGetSongInfoJob::DoWork(), CAutorunMediaJob::DoWork(), CFileOperationJob::DoWork(), CWeatherJob::DoWork(), CSaveFileState::DoWork(), KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), CGUIDialogSmartPlaylistEditor::EditPlaylist(), CGUIDialogSmartPlaylistRule::EditRule(), PVR::CPVRGUIActionsEPG::EditSavedSearch(), CPartyModeManager::Enable(), XBMCAddon::xbmc::enableNavSounds(), anonymous_namespace{PVRBuiltins.cpp}::EpgGridControl(), CMediaLibraryEvent::Execute(), CONTEXTMENU::CMusicBrowse::Execute(), CONTEXTMENU::CMusicQueue::Execute(), CONTEXTMENU::CVideoBrowse::Execute(), CONTEXTMENU::CVideoQueue::Execute(), CONTEXTMENU::CVideoPlayAndQueue::Execute(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::ExecuteAction(), FAVOURITES_UTILS::anonymous_namespace{FavouritesUtils.cpp}::ExecuteAction(), anonymous_namespace{DirectoryProvider.cpp}::ExecuteAction(), CGUIAction::ExecuteActions(), CInputManager::ExecuteInputAction(), EVENTSERVER::CEventServer::ExecuteNextAction(), PVR::CPVRGUIActionsEPG::ExecuteSavedSearch(), CMusicLibraryQueue::ExportLibrary(), CVideoDatabase::ExportToXML(), CProfileManager::FinalizeLoadProfile(), PVR::CPVRGUIActionsEPG::FindSimilar(), CGUIFontTTFGL::FirstBegin(), CGUIFontTTFGLES::FirstBegin(), CGraphicContext::Flip(), CApplicationPlayer::FrameMove(), CGUIWindowManager::FrameMove(), CSeekHandler::FrameMove(), KODI::RETRO::CGUIPlaybackControl::FrameMove(), CGUIDialogMusicOSD::FrameMove(), CGUIWindowVisualisation::FrameMove(), CGUIDialogPictureInfo::FrameMove(), CGUIWindowSettingsScreenCalibration::FrameMove(), CGUIDialogVideoOSD::FrameMove(), CGUIWindowLoginScreen::FrameMove(), CGUIWindowSystemInfo::FrameMove(), CApplication::FrameMove(), CGUITexture::FreeResources(), XFILE::GenerateGameListing(), XFILE::GenerateMainCategoryListing(), XFILE::GenerateTypeListing(), ADDON::Interface_GUIGeneral::get_current_window_dialog_id(), ADDON::Interface_GUIGeneral::get_current_window_id(), KODI::KEYMAP::CKeyboardActionMap::GetActionID(), JSONRPC::CPlayerOperations::GetActivePlayers(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetBool(), PVR::CPVRGUIActionsChannels::GetChannelGroupMember(), PVR::CPVRGUIActionsChannels::GetChannelNumberInputHandler(), CGUIControlFactory::GetColor(), XBMCAddon::xbmc::getCondVisibility(), XBMCAddon::xbmcgui::getCurrentWindowDialogId(), XBMCAddon::xbmcgui::getCurrentWindowId(), CUtil::GetDefaultFolderThumb(), KODI::GAME::CGUIDialogSelectSavestate::GetDialog(), KODI::GAME::CGUIDialogSelectGameClient::GetDialog(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMultiPathDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectory(), XFILE::CSourcesDirectory::GetDirectory(), CGUIDialogSeekBar::GetEpgEventProgress(), XBMCAddon::xbmc::Player::getGameInfoTag(), XBMCAddon::xbmc::getInfoImage(), XBMCAddon::xbmc::getInfoLabel(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetInt(), JSONRPC::CPlayerOperations::GetItem(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CGUIDialogVideoInfo::GetItemsForTag(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetLabel(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), CWeatherManager::GetLocation(), UPNP::CUPnPRenderer::GetMetadata(), CGUIDialogVideoInfo::GetMoviesForSet(), XBMCAddon::xbmc::Player::getMusicInfoTag(), CGUIAction::GetNavigation(), ADDON::Interface_GUIWindow::GetNextAvailableWindowId(), XBMCAddon::xbmcgui::Window::getNextAvailableWindowId(), KODI::PLAYLIST::CPlayListPlayer::GetNextItemIdx(), KODI::RETRO::CGameWindowFullScreen::GetOSD(), CGUIWindowFullScreen::GetOSD(), CGUIDialogSeekBar::GetProgress(), JSONRPC::CGUIOperations::GetPropertyValue(), anonymous_namespace{PVRGUIActionsEPG.cpp}::GetSearchWindow(), CGUIWindowSettingsProfile::GetSelectedItem(), CGUIViewControl::GetSelectedItem(), CGUIDialogVideoInfo::GetSetForMovie(), CGUIViewStateWindowPrograms::GetSources(), CStereoscopicsManager::GetStereoModeByUserChoice(), JSONRPC::CGUIOperations::GetStereoModeObjectFromGuiMode(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::GetTargetWindowID(), XBMCAddon::xbmcgui::ControlEdit::getText(), CGUIDialogSeekBar::GetTimeshiftProgress(), XBMCAddon::xbmc::Player::getVideoInfoTag(), CAutoSwitch::GetView(), CGUIViewState::GetViewState(), KODI::GUILIB::GUIINFO::anonymous_namespace{GUIInfoHelper.cpp}::GetWindowWithCondition(), CInputCodingTableBasePY::GetWordListPage(), KODI::GAME::CDialogGameSaves::HandleCaption(), CAppInboundProtocol::HandleEvents(), KODI::GAME::CDialogGameSaves::HandleGameClient(), CInputManager::HandleKey(), CGUIAction::HasActionsMeetingCondition(), PVR::CPVRGUIActionsChannels::HideChannel(), PVR::CPVRGUIChannelNavigator::HideInfo(), CVideoDatabase::ImportFromXML(), CMusicDatabase::ImportFromXML(), CMusicLibraryQueue::ImportLibrary(), anonymous_namespace{AddonSettings.cpp}::InfoBool(), TVOSLibInputHandler::init, CApplication::Initialize(), CGUIWindow::Initialize(), KODI::PLAYLIST::CPlayListPlayer::Insert(), KODI::GAME::CGameClientProperties::InstallDependencies(), CGUIWindowAddonBrowser::InstallFromZip(), CGUIWindow::IsActive(), CGUIPassword::IsDatabasePathUnlocked(), CApplication::IsFullScreen(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), CContextMenuItem::IsVisible(), CONTEXTMENU::CVideoPlayAndQueue::IsVisible(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::ItemLabelNeedsUpdate(), CGUIKeyboardFactory::keyTypedCB(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::LabelNeedsUpdate(), CGUIDialogVideoInfo::LinkMovieToTvShow(), CGUIWindow::Load(), CApplicationSkinHandling::LoadCustomWindows(), CGUIMultiImage::LoadDirectory(), CGUIListItemLayout::LoadLayout(), CGUIWindowMusicBase::LoadPlayList(), CGUIWindowPictures::LoadPlayList(), CProfileManager::LoadProfile(), CApplicationSkinHandling::LoadSkin(), ADDON::CSkinInfo::LoadTimers(), XFILE::CLibraryDirectory::LoadXML(), CGUIPassword::LockSource(), CGUIPassword::LockSources(), CProfileManager::LogOff(), CMusicDatabase::LookupCDDBInfo(), CGUIDialogVideoManagerExtras::ManageVideoExtras(), CGUIDialogVideoInfo::ManageVideoItemArtwork(), CGUIDialogVideoManagerVersions::ManageVideoVersions(), CBaseRenderer::MarkDirty(), MasterMode(), CWinEventsAndroid::MessagePump(), CWinEventsWin10::MessagePump(), KODI::WINDOWING::X11::CWinEventsX11::MessagePump(), XBMCAddon::xbmcgui::Dialog::multiselect(), CGUIWindow::NeedLoad(), ADDON::Interface_GUIDialogProgress::new_dialog(), ADDON::Interface_GUIDialogExtendedProgress::new_dialog(), CGUIDialogSmartPlaylistEditor::NewPlaylist(), JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CApplication::OnAction(), XBMCAddon::xbmcgui::WindowDialogMixin::OnAction(), KODI::RETRO::CGameWindowFullScreen::OnAction(), CGUIWindowMusicBase::OnAction(), CGUIWindowMusicPlayList::OnAction(), CGUIWindowVisualisation::OnAction(), CGUIDialogPictureInfo::OnAction(), CGUIWindowSlideShow::OnAction(), PVR::CPVRGUIActionListener::OnAction(), CGUIWindowSettingsScreenCalibration::OnAction(), CPlayerController::OnAction(), CGUIWindowFullScreen::OnAction(), CGUIWindowVideoBase::OnAction(), CGUIWindowVideoPlaylist::OnAction(), CGUIWindowHome::OnAction(), CGUIDialogVideoBookmarks::OnAddBookmark(), CGUIDialogVideoBookmarks::OnAddEpisodeBookmark(), CApplication::OnApplicationMessage(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CApplicationPlayerCallback::OnAVChange(), CApplicationPlayerCallback::OnAVStarted(), CGUIWindow::OnBack(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIControlColorButtonSetting::OnClick(), CGUIControlListSetting::OnClick(), CGUIMediaWindow::OnClick(), PVR::CGUIDialogPVRChannelManager::OnClickButtonGroupManager(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRefreshChannelLogos(), CGUIDialogContextMenu::OnContextButton(), PVR::CGUIDialogPVRChannelManager::OnContextButton(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), PVR::CGUIWindowPVRGuideBase::OnContextButtonNavigate(), XBMCAddon::xbmcgui::Window::OnDeinitWindow(), KODI::RETRO::CGameWindowFullScreen::OnDeinitWindow(), KODI::GAME::CDialogGameVolume::OnDeinitWindow(), CGUIDialog::OnDeinitWindow(), XBMCAddon::xbmcgui::WindowDialog::OnDeinitWindow(), XBMCAddon::xbmcgui::WindowXMLDialog::OnDeinitWindow(), CGUIWindowSlideShow::OnDeinitWindow(), PVR::CGUIWindowPVRGuideBase::OnDeinitWindow(), CGUIWindowStartup::OnDeinitWindow(), CGUIWindowVideoNav::OnDeleteItem(), KODI::GAME::CDialogGameVideoSelect::OnDescriptionChange(), PERIPHERALS::CPeripherals::OnDeviceChanged(), DX::DeviceResources::OnDeviceLost(), DX::DeviceResources::OnDeviceRestored(), OnDirectoryScanned(), KODI::VIDEO::OnDirectoryScanned(), CGUIDialogSubtitles::OnDownloadComplete(), CPythonInvoker::onError(), CGUIWindowAddonBrowser::OnEvent(), CGUIWindowAddonBrowser::OnEvent(), CInputManager::OnEvent(), CGUIDialogSmartPlaylistRule::OnField(), KODI::JOYSTICK::CJoystickEasterEgg::OnFinish(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSongInfo::OnGetArt(), CGUIDialogSmartPlaylistEditor::OnGroupBy(), CGUIWindow::OnInitWindow(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), KODI::GAME::CDialogGameVolume::OnInitWindow(), CGUIDialogVisualisationPresetList::OnInitWindow(), CGUIWindowMusicBase::OnInitWindow(), CGUIMediaWindow::OnInitWindow(), CGUIWindowPictures::OnItemInfo(), ADDON::CAddonInstaller::OnJobComplete(), ADDON::CAddonInstaller::OnJobProgress(), CInputManager::OnKey(), CGUIDialogSmartPlaylistEditor::OnLimit(), CPictureThumbLoader::OnLoaderFinish(), CGUIWindowAddonBrowser::OnMessage(), CApplication::OnMessage(), KODI::GAME::CGUIWindowGames::OnMessage(), GUIFontManager::OnMessage(), CGUIDialogMusicInfo::OnMessage(), CGUIDialogMusicOSD::OnMessage(), CGUIDialogSongInfo::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowVisualisation::OnMessage(), CGUIWindowPictures::OnMessage(), KODI::PLAYLIST::CPlayListPlayer::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIDialogVideoOSD::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIWindowSystemInfo::OnMessage(), CGUIVideoControl::OnMouseEvent(), CGUIWindowVisualisation::OnMouseEvent(), UPNP::CUPnPRenderer::OnNext(), CGUIDialogLibExportSettings::OnOK(), CGUIDialogSmartPlaylistRule::OnOperator(), CGUIDialogSmartPlaylistEditor::OnOrder(), CXBMCApp::onPause(), UPNP::CUPnPRenderer::OnPause(), UPNP::CUPnPRenderer::OnPlay(), CApplicationPlayerCallback::OnPlayBackEnded(), CApplicationPlayerCallback::OnPlayBackError(), CApplicationPlayerCallback::OnPlayBackPaused(), CApplicationPlayerCallback::OnPlayBackResumed(), CApplicationPlayerCallback::OnPlayBackSeek(), CApplicationPlayerCallback::OnPlayBackSpeedChanged(), CApplicationPlayerCallback::OnPlayBackStarted(), CApplicationPlayerCallback::OnPlayBackStopped(), CGUIWindowMusicBase::OnPlayMedia(), CGUIWindowFileManager::OnPopupMenu(), ADDON::CSkinInfo::OnPostInstall(), ADDON::CUISoundsResource::OnPostInstall(), CGUIWindowPictures::OnPrepareFileItems(), UPNP::CUPnPRenderer::OnPrevious(), CApplicationPlayerCallback::OnQueueNextItem(), CGUIWindowMusicBase::OnRemoveSource(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), CGUIWindowVideoBase::OnSearch(), CGUIDialogVideoInfo::OnSearch(), UPNP::CUPnPRenderer::OnSetAVTransportURI(), UPNP::CUPnPRenderer::OnSetNextAVTransportURI(), ADDON::CAddonSystemSettings::OnSettingAction(), CApplicationSettingsHandling::OnSettingAction(), PERIPHERALS::CPeripherals::OnSettingAction(), CGUIDialogLockSettings::OnSettingAction(), PVR::CPVRGUIActionListener::OnSettingAction(), CGUIDialogContentSettings::OnSettingAction(), CGUIDialogSubtitleSettings::OnSettingAction(), CGUIDialogVideoSettings::OnSettingAction(), CApplicationSkinHandling::OnSettingChanged(), CGUIDialogMediaFilter::OnSettingChanged(), CWeatherManager::OnSettingChanged(), CGUIDialogVideoInfo::OnSetUserrating(), CGUIWindowPictures::OnShowPictureRecursive(), CPowerManager::OnSleep(), CGUIWindowFileManager::OnStart(), UPNP::CUPnPRenderer::OnStop(), CStereoscopicsManager::OnStreamChange(), ADDON::CRepositoryUpdater::OnTimeout(), CGUIDialogSmartPlaylistEditor::OnType(), CGUIWindowVideoBase::OnUnAssignContent(), UPNP::CUPnPServer::OnUpdateObject(), CPowerManager::OnWake(), ADDON::Interface_GUIDialogContextMenu::open(), ADDON::Interface_GUIDialogSelect::open(), ADDON::Interface_GUIDialogTextViewer::open(), CGUIDialog::Open_Internal(), ADDON::Interface_GUIDialogSelect::open_multi_select(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), OpenDefaultSettings(), PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream(), KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream(), KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream(), KODI::RETRO::CRetroPlayer::OpenOSD(), CVideoPlayer::OpenVideoStream(), KODI::GUILIB::GUIINFO::CGUIInfoBool::Parse(), KODI::GUILIB::GUIINFO::CGUIInfoColor::Parse(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::Parse(), CGUITextLayout::ParseText(), CGUIDialogVideoInfo::Play(), KODI::PLAYLIST::CPlayListPlayer::Play(), CApplication::PlaybackCleanup(), PVR::CPVRGUIActionsPlayback::PlayEpgTag(), PlayerControl(), CApplication::PlayFile(), KODI::PLAYLIST::CPlayListPlayer::PlayNext(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), PVR::CPVRGUIActionsPlayback::PlayRecording(), XBMCAddon::xbmc::playSFX(), CGUIDialogVideoInfo::PlayTrailer(), CGUIDialogContextMenu::PositionAtCurrentFocus(), CPowerManager::Powerdown(), CGUIWindowManager::PreviousWindow(), MUSIC_INFO::CMusicInfoScanner::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), ADDON::CAddonStatusHandler::Process(), CApplication::Process(), CExternalPlayer::Process(), CGUIDialogCache::Process(), KODI::GAME::CControllerInstaller::Process(), KODI::GAME::CControllerSelect::Process(), KODI::JOYSTICK::CGUIDialogNewJoystick::Process(), PVR::CPVRGUIInfo::Process(), PVR::CPVRGUIProgressHandler::Process(), XBMCAddon::xbmcgui::WindowXML::Process(), CGUISliderControl::Process(), CGUIVisualisationControl::Process(), CGUIWindowDebugInfo::Process(), CGUIWindowSlideShow::Process(), CMediaManager::ProcessEvents(), CVideoPlayerAudioID3::ProcessID3v1(), CVideoPlayerAudioID3::ProcessID3v2(), CGUIMediaWindow::ProcessRenderLoop(), CGUIDialog::ProcessRenderLoop(), PVR::CPVRGUIActionsClients::ProcessSettingsMenuHooks(), CApplication::ProcessSlow(), CDVDRadioRDSData::ProcessUECP(), ProgressDialogHelper::ProgressDialogHelper(), PVR::CGUIDialogPVRChannelManager::PromptAndSaveList(), CGenericTouchActionHandler::QuerySupportedGestures(), MUSIC_UTILS::QueueItem(), CPowerManager::Reboot(), CMusicLibraryQueue::Refresh(), CVideoLibraryQueue::Refresh(), Refresh(), CGUIWindowMusicBase::RefreshContent(), CAirTunesServer::RefreshCoverArt(), CGUIDialogMusicInfo::RefreshInfo(), KODI::GAME::CDialogGameVideoSelect::RefreshList(), CAirTunesServer::RefreshMetadata(), CApplicationSkinHandling::ReloadSkin(), KODI::PLAYLIST::CPlayListPlayer::Remove(), CMediaManager::RemoveAutoSource(), CGUIPassword::RemoveSourceLocks(), ADDON::CGUIAddonWindow::Render(), CApplication::Render(), XBMCAddon::xbmcgui::ControlList::reset(), XBMCAddon::xbmcgui::ControlFadeLabel::reset(), XBMCAddon::xbmcgui::ControlTextBox::reset(), KODI::PLAYLIST::CPlayListPlayer::Reset(), CSkinSettings::Reset(), ADDON::Interface_GUIControlSettingsSlider::reset(), ADDON::Interface_GUIControlSlider::reset(), ADDON::Interface_GUIControlSpin::reset(), ADDON::Interface_GUIControlTextBox::reset(), CGUIWindowSettingsScreenCalibration::ResetCalibration(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), CDVDRadioRDSData::ResetRDSCache(), CGUIWindowSlideShow::RunSlideShow(), CGUIWindowSlideShow::RunSlideShow(), CGUIDialogAddonSettings::SaveAndClose(), PVR::CGUIDialogPVRChannelManager::SaveList(), CGUIViewStateFromItems::SaveViewState(), CGUIViewStateLibrary::SaveViewState(), SearchVideoLibrary(), SeekPercentage(), anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::Select(), XBMCAddon::xbmcgui::Dialog::select(), CGUIWindowAddonBrowser::SelectAddonID(), SelectBool(), PVR::CPVRGUIChannelNavigator::SelectChannel(), XBMCAddon::xbmcgui::ControlList::selectItem(), anonymous_namespace{ContextMenus.cpp}::SelectNextItem(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::SelectNextItem(), JSONRPC::CInputOperations::SendAction(), CGUISliderControl::SendClick(), SendClick(), XBMCAddon::xbmcgui::ControlList::sendLabelBind(), CEventLog::SendMessage(), SendMessage(), JSONRPC::CInputOperations::SendText(), CPartyModeManager::SendUpdateMessage(), CGUIControl::SendWindowMessage(), ADDON::Interface_GUIControlLabel::set_label(), ADDON::Interface_GUIControlSettingsSlider::set_text(), ADDON::Interface_GUIControlSpin::set_text(), ADDON::Interface_GUIControlTextBox::set_text(), CGUIBaseContainer::SetAutoScrolling(), CGUITextBox::SetAutoScrolling(), CGUITextBox::SetAutoScrolling(), SetColor(), CGUIBaseContainer::SetContainerMoving(), CGUIWindowSystemInfo::SetControlLabel(), CGUIViewControl::SetCurrentView(), SetDefaultAddon(), CGUIDialogVideoManagerVersions::SetDefaultVideoVersion(), CGUIControl::SetEnableCondition(), XBMCAddon::xbmcgui::Window::setFocus(), SetFocus(), CGUIViewControl::SetFocused(), XBMCAddon::xbmcgui::Window::setFocusId(), CWeatherJob::SetFromProperties(), SetHidden(), CGUIWindow::SetInitialVisibility(), XBMCAddon::xbmcgui::ControlLabel::setLabel(), XBMCAddon::xbmcgui::ControlEdit::setLabel(), SetLocation(), CGraphicContext::SetMediaDir(), CGUIDialogPictureInfo::SetPicture(), PVR::CPVRGUIChannelNavigator::SetPlayingChannel(), ADDON::SetProgressIndicator(), anonymous_namespace{GUIBuiltins.cpp}::SetProperty(), KODI::PLAYLIST::CPlayListPlayer::SetRepeat(), CGUIViewControl::SetSelectedItem(), KODI::PLAYLIST::CPlayListPlayer::SetShuffle(), SetSortMethod(), KODI::RETRO::CRetroPlayer::SetSpeed(), XBMCAddon::xbmcgui::ControlEdit::setText(), XBMCAddon::xbmcgui::ControlTextBox::setText(), CDisplaySettings::SettingOptionsPreferredStereoscopicViewModesFiller(), CDisplaySettings::SettingOptionsStereoscopicModesFiller(), CGUIRadioButtonControl::SetToggleSelect(), CGUIToggleButtonControl::SetToggleSelect(), CGUIDialogVideoInfo::SetUserrating(), CGraphicContext::SetVideoResolutionInternal(), SetViewMode(), SetVisible(), CGUIStaticItem::SetVisibleCondition(), CGUIControl::SetVisibleCondition(), XBMCAddon::xbmcgui::Window::setWindow(), ShiftPage(), FAVOURITES_UTILS::ShouldEnableMoveItems(), CGUIDialogInfoProviderSettings::Show(), CGUIDialogInfoProviderSettings::Show(), CGUIDialogLibExportSettings::Show(), CGUIDialogContextMenu::Show(), Show(), PERIPHERALS::CGUIDialogPeripherals::Show(), ADDON::Interface_GUIWindow::show(), ADDON::CGUIAddonWindowDialog::Show_Internal(), CGUIDialogMediaSource::ShowAndAddMediaSource(), CGUIDialogMediaFilter::ShowAndEditMediaFilter(), CGUIDialogMediaSource::ShowAndEditMediaSource(), CGUIDialogContextMenu::ShowAndGetChoice(), CGUIDialogNumeric::ShowAndGetDate(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFileList(), CGUIDialogFileBrowser::ShowAndGetImage(), CGUIDialogKeyboardGeneric::ShowAndGetInput(), CGUIDialogOK::ShowAndGetInput(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogOK::ShowAndGetInput(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogSlider::ShowAndGetInput(), CGUIDialogPlayEject::ShowAndGetInput(), CGUIKeyboardFactory::ShowAndGetInput(), CGUIDialogNumeric::ShowAndGetIPAddress(), CGUIDialogLockSettings::ShowAndGetLock(), CGUIDialogNetworkSetup::ShowAndGetNetworkAddress(), CGUIDialogNumeric::ShowAndGetNumber(), CGUIDialogNumeric::ShowAndGetSeconds(), CGUIDialogFileBrowser::ShowAndGetSource(), CGUIDialogNumeric::ShowAndGetTime(), CGUIDialogLockSettings::ShowAndGetUserAndPassword(), CGUIDialogGamepad::ShowAndVerifyInput(), CGUIDialogNumeric::ShowAndVerifyInput(), KODI::JOYSTICK::CGUIDialogNewJoystick::ShowAsync(), PVR::CPVRGUIActionsEPG::ShowChannelEPG(), PVR::CGUIWindowPVRChannelsBase::ShowChannelManager(), KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), CGUIDialogAddonInfo::ShowDependencyList(), PVR::CPVRGUIActionsEPG::ShowEPGInfo(), CGUIDialogMusicInfo::ShowFor(), CGUIDialogSongInfo::ShowFor(), CGUIDialogVideoInfo::ShowFor(), CGUIDialogAddonSettings::ShowForAddon(), CGUIDialogTextViewer::ShowForFile(), CGUIDialogAddonInfo::ShowForItem(), CGUIDialogAddonSettings::ShowForMultipleInstances(), CGUIDialogProfileSettings::ShowForProfile(), CGUIDialogAddonSettings::ShowForSingleInstance(), CEventLog::ShowFullEventLog(), PVR::CGUIWindowPVRChannelsBase::ShowGroupManager(), PVR::CPVRGUIChannelNavigator::ShowInfo(), CGUIWindowVideoBase::ShowInfo(), CGUIWindowPictures::ShowPicture(), CGUIDialogSimpleMenu::ShowPlaySelection(), PVR::CGUIWindowPVRBase::ShowProgressDialog(), PVR::CPVRGUIActionsRecordings::ShowRecordingInfo(), PVR::CPVRGUIActionsRecordings::ShowRecordingSettings(), MUSIC_UTILS::ShowSelectArtTypeDialog(), MUSIC_UTILS::ShowSelectRatingDialog(), CGUIDialogAddonInfo::ShowSupportList(), PVR::CPVRGUIActionsTimers::ShowTimerSettings(), CApplicationVolumeHandling::ShowVolumeBar(), XBMCAddon::xbmc::skinHasImage(), Slideshow(), CNetworkServices::Start(), PVR::CPVRGUIActionsChannels::StartChannelScan(), PVR::CPVRGUIInfo::Stop(), CApplication::Stop(), CApplication::StopPlaying(), XBMCAddon::xbmc::stopSFX(), PVR::CPVRGUIChannelNavigator::SubscribeToShowInfoEventStream(), KODI::PLAYLIST::CPlayListPlayer::Swap(), SwitchLocation(), CGUIDialogContextMenu::SwitchMedia(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), XBMCAddon::xbmcgui::Dialog::textviewer(), ToggleSortDirection(), CGUIDialogMediaFilter::TriggerFilter(), CApplicationSkinHandling::UnloadSkin(), CGUIDialogVideoInfo::Update(), KODI::GUILIB::GUIINFO::CGUIInfoColor::Update(), Update(), CGUIViewControl::UpdateContents(), CGUIWindowFileManager::UpdateControl(), CApplication::UpdateCurrentPlayArt(), CGUIProgressControl::UpdateInfo(), CGUIRangesControl::UpdateInfo(), XBMCAddon::xbmc::Player::updateInfoTag(), CRecentlyAddedJob::UpdateMusic(), CGUIDialogPictureInfo::UpdatePictureInfo(), CXBMCApp::UpdateSessionMetadata(), CGUIDialogSettingsBase::UpdateSettingControl(), ADDON::Interface_Base::UpdateSettingInActiveDialog(), XBMCAddon::xbmcaddon::Addon::UpdateSettingInActiveDialog(), UPNP::CUPnPRenderer::UpdateState(), CRecentlyAddedJob::UpdateTotal(), CGUIVisualisationControl::UpdateTrack(), CRecentlyAddedJob::UpdateVideo(), CGUIViewControl::UpdateViewAsControl(), CGUIViewControl::UpdateViewVisibility(), CGUIMediaWindow::WaitForNetwork(), CGUIMediaWindow::WaitGetDirectoryItems(), CGUIDialogBusy::WaitOnEvent(), CScriptRunner::WaitOnScriptResult(), CApplicationPowerHandling::WakeUpScreenSaver(), XBMCAddon::xbmcgui::Window::Window(), CWinEventsWin32::WndProc(), CVideoLibraryRefreshingJob::Work(), and PVR::CPVRGUIChannelNavigator::~CPVRGUIChannelNavigator().
GetInputManager()
CInputManager & CServiceBroker::GetInputManager () static
References g_application.
Referenced by CGraphicContext::ApplyVideoResolution(), KODI::KEYMAP::CKeymapHandling::CKeymapHandling(), CApplication::CreateGUI(), CBuiltins::Execute(), CGUIDialogMusicOSD::FrameMove(), CGUIDialogVideoOSD::FrameMove(), CApplication::FrameMove(), KODI::KEYMAP::CKeyboardActionMap::GetActionID(), CAppInboundProtocol::HandleEvents(), CBuiltins::HasCommand(), TVOSLibInputHandler::init, KODI::WINDOWING::WAYLAND::CWinSystemWayland::InitWindowSystem(), KODI::GAME::CGUIConfigurationWizard::InstallHooks(), KODI::KEYMAP::CKeymapHandling::LoadKeymaps(), CProfileManager::LoadProfile(), KODI::WINDOWING::X11::CWinEventsX11::MessagePump(), CApplication::OnAction(), KODI::JOYSTICK::CJoystickMonitor::OnAnalogStickMotion(), KODI::JOYSTICK::CJoystickMonitor::OnButtonMotion(), KODI::JOYSTICK::CJoystickMonitor::OnButtonPress(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnEnter(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnLeave(), CGUIWindowFileManager::OnMessage(), CGUIControl::OnMouseOver(), KODI::JOYSTICK::CJoystickMonitor::OnThrottleMotion(), KODI::JOYSTICK::CJoystickMonitor::OnWheelMotion(), CGUIWindowPointer::Process(), KODI::GAME::CGUIConfigurationWizard::RemoveHooks(), CGraphicContext::SetVideoResolutionInternal(), KODI::WINDOWING::X11::CWinSystemX11::SetWindow(), CGUIWindowPointer::UpdateVisibility(), CWinEventsWin32::WndProc(), and KODI::KEYMAP::CKeymapHandling::~CKeymapHandling().
GetJobManager()
std::shared_ptr< CJobManager > CServiceBroker::GetJobManager () static
References g_serviceBroker.
Referenced by anonymous_namespace{PVRGUIActionsTimers.cpp}::AddEventLogEntry(), CGUIWindowHome::AddRecentlyAddedJobs(), ADDON::CAddonInstaller::Cancel(), CJobQueue::CJobPointer::CancelJob(), CGUIMultiImage::CancelLoading(), CGetDirectory::CGetDirectory(), ADDON::CRepositoryUpdater::CheckForUpdates(), CTextureCache::CleanAllUnusedImages(), CTextureCache::CleanTimer(), PAPlayer::CloseFileCB(), PVR::CPVRManager::ConnectionStateChange(), PVR::CPVRClients::ConnectionStateChange(), ADDON::CAddonInstaller::DoInstall(), CGUIWindowMusicNav::GetContextButtons(), CInfoLoader::GetInfo(), PVR::CPVRGUIChannelNavigator::HideInfo(), PVR::CPVRManager::Init(), CApplication::Initialize(), CWin32StorageProvider::Initialize(), CJobQueue::IsProcessing(), CGUIMultiImage::LoadDirectory(), PVR::CPVRClients::OnAddonEvent(), CGUIDialogMusicInfo::OnMessage(), CApplicationPlayerCallback::OnPlayBackStarted(), CGUIWindowFileManager::OnPopupMenu(), CMediaManager::OnStorageAdded(), PAPlayer::OpenFile(), PingResponseWaiter::PingResponseWaiter(), PVR::CPVRGUIActionsRecordings::ProcessDeleteAfterWatch(), CApplication::ProcessSlow(), CZeroconf::PublishService(), CGUILargeTextureManager::QueueImage(), CWakeOnAccess::QueueMACDiscoveryForHost(), PAPlayer::QueueNextFile(), CJobQueue::QueueNextJob(), CGUIDialogMusicInfo::RefreshInfo(), CGUILargeTextureManager::ReleaseImage(), PVR::CPVRClients::RequestRestart(), CDirectoryProvider::Reset(), PVR::CPVRGUIChannelNavigator::SelectChannel(), CGUIDialogMusicInfo::SetItem(), KODI::RETRO::CRetroPlayer::SetPlaybackSpeed(), CGUIDialogSongInfo::SetSong(), PVR::CPVRGUIChannelNavigator::ShowInfo(), CZeroconf::Start(), CApplication::Stop(), PVR::CPVRGUIChannelNavigator::SwitchToCurrentChannel(), CScreenShot::TakeScreenshot(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), PVR::CPVRManager::TriggerPlayChannelOnStartup(), ADDON::CAddonInstaller::UnInstall(), CDirectoryProvider::Update(), MUSIC_UTILS::UpdateArtJob(), PVR::CPVRClients::UpdateClients(), PVR::CPVRTimers::UpdateEntries(), ADDON::CAddonMgr::UpdateLastUsed(), MUSIC_UTILS::UpdateSongRatingJob(), anonymous_namespace{TestJobManager.cpp}::WaitForJobToStartProcessing(), CGUIMediaWindow::WaitGetDirectoryItems(), CWinEventsWin32::WndProc(), CGetDirectory::~CGetDirectory(), PingResponseWaiter::~PingResponseWaiter(), and TestJobManager::~TestJobManager().
GetKeyboardLayoutManager()
std::shared_ptr< KEYBOARD::CKeyboardLayoutManager > CServiceBroker::GetKeyboardLayoutManager () static
References g_serviceBroker.
Referenced by ADDON::Interface_General::change_keyboard_layout(), ADDON::Interface_General::get_keyboard_layout(), CGUIDialogKeyboardGeneric::OnInitWindow(), and KODI::KEYBOARD::CKeyboardLayoutManager::SettingOptionsKeyboardLayoutsFiller().
GetLogging()
CLog & CServiceBroker::GetLogging () static
References g_serviceBroker.
Referenced by CDVDVideoCodecAndroidMediaCodec::AddData(), CWebServer::AddHeader(), CHTTPJsonRpcHandler::appendPostData(), CHTTPPythonHandler::appendPostData(), UPNP::BuildObject(), XBMCController::CallExit, CRendererDXVA::Configure(), CDVDVideoCodecAndroidMediaCodec::ConfigureOutputFormat(), CWebServer::ContentReaderCallback(), CWebServer::ContentReaderFreeCallback(), CApplication::Create(), CEGLImage::CreateImage(), CSetting::CSetting(), CSettingAction::CSettingAction(), CSettingBool::CSettingBool(), CSettingCategory::CSettingCategory(), CSettingDependency::CSettingDependency(), CSettingDependencyCondition::CSettingDependencyCondition(), CSettingGroup::CSettingGroup(), CSettingInt::CSettingInt(), CSettingList::CSettingList(), CSettingNumber::CSettingNumber(), CSettingSection::CSettingSection(), CSettingString::CSettingString(), CSettingUpdate::CSettingUpdate(), debug_callback(), KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), CHTTPPythonWsgiInvoker::executeScript(), CVideoBufferDMA::Export(), ff_avutil_log(), CDVDVideoCodecFFmpeg::FilterOpen(), CDVDAudioCodecAndroidMediaCodec::GetData(), CAESinkAUDIOTRACK::GetDelay(), CLog::GetInstance(), CWebServer::GetLogger(), GetMhdLogger(), UPNP::GetResource(), CSMB::Init(), CAirTunesServer::Initialize(), CAdvancedSettings::Initialize(), CAESinkXAudio::InitializeInternal(), CPlatformWebOS::InitStageTwo(), ISettingControl::ISettingControl(), CWebServer::LogRequest(), CWebServer::LogResponse(), CAdvancedSettings::OnSettingsLoaded(), XFILE::CCurlFile::Open(), CAdvancedSettings::ParseSettingsFile(), DXVA::CEnumeratorHD::ProbeProcessorCaps(), CMediaCodecVideoBuffer::ReleaseOutputBuffer(), DX::DeviceResources::ResizeBuffers(), CAESinkALSA::SelectALSAChannelMap(), CAdvancedSettings::SetDebugMode(), CVideoBufferDMA::SetDimensions(), shairplay_log(), CAESinkALSA::sndLibErrorHandler(), CWebServer::Start(), DXVA::CEnumeratorHD::SupportedConversions(), CAppEnvironment::TearDown(), TEST_F(), TEST_F(), TEST_F(), UPnPLogger(), Testlog::~Testlog(), and TestRegExpLog::~TestRegExpLog().
GetMediaManager()
CMediaManager & CServiceBroker::GetMediaManager () static
References g_application.
Referenced by CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), XBMCAddon::xbmcgui::Dialog::browseMultiple(), XBMCAddon::xbmcgui::Dialog::browseSingle(), FAVOURITES_UTILS::ChooseAndSetNewThumbnail(), PVR::CPVRGUIActionsEPG::ChooseIconForSavedSearch(), CHTTPVfsHandler::CHTTPVfsHandler(), CVideoDatabase::CleanDatabase(), CVideoDatabase::CleanMediaType(), CWIN32Util::CloseTray(), CDVDFactoryInputStream::CreateInputStream(), CDetectDisc::DoWork(), KODI::CDRIP::CCDDARipJob::DoWork(), Eject(), CWIN32Util::EjectTray(), CONTEXTMENU::CEjectDisk::Execute(), CONTEXTMENU::CEjectDrive::Execute(), ExportLibrary(), CGUIDialogPlayEject::FrameMove(), CGUIWindowSystemInfo::FrameMove(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), XFILE::CCDDADirectory::GetDirectory(), XFILE::CSourcesDirectory::GetDirectory(), CUtil::GetDVDDriveIcon(), XBMCAddon::xbmc::getDVDState(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), CGUIControlButtonSetting::GetPath(), XFILE::CVirtualDirectory::GetSources(), ADDON::Interface_GUIDialogFileBrowser::GetVECShares(), CGUIMediaWindow::HaveDiscOrConnection(), CGUIDialogFileBrowser::HaveDiscOrConnection(), CGUIWindowFileManager::HaveDiscOrConnection(), CApplication::Initialize(), CWin32StorageProvider::Initialize(), CStorageProvider::Initialize(), CGUIWindowAddonBrowser::InstallFromZip(), MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load(), CMusicDatabase::LookupCDDBInfo(), CGUIDialogVideoInfo::ManageVideoItemArtwork(), CGUIDialogFileBrowser::OnAction(), CGUIDialogFileBrowser::OnAddNetworkLocation(), CGUIDialogSmartPlaylistRule::OnBrowse(), PVR::CGUIDialogPVRChannelManager::OnClickButtonChannelLogo(), CGUIDialogContextMenu::OnContextButton(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSongInfo::OnGetArt(), CGUIDialogPlayEject::OnInitWindow(), CGUIDialogPlayEject::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIDialogFileBrowser::OnPopupMenu(), CGUIWindowMusicBase::OnRipCD(), CGUIWindowMusicBase::OnRipTrack(), CGUIDialogInfoProviderSettings::OnSettingAction(), CGUIDialogProfileSettings::OnSettingAction(), CGUIDialogLibExportSettings::OnSettingAction(), CDisplaySettings::OnSettingAction(), CMediaSettings::OnSettingAction(), CGUIWindowFileManager::OnSort(), XFILE::CFileCDDA::Open(), CApplication::PlaybackCleanup(), PlayDVD(), CApplication::PlayFile(), CApplication::ProcessSlow(), XFILE::CFileCDDA::Read(), CFileUtils::RemoteAccessAllowed(), XFILE::CDVDDirectory::Resolve(), KODI::CDRIP::CCDDARipper::RipCD(), SetFile(), SetImage(), SetPath(), CGUIDialogFileBrowser::SetSources(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetSource(), CWIN32Util::ToggleTray(), CGUIMediaWindow::Update(), CGUIWindowMusicBase::UpdateButtons(), and CWinEventsWin32::WndProc().
GetNetwork()
CNetworkBase & CServiceBroker::GetNetwork () static
References g_application, and CNetworkBase::GetNetwork().
Referenced by UPNP::CUPnP::CUPnP(), CMACDiscoveryJob::DoWork(), CWeatherJob::DoWork(), PVR::CPVRGUIActionsPowerManagement::EventOccursOnLocalBackend(), CProfileManager::FinalizeLoadProfile(), ADDON::Interface_Network::get_hostname(), ADDON::Interface_Network::get_ip_address(), CSysInfo::GetDeviceName(), CSysInfoJob::GetDNSServers(), CSysInfoJob::GetGatewayAddress(), XBMCAddon::xbmc::getIPAddress(), CSysInfoJob::GetIPAddress(), CSysInfoJob::GetMACAddress(), UPNP::CUPnPRenderer::GetMetadata(), CSysInfoJob::GetNetMask(), CSysInfoJob::GetNetworkLinkState(), CGUIMediaWindow::HaveDiscOrConnection(), CGUIDialogFileBrowser::HaveDiscOrConnection(), CGUIWindowFileManager::HaveDiscOrConnection(), CAirTunesServer::Initialize(), ADDON::Interface_Network::is_local_host(), URIUtils::IsHostOnLAN(), CURL::IsLocalHost(), CProfileManager::LogOff(), CMusicDatabase::LookupCDDBInfo(), CPowerManager::OnWake(), PingResponseWaiter::Ping(), TestNetwork::PingHost(), CProfileManager::PrepareLoadProfile(), CRssReader::Process(), CAirPlayServer::CTCPClient::ProcessRequest(), CUtil::ScanForExternalSubtitles(), CNetworkServices::StartAirPlayServer(), CNetworkServices::StartAirTunesServer(), XBMCAddon::xbmc::startServer(), CAirTunesServer::StartServer(), CNetworkServices::StartWebserver(), NetworkStartWaiter::SuccessWaiting(), CGUIMediaWindow::WaitForNetwork(), ADDON::Interface_Network::wake_on_lan(), WakeOnLAN(), and CWakeOnAccess::WakeUpHost().
GetPeripherals()
PERIPHERALS::CPeripherals & CServiceBroker::GetPeripherals () static
References g_application.
Referenced by KODI::GAME::CGameClientInput::CloseJoystick(), CGUIDialogKaiToast::DoWork(), anonymous_namespace{SettingConditions.cpp}::HasPeripherals(), anonymous_namespace{SettingConditions.cpp}::HasPowerOffFeature(), anonymous_namespace{SettingConditions.cpp}::HasRumbleController(), anonymous_namespace{SettingConditions.cpp}::HasRumbleFeature(), PERIPHERALS::CGUIDialogPeripheralSettings::InitializeSettings(), KODI::GAME::CGUIDialogButtonCapture::InstallHooks(), KODI::GAME::CGUIConfigurationWizard::InstallHooks(), CApplicationVolumeHandling::IsMuted(), KODI::KEYBOARD::CKeyboardStat::LookupSymAndUnicodePeripherals(), CApplicationVolumeHandling::Mute(), KODI::GAME::CGUIDialogButtonCapture::Notify(), KODI::GAME::CGUIConfigurationWizard::Notify(), CApplication::OnAction(), KODI::GAME::CGUIControllerWindow::OnInitWindow(), PERIPHERALS::CGUIDialogPeripheralSettings::OnResetSettings(), PERIPHERALS::CGUIDialogPeripheralSettings::OnSettingChanged(), KODI::RETRO::CRetroPlayer::OpenFile(), CInputManager::ProcessPeripherals(), KODI::GAME::CGUIDialogButtonCapture::RemoveHooks(), KODI::GAME::CGUIConfigurationWizard::RemoveHooks(), KODI::GAME::CGUIControllerList::ResetController(), PERIPHERALS::CGUIDialogPeripheralSettings::Save(), KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), CApplicationVolumeHandling::UnMute(), and CWinEventsWin32::WndProc().
GetPlatform()
CPlatform & CServiceBroker::GetPlatform () static
References g_application.
Referenced by CAESinkALSA::Cleanup(), CAESinkALSA::EnumerateDevice(), CAESinkALSA::EnumerateDevicesEx(), CGUIWindowAddonBrowser::GetStartFolder(), CALSADeviceMonitor::Start(), CALSAHControlMonitor::Start(), CALSADeviceMonitor::Stop(), and CALSAHControlMonitor::Stop().
GetPlayerCoreFactory()
CPlayerCoreFactory & CServiceBroker::GetPlayerCoreFactory () static
References g_application.
Referenced by CONTEXTMENU::CMusicPlayUsing::Execute(), JSONRPC::CPlayerOperations::GetPlayers(), CONTEXTMENU::CMusicPlayUsing::IsVisible(), CONTEXTMENU::CVideoPlayUsing::IsVisible(), UPNP::CMediaController::OnMRAdded(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoPlayActionProcessor::OnPlaySelected(), CGUIWindowFileManager::OnPopupMenu(), JSONRPC::CPlayerOperations::Open(), and UPNP::CMediaController::unregisterRenderer().
GetPlaylistPlayer()
PLAYLIST::CPlayListPlayer & CServiceBroker::GetPlaylistPlayer () static
References g_application.
Referenced by CPartyModeManager::Add(), anonymous_namespace{MusicUtils.cpp}::AddItemToPlayListAndPlay(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::AddItemToPlayListAndPlay(), CPartyModeManager::AddRandomSongs(), CPartyModeManager::AddUserSongs(), CPartyModeManager::AddUserSongs(), CPartyModeManager::Announce(), AnnounceBridge(), CApplication::Cleanup(), CGUIWindowMusicPlayList::ClearPlayList(), CGUIWindowVideoPlaylist::ClearPlayList(), ClearPlaylist(), CApplication::Create(), MUSIC_UTILS::CSetArtJob::DoWork(), CPartyModeManager::Enable(), CProfileManager::FinalizeLoadProfile(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), CGUIWindowMusicPlayList::GetContextButtons(), CGUIWindowVideoPlaylist::GetContextButtons(), XFILE::CPlaylistDirectory::GetDirectory(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), JSONRPC::CPlayerOperations::GetPlaylist(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPlaylistInfo(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetPlaylistInfo(), KODI::GUILIB::GUIINFO::GetPlaylistLabel(), XBMCAddon::xbmc::PlayList::getposition(), JSONRPC::CPlayerOperations::GetPropertyValue(), CGUIViewState::IsCurrentPlaylistDirectory(), XBMCAddon::xbmc::PlayList::load(), CMediaSettings::Load(), CApplicationSkinHandling::LoadSkin(), CGUIWindowMusicPlayList::MoveCurrentPlayListItem(), CGUIWindowVideoPlaylist::MoveCurrentPlayListItem(), CPartyModeManager::MovePlaying(), CApplication::OnAction(), CGUIWindowMusicBase::OnAction(), CGUIWindowVideoBase::OnAction(), CApplication::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIMediaWindow::OnPlayAndQueueMedia(), CGUIWindowVideoBase::OnPlayAndQueueMedia(), CGUIWindowVideoBase::OnPlayMedia(), CGUIMediaWindow::OnPlayMedia(), CGUIWindowMusicBase::OnPlayMedia(), CGUIWindowMusicPlayList::OnPlayMedia(), anonymous_namespace{GUIWindowVideoPlaylist.cpp}::CVideoPlayActionProcessor::OnPlaySelected(), anonymous_namespace{GUIWindowVideoPlaylist.cpp}::CVideoPlayActionProcessor::OnResumeSelected(), CGUIWindowFileManager::OnStart(), JSONRPC::CPlayerOperations::Open(), CPartyModeManager::Play(), CApplication::PlaybackCleanup(), XBMCAddon::xbmc::Player::playCurrent(), PlayerControl(), CApplication::PlayFile(), CGUIWindowVideoBase::PlayItem(), MUSIC_UTILS::PlayItem(), KODI::VIDEO::UTILS::PlayItem(), CGUIWindowMusicBase::PlayItem(), XBMCAddon::xbmc::PlayList::PlayList(), PlayOffset(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), XBMCAddon::xbmc::Player::playPlaylist(), XBMCAddon::xbmc::Player::playselected(), CApplication::ProcessAndStartPlaylist(), MUSIC_UTILS::QueueItem(), KODI::VIDEO::UTILS::QueueItem(), CPartyModeManager::ReapSongs(), JSONRPC::CPlaylistOperations::Remove(), CGUIWindowMusicPlayList::RemovePlayListItem(), CGUIWindowVideoPlaylist::RemovePlayListItem(), CApplication::Run(), JSONRPC::CPlayerOperations::SetRepeat(), JSONRPC::CPlayerOperations::SetShuffle(), CGUIWindowMusicPlayList::UpdateButtons(), CGUIWindowVideoPlaylist::UpdateButtons(), and CGUIMediaWindow::UpdateFileList().
GetPowerManager()
CPowerManager & CServiceBroker::GetPowerManager () static
References g_application.
Referenced by CSysInfoJob::GetBatteryLevel(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), JSONRPC::CXBMCOperations::GetInfoBooleans(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetInt(), JSONRPC::CSystemOperations::GetPropertyValue(), JSONRPC::CSystemOperations::Hibernate(), CApplication::OnApplicationMessage(), CXBMCApp::OnSleep(), CXBMCApp::OnWakeup(), CCocoaPowerSyscall::OSPowerCallBack(), CApplication::ProcessSlow(), JSONRPC::CSystemOperations::Reboot(), CPowerManager::SetDefaults(), CPowerManager::SettingOptionsShutdownStatesFiller(), JSONRPC::CSystemOperations::Shutdown(), and JSONRPC::CSystemOperations::Suspend().
GetPVRManager()
PVR::CPVRManager & CServiceBroker::GetPVRManager () static
References g_application.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonChannelGroups(), PVR::CGUIDialogPVRGroupManager::ActionButtonDeleteGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonGroupMembers(), PVR::CGUIDialogPVRGroupManager::ActionButtonHideGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonNewGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonRenameGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonUngroupedChannels(), PVR::CGUIWindowPVRTimersBase::ActionShowTimer(), PVR::CGUIWindowPVRProvidersBase::ActivateChannelsWindow(), PVR::CGUIWindowPVRBase::ActivateNextChannelGroup(), PVR::CGUIWindowPVRBase::ActivatePreviousChannelGroup(), CApplicationPowerHandling::ActivateScreenSaver(), anonymous_namespace{PVRGUIActionsTimers.cpp}::AddEventLogEntry(), PVR::CPVRGUIActionsTimers::AddReminder(), PVR::CPVRGUIActionsTimers::AddTimer(), PVR::CPVRGUIActionsTimers::AddTimer(), JSONRPC::CPVROperations::AddTimer(), anonymous_namespace{PVRTimers.cpp}::AddTimerRuleToEpgMap(), PVR::CPVRTimerInfoTag::AddToClient(), PVR::CPVRGUIActionsPowerManagement::AllLocalBackendsIdle(), PVR::CPVRGUIAnyTimerInfo::AmountActiveRecordings(), PVR::CPVRGUITVTimerInfo::AmountActiveRecordings(), PVR::CPVRGUIRadioTimerInfo::AmountActiveRecordings(), PVR::CPVRGUIAnyTimerInfo::AmountActiveTimers(), PVR::CPVRGUITVTimerInfo::AmountActiveTimers(), PVR::CPVRGUIRadioTimerInfo::AmountActiveTimers(), PVR::CPVRGUIActionsTimers::AnnounceReminder(), PVR::CPVRGUIActionsTimers::AnnounceReminders(), PVR::CGUIDialogPVRRecordingSettings::CanEditRecording(), PVR::CPVRChannel::CanRecord(), PVR::CPVRGUIActionsPowerManagement::CanSystemPowerdown(), PVR::CPVRClient::cb_connection_state_change(), PVR::CPVRClient::cb_epg_event_state_change(), PVR::CPVRClient::cb_transfer_channel_group_member(), PVR::CPVRClient::cb_transfer_timer_entry(), PVR::CPVRClient::cb_trigger_channel_groups_update(), PVR::CPVRClient::cb_trigger_channel_update(), PVR::CPVRClient::cb_trigger_epg_update(), PVR::CPVRClient::cb_trigger_provider_update(), PVR::CPVRClient::cb_trigger_recording_update(), PVR::CPVRClient::cb_trigger_timer_update(), CFileItem::CFileItem(), PVR::CGUIDialogPVRChannelsOSD::CGUIDialogPVRChannelsOSD(), PVR::CGUIViewStateWindowPVRRecordings::CGUIViewStateWindowPVRRecordings(), PVR::CGUIWindowPVRBase::CGUIWindowPVRBase(), PVR::CGUIWindowPVRChannelsBase::CGUIWindowPVRChannelsBase(), PVR::CGUIWindowPVRGuideBase::CGUIWindowPVRGuideBase(), PVR::CPVRRecordings::ChangeRecordingsPlayCount(), PVR::CPVRRecording::Channel(), PVR::CPVRGUIInfo::CharInfoEncryption(), PVR::CPVRGUIActionsParentalControl::CheckParentalLock(), PVR::CPVRGUIActionsParentalControl::CheckParentalPIN(), PVR::CPVRSettings::CheckParentalPin(), PVR::CPVREpgContainer::CheckPlayingEvents(), CApplicationPowerHandling::CheckShutdown(), PVR::CPVRGUIActionsEPG::ChooseIconForSavedSearch(), PVR::CGUIDialogPVRGroupManager::ClearGroupThumbnails(), PVR::CPVRGUIActionsTimers::ConfirmDeleteTimer(), PVR::CPVRRecording::CPVRRecording(), PVR::CPVRTimerInfoTag::CPVRTimerInfoTag(), PVR::CPVRTimerInfoTag::CPVRTimerInfoTag(), PVR::CPVRChannel::CreateEPG(), PVR::CPVRTimerInfoTag::CreateFromEpg(), PVR::CPVRChannelGroupAllChannelsSingleClient::CreateMissingGroups(), PVR::CPVRChannelGroup::Delete(), PVR::CPVRRecording::Delete(), PVR::CPVRTimerInfoTag::DeleteFromClient(), PVR::CPVRProvider::DeleteFromDatabase(), PVR::CPVRTimerInfoTag::DeleteFromDatabase(), PVR::CPVRChannelGroup::DeleteGroupMembersFromDb(), PVR::CPVRGUIActionsEPG::DeleteSavedSearch(), PVR::CPVRGUIActionsTimers::DeleteTimer(), PVR::CPVRGUIActionsTimers::DeleteTimer(), JSONRPC::CPVROperations::DeleteTimer(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording::DoRun(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncEmptyRecordingsTrash::DoRun(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncSetRecordingPlayCount::DoRun(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncSetRecordingLifetime::DoRun(), CSaveFileState::DoWork(), PVR::CPVRGUIActionsEPG::DuplicateSavedSearch(), PVR::CPVRGUIActionsRecordings::EditRecording(), PVR::CPVRGUIActionsPowerManagement::EventOccursOnLocalBackend(), PVR::CPVREpgSearch::Execute(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::Execute(), PVR::CGUIWindowPVRSearchBase::ExecuteSearch(), CApplication::ExecuteXBMCAction(), PVR::CPVRGUIDirectory::Exists(), CFileItem::FillMusicInfoTag(), CProfileManager::FinalizeLoadProfile(), JSONRPC::CPlayerOperations::GetActivePlayers(), PVR::CPVRGUIAnyTimerInfo::GetActiveRecordings(), PVR::CPVRGUITVTimerInfo::GetActiveRecordings(), PVR::CPVRGUIRadioTimerInfo::GetActiveRecordings(), PVR::CPVRTimerType::GetAllTypes(), JSONRPC::CPVROperations::GetBroadcastDetails(), JSONRPC::CPVROperations::GetBroadcastIsPlayable(), JSONRPC::CPVROperations::GetBroadcasts(), PVR::CPVRItem::GetChannel(), JSONRPC::CPVROperations::GetChannelDetails(), JSONRPC::CPVROperations::GetChannelGroupDetails(), PVR::CPVRGUIActionsChannels::GetChannelGroupMember(), anonymous_namespace{PVRGUIDirectory.cpp}::GetChannelGroupMembers(), JSONRPC::CPVROperations::GetChannelGroups(), PVR::CPVRGUIDirectory::GetChannelGroupsDirectory(), PVR::CPVRChannelSwitchingInputHandler::GetChannelNumbers(), JSONRPC::CPVROperations::GetChannels(), PVR::CPVRGUIDirectory::GetChannelsDirectory(), PVR::CPVRChannelGroup::GetClientPriority(), JSONRPC::CPVROperations::GetClients(), JSONRPC::CPlayerOperations::GetCurrentEpg(), PVR::CPVREpgInfoTag::GetCurrentPlayingTime(), PVR::CPVRClient::GetDateTimeFirstChannelsAdded(), PVR::CPVRChannel::GetDefaultProvider(), PVR::CPVRRecording::GetDefaultProvider(), PVR::CPVRGUIDirectory::GetDirectory(), PVR::CPVREpgInfoTag::GetEdl(), PVR::CPVRRecording::GetEdl(), PVR::CPVRTimerInfoTag::GetEpgInfoTag(), anonymous_namespace{PVRTimers.cpp}::GetEpgTagsForTimerRule(), PVR::CPVRGUIInfo::GetFallbackLabel(), JSONRPC::CFileItemHandler::GetField(), anonymous_namespace{PVRGUIDirectory.cpp}::GetFirstMatchingGroupMember(), anonymous_namespace{PVRPlaybackState.cpp}::GetFirstNonDeletedAndNonHiddenChannelGroup(), PVR::CGUIEPGGridContainerModel::GetGridStartPadding(), CFileItem::GetItemToPlay(), PVR::CPVRChannelGroup::GetLastPlayedChannelGroupMember(), anonymous_namespace{PVRGUIDirectory.cpp}::GetLastWatchedChannelGroupMember(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRGUIAnyTimerInfo::GetNextActiveTimer(), PVR::CPVRGUITVTimerInfo::GetNextActiveTimer(), PVR::CPVRGUIRadioTimerInfo::GetNextActiveTimer(), PVR::CPVRPlaybackState::GetNextAutoplayItem(), PVR::CPVRItem::GetNextEpgInfoTag(), PVR::CPVRGUIChannelNavigator::GetNextOrPrevChannel(), PVR::CPVRClient::GetPriority(), JSONRPC::CPVROperations::GetProperties(), JSONRPC::CPVROperations::GetPropertyValue(), PVR::CPVRChannel::GetProvider(), PVR::CPVRRecording::GetProvider(), PVR::UTILS::GetProviderNameFromPath(), PVR::CPVRProviders::GetProviders(), PVR::CPVRGUIDirectory::GetProvidersDirectory(), PVR::CPVRGUIInfo::GetPVRInt(), PVR::CPVRItem::GetRecording(), JSONRPC::CPVROperations::GetRecordingDetails(), JSONRPC::CPVROperations::GetRecordingFileItem(), JSONRPC::CPVROperations::GetRecordings(), PVR::CPVRGUIDirectory::GetRecordingsDirectory(), PVR::CPVRRecording::GetRecordingTimer(), PVR::CPVRRecording::GetResumePoint(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), PVR::CPVRGUIDirectory::GetSavedSearchesDirectory(), PVR::CPVRGUIDirectory::GetSavedSearchResults(), PVR::CPVRGUIActionsChannels::GetSelectedChannelPath(), JSONRPC::CPVROperations::GetTimerDetails(), PVR::CPVRItem::GetTimerInfoTag(), PVR::CONTEXTMENUITEM::GetTimerInfoTagFromItem(), PVR::CPVRGUIActionsTimers::GetTimerRule(), JSONRPC::CPVROperations::GetTimers(), PVR::CPVRGUIDirectory::GetTimersDirectory(), PVR::CPVRGUIActionsEPG::GetTitleForEpgTag(), CWindowTranslator::GetVirtualWindow(), PVR::CGUIDialogPVRChannelsOSD::GotoChannel(), PVR::CGUIWindowPVRGuideBase::GotoCurrentProgramme(), PVR::CGUIWindowPVRGuideBase::GotoPlayingChannel(), PVR::CPVRChannelGroups::GroupStateChanged(), PVR::CPVRGUIDirectory::HasDeletedRadioRecordings(), PVR::CPVRGUIDirectory::HasDeletedTVRecordings(), KODI::UTILS::GUILIB::CGUIContentUtils::HasInfoForItem(), PVR::CPVRGUIDirectory::HasRadioRecordings(), PVR::CPVRGUIDirectory::HasTVRecordings(), PVR::CPVRGUIActionsChannels::HideChannel(), PVR::CPVRRecording::IncrementPlayCount(), PVR::CGUIWindowPVRBase::InitChannelGroup(), PVR::CPVRGUIInfo::InitCurrentItem(), PVR::CGUIWindowPVRGuideBase::InitEpgGridControl(), PVR::CGUIPVRChannelGroupsSelector::Initialize(), PVR::CGUIDialogPVRTimerSettings::InitializeChannelsList(), PVR::CGUIDialogPVRClientPriorities::InitializeSettings(), PVR::CGUIDialogPVRRecordingSettings::InitializeSettings(), PVR::CGUIDialogPVRTimerSettings::InitializeSettings(), PVR::CPVRGUIActionsPowerManagement::IsNextEventWithinBackendIdleTime(), PVR::CPVREpgInfoTag::IsPlayable(), JSONRPC::CPlayerOperations::IsPVRChannel(), PVR::CPVREpgInfoTag::IsRecordable(), PVR::CPVRPlaybackState::IsRecording(), PVR::CPVRPlaybackState::IsRecordingOnPlayingChannel(), PVR::CPVRSettings::IsSettingVisible(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible(), PVR::CGUIDialogPVRRecordingSettings::LifetimesFiller(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadChannelItem(), PVR::CPVRChannelGroup::LoadFromDatabase(), PVR::CPVRChannelGroups::LoadFromDatabase(), PVR::CPVRProviders::LoadFromDatabase(), PVR::CPVRTimers::LoadFromDatabase(), CProfileManager::LogOff(), PVR::CPVRGUIActionsRecordings::MarkWatched(), PVR::CPVREpgSearchFilter::MatchChannel(), PVR::CPVREpgSearchFilter::MatchChannelGroup(), PVR::CPVREpgSearchFilter::MatchFreeToAir(), PVR::CPVREpgSearchFilter::MatchRecordings(), PVR::CPVREpgSearchFilter::MatchSearchTerm(), PVR::CPVREpgSearchFilter::MatchTimers(), PVR::CPVRTimers::Notify(), PVR::CPVRTimers::NotifyTimersEvent(), CApplication::OnAction(), PVR::CGUIDialogPVRChannelsOSD::OnAction(), PVR::CPVRGUIActionListener::OnAction(), CGUIWindowLoginScreen::OnAction(), CApplication::OnApplicationMessage(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonAddTimer(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonFind(), PVR::CGUIDialogPVRRecordingInfo::OnClickButtonFind(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonPlay(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRadioParentalLocked(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonRecord(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonSetReminder(), PVR::CGUIDialogPVRChannelManager::OnContextButton(), PVR::CGUIWindowPVRRecordingsBase::OnContextButtonDeleteAll(), PVR::CGUIWindowPVRGuideBase::OnContextButtonNavigate(), PVR::CGUIDialogPVRChannelsOSD::OnDeinitWindow(), PVR::CPVRGUIActionsUtils::OnInfo(), anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnInfoSelected(), PVR::CGUIDialogPVRChannelGuide::OnInitWindow(), PVR::CGUIDialogPVRChannelsOSD::OnInitWindow(), PVR::CGUIDialogPVRGuideInfo::OnInitWindow(), PVR::CGUIWindowPVRBase::OnInitWindow(), PVR::CPVRThumbLoader::OnLoaderFinish(), CApplication::OnMessage(), PVR::CGUIDialogPVRRadioRDSInfo::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIWindowSystemInfo::OnMessage(), PVR::CPVRPlaybackState::OnPlaybackStarted(), anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnPlaySelected(), anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoPlayActionProcessor::OnPlaySelected(), anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnResumeSelected(), anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoPlayActionProcessor::OnResumeSelected(), PVR::CPVRGUIActionListener::OnSettingAction(), PVR::CPVRChannelGroup::OnSettingChanged(), PVR::CPVRGUIActionListener::OnSettingChanged(), CPowerManager::OnSleep(), CPowerManager::OnWake(), JSONRPC::CPlayerOperations::Open(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), CInputStreamPVRChannel::OpenPVRStream(), CInputStreamPVRRecording::OpenPVRStream(), PVR::CPVRChannel::Persist(), PVR::CPVRChannelGroup::Persist(), PVR::CPVRTimerInfoTag::Persist(), PVR::CPVRProvider::Persist(), PVR::CGUIPVRRecordingsPlayActionProcessor::Play(), PVR::CPVRGUIActionsPlayback::PlayChannelOnStartup(), PVR::CPVRGUIActionsPlayback::PlayEpgTag(), PlayerControl(), CApplication::PlayMedia(), PVR::CPVRGUIActionsPlayback::PlayMedia(), PVR::CPVRGUIActionsPlayback::PlayRecording(), CProfileManager::PrepareLoadProfile(), PVR::CPVRGUIInfo::Process(), PVR::CPVRGUIActionsClients::ProcessSettingsMenuHooks(), CInputStreamPVRBase::ProvidesStreamForMetaDataExtraction(), PVR::CPVRChannel::QueueDelete(), JSONRPC::CPVROperations::Record(), PVR::CPVREpgTagsCache::Refresh(), PVR::CGUIWindowPVRGuideBase::RefreshTimelineItems(), PVR::CPVRPlaybackState::ReInit(), PVR::CPVRChannelGroupAllChannels::RemoveDeletedGroupMembers(), PVR::CPVRRecording::Rename(), PVR::CGUIDialogPVRChannelManager::RenameChannel(), PVR::CPVRGUIActionsEPG::RenameSavedSearch(), CDirectoryProvider::Reset(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), PVR::CPVRChannelGroups::ResetGroupPositions(), PVR::CPVRClient::ResetProperties(), PVR::CPVRRecordings::ResetResumePoint(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction::Run(), anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer::Run(), PVR::CGUIDialogPVRChannelManager::SaveList(), JSONRPC::CPVROperations::Scan(), SearchMissingIcons(), PVR::CPVRGUIActionsPlayback::SeekBackward(), PVR::CPVRGUIActionsPlayback::SeekForward(), PVR::CPVRPlaybackState::SetActiveChannelGroup(), PVR::CGUIWindowPVRBase::SetChannelGroup(), PVR::CPVRClient::SetDateTimeFirstChannelsAdded(), PVR::CPVRChannelGroupMember::SetGroupName(), PVR::CGUIWindowPVRSearchBase::SetItemToSearch(), CLangInfo::SetLanguage(), PVR::CPVRChannelGroup::SetLastOpened(), PVR::CPVRChannelGroup::SetLastWatched(), PVR::CPVRChannel::SetLastWatched(), PVR::CPVRRecording::SetPlayCount(), PVR::CPVRClient::SetPriority(), PVR::CPVRGUIActionsTimers::SetRecordingOnChannel(), PVR::CPVRRecording::SetResumePoint(), PVR::CPVRRecording::SetResumePoint(), PVR::CGUIWindowPVRSearchBase::SetSearchFilter(), PVR::CPVRGUIActionsEPG::ShowChannelEPG(), PVR::CPVRGUIActionsEPG::ShowEPGInfo(), PVR::CGUIDialogPVRItemsViewBase::ShowInfo(), KODI::UTILS::GUILIB::CGUIContentUtils::ShowInfoForItem(), PVR::CPVRChannelGroups::SortGroups(), PVR::CPVRTimers::Start(), PVR::CPVRGUIActionsChannels::StartChannelScan(), PVR::CPVRPlaybackState::StartPlayback(), PVR::CPVRGUIInfo::Stop(), PVR::CPVRTimers::Stop(), PVR::CPVRClients::StopClient(), PVR::CPVRGUIActionsTimers::StopRecording(), PVR::CPVRClient::StopRunningInstance(), PVR::CPVRGUIDirectory::SupportsWriteFileOperations(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), PVR::CPVRChannelSwitchingInputHandler::SwitchToChannel(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), PVR::CPVRGUIChannelNavigator::SwitchToCurrentChannel(), PVR::CPVRChannelSwitchingInputHandler::SwitchToPreviousChannel(), PVR::CPVRGUIActionsTimers::ToggleRecordingOnPlayingChannel(), ToggleRecordPlayingChannel(), JSONRPC::CPVROperations::ToggleTimer(), PVR::CPVRGUIActionsTimers::ToggleTimerState(), PVR::CGUIDialogPVRTimerSettings::TypesFiller(), PVR::CPVRRecording::Undelete(), PVR::CPVRChannelGroups::Unload(), PVR::CGUIDialogPVRChannelManager::Update(), PVR::CGUIDialogPVRChannelsOSD::Update(), PVR::CGUIDialogPVRGroupManager::Update(), PVR::CGUIDialogPVRGuideSearch::Update(), PVR::CGUIWindowPVRGuideBase::Update(), anonymous_namespace{PVRGUIActionsChannels.cpp}::UpdateActiveGroup(), PVR::CPVRGUIInfo::UpdateBackendCache(), PVR::CGUIWindowPVRChannelsBase::UpdateButtons(), PVR::CGUIWindowPVRProvidersBase::UpdateButtons(), PVR::CGUIWindowPVRRecordingsBase::UpdateButtons(), PVR::CPVRTimerInfoTag::UpdateChannel(), PVR::CGUIDialogPVRChannelManager::UpdateChannelData(), PVR::CGUIDialogPVRGuideSearch::UpdateChannelSpin(), PVR::CPVRClients::UpdateClients(), PVR::CPVRGUIInfo::UpdateDescrambleData(), PVR::CPVRTimers::UpdateEntries(), PVR::CPVRTimers::UpdateEntries(), PVR::CPVRProviders::UpdateFromClients(), PVR::CPVRRecordings::UpdateFromClients(), PVR::CPVRTimers::UpdateFromClients(), PVR::CPVRChannelGroupAllChannels::UpdateFromClients(), PVR::CPVRChannelGroupFromClient::UpdateFromClients(), PVR::CPVRChannelGroups::UpdateFromClients(), PVR::CPVREpg::UpdateFromScraper(), PVR::CGUIDialogPVRGuideSearch::UpdateGroupsSpin(), PVR::CGUIDialogPVRRadioRDSInfo::UpdateInfoControls(), PVR::CPVRRecordings::UpdateInProgressSize(), PVR::CPVRPlaybackState::UpdateLastWatched(), PVR::CPVRChannelGroup::UpdateMembersClientPriority(), PVR::CPVRGUIInfo::UpdateMisc(), PVR::CPVRTimerInfoTag::UpdateOnClient(), PVR::CPVRGUITimesInfo::UpdatePlayingTag(), PVR::CPVRGUIInfo::UpdateQualityData(), PVR::CPVRRecording::UpdateRecordingSize(), PVR::CGUIWindowPVRBase::UpdateSelectedItemPath(), PVR::CGUIWindowPVRGuideBase::UpdateSelectedItemPath(), PVR::CPVRGUITimesInfo::UpdateTimeshiftData(), CDirectoryProvider::UpdateURL(), PVR::CPVRChannelGroupSettings::UpdateUseBackendChannelNumbers(), CVideoLibraryMarkWatchedJob::Work(), CVideoLibraryResetResumePointJob::Work(), PVR::CGUIDialogPVRChannelsOSD::~CGUIDialogPVRChannelsOSD(), PVR::CGUIWindowPVRBase::~CGUIWindowPVRBase(), PVR::CGUIWindowPVRChannelsBase::~CGUIWindowPVRChannelsBase(), and PVR::CGUIWindowPVRGuideBase::~CGUIWindowPVRGuideBase().
GetRenderSystem()
CRenderSystemBase * CServiceBroker::GetRenderSystem () static
References g_serviceBroker.
Referenced by CTextureBase::Allocate(), Shaders::CShader::AppendSource(), CGraphicContext::ApplyStateBlock(), CRenderCaptureGL::BeginRender(), CGraphicContext::CaptureStateBlock(), CGLESTexture::CGLESTexture(), CGLTexture::CGLTexture(), CGUITextureGL::CGUITextureGL(), CGUITextureGLES::CGUITextureGLES(), CApplication::Cleanup(), CGraphicContext::Clear(), CLinuxRendererGL::CLinuxRendererGL(), CLinuxRendererGLES::CLinuxRendererGLES(), CLinuxRendererGL::Configure(), Shaders::GLES::ConvolutionFilterShader::ConvolutionFilterShader(), Shaders::GL::ConvolutionFilterShader::ConvolutionFilterShader(), CApplication::CreateGUI(), CRendererDRMPRIMEGLES::DrawBlackBars(), CLinuxRendererGLES::DrawBlackBars(), CGUITextureGL::DrawQuad(), CGUITextureGLES::DrawQuad(), CGUIFontTTFGL::FirstBegin(), CGUIFontTTFGLES::FirstBegin(), CGraphicContext::Flip(), CGUIWindowSystemInfo::FrameMove(), CGraphicContext::GenerateAABB(), CGUIWindowSlideShow::GetCheckedSize(), CGLESTexture::GetFormatGLES20(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), CStereoscopicsManager::GetNextSupportedStereoMode(), CStereoscopicsManager::GetStereoModeByUserChoice(), JSONRPC::CGUIOperations::GetStereoscopicModes(), CSysInfoJob::GetVideoEncoder(), CApplication::Initialize(), CApplication::InitWindow(), Shaders::CShader::InsertSource(), CFrameBufferObject::IsSupported(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CTexture::LoadFromFileInMem(), CTexture::LoadFromFileInternal(), Shaders::CShader::LoadSource(), LoadTexture(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), LogGraphicsInfo(), CGLShader::OnEnabled(), CGLESShader::OnEnabled(), CStereoscopicsManager::OnStreamChange(), VDPAU::CDecoder::Open(), CBackgroundPicLoader::Process(), VDPAU::CDecoder::Register(), CApplication::Render(), CSlideShowPicGL::Render(), CSlideShowPicGLES::Render(), OVERLAY::COverlayTextureGL::Render(), OVERLAY::COverlayGlyphGL::Render(), OVERLAY::COverlayTextureGLES::Render(), OVERLAY::COverlayGlyphGLES::Render(), CRendererDRMPRIMEGLES::Render(), CRendererMediaCodec::RenderHook(), CGraphicContext::ResetScissors(), CGraphicContext::RestoreViewPort(), CGraphicContext::SetRenderOrder(), CGraphicContext::SetScissors(), CStereoscopicsManager::SetStereoMode(), CGraphicContext::SetStereoView(), CGLTexture::SetSwizzle(), CDisplaySettings::SettingOptionsPreferredStereoscopicViewModesFiller(), CDisplaySettings::SettingOptionsStereoscopicModesFiller(), CGraphicContext::SetViewPort(), and CGraphicContext::UpdateCameraPosition().
GetRepositoryUpdater()
ADDON::CRepositoryUpdater & CServiceBroker::GetRepositoryUpdater () static
References g_application.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CONTEXTMENU::CCheckForUpdates::Execute(), CApplication::Initialize(), ADDON::CAddonRepos::LoadAddonsFromDatabase(), KODI::GAME::CGUIControllerWindow::OnDeinitWindow(), KODI::GAME::CGUIControllerWindow::OnInitWindow(), CGUIWindowAddonBrowser::OnMessage(), CDirectoryProvider::Reset(), CGUIWindowAddonBrowser::SetProperties(), UpdateRepos(), and CDirectoryProvider::UpdateURL().
GetServiceAddons()
ADDON::CServiceAddonManager & CServiceBroker::GetServiceAddons () static
References g_application.
Referenced by CProfileManager::FinalizeLoadProfile(), CApplication::Initialize(), CProfileManager::PrepareLoadProfile(), and CApplication::Stop().
GetSettingsComponent()
std::shared_ptr< CSettingsComponent > CServiceBroker::GetSettingsComponent () static
References g_serviceBroker.
Referenced by CApplicationPowerHandling::ActivateScreenSaver(), CEventLog::Add(), MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), MUSIC_INFO::CMusicInfoScanner::AddArtistArtwork(), MUSIC_INFO::CMusicInfoTag::AddArtistRole(), CGUIDialogVideoBookmarks::AddBookmark(), CEdl::AddEdit(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::AddItemPathToFileBrowserSources(), CGUIDialogMusicInfo::AddItemPathToFileBrowserSources(), MUSIC_INFO::CMusicInfoScanner::AddLocalArtwork(), CGUIViewStateWindowMusicNav::AddOnlineShares(), CMusicFileItemListModifier::AddQueuingFolder(), CVideoFileItemListModifier::AddQueuingFolder(), MUSIC_INFO::CMusicInfoScanner::AddRemoteArtwork(), CMusicDatabase::AddSongContributors(), CMusicDatabase::AddSongGenres(), XFILE::CPluginDirectory::AddSortMethod(), CDVDDemuxFFmpeg::AddStream(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), CGUIDialogVideoManagerExtras::AddVideoExtra(), KODI::VIDEO::CVideoInfoScanner::AddVideoExtras(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), CWinSystemWin32::AdjustWindow(), AdvancedSettingsResetBase::AdvancedSettingsResetBase(), anonymous_namespace{TestArtUtils.cpp}::AdvancedSettingsResetBase::AdvancedSettingsResetBase(), CMusicDatabase::AlphanumericSortSQL(), CGUIPlayerAnnouncementHandler::Announce(), XBPython::Announce(), JSONRPC::CTCPServer::Announce(), PERIPHERALS::CPeripherals::Announce(), CGUIWindowVideoBase::AppendAndClearSearchItems(), CGUIWindowMusicPlaylistEditor::AppendToPlaylist(), CGraphicContext::ApplyVideoResolution(), CAirTunesServer::AudioOutputFunctions::audio_set_volume(), CGUIViewStateWindowMusic::AutoPlayNextItem(), CGUIViewStateWindowVideoNav::AutoPlayNextItem(), Shaders::GL::BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader(), CGUIDialogSubtitleSettings::BrowseForSubtitle(), UPNP::BuildObject(), CPicture::CacheTexture(), ActiveAE::CActiveAESettings::CActiveAESettings(), anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording(), anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer(), CBaseRenderer::CalcDestRect(), CVideoPlayerVideo::CalcFrameRate(), XBMCController::CallExit, CAndroidUtils::CAndroidUtils(), KODI::VIDEO::CVideoInfoScanner::CanFastHash(), CDPMSSupport::CDPMSSupport(), KODI::GAME::CGameSettings::CGameSettings(), CGLContextEGL::CGLContextEGL(), CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), CGUIViewStateMusicPlaylist::CGUIViewStateMusicPlaylist(), CGUIViewStateMusicSearch::CGUIViewStateMusicSearch(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoPlaylist::CGUIViewStateVideoPlaylist(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowMusicPlaylist::CGUIViewStateWindowMusicPlaylist(), CGUIViewStateWindowPrograms::CGUIViewStateWindowPrograms(), PVR::CGUIViewStateWindowPVRRecordings::CGUIViewStateWindowPVRRecordings(), PVR::CGUIViewStateWindowPVRTimers::CGUIViewStateWindowPVRTimers(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), ADDON::Interface_General::change_keyboard_layout(), CheckAndUpdateCurrentMonitor(), CheckCompatibility(), CColorManager::CheckConfiguration(), CGUIPassword::CheckLock(), CGUIPassword::CheckMenuLock(), CApplicationPowerHandling::CheckOSScreenSaverInhibitionSetting(), PVR::CPVREpgContainer::CheckPlayingEvents(), CApplicationPowerHandling::CheckScreenSaverAndDPMS(), CGUIPassword::CheckSettingLevelLock(), CApplicationPowerHandling::CheckShutdown(), CGUIPassword::CheckStartUpLock(), CCPUInfoPosix::CheckUserTemperatureCommand(), CEGLContextUtils::ChooseConfig(), KODI::VIDEO::GUILIB::CVideoVersionHelper::ChooseVideoFromAssets(), CInputManager::CInputManager(), CLabelFormatter::CLabelFormatter(), CDirtyRegionTracker::CleanMarkedRegions(), CUtil::CleanString(), WSDiscovery::CWSDiscoveryListenerUDP::Cleanup(), CGUIWindow::ClearBackground(), CGUIWindowFullScreen::ClearBackground(), CRenderSystemGL::ClearBuffers(), CRenderSystemGLES::ClearBuffers(), ADDON::CScraper::ClearCache(), CLibInputSettings::CLibInputSettings(), CLinuxRendererGL::CLinuxRendererGL(), CGUIDialogCMSSettings::Cms3dLutsFiller(), CNetworkServices::CNetworkServices(), CDVDSubtitlesLibass::Configure(), XBMCHelper::Configure(), CSeekHandler::Configure(), CNfsConnection::Connect(), PERIPHERALS::CPeripherals::CPeripherals(), PVR::CPVREpgInfoTag::CPVREpgInfoTag(), PVR::CPVRGUIActionListener::CPVRGUIActionListener(), PVR::CPVRRecording::CPVRRecording(), PVR::CPVRSettings::CPVRSettings(), PVR::CPVRTimerInfoTag::CPVRTimerInfoTag(), CApplication::Create(), DXVA::CDecoder::Create(), VAAPI::CDecoder::Create(), VDPAU::CDecoder::Create(), VTB::CDecoder::Create(), CAudioDecoder::Create(), CDVDVideoCodecDRMPRIME::Create(), CRendererDRMPRIME::Create(), KODI::CDRIP::CCDDARipper::CreateAlbumDir(), CMusicDatabase::CreateAnalytics(), CEGLContextUtils::CreateContext(), PVR::CPVRTimerInfoTag::CreateFromDate(), CApplication::CreateGUI(), CMusicDatabase::CreateNativeDBFunctions(), CWinSystemOSX::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::CreateNewWindow(), CWinSystemWin32DX::CreateNewWindow(), CWinSystemWin32::CreateNewWindow(), UPNP::CUPnP::CreateRenderer(), UPNP::CUPnP::CreateServer(), OVERLAY::CRenderer::CreateSubtitlesStyle(), CFFmpegImage::CreateThumbnailFromSurface(), CPicture::CreateTiledThumb(), OVERLAY::CRenderer::CRenderer(), ADDON::CRepositoryUpdater::CRepositoryUpdater(), CSong::CSong(), KODI::VIDEO::CVideoInfoScanner::CVideoInfoScanner(), CVideoPlayer::CVideoPlayer(), CVideoPlayerVideo::CVideoPlayerVideo(), CWeatherManager::CWeatherManager(), CWinSystemWin32::CWinSystemWin32(), DebugLogSharingPresenter::DebugLogSharingPresenter(), CDVDRadioRDSData::DecodeTA_TP(), CFileUtils::DeleteItemWithConfirm(), CGUIDialogVideoInfo::DeleteVideoItem(), CStereoscopicsManager::DetectStereoModeByString(), CUDisksProvider::DeviceAdded(), CUDisksProvider::DeviceChanged(), KODI::WINDOWING::WINDOWS::DIB_InitOSKeymap(), CGUIViewState::DisableAddSourceButtons(), KODI::WINDOWING::GBM::CDRMAtomic::DisplayHardwareScalingEnabled(), CGUIWindow::DoProcess(), MUSIC_INFO::CMusicInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::DoScan(), CGUIWindowMusicBase::DoScan(), CGUIDialogVideoInfo::DoSearch(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), KODI::VIDEO::CVideoInfoScanner::DownloadFailed(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CImageLoader::DoWork(), CGetInfoJob::DoWork(), CWeatherJob::DoWork(), CGUIDialogSmartPlaylistEditor::EditPlaylist(), CGUIAudioManager::Enable(), CPartyModeManager::Enable(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), XFILE::CCurlFile::Exists(), ExportLibrary(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), XFILE::CShoutcastFile::ExtractTagInfo(), CDVDFileInfo::ExtractThumbToTexture(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), ff_avutil_log(), MUSIC_INFO::CMusicInfoScanner::FileItemsToAlbums(), CUDisks2Provider::FilesystemAdded(), XFILE::CCurlFile::CReadState::FillBuffer(), JSONRPC::CAudioLibrary::FillFileItemList(), JSONRPC::CFileOperations::FillFileItemList(), CWinSystemOSX::FillInVideoModes(), CVideoThumbLoader::FillLibraryArt(), CGUIDialogSubtitles::FillServices(), ADDON::CScraper::FindArtist(), KODI::WINDOWING::GBM::CDRMUtils::FindConnector(), FindHWConfig(), CResolutionUtils::FindResolutionFromOverride(), CResolutionUtils::FindResolutionFromWhitelist(), KODI::VIDEO::UTILS::FindTrailer(), KODI::WINDOWING::X11::CWinSystemX11::FinishWindowResize(), CGUIFontTTFGL::FirstBegin(), CGUIFontTTFGLES::FirstBegin(), KODI::PLAYLIST::CSmartPlaylistRule::FormatWhereClause(), CGUIWindowVisualisation::FrameMove(), CGUIDialogAudioSettings::FrameMove(), CGUIWindowLoginScreen::FrameMove(), CApplication::FrameMove(), ADDON::FromArray(), ADDON::FromFileItem< CMusicArtistInfo >(), CScraperUrl::Get(), CColorManager::Get3dLutSize(), ADDON::Interface_GUIGeneral::get_adjust_refresh_rate_status(), ADDON::Interface_General::get_current_skin_id(), ADDON::Interface_General::get_keyboard_layout(), ADDON::CAddonSystemSettings::GetActive(), ADDON::CAddonSystemSettings::GetAddonAutoUpdateMode(), ADDON::CAddonSystemSettings::GetAddonRepoUpdateMode(), CAlbum::GetAlbumArtistString(), MUSIC_INFO::CMusicInfoTag::GetAlbumArtistString(), CMusicDatabase::GetAlbumByName(), KODI::CDRIP::CCDDARipper::GetAlbumDirName(), CMusicDatabase::GetAlbumFromDataset(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CGUIDialogVideoManagerVersions::GetAllOtherMovies(), CWeatherManager::GetArea(), CSong::GetArtist(), CMusicDatabase::GetArtistFromDataset(), CMusicDatabase::GetArtistPath(), JSONRPC::CAudioLibrary::GetArtists(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CSong::GetArtistString(), MUSIC_INFO::CMusicInfoTag::GetArtistString(), MUSIC_INFO::CMusicInfoTag::GetArtistStringForRole(), CVideoThumbLoader::GetArtTypes(), MUSIC_UTILS::GetArtTypesToScan(), MUSIC_INFO::CMusicInfoScanner::GetArtWhitelist(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CApplicationPlayer::GetAudioDelay(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetBool(), CTextureCache::GetCachedPath(), JSONRPC::CSettingsOperations::GetCategories(), PVR::CPVRGUIActionListener::GetChannelSwitchMode(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetChildType(), XFILE::CWin32File::GetChunkSize(), XFILE::CSMBFile::GetChunkSize(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeOverview::GetContent(), CGUIDialogContextMenu::GetContextButtons(), KODI::GAME::CGUIWindowGames::GetContextButtons(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowPictures::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), CSettingConditions::GetCurrentProfile(), JSONRPC::CProfilesOperations::GetCurrentProfile(), CVideoDatabase::GetDateAdded(), KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::GetDefaultAction(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::GetDefaultSelectAction(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsFromDB(), CSysInfo::GetDeviceName(), XBMCAddon::xbmc::InfoTagVideo::getDirector(), PVR::CPVREpgInfoTag::GetDirectorsLabel(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CUPnPDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), XFILE::CDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), JSONRPC::CFileOperations::GetDirectory(), CGUIMediaWindow::GetDirectory(), CGUIWindowAddonBrowser::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowVideoBase::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CGUIWindowSlideShow::GetDisplayEffect(), CWinSystemIOS::GetDisplayIndexFromSettings(), CDisplaySettings::GetDisplayResolution(), CWinSystemBase::GetDitherSettings(), PVR::CPVRClient::GetEPGForChannel(), CNfsConnection::GetExportList(), CGUIViewStateWindowPictures::GetExtensions(), CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput(), KODI::PLAYLIST::CSmartPlaylistRule::GetFields(), CUtil::GetFilenameIdentifier(), CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), XBMCAddon::xbmc::InfoTagMusic::getGenre(), XBMCAddon::xbmc::InfoTagVideo::getGenre(), PVR::CPVREpgInfoTag::GetGenresLabel(), PVR::CPVRRecording::GetGenresLabel(), CAlbum::GetGenreString(), CGUIWindowVideoBase::GetGroupedItems(), KODI::PLAYLIST::CSmartPlaylistRule::GetGroups(), CLangInfo::GetGuiCharSet(), CGraphicContext::GetGUIScaling(), CWinSystemAndroid::GetGuiSdrPeakLuminance(), CWinSystemWin10::GetGuiSdrPeakLuminance(), CWinSystemWin32::GetGuiSdrPeakLuminance(), XFILE::CVideoDatabaseDirectory::GetIcon(), CMusicDatabase::GetItems(), CVideoDatabase::GetItems(), CGUIDialogVideoInfo::GetItemsForTag(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CWeatherGUIInfo::GetLabel(), CLangInfo::GetLanguageAddon(), CVideoThumbLoader::GetLocalArt(), KODI::ART::GetLocalFanart(), CLabelFormatter::GetMaskContent(), CResolutionUtils::GetMaxAllowedScreenResolution(), CProcessInfo::GetMaxPassthroughOffSyncDuration(), CMusicDatabase::GetMediaDateFromFile(), CVideoDatabase::GetMoviesByName(), KODI::VIDEO::CVideoInfoScanner::GetMovieSetInfoFolder(), CGUIDialogVideoInfo::GetMoviesForSet(), XBMCAddon::xbmcgui::ListItem::getMusicStringArray(), CVideoDatabase::GetMusicVideosByArtist(), CMediaManager::GetNetworkLocations(), KODI::PLAYLIST::CSmartPlaylistRule::GetOrders(), CDVDOverlayCodecSSA::GetOverlay(), CVideoDatabase::GetPeopleNav(), CPlayerCoreFactory::GetPlayerIndex(), JSONRPC::CProfilesOperations::GetProfiles(), JSONRPC::CGUIOperations::GetPropertyValue(), CMusicDatabase::GetRecentlyAddedAlbums(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), CVideoDatabase::GetRecentlyAddedEpisodesNav(), CVideoDatabase::GetRecentlyAddedMoviesNav(), CVideoDatabase::GetRecentlyAddedMusicVideosNav(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), PVR::CPVRGUIDirectory::GetRecordingsDirectory(), CRenderManager::GetResolution(), CDisplaySettings::GetResolutionForScreen(), KODI::WINDOWING::GBM::CDRMUtils::GetResolutionInfo(), XFILE::CUPnPDirectory::GetResource(), CVideoDatabase::GetSeasonsByWhere(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), JSONRPC::CSettingsOperations::GetSections(), CGUIDialogVideoInfo::GetSetForMovie(), CGUIWindowVideoNav::GetSettingIncludeAllSeasonsAndSpecials(), anonymous_namespace{VideoThumbLoader.cpp}::GetSettingListAsString(), JSONRPC::CSettingsOperations::GetSettings(), CGUIWindowVideoNav::GetSettingSelectFirstUnwatchedItem(), JSONRPC::CSettingsOperations::GetSettingValue(), XBMCAddon::xbmc::getSkinDir(), JSONRPC::CSettingsOperations::GetSkinSettings(), CMusicDatabase::GetSongFromDataset(), CCueDocument::GetSongs(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsFullByWhere(), CLangInfo::GetSortTokens(), GetSoundSkinPath(), CGUIViewStateWindowVideoNav::GetSources(), CMediaSourceSettings::GetSourcesFile(), XFILE::CStackDirectory::GetStackedTitlePath(), ADDON::CSkinInfo::GetStartWindow(), OVERLAY::GetStereoscopicDepth(), CLangInfo::GetSubtitleCharSet(), CApplicationPlayer::GetSubtitleDelay(), CGPUInfo::GetTemperature(), CCPUInfoOsx::GetTemperature(), CFileItem::GetThumbHideIfUnwatched(), PVR::CPVRGUIDirectory::GetTimersDirectory(), PVR::CPVRGUIActionsEPG::GetTitleForEpgTag(), CUtil::GetTitleFromPath(), KODI::CDRIP::CCDDARipper::GetTrackName(), CVideoDatabase::GetTvShowsNav(), CVideoDatabase::GetUsedImages(), CMusicDatabase::GetUsedImages(), CFileItem::GetUserMusicThumb(), CVideoDatabase::GetValueString(), CColorManager::GetVideo3dLut(), XBMCAddon::xbmcgui::ListItem::getVideoStringArray(), CAutoSwitch::GetView(), PVR::CPVREpgInfoTag::GetWritersLabel(), XBMCAddon::xbmc::InfoTagVideo::getWritingCredits(), CMusicDatabase::GetYearsNav(), MUSIC_INFO::CMusicInfoTag::GetYearString(), PVR::CGUIDialogPVRChannelsOSD::GotoChannel(), CRemoteControlXbox::HandleAcceleratorKey(), CAppInboundProtocol::HandleEvents(), XBMCHelper::HandleLaunchAgent(), CWinSystemOSX::HandleOnResetDevice(), CIRServerSuite::HandleRemoteEvent(), CApplicationPowerHandling::HandleShutdownMessage(), ActiveAE::CActiveAE::HasHDAudioChannelCount(), ActiveAE::CActiveAE::HasStereoAudioChannelCount(), CResolutionUtils::HasWhitelist(), CGUIViewState::HideExtensions(), CGUIViewState::HideParentDirItems(), CDVDDemuxFFmpeg::HLSSelectProgram(), CVideoDatabase::ImportFromXML(), VDPAU::CMixer::Init(), CSMB::Init(), KODI::CDRIP::CEncoderFFmpeg::Init(), PVR::CPVRSettings::Init(), VAAPI::COutput::InitCycle(), CApplication::Initialize(), CWebVTTHandler::Initialize(), CDatabaseManager::Initialize(), CTVOSInputSettings::Initialize(), CAEEncoderFFmpeg::Initialize(), CAESinkAUDIOTRACK::Initialize(), CLog::Initialize(), CPlayerSelectionRule::Initialize(), CInputManager::InitializeInputs(), CGUIDialogProfileSettings::InitializeSettings(), CGUIDialogAudioSettings::InitializeSettings(), CGUIDialogCMSSettings::InitializeSettings(), CGUIDialogSubtitleSettings::InitializeSettings(), CWinSystemAndroid::InitiateModeChange(), CRenderSystemGL::InitRenderSystem(), CRenderSystemGLES::InitRenderSystem(), CPlatformAndroid::InitStageThree(), CGUIVisualisationControl::InitVisualization(), KODI::WINDOWING::GBM::CWinSystemGbm::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::InitWindowSystem(), KODI::WINDOWING::X11::CWinSystemX11::InitWindowSystem(), CGUIWindowAddonBrowser::InstallFromZip(), CRenderSystemGL::InvalidateColorBuffer(), CRenderSystemGLES::InvalidateColorBuffer(), MUSIC_UTILS::IsAutoPlayNextItem(), KODI::VIDEO::UTILS::IsAutoPlayNextItem(), CTextureCache::IsCachedImage(), CGUIPassword::IsDatabasePathUnlocked(), CColorManager::IsEnabled(), KODI::VIDEO::TAGS::CVideoTagExtractionHelper::IsExtractionSupportedFor(), CFileItem::IsFileFolder(), CWinSystemBase::IsHDRDisplaySettingEnabled(), CWinSystemBase::IsHighPrecisionProcessingSettingEnabled(), ADDON::CLanguageResource::IsInUse(), ADDON::CSkinInfo::IsInUse(), ADDON::CUISoundsResource::IsInUse(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), CGUIPassword::IsItemUnlocked(), CGUIPassword::IsMasterLockUnlocked(), anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked(), CGUIPassword::IsMusicUnlocked(), MUSIC_UTILS::anonymous_namespace{MusicUtils.cpp}::IsNonExistingUserPartyModePlaylist(), KODI::VIDEO::UTILS::anonymous_namespace{VideoGUIUtils.cpp}::IsNonExistingUserPartyModePlaylist(), CGUIPassword::IsProfileLockUnlocked(), PVR::CPVRSettings::IsSettingVisible(), ActiveAE::CActiveAE::IsSettingVisible(), IsSupportedHwFormat(), CBuiltins::IsSystemPowerdownCommand(), anonymous_namespace{Epg.cpp}::IsTagExpired(), CProcessInfo::IsTempoAllowed(), PVR::CPVRGUITimesInfo::IsTimeshifting(), CColorManager::IsValid(), CWinSystemBase::IsVideoSuperResolutionSettingEnabled(), CGUIPassword::IsVideoUnlocked(), CONTEXTMENU::CVideoChooseVersion::IsVisible(), CONTEXTMENU::CVideoPlayVersionUsing::IsVisible(), CONTEXTMENU::CVideoPlayUsing::IsVisible(), CGUIDialogVideoInfo::LinkMovieToTvShow(), CPasswordManager::Load(), CRssManager::Load(), CSettings::Load(), KODI::VIDEO::CVideoGeneratedImageFileLoader::Load(), KODI::KEYMAP::CIRTranslator::Load(), MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load(), CTagLoaderTagLib::Load(), CLangInfo::Load(), CAlbum::Load(), CArtist::Load(), CMediaManager::LoadAddonSources(), CWakeOnAccess::LoadFromXML(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CVideoThumbLoader::LoadItemLookup(), CApplication::LoadLanguage(), CGUIWindowSettingsProfile::LoadList(), CWeatherJob::LoadLocalizedToken(), CFileItem::LoadMusicTag(), JSONRPC::CProfilesOperations::LoadProfile(), LoadProfile(), CProfileManager::LoadProfile(), ActiveAE::CActiveAE::LoadSettings(), OVERLAY::CRenderer::LoadSettings(), CLinuxRendererGL::LoadShaders(), CLinuxRendererGLES::LoadShaders(), CApplicationSkinHandling::LoadSkin(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), CGUIWindowVideoBase::LoadVideoInfo(), CGUIViewState::LoadViewState(), LogOff(), CMusicDatabase::LookupCDDBInfo(), CGUIWindowMusicNav::ManageInfoProvider(), CEdl::MergeShortCommBreaks(), JSONRPC::CJSONRPC::MethodCall(), CSkinSettings::MigrateSettings(), CUtil::MusicPlaylistsLocation(), CWinSystemBase::NoOfBuffers(), CApplication::OnAction(), CGUIDialogAddonSettings::OnAction(), CGUIWindowVisualisation::OnAction(), PVR::CPVRGUIActionListener::OnAction(), CGUIWindowSettingsCategory::OnAction(), CPlayerController::OnAction(), CApplication::OnApplicationMessage(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIMediaWindow::OnClick(), CGUIWindowMusicNav::OnClick(), PVR::CGUIDialogPVRChannelManager::OnClickButtonChannelLogo(), KODI::GAME::CGUIWindowGames::OnClickMsg(), CGUIDialogContextMenu::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowMusicPlayList::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), CGUIWindowVideoBase::OnDeleteItem(), CGUIMediaWindow::OnDeleteItem(), CWinSystemWin10::OnDisplayBack(), CWinSystemWin32::OnDisplayBack(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIDialogKeyboardGeneric::OnInitWindow(), CGUIDialogSongInfo::OnInitWindow(), CGUIWindowMusicBase::OnInitWindow(), PVR::CGUIDialogPVRChannelManager::OnInitWindow(), PVR::CGUIDialogPVRGroupManager::OnInitWindow(), CGUIDialogSubtitles::OnInitWindow(), CGUIDialogVideoInfo::OnInitWindow(), CGUIWindowHome::OnInitWindow(), CGUIWindowLoginScreen::OnInitWindow(), CGUIWindowSplash::OnInitWindow(), CGUIWindowVideoBase::OnItemInfo(), CGUIWindowMusicPlayList::OnItemLoaded(), CGUIBaseContainer::OnJumpLetter(), CGUIDialogKeyboardGeneric::OnLayout(), CPictureInfoLoader::OnLoaderStart(), CGUIWindowAddonBrowser::OnMessage(), CGUIDialogSmartPlaylistEditor::OnMessage(), CGUIWindowEventLog::OnMessage(), CGUIDialogMusicOSD::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowVisualisation::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowSlideShow::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIWindowScreensaver::OnMessage(), CWinSystemWin32DX::OnMove(), CGUIDialogSmartPlaylistEditor::OnOK(), CGUIDialogLibExportSettings::OnOK(), CGUIDialogMediaSource::OnPathBrowse(), PVR::CPVRPlaybackState::OnPlaybackStarted(), CApplicationPlayerCallback::OnPlayerCloseFile(), CGUIWindowMusicBase::OnPlayMedia(), CGUIWindowSettingsProfile::OnPopupMenu(), CGUIWindowLoginScreen::OnPopupMenu(), CGUIWindowFileManager::OnPopupMenu(), ADDON::CFontResource::OnPostInstall(), ADDON::CLanguageResource::OnPostInstall(), ADDON::CSkinInfo::OnPostInstall(), CGUIWindowPictures::OnPrepareFileItems(), CGUIDialogVideoBookmarks::OnRefreshList(), CGUIMediaWindow::OnRenameItem(), CXBMCApp::onResume(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), CGUIWindowMusicPlaylistEditor::OnSavePlaylist(), CGUIDialogSubtitles::OnSearchComplete(), CGUIWindowVideoBase::OnSearchItemFound(), CApplicationPowerHandling::OnSettingAction(), CApplicationSettingsHandling::OnSettingAction(), CGUIDialogProfileSettings::OnSettingAction(), CGUIDialogVideoSettings::OnSettingAction(), CWeatherManager::OnSettingAction(), CApplicationSkinHandling::OnSettingChanged(), ADDON::CAddonSystemSettings::OnSettingChanged(), CLangInfo::OnSettingChanged(), PVR::CPVRGUIActionListener::OnSettingChanged(), CGUIDialogAudioSettings::OnSettingChanged(), CGUIDialogCMSSettings::OnSettingChanged(), XBMCHelper::OnSettingChanging(), CDisplaySettings::OnSettingChanging(), CLangInfo::OnSettingsLoaded(), CAdvancedSettings::OnSettingsLoaded(), CLog::OnSettingsLoaded(), CDisplaySettings::OnSettingUpdate(), CGUIWindowPictures::OnSlideShowRecursive(), CMediaManager::OnStorageAdded(), PERIPHERALS::CPeripherals::OnUserNotification(), CDVDInputStreamBluray::Open(), CDVDInputStreamNavigator::Open(), CMusicDatabase::Open(), PVR::CPVREpgDatabase::Open(), PVR::CPVRDatabase::Open(), CVideoDatabase::Open(), VAAPI::CDecoder::Open(), VDPAU::CDecoder::Open(), VTB::CDecoder::Open(), CDVDSubtitleParserSSA::Open(), CDVDAudioCodecFFmpeg::Open(), CDVDVideoCodecAndroidMediaCodec::Open(), CDVDVideoCodecFFmpeg::Open(), XFILE::CFile::Open(), XFILE::CFileCache::Open(), CDVDDemuxFFmpeg::Open(), CTextureBundleXBT::OpenBundle(), PAPlayer::OpenFile(), CDVDVideoCodecStarfish::OpenInternal(), CVideoPlayerAudio::OpenStream(), CVideoPlayerAudio::OpenStream(), CVideoPlayer::OpenVideoStream(), PredicateAudioFilter::operator()(), PredicateSubtitlePriority::operator()(), CExecString::Parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), ParseItem(), ParseItemMRSS(), CVideoInfoTag::ParseNative(), CAdvancedSettings::ParseSettingsFile(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), PERIPHERALS::CPeripheralBusApplication::PerformDeviceScan(), KODI::PLAYLIST::CPlayListPlayer::Play(), CApplication::PlaybackCleanup(), PlayerControl(), CApplication::PlayFile(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::PlayItem(), UPNP::PopulateObjectFromTag(), UPNP::PopulateTagFromObject(), PredicateSubtitleFilter::PredicateSubtitleFilter(), PAPlayer::PrepareStream(), CResolutionUtils::PrintWhitelist(), MUSIC_INFO::CMusicInfoScanner::Process(), CIRServerSuite::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), CVideoPlayer::Process(), XFILE::CFileCache::Process(), KODI::JOYSTICK::CGUIDialogNewJoystick::Process(), CLirc::Process(), PVR::CPVREpgContainer::Process(), PVR::CPVRGUIInfo::Process(), CRssReader::Process(), CSlideShowPic::Process(), CGUIRSSControl::Process(), CGUIWindowDebugInfo::Process(), CLirc::ProcessCode(), CAirPlayServer::CTCPClient::ProcessRequest(), CApplication::ProcessSlow(), UPNP::CUPnPServer::PropagateUpdates(), ADDON::CAddonInstaller::PrunePackageCache(), MUSIC_UTILS::QueueItem(), CWakeOnAccess::QueueMACDiscoveryForAllRemotes(), CGUIDialogMusicInfo::RefreshInfo(), EVENTCLIENT::CEventClient::RefreshSettings(), CDVDVideoCodecDRMPRIME::Register(), VDPAU::CDecoder::Register(), CRendererDRMPRIME::Register(), VAAPI::CDecoder::Register(), CApplicationSettingsHandling::RegisterSettings(), CApplicationSkinHandling::ReloadSkin(), CFileUtils::RemoteAccessAllowed(), CUtil::RemoveTempFiles(), CGUIWindowManager::Render(), CGUIRSSControl::Render(), CGUIWindowFullScreen::Render(), CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGL::RenderSinglePass(), CSettings::Reset(), CGUIWindowSettingsScreenCalibration::ResetControls(), CVideoPlayerVideo::ResetFrameRateCalc(), JSONRPC::CSettingsOperations::ResetSettingValue(), OVERLAY::CRenderer::ResetSubtitlePosition(), DX::DeviceResources::ResizeBuffers(), KODI::WINDOWING::X11::CWinSystemX11::ResizeWindow(), CAirPlayServer::restoreVolume(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), KODI::CDRIP::CCDDARipper::RipCD(), KODI::CDRIP::CCDDARipper::RipTrack(), XFILE::RootDirectory(), CSlideShowPic::Rotate(), EVENTSERVER::CEventServer::Run(), CAELimiter::Run(), CGUIWindowSlideShow::RunSlideShow(), CPasswordManager::Save(), CGUIDialogInfoProviderSettings::Save(), CGUIDialogLibExportSettings::Save(), CSettings::Save(), CGUIDialogAudioSettings::Save(), CGUIDialogCMSSettings::Save(), CGUIDialogSubtitleSettings::Save(), CGUIDialogVideoSettings::Save(), CGUIWindowMusicPlayList::SavePlayList(), CGUIWindowVideoPlaylist::SavePlayList(), KODI::GAME::CDialogGameVideoSelect::SaveSettings(), CGUIViewState::SaveViewToDb(), CUtil::ScanForExternalSubtitles(), CMusicLibraryQueue::ScanLibrary(), MUSIC_INFO::CMusicInfoScanner::ScanTags(), MUSIC_INFO::CMusicInfoScanner::ScrapeInfoAddedAlbums(), CGUIDialogSubtitles::Search(), PVR::CPVRGUIChannelIconUpdater::SearchAndUpdateMissingChannelIcons(), CVideoPlayer::Seek(), PAPlayer::Seek(), CDirtyRegionTracker::SelectAlgorithm(), SelectBool(), PVR::CPVRGUIChannelNavigator::SelectChannel(), CRendererHQ::SelectPSVideoFilter(), CWinRenderer::SelectRenderer(), MUSIC_INFO::CMusicInfoTag::Serialize(), ADDON::CAddonSystemSettings::SetActive(), SetAddon(), MUSIC_INFO::CMusicInfoTag::SetAlbum(), MUSIC_INFO::CMusicInfoTag::SetAlbumArtist(), MUSIC_INFO::CMusicInfoTag::SetAlbumArtist(), CTagLoaderTagLib::SetAlbumArtistHints(), CTagLoaderTagLib::SetAlbumArtistSort(), JSONRPC::CAudioLibrary::SetAlbumDetails(), CWeatherManager::SetArea(), MUSIC_INFO::CMusicInfoTag::SetArtist(), MUSIC_INFO::CMusicInfoTag::SetArtist(), MUSIC_INFO::CMusicInfoTag::SetArtist(), CSong::SetArtistCredits(), CAlbum::SetArtistCredits(), CTagLoaderTagLib::SetArtistHints(), CTagLoaderTagLib::SetArtistSort(), JSONRPC::CPlayerOperations::SetAudioDelay(), SetBool(), VDPAU::CMixer::SetColor(), XFILE::CCurlFile::SetCommonOptions(), CTagLoaderTagLib::SetComposerSort(), CGUIDialogTeletext::SetCoordinates(), CLangInfo::SetCurrentRegion(), CDisplaySettings::SetCurrentResolution(), VDPAU::CMixer::SetDeinterlacing(), VDPAU::CMixer::SetDeintSkipChroma(), KODI::WINDOWING::GBM::CWinSystemGbm::SetFullScreen(), CWinSystemOSX::SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11::SetFullScreen(), CGraphicContext::SetFullScreenVideo(), MUSIC_INFO::CMusicInfoTag::SetGenre(), PVR::CPVRRecording::SetGenre(), CWinSystemAndroid::SetHdmiState(), KODI::WINDOWING::GBM::CWinSystemGbm::SetHDR(), CApplication::SetLanguage(), CLangInfo::SetLanguage(), CGUIPassword::SetMasterLockMode(), CWinSystemWin32::SetMinimized(), CDisplaySettings::SetMonitor(), CGUIDialogVideoInfo::SetMovie(), CNfsConnection::setOptions(), SetPath(), CDVDVideoCodecFFmpeg::SetPictureParams(), CMusicDatabase::SetPropertiesFromAlbum(), CMusicDatabase::SetPropertiesFromArtist(), CTagLoaderTagLib::SetReleaseType(), JSONRPC::CSettingsOperations::SetSettingValue(), JSONRPC::CAudioLibrary::SetSongDetails(), SetString(), CSlideShowPic::SetTexture_Internal(), SetTheme(), CDisplaySettings::SettingOptionsDispModeFiller(), CDisplaySettings::SettingOptionsMonitorsFiller(), CSeekHandler::SettingOptionsSeekStepsFiller(), TestBasicEnvironment::SetUp(), KODI::CDRIP::CCDDARipJob::SetupEncoder(), CDVDInputStreamBluray::SetupPlayerSettings(), CGraphicContext::SetVideoResolutionInternal(), CBaseRenderer::SetViewMode(), UPNP::CUPnPPlayer::SetVolume(), VDPAU::CDecoder::SetWidthHeight(), CGUIDialogInfoProviderSettings::Show(), CGUIDialogInfoProviderSettings::Show(), CWinSystemWin32::Show(), CGUIDialogLibExportSettings::Show(), CGUIKeyboardFactory::ShowAndGetInput(), CGUIKeyboardFactory::ShowAndVerifyPassword(), KODI::JOYSTICK::CGUIDialogNewJoystick::ShowAsync(), CGUIDialogProfileSettings::ShowForProfile(), PVR::CPVRGUIChannelNavigator::ShowInfo(), CGUIWindowVideoBase::ShowInfo(), CGUIWindowPictures::ShowPicture(), CGUIDialogSimpleMenu::ShowPlaySelection(), CRenderSystemBase::ShowSplash(), SkinReset(), SkinResetAll(), CFileItem::SkipLocalArt(), CGUIMediaWindow::SortItems(), CNfsConnection::splitUrlIntoExportAndPath(), CFileItemList::StackFiles(), CFileItemList::StackFolders(), CVideoReferenceClock::Start(), CZeroconf::Start(), KODI::VIDEO::CVideoInfoScanner::Start(), MUSIC_INFO::CMusicInfoScanner::Start(), CNetworkServices::StartAirPlayServer(), CNetworkServices::StartAirTunesServer(), CNetworkServices::StartJSONRPCServer(), CWebServer::StartMHD(), PVR::CPVRPlaybackState::StartPlayback(), UPNP::CUPnP::StartRenderer(), EVENTSERVER::CEventServer::StartServer(), UPNP::CUPnP::StartServer(), CNetworkServices::StartServer(), CNetworkServices::StartWebserver(), XFILE::CCurlFile::Stat(), CApplication::Stop(), CRendererVDPAU::Supports(), CRendererVDPAU::Supports(), CLinuxRendererGL::Supports(), CLinuxRendererGLES::Supports(), CRendererHQ::Supports(), ActiveAE::CActiveAE::SupportsRaw(), CEGLContextUtils::SurfaceAttrib(), CVideoPlayerAudio::SwitchCodecIfNeeded(), CWinSystemOSX::SwitchToVideoMode(), CScreenShot::TakeScreenshot(), CAppEnvironment::TearDown(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TestFileFactory::TestFileFactory(), PVR::CPVRGUITimerInfo::TimerInfoToggle(), ToggleDebug(), anonymous_namespace{GUIBuiltins.cpp}::ToggleDirty(), ToggleSetting(), CSpecialProtocol::TranslatePath(), CUtil::TranslateSpecialSource(), OVERLAY::CRenderer::UnInit(), CLog::UnregisterFromSettings(), CApplicationSettingsHandling::UnregisterSettings(), ADDON::CAddonSystemSettings::UnsetActive(), CGUIDialogMusicInfo::Update(), CGUIDialogVideoInfo::Update(), CGUIWindowLoginScreen::Update(), PVR::CPVRRecording::Update(), CGUIDialogFileBrowser::Update(), CGUIMediaWindow::Update(), CGUIWindowPictures::Update(), CGUIWindowFileManager::Update(), PVR::CPVREpg::Update(), update_emu_environ(), CMusicDatabase::UpdateAlbum(), CMusicDatabase::UpdateAlbum(), CMusicDatabase::UpdateArtist(), CMusicDatabase::UpdateArtist(), CMusicDatabase::UpdateArtistSortNames(), CGUIWindowAddonBrowser::UpdateButtons(), CGUIWindowPictures::UpdateButtons(), PVR::CGUIWindowPVRTimersBase::UpdateButtons(), CGraphicContext::UpdateCameraPosition(), CGUIDialogAddonInfo::UpdateControls(), PAPlayer::UpdateCrossfadeTime(), MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo(), PVR::CPVREpgContainer::UpdateEPG(), PVR::CPVRChannelGroups::UpdateFromClients(), CRenderManager::UpdateLatencyTweak(), CApplication::UpdateLibraries(), CGUIPassword::UpdateMasterLockRetryCount(), CVideoPlayer::UpdatePlayState(), PVR::CPVRGUIInfo::UpdateQualityData(), CRenderManager::UpdateResolution(), CWinSystemOSX::UpdateResolutions(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateResolutions(), CWinSystemWin32::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), CMusicDatabase::UpdateSong(), CDirectoryProvider::UpdateSort(), CWinSystemWin32::UpdateStates(), CInputStreamPVRBase::UpdateStreamMap(), CMusicDatabase::UpdateTables(), PVR::CPVREpgDatabase::UpdateTables(), PVR::CPVRGUITimesInfo::UpdateTimeshiftProgressData(), CRecentlyAddedJob::UpdateTotal(), CGUIVisualisationControl::UpdateTrack(), CRecentlyAddedJob::UpdateVideo(), CLinuxRendererGL::UpdateVideoFilter(), CGUIWindowVideoBase::UpdateVideoVersionItems(), CGUIWindowDebugInfo::UpdateVisibility(), CWinEventsWin10::UpdateWindowSize(), KODI::WINDOWING::GBM::CWinSystemGbm::UseLimitedColor(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::UseLimitedColor(), CWinSystemWin10::UseLimitedColor(), CWinSystemWin32::UseLimitedColor(), KODI::WINDOWING::X11::CWinSystemX11::UseLimitedColor(), CLangInfo::UseLocaleCollation(), CRenderCapture::UseOcclusionQuery(), ActiveAE::CActiveAE::ValidateOutputDevices(), CUtil::VideoPlaylistsLocation(), CNetworkBase::WaitForNet(), CApplicationPowerHandling::WakeUpScreenSaver(), VIDEOPLAYER::CProcessInfoAndroid::WantsRawPassthrough(), CVideoLibraryMarkWatchedJob::Work(), CVideoLibraryResetResumePointJob::Work(), CSlideShowPic::Zoom(), ActiveAE::CActiveAESettings::~CActiveAESettings(), CInputManager::~CInputManager(), CLibInputSettings::~CLibInputSettings(), PERIPHERALS::CPeripherals::~CPeripherals(), PVR::CPVRGUIActionListener::~CPVRGUIActionListener(), PVR::CPVRSettings::~CPVRSettings(), OVERLAY::CRenderer::~CRenderer(), ADDON::CRepositoryUpdater::~CRepositoryUpdater(), CWeatherManager::~CWeatherManager(), DebugLogSharingPresenter::~DebugLogSharingPresenter(), TestCharsetConverter::~TestCharsetConverter(), TestFileFactory::~TestFileFactory(), TestLabelFormatter::~TestLabelFormatter(), TestURIUtils::~TestURIUtils(), and TestZipFile::~TestZipFile().
GetSlideShowDelegator()
CSlideShowDelegator & CServiceBroker::GetSlideShowDelegator () static
References g_application.
Referenced by JSONRPC::CPlaylistOperations::Add(), CGUIWindowSlideShow::CGUIWindowSlideShow(), JSONRPC::CPlaylistOperations::Clear(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetBool(), JSONRPC::CPlayerOperations::GetItem(), JSONRPC::CPlaylistOperations::GetItems(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), JSONRPC::CPlaylistOperations::GetPropertyValue(), JSONRPC::CPlayerOperations::GetPropertyValue(), CGUIWindowPictures::LoadPlayList(), CApplication::OnAction(), CApplication::OnApplicationMessage(), CGUIWindowPictures::OnInitWindow(), CGUIWindowPictures::OnShowPictureRecursive(), CGUIWindowPictures::OnSlideShow(), CGUIWindowPictures::OnSlideShowRecursive(), CGUIWindowFileManager::OnStart(), JSONRPC::CPlayerOperations::Open(), JSONRPC::CPlayerOperations::PlayPause(), JSONRPC::CPlayerOperations::SetShuffle(), CGUIWindowPictures::ShowPicture(), UPNP::CUPnPRenderer::UpdateState(), and CGUIWindowSlideShow::~CGUIWindowSlideShow().
GetSpeechRecognition()
std::shared_ptr< speech::ISpeechRecognition > CServiceBroker::GetSpeechRecognition () static
References g_serviceBroker.
Referenced by CGUIDialogKeyboardGeneric::OnVoiceRecognition().
GetTextureCache()
std::shared_ptr< CTextureCache > CServiceBroker::GetTextureCache () static
References g_serviceBroker.
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), MUSIC_INFO::CMusicInfoScanner::AddArtistArtwork(), KODI::VIDEO::CVideoInfoScanner::AddLocalItemArtwork(), AnnounceBridge(), UPNP::BuildObject(), PVR::CPVRCachedImages::Cleanup(), PVR::CPVRThumbLoader::ClearCachedImage(), CImageLoader::DoWork(), CTextureCacheJob::DoWork(), XFILE::CImageFile::Exists(), CVideoDatabase::ExportActorThumbs(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs(), JSONRPC::CAddonsOperations::FillDetails(), CProgramThumbLoader::FillThumb(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CGUIMultiImage::LoadDirectory(), CPictureThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), CApplicationSkinHandling::LoadSkin(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRefreshChannelLogos(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSongInfo::OnGetArt(), CMediaSettings::OnSettingAction(), XFILE::CImageFile::Open(), CPictureThumbLoader::ProcessFoldersAndArchives(), JSONRPC::CTextureOperations::RemoveTexture(), CGUIDialogVideoInfo::SetMovie(), XFILE::CImageFile::Stat(), CApplicationSkinHandling::UnloadSkin(), and CXBMCApp::UpdateSessionMetadata().
GetVFSAddonCache()
ADDON::CVFSAddonCache & CServiceBroker::GetVFSAddonCache () static
References g_application.
Referenced by CGUIDialogSubtitleSettings::BrowseForSubtitle(), CApplication::CloseNetworkShares(), XFILE::CDirectoryFactory::Create(), XFILE::CFileDirectoryFactory::Create(), XFILE::CFileFactory::CreateLoader(), CMediaManager::GetNetworkLocations(), CApplication::ProcessSlow(), CApplication::Stop(), CUtil::SupportsWriteFileOperations(), and CGUIDialogNetworkSetup::UpdateAvailableProtocols().
GetWeatherManager()
CWeatherManager & CServiceBroker::GetWeatherManager () static
References g_application.
Referenced by CProfileManager::FinalizeLoadProfile(), KODI::GUILIB::GUIINFO::CWeatherGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CWeatherGUIInfo::GetLabel(), CGUIWindowWeather::OnMessage(), CPowerManager::OnWake(), CLangInfo::SetLanguage(), CGUIWindowWeather::SetLocation(), CGUIWindowWeather::SetProperties(), CLangInfo::SetSpeedUnit(), CLangInfo::SetTemperatureUnit(), CGUIWindowWeather::UpdateButtons(), and CGUIWindowWeather::UpdateLocations().
GetWinSystem()
CWinSystemBase * CServiceBroker::GetWinSystem () static
References g_serviceBroker.
Referenced by CGUIWindowManager::ActivateWindow(), CGUIWindowManager::Add(), XBMCAddon::xbmcgui::Window::addControl(), XBMCAddon::xbmcgui::Window::addControls(), CGUIWindowManager::AddCustomWindow(), CGUIWindowManager::AddUniqueInstance(), CGUIWindowManager::AfterRender(), CGUIWindow::AllocResources(), CRotateEffect::ApplyEffect(), CGraphicContext::ApplyModeChange(), CStereoscopicsManager::ApplyStereoMode(), CRendererDXVA::ApplyTransforms(), CGraphicContext::ApplyWindowResize(), CGUIControl::AssignDepth(), PVR::CGUIEPGGridContainer::AssignDepth(), CGUITextureGLES::Begin(), CRenderSystemDX::BeginRender(), CRenderSystemGL::BeginRender(), CRenderSystemGLES::BeginRender(), CBaseRenderer::CalcDestRect(), CBaseRenderer::CalcNormalRenderRect(), CGUITexture::CalculateSize(), CScreenshotSurfaceWindows::Capture(), CScreenshotSurfaceGL::Capture(), CScreenshotSurfaceGLES::Capture(), CDumbBufferObject::CDumbBufferObject(), CDVDVideoCodecStarfish::CDVDVideoCodecStarfish(), CGBMBufferObject::CGBMBufferObject(), CWinSystemWin10::ChangeResolution(), CRenderManager::CheckEnableClockSync(), CInertialScrollingHandler::CheckForInertialScrolling(), CRenderSystemDX::CheckInterlacedStereoView(), CApplicationPowerHandling::CheckOSScreenSaverInhibitionSetting(), CApplicationPowerHandling::CheckScreenSaverAndDPMS(), CResolutionUtils::ChooseBestResolution(), CApplication::Cleanup(), CGUITextureManager::Cleanup(), CVideoSyncAndroid::Cleanup(), CVideoSyncOsx::Cleanup(), CLinuxRendererGL::ClearBackBuffer(), CLinuxRendererGLES::ClearBackBuffer(), CLinuxRendererGL::ClearBackBufferQuad(), CLinuxRendererGLES::ClearBackBufferQuad(), CGUIWindow::ClearBackground(), CGUIWindowFullScreen::ClearBackground(), XBMCAddon::xbmcgui::Window::clearProperties(), XBMCAddon::xbmcgui::Window::clearProperty(), CLinuxRendererGL::CLinuxRendererGL(), CLinuxRendererGLES::CLinuxRendererGLES(), CGUIShaderDX::ClipToScissorParams(), VDPAU::CDecoder::Close(), CGUIWindow::Close(), CGUIWindow::Close_Internal(), CGUIWindowManager::CloseDialogs(), CVideoPlayer::CloseFile(), CGUIWindowManager::CloseInternalModalDialogs(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CVideoLayerBridgeDRMPRIME::Configure(), VAAPI::CDecoder::ConfigVAAPI(), VDPAU::CDecoder::ConfigVDPAU(), OVERLAY::CRenderer::ConvertLibass(), CRendererDRMPRIME::Create(), CRendererDRMPRIMEGLES::Create(), VDPAU::CVDPAUContext::CreateContext(), CApplication::CreateGUI(), CWinSystemAndroid::CreateNewWindow(), KODI::RETRO::CRenderBufferDMA::CRenderBufferDMA(), CRendererVTB::CRendererVTB(), KODI::RETRO::CRetroPlayer::CRetroPlayer(), CVideoPlayer::CVideoPlayer(), CX11DPMSSupport::CX11DPMSSupport(), CGUIVisualisationControl::DeInitVisualization(), CGUIWindowManager::Delete(), CRenderSystemGLES::DestroyRenderSystem(), CGUIWindowManager::DestroyWindow(), CVideoLayerBridgeDRMPRIME::Disable(), CGBMDPMSSupport::DisablePowerSaving(), CX11DPMSSupport::DisablePowerSaving(), ActiveAE::CActiveAE::Dispose(), VAAPI::COutput::Dispose(), VDPAU::COutput::Dispose(), XBMCAddon::xbmcgui::Window::dispose(), CGUIControl::DoProcess(), CGUIWindow::DoProcess(), CGUIWindowSettingsScreenCalibration::DoProcess(), CGUIControl::DoRender(), CGUIWindow::DoRender(), CGUIDialogKaiToast::DoWork(), CImageLoader::DoWork(), CRendererDRMPRIMEGLES::DrawBlackBars(), CLinuxRendererGL::DrawBlackBars(), CLinuxRendererGLES::DrawBlackBars(), CGUITexture::DrawQuad(), CGUIFont::DrawScrollingText(), CGUIFont::DrawText(), CGBMDPMSSupport::EnablePowerSaving(), CWin32DPMSSupport::EnablePowerSaving(), CX11DPMSSupport::EnablePowerSaving(), VAAPI::CVAAPIContext::EnsureContext(), VDPAU::CVDPAUContext::EnsureContext(), CWinSystemIOS::FillInVideoModes(), CWinSystemTVOS::FillInVideoModes(), CRendererHQ::FinalOutput(), CGUIWindowSettingsScreenCalibration::FindCurrentResolution(), CResolutionUtils::FindResolutionFromOverride(), CResolutionUtils::FindResolutionFromWhitelist(), CGUITextureManager::Flush(), CRenderManager::Flush(), CGUIWindowManager::FrameMove(), CGUIWindowFullScreen::FrameMove(), CGUIWindowSystemInfo::FrameMove(), CApplication::FrameMove(), CTextureArray::Free(), CGUIRenderingControl::FreeResources(), CGUITextureManager::FreeUnusedTextures(), ADDON::Interface_GUIGeneral::get_current_window_dialog_id(), ADDON::Interface_GUIGeneral::get_current_window_id(), ADDON::Interface_GUIGeneral::get_hw_context(), ADDON::Interface_GUIGeneral::get_screen_height(), ADDON::Interface_GUIGeneral::get_screen_width(), ADDON::Interface_GUIGeneral::get_video_resolution(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIFont::GetCharWidth(), XBMCAddon::xbmcgui::Window::getControl(), XBMCAddon::xbmcgui::getCurrentWindowDialogId(), XBMCAddon::xbmcgui::getCurrentWindowId(), CGraphicContext::GetDisplayLatency(), XBMCAddon::xbmcgui::Window::getFocus(), XBMCAddon::xbmcgui::Window::getFocusId(), CVideoSyncAndroid::GetFps(), CVideoSyncIos::GetFps(), CVideoSyncOsx::GetFps(), CVideoSyncTVos::GetFps(), XBMCAddon::xbmcgui::Window::getHeight(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), CGUIFont::GetLineHeight(), CResolutionUtils::GetMaxAllowedScreenResolution(), EVENTCLIENT::CEventClient::GetMousePos(), CDVDOverlayCodecFFmpeg::GetOverlay(), GetPos(), KODI::ADDONS::CScreenSaver::GetProperties(), KODI::ADDONS::CVisualization::GetProperties(), XBMCAddon::xbmcgui::Window::getProperty(), CRenderManager::GetResolution(), CGUIWindow::GetScaledBounds(), XBMCAddon::xbmcgui::getScreenHeight(), CWinRenderer::GetScreenRect(), XBMCAddon::xbmcgui::getScreenWidth(), ADDON::CSkinInfo::GetSkinPath(), CUtil::GetSkinThemes(), OVERLAY::GetStereoscopicDepth(), CGUIFont::GetTextBaseLine(), CGUIFont::GetTextHeight(), CGUIFont::GetTextWidth(), CVideoPlayer::GetVideoResolution(), XBMCAddon::xbmcgui::Window::getWidth(), PVR::CGUIEPGGridContainer::HandleChannels(), CAppInboundProtocol::HandleEvents(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), PVR::CGUIEPGGridContainer::HandleRuler(), PVR::CGUIEPGGridContainer::HandleRulerDate(), anonymous_namespace{SettingConditions.cpp}::HasSystemSdrPeakLuminance(), CGUIRenderingControl::InitCallback(), VDPAU::CMixer::InitCycle(), CTeletextDecoder::InitDecoder(), CRenderSystemGL::InitialiseShaders(), CRenderSystemGLES::InitialiseShaders(), CGUIDialogVideoSettings::InitializeSettings(), CGUIVisualisationControl::InitVisualization(), CApplication::InitWindow(), anonymous_namespace{SettingConditions.cpp}::IsHDRDisplay(), CApplication::IsPlayingFullScreenVideo(), CGUIFontTTFDX::LastEnd(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGUITextureManager::Load(), CGUIWindow::Load(), CApplicationSkinHandling::LoadSkin(), CTexture::LoadToGPUAsync(), GUIFontManager::LoadTTF(), ADDON::Interface_GUIGeneral::lock(), CApplication::LockFrameMoveGuard(), XBMCAddon::xbmcgui::WindowXML::lockingGetNextAvailableWindowId(), CBaseRenderer::ManageRenderArea(), CRendererDRMPRIME::ManageRenderArea(), CRendererStarfish::ManageRenderArea(), CXBMCApp::MapRenderToDroid(), CGUIWindowManager::MarkDirty(), CWinSystemIOS::Minimize(), CWinSystemTVOS::Minimize(), CAndroidMouse::MouseWheel(), CWinSystemIOS::NotifyAppActiveChange(), CWinSystemTVOS::NotifyAppActiveChange(), CWinSystemWin32::NotifyAppFocusChange(), KODI::WINDOWING::X11::CWinSystemX11::NotifyXRREvent(), CApplication::OnAction(), CGUIWindowSlideShow::OnAction(), CGUIWindowSettingsScreenCalibration::OnAction(), CPlayerController::OnAction(), CApplication::OnApplicationMessage(), KODI::RETRO::CGameWindowFullScreen::OnDeinitWindow(), CXBMCApp::onDisplayChanged(), CGLShader::OnEnabled(), CGLESShader::OnEnabled(), CPythonInvoker::onError(), CVideoPlayer::OnExit(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), CGUIWindowSplash::OnInitWindow(), VDPAU::CDecoder::OnLostDisplay(), CGUIWindowSlideShow::OnMessage(), CGUIWindowSettingsCategory::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowScreensaver::OnMessage(), CGUIWindow::OnMouseAction(), CGUIEditControl::OnPasteClipboard(), CXBMCApp::onReceive(), VDPAU::CDecoder::OnResetDisplay(), CXBMCApp::onResume(), CApplicationSettingsHandling::OnSettingChanged(), CDisplaySettings::OnSettingChanging(), CPowerManager::OnWake(), VDPAU::CDecoder::Open(), CGUIDialog::Open(), CDVDVideoCodecDRMPRIME::Open(), CGUIDialogProgress::Open(), CTextureBundleXBT::OpenBundle(), CDVDVideoCodecStarfish::OpenInternal(), CVideoPlayer::OpenVideoStream(), CApplication::PlaybackCleanup(), CWinRenderer::PreInit(), CRenderManager::PrepareNextRender(), CGUIWindowManager::PreviousWindow(), CResolutionUtils::PrintWhitelist(), CApplication::Process(), CExternalPlayer::Process(), CVideoPlayer::Process(), CVideoReferenceClock::Process(), CGUIDialogCache::Process(), CGUIWindowManager::Process(), KODI::RETRO::CGameWindowFullScreen::Process(), CGUIWindowFullScreen::Process(), CGUIControl::Process(), CSlideShowPic::Process(), CGUIControlGroup::Process(), CGUIControlGroupList::Process(), CGUIFadeLabelControl::Process(), CGUIListGroup::Process(), CGUIMultiImage::Process(), CGUITextBox::Process(), CGUIVisualisationControl::Process(), CGUIWindowDebugInfo::Process(), CGUIWindowScreensaverDim::Process(), CGUIWindowSlideShow::Process(), CGUIWindowScreensaver::Process(), CGUIImage::ProcessFadingTransition(), PVR::CGUIEPGGridContainer::ProcessItem(), CGUIBaseContainer::ProcessItem(), CLibInputPointer::ProcessMotion(), CLibInputPointer::ProcessMotionAbsolute(), CGUIEditControl::ProcessText(), KODI::WINDOWING::X11::CWinSystemX11::RecreateWindow(), CRendererDRMPRIME::Register(), CGUIInfoManager::RegisterInfoProvider(), VAAPI::CDecoder::Release(), CGUITextureManager::ReleaseHwTexture(), CGUITextureManager::ReleaseTexture(), GUIFontManager::ReloadTTFFonts(), CGUIWindowManager::Remove(), XBMCAddon::xbmcgui::Window::removeControl(), CGUIWindowManager::Render(), CSlideShowPic::Render(), CApplication::Render(), CGUIBaseContainer::Render(), CGUIBorderedImage::Render(), CGUIButtonControl::Render(), CGUIControlGroup::Render(), CGUIControlGroupList::Render(), CGUIFadeLabelControl::Render(), CGUILabelControl::Render(), CGUIListLabel::Render(), CGUIPanelContainer::Render(), CGUIProgressControl::Render(), CGUIRenderingControl::Render(), CGUISettingsSliderControl::Render(), CGUITextBox::Render(), CGUIVideoControl::Render(), CGUIVisualisationControl::Render(), CGUIWindowSlideShow::Render(), PVR::CGUIEPGGridContainer::Render(), CGUIDialogTeletext::Render(), CGUIWindowFullScreen::Render(), CGUIWindowDebugInfo::Render(), CGUIWindowScreensaver::Render(), CGUIWindowScreensaverDim::Render(), CGUIWindowSplash::Render(), CRenderManager::Render(), OVERLAY::CRenderer::Render(), CSlideShowPicGLES::Render(), CGUITexture::Render(), CGUITextLayout::Render(), CGUITexture::Render(), OVERLAY::COverlayQuadsDX::Render(), OVERLAY::COverlayImageDX::Render(), CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), CGUIWindowSlideShow::RenderErrorMessage(), CGUIWindowFullScreen::RenderEx(), CGUIBaseContainer::RenderItem(), PVR::CGUIEPGGridContainer::RenderItem(), PVR::CGUIEPGGridContainer::RenderProgressIndicator(), CGUITextLayout::RenderScrolling(), CGUIButtonControl::RenderText(), CGUIEditControl::RenderText(), CGUISpinControl::RenderText(), CRendererDRMPRIME::RenderUpdate(), CRendererMediaCodecSurface::RenderUpdate(), CWinRenderer::RenderUpdate(), CRendererMediaCodecSurface::Reset(), CGUIWindowSlideShow::Reset(), CGUIWindowSettingsScreenCalibration::ResetCalibration(), CGUIWindowSettingsScreenCalibration::ResetControls(), OVERLAY::CRenderer::ResetSubtitlePosition(), DX::DeviceResources::ResizeBuffers(), CSlideShowPic::Rotate(), CSeekHandler::Seek(), CGUIWindowManager::SendMessage(), KODI::MESSAGING::CApplicationMessenger::SendMsg(), CMouseStat::SetActive(), CGUIDialogTeletext::SetCoordinates(), CDisplaySettings::SetCurrentResolution(), CXBMCApp::SetDisplayMode(), DX::DeviceResources::SetFullScreen(), CWinSystemWin10::SetFullScreen(), CWinSystemWin32::SetFullScreen(), CWinSystemAndroidGLESContext::SetHDR(), XBMCAddon::xbmcgui::Window::setProperty(), CConvolutionShaderSeparable::SetStepParams(), CSlideShowPic::SetTexture_Internal(), CDisplaySettings::SettingOptionsDispModeFiller(), CDisplaySettings::SettingOptionsMonitorsFiller(), CDisplaySettings::SettingOptionsRefreshRatesFiller(), CDisplaySettings::SettingOptionsResolutionsFiller(), CVideoSyncAndroid::Setup(), CVideoSyncOsx::Setup(), CVideoSyncD3D::Setup(), CGraphicContext::SetVideoResolutionInternal(), CBaseRenderer::SetViewMode(), VDPAU::CDecoder::SetWidthHeight(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow(), CWinSystemBase::SetWindowResolution(), ADDON::CGUIAddonWindowDialog::Show(), CRenderSystemBase::ShowSplash(), CGUIDialogKeyboardGeneric::ShowWordList(), CFillViewportAlwaysRegionSolver::Solve(), CFillViewportOnChangeRegionSolver::Solve(), ADDON::CSkinInfo::Start(), ActiveAE::CActiveAE::StateMachine(), anonymous_namespace{SettingConditions.cpp}::SupportsDolbyVision(), anonymous_namespace{SettingConditions.cpp}::SupportsScreenMove(), anonymous_namespace{SettingConditions.cpp}::SupportsVideoSuperResolution(), CApplicationPowerHandling::ToggleDPMS(), CSpecialProtocol::TranslatePath(), CLinuxRendererGL::UnInit(), CLinuxRendererGLES::UnInit(), CWinRenderer::UnInit(), ADDON::Interface_GUIGeneral::unlock(), CApplication::UnlockFrameMoveGuard(), CGUIInfoManager::UnregisterInfoProvider(), KODI::WINDOWING::X11::CWinSystemX11::UpdateCrtc(), CTimeUtils::UpdateFrameTime(), CGUIWindowSettingsScreenCalibration::UpdateFromControl(), CRenderManager::UpdateLatencyTweak(), CRssReader::UpdateObserver(), CRenderManager::UpdateResolution(), KODI::WINDOWING::GBM::CWinSystemGbm::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), CWinSystemAndroid::UpdateResolutions(), CGUIFont::UpdateScrollInfo(), CGUIWindowPointer::UpdateVisibility(), CRendererVTB::UploadTexture(), XBMCAddon::xbmcgui::Window::Window(), XBMCAddon::xbmcgui::WindowDialog::WindowDialog(), CAndroidKey::XBMC_Key(), CSlideShowPic::Zoom(), KODI::RETRO::CRetroPlayer::~CRetroPlayer(), and CVideoPlayer::~CVideoPlayer().
GetWSDiscovery()
static WSDiscovery::IWSDiscovery & CServiceBroker::GetWSDiscovery () static
Referenced by WSDiscovery::CWSDiscoveryListenerUDP::buildSoapMessage(), CDNSNameCache::GetCached(), XFILE::CSMBDirectory::GetDirectory(), CNetworkServices::IsWSDiscoveryRunning(), localGetServers(), WSDiscovery::CWSDiscoveryListenerUDP::ParseBuffer(), WSDiscovery::CWSDiscoveryListenerUDP::Start(), CNetworkServices::StartWSDiscovery(), and CNetworkServices::StopWSDiscovery().
GetXBPython()
static XBPython & CServiceBroker::GetXBPython () static
Referenced by CContextMenuItem::Execute(), CHTTPPythonHandler::HandleRequest(), CApplication::OnMessage(), CApplicationPlayerCallback::OnPlayBackPaused(), CApplicationPlayerCallback::OnPlayBackResumed(), CApplicationPlayerCallback::OnPlayBackSeek(), CApplicationPlayerCallback::OnPlayBackSeekChapter(), CApplicationPlayerCallback::OnPlayBackSpeedChanged(), CApplicationPlayerCallback::OnQueueNextItem(), XBMCAddon::Python::PythonLanguageHook::RegisterMonitorCallback(), XBMCAddon::Python::PythonLanguageHook::RegisterPlayerCallback(), ADDON::CAddon::SaveSettings(), XBMCAddon::Python::PythonLanguageHook::UnregisterMonitorCallback(), XBMCAddon::Python::PythonLanguageHook::UnregisterPlayerCallback(), and XBMCAddon::Python::PythonLanguageHook::WaitForEvent().
IsAddonInterfaceUp()
bool CServiceBroker::IsAddonInterfaceUp () static
References g_application.
Referenced by CFileExtensionProvider::CanOperateExtension(), XFILE::CDirectoryFactory::Create(), XFILE::CFileDirectoryFactory::Create(), XFILE::CFileFactory::CreateLoader(), CMediaManager::GetNetworkLocations(), ADDON::CAddonDll::GetRunningInstance(), URIUtils::HasParentInHostname(), CFileItem::IsFileFolder(), CPictureInfoTag::Load(), CUtil::SupportsWriteFileOperations(), and CGUIDialogNetworkSetup::UpdateAvailableProtocols().
IsLoggingUp()
bool CServiceBroker::IsLoggingUp () static
References g_serviceBroker.
Referenced by CXBMCApp::android_printf(), and CWinEventsWin10::OnWindowActivationChanged().
IsServiceManagerUp()
bool CServiceBroker::IsServiceManagerUp () static
References g_application.
Referenced by KODI::GAME::CGUIAgentControllerList::Deinitialize(), CWIN32Util::GetWindowsHDRStatusWin32(), KODI::GAME::CGUIAgentControllerList::Initialize(), KODI::GAME::CDialogGameOSD::OnAction(), KODI::GAME::CDialogGameOSD::OnDeinitWindow(), CLangInfo::SetSpeedUnit(), and CLangInfo::SetTemperatureUnit().
RegisterAE()
void CServiceBroker::RegisterAE (IAE * ae) static
References g_serviceBroker.
Referenced by CApplication::Create().
RegisterAnnouncementManager()
void CServiceBroker::RegisterAnnouncementManager (std::shared_ptr< ANNOUNCEMENT::CAnnouncementManager > announcementManager) static
References g_serviceBroker.
Referenced by CApplication::Create().
RegisterAppMessenger()
void CServiceBroker::RegisterAppMessenger (const std::shared_ptr< KODI::MESSAGING::CApplicationMessenger > & appMessenger) static
References g_serviceBroker.
Referenced by CApplication::Create(), and TestBasicEnvironment::SetUp().
RegisterAppParams()
void CServiceBroker::RegisterAppParams (const std::shared_ptr< CAppParams > & appParams) static
References g_serviceBroker.
Referenced by CAppEnvironment::SetUp().
RegisterAppPort()
void CServiceBroker::RegisterAppPort (std::shared_ptr< CAppInboundProtocol > port) static
References g_serviceBroker.
Referenced by CApplication::Create().
RegisterCPUInfo()
void CServiceBroker::RegisterCPUInfo (std::shared_ptr< CCPUInfo > cpuInfo) static
References g_serviceBroker.
Referenced by CApplication::Create(), TestCPUInfo::TestCPUInfo(), and TestSystemInfo::TestSystemInfo().
RegisterDecoderFilterManager()
void CServiceBroker::RegisterDecoderFilterManager (CDecoderFilterManager * manager) static
References g_serviceBroker.
Referenced by CWinSystemAndroid::DestroyWindowSystem(), and CWinSystemAndroid::InitWindowSystem().
RegisterGUI()
void CServiceBroker::RegisterGUI (CGUIComponent * gui) static
References g_serviceBroker.
Referenced by anonymous_namespace{TestGUIControlFactory.cpp}::CGUITestComponent::CGUITestComponent(), and CGUIComponent::Init().
RegisterJobManager()
void CServiceBroker::RegisterJobManager (const std::shared_ptr< CJobManager > & jobManager) static
References g_serviceBroker.
Referenced by CApplication::Create(), and TestJobManager::TestJobManager().
RegisterKeyboardLayoutManager()
void CServiceBroker::RegisterKeyboardLayoutManager (const std::shared_ptr< KODI::KEYBOARD::CKeyboardLayoutManager > & keyboardLayoutManager) static
References g_serviceBroker.
Referenced by CApplication::Create().
RegisterSettingsComponent()
void CServiceBroker::RegisterSettingsComponent (const std::shared_ptr< CSettingsComponent > & settings) static
References g_serviceBroker.
Referenced by CAppEnvironment::SetUp().
RegisterSpeechRecognition()
void CServiceBroker::RegisterSpeechRecognition (const std::shared_ptr< speech::ISpeechRecognition > & speechRecognition) static
References g_serviceBroker.
Referenced by CApplication::Initialize().
RegisterTextureCache()
void CServiceBroker::RegisterTextureCache (const std::shared_ptr< CTextureCache > & cache) static
References g_serviceBroker.
Referenced by CApplication::Initialize().
RegisterWinSystem()
void CServiceBroker::RegisterWinSystem (CWinSystemBase * winsystem) static
References g_serviceBroker.
Referenced by CApplication::CreateGUI().
UnregisterAE()
void CServiceBroker::UnregisterAE () static
References g_serviceBroker.
Referenced by CApplication::Stop().
UnregisterAnnouncementManager()
void CServiceBroker::UnregisterAnnouncementManager () static
References g_serviceBroker.
Referenced by CApplication::Cleanup().
UnregisterAppMessenger()
void CServiceBroker::UnregisterAppMessenger () static
References g_serviceBroker.
Referenced by CApplication::Cleanup(), and TestBasicEnvironment::TearDown().
UnregisterAppParams()
void CServiceBroker::UnregisterAppParams () static
References g_serviceBroker.
Referenced by CAppEnvironment::TearDown().
UnregisterAppPort()
void CServiceBroker::UnregisterAppPort () static
References g_serviceBroker.
Referenced by CApplication::Stop().
UnregisterCPUInfo()
void CServiceBroker::UnregisterCPUInfo () static
References g_serviceBroker.
Referenced by CApplication::Cleanup(), TestCPUInfo::~TestCPUInfo(), and TestSystemInfo::~TestSystemInfo().
UnregisterGUI()
void CServiceBroker::UnregisterGUI () static
References g_serviceBroker.
Referenced by CGUIComponent::Deinit().
UnregisterJobManager()
void CServiceBroker::UnregisterJobManager () static
References g_serviceBroker.
Referenced by CApplication::Cleanup(), and TestJobManager::~TestJobManager().
UnregisterKeyboardLayoutManager()
void CServiceBroker::UnregisterKeyboardLayoutManager () static
References g_serviceBroker.
Referenced by CApplication::Cleanup().
UnregisterSettingsComponent()
void CServiceBroker::UnregisterSettingsComponent () static
References g_serviceBroker.
Referenced by CAppEnvironment::TearDown().
UnregisterSpeechRecognition()
void CServiceBroker::UnregisterSpeechRecognition () static
References g_serviceBroker.
Referenced by CApplication::Cleanup().
UnregisterTextureCache()
void CServiceBroker::UnregisterTextureCache () static
References g_serviceBroker.
Referenced by CApplication::Cleanup().
UnregisterWinSystem()
void CServiceBroker::UnregisterWinSystem () static
References g_serviceBroker.
Referenced by CApplication::Cleanup(), and CApplication::CreateGUI().
Member Data Documentation
m_appMessenger
std::shared_ptr<KODI::MESSAGING::CApplicationMessenger> CServiceBroker::m_appMessenger private
m_appParams
std::shared_ptr<CAppParams> CServiceBroker::m_appParams private
m_cpuInfo
std::shared_ptr<CCPUInfo> CServiceBroker::m_cpuInfo private
m_decoderFilterManager
CDecoderFilterManager* CServiceBroker::m_decoderFilterManager = nullptr private
m_jobManager
std::shared_ptr<CJobManager> CServiceBroker::m_jobManager private
m_keyboardLayoutManager
std::shared_ptr<KODI::KEYBOARD::CKeyboardLayoutManager> CServiceBroker::m_keyboardLayoutManager private
m_logging
std::unique_ptr<CLog> CServiceBroker::m_logging private
m_pActiveAE
IAE* CServiceBroker::m_pActiveAE = nullptr private
m_pAnnouncementManager
std::shared_ptr<ANNOUNCEMENT::CAnnouncementManager> CServiceBroker::m_pAnnouncementManager private
m_pAppPort
std::shared_ptr<CAppInboundProtocol> CServiceBroker::m_pAppPort private
m_pGUI
CGUIComponent* CServiceBroker::m_pGUI = nullptr private
m_pSettingsComponent
std::shared_ptr<CSettingsComponent> CServiceBroker::m_pSettingsComponent private
m_pWinSystem
CWinSystemBase* CServiceBroker::m_pWinSystem = nullptr private
m_slideshowDelegator
std::shared_ptr<CSlideShowDelegator> CServiceBroker::m_slideshowDelegator private
m_speechRecognition
std::shared_ptr<speech::ISpeechRecognition> CServiceBroker::m_speechRecognition private
m_textureCache
std::shared_ptr<CTextureCache> CServiceBroker::m_textureCache private
The documentation for this class was generated from the following files:
ServiceBroker.h
ServiceBroker.cpp