Kodi Documentation: ADDON::IAddonInstanceHandler Class Reference
ADDON::IAddonInstanceHandler Class Reference
#include <AddonInstanceHandler.h>
Public Member Functions
IAddonInstanceHandler (ADDON_TYPE type, const AddonInfoPtr &addonInfo, AddonInstanceId instanceId=ADDON_INSTANCE_ID_UNUSED, KODI_HANDLE parentInstance=nullptr, const std::string &uniqueWorkID="")
Class constructor for handling add-on instance processes, allowing an add-on to handle multiple work simultaneously and independently.
virtual ~IAddonInstanceHandler ()
ADDON_TYPE UsedType () const
AddonInstanceId InstanceId () const
const std::string & UniqueWorkID ()
std::string ID () const
AddonInstanceId InstanceID () const
std::string Name () const
std::string Author () const
std::string Icon () const
std::string Path () const
std::string Profile () const
CAddonVersion Version () const
ADDON_STATUS CreateInstance ()
void DestroyInstance ()
const AddonDllPtr & Addon () const
AddonInfoPtr GetAddonInfo () const
virtual void OnPreInstall ()
virtual void OnPostInstall (bool update, bool modal)
virtual void OnPreUnInstall ()
virtual void OnPostUnInstall ()
Protected Attributes
KODI_ADDON_INSTANCE_INFO m_info {}
KODI_ADDON_INSTANCE_STRUCT m_ifc {}
Private Member Functions
std::shared_ptr< CSetting > GetSetting (const std::string &setting)
Static Private Member Functions
static char * get_instance_user_path (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl)
static bool is_instance_setting_using_default (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char *id)
static bool get_instance_setting_bool (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char *id, bool *value)
static bool get_instance_setting_int (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char *id, int *value)
static bool get_instance_setting_float (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char *id, float *value)
static bool get_instance_setting_string (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char *id, char **value)
static bool set_instance_setting_bool (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char *id, bool value)
static bool set_instance_setting_int (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char *id, int value)
static bool set_instance_setting_float (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char *id, float value)
static bool set_instance_setting_string (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char *id, const char *value)
Private Attributes
const ADDON_TYPE m_type
const AddonInstanceId m_instanceId
std::string m_uniqueWorkID
KODI_HANDLE m_parentInstance
AddonInfoPtr m_addonInfo
BinaryAddonBasePtr m_addonBase
AddonDllPtr m_addon
Static Private Attributes
static CCriticalSection m_cdSec
Constructor & Destructor Documentation
IAddonInstanceHandler()
ADDON::IAddonInstanceHandler::IAddonInstanceHandler (ADDON_TYPE type, const AddonInfoPtr & addonInfo, AddonInstanceId instanceId = ADDON_INSTANCE_ID_UNUSED, KODI_HANDLE parentInstance = nullptr, const std::string & uniqueWorkID = "")
Class constructor for handling add-on instance processes, allowing an add-on to handle multiple work simultaneously and independently.
Parameters
[in] type The associated add-on type which is processed in the running instance.
[in] addonInfo Class for querying available add-on information (e.g. content declared in addon.xml).
[in] parentInstance [opt] Above running add-on instance which starts this instance. Used to have the associated class for work to open in the add-on.
Currently used values:
Parent Target Description
kodi::addon::CInstanceInputStream kodi::addon::CInstanceVideoCodec In order to be able to access the overlying input stream instance in the video codec created by Kodi on the add-on.
[in] uniqueWorkID [opt] Identification value intended to pass any special values to the instance to be opened. If not used, the IAddonInstanceHandler class pointer is used as a string.
Currently used values:
Add-on instance type Description
Inputstream To transfer special values to inputstream using the property STREAM_PROPERTY_INPUTSTREAM_INSTANCE_ID from external space, for example PVR add-on which also supports inputstream can exchange special values with it, e.g. select the necessary add-on processing class, since it is not known at the start what is being executed (live TV, radio, recordings...) and add-on may use different classes.
All other The used class pointer of Kodi's IAddonInstanceHandler is used as a value to have an individually different value.
References KODI_ADDON_INSTANCE_STRUCT::functions, get_instance_setting_bool(), get_instance_setting_float(), get_instance_setting_int(), get_instance_setting_string(), get_instance_user_path(), ADDON::CBinaryAddonManager::GetAddonBase(), CServiceBroker::GetBinaryAddonManager(), kodi::addon::GetTypeVersion(), KODI_ADDON_INSTANCE_STRUCT::info, is_instance_setting_using_default(), m_addon, m_addonBase, m_ifc, m_instanceId, m_parentInstance, m_type, m_uniqueWorkID, set_instance_setting_bool(), set_instance_setting_float(), set_instance_setting_int(), and set_instance_setting_string().
~IAddonInstanceHandler()
ADDON::IAddonInstanceHandler::~IAddonInstanceHandler () virtual
References KODI_ADDON_INSTANCE_INFO::functions, KODI_ADDON_INSTANCE_STRUCT::functions, CServiceBroker::GetBinaryAddonManager(), KODI_ADDON_INSTANCE_STRUCT::info, m_addonBase, m_ifc, and ADDON::CBinaryAddonManager::ReleaseAddonBase().
Member Function Documentation
Addon()
const AddonDllPtr & ADDON::IAddonInstanceHandler::Addon () const inline
References m_addon.
Referenced by PVR::CPVRClient::GetFullClientName(), PVR::CPVRClient::GetInstanceName(), PVR::CPVRClient::IsEnabled(), and CInputStreamAddon::Open().
Author()
std::string ADDON::IAddonInstanceHandler::Author () const
References m_addon.
Referenced by PERIPHERALS::CPeripheralAddon::GetAddonProperties().
CreateInstance()
ADDON_STATUS ADDON::IAddonInstanceHandler::CreateInstance ()
References ADDON_STATUS_OK, ADDON_STATUS_UNKNOWN, CLog::Log(), LOGERROR, m_addon, m_cdSec, m_ifc, and kodi::addon::TranslateAddonStatus().
Referenced by CAddonVideoCodec::CAddonVideoCodec(), KODI::ADDONS::CImageDecoder::CImageDecoder(), PVR::CPVRClient::Create(), PERIPHERALS::CPeripheralAddon::CreateAddon(), KODI::ADDONS::CAudioDecoder::CreateDecoder(), KODI::ADDONS::CScreenSaver::CScreenSaver(), ADDON::CVFSEntry::CVFSEntry(), KODI::ADDONS::CVisualization::CVisualization(), KODI::CDRIP::CEncoderAddon::Init(), and CInputStreamAddon::Open().
DestroyInstance()
void ADDON::IAddonInstanceHandler::DestroyInstance ()
References m_addon, m_cdSec, and m_ifc.
Referenced by KODI::CDRIP::CEncoderAddon::Close(), CInputStreamAddon::Close(), PERIPHERALS::CPeripheralAddon::CreateAddon(), PVR::CPVRClient::Destroy(), PERIPHERALS::CPeripheralAddon::DestroyAddon(), CAddonVideoCodec::~CAddonVideoCodec(), KODI::ADDONS::CAudioDecoder::~CAudioDecoder(), KODI::ADDONS::CImageDecoder::~CImageDecoder(), KODI::ADDONS::CScreenSaver::~CScreenSaver(), ADDON::CVFSEntry::~CVFSEntry(), and KODI::ADDONS::CVisualization::~CVisualization().
get_instance_setting_bool()
bool ADDON::IAddonInstanceHandler::get_instance_setting_bool (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char * id, bool * value) static private
References Boolean, CLog::Log(), LOGERROR, and value.
Referenced by IAddonInstanceHandler().
get_instance_setting_float()
bool ADDON::IAddonInstanceHandler::get_instance_setting_float (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char * id, float * value) static private
References CLog::Log(), LOGERROR, Number, and value.
Referenced by IAddonInstanceHandler().
get_instance_setting_int()
bool ADDON::IAddonInstanceHandler::get_instance_setting_int (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char * id, int * value) static private
References Integer, CLog::Log(), LOGERROR, Number, and value.
Referenced by IAddonInstanceHandler().
get_instance_setting_string()
bool ADDON::IAddonInstanceHandler::get_instance_setting_string (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char * id, char ** value) static private
References GetValue(), CLog::Log(), LOGERROR, String, and value.
Referenced by IAddonInstanceHandler().
get_instance_user_path()
char * ADDON::IAddonInstanceHandler::get_instance_user_path (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl) static private
References XFILE::CDirectory::Create(), and CSpecialProtocol::TranslatePath().
Referenced by IAddonInstanceHandler().
GetAddonInfo()
AddonInfoPtr ADDON::IAddonInstanceHandler::GetAddonInfo () const inline
References m_addonInfo.
Referenced by CInputStreamAddon::cb_get_stream_transfer(), and CInputStreamAddon::Open().
GetSetting()
std::shared_ptr< CSetting > ADDON::IAddonInstanceHandler::GetSetting (const std::string & setting) private
References CLog::Log(), LOGERROR, m_addon, m_instanceId, Name(), and value.
Icon()
std::string ADDON::IAddonInstanceHandler::Icon () const
References m_addon.
Referenced by PVR::CPVRClient::cb_recording_notification(), and PVR::CPVRClients::ConnectionStateChange().
ID()
std::string ADDON::IAddonInstanceHandler::ID () const
References m_addon.
Referenced by PVR::CPVRClient::Create(), KODI::ADDONS::CScreenSaver::CScreenSaver(), KODI::ADDONS::CVisualization::CVisualization(), PVR::CPVRClient::GetMenuHooks(), PVR::CPVRClient::HandleAddonCallback(), KODI::ADDONS::CAudioDecoder::Init(), PVR::CPVRClient::IsEnabled(), PERIPHERALS::CPeripheralAddon::PerformDeviceScan(), and PVR::CPVRDatabase::Persist().
InstanceId()
AddonInstanceId ADDON::IAddonInstanceHandler::InstanceId () const inline
References m_instanceId.
Referenced by PVR::CPVRClient::Create(), PVR::CPVRClient::GetFullClientName(), PVR::CPVRClient::GetInstanceName(), and PVR::CPVRClient::IsEnabled().
InstanceID()
AddonInstanceId ADDON::IAddonInstanceHandler::InstanceID () const
References m_instanceId.
Referenced by PVR::CPVRDatabase::Persist().
is_instance_setting_using_default()
bool ADDON::IAddonInstanceHandler::is_instance_setting_using_default (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char * id) static private
Referenced by IAddonInstanceHandler().
Name()
std::string ADDON::IAddonInstanceHandler::Name () const
References m_addon.
Referenced by PERIPHERALS::CPeripheralAddon::CreateAddon(), PERIPHERALS::CPeripheralAddon::GetAddonProperties(), PVR::CPVRClient::GetClientName(), PVR::CPVRClient::GetFullClientName(), GetSetting(), PERIPHERALS::CPeripheralAddon::LogError(), and PVR::CPVRClient::UpdateTimerTypes().
OnPostInstall()
virtual void ADDON::IAddonInstanceHandler::OnPostInstall (bool update, bool modal) inline virtual
OnPostUnInstall()
virtual void ADDON::IAddonInstanceHandler::OnPostUnInstall () inline virtual
OnPreInstall()
virtual void ADDON::IAddonInstanceHandler::OnPreInstall () inline virtual
Reimplemented in PVR::CPVRClient.
OnPreUnInstall()
virtual void ADDON::IAddonInstanceHandler::OnPreUnInstall () inline virtual
Reimplemented in PVR::CPVRClient.
Path()
std::string ADDON::IAddonInstanceHandler::Path () const
References m_addon.
Referenced by CInputStreamAddon::Open(), PVR::CPVRClient::ResetProperties(), and PERIPHERALS::CPeripheralAddon::ResetProperties().
Profile()
std::string ADDON::IAddonInstanceHandler::Profile () const
References m_addon.
Referenced by CInputStreamAddon::Open(), PVR::CPVRClient::ResetProperties(), and PERIPHERALS::CPeripheralAddon::ResetProperties().
set_instance_setting_bool()
bool ADDON::IAddonInstanceHandler::set_instance_setting_bool (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char * id, bool value) static private
References CLog::Log(), LOGERROR, ADDON::Interface_Base::UpdateSettingInActiveDialog(), and value.
Referenced by IAddonInstanceHandler().
set_instance_setting_float()
bool ADDON::IAddonInstanceHandler::set_instance_setting_float (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char * id, float value) static private
References CLog::Log(), LOGERROR, ADDON::Interface_Base::UpdateSettingInActiveDialog(), and value.
Referenced by IAddonInstanceHandler().
set_instance_setting_int()
bool ADDON::IAddonInstanceHandler::set_instance_setting_int (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char * id, int value) static private
References CLog::Log(), LOGERROR, ADDON::Interface_Base::UpdateSettingInActiveDialog(), and value.
Referenced by IAddonInstanceHandler().
set_instance_setting_string()
bool ADDON::IAddonInstanceHandler::set_instance_setting_string (const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char * id, const char * value) static private
References CLog::Log(), LOGERROR, ADDON::Interface_Base::UpdateSettingInActiveDialog(), and value.
Referenced by IAddonInstanceHandler().
UniqueWorkID()
const std::string & ADDON::IAddonInstanceHandler::UniqueWorkID () inline
References m_uniqueWorkID.
UsedType()
ADDON_TYPE ADDON::IAddonInstanceHandler::UsedType () const inline
References m_type.
Version()
CAddonVersion ADDON::IAddonInstanceHandler::Version () const
References m_addon.
Member Data Documentation
m_addon
AddonDllPtr ADDON::IAddonInstanceHandler::m_addon private
Referenced by Addon(), Author(), CreateInstance(), DestroyInstance(), GetSetting(), IAddonInstanceHandler(), Icon(), ID(), Name(), Path(), Profile(), and Version().
m_addonBase
BinaryAddonBasePtr ADDON::IAddonInstanceHandler::m_addonBase private
Referenced by IAddonInstanceHandler(), and ~IAddonInstanceHandler().
m_addonInfo
AddonInfoPtr ADDON::IAddonInstanceHandler::m_addonInfo private
Referenced by GetAddonInfo().
m_cdSec
CCriticalSection ADDON::IAddonInstanceHandler::m_cdSec static private
Referenced by CreateInstance(), and DestroyInstance().
m_ifc
KODI_ADDON_INSTANCE_STRUCT ADDON::IAddonInstanceHandler::m_ifc {} protected
Referenced by CInputStreamAddon::AbortDemux(), CAddonVideoCodec::AddData(), KODI::ADDONS::CVisualization::AudioData(), CAddonVideoCodec::CAddonVideoCodec(), KODI::ADDONS::CAudioDecoder::CAudioDecoder(), KODI::CDRIP::CEncoderAddon::CEncoderAddon(), KODI::ADDONS::CImageDecoder::CImageDecoder(), ADDON::CVFSEntry::ClearOutIdle(), KODI::CDRIP::CEncoderAddon::Close(), CInputStreamAddon::Close(), ADDON::CVFSEntry::Close(), ADDON::CVFSEntry::ContainsFiles(), PERIPHERALS::CPeripheralAddon::CPeripheralAddon(), PVR::CPVRClient::CPVRClient(), ADDON::CVFSEntry::CreateDirectory(), CreateInstance(), KODI::ADDONS::CScreenSaver::CScreenSaver(), ADDON::CVFSEntry::CVFSEntry(), KODI::ADDONS::CVisualization::CVisualization(), KODI::ADDONS::CImageDecoder::Decode(), ADDON::CVFSEntry::Delete(), DestroyInstance(), ADDON::CVFSEntry::DirectoryExists(), ADDON::CVFSEntry::DisconnectAll(), PVR::CPVRClient::DoAddonCall(), CInputStreamAddon::EnableStream(), KODI::CDRIP::CEncoderAddon::Encode(), ADDON::CVFSEntry::Exists(), CInputStreamAddon::FlushDemux(), KODI::ADDONS::CVisualization::GetActivePreset(), PERIPHERALS::CPeripheralAddon::GetAddonProperties(), PERIPHERALS::CPeripheralAddon::GetAppearance(), CInputStreamAddon::GetBlockSize(), CInputStreamAddon::GetChapter(), CInputStreamAddon::GetChapterCount(), CInputStreamAddon::GetChapterName(), CInputStreamAddon::GetChapterPos(), ADDON::CVFSEntry::GetChunkSize(), ADDON::CVFSEntry::GetDirectory(), PERIPHERALS::CPeripheralAddon::GetFeatures(), PERIPHERALS::CPeripheralAddon::GetIgnoredPrimitives(), PERIPHERALS::CPeripheralAddon::GetJoystickProperties(), CInputStreamAddon::GetLength(), ADDON::CVFSEntry::GetLength(), CAddonVideoCodec::GetName(), CAddonVideoCodec::GetPicture(), ADDON::CVFSEntry::GetPosition(), CInputStreamAddon::GetStream(), CInputStreamAddon::GetStreams(), KODI::ADDONS::CVisualization::GetSyncDelay(), CInputStreamAddon::GetTime(), CInputStreamAddon::GetTimes(), CInputStreamAddon::GetTotalTime(), KODI::ADDONS::CAudioDecoder::GetTrackCount(), IAddonInstanceHandler(), KODI::CDRIP::CEncoderAddon::Init(), KODI::ADDONS::CAudioDecoder::Init(), ADDON::CVFSEntry::IoControl(), KODI::ADDONS::CVisualization::IsDirty(), KODI::ADDONS::CVisualization::IsLocked(), CInputStreamAddon::IsRealtime(), KODI::ADDONS::CAudioDecoder::Load(), KODI::ADDONS::CImageDecoder::LoadImageFromMemory(), KODI::ADDONS::CImageDecoder::LoadInfoTag(), KODI::ADDONS::CVisualization::LoadPreset(), KODI::ADDONS::CVisualization::LockPreset(), PERIPHERALS::CPeripheralAddon::MapFeature(), KODI::ADDONS::CVisualization::NextPreset(), CInputStreamAddon::Open(), CAddonVideoCodec::Open(), ADDON::CVFSEntry::Open(), ADDON::CVFSEntry::OpenForWrite(), CInputStreamAddon::OpenStream(), PERIPHERALS::CPeripheralAddon::PerformDeviceScan(), CInputStreamAddon::PosTime(), PERIPHERALS::CPeripheralAddon::PowerOffJoystick(), KODI::ADDONS::CVisualization::PrevPreset(), PERIPHERALS::CPeripheralAddon::ProcessEvents(), KODI::ADDONS::CVisualization::RandomPreset(), KODI::ADDONS::CVisualization::RatePreset(), CInputStreamAddon::Read(), ADDON::CVFSEntry::Read(), CInputStreamAddon::ReadDemux(), KODI::ADDONS::CAudioDecoder::ReadPCM(), CAddonVideoCodec::Reconfigure(), ADDON::CVFSEntry::RemoveDirectory(), ADDON::CVFSEntry::Rename(), KODI::ADDONS::CScreenSaver::Render(), KODI::ADDONS::CVisualization::Render(), CAddonVideoCodec::Reset(), PERIPHERALS::CPeripheralAddon::ResetButtonMap(), PVR::CPVRClient::ResetProperties(), PERIPHERALS::CPeripheralAddon::ResetProperties(), PERIPHERALS::CPeripheralAddon::RevertButtonMap(), PERIPHERALS::CPeripheralAddon::SaveButtonMap(), CInputStreamAddon::Seek(), KODI::ADDONS::CAudioDecoder::Seek(), ADDON::CVFSEntry::Seek(), CInputStreamAddon::SeekChapter(), CInputStreamAddon::SeekTime(), PERIPHERALS::CPeripheralAddon::SendRumbleEvent(), PERIPHERALS::CPeripheralAddon::SetAppearance(), PERIPHERALS::CPeripheralAddon::SetIgnoredPrimitives(), CInputStreamAddon::SetSpeed(), CInputStreamAddon::SetVideoResolution(), KODI::ADDONS::CScreenSaver::Start(), KODI::ADDONS::CVisualization::Start(), ADDON::CVFSEntry::Stat(), KODI::ADDONS::CScreenSaver::Stop(), KODI::ADDONS::CVisualization::Stop(), KODI::ADDONS::CAudioDecoder::SupportsFile(), KODI::ADDONS::CImageDecoder::SupportsFile(), ADDON::CVFSEntry::Truncate(), KODI::ADDONS::CVisualization::UpdateAlbumart(), KODI::ADDONS::CVisualization::UpdateTrack(), ADDON::CVFSEntry::Write(), CAddonVideoCodec::~CAddonVideoCodec(), KODI::ADDONS::CAudioDecoder::~CAudioDecoder(), KODI::CDRIP::CEncoderAddon::~CEncoderAddon(), KODI::ADDONS::CImageDecoder::~CImageDecoder(), PERIPHERALS::CPeripheralAddon::~CPeripheralAddon(), PVR::CPVRClient::~CPVRClient(), KODI::ADDONS::CScreenSaver::~CScreenSaver(), ADDON::CVFSEntry::~CVFSEntry(), KODI::ADDONS::CVisualization::~CVisualization(), and ~IAddonInstanceHandler().
m_info
KODI_ADDON_INSTANCE_INFO ADDON::IAddonInstanceHandler::m_info {} protected
m_instanceId
const AddonInstanceId ADDON::IAddonInstanceHandler::m_instanceId private
Referenced by GetSetting(), IAddonInstanceHandler(), InstanceId(), and InstanceID().
m_parentInstance
KODI_HANDLE ADDON::IAddonInstanceHandler::m_parentInstance private
Referenced by IAddonInstanceHandler().
m_type
const ADDON_TYPE ADDON::IAddonInstanceHandler::m_type private
Referenced by IAddonInstanceHandler(), and UsedType().
m_uniqueWorkID
std::string ADDON::IAddonInstanceHandler::m_uniqueWorkID private
Referenced by IAddonInstanceHandler(), and UniqueWorkID().
The documentation for this class was generated from the following files:
AddonInstanceHandler.h
AddonInstanceHandler.cpp