Kodi Documentation: 8. Inputstream
8. Inputstream
C++ » Interface - kodi::addon » Addon type instances » PVR
PVR Inputstream
This includes functions that are used in the PVR inputstream.
Modules
8.1. TV stream
PVR TV stream
Stream processing regarding live TV.
8.2. Recording stream
PVR Recording stream
Stream processing regarding recordings.
8.3. Various functions
Various other PVR stream related functions
These apply to all other groups in inputstream and are therefore declared as several.
Functions
void kodi::addon::CInstancePVRClient::SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT *instance)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetCapabilities (const AddonInstance_PVR *instance, PVR_ADDON_CAPABILITIES *capabilities)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeCapabilities (const AddonInstance_PVR *instance, PVR_ADDON_CAPABILITIES *capabilities)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetBackendName (const AddonInstance_PVR *instance, char **str)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetBackendVersion (const AddonInstance_PVR *instance, char **str)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetBackendHostname (const AddonInstance_PVR *instance, char **str)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetConnectionString (const AddonInstance_PVR *instance, char **str)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetDriveSpace (const AddonInstance_PVR *instance, uint64_t *total, uint64_t *used)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_CallSettingsMenuHook (const AddonInstance_PVR *instance, const PVR_MENUHOOK *menuhook)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannelsAmount (const AddonInstance_PVR *instance, int *amount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannels (const AddonInstance_PVR *instance, PVR_HANDLE handle, bool radio)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannelStreamProperties (const AddonInstance_PVR *instance, const PVR_CHANNEL *channel, PVR_SOURCE source, PVR_NAMED_VALUE ***properties, unsigned int *propertiesCount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetSignalStatus (const AddonInstance_PVR *instance, int channelUid, PVR_SIGNAL_STATUS *signalStatus)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeSignalStatus (const AddonInstance_PVR *instance, PVR_SIGNAL_STATUS *signalStatus)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetDescrambleInfo (const AddonInstance_PVR *instance, int channelUid, PVR_DESCRAMBLE_INFO *descrambleInfo)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeDescrambleInfo (const AddonInstance_PVR *instance, PVR_DESCRAMBLE_INFO *descrambleInfo)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetProvidersAmount (const AddonInstance_PVR *instance, int *amount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetProviders (const AddonInstance_PVR *instance, PVR_HANDLE handle)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannelGroupsAmount (const AddonInstance_PVR *instance, int *amount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannelGroups (const AddonInstance_PVR *instance, PVR_HANDLE handle, bool radio)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannelGroupMembers (const AddonInstance_PVR *instance, PVR_HANDLE handle, const PVR_CHANNEL_GROUP *group)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_DeleteChannel (const AddonInstance_PVR *instance, const PVR_CHANNEL *channel)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_RenameChannel (const AddonInstance_PVR *instance, const PVR_CHANNEL *channel)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OpenDialogChannelSettings (const AddonInstance_PVR *instance, const PVR_CHANNEL *channel)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OpenDialogChannelAdd (const AddonInstance_PVR *instance, const PVR_CHANNEL *channel)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OpenDialogChannelScan (const AddonInstance_PVR *instance)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_CallChannelMenuHook (const AddonInstance_PVR *instance, const PVR_MENUHOOK *menuhook, const PVR_CHANNEL *channel)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetEPGForChannel (const AddonInstance_PVR *instance, PVR_HANDLE handle, int channelUid, time_t start, time_t end)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_IsEPGTagRecordable (const AddonInstance_PVR *instance, const EPG_TAG *tag, bool *isRecordable)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_IsEPGTagPlayable (const AddonInstance_PVR *instance, const EPG_TAG *tag, bool *isPlayable)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetEPGTagEdl (const AddonInstance_PVR *instance, const EPG_TAG *tag, PVR_EDL_ENTRY ***edls, unsigned int *size)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetEPGTagStreamProperties (const AddonInstance_PVR *instance, const EPG_TAG *tag, PVR_NAMED_VALUE ***properties, unsigned int *propertiesCount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_SetEPGMaxPastDays (const AddonInstance_PVR *instance, int pastDays)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_SetEPGMaxFutureDays (const AddonInstance_PVR *instance, int futureDays)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_CallEPGMenuHook (const AddonInstance_PVR *instance, const PVR_MENUHOOK *menuhook, const EPG_TAG *tag)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordingsAmount (const AddonInstance_PVR *instance, bool deleted, int *amount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordings (const AddonInstance_PVR *instance, PVR_HANDLE handle, bool deleted)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_DeleteRecording (const AddonInstance_PVR *instance, const PVR_RECORDING *recording)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_UndeleteRecording (const AddonInstance_PVR *instance, const PVR_RECORDING *recording)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_DeleteAllRecordingsFromTrash (const AddonInstance_PVR *instance)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_RenameRecording (const AddonInstance_PVR *instance, const PVR_RECORDING *recording)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_SetRecordingLifetime (const AddonInstance_PVR *instance, const PVR_RECORDING *recording)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_SetRecordingPlayCount (const AddonInstance_PVR *instance, const PVR_RECORDING *recording, int count)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_SetRecordingLastPlayedPosition (const AddonInstance_PVR *instance, const PVR_RECORDING *recording, int lastplayedposition)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordingLastPlayedPosition (const AddonInstance_PVR *instance, const PVR_RECORDING *recording, int *position)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordingEdl (const AddonInstance_PVR *instance, const PVR_RECORDING *recording, PVR_EDL_ENTRY ***edls, unsigned int *size)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeEdlEntries (const AddonInstance_PVR *instance, PVR_EDL_ENTRY **edls, unsigned int size)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordingSize (const AddonInstance_PVR *instance, const PVR_RECORDING *recording, int64_t *size)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordingStreamProperties (const AddonInstance_PVR *instance, const PVR_RECORDING *recording, PVR_NAMED_VALUE ***properties, unsigned int *propertiesCount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeProperties (const AddonInstance_PVR *instance, PVR_NAMED_VALUE **properties, unsigned int propertiesCount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_CallRecordingMenuHook (const AddonInstance_PVR *instance, const PVR_MENUHOOK *menuhook, const PVR_RECORDING *recording)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetTimerTypes (const AddonInstance_PVR *instance, PVR_TIMER_TYPE ***types, unsigned int *typesCount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeTimerTypes (const AddonInstance_PVR *instance, PVR_TIMER_TYPE **types, unsigned int typesCount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetTimersAmount (const AddonInstance_PVR *instance, int *amount)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetTimers (const AddonInstance_PVR *instance, PVR_HANDLE handle)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_AddTimer (const AddonInstance_PVR *instance, const PVR_TIMER *timer)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_DeleteTimer (const AddonInstance_PVR *instance, const PVR_TIMER *timer, bool forceDelete)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_UpdateTimer (const AddonInstance_PVR *instance, const PVR_TIMER *timer)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_CallTimerMenuHook (const AddonInstance_PVR *instance, const PVR_MENUHOOK *menuhook, const PVR_TIMER *timer)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OnSystemSleep (const AddonInstance_PVR *instance)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OnSystemWake (const AddonInstance_PVR *instance)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OnPowerSavingActivated (const AddonInstance_PVR *instance)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OnPowerSavingDeactivated (const AddonInstance_PVR *instance)
Variables
AddonInstance_PVR * kodi::addon::CInstancePVRClient::m_instanceData = nullptr
static bool kodi::addon::CInstancePVRClient::ADDON_OpenLiveStream (const AddonInstance_PVR *instance, const PVR_CHANNEL *channel)
static void kodi::addon::CInstancePVRClient::ADDON_CloseLiveStream (const AddonInstance_PVR *instance)
static int kodi::addon::CInstancePVRClient::ADDON_ReadLiveStream (const AddonInstance_PVR *instance, unsigned char *buffer, unsigned int size)
static int64_t kodi::addon::CInstancePVRClient::ADDON_SeekLiveStream (const AddonInstance_PVR *instance, int64_t position, int whence)
static int64_t kodi::addon::CInstancePVRClient::ADDON_LengthLiveStream (const AddonInstance_PVR *instance)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetStreamProperties (const AddonInstance_PVR *instance, PVR_STREAM_PROPERTIES *properties)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_StreamClosed (const AddonInstance_PVR *instance)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetStreamReadChunkSize (const AddonInstance_PVR *instance, int *chunksize)
static bool kodi::addon::CInstancePVRClient::ADDON_IsRealTimeStream (const AddonInstance_PVR *instance)
static bool kodi::addon::CInstancePVRClient::ADDON_OpenRecordedStream (const AddonInstance_PVR *instance, const PVR_RECORDING *recording, int64_t *streamId)
static void kodi::addon::CInstancePVRClient::ADDON_CloseRecordedStream (const AddonInstance_PVR *instance, int64_t streamId)
static int kodi::addon::CInstancePVRClient::ADDON_ReadRecordedStream (const AddonInstance_PVR *instance, int64_t streamId, unsigned char *buffer, unsigned int size)
static int64_t kodi::addon::CInstancePVRClient::ADDON_SeekRecordedStream (const AddonInstance_PVR *instance, int64_t streamId, int64_t position, int whence)
static int64_t kodi::addon::CInstancePVRClient::ADDON_LengthRecordedStream (const AddonInstance_PVR *instance, int64_t streamId)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_IsRecordedStreamRealTime (const AddonInstance_PVR *instance, int64_t streamId, bool *isRealTime)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_PauseRecordedStream (const AddonInstance_PVR *instance, int64_t streamId, bool paused)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordedStreamTimes (const AddonInstance_PVR *instance, int64_t streamId, PVR_STREAM_TIMES *times)
static void kodi::addon::CInstancePVRClient::ADDON_DemuxReset (const AddonInstance_PVR *instance)
static void kodi::addon::CInstancePVRClient::ADDON_DemuxAbort (const AddonInstance_PVR *instance)
static void kodi::addon::CInstancePVRClient::ADDON_DemuxFlush (const AddonInstance_PVR *instance)
static DEMUX_PACKET * kodi::addon::CInstancePVRClient::ADDON_DemuxRead (const AddonInstance_PVR *instance)
static bool kodi::addon::CInstancePVRClient::ADDON_CanPauseStream (const AddonInstance_PVR *instance)
static bool kodi::addon::CInstancePVRClient::ADDON_CanSeekStream (const AddonInstance_PVR *instance)
static void kodi::addon::CInstancePVRClient::ADDON_PauseStream (const AddonInstance_PVR *instance, bool bPaused)
static bool kodi::addon::CInstancePVRClient::ADDON_SeekTime (const AddonInstance_PVR *instance, double time, bool backwards, double *startpts)
static void kodi::addon::CInstancePVRClient::ADDON_SetSpeed (const AddonInstance_PVR *instance, int speed)
static void kodi::addon::CInstancePVRClient::ADDON_FillBuffer (const AddonInstance_PVR *instance, bool mode)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetStreamTimes (const AddonInstance_PVR *instance, PVR_STREAM_TIMES *times)
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeString (const AddonInstance_PVR *instance, char *str)
Detailed Description
PVR Inputstream
This includes functions that are used in the PVR inputstream.
Warning
The parts here will be removed in the future and replaced by the separate inputstream addon instance. If there is already a possibility, new addons should do it via the inputstream instance.
Function Documentation
ADDON_AddTimer()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_AddTimer (const AddonInstance_PVR * instance, const PVR_TIMER * timer) inline static private
ADDON_CallChannelMenuHook()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_CallChannelMenuHook (const AddonInstance_PVR * instance, const PVR_MENUHOOK * menuhook, const PVR_CHANNEL * channel) inline static private
ADDON_CallEPGMenuHook()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_CallEPGMenuHook (const AddonInstance_PVR * instance, const PVR_MENUHOOK * menuhook, const EPG_TAG * tag) inline static private
ADDON_CallRecordingMenuHook()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_CallRecordingMenuHook (const AddonInstance_PVR * instance, const PVR_MENUHOOK * menuhook, const PVR_RECORDING * recording) inline static private
ADDON_CallSettingsMenuHook()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_CallSettingsMenuHook (const AddonInstance_PVR * instance, const PVR_MENUHOOK * menuhook) inline static private
ADDON_CallTimerMenuHook()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_CallTimerMenuHook (const AddonInstance_PVR * instance, const PVR_MENUHOOK * menuhook, const PVR_TIMER * timer) inline static private
ADDON_CanPauseStream()
static bool kodi::addon::CInstancePVRClient::ADDON_CanPauseStream (const AddonInstance_PVR * instance) inline static private
ADDON_CanSeekStream()
static bool kodi::addon::CInstancePVRClient::ADDON_CanSeekStream (const AddonInstance_PVR * instance) inline static private
ADDON_CloseLiveStream()
static void kodi::addon::CInstancePVRClient::ADDON_CloseLiveStream (const AddonInstance_PVR * instance) inline static private
ADDON_CloseRecordedStream()
static void kodi::addon::CInstancePVRClient::ADDON_CloseRecordedStream (const AddonInstance_PVR * instance, int64_t streamId) inline static private
ADDON_DeleteAllRecordingsFromTrash()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_DeleteAllRecordingsFromTrash (const AddonInstance_PVR * instance) inline static private
ADDON_DeleteChannel()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_DeleteChannel (const AddonInstance_PVR * instance, const PVR_CHANNEL * channel) inline static private
ADDON_DeleteRecording()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_DeleteRecording (const AddonInstance_PVR * instance, const PVR_RECORDING * recording) inline static private
ADDON_DeleteTimer()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_DeleteTimer (const AddonInstance_PVR * instance, const PVR_TIMER * timer, bool forceDelete) inline static private
ADDON_DemuxAbort()
static void kodi::addon::CInstancePVRClient::ADDON_DemuxAbort (const AddonInstance_PVR * instance) inline static private
ADDON_DemuxFlush()
static void kodi::addon::CInstancePVRClient::ADDON_DemuxFlush (const AddonInstance_PVR * instance) inline static private
ADDON_DemuxRead()
static DEMUX_PACKET * kodi::addon::CInstancePVRClient::ADDON_DemuxRead (const AddonInstance_PVR * instance) inline static private
ADDON_DemuxReset()
static void kodi::addon::CInstancePVRClient::ADDON_DemuxReset (const AddonInstance_PVR * instance) inline static private
ADDON_FillBuffer()
static void kodi::addon::CInstancePVRClient::ADDON_FillBuffer (const AddonInstance_PVR * instance, bool mode) inline static private
ADDON_FreeCapabilities()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeCapabilities (const AddonInstance_PVR * instance, PVR_ADDON_CAPABILITIES * capabilities) inline static private
References PVR_ERROR_NO_ERROR.
ADDON_FreeDescrambleInfo()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeDescrambleInfo (const AddonInstance_PVR * instance, PVR_DESCRAMBLE_INFO * descrambleInfo) inline static private
References PVR_ERROR_NO_ERROR.
ADDON_FreeEdlEntries()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeEdlEntries (const AddonInstance_PVR * instance, PVR_EDL_ENTRY ** edls, unsigned int size) inline static private
References PVR_ERROR_NO_ERROR.
ADDON_FreeProperties()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeProperties (const AddonInstance_PVR * instance, PVR_NAMED_VALUE ** properties, unsigned int propertiesCount) inline static private
References PVR_ERROR_NO_ERROR.
ADDON_FreeSignalStatus()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeSignalStatus (const AddonInstance_PVR * instance, PVR_SIGNAL_STATUS * signalStatus) inline static private
References PVR_ERROR_NO_ERROR.
ADDON_FreeString()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeString (const AddonInstance_PVR * instance, char * str) inline static private
References kodi::addon::FreeString(), and PVR_ERROR_NO_ERROR.
ADDON_FreeTimerTypes()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_FreeTimerTypes (const AddonInstance_PVR * instance, PVR_TIMER_TYPE ** types, unsigned int typesCount) inline static private
References PVR_ERROR_NO_ERROR, and types.
ADDON_GetBackendHostname()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetBackendHostname (const AddonInstance_PVR * instance, char ** str) inline static private
References kodi::addon::AllocAndCopyString(), err(), and PVR_ERROR_NO_ERROR.
ADDON_GetBackendName()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetBackendName (const AddonInstance_PVR * instance, char ** str) inline static private
References kodi::addon::AllocAndCopyString(), err(), and PVR_ERROR_NO_ERROR.
ADDON_GetBackendVersion()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetBackendVersion (const AddonInstance_PVR * instance, char ** str) inline static private
References kodi::addon::AllocAndCopyString(), err(), and PVR_ERROR_NO_ERROR.
ADDON_GetCapabilities()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetCapabilities (const AddonInstance_PVR * instance, PVR_ADDON_CAPABILITIES * capabilities) inline static private
ADDON_GetChannelGroupMembers()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannelGroupMembers (const AddonInstance_PVR * instance, PVR_HANDLE handle, const PVR_CHANNEL_GROUP * group) inline static private
ADDON_GetChannelGroups()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannelGroups (const AddonInstance_PVR * instance, PVR_HANDLE handle, bool radio) inline static private
ADDON_GetChannelGroupsAmount()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannelGroupsAmount (const AddonInstance_PVR * instance, int * amount) inline static private
ADDON_GetChannels()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannels (const AddonInstance_PVR * instance, PVR_HANDLE handle, bool radio) inline static private
ADDON_GetChannelsAmount()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannelsAmount (const AddonInstance_PVR * instance, int * amount) inline static private
ADDON_GetChannelStreamProperties()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetChannelStreamProperties (const AddonInstance_PVR * instance, const PVR_CHANNEL * channel, PVR_SOURCE source, PVR_NAMED_VALUE *** properties, unsigned int * propertiesCount) inline static private
References PVR_ERROR_NO_ERROR.
ADDON_GetConnectionString()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetConnectionString (const AddonInstance_PVR * instance, char ** str) inline static private
References kodi::addon::AllocAndCopyString(), err(), and PVR_ERROR_NO_ERROR.
ADDON_GetDescrambleInfo()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetDescrambleInfo (const AddonInstance_PVR * instance, int channelUid, PVR_DESCRAMBLE_INFO * descrambleInfo) inline static private
ADDON_GetDriveSpace()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetDriveSpace (const AddonInstance_PVR * instance, uint64_t * total, uint64_t * used) inline static private
ADDON_GetEPGForChannel()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetEPGForChannel (const AddonInstance_PVR * instance, PVR_HANDLE handle, int channelUid, time_t start, time_t end) inline static private
References end().
ADDON_GetEPGTagEdl()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetEPGTagEdl (const AddonInstance_PVR * instance, const EPG_TAG * tag, PVR_EDL_ENTRY *** edls, unsigned int * size) inline static private
References PVR_ERROR_NO_ERROR.
ADDON_GetEPGTagStreamProperties()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetEPGTagStreamProperties (const AddonInstance_PVR * instance, const EPG_TAG * tag, PVR_NAMED_VALUE *** properties, unsigned int * propertiesCount) inline static private
References PVR_ERROR_NO_ERROR.
ADDON_GetProviders()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetProviders (const AddonInstance_PVR * instance, PVR_HANDLE handle) inline static private
ADDON_GetProvidersAmount()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetProvidersAmount (const AddonInstance_PVR * instance, int * amount) inline static private
ADDON_GetRecordedStreamTimes()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordedStreamTimes (const AddonInstance_PVR * instance, int64_t streamId, PVR_STREAM_TIMES * times) inline static private
ADDON_GetRecordingEdl()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordingEdl (const AddonInstance_PVR * instance, const PVR_RECORDING * recording, PVR_EDL_ENTRY *** edls, unsigned int * size) inline static private
References PVR_ERROR_NO_ERROR.
ADDON_GetRecordingLastPlayedPosition()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordingLastPlayedPosition (const AddonInstance_PVR * instance, const PVR_RECORDING * recording, int * position) inline static private
ADDON_GetRecordings()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordings (const AddonInstance_PVR * instance, PVR_HANDLE handle, bool deleted) inline static private
ADDON_GetRecordingsAmount()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordingsAmount (const AddonInstance_PVR * instance, bool deleted, int * amount) inline static private
ADDON_GetRecordingSize()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordingSize (const AddonInstance_PVR * instance, const PVR_RECORDING * recording, int64_t * size) inline static private
ADDON_GetRecordingStreamProperties()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetRecordingStreamProperties (const AddonInstance_PVR * instance, const PVR_RECORDING * recording, PVR_NAMED_VALUE *** properties, unsigned int * propertiesCount) inline static private
References PVR_ERROR_NO_ERROR.
ADDON_GetSignalStatus()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetSignalStatus (const AddonInstance_PVR * instance, int channelUid, PVR_SIGNAL_STATUS * signalStatus) inline static private
ADDON_GetStreamProperties()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetStreamProperties (const AddonInstance_PVR * instance, PVR_STREAM_PROPERTIES * properties) inline static private
References ADDON_LOG_ERROR, err(), PVR_STREAM_PROPERTIES::iStreamCount, kodi::Log(), PVR_ERROR_NO_ERROR, PVR_STREAM_MAX_STREAMS, and PVR_STREAM_PROPERTIES::stream.
ADDON_GetStreamReadChunkSize()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetStreamReadChunkSize (const AddonInstance_PVR * instance, int * chunksize) inline static private
ADDON_GetStreamTimes()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetStreamTimes (const AddonInstance_PVR * instance, PVR_STREAM_TIMES * times) inline static private
ADDON_GetTimers()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetTimers (const AddonInstance_PVR * instance, PVR_HANDLE handle) inline static private
ADDON_GetTimersAmount()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetTimersAmount (const AddonInstance_PVR * instance, int * amount) inline static private
ADDON_GetTimerTypes()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_GetTimerTypes (const AddonInstance_PVR * instance, PVR_TIMER_TYPE *** types, unsigned int * typesCount) inline static private
References PVR_ERROR_NO_ERROR, and types.
ADDON_IsEPGTagPlayable()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_IsEPGTagPlayable (const AddonInstance_PVR * instance, const EPG_TAG * tag, bool * isPlayable) inline static private
ADDON_IsEPGTagRecordable()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_IsEPGTagRecordable (const AddonInstance_PVR * instance, const EPG_TAG * tag, bool * isRecordable) inline static private
ADDON_IsRealTimeStream()
static bool kodi::addon::CInstancePVRClient::ADDON_IsRealTimeStream (const AddonInstance_PVR * instance) inline static private
ADDON_IsRecordedStreamRealTime()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_IsRecordedStreamRealTime (const AddonInstance_PVR * instance, int64_t streamId, bool * isRealTime) inline static private
ADDON_LengthLiveStream()
static int64_t kodi::addon::CInstancePVRClient::ADDON_LengthLiveStream (const AddonInstance_PVR * instance) inline static private
ADDON_LengthRecordedStream()
static int64_t kodi::addon::CInstancePVRClient::ADDON_LengthRecordedStream (const AddonInstance_PVR * instance, int64_t streamId) inline static private
ADDON_OnPowerSavingActivated()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OnPowerSavingActivated (const AddonInstance_PVR * instance) inline static private
ADDON_OnPowerSavingDeactivated()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OnPowerSavingDeactivated (const AddonInstance_PVR * instance) inline static private
ADDON_OnSystemSleep()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OnSystemSleep (const AddonInstance_PVR * instance) inline static private
ADDON_OnSystemWake()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OnSystemWake (const AddonInstance_PVR * instance) inline static private
ADDON_OpenDialogChannelAdd()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OpenDialogChannelAdd (const AddonInstance_PVR * instance, const PVR_CHANNEL * channel) inline static private
ADDON_OpenDialogChannelScan()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OpenDialogChannelScan (const AddonInstance_PVR * instance) inline static private
ADDON_OpenDialogChannelSettings()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_OpenDialogChannelSettings (const AddonInstance_PVR * instance, const PVR_CHANNEL * channel) inline static private
ADDON_OpenLiveStream()
static bool kodi::addon::CInstancePVRClient::ADDON_OpenLiveStream (const AddonInstance_PVR * instance, const PVR_CHANNEL * channel) inline static private
ADDON_OpenRecordedStream()
static bool kodi::addon::CInstancePVRClient::ADDON_OpenRecordedStream (const AddonInstance_PVR * instance, const PVR_RECORDING * recording, int64_t * streamId) inline static private
ADDON_PauseRecordedStream()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_PauseRecordedStream (const AddonInstance_PVR * instance, int64_t streamId, bool paused) inline static private
ADDON_PauseStream()
static void kodi::addon::CInstancePVRClient::ADDON_PauseStream (const AddonInstance_PVR * instance, bool bPaused) inline static private
ADDON_ReadLiveStream()
static int kodi::addon::CInstancePVRClient::ADDON_ReadLiveStream (const AddonInstance_PVR * instance, unsigned char * buffer, unsigned int size) inline static private
ADDON_ReadRecordedStream()
static int kodi::addon::CInstancePVRClient::ADDON_ReadRecordedStream (const AddonInstance_PVR * instance, int64_t streamId, unsigned char * buffer, unsigned int size) inline static private
ADDON_RenameChannel()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_RenameChannel (const AddonInstance_PVR * instance, const PVR_CHANNEL * channel) inline static private
ADDON_RenameRecording()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_RenameRecording (const AddonInstance_PVR * instance, const PVR_RECORDING * recording) inline static private
ADDON_SeekLiveStream()
static int64_t kodi::addon::CInstancePVRClient::ADDON_SeekLiveStream (const AddonInstance_PVR * instance, int64_t position, int whence) inline static private
ADDON_SeekRecordedStream()
static int64_t kodi::addon::CInstancePVRClient::ADDON_SeekRecordedStream (const AddonInstance_PVR * instance, int64_t streamId, int64_t position, int whence) inline static private
ADDON_SeekTime()
static bool kodi::addon::CInstancePVRClient::ADDON_SeekTime (const AddonInstance_PVR * instance, double time, bool backwards, double * startpts) inline static private
ADDON_SetEPGMaxFutureDays()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_SetEPGMaxFutureDays (const AddonInstance_PVR * instance, int futureDays) inline static private
ADDON_SetEPGMaxPastDays()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_SetEPGMaxPastDays (const AddonInstance_PVR * instance, int pastDays) inline static private
ADDON_SetRecordingLastPlayedPosition()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_SetRecordingLastPlayedPosition (const AddonInstance_PVR * instance, const PVR_RECORDING * recording, int lastplayedposition) inline static private
ADDON_SetRecordingLifetime()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_SetRecordingLifetime (const AddonInstance_PVR * instance, const PVR_RECORDING * recording) inline static private
ADDON_SetRecordingPlayCount()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_SetRecordingPlayCount (const AddonInstance_PVR * instance, const PVR_RECORDING * recording, int count) inline static private
ADDON_SetSpeed()
static void kodi::addon::CInstancePVRClient::ADDON_SetSpeed (const AddonInstance_PVR * instance, int speed) inline static private
ADDON_StreamClosed()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_StreamClosed (const AddonInstance_PVR * instance) inline static private
ADDON_UndeleteRecording()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_UndeleteRecording (const AddonInstance_PVR * instance, const PVR_RECORDING * recording) inline static private
ADDON_UpdateTimer()
static PVR_ERROR kodi::addon::CInstancePVRClient::ADDON_UpdateTimer (const AddonInstance_PVR * instance, const PVR_TIMER * timer) inline static private
SetAddonStruct()
void kodi::addon::CInstancePVRClient::SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT * instance) inline private
References KodiToAddonFuncTable_PVR::addonInstance, KodiToAddonFuncTable_PVR::DemuxRead(), KODI_ADDON_INSTANCE_STRUCT::hdl, KODI_ADDON_INSTANCE_STRUCT::pvr, and AddonInstance_PVR::toAddon.
Variable Documentation
m_instanceData
AddonInstance_PVR* kodi::addon::CInstancePVRClient::m_instanceData = nullptr private