Kodi Documentation: ImageFactory Class Reference
ImageFactory Class Reference
#include <imagefactory.h>
Public Member Functions
ImageFactory ()=default
virtual ~ImageFactory ()=default
Static Public Member Functions
static IImage * CreateLoader (const std::string &strFileName)
static IImage * CreateLoader (const CURL &url)
static IImage * CreateLoaderFromMimeType (const std::string &strMimeType)
Static Private Attributes
static CCriticalSection m_createSec
Critical section for add-on creation.
Constructor & Destructor Documentation
ImageFactory()
ImageFactory::ImageFactory () default
~ImageFactory()
virtual ImageFactory::~ImageFactory () virtual default
Member Function Documentation
CreateLoader() [1/2]
IImage * ImageFactory::CreateLoader (const CURL & url) static
References CreateLoaderFromMimeType(), CURL::GetFileType(), and CMime::GetMimeType().
CreateLoader() [2/2]
IImage * ImageFactory::CreateLoader (const std::string & strFileName) static
References CreateLoader().
Referenced by CreateLoader(), CPicture::CreateThumbnailFromSurface(), CPicture::GetThumbnailFromSurface(), and CTexture::LoadFromFileInternal().
CreateLoaderFromMimeType()
IImage * ImageFactory::CreateLoaderFromMimeType (const std::string & strMimeType) static
References CServiceBroker::GetExtsMimeSupportList(), KODI::ADDONS::CExtsMimeSupportList::GetMimetypeSupportedAddonInfos(), ADDON::IMAGEDECODER, and m_createSec.
Referenced by CreateLoader(), CTexture::LoadFromFileInMem(), and CTexture::LoadFromFileInternal().
Member Data Documentation
m_createSec
CCriticalSection ImageFactory::m_createSec static private
Critical section for add-on creation.
Referenced by CreateLoaderFromMimeType().
The documentation for this class was generated from the following files:
imagefactory.h
imagefactory.cpp