Kodi Documentation: CRendererShaders::CRenderBufferImpl Class Reference
CRendererShaders::CRenderBufferImpl Class Reference
#include <RendererShaders.h>
Public Member Functions
CRenderBufferImpl (AVPixelFormat av_pix_format, unsigned width, unsigned height)
~CRenderBufferImpl ()
void AppendPicture (const VideoPicture &picture) override
bool UploadBuffer () override
unsigned GetViewCount () const override
ID3D11View * GetView (unsigned viewIdx) override
void ReleasePicture () override
Public Member Functions inherited from CRenderBuffer
virtual ~CRenderBuffer ()=default
unsigned GetWidth () const
unsigned GetHeight () const
bool IsLoaded ()
virtual HRESULT GetResource (ID3D11Resource **ppResource, unsigned *index) const
virtual bool GetDataPlanes (uint8_t *(&planes)[3], int(&strides)[3])
Private Member Functions
bool UploadFromGPU ()
bool UploadFromBuffer () const
Private Attributes
unsigned m_viewCount = 0
CD3DTexture m_textures [YuvImage::MAX_PLANES]
Microsoft::WRL::ComPtr< ID3D11ShaderResourceView > m_planes [2]
Additional Inherited Members
Public Attributes inherited from CRenderBuffer
AVPixelFormat av_format
CVideoBuffer * videoBuffer = nullptr
unsigned int pictureFlags = 0
AVColorPrimaries m_originalPrimaries = AVCOL_PRI_BT709
AVColorPrimaries primaries = AVCOL_PRI_BT709
AVColorSpace color_space = AVCOL_SPC_BT709
AVColorTransferCharacteristic color_transfer = AVCOL_TRC_BT709
bool full_range = false
int bits = 8
uint8_t texBits = 8
AVPixelFormat pixelFormat = AV_PIX_FMT_NONE
bool hasDisplayMetadata = false
bool hasLightMetadata = false
AVMasteringDisplayMetadata displayMetadata = {}
AVContentLightMetadata lightMetadata = {}
std::string stereoMode
uint64_t frameIdx = 0
Protected Member Functions inherited from CRenderBuffer
CRenderBuffer (AVPixelFormat av_pix_format, unsigned width, unsigned height)
void QueueCopyFromGPU ()
Protected Attributes inherited from CRenderBuffer
unsigned int m_width
unsigned int m_height
unsigned int m_widthTex
unsigned int m_heightTex
Microsoft::WRL::ComPtr< ID3D11Texture2D > m_staging
D3D11_TEXTURE2D_DESC m_sDesc {}
bool m_bPending = false
bool m_bLoaded = false
Constructor & Destructor Documentation
CRenderBufferImpl()
CRendererShaders::CRenderBufferImpl::CRenderBufferImpl (AVPixelFormat av_pix_format, unsigned width, unsigned height) explicit
References CRenderBuffer::av_format, CRendererShaders::Create(), CRenderBuffer::m_height, m_textures, m_viewCount, CRenderBuffer::m_width, YuvImage::MAX_PLANES, and CRenderBuffer::texBits.
~CRenderBufferImpl()
CRendererShaders::CRenderBufferImpl::~CRenderBufferImpl ()
References ReleasePicture().
Member Function Documentation
AppendPicture()
void CRendererShaders::CRenderBufferImpl::AppendPicture (const VideoPicture & picture) override virtual
Reimplemented from CRenderBuffer.
References DXVA::CVideoBuffer::width.
GetView()
ID3D11View * CRendererShaders::CRenderBufferImpl::GetView (unsigned viewIdx) override virtual
Reimplemented from CRenderBuffer.
References FAILED, DX::DeviceResources::Get(), CRendererBase::GetDXGIFormat(), LOGERROR, and plane_formats.
GetViewCount()
unsigned CRendererShaders::CRenderBufferImpl::GetViewCount () const override virtual
Reimplemented from CRenderBuffer.
ReleasePicture()
void CRendererShaders::CRenderBufferImpl::ReleasePicture () override virtual
Reimplemented from CRenderBuffer.
Referenced by ~CRenderBufferImpl().
UploadBuffer()
bool CRendererShaders::CRenderBufferImpl::UploadBuffer () override virtual
Reimplemented from CRenderBuffer.
UploadFromBuffer()
bool CRendererShaders::CRenderBufferImpl::UploadFromBuffer () const private
UploadFromGPU()
bool CRendererShaders::CRenderBufferImpl::UploadFromGPU () private
References CPU_FEATURE_SSE4, FAILED, DX::DeviceResources::Get(), CServiceBroker::GetCPUInfo(), gpu_memcpy(), mappings, PLANE_UV, and PLANE_Y.
Member Data Documentation
m_planes
Microsoft::WRL::ComPtr<ID3D11ShaderResourceView> CRendererShaders::CRenderBufferImpl::m_planes[2] private
m_textures
CD3DTexture CRendererShaders::CRenderBufferImpl::m_textures[YuvImage::MAX_PLANES] private
Referenced by CRenderBufferImpl().
m_viewCount
unsigned CRendererShaders::CRenderBufferImpl::m_viewCount = 0 private
Referenced by CRenderBufferImpl().
The documentation for this class was generated from the following files:
RendererShaders.h
RendererShaders.cpp