Kodi Documentation: GUIContainerBuiltins.cpp File Reference
GUIContainerBuiltins.cpp File Reference
#include "GUIContainerBuiltins.h"
#include "GUIUserMessages.h"
#include "ServiceBroker.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "utils/StringUtils.h"
Functions
template<int Dir>
static int ChangeSortMethod (const std::vector< std::string > &params)
Change sort method.
template<int Dir>
static int ChangeViewMode (const std::vector< std::string > &params)
Change view mode.
static int Refresh (const std::vector< std::string > &params)
Refresh a media window.
static int SetSortMethod (const std::vector< std::string > &params)
Set sort method.
static int SetViewMode (const std::vector< std::string > &params)
Set view mode.
static int ToggleSortDirection (const std::vector< std::string > &params)
Toggle sort direction.
static int Update (const std::vector< std::string > &params)
Update a listing in a media window.
Function Documentation
ChangeSortMethod()
template<int Dir> static int ChangeSortMethod (const std::vector< std::string > & params) static
Change sort method.
Parameters
params (ignored)
Set the Dir template parameter to 1 to switch to next sort method or -1 to switch to previous sort method.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_CHANGE_SORT_METHOD, and CGUIWindowManager::SendMessage().
Referenced by CGUIContainerBuiltins::GetOperations().
ChangeViewMode()
template<int Dir> static int ChangeViewMode (const std::vector< std::string > & params) static
Change view mode.
Parameters
params (ignored)
Set the Dir template parameter to 1 to switch to next view mode or -1 to switch to previous view mode.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_CHANGE_VIEW_MODE, and CGUIWindowManager::SendMessage().
Referenced by CGUIContainerBuiltins::GetOperations().
Refresh()
static int Refresh (const std::vector< std::string > & params) static
Refresh a media window.
Parameters
params The parameters.
params[0] = The URL to refresh window at.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE, CGUIWindowManager::SendMessage(), and CGUIMessage::SetStringParam().
Referenced by CGUIContainerBuiltins::GetOperations().
SetSortMethod()
static int SetSortMethod (const std::vector< std::string > & params) static
Set sort method.
Parameters
params The parameters.
params[0] = ID of sort method.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_CHANGE_SORT_METHOD, and CGUIWindowManager::SendMessage().
Referenced by CGUIContainerBuiltins::GetOperations().
SetViewMode()
static int SetViewMode (const std::vector< std::string > & params) static
Set view mode.
Parameters
params The parameters.
params[0] = ID of view mode.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_CHANGE_VIEW_MODE, and CGUIWindowManager::SendMessage().
Referenced by CGUIContainerBuiltins::GetOperations().
ToggleSortDirection()
static int ToggleSortDirection (const std::vector< std::string > & params) static
Toggle sort direction.
Parameters
params (ignored)
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_CHANGE_SORT_DIRECTION, and CGUIWindowManager::SendMessage().
Referenced by CGUIContainerBuiltins::GetOperations().
Update()
static int Update (const std::vector< std::string > & params) static
Update a listing in a media window.
Parameters
params The parameters.
params[0] = The URL to update listing at. params[1] = "replace" to reset history (optional).
References KODI::UTILS::StringUtils::EqualsNoCase(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE, CGUIWindowManager::SendMessage(), CGUIMessage::SetParam2(), and CGUIMessage::SetStringParam().