Kodi Documentation: JSONRPC::CAddonsOperations Class Reference
JSONRPC::CAddonsOperations Class Reference
#include <AddonsOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetAddons (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetAddonDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetAddonEnabled (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ExecuteAddon (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Static Public Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
Static Private Member Functions
static void FillDetails (const std::shared_ptr< ADDON::IAddon > &addon, const CVariant &fields, CVariant &result, bool append)
Additional Inherited Members
Static Protected Member Functions inherited from JSONRPC::CJSONUtils
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Member Function Documentation
ExecuteAddon()
JSONRPC_STATUS CAddonsOperations::ExecuteAddon (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asString(), CVariant::begin_array(), CVariant::begin_map(), CVariant::empty(), CVariant::end_array(), CVariant::end_map(), CServiceBroker::GetAddonMgr(), CServiceBroker::GetAppMessenger(), JSONRPC::InvalidParams, CVariant::isArray(), CVariant::isObject(), CVariant::isString(), and TMSG_EXECUTE_BUILT_IN.
FillDetails()
void CAddonsOperations::FillDetails (const std::shared_ptr< ADDON::IAddon > & addon, const CVariant & fields, CVariant & result, bool append) static private
References CVariant::append(), CVariant::asString(), CFileUtils::Exists(), fields, CServiceBroker::GetAddonMgr(), CServiceBroker::GetTextureCache(), index(), ADDON::CAddonMgr::IsAddonDisabled(), ADDON::CAddonMgr::IsAddonInstalled(), CVariant::isMember(), Serialize(), and IMAGE_FILES::URLFromFile().
Referenced by GetAddonDetails(), and GetAddons().
GetAddonDetails()
JSONRPC_STATUS CAddonsOperations::GetAddonDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), FillDetails(), CServiceBroker::GetAddonMgr(), JSONRPC::InvalidParams, and JSONRPC::OK.
GetAddons()
JSONRPC_STATUS CAddonsOperations::GetAddons (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References addons, CVariant::asBoolean(), ADDON::CPluginSource::AUDIO, ADDON::content, end(), ADDON::CPluginSource::EXECUTABLE, FillDetails(), ADDON::CPluginSource::GAME, CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetAddons(), ADDON::CAddonMgr::GetDisabledAddons(), ADDON::CAddonMgr::GetInstallableAddons(), ADDON::CAddonMgr::GetInstalledAddons(), JSONRPC::CJSONUtils::HandleLimits(), ADDON::CPluginSource::IMAGE, index(), CVariant::isBoolean(), JSONRPC::OK, ADDON::CPluginSource::Translate(), ADDON::CAddonInfo::TranslateType(), ADDON::CPluginSource::UNKNOWN, and ADDON::CPluginSource::VIDEO.
SetAddonEnabled()
JSONRPC_STATUS CAddonsOperations::SetAddonEnabled (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asBoolean(), CVariant::asString(), ADDON::CAddonMgr::DisableAddon(), ADDON::CAddonMgr::EnableAddon(), CServiceBroker::GetAddonMgr(), JSONRPC::InvalidParams, ADDON::CAddonMgr::IsAddonDisabled(), and success.
The documentation for this class was generated from the following files:
AddonsOperations.h
AddonsOperations.cpp