Kodi Documentation: OVERLAY::COverlayTextureGL Class Reference
OVERLAY::COverlayTextureGL Class Reference
#include <OverlayRendererGL.h>
Public Member Functions
COverlayTextureGL (const CDVDOverlayImage &o, CRect &rSource)
Create the overlay for rendering.
COverlayTextureGL (const CDVDOverlaySpu &o)
~COverlayTextureGL () override
void Render (SRenderState &state) override
Public Member Functions inherited from OVERLAY::COverlay
COverlay ()
virtual ~COverlay ()
Public Attributes
GLuint m_texture = 0
float m_u
float m_v
bool m_pma
Public Attributes inherited from OVERLAY::COverlay
enum OVERLAY::COverlay::EType m_type
enum OVERLAY::COverlay::EAlign m_align
enum OVERLAY::COverlay::EPosition m_pos
float m_x {0}
float m_y {0}
float m_width {1.0f}
float m_height {1.0f}
float m_source_width {0}
float m_source_height {0}
Additional Inherited Members
Public Types inherited from OVERLAY::COverlay
enum EType { TYPE_NONE , TYPE_TEXTURE }
enum EAlign { ALIGN_SCREEN , ALIGN_SCREEN_AR , ALIGN_VIDEO , ALIGN_SUBTITLE }
enum EPosition { POSITION_ABSOLUTE , POSITION_ABSOLUTE_SCREEN , POSITION_RELATIVE }
Static Public Member Functions inherited from OVERLAY::COverlay
static std::shared_ptr< COverlay > Create (const CDVDOverlayImage &o, CRect &rSource)
static std::shared_ptr< COverlay > Create (const CDVDOverlaySpu &o)
static std::shared_ptr< COverlay > Create (ASS_Image *images, float width, float height)
Protected Member Functions inherited from OVERLAY::COverlay
bool IsSquareResolution (float resRatio)
Given the resolution ratio determines if it is a 4/3 resolution.
Constructor & Destructor Documentation
COverlayTextureGL() [1/2]
COverlayTextureGL::COverlayTextureGL (const CDVDOverlayImage & o, CRect & rSource) explicit
Create the overlay for rendering.
Parameters
o The overlay image
rSource The video source rect size
References OVERLAY::COverlay::ALIGN_SCREEN_AR, OVERLAY::COverlay::ALIGN_VIDEO, OVERLAY::convert_rgba(), GL_CLAMP, CDVDOverlayImage::height, CRectGen< T >::Height(), OVERLAY::COverlay::IsSquareResolution(), CDVDOverlayImage::linesize, LoadTexture(), OVERLAY::COverlay::m_align, OVERLAY::COverlay::m_height, m_pma, OVERLAY::COverlay::m_pos, OVERLAY::COverlay::m_source_height, OVERLAY::COverlay::m_source_width, m_texture, m_u, m_v, OVERLAY::COverlay::m_width, OVERLAY::COverlay::m_x, OVERLAY::COverlay::m_y, CDVDOverlayImage::palette, CDVDOverlayImage::pixels, OVERLAY::COverlay::POSITION_ABSOLUTE, OVERLAY::COverlay::POSITION_RELATIVE, CDVDOverlayImage::source_height, CDVDOverlayImage::source_width, USE_PREMULTIPLIED_ALPHA, CDVDOverlayImage::width, CRectGen< T >::Width(), CDVDOverlayImage::x, and CDVDOverlayImage::y.
COverlayTextureGL() [2/2]
COverlayTextureGL::COverlayTextureGL (const CDVDOverlaySpu & o) explicit
References OVERLAY::COverlay::ALIGN_VIDEO, OVERLAY::convert_rgba(), GL_CLAMP, CDVDOverlaySpu::height, LoadTexture(), OVERLAY::COverlay::m_align, OVERLAY::COverlay::m_height, m_pma, OVERLAY::COverlay::m_pos, m_texture, m_u, m_v, OVERLAY::COverlay::m_width, OVERLAY::COverlay::m_x, OVERLAY::COverlay::m_y, OVERLAY::COverlay::POSITION_ABSOLUTE, USE_PREMULTIPLIED_ALPHA, CDVDOverlaySpu::width, CDVDOverlaySpu::x, and CDVDOverlaySpu::y.
~COverlayTextureGL()
COverlayTextureGL::~COverlayTextureGL () override
References m_texture.
Member Function Documentation
Render()
void COverlayTextureGL::Render (SRenderState & state) override virtual
Implements OVERLAY::COverlay.
References CRenderSystemGL::DisableShader(), CRenderSystemGL::EnableShader(), CRenderSystemGL::GetGLSLVersion(), CServiceBroker::GetRenderSystem(), OVERLAY::SRenderState::height, left, m_pma, OVERLAY::COverlay::m_pos, m_texture, m_u, m_v, OVERLAY::COverlay::POSITION_RELATIVE, right, CRectGen< T >::SetRect(), CRenderSystemGL::ShaderGetCoord0(), CRenderSystemGL::ShaderGetDepth(), CRenderSystemGL::ShaderGetPos(), CRenderSystemGL::ShaderGetUniCol(), SM_TEXTURE, SM_TEXTURE_LIM, OVERLAY::SRenderState::width, OVERLAY::SRenderState::x, CRectGen< T >::x1, CRectGen< T >::x2, OVERLAY::SRenderState::y, CRectGen< T >::y1, and CRectGen< T >::y2.
Member Data Documentation
m_pma
bool OVERLAY::COverlayTextureGL::m_pma
Referenced by COverlayTextureGL(), COverlayTextureGL(), and Render().
m_texture
GLuint OVERLAY::COverlayTextureGL::m_texture = 0
Referenced by COverlayTextureGL(), COverlayTextureGL(), Render(), and ~COverlayTextureGL().
m_u
float OVERLAY::COverlayTextureGL::m_u
Referenced by COverlayTextureGL(), COverlayTextureGL(), and Render().
m_v
float OVERLAY::COverlayTextureGL::m_v
Referenced by COverlayTextureGL(), COverlayTextureGL(), and Render().
The documentation for this class was generated from the following files:
OverlayRendererGL.h
OverlayRendererGL.cpp