Kodi Documentation: CLog Class Reference
CLog Class Reference
#include <log.h>
Public Member Functions
CLog ()
~CLog ()
void OnSettingsLoaded () override
Settings have been loaded.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void Initialize (const std::string &path)
void UnregisterFromSettings ()
void Deinitialize ()
void SetLogLevel (int level)
int GetLogLevel ()
bool IsLogLevelLogged (int loglevel)
bool CanLogComponent (uint32_t component) const
Logger GetLogger (const std::string &loggerName)
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsUnloaded ()
Setting values have been unloaded.
virtual void OnSettingsCleared ()
Settings have been cleared.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Static Public Member Functions
static void SettingOptionsLoggingComponentsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
template<typename... Args>
static void Log (int level, fmt::format_string< Args... > format, Args &&... args)
template<typename... Args>
static void Log (int level, uint32_t component, fmt::format_string< Args... > format, Args &&... args)
template<typename... Args>
static void Log (spdlog::level::level_enum level, fmt::format_string< Args... > format, Args &&... args)
template<typename... Args>
static void Log (spdlog::level::level_enum level, uint32_t component, fmt::format_string< Args... > format, Args &&... args)
Private Member Functions
void FormatAndLogInternal (spdlog::level::level_enum level, fmt::string_view format, fmt::format_args args)
Logger CreateLogger (const std::string &loggerName)
void SetComponentLogLevel (const std::vector< CVariant > &components)
void FormatLineBreaks (std::string &message)
Static Private Member Functions
static CLog & GetInstance ()
static spdlog::level::level_enum MapLogLevel (int level)
Private Attributes
std::unique_ptr< IPlatformLog > m_platform
std::shared_ptr< spdlog::sinks::dist_sink< std::mutex > > m_sinks
Logger m_defaultLogger
std::shared_ptr< spdlog::sinks::sink > m_fileSink
int m_logLevel
bool m_componentLogEnabled = false
uint32_t m_componentLogLevels = 0
Constructor & Destructor Documentation
CLog()
CLog::CLog ()
References m_defaultLogger, m_logLevel, m_platform, m_sinks, and SetLogLevel().
~CLog()
CLog::~CLog ()
Member Function Documentation
CanLogComponent()
bool CLog::CanLogComponent (uint32_t component) const
References m_componentLogEnabled, and m_componentLogLevels.
Referenced by CWebServer::ContentReaderCallback(), CWebServer::ContentReaderFreeCallback(), CVideoBufferDMA::Export(), CDVDAudioCodecAndroidMediaCodec::GetData(), CAESinkAUDIOTRACK::GetDelay(), CSMB::Init(), Log(), Log(), and CMediaCodecVideoBuffer::ReleaseOutputBuffer().
CreateLogger()
Logger CLog::CreateLogger (const std::string & loggerName) private
References m_sinks.
Referenced by GetLogger().
Deinitialize()
void CLog::Deinitialize ()
References m_fileSink, and m_sinks.
Referenced by CAppEnvironment::TearDown(), TEST_F(), TEST_F(), TEST_F(), Testlog::~Testlog(), and TestRegExpLog::~TestRegExpLog().
FormatAndLogInternal()
void CLog::FormatAndLogInternal (spdlog::level::level_enum level, fmt::string_view format, fmt::format_args args) inline private
References FormatLineBreaks(), and m_defaultLogger.
Referenced by Log(), and SetLogLevel().
FormatLineBreaks()
void CLog::FormatLineBreaks (std::string & message) private
Referenced by FormatAndLogInternal().
GetInstance()
CLog & CLog::GetInstance () static private
References CServiceBroker::GetLogging().
Referenced by Log(), Log(), and Log().
GetLogger()
Logger CLog::GetLogger (const std::string & loggerName)
References CreateLogger().
Referenced by CHTTPJsonRpcHandler::appendPostData(), CHTTPPythonHandler::appendPostData(), UPNP::BuildObject(), CSetting::CSetting(), CSettingAction::CSettingAction(), CSettingBool::CSettingBool(), CSettingCategory::CSettingCategory(), CSettingDependency::CSettingDependency(), CSettingDependencyCondition::CSettingDependencyCondition(), CSettingGroup::CSettingGroup(), CSettingInt::CSettingInt(), CSettingList::CSettingList(), CSettingNumber::CSettingNumber(), CSettingSection::CSettingSection(), CSettingString::CSettingString(), CSettingUpdate::CSettingUpdate(), CHTTPPythonWsgiInvoker::executeScript(), CWebServer::GetLogger(), GetMhdLogger(), UPNP::GetResource(), ISettingControl::ISettingControl(), CWebServer::Start(), and UPnPLogger().
GetLogLevel()
int CLog::GetLogLevel () inline
References m_logLevel.
Initialize()
void CLog::Initialize (const std::string & path)
References URIUtils::AddFileToFolder(), XFILE::CFile::Delete(), CCompileInfo::GetAppName(), CServiceBroker::GetSettingsComponent(), m_fileSink, m_platform, m_sinks, XFILE::CFile::Rename(), CSettings::SETTING_DEBUG_EXTRALOGGING, CSettings::SETTING_DEBUG_SETEXTRALOGLEVEL, SettingOptionsLoggingComponentsFiller(), and XFILE::CFile::Write().
Referenced by CApplication::Create(), TEST_F(), TEST_F(), and TEST_F().
IsLogLevelLogged()
bool CLog::IsLogLevelLogged (int loglevel)
References LOG_LEVEL_DEBUG, LOG_LEVEL_NONE, LOGINFO, LOGMASK, and m_logLevel.
Log() [1/4]
template<typename... Args> static void CLog::Log (int level, fmt::format_string< Args... > format, Args &&... args) inline static
References Log(), and MapLogLevel().
Referenced by jni::CJNIXBMCNsdManagerDiscoveryListener::_onDiscoveryStarted(), jni::CJNIXBMCNsdManagerDiscoveryListener::_onDiscoveryStopped(), jni::CJNIXBMCNsdManagerRegistrationListener::_onRegistrationFailed(), jni::CJNIXBMCNsdManagerRegistrationListener::_onServiceRegistered(), jni::CJNIXBMCNsdManagerRegistrationListener::_onServiceUnregistered(), jni::CJNIXBMCNsdManagerRegistrationListener::_onUnregistrationFailed(), _VerifyGLState(), ADDON::Interface_GUIDialogProgress::abort(), XBMCAddon::AddonClass::Acquire(), PERIPHERALS::CEventScanner::Activate(), anonymous_namespace{GUIBuiltins.cpp}::ActivateAndFocus(), CApplicationPowerHandling::ActivateScreenSaver(), anonymous_namespace{GUIBuiltins.cpp}::ActivateWindow(), CPartyModeManager::Add(), CGUIWindowManager::Add(), CPtsTracker::Add(), WSDiscovery::CClientNotificationSink::Add(), ADDON::Interface_GUIControlSpin::add_int_label(), ADDON::Interface_GUIControlFadeLabel::add_label(), ADDON::Interface_GUIWindow::add_list_item(), ADDON::Interface_GUIControlSpin::add_string_label(), CVideoDatabase::AddActor(), CMusicDatabase::AddAlbum(), CMusicDatabase::AddAlbumSources(), CMusicDatabase::AddArtist(), CMusicDatabase::AddArtist(), CMusicDatabase::AddArtistVideoLinks(), XBMCAddon::xbmcgui::ListItem::addAvailableArtwork(), CGUIDialogVideoBookmarks::AddBookmark(), CVideoDatabase::AddBookMarkForEpisode(), CVideoDatabase::AddBookMarkToFile(), CTextureDatabase::AddCachedTexture(), WSDiscovery::CWSDiscoveryListenerUDP::AddCommand(), CGUIListGroup::AddControl(), CDVDAudioCodecAndroidMediaCodec::AddData(), CDVDAudioCodecFFmpeg::AddData(), CDVDVideoCodecAndroidMediaCodec::AddData(), CDVDVideoCodecDRMPRIME::AddData(), CDVDVideoCodecFFmpeg::AddData(), ActiveAE::CActiveAEStream::AddData(), CEdl::AddEdit(), CDVDSubtitlesLibass::AddEvent(), CVideoDatabase::AddFile(), KODI::RETRO::CRPRenderManager::AddFrame(), CMusicDatabase::AddGenre(), ADDON::CAddonDatabase::AddInstalledAddon(), ADDON::CAddonSettings::AddInstanceSettings(), CCoreAudioDevice::AddIOProc(), JSONRPC::CJSONServiceDescription::AddMethod(), JSONRPC::CJSONServiceDescription::addMethod(), CGUIInfoManager::AddMultiInfo(), CVideoDatabase::AddNewEpisode(), CVideoDatabase::AddNewMovie(), CVideoDatabase::AddNewMusicVideo(), JSONRPC::CJSONServiceDescription::AddNotification(), ADDON::Interface_Base::addon_log_msg(), ADDON::CAddonMgr::AddonsFromRepoXML(), CUrlOptions::AddOptions(), EVENTCLIENT::CEventClient::AddPacket(), CAudioSinkAE::AddPackets(), CAESinkALSA::AddPackets(), CAESinkAUDIOTRACK::AddPackets(), CAESinkDARWINOSX::AddPackets(), CAESinkOSS::AddPackets(), CAESinkPULSE::AddPackets(), CMusicDatabase::AddPath(), CVideoDatabase::AddPath(), VAAPI::CFFmpegPostproc::AddPicture(), KODI::GAME::CControllerGrid::AddPorts(), CVideoDatabase::AddRatings(), JSONRPC::CJSONServiceDescription::addReferenceTypeDefinition(), CMusicDatabase::AddRole(), KODI::RETRO::CSavestateDatabase::AddSavestate(), CEdl::AddSceneMarker(), XBMCAddon::xbmcgui::ListItem::addSeason(), CZeroconfAvahi::addService(), CVideoDatabase::AddSet(), PERIPHERALS::CPeripheral::AddSetting(), CMediaSourceSettings::AddShare(), CMusicDatabase::AddSong(), CMusicDatabase::AddSongContributor(), CMusicDatabase::AddSongGenres(), CMusicDatabase::AddSource(), CDVDDemuxFFmpeg::AddStream(), CDVDDemuxFFmpeg::AddStream(), KODI::RETRO::CRetroPlayerAudio::AddStreamData(), XBMCAddon::xbmcgui::ListItem::addStreamInfo(), CVideoDatabase::AddToTable(), JSONRPC::CJSONServiceDescription::AddType(), CVideoDatabase::AddUniqueIDs(), ADDON::CAddonDatabase::AddUpdateRuleForAddon(), CPartyModeManager::AddUserSongs(), CPartyModeManager::AddUserSongs(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), KODI::VIDEO::CVideoInfoScanner::AddVideoExtras(), CRenderManager::AddVideoPicture(), CVideoDatabase::AddVideoVersionType(), CWinSystemWin10::AdjustWindow(), ADDON::Interface_AudioEngine::aestream_add_data(), ADDON::Interface_AudioEngine::aestream_drain(), ADDON::Interface_AudioEngine::aestream_flush(), ADDON::Interface_AudioEngine::aestream_get_amplification(), ADDON::Interface_AudioEngine::aestream_get_cache_time(), ADDON::Interface_AudioEngine::aestream_get_cache_total(), ADDON::Interface_AudioEngine::aestream_get_channel_count(), ADDON::Interface_AudioEngine::aestream_get_data_format(), ADDON::Interface_AudioEngine::aestream_get_delay(), ADDON::Interface_AudioEngine::aestream_get_frame_size(), ADDON::Interface_AudioEngine::aestream_get_resample_ratio(), ADDON::Interface_AudioEngine::aestream_get_sample_rate(), ADDON::Interface_AudioEngine::aestream_get_space(), ADDON::Interface_AudioEngine::aestream_get_volume(), ADDON::Interface_AudioEngine::aestream_is_buffering(), ADDON::Interface_AudioEngine::aestream_is_drained(), ADDON::Interface_AudioEngine::aestream_is_draining(), ADDON::Interface_AudioEngine::aestream_pause(), ADDON::Interface_AudioEngine::aestream_resume(), ADDON::Interface_AudioEngine::aestream_set_amplification(), ADDON::Interface_AudioEngine::aestream_set_resample_ratio(), ADDON::Interface_AudioEngine::aestream_set_volume(), CVideoBufferDMA::Alloc(), CTextureBase::Allocate(), CGUIWindow::AllocResources(), CXBMCApp::android_printf(), CLibInputHandler::Announce(), CGUIWindowHome::Announce(), CWinSystemTVOS::AnnounceOnLostDevice(), CWinSystemTVOS::AnnounceOnResetDevice(), Shaders::CShader::AppendSource(), CDVDSubtitlesLibass::AppendTextToEvent(), XBMCDelegate::application:openFile:, ActiveAE::CActiveAE::ApplySettingsToFormat(), CStereoscopicsManager::ApplyStereoMode(), CDVDSubtitlesLibass::ApplyStyle(), CAirTunesServer::AudioOutputFunctions::audio_destroy(), ADDON::Interface_AudioEngine::audioengine_free_stream(), ADDON::Interface_AudioEngine::audioengine_make_stream(), KODI::CDRIP::CEncoderFFmpeg::avio_write_callback(), Shaders::GL::BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader(), Shaders::GLES::BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader(), CRenderCaptureDX::BeginRender(), CRenderCaptureGL::BeginRender(), CDatabase::BeginTransaction(), KODI::WINDOWING::WAYLAND::CRegistry::Bind(), SOCKETS::CPosixUDPSocket::Bind(), CEGLContextUtils::BindContext(), CBitstreamConverter::BitstreamConvertInitAVC(), CBitstreamConverter::BitstreamConvertInitHEVC(), CUDisks2Provider::BlockAdded(), CUDisks2Provider::BlockPropertiesChanged(), CUDisks2Provider::BlockRemoved(), CBlurayCallback::bluray_logger(), KODI::PIPEWIRE::CPipewireProxy::Bound(), CZeroconfBrowserAvahi::browseCallback(), CZeroconfBrowserDarwin::BrowserCallback(), CZeroconfBrowserMDNS::BrowserCallback(), CDVDAudioCodecFFmpeg::BuildChannelMap(), UPNP::BuildObject(), WSDiscovery::CWSDiscoveryListenerUDP::buildSoapMessage(), CAESinkFactoryWin::BuildWaveFormatExtensible(), CTextureCache::CacheImage(), CTextureCacheJob::CacheTexture(), PERIPHERALS::CAddonButtonMapping::CAddonButtonMapping(), ADDON::CAddonStatusHandler::CAddonStatusHandler(), CAddonVideoCodec::CAddonVideoCodec(), CAESinkDARWINOSX::CAESinkDARWINOSX(), CVideoPlayerVideo::CalcDropRequirement(), CVideoPlayerVideo::CalcFrameRate(), CRenderSystemGL::CalculateMaxTexturesize(), CRenderSystemGLES::CalculateMaxTexturesize(), XBMCController::CallExit, ADDON::Interface_Filesystem::can_open_directory(), CGUIMediaWindow::CancelUpdateItems(), CAndroidUtils::CAndroidUtils(), KODI::WINDOWING::WAYLAND::CConnection::CConnection(), CDBusMessage::CDBusMessage(), KODI::JOYSTICK::CDeadzoneFilter::CDeadzoneFilter(), cdio_log_handler(), CDVDRadioRDSData::CDVDRadioRDSData(), CDVDSubtitlesLibass::CDVDSubtitlesLibass(), CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), ADDON::Interface_General::change_keyboard_layout(), CDVDSubtitlesLibass::ChangeEventStopTime(), DXVA::CDecoder::Check(), VAAPI::CDecoder::Check(), VDPAU::CDecoder::Check(), JSONRPC::JSONSchemaTypeDefinition::Check(), ADDON::CAddonDll::CheckAPIVersion(), CAirPlayServer::CTCPClient::checkAuthorization(), CVideoPlayer::CheckAutoSceneSkip(), CDVDInputStreamNavigator::CheckButtons(), CheckCompatibility(), CColorManager::CheckConfiguration(), KODI::WINDOWING::GBM::CDRMConnector::CheckConnector(), CVideoPlayer::CheckContinuity(), ADDON::CAddonInstaller::CheckDependencies(), CFileUtils::CheckFileAccessAllowed(), CRssReader::CheckForUpdates(), XCURL::DllLibCurlGlobal::CheckIdle(), CNfsConnection::CheckIfIdle(), CSMB::CheckIfIdle(), CRenderSystemDX::CheckInterlacedStereoView(), CVideoPlayer::CheckPlayerInit(), CAAudioUnitSink::checkSessionProperties(), CMusicDatabase::CheckSources(), VDPAU::CMixer::CheckStatus(), VDPAU::COutput::CheckStatus(), VDPAU::CDecoder::CheckStatus(), VAAPI::CVAAPIContext::CheckSuccess(), VAAPI::CDecoder::CheckSuccess(), VAAPI::CVppPostproc::CheckSuccess(), VAAPI::CFFmpegPostproc::CheckSuccess(), CDBusMessage::CheckTypeAndGetValue(), CResolutionUtils::ChooseBestResolution(), CEGLContextUtils::ChooseConfig(), CInputStreamPVRBase::CInputStreamPVRBase(), CVideoDatabase::CleanDatabase(), CleanLibrary(), CUtil::CleanString(), CApplication::Cleanup(), CGUITextureManager::Cleanup(), CVideoSyncAndroid::Cleanup(), CVideoSyncGbm::Cleanup(), CVideoSyncIos::Cleanup(), CVideoSyncOsx::Cleanup(), CVideoSyncTVos::Cleanup(), CVideoSyncD3D::Cleanup(), KODI::WINDOWING::X11::CVideoSyncGLX::Cleanup(), CMusicDatabase::Cleanup(), CMusicDatabase::CleanupAlbums(), CMusicDatabase::CleanupArtists(), CMusicDatabase::CleanupGenres(), CMusicDatabase::CleanupInfoSettings(), CMusicDatabase::CleanupPaths(), CMusicDatabase::CleanupRoles(), CMusicDatabase::CleanupSongs(), CMusicDatabase::CleanupSongsByIds(), CGUIInfoManager::Clear(), ADDON::Interface_GUIDialogFileBrowser::clear_file_list(), ADDON::Interface_GUIWindow::clear_item_list(), ADDON::Interface_GUIWindow::clear_properties(), ADDON::Interface_GUIWindow::clear_property(), CVideoDatabase::ClearBookMarkOfFile(), CVideoDatabase::ClearBookMarksOfFile(), CTextureDatabase::ClearCachedTexture(), ActiveAE::CActiveAE::ClearDiscardedBuffers(), XBMCAddon::RetardedAsyncCallbackHandler::clearPendingCalls(), ClearPhotoAssetCache(), VAAPI::CVideoSurfaces::ClearReference(), VDPAU::CVideoSurfaces::ClearReference(), VAAPI::CVideoSurfaces::ClearRender(), VDPAU::CVideoSurfaces::ClearRender(), CUtil::ClearSubtitles(), CTextureDatabase::ClearTextureForPath(), CViewDatabase::ClearViewStates(), CLibInputHandler::CLibInputHandler(), CLibInputSettings::CLibInputSettings(), CZeroconfBrowserAvahi::clientCallback(), CZeroconfAvahi::clientCallback(), CLogindUPowerSyscall::CLogindUPowerSyscall(), DXVA::CContext::Close(), VAAPI::CVAAPIContext::Close(), VAAPI::CDecoder::Close(), VDPAU::CVDPAUContext::Close(), VDPAU::CDecoder::Close(), XFILE::CFile::Close(), CDVDInputStreamNavigator::Close(), XFILE::CSimpleFileCache::Close(), XFILE::CNFSFile::Close(), XFILE::CSMBFile::Close(), CCoreAudioStream::Close(), ADDON::Interface_GUIWindow::close(), CWebSocketV13::Close(), CWebSocketV8::Close(), ADDON::Interface_Filesystem::close_file(), CTextureBundleXBT::CloseBundle(), KODI::RETRO::CRetroPlayer::CloseFile(), CVideoPlayer::CloseFile(), CApplication::CloseNetworkShares(), CInputStreamPVRChannel::ClosePVRStream(), CInputStreamPVRRecording::ClosePVRStream(), KODI::RETRO::CRetroPlayerAudio::CloseStream(), KODI::RETRO::CRetroPlayerVideo::CloseStream(), CVideoPlayerAudio::CloseStream(), CVideoPlayerAudioID3::CloseStream(), CDVDRadioRDSData::CloseStream(), CDVDTeletextData::CloseStream(), CVideoPlayerVideo::CloseStream(), CVideoPlayer::CloseStream(), CMediaCodecDecoderFilterManager::CMediaCodecDecoderFilterManager(), DRM::CMediaDrmCryptoSession::CMediaDrmCryptoSession(), CDatabase::CommitDeleteQueries(), CDatabase::CommitInsertQueries(), CDatabase::CommitTransaction(), PythonBindings::PythonCompare< T >::compare(), Shaders::CGLSLVertexShader::Compile(), Shaders::CGLSLPixelShader::Compile(), Shaders::CGLSLShaderProgram::CompileAndLink(), KODI::RETRO::CWinRenderBufferPool::CompileOutputShaders(), CAirPlayServer::CTCPClient::ComposeReverseEvent(), CDatabase::Compress(), CDVDSubtitlesLibass::Configure(), CRenderManager::Configure(), ActiveAE::CActiveAE::Configure(), KODI::RETRO::CRPBaseRenderer::Configure(), KODI::RETRO::CRPRenderManager::Configure(), CRendererMediaCodecSurface::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CRenderManager::Configure(), dbiplus::MysqlDatabase::configure_connection(), CApplication::ConfigureAndEnableAddons(), CDVDSubtitlesLibass::ConfigureAssOverride(), CDVDAudioCodecAndroidMediaCodec::ConfigureMediaCodec(), CDVDVideoCodecAndroidMediaCodec::ConfigureMediaCodec(), CDVDVideoCodecAndroidMediaCodec::ConfigureOutputFormat(), CDVDAudioCodecAndroidMediaCodec::ConfigureOutputFormat(), VAAPI::CDecoder::ConfigVAAPI(), VDPAU::CDecoder::ConfigVDPAU(), dbiplus::MysqlDatabase::connect(), dbiplus::SqliteDatabase::connect(), CNfsConnection::Connect(), CDatabase::Connect(), KODI::PIPEWIRE::CPipewireStream::Connect(), XFILE::CCurlFile::CReadState::Connect(), KODI::GAME::CGameClientInput::ConnectController(), CCharsetConverter::CInnerConverter::convert(), CBitstreamConverter::Convert(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::ConvertAndSendKey(), CTextureBundleXBT::ConvertFrameToTexture(), CCharsetDetection::ConvertHtmlToUtf8(), CPODocument::ConvertLineEnds(), CWIN32Util::ConvertPathToWin32Form(), CCharsetDetection::ConvertPlainTextToUtf8(), PERIPHERALS::CPeripheralBusAndroid::ConvertToPeripheralScanResult(), Shaders::GLES::ConvolutionFilterShader::ConvolutionFilterShader(), Shaders::GL::ConvolutionFilterShader::ConvolutionFilterShader(), XFILE::CFile::Copy(), ADDON::Interface_Filesystem::copy_file(), OVERLAY::COverlayQuadsDX::COverlayQuadsDX(), KODI::PIPEWIRE::CPipewireContext::CPipewireContext(), KODI::PIPEWIRE::CPipewireCore::CPipewireCore(), KODI::PIPEWIRE::CPipewireProxy::CPipewireProxy(), KODI::PIPEWIRE::CPipewireRegistry::CPipewireRegistry(), KODI::PIPEWIRE::CPipewireStream::CPipewireStream(), KODI::PIPEWIRE::CPipewireThreadLoop::CPipewireThreadLoop(), CPlayerCoreConfig::CPlayerCoreConfig(), PVR::CPVRRecording::CPVRRecording(), CApplication::Create(), KODI::PIPEWIRE::CPipewire::Create(), CUdpClient::Create(), CThread::Create(), CAudioDecoder::Create(), XFILE::CDirectory::Create(), XFILE::CDirectoryFactory::Create(), XFILE::CDAVDirectory::Create(), XFILE::CNFSDirectory::Create(), XFILE::CSMBDirectory::Create(), XFILE::CFileDirectoryFactory::Create(), CAudioSinkAE::Create(), CAnimation::Create(), ADDON::CAddonDll::Create(), ADDON::Interface_GUIListItem::create(), ADDON::Interface_GUIWindow::create(), ADDON::Interface_Filesystem::create_directory(), PERIPHERALS::CPeripheralAddon::CreateAddon(), KODI::CDRIP::CCDDARipper::CreateAlbumDir(), ADDON::CAddonDatabase::CreateAnalytics(), CMusicDatabase::CreateAnalytics(), CTextureDatabase::CreateAnalytics(), CVideoDatabase::CreateAnalytics(), CViewDatabase::CreateAnalytics(), ActiveAE::CActiveAEFilter::CreateAtempoFilter(), CAESinkAUDIOTRACK::CreateAudioTrack(), CDumbBufferObject::CreateBufferObject(), CDMAHeapBufferObject::CreateBufferObject(), CUDMABufferObject::CreateBufferObject(), CZeroconfAvahi::createClient(), VAAPI::CVAAPIContext::CreateContext(), VDPAU::CVDPAUContext::CreateContext(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::CreateContext(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::CreateContext(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::CreateContext(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::CreateContext(), CEGLContextUtils::CreateContext(), CDatabase::CreateDatabase(), CDVDFactoryDemuxer::CreateDemuxer(), KODI::WINDOWING::GBM::CGBMUtils::CreateDevice(), CUtil::CreateDirectoryEx(), CD3DEffect::CreateEffect(), ActiveAE::CActiveAEFilter::CreateFilterGraph(), KODI::RETRO::CSavestateDatabase::CreateFolderIfNotExists(), KODI::RETRO::CRPRenderManager::CreateFromCache(), CApplication::CreateGUI(), KODI::WINDOWING::X11::CWinSystemX11::CreateIconPixmap(), CEGLImage::CreateImage(), KODI::WINDOWING::COSScreenSaverManager::CreateInhibitor(), ADDON::IAddonInstanceHandler::CreateInstance(), KODI::RETRO::CRPProcessInfo::CreateInstance(), XFILE::CFileFactory::CreateLoader(), CMusicDatabase::CreateNativeDBFunctions(), CWinSystemAndroid::CreateNewWindow(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), CWinSystemIOS::CreateNewWindow(), CWinSystemTVOS::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::CreateNewWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::CreateNewWindow(), CLinuxRendererGL::CreateNV12Texture(), CCocoaPowerSyscall::CreateOSPowerCallBacks(), CGLContextEGL::CreatePB(), PERIPHERALS::CPeripherals::CreatePeripheral(), KODI::RETRO::CRetroPlayer::CreatePlayback(), KODI::RETRO::CRPProcessInfo::CreateRenderer(), KODI::RETRO::CWinRenderBuffer::CreateScalingContext(), CZeroconfBrowserAvahi::createServiceBrowser(), CDVDSubtitlesLibass::CreateStyle(), KODI::WINDOWING::GBM::CGBMUtils::CGBMDevice::CreateSurface(), DXVA::CContext::CreateSurfaces(), ADDON::CAddonDatabase::CreateTables(), CMusicDatabase::CreateTables(), PVR::CPVREpgDatabase::CreateTables(), CTextureDatabase::CreateTables(), CVideoDatabase::CreateTables(), CViewDatabase::CreateTables(), CreateTCPServerSocket(), KODI::RETRO::CWinRenderBuffer::CreateTexture(), CPicture::CreateThumbnailFromSurface(), CFFmpegImage::CreateThumbnailFromSurface(), CDVDSubtitlesLibass::CreateTrack(), CDVDSubtitlesLibass::CreateTrack(), CSettingsComponent::CreateUserDirs(), VDPAU::CMixer::CreateVdpauMixer(), jni::CJNIXBMCVideoView::createVideoView(), CMusicDatabase::CreateViews(), CVideoDatabase::CreateViews(), CLinuxRendererGL::CreateYUV422PackedTexture(), CLinuxRendererGL::CreateYV12Texture(), KODI::RETRO::CRenderBufferDMA::CRenderBufferDMA(), CRendererMediaCodec::CRendererMediaCodec(), CRendererMediaCodecSurface::CRendererMediaCodecSurface(), CRendererVTB::CRendererVTB(), ADDON::CRepository::CRepository(), KODI::RETRO::CRetroPlayerAudio::CRetroPlayerAudio(), KODI::RETRO::CRetroPlayerAutoSave::CRetroPlayerAutoSave(), KODI::RETRO::CRetroPlayerInput::CRetroPlayerInput(), KODI::RETRO::CRetroPlayerVideo::CRetroPlayerVideo(), KODI::ADDONS::CScreenSaver::CScreenSaver(), KODI::WINDOWING::WAYLAND::CSeatSelection::CSeatSelection(), KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell::CShellSurfaceWebOSShell(), KODI::RETRO::CDeltaPairMemoryStream::CullPastFrames(), CUPowerSyscall::CUPowerSyscall(), ADDON::Interface_Filesystem::curl_add_option(), ADDON::Interface_Filesystem::curl_create(), ADDON::Interface_Filesystem::curl_open(), CCharsetConverter::CInnerConverter::customConvert(), ADDON::CVFSEntry::CVFSEntry(), CVideoPlayerAudioID3::CVideoPlayerAudioID3(), KODI::ADDONS::CVisualization::CVisualization(), ADDON::CWebinterface::CWebinterface(), CWebSocketFrame::CWebSocketFrame(), CWinEventsAndroid::CWinEventsAndroid(), CWinEventsTVOS::CWinEventsTVOS(), CX11DPMSSupport::CX11DPMSSupport(), CXHandle::CXHandle(), CZeroconfAvahi::CZeroconfAvahi(), CZeroconfBrowserAvahi::CZeroconfBrowserAvahi(), dbiplus::DbErrors::DbErrors(), PERIPHERALS::CEventScanner::Deactivate(), deactivateAudioSession(), debug_callback(), DebugLog(), DXVA::CDecoder::Decode(), VAAPI::CDecoder::Decode(), VDPAU::CDecoder::Decode(), CDVDOverlayCodecCCText::Decode(), CDVDOverlayCodecFFmpeg::Decode(), CDVDOverlayCodecText::Decode(), CDVDOverlayCodecTX3G::Decode(), CFFmpegImage::Decode(), CTeletextDecoder::Decode_ADIP(), CTeletextDecoder::Decode_BTT(), CDVDSubtitlesLibass::DecodeDemuxPkt(), CDVDRadioRDSData::DecodeDI(), CDVDRadioRDSData::DecodeEPPTransmitterInfo(), CFFmpegImage::DecodeFrame(), CDVDSubtitlesLibass::DecodeHeader(), CDVDRadioRDSData::DecodeMS(), CDVDRadioRDSData::DecodeODA(), CDVDRadioRDSData::DecodePI(), CDVDRadioRDSData::DecodeRT(), CDVDRadioRDSData::DecodeRTC(), CDVDRadioRDSData::DecodeRTPlus(), CDVDRadioRDSData::DecodeSlowLabelingCodes(), CWebVTTISOHandler::DecodeStream(), XFILE::CZipFile::DecompressGzip(), DRM::CMediaDrmCryptoSession::Decrypt(), KODI::RETRO::CRPRenderManager::Deinitialize(), CAESinkAUDIOTRACK::Deinitialize(), CGUIVisualisationControl::DeInitVisualization(), XFILE::CFile::Delete(), XFILE::CDAVFile::Delete(), XFILE::CNFSFile::Delete(), XFILE::CSMBFile::Delete(), ADDON::Interface_GUIDialogExtendedProgress::delete_dialog(), ADDON::Interface_GUIDialogProgress::delete_dialog(), ADDON::Interface_Filesystem::delete_file(), CVideoDatabase::DeleteBookMarkForEpisode(), CLinuxRendererGL::DeleteCLUT(), CVideoDatabase::DeleteDetailsForTvShow(), CVideoDatabase::DeleteEpisode(), CDVDSubtitlesLibass::DeleteEvents(), CVideoDatabase::DeleteMusicVideo(), CMusicDatabase::DeleteRemovedLinks(), CRenderManager::DeleteRenderer(), ADDON::CAddonDatabase::DeleteRepository(), ADDON::CAddonDatabase::DeleteRepositoryContents(), CVideoDatabase::DeleteResumeBookMark(), KODI::RETRO::CSavestateDatabase::DeleteSavestate(), CVideoDatabase::DeleteSeason(), CVideoDatabase::DeleteSet(), CMediaSourceSettings::DeleteSource(), CVideoDatabase::DeleteTag(), CVideoDatabase::DeleteTvShow(), KODI::GAME::CPhysicalTopology::Deserialize(), KODI::GAME::CPhysicalPort::Deserialize(), KODI::GAME::CPhysicalFeature::Deserialize(), KODI::GAME::CControllerLayout::Deserialize(), CBooleanLogicValue::Deserialize(), CBooleanLogicOperation::Deserialize(), CSettingAddon::Deserialize(), CSettingControlButton::Deserialize(), CSettingControlTitle::Deserialize(), CSettingPath::Deserialize(), KODI::RETRO::CSavestateFlatBuffer::Deserialize(), KODI::GAME::CPortManager::DeserializeControllers(), KODI::GAME::CPortManager::DeserializePorts(), ADDON::CAddonDll::Destroy(), ADDON::Interface_GUIControlAddonRendering::destroy(), ADDON::Interface_GUIListItem::destroy(), ADDON::Interface_GUIWindow::destroy(), CDMAHeapBufferObject::DestroyBufferObject(), CDumbBufferObject::DestroyBufferObject(), CUDMABufferObject::DestroyBufferObject(), CWinSystemAndroid::DestroyWindow(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::DestroyWindow(), CGUIWindowManager::DestroyWindows(), CWinSystemAndroid::DestroyWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbm::DestroyWindowSystem(), CStereoscopicsManager::DetectStereoModeByString(), KODI::JOYSTICK::CAxisDetector::DetectType(), CUDisksProvider::DeviceAdded(), CLibInputHandler::DeviceAdded(), PERIPHERALS::CPeripheralBusUSB::DeviceAttachCallback(), CUDisksProvider::DeviceChanged(), deviceChangedCB(), PERIPHERALS::CPeripheralBusUSB::DeviceDetachCallback(), CUDisksProvider::DeviceRemoved(), CLibInputHandler::DeviceRemoved(), CBlurayCallback::dir_close(), CBlurayCallback::dir_open(), ADDON::Interface_Filesystem::directory_exists(), CPartyModeManager::Disable(), ADDON::CAddonDatabase::DisableAddon(), ADDON::CAddonMgr::DisableAddon(), ADDON::CAddonMgr::DisableIncompatibleAddons(), ActiveAE::CActiveAE::DiscardStream(), WSDiscovery::CWSDiscoveryListenerUDP::DispatchCommand(), CUdpClient::DispatchNextCommand(), DisplayReconfigured(), CDVDVideoCodecAndroidMediaCodec::Dispose(), CDVDDemuxFFmpeg::Dispose(), dll__security_error_handler(), dll_close(), dll_fclose(), dll_fdopen(), dll_feof(), dll_fgetc(), dll_fgetpos64(), dll_fgets(), dll_flockfile(), dll_fopen(), dll_fputc(), dll_fputs(), dll_fread(), dll_fscanf(), dll_fseek64(), dll_fsetpos(), dll_fsetpos64(), dll_fstat64(), dll_fstati64(), dll_ftell64(), dll_ftrylockfile(), dll_funlockfile(), dll_fwrite(), dll_getc(), dll_lseek(), dll_lseeki64(), dll_opendir(), dll_read(), dll_rewind(), dll_setvbuf(), dll_tell(), dll_telli64(), dll_ungetc(), dll_vfprintf(), dll_write(), dllcalloc(), dllFreeLibrary(), dllGetModuleHandleA(), XCURL::DllLibCurlGlobal::DllLibCurlGlobal(), dllLoadLibraryExExtended(), dllLoadLibraryExtended(), dllmalloc(), dllperror(), dllprintf(), dllputs(), dllrealloc(), dllvprintf(), ADDON::Interface_Network::dns_lookup(), ADDON::Interface_GUIWindow::do_modal(), PVR::CPVRClient::DoAddonCall(), CZeroconfBrowserMDNS::doAddServiceType(), CZeroconfBrowserAndroid::doAddServiceType(), CZeroconfBrowserDarwin::doAddServiceType(), CZeroconfBrowserAvahi::doAddServiceType(), ANNOUNCEMENT::CAnnouncementManager::DoAnnounce(), XBMCAddon::xbmcgui::Window::doModal(), CFileOperationJob::DoProcessFolder(), CZeroconfMDNS::doPublishService(), CZeroconfAndroid::doPublishService(), CZeroconfDarwin::doPublishService(), CZeroconfAvahi::doPublishService(), CZeroconfMDNS::doRemoveService(), CZeroconfAndroid::doRemoveService(), CZeroconfAvahi::doRemoveService(), CZeroconfBrowserAndroid::doRemoveServiceType(), CZeroconfBrowserMDNS::doResolveService(), CZeroconfBrowserAvahi::doResolveService(), CZeroconfBrowserAndroid::doResolveService(), MUSIC_INFO::CMusicInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::DoScan(), CZeroconfMDNS::doStop(), CZeroconfAndroid::doStop(), XFILE::CCurlFile::Download(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CDetectDisc::DoWork(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::DoWork(), ADDON::CRepositoryUpdateJob::DoWork(), KODI::CDRIP::CCDDARipJob::DoWork(), CImageLoader::DoWork(), CMACDiscoveryJob::DoWork(), CThumbnailWriter::DoWork(), CWeatherJob::DoWork(), CSaveFileState::DoWork(), CDVDVideoCodecDRMPRIME::Drain(), CAESinkAUDIOTRACK::Drain(), CAESinkOSS::Drain(), CAESinkSNDIO::Drain(), AE::SINK::CAESinkPipewire::Drain(), ActiveAE::CActiveAEStream::Drain(), KODI::PIPEWIRE::CPipewireStream::Drained(), ActiveAE::CActiveAE::DrainSink(), CUDisks2Provider::DriveAdded(), CUDisks2Provider::DrivePropertiesChanged(), CUDisks2Provider::DriveRemoved(), KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), anonymous_namespace{DRMUtils.cpp}::DrmFbDestroyCallback(), KODI::WINDOWING::GBM::CDRMUtils::DrmFbGetFromBo(), CTextureMap::Dump(), CGUITextureManager::Dump(), dumpAVAudioSessionProperties(), CXHandle::DumpObjectTracker(), CRegExp::DumpOvector(), CDirectoryHistory::DumpPathHistory(), dvd_inputstreamnavigator_cb_read(), dvd_logger(), XCURL::DllLibCurlGlobal::easy_acquire(), EglErrorCallback(), Shaders::CGLSLShaderProgram::Enable(), CPartyModeManager::Enable(), ADDON::CAddonDatabase::EnableAddon(), ADDON::CAddonMgr::EnableAddon(), CRenderSystemGLES::EnableGUIShader(), CWin32DPMSSupport::EnablePowerSaving(), KODI::RETRO::CCheevos::EnableRichPresence(), CRenderSystemGL::EnableShader(), ADDON::CAddonMgr::EnableSingle(), CAEEncoderFFmpeg::Encode(), KODI::CDRIP::CEncoder::EncoderEncode(), KODI::CDRIP::CEncoder::EncoderInit(), DRM::CMediaDrmCryptoSession::Encrypt(), CTeletextDecoder::EndDecoder(), VDPAU::COutput::EnsureBufferPool(), CAESinkALSA::EnumerateDevice(), EnumerateDevices(), EnumerateDevices(), CAESinkALSA::EnumerateDevicesEx(), CAESinkOSS::EnumerateDevicesEx(), CAESinkPULSE::EnumerateDevicesEx(), CAESinkSNDIO::EnumerateDevicesEx(), AE::SINK::CAESinkPipewire::EnumerateDevicesEx(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), ActiveAE::CActiveAESink::EnumerateSinkList(), anonymous_namespace{PVRBuiltins.cpp}::EpgGridControl(), CVideoDatabase::EraseAllForFile(), CVideoDatabase::EraseAllForPath(), CVideoDatabase::EraseAllVideoSettings(), CVideoDatabase::EraseAllVideoSettings(), CVideoDatabase::EraseVideoSettings(), err(), CDVDClock::ErrorAdjust(), CUtil::ExcludeFileOrFolder(), XFILE::CDAVFile::Execute(), CBuiltins::Execute(), CPythonInvoker::Execute(), CPythonInvoker::execute(), CScriptInvocationManager::ExecuteAsync(), CScriptInvocationManager::ExecuteAsync(), XBMCAddon::xbmc::executebuiltin(), CFileOperationJob::CFileOperation::ExecuteOperation(), CDatabase::ExecuteQuery(), CScriptRunner::ExecuteScript(), CScriptInvocationManager::ExecuteSync(), dbiplus::MysqlDatabase::exists(), XFILE::CFile::Exists(), XFILE::CCurlFile::Exists(), XFILE::CMultiPathDirectory::Exists(), XFILE::CDirectory::Exists(), CVideoBufferDMA::Export(), CTextureCache::Export(), CTextureCache::Export(), CMusicDatabase::ExportSongHistory(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), Extract(), CFFmpegImage::ExtractFrame(), CDVDFileInfo::ExtractThumbToTexture(), CALSADeviceMonitor::FDEventCallback(), ADDON::CRepository::FetchChecksum(), fetchDisplayModes(), ADDON::CRepository::FetchIfChanged(), ADDON::CRepository::FetchIndex(), ff_avutil_log(), VAAPI::CDecoder::FFGetBuffer(), VDPAU::CDecoder::FFGetBuffer(), ADDON::Interface_Filesystem::file_exists(), CBlurayCallback::file_open(), MUSIC_INFO::CMusicInfoScanner::FileItemsToAlbums(), CUDisks2Provider::FilesystemAdded(), CUDisks2Provider::FilesystemPropertiesChanged(), CUDisks2Provider::FilesystemRemoved(), XFILE::CCurlFile::CReadState::FillBuffer(), KODI::GAME::CGameUtils::FillInGameClient(), CWinSystemIOS::FillInVideoModes(), CWinSystemTVOS::FillInVideoModes(), VAAPI::CVppPostproc::Filter(), VAAPI::CFFmpegPostproc::Filter(), CDVDVideoCodecFFmpeg::FilterClose(), CDVDVideoCodecFFmpeg::FilterOpen(), CDVDVideoCodecFFmpeg::FilterProcess(), CProfileManager::FinalizeLoadProfile(), ADDON::CAddonMgr::FindAddon(), ADDON::CAddonMgr::FindAddons(), ADDON::CAddonMgr::FindAddons(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), CCoreAudioHardware::FindAudioDevice(), ADDON::CAddonDatabase::FindByAddonId(), KODI::WINDOWING::GBM::CDRMUtils::FindConnector(), KODI::WINDOWING::GBM::CDRMUtils::FindCrtc(), CGUIWindowSettingsScreenCalibration::FindCurrentResolution(), KODI::WINDOWING::GBM::CDRMUtils::FindEncoder(), DllLoaderContainer::FindModule(), ADDON::CScraper::FindMovie(), KODI::WINDOWING::GBM::CDRMUtils::FindPreferredMode(), CResolutionUtils::FindResolutionFromOverride(), CResolutionUtils::FindResolutionFromWhitelist(), AEDeviceEnumerationOSX::FindSuitableFormatForStream(), VAAPI::CDecoder::FiniVAAPIOutput(), VDPAU::CDecoder::FiniVDPAUOutput(), PVR::CPVRDatabase::FixupClientIDs(), KODI::WINDOWING::GBM::CDRMAtomic::FlipPage(), CAudioSinkAE::Flush(), VDPAU::COutput::Flush(), XFILE::CFile::Flush(), CRenderManager::Flush(), ADDON::Interface_Filesystem::flush_file(), CArchive::FlushBuffer(), CVideoPlayer::FlushBuffers(), ActiveAE::CActiveAE::FlushEngine(), CDVDSubtitlesLibass::FlushEvents(), ActiveAE::CActiveAE::FlushStream(), CGUIWindowSettingsCategory::FocusElement(), CGUIControlSliderSetting::FormatText(), KODI::RETRO::CRPRenderManager::FrameMove(), ADDON::Interface_Filesystem::free_directory(), CDVDDemuxUtils::FreeDemuxPacket(), CGUIVisualisationControl::FreeResources(), ActiveAE::CActiveAE::FreeStream(), ADDON::CAddonInfoBuilder::Generate(), ADDON::CAddonInfoBuilder::Generate(), CScraperUrl::Get(), CDVDMessageQueue::Get(), CColorManager::Get3dLutSize(), ADDON::Interface_Base::get_addon_info(), ADDON::Interface_Base::get_addon_path(), ADDON::Interface_GUIGeneral::get_adjust_refresh_rate_status(), ADDON::Interface_GUIListItem::get_art(), ADDON::Interface_Filesystem::get_cache_thumb_name(), ADDON::Interface_Filesystem::get_content_type(), ADDON::Interface_Filesystem::get_cookies(), ADDON::Interface_GUIWindow::get_current_container_id(), ADDON::Interface_GUIWindow::get_current_list_position(), ADDON::Interface_AudioEngine::get_current_sink_format(), ADDON::Interface_General::get_current_skin_id(), ADDON::Interface_GUIGeneral::get_current_window_dialog_id(), ADDON::Interface_GUIGeneral::get_current_window_id(), ADDON::Interface_GUIControlEdit::get_cursor_position(), ADDON::Interface_GUIControlSlider::get_description(), ADDON::Interface_Filesystem::get_directory(), ADDON::Interface_Filesystem::get_disk_space(), ADDON::Interface_Filesystem::get_file_chunk_size(), ADDON::Interface_Filesystem::get_file_download_speed(), ADDON::Interface_Filesystem::get_file_length(), ADDON::Interface_Filesystem::get_file_md5(), ADDON::Interface_Filesystem::get_file_position(), ADDON::Interface_GUIControlSettingsSlider::get_float_value(), ADDON::Interface_GUIControlSlider::get_float_value(), ADDON::Interface_GUIControlSpin::get_float_value(), ADDON::Interface_GUIWindow::get_focus_id(), ADDON::Interface_General::get_free_mem(), ADDON::Interface_General::get_global_idle_time(), ADDON::Interface_Network::get_hostname(), ADDON::Interface_Filesystem::get_http_header(), ADDON::IAddonInstanceHandler::get_instance_setting_bool(), ADDON::IAddonInstanceHandler::get_instance_setting_float(), ADDON::IAddonInstanceHandler::get_instance_setting_int(), ADDON::IAddonInstanceHandler::get_instance_setting_string(), ADDON::Interface_GUIControlSettingsSlider::get_int_value(), ADDON::Interface_GUIControlSlider::get_int_value(), ADDON::Interface_GUIControlSpin::get_int_value(), ADDON::Interface_Network::get_ip_address(), ADDON::Interface_General::get_keyboard_layout(), ADDON::Interface_GUIControlButton::get_label(), ADDON::Interface_GUIControlEdit::get_label(), ADDON::Interface_GUIControlFadeLabel::get_label(), ADDON::Interface_GUIControlLabel::get_label(), ADDON::Interface_GUIControlRadioButton::get_label(), ADDON::Interface_GUIListItem::get_label(), ADDON::Interface_GUIControlButton::get_label2(), ADDON::Interface_GUIListItem::get_label2(), ADDON::Interface_General::get_language(), ADDON::Interface_Base::get_lib_path(), ADDON::Interface_GUIWindow::get_list_item(), ADDON::Interface_GUIWindow::get_list_size(), ADDON::Interface_Base::get_localized_string(), ADDON::Interface_General::get_md5(), ADDON::Interface_Filesystem::get_mime_type(), ADDON::Interface_GUIListItem::get_path(), ADDON::Interface_GUIControlProgress::get_percentage(), ADDON::Interface_GUIControlSettingsSlider::get_percentage(), ADDON::Interface_GUIControlSlider::get_percentage(), ADDON::Interface_GUIDialogExtendedProgress::get_percentage(), ADDON::Interface_GUIDialogProgress::get_percentage(), ADDON::Interface_GUIListItem::get_property(), ADDON::Interface_GUIWindow::get_property(), ADDON::Interface_GUIWindow::get_property_bool(), ADDON::Interface_GUIWindow::get_property_double(), ADDON::Interface_GUIWindow::get_property_int(), ADDON::Interface_Filesystem::get_property_values(), ADDON::Interface_General::get_region(), ADDON::Interface_GUIGeneral::get_screen_height(), ADDON::Interface_GUIGeneral::get_screen_width(), ADDON::Interface_Base::get_setting_bool(), ADDON::Interface_Base::get_setting_float(), ADDON::Interface_Base::get_setting_int(), ADDON::Interface_Base::get_setting_string(), ADDON::Interface_GUIControlSpin::get_string_value(), ADDON::Interface_Base::get_temp_path(), ADDON::Interface_GUIControlEdit::get_text(), ADDON::Interface_GUIControlTextBox::get_text(), ADDON::Interface_GUIDialogExtendedProgress::get_text(), ADDON::Interface_GUIDialogExtendedProgress::get_title(), ADDON::Interface_Network::get_user_agent(), ADDON::Interface_Base::get_user_path(), ADDON::Interface_GUIGeneral::get_video_resolution(), KODI::KEYMAP::CButtonTranslator::GetActionCode(), ADDON::CAddonDatabase::GetAddon(), ADDON::CBinaryAddonBase::GetAddon(), ADDON::CAddonDatabase::GetAddon(), ADDON::CBinaryAddonManager::GetAddonBase(), ADDON::CGUIAddonWindow::GetAddonControl(), XBMCAddon::Python::PythonLanguageHook::GetAddonId(), PERIPHERALS::CPeripheralAddon::GetAddonProperties(), ADDON::CAddonMgr::GetAddonsWithAvailableUpdate(), ADDON::CAddonDatabase::GetAddonUpdateRules(), XBMCAddon::Python::PythonLanguageHook::GetAddonVersion(), PERIPHERALS::CPeripheralBusAddon::GetAddonWithButtonMap(), CZeroconfBrowserMDNS::GetAddrInfoCallback(), CGUIMediaWindow::GetAdvanceFilteredItems(), AEDeviceEnumerationOSX::GetAEChannelMap(), CMusicDatabase::GetAlbum(), CMusicDatabase::GetAlbumByMatch(), CMusicDatabase::GetAlbumByName(), ADDON::CScraper::GetAlbumDetails(), CMusicDatabase::GetAlbumFromSong(), CMusicDatabase::GetAlbumIdByPath(), CMusicDatabase::GetAlbumPaths(), CMusicDatabase::GetAlbumsByArtist(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CDBusUtil::GetAll(), CVideoDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtist(), CMusicDatabase::GetArtistByMatch(), CMusicDatabase::GetArtistByName(), ADDON::CScraper::GetArtistDetails(), CMusicDatabase::GetArtistDiscography(), CMusicDatabase::GetArtistExists(), CMusicDatabase::GetArtistFromMBID(), CMusicDatabase::GetArtistFromSong(), CMusicDatabase::GetArtistsByAlbum(), CMusicDatabase::GetArtistsByAlbum(), CMusicDatabase::GetArtistsBySong(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetArtistsNav(), CMusicDatabase::GetArtTypes(), CVideoDatabase::GetArtTypes(), ADDON::CScraper::GetArtwork(), CDateTime::GetAsRFC1123DateTime(), CCoreAudioHardware::GetAutoHogMode(), ADDON::CAddonMgr::GetAvailableUpdatesOrOutdatedAddons(), KODI::JOYSTICK::CButtonMapping::GetAxis(), CVideoDatabase::GetBookMarkForEpisode(), CVideoDatabase::GetBookMarksForFile(), KODI::RETRO::CBaseRenderBufferPool::GetBuffer(), CCoreAudioDevice::GetBufferSize(), CDNSNameCache::GetCached(), WSDiscovery::CWSDiscoveryPosix::GetCached(), CTextureDatabase::GetCachedTexture(), CVideoPlayer::GetCachingTimes(), CVideoDatabase::GetCast(), MEDIA_DETECT::CCdIoSupport::GetCdInfo(), CAESinkALSA::GetChannelLayout(), CMusicDatabase::GetCommonNav(), ADDON::CAddonMgr::GetCompatibleVersions(), DXVA::CContext::GetConfig(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetContentRanges(), XFILE::CCurlFile::GetContentType(), CNfsConnection::getContextForExport(), CNfsConnection::getContextFromMap(), ADDON::Interface_GUIWindow::GetControl(), KODI::GAME::CGameClientDevice::GetController(), CConverterType::GetConverter(), XFILE::CCurlFile::GetCookies(), CPosixResourceCounter::GetCPUUsage(), CNetworkInterfaceIOS::GetCurrentDefaultGateway(), CNetworkInterfaceMacOS::GetCurrentDefaultGateway(), CProfileManager::GetCurrentProfile(), CExternalPlayer::GetCustomRegexpReplacers(), CDVDAudioCodecAndroidMediaCodec::GetData(), CDVDAudioCodecAndroidMediaCodec::GetData(), CAudioDecoder::GetData(), DatabaseUtils::GetDatabaseResults(), CDVDAudioCodecFFmpeg::GetDataFormat(), CCoreAudioHardware::GetDefaultOutputDevice(), CVideoDatabase::GetDefaultVideoVersion(), CAESinkAUDIOTRACK::GetDelay(), XFILE::CHTTPDirectory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMultiPathDirectory::GetDirectory(), XFILE::CMusicSearchDirectory::GetDirectory(), XFILE::CNFSDirectory::GetDirectory(), XFILE::CRSSDirectory::GetDirectory(), XFILE::CZeroconfDirectory::GetDirectory(), XFILE::CAndroidAppDirectory::GetDirectory(), XFILE::CAPKDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), XFILE::CWin32Directory::GetDirectory(), XFILE::CDirectory::GetDirectory(), CGUIMediaWindow::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), ADDON::CAddonDatabase::GetDisabled(), CMusicDatabase::GetDiscnumberForPathID(), CMusicDatabase::GetDiscsByWhere(), ADDON::CAddonDll::GetDllPath(), CAndroidUtils::GetDolbyVisionCapabilities(), CAEStreamInfo::GetDuration(), CVideoInfoTag::GetDurationFromMinuteString(), CGLContextEGL::GetEGLConfig(), CVideoDatabase::GetEpisodeBasicInfo(), CVideoDatabase::GetEpisodeId(), CVideoDatabase::GetEpisodeInfo(), ADDON::CScraper::GetEpisodeList(), CVideoDatabase::GetEpisodesByFile(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CDVDSubtitlesLibass::GetEvents(), CGUIDialogLibExportSettings::GetExportItemsFromSetting(), CUtil::GetExternalStreamDetailsFromFilename(), AEDeviceEnumerationOSX::getExtraDisplayNameForStream(), CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput(), CVideoDatabase::GetFileBasePathById(), CVideoDatabase::GetFileId(), CVideoDatabase::GetFileIdByMovie(), CVideoDatabase::GetFileInfo(), CVideoDatabase::GetFilePathById(), XBMCAddon::xbmc::InfoTagVideo::getFirstAired(), CNetworkPosix::GetFirstConnectedInterface(), CDVDVideoCodecDRMPRIME::GetFormat(), DXVA::CContext::GetFormatAndConfig(), CZeroconfBrowser::GetFoundServices(), CVideoSyncAndroid::GetFps(), CVideoSyncGbm::GetFps(), CVideoSyncIos::GetFps(), CVideoSyncOsx::GetFps(), CVideoSyncTVos::GetFps(), CAddonVideoCodec::GetFrameBuffer(), VAAPI::CVideoSurfaces::GetFree(), VDPAU::CVideoSurfaces::GetFree(), CMusicDatabase::GetGenreByName(), CMusicDatabase::GetGenresByAlbum(), CMusicDatabase::GetGenresByArtist(), CMusicDatabase::GetGenresBySong(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetGenresNav(), CALSAHControlMonitor::GetHandle(), XFILE::CCurlFile::GetHttpHeader(), CTextureCacheJob::GetImageHash(), XFILE::CCurlFile::GetInfoString(), PERIPHERALS::CPeripheralBusAndroid::GetInputDevices(), PERIPHERALS::CPeripheralBusGCController::GetInputDevices(), ADDON::CAddonDatabase::GetInstallData(), XBMCAddon::Python::PythonLanguageHook::GetInvokerId(), CMusicDatabase::GetIsAlbumArtist(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), DRM::CMediaDrmCryptoSession::GetKeyRequest(), CDVDDemuxFFmpeg::GetL16Parameters(), KODI::GAME::CGUIPortList::GetLabel(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), CScriptInvocationManager::GetLanguageInvoker(), XBMCAddon::xbmc::InfoTagMusic::getLastPlayed(), XBMCAddon::xbmc::InfoTagVideo::getLastPlayed(), CVideoDatabase::GetLastPlayed(), XFILE::CFile::GetLength(), CDVDMessageQueue::GetLevel(), CVideoDatabase::GetLinksToTvShow(), CNetworkInterfaceAndroid::GetMacAddress(), CNetworkInterfaceAndroid::GetMacAddressRaw(), PERIPHERALS::CPeripherals::GetMappingForDevice(), CProfileManager::GetMasterProfile(), CVideoDatabase::GetMatchingMusicVideo(), CMusicDatabase::GetMatchingMusicVideoAlbum(), CUtil::GetMatchingSource(), CDMAHeapBufferObject::GetMemory(), CDumbBufferObject::GetMemory(), CUDMABufferObject::GetMemory(), XFILE::CCurlFile::GetMimeType(), CCoreAudioDevice::GetMixingSupport(), getModeForResolution(), CFileUtils::GetModificationDate(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMovieId(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), KODI::VIDEO::CVideoInfoScanner::GetMovieSetInfoFolder(), CMusicDatabase::GetMusicNeedsTagScan(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideoId(), CVideoDatabase::GetMusicVideoInfo(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByArtist(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CCoreAudioDevice::GetName(), CNetworkIOS::GetNameServers(), CNetworkMacOS::GetNameServers(), CAndroidUtils::GetNativeResolution(), CVideoDatabase::GetNavCommon(), ADDON::Interface_GUIWindow::GetNextAvailableWindowId(), KODI::PLAYLIST::CPlayListPlayer::GetNextItemIdx(), CCoreAudioDevice::GetNominalSampleRate(), CCoreAudioDevice::GetNumChannelsOfStream(), CMusicDatabase::GetOldArtistPath(), CTextureDatabase::GetOldestCachedImages(), CCoreAudioHardware::GetOutputDevices(), CDVDVideoCodecAndroidMediaCodec::GetOutputPicture(), CMusicDatabase::GetPathHash(), CVideoDatabase::GetPathHash(), CVideoDatabase::GetPathId(), CMusicDatabase::GetPaths(), CVideoDatabase::GetPaths(), CVideoDatabase::GetPathsForTvShow(), CVideoDatabase::GetPathsLinkedToTvShow(), CVideoDatabase::GetPeopleNav(), CAddonVideoCodec::GetPicture(), CDVDVideoCodecAndroidMediaCodec::GetPicture(), CDVDVideoCodecDRMPRIME::GetPicture(), CDVDVideoCodecFFmpeg::GetPicture(), CLinuxRendererGL::GetPlaneTextureSize(), CVideoDatabase::GetPlayCount(), CVideoDatabase::GetPlayCounts(), CPlayerCoreFactory::GetPlayerIndex(), CPlayerCoreFactory::GetPlayers(), CPlayerSelectionRule::GetPlayers(), CPlayerCoreFactory::GetPlayers(), KODI::RETRO::CRetroPlayer::GetPlayerState(), CDVDSubtitlesLibass::GetPlayResY(), CPODocument::GetPlurMsgstr(), GetPos(), XFILE::CFile::GetPosition(), XFILE::CNFSFile::GetPosition(), CCoreAudioDevice::GetPreferredChannelLayout(), CCoreAudioDevice::GetPreferredChannelLayoutForStereo(), XBMCAddon::xbmc::InfoTagVideo::getPremiered(), GetProductAndVendorId(), XBMCAddon::xbmcgui::ListItem::getProperty(), KODI::GAME::CGameClientProperties::GetProxyAddons(), CVideoDatabase::GetRandomMusicVideoIDs(), CMusicDatabase::GetRandomSongIDs(), XBMCAddon::xbmcgui::ListItem::getRating(), CVideoDatabase::GetRatings(), CMusicDatabase::GetRecentlyAddedAlbums(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), CMusicDatabase::GetRecentlyPlayedAlbums(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), CAndroidStorageProvider::GetRemovableDrivesLinux(), KODI::RETRO::CRPRenderManager::GetRendererForPool(), CLibInputKeyboard::GetRepeat(), CAudioDecoder::GetReplayGain(), ADDON::CAddonDatabase::GetRepoChecksum(), ADDON::CAddonDatabase::GetRepositoryContent(), ADDON::CAddonDatabase::GetRepoUpdateData(), XFILE::CUPnPDirectory::GetResource(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), CVideoDatabase::GetResumePoint(), KODI::RETRO::CCheevos::GetRichPresenceEvaluation(), CMusicDatabase::GetRoleByName(), CMusicDatabase::GetRolesByArtist(), CMusicDatabase::GetRolesNav(), XFILE::CBlurayDirectory::GetRoot(), CVideoDatabase::GetSameVideoItems(), AEDeviceEnumerationOSX::getSampleRateListForStream(), KODI::RETRO::CSavestateDatabase::GetSavestate(), CMusicDatabase::GetScraper(), CVideoDatabase::GetScraperForPath(), CWinSystemIOS::GetScreenResolution(), CWinSystemTVOS::GetScreenResolution(), CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetSeasonsByWhere(), CSeekHandler::GetSeekStepSize(), DatabaseUtils::GetSelectFields(), CVideoDatabase::GetSetInfo(), CVideoDatabase::GetSetsByWhere(), ADDON::IAddonInstanceHandler::GetSetting(), CBaseRenderer::GetShaderFormat(), CDatabase::GetSingleValue(), CDatabase::GetSingleValueInt(), CMusicDatabase::GetSong(), CMusicDatabase::GetSongByArtistAndAlbumAndTitle(), CMusicDatabase::GetSongIDFromPath(), CMusicDatabase::GetSongsByArtist(), CMusicDatabase::GetSongsByPath(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsCount(), CGUIWindowMusicNav::GetSongsFromPlayList(), CMusicDatabase::GetSongsFullByWhere(), GetSoundSkinPath(), CMediaSourceSettings::GetSource(), CMusicDatabase::GetSourceByName(), CMusicDatabase::GetSourceFromPath(), CVideoDatabase::GetSourcePath(), CMusicDatabase::GetSources(), CMediaSourceSettings::GetSources(), CMusicDatabase::GetSourcesByAlbum(), CMusicDatabase::GetSourcesByArtist(), CMusicDatabase::GetSourcesBySong(), CMusicDatabase::GetSourcesNav(), XFILE::CStackDirectory::GetStackedTitlePath(), CVideoDatabase::GetStackTimes(), CDVDInputStreamNavigator::GetState(), CStereoscopicsManager::GetStereoModeOfPlayingVideo(), CVideoDatabase::GetStreamDetails(), CDVDInputStreamBluray::GetStreamInfo(), CVideoDatabase::GetSubPaths(), CVideoDatabase::GetTags(), KODI::RETRO::CWinRenderBuffer::GetTexture(), CTextureDatabase::GetTextureForPath(), CGUITextureManager::GetTexturePath(), CTextureDatabase::GetTextures(), CDVDInputStreamBluray::GetTitleFile(), CDVDInputStreamBluray::GetTitleLongest(), XFILE::CBlurayDirectory::GetTitles(), CMusicDatabase::GetTop100(), CMusicDatabase::GetTop100Albums(), CMusicDatabase::GetTop100AlbumSongs(), CCoreAudioDevice::GetTotalOutputChannels(), CVideoDatabase::GetTvShowForEpisode(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowId(), CVideoDatabase::GetTvShowInfo(), CVideoDatabase::GetTvShowNamedSeasons(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), CVideoDatabase::GetTvShowSeasonArt(), CVideoDatabase::GetTvShowSeasons(), XBMCAddon::xbmcgui::ListItem::getUniqueID(), CVideoDatabase::GetUniqueIDs(), CMusicDatabase::GetUsedImages(), XFILE::CBlurayDirectory::GetUserPlaylists(), CDBusUtil::GetVariant(), CColorManager::GetVideo3dLut(), CDVDInputStreamNavigator::GetVideoAspectRatio(), KODI::RETRO::CRPRenderManager::GetVideoBuffer(), ADDON::CScraper::GetVideoDetails(), CDVDInputStreamNavigator::GetVideoResolution(), CVideoDatabase::GetVideoSettings(), CVideoDatabase::GetVideoVersions(), CVideoDatabase::GetVideoVersionsNav(), CVideoDatabase::GetVideoVersionTypes(), CViewDatabase::GetViewState(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::GetVisual(), XBMCAddon::xbmc::InfoTagVideo::getVotes(), XBMCAddon::xbmcgui::ListItem::getVotes(), CMusicDatabase::GetYearsNav(), CVideoDatabase::GetYearsNav(), CZipManager::GetZipList(), KODI::UTILS::GL::GlErrorCallback(), KODI::UTILS::GL::glFormatElementByteCount(), CAddonPythonInvoker::GlobalInitializeModules(), CHTTPPythonWsgiInvoker::GlobalInitializeModules(), CZeroconfAvahi::groupCallback(), CAEUtil::GuessChLayout(), CWebSocket::Handle(), CWebSocketManager::Handle(), handle_708_C3(), CTeletextDecoder::HandleAction(), PVR::CPVRClient::HandleAddonCallback(), anonymous_namespace{Seat.cpp}::HandleCapabilityChange(), CAESinkALSA::HandleError(), CVideoPlayer::HandleMessages(), JSONRPC::CJSONRPC::HandleMethodCall(), CVideoPlayer::HandlePlaySpeed(), KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::HandlePresentation(), CApplicationPowerHandling::HandleShutdownMessage(), CGenericTouchInputHandler::HandleTouchInput(), CWinEventsWin10::HandleWindowSizeChanged(), CWebSocketV13::Handshake(), CWebSocketV8::Handshake(), CCoreAudioStream::HardwareStreamListener(), CVideoDatabase::HasArtForItem(), CVideoDatabase::HasContent(), CVideoDatabase::HasEpisodeInfo(), CDarwinEmbedKeyboard::hasExternalKeyboard(), KODI::GAME::CGameClientInput::HasFeature(), CTextureBundleXBT::HasFile(), CLogindUPowerSyscall::HasLogind(), CVideoDatabase::HasMovieInfo(), CVideoDatabase::HasMusicVideoInfo(), CInfoScanner::HasNoMedia(), CVideoDatabase::HasSets(), CVideoDatabase::HasTvShowInfo(), KODI::WINDOWING::X11::CWinSystemX11::HasWindowManager(), CALSAHControlMonitor::HCTLCallback(), CCocoaPowerSyscall::Hibernate(), CWinSystemWin10::Hide(), ADDON::Interface_Filesystem::http_header_create(), ADDON::Interface_Filesystem::http_header_free(), ADDON::Interface_Filesystem::http_header_get_charset(), ADDON::Interface_Filesystem::http_header_get_header(), ADDON::Interface_Filesystem::http_header_get_mime_type(), ADDON::Interface_Filesystem::http_header_get_proto_line(), ADDON::Interface_Filesystem::http_header_get_value(), ADDON::Interface_Filesystem::http_header_get_values(), CVideoDatabase::ImportFromXML(), CMusicDatabase::ImportFromXML(), CMusicDatabase::ImportSongHistory(), CMusicDatabase::IncrementPlayCount(), KODI::PIPEWIRE::CPipewireNode::Info(), KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::Inhibit(), CLogindUPowerSyscall::InhibitDelayLock(), ADDON::CAddonMgr::Init(), TVOSLibInputHandler::init, KODI::CDRIP::CEncoderFFmpeg::Init(), KODI::ADDONS::CAudioDecoder::Init(), VideoPlayerCodec::Init(), KODI::WINDOWING::X11::CWinEventsX11::Init(), VAAPI::CFFmpegPostproc::Init(), ActiveAE::CActiveAEResampleFFMPEG::Init(), VDPAU::CInteropState::Init(), KODI::GUILIB::GUIINFO::CGamesGUIInfo::InitCurrentItem(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::InitCurrentItem(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::InitCurrentItem(), VAAPI::COutput::InitCycle(), CTeletextDecoder::InitDecoder(), XFILE::CZipFile::InitDecompress(), CVideoSyncIos::InitDisplayLink(), CVideoSyncOsx::InitDisplayLink(), CVideoSyncTVos::InitDisplayLink(), KODI::WINDOWING::GBM::CDRMUtils::InitDrm(), KODI::WINDOWING::GBM::CDRMAtomic::InitDrm(), KODI::WINDOWING::GBM::CDRMLegacy::InitDrm(), KODI::WINDOWING::GBM::COffScreenModeSetting::InitDrm(), CServiceManager::InitForTesting(), CWinSystemWin32DX::InitHooks(), PERIPHERALS::CPeripheral::Initialise(), PERIPHERALS::CPeripheralHID::InitialiseFeature(), PERIPHERALS::CPeripheralJoystick::InitialiseFeature(), CRenderSystemGL::InitialiseShaders(), CRenderSystemGLES::InitialiseShaders(), CApplication::Initialize(), KODI::RETRO::CRPRenderManager::Initialize(), CDebugRenderer::Initialize(), CDatabaseManager::Initialize(), JSONRPC::CJSONRPC::Initialize(), CAirPlayServer::Initialize(), JSONRPC::CTCPServer::Initialize(), CWin32StorageProvider::Initialize(), CUDevProvider::Initialize(), CUDisks2Provider::Initialize(), CUDisksProvider::Initialize(), CPosixMountProvider::Initialize(), CStorageProvider::Initialize(), CAEEncoderFFmpeg::Initialize(), CAESinkDirectSound::Initialize(), CAESinkALSA::Initialize(), CAESinkAUDIOTRACK::Initialize(), CAESinkDARWINOSX::Initialize(), CAESinkDARWINTVOS::Initialize(), CAESinkOSS::Initialize(), CAESinkPULSE::Initialize(), CAESinkSNDIO::Initialize(), AE::SINK::CAESinkPipewire::Initialize(), INFO::InfoExpression::Initialize(), PERIPHERALS::CAndroidJoystickState::Initialize(), CSettings::Initialize(), CExternalPlayer::Initialize(), CPlayerSelectionRule::Initialize(), CFFmpegImage::Initialize(), JSONRPC::CTCPServer::InitializeBlue(), XFILE::CBlurayDirectory::InitializeBluray(), PERIPHERALS::CPeripheralBusAndroid::InitializeButtonMap(), PERIPHERALS::CAndroidJoystickState::InitializeButtonMap(), CSettings::InitializeDefaults(), CSettings::InitializeDefinitions(), CEGLContextUtils::InitializeDisplay(), CAESinkWASAPI::InitializeExclusive(), CAESinkALSA::InitializeHW(), CAESinkXAudio::InitializeInternal(), PERIPHERALS::CPeripheralBusAndroid::InitializeProperties(), PERIPHERALS::CPeripheralBusGCController::InitializeProperties(), CDBusMessage::InitializeReplyIter(), CGUIDialogMediaFilter::InitializeSettings(), CGUIDialogInfoProviderSettings::InitializeSettings(), CGUIDialogNetworkSetup::InitializeSettings(), PERIPHERALS::CGUIDialogPeripheralSettings::InitializeSettings(), CGUIDialogLockSettings::InitializeSettings(), CGUIDialogProfileSettings::InitializeSettings(), CGUIDialogContentSettings::InitializeSettings(), CGUIDialogLibExportSettings::InitializeSettings(), CGUIDialogAudioSettings::InitializeSettings(), CGUIDialogCMSSettings::InitializeSettings(), CGUIDialogSubtitleSettings::InitializeSettings(), CGUIDialogVideoSettings::InitializeSettings(), CAESinkALSA::InitializeSW(), ActiveAE::CActiveAEStream::InitRemapper(), CRenderSystemGL::InitRenderSystem(), CRenderSystemGLES::InitRenderSystem(), CDatabase::InitSettings(), ActiveAE::CActiveAE::InitSink(), CPlatformAndroid::InitStageThree(), CServiceManager::InitStageThree(), CPlatformWebOS::InitStageTwo(), CServiceManager::InitStageTwo(), CApplication::InitWindow(), CWinSystemAndroidGLESContext::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbm::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::InitWindowSystem(), CWinSystemWin10::InitWindowSystem(), KODI::WINDOWING::X11::CWinSystemX11::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL(), CDVDVideoCodecAndroidMediaCodec::InjectExtraData(), KODI::GAME::CGameClientInput::InputEvent(), Shaders::CShader::InsertSource(), ADDON::CAddonInstaller::Install(), KODI::GAME::CGameUtils::Install(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), KODI::GAME::CGameClientProperties::InstallDependencies(), ADDON::CAddonInstaller::InstallFromZip(), CFilesystemInstaller::InstallToFilesystem(), XBMCAddon::xbmcgui::Interceptor< P >::Interceptor(), XBMCAddon::xbmcgui::Interceptor< P >::Interceptor(), ADDON::Interface_Filesystem::io_control_get_cache_status(), ADDON::Interface_Filesystem::io_control_get_seek_possible(), ADDON::Interface_Filesystem::io_control_set_cache_rate(), ADDON::Interface_Filesystem::io_control_set_retry(), XFILE::CFileCache::IoControl(), ADDON::Interface_General::is_addon_avilable(), ADDON::Interface_GUIDialogProgress::is_canceled(), ADDON::Interface_GUIDialogExtendedProgress::is_finished(), ADDON::Interface_Network::is_host_on_lan(), ADDON::Interface_Filesystem::is_internet_stream(), ADDON::Interface_GUIDialogKeyboard::is_keyboard_activated(), ADDON::Interface_Filesystem::is_local(), ADDON::Interface_Network::is_local_host(), ADDON::Interface_Filesystem::is_on_lan(), ADDON::Interface_Filesystem::is_remote(), ADDON::Interface_GUIControlRadioButton::is_selected(), ADDON::Interface_GUIListItem::is_selected(), ADDON::Interface_Base::is_setting_using_default(), ADDON::Interface_Filesystem::is_url(), CVideoDatabase::IsDefaultVideoVersion(), CAndroidUtils::IsHDRDisplay(), CTVOSNSUserDefaults::IsKeyFromPath(), CVideoDatabase::IsLinkedToTvshow(), CGUIPassword::IsMediaFileUnlocked(), XFILE::CPluginDirectory::IsMediaLibraryScanningAllowed(), anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked(), URIUtils::IsOnDVD(), KODI::UTILS::CDisplayInfo::IsValid(), KODI::GAME::CControllerLayout::IsValid(), CZeroconfMDNS::IsZCdaemonRunning(), ADDON::Interface_General::kodi_version(), XBMCAddon::Python::PyContext::leaveContext(), libass_log(), CVideoDatabase::LinkMovieToTvshow(), SOCKETS::CSocketListener::Listen(), ADDON::CScraper::Load(), Win32DllLoader::Load(), DllDynamic::Load(), CGUIAudioManager::Load(), KODI::KEYMAP::CButtonTranslator::Load(), EVENTCLIENT::CEventButtonState::Load(), CProfileManager::Load(), CSettingsComponent::Load(), CRssManager::Load(), SoLoader::Load(), KODI::GAME::CDefaultButtonMap::Load(), CGUIColorManager::Load(), CMediaSourceSettings::Load(), CSettings::Load(), KODI::KEYMAP::CIRTranslator::Load(), KODI::KEYBOARD::CKeyboardLayoutManager::Load(), KODI::PLAYLIST::CPlayList::Load(), KODI::PLAYLIST::CPlayListPLS::Load(), KODI::PLAYLIST::CPlayListXML::Load(), KODI::PLAYLIST::CPlayListXSPF::Load(), CGUIWindow::Load(), MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load(), MUSIC_INFO::CMusicInfoTagLoaderSHN::Load(), CTagLoaderTagLib::Load(), CLangInfo::Load(), CGUITextureManager::Load(), KODI::KEYBOARD::CKeyboardLayout::Load(), CDisplaySettings::Load(), CSkinSettings::Load(), CViewStateSettings::Load(), OVERLAY::COverlayImageDX::Load(), CVideoTagLoaderNFO::Load(), KODI::GAME::CGameClientInGameSaves::Load(), CFileItemList::Load(), PERIPHERALS::CAddonButtonMap::Load(), CColorManager::Load3dLut(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), ADDON::CAddonMgr::LoadAddon(), KODI::PLAYLIST::CPlayListASX::LoadAsxIniInfo(), CLinuxRendererGL::LoadCLUT(), CGUIDialogColorPicker::LoadColors(), CGUIColorManager::LoadColorsListFromXML(), CPlayerCoreFactory::LoadConfiguration(), CXRandR::LoadCustomModeLinesToAllOutputs(), CApplicationSkinHandling::LoadCustomWindows(), KODI::PLAYLIST::CPlayListASX::LoadData(), KODI::PLAYLIST::CPlayListB4S::LoadData(), KODI::PLAYLIST::CPlayListRAM::LoadData(), KODI::PLAYLIST::CPlayListWPL::LoadData(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::LoadDefaultCursor(), DllLoaderContainer::LoadDll(), CSectionLoader::LoadDLL(), CPODocument::LoadFile(), PVR::CPVRChannelGroup::LoadFromDatabase(), anonymous_namespace{FavouritesService.cpp}::LoadFromFile(), CTexture::LoadFromFileInternal(), CWakeOnAccess::LoadFromXML(), KODI::GAME::CGameClient::LoadGameInfo(), ADDON::CSkinInfo::LoadIncludes(), KODI::KEYMAP::CIRTranslator::LoadIRMap(), KODI::KEYMAP::CButtonTranslator::LoadKeymap(), KODI::GAME::CController::LoadLayout(), CWeatherJob::LoadLocalizedToken(), ADDON::LoadManifest(), DllLoaderContainer::LoadModule(), CFileItem::LoadMusicTag(), CDVDTeletextData::LoadPage(), CGUIWindowPictures::LoadPlayList(), LoadPO(), CProfileManager::LoadProfile(), KODI::RETRO::CReversiblePlayback::LoadSavestate(), ADDON::CAddon::LoadSettings(), CLinuxRendererGL::LoadShaders(), CLinuxRendererGLES::LoadShaders(), CRendererMediaCodec::LoadShadersHook(), CRendererVDPAU::LoadShadersHook(), CRendererVTB::LoadShadersHook(), CApplicationSkinHandling::LoadSkin(), Shaders::CShader::LoadSource(), CMediaManager::LoadSources(), VDPAU::CVDPAUContext::LoadSymbols(), LoadTexture(), CDXTexture::LoadToGPU(), CGLTexture::LoadToGPU(), GUIFontManager::LoadTTF(), ADDON::CAddon::LoadUserSettings(), KODI::RETRO::CRPRenderManager::LoadVideoFrameSync(), KODI::GAME::CPortManager::LoadXML(), CGUIWindow::LoadXML(), CGUIColorManager::LoadXML(), localGetNetworkResources(), CDatabaseManager::LocalizationChanged(), KODI::WINDOWING::GBM::CGBMUtils::CGBMDevice::CGBMSurface::LockFrontBuffer(), XBMCAddon::xbmc::log(), Log(), CDBusError::Log(), Log(), CEGLUtils::Log(), Log(), KODI::GAME::CGameClient::LogAddonProperties(), KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::LogAtomicDiff(), KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::LogAtomicRequest(), KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::LogAtomicRequest(), CRegExp::LogCheckUtf8Support(), anonymous_namespace{PVRClients.cpp}::LogClientWarning(), CAndroidUtils::LogDisplaySupportedHdrTypes(), PERIPHERALS::CPeripheralAddon::LogError(), KODI::GAME::CGameClient::LogError(), KODI::GAME::CGameClient::LogException(), KODI::GAME::CGUIDialogSelectGameClient::LogGameClients(), LogGraphicsInfo(), LogHandler(), CCharsetConverter::CInnerConverter::logicalToVisualBiDi(), KODI::UTILS::CDisplayInfo::LogInfo(), PERIPHERALS::CPeripheralBusAndroid::LogInputDevice(), KODI::GAME::CGameSettings::LoginToRA(), LogLevel(), CSpecialProtocol::LogPaths(), KODI::GAME::CAgentInput::LogPeripheralMap(), XbmcCommons::Exception::LogThrowMessage(), CDNSNameCache::Lookup(), PERIPHERALS::CPeripheralNyxboard::LookupSymAndUnicode(), ADDON::Interface_Filesystem::make_legal_filename(), ADDON::Interface_Filesystem::make_legal_path(), XBMCAddon::RetardedAsyncCallbackHandler::makePendingCalls(), ActiveAE::CActiveAE::MakeSound(), ActiveAE::CActiveAE::MakeStream(), VAAPI::CVaapi1Texture::Map(), VAAPI::CVaapi2Texture::Map(), CDRMPRIMETexture::Map(), CVideoLayerBridgeDRMPRIME::Map(), KODI::KEYMAP::CCustomControllerTranslator::MapActions(), PERIPHERALS::CAndroidJoystickState::MapAnalogStick(), PERIPHERALS::CAndroidJoystickState::MapButton(), PERIPHERALS::CAndroidJoystickState::MapDpad(), VDPAU::CVdpauTexture::MapNV12(), KODI::JOYSTICK::CButtonMapping::MapPrimitive(), KODI::GAME::CGUIConfigurationWizard::MapPrimitive(), KODI::GAME::CGUIDialogIgnoreInput::MapPrimitiveInternal(), KODI::KEYMAP::CIRTranslator::MapRemote(), VDPAU::CVdpauTexture::MapRGB(), PERIPHERALS::CAndroidJoystickState::MapTrigger(), ADDON::Interface_GUIWindow::mark_dirty_region(), ADDON::Interface_GUIDialogExtendedProgress::mark_finished(), VAAPI::CVideoSurfaces::MarkRender(), VDPAU::CVideoSurfaces::MarkRender(), XFILE::CMultiPathDirectory::MergeItems(), CEdl::MergeShortCommBreaks(), KODI::WINDOWING::X11::CWinEventsX11::MessagePump(), JSONRPC::CJSONRPC::MethodCall(), ADDON::CAddonMgr::MigrateAddons(), CMusicDatabase::MigrateSources(), CWinSystemWin10::Minimize(), CUDisks2Provider::Filesystem::Mount(), CUDiskDevice::Mount(), CDVDInputStreamBluray::MouseClick(), CDVDInputStreamBluray::MouseMove(), CPartyModeManager::MovePlaying(), CTeletextDecoder::MyFaceRequester(), dbiplus::MysqlDatabase::mysqlStrAccumAppend(), CNetworkBase::NetworkMessage(), ADDON::Interface_GUIDialogProgress::new_dialog(), ADDON::Interface_GUIDialogExtendedProgress::new_dialog(), ADDON::CScraper::NfoUrl(), not_implement(), NotifyAll(), KODI::WINDOWING::X11::CWinSystemX11::NotifyXRREvent(), CApplication::OnAction(), CGUIWindowManager::OnAction(), KODI::RETRO::CRetroPlayer::OnAction(), CVideoPlayer::OnAction(), KODI::JOYSTICK::CScalarFeature::OnAnalogMotion(), CWinSystemIOS::OnAppFocusChange(), CWinSystemTVOS::OnAppFocusChange(), CApplication::OnApplicationMessage(), CGUIWindowManager::OnApplicationMessage(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::OnAppLifecycleEvent(), CNetworkAndroid::onAvailable(), PERIPHERALS::CPeripheralJoystick::OnButtonMotion(), CGUIMediaWindow::OnClick(), CRendererBase::OnCMSConfigChanged(), Shaders::GL::ConvolutionFilterShader::OnCompiledAndLinked(), Shaders::GLES::ConvolutionFilterShader::OnCompiledAndLinked(), Shaders::GL::YUV2RGBFilterShader4::OnCompiledAndLinked(), Shaders::GLSLOutput::OnCompiledAndLinked(), KODI::GAME::CGUIAgentControllerList::OnControllerSelect(), CMMNotificationClient::OnDefaultDeviceChanged(), CGUIWindowSlideShow::OnDeinitWindow(), CMMNotificationClient::OnDeviceAdded(), CMMNotificationClient::OnDeviceRemoved(), CMMNotificationClient::OnDeviceStateChanged(), KODI::JOYSTICK::CScalarFeature::OnDigitalMotion(), KODI::JOYSTICK::CInputHandling::OnDigitalMotion(), CVideoPlayer::OnDiscNavResult(), CZeroconfBrowserAndroidDiscover::onDiscoveryStarted(), CZeroconfBrowserAndroidDiscover::onDiscoveryStopped(), CXBMCApp::onDisplayChanged(), CWinEventsWin10::OnDisplayContentsInvalidated(), CWinSystemWin10::OnDisplayLost(), CWinSystemWin10::OnDisplayReset(), CGUIDialogSubtitles::OnDownloadComplete(), CPartyModeManager::OnError(), CContextMenuManager::OnEvent(), CPythonInvoker::onExecutionDone(), XBPython::OnExecutionEnded(), CPythonInvoker::onExecutionFailed(), VAAPI::COutput::OnExit(), VDPAU::CMixer::OnExit(), VDPAU::COutput::OnExit(), CVideoPlayer::OnExit(), CVideoPlayerAudio::OnExit(), CVideoPlayerAudioID3::OnExit(), CDVDRadioRDSData::OnExit(), CDVDTeletextData::OnExit(), CVideoPlayerVideo::OnExit(), KODI::PIPEWIRE::CPipewireRegistry::OnGlobalRemoved(), PERIPHERALS::CPeripheralJoystick::OnHatMotion(), CPythonInvoker::onInitialization(), CGUIDialogColorPicker::OnInitWindow(), CGUIDialogTeletext::OnInitWindow(), PERIPHERALS::CPeripheralBusAndroid::OnInputDeviceAdded(), PERIPHERALS::CPeripheralBusAndroid::OnInputDeviceChanged(), PERIPHERALS::CPeripheralBusAndroid::OnInputDeviceEvent(), PERIPHERALS::CPeripheralBusAndroid::OnInputDeviceRemoved(), CJobManager::OnJobComplete(), ADDON::CRepositoryUpdater::OnJobComplete(), CWakeOnAccess::OnJobComplete(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::OnKeyboardKey(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::OnKeyboardKeymap(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::OnKeyboardModifiers(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::OnKeyboardRepeatInfo(), KODI::GAME::CGameClientKeyboard::OnKeyPress(), CGUIWindowSlideShow::OnLoadPic(), CNetworkAndroid::onLost(), KODI::WINDOWING::GBM::CWinSystemGbm::OnLostDevice(), KODI::WINDOWING::X11::CWinSystemX11::OnLostDevice(), ActiveAE::CActiveAE::OnLostDisplay(), VDPAU::CDecoder::OnLostDisplay(), CVideoPlayer::OnLostDisplay(), CPowerManager::OnLowBattery(), CDVDInputStreamBluray::OnMenu(), CGUIControl::OnMessage(), CGUIDialogAddonSettings::OnMessage(), CGUIWindow::OnMessage(), XBMCAddon::xbmcgui::WindowDialog::OnMessage(), XBMCAddon::xbmcgui::WindowXML::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindow::OnMove(), CXBMCApp::onNewIntent(), KODI::GAME::CDialogInGameSaves::OnOverwrite(), EVENTCLIENT::CEventClient::OnPacketACTION(), EVENTCLIENT::CEventClient::OnPacketBUTTON(), EVENTCLIENT::CEventClient::OnPacketHELO(), EVENTCLIENT::CEventClient::OnPacketLOG(), EVENTCLIENT::CEventClient::OnPacketNOTIFICATION(), CXBMCApp::OnPlayBackPaused(), CXBMCApp::OnPlayBackStarted(), CXBMCApp::OnPlayBackStopped(), CGUIWindowVideoBase::OnPlayMedia(), CGUIMediaWindow::OnPlayMedia(), ADDON::CAddonDatabase::OnPostUnInstall(), KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(), CMMNotificationClient::OnPropertyValueChanged(), CPythonInvoker::onPythonModuleInitialization(), CContextItemAddonInvoker::onPythonModuleInitialization(), CXBMCApp::onReceive(), KODI::GAME::CGameClientHardware::OnResetButton(), VDPAU::CDecoder::OnResetDisplay(), CVideoPlayer::OnResetDisplay(), CWinEventsWin10::OnResize(), CZeroconfBrowserAndroidResolve::onResolveFailed(), XBPython::OnScriptFinalized(), XBPython::OnScriptInitialized(), CGUIDialogSubtitles::OnSearchComplete(), CZeroconfBrowserAndroidDiscover::onServiceFound(), CZeroconfBrowserAndroidDiscover::onServiceLost(), CZeroconfBrowserAndroidResolve::onServiceResolved(), CGUIDialogInfoProviderSettings::OnSettingAction(), CGUIDialogContentSettings::OnSettingAction(), CGUIDialogVideoSettings::OnSettingAction(), PVR::CPVRChannelGroup::OnSettingChanged(), CStereoscopicsManager::OnSettingChanged(), CLangInfo::OnSettingChanged(), CDiscSettings::OnSettingChanged(), CAdvancedSettings::OnSettingsLoaded(), CXBMCApp::OnSleep(), CPowerManager::OnSleep(), CZeroconfBrowserAndroidDiscover::onStartDiscoveryFailed(), VAAPI::COutput::OnStartup(), VDPAU::CMixer::OnStartup(), VDPAU::COutput::OnStartup(), CZeroconfBrowserAndroidDiscover::onStopDiscoveryFailed(), CMediaManager::OnStorageAdded(), CGUIDialogSubtitles::OnSubtitleServiceContextMenu(), ADDON::CRepositoryUpdater::OnTimeout(), CWinEventsWin10::OnVisibilityChanged(), CXBMCApp::onVisibleBehindCanceled(), CPowerManager::OnWake(), CXBMCApp::OnWakeup(), CWinEventsWin10::OnWindowActivationChanged(), CWinEventsWin10::OnWindowResizeCompleted(), CWinEventsWin10::OnWindowResizeStarted(), KODI::UTILS::POSIX::CSharedMemory::Open(), CDVDInputStreamBluray::Open(), CDVDInputStreamNavigator::Open(), CDVDInputStreamStack::Open(), CInputStreamAddon::Open(), CInputStreamMultiSource::Open(), XFILE::CSimpleFileCache::Open(), CCoreAudioStream::Open(), DXVA::CDecoder::Open(), VAAPI::CDecoder::Open(), VDPAU::CDecoder::Open(), CDVDSubtitleParserMicroDVD::Open(), CDVDAudioCodecAndroidMediaCodec::Open(), CDVDAudioCodecFFmpeg::Open(), CDVDAudioCodecPassthrough::Open(), CDVDOverlayCodecFFmpeg::Open(), CDVDVideoCodecAndroidMediaCodec::Open(), CDVDVideoCodecDRMPRIME::Open(), CDVDVideoCodecFFmpeg::Open(), XFILE::CFile::Open(), XFILE::CFileCDDA::Open(), XFILE::CCurlFile::Open(), XFILE::CFileCache::Open(), XFILE::CNFSFile::Open(), XFILE::CZipFile::Open(), XFILE::CAPKFile::Open(), XFILE::CSMBFile::Open(), CDVDDemuxFFmpeg::Open(), CGUIDialogProgress::Open(), CDVDSubtitleStream::Open(), CBitstreamConverter::Open(), ADDON::Interface_GUIDialogContextMenu::open(), ADDON::Interface_GUIDialogSelect::open(), ADDON::Interface_GUIDialogTextViewer::open(), ADDON::Interface_GUIDialogProgress::open(), ADDON::Interface_Filesystem::open_file(), ADDON::Interface_Filesystem::open_file_for_write(), ADDON::Interface_GUIDialogSelect::open_multi_select(), open_restricted(), ADDON::Interface_Base::open_settings_dialog(), CTextureBundleXBT::OpenBundle(), CVideoPlayer::OpenDemuxStream(), XFILE::CSMBDirectory::OpenDir(), KODI::WINDOWING::GBM::CDRMUtils::OpenDrm(), CExternalPlayer::OpenFile(), KODI::RETRO::CRetroPlayer::OpenFile(), CVideoPlayer::OpenFile(), KODI::GAME::CGameClient::OpenFile(), XFILE::CFile::OpenForWrite(), XFILE::CCurlFile::OpenForWrite(), XFILE::CNFSFile::OpenForWrite(), XFILE::CSMBFile::OpenForWrite(), CVideoPlayer::OpenInputStream(), KODI::GAME::CGameClientInput::OpenJoystick(), KODI::GAME::CGameClientInput::OpenKeyboard(), KODI::GAME::CGameClientInput::OpenMouse(), CInputStreamPVRChannel::OpenPVRStream(), CInputStreamPVRRecording::OpenPVRStream(), DRM::CMediaDrmCryptoSession::OpenSession(), ActiveAE::CActiveAESink::OpenSink(), CDDB::Xcddb::openSocket(), KODI::GAME::CGameClient::OpenStandalone(), CVideoPlayer::OpenStream(), CVideoPlayerVideo::OpenStream(), CVideoPlayerSubtitle::OpenStream(), CVideoPlayerVideo::OpenStream(), CVideoPlayerAudio::OpenStream(), CVideoPlayerAudioID3::OpenStream(), CDVDRadioRDSData::OpenStream(), CDVDTeletextData::OpenStream(), CDVDInputStreamBluray::OpenStream(), KODI::GAME::CGameClientStreams::OpenStream(), KODI::RETRO::CRetroPlayerAudio::OpenStream(), KODI::RETRO::CRetroPlayerVideo::OpenStream(), KODI::GAME::CGameClientStreamAudio::OpenStream(), KODI::GAME::CGameClientStreamVideo::OpenStream(), CRegExp::operator=(), KODI::PLAYLIST::CPlayList::operator[](), KODI::PLAYLIST::CPlayList::operator[](), CPicture::OrientateImage(), CVideoPlayerVideo::OutputPicture(), ActiveAE::CActiveAESink::OutputSamples(), CDVDInputStreamBluray::OverlayCallback(), Win32DllLoader::OverrideImports(), CAEBitstreamPacker::Pack(), CAEBitstreamPacker::PackPause(), CPackerMAT::PackTrueHD(), JSONRPC::JsonRpcMethod::Parse(), JSONRPC::JSONSchemaTypeDefinition::Parse(), CXBMCTinyXML::Parse(), INFO::InfoExpression::Parse(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::Parse(), CScraperParser::Parse(), CCueDocument::Parse(), XFILE::CCurlFile::ParseAndCorrectUrl(), WSDiscovery::CWSDiscoveryListenerUDP::ParseBuffer(), ADDON::CRepository::ParseDirConfiguration(), CPODocument::ParseEntry(), JSONRPC::CJSONServiceDescription::parseJSONSchemaType(), CScraperParser::ParseNext(), CPODocument::ParseNumID(), CDVDDemuxFFmpeg::ParsePacket(), CDVDDemuxClient::ParsePacket(), CDVDDemuxSPU::ParseRLE(), CAdvancedSettings::ParseSettingsFile(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CWebVTTISOHandler::ParseVTTCueBox(), ADDON::CAddonInfoBuilder::ParseXML(), ADDON::CAddonInfoBuilder::ParseXMLTypes(), CScraperParser::ParseXSLT(), CAESinkSNDIO::ParToAudioFormat(), CAudioSinkAE::Pause(), CRenderCaptureGL::PboToBuffer(), PERIPHERALS::CPeripheralBusUSB::PerformDeviceScan(), CNetworkWin32::PingHost(), CNetworkMacOS::PingHost(), CNetworkFreebsd::PingHost(), CNetworkLinux::PingHost(), CNetworkBase::PingHost(), CNetworkAndroid::PingHost(), CWIN32Util::PlatformSyslog(), CPlatformAndroid::PlatformSyslog(), KODI::PLAYLIST::CPlayListPlayer::Play(), CPartyModeManager::Play(), PVR::CPVRGUIActionsPlayback::PlayChannelOnStartup(), PlayerControl(), CApplication::PlayMedia(), PlayOffset(), CMediaManager::playStubFile(), CGUIWindowSlideShow::PlayVideo(), CDVDInputStreamNavigator::PosTime(), CCocoaPowerSyscall::Powerdown(), CWin32PowerStateWorker::PowerManagement(), VDPAU::COutput::PreCleanup(), CRenderManager::PreInit(), VAAPI::CVppPostproc::PreInit(), VAAPI::CFFmpegPostproc::PreInit(), CVideoPlayer::Prepare(), JSONRPC::CJSONServiceDescription::prepareDescription(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::PrepareFramePresentation(), CRenderManager::PrepareNextRender(), PAPlayer::PrepareStream(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender(), CGUIWindowManager::PreviousWindow(), MEDIA_DETECT::CCdIoSupport::PrintAnalysis(), KODI::WINDOWING::GBM::CDRMUtils::PrintDrmDeviceInfo(), KODI::RETRO::CRetroPlayer::PrintGameInfo(), PrintMatrix(), ActiveAE::CActiveAESink::PrintSinks(), CApplication::PrintStartupLog(), CResolutionUtils::PrintWhitelist(), WSDiscovery::CWSDiscoveryListenerUDP::PrintWSDInfo(), CRegExp::PrivateRegFind(), CColorManager::Probe3dLut(), CAndroidUtils::ProbeResolutions(), MUSIC_INFO::CMusicInfoScanner::Process(), CZeroconfMDNS::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), CExternalPlayer::Process(), PAPlayer::Process(), KODI::RETRO::CRetroPlayerAutoSave::Process(), CVideoPlayer::Process(), CVideoPlayerAudio::Process(), CVideoPlayerAudioID3::Process(), CDVDRadioRDSData::Process(), CDVDTeletextData::Process(), CVideoPlayerVideo::Process(), CVideoReferenceClock::Process(), CGUIDialogCache::Process(), XFILE::CFileCache::Process(), KODI::GAME::CControllerInstaller::Process(), KODI::GAME::CControllerSelect::Process(), KODI::GAME::CGUIConfigurationWizard::Process(), MUSIC_GRABBER::CMusicInfoScraper::Process(), CAirPlayServer::Process(), JSONRPC::CTCPServer::Process(), CUdpClient::Process(), CBackgroundPicLoader::Process(), CFDEventMonitor::Process(), CLibInputHandler::Process(), WSDiscovery::CWSDiscoveryListenerUDP::Process(), PVR::CPVREpgContainer::Process(), PVR::CPVRManager::Process(), CJobWorker::Process(), CRssReader::Process(), CVideoInfoDownloader::Process(), CWinEventsAndroid::Process(), anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::Process(), CDVDVideoCodecFFmpeg::CDropControl::Process(), CGUIWindowSlideShow::Process(), CDVDVideoPPFFmpeg::Process(), PERIPHERALS::CPeripheralBusUSB::Process(), CApplication::ProcessAndStartPlaylist(), CLibInputPointer::ProcessAxis(), CDVDInputStreamNavigator::ProcessBlock(), CLibInputPointer::ProcessButton(), CLirc::ProcessCode(), CVideoPlayerVideo::ProcessDecoderOutput(), CVideoPlayerAudio::ProcessDecoderOutput(), CDVDInputStreamBluray::ProcessEvent(), PERIPHERALS::CAndroidJoystickState::ProcessEvent(), CInputManager::ProcessEventServer(), ActiveAE::CActiveAEFilter::ProcessFilter(), KODI::VIDEO::CVideoInfoScanner::ProcessItemByVideoInfoTag(), CLibInputKeyboard::ProcessKey(), KODI::JOYSTICK::CAxisDetector::ProcessMotion(), CLibInputPointer::ProcessMotion(), CLibInputPointer::ProcessMotionAbsolute(), KODI::JOYSTICK::CAxisFeature::ProcessMotions(), KODI::JOYSTICK::CAnalogStick::ProcessMotions(), EVENTCLIENT::CEventClient::ProcessPacket(), EVENTSERVER::CEventServer::ProcessPacket(), VAAPI::COutput::ProcessPicture(), CAirPlayServer::CTCPClient::ProcessRequest(), CZeroconfBrowserMDNS::ProcessResults(), CZeroconfMDNS::ProcessResults(), CApplication::ProcessSlow(), PAPlayer::ProcessStream(), PAPlayer::ProcessStreams(), VAAPI::CVaapiBufferPool::ProcessSyncPicture(), VDPAU::CVdpauBufferPool::ProcessSyncPicture(), CLibInputTouch::ProcessTouchCancel(), CLibInputTouch::ProcessTouchDown(), CLibInputTouch::ProcessTouchFrame(), CLibInputTouch::ProcessTouchMotion(), CLibInputTouch::ProcessTouchUp(), CDVDRadioRDSData::ProcessUECP(), DRM::CMediaDrmCryptoSession::ProvideKeyResponse(), DRM::CMediaDrmCryptoSession::ProvisionRequest(), CUDevProvider::PumpDriveChangeEvents(), CUDisks2Provider::PumpDriveChangeEvents(), CAndroidPowerSyscall::PumpPowerEvents(), CTVOSPowerSyscall::PumpPowerEvents(), CLogindUPowerSyscall::PumpPowerEvents(), CUPowerSyscall::PumpPowerEvents(), JSONRPC::CTCPServer::CWebSocketClient::PushBuffer(), CDVDMessageQueue::Put(), CXRandR::Query(), dbiplus::MysqlDataset::query(), dbiplus::MysqlDatabase::query_with_reconnect(), DXVA::CContext::QueryCaps(), VAAPI::CVAAPIContext::QueryCaps(), CDDB::Xcddb::queryCDinfo(), CDDB::Xcddb::queryCDinfo(), CGLContextEGL::QueryExtensions(), KODI::WINDOWING::X11::CGLContextGLX::QueryExtensions(), CNetworkWin32::queryInterfaceList(), ADDON::Interface_General::queue_notification(), PAPlayer::QueueData(), KODI::WINDOWING::GBM::CDRMLegacy::QueueFlip(), CWakeOnAccess::QueueMACDiscoveryForHost(), PAPlayer::QueueNextFileEx(), VAAPI::CVaapiBufferPool::QueueReturnPicture(), VDPAU::CVdpauBufferPool::QueueReturnPicture(), CXBMCApp::Quit(), CDemuxMultiSource::Read(), CDVDInputStreamNavigator::Read(), CDVDInputStreamStack::Read(), AERingBuffer::Read(), XFILE::CFile::Read(), XFILE::CCurlFile::CReadState::Read(), XFILE::CFileCDDA::Read(), XFILE::CFileCache::Read(), XFILE::CNFSFile::Read(), XFILE::CSMBFile::Read(), ADDON::Interface_Filesystem::read_file(), ADDON::Interface_Filesystem::read_file_string(), CEdl::ReadBeyondTV(), CEdl::ReadComskip(), CEdl::ReadEditDecisionLists(), CEdl::ReadEdl(), XFILE::CSimpleFileCache::ReadFromCache(), XFILE::CFileAndroidApp::ReadIcon(), CDVDDemuxFFmpeg::ReadInternal(), KODI::PLAYLIST::CSmartPlaylist::readName(), KODI::PLAYLIST::CSmartPlaylist::readNameFromPath(), KODI::PLAYLIST::CSmartPlaylist::readNameFromXml(), CCharArrayParser::ReadNextArray(), CCharArrayParser::ReadNextLine(), CCharArrayParser::ReadNextString(), CCharArrayParser::ReadNextUnsignedChar(), CCharArrayParser::ReadNextUnsignedInt(), CCharArrayParser::ReadNextUnsignedShort(), CRenderCaptureDX::ReadOut(), CVideoPlayer::ReadPacket(), CEdl::ReadPvr(), CAudioDecoder::ReadSamples(), XFILE::CCurlFile::CReadState::ReadString(), XFILE::CFile::ReadString(), XFILE::CFile::ReadString(), CEdl::ReadVideoReDo(), CGUIFontTTFGL::ReallocTexture(), CGUIFontTTFGLES::ReallocTexture(), CCocoaPowerSyscall::Reboot(), CDVDVideoCodecAndroidMediaCodec::Reconfigure(), KODI::WINDOWING::X11::CWinSystemX11::RecreateWindow(), CDDB::Xcddb::Recv(), CGLContextEGL::Refresh(), KODI::WINDOWING::X11::CGLContextGLX::Refresh(), EVENTSERVER::CEventServer::RefreshClients(), CRegExp::RegComp(), CDVDVideoCodecDRMPRIME::Register(), VDPAU::CDecoder::Register(), CDMAHeapBufferObject::Register(), CUDMABufferObject::Register(), CAESinkPULSE::Register(), PERIPHERALS::CPeripheralBus::Register(), VAAPI::CDecoder::Register(), PERIPHERALS::CPeripheralAddon::Register(), CRendererVAAPIGL::Register(), CRendererVAAPIGLES::Register(), CZeroconfDarwin::registerCallback(), CZeroconfMDNS::registerCallback(), CCoreAudioDevice::RegisterDefaultOutputDeviceChangedCB(), CCoreAudioDevice::RegisterDeviceChangedCB(), PERIPHERALS::CPeripheral::RegisterInputHandler(), PERIPHERALS::CPeripheral::RegisterKeyboardHandler(), PERIPHERALS::CEventScanner::RegisterLock(), PERIPHERALS::CPeripheral::RegisterMouseHandler(), PERIPHERALS::CEventScanner::RegisterPollHandle(), KODI::RETRO::CRPProcessInfo::RegisterRendererFactory(), CFavouritesService::ReInit(), XBMCAddon::AddonClass::Release(), VAAPI::CDecoder::Release(), VDPAU::CDecoder::Release(), PERIPHERALS::CEventScanner::Release(), ADDON::CBinaryAddonBase::ReleaseAddon(), CLogindUPowerSyscall::ReleaseDelayLock(), PERIPHERALS::CEventScanner::ReleaseLock(), CDMAHeapBufferObject::ReleaseMemory(), CDumbBufferObject::ReleaseMemory(), CUDMABufferObject::ReleaseMemory(), DllLoaderContainer::ReleaseModule(), CMediaCodecVideoBuffer::ReleaseOutputBuffer(), KODI::RETRO::CWinRenderBuffer::ReleaseTexture(), CGUITextureManager::ReleaseTexture(), CContextMenuManager::ReloadAddonItems(), CApplicationSkinHandling::ReloadSkin(), GUIFontManager::ReloadTTFFonts(), ActiveAE::CActiveAEStream::RemapBuffer(), XFILE::CDirectory::Remove(), XFILE::CDAVDirectory::Remove(), XFILE::CNFSDirectory::Remove(), XFILE::CSMBDirectory::Remove(), CGUIWindowManager::Remove(), WSDiscovery::CClientNotificationSink::Remove(), ADDON::Interface_Filesystem::remove_directory(), ADDON::Interface_Filesystem::remove_directory_recursive(), ADDON::Interface_GUIWindow::remove_list_item(), ADDON::Interface_GUIWindow::remove_list_item_from_position(), CVideoDatabase::RemoveContentForPath(), KODI::PIPEWIRE::CPipewireProxy::Removed(), CFileItemList::RemoveDiscCache(), CFDEventMonitor::RemoveFD(), CFDEventMonitor::RemoveFDs(), KODI::WINDOWING::COSScreenSaverManager::RemoveInhibitor(), CCoreAudioDevice::RemoveIOProc(), DRM::CMediaDrmCryptoSession::RemoveKeys(), CCoreAudioDevice::RemoveObjectListenerProc(), ADDON::CAddonInstaller::RemoveOrphanedDepsRecursively(), XFILE::CDirectory::RemoveRecursive(), XFILE::CWin32Directory::RemoveRecursive(), CMusicDatabase::RemoveSongsFromPath(), ADDON::CAddonDatabase::RemoveUpdateRuleForAddon(), XFILE::CFile::Rename(), XFILE::CDAVFile::Rename(), XFILE::CNFSFile::Rename(), XFILE::CSMBFile::Rename(), ADDON::Interface_Filesystem::rename_file(), CFileUtils::RenameFile(), CGUIDialogTeletext::Render(), VDPAU::CDecoder::Render(), CTeletextDecoder::RenderCharIntern(), CLinuxRendererGL::RenderFromFBO(), CDVDSubtitlesLibass::RenderImage(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGLES::RenderToFBO(), CLinuxRendererGL::RenderToFBO(), CMediaCodecVideoBuffer::RenderUpdate(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::ReplaceSpecialKeywordReferences(), CApplicationPlayerCallback::RequestVideoSettings(), CXBMCApp::RequestVisibleBehind(), ActiveAE::CActiveAEResampleFFMPEG::Resample(), AERingBuffer::Reset(), CPosixResourceCounter::Reset(), CSettings::Reset(), CDVDAudioCodecAndroidMediaCodec::Reset(), CAddonVideoCodec::Reset(), CDVDVideoCodecAndroidMediaCodec::Reset(), CDVDVideoCodecDRMPRIME::Reset(), VAAPI::CDecoder::Reset(), VDPAU::CDecoder::Reset(), XFILE::CDoubleCache::Reset(), ADDON::Interface_GUIControlFadeLabel::reset(), ADDON::Interface_GUIControlSettingsSlider::reset(), ADDON::Interface_GUIControlSlider::reset(), ADDON::Interface_GUIControlSpin::reset(), ADDON::Interface_GUIControlTextBox::reset(), CCoreAudioHardware::ResetAudioDevices(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), CRenderSystemGL::ResetGLErrors(), CRenderSystemGL::ResetRenderSystem(), CCoreAudioHardware::ResetStream(), CZeroconfBrowserAvahi::resolveCallback(), CZeroconfBrowserMDNS::ResolveCallback(), Win32DllLoader::ResolveExport(), SoLoader::ResolveExport(), ADDON::CScraper::ResolveIDToUrl(), MUSIC_INFO::CMusicInfoScanner::ResolveMusicBrainz(), LibraryLoader::ResolveOrdinal(), CCueDocument::ResolvePath(), ADDON::CRepository::ResolvePathAndHash(), CZeroconfBrowser::ResolveService(), XFILE::CNFSDirectory::ResolveSymlink(), CWinSystemWin10::Restore(), CWinSystemWin10::RestoreDesktopResolution(), DRM::CMediaDrmCryptoSession::RestoreKeys(), KODI::WINDOWING::GBM::CDRMUtils::RestoreOriginalMode(), CPowerManager::RestorePlayerState(), CDatabase::ResultQuery(), CAudioSinkAE::Resume(), ActiveAE::CActiveAE::Resume(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), CNetworkAndroid::RetrieveInterfaces(), CGUIWindowMusicBase::RetrieveMusicInfo(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), KODI::CDRIP::CCDDARipper::RipCD(), KODI::CDRIP::CCDDARipper::RipTrack(), CDatabase::RollbackTransaction(), CApplication::Run(), EVENTSERVER::CEventServer::Run(), CBackgroundInfoLoader::Run(), CVideoSyncGbm::Run(), KODI::WINDOWING::X11::CVideoSyncGLX::Run(), ADDON::CScraper::Run(), RunAddon(), RunPlugin(), CVideoDatabase::RunQuery(), RunScript(), XFILE::CPluginDirectory::RunScriptWithParams(), ActiveAE::CActiveAE::RunStages(), CGUIDialogInfoProviderSettings::Save(), PVR::CGUIDialogPVRTimerSettings::Save(), CGUIDialogLibExportSettings::Save(), CGUIDialogCMSSettings::Save(), KODI::PLAYLIST::CPlayListB4S::Save(), KODI::PLAYLIST::CPlayListM3U::Save(), KODI::PLAYLIST::CPlayListPLS::Save(), KODI::PLAYLIST::CPlayListWPL::Save(), KODI::PLAYLIST::CPlayListXML::Save(), KODI::GAME::CGameClientInGameSaves::Save(), CFileItemList::Save(), CViewStateSettings::Save(), CWakeOnAccess::SaveMACDiscoveryResult(), CDVDTeletextData::SavePage(), CGUIWindowMusicPlayList::SavePlayList(), CGUIWindowVideoPlaylist::SavePlayList(), KODI::RETRO::CRPRenderManager::SaveThumbnail(), KODI::RETRO::CRPRenderManager::SaveVideoFrame(), CUtil::ScanArchiveForAssociatedItems(), CUtil::ScanForExternalSubtitles(), CUtil::ScanPathsForAssociatedItems(), MUSIC_INFO::CMusicInfoScanner::ScanTags(), ADDON::CRepositoryUpdater::ScheduleUpdate(), CMusicDatabase::ScraperInUse(), CVideoDatabase::ScraperInUse(), anonymous_namespace{GUIBuiltins.cpp}::Screenshot(), ADDON::Interface_GUIControlTextBox::scroll(), ADDON::CAddonDatabase::Search(), CMusicDatabase::Search(), CMusicDatabase::SearchAlbums(), CMusicDatabase::SearchAlbumsByArtistName(), PVR::CPVRGUIChannelIconUpdater::SearchAndUpdateMissingChannelIcons(), CMusicDatabase::SearchArtists(), WSDiscovery::CClientNotificationSink::SearchComplete(), WSDiscovery::CClientNotificationSink::SearchFailed(), CMusicDatabase::SearchSongs(), XFILE::CSimpleFileCache::Seek(), XFILE::CFileCache::Seek(), XFILE::CFile::Seek(), XFILE::CNFSFile::Seek(), XFILE::CSMBFile::Seek(), CDVDInputStreamBluray::Seek(), XFILE::CCurlFile::CReadState::Seek(), XFILE::CCircularCache::Seek(), ADDON::Interface_Filesystem::seek_file(), CDVDDemuxFFmpeg::SeekChapter(), CDVDInputStreamNavigator::SeekChapter(), SeekPercentage(), CDemuxMultiSource::SeekTime(), CDVDDemuxFFmpeg::SeekTime(), ADDON::Interface_GUIListItem::select(), CDirtyRegionTracker::SelectAlgorithm(), CAESinkALSA::SelectALSAChannelMap(), CWebSocket::Send(), ADDON::Interface_GUIDialogKeyboard::send_text_to_active_keyboard(), CVideoPlayerSubtitle::SendMessage(), CSettingsValueXmlSerializer::SerializeSetting(), CSettingsValueFlatJsonSerializer::SerializeSettingValue(), CSettingsValueFlatJsonSerializer::SerializeValues(), XbmcThreads::EndTime< T, true >::Set(), ADDON::Interface_GUIListItem::set_art(), ADDON::Interface_GUIControlTextBox::set_auto_scrolling(), ADDON::Interface_GUIControlAddonRendering::set_callbacks(), ADDON::Interface_GUIWindow::set_callbacks(), ADDON::Interface_GUIDialogProgress::set_can_cancel(), ADDON::Interface_GUIControlImage::set_color_diffuse(), ADDON::Interface_GUIWindow::set_container_content(), ADDON::Interface_GUIWindow::set_container_property(), ADDON::Interface_GUIWindow::set_control_label(), ADDON::Interface_GUIWindow::set_control_selected(), ADDON::Interface_GUIWindow::set_control_visible(), ADDON::Interface_GUIWindow::set_current_list_position(), ADDON::Interface_GUIControlEdit::set_cursor_position(), ADDON::Interface_GUIControlButton::set_enabled(), ADDON::Interface_GUIControlEdit::set_enabled(), ADDON::Interface_GUIControlRadioButton::set_enabled(), ADDON::Interface_GUIControlSettingsSlider::set_enabled(), ADDON::Interface_GUIControlSlider::set_enabled(), ADDON::Interface_GUIControlSpin::set_enabled(), ADDON::Interface_GUIControlImage::set_filename(), ADDON::Interface_GUIControlSettingsSlider::set_float_interval(), ADDON::Interface_GUIControlSlider::set_float_interval(), ADDON::Interface_GUIControlSpin::set_float_interval(), ADDON::Interface_GUIControlSettingsSlider::set_float_range(), ADDON::Interface_GUIControlSlider::set_float_range(), ADDON::Interface_GUIControlSpin::set_float_range(), ADDON::Interface_GUIControlSettingsSlider::set_float_value(), ADDON::Interface_GUIControlSlider::set_float_value(), ADDON::Interface_GUIControlSpin::set_float_value(), ADDON::Interface_GUIWindow::set_focus_id(), ADDON::Interface_GUIDialogProgress::set_heading(), ADDON::Interface_GUIControlEdit::set_input_type(), ADDON::IAddonInstanceHandler::set_instance_setting_bool(), ADDON::IAddonInstanceHandler::set_instance_setting_float(), ADDON::IAddonInstanceHandler::set_instance_setting_int(), ADDON::IAddonInstanceHandler::set_instance_setting_string(), ADDON::Interface_GUIControlSettingsSlider::set_int_interval(), ADDON::Interface_GUIControlSlider::set_int_interval(), ADDON::Interface_GUIControlSettingsSlider::set_int_range(), ADDON::Interface_GUIControlSlider::set_int_range(), ADDON::Interface_GUIControlSpin::set_int_range(), ADDON::Interface_GUIControlSettingsSlider::set_int_value(), ADDON::Interface_GUIControlSlider::set_int_value(), ADDON::Interface_GUIControlSpin::set_int_value(), ADDON::Interface_GUIControlButton::set_label(), ADDON::Interface_GUIControlEdit::set_label(), ADDON::Interface_GUIControlLabel::set_label(), ADDON::Interface_GUIControlRadioButton::set_label(), ADDON::Interface_GUIListItem::set_label(), ADDON::Interface_GUIControlButton::set_label2(), ADDON::Interface_GUIListItem::set_label2(), ADDON::Interface_GUIDialogProgress::set_line(), ADDON::Interface_GUIListItem::set_path(), ADDON::Interface_GUIControlProgress::set_percentage(), ADDON::Interface_GUIControlSettingsSlider::set_percentage(), ADDON::Interface_GUIControlSlider::set_percentage(), ADDON::Interface_GUIDialogExtendedProgress::set_percentage(), ADDON::Interface_GUIDialogProgress::set_percentage(), ADDON::Interface_GUIDialogExtendedProgress::set_progress(), ADDON::Interface_GUIDialogProgress::set_progress_advance(), ADDON::Interface_GUIDialogProgress::set_progress_max(), ADDON::Interface_GUIListItem::set_property(), ADDON::Interface_GUIWindow::set_property(), ADDON::Interface_GUIWindow::set_property_bool(), ADDON::Interface_GUIWindow::set_property_double(), ADDON::Interface_GUIWindow::set_property_int(), ADDON::Interface_GUIControlFadeLabel::set_scrolling(), ADDON::Interface_GUIControlRadioButton::set_selected(), ADDON::Interface_Base::set_setting_bool(), ADDON::Interface_Base::set_setting_float(), ADDON::Interface_Base::set_setting_int(), ADDON::Interface_Base::set_setting_string(), ADDON::Interface_GUIControlSpin::set_string_value(), ADDON::Interface_GUIControlEdit::set_text(), ADDON::Interface_GUIControlSettingsSlider::set_text(), ADDON::Interface_GUIControlSpin::set_text(), ADDON::Interface_GUIControlTextBox::set_text(), ADDON::Interface_GUIDialogExtendedProgress::set_text(), ADDON::Interface_GUIDialogExtendedProgress::set_title(), ADDON::Interface_GUIControlSpin::set_type(), ADDON::Interface_GUIControlButton::set_visible(), ADDON::Interface_GUIControlEdit::set_visible(), ADDON::Interface_GUIControlFadeLabel::set_visible(), ADDON::Interface_GUIControlImage::set_visible(), ADDON::Interface_GUIControlLabel::set_visible(), ADDON::Interface_GUIControlProgress::set_visible(), ADDON::Interface_GUIControlRadioButton::set_visible(), ADDON::Interface_GUIControlSettingsSlider::set_visible(), ADDON::Interface_GUIControlSlider::set_visible(), ADDON::Interface_GUIControlSpin::set_visible(), ADDON::Interface_GUIControlTextBox::set_visible(), KODI::WINDOWING::GBM::CDRMLegacy::SetActive(), CDVDInputStreamNavigator::SetActiveAudioStream(), CMusicDatabase::SetAlbumUserrating(), CVideoDatabase::SetArtForItem(), CMusicDatabase::SetArtForItem(), CSong::SetArtistCredits(), CAlbum::SetArtistCredits(), CCoreAudioHardware::SetAutoHogMode(), setAVAudioSessionProperties(), ADDON::CSkinInfo::SetBool(), CCoreAudioDevice::SetBufferSize(), CVideoPlayer::SetCaching(), XBMCAddon::xbmcgui::ListItem::setCast(), CDVDVideoCodecAndroidMediaCodec::SetCodecControl(), CAAudioUnitSink::setCoreAudioInputFormat(), CCoreAudioDevice::SetCurrentVolume(), CAdvancedSettings::SetDebugMode(), CPowerManager::SetDefaults(), CVideoDatabase::SetDefaultVideoVersion(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMovieSet(), CVideoDatabase::SetDetailsForMusicVideo(), CVideoDatabase::SetDetailsForSeason(), CVideoBufferDMA::SetDimensions(), CWakeOnAccess::SetEnabled(), CVideoDatabase::SetFileForEpisode(), CVideoDatabase::SetFileForMovie(), DX::DeviceResources::SetFullScreen(), KODI::WINDOWING::GBM::CWinSystemGbm::SetFullScreen(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::SetFullScreen(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::SetFullScreen(), CWinSystemIOS::SetFullScreen(), CWinSystemTVOS::SetFullScreen(), CWinSystemWin10::SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11::SetFullScreen(), CLangInfo::CRegion::SetGlobalLocale(), CWinSystemAndroid::SetHdmiState(), CWinSystemAndroidGLESContext::SetHDR(), KODI::WINDOWING::GBM::CWinSystemGbm::SetHDR(), XFILE::CFile::SetHidden(), CAESinkDARWINOSX::SetHogMode(), CCoreAudioDevice::SetHogStatus(), XBMCAddon::xbmcgui::ControlList::setImageDimensions(), XBMCAddon::xbmcgui::ListItem::setInfo(), CGUIWindowFileManager::SetInitialPath(), CGUIDialogAddonInfo::SetItem(), XBMCAddon::xbmcgui::ControlList::setItemHeight(), CMusicDatabase::SetItemUpdated(), CTVOSNSUserDefaults::SetKeyData(), CLibInputKeyboard::SetKeymap(), CLangInfo::SetLanguage(), ADDON::CAddonDatabase::SetLastUpdated(), ADDON::CAddonDatabase::SetLastUsed(), CCoreAudioDevice::SetMixingSupport(), KODI::WINDOWING::GBM::CDRMUtils::SetMode(), CXRandR::SetMode(), CAndroidUtils::SetNativeResolution(), VDPAU::CMixer::SetNoiseReduction(), CCoreAudioDevice::SetNominalSampleRate(), CCoreAudioDevice::SetObjectListenerProc(), CURL::SetOptions(), CNfsConnection::setOptions(), ADDON::CAddonDatabase::SetOrigin(), XBMCAddon::xbmcgui::ControlList::setPageControlVisible(), CGUIDialogMediaFilter::SetPath(), CMusicDatabase::SetPathHash(), CVideoDatabase::SetPathHash(), CCoreAudioStream::SetPhysicalFormat(), CVideoDatabase::SetPlayCount(), CCharArrayParser::SetPosition(), CThreadImplLinux::SetPriority(), CThreadImplPosix::SetPriority(), CSpecialProtocol::SetProfilePath(), XBMCAddon::xbmcgui::ListItem::setProperty(), XFILE::CCurlFile::SetProxy(), CDVDRadioRDSData::SetRadioStyle(), XBMCAddon::xbmcgui::ListItem::setRating(), CDVDInputStreamFile::SetReadRate(), ADDON::CAddonDatabase::SetRepoUpdateData(), CMusicDatabase::SetScraper(), CMusicDatabase::SetScraperAll(), CVideoDatabase::SetScraperForPath(), CGUIDialogSubtitles::SetService(), VDPAU::CMixer::SetSharpness(), CVideoDatabase::SetSingleValue(), CVideoDatabase::SetSingleValue(), CMusicDatabase::SetSongUserrating(), CMusicDatabase::SetSongUserrating(), CMusicDatabase::SetSongVotes(), XBMCAddon::xbmcgui::ControlList::setSpace(), CVideoReferenceClock::SetSpeed(), KODI::RETRO::CRetroPlayer::SetSpeed(), CDVDClock::SetSpeedAdjust(), CVideoDatabase::SetStackTimes(), KODI::WINDOWING::WAYLAND::CWindowDecorator::SetState(), anonymous_namespace{GUIBuiltins.cpp}::SetStereoMode(), CVideoDatabase::SetStreamDetailsForFileId(), CDVDDemuxClient::SetStreamProps(), ADDON::CSkinInfo::SetString(), XSLTUtils::SetStylesheet(), CVideoPlayerAudio::SetSyncType(), CTextureDatabase::SetTextureForPath(), ADDON::CAddon::SettingsFromXML(), ADDON::CSkinInfo::SettingsFromXML(), ADDON::CAddon::SettingsToXML(), ADDON::CSkinInfo::SettingsToXML(), CTVOSTopShelf::SetTopShelfItems(), CZeroconfBrowser::ZeroconfService::SetTxtRecords(), XBMCAddon::xbmcgui::ListItem::setUniqueIDs(), KODI::PLAYLIST::CPlayList::SetUnPlayable(), CVideoSyncAndroid::Setup(), CVideoSyncGbm::Setup(), CVideoSyncIos::Setup(), CVideoSyncOsx::Setup(), CVideoSyncTVos::Setup(), CVideoSyncD3D::Setup(), KODI::WINDOWING::X11::CVideoSyncGLX::Setup(), KODI::WINDOWING::X11::CVideoSyncOML::Setup(), CAAudioUnitSink::setupAudio(), SetupContext(), CDVDInputStreamBluray::SetupPlayerSettings(), VAAPI::CVAAPIContext::SetValidDRMVaDisplayFromRenderNode(), KODI::WINDOWING::GBM::CDRMLegacy::SetVideoMode(), CVideoDatabase::SetVideoSettings(), CVideoDatabase::SetVideoUserRating(), CVideoDatabase::SetVideoVersion(), CViewDatabase::SetViewState(), CCoreAudioStream::SetVirtualFormat(), CAESinkPULSE::SetVolume(), KODI::WINDOWING::X11::CGLContextGLX::SetVSync(), CRenderSystemGL::SetVSync(), CRenderSystemGLES::SetVSync(), VDPAU::CDecoder::SetWidthHeight(), KODI::WINDOWING::X11::CWinSystemX11::SetWindow(), shairplay_log(), CWinSystemWin10::Show(), ADDON::Interface_GUIWindow::show(), ADDON::Interface_GUIDialogNumeric::show_and_get_date(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_directory(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_file(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_file_from_dir(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_file_list(), ADDON::Interface_GUIDialogKeyboard::show_and_get_filter(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_image(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_image_list(), ADDON::Interface_GUIDialogKeyboard::show_and_get_input(), ADDON::Interface_GUIDialogYesNo::show_and_get_input_line_button_text(), ADDON::Interface_GUIDialogOK::show_and_get_input_line_text(), ADDON::Interface_GUIDialogYesNo::show_and_get_input_line_text(), ADDON::Interface_GUIDialogOK::show_and_get_input_single_text(), ADDON::Interface_GUIDialogYesNo::show_and_get_input_single_text(), ADDON::Interface_GUIDialogKeyboard::show_and_get_input_with_head(), ADDON::Interface_GUIDialogNumeric::show_and_get_ip_address(), ADDON::Interface_GUIDialogKeyboard::show_and_get_new_password(), ADDON::Interface_GUIDialogKeyboard::show_and_get_new_password_with_head(), ADDON::Interface_GUIDialogNumeric::show_and_get_number(), ADDON::Interface_GUIDialogNumeric::show_and_get_seconds(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_source(), ADDON::Interface_GUIDialogNumeric::show_and_get_time(), ADDON::Interface_GUIDialogNumeric::show_and_verify_input(), ADDON::Interface_GUIDialogNumeric::show_and_verify_new_password(), ADDON::Interface_GUIDialogKeyboard::show_and_verify_new_password(), ADDON::Interface_GUIDialogKeyboard::show_and_verify_new_password_with_head(), ADDON::Interface_GUIDialogNumeric::show_and_verify_password(), ADDON::Interface_GUIDialogKeyboard::show_and_verify_password(), ADDON::Interface_GUIDialogProgress::show_progress_bar(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), KODI::GAME::CGUIDialogSelectSavestate::ShowAndGetSavestate(), KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), ShowDiscoveryMessage(), CGUIDialogTextViewer::ShowForFile(), CGUIWindowVideoBase::ShowInfo(), CGUIDialogSimpleMenu::ShowPlaySelection(), KODI::PLAYLIST::CPlayList::Shuffle(), DRM::CMediaDrmCryptoSession::Sign(), CDVDVideoCodecAndroidMediaCodec::SignalEndOfStream(), SinkCallback(), SinkChangedCallback(), SinkInfoCallback(), SinkInfoRequestCallback(), CAESinkALSA::sndLibErrorHandler(), VDPAU::CVDPAUContext::SpewHardwareAvailable(), CGUIInfoManager::SplitInfoString(), CUtil::SplitParams(), CFileItemList::StackFiles(), CFileItemList::StackFolders(), ADDON::CSkinInfo::Start(), CALSADeviceMonitor::Start(), CCoreAudioDevice::Start(), KODI::PIPEWIRE::CPipewire::Start(), WSDiscovery::CWSDiscoveryListenerUDP::Start(), PVR::CPVRManager::Start(), ActiveAE::CActiveAE::Start(), CDriverMonitor::Start(), ADDON::CServiceAddonManager::Start(), CAlarmClock::Start(), CNetworkServices::StartAirTunesServer(), CNetworkServices::StartEventServer(), CFDEventMonitor::StartMonitoring(), CRenderManager::StartRenderCapture(), XFILE::CPluginDirectory::StartScript(), EVENTSERVER::CEventServer::StartServer(), WSDiscovery::CWSDiscoveryWindows::StartServices(), CNetworkServices::StartUPnPClient(), CNetworkServices::StartUPnPController(), CNetworkServices::StartUPnPRenderer(), CNetworkServices::StartUPnPServer(), CNetworkServices::StartWebserver(), CNetworkServices::StartZeroconf(), XFILE::CFile::Stat(), CNfsConnection::stat(), XFILE::CCurlFile::Stat(), XFILE::CNFSFile::Stat(), XFILE::CAPKFile::Stat(), CUtil::Stat64ToStat(), ADDON::Interface_Filesystem::stat_file(), KODI::PIPEWIRE::CPipewireStream::StateChanged(), VDPAU::CMixer::StateMachine(), VDPAU::COutput::StateMachine(), ActiveAE::CActiveAE::StateMachine(), ActiveAE::CActiveAESink::StateMachine(), VAAPI::COutput::StateMachine(), CAESinkSNDIO::Stop(), CCoreAudioDevice::Stop(), XBMCHelper::Stop(), WSDiscovery::CWSDiscoveryListenerUDP::Stop(), anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::Stop(), CPythonInvoker::stop(), PVR::CPVRManager::Stop(), ADDON::CServiceAddonManager::Stop(), CApplication::Stop(), CXBMCApp::Stop(), CNetworkServices::StopEventServer(), WSDiscovery::CWSDiscoveryWindows::StopServices(), CNetworkServices::StopUPnP(), CNetworkServices::StopUPnPClient(), CNetworkServices::StopUPnPController(), CNetworkServices::StopUPnPRenderer(), CNetworkServices::StopUPnPServer(), CNetworkServices::StopWebserver(), CNetworkServices::StopZeroconf(), CPowerManager::StorePlayerState(), CDVDDemuxUtils::StoreSideData(), ActiveAE::CActiveAESound::StoreSound(), CArchive::streamin_bufferwrap(), CInputStreamAddon::Supports(), KODI::WINDOWING::GBM::CDRMPlane::SupportsFormatAndModifier(), CRenderCaptureDX::SurfaceToBuffer(), CCocoaPowerSyscall::Suspend(), CGLContextEGL::SwapBuffers(), KODI::WINDOWING::X11::CGLContextGLX::SwapBuffers(), CVideoPlayerAudio::SwitchCodecIfNeeded(), CAEStreamParser::SyncAC3(), CAEStreamParser::SyncDTS(), ADDON::CAddonDatabase::SyncInstalled(), ActiveAE::CActiveAE::SyncStream(), CAEStreamParser::SyncTrueHD(), CScreenShot::TakeScreenshot(), CScreenShot::TakeScreenshot(), TEST_F(), PERIPHERALS::CPeripherals::TestFeature(), ADDON::CAddonDll::TransferSettings(), ADDON::Interface_Filesystem::translate_special_protocol(), TranslateAliasShortcut(), KODI::KEYMAP::CAppTranslator::TranslateAppCommand(), KODI::KEYMAP::CKeyboardTranslator::TranslateButton(), CMouseTranslator::TranslateCommand(), KODI::KEYBOARD::CKeyboardStat::TranslateKey(), CSpecialProtocol::TranslatePath(), translatePathIntoKey(), KODI::GAME::CGameClientStreamAudio::TranslateProperties(), KODI::GAME::CGameClientStreamVideo::TranslateProperties(), KODI::KEYMAP::CKeyboardTranslator::TranslateString(), KODI::ACTION::CActionTranslator::TranslateString(), KODI::KEYMAP::CGamepadTranslator::TranslateString(), KODI::KEYMAP::CIRTranslator::TranslateString(), KODI::KEYMAP::CTouchTranslator::TranslateTouchCommand(), CWindowTranslator::TranslateWindow(), PVR::CPVRManager::TriggerCleanupCachedImages(), KODI::PIPEWIRE::CPipewireStream::TriggerProcess(), XFILE::CFile::Truncate(), XFILE::CNFSFile::Truncate(), XFILE::CSMBFile::Truncate(), ADDON::Interface_Filesystem::truncate_file(), anonymous_namespace{Registry.cpp}::TryBind(), CAESinkALSA::TryDevice(), CAEStreamParser::TrySyncAC3(), ActiveAE::CActiveAE::UnconfigureSink(), CPODocument::UnescapeString(), WSDiscovery::CWSDiscoveryListenerUDP::UnicastGet(), KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::Uninhibit(), VAAPI::COutput::Uninit(), CRenderManager::UnInit(), CLinuxRendererGL::UnInit(), CLinuxRendererGLES::UnInit(), CFilesystemInstaller::UnInstallFromFilesystem(), ADDON::Interface_General::unknown_to_utf8(), Win32DllLoader::Unload(), SoLoader::Unload(), ADDON::CAddonMgr::UnloadAddon(), CSectionLoader::UnloadDelayed(), CSectionLoader::UnloadDLL(), CApplicationSkinHandling::UnloadSkin(), VAAPI::CVaapi1Texture::Unmap(), CUDisks2Provider::Filesystem::Unmount(), CUDiskDevice::UnMount(), CFilesystemInstaller::UnpackArchive(), CTextureBundleXBT::UnpackFrame(), XFILE::CZipFile::UnpackFromMemory(), PERIPHERALS::CPeripheralBusAddon::UnRegisterAddon(), DllLoaderContainer::UnRegisterDll(), PERIPHERALS::CPeripheralBus::UnregisterRemovedDevices(), PERIPHERALS::CPeripheralAddon::UnregisterRemovedDevices(), CDirectoryProvider::Update(), CDatabaseManager::Update(), PVR::CPVRRecording::Update(), CGUIDialogFileBrowser::Update(), CGUIMediaWindow::Update(), CGUIWindowFileManager::Update(), PERIPHERALS::CPeripheralBusAddon::UpdateAddons(), CMusicDatabase::UpdateAlbum(), CMusicDatabase::UpdateArtist(), CMusicDatabase::UpdateArtist(), CMusicDatabase::UpdateArtistScrapedMBID(), CMusicDatabase::UpdateArtistSortNames(), CAESinkAUDIOTRACK::UpdateAvailablePassthroughCapabilities(), CAESinkAUDIOTRACK::UpdateAvailablePCMCapabilities(), CLogindUPowerSyscall::UpdateBatteryLevel(), CAESinkDirectSound::UpdateCacheStatus(), CVideoReferenceClock::UpdateClockInternal(), MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo(), CVideoDatabase::UpdateDetailsForMovie(), ADDON::CAddonMgr::UpdateDisabledReason(), CVideoDatabase::UpdateFanart(), CVideoDatabase::UpdateFileDateAdded(), CVideoPlayer::UpdateFileItemStreamDetails(), CGUIMediaWindow::UpdateFilterPath(), CDVDVideoCodecAndroidMediaCodec::UpdateFpsDuration(), CGUIRangesControl::UpdateInfo(), CVideoDatabase::UpdateMovieTitle(), CRecentlyAddedJob::UpdateMusic(), CDVDVideoCodecFFmpeg::UpdateName(), CVideoDatabase::UpdateRatings(), CVideoReferenceClock::UpdateRefreshrate(), ADDON::CAddonDatabase::UpdateRepositoryContent(), KODI::WINDOWING::GBM::CWinSystemGbm::UpdateResolutions(), CWinSystemWin10::UpdateResolutions(), CWinSystemWin32::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), CWinSystemAndroid::UpdateResolutions(), ADDON::CAddon::UpdateSetting(), ADDON::UpdateSettingValue(), ActiveAE::CEngineStats::UpdateSinkDelay(), CMusicDatabase::UpdateSource(), CMusicDatabase::UpdateSources(), CMusicDatabase::UpdateTables(), CMediaCodecVideoBuffer::UpdateTexImage(), CRecentlyAddedJob::UpdateTotal(), CGUIVisualisationControl::UpdateTrack(), CVideoDatabase::UpdateUniqueIDs(), CDatabaseManager::UpdateVersion(), CRecentlyAddedJob::UpdateVideo(), CLinuxRendererGL::UpdateVideoFilter(), CLinuxRendererGLES::UpdateVideoFilter(), CVideoDatabase::UpdateVideoSortTitle(), CVideoDatabase::UpdateVideoVersionTypeTable(), CWinEventsWin10::UpdateWindowSize(), KODI::RETRO::CWinRenderBuffer::UploadTexture(), ADDON::Interface_Network::url_encode(), CDVDInputStreamBluray::UserInput(), VAAPI::VaErrorCallback(), VAAPI::VaInfoCallback(), CLinuxRendererGL::ValidateRenderTarget(), DRM::CMediaDrmCryptoSession::Verify(), CAESinkAUDIOTRACK::VerifySinkConfiguration(), CDVDMsgGeneralSynchronize::Wait(), CNetworkBase::WaitForNet(), CAESinkPULSE::WaitForOperation(), PERIPHERALS::CPeripheralBusUSB::WaitForUpdate(), CGUIDialogBusy::WaitOnEvent(), CScriptRunner::WaitOnScriptResult(), CDVDMessageQueue::WaitUntilEmpty(), ADDON::Interface_Network::wake_on_lan(), CNetworkBase::WakeOnLan(), CWakeOnAccess::WakeUpHost(), CWakeOnAccess::WakeUpHost(), CWinEventsWin32::WndProc(), CVideoLibraryRefreshingJob::Work(), XBMCAddon::xbmcwsgi::WsgiErrorStream::write(), XFILE::CFile::Write(), XFILE::CCurlFile::Write(), XFILE::CNFSFile::Write(), CAAudioUnitSink::write(), CAAudioUnitSink::write(), AERingBuffer::Write(), ADDON::Interface_Filesystem::write_file(), XFILE::CCurlFile::CReadState::WriteCallback(), XBMCHelper::WriteFile(), KODI::CDRIP::CEncoderFFmpeg::WriteFrame(), XFILE::CSimpleFileCache::WriteToCache(), xb_smbc_log(), KODI::WINDOWING::X11::CWinSystemX11::XErrorHandler(), anonymous_namespace{LibInputKeyboard.cpp}::xkbLogger(), anonymous_namespace{XkbcommonKeymap.cpp}::xkbLogger(), XSLTUtils::XSLTTransform(), AERingBuffer::~AERingBuffer(), CDVDRadioRDSData::~CDVDRadioRDSData(), CMediaCodecVideoBufferPool::~CMediaCodecVideoBufferPool(), PERIPHERALS::CPeripheralHID::~CPeripheralHID(), CPythonInvoker::~CPythonInvoker(), KODI::RETRO::CRetroPlayerAudio::~CRetroPlayerAudio(), KODI::RETRO::CRetroPlayerAutoSave::~CRetroPlayerAutoSave(), KODI::RETRO::CRetroPlayerInput::~CRetroPlayerInput(), KODI::RETRO::CRetroPlayerVideo::~CRetroPlayerVideo(), CUDMABufferObject::~CUDMABufferObject(), CVideoPlayerAudioID3::~CVideoPlayerAudioID3(), CXHandle::~CXHandle(), CZeroconfAvahi::~CZeroconfAvahi(), CZeroconfBrowserAvahi::~CZeroconfBrowserAvahi(), and CZeroconfBrowserMDNS::~CZeroconfBrowserMDNS().
Log() [2/4]
template<typename... Args> static void CLog::Log (int level, uint32_t component, fmt::format_string< Args... > format, Args &&... args) inline static
References CanLogComponent(), GetInstance(), and Log().
Log() [3/4]
template<typename... Args> static void CLog::Log (spdlog::level::level_enum level, fmt::format_string< Args... > format, Args &&... args) inline static
References FormatAndLogInternal(), and GetInstance().
Log() [4/4]
template<typename... Args> static void CLog::Log (spdlog::level::level_enum level, uint32_t component, fmt::format_string< Args... > format, Args &&... args) inline static
References CanLogComponent(), GetInstance(), and Log().
MapLogLevel()
spdlog::level::level_enum CLog::MapLogLevel (int level) static private
References LOGDEBUG, LOGERROR, LOGFATAL, LOGINFO, LOGNONE, and LOGWARNING.
Referenced by Log().
OnSettingChanged()
void CLog::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References CSettingUtils::GetList(), m_componentLogEnabled, SetComponentLogLevel(), CSettings::SETTING_DEBUG_EXTRALOGGING, and CSettings::SETTING_DEBUG_SETEXTRALOGLEVEL.
OnSettingsLoaded()
void CLog::OnSettingsLoaded () override virtual
Settings have been loaded.
This callback can be used to trigger loading other settings.
Reimplemented from ISettingsHandler.
References CServiceBroker::GetSettingsComponent(), m_componentLogEnabled, SetComponentLogLevel(), CSettings::SETTING_DEBUG_EXTRALOGGING, and CSettings::SETTING_DEBUG_SETEXTRALOGLEVEL.
SetComponentLogLevel()
void CLog::SetComponentLogLevel (const std::vector< CVariant > & components) private
References m_componentLogLevels.
Referenced by OnSettingChanged(), and OnSettingsLoaded().
SetLogLevel()
void CLog::SetLogLevel (int level)
References FormatAndLogInternal(), LOG_LEVEL_DEBUG, LOG_LEVEL_MAX, LOG_LEVEL_NONE, m_defaultLogger, and m_logLevel.
Referenced by XBMCController::CallExit, CLog(), CAdvancedSettings::Initialize(), CAdvancedSettings::OnSettingsLoaded(), CAdvancedSettings::ParseSettingsFile(), CAdvancedSettings::SetDebugMode(), and TEST_F().
SettingOptionsLoggingComponentsFiller()
void CLog::SettingOptionsLoggingComponentsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, CLocalizeStrings::Get(), LOGADDONS, LOGAIRTUNES, LOGANNOUNCE, LOGAUDIO, LOGAVTIMING, LOGCEC, LOGCURL, LOGDATABASE, LOGDBUS, LOGEPG, LOGFFMPEG, LOGJSONRPC, LOGPVR, LOGSAMBA, LOGUPNP, LOGVIDEO, LOGWEBSERVER, LOGWINDOWING, and LOGWSDISCOVERY.
Referenced by Initialize().
UnregisterFromSettings()
void CLog::UnregisterFromSettings ()
References CServiceBroker::GetSettingsComponent().
Referenced by CAppEnvironment::TearDown().
Member Data Documentation
m_componentLogEnabled
bool CLog::m_componentLogEnabled = false private
Referenced by CanLogComponent(), OnSettingChanged(), and OnSettingsLoaded().
m_componentLogLevels
uint32_t CLog::m_componentLogLevels = 0 private
Referenced by CanLogComponent(), and SetComponentLogLevel().
m_defaultLogger
Logger CLog::m_defaultLogger private
Referenced by CLog(), FormatAndLogInternal(), and SetLogLevel().
m_fileSink
std::shared_ptr<spdlog::sinks::sink> CLog::m_fileSink private
Referenced by Deinitialize(), and Initialize().
m_logLevel
int CLog::m_logLevel private
Referenced by CLog(), GetLogLevel(), IsLogLevelLogged(), and SetLogLevel().
m_platform
std::unique_ptr<IPlatformLog> CLog::m_platform private
Referenced by CLog(), and Initialize().
m_sinks
std::shared_ptr<spdlog::sinks::dist_sink<std::mutex> > CLog::m_sinks private
Referenced by CLog(), CreateLogger(), Deinitialize(), and Initialize().
The documentation for this class was generated from the following files:
log.h
log.cpp