Kodi Documentation: TestSortUtils.cpp File Reference
TestSortUtils.cpp File Reference
#include "utils/SortUtils.h"
#include "utils/Variant.h"
#include <gtest/gtest.h>
Functions
TEST (TestSortUtils, Sort_SortBy)
TEST (TestSortUtils, Sort_SortDescription)
TEST (TestSortUtils, GetFieldsForSorting)
Function Documentation
TEST() [1/3]
TEST (TestSortUtils , GetFieldsForSorting)
References EXPECT_EQ(), FieldAlbum, FieldArtist, FieldArtistSort, fields, FieldTrackNumber, FieldYear, SortUtils::GetFieldsForSorting(), and SortByArtist.
TEST() [2/3]
TEST (TestSortUtils , Sort_SortBy)
References FieldArtist, CVariant::push_back(), SortUtils::Sort(), SortAttributeNone, SortByArtist, and SortOrderAscending.
TEST() [3/3]
TEST (TestSortUtils , Sort_SortDescription)
References FieldArtist, CVariant::push_back(), SortUtils::Sort(), SortDescription::sortBy, and SortByArtist.