Kodi Documentation: XFILE::CDirectory Class Reference
XFILE::CDirectory Class Reference
Filesystem
Wrappers for IDirectory.
#include <Directory.h>
Classes
class CHints
Public Types
using DirectoryEnumerationCallback = std::function< void(const std::shared_ptr< CFileItem > &item)>
using DirectoryFilter = std::function< bool(const std::shared_ptr< CFileItem > &folder)>
Public Member Functions
CDirectory (void)
virtual ~CDirectory (void)
Static Public Member Functions
static bool GetDirectory (const CURL &url, CFileItemList &items, const std::string &strMask, int flags)
static bool GetDirectory (const CURL &url, const std::shared_ptr< IDirectory > &pDirectory, CFileItemList &items, const CHints &hints)
static bool GetDirectory (const CURL &url, CFileItemList &items, const CHints &hints)
static bool Create (const CURL &url)
static bool Exists (const CURL &url, bool bUseCache=true)
static bool Remove (const CURL &url)
static bool RemoveRecursive (const CURL &url)
static bool GetDirectory (const std::string &strPath, CFileItemList &items, const std::string &strMask, int flags)
static bool GetDirectory (const std::string &strPath, const std::shared_ptr< IDirectory > &pDirectory, CFileItemList &items, const std::string &strMask, int flags)
static bool GetDirectory (const std::string &strPath, CFileItemList &items, const CHints &hints)
static bool EnumerateDirectory (const std::string &path, const DirectoryEnumerationCallback &callback, const DirectoryFilter &filter=[](const std::shared_ptr< CFileItem > &) { return true;}, bool fileOnly=false, const std::string &mask="", int flags=DIR_FLAG_DEFAULTS)
Enumerates files and folders in and below a directory. Every applicable gets passed to the callback.
static bool Create (const std::string &strPath)
static bool Exists (const std::string &strPath, bool bUseCache=true)
static bool Remove (const std::string &strPath)
static bool RemoveRecursive (const std::string &strPath)
static void FilterFileDirectories (CFileItemList &items, const std::string &mask, bool expandImages=false)
Filter files that act like directories from the list, replacing them with their directory counterparts.
Detailed Description
Wrappers for IDirectory.
Member Typedef Documentation
DirectoryEnumerationCallback
using XFILE::CDirectory::DirectoryEnumerationCallback = std::function<void(const std::shared_ptr<CFileItem>& item)>
DirectoryFilter
using XFILE::CDirectory::DirectoryFilter = std::function<bool(const std::shared_ptr<CFileItem>& folder)>
Constructor & Destructor Documentation
CDirectory()
CDirectory::CDirectory (void) default
~CDirectory()
CDirectory::~CDirectory (void) virtual default
Member Function Documentation
Create() [1/2]
bool CDirectory::Create (const CURL & url) static
References CPasswordManager::AuthenticateURL(), XFILE::CDirectoryFactory::Create(), CPasswordManager::GetInstance(), CURL::GetRedacted(), CURL::GetUserName(), CLog::Log(), LOGERROR, URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by CDVDDemuxFFmpeg::AddStream(), ADDON::CScraper::ClearCache(), XFILE::CFile::Copy(), CApplication::Create(), XFILE::COverrideDirectory::Create(), Create(), ADDON::Interface_Filesystem::create_directory(), PERIPHERALS::CPeripheralAddon::CreateAddon(), CUtil::CreateDirectoryEx(), KODI::RETRO::CSavestateDatabase::CreateFolderIfNotExists(), CProfileManager::CreateProfileFolders(), CSettingsComponent::CreateUserDirs(), CVideoDatabase::DumpToDummyFiles(), CFileOperationJob::CFileOperation::ExecuteOperation(), CVideoDatabase::ExportActorThumbs(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), ADDON::IAddonInstanceHandler::get_instance_user_path(), ADDON::Interface_Base::get_temp_path(), KODI::GAME::CGameClientInGameSaves::GetPath(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), CSettingsComponent::InitDirectoriesOSX(), PERIPHERALS::CPeripherals::Initialise(), XBMCHelper::Install(), CFilesystemInstaller::InstallToFilesystem(), XBMCAddon::xbmcvfs::mkdir(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), CGUIWindowFileManager::OnNewFolder(), CProfileManager::OnSettingsLoaded(), CGUIDialogProfileSettings::ShowForProfile(), TEST(), TEST(), TEST(), TEST(), TEST_P(), and TEST_P().
Create() [2/2]
bool CDirectory::Create (const std::string & strPath) static
References Create().
EnumerateDirectory()
bool CDirectory::EnumerateDirectory (const std::string & path, const DirectoryEnumerationCallback & callback, const DirectoryFilter & filter = [](const std::shared_ptr<CFileItem>&) { return true; }, bool fileOnly = false, const std::string & mask = "", int flags = DIR_FLAG_DEFAULTS) static
Enumerates files and folders in and below a directory. Every applicable gets passed to the callback.
Parameters
path Directory to enumerate
callback Files and folders matching the criteria are passed to this function
filter Only folders are passed to this function. If it return false the folder and everything below it will skipped from the enumeration
fileOnly If true only files are passed to callback. Doesn't affect filter
mask Only files matching this mask are passed to callback
flags See DIR_FLAG enum
References EnumerateDirectory(), and GetDirectory().
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideoExtras(), EnumerateDirectory(), and KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder().
Exists() [1/2]
bool CDirectory::Exists (const CURL & url, bool bUseCache = true) static
References URIUtils::AddSlashAtEnd(), CPasswordManager::AuthenticateURL(), XFILE::CDirectoryFactory::Create(), XFILE::CDirectoryCache::FileExists(), g_directoryCache, CURL::Get(), CPasswordManager::GetInstance(), CURL::GetRedacted(), CURL::GetUserName(), CLog::Log(), LOGERROR, URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::AddItemPathStringToFileBrowserSources(), CGUIDialogMusicInfo::AddItemPathToFileBrowserSources(), CGUIDialogVideoManager::AppendItemFolderToFileBrowserSources(), UPNP::CUPnPServer::Build(), CVideoDatabase::CleanDatabase(), CVideoDatabase::CleanMediaType(), ADDON::CScraper::ClearCache(), KODI::UTILS::FONT::ClearTemporaryFonts(), CDVDSubtitlesLibass::Configure(), PERIPHERALS::CPeripheralAddon::CreateAddon(), CUtil::CreateDirectoryEx(), KODI::RETRO::CSavestateDatabase::CreateFolderIfNotExists(), CSettingsComponent::CreateUserDirs(), ADDON::CAddonMgr::DeInit(), ADDON::Interface_Filesystem::directory_exists(), CFileOperationJob::DoProcess(), CGetInfoJob::DoWork(), CFileItem::Exists(), XFILE::CFavouritesDirectory::Exists(), XFILE::CMultiPathDirectory::Exists(), XFILE::COverrideDirectory::Exists(), Exists(), XBMCAddon::xbmcvfs::exists(), CVideoDatabase::ExportActorThumbs(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs(), JSONRPC::CFileOperations::FillFileItem(), JSONRPC::CAudioLibrary::FillFileItem(), JSONRPC::CFileItemHandler::FillFileItemList(), ADDON::CAddonInfo::GetKnownInstanceIds(), CAndroidStorageProvider::GetLocalDrives(), KODI::VIDEO::CVideoInfoScanner::GetMovieSetInfoFolder(), CUtil::GetNextPathname(), XFILE::CLibraryDirectory::GetNode(), KODI::GAME::CGameClientInGameSaves::GetPath(), CAndroidStorageProvider::GetRemovableDrives(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), CGUITextureManager::GetTexturePath(), CProfileManager::GetUserDataItem(), CVideoDatabase::ImportFromXML(), CSettingsComponent::InitDirectoriesLinux(), CFilesystemInstaller::InstallToFilesystem(), ADDON::CAddonMgr::IsBundledAddon(), KODI::KEYMAP::CButtonTranslator::Load(), CProfileManager::Load(), KODI::KEYBOARD::CKeyboardLayoutManager::Load(), LoadStr2Mem(), GUIFontManager::LoadUserFonts(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogLibExportSettings::OnOK(), CGUIDialogMediaSource::OnPathBrowse(), CGUIDialogAddonInfo::OnUninstall(), MUSIC_INFO::CMusicInfoScanner::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), ADDON::CAddonInstaller::RemoveDependency(), CHTTPWebinterfaceHandler::ResolveUrl(), MUSIC_INFO::CMusicInfoScanner::RetrieveLocalArt(), CUtil::ScanForExternalSubtitles(), anonymous_namespace{GUIBuiltins.cpp}::Screenshot(), CMusicDatabase::SetPathHash(), TEST(), TEST(), TEST(), and MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo().
Exists() [2/2]
bool CDirectory::Exists (const std::string & strPath, bool bUseCache = true) static
References Exists().
FilterFileDirectories()
void CDirectory::FilterFileDirectories (CFileItemList & items, const std::string & mask, bool expandImages = false) static
Filter files that act like directories from the list, replacing them with their directory counterparts.
Parameters
items The item list to filter
mask The mask to apply when filtering files
expandImages True to include disc images in file directory expansion
References XFILE::CFileDirectoryFactory::Create(), EFILEFOLDER_TYPE_ALWAYS, EFILEFOLDER_TYPE_ONBROWSE, CFileItem::IsDiscImage(), CFileItemList::Remove(), and CFileItemList::Size().
Referenced by GetDirectory(), CGUIWindowMusicBase::GetDirectory(), and TEST().
GetDirectory() [1/6]
bool CDirectory::GetDirectory (const CURL & url, CFileItemList & items, const CHints & hints) static
References XFILE::CDirectoryFactory::Create(), GetDirectory(), and URIUtils::SubstitutePath().
GetDirectory() [2/6]
bool CDirectory::GetDirectory (const CURL & url, CFileItemList & items, const std::string & strMask, int flags) static
References XFILE::CDirectory::CHints::flags, GetDirectory(), and XFILE::CDirectory::CHints::mask.
Referenced by CGUIWindowSlideShow::AddItems(), MUSIC_INFO::CMusicInfoScanner::AddLocalArtwork(), KODI::VIDEO::CVideoInfoScanner::AddLocalItemArtwork(), ADDON::Interface_Filesystem::can_open_directory(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::ChooseStackItemPartNumber(), CVideoDatabase::CleanDatabase(), ADDON::CScraper::ClearCache(), ClearPhotoAssetCache(), CUtil::ClearSubtitles(), KODI::UTILS::FONT::ClearTemporaryFonts(), CGUIDialogCMSSettings::Cms3dLutsFiller(), CDVDSubtitlesLibass::Configure(), MUSIC_INFO::CMusicInfoScanner::CountFilesRecursively(), XFILE::CFileDirectoryFactory::Create(), CMusicDatabase::DeleteCDDBInfo(), CUtil::DeleteDirectoryCache(), CBlurayCallback::dir_open(), dll_findfirst64i32(), dll_opendir(), CFileOperationJob::DoProcessFolder(), MUSIC_INFO::CMusicInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::DoScan(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CGUIMultiImage::CMultiImageJob::DoWork(), CDirectoryJob::DoWork(), CSubtitlesJob::DoWork(), EnumerateDirectory(), ADDON::CAddonInstaller::EnumeratePackageFolder(), KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs(), ADDON::CAddonSettings::FileEnumSettingOptionsFiller(), JSONRPC::CFileOperations::FillFileItemList(), ADDON::CAddonMgr::FindAddons(), CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), ADDON::Interface_Filesystem::get_directory(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), XFILE::CBlurayDirectory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMultiPathDirectory::GetDirectory(), XFILE::CResourceDirectory::GetDirectory(), XFILE::CSpecialProtocolDirectory::GetDirectory(), XFILE::CZeroconfDirectory::GetDirectory(), XFILE::CVirtualDirectory::GetDirectory(), GetDirectory(), GetDirectory(), JSONRPC::CFileOperations::GetDirectory(), GetDirectory(), GetDirectory(), GetDirectory(), ADDON::CScraper::GetEpisodeList(), JSONRPC::CFileOperations::GetFileDetails(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CUtil::GetItemsToScan(), ADDON::CAddonInfo::GetKnownInstanceIds(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::GetLocalArt(), CVideoThumbLoader::GetLocalArt(), KODI::ART::GetLocalFanart(), CGUIDialogVideoInfo::GetMoviesForSet(), CUtil::GetNextFilename(), XFILE::CSmartPlaylistDirectory::GetPlaylistByName(), CUtil::GetRecursiveDirsListing(), CUtil::GetRecursiveListing(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), KODI::RETRO::CSavestateDatabase::GetSavestatesNav(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), CGUIDialogVideoInfo::GetSetForMovie(), CUtil::GetSkinThemes(), CGUIViewStateWindowMusicNav::GetSources(), CGUIViewStateWindowVideoNav::GetSources(), KODI::VIDEO::UTILS::GetStackPartResumeInformation(), XFILE::CDirectoryCache::InitCache(), ADDON::CAddonInstaller::InstallFromZip(), XBMCAddon::xbmcvfs::listdir(), KODI::KEYMAP::CButtonTranslator::Load(), CPictureFolderImageFileLoader::Load(), KODI::KEYBOARD::CKeyboardLayoutManager::Load(), CApplicationSkinHandling::LoadCustomWindows(), GUIFontManager::LoadFonts(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadRecordingFileOrFolderItem(), GUIFontManager::LoadUserFonts(), ADDON::CScraper::NfoUrl(), CGUIDialogFileBrowser::OnAddNetworkLocation(), CGUIDialogSmartPlaylistRule::OnBrowse(), UPNP::CUPnPServer::OnBrowseDirectChildren(), CGUIWindowVideoNav::OnDeleteItem(), CGUIDialogMusicInfo::OnGetArt(), CGUIWindowVideoBase::OnItemInfo(), CGUIDialogMediaSource::OnOK(), CGUIWindowVideoBase::OnPlayStackPart(), CGUIDialogAddonInfo::OnSelectVersion(), CPictureThumbLoader::ProcessFoldersAndArchives(), ADDON::PythonFind(), ADDON::Interface_Filesystem::remove_directory(), CUtil::RemoveTempFiles(), CCueDocument::ResolvePath(), anonymous_namespace{GUIDialogSimpleMenu.cpp}::CGetDirectoryItems::Run(), CUtil::ScanArchiveForAssociatedItems(), CUtil::ScanForExternalSubtitles(), PVR::CPVRGUIChannelIconUpdater::SearchAndUpdateMissingChannelIcons(), GUIFontManager::SettingOptionsFontsFiller(), ADDON::CSkinInfo::SettingOptionsSkinColorsFiller(), ADDON::CSkinInfo::SettingOptionsSkinFontsFiller(), CGUIDialogFileBrowser::ShowAndGetFile(), CFileItemList::StackFolders(), ADDON::CSkinInfo::Start(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and CFilesystemInstaller::UnpackArchive().
GetDirectory() [3/6]
bool CDirectory::GetDirectory (const CURL & url, const std::shared_ptr< IDirectory > & pDirectory, CFileItemList & items, const CHints & hints) static
Todo:
we shouldn't be checking the gui setting here, callers should use getHidden instead
References CPasswordManager::AuthenticateURL(), XFILE::CDirectoryCache::ClearDirectory(), XFILE::DIR_FLAG_BYPASS_CACHE, XFILE::DIR_FLAG_GET_HIDDEN, XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_READ_CACHE, FilterFileDirectories(), XFILE::CDirectory::CHints::flags, g_directoryCache, CURL::Get(), CServiceBroker::GetAppMessenger(), XFILE::CDirectoryCache::GetDirectory(), CURL::GetDomain(), CPasswordManager::GetInstance(), CURL::GetPassWord(), CURL::GetRedacted(), CServiceBroker::GetSettingsComponent(), CURL::GetUserName(), KODI::MUSIC::IsMusicDb(), KODI::PLAYLIST::IsSmartPlayList(), CLog::Log(), LOGERROR, XFILE::CDirectory::CHints::mask, CFileItemList::Remove(), XFILE::CDirectoryCache::SetDirectory(), CURL::SetDomain(), CURL::SetPassword(), CFileItem::SetPath(), CSettings::SETTING_FILELISTS_SHOWHIDDEN, CFileItem::SetURL(), CURL::SetUserName(), CFileItemList::Size(), URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
GetDirectory() [4/6]
bool CDirectory::GetDirectory (const std::string & strPath, CFileItemList & items, const CHints & hints) static
References GetDirectory().
GetDirectory() [5/6]
bool CDirectory::GetDirectory (const std::string & strPath, CFileItemList & items, const std::string & strMask, int flags) static
References XFILE::CDirectory::CHints::flags, GetDirectory(), and XFILE::CDirectory::CHints::mask.
GetDirectory() [6/6]
bool CDirectory::GetDirectory (const std::string & strPath, const std::shared_ptr< IDirectory > & pDirectory, CFileItemList & items, const std::string & strMask, int flags) static
References XFILE::CDirectory::CHints::flags, GetDirectory(), and XFILE::CDirectory::CHints::mask.
Remove() [1/2]
bool CDirectory::Remove (const CURL & url) static
References CPasswordManager::AuthenticateURL(), XFILE::CDirectoryCache::ClearFile(), XFILE::CDirectoryFactory::Create(), g_directoryCache, CURL::Get(), CPasswordManager::GetInstance(), CURL::GetRedacted(), CURL::GetUserName(), CLog::Log(), LOGERROR, URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by CFileOperationJob::CFileOperation::ExecuteOperation(), CVideoDatabase::ExportToXML(), XFILE::CMultiPathDirectory::Remove(), XFILE::COverrideDirectory::Remove(), Remove(), ADDON::Interface_Filesystem::remove_directory(), XBMCAddon::xbmcvfs::rmdir(), CGUIDialogProfileSettings::ShowForProfile(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
Remove() [2/2]
bool CDirectory::Remove (const std::string & strPath) static
References Remove().
RemoveRecursive() [1/2]
bool CDirectory::RemoveRecursive (const CURL & url) static
References CPasswordManager::AuthenticateURL(), XFILE::CDirectoryCache::ClearFile(), XFILE::CDirectoryFactory::Create(), g_directoryCache, CURL::Get(), CPasswordManager::GetInstance(), CURL::GetRedacted(), CURL::GetUserName(), CLog::Log(), LOGERROR, URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by CSettingsComponent::CreateUserDirs(), ADDON::CAddonMgr::DeInit(), CFilesystemInstaller::InstallToFilesystem(), ADDON::Interface_Filesystem::remove_directory_recursive(), RemoveRecursive(), TestBasicEnvironment::TearDown(), TEST(), TEST_P(), TEST_P(), TEST_P(), and CFilesystemInstaller::UnInstallFromFilesystem().
RemoveRecursive() [2/2]
bool CDirectory::RemoveRecursive (const std::string & strPath) static
References RemoveRecursive().
The documentation for this class was generated from the following files:
Directory.h
Directory.cpp