Kodi Documentation: CDVDOverlayCodecSSA Class Reference
CDVDOverlayCodecSSA Class Reference
#include <DVDOverlayCodecSSA.h>
Public Member Functions
CDVDOverlayCodecSSA ()
~CDVDOverlayCodecSSA () override=default
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
OverlayMessage Decode (DemuxPacket *pPacket) override
void Reset () override
void Flush () override
std::shared_ptr< CDVDOverlay > GetOverlay () override
Public Member Functions inherited from CDVDOverlayCodec
CDVDOverlayCodec (const char *name)
virtual ~CDVDOverlayCodec ()=default
const std::string & GetName () const
Private Attributes
std::shared_ptr< CDVDSubtitlesLibass > m_libass
std::shared_ptr< CDVDOverlaySSA > m_pOverlay
int m_order
Additional Inherited Members
Static Protected Member Functions inherited from CDVDOverlayCodec
static void GetAbsoluteTimes (double &starttime, double &stoptime, DemuxPacket *pkt)
Constructor & Destructor Documentation
CDVDOverlayCodecSSA()
CDVDOverlayCodecSSA::CDVDOverlayCodecSSA ()
References m_libass, and m_order.
~CDVDOverlayCodecSSA()
CDVDOverlayCodecSSA::~CDVDOverlayCodecSSA () override default
Member Function Documentation
Decode()
OverlayMessage CDVDOverlayCodecSSA::Decode (DemuxPacket * pPacket) override virtual
Implements CDVDOverlayCodec.
References data(), DEMUX_PACKET::dts, DEMUX_PACKET::duration, DVD_NOPTS_VALUE, end(), DEMUX_PACKET::iSize, m_libass, m_order, m_pOverlay, OC_DONE, OC_ERROR, OC_OVERLAY, DEMUX_PACKET::pData, and DEMUX_PACKET::pts.
Flush()
void CDVDOverlayCodecSSA::Flush () override virtual
Implements CDVDOverlayCodec.
References m_order, and m_pOverlay.
Referenced by Reset().
GetOverlay()
std::shared_ptr< CDVDOverlay > CDVDOverlayCodecSSA::GetOverlay () override virtual
Implements CDVDOverlayCodec.
References DVD_NOPTS_VALUE, CServiceBroker::GetSettingsComponent(), m_libass, and m_pOverlay.
Open()
bool CDVDOverlayCodecSSA::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Implements CDVDOverlayCodec.
References CDVDStreamInfo::codec, CDVDStreamInfo::extradata, FFmpegExtraData::GetData(), FFmpegExtraData::GetSize(), m_libass, and m_pOverlay.
Reset()
void CDVDOverlayCodecSSA::Reset () override virtual
Implements CDVDOverlayCodec.
References Flush().
Member Data Documentation
m_libass
std::shared_ptr<CDVDSubtitlesLibass> CDVDOverlayCodecSSA::m_libass private
Referenced by CDVDOverlayCodecSSA(), Decode(), GetOverlay(), and Open().
m_order
int CDVDOverlayCodecSSA::m_order private
Referenced by CDVDOverlayCodecSSA(), Decode(), and Flush().
m_pOverlay
std::shared_ptr<CDVDOverlaySSA> CDVDOverlayCodecSSA::m_pOverlay private
Referenced by Decode(), Flush(), GetOverlay(), and Open().
The documentation for this class was generated from the following files:
DVDOverlayCodecSSA.h
DVDOverlayCodecSSA.cpp