Kodi Documentation: PlatformDefs.h File Reference
PlatformDefs.h File Reference
#include <windows.h>
#include <winsock2.h>
#include <inttypes.h>
Macros
#define __STDC_FORMAT_MACROS
#define _SSIZE_T_DEFINED
#define SSIZE_MAX INTPTR_MAX
#define ftello64 _ftelli64
#define fseeko64 _fseeki64
#define PIXEL_ASHIFT 24
#define PIXEL_RSHIFT 16
#define PIXEL_GSHIFT 8
#define PIXEL_BSHIFT 0
Typedefs
typedef __int64 off64_t
typedef __int64 fpos64_t
typedef __int64 __off64_t
typedef long __off_t
typedef intptr_t ssize_t
Functions
char * strptime (const char *buf, const char *fmt, struct tm *tm)
Macro Definition Documentation
__STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
_SSIZE_T_DEFINED
#define _SSIZE_T_DEFINED
fseeko64
#define fseeko64 _fseeki64
ftello64
#define ftello64 _ftelli64
PIXEL_ASHIFT
#define PIXEL_ASHIFT 24
PIXEL_BSHIFT
#define PIXEL_BSHIFT 0
PIXEL_GSHIFT
#define PIXEL_GSHIFT 8
PIXEL_RSHIFT
#define PIXEL_RSHIFT 16
SSIZE_MAX
#define SSIZE_MAX INTPTR_MAX
Typedef Documentation
__off64_t
typedef __int64 __off64_t
__off_t
typedef long __off_t
fpos64_t
typedef __int64 fpos64_t
off64_t
typedef __int64 off64_t
ssize_t
typedef intptr_t ssize_t
Function Documentation
strptime()
char * strptime (const char * buf, const char * fmt, struct tm * tm)
References __UNCONST, _ctloc, abday, abmon, ALT_E, ALT_O, am_pm, conv_num(), d_fmt, d_t_fmt, day, find_string(), LEGAL_ALT, mon, strptime(), t_fmt, t_fmt_ampm, and TM_YEAR_BASE.
Referenced by ADDON::CScraper::GetEpisodeList(), ParseDate(), XFILE::CDAVDirectory::ParseResponse(), and strptime().