Kodi Documentation: CAutorunMediaJob Class Reference
CAutorunMediaJob Class Reference
#include <AutorunMediaJob.h>
Public Member Functions
CAutorunMediaJob (const std::string &label, const std::string &path)
bool DoWork () override
Main workhorse function of CJob instances.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual const char * GetType () const
Function that returns the type of job.
virtual bool operator== (const CJob *job) const
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Private Member Functions
const char * GetWindowString (int selection)
Private Attributes
std::string m_path
std::string m_label
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Constructor & Destructor Documentation
CAutorunMediaJob()
CAutorunMediaJob::CAutorunMediaJob (const std::string & label, const std::string & path)
Member Function Documentation
DoWork()
bool CAutorunMediaJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), m_label, CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CApplicationPowerHandling::WakeUpScreenSaverAndDPMS(), and WINDOW_DIALOG_SELECT.
GetWindowString()
const char * CAutorunMediaJob::GetWindowString (int selection) private
Member Data Documentation
m_label
std::string CAutorunMediaJob::m_label private
Referenced by DoWork().
m_path
std::string CAutorunMediaJob::m_path private
The documentation for this class was generated from the following files:
AutorunMediaJob.h
AutorunMediaJob.cpp