Kodi Documentation: CDVDDemuxClient Class Reference
CDVDDemuxClient Class Reference
#include <DVDDemuxClient.h>
Public Member Functions
CDVDDemuxClient ()
~CDVDDemuxClient () override
bool Open (std::shared_ptr< CDVDInputStream > pInput)
void Dispose ()
bool Reset () override
void Abort () override
void Flush () override
DemuxPacket * Read () override
bool SeekTime (double time, bool backwards=false, double *startpts=NULL) override
void SetSpeed (int iSpeed) override
void FillBuffer (bool mode) override
CDemuxStream * GetStream (int iStreamId) const override
std::vector< CDemuxStream * > GetStreams () const override
int GetNrOfStreams () const override
std::string GetFileName () override
std::string GetStreamCodecName (int iStreamId) override
void EnableStream (int id, bool enable) override
void OpenStream (int id) override
void SetVideoResolution (unsigned int width, unsigned int height) override
Public Member Functions inherited from CDVDDemux
CDVDDemux ()
virtual ~CDVDDemux ()=default
virtual bool SeekChapter (int chapter, double *startpts=NULL)
virtual int GetChapterCount ()
virtual int GetChapter ()
virtual void GetChapterName (std::string &strChapterName, int chapterIdx=-1)
virtual int64_t GetChapterPos (int chapterIdx=-1)
virtual int GetStreamLength ()
virtual CDemuxStream * GetStream (int64_t demuxerId, int iStreamId) const
virtual int GetPrograms (std::vector< ProgramInfo > &programs)
virtual void SetProgram (int progId)
int GetNrOfSubtitleStreams ()
virtual std::string GetStreamCodecName (int64_t demuxerId, int iStreamId)
virtual void EnableStream (int64_t demuxerId, int id, bool enable)
virtual void OpenStream (int64_t demuxerId, int id)
int64_t GetDemuxerId ()
Protected Member Functions
void RequestStreams ()
void SetStreamProps (CDemuxStream *stream, std::map< int, std::shared_ptr< CDemuxStream > > &map, bool forceInit)
bool ParsePacket (DemuxPacket *pPacket)
void DisposeStreams ()
std::shared_ptr< CDemuxStream > GetStreamInternal (int iStreamId)
bool IsVideoReady ()
Protected Member Functions inherited from CDVDDemux
int GetNrOfStreams (StreamType streamType)
Protected Attributes
std::shared_ptr< CDVDInputStream > m_pInput
std::shared_ptr< CDVDInputStream::IDemux > m_IDemux
std::map< int, std::shared_ptr< CDemuxStream > > m_streams
int m_displayTime
double m_dtsAtDisplayTime
std::unique_ptr< DemuxPacket > m_packet
int m_videoStreamPlaying = -1
Protected Attributes inherited from CDVDDemux
int64_t m_demuxerId
Static Private Member Functions
static bool CodecHasExtraData (AVCodecID id)
Constructor & Destructor Documentation
CDVDDemuxClient()
CDVDDemuxClient::CDVDDemuxClient ()
References m_streams.
~CDVDDemuxClient()
CDVDDemuxClient::~CDVDDemuxClient () override
References Dispose().
Member Function Documentation
Abort()
void CDVDDemuxClient::Abort () override virtual
Reimplemented from CDVDDemux.
References m_IDemux.
Referenced by Open().
CodecHasExtraData()
bool CDVDDemuxClient::CodecHasExtraData (AVCodecID id) inline static private
Referenced by IsVideoReady(), and ParsePacket().
Dispose()
void CDVDDemuxClient::Dispose ()
References DisposeStreams(), m_IDemux, and m_pInput.
Referenced by Reset(), and ~CDVDDemuxClient().
DisposeStreams()
void CDVDDemuxClient::DisposeStreams () protected
References m_streams, and m_videoStreamPlaying.
Referenced by Dispose(), and SetStreamProps().
EnableStream()
void CDVDDemuxClient::EnableStream (int id, bool enable) override virtual
Reimplemented from CDVDDemux.
References m_IDemux.
FillBuffer()
void CDVDDemuxClient::FillBuffer (bool mode) override virtual
Reimplemented from CDVDDemux.
References m_IDemux.
Flush()
void CDVDDemuxClient::Flush () override virtual
Implements CDVDDemux.
References DVD_NOPTS_VALUE, m_displayTime, m_dtsAtDisplayTime, and m_IDemux.
GetFileName()
std::string CDVDDemuxClient::GetFileName () override virtual
Reimplemented from CDVDDemux.
References m_pInput.
GetNrOfStreams()
int CDVDDemuxClient::GetNrOfStreams () const override virtual
Implements CDVDDemux.
References m_streams.
GetStream()
CDemuxStream * CDVDDemuxClient::GetStream (int iStreamId) const override virtual
Implements CDVDDemux.
References m_streams.
Referenced by GetStreamCodecName(), and ParsePacket().
GetStreamCodecName()
std::string CDVDDemuxClient::GetStreamCodecName (int iStreamId) override virtual
Reimplemented from CDVDDemux.
References CDemuxStream::codec, and GetStream().
GetStreamInternal()
std::shared_ptr< CDemuxStream > CDVDDemuxClient::GetStreamInternal (int iStreamId) protected
References m_streams.
Referenced by SetStreamProps().
GetStreams()
std::vector< CDemuxStream * > CDVDDemuxClient::GetStreams () const override virtual
Implements CDVDDemux.
References m_streams.
IsVideoReady()
bool CDVDDemuxClient::IsVideoReady () protected
References CodecHasExtraData(), m_streams, m_videoStreamPlaying, and STREAM_VIDEO.
Referenced by Read().
Open()
bool CDVDDemuxClient::Open (std::shared_ptr< CDVDInputStream > pInput)
References Abort(), DVD_NOPTS_VALUE, m_displayTime, m_dtsAtDisplayTime, m_IDemux, m_pInput, and RequestStreams().
Referenced by Reset().
OpenStream()
void CDVDDemuxClient::OpenStream (int id) override virtual
Reimplemented from CDVDDemux.
References id, m_IDemux, m_streams, m_videoStreamPlaying, SetStreamProps(), STREAM_VIDEO, and CDemuxStream::type.
ParsePacket()
bool CDVDDemuxClient::ParsePacket (DemuxPacket * pPacket) protected
References CDemuxStream::changes, CDemuxStream::codec, CodecHasExtraData(), CDemuxStream::disabled, CDemuxStreamClientInternal::DisposeParser(), DEMUX_PACKET::dts, DVD_TIME_BASE, CDemuxStream::extraData, GetPacketExtradata(), GetStream(), int64_t(), DEMUX_PACKET::iSize, DEMUX_PACKET::iStreamId, CDemuxStream::level, CLog::Log(), LOGDEBUG, LOGERROR, CDemuxStreamClientInternal::m_context, CDemuxStreamClientInternal::m_parser, CDemuxStreamClientInternal::m_parser_split, DEMUX_PACKET::pData, CDemuxStream::profile, DEMUX_PACKET::pts, STREAM_AUDIO, STREAM_VIDEO, CDemuxStream::type, and CDemuxStream::uniqueId.
Referenced by Read().
Read()
DemuxPacket * CDVDDemuxClient::Read () override virtual
Todo:
drop this block
Implements CDVDDemux.
References CDVDDemuxUtils::AllocateDemuxPacket(), DEMUX_PACKET::demuxerId, DMX_SPECIALID_STREAMCHANGE, DMX_SPECIALID_STREAMINFO, DVD_NOPTS_VALUE, DVD_TIME_TO_MSEC(), CDVDDemuxUtils::FreeDemuxPacket(), CDVDInputStream::IDisplayTime::GetTime(), DEMUX_PACKET::iStreamId, IsVideoReady(), CDVDDemux::m_demuxerId, m_displayTime, m_dtsAtDisplayTime, m_IDemux, m_packet, m_pInput, m_streams, ParsePacket(), and RequestStreams().
RequestStreams()
void CDVDDemuxClient::RequestStreams () protected
References m_IDemux, m_streams, and SetStreamProps().
Referenced by Open(), and Read().
Reset()
bool CDVDDemuxClient::Reset () override virtual
Implements CDVDDemux.
References Dispose(), m_pInput, and Open().
SeekTime()
bool CDVDDemuxClient::SeekTime (double time, bool backwards = false, double * startpts = NULL) override virtual
Implements CDVDDemux.
References DVD_NOPTS_VALUE, m_displayTime, m_dtsAtDisplayTime, and m_IDemux.
SetSpeed()
void CDVDDemuxClient::SetSpeed (int iSpeed) override virtual
Reimplemented from CDVDDemux.
References m_IDemux.
SetStreamProps()
void CDVDDemuxClient::SetStreamProps (CDemuxStream * stream, std::map< int, std::shared_ptr< CDemuxStream > > & map, bool forceInit) protected
References CDemuxStream::codec, CDemuxStream::codec_fourcc, CDemuxStream::codecName, CDemuxStreamVideo::colorPrimaries, CDemuxStreamVideo::colorRange, CDemuxStreamVideo::colorSpace, CDemuxStreamVideo::colorTransferCharacteristic, CDemuxStreamVideo::contentLightMetaData, CDemuxStream::cryptoSession, DisposeStreams(), CDemuxStream::externalInterfaces, CDemuxStream::extraData, CDemuxStreamVideo::fAspect, CDemuxStream::flags, FFmpegExtraData::GetSize(), GetStreamInternal(), CDemuxStreamVideo::iBitRate, CDemuxStreamAudio::iBitRate, CDemuxStreamAudio::iBitsPerSample, CDemuxStreamAudio::iBlockAlign, CDemuxStreamAudio::iChannels, CDemuxStreamVideo::iFpsRate, CDemuxStreamVideo::iFpsScale, CDemuxStreamVideo::iHeight, CDemuxStreamAudio::iSampleRate, CDemuxStreamVideo::iWidth, CDemuxStream::language, CDemuxStream::level, CLog::Log(), LOGDEBUG, LOGERROR, CDemuxStreamVideo::masteringMetaData, CDemuxStream::name, CDemuxStream::profile, STREAM_AUDIO, STREAM_AUDIO_ID3, STREAM_RADIO_RDS, STREAM_SUBTITLE, STREAM_TELETEXT, STREAM_VIDEO, CDemuxStream::type, and CDemuxStream::uniqueId.
Referenced by OpenStream(), and RequestStreams().
SetVideoResolution()
void CDVDDemuxClient::SetVideoResolution (unsigned int width, unsigned int height) override virtual
Reimplemented from CDVDDemux.
References m_IDemux.
Member Data Documentation
m_displayTime
int CDVDDemuxClient::m_displayTime protected
Referenced by Flush(), Open(), Read(), and SeekTime().
m_dtsAtDisplayTime
double CDVDDemuxClient::m_dtsAtDisplayTime protected
Referenced by Flush(), Open(), Read(), and SeekTime().
m_IDemux
std::shared_ptr<CDVDInputStream::IDemux> CDVDDemuxClient::m_IDemux protected
Referenced by Abort(), Dispose(), EnableStream(), FillBuffer(), Flush(), Open(), OpenStream(), Read(), RequestStreams(), SeekTime(), SetSpeed(), and SetVideoResolution().
m_packet
std::unique_ptr<DemuxPacket> CDVDDemuxClient::m_packet protected
Referenced by Read().
m_pInput
std::shared_ptr<CDVDInputStream> CDVDDemuxClient::m_pInput protected
Referenced by Dispose(), GetFileName(), Open(), Read(), and Reset().
m_streams
std::map<int, std::shared_ptr<CDemuxStream> > CDVDDemuxClient::m_streams protected
Referenced by CDVDDemuxClient(), DisposeStreams(), GetNrOfStreams(), GetStream(), GetStreamInternal(), GetStreams(), IsVideoReady(), OpenStream(), Read(), and RequestStreams().
m_videoStreamPlaying
int CDVDDemuxClient::m_videoStreamPlaying = -1 protected
Referenced by DisposeStreams(), IsVideoReady(), and OpenStream().
The documentation for this class was generated from the following files:
DVDDemuxClient.h
DVDDemuxClient.cpp