Kodi Documentation: JSONRPC::CGUIOperations Class Reference
JSONRPC::CGUIOperations Class Reference
#include <GUIOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetProperties (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ActivateWindow (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ShowNotification (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetFullscreen (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetStereoscopicMode (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetStereoscopicModes (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ActivateScreenSaver (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Static Private Member Functions
static JSONRPC_STATUS GetPropertyValue (const std::string &property, CVariant &result)
static CVariant GetStereoModeObjectFromGuiMode (const RENDER_STEREO_MODE &mode)
Member Function Documentation
ActivateScreenSaver()
JSONRPC_STATUS CGUIOperations::ActivateScreenSaver (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CServiceBroker::GetAppMessenger(), and TMSG_ACTIVATESCREENSAVER.
ActivateWindow()
JSONRPC_STATUS CGUIOperations::ActivateWindow (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::end_array(), CServiceBroker::GetAppMessenger(), JSONRPC::InvalidParams, TMSG_GUI_ACTIVATE_WINDOW, CWindowTranslator::TranslateWindow(), and WINDOW_INVALID.
GetProperties()
JSONRPC_STATUS CGUIOperations::GetProperties (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), GetPropertyValue(), index(), JSONRPC::OK, CVariant::size(), and CVariant::VariantTypeObject.
GetPropertyValue()
JSONRPC_STATUS CGUIOperations::GetPropertyValue (const std::string & property, CVariant & result) static private
References INFO::DEFAULT_CONTEXT, g_application, CServiceBroker::GetAddonMgr(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetLabel(), CServiceBroker::GetSettingsComponent(), CStereoscopicsManager::GetStereoMode(), GetStereoModeObjectFromGuiMode(), CGUIComponent::GetStereoscopicsManager(), CGUIComponent::GetWindowManager(), JSONRPC::InternalError, JSONRPC::InvalidParams, JSONRPC::OK, and CSettings::SETTING_LOOKANDFEEL_SKIN.
Referenced by GetProperties(), and SetFullscreen().
GetStereoModeObjectFromGuiMode()
CVariant CGUIOperations::GetStereoModeObjectFromGuiMode (const RENDER_STEREO_MODE & mode) static private
References CStereoscopicsManager::ConvertGuiStereoModeToString(), CServiceBroker::GetGUI(), CStereoscopicsManager::GetLabelForStereoMode(), CGUIComponent::GetStereoscopicsManager(), and CVariant::VariantTypeObject.
Referenced by GetPropertyValue(), and GetStereoscopicModes().
GetStereoscopicModes()
JSONRPC_STATUS CGUIOperations::GetStereoscopicModes (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CServiceBroker::GetRenderSystem(), GetStereoModeObjectFromGuiMode(), JSONRPC::OK, push_back(), RENDER_STEREO_MODE_COUNT, RENDER_STEREO_MODE_OFF, and CRenderSystemBase::SupportsStereo().
SetFullscreen()
JSONRPC_STATUS CGUIOperations::SetFullscreen (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ACTION_SHOW_GUI, g_application, CServiceBroker::GetAppMessenger(), GetPropertyValue(), JSONRPC::InvalidParams, TMSG_GUI_ACTION, and WINDOW_INVALID.
SetStereoscopicMode()
JSONRPC_STATUS CGUIOperations::SetStereoscopicMode (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, ACTION_NONE, CStereoscopicsManager::ConvertActionCommandToAction(), CServiceBroker::GetAppMessenger(), JSONRPC::InvalidParams, TMSG_GUI_ACTION, and WINDOW_INVALID.
ShowNotification()
JSONRPC_STATUS CGUIOperations::ShowNotification (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asString(), CGUIDialogKaiToast::Error, CGUIDialogKaiToast::Info, CGUIDialogKaiToast::QueueNotification(), and CGUIDialogKaiToast::Warning.
The documentation for this class was generated from the following files:
GUIOperations.h
GUIOperations.cpp