Kodi Documentation: KODI::RETRO::CWinRenderBufferPool Class Reference
KODI::RETRO::CWinRenderBufferPool Class Reference
#include <RPWinRenderer.h>
Public Member Functions
CWinRenderBufferPool ()
~CWinRenderBufferPool () override=default
bool IsCompatible (const CRenderVideoSettings &renderSettings) const override
IRenderBuffer * CreateRenderBuffer (void *header=nullptr) override
bool ConfigureDX ()
CRPWinOutputShader * GetShader (SCALINGMETHOD scalingMethod) const
Public Member Functions inherited from KODI::RETRO::CBaseRenderBufferPool
CBaseRenderBufferPool ()=default
~CBaseRenderBufferPool () override
void RegisterRenderer (CRPBaseRenderer *renderer) override
void UnregisterRenderer (CRPBaseRenderer *renderer) override
bool HasVisibleRenderer () const override
bool Configure (AVPixelFormat format) override
bool IsConfigured () const override
IRenderBuffer * GetBuffer (unsigned int width, unsigned int height) override
Get a free buffer from the pool, sets ref count to 1.
void Return (IRenderBuffer *buffer) override
Called by buffer when ref count goes to zero.
void Prime (unsigned int width, unsigned int height) override
void Flush () override
AVPixelFormat Format () const
Public Member Functions inherited from KODI::RETRO::IRenderBufferPool
virtual ~IRenderBufferPool ()=default
virtual DataAccess GetMemoryAccess () const
virtual DataAlignment GetMemoryAlignment () const
virtual std::shared_ptr< IRenderBufferPool > GetPtr ()
Call in GetBuffer() before returning buffer to caller.
Private Member Functions
void CompileOutputShaders ()
Static Private Member Functions
static const std::vector< SCALINGMETHOD > & GetScalingMethods ()
Private Attributes
DXGI_FORMAT m_targetDxFormat = DXGI_FORMAT_UNKNOWN
std::map< SCALINGMETHOD, std::unique_ptr< CRPWinOutputShader > > m_outputShaders
Additional Inherited Members
Protected Member Functions inherited from KODI::RETRO::CBaseRenderBufferPool
virtual bool ConfigureInternal ()
virtual void * GetHeader (unsigned int timeoutMs=0)
virtual bool GetHeaderWithTimeout (void *&header)
virtual bool SendBuffer (IRenderBuffer *buffer)
Protected Attributes inherited from KODI::RETRO::CBaseRenderBufferPool
bool m_bConfigured = false
AVPixelFormat m_format = AV_PIX_FMT_NONE
Constructor & Destructor Documentation
CWinRenderBufferPool()
CWinRenderBufferPool::CWinRenderBufferPool ()
References CompileOutputShaders().
~CWinRenderBufferPool()
KODI::RETRO::CWinRenderBufferPool::~CWinRenderBufferPool () override default
Member Function Documentation
CompileOutputShaders()
void CWinRenderBufferPool::CompileOutputShaders () private
References GetScalingMethods(), CLog::Log(), LOGERROR, m_outputShaders, and KODI::RETRO::CRenderTranslator::TranslateScalingMethod().
Referenced by CWinRenderBufferPool().
ConfigureDX()
bool CWinRenderBufferPool::ConfigureDX ()
References m_targetDxFormat.
CreateRenderBuffer()
IRenderBuffer * CWinRenderBufferPool::CreateRenderBuffer (void * header = nullptr) override virtual
Implements KODI::RETRO::CBaseRenderBufferPool.
References KODI::RETRO::CBaseRenderBufferPool::m_format, and m_targetDxFormat.
GetScalingMethods()
const std::vector< SCALINGMETHOD > & CWinRenderBufferPool::GetScalingMethods () static private
References KODI::RETRO::LINEAR, and KODI::RETRO::NEAREST.
Referenced by CompileOutputShaders().
GetShader()
CRPWinOutputShader * CWinRenderBufferPool::GetShader (SCALINGMETHOD scalingMethod) const
References m_outputShaders.
Referenced by IsCompatible(), and KODI::RETRO::CRPWinRenderer::Render().
IsCompatible()
bool CWinRenderBufferPool::IsCompatible (const CRenderVideoSettings & renderSettings) const override virtual
Implements KODI::RETRO::IRenderBufferPool.
References KODI::RETRO::CRenderVideoSettings::GetScalingMethod(), and GetShader().
Member Data Documentation
m_outputShaders
std::map<SCALINGMETHOD, std::unique_ptr<CRPWinOutputShader> > KODI::RETRO::CWinRenderBufferPool::m_outputShaders private
Referenced by CompileOutputShaders(), and GetShader().
m_targetDxFormat
DXGI_FORMAT KODI::RETRO::CWinRenderBufferPool::m_targetDxFormat = DXGI_FORMAT_UNKNOWN private
Referenced by ConfigureDX(), and CreateRenderBuffer().
The documentation for this class was generated from the following files:
RPWinRenderer.h
RPWinRenderer.cpp