Kodi Documentation: CXBTFFile Class Reference
CXBTFFile Class Reference
#include <XBTF.h>
Public Member Functions
CXBTFFile ()
const std::string & GetPath () const
void SetPath (const std::string &path)
uint32_t GetLoop () const
void SetLoop (uint32_t loop)
const std::vector< CXBTFFrame > & GetFrames () const
std::vector< CXBTFFrame > & GetFrames ()
uint64_t GetPackedSize () const
uint64_t GetUnpackedSize () const
uint64_t GetHeaderSize () const
Static Public Attributes
static const size_t MaximumPathLength = 256
Private Attributes
std::string m_path
uint32_t m_loop = 0
std::vector< CXBTFFrame > m_frames
Constructor & Destructor Documentation
CXBTFFile()
CXBTFFile::CXBTFFile ()
Member Function Documentation
GetFrames() [1/2]
std::vector< CXBTFFrame > & CXBTFFile::GetFrames ()
References m_frames.
GetFrames() [2/2]
const std::vector< CXBTFFrame > & CXBTFFile::GetFrames () const
References m_frames.
Referenced by XFILE::CXbtFile::GetFirstFrame(), CTextureBundleXBT::LoadAnim(), XFILE::CXbtFile::Open(), CXBTFReader::Open(), XFILE::CXbtFile::Read(), and XFILE::CXbtFile::Seek().
GetHeaderSize()
uint64_t CXBTFFile::GetHeaderSize () const
References m_frames, m_loop, and MaximumPathLength.
GetLoop()
uint32_t CXBTFFile::GetLoop () const
References m_loop.
GetPackedSize()
uint64_t CXBTFFile::GetPackedSize () const
References m_frames.
GetPath()
const std::string & CXBTFFile::GetPath () const
References m_path.
GetUnpackedSize()
uint64_t CXBTFFile::GetUnpackedSize () const
References m_frames.
Referenced by XFILE::CXbtFile::GetLength(), XFILE::CXbtFile::Stat(), and XFILE::XBTFFileToFileItem().
SetLoop()
void CXBTFFile::SetLoop (uint32_t loop)
References m_loop.
Referenced by CXBTFReader::Open().
SetPath()
void CXBTFFile::SetPath (const std::string & path)
References m_path.
Referenced by CXBTFReader::Open().
Member Data Documentation
m_frames
std::vector<CXBTFFrame> CXBTFFile::m_frames private
Referenced by GetFrames(), GetFrames(), GetHeaderSize(), GetPackedSize(), and GetUnpackedSize().
m_loop
uint32_t CXBTFFile::m_loop = 0 private
Referenced by GetHeaderSize(), GetLoop(), and SetLoop().
m_path
std::string CXBTFFile::m_path private
Referenced by GetPath(), and SetPath().
MaximumPathLength
const size_t CXBTFFile::MaximumPathLength = 256 static
Referenced by GetHeaderSize(), and CXBTFReader::Open().
The documentation for this class was generated from the following files:
XBTF.h
XBTF.cpp