Kodi Documentation: CRenderSystemGL Class Reference
CRenderSystemGL Class Reference abstract
#include <RenderSystemGL.h>
Public Member Functions
CRenderSystemGL ()
~CRenderSystemGL () override
bool InitRenderSystem () override
bool DestroyRenderSystem () override
bool ResetRenderSystem (int width, int height) override
bool BeginRender () override
bool EndRender () override
void PresentRender (bool rendered, bool videoLayer) override
void InvalidateColorBuffer () override
bool ClearBuffers (KODI::UTILS::COLOR::Color color) override
bool IsExtSupported (const char *extension) const override
void SetVSync (bool vsync)
void ResetVSync ()
void SetViewPort (const CRect &viewPort) override
void GetViewPort (CRect &viewPort) override
bool ScissorsCanEffectClipping () override
CRect ClipRectToScissorRect (const CRect &rect) override
void SetScissors (const CRect &rect) override
void ResetScissors () override
void SetDepthCulling (DEPTH_CULLING culling) override
void CaptureStateBlock () override
void ApplyStateBlock () override
void SetCameraPosition (const CPoint &camera, int screenWidth, int screenHeight, float stereoFactor=0.0f) override
void SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view) override
bool SupportsStereo (RENDER_STEREO_MODE mode) const override
bool SupportsNPOT (bool dxt) const override
void Project (float &x, float &y, float &z) override
std::string GetShaderPath (const std::string &filename) override
void GetGLVersion (int &major, int &minor)
void GetGLSLVersion (int &major, int &minor)
void ResetGLErrors ()
void EnableShader (ShaderMethodGL method)
void DisableShader ()
GLint ShaderGetPos ()
GLint ShaderGetCol ()
GLint ShaderGetCoord0 ()
GLint ShaderGetCoord1 ()
GLint ShaderGetDepth ()
GLint ShaderGetUniCol ()
GLint ShaderGetModel ()
GLint ShaderGetMatrix ()
GLint ShaderGetClip ()
GLint ShaderGetCoordStep ()
Public Member Functions inherited from CRenderSystemBase
CRenderSystemBase ()
virtual ~CRenderSystemBase ()
virtual void RestoreViewPort ()
void GetRenderVersion (unsigned int &major, unsigned int &minor) const
const std::string & GetRenderVendor () const
const std::string & GetRenderRenderer () const
const std::string & GetRenderVersionString () const
unsigned int GetMaxTextureSize () const
unsigned int GetMinDXTPitch () const
virtual void ShowSplash (const std::string &message)
Protected Member Functions
virtual void SetVSyncImpl (bool enable)=0
virtual void PresentRenderImpl (bool rendered)=0
void CalculateMaxTexturesize ()
void InitialiseShaders ()
void ReleaseShaders ()
Protected Attributes
bool m_bVsyncInit = false
int m_width
int m_height
std::string m_RenderExtensions
int m_glslMajor = 0
int m_glslMinor = 0
GLint m_viewPort [4]
std::map< ShaderMethodGL, std::unique_ptr< CGLShader > > m_pShader
ShaderMethodGL m_method = ShaderMethodGL::SM_DEFAULT
GLuint m_vertexArray = GL_NONE
Protected Attributes inherited from CRenderSystemBase
bool m_bRenderCreated
bool m_bVSync
unsigned int m_maxTextureSize
unsigned int m_minDXTPitch
std::string m_RenderRenderer
std::string m_RenderVendor
std::string m_RenderVersion
int m_RenderVersionMinor
int m_RenderVersionMajor
RENDER_STEREO_VIEW m_stereoView = RENDER_STEREO_VIEW_OFF
RENDER_STEREO_MODE m_stereoMode = RENDER_STEREO_MODE_OFF
bool m_limitedColorRange = false
bool m_transferPQ {false}
std::unique_ptr< CGUIImage > m_splashImage
std::unique_ptr< CGUITextLayout > m_splashMessageLayout
Constructor & Destructor Documentation
CRenderSystemGL()
CRenderSystemGL::CRenderSystemGL ()
~CRenderSystemGL()
CRenderSystemGL::~CRenderSystemGL () override default
Member Function Documentation
ApplyStateBlock()
void CRenderSystemGL::ApplyStateBlock () override virtual
Implements CRenderSystemBase.
References glMatrixModview, glMatrixProject, glMatrixTexture, CRenderSystemBase::m_bRenderCreated, m_vertexArray, m_viewPort, and CMatrixGLStack::PopLoad().
BeginRender()
bool CRenderSystemGL::BeginRender () override virtual
Implements CRenderSystemBase.
References CServiceBroker::GetWinSystem(), InitialiseShaders(), CRenderSystemBase::m_bRenderCreated, CRenderSystemBase::m_limitedColorRange, ReleaseShaders(), and CWinSystemBase::UseLimitedColor().
CalculateMaxTexturesize()
void CRenderSystemGL::CalculateMaxTexturesize () protected
References CLog::Log(), LOGERROR, LOGINFO, CRenderSystemBase::m_maxTextureSize, and ResetGLErrors().
Referenced by ResetRenderSystem().
CaptureStateBlock()
void CRenderSystemGL::CaptureStateBlock () override virtual
Implements CRenderSystemBase.
References glMatrixModview, glMatrixProject, glMatrixTexture, CRenderSystemBase::m_bRenderCreated, and CMatrixGLStack::Push().
ClearBuffers()
bool CRenderSystemGL::ClearBuffers (KODI::UTILS::COLOR::Color color) override virtual
Implements CRenderSystemBase.
References KODI::UTILS::GL::A, KODI::UTILS::GL::B, color, KODI::UTILS::GL::G, KODI::UTILS::GL::GetChannelFromARGB(), CServiceBroker::GetSettingsComponent(), CRenderSystemBase::m_bRenderCreated, CRenderSystemBase::m_stereoMode, CRenderSystemBase::m_stereoView, KODI::UTILS::GL::R, RENDER_STEREO_MODE_INTERLACED, and RENDER_STEREO_VIEW_RIGHT.
Referenced by InvalidateColorBuffer().
ClipRectToScissorRect()
CRect CRenderSystemGL::ClipRectToScissorRect (const CRect & rect) override virtual
Reimplemented from CRenderSystemBase.
References m_method, m_pShader, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUIFontTTFGL::LastEnd().
DestroyRenderSystem()
bool CRenderSystemGL::DestroyRenderSystem () override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_vertexArray, and ReleaseShaders().
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext().
DisableShader()
void CRenderSystemGL::DisableShader ()
References m_method, m_pShader, and SM_DEFAULT.
Referenced by CLinuxRendererGL::ClearBackBufferQuad(), KODI::RETRO::CRenderContext::DisableGUIShader(), CLinuxRendererGL::DrawBlackBars(), CGUITextureGL::DrawQuad(), CGUITextureGL::End(), CGUIFontTTFGL::LastEnd(), CSlideShowPicGL::Render(), OVERLAY::COverlayTextureGL::Render(), and OVERLAY::COverlayGlyphGL::Render().
EnableShader()
void CRenderSystemGL::EnableShader (ShaderMethodGL method)
References CLog::Log(), LOGERROR, m_method, and m_pShader.
Referenced by CGUITextureGL::Begin(), CLinuxRendererGL::ClearBackBufferQuad(), CLinuxRendererGL::DrawBlackBars(), CGUITextureGL::DrawQuad(), KODI::RETRO::CRenderContext::EnableGUIShader(), CGUIFontTTFGL::FirstBegin(), CSlideShowPicGL::Render(), OVERLAY::COverlayTextureGL::Render(), and OVERLAY::COverlayGlyphGL::Render().
EndRender()
bool CRenderSystemGL::EndRender () override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated.
GetGLSLVersion()
void CRenderSystemGL::GetGLSLVersion (int & major, int & minor)
References m_glslMajor, and m_glslMinor.
Referenced by OVERLAY::COverlayTextureGL::Render().
GetGLVersion()
void CRenderSystemGL::GetGLVersion (int & major, int & minor)
GetShaderPath()
std::string CRenderSystemGL::GetShaderPath (const std::string & filename) override virtual
Reimplemented from CRenderSystemBase.
References CFileUtils::Exists(), CURL::Get(), m_glslMajor, and m_glslMinor.
GetViewPort()
void CRenderSystemGL::GetViewPort (CRect & viewPort) override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_height, m_viewPort, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CLinuxRendererGL::RenderToFBO().
InitialiseShaders()
void CRenderSystemGL::InitialiseShaders () protected
References CServiceBroker::GetWinSystem(), CLog::Log(), LOGERROR, CRenderSystemBase::m_limitedColorRange, m_pShader, SM_DEFAULT, SM_FONTS, SM_FONTS_SHADER_CLIP, SM_MULTI, SM_MULTI_BLENDCOLOR, SM_TEXTURE, SM_TEXTURE_LIM, SM_TEXTURE_NOBLEND, and CWinSystemBase::UseLimitedColor().
Referenced by BeginRender(), InitRenderSystem(), and ResetRenderSystem().
InitRenderSystem()
bool CRenderSystemGL::InitRenderSystem () override virtual
Implements CRenderSystemBase.
References CServiceBroker::GetSettingsComponent(), KODI::UTILS::GL::GlErrorCallback(), InitialiseShaders(), IsExtSupported(), CLog::Log(), LOGDEBUG, LOGFATAL, LogGraphicsInfo(), LOGINFO, CRenderSystemBase::m_bRenderCreated, CRenderSystemBase::m_bVSync, m_bVsyncInit, m_glslMajor, m_glslMinor, CRenderSystemBase::m_maxTextureSize, m_RenderExtensions, CRenderSystemBase::m_RenderRenderer, CRenderSystemBase::m_RenderVendor, CRenderSystemBase::m_RenderVersion, CRenderSystemBase::m_RenderVersionMajor, CRenderSystemBase::m_RenderVersionMinor, m_vertexArray, and CGUITextureGL::Register().
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext().
InvalidateColorBuffer()
void CRenderSystemGL::InvalidateColorBuffer () override virtual
Reimplemented from CRenderSystemBase.
References ClearBuffers(), CServiceBroker::GetSettingsComponent(), CRenderSystemBase::m_bRenderCreated, CRenderSystemBase::m_stereoMode, CRenderSystemBase::m_stereoView, RENDER_STEREO_MODE_INTERLACED, and RENDER_STEREO_VIEW_RIGHT.
IsExtSupported()
bool CRenderSystemGL::IsExtSupported (const char * extension) const override virtual
Implements CRenderSystemBase.
Reimplemented in KODI::WINDOWING::X11::CWinSystemX11GLContext.
References m_RenderExtensions, CRenderSystemBase::m_RenderVersionMajor, CRenderSystemBase::m_RenderVersionMinor, and name.
Referenced by InitRenderSystem(), KODI::WINDOWING::X11::CWinSystemX11GLContext::IsExtSupported(), ResetRenderSystem(), CLinuxRendererGL::Supports(), and CLinuxRendererGL::SupportsMultiPassRendering().
PresentRender()
void CRenderSystemGL::PresentRender (bool rendered, bool videoLayer) override virtual
Implements CRenderSystemBase.
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbmGLContext.
References CRenderSystemBase::m_bRenderCreated, PresentRenderImpl(), SetVSync(), and KODI::TIME::Sleep().
PresentRenderImpl()
virtual void CRenderSystemGL::PresentRenderImpl (bool rendered) protected pure virtual
Implemented in KODI::WINDOWING::GBM::CWinSystemGbmGLContext, CWinSystemOSXGL, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL, and KODI::WINDOWING::X11::CWinSystemX11GLContext.
Referenced by PresentRender().
Project()
void CRenderSystemGL::Project (float & x, float & y, float & z) override virtual
Project (x,y,z) 3d scene coordinates to (x,y) 2d screen coordinates
Reimplemented from CRenderSystemBase.
References CMatrixGLStack::Get(), glMatrixModview, glMatrixProject, m_viewPort, and CMatrixGL::Project().
ReleaseShaders()
void CRenderSystemGL::ReleaseShaders () protected
References m_pShader, SM_DEFAULT, SM_FONTS, SM_FONTS_SHADER_CLIP, SM_MULTI, SM_MULTI_BLENDCOLOR, SM_TEXTURE, SM_TEXTURE_LIM, and SM_TEXTURE_NOBLEND.
Referenced by BeginRender(), DestroyRenderSystem(), and ResetRenderSystem().
ResetGLErrors()
void CRenderSystemGL::ResetGLErrors ()
References CLog::Log(), and LOGWARNING.
Referenced by CalculateMaxTexturesize(), and ResetRenderSystem().
ResetRenderSystem()
bool CRenderSystemGL::ResetRenderSystem (int width, int height) override virtual
Implements CRenderSystemBase.
References CalculateMaxTexturesize(), CMatrixGLStack::Clear(), glMatrixModview, glMatrixProject, glMatrixTexture, InitialiseShaders(), IsExtSupported(), CMatrixGLStack::Load(), CMatrixGL::LoadIdentity(), CLog::Log(), LOGERROR, CRenderSystemBase::m_bRenderCreated, m_height, CRenderSystemBase::m_RenderVersionMajor, CRenderSystemBase::m_RenderVersionMinor, m_vertexArray, m_width, CMatrixGL::Ortho(), ReleaseShaders(), ResetGLErrors(), and SetViewPort().
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::FinishWindowResize(), CWinSystemOSXGL::ResizeWindow(), KODI::WINDOWING::X11::CWinSystemX11GLContext::ResizeWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::SetContextSize(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::SetFullScreen(), CWinSystemOSXGL::SetFullScreen(), and KODI::WINDOWING::X11::CWinSystemX11GLContext::SetFullScreen().
ResetScissors()
void CRenderSystemGL::ResetScissors () override virtual
Implements CRenderSystemBase.
References m_height, m_width, and SetScissors().
Referenced by CGUIFontTTFGL::FirstBegin(), and CGUIFontTTFGL::LastEnd().
ResetVSync()
void CRenderSystemGL::ResetVSync () inline
References m_bVsyncInit.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow().
ScissorsCanEffectClipping()
bool CRenderSystemGL::ScissorsCanEffectClipping () override virtual
Reimplemented from CRenderSystemBase.
References m_method, and m_pShader.
Referenced by CGUIFontTTFGL::FirstBegin().
SetCameraPosition()
void CRenderSystemGL::SetCameraPosition (const CPoint & camera, int screenWidth, int screenHeight, float stereoFactor = 0.0f) override virtual
Implements CRenderSystemBase.
References CMatrixGL::Frustum(), glMatrixModview, glMatrixProject, CMatrixGLStack::Load(), CMatrixGL::LoadIdentity(), CMatrixGL::LookAt(), CRenderSystemBase::m_bRenderCreated, m_viewPort, CMatrixGL::Translatef(), CPointGen< T >::x, and CPointGen< T >::y.
SetDepthCulling()
void CRenderSystemGL::SetDepthCulling (DEPTH_CULLING culling) override virtual
Reimplemented from CRenderSystemBase.
References DEPTH_CULLING_BACK_TO_FRONT, DEPTH_CULLING_FRONT_TO_BACK, and DEPTH_CULLING_OFF.
SetScissors()
void CRenderSystemGL::SetScissors (const CRect & rect) override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_height, MathUtils::round_int(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUIFontTTFGL::LastEnd(), and ResetScissors().
SetStereoMode()
void CRenderSystemGL::SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view) override virtual
Reimplemented from CRenderSystemBase.
References CRenderSystemBase::m_stereoMode, CRenderSystemBase::m_stereoView, RENDER_STEREO_MODE_ANAGLYPH_GREEN_MAGENTA, RENDER_STEREO_MODE_ANAGLYPH_RED_CYAN, RENDER_STEREO_MODE_ANAGLYPH_YELLOW_BLUE, RENDER_STEREO_MODE_HARDWAREBASED, RENDER_STEREO_MODE_INTERLACED, RENDER_STEREO_VIEW_LEFT, RENDER_STEREO_VIEW_RIGHT, CRenderSystemBase::SetStereoMode(), and stipple_3d.
SetViewPort()
void CRenderSystemGL::SetViewPort (const CRect & viewPort) override virtual
Implements CRenderSystemBase.
References CRectGen< T >::Height(), CRenderSystemBase::m_bRenderCreated, m_height, m_viewPort, CRectGen< T >::Width(), CRectGen< T >::x1, and CRectGen< T >::y1.
Referenced by CLinuxRendererGL::RenderToFBO(), and ResetRenderSystem().
SetVSync()
void CRenderSystemGL::SetVSync (bool vsync)
References CLog::Log(), LOGINFO, CRenderSystemBase::m_bRenderCreated, CRenderSystemBase::m_bVSync, m_bVsyncInit, and SetVSyncImpl().
Referenced by PresentRender().
SetVSyncImpl()
virtual void CRenderSystemGL::SetVSyncImpl (bool enable) protected pure virtual
Implemented in KODI::WINDOWING::GBM::CWinSystemGbmGLContext, CWinSystemOSXGL, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL, and KODI::WINDOWING::X11::CWinSystemX11GLContext.
Referenced by SetVSync().
ShaderGetClip()
GLint CRenderSystemGL::ShaderGetClip ()
References m_method, and m_pShader.
Referenced by CGUIFontTTFGL::LastEnd().
ShaderGetCol()
GLint CRenderSystemGL::ShaderGetCol ()
References m_method, and m_pShader.
Referenced by CGUIFontTTFGL::LastEnd(), and OVERLAY::COverlayGlyphGL::Render().
ShaderGetCoord0()
GLint CRenderSystemGL::ShaderGetCoord0 ()
References m_method, and m_pShader.
Referenced by CGUITextureGL::DrawQuad(), CGUITextureGL::End(), KODI::RETRO::CRenderContext::GUIShaderGetCoord0(), CGUIFontTTFGL::LastEnd(), CSlideShowPicGL::Render(), OVERLAY::COverlayTextureGL::Render(), and OVERLAY::COverlayGlyphGL::Render().
ShaderGetCoord1()
GLint CRenderSystemGL::ShaderGetCoord1 ()
References m_method, and m_pShader.
Referenced by CGUITextureGL::End().
ShaderGetCoordStep()
GLint CRenderSystemGL::ShaderGetCoordStep ()
References m_method, and m_pShader.
Referenced by CGUIFontTTFGL::LastEnd().
ShaderGetDepth()
GLint CRenderSystemGL::ShaderGetDepth ()
References m_method, and m_pShader.
Referenced by CGUITextureGL::DrawQuad(), CGUITextureGL::End(), KODI::RETRO::CRenderContext::GUIShaderGetDepth(), CGUIFontTTFGL::LastEnd(), CSlideShowPicGL::Render(), OVERLAY::COverlayTextureGL::Render(), and OVERLAY::COverlayGlyphGL::Render().
ShaderGetMatrix()
GLint CRenderSystemGL::ShaderGetMatrix ()
References m_method, and m_pShader.
Referenced by CGUIFontTTFGL::LastEnd(), and OVERLAY::COverlayGlyphGL::Render().
ShaderGetModel()
GLint CRenderSystemGL::ShaderGetModel ()
References m_method, and m_pShader.
ShaderGetPos()
GLint CRenderSystemGL::ShaderGetPos ()
References m_method, and m_pShader.
Referenced by CLinuxRendererGL::ClearBackBufferQuad(), CLinuxRendererGL::DrawBlackBars(), CGUITextureGL::DrawQuad(), CGUITextureGL::End(), KODI::RETRO::CRenderContext::GUIShaderGetPos(), CGUIFontTTFGL::LastEnd(), CSlideShowPicGL::Render(), OVERLAY::COverlayTextureGL::Render(), and OVERLAY::COverlayGlyphGL::Render().
ShaderGetUniCol()
GLint CRenderSystemGL::ShaderGetUniCol ()
References m_method, and m_pShader.
Referenced by CLinuxRendererGL::ClearBackBufferQuad(), CLinuxRendererGL::DrawBlackBars(), CGUITextureGL::DrawQuad(), CGUITextureGL::End(), KODI::RETRO::CRenderContext::GUIShaderGetUniCol(), CSlideShowPicGL::Render(), and OVERLAY::COverlayTextureGL::Render().
SupportsNPOT()
bool CRenderSystemGL::SupportsNPOT (bool dxt) const override virtual
Reimplemented from CRenderSystemBase.
SupportsStereo()
bool CRenderSystemGL::SupportsStereo (RENDER_STEREO_MODE mode) const override virtual
Reimplemented from CRenderSystemBase.
References RENDER_STEREO_MODE_ANAGLYPH_GREEN_MAGENTA, RENDER_STEREO_MODE_ANAGLYPH_RED_CYAN, RENDER_STEREO_MODE_ANAGLYPH_YELLOW_BLUE, RENDER_STEREO_MODE_HARDWAREBASED, RENDER_STEREO_MODE_INTERLACED, and CRenderSystemBase::SupportsStereo().
Member Data Documentation
m_bVsyncInit
bool CRenderSystemGL::m_bVsyncInit = false protected
Referenced by InitRenderSystem(), ResetVSync(), and SetVSync().
m_glslMajor
int CRenderSystemGL::m_glslMajor = 0 protected
Referenced by GetGLSLVersion(), GetShaderPath(), and InitRenderSystem().
m_glslMinor
int CRenderSystemGL::m_glslMinor = 0 protected
Referenced by GetGLSLVersion(), GetShaderPath(), and InitRenderSystem().
m_height
int CRenderSystemGL::m_height protected
Referenced by GetViewPort(), ResetRenderSystem(), ResetScissors(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::SetContextSize(), SetScissors(), and SetViewPort().
m_method
ShaderMethodGL CRenderSystemGL::m_method = ShaderMethodGL::SM_DEFAULT protected
Referenced by ClipRectToScissorRect(), DisableShader(), EnableShader(), ScissorsCanEffectClipping(), ShaderGetClip(), ShaderGetCol(), ShaderGetCoord0(), ShaderGetCoord1(), ShaderGetCoordStep(), ShaderGetDepth(), ShaderGetMatrix(), ShaderGetModel(), ShaderGetPos(), and ShaderGetUniCol().
m_pShader
std::map<ShaderMethodGL, std::unique_ptr<CGLShader> > CRenderSystemGL::m_pShader protected
Referenced by ClipRectToScissorRect(), DisableShader(), EnableShader(), InitialiseShaders(), ReleaseShaders(), ScissorsCanEffectClipping(), ShaderGetClip(), ShaderGetCol(), ShaderGetCoord0(), ShaderGetCoord1(), ShaderGetCoordStep(), ShaderGetDepth(), ShaderGetMatrix(), ShaderGetModel(), ShaderGetPos(), and ShaderGetUniCol().
m_RenderExtensions
std::string CRenderSystemGL::m_RenderExtensions protected
Referenced by InitRenderSystem(), and IsExtSupported().
m_vertexArray
GLuint CRenderSystemGL::m_vertexArray = GL_NONE protected
Referenced by ApplyStateBlock(), DestroyRenderSystem(), InitRenderSystem(), and ResetRenderSystem().
m_viewPort
GLint CRenderSystemGL::m_viewPort[4] protected
Referenced by ApplyStateBlock(), GetViewPort(), Project(), SetCameraPosition(), and SetViewPort().
m_width
int CRenderSystemGL::m_width protected
Referenced by ResetRenderSystem(), ResetScissors(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::SetContextSize().
The documentation for this class was generated from the following files:
RenderSystemGL.h
RenderSystemGL.cpp