Kodi Documentation: AESinkWASAPI.cpp File Reference
AESinkWASAPI.cpp File Reference
#include "AESinkWASAPI.h"
#include "cores/AudioEngine/AESinkFactory.h"
#include "cores/AudioEngine/Utils/AEDeviceInfo.h"
#include "cores/AudioEngine/Utils/AEUtil.h"
#include "utils/StringUtils.h"
#include "utils/SystemInfo.h"
#include "utils/TimeUtils.h"
#include "utils/XTimeUtils.h"
#include "utils/log.h"
#include "platform/win32/WIN32Util.h"
#include <algorithm>
#include <stdint.h>
#include <Audioclient.h>
#include <Mmreg.h>
Macros
#define EXIT_ON_FAILURE(hr, reason)
Functions
DEFINE_PROPERTYKEY (PKEY_Device_FriendlyName, 0xa45c254e, 0xdf1c, 0x4efd, 0x80, 0x20, 0x67, 0xd1, 0x46, 0xa8, 0x50, 0xe0, 14)
DEFINE_PROPERTYKEY (PKEY_Device_EnumeratorName, 0xa45c254e, 0xdf1c, 0x4efd, 0x80, 0x20, 0x67, 0xd1, 0x46, 0xa8, 0x50, 0xe0, 24)
template<class T >
void SafeRelease (T **ppT)
static uint64_t rescale_u64 (uint64_t val, uint64_t num, uint64_t den)
rescale uint64_t without overflowing on large values
Variables
const IID IID_IAudioRenderClient = __uuidof(IAudioRenderClient)
const IID IID_IAudioClock = __uuidof(IAudioClock)
Macro Definition Documentation
EXIT_ON_FAILURE
#define EXIT_ON_FAILURE (hr, reason)
Value:
  if (FAILED(hr)) \
  { \
    CLog::LogF(LOGERROR, reason " - error {}", hr, CWIN32Util::FormatHRESULT(hr)); \
    goto failed; \
  }
Function Documentation
DEFINE_PROPERTYKEY() [1/2]
DEFINE_PROPERTYKEY (PKEY_Device_EnumeratorName , 0xa45c254e , 0xdf1c , 0x4efd , 0x80 , 0x20 , 0x67 , 0xd1 , 0x46 , 0xa8 , 0x50 , 0xe0 , 24)
DEFINE_PROPERTYKEY() [2/2]
DEFINE_PROPERTYKEY (PKEY_Device_FriendlyName , 0xa45c254e , 0xdf1c , 0x4efd , 0x80 , 0x20 , 0x67 , 0xd1 , 0x46 , 0xa8 , 0x50 , 0xe0 , 14)
rescale_u64()
static uint64_t rescale_u64 (uint64_t val, uint64_t num, uint64_t den) static
rescale uint64_t without overflowing on large values
Referenced by CAESinkWASAPI::GetDelay().
SafeRelease()
template<class T > void SafeRelease (T ** ppT) inline
Referenced by CAESinkWASAPI::Deinitialize(), CAESinkWASAPI::EnumerateDevicesEx(), and CAESinkWASAPI::Initialize().
Variable Documentation
IID_IAudioClock
const IID IID_IAudioClock = __uuidof(IAudioClock)
Referenced by CAESinkWASAPI::Initialize().
IID_IAudioRenderClient
const IID IID_IAudioRenderClient = __uuidof(IAudioRenderClient)
Referenced by CAESinkWASAPI::Initialize().