Kodi Documentation: KODI::PIPEWIRE::CPipewireThreadLoop Class Reference
KODI::PIPEWIRE::CPipewireThreadLoop Class Reference
#include <PipewireThreadLoop.h>
Classes
struct PipewireThreadLoopDeleter
Public Member Functions
CPipewireThreadLoop ()
~CPipewireThreadLoop ()=default
pw_loop * Get () const
bool Start ()
void Stop ()
void Lock () const
void Unlock () const
int Wait (std::chrono::nanoseconds timeout)
void Signal (bool accept)
Private Attributes
std::unique_ptr< pw_thread_loop, PipewireThreadLoopDeleter > m_mainloop
Constructor & Destructor Documentation
CPipewireThreadLoop()
CPipewireThreadLoop::CPipewireThreadLoop ()
References CLog::Log(), LOGERROR, and m_mainloop.
~CPipewireThreadLoop()
KODI::PIPEWIRE::CPipewireThreadLoop::~CPipewireThreadLoop () default
Member Function Documentation
Get()
pw_loop * KODI::PIPEWIRE::CPipewireThreadLoop::Get () const inline
References m_mainloop.
Referenced by KODI::PIPEWIRE::CPipewireContext::CPipewireContext().
Lock()
void CPipewireThreadLoop::Lock () const
References m_mainloop.
Referenced by KODI::PIPEWIRE::CLoopLockGuard::CLoopLockGuard().
Signal()
void CPipewireThreadLoop::Signal (bool accept)
References m_mainloop.
Referenced by KODI::PIPEWIRE::CPipewireCore::OnCoreDone(), KODI::PIPEWIRE::CPipewireNode::Param(), and KODI::PIPEWIRE::CPipewireStream::Process().
Start()
bool CPipewireThreadLoop::Start ()
References m_mainloop.
Stop()
void CPipewireThreadLoop::Stop ()
References m_mainloop.
Unlock()
void CPipewireThreadLoop::Unlock () const
References m_mainloop.
Referenced by KODI::PIPEWIRE::CLoopLockGuard::~CLoopLockGuard().
Wait()
int CPipewireThreadLoop::Wait (std::chrono::nanoseconds timeout)
References m_mainloop.
Member Data Documentation
m_mainloop
std::unique_ptr<pw_thread_loop, PipewireThreadLoopDeleter> KODI::PIPEWIRE::CPipewireThreadLoop::m_mainloop private
Referenced by CPipewireThreadLoop(), Get(), Lock(), Signal(), Start(), Stop(), Unlock(), and Wait().
The documentation for this class was generated from the following files:
PipewireThreadLoop.h
PipewireThreadLoop.cpp