Kodi Documentation: RSSDirectory.cpp File Reference
RSSDirectory.cpp File Reference
#include "RSSDirectory.h"
#include "CurlFile.h"
#include "FileItem.h"
#include "FileItemList.h"
#include "ServiceBroker.h"
#include "URL.h"
#include "settings/AdvancedSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/FileExtensionProvider.h"
#include "utils/HTMLUtil.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/XBMCTinyXML2.h"
#include "utils/XMLUtils.h"
#include "utils/log.h"
#include "video/VideoInfoTag.h"
#include <climits>
#include <mutex>
#include <utility>
Classes
struct anonymous_namespace{RSSDirectory.cpp}::SResource
Namespaces
namespace anonymous_namespace{RSSDirectory.cpp}
Typedefs
typedef std::vector< SResource > anonymous_namespace{RSSDirectory.cpp}::SResources
Functions
static bool IsPathToMedia (const std::string &strPath)
static bool IsPathToThumbnail (const std::string &strPath)
static time_t ParseDate (const std::string &strDate)
static void ParseItem (CFileItem *item, SResources &resources, tinyxml2::XMLElement *root, const std::string &path)
static std::string GetValue (tinyxml2::XMLElement *element)
static void ParseItemMRSS (CFileItem *item, SResources &resources, tinyxml2::XMLElement *item_child, const std::string &name, const std::string &xmlns, const std::string &path)
static void ParseItemItunes (CFileItem *item, SResources &resources, tinyxml2::XMLElement *item_child, const std::string &name, const std::string &xmlns, const std::string &path)
static void ParseItemRSS (CFileItem *item, SResources &resources, tinyxml2::XMLElement *item_child, const std::string &name, const std::string &xmlns, const std::string &path)
static void ParseItemVoddler (CFileItem *item, SResources &resources, tinyxml2::XMLElement *element, const std::string &name, const std::string &xmlns, const std::string &path)
static void ParseItemBoxee (CFileItem *item, SResources &resources, tinyxml2::XMLElement *element, const std::string &name, const std::string &xmlns, const std::string &path)
static void ParseItemZink (CFileItem *item, SResources &resources, tinyxml2::XMLElement *element, const std::string &name, const std::string &xmlns, const std::string &path)
static void ParseItemSVT (CFileItem *item, SResources &resources, tinyxml2::XMLElement *element, const std::string &name, const std::string &xmlns, const std::string &path)
static bool FindMime (const SResources &resources, const std::string &mime)
static void ParseItem (CFileItem *item, tinyxml2::XMLElement *root, const std::string &path)
Function Documentation
FindMime()
static bool FindMime (const SResources & resources, const std::string & mime) static
Referenced by ParseItem().
GetValue()
static std::string GetValue (tinyxml2::XMLElement * element) static
Referenced by KODI::GAME::CGameClient::CGameClient(), ADDON::CRepository::CRepository(), ADDON::IAddonInstanceHandler::get_instance_setting_string(), ADDON::Interface_Base::get_setting_string(), ADDON::Interface_Filesystem::http_header_get_value(), CGUIControlRadioButtonSetting::OnClick(), CApplicationSkinHandling::OnSettingChanged(), CApplicationVolumeHandling::OnSettingChanged(), KODI::GAME::CGameSettings::OnSettingChanged(), CInputManager::OnSettingChanged(), CLangInfo::OnSettingChanged(), PVR::CGUIDialogPVRTimerSettings::OnSettingChanged(), PVR::CPVRGUIActionListener::OnSettingChanged(), CAdvancedSettings::OnSettingChanged(), CGUIDialogLibExportSettings::OnSettingChanged(), CGUIDialogCMSSettings::OnSettingChanged(), CNetworkServices::OnSettingChanging(), CDisplaySettings::OnSettingChanging(), CGUIAudioManager::OnSettingUpdate(), ParseItemBoxee(), ParseItemItunes(), ParseItemMRSS(), ParseItemRSS(), ParseItemSVT(), ParseItemVoddler(), ParseItemZink(), CSettingsValueFlatJsonSerializer::SerializeSettingValue(), CDisplaySettings::SettingOptionsRefreshRatesFiller(), CLangInfo::SettingOptionsRegionsFiller(), CSettingsManager::ToggleBool(), CGUIControlRadioButtonSetting::Update(), and CGUIControlColorButtonSetting::Update().
IsPathToMedia()
static bool IsPathToMedia (const std::string & strPath) static
References CServiceBroker::GetFileExtensionProvider(), and URIUtils::HasExtension().
Referenced by ParseItemRSS().
IsPathToThumbnail()
static bool IsPathToThumbnail (const std::string & strPath) static
References CServiceBroker::GetFileExtensionProvider(), and URIUtils::HasExtension().
Referenced by ParseItemMRSS(), and ParseItemVoddler().
ParseDate()
static time_t ParseDate (const std::string & strDate) static
Todo:
Handle time zone
References strptime().
Referenced by ParseItemRSS().
ParseItem() [1/2]
static void ParseItem (CFileItem * item, SResources & resources, tinyxml2::XMLElement * root, const std::string & path) static
References name, ParseItemBoxee(), ParseItemItunes(), ParseItemMRSS(), ParseItemRSS(), ParseItemSVT(), ParseItemVoddler(), ParseItemZink(), and root.
Referenced by XFILE::CRSSDirectory::GetDirectory(), ParseItem(), and ParseItemMRSS().
ParseItem() [2/2]
static void ParseItem (CFileItem * item, tinyxml2::XMLElement * root, const std::string & path) static
References CVariant::asString(), FindMime(), CVideoInfoTag::GetDuration(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CServiceBroker::GetSettingsComponent(), CFileItem::GetVideoInfoTag(), CGUIListItem::HasProperty(), CFileItem::HasVideoInfoTag(), CGUIListItem::m_bIsFolder, CFileItem::m_dwSize, CVideoInfoTag::m_strPlot, CVideoInfoTag::m_strPlotOutline, CFileItem::m_strTitle, ParseItem(), root, CVideoInfoTag::SetDuration(), CFileItem::SetLabel(), CGUIListItem::SetLabel2(), CFileItem::SetMimeType(), CFileItem::SetPath(), CGUIListItem::SetProperty(), and CSettings::SETTING_NETWORK_BANDWIDTH.
ParseItemBoxee()
static void ParseItemBoxee (CFileItem * item, SResources & resources, tinyxml2::XMLElement * element, const std::string & name, const std::string & xmlns, const std::string & path) static
References GetValue(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_strShowTitle, name, CGUIListItem::SetArt(), CVideoInfoTag::SetDuration(), CFileItem::SetMimeType(), CVideoInfoTag::SetPlayCount(), CGUIListItem::SetProperty(), and text.
Referenced by ParseItem().
ParseItemItunes()
static void ParseItemItunes (CFileItem * item, SResources & resources, tinyxml2::XMLElement * item_child, const std::string & name, const std::string & xmlns, const std::string & path) static
References GetValue(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::m_strPlot, CVideoInfoTag::m_strPlotOutline, CVideoInfoTag::m_writingCredits, name, CGUIListItem::SetArt(), CVideoInfoTag::SetDuration(), CGUIListItem::SetProperty(), and text.
Referenced by ParseItem().
ParseItemMRSS()
static void ParseItemMRSS (CFileItem * item, SResources & resources, tinyxml2::XMLElement * item_child, const std::string & name, const std::string & xmlns, const std::string & path) static
References XMLUtils::GetAttribute(), CServiceBroker::GetSettingsComponent(), GetValue(), CFileItem::GetVideoInfoTag(), IsPathToThumbnail(), CVideoInfoTag::m_cast, CVideoInfoTag::m_director, CVideoInfoTag::m_genre, CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_strMPAARating, CVideoInfoTag::m_strShowTitle, CFileItem::m_strTitle, CVideoInfoTag::m_studio, CVideoInfoTag::m_writingCredits, name, ParseItem(), HTML::CHTMLUtil::RemoveTags(), CGUIListItem::SetArt(), CVideoInfoTag::SetPlayCount(), CGUIListItem::SetProperty(), CVideoInfoTag::SetRating(), SActorInfo::strName, and text.
Referenced by ParseItem().
ParseItemRSS()
static void ParseItemRSS (CFileItem * item, SResources & resources, tinyxml2::XMLElement * item_child, const std::string & name, const std::string & xmlns, const std::string & path) static
References XMLUtils::GetAttribute(), GetValue(), IsPathToMedia(), CFileItem::m_dateTime, CFileItem::m_strTitle, name, ParseDate(), HTML::CHTMLUtil::RemoveTags(), CGUIListItem::SetProperty(), and text.
Referenced by ParseItem().
ParseItemSVT()
static void ParseItemSVT (CFileItem * item, SResources & resources, tinyxml2::XMLElement * element, const std::string & name, const std::string & xmlns, const std::string & path) static
References CURL::GetFileName(), GetValue(), CURL::GetWithoutFilename(), name, and text.
Referenced by ParseItem().
ParseItemVoddler()
static void ParseItemVoddler (CFileItem * item, SResources & resources, tinyxml2::XMLElement * element, const std::string & name, const std::string & xmlns, const std::string & path) static
References XMLUtils::GetAttribute(), GetValue(), CFileItem::GetVideoInfoTag(), IsPathToThumbnail(), CVideoInfoTag::m_strTagLine, CVideoInfoTag::m_strTrailer, name, CGUIListItem::SetArt(), CVideoInfoTag::SetRating(), CVideoInfoTag::SetYear(), and text.
Referenced by ParseItem().
ParseItemZink()
static void ParseItemZink (CFileItem * item, SResources & resources, tinyxml2::XMLElement * element, const std::string & name, const std::string & xmlns, const std::string & path) static
References GetValue(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::m_firstAired, CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iSeason, name, CVideoInfoTag::SetDuration(), CDateTime::SetFromDateString(), CVideoInfoTag::SetPlayCount(), CVideoInfoTag::SetRating(), and text.
Referenced by ParseItem().