Kodi Documentation: Win32SMBDirectory.cpp File Reference
Win32SMBDirectory.cpp File Reference
#include "Win32SMBDirectory.h"
#include "FileItem.h"
#include "FileItemList.h"
#include "PasswordManager.h"
#include "ServiceBroker.h"
#include "URL.h"
#include "utils/CharsetConverter.h"
#include "utils/XTimeUtils.h"
#include "utils/log.h"
#include "platform/win32/CharsetConverter.h"
#include "platform/win32/WIN32Util.h"
#include "platform/win32/network/WSDiscoveryWin32.h"
#include <Windows.h>
#include <Winnetwk.h>
#include <lm.h>
#include <cassert>
Functions
static bool worthTryToConnect (const DWORD lastErr)
static bool localGetNetworkResources (struct _NETRESOURCEW *basePathToScanPtr, const std::string &urlPrefixForItems, CFileItemList &items, bool getShares)
static bool localGetShares (const std::wstring &serverNameToScan, const std::string &urlPrefixForItems, CFileItemList &items)
static bool localGetServers (const std::string &urlPrefixForItems, CFileItemList &items)
static std::wstring prepareWin32SMBDirectoryName (const CURL &url)
Function Documentation
localGetNetworkResources()
static bool localGetNetworkResources (struct _NETRESOURCEW * basePathToScanPtr, const std::string & urlPrefixForItems, CFileItemList & items, bool getShares) static
Get servers recursively or get shares from specific server
Parameters
basePathToScanPtr the pointer to start point for scan
urlPrefixForItems path prefix to be putted into list items
items the list of the collected items
getShares set to true to get shares, set for false to get servers
Returns
true if succeed, false otherwise
References CFileItemList::Add(), g_charsetConverter, localGetNetworkResources(), localGetServers(), localGetShares(), CLog::Log(), LOGERROR, LOGINFO, and LOGWARNING.
Referenced by XFILE::CWin32SMBDirectory::GetNetworkResources(), and localGetNetworkResources().
localGetServers()
static bool localGetServers (const std::string & urlPrefixForItems, CFileItemList & items) static
References CFileItemList::Add(), g_charsetConverter, WSDiscovery::CWSDiscoveryWindows::GetServersIPs(), CServiceBroker::GetWSDiscovery(), WSDiscovery::CWSDiscoveryWindows::IsRunning(), WSDiscovery::CWSDiscoveryWindows::ResolveHostName(), and WSDiscovery::CWSDiscoveryWindows::ThereAreServers().
Referenced by localGetNetworkResources().
localGetShares()
static bool localGetShares (const std::wstring & serverNameToScan, const std::string & urlPrefixForItems, CFileItemList & items) static
References CFileItemList::Add(), CFileItemList::Append(), and g_charsetConverter.
Referenced by localGetNetworkResources().
prepareWin32SMBDirectoryName()
static std::wstring prepareWin32SMBDirectoryName (const CURL & url) inline static
References CWIN32Util::ConvertPathToWin32Form(), CURL::GetFileName(), CURL::GetHostName(), CURL::GetShareName(), and CURL::IsProtocol().
Referenced by XFILE::CWin32SMBDirectory::RealCreate(), XFILE::CWin32SMBDirectory::RealExists(), and XFILE::CWin32SMBDirectory::Remove().
worthTryToConnect()
static bool worthTryToConnect (const DWORD lastErr) inline static
Referenced by XFILE::CWin32SMBFile::Delete(), XFILE::CWin32SMBFile::Exists(), XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CWin32SMBFile::Open(), XFILE::CWin32SMBFile::OpenForWrite(), XFILE::CWin32SMBDirectory::RealCreate(), XFILE::CWin32SMBDirectory::RealExists(), XFILE::CWin32SMBDirectory::Remove(), XFILE::CWin32SMBFile::Rename(), XFILE::CWin32SMBFile::SetHidden(), and XFILE::CWin32SMBFile::Stat().