Kodi Documentation: KODI::RETRO::CRenderSettings Class Reference
KODI::RETRO::CRenderSettings Class Reference
#include <RenderSettings.h>
Public Member Functions
CRenderSettings ()
void Reset ()
bool operator== (const CRenderSettings &rhs) const
bool operator< (const CRenderSettings &rhs) const
CRenderVideoSettings & VideoSettings ()
const CRenderVideoSettings & VideoSettings () const
Private Attributes
CRenderVideoSettings m_videoSettings
Constructor & Destructor Documentation
CRenderSettings()
KODI::RETRO::CRenderSettings::CRenderSettings () inline
References Reset().
Member Function Documentation
operator<()
bool CRenderSettings::operator< (const CRenderSettings & rhs) const
References m_videoSettings.
operator==()
bool CRenderSettings::operator== (const CRenderSettings & rhs) const
References m_videoSettings.
Reset()
void CRenderSettings::Reset ()
References m_videoSettings, and KODI::RETRO::CRenderVideoSettings::Reset().
Referenced by CRenderSettings(), and KODI::RETRO::CGUIRenderSettings::Reset().
VideoSettings() [1/2]
CRenderVideoSettings & KODI::RETRO::CRenderSettings::VideoSettings () inline
References m_videoSettings.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings(), KODI::RETRO::CRPRenderManager::GetRendererForPool(), KODI::RETRO::CRPRenderManager::GetRendererForSettings(), KODI::RETRO::CRPBaseRenderer::ManageRenderArea(), KODI::RETRO::CRPWinRenderer::Render(), KODI::RETRO::CGUIRenderSettings::SetPixels(), KODI::RETRO::CRPBaseRenderer::SetPixels(), KODI::RETRO::CRPBaseRenderer::SetRenderRotation(), KODI::RETRO::CGUIRenderSettings::SetRotationDegCCW(), KODI::RETRO::CRPBaseRenderer::SetScalingMethod(), KODI::RETRO::CGUIRenderSettings::SetStretchMode(), KODI::RETRO::CRPBaseRenderer::SetStretchMode(), KODI::RETRO::CGUIRenderSettings::SetVideoFilter(), and KODI::RETRO::CGUIGameSettings::UpdateSettings().
VideoSettings() [2/2]
const CRenderVideoSettings & KODI::RETRO::CRenderSettings::VideoSettings () const inline
References m_videoSettings.
Member Data Documentation
m_videoSettings
CRenderVideoSettings KODI::RETRO::CRenderSettings::m_videoSettings private
Referenced by operator<(), operator==(), Reset(), VideoSettings(), and VideoSettings().
The documentation for this class was generated from the following files:
RenderSettings.h
RenderSettings.cpp