Kodi Documentation: KODI::VIDEO::UTILS Namespace Reference
KODI::VIDEO::UTILS Namespace Reference
Namespaces
namespace anonymous_namespace{VideoGUIUtils.cpp}
Classes
struct ResumeInformation
Enumerations
enum class QueuePosition { POSITION_BEGIN , POSITION_END }
Functions
void PlayItem (const std::shared_ptr< CFileItem > &item, const std::string &player, ContentUtils::PlayMode mode=ContentUtils::PlayMode::CHECK_AUTO_PLAY_NEXT_ITEM)
Start playback of the given item. If the item is a folder, build a playlist with all items contained in the folder and start playback of the playlist. If item is a single video item, start playback directly, without adding it to the video playlist first.
void QueueItem (const std::shared_ptr< CFileItem > &item, QueuePosition pos)
Queue the given item in the currently active playlist. If no playlist is active, put the item into the video playlist.
bool GetItemsForPlayList (const std::shared_ptr< CFileItem > &item, CFileItemList &queuedItems)
For a given item, get the items to put in a playlist. If the item is a folder, all subitems will be added recursively to the returned item list. If the item is a playlist, the playlist will be loaded and contained items will be added to the returned item list. Shows a busy dialog if action takes certain amount of time to give the user visual feedback.
bool IsItemPlayable (const CFileItem &item)
Check whether the given item can be played by the app playlist player as one or more videos.
bool HasItemVideoDbInformation (const CFileItem &item)
Check whether for the given item information is stored in the video database.
std::string GetResumeString (const CFileItem &item)
Get a localized resume string for the given item, if it is resumable.
std::string FindTrailer (const CFileItem &item)
Find a local trailer file for a given file item.
std::string GetOpticalMediaPath (const CFileItem &item)
Check whether an item is an optical media folder or its parent. This will return the non-empty path to the playable entry point of the media one or two levels down (VIDEO_TS.IFO for DVDs or index.bdmv for BDs). The returned path will be empty if folder does not meet this criterion.
bool IsAutoPlayNextItem (const CFileItem &item)
Check whether auto play next item is set for the media type of the given item.
bool IsAutoPlayNextItem (const std::string &content)
Check whether auto play next item is set for the given content type.
ResumeInformation GetItemResumeInformation (const CFileItem &item)
Check whether playback of the given item can be resumed, get detailed information.
ResumeInformation GetStackPartResumeInformation (const CFileItem &item, unsigned int partNumber)
Get resume information for a part of a stack item.
Enumeration Type Documentation
QueuePosition
enum class KODI::VIDEO::UTILS::QueuePosition strong
Enumerator
POSITION_BEGIN
POSITION_END
Function Documentation
FindTrailer()
std::string KODI::VIDEO::UTILS::FindTrailer (const CFileItem & item)
Find a local trailer file for a given file item.
Returns
non-empty string with path of trailer if found
References URIUtils::AddFileToFolder(), CRegExp::autoUtf8, XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, XFILE::DIR_FLAG_READ_CACHE, XFILE::CDirectory::GetDirectory(), URIUtils::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), URIUtils::GetFileName(), XFILE::CStackDirectory::GetFirstStackedFile(), URIUtils::GetParentPath(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), XFILE::CStackDirectory::GetStackedTitlePath(), KODI::ART::GetTBNFile(), URIUtils::IsBluray(), CFileItem::IsDVD(), URIUtils::IsInRAR(), KODI::NETWORK::IsInternetStream(), URIUtils::IsInZIP(), CFileItem::IsLiveTV(), CFileItem::IsPlugin(), CFileItem::IsStack(), URIUtils::IsUPnP(), CRegExp::RegComp(), URIUtils::RemoveExtension(), URIUtils::ReplaceExtension(), and CFileItemList::Size().
Referenced by CGUIDialogVideoInfo::SetMovie(), and TEST_P().
GetItemResumeInformation()
ResumeInformation KODI::VIDEO::UTILS::GetItemResumeInformation (const CFileItem & item)
Check whether playback of the given item can be resumed, get detailed information.
Parameters
item The item to retrieve information for
Returns
The resume information.
Referenced by CONTEXTMENU::CFavouritesTargetPlay::GetLabel(), CONTEXTMENU::CVideoPlay::GetLabel(), GetResumeString(), GetStackPartResumeInformation(), CONTEXTMENU::CFavouritesTargetResume::IsVisible(), CONTEXTMENU::CVideoRemoveResumePoint::IsVisible(), CONTEXTMENU::CVideoResume::IsVisible(), CGUIWindowVideoBase::OnPlayStackPart(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), PVR::CPVRGUIActionsPlayback::ResumePlayRecording(), and CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::SetPathAndPlay().
GetItemsForPlayList()
bool KODI::VIDEO::UTILS::GetItemsForPlayList (const std::shared_ptr< CFileItem > & item, CFileItemList & queuedItems) private
For a given item, get the items to put in a playlist. If the item is a folder, all subitems will be added recursively to the returned item list. If the item is a playlist, the playlist will be loaded and contained items will be added to the returned item list. Shows a busy dialog if action takes certain amount of time to give the user visual feedback.
Parameters
item [in] the item to add to the playlist
queuedItems [out] the items that can be put in a play list
Returns
true on success, false otherwise
References CGUIDialogBusy::Wait().
Referenced by KODI::anonymous_namespace{VideoGUIUtils.cpp}::AddItemToPlayListAndPlay(), anonymous_namespace{PlayerBuiltins.cpp}::GetItemsForPlayList(), CGUIWindowVideoBase::PlayItem(), PVR::CPVRGUIActionsPlayback::PlayRecording(), PVR::CPVRGUIActionsPlayback::PlayRecordingFolder(), and QueueItem().
GetOpticalMediaPath()
std::string KODI::VIDEO::UTILS::GetOpticalMediaPath (const CFileItem & item)
Check whether an item is an optical media folder or its parent. This will return the non-empty path to the playable entry point of the media one or two levels down (VIDEO_TS.IFO for DVDs or index.bdmv for BDs). The returned path will be empty if folder does not meet this criterion.
Returns
non-empty string if item is optical media folder, empty otherwise.
References URIUtils::AddFileToFolder(), exists(), CFileUtils::Exists(), and CFileItem::GetPath().
Referenced by KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CFileItem::IsBluray(), CGUIWindowVideoBase::OnItemInfo(), CFileItemList::StackFolders(), and TEST_P().
GetResumeString()
std::string KODI::VIDEO::UTILS::GetResumeString (const CFileItem & item) private
Get a localized resume string for the given item, if it is resumable.
Parameters
item The item to retrieve the resume string for
Returns
The resume string or empty string in case the item is not resumable.
References CUtil::ConvertMilliSecsToSecsInt(), g_localizeStrings, CLocalizeStrings::Get(), GetItemResumeInformation(), KODI::VIDEO::UTILS::ResumeInformation::isResumable, KODI::VIDEO::UTILS::ResumeInformation::partNumber, KODI::VIDEO::UTILS::ResumeInformation::startOffset, and TIME_FORMAT_HH_MM_SS.
Referenced by KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::ChoosePlayOrResume(), CONTEXTMENU::CFavouritesTargetResume::GetLabel(), and CONTEXTMENU::CVideoResume::GetLabel().
GetStackPartResumeInformation()
ResumeInformation KODI::VIDEO::UTILS::GetStackPartResumeInformation (const CFileItem & item, unsigned int partNumber)
Get resume information for a part of a stack item.
Parameters
item The stack item to retrieve information for
partNumber The number of the part
Returns
The resume information.
References XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::GetDirectory(), CFileItem::GetDynPath(), GetItemResumeInformation(), CVideoDatabase::GetStackTimes(), URIUtils::IsDiscImageStack(), KODI::VIDEO::UTILS::ResumeInformation::isResumable, CFileItem::IsStack(), LOGERROR, CVideoDatabase::Open(), KODI::VIDEO::UTILS::ResumeInformation::partNumber, and KODI::VIDEO::UTILS::ResumeInformation::startOffset.
HasItemVideoDbInformation()
bool KODI::VIDEO::UTILS::HasItemVideoDbInformation (const CFileItem & item) private
Check whether for the given item information is stored in the video database.
Parameters
item The item to check
Returns
True if info is available, false otherwise.
References URIUtils::GetDirectory(), CFileItem::GetDynPath(), CFileItem::GetPath(), CVideoDatabase::HasEpisodeInfo(), CVideoDatabase::HasMovieInfo(), CVideoDatabase::HasMusicVideoInfo(), CVideoDatabase::HasTvShowInfo(), LOGERROR, and CVideoDatabase::Open().
Referenced by CGUIWindowVideoBase::OnItemInfo(), and KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::Process().
IsAutoPlayNextItem() [1/2]
bool KODI::VIDEO::UTILS::IsAutoPlayNextItem (const CFileItem & item)
Check whether auto play next item is set for the media type of the given item.
Parameters
item [in] the item to check
Returns
True if auto play next item is active, false otherwise.
References CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), IsAutoPlayNextItem(), and CVideoInfoTag::m_type.
Referenced by CGUIViewState::AutoPlayNextVideoItem(), CONTEXTMENU::CVideoPlayAndQueue::Execute(), CGUIWindowVideoBase::GetContextButtons(), CONTEXTMENU::CVideoPlayAndQueue::GetLabel(), IsAutoPlayNextItem(), PlayItem(), and PVR::CPVRGUIActionsPlayback::PlayRecording().
IsAutoPlayNextItem() [2/2]
bool KODI::VIDEO::UTILS::IsAutoPlayNextItem (const std::string & content)
Check whether auto play next item is set for the given content type.
Parameters
item [in] the content to check
Returns
True if auto play next item is active, false otherwise.
References CSettingUtils::FindIntInList(), CServiceBroker::GetSettingsComponent(), MediaTypeEpisode, MediaTypeEpisodes, MediaTypeMovie, MediaTypeMovies, MediaTypeMusicVideo, MediaTypeMusicVideos, MediaTypeSeasons, MediaTypeTvShow, MediaTypeTvShows, MediaTypeVideoCollections, CSettings::SETTING_AUTOPLAYNEXT_EPISODES, CSettings::SETTING_AUTOPLAYNEXT_MOVIES, CSettings::SETTING_AUTOPLAYNEXT_MUSICVIDEOS, CSettings::SETTING_AUTOPLAYNEXT_TVSHOWS, CSettings::SETTING_AUTOPLAYNEXT_UNCATEGORIZED, and CSettings::SETTING_VIDEOPLAYER_AUTOPLAYNEXTITEM.
IsItemPlayable()
bool KODI::VIDEO::UTILS::IsItemPlayable (const CFileItem & item) private
Check whether the given item can be played by the app playlist player as one or more videos.
Parameters
item The item to check
Returns
True if playable, false otherwise.
References CFileItem::CanQueue(), XFILE::CVideoDatabaseDirectory::GetDirectoryParentType(), CServiceBroker::GetGUI(), CFileItem::GetMimeType(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), CFileItem::HasVideoInfoTag(), CFileItem::IsAddonsPath(), KODI::MUSIC::IsCDDA(), CFileItem::IsDeleted(), CFileItem::IsDVD(), CFileItem::IsEPG(), CFileItem::IsLiveTV(), KODI::MUSIC::IsMusicDb(), CFileItem::IsParentFolder(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsPlugin(), URIUtils::IsPVRRecordingFileOrFolder(), CFileItem::IsScript(), KODI::VIDEO::IsVideo(), KODI::VIDEO::IsVideoDb(), CGUIListItem::m_bIsFolder, node, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MOVIES_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TVSHOWS_OVERVIEW, CSettings::SETTING_SYSTEM_PLAYLISTSPATH, and WINDOW_VIDEO_NAV.
Referenced by anonymous_namespace{PlayerBuiltins.cpp}::GetItemsForPlayList(), CPlayerUtils::IsItemPlayable(), CONTEXTMENU::CVideoBrowse::IsVisible(), CONTEXTMENU::CVideoPlay::IsVisible(), CONTEXTMENU::CVideoPlayUsing::IsVisible(), CONTEXTMENU::CVideoQueue::IsVisible(), CONTEXTMENU::CVideoPlayNext::IsVisible(), CGUIWindowFavourites::OnAction(), and CDirectoryProvider::OnPlay().
PlayItem()
void KODI::VIDEO::UTILS::PlayItem (const std::shared_ptr< CFileItem > & item, const std::string & player, ContentUtils::PlayMode mode = ContentUtils::PlayMode::CHECK_AUTO_PLAY_NEXT_ITEM) private
Start playback of the given item. If the item is a folder, build a playlist with all items contained in the folder and start playback of the playlist. If item is a single video item, start playback directly, without adding it to the video playlist first.
Parameters
item [in] the item to play
player [in] the player to use, empty for default player
mode [in] queue all successors and play them after item
References ContentUtils::CHECK_AUTO_PLAY_NEXT_ITEM, URIUtils::GetParentPath(), CServiceBroker::GetPlaylistPlayer(), IsAutoPlayNextItem(), LOGERROR, ContentUtils::PLAY_FROM_HERE, STARTOFFSET_RESUME, and KODI::PLAYLIST::TYPE_NONE.
Referenced by CONTEXTMENU::CVideoPlayAndQueue::Execute(), anonymous_namespace{GUIDialogVideoInfo.cpp}::CVideoPlayActionProcessor::Play(), anonymous_namespace{GUIDialogVideoManager.cpp}::CVideoPlayActionProcessor::Play(), and CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoPlayActionProcessor::Play().
QueueItem()
void KODI::VIDEO::UTILS::QueueItem (const std::shared_ptr< CFileItem > & item, QueuePosition pos) private
Queue the given item in the currently active playlist. If no playlist is active, put the item into the video playlist.
Parameters
item [in] the item to queue
pos [in] whether to place the item and the begin or the end of the queue
References CPartyModeManager::AddUserSongs(), g_partyModeManager, CServiceBroker::GetAppComponents(), GetItemsForPlayList(), CServiceBroker::GetPlaylistPlayer(), CPartyModeManager::IsEnabled(), CApplicationPlayer::IsPlaying(), PARTYMODECONTEXT_VIDEO, POSITION_BEGIN, KODI::PLAYLIST::TYPE_NONE, and KODI::PLAYLIST::TYPE_VIDEO.
Referenced by CONTEXTMENU::CVideoQueue::Execute(), CONTEXTMENU::CVideoPlayNext::Execute(), CGUIWindowVideoBase::OnQueueItem(), and anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnQueueSelected().