Kodi Documentation: PVR::CPVRGUIDirectory Class Reference
PVR::CPVRGUIDirectory Class Reference
#include <PVRGUIDirectory.h>
Public Member Functions
CPVRGUIDirectory (const CURL &url)
PVR GUI directory ctor.
CPVRGUIDirectory (const std::string &path)
PVR GUI directory ctor.
virtual ~CPVRGUIDirectory ()=default
PVR GUI directory dtor.
bool Exists () const
Check existence of this directory.
bool GetDirectory (CFileItemList &results) const
Obtain the directory listing.
bool SupportsWriteFileOperations () const
Check if this directory supports file write operations.
bool GetChannelsDirectory (CFileItemList &results) const
Get the list of channels.
bool GetProvidersDirectory (CFileItemList &results) const
Get the list of providers.
Static Public Member Functions
static bool HasTVRecordings ()
Check if any TV recordings are existing.
static bool HasDeletedTVRecordings ()
Check if any deleted TV recordings are existing.
static bool HasRadioRecordings ()
Check if any radio recordings are existing.
static bool HasDeletedRadioRecordings ()
Check if any deleted radio recordings are existing.
static bool GetChannelGroupsDirectory (bool bRadio, bool bExcludeHidden, CFileItemList &results)
Get the list of channel groups.
static bool GetRecordingsDirectoryInfo (CFileItem &item)
Get info for a recording folder.
Private Member Functions
bool GetTimersDirectory (CFileItemList &results) const
bool GetRecordingsDirectory (CFileItemList &results) const
bool GetSavedSearchesDirectory (bool bRadio, CFileItemList &results) const
bool GetSavedSearchResults (bool isRadio, int id, CFileItemList &results) const
Private Attributes
const CURL m_url
Constructor & Destructor Documentation
CPVRGUIDirectory() [1/2]
PVR::CPVRGUIDirectory::CPVRGUIDirectory (const CURL & url) inline explicit
PVR GUI directory ctor.
Parameters
url The directory's URL.
CPVRGUIDirectory() [2/2]
PVR::CPVRGUIDirectory::CPVRGUIDirectory (const std::string & path) inline explicit
PVR GUI directory ctor.
Parameters
path The directory's path.
~CPVRGUIDirectory()
virtual PVR::CPVRGUIDirectory::~CPVRGUIDirectory () virtual default
PVR GUI directory dtor.
Member Function Documentation
Exists()
bool CPVRGUIDirectory::Exists () const
Check existence of this directory.
Returns
True if the directory exists, false otherwise.
References CURL::GetFileName(), CServiceBroker::GetPVRManager(), CURL::IsProtocol(), and m_url.
Referenced by XFILE::CPVRDirectory::Exists().
GetChannelGroupsDirectory()
bool CPVRGUIDirectory::GetChannelGroupsDirectory (bool bRadio, bool bExcludeHidden, CFileItemList & results) static
Get the list of channel groups.
Parameters
bRadio If true, obtain radio groups, tv groups otherwise.
bExcludeHidden If true exclude hidden groups, include hidden groups otherwise.
results The file list to store the results in.
Returns
True on success, false otherwise..
References CFileItemList::Add(), PVR::CPVRManager::ChannelGroups(), and CServiceBroker::GetPVRManager().
Referenced by GetChannelsDirectory(), PVR::CGUIPVRChannelGroupsSelector::Initialize(), PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), and PVR::CGUIDialogPVRGroupManager::Update().
GetChannelsDirectory()
bool CPVRGUIDirectory::GetChannelsDirectory (CFileItemList & results) const
Get the list of channels.
Parameters
results The file list to store the results in.
Returns
True on success, false otherwise..
References CFileItemList::Add(), g_localizeStrings, CLocalizeStrings::Get(), GetChannelGroupsDirectory(), PVR::CPVRManager::GetClient(), CURL::GetOption(), CServiceBroker::GetPVRManager(), CURL::GetWithoutOptions(), CURL::HasOption(), PVR::CPVRChannelsPath::IsChannelGroup(), PVR::CPVRChannelsPath::IsChannelsRoot(), PVR::CPVRChannelsPath::IsEmpty(), PVR::CPVRChannelsPath::IsHiddenChannelGroup(), PVR::CPVRChannelsPath::IsRadio(), PVR::CPVRChannelsPath::IsValid(), m_url, PVR::CPVRChannelsPath::PATH_RADIO_CHANNELS, and PVR::CPVRChannelsPath::PATH_TV_CHANNELS.
Referenced by GetDirectory(), and PVR::CPVRChannelGroupImageFileLoader::Load().
GetDirectory()
bool CPVRGUIDirectory::GetDirectory (CFileItemList & results) const
Obtain the directory listing.
Parameters
results The list to fill with the results.
Returns
True on success, false otherwise.
References CFileItemList::Add(), CFileItemList::AddSortMethod(), CFileItemList::CACHE_NEVER, g_localizeStrings, CURL::Get(), CLocalizeStrings::Get(), GetChannelsDirectory(), CURL::GetFileName(), PVR::CPVREpgSearchPath::GetId(), GetProvidersDirectory(), CServiceBroker::GetPVRManager(), GetRecordingsDirectory(), GetSavedSearchesDirectory(), GetSavedSearchResults(), GetTimersDirectory(), PVR::CPVREpgSearchPath::IsRadio(), PVR::CPVREpgSearchPath::IsSavedSearch(), PVR::CPVREpgSearchPath::IsSavedSearchesRoot(), PVR::CPVREpgSearchPath::IsValid(), m_url, URIUtils::RemoveSlashAtEnd(), CFileItemList::SetCacheToDisc(), and SortByLabel.
Referenced by XFILE::CPVRDirectory::GetDirectory().
GetProvidersDirectory()
bool CPVRGUIDirectory::GetProvidersDirectory (CFileItemList & results) const
Get the list of providers.
Parameters
results The file list to store the results in.
Returns
True on success, false otherwise..
References CFileItemList::Add(), PVR::CPVRManager::ChannelGroups(), PVR::CPVRProvidersPath::CHANNELS, g_localizeStrings, CLocalizeStrings::Get(), PVR::CPVRProvidersPath::GetClientId(), PVR::CPVRProvidersPath::GetKind(), PVR::CPVRProvidersPath::GetProviderUid(), CServiceBroker::GetPVRManager(), CURL::GetWithoutOptions(), PVR::CPVRProvidersPath::IsChannels(), PVR::CPVRProvidersPath::IsProvider(), PVR::CPVRProvidersPath::IsProvidersRoot(), PVR::CPVRProvidersPath::IsRadio(), PVR::CPVRProvidersPath::IsRecordings(), PVR::CPVRProvidersPath::IsValid(), m_url, PVR::CPVRChannelGroup::ONLY_VISIBLE, PVR::CPVRManager::Providers(), PVR_PROVIDER_INVALID_UID, PVR::CPVRProvidersPath::RECORDINGS, and PVR::CPVRManager::Recordings().
Referenced by GetDirectory().
GetRecordingsDirectory()
bool CPVRGUIDirectory::GetRecordingsDirectory (CFileItemList & results) const private
References CFileItemList::Add(), CURL::GetOption(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), PVR::CPVRRecordingsPath::GetUnescapedDirectoryPath(), CURL::GetWithoutOptions(), CURL::HasOption(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, PVR::CPVRRecordingsPath::IsDeleted(), PVR::CPVRRecordingsPath::IsRadio(), PVR::CPVRRecordingsPath::IsValid(), LOGERROR, m_url, PVR::CPVRManager::Recordings(), CFileItemList::SetContent(), and CSettings::SETTING_PVRRECORD_GROUPRECORDINGS.
Referenced by GetDirectory().
GetRecordingsDirectoryInfo()
bool CPVRGUIDirectory::GetRecordingsDirectoryInfo (CFileItem & item) static
Get info for a recording folder.
Parameters
item The folder.
Returns
True on success, false otherwise..
References CVariant::asInteger(), CFileItemList::GetList(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, CGUIListItem::IncrementProperty(), int64_t(), CDateTime::IsValid(), CFileItem::m_dateTime, CFileItem::SetLabelPreformatted(), CGUIListItem::SetOverlayImage(), and CGUIListItem::SetProperty().
Referenced by anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation().
GetSavedSearchesDirectory()
bool CPVRGUIDirectory::GetSavedSearchesDirectory (bool bRadio, CFileItemList & results) const private
References CFileItemList::Add(), PVR::CPVRManager::EpgContainer(), CServiceBroker::GetPVRManager(), and PVR::CPVREpgContainer::GetSavedSearches().
Referenced by GetDirectory().
GetSavedSearchResults()
bool CPVRGUIDirectory::GetSavedSearchResults (bool isRadio, int id, CFileItemList & results) const private
References CFileItemList::Add(), PVR::CPVRManager::EpgContainer(), PVR::CPVREpgSearch::Execute(), CServiceBroker::GetPVRManager(), PVR::CPVREpgSearch::GetResults(), PVR::CPVREpgContainer::GetSavedSearchById(), and tags.
Referenced by GetDirectory().
GetTimersDirectory()
bool CPVRGUIDirectory::GetTimersDirectory (CFileItemList & results) const private
References CURL::GetOption(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), CURL::GetWithoutOptions(), CURL::HasOption(), PVR::CPVRTimersPath::IsTimerRule(), PVR::CPVRTimersPath::IsTimersRoot(), PVR::CPVRTimersPath::IsValid(), LOGERROR, m_url, CSettings::SETTING_PVRTIMERS_HIDEDISABLEDTIMERS, and PVR::CPVRManager::Timers().
Referenced by GetDirectory().
HasDeletedRadioRecordings()
bool CPVRGUIDirectory::HasDeletedRadioRecordings () static
Check if any deleted radio recordings are existing.
Returns
True if deleted radio recordings exists, false otherwise.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::IsStarted(), and PVR::CPVRManager::Recordings().
Referenced by XFILE::CPVRDirectory::HasDeletedRadioRecordings().
HasDeletedTVRecordings()
bool CPVRGUIDirectory::HasDeletedTVRecordings () static
Check if any deleted TV recordings are existing.
Returns
True if deleted TV recordings exists, false otherwise.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::IsStarted(), and PVR::CPVRManager::Recordings().
Referenced by XFILE::CPVRDirectory::HasDeletedTVRecordings().
HasRadioRecordings()
bool CPVRGUIDirectory::HasRadioRecordings () static
Check if any radio recordings are existing.
Returns
True if radio recordings exists, false otherwise.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::IsStarted(), and PVR::CPVRManager::Recordings().
Referenced by XFILE::CPVRDirectory::HasRadioRecordings().
HasTVRecordings()
bool CPVRGUIDirectory::HasTVRecordings () static
Check if any TV recordings are existing.
Returns
True if TV recordings exists, false otherwise.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::IsStarted(), and PVR::CPVRManager::Recordings().
Referenced by XFILE::CPVRDirectory::HasTVRecordings().
SupportsWriteFileOperations()
bool CPVRGUIDirectory::SupportsWriteFileOperations () const
Check if this directory supports file write operations.
Returns
True if the directory supports file write operations, false otherwise.
References CURL::GetFileName(), CServiceBroker::GetPVRManager(), URIUtils::IsPVRRecording(), and m_url.
Referenced by XFILE::CPVRDirectory::SupportsWriteFileOperations().
Member Data Documentation
m_url
const CURL PVR::CPVRGUIDirectory::m_url private
Referenced by Exists(), GetChannelsDirectory(), GetDirectory(), GetProvidersDirectory(), GetRecordingsDirectory(), GetTimersDirectory(), and SupportsWriteFileOperations().
The documentation for this class was generated from the following files:
PVRGUIDirectory.h
PVRGUIDirectory.cpp