Kodi Documentation: CVideoTagLoaderFFmpeg Class Reference
CVideoTagLoaderFFmpeg Class Reference
Video tag loader using FFMPEG.
#include <VideoTagLoaderFFmpeg.h>
Public Member Functions
CVideoTagLoaderFFmpeg (const CFileItem &item, const ADDON::ScraperPtr &info, bool lookInFolder)
Constructor.
~CVideoTagLoaderFFmpeg () override
Destructor.
bool HasInfo () const override
Returns whether or not reader has info.
CInfoScanner::INFO_TYPE Load (CVideoInfoTag &tag, bool, std::vector< EmbeddedArt > *art=nullptr) override
Load "tag" from nfo file.
ADDON::ScraperPtr GetScraperInfo () const
Public Member Functions inherited from KODI::VIDEO::IVideoInfoTagLoader
IVideoInfoTagLoader (const CFileItem &item, ADDON::ScraperPtr info, bool lookInFolder)
Constructor.
virtual ~IVideoInfoTagLoader ()=default
const CScraperUrl & ScraperUrl () const
Returns url associated with obtained URL (NFO_URL et al).
const ADDON::ScraperPtr GetAddonInfo () const
Returns current scaper info.
Protected Member Functions
CInfoScanner::INFO_TYPE LoadMKV (CVideoInfoTag &tag, std::vector< EmbeddedArt > *art)
Load tags from MKV file.
CInfoScanner::INFO_TYPE LoadMP4 (CVideoInfoTag &tag, std::vector< EmbeddedArt > *art)
Load tags from MP4 file.
CInfoScanner::INFO_TYPE LoadAVI (CVideoInfoTag &tag, std::vector< EmbeddedArt > *art)
Load tags from AVI file.
Protected Attributes
ADDON::ScraperPtr m_info
Passed scraper info.
AVIOContext * m_ioctx = nullptr
IO context for file.
AVFormatContext * m_fctx = nullptr
Format context for file.
XFILE::CFile * m_file = nullptr
VFS file handle for file.
int m_metadata_stream = -1
Stream holding kodi metadata (mkv)
bool m_override_data = false
Data is for overriding.
Protected Attributes inherited from KODI::VIDEO::IVideoInfoTagLoader
const CFileItem & m_item
Reference to item to load for.
ADDON::ScraperPtr m_info
Scraper info.
CScraperUrl m_url
URL for scraper.
Detailed Description
Video tag loader using FFMPEG.
Constructor & Destructor Documentation
CVideoTagLoaderFFmpeg()
CVideoTagLoaderFFmpeg::CVideoTagLoaderFFmpeg (const CFileItem & item, const ADDON::ScraperPtr & info, bool lookInFolder)
Constructor.
References XFILE::CFile::GetChunkSize(), XFILE::CStackDirectory::GetFirstStackedFile(), CFileItem::GetPath(), XFILE::CFile::IoControl(), XFILE::IOCTRL_SEEK_POSSIBLE, CFileItem::IsStack(), m_fctx, m_file, m_ioctx, KODI::VIDEO::IVideoInfoTagLoader::m_item, XFILE::CFile::Open(), vfs_file_read(), and vfs_file_seek().
~CVideoTagLoaderFFmpeg()
CVideoTagLoaderFFmpeg::~CVideoTagLoaderFFmpeg () override
Destructor.
References m_fctx, m_file, and m_ioctx.
Member Function Documentation
GetScraperInfo()
ADDON::ScraperPtr CVideoTagLoaderFFmpeg::GetScraperInfo () const inline
References m_info.
HasInfo()
bool CVideoTagLoaderFFmpeg::HasInfo () const override virtual
Returns whether or not reader has info.
Implements KODI::VIDEO::IVideoInfoTagLoader.
References CFileItem::IsType(), m_fctx, m_file, KODI::VIDEO::IVideoInfoTagLoader::m_item, m_metadata_stream, and m_override_data.
Referenced by KODI::VIDEO::CVideoInfoTagLoaderFactory::CreateLoader().
Load()
CInfoScanner::INFO_TYPE CVideoTagLoaderFFmpeg::Load (CVideoInfoTag & tag, bool , std::vector< EmbeddedArt > * art = nullptr) override virtual
Load "tag" from nfo file.
tag Tag to load info into
Implements KODI::VIDEO::IVideoInfoTagLoader.
References CFileItem::IsType(), LoadAVI(), LoadMKV(), LoadMP4(), KODI::VIDEO::IVideoInfoTagLoader::m_item, and CInfoScanner::NO_NFO.
Referenced by KODI::VIDEO::TAGS::CVideoTagExtractionHelper::ExtractEmbeddedArtFor().
LoadAVI()
CInfoScanner::INFO_TYPE CVideoTagLoaderFFmpeg::LoadAVI (CVideoInfoTag & tag, std::vector< EmbeddedArt > * art) protected
Load tags from AVI file.
References m_fctx, and CInfoScanner::TITLE_NFO.
Referenced by Load().
LoadMKV()
CInfoScanner::INFO_TYPE CVideoTagLoaderFFmpeg::LoadMKV (CVideoInfoTag & tag, std::vector< EmbeddedArt > * art) protected
Load tags from MKV file.
References CNfoFile::Create(), data(), CInfoScanner::FULL_NFO, CNfoFile::GetDetails(), m_fctx, m_info, m_metadata_stream, m_override_data, KODI::VIDEO::IVideoInfoTagLoader::m_url, CInfoScanner::NO_NFO, CNfoFile::ScraperUrl(), CScraperUrl::SetTitle(), CInfoScanner::TITLE_NFO, CInfoScanner::URL_NFO, and value.
Referenced by Load().
LoadMP4()
CInfoScanner::INFO_TYPE CVideoTagLoaderFFmpeg::LoadMP4 (CVideoInfoTag & tag, std::vector< EmbeddedArt > * art) protected
Load tags from MP4 file.
References CInfoScanner::FULL_NFO, m_fctx, and CInfoScanner::TITLE_NFO.
Referenced by Load().
Member Data Documentation
m_fctx
AVFormatContext* CVideoTagLoaderFFmpeg::m_fctx = nullptr protected
Format context for file.
Referenced by CVideoTagLoaderFFmpeg(), HasInfo(), LoadAVI(), LoadMKV(), LoadMP4(), and ~CVideoTagLoaderFFmpeg().
m_file
XFILE::CFile* CVideoTagLoaderFFmpeg::m_file = nullptr protected
VFS file handle for file.
Referenced by CVideoTagLoaderFFmpeg(), HasInfo(), and ~CVideoTagLoaderFFmpeg().
m_info
ADDON::ScraperPtr CVideoTagLoaderFFmpeg::m_info protected
Passed scraper info.
Referenced by GetScraperInfo(), and LoadMKV().
m_ioctx
AVIOContext* CVideoTagLoaderFFmpeg::m_ioctx = nullptr protected
IO context for file.
Referenced by CVideoTagLoaderFFmpeg(), and ~CVideoTagLoaderFFmpeg().
m_metadata_stream
int CVideoTagLoaderFFmpeg::m_metadata_stream = -1 mutable protected
Stream holding kodi metadata (mkv)
Referenced by HasInfo(), and LoadMKV().
m_override_data
bool CVideoTagLoaderFFmpeg::m_override_data = false mutable protected
Data is for overriding.
Referenced by HasInfo(), and LoadMKV().
The documentation for this class was generated from the following files:
VideoTagLoaderFFmpeg.h
VideoTagLoaderFFmpeg.cpp