Kodi Documentation: TestUrlOptions.cpp File Reference
TestUrlOptions.cpp File Reference
#include "utils/UrlOptions.h"
#include "utils/Variant.h"
#include <gtest/gtest.h>
Functions
TEST (TestUrlOptions, Clear)
TEST (TestUrlOptions, AddOption)
TEST (TestUrlOptions, AddOptions)
TEST (TestUrlOptions, RemoveOption)
TEST (TestUrlOptions, HasOption)
TEST (TestUrlOptions, GetOptions)
TEST (TestUrlOptions, GetOptionsString)
Function Documentation
TEST() [1/7]
TEST (TestUrlOptions , AddOption)
References CUrlOptions::AddOption(), CVariant::asBoolean(), CVariant::asDouble(), CVariant::asFloat(), CVariant::asInteger(), CVariant::asString(), EXPECT_EQ(), EXPECT_TRUE(), CUrlOptions::GetOption(), CVariant::isBoolean(), CVariant::isDouble(), CVariant::isInteger(), and CVariant::isString().
TEST() [2/7]
TEST (TestUrlOptions , AddOptions)
References CUrlOptions::AddOptions(), CUrlOptions::Clear(), EXPECT_TRUE(), CUrlOptions::GetOption(), and value.
TEST() [3/7]
TEST (TestUrlOptions , Clear)
References CUrlOptions::AddOption(), CUrlOptions::Clear(), EXPECT_TRUE(), and CUrlOptions::HasOption().
TEST() [4/7]
TEST (TestUrlOptions , GetOptions)
References CUrlOptions::AddOption(), EXPECT_EQ(), EXPECT_TRUE(), and CUrlOptions::GetOptions().
TEST() [5/7]
TEST (TestUrlOptions , GetOptionsString)
References CUrlOptions::GetOptionsString(), and value.
TEST() [6/7]
TEST (TestUrlOptions , HasOption)
References CUrlOptions::AddOption(), EXPECT_TRUE(), and CUrlOptions::HasOption().
TEST() [7/7]
TEST (TestUrlOptions , RemoveOption)
References CUrlOptions::AddOption(), EXPECT_TRUE(), CUrlOptions::HasOption(), and CUrlOptions::RemoveOption().