Kodi Documentation: ADDON::Interface_GUIDialogProgress Struct Reference
ADDON::Interface_GUIDialogProgress Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Progress.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static KODI_GUI_HANDLE new_dialog (KODI_HANDLE kodiBase)
callback functions from add-on to kodi
static void delete_dialog (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
static void open (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
static void set_heading (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char *heading)
static void set_line (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, unsigned int line, const char *text)
static void set_can_cancel (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, bool canCancel)
static bool is_canceled (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
static void set_percentage (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int percentage)
static int get_percentage (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
static void show_progress_bar (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, bool bOnOff)
static void set_progress_max (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int max)
static void set_progress_advance (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int nSteps)
static bool abort (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/dialogs/Progress.h"
Member Function Documentation
abort()
bool ADDON::Interface_GUIDialogProgress::abort (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
DeInit()
void ADDON::Interface_GUIDialogProgress::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogProgress, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
delete_dialog()
void ADDON::Interface_GUIDialogProgress::delete_dialog (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References Close(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_percentage()
int ADDON::Interface_GUIDialogProgress::get_percentage (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIDialogProgress::Init (AddonGlobalInterface * addonInterface) static
References abort(), AddonToKodiFuncTable_kodi_gui_dialogProgress::abort, delete_dialog(), AddonToKodiFuncTable_kodi_gui_dialogProgress::delete_dialog, AddonToKodiFuncTable_kodi_gui::dialogProgress, get_percentage(), AddonToKodiFuncTable_kodi_gui_dialogProgress::get_percentage, is_canceled(), AddonToKodiFuncTable_kodi_gui_dialogProgress::is_canceled, AddonToKodiFuncTable_Addon::kodi_gui, new_dialog(), AddonToKodiFuncTable_kodi_gui_dialogProgress::new_dialog, open(), AddonToKodiFuncTable_kodi_gui_dialogProgress::open, set_can_cancel(), AddonToKodiFuncTable_kodi_gui_dialogProgress::set_can_cancel, set_heading(), AddonToKodiFuncTable_kodi_gui_dialogProgress::set_heading, set_line(), AddonToKodiFuncTable_kodi_gui_dialogProgress::set_line, set_percentage(), AddonToKodiFuncTable_kodi_gui_dialogProgress::set_percentage, set_progress_advance(), AddonToKodiFuncTable_kodi_gui_dialogProgress::set_progress_advance, set_progress_max(), AddonToKodiFuncTable_kodi_gui_dialogProgress::set_progress_max, show_progress_bar(), AddonToKodiFuncTable_kodi_gui_dialogProgress::show_progress_bar, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
is_canceled()
bool ADDON::Interface_GUIDialogProgress::is_canceled (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
new_dialog()
KODI_GUI_HANDLE ADDON::Interface_GUIDialogProgress::new_dialog (KODI_HANDLE kodiBase) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and WINDOW_DIALOG_PROGRESS.
Referenced by Init().
open()
void ADDON::Interface_GUIDialogProgress::open (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
set_can_cancel()
void ADDON::Interface_GUIDialogProgress::set_can_cancel (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, bool canCancel) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
set_heading()
void ADDON::Interface_GUIDialogProgress::set_heading (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char * heading) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
set_line()
void ADDON::Interface_GUIDialogProgress::set_line (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, unsigned int line, const char * text) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and text.
Referenced by Init().
set_percentage()
void ADDON::Interface_GUIDialogProgress::set_percentage (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int percentage) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
set_progress_advance()
void ADDON::Interface_GUIDialogProgress::set_progress_advance (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int nSteps) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
set_progress_max()
void ADDON::Interface_GUIDialogProgress::set_progress_max (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int max) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and max.
Referenced by Init().
show_progress_bar()
void ADDON::Interface_GUIDialogProgress::show_progress_bar (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, bool bOnOff) static
References ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/dialogs/progress.h
dialogs/Progress.cpp