Kodi Documentation: CZeroconfBrowserDarwin Class Reference
CZeroconfBrowserDarwin Class Reference
#include <ZeroconfBrowserDarwin.h>
Public Member Functions
CZeroconfBrowserDarwin ()
~CZeroconfBrowserDarwin () override
Public Member Functions inherited from CZeroconfBrowser
void Start ()
void Stop ()
std::vector< ZeroconfService > GetFoundServices ()
bool ResolveService (ZeroconfService &fr_service, double f_timeout=1.0)
virtual void ProcessResults ()
bool AddServiceType (const std::string &fcr_service_type)
bool RemoveServiceType (const std::string &fcr_service_type)
Private Types
typedef std::map< std::string, CFNetServiceBrowserRef > tBrowserMap
typedef std::map< CFNetServiceBrowserRef, std::vector< std::pair< ZeroconfService, unsigned int > > > tDiscoveredServicesMap
Private Member Functions
void addDiscoveredService (CFNetServiceBrowserRef browser, CFOptionFlags flags, ZeroconfService const &fcr_service)
adds the service to list of found services
void removeDiscoveredService (CFNetServiceBrowserRef browser, CFOptionFlags flags, ZeroconfService const &fcr_service)
removes the service from list of found services
bool doAddServiceType (const std::string &fcr_service_type) override
bool doRemoveServiceType (const std::string &fcr_service_type) override
std::vector< CZeroconfBrowser::ZeroconfService > doGetFoundServices () override
bool doResolveService (CZeroconfBrowser::ZeroconfService &fr_service, double f_timeout) override
Static Private Member Functions
static void BrowserCallback (CFNetServiceBrowserRef browser, CFOptionFlags flags, CFTypeRef domainOrService, CFStreamError *error, void *info)
browser callback
static void ResolveCallback (CFNetServiceRef theService, CFStreamError *error, void *info)
resolve callback
Private Attributes
CFRunLoopRef m_runloop = nullptr
CCriticalSection m_data_guard
tBrowserMap m_service_browsers
tDiscoveredServicesMap m_discovered_services
Additional Inherited Members
Static Public Member Functions inherited from CZeroconfBrowser
static CZeroconfBrowser * GetInstance ()
static void ReleaseInstance ()
static bool IsInstantiated ()
Protected Member Functions inherited from CZeroconfBrowser
CZeroconfBrowser (const CZeroconfBrowser &)=delete
CZeroconfBrowser & operator= (const CZeroconfBrowser &)=delete
Member Typedef Documentation
tBrowserMap
typedef std::map<std::string, CFNetServiceBrowserRef> CZeroconfBrowserDarwin::tBrowserMap private
tDiscoveredServicesMap
typedef std::map<CFNetServiceBrowserRef, std::vector<std::pair<ZeroconfService, unsigned int> > > CZeroconfBrowserDarwin::tDiscoveredServicesMap private
Constructor & Destructor Documentation
CZeroconfBrowserDarwin()
CZeroconfBrowserDarwin::CZeroconfBrowserDarwin ()
References m_runloop.
~CZeroconfBrowserDarwin()
CZeroconfBrowserDarwin::~CZeroconfBrowserDarwin () override
References doRemoveServiceType(), m_data_guard, and m_service_browsers.
Member Function Documentation
addDiscoveredService()
void CZeroconfBrowserDarwin::addDiscoveredService (CFNetServiceBrowserRef browser, CFOptionFlags flags, CZeroconfBrowser::ZeroconfService const & fcr_service) private
adds the service to list of found services
References m_data_guard, and m_discovered_services.
Referenced by BrowserCallback().
BrowserCallback()
void CZeroconfBrowserDarwin::BrowserCallback (CFNetServiceBrowserRef browser, CFOptionFlags flags, CFTypeRef domainOrService, CFStreamError * error, void * info) static private
browser callback
References addDiscoveredService(), CDarwinUtils::CFStringRefToUTF8String(), CServiceBroker::GetAnnouncementManager(), CZeroconfBrowser::ZeroconfService::GetDomain(), CZeroconfBrowser::ZeroconfService::GetName(), CZeroconfBrowser::ZeroconfService::GetType(), int64_t(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, name, removeDiscoveredService(), and ANNOUNCEMENT::Sources.
Referenced by doAddServiceType().
doAddServiceType()
bool CZeroconfBrowserDarwin::doAddServiceType (const std::string & fcr_service_type) override private virtual
implementation if CZeroconfBrowser interface
Implements CZeroconfBrowser.
References Boolean, BrowserCallback(), int64_t(), CLog::Log(), LOGERROR, m_data_guard, m_runloop, and m_service_browsers.
doGetFoundServices()
std::vector< CZeroconfBrowser::ZeroconfService > CZeroconfBrowserDarwin::doGetFoundServices () override private virtual
Implements CZeroconfBrowser.
References m_data_guard, and m_discovered_services.
doRemoveServiceType()
bool CZeroconfBrowserDarwin::doRemoveServiceType (const std::string & fcr_service_type) override private virtual
Implements CZeroconfBrowser.
References m_data_guard, m_discovered_services, m_runloop, and m_service_browsers.
Referenced by ~CZeroconfBrowserDarwin().
doResolveService()
bool CZeroconfBrowserDarwin::doResolveService (CZeroconfBrowser::ZeroconfService & fr_service, double f_timeout) override private virtual
Implements CZeroconfBrowser.
References CZeroconfBrowser::ZeroconfService::GetDomain(), CZeroconfBrowser::ZeroconfService::GetName(), GetTxtRecords(), CZeroconfBrowser::ZeroconfService::GetType(), name, CZeroconfBrowser::ZeroconfService::SetIP(), CZeroconfBrowser::ZeroconfService::SetPort(), and CZeroconfBrowser::ZeroconfService::SetTxtRecords().
removeDiscoveredService()
void CZeroconfBrowserDarwin::removeDiscoveredService (CFNetServiceBrowserRef browser, CFOptionFlags flags, CZeroconfBrowser::ZeroconfService const & fcr_service) private
removes the service from list of found services
References m_data_guard, and m_discovered_services.
Referenced by BrowserCallback().
ResolveCallback()
static void CZeroconfBrowserDarwin::ResolveCallback (CFNetServiceRef theService, CFStreamError * error, void * info) static private
resolve callback
Member Data Documentation
m_data_guard
CCriticalSection CZeroconfBrowserDarwin::m_data_guard private
Todo:
split the guard for discovered, resolved access?
Referenced by addDiscoveredService(), doAddServiceType(), doGetFoundServices(), doRemoveServiceType(), removeDiscoveredService(), and ~CZeroconfBrowserDarwin().
m_discovered_services
tDiscoveredServicesMap CZeroconfBrowserDarwin::m_discovered_services private
Referenced by addDiscoveredService(), doGetFoundServices(), doRemoveServiceType(), and removeDiscoveredService().
m_runloop
CFRunLoopRef CZeroconfBrowserDarwin::m_runloop = nullptr private
Referenced by CZeroconfBrowserDarwin(), doAddServiceType(), and doRemoveServiceType().
m_service_browsers
tBrowserMap CZeroconfBrowserDarwin::m_service_browsers private
Referenced by doAddServiceType(), doRemoveServiceType(), and ~CZeroconfBrowserDarwin().
The documentation for this class was generated from the following files:
ZeroconfBrowserDarwin.h
ZeroconfBrowserDarwin.cpp