Kodi Documentation: DebugLogSharingPresenter Class Reference
DebugLogSharingPresenter Class Reference
Public Member Functions
DebugLogSharingPresenter ()
virtual ~DebugLogSharingPresenter ()
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
Additional Inherited Members
Private Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingChanged (const std::shared_ptr< const CSetting > &setting)
The value of the given setting has changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Constructor & Destructor Documentation
DebugLogSharingPresenter()
DebugLogSharingPresenter::DebugLogSharingPresenter () inline
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_DEBUG_SHARE_LOG.
~DebugLogSharingPresenter()
virtual DebugLogSharingPresenter::~DebugLogSharingPresenter () inline virtual
References CServiceBroker::GetSettingsComponent().
Member Function Documentation
OnSettingAction()
void DebugLogSharingPresenter::OnSettingAction (const std::shared_ptr< const CSetting > & setting) inline override virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References URIUtils::AddFileToFolder(), CCompileInfo::GetAppName(), CSettings::SETTING_DEBUG_SHARE_LOG, and CSpecialProtocol::TranslatePath().
The documentation for this class was generated from the following file:
ios/XBMCController.mm