Kodi Documentation: KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist Class Reference
KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist Class Reference
Public Member Functions
CAsyncGetItemsForPlaylist (const std::shared_ptr< CFileItem > &item, CFileItemList &queuedItems)
~CAsyncGetItemsForPlaylist () override=default
void Run () override
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Private Member Functions
void GetItemsForPlaylist (const std::shared_ptr< CFileItem > &item)
Private Attributes
const std::shared_ptr< CFileItem > m_item
const bool m_resume {false}
CFileItemList & m_queuedItems
Constructor & Destructor Documentation
CAsyncGetItemsForPlaylist()
KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::CAsyncGetItemsForPlaylist (const std::shared_ptr< CFileItem > & item, CFileItemList & queuedItems) inline
~CAsyncGetItemsForPlaylist()
KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::~CAsyncGetItemsForPlaylist () override default
Member Function Documentation
GetItemsForPlaylist()
void KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist (const std::shared_ptr< CFileItem > & item) private
References CFileItemList::AddFront(), CFileItemList::ClearSortState(), CUtil::ConvertSecsToMilliSecs(), XFILE::DIR_FLAG_DEFAULTS, CLabelFormatter::FormatLabels(), g_passwordManager, CFileItemList::GetContent(), CVideoDatabase::GetContentForPath(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetGUI(), CMediaSettings::GetInstance(), KODI::VIDEO::UTILS::GetOpticalMediaPath(), CFileItem::GetPath(), CVideoDatabase::GetPlayCounts(), CGUIViewState::GetViewState(), CMediaSettings::GetWatchedMode(), CGUIComponent::GetWindowManager(), KODI::NETWORK::IsInternetStream(), CGUIPassword::IsItemUnlocked(), CFileItem::IsLibraryFolder(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsPlugin(), URIUtils::IsPVRRadioRecordingFileOrFolder(), URIUtils::IsPVRTVRecordingFileOrFolder(), CBookmark::IsSet(), CFileItem::IsSourcesPath(), CDateTime::IsValid(), KODI::VIDEO::IsVideo(), KODI::VIDEO::IsVideoDb(), CFileItem::IsVirtualDirectoryRoot(), LABEL_MASKS::m_strLabel2File, LABEL_MASKS::m_strLabel2Folder, LABEL_MASKS::m_strLabelFile, LABEL_MASKS::m_strLabelFolder, CVideoDatabase::Open(), CFileItemList::Remove(), URIUtils::RemoveSlashAtEnd(), CFileItemList::SetContent(), CFileItemList::Sort(), SortDescription::sortBy, SortByDate, SortByEpisodeNumber, SortByLabel, SortByYear, SortDescription::sortOrder, SortOrderAscending, CBookmark::timeInSeconds, WatchedModeUnwatched, WatchedModeWatched, WINDOW_RADIO_RECORDINGS, WINDOW_TV_RECORDINGS, and WINDOW_VIDEO_NAV.
Run()
void KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::Run () inline override virtual
Implements IRunnable.
Member Data Documentation
m_item
const std::shared_ptr<CFileItem> KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::m_item private
m_queuedItems
CFileItemList& KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::m_queuedItems private
m_resume
const bool KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::m_resume {false} private
The documentation for this class was generated from the following file:
VideoGUIUtils.cpp