Kodi Documentation: CZeroconfMDNS Class Reference
CZeroconfMDNS Class Reference
#include <ZeroconfMDNS.h>
Classes
struct tServiceRef
Public Member Functions
CZeroconfMDNS ()
~CZeroconfMDNS ()
Public Member Functions inherited from CZeroconf
bool PublishService (const std::string &fcr_identifier, const std::string &fcr_type, const std::string &fcr_name, unsigned int f_port, std::vector< std::pair< std::string, std::string > > txt)
bool ForceReAnnounceService (const std::string &fcr_identifier)
bool RemoveService (const std::string &fcr_identifier)
bool HasService (const std::string &fcr_identifier) const
returns true if fcr_identifier exists
bool Start ()
void Stop ()
bool IsStarted ()
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Protected Member Functions
void Process ()
bool doPublishService (const std::string &fcr_identifier, const std::string &fcr_type, const std::string &fcr_name, unsigned int f_port, const std::vector< std::pair< std::string, std::string > > &txt)
bool doForceReAnnounceService (const std::string &fcr_identifier)
bool doRemoveService (const std::string &fcr_ident)
virtual void doStop ()
bool IsZCdaemonRunning ()
void ProcessResults ()
Protected Member Functions inherited from CZeroconf
CZeroconf ()
CZeroconf (const CZeroconf &)
virtual ~CZeroconf ()
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Types
typedef std::map< std::string, struct tServiceRef > tServiceMap
Static Private Member Functions
static void DNSSD_API registerCallback (DNSServiceRef sdref, const DNSServiceFlags flags, DNSServiceErrorType errorCode, const char *name, const char *regtype, const char *domain, void *context)
Private Attributes
CCriticalSection m_data_guard
tServiceMap m_services
DNSServiceRef m_service
Additional Inherited Members
Static Public Member Functions inherited from CZeroconf
static CZeroconf * GetInstance ()
static void ReleaseInstance ()
static bool IsInstantiated ()
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Member Typedef Documentation
tServiceMap
typedef std::map<std::string, struct tServiceRef> CZeroconfMDNS::tServiceMap private
Constructor & Destructor Documentation
CZeroconfMDNS()
CZeroconfMDNS::CZeroconfMDNS ()
References CThread::Create(), and m_service.
~CZeroconfMDNS()
CZeroconfMDNS::~CZeroconfMDNS ()
References doStop(), and CThread::StopThread().
Member Function Documentation
doForceReAnnounceService()
bool CZeroconfMDNS::doForceReAnnounceService (const std::string & fcr_identifier) protected virtual
Implements CZeroconf.
References m_data_guard, and m_services.
doPublishService()
bool CZeroconfMDNS::doPublishService (const std::string & fcr_identifier, const std::string & fcr_type, const std::string & fcr_name, unsigned int f_port, const std::vector< std::pair< std::string, std::string > > & txt) protected virtual
HAS_MDNS_EMBEDDED
Implements CZeroconf.
References BONJOUR_EVENT, err(), g_hWnd, CLog::Log(), LOGDEBUG, LOGERROR, m_data_guard, m_service, m_services, registerCallback(), CZeroconfMDNS::tServiceRef::serviceRef, CZeroconfMDNS::tServiceRef::txtRecordRef, and CZeroconfMDNS::tServiceRef::updateNumber.
doRemoveService()
bool CZeroconfMDNS::doRemoveService (const std::string & fcr_ident) protected virtual
Implements CZeroconf.
References CLog::Log(), LOGDEBUG, m_data_guard, and m_services.
doStop()
void CZeroconfMDNS::doStop () protected virtual
Implements CZeroconf.
References BONJOUR_EVENT, g_hWnd, CLog::Log(), LOGDEBUG, LOGERROR, m_data_guard, m_service, and m_services.
Referenced by ~CZeroconfMDNS().
IsZCdaemonRunning()
bool CZeroconfMDNS::IsZCdaemonRunning () protected virtual
HAS_MDNS_EMBEDDED
Reimplemented from CZeroconf.
References err(), CGUIDialogKaiToast::Error, g_localizeStrings, CLocalizeStrings::Get(), CLog::Log(), LOGDEBUG, LOGERROR, and CGUIDialogKaiToast::QueueNotification().
Process()
void CZeroconfMDNS::Process (void) protected virtual
Reimplemented from CThread.
References CLog::Log(), LOGDEBUG, and CThread::m_bStop.
ProcessResults()
void CZeroconfMDNS::ProcessResults () protected virtual
Reimplemented from CZeroconf.
References err(), CLog::Log(), LOGERROR, m_data_guard, and m_service.
registerCallback()
void DNSSD_API CZeroconfMDNS::registerCallback (DNSServiceRef sdref, const DNSServiceFlags flags, DNSServiceErrorType errorCode, const char * name, const char * regtype, const char * domain, void * context) static private
References CLog::Log(), LOGDEBUG, name, and void().
Referenced by doPublishService().
Member Data Documentation
m_data_guard
CCriticalSection CZeroconfMDNS::m_data_guard private
Referenced by doForceReAnnounceService(), doPublishService(), doRemoveService(), doStop(), and ProcessResults().
m_service
DNSServiceRef CZeroconfMDNS::m_service private
Referenced by CZeroconfMDNS(), doPublishService(), doStop(), and ProcessResults().
m_services
tServiceMap CZeroconfMDNS::m_services private
Referenced by doForceReAnnounceService(), doPublishService(), doRemoveService(), and doStop().
The documentation for this class was generated from the following files:
ZeroconfMDNS.h
ZeroconfMDNS.cpp