Kodi Documentation: UPnP.cpp File Reference
UPnP.cpp File Reference
#include "UPnP.h"
#include "FileItem.h"
#include "ServiceBroker.h"
#include "UPnPInternal.h"
#include "UPnPRenderer.h"
#include "UPnPServer.h"
#include "UPnPSettings.h"
#include "URL.h"
#include "cores/playercorefactory/PlayerCoreFactory.h"
#include "interfaces/AnnouncementManager.h"
#include "messaging/ApplicationMessenger.h"
#include "network/Network.h"
#include "profiles/ProfileManager.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/SystemInfo.h"
#include "utils/TimeUtils.h"
#include "utils/URIUtils.h"
#include "utils/log.h"
#include "video/VideoInfoTag.h"
#include <memory>
#include <mutex>
#include <set>
#include <Platinum/Source/Platinum/Platinum.h>
Classes
class UPNP::CDeviceHostReferenceHolder
class UPNP::CCtrlPointReferenceHolder
class UPNP::CUPnPCleaner
class UPNP::CMediaBrowser
class UPNP::CMediaController
Namespaces
namespace UPNP
Macros
#define UPNP_DEFAULT_MAX_RETURNED_ITEMS 200
#define UPNP_DEFAULT_MIN_RETURNED_ITEMS 30
#define CHECK_USERDATA_RETURN(userdata)
Functions
spdlog::level::level_enum ConvertLogLevel (int nptLogLevel)
void UPnPLogger (const NPT_LogRecord *record)
Variables
static NPT_List< void * > UPNP::g_UserData
static NPT_Mutex UPNP::g_UserDataLock
Macro Definition Documentation
CHECK_USERDATA_RETURN
#define CHECK_USERDATA_RETURN (userdata)
Value:
  do \
  { \
    if (!g_UserData.Contains(userdata)) \
      return; \
  } while (0)
UPNP_DEFAULT_MAX_RETURNED_ITEMS
#define UPNP_DEFAULT_MAX_RETURNED_ITEMS 200
UPNP_DEFAULT_MIN_RETURNED_ITEMS
#define UPNP_DEFAULT_MIN_RETURNED_ITEMS 30
Function Documentation
ConvertLogLevel()
spdlog::level::level_enum ConvertLogLevel (int nptLogLevel)
Referenced by UPnPLogger().
UPnPLogger()
void UPnPLogger (const NPT_LogRecord * record)
References ConvertLogLevel(), CLog::GetLogger(), CServiceBroker::GetLogging(), and LOGUPNP.
Referenced by UPNP::CUPnP::CUPnP().