Kodi Documentation: PVR::anonymous_namespace{PVRGUIActionsUtils.cpp} Namespace Reference
PVR::anonymous_namespace{PVRGUIActionsUtils.cpp} Namespace Reference
Functions
std::shared_ptr< CFileItem > LoadRecordingFileOrFolderItem (const CFileItem &item)
std::shared_ptr< CFileItem > LoadChannelItem (const CFileItem &item)
Function Documentation
LoadChannelItem()
std::shared_ptr< CFileItem > PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadChannelItem (const CFileItem & item)
References PVR::CPVRManager::ChannelGroups(), CFileItem::GetPath(), CServiceBroker::GetPVRManager(), CFileItem::HasPVRChannelInfoTag(), URIUtils::IsPVRChannel(), and LoadChannelItem().
Referenced by LoadChannelItem().
LoadRecordingFileOrFolderItem()
std::shared_ptr< CFileItem > PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadRecordingFileOrFolderItem (const CFileItem & item)
Todo:
prop misused to detect loaded state for recording folder item
Todo:
optimize, find a way to set the details of the item without loading parent directory.
References CFileItemList::cbegin(), CFileItemList::cend(), XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::GetDirectory(), URIUtils::GetParentPath(), CFileItem::GetPath(), CGUIListItem::HasProperty(), CFileItem::HasPVRRecordingInfoTag(), URIUtils::IsPVRRecordingFileOrFolder(), and LoadRecordingFileOrFolderItem().
Referenced by LoadRecordingFileOrFolderItem().