Kodi Documentation: CTextureBase Class Reference
CTextureBase Class Reference
Guilib classes » Graphics and Screen » Textures and Fonts
Base texture class, which holds the state of the texture, as well as all conversion functions.
#include <TextureBase.h>
Public Member Functions
CTextureBase ()=default
~CTextureBase ()=default
bool HasAlpha () const
void SetAlpha (bool hasAlpha)
void SetMipmapping ()
sets mipmapping. do not use in new code. will be replaced with proper scaling.
bool IsMipmapped () const
return true if we want to mipmap
void SetScalingMethod (TEXTURE_SCALING scalingMethod)
sets the scaling method. scanout systems might support more than NN/linear.
TEXTURE_SCALING GetScalingMethod () const
returns the scaling method.
int32_t GetOrientation () const
void SetOrientation (int orientation)
void SetCacheMemory (bool bCacheMemory)
retains a shadow copy of the texture on the CPU side.
bool GetCacheMemory () const
returns true if a shadow copy is kept on the CPU side.
uint8_t * GetPixels () const
returns a pointer to the staging texture.
uint32_t GetPitch () const
return the size of one row in bytes.
uint32_t GetRows () const
return the number of rows (number of blocks in the Y direction).
uint32_t GetTextureWidth () const
return the total width of the texture, which might be scaled to fit its displayed size.
uint32_t GetTextureHeight () const
return the total height of the texture, which might be scaled to fit its displayed size.
uint32_t GetWidth () const
return the total width of "active" area, which might be equal or lower than the texture width due to alignment.
uint32_t GetHeight () const
return the total height of "active" area, which might be equal or lower than the texture height due to alignment.
uint32_t GetOriginalWidth () const
return the original width of the image, before scaling/cropping
uint32_t GetOriginalHeight () const
return the original height of the image, before scaling/cropping
void Allocate (uint32_t width, uint32_t height, XB_FMT format)
void ClampToEdge ()
Static Public Member Functions
static uint32_t PadPow2 (uint32_t x)
rounds to power of two. deprecated.
static bool SwapBlueRed (uint8_t *pixels, uint32_t height, uint32_t pitch, uint32_t elements=4, uint32_t offset=0)
swaps the blue/red channel. deprecated in this form.
Protected Member Functions
uint32_t GetPitch (uint32_t width) const
uint32_t GetRows (uint32_t height) const
uint32_t GetBlockWidth () const
uint32_t GetBlockHeight () const
uint32_t GetBlockSize () const
return the size of a compression block (tile) in bytes.
void SetKDFormat (XB_FMT xbFMT)
bool ConvertToLegacy (uint32_t width, uint32_t height, uint8_t *src)
Textures might be in a single/dual channel format with L/A/I/LA swizzle. DX and GLES 2.0 don't handle some/all at the moment. This function can convert the texture into a traditional BGRA format.
Protected Attributes
uint32_t m_imageWidth {0}
uint32_t m_imageHeight {0}
uint32_t m_textureWidth {0}
uint32_t m_textureHeight {0}
uint32_t m_originalWidth {0}
original image width before scaling or cropping
uint32_t m_originalHeight {0}
original image height before scaling or cropping
uint8_t * m_pixels {nullptr}
bool m_loadedToGPU {false}
KD_TEX_FMT m_textureFormat {KD_TEX_FMT_UNKNOWN}
KD_TEX_SWIZ m_textureSwizzle {KD_TEX_SWIZ_RGBA}
KD_TEX_COL m_textureColorspace {KD_TEX_COL_REC709}
KD_TEX_TRANSFER m_textureTransfer {KD_TEX_TRANSFER_SRGB}
KD_TEX_ALPHA m_textureAlpha {KD_TEX_ALPHA_STRAIGHT}
XB_FMT m_format {XB_FMT_UNKNOWN}
int32_t m_orientation {0}
bool m_mipmapping {false}
TEXTURE_SCALING m_scalingMethod {TEXTURE_SCALING::LINEAR}
bool m_bCacheMemory {false}
Detailed Description
Base texture class, which holds the state of the texture, as well as all conversion functions.
Constructor & Destructor Documentation
CTextureBase()
CTextureBase::CTextureBase () default
~CTextureBase()
CTextureBase::~CTextureBase () default
Member Function Documentation
Allocate()
void CTextureBase::Allocate (uint32_t width, uint32_t height, XB_FMT format)
References KODI::MEMORY::AlignedFree(), KODI::MEMORY::AlignedMalloc(), GetPitch(), CServiceBroker::GetRenderSystem(), GetRows(), KD_TEX_FMT_S3TC, KD_TEX_FMT_TYPE_MASK, CLog::Log(), LOGERROR, m_format, m_imageHeight, m_imageWidth, m_orientation, m_originalHeight, m_originalWidth, m_pixels, m_textureFormat, m_textureHeight, m_textureWidth, PadPow2(), and SetKDFormat().
Referenced by ConvertToLegacy(), CTexture::CTexture(), CTexture::LoadIImage(), CTexture::LoadPaletted(), and CTexture::Update().
ClampToEdge()
void CTextureBase::ClampToEdge ()
References GetBlockSize(), GetPitch(), GetRows(), m_imageHeight, m_imageWidth, m_pixels, m_textureHeight, and m_textureWidth.
Referenced by CTexture::LoadIImage(), CTexture::LoadPaletted(), and CTexture::Update().
ConvertToLegacy()
bool CTextureBase::ConvertToLegacy (uint32_t width, uint32_t height, uint8_t * src) protected
Textures might be in a single/dual channel format with L/A/I/LA swizzle. DX and GLES 2.0 don't handle some/all at the moment. This function can convert the texture into a traditional BGRA format.
References Allocate(), GetPitch(), GetRows(), KD_TEX_FMT_SDR_BGRA8, KD_TEX_FMT_SDR_R8, KD_TEX_FMT_SDR_RG8, KD_TEX_SWIZ_111R, KD_TEX_SWIZ_RGBA, KD_TEX_SWIZ_RRR1, KD_TEX_SWIZ_RRRG, KD_TEX_SWIZ_RRRR, m_format, m_pixels, m_textureFormat, m_textureSwizzle, and XB_FMT_A8R8G8B8.
Referenced by CTexture::UploadFromMemory().
GetBlockHeight()
uint32_t CTextureBase::GetBlockHeight () const protected
References KD_TEX_FMT_ASTC_HDR_10x10, KD_TEX_FMT_ASTC_HDR_10x5, KD_TEX_FMT_ASTC_HDR_10x6, KD_TEX_FMT_ASTC_HDR_10x8, KD_TEX_FMT_ASTC_HDR_12x10, KD_TEX_FMT_ASTC_HDR_12x12, KD_TEX_FMT_ASTC_HDR_4x4, KD_TEX_FMT_ASTC_HDR_5x4, KD_TEX_FMT_ASTC_HDR_5x5, KD_TEX_FMT_ASTC_HDR_6x5, KD_TEX_FMT_ASTC_HDR_6x6, KD_TEX_FMT_ASTC_HDR_8x5, KD_TEX_FMT_ASTC_HDR_8x6, KD_TEX_FMT_ASTC_HDR_8x8, KD_TEX_FMT_ASTC_LDR_10x10, KD_TEX_FMT_ASTC_LDR_10x5, KD_TEX_FMT_ASTC_LDR_10x6, KD_TEX_FMT_ASTC_LDR_10x8, KD_TEX_FMT_ASTC_LDR_12x10, KD_TEX_FMT_ASTC_LDR_12x12, KD_TEX_FMT_ASTC_LDR_4x4, KD_TEX_FMT_ASTC_LDR_5x4, KD_TEX_FMT_ASTC_LDR_5x5, KD_TEX_FMT_ASTC_LDR_6x5, KD_TEX_FMT_ASTC_LDR_6x6, KD_TEX_FMT_ASTC_LDR_8x5, KD_TEX_FMT_ASTC_LDR_8x6, KD_TEX_FMT_ASTC_LDR_8x8, KD_TEX_FMT_BPTC_RGB16F, KD_TEX_FMT_BPTC_RGBA8, KD_TEX_FMT_ETC1, KD_TEX_FMT_ETC2_R11, KD_TEX_FMT_ETC2_RG11, KD_TEX_FMT_ETC2_RGB8, KD_TEX_FMT_ETC2_RGB8_A1, KD_TEX_FMT_ETC2_RGBA8, KD_TEX_FMT_HDR_R11F_G11F_B10F, KD_TEX_FMT_HDR_R16f, KD_TEX_FMT_HDR_RG16f, KD_TEX_FMT_HDR_RGB10_A2, KD_TEX_FMT_HDR_RGB9_E5, KD_TEX_FMT_HDR_RGBA16f, KD_TEX_FMT_RGTC_R11, KD_TEX_FMT_RGTC_RG11, KD_TEX_FMT_S3TC_RGB8, KD_TEX_FMT_S3TC_RGB8_A1, KD_TEX_FMT_S3TC_RGB8_A4, KD_TEX_FMT_S3TC_RGBA8, KD_TEX_FMT_SDR_BGRA8, KD_TEX_FMT_SDR_R5G6B5, KD_TEX_FMT_SDR_R8, KD_TEX_FMT_SDR_RG8, KD_TEX_FMT_SDR_RGB5_A1, KD_TEX_FMT_SDR_RGB8, KD_TEX_FMT_SDR_RGBA4, KD_TEX_FMT_SDR_RGBA8, KD_TEX_FMT_YUV_YUYV8, and m_textureFormat.
Referenced by GetRows().
GetBlockSize()
uint32_t CTextureBase::GetBlockSize () const protected
return the size of a compression block (tile) in bytes.
References KD_TEX_FMT_ASTC_HDR_10x10, KD_TEX_FMT_ASTC_HDR_10x5, KD_TEX_FMT_ASTC_HDR_10x6, KD_TEX_FMT_ASTC_HDR_10x8, KD_TEX_FMT_ASTC_HDR_12x10, KD_TEX_FMT_ASTC_HDR_12x12, KD_TEX_FMT_ASTC_HDR_4x4, KD_TEX_FMT_ASTC_HDR_5x4, KD_TEX_FMT_ASTC_HDR_5x5, KD_TEX_FMT_ASTC_HDR_6x5, KD_TEX_FMT_ASTC_HDR_6x6, KD_TEX_FMT_ASTC_HDR_8x5, KD_TEX_FMT_ASTC_HDR_8x6, KD_TEX_FMT_ASTC_HDR_8x8, KD_TEX_FMT_ASTC_LDR_10x10, KD_TEX_FMT_ASTC_LDR_10x5, KD_TEX_FMT_ASTC_LDR_10x6, KD_TEX_FMT_ASTC_LDR_10x8, KD_TEX_FMT_ASTC_LDR_12x10, KD_TEX_FMT_ASTC_LDR_12x12, KD_TEX_FMT_ASTC_LDR_4x4, KD_TEX_FMT_ASTC_LDR_5x4, KD_TEX_FMT_ASTC_LDR_5x5, KD_TEX_FMT_ASTC_LDR_6x5, KD_TEX_FMT_ASTC_LDR_6x6, KD_TEX_FMT_ASTC_LDR_8x5, KD_TEX_FMT_ASTC_LDR_8x6, KD_TEX_FMT_ASTC_LDR_8x8, KD_TEX_FMT_BPTC_RGB16F, KD_TEX_FMT_BPTC_RGBA8, KD_TEX_FMT_ETC1, KD_TEX_FMT_ETC2_R11, KD_TEX_FMT_ETC2_RG11, KD_TEX_FMT_ETC2_RGB8, KD_TEX_FMT_ETC2_RGB8_A1, KD_TEX_FMT_ETC2_RGBA8, KD_TEX_FMT_HDR_R11F_G11F_B10F, KD_TEX_FMT_HDR_R16f, KD_TEX_FMT_HDR_RG16f, KD_TEX_FMT_HDR_RGB10_A2, KD_TEX_FMT_HDR_RGB9_E5, KD_TEX_FMT_HDR_RGBA16f, KD_TEX_FMT_RGTC_R11, KD_TEX_FMT_RGTC_RG11, KD_TEX_FMT_S3TC_RGB8, KD_TEX_FMT_S3TC_RGB8_A1, KD_TEX_FMT_S3TC_RGB8_A4, KD_TEX_FMT_S3TC_RGBA8, KD_TEX_FMT_SDR_BGRA8, KD_TEX_FMT_SDR_R5G6B5, KD_TEX_FMT_SDR_R8, KD_TEX_FMT_SDR_RG8, KD_TEX_FMT_SDR_RGB5_A1, KD_TEX_FMT_SDR_RGB8, KD_TEX_FMT_SDR_RGBA4, KD_TEX_FMT_SDR_RGBA8, KD_TEX_FMT_YUV_YUYV8, and m_textureFormat.
Referenced by ClampToEdge(), and GetPitch().
GetBlockWidth()
uint32_t CTextureBase::GetBlockWidth () const protected
References KD_TEX_FMT_ASTC_HDR_10x10, KD_TEX_FMT_ASTC_HDR_10x5, KD_TEX_FMT_ASTC_HDR_10x6, KD_TEX_FMT_ASTC_HDR_10x8, KD_TEX_FMT_ASTC_HDR_12x10, KD_TEX_FMT_ASTC_HDR_12x12, KD_TEX_FMT_ASTC_HDR_4x4, KD_TEX_FMT_ASTC_HDR_5x4, KD_TEX_FMT_ASTC_HDR_5x5, KD_TEX_FMT_ASTC_HDR_6x5, KD_TEX_FMT_ASTC_HDR_6x6, KD_TEX_FMT_ASTC_HDR_8x5, KD_TEX_FMT_ASTC_HDR_8x6, KD_TEX_FMT_ASTC_HDR_8x8, KD_TEX_FMT_ASTC_LDR_10x10, KD_TEX_FMT_ASTC_LDR_10x5, KD_TEX_FMT_ASTC_LDR_10x6, KD_TEX_FMT_ASTC_LDR_10x8, KD_TEX_FMT_ASTC_LDR_12x10, KD_TEX_FMT_ASTC_LDR_12x12, KD_TEX_FMT_ASTC_LDR_4x4, KD_TEX_FMT_ASTC_LDR_5x4, KD_TEX_FMT_ASTC_LDR_5x5, KD_TEX_FMT_ASTC_LDR_6x5, KD_TEX_FMT_ASTC_LDR_6x6, KD_TEX_FMT_ASTC_LDR_8x5, KD_TEX_FMT_ASTC_LDR_8x6, KD_TEX_FMT_ASTC_LDR_8x8, KD_TEX_FMT_BPTC_RGB16F, KD_TEX_FMT_BPTC_RGBA8, KD_TEX_FMT_ETC1, KD_TEX_FMT_ETC2_R11, KD_TEX_FMT_ETC2_RG11, KD_TEX_FMT_ETC2_RGB8, KD_TEX_FMT_ETC2_RGB8_A1, KD_TEX_FMT_ETC2_RGBA8, KD_TEX_FMT_HDR_R11F_G11F_B10F, KD_TEX_FMT_HDR_R16f, KD_TEX_FMT_HDR_RG16f, KD_TEX_FMT_HDR_RGB10_A2, KD_TEX_FMT_HDR_RGB9_E5, KD_TEX_FMT_HDR_RGBA16f, KD_TEX_FMT_RGTC_R11, KD_TEX_FMT_RGTC_RG11, KD_TEX_FMT_S3TC_RGB8, KD_TEX_FMT_S3TC_RGB8_A1, KD_TEX_FMT_S3TC_RGB8_A4, KD_TEX_FMT_S3TC_RGBA8, KD_TEX_FMT_SDR_BGRA8, KD_TEX_FMT_SDR_R5G6B5, KD_TEX_FMT_SDR_R8, KD_TEX_FMT_SDR_RG8, KD_TEX_FMT_SDR_RGB5_A1, KD_TEX_FMT_SDR_RGB8, KD_TEX_FMT_SDR_RGBA4, KD_TEX_FMT_SDR_RGBA8, KD_TEX_FMT_YUV_YUYV8, and m_textureFormat.
Referenced by GetPitch().
GetCacheMemory()
bool CTextureBase::GetCacheMemory () const inline
returns true if a shadow copy is kept on the CPU side.
References m_bCacheMemory.
GetHeight()
uint32_t CTextureBase::GetHeight () const inline
return the total height of "active" area, which might be equal or lower than the texture height due to alignment.
References m_imageHeight.
Referenced by CPicture::CacheTexture(), CSlideShowPicDX::Render(), CSlideShowPicGL::Render(), CSlideShowPicGLES::Render(), and CPicture::ResizeTexture().
GetOrientation()
int32_t CTextureBase::GetOrientation () const inline
References m_orientation.
Referenced by CPicture::CacheTexture().
GetOriginalHeight()
uint32_t CTextureBase::GetOriginalHeight () const inline
return the original height of the image, before scaling/cropping
References m_originalHeight.
GetOriginalWidth()
uint32_t CTextureBase::GetOriginalWidth () const inline
return the original width of the image, before scaling/cropping
References m_originalWidth.
GetPitch() [1/2]
uint32_t CTextureBase::GetPitch () const inline
return the size of one row in bytes.
References GetPitch(), and m_textureWidth.
Referenced by Allocate(), CPicture::CacheTexture(), ClampToEdge(), ConvertToLegacy(), CGLESTexture::GetFormatGLES20(), GetPitch(), CTexture::LoadIImage(), CTexture::LoadPaletted(), CDXTexture::LoadToGPU(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), CPicture::ResizeTexture(), CTexture::Update(), and CTexture::UploadFromMemory().
GetPitch() [2/2]
uint32_t CTextureBase::GetPitch (uint32_t width) const protected
References GetBlockSize(), GetBlockWidth(), KD_TEX_FMT_SDR_RGB8, and m_textureFormat.
GetPixels()
uint8_t * CTextureBase::GetPixels () const inline
returns a pointer to the staging texture.
References m_pixels.
Referenced by CPicture::CacheTexture(), and CPicture::ResizeTexture().
GetRows() [1/2]
uint32_t CTextureBase::GetRows () const inline
return the number of rows (number of blocks in the Y direction).
References GetRows(), and m_textureHeight.
Referenced by Allocate(), ClampToEdge(), ConvertToLegacy(), GetRows(), CTexture::LoadIImage(), CDXTexture::LoadToGPU(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), CTexture::Update(), and CTexture::UploadFromMemory().
GetRows() [2/2]
uint32_t CTextureBase::GetRows (uint32_t height) const protected
References GetBlockHeight().
GetScalingMethod()
TEXTURE_SCALING CTextureBase::GetScalingMethod () const inline
returns the scaling method.
References m_scalingMethod.
GetTextureHeight()
uint32_t CTextureBase::GetTextureHeight () const inline
return the total height of the texture, which might be scaled to fit its displayed size.
References m_textureHeight.
Referenced by CSlideShowPicDX::Render(), CSlideShowPicGL::Render(), and CSlideShowPicGLES::Render().
GetTextureWidth()
uint32_t CTextureBase::GetTextureWidth () const inline
return the total width of the texture, which might be scaled to fit its displayed size.
References m_textureWidth.
Referenced by CTexture::LoadIImage(), CSlideShowPicDX::Render(), CSlideShowPicGL::Render(), and CSlideShowPicGLES::Render().
GetWidth()
uint32_t CTextureBase::GetWidth () const inline
return the total width of "active" area, which might be equal or lower than the texture width due to alignment.
References m_imageWidth.
Referenced by CPicture::CacheTexture(), CSlideShowPicDX::Render(), CSlideShowPicGL::Render(), CSlideShowPicGLES::Render(), and CPicture::ResizeTexture().
HasAlpha()
bool CTextureBase::HasAlpha () const inline
References KD_TEX_ALPHA_OPAQUE, and m_textureAlpha.
IsMipmapped()
bool CTextureBase::IsMipmapped () const inline
return true if we want to mipmap
References m_mipmapping.
Referenced by CDXTexture::LoadToGPU(), CGLTexture::LoadToGPU(), and CGLESTexture::LoadToGPU().
PadPow2()
uint32_t CTextureBase::PadPow2 (uint32_t x) static
rounds to power of two. deprecated.
Referenced by Allocate(), CGUIFontTTF::Load(), CGUIFontTTFGL::ReallocTexture(), and CGUIFontTTFGLES::ReallocTexture().
SetAlpha()
void CTextureBase::SetAlpha (bool hasAlpha) inline
References KD_TEX_ALPHA_OPAQUE, KD_TEX_ALPHA_STRAIGHT, and m_textureAlpha.
SetCacheMemory()
void CTextureBase::SetCacheMemory (bool bCacheMemory) inline
retains a shadow copy of the texture on the CPU side.
References m_bCacheMemory.
SetKDFormat()
void CTextureBase::SetKDFormat (XB_FMT xbFMT) protected
References KD_TEX_FMT_S3TC_RGB8, KD_TEX_FMT_S3TC_RGB8_A4, KD_TEX_FMT_S3TC_RGBA8, KD_TEX_FMT_SDR_BGRA8, KD_TEX_FMT_SDR_R8, KD_TEX_FMT_SDR_RGB8, KD_TEX_FMT_SDR_RGBA8, KD_TEX_FMT_UNKNOWN, KD_TEX_SWIZ_111R, m_textureFormat, m_textureSwizzle, XB_FMT_A8, XB_FMT_A8R8G8B8, XB_FMT_DXT1, XB_FMT_DXT3, XB_FMT_DXT5, XB_FMT_DXT5_YCoCg, XB_FMT_RGB8, XB_FMT_RGBA8, and XB_FMT_UNKNOWN.
Referenced by Allocate().
SetMipmapping()
void CTextureBase::SetMipmapping () inline
sets mipmapping. do not use in new code. will be replaced with proper scaling.
References m_mipmapping.
SetOrientation()
void CTextureBase::SetOrientation (int orientation) inline
References m_orientation.
SetScalingMethod()
void CTextureBase::SetScalingMethod (TEXTURE_SCALING scalingMethod) inline
sets the scaling method. scanout systems might support more than NN/linear.
References m_scalingMethod.
SwapBlueRed()
bool CTextureBase::SwapBlueRed (uint8_t * pixels, uint32_t height, uint32_t pitch, uint32_t elements = 4, uint32_t offset = 0) static
swaps the blue/red channel. deprecated in this form.
Referenced by CGLESTexture::GetFormatGLES20().
Member Data Documentation
m_bCacheMemory
bool CTextureBase::m_bCacheMemory {false} protected
Referenced by GetCacheMemory(), CDXTexture::LoadToGPU(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), SetCacheMemory(), and CTexture::UploadFromMemory().
m_format
XB_FMT CTextureBase::m_format {XB_FMT_UNKNOWN} protected
Referenced by Allocate(), ConvertToLegacy(), CDXTexture::GetFormat(), CTexture::LoadFromMemory(), and CDXTexture::LoadToGPU().
m_imageHeight
uint32_t CTextureBase::m_imageHeight {0} protected
Referenced by Allocate(), ClampToEdge(), GetHeight(), CTexture::LoadFromMemory(), CTexture::LoadIImage(), CTexture::LoadPaletted(), and CTexture::UploadFromMemory().
m_imageWidth
uint32_t CTextureBase::m_imageWidth {0} protected
Referenced by Allocate(), ClampToEdge(), GetWidth(), CTexture::LoadFromMemory(), CTexture::LoadIImage(), CTexture::LoadPaletted(), and CTexture::UploadFromMemory().
m_loadedToGPU
bool CTextureBase::m_loadedToGPU {false} protected
Referenced by CTexture::CTexture(), CDXTexture::LoadToGPU(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), and CTexture::UploadFromMemory().
m_mipmapping
bool CTextureBase::m_mipmapping {false} protected
Referenced by IsMipmapped(), and SetMipmapping().
m_orientation
int32_t CTextureBase::m_orientation {0} protected
Referenced by Allocate(), GetOrientation(), CTexture::LoadIImage(), and SetOrientation().
m_originalHeight
uint32_t CTextureBase::m_originalHeight {0} protected
original image height before scaling or cropping
Referenced by Allocate(), GetOriginalHeight(), CTexture::LoadFromMemory(), CTexture::LoadIImage(), and CTexture::UploadFromMemory().
m_originalWidth
uint32_t CTextureBase::m_originalWidth {0} protected
original image width before scaling or cropping
Referenced by Allocate(), GetOriginalWidth(), CTexture::LoadFromMemory(), CTexture::LoadIImage(), and CTexture::UploadFromMemory().
m_pixels
uint8_t* CTextureBase::m_pixels {nullptr} protected
Referenced by Allocate(), ClampToEdge(), ConvertToLegacy(), CTexture::CTexture(), CGLESTexture::GetFormatGLES20(), GetPixels(), CTexture::LoadIImage(), CTexture::LoadPaletted(), CDXTexture::LoadToGPU(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), CTexture::Update(), CTexture::UploadFromMemory(), and CTexture::~CTexture().
m_scalingMethod
TEXTURE_SCALING CTextureBase::m_scalingMethod {TEXTURE_SCALING::LINEAR} protected
Referenced by GetScalingMethod(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), and SetScalingMethod().
m_textureAlpha
KD_TEX_ALPHA CTextureBase::m_textureAlpha {KD_TEX_ALPHA_STRAIGHT} protected
Referenced by HasAlpha(), CTexture::LoadFromMemory(), CTexture::LoadIImage(), SetAlpha(), and CTexture::UploadFromMemory().
m_textureColorspace
KD_TEX_COL CTextureBase::m_textureColorspace {KD_TEX_COL_REC709} protected
m_textureFormat
KD_TEX_FMT CTextureBase::m_textureFormat {KD_TEX_FMT_UNKNOWN} protected
Referenced by Allocate(), ConvertToLegacy(), GetBlockHeight(), GetBlockSize(), GetBlockWidth(), CGLESTexture::GetFormatGLES20(), GetPitch(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), SetKDFormat(), and CTexture::UploadFromMemory().
m_textureHeight
uint32_t CTextureBase::m_textureHeight {0} protected
Referenced by Allocate(), ClampToEdge(), CDXTexture::CreateTextureObject(), CGLESTexture::GetFormatGLES20(), GetRows(), GetTextureHeight(), CDXTexture::LoadToGPU(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), CTexture::Update(), and CTexture::UploadFromMemory().
m_textureSwizzle
KD_TEX_SWIZ CTextureBase::m_textureSwizzle {KD_TEX_SWIZ_RGBA} protected
Referenced by ConvertToLegacy(), CGLESTexture::GetFormatGLES20(), SetKDFormat(), CGLTexture::SetSwizzle(), CGLESTexture::SetSwizzle(), and CTexture::UploadFromMemory().
m_textureTransfer
KD_TEX_TRANSFER CTextureBase::m_textureTransfer {KD_TEX_TRANSFER_SRGB} protected
m_textureWidth
uint32_t CTextureBase::m_textureWidth {0} protected
Referenced by Allocate(), ClampToEdge(), CDXTexture::CreateTextureObject(), GetPitch(), GetTextureWidth(), CDXTexture::LoadToGPU(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), CTexture::Update(), and CTexture::UploadFromMemory().
The documentation for this class was generated from the following files:
TextureBase.h
TextureBase.cpp