Kodi Documentation: ADDON::Interface_GUIControlSettingsSlider Struct Reference
ADDON::Interface_GUIControlSettingsSlider Struct Reference
Global gui Add-on to Kodi callback functions.
#include <SettingsSlider.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
callback functions from add-on to kodi
static void set_enabled (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled)
static void set_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *text)
static void reset (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_int_range (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int start, int end)
static void set_int_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int value)
static int get_int_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_int_interval (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int interval)
static void set_percentage (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float percent)
static float get_percentage (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_float_range (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float start, float end)
static void set_float_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float value)
static float get_float_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_float_interval (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float interval)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold general gui functions and initialize also all other gui related types not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/controls/SettingsSlider.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIControlSettingsSlider::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_settings_slider, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
get_float_value()
float ADDON::Interface_GUIControlSettingsSlider::get_float_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUISliderControl::GetFloatValue(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_int_value()
int ADDON::Interface_GUIControlSettingsSlider::get_int_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUISliderControl::GetIntValue(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_percentage()
float ADDON::Interface_GUIControlSettingsSlider::get_percentage (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUISliderControl::GetPercentage(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIControlSettingsSlider::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_settings_slider, get_float_value(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::get_float_value, get_int_value(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::get_int_value, get_percentage(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::get_percentage, AddonToKodiFuncTable_Addon::kodi_gui, reset(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::reset, set_enabled(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_enabled, set_float_interval(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_float_interval, set_float_range(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_float_range, set_float_value(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_float_value, set_int_interval(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_int_interval, set_int_range(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_int_range, set_int_value(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_int_value, set_percentage(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_percentage, set_text(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_text, set_visible(), AddonToKodiFuncTable_kodi_gui_control_settings_slider::set_visible, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
reset()
void ADDON::Interface_GUIControlSettingsSlider::reset (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIControl::GetParentID(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_RESET, ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
set_enabled()
void ADDON::Interface_GUIControlSettingsSlider::set_enabled (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUISettingsSliderControl::SetEnabled().
Referenced by Init().
set_float_interval()
void ADDON::Interface_GUIControlSettingsSlider::set_float_interval (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float interval) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUISliderControl::SetFloatInterval().
Referenced by Init().
set_float_range()
void ADDON::Interface_GUIControlSettingsSlider::set_float_range (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float start, float end) static
References end(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUISliderControl::SetFloatRange(), CGUISliderControl::SetType(), and SLIDER_CONTROL_TYPE_FLOAT.
Referenced by Init().
set_float_value()
void ADDON::Interface_GUIControlSettingsSlider::set_float_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float value) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUISliderControl::SetFloatValue(), CGUISliderControl::SetType(), SLIDER_CONTROL_TYPE_FLOAT, and value.
Referenced by Init().
set_int_interval()
void ADDON::Interface_GUIControlSettingsSlider::set_int_interval (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int interval) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUISliderControl::SetIntInterval().
Referenced by Init().
set_int_range()
void ADDON::Interface_GUIControlSettingsSlider::set_int_range (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int start, int end) static
References end(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUISliderControl::SetRange(), CGUISliderControl::SetType(), and SLIDER_CONTROL_TYPE_INT.
Referenced by Init().
set_int_value()
void ADDON::Interface_GUIControlSettingsSlider::set_int_value (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int value) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUISliderControl::SetIntValue(), CGUISliderControl::SetType(), SLIDER_CONTROL_TYPE_INT, and value.
Referenced by Init().
set_percentage()
void ADDON::Interface_GUIControlSettingsSlider::set_percentage (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, float percent) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUISliderControl::SetPercentage(), CGUISliderControl::SetType(), and SLIDER_CONTROL_TYPE_PERCENTAGE.
Referenced by Init().
set_text()
void ADDON::Interface_GUIControlSettingsSlider::set_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * text) static
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIControl::GetParentID(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_SET, ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUIMessage::SetLabel(), and text.
Referenced by Init().
set_visible()
void ADDON::Interface_GUIControlSettingsSlider::set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetVisible().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/controls/SettingsSlider.h
SettingsSlider.cpp