Kodi Documentation: CContextMenuItem Class Reference
CContextMenuItem Class Reference
#include <ContextMenuItem.h>
Public Member Functions
CContextMenuItem ()=default
std::string GetLabel (const CFileItem &item) const override
bool IsVisible (const CFileItem &item) const override
bool IsParentOf (const CContextMenuItem &menuItem) const
bool IsGroup () const override
bool HasParent () const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
bool operator== (const CContextMenuItem &other) const
std::string ToString () const
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
Static Public Member Functions
static CContextMenuItem CreateGroup (const std::string &label, const std::string &parent, const std::string &groupId, const std::string &addonId)
static CContextMenuItem CreateItem (const std::string &label, const std::string &parent, const std::string &library, const std::string &condition, const std::string &addonId, const std::vector< std::string > &args=std::vector< std::string >())
Private Attributes
std::string m_label
std::string m_parent
std::string m_groupId
std::string m_library
std::string m_addonId
std::vector< std::string > m_args
std::string m_visibilityCondition
std::shared_ptr< INFO::InfoBool > m_infoBool
bool m_infoBoolRegistered {false}
Friends
class ADDON::CContextMenuAddon
Constructor & Destructor Documentation
CContextMenuItem()
CContextMenuItem::CContextMenuItem () default
Member Function Documentation
CreateGroup()
CContextMenuItem CContextMenuItem::CreateGroup (const std::string & label, const std::string & parent, const std::string & groupId, const std::string & addonId) static
References label, m_addonId, m_groupId, m_label, and m_parent.
Referenced by ADDON::CContextMenuAddon::ParseMenu().
CreateItem()
CContextMenuItem CContextMenuItem::CreateItem (const std::string & label, const std::string & parent, const std::string & library, const std::string & condition, const std::string & addonId, const std::vector< std::string > & args = std::vector<std::string>()) static
References label, m_addonId, m_args, m_label, m_library, m_parent, and m_visibilityCondition.
Referenced by ADDON::CContextMenuAddon::CContextMenuAddon(), and ADDON::CContextMenuAddon::ParseMenu().
Execute()
bool CContextMenuItem::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References ADDON::CHOICE_YES, CServiceBroker::GetAddonMgr(), CScriptInvocationManager::GetInstance(), CServiceBroker::GetXBPython(), IsGroup(), m_addonId, m_args, and m_library.
GetLabel()
std::string CContextMenuItem::GetLabel (const CFileItem & item) const inline override virtual
Implements IContextMenuItem.
References m_label.
Referenced by CContextMenuManager::IsVisible().
HasParent()
bool CContextMenuItem::HasParent () const override virtual
Reimplemented from IContextMenuItem.
References m_parent.
IsGroup()
bool CContextMenuItem::IsGroup () const override virtual
Reimplemented from IContextMenuItem.
References m_groupId.
Referenced by Execute(), CContextMenuManager::IsVisible(), IsVisible(), operator==(), and ToString().
IsParentOf()
bool CContextMenuItem::IsParentOf (const CContextMenuItem & menuItem) const
References m_groupId, and m_parent.
IsVisible()
bool CContextMenuItem::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References INFO::DEFAULT_CONTEXT, CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), IsGroup(), m_infoBool, m_infoBoolRegistered, m_visibilityCondition, and CGUIInfoManager::Register().
Referenced by CContextMenuManager::IsVisible().
operator==()
bool CContextMenuItem::operator== (const CContextMenuItem & other) const
References IsGroup(), m_addonId, m_args, m_groupId, m_library, and m_parent.
ToString()
std::string CContextMenuItem::ToString () const
References IsGroup(), m_addonId, m_groupId, m_library, and m_parent.
Friends And Related Symbol Documentation
ADDON::CContextMenuAddon
friend class ADDON::CContextMenuAddon friend
Member Data Documentation
m_addonId
std::string CContextMenuItem::m_addonId private
Referenced by CreateGroup(), CreateItem(), Execute(), operator==(), and ToString().
m_args
std::vector<std::string> CContextMenuItem::m_args private
Referenced by CreateItem(), Execute(), and operator==().
m_groupId
std::string CContextMenuItem::m_groupId private
Referenced by ADDON::CContextMenuAddon::CContextMenuAddon(), CreateGroup(), IsGroup(), IsParentOf(), operator==(), and ToString().
m_infoBool
std::shared_ptr<INFO::InfoBool> CContextMenuItem::m_infoBool mutable private
Referenced by IsVisible().
m_infoBoolRegistered
bool CContextMenuItem::m_infoBoolRegistered {false} mutable private
Referenced by IsVisible().
m_label
std::string CContextMenuItem::m_label private
Referenced by CreateGroup(), CreateItem(), and GetLabel().
m_library
std::string CContextMenuItem::m_library private
Referenced by CreateItem(), Execute(), operator==(), and ToString().
m_parent
std::string CContextMenuItem::m_parent private
Referenced by CreateGroup(), CreateItem(), HasParent(), IsParentOf(), operator==(), and ToString().
m_visibilityCondition
std::string CContextMenuItem::m_visibilityCondition private
Referenced by CreateItem(), and IsVisible().
The documentation for this class was generated from the following files:
ContextMenuItem.h
ContextMenuItem.cpp