Kodi Documentation: KODI::UTILS::CDisplayInfo Class Reference
KODI::UTILS::CDisplayInfo Class Reference
#include <DisplayInfo.h>
Classes
struct DiInfoDeleter
Public Member Functions
~CDisplayInfo ()
bool SupportsHDRStaticMetadataType1 () const
bool SupportsEOTF (Eotf eotf) const
bool SupportsColorimetry (Colorimetry colorimetry) const
Static Public Member Functions
static std::unique_ptr< CDisplayInfo > Create (const std::vector< uint8_t > &edid)
Private Member Functions
CDisplayInfo (const std::vector< uint8_t > &edid)
bool IsValid () const
void Parse ()
void LogInfo () const
Private Attributes
std::unique_ptr< di_info, DiInfoDeleter > m_info
std::string m_make
std::string m_model
const di_cta_colorimetry_block * m_colorimetry = nullptr
const di_cta_hdr_static_metadata_block * m_hdr_static_metadata = nullptr
Constructor & Destructor Documentation
~CDisplayInfo()
CDisplayInfo::~CDisplayInfo () default
CDisplayInfo()
CDisplayInfo::CDisplayInfo (const std::vector< uint8_t > & edid) explicit private
Member Function Documentation
Create()
std::unique_ptr< CDisplayInfo > CDisplayInfo::Create (const std::vector< uint8_t > & edid) static
Referenced by KODI::WINDOWING::GBM::CWinSystemGbm::InitWindowSystem().
IsValid()
bool CDisplayInfo::IsValid () const private
References CLog::Log(), LOGERROR, and KODI::UTILS::StringUtils::Split().
LogInfo()
void CDisplayInfo::LogInfo () const private
References CLog::Log(), and LOGINFO.
Parse()
void CDisplayInfo::Parse () private
SupportsColorimetry()
bool CDisplayInfo::SupportsColorimetry (Colorimetry colorimetry) const
SupportsEOTF()
bool CDisplayInfo::SupportsEOTF (Eotf eotf) const
SupportsHDRStaticMetadataType1()
bool CDisplayInfo::SupportsHDRStaticMetadataType1 () const
Member Data Documentation
m_colorimetry
const di_cta_colorimetry_block* KODI::UTILS::CDisplayInfo::m_colorimetry = nullptr private
m_hdr_static_metadata
const di_cta_hdr_static_metadata_block* KODI::UTILS::CDisplayInfo::m_hdr_static_metadata = nullptr private
m_info
std::unique_ptr<di_info, DiInfoDeleter> KODI::UTILS::CDisplayInfo::m_info private
m_make
std::string KODI::UTILS::CDisplayInfo::m_make private
m_model
std::string KODI::UTILS::CDisplayInfo::m_model private
The documentation for this class was generated from the following files:
DisplayInfo.h
DisplayInfo.cpp