Kodi Documentation: SortUtils Class Reference
SortUtils Class Reference
#include <SortUtils.h>
Public Types
typedef std::string(* SortPreparator) (SortAttribute, const SortItem &)
typedef bool(* Sorter) (const DatabaseResult &, const DatabaseResult &)
typedef bool(* SorterIndirect) (const SortItemPtr &, const SortItemPtr &)
Static Public Member Functions
static SORT_METHOD TranslateOldSortMethod (SortBy sortBy, bool ignoreArticle)
static SortDescription TranslateOldSortMethod (SORT_METHOD sortBy)
static SortBy SortMethodFromString (const std::string &sortMethod)
static const std::string & SortMethodToString (SortBy sortMethod)
static SortOrder SortOrderFromString (const std::string &sortOrder)
static const std::string & SortOrderToString (SortOrder sortOrder)
static int GetSortLabel (SortBy sortBy)
retrieve the label id associated with a sort method for displaying in the UI.
static void Sort (SortBy sortBy, SortOrder sortOrder, SortAttribute attributes, DatabaseResults &items, int limitEnd=-1, int limitStart=0)
static void Sort (SortBy sortBy, SortOrder sortOrder, SortAttribute attributes, SortItems &items, int limitEnd=-1, int limitStart=0)
static void Sort (const SortDescription &sortDescription, DatabaseResults &items)
static void Sort (const SortDescription &sortDescription, SortItems &items)
static bool SortFromDataset (const SortDescription &sortDescription, const MediaType &mediaType, const std::unique_ptr< dbiplus::Dataset > &dataset, DatabaseResults &results)
static void GetFieldsForSQLSort (const MediaType &mediaType, SortBy sortMethod, FieldList &fields)
static const Fields & GetFieldsForSorting (SortBy sortBy)
static std::string RemoveArticles (const std::string &label)
Static Private Member Functions
static const SortPreparator & getPreparator (SortBy sortBy)
static Sorter getSorter (SortOrder sortOrder, SortAttribute attributes)
static SorterIndirect getSorterIndirect (SortOrder sortOrder, SortAttribute attributes)
Static Private Attributes
static std::map< SortBy, SortPreparator > m_preparators = fillPreparators()
static std::map< SortBy, Fields > m_sortingFields = fillSortingFields()
Member Typedef Documentation
Sorter
typedef bool(* SortUtils::Sorter) (const DatabaseResult &, const DatabaseResult &)
SorterIndirect
typedef bool(* SortUtils::SorterIndirect) (const SortItemPtr &, const SortItemPtr &)
SortPreparator
typedef std::string(* SortUtils::SortPreparator) (SortAttribute, const SortItem &)
Member Function Documentation
GetFieldsForSorting()
const Fields & SortUtils::GetFieldsForSorting (SortBy sortBy) static
References m_sortingFields, and SortByNone.
Referenced by Sort(), Sort(), CFileItemList::Sort(), SortFromDataset(), and TEST().
GetFieldsForSQLSort()
void SortUtils::GetFieldsForSQLSort (const MediaType & mediaType, SortBy sortMethod, FieldList & fields) static
References FieldAlbum, FieldAlbumArtist, FieldAlbumType, FieldArtist, FieldBPM, FieldDateAdded, FieldFilename, FieldGenre, FieldId, FieldLastPlayed, FieldOrigDate, FieldPath, FieldPlaycount, FieldRating, fields, FieldStartOffset, FieldTime, FieldTitle, FieldTotalDiscs, FieldTrackNumber, FieldUserRating, FieldVotes, FieldYear, MediaTypeAlbum, MediaTypeArtist, MediaTypeNone, MediaTypeSong, SortByAlbum, SortByAlbumType, SortByArtist, SortByArtistThenYear, SortByBPM, SortByDateAdded, SortByFile, SortByGenre, SortByLabel, SortByLastPlayed, SortByOrigDate, SortByPlaycount, SortByRating, SortByTime, SortByTitle, SortByTotalDiscs, SortByTrackNumber, SortByUserRating, SortByVotes, and SortByYear.
Referenced by CMusicDatabase::GetOrderFilter().
getPreparator()
const SortUtils::SortPreparator & SortUtils::getPreparator (SortBy sortBy) static private
References m_preparators, and SortByNone.
Referenced by Sort(), and Sort().
getSorter()
SortUtils::Sorter SortUtils::getSorter (SortOrder sortOrder, SortAttribute attributes) static private
References SortAttributeIgnoreFolders, SorterAscending(), SorterDescending(), SorterIgnoreFoldersAscending(), SorterIgnoreFoldersDescending(), and SortOrderDescending.
Referenced by Sort().
getSorterIndirect()
SortUtils::SorterIndirect SortUtils::getSorterIndirect (SortOrder sortOrder, SortAttribute attributes) static private
References SortAttributeIgnoreFolders, SorterIndirectAscending(), SorterIndirectDescending(), SorterIndirectIgnoreFoldersAscending(), SorterIndirectIgnoreFoldersDescending(), and SortOrderDescending.
Referenced by Sort().
GetSortLabel()
int SortUtils::GetSortLabel (SortBy sortBy) static
retrieve the label id associated with a sort method for displaying in the UI.
Parameters
sortBy the sort method in question.
Returns
the label id of the sort method.
References t, and table.
Referenced by CGUIViewState::AddPlaylistOrder(), CGUIDialogSmartPlaylistEditor::OnOrder(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
RemoveArticles()
std::string SortUtils::RemoveArticles (const std::string & label) static
References g_langInfo, and label.
Referenced by ArrayToString(), ByAlbum(), ByArtist(), ByArtistThenYear(), ByLabel(), ByOrigDate(), ByOriginalTitle(), BySortTitle(), ByTitle(), ByYear(), and CGUIBaseContainer::OnJumpLetter().
Sort() [1/4]
void SortUtils::Sort (const SortDescription & sortDescription, DatabaseResults & items) static
References SortDescription::limitEnd, SortDescription::limitStart, Sort(), SortDescription::sortAttributes, SortDescription::sortBy, and SortDescription::sortOrder.
Sort() [2/4]
void SortUtils::Sort (const SortDescription & sortDescription, SortItems & items) static
References SortDescription::limitEnd, SortDescription::limitStart, Sort(), SortDescription::sortAttributes, SortDescription::sortBy, and SortDescription::sortOrder.
Sort() [3/4]
void SortUtils::Sort (SortBy sortBy, SortOrder sortOrder, SortAttribute attributes, DatabaseResults & items, int limitEnd = -1, int limitStart = 0) static
References CVariant::ConstNullVariant, FieldSort, g_charsetConverter, GetFieldsForSorting(), getPreparator(), getSorter(), and SortByNone.
Referenced by Sort(), Sort(), CFileItemList::Sort(), SortFromDataset(), TEST(), and TEST().
Sort() [4/4]
void SortUtils::Sort (SortBy sortBy, SortOrder sortOrder, SortAttribute attributes, SortItems & items, int limitEnd = -1, int limitStart = 0) static
References CVariant::ConstNullVariant, FieldSort, g_charsetConverter, GetFieldsForSorting(), getPreparator(), getSorterIndirect(), and SortByNone.
SortFromDataset()
bool SortUtils::SortFromDataset (const SortDescription & sortDescription, const MediaType & mediaType, const std::unique_ptr< dbiplus::Dataset > & dataset, DatabaseResults & results) static
References fields, DatabaseUtils::GetDatabaseResults(), GetFieldsForSorting(), DatabaseUtils::GetSelectFields(), SortDescription::limitEnd, SortDescription::limitStart, Sort(), SortDescription::sortBy, and SortByNone.
Referenced by CMusicDatabase::GetDiscsByWhere(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideosByWhere(), CMusicDatabase::GetSongsByWhere(), and CVideoDatabase::GetTvShowsByWhere().
SortMethodFromString()
SortBy SortUtils::SortMethodFromString (const std::string & sortMethod) static
References SortByNone, and sortMethods.
Referenced by JSONRPC::CJSONUtils::ParseSorting(), KODI::PLAYLIST::CSmartPlaylistRule::TranslateOrder(), and CDirectoryProvider::UpdateSort().
SortMethodToString()
const std::string & SortUtils::SortMethodToString (SortBy sortMethod) static
References sortMethods.
Referenced by KODI::PLAYLIST::CSmartPlaylistRule::TranslateOrder().
SortOrderFromString()
SortOrder SortUtils::SortOrderFromString (const std::string & sortOrder) static
References SortOrderNone, and sortOrders.
Referenced by JSONRPC::CJSONUtils::ParseSorting(), and CDirectoryProvider::UpdateSort().
SortOrderToString()
const std::string & SortUtils::SortOrderToString (SortOrder sortOrder) static
References sortOrders.
TranslateOldSortMethod() [1/2]
SortDescription SortUtils::TranslateOldSortMethod (SORT_METHOD sortBy) static
References SortDescription::sortAttributes, SortDescription::sortBy, t, and table.
TranslateOldSortMethod() [2/2]
SORT_METHOD SortUtils::TranslateOldSortMethod (SortBy sortBy, bool ignoreArticle) static
References SORT_METHOD_NONE, SortAttributeIgnoreArticle, t, and table.
Referenced by CViewStateSettings::Load(), and CViewDatabase::UpdateTables().
Member Data Documentation
m_preparators
std::map< SortBy, SortUtils::SortPreparator > SortUtils::m_preparators = fillPreparators() static private
Referenced by getPreparator().
m_sortingFields
std::map< SortBy, Fields > SortUtils::m_sortingFields = fillSortingFields() static private
Referenced by GetFieldsForSorting().
The documentation for this class was generated from the following files:
SortUtils.h
SortUtils.cpp