Kodi Documentation: CDebugRenderer Class Reference
CDebugRenderer Class Reference
#include <DebugRenderer.h>
Classes
class CRenderer
Public Member Functions
CDebugRenderer ()
virtual ~CDebugRenderer ()
void Initialize ()
void Dispose ()
void SetInfo (DEBUG_INFO_PLAYER &info)
void SetInfo (DEBUG_INFO_VIDEO &video, DEBUG_INFO_RENDER &render)
void Render (CRect &src, CRect &dst, CRect &view)
void Flush ()
Protected Attributes
CRenderer m_overlayRenderer
Private Attributes
CSubtitlesAdapter * m_adapter {nullptr}
std::atomic_bool m_isInitialized {false}
std::shared_ptr< CDVDOverlay > m_overlay
Constructor & Destructor Documentation
CDebugRenderer()
CDebugRenderer::CDebugRenderer ()
~CDebugRenderer()
CDebugRenderer::~CDebugRenderer () virtual
References Dispose().
Member Function Documentation
Dispose()
void CDebugRenderer::Dispose ()
References OVERLAY::CRenderer::Flush(), m_adapter, m_isInitialized, m_overlay, and m_overlayRenderer.
Referenced by CRenderManager::ToggleDebug(), CRenderManager::ToggleDebugVideo(), CRenderManager::UnInit(), and ~CDebugRenderer().
Flush()
void CDebugRenderer::Flush ()
References CSubtitlesAdapter::FlushSubtitles(), m_adapter, and m_isInitialized.
Referenced by CRenderManager::Flush().
Initialize()
void CDebugRenderer::Initialize ()
References OVERLAY::CRenderer::AddOverlay(), CSubtitlesAdapter::CreateOverlay(), CSubtitlesAdapter::Initialize(), CLog::Log(), LOGERROR, m_adapter, m_isInitialized, m_overlay, and m_overlayRenderer.
Referenced by CRenderManager::ToggleDebug(), and CRenderManager::ToggleDebugVideo().
Render()
void CDebugRenderer::Render (CRect & src, CRect & dst, CRect & view)
References m_isInitialized, m_overlayRenderer, CDebugRenderer::CRenderer::Render(), and OVERLAY::CRenderer::SetVideoRect().
Referenced by CRenderManager::Render().
SetInfo() [1/2]
void CDebugRenderer::SetInfo (DEBUG_INFO_PLAYER & info)
References CSubtitlesAdapter::AddSubtitle(), CSubtitlesAdapter::FlushSubtitles(), m_adapter, and m_isInitialized.
Referenced by CRenderManager::Render().
SetInfo() [2/2]
void CDebugRenderer::SetInfo (DEBUG_INFO_VIDEO & video, DEBUG_INFO_RENDER & render)
References CSubtitlesAdapter::AddSubtitle(), CSubtitlesAdapter::FlushSubtitles(), m_adapter, m_isInitialized, DEBUG_INFO_VIDEO::metaLight, DEBUG_INFO_VIDEO::metaPrim, DEBUG_INFO_VIDEO::render, DEBUG_INFO_RENDER::renderFlags, DEBUG_INFO_VIDEO::shader, DEBUG_INFO_RENDER::videoOutput, and DEBUG_INFO_VIDEO::videoSource.
Member Data Documentation
m_adapter
CSubtitlesAdapter* CDebugRenderer::m_adapter {nullptr} private
Referenced by Dispose(), Flush(), Initialize(), SetInfo(), and SetInfo().
m_isInitialized
std::atomic_bool CDebugRenderer::m_isInitialized {false} private
Referenced by Dispose(), Flush(), Initialize(), Render(), SetInfo(), and SetInfo().
m_overlay
std::shared_ptr<CDVDOverlay> CDebugRenderer::m_overlay private
Referenced by Dispose(), and Initialize().
m_overlayRenderer
CRenderer CDebugRenderer::m_overlayRenderer protected
Referenced by Dispose(), Initialize(), and Render().
The documentation for this class was generated from the following files:
DebugRenderer.h
DebugRenderer.cpp