Kodi Documentation: KODI::JOYSTICK::CDriverReceiving Class Reference
KODI::JOYSTICK::CDriverReceiving Class Reference
Input » Joystick
Class to translate input events from higher-level features to driver primitives.
#include <DriverReceiving.h>
Public Member Functions
CDriverReceiving (IDriverReceiver *receiver, IButtonMap *buttonMap)
~CDriverReceiving () override=default
bool SetRumbleState (const FeatureName &feature, float magnitude) override
Set the value of a rumble motor.
Public Member Functions inherited from KODI::JOYSTICK::IInputReceiver
virtual ~IInputReceiver ()=default
Private Attributes
IDriverReceiver *const m_receiver
IButtonMap *const m_buttonMap
Detailed Description
Class to translate input events from higher-level features to driver primitives.
A button map is used to translate controller features to driver primitives. The button map has been abstracted away behind the IButtonMap interface so that it can be provided by an add-on.
Constructor & Destructor Documentation
CDriverReceiving()
CDriverReceiving::CDriverReceiving (IDriverReceiver * receiver, IButtonMap * buttonMap)
~CDriverReceiving()
KODI::JOYSTICK::CDriverReceiving::~CDriverReceiving () override default
Member Function Documentation
SetRumbleState()
bool CDriverReceiving::SetRumbleState (const FeatureName & feature, float magnitude) override virtual
Set the value of a rumble motor.
Parameters
feature The name of the motor to rumble
magnitude The motor's new magnitude of vibration in the closed interval [0, 1]
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputReceiver.
References KODI::JOYSTICK::IButtonMap::GetScalar(), KODI::JOYSTICK::CDriverPrimitive::Index(), m_buttonMap, m_receiver, KODI::JOYSTICK::MOTOR, KODI::JOYSTICK::IDriverReceiver::SetMotorState(), and KODI::JOYSTICK::CDriverPrimitive::Type().
Member Data Documentation
m_buttonMap
IButtonMap* const KODI::JOYSTICK::CDriverReceiving::m_buttonMap private
Referenced by SetRumbleState().
m_receiver
IDriverReceiver* const KODI::JOYSTICK::CDriverReceiving::m_receiver private
Referenced by SetRumbleState().
The documentation for this class was generated from the following files:
DriverReceiving.h
DriverReceiving.cpp