Kodi Documentation: KODI::GAME::CPhysicalPort Class Reference
KODI::GAME::CPhysicalPort Class Reference
Games
#include <PhysicalPort.h>
Public Member Functions
CPhysicalPort ()=default
CPhysicalPort (std::string portId, std::vector< std::string > accepts)
Create a controller port.
void Reset ()
const std::string & ID () const
Get the ID of the port.
const std::vector< std::string > & Accepts () const
Get the controllers that can connect to this port.
bool IsCompatible (const std::string &controllerId) const
Check if the controller is compatible with this port.
bool Deserialize (const tinyxml2::XMLElement *pElement)
Private Attributes
std::string m_portId
std::vector< std::string > m_accepts
Constructor & Destructor Documentation
CPhysicalPort() [1/2]
KODI::GAME::CPhysicalPort::CPhysicalPort () default
CPhysicalPort() [2/2]
CPhysicalPort::CPhysicalPort (std::string portId, std::vector< std::string > accepts)
Create a controller port.
Parameters
portId The port's ID
accepts A list of controller IDs that this port accepts
Member Function Documentation
Accepts()
const std::vector< std::string > & KODI::GAME::CPhysicalPort::Accepts () const inline
Get the controllers that can connect to this port.
Returns
A list of controllers that are physically compatible with this port
References m_accepts.
Deserialize()
bool CPhysicalPort::Deserialize (const tinyxml2::XMLElement * pElement)
References XMLUtils::GetAttribute(), LAYOUT_XML_ATTR_CONTROLLER, LAYOUT_XML_ATTR_PORT_ID, LAYOUT_XML_ELM_ACCEPTS, CLog::Log(), LOGDEBUG, LOGWARNING, m_accepts, m_portId, and Reset().
Referenced by KODI::GAME::CPhysicalTopology::Deserialize().
ID()
const std::string & KODI::GAME::CPhysicalPort::ID () const inline
Get the ID of the port.
Returns
The port's ID, e.g. "1", as a string
References m_portId.
IsCompatible()
bool CPhysicalPort::IsCompatible (const std::string & controllerId) const
Check if the controller is compatible with this port.
Returns
True if the controller is accepted, false otherwise
References m_accepts.
Referenced by KODI::GAME::CGameClientPort::CGameClientPort(), KODI::GAME::CPortNode::IsControllerAccepted(), and KODI::GAME::CPortNode::IsControllerAccepted().
Reset()
void CPhysicalPort::Reset ()
Referenced by Deserialize().
Member Data Documentation
m_accepts
std::vector<std::string> KODI::GAME::CPhysicalPort::m_accepts private
Referenced by Accepts(), Deserialize(), and IsCompatible().
m_portId
std::string KODI::GAME::CPhysicalPort::m_portId private
Referenced by Deserialize(), and ID().
The documentation for this class was generated from the following files:
PhysicalPort.h
PhysicalPort.cpp