Kodi Documentation: KODI::GUILIB::GUIINFO::CPicturesGUIInfo Class Reference
KODI::GUILIB::GUIINFO::CPicturesGUIInfo Class Reference
#include <PicturesGUIInfo.h>
Public Member Functions
CPicturesGUIInfo ()
~CPicturesGUIInfo () override
bool InitCurrentItem (CFileItem *item) override
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) const override
Get a GUIInfoManager label string.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager integer value.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager bool value.
void SetCurrentSlide (CFileItem *item)
const CFileItem * GetCurrentSlide () const
Public Member Functions inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
CGUIInfoProvider ()=default
~CGUIInfoProvider () override=default
bool GetFallbackLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) override
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo) override
Set new audio/video stream info data.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::IGUIInfoProvider
virtual ~IGUIInfoProvider ()=default
Private Attributes
std::unique_ptr< CFileItem > m_currentSlide
Additional Inherited Members
Protected Attributes inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
VideoStreamInfo m_videoInfo
AudioStreamInfo m_audioInfo
SubtitleStreamInfo m_subtitleInfo
Constructor & Destructor Documentation
CPicturesGUIInfo()
CPicturesGUIInfo::CPicturesGUIInfo () default
~CPicturesGUIInfo()
CPicturesGUIInfo::~CPicturesGUIInfo () override default
Member Function Documentation
GetBool()
bool CPicturesGUIInfo::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager bool value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CSlideShowDelegator::GetCurrentSlide(), CServiceBroker::GetSlideShowDelegator(), CSlideShowDelegator::InSlideShow(), CSlideShowDelegator::IsPaused(), CSlideShowDelegator::IsShuffled(), KODI::VIDEO::IsVideo(), SLIDESHOW_ISACTIVE, SLIDESHOW_ISPAUSED, SLIDESHOW_ISRANDOM, SLIDESHOW_ISVIDEO, and value.
GetCurrentSlide()
const CFileItem * CPicturesGUIInfo::GetCurrentSlide () const
References m_currentSlide.
Referenced by CGUIDialogPictureInfo::FrameMove().
GetInt()
bool CPicturesGUIInfo::GetInt (int & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager integer value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
GetLabel()
bool CPicturesGUIInfo::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) const override virtual
Get a GUIInfoManager label string.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References URIUtils::GetDirectory(), URIUtils::GetFileName(), CPictureInfoTag::GetInfo(), CFileItem::GetPath(), CFileItem::GetPictureInfoTag(), CServiceBroker::GetSlideShowDelegator(), CURL::GetWithoutUserDetails(), CFileItem::HasPictureInfoTag(), CFileItem::IsCBR(), CFileItem::IsCBZ(), CFileItem::IsPicture(), CFileItem::IsRAR(), CFileItem::IsZIP(), listitem2slideshow_map, LISTITEM_PICTURE_END, LISTITEM_PICTURE_PATH, LISTITEM_PICTURE_START, CLog::Log(), LOGERROR, m_currentSlide, slideshow, SLIDESHOW_FILE_DATE, SLIDESHOW_FILE_NAME, SLIDESHOW_FILE_PATH, SLIDESHOW_FILE_SIZE, SLIDESHOW_INDEX, SLIDESHOW_LABELS_END, SLIDESHOW_LABELS_START, and value.
InitCurrentItem()
bool CPicturesGUIInfo::InitCurrentItem (CFileItem * item) override virtual
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by the provider, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
SetCurrentSlide()
void CPicturesGUIInfo::SetCurrentSlide (CFileItem * item)
References CFileItem::GetPath(), CFileItem::GetPictureInfoTag(), CFileItem::HasPictureInfoTag(), CPictureInfoTag::Load(), and m_currentSlide.
Referenced by CGUIWindowSlideShow::OnDeinitWindow(), CGUIWindowSlideShow::Process(), and CGUIDialogPictureInfo::SetPicture().
Member Data Documentation
m_currentSlide
std::unique_ptr<CFileItem> KODI::GUILIB::GUIINFO::CPicturesGUIInfo::m_currentSlide private
Referenced by GetCurrentSlide(), GetLabel(), and SetCurrentSlide().
The documentation for this class was generated from the following files:
PicturesGUIInfo.h
PicturesGUIInfo.cpp