Kodi Documentation: CXBTFReader Class Reference
CXBTFReader Class Reference
#include <XBTFReader.h>
Public Member Functions
CXBTFReader ()
~CXBTFReader () override
bool Open (const std::string &path)
bool IsOpen () const
void Close ()
time_t GetLastModificationTimestamp () const
bool Load (const CXBTFFrame &frame, unsigned char *buffer) const
Public Member Functions inherited from CXBTFBase
virtual ~CXBTFBase ()=default
uint64_t GetHeaderSize () const
bool Exists (const std::string &name) const
bool Get (const std::string &name, CXBTFFile &file) const
std::vector< CXBTFFile > GetFiles () const
void AddFile (const CXBTFFile &file)
void UpdateFile (const CXBTFFile &file)
Private Attributes
std::string m_path
FILE * m_file = nullptr
Additional Inherited Members
Protected Member Functions inherited from CXBTFBase
CXBTFBase ()=default
Protected Attributes inherited from CXBTFBase
std::map< std::string, CXBTFFile > m_files
Constructor & Destructor Documentation
CXBTFReader()
CXBTFReader::CXBTFReader ()
~CXBTFReader()
CXBTFReader::~CXBTFReader () override
References Close().
Member Function Documentation
Close()
void CXBTFReader::Close ()
References fclose(), m_file, CXBTFBase::m_files, and m_path.
Referenced by ~CXBTFReader().
GetLastModificationTimestamp()
time_t CXBTFReader::GetLastModificationTimestamp () const
References m_file.
IsOpen()
bool CXBTFReader::IsOpen () const
References m_file.
Load()
bool CXBTFReader::Load (const CXBTFFrame & frame, unsigned char * buffer) const
References fseeko64, CXBTFFrame::GetOffset(), CXBTFFrame::GetPackedSize(), and m_file.
Referenced by CTextureBundleXBT::UnpackFrame().
Open()
bool CXBTFReader::Open (const std::string & path)
References CXBTFBase::AddFile(), g_charsetConverter, CXBTFFile::GetFrames(), CXBTFBase::GetHeaderSize(), m_file, m_path, CXBTFFile::MaximumPathLength, ReadChar(), ReadString(), ReadUInt32(), ReadUInt64(), CXBTFFrame::SetDuration(), CXBTFFrame::SetFormat(), CXBTFFrame::SetHeight(), CXBTFFile::SetLoop(), CXBTFFrame::SetOffset(), CXBTFFrame::SetPackedSize(), CXBTFFile::SetPath(), CXBTFFrame::SetUnpackedSize(), CXBTFFrame::SetWidth(), CSpecialProtocol::TranslatePath(), XBTF_MAGIC, and XBTF_VERSION_MIN.
Member Data Documentation
m_file
FILE* CXBTFReader::m_file = nullptr private
Referenced by Close(), GetLastModificationTimestamp(), IsOpen(), Load(), and Open().
m_path
std::string CXBTFReader::m_path private
Referenced by Close(), and Open().
The documentation for this class was generated from the following files:
XBTFReader.h
XBTFReader.cpp