Kodi Documentation: CMMNotificationClient Class Reference
CMMNotificationClient Class Reference
#include <IMMNotificationClient.h>
Public Member Functions
CMMNotificationClient ()
~CMMNotificationClient ()=default
ULONG STDMETHODCALLTYPE AddRef ()
ULONG STDMETHODCALLTYPE Release ()
HRESULT STDMETHODCALLTYPE QueryInterface (const IID &riid, void **ppvInterface)
HRESULT STDMETHODCALLTYPE OnDefaultDeviceChanged (EDataFlow flow, ERole role, LPCWSTR pwstrDeviceId)
HRESULT STDMETHODCALLTYPE OnDeviceAdded (LPCWSTR pwstrDeviceId)
HRESULT STDMETHODCALLTYPE OnDeviceRemoved (LPCWSTR pwstrDeviceId)
HRESULT STDMETHODCALLTYPE OnDeviceStateChanged (LPCWSTR pwstrDeviceId, DWORD dwNewState)
HRESULT STDMETHODCALLTYPE OnPropertyValueChanged (LPCWSTR pwstrDeviceId, const PROPERTYKEY key)
void STDMETHODCALLTYPE NotifyAE ()
Private Attributes
LONG _cRef
Microsoft::WRL::ComPtr< IMMDeviceEnumerator > _pEnumerator
Constructor & Destructor Documentation
CMMNotificationClient()
CMMNotificationClient::CMMNotificationClient () inline
~CMMNotificationClient()
CMMNotificationClient::~CMMNotificationClient () default
Member Function Documentation
AddRef()
ULONG STDMETHODCALLTYPE CMMNotificationClient::AddRef () inline
References _cRef.
Referenced by QueryInterface().
NotifyAE()
void STDMETHODCALLTYPE CMMNotificationClient::NotifyAE () inline
References IAE::DeviceChange(), CServiceBroker::GetActiveAE(), and CWin32PowerSyscall::IsSuspending().
Referenced by OnDefaultDeviceChanged(), OnDeviceAdded(), OnDeviceRemoved(), and OnDeviceStateChanged().
OnDefaultDeviceChanged()
HRESULT STDMETHODCALLTYPE CMMNotificationClient::OnDefaultDeviceChanged (EDataFlow flow, ERole role, LPCWSTR pwstrDeviceId) inline
References CLog::Log(), LOGDEBUG, and NotifyAE().
OnDeviceAdded()
HRESULT STDMETHODCALLTYPE CMMNotificationClient::OnDeviceAdded (LPCWSTR pwstrDeviceId) inline
References CLog::Log(), LOGDEBUG, and NotifyAE().
OnDeviceRemoved()
HRESULT STDMETHODCALLTYPE CMMNotificationClient::OnDeviceRemoved (LPCWSTR pwstrDeviceId) inline
References CLog::Log(), LOGDEBUG, and NotifyAE().
OnDeviceStateChanged()
HRESULT STDMETHODCALLTYPE CMMNotificationClient::OnDeviceStateChanged (LPCWSTR pwstrDeviceId, DWORD dwNewState) inline
References CLog::Log(), LOGDEBUG, and NotifyAE().
OnPropertyValueChanged()
HRESULT STDMETHODCALLTYPE CMMNotificationClient::OnPropertyValueChanged (LPCWSTR pwstrDeviceId, const PROPERTYKEY key) inline
References CLog::Log(), and LOGDEBUG.
QueryInterface()
HRESULT STDMETHODCALLTYPE CMMNotificationClient::QueryInterface (const IID & riid, void ** ppvInterface) inline
References AddRef().
Release()
ULONG STDMETHODCALLTYPE CMMNotificationClient::Release () inline
References _cRef.
Member Data Documentation
_cRef
LONG CMMNotificationClient::_cRef private
Referenced by AddRef(), and Release().
_pEnumerator
Microsoft::WRL::ComPtr<IMMDeviceEnumerator> CMMNotificationClient::_pEnumerator private
The documentation for this class was generated from the following file:
IMMNotificationClient.h