Kodi Documentation: Shaders::GLES::BaseYUV2RGBGLSLShader Class Reference
Shaders::GLES::BaseYUV2RGBGLSLShader Class Reference
#include <YUV2RGBShaderGLES.h>
Public Member Functions
BaseYUV2RGBGLSLShader (EShaderFormat format, AVColorPrimaries dst, AVColorPrimaries src, bool toneMap, ETONEMAPMETHOD toneMapMethod)
~BaseYUV2RGBGLSLShader () override
void SetField (int field)
void SetWidth (int w)
void SetHeight (int h)
void SetColParams (AVColorSpace colSpace, int bits, bool limited, int textureBits)
void SetBlack (float black)
void SetContrast (float contrast)
void SetConvertFullColorRange (bool convertFullRange)
void SetDisplayMetadata (bool hasDisplayMetadata, const AVMasteringDisplayMetadata &displayMetadata, bool hasLightMetadata, AVContentLightMetadata lightMetadata)
void SetToneMapParam (float param)
GLint GetVertexLoc ()
GLint GetYcoordLoc ()
GLint GetUcoordLoc ()
GLint GetVcoordLoc ()
void SetMatrices (const GLfloat *p, const GLfloat *m)
void SetAlpha (GLfloat alpha)
Public Member Functions inherited from Shaders::CGLSLShaderProgram
CGLSLShaderProgram ()
CGLSLShaderProgram (const std::string &vert, const std::string &frag)
~CGLSLShaderProgram () override
bool Enable () override
void Disable () override
bool CompileAndLink () override
Public Member Functions inherited from Shaders::CShaderProgram
CShaderProgram ()=default
virtual ~CShaderProgram ()
bool OK () const
CVertexShader * VertexShader ()
CPixelShader * PixelShader ()
virtual GLuint ProgramHandle ()
Protected Member Functions
void OnCompiledAndLinked () override
bool OnEnabled () override
void OnDisabled () override
void Free ()
Protected Member Functions inherited from Shaders::CGLSLShaderProgram
void Free ()
Protected Attributes
EShaderFormat m_format
int m_width
int m_height
int m_field
bool m_hasDisplayMetadata {false}
AVMasteringDisplayMetadata m_displayMetadata
bool m_hasLightMetadata {false}
AVContentLightMetadata m_lightMetadata
bool m_toneMapping {false}
ETONEMAPMETHOD m_toneMappingMethod {VS_TONEMAPMETHOD_OFF}
float m_toneMappingParam {1.0}
bool m_colorConversion {false}
float m_black
float m_contrast
std::string m_defines
CConvertMatrix m_convMatrix
GLint m_hYTex {-1}
GLint m_hUTex {-1}
GLint m_hVTex {-1}
GLint m_hYuvMat {-1}
GLint m_hStep {-1}
GLint m_hGammaSrc {-1}
GLint m_hGammaDstInv {-1}
GLint m_hPrimMat {-1}
GLint m_hToneP1 {-1}
GLint m_hCoefsDst {-1}
GLint m_hLuminance = -1
GLint m_hVertex {-1}
GLint m_hYcoord {-1}
GLint m_hUcoord {-1}
GLint m_hVcoord {-1}
GLint m_hProj {-1}
GLint m_hModel {-1}
GLint m_hAlpha {-1}
const GLfloat * m_proj {nullptr}
const GLfloat * m_model {nullptr}
GLfloat m_alpha {1.0f}
bool m_convertFullRange
Protected Attributes inherited from Shaders::CGLSLShaderProgram
GLint m_lastProgram
bool m_validated = false
Protected Attributes inherited from Shaders::CShaderProgram
CVertexShader * m_pVP = nullptr
CPixelShader * m_pFP = nullptr
GLuint m_shaderProgram = 0
bool m_ok = false
Constructor & Destructor Documentation
BaseYUV2RGBGLSLShader()
BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader (EShaderFormat format, AVColorPrimaries dst, AVColorPrimaries src, bool toneMap, ETONEMAPMETHOD toneMapMethod)
References Shaders::CShader::LoadSource(), CLog::Log(), LOGDEBUG, LOGERROR, m_black, m_colorConversion, m_contrast, m_convertFullRange, m_convMatrix, m_defines, m_field, m_format, m_height, m_toneMapping, m_toneMappingMethod, m_width, CConvertMatrix::SetDestinationColorPrimaries(), CConvertMatrix::SetSourceColorPrimaries(), SHADER_NV12, SHADER_NV12_RRG, SHADER_YV12, Shaders::CShaderProgram::VertexShader(), VS_TONEMAPMETHOD_ACES, VS_TONEMAPMETHOD_HABLE, and VS_TONEMAPMETHOD_REINHARD.
~BaseYUV2RGBGLSLShader()
BaseYUV2RGBGLSLShader::~BaseYUV2RGBGLSLShader () override
References Free().
Member Function Documentation
Free()
void BaseYUV2RGBGLSLShader::Free () protected
Referenced by ~BaseYUV2RGBGLSLShader().
GetUcoordLoc()
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::GetUcoordLoc () inline
References m_hUcoord.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
GetVcoordLoc()
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::GetVcoordLoc () inline
References m_hVcoord.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
GetVertexLoc()
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::GetVertexLoc () inline
References m_hVertex.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
GetYcoordLoc()
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::GetYcoordLoc () inline
References m_hYcoord.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
OnCompiledAndLinked()
void BaseYUV2RGBGLSLShader::OnCompiledAndLinked () override protected virtual
Reimplemented from Shaders::CShaderProgram.
Reimplemented in Shaders::GLES::YUV2RGBBobShader, and Shaders::GLES::YUV2RGBFilterShader.
References m_hAlpha, m_hCoefsDst, m_hGammaDstInv, m_hGammaSrc, m_hLuminance, m_hModel, m_hPrimMat, m_hProj, m_hStep, m_hToneP1, m_hUcoord, m_hUTex, m_hVcoord, m_hVertex, m_hVTex, m_hYcoord, m_hYTex, m_hYuvMat, Shaders::CShaderProgram::ProgramHandle(), and VerifyGLState.
Referenced by Shaders::GLES::YUV2RGBBobShader::OnCompiledAndLinked(), and Shaders::GLES::YUV2RGBFilterShader::OnCompiledAndLinked().
OnDisabled()
void BaseYUV2RGBGLSLShader::OnDisabled () override protected virtual
Reimplemented from Shaders::CShaderProgram.
OnEnabled()
bool BaseYUV2RGBGLSLShader::OnEnabled () override protected virtual
Reimplemented from Shaders::CShaderProgram.
Reimplemented in Shaders::GLES::YUV2RGBBobShader, and Shaders::GLES::YUV2RGBFilterShader.
References CConvertMatrix::GetGammaDst(), CConvertMatrix::GetGammaSrc(), CToneMappers::GetLuminanceValue(), CConvertMatrix::GetPrimMat(), CConvertMatrix::GetRGBYuvCoefs(), CConvertMatrix::GetYuvMat(), m_alpha, m_black, m_colorConversion, m_contrast, m_convertFullRange, m_convMatrix, m_displayMetadata, m_hAlpha, m_hasDisplayMetadata, m_hasLightMetadata, m_hCoefsDst, m_height, m_hGammaDstInv, m_hGammaSrc, m_hLuminance, m_hModel, m_hPrimMat, m_hProj, m_hStep, m_hToneP1, m_hUTex, m_hVTex, m_hYTex, m_hYuvMat, m_lightMetadata, m_model, m_proj, m_toneMapping, m_toneMappingMethod, m_toneMappingParam, m_width, CConvertMatrix::SetDestinationBlack(), CConvertMatrix::SetDestinationContrast(), CConvertMatrix::SetDestinationLimitedRange(), CMatrix< Order >::ToRaw(), VerifyGLState, VS_TONEMAPMETHOD_ACES, VS_TONEMAPMETHOD_HABLE, and VS_TONEMAPMETHOD_REINHARD.
Referenced by Shaders::GLES::YUV2RGBBobShader::OnEnabled(), and Shaders::GLES::YUV2RGBFilterShader::OnEnabled().
SetAlpha()
void Shaders::GLES::BaseYUV2RGBGLSLShader::SetAlpha (GLfloat alpha) inline
References m_alpha.
Referenced by CLinuxRendererGLES::RenderUpdate().
SetBlack()
void Shaders::GLES::BaseYUV2RGBGLSLShader::SetBlack (float black) inline
References m_black.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
SetColParams()
void BaseYUV2RGBGLSLShader::SetColParams (AVColorSpace colSpace, int bits, bool limited, int textureBits)
References m_convMatrix, m_height, m_width, CConvertMatrix::SetSourceBitDepth(), CConvertMatrix::SetSourceColorSpace(), CConvertMatrix::SetSourceLimitedRange(), and CConvertMatrix::SetSourceTextureBitDepth().
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
SetContrast()
void Shaders::GLES::BaseYUV2RGBGLSLShader::SetContrast (float contrast) inline
References m_contrast.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
SetConvertFullColorRange()
void Shaders::GLES::BaseYUV2RGBGLSLShader::SetConvertFullColorRange (bool convertFullRange) inline
References m_convertFullRange.
Referenced by CLinuxRendererGLES::LoadShaders().
SetDisplayMetadata()
void BaseYUV2RGBGLSLShader::SetDisplayMetadata (bool hasDisplayMetadata, const AVMasteringDisplayMetadata & displayMetadata, bool hasLightMetadata, AVContentLightMetadata lightMetadata)
References m_displayMetadata, m_hasDisplayMetadata, m_hasLightMetadata, and m_lightMetadata.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
SetField()
void Shaders::GLES::BaseYUV2RGBGLSLShader::SetField (int field) inline
References m_field.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
SetHeight()
void Shaders::GLES::BaseYUV2RGBGLSLShader::SetHeight (int h) inline
References m_height.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
SetMatrices()
void Shaders::GLES::BaseYUV2RGBGLSLShader::SetMatrices (const GLfloat * p, const GLfloat * m) inline
References m_model, and m_proj.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
SetToneMapParam()
void Shaders::GLES::BaseYUV2RGBGLSLShader::SetToneMapParam (float param) inline
References m_toneMappingParam.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
SetWidth()
void Shaders::GLES::BaseYUV2RGBGLSLShader::SetWidth (int w) inline
References m_width.
Referenced by CLinuxRendererGLES::RenderSinglePass(), and CLinuxRendererGLES::RenderToFBO().
Member Data Documentation
m_alpha
GLfloat Shaders::GLES::BaseYUV2RGBGLSLShader::m_alpha {1.0f} protected
Referenced by OnEnabled(), and SetAlpha().
m_black
float Shaders::GLES::BaseYUV2RGBGLSLShader::m_black protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), and SetBlack().
m_colorConversion
bool Shaders::GLES::BaseYUV2RGBGLSLShader::m_colorConversion {false} protected
Referenced by BaseYUV2RGBGLSLShader(), and OnEnabled().
m_contrast
float Shaders::GLES::BaseYUV2RGBGLSLShader::m_contrast protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), and SetContrast().
m_convertFullRange
bool Shaders::GLES::BaseYUV2RGBGLSLShader::m_convertFullRange protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), and SetConvertFullColorRange().
m_convMatrix
CConvertMatrix Shaders::GLES::BaseYUV2RGBGLSLShader::m_convMatrix protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), and SetColParams().
m_defines
std::string Shaders::GLES::BaseYUV2RGBGLSLShader::m_defines protected
Referenced by BaseYUV2RGBGLSLShader(), Shaders::GLES::YUV2RGBBobShader::YUV2RGBBobShader(), Shaders::GLES::YUV2RGBFilterShader::YUV2RGBFilterShader(), and Shaders::GLES::YUV2RGBProgressiveShader::YUV2RGBProgressiveShader().
m_displayMetadata
AVMasteringDisplayMetadata Shaders::GLES::BaseYUV2RGBGLSLShader::m_displayMetadata protected
Referenced by OnEnabled(), and SetDisplayMetadata().
m_field
int Shaders::GLES::BaseYUV2RGBGLSLShader::m_field protected
Referenced by BaseYUV2RGBGLSLShader(), Shaders::GLES::YUV2RGBBobShader::OnEnabled(), and SetField().
m_format
EShaderFormat Shaders::GLES::BaseYUV2RGBGLSLShader::m_format protected
Referenced by BaseYUV2RGBGLSLShader().
m_hAlpha
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hAlpha {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hasDisplayMetadata
bool Shaders::GLES::BaseYUV2RGBGLSLShader::m_hasDisplayMetadata {false} protected
Referenced by OnEnabled(), and SetDisplayMetadata().
m_hasLightMetadata
bool Shaders::GLES::BaseYUV2RGBGLSLShader::m_hasLightMetadata {false} protected
Referenced by OnEnabled(), and SetDisplayMetadata().
m_hCoefsDst
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hCoefsDst {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_height
int Shaders::GLES::BaseYUV2RGBGLSLShader::m_height protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), Shaders::GLES::YUV2RGBBobShader::OnEnabled(), SetColParams(), and SetHeight().
m_hGammaDstInv
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hGammaDstInv {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hGammaSrc
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hGammaSrc {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hLuminance
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hLuminance = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hModel
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hModel {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hPrimMat
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hPrimMat {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hProj
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hProj {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hStep
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hStep {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hToneP1
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hToneP1 {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hUcoord
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hUcoord {-1} protected
Referenced by GetUcoordLoc(), and OnCompiledAndLinked().
m_hUTex
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hUTex {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hVcoord
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hVcoord {-1} protected
Referenced by GetVcoordLoc(), and OnCompiledAndLinked().
m_hVertex
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hVertex {-1} protected
Referenced by GetVertexLoc(), and OnCompiledAndLinked().
m_hVTex
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hVTex {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hYcoord
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hYcoord {-1} protected
Referenced by GetYcoordLoc(), and OnCompiledAndLinked().
m_hYTex
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hYTex {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hYuvMat
GLint Shaders::GLES::BaseYUV2RGBGLSLShader::m_hYuvMat {-1} protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_lightMetadata
AVContentLightMetadata Shaders::GLES::BaseYUV2RGBGLSLShader::m_lightMetadata protected
Referenced by OnEnabled(), and SetDisplayMetadata().
m_model
const GLfloat* Shaders::GLES::BaseYUV2RGBGLSLShader::m_model {nullptr} protected
Referenced by OnEnabled(), and SetMatrices().
m_proj
const GLfloat* Shaders::GLES::BaseYUV2RGBGLSLShader::m_proj {nullptr} protected
Referenced by OnEnabled(), and SetMatrices().
m_toneMapping
bool Shaders::GLES::BaseYUV2RGBGLSLShader::m_toneMapping {false} protected
Referenced by BaseYUV2RGBGLSLShader(), and OnEnabled().
m_toneMappingMethod
ETONEMAPMETHOD Shaders::GLES::BaseYUV2RGBGLSLShader::m_toneMappingMethod {VS_TONEMAPMETHOD_OFF} protected
Referenced by BaseYUV2RGBGLSLShader(), and OnEnabled().
m_toneMappingParam
float Shaders::GLES::BaseYUV2RGBGLSLShader::m_toneMappingParam {1.0} protected
Referenced by OnEnabled(), and SetToneMapParam().
m_width
int Shaders::GLES::BaseYUV2RGBGLSLShader::m_width protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), Shaders::GLES::YUV2RGBBobShader::OnEnabled(), SetColParams(), and SetWidth().
The documentation for this class was generated from the following files:
YUV2RGBShaderGLES.h
YUV2RGBShaderGLES.cpp