Kodi Documentation: DVDInputStreamNavigator.cpp File Reference
DVDInputStreamNavigator.cpp File Reference
#include "DVDInputStreamNavigator.h"
#include "../DVDDemuxSPU.h"
#include "LangInfo.h"
#include "ServiceBroker.h"
#include "filesystem/IFileTypes.h"
#include "guilib/LocalizeStrings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/Geometry.h"
#include "utils/LangCodeExpander.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/log.h"
#include <memory>
Namespaces
namespace anonymous_namespace{DVDInputStreamNavigator.cpp}
Functions
static int dvd_inputstreamnavigator_cb_seek (void *p_stream, uint64_t i_pos)
static int dvd_inputstreamnavigator_cb_read (void *p_stream, void *buffer, int i_read)
static int dvd_inputstreamnavigator_cb_readv (void *p_stream, void *p_iovec, int i_blocks)
static void dvd_logger (void *priv, dvdnav_logger_level_t level, const char *fmt, va_list va)
Variables
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::HOLDMODE_NONE = 0
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::HOLDMODE_HELD = 1
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::HOLDMODE_SKIP = 2
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::HOLDMODE_DATA = 3
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_TYPE_NOTSPECIFIED = 0
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_TYPE_LANGUAGE = 1
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_NOTSPECIFIED = 0
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_NORMALCAPTIONS = 1
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_BIGCAPTIONS = 2
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_CHILDRENSCAPTIONS = 3
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_NORMALCC = 5
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_BIGCC = 6
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_CHILDRENSCC = 7
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_FORCED = 9
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_NORMALDIRECTORSCOMMENTS = 13
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_BIGDIRECTORSCOMMENTS = 14
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_SUBPICTURE_LANG_EXT_CHILDRENDIRECTORSCOMMENTS = 15
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_AUDIO_LANG_EXT_NOTSPECIFIED = 0
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_AUDIO_LANG_EXT_NORMALCAPTIONS = 1
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_AUDIO_LANG_EXT_VISUALLYIMPAIRED = 2
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_AUDIO_LANG_EXT_DIRECTORSCOMMENTS1 = 3
constexpr int anonymous_namespace{DVDInputStreamNavigator.cpp}::DVD_AUDIO_LANG_EXT_DIRECTORSCOMMENTS2 = 4
Function Documentation
dvd_inputstreamnavigator_cb_read()
int dvd_inputstreamnavigator_cb_read (void * p_stream, void * buffer, int i_read) static
References CLog::Log(), LOGERROR, and CDVDInputStreamFile::Read().
Referenced by CDVDInputStreamNavigator::CDVDInputStreamNavigator().
dvd_inputstreamnavigator_cb_readv()
int dvd_inputstreamnavigator_cb_readv (void * p_stream, void * p_iovec, int i_blocks) static
References CDVDInputStreamFile::Read(), and CDVDInputStreamFile::Seek().
Referenced by CDVDInputStreamNavigator::CDVDInputStreamNavigator().
dvd_inputstreamnavigator_cb_seek()
int dvd_inputstreamnavigator_cb_seek (void * p_stream, uint64_t i_pos) static
References CDVDInputStreamFile::Seek().
Referenced by CDVDInputStreamNavigator::CDVDInputStreamNavigator().
dvd_logger()
void dvd_logger (void * priv, dvdnav_logger_level_t level, const char * fmt, va_list va) static
References DVDNAV_LOGGER_LEVEL_DEBUG, DVDNAV_LOGGER_LEVEL_ERROR, DVDNAV_LOGGER_LEVEL_INFO, DVDNAV_LOGGER_LEVEL_WARN, KODI::UTILS::StringUtils::FormatV(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, and LOGWARNING.
Referenced by CDVDInputStreamNavigator::Open().