Kodi Documentation: KODI::GAME::CGameUtils Class Reference
KODI::GAME::CGameUtils Class Reference
Games
Game related utilities.
#include <GameUtils.h>
Static Public Member Functions
static bool FillInGameClient (CFileItem &item, std::string &savestatePath)
Set the game client property, prompt the user for a savestate if there are any (savestates store the information of which game client created it). If there are no savestates or the user wants a new savestate, prompt the user for a game client.
static bool HasGameExtension (const std::string &path)
Check if the file extension is supported by an add-on in a local or remote repository.
static std::set< std::string > GetGameExtensions ()
Get all game extensions.
static bool IsStandaloneGame (const ADDON::AddonPtr &addon)
Check if game script or game add-on can be launched directly.
Static Private Member Functions
static void GetGameClients (const CFileItem &file, GameClientVector &candidates, GameClientVector &installable, bool &bHasVfsGameClient)
static void GetGameClients (const ADDON::VECADDONS &addons, const CURL &translatedUrl, GameClientVector &candidates, bool &bHasVfsGameClient)
static bool Install (const std::string &gameClient)
Install the specified game client.
static bool Enable (const std::string &gameClient)
Enable the specified game client.
Detailed Description
Game related utilities.
Member Function Documentation
Enable()
bool CGameUtils::Enable (const std::string & gameClient) static private
Enable the specified game client.
Parameters
gameClient the game client to enable
Returns
True if the game client is enabled, false otherwise
References ADDON::CAddonMgr::EnableAddon(), and CServiceBroker::GetAddonMgr().
FillInGameClient()
bool CGameUtils::FillInGameClient (CFileItem & item, std::string & savestatePath) static
Set the game client property, prompt the user for a savestate if there are any (savestates store the information of which game client created it). If there are no savestates or the user wants a new savestate, prompt the user for a game client.
Parameters
item The item with or without a game client in its info tag
savestatePath Output. The path to the savestate selected. Empty if new savestate was selected
Returns
True if the item has a valid game client ID in its info tag
References KODI::RETRO::CSavestateDatabase::AllocateSavestate(), Enable, CFileItem::GetAddonInfo(), KODI::GAME::CGameInfoTag::GetGameClient(), GetGameClients(), CFileItem::GetGameInfoTag(), CFileItem::GetPath(), KODI::RETRO::CSavestateDatabase::GetSavestate(), CFileItem::HasAddonInfo(), ID, Install(), CLog::Log(), LOGDEBUG, KODI::GAME::CGameInfoTag::SetGameClient(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), KODI::GAME::CGUIDialogSelectSavestate::ShowAndGetSavestate(), and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by KODI::RETRO::CRetroPlayer::OpenFile().
GetGameClients() [1/2]
void CGameUtils::GetGameClients (const ADDON::VECADDONS & addons, const CURL & translatedUrl, GameClientVector & candidates, bool & bHasVfsGameClient) static private
References addons, CURL::Get(), URIUtils::GetExtension(), and CURL::GetProtocol().
GetGameClients() [2/2]
void CGameUtils::GetGameClients (const CFileItem & file, GameClientVector & candidates, GameClientVector & installable, bool & bHasVfsGameClient) static private
Todo:
Move to presentation code
References CServiceBroker::GetAddonMgr(), ADDON::CBinaryAddonCache::GetAddons(), CServiceBroker::GetBinaryAddonCache(), GetGameClients(), and CSpecialProtocol::TranslatePath().
Referenced by FillInGameClient(), and GetGameClients().
GetGameExtensions()
std::set< std::string > CGameUtils::GetGameExtensions () static
Get all game extensions.
References CServiceBroker::GetAddonMgr(), ADDON::CBinaryAddonCache::GetAddons(), and CServiceBroker::GetBinaryAddonCache().
Referenced by KODI::GAME::CGUIViewStateWindowGames::GetExtensions().
HasGameExtension()
bool CGameUtils::HasGameExtension (const std::string & path) static
Check if the file extension is supported by an add-on in a local or remote repository.
Parameters
path The path of the game file
Returns
true if the path's extension is supported by a known game client
References CServiceBroker::GetAddonMgr(), CServiceBroker::GetBinaryAddonCache(), URIUtils::GetExtension(), CURL::GetFileNameWithoutPath(), and ADDON::CBinaryAddonCache::GetInstalledAddons().
Referenced by CFileItem::IsGame().
Install()
bool CGameUtils::Install (const std::string & gameClient) static private
Install the specified game client.
If the game client is not installed, a model dialog is shown installing the game client. If the installation fails, an error dialog is shown.
Parameters
gameClient The game client to install
Returns
True if the game client is installed, false otherwise
References ADDON::CHOICE_NO, CServiceBroker::GetAddonMgr(), ADDON::CAddonInstaller::GetInstance(), ADDON::CAddonInstaller::InstallModal(), ADDON::CAddonMgr::IsAddonInstalled(), CLog::Log(), LOGERROR, and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by FillInGameClient().
IsStandaloneGame()
bool CGameUtils::IsStandaloneGame (const ADDON::AddonPtr & addon) static
Check if game script or game add-on can be launched directly.
Returns
true if the add-on can be launched, false otherwise
Referenced by CGUIDialogAddonInfo::CanRun(), CFileItem::IsGame(), and XFILE::IsStandaloneGame().
The documentation for this class was generated from the following files:
GameUtils.h
GameUtils.cpp