Kodi Documentation: CLibInputHandler Class Reference
CLibInputHandler Class Reference
#include <LibInputHandler.h>
Public Member Functions
CLibInputHandler ()
~CLibInputHandler () override
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
void Start ()
bool SetKeymap (const std::string &layout)
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Private Member Functions
void Process () override
void ProcessEvent (libinput_event *ev)
void DeviceAdded (libinput_device *dev)
void DeviceRemoved (libinput_device *dev)
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Attributes
udev * m_udev
libinput * m_li
int m_liFd
std::unique_ptr< CLibInputKeyboard > m_keyboard
std::unique_ptr< CLibInputPointer > m_pointer
std::unique_ptr< CLibInputSettings > m_settings
std::unique_ptr< CLibInputTouch > m_touch
std::vector< libinput_device * > m_devices
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Constructor & Destructor Documentation
CLibInputHandler()
CLibInputHandler::CLibInputHandler ()
References CServiceBroker::GetAnnouncementManager(), CLog::Log(), LOGERROR, LogHandler(), m_interface, m_keyboard, m_li, m_liFd, m_pointer, m_settings, m_touch, m_udev, and ANNOUNCEMENT::System.
~CLibInputHandler()
CLibInputHandler::~CLibInputHandler () override
References CServiceBroker::GetAnnouncementManager(), m_li, m_udev, and CThread::StopThread().
Member Function Documentation
Announce()
void CLibInputHandler::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References CLog::Log(), LOGERROR, m_li, and ANNOUNCEMENT::System.
DeviceAdded()
void CLibInputHandler::DeviceAdded (libinput_device * dev) private
References CLog::Log(), LOGDEBUG, m_devices, m_keyboard, and name.
Referenced by ProcessEvent().
DeviceRemoved()
void CLibInputHandler::DeviceRemoved (libinput_device * dev) private
References CLog::Log(), LOGDEBUG, m_devices, and name.
Referenced by ProcessEvent().
Process()
void CLibInputHandler::Process (void) override private virtual
Reimplemented from CThread.
References CLog::Log(), LOGERROR, CThread::m_bStop, m_li, m_liFd, and ProcessEvent().
ProcessEvent()
void CLibInputHandler::ProcessEvent (libinput_event * ev) private
References DeviceAdded(), DeviceRemoved(), m_keyboard, m_pointer, and m_touch.
Referenced by Process().
SetKeymap()
bool CLibInputHandler::SetKeymap (const std::string & layout)
References m_keyboard.
Referenced by CLibInputSettings::OnSettingChanged().
Start()
void CLibInputHandler::Start ()
References CThread::Create(), LOWEST, and CThread::SetPriority().
Member Data Documentation
m_devices
std::vector<libinput_device*> CLibInputHandler::m_devices private
Referenced by DeviceAdded(), and DeviceRemoved().
m_keyboard
std::unique_ptr<CLibInputKeyboard> CLibInputHandler::m_keyboard private
Referenced by CLibInputHandler(), DeviceAdded(), ProcessEvent(), and SetKeymap().
m_li
libinput* CLibInputHandler::m_li private
Referenced by Announce(), CLibInputHandler(), Process(), and ~CLibInputHandler().
m_liFd
int CLibInputHandler::m_liFd private
Referenced by CLibInputHandler(), and Process().
m_pointer
std::unique_ptr<CLibInputPointer> CLibInputHandler::m_pointer private
Referenced by CLibInputHandler(), and ProcessEvent().
m_settings
std::unique_ptr<CLibInputSettings> CLibInputHandler::m_settings private
Referenced by CLibInputHandler().
m_touch
std::unique_ptr<CLibInputTouch> CLibInputHandler::m_touch private
Referenced by CLibInputHandler(), and ProcessEvent().
m_udev
udev* CLibInputHandler::m_udev private
Referenced by CLibInputHandler(), and ~CLibInputHandler().
The documentation for this class was generated from the following files:
linux/input/LibInputHandler.h
LibInputHandler.cpp