Kodi Documentation: CDVDOverlayCodecTX3G Class Reference
CDVDOverlayCodecTX3G Class Reference
#include <DVDOverlayCodecTX3G.h>
Public Member Functions
CDVDOverlayCodecTX3G ()
~CDVDOverlayCodecTX3G () override=default
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
OverlayMessage Decode (DemuxPacket *pPacket) override
void Reset () override
void Flush () override
std::shared_ptr< CDVDOverlay > GetOverlay () override
void PostProcess (std::string &text) override
Post processing of subtitle, will be called before processing AddSubtitle method.
Public Member Functions inherited from CDVDOverlayCodec
CDVDOverlayCodec (const char *name)
virtual ~CDVDOverlayCodec ()=default
const std::string & GetName () const
Private Attributes
std::shared_ptr< CDVDOverlay > m_pOverlay
Additional Inherited Members
Static Protected Member Functions inherited from CDVDOverlayCodec
static void GetAbsoluteTimes (double &starttime, double &stoptime, DemuxPacket *pkt)
Private Member Functions inherited from CSubtitlesAdapter
CSubtitlesAdapter ()
virtual ~CSubtitlesAdapter ()
bool Initialize ()
Initialize the subtitles adapter.
int AddSubtitle (std::string &text, double startTime, double stopTime)
Add a subtitle.
int AddSubtitle (std::string &text, double startTime, double stopTime, KODI::SUBTITLES::STYLE::subtitleOpts *opts)
Add a subtitle with supplementary options.
void AppendToSubtitle (int subtitleId, const char *text)
Append text to the specified subtitle ID.
int DeleteSubtitles (int nSubtitles, int threshold)
Delete old subtitles only if the total number of subtitles added reaches the threshold.
void ChangeSubtitleStopTime (int subtitleId, double stopTime)
Change the stop time of a subtitle ID with the specified time.
void FlushSubtitles ()
std::shared_ptr< CDVDOverlay > CreateOverlay ()
Constructor & Destructor Documentation
CDVDOverlayCodecTX3G()
CDVDOverlayCodecTX3G::CDVDOverlayCodecTX3G ()
~CDVDOverlayCodecTX3G()
CDVDOverlayCodecTX3G::~CDVDOverlayCodecTX3G () override default
Member Function Documentation
Decode()
OverlayMessage CDVDOverlayCodecTX3G::Decode (DemuxPacket * pPacket) override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::AddSubtitle(), CCharArrayParser::CharsLeft(), KODI::UTILS::COLOR::ConvertToARGB(), data(), CDVDOverlayCodec::GetAbsoluteTimes(), CCharArrayParser::GetPosition(), DEMUX_PACKET::iSize, CLog::Log(), LOGDEBUG, LOGWARNING, m_pOverlay, MP4_BOX_HEADER_SIZE, OC_BUFFER, OC_DONE, OC_ERROR, OC_OVERLAY, DEMUX_PACKET::pData, CCharArrayParser::ReadNextUnsignedChar(), CCharArrayParser::ReadNextUnsignedInt(), CCharArrayParser::ReadNextUnsignedShort(), CCharArrayParser::Reset(), CCharArrayParser::SkipChars(), and text.
Flush()
void CDVDOverlayCodecTX3G::Flush () override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::FlushSubtitles(), and m_pOverlay.
Referenced by Reset().
GetOverlay()
std::shared_ptr< CDVDOverlay > CDVDOverlayCodecTX3G::GetOverlay () override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::CreateOverlay(), and m_pOverlay.
Open()
bool CDVDOverlayCodecTX3G::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Implements CDVDOverlayCodec.
References CDVDStreamInfo::codec, CSubtitlesAdapter::Initialize(), and m_pOverlay.
PostProcess()
void CDVDOverlayCodecTX3G::PostProcess (std::string & text) override virtual
Post processing of subtitle, will be called before processing AddSubtitle method.
Parameters
text The subtitle text
Reimplemented from CSubtitlesAdapter.
References CSubtitlesAdapter::PostProcess(), and text.
Reset()
void CDVDOverlayCodecTX3G::Reset () override virtual
Implements CDVDOverlayCodec.
References Flush().
Member Data Documentation
m_pOverlay
std::shared_ptr<CDVDOverlay> CDVDOverlayCodecTX3G::m_pOverlay private
Referenced by Decode(), Flush(), GetOverlay(), and Open().
The documentation for this class was generated from the following files:
DVDOverlayCodecTX3G.h
DVDOverlayCodecTX3G.cpp