Kodi Documentation: PERIPHERALS::CPeripheralBusGCController Class Reference
PERIPHERALS::CPeripheralBusGCController Class Reference
#include <PeripheralBusGCController.h>
Public Member Functions
CPeripheralBusGCController (CPeripherals &manager)
~CPeripheralBusGCController () override
bool InitializeProperties (CPeripheral &peripheral) override
Initialize the properties of a peripheral with a known location.
void Initialise (void) override
Initialise this bus and start a polling thread if this bus needs polling.
void ProcessEvents () override
Poll for events.
bool PerformDeviceScan (PeripheralScanResults &results) override
Scan for devices on this bus and add them to the results list. This will have to be implemented for each bus.
PeripheralScanResults GetInputDevices ()
void callOnDeviceAdded (const std::string &strLocation)
void callOnDeviceRemoved (const std::string &strLocation)
void SetScanResults (const PeripheralScanResults &resScanResults)
const std::string & getDeviceLocationPrefix ()
Public Member Functions inherited from PERIPHERALS::CPeripheralBus
CPeripheralBus (const std::string &threadname, CPeripherals &manager, PeripheralBusType type)
~CPeripheralBus (void) override
PeripheralBusType Type (void) const
bool NeedsPolling (void) const
virtual bool InitializeButtonMap (const CPeripheral &peripheral, KODI::JOYSTICK::IButtonMap &buttonMap) const
Initialize a joystick buttonmap, if possible.
virtual PeripheralPtr GetPeripheral (const std::string &strLocation) const
Get the instance of the peripheral at the given location.
virtual bool HasPeripheral (const std::string &strLocation) const
Check whether a peripheral is present at the given location.
virtual bool SupportsFeature (PeripheralFeature feature) const
Check if the bus supports the given feature.
virtual unsigned int GetPeripheralsWithFeature (PeripheralVector &results, const PeripheralFeature feature) const
Get all peripheral instances that have the given feature.
virtual unsigned int GetNumberOfPeripherals () const
virtual unsigned int GetNumberOfPeripheralsWithId (const int iVendorId, const int iProductId) const
virtual void GetFeatures (std::vector< PeripheralFeature > &features) const
Get all features that are supported by devices on this bus.
virtual bool HasFeature (const PeripheralFeature feature) const
Check whether there is at least one device present with the given feature.
virtual void OnDeviceAdded (const std::string &strLocation)
Callback method for when a device has been added. Will perform a device scan.
virtual void OnDeviceChanged (const std::string &strLocation)
Callback method for when a device has been changed. Will perform a device scan.
virtual void OnDeviceRemoved (const std::string &strLocation)
Callback method for when a device has been removed. Will perform a device scan.
virtual void Clear (void)
Stop the polling thread and clear all known devices on this bus.
virtual void TriggerDeviceScan (void)
Scan for devices.
virtual void GetDirectory (const std::string &strPath, CFileItemList &items) const
Get all fileitems for a path.
virtual PeripheralPtr GetByPath (const std::string &strPath) const
Get the instance of a peripheral given it's path.
virtual void Register (const PeripheralPtr &peripheral)
Register a new peripheral on this bus.
virtual bool FindComPort (std::string &strLocation)
virtual void EnableButtonMapping ()
Initialize button mapping.
virtual void PowerOff (const std::string &strLocation)
Power off the specified device.
Private Member Functions
void GetEvents (std::vector< kodi::addon::PeripheralEvent > &events)
std::string GetDeviceLocation (int deviceId)
bool GetDeviceId (const std::string &deviceLocation, int &deviceId)
Private Attributes
std::unique_ptr< PeripheralBusGCControllerWrapper > m_peripheralGCController
PeripheralScanResults m_scanResults
CCriticalSection m_critSectionStates
CCriticalSection m_critSectionResults
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from PERIPHERALS::CPeripheralBus
void Process (void) override
virtual bool ScanForDevices (void)
virtual void UnregisterRemovedDevices (const PeripheralScanResults &results)
virtual void RegisterNewDevices (const PeripheralScanResults &results)
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Attributes inherited from PERIPHERALS::CPeripheralBus
PeripheralVector m_peripherals
std::chrono::milliseconds m_iRescanTime
bool m_bNeedsPolling
CPeripherals & m_manager
const PeripheralBusType m_type
CCriticalSection m_critSection
CEvent m_triggerEvent
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CPeripheralBusGCController()
PERIPHERALS::CPeripheralBusGCController::CPeripheralBusGCController (CPeripherals & manager) explicit
References GetInputDevices(), PERIPHERALS::CPeripheralBus::m_bNeedsPolling, m_peripheralGCController, and m_scanResults.
~CPeripheralBusGCController()
PERIPHERALS::CPeripheralBusGCController::~CPeripheralBusGCController () override
Member Function Documentation
callOnDeviceAdded()
void PERIPHERALS::CPeripheralBusGCController::callOnDeviceAdded (const std::string & strLocation)
callOnDeviceRemoved()
void PERIPHERALS::CPeripheralBusGCController::callOnDeviceRemoved (const std::string & strLocation)
GetDeviceId()
bool PERIPHERALS::CPeripheralBusGCController::GetDeviceId (const std::string & deviceLocation, int & deviceId) private
GetDeviceLocation()
std::string PERIPHERALS::CPeripheralBusGCController::GetDeviceLocation (int deviceId) private
getDeviceLocationPrefix()
const std::string & PERIPHERALS::CPeripheralBusGCController::getDeviceLocationPrefix () inline
References DeviceLocationPrefix.
GetEvents()
void PERIPHERALS::CPeripheralBusGCController::GetEvents (std::vector< kodi::addon::PeripheralEvent > & events) private
References events.
GetInputDevices()
PERIPHERALS::PeripheralScanResults PERIPHERALS::CPeripheralBusGCController::GetInputDevices ()
References CLog::Log(), and LOGINFO.
Referenced by CPeripheralBusGCController().
Initialise()
void PERIPHERALS::CPeripheralBusGCController::Initialise (void) override virtual
Initialise this bus and start a polling thread if this bus needs polling.
Reimplemented from PERIPHERALS::CPeripheralBus.
References PERIPHERALS::CPeripheralBus::Initialise().
InitializeProperties()
bool PERIPHERALS::CPeripheralBusGCController::InitializeProperties (CPeripheral & peripheral) override virtual
Initialize the properties of a peripheral with a known location.
Reimplemented from PERIPHERALS::CPeripheralBus.
References PERIPHERALS::CPeripheral::DeviceName(), EXTENDED, PERIPHERALS::CPeripheralBus::InitializeProperties(), JOYSTICK_PROVIDER_DARWIN_GCController, PERIPHERALS::CPeripheral::Location(), CLog::Log(), LOGDEBUG, LOGWARNING, MICRO, PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERALS::CPeripheralJoystick::SetRequestedPort(), PERIPHERALS::CPeripheral::Type(), and PERIPHERALS::PeripheralTypeTranslator::TypeToString().
PerformDeviceScan()
bool PERIPHERALS::CPeripheralBusGCController::PerformDeviceScan (PeripheralScanResults & results) override virtual
Scan for devices on this bus and add them to the results list. This will have to be implemented for each bus.
Parameters
results The result list.
Returns
True when the scan was successful, false otherwise.
Implements PERIPHERALS::CPeripheralBus.
ProcessEvents()
void PERIPHERALS::CPeripheralBusGCController::ProcessEvents (void) override virtual
Poll for events.
Todo:
Multiple controller event processing
Todo:
Multiple controller handling
Reimplemented from PERIPHERALS::CPeripheralBus.
References events, JOYSTICK_STATE_BUTTON_PRESSED, PERIPHERALS::CPeripheralJoystick::OnButtonMotion(), PERIPHERAL_EVENT_TYPE_DRIVER_AXIS, PERIPHERAL_EVENT_TYPE_DRIVER_BUTTON, and PERIPHERALS::PERIPHERAL_JOYSTICK.
SetScanResults()
void PERIPHERALS::CPeripheralBusGCController::SetScanResults (const PeripheralScanResults & resScanResults)
Member Data Documentation
m_critSectionResults
CCriticalSection PERIPHERALS::CPeripheralBusGCController::m_critSectionResults private
m_critSectionStates
CCriticalSection PERIPHERALS::CPeripheralBusGCController::m_critSectionStates private
m_peripheralGCController
std::unique_ptr<PeripheralBusGCControllerWrapper> PERIPHERALS::CPeripheralBusGCController::m_peripheralGCController private
Referenced by CPeripheralBusGCController().
m_scanResults
PeripheralScanResults PERIPHERALS::CPeripheralBusGCController::m_scanResults private
Referenced by CPeripheralBusGCController().
The documentation for this class was generated from the following files:
PeripheralBusGCController.h
PeripheralBusGCController.mm