Kodi Documentation: BitstreamStats Class Reference
BitstreamStats Class Reference final
#include <BitstreamStats.h>
Public Member Functions
BitstreamStats (unsigned int nEstimatedBitrate=(10240 *8))
void AddSampleBytes (unsigned int nBytes)
void AddSampleBits (unsigned int nBits)
double GetBitrate () const
double GetMaxBitrate () const
double GetMinBitrate () const
void Start ()
void CalculateBitrate ()
Private Attributes
double m_dBitrate
double m_dMaxBitrate
double m_dMinBitrate
unsigned int m_nBitCount
unsigned int m_nEstimatedBitrate
int64_t m_tmStart
Static Private Attributes
static int64_t m_tmFreq
Constructor & Destructor Documentation
BitstreamStats()
BitstreamStats::BitstreamStats (unsigned int nEstimatedBitrate = (10240*8)) explicit
References CurrentHostFrequency(), m_dBitrate, m_dMaxBitrate, m_dMinBitrate, m_nBitCount, m_nEstimatedBitrate, m_tmFreq, and m_tmStart.
Member Function Documentation
AddSampleBits()
void BitstreamStats::AddSampleBits (unsigned int nBits)
References CalculateBitrate(), m_nBitCount, and m_nEstimatedBitrate.
Referenced by AddSampleBytes(), and TEST().
AddSampleBytes()
void BitstreamStats::AddSampleBytes (unsigned int nBytes)
References AddSampleBits().
Referenced by CVideoPlayerAudio::Process(), CVideoPlayerVideo::Process(), and TEST().
CalculateBitrate()
void BitstreamStats::CalculateBitrate ()
References CurrentHostCounter(), int64_t(), m_dBitrate, m_dMaxBitrate, m_dMinBitrate, m_nBitCount, m_tmFreq, m_tmStart, and Start().
Referenced by AddSampleBits(), and TEST().
GetBitrate()
double BitstreamStats::GetBitrate () const inline
References m_dBitrate.
Referenced by CVideoPlayerVideo::GetVideoBitrate(), TEST(), and CVideoPlayerAudio::UpdatePlayerInfo().
GetMaxBitrate()
double BitstreamStats::GetMaxBitrate () const inline
References m_dMaxBitrate.
Referenced by TEST().
GetMinBitrate()
double BitstreamStats::GetMinBitrate () const inline
References m_dMinBitrate.
Referenced by TEST().
Start()
void BitstreamStats::Start ()
References CurrentHostCounter(), m_nBitCount, and m_tmStart.
Referenced by CalculateBitrate(), CVideoPlayerAudio::Process(), CVideoPlayerVideo::Process(), and TEST().
Member Data Documentation
m_dBitrate
double BitstreamStats::m_dBitrate private
Referenced by BitstreamStats(), CalculateBitrate(), and GetBitrate().
m_dMaxBitrate
double BitstreamStats::m_dMaxBitrate private
Referenced by BitstreamStats(), CalculateBitrate(), and GetMaxBitrate().
m_dMinBitrate
double BitstreamStats::m_dMinBitrate private
Referenced by BitstreamStats(), CalculateBitrate(), and GetMinBitrate().
m_nBitCount
unsigned int BitstreamStats::m_nBitCount private
Referenced by AddSampleBits(), BitstreamStats(), CalculateBitrate(), and Start().
m_nEstimatedBitrate
unsigned int BitstreamStats::m_nEstimatedBitrate private
Referenced by AddSampleBits(), and BitstreamStats().
m_tmFreq
int64_t BitstreamStats::m_tmFreq static private
Referenced by BitstreamStats(), and CalculateBitrate().
m_tmStart
int64_t BitstreamStats::m_tmStart private
Referenced by BitstreamStats(), CalculateBitrate(), and Start().
The documentation for this class was generated from the following files:
BitstreamStats.h
BitstreamStats.cpp