Kodi Documentation: CRingBuffer Class Reference
CRingBuffer Class Reference
#include <RingBuffer.h>
Public Member Functions
CRingBuffer ()
~CRingBuffer ()
bool Create (unsigned int size)
void Destroy ()
void Clear ()
bool ReadData (char *buf, unsigned int size)
bool ReadData (CRingBuffer &rBuf, unsigned int size)
bool WriteData (const char *buf, unsigned int size)
bool WriteData (CRingBuffer &rBuf, unsigned int size)
bool SkipBytes (int skipSize)
bool Append (CRingBuffer &rBuf)
bool Copy (CRingBuffer &rBuf)
char * getBuffer ()
unsigned int getSize ()
unsigned int getReadPtr () const
unsigned int getWritePtr ()
unsigned int getMaxReadSize ()
unsigned int getMaxWriteSize ()
Private Attributes
CCriticalSection m_critSection
char * m_buffer
unsigned int m_size
unsigned int m_readPtr
unsigned int m_writePtr
unsigned int m_fillCount
Constructor & Destructor Documentation
CRingBuffer()
CRingBuffer::CRingBuffer ()
References m_buffer, m_fillCount, m_readPtr, m_size, and m_writePtr.
~CRingBuffer()
CRingBuffer::~CRingBuffer ()
References Destroy().
Member Function Documentation
Append()
bool CRingBuffer::Append (CRingBuffer & rBuf)
References getMaxReadSize(), and WriteData().
Referenced by Copy().
Clear()
void CRingBuffer::Clear ()
References m_critSection, m_fillCount, m_readPtr, and m_writePtr.
Referenced by Copy(), XFILE::CCurlFile::CReadState::Disconnect(), XFILE::CCurlFile::CReadState::FillBuffer(), XFILE::Pipe::Flush(), CAudioDecoder::Seek(), and TEST().
Copy()
bool CRingBuffer::Copy (CRingBuffer & rBuf)
References Append(), and Clear().
Create()
bool CRingBuffer::Create (unsigned int size)
References m_buffer, m_critSection, and m_size.
Referenced by XFILE::CCurlFile::CReadState::Connect(), CAudioDecoder::Create(), XFILE::Pipe::Pipe(), ReadData(), TEST(), and WriteData().
Destroy()
void CRingBuffer::Destroy ()
References m_buffer, m_critSection, m_fillCount, m_readPtr, m_size, and m_writePtr.
Referenced by XFILE::CCurlFile::CReadState::Connect(), CAudioDecoder::Destroy(), and ~CRingBuffer().
getBuffer()
char * CRingBuffer::getBuffer ()
References m_buffer.
Referenced by ReadData(), TEST(), and WriteData().
getMaxReadSize()
unsigned int CRingBuffer::getMaxReadSize ()
References m_critSection, and m_fillCount.
Referenced by Append(), XFILE::Pipe::CheckStatus(), XFILE::CCurlFile::CReadState::FillBuffer(), XFILE::Pipe::GetAvailableRead(), CAudioDecoder::GetData(), CAudioDecoder::GetDataSize(), XFILE::Pipe::IsEmpty(), XFILE::Pipe::Read(), XFILE::CCurlFile::CReadState::Read(), ReadData(), CAudioDecoder::ReadSamples(), XFILE::CCurlFile::CReadState::ReadString(), XFILE::CCurlFile::CReadState::Seek(), and WriteData().
getMaxWriteSize()
unsigned int CRingBuffer::getMaxWriteSize ()
References m_critSection, m_fillCount, and m_size.
Referenced by XFILE::Pipe::CheckStatus(), XFILE::CCurlFile::CReadState::FillBuffer(), ReadData(), CAudioDecoder::ReadSamples(), XFILE::Pipe::Write(), XFILE::CCurlFile::CReadState::WriteCallback(), and WriteData().
getReadPtr()
unsigned int CRingBuffer::getReadPtr () const
References m_readPtr.
Referenced by WriteData().
getSize()
unsigned int CRingBuffer::getSize ()
References m_critSection, and m_size.
Referenced by CAudioDecoder::ReadSamples(), TEST(), and WriteData().
getWritePtr()
unsigned int CRingBuffer::getWritePtr ()
References m_critSection, and m_writePtr.
ReadData() [1/2]
bool CRingBuffer::ReadData (char * buf, unsigned int size)
References m_buffer, m_critSection, m_fillCount, m_readPtr, and m_size.
Referenced by CAudioDecoder::GetData(), XFILE::Pipe::Read(), XFILE::CCurlFile::CReadState::Read(), XFILE::CCurlFile::CReadState::ReadString(), and TEST().
ReadData() [2/2]
bool CRingBuffer::ReadData (CRingBuffer & rBuf, unsigned int size)
References Create(), getBuffer(), getMaxReadSize(), getMaxWriteSize(), m_critSection, m_readPtr, m_size, SkipBytes(), and WriteData().
SkipBytes()
bool CRingBuffer::SkipBytes (int skipSize)
References m_critSection, m_fillCount, m_readPtr, and m_size.
Referenced by ReadData(), and XFILE::CCurlFile::CReadState::Seek().
WriteData() [1/2]
bool CRingBuffer::WriteData (const char * buf, unsigned int size)
References m_buffer, m_critSection, m_fillCount, m_size, and m_writePtr.
Referenced by Append(), XFILE::CCurlFile::CReadState::FillBuffer(), ReadData(), CAudioDecoder::ReadSamples(), TEST(), XFILE::Pipe::Write(), XFILE::CCurlFile::CReadState::WriteCallback(), and WriteData().
WriteData() [2/2]
bool CRingBuffer::WriteData (CRingBuffer & rBuf, unsigned int size)
References Create(), getBuffer(), getMaxReadSize(), getMaxWriteSize(), getReadPtr(), getSize(), m_buffer, m_critSection, and WriteData().
Member Data Documentation
m_buffer
char* CRingBuffer::m_buffer private
Referenced by Create(), CRingBuffer(), Destroy(), getBuffer(), ReadData(), WriteData(), and WriteData().
m_critSection
CCriticalSection CRingBuffer::m_critSection private
Referenced by Clear(), Create(), Destroy(), getMaxReadSize(), getMaxWriteSize(), getSize(), getWritePtr(), ReadData(), ReadData(), SkipBytes(), WriteData(), and WriteData().
m_fillCount
unsigned int CRingBuffer::m_fillCount private
Referenced by Clear(), CRingBuffer(), Destroy(), getMaxReadSize(), getMaxWriteSize(), ReadData(), SkipBytes(), and WriteData().
m_readPtr
unsigned int CRingBuffer::m_readPtr private
Referenced by Clear(), CRingBuffer(), Destroy(), getReadPtr(), ReadData(), ReadData(), and SkipBytes().
m_size
unsigned int CRingBuffer::m_size private
Referenced by Create(), CRingBuffer(), Destroy(), getMaxWriteSize(), getSize(), ReadData(), ReadData(), SkipBytes(), and WriteData().
m_writePtr
unsigned int CRingBuffer::m_writePtr private
Referenced by Clear(), CRingBuffer(), Destroy(), getWritePtr(), and WriteData().
The documentation for this class was generated from the following files:
RingBuffer.h
RingBuffer.cpp