Kodi Documentation: KODI::GAME::CGUIPortList Class Reference
KODI::GAME::CGUIPortList Class Reference
#include <GUIPortList.h>
Public Member Functions
CGUIPortList (CGUIWindow &window)
~CGUIPortList () override
void OnWindowLoaded () override
Callback when the GUI window is loaded.
void OnWindowUnload () override
Callback when the GUI window is unloaded.
bool Initialize (GameClientPtr gameClient) override
Initialize resources.
void Deinitialize () override
Deinitialize resources.
bool HasControl (int controlId) override
Query if a control with the given ID belongs to this list.
int GetCurrentControl () override
Query the ID of the current control in this list.
void Refresh () override
Refresh the contents of the list.
void FrameMove () override
Callback when a frame is rendered by the GUI.
void SetFocused () override
The port list has been focused in the GUI.
bool OnSelect () override
The port list has been selected.
void ResetPorts () override
Reset the ports to their game add-on's default configuration.
Public Member Functions inherited from KODI::GAME::IPortList
virtual ~IPortList ()=default
Private Member Functions
void OnEvent (const ADDON::AddonEvent &event)
bool AddItems (const CPortNode &port, unsigned int &itemId, const std::string &itemLabel)
void CleanupItems ()
void OnItemFocus (unsigned int itemIndex)
void OnItemSelect (unsigned int itemIndex)
void OnControllerSelected (const CPortNode &port, const ControllerPtr &controller)
Static Private Member Functions
static std::string GetLabel (const CPortNode &port)
Private Attributes
CGUIWindow & m_guiWindow
CControllerSelect m_controllerSelectDialog
std::string m_focusedPort
int m_currentItem {-1}
std::unique_ptr< CGUIViewControl > m_viewControl
std::unique_ptr< CFileItemList > m_vecItems
GameClientPtr m_gameClient
std::map< unsigned int, std::string > m_itemToAddress
std::map< std::string, unsigned int > m_addressToItem
Constructor & Destructor Documentation
CGUIPortList()
CGUIPortList::CGUIPortList (CGUIWindow & window)
~CGUIPortList()
CGUIPortList::~CGUIPortList () override
References Deinitialize().
Member Function Documentation
AddItems()
bool CGUIPortList::AddItems (const CPortNode & port, unsigned int & itemId, const std::string & itemLabel) private
References AddItems(), g_localizeStrings, CLocalizeStrings::Get(), KODI::GAME::CPortNode::GetActiveController(), KODI::GAME::CPortNode::GetAddress(), KODI::GAME::CControllerNode::GetController(), KODI::GAME::CControllerNode::GetHub(), GetLabel(), KODI::GAME::CControllerHub::GetPorts(), KODI::GAME::CPortNode::IsConnected(), m_addressToItem, m_itemToAddress, and m_vecItems.
Referenced by AddItems(), and Refresh().
CleanupItems()
void CGUIPortList::CleanupItems () private
References m_addressToItem, m_itemToAddress, and m_vecItems.
Referenced by Deinitialize(), and Refresh().
Deinitialize()
void CGUIPortList::Deinitialize () override virtual
Deinitialize resources.
Implements KODI::GAME::IPortList.
References CleanupItems(), ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), and m_gameClient.
Referenced by ~CGUIPortList().
FrameMove()
void CGUIPortList::FrameMove () override virtual
Callback when a frame is rendered by the GUI.
Implements KODI::GAME::IPortList.
References m_currentItem, m_viewControl, and OnItemFocus().
GetCurrentControl()
int CGUIPortList::GetCurrentControl () override virtual
Query the ID of the current control in this list.
Returns
The control ID, or -1 if no control is currently active
Implements KODI::GAME::IPortList.
References m_viewControl.
GetLabel()
std::string CGUIPortList::GetLabel (const CPortNode & port) static private
References KODI::GAME::CONTROLLER, g_localizeStrings, CLocalizeStrings::Get(), KODI::GAME::CPortNode::GetAddress(), KODI::GAME::CPortNode::GetPortID(), KODI::GAME::CPortNode::GetPortType(), KODI::GAME::KEYBOARD, CLog::Log(), LOGERROR, and KODI::GAME::MOUSE.
Referenced by AddItems(), and Refresh().
HasControl()
bool CGUIPortList::HasControl (int controlId) override virtual
Query if a control with the given ID belongs to this list.
Implements KODI::GAME::IPortList.
References m_viewControl.
Initialize()
bool CGUIPortList::Initialize (GameClientPtr gameClient) override virtual
Initialize resources.
Parameters
gameClient The game client providing the ports
Returns
True if the resource is initialized and can be used, false if the resource failed to initialize and must not be used
Implements KODI::GAME::IPortList.
References DEFAULT_VIEW_LIST, ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), m_gameClient, m_viewControl, OnEvent(), and Refresh().
OnControllerSelected()
void CGUIPortList::OnControllerSelected (const CPortNode & port, const ControllerPtr & controller) private
References CONTROL_PORT_LIST, g_localizeStrings, CLocalizeStrings::Get(), KODI::GAME::CPortNode::GetAddress(), CServiceBroker::GetAppMessenger(), CGUIControl::GetID(), GUI_MSG_REFRESH_LIST, m_gameClient, m_guiWindow, and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by OnItemSelect().
OnEvent()
void CGUIPortList::OnEvent (const ADDON::AddonEvent & event) private
References ADDON::AddonEvent::addonId, CONTROL_PORT_LIST, CServiceBroker::GetAppMessenger(), CGUIControl::GetID(), GUI_MSG_REFRESH_LIST, m_guiWindow, and CGUIMessage::SetStringParam().
Referenced by Initialize().
OnItemFocus()
void CGUIPortList::OnItemFocus (unsigned int itemIndex) private
References m_focusedPort, and m_itemToAddress.
Referenced by FrameMove(), and Refresh().
OnItemSelect()
void CGUIPortList::OnItemSelect (unsigned int itemIndex) private
References KODI::GAME::CPortNode::GetActiveController(), KODI::GAME::CPortNode::GetCompatibleControllers(), KODI::GAME::CControllerNode::GetController(), KODI::GAME::CPortNode::GetPort(), KODI::GAME::CControllerSelect::Initialize(), KODI::GAME::CPortNode::IsForceConnected(), m_controllerSelectDialog, m_gameClient, m_itemToAddress, and OnControllerSelected().
Referenced by OnSelect().
OnSelect()
bool CGUIPortList::OnSelect () override virtual
The port list has been selected.
True if a control was active, false of all controls were inactive
Implements KODI::GAME::IPortList.
References m_viewControl, and OnItemSelect().
OnWindowLoaded()
void CGUIPortList::OnWindowLoaded () override virtual
Callback when the GUI window is loaded.
Implements KODI::GAME::IPortList.
References CONTROL_PORT_LIST, CGUIControlLookup::GetControl(), CGUIControl::GetID(), m_guiWindow, and m_viewControl.
OnWindowUnload()
void CGUIPortList::OnWindowUnload () override virtual
Callback when the GUI window is unloaded.
Implements KODI::GAME::IPortList.
References m_viewControl.
Refresh()
void CGUIPortList::Refresh () override virtual
Refresh the contents of the list.
Implements KODI::GAME::IPortList.
References AddItems(), CleanupItems(), GetLabel(), KODI::GAME::CControllerHub::GetPorts(), m_addressToItem, m_focusedPort, m_gameClient, m_vecItems, m_viewControl, and OnItemFocus().
Referenced by Initialize().
ResetPorts()
void CGUIPortList::ResetPorts () override virtual
Reset the ports to their game add-on's default configuration.
Implements KODI::GAME::IPortList.
References CONTROL_PORT_LIST, CServiceBroker::GetAppMessenger(), CGUIControl::GetID(), GUI_MSG_REFRESH_LIST, m_gameClient, and m_guiWindow.
SetFocused()
void CGUIPortList::SetFocused () override virtual
The port list has been focused in the GUI.
Implements KODI::GAME::IPortList.
References m_viewControl.
Member Data Documentation
m_addressToItem
std::map<std::string, unsigned int> KODI::GAME::CGUIPortList::m_addressToItem private
Referenced by AddItems(), CleanupItems(), and Refresh().
m_controllerSelectDialog
CControllerSelect KODI::GAME::CGUIPortList::m_controllerSelectDialog private
Referenced by OnItemSelect().
m_currentItem
int KODI::GAME::CGUIPortList::m_currentItem {-1} private
Referenced by FrameMove().
m_focusedPort
std::string KODI::GAME::CGUIPortList::m_focusedPort private
Referenced by OnItemFocus(), and Refresh().
m_gameClient
GameClientPtr KODI::GAME::CGUIPortList::m_gameClient private
Referenced by Deinitialize(), Initialize(), OnControllerSelected(), OnItemSelect(), Refresh(), and ResetPorts().
m_guiWindow
CGUIWindow& KODI::GAME::CGUIPortList::m_guiWindow private
Referenced by OnControllerSelected(), OnEvent(), OnWindowLoaded(), and ResetPorts().
m_itemToAddress
std::map<unsigned int, std::string> KODI::GAME::CGUIPortList::m_itemToAddress private
Referenced by AddItems(), CleanupItems(), OnItemFocus(), and OnItemSelect().
m_vecItems
std::unique_ptr<CFileItemList> KODI::GAME::CGUIPortList::m_vecItems private
Referenced by AddItems(), CleanupItems(), and Refresh().
m_viewControl
std::unique_ptr<CGUIViewControl> KODI::GAME::CGUIPortList::m_viewControl private
Referenced by FrameMove(), GetCurrentControl(), HasControl(), Initialize(), OnSelect(), OnWindowLoaded(), OnWindowUnload(), Refresh(), and SetFocused().
The documentation for this class was generated from the following files:
GUIPortList.h
GUIPortList.cpp