Kodi Documentation: PVR::CPVRGUIChannelNavigator Class Reference
PVR::CPVRGUIChannelNavigator Class Reference
#include <PVRGUIChannelNavigator.h>
Public Member Functions
CPVRGUIChannelNavigator ()
virtual ~CPVRGUIChannelNavigator ()
template<typename A >
void Subscribe (A *owner, void(A::*fn)(const PVRPreviewAndPlayerShowInfoChangedEvent &))
Subscribe to the event stream for changes of channel preview and player show info.
template<typename A >
void Unsubscribe (A *obj)
Unsubscribe from the event stream for changes of channel preview and player show info.
void Notify (const KODI::GUILIB::GUIINFO::PlayerShowInfoChangedEvent &event)
CEventStream callback for player show info flag changes.
void SelectNextChannel (ChannelSwitchMode eSwitchMode)
Select the next channel in currently playing channel group, relative to the currently selected channel.
void SelectPreviousChannel (ChannelSwitchMode eSwitchMode)
Select the previous channel in currently playing channel group, relative to the currently selected channel.
void SwitchToCurrentChannel ()
Switch to the currently selected channel.
bool IsPreview () const
Query the state of channel preview.
bool IsPreviewAndShowInfo () const
Query the state of channel preview and channel info OSD.
void ShowInfo ()
Show the channel info OSD.
void HideInfo ()
Hide the channel info OSD.
void ToggleInfo ()
Toggle the channel info OSD visibility.
void SetPlayingChannel (const std::shared_ptr< CPVRChannelGroupMember > &groupMember)
Set a new playing channel group member and show the channel info OSD for the new channel.
void ClearPlayingChannel ()
Clear the currently playing channel and hide the channel info OSD.
Private Member Functions
std::shared_ptr< CPVRChannelGroupMember > GetNextOrPrevChannel (bool bNext)
Get next or previous channel group member of the playing channel group, relative to the currently selected channel group member.
void SelectChannel (const std::shared_ptr< CPVRChannelGroupMember > &groupMember, ChannelSwitchMode eSwitchMode)
Select a given channel group member, display channel info OSD, switch according to given switch mode.
void ShowInfo (bool bForce)
Show the channel info OSD.
void SubscribeToShowInfoEventStream ()
Subscribe to the event stream for changes of player show info.
void CheckAndPublishPreviewAndPlayerShowInfoChangedEvent ()
Check if property preview and show info value changed, inform subscribers in case.
Private Attributes
CCriticalSection m_critSection
std::shared_ptr< CPVRChannelGroupMember > m_playingChannel
std::shared_ptr< CPVRChannelGroupMember > m_currentChannel
int m_iChannelEntryJobId = -1
int m_iChannelInfoJobId = -1
CEventSource< PVRPreviewAndPlayerShowInfoChangedEvent > m_events
bool m_playerShowInfo {false}
bool m_previewAndPlayerShowInfo {false}
Constructor & Destructor Documentation
CPVRGUIChannelNavigator()
CPVRGUIChannelNavigator::CPVRGUIChannelNavigator ()
~CPVRGUIChannelNavigator()
CPVRGUIChannelNavigator::~CPVRGUIChannelNavigator () virtual
References CServiceBroker::GetGUI().
Member Function Documentation
CheckAndPublishPreviewAndPlayerShowInfoChangedEvent()
void CPVRGUIChannelNavigator::CheckAndPublishPreviewAndPlayerShowInfoChangedEvent () private
Check if property preview and show info value changed, inform subscribers in case.
References IsPreview(), m_critSection, m_events, m_playerShowInfo, and m_previewAndPlayerShowInfo.
Referenced by ClearPlayingChannel(), HideInfo(), Notify(), SelectChannel(), and SetPlayingChannel().
ClearPlayingChannel()
void CPVRGUIChannelNavigator::ClearPlayingChannel ()
Clear the currently playing channel and hide the channel info OSD.
References CheckAndPublishPreviewAndPlayerShowInfoChangedEvent(), HideInfo(), m_critSection, and m_playingChannel.
Referenced by PVR::CPVRGUIActionsChannels::OnPlaybackStopped().
GetNextOrPrevChannel()
std::shared_ptr< CPVRChannelGroupMember > CPVRGUIChannelNavigator::GetNextOrPrevChannel (bool bNext) private
Get next or previous channel group member of the playing channel group, relative to the currently selected channel group member.
Parameters
bNext True to get the next channel group member, false to get the previous channel group member.
return The channel or nullptr if not found.
References CServiceBroker::GetPVRManager(), m_critSection, m_currentChannel, and PVR::CPVRManager::PlaybackState().
Referenced by SelectNextChannel(), and SelectPreviousChannel().
HideInfo()
void CPVRGUIChannelNavigator::HideInfo ()
Hide the channel info OSD.
References CheckAndPublishPreviewAndPlayerShowInfoChangedEvent(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CServiceBroker::GetJobManager(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetPlayerInfoProvider(), m_critSection, m_currentChannel, m_iChannelInfoJobId, m_playingChannel, CGUIInfoManager::SetCurrentItem(), and KODI::GUILIB::GUIINFO::CPlayerGUIInfo::SetShowInfo().
Referenced by ClearPlayingChannel(), and ToggleInfo().
IsPreview()
bool CPVRGUIChannelNavigator::IsPreview () const
Query the state of channel preview.
Returns
True, if the currently selected channel is different from the currently playing channel, False otherwise.
References m_critSection, m_currentChannel, and m_playingChannel.
Referenced by CheckAndPublishPreviewAndPlayerShowInfoChangedEvent(), and SelectChannel().
IsPreviewAndShowInfo()
bool CPVRGUIChannelNavigator::IsPreviewAndShowInfo () const
Query the state of channel preview and channel info OSD.
Returns
True, if the currently selected channel is different from the currently playing channel and channel info OSD is active, False otherwise.
References m_critSection, and m_previewAndPlayerShowInfo.
Notify()
void CPVRGUIChannelNavigator::Notify (const KODI::GUILIB::GUIINFO::PlayerShowInfoChangedEvent & event)
CEventStream callback for player show info flag changes.
Parameters
event The event.
References CheckAndPublishPreviewAndPlayerShowInfoChangedEvent(), m_critSection, and m_playerShowInfo.
Referenced by SubscribeToShowInfoEventStream().
SelectChannel()
void CPVRGUIChannelNavigator::SelectChannel (const std::shared_ptr< CPVRChannelGroupMember > & groupMember, ChannelSwitchMode eSwitchMode) private
Select a given channel group member, display channel info OSD, switch according to given switch mode.
Parameters
groupMember The channel group member to select.
eSwitchMode The channel switch mode.
References CheckAndPublishPreviewAndPlayerShowInfoChangedEvent(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CServiceBroker::GetJobManager(), CServiceBroker::GetSettingsComponent(), PVR::INSTANT_OR_DELAYED_SWITCH, IsPreview(), m_critSection, m_currentChannel, m_iChannelEntryJobId, CGUIInfoManager::SetCurrentItem(), CSettings::SETTING_PVRPLAYBACK_CHANNELENTRYTIMEOUT, ShowInfo(), and SwitchToCurrentChannel().
Referenced by SelectNextChannel(), and SelectPreviousChannel().
SelectNextChannel()
void CPVRGUIChannelNavigator::SelectNextChannel (ChannelSwitchMode eSwitchMode)
Select the next channel in currently playing channel group, relative to the currently selected channel.
Parameters
eSwitchMode controls whether only the channel info OSD is triggered or whether additionally a (delayed) channel switch will be done.
References GetNextOrPrevChannel(), m_critSection, m_playerShowInfo, PVR::NO_SWITCH, SelectChannel(), and ShowInfo().
SelectPreviousChannel()
void CPVRGUIChannelNavigator::SelectPreviousChannel (ChannelSwitchMode eSwitchMode)
Select the previous channel in currently playing channel group, relative to the currently selected channel.
Parameters
eSwitchMode controls whether only the channel info OSD is triggered or whether additionally a (delayed) channel switch will be done.
References GetNextOrPrevChannel(), m_critSection, m_playerShowInfo, PVR::NO_SWITCH, SelectChannel(), and ShowInfo().
SetPlayingChannel()
void CPVRGUIChannelNavigator::SetPlayingChannel (const std::shared_ptr< CPVRChannelGroupMember > & groupMember)
Set a new playing channel group member and show the channel info OSD for the new channel.
Parameters
groupMember The new playing channel group member
References CheckAndPublishPreviewAndPlayerShowInfoChangedEvent(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), m_critSection, m_currentChannel, m_playingChannel, CGUIInfoManager::SetCurrentItem(), and ShowInfo().
Referenced by PVR::CPVRGUIActionsChannels::OnPlaybackStarted().
ShowInfo() [1/2]
void CPVRGUIChannelNavigator::ShowInfo ()
Show the channel info OSD.
References ShowInfo().
Referenced by SelectChannel(), SelectNextChannel(), SelectPreviousChannel(), SetPlayingChannel(), ShowInfo(), and ToggleInfo().
ShowInfo() [2/2]
void CPVRGUIChannelNavigator::ShowInfo (bool bForce) private
Show the channel info OSD.
Parameters
bForce True ignores value of SETTING_PVRMENU_DISPLAYCHANNELINFO and always activates the info, False acts aaccording settings value.
References CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CServiceBroker::GetJobManager(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetPlayerInfoProvider(), CServiceBroker::GetSettingsComponent(), m_critSection, m_iChannelInfoJobId, KODI::GUILIB::GUIINFO::CPlayerGUIInfo::SetShowInfo(), and CSettings::SETTING_PVRMENU_DISPLAYCHANNELINFO.
Subscribe()
template<typename A > void PVR::CPVRGUIChannelNavigator::Subscribe (A * owner, void(A::*)(const PVRPreviewAndPlayerShowInfoChangedEvent &) fn) inline
Subscribe to the event stream for changes of channel preview and player show info.
Parameters
owner The subscriber.
fn The callback function of the subscriber for the events.
References m_events, owner, and SubscribeToShowInfoEventStream().
SubscribeToShowInfoEventStream()
void CPVRGUIChannelNavigator::SubscribeToShowInfoEventStream () private
Subscribe to the event stream for changes of player show info.
References KODI::GUILIB::GUIINFO::CPlayerGUIInfo::Events(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetPlayerInfoProvider(), and Notify().
Referenced by Subscribe().
SwitchToCurrentChannel()
void CPVRGUIChannelNavigator::SwitchToCurrentChannel ()
Switch to the currently selected channel.
References PVR::CPVRManager::Get(), CServiceBroker::GetJobManager(), CServiceBroker::GetPVRManager(), m_critSection, m_currentChannel, and m_iChannelEntryJobId.
Referenced by SelectChannel().
ToggleInfo()
void CPVRGUIChannelNavigator::ToggleInfo ()
Toggle the channel info OSD visibility.
References HideInfo(), m_critSection, m_playerShowInfo, and ShowInfo().
Unsubscribe()
template<typename A > void PVR::CPVRGUIChannelNavigator::Unsubscribe (A * obj) inline
Unsubscribe from the event stream for changes of channel preview and player show info.
Parameters
obj The subscriber.
References m_events.
Referenced by PVR::CPVRGUIInfo::Stop().
Member Data Documentation
m_critSection
CCriticalSection PVR::CPVRGUIChannelNavigator::m_critSection mutable private
Referenced by CheckAndPublishPreviewAndPlayerShowInfoChangedEvent(), ClearPlayingChannel(), GetNextOrPrevChannel(), HideInfo(), IsPreview(), IsPreviewAndShowInfo(), Notify(), SelectChannel(), SelectNextChannel(), SelectPreviousChannel(), SetPlayingChannel(), ShowInfo(), SwitchToCurrentChannel(), and ToggleInfo().
m_currentChannel
std::shared_ptr<CPVRChannelGroupMember> PVR::CPVRGUIChannelNavigator::m_currentChannel private
Referenced by GetNextOrPrevChannel(), HideInfo(), IsPreview(), SelectChannel(), SetPlayingChannel(), and SwitchToCurrentChannel().
m_events
CEventSource<PVRPreviewAndPlayerShowInfoChangedEvent> PVR::CPVRGUIChannelNavigator::m_events private
Referenced by CheckAndPublishPreviewAndPlayerShowInfoChangedEvent(), Subscribe(), and Unsubscribe().
m_iChannelEntryJobId
int PVR::CPVRGUIChannelNavigator::m_iChannelEntryJobId = -1 private
Referenced by SelectChannel(), and SwitchToCurrentChannel().
m_iChannelInfoJobId
int PVR::CPVRGUIChannelNavigator::m_iChannelInfoJobId = -1 private
Referenced by HideInfo(), and ShowInfo().
m_playerShowInfo
bool PVR::CPVRGUIChannelNavigator::m_playerShowInfo {false} private
Referenced by CheckAndPublishPreviewAndPlayerShowInfoChangedEvent(), Notify(), SelectNextChannel(), SelectPreviousChannel(), and ToggleInfo().
m_playingChannel
std::shared_ptr<CPVRChannelGroupMember> PVR::CPVRGUIChannelNavigator::m_playingChannel private
Referenced by ClearPlayingChannel(), HideInfo(), IsPreview(), and SetPlayingChannel().
m_previewAndPlayerShowInfo
bool PVR::CPVRGUIChannelNavigator::m_previewAndPlayerShowInfo {false} private
Referenced by CheckAndPublishPreviewAndPlayerShowInfoChangedEvent(), and IsPreviewAndShowInfo().
The documentation for this class was generated from the following files:
PVRGUIChannelNavigator.h
PVRGUIChannelNavigator.cpp