Kodi Documentation: CALSAHControlMonitor Class Reference
CALSAHControlMonitor Class Reference
#include <ALSAHControlMonitor.h>
Classes
struct CTLHandle
Public Member Functions
CALSAHControlMonitor ()
~CALSAHControlMonitor ()
bool Add (const std::string &ctlHandleName, snd_ctl_elem_iface_t interface, unsigned int device, const std::string &name)
void Clear ()
void Start ()
void Stop ()
Public Member Functions inherited from IPlatformService
virtual ~IPlatformService ()=default
Private Member Functions
snd_hctl_t * GetHandle (const std::string &ctlHandleName)
void PutHandle (const std::string &ctlHandleName)
Static Private Member Functions
static int HCTLCallback (snd_hctl_elem_t *elem, unsigned int mask)
static void FDEventCallback (int id, int fd, short revents, void *data)
Private Attributes
std::map< std::string, CTLHandle > m_ctlHandles
std::vector< int > m_fdMonitorIds
Constructor & Destructor Documentation
CALSAHControlMonitor()
CALSAHControlMonitor::CALSAHControlMonitor () default
~CALSAHControlMonitor()
CALSAHControlMonitor::~CALSAHControlMonitor ()
References Clear().
Member Function Documentation
Add()
bool CALSAHControlMonitor::Add (const std::string & ctlHandleName, snd_ctl_elem_iface_t interface, unsigned int device, const std::string & name)
References GetHandle(), HCTLCallback(), id, name, and PutHandle().
Referenced by CAESinkALSA::EnumerateDevice().
Clear()
void CALSAHControlMonitor::Clear ()
References m_ctlHandles, and Stop().
Referenced by CAESinkALSA::Cleanup(), CAESinkALSA::EnumerateDevicesEx(), and ~CALSAHControlMonitor().
FDEventCallback()
void CALSAHControlMonitor::FDEventCallback (int id, int fd, short revents, void * data) static private
References data().
Referenced by Start().
GetHandle()
snd_hctl_t * CALSAHControlMonitor::GetHandle (const std::string & ctlHandleName) private
References CLog::Log(), LOGERROR, LOGWARNING, and m_ctlHandles.
Referenced by Add().
HCTLCallback()
int CALSAHControlMonitor::HCTLCallback (snd_hctl_elem_t * elem, unsigned int mask) static private
References IAE::DeviceChange(), CServiceBroker::GetActiveAE(), CLog::Log(), and LOGDEBUG.
Referenced by Add().
PutHandle()
void CALSAHControlMonitor::PutHandle (const std::string & ctlHandleName) private
References m_ctlHandles.
Referenced by Add().
Start()
void CALSAHControlMonitor::Start ()
References CFDEventMonitor::AddFDs(), events, FDEventCallback(), CServiceBroker::GetPlatform(), CPlatform::GetService(), m_ctlHandles, and m_fdMonitorIds.
Stop()
void CALSAHControlMonitor::Stop ()
References CServiceBroker::GetPlatform(), CPlatform::GetService(), m_fdMonitorIds, and CFDEventMonitor::RemoveFDs().
Referenced by Clear().
Member Data Documentation
m_ctlHandles
std::map<std::string, CTLHandle> CALSAHControlMonitor::m_ctlHandles private
Referenced by Clear(), GetHandle(), PutHandle(), and Start().
m_fdMonitorIds
std::vector<int> CALSAHControlMonitor::m_fdMonitorIds private
Referenced by Start(), and Stop().
The documentation for this class was generated from the following files:
ALSAHControlMonitor.h
ALSAHControlMonitor.cpp