Kodi Documentation: anonymous_namespace{WinSystemWayland.cpp} Namespace Reference
anonymous_namespace{WinSystemWayland.cpp} Namespace Reference
Namespaces
namespace WinSystemWaylandProtocol
Classes
class MessageHandle
Scope guard for Actor::Message.
struct OutputCurrentRefreshRateComparer
struct OutputScaleComparer
Functions
RESOLUTION FindMatchingCustomResolution (CSizeInt size, float refreshRate)
Function Documentation
FindMatchingCustomResolution()
RESOLUTION anonymous_namespace{WinSystemWayland.cpp}::FindMatchingCustomResolution (CSizeInt size, float refreshRate)
References MathUtils::FloatEquals(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RES_DESKTOP, RES_INVALID, and CDisplaySettings::ResolutionInfoSize().