Kodi Documentation: CJSONVariantWriter Class Reference
CJSONVariantWriter Class Reference
#include <JSONVariantWriter.h>
Public Member Functions
CJSONVariantWriter ()=delete
Static Public Member Functions
static bool Write (const CVariant &value, std::string &output, bool compact)
Constructor & Destructor Documentation
CJSONVariantWriter()
CJSONVariantWriter::CJSONVariantWriter () delete
Member Function Documentation
Write()
bool CJSONVariantWriter::Write (const CVariant & value, std::string & output, bool compact) static
References InternalWrite(), and value.
Referenced by CDVDVideoCodecStarfish::AddData(), CAESinkStarfish::AddPackets(), XBPython::Announce(), JSONRPC::IJSONRPCAnnouncer::AnnouncementToJSONRPC(), JSONRPC::CJSONRPC::HandleMethodCall(), CHTTPJsonRpcHandler::HandleRequest(), KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS::Inhibit(), CAESinkStarfish::Initialize(), JSONRPC::CJSONRPC::MethodCall(), KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS::OnScreenSaverAboutToStart(), CDVDVideoCodecStarfish::OpenInternal(), CLunaPowerManagement::Powerdown(), ADDON::PythonDetails(), CLunaPowerManagement::Reboot(), KODI::PLAYLIST::CSmartPlaylist::SaveAsJson(), ADDON::CAddonDatabaseSerializer::SerializeMetadata(), CSettingsValueFlatJsonSerializer::SerializeValues(), CDVDVideoCodecStarfish::SetHDR(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and ADDON::CAddonDatabase::UpdateTables().
The documentation for this class was generated from the following files:
JSONVariantWriter.h
JSONVariantWriter.cpp