Kodi Documentation: KODI::PIPEWIRE::CPipewireCore Class Reference
KODI::PIPEWIRE::CPipewireCore Class Reference
#include <PipewireCore.h>
Classes
struct PipewireCoreDeleter
Public Member Functions
CPipewireCore (CPipewireContext &context)
CPipewireCore ()=delete
~CPipewireCore ()
pw_core * Get () const
CPipewireContext & GetContext () const
void Sync ()
int GetSync () const
Static Private Member Functions
static void OnCoreDone (void *userdata, uint32_t id, int seq)
static pw_core_events CreateCoreEvents ()
Private Attributes
CPipewireContext & m_context
const pw_core_events m_coreEvents
spa_hook m_coreListener
std::unique_ptr< pw_core, PipewireCoreDeleter > m_core
int m_sync
Constructor & Destructor Documentation
CPipewireCore() [1/2]
CPipewireCore::CPipewireCore (CPipewireContext & context) explicit
References KODI::PIPEWIRE::CPipewireContext::Get(), CLog::Log(), LOGERROR, m_core, m_coreEvents, and m_coreListener.
CPipewireCore() [2/2]
KODI::PIPEWIRE::CPipewireCore::CPipewireCore () delete
~CPipewireCore()
CPipewireCore::~CPipewireCore ()
References m_coreListener.
Member Function Documentation
CreateCoreEvents()
pw_core_events CPipewireCore::CreateCoreEvents () static private
References OnCoreDone().
Get()
pw_core * KODI::PIPEWIRE::CPipewireCore::Get () const inline
References m_core.
Referenced by KODI::PIPEWIRE::CPipewireRegistry::CPipewireRegistry(), and KODI::PIPEWIRE::CPipewireStream::CPipewireStream().
GetContext()
CPipewireContext & KODI::PIPEWIRE::CPipewireCore::GetContext () const inline
References m_context.
Referenced by KODI::PIPEWIRE::CPipewireStream::Drained(), OnCoreDone(), KODI::PIPEWIRE::CPipewireNode::Param(), KODI::PIPEWIRE::CPipewireStream::Process(), and KODI::PIPEWIRE::CPipewireStream::StateChanged().
GetSync()
int KODI::PIPEWIRE::CPipewireCore::GetSync () const inline
References m_sync.
OnCoreDone()
void CPipewireCore::OnCoreDone (void * userdata, uint32_t id, int seq) static private
References GetContext(), KODI::PIPEWIRE::CPipewireContext::GetThreadLoop(), and KODI::PIPEWIRE::CPipewireThreadLoop::Signal().
Referenced by CreateCoreEvents().
Sync()
void CPipewireCore::Sync ()
References m_core, and m_sync.
Member Data Documentation
m_context
CPipewireContext& KODI::PIPEWIRE::CPipewireCore::m_context private
Referenced by GetContext().
m_core
std::unique_ptr<pw_core, PipewireCoreDeleter> KODI::PIPEWIRE::CPipewireCore::m_core private
Referenced by CPipewireCore(), Get(), and Sync().
m_coreEvents
const pw_core_events KODI::PIPEWIRE::CPipewireCore::m_coreEvents private
Referenced by CPipewireCore().
m_coreListener
spa_hook KODI::PIPEWIRE::CPipewireCore::m_coreListener private
Referenced by CPipewireCore(), and ~CPipewireCore().
m_sync
int KODI::PIPEWIRE::CPipewireCore::m_sync private
Referenced by GetSync(), and Sync().
The documentation for this class was generated from the following files:
PipewireCore.h
PipewireCore.cpp