Kodi Documentation: CGUIShaderDX Class Reference
CGUIShaderDX Class Reference
#include <GUIShaderDX.h>
Classes
struct cbViewPort
struct cbWorld
struct cbWorldViewProj
Public Member Functions
CGUIShaderDX ()
~CGUIShaderDX ()
bool Initialize ()
void Begin (unsigned int flags)
void End (void)
void ApplyStateBlock (void)
void RestoreBuffers (void)
void SetShaderViews (unsigned int numViews, ID3D11ShaderResourceView **views)
void SetViewPort (D3D11_VIEWPORT viewPort)
void XM_CALLCONV GetWVP (DirectX::XMMATRIX &w, DirectX::XMMATRIX &v, DirectX::XMMATRIX &p)
DirectX::XMMATRIX XM_CALLCONV GetWorld () const
DirectX::XMMATRIX XM_CALLCONV GetView () const
DirectX::XMMATRIX XM_CALLCONV GetProjection () const
void XM_CALLCONV SetWVP (const DirectX::XMMATRIX &w, const DirectX::XMMATRIX &v, const DirectX::XMMATRIX &p)
void XM_CALLCONV SetWorld (const DirectX::XMMATRIX &value)
void XM_CALLCONV SetView (const DirectX::XMMATRIX &value)
void XM_CALLCONV SetProjection (const DirectX::XMMATRIX &value)
void Project (float &x, float &y, float &z)
void DrawQuad (Vertex &v1, Vertex &v2, Vertex &v3, Vertex &v4)
void DrawIndexed (unsigned int indexCount, unsigned int startIndex, unsigned int startVertex)
void Draw (unsigned int vertexCount, unsigned int startVertex)
bool HardwareClipIsPossible (void) const
float GetClipXFactor (void) const
float GetClipXOffset (void) const
float GetClipYFactor (void) const
float GetClipYOffset (void) const
void * operator new (size_t size)
void operator delete (void *ptr)
Private Member Functions
void Release (void)
bool CreateBuffers (void)
bool CreateSamplers (void)
void ApplyChanges (void)
void ClipToScissorParams (void)
Private Attributes
cbViewPort m_cbViewPort = {}
cbWorldViewProj m_cbWorldViewProj = {}
bool m_bCreated
size_t m_currentShader
CD3DVertexShader m_vertexShader
CD3DPixelShader m_pixelShader [SHADER_METHOD_RENDER_COUNT]
Microsoft::WRL::ComPtr< ID3D11SamplerState > m_pSampLinear
bool m_bIsWVPDirty
bool m_bIsVPDirty
Microsoft::WRL::ComPtr< ID3D11Buffer > m_pWVPBuffer
Microsoft::WRL::ComPtr< ID3D11Buffer > m_pVPBuffer
Microsoft::WRL::ComPtr< ID3D11Buffer > m_pVertexBuffer
bool m_clipPossible
float m_clipXFactor
float m_clipXOffset
float m_clipYFactor
float m_clipYOffset
Constructor & Destructor Documentation
CGUIShaderDX()
CGUIShaderDX::CGUIShaderDX ()
~CGUIShaderDX()
CGUIShaderDX::~CGUIShaderDX ()
References Release().
Member Function Documentation
ApplyChanges()
void CGUIShaderDX::ApplyChanges (void) private
References DX::DeviceResources::Get(), m_bIsVPDirty, m_bIsWVPDirty, m_cbViewPort, m_cbWorldViewProj, m_pVPBuffer, m_pWVPBuffer, CGUIShaderDX::cbWorldViewProj::projection, CGUIShaderDX::cbWorldViewProj::view, and CGUIShaderDX::cbWorldViewProj::world.
Referenced by Draw(), DrawIndexed(), and DrawQuad().
ApplyStateBlock()
void CGUIShaderDX::ApplyStateBlock (void)
References CD3DVertexShader::BindShader(), CD3DPixelShader::BindShader(), DX::DeviceResources::Get(), m_bCreated, m_currentShader, m_pixelShader, m_pSampLinear, m_pVPBuffer, m_pWVPBuffer, m_vertexShader, and RestoreBuffers().
Referenced by CRenderSystemDX::ApplyStateBlock(), and CRenderSystemDX::InitGUIShader().
Begin()
void CGUIShaderDX::Begin (unsigned int flags)
References CD3DPixelShader::BindShader(), ClipToScissorParams(), m_bCreated, m_currentShader, and m_pixelShader.
Referenced by CGUITextureD3D::Draw(), CD3DTexture::DrawQuad(), CGUIFontTTFDX::FirstBegin(), CSlideShowPicDX::Render(), OVERLAY::COverlayQuadsDX::Render(), OVERLAY::COverlayImageDX::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
ClipToScissorParams()
void CGUIShaderDX::ClipToScissorParams (void) private
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIMatrix(), CServiceBroker::GetWinSystem(), TransformMatrix::m, m_cbWorldViewProj, m_clipPossible, m_clipXFactor, m_clipXOffset, m_clipYFactor, m_clipYOffset, CGUIShaderDX::cbWorldViewProj::projection, CGUIShaderDX::cbWorldViewProj::view, CGUIShaderDX::cbWorldViewProj::world, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by Begin().
CreateBuffers()
bool CGUIShaderDX::CreateBuffers (void) private
References FAILED, DX::DeviceResources::Get(), CGUIShaderDX::cbViewPort::Height, CRectGen< T >::Height(), LOGERROR, m_bIsWVPDirty, m_cbViewPort, m_pVertexBuffer, m_pVPBuffer, m_pWVPBuffer, CGUIShaderDX::cbViewPort::TopLeftX, CGUIShaderDX::cbViewPort::TopLeftY, CGUIShaderDX::cbViewPort::Width, CRectGen< T >::Width(), CRectGen< T >::x1, and CRectGen< T >::y1.
Referenced by Initialize().
CreateSamplers()
bool CGUIShaderDX::CreateSamplers (void) private
References FAILED, DX::DeviceResources::Get(), and m_pSampLinear.
Referenced by Initialize().
Draw()
void CGUIShaderDX::Draw (unsigned int vertexCount, unsigned int startVertex)
References ApplyChanges(), DX::DeviceResources::Get(), and m_bCreated.
Referenced by CSlideShowPicDX::Render(), OVERLAY::COverlayQuadsDX::Render(), and OVERLAY::COverlayImageDX::Render().
DrawIndexed()
void CGUIShaderDX::DrawIndexed (unsigned int indexCount, unsigned int startIndex, unsigned int startVertex)
References ApplyChanges(), DX::DeviceResources::Get(), and m_bCreated.
Referenced by CGUIFontTTFDX::LastEnd().
DrawQuad()
void CGUIShaderDX::DrawQuad (Vertex & v1, Vertex & v2, Vertex & v3, Vertex & v4)
References ApplyChanges(), DX::DeviceResources::Get(), m_bCreated, and m_pVertexBuffer.
Referenced by CGUITextureD3D::Draw(), CD3DTexture::DrawQuad(), CSlideShowPicDX::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
End()
void CGUIShaderDX::End (void)
References m_bCreated.
Referenced by CRenderSystemDX::DestroyRenderSystem().
GetClipXFactor()
float CGUIShaderDX::GetClipXFactor (void) const inline
References m_clipXFactor.
Referenced by CRenderSystemDX::ClipRectToScissorRect().
GetClipXOffset()
float CGUIShaderDX::GetClipXOffset (void) const inline
References m_clipXOffset.
Referenced by CRenderSystemDX::ClipRectToScissorRect().
GetClipYFactor()
float CGUIShaderDX::GetClipYFactor (void) const inline
References m_clipYFactor.
Referenced by CRenderSystemDX::ClipRectToScissorRect().
GetClipYOffset()
float CGUIShaderDX::GetClipYOffset (void) const inline
References m_clipYOffset.
Referenced by CRenderSystemDX::ClipRectToScissorRect().
GetProjection()
DirectX::XMMATRIX XM_CALLCONV CGUIShaderDX::GetProjection () const inline
References m_cbWorldViewProj, and CGUIShaderDX::cbWorldViewProj::projection.
GetView()
DirectX::XMMATRIX XM_CALLCONV CGUIShaderDX::GetView () const inline
References m_cbWorldViewProj, and CGUIShaderDX::cbWorldViewProj::view.
Referenced by CGUIFontTTFDX::LastEnd().
GetWorld()
DirectX::XMMATRIX XM_CALLCONV CGUIShaderDX::GetWorld () const inline
References m_cbWorldViewProj, and CGUIShaderDX::cbWorldViewProj::world.
GetWVP()
void XM_CALLCONV CGUIShaderDX::GetWVP (DirectX::XMMATRIX & w, DirectX::XMMATRIX & v, DirectX::XMMATRIX & p) inline
References m_cbWorldViewProj, CGUIShaderDX::cbWorldViewProj::projection, CGUIShaderDX::cbWorldViewProj::view, and CGUIShaderDX::cbWorldViewProj::world.
Referenced by OVERLAY::COverlayQuadsDX::Render(), and OVERLAY::COverlayImageDX::Render().
HardwareClipIsPossible()
bool CGUIShaderDX::HardwareClipIsPossible (void) const inline
References m_clipPossible.
Referenced by CRenderSystemDX::ScissorsCanEffectClipping().
Initialize()
bool CGUIShaderDX::Initialize ()
References cbPSShaderCode, CD3DVertexShader::Create(), CreateBuffers(), CreateSamplers(), m_bCreated, m_pixelShader, m_vertexShader, CD3DVertexShader::Release(), Release(), and SHADER_METHOD_RENDER_COUNT.
Referenced by CRenderSystemDX::InitGUIShader().
operator delete()
void CGUIShaderDX::operator delete (void * ptr) inline
References KODI::MEMORY::AlignedFree().
operator new()
void * CGUIShaderDX::operator new (size_t size) inline
References KODI::MEMORY::AlignedMalloc().
Project()
void CGUIShaderDX::Project (float & x, float & y, float & z)
References CGUIShaderDX::cbViewPort::Height, m_cbViewPort, m_cbWorldViewProj, CGUIShaderDX::cbWorldViewProj::projection, CGUIShaderDX::cbViewPort::TopLeftX, CGUIShaderDX::cbViewPort::TopLeftY, CGUIShaderDX::cbWorldViewProj::view, CGUIShaderDX::cbViewPort::Width, and CGUIShaderDX::cbWorldViewProj::world.
Referenced by CRenderSystemDX::Project().
Release()
void CGUIShaderDX::Release (void) private
References m_bCreated, m_pSampLinear, m_pVertexBuffer, m_pVPBuffer, and m_pWVPBuffer.
Referenced by Initialize(), and ~CGUIShaderDX().
RestoreBuffers()
void CGUIShaderDX::RestoreBuffers (void)
References DX::DeviceResources::Get(), and m_pVertexBuffer.
Referenced by ApplyStateBlock(), CGUIFontTTFDX::LastEnd(), CSlideShowPicDX::Render(), OVERLAY::COverlayQuadsDX::Render(), and OVERLAY::COverlayImageDX::Render().
SetProjection()
void CGUIShaderDX::SetProjection (const DirectX::XMMATRIX & value)
References m_bIsWVPDirty, m_cbWorldViewProj, CGUIShaderDX::cbWorldViewProj::projection, and value.
Referenced by CRenderSystemDX::SetCameraPosition().
SetShaderViews()
void CGUIShaderDX::SetShaderViews (unsigned int numViews, ID3D11ShaderResourceView ** views)
References DX::DeviceResources::Get(), and m_bCreated.
Referenced by CGUITextureD3D::Draw(), CD3DTexture::DrawQuad(), CGUIFontTTFDX::LastEnd(), CSlideShowPicDX::Render(), OVERLAY::COverlayQuadsDX::Render(), OVERLAY::COverlayImageDX::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
SetView()
void CGUIShaderDX::SetView (const DirectX::XMMATRIX & value)
References m_bIsWVPDirty, m_cbWorldViewProj, value, and CGUIShaderDX::cbWorldViewProj::view.
Referenced by CGUIFontTTFDX::LastEnd(), and CRenderSystemDX::SetCameraPosition().
SetViewPort()
void CGUIShaderDX::SetViewPort (D3D11_VIEWPORT viewPort)
References CGUIShaderDX::cbViewPort::Height, m_bIsVPDirty, m_cbViewPort, m_pVPBuffer, CGUIShaderDX::cbViewPort::TopLeftX, CGUIShaderDX::cbViewPort::TopLeftY, and CGUIShaderDX::cbViewPort::Width.
Referenced by CRenderSystemDX::RestoreViewPort(), and CRenderSystemDX::SetViewPort().
SetWorld()
void CGUIShaderDX::SetWorld (const DirectX::XMMATRIX & value)
References m_bIsWVPDirty, m_cbWorldViewProj, value, and CGUIShaderDX::cbWorldViewProj::world.
Referenced by OVERLAY::COverlayQuadsDX::Render(), OVERLAY::COverlayImageDX::Render(), and CRenderSystemDX::SetCameraPosition().
SetWVP()
void XM_CALLCONV CGUIShaderDX::SetWVP (const DirectX::XMMATRIX & w, const DirectX::XMMATRIX & v, const DirectX::XMMATRIX & p)
References m_bIsWVPDirty, m_cbWorldViewProj, CGUIShaderDX::cbWorldViewProj::projection, CGUIShaderDX::cbWorldViewProj::view, and CGUIShaderDX::cbWorldViewProj::world.
Referenced by OVERLAY::COverlayQuadsDX::Render(), and OVERLAY::COverlayImageDX::Render().
Member Data Documentation
m_bCreated
bool CGUIShaderDX::m_bCreated private
Referenced by ApplyStateBlock(), Begin(), Draw(), DrawIndexed(), DrawQuad(), End(), Initialize(), Release(), and SetShaderViews().
m_bIsVPDirty
bool CGUIShaderDX::m_bIsVPDirty private
Referenced by ApplyChanges(), and SetViewPort().
m_bIsWVPDirty
bool CGUIShaderDX::m_bIsWVPDirty private
Referenced by ApplyChanges(), CreateBuffers(), SetProjection(), SetView(), SetWorld(), and SetWVP().
m_cbViewPort
cbViewPort CGUIShaderDX::m_cbViewPort = {} private
Referenced by ApplyChanges(), CreateBuffers(), Project(), and SetViewPort().
m_cbWorldViewProj
cbWorldViewProj CGUIShaderDX::m_cbWorldViewProj = {} private
Referenced by ApplyChanges(), ClipToScissorParams(), GetProjection(), GetView(), GetWorld(), GetWVP(), Project(), SetProjection(), SetView(), SetWorld(), and SetWVP().
m_clipPossible
bool CGUIShaderDX::m_clipPossible private
Referenced by ClipToScissorParams(), and HardwareClipIsPossible().
m_clipXFactor
float CGUIShaderDX::m_clipXFactor private
Referenced by ClipToScissorParams(), and GetClipXFactor().
m_clipXOffset
float CGUIShaderDX::m_clipXOffset private
Referenced by ClipToScissorParams(), and GetClipXOffset().
m_clipYFactor
float CGUIShaderDX::m_clipYFactor private
Referenced by ClipToScissorParams(), and GetClipYFactor().
m_clipYOffset
float CGUIShaderDX::m_clipYOffset private
Referenced by ClipToScissorParams(), and GetClipYOffset().
m_currentShader
size_t CGUIShaderDX::m_currentShader private
Referenced by ApplyStateBlock(), and Begin().
m_pixelShader
CD3DPixelShader CGUIShaderDX::m_pixelShader[SHADER_METHOD_RENDER_COUNT] private
Referenced by ApplyStateBlock(), Begin(), and Initialize().
m_pSampLinear
Microsoft::WRL::ComPtr<ID3D11SamplerState> CGUIShaderDX::m_pSampLinear private
Referenced by ApplyStateBlock(), CreateSamplers(), and Release().
m_pVertexBuffer
Microsoft::WRL::ComPtr<ID3D11Buffer> CGUIShaderDX::m_pVertexBuffer private
Referenced by CreateBuffers(), DrawQuad(), Release(), and RestoreBuffers().
m_pVPBuffer
Microsoft::WRL::ComPtr<ID3D11Buffer> CGUIShaderDX::m_pVPBuffer private
Referenced by ApplyChanges(), ApplyStateBlock(), CreateBuffers(), Release(), and SetViewPort().
m_pWVPBuffer
Microsoft::WRL::ComPtr<ID3D11Buffer> CGUIShaderDX::m_pWVPBuffer private
Referenced by ApplyChanges(), ApplyStateBlock(), CreateBuffers(), and Release().
m_vertexShader
CD3DVertexShader CGUIShaderDX::m_vertexShader private
Referenced by ApplyStateBlock(), and Initialize().
The documentation for this class was generated from the following files:
GUIShaderDX.h
GUIShaderDX.cpp