Kodi Documentation: CGUIControlProfilerItem Class Reference
CGUIControlProfilerItem Class Reference
#include <GUIControlProfiler.h>
Public Member Functions
CGUIControlProfilerItem (CGUIControlProfiler *pProfiler, CGUIControlProfilerItem *pParent, CGUIControl *pControl)
~CGUIControlProfilerItem (void)
void Reset (CGUIControlProfiler *pProfiler)
void BeginVisibility (void)
void EndVisibility (void)
void BeginRender (void)
void EndRender (void)
void SaveToXML (TiXmlElement *parent)
unsigned int GetTotalTime (void) const
CGUIControlProfilerItem * AddControl (CGUIControl *pControl)
CGUIControlProfilerItem * FindOrAddControl (CGUIControl *pControl, bool recurse)
Public Attributes
CGUIControlProfiler * m_pProfiler
CGUIControlProfilerItem * m_pParent
CGUIControl * m_pControl
std::vector< CGUIControlProfilerItem * > m_vecChildren
std::string m_strDescription
int m_controlID
CGUIControl::GUICONTROLTYPES m_ControlType
unsigned int m_visTime = 0
unsigned int m_renderTime = 0
int64_t m_i64VisStart = 0
int64_t m_i64RenderStart = 0
Constructor & Destructor Documentation
CGUIControlProfilerItem()
CGUIControlProfilerItem::CGUIControlProfilerItem (CGUIControlProfiler * pProfiler, CGUIControlProfilerItem * pParent, CGUIControl * pControl)
References CGUIControl::GetControlType(), CGUIControl::GetDescription(), CGUIControl::GetID(), CGUIControl::GUICONTROL_UNKNOWN, m_controlID, m_ControlType, m_pControl, and m_strDescription.
~CGUIControlProfilerItem()
CGUIControlProfilerItem::~CGUIControlProfilerItem (void)
References Reset().
Member Function Documentation
AddControl()
CGUIControlProfilerItem * CGUIControlProfilerItem::AddControl (CGUIControl * pControl)
References m_pProfiler, and m_vecChildren.
Referenced by CGUIControlProfiler::FindOrAddControl(), and FindOrAddControl().
BeginRender()
void CGUIControlProfilerItem::BeginRender (void)
References CurrentHostCounter(), and m_i64RenderStart.
Referenced by CGUIControlProfiler::BeginRender().
BeginVisibility()
void CGUIControlProfilerItem::BeginVisibility (void)
References CurrentHostCounter(), and m_i64VisStart.
Referenced by CGUIControlProfiler::BeginVisibility().
EndRender()
void CGUIControlProfilerItem::EndRender (void)
References CurrentHostCounter(), CGUIControlProfiler::m_fPerfScale, m_i64RenderStart, m_pProfiler, and m_renderTime.
Referenced by CGUIControlProfiler::EndRender().
EndVisibility()
void CGUIControlProfilerItem::EndVisibility (void)
References CurrentHostCounter(), CGUIControlProfiler::m_fPerfScale, m_i64VisStart, m_pProfiler, and m_visTime.
Referenced by CGUIControlProfiler::EndVisibility().
FindOrAddControl()
CGUIControlProfilerItem * CGUIControlProfilerItem::FindOrAddControl (CGUIControl * pControl, bool recurse)
References AddControl(), FindOrAddControl(), CGUIControl::GetParentControl(), m_pControl, and m_vecChildren.
Referenced by CGUIControlProfiler::FindOrAddControl(), and FindOrAddControl().
GetTotalTime()
unsigned int CGUIControlProfilerItem::GetTotalTime (void) const inline
References m_renderTime, and m_visTime.
Referenced by CGUIControlProfiler::GetTotalTime(), and SaveToXML().
Reset()
void CGUIControlProfilerItem::Reset (CGUIControlProfiler * pProfiler)
References CGUIControl::GUICONTROL_UNKNOWN, m_controlID, m_ControlType, m_pControl, m_pProfiler, m_renderTime, m_vecChildren, and m_visTime.
Referenced by CGUIControlProfiler::EndFrame(), and CGUIControlProfiler::Start().
SaveToXML()
void CGUIControlProfilerItem::SaveToXML (TiXmlElement * parent)
References GetTotalTime(), CGUIControlProfiler::GetTotalTime(), CGUIControl::GUICONTAINER_FIXEDLIST, CGUIControl::GUICONTAINER_LIST, CGUIControl::GUICONTAINER_PANEL, CGUIControl::GUICONTAINER_WRAPLIST, CGUIControl::GUICONTROL_BORDEREDIMAGE, CGUIControl::GUICONTROL_BUTTON, CGUIControl::GUICONTROL_COLORBUTTON, CGUIControl::GUICONTROL_EDIT, CGUIControl::GUICONTROL_FADELABEL, CGUIControl::GUICONTROL_GROUP, CGUIControl::GUICONTROL_GROUPLIST, CGUIControl::GUICONTROL_IMAGE, CGUIControl::GUICONTROL_LABEL, CGUIControl::GUICONTROL_LISTGROUP, CGUIControl::GUICONTROL_LISTLABEL, CGUIControl::GUICONTROL_MOVER, CGUIControl::GUICONTROL_MULTI_IMAGE, CGUIControl::GUICONTROL_PROGRESS, CGUIControl::GUICONTROL_RADIO, CGUIControl::GUICONTROL_RESIZE, CGUIControl::GUICONTROL_RSS, CGUIControl::GUICONTROL_SCROLLBAR, CGUIControl::GUICONTROL_SETTINGS_SLIDER, CGUIControl::GUICONTROL_SLIDER, CGUIControl::GUICONTROL_SPIN, CGUIControl::GUICONTROL_SPINEX, CGUIControl::GUICONTROL_TEXTBOX, CGUIControl::GUICONTROL_TOGGLEBUTTON, CGUIControl::GUICONTROL_VIDEO, CGUIControl::GUICONTROL_VISUALISATION, m_controlID, m_ControlType, m_pProfiler, m_renderTime, m_strDescription, m_vecChildren, m_visTime, SaveToXML(), and text.
Referenced by CGUIControlProfiler::SaveResults(), and SaveToXML().
Member Data Documentation
m_controlID
int CGUIControlProfilerItem::m_controlID
Referenced by CGUIControlProfilerItem(), Reset(), and SaveToXML().
m_ControlType
CGUIControl::GUICONTROLTYPES CGUIControlProfilerItem::m_ControlType
Referenced by CGUIControlProfilerItem(), Reset(), and SaveToXML().
m_i64RenderStart
int64_t CGUIControlProfilerItem::m_i64RenderStart = 0
Referenced by BeginRender(), and EndRender().
m_i64VisStart
int64_t CGUIControlProfilerItem::m_i64VisStart = 0
Referenced by BeginVisibility(), and EndVisibility().
m_pControl
CGUIControl* CGUIControlProfilerItem::m_pControl
Referenced by CGUIControlProfilerItem(), CGUIControlProfiler::FindOrAddControl(), FindOrAddControl(), and Reset().
m_pParent
CGUIControlProfilerItem* CGUIControlProfilerItem::m_pParent
Referenced by CGUIControlProfiler::FindOrAddControl().
m_pProfiler
CGUIControlProfiler* CGUIControlProfilerItem::m_pProfiler
Referenced by AddControl(), EndRender(), EndVisibility(), Reset(), and SaveToXML().
m_renderTime
unsigned int CGUIControlProfilerItem::m_renderTime = 0
Referenced by CGUIControlProfiler::EndFrame(), EndRender(), GetTotalTime(), Reset(), and SaveToXML().
m_strDescription
std::string CGUIControlProfilerItem::m_strDescription
Referenced by CGUIControlProfilerItem(), and SaveToXML().
m_vecChildren
std::vector<CGUIControlProfilerItem *> CGUIControlProfilerItem::m_vecChildren
Referenced by AddControl(), CGUIControlProfiler::EndFrame(), FindOrAddControl(), Reset(), and SaveToXML().
m_visTime
unsigned int CGUIControlProfilerItem::m_visTime = 0
Referenced by CGUIControlProfiler::EndFrame(), EndVisibility(), GetTotalTime(), Reset(), and SaveToXML().
The documentation for this class was generated from the following files:
GUIControlProfiler.h
GUIControlProfiler.cpp