Kodi Documentation: LibraryBuiltins.cpp File Reference
LibraryBuiltins.cpp File Reference
#include "LibraryBuiltins.h"
#include "GUIUserMessages.h"
#include "MediaSource.h"
#include "ServiceBroker.h"
#include "dialogs/GUIDialogFileBrowser.h"
#include "dialogs/GUIDialogYesNo.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "guilib/LocalizeStrings.h"
#include "messaging/helpers/DialogHelper.h"
#include "messaging/helpers/DialogOKHelper.h"
#include "music/MusicLibraryQueue.h"
#include "music/infoscanner/MusicInfoScanner.h"
#include "settings/LibExportSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "storage/MediaManager.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include "video/VideoDatabase.h"
#include "video/VideoLibraryQueue.h"
Functions
static int CleanLibrary (const std::vector< std::string > &params)
Clean a library.
static int ExportLibrary (const std::vector< std::string > &params)
Export a library.
static int ExportLibrary2 (const std::vector< std::string > &params)
Export a library with extended parameters Avoiding breaking change to original ExportLibrary routine parameters.
static int UpdateLibrary (const std::vector< std::string > &params)
Update a library.
static int SearchVideoLibrary (const std::vector< std::string > &params)
Open a video library search.
Function Documentation
CleanLibrary()
static int CleanLibrary (const std::vector< std::string > & params) static
Clean a library.
Parameters
params The parameters.
params[0] = "video" or "music".
References CMusicLibraryQueue::CleanLibrary(), CVideoLibraryQueue::CleanLibrary(), CVideoLibraryQueue::CleanLibraryModal(), KODI::UTILS::StringUtils::EqualsNoCase(), CVideoDatabase::GetContentForPath(), CMusicLibraryQueue::GetInstance(), CVideoLibraryQueue::GetInstance(), CVideoDatabase::GetPathId(), CVideoDatabase::GetPaths(), CVideoDatabase::GetSubPaths(), CLog::Log(), LOGERROR, CVideoDatabase::Open(), and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by CLibraryBuiltins::GetOperations().
ExportLibrary()
static int ExportLibrary (const std::vector< std::string > & params) static
Export a library.
Parameters
params The parameters.
params[0] = "video" or "music". params[1] = "true" to export to separate files (optional). params[2] = "true" to export thumbs (optional) or the file path for export to singlefile. params[3] = "true" to overwrite existing files (optional). params[4] = "true" to export actor thumbs (optional).
References CDatabase::Close(), ELIBEXPORT_TOLIBRARYFOLDER, KODI::UTILS::StringUtils::EqualsNoCase(), CMusicLibraryQueue::ExportLibrary(), CVideoDatabase::ExportToXML(), g_localizeStrings, CLocalizeStrings::Get(), CMusicLibraryQueue::GetInstance(), CMediaManager::GetLocalDrives(), CServiceBroker::GetMediaManager(), CMediaManager::GetNetworkLocations(), CMediaManager::GetRemovableDrives(), CServiceBroker::GetSettingsComponent(), CLibExportSettings::m_artwork, CLibExportSettings::m_overwrite, CLibExportSettings::m_strPath, CVideoDatabase::Open(), CLibExportSettings::SetExportType(), CSettings::SETTING_VIDEOLIBRARY_MOVIESETSFOLDER, CGUIDialogFileBrowser::ShowAndGetDirectory(), and KODI::MESSAGING::HELPERS::ShowYesNoDialogText().
Referenced by CLibraryBuiltins::GetOperations().
ExportLibrary2()
static int ExportLibrary2 (const std::vector< std::string > & params) static
Export a library with extended parameters Avoiding breaking change to original ExportLibrary routine parameters.
Parameters
params The parameters.
params[0] = "video" or "music". params[1] = export type "singlefile", "separate", or "library". params[2] = path of destination folder. params[3,...] = "unscraped" to include unscraped items params[3,...] = "overwrite" to overwrite existing files. params[3,...] = "artwork" to include images such as thumbs and fanart. params[3,...] = "skipnfo" to not include nfo files (just art). params[3,...] = "ablums" to include albums. params[3,...] = "albumartists" to include album artists. params[3,...] = "songartists" to include song artists. params[3,...] = "otherartists" to include other artists.
References CLibExportSettings::AddItem(), CLibExportSettings::ClearItems(), CDatabase::Close(), ELIBEXPORT_ACTORTHUMBS, ELIBEXPORT_ALBUMARTISTS, ELIBEXPORT_ALBUMS, ELIBEXPORT_OTHERARTISTS, ELIBEXPORT_SEPARATEFILES, ELIBEXPORT_SINGLEFILE, ELIBEXPORT_SONGARTISTS, ELIBEXPORT_TOLIBRARYFOLDER, KODI::UTILS::StringUtils::EqualsNoCase(), CMusicLibraryQueue::ExportLibrary(), CVideoDatabase::ExportToXML(), CMusicLibraryQueue::GetInstance(), CLibExportSettings::IsItemExported(), CLibExportSettings::IsSingleFile(), CLibExportSettings::m_artwork, CLibExportSettings::m_overwrite, CLibExportSettings::m_skipnfo, CLibExportSettings::m_strPath, CLibExportSettings::m_unscraped, CVideoDatabase::Open(), and CLibExportSettings::SetExportType().
Referenced by CLibraryBuiltins::GetOperations().
SearchVideoLibrary()
static int SearchVideoLibrary (const std::vector< std::string > & params) static
Open a video library search.
Parameters
params (ignored)
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_SEARCH, CGUIWindowManager::SendMessage(), and WINDOW_VIDEO_NAV.
Referenced by CLibraryBuiltins::GetOperations().
UpdateLibrary()
static int UpdateLibrary (const std::vector< std::string > & params) static
Update a library.
Parameters
params The parameters.
params[0] = "video" or "music". params[1] = "true" to suppress dialogs (optional).
References KODI::UTILS::StringUtils::EqualsNoCase(), CMusicLibraryQueue::GetInstance(), CVideoLibraryQueue::GetInstance(), CVideoLibraryQueue::IsScanningLibrary(), MUSIC_INFO::CMusicInfoScanner::SCAN_NORMAL, CVideoLibraryQueue::ScanLibrary(), CMusicLibraryQueue::ScanLibrary(), CMusicLibraryQueue::StopLibraryScanning(), and CVideoLibraryQueue::StopLibraryScanning().
Referenced by CLibraryBuiltins::GetOperations().