Kodi Documentation: CComponentContainer< BaseType > Class Template Reference
CComponentContainer< BaseType > Class Template Reference
A generic container for components.
#include <ComponentContainer.h>
Public Member Functions
template<class T >
std::shared_ptr< T > GetComponent ()
Obtain a component.
template<class T >
std::shared_ptr< const T > GetComponent () const
Obtain a component.
std::size_t size () const
Returns number of registered components.
Protected Member Functions
void RegisterComponent (const std::shared_ptr< BaseType > &component)
Register a new component instance.
void DeregisterComponent (const std::type_info &typeInfo)
Deregister a component.
Private Attributes
CCriticalSection m_critSection
Critical section for map updates.
std::unordered_map< std::type_index, std::shared_ptr< BaseType > > m_components
Map of components.
Detailed Description
template<class BaseType>
class CComponentContainer< BaseType >
A generic container for components.
A component has to be derived from the BaseType. Only a single instance of each derived type can be registered. Intended use is through inheritance.
Member Function Documentation
DeregisterComponent()
template<class BaseType > void CComponentContainer< BaseType >::DeregisterComponent (const std::type_info & typeInfo) inline protected
Deregister a component.
References CComponentContainer< BaseType >::m_components, and CComponentContainer< BaseType >::m_critSection.
Referenced by CApplication::~CApplication().
GetComponent() [1/2]
template<class BaseType > template<class T > std::shared_ptr< T > CComponentContainer< BaseType >::GetComponent () inline
Obtain a component.
Referenced by CAppInboundProtocol::HandleEvents(), and TEST().
GetComponent() [2/2]
template<class BaseType > template<class T > std::shared_ptr< const T > CComponentContainer< BaseType >::GetComponent () const inline
Obtain a component.
References CComponentContainer< BaseType >::m_components, and CComponentContainer< BaseType >::m_critSection.
RegisterComponent()
template<class BaseType > void CComponentContainer< BaseType >::RegisterComponent (const std::shared_ptr< BaseType > & component) inline protected
Register a new component instance.
References CComponentContainer< BaseType >::m_components, and CComponentContainer< BaseType >::m_critSection.
Referenced by CApplication::CApplication(), and TEST().
size()
template<class BaseType > std::size_t CComponentContainer< BaseType >::size () const inline
Returns number of registered components.
References CComponentContainer< BaseType >::m_components.
Referenced by CApplication::PlayFile(), CApplication::ProcessAndStartPlaylist(), and TEST().
Member Data Documentation
m_components
template<class BaseType > std::unordered_map<std::type_index, std::shared_ptr<BaseType> > CComponentContainer< BaseType >::m_components private
Map of components.
Referenced by CComponentContainer< BaseType >::DeregisterComponent(), CComponentContainer< BaseType >::GetComponent(), CComponentContainer< BaseType >::RegisterComponent(), and CComponentContainer< BaseType >::size().
m_critSection
template<class BaseType > CCriticalSection CComponentContainer< BaseType >::m_critSection mutable private
Critical section for map updates.
Referenced by CComponentContainer< BaseType >::DeregisterComponent(), CComponentContainer< BaseType >::GetComponent(), and CComponentContainer< BaseType >::RegisterComponent().
The documentation for this class was generated from the following files:
ServiceBroker.h
ComponentContainer.h