Kodi Documentation: KODI::WINDOWING::GBM::CWinSystemGbmEGLContext Class Reference
KODI::WINDOWING::GBM::CWinSystemGbmEGLContext Class Reference abstract
#include <WinSystemGbmEGLContext.h>
Classes
struct delete_CVaapiProxy
Public Member Functions
~CWinSystemGbmEGLContext () override=default
bool DestroyWindowSystem () override
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override
bool DestroyWindow () override
bool BindTextureUploadContext () override
Binds a shared context to the current thread, in order to upload textures asynchronously.
bool UnbindTextureUploadContext () override
Unbinds the shared context.
bool HasContext () override
Checks if a graphics context is already bound to the current thread.
Public Member Functions inherited from KODI::WINDOWING::LINUX::CWinSystemEGL
CWinSystemEGL (EGLenum platform, std::string const &platformExtension)
~CWinSystemEGL ()=default
EGLDisplay GetEGLDisplay () const
EGLSurface GetEGLSurface () const
EGLContext GetEGLContext () const
EGLConfig GetEGLConfig () const
Public Member Functions inherited from KODI::WINDOWING::GBM::CWinSystemGbm
CWinSystemGbm ()
~CWinSystemGbm () override
const std::string GetName () override
bool InitWindowSystem () override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
bool DisplayHardwareScalingEnabled () override
void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo) override
void FlipPage (bool rendered, bool videoLayer, bool async)
bool CanDoWindowed () override
void UpdateResolutions () override
bool UseLimitedColor () override
bool Hide () override
bool Show (bool raise=true) override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
bool SetHDR (const VideoPicture *videoPicture) override
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
bool IsHDRDisplay () override
CHDRCapabilities GetDisplayHDRCapabilities () const override
std::shared_ptr< CVideoLayerBridge > GetVideoLayerBridge () const
void RegisterVideoLayerBridge (std::shared_ptr< CVideoLayerBridge > bridge)
CGBMUtils::CGBMDevice & GetGBMDevice () const
std::shared_ptr< CDRMUtils > GetDrm () const
std::vector< std::string > GetConnectedOutputs () override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual CRenderSystemBase * GetRenderSystem ()
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual void FinishWindowResize (int newWidth, int newHeight)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppFocusChange (bool bGaining)
virtual void NotifyAppActiveChange (bool bActivated)
virtual void ShowOSMouse (bool show)
virtual bool HasCursor ()
virtual bool HasInertialGestures ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual float GetDisplayLatency ()
Get average display latency.
virtual float GetFrameLatencyAdjustment ()
Get time that should be subtracted from the display latency for this frame in milliseconds.
virtual bool Minimize ()
virtual bool Restore ()
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
virtual std::string GetClipboardText (void)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual bool MessagePump ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual float GetGuiSdrPeakLuminance () const
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
Protected Member Functions
CWinSystemGbmEGLContext (EGLenum platform, std::string const &platformExtension)
bool InitWindowSystemEGL (EGLint renderableType, EGLint apiType)
virtual bool CreateContext ()=0
Protected Member Functions inherited from KODI::WINDOWING::GBM::CWinSystemGbm
void OnLostDevice ()
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
virtual std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl ()
Protected Attributes
std::unique_ptr< KODI::UTILS::EGL::CEGLFence > m_eglFence
std::unique_ptr< CVaapiProxy, delete_CVaapiProxy > m_vaapiProxy
Protected Attributes inherited from KODI::WINDOWING::LINUX::CWinSystemEGL
CEGLContextUtils m_eglContext
Protected Attributes inherited from KODI::WINDOWING::GBM::CWinSystemGbm
std::shared_ptr< CDRMUtils > m_DRM
std::unique_ptr< CGBMUtils > m_GBM
std::shared_ptr< CVideoLayerBridge > m_videoLayerBridge
CCriticalSection m_resourceSection
std::vector< IDispResource * > m_resources
bool m_dispReset = false
XbmcThreads::EndTime m_dispResetTimer
std::unique_ptr< CLibInputHandler > m_libinput
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Additional Inherited Members
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Constructor & Destructor Documentation
~CWinSystemGbmEGLContext()
KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::~CWinSystemGbmEGLContext () override default
CWinSystemGbmEGLContext()
KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CWinSystemGbmEGLContext (EGLenum platform, std::string const & platformExtension) inline protected
Member Function Documentation
BindTextureUploadContext()
bool CWinSystemGbmEGLContext::BindTextureUploadContext () override virtual
Binds a shared context to the current thread, in order to upload textures asynchronously.
Returns
Return true if a texture upload context exists and the binding succeeds.
Reimplemented from CWinSystemBase.
References CEGLContextUtils::BindTextureUploadContext(), and KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext.
CreateContext()
virtual bool KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateContext () protected pure virtual
Implemented in KODI::WINDOWING::GBM::CWinSystemGbmGLContext, and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext.
Referenced by InitWindowSystemEGL().
CreateNewWindow()
bool CWinSystemGbmEGLContext::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) override virtual
Implements CWinSystemBase.
References CEGLContextUtils::BindContext(), CEGLContextUtils::CreatePlatformSurface(), DestroyWindow(), RESOLUTION_INFO::fRefreshRate, CEGLContextUtils::GetConfigAttrib(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, CLog::Log(), LOGDEBUG, LOGERROR, CWinSystemBase::m_bFullScreen, KODI::WINDOWING::GBM::CWinSystemGbm::m_DRM, KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext, CWinSystemBase::m_fRefreshRate, KODI::WINDOWING::GBM::CWinSystemGbm::m_GBM, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, and KODI::WINDOWING::GBM::CWinSystemGbm::OnLostDevice().
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::SetFullScreen(), and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::SetFullScreen().
DestroyWindow()
bool CWinSystemGbmEGLContext::DestroyWindow () override virtual
Reimplemented from CWinSystemBase.
References CEGLContextUtils::DestroySurface(), CLog::Log(), LOGDEBUG, and KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext.
Referenced by CreateNewWindow().
DestroyWindowSystem()
bool CWinSystemGbmEGLContext::DestroyWindowSystem () override virtual
Reimplemented from KODI::WINDOWING::GBM::CWinSystemGbm.
References CDVDFactoryCodec::ClearHWAccels(), VIDEOPLAYER::CRendererFactory::ClearRenderer(), CEGLContextUtils::Destroy(), KODI::WINDOWING::GBM::CWinSystemGbm::DestroyWindowSystem(), and KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext.
HasContext()
bool CWinSystemGbmEGLContext::HasContext () override virtual
Checks if a graphics context is already bound to the current thread.
Returns
Return true if so.
Reimplemented from CWinSystemBase.
References CEGLContextUtils::HasContext(), and KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext.
InitWindowSystemEGL()
bool CWinSystemGbmEGLContext::InitWindowSystemEGL (EGLint renderableType, EGLint apiType) protected
Inheriting classes should override InitWindowSystem() without parameters and call this function there with appropriate parameters
References CEGLContextUtils::ChooseConfig(), CreateContext(), CEGLContextUtils::CreatePlatformDisplay(), KODI::WINDOWING::GBM::CDRMUtils::FourCCWithAlpha(), KODI::WINDOWING::GBM::CDRMUtils::FourCCWithoutAlpha(), CEGLContextUtils::GetEGLDisplay(), CEGLUtils::HasExtension(), CEGLContextUtils::InitializeDisplay(), KODI::WINDOWING::GBM::CWinSystemGbm::InitWindowSystem(), CLog::Log(), LOGWARNING, KODI::WINDOWING::GBM::CWinSystemGbm::m_DRM, KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext, m_eglFence, and KODI::WINDOWING::GBM::CWinSystemGbm::m_GBM.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem().
UnbindTextureUploadContext()
bool CWinSystemGbmEGLContext::UnbindTextureUploadContext () override virtual
Unbinds the shared context.
Returns
Return true if the texture upload context has been unbound.
Reimplemented from CWinSystemBase.
References KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext, and CEGLContextUtils::UnbindTextureUploadContext().
Member Data Documentation
m_eglFence
std::unique_ptr<KODI::UTILS::EGL::CEGLFence> KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::m_eglFence protected
Referenced by InitWindowSystemEGL(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender().
m_vaapiProxy
std::unique_ptr<CVaapiProxy, delete_CVaapiProxy> KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::m_vaapiProxy protected
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem().
The documentation for this class was generated from the following files:
WinSystemGbmEGLContext.h
WinSystemGbmEGLContext.cpp