Kodi Documentation: CMatrixGLStack Class Reference
CMatrixGLStack Class Reference
#include <MatrixGL.h>
Public Member Functions
void Push ()
void Clear ()
void Pop ()
void Load ()
void PopLoad ()
CMatrixGL & Get ()
CMatrixGL * operator-> ()
Private Attributes
std::stack< CMatrixGL > m_stack
CMatrixGL m_current
Member Function Documentation
Clear()
void CMatrixGLStack::Clear () inline
References m_stack.
Referenced by CRenderSystemGL::ResetRenderSystem(), and CRenderSystemGLES::ResetRenderSystem().
Get()
CMatrixGL & CMatrixGLStack::Get () inline
References m_current.
Referenced by _VerifyGLState(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGLShader::OnEnabled(), CGLESShader::OnEnabled(), CRenderSystemGL::Project(), CRenderSystemGLES::Project(), OVERLAY::COverlayGlyphGL::Render(), OVERLAY::COverlayGlyphGLES::Render(), CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGLES::RenderFromFBO(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGLES::RenderSinglePass(), CLinuxRendererGL::RenderSinglePass(), CLinuxRendererGLES::RenderToFBO(), and CLinuxRendererGL::RenderToFBO().
Load()
void CMatrixGLStack::Load ()
Referenced by PopLoad(), OVERLAY::COverlayGlyphGL::Render(), OVERLAY::COverlayGlyphGLES::Render(), CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), CLinuxRendererGLES::RenderToFBO(), CLinuxRendererGL::RenderToFBO(), CRenderSystemGL::ResetRenderSystem(), CRenderSystemGLES::ResetRenderSystem(), CRenderSystemGL::SetCameraPosition(), and CRenderSystemGLES::SetCameraPosition().
operator->()
CMatrixGL * CMatrixGLStack::operator-> () inline
References m_current.
Pop()
void CMatrixGLStack::Pop () inline
References m_current, and m_stack.
Referenced by CGUIFontTTFGLES::LastEnd(), and PopLoad().
PopLoad()
void CMatrixGLStack::PopLoad () inline
References Load(), and Pop().
Referenced by CRenderSystemGL::ApplyStateBlock(), CRenderSystemGLES::ApplyStateBlock(), OVERLAY::COverlayGlyphGL::Render(), OVERLAY::COverlayGlyphGLES::Render(), CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), CLinuxRendererGLES::RenderToFBO(), and CLinuxRendererGL::RenderToFBO().
Push()
void CMatrixGLStack::Push () inline
References m_current, and m_stack.
Referenced by CRenderSystemGL::CaptureStateBlock(), CRenderSystemGLES::CaptureStateBlock(), OVERLAY::COverlayGlyphGL::Render(), OVERLAY::COverlayGlyphGLES::Render(), CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), CLinuxRendererGLES::RenderToFBO(), and CLinuxRendererGL::RenderToFBO().
Member Data Documentation
m_current
CMatrixGL CMatrixGLStack::m_current private
Referenced by Get(), operator->(), Pop(), and Push().
m_stack
std::stack<CMatrixGL> CMatrixGLStack::m_stack private
Referenced by Clear(), Pop(), and Push().
The documentation for this class was generated from the following files:
MatrixGL.h
MatrixGL.cpp