Kodi Documentation: Win32DllLoader Class Reference
Win32DllLoader Class Reference
#include <Win32DllLoader.h>
Classes
class Import
Public Member Functions
Win32DllLoader (const std::string &dll, bool isSystemDll)
~Win32DllLoader ()
virtual bool Load ()
virtual void Unload ()
virtual int ResolveExport (const char *symbol, void **ptr, bool logging=true)
virtual bool IsSystemDll ()
virtual HMODULE GetHModule ()
virtual bool HasSymbols ()
Public Member Functions inherited from LibraryLoader
LibraryLoader (const std::string &libraryFile)
virtual ~LibraryLoader ()
virtual int ResolveOrdinal (unsigned long ordinal, void **ptr)
const char * GetName () const
const char * GetFileName () const
const char * GetPath () const
int IncrRef ()
int DecrRef ()
int GetRef ()
Private Member Functions
void OverrideImports (const std::string &dll)
void RestoreImports ()
bool NeedsHooking (const char *dllName)
Static Private Member Functions
static bool ResolveImport (const char *dllName, const char *functionName, void **fixup)
static bool ResolveOrdinal (const char *dllName, unsigned long ordinal, void **fixup)
Private Attributes
HMODULE m_dllHandle
bool bIsSystemDll
std::vector< Import > m_overriddenImports
std::vector< HMODULE > m_referencedDlls
Constructor & Destructor Documentation
Win32DllLoader()
Win32DllLoader::Win32DllLoader (const std::string & dll, bool isSystemDll)
References m_dllHandle, and DllLoaderContainer::RegisterDll().
~Win32DllLoader()
Win32DllLoader::~Win32DllLoader ()
References m_dllHandle, Unload(), and DllLoaderContainer::UnRegisterDll().
Member Function Documentation
GetHModule()
HMODULE Win32DllLoader::GetHModule () virtual
Implements LibraryLoader.
References m_dllHandle.
HasSymbols()
bool Win32DllLoader::HasSymbols () virtual
Implements LibraryLoader.
IsSystemDll()
bool Win32DllLoader::IsSystemDll () virtual
Implements LibraryLoader.
References bIsSystemDll.
Load()
bool Win32DllLoader::Load () virtual
Implements LibraryLoader.
References LibraryLoader::GetFileName(), GetLastError(), LOAD_WITH_ALTERED_SEARCH_PATH, CLog::Log(), LOGERROR, m_dllHandle, NeedsHooking(), OverrideImports(), and CSpecialProtocol::TranslatePath().
Referenced by ResolveExport().
NeedsHooking()
bool Win32DllLoader::NeedsHooking (const char * dllName) private
References LibraryLoader::GetHModule(), DllLoaderContainer::GetModule(), and m_referencedDlls.
Referenced by Load(), and OverrideImports().
OverrideImports()
void Win32DllLoader::OverrideImports (const std::string & dll) private
References dllLoadLibraryA(), CLog::Log(), LOGERROR, m_dllHandle, m_overriddenImports, m_referencedDlls, NeedsHooking(), ResolveImport(), ResolveOrdinal(), Win32DllLoader::Import::table, KODI::PLATFORM::WINDOWS::ToW(), and CSpecialProtocol::TranslatePath().
Referenced by Load().
ResolveExport()
int Win32DllLoader::ResolveExport (const char * symbol, void ** ptr, bool logging = true) virtual
Implements LibraryLoader.
References f, LibraryLoader::GetName(), Load(), CLog::Log(), LOGWARNING, and m_dllHandle.
ResolveImport()
bool Win32DllLoader::ResolveImport (const char * dllName, const char * functionName, void ** fixup) static private
References FunctionNeedsWrapping().
Referenced by OverrideImports().
ResolveOrdinal()
bool Win32DllLoader::ResolveOrdinal (const char * dllName, unsigned long ordinal, void ** fixup) static private
References win32_exports.
Referenced by OverrideImports().
RestoreImports()
void Win32DllLoader::RestoreImports () private
References dllFreeLibrary(), m_overriddenImports, m_referencedDlls, and table.
Referenced by Unload().
Unload()
void Win32DllLoader::Unload () virtual
Implements LibraryLoader.
References LibraryLoader::GetName(), CLog::Log(), LOGERROR, m_dllHandle, and RestoreImports().
Referenced by ~Win32DllLoader().
Member Data Documentation
bIsSystemDll
bool Win32DllLoader::bIsSystemDll private
Referenced by IsSystemDll().
m_dllHandle
HMODULE Win32DllLoader::m_dllHandle private
Referenced by GetHModule(), Load(), OverrideImports(), ResolveExport(), Unload(), Win32DllLoader(), and ~Win32DllLoader().
m_overriddenImports
std::vector<Import> Win32DllLoader::m_overriddenImports private
Referenced by OverrideImports(), and RestoreImports().
m_referencedDlls
std::vector<HMODULE> Win32DllLoader::m_referencedDlls private
Referenced by NeedsHooking(), OverrideImports(), and RestoreImports().
The documentation for this class was generated from the following files:
Win32DllLoader.h
Win32DllLoader.cpp