Kodi Documentation: CYUV2RGBShader Class Reference
CYUV2RGBShader Class Reference
#include <WinVideoFilter.h>
Classes
struct Vertex
Public Member Functions
CYUV2RGBShader ()=default
~CYUV2RGBShader ()=default
bool Create (AVPixelFormat fmt, AVColorPrimaries dstPrimaries, AVColorPrimaries srcPrimaries, const std::shared_ptr< COutputShader > &pOutShader=nullptr)
void Render (CRect sourceRect, CPoint dest[], CRenderBuffer *videoBuffer, CD3DTexture &target)
void SetParams (float contrast, float black, bool limited)
void SetColParams (AVColorSpace colSpace, int bits, bool limited, int texBits)
Protected Member Functions
void PrepareParameters (CRenderBuffer *videoBuffer, CRect sourceRect, CPoint dest[])
void SetShaderParameters (CRenderBuffer *videoBuffer)
Protected Member Functions inherited from CWinShader
CWinShader ()=default
virtual ~CWinShader ()=default
virtual bool CreateVertexBuffer (unsigned int vertCount, unsigned int vertSize)
virtual bool LockVertexBuffer (void **data)
virtual bool UnlockVertexBuffer ()
virtual bool LoadEffect (const std::string &filename, DefinesMap *defines)
virtual bool Execute (const std::vector< CD3DTexture * > &targets, unsigned int vertexIndexStep)
virtual void SetStepParams (unsigned stepIndex)
virtual bool CreateInputLayout (D3D11_INPUT_ELEMENT_DESC *layout, unsigned numElements)
Private Attributes
unsigned int m_sourceWidth = 0
unsigned int m_sourceHeight = 0
CRect m_sourceRect = {}
CPoint m_dest [4] = {}
AVPixelFormat m_format = AV_PIX_FMT_NONE
std::array< float, 2 > m_texSteps = {}
std::shared_ptr< COutputShader > m_pOutShader = nullptr
CConvertMatrix m_convMatrix
bool m_colorConversion {false}
Additional Inherited Members
Protected Attributes inherited from CWinShader
CD3DEffect m_effect
CD3DTexture * m_target = nullptr
Constructor & Destructor Documentation
CYUV2RGBShader()
CYUV2RGBShader::CYUV2RGBShader () explicit default
~CYUV2RGBShader()
CYUV2RGBShader::~CYUV2RGBShader () default
Member Function Documentation
Create()
bool CYUV2RGBShader::Create (AVPixelFormat fmt, AVColorPrimaries dstPrimaries, AVColorPrimaries srcPrimaries, const std::shared_ptr< COutputShader > & pOutShader = nullptr)
References CWinShader::CreateInputLayout(), CWinShader::CreateVertexBuffer(), CWinShader::LoadEffect(), LOGERROR, m_colorConversion, m_convMatrix, m_format, m_pOutShader, CConvertMatrix::SetDestinationColorPrimaries(), and CConvertMatrix::SetSourceColorPrimaries().
PrepareParameters()
void CYUV2RGBShader::PrepareParameters (CRenderBuffer * videoBuffer, CRect sourceRect, CPoint dest[]) protected
References CRenderBuffer::GetHeight(), CRenderBuffer::GetWidth(), CWinShader::LockVertexBuffer(), m_dest, m_format, m_sourceHeight, m_sourceRect, m_sourceWidth, m_texSteps, CYUV2RGBShader::Vertex::tu, CYUV2RGBShader::Vertex::tu2, CYUV2RGBShader::Vertex::tv, CYUV2RGBShader::Vertex::tv2, CWinShader::UnlockVertexBuffer(), CYUV2RGBShader::Vertex::x, CPointGen< T >::x, CRectGen< T >::x1, CRectGen< T >::x2, CYUV2RGBShader::Vertex::y, CPointGen< T >::y, CRectGen< T >::y1, CRectGen< T >::y2, and CYUV2RGBShader::Vertex::z.
Referenced by Render().
Render()
void CYUV2RGBShader::Render (CRect sourceRect, CPoint dest[], CRenderBuffer * videoBuffer, CD3DTexture & target)
References CWinShader::Execute(), PrepareParameters(), and SetShaderParameters().
SetColParams()
void CYUV2RGBShader::SetColParams (AVColorSpace colSpace, int bits, bool limited, int texBits)
References m_convMatrix, m_sourceHeight, m_sourceWidth, CConvertMatrix::SetSourceBitDepth(), CConvertMatrix::SetSourceColorSpace(), CConvertMatrix::SetSourceLimitedRange(), and CConvertMatrix::SetSourceTextureBitDepth().
SetParams()
void CYUV2RGBShader::SetParams (float contrast, float black, bool limited)
References m_convMatrix, CConvertMatrix::SetDestinationBlack(), CConvertMatrix::SetDestinationContrast(), and CConvertMatrix::SetDestinationLimitedRange().
SetShaderParameters()
void CYUV2RGBShader::SetShaderParameters (CRenderBuffer * videoBuffer) protected
References DX::DeviceResources::Get(), CConvertMatrix::GetGammaDst(), CConvertMatrix::GetGammaSrc(), CConvertMatrix::GetPrimMat(), CRenderBuffer::GetView(), CRenderBuffer::GetViewCount(), CConvertMatrix::GetYuvMat(), m_colorConversion, m_convMatrix, CWinShader::m_effect, m_pOutShader, m_sourceHeight, m_sourceWidth, m_texSteps, CD3DEffect::SetFloatArray(), CD3DEffect::SetMatrix(), CD3DEffect::SetResources(), CD3DEffect::SetScalar(), CD3DEffect::SetTechnique(), and CMatrix< Order >::ToRaw().
Referenced by Render().
Member Data Documentation
m_colorConversion
bool CYUV2RGBShader::m_colorConversion {false} private
Referenced by Create(), and SetShaderParameters().
m_convMatrix
CConvertMatrix CYUV2RGBShader::m_convMatrix private
Referenced by Create(), SetColParams(), SetParams(), and SetShaderParameters().
m_dest
CPoint CYUV2RGBShader::m_dest[4] = {} private
Referenced by PrepareParameters().
m_format
AVPixelFormat CYUV2RGBShader::m_format = AV_PIX_FMT_NONE private
Referenced by Create(), and PrepareParameters().
m_pOutShader
std::shared_ptr<COutputShader> CYUV2RGBShader::m_pOutShader = nullptr private
Referenced by Create(), and SetShaderParameters().
m_sourceHeight
unsigned int CYUV2RGBShader::m_sourceHeight = 0 private
Referenced by PrepareParameters(), SetColParams(), and SetShaderParameters().
m_sourceRect
CRect CYUV2RGBShader::m_sourceRect = {} private
Referenced by PrepareParameters().
m_sourceWidth
unsigned int CYUV2RGBShader::m_sourceWidth = 0 private
Referenced by PrepareParameters(), SetColParams(), and SetShaderParameters().
m_texSteps
std::array<float, 2> CYUV2RGBShader::m_texSteps = {} private
Referenced by PrepareParameters(), and SetShaderParameters().
The documentation for this class was generated from the following files:
WinVideoFilter.h
WinVideoFilter.cpp