Kodi Documentation: CSkinTimerManager Class Reference
CSkinTimerManager Class Reference
CSkinTimerManager is the container and manager for Skin timers. Its role is that of checking if the timer boolean conditions are valid, start or stop timers and execute the respective builtin actions linked to the timer lifecycle.
#include <SkinTimerManager.h>
Public Member Functions
CSkinTimerManager (CGUIInfoManager &infoMgr)
Skin timer manager constructor.
CSkinTimerManager ()=delete
~CSkinTimerManager ()=default
Default skin timer manager destructor.
void LoadTimers (const std::string &path)
Loads all the skin timers.
void Stop ()
Stops the manager.
size_t GetTimerCount () const
Gets the total number of timers registered in the manager.
bool TimerExists (const std::string &timer) const
Checks if the timer with name timer exists.
std::unique_ptr< CSkinTimer > GrabTimer (const std::string &timer)
Move a given timer, removing it from the manager.
bool TimerIsRunning (const std::string &timer) const
Checks if the timer with name timer is running.
float GetTimerElapsedSeconds (const std::string &timer) const
Get the elapsed seconds since the timer with name timer was started.
void TimerStart (const std::string &timer) const
Starts/Enables a given skin timer.
void TimerStop (const std::string &timer) const
Stops/Disables a given skin timer.
void Process ()
Run the main manager processing loop.
Private Member Functions
void LoadTimerInternal (const tinyxml2::XMLNode *node)
Loads a specific timer.
Private Attributes
std::map< std::string, std::unique_ptr< CSkinTimer > > m_timers
CGUIInfoManager & m_infoMgr
Detailed Description
CSkinTimerManager is the container and manager for Skin timers. Its role is that of checking if the timer boolean conditions are valid, start or stop timers and execute the respective builtin actions linked to the timer lifecycle.
Note
This component should only be called by the main/rendering thread
See also
Skin_Timers
CSkinTimer
Constructor & Destructor Documentation
CSkinTimerManager() [1/2]
CSkinTimerManager::CSkinTimerManager (CGUIInfoManager & infoMgr)
Skin timer manager constructor.
Parameters
infoMgr reference to the infomanager
CSkinTimerManager() [2/2]
CSkinTimerManager::CSkinTimerManager () delete
~CSkinTimerManager()
CSkinTimerManager::~CSkinTimerManager () default
Default skin timer manager destructor.
Member Function Documentation
GetTimerCount()
size_t CSkinTimerManager::GetTimerCount () const
Gets the total number of timers registered in the manager.
Returns
the timer count
References m_timers.
GetTimerElapsedSeconds()
float CSkinTimerManager::GetTimerElapsedSeconds (const std::string & timer) const
Get the elapsed seconds since the timer with name timer was started.
Parameters
timer the name of the skin timer
Returns
the elapsed time in seconds the given timer is running (0 if not running or if it does not exist)
References LOGERROR, and m_timers.
GrabTimer()
std::unique_ptr< CSkinTimer > CSkinTimerManager::GrabTimer (const std::string & timer)
Move a given timer, removing it from the manager.
Parameters
timer the name of the skin timer
Returns
the timer (moved), nullptr if it doesn't exist
References m_timers.
LoadTimerInternal()
void CSkinTimerManager::LoadTimerInternal (const tinyxml2::XMLNode * node) private
Loads a specific timer.
Note
Called internally from LoadTimers
Parameters
node - the XML representation of a skin timer object
References CGUIAction::Append(), CGUIAction::EnableSendThreadMessageMode(), LOGERROR, LOGWARNING, m_infoMgr, m_timers, node, CGUIInfoManager::Register(), and TimerExists().
Referenced by LoadTimers().
LoadTimers()
void CSkinTimerManager::LoadTimers (const std::string & path)
Loads all the skin timers.
Parameters
path - the path for the skin Timers.xml file
References CXBMCTinyXML2::LoadFile(), LoadTimerInternal(), LOGERROR, LOGWARNING, and root.
Process()
void CSkinTimerManager::Process ()
Run the main manager processing loop.
References m_timers.
Stop()
void CSkinTimerManager::Stop ()
Stops the manager.
References m_infoMgr, m_timers, and CGUIInfoManager::UnRegister().
TimerExists()
bool CSkinTimerManager::TimerExists (const std::string & timer) const
Checks if the timer with name timer exists.
Parameters
timer the name of the skin timer
Returns
true if the given timer exists, false otherwise
References m_timers.
Referenced by LoadTimerInternal().
TimerIsRunning()
bool CSkinTimerManager::TimerIsRunning (const std::string & timer) const
Checks if the timer with name timer is running.
Parameters
timer the name of the skin timer
Returns
true if the given timer exists and is running, false otherwise
References LOGERROR, and m_timers.
TimerStart()
void CSkinTimerManager::TimerStart (const std::string & timer) const
Starts/Enables a given skin timer.
Parameters
timer the name of the skin timer
References LOGERROR, and m_timers.
TimerStop()
void CSkinTimerManager::TimerStop (const std::string & timer) const
Stops/Disables a given skin timer.
Parameters
timer the name of the skin timer
References LOGERROR, and m_timers.
Member Data Documentation
m_infoMgr
CGUIInfoManager& CSkinTimerManager::m_infoMgr private
Referenced by LoadTimerInternal(), and Stop().
m_timers
std::map<std::string, std::unique_ptr<CSkinTimer> > CSkinTimerManager::m_timers private
Container for the skin timers
Referenced by GetTimerCount(), GetTimerElapsedSeconds(), GrabTimer(), LoadTimerInternal(), Process(), Stop(), TimerExists(), TimerIsRunning(), TimerStart(), and TimerStop().
The documentation for this class was generated from the following files:
SkinTimerManager.h
SkinTimerManager.cpp