Kodi Documentation: CWinEventsOSX Class Reference
CWinEventsOSX Class Reference
#include <WinEventsOSX.h>
Public Member Functions
CWinEventsOSX ()
~CWinEventsOSX ()
void MessagePush (XBMC_Event *newEvent)
bool MessagePump ()
size_t GetQueueSize ()
void enableInputEvents ()
void disableInputEvents ()
void signalMouseEntered ()
void signalMouseExited ()
void SendInputEvent (NSEvent *nsEvent)
Public Member Functions inherited from IWinEvents
virtual ~IWinEvents ()=default
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Attributes
std::unique_ptr< CWinEventsOSXImplWrapper > m_eventsImplWrapper
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
virtual void Process ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CWinEventsOSX()
CWinEventsOSX::CWinEventsOSX ()
References CThread::Create(), and m_eventsImplWrapper.
~CWinEventsOSX()
CWinEventsOSX::~CWinEventsOSX ()
References CThread::m_bStop, and CThread::StopThread().
Member Function Documentation
disableInputEvents()
void CWinEventsOSX::disableInputEvents ()
References disableInputEvents(), and m_eventsImplWrapper.
Referenced by disableInputEvents().
enableInputEvents()
void CWinEventsOSX::enableInputEvents ()
References enableInputEvents(), and m_eventsImplWrapper.
Referenced by enableInputEvents().
GetQueueSize()
size_t CWinEventsOSX::GetQueueSize ()
References GetQueueSize(), and m_eventsImplWrapper.
Referenced by GetQueueSize().
MessagePump()
bool CWinEventsOSX::MessagePump () virtual
Implements IWinEvents.
References m_eventsImplWrapper, and MessagePump().
Referenced by MessagePump().
MessagePush()
void CWinEventsOSX::MessagePush (XBMC_Event * newEvent)
References m_eventsImplWrapper, and MessagePush().
Referenced by MessagePush().
SendInputEvent()
void CWinEventsOSX::SendInputEvent (NSEvent * nsEvent)
References m_eventsImplWrapper.
signalMouseEntered()
void CWinEventsOSX::signalMouseEntered ()
References m_eventsImplWrapper, and signalMouseEntered().
Referenced by signalMouseEntered().
signalMouseExited()
void CWinEventsOSX::signalMouseExited ()
References m_eventsImplWrapper, and signalMouseExited().
Referenced by signalMouseExited().
Member Data Documentation
m_eventsImplWrapper
std::unique_ptr<CWinEventsOSXImplWrapper> CWinEventsOSX::m_eventsImplWrapper private
Referenced by CWinEventsOSX(), disableInputEvents(), enableInputEvents(), GetQueueSize(), MessagePump(), MessagePush(), SendInputEvent(), signalMouseEntered(), and signalMouseExited().
The documentation for this class was generated from the following files:
WinEventsOSX.h
WinEventsOSX.mm