Kodi Documentation: Shaders::CGLSLPixelShader Class Reference
Shaders::CGLSLPixelShader Class Reference
#include <Shader.h>
Public Member Functions
void Free () override
bool Compile () override
Public Member Functions inherited from Shaders::CPixelShader
CPixelShader ()=default
~CPixelShader () override
void Free () override
GLuint Handle () override
Public Member Functions inherited from Shaders::CShader
CShader ()=default
virtual ~CShader ()=default
virtual void SetSource (const std::string &src)
virtual bool LoadSource (const std::string &filename, const std::string &prefix="")
virtual bool AppendSource (const std::string &filename)
virtual bool InsertSource (const std::string &filename, const std::string &loc)
bool OK () const
std::string GetName () const
std::string GetSourceWithLineNumbers () const
Additional Inherited Members
Protected Attributes inherited from Shaders::CPixelShader
GLuint m_pixelShader = 0
Protected Attributes inherited from Shaders::CShader
std::string m_source
std::string m_lastLog
std::vector< std::string > m_attr
bool m_compiled = false
Member Function Documentation
Compile()
bool CGLSLPixelShader::Compile () override virtual
Implements Shaders::CShader.
References Free(), GLchar, log(), CLog::Log(), LOG_SIZE, LOGDEBUG, LOGERROR, LOGINFO, Shaders::CShader::m_compiled, Shaders::CShader::m_lastLog, Shaders::CPixelShader::m_pixelShader, and Shaders::CShader::m_source.
Free()
void CGLSLPixelShader::Free () override virtual
Implements Shaders::CShader.
References Shaders::CPixelShader::m_pixelShader.
Referenced by Compile().
The documentation for this class was generated from the following files:
guilib/Shader.h
Shader.cpp