Kodi Documentation: DVDAudioCodecAndroidMediaCodec.cpp File Reference
DVDAudioCodecAndroidMediaCodec.cpp File Reference
#include "DVDAudioCodecAndroidMediaCodec.h"
#include "DVDAudioCodecFFmpeg.h"
#include "DVDAudioCodecPassthrough.h"
#include "DVDCodecs/DVDCodecs.h"
#include "DVDCodecs/DVDFactoryCodec.h"
#include "ServiceBroker.h"
#include "cores/AudioEngine/Interfaces/AE.h"
#include "cores/AudioEngine/Utils/AEUtil.h"
#include "cores/VideoPlayer/Interface/DemuxCrypto.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include <cassert>
#include <memory>
#include <stdexcept>
#include <androidjni/ByteBuffer.h>
#include <androidjni/MediaCodec.h>
#include <androidjni/MediaCodecCryptoInfo.h>
#include <androidjni/MediaCodecInfo.h>
#include <androidjni/MediaCodecList.h>
#include <androidjni/MediaCrypto.h>
#include <androidjni/MediaFormat.h>
#include <androidjni/Surface.h>
#include <androidjni/UUID.h>
Functions
static bool IsDownmixDecoder (const std::string &name)
static bool IsDecoderWhitelisted (const std::string &name)
Variables
static const AEChannel KnownChannels [] = { AE_CH_FL, AE_CH_FR, AE_CH_FC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_CH_BL, AE_CH_BR, AE_CH_BC, AE_CH_BLOC, AE_CH_BROC, AE_CH_NULL }
Function Documentation
IsDecoderWhitelisted()
static bool IsDecoderWhitelisted (const std::string & name) static
References KODI::UTILS::StringUtils::CompareNoCase(), and name.
Referenced by CDVDAudioCodecAndroidMediaCodec::Open().
IsDownmixDecoder()
static bool IsDownmixDecoder (const std::string & name) static
References KODI::UTILS::StringUtils::CompareNoCase(), and name.
Referenced by CDVDAudioCodecAndroidMediaCodec::Open().
Variable Documentation
KnownChannels
const AEChannel KnownChannels[] = { AE_CH_FL, AE_CH_FR, AE_CH_FC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_CH_BL, AE_CH_BR, AE_CH_BC, AE_CH_BLOC, AE_CH_BROC, AE_CH_NULL } static