Kodi Documentation: InfoTagMusic
InfoTagMusic
Python » Library - xbmc
Kodi's music info tag class.
Classes
class XBMCAddon::xbmc::InfoTagMusic
Functions
XBMCAddon::xbmc::InfoTagMusic::InfoTagMusic (const MUSIC_INFO::CMusicInfoTag *tag)
XBMCAddon::xbmc::InfoTagMusic::InfoTagMusic (MUSIC_INFO::CMusicInfoTag *tag, bool offscreen=false)
XBMCAddon::xbmc::InfoTagMusic::InfoTagMusic (...)
Function: xbmc.InfoTagMusic([offscreen])
Create a music info tag.
XBMCAddon::xbmc::InfoTagMusic::~InfoTagMusic () override
XBMCAddon::xbmc::InfoTagMusic::getDbId ()
Function: getDbId()
Get identification number of tag in database.
XBMCAddon::xbmc::InfoTagMusic::getURL ()
Function: getURL()
Returns url of source as string from music info tag.
XBMCAddon::xbmc::InfoTagMusic::getTitle ()
Function: getTitle()
Returns the title from music as string on info tag.
XBMCAddon::xbmc::InfoTagMusic::getMediaType ()
Function: getMediaType()
Get the media type of the music item.
XBMCAddon::xbmc::InfoTagMusic::getArtist ()
Function: getArtist()
Returns the artist from music as string if present.
XBMCAddon::xbmc::InfoTagMusic::getAlbum ()
Function: getAlbum()
Returns the album from music tag as string if present.
XBMCAddon::xbmc::InfoTagMusic::getAlbumArtist ()
Function: getAlbumArtist()
Returns the album artist from music tag as string if present.
XBMCAddon::xbmc::InfoTagMusic::getGenre ()
Function: getGenre()
Returns the genre name from music tag as string if present.
XBMCAddon::xbmc::InfoTagMusic::getGenres ()
Function: getGenres()
Returns the list of genres from music tag if present.
XBMCAddon::xbmc::InfoTagMusic::getDuration ()
Function: getDuration()
Returns the duration of music as integer from info tag.
XBMCAddon::xbmc::InfoTagMusic::getYear ()
Function: getYear()
Returns the year of music as integer from info tag.
XBMCAddon::xbmc::InfoTagMusic::getRating ()
Function: getRating()
Returns the scraped rating as integer.
XBMCAddon::xbmc::InfoTagMusic::getUserRating ()
Function: getUserRating()
Returns the user rating as integer (-1 if not existing)
XBMCAddon::xbmc::InfoTagMusic::getTrack ()
Function: getTrack()
Returns the track number (if present) from music info tag as integer.
XBMCAddon::xbmc::InfoTagMusic::getDisc ()
Function: getDisc()
Returns the disk number (if present) from music info tag as integer.
XBMCAddon::xbmc::InfoTagMusic::getReleaseDate ()
Function: getReleaseDate()
Returns the release date as string from music info tag (if present).
XBMCAddon::xbmc::InfoTagMusic::getListeners ()
Function: getListeners()
Returns the listeners as integer from music info tag.
XBMCAddon::xbmc::InfoTagMusic::getPlayCount ()
Function: getPlayCount()
Returns the number of carried out playbacks.
XBMCAddon::xbmc::InfoTagMusic::getLastPlayed ()
Function: getLastPlayed()
Returns last played time as string from music info tag.
XBMCAddon::xbmc::InfoTagMusic::getLastPlayedAsW3C ()
Function: getLastPlayedAsW3C()
Returns last played time as string in W3C format (YYYY-MM-DDThh:mm:ssTZD).
XBMCAddon::xbmc::InfoTagMusic::getComment ()
Function: getComment()
Returns comment as string from music info tag.
XBMCAddon::xbmc::InfoTagMusic::getLyrics ()
Function: getLyrics()
Returns a string from lyrics.
XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzTrackID ()
Function: getMusicBrainzTrackID()
Returns the MusicBrainz Recording ID from music info tag (if present).
XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzArtistID ()
Function: getMusicBrainzArtistID()
Returns the MusicBrainz Artist IDs from music info tag (if present).
XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzAlbumID ()
Function: getMusicBrainzAlbumID()
Returns the MusicBrainz Release ID from music info tag (if present).
XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzReleaseGroupID ()
Function: getMusicBrainzReleaseGroupID()
Returns the MusicBrainz Release Group ID from music info tag (if present).
XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzAlbumArtistID ()
Function: getMusicBrainzAlbumArtistID()
Returns the MusicBrainz Release Artist IDs from music info tag (if present).
XBMCAddon::xbmc::InfoTagMusic::getSongVideoURL ()
Function: getSongVideoURL()
Returns the URL to a video of the song from the music tag as a string (if present).
XBMCAddon::xbmc::InfoTagMusic::setDbId (...)
Function: setDbId(dbId, type)
Set the database identifier of the music item.
XBMCAddon::xbmc::InfoTagMusic::setURL (...)
Function: setURL(url)
Set the URL of the music item.
XBMCAddon::xbmc::InfoTagMusic::setMediaType (...)
Function: setMediaType(mediaType)
Set the media type of the music item.
XBMCAddon::xbmc::InfoTagMusic::setTrack (...)
Function: setTrack(track)
Set the track number of the song.
XBMCAddon::xbmc::InfoTagMusic::setDisc (...)
Function: setDisc(disc)
Set the disc number of the song.
XBMCAddon::xbmc::InfoTagMusic::setDuration (...)
Function: setDuration(duration)
Set the duration of the song.
XBMCAddon::xbmc::InfoTagMusic::setYear (...)
Function: setYear(year)
Set the year of the music item.
XBMCAddon::xbmc::InfoTagMusic::setReleaseDate (...)
Function: setReleaseDate(releaseDate)
Set the release date of the music item.
XBMCAddon::xbmc::InfoTagMusic::setListeners (...)
Function: setListeners(listeners)
Set the number of listeners of the music item.
XBMCAddon::xbmc::InfoTagMusic::setPlayCount (...)
Function: setPlayCount(playcount)
Set the playcount of the music item.
XBMCAddon::xbmc::InfoTagMusic::setGenres (...)
Function: setGenres(genres)
Set the genres of the music item.
XBMCAddon::xbmc::InfoTagMusic::setAlbum (...)
Function: setAlbum(album)
Set the album of the music item.
XBMCAddon::xbmc::InfoTagMusic::setArtist (...)
Function: setArtist(artist)
Set the artist(s) of the music item.
XBMCAddon::xbmc::InfoTagMusic::setAlbumArtist (...)
Function: setAlbumArtist(albumArtist)
Set the album artist(s) of the music item.
XBMCAddon::xbmc::InfoTagMusic::setTitle (...)
Function: setTitle(title)
Set the title of the music item.
XBMCAddon::xbmc::InfoTagMusic::setRating (...)
Function: setRating(rating)
Set the rating of the music item.
XBMCAddon::xbmc::InfoTagMusic::setUserRating (...)
Function: setUserRating(userrating)
Set the user rating of the music item.
XBMCAddon::xbmc::InfoTagMusic::setLyrics (...)
Function: setLyrics(lyrics)
Set the lyrics of the song.
XBMCAddon::xbmc::InfoTagMusic::setLastPlayed (...)
Function: setLastPlayed(lastPlayed)
Set the last played date of the music item.
XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzTrackID (...)
Function: setMusicBrainzTrackID(musicBrainzTrackID)
Set the MusicBrainz track ID of the song.
XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzArtistID (...)
Function: setMusicBrainzArtistID(musicBrainzArtistID)
Set the MusicBrainz artist IDs of the music item.
XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumID (...)
Function: setMusicBrainzAlbumID(musicBrainzAlbumID)
Set the MusicBrainz album ID of the music item.
XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzReleaseGroupID (...)
Function: setMusicBrainzReleaseGroupID(musicBrainzReleaseGroupID)
Set the MusicBrainz release group ID of the music item.
XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumArtistID (...)
Function: setMusicBrainzAlbumArtistID(musicBrainzAlbumArtistID)
Set the MusicBrainz album artist IDs of the music item.
XBMCAddon::xbmc::InfoTagMusic::setComment (...)
Function: setComment(comment)
Set the comment of the music item.
XBMCAddon::xbmc::InfoTagMusic::setSongVideoURL (...)
Function: setSongVideoURL(songVideoURL)
Set the URL of the song to point to a video.
static void XBMCAddon::xbmc::InfoTagMusic::setDbIdRaw (MUSIC_INFO::CMusicInfoTag *infoTag, int dbId, const String &type)
static void XBMCAddon::xbmc::InfoTagMusic::setURLRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &url)
static void XBMCAddon::xbmc::InfoTagMusic::setMediaTypeRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &mediaType)
static void XBMCAddon::xbmc::InfoTagMusic::setTrackRaw (MUSIC_INFO::CMusicInfoTag *infoTag, int track)
static void XBMCAddon::xbmc::InfoTagMusic::setDiscRaw (MUSIC_INFO::CMusicInfoTag *infoTag, int disc)
static void XBMCAddon::xbmc::InfoTagMusic::setDurationRaw (MUSIC_INFO::CMusicInfoTag *infoTag, int duration)
static void XBMCAddon::xbmc::InfoTagMusic::setYearRaw (MUSIC_INFO::CMusicInfoTag *infoTag, int year)
static void XBMCAddon::xbmc::InfoTagMusic::setReleaseDateRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &releaseDate)
static void XBMCAddon::xbmc::InfoTagMusic::setListenersRaw (MUSIC_INFO::CMusicInfoTag *infoTag, int listeners)
static void XBMCAddon::xbmc::InfoTagMusic::setPlayCountRaw (MUSIC_INFO::CMusicInfoTag *infoTag, int playcount)
static void XBMCAddon::xbmc::InfoTagMusic::setGenresRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const std::vector< String > &genres)
static void XBMCAddon::xbmc::InfoTagMusic::setAlbumRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &album)
static void XBMCAddon::xbmc::InfoTagMusic::setArtistRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &artist)
static void XBMCAddon::xbmc::InfoTagMusic::setAlbumArtistRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &albumArtist)
static void XBMCAddon::xbmc::InfoTagMusic::setTitleRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &title)
static void XBMCAddon::xbmc::InfoTagMusic::setRatingRaw (MUSIC_INFO::CMusicInfoTag *infoTag, float rating)
static void XBMCAddon::xbmc::InfoTagMusic::setUserRatingRaw (MUSIC_INFO::CMusicInfoTag *infoTag, int userrating)
static void XBMCAddon::xbmc::InfoTagMusic::setLyricsRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &lyrics)
static void XBMCAddon::xbmc::InfoTagMusic::setLastPlayedRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &lastPlayed)
static void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzTrackIDRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &musicBrainzTrackID)
static void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzArtistIDRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const std::vector< String > &musicBrainzArtistID)
static void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumIDRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &musicBrainzAlbumID)
static void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzReleaseGroupIDRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &musicBrainzReleaseGroupID)
static void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumArtistIDRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const std::vector< String > &musicBrainzAlbumArtistID)
static void XBMCAddon::xbmc::InfoTagMusic::setCommentRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &comment)
static void XBMCAddon::xbmc::InfoTagMusic::setSongVideoURLRaw (MUSIC_INFO::CMusicInfoTag *infoTag, const String &songVideoURL)
Variables
MUSIC_INFO::CMusicInfoTag * XBMCAddon::xbmc::InfoTagMusic::infoTag
bool XBMCAddon::xbmc::InfoTagMusic::offscreen
bool XBMCAddon::xbmc::InfoTagMusic::owned
Detailed Description
Kodi's music info tag class.
Class: xbmc.InfoTagMusic([offscreen])
Access and / or modify the music metadata of a ListItem.
Example:
...
tag = xbmc.Player().getMusicInfoTag()
title = tag.getTitle()
url   = tag.getURL()
...
Function Documentation
getAlbum()
String XBMCAddon::xbmc::InfoTagMusic::getAlbum ()
Function: getAlbum()
Returns the album from music tag as string if present.
Returns
[string] Music album name
References MUSIC_INFO::CMusicInfoTag::GetAlbum(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getAlbumArtist()
String XBMCAddon::xbmc::InfoTagMusic::getAlbumArtist ()
Function: getAlbumArtist()
Returns the album artist from music tag as string if present.
Returns
[string] Music album artist name
References MUSIC_INFO::CMusicInfoTag::GetAlbumArtistString(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getArtist()
String XBMCAddon::xbmc::InfoTagMusic::getArtist ()
Function: getArtist()
Returns the artist from music as string if present.
Returns
[string] Music artist
References MUSIC_INFO::CMusicInfoTag::GetArtistString(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getComment()
String XBMCAddon::xbmc::InfoTagMusic::getComment ()
Function: getComment()
Returns comment as string from music info tag.
Returns
[string] Comment on tag
References MUSIC_INFO::CMusicInfoTag::GetComment(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getDbId()
int XBMCAddon::xbmc::InfoTagMusic::getDbId ()
Function: getDbId()
Get identification number of tag in database.
Returns
[integer] database id.
v18 Python API changes:
New function added.
References MUSIC_INFO::CMusicInfoTag::GetDatabaseId(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getDisc()
int XBMCAddon::xbmc::InfoTagMusic::getDisc ()
Function: getDisc()
Returns the disk number (if present) from music info tag as integer.
Returns
[integer] Disc number
References MUSIC_INFO::CMusicInfoTag::GetDiscNumber(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getDuration()
int XBMCAddon::xbmc::InfoTagMusic::getDuration ()
Function: getDuration()
Returns the duration of music as integer from info tag.
Returns
[integer] Duration
References MUSIC_INFO::CMusicInfoTag::GetDuration(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getGenre()
String XBMCAddon::xbmc::InfoTagMusic::getGenre ()
Function: getGenre()
Returns the genre name from music tag as string if present.
Returns
[string] Genre name
v20 Python API changes:
Deprecated. Use getGenres() instead.
References MUSIC_INFO::CMusicInfoTag::GetGenre(), CServiceBroker::GetSettingsComponent(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getGenres()
std::vector< String > XBMCAddon::xbmc::InfoTagMusic::getGenres ()
Function: getGenres()
Returns the list of genres from music tag if present.
Returns
[list] List of genres
v20 Python API changes:
New function added.
References MUSIC_INFO::CMusicInfoTag::GetGenre(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getLastPlayed()
String XBMCAddon::xbmc::InfoTagMusic::getLastPlayed ()
Function: getLastPlayed()
Returns last played time as string from music info tag.
Returns
[string] Last played date / time on tag
v20 Python API changes:
Deprecated. Use getLastPlayedAsW3C() instead.
References CDateTime::GetAsLocalizedDate(), MUSIC_INFO::CMusicInfoTag::GetLastPlayed(), XBMCAddon::xbmc::InfoTagMusic::infoTag, CLog::Log(), and LOGWARNING.
getLastPlayedAsW3C()
String XBMCAddon::xbmc::InfoTagMusic::getLastPlayedAsW3C ()
Function: getLastPlayedAsW3C()
Returns last played time as string in W3C format (YYYY-MM-DDThh:mm:ssTZD).
Returns
[string] Last played datetime (W3C)
v20 Python API changes:
New function added.
References CDateTime::GetAsW3CDateTime(), MUSIC_INFO::CMusicInfoTag::GetLastPlayed(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getListeners()
int XBMCAddon::xbmc::InfoTagMusic::getListeners ()
Function: getListeners()
Returns the listeners as integer from music info tag.
Returns
[integer] Listeners
References MUSIC_INFO::CMusicInfoTag::GetListeners(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getLyrics()
String XBMCAddon::xbmc::InfoTagMusic::getLyrics ()
Function: getLyrics()
Returns a string from lyrics.
Returns
[string] Lyrics on tag
References MUSIC_INFO::CMusicInfoTag::GetLyrics(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getMediaType()
String XBMCAddon::xbmc::InfoTagMusic::getMediaType ()
Function: getMediaType()
Get the media type of the music item.
Returns
[string] media type
Available strings about media type for music:
String Description
artist If it is defined as an artist
album If it is defined as an album
song If it is defined as a song
v18 Python API changes:
New function added.
References MUSIC_INFO::CMusicInfoTag::GetType(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getMusicBrainzAlbumArtistID()
std::vector< String > XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzAlbumArtistID ()
Function: getMusicBrainzAlbumArtistID()
Returns the MusicBrainz Release Artist IDs from music info tag (if present).
Returns
[list] MusicBrainz Release Artist IDs
v19 Python API changes:
New function added.
References MUSIC_INFO::CMusicInfoTag::GetMusicBrainzAlbumArtistID(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getMusicBrainzAlbumID()
String XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzAlbumID ()
Function: getMusicBrainzAlbumID()
Returns the MusicBrainz Release ID from music info tag (if present).
Returns
[string] MusicBrainz Release ID
v19 Python API changes:
New function added.
References MUSIC_INFO::CMusicInfoTag::GetMusicBrainzAlbumID(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getMusicBrainzArtistID()
std::vector< String > XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzArtistID ()
Function: getMusicBrainzArtistID()
Returns the MusicBrainz Artist IDs from music info tag (if present).
Returns
[list] MusicBrainz Artist IDs
v19 Python API changes:
New function added.
References MUSIC_INFO::CMusicInfoTag::GetMusicBrainzArtistID(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getMusicBrainzReleaseGroupID()
String XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzReleaseGroupID ()
Function: getMusicBrainzReleaseGroupID()
Returns the MusicBrainz Release Group ID from music info tag (if present).
Returns
[string] MusicBrainz Release Group ID
v19 Python API changes:
New function added.
References MUSIC_INFO::CMusicInfoTag::GetMusicBrainzReleaseGroupID(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getMusicBrainzTrackID()
String XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzTrackID ()
Function: getMusicBrainzTrackID()
Returns the MusicBrainz Recording ID from music info tag (if present).
Returns
[string] MusicBrainz Recording ID
v19 Python API changes:
New function added.
References MUSIC_INFO::CMusicInfoTag::GetMusicBrainzTrackID(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getPlayCount()
int XBMCAddon::xbmc::InfoTagMusic::getPlayCount ()
Function: getPlayCount()
Returns the number of carried out playbacks.
Returns
[integer] Playback count
References MUSIC_INFO::CMusicInfoTag::GetPlayCount(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getRating()
int XBMCAddon::xbmc::InfoTagMusic::getRating ()
Function: getRating()
Returns the scraped rating as integer.
Returns
[integer] Rating
References MUSIC_INFO::CMusicInfoTag::GetRating(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getReleaseDate()
String XBMCAddon::xbmc::InfoTagMusic::getReleaseDate ()
Function: getReleaseDate()
Returns the release date as string from music info tag (if present).
Returns
[string] Release date
References MUSIC_INFO::CMusicInfoTag::GetReleaseDate(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getSongVideoURL()
String XBMCAddon::xbmc::InfoTagMusic::getSongVideoURL ()
Function: getSongVideoURL()
Returns the URL to a video of the song from the music tag as a string (if present).
Returns
[string] URL to a video of the song.
v21 Python API changes:
New function added.
References MUSIC_INFO::CMusicInfoTag::GetSongVideoURL(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getTitle()
String XBMCAddon::xbmc::InfoTagMusic::getTitle ()
Function: getTitle()
Returns the title from music as string on info tag.
Returns
[string] Music title
References MUSIC_INFO::CMusicInfoTag::GetTitle(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getTrack()
int XBMCAddon::xbmc::InfoTagMusic::getTrack ()
Function: getTrack()
Returns the track number (if present) from music info tag as integer.
Returns
[integer] Track number
References MUSIC_INFO::CMusicInfoTag::GetTrackNumber(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getURL()
String XBMCAddon::xbmc::InfoTagMusic::getURL ()
Function: getURL()
Returns url of source as string from music info tag.
Returns
[string] Url of source
References MUSIC_INFO::CMusicInfoTag::GetURL(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getUserRating()
int XBMCAddon::xbmc::InfoTagMusic::getUserRating ()
Function: getUserRating()
Returns the user rating as integer (-1 if not existing)
Returns
[integer] User rating
References MUSIC_INFO::CMusicInfoTag::GetUserrating(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
getYear()
int XBMCAddon::xbmc::InfoTagMusic::getYear ()
Function: getYear()
Returns the year of music as integer from info tag.
Returns
[integer] Year
v20 Python API changes:
New function added.
References MUSIC_INFO::CMusicInfoTag::GetYear(), and XBMCAddon::xbmc::InfoTagMusic::infoTag.
InfoTagMusic() [1/3]
XBMCAddon::xbmc::InfoTagMusic::InfoTagMusic (...)
Function: xbmc.InfoTagMusic([offscreen])
Create a music info tag.
Parameters
offscreen [opt] bool (default False) - if GUI based locks should be avoided. Most of the times listitems are created offscreen and added later to a container for display (e.g. plugins) or they are not even displayed (e.g. python scrapers). In such cases, there is no need to lock the GUI when creating the items (increasing your addon performance). Note however, that if you are creating listitems and managing the container itself (e.g using WindowXML or WindowXMLDialog classes) subsquent modifications to the item will require locking. Thus, in such cases, use the default value (False).
v20 Python API changes:
Added offscreen argument.
Example:
...
musicinfo = xbmc.InfoTagMusic(offscreen=False)
...
InfoTagMusic() [2/3]
XBMCAddon::xbmc::InfoTagMusic::InfoTagMusic (const MUSIC_INFO::CMusicInfoTag * tag) explicit
References XBMCAddon::xbmc::InfoTagMusic::infoTag.
InfoTagMusic() [3/3]
XBMCAddon::xbmc::InfoTagMusic::InfoTagMusic (MUSIC_INFO::CMusicInfoTag * tag, bool offscreen = false) explicit
setAlbum()
void XBMCAddon::xbmc::InfoTagMusic::setAlbum (...)
Function: setAlbum(album)
Set the album of the music item.
Parameters
album string - Album.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setAlbumRaw().
setAlbumArtist()
void XBMCAddon::xbmc::InfoTagMusic::setAlbumArtist (...)
Function: setAlbumArtist(albumArtist)
Set the album artist(s) of the music item.
Parameters
albumArtist string - Album artist(s).
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setAlbumArtistRaw().
setAlbumArtistRaw()
void XBMCAddon::xbmc::InfoTagMusic::setAlbumArtistRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & albumArtist) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetAlbumArtist().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setAlbumArtist().
setAlbumRaw()
void XBMCAddon::xbmc::InfoTagMusic::setAlbumRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & album) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetAlbum().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setAlbum().
setArtist()
void XBMCAddon::xbmc::InfoTagMusic::setArtist (...)
Function: setArtist(artist)
Set the artist(s) of the music item.
Parameters
artist string - Artist(s).
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setArtistRaw().
setArtistRaw()
void XBMCAddon::xbmc::InfoTagMusic::setArtistRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & artist) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetArtist().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setArtist().
setComment()
void XBMCAddon::xbmc::InfoTagMusic::setComment (...)
Function: setComment(comment)
Set the comment of the music item.
Parameters
comment string - Comment.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setCommentRaw().
setCommentRaw()
void XBMCAddon::xbmc::InfoTagMusic::setCommentRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & comment) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetComment().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setComment().
setDbId()
void XBMCAddon::xbmc::InfoTagMusic::setDbId (...)
Function: setDbId(dbId, type)
Set the database identifier of the music item.
Parameters
dbId integer - Database identifier.
type string - Media type of the item.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setDbIdRaw().
setDbIdRaw()
void XBMCAddon::xbmc::InfoTagMusic::setDbIdRaw (MUSIC_INFO::CMusicInfoTag * infoTag, int dbId, const String & type) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetDatabaseId().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setDbId().
setDisc()
void XBMCAddon::xbmc::InfoTagMusic::setDisc (...)
Function: setDisc(disc)
Set the disc number of the song.
Parameters
disc integer - Disc number.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setDiscRaw().
setDiscRaw()
void XBMCAddon::xbmc::InfoTagMusic::setDiscRaw (MUSIC_INFO::CMusicInfoTag * infoTag, int disc) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetDiscNumber().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setDisc().
setDuration()
void XBMCAddon::xbmc::InfoTagMusic::setDuration (...)
Function: setDuration(duration)
Set the duration of the song.
Parameters
duration integer - Duration in seconds.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setDurationRaw().
setDurationRaw()
void XBMCAddon::xbmc::InfoTagMusic::setDurationRaw (MUSIC_INFO::CMusicInfoTag * infoTag, int duration) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetDuration().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setDuration().
setGenres()
void XBMCAddon::xbmc::InfoTagMusic::setGenres (...)
Function: setGenres(genres)
Set the genres of the music item.
Parameters
genres list - Genres.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setGenresRaw().
setGenresRaw()
void XBMCAddon::xbmc::InfoTagMusic::setGenresRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const std::vector< String > & genres) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetGenre().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setGenres().
setLastPlayed()
void XBMCAddon::xbmc::InfoTagMusic::setLastPlayed (...)
Function: setLastPlayed(lastPlayed)
Set the last played date of the music item.
Parameters
lastPlayed string - Last played date (YYYY-MM-DD HH:MM:SS).
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setLastPlayedRaw().
setLastPlayedRaw()
void XBMCAddon::xbmc::InfoTagMusic::setLastPlayedRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & lastPlayed) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetLastPlayed().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setLastPlayed().
setListeners()
void XBMCAddon::xbmc::InfoTagMusic::setListeners (...)
Function: setListeners(listeners)
Set the number of listeners of the music item.
Parameters
listeners integer - Number of listeners.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setListenersRaw().
setListenersRaw()
void XBMCAddon::xbmc::InfoTagMusic::setListenersRaw (MUSIC_INFO::CMusicInfoTag * infoTag, int listeners) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetListeners().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setListeners().
setLyrics()
void XBMCAddon::xbmc::InfoTagMusic::setLyrics (...)
Function: setLyrics(lyrics)
Set the lyrics of the song.
Parameters
lyrics string - Lyrics.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setLyricsRaw().
setLyricsRaw()
void XBMCAddon::xbmc::InfoTagMusic::setLyricsRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & lyrics) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetLyrics().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setLyrics().
setMediaType()
void XBMCAddon::xbmc::InfoTagMusic::setMediaType (...)
Function: setMediaType(mediaType)
Set the media type of the music item.
Parameters
mediaType string - Media type.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setMediaTypeRaw().
setMediaTypeRaw()
void XBMCAddon::xbmc::InfoTagMusic::setMediaTypeRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & mediaType) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetType().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setMediaType().
setMusicBrainzAlbumArtistID()
void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumArtistID (...)
Function: setMusicBrainzAlbumArtistID(musicBrainzAlbumArtistID)
Set the MusicBrainz album artist IDs of the music item.
Parameters
musicBrainzAlbumArtistID list - MusicBrainz album artist IDs.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumArtistIDRaw().
setMusicBrainzAlbumArtistIDRaw()
void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumArtistIDRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const std::vector< String > & musicBrainzAlbumArtistID) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetMusicBrainzAlbumArtistID().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumArtistID().
setMusicBrainzAlbumID()
void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumID (...)
Function: setMusicBrainzAlbumID(musicBrainzAlbumID)
Set the MusicBrainz album ID of the music item.
Parameters
musicBrainzAlbumID string - MusicBrainz album ID.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumIDRaw().
setMusicBrainzAlbumIDRaw()
void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumIDRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & musicBrainzAlbumID) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetMusicBrainzAlbumID().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumID().
setMusicBrainzArtistID()
void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzArtistID (...)
Function: setMusicBrainzArtistID(musicBrainzArtistID)
Set the MusicBrainz artist IDs of the music item.
Parameters
musicBrainzArtistID list - MusicBrainz artist IDs.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzArtistIDRaw().
setMusicBrainzArtistIDRaw()
void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzArtistIDRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const std::vector< String > & musicBrainzArtistID) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetMusicBrainzArtistID().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzArtistID().
setMusicBrainzReleaseGroupID()
void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzReleaseGroupID (...)
Function: setMusicBrainzReleaseGroupID(musicBrainzReleaseGroupID)
Set the MusicBrainz release group ID of the music item.
Parameters
musicBrainzReleaseGroupID string - MusicBrainz release group ID.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzReleaseGroupIDRaw().
setMusicBrainzReleaseGroupIDRaw()
void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzReleaseGroupIDRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & musicBrainzReleaseGroupID) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetMusicBrainzReleaseGroupID().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzReleaseGroupID().
setMusicBrainzTrackID()
void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzTrackID (...)
Function: setMusicBrainzTrackID(musicBrainzTrackID)
Set the MusicBrainz track ID of the song.
Parameters
musicBrainzTrackID string - MusicBrainz track ID.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzTrackIDRaw().
setMusicBrainzTrackIDRaw()
void XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzTrackIDRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & musicBrainzTrackID) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetMusicBrainzTrackID().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzTrackID().
setPlayCount()
void XBMCAddon::xbmc::InfoTagMusic::setPlayCount (...)
Function: setPlayCount(playcount)
Set the playcount of the music item.
Parameters
playcount integer - Playcount.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setPlayCountRaw().
setPlayCountRaw()
void XBMCAddon::xbmc::InfoTagMusic::setPlayCountRaw (MUSIC_INFO::CMusicInfoTag * infoTag, int playcount) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetPlayCount().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setPlayCount().
setRating()
void XBMCAddon::xbmc::InfoTagMusic::setRating (...)
Function: setRating(rating)
Set the rating of the music item.
Parameters
rating float - Rating.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setRatingRaw().
setRatingRaw()
void XBMCAddon::xbmc::InfoTagMusic::setRatingRaw (MUSIC_INFO::CMusicInfoTag * infoTag, float rating) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetRating().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setRating().
setReleaseDate()
void XBMCAddon::xbmc::InfoTagMusic::setReleaseDate (...)
Function: setReleaseDate(releaseDate)
Set the release date of the music item.
Parameters
releaseDate string - Release date in ISO8601 format (YYYY, YYYY-MM or YYYY-MM-DD).
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setReleaseDateRaw().
setReleaseDateRaw()
void XBMCAddon::xbmc::InfoTagMusic::setReleaseDateRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & releaseDate) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetReleaseDate().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setReleaseDate().
setSongVideoURL()
void XBMCAddon::xbmc::InfoTagMusic::setSongVideoURL (...)
Function: setSongVideoURL(songVideoURL)
Set the URL of the song to point to a video.
Parameters
songVideoURL string - URL to a video of the song.
v21 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setSongVideoURLRaw().
setSongVideoURLRaw()
void XBMCAddon::xbmc::InfoTagMusic::setSongVideoURLRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & songVideoURL) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetSongVideoURL().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setSongVideoURL().
setTitle()
void XBMCAddon::xbmc::InfoTagMusic::setTitle (...)
Function: setTitle(title)
Set the title of the music item.
Parameters
title string - Title.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setTitleRaw().
setTitleRaw()
void XBMCAddon::xbmc::InfoTagMusic::setTitleRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & title) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetTitle().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setTitle().
setTrack()
void XBMCAddon::xbmc::InfoTagMusic::setTrack (...)
Function: setTrack(track)
Set the track number of the song.
Parameters
track integer - Track number.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setTrackRaw().
setTrackRaw()
void XBMCAddon::xbmc::InfoTagMusic::setTrackRaw (MUSIC_INFO::CMusicInfoTag * infoTag, int track) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetTrackNumber().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setTrack().
setURL()
void XBMCAddon::xbmc::InfoTagMusic::setURL (...)
Function: setURL(url)
Set the URL of the music item.
Parameters
url string - URL.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setURLRaw().
setURLRaw()
void XBMCAddon::xbmc::InfoTagMusic::setURLRaw (MUSIC_INFO::CMusicInfoTag * infoTag, const String & url) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetURL().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setURL().
setUserRating()
void XBMCAddon::xbmc::InfoTagMusic::setUserRating (...)
Function: setUserRating(userrating)
Set the user rating of the music item.
Parameters
userrating integer - User rating.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setUserRatingRaw().
setUserRatingRaw()
void XBMCAddon::xbmc::InfoTagMusic::setUserRatingRaw (MUSIC_INFO::CMusicInfoTag * infoTag, int userrating) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetUserrating().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setUserRating().
setYear()
void XBMCAddon::xbmc::InfoTagMusic::setYear (...)
Function: setYear(year)
Set the year of the music item.
Parameters
year integer - Year.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagMusic::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagMusic::offscreen, and XBMCAddon::xbmc::InfoTagMusic::setYearRaw().
setYearRaw()
void XBMCAddon::xbmc::InfoTagMusic::setYearRaw (MUSIC_INFO::CMusicInfoTag * infoTag, int year) static
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and MUSIC_INFO::CMusicInfoTag::SetYear().
Referenced by XBMCAddon::xbmc::InfoTagMusic::setYear().
~InfoTagMusic()
XBMCAddon::xbmc::InfoTagMusic::~InfoTagMusic () override
References XBMCAddon::xbmc::InfoTagMusic::infoTag, and XBMCAddon::xbmc::InfoTagMusic::owned.
Variable Documentation
infoTag
MUSIC_INFO::CMusicInfoTag* XBMCAddon::xbmc::InfoTagMusic::infoTag private
Referenced by XBMCAddon::xbmc::InfoTagMusic::getAlbum(), XBMCAddon::xbmc::InfoTagMusic::getAlbumArtist(), XBMCAddon::xbmc::InfoTagMusic::getArtist(), XBMCAddon::xbmc::InfoTagMusic::getComment(), XBMCAddon::xbmc::InfoTagMusic::getDbId(), XBMCAddon::xbmc::InfoTagMusic::getDisc(), XBMCAddon::xbmc::InfoTagMusic::getDuration(), XBMCAddon::xbmc::InfoTagMusic::getGenre(), XBMCAddon::xbmc::InfoTagMusic::getGenres(), XBMCAddon::xbmc::InfoTagMusic::getLastPlayed(), XBMCAddon::xbmc::InfoTagMusic::getLastPlayedAsW3C(), XBMCAddon::xbmc::InfoTagMusic::getListeners(), XBMCAddon::xbmc::InfoTagMusic::getLyrics(), XBMCAddon::xbmc::InfoTagMusic::getMediaType(), XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzAlbumArtistID(), XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzAlbumID(), XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzArtistID(), XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzReleaseGroupID(), XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzTrackID(), XBMCAddon::xbmc::InfoTagMusic::getPlayCount(), XBMCAddon::xbmc::InfoTagMusic::getRating(), XBMCAddon::xbmc::InfoTagMusic::getReleaseDate(), XBMCAddon::xbmc::InfoTagMusic::getSongVideoURL(), XBMCAddon::xbmc::InfoTagMusic::getTitle(), XBMCAddon::xbmc::InfoTagMusic::getTrack(), XBMCAddon::xbmc::InfoTagMusic::getURL(), XBMCAddon::xbmc::InfoTagMusic::getUserRating(), XBMCAddon::xbmc::InfoTagMusic::getYear(), XBMCAddon::xbmc::InfoTagMusic::InfoTagMusic(), XBMCAddon::xbmc::InfoTagMusic::setAlbum(), XBMCAddon::xbmc::InfoTagMusic::setAlbumArtist(), XBMCAddon::xbmc::InfoTagMusic::setAlbumArtistRaw(), XBMCAddon::xbmc::InfoTagMusic::setAlbumRaw(), XBMCAddon::xbmc::InfoTagMusic::setArtist(), XBMCAddon::xbmc::InfoTagMusic::setArtistRaw(), XBMCAddon::xbmc::InfoTagMusic::setComment(), XBMCAddon::xbmc::InfoTagMusic::setCommentRaw(), XBMCAddon::xbmc::InfoTagMusic::setDbId(), XBMCAddon::xbmc::InfoTagMusic::setDbIdRaw(), XBMCAddon::xbmc::InfoTagMusic::setDisc(), XBMCAddon::xbmc::InfoTagMusic::setDiscRaw(), XBMCAddon::xbmc::InfoTagMusic::setDuration(), XBMCAddon::xbmc::InfoTagMusic::setDurationRaw(), XBMCAddon::xbmc::InfoTagMusic::setGenres(), XBMCAddon::xbmc::InfoTagMusic::setGenresRaw(), XBMCAddon::xbmc::InfoTagMusic::setLastPlayed(), XBMCAddon::xbmc::InfoTagMusic::setLastPlayedRaw(), XBMCAddon::xbmc::InfoTagMusic::setListeners(), XBMCAddon::xbmc::InfoTagMusic::setListenersRaw(), XBMCAddon::xbmc::InfoTagMusic::setLyrics(), XBMCAddon::xbmc::InfoTagMusic::setLyricsRaw(), XBMCAddon::xbmc::InfoTagMusic::setMediaType(), XBMCAddon::xbmc::InfoTagMusic::setMediaTypeRaw(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumArtistID(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumArtistIDRaw(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumID(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumIDRaw(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzArtistID(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzArtistIDRaw(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzReleaseGroupID(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzReleaseGroupIDRaw(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzTrackID(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzTrackIDRaw(), XBMCAddon::xbmc::InfoTagMusic::setPlayCount(), XBMCAddon::xbmc::InfoTagMusic::setPlayCountRaw(), XBMCAddon::xbmc::InfoTagMusic::setRating(), XBMCAddon::xbmc::InfoTagMusic::setRatingRaw(), XBMCAddon::xbmc::InfoTagMusic::setReleaseDate(), XBMCAddon::xbmc::InfoTagMusic::setReleaseDateRaw(), XBMCAddon::xbmc::InfoTagMusic::setSongVideoURL(), XBMCAddon::xbmc::InfoTagMusic::setSongVideoURLRaw(), XBMCAddon::xbmc::InfoTagMusic::setTitle(), XBMCAddon::xbmc::InfoTagMusic::setTitleRaw(), XBMCAddon::xbmc::InfoTagMusic::setTrack(), XBMCAddon::xbmc::InfoTagMusic::setTrackRaw(), XBMCAddon::xbmc::InfoTagMusic::setURL(), XBMCAddon::xbmc::InfoTagMusic::setURLRaw(), XBMCAddon::xbmc::InfoTagMusic::setUserRating(), XBMCAddon::xbmc::InfoTagMusic::setUserRatingRaw(), XBMCAddon::xbmc::InfoTagMusic::setYear(), XBMCAddon::xbmc::InfoTagMusic::setYearRaw(), and XBMCAddon::xbmc::InfoTagMusic::~InfoTagMusic().
offscreen
bool XBMCAddon::xbmc::InfoTagMusic::offscreen private
Referenced by XBMCAddon::xbmc::InfoTagMusic::setAlbum(), XBMCAddon::xbmc::InfoTagMusic::setAlbumArtist(), XBMCAddon::xbmc::InfoTagMusic::setArtist(), XBMCAddon::xbmc::InfoTagMusic::setComment(), XBMCAddon::xbmc::InfoTagMusic::setDbId(), XBMCAddon::xbmc::InfoTagMusic::setDisc(), XBMCAddon::xbmc::InfoTagMusic::setDuration(), XBMCAddon::xbmc::InfoTagMusic::setGenres(), XBMCAddon::xbmc::InfoTagMusic::setLastPlayed(), XBMCAddon::xbmc::InfoTagMusic::setListeners(), XBMCAddon::xbmc::InfoTagMusic::setLyrics(), XBMCAddon::xbmc::InfoTagMusic::setMediaType(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumArtistID(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumID(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzArtistID(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzReleaseGroupID(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzTrackID(), XBMCAddon::xbmc::InfoTagMusic::setPlayCount(), XBMCAddon::xbmc::InfoTagMusic::setRating(), XBMCAddon::xbmc::InfoTagMusic::setReleaseDate(), XBMCAddon::xbmc::InfoTagMusic::setSongVideoURL(), XBMCAddon::xbmc::InfoTagMusic::setTitle(), XBMCAddon::xbmc::InfoTagMusic::setTrack(), XBMCAddon::xbmc::InfoTagMusic::setURL(), XBMCAddon::xbmc::InfoTagMusic::setUserRating(), and XBMCAddon::xbmc::InfoTagMusic::setYear().
owned
bool XBMCAddon::xbmc::InfoTagMusic::owned private
Referenced by XBMCAddon::xbmc::InfoTagMusic::~InfoTagMusic().