Kodi Documentation: CPlayerCoreFactory Class Reference
CPlayerCoreFactory Class Reference
#include <PlayerCoreFactory.h>
Public Member Functions
CPlayerCoreFactory (const CProfileManager &profileManager)
CPlayerCoreFactory (const CPlayerCoreFactory &)=delete
CPlayerCoreFactory & operator= (CPlayerCoreFactory const &)=delete
~CPlayerCoreFactory () override
void OnSettingsLoaded () override
Settings have been loaded.
std::shared_ptr< IPlayer > CreatePlayer (const std::string &nameId, IPlayerCallback &callback) const
void GetPlayers (const CFileItem &item, std::vector< std::string > &players) const
void GetPlayers (std::vector< std::string > &players, bool audio, bool video) const
void GetPlayers (std::vector< std::string > &players) const
void GetPlayers (std::vector< std::string > &players, std::string &type) const
void GetRemotePlayers (std::vector< std::string > &players) const
std::string GetPlayerType (const std::string &player) const
bool IsExternalPlayer (const std::string &player) const
bool IsRemotePlayer (const std::string &player) const
bool PlaysAudio (const std::string &player) const
bool PlaysVideo (const std::string &player) const
std::string GetDefaultPlayer (const CFileItem &item) const
std::string SelectPlayerDialog (const std::vector< std::string > &players, float posX=0, float posY=0) const
std::string SelectPlayerDialog (float posX, float posY) const
void OnPlayerDiscovered (const std::string &id, const std::string &name)
void OnPlayerRemoved (const std::string &id)
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsUnloaded ()
Setting values have been unloaded.
virtual void OnSettingsCleared ()
Settings have been cleared.
Private Member Functions
int GetPlayerIndex (const std::string &strCoreName) const
std::string GetPlayerName (size_t idx) const
bool LoadConfiguration (const std::string &file, bool clear)
Private Attributes
std::shared_ptr< CSettings > m_settings
const CProfileManager & m_profileManager
std::vector< std::unique_ptr< CPlayerCoreConfig > > m_vecPlayerConfigs
std::list< std::unique_ptr< CPlayerSelectionRule > > m_vecCoreSelectionRules
CCriticalSection m_section
Constructor & Destructor Documentation
CPlayerCoreFactory() [1/2]
CPlayerCoreFactory::CPlayerCoreFactory (const CProfileManager & profileManager)
References m_settings, and OnSettingsLoaded().
CPlayerCoreFactory() [2/2]
CPlayerCoreFactory::CPlayerCoreFactory (const CPlayerCoreFactory &) delete
~CPlayerCoreFactory()
CPlayerCoreFactory::~CPlayerCoreFactory () override
References m_settings.
Member Function Documentation
CreatePlayer()
std::shared_ptr< IPlayer > CPlayerCoreFactory::CreatePlayer (const std::string & nameId, IPlayerCallback & callback) const
References GetPlayerIndex(), m_section, and m_vecPlayerConfigs.
Referenced by CApplicationPlayer::CreatePlayer().
GetDefaultPlayer()
std::string CPlayerCoreFactory::GetDefaultPlayer (const CFileItem & item) const
References GetPlayers().
Referenced by CApplicationPlayer::OpenFile().
GetPlayerIndex()
int CPlayerCoreFactory::GetPlayerIndex (const std::string & strCoreName) const private
References CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGWARNING, m_section, and m_vecPlayerConfigs.
Referenced by CreatePlayer(), GetPlayers(), GetPlayerType(), LoadConfiguration(), OnPlayerDiscovered(), PlaysAudio(), and PlaysVideo().
GetPlayerName()
std::string CPlayerCoreFactory::GetPlayerName (size_t idx) const private
References m_section, and m_vecPlayerConfigs.
Referenced by GetPlayers().
GetPlayers() [1/4]
void CPlayerCoreFactory::GetPlayers (const CFileItem & item, std::vector< std::string > & players) const
References CVariant::asString(), CVariant::empty(), CFileItem::GetDynPath(), GetPlayerIndex(), GetPlayerName(), GetPlayers(), CGUIListItem::GetProperty(), KODI::MUSIC::IsAudio(), CFileItem::IsGame(), CLog::Log(), LOGDEBUG, m_vecCoreSelectionRules, NONE, STREAM_PROPERTY_INPUTSTREAM, and STREAM_PROPERTY_INPUTSTREAM_PLAYER.
Referenced by GetDefaultPlayer(), GetPlayers(), anonymous_namespace{ContextMenus.cpp}::GetPlayers(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::GetPlayers(), JSONRPC::CPlayerOperations::GetPlayers(), CApplication::OnAction(), CGUIWindowFileManager::OnPopupMenu(), JSONRPC::CPlayerOperations::Open(), and SelectPlayerDialog().
GetPlayers() [2/4]
void CPlayerCoreFactory::GetPlayers (std::vector< std::string > & players) const
References m_section, and m_vecPlayerConfigs.
GetPlayers() [3/4]
void CPlayerCoreFactory::GetPlayers (std::vector< std::string > & players, bool audio, bool video) const
References CLog::Log(), LOGDEBUG, m_section, and m_vecPlayerConfigs.
GetPlayers() [4/4]
void CPlayerCoreFactory::GetPlayers (std::vector< std::string > & players, std::string & type) const
References m_section, and m_vecPlayerConfigs.
GetPlayerType()
std::string CPlayerCoreFactory::GetPlayerType (const std::string & player) const
References GetPlayerIndex(), m_section, and m_vecPlayerConfigs.
Referenced by JSONRPC::CPlayerOperations::GetPlayers(), IsExternalPlayer(), IsRemotePlayer(), and JSONRPC::CPlayerOperations::Open().
GetRemotePlayers()
void CPlayerCoreFactory::GetRemotePlayers (std::vector< std::string > & players) const
References m_section, and m_vecPlayerConfigs.
Referenced by CApplication::OnAction().
IsExternalPlayer()
bool CPlayerCoreFactory::IsExternalPlayer (const std::string & player) const
References GetPlayerType().
IsRemotePlayer()
bool CPlayerCoreFactory::IsRemotePlayer (const std::string & player) const
References GetPlayerType().
LoadConfiguration()
bool CPlayerCoreFactory::LoadConfiguration (const std::string & file, bool clear) private
References CFileUtils::Exists(), XMLUtils::GetAttribute(), GetPlayerIndex(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGERROR, LOGINFO, m_section, m_vecCoreSelectionRules, m_vecPlayerConfigs, and name.
Referenced by OnSettingsLoaded().
OnPlayerDiscovered()
void CPlayerCoreFactory::OnPlayerDiscovered (const std::string & id, const std::string & name)
References GetPlayerIndex(), id, m_section, m_vecPlayerConfigs, and name.
Referenced by UPNP::CMediaController::OnMRAdded().
OnPlayerRemoved()
void CPlayerCoreFactory::OnPlayerRemoved (const std::string & id)
References id, m_section, and m_vecPlayerConfigs.
Referenced by UPNP::CMediaController::unregisterRenderer().
OnSettingsLoaded()
void CPlayerCoreFactory::OnSettingsLoaded () override virtual
Settings have been loaded.
This callback can be used to trigger loading other settings.
Reimplemented from ISettingsHandler.
References CProfileManager::GetUserDataItem(), LoadConfiguration(), m_profileManager, and PLAYERCOREFACTORY_XML.
Referenced by CPlayerCoreFactory().
operator=()
CPlayerCoreFactory & CPlayerCoreFactory::operator= (CPlayerCoreFactory const &) delete
PlaysAudio()
bool CPlayerCoreFactory::PlaysAudio (const std::string & player) const
References GetPlayerIndex(), m_section, and m_vecPlayerConfigs.
Referenced by JSONRPC::CPlayerOperations::GetPlayers().
PlaysVideo()
bool CPlayerCoreFactory::PlaysVideo (const std::string & player) const
References GetPlayerIndex(), m_section, and m_vecPlayerConfigs.
Referenced by JSONRPC::CPlayerOperations::GetPlayers().
SelectPlayerDialog() [1/2]
std::string CPlayerCoreFactory::SelectPlayerDialog (const std::vector< std::string > & players, float posX = 0, float posY = 0) const
References CContextButtons::Add(), g_localizeStrings, CLocalizeStrings::Get(), and CGUIDialogContextMenu::ShowAndGetChoice().
Referenced by CApplication::OnAction(), CGUIWindowFileManager::OnPopupMenu(), and SelectPlayerDialog().
SelectPlayerDialog() [2/2]
std::string CPlayerCoreFactory::SelectPlayerDialog (float posX, float posY) const
References GetPlayers(), and SelectPlayerDialog().
Member Data Documentation
m_profileManager
const CProfileManager& CPlayerCoreFactory::m_profileManager private
Referenced by OnSettingsLoaded().
m_section
CCriticalSection CPlayerCoreFactory::m_section mutable private
Referenced by CreatePlayer(), GetPlayerIndex(), GetPlayerName(), GetPlayers(), GetPlayers(), GetPlayers(), GetPlayerType(), GetRemotePlayers(), LoadConfiguration(), OnPlayerDiscovered(), OnPlayerRemoved(), PlaysAudio(), and PlaysVideo().
m_settings
std::shared_ptr<CSettings> CPlayerCoreFactory::m_settings private
Referenced by CPlayerCoreFactory(), and ~CPlayerCoreFactory().
m_vecCoreSelectionRules
std::list<std::unique_ptr<CPlayerSelectionRule> > CPlayerCoreFactory::m_vecCoreSelectionRules private
Referenced by GetPlayers(), and LoadConfiguration().
m_vecPlayerConfigs
std::vector<std::unique_ptr<CPlayerCoreConfig> > CPlayerCoreFactory::m_vecPlayerConfigs private
Referenced by CreatePlayer(), GetPlayerIndex(), GetPlayerName(), GetPlayers(), GetPlayers(), GetPlayers(), GetPlayerType(), GetRemotePlayers(), LoadConfiguration(), OnPlayerDiscovered(), OnPlayerRemoved(), PlaysAudio(), and PlaysVideo().
The documentation for this class was generated from the following files:
PlayerCoreFactory.h
PlayerCoreFactory.cpp