Kodi Documentation: KODI::RETRO::CRenderTranslator Class Reference
KODI::RETRO::CRenderTranslator Class Reference
#include <RenderTranslator.h>
Static Public Member Functions
static const char * TranslatePixelFormat (AVPixelFormat format)
Translate a pixel format to a string suitable for logging.
static const char * TranslateScalingMethod (SCALINGMETHOD scalingMethod)
Translate a scaling method to a string suitable for logging.
static unsigned int TranslateWidthToBytes (unsigned int width, AVPixelFormat format)
Translate a width in pixels to a width in bytes.
Member Function Documentation
TranslatePixelFormat()
const char * CRenderTranslator::TranslatePixelFormat (AVPixelFormat format) static
Translate a pixel format to a string suitable for logging.
Referenced by KODI::RETRO::CRPRenderManager::Configure(), and KODI::RETRO::CRetroPlayerVideo::OpenStream().
TranslateScalingMethod()
const char * CRenderTranslator::TranslateScalingMethod (SCALINGMETHOD scalingMethod) static
Translate a scaling method to a string suitable for logging.
References KODI::RETRO::LINEAR, and KODI::RETRO::NEAREST.
Referenced by KODI::RETRO::CWinRenderBufferPool::CompileOutputShaders().
TranslateWidthToBytes()
unsigned int CRenderTranslator::TranslateWidthToBytes (unsigned int width, AVPixelFormat format) static
Translate a width in pixels to a width in bytes.
Parameters
width The width in pixels
format The pixel format
Returns
The width in bytes, or 0 if unknown
Referenced by KODI::RETRO::CRPRenderManager::CopyFrame(), KODI::RETRO::CRenderBufferSysMem::GetBufferSize(), and KODI::RETRO::CRPRenderManager::SaveThumbnail().
The documentation for this class was generated from the following files:
RenderTranslator.h
RenderTranslator.cpp