Kodi Documentation: XFILE::CFileCache Class Reference
XFILE::CFileCache Class Reference
#include <FileCache.h>
Public Member Functions
CFileCache (const unsigned int flags)
~CFileCache () override
void Process () override
void OnExit () override
void StopThread (bool bWait=true) override
bool Open (const CURL &url) override
void Close () override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence) override
int64_t GetPosition () override
int64_t GetLength () override
int IoControl (EIoControl request, void *param) override
IFile * GetFileImp ()
const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const override
const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool OpenForWrite (const CURL &url, bool bOverWrite=false)
virtual bool ReOpen (const CURL &url)
virtual int Stat (struct __stat64 *buffer)
virtual ssize_t Write (const void *bufPtr, size_t bufSize)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool Delete (const CURL &url)
virtual bool Rename (const CURL &url, const CURL &urlnew)
virtual bool SetHidden (const CURL &url, bool hidden)
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Attributes
std::unique_ptr< CCacheStrategy > m_pCache
int m_seekPossible = 0
CFile m_source
std::string m_sourcePath
CEvent m_seekEvent
CEvent m_seekEnded
int64_t m_nSeekResult = 0
int64_t m_seekPos = 0
int64_t m_readPos = 0
int64_t m_writePos = 0
unsigned m_chunkSize = 0
uint32_t m_writeRate = 0
uint32_t m_writeRateActual = 0
uint32_t m_writeRateLowSpeed = 0
int64_t m_forwardCacheSize = 0
int64_t m_maxForward = 0
bool m_bFilling = false
std::atomic< int64_t > m_fileSize
unsigned int m_flags
CCriticalSection m_sync
std::chrono::milliseconds m_processWait {100ms}
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CFileCache()
CFileCache::CFileCache (const unsigned int flags) explicit
~CFileCache()
CFileCache::~CFileCache () override
References Close().
Member Function Documentation
Close()
void CFileCache::Close () override virtual
Implements XFILE::IFile.
References XFILE::CFile::Close(), m_pCache, m_source, m_sync, and StopThread().
Referenced by Open(), and ~CFileCache().
Exists()
bool CFileCache::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References XFILE::CFile::Exists(), and CURL::Get().
GetFileImp()
IFile * CFileCache::GetFileImp ()
References XFILE::CFile::GetImplementation(), and m_source.
GetLength()
int64_t CFileCache::GetLength () override virtual
Implements XFILE::IFile.
References m_fileSize.
GetPosition()
int64_t CFileCache::GetPosition () override virtual
Implements XFILE::IFile.
References m_readPos.
Referenced by XFILE::CShoutcastFile::Process().
GetProperty()
const std::string CFileCache::GetProperty (XFILE::FileProperty type, const std::string & name = "") const override virtual
Reimplemented from XFILE::IFile.
References XFILE::CFile::GetImplementation(), XFILE::IFile::GetProperty(), m_source, and name.
GetPropertyValues()
const std::vector< std::string > XFILE::CFileCache::GetPropertyValues (XFILE::FileProperty type, const std::string & name = "") const inline override virtual
Reimplemented from XFILE::IFile.
IoControl()
int CFileCache::IoControl (EIoControl request, void * param) override virtual
Reimplemented from XFILE::IFile.
References XFILE::SCacheStatus::currate, XFILE::SCacheStatus::forward, XFILE::IOCTRL_CACHE_SETRATE, XFILE::IOCTRL_CACHE_STATUS, XFILE::IOCTRL_SEEK_POSSIBLE, CLog::Log(), LOGDEBUG, XFILE::SCacheStatus::lowrate, m_maxForward, m_pCache, m_processWait, m_seekPossible, m_writeRate, m_writeRateActual, m_writeRateLowSpeed, XFILE::SCacheStatus::maxforward, and XFILE::SCacheStatus::maxrate.
OnExit()
void CFileCache::OnExit () override virtual
Reimplemented from CThread.
References CThread::m_bStop, m_pCache, m_seekEnded, and CEvent::Set().
Open()
bool CFileCache::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References CACHE_RC_OK, Close(), CThread::Create(), XFILE::CFile::DetermineChunkSize(), CURL::Get(), XFILE::CFile::GetChunkSize(), XFILE::CFile::GetLength(), CURL::GetRedacted(), CServiceBroker::GetSettingsComponent(), XFILE::CFile::IoControl(), XFILE::IOCTRL_SEEK_POSSIBLE, XFILE::IOCTRL_SET_CACHE, XFILE::IOCTRL_SET_RETRY, CLog::Log(), LOGDEBUG, LOGERROR, m_bFilling, m_chunkSize, m_fileSize, m_flags, m_forwardCacheSize, m_maxForward, m_pCache, m_readPos, m_seekEnded, m_seekEvent, m_seekPossible, m_source, m_sourcePath, m_sync, m_writePos, m_writeRate, m_writeRateActual, m_writeRateLowSpeed, XFILE::CFile::Open(), XFILE::READ_AUDIO_VIDEO, XFILE::READ_MULTI_STREAM, XFILE::READ_NO_BUFFER, XFILE::READ_NO_CACHE, XFILE::READ_TRUNCATED, CEvent::Reset(), CSettings::SETTING_FILECACHE_CHUNKSIZE, and CSettings::SETTING_FILECACHE_MEMORYSIZE.
Process()
void CFileCache::Process (void) override virtual
Reimplemented from CThread.
References CThread::AbortableWait(), GetLastError(), XFILE::CFile::GetLength(), CServiceBroker::GetSettingsComponent(), int64_t(), XFILE::CFile::IoControl(), XFILE::IOCTRL_SEEK_POSSIBLE, CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_bFilling, CThread::m_bStop, m_chunkSize, m_fileSize, m_forwardCacheSize, m_maxForward, m_nSeekResult, m_pCache, m_processWait, m_readPos, m_seekEnded, m_seekEvent, m_seekPos, m_seekPossible, m_source, m_sourcePath, m_writePos, m_writeRate, m_writeRateActual, m_writeRateLowSpeed, CWriteRate::Rate(), XFILE::CFile::Read(), CEvent::Reset(), CWriteRate::Reset(), XFILE::CFile::Seek(), CEvent::Set(), CSettings::SETTING_FILECACHE_READFACTOR, CEvent::Wait(), and CThread::WAIT_SIGNALED.
Read()
ssize_t CFileCache::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References CACHE_RC_TIMEOUT, CACHE_RC_WOULD_BLOCK, int64_t(), CLog::Log(), LOGERROR, LOGWARNING, m_pCache, m_readPos, m_sourcePath, m_sync, and SSIZE_MAX.
Seek()
int64_t CFileCache::Seek (int64_t iFilePosition, int iWhence) override virtual
Implements XFILE::IFile.
References int64_t(), CThread::IsRunning(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_chunkSize, m_fileSize, m_nSeekResult, m_pCache, m_readPos, m_seekEnded, m_seekEvent, m_seekPos, m_seekPossible, m_sourcePath, m_sync, CEvent::Reset(), CEvent::Set(), and CEvent::Wait().
Stat()
int CFileCache::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References CURL::Get(), and XFILE::CFile::Stat().
StopThread()
void CFileCache::StopThread (bool bWait = true) override virtual
Reimplemented from CThread.
References CThread::m_bStop, m_seekEvent, CEvent::Set(), and CThread::StopThread().
Referenced by Close().
Member Data Documentation
m_bFilling
bool XFILE::CFileCache::m_bFilling = false private
Referenced by Open(), and Process().
m_chunkSize
unsigned XFILE::CFileCache::m_chunkSize = 0 private
Referenced by Open(), Process(), and Seek().
m_fileSize
std::atomic<int64_t> XFILE::CFileCache::m_fileSize private
Referenced by GetLength(), Open(), Process(), and Seek().
m_flags
unsigned int XFILE::CFileCache::m_flags private
Referenced by Open().
m_forwardCacheSize
int64_t XFILE::CFileCache::m_forwardCacheSize = 0 private
Referenced by Open(), and Process().
m_maxForward
int64_t XFILE::CFileCache::m_maxForward = 0 private
Referenced by IoControl(), Open(), and Process().
m_nSeekResult
int64_t XFILE::CFileCache::m_nSeekResult = 0 private
Referenced by Process(), and Seek().
m_pCache
std::unique_ptr<CCacheStrategy> XFILE::CFileCache::m_pCache private
Referenced by Close(), IoControl(), OnExit(), Open(), Process(), Read(), and Seek().
m_processWait
std::chrono::milliseconds XFILE::CFileCache::m_processWait {100ms} private
Referenced by IoControl(), and Process().
m_readPos
int64_t XFILE::CFileCache::m_readPos = 0 private
Referenced by GetPosition(), Open(), Process(), Read(), and Seek().
m_seekEnded
CEvent XFILE::CFileCache::m_seekEnded private
Referenced by OnExit(), Open(), Process(), and Seek().
m_seekEvent
CEvent XFILE::CFileCache::m_seekEvent private
Referenced by Open(), Process(), Seek(), and StopThread().
m_seekPos
int64_t XFILE::CFileCache::m_seekPos = 0 private
Referenced by Process(), and Seek().
m_seekPossible
int XFILE::CFileCache::m_seekPossible = 0 private
Referenced by IoControl(), Open(), Process(), and Seek().
m_source
CFile XFILE::CFileCache::m_source private
Referenced by Close(), GetFileImp(), GetProperty(), Open(), and Process().
m_sourcePath
std::string XFILE::CFileCache::m_sourcePath private
Referenced by Open(), Process(), Read(), and Seek().
m_sync
CCriticalSection XFILE::CFileCache::m_sync private
Referenced by Close(), Open(), Read(), and Seek().
m_writePos
int64_t XFILE::CFileCache::m_writePos = 0 private
Referenced by Open(), and Process().
m_writeRate
uint32_t XFILE::CFileCache::m_writeRate = 0 private
Referenced by IoControl(), Open(), and Process().
m_writeRateActual
uint32_t XFILE::CFileCache::m_writeRateActual = 0 private
Referenced by IoControl(), Open(), and Process().
m_writeRateLowSpeed
uint32_t XFILE::CFileCache::m_writeRateLowSpeed = 0 private
Referenced by IoControl(), Open(), and Process().
The documentation for this class was generated from the following files:
FileCache.h
FileCache.cpp