Kodi Documentation: CGLContext Class Reference
CGLContext Class Reference abstract
#include <GLContext.h>
Public Member Functions
CGLContext (Display *dpy)
virtual ~CGLContext ()=default
virtual bool Refresh (bool force, int screen, Window glWindow, bool &newContext)=0
virtual bool CreatePB ()
virtual void Destroy ()=0
virtual void Detach ()=0
virtual void SetVSync (bool enable)=0
virtual void SwapBuffers ()=0
virtual void QueryExtensions ()=0
virtual uint64_t GetVblankTiming (uint64_t &msc, uint64_t &interval)
bool IsExtSupported (const char *extension) const
const std::string & ExtPrefix () const
Public Attributes
std::string m_extPrefix
std::string m_extensions
Display * m_dpy
Protected Attributes
bool m_omlSync = true
Constructor & Destructor Documentation
CGLContext()
CGLContext::CGLContext (Display * dpy) inline explicit
References m_dpy.
~CGLContext()
virtual CGLContext::~CGLContext () virtual default
Member Function Documentation
CreatePB()
virtual bool CGLContext::CreatePB () inline virtual
Reimplemented in CGLContextEGL.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext().
Destroy()
virtual void CGLContext::Destroy () pure virtual
Implemented in CGLContextEGL, and KODI::WINDOWING::X11::CGLContextGLX.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::DestroyWindowSystem().
Detach()
virtual void CGLContext::Detach () pure virtual
Implemented in CGLContextEGL, and KODI::WINDOWING::X11::CGLContextGLX.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::DestroyWindow().
ExtPrefix()
const std::string & CGLContext::ExtPrefix () const inline
References m_extPrefix.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::IsExtSupported(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::IsExtSupported().
GetVblankTiming()
virtual uint64_t CGLContext::GetVblankTiming (uint64_t & msc, uint64_t & interval) inline virtual
Reimplemented in CGLContextEGL.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::GetFrameLatencyAdjustment(), and KODI::WINDOWING::X11::CWinSystemX11GLContext::GetVblankTiming().
IsExtSupported()
bool CGLContext::IsExtSupported (const char * extension) const
References m_extensions, and name.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::IsExtSupported(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::IsExtSupported(), and KODI::WINDOWING::X11::CGLContextGLX::QueryExtensions().
QueryExtensions()
virtual void CGLContext::QueryExtensions () pure virtual
Implemented in CGLContextEGL, and KODI::WINDOWING::X11::CGLContextGLX.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::CreateNewWindow().
Refresh()
virtual bool CGLContext::Refresh (bool force, int screen, Window glWindow, bool & newContext) pure virtual
Implemented in CGLContextEGL, and KODI::WINDOWING::X11::CGLContextGLX.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext().
SetVSync()
virtual void CGLContext::SetVSync (bool enable) pure virtual
Implemented in CGLContextEGL, and KODI::WINDOWING::X11::CGLContextGLX.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::SetVSyncImpl().
SwapBuffers()
virtual void CGLContext::SwapBuffers () pure virtual
Implemented in CGLContextEGL, and KODI::WINDOWING::X11::CGLContextGLX.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::PresentRenderImpl().
Member Data Documentation
m_dpy
Display* CGLContext::m_dpy
Referenced by CGLContext(), CGLContextEGL::CreatePB(), KODI::WINDOWING::X11::CGLContextGLX::Destroy(), KODI::WINDOWING::X11::CGLContextGLX::Detach(), KODI::WINDOWING::X11::CGLContextGLX::IsSuitableVisual(), KODI::WINDOWING::X11::CGLContextGLX::QueryExtensions(), CGLContextEGL::Refresh(), KODI::WINDOWING::X11::CGLContextGLX::Refresh(), KODI::WINDOWING::X11::CGLContextGLX::SetVSync(), and KODI::WINDOWING::X11::CGLContextGLX::SwapBuffers().
m_extensions
std::string CGLContext::m_extensions
Referenced by IsExtSupported(), CGLContextEGL::QueryExtensions(), and KODI::WINDOWING::X11::CGLContextGLX::QueryExtensions().
m_extPrefix
std::string CGLContext::m_extPrefix
Referenced by CGLContextEGL::CGLContextEGL(), KODI::WINDOWING::X11::CGLContextGLX::CGLContextGLX(), and ExtPrefix().
m_omlSync
bool CGLContext::m_omlSync = true protected
Referenced by CGLContextEGL::CGLContextEGL(), and CGLContextEGL::SwapBuffers().
The documentation for this class was generated from the following files:
GLContext.h
GLContext.cpp