Kodi Documentation: ADDON Namespace Reference
ADDON Namespace Reference
Namespaces
namespace AddonEvents
namespace anonymous_namespace{Skin.cpp}
namespace GUI
Classes
struct AddonEvent
struct AddonIdFinder
class CAddon
class CAddonBuilder
class CAddonDatabase
class CAddonDatabaseSerializer
Addon content serializer/deserializer.
class CAddonDll
class CAddonDllInformer
Information class for use on addon type managers.
class CAddonExtensions
class CAddonGUITranslator
Translates data types from GUI API to the corresponding format in Kodi.
class CAddonInfo
class CAddonInfoBuilder
class CAddonInfoBuilderFromDB
class CAddonInstaller
class CAddonMgr
class CAddonRepos
class CAddonSettings
class CAddonStatusHandler
class CAddonSystemSettings
class CAddonType
class CAddonUpdateRules
class CAddonVersion
class CBinaryAddonBase
class CBinaryAddonCache
class CBinaryAddonManager
class CContextMenuAddon
class CExtValues
class CFontResource
class CGameResource
class CGUIAddonRenderingControl
class CGUIAddonWindow
class CGUIAddonWindowDialog
class CImageResource
A collection of images. The collection can have a type.
class CLanguageResource
struct closestRes
struct ContentMapping
class CPluginSource
class CRepository
class CRepositoryUpdateJob
class CRepositoryUpdater
class CResource
class CScraper
class CScraperError
class CService
class CServiceAddonManager
class CSettingUrlEncodedString
class CSkinInfo
class CSkinSetting
class CSkinSettingBool
class CSkinSettingString
class CSkinSettingUpdateHandler
class CUISoundsResource
class CVFSAddonCache
class CVFSEntry
A virtual filesystem entry add-on.
class CVFSEntryIDirectoryWrapper
Wrapper equpping a CVFSEntry with an IDirectory interface.
class CVFSEntryIFileDirectoryWrapper
Wrapper equpping a CVFSEntry with an IFileDirectory interface.
class CVFSEntryIFileWrapper
Wrapper equipping a CVFSEntry with an IFile interface.
class CVFSURLWrapper
class CWebinterface
struct DependencyInfo
class IAddon
class IAddonInstanceHandler
class IAddonMgrCallback
class IAddonProvider
struct Interface_Android
struct Interface_AudioEngine
struct Interface_Base
Global general Add-on to Kodi callback functions.
struct Interface_Filesystem
struct Interface_General
Global general Add-on to Kodi callback functions.
struct Interface_GUIControlAddonRendering
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlButton
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlEdit
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlFadeLabel
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlImage
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlLabel
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlProgress
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlRadioButton
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlSettingsSlider
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlSlider
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlSpin
Global gui Add-on to Kodi callback functions.
struct Interface_GUIControlTextBox
Global gui Add-on to Kodi callback functions.
struct Interface_GUIDialogContextMenu
Global gui Add-on to Kodi callback functions.
struct Interface_GUIDialogExtendedProgress
Global gui Add-on to Kodi callback functions.
struct Interface_GUIDialogFileBrowser
Global gui Add-on to Kodi callback functions.
struct Interface_GUIDialogKeyboard
Global gui Add-on to Kodi callback functions.
struct Interface_GUIDialogNumeric
Global gui Add-on to Kodi callback functions.
struct Interface_GUIDialogOK
Global gui Add-on to Kodi callback functions.
struct Interface_GUIDialogProgress
Global gui Add-on to Kodi callback functions.
struct Interface_GUIDialogSelect
Global gui Add-on to Kodi callback functions.
struct Interface_GUIDialogTextViewer
Global gui Add-on to Kodi callback functions.
struct Interface_GUIDialogYesNo
Global gui Add-on to Kodi callback functions.
struct Interface_GUIGeneral
Global gui Add-on to Kodi callback functions.
struct Interface_GUIListItem
Global gui Add-on to Kodi callback functions.
struct Interface_GUIWindow
Global gui Add-on to Kodi callback functions.
struct Interface_Network
Global general Add-on to Kodi callback functions.
struct RepoInfo
struct RepositoryDirInfo
struct SExtValue
struct TypeMapping
Typedefs
using AddonInfoPtr = std::shared_ptr< CAddonInfo >
using AddonPtr = std::shared_ptr< IAddon >
using VECADDONS = std::vector< AddonPtr >
typedef std::vector< std::pair< std::string, CAddonExtensions > > EXT_ELEMENTS
typedef std::vector< std::pair< std::string, SExtValue > > EXT_VALUE
typedef std::vector< std::pair< std::string, CExtValues > > EXT_VALUES
typedef std::vector< AddonInfoPtr > AddonInfos
using AddonInstanceId = uint32_t
using InfoMap = std::map< std::string, std::string >
using ArtMap = std::map< std::string, std::string >
using RepositoryPtr = std::shared_ptr< CRepository >
using ADDON_INFO_LIST = std::map< std::string, AddonInfoPtr >
using AddonWithUpdate = std::pair< std::shared_ptr< IAddon >, std::shared_ptr< IAddon > >
using BinaryAddonBasePtr = std::shared_ptr< CBinaryAddonBase >
using ADDON_INSTANCE_HANDLER = void *
using AddonDllPtr = std::shared_ptr< CAddonDll >
typedef void *(* ADDON_GET_INTERFACE_FN) (const std::string &name, const std::string &version)
typedef std::map< std::string, std::vector< std::string > > ContentPathMap
typedef std::vector< RepositoryDirInfo > RepositoryDirList
typedef std::shared_ptr< CScraper > ScraperPtr
typedef std::shared_ptr< CSkinSetting > CSkinSettingPtr
typedef std::shared_ptr< CSkinSettingString > CSkinSettingStringPtr
typedef std::shared_ptr< CSkinSettingBool > CSkinSettingBoolPtr
typedef std::shared_ptr< CVFSEntry > VFSEntryPtr
typedef enum ADDON::WebinterfaceType WebinterfaceType
Enumerations
enum class AddonDisabledReason { NONE = 0 , USER = 1 , INCOMPATIBLE = 2 , PERMANENT_FAILURE = 3 }
enum class AddonOriginType { SYSTEM = 0 , REPOSITORY = 1 , MANUAL = 2 }
enum class AddonUpdateRule { ANY = 0 , USER_DISABLED_AUTO_UPDATE = 1 , PIN_OLD_VERSION = 2 , PIN_ZIP_INSTALL = 3 }
Reasons why an addon is not updateable.
enum class AddonInstanceSupport { SUPPORT_NONE = 0 , SUPPORT_MANDATORY = 1 , SUPPORT_OPTIONAL = 2 , SUPPORT_SETTINGS = 3 }
Independent add-on instance support.
enum class AddonLifecycleState { NORMAL = 0 , DEPRECATED = 1 , BROKEN = 2 }
Add-on state defined within addon.xml to report about the current addon lifecycle state.
enum class AddonType {
UNKNOWN = 0 , VISUALIZATION , SKIN , PVRDLL ,
INPUTSTREAM , GAMEDLL , PERIPHERALDLL , SCRIPT ,
SCRIPT_WEATHER , SUBTITLE_MODULE , SCRIPT_LYRICS , SCRAPER_ALBUMS ,
SCRAPER_ARTISTS , SCRAPER_MOVIES , SCRAPER_MUSICVIDEOS , SCRAPER_TVSHOWS ,
SCREENSAVER , PLUGIN , REPOSITORY , WEB_INTERFACE ,
SERVICE , AUDIOENCODER , CONTEXTMENU_ITEM , AUDIODECODER ,
RESOURCE_IMAGES , RESOURCE_LANGUAGE , RESOURCE_UISOUNDS , RESOURCE_GAMES ,
RESOURCE_FONT , VFS , IMAGEDECODER , SCRAPER_LIBRARY ,
SCRIPT_LIBRARY , SCRIPT_MODULE , GAME_CONTROLLER , VIDEOCODEC ,
VIDEO , AUDIO , IMAGE , EXECUTABLE ,
GAME , MAX_TYPES
}
enum class BackgroundJob : bool { CHOICE_YES = true , CHOICE_NO = false }
enum class ModalJob : bool { CHOICE_YES = true , CHOICE_NO = false }
enum class AutoUpdateJob : bool { CHOICE_YES = true , CHOICE_NO = false }
enum class DependencyJob : bool { CHOICE_YES = true , CHOICE_NO = false }
enum class InstallModalPrompt : bool { CHOICE_YES = true , CHOICE_NO = false }
enum class AllowCheckForUpdates : bool { CHOICE_YES = true , CHOICE_NO = false }
enum class RecurseOrphaned : bool { CHOICE_YES = true , CHOICE_NO = false }
enum class AddonCheckType : bool { OUTDATED_ADDONS , AVAILABLE_UPDATES }
enum class OnlyEnabled : bool { CHOICE_YES = true , CHOICE_NO = false }
enum class OnlyEnabledRootAddon : bool { CHOICE_YES = true , CHOICE_NO = false }
enum class CheckIncompatible : bool { CHOICE_YES = true , CHOICE_NO = false }
enum class CheckAddonPath { CHOICE_YES = true , CHOICE_NO = false }
enum class AddonRepoUpdateMode { OFFICIAL_ONLY = 0 , ANY_REPOSITORY = 1 }
enum WebinterfaceType { WebinterfaceTypeStatic = 0 , WebinterfaceTypeWsgi }
Functions
template<class TSetting >
bool GetSettingValue (CAddon &addon, AddonInstanceId instanceId, const std::string &key, typename TSetting::Value &value)
template<class TSetting >
bool UpdateSettingValue (CAddon &addon, AddonInstanceId instanceId, const std::string &key, typename TSetting::Value value)
void OnPreInstall (const AddonPtr &addon)
void OnPostInstall (const AddonPtr &addon, bool update, bool modal)
void OnPreUnInstall (const AddonPtr &addon)
void OnPostUnInstall (const AddonPtr &addon)
static bool LoadManifest (std::set< std::string > &system, std::set< std::string > &optional)
static void ResolveDependencies (const std::string &addonId, std::vector< std::string > &needed, std::vector< std::string > &missing)
static void CFileItemListToVFSDirEntries (VFSDirEntry *entries, const CFileItemList &items)
static void SetProgressIndicator (CRepositoryUpdateJob *job)
std::string TranslateContent (const CONTENT_TYPE &type, bool pretty)
CONTENT_TYPE TranslateContent (const std::string &string)
AddonType ScraperTypeFromContent (const CONTENT_TYPE &content)
static void CheckScraperError (const TiXmlElement *pxeRoot)
static bool RelevanceSortFunction (const CScraperUrl &left, const CScraperUrl &right)
template<class T >
static T FromFileItem (const CFileItem &item)
template<>
CScraperUrl FromFileItem< CScraperUrl > (const CFileItem &item)
template<>
CMusicAlbumInfo FromFileItem< CMusicAlbumInfo > (const CFileItem &item)
template<>
CMusicArtistInfo FromFileItem< CMusicArtistInfo > (const CFileItem &item)
template<class T >
static std::vector< T > PythonFind (const std::string &ID, const std::map< std::string, std::string > &additionals)
static std::string FromString (const CFileItem &item, const std::string &key)
static std::vector< std::string > FromArray (const CFileItem &item, const std::string &key, int sep)
static void ParseThumbs (CScraperUrl &scurl, const CFileItem &item, int nThumbs, const std::string &tag)
static std::string ParseFanart (const CFileItem &item, int nFanart, const std::string &tag)
template<class T >
static bool DetailsFromFileItem (const CFileItem &, T &)
template<>
bool DetailsFromFileItem< CAlbum > (const CFileItem &item, CAlbum &album)
template<>
bool DetailsFromFileItem< CArtist > (const CFileItem &item, CArtist &artist)
template<>
bool DetailsFromFileItem< CVideoInfoTag > (const CFileItem &item, CVideoInfoTag &tag)
template<class T >
static bool PythonDetails (const std::string &ID, const std::string &key, const std::string &url, const std::string &action, const std::string &pathSettings, const std::unordered_map< std::string, std::string > &uniqueIDs, T &result)
template<class T >
static bool PythonDetails (const std::string &ID, const std::string &key, const std::string &url, const std::string &action, const std::string &pathSettings, T &result)
static void VFSDirEntriesToCFileItemList (int num_entries, VFSDirEntry *entries, CFileItemList &items)
Variables
static constexpr const std::array< TypeMapping, 40 > types
constexpr const char * KODI_ADDON_DEFAULT_LANGUAGE_CODE = "en_GB"
static const std::set< AddonType > dependencyTypes
const int AUTO_UPDATES_ON = 0
const int AUTO_UPDATES_NOTIFY = 1
const int AUTO_UPDATES_NEVER = 2
const std::vector< AddonType > ADDONS_TO_CACHE = {AddonType::GAMEDLL}
constexpr const char * ADDON_SETTING_INSTANCE_GROUP = "kodi_addon_instance"
constexpr const char * ADDON_SETTING_INSTANCE_NAME_VALUE = "kodi_addon_instance_name"
constexpr const char * ADDON_SETTING_INSTANCE_ENABLED_VALUE = "kodi_addon_instance_enabled"
constexpr AddonInstanceId ADDON_SINGLETON_INSTANCE_ID = 0
Identifier denoting default add-on instance.
constexpr AddonInstanceId ADDON_FIRST_INSTANCE_ID = 1
Identifier denoting initial first add-on instance.
constexpr AddonInstanceId ADDON_INSTANCE_ID_UNUSED = ADDON_SINGLETON_INSTANCE_ID
Identifier denoting add-on instance id as unused.
constexpr AddonInstanceId ADDON_SETTINGS_ID = ADDON_SINGLETON_INSTANCE_ID
Identifier denoting default add-on settings.xml.
constexpr char const * ORIGIN_SYSTEM = "b6a50484-93a0-4afb-a01c-8d17e059feda"
static const ContentMapping content []
Typedef Documentation
ADDON_GET_INTERFACE_FN
typedef void *(* ADDON::ADDON_GET_INTERFACE_FN) (const std::string &name, const std::string &version)
ADDON_INFO_LIST
using ADDON::ADDON_INFO_LIST = typedef std::map<std::string, AddonInfoPtr>
ADDON_INSTANCE_HANDLER
using ADDON::ADDON_INSTANCE_HANDLER = typedef void*
Addon instance handler, used as identify for std::map to find related addon instance. This class itself not accessed here.
Todo:
As long game addon system use CAddonDll itself and not IAddonInstanceHandler as parent, is the set of this as "void*" needed. After game system is changed should by this also changed to "const IAddonInstanceHandler*" or direct in map below.
AddonDllPtr
typedef std::shared_ptr< CAddonDll > ADDON::AddonDllPtr
AddonInfoPtr
typedef std::shared_ptr< CAddonInfo > ADDON::AddonInfoPtr
AddonInfos
typedef std::vector<AddonInfoPtr> ADDON::AddonInfos
AddonInstanceId
typedef uint32_t ADDON::AddonInstanceId
AddonPtr
typedef std::shared_ptr< IAddon > ADDON::AddonPtr
AddonWithUpdate
typedef std::pair< std::shared_ptr< IAddon >, std::shared_ptr< IAddon > > ADDON::AddonWithUpdate
ArtMap
typedef std::map< std::string, std::string > ADDON::ArtMap
BinaryAddonBasePtr
typedef std::shared_ptr< CBinaryAddonBase > ADDON::BinaryAddonBasePtr
ContentPathMap
typedef std::map<std::string, std::vector<std::string> > ADDON::ContentPathMap
CSkinSettingBoolPtr
typedef std::shared_ptr<CSkinSettingBool> ADDON::CSkinSettingBoolPtr
CSkinSettingPtr
typedef std::shared_ptr<CSkinSetting> ADDON::CSkinSettingPtr
CSkinSettingStringPtr
typedef std::shared_ptr<CSkinSettingString> ADDON::CSkinSettingStringPtr
EXT_ELEMENTS
typedef std::vector<std::pair<std::string, CAddonExtensions> > ADDON::EXT_ELEMENTS
EXT_VALUE
typedef std::vector<std::pair<std::string, SExtValue> > ADDON::EXT_VALUE
EXT_VALUES
typedef std::vector<std::pair<std::string, CExtValues> > ADDON::EXT_VALUES
InfoMap
typedef std::map< std::string, std::string > ADDON::InfoMap
RepositoryDirList
typedef std::vector<RepositoryDirInfo> ADDON::RepositoryDirList
RepositoryPtr
typedef std::shared_ptr< CRepository > ADDON::RepositoryPtr
ScraperPtr
typedef std::shared_ptr<CScraper> ADDON::ScraperPtr
VECADDONS
typedef std::vector< AddonPtr > ADDON::VECADDONS
VFSEntryPtr
typedef std::shared_ptr<CVFSEntry> ADDON::VFSEntryPtr
WebinterfaceType
typedef enum ADDON::WebinterfaceType ADDON::WebinterfaceType
Enumeration Type Documentation
AddonCheckType
enum class ADDON::AddonCheckType : bool strong
Enumerator
OUTDATED_ADDONS
AVAILABLE_UPDATES
AddonDisabledReason
enum class ADDON::AddonDisabledReason strong
Enumerator
NONE
Special reason for returning all disabled addons.
Only used as an actual value when an addon is enabled.
USER
INCOMPATIBLE
PERMANENT_FAILURE
AddonInstanceSupport
enum class ADDON::AddonInstanceSupport strong
Independent add-on instance support.
Used to be able to find out its instance path for the respective add-on types.
Enumerator
SUPPORT_NONE
If add-on type does not support instances.
SUPPORT_MANDATORY
If add-on type needs support for several instances individually.
SUPPORT_OPTIONAL
If add-on type can support several instances individually.
SUPPORT_SETTINGS
If add-on type supports multiple instances using independent settings.
AddonLifecycleState
enum class ADDON::AddonLifecycleState strong
Add-on state defined within addon.xml to report about the current addon lifecycle state.
E.g. the add-on is broken and can no longer be used.
XML examples:
<lifecyclestate type="broken" lang="en_GB">SOME TEXT</lifecyclestate>
Enumerator
NORMAL
Used if an add-on has no special lifecycle state which is the default state.
DEPRECATED
the add-on should be marked as deprecated but is still usable
BROKEN
the add-on should marked as broken in the repository
AddonOriginType
enum class ADDON::AddonOriginType strong
Enumerator
SYSTEM
The type of the origin of an addon.
Represents where an addon was installed from.
REPOSITORY
The addon is a system addon.
MANUAL
The addon origin is a repository.
AddonRepoUpdateMode
enum class ADDON::AddonRepoUpdateMode strong
Enumerator
OFFICIAL_ONLY
ANY_REPOSITORY
AddonType
enum class ADDON::AddonType strong
Enumerator
UNKNOWN
VISUALIZATION
SKIN
PVRDLL
INPUTSTREAM
GAMEDLL
PERIPHERALDLL
SCRIPT
SCRIPT_WEATHER
SUBTITLE_MODULE
SCRIPT_LYRICS
SCRAPER_ALBUMS
SCRAPER_ARTISTS
SCRAPER_MOVIES
SCRAPER_MUSICVIDEOS
SCRAPER_TVSHOWS
SCREENSAVER
PLUGIN
REPOSITORY
WEB_INTERFACE
SERVICE
AUDIOENCODER
CONTEXTMENU_ITEM
AUDIODECODER
RESOURCE_IMAGES
RESOURCE_LANGUAGE
RESOURCE_UISOUNDS
RESOURCE_GAMES
RESOURCE_FONT
VFS
IMAGEDECODER
SCRAPER_LIBRARY
SCRIPT_LIBRARY
SCRIPT_MODULE
GAME_CONTROLLER
VIDEOCODEC
VIDEO
virtual addon types
AUDIO
IMAGE
EXECUTABLE
GAME
MAX_TYPES
AddonUpdateRule
enum class ADDON::AddonUpdateRule strong
Reasons why an addon is not updateable.
Enumerator
ANY
used internally, not to be explicitly set
USER_DISABLED_AUTO_UPDATE
automatic updates disabled via AddonInfo dialog
PIN_OLD_VERSION
user downgraded to an older version
PIN_ZIP_INSTALL
user installed manually from zip
AllowCheckForUpdates
enum class ADDON::AllowCheckForUpdates : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
AutoUpdateJob
enum class ADDON::AutoUpdateJob : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
BackgroundJob
enum class ADDON::BackgroundJob : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
CheckAddonPath
enum class ADDON::CheckAddonPath strong
Enumerator
CHOICE_YES
CHOICE_NO
CheckIncompatible
enum class ADDON::CheckIncompatible : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
DependencyJob
enum class ADDON::DependencyJob : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
InstallModalPrompt
enum class ADDON::InstallModalPrompt : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
ModalJob
enum class ADDON::ModalJob : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
OnlyEnabled
enum class ADDON::OnlyEnabled : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
OnlyEnabledRootAddon
enum class ADDON::OnlyEnabledRootAddon : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
RecurseOrphaned
enum class ADDON::RecurseOrphaned : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
WebinterfaceType
enum ADDON::WebinterfaceType
Enumerator
WebinterfaceTypeStatic
WebinterfaceTypeWsgi
Function Documentation
CFileItemListToVFSDirEntries()
static void ADDON::CFileItemListToVFSDirEntries (VFSDirEntry * entries, const CFileItemList & items) static
References VFSDirEntry::folder, CDateTime::GetAsTime(), VFSDirEntry::label, CGUIListItem::m_bIsFolder, CFileItem::m_dateTime, CFileItem::m_dwSize, VFSDirEntry::path, VFSDirEntry::size, and CFileItemList::Size().
Referenced by ADDON::Interface_Filesystem::get_directory().
CheckScraperError()
static void ADDON::CheckScraperError (const TiXmlElement * pxeRoot) static
References XMLUtils::GetString().
Referenced by ADDON::CScraper::FindMovie(), ADDON::CScraper::NfoUrl(), and ADDON::CScraper::ResolveIDToUrl().
DetailsFromFileItem()
template<class T > static bool ADDON::DetailsFromFileItem (const CFileItem & , T &) static
Referenced by PythonDetails().
DetailsFromFileItem< CAlbum >()
template<> bool ADDON::DetailsFromFileItem< CAlbum > (const CFileItem & item, CAlbum & album)
References CAlbum::artistCredits, CVariant::asBoolean(), CVariant::asFloat(), CVariant::asInteger32(), CAlbum::bCompilation, CAlbum::fRating, FromArray(), FromString(), CAlbum::genre, CGUIListItem::GetLabel(), CGUIListItem::GetProperty(), CAlbum::iUserrating, CAlbum::iVotes, CAlbum::moods, ParseThumbs(), CArtistCredit::SetArtist(), CArtistCredit::SetMusicBrainzArtistID(), CAlbum::strAlbum, CAlbum::strArtistDesc, CAlbum::strLabel, CAlbum::strMusicBrainzAlbumID, CAlbum::strOrigReleaseDate, CAlbum::strReleaseDate, CAlbum::strReleaseGroupMBID, CAlbum::strReleaseStatus, CAlbum::strReview, CAlbum::strType, CAlbum::styles, CAlbum::themes, and CAlbum::thumbURL.
DetailsFromFileItem< CArtist >()
template<> bool ADDON::DetailsFromFileItem< CArtist > (const CFileItem & item, CArtist & artist)
References CScraperUrl::AddParsedUrl(), CVariant::asInteger32(), CArtist::discography, FromArray(), FromString(), CArtist::genre, CFanart::GetImageURL(), CGUIListItem::GetLabel(), CFanart::GetNumFanarts(), CFanart::GetPreviewURL(), CGUIListItem::GetProperty(), CArtist::instruments, CFanart::m_xml, ArtistVideoLinks::mbTrackID, CArtist::moods, ParseFanart(), ParseThumbs(), CDiscoAlbum::strAlbum, CArtist::strArtist, CArtist::strBiography, CArtist::strBorn, CArtist::strDied, CArtist::strDisambiguation, CArtist::strDisbanded, CArtist::strFormed, CArtist::strGender, CArtist::strMusicBrainzArtistID, CDiscoAlbum::strReleaseGroupMBID, CArtist::strType, CDiscoAlbum::strYear, CArtist::styles, ArtistVideoLinks::thumbURL, CArtist::thumbURL, ArtistVideoLinks::title, CFanart::Unpack(), CArtist::videolinks, ArtistVideoLinks::videoURL, and CArtist::yearsActive.
DetailsFromFileItem< CVideoInfoTag >()
template<> bool ADDON::DetailsFromFileItem< CVideoInfoTag > (const CFileItem & item, CVideoInfoTag & tag)
References CFileItem::GetVideoInfoTag(), and CFileItem::HasVideoInfoTag().
FromArray()
static std::vector< std::string > ADDON::FromArray (const CFileItem & item, const std::string & key, int sep) static
References CVariant::asString(), CGUIListItem::GetProperty(), and CServiceBroker::GetSettingsComponent().
Referenced by DetailsFromFileItem< CAlbum >(), and DetailsFromFileItem< CArtist >().
FromFileItem()
template<class T > static T ADDON::FromFileItem (const CFileItem & item) static
FromFileItem< CMusicAlbumInfo >()
template<> CMusicAlbumInfo ADDON::FromFileItem< CMusicAlbumInfo > (const CFileItem & item)
References CScraperUrl::AppendUrl(), CVariant::asFloat(), CVariant::asString(), CGUIListItem::GetArt(), CFileItem::GetDynPath(), CGUIListItem::GetLabel(), CGUIListItem::GetProperty(), and CGUIListItem::HasProperty().
FromFileItem< CMusicArtistInfo >()
template<> CMusicArtistInfo ADDON::FromFileItem< CMusicArtistInfo > (const CFileItem & item)
References CScraperUrl::AppendUrl(), CVariant::asString(), CFileItem::GetDynPath(), CGUIListItem::GetLabel(), CGUIListItem::GetProperty(), CServiceBroker::GetSettingsComponent(), and CGUIListItem::HasProperty().
FromFileItem< CScraperUrl >()
template<> CScraperUrl ADDON::FromFileItem< CScraperUrl > (const CFileItem & item)
References CScraperUrl::AppendUrl(), CVariant::asDouble(), CScraperUrl::General, CFileItem::GetDynPath(), CGUIListItem::GetLabel(), CGUIListItem::GetProperty(), CGUIListItem::HasProperty(), CScraperUrl::SUrlEntry::m_type, CScraperUrl::SUrlEntry::m_url, CScraperUrl::SetRelevance(), and CScraperUrl::SetTitle().
FromString()
static std::string ADDON::FromString (const CFileItem & item, const std::string & key) static
References CVariant::asString(), and CGUIListItem::GetProperty().
Referenced by DetailsFromFileItem< CAlbum >(), DetailsFromFileItem< CArtist >(), ParseFanart(), and ParseThumbs().
GetSettingValue()
template<class TSetting > bool ADDON::GetSettingValue (CAddon & addon, AddonInstanceId instanceId, const std::string & key, typename TSetting::Value & value)
References ADDON::CAddon::GetSettings(), ADDON::CAddon::HasSettings(), and value.
LoadManifest()
static bool ADDON::LoadManifest (std::set< std::string > & system, std::set< std::string > & optional) static
References XMLUtils::GetAttribute(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGERROR, and root.
Referenced by ADDON::CAddonMgr::Init().
OnPostInstall()
void ADDON::OnPostInstall (const AddonPtr & addon, bool update, bool modal)
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork().
OnPostUnInstall()
void ADDON::OnPostUnInstall (const AddonPtr & addon)
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::DoWork().
OnPreInstall()
void ADDON::OnPreInstall (const AddonPtr & addon)
Bug:
If primary extension point have changed we're calling the wrong method.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork().
OnPreUnInstall()
void ADDON::OnPreUnInstall (const AddonPtr & addon)
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::DoWork().
ParseFanart()
static std::string ADDON::ParseFanart (const CFileItem & item, int nFanart, const std::string & tag) static
References FromString(), and text.
Referenced by DetailsFromFileItem< CArtist >().
ParseThumbs()
static void ADDON::ParseThumbs (CScraperUrl & scurl, const CFileItem & item, int nThumbs, const std::string & tag) static
References CScraperUrl::AddParsedUrl(), and FromString().
Referenced by DetailsFromFileItem< CAlbum >(), and DetailsFromFileItem< CArtist >().
PythonDetails() [1/2]
template<class T > static bool ADDON::PythonDetails (const std::string & ID, const std::string & key, const std::string & url, const std::string & action, const std::string & pathSettings, const std::unordered_map< std::string, std::string > & uniqueIDs, T & result) static
References DetailsFromFileItem(), XFILE::CPluginDirectory::GetPluginResult(), ID, and CJSONVariantWriter::Write().
Referenced by ADDON::CScraper::GetAlbumDetails(), ADDON::CScraper::GetArtistDetails(), ADDON::CScraper::GetArtwork(), ADDON::CScraper::GetVideoDetails(), and PythonDetails().
PythonDetails() [2/2]
template<class T > static bool ADDON::PythonDetails (const std::string & ID, const std::string & key, const std::string & url, const std::string & action, const std::string & pathSettings, T & result) static
References ID, and PythonDetails().
PythonFind()
template<class T > static std::vector< T > ADDON::PythonFind (const std::string & ID, const std::map< std::string, std::string > & additionals) static
References XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::GetDirectory(), and ID.
RelevanceSortFunction()
static bool ADDON::RelevanceSortFunction (const CScraperUrl & left, const CScraperUrl & right) static
References CScraperUrl::GetRelevance(), left, and right.
Referenced by ADDON::CScraper::FindMovie().
ResolveDependencies()
static void ADDON::ResolveDependencies (const std::string & addonId, std::vector< std::string > & needed, std::vector< std::string > & missing) static
References CHOICE_NO, CServiceBroker::GetAddonMgr(), ResolveDependencies(), and UNKNOWN.
Referenced by ADDON::CAddonMgr::EnableAddon(), and ResolveDependencies().
ScraperTypeFromContent()
AddonType ADDON::ScraperTypeFromContent (const CONTENT_TYPE & content)
References content, CONTENT_ALBUMS, CONTENT_ARTISTS, CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_TVSHOWS, SCRAPER_ALBUMS, SCRAPER_ARTISTS, SCRAPER_MOVIES, SCRAPER_MUSICVIDEOS, SCRAPER_TVSHOWS, and UNKNOWN.
Referenced by CNfoFile::Create(), CMusicDatabase::GetScraper(), CGUIWindowMusicNav::ManageInfoProvider(), CGUIDialogContentSettings::OnSettingAction(), and ADDON::CScraper::Supports().
SetProgressIndicator()
static void ADDON::SetProgressIndicator (CRepositoryUpdateJob * job) static
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CProgressJob::SetProgressIndicators(), and WINDOW_DIALOG_EXT_PROGRESS.
Referenced by ADDON::CRepositoryUpdater::CheckForUpdates().
TranslateContent() [1/2]
std::string ADDON::TranslateContent (const CONTENT_TYPE & type, bool pretty)
References content, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), CVideoDatabase::CleanDatabase(), KODI::VIDEO::CVideoInfoScanner::DoScan(), CVideoDatabase::ExportToXML(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), ADDON::CScraper::FindMovie(), ADDON::CScraper::GetAlbumDetails(), ADDON::CScraper::GetArtistDetails(), ADDON::CScraper::GetArtwork(), CVideoDatabase::GetContentForPath(), CGUIDialogContextMenu::GetContextButtons(), ADDON::CScraper::GetEpisodeList(), CVideoDatabase::GetScraperForPath(), ADDON::CScraper::GetVideoDetails(), CVideoDatabase::ImportFromXML(), CGUIDialogContentSettings::OnSettingAction(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), CVideoDatabase::SetScraperForPath(), CGUIDialogContentSettings::SetupView(), and CVideoLibraryRefreshingJob::Work().
TranslateContent() [2/2]
CONTENT_TYPE ADDON::TranslateContent (const std::string & string)
References content, and CONTENT_NONE.
UpdateSettingValue()
template<class TSetting > bool ADDON::UpdateSettingValue (CAddon & addon, AddonInstanceId instanceId, const std::string & key, typename TSetting::Value value)
References ADDON::CAddon::GetSettings(), ADDON::CAddon::HasSettings(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and value.
VFSDirEntriesToCFileItemList()
static void ADDON::VFSDirEntriesToCFileItemList (int num_entries, VFSDirEntry * entries, CFileItemList & items) static
References CFileItemList::Add(), VFSDirEntry::date_time, VFSDirEntry::folder, label, name, VFSDirEntry::num_props, VFSDirEntry::size, and VFSDirEntry::title.
Referenced by ADDON::CVFSEntry::ContainsFiles(), and ADDON::CVFSEntry::GetDirectory().
Variable Documentation
ADDON_FIRST_INSTANCE_ID
constexpr AddonInstanceId ADDON::ADDON_FIRST_INSTANCE_ID = 1 constexpr
Identifier denoting initial first add-on instance.
Referenced by ADDON::CAddonInfo::GetKnownInstanceIds(), and PVR::CPVRClientUID::GetLegacyUID().
ADDON_INSTANCE_ID_UNUSED
constexpr AddonInstanceId ADDON::ADDON_INSTANCE_ID_UNUSED = ADDON_SINGLETON_INSTANCE_ID constexpr
Identifier denoting add-on instance id as unused.
See also
ADDON::IAddonInstanceHandler
ADDON_SETTING_INSTANCE_ENABLED_VALUE
constexpr const char* ADDON::ADDON_SETTING_INSTANCE_ENABLED_VALUE = "kodi_addon_instance_enabled" constexpr
Referenced by ADDON::CAddonSettings::AddInstanceSettings(), PVR::CPVRClient::IsEnabled(), and CGUIDialogAddonSettings::ShowForMultipleInstances().
ADDON_SETTING_INSTANCE_GROUP
constexpr const char* ADDON::ADDON_SETTING_INSTANCE_GROUP = "kodi_addon_instance" constexpr
Referenced by ADDON::CAddonSettings::AddInstanceSettings(), and ADDON::CAddonDll::TransferSettings().
ADDON_SETTING_INSTANCE_NAME_VALUE
constexpr const char* ADDON::ADDON_SETTING_INSTANCE_NAME_VALUE = "kodi_addon_instance_name" constexpr
Referenced by ADDON::CAddonSettings::AddInstanceSettings(), PVR::CPVRClient::GetFullClientName(), PVR::CPVRClient::GetInstanceName(), and CGUIDialogAddonSettings::ShowForMultipleInstances().
ADDON_SETTINGS_ID
constexpr AddonInstanceId ADDON::ADDON_SETTINGS_ID = ADDON_SINGLETON_INSTANCE_ID constexpr
Identifier denoting default add-on settings.xml.
All numbers greater than 0 denote add-on instances with an individual set of settings.
Referenced by ADDON::CAddon::CanHaveAddonOrInstanceSettings(), ADDON::CAddonDll::Create(), ADDON::CAddon::DeleteInstanceSettings(), ADDON::CAddonDll::Destroy(), ADDON::CAddon::InitSettings(), ADDON::Interface_Base::set_setting_bool(), ADDON::Interface_Base::set_setting_float(), ADDON::Interface_Base::set_setting_int(), ADDON::Interface_Base::set_setting_string(), ADDON::CSkinInfo::SettingsLoaded(), CGUIDialogAddonSettings::ShowForMultipleInstances(), ADDON::CAddonDll::TransferSettings(), and XBMCAddon::xbmcaddon::Addon::UpdateSettingInActiveDialog().
ADDON_SINGLETON_INSTANCE_ID
constexpr AddonInstanceId ADDON::ADDON_SINGLETON_INSTANCE_ID = 0 constexpr
Identifier denoting default add-on instance.
All numbers greater than 0 denote add-ons with support for multiple instances.
Referenced by PVR::CPVRChannelsPath::CPVRChannelsPath(), ADDON::CAddonInfo::GetKnownInstanceIds(), PVR::CPVRClient::IsEnabled(), TEST(), TEST(), and PVR::CPVRClients::UpdateClients().
ADDONS_TO_CACHE
const std::vector<AddonType> ADDON::ADDONS_TO_CACHE = {AddonType::GAMEDLL}
Referenced by ADDON::CBinaryAddonCache::OnEvent(), and ADDON::CBinaryAddonCache::Update().
AUTO_UPDATES_NEVER
const int ADDON::AUTO_UPDATES_NEVER = 2
Referenced by ADDON::CRepositoryUpdater::ScheduleUpdate().
AUTO_UPDATES_NOTIFY
const int ADDON::AUTO_UPDATES_NOTIFY = 1
Referenced by ADDON::CRepositoryUpdater::OnJobComplete().
AUTO_UPDATES_ON
const int ADDON::AUTO_UPDATES_ON = 0
Referenced by CApplication::Initialize(), ADDON::CRepositoryUpdater::OnJobComplete(), XFILE::OutdatedAddons(), XFILE::RootDirectory(), and CGUIDialogAddonInfo::UpdateControls().
content
const ContentMapping ADDON::content[] static
Initial value:
= {{"unknown", CONTENT_NONE, 231},
                                         {"albums", CONTENT_ALBUMS, 132},
                                         {"music", CONTENT_ALBUMS, 132},
                                         {"artists", CONTENT_ARTISTS, 133},
                                         {"movies", CONTENT_MOVIES, 20342},
                                         {"tvshows", CONTENT_TVSHOWS, 20343},
                                         {"musicvideos", CONTENT_MUSICVIDEOS, 20389}}
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), KODI::VIDEO::CVideoInfoScanner::AddVideoExtras(), CVideoDatabase::AnnounceRemove(), CVideoDatabase::AnnounceUpdate(), XFILE::CPluginDirectory::CheckExists(), CGUIWindowVideoBase::CheckFilterAdvanced(), KODI::VIDEO::ContentToMediaType(), KODI::VIDEO::ContentToVideoDbType(), ADDON::CPluginSource::CPluginSource(), CVideoDatabase::DeleteResumeBookMark(), ADDON::CAddonDatabaseSerializer::DeserializeExtensions(), KODI::VIDEO::CVideoInfoScanner::DoScan(), ADDON::Interface_Filesystem::get_content_type(), ADDON::Interface_Filesystem::get_mime_type(), JSONRPC::CAddonsOperations::GetAddons(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CVideoDatabase::GetItemsForPath(), CVideoDatabase::GetScraperForPath(), XFILE::CAddonsDirectory::GetScriptsAndPlugins(), XFILE::CAddonsDirectory::GetScriptsAndPlugins(), CVideoDatabase::ImportFromXML(), XFILE::CPluginDirectory::IsMediaLibraryScanningAllowed(), CGUIWindowVideoBase::LoadVideoInfo(), ADDON::CPluginSource::Provides(), ADDON::CAddonInfo::ProvidesSubContent(), ADDON::CAddonType::ProvidesSubContent(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), CNfoFile::Scrape(), ScraperTypeFromContent(), ADDON::CAddonDatabaseSerializer::SerializeExtensions(), CGUIDialogContentSettings::SetContent(), SetFile(), ADDON::CScraper::SetPathSettings(), ADDON::CAddonType::SetProvides(), ADDON::CPluginSource::SetProvides(), CVideoDatabase::SetScraperForPath(), CGUIDialogContentSettings::Show(), ADDON::CScraper::Supports(), ADDON::CPluginSource::Translate(), TranslateContent(), TranslateContent(), ADDON::CAddonInfo::TranslateSubContent(), CVideoDatabase::UpdateMovieTitle(), and CVideoDatabase::UpdateVideoSortTitle().
dependencyTypes
const std::set<AddonType> ADDON::dependencyTypes static
Initial value:
= {
    AddonType::SCRAPER_LIBRARY,
    AddonType::SCRIPT_LIBRARY,
    AddonType::SCRIPT_MODULE,
}
Referenced by ADDON::CAddonType::IsDependencyType().
KODI_ADDON_DEFAULT_LANGUAGE_CODE
constexpr const char* ADDON::KODI_ADDON_DEFAULT_LANGUAGE_CODE = "en_GB" constexpr
Defines the default language code used as fallback in case the requested language is not available. Used, for instance, to handle content from addon.xml.
Referenced by ADDON::CAddonInfoBuilder::GetTextList(), ADDON::CAddonInfo::GetTranslatedText(), and ADDON::CAddonInfoBuilder::ParseXML().
ORIGIN_SYSTEM
constexpr char const* ADDON::ORIGIN_SYSTEM = "b6a50484-93a0-4afb-a01c-8d17e059feda" constexpr
Referenced by ADDON::CAddonRepos::DoAddonUpdateCheck(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), ADDON::CAddonMgr::GetAddonOriginType(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetLabel(), ADDON::CAddonMgr::IsAddonInstalled(), ADDON::CAddonMgr::IsAddonInstalled(), ADDON::CAddonRepos::IsFromOfficialRepo(), ADDON::CAddonRepos::IsOfficialRepo(), CGUIDialogAddonInfo::OnInstall(), and ADDON::CAddonDatabase::SyncInstalled().
types
constexpr const std::array<TypeMapping, 40> ADDON::types static constexpr
Referenced by KODI::ADDONS::CExtsMimeSupportList::CExtsMimeSupportList(), XFILE::GenerateTypeListing(), ADDON::CAddonMgr::GetAddonInfos(), PVR::CPVRClients::GetTimerTypes(), ADDON::CAddonInfo::InstanceSupportType(), CGUIWindowAddonBrowser::SelectAddonID(), CGUIWindowAddonBrowser::SelectAddonID(), CGUIWindowAddonBrowser::SelectAddonID(), CGUIWindowAddonBrowser::SelectAddonID(), SetAddon(), ADDON::CAddonInfo::TranslateIconType(), ADDON::CAddonInfo::TranslateType(), and ADDON::CAddonInfo::TranslateType().