Kodi Documentation: KODI::WINDOWING::X11::CVideoSyncOML Class Reference
KODI::WINDOWING::X11::CVideoSyncOML Class Reference
#include <VideoSyncOML.h>
Public Member Functions
CVideoSyncOML (CVideoReferenceClock *clock, CWinSystemX11GLContext &winSystem)
bool Setup () override
void Run (CEvent &stopEvent) override
void Cleanup () override
float GetFps () override
void OnResetDisplay () override
Public Member Functions inherited from CVideoSync
CVideoSync (CVideoReferenceClock *clock)
virtual ~CVideoSync ()=default
virtual void RefreshChanged ()
Private Attributes
std::atomic_bool m_abort
CWinSystemX11GLContext & m_winSystem
Additional Inherited Members
Protected Attributes inherited from CVideoSync
float m_fps
CVideoReferenceClock * m_refClock
Private Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
virtual void OnLostDisplay ()
virtual void OnAppFocusChange (bool focus)
Constructor & Destructor Documentation
CVideoSyncOML()
KODI::WINDOWING::X11::CVideoSyncOML::CVideoSyncOML (CVideoReferenceClock * clock, CWinSystemX11GLContext & winSystem) inline explicit
Member Function Documentation
Cleanup()
void CVideoSyncOML::Cleanup () override virtual
Implements CVideoSync.
References m_winSystem, and KODI::WINDOWING::X11::CWinSystemX11::Unregister().
GetFps()
float CVideoSyncOML::GetFps () override virtual
Implements CVideoSync.
References CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CVideoSync::m_fps, and m_winSystem.
OnResetDisplay()
void CVideoSyncOML::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References m_abort.
Run()
void CVideoSyncOML::Run (CEvent & stopEvent) override virtual
Implements CVideoSync.
References CurrentHostCounter(), KODI::WINDOWING::X11::CWinSystemX11GLContext::GetVblankTiming(), m_abort, CVideoSync::m_refClock, m_winSystem, CEvent::Signaled(), and CVideoReferenceClock::UpdateClock().
Setup()
bool CVideoSyncOML::Setup () override virtual
Implements CVideoSync.
References CLog::Log(), LOGDEBUG, m_abort, and m_winSystem.
Member Data Documentation
m_abort
std::atomic_bool KODI::WINDOWING::X11::CVideoSyncOML::m_abort private
Referenced by OnResetDisplay(), Run(), and Setup().
m_winSystem
CWinSystemX11GLContext& KODI::WINDOWING::X11::CVideoSyncOML::m_winSystem private
Referenced by Cleanup(), GetFps(), Run(), and Setup().
The documentation for this class was generated from the following files:
VideoSyncOML.h
VideoSyncOML.cpp