Kodi Documentation: StringValidation Class Reference
StringValidation Class Reference
#include <StringValidation.h>
Public Types
typedef bool(* Validator) (const std::string &input, void *data)
Static Public Member Functions
static bool NonEmpty (const std::string &input, void *data)
static bool IsInteger (const std::string &input, void *data)
static bool IsPositiveInteger (const std::string &input, void *data)
static bool IsTime (const std::string &input, void *data)
Private Member Functions
StringValidation ()=default
Member Typedef Documentation
Validator
typedef bool(* StringValidation::Validator) (const std::string &input, void *data)
Constructor & Destructor Documentation
StringValidation()
StringValidation::StringValidation () private default
Member Function Documentation
IsInteger()
bool StringValidation::IsInteger (const std::string & input, void * data) static
IsPositiveInteger()
bool StringValidation::IsPositiveInteger (const std::string & input, void * data) static
Referenced by IsTime(), and KODI::PLAYLIST::CSmartPlaylistRule::ValidateMyRating().
IsTime()
bool StringValidation::IsTime (const std::string & input, void * data) static
References IsPositiveInteger().
NonEmpty()
static bool StringValidation::NonEmpty (const std::string & input, void * data) inline static
The documentation for this class was generated from the following files:
StringValidation.h
StringValidation.cpp