Kodi Documentation: XFILE::Pipe Class Reference
XFILE::Pipe Class Reference
#include <PipesManager.h>
Public Member Functions
Pipe (const std::string &name, int nMaxSize=PIPE_DEFAULT_MAX_SIZE)
virtual ~Pipe ()
const std::string & GetName ()
void AddRef ()
void DecRef ()
int RefCount ()
bool IsEmpty ()
int Read (char *buf, int nMaxSize, int nWaitMillis=-1)
bool Write (const char *buf, int nSize, int nWaitMillis=-1)
void Flush ()
void CheckStatus ()
void Close ()
void AddListener (IPipeListener *l)
void RemoveListener (IPipeListener *l)
void SetEof ()
bool IsEof ()
int GetAvailableRead ()
void SetOpenThreshold (int threshold)
Protected Attributes
bool m_bOpen
bool m_bReadyForRead
bool m_bEof
CRingBuffer m_buffer
std::string m_strPipeName
int m_nRefCount
int m_nOpenThreshold
CEvent m_readEvent
CEvent m_writeEvent
std::vector< XFILE::IPipeListener * > m_listeners
CCriticalSection m_lock
Constructor & Destructor Documentation
Pipe()
Pipe::Pipe (const std::string & name, int nMaxSize = PIPE_DEFAULT_MAX_SIZE)
References CRingBuffer::Create(), m_bEof, m_bOpen, m_bReadyForRead, m_buffer, m_nOpenThreshold, m_nRefCount, m_readEvent, m_strPipeName, m_writeEvent, name, PIPE_DEFAULT_MAX_SIZE, CEvent::Reset(), and CEvent::Set().
~Pipe()
Pipe::~Pipe () virtual default
Member Function Documentation
AddListener()
void Pipe::AddListener (IPipeListener * l)
References m_listeners, and m_lock.
Referenced by XFILE::CPipeFile::Open(), and XFILE::CPipeFile::OpenForWrite().
AddRef()
void Pipe::AddRef ()
References m_lock, and m_nRefCount.
Referenced by Read().
CheckStatus()
void Pipe::CheckStatus ()
References CRingBuffer::getMaxReadSize(), CRingBuffer::getMaxWriteSize(), m_bEof, m_bReadyForRead, m_buffer, m_nOpenThreshold, m_readEvent, m_writeEvent, CEvent::Reset(), and CEvent::Set().
Referenced by Flush(), Read(), and Write().
Close()
void Pipe::Close ()
References m_bOpen, m_lock, m_readEvent, m_writeEvent, and CEvent::Set().
Referenced by XFILE::PipesManager::ClosePipe().
DecRef()
void Pipe::DecRef ()
References m_lock, and m_nRefCount.
Referenced by XFILE::PipesManager::ClosePipe(), and Read().
Flush()
void Pipe::Flush ()
References CheckStatus(), CRingBuffer::Clear(), m_bEof, m_bOpen, m_bReadyForRead, m_buffer, and m_lock.
Referenced by XFILE::CPipeFile::Flush().
GetAvailableRead()
int Pipe::GetAvailableRead ()
References CRingBuffer::getMaxReadSize(), m_buffer, and m_lock.
Referenced by XFILE::CPipeFile::GetAvailableRead().
GetName()
const std::string & Pipe::GetName ()
References m_strPipeName.
Referenced by XFILE::PipesManager::ClosePipe(), and XFILE::CPipeFile::GetName().
IsEmpty()
bool Pipe::IsEmpty ()
References CRingBuffer::getMaxReadSize(), and m_buffer.
Referenced by XFILE::CPipeFile::IsEmpty(), and Read().
IsEof()
bool Pipe::IsEof ()
References m_bEof.
Referenced by XFILE::CPipeFile::IsEof().
Read()
int Pipe::Read (char * buf, int nMaxSize, int nWaitMillis = -1)
Read into the buffer from the Pipe the num of bytes asked for blocking forever (which happens to be 5 minutes in this case).
In the case where nWaitMillis is provided block for that number of milliseconds instead.
References AddRef(), CheckStatus(), DecRef(), CRingBuffer::getMaxReadSize(), IsEmpty(), m_bEof, m_bOpen, m_bReadyForRead, m_buffer, m_listeners, m_lock, m_readEvent, CRingBuffer::ReadData(), and CEvent::Wait().
Referenced by XFILE::CPipeFile::Read().
RefCount()
int Pipe::RefCount ()
References m_lock, and m_nRefCount.
Referenced by XFILE::PipesManager::ClosePipe().
RemoveListener()
void Pipe::RemoveListener (IPipeListener * l)
References m_listeners, and m_lock.
Referenced by XFILE::CPipeFile::Close().
SetEof()
void Pipe::SetEof ()
References m_bEof.
Referenced by XFILE::CPipeFile::SetEof().
SetOpenThreshold()
void Pipe::SetOpenThreshold (int threshold)
References m_nOpenThreshold.
Referenced by XFILE::CPipeFile::SetOpenThreshold().
Write()
bool Pipe::Write (const char * buf, int nSize, int nWaitMillis = -1)
Write into the Pipe from the buffer the num of bytes asked for blocking forever.
In the case where nWaitMillis is provided block for that number of milliseconds instead.
References CheckStatus(), CRingBuffer::getMaxWriteSize(), m_bOpen, m_buffer, m_listeners, m_lock, m_writeEvent, CEvent::Wait(), and CRingBuffer::WriteData().
Referenced by XFILE::CPipeFile::Write().
Member Data Documentation
m_bEof
bool XFILE::Pipe::m_bEof protected
Referenced by CheckStatus(), Flush(), IsEof(), Pipe(), Read(), and SetEof().
m_bOpen
bool XFILE::Pipe::m_bOpen protected
Referenced by Close(), Flush(), Pipe(), Read(), and Write().
m_bReadyForRead
bool XFILE::Pipe::m_bReadyForRead protected
Referenced by CheckStatus(), Flush(), Pipe(), and Read().
m_buffer
CRingBuffer XFILE::Pipe::m_buffer protected
Referenced by CheckStatus(), Flush(), GetAvailableRead(), IsEmpty(), Pipe(), Read(), and Write().
m_listeners
std::vector<XFILE::IPipeListener *> XFILE::Pipe::m_listeners protected
Referenced by AddListener(), Read(), RemoveListener(), and Write().
m_lock
CCriticalSection XFILE::Pipe::m_lock protected
Referenced by AddListener(), AddRef(), Close(), DecRef(), Flush(), GetAvailableRead(), Read(), RefCount(), RemoveListener(), and Write().
m_nOpenThreshold
int XFILE::Pipe::m_nOpenThreshold protected
Referenced by CheckStatus(), Pipe(), and SetOpenThreshold().
m_nRefCount
int XFILE::Pipe::m_nRefCount protected
Referenced by AddRef(), DecRef(), Pipe(), and RefCount().
m_readEvent
CEvent XFILE::Pipe::m_readEvent protected
Referenced by CheckStatus(), Close(), Pipe(), and Read().
m_strPipeName
std::string XFILE::Pipe::m_strPipeName protected
Referenced by GetName(), and Pipe().
m_writeEvent
CEvent XFILE::Pipe::m_writeEvent protected
Referenced by CheckStatus(), Close(), Pipe(), and Write().
The documentation for this class was generated from the following files:
PipesManager.h
PipesManager.cpp