Kodi Documentation: PERIPHERALS::CAddonButtonMap Class Reference
PERIPHERALS::CAddonButtonMap Class Reference
#include <AddonButtonMap.h>
Public Member Functions
CAddonButtonMap (CPeripheral *device, const std::weak_ptr< CPeripheralAddon > &addon, const std::string &strControllerId, CPeripherals &manager)
~CAddonButtonMap (void) override
std::string ControllerID (void) const override
The add-on ID of the game controller associated with this button map.
std::string Location (void) const override
The Location of the peripheral associated with this button map.
bool Load (void) override
Load the button map into memory.
void Reset (void) override
Reset the button map to its defaults, or clear button map if no defaults.
bool IsEmpty (void) const override
Check if the button map is empty.
std::string GetAppearance () const override
Get the ID of the controller profile that best represents the appearance of the peripheral.
bool SetAppearance (const std::string &controllerId) const override
Set the ID of the controller that best represents the appearance of the peripheral.
bool GetFeature (const KODI::JOYSTICK::CDriverPrimitive &primitive, KODI::JOYSTICK::FeatureName &feature) override
Get the feature associated with a driver primitive.
KODI::JOYSTICK::FEATURE_TYPE GetFeatureType (const KODI::JOYSTICK::FeatureName &feature) override
Get the type of the feature for the given name.
bool GetScalar (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::CDriverPrimitive &primitive) override
Get the driver primitive for a scalar feature.
void AddScalar (const KODI::JOYSTICK::FeatureName &feature, const KODI::JOYSTICK::CDriverPrimitive &primitive) override
Add or update a scalar feature.
bool GetAnalogStick (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::ANALOG_STICK_DIRECTION direction, KODI::JOYSTICK::CDriverPrimitive &primitive) override
Get an analog stick direction from the button map.
void AddAnalogStick (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::ANALOG_STICK_DIRECTION direction, const KODI::JOYSTICK::CDriverPrimitive &primitive) override
Add or update an analog stick direction.
bool GetRelativePointer (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::RELATIVE_POINTER_DIRECTION direction, KODI::JOYSTICK::CDriverPrimitive &primitive) override
Get a relative pointer direction from the button map.
void AddRelativePointer (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::RELATIVE_POINTER_DIRECTION direction, const KODI::JOYSTICK::CDriverPrimitive &primitive) override
Add or update a relative pointer direction.
bool GetAccelerometer (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::CDriverPrimitive &positiveX, KODI::JOYSTICK::CDriverPrimitive &positiveY, KODI::JOYSTICK::CDriverPrimitive &positiveZ) override
Get an accelerometer from the button map.
void AddAccelerometer (const KODI::JOYSTICK::FeatureName &feature, const KODI::JOYSTICK::CDriverPrimitive &positiveX, const KODI::JOYSTICK::CDriverPrimitive &positiveY, const KODI::JOYSTICK::CDriverPrimitive &positiveZ) override
Get or update an accelerometer.
bool GetWheel (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::WHEEL_DIRECTION direction, KODI::JOYSTICK::CDriverPrimitive &primitive) override
Get a wheel direction from the button map.
void AddWheel (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::WHEEL_DIRECTION direction, const KODI::JOYSTICK::CDriverPrimitive &primitive) override
Add or update a wheel direction.
bool GetThrottle (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::THROTTLE_DIRECTION direction, KODI::JOYSTICK::CDriverPrimitive &primitive) override
Get a throttle direction from the button map.
void AddThrottle (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::THROTTLE_DIRECTION direction, const KODI::JOYSTICK::CDriverPrimitive &primitive) override
Add or update a throttle direction.
bool GetKey (const KODI::JOYSTICK::FeatureName &feature, KODI::JOYSTICK::CDriverPrimitive &primitive) override
Get the driver primitive for a keyboard key.
void AddKey (const KODI::JOYSTICK::FeatureName &feature, const KODI::JOYSTICK::CDriverPrimitive &primitive) override
Add or update a key.
void SetIgnoredPrimitives (const std::vector< KODI::JOYSTICK::CDriverPrimitive > &primitives) override
Set a list of driver primitives to be ignored.
bool IsIgnored (const KODI::JOYSTICK::CDriverPrimitive &primitive) override
Check if a primitive is in the list of primitives to be ignored.
bool GetAxisProperties (unsigned int axisIndex, int &center, unsigned int &range) override
Get the properties of an axis.
void SaveButtonMap () override
Save the button map.
void RevertButtonMap () override
Revert changes to the button map since the last time it was loaded or committed to disk.
Public Member Functions inherited from KODI::JOYSTICK::IButtonMap
virtual ~IButtonMap ()=default
Private Types
typedef std::map< KODI::JOYSTICK::CDriverPrimitive, KODI::JOYSTICK::FeatureName > DriverMap
typedef std::vector< KODI::JOYSTICK::CDriverPrimitive > JoystickPrimitiveVector
Static Private Member Functions
static DriverMap CreateLookupTable (const FeatureMap &features)
static JOYSTICK_FEATURE_PRIMITIVE GetAnalogStickIndex (KODI::JOYSTICK::ANALOG_STICK_DIRECTION dir)
static JOYSTICK_FEATURE_PRIMITIVE GetRelativePointerIndex (KODI::JOYSTICK::RELATIVE_POINTER_DIRECTION dir)
static JOYSTICK_FEATURE_PRIMITIVE GetPrimitiveIndex (KODI::JOYSTICK::WHEEL_DIRECTION dir)
static JOYSTICK_FEATURE_PRIMITIVE GetPrimitiveIndex (KODI::JOYSTICK::THROTTLE_DIRECTION dir)
Private Attributes
CPeripheral *const m_device
const std::weak_ptr< CPeripheralAddon > m_addon
const std::string m_strControllerId
CPeripherals & m_manager
std::string m_controllerAppearance
FeatureMap m_features
DriverMap m_driverMap
JoystickPrimitiveVector m_ignoredPrimitives
CCriticalSection m_mutex
Member Typedef Documentation
DriverMap
typedef std::map<KODI::JOYSTICK::CDriverPrimitive, KODI::JOYSTICK::FeatureName> PERIPHERALS::CAddonButtonMap::DriverMap private
JoystickPrimitiveVector
typedef std::vector<KODI::JOYSTICK::CDriverPrimitive> PERIPHERALS::CAddonButtonMap::JoystickPrimitiveVector private
Constructor & Destructor Documentation
CAddonButtonMap()
CAddonButtonMap::CAddonButtonMap (CPeripheral * device, const std::weak_ptr< CPeripheralAddon > & addon, const std::string & strControllerId, CPeripherals & manager)
References m_addon.
~CAddonButtonMap()
CAddonButtonMap::~CAddonButtonMap (void) override
References m_addon.
Member Function Documentation
AddAccelerometer()
void CAddonButtonMap::AddAccelerometer (const KODI::JOYSTICK::FeatureName & feature, const KODI::JOYSTICK::CDriverPrimitive & positiveX, const KODI::JOYSTICK::CDriverPrimitive & positiveY, const KODI::JOYSTICK::CDriverPrimitive & positiveZ) override virtual
Get or update an accelerometer.
Parameters
feature Must be an accelerometer or this will return false
positiveX The semiaxis corresponding to the positive X direction
positiveY The semiaxis corresponding to the positive Y direction
positiveZ The semiaxis corresponding to the positive Z direction
The driver primitives must be mapped to a semiaxis or this function will fail.
Returns
True if the accelerometer was updated, false if unchanged or failure occurred
Implements KODI::JOYSTICK::IButtonMap.
References KODI::JOYSTICK::JOYSTICK, JOYSTICK_ACCELEROMETER_POSITIVE_X, JOYSTICK_ACCELEROMETER_POSITIVE_Y, JOYSTICK_ACCELEROMETER_POSITIVE_Z, JOYSTICK_FEATURE_TYPE_ACCELEROMETER, m_addon, m_device, m_strControllerId, kodi::addon::JoystickFeature::SetPrimitive(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
AddAnalogStick()
void CAddonButtonMap::AddAnalogStick (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::ANALOG_STICK_DIRECTION direction, const KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Add or update an analog stick direction.
Parameters
feature Must be an analog stick or this will return false
direction The direction being mapped
primitive The driver primitive for the specified analog stick and direction
Returns
True if the analog stick was updated, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
References GetAnalogStickIndex(), KODI::JOYSTICK::JOYSTICK, JOYSTICK_FEATURE_TYPE_ANALOG_STICK, Load(), m_addon, m_device, m_features, m_mutex, m_strControllerId, kodi::addon::JoystickFeature::Primitive(), kodi::addon::JoystickFeature::SetPrimitive(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
AddKey()
void CAddonButtonMap::AddKey (const KODI::JOYSTICK::FeatureName & feature, const KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Add or update a key.
Parameters
feature Must be a key
primitive The feature's driver primitive
Returns
True if the feature was updated, false if the feature is unchanged or failure occurs
Implements KODI::JOYSTICK::IButtonMap.
References JOYSTICK_FEATURE_TYPE_KEY, JOYSTICK_SCALAR_PRIMITIVE, m_addon, m_device, m_strControllerId, kodi::addon::JoystickFeature::SetPrimitive(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
AddRelativePointer()
void CAddonButtonMap::AddRelativePointer (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::RELATIVE_POINTER_DIRECTION direction, const KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Add or update a relative pointer direction.
Parameters
feature Must be a relative pointer or this will return false
direction The direction being mapped
primitive The driver primitive for the specified analog stick and direction
Returns
True if the analog stick was updated, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
References GetRelativePointerIndex(), KODI::JOYSTICK::JOYSTICK, JOYSTICK_FEATURE_TYPE_RELPOINTER, Load(), m_addon, m_device, m_features, m_mutex, m_strControllerId, kodi::addon::JoystickFeature::Primitive(), kodi::addon::JoystickFeature::SetPrimitive(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
AddScalar()
void CAddonButtonMap::AddScalar (const KODI::JOYSTICK::FeatureName & feature, const KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Add or update a scalar feature.
Parameters
feature Must be a scalar feature
primitive The feature's driver primitive
Returns
True if the feature was updated, false if the feature is unchanged or failure occurs
Implements KODI::JOYSTICK::IButtonMap.
References JOYSTICK_FEATURE_TYPE_MOTOR, JOYSTICK_FEATURE_TYPE_SCALAR, JOYSTICK_SCALAR_PRIMITIVE, m_addon, m_device, m_strControllerId, kodi::addon::JoystickFeature::SetPrimitive(), PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive(), and KODI::JOYSTICK::CDriverPrimitive::Type().
AddThrottle()
void CAddonButtonMap::AddThrottle (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::THROTTLE_DIRECTION direction, const KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Add or update a throttle direction.
Parameters
feature Must be a throttle or this will return false
direction The direction being mapped
primitive The driver primitive for the specified analog stick and direction
Returns
True if the analog stick was updated, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
References GetPrimitiveIndex(), KODI::JOYSTICK::JOYSTICK, JOYSTICK_FEATURE_TYPE_THROTTLE, Load(), m_addon, m_device, m_features, m_mutex, m_strControllerId, kodi::addon::JoystickFeature::Primitive(), kodi::addon::JoystickFeature::SetPrimitive(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
AddWheel()
void CAddonButtonMap::AddWheel (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::WHEEL_DIRECTION direction, const KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Add or update a wheel direction.
Parameters
feature Must be a wheel or this will return false
direction The direction being mapped
primitive The driver primitive for the specified analog stick and direction
Returns
True if the analog stick was updated, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
References GetPrimitiveIndex(), KODI::JOYSTICK::JOYSTICK, JOYSTICK_FEATURE_TYPE_WHEEL, Load(), m_addon, m_device, m_features, m_mutex, m_strControllerId, kodi::addon::JoystickFeature::Primitive(), kodi::addon::JoystickFeature::SetPrimitive(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
ControllerID()
std::string PERIPHERALS::CAddonButtonMap::ControllerID (void) const inline override virtual
The add-on ID of the game controller associated with this button map.
The controller ID provided by the implementation serves as the context for the feature names below.
Returns
The ID of this button map's game controller add-on
Implements KODI::JOYSTICK::IButtonMap.
References m_strControllerId.
CreateLookupTable()
CAddonButtonMap::DriverMap CAddonButtonMap::CreateLookupTable (const FeatureMap & features) static private
References KODI::JOYSTICK::CDriverPrimitive::Index(), KODI::JOYSTICK::JOYSTICK, JOYSTICK_ACCELEROMETER_POSITIVE_X, JOYSTICK_ACCELEROMETER_POSITIVE_Y, JOYSTICK_ACCELEROMETER_POSITIVE_Z, JOYSTICK_ANALOG_STICK_DOWN, JOYSTICK_ANALOG_STICK_LEFT, JOYSTICK_ANALOG_STICK_RIGHT, JOYSTICK_ANALOG_STICK_UP, JOYSTICK_FEATURE_TYPE_ACCELEROMETER, JOYSTICK_FEATURE_TYPE_ANALOG_STICK, JOYSTICK_FEATURE_TYPE_KEY, JOYSTICK_FEATURE_TYPE_RELPOINTER, JOYSTICK_FEATURE_TYPE_SCALAR, JOYSTICK_FEATURE_TYPE_THROTTLE, JOYSTICK_FEATURE_TYPE_WHEEL, JOYSTICK_RELPOINTER_DOWN, JOYSTICK_RELPOINTER_LEFT, JOYSTICK_RELPOINTER_RIGHT, JOYSTICK_RELPOINTER_UP, JOYSTICK_SCALAR_PRIMITIVE, JOYSTICK_THROTTLE_DOWN, JOYSTICK_THROTTLE_UP, JOYSTICK_WHEEL_LEFT, JOYSTICK_WHEEL_RIGHT, kodi::addon::JoystickFeature::Primitive(), KODI::JOYSTICK::CDriverPrimitive::SemiAxisDirection(), PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive(), and kodi::addon::JoystickFeature::Type().
Referenced by Load().
GetAccelerometer()
bool CAddonButtonMap::GetAccelerometer (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::CDriverPrimitive & positiveX, KODI::JOYSTICK::CDriverPrimitive & positiveY, KODI::JOYSTICK::CDriverPrimitive & positiveZ) override virtual
Get an accelerometer from the button map.
Parameters
feature Must be an accelerometer or this will return false
positiveX The semiaxis mapped to the positive X direction (possibly unknown)
positiveY The semiaxis mapped to the positive Y direction (possibly unknown)
positiveZ The semiaxis mapped to the positive Z direction (possibly unknown)
Returns
True if the feature resolved to an accelerometer with at least 1 known axis
Implements KODI::JOYSTICK::IButtonMap.
References JOYSTICK_ACCELEROMETER_POSITIVE_X, JOYSTICK_ACCELEROMETER_POSITIVE_Y, JOYSTICK_ACCELEROMETER_POSITIVE_Z, JOYSTICK_FEATURE_TYPE_ACCELEROMETER, m_features, m_mutex, kodi::addon::JoystickFeature::Primitive(), PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive(), and kodi::addon::JoystickFeature::Type().
GetAnalogStick()
bool CAddonButtonMap::GetAnalogStick (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::ANALOG_STICK_DIRECTION direction, KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Get an analog stick direction from the button map.
Parameters
feature Must be an analog stick or this will return false
direction The direction whose primitive is to be retrieved
[out] primitive The primitive mapped to the specified direction
Returns
True if the feature and direction resolved to a driver primitive
Implements KODI::JOYSTICK::IButtonMap.
References GetAnalogStickIndex(), KODI::JOYSTICK::CDriverPrimitive::IsValid(), JOYSTICK_FEATURE_TYPE_ANALOG_STICK, m_features, m_mutex, kodi::addon::JoystickFeature::Primitive(), PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive(), and kodi::addon::JoystickFeature::Type().
GetAnalogStickIndex()
JOYSTICK_FEATURE_PRIMITIVE CAddonButtonMap::GetAnalogStickIndex (KODI::JOYSTICK::ANALOG_STICK_DIRECTION dir) static private
References KODI::JOYSTICK::JOYSTICK, JOYSTICK_ANALOG_STICK_DOWN, JOYSTICK_ANALOG_STICK_LEFT, JOYSTICK_ANALOG_STICK_RIGHT, and JOYSTICK_ANALOG_STICK_UP.
Referenced by AddAnalogStick(), and GetAnalogStick().
GetAppearance()
std::string CAddonButtonMap::GetAppearance () const override virtual
Get the ID of the controller profile that best represents the appearance of the peripheral.
Returns
The controller ID, or empty if the appearance is unknown
Implements KODI::JOYSTICK::IButtonMap.
References m_controllerAppearance, and m_mutex.
GetAxisProperties()
bool CAddonButtonMap::GetAxisProperties (unsigned int axisIndex, int & center, unsigned int & range) override virtual
Get the properties of an axis.
Parameters
axisIndex The index of the axis to check
center[out] The center, if known
range[out] The range, if known
Returns
True if the properties are known, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
References center, KODI::JOYSTICK::CDriverPrimitive::Center(), KODI::JOYSTICK::CDriverPrimitive::Index(), m_driverMap, m_mutex, KODI::JOYSTICK::CDriverPrimitive::Range(), and KODI::JOYSTICK::CDriverPrimitive::Type().
GetFeature()
bool CAddonButtonMap::GetFeature (const KODI::JOYSTICK::CDriverPrimitive & primitive, KODI::JOYSTICK::FeatureName & feature) override virtual
Get the feature associated with a driver primitive.
Multiple primitives can be mapped to the same feature. For example, analog sticks use one primitive for each direction.
Parameters
primitive The driver primitive
feature The name of the resolved joystick feature, or invalid if false is returned
Returns
True if the driver primitive is associated with a feature, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
References m_driverMap, and m_mutex.
GetFeatureType()
FEATURE_TYPE CAddonButtonMap::GetFeatureType (const KODI::JOYSTICK::FeatureName & feature) override virtual
Get the type of the feature for the given name.
Parameters
feature The feature to look up
Returns
The feature's type
Implements KODI::JOYSTICK::IButtonMap.
References m_features, m_mutex, and PERIPHERALS::CPeripheralAddonTranslator::TranslateFeatureType().
GetKey()
bool CAddonButtonMap::GetKey (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Get the driver primitive for a keyboard key.
Parameters
feature Must be a key
primitive The resolved driver primitive
Returns
True if the feature resolved to a driver primitive, false if the feature didn't resolve or isn't a scalar feature
Implements KODI::JOYSTICK::IButtonMap.
References JOYSTICK_FEATURE_TYPE_KEY, JOYSTICK_SCALAR_PRIMITIVE, m_features, m_mutex, kodi::addon::JoystickFeature::Primitive(), PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive(), and kodi::addon::JoystickFeature::Type().
GetPrimitiveIndex() [1/2]
JOYSTICK_FEATURE_PRIMITIVE CAddonButtonMap::GetPrimitiveIndex (KODI::JOYSTICK::THROTTLE_DIRECTION dir) static private
References KODI::JOYSTICK::JOYSTICK, JOYSTICK_THROTTLE_DOWN, and JOYSTICK_THROTTLE_UP.
GetPrimitiveIndex() [2/2]
JOYSTICK_FEATURE_PRIMITIVE CAddonButtonMap::GetPrimitiveIndex (KODI::JOYSTICK::WHEEL_DIRECTION dir) static private
References KODI::JOYSTICK::JOYSTICK, JOYSTICK_WHEEL_LEFT, and JOYSTICK_WHEEL_RIGHT.
Referenced by AddThrottle(), AddWheel(), GetThrottle(), and GetWheel().
GetRelativePointer()
bool CAddonButtonMap::GetRelativePointer (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::RELATIVE_POINTER_DIRECTION direction, KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Get a relative pointer direction from the button map.
Parameters
feature Must be a relative pointer stick or this will return false
direction The direction whose primitive is to be retrieved
[out] primitive The primitive mapped to the specified direction
Returns
True if the feature and direction resolved to a driver primitive
Implements KODI::JOYSTICK::IButtonMap.
References GetRelativePointerIndex(), KODI::JOYSTICK::CDriverPrimitive::IsValid(), JOYSTICK_FEATURE_TYPE_RELPOINTER, m_features, m_mutex, kodi::addon::JoystickFeature::Primitive(), PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive(), and kodi::addon::JoystickFeature::Type().
GetRelativePointerIndex()
JOYSTICK_FEATURE_PRIMITIVE CAddonButtonMap::GetRelativePointerIndex (KODI::JOYSTICK::RELATIVE_POINTER_DIRECTION dir) static private
References KODI::JOYSTICK::JOYSTICK, JOYSTICK_RELPOINTER_DOWN, JOYSTICK_RELPOINTER_LEFT, JOYSTICK_RELPOINTER_RIGHT, and JOYSTICK_RELPOINTER_UP.
Referenced by AddRelativePointer(), and GetRelativePointer().
GetScalar()
bool CAddonButtonMap::GetScalar (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Get the driver primitive for a scalar feature.
When a feature can be represented by a single driver primitive, it is called a scalar feature.
This includes buttons and triggers, because they can be mapped to a single button/hat/semiaxis
This does not include analog sticks, because they require two axes and four driver primitives (one for each semiaxis)
Parameters
feature Must be a scalar feature (a feature that only requires a single driver primitive)
primitive The resolved driver primitive
Returns
True if the feature resolved to a driver primitive, false if the feature didn't resolve or isn't a scalar feature
Implements KODI::JOYSTICK::IButtonMap.
References JOYSTICK_FEATURE_TYPE_MOTOR, JOYSTICK_FEATURE_TYPE_SCALAR, JOYSTICK_SCALAR_PRIMITIVE, m_features, m_mutex, kodi::addon::JoystickFeature::Primitive(), PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive(), and kodi::addon::JoystickFeature::Type().
GetThrottle()
bool CAddonButtonMap::GetThrottle (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::THROTTLE_DIRECTION direction, KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Get a throttle direction from the button map.
Parameters
feature Must be a throttle or this will return false
direction The direction whose primitive is to be retrieved
[out] primitive The primitive mapped to the specified direction
Returns
True if the feature and direction resolved to a driver primitive
Implements KODI::JOYSTICK::IButtonMap.
References GetPrimitiveIndex(), KODI::JOYSTICK::CDriverPrimitive::IsValid(), JOYSTICK_FEATURE_TYPE_THROTTLE, m_features, m_mutex, kodi::addon::JoystickFeature::Primitive(), PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive(), and kodi::addon::JoystickFeature::Type().
GetWheel()
bool CAddonButtonMap::GetWheel (const KODI::JOYSTICK::FeatureName & feature, KODI::JOYSTICK::WHEEL_DIRECTION direction, KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Get a wheel direction from the button map.
Parameters
feature Must be a wheel or this will return false
direction The direction whose primitive is to be retrieved
[out] primitive The primitive mapped to the specified direction
Returns
True if the feature and direction resolved to a driver primitive
Implements KODI::JOYSTICK::IButtonMap.
References GetPrimitiveIndex(), KODI::JOYSTICK::CDriverPrimitive::IsValid(), JOYSTICK_FEATURE_TYPE_WHEEL, m_features, m_mutex, kodi::addon::JoystickFeature::Primitive(), PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive(), and kodi::addon::JoystickFeature::Type().
IsEmpty()
bool CAddonButtonMap::IsEmpty (void) const override virtual
Check if the button map is empty.
Returns
True if the button map is empty, false if it has features
Implements KODI::JOYSTICK::IButtonMap.
References m_driverMap, and m_mutex.
IsIgnored()
bool CAddonButtonMap::IsIgnored (const KODI::JOYSTICK::CDriverPrimitive & primitive) override virtual
Check if a primitive is in the list of primitives to be ignored.
Parameters
primitive The primitive to check
Returns
True if the primitive should be ignored in the mapping process
Implements KODI::JOYSTICK::IButtonMap.
References m_ignoredPrimitives.
Load()
bool CAddonButtonMap::Load (void) override virtual
Load the button map into memory.
Returns
True if button map is ready to start translating buttons, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
References CreateLookupTable(), PERIPHERALS::CPeripherals::GetBusByType(), PERIPHERALS::CPeripheral::GetBusType(), PERIPHERALS::CPeripheral::Location(), CLog::Log(), LOGDEBUG, m_addon, m_controllerAppearance, m_device, m_driverMap, m_features, m_ignoredPrimitives, m_manager, m_mutex, m_strControllerId, and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitives().
Referenced by AddAnalogStick(), AddRelativePointer(), AddThrottle(), and AddWheel().
Location()
std::string CAddonButtonMap::Location (void) const override virtual
The Location of the peripheral associated with this button map.
Returns
The peripheral's location
Implements KODI::JOYSTICK::IButtonMap.
References PERIPHERALS::CPeripheral::Location(), and m_device.
Reset()
void CAddonButtonMap::Reset (void) override virtual
Reset the button map to its defaults, or clear button map if no defaults.
Implements KODI::JOYSTICK::IButtonMap.
References m_addon, m_device, and m_strControllerId.
Referenced by PERIPHERALS::CPeripherals::ResetButtonMaps().
RevertButtonMap()
void CAddonButtonMap::RevertButtonMap () override virtual
Revert changes to the button map since the last time it was loaded or committed to disk.
Implements KODI::JOYSTICK::IButtonMap.
References m_addon, and m_device.
SaveButtonMap()
void CAddonButtonMap::SaveButtonMap () override virtual
Save the button map.
Implements KODI::JOYSTICK::IButtonMap.
References m_addon, and m_device.
SetAppearance()
bool CAddonButtonMap::SetAppearance (const std::string & controllerId) const override virtual
Set the ID of the controller that best represents the appearance of the peripheral.
Parameters
controllerId The controller ID, or empty to unset the appearance
Returns
True if the appearance was set, false on error
Implements KODI::JOYSTICK::IButtonMap.
References m_addon, and m_device.
SetIgnoredPrimitives()
void CAddonButtonMap::SetIgnoredPrimitives (const std::vector< KODI::JOYSTICK::CDriverPrimitive > & primitives) override virtual
Set a list of driver primitives to be ignored.
This is necessary to prevent features from interfering with the button mapping process. This includes accelerometers, as well as PS4 triggers which send both a button press and an analog value.
Parameters
primitives The driver primitives to be ignored
Implements KODI::JOYSTICK::IButtonMap.
References m_addon, m_device, and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitives().
Member Data Documentation
m_addon
const std::weak_ptr<CPeripheralAddon> PERIPHERALS::CAddonButtonMap::m_addon private
Referenced by AddAccelerometer(), AddAnalogStick(), AddKey(), AddRelativePointer(), AddScalar(), AddThrottle(), AddWheel(), CAddonButtonMap(), Load(), Reset(), RevertButtonMap(), SaveButtonMap(), SetAppearance(), SetIgnoredPrimitives(), and ~CAddonButtonMap().
m_controllerAppearance
std::string PERIPHERALS::CAddonButtonMap::m_controllerAppearance private
Referenced by GetAppearance(), and Load().
m_device
CPeripheral* const PERIPHERALS::CAddonButtonMap::m_device private
Referenced by AddAccelerometer(), AddAnalogStick(), AddKey(), AddRelativePointer(), AddScalar(), AddThrottle(), AddWheel(), Load(), Location(), Reset(), RevertButtonMap(), SaveButtonMap(), SetAppearance(), and SetIgnoredPrimitives().
m_driverMap
DriverMap PERIPHERALS::CAddonButtonMap::m_driverMap private
Referenced by GetAxisProperties(), GetFeature(), IsEmpty(), and Load().
m_features
FeatureMap PERIPHERALS::CAddonButtonMap::m_features private
Referenced by AddAnalogStick(), AddRelativePointer(), AddThrottle(), AddWheel(), GetAccelerometer(), GetAnalogStick(), GetFeatureType(), GetKey(), GetRelativePointer(), GetScalar(), GetThrottle(), GetWheel(), and Load().
m_ignoredPrimitives
JoystickPrimitiveVector PERIPHERALS::CAddonButtonMap::m_ignoredPrimitives private
Referenced by IsIgnored(), and Load().
m_manager
CPeripherals& PERIPHERALS::CAddonButtonMap::m_manager private
Referenced by Load().
m_mutex
CCriticalSection PERIPHERALS::CAddonButtonMap::m_mutex mutable private
Referenced by AddAnalogStick(), AddRelativePointer(), AddThrottle(), AddWheel(), GetAccelerometer(), GetAnalogStick(), GetAppearance(), GetAxisProperties(), GetFeature(), GetFeatureType(), GetKey(), GetRelativePointer(), GetScalar(), GetThrottle(), GetWheel(), IsEmpty(), and Load().
m_strControllerId
const std::string PERIPHERALS::CAddonButtonMap::m_strControllerId private
Referenced by AddAccelerometer(), AddAnalogStick(), AddKey(), AddRelativePointer(), AddScalar(), AddThrottle(), AddWheel(), ControllerID(), Load(), and Reset().
The documentation for this class was generated from the following files:
AddonButtonMap.h
AddonButtonMap.cpp