Kodi Documentation: CXBMCTinyXML Class Reference
CXBMCTinyXML Class Reference
#include <XBMCTinyXML.h>
Public Member Functions
CXBMCTinyXML ()
CXBMCTinyXML (const char *)
CXBMCTinyXML (const std::string &documentName)
CXBMCTinyXML (const std::string &documentName, const std::string &documentCharset)
bool LoadFile (TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool LoadFile (const char *, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool LoadFile (const std::string &_filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool LoadFile (const std::string &_filename, const std::string &documentCharset)
bool LoadFile (FILE *, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool SaveFile (const char *) const
bool SaveFile (const std::string &filename) const
bool Parse (const std::string &data, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool Parse (const std::string &data, const std::string &dataCharset)
const std::string & GetSuggestedCharset () const
const std::string & GetUsedCharset () const
Static Public Member Functions
static bool Test ()
Protected Member Functions
bool TryParse (const std::string &data, const std::string &tryDataCharset)
bool InternalParse (const std::string &rawdata, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Protected Attributes
std::string m_SuggestedCharset
std::string m_UsedCharset
Constructor & Destructor Documentation
CXBMCTinyXML() [1/4]
CXBMCTinyXML::CXBMCTinyXML ()
CXBMCTinyXML() [2/4]
CXBMCTinyXML::CXBMCTinyXML (const char * documentName) explicit
CXBMCTinyXML() [3/4]
CXBMCTinyXML::CXBMCTinyXML (const std::string & documentName) explicit
CXBMCTinyXML() [4/4]
CXBMCTinyXML::CXBMCTinyXML (const std::string & documentName, const std::string & documentCharset)
References m_SuggestedCharset.
Member Function Documentation
GetSuggestedCharset()
const std::string & CXBMCTinyXML::GetSuggestedCharset () const inline
References m_SuggestedCharset.
GetUsedCharset()
const std::string & CXBMCTinyXML::GetUsedCharset () const inline
References m_UsedCharset.
Referenced by CScraperUrl::Get().
InternalParse()
bool CXBMCTinyXML::InternalParse (const std::string & rawdata, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING) protected
References CRegExp::asciiOnly, data(), MAX_ENTITY_LENGTH, and CRegExp::RegFind().
Referenced by Parse(), and TryParse().
LoadFile() [1/5]
bool CXBMCTinyXML::LoadFile (const char * _filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
References LoadFile().
LoadFile() [2/5]
bool CXBMCTinyXML::LoadFile (const std::string & _filename, const std::string & documentCharset)
References LoadFile(), and m_SuggestedCharset.
LoadFile() [3/5]
bool CXBMCTinyXML::LoadFile (const std::string & _filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
References data(), Error, XFILE::FILE_PROPERTY_CONTENT_CHARSET, Parse(), and value.
LoadFile() [4/5]
bool CXBMCTinyXML::LoadFile (FILE * f, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
References BUFFER_SIZE, data(), f, and Parse().
LoadFile() [5/5]
bool CXBMCTinyXML::LoadFile (TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
References LoadFile(), and value.
Referenced by ADDON::anonymous_namespace{Skin.cpp}::GetFontsetsFromFile(), CVideoDatabase::ImportFromXML(), CMusicDatabase::ImportFromXML(), CMusicDatabase::ImportSongHistory(), CSettings::Initialize(), ADDON::CScraper::Load(), CGUIAudioManager::Load(), CProfileManager::Load(), CGUIColorManager::Load(), CSettings::Load(), CLangInfo::Load(), CScraperParser::Load(), CGUIColorManager::LoadColorsListFromXML(), CPlayerCoreFactory::LoadConfiguration(), CApplicationSkinHandling::LoadCustomWindows(), LoadFile(), LoadFile(), LoadFile(), ADDON::LoadManifest(), CProfileManager::LoadProfile(), ADDON::CAddon::LoadSettings(), ADDON::CAddon::LoadUserSettings(), CGUIWindow::LoadXML(), XFILE::CLibraryDirectory::LoadXML(), anonymous_namespace{GUIFontManager.cpp}::LoadXMLData(), CAdvancedSettings::ParseSettingsFile(), and TEST().
Parse() [1/2]
bool CXBMCTinyXML::Parse (const std::string & data, const std::string & dataCharset)
References data(), m_SuggestedCharset, and Parse().
Parse() [2/2]
bool CXBMCTinyXML::Parse (const std::string & data, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
References data(), CCharsetDetection::DetectXmlEncoding(), g_langInfo, InternalParse(), CUtf8Utils::isValidUtf8(), CLog::Log(), LOGWARNING, m_SuggestedCharset, m_UsedCharset, TryParse(), and value.
Referenced by anonymous_namespace{TestGUIControlFactory.cpp}::CGUITestColorManager::CGUITestColorManager(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), ADDON::CScraper::FindMovie(), CScraperUrl::Get(), ADDON::CScraper::GetAlbumDetails(), ADDON::CScraper::GetArtistDetails(), ADDON::CScraper::GetArtwork(), CNfoFile::GetDetails(), ADDON::CScraper::GetEpisodeList(), ADDON::CScraper::GetVideoDetails(), LoadFile(), LoadFile(), ADDON::CScraper::NfoUrl(), Parse(), CScraperUrl::ParseAndAppendUrlsFromEpisodeGuide(), CScraperUrl::ParseFromData(), KODI::PLAYLIST::CSmartPlaylist::readNameFromXml(), ADDON::CScraper::ResolveIDToUrl(), ADDON::CScraper::Run(), CVideoInfoTag::Save(), CAlbum::Save(), CArtist::Save(), CSettingsBase::SaveValuesToXml(), ADDON::CScraper::SetPathSettings(), Test(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
SaveFile() [1/2]
bool CXBMCTinyXML::SaveFile (const char * _filename) const
References SaveFile().
Referenced by CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), GUIFontManager::LoadUserFonts(), CProfileManager::Save(), CSettings::Save(), KODI::PLAYLIST::CSmartPlaylist::Save(), SaveFile(), CGUIControlProfiler::SaveResults(), and ADDON::CAddon::SaveSettings().
SaveFile() [2/2]
bool CXBMCTinyXML::SaveFile (const std::string & filename) const
Test()
bool CXBMCTinyXML::Test () static
References data(), Parse(), and root.
TryParse()
bool CXBMCTinyXML::TryParse (const std::string & data, const std::string & tryDataCharset) protected
References data(), Error, g_charsetConverter, InternalParse(), and m_UsedCharset.
Referenced by Parse().
Member Data Documentation
m_SuggestedCharset
std::string CXBMCTinyXML::m_SuggestedCharset protected
Referenced by CXBMCTinyXML(), GetSuggestedCharset(), LoadFile(), Parse(), and Parse().
m_UsedCharset
std::string CXBMCTinyXML::m_UsedCharset protected
Referenced by GetUsedCharset(), Parse(), and TryParse().
The documentation for this class was generated from the following files:
XBMCTinyXML.h
XBMCTinyXML.cpp