Kodi Documentation: CRenderCaptureDX Class Reference
CRenderCaptureDX Class Reference
#include <RenderCaptureDX.h>
Public Member Functions
CRenderCaptureDX ()
~CRenderCaptureDX () override
void BeginRender () override
void EndRender () override
void ReadOut () override
void OnDestroyDevice (bool fatal) override
void OnCreateDevice () override
CD3DTexture & GetTarget ()
Public Member Functions inherited from CRenderCapture
CRenderCapture ()=default
virtual ~CRenderCapture ()=default
virtual void * GetRenderBuffer ()
void SetState (ECAPTURESTATE state)
ECAPTURESTATE GetState ()
void SetUserState (ECAPTURESTATE state)
ECAPTURESTATE GetUserState ()
CEvent & GetEvent ()
void SetFlags (int flags)
int GetFlags ()
void SetWidth (unsigned int width)
void SetHeight (unsigned int height)
unsigned int GetWidth ()
unsigned int GetHeight ()
uint8_t * GetPixels () const
bool IsAsync ()
Public Member Functions inherited from ID3DResource
virtual ~ID3DResource ()
Private Member Functions
void SurfaceToBuffer ()
void CleanupDX ()
Private Attributes
unsigned int m_surfaceWidth {0}
unsigned int m_surfaceHeight {0}
Microsoft::WRL::ComPtr< ID3D11Query > m_query {nullptr}
CD3DTexture m_renderTex
CD3DTexture m_copyTex
Additional Inherited Members
Protected Member Functions inherited from CRenderCapture
bool UseOcclusionQuery ()
Protected Member Functions inherited from ID3DResource
void Register ()
void Unregister ()
Protected Attributes inherited from CRenderCapture
ECAPTURESTATE m_state {CAPTURESTATE_FAILED}
ECAPTURESTATE m_userState {CAPTURESTATE_FAILED}
int m_flags {0}
CEvent m_event
uint8_t * m_pixels {nullptr}
unsigned int m_width {0}
unsigned int m_height {0}
unsigned int m_bufferSize {0}
bool m_asyncSupported {false}
bool m_asyncChecked {false}
Protected Attributes inherited from ID3DResource
bool m_bRegistered = false
Constructor & Destructor Documentation
CRenderCaptureDX()
CRenderCaptureDX::CRenderCaptureDX ()
~CRenderCaptureDX()
CRenderCaptureDX::~CRenderCaptureDX () override
References CleanupDX(), and CRenderCapture::m_pixels.
Member Function Documentation
BeginRender()
void CRenderCaptureDX::BeginRender () override virtual
Implements CRenderCapture.
References CAPTUREFLAG_CONTINUOUS, CAPTURESTATE_FAILED, CD3DTexture::Create(), FAILED, CWIN32Util::FormatHRESULT(), DX::DeviceResources::Get(), CLog::Log(), LOGERROR, LOGWARNING, CRenderCapture::m_asyncChecked, CRenderCapture::m_asyncSupported, CRenderCapture::m_bufferSize, m_copyTex, CRenderCapture::m_flags, CRenderCapture::m_height, CRenderCapture::m_pixels, m_query, m_renderTex, m_surfaceHeight, m_surfaceWidth, CRenderCapture::m_width, CD3DTexture::Release(), CRenderCapture::SetState(), and CRenderCapture::UseOcclusionQuery().
CleanupDX()
void CRenderCaptureDX::CleanupDX () private
References m_copyTex, m_query, m_renderTex, m_surfaceHeight, m_surfaceWidth, and CD3DTexture::Release().
Referenced by OnDestroyDevice(), and ~CRenderCaptureDX().
EndRender()
void CRenderCaptureDX::EndRender () override virtual
Implements CRenderCapture.
References CAPTUREFLAG_IMMEDIATELY, CAPTURESTATE_NEEDSREADOUT, DX::DeviceResources::Get(), CD3DTexture::Get(), m_copyTex, CRenderCapture::m_flags, m_query, m_renderTex, CRenderCapture::SetState(), and SurfaceToBuffer().
GetTarget()
CD3DTexture & CRenderCaptureDX::GetTarget () inline
References m_renderTex.
OnCreateDevice()
void CRenderCaptureDX::OnCreateDevice (void) inline override virtual
Implements ID3DResource.
OnDestroyDevice()
void CRenderCaptureDX::OnDestroyDevice (bool fatal) override virtual
Implements ID3DResource.
References CAPTURESTATE_FAILED, CleanupDX(), and CRenderCapture::SetState().
ReadOut()
void CRenderCaptureDX::ReadOut () override virtual
Reimplemented from CRenderCapture.
References DX::DeviceResources::Get(), CLog::Log(), LOGERROR, m_query, and SurfaceToBuffer().
SurfaceToBuffer()
void CRenderCaptureDX::SurfaceToBuffer () private
References CAPTURESTATE_DONE, CAPTURESTATE_FAILED, CD3DTexture::LockRect(), CLog::Log(), LOGERROR, m_copyTex, CRenderCapture::m_height, CRenderCapture::m_pixels, CRenderCapture::m_width, CRenderCapture::SetState(), and CD3DTexture::UnlockRect().
Referenced by EndRender(), and ReadOut().
Member Data Documentation
m_copyTex
CD3DTexture CRenderCaptureDX::m_copyTex private
Referenced by BeginRender(), CleanupDX(), EndRender(), and SurfaceToBuffer().
m_query
Microsoft::WRL::ComPtr<ID3D11Query> CRenderCaptureDX::m_query {nullptr} private
Referenced by BeginRender(), CleanupDX(), EndRender(), and ReadOut().
m_renderTex
CD3DTexture CRenderCaptureDX::m_renderTex private
Referenced by BeginRender(), CleanupDX(), EndRender(), and GetTarget().
m_surfaceHeight
unsigned int CRenderCaptureDX::m_surfaceHeight {0} private
Referenced by BeginRender(), and CleanupDX().
m_surfaceWidth
unsigned int CRenderCaptureDX::m_surfaceWidth {0} private
Referenced by BeginRender(), and CleanupDX().
The documentation for this class was generated from the following files:
RenderCaptureDX.h
RenderCaptureDX.cpp