Kodi Documentation: CFileExtensionProvider Class Reference
CFileExtensionProvider Class Reference
#include <FileExtensionProvider.h>
Public Member Functions
CFileExtensionProvider (ADDON::CAddonMgr &addonManager)
~CFileExtensionProvider ()
std::string GetPictureExtensions () const
Returns a list of picture extensions.
std::string GetMusicExtensions () const
Returns a list of music extensions.
std::string GetVideoExtensions () const
Returns a list of video extensions.
std::string GetSubtitleExtensions () const
Returns a list of subtitle extensions.
std::string GetDiscStubExtensions () const
Returns a list of disc stub extensions.
std::string GetFileFolderExtensions () const
Returns a file folder extensions.
bool EncodedHostName (const std::string &protocol) const
Returns whether a url protocol from add-ons use encoded hostnames.
bool CanOperateExtension (const std::string &path) const
Returns true if related provider can operate related file.
Private Member Functions
std::string GetAddonExtensions (ADDON::AddonType type) const
std::string GetAddonFileFolderExtensions (ADDON::AddonType type) const
void SetAddonExtensions ()
void SetAddonExtensions (ADDON::AddonType type)
void OnAddonEvent (const ADDON::AddonEvent &event)
Private Attributes
std::shared_ptr< CAdvancedSettings > m_advancedSettings
ADDON::CAddonMgr & m_addonManager
std::map< ADDON::AddonType, std::string > m_addonExtensions
std::map< ADDON::AddonType, std::string > m_addonFileFolderExtensions
std::vector< std::string > m_encoded
Constructor & Destructor Documentation
CFileExtensionProvider()
CFileExtensionProvider::CFileExtensionProvider (ADDON::CAddonMgr & addonManager)
References ADDON::CAddonMgr::Events(), m_addonManager, OnAddonEvent(), and SetAddonExtensions().
~CFileExtensionProvider()
CFileExtensionProvider::~CFileExtensionProvider ()
References ADDON::CAddonMgr::Events(), m_addonExtensions, m_addonManager, and m_advancedSettings.
Member Function Documentation
CanOperateExtension()
bool CFileExtensionProvider::CanOperateExtension (const std::string & path) const
Returns true if related provider can operate related file.
Note
Thought for cases e.g. by ISO, where can be a video or also a SACD.
Todo:
Improve this function to support all cases and not only audio decoder.
We expect that other addons can support the file, and return true if list empty.
Todo:
Check addons can also be types in conflict with Kodi's supported parts!
Warning
This part is really big ugly at the moment and as soon as possible add about other addons where works with extensions!!! Due to GetFileFolderExtensions() call from outside place before here, becomes it usable in this way, as there limited to AudioDecoder and VFS addons.
Check all found addons about support of asked file.
If no file extensions present, mark it as not supported.
References URIUtils::GetExtension(), KODI::ADDONS::CExtsMimeSupportList::GetExtensionSupportedAddonInfos(), CServiceBroker::GetExtsMimeSupportList(), and CServiceBroker::IsAddonInterfaceUp().
EncodedHostName()
bool CFileExtensionProvider::EncodedHostName (const std::string & protocol) const
Returns whether a url protocol from add-ons use encoded hostnames.
References m_encoded.
Referenced by URIUtils::HasParentInHostname().
GetAddonExtensions()
std::string CFileExtensionProvider::GetAddonExtensions (ADDON::AddonType type) const private
References m_addonExtensions.
Referenced by GetMusicExtensions(), GetPictureExtensions(), GetSubtitleExtensions(), and GetVideoExtensions().
GetAddonFileFolderExtensions()
std::string CFileExtensionProvider::GetAddonFileFolderExtensions (ADDON::AddonType type) const private
References m_addonFileFolderExtensions.
Referenced by GetFileFolderExtensions().
GetDiscStubExtensions()
std::string CFileExtensionProvider::GetDiscStubExtensions () const
Returns a list of disc stub extensions.
References m_advancedSettings.
Referenced by KODI::VIDEO::IsDiscStub().
GetFileFolderExtensions()
std::string CFileExtensionProvider::GetFileFolderExtensions () const
Returns a file folder extensions.
References GetAddonFileFolderExtensions().
GetMusicExtensions()
std::string CFileExtensionProvider::GetMusicExtensions () const
Returns a list of music extensions.
References GetAddonExtensions(), and m_advancedSettings.
Referenced by JSONRPC::CFileOperations::FillFileItemList(), JSONRPC::CFileOperations::GetDirectory(), CGUIViewStateWindowMusic::GetExtensions(), CSettingPath::GetMasking(), XBMCAddon::xbmc::getSupportedMedia(), ADDON::CAddonSettings::InitializeFromOldSettingPath(), KODI::MUSIC::IsAudio(), UPNP::CUPnPServer::OnBrowseDirectChildren(), URIUtils::RemoveExtension(), and TEST().
GetPictureExtensions()
std::string CFileExtensionProvider::GetPictureExtensions () const
Returns a list of picture extensions.
References GetAddonExtensions(), and m_advancedSettings.
Referenced by JSONRPC::CFileOperations::FillFileItemList(), JSONRPC::CFileOperations::GetDirectory(), CGUIViewStateWindowPictures::GetExtensions(), KODI::ART::GetLocalFanart(), CSettingPath::GetMasking(), CGUIControlButtonSetting::GetPath(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), XBMCAddon::xbmc::getSupportedMedia(), ADDON::CAddonSettings::InitializeFromOldSettingPath(), CPictureFolderImageFileLoader::Load(), CApplication::OnApplicationMessage(), UPNP::CUPnPServer::OnBrowseDirectChildren(), and URIUtils::RemoveExtension().
GetSubtitleExtensions()
std::string CFileExtensionProvider::GetSubtitleExtensions () const
Returns a list of subtitle extensions.
References GetAddonExtensions(), and m_advancedSettings.
Referenced by KODI::VIDEO::IsSubtitle(), URIUtils::RemoveExtension(), CUtil::ScanForExternalSubtitles(), and TEST().
GetVideoExtensions()
std::string CFileExtensionProvider::GetVideoExtensions () const
Returns a list of video extensions.
References GetAddonExtensions(), and m_advancedSettings.
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideoExtras(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), JSONRPC::CFileOperations::FillFileItemList(), JSONRPC::CFileOperations::GetDirectory(), CGUIViewStateWindowPictures::GetExtensions(), CGUIViewStateWindowVideo::GetExtensions(), CSettingPath::GetMasking(), XBMCAddon::xbmc::getSupportedMedia(), ADDON::CAddonSettings::InitializeFromOldSettingPath(), KODI::VIDEO::IsVideo(), UPNP::CUPnPServer::OnBrowseDirectChildren(), CGUIWindowVideoBase::OnItemInfo(), URIUtils::RemoveExtension(), CFileItemList::StackFolders(), and TEST().
OnAddonEvent()
void CFileExtensionProvider::OnAddonEvent (const ADDON::AddonEvent & event) private
References ADDON_TYPES, ADDON::AddonEvent::addonId, ADDON::CAddonMgr::HasType(), m_addonManager, and SetAddonExtensions().
Referenced by CFileExtensionProvider().
SetAddonExtensions() [1/2]
void CFileExtensionProvider::SetAddonExtensions () private
References ADDON_TYPES, and SetAddonExtensions().
Referenced by CFileExtensionProvider(), OnAddonEvent(), and SetAddonExtensions().
SetAddonExtensions() [2/2]
void CFileExtensionProvider::SetAddonExtensions (ADDON::AddonType type) private
References ADDON::CAddonMgr::GetAddonInfos(), CServiceBroker::GetExtsMimeSupportList(), KODI::ADDONS::CExtsMimeSupportList::GetSupportedAddonInfos(), m_addonExtensions, m_addonFileFolderExtensions, m_addonManager, and m_encoded.
Member Data Documentation
m_addonExtensions
std::map<ADDON::AddonType, std::string> CFileExtensionProvider::m_addonExtensions private
Referenced by GetAddonExtensions(), SetAddonExtensions(), and ~CFileExtensionProvider().
m_addonFileFolderExtensions
std::map<ADDON::AddonType, std::string> CFileExtensionProvider::m_addonFileFolderExtensions private
Referenced by GetAddonFileFolderExtensions(), and SetAddonExtensions().
m_addonManager
ADDON::CAddonMgr& CFileExtensionProvider::m_addonManager private
Referenced by CFileExtensionProvider(), OnAddonEvent(), SetAddonExtensions(), and ~CFileExtensionProvider().
m_advancedSettings
std::shared_ptr<CAdvancedSettings> CFileExtensionProvider::m_advancedSettings private
Referenced by GetDiscStubExtensions(), GetMusicExtensions(), GetPictureExtensions(), GetSubtitleExtensions(), GetVideoExtensions(), and ~CFileExtensionProvider().
m_encoded
std::vector<std::string> CFileExtensionProvider::m_encoded private
Referenced by EncodedHostName(), and SetAddonExtensions().
The documentation for this class was generated from the following files:
FileExtensionProvider.h
FileExtensionProvider.cpp