Kodi Documentation: CEventSource< Event > Class Template Reference
CEventSource< Event > Class Template Reference
#include <EventStream.h>
Public Member Functions
CEventSource ()
template<typename A >
void Publish (A event)
Public Member Functions inherited from CEventStream< Event >
template<typename A >
void Subscribe (A *owner, void(A::*fn)(const Event &))
template<typename A >
void Unsubscribe (A *obj)
Private Attributes
CJobQueue m_queue
Additional Inherited Members
Protected Attributes inherited from CEventStream< Event >
std::vector< std::shared_ptr< detail::ISubscription< Event > > > m_subscriptions
CCriticalSection m_criticalSection
Constructor & Destructor Documentation
CEventSource()
template<typename Event > CEventSource< Event >::CEventSource () inline explicit
Member Function Documentation
Publish()
template<typename Event > template<typename A > void CEventSource< Event >::Publish (A event) inline
References CEventStream< Event >::m_criticalSection, CEventSource< Event >::m_queue, CEventStream< Event >::m_subscriptions, and CJobQueue::Submit().
Referenced by PVR::CPVREpg::CheckPlayingEvent(), PVR::CPVREpgContainer::CheckPlayingEvents(), PVR::CPVREpgContainer::CreateChannelEpg(), PVR::CPVREpgContainer::DeleteSavedSearch(), PVR::CPVREpg::ForceUpdate(), PVR::CPVREpgContainer::Notify(), PVR::CPVRChannelGroup::OnSettingChanged(), PVR::CPVREpgContainer::PersistSavedSearch(), PVR::CPVREpgContainer::Process(), PVR::CPVRManager::PublishEvent(), PVR::CPVREpg::RemovedFromContainer(), PVR::CPVRChannelGroup::UpdateChannelNumbersFromAllChannelsGroup(), PVR::CPVREpg::UpdateEntries(), PVR::CPVREpg::UpdateEntry(), PVR::CPVREpgContainer::UpdateEPG(), and PVR::CPVRChannelGroup::UpdateGroupEntries().
Member Data Documentation
m_queue
template<typename Event > CJobQueue CEventSource< Event >::m_queue private
Referenced by CEventSource< Event >::Publish().
The documentation for this class was generated from the following file:
EventStream.h