Kodi Documentation: KODI::GAME::CGameClientStreams Class Reference
KODI::GAME::CGameClientStreams Class Reference
Games
#include <GameClientStreams.h>
Public Member Functions
CGameClientStreams (CGameClient &gameClient)
void Initialize (RETRO::IStreamManager &streamManager)
void Deinitialize ()
IGameClientStream * OpenStream (const game_stream_properties &properties)
void CloseStream (IGameClientStream *stream)
Private Member Functions
std::unique_ptr< IGameClientStream > CreateStream (GAME_STREAM_TYPE streamType) const
Private Attributes
CGameClient & m_gameClient
RETRO::IStreamManager * m_streamManager = nullptr
std::map< IGameClientStream *, RETRO::StreamPtr > m_streams
Constructor & Destructor Documentation
CGameClientStreams()
CGameClientStreams::CGameClientStreams (CGameClient & gameClient)
Member Function Documentation
CloseStream()
void CGameClientStreams::CloseStream (IGameClientStream * stream)
References KODI::RETRO::IStreamManager::CloseStream(), m_streamManager, and m_streams.
Referenced by KODI::GAME::CGameClient::cb_close_stream().
CreateStream()
std::unique_ptr< IGameClientStream > CGameClientStreams::CreateStream (GAME_STREAM_TYPE streamType) const private
References GAME_STREAM_AUDIO, GAME_STREAM_SW_FRAMEBUFFER, GAME_STREAM_VIDEO, KODI::GAME::CGameClient::GetSampleRate(), and m_gameClient.
Referenced by OpenStream().
Deinitialize()
void CGameClientStreams::Deinitialize ()
References m_streamManager.
Referenced by KODI::GAME::CGameClient::CloseFile(), KODI::GAME::CGameClient::OpenFile(), and KODI::GAME::CGameClient::OpenStandalone().
Initialize()
void CGameClientStreams::Initialize (RETRO::IStreamManager & streamManager)
References m_streamManager.
Referenced by KODI::GAME::CGameClient::OpenFile(), and KODI::GAME::CGameClient::OpenStandalone().
OpenStream()
IGameClientStream * CGameClientStreams::OpenStream (const game_stream_properties & properties)
References CreateStream(), KODI::RETRO::IStreamManager::CreateStream(), CLog::Log(), LOGERROR, m_streamManager, m_streams, KODI::GAME::CGameClientTranslator::TranslateStreamType(), and game_stream_properties::type.
Referenced by KODI::GAME::CGameClient::cb_open_stream().
Member Data Documentation
m_gameClient
CGameClient& KODI::GAME::CGameClientStreams::m_gameClient private
Referenced by CreateStream().
m_streamManager
RETRO::IStreamManager* KODI::GAME::CGameClientStreams::m_streamManager = nullptr private
Referenced by CloseStream(), Deinitialize(), Initialize(), and OpenStream().
m_streams
std::map<IGameClientStream*, RETRO::StreamPtr> KODI::GAME::CGameClientStreams::m_streams private
Referenced by CloseStream(), and OpenStream().
The documentation for this class was generated from the following files:
GameClientStreams.h
GameClientStreams.cpp