Kodi Documentation: CWebVTTHandler Class Reference
CWebVTTHandler Class Reference
#include <WebVTTHandler.h>
Public Member Functions
CWebVTTHandler ()
~CWebVTTHandler ()
bool Initialize ()
Prepare the handler to the decoding.
void Reset ()
bool CheckSignature (const std::string &data)
Verify the validity of the WebVTT signature.
void DecodeLine (std::string line, std::vector< subtitleData > *subList)
Decode a line of the WebVTT text data.
bool IsForcedMargins () const
void SetPeriodStart (double pts)
Protected Member Functions
void CalculateTextPosition (std::string &subtitleText)
void ConvertSubtitle (std::string &text)
void GetCueSettings (std::string &cueSettings)
Protected Attributes
subtitleData m_subtitleData
Private Member Functions
bool IsCueLine (std::string &line)
void GetCueData (std::string &cueText)
std::string GetCueSettingValue (const std::string &propName, std::string &text, const std::string &defaultValue)
std::string GetCueCssValue (const std::string &cssPropName, std::string &line)
void AddDefaultCssClasses ()
void InsertCssStyleStartTag (const tagToken &tag, std::string &text, int &pos, int flagTags[], std::deque< std::pair< std::string, webvttCssStyle * > > &cssTagsOpened)
void InsertCssStyleCloseTag (const tagToken &tag, std::string &text, int &pos, int flagTags[], std::deque< std::pair< std::string, webvttCssStyle * > > &cssTagsOpened, webvttCssStyle &baseStyle)
bool GetBaseStyle (webvttCssStyle &style)
void ConvertAddSubtitle (std::vector< subtitleData > *subList)
void LoadColors ()
double GetTimeFromRegexTS (CRegExp &regex, int indexStart=1)
Private Attributes
std::unique_ptr< subtitleData > m_lastSubtitleData
std::string m_previousLines [3]
bool m_overrideStyle {false}
bool m_overridePositions {false}
WebvttSection m_currentSection {WebvttSection::UNDEFINED}
CRegExp m_cueTimeRegex
CRegExp m_timeRegex
std::map< std::string, CRegExp > m_cuePropsMapRegex
CGUIColorManager m_colorManager
CRegExp m_tagsRegex
CRegExp m_cueCssTagRegex
std::map< std::string, CRegExp > m_cueCssStyleMapRegex
std::vector< std::string > m_feedCssSelectorNames
webvttCssStyle m_feedCssStyle
std::map< WebvttSelector, std::map< std::string, webvttCssStyle > > m_cssSelectors
bool m_CSSColorsLoaded {false}
std::vector< std::pair< std::string, KODI::UTILS::COLOR::ColorInfo > > m_CSSColors
double m_offset {0.0}
Constructor & Destructor Documentation
CWebVTTHandler()
CWebVTTHandler::CWebVTTHandler () inline
~CWebVTTHandler()
CWebVTTHandler::~CWebVTTHandler () inline
Member Function Documentation
AddDefaultCssClasses()
void CWebVTTHandler::AddDefaultCssClasses () private
References CLASS, and m_cssSelectors.
Referenced by Initialize().
CalculateTextPosition()
void CWebVTTHandler::CalculateTextPosition (std::string & subtitleText) protected
References webvttCueSettings::align, AUTO, CENTER, subtitleData::cueSettings, END, webvttAutoValue::isAuto, LEFT, webvttCueSettings::line, m_overridePositions, m_subtitleData, KODI::SUBTITLES::STYLE::MARGIN_VERTICAL, subtitleData::marginLeft, subtitleData::marginRight, subtitleData::marginVertical, webvttCueSettings::position, webvttCueSettings::positionAlign, HTML::CHTMLUtil::RemoveTags(), RIGHT, webvttCueSettings::size, webvttCueSettings::snapToLines, START, SUB_CENTER, SUB_LEFT, SUB_RIGHT, subtitleData::textAlign, TOP_CENTER, TOP_LEFT, TOP_RIGHT, subtitleData::useMargins, CCharsetConverter::utf8IsRTLBidiDirection(), webvttAutoValue::value, KODI::SUBTITLES::STYLE::VIEWPORT_HEIGHT, and KODI::SUBTITLES::STYLE::VIEWPORT_WIDTH.
Referenced by DecodeLine(), and CWebVTTISOHandler::ParseVTTCueBox().
CheckSignature()
bool CWebVTTHandler::CheckSignature (const std::string & data)
Verify the validity of the WebVTT signature.
References data(), and LOGERROR.
Referenced by COverlayCodecWebVTT::Decode(), and CSubtitleParserWebVTT::Open().
ConvertAddSubtitle()
void CWebVTTHandler::ConvertAddSubtitle (std::vector< subtitleData > * subList) private
References ConvertSubtitle(), subtitleData::cueSettings, m_lastSubtitleData, m_subtitleData, subtitleData::startTime, subtitleData::stopTime, subtitleData::text, and subtitleData::textRaw.
Referenced by DecodeLine().
ConvertSubtitle()
void CWebVTTHandler::ConvertSubtitle (std::string & text) protected
References GetBaseStyle(), CRegExp::GetMatch(), InsertCssStyleCloseTag(), InsertCssStyleStartTag(), m_overridePositions, m_subtitleData, m_tagsRegex, CRegExp::RegFind(), SUB_CENTER, SUB_LEFT, SUB_RIGHT, text, subtitleData::textAlign, subtitleData::textRaw, TOP_CENTER, TOP_LEFT, and TOP_RIGHT.
Referenced by ConvertAddSubtitle(), and CWebVTTISOHandler::ParseVTTCueBox().
DecodeLine()
void CWebVTTHandler::DecodeLine (std::string line, std::vector< subtitleData > * subList)
Decode a line of the WebVTT text data.
Parameters
line The line to decode
subList The list to be filled with decoded subtitles
References ANY, ATTRIBUTE, CalculateTextPosition(), CLASS, color, ConvertAddSubtitle(), KODI::UTILS::COLOR::ConvertIntToRGB(), KODI::UTILS::COLOR::ConvertToBGR(), CUE, CUE_METADATA, CUE_TEXT, subtitleData::cueSettings, UTILS::CSS::Escape(), GetCueCssValue(), GetCueData(), CRegExp::GetMatch(), CRegExp::GetSubCount(), GetTimeFromRegexTS(), webvttCueSettings::id, ID, IsCueLine(), LoadColors(), LOGERROR, LOGWARNING, webvttCssStyle::m_color, m_CSSColors, m_CSSColorsLoaded, m_cssSelectors, m_cueCssTagRegex, m_currentSection, m_feedCssSelectorNames, m_feedCssStyle, webvttCssStyle::m_isFontBold, webvttCssStyle::m_isFontItalic, webvttCssStyle::m_isFontUnderline, m_offset, m_previousLines, webvttCssStyle::m_selectorName, webvttCssStyle::m_selectorType, m_subtitleData, NOTE, CRegExp::RegComp(), CRegExp::RegFind(), REGION, STYLE, STYLE_CONTENT, subtitleData::text, TYPE, UNDEFINED, and UNSUPPORTED.
Referenced by COverlayCodecWebVTT::Decode(), and CSubtitleParserWebVTT::Open().
GetBaseStyle()
bool CWebVTTHandler::GetBaseStyle (webvttCssStyle & style) private
References ANY, subtitleData::cueSettings, webvttCueSettings::id, ID, webvttCssStyle::m_color, m_cssSelectors, webvttCssStyle::m_isFontBold, webvttCssStyle::m_isFontItalic, webvttCssStyle::m_isFontUnderline, m_overrideStyle, and m_subtitleData.
Referenced by ConvertSubtitle().
GetCueCssValue()
std::string CWebVTTHandler::GetCueCssValue (const std::string & cssPropName, std::string & line) private
References m_cueCssStyleMapRegex.
Referenced by DecodeLine().
GetCueData()
void CWebVTTHandler::GetCueData (std::string & cueText) private
References GetCueSettings(), CRegExp::GetFindLen(), CRegExp::GetSubCount(), GetTimeFromRegexTS(), LOGERROR, m_cueTimeRegex, m_offset, m_subtitleData, subtitleData::startTime, and subtitleData::stopTime.
Referenced by DecodeLine().
GetCueSettings()
void CWebVTTHandler::GetCueSettings (std::string & cueSettings) protected
References webvttCueSettings::align, AUTO, CENTER, subtitleData::cueSettings, END, GetCueSettingValue(), HORIZONTAL, webvttAutoValue::isAuto, LEFT, webvttCueSettings::line, m_subtitleData, webvttCueSettings::position, webvttCueSettings::positionAlign, RIGHT, webvttCueSettings::size, webvttCueSettings::snapToLines, START, webvttAutoValue::value, VERTICAL_LR, VERTICAL_RL, and webvttCueSettings::verticalAlign.
Referenced by GetCueData(), and CWebVTTISOHandler::ParseVTTCueBox().
GetCueSettingValue()
std::string CWebVTTHandler::GetCueSettingValue (const std::string & propName, std::string & text, const std::string & defaultValue) private
References m_cuePropsMapRegex, and text.
Referenced by GetCueSettings().
GetTimeFromRegexTS()
double CWebVTTHandler::GetTimeFromRegexTS (CRegExp & regex, int indexStart = 1) private
References DVD_TIME_BASE, and CRegExp::GetMatch().
Referenced by DecodeLine(), GetCueData(), and InsertCssStyleStartTag().
Initialize()
bool CWebVTTHandler::Initialize ()
Prepare the handler to the decoding.
References AddDefaultCssClasses(), CServiceBroker::GetSettingsComponent(), m_cueCssStyleMapRegex, m_cueCssTagRegex, m_cuePropsMapRegex, m_cueTimeRegex, m_currentSection, m_overridePositions, m_overrideStyle, m_tagsRegex, m_timeRegex, KODI::SUBTITLES::POSITIONS, CRegExp::RegComp(), KODI::SUBTITLES::STYLES, KODI::SUBTITLES::STYLES_POSITIONS, and UNDEFINED.
Referenced by CSubtitleParserWebVTT::Open(), and COverlayCodecWebVTT::Open().
InsertCssStyleCloseTag()
void CWebVTTHandler::InsertCssStyleCloseTag (const tagToken & tag, std::string & text, int & pos, int flagTags[], std::deque< std::pair< std::string, webvttCssStyle * > > & cssTagsOpened, webvttCssStyle & baseStyle) private
References tags, and text.
Referenced by ConvertSubtitle().
InsertCssStyleStartTag()
void CWebVTTHandler::InsertCssStyleStartTag (const tagToken & tag, std::string & text, int & pos, int flagTags[], std::deque< std::pair< std::string, webvttCssStyle * > > & cssTagsOpened) private
References ATTRIBUTE, CLASS, GetTimeFromRegexTS(), LOGERROR, m_cssSelectors, m_offset, m_subtitleData, m_timeRegex, CRegExp::RegFind(), subtitleData::stopTime, tags, text, and TYPE.
Referenced by ConvertSubtitle().
IsCueLine()
bool CWebVTTHandler::IsCueLine (std::string & line) private
References m_cueTimeRegex, and CRegExp::RegFind().
Referenced by DecodeLine().
IsForcedMargins()
bool CWebVTTHandler::IsForcedMargins () const inline
References m_overridePositions.
Referenced by COverlayCodecWebVTT::GetOverlay(), and CSubtitleParserWebVTT::Open().
LoadColors()
void CWebVTTHandler::LoadColors () private
References CGUIColorManager::LoadColorsListFromXML(), m_CSSColors, m_CSSColorsLoaded, and CSpecialProtocol::TranslatePathConvertCase().
Referenced by DecodeLine().
Reset()
void CWebVTTHandler::Reset ()
References m_currentSection, m_offset, m_previousLines, and UNDEFINED.
Referenced by COverlayCodecWebVTT::Decode().
SetPeriodStart()
void CWebVTTHandler::SetPeriodStart (double pts) inline
References m_offset.
Referenced by COverlayCodecWebVTT::Decode().
Member Data Documentation
m_colorManager
CGUIColorManager CWebVTTHandler::m_colorManager private
m_CSSColors
std::vector<std::pair<std::string, KODI::UTILS::COLOR::ColorInfo> > CWebVTTHandler::m_CSSColors private
Referenced by DecodeLine(), and LoadColors().
m_CSSColorsLoaded
bool CWebVTTHandler::m_CSSColorsLoaded {false} private
Referenced by DecodeLine(), and LoadColors().
m_cssSelectors
std::map<WebvttSelector, std::map<std::string, webvttCssStyle> > CWebVTTHandler::m_cssSelectors private
Referenced by AddDefaultCssClasses(), DecodeLine(), GetBaseStyle(), and InsertCssStyleStartTag().
m_cueCssStyleMapRegex
std::map<std::string, CRegExp> CWebVTTHandler::m_cueCssStyleMapRegex private
Referenced by GetCueCssValue(), and Initialize().
m_cueCssTagRegex
CRegExp CWebVTTHandler::m_cueCssTagRegex private
Referenced by DecodeLine(), and Initialize().
m_cuePropsMapRegex
std::map<std::string, CRegExp> CWebVTTHandler::m_cuePropsMapRegex private
Referenced by GetCueSettingValue(), and Initialize().
m_cueTimeRegex
CRegExp CWebVTTHandler::m_cueTimeRegex private
Referenced by GetCueData(), Initialize(), and IsCueLine().
m_currentSection
WebvttSection CWebVTTHandler::m_currentSection {WebvttSection::UNDEFINED} private
Referenced by DecodeLine(), Initialize(), and Reset().
m_feedCssSelectorNames
std::vector<std::string> CWebVTTHandler::m_feedCssSelectorNames private
Referenced by DecodeLine().
m_feedCssStyle
webvttCssStyle CWebVTTHandler::m_feedCssStyle private
Referenced by DecodeLine().
m_lastSubtitleData
std::unique_ptr<subtitleData> CWebVTTHandler::m_lastSubtitleData private
Referenced by ConvertAddSubtitle().
m_offset
double CWebVTTHandler::m_offset {0.0} private
Referenced by DecodeLine(), GetCueData(), InsertCssStyleStartTag(), Reset(), and SetPeriodStart().
m_overridePositions
bool CWebVTTHandler::m_overridePositions {false} private
Referenced by CalculateTextPosition(), ConvertSubtitle(), Initialize(), and IsForcedMargins().
m_overrideStyle
bool CWebVTTHandler::m_overrideStyle {false} private
Referenced by GetBaseStyle(), and Initialize().
m_previousLines
std::string CWebVTTHandler::m_previousLines[3] private
Referenced by DecodeLine(), and Reset().
m_subtitleData
subtitleData CWebVTTHandler::m_subtitleData protected
Referenced by CalculateTextPosition(), ConvertAddSubtitle(), ConvertSubtitle(), DecodeLine(), CWebVTTISOHandler::DecodeStream(), GetBaseStyle(), GetCueData(), GetCueSettings(), InsertCssStyleStartTag(), and CWebVTTISOHandler::ParseVTTCueBox().
m_tagsRegex
CRegExp CWebVTTHandler::m_tagsRegex private
Referenced by ConvertSubtitle(), and Initialize().
m_timeRegex
CRegExp CWebVTTHandler::m_timeRegex private
Referenced by Initialize(), and InsertCssStyleStartTag().
The documentation for this class was generated from the following files:
WebVTTHandler.h
WebVTTHandler.cpp