Kodi Documentation: GUIFontManager Class Reference
GUIFontManager Class Reference
Guilib classes » Graphics and Screen » Textures and Fonts
#include <GUIFontManager.h>
Public Member Functions
GUIFontManager ()
~GUIFontManager () override
void Initialize ()
Initialize the font manager. Checks that fonts cache are up to date, otherwise update it.
bool IsUpdating () const
bool OnMessage (CGUIMessage &message) override
void Unload (const std::string &strFontName)
void LoadFonts (const std::string &fontSet)
CGUIFont * LoadTTF (const std::string &strFontName, const std::string &strFilename, KODI::UTILS::COLOR::Color textColor, KODI::UTILS::COLOR::Color shadowColor, const int iSize, const int iStyle, bool border=false, float lineSpacing=1.0f, float aspect=1.0f, const RESOLUTION_INFO *res=nullptr, bool preserveAspect=false)
CGUIFont * GetFont (const std::string &strFontName, bool fallback=true)
CGUIFont * GetDefaultFont (bool border=false)
return a default font
void Clear ()
void FreeFontFile (CGUIFontTTF *pFont)
std::vector< std::string > GetUserFontsFamilyNames ()
Get the list of user fonts as family names from cache.
Public Member Functions inherited from IMsgTargetCallback
virtual ~IMsgTargetCallback ()=default
Static Public Member Functions
static void SettingOptionsFontsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
Protected Member Functions
void ReloadTTFFonts ()
void LoadFonts (const TiXmlNode *fontNode)
CGUIFontTTF * GetFontFile (const std::string &fontIdent)
Static Protected Member Functions
static void RescaleFontSizeAndAspect (CGraphicContext &context, float *size, float *aspect, const RESOLUTION_INFO &sourceRes, bool preserveAspect)
static void GetStyle (const TiXmlNode *fontNode, int &iStyle)
Protected Attributes
std::vector< std::unique_ptr< CGUIFont > > m_vecFonts
std::vector< std::unique_ptr< CGUIFontTTF > > m_vecFontFiles
std::vector< OrigFontInfo > m_vecFontInfo
RESOLUTION_INFO m_skinResolution
bool m_canReload {true}
Private Member Functions
void LoadUserFonts ()
bool LoadFontsFromFile (const std::string &fontsetFilePath, const std::string &fontSet, std::string &firstFontset)
Private Attributes
CCriticalSection m_critSection
std::vector< FontMetadata > m_userFontsCache
Constructor & Destructor Documentation
GUIFontManager()
GUIFontManager::GUIFontManager () default
~GUIFontManager()
GUIFontManager::~GUIFontManager () override
References Clear().
Member Function Documentation
Clear()
void GUIFontManager::Clear ()
References CGUIFontTTFGL::DestroyStaticVertexBuffers(), CGUIFontTTFGLES::DestroyStaticVertexBuffers(), m_vecFontFiles, m_vecFontInfo, and m_vecFonts.
Referenced by ~GUIFontManager().
FreeFontFile()
void GUIFontManager::FreeFontFile (CGUIFontTTF * pFont)
References m_vecFontFiles.
GetDefaultFont()
CGUIFont * GUIFontManager::GetDefaultFont (bool border = false)
return a default font
Parameters
border whether the font should be a font with an outline
Returns
the font. nullptr if no default font can be found.
References OrigFontInfo::aspect, KODI::UTILS::COLOR::BLACK, OrigFontInfo::fileName, CGUIFont::GetFontName(), LoadTTF(), m_vecFontInfo, m_vecFonts, OrigFontInfo::preserveAspect, OrigFontInfo::size, and OrigFontInfo::sourceRes.
GetFont()
CGUIFont * GUIFontManager::GetFont (const std::string & strFontName, bool fallback = true)
References GetFont(), CGUIFont::GetFontName(), and m_vecFonts.
Referenced by GetFont(), and LoadTTF().
GetFontFile()
CGUIFontTTF * GUIFontManager::GetFontFile (const std::string & fontIdent) protected
References m_vecFontFiles.
Referenced by LoadTTF(), and ReloadTTFFonts().
GetStyle()
void GUIFontManager::GetStyle (const TiXmlNode * fontNode, int & iStyle) static protected
References FONT_STYLE_BOLD, FONT_STYLE_CAPITALIZE, FONT_STYLE_ITALICS, FONT_STYLE_LIGHT, FONT_STYLE_LOWERCASE, FONT_STYLE_NORMAL, FONT_STYLE_UPPERCASE, and XMLUtils::GetString().
Referenced by LoadFonts().
GetUserFontsFamilyNames()
std::vector< std::string > GUIFontManager::GetUserFontsFamilyNames ()
Get the list of user fonts as family names from cache.
Returns
The list of available fonts family names
References m_userFontsCache.
Initialize()
void GUIFontManager::Initialize ()
Initialize the font manager. Checks that fonts cache are up to date, otherwise update it.
References LoadUserFonts(), and m_critSection.
Referenced by CApplication::Initialize().
IsUpdating()
bool GUIFontManager::IsUpdating () const inline
References m_critSection.
LoadFonts() [1/2]
void GUIFontManager::LoadFonts (const std::string & fontSet)
References XFILE::DIR_FLAG_BYPASS_CACHE, g_SkinInfo, XFILE::CDirectory::GetDirectory(), LoadFonts(), LoadFontsFromFile(), LOGERROR, LOGWARNING, m_skinResolution, CFileItemList::Size(), and CSpecialProtocol::TranslatePath().
Referenced by LoadFonts(), and LoadFontsFromFile().
LoadFonts() [2/2]
void GUIFontManager::LoadFonts (const TiXmlNode * fontNode) protected
References FONT_STYLE_NORMAL, CGUIControlFactory::GetColor(), XMLUtils::GetFloat(), XMLUtils::GetInt(), XMLUtils::GetString(), GetStyle(), URIUtils::HasExtension(), and LoadTTF().
LoadFontsFromFile()
bool GUIFontManager::LoadFontsFromFile (const std::string & fontsetFilePath, const std::string & fontSet, std::string & firstFontset) private
References g_SkinInfo, LoadFonts(), and LOGINFO.
Referenced by LoadFonts().
LoadTTF()
CGUIFont * GUIFontManager::LoadTTF (const std::string & strFontName, const std::string & strFilename, KODI::UTILS::COLOR::Color textColor, KODI::UTILS::COLOR::Color shadowColor, const int iSize, const int iStyle, bool border = false, float lineSpacing = 1.0f, float aspect = 1.0f, const RESOLUTION_INFO * res = nullptr, bool preserveAspect = false)
References URIUtils::AddFileToFolder(), addons, OrigFontInfo::aspect, OrigFontInfo::border, CheckFont(), CGUIFontTTF::CreateGUIFontTTF(), OrigFontInfo::fileName, OrigFontInfo::fontFilePath, CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetAddons(), URIUtils::GetFileName(), GetFont(), GetFontFile(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetMediaDir(), CServiceBroker::GetWinSystem(), LoadTTF(), CLog::Log(), LOGERROR, LOGFATAL, m_skinResolution, m_vecFontFiles, m_vecFontInfo, m_vecFonts, OrigFontInfo::preserveAspect, RescaleFontSizeAndAspect(), OrigFontInfo::size, OrigFontInfo::sourceRes, and CSpecialProtocol::TranslatePathConvertCase().
Referenced by GetDefaultFont(), LoadFonts(), and LoadTTF().
LoadUserFonts()
void GUIFontManager::LoadUserFonts () private
Todo:
FIXME: this "for" loop should be replaced with the more performant parallel execution std::for_each(std::execution::par, ... to halving loading times of fonts list, maybe with C++17 with appropriate fix to include parallel execution or future C++20
References URIUtils::AddFileToFolder(), CFileItemList::Contains(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, XFILE::CDirectory::Exists(), CFileItemList::Get(), XFILE::CDirectory::GetDirectory(), KODI::UTILS::FONT::GetFontFamilyNames(), XMLUtils::GetString(), LOGDEBUG, LOGERROR, m_userFontsCache, CFileItemList::Remove(), CXBMCTinyXML::SaveFile(), CFileItemList::SetFastLookup(), XMLUtils::SetString(), KODI::UTILS::FONT::SUPPORTED_EXTENSIONS_MASK, and KODI::UTILS::FONT::FONTPATH::USER.
Referenced by Initialize().
OnMessage()
bool GUIFontManager::OnMessage (CGUIMessage & message) override virtual
Implements IMsgTargetCallback.
References CServiceBroker::GetGUI(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_RENDERER_LOST, GUI_MSG_RENDERER_RESET, GUI_MSG_WINDOW_RESIZE, m_canReload, ReloadTTFFonts(), and CGUIWindowManager::SendMessage().
ReloadTTFFonts()
void GUIFontManager::ReloadTTFFonts (void) protected
References OrigFontInfo::aspect, OrigFontInfo::border, CGUIFontTTF::CreateGUIFontTTF(), OrigFontInfo::fileName, OrigFontInfo::fontFilePath, GetFontFile(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGERROR, m_vecFontFiles, m_vecFontInfo, m_vecFonts, OrigFontInfo::preserveAspect, RescaleFontSizeAndAspect(), OrigFontInfo::size, and OrigFontInfo::sourceRes.
Referenced by OnMessage().
RescaleFontSizeAndAspect()
void GUIFontManager::RescaleFontSizeAndAspect (CGraphicContext & context, float * size, float * aspect, const RESOLUTION_INFO & sourceRes, bool preserveAspect) static protected
References RESOLUTION_INFO::fPixelRatio, CGraphicContext::GetGUIScaling(), and CGraphicContext::GetResInfo().
Referenced by LoadTTF(), and ReloadTTFFonts().
SettingOptionsFontsFiller()
void GUIFontManager::SettingOptionsFontsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References CFileItemList::AddFront(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, XFILE::CDirectory::GetDirectory(), CFileItemList::rbegin(), CFileItemList::rend(), KODI::UTILS::FONT::SUPPORTED_EXTENSIONS_MASK, KODI::UTILS::FONT::FONTPATH::SYSTEM, and KODI::UTILS::FONT::FONTPATH::USER.
Referenced by CSettings::InitializeOptionFillers().
Unload()
void GUIFontManager::Unload (const std::string & strFontName)
References m_vecFonts.
Member Data Documentation
m_canReload
bool GUIFontManager::m_canReload {true} protected
Referenced by OnMessage().
m_critSection
CCriticalSection GUIFontManager::m_critSection mutable private
Referenced by Initialize(), and IsUpdating().
m_skinResolution
RESOLUTION_INFO GUIFontManager::m_skinResolution protected
Referenced by LoadFonts(), and LoadTTF().
m_userFontsCache
std::vector<FontMetadata> GUIFontManager::m_userFontsCache private
Referenced by GetUserFontsFamilyNames(), and LoadUserFonts().
m_vecFontFiles
std::vector<std::unique_ptr<CGUIFontTTF> > GUIFontManager::m_vecFontFiles protected
Referenced by Clear(), FreeFontFile(), GetFontFile(), LoadTTF(), and ReloadTTFFonts().
m_vecFontInfo
std::vector<OrigFontInfo> GUIFontManager::m_vecFontInfo protected
Referenced by Clear(), GetDefaultFont(), LoadTTF(), and ReloadTTFFonts().
m_vecFonts
std::vector<std::unique_ptr<CGUIFont> > GUIFontManager::m_vecFonts protected
Referenced by Clear(), GetDefaultFont(), GetFont(), LoadTTF(), ReloadTTFFonts(), and Unload().
The documentation for this class was generated from the following files:
GUIFontManager.h
GUIFontManager.cpp