Kodi Documentation: TestLocale.cpp File Reference
TestLocale.cpp File Reference
#include "utils/Locale.h"
#include "utils/StringUtils.h"
#include <gtest/gtest.h>
Functions
TEST (TestLocale, DefaultLocale)
TEST (TestLocale, LanguageLocale)
TEST (TestLocale, LanguageTerritoryLocale)
TEST (TestLocale, LanguageCodesetLocale)
TEST (TestLocale, LanguageModifierLocale)
TEST (TestLocale, LanguageTerritoryCodesetLocale)
TEST (TestLocale, LanguageTerritoryModifierLocale)
TEST (TestLocale, LanguageTerritoryCodesetModifierLocale)
TEST (TestLocale, FullStringLocale)
TEST (TestLocale, FromString)
TEST (TestLocale, EmptyLocale)
TEST (TestLocale, Equals)
Variables
static const std::string TerritorySeparator = "_"
static const std::string CodesetSeparator = "."
static const std::string ModifierSeparator = "@"
static const std::string LanguageCodeEnglish = "en"
static const std::string TerritoryCodeBritain = "GB"
static const std::string CodesetUtf8 = "UTF-8"
static const std::string ModifierLatin = "latin"
Function Documentation
TEST() [1/12]
TEST (TestLocale , DefaultLocale)
References CLocale::GetCodeset(), CLocale::GetLanguageCode(), CLocale::GetModifier(), CLocale::GetTerritoryCode(), CLocale::IsValid(), and CLocale::ToString().
TEST() [2/12]
TEST (TestLocale , EmptyLocale)
References CLocale::Empty.
TEST() [3/12]
TEST (TestLocale , Equals)
References CodesetSeparator, CodesetUtf8, CLocale::Equals(), LanguageCodeEnglish, ModifierLatin, ModifierSeparator, TerritoryCodeBritain, and TerritorySeparator.
TEST() [4/12]
TEST (TestLocale , FromString)
References CodesetSeparator, CodesetUtf8, CLocale::FromString(), CLocale::IsValid(), LanguageCodeEnglish, ModifierLatin, ModifierSeparator, TerritoryCodeBritain, TerritorySeparator, and CLocale::ToString().
TEST() [5/12]
TEST (TestLocale , FullStringLocale)
References CodesetSeparator, CodesetUtf8, CLocale::GetCodeset(), CLocale::GetLanguageCode(), CLocale::GetModifier(), CLocale::GetTerritoryCode(), CLocale::IsValid(), LanguageCodeEnglish, ModifierLatin, ModifierSeparator, TerritoryCodeBritain, TerritorySeparator, KODI::UTILS::StringUtils::ToLower(), CLocale::ToShortString(), CLocale::ToShortStringLC(), CLocale::ToString(), and CLocale::ToStringLC().
TEST() [6/12]
TEST (TestLocale , LanguageCodesetLocale)
References CodesetSeparator, CodesetUtf8, CLocale::GetCodeset(), CLocale::GetLanguageCode(), CLocale::GetModifier(), CLocale::GetTerritoryCode(), CLocale::IsValid(), LanguageCodeEnglish, KODI::UTILS::StringUtils::ToLower(), CLocale::ToShortString(), CLocale::ToShortStringLC(), CLocale::ToString(), and CLocale::ToStringLC().
TEST() [7/12]
TEST (TestLocale , LanguageLocale)
References CLocale::GetCodeset(), CLocale::GetLanguageCode(), CLocale::GetModifier(), CLocale::GetTerritoryCode(), CLocale::IsValid(), LanguageCodeEnglish, CLocale::ToShortString(), CLocale::ToShortStringLC(), CLocale::ToString(), and CLocale::ToStringLC().
TEST() [8/12]
TEST (TestLocale , LanguageModifierLocale)
References CLocale::GetCodeset(), CLocale::GetLanguageCode(), CLocale::GetModifier(), CLocale::GetTerritoryCode(), CLocale::IsValid(), LanguageCodeEnglish, ModifierLatin, ModifierSeparator, KODI::UTILS::StringUtils::ToLower(), CLocale::ToShortString(), CLocale::ToShortStringLC(), CLocale::ToString(), and CLocale::ToStringLC().
TEST() [9/12]
TEST (TestLocale , LanguageTerritoryCodesetLocale)
References CodesetSeparator, CodesetUtf8, CLocale::GetCodeset(), CLocale::GetLanguageCode(), CLocale::GetModifier(), CLocale::GetTerritoryCode(), CLocale::IsValid(), LanguageCodeEnglish, TerritoryCodeBritain, TerritorySeparator, KODI::UTILS::StringUtils::ToLower(), CLocale::ToShortString(), CLocale::ToShortStringLC(), CLocale::ToString(), and CLocale::ToStringLC().
TEST() [10/12]
TEST (TestLocale , LanguageTerritoryCodesetModifierLocale)
References CodesetSeparator, CodesetUtf8, CLocale::GetCodeset(), CLocale::GetLanguageCode(), CLocale::GetModifier(), CLocale::GetTerritoryCode(), CLocale::IsValid(), LanguageCodeEnglish, ModifierLatin, ModifierSeparator, TerritoryCodeBritain, TerritorySeparator, KODI::UTILS::StringUtils::ToLower(), CLocale::ToShortString(), CLocale::ToShortStringLC(), CLocale::ToString(), and CLocale::ToStringLC().
TEST() [11/12]
TEST (TestLocale , LanguageTerritoryLocale)
References CLocale::GetCodeset(), CLocale::GetLanguageCode(), CLocale::GetModifier(), CLocale::GetTerritoryCode(), CLocale::IsValid(), LanguageCodeEnglish, TerritoryCodeBritain, TerritorySeparator, KODI::UTILS::StringUtils::ToLower(), CLocale::ToShortString(), CLocale::ToShortStringLC(), CLocale::ToString(), and CLocale::ToStringLC().
TEST() [12/12]
TEST (TestLocale , LanguageTerritoryModifierLocale)
References CLocale::GetCodeset(), CLocale::GetLanguageCode(), CLocale::GetModifier(), CLocale::GetTerritoryCode(), CLocale::IsValid(), LanguageCodeEnglish, ModifierLatin, ModifierSeparator, TerritoryCodeBritain, TerritorySeparator, KODI::UTILS::StringUtils::ToLower(), CLocale::ToShortString(), CLocale::ToShortStringLC(), CLocale::ToString(), and CLocale::ToStringLC().
Variable Documentation
CodesetSeparator
const std::string CodesetSeparator = "." static
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
CodesetUtf8
const std::string CodesetUtf8 = "UTF-8" static
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
LanguageCodeEnglish
const std::string LanguageCodeEnglish = "en" static
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
ModifierLatin
const std::string ModifierLatin = "latin" static
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
ModifierSeparator
const std::string ModifierSeparator = "@" static
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
TerritoryCodeBritain
const std::string TerritoryCodeBritain = "GB" static
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
TerritorySeparator
const std::string TerritorySeparator = "_" static
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().