Kodi Documentation: CLibInputKeyboard Class Reference
CLibInputKeyboard Class Reference
#include <LibInputKeyboard.h>
Classes
struct XkbComposeStateDeleter
struct XkbComposeTableDeleter
struct XkbContextDeleter
struct XkbKeymapDeleter
struct XkbStateDeleter
Public Member Functions
CLibInputKeyboard ()
~CLibInputKeyboard ()=default
void ProcessKey (libinput_event_keyboard *e)
void UpdateLeds (libinput_device *dev)
void GetRepeat (libinput_device *dev)
bool SetKeymap (const std::string &layout)
Private Member Functions
XBMCKey XBMCKeyForKeysym (xkb_keysym_t sym, uint32_t scancode)
void KeyRepeatTimeout ()
bool SupportsKeyComposition () const
void NotifyKeyComposingEvent (uint8_t eventType, std::uint16_t unicodeCodepoint)
std::uint32_t UnicodeCodepointForKeycode (xkb_keycode_t code) const
Private Attributes
std::unique_ptr< xkb_context, XkbContextDeleter > m_ctx
std::unique_ptr< xkb_keymap, XkbKeymapDeleter > m_keymap
std::unique_ptr< xkb_state, XkbStateDeleter > m_state
std::unique_ptr< xkb_compose_table, XkbComposeTableDeleter > m_composeTable
std::unique_ptr< xkb_compose_state, XkbComposeStateDeleter > m_composedState
xkb_mod_index_t m_modindex [4]
xkb_led_index_t m_ledindex [3]
int m_leds
XBMC_Event m_repeatEvent
std::map< libinput_device *, std::vector< int > > m_repeatData
CTimer m_repeatTimer
int m_repeatRate
Constructor & Destructor Documentation
CLibInputKeyboard()
CLibInputKeyboard::CLibInputKeyboard ()
~CLibInputKeyboard()
CLibInputKeyboard::~CLibInputKeyboard () default
Member Function Documentation
GetRepeat()
void CLibInputKeyboard::GetRepeat (libinput_device * dev)
References data(), CLog::Log(), LOGDEBUG, LOGERROR, m_repeatData, and name.
KeyRepeatTimeout()
void CLibInputKeyboard::KeyRepeatTimeout () private
References CServiceBroker::GetAppPort(), m_repeatEvent, m_repeatRate, m_repeatTimer, and CTimer::RestartAsync().
NotifyKeyComposingEvent()
void CLibInputKeyboard::NotifyKeyComposingEvent (uint8_t eventType, std::uint16_t unicodeCodepoint) private
Notify the outside world about key composing events
Parameters
eventType - the key composition event type
unicodeCodepoint - unicode codepoint of the pressed dead key
References CServiceBroker::GetAppPort(), and XBMC_Event::type.
Referenced by ProcessKey().
ProcessKey()
void CLibInputKeyboard::ProcessKey (libinput_event_keyboard * e)
References data(), CServiceBroker::GetAppPort(), CLog::Log(), LOGDEBUG, m_composedState, m_ctx, m_keymap, m_ledindex, m_leds, m_modindex, m_repeatData, m_repeatEvent, m_repeatRate, m_repeatTimer, m_state, NotifyKeyComposingEvent(), CTimer::Start(), CTimer::Stop(), SupportsKeyComposition(), XBMC_Event::type, UnicodeCodepointForKeycode(), XBMC_KEYCOMPOSING_CANCELLED, XBMC_KEYCOMPOSING_COMPOSING, XBMC_KEYCOMPOSING_FINISHED, XBMC_KEYDOWN, XBMC_KEYUP, XBMCK_BACKSPACE, XBMCK_CAPSLOCK, XBMCK_LALT, XBMCK_LCTRL, XBMCK_LMETA, XBMCK_LSHIFT, XBMCK_NUMLOCK, XBMCK_RALT, XBMCK_RCTRL, XBMCK_RMETA, XBMCK_RSHIFT, XBMCK_SCROLLOCK, XBMCK_UNKNOWN, XBMCKeyForKeysym(), XBMCKMOD_ALT, XBMCKMOD_CAPS, XBMCKMOD_CTRL, XBMCKMOD_META, XBMCKMOD_NONE, XBMCKMOD_NUM, and XBMCKMOD_SHIFT.
SetKeymap()
bool CLibInputKeyboard::SetKeymap (const std::string & layout)
References CLog::Log(), LOGERROR, m_ctx, m_keymap, m_ledindex, m_leds, m_modindex, and m_state.
SupportsKeyComposition()
bool CLibInputKeyboard::SupportsKeyComposition () const private
Check if the system supports key composition
Returns
true if composition is supported, false otherwise
References m_composedState.
Referenced by ProcessKey(), and UnicodeCodepointForKeycode().
UnicodeCodepointForKeycode()
std::uint32_t CLibInputKeyboard::UnicodeCodepointForKeycode (xkb_keycode_t code) const private
Get Unicode codepoint/UTF32 code for provided keycode
References m_composedState, m_state, SupportsKeyComposition(), and XBMCK_UNKNOWN.
Referenced by ProcessKey().
UpdateLeds()
void CLibInputKeyboard::UpdateLeds (libinput_device * dev)
References m_leds.
XBMCKeyForKeysym()
XBMCKey CLibInputKeyboard::XBMCKeyForKeysym (xkb_keysym_t sym, uint32_t scancode) private
References XBMCK_F1, and XBMCK_UNKNOWN.
Referenced by ProcessKey().
Member Data Documentation
m_composedState
std::unique_ptr<xkb_compose_state, XkbComposeStateDeleter> CLibInputKeyboard::m_composedState private
Referenced by ProcessKey(), SupportsKeyComposition(), and UnicodeCodepointForKeycode().
m_composeTable
std::unique_ptr<xkb_compose_table, XkbComposeTableDeleter> CLibInputKeyboard::m_composeTable private
m_ctx
std::unique_ptr<xkb_context, XkbContextDeleter> CLibInputKeyboard::m_ctx private
Referenced by ProcessKey(), and SetKeymap().
m_keymap
std::unique_ptr<xkb_keymap, XkbKeymapDeleter> CLibInputKeyboard::m_keymap private
Referenced by ProcessKey(), and SetKeymap().
m_ledindex
xkb_led_index_t CLibInputKeyboard::m_ledindex[3] private
Referenced by ProcessKey(), and SetKeymap().
m_leds
int CLibInputKeyboard::m_leds private
Referenced by ProcessKey(), SetKeymap(), and UpdateLeds().
m_modindex
xkb_mod_index_t CLibInputKeyboard::m_modindex[4] private
Referenced by ProcessKey(), and SetKeymap().
m_repeatData
std::map<libinput_device*, std::vector<int> > CLibInputKeyboard::m_repeatData private
Referenced by GetRepeat(), and ProcessKey().
m_repeatEvent
XBMC_Event CLibInputKeyboard::m_repeatEvent private
Referenced by KeyRepeatTimeout(), and ProcessKey().
m_repeatRate
int CLibInputKeyboard::m_repeatRate private
Referenced by KeyRepeatTimeout(), and ProcessKey().
m_repeatTimer
CTimer CLibInputKeyboard::m_repeatTimer private
Referenced by KeyRepeatTimeout(), and ProcessKey().
m_state
std::unique_ptr<xkb_state, XkbStateDeleter> CLibInputKeyboard::m_state private
Referenced by ProcessKey(), SetKeymap(), and UnicodeCodepointForKeycode().
The documentation for this class was generated from the following files:
LibInputKeyboard.h
LibInputKeyboard.cpp