Kodi Documentation: XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode Class Reference
XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode Class Reference
#include <DirectoryNode.h>
Public Member Functions
virtual ~CDirectoryNode ()
NODE_TYPE GetType () const
bool GetChilds (CFileItemList &items)
virtual NODE_TYPE GetChildType () const
virtual std::string GetLocalizedName () const
CDirectoryNode * GetParent () const
virtual bool CanCache () const
std::string BuildPath () const
Static Public Member Functions
static CDirectoryNode * ParseURL (const std::string &strPath)
static void GetDatabaseInfo (const std::string &strPath, CQueryParams &params)
static bool GetNodeInfo (const std::string &strPath, NODE_TYPE &type, NODE_TYPE &childtype, CQueryParams &params)
Protected Member Functions
CDirectoryNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
void AddOptions (const std::string &options)
void CollectQueryParams (CQueryParams &params) const
const std::string & GetName () const
int GetID () const
void RemoveParent ()
virtual bool GetContent (CFileItemList &items) const
Static Protected Member Functions
static CDirectoryNode * CreateNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
Private Attributes
NODE_TYPE m_Type
std::string m_strName
CDirectoryNode * m_pParent
CUrlOptions m_options
Constructor & Destructor Documentation
~CDirectoryNode()
CDirectoryNode::~CDirectoryNode () virtual
References m_pParent.
CDirectoryNode()
CDirectoryNode::CDirectoryNode (NODE_TYPE Type, const std::string & strName, CDirectoryNode * pParent) protected
References m_pParent, m_strName, and m_Type.
Member Function Documentation
AddOptions()
void CDirectoryNode::AddOptions (const std::string & options) protected
References CUrlOptions::AddOptions(), and m_options.
Referenced by ParseURL().
BuildPath()
std::string CDirectoryNode::BuildPath () const
References GetName(), CUrlOptions::GetOptionsString(), GetParent(), m_options, m_pParent, and m_strName.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAddedSong::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayedSong::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100Song::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeOverview::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSingles::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSong::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSongTop100::GetContent(), and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeTop100::GetContent().
CanCache()
bool CDirectoryNode::CanCache () const virtual
Referenced by GetChilds().
CollectQueryParams()
void CDirectoryNode::CollectQueryParams (CQueryParams & params) const protected
References GetName(), GetParent(), GetType(), m_pParent, m_strName, m_Type, and XFILE::MUSICDATABASEDIRECTORY::CQueryParams::SetQueryParam().
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSong::GetContent(), and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetLocalizedName().
CreateNode()
CDirectoryNode * CDirectoryNode::CreateNode (NODE_TYPE Type, const std::string & strName, CDirectoryNode * pParent) static protected
References XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ARTIST, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_DISC, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_OVERVIEW, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ROLE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ROOT, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SINGLES, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SOURCE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_TOP100, and XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_YEAR.
Referenced by GetChilds(), and ParseURL().
GetChilds()
bool CDirectoryNode::GetChilds (CFileItemList & items)
References CFileItemList::CACHE_ALWAYS, CanCache(), CFileItemList::Clear(), CreateNode(), GetChildType(), CFileItemList::Load(), m_options, and CFileItemList::SetCacheToDisc().
GetChildType()
NODE_TYPE CDirectoryNode::GetChildType () const virtual
Reimplemented in XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeOverview, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeRoot, and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeTop100.
References XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_NONE.
Referenced by GetChilds(), XFILE::CMusicDatabaseDirectory::GetDirectoryParentType(), and ParseURL().
GetContent()
bool CDirectoryNode::GetContent (CFileItemList & items) const protected virtual
Reimplemented in XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAddedSong, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayedSong, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100Song, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeOverview, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSingles, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSong, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSongTop100, and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeTop100.
GetDatabaseInfo()
void CDirectoryNode::GetDatabaseInfo (const std::string & strPath, CQueryParams & params) static
References ParseURL().
Referenced by UPNP::CUPnPServer::Build(), MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), CGUIWindowMusicBase::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetLabel(), MUSIC_INFO::CMusicInfoTagLoaderDatabase::Load(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CGUIWindowMusicNav::ManageInfoProvider(), MUSIC_INFO::CMusicInfoScanner::Process(), and CGUIDialogMusicInfo::ShowFor().
GetID()
int CDirectoryNode::GetID () const protected
References m_strName.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100::GetLocalizedName(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetLocalizedName(), and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped::GetLocalizedName().
GetLocalizedName()
std::string CDirectoryNode::GetLocalizedName () const virtual
Reimplemented in XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped, XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeOverview, and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeTop100.
GetName()
const std::string & CDirectoryNode::GetName () const protected
References m_strName.
Referenced by BuildPath(), CollectQueryParams(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded::GetChildType(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed::GetChildType(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100::GetChildType(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeOverview::GetChildType(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeTop100::GetChildType(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeOverview::GetLocalizedName(), and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeTop100::GetLocalizedName().
GetNodeInfo()
bool CDirectoryNode::GetNodeInfo (const std::string & strPath, NODE_TYPE & type, NODE_TYPE & childtype, CQueryParams & params) static
References ParseURL().
Referenced by XFILE::CMusicDatabaseDirectory::GetDirectoryNodeInfo().
GetParent()
CDirectoryNode * CDirectoryNode::GetParent () const
References m_pParent.
Referenced by BuildPath(), CollectQueryParams(), and XFILE::CMusicDatabaseDirectory::GetDirectoryParentType().
GetType()
NODE_TYPE CDirectoryNode::GetType () const
References m_Type.
Referenced by CollectQueryParams(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped::GetChildType(), and XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeGrouped::GetContentType().
ParseURL()
CDirectoryNode * CDirectoryNode::ParseURL (const std::string & strPath) static
References AddOptions(), CreateNode(), GetChildType(), CURL::GetFileName(), CURL::GetOptions(), XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ROOT, and URIUtils::RemoveSlashAtEnd().
Referenced by CMusicFileItemListModifier::AddQueuingFolder(), XFILE::CMusicDatabaseDirectory::CanCache(), XFILE::CMusicDatabaseDirectory::Exists(), GetDatabaseInfo(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectoryChildType(), XFILE::CMusicDatabaseDirectory::GetDirectoryParentType(), XFILE::CMusicDatabaseDirectory::GetDirectoryType(), XFILE::CMusicDatabaseDirectory::GetLabel(), and GetNodeInfo().
RemoveParent()
void CDirectoryNode::RemoveParent () protected
References m_pParent.
Member Data Documentation
m_options
CUrlOptions XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::m_options private
Referenced by AddOptions(), BuildPath(), and GetChilds().
m_pParent
CDirectoryNode* XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::m_pParent private
Referenced by BuildPath(), CDirectoryNode(), CollectQueryParams(), GetParent(), RemoveParent(), and ~CDirectoryNode().
m_strName
std::string XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::m_strName private
Referenced by BuildPath(), CDirectoryNode(), CollectQueryParams(), GetID(), and GetName().
m_Type
NODE_TYPE XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::m_Type private
Referenced by CDirectoryNode(), CollectQueryParams(), and GetType().
The documentation for this class was generated from the following files:
MusicDatabaseDirectory/DirectoryNode.h
MusicDatabaseDirectory/DirectoryNode.cpp