Kodi Documentation: CDatabase::Filter Class Reference
CDatabase::Filter Class Reference
#include <Database.h>
Public Member Functions
Filter ()
Filter (const char *w)
Filter (const std::string &w)
void AppendField (const std::string &strField)
void AppendJoin (const std::string &strJoin)
void AppendWhere (const std::string &strWhere, bool combineWithAnd=true)
void AppendOrder (const std::string &strOrder)
void AppendGroup (const std::string &strGroup)
Public Attributes
std::string fields
std::string join
std::string where
std::string order
std::string group
std::string limit
Constructor & Destructor Documentation
Filter() [1/3]
CDatabase::Filter::Filter () inline
Filter() [2/3]
CDatabase::Filter::Filter (const char * w) inline explicit
Filter() [3/3]
CDatabase::Filter::Filter (const std::string & w) inline explicit
Member Function Documentation
AppendField()
void CDatabase::Filter::AppendField (const std::string & strField)
References fields.
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetGenresJSON(), CVideoDatabase::GetNavCommon(), CMusicDatabase::GetOrderFilter(), CVideoDatabase::GetPeopleNav(), and CMusicDatabase::GetSongsByWhereJSON().
AppendGroup()
void CDatabase::Filter::AppendGroup (const std::string & strGroup)
Referenced by CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetCommonNav(), CMusicDatabase::GetDiscsByWhere(), CMusicDatabase::GetGenresNav(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsFullByWhere(), CMusicDatabase::GetSourcesNav(), and CVideoDatabase::GetYearsNav().
AppendJoin()
void CDatabase::Filter::AppendJoin (const std::string & strJoin)
Referenced by CMusicDatabase::AddSource(), CVideoDatabase::AppendIdLinkFilter(), CVideoDatabase::AppendLinkFilter(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetDiscsByWhere(), CVideoDatabase::GetFilter(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetGenresNav(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsFullByWhere(), CMusicDatabase::GetSourcesNav(), and CVideoDatabase::GetYearsNav().
AppendOrder()
void CDatabase::Filter::AppendOrder (const std::string & strOrder)
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetOrderFilter(), CMusicDatabase::GetSongsByWhereJSON(), and CMusicDatabase::GetSongsFullByWhere().
AppendWhere()
void CDatabase::Filter::AppendWhere (const std::string & strWhere, bool combineWithAnd = true)
Referenced by CMusicDatabase::AddSource(), CVideoDatabase::AppendIdLinkFilter(), CVideoDatabase::AppendLinkFilter(), PVR::CPVRCachedImages::Cleanup(), PVR::CPVRDatabase::Delete(), PVR::CPVRDatabase::Delete(), PVR::CPVREpgDatabase::Delete(), PVR::CPVRDatabase::Delete(), PVR::CPVRDatabase::Delete(), PVR::CPVREpgDatabase::DeleteEpgTags(), PVR::CPVREpgDatabase::DeleteEpgTags(), CMusicDatabase::ExportToXML(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetCommonNav(), PVR::CPVREpgDatabase::GetEpgTags(), CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetGenresNav(), CVideoDatabase::GetItems(), CVideoDatabase::GetMusicVideoAlbumsNav(), JSONRPC::CTextureOperations::GetTextures(), CVideoDatabase::GetTvShowsNav(), CMusicDatabase::GetYearsNav(), PVR::CPVREpgDatabase::QueueDeleteEpgQuery(), PVR::CPVREpgDatabase::QueueDeleteEpgTags(), PVR::CPVREpgDatabase::QueueDeleteEpgTagsByMinEndMaxStartTimeQuery(), PVR::CPVREpgDatabase::QueueDeleteLastEpgScanTimeQuery(), PVR::CPVRDatabase::QueueDeleteQuery(), PVR::CPVRDatabase::QueueDeleteQuery(), PVR::CPVREpgDatabase::QueueDeleteTagQuery(), and PVR::CPVRDatabase::RemoveChannelsFromGroup().
Member Data Documentation
fields
std::string CDatabase::Filter::fields
Referenced by AppendField(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetCommonNav(), CVideoDatabase::GetEpisodesByWhere(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetGenresNav(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CMusicDatabase::GetOrderFilter(), CVideoDatabase::GetPeopleNav(), CVideoDatabase::GetSeasonsByWhere(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsFullByWhere(), CMusicDatabase::GetSourcesNav(), CTextureDatabase::GetTextures(), and CVideoDatabase::GetTvShowsByWhere().
group
std::string CDatabase::Filter::group
Referenced by CDatabase::BuildSQL(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetCommonNav(), CVideoDatabase::GetEpisodesByActor(), CMusicDatabase::GetGenresNav(), CVideoDatabase::GetMoviesByActor(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), and CMusicDatabase::GetSourcesNav().
join
std::string CDatabase::Filter::join
Referenced by CDatabase::BuildSQL(), CMusicDatabase::GetArtistsByWhereJSON(), CVideoDatabase::GetEpisodesByActor(), CVideoDatabase::GetEpisodesNav(), CVideoDatabase::GetMoviesByActor(), CVideoDatabase::GetSeasonsNav(), CVideoDatabase::GetSetsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsFullByWhere(), and CVideoDatabase::GetTvShowsByActor().
limit
std::string CDatabase::Filter::limit
Referenced by CDatabase::BuildSQL(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetDiscsByWhere(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetRecentlyAddedEpisodesNav(), CVideoDatabase::GetRecentlyAddedMoviesNav(), CVideoDatabase::GetRecentlyAddedMusicVideosNav(), CVideoDatabase::GetSeasonsByWhere(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsFullByWhere(), and CVideoDatabase::GetTvShowsByWhere().
order
std::string CDatabase::Filter::order
Referenced by CDatabase::BuildSQL(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetCommonNav(), CMusicDatabase::GetGenresNav(), CVideoDatabase::GetInProgressTvShowsNav(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), CVideoDatabase::GetRecentlyAddedEpisodesNav(), CVideoDatabase::GetRecentlyAddedMoviesNav(), CVideoDatabase::GetRecentlyAddedMusicVideosNav(), CVideoDatabase::GetSetsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsFullByWhere(), and CMusicDatabase::GetSourcesNav().
where
std::string CDatabase::Filter::where
Referenced by CDatabase::BuildSQL(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetDiscsByWhere(), CVideoDatabase::GetEpisodesByActor(), CVideoDatabase::GetEpisodesNav(), CMusicDatabase::GetGenresNav(), CVideoDatabase::GetInProgressTvShowsNav(), CGUIDialogMediaFilter::GetItems(), CGUIDialogVideoInfo::GetItemsForTag(), CVideoDatabase::GetMoviesByActor(), CMusicDatabase::GetRandomSongIDs(), CGUIDialogMediaFilter::GetRange(), CVideoDatabase::GetSeasonsNav(), CVideoDatabase::GetSetInfo(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsCount(), CMusicDatabase::GetSongsFullByWhere(), CMusicDatabase::GetSourcesNav(), and CVideoDatabase::GetTvShowsByActor().
The documentation for this class was generated from the following files:
Database.h
Database.cpp