Kodi Documentation: TestDatabaseUtils.cpp File Reference
TestDatabaseUtils.cpp File Reference
#include "dbwrappers/qry_dat.h"
#include "music/MusicDatabase.h"
#include "utils/DatabaseUtils.h"
#include "utils/StringUtils.h"
#include "utils/Variant.h"
#include "video/VideoDatabase.h"
#include <gtest/gtest.h>
Classes
class TestDatabaseUtilsHelper
Functions
TEST (TestDatabaseUtils, GetField_None)
TEST (TestDatabaseUtils, GetField_MediaTypeAlbum)
TEST (TestDatabaseUtils, GetField_MediaTypeSong)
TEST (TestDatabaseUtils, GetField_MediaTypeMusicVideo)
TEST (TestDatabaseUtils, GetField_MediaTypeMovie)
TEST (TestDatabaseUtils, GetField_MediaTypeTvShow)
TEST (TestDatabaseUtils, GetField_MediaTypeEpisode)
TEST (TestDatabaseUtils, GetField_FieldRandom)
TEST (TestDatabaseUtils, GetFieldIndex_None)
TEST (TestDatabaseUtils, GetFieldIndex_MediaTypeAlbum)
TEST (TestDatabaseUtils, GetFieldIndex_MediaTypeSong)
TEST (TestDatabaseUtils, GetFieldIndex_MediaTypeMusicVideo)
TEST (TestDatabaseUtils, GetFieldIndex_MediaTypeMovie)
TEST (TestDatabaseUtils, GetFieldIndex_MediaTypeTvShow)
TEST (TestDatabaseUtils, GetFieldIndex_MediaTypeEpisode)
TEST (TestDatabaseUtils, GetSelectFields)
TEST (TestDatabaseUtils, GetFieldValue)
TEST (TestDatabaseUtils, BuildLimitClause)
Function Documentation
TEST() [1/18]
TEST (TestDatabaseUtils , BuildLimitClause)
Todo:
Need some way to test this function
References DatabaseUtils::BuildLimitClause().
TEST() [2/18]
TEST (TestDatabaseUtils , GetField_FieldRandom)
References DatabaseQueryPartOrderBy, DatabaseQueryPartSelect, DatabaseQueryPartWhere, FieldRandom, DatabaseUtils::GetField(), and MediaTypeEpisode.
TEST() [3/18]
TEST (TestDatabaseUtils , GetField_MediaTypeAlbum)
References DatabaseQueryPartOrderBy, DatabaseQueryPartSelect, DatabaseQueryPartWhere, FieldAlbum, FieldAlbumArtist, FieldAlbumType, FieldArtist, FieldDateAdded, FieldGenre, FieldId, FieldMoods, FieldMusicLabel, FieldNone, FieldOrigYear, FieldRating, FieldReview, FieldStyles, FieldThemes, FieldUserRating, FieldVotes, FieldYear, DatabaseUtils::GetField(), and MediaTypeAlbum.
TEST() [4/18]
TEST (TestDatabaseUtils , GetField_MediaTypeEpisode)
References DatabaseQueryPartSelect, FieldAirDate, FieldDateAdded, FieldDirector, FieldEpisodeNumber, FieldFilename, FieldId, FieldLastPlayed, FieldMPAA, FieldPath, FieldPlaycount, FieldPlot, FieldRandom, FieldRating, FieldSeason, FieldStudio, FieldTime, FieldTitle, FieldTvShowTitle, FieldUserRating, FieldVotes, FieldWriter, FieldYear, KODI::UTILS::StringUtils::Format(), DatabaseUtils::GetField(), MediaTypeEpisode, VIDEODB_ID_EPISODE_AIRED, VIDEODB_ID_EPISODE_CREDITS, VIDEODB_ID_EPISODE_DIRECTOR, VIDEODB_ID_EPISODE_EPISODE, VIDEODB_ID_EPISODE_PLOT, VIDEODB_ID_EPISODE_RUNTIME, VIDEODB_ID_EPISODE_SEASON, and VIDEODB_ID_EPISODE_TITLE.
TEST() [5/18]
TEST (TestDatabaseUtils , GetField_MediaTypeMovie)
References DatabaseQueryPartOrderBy, DatabaseQueryPartSelect, FieldCountry, FieldDateAdded, FieldDirector, FieldFilename, FieldGenre, FieldId, FieldLastPlayed, FieldMPAA, FieldPath, FieldPlaycount, FieldPlot, FieldPlotOutline, FieldRandom, FieldRating, FieldSortTitle, FieldStudio, FieldTagline, FieldTime, FieldTitle, FieldTop250, FieldTrailer, FieldUserRating, FieldVotes, FieldWriter, KODI::UTILS::StringUtils::Format(), DatabaseUtils::GetField(), MediaTypeMovie, VIDEODB_ID_COUNTRY, VIDEODB_ID_CREDITS, VIDEODB_ID_DIRECTOR, VIDEODB_ID_GENRE, VIDEODB_ID_MPAA, VIDEODB_ID_PLOT, VIDEODB_ID_PLOTOUTLINE, VIDEODB_ID_RUNTIME, VIDEODB_ID_SORTTITLE, VIDEODB_ID_STUDIOS, VIDEODB_ID_TAGLINE, VIDEODB_ID_TITLE, VIDEODB_ID_TOP250, and VIDEODB_ID_TRAILER.
TEST() [6/18]
TEST (TestDatabaseUtils , GetField_MediaTypeMusicVideo)
References DatabaseQueryPartOrderBy, DatabaseQueryPartSelect, DatabaseQueryPartWhere, FieldAlbum, FieldArtist, FieldDateAdded, FieldDirector, FieldFilename, FieldGenre, FieldId, FieldLastPlayed, FieldPath, FieldPlaycount, FieldPlot, FieldStudio, FieldTime, FieldTitle, FieldTrackNumber, FieldUserRating, FieldVideoResolution, KODI::UTILS::StringUtils::Format(), DatabaseUtils::GetField(), MediaTypeMusicVideo, VIDEODB_ID_MUSICVIDEO_ALBUM, VIDEODB_ID_MUSICVIDEO_ARTIST, VIDEODB_ID_MUSICVIDEO_DIRECTOR, VIDEODB_ID_MUSICVIDEO_GENRE, VIDEODB_ID_MUSICVIDEO_PLOT, VIDEODB_ID_MUSICVIDEO_RUNTIME, VIDEODB_ID_MUSICVIDEO_STUDIOS, VIDEODB_ID_MUSICVIDEO_TITLE, and VIDEODB_ID_MUSICVIDEO_TRACK.
TEST() [7/18]
TEST (TestDatabaseUtils , GetField_MediaTypeSong)
References DatabaseQueryPartOrderBy, DatabaseQueryPartSelect, DatabaseQueryPartWhere, FieldAlbum, FieldAlbumArtist, FieldArtist, FieldComment, FieldDateAdded, FieldEndOffset, FieldFilename, FieldGenre, FieldId, FieldLastPlayed, FieldOrigYear, FieldPath, FieldPlaycount, FieldRating, FieldStartOffset, FieldTime, FieldTitle, FieldTrackNumber, FieldUserRating, FieldVotes, FieldYear, DatabaseUtils::GetField(), and MediaTypeSong.
TEST() [8/18]
TEST (TestDatabaseUtils , GetField_MediaTypeTvShow)
References DatabaseQueryPartOrderBy, DatabaseQueryPartSelect, FieldDateAdded, FieldGenre, FieldId, FieldMPAA, FieldNumberOfEpisodes, FieldNumberOfWatchedEpisodes, FieldPath, FieldPlot, FieldRandom, FieldRating, FieldSeason, FieldSortTitle, FieldStudio, FieldTitle, FieldTvShowStatus, FieldUserRating, FieldVotes, FieldYear, KODI::UTILS::StringUtils::Format(), DatabaseUtils::GetField(), MediaTypeTvShow, VIDEODB_ID_TV_GENRE, VIDEODB_ID_TV_MPAA, VIDEODB_ID_TV_PLOT, VIDEODB_ID_TV_PREMIERED, VIDEODB_ID_TV_SORTTITLE, VIDEODB_ID_TV_STATUS, VIDEODB_ID_TV_STUDIOS, and VIDEODB_ID_TV_TITLE.
TEST() [9/18]
TEST (TestDatabaseUtils , GetField_None)
References DatabaseQueryPartSelect, FieldNone, DatabaseUtils::GetField(), MediaTypeMovie, and MediaTypeNone.
TEST() [10/18]
TEST (TestDatabaseUtils , GetFieldIndex_MediaTypeAlbum)
Todo:
Should enums in CMusicDatabase be made public instead?
References TestDatabaseUtilsHelper::album_dtDateAdded, TestDatabaseUtilsHelper::album_fRating, TestDatabaseUtilsHelper::album_idAlbum, TestDatabaseUtilsHelper::album_strAlbum, TestDatabaseUtilsHelper::album_strArtists, TestDatabaseUtilsHelper::album_strGenres, TestDatabaseUtilsHelper::album_strLabel, TestDatabaseUtilsHelper::album_strMoods, TestDatabaseUtilsHelper::album_strOrigReleaseDate, TestDatabaseUtilsHelper::album_strReleaseDate, TestDatabaseUtilsHelper::album_strReview, TestDatabaseUtilsHelper::album_strStyles, TestDatabaseUtilsHelper::album_strThemes, TestDatabaseUtilsHelper::album_strType, EXPECT_EQ(), FieldAlbum, FieldAlbumArtist, FieldAlbumType, FieldArtist, FieldDateAdded, FieldGenre, FieldId, FieldMoods, FieldMusicLabel, FieldOrigYear, FieldRandom, FieldRating, FieldReview, FieldStyles, FieldThemes, FieldYear, DatabaseUtils::GetFieldIndex(), and MediaTypeAlbum.
TEST() [11/18]
TEST (TestDatabaseUtils , GetFieldIndex_MediaTypeEpisode)
References EXPECT_EQ(), FieldAirDate, FieldDateAdded, FieldDirector, FieldEpisodeNumber, FieldFilename, FieldId, FieldLastPlayed, FieldMPAA, FieldPath, FieldPlaycount, FieldPlot, FieldRandom, FieldRating, FieldSeason, FieldStudio, FieldTime, FieldTitle, FieldTvShowTitle, FieldUserRating, FieldVotes, FieldWriter, FieldYear, DatabaseUtils::GetFieldIndex(), MediaTypeEpisode, VIDEODB_DETAILS_EPISODE_DATEADDED, VIDEODB_DETAILS_EPISODE_FILE, VIDEODB_DETAILS_EPISODE_LASTPLAYED, VIDEODB_DETAILS_EPISODE_PATH, VIDEODB_DETAILS_EPISODE_PLAYCOUNT, VIDEODB_DETAILS_EPISODE_RATING, VIDEODB_DETAILS_EPISODE_TVSHOW_AIRED, VIDEODB_DETAILS_EPISODE_TVSHOW_MPAA, VIDEODB_DETAILS_EPISODE_TVSHOW_NAME, VIDEODB_DETAILS_EPISODE_TVSHOW_STUDIO, VIDEODB_DETAILS_EPISODE_USER_RATING, VIDEODB_DETAILS_EPISODE_VOTES, VIDEODB_ID_EPISODE_AIRED, VIDEODB_ID_EPISODE_CREDITS, VIDEODB_ID_EPISODE_DIRECTOR, VIDEODB_ID_EPISODE_EPISODE, VIDEODB_ID_EPISODE_PLOT, VIDEODB_ID_EPISODE_RUNTIME, VIDEODB_ID_EPISODE_SEASON, and VIDEODB_ID_EPISODE_TITLE.
TEST() [12/18]
TEST (TestDatabaseUtils , GetFieldIndex_MediaTypeMovie)
References EXPECT_EQ(), FieldCountry, FieldDateAdded, FieldDirector, FieldFilename, FieldGenre, FieldId, FieldLastPlayed, FieldMPAA, FieldPath, FieldPlaycount, FieldPlot, FieldPlotOutline, FieldRandom, FieldRating, FieldSortTitle, FieldStudio, FieldTagline, FieldTime, FieldTitle, FieldTop250, FieldTrailer, FieldUserRating, FieldVotes, FieldWriter, FieldYear, DatabaseUtils::GetFieldIndex(), MediaTypeMovie, VIDEODB_DETAILS_MOVIE_DATEADDED, VIDEODB_DETAILS_MOVIE_FILE, VIDEODB_DETAILS_MOVIE_LASTPLAYED, VIDEODB_DETAILS_MOVIE_PATH, VIDEODB_DETAILS_MOVIE_PLAYCOUNT, VIDEODB_DETAILS_MOVIE_PREMIERED, VIDEODB_DETAILS_MOVIE_RATING, VIDEODB_DETAILS_MOVIE_USER_RATING, VIDEODB_DETAILS_MOVIE_VOTES, VIDEODB_ID_COUNTRY, VIDEODB_ID_CREDITS, VIDEODB_ID_DIRECTOR, VIDEODB_ID_GENRE, VIDEODB_ID_MPAA, VIDEODB_ID_PLOT, VIDEODB_ID_PLOTOUTLINE, VIDEODB_ID_RUNTIME, VIDEODB_ID_SORTTITLE, VIDEODB_ID_STUDIOS, VIDEODB_ID_TAGLINE, VIDEODB_ID_TITLE, VIDEODB_ID_TOP250, and VIDEODB_ID_TRAILER.
TEST() [13/18]
TEST (TestDatabaseUtils , GetFieldIndex_MediaTypeMusicVideo)
References EXPECT_EQ(), FieldAlbum, FieldArtist, FieldDateAdded, FieldDirector, FieldFilename, FieldGenre, FieldId, FieldLastPlayed, FieldPath, FieldPlaycount, FieldPlot, FieldRandom, FieldStudio, FieldTime, FieldTitle, FieldTrackNumber, FieldUserRating, FieldYear, DatabaseUtils::GetFieldIndex(), MediaTypeMusicVideo, VIDEODB_DETAILS_MUSICVIDEO_DATEADDED, VIDEODB_DETAILS_MUSICVIDEO_FILE, VIDEODB_DETAILS_MUSICVIDEO_LASTPLAYED, VIDEODB_DETAILS_MUSICVIDEO_PATH, VIDEODB_DETAILS_MUSICVIDEO_PLAYCOUNT, VIDEODB_DETAILS_MUSICVIDEO_PREMIERED, VIDEODB_DETAILS_MUSICVIDEO_USER_RATING, VIDEODB_ID_MUSICVIDEO_ALBUM, VIDEODB_ID_MUSICVIDEO_ARTIST, VIDEODB_ID_MUSICVIDEO_DIRECTOR, VIDEODB_ID_MUSICVIDEO_GENRE, VIDEODB_ID_MUSICVIDEO_PLOT, VIDEODB_ID_MUSICVIDEO_RUNTIME, VIDEODB_ID_MUSICVIDEO_STUDIOS, VIDEODB_ID_MUSICVIDEO_TITLE, and VIDEODB_ID_MUSICVIDEO_TRACK.
TEST() [14/18]
TEST (TestDatabaseUtils , GetFieldIndex_MediaTypeSong)
References EXPECT_EQ(), FieldAlbum, FieldArtist, FieldComment, FieldEndOffset, FieldFilename, FieldGenre, FieldId, FieldLastPlayed, FieldPath, FieldPlaycount, FieldRandom, FieldRating, FieldStartOffset, FieldTime, FieldTitle, FieldTrackNumber, FieldUserRating, FieldVotes, FieldYear, DatabaseUtils::GetFieldIndex(), MediaTypeSong, TestDatabaseUtilsHelper::song_comment, TestDatabaseUtilsHelper::song_idSong, TestDatabaseUtilsHelper::song_iDuration, TestDatabaseUtilsHelper::song_iEndOffset, TestDatabaseUtilsHelper::song_iStartOffset, TestDatabaseUtilsHelper::song_iTimesPlayed, TestDatabaseUtilsHelper::song_iTrack, TestDatabaseUtilsHelper::song_lastplayed, TestDatabaseUtilsHelper::song_rating, TestDatabaseUtilsHelper::song_strAlbum, TestDatabaseUtilsHelper::song_strArtists, TestDatabaseUtilsHelper::song_strFileName, TestDatabaseUtilsHelper::song_strGenres, TestDatabaseUtilsHelper::song_strPath, TestDatabaseUtilsHelper::song_strReleaseDate, TestDatabaseUtilsHelper::song_strTitle, TestDatabaseUtilsHelper::song_userrating, and TestDatabaseUtilsHelper::song_votes.
TEST() [15/18]
TEST (TestDatabaseUtils , GetFieldIndex_MediaTypeTvShow)
References EXPECT_EQ(), FieldDateAdded, FieldGenre, FieldId, FieldMPAA, FieldNumberOfEpisodes, FieldNumberOfWatchedEpisodes, FieldPath, FieldPlot, FieldRandom, FieldRating, FieldSeason, FieldSortTitle, FieldStudio, FieldTitle, FieldTvShowStatus, FieldUserRating, FieldVotes, FieldYear, DatabaseUtils::GetFieldIndex(), MediaTypeTvShow, VIDEODB_DETAILS_TVSHOW_DATEADDED, VIDEODB_DETAILS_TVSHOW_NUM_EPISODES, VIDEODB_DETAILS_TVSHOW_NUM_SEASONS, VIDEODB_DETAILS_TVSHOW_NUM_WATCHED, VIDEODB_DETAILS_TVSHOW_PATH, VIDEODB_DETAILS_TVSHOW_RATING, VIDEODB_DETAILS_TVSHOW_USER_RATING, VIDEODB_DETAILS_TVSHOW_VOTES, VIDEODB_ID_TV_GENRE, VIDEODB_ID_TV_MPAA, VIDEODB_ID_TV_PLOT, VIDEODB_ID_TV_PREMIERED, VIDEODB_ID_TV_SORTTITLE, VIDEODB_ID_TV_STATUS, VIDEODB_ID_TV_STUDIOS, and VIDEODB_ID_TV_TITLE.
TEST() [16/18]
TEST (TestDatabaseUtils , GetFieldIndex_None)
References EXPECT_EQ(), FieldNone, FieldRandom, DatabaseUtils::GetFieldIndex(), MediaTypeAlbum, and MediaTypeNone.
TEST() [17/18]
TEST (TestDatabaseUtils , GetFieldValue)
References EXPECT_TRUE(), DatabaseUtils::GetFieldValue(), CVariant::isNull(), CVariant::isString(), and dbiplus::field_value::set_isNull().
TEST() [18/18]
TEST (TestDatabaseUtils , GetSelectFields)
References EXPECT_TRUE(), FieldAlbum, FieldArtist, FieldGenre, FieldId, fields, FieldTitle, DatabaseUtils::GetSelectFields(), MediaTypeAlbum, and MediaTypeNone.