Kodi Documentation: XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped Class Reference
XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped Class Reference
#include <DirectoryNodeGrouped.h>
Public Member Functions
CDirectoryNodeGrouped (NODE_TYPE type, const std::string &strName, CDirectoryNode *pParent)
Public Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
virtual ~CDirectoryNode ()
NODE_TYPE GetType () const
bool GetChilds (CFileItemList &items)
void CollectQueryParams (CQueryParams &params) const
CDirectoryNode * GetParent () const
std::string BuildPath () const
virtual bool CanCache () const
Protected Member Functions
NODE_TYPE GetChildType () const override
bool GetContent (CFileItemList &items) const override
std::string GetLocalizedName () const override
Protected Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
CDirectoryNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
void AddOptions (const std::string &options)
const std::string & GetName () const
int GetID () const
void RemoveParent ()
Private Member Functions
std::string GetContentType () const
std::string GetContentType (const CQueryParams &params) const
Additional Inherited Members
Static Public Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
static CDirectoryNode * ParseURL (const std::string &strPath)
static void GetDatabaseInfo (const std::string &strPath, CQueryParams &params)
Static Protected Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
static CDirectoryNode * CreateNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
Constructor & Destructor Documentation
CDirectoryNodeGrouped()
CDirectoryNodeGrouped::CDirectoryNodeGrouped (NODE_TYPE type, const std::string & strName, CDirectoryNode * pParent)
Member Function Documentation
GetChildType()
NODE_TYPE CDirectoryNodeGrouped::GetChildType () const override protected virtual
Reimplemented from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode.
References XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::CollectQueryParams(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetContentType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetType(), MOVIES, MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ACTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_ALBUM, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MUSICVIDEOS, and XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_TVSHOWS.
GetContent()
bool CDirectoryNodeGrouped::GetContent (CFileItemList & items) const override protected virtual
Reimplemented from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode.
References XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::BuildPath(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::CollectQueryParams(), CDbUrl::FromString(), GetContentType(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetContentType(), CVideoDatabase::GetItems(), CVideoDatabase::Open(), and CDbUrl::ToString().
GetContentType() [1/2]
std::string CDirectoryNodeGrouped::GetContentType () const private
References XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::CollectQueryParams(), and GetContentType().
Referenced by GetContent(), GetContentType(), and GetLocalizedName().
GetContentType() [2/2]
std::string CDirectoryNodeGrouped::GetContentType (const CQueryParams & params) const private
References XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetContentType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetType(), MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ACTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_COUNTRY, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_DIRECTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_INPROGRESS_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MOVIES_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_ALBUM, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_NONE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ROOT, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SEASONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SETS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_STUDIO, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TAGS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TVSHOWS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_VIDEOVERSIONS, and XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_YEAR.
GetLocalizedName()
std::string CDirectoryNodeGrouped::GetLocalizedName () const override protected virtual
Reimplemented from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode.
References GetContentType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetID(), CVideoDatabase::GetItemById(), and CVideoDatabase::Open().
The documentation for this class was generated from the following files:
VideoDatabaseDirectory/DirectoryNodeGrouped.h
VideoDatabaseDirectory/DirectoryNodeGrouped.cpp