Kodi Documentation: XFILE::CFile Class Reference
XFILE::CFile Class Reference
#include <File.h>
Public Member Functions
CFile ()
~CFile ()
bool CURLCreate (const std::string &url)
bool CURLAddOption (XFILE::CURLOPTIONTYPE type, const char *name, const char *value)
bool CURLOpen (unsigned int flags)
bool Open (const CURL &file, const unsigned int flags=0)
bool Open (const std::string &strFileName, const unsigned int flags=0)
bool OpenForWrite (const CURL &file, bool bOverWrite=false)
bool OpenForWrite (const std::string &strFileName, bool bOverWrite=false)
ssize_t LoadFile (const CURL &file, std::vector< uint8_t > &outputBuffer)
ssize_t Read (void *bufPtr, size_t bufSize)
bool ReadString (std::vector< char > &line)
String reading by line.
bool ReadString (char *szLine, int iLineLength)
ssize_t Write (const void *bufPtr, size_t bufSize)
void Flush ()
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET)
int Truncate (int64_t iSize)
int64_t GetPosition () const
int64_t GetLength ()
void Close ()
int GetChunkSize ()
const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
ssize_t LoadFile (const std::string &filename, std::vector< uint8_t > &outputBuffer)
const std::unique_ptr< BitstreamStats > & GetBitstreamStats () const
int IoControl (EIoControl request, void *param)
IFile * GetImplementation () const
int Stat (struct __stat64 *buffer)
double GetDownloadSpeed ()
Static Public Member Functions
static int DetermineChunkSize (const int srcChunkSize, const int reqChunkSize)
static bool Exists (const CURL &file, bool bUseCache=true)
static bool Delete (const CURL &file)
static int Stat (const CURL &file, struct __stat64 *buffer)
static bool Rename (const CURL &file, const CURL &urlNew)
static bool Copy (const CURL &file, const CURL &dest, XFILE::IFileCallback *pCallback=NULL, void *pContext=NULL)
static bool SetHidden (const CURL &file, bool hidden)
static bool Exists (const std::string &strFileName, bool bUseCache=true)
static int Stat (const std::string &strFileName, struct __stat64 *buffer)
static bool Delete (const std::string &strFileName)
static bool Rename (const std::string &strFileName, const std::string &strNewFileName)
static bool Copy (const std::string &strFileName, const std::string &strDest, XFILE::IFileCallback *pCallback=NULL, void *pContext=NULL)
static bool SetHidden (const std::string &fileName, bool hidden)
Private Member Functions
bool ShouldUseStreamBuffer (const CURL &url)
Determines if CFileStreamBuffer should be used to read a file.
Private Attributes
unsigned int m_flags = 0
CURL m_curl
std::unique_ptr< IFile > m_pFile
std::unique_ptr< CFileStreamBuffer > m_pBuffer
std::unique_ptr< BitstreamStats > m_bitStreamStats
Constructor & Destructor Documentation
CFile()
CFile::CFile () default
~CFile()
CFile::~CFile ()
References Close().
Member Function Documentation
Close()
void CFile::Close ()
References CLog::Log(), LOGERROR, m_pBuffer, m_pFile, and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by CDVDDemuxFFmpeg::AddStream(), CDVDInputStreamFile::Close(), XFILE::CFileCache::Close(), XFILE::CImageFile::Close(), XFILE::CMusicDatabaseFile::Close(), XFILE::COverrideFile::Close(), XFILE::CZipFile::Close(), Copy(), CXBMCTestUtils::CreateCorruptedFile(), CTempFile::Delete(), dll_close(), dll_open(), KODI::CDRIP::CCDDARipJob::DoWork(), CVideoDatabase::DumpToDummyFiles(), CZipManager::GetZipList(), KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListPLS::Load(), KODI::PLAYLIST::CPlayListURL::Load(), CWebServer::LoadCert(), KODI::RETRO::CCheevos::LoadData(), CGUIDialogFileBrowser::OnMessage(), CAirPlayServer::CTCPClient::ProcessRequest(), CEdl::ReadComskip(), CEdl::ReadEdl(), CDDSImage::ReadFile(), CEdl::ReadVideoReDo(), CAirTunesServer::SetCoverArtFromBuffer(), CScreenShot::TakeScreenshot(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), CDDB::Xcddb::writeCacheFile(), ~CFile(), FileReader::~FileReader(), and MUSIC_INFO::TagLibVFSStream::~TagLibVFSStream().
Copy() [1/2]
bool CFile::Copy (const CURL & file, const CURL & dest, XFILE::IFileCallback * pCallback = NULL, void * pContext = NULL) static
References Close(), XFILE::CDirectory::Create(), Delete(), DetermineChunkSize(), end(), Exists(), CURL::Get(), CServiceBroker::GetAppComponents(), URIUtils::GetDirectory(), CStopWatch::GetElapsedSeconds(), CURL::GetFileName(), CURL::GetProtocol(), CURL::GetRedacted(), URIUtils::IsHD(), URIUtils::IsInAPK(), CLog::Log(), LOGERROR, XFILE::IFileCallback::OnFileCallback(), OpenForWrite(), XFILE::READ_CHUNKED, XFILE::READ_TRUNCATED, URIUtils::RemoveSlashAtEnd(), CApplicationPowerHandling::ResetScreenSaver(), CURL::SetOptions(), CStopWatch::StartZero(), and Write().
Referenced by Copy(), XBMCAddon::xbmcvfs::copy(), ADDON::Interface_Filesystem::copy_file(), CUtil::CopyUserDataIfNeeded(), KODI::CDRIP::CCDDARipJob::DoWork(), CFileOperationJob::CFileOperation::ExecuteOperation(), CTextureCache::Export(), CTextureCache::Export(), CZipManager::ExtractArchive(), DllLoaderContainer::FindModule(), ADDON::CAddonDll::GetDllPath(), CGUIDialogSubtitles::OnDownloadComplete(), XFILE::CZipFile::Open(), XFILE::CPosixFile::Rename(), CUtil::ScanForExternalSubtitles(), CTVOSTopShelf::SetTopShelfItems(), CGUIDialogProfileSettings::ShowForProfile(), and TEST().
Copy() [2/2]
bool CFile::Copy (const std::string & strFileName, const std::string & strDest, XFILE::IFileCallback * pCallback = NULL, void * pContext = NULL) static
References Copy().
CURLAddOption()
bool CFile::CURLAddOption (XFILE::CURLOPTIONTYPE type, const char * name, const char * value)
References XFILE::CURL_OPTION_CREDENTIALS, XFILE::CURL_OPTION_HEADER, XFILE::CURL_OPTION_OPTION, XFILE::CURL_OPTION_PROTOCOL, m_curl, name, CURL::SetOption(), CURL::SetPassword(), CURL::SetProtocolOption(), CURL::SetUserName(), and value.
CURLCreate()
bool CFile::CURLCreate (const std::string & url)
References m_curl, and CURL::Parse().
Referenced by KODI::RETRO::CCheevos::LoadData().
CURLOpen()
bool CFile::CURLOpen (unsigned int flags)
References m_curl, and Open().
Referenced by KODI::RETRO::CCheevos::LoadData().
Delete() [1/2]
bool CFile::Delete (const CURL & file) static
References CPasswordManager::AuthenticateURL(), XFILE::CDirectoryCache::ClearFile(), XFILE::CFileFactory::CreateLoader(), Exists(), g_directoryCache, CURL::Get(), CPasswordManager::GetInstance(), CURL::GetUserName(), CLog::Log(), LOGERROR, URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by CDVDDemuxFFmpeg::AddStream(), ADDON::CScraper::ClearCache(), CTextureCache::ClearCachedImage(), CTextureCache::ClearCachedImage(), XFILE::CMusicDatabaseDirectory::ClearDirectoryCache(), XFILE::CVideoDatabaseDirectory::ClearDirectoryCache(), ClearPhotoAssetCache(), CUtil::ClearSubtitles(), KODI::UTILS::FONT::ClearTemporaryFonts(), Copy(), XFILE::COverrideFile::Delete(), Delete(), ADDON::Interface_Filesystem::delete_file(), CMusicDatabase::DeleteCDDBInfo(), CUtil::DeleteDirectoryCache(), XBMCAddon::xbmcvfs::deleteFile(), KODI::RETRO::CSavestateDatabase::DeleteSavestate(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), KODI::CDRIP::CCDDARipJob::DoWork(), CFileOperationJob::CFileOperation::ExecuteOperation(), CLog::Initialize(), CProfileManager::Load(), CMusicDatabase::LookupCDDBInfo(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogSmartPlaylistEditor::OnOK(), XFILE::CPlaylistFileDirectory::Remove(), XFILE::CSmartPlaylistDirectory::Remove(), ADDON::Interface_Filesystem::remove_directory(), CFileItemList::RemoveDiscCache(), CUtil::RemoveTempFiles(), XFILE::CPosixFile::Rename(), CSettings::Reset(), CAirTunesServer::ResetMetadata(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), and XBMCHelper::Uninstall().
Delete() [2/2]
bool CFile::Delete (const std::string & strFileName) static
References Delete().
DetermineChunkSize()
int CFile::DetermineChunkSize (const int srcChunkSize, const int reqChunkSize) static
Referenced by XFILE::CFileStreamBuffer::Attach(), Copy(), LoadFile(), and XFILE::CFileCache::Open().
Exists() [1/2]
bool CFile::Exists (const CURL & file, bool bUseCache = true) static
References CPasswordManager::AuthenticateURL(), XFILE::CFileFactory::CreateLoader(), XFILE::CDirectoryCache::FileExists(), g_directoryCache, CURL::Get(), CPasswordManager::GetInstance(), CURL::GetUserName(), CLog::Log(), LOGDEBUG, LOGERROR, XFILE::CRedirectException::m_pNewFileImp, XFILE::CRedirectException::m_pNewUrl, URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by jni::CJNIXBMCFile::_open(), CDVDFileInfo::AddExternalSubtitleToDetails(), CVideoDatabase::CleanDatabase(), CMusicDatabase::CleanupSongsByIds(), CTextureCache::ClearCachedImage(), CTextureCache::ClearCachedImage(), KODI::RETRO::CReversiblePlayback::CommitSavestate(), Copy(), CUtil::CopyUserDataIfNeeded(), CApplication::Create(), CWinSystemWin32::CWinSystemWin32(), Delete(), CBlurayCallback::dir_open(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CFileItem::Exists(), XFILE::CAudioBookFileDirectory::Exists(), XFILE::CFileCache::Exists(), XFILE::CImageFile::Exists(), XFILE::CMultiPathFile::Exists(), XFILE::COverrideFile::Exists(), Exists(), CFileUtils::Exists(), XBMCAddon::xbmcvfs::exists(), CTextureCache::Export(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), ADDON::Interface_Filesystem::file_exists(), CFileItemList::FilterCueItems(), CFileItem::FindLocalArt(), DllLoaderContainer::FindModule(), CScraperUrl::Get(), ADDON::CAddonDll::GetDllPath(), CUtil::GetNextPathname(), KODI::UTILS::FONT::FONTPATH::GetSystemFontPath(), KODI::ART::GetTBNFile(), CGUITextureManager::GetTexturePath(), CProfileManager::GetUserDataItem(), CFileItem::GetUserMusicThumb(), CUtil::GetVobSubIdxFromSub(), CUtil::GetVobSubSubFromIdx(), CSettings::InitializeDefinitions(), CDDB::Xcddb::isCDCached(), CDDB::Xcddb::isCDCached(), CColorManager::IsValid(), CDecoderFilterManager::Load(), CProfileManager::Load(), CSettings::Load(), KODI::GAME::CGameClientInGameSaves::Load(), CPODocument::LoadFile(), KODI::RETRO::CRPRenderManager::LoadVideoFrameSync(), CGUIDialogSubtitles::OnDownloadComplete(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogSmartPlaylistEditor::OnMessage(), XFILE::CZipFile::Open(), CAirPlayServer::CTCPClient::ProcessRequest(), CEdl::ReadBeyondTV(), CEdl::ReadComskip(), CEdl::ReadEdl(), CEdl::ReadVideoReDo(), CFileItemList::RemoveDiscCache(), CSettings::Reset(), CCueDocument::ResolvePath(), XFILE::CCurlFile::SetCommonOptions(), CTVOSTopShelf::SetTopShelfItems(), CGUIDialogProfileSettings::ShowForProfile(), XFILE::CXbtFile::Stat(), XFILE::CZipFile::Stat(), CApplication::Stop(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Exists() [2/2]
bool CFile::Exists (const std::string & strFileName, bool bUseCache = true) static
References Exists().
Flush()
void CFile::Flush ()
References CLog::Log(), LOGERROR, m_pFile, and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by dll__commit(), and dll_fflush().
GetBitstreamStats()
const std::unique_ptr< BitstreamStats > & XFILE::CFile::GetBitstreamStats () const inline
References m_bitStreamStats.
Referenced by CDVDInputStreamFile::GetBitstreamStats().
GetChunkSize()
int CFile::GetChunkSize ()
References m_pFile.
Referenced by CVideoTagLoaderFFmpeg::CVideoTagLoaderFFmpeg(), CDVDInputStreamFile::GetBlockSize(), ActiveAE::CActiveAESound::GetChunkSize(), MUSIC_INFO::CMusicInfoTagLoaderFFmpeg::Load(), LoadFile(), and XFILE::CFileCache::Open().
GetDownloadSpeed()
double CFile::GetDownloadSpeed ()
References m_pFile.
GetImplementation()
IFile * XFILE::CFile::GetImplementation () const inline
References m_pFile.
Referenced by XFILE::CFileCache::GetFileImp(), XFILE::CFileCache::GetProperty(), and CDVDInputStreamFile::Open().
GetLength()
int64_t CFile::GetLength ()
References CLog::Log(), LOGERROR, m_pFile, and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by cfile_file_seek(), dll_feof(), dll_fgets(), dll_fstati64(), CBlurayCallback::file_eof(), CDVDInputStreamFile::GetLength(), XFILE::CImageFile::GetLength(), XFILE::CMusicDatabaseFile::GetLength(), XFILE::COverrideFile::GetLength(), KODI::RETRO::CSavestateDatabase::GetSavestate(), CZipManager::GetZipList(), MUSIC_INFO::TagLibVFSStream::length(), LoadFile(), XFILE::CFileCache::Open(), ActiveAE::CActiveAESound::Prepare(), XFILE::CFileCache::Process(), KODI::CDRIP::CCDDARipJob::RipChunk(), ActiveAE::CActiveAESound::Seek(), KODI::CDRIP::CCDDARipJob::SetupEncoder(), TEST_F(), vfs_file_seek(), and vfs_file_seek().
GetPosition()
int64_t CFile::GetPosition () const
References CLog::Log(), LOGERROR, m_pBuffer, m_pFile, and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by dll_feof(), dll_fgetpos64(), dll_fgets(), dll_ftell64(), dll_tell(), dll_telli64(), CBlurayCallback::file_eof(), XFILE::CImageFile::GetPosition(), XFILE::CMusicDatabaseFile::GetPosition(), XFILE::COverrideFile::GetPosition(), XFILE::CZipFile::GetPosition(), CZipManager::GetZipList(), KODI::CDRIP::CCDDARipJob::RipChunk(), and MUSIC_INFO::TagLibVFSStream::tell().
GetProperty()
const std::string CFile::GetProperty (XFILE::FileProperty type, const std::string & name = "") const
References m_pFile, and name.
GetPropertyValues()
const std::vector< std::string > CFile::GetPropertyValues (XFILE::FileProperty type, const std::string & name = "") const
References m_pFile, and name.
IoControl()
int CFile::IoControl (EIoControl request, void * param)
References XFILE::IOCTRL_SEEK_POSSIBLE, and m_pFile.
Referenced by CVideoTagLoaderFFmpeg::CVideoTagLoaderFFmpeg(), CDVDInputStreamFile::GetCacheStatus(), XFILE::CFileCache::Open(), ActiveAE::CActiveAESound::Prepare(), XFILE::CFileCache::Process(), CDVDInputStreamFile::Seek(), and CDVDInputStreamFile::SetReadRate().
LoadFile() [1/2]
ssize_t CFile::LoadFile (const CURL & file, std::vector< uint8_t > & outputBuffer)
References DetermineChunkSize(), GetChunkSize(), GetLength(), int64_t(), Open(), Read(), and XFILE::READ_TRUNCATED.
Referenced by CDVDSubtitlesLibass::Configure(), CImageMetadataParser::ExtractMetadata(), KODI::GAME::CGameSettings::IsAccountVerified(), KODI::RETRO::CCheevos::LoadData(), LoadFile(), and KODI::GAME::CGameSettings::LoginToRA().
LoadFile() [2/2]
ssize_t CFile::LoadFile (const std::string & filename, std::vector< uint8_t > & outputBuffer)
References LoadFile().
Open() [1/2]
bool CFile::Open (const CURL & file, const unsigned int flags = 0)
Attempt to open an IFile instance.
Parameters
file reference to CCurl file description
flags see IFileTypes.h
Returns
true on success, false otherwise
Remarks: Open can only be called once. Calling Open() on an already opened file will fail except if flag READ_REOPEN is set and the underlying file has an implementation of ReOpen().
References CPasswordManager::AuthenticateURL(), XFILE::CACHE_BUFFER_MODE_ALL, XFILE::CACHE_BUFFER_MODE_INTERNET, XFILE::CACHE_BUFFER_MODE_NETWORK, XFILE::CACHE_BUFFER_MODE_TRUE_INTERNET, XFILE::CFileFactory::CreateLoader(), XFILE::CDirectoryCache::FileExists(), g_directoryCache, CURL::Get(), CPasswordManager::GetInstance(), CServiceBroker::GetSettingsComponent(), CURL::GetUserName(), URIUtils::IsBluray(), URIUtils::IsDVD(), URIUtils::IsHD(), URIUtils::IsInternetStream(), URIUtils::IsNetworkFilesystem(), CURL::IsProtocol(), CLog::Log(), LOGDEBUG, LOGERROR, m_bitStreamStats, m_flags, m_pBuffer, m_pFile, XFILE::CRedirectException::m_pNewFileImp, XFILE::CRedirectException::m_pNewUrl, XFILE::READ_AUDIO_VIDEO, XFILE::READ_BITRATE, XFILE::READ_CACHED, XFILE::READ_NO_CACHE, XFILE::READ_REOPEN, CURL::SetOptions(), CSettings::SETTING_FILECACHE_BUFFERMODE, ShouldUseStreamBuffer(), URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by CXBMCTestUtils::CreateCorruptedFile(), CURLOpen(), CVideoTagLoaderFFmpeg::CVideoTagLoaderFFmpeg(), dll_open(), KODI::CDRIP::CCDDARipJob::DoWork(), CBlurayCallback::file_open(), FileReader::FileReader(), KODI::RETRO::CSavestateDatabase::GetSavestate(), CZipManager::GetZipList(), LoadFile(), CDVDInputStreamFile::Open(), XFILE::CFileCache::Open(), XFILE::CImageFile::Open(), XFILE::CMultiPathFile::Open(), XFILE::CMusicDatabaseFile::Open(), XFILE::COverrideFile::Open(), XFILE::CZipFile::Open(), Open(), ActiveAE::CActiveAESound::Prepare(), CEdl::ReadComskip(), CEdl::ReadEdl(), CEdl::ReadVideoReDo(), CDACP::SendCmd(), CHTTPFileHandler::SetFile(), MUSIC_INFO::TagLibVFSStream::TagLibVFSStream(), and TEST_F().
Open() [2/2]
bool CFile::Open (const std::string & strFileName, const unsigned int flags = 0)
References Open().
OpenForWrite() [1/2]
bool CFile::OpenForWrite (const CURL & file, bool bOverWrite = false)
References XFILE::CDirectoryCache::AddFile(), CPasswordManager::AuthenticateURL(), XFILE::CFileFactory::CreateLoader(), g_directoryCache, CURL::Get(), CPasswordManager::GetInstance(), CURL::GetUserName(), CLog::Log(), LOGERROR, m_pFile, URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by Copy(), CTempFile::Create(), CPicture::CreateThumbnailFromSurface(), dll_open(), XFILE::COverrideFile::OpenForWrite(), OpenForWrite(), CAirPlayServer::CTCPClient::ProcessRequest(), CAirTunesServer::SetCoverArtFromBuffer(), MUSIC_INFO::TagLibVFSStream::TagLibVFSStream(), and TEST().
OpenForWrite() [2/2]
bool CFile::OpenForWrite (const std::string & strFileName, bool bOverWrite = false)
References OpenForWrite().
Read()
ssize_t CFile::Read (void * bufPtr, size_t bufSize)
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
References CLog::Log(), LOGERROR, m_bitStreamStats, m_flags, m_pBuffer, m_pFile, XFILE::READ_TRUNCATED, SSIZE_MAX, and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by cfile_file_read(), CXBMCTestUtils::CreateCorruptedFile(), dll_fread(), dll_read(), XFILE::CZipFile::FillBuffer(), CArchive::FillBuffer(), KODI::RETRO::CSavestateDatabase::GetSavestate(), CZipManager::GetZipList(), KODI::GAME::CGameClientInGameSaves::Load(), LoadFile(), XFILE::CFileCache::Process(), CDDB::Xcddb::queryCache(), CDVDInputStreamFile::Read(), ActiveAE::CActiveAESound::Read(), XFILE::CImageFile::Read(), XFILE::CMusicDatabaseFile::Read(), XFILE::COverrideFile::Read(), XFILE::CZipFile::Read(), KODI::CDRIP::CCDDARipJob::RipChunk(), CGUIDialogTextViewer::ShowForFile(), TEST_F(), vfs_file_read(), and vfs_file_read().
ReadString() [1/2]
bool CFile::ReadString (char * szLine, int iLineLength)
References CLog::Log(), LOGERROR, m_pBuffer, m_pFile, and XBMCCOMMONS_HANDLE_UNCHECKED.
ReadString() [2/2]
bool XFILE::CFile::ReadString (std::vector< char > & line)
String reading by line.
Parameters
line[OUT] The line read
Returns
True if has success, otherwise false for EOF or error
References CLog::Log(), LOGERROR, and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by dll_fgets(), KODI::RETRO::CCheevos::LoadData(), CEdl::ReadComskip(), CEdl::ReadEdl(), FileReader::ReadLine(), and CEdl::ReadVideoReDo().
Rename() [1/2]
bool CFile::Rename (const CURL & file, const CURL & urlNew) static
References XFILE::CDirectoryCache::AddFile(), CPasswordManager::AuthenticateURL(), XFILE::CDirectoryCache::ClearFile(), XFILE::CFileFactory::CreateLoader(), g_directoryCache, CURL::Get(), CPasswordManager::GetInstance(), CURL::GetUserName(), CLog::Log(), LOGERROR, URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by CFileOperationJob::CFileOperation::ExecuteOperation(), CLog::Initialize(), CFilesystemInstaller::InstallToFilesystem(), XFILE::COverrideFile::Rename(), XBMCAddon::xbmcvfs::rename(), ADDON::Interface_Filesystem::rename_file(), CFileUtils::RenameFile(), TEST(), and CFilesystemInstaller::UnInstallFromFilesystem().
Rename() [2/2]
bool CFile::Rename (const std::string & strFileName, const std::string & strNewFileName) static
References Rename.
Seek()
int64_t CFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET)
References CLog::Log(), LOGERROR, m_pBuffer, m_pFile, and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by cfile_file_seek(), dll_lseeki64(), CZipManager::GetZipList(), XFILE::CZipFile::Open(), XFILE::CFileCache::Process(), XFILE::CImageFile::Seek(), XFILE::CMusicDatabaseFile::Seek(), XFILE::COverrideFile::Seek(), XFILE::CZipFile::Seek(), CDVDInputStreamFile::Seek(), MUSIC_INFO::TagLibVFSStream::seek(), ActiveAE::CActiveAESound::Seek(), vfs_file_seek(), and vfs_file_seek().
SetHidden() [1/2]
bool CFile::SetHidden (const CURL & file, bool hidden) static
References CPasswordManager::AuthenticateURL(), XFILE::CFileFactory::CreateLoader(), CPasswordManager::GetInstance(), CURL::GetUserName(), CLog::Log(), LOGERROR, and URIUtils::SubstitutePath().
Referenced by CVideoDatabase::ExportActorThumbs(), SetHidden(), and TEST().
SetHidden() [2/2]
bool CFile::SetHidden (const std::string & fileName, bool hidden) static
References SetHidden().
ShouldUseStreamBuffer()
bool CFile::ShouldUseStreamBuffer (const CURL & url) private
Determines if CFileStreamBuffer should be used to read a file.
In general, should be used for ALL media files (only when is not used FileCache) and NOT used for non-media files e.g. small local files as config/settings xml files. Enables basic buffer that allows read sources with 64K chunk size even if FFmpeg only reads data with small 4K chunks or Blu-Ray sector size (6144 bytes):
[FFmpeg] <--—4K chunks--— [CFileStreamBuffer] <--—64K chunks--— [Source file / Network]
NOTE: in case of SMB / NFS default 64K chunk size is replaced with value configured in settings for the protocol. This improves performance when reads big files through Network.
Parameters
url Source file info as CULR class.
References CURL::GetShareName(), URIUtils::IsDVD(), m_flags, m_pFile, XFILE::READ_CHUNKED, and XFILE::READ_NO_BUFFER.
Referenced by Open().
Stat() [1/3]
int CFile::Stat (const CURL & file, struct __stat64 * buffer) static
Fills struct __stat64 with information about file specified by filename For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
file specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
References CPasswordManager::AuthenticateURL(), XFILE::CFileFactory::CreateLoader(), CPasswordManager::GetInstance(), CURL::GetUserName(), CLog::Log(), LOGDEBUG, LOGERROR, XFILE::CRedirectException::m_pNewFileImp, XFILE::CRedirectException::m_pNewUrl, URIUtils::SubstitutePath(), and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by CHTTPPythonHandler::CHTTPPythonHandler(), dll_fstat(), dll_fstat64(), dll_stat(), dll_stat64(), CFileOperationJob::DoProcessFile(), XFILE::CCDDADirectory::GetDirectory(), ADDON::CAddonDll::GetDllPath(), KODI::VIDEO::CVideoInfoScanner::GetFastHash(), CTextureCacheJob::GetImageHash(), CFileUtils::GetModificationDate(), KODI::VIDEO::CVideoInfoScanner::GetRecursiveFastHash(), CZipManager::GetZipList(), CURL::Parse(), CHTTPFileHandler::SetFile(), XFILE::CFileCache::Stat(), XFILE::CImageFile::Stat(), XFILE::CMultiPathFile::Stat(), XFILE::CMusicDatabaseFile::Stat(), XFILE::COverrideFile::Stat(), XFILE::CXbtFile::Stat(), Stat(), XBMCAddon::xbmcvfs::Stat::Stat(), XFILE::COverrideFile::Stat(), XFILE::CZipFile::Stat(), ADDON::Interface_Filesystem::stat_file(), TEST(), and TEST_F().
Stat() [2/3]
int CFile::Stat (const std::string & strFileName, struct __stat64 * buffer) static
Fills struct __stat64 with information about file specified by filename For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
strFileName specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
References Stat().
Stat() [3/3]
int CFile::Stat (struct __stat64 * buffer)
Fills struct __stat64 with information about currently open file For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
References m_pFile.
Truncate()
int CFile::Truncate (int64_t iSize)
References CLog::Log(), LOGERROR, m_pFile, and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by MUSIC_INFO::TagLibVFSStream::truncate().
Write()
ssize_t CFile::Write (const void * bufPtr, size_t bufSize)
Attempt to write bufSize bytes from buffer bufPtr into currently opened file.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully written bytes if any bytes were written, zero if no bytes were written and no detectable error occur, -1 in case of any explicit error
References CLog::Log(), LOGERROR, m_pFile, and XBMCCOMMONS_HANDLE_UNCHECKED.
Referenced by KODI::RETRO::CSavestateDatabase::AddSavestate(), Copy(), CXBMCTestUtils::CreateCorruptedFile(), dll_fwrite(), dll_vfprintf(), dll_write(), CArchive::FlushBuffer(), CLog::Initialize(), CAirPlayServer::CTCPClient::ProcessRequest(), KODI::GAME::CGameClientInGameSaves::Save(), CAirTunesServer::SetCoverArtFromBuffer(), XFILE::COverrideFile::Write(), and MUSIC_INFO::TagLibVFSStream::writeBlock().
Member Data Documentation
m_bitStreamStats
std::unique_ptr<BitstreamStats> XFILE::CFile::m_bitStreamStats private
Referenced by GetBitstreamStats(), Open(), and Read().
m_curl
CURL XFILE::CFile::m_curl private
Referenced by CURLAddOption(), CURLCreate(), and CURLOpen().
m_flags
unsigned int XFILE::CFile::m_flags = 0 private
Referenced by Open(), Read(), and ShouldUseStreamBuffer().
m_pBuffer
std::unique_ptr<CFileStreamBuffer> XFILE::CFile::m_pBuffer private
Referenced by Close(), GetPosition(), Open(), Read(), ReadString(), and Seek().
m_pFile
std::unique_ptr<IFile> XFILE::CFile::m_pFile private
Referenced by Close(), Flush(), GetChunkSize(), GetDownloadSpeed(), GetImplementation(), GetLength(), GetPosition(), GetProperty(), GetPropertyValues(), IoControl(), Open(), OpenForWrite(), Read(), ReadString(), Seek(), ShouldUseStreamBuffer(), Stat(), Truncate(), and Write().
The documentation for this class was generated from the following files:
filesystem/File.h
filesystem/File.cpp