Kodi Documentation: CVideoLayerBridgeDRMPRIME Class Reference
CVideoLayerBridgeDRMPRIME Class Reference
#include <VideoLayerBridgeDRMPRIME.h>
Public Member Functions
CVideoLayerBridgeDRMPRIME (std::shared_ptr< KODI::WINDOWING::GBM::CDRMAtomic > drm)
~CVideoLayerBridgeDRMPRIME () override
void Disable () override
virtual void Configure (CVideoBufferDRMPRIME *buffer)
virtual void SetVideoPlane (CVideoBufferDRMPRIME *buffer, const CRect &destRect)
virtual void UpdateVideoPlane ()
Public Member Functions inherited from KODI::WINDOWING::GBM::CVideoLayerBridge
virtual ~CVideoLayerBridge ()=default
Protected Attributes
std::shared_ptr< KODI::WINDOWING::GBM::CDRMAtomic > m_DRM
Private Member Functions
void Acquire (CVideoBufferDRMPRIME *buffer)
void Release (CVideoBufferDRMPRIME *buffer)
bool Map (CVideoBufferDRMPRIME *buffer)
void Unmap (CVideoBufferDRMPRIME *buffer)
Private Attributes
CVideoBufferDRMPRIME * m_buffer = nullptr
CVideoBufferDRMPRIME * m_prev_buffer = nullptr
Constructor & Destructor Documentation
CVideoLayerBridgeDRMPRIME()
CVideoLayerBridgeDRMPRIME::CVideoLayerBridgeDRMPRIME (std::shared_ptr< KODI::WINDOWING::GBM::CDRMAtomic > drm)
~CVideoLayerBridgeDRMPRIME()
CVideoLayerBridgeDRMPRIME::~CVideoLayerBridgeDRMPRIME () override
References m_buffer, m_prev_buffer, and Release().
Member Function Documentation
Acquire()
void CVideoLayerBridgeDRMPRIME::Acquire (CVideoBufferDRMPRIME * buffer) private
References CVideoBuffer::Acquire(), m_buffer, m_prev_buffer, and Release().
Referenced by Map().
Configure()
void CVideoLayerBridgeDRMPRIME::Configure (CVideoBufferDRMPRIME * buffer) virtual
References DRMPRIME::GetColorEncoding(), DRMPRIME::GetColorRange(), CServiceBroker::GetWinSystem(), and m_DRM.
Disable()
void CVideoLayerBridgeDRMPRIME::Disable () override virtual
Reimplemented from KODI::WINDOWING::GBM::CVideoLayerBridge.
References CServiceBroker::GetWinSystem(), and m_DRM.
Map()
bool CVideoLayerBridgeDRMPRIME::Map (CVideoBufferDRMPRIME * buffer) private
References Acquire(), CLog::Log(), LOGERROR, and m_DRM.
Referenced by SetVideoPlane().
Release()
void CVideoLayerBridgeDRMPRIME::Release (CVideoBufferDRMPRIME * buffer) private
References Unmap().
Referenced by Acquire(), and ~CVideoLayerBridgeDRMPRIME().
SetVideoPlane()
void CVideoLayerBridgeDRMPRIME::SetVideoPlane (CVideoBufferDRMPRIME * buffer, const CRect & destRect) virtual
References CRectGen< T >::Height(), m_DRM, Map(), Unmap(), CRectGen< T >::Width(), CRectGen< T >::x1, and CRectGen< T >::y1.
Unmap()
void CVideoLayerBridgeDRMPRIME::Unmap (CVideoBufferDRMPRIME * buffer) private
References m_DRM.
Referenced by Release(), and SetVideoPlane().
UpdateVideoPlane()
void CVideoLayerBridgeDRMPRIME::UpdateVideoPlane () virtual
References m_buffer, m_DRM, and CVideoBufferDRMPRIME::m_fb_id.
Member Data Documentation
m_buffer
CVideoBufferDRMPRIME* CVideoLayerBridgeDRMPRIME::m_buffer = nullptr private
Referenced by Acquire(), UpdateVideoPlane(), and ~CVideoLayerBridgeDRMPRIME().
m_DRM
std::shared_ptr<KODI::WINDOWING::GBM::CDRMAtomic> CVideoLayerBridgeDRMPRIME::m_DRM protected
Referenced by Configure(), Disable(), Map(), SetVideoPlane(), Unmap(), and UpdateVideoPlane().
m_prev_buffer
CVideoBufferDRMPRIME* CVideoLayerBridgeDRMPRIME::m_prev_buffer = nullptr private
Referenced by Acquire(), and ~CVideoLayerBridgeDRMPRIME().
The documentation for this class was generated from the following files:
VideoLayerBridgeDRMPRIME.h
VideoLayerBridgeDRMPRIME.cpp