Kodi Documentation: anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser Class Reference
anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser Class Reference
Public Member Functions
CArtTypeChooser ()=delete
CArtTypeChooser (const std::shared_ptr< CFileItem > &item)
bool ChooseArtType ()
const std::string & GetArtType () const
void UpdateArtType (const std::string &type, const std::string &art) const
Private Attributes
std::shared_ptr< CFileItem > m_item
CFileItemList m_items
int m_selectedItem {0}
std::string m_artType
Constructor & Destructor Documentation
CArtTypeChooser() [1/2]
anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::CArtTypeChooser () delete
CArtTypeChooser() [2/2]
anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::CArtTypeChooser (const std::shared_ptr< CFileItem > & item) inline explicit
Member Function Documentation
ChooseArtType()
bool anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::ChooseArtType ()
References CGUIDialogSelect::EnableButton(), g_localizeStrings, CLocalizeStrings::Get(), anonymous_namespace{GUIDialogVideoInfo.cpp}::GetArtTypesList(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedFileItem(), CGUIDialogSelect::GetSelectedItem(), CGUIComponent::GetWindowManager(), CGUIDialogSelect::IsButtonPressed(), CGUIDialog::Open(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CGUIDialogSelect::SetSelected(), CGUIDialogSelect::SetUseDetails(), CGUIKeyboardFactory::ShowAndGetInput(), and WINDOW_DIALOG_SELECT.
GetArtType()
const std::string & anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::GetArtType () const inline
UpdateArtType()
void anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::UpdateArtType (const std::string & type, const std::string & art) const
Member Data Documentation
m_artType
std::string anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::m_artType private
m_item
std::shared_ptr<CFileItem> anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::m_item private
m_items
CFileItemList anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::m_items private
m_selectedItem
int anonymous_namespace{GUIDialogVideoInfo.cpp}::CArtTypeChooser::m_selectedItem {0} private
The documentation for this class was generated from the following file:
GUIDialogVideoInfo.cpp