Kodi Documentation: KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS Class Reference
KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS Class Reference
#include <OSScreenSaverWebOS.h>
Public Member Functions
~COSScreenSaverWebOS () override
void Inhibit () override
void Uninhibit () override
Public Member Functions inherited from KODI::WINDOWING::IOSScreenSaver
virtual ~IOSScreenSaver ()=default
Static Private Member Functions
static bool OnScreenSaverAboutToStart (LSHandle *sh, LSMessage *reply, void *ctx)
Private Attributes
std::unique_ptr< HContext > m_requestContext
Constructor & Destructor Documentation
~COSScreenSaverWebOS()
KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS::~COSScreenSaverWebOS () override
References LOGWARNING, and m_requestContext.
Member Function Documentation
Inhibit()
void KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS::Inhibit () override virtual
Screensaver inhibition on webOS works by subscribing to the tvpower service. The service will respond every few minutes with a timestamp that needs to be confirmed if the screensaver should still be inhibited. If those responses are not answered the screensaver will be uninhibited again
Implements KODI::WINDOWING::IOSScreenSaver.
References CCompileInfo::GetPackage(), LOGWARNING, m_requestContext, OnScreenSaverAboutToStart(), and CJSONVariantWriter::Write().
OnScreenSaverAboutToStart()
bool KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS::OnScreenSaverAboutToStart (LSHandle * sh, LSMessage * reply, void * ctx) static private
References CCompileInfo::GetPackage(), LOGDEBUG, LOGWARNING, CJSONVariantParser::Parse(), and CJSONVariantWriter::Write().
Referenced by Inhibit().
Uninhibit()
void KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS::Uninhibit () override virtual
Allow the OS screen saver to become active again
Calling this function multiple times or at all without calling Inhibit MUST NOT produce any side-effects.
Implements KODI::WINDOWING::IOSScreenSaver.
References LOGWARNING, and m_requestContext.
Member Data Documentation
m_requestContext
std::unique_ptr<HContext> KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS::m_requestContext private
Referenced by Inhibit(), Uninhibit(), and ~COSScreenSaverWebOS().
The documentation for this class was generated from the following files:
OSScreenSaverWebOS.h
OSScreenSaverWebOS.cpp