Kodi Documentation: KODI::MESSAGING::HELPERS Namespace Reference
KODI::MESSAGING::HELPERS Namespace Reference
Classes
struct DialogOKMessage
struct DialogYesNoMessage
Payload sent for message TMSG_GUI_DIALOG_YESNO.
Enumerations
enum class DialogResponse : int { CHOICE_CANCELLED , CHOICE_YES , CHOICE_NO , CHOICE_CUSTOM }
Functions
DialogResponse ShowYesNoDialogText (CVariant heading, CVariant text, CVariant noLabel=CVariant(), CVariant yesLabel=CVariant(), uint32_t autoCloseTimeout=0)
This is a helper method to send a threadmessage to open a Yes/No dialog box.
DialogResponse ShowYesNoCustomDialog (CVariant heading, CVariant text, CVariant noLabel=CVariant(), CVariant yesLabel=CVariant(), CVariant customLabel=CVariant(), uint32_t autoCloseTimeout=0)
This is a helper method to send a threadmessage to open a Yes/No dialog box with a custom button.
DialogResponse ShowYesNoDialogLines (CVariant heading, CVariant line0, CVariant line1=CVariant(), CVariant line2=CVariant(), CVariant noLabel=CVariant(), CVariant yesLabel=CVariant(), uint32_t autoCloseTimeout=0)
This is a helper method to send a threadmessage to open a Yes/No dialog box.
bool ShowOKDialogText (CVariant heading, CVariant text)
This is a helper method to send a threadmessage to open a Ok dialog box.
void UpdateOKDialogText (CVariant heading, CVariant text)
This is a helper method to send a threadmessage to update a Ok dialog text.
bool ShowOKDialogLines (CVariant heading, CVariant line0, CVariant line1=CVariant(), CVariant line2=CVariant())
This is a helper method to send a threadmessage to open a OK dialog box.
Enumeration Type Documentation
DialogResponse
enum class KODI::MESSAGING::HELPERS::DialogResponse : int strong
Enumerator
CHOICE_CANCELLED
CHOICE_YES
CHOICE_NO
CHOICE_CUSTOM
Function Documentation
ShowOKDialogLines()
bool KODI::MESSAGING::HELPERS::ShowOKDialogLines (CVariant heading, CVariant line0, CVariant line1 = CVariant(), CVariant line2 = CVariant())
This is a helper method to send a threadmessage to open a OK dialog box.
Parameters
[in] heading The text to display as the dialog box header
[in] line0 The text to display on the first line
[in] line1 The text to display on the second line
[in] line2 The text to display on the third line
Returns
if it's confirmed
See also
ShowOKDialogText
CGUIDialogOK::ShowAndGetInput
DialogOKMessage
References CServiceBroker::GetAppMessenger(), and TMSG_GUI_DIALOG_OK.
Referenced by CGUIPassword::CheckStartUpLock(), ADDON::CAddonDll::Create(), CMusicDatabase::ExportToXML(), KODI::GAME::CGameClientProperties::GetProxyAddons(), CMusicDatabase::ImportFromXML(), ADDON::CAddonDll::LoadDll(), CMusicDatabase::LookupCDDBInfo(), CPartyModeManager::OnError(), CGUIWindowFileManager::OnJobComplete(), ADDON::CAddonStatusHandler::Process(), XFILE::IDirectory::ProcessRequirements(), CGUIDialogAddonInfo::PromptIfDependency(), ADDON::Interface_GUIDialogOK::show_and_get_input_line_text(), and CGUIPassword::UpdateMasterLockRetryCount().
ShowOKDialogText()
bool KODI::MESSAGING::HELPERS::ShowOKDialogText (CVariant heading, CVariant text)
This is a helper method to send a threadmessage to open a Ok dialog box.
Parameters
[in] heading The text to display as the dialog box header
[in] text The text to display in the dialog body
Returns
if it's confirmed
See also
UpdateOKDialogLines
CGUIDialogOK::ShowAndGetInput
DialogOKMessage
References CServiceBroker::GetAppMessenger(), text, and TMSG_GUI_DIALOG_OK.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonUngroupedChannels(), PVR::CPVRGUIActionsTimers::AddReminder(), PVR::CPVRGUIActionsTimers::AddTimer(), PVR::CPVRGUIActionsTimers::AddTimer(), PVR::CGUIWindowPVRBase::CanBeActivated(), PVR::CPVRGUIActionsParentalControl::CheckParentalPIN(), CMusicDatabase::Clean(), CleanLibrary(), KODI::CDRIP::CCDDARipper::CreateAlbumDir(), CMusicDatabase::DeleteCDDBInfo(), PVR::CPVRGUIActionsRecordings::DeleteRecording(), PVR::CPVRGUIActionsTimers::DeleteTimer(), PVR::CPVRGUIActionsTimers::DeleteTimer(), CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), PVR::CPVRGUIActionsRecordings::DeleteWatchedRecordings(), KODI::VIDEO::CVideoInfoScanner::DownloadFailed(), CVideoDatabase::ExportToXML(), KODI::GAME::CGameUtils::FillInGameClient(), KODI::GAME::CGUIControllerWindow::GetMoreControllers(), CGUIWindowMusicNav::GetSongsFromPlayList(), CGUIMediaWindow::HaveDiscOrConnection(), CGUIDialogFileBrowser::HaveDiscOrConnection(), CGUIWindowFileManager::HaveDiscOrConnection(), KODI::GAME::CGameUtils::Install(), KODI::GAME::CGameClientProperties::InstallDependencies(), CGUIPassword::IsItemUnlocked(), ADDON::CAddonRepos::LoadAddonsFromDatabase(), CGUIWindowMusicBase::LoadPlayList(), CGUIWindowPictures::LoadPlayList(), CGUIWindowVideoBase::LoadPlayList(), KODI::GAME::CGameClient::NotifyError(), XBMCAddon::xbmcgui::Dialog::ok(), CGUIWindowVideoNav::OnClick(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), PVR::CGUIDialogPVRChannelManager::OnContextButton(), CGUIWindowMusicBase::OnContextButton(), KODI::GAME::CGUIAgentControllerList::OnControllerSelect(), KODI::GAME::CGUIPortList::OnControllerSelected(), CGUIWindowVideoBase::OnItemInfo(), CApplication::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowLoginScreen::OnMessage(), CGUIDialogLibExportSettings::OnOK(), PVR::CGUIWindowPVRSearchBase::OnPrepareFileItems(), CGUIWindowMusicBase::OnRipCD(), CGUIWindowMusicBase::OnRipTrack(), CGUIWindowVideoBase::OnSearch(), CGUIDialogVideoInfo::OnSearch(), CGUIDialogAddonInfo::OnSelectVersion(), CMediaSettings::OnSettingAction(), CDiscSettings::OnSettingChanged(), CNetworkServices::OnSettingChanging(), CGUIWindowFileManager::OnStart(), KODI::GAME::CGameClient::OpenFile(), KODI::PLAYLIST::CPlayListPlayer::Play(), CGUIWindowVideoBase::PlayItem(), CMediaManager::playStubFile(), KODI::GAME::CControllerInstaller::Process(), PVR::CPVRGUIActionsRecordings::ProcessDeleteAfterWatch(), PVR::CPVRGUIActionsClients::ProcessSettingsMenuHooks(), CGUIDialogMusicInfo::RefreshInfo(), PVR::CGUIDialogPVRChannelManager::RenameChannel(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::ReportInstallError(), anonymous_namespace{PVRGUIActionsTimers.cpp}::AsyncUpdateTimer::Run(), PVR::CPVRGUIActionsTimers::SetRecordingOnChannel(), KODI::GAME::CGUIDialogButtonCapture::Show(), PERIPHERALS::CGUIDialogPeripherals::Show(), ADDON::Interface_GUIDialogOK::show_and_get_input_single_text(), CGUIDialogNetworkSetup::ShowAndGetNetworkAddress(), CGUIKeyboardFactory::ShowAndVerifyNewPassword(), CGUIDialogGamepad::ShowAndVerifyNewPassword(), CGUIDialogNumeric::ShowAndVerifyNewPassword(), CVideoInfoDownloader::ShowErrorDialog(), CGUIDialogAddonSettings::ShowForSingleInstance(), KODI::GAME::CGUIControllerWindow::ShowHelp(), CGUIWindowVideoBase::ShowInfo(), CGUIWindowFileManager::ShowShareErrorMessage(), CGUIMediaWindow::ShowShareErrorMessage(), CNetworkServices::Start(), PVR::CPVRGUIActionsChannels::StartChannelScan(), PVR::CPVRGUIActionsTimers::ToggleTimerState(), PVR::CPVRGUIActionsRecordings::UndeleteRecording(), CGUIPassword::UpdateMasterLockRetryCount(), CGUIDialogVideoInfo::UpdateVideoItemSortTitle(), CGUIDialogVideoInfo::UpdateVideoItemTitle(), PVR::CGUIDialogPVRTimerSettings::Validate(), and CVideoLibraryRefreshingJob::Work().
ShowYesNoCustomDialog()
DialogResponse KODI::MESSAGING::HELPERS::ShowYesNoCustomDialog (CVariant heading, CVariant text, CVariant noLabel = CVariant(), CVariant yesLabel = CVariant(), CVariant customLabel = CVariant(), uint32_t autoCloseTimeout = 0)
This is a helper method to send a threadmessage to open a Yes/No dialog box with a custom button.
Parameters
[in] heading The text to display as the dialog box header
[in] text The text to display in the dialog body
[in] noLabel The text to display on the No button defaults to No
[in] yesLabel The text to display on the Yes button defaults to Yes
[in] customLabel The text to display on the optional 3rd custom button defaults to empty and button not shown
[in] autoCloseTimeout The time before the dialog closes defaults to 0 show indefinitely
Returns
-1 on cancelled, 0 on no, 1 on yes and 2 on 3rd custom response
See also
ShowYesNoDialogLines
CGUIDialogYesNo::ShowAndGetInput
DialogYesNoMessage
References CHOICE_CANCELLED, CHOICE_CUSTOM, CHOICE_NO, CHOICE_YES, CServiceBroker::GetAppMessenger(), text, and TMSG_GUI_DIALOG_YESNO.
Referenced by CGUIWindowMusicBase::OnAssignContent(), and ShowYesNoDialogText().
ShowYesNoDialogLines()
DialogResponse KODI::MESSAGING::HELPERS::ShowYesNoDialogLines (CVariant heading, CVariant line0, CVariant line1 = CVariant(), CVariant line2 = CVariant(), CVariant noLabel = CVariant(), CVariant yesLabel = CVariant(), uint32_t autoCloseTimeout = 0)
This is a helper method to send a threadmessage to open a Yes/No dialog box.
Parameters
[in] heading The text to display as the dialog box header
[in] line0 The text to display on the first line
[in] line1 The text to display on the second line
[in] line2 The text to display on the third line
[in] noLabel The text to display on the No button defaults to No
[in] yesLabel The text to display on the Yes button defaults to Yes
[in] autoCloseTimeout The time before the dialog closes defaults to 0 show indefinitely
Returns
-1 on cancelled, 0 on no and 1 on yes
See also
ShowYesNoDialogText
CGUIDialogYesNo::ShowAndGetInput
DialogYesNoMessage
References CHOICE_CANCELLED, CHOICE_CUSTOM, CHOICE_NO, CHOICE_YES, CServiceBroker::GetAppMessenger(), and TMSG_GUI_DIALOG_YESNO.
Referenced by CApplication::ConfigureAndEnableAddons(), EnableAddon(), ADDON::CAddonInstaller::InstallModal(), PVR::CPVRGUIActionsRecordings::ProcessDeleteAfterWatch(), ADDON::Interface_GUIDialogYesNo::show_and_get_input_line_button_text(), and ADDON::Interface_GUIDialogYesNo::show_and_get_input_line_text().
ShowYesNoDialogText()
DialogResponse KODI::MESSAGING::HELPERS::ShowYesNoDialogText (CVariant heading, CVariant text, CVariant noLabel = CVariant(), CVariant yesLabel = CVariant(), uint32_t autoCloseTimeout = 0)
This is a helper method to send a threadmessage to open a Yes/No dialog box.
Parameters
[in] heading The text to display as the dialog box header
[in] text The text to display in the dialog body
[in] noLabel The text to display on the No button defaults to No
[in] yesLabel The text to display on the Yes button defaults to Yes
[in] autoCloseTimeout The time before the dialog closes defaults to 0 show indefinitely
Returns
-1 on cancelled, 0 on no and 1 on yes
See also
ShowYesNoDialogLines
CGUIDialogYesNo::ShowAndGetInput
DialogYesNoMessage
References ShowYesNoCustomDialog(), and text.
Referenced by PVR::CPVRGUIActionsPowerManagement::CanSystemPowerdown(), CMusicDatabase::Clean(), PVR::CPVRGUIActionsTimers::DeleteTimer(), KODI::VIDEO::CVideoInfoScanner::DownloadFailed(), ExportLibrary(), UPNP::CUPnPPlayer::OnAction(), PVR::CGUIWindowPVRGuideBase::OnMessage(), CGUIDialogLibExportSettings::OnOK(), ADDON::CLanguageResource::OnPostInstall(), ADDON::CSkinInfo::OnPostInstall(), CMediaSettings::OnSettingAction(), CNetworkServices::OnSettingChanged(), CNetworkServices::OnSettingChanging(), PVR::CGUIDialogPVRRecordingSettings::OnSettingChanging(), CDisplaySettings::OnSettingChanging(), CApplicationSkinHandling::ReloadSkin(), ADDON::Interface_GUIDialogYesNo::show_and_get_input_single_text(), and CNetworkServices::StopEventServer().
UpdateOKDialogText()
void KODI::MESSAGING::HELPERS::UpdateOKDialogText (CVariant heading, CVariant text)
This is a helper method to send a threadmessage to update a Ok dialog text.
Parameters
[in] heading The text to display as the dialog box header
[in] text The text to display in the dialog body
See also
ShowOKDialogLines
CGUIDialogOK::ShowAndGetInput
DialogOKMessage
References CServiceBroker::GetAppMessenger(), text, and TMSG_GUI_DIALOG_OK.
Referenced by KODI::GAME::CGUIDialogButtonCapture::Process().