Kodi Documentation: HTTPRequestHandlerUtils Class Reference
HTTPRequestHandlerUtils Class Reference
#include <HTTPRequestHandlerUtils.h>
Static Public Member Functions
static std::string GetRequestHeaderValue (struct MHD_Connection *connection, enum MHD_ValueKind kind, const std::string &key)
static int GetRequestHeaderValues (struct MHD_Connection *connection, enum MHD_ValueKind kind, std::map< std::string, std::string > &headerValues)
static int GetRequestHeaderValues (struct MHD_Connection *connection, enum MHD_ValueKind kind, std::multimap< std::string, std::string > &headerValues)
static bool GetRequestedRanges (struct MHD_Connection *connection, uint64_t totalLength, CHttpRanges &ranges)
Private Member Functions
HTTPRequestHandlerUtils ()=delete
Static Private Member Functions
static MHD_RESULT FillArgumentMap (void *cls, enum MHD_ValueKind kind, const char *key, const char *value)
static MHD_RESULT FillArgumentMultiMap (void *cls, enum MHD_ValueKind kind, const char *key, const char *value)
Constructor & Destructor Documentation
HTTPRequestHandlerUtils()
HTTPRequestHandlerUtils::HTTPRequestHandlerUtils () private delete
Member Function Documentation
FillArgumentMap()
MHD_RESULT HTTPRequestHandlerUtils::FillArgumentMap (void * cls, enum MHD_ValueKind kind, const char * key, const char * value) static private
References value.
Referenced by GetRequestHeaderValues().
FillArgumentMultiMap()
MHD_RESULT HTTPRequestHandlerUtils::FillArgumentMultiMap (void * cls, enum MHD_ValueKind kind, const char * key, const char * value) static private
References value.
Referenced by GetRequestHeaderValues().
GetRequestedRanges()
bool HTTPRequestHandlerUtils::GetRequestedRanges (struct MHD_Connection * connection, uint64_t totalLength, CHttpRanges & ranges) static
References CHttpRanges::Clear(), GetRequestHeaderValue(), and CHttpRanges::Parse().
Referenced by CWebServer::CreateFileDownloadResponse(), and IHTTPRequestHandler::GetRequestedRanges().
GetRequestHeaderValue()
std::string HTTPRequestHandlerUtils::GetRequestHeaderValue (struct MHD_Connection * connection, enum MHD_ValueKind kind, const std::string & key) static
References value.
Referenced by IHTTPRequestHandler::GetHostnameAndPort(), GetRequestedRanges(), CWebServer::HandlePartialRequest(), CHTTPJsonRpcHandler::HandleRequest(), CWebServer::IsRequestCacheable(), CWebServer::IsRequestRanged(), and CWebServer::SetupPostDataProcessing().
GetRequestHeaderValues() [1/2]
int HTTPRequestHandlerUtils::GetRequestHeaderValues (struct MHD_Connection * connection, enum MHD_ValueKind kind, std::map< std::string, std::string > & headerValues) static
References FillArgumentMap().
Referenced by CHTTPImageTransformationHandler::CanHandleRequest(), CHTTPImageTransformationHandler::HandleRequest(), CHTTPJsonRpcHandler::HandleRequest(), CHTTPPythonHandler::HandleRequest(), CWebServer::LogRequest(), and CWebServer::LogResponse().
GetRequestHeaderValues() [2/2]
int HTTPRequestHandlerUtils::GetRequestHeaderValues (struct MHD_Connection * connection, enum MHD_ValueKind kind, std::multimap< std::string, std::string > & headerValues) static
References FillArgumentMultiMap().
The documentation for this class was generated from the following files:
HTTPRequestHandlerUtils.h
HTTPRequestHandlerUtils.cpp