Kodi Documentation: CViewStateSettings Class Reference
CViewStateSettings Class Reference
#include <ViewStateSettings.h>
Public Member Functions
bool Load (const TiXmlNode *settings) override
Load settings from the given XML node.
bool Save (TiXmlNode *settings) const override
Save settings to the given XML node.
void Clear () override
Clear any loaded setting values.
const CViewState * Get (const std::string &viewState) const
CViewState * Get (const std::string &viewState)
SettingLevel GetSettingLevel () const
void SetSettingLevel (SettingLevel settingLevel)
void CycleSettingLevel ()
SettingLevel GetNextSettingLevel () const
EventLevel GetEventLevel () const
void SetEventLevel (EventLevel eventLevel)
void CycleEventLevel ()
EventLevel GetNextEventLevel () const
bool ShowHigherEventLevels () const
void SetShowHigherEventLevels (bool showHigherEventLevels)
void ToggleShowHigherEventLevels ()
Public Member Functions inherited from ISubSettings
virtual ~ISubSettings ()=default
Static Public Member Functions
static CViewStateSettings & GetInstance ()
Protected Member Functions
CViewStateSettings ()
CViewStateSettings (const CViewStateSettings &)=delete
CViewStateSettings & operator= (CViewStateSettings const &)=delete
~CViewStateSettings () override
Private Member Functions
void AddViewState (const std::string &strTagName, int defaultView=DEFAULT_VIEW_LIST, SortBy defaultSort=SortByLabel)
Private Attributes
std::map< std::string, CViewState * > m_viewStates
SettingLevel m_settingLevel = SettingLevel::Standard
EventLevel m_eventLevel = EventLevel::Basic
bool m_eventShowHigherLevels = true
CCriticalSection m_critical
Constructor & Destructor Documentation
CViewStateSettings() [1/2]
CViewStateSettings::CViewStateSettings () protected
References AddViewState(), Clear(), DEFAULT_VIEW_AUTO, DEFAULT_VIEW_LIST, SortByEpisodeNumber, and SortByTrackNumber.
CViewStateSettings() [2/2]
CViewStateSettings::CViewStateSettings (const CViewStateSettings &) protected delete
~CViewStateSettings()
CViewStateSettings::~CViewStateSettings () override protected
References m_viewStates.
Member Function Documentation
AddViewState()
void CViewStateSettings::AddViewState (const std::string & strTagName, int defaultView = DEFAULT_VIEW_LIST, SortBy defaultSort = SortByLabel) private
References m_viewStates, and SortOrderAscending.
Referenced by CViewStateSettings().
Clear()
void CViewStateSettings::Clear () override virtual
Clear any loaded setting values.
Reimplemented from ISubSettings.
References m_settingLevel, and Standard.
Referenced by CViewStateSettings().
CycleEventLevel()
void CViewStateSettings::CycleEventLevel ()
References GetNextEventLevel(), and m_eventLevel.
Referenced by CGUIWindowEventLog::OnMessage().
CycleSettingLevel()
void CViewStateSettings::CycleSettingLevel ()
References GetNextSettingLevel(), and m_settingLevel.
Referenced by CGUIDialogAddonSettings::OnAction(), and CGUIWindowSettingsCategory::OnAction().
Get() [1/2]
CViewState * CViewStateSettings::Get (const std::string & viewState)
References m_critical, and m_viewStates.
Get() [2/2]
const CViewState * CViewStateSettings::Get (const std::string & viewState) const
References m_critical, and m_viewStates.
Referenced by CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), CGUIViewStateMusicPlaylist::CGUIViewStateMusicPlaylist(), CGUIViewStateMusicSearch::CGUIViewStateMusicSearch(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoPlaylist::CGUIViewStateVideoPlaylist(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), KODI::GAME::CGUIViewStateWindowGames::CGUIViewStateWindowGames(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowPictures::CGUIViewStateWindowPictures(), CGUIViewStateWindowPrograms::CGUIViewStateWindowPrograms(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), KODI::GAME::CGUIViewStateWindowGames::SaveViewState(), CGUIViewStateMusicSearch::SaveViewState(), CGUIViewStateMusicDatabase::SaveViewState(), CGUIViewStateMusicSmartPlaylist::SaveViewState(), CGUIViewStateWindowPictures::SaveViewState(), CGUIViewStateWindowPrograms::SaveViewState(), PVR::CGUIViewStateWindowPVRRecordings::SaveViewState(), PVR::CGUIViewStateWindowPVRSearch::SaveViewState(), PVR::CGUIViewStateWindowPVRProviders::SaveViewState(), CGUIViewStateWindowVideoNav::SaveViewState(), CGUIViewStateVideoMovies::SaveViewState(), CGUIViewStateVideoMusicVideos::SaveViewState(), CGUIViewStateVideoTVShows::SaveViewState(), and CGUIViewStateVideoEpisodes::SaveViewState().
GetEventLevel()
EventLevel CViewStateSettings::GetEventLevel () const inline
References m_eventLevel.
Referenced by CGUIWindowEventLog::GetDirectory(), and CGUIWindowEventLog::UpdateButtons().
GetInstance()
CViewStateSettings & CViewStateSettings::GetInstance () static
Referenced by CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), CGUIViewStateMusicPlaylist::CGUIViewStateMusicPlaylist(), CGUIViewStateMusicSearch::CGUIViewStateMusicSearch(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoPlaylist::CGUIViewStateVideoPlaylist(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), KODI::GAME::CGUIViewStateWindowGames::CGUIViewStateWindowGames(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowPictures::CGUIViewStateWindowPictures(), CGUIViewStateWindowPrograms::CGUIViewStateWindowPrograms(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), CGUIPassword::CheckMenuLock(), CGUIPassword::CheckSettingLevelLock(), CGUIWindowEventLog::GetDirectory(), CGUIDialogAddonSettings::GetSettingLevel(), CGUIWindowSettingsCategory::GetSettingLevel(), CSettings::InitializeISubSettings(), CGUIDialogAddonSettings::OnAction(), CGUIWindowSettingsCategory::OnAction(), CGUIWindowEventLog::OnMessage(), CGUIWindowSettingsCategory::OnWindowLoaded(), KODI::GAME::CGUIViewStateWindowGames::SaveViewState(), CGUIViewStateMusicSearch::SaveViewState(), CGUIViewStateMusicDatabase::SaveViewState(), CGUIViewStateMusicSmartPlaylist::SaveViewState(), CGUIViewStateWindowPictures::SaveViewState(), CGUIViewStateWindowPrograms::SaveViewState(), PVR::CGUIViewStateWindowPVRChannels::SaveViewState(), PVR::CGUIViewStateWindowPVRRecordings::SaveViewState(), PVR::CGUIViewStateWindowPVRGuide::SaveViewState(), PVR::CGUIViewStateWindowPVRTimers::SaveViewState(), PVR::CGUIViewStateWindowPVRSearch::SaveViewState(), PVR::CGUIViewStateWindowPVRProviders::SaveViewState(), CGUIViewStateWindowVideoNav::SaveViewState(), CGUIViewStateVideoMovies::SaveViewState(), CGUIViewStateVideoMusicVideos::SaveViewState(), CGUIViewStateVideoTVShows::SaveViewState(), CGUIViewStateVideoEpisodes::SaveViewState(), CGUIDialogAddonSettings::SetupView(), CSettings::UninitializeISubSettings(), and CGUIWindowEventLog::UpdateButtons().
GetNextEventLevel()
EventLevel CViewStateSettings::GetNextEventLevel () const
References Basic, Error, and m_eventLevel.
Referenced by CycleEventLevel().
GetNextSettingLevel()
SettingLevel CViewStateSettings::GetNextSettingLevel () const
References Basic, Expert, and m_settingLevel.
Referenced by CycleSettingLevel(), CGUIDialogAddonSettings::OnAction(), and CGUIWindowSettingsCategory::OnAction().
GetSettingLevel()
SettingLevel CViewStateSettings::GetSettingLevel () const inline
References m_settingLevel.
Referenced by CGUIDialogAddonSettings::GetSettingLevel(), and CGUIWindowSettingsCategory::GetSettingLevel().
Load()
bool CViewStateSettings::Load (const TiXmlNode * settings) override virtual
Load settings from the given XML node.
Parameters
settings XML node containing setting values
Returns
True if loading the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References Basic, DEFAULT_VIEW_LIST, DEFAULT_VIEW_MAX, Error, Expert, XMLUtils::GetBoolean(), XMLUtils::GetInt(), CLog::Log(), LOGWARNING, m_critical, m_eventLevel, m_eventShowHigherLevels, m_settingLevel, m_viewStates, SORT_METHOD_MAX, SORT_METHOD_NONE, SortAttributeIgnoreFolders, SortAttributeNone, SortByLastUsed, SortByNone, SortOrderDescending, SortOrderNone, Standard, SortUtils::TranslateOldSortMethod(), XML_EVENTLOG, XML_EVENTLOG_LEVEL, XML_EVENTLOG_LEVEL_HIGHER, XML_GENERAL, XML_SETTINGLEVEL, XML_SORTATTRIBUTES, XML_SORTMETHOD, XML_SORTORDER, XML_VIEWMODE, and XML_VIEWSTATESETTINGS.
operator=()
CViewStateSettings & CViewStateSettings::operator= (CViewStateSettings const &) protected delete
Save()
bool CViewStateSettings::Save (TiXmlNode * settings) const override virtual
Save settings to the given XML node.
Parameters
settings XML node in which the settings will be saved
Returns
True if saving the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References CLog::Log(), LOGWARNING, m_critical, m_eventLevel, m_eventShowHigherLevels, m_settingLevel, m_viewStates, XMLUtils::SetBoolean(), XMLUtils::SetInt(), XML_EVENTLOG, XML_EVENTLOG_LEVEL, XML_EVENTLOG_LEVEL_HIGHER, XML_GENERAL, XML_SETTINGLEVEL, XML_SORTATTRIBUTES, XML_SORTMETHOD, XML_SORTORDER, XML_VIEWMODE, and XML_VIEWSTATESETTINGS.
SetEventLevel()
void CViewStateSettings::SetEventLevel (EventLevel eventLevel)
References Basic, Error, and m_eventLevel.
SetSettingLevel()
void CViewStateSettings::SetSettingLevel (SettingLevel settingLevel)
References Basic, Expert, and m_settingLevel.
Referenced by CGUIPassword::CheckSettingLevelLock().
SetShowHigherEventLevels()
void CViewStateSettings::SetShowHigherEventLevels (bool showHigherEventLevels) inline
References m_eventShowHigherLevels.
ShowHigherEventLevels()
bool CViewStateSettings::ShowHigherEventLevels () const inline
References m_eventShowHigherLevels.
Referenced by CGUIWindowEventLog::GetDirectory().
ToggleShowHigherEventLevels()
void CViewStateSettings::ToggleShowHigherEventLevels () inline
References m_eventShowHigherLevels.
Referenced by CGUIWindowEventLog::OnMessage().
Member Data Documentation
m_critical
CCriticalSection CViewStateSettings::m_critical mutable private
Referenced by Get(), Get(), Load(), and Save().
m_eventLevel
EventLevel CViewStateSettings::m_eventLevel = EventLevel::Basic private
Referenced by CycleEventLevel(), GetEventLevel(), GetNextEventLevel(), Load(), Save(), and SetEventLevel().
m_eventShowHigherLevels
bool CViewStateSettings::m_eventShowHigherLevels = true private
Referenced by Load(), Save(), SetShowHigherEventLevels(), ShowHigherEventLevels(), and ToggleShowHigherEventLevels().
m_settingLevel
SettingLevel CViewStateSettings::m_settingLevel = SettingLevel::Standard private
Referenced by Clear(), CycleSettingLevel(), GetNextSettingLevel(), GetSettingLevel(), Load(), Save(), and SetSettingLevel().
m_viewStates
std::map<std::string, CViewState*> CViewStateSettings::m_viewStates private
Referenced by AddViewState(), Get(), Get(), Load(), Save(), and ~CViewStateSettings().
The documentation for this class was generated from the following files:
ViewStateSettings.h
ViewStateSettings.cpp