Kodi Documentation: UPNP Namespace Reference
UPNP Namespace Reference
Classes
class CCtrlPointReferenceHolder
class CDeviceHostReferenceHolder
class CMediaBrowser
class CMediaController
class CRendererReferenceHolder
class CResourceFinder
class CUPnP
class CUPnPCleaner
class CUPnPPlayer
class CUPnPPlayerController
class CUPnPRenderer
class CUPnPServer
struct ResourcePrioritySort
Enumerations
enum UPnPService {
UPnPServiceNone = 0 , UPnPClient , UPnPContentDirectory , UPnPPlayer ,
UPnPRenderer
}
enum EClientQuirks { ECLIENTQUIRKS_NONE = 0x0 , ECLIENTQUIRKS_ONLYSTORAGEFOLDER = 0x01 , ECLIENTQUIRKS_BASICVIDEOCLASS = 0x02 , ECLIENTQUIRKS_UNKNOWNSERIES = 0x04 }
enum EMediaControllerQuirks { EMEDIACONTROLLERQUIRKS_NONE = 0x00 , EMEDIACONTROLLERQUIRKS_X_MKV = 0x01 }
Functions
EClientQuirks GetClientQuirks (const PLT_HttpRequestContext *context)
EMediaControllerQuirks GetMediaControllerQuirks (const PLT_DeviceData *device)
NPT_String GetMimeType (const char *filename, const PLT_HttpRequestContext *context)
NPT_String GetMimeType (const CFileItem &item, const PLT_HttpRequestContext *context)
const NPT_String GetProtocolInfo (const CFileItem &item, const char *protocol, const PLT_HttpRequestContext *context)
NPT_Result PopulateObjectFromTag (CMusicInfoTag &tag, PLT_MediaObject &object, NPT_String *file_path, PLT_MediaItemResource *resource, EClientQuirks quirks, UPnPService service)
NPT_Result PopulateObjectFromTag (CVideoInfoTag &tag, PLT_MediaObject &object, NPT_String *file_path, PLT_MediaItemResource *resource, EClientQuirks quirks, UPnPService service)
PLT_MediaObject * BuildObject (CFileItem &item, NPT_String &file_path, bool with_count, NPT_Reference< CThumbLoader > &thumb_loader, const PLT_HttpRequestContext *context, CUPnPServer *upnp_server, UPnPService upnp_service)
const std::string & CorrectAllItemsSortHack (const std::string &item)
int PopulateTagFromObject (CMusicInfoTag &tag, PLT_MediaObject &object, PLT_MediaItemResource *resource, UPnPService service)
int PopulateTagFromObject (CVideoInfoTag &tag, PLT_MediaObject &object, PLT_MediaItemResource *resource, UPnPService service)
std::shared_ptr< CFileItem > BuildObject (PLT_MediaObject *entry, UPnPService upnp_service)
bool GetResource (const PLT_MediaObject *entry, CFileItem &item)
std::shared_ptr< CFileItem > GetFileItem (const NPT_String &uri, const NPT_String &meta)
NPT_String EncodeObjectId (const std::string &id)
Provided a given object id, encode it into a safe format to provide to UPnP clients @Note base64 is currently used as the safe format.
NPT_String DecodeObjectId (const std::string &id)
Provided a given encoded object id, decode it into a format known by the application @Note base64 is currently used as the expected input format.
const char * GetMimeTypeFromExtension (const char *extension, const PLT_HttpRequestContext *context=NULL)
static NPT_Result WaitOnEvent (CEvent &event, XbmcThreads::EndTime<> &timeout)
static NPT_String TranslateWMPObjectId (NPT_String id, const Logger &logger)
NPT_Result ObjectIDValidate (const NPT_String &id)
static NPT_String FindSubCriteria (NPT_String criteria, const char *name)
Variables
static NPT_List< void * > g_UserData
static NPT_Mutex g_UserDataLock
constexpr std::array< std::string_view, 9 > SupportedSubFormats
constexpr NPT_HttpFileRequestHandler_DefaultFileTypeMapEntry kodiPlatinumMimeTypeExtensions []
const char * audio_containers []
const char * video_containers []
Enumeration Type Documentation
EClientQuirks
enum UPNP::EClientQuirks
Enumerator
ECLIENTQUIRKS_NONE
ECLIENTQUIRKS_ONLYSTORAGEFOLDER
ECLIENTQUIRKS_BASICVIDEOCLASS
ECLIENTQUIRKS_UNKNOWNSERIES
EMediaControllerQuirks
enum UPNP::EMediaControllerQuirks
Enumerator
EMEDIACONTROLLERQUIRKS_NONE
EMEDIACONTROLLERQUIRKS_X_MKV
UPnPService
enum UPNP::UPnPService
Enumerator
UPnPServiceNone
UPnPClient
UPnPContentDirectory
UPnPPlayer
UPnPRenderer
Function Documentation
BuildObject() [1/2]
PLT_MediaObject * UPNP::BuildObject (CFileItem & item, NPT_String & file_path, bool with_count, NPT_Reference< CThumbLoader > & thumb_loader, const PLT_HttpRequestContext * context, CUPnPServer * upnp_server, UPnPService upnp_service)
Todo:
get file count of this directory
References UPNP::CUPnPServer::AddSafeResourceUri(), UPNP::CUPnPServer::AddSubtitleUriForSecResponse(), UPNP::CUPnPServer::BuildSafeResourceUri(), CLangCodeExpander::ConvertToISO6392B(), CorrectAllItemsSortHack(), DecodeObjectId(), ECLIENTQUIRKS_ONLYSTORAGEFOLDER, ECLIENTQUIRKS_UNKNOWNSERIES, EncodeObjectId(), g_LangCodeExpander, CGUIListItem::GetArt(), CDateTime::GetAsW3CDate(), GetClientQuirks(), XFILE::CMusicDatabaseDirectory::GetDirectoryType(), XFILE::CVideoDatabaseDirectory::GetDirectoryType(), URIUtils::GetExtension(), CUtil::GetExternalStreamDetailsFromFilename(), CGUIListItem::GetLabel(), CLog::GetLogger(), CServiceBroker::GetLogging(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), ContentUtils::GetPreferredArtImage(), CURL::GetProtocol(), GetProtocolInfo(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetTextureCache(), CFileItem::GetURL(), CFileItem::GetVideoInfoTag(), CFileItem::HasMusicInfoTag(), CFileItem::HasVideoInfoTag(), KODI::MUSIC::IsAudio(), KODI::MUSIC::IsMusicDb(), CFileItem::IsPicture(), KODI::PLAYLIST::IsPlayList(), URIUtils::IsRemote(), KODI::PLAYLIST::IsSmartPlayList(), CDateTime::IsValid(), CLog::Log(), LOGERROR, CGUIListItem::m_bIsFolder, CFileItem::m_dateTime, CFileItem::m_dwSize, CVideoInfoTag::m_strTitle, node, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ACTOR, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ARTIST, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SEASONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_TVSHOWS, PopulateObjectFromTag(), URIUtils::RemoveExtension(), CUtil::ScanForExternalSubtitles(), CSettings::SETTING_SERVICES_UPNPLOOKFOREXTERNALSUBTITLES, SupportedSubFormats, UPnPPlayer, UPnPRenderer, and IMAGE_FILES::URLFromFile().
Referenced by UPNP::CUPnPServer::Build(), XFILE::CUPnPDirectory::GetDirectory(), GetFileItem(), UPNP::CUPnPRenderer::GetMetadata(), UPNP::CUPnPPlayer::PlayFile(), and UPNP::CUPnPPlayer::QueueNextFile().
BuildObject() [2/2]
std::shared_ptr< CFileItem > UPNP::BuildObject (PLT_MediaObject * entry, UPnPService upnp_service)
Todo:
fill pictureinfotag?
References GetResource(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, index(), MediaTypeEpisode, MediaTypeMovie, MediaTypeSeason, MediaTypeTvShow, and PopulateTagFromObject().
CorrectAllItemsSortHack()
const std::string & UPNP::CorrectAllItemsSortHack (const std::string & item)
Referenced by BuildObject().
DecodeObjectId()
NPT_String UPNP::DecodeObjectId (const std::string & id)
Provided a given encoded object id, decode it into a format known by the application @Note base64 is currently used as the expected input format.
Parameters
id the object it to decode
Returns
the decoded object id
Todo:
all other items except upnproot and -1 (the parent of upnproot) seem to only be enabled
References Base64::Decode(), URIUtils::IsURL(), LOGERROR, and LOGWARNING.
Referenced by BuildObject(), UPNP::CUPnPServer::OnBrowseDirectChildren(), UPNP::CUPnPServer::OnBrowseMetadata(), UPNP::CUPnPServer::OnSearchContainer(), and UPNP::CUPnPServer::OnUpdateObject().
EncodeObjectId()
NPT_String UPNP::EncodeObjectId (const std::string & id)
Provided a given object id, encode it into a safe format to provide to UPnP clients @Note base64 is currently used as the safe format.
Parameters
id the object it to encode
Returns
the encoded object id
Todo:
all other items except upnproot and -1 (the parent of upnproot) seem to only be enabled
References Base64::Encode(), and LOGWARNING.
Referenced by UPNP::CUPnPServer::Build(), BuildObject(), UPNP::CUPnPServer::OnBrowseMetadata(), PopulateObjectFromTag(), PopulateObjectFromTag(), and UPNP::CUPnPServer::PropagateUpdates().
FindSubCriteria()
static NPT_String UPNP::FindSubCriteria (NPT_String criteria, const char * name) static
References name.
Referenced by UPNP::CUPnPServer::OnSearchContainer().
GetClientQuirks()
EClientQuirks UPNP::GetClientQuirks (const PLT_HttpRequestContext * context)
References ECLIENTQUIRKS_BASICVIDEOCLASS, ECLIENTQUIRKS_NONE, ECLIENTQUIRKS_ONLYSTORAGEFOLDER, and ECLIENTQUIRKS_UNKNOWNSERIES.
Referenced by BuildObject().
GetFileItem()
std::shared_ptr< CFileItem > UPNP::GetFileItem (const NPT_String & uri, const NPT_String & meta)
References BuildObject(), and GetResource().
Referenced by UPNP::CUPnPRenderer::OnSetNextAVTransportURI(), and UPNP::CUPnPRenderer::PlayMedia().
GetMediaControllerQuirks()
EMediaControllerQuirks UPNP::GetMediaControllerQuirks (const PLT_DeviceData * device)
References EMEDIACONTROLLERQUIRKS_NONE, and EMEDIACONTROLLERQUIRKS_X_MKV.
Referenced by UPNP::CUPnPPlayer::PlayFile().
GetMimeType() [1/2]
NPT_String UPNP::GetMimeType (const CFileItem & item, const PLT_HttpRequestContext * context)
References URIUtils::GetExtension(), XFILE::CStackDirectory::GetFirstStackedFile(), CFileItem::GetMimeType(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), CVideoInfoTag::GetPath(), MUSIC_INFO::CMusicInfoTag::GetURL(), CFileItem::GetVideoInfoTag(), CFileItem::HasMusicInfoTag(), CFileItem::HasVideoInfoTag(), KODI::MUSIC::IsAudio(), KODI::MUSIC::IsMusicDb(), CFileItem::IsPicture(), URIUtils::IsStack(), and kodiPlatinumMimeTypeExtensions.
GetMimeType() [2/2]
NPT_String UPNP::GetMimeType (const char * filename, const PLT_HttpRequestContext * context)
References URIUtils::GetExtension().
Referenced by GetProtocolInfo(), and UPNP::CUPnPRenderer::ProcessHttpGetRequest().
GetMimeTypeFromExtension()
const char * UPNP::GetMimeTypeFromExtension (const char * extension, const PLT_HttpRequestContext * context = NULL)
GetProtocolInfo()
const NPT_String UPNP::GetProtocolInfo (const CFileItem & item, const char * protocol, const PLT_HttpRequestContext * context)
Todo:
fixup the protocol just in case nothing was passed
map protocol to right prefix and use xbmc-get for unsupported UPnP protocols for other xbmc clients
Todo:
add rtsp ?
References GetMimeType(), CURL::GetProtocol(), and CFileItem::GetURL().
Referenced by BuildObject().
GetResource()
bool UPNP::GetResource (const PLT_MediaObject * entry, CFileItem & item)
References CLog::GetLogger(), CServiceBroker::GetLogging(), CFileItem::GetMimeType(), CFileItem::GetPath(), CGUIListItem::SetArt(), CFileItem::SetDynPath(), CFileItem::SetMimeType(), CGUIListItem::SetProperty(), and SupportedSubFormats.
Referenced by BuildObject(), GetFileItem(), and XFILE::CUPnPDirectory::GetResource().
ObjectIDValidate()
NPT_Result UPNP::ObjectIDValidate (const NPT_String & id)
References CFileUtils::RemoteAccessAllowed().
Referenced by UPNP::CUPnPServer::OnBrowseDirectChildren(), and UPNP::CUPnPServer::OnBrowseMetadata().
PopulateObjectFromTag() [1/2]
NPT_Result UPNP::PopulateObjectFromTag (CMusicInfoTag & tag, PLT_MediaObject & object, NPT_String * file_path, PLT_MediaItemResource * resource, EClientQuirks quirks, UPnPService service)
References EncodeObjectId(), URIUtils::GetExtension(), and index().
Referenced by BuildObject().
PopulateObjectFromTag() [2/2]
NPT_Result UPNP::PopulateObjectFromTag (CVideoInfoTag & tag, PLT_MediaObject & object, NPT_String * file_path, PLT_MediaItemResource * resource, EClientQuirks quirks, UPnPService service)
References ECLIENTQUIRKS_BASICVIDEOCLASS, EncodeObjectId(), CDateTime::GetAsW3CDate(), CStreamDetails::GetAudioChannels(), CServiceBroker::GetSettingsComponent(), CStreamDetails::GetVideoHeight(), CStreamDetails::GetVideoWidth(), index(), MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSeason, and MediaTypeTvShow.
PopulateTagFromObject() [1/2]
NPT_Result UPNP::PopulateTagFromObject (CMusicInfoTag & tag, PLT_MediaObject & object, PLT_MediaItemResource * resource, UPnPService service)
References CDateTime::SetFromW3CDateTime().
Referenced by BuildObject().
PopulateTagFromObject() [2/2]
NPT_Result UPNP::PopulateTagFromObject (CVideoInfoTag & tag, PLT_MediaObject & object, PLT_MediaItemResource * resource, UPnPService service)
References CServiceBroker::GetSettingsComponent(), index(), CDateTime::IsValid(), MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSeason, MediaTypeTvShow, CDateTime::SetFromW3CDate(), and SActorInfo::strName.
TranslateWMPObjectId()
static NPT_String UPNP::TranslateWMPObjectId (NPT_String id, const Logger & logger) static
References id.
Referenced by UPNP::CUPnPServer::OnBrowseDirectChildren(), and UPNP::CUPnPServer::OnBrowseMetadata().
WaitOnEvent()
static NPT_Result UPNP::WaitOnEvent (CEvent & event, XbmcThreads::EndTime<> & timeout) static
References CEvent::Wait(), and CGUIDialogBusy::WaitOnEvent().
Referenced by UPNP::CUPnPPlayer::OpenFile(), and UPNP::CUPnPPlayer::PlayFile().
Variable Documentation
audio_containers
const char* UPNP::audio_containers[]
Initial value:
= {"musicdb://genres/",
                                  "musicdb://artists/",
                                  "musicdb://albums/",
                                  "musicdb://songs/",
                                  "musicdb://recentlyaddedalbums/",
                                  "musicdb://years/",
                                  "musicdb://singles/"}
Referenced by UPNP::CUPnPServer::OnScanCompleted().
g_UserData
NPT_List<void*> UPNP::g_UserData static
Referenced by UPNP::CUPnP::RegisterUserdata(), and UPNP::CUPnP::UnregisterUserdata().
g_UserDataLock
NPT_Mutex UPNP::g_UserDataLock static
Referenced by UPNP::CMediaController::OnGetMediaInfoResult(), UPNP::CMediaController::OnGetPositionInfoResult(), UPNP::CMediaController::OnGetTransportInfoResult(), UPNP::CMediaController::OnNextResult(), UPNP::CMediaController::OnPauseResult(), UPNP::CMediaController::OnPlayResult(), UPNP::CMediaController::OnPreviousResult(), UPNP::CMediaController::OnSeekResult(), UPNP::CMediaController::OnSetAVTransportURIResult(), UPNP::CMediaController::OnSetPlayModeResult(), UPNP::CMediaController::OnStopResult(), UPNP::CUPnP::RegisterUserdata(), and UPNP::CUPnP::UnregisterUserdata().
kodiPlatinumMimeTypeExtensions
constexpr NPT_HttpFileRequestHandler_DefaultFileTypeMapEntry UPNP::kodiPlatinumMimeTypeExtensions[] constexpr
Initial value:
= {
    {"m2ts", "video/vnd.dlna.mpeg-tts"}}
Referenced by GetMimeType().
SupportedSubFormats
constexpr std::array<std::string_view, 9> UPNP::SupportedSubFormats constexpr
Initial value:
= {
    "txt", "srt", "ssa", "ass", "sub", "smi", "vtt",
    "sup", "idx"}
Referenced by BuildObject(), and GetResource().
video_containers
const char* UPNP::video_containers[]
Initial value:
= {
    "library://video/movies/titles.xml/", "library://video/tvshows/titles.xml/",
    "videodb://recentlyaddedmovies/", "videodb://recentlyaddedepisodes/"}
Referenced by UPNP::CUPnPServer::OnScanCompleted().