Kodi Documentation: KODI::RETRO::CRPProcessInfo Class Reference
KODI::RETRO::CRPProcessInfo Class Reference
Player process info.
#include <RPProcessInfo.h>
Public Member Functions
virtual ~CRPProcessInfo ()
const std::string & GetPlatformName () const
Get the descriptive name of the platform.
std::string GetRenderSystemName (IRenderBufferPool *renderBufferPool) const
Get the descriptive name of the rendering system.
CRPBaseRenderer * CreateRenderer (IRenderBufferPool *renderBufferPool, const CRenderSettings &renderSettings)
Create a renderer.
void SetDataCache (CDataCacheCore *cache)
Set data cache.
void ResetInfo ()
Reset data cache info.
Rendering functions
{
CRenderContext & GetRenderContext ()
Get the context shared by the rendering system.
CRenderBufferManager & GetBufferManager ()
Get the buffer manager that owns the buffer pools.
bool HasScalingMethod (SCALINGMETHOD scalingMethod) const
Check if a buffer pool supports the given scaling method.
SCALINGMETHOD GetDefaultScalingMethod () const
Get the default scaling method for this rendering system.
Player video info
}
{
void SetVideoPixelFormat (AVPixelFormat pixFormat)
void SetVideoDimensions (int width, int height)
void SetVideoFps (float fps)
Player audio info
}
{
void SetAudioChannels (const std::string &channels)
void SetAudioSampleRate (int sampleRate)
void SetAudioBitsPerSample (int bitsPerSample)
Static Public Member Functions
static std::unique_ptr< CRPProcessInfo > CreateInstance ()
static void RegisterProcessControl (const CreateRPProcessControl &createFunc)
static void RegisterRendererFactory (IRendererFactory *factory)
Player states
}
{
static CreateRPProcessControl m_processControl = nullptr
static std::vector< std::unique_ptr< IRendererFactory > > m_rendererFactories
static CCriticalSection m_createSection
const std::string m_platformName
CDataCacheCore * m_dataCache = nullptr
std::unique_ptr< CRenderBufferManager > m_renderBufferManager
std::unique_ptr< CRenderContext > m_renderContext
SCALINGMETHOD m_defaultScalingMethod = SCALINGMETHOD::AUTO
void SetSpeed (float speed)
void SetPlayTimes (time_t start, int64_t current, int64_t min, int64_t max)
CRPProcessInfo (std::string platformName)
}
static std::vector< SCALINGMETHOD > GetScalingMethods ()
Get all scaling methods available to the rendering system.
Detailed Description
Player process info.
Constructor & Destructor Documentation
~CRPProcessInfo()
CRPProcessInfo::~CRPProcessInfo () virtual default
CRPProcessInfo()
CRPProcessInfo::CRPProcessInfo (std::string platformName) protected
}
Constructor
Parameters
platformName A descriptive name of the platform
References GetScalingMethods(), HasScalingMethod(), m_defaultScalingMethod, m_renderBufferManager, m_renderContext, and m_rendererFactories.
Member Function Documentation
CreateInstance()
std::unique_ptr< CRPProcessInfo > CRPProcessInfo::CreateInstance () static
References CLog::Log(), LOGERROR, LOGINFO, m_createSection, and m_processControl.
Referenced by KODI::RETRO::CRetroPlayer::OpenFile().
CreateRenderer()
CRPBaseRenderer * CRPProcessInfo::CreateRenderer (IRenderBufferPool * renderBufferPool, const CRenderSettings & renderSettings)
Create a renderer.
Parameters
renderBufferPool The buffer pool used to return render buffers
renderSettings The settings for this renderer
Returns
The renderer, or nullptr on failure
References CLog::Log(), LOGERROR, m_createSection, m_renderBufferManager, m_renderContext, and m_rendererFactories.
Referenced by KODI::RETRO::CRPRenderManager::GetRendererForPool().
GetBufferManager()
CRenderBufferManager & KODI::RETRO::CRPProcessInfo::GetBufferManager () inline
Get the buffer manager that owns the buffer pools.
References m_renderBufferManager.
Referenced by KODI::RETRO::CRPRenderManager::AddFrame(), KODI::RETRO::CRPRenderManager::CheckFlush(), KODI::RETRO::CRPRenderManager::GetRendererForSettings(), KODI::RETRO::CRPRenderManager::GetVideoBuffer(), KODI::RETRO::CRPRenderManager::LoadVideoFrameSync(), and KODI::RETRO::CRPRenderManager::SupportsScalingMethod().
GetDefaultScalingMethod()
SCALINGMETHOD KODI::RETRO::CRPProcessInfo::GetDefaultScalingMethod () const inline
Get the default scaling method for this rendering system.
References m_defaultScalingMethod.
Referenced by KODI::RETRO::CRPRenderManager::GetEffectiveSettings().
GetPlatformName()
const std::string & KODI::RETRO::CRPProcessInfo::GetPlatformName () const inline
Get the descriptive name of the platform.
Returns
The name of the platform as set by windowing
References m_platformName.
GetRenderContext()
CRenderContext & KODI::RETRO::CRPProcessInfo::GetRenderContext () inline
Get the context shared by the rendering system.
References m_renderContext.
Referenced by KODI::RETRO::CGUIGameSettings::CGUIGameSettings(), KODI::RETRO::CRetroPlayerInput::StartAgentManager(), and KODI::RETRO::CRetroPlayerInput::StopAgentManager().
GetRenderSystemName()
std::string CRPProcessInfo::GetRenderSystemName (IRenderBufferPool * renderBufferPool) const
Get the descriptive name of the rendering system.
Parameters
renderBufferPool A pool belonging to the rendering system
Returns
The name of the rendering system as set by windowing
References m_renderBufferManager.
Referenced by KODI::RETRO::CRPRenderManager::GetRendererForPool().
GetScalingMethods()
std::vector< SCALINGMETHOD > CRPProcessInfo::GetScalingMethods () static protected
Get all scaling methods available to the rendering system.
References KODI::RETRO::LINEAR, and KODI::RETRO::NEAREST.
Referenced by CRPProcessInfo().
HasScalingMethod()
bool CRPProcessInfo::HasScalingMethod (SCALINGMETHOD scalingMethod) const
Check if a buffer pool supports the given scaling method.
References m_renderBufferManager.
Referenced by CRPProcessInfo(), and KODI::RETRO::CRPRenderManager::GetEffectiveSettings().
RegisterProcessControl()
void CRPProcessInfo::RegisterProcessControl (const CreateRPProcessControl & createFunc) static
References m_processControl.
Referenced by KODI::RETRO::CRPProcessInfoAndroid::Register(), KODI::RETRO::CRPProcessInfoGbm::Register(), KODI::RETRO::CRPProcessInfoIOS::Register(), KODI::RETRO::CRPProcessInfoOSX::Register(), KODI::RETRO::CRPProcessInfoWayland::Register(), KODI::RETRO::CRPProcessInfoWin::Register(), and KODI::RETRO::CRPProcessInfoX11::Register().
RegisterRendererFactory()
void CRPProcessInfo::RegisterRendererFactory (IRendererFactory * factory) static
References CLog::Log(), LOGINFO, m_createSection, m_rendererFactories, and KODI::RETRO::IRendererFactory::RenderSystemName().
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::InitWindowSystem(), KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::RefreshGLContext().
ResetInfo()
void CRPProcessInfo::ResetInfo ()
Reset data cache info.
References m_dataCache, and CDataCacheCore::Reset().
SetAudioBitsPerSample()
void CRPProcessInfo::SetAudioBitsPerSample (int bitsPerSample)
References m_dataCache, and CDataCacheCore::SetAudioBitsPerSample().
Referenced by KODI::RETRO::CRetroPlayerAudio::OpenStream().
SetAudioChannels()
void CRPProcessInfo::SetAudioChannels (const std::string & channels)
References m_dataCache, and CDataCacheCore::SetAudioChannels().
Referenced by KODI::RETRO::CRetroPlayerAudio::OpenStream().
SetAudioSampleRate()
void CRPProcessInfo::SetAudioSampleRate (int sampleRate)
References m_dataCache, and CDataCacheCore::SetAudioSampleRate().
Referenced by KODI::RETRO::CRetroPlayerAudio::OpenStream().
SetDataCache()
void CRPProcessInfo::SetDataCache (CDataCacheCore * cache)
Set data cache.
References m_dataCache.
SetPlayTimes()
void CRPProcessInfo::SetPlayTimes (time_t start, int64_t current, int64_t min, int64_t max)
References m_dataCache, max, min, and CDataCacheCore::SetPlayTimes().
SetSpeed()
void CRPProcessInfo::SetSpeed (float speed)
References m_dataCache, and CDataCacheCore::SetSpeed().
SetVideoDimensions()
void CRPProcessInfo::SetVideoDimensions (int width, int height)
References m_dataCache, and CDataCacheCore::SetVideoDimensions().
Referenced by KODI::RETRO::CRetroPlayerVideo::OpenStream().
SetVideoFps()
void CRPProcessInfo::SetVideoFps (float fps)
References m_dataCache, and CDataCacheCore::SetVideoFps().
SetVideoPixelFormat()
void CRPProcessInfo::SetVideoPixelFormat (AVPixelFormat pixFormat)
References m_dataCache, and CDataCacheCore::SetVideoPixelFormat().
Referenced by KODI::RETRO::CRetroPlayerVideo::OpenStream().
Member Data Documentation
m_createSection
CCriticalSection CRPProcessInfo::m_createSection static protected
Referenced by CreateInstance(), CreateRenderer(), and RegisterRendererFactory().
m_dataCache
CDataCacheCore* KODI::RETRO::CRPProcessInfo::m_dataCache = nullptr protected
Referenced by ResetInfo(), SetAudioBitsPerSample(), SetAudioChannels(), SetAudioSampleRate(), SetDataCache(), SetPlayTimes(), SetSpeed(), SetVideoDimensions(), SetVideoFps(), and SetVideoPixelFormat().
m_defaultScalingMethod
SCALINGMETHOD KODI::RETRO::CRPProcessInfo::m_defaultScalingMethod = SCALINGMETHOD::AUTO private
Referenced by CRPProcessInfo(), and GetDefaultScalingMethod().
m_platformName
const std::string KODI::RETRO::CRPProcessInfo::m_platformName protected
Referenced by GetPlatformName().
m_processControl
CreateRPProcessControl CRPProcessInfo::m_processControl = nullptr static protected
Referenced by CreateInstance(), and RegisterProcessControl().
m_renderBufferManager
std::unique_ptr<CRenderBufferManager> KODI::RETRO::CRPProcessInfo::m_renderBufferManager protected
Referenced by CreateRenderer(), CRPProcessInfo(), GetBufferManager(), GetRenderSystemName(), and HasScalingMethod().
m_renderContext
std::unique_ptr<CRenderContext> KODI::RETRO::CRPProcessInfo::m_renderContext private
Referenced by CreateRenderer(), CRPProcessInfo(), and GetRenderContext().
m_rendererFactories
std::vector< std::unique_ptr< IRendererFactory > > CRPProcessInfo::m_rendererFactories static protected
Referenced by CreateRenderer(), CRPProcessInfo(), and RegisterRendererFactory().
The documentation for this class was generated from the following files:
RPProcessInfo.h
RPProcessInfo.cpp