Kodi Documentation: CWebSocketMessage Class Reference
CWebSocketMessage Class Reference
#include <WebSocket.h>
Public Member Functions
CWebSocketMessage ()
virtual ~CWebSocketMessage ()
virtual bool IsFragmented () const
virtual bool IsComplete () const
virtual bool AddFrame (const CWebSocketFrame *frame)
virtual const std::vector< const CWebSocketFrame * > & GetFrames () const
virtual void Clear ()
Protected Attributes
std::vector< const CWebSocketFrame * > m_frames
bool m_fragmented
bool m_complete
Constructor & Destructor Documentation
CWebSocketMessage()
CWebSocketMessage::CWebSocketMessage ()
References Clear().
~CWebSocketMessage()
CWebSocketMessage::~CWebSocketMessage () virtual
References index(), and m_frames.
Member Function Documentation
AddFrame()
bool CWebSocketMessage::AddFrame (const CWebSocketFrame * frame) virtual
References CWebSocketFrame::IsFinal(), CWebSocketFrame::IsValid(), m_complete, m_fragmented, and m_frames.
Referenced by CWebSocket::Handle(), and CWebSocket::Send().
Clear()
void CWebSocketMessage::Clear () virtual
References m_complete, m_fragmented, and m_frames.
Referenced by CWebSocketMessage().
GetFrames()
virtual const std::vector< const CWebSocketFrame * > & CWebSocketMessage::GetFrames () const inline virtual
References m_frames.
Referenced by JSONRPC::CTCPServer::CWebSocketClient::PushBuffer(), and JSONRPC::CTCPServer::CWebSocketClient::Send().
IsComplete()
virtual bool CWebSocketMessage::IsComplete () const inline virtual
References m_complete.
Referenced by CWebSocket::Handle(), JSONRPC::CTCPServer::CWebSocketClient::PushBuffer(), JSONRPC::CTCPServer::CWebSocketClient::Send(), and CWebSocket::Send().
IsFragmented()
virtual bool CWebSocketMessage::IsFragmented () const inline virtual
References m_fragmented.
Member Data Documentation
m_complete
bool CWebSocketMessage::m_complete protected
Referenced by AddFrame(), Clear(), and IsComplete().
m_fragmented
bool CWebSocketMessage::m_fragmented protected
Referenced by AddFrame(), Clear(), and IsFragmented().
m_frames
std::vector<const CWebSocketFrame *> CWebSocketMessage::m_frames protected
Referenced by AddFrame(), Clear(), GetFrames(), and ~CWebSocketMessage().
The documentation for this class was generated from the following files:
WebSocket.h
WebSocket.cpp