Kodi Documentation: PVR::CPVREpgContainer Class Reference
PVR::CPVREpgContainer Class Reference
#include <EpgContainer.h>
Public Member Functions
CPVREpgContainer ()=delete
CPVREpgContainer (CEventSource< PVREvent > &eventSource)
Create a new EPG table container.
~CPVREpgContainer () override
Destroy this instance.
std::shared_ptr< CPVREpgDatabase > GetEpgDatabase () const
Get a pointer to the database instance.
void Start ()
Start the EPG update thread.
void Stop ()
Stop the EPG update thread.
bool Load ()
(re)load EPG data.
void Unload ()
unload all EPG data.
bool IsStarted () const
Check whether the EpgContainer has fully started.
bool QueueDeleteEpgs (const std::vector< std::shared_ptr< CPVREpg > > &epgs)
Queue the deletion of the given EPG tables from this container.
void Notify (const PVREvent &event)
CEventStream callback for PVR events.
std::shared_ptr< CPVREpg > CreateChannelEpg (int iEpgId, const std::string &strScraperName, const std::shared_ptr< CPVREpgChannelData > &channelData)
Create the EPg for a given channel.
std::pair< CDateTime, CDateTime > GetFirstAndLastEPGDate () const
Get the start and end time across all EPGs.
std::vector< std::shared_ptr< CPVREpg > > GetAllEpgs () const
Get all EPGs.
std::shared_ptr< CPVREpg > GetById (int iEpgId) const
Get an EPG given its ID.
std::shared_ptr< CPVREpg > GetByChannelUid (int iClientId, int iChannelUid) const
Get an EPG given its client id and channel uid.
std::shared_ptr< CPVREpgInfoTag > GetTagById (const std::shared_ptr< const CPVREpg > &epg, unsigned int iBroadcastId) const
Get the EPG event with the given event id.
std::shared_ptr< CPVREpgInfoTag > GetTagByDatabaseId (int iDatabaseId) const
Get the EPG event with the given database id.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetTags (const PVREpgSearchData &searchData) const
Get all EPG tags matching the given search criteria.
void SetHasPendingUpdates (bool bHasPendingUpdates=true)
Notify EPG container that there are pending manual EPG updates.
void UpdateRequest (int iClientID, int iUniqueChannelID)
A client triggered an epg update request for a channel.
void UpdateFromClient (const std::shared_ptr< CPVREpgInfoTag > &tag, EPG_EVENT_STATE eNewState)
A client announced an updated epg tag for a channel.
int GetPastDaysToDisplay () const
Get the number of past days to show in the guide and to import from backends.
int GetFutureDaysToDisplay () const
Get the number of future days to show in the guide and to import from backends.
void OnPlaybackStarted ()
Inform the epg container that playback of an item just started.
void OnPlaybackStopped ()
Inform the epg container that playback of an item was stopped due to user interaction.
void OnSystemSleep ()
Inform the epg container that the system is going to sleep.
void OnSystemWake ()
Inform the epg container that the system gets awake from sleep.
int CleanupCachedImages ()
Erase stale texture db entries and image files.
std::vector< std::shared_ptr< CPVREpgSearchFilter > > GetSavedSearches (bool bRadio) const
Get all saved searches from the database.
std::shared_ptr< CPVREpgSearchFilter > GetSavedSearchById (bool bRadio, int iId) const
Get the saved search matching the given id.
bool PersistSavedSearch (CPVREpgSearchFilter &search)
Persist a saved search in the database.
bool UpdateSavedSearchLastExecuted (const CPVREpgSearchFilter &epgSearch)
Update time last executed for the given search.
bool DeleteSavedSearch (const CPVREpgSearchFilter &search)
Delete a saved search from the database.
Private Member Functions
bool CheckPlayingEvents ()
Notify EPG table observers when the currently active tag changed.
int NextEpgId ()
The next EPG ID to be given to a table when the db isn't being used.
void WaitForUpdateFinish ()
Wait for an EPG update to finish.
bool PersistAll (unsigned int iMaxTimeslice) const
Call Persist() on each table.
bool RemoveOldEntries ()
Remove old EPG entries.
bool UpdateEPG (bool bOnlyPending=false)
Load and update the EPG data.
bool InterruptUpdate () const
Check whether a running update should be interrupted.
void Process () override
EPG update thread.
void LoadFromDatabase ()
Load all tables from the database.
void InsertFromDB (const std::shared_ptr< CPVREpg > &newEpg)
Insert data from database.
bool QueueDeleteEpg (const std::shared_ptr< const CPVREpg > &epg, const std::shared_ptr< CPVREpgDatabase > &database)
Queue the deletion of an EPG table from this container.
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Attributes
std::shared_ptr< CPVREpgDatabase > m_database
bool m_bIsUpdating = false
std::atomic< bool > m_bIsInitialising
bool m_bStarted = false
bool m_bLoaded = false
bool m_bPreventUpdates = false
bool m_bPlaying = false
int m_pendingUpdates = 0
time_t m_iLastEpgCleanup = 0
time_t m_iNextEpgUpdate = 0
time_t m_iNextEpgActiveTagCheck = 0
int m_iNextEpgId = 0
std::map< int, std::shared_ptr< CPVREpg > > m_epgIdToEpgMap
std::map< std::pair< int, int >, std::shared_ptr< CPVREpg > > m_channelUidToEpgMap
CCriticalSection m_critSection
CEvent m_updateEvent
std::list< CEpgUpdateRequest > m_updateRequests
CCriticalSection m_updateRequestsLock
std::list< CEpgTagStateChange > m_epgTagChanges
CCriticalSection m_epgTagChangesLock
bool m_bUpdateNotificationPending = false
CPVRSettings m_settings
CEventSource< PVREvent > & m_events
std::atomic< bool > m_bSuspended = {false}
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Friends
class CPVREpgDatabase
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Constructor & Destructor Documentation
CPVREpgContainer() [1/2]
PVR::CPVREpgContainer::CPVREpgContainer () delete
CPVREpgContainer() [2/2]
PVR::CPVREpgContainer::CPVREpgContainer (CEventSource< PVREvent > & eventSource) explicit
Create a new EPG table container.
References CSettings::SETTING_EPG_EPGUPDATE, CSettings::SETTING_EPG_FUTURE_DAYSTODISPLAY, CSettings::SETTING_EPG_PAST_DAYSTODISPLAY, and CSettings::SETTING_EPG_PREVENTUPDATESWHILEPLAYINGTV.
~CPVREpgContainer()
PVR::CPVREpgContainer::~CPVREpgContainer () override
Destroy this instance.
References Stop(), and Unload().
Member Function Documentation
CheckPlayingEvents()
bool PVR::CPVREpgContainer::CheckPlayingEvents () private
Notify EPG table observers when the currently active tag changed.
Returns
True if the check was done, false if it was not the right time to check
References PVR::EpgActiveItem, CDateTime::GetAsTime(), CDateTime::GetAsUTCDateTime(), CDateTime::GetCurrentDateTime(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), IsStarted(), m_critSection, m_epgIdToEpgMap, m_events, m_iNextEpgActiveTagCheck, and CEventSource< Event >::Publish().
Referenced by Process().
CleanupCachedImages()
int PVR::CPVREpgContainer::CleanupCachedImages ()
Erase stale texture db entries and image files.
Returns
number of cleaned up images.
References GetEpgDatabase(), LOGERROR, m_critSection, and m_epgIdToEpgMap.
Referenced by PVR::CPVRManager::TriggerCleanupCachedImages().
CreateChannelEpg()
std::shared_ptr< CPVREpg > PVR::CPVREpgContainer::CreateChannelEpg (int iEpgId, const std::string & strScraperName, const std::shared_ptr< CPVREpgChannelData > & channelData)
Create the EPg for a given channel.
Parameters
iEpgId The EPG id.
strScraperName The scraper name.
channelData The channel data.
Returns
the created EPG
References PVR::EpgContainer, CDateTime::GetAsTime(), CDateTime::GetAsUTCDateTime(), GetById(), CDateTime::GetCurrentDateTime(), GetEpgDatabase(), LoadFromDatabase(), m_bPreventUpdates, m_channelUidToEpgMap, m_critSection, m_epgIdToEpgMap, m_events, m_iNextEpgUpdate, NextEpgId(), Notify(), CEventSource< Event >::Publish(), and WaitForUpdateFinish().
Referenced by PVR::CPVRChannel::CreateEPG().
DeleteSavedSearch()
bool PVR::CPVREpgContainer::DeleteSavedSearch (const CPVREpgSearchFilter & search)
Delete a saved search from the database.
Parameters
search The saved search.
Returns
True on success, false otherwise.
References GetEpgDatabase(), LOGERROR, m_events, CEventSource< Event >::Publish(), and PVR::SavedSearchesInvalidated.
Referenced by PVR::CPVRGUIActionsEPG::DeleteSavedSearch().
GetAllEpgs()
std::vector< std::shared_ptr< CPVREpg > > PVR::CPVREpgContainer::GetAllEpgs () const
Get all EPGs.
Returns
The EPGs.
References m_critSection, and m_epgIdToEpgMap.
Referenced by anonymous_namespace{PVRTimers.cpp}::AddTimerRuleToEpgMap(), and anonymous_namespace{PVRTimers.cpp}::GetEpgTagsForTimerRule().
GetByChannelUid()
std::shared_ptr< CPVREpg > PVR::CPVREpgContainer::GetByChannelUid (int iClientId, int iChannelUid) const
Get an EPG given its client id and channel uid.
Parameters
iClientId the id of the pvr client providing the EPG
iChannelUid the uid of the channel for the EPG
Returns
The EPG or nullptr if it wasn't found.
References m_channelUidToEpgMap, and m_critSection.
Referenced by PVR::CPVRPlaybackState::GetNextAutoplayItem(), Process(), PVR::CPVRPlaybackState::ReInit(), and PVR::CPVRTimers::UpdateEntries().
GetById()
std::shared_ptr< CPVREpg > PVR::CPVREpgContainer::GetById (int iEpgId) const
Get an EPG given its ID.
Parameters
iEpgId The database ID of the table.
Returns
The EPG or nullptr if it wasn't found.
References m_critSection, and m_epgIdToEpgMap.
Referenced by CreateChannelEpg(), and InsertFromDB().
GetEpgDatabase()
std::shared_ptr< CPVREpgDatabase > PVR::CPVREpgContainer::GetEpgDatabase () const
Get a pointer to the database instance.
Returns
A pointer to the database instance.
References m_critSection, and m_database.
Referenced by CleanupCachedImages(), CreateChannelEpg(), DeleteSavedSearch(), GetFirstAndLastEPGDate(), GetSavedSearchById(), GetSavedSearches(), GetTags(), LoadFromDatabase(), PersistAll(), PersistSavedSearch(), QueueDeleteEpgs(), UpdateEPG(), and UpdateSavedSearchLastExecuted().
GetFirstAndLastEPGDate()
std::pair< CDateTime, CDateTime > PVR::CPVREpgContainer::GetFirstAndLastEPGDate () const
Get the start and end time across all EPGs.
Returns
The times; first: start time, second: end time.
References GetEpgDatabase(), CDateTime::IsValid(), m_critSection, and m_epgIdToEpgMap.
Referenced by PVR::CGUIWindowPVRGuideBase::RefreshTimelineItems(), and PVR::CGUIDialogPVRGuideSearch::Update().
GetFutureDaysToDisplay()
int PVR::CPVREpgContainer::GetFutureDaysToDisplay () const
Get the number of future days to show in the guide and to import from backends.
Returns
the number of future epg days.
References PVR::CPVRSettings::GetIntValue(), m_settings, and CSettings::SETTING_EPG_FUTURE_DAYSTODISPLAY.
Referenced by PVR::CGUIWindowPVRGuideBase::RefreshTimelineItems(), PVR::CPVRClient::ResetProperties(), and UpdateEPG().
GetPastDaysToDisplay()
int PVR::CPVREpgContainer::GetPastDaysToDisplay () const
Get the number of past days to show in the guide and to import from backends.
Returns
the number of past epg days.
References PVR::CPVRSettings::GetIntValue(), m_settings, and CSettings::SETTING_EPG_PAST_DAYSTODISPLAY.
Referenced by PVR::CGUIEPGGridContainerModel::GetGridStartPadding(), PVR::CGUIWindowPVRGuideBase::RefreshTimelineItems(), RemoveOldEntries(), PVR::CPVRClient::ResetProperties(), and UpdateEPG().
GetSavedSearchById()
std::shared_ptr< CPVREpgSearchFilter > PVR::CPVREpgContainer::GetSavedSearchById (bool bRadio, int iId) const
Get the saved search matching the given id.
Parameters
bRadio Whether to fetch a TV or radio saved search.
iId The id.
Returns
The saved search or nullptr if not found.
References GetEpgDatabase(), and LOGERROR.
Referenced by PVR::CPVRGUIDirectory::GetSavedSearchResults(), and PVR::CGUIWindowPVRSearchBase::OnMessage().
GetSavedSearches()
std::vector< std::shared_ptr< CPVREpgSearchFilter > > PVR::CPVREpgContainer::GetSavedSearches (bool bRadio) const
Get all saved searches from the database.
Parameters
bRadio Whether to fetch saved searches for radio or TV.
Returns
The searches.
References GetEpgDatabase(), and LOGERROR.
Referenced by PVR::CPVRGUIDirectory::GetSavedSearchesDirectory().
GetTagByDatabaseId()
std::shared_ptr< CPVREpgInfoTag > PVR::CPVREpgContainer::GetTagByDatabaseId (int iDatabaseId) const
Get the EPG event with the given database id.
Parameters
iDatabaseId The id to lookup.
Returns
The requested event, or an empty tag when not found
References m_critSection, and m_epgIdToEpgMap.
Referenced by JSONRPC::CPVROperations::AddTimer(), JSONRPC::CPVROperations::GetBroadcastDetails(), JSONRPC::CPVROperations::GetBroadcastIsPlayable(), JSONRPC::CPlayerOperations::Open(), and JSONRPC::CPVROperations::ToggleTimer().
GetTagById()
std::shared_ptr< CPVREpgInfoTag > PVR::CPVREpgContainer::GetTagById (const std::shared_ptr< const CPVREpg > & epg, unsigned int iBroadcastId) const
Get the EPG event with the given event id.
Parameters
epg The epg to lookup the event.
iBroadcastId The event id to lookup.
Returns
The requested event, or an empty tag when not found
References EPG_TAG_INVALID_UID.
Referenced by PVR::CPVRGUIInfo::GetListItemAndPlayerBool().
GetTags()
std::vector< std::shared_ptr< CPVREpgInfoTag > > PVR::CPVREpgContainer::GetTags (const PVREpgSearchData & searchData) const
Get all EPG tags matching the given search criteria.
Parameters
searchData The search criteria.
Returns
The matching tags.
References GetEpgDatabase(), m_critSection, m_epgIdToEpgMap, and PersistAll().
Referenced by PVR::CPVREpgSearch::Execute().
InsertFromDB()
void PVR::CPVREpgContainer::InsertFromDB (const std::shared_ptr< CPVREpg > & newEpg) private
Insert data from database.
Parameters
newEpg the EPG containing the updated data.
References GetById(), m_critSection, m_epgIdToEpgMap, and Notify().
Referenced by LoadFromDatabase().
InterruptUpdate()
bool PVR::CPVREpgContainer::InterruptUpdate () const private
Check whether a running update should be interrupted.
Returns
True if a running update should be interrupted, false otherwise.
References PVR::CPVRSettings::GetBoolValue(), m_bPlaying, m_bPreventUpdates, CThread::m_bStop, m_critSection, m_settings, and CSettings::SETTING_EPG_PREVENTUPDATESWHILEPLAYINGTV.
Referenced by Process(), and UpdateEPG().
IsStarted()
bool PVR::CPVREpgContainer::IsStarted () const
Check whether the EpgContainer has fully started.
Returns
True if started, false otherwise.
References m_bStarted, and m_critSection.
Referenced by CheckPlayingEvents().
Load()
bool PVR::CPVREpgContainer::Load ()
(re)load EPG data.
Returns
True if loaded successfully, false otherwise.
LoadFromDatabase()
void PVR::CPVREpgContainer::LoadFromDatabase () private
Load all tables from the database.
References GetEpgDatabase(), InsertFromDB(), m_bLoaded, m_critSection, and m_iNextEpgId.
Referenced by CreateChannelEpg().
NextEpgId()
int PVR::CPVREpgContainer::NextEpgId () private
The next EPG ID to be given to a table when the db isn't being used.
Returns
The next ID.
References m_critSection, and m_iNextEpgId.
Referenced by CreateChannelEpg().
Notify()
void PVR::CPVREpgContainer::Notify (const PVREvent & event)
CEventStream callback for PVR events.
Parameters
event The event.
References PVR::EpgActiveItem, PVR::EpgItemUpdate, PVR::EpgUpdatePending, m_bUpdateNotificationPending, m_critSection, m_events, CEventSource< Event >::Publish(), and SetHasPendingUpdates().
Referenced by CreateChannelEpg(), and InsertFromDB().
OnPlaybackStarted()
void PVR::CPVREpgContainer::OnPlaybackStarted ()
Inform the epg container that playback of an item just started.
References m_bPlaying, and m_critSection.
OnPlaybackStopped()
void PVR::CPVREpgContainer::OnPlaybackStopped ()
Inform the epg container that playback of an item was stopped due to user interaction.
References m_bPlaying, and m_critSection.
OnSystemSleep()
void PVR::CPVREpgContainer::OnSystemSleep ()
Inform the epg container that the system is going to sleep.
References m_bSuspended.
OnSystemWake()
void PVR::CPVREpgContainer::OnSystemWake ()
Inform the epg container that the system gets awake from sleep.
References m_bSuspended.
PersistAll()
bool PVR::CPVREpgContainer::PersistAll (unsigned int iMaxTimeslice) const private
Call Persist() on each table.
Parameters
iMaxTimeslice time in milliseconds for max processing. Return after this time even if not all data was persisted, unless value is -1
Returns
True when they all were persisted, false otherwise.
References PVR::EPG_COMMIT_QUERY_COUNT_LIMIT, GetEpgDatabase(), LOGDEBUG, LOGEPG, LOGERROR, m_critSection, and m_epgIdToEpgMap.
Referenced by GetTags(), and Process().
PersistSavedSearch()
bool PVR::CPVREpgContainer::PersistSavedSearch (CPVREpgSearchFilter & search)
Persist a saved search in the database.
Parameters
search The saved search.
Returns
True on success, false otherwise.
References GetEpgDatabase(), LOGERROR, m_events, CEventSource< Event >::Publish(), and PVR::SavedSearchesInvalidated.
Referenced by PVR::CPVRGUIActionsEPG::ChooseIconForSavedSearch(), PVR::CPVRGUIActionsEPG::DuplicateSavedSearch(), PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), PVR::CPVRGUIActionsEPG::RenameSavedSearch(), and PVR::CGUIWindowPVRSearchBase::SetSearchFilter().
Process()
void PVR::CPVREpgContainer::Process (void) override private virtual
EPG update thread.
Reimplemented from CThread.
References CheckPlayingEvents(), PVR::CEpgUpdateRequest::Deliver(), PVR::CEpgTagStateChange::Deliver(), PVR::Epg, CDateTime::GetAsTime(), CDateTime::GetAsUTCDateTime(), GetByChannelUid(), PVR::CEpgUpdateRequest::GetClientID(), CDateTime::GetCurrentDateTime(), CServiceBroker::GetSettingsComponent(), PVR::CEpgTagStateChange::GetTag(), PVR::CEpgUpdateRequest::GetUniqueChannelID(), InterruptUpdate(), CLog::Log(), LOGDEBUG, LOGEPG, LOGINFO, LOWEST, m_bIsInitialising, CThread::m_bStop, m_bSuspended, m_bUpdateNotificationPending, m_critSection, m_epgTagChanges, m_epgTagChangesLock, m_events, m_iLastEpgCleanup, m_iNextEpgUpdate, m_pendingUpdates, m_updateRequests, m_updateRequestsLock, PersistAll(), CEventSource< Event >::Publish(), RemoveOldEntries(), CThread::SetPriority(), CThread::Sleep(), and UpdateEPG().
QueueDeleteEpg()
bool PVR::CPVREpgContainer::QueueDeleteEpg (const std::shared_ptr< const CPVREpg > & epg, const std::shared_ptr< CPVREpgDatabase > & database) private
Queue the deletion of an EPG table from this container.
Parameters
epg The table to delete.
database The database containing the epg data.
Returns
True on success, false otherwise.
References LOGDEBUG, LOGEPG, m_channelUidToEpgMap, m_critSection, and m_epgIdToEpgMap.
Referenced by QueueDeleteEpgs().
QueueDeleteEpgs()
bool PVR::CPVREpgContainer::QueueDeleteEpgs (const std::vector< std::shared_ptr< CPVREpg > > & epgs)
Queue the deletion of the given EPG tables from this container.
Parameters
epg The tables to delete.
Returns
True on success, false otherwise.
References PVR::EPG_COMMIT_QUERY_COUNT_LIMIT, GetEpgDatabase(), LOGERROR, and QueueDeleteEpg().
Referenced by PVR::CPVRChannelGroupAllChannels::RemoveDeletedGroupMembers(), and UpdateEPG().
RemoveOldEntries()
bool PVR::CPVREpgContainer::RemoveOldEntries () private
Remove old EPG entries.
Returns
True if the old entries were removed successfully, false otherwise.
References CDateTime::GetAsTime(), CDateTime::GetAsUTCDateTime(), CDateTime::GetCurrentDateTime(), GetPastDaysToDisplay(), CDateTime::GetUTCDateTime(), m_critSection, m_epgIdToEpgMap, and m_iLastEpgCleanup.
Referenced by Process().
SetHasPendingUpdates()
void PVR::CPVREpgContainer::SetHasPendingUpdates (bool bHasPendingUpdates = true)
Notify EPG container that there are pending manual EPG updates.
Parameters
bHasPendingUpdates The new value
References m_critSection, and m_pendingUpdates.
Referenced by Notify().
Start()
void PVR::CPVREpgContainer::Start ()
Start the EPG update thread.
References BELOW_NORMAL, CThread::Create(), m_bIsInitialising, m_bStarted, m_critSection, CThread::SetPriority(), and Stop().
Stop()
void PVR::CPVREpgContainer::Stop ()
Stop the EPG update thread.
References m_bStarted, m_critSection, and CThread::StopThread().
Referenced by Start(), and ~CPVREpgContainer().
Unload()
void PVR::CPVREpgContainer::Unload ()
unload all EPG data.
References m_bLoaded, m_bUpdateNotificationPending, m_channelUidToEpgMap, m_critSection, m_database, m_epgIdToEpgMap, m_epgTagChanges, m_epgTagChangesLock, m_iNextEpgActiveTagCheck, m_iNextEpgId, m_iNextEpgUpdate, m_updateRequests, and m_updateRequestsLock.
Referenced by ~CPVREpgContainer().
UpdateEPG()
bool PVR::CPVREpgContainer::UpdateEPG (bool bOnlyPending = false) private
Load and update the EPG data.
Parameters
bOnlyPending Only check and update EPG tables with pending manual updates
Returns
True if the update has not been interrupted, false otherwise.
References end(), PVR::EpgContainer, g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetAsTime(), CDateTime::GetAsUTCDateTime(), CDateTime::GetCurrentDateTime(), GetEpgDatabase(), GetFutureDaysToDisplay(), PVR::CPVRSettings::GetIntValue(), GetPastDaysToDisplay(), CServiceBroker::GetSettingsComponent(), CDateTime::GetUTCDateTime(), InterruptUpdate(), m_bIsInitialising, m_bIsUpdating, m_critSection, m_epgIdToEpgMap, m_events, m_iNextEpgUpdate, m_pendingUpdates, m_settings, m_updateEvent, CEventSource< Event >::Publish(), QueueDeleteEpgs(), CEvent::Set(), CSettings::SETTING_EPG_EPGUPDATE, and CSettings::SETTING_EPG_PAST_DAYSTODISPLAY.
Referenced by Process().
UpdateFromClient()
void PVR::CPVREpgContainer::UpdateFromClient (const std::shared_ptr< CPVREpgInfoTag > & tag, EPG_EVENT_STATE eNewState)
A client announced an updated epg tag for a channel.
Parameters
tag The epg tag containing the updated data
eNewState The kind of change (CREATED, UPDATED, DELETED)
References m_epgTagChanges, and m_epgTagChangesLock.
Referenced by PVR::CPVRClient::cb_epg_event_state_change().
UpdateRequest()
void PVR::CPVREpgContainer::UpdateRequest (int iClientID, int iUniqueChannelID)
A client triggered an epg update request for a channel.
Parameters
iClientID The id of the client which triggered the update request
iUniqueChannelID The uid of the channel for which the epg shall be updated
References m_updateRequests, and m_updateRequestsLock.
Referenced by PVR::CPVRClient::cb_trigger_epg_update().
UpdateSavedSearchLastExecuted()
bool PVR::CPVREpgContainer::UpdateSavedSearchLastExecuted (const CPVREpgSearchFilter & epgSearch)
Update time last executed for the given search.
Parameters
epgSearch The search.
Returns
True on success, false otherwise.
References GetEpgDatabase(), and LOGERROR.
Referenced by PVR::CGUIWindowPVRSearchBase::ExecuteSearch().
WaitForUpdateFinish()
void PVR::CPVREpgContainer::WaitForUpdateFinish () private
Wait for an EPG update to finish.
References m_bIsUpdating, m_bPreventUpdates, m_critSection, m_updateEvent, CEvent::Reset(), and CEvent::Wait().
Referenced by CreateChannelEpg().
Friends And Related Symbol Documentation
CPVREpgDatabase
friend class CPVREpgDatabase friend
Member Data Documentation
m_bIsInitialising
std::atomic<bool> PVR::CPVREpgContainer::m_bIsInitialising private
Initial value:
= {
        true}
true while the epg manager hasn't loaded all tables
Referenced by Process(), Start(), and UpdateEPG().
m_bIsUpdating
bool PVR::CPVREpgContainer::m_bIsUpdating = false private
true while an update is running
Referenced by UpdateEPG(), and WaitForUpdateFinish().
m_bLoaded
bool PVR::CPVREpgContainer::m_bLoaded = false private
true after epg data is initially loaded from the database
Referenced by LoadFromDatabase(), and Unload().
m_bPlaying
bool PVR::CPVREpgContainer::m_bPlaying = false private
true if Kodi is currently playing something
Referenced by InterruptUpdate(), OnPlaybackStarted(), and OnPlaybackStopped().
m_bPreventUpdates
bool PVR::CPVREpgContainer::m_bPreventUpdates = false private
true to prevent EPG updates
Referenced by CreateChannelEpg(), InterruptUpdate(), and WaitForUpdateFinish().
m_bStarted
bool PVR::CPVREpgContainer::m_bStarted = false private
true if EpgContainer has fully started
Referenced by IsStarted(), Start(), and Stop().
m_bSuspended
std::atomic<bool> PVR::CPVREpgContainer::m_bSuspended = {false} private
Referenced by OnSystemSleep(), OnSystemWake(), and Process().
m_bUpdateNotificationPending
bool PVR::CPVREpgContainer::m_bUpdateNotificationPending = false private
true while an epg updated notification to observers is pending.
Referenced by Notify(), Process(), and Unload().
m_channelUidToEpgMap
std::map<std::pair<int, int>, std::shared_ptr<CPVREpg> > PVR::CPVREpgContainer::m_channelUidToEpgMap private
the EPGs in this container. maps channel uids to epgs
Referenced by CreateChannelEpg(), GetByChannelUid(), QueueDeleteEpg(), and Unload().
m_critSection
CCriticalSection PVR::CPVREpgContainer::m_critSection mutable private
a critical section for changes to this container
Referenced by CheckPlayingEvents(), CleanupCachedImages(), CreateChannelEpg(), GetAllEpgs(), GetByChannelUid(), GetById(), GetEpgDatabase(), GetFirstAndLastEPGDate(), GetTagByDatabaseId(), GetTags(), InsertFromDB(), InterruptUpdate(), IsStarted(), LoadFromDatabase(), NextEpgId(), Notify(), OnPlaybackStarted(), OnPlaybackStopped(), PersistAll(), Process(), QueueDeleteEpg(), RemoveOldEntries(), SetHasPendingUpdates(), Start(), Stop(), Unload(), UpdateEPG(), and WaitForUpdateFinish().
m_database
std::shared_ptr<CPVREpgDatabase> PVR::CPVREpgContainer::m_database private
the EPG database
Referenced by GetEpgDatabase(), and Unload().
m_epgIdToEpgMap
std::map<int, std::shared_ptr<CPVREpg> > PVR::CPVREpgContainer::m_epgIdToEpgMap private
the EPGs in this container. maps epg ids to epgs
Referenced by CheckPlayingEvents(), CleanupCachedImages(), CreateChannelEpg(), GetAllEpgs(), GetById(), GetFirstAndLastEPGDate(), GetTagByDatabaseId(), GetTags(), InsertFromDB(), PersistAll(), QueueDeleteEpg(), RemoveOldEntries(), Unload(), and UpdateEPG().
m_epgTagChanges
std::list<CEpgTagStateChange> PVR::CPVREpgContainer::m_epgTagChanges private
list of updated epg tags announced by addon
Referenced by Process(), Unload(), and UpdateFromClient().
m_epgTagChangesLock
CCriticalSection PVR::CPVREpgContainer::m_epgTagChangesLock private
protect changed epg tags list
Referenced by Process(), Unload(), and UpdateFromClient().
m_events
CEventSource<PVREvent>& PVR::CPVREpgContainer::m_events private
Referenced by CheckPlayingEvents(), CreateChannelEpg(), DeleteSavedSearch(), Notify(), PersistSavedSearch(), Process(), and UpdateEPG().
m_iLastEpgCleanup
time_t PVR::CPVREpgContainer::m_iLastEpgCleanup = 0 private
the time the EPG was cleaned up
Referenced by Process(), and RemoveOldEntries().
m_iNextEpgActiveTagCheck
time_t PVR::CPVREpgContainer::m_iNextEpgActiveTagCheck = 0 private
the time the EPG will be checked for active tag updates
Referenced by CheckPlayingEvents(), and Unload().
m_iNextEpgId
int PVR::CPVREpgContainer::m_iNextEpgId = 0 private
the next epg ID that will be given to a new table when the db isn't being used
Referenced by LoadFromDatabase(), NextEpgId(), and Unload().
m_iNextEpgUpdate
time_t PVR::CPVREpgContainer::m_iNextEpgUpdate = 0 private
the time the EPG will be updated
Referenced by CreateChannelEpg(), Process(), Unload(), and UpdateEPG().
m_pendingUpdates
int PVR::CPVREpgContainer::m_pendingUpdates = 0 private
count of pending manual updates
Referenced by Process(), SetHasPendingUpdates(), and UpdateEPG().
m_settings
CPVRSettings PVR::CPVREpgContainer::m_settings private
Referenced by GetFutureDaysToDisplay(), GetPastDaysToDisplay(), InterruptUpdate(), and UpdateEPG().
m_updateEvent
CEvent PVR::CPVREpgContainer::m_updateEvent private
trigger when an update finishes
Referenced by UpdateEPG(), and WaitForUpdateFinish().
m_updateRequests
std::list<CEpgUpdateRequest> PVR::CPVREpgContainer::m_updateRequests private
list of update requests triggered by addon
Referenced by Process(), Unload(), and UpdateRequest().
m_updateRequestsLock
CCriticalSection PVR::CPVREpgContainer::m_updateRequestsLock private
protect update requests
Referenced by Process(), Unload(), and UpdateRequest().
The documentation for this class was generated from the following files:
EpgContainer.h
EpgContainer.cpp