Kodi Documentation: PVR::CPVRGUIProgressHandler Class Reference
PVR::CPVRGUIProgressHandler Class Reference
#include <PVRGUIProgressHandler.h>
Public Member Functions
CPVRGUIProgressHandler ()=delete
CPVRGUIProgressHandler (const std::string &strTitle)
Creates and asynchronously shows a progress dialog with the given title.
~CPVRGUIProgressHandler () override=default
void UpdateProgress (const std::string &strText, float fProgress)
Update the progress dialogs's content.
void UpdateProgress (const std::string &strText, unsigned int iCurrent, unsigned int iMax)
Update the progress dialogs's content.
Protected Member Functions
void Process () override
Private Attributes
CCriticalSection m_critSection
const std::string m_strTitle
std::string m_strText
float m_fProgress {0.0f}
bool m_bChanged {false}
bool m_bCreated {false}
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Constructor & Destructor Documentation
CPVRGUIProgressHandler() [1/2]
PVR::CPVRGUIProgressHandler::CPVRGUIProgressHandler () delete
CPVRGUIProgressHandler() [2/2]
PVR::CPVRGUIProgressHandler::CPVRGUIProgressHandler (const std::string & strTitle) explicit
Creates and asynchronously shows a progress dialog with the given title.
Parameters
strTitle The title for the progress dialog.
~CPVRGUIProgressHandler()
PVR::CPVRGUIProgressHandler::~CPVRGUIProgressHandler () override default
Member Function Documentation
Process()
void PVR::CPVRGUIProgressHandler::Process (void) override protected virtual
Reimplemented from CThread.
References CServiceBroker::GetGUI(), CGUIDialogExtendedProgressBar::GetHandle(), CGUIComponent::GetWindowManager(), m_bChanged, CThread::m_bStop, m_critSection, m_fProgress, m_strText, m_strTitle, CGUIDialogProgressBarHandle::MarkFinished(), CGUIDialogProgressBarHandle::SetPercentage(), CGUIDialogProgressBarHandle::SetText(), CThread::Sleep(), and WINDOW_DIALOG_EXT_PROGRESS.
UpdateProgress() [1/2]
void PVR::CPVRGUIProgressHandler::UpdateProgress (const std::string & strText, float fProgress)
Update the progress dialogs's content.
Parameters
strText The new progress text.
fProgress The new progress value, in a range from 0.0 to 100.0.
References CThread::Create(), m_bChanged, m_bCreated, m_critSection, m_fProgress, and m_strText.
Referenced by UpdateProgress().
UpdateProgress() [2/2]
void PVR::CPVRGUIProgressHandler::UpdateProgress (const std::string & strText, unsigned int iCurrent, unsigned int iMax)
Update the progress dialogs's content.
Parameters
strText The new progress text.
iCurrent The new current progress value, must be less or equal iMax.
iMax The new maximum progress value, must be greater or equal iCurrent.
References UpdateProgress().
Member Data Documentation
m_bChanged
bool PVR::CPVRGUIProgressHandler::m_bChanged {false} private
Referenced by Process(), and UpdateProgress().
m_bCreated
bool PVR::CPVRGUIProgressHandler::m_bCreated {false} private
Referenced by UpdateProgress().
m_critSection
CCriticalSection PVR::CPVRGUIProgressHandler::m_critSection private
Referenced by Process(), and UpdateProgress().
m_fProgress
float PVR::CPVRGUIProgressHandler::m_fProgress {0.0f} private
Referenced by Process(), and UpdateProgress().
m_strText
std::string PVR::CPVRGUIProgressHandler::m_strText private
Referenced by Process(), and UpdateProgress().
m_strTitle
const std::string PVR::CPVRGUIProgressHandler::m_strTitle private
Referenced by Process().
The documentation for this class was generated from the following files:
PVRGUIProgressHandler.h
PVRGUIProgressHandler.cpp