Kodi Documentation: PingResponseWaiter Class Reference
PingResponseWaiter Class Reference
Classes
class CHostProberJob
Public Member Functions
PingResponseWaiter (bool async, const CWakeOnAccess::WakeUpEntry &server)
~PingResponseWaiter () override
bool SuccessWaiting () const override
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
Public Member Functions inherited from WaitCondition
virtual ~WaitCondition ()=default
Static Public Member Functions
static bool Ping (const CWakeOnAccess::WakeUpEntry &server, unsigned timeOutMs=2000)
Private Attributes
const CWakeOnAccess::WakeUpEntry & m_server
unsigned int m_jobId = 0
bool m_hostOnline = false
Additional Inherited Members
Private Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Constructor & Destructor Documentation
PingResponseWaiter()
PingResponseWaiter::PingResponseWaiter (bool async, const CWakeOnAccess::WakeUpEntry & server) inline
References CServiceBroker::GetJobManager().
~PingResponseWaiter()
PingResponseWaiter::~PingResponseWaiter () inline override
References CServiceBroker::GetJobManager().
Member Function Documentation
OnJobComplete()
void PingResponseWaiter::OnJobComplete (unsigned int jobID, bool success, CJob * job) inline override virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
References success.
Ping()
static bool PingResponseWaiter::Ping (const CWakeOnAccess::WakeUpEntry & server, unsigned timeOutMs = 2000) inline static
References CServiceBroker::GetNetwork(), CWakeOnAccess::WakeUpEntry::host, HostToIP(), LookupUPnPHost(), CWakeOnAccess::WakeUpEntry::ping_mode, CWakeOnAccess::WakeUpEntry::ping_port, CNetworkBase::PingHost(), KODI::TIME::Sleep(), and CWakeOnAccess::WakeUpEntry::upnpUuid.
Referenced by PingResponseWaiter::CHostProberJob::DoWork(), and CWakeOnAccess::WakeUpHost().
SuccessWaiting()
bool PingResponseWaiter::SuccessWaiting () const inline override virtual
Reimplemented from WaitCondition.
Member Data Documentation
m_hostOnline
bool PingResponseWaiter::m_hostOnline = false private
m_jobId
unsigned int PingResponseWaiter::m_jobId = 0 private
m_server
const CWakeOnAccess::WakeUpEntry& PingResponseWaiter::m_server private
The documentation for this class was generated from the following file:
WakeOnAccess.cpp