Kodi Documentation: KODI::WINDOWING::GBM::CDRMUtils Class Reference
KODI::WINDOWING::GBM::CDRMUtils Class Reference
#include <DRMUtils.h>
Public Member Functions
CDRMUtils ()=default
virtual ~CDRMUtils ()
virtual void FlipPage (struct gbm_bo *bo, bool rendered, bool videoLayer, bool async)
virtual bool SetVideoMode (const RESOLUTION_INFO &res, struct gbm_bo *bo)
virtual bool SetActive (bool active)
virtual bool InitDrm ()
virtual void DestroyDrm ()
int GetFileDescriptor () const
int GetRenderNodeFileDescriptor () const
const char * GetRenderDevicePath () const
CDRMPlane * GetVideoPlane () const
CDRMPlane * GetGuiPlane () const
CDRMCrtc * GetCrtc () const
CDRMConnector * GetConnector () const
std::vector< std::string > GetConnectedConnectorNames ()
virtual RESOLUTION_INFO GetCurrentMode ()
virtual std::vector< RESOLUTION_INFO > GetModes ()
virtual bool SetMode (const RESOLUTION_INFO &res)
void SetInFenceFd (int fd)
int TakeOutFenceFd ()
Static Public Member Functions
static uint32_t FourCCWithAlpha (uint32_t fourcc)
static uint32_t FourCCWithoutAlpha (uint32_t fourcc)
Protected Member Functions
bool OpenDrm (bool needConnector)
drm_fb * DrmFbGetFromBo (struct gbm_bo *bo)
Protected Attributes
int m_fd
CDRMConnector * m_connector {nullptr}
CDRMEncoder * m_encoder {nullptr}
CDRMCrtc * m_crtc {nullptr}
CDRMCrtc * m_orig_crtc {nullptr}
CDRMPlane * m_video_plane {nullptr}
CDRMPlane * m_gui_plane {nullptr}
drmModeModeInfo * m_mode = nullptr
int m_width = 0
int m_height = 0
int m_inFenceFd {-1}
int m_outFenceFd {-1}
std::vector< std::unique_ptr< CDRMPlane > > m_planes
Private Member Functions
bool FindConnector ()
bool FindEncoder ()
bool FindCrtc ()
bool FindPlanes ()
bool FindPreferredMode ()
bool RestoreOriginalMode ()
RESOLUTION_INFO GetResolutionInfo (drmModeModeInfoPtr mode)
void PrintDrmDeviceInfo (drmDevicePtr device)
Private Attributes
int m_renderFd
const char * m_renderDevicePath {nullptr}
std::vector< std::unique_ptr< CDRMConnector > > m_connectors
std::vector< std::unique_ptr< CDRMEncoder > > m_encoders
std::vector< std::unique_ptr< CDRMCrtc > > m_crtcs
Constructor & Destructor Documentation
CDRMUtils()
KODI::WINDOWING::GBM::CDRMUtils::CDRMUtils () default
~CDRMUtils()
CDRMUtils::~CDRMUtils () virtual
References DestroyDrm().
Member Function Documentation
DestroyDrm()
void CDRMUtils::DestroyDrm () virtual
Reimplemented in KODI::WINDOWING::GBM::CDRMAtomic, and KODI::WINDOWING::GBM::COffScreenModeSetting.
References m_connector, m_crtc, m_encoder, m_fd, m_gui_plane, m_orig_crtc, m_renderFd, m_video_plane, and RestoreOriginalMode().
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::DestroyDrm(), and ~CDRMUtils().
DrmFbGetFromBo()
drm_fb * CDRMUtils::DrmFbGetFromBo (struct gbm_bo * bo) protected
References KODI::WINDOWING::GBM::drm_fb::bo, KODI::WINDOWING::GBM::drm_fb::fb_id, KODI::WINDOWING::GBM::drm_fb::format, KODI::WINDOWING::GBM::CDRMPlane::GetFormat(), CLog::Log(), LOGDEBUG, m_fd, m_gui_plane, and DRMHELPERS::ModifierToString().
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::FlipPage(), KODI::WINDOWING::GBM::CDRMLegacy::QueueFlip(), and KODI::WINDOWING::GBM::CDRMLegacy::SetVideoMode().
FindConnector()
bool CDRMUtils::FindConnector () private
References CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, LOGINFO, m_connector, m_connectors, and CSettings::SETTING_VIDEOSCREEN_MONITOR.
Referenced by InitDrm(), and OpenDrm().
FindCrtc()
bool CDRMUtils::FindCrtc () private
References KODI::WINDOWING::GBM::CDRMEncoder::GetCrtcId(), KODI::WINDOWING::GBM::CDRMCrtc::GetMode(), KODI::WINDOWING::GBM::CDRMCrtc::GetModeValid(), KODI::WINDOWING::GBM::CDRMEncoder::GetPossibleCrtcs(), CLog::Log(), LOGDEBUG, m_crtcs, m_encoder, m_mode, and m_orig_crtc.
Referenced by InitDrm().
FindEncoder()
bool CDRMUtils::FindEncoder () private
References KODI::WINDOWING::GBM::CDRMConnector::GetConnectorId(), CLog::Log(), LOGDEBUG, LOGINFO, m_connector, m_encoder, and m_encoders.
Referenced by InitDrm().
FindPlanes()
bool CDRMUtils::FindPlanes () private
References KODI::WINDOWING::GBM::CDRMEncoder::GetPossibleCrtcs(), m_crtcs, m_encoder, and m_planes.
Referenced by InitDrm().
FindPreferredMode()
bool CDRMUtils::FindPreferredMode () private
References KODI::WINDOWING::GBM::CDRMConnector::GetModeForIndex(), KODI::WINDOWING::GBM::CDRMConnector::GetModesCount(), CLog::Log(), LOGDEBUG, m_connector, and m_mode.
Referenced by InitDrm().
FlipPage()
virtual void KODI::WINDOWING::GBM::CDRMUtils::FlipPage (struct gbm_bo * bo, bool rendered, bool videoLayer, bool async) inline virtual
Reimplemented in KODI::WINDOWING::GBM::CDRMAtomic, KODI::WINDOWING::GBM::CDRMLegacy, and KODI::WINDOWING::GBM::COffScreenModeSetting.
FourCCWithAlpha()
uint32_t CDRMUtils::FourCCWithAlpha (uint32_t fourcc) static
Referenced by CRendererDRMPRIME::Create(), KODI::WINDOWING::GBM::CDRMAtomic::FlipPage(), and KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL().
FourCCWithoutAlpha()
uint32_t CDRMUtils::FourCCWithoutAlpha (uint32_t fourcc) static
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::FlipPage(), and KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL().
GetConnectedConnectorNames()
std::vector< std::string > CDRMUtils::GetConnectedConnectorNames ()
References m_connectors.
GetConnector()
CDRMConnector * KODI::WINDOWING::GBM::CDRMUtils::GetConnector () const inline
References m_connector.
GetCrtc()
CDRMCrtc * KODI::WINDOWING::GBM::CDRMUtils::GetCrtc () const inline
References m_crtc.
GetCurrentMode()
RESOLUTION_INFO CDRMUtils::GetCurrentMode () virtual
Reimplemented in KODI::WINDOWING::GBM::COffScreenModeSetting.
References GetResolutionInfo(), and m_mode.
GetFileDescriptor()
int KODI::WINDOWING::GBM::CDRMUtils::GetFileDescriptor () const inline
References m_fd.
GetGuiPlane()
CDRMPlane * KODI::WINDOWING::GBM::CDRMUtils::GetGuiPlane () const inline
References m_gui_plane.
GetModes()
std::vector< RESOLUTION_INFO > CDRMUtils::GetModes () virtual
Reimplemented in KODI::WINDOWING::GBM::COffScreenModeSetting.
References KODI::WINDOWING::GBM::CDRMConnector::GetModeForIndex(), KODI::WINDOWING::GBM::CDRMConnector::GetModesCount(), GetResolutionInfo(), m_connector, and RESOLUTION_INFO::strId.
GetRenderDevicePath()
const char * KODI::WINDOWING::GBM::CDRMUtils::GetRenderDevicePath () const inline
References m_renderDevicePath.
GetRenderNodeFileDescriptor()
int KODI::WINDOWING::GBM::CDRMUtils::GetRenderNodeFileDescriptor () const inline
References m_renderFd.
GetResolutionInfo()
RESOLUTION_INFO CDRMUtils::GetResolutionInfo (drmModeModeInfoPtr mode) private
References RESOLUTION_INFO::bFullScreen, D3DPRESENTFLAG_INTERLACED, D3DPRESENTFLAG_MODE3DSBS, D3DPRESENTFLAG_MODE3DTB, D3DPRESENTFLAG_PROGRESSIVE, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fPixelRatio, RESOLUTION_INFO::fRefreshRate, CServiceBroker::GetSettingsComponent(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, and RESOLUTION_INFO::strMode.
Referenced by GetCurrentMode(), and GetModes().
GetVideoPlane()
CDRMPlane * KODI::WINDOWING::GBM::CDRMUtils::GetVideoPlane () const inline
References m_video_plane.
InitDrm()
bool CDRMUtils::InitDrm () virtual
Reimplemented in KODI::WINDOWING::GBM::CDRMAtomic, KODI::WINDOWING::GBM::CDRMLegacy, and KODI::WINDOWING::GBM::COffScreenModeSetting.
References FindConnector(), FindCrtc(), FindEncoder(), FindPlanes(), FindPreferredMode(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_connectors, m_crtcs, m_encoders, m_fd, and m_planes.
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::InitDrm(), and KODI::WINDOWING::GBM::CDRMLegacy::InitDrm().
OpenDrm()
bool CDRMUtils::OpenDrm (bool needConnector) protected
References FindConnector(), CLog::Log(), LOGDEBUG, LOGERROR, m_connectors, m_fd, m_renderDevicePath, m_renderFd, and PrintDrmDeviceInfo().
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::InitDrm(), KODI::WINDOWING::GBM::CDRMLegacy::InitDrm(), and KODI::WINDOWING::GBM::COffScreenModeSetting::InitDrm().
PrintDrmDeviceInfo()
void CDRMUtils::PrintDrmDeviceInfo (drmDevicePtr device) private
References CLog::Log(), and LOGDEBUG.
Referenced by OpenDrm().
RestoreOriginalMode()
bool CDRMUtils::RestoreOriginalMode () private
References KODI::WINDOWING::GBM::CDRMCrtc::GetBufferId(), KODI::WINDOWING::GBM::CDRMConnector::GetConnectorId(), KODI::WINDOWING::GBM::CDRMCrtc::GetCrtcId(), KODI::WINDOWING::GBM::CDRMCrtc::GetMode(), KODI::WINDOWING::GBM::CDRMCrtc::GetX(), KODI::WINDOWING::GBM::CDRMCrtc::GetY(), CLog::Log(), LOGDEBUG, LOGERROR, m_connector, m_fd, and m_orig_crtc.
Referenced by DestroyDrm().
SetActive()
virtual bool KODI::WINDOWING::GBM::CDRMUtils::SetActive (bool active) inline virtual
Reimplemented in KODI::WINDOWING::GBM::CDRMAtomic, KODI::WINDOWING::GBM::CDRMLegacy, and KODI::WINDOWING::GBM::COffScreenModeSetting.
SetInFenceFd()
void KODI::WINDOWING::GBM::CDRMUtils::SetInFenceFd (int fd) inline
References m_inFenceFd.
SetMode()
bool CDRMUtils::SetMode (const RESOLUTION_INFO & res) virtual
Reimplemented in KODI::WINDOWING::GBM::COffScreenModeSetting.
References KODI::WINDOWING::GBM::CDRMConnector::CheckConnector(), KODI::WINDOWING::GBM::CDRMConnector::GetModeForIndex(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, CLog::Log(), LOGDEBUG, m_connector, m_height, m_mode, m_width, and RESOLUTION_INFO::strId.
SetVideoMode()
virtual bool KODI::WINDOWING::GBM::CDRMUtils::SetVideoMode (const RESOLUTION_INFO & res, struct gbm_bo * bo) inline virtual
Reimplemented in KODI::WINDOWING::GBM::CDRMAtomic, KODI::WINDOWING::GBM::CDRMLegacy, and KODI::WINDOWING::GBM::COffScreenModeSetting.
TakeOutFenceFd()
int KODI::WINDOWING::GBM::CDRMUtils::TakeOutFenceFd () inline
References m_outFenceFd.
Member Data Documentation
m_connector
CDRMConnector* KODI::WINDOWING::GBM::CDRMUtils::m_connector {nullptr} protected
Referenced by DestroyDrm(), KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), FindConnector(), FindEncoder(), FindPreferredMode(), GetConnector(), GetModes(), RestoreOriginalMode(), KODI::WINDOWING::GBM::CDRMLegacy::SetActive(), SetMode(), and KODI::WINDOWING::GBM::CDRMLegacy::SetVideoMode().
m_connectors
std::vector<std::unique_ptr<CDRMConnector> > KODI::WINDOWING::GBM::CDRMUtils::m_connectors private
Referenced by FindConnector(), GetConnectedConnectorNames(), InitDrm(), and OpenDrm().
m_crtc
CDRMCrtc* KODI::WINDOWING::GBM::CDRMUtils::m_crtc {nullptr} protected
Referenced by DestroyDrm(), KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), GetCrtc(), KODI::WINDOWING::GBM::CDRMLegacy::QueueFlip(), and KODI::WINDOWING::GBM::CDRMLegacy::SetVideoMode().
m_crtcs
std::vector<std::unique_ptr<CDRMCrtc> > KODI::WINDOWING::GBM::CDRMUtils::m_crtcs private
Referenced by FindCrtc(), FindPlanes(), and InitDrm().
m_encoder
CDRMEncoder* KODI::WINDOWING::GBM::CDRMUtils::m_encoder {nullptr} protected
Referenced by DestroyDrm(), FindCrtc(), FindEncoder(), and FindPlanes().
m_encoders
std::vector<std::unique_ptr<CDRMEncoder> > KODI::WINDOWING::GBM::CDRMUtils::m_encoders private
Referenced by FindEncoder(), and InitDrm().
m_fd
int KODI::WINDOWING::GBM::CDRMUtils::m_fd protected
Referenced by DestroyDrm(), KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), DrmFbGetFromBo(), GetFileDescriptor(), InitDrm(), KODI::WINDOWING::GBM::CDRMAtomic::InitDrm(), OpenDrm(), KODI::WINDOWING::GBM::CDRMLegacy::QueueFlip(), RestoreOriginalMode(), KODI::WINDOWING::GBM::CDRMLegacy::SetVideoMode(), and KODI::WINDOWING::GBM::CDRMLegacy::WaitingForFlip().
m_gui_plane
CDRMPlane* KODI::WINDOWING::GBM::CDRMUtils::m_gui_plane {nullptr} protected
Referenced by DestroyDrm(), KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), DrmFbGetFromBo(), KODI::WINDOWING::GBM::CDRMAtomic::FlipPage(), GetGuiPlane(), and KODI::WINDOWING::GBM::CDRMAtomic::SetScalingFilter().
m_height
int KODI::WINDOWING::GBM::CDRMUtils::m_height = 0 protected
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), SetMode(), and KODI::WINDOWING::GBM::CDRMAtomic::SetScalingFilter().
m_inFenceFd
int KODI::WINDOWING::GBM::CDRMUtils::m_inFenceFd {-1} protected
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), and SetInFenceFd().
m_mode
drmModeModeInfo* KODI::WINDOWING::GBM::CDRMUtils::m_mode = nullptr protected
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), FindCrtc(), FindPreferredMode(), GetCurrentMode(), SetMode(), KODI::WINDOWING::GBM::CDRMAtomic::SetScalingFilter(), and KODI::WINDOWING::GBM::CDRMLegacy::SetVideoMode().
m_orig_crtc
CDRMCrtc* KODI::WINDOWING::GBM::CDRMUtils::m_orig_crtc {nullptr} protected
Referenced by DestroyDrm(), KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), FindCrtc(), and RestoreOriginalMode().
m_outFenceFd
int KODI::WINDOWING::GBM::CDRMUtils::m_outFenceFd {-1} protected
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), and TakeOutFenceFd().
m_planes
std::vector<std::unique_ptr<CDRMPlane> > KODI::WINDOWING::GBM::CDRMUtils::m_planes protected
Referenced by FindPlanes(), InitDrm(), and KODI::WINDOWING::GBM::CDRMAtomic::InitDrm().
m_renderDevicePath
const char* KODI::WINDOWING::GBM::CDRMUtils::m_renderDevicePath {nullptr} private
Referenced by GetRenderDevicePath(), and OpenDrm().
m_renderFd
int KODI::WINDOWING::GBM::CDRMUtils::m_renderFd private
Referenced by DestroyDrm(), GetRenderNodeFileDescriptor(), and OpenDrm().
m_video_plane
CDRMPlane* KODI::WINDOWING::GBM::CDRMUtils::m_video_plane {nullptr} protected
Referenced by DestroyDrm(), and GetVideoPlane().
m_width
int KODI::WINDOWING::GBM::CDRMUtils::m_width = 0 protected
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), SetMode(), and KODI::WINDOWING::GBM::CDRMAtomic::SetScalingFilter().
The documentation for this class was generated from the following files:
DRMUtils.h
DRMUtils.cpp