Kodi Documentation: VDPAU::CVDPAUContext Class Reference
VDPAU::CVDPAUContext Class Reference
#include <VDPAU.h>
Public Member Functions
void Release ()
VDPAU_procs & GetProcs ()
VdpDevice GetDevice ()
bool Supports (VdpVideoMixerFeature feature)
VdpVideoMixerFeature * GetFeatures ()
int GetFeatureCount ()
Static Public Member Functions
static bool EnsureContext (CVDPAUContext **ctx)
Private Member Functions
CVDPAUContext ()
void Close ()
bool LoadSymbols ()
bool CreateContext ()
void DestroyContext ()
void QueryProcs ()
void SpewHardwareAvailable ()
Private Attributes
int m_refCount
VdpVideoMixerFeature m_vdpFeatures [14]
int m_featureCount
VdpDevice m_vdpDevice
VDPAU_procs m_vdpProcs
VdpStatus(* dl_vdp_device_create_x11)(Display *display, int screen, VdpDevice *device, VdpGetProcAddress **get_proc_address)
Static Private Attributes
static CVDPAUContext * m_context = 0
static CCriticalSection m_section
static Display * m_display = 0
static void * m_dlHandle = 0
Constructor & Destructor Documentation
CVDPAUContext()
CVDPAUContext::CVDPAUContext () private
References m_context, and m_refCount.
Referenced by EnsureContext().
Member Function Documentation
Close()
void CVDPAUContext::Close () private
References DestroyContext(), CLog::Log(), and LOGINFO.
Referenced by Release().
CreateContext()
bool CVDPAUContext::CreateContext () private
References dl_vdp_device_create_x11, CServiceBroker::GetWinSystem(), CLog::Log(), LOGERROR, LOGINFO, m_display, m_vdpDevice, m_vdpProcs, QueryProcs(), SpewHardwareAvailable(), and VDPAU::VDPAU_procs::vdp_get_proc_address.
Referenced by EnsureContext().
DestroyContext()
void CVDPAUContext::DestroyContext () private
References m_vdpDevice, m_vdpProcs, and VDPAU::VDPAU_procs::vdp_device_destroy.
Referenced by Close().
EnsureContext()
bool CVDPAUContext::EnsureContext (CVDPAUContext ** ctx) static
References CreateContext(), CVDPAUContext(), CServiceBroker::GetWinSystem(), LoadSymbols(), m_context, m_refCount, and m_section.
Referenced by VDPAU::CDecoder::Check(), VDPAU::CDecoder::Open(), and VDPAU::CDecoder::Register().
GetDevice()
VdpDevice CVDPAUContext::GetDevice ()
References m_vdpDevice.
Referenced by VDPAU::CDecoder::ConfigVDPAU(), VDPAU::CMixer::CreateVdpauMixer(), VDPAU::COutput::EnsureBufferPool(), VDPAU::CDecoder::FFGetBuffer(), VDPAU::CDecoder::Open(), and VDPAU::COutput::ProcessMixerPicture().
GetFeatureCount()
int CVDPAUContext::GetFeatureCount ()
References m_featureCount.
Referenced by VDPAU::CMixer::CreateVdpauMixer().
GetFeatures()
VdpVideoMixerFeature * CVDPAUContext::GetFeatures ()
References m_vdpFeatures.
Referenced by VDPAU::CMixer::CreateVdpauMixer().
GetProcs()
VDPAU_procs & CVDPAUContext::GetProcs ()
References m_vdpProcs.
Referenced by VDPAU::CMixer::CheckStatus(), VDPAU::COutput::CheckStatus(), VDPAU::CDecoder::CheckStatus(), VDPAU::CDecoder::ConfigVDPAU(), VDPAU::CMixer::CreateVdpauMixer(), VDPAU::CMixer::DisableHQScaling(), VDPAU::COutput::EnsureBufferPool(), VDPAU::CDecoder::FFGetBuffer(), VDPAU::CDecoder::FiniVDPAUOutput(), VDPAU::CDecoder::Open(), VDPAU::CMixer::PostProcOff(), VDPAU::COutput::PreCleanup(), VDPAU::COutput::ProcessMixerPicture(), VDPAU::CMixer::ProcessPicture(), VDPAU::CDecoder::Release(), VDPAU::COutput::ReleaseBufferPool(), VDPAU::CDecoder::Render(), VDPAU::CMixer::SetColor(), VDPAU::CMixer::SetDeinterlacing(), VDPAU::CMixer::SetDeintSkipChroma(), VDPAU::CMixer::SetHWUpscaling(), VDPAU::CMixer::SetNoiseReduction(), VDPAU::CMixer::SetSharpness(), and VDPAU::CMixer::Uninit().
LoadSymbols()
bool CVDPAUContext::LoadSymbols () private
References dl_vdp_device_create_x11, CLog::Log(), LOGERROR, m_dlHandle, m_vdpDevice, and void().
Referenced by EnsureContext().
QueryProcs()
void CVDPAUContext::QueryProcs () private
References m_vdpProcs, VDPAU::VDPAU_procs::vdp_decoder_create, VDPAU::VDPAU_procs::vdp_decoder_destroy, VDPAU::VDPAU_procs::vdp_decoder_query_caps, VDPAU::VDPAU_procs::vdp_decoder_render, VDPAU::VDPAU_procs::vdp_device_destroy, VDPAU::VDPAU_procs::vdp_generate_csc_matrix, VDPAU::VDPAU_procs::vdp_get_error_string, VDPAU::VDPAU_procs::vdp_output_surface_create, VDPAU::VDPAU_procs::vdp_output_surface_destroy, VDPAU::VDPAU_procs::vdp_output_surface_get_bits_native, VDPAU::VDPAU_procs::vdp_output_surface_put_bits_indexed, VDPAU::VDPAU_procs::vdp_output_surface_put_bits_native, VDPAU::VDPAU_procs::vdp_output_surface_put_bits_y_cb_cr, VDPAU::VDPAU_procs::vdp_output_surface_render_output_surface, VDP_PROC, VDPAU::VDPAU_procs::vdp_video_mixer_create, VDPAU::VDPAU_procs::vdp_video_mixer_destroy, VDPAU::VDPAU_procs::vdp_video_mixer_query_feature_support, VDPAU::VDPAU_procs::vdp_video_mixer_query_parameter_support, VDPAU::VDPAU_procs::vdp_video_mixer_render, VDPAU::VDPAU_procs::vdp_video_mixer_set_attribute_values, VDPAU::VDPAU_procs::vdp_video_mixer_set_feature_enables, VDPAU::VDPAU_procs::vdp_video_surface_create, VDPAU::VDPAU_procs::vdp_video_surface_destroy, VDPAU::VDPAU_procs::vdp_video_surface_get_bits_y_cb_cr, and VDPAU::VDPAU_procs::vdp_video_surface_put_bits_y_cb_cr.
Referenced by CreateContext().
Release()
void CVDPAUContext::Release ()
References Close(), m_context, m_refCount, and m_section.
Referenced by VDPAU::CDecoder::Check(), VDPAU::CDecoder::Close(), VDPAU::CDecoder::OnLostDisplay(), and VDPAU::CDecoder::Register().
SpewHardwareAvailable()
void CVDPAUContext::SpewHardwareAvailable () private
References CHECK_SUPPORT, decoder_profiles, CLog::Log(), LOGINFO, m_featureCount, m_vdpDevice, m_vdpProcs, and VDPAU::VDPAU_procs::vdp_decoder_query_caps.
Referenced by CreateContext().
Supports()
bool CVDPAUContext::Supports (VdpVideoMixerFeature feature)
References m_featureCount, and m_vdpFeatures.
Referenced by VDPAU::CDecoder::Supports().
Member Data Documentation
dl_vdp_device_create_x11
VdpStatus(* VDPAU::CVDPAUContext::dl_vdp_device_create_x11) (Display *display, int screen, VdpDevice *device, VdpGetProcAddress **get_proc_address) private
Referenced by CreateContext(), and LoadSymbols().
m_context
CVDPAUContext * CVDPAUContext::m_context = 0 static private
Referenced by CVDPAUContext(), EnsureContext(), and Release().
m_display
Display * CVDPAUContext::m_display = 0 static private
Referenced by CreateContext().
m_dlHandle
void * CVDPAUContext::m_dlHandle = 0 static private
Referenced by LoadSymbols().
m_featureCount
int VDPAU::CVDPAUContext::m_featureCount private
Referenced by GetFeatureCount(), SpewHardwareAvailable(), and Supports().
m_refCount
int VDPAU::CVDPAUContext::m_refCount private
Referenced by CVDPAUContext(), EnsureContext(), and Release().
m_section
CCriticalSection CVDPAUContext::m_section static private
Referenced by EnsureContext(), and Release().
m_vdpDevice
VdpDevice VDPAU::CVDPAUContext::m_vdpDevice private
Referenced by CreateContext(), DestroyContext(), GetDevice(), LoadSymbols(), and SpewHardwareAvailable().
m_vdpFeatures
VdpVideoMixerFeature VDPAU::CVDPAUContext::m_vdpFeatures[14] private
Referenced by GetFeatures(), and Supports().
m_vdpProcs
VDPAU_procs VDPAU::CVDPAUContext::m_vdpProcs private
Referenced by CreateContext(), DestroyContext(), GetProcs(), QueryProcs(), and SpewHardwareAvailable().
The documentation for this class was generated from the following files:
VDPAU.h
VDPAU.cpp