Kodi Documentation: AddonToKodiFuncTable_kodi_gui_dialogProgress Struct Reference
AddonToKodiFuncTable_kodi_gui_dialogProgress Struct Reference
#include <progress.h>
Public Attributes
KODI_GUI_HANDLE(* new_dialog)(KODI_HANDLE kodiBase)
void(* delete_dialog)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
void(* open)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
void(* set_heading)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char *heading)
void(* set_line)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, unsigned int lineNo, const char *line)
void(* set_can_cancel)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, bool canCancel)
bool(* is_canceled)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
void(* set_percentage)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int percentage)
int(* get_percentage)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
void(* show_progress_bar)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, bool pnOff)
void(* set_progress_max)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int max)
void(* set_progress_advance)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int nSteps)
bool(* abort)(KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Member Data Documentation
abort
bool(* AddonToKodiFuncTable_kodi_gui_dialogProgress::abort) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
delete_dialog
void(* AddonToKodiFuncTable_kodi_gui_dialogProgress::delete_dialog) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
get_percentage
int(* AddonToKodiFuncTable_kodi_gui_dialogProgress::get_percentage) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
is_canceled
bool(* AddonToKodiFuncTable_kodi_gui_dialogProgress::is_canceled) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
new_dialog
KODI_GUI_HANDLE(* AddonToKodiFuncTable_kodi_gui_dialogProgress::new_dialog) (KODI_HANDLE kodiBase)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
open
void(* AddonToKodiFuncTable_kodi_gui_dialogProgress::open) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
set_can_cancel
void(* AddonToKodiFuncTable_kodi_gui_dialogProgress::set_can_cancel) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, bool canCancel)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
set_heading
void(* AddonToKodiFuncTable_kodi_gui_dialogProgress::set_heading) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, const char *heading)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
set_line
void(* AddonToKodiFuncTable_kodi_gui_dialogProgress::set_line) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, unsigned int lineNo, const char *line)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
set_percentage
void(* AddonToKodiFuncTable_kodi_gui_dialogProgress::set_percentage) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int percentage)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
set_progress_advance
void(* AddonToKodiFuncTable_kodi_gui_dialogProgress::set_progress_advance) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int nSteps)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
set_progress_max
void(* AddonToKodiFuncTable_kodi_gui_dialogProgress::set_progress_max) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, int max)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
show_progress_bar
void(* AddonToKodiFuncTable_kodi_gui_dialogProgress::show_progress_bar) (KODI_HANDLE kodiBase, KODI_GUI_HANDLE handle, bool pnOff)
Referenced by ADDON::Interface_GUIDialogProgress::Init().
The documentation for this struct was generated from the following file:
kodi-dev-kit/include/kodi/c-api/gui/dialogs/progress.h