Kodi Documentation: class DriverPrimitive
class DriverPrimitive
C++ » Interface - kodi::addon » Addon type instances » Peripheral » Definitions, structures and enumerators » 4. Joystick
Base class for joystick driver primitives
Classes
struct kodi::addon::DriverPrimitive
Functions
kodi::addon::DriverPrimitive::DriverPrimitive (void)=default
Construct an invalid driver primitive.
static DriverPrimitive kodi::addon::DriverPrimitive::CreateButton (unsigned int buttonIndex)
Construct a driver primitive representing a joystick button.
kodi::addon::DriverPrimitive::DriverPrimitive (unsigned int hatIndex, JOYSTICK_DRIVER_HAT_DIRECTION direction)
Construct a driver primitive representing one of the four direction arrows on a dpad.
kodi::addon::DriverPrimitive::DriverPrimitive (unsigned int axisIndex, int center, JOYSTICK_DRIVER_SEMIAXIS_DIRECTION direction, unsigned int range)
Construct a driver primitive representing the positive or negative half of an axis.
static DriverPrimitive kodi::addon::DriverPrimitive::CreateMotor (unsigned int motorIndex)
Construct a driver primitive representing a motor.
kodi::addon::DriverPrimitive::DriverPrimitive (std::string keycode)
Construct a driver primitive representing a key on a keyboard.
static DriverPrimitive kodi::addon::DriverPrimitive::CreateMouseButton (JOYSTICK_DRIVER_MOUSE_INDEX buttonIndex)
Construct a driver primitive representing a mouse button.
kodi::addon::DriverPrimitive::DriverPrimitive (JOYSTICK_DRIVER_RELPOINTER_DIRECTION direction)
Construct a driver primitive representing one of the four direction in which a relative pointer can move.
JOYSTICK_DRIVER_PRIMITIVE_TYPE kodi::addon::DriverPrimitive::Type (void) const
Get type of primitive.
unsigned int kodi::addon::DriverPrimitive::DriverIndex (void) const
Get driver index.
JOYSTICK_DRIVER_HAT_DIRECTION kodi::addon::DriverPrimitive::HatDirection (void) const
Get hat direction.
int kodi::addon::DriverPrimitive::Center (void) const
Get center.
JOYSTICK_DRIVER_SEMIAXIS_DIRECTION kodi::addon::DriverPrimitive::SemiAxisDirection (void) const
Get semi axis direction.
unsigned int kodi::addon::DriverPrimitive::Range (void) const
Get range.
const std::string & kodi::addon::DriverPrimitive::Keycode (void) const
Get key code as string.
JOYSTICK_DRIVER_MOUSE_INDEX kodi::addon::DriverPrimitive::MouseIndex (void) const
Get mouse index.
JOYSTICK_DRIVER_RELPOINTER_DIRECTION kodi::addon::DriverPrimitive::RelPointerDirection (void) const
Get relative pointer direction.
bool kodi::addon::DriverPrimitive::operator== (const DriverPrimitive &other) const
Compare this with another class of this type.
Detailed Description
Base class for joystick driver primitives
A driver primitive can be:
a button
a hat direction
a semiaxis (either the positive or negative half of an axis)
a motor
a keyboard key
a mouse button
a relative pointer direction
The type determines the fields in use:
Button:
driver index
Hat direction:
driver index
hat direction
Semiaxis:
driver index
center
semiaxis direction
range
Motor:
driver index
Key:
key code
Mouse button:
driver index
Relative pointer direction:
relative pointer direction
Function Documentation
Center()
int kodi::addon::DriverPrimitive::Center (void) const inline
Get center.
Returns
Center
References kodi::addon::DriverPrimitive::m_center.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::Opposite(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
CreateButton()
static DriverPrimitive kodi::addon::DriverPrimitive::CreateButton (unsigned int buttonIndex) inline static
Construct a driver primitive representing a joystick button.
Parameters
[in] buttonIndex Index
Returns
Created class
References kodi::addon::DriverPrimitive::DriverPrimitive(), and JOYSTICK_DRIVER_PRIMITIVE_TYPE_BUTTON.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
CreateMotor()
static DriverPrimitive kodi::addon::DriverPrimitive::CreateMotor (unsigned int motorIndex) inline static
Construct a driver primitive representing a motor.
Parameters
[in] motorIndex Motor index number
Returns
Constructed driver primitive representing a motor
References kodi::addon::DriverPrimitive::DriverPrimitive(), and JOYSTICK_DRIVER_PRIMITIVE_TYPE_MOTOR.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
CreateMouseButton()
static DriverPrimitive kodi::addon::DriverPrimitive::CreateMouseButton (JOYSTICK_DRIVER_MOUSE_INDEX buttonIndex) inline static
Construct a driver primitive representing a mouse button.
Parameters
[in] buttonIndex Index
Returns
Constructed driver primitive representing a mouse button
References kodi::addon::DriverPrimitive::DriverPrimitive(), and JOYSTICK_DRIVER_PRIMITIVE_TYPE_MOUSE_BUTTON.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
DriverIndex()
unsigned int kodi::addon::DriverPrimitive::DriverIndex (void) const inline
Get driver index.
Returns
Index number
References kodi::addon::DriverPrimitive::m_driverIndex.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::Opposite(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
DriverPrimitive() [1/5]
kodi::addon::DriverPrimitive::DriverPrimitive (JOYSTICK_DRIVER_RELPOINTER_DIRECTION direction) inline
Construct a driver primitive representing one of the four direction in which a relative pointer can move.
Parameters
[in] direction With JOYSTICK_DRIVER_RELPOINTER_DIRECTION defined direction
DriverPrimitive() [2/5]
kodi::addon::DriverPrimitive::DriverPrimitive (std::string keycode) inline
Construct a driver primitive representing a key on a keyboard.
Parameters
[in] keycode Keycode to use
DriverPrimitive() [3/5]
kodi::addon::DriverPrimitive::DriverPrimitive (unsigned int axisIndex, int center, JOYSTICK_DRIVER_SEMIAXIS_DIRECTION direction, unsigned int range) inline
Construct a driver primitive representing the positive or negative half of an axis.
Parameters
[in] axisIndex Axis index
[in] center Center
[in] direction With JOYSTICK_DRIVER_HAT_DIRECTION defined direction
[in] range Range
DriverPrimitive() [4/5]
kodi::addon::DriverPrimitive::DriverPrimitive (unsigned int hatIndex, JOYSTICK_DRIVER_HAT_DIRECTION direction) inline
Construct a driver primitive representing one of the four direction arrows on a dpad.
Parameters
[in] hatIndex Hat index
[in] direction With JOYSTICK_DRIVER_HAT_DIRECTION defined direction
DriverPrimitive() [5/5]
kodi::addon::DriverPrimitive::DriverPrimitive (void) default
Construct an invalid driver primitive.
Referenced by kodi::addon::DriverPrimitive::CreateButton(), kodi::addon::DriverPrimitive::CreateMotor(), and kodi::addon::DriverPrimitive::CreateMouseButton().
HatDirection()
JOYSTICK_DRIVER_HAT_DIRECTION kodi::addon::DriverPrimitive::HatDirection (void) const inline
Get hat direction.
Returns
The with JOYSTICK_DRIVER_HAT_DIRECTION defined direction
References kodi::addon::DriverPrimitive::m_hatDirection.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
Keycode()
const std::string & kodi::addon::DriverPrimitive::Keycode (void) const inline
Get key code as string.
Returns
Key code
References kodi::addon::DriverPrimitive::m_keycode.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
MouseIndex()
JOYSTICK_DRIVER_MOUSE_INDEX kodi::addon::DriverPrimitive::MouseIndex (void) const inline
Get mouse index.
Returns
With JOYSTICK_DRIVER_MOUSE_INDEX defined mouse index
References kodi::addon::DriverPrimitive::m_driverIndex.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
operator==()
bool kodi::addon::DriverPrimitive::operator== (const DriverPrimitive & other) const inline
Compare this with another class of this type.
Parameters
[in] other Other class to compare
Returns
True if they are equal, false otherwise
References JOYSTICK_DRIVER_PRIMITIVE_TYPE_BUTTON, JOYSTICK_DRIVER_PRIMITIVE_TYPE_HAT_DIRECTION, JOYSTICK_DRIVER_PRIMITIVE_TYPE_KEY, JOYSTICK_DRIVER_PRIMITIVE_TYPE_MOTOR, JOYSTICK_DRIVER_PRIMITIVE_TYPE_MOUSE_BUTTON, JOYSTICK_DRIVER_PRIMITIVE_TYPE_RELPOINTER_DIRECTION, JOYSTICK_DRIVER_PRIMITIVE_TYPE_SEMIAXIS, kodi::addon::DriverPrimitive::m_center, kodi::addon::DriverPrimitive::m_driverIndex, kodi::addon::DriverPrimitive::m_hatDirection, kodi::addon::DriverPrimitive::m_keycode, kodi::addon::DriverPrimitive::m_range, kodi::addon::DriverPrimitive::m_relPointerDirection, kodi::addon::DriverPrimitive::m_semiAxisDirection, and kodi::addon::DriverPrimitive::m_type.
Range()
unsigned int kodi::addon::DriverPrimitive::Range (void) const inline
Get range.
Returns
Range
References kodi::addon::DriverPrimitive::m_range.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::Opposite(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
RelPointerDirection()
JOYSTICK_DRIVER_RELPOINTER_DIRECTION kodi::addon::DriverPrimitive::RelPointerDirection (void) const inline
Get relative pointer direction.
Returns
With JOYSTICK_DRIVER_RELPOINTER_DIRECTION defined direction
References kodi::addon::DriverPrimitive::m_relPointerDirection.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
SemiAxisDirection()
JOYSTICK_DRIVER_SEMIAXIS_DIRECTION kodi::addon::DriverPrimitive::SemiAxisDirection (void) const inline
Get semi axis direction.
Returns
With JOYSTICK_DRIVER_SEMIAXIS_DIRECTION defined direction
References kodi::addon::DriverPrimitive::m_semiAxisDirection.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::Opposite(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
Type()
JOYSTICK_DRIVER_PRIMITIVE_TYPE kodi::addon::DriverPrimitive::Type (void) const inline
Get type of primitive.
Returns
The with JOYSTICK_DRIVER_PRIMITIVE_TYPE defined type
References kodi::addon::DriverPrimitive::m_type.
Referenced by PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().