Kodi Documentation: CGUIFontTTFGL Class Reference
CGUIFontTTFGL Class Reference
#include <GUIFontTTFGL.h>
Public Member Functions
CGUIFontTTFGL (const std::string &fontIdent)
~CGUIFontTTFGL (void) override
bool FirstBegin () override
void LastEnd () override
CVertexBuffer CreateVertexBuffer (const std::vector< SVertex > &vertices) const override
void DestroyVertexBuffer (CVertexBuffer &bufferHandle) const override
Public Member Functions inherited from CGUIFontTTF
virtual ~CGUIFontTTF ()
void Clear ()
bool Load (const std::string &strFilename, float height=20.0f, float aspect=1.0f, float lineSpacing=1.0f, bool border=false)
void Begin ()
void End ()
const std::string & GetFontIdent () const
Static Public Member Functions
static void CreateStaticVertexBuffers (void)
static void DestroyStaticVertexBuffers (void)
Static Public Member Functions inherited from CGUIFontTTF
static CGUIFontTTF * CreateGUIFontTTF (const std::string &fontIdent)
Protected Member Functions
std::unique_ptr< CTexture > ReallocTexture (unsigned int &newHeight) override
bool CopyCharToTexture (FT_BitmapGlyph bitGlyph, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2) override
void DeleteHardwareTexture () override
Protected Member Functions inherited from CGUIFontTTF
CGUIFontTTF (const std::string &fontIdent)
void AddReference ()
void RemoveReference ()
std::vector< Glyph > GetHarfBuzzShapedGlyphs (const vecText &text)
float GetTextWidthInternal (const vecText &text)
float GetTextWidthInternal (const vecText &text, const std::vector< Glyph > &glyph)
float GetCharWidthInternal (character_t ch)
float GetTextHeight (float lineSpacing, int numLines) const
float GetTextBaseLine () const
float GetLineHeight (float lineSpacing) const
float GetFontHeight () const
void DrawTextInternal (CGraphicContext &context, float x, float y, const std::vector< KODI::UTILS::COLOR::Color > &colors, const vecText &text, uint32_t alignment, float maxPixelWidth, bool scrolling, float dx=0.0f, float dy=0.0f)
Character * GetCharacter (character_t letter, FT_UInt glyphIndex)
bool CacheCharacter (FT_UInt glyphIndex, uint32_t style, Character *ch)
void RenderCharacter (CGraphicContext &context, float posX, float posY, const Character *ch, KODI::UTILS::COLOR::Color color, bool roundX, std::vector< SVertex > &vertices)
void ClearCharacterCache ()
void SetGlyphStrength (FT_GlyphSlot slot, int glyphStrength)
unsigned int GetTextureLineHeight () const
the height of each line in the texture. Accounts for spacing between lines to avoid characters overlapping.
unsigned int GetMaxFontHeight () const
Static Protected Attributes
static GLuint m_elementArrayHandle {0}
Private Types
enum TextureStatus { TEXTURE_VOID = 0 , TEXTURE_READY , TEXTURE_REALLOCATED , TEXTURE_UPDATED }
Private Attributes
unsigned int m_updateY1 {0}
unsigned int m_updateY2 {0}
TextureStatus m_textureStatus {TEXTURE_VOID}
bool m_scissorClip {false}
Static Private Attributes
static bool m_staticVertexBufferCreated {false}
Additional Inherited Members
Static Protected Member Functions inherited from CGUIFontTTF
static void ObliqueGlyph (FT_GlyphSlot slot)
Protected Attributes inherited from CGUIFontTTF
float m_height {0.0f}
std::unique_ptr< CTexture > m_texture
unsigned int m_textureWidth {0}
unsigned int m_textureHeight {0}
int m_posX {0}
int m_posY {0}
KODI::UTILS::COLOR::Color m_color {KODI::UTILS::COLOR::NONE}
std::vector< Character > m_char
Character * m_charquick [LOOKUPTABLE_SIZE] {nullptr}
bool m_ellipseCached {false}
float m_ellipsesWidth {0.0f}
unsigned int m_cellBaseLine {0}
unsigned int m_cellHeight {0}
unsigned int m_maxFontHeight {0}
unsigned int m_nestedBeginCount {0}
FT_Face m_face {nullptr}
FT_Stroker m_stroker {nullptr}
hb_font_t * m_hbFont {nullptr}
float m_originX {0.0f}
float m_originY {0.0f}
unsigned int m_nTexture {0}
std::vector< CTranslatedVertices > m_vertexTrans
std::vector< SVertex > m_vertex
float m_textureScaleX {0.0f}
float m_textureScaleY {0.0f}
const std::string m_fontIdent
std::vector< uint8_t > m_fontFileInMemory
CGUIFontCache< CGUIFontCacheStaticPosition, CGUIFontCacheStaticValue > m_staticCache
CGUIFontCache< CGUIFontCacheDynamicPosition, CGUIFontCacheDynamicValue > m_dynamicCache
CRenderSystemBase * m_renderSystem
Member Enumeration Documentation
TextureStatus
enum CGUIFontTTFGL::TextureStatus private
Enumerator
TEXTURE_VOID
TEXTURE_READY
TEXTURE_REALLOCATED
TEXTURE_UPDATED
Constructor & Destructor Documentation
CGUIFontTTFGL()
CGUIFontTTFGL::CGUIFontTTFGL (const std::string & fontIdent) explicit
~CGUIFontTTFGL()
CGUIFontTTFGL::~CGUIFontTTFGL (void) override
References DeleteHardwareTexture(), and CGUIFontTTF::m_dynamicCache.
Member Function Documentation
CopyCharToTexture()
bool CGUIFontTTFGL::CopyCharToTexture (FT_BitmapGlyph bitGlyph, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2) override protected virtual
Implements CGUIFontTTF.
References CGUIFontTTF::m_texture, m_textureStatus, m_updateY1, m_updateY2, TEXTURE_READY, TEXTURE_REALLOCATED, TEXTURE_UPDATED, and TEXTURE_VOID.
CreateStaticVertexBuffers()
void CGUIFontTTFGL::CreateStaticVertexBuffers (void) static
References index(), m_elementArrayHandle, and m_staticVertexBufferCreated.
Referenced by LastEnd().
CreateVertexBuffer()
CVertexBuffer CGUIFontTTFGL::CreateVertexBuffer (const std::vector< SVertex > & vertices) const override virtual
Reimplemented from CGUIFontTTF.
DeleteHardwareTexture()
void CGUIFontTTFGL::DeleteHardwareTexture () override protected virtual
Implements CGUIFontTTF.
References CServiceBroker::GetGUI(), CGUIComponent::GetTextureManager(), CGUIFontTTF::m_nTexture, m_textureStatus, m_updateY1, m_updateY2, CGUITextureManager::ReleaseHwTexture(), and TEXTURE_VOID.
Referenced by ~CGUIFontTTFGL().
DestroyStaticVertexBuffers()
void CGUIFontTTFGL::DestroyStaticVertexBuffers (void) static
References m_elementArrayHandle, and m_staticVertexBufferCreated.
Referenced by GUIFontManager::Clear().
DestroyVertexBuffer()
void CGUIFontTTFGL::DestroyVertexBuffer (CVertexBuffer & bufferHandle) const override virtual
Reimplemented from CGUIFontTTF.
FirstBegin()
bool CGUIFontTTFGL::FirstBegin () override virtual
Implements CGUIFontTTF.
References CRenderSystemGL::EnableShader(), CServiceBroker::GetGUI(), CServiceBroker::GetRenderSystem(), CRenderSystemBase::GetRenderVersion(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetTextureManager(), CGUIFontTTF::m_nTexture, m_scissorClip, CGUIFontTTF::m_texture, m_textureStatus, m_updateY1, m_updateY2, CGUITextureManager::ReleaseHwTexture(), CRenderSystemGL::ResetScissors(), CRenderSystemGL::ScissorsCanEffectClipping(), SM_FONTS, SM_FONTS_SHADER_CLIP, TEXTURE_READY, TEXTURE_REALLOCATED, TEXTURE_UPDATED, TEXTURE_VOID, and VerifyGLState.
LastEnd()
void CGUIFontTTFGL::LastEnd () override virtual
Implements CGUIFontTTF.
References CRenderSystemGL::ClipRectToScissorRect(), CreateStaticVertexBuffers(), CRenderSystemGL::DisableShader(), CMatrixGLStack::Get(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIMatrix(), CGraphicContext::GetGUIScaleX(), CGraphicContext::GetGUIScaleY(), CServiceBroker::GetRenderSystem(), CGraphicContext::GetScissors(), CGraphicContext::GetTransformDepth(), CServiceBroker::GetWinSystem(), glMatrixModview, glMatrixProject, CRectGen< T >::Intersect(), CRectGen< T >::IsEmpty(), m_elementArrayHandle, m_scissorClip, CGUIFontTTF::m_textureHeight, CGUIFontTTF::m_textureWidth, CGUIFontTTF::m_vertex, CGUIFontTTF::m_vertexTrans, CMatrixGL::MultMatrixf(), CRenderSystemGL::ResetScissors(), CMatrixGL::Scalef(), CGraphicContext::ScaleFinalXCoord(), CGraphicContext::ScaleFinalYCoord(), CRenderSystemGL::SetScissors(), CRenderSystemGL::ShaderGetClip(), CRenderSystemGL::ShaderGetCol(), CRenderSystemGL::ShaderGetCoord0(), CRenderSystemGL::ShaderGetCoordStep(), CRenderSystemGL::ShaderGetDepth(), CRenderSystemGL::ShaderGetMatrix(), CRenderSystemGL::ShaderGetPos(), CGraphicContext::StereoCorrection(), and CMatrixGL::Translatef().
ReallocTexture()
std::unique_ptr< CTexture > CGUIFontTTFGL::ReallocTexture (unsigned int & newHeight) override protected virtual
Implements CGUIFontTTF.
References CTexture::CreateTexture(), CGUIFontCache< Position, Value >::Flush(), CLog::Log(), LOGERROR, LOGWARNING, CGUIFontTTF::m_dynamicCache, CGUIFontTTF::m_height, CGUIFontTTF::m_staticCache, CGUIFontTTF::m_texture, CGUIFontTTF::m_textureHeight, CGUIFontTTF::m_textureScaleX, CGUIFontTTF::m_textureScaleY, m_textureStatus, CGUIFontTTF::m_textureWidth, m_updateY1, m_updateY2, CTextureBase::PadPow2(), TEXTURE_REALLOCATED, and XB_FMT_A8.
Member Data Documentation
m_elementArrayHandle
GLuint CGUIFontTTFGL::m_elementArrayHandle {0} static protected
Referenced by CreateStaticVertexBuffers(), DestroyStaticVertexBuffers(), and LastEnd().
m_scissorClip
bool CGUIFontTTFGL::m_scissorClip {false} private
Referenced by FirstBegin(), and LastEnd().
m_staticVertexBufferCreated
bool CGUIFontTTFGL::m_staticVertexBufferCreated {false} static private
Referenced by CreateStaticVertexBuffers(), and DestroyStaticVertexBuffers().
m_textureStatus
TextureStatus CGUIFontTTFGL::m_textureStatus {TEXTURE_VOID} private
Referenced by CopyCharToTexture(), DeleteHardwareTexture(), FirstBegin(), and ReallocTexture().
m_updateY1
unsigned int CGUIFontTTFGL::m_updateY1 {0} private
Referenced by CopyCharToTexture(), DeleteHardwareTexture(), FirstBegin(), and ReallocTexture().
m_updateY2
unsigned int CGUIFontTTFGL::m_updateY2 {0} private
Referenced by CopyCharToTexture(), DeleteHardwareTexture(), FirstBegin(), and ReallocTexture().
The documentation for this class was generated from the following files:
GUIFontTTFGL.h
GUIFontTTFGL.cpp