Kodi Documentation: TestXBMCTinyXML2.cpp File Reference
TestXBMCTinyXML2.cpp File Reference
#include "filesystem/File.h"
#include "test/TestUtils.h"
#include "utils/StringUtils.h"
#include "utils/XBMCTinyXML2.h"
#include <gtest/gtest.h>
Classes
class TestXBMCTinyXML2
Functions
TEST (TestXBMCTinyXML2, ParseFromString)
TEST (TestXBMCTinyXML2, ParseFromChar)
TEST (TestXBMCTinyXML2, ParseFromCharFail)
TEST (TestXBMCTinyXML2, ParseFromFileHandle)
std::string data ("<details><url function=\"ParseTMDBRating\" " "cache=\"tmdb-en-12244.json\">" "http://api.themoviedb.org/3/movie/12244" "?api_key=57983e31fb435df4df77afb854740ea9" "&language=en&#x3f;&#x003F;&#0063;</url></details>")
outputdoc Parse (data)
EXPECT_TRUE (outputdoc.SaveFile(xmlfile))
file Close ()
ASSERT_NE (nullptr, f)
inputdoc LoadFile (f)
fclose (f)
XBMC_DELETETEMPFILE (file)
if (root &&(strcmp(root->Value(), "details")==0))
EXPECT_TRUE (retval)
Variables
CXBMCTinyXML2 outputdoc
XFILE::CFile * file = XBMC_CREATETEMPFILE(".xml")
std::string xmlfile = XBMC_TEMPFILEPATH(file)
CXBMCTinyXML2 inputdoc
FILE * f = fopen(xmlfile.c_str(), "r")
auto * root = inputdoc.RootElement()
Function Documentation
ASSERT_NE()
ASSERT_NE (nullptr , f)
Referenced by TestHTTPDirectory::CheckFileItemSizes(), TestWebServer::CheckRangesTestFileResponse(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Close()
file Close ()
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonOk(), kodi::addon::CInstanceInputStream::ADDON_Close(), kodi::addon::CInstanceVFS::ADDON_Close(), CGUIWindow::AfterRender(), CGUIWindowSlideShow::Announce(), CGUIDialogKeyboardGeneric::Cancel(), ADDON::Interface_Filesystem::close_file(), CGUIDialogVideoManager::CloseAll(), KODI::GAME::CGUIAgentWindow::CloseDialog(), KODI::GAME::CGUIPortWindow::CloseDialog(), anonymous_namespace{GUIBuiltins.cpp}::CloseDialog(), PVR::CGUIDialogPVRItemsViewBase::ContextMenu(), ADDON::Interface_GUIDialogProgress::delete_dialog(), CGUIDialogKaiToast::FrameMove(), CGUIDialogSeekBar::FrameMove(), CGUIDialogVideoBookmarks::GotoBookmark(), PVR::CGUIDialogPVRChannelsOSD::GotoChannel(), CWebSocket::Handle(), kodi::gui::CWindow::OnAction(), CGUIDialogAddonInfo::OnAction(), CGUIDialogContextMenu::OnAction(), CGUIDialogGamepad::OnAction(), CGUIDialogPlayerProcessInfo::OnAction(), CGUIDialogSlider::OnAction(), CGUIDialogMusicInfo::OnAction(), CGUIDialogMusicOSD::OnAction(), CGUIDialogSongInfo::OnAction(), CGUIDialogPictureInfo::OnAction(), CGUIWindowSlideShow::OnAction(), CGUIDialogFullScreenInfo::OnAction(), CGUIDialogVideoInfo::OnAction(), CGUIDialogVideoOSD::OnAction(), CGUIDialogMusicInfo::OnAlbumInfo(), CGUIDialogMusicInfo::OnArtistInfo(), CGUIDialog::OnBack(), CGUIDialogMediaSource::OnCancel(), CGUIDialogNumeric::OnCancel(), CGUIDialogSmartPlaylistEditor::OnCancel(), CGUIDialogSmartPlaylistRule::OnCancel(), CGUIDialogNetworkSetup::OnCancel(), CGUIDialogFileBrowser::OnClick(), KODI::GAME::CDialogGameStretchMode::OnClickAction(), KODI::GAME::CDialogGameVideoFilter::OnClickAction(), KODI::GAME::CDialogGameVideoRotation::OnClickAction(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonAddTimer(), PVR::CGUIDialogPVRChannelManager::OnClickButtonCancel(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonFind(), PVR::CGUIDialogPVRRecordingInfo::OnClickButtonFind(), PVR::CGUIDialogPVRChannelManager::OnClickButtonOK(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonOK(), PVR::CGUIDialogPVRRecordingInfo::OnClickButtonOK(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonPlay(), PVR::CGUIDialogPVRRecordingInfo::OnClickButtonPlay(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonRecord(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonSetReminder(), CGUIDialogSubtitles::OnDownloadComplete(), PVR::CGUIDialogPVRGuideInfo::OnInfo(), PVR::CGUIDialogPVRRecordingInfo::OnInfo(), PVR::CGUIDialogPVRChannelGuide::OnInitWindow(), PVR::CGUIDialogPVRChannelsOSD::OnInitWindow(), CGUIDialogTeletext::OnInitWindow(), CGUIDialogAddonInfo::OnInstall(), CGUIDialogButtonMenu::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIDialogContextMenu::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIDialogOK::OnMessage(), CGUIDialogPlayEject::OnMessage(), CGUIDialogSelect::OnMessage(), CGUIDialogSubMenu::OnMessage(), CGUIDialogYesNo::OnMessage(), KODI::GAME::CGUIControllerWindow::OnMessage(), KODI::GAME::CDialogGameSaves::OnMessage(), PVR::CGUIDialogPVRGuideSearch::OnMessage(), PVR::CGUIDialogPVRRadioRDSInfo::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIDialogSubtitleSettings::OnMessage(), CGUIDialogTeletext::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIDialogVideoOSD::OnMessage(), CGUIDialogKeyboardGeneric::OnOK(), CGUIDialogMediaSource::OnOK(), CGUIDialogNumeric::OnOK(), CGUIDialogSmartPlaylistEditor::OnOK(), CGUIDialogSmartPlaylistRule::OnOK(), CGUIDialogNetworkSetup::OnOK(), CGUIDialogLibExportSettings::OnOK(), CGUIDialogMusicInfo::OnPlayItem(), CGUIDialogSongInfo::OnPlaySong(), CGUIDialogVideoInfo::OnSearchItemFound(), CGUIDialogAddonInfo::OnSelect(), KODI::GAME::CDialogGameSaves::OnSelect(), CGUIDialogColorPicker::OnSelect(), CGUIDialogSelect::OnSelect(), CGUIDialogAddonInfo::OnSelectVersion(), CGUIDialogSubtitleSettings::OnSettingAction(), CGUIDialogAddonInfo::OnUninstall(), CGUIDialogAddonInfo::OnUpdate(), kodi::addon::CInstanceGame::CStream::Open(), CGUIDialog::Open_Internal(), kodi::vfs::CFile::OpenFile(), kodi::vfs::CFile::OpenFileForWrite(), CGUIDialogVideoInfo::Play(), CGUIDialogVideoInfo::PlayTrailer(), CGUIDialogKeyboardTouch::Process(), CGUIDialogTeletext::Render(), CGUIDialogAddonInfo::ShowDependencyList(), CGUIDialogExtendedProgressBar::UpdateState(), CGUIDialog::UpdateVisibility(), CGUIWindowDebugInfo::UpdateVisibility(), CGUIWindowPointer::UpdateVisibility(), CGUIWindowScreensaver::UpdateVisibility(), CGUIWindowScreensaverDim::UpdateVisibility(), CCoreAudioStream::~CCoreAudioStream(), kodi::vfs::CFile::~CFile(), and kodi::addon::CInstanceGame::CStream::~CStream().
data()
std::string data ()
Referenced by PVR::CPVRRadioRDSInfoTag::Info::Add(), CGUIDialogSettingsManualBase::AddButton(), ActiveAE::CActiveAEStream::AddData(), kodi::audioengine::CAEStream::AddData(), CDVDDemuxSPU::AddData(), CAEStreamParser::AddData(), CSettingsManager::AddDynamicCondition(), CSettingConditionsManager::AddDynamicCondition(), KODI::RETRO::CRPRenderManager::AddFrame(), kodi::addon::CInstanceGame::ADDON_Deserialize(), kodi::addon::CInstanceGame::ADDON_GetMemory(), kodi::addon::CInstanceGame::ADDON_Serialize(), CAESinkDirectSound::AddPackets(), CAESinkALSA::AddPackets(), CAESinkAUDIOTRACK::AddPackets(), CAESinkDARWINIOS::AddPackets(), CAESinkDARWINOSX::AddPackets(), CAESinkDARWINTVOS::AddPackets(), CAESinkOSS::AddPackets(), CAESinkPULSE::AddPackets(), CAESinkSNDIO::AddPackets(), CAESinkStarfish::AddPackets(), CAESinkWASAPI::AddPackets(), CAESinkXAudio::AddPackets(), AE::SINK::CAESinkPipewire::AddPackets(), IHTTPRequestHandler::AddPostData(), KODI::RETRO::CSavestateDatabase::AddSavestate(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), ADDON::Interface_AudioEngine::aestream_add_data(), CPartyModeManager::Announce(), KODI::GAME::CDialogGameVolume::Announce(), CGUIPlayerAnnouncementHandler::Announce(), CGUISourcesAnnouncementHandler::Announce(), CDirectoryProvider::Announce(), XBPython::Announce(), CAirPlayServer::Announce(), JSONRPC::CTCPServer::Announce(), UPNP::CUPnPRenderer::Announce(), UPNP::CUPnPServer::Announce(), CGUIWindowSlideShow::Announce(), CAnnounceReceiver::Announce(), CWinEventsWin10::Announce(), CGUIWindowHome::Announce(), ANNOUNCEMENT::CAnnouncementManager::Announce(), ANNOUNCEMENT::CAnnouncementManager::Announce(), ANNOUNCEMENT::CAnnouncementManager::Announce(), ANNOUNCEMENT::CAnnouncementManager::Announce(), ANNOUNCEMENT::CAnnouncementManager::Announce(), ANNOUNCEMENT::CAnnouncementManager::Announce(), ANNOUNCEMENT::CAnnouncementManager::Announce(), KODI::PLAYLIST::CPlayList::AnnounceAdd(), AnnounceBridge(), KODI::PLAYLIST::CPlayList::AnnounceClear(), JSONRPC::IJSONRPCAnnouncer::AnnouncementToJSONRPC(), CGUIWindowSlideShow::AnnouncePlaylistAdd(), CGUIWindowSlideShow::AnnouncePlaylistClear(), CGUIWindowSlideShow::AnnouncePropertyChanged(), KODI::PLAYLIST::CPlayListPlayer::AnnouncePropertyChanged(), AnnounceRemove(), CVideoDatabase::AnnounceRemove(), KODI::PLAYLIST::CPlayList::AnnounceRemove(), CVideoDatabase::AnnounceUpdate(), AnnounceUpdate(), XBMCAddon::xbmcwsgi::WsgiResponse::Append(), CPackerMAT::AppendData(), CHTTPJsonRpcHandler::appendPostData(), CHTTPPythonHandler::appendPostData(), CVideoInfoTag::Archive(), arrayFromVariantArray(), CAESinkXAudio::BuildXAudio2Buffer(), KODI::UTILITY::CDigest::Calculate(), KODI::UTILITY::CDigest::Calculate(), KODI::CDRIP::CEncoderAddon::cb_write(), CBitstream::CBitstream(), cc_decode_EIA608(), CControlState::CControlState(), CDVDMsgSubtitleClutChange::CDVDMsgSubtitleClutChange(), EVENTPACKET::CEventPacket::CEventPacket(), CFMutableDictionarySetData(), PVR::CGUIDialogPVRTimerSettings::ChannelsFiller(), DXVA::CDecoder::Check(), TestWebServer::CheckRangesTestFileResponse(), CWebVTTHandler::CheckSignature(), anonymous_namespace{NetworkLinux.cpp}::IcmpPacket::Checksum(), CIrssMessage::CIrssMessage(), CIrssMessage::CIrssMessage(), CAEUtil::ClampArray(), CWebSocketV8::close(), OVERLAY::convert_quad(), KODI::RETRO::CRPRenderManager::CopyFrame(), Actor::CPayloadWrap< Payload >::CPayloadWrap(), Actor::CPayloadWrap< Payload >::CPayloadWrap(), PVR::CPVREpgInfoTag::CPVREpgInfoTag(), crc16_ccitt(), CD3DBuffer::Create(), create_response(), CConvolutionShader::CreateHQKernel(), CWebServer::CreateMemoryDownloadResponse(), PVR::CGUIDialogPVRTimerSettings::CustomIntSettingDefinitionsFiller(), PVR::CGUIDialogPVRTimerSettings::CustomStringSettingDefinitionsFiller(), CWebSocketFrame::CWebSocketFrame(), CWebSocketFrame::CWebSocketFrame(), PVR::CGUIDialogPVRTimerSettings::DaysFiller(), CDVDDemuxCC::Decode(), CDecoderCC708::Decode(), CDVDOverlayCodecCCText::Decode(), CDVDOverlayCodecSSA::Decode(), CDVDOverlayCodecText::Decode(), CDVDOverlayCodecTX3G::Decode(), COverlayCodecWebVTT::Decode(), decode_708(), CDVDSubtitlesLibass::DecodeDemuxPkt(), CDVDSubtitlesLibass::DecodeHeader(), CDVDRadioRDSData::DecodeRTC(), CDVDRadioRDSData::DecodeTA_TP(), KODI::GAME::CGameClient::Deserialize(), KODI::RETRO::CSavestateFlatBuffer::Deserialize(), CAEStreamParser::DetectType(), dictionaryFromVariantMap(), dll_findfirst(), dll_findfirst64i32(), dll_findnext(), dll_findnext64i32(), ANNOUNCEMENT::CAnnouncementManager::DoAnnounce(), ANNOUNCEMENT::CAnnouncementManager::DoAnnounce(), CFileOperationJob::DoProcessFile(), CSaveFileState::DoWork(), anonymous_namespace{DRMUtils.cpp}::DrmFbDestroyCallback(), PVR::CGUIDialogPVRTimerSettings::DupEpisodesFiller(), EmbeddedArt::EmbeddedArt(), PVR::CGUIDialogPVRTimerSettings::EndAnytimeSetCondition(), CFileOperationJob::CFileOperation::ExecuteOperation(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), CALSADeviceMonitor::FDEventCallback(), CALSAHControlMonitor::FDEventCallback(), FFmpegExtraData::FFmpegExtraData(), VAAPI::CDecoder::FFReleaseBuffer(), DXVA::CDecoder::FFReleaseBuffer(), VAAPI::CVAAPIContext::FFReleaseBuffer(), VDPAU::CDecoder::FFReleaseBuffer(), CPackerMAT::FillDataBuffer(), ActiveAE::CActiveAE::FreeSoundSample(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetArtistsByWhere(), KODI::WINDOWING::WAYLAND::CWindowDecorator::GetBuffer(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetChapters(), CGUIBaseContainer::GetCondition(), CGUIControlGroupList::GetCondition(), CGUIPanelContainer::GetCondition(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetContentRanges(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetCuts(), CDVDAudioCodecFFmpeg::GetData(), CAEEncoderFFmpeg::GetData(), CMusicDatabase::GetDiscsByWhere(), KODI::WINDOWING::GBM::CDRMConnector::GetEDID(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetEditList(), CVideoDatabase::GetEpisodesByWhere(), CXBMCApp::GetFilenameFromIntent(), CWebSocketV8::GetFrame(), CWebSocketV8::GetFrame(), CDVDVideoCodecAndroidMediaCodec::GetHDRStaticMetadata(), DRM::CMediaDrmCryptoSession::GetKeyRequest(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideosByWhere(), CLibInputKeyboard::GetRepeat(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetSceneMarkers(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsFullByWhere(), CGUIDialogMediaFilter::GetStringListOptions(), KODI::RETRO::CWinRenderBuffer::GetTexture(), CVideoDatabase::GetTvShowsByWhere(), anonymous_namespace{ZeroconfBrowserDarwin.cpp}::GetTxtRecords(), good_parity(), CWebSocketManager::Handle(), handle_708_C0(), handle_708_C1(), handle_708_C2(), handle_708_C3(), handle_708_DFx_DefineWindow(), handle_708_extended_char(), handle_708_G0(), handle_708_G1(), handle_708_SPA_SetPenAttributes(), handle_708_SPC_SetPenColor(), handle_708_SPL_SetPenLocation(), handle_708_SWA_SetWindowAttributes(), CWebServer::HandlePostField(), CDVDDemuxCC::Handler(), CIRServerSuite::HandleRemoteEvent(), CWebSocketV13::Handshake(), CWebSocketV8::Handshake(), KODI::WINDOWING::X11::CWinSystemX11::HasWindowManager(), CGUIDialogMediaFilter::InitializeSettings(), ADDON::CAddon::InitSettings(), ActiveAE::CActiveAE::InitSink(), CGUIControlEditSetting::InputValidation(), MUSIC_INFO::TagLibVFSStream::insert(), CXBMCTinyXML::InternalParse(), ADDON::Interface_Filesystem::io_control_get_cache_status(), KODI::GAME::CGameSettings::IsAccountVerified(), CBitstreamConverter::isom_write_avcc(), anonymous_namespace{ApplicationSettingsHandling.cpp}::IsPlaying(), PVR::CGUIDialogPVRRecordingSettings::LifetimesFiller(), PVR::CGUIDialogPVRTimerSettings::LifetimesFiller(), KODI::RETRO::CCheevos::LoadData(), CXBMCTinyXML::LoadFile(), CXBMCTinyXML::LoadFile(), CXBMCTinyXML2::LoadFile(), CVideoTagLoaderFFmpeg::LoadMKV(), CLinuxRendererGL::LoadPlane(), CLinuxRendererGLES::LoadPlane(), ADDON::CAddon::LoadUserSettings(), KODI::RETRO::CRPRenderManager::LoadVideoFrameSync(), CWinShader::LockVertexBuffer(), KODI::GAME::CGameSettings::LoginToRA(), CD3DBuffer::Map(), PVR::CGUIDialogPVRTimerSettings::MarginTimeFiller(), PVR::CGUIDialogPVRTimerSettings::MaxRecordingsFiller(), KODI::WINDOWING::X11::CWinEventsX11::MessagePump(), CBitstreamConverter::mpeg2_sequence_header(), nal_bs_init(), JSONRPC::CJSONRPC::NotifyAll(), NotifyAll(), objectFromVariant(), Shaders::GL::ConvolutionFilterShader::OnCompiledAndLinked(), Shaders::GLES::ConvolutionFilterShader::OnCompiledAndLinked(), Shaders::GL::YUV2RGBFilterShader4::OnCompiledAndLinked(), Shaders::GLES::YUV2RGBFilterShader::OnCompiledAndLinked(), CFileOperationJob::CFileOperation::OnFileCallback(), CGUIDialogKeyboardGeneric::OnInitWindow(), CGUIDialogNumeric::OnInitWindow(), CApplication::OnMessage(), XBPython::OnNotification(), XBMCAddon::xbmc::Monitor::OnNotification(), UPNP::CUPnPServer::OnUpdateObject(), CDVDSubtitleParserSSA::Open(), CDVDDemuxVobsub::Open(), XBMCAddon::xbmcwsgi::WsgiResponseBody::operator()(), CAEBitstreamPacker::Pack(), CAEPackIEC61937::PackAC3(), CAEPackIEC61937::PackDTS(), CAEPackIEC61937::PackDTS_1024(), CAEPackIEC61937::PackDTS_2048(), CAEPackIEC61937::PackDTS_512(), CAEBitstreamPacker::PackDTSHD(), CAEPackIEC61937::PackDTSHD(), CAEBitstreamPacker::PackEAC3(), CAEPackIEC61937::PackEAC3(), CPackerMAT::PackTrueHD(), CAEPackIEC61937::PackTrueHD(), KODI::WINDOWING::GBM::CDRMLegacy::PageFlipHandler(), CJSONVariantParser::Parse(), CXBMCTinyXML::Parse(), CRssReader::Parse(), CXBMCTinyXML::Parse(), CJSONVariantParser::Parse(), CAEELDParser::Parse(), EVENTPACKET::CEventPacket::Parse(), CScraperUrl::ParseFromData(), CTagLoaderTagLib::ParseTag(), CWebSocketV8::Ping(), CAESinkStarfish::PlayerCallback(), CDVDVideoCodecStarfish::PlayerCallback(), CWebSocketV8::Pong(), PVR::CGUIDialogPVRTimerSettings::PrioritiesFiller(), process_service_block(), CVideoPlayerAudioID3::ProcessID3(), CLibInputKeyboard::ProcessKey(), CDVDRadioRDSData::ProcessUECP(), PAPlayer::QueueData(), XFILE::CXbtFile::Read(), CEdl::ReadEdl(), CIRServerSuite::ReadNext(), CCharArrayParser::ReadNextArray(), PVR::CGUIDialogPVRTimerSettings::RecordingGroupFiller(), DXVA::CDecoder::ReleaseBuffer(), CCharArrayParser::Reset(), ADDON::CAddon::SaveSettings(), JSONRPC::CTCPServer::CTCPClient::Send(), JSONRPC::CTCPServer::CWebSocketClient::Send(), CWebSocket::Send(), Actor::Protocol::SendInMessage(), Actor::Protocol::SendOutMessage(), Actor::Protocol::SendOutMessageSync(), CDVDRadioRDSData::SendTMCSignal(), KODI::RETRO::CSavestateFlatBuffer::Serialize(), KODI::GAME::CGameClient::Serialize(), EmbeddedArt::Set(), PVR::CPVREpg::SetChannelData(), PVR::CPVREpgInfoTag::SetChannelData(), PVR::CPVREpgTagsCache::SetChannelData(), PVR::CPVREpgTagsContainer::SetChannelData(), CHttpResponse::SetContent(), kodi::addon::AudioDecoderInfoTag::SetCoverArtByMem(), CSettingAction::SetData(), CHttpResponseRange::SetData(), CHttpResponseRange::SetData(), CHttpResponseRange::SetData(), CScraperUrl::SetData(), CIrssMessage::SetDataAsBytes(), CIrssMessage::SetDataAsString(), CGUIEditControl::SetInputValidation(), CSettingInt::SetOptionsFiller(), CSettingString::SetOptionsFiller(), CSettingInt::SetOptionsFillerName(), CSettingString::SetOptionsFillerName(), CVideoDatabase::SetPlayCount(), KODI::PLAYLIST::CPlayListPlayer::SetRepeat(), CGUIDialogTextViewer::ShowForFile(), PVR::CGUIDialogPVRTimerSettings::StartAnytimeSetCondition(), VDPAU::CMixer::StateMachine(), VDPAU::COutput::StateMachine(), ActiveAE::CActiveAESink::StateMachine(), VAAPI::COutput::StateMachine(), CAEStreamParser::SyncAC3(), CAEStreamParser::SyncDTS(), CAEStreamParser::SyncTrueHD(), CXBMCTinyXML::Test(), TEST(), TEST(), TEST(), ADDON::CAddonDll::TransferSettings(), CGUIInfoManager::TranslateSingleString(), CXBMCTinyXML::TryParse(), CAEStreamParser::TrySyncAC3(), PVR::CGUIDialogPVRTimerSettings::TypeReadOnlyCondition(), PVR::CGUIDialogPVRTimerSettings::TypesFiller(), PVR::CGUIDialogPVRTimerSettings::TypeSupportsCondition(), CFanart::Unpack(), KODI::UTILITY::CDigest::Update(), KODI::UTILITY::CDigest::Update(), PVR::CPVREpg::UpdateEntry(), KODI::PLAYLIST::CSmartPlaylistRule::Validate(), KODI::PLAYLIST::CSmartPlaylistRule::ValidateMyRating(), anonymous_namespace{WebVTTHandler.cpp}::ValidateSignature(), CApplicationVolumeHandling::VolumeChanged(), CApplicationPowerHandling::WakeUpScreenSaverAndDPMS(), PVR::CGUIDialogPVRTimerSettings::WeekdaysFiller(), KODI::CDRIP::CEncoderAddon::Write(), kodi::addon::CInstanceAudioEncoder::Write(), CAAudioUnitSink::write(), CAAudioUnitSink::write(), MUSIC_INFO::TagLibVFSStream::writeBlock(), and XBMCHelper::WriteFile().
EXPECT_TRUE() [1/2]
EXPECT_TRUE (outputdoc. SaveFilexmlfile)
Referenced by TEST(), TEST(), and TEST().
EXPECT_TRUE() [2/2]
EXPECT_TRUE (retval)
fclose()
fclose (f)
Referenced by CXBTFReader::Close(), anonymous_namespace{UDevProvider.cpp}::get_mountpoint(), CNetworkInterfaceLinux::GetCurrentDefaultGateway(), CAndroidStorageProvider::GetRemovableDrivesLinux(), CSMB::Init(), CNetworkLinux::queryInterfaceList(), TEST(), and TEST().
if()
if (root && strcmp(root->Value(), "details")==0)
References root.
Referenced by CGUIDialogAddonInfo::BuildDependencyList(), and KODI::GAME::CAgentInput::ProcessAgentControllers().
LoadFile()
inputdoc LoadFile (f)
Referenced by KODI::UTILS::FONT::GetFontFamily(), and KODI::UTILS::FONT::GetFontFamilyNames().
Parse()
outputdoc Parse (data)
TEST() [1/4]
TEST (TestXBMCTinyXML2 , ParseFromChar)
References EXPECT_TRUE(), CXBMCTinyXML2::LoadFile(), root, KODI::UTILS::StringUtils::Trim(), and XBMC_REF_FILE_PATH.
TEST() [2/4]
TEST (TestXBMCTinyXML2 , ParseFromCharFail)
References CXBMCTinyXML2::LoadFile(), and XBMC_REF_FILE_PATH.
TEST() [3/4]
TEST (TestXBMCTinyXML2 , ParseFromFileHandle)
References ASSERT_NE(), EXPECT_TRUE(), f, fclose(), CXBMCTinyXML2::LoadFile(), root, KODI::UTILS::StringUtils::Trim(), and XBMC_REF_FILE_PATH.
TEST() [4/4]
TEST (TestXBMCTinyXML2 , ParseFromString)
References data(), EXPECT_TRUE(), CXBMCTinyXML2::Parse(), and root.
XBMC_DELETETEMPFILE()
XBMC_DELETETEMPFILE (file)
Variable Documentation
f
FILE* f = fopen(xmlfile.c_str(), "r")
Referenced by PVR::CPVRManagerJobQueue::Append(), CAESinkSNDIO::AudioFormatToPar(), ccmem_tobuf(), CLinuxRendererGL::CreateNV12Texture(), CLinuxRendererGLES::CreateNV12Texture(), CXBMCTestUtils::CreateTempFile(), CRendererMediaCodec::CreateTexture(), CLinuxRendererGL::CreateYUV422PackedTexture(), CLinuxRendererGL::CreateYV12Texture(), CLinuxRendererGLES::CreateYV12Texture(), CLinuxRendererGL::DeleteNV12Texture(), CLinuxRendererGLES::DeleteNV12Texture(), CXBMCTestUtils::DeleteTempFile(), CLinuxRendererGL::DeleteYUV422PackedTexture(), CLinuxRendererGL::DeleteYV12Texture(), CLinuxRendererGLES::DeleteYV12Texture(), dll_findnext(), dll_findnext64i32(), dll_open(), CPythonInvoker::execute(), dbiplus::field_value::field_value(), CMatrixGL::Frustum(), dbiplus::Dataset::fv(), KODI::PLAYLIST::CSmartPlaylistRule::GetFieldType(), CTextureRule::GetFieldType(), CFreeTypeLibrary::GetFont(), KODI::PLAYLIST::CSmartPlaylistRule::GetLocalizedField(), GetPacketExtradata(), CSMB::Init(), CGUIDialogMediaFilter::InitializeSettings(), KODI::PLAYLIST::CSmartPlaylistRule::IsFieldBrowseable(), anonymous_namespace{EmuFileWrapper.cpp}::isValidFilePtr(), CXBMCTinyXML::LoadFile(), CMatrixGL::MultMatrixf(), CArchive::operator<<(), dbiplus::field_value::operator=(), CArchive::operator>>(), CMatrixGL::Ortho(), HttpParser::parseHeader(), CUDisks2Provider::ParseInterface(), CUDisks2Provider::ParseProperties(), printTVtoBuf(), CPythonInvoker::PyFile_AsFileWithMode(), CTeletextDecoder::RenderChar(), CTeletextDecoder::RenderCharIntern(), CWeatherInfo::Reset(), Win32DllLoader::ResolveExport(), SoLoader::ResolveExport(), CMatrixGL::Rotatef(), dbiplus::field_value::set_asFloat(), CLinuxRendererGL::SetTextureFilter(), CLinuxRendererGLES::SetTextureFilter(), TestBasicEnvironment::SetUp(), dbiplus::Dataset::sf(), CJobQueue::Submit(), CJobManager::Submit(), CJobManager::Submit(), CXBMCTestUtils::TempFileDirectory(), CXBMCTestUtils::TempFilePath(), TEST(), TEST(), KODI::PLAYLIST::CSmartPlaylistRule::TranslateField(), CTextureRule::TranslateField(), KODI::PLAYLIST::CSmartPlaylistRule::TranslateField(), CTextureRule::TranslateField(), and CRendererVDPAU::UploadVDPAUTexture420().
file
file = XBMC_CREATETEMPFILE(".xml")
inputdoc
CXBMCTinyXML2 inputdoc
outputdoc
CXBMCTinyXML2 outputdoc
Initial value:
{
  bool retval = false
root
auto* root = inputdoc.RootElement()
Referenced by CDVDStateSerializer::AddXMLElement(), JSONRPC::IJSONRPCAnnouncer::AnnouncementToJSONRPC(), IListProvider::Create(), CContextMenuManager::GetAddonItems(), XFILE::CBlurayDirectory::GetDirectory(), XFILE::CPosixDirectory::GetDirectory(), XMLUtils::GetDouble(), CContextMenuManager::GetItems(), XFILE::CBlurayDirectory::GetUserPlaylists(), CContextMenuManager::HasAddonItems(), CONTEXTMENU::HasAnyMenuItemsFor(), CContextMenuManager::HasItems(), if(), CVideoDatabase::ImportFromXML(), CMusicDatabase::ImportFromXML(), CMusicDatabase::ImportSongHistory(), CSettingsManager::Initialize(), XFILE::CBlurayDirectory::InitializeBluray(), CSettingsBase::InitializeDefinitionsFromXml(), ADDON::CAddonSettings::InitializeFromOldSettingDefinitions(), CContextMenuManager::IsVisible(), CPasswordManager::Load(), CSettings::Load(), CSettings::Load(), CSettingsManager::Load(), KODI::PLAYLIST::CSmartPlaylist::load(), anonymous_namespace{FavouritesService.cpp}::LoadFromFile(), KODI::PLAYLIST::CSmartPlaylist::LoadFromXML(), CSettings::LoadHidden(), CSettingsBase::LoadHiddenValuesFromXml(), ADDON::LoadManifest(), CSkinTimerManager::LoadTimers(), CSettingsBase::LoadValuesFromXml(), CDVDInputStreamBluray::Open(), ParseItem(), ParseItem(), ADDON::CAddonSettings::ParseSettingVersion(), CSettingsManager::ParseVersion(), CEdl::ReadBeyondTV(), KODI::PLAYLIST::CSmartPlaylist::readName(), KODI::PLAYLIST::CSmartPlaylist::readNameFromPath(), KODI::PLAYLIST::CSmartPlaylist::readNameFromXml(), XFILE::CPosixDirectory::RemoveRecursive(), CDecoderFilterManager::Save(), CPasswordManager::Save(), CSettings::Save(), CProfile::Save(), CSettings::Save(), CGUIControlProfiler::SaveResults(), CWakeOnAccess::SaveToXML(), CSettingsValueFlatJsonSerializer::SerializeValues(), CMediaSourceSettings::SetSources(), CONTEXTMENU::ShowFor(), CGUIDialogSimpleMenu::ShowPlaySelection(), CXBMCTinyXML::Test(), TEST(), TEST(), TEST(), TEST(), and TEST().
xmlfile
std::string xmlfile = XBMC_TEMPFILEPATH(file)
Referenced by TEST().