Kodi Documentation: KODI::WINDOWING::WAYLAND::COutput Class Reference
KODI::WINDOWING::WAYLAND::COutput Class Reference
#include <Output.h>
Classes
struct Mode
Public Member Functions
COutput (std::uint32_t globalName, wayland::output_t const &output, std::function< void()> doneHandler)
~COutput () noexcept
wayland::output_t const & GetWaylandOutput () const
std::uint32_t GetGlobalName () const
CPointInt GetPosition () const
CSizeInt GetPhysicalSize () const
std::string const & GetMake () const
std::string const & GetModel () const
std::int32_t GetScale () const
std::set< Mode > const & GetModes () const
Mode const & GetCurrentMode () const
Mode const & GetPreferredMode () const
float GetPixelRatioForMode (Mode const &mode) const
float GetDpiForMode (Mode const &mode) const
float GetCurrentDpi () const
Private Member Functions
COutput (COutput const &other)=delete
COutput & operator= (COutput const &other)=delete
Private Attributes
std::uint32_t m_globalName
wayland::output_t m_output
std::function< void()> m_doneHandler
CCriticalSection m_geometryCriticalSection
CCriticalSection m_iteratorCriticalSection
CPointInt m_position
CSizeInt m_physicalSize
std::string m_make
std::string m_model
std::atomic< std::int32_t > m_scale {1}
std::set< Mode > m_modes
std::set< Mode >::iterator m_currentMode {m_modes.end()}
std::set< Mode >::iterator m_preferredMode {m_modes.end()}
Detailed Description
wl_output handler that collects information from the compositor and then passes it on when everything is available
Constructor & Destructor Documentation
COutput() [1/2]
COutput::COutput (std::uint32_t globalName, wayland::output_t const & output, std::function< void()> doneHandler)
References m_currentMode, m_doneHandler, m_geometryCriticalSection, m_iteratorCriticalSection, m_make, m_model, m_modes, m_output, m_physicalSize, m_position, m_preferredMode, and m_scale.
~COutput()
COutput::~COutput () noexcept
References m_output.
COutput() [2/2]
KODI::WINDOWING::WAYLAND::COutput::COutput (COutput const & other) private delete
Member Function Documentation
GetCurrentDpi()
float COutput::GetCurrentDpi () const
References GetCurrentMode(), and GetDpiForMode().
GetCurrentMode()
const COutput::Mode & COutput::GetCurrentMode () const
References m_currentMode, m_iteratorCriticalSection, and m_modes.
Referenced by GetCurrentDpi().
GetDpiForMode()
float COutput::GetDpiForMode (Mode const & mode) const
References CSizeGen< T >::Height(), CSizeGen< T >::IsZero(), m_geometryCriticalSection, m_physicalSize, KODI::WINDOWING::WAYLAND::COutput::Mode::size, and CSizeGen< T >::Width().
Referenced by GetCurrentDpi().
GetGlobalName()
std::uint32_t KODI::WINDOWING::WAYLAND::COutput::GetGlobalName () const inline
References m_globalName.
GetMake()
std::string const & KODI::WINDOWING::WAYLAND::COutput::GetMake () const inline
References m_geometryCriticalSection, and m_make.
GetModel()
std::string const & KODI::WINDOWING::WAYLAND::COutput::GetModel () const inline
References m_geometryCriticalSection, and m_model.
GetModes()
std::set< Mode > const & KODI::WINDOWING::WAYLAND::COutput::GetModes () const inline
References m_modes.
GetPhysicalSize()
CSizeInt KODI::WINDOWING::WAYLAND::COutput::GetPhysicalSize () const inline
Get output physical size in millimeters
Returns
(width, height) tuple of output physical size in millimeters
References m_geometryCriticalSection, and m_physicalSize.
GetPixelRatioForMode()
float COutput::GetPixelRatioForMode (Mode const & mode) const
References CSizeGen< T >::Height(), CSizeGen< T >::IsZero(), m_geometryCriticalSection, m_physicalSize, KODI::WINDOWING::WAYLAND::COutput::Mode::size, and CSizeGen< T >::Width().
GetPosition()
CPointInt KODI::WINDOWING::WAYLAND::COutput::GetPosition () const inline
Get output position in compositor coordinate space
Returns
(x, y) tuple of output position
References m_geometryCriticalSection, and m_position.
GetPreferredMode()
const COutput::Mode & COutput::GetPreferredMode () const
References m_iteratorCriticalSection, m_modes, and m_preferredMode.
GetScale()
std::int32_t KODI::WINDOWING::WAYLAND::COutput::GetScale () const inline
References m_scale.
GetWaylandOutput()
wayland::output_t const & KODI::WINDOWING::WAYLAND::COutput::GetWaylandOutput () const inline
References m_output.
operator=()
COutput & KODI::WINDOWING::WAYLAND::COutput::operator= (COutput const & other) private delete
Member Data Documentation
m_currentMode
std::set<Mode>::iterator KODI::WINDOWING::WAYLAND::COutput::m_currentMode {m_modes.end()} private
Referenced by COutput(), and GetCurrentMode().
m_doneHandler
std::function<void()> KODI::WINDOWING::WAYLAND::COutput::m_doneHandler private
Referenced by COutput().
m_geometryCriticalSection
CCriticalSection KODI::WINDOWING::WAYLAND::COutput::m_geometryCriticalSection mutable private
Referenced by COutput(), GetDpiForMode(), GetMake(), GetModel(), GetPhysicalSize(), GetPixelRatioForMode(), and GetPosition().
m_globalName
std::uint32_t KODI::WINDOWING::WAYLAND::COutput::m_globalName private
Referenced by GetGlobalName().
m_iteratorCriticalSection
CCriticalSection KODI::WINDOWING::WAYLAND::COutput::m_iteratorCriticalSection mutable private
Referenced by COutput(), GetCurrentMode(), and GetPreferredMode().
m_make
std::string KODI::WINDOWING::WAYLAND::COutput::m_make private
Referenced by COutput(), and GetMake().
m_model
std::string KODI::WINDOWING::WAYLAND::COutput::m_model private
Referenced by COutput(), and GetModel().
m_modes
std::set<Mode> KODI::WINDOWING::WAYLAND::COutput::m_modes private
Referenced by COutput(), GetCurrentMode(), GetModes(), and GetPreferredMode().
m_output
wayland::output_t KODI::WINDOWING::WAYLAND::COutput::m_output private
Referenced by COutput(), GetWaylandOutput(), and ~COutput().
m_physicalSize
CSizeInt KODI::WINDOWING::WAYLAND::COutput::m_physicalSize private
Referenced by COutput(), GetDpiForMode(), GetPhysicalSize(), and GetPixelRatioForMode().
m_position
CPointInt KODI::WINDOWING::WAYLAND::COutput::m_position private
Referenced by COutput(), and GetPosition().
m_preferredMode
std::set<Mode>::iterator KODI::WINDOWING::WAYLAND::COutput::m_preferredMode {m_modes.end()} private
Referenced by COutput(), and GetPreferredMode().
m_scale
std::atomic<std::int32_t> KODI::WINDOWING::WAYLAND::COutput::m_scale {1} private
Referenced by COutput(), and GetScale().
The documentation for this class was generated from the following files:
Output.h
Output.cpp