Kodi Documentation: CWinSystemWin10 Class Reference
CWinSystemWin10 Class Reference abstract
#include <WinSystemWin10.h>
Public Member Functions
CWinSystemWin10 ()
virtual ~CWinSystemWin10 ()
bool InitWindowSystem () override
bool DestroyWindowSystem () override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
void FinishWindowResize (int newWidth, int newHeight) override
void ForceFullScreen (const RESOLUTION_INFO &resInfo) override
Forces the window to fullscreen provided the window resolution.
void UpdateResolutions () override
void NotifyAppFocusChange (bool bGaining) override
void ShowOSMouse (bool show) override
bool HasInertialGestures () override
bool Minimize () override
bool Restore () override
bool Hide () override
bool Show (bool raise=true) override
std::string GetClipboardText () override
bool UseLimitedColor () override
float GetGuiSdrPeakLuminance () const override
Max luminance for GUI SDR content in HDR mode.
bool HasSystemSdrPeakLuminance () override
Test support of the OS for a SDR max luminance in HDR mode setting.
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
bool WindowedMode () const
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
bool IsAlteringWindow () const
void SetAlteringWindow (bool altering)
bool IsTogglingHDR () const
void SetTogglingHDR (bool toggling)
virtual bool DPIChanged (WORD dpi, RECT windowRect) const
bool IsMinimized () const
void SetMinimized (bool minimized)
void CacheSystemSdrPeakLuminance ()
Cache the system HDR/SDR balance for use during rendering, instead of querying the API for each frame.
bool CanDoWindowed () override
bool MessagePump () override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual CRenderSystemBase * GetRenderSystem ()
virtual const std::string GetName ()
virtual bool DestroyWindow ()
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppActiveChange (bool bActivated)
virtual bool HasCursor ()
virtual int NoOfBuffers ()
virtual float GetDisplayLatency ()
Get average display latency.
virtual float GetFrameLatencyAdjustment ()
Get time that should be subtracted from the display latency for this frame in milliseconds.
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual bool SetHDR (const VideoPicture *videoPicture)
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
virtual bool IsHDRDisplay ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual CHDRCapabilities GetDisplayHDRCapabilities () const
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
virtual std::vector< std::string > GetConnectedOutputs ()
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
virtual bool BindTextureUploadContext ()
Binds a shared context to the current thread, in order to upload textures asynchronously.
virtual bool UnbindTextureUploadContext ()
Unbinds the shared context.
virtual bool HasContext ()
Checks if a graphics context is already bound to the current thread.
Protected Member Functions
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override=0
virtual void UpdateStates (bool fullScreen)
WINDOW_STATE GetState (bool fullScreen) const
virtual void SetDeviceFullScreen (bool fullScreen, RESOLUTION_INFO &res)=0
virtual void ReleaseBackBuffer ()=0
virtual void CreateBackBuffer ()=0
virtual void ResizeDeviceBuffers ()=0
virtual bool IsStereoEnabled ()=0
virtual void AdjustWindow ()
virtual void Register (IDispResource *resource)
virtual void Unregister (IDispResource *resource)
bool ChangeResolution (const RESOLUTION_INFO &res, bool forceChange=false)
const MONITOR_DETAILS * GetDefaultMonitor () const
void RestoreDesktopResolution ()
void GetConnectedDisplays (std::vector< MONITOR_DETAILS > &outputs)
void OnDisplayLost ()
void OnDisplayReset ()
void OnDisplayBack ()
void ResolutionChanged ()
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
virtual std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl ()
Static Protected Member Functions
static bool AddResolution (const RESOLUTION_INFO &res)
Adds a resolution to the list of resolutions if we don't already have it.
Protected Attributes
std::vector< MONITOR_DETAILS > m_displays
bool m_ValidWindowedPosition
bool m_IsAlteringWindow
CCriticalSection m_resourceSection
std::vector< IDispResource * > m_resources
bool m_delayDispReset
XbmcThreads::EndTime m_dispResetTimer
WINDOW_STATE m_state
WINDOW_FULLSCREEN_STATE m_fullscreenState
WINDOW_WINDOW_STATE m_windowState
bool m_inFocus
bool m_bMinimized
bool m_bFirstResChange = true
winrt::Windows::UI::Core::CoreWindow m_coreWindow = nullptr
bool m_validSystemSdrPeakLuminance {false}
float m_systemSdrPeakLuminance {.0f}
DWORD m_uiThreadId {0}
HDR_STATUS m_cachedHdrStatus {HDR_STATUS::HDR_UNSUPPORTED}
bool m_cachedHasSystemSdrPeakLum {false}
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Additional Inherited Members
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Constructor & Destructor Documentation
CWinSystemWin10()
CWinSystemWin10::CWinSystemWin10 ()
References AE::CAESinkFactory::ClearSinks(), CWinSystemBase::m_winEvents, CAESinkWASAPI::Register(), CAESinkXAudio::Register(), and CScreenshotSurfaceWindows::Register().
~CWinSystemWin10()
CWinSystemWin10::~CWinSystemWin10 () virtual
Member Function Documentation
AddResolution()
bool CWinSystemWin10::AddResolution (const RESOLUTION_INFO & res) static protected
Adds a resolution to the list of resolutions if we don't already have it.
Parameters
res resolution to add.
References CDisplaySettings::AddResolutionInfo(), RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fRefreshRate, CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iWidth, RES_CUSTOM, and CDisplaySettings::ResolutionInfoSize().
Referenced by UpdateResolutions().
AdjustWindow()
void CWinSystemWin10::AdjustWindow () protected virtual
References DX::ConvertPixelsToDips(), DX::DeviceResources::Get(), CLog::Log(), LOGDEBUG, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, m_state, WINDOW_STATE_FULLSCREEN, and WINDOW_STATE_FULLSCREEN_WINDOW.
Referenced by CreateNewWindow(), ResizeWindow(), and SetFullScreen().
CacheSystemSdrPeakLuminance()
void CWinSystemWin10::CacheSystemSdrPeakLuminance ()
Cache the system HDR/SDR balance for use during rendering, instead of querying the API for each frame.
References CWIN32Util::GetSystemSdrWhiteLevel(), m_systemSdrPeakLuminance, and m_validSystemSdrPeakLuminance.
CanDoWindowed()
bool CWinSystemWin10::CanDoWindowed () override virtual
Reimplemented from CWinSystemBase.
References CSysInfo::Desktop, and CSysInfo::GetWindowsDeviceFamily().
ChangeResolution()
bool CWinSystemWin10::ChangeResolution (const RESOLUTION_INFO & res, bool forceChange = false) protected
References DX::ConvertPixelsToDips(), RESOLUTION_INFO::fRefreshRate, DX::DeviceResources::Get(), GetDefaultMonitor(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetStereoMode(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, LOGDEBUG, CWinSystemBase::m_bWindowCreated, m_coreWindow, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, CWinEventsWin10::OnResize(), MONITOR_DETAILS::RefreshRate, RENDER_STEREO_MODE_HARDWAREBASED, MONITOR_DETAILS::ScreenHeight, MONITOR_DETAILS::ScreenWidth, and Wait().
Referenced by RestoreDesktopResolution(), and SetFullScreen().
CreateBackBuffer()
virtual void CWinSystemWin10::CreateBackBuffer () protected pure virtual
Implemented in CWinSystemWin10DX.
Referenced by SetFullScreen().
CreateNewWindow()
bool CWinSystemWin10::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) override protected pure virtual
Implements CWinSystemBase.
Implemented in CWinSystemWin10DX.
References AdjustWindow(), RESOLUTION_INFO::fRefreshRate, GetState(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, CWinSystemBase::m_bFullScreen, CWinSystemBase::m_bWindowCreated, m_coreWindow, CWinSystemBase::m_fRefreshRate, m_inFocus, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, m_state, and UpdateStates().
Referenced by CWinSystemWin10DX::CreateNewWindow().
DestroyWindowSystem()
bool CWinSystemWin10::DestroyWindowSystem () override virtual
Reimplemented from CWinSystemBase.
References CWinSystemBase::m_bWindowCreated, and RestoreDesktopResolution().
DPIChanged()
bool CWinSystemWin10::DPIChanged (WORD dpi, RECT windowRect) const virtual
Reimplemented in CWinSystemWin10DX.
References void().
Referenced by CWinSystemWin10DX::DPIChanged().
FinishWindowResize()
void CWinSystemWin10::FinishWindowResize (int newWidth, int newHeight) override virtual
Reimplemented from CWinSystemBase.
References DX::ConvertPixelsToDips(), DX::DeviceResources::Get(), CWinSystemBase::m_nHeight, and CWinSystemBase::m_nWidth.
ForceFullScreen()
void CWinSystemWin10::ForceFullScreen (const RESOLUTION_INFO & resInfo) override virtual
Forces the window to fullscreen provided the window resolution.
Parameters
resInfo - the resolution info
Reimplemented from CWinSystemBase.
References RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, and ResizeWindow().
GetClipboardText()
std::string CWinSystemWin10::GetClipboardText (void) override virtual
Reimplemented from CWinSystemBase.
References KODI::PLATFORM::WINDOWS::FromW(), text, and Wait().
GetConnectedDisplays()
void CWinSystemWin10::GetConnectedDisplays (std::vector< MONITOR_DETAILS > & outputs) protected
References MONITOR_DETAILS::Bpp, MONITOR_DETAILS::Interlaced, m_coreWindow, MONITOR_DETAILS::RefreshRate, MONITOR_DETAILS::ScreenHeight, MONITOR_DETAILS::ScreenWidth, and Wait().
Referenced by UpdateResolutions().
GetDefaultMonitor()
const MONITOR_DETAILS * CWinSystemWin10::GetDefaultMonitor () const protected
References m_displays.
Referenced by ChangeResolution(), CWinSystemWin10DX::CreateNewWindow(), and UpdateResolutions().
GetGuiSdrPeakLuminance()
float CWinSystemWin10::GetGuiSdrPeakLuminance () const override virtual
Max luminance for GUI SDR content in HDR mode.
Returns
Max luminance in nits, lower than 10000.
Reimplemented from CWinSystemBase.
References CServiceBroker::GetSettingsComponent(), m_systemSdrPeakLuminance, m_validSystemSdrPeakLuminance, CSettings::SETTING_VIDEOSCREEN_GUISDRPEAKLUMINANCE, and CSettings::SETTING_VIDEOSCREEN_USESYSTEMSDRPEAKLUMINANCE.
GetState()
WINDOW_STATE CWinSystemWin10::GetState (bool fullScreen) const protected
References m_fullscreenState, and m_windowState.
Referenced by CreateNewWindow(), and SetFullScreen().
GetVideoSync()
std::unique_ptr< CVideoSync > CWinSystemWin10::GetVideoSync (CVideoReferenceClock * clock) override virtual
Reimplemented from CWinSystemBase.
HasInertialGestures()
bool CWinSystemWin10::HasInertialGestures () inline override virtual
Reimplemented from CWinSystemBase.
HasSystemSdrPeakLuminance()
bool CWinSystemWin10::HasSystemSdrPeakLuminance () override virtual
Test support of the OS for a SDR max luminance in HDR mode setting.
Returns
true when the OS supports that setting, false otherwise
Reimplemented from CWinSystemBase.
References CWIN32Util::GetSystemSdrWhiteLevel(), m_cachedHasSystemSdrPeakLum, and m_uiThreadId.
Referenced by CWinSystemWin10DX::CreateNewWindow().
Hide()
bool CWinSystemWin10::Hide () override virtual
Reimplemented from CWinSystemBase.
References CLog::Log(), and LOGDEBUG.
InitWindowSystem()
bool CWinSystemWin10::InitWindowSystem () override virtual
Reimplemented from CWinSystemBase.
References CWinEventsWin10::InitEventHandlers(), CWinSystemBase::InitWindowSystem(), CLog::Log(), LOGERROR, m_coreWindow, and m_displays.
IsAlteringWindow()
bool CWinSystemWin10::IsAlteringWindow () const inline
References m_IsAlteringWindow.
Referenced by CWinSystemWin10DX::DPIChanged().
IsMinimized()
bool CWinSystemWin10::IsMinimized () const inline
References m_bMinimized.
IsStereoEnabled()
virtual bool CWinSystemWin10::IsStereoEnabled () protected pure virtual
Implemented in CWinSystemWin10DX.
Referenced by SetFullScreen().
IsTogglingHDR()
bool CWinSystemWin10::IsTogglingHDR () const inline
MessagePump()
bool CWinSystemWin10::MessagePump () override virtual
Reimplemented from CWinSystemBase.
References CWinSystemBase::m_winEvents.
Minimize()
bool CWinSystemWin10::Minimize () override virtual
Reimplemented from CWinSystemBase.
References CLog::Log(), and LOGDEBUG.
NotifyAppFocusChange()
void CWinSystemWin10::NotifyAppFocusChange (bool bGaining) override virtual
Reimplemented from CWinSystemBase.
References m_inFocus.
OnDisplayBack()
void CWinSystemWin10::OnDisplayBack () protected
References CServiceBroker::GetSettingsComponent(), m_delayDispReset, m_dispResetTimer, and OnDisplayReset().
Referenced by ResolutionChanged().
OnDisplayLost()
void CWinSystemWin10::OnDisplayLost () protected
References CLog::Log(), LOGDEBUG, m_resources, and m_resourceSection.
Referenced by ResolutionChanged().
OnDisplayReset()
void CWinSystemWin10::OnDisplayReset () protected
References CLog::Log(), LOGDEBUG, m_delayDispReset, m_resources, and m_resourceSection.
Referenced by OnDisplayBack(), and CWinSystemWin10DX::PresentRenderImpl().
Register()
void CWinSystemWin10::Register (IDispResource * resource) protected virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemWin10DX.
References m_resources, and m_resourceSection.
Referenced by CWinSystemWin10DX::Register().
ReleaseBackBuffer()
virtual void CWinSystemWin10::ReleaseBackBuffer () protected pure virtual
Implemented in CWinSystemWin10DX.
Referenced by SetFullScreen().
ResizeDeviceBuffers()
virtual void CWinSystemWin10::ResizeDeviceBuffers () protected pure virtual
Implemented in CWinSystemWin10DX.
ResizeWindow()
bool CWinSystemWin10::ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemWin10DX.
References AdjustWindow(), CWinSystemBase::m_nHeight, CWinSystemBase::m_nLeft, CWinSystemBase::m_nTop, and CWinSystemBase::m_nWidth.
Referenced by ForceFullScreen(), and CWinSystemWin10DX::ResizeWindow().
ResolutionChanged()
void CWinSystemWin10::ResolutionChanged () protected
References OnDisplayBack(), and OnDisplayLost().
Restore()
bool CWinSystemWin10::Restore () override virtual
Reimplemented from CWinSystemBase.
References CLog::Log(), and LOGDEBUG.
RestoreDesktopResolution()
void CWinSystemWin10::RestoreDesktopResolution () protected
References ChangeResolution(), CDisplaySettings::GetInstance(), CLog::Log(), LOGDEBUG, and RES_DESKTOP.
Referenced by DestroyWindowSystem(), and SetFullScreen().
SetAlteringWindow()
void CWinSystemWin10::SetAlteringWindow (bool altering) inline
References m_IsAlteringWindow.
SetDeviceFullScreen()
virtual void CWinSystemWin10::SetDeviceFullScreen (bool fullScreen, RESOLUTION_INFO & res) protected pure virtual
Implemented in CWinSystemWin10DX.
SetFullScreen()
bool CWinSystemWin10::SetFullScreen (bool fullScreen, RESOLUTION_INFO & res, bool blankOtherDisplays) override virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemWin10DX.
References AdjustWindow(), ChangeResolution(), CResolutionUtils::ChooseBestResolution(), CreateBackBuffer(), D3DPRESENTFLAG_INTERLACED, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fRefreshRate, CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), GetState(), CGraphicContext::GetStereoMode(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iHeight, IsStereoEnabled(), RESOLUTION_INFO::iWidth, CLog::Log(), LOGDEBUG, CWinSystemBase::m_bBlankOtherDisplay, m_bFirstResChange, CWinSystemBase::m_bFullScreen, m_coreWindow, CWinSystemBase::m_fRefreshRate, m_IsAlteringWindow, CWinSystemBase::m_nHeight, CWinSystemBase::m_nLeft, CWinSystemBase::m_nTop, CWinSystemBase::m_nWidth, m_state, m_ValidWindowedPosition, ReleaseBackBuffer(), RENDER_STEREO_MODE_HARDWAREBASED, RestoreDesktopResolution(), UpdateStates(), WINDOW_STATE_FULLSCREEN, WINDOW_STATE_FULLSCREEN_WINDOW, window_state_names, and WINDOW_STATE_WINDOWED.
Referenced by CWinSystemWin10DX::SetFullScreen().
SetMinimized()
void CWinSystemWin10::SetMinimized (bool minimized) inline
References m_bMinimized.
SetTogglingHDR()
void CWinSystemWin10::SetTogglingHDR (bool toggling) inline
Show()
bool CWinSystemWin10::Show (bool raise = true) override virtual
Reimplemented from CWinSystemBase.
References CLog::Log(), and LOGDEBUG.
ShowOSMouse()
void CWinSystemWin10::ShowOSMouse (bool show) override virtual
Reimplemented from CWinSystemBase.
References m_coreWindow.
Unregister()
void CWinSystemWin10::Unregister (IDispResource * resource) protected virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemWin10DX.
References m_resources, and m_resourceSection.
Referenced by CWinSystemWin10DX::Unregister().
UpdateResolutions()
void CWinSystemWin10::UpdateResolutions () override virtual
Reimplemented from CWinSystemBase.
References AddResolution(), CDisplaySettings::ApplyCalibrations(), RESOLUTION_INFO::bFullScreen, CDisplaySettings::ClearCustomResolutions(), D3DPRESENTFLAG_INTERLACED, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fPixelRatio, RESOLUTION_INFO::fRefreshRate, GetConnectedDisplays(), GetDefaultMonitor(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RESOLUTION_INFO::iHeight, MONITOR_DETAILS::Interlaced, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, CLog::Log(), LOGINFO, m_displays, MONITOR_DETAILS::RefreshRate, RES_DESKTOP, CGraphicContext::ResetOverscan(), MONITOR_DETAILS::ScreenHeight, MONITOR_DETAILS::ScreenWidth, RESOLUTION_INFO::strMode, CWinSystemBase::UpdateDesktopResolution(), and CWinSystemBase::UpdateResolutions().
UpdateStates()
void CWinSystemWin10::UpdateStates (bool fullScreen) protected virtual
References m_fullscreenState, m_windowState, WINDOW_FULLSCREEN_STATE_FULLSCREEN_WINDOW, and WINDOW_WINDOW_STATE_WINDOWED.
Referenced by CreateNewWindow(), and SetFullScreen().
UseLimitedColor()
bool CWinSystemWin10::UseLimitedColor () override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOSCREEN_LIMITEDRANGE.
WindowedMode()
bool CWinSystemWin10::WindowedMode () const inline
References m_state, and WINDOW_STATE_FULLSCREEN.
Member Data Documentation
m_bFirstResChange
bool CWinSystemWin10::m_bFirstResChange = true protected
Referenced by SetFullScreen().
m_bMinimized
bool CWinSystemWin10::m_bMinimized protected
Referenced by IsMinimized(), and SetMinimized().
m_cachedHasSystemSdrPeakLum
bool CWinSystemWin10::m_cachedHasSystemSdrPeakLum {false} protected
Referenced by HasSystemSdrPeakLuminance().
m_cachedHdrStatus
HDR_STATUS CWinSystemWin10::m_cachedHdrStatus {HDR_STATUS::HDR_UNSUPPORTED} protected
Referenced by CWinSystemWin10DX::IsHDRDisplay().
m_coreWindow
winrt::Windows::UI::Core::CoreWindow CWinSystemWin10::m_coreWindow = nullptr protected
Referenced by ChangeResolution(), CWinSystemWin10DX::CreateNewWindow(), CreateNewWindow(), GetConnectedDisplays(), InitWindowSystem(), CWinSystemWin10DX::OnMove(), SetFullScreen(), ShowOSMouse(), and CWinSystemWin10DX::ShowSplash().
m_delayDispReset
bool CWinSystemWin10::m_delayDispReset protected
Referenced by OnDisplayBack(), OnDisplayReset(), and CWinSystemWin10DX::PresentRenderImpl().
m_displays
std::vector<MONITOR_DETAILS> CWinSystemWin10::m_displays protected
Referenced by GetDefaultMonitor(), InitWindowSystem(), and UpdateResolutions().
m_dispResetTimer
XbmcThreads::EndTime CWinSystemWin10::m_dispResetTimer protected
Referenced by OnDisplayBack(), and CWinSystemWin10DX::PresentRenderImpl().
m_fullscreenState
WINDOW_FULLSCREEN_STATE CWinSystemWin10::m_fullscreenState protected
Referenced by GetState(), and UpdateStates().
m_inFocus
bool CWinSystemWin10::m_inFocus protected
Referenced by CreateNewWindow(), and NotifyAppFocusChange().
m_IsAlteringWindow
bool CWinSystemWin10::m_IsAlteringWindow protected
Referenced by IsAlteringWindow(), CWinSystemWin10DX::OnResize(), SetAlteringWindow(), and SetFullScreen().
m_resources
std::vector<IDispResource*> CWinSystemWin10::m_resources protected
Referenced by OnDisplayLost(), OnDisplayReset(), Register(), and Unregister().
m_resourceSection
CCriticalSection CWinSystemWin10::m_resourceSection protected
Referenced by OnDisplayLost(), OnDisplayReset(), Register(), and Unregister().
m_state
WINDOW_STATE CWinSystemWin10::m_state protected
Referenced by AdjustWindow(), CreateNewWindow(), SetFullScreen(), and WindowedMode().
m_systemSdrPeakLuminance
float CWinSystemWin10::m_systemSdrPeakLuminance {.0f} protected
Referenced by CacheSystemSdrPeakLuminance(), and GetGuiSdrPeakLuminance().
m_uiThreadId
DWORD CWinSystemWin10::m_uiThreadId {0} protected
Referenced by CWinSystemWin10DX::CreateNewWindow(), HasSystemSdrPeakLuminance(), and CWinSystemWin10DX::IsHDRDisplay().
m_validSystemSdrPeakLuminance
bool CWinSystemWin10::m_validSystemSdrPeakLuminance {false} protected
Referenced by CacheSystemSdrPeakLuminance(), and GetGuiSdrPeakLuminance().
m_ValidWindowedPosition
bool CWinSystemWin10::m_ValidWindowedPosition protected
Referenced by SetFullScreen().
m_windowState
WINDOW_WINDOW_STATE CWinSystemWin10::m_windowState protected
Referenced by GetState(), and UpdateStates().
The documentation for this class was generated from the following files:
WinSystemWin10.h
WinSystemWin10.cpp