Kodi Documentation: Observable Class Reference
Observable Class Reference
#include <Observer.h>
Public Member Functions
Observable ()=default
virtual ~Observable ()=default
Observable & operator= (const Observable &observable)
virtual void RegisterObserver (Observer *obs)
Register an observer.
virtual void UnregisterObserver (Observer *obs)
Unregister an observer.
virtual void NotifyObservers (const ObservableMessage message=ObservableMessageNone)
Send a message to all observers when m_bObservableChanged is true.
virtual void SetChanged (bool bSetTo=true)
Mark an observable changed.
virtual bool IsObserving (const Observer &obs) const
Check whether this observable is being observed by an observer.
Protected Member Functions
void SendMessage (const ObservableMessage message)
Send a message to all observer when m_bObservableChanged is true.
Protected Attributes
std::atomic< bool > m_bObservableChanged {false}
std::vector< Observer * > m_observers
CCriticalSection m_obsCritSection
Friends
class ObservableMessageJob
Constructor & Destructor Documentation
Observable()
Observable::Observable () default
~Observable()
virtual Observable::~Observable () virtual default
Member Function Documentation
IsObserving()
bool Observable::IsObserving (const Observer & obs) const virtual
Check whether this observable is being observed by an observer.
Parameters
obs The observer to check.
Returns
True if this observable is being observed by the given observer, false otherwise.
References m_obsCritSection, and m_observers.
Referenced by RegisterObserver().
NotifyObservers()
void Observable::NotifyObservers (const ObservableMessage message = ObservableMessageNone) virtual
Send a message to all observers when m_bObservableChanged is true.
Parameters
message The message to send.
References m_bObservableChanged, and SendMessage().
Referenced by CInputManager::AddKeymap(), CInputManager::ClearKeymaps(), CInputManager::LoadKeymaps(), KODI::GAME::CAgentInput::OnButtonPress(), KODI::GAME::CDialogGameStretchMode::OnItemFocus(), KODI::GAME::CDialogGameVideoFilter::OnItemFocus(), KODI::GAME::CDialogGameVideoRotation::OnItemFocus(), KODI::GAME::CAgentInput::OnKeyPress(), KODI::GAME::CAgentInput::OnPosition(), KODI::GAME::CGameSettings::OnSettingChanged(), KODI::SUBTITLES::CSubtitlesSettings::OnSettingChanged(), KODI::GAME::CAgentInput::Refresh(), CInputManager::RemoveKeymap(), KODI::GAME::CGameClientInput::SavePorts(), PERIPHERALS::CPeripheralBus::ScanForDevices(), KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), KODI::GAME::CGameClientInput::Start(), and KODI::GAME::CAgentInput::Stop().
operator=()
Observable & Observable::operator= (const Observable & observable)
References m_bObservableChanged, m_obsCritSection, and m_observers.
RegisterObserver()
void Observable::RegisterObserver (Observer * obs) virtual
Register an observer.
Parameters
obs The observer to register.
References IsObserving(), m_obsCritSection, and m_observers.
Referenced by KODI::GAME::CAgentInput::CAgentInput(), KODI::RETRO::CGUIGameSettings::CGUIGameSettings(), KODI::KEYMAP::CKeymapHandling::CKeymapHandling(), KODI::RETRO::CReversiblePlayback::CReversiblePlayback(), KODI::GAME::CGUIAgentControllerList::Initialize(), KODI::GAME::CGUIDialogButtonCapture::InstallHooks(), KODI::GAME::CGUIConfigurationWizard::InstallHooks(), and PERIPHERALS::CGUIDialogPeripherals::RegisterPeripheralManager().
SendMessage()
void Observable::SendMessage (const ObservableMessage message) protected
Send a message to all observer when m_bObservableChanged is true.
Parameters
obs The observer that sends the message.
message The message to send.
References m_obsCritSection, and m_observers.
Referenced by NotifyObservers().
SetChanged()
void Observable::SetChanged (bool bSetTo = true) virtual
Mark an observable changed.
Parameters
bSetTo True to mark the observable changed, false to mark it as unchanged.
References m_bObservableChanged.
Referenced by CInputManager::AddKeymap(), CInputManager::ClearKeymaps(), KODI::GAME::CGameClientInput::ConnectController(), KODI::GAME::CGameClientInput::DisconnectController(), CInputManager::LoadKeymaps(), PERIPHERALS::CPeripherals::OnDeviceChanged(), KODI::GAME::CGameSettings::OnSettingChanged(), KODI::SUBTITLES::CSubtitlesSettings::OnSettingChanged(), KODI::GAME::CAgentInput::ProcessAgentControllers(), KODI::GAME::CAgentInput::ProcessKeyboard(), KODI::GAME::CAgentInput::ProcessMouse(), CInputManager::RemoveKeymap(), CDisplaySettings::SetCurrentResolution(), CGameSettings::SetRotationDegCCW(), CGameSettings::SetStretchMode(), CGameSettings::SetVideoFilter(), KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), KODI::GAME::CAgentInput::Stop(), KODI::GAME::CAgentInput::UpdateConnectedJoysticks(), and KODI::GAME::CAgentInput::UpdateExpiredJoysticks().
UnregisterObserver()
void Observable::UnregisterObserver (Observer * obs) virtual
Unregister an observer.
Parameters
obs The observer to unregister.
References m_obsCritSection, and m_observers.
Referenced by KODI::GAME::CGUIAgentControllerList::Deinitialize(), KODI::GAME::CGUIDialogButtonCapture::RemoveHooks(), KODI::GAME::CGUIConfigurationWizard::RemoveHooks(), PERIPHERALS::CGUIDialogPeripherals::UnregisterPeripheralManager(), KODI::GAME::CAgentInput::~CAgentInput(), KODI::RETRO::CGUIGameSettings::~CGUIGameSettings(), KODI::KEYMAP::CKeymapHandling::~CKeymapHandling(), and KODI::RETRO::CReversiblePlayback::~CReversiblePlayback().
Friends And Related Symbol Documentation
ObservableMessageJob
friend class ObservableMessageJob friend
Member Data Documentation
m_bObservableChanged
std::atomic<bool> Observable::m_bObservableChanged {false} protected
true when the observable is marked as changed, false otherwise
Referenced by NotifyObservers(), operator=(), and SetChanged().
m_obsCritSection
CCriticalSection Observable::m_obsCritSection mutable protected
mutex
Referenced by IsObserving(), operator=(), RegisterObserver(), SendMessage(), and UnregisterObserver().
m_observers
std::vector<Observer *> Observable::m_observers protected
all observers
Referenced by IsObserving(), operator=(), RegisterObserver(), SendMessage(), and UnregisterObserver().
The documentation for this class was generated from the following files:
Observer.h
Observer.cpp