Kodi Documentation: KODI::RETRO::CRPWinOutputShader Class Reference
KODI::RETRO::CRPWinOutputShader Class Reference
#include <RPWinOutputShader.h>
Classes
struct CUSTOMVERTEX
Public Member Functions
~CRPWinOutputShader ()=default
bool Create (SCALINGMETHOD scalingMethod)
void Render (CD3DTexture &sourceTexture, CRect sourceRect, const CPoint points[4], CRect &viewPort, CD3DTexture *target, unsigned range=0)
Private Member Functions
void PrepareParameters (unsigned sourceWidth, unsigned sourceHeight, CRect sourceRect, const CPoint points[4])
void SetShaderParameters (CD3DTexture &sourceTexture, unsigned range, CRect &viewPort)
Private Attributes
unsigned m_sourceWidth {0}
unsigned m_sourceHeight {0}
CRect m_sourceRect {0.f, 0.f, 0.f, 0.f}
CPoint m_destPoints [4]
Additional Inherited Members
Protected Member Functions inherited from CWinShader
CWinShader ()=default
virtual ~CWinShader ()=default
virtual bool CreateVertexBuffer (unsigned int vertCount, unsigned int vertSize)
virtual bool LockVertexBuffer (void **data)
virtual bool UnlockVertexBuffer ()
virtual bool LoadEffect (const std::string &filename, DefinesMap *defines)
virtual bool Execute (const std::vector< CD3DTexture * > &targets, unsigned int vertexIndexStep)
virtual void SetStepParams (unsigned stepIndex)
virtual bool CreateInputLayout (D3D11_INPUT_ELEMENT_DESC *layout, unsigned numElements)
Protected Attributes inherited from CWinShader
CD3DEffect m_effect
CD3DTexture * m_target = nullptr
Constructor & Destructor Documentation
~CRPWinOutputShader()
KODI::RETRO::CRPWinOutputShader::~CRPWinOutputShader () default
Member Function Documentation
Create()
bool CRPWinOutputShader::Create (SCALINGMETHOD scalingMethod)
References CWinShader::CreateInputLayout(), CWinShader::CreateVertexBuffer(), KODI::RETRO::LINEAR, CWinShader::LoadEffect(), LOGERROR, and KODI::RETRO::NEAREST.
PrepareParameters()
void CRPWinOutputShader::PrepareParameters (unsigned sourceWidth, unsigned sourceHeight, CRect sourceRect, const CPoint points[4]) private
References CWinShader::LockVertexBuffer(), m_destPoints, m_sourceHeight, m_sourceRect, m_sourceWidth, KODI::RETRO::CRPWinOutputShader::CUSTOMVERTEX::tu, KODI::RETRO::CRPWinOutputShader::CUSTOMVERTEX::tv, CWinShader::UnlockVertexBuffer(), KODI::RETRO::CRPWinOutputShader::CUSTOMVERTEX::x, CPointGen< T >::x, CRectGen< T >::x1, CRectGen< T >::x2, KODI::RETRO::CRPWinOutputShader::CUSTOMVERTEX::y, CPointGen< T >::y, CRectGen< T >::y1, CRectGen< T >::y2, and KODI::RETRO::CRPWinOutputShader::CUSTOMVERTEX::z.
Referenced by Render().
Render()
void CRPWinOutputShader::Render (CD3DTexture & sourceTexture, CRect sourceRect, const CPoint points[4], CRect & viewPort, CD3DTexture * target, unsigned range = 0)
References CWinShader::Execute(), CD3DTexture::GetHeight(), CD3DTexture::GetWidth(), PrepareParameters(), and SetShaderParameters().
Referenced by KODI::RETRO::CRPWinRenderer::Render().
SetShaderParameters()
void CRPWinOutputShader::SetShaderParameters (CD3DTexture & sourceTexture, unsigned range, CRect & viewPort) private
References CD3DTexture::GetAddressOfSRV(), CRectGen< T >::Height(), CWinShader::m_effect, CD3DEffect::SetFloatArray(), CD3DEffect::SetResources(), CD3DEffect::SetTechnique(), and CRectGen< T >::Width().
Referenced by Render().
Member Data Documentation
m_destPoints
CPoint KODI::RETRO::CRPWinOutputShader::m_destPoints[4] private
Initial value:
= {
      {0.f, 0.f},
      {0.f, 0.f},
      {0.f, 0.f},
      {0.f, 0.f},
  }
Referenced by PrepareParameters().
m_sourceHeight
unsigned KODI::RETRO::CRPWinOutputShader::m_sourceHeight {0} private
Referenced by PrepareParameters().
m_sourceRect
CRect KODI::RETRO::CRPWinOutputShader::m_sourceRect {0.f, 0.f, 0.f, 0.f} private
Referenced by PrepareParameters().
m_sourceWidth
unsigned KODI::RETRO::CRPWinOutputShader::m_sourceWidth {0} private
Referenced by PrepareParameters().
The documentation for this class was generated from the following files:
RPWinOutputShader.h
RPWinOutputShader.cpp