Kodi Documentation: CGUIVisualisationControl Class Reference
CGUIVisualisationControl Class Reference
#include <GUIVisualisationControl.h>
Public Member Functions
CGUIVisualisationControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIVisualisationControl (const CGUIVisualisationControl &from)
CGUIVisualisationControl * Clone () const override
void OnInitialize (int channels, int samplesPerSec, int bitsPerSample) override
void OnAudioData (const float *audioData, unsigned int audioDataLength) override
void FreeResources (bool immediately=false) override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void UpdateVisibility (const CGUIListItem *item=nullptr) override
bool OnAction (const CAction &action) override
bool OnMessage (CGUIMessage &message) override
bool CanFocus () const override
bool CanFocusFromPoint (const CPoint &point) const override
Test whether we can focus a control from a point on screen.
std::string Name ()
void UpdateTrack ()
bool HasPresets ()
void SetPreset (int idx)
bool IsLocked ()
int GetActivePreset ()
std::string GetActivePresetName ()
bool GetPresetList (std::vector< std::string > &vecpresets)
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
Perform a mouse action.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual void AllocResources ()
virtual void DynamicResourceAlloc (bool bOnOff)
virtual bool IsDynamicallyAllocated ()
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Public Member Functions inherited from IAudioCallback
IAudioCallback ()=default
virtual ~IAudioCallback ()=default
Private Member Functions
bool InitVisualization ()
void DeInitVisualization ()
void CreateBuffers ()
void ClearBuffers ()
Private Attributes
bool m_callStart {false}
bool m_alreadyStarted {false}
bool m_attemptedLoad {false}
bool m_updateTrack {false}
std::list< std::unique_ptr< CAudioBuffer > > m_vecBuffers
unsigned int m_numBuffers
std::vector< std::string > m_presets
int m_channels
int m_samplesPerSec
int m_bitsPerSample
std::string m_albumThumb
std::string m_name
std::string m_presetsPath
std::string m_profilePath
std::unique_ptr< KODI::ADDONS::CVisualization > m_instance
Additional Inherited Members
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool UpdateColors (const CGUIListItem *item)
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIVisualisationControl() [1/2]
CGUIVisualisationControl::CGUIVisualisationControl (int parentID, int controlID, float posX, float posY, float width, float height)
References CGUIControl::ControlType, and CGUIControl::GUICONTROL_VISUALISATION.
CGUIVisualisationControl() [2/2]
CGUIVisualisationControl::CGUIVisualisationControl (const CGUIVisualisationControl & from)
References CGUIControl::ControlType, and CGUIControl::GUICONTROL_VISUALISATION.
Member Function Documentation
CanFocus()
bool CGUIVisualisationControl::CanFocus () const inline override virtual
Reimplemented from CGUIControl.
CanFocusFromPoint()
bool CGUIVisualisationControl::CanFocusFromPoint (const CPoint & point) const override virtual
Test whether we can focus a control from a point on screen.
Parameters
point the location in vanilla skin coordinates from the upper left corner of the parent control.
Returns
true if the control can be focused from this location
See also
UnfocusFromPoint, HitRect
Reimplemented from CGUIControl.
References CGUIControl::HitTest(), and CGUIControl::IsVisible().
ClearBuffers()
void CGUIVisualisationControl::ClearBuffers () inline private
References m_numBuffers, and m_vecBuffers.
Referenced by CreateBuffers(), and DeInitVisualization().
Clone()
CGUIVisualisationControl * CGUIVisualisationControl::Clone (void) const inline override virtual
Implements CGUIControl.
CreateBuffers()
void CGUIVisualisationControl::CreateBuffers () inline private
References ClearBuffers(), m_instance, and m_numBuffers.
Referenced by InitVisualization().
DeInitVisualization()
void CGUIVisualisationControl::DeInitVisualization () private
References CGraphicContext::CaptureStateBlock(), ClearBuffers(), CServiceBroker::GetActiveAE(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), GUI_MSG_VISUALISATION_UNLOADING, CLog::Log(), LOGDEBUG, m_alreadyStarted, m_attemptedLoad, CGUIControl::m_controlID, m_instance, CGUIWindowManager::SendMessage(), and IAE::UnregisterAudioCallback().
Referenced by FreeResources().
FreeResources()
void CGUIVisualisationControl::FreeResources (bool immediately = false) override virtual
Reimplemented from CGUIControl.
References DeInitVisualization(), CGUIControl::FreeResources(), CLog::Log(), and LOGDEBUG.
Referenced by OnMessage(), Process(), and UpdateVisibility().
GetActivePreset()
int CGUIVisualisationControl::GetActivePreset ()
References m_alreadyStarted, and m_instance.
Referenced by CGUIDialogVisualisationPresetList::SetVisualisation().
GetActivePresetName()
std::string CGUIVisualisationControl::GetActivePresetName ()
References m_alreadyStarted, and m_instance.
Referenced by KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetLabel().
GetPresetList()
bool CGUIVisualisationControl::GetPresetList (std::vector< std::string > & vecpresets)
References m_alreadyStarted, and m_instance.
Referenced by CGUIDialogVisualisationPresetList::SetVisualisation().
HasPresets()
bool CGUIVisualisationControl::HasPresets ()
References m_alreadyStarted, and m_instance.
Referenced by KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetBool().
InitVisualization()
bool CGUIVisualisationControl::InitVisualization () private
References CGraphicContext::CaptureStateBlock(), CreateBuffers(), CServiceBroker::GetActiveAE(), ADDON::CAddonMgr::GetAddonInfo(), CServiceBroker::GetAddonMgr(), CWinSystemBase::GetGfxContext(), CGUIControl::GetHeight(), CServiceBroker::GetSettingsComponent(), CGUIControl::GetWidth(), CServiceBroker::GetWinSystem(), CGUIControl::GetXPosition(), CGUIControl::GetYPosition(), m_alreadyStarted, m_instance, IAE::RegisterAudioCallback(), CSettings::SETTING_MUSICPLAYER_VISUALISATION, and ADDON::VISUALIZATION.
Referenced by Process().
IsLocked()
bool CGUIVisualisationControl::IsLocked ()
References m_alreadyStarted, and m_instance.
Referenced by KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetBool().
Name()
std::string CGUIVisualisationControl::Name ()
References m_instance.
Referenced by CGUIDialogVisualisationPresetList::SetVisualisation().
OnAction()
bool CGUIVisualisationControl::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControl.
References ACTION_VIS_PRESET_LOCK, ACTION_VIS_PRESET_NEXT, ACTION_VIS_PRESET_PREV, ACTION_VIS_PRESET_RANDOM, ACTION_VIS_RATE_PRESET_MINUS, ACTION_VIS_RATE_PRESET_PLUS, m_alreadyStarted, m_instance, and CGUIControl::OnAction().
OnAudioData()
void CGUIVisualisationControl::OnAudioData (const float * audioData, unsigned int audioDataLength) override virtual
Implements IAudioCallback.
References m_alreadyStarted, m_instance, m_numBuffers, and m_vecBuffers.
OnInitialize()
void CGUIVisualisationControl::OnInitialize (int channels, int samplesPerSec, int bitsPerSample) override virtual
Todo:
check for naughties
Implements IAudioCallback.
References m_bitsPerSample, m_callStart, m_channels, and m_samplesPerSec.
OnMessage()
bool CGUIVisualisationControl::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControl.
References FreeResources(), CGUIMessage::GetMessage(), GUI_MSG_GET_VISUALISATION, GUI_MSG_PLAYBACK_STARTED, GUI_MSG_VISUALISATION_RELOAD, m_alreadyStarted, m_updateTrack, CGUIControl::OnMessage(), and CGUIMessage::SetPointer().
Process()
void CGUIVisualisationControl::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
References CGraphicContext::CaptureStateBlock(), FreeResources(), g_application, CServiceBroker::GetAppComponents(), CGUIInfoManager::GetCurrentSongTag(), URIUtils::GetFileName(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), MUSIC_INFO::CMusicInfoTag::GetTitle(), CServiceBroker::GetWinSystem(), InitVisualization(), m_alreadyStarted, m_attemptedLoad, CGUIControl::m_bInvalidated, m_bitsPerSample, m_callStart, m_channels, m_instance, m_samplesPerSec, m_updateTrack, CGUIControl::MarkDirtyRegion(), CGUIControl::Process(), and UpdateTrack().
Render()
void CGUIVisualisationControl::Render () override virtual
Reimplemented from CGUIControl.
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), m_alreadyStarted, CGUIControl::m_height, m_instance, CGUIControl::m_posX, CGUIControl::m_posY, CGUIControl::m_width, CGUIControl::Render(), and CGraphicContext::SetViewPort().
SetPreset()
void CGUIVisualisationControl::SetPreset (int idx)
References m_alreadyStarted, and m_instance.
Referenced by CGUIDialogVisualisationPresetList::OnSelect().
UpdateTrack()
void CGUIVisualisationControl::UpdateTrack ()
References KODI_ADDON_VISUALIZATION_TRACK::album, KODI_ADDON_VISUALIZATION_TRACK::albumArtist, KODI_ADDON_VISUALIZATION_TRACK::artist, KODI_ADDON_VISUALIZATION_TRACK::comment, KODI_ADDON_VISUALIZATION_TRACK::discNumber, KODI_ADDON_VISUALIZATION_TRACK::duration, KODI_ADDON_VISUALIZATION_TRACK::genre, CGUIInfoManager::GetCurrentSongTag(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, KODI_ADDON_VISUALIZATION_TRACK::lyrics, m_albumThumb, m_alreadyStarted, m_instance, MUSICPLAYER_COVER, KODI_ADDON_VISUALIZATION_TRACK::rating, KODI_ADDON_VISUALIZATION_TRACK::title, KODI_ADDON_VISUALIZATION_TRACK::trackNumber, CSpecialProtocol::TranslatePath(), WINDOW_INVALID, and KODI_ADDON_VISUALIZATION_TRACK::year.
Referenced by Process().
UpdateVisibility()
void CGUIVisualisationControl::UpdateVisibility (const CGUIListItem * item = nullptr) override virtual
Reimplemented from CGUIControl.
References FreeResources(), CGUIControl::IsVisible(), m_attemptedLoad, and CGUIControl::UpdateVisibility().
Member Data Documentation
m_albumThumb
std::string CGUIVisualisationControl::m_albumThumb private
track information
Referenced by UpdateTrack().
m_alreadyStarted
bool CGUIVisualisationControl::m_alreadyStarted {false} private
Referenced by DeInitVisualization(), GetActivePreset(), GetActivePresetName(), GetPresetList(), HasPresets(), InitVisualization(), IsLocked(), OnAction(), OnAudioData(), OnMessage(), Process(), Render(), SetPreset(), and UpdateTrack().
m_attemptedLoad
bool CGUIVisualisationControl::m_attemptedLoad {false} private
Referenced by DeInitVisualization(), Process(), and UpdateVisibility().
m_bitsPerSample
int CGUIVisualisationControl::m_bitsPerSample private
Referenced by OnInitialize(), and Process().
m_callStart
bool CGUIVisualisationControl::m_callStart {false} private
Referenced by OnInitialize(), and Process().
m_channels
int CGUIVisualisationControl::m_channels private
Referenced by OnInitialize(), and Process().
m_instance
std::unique_ptr<KODI::ADDONS::CVisualization> CGUIVisualisationControl::m_instance private
Referenced by CreateBuffers(), DeInitVisualization(), GetActivePreset(), GetActivePresetName(), GetPresetList(), HasPresets(), InitVisualization(), IsLocked(), Name(), OnAction(), OnAudioData(), Process(), Render(), SetPreset(), and UpdateTrack().
m_name
std::string CGUIVisualisationControl::m_name private
To add-on sended name
m_numBuffers
unsigned int CGUIVisualisationControl::m_numBuffers private
Number of Audio buffers
Referenced by ClearBuffers(), CreateBuffers(), and OnAudioData().
m_presets
std::vector<std::string> CGUIVisualisationControl::m_presets private
cached preset list
m_presetsPath
std::string CGUIVisualisationControl::m_presetsPath private
To add-on sended preset path
m_profilePath
std::string CGUIVisualisationControl::m_profilePath private
To add-on sended profile path
m_samplesPerSec
int CGUIVisualisationControl::m_samplesPerSec private
Referenced by OnInitialize(), and Process().
m_updateTrack
bool CGUIVisualisationControl::m_updateTrack {false} private
Referenced by OnMessage(), and Process().
m_vecBuffers
std::list<std::unique_ptr<CAudioBuffer> > CGUIVisualisationControl::m_vecBuffers private
Referenced by ClearBuffers(), and OnAudioData().
The documentation for this class was generated from the following files:
GUIVisualisationControl.h
GUIVisualisationControl.cpp