Kodi Documentation: KODI::RETRO::CLinearMemoryStream Class Reference
KODI::RETRO::CLinearMemoryStream Class Reference abstract
#include <LinearMemoryStream.h>
Public Member Functions
CLinearMemoryStream ()
~CLinearMemoryStream () override=default
void Init (size_t frameSize, uint64_t maxFrameCount) override
Initialize memory stream.
void Reset () override
Free any resources used by this stream.
size_t FrameSize () const override
Return the frame size passed to Init()
uint64_t MaxFrameCount () const override
Return the current max frame count.
void SetMaxFrameCount (uint64_t maxFrameCount) override
Update the max frame count.
uint8_t * BeginFrame () override
void SubmitFrame () override
Indicate that a frame of size FrameSize() has been written to the location returned from BeginFrame()
const uint8_t * CurrentFrame () const override
Get a pointer to the current frame.
uint64_t FutureFramesAvailable () const override
Return the number of frames ahead of the current frame.
uint64_t AdvanceFrames (uint64_t frameCount) override
Seek ahead the specified number of frames.
uint64_t PastFramesAvailable () const override=0
Return the number of frames behind the current frame.
uint64_t RewindFrames (uint64_t frameCount) override=0
Seek backwards the specified number of frames.
uint64_t GetFrameCounter () const override
Get the total number of frames played until the current frame.
void SetFrameCounter (uint64_t frameCount) override
Set the total number of frames played until the current frame.
Public Member Functions inherited from KODI::RETRO::IMemoryStream
virtual ~IMemoryStream ()=default
Protected Member Functions
virtual void SubmitFrameInternal ()=0
virtual void CullPastFrames (uint64_t frameCount)=0
uint64_t BufferSize () const
Protected Attributes
size_t m_paddedFrameSize
uint64_t m_maxFrames
std::unique_ptr< uint32_t[]> m_currentFrame
std::unique_ptr< uint32_t[]> m_nextFrame
bool m_bHasCurrentFrame
bool m_bHasNextFrame
uint64_t m_currentFrameHistory
Private Attributes
size_t m_frameSize
Constructor & Destructor Documentation
CLinearMemoryStream()
CLinearMemoryStream::CLinearMemoryStream ()
References Reset().
~CLinearMemoryStream()
KODI::RETRO::CLinearMemoryStream::~CLinearMemoryStream () override default
Member Function Documentation
AdvanceFrames()
uint64_t KODI::RETRO::CLinearMemoryStream::AdvanceFrames (uint64_t frameCount) inline override virtual
Seek ahead the specified number of frames.
Returns
The number of frames advanced
Implements KODI::RETRO::IMemoryStream.
BeginFrame()
uint8_t * CLinearMemoryStream::BeginFrame () override virtual
\ brief Get a pointer to which FrameSize() bytes can be written
The buffer exposed by this function is passed to the game client, which fills it with a serialization of its current state.
Implements KODI::RETRO::IMemoryStream.
References m_bHasCurrentFrame, m_currentFrame, m_nextFrame, and m_paddedFrameSize.
BufferSize()
uint64_t CLinearMemoryStream::BufferSize () const protected
References m_bHasCurrentFrame, and PastFramesAvailable().
Referenced by SetMaxFrameCount().
CullPastFrames()
virtual void KODI::RETRO::CLinearMemoryStream::CullPastFrames (uint64_t frameCount) protected pure virtual
Implemented in KODI::RETRO::CDeltaPairMemoryStream.
Referenced by SetMaxFrameCount().
CurrentFrame()
const uint8_t * CLinearMemoryStream::CurrentFrame () const override virtual
Get a pointer to the current frame.
This function must have no side effects. The pointer is valid until the stream is modified.
Returns
A buffer of size FrameSize(), or nullptr if the stream is empty
Implements KODI::RETRO::IMemoryStream.
References m_bHasCurrentFrame, and m_currentFrame.
FrameSize()
size_t KODI::RETRO::CLinearMemoryStream::FrameSize () const inline override virtual
Return the frame size passed to Init()
Implements KODI::RETRO::IMemoryStream.
References m_frameSize.
FutureFramesAvailable()
uint64_t KODI::RETRO::CLinearMemoryStream::FutureFramesAvailable () const inline override virtual
Return the number of frames ahead of the current frame.
If the stream supports forward seeking, frames that are passed over during a "rewind" operation can be recovered again.
Implements KODI::RETRO::IMemoryStream.
GetFrameCounter()
uint64_t KODI::RETRO::CLinearMemoryStream::GetFrameCounter () const inline override virtual
Get the total number of frames played until the current frame.
Returns
The history of the current frame, or 0 for unknown
Implements KODI::RETRO::IMemoryStream.
References m_currentFrameHistory.
Init()
void CLinearMemoryStream::Init (size_t frameSize, uint64_t maxFrameCount) override virtual
Initialize memory stream.
Parameters
frameSize The size of the serialized memory state
maxFrameCount The maximum number of frames this stream can hold
Implements KODI::RETRO::IMemoryStream.
References m_frameSize, m_maxFrames, m_paddedFrameSize, PAD_TO_CEIL, and Reset().
MaxFrameCount()
uint64_t KODI::RETRO::CLinearMemoryStream::MaxFrameCount () const inline override virtual
Return the current max frame count.
Implements KODI::RETRO::IMemoryStream.
References m_maxFrames.
Referenced by KODI::RETRO::CDeltaPairMemoryStream::SubmitFrameInternal().
PastFramesAvailable()
uint64_t KODI::RETRO::CLinearMemoryStream::PastFramesAvailable () const override pure virtual
Return the number of frames behind the current frame.
Implements KODI::RETRO::IMemoryStream.
Implemented in KODI::RETRO::CDeltaPairMemoryStream.
Referenced by BufferSize().
Reset()
void CLinearMemoryStream::Reset () override virtual
Free any resources used by this stream.
Implements KODI::RETRO::IMemoryStream.
References m_bHasCurrentFrame, m_bHasNextFrame, m_currentFrame, m_currentFrameHistory, m_frameSize, m_maxFrames, m_nextFrame, and m_paddedFrameSize.
Referenced by CLinearMemoryStream(), Init(), KODI::RETRO::CDeltaPairMemoryStream::Reset(), and SetMaxFrameCount().
RewindFrames()
uint64_t KODI::RETRO::CLinearMemoryStream::RewindFrames (uint64_t frameCount) override pure virtual
Seek backwards the specified number of frames.
Returns
The number of frames rewound
Implements KODI::RETRO::IMemoryStream.
Implemented in KODI::RETRO::CDeltaPairMemoryStream.
SetFrameCounter()
void KODI::RETRO::CLinearMemoryStream::SetFrameCounter (uint64_t frameCount) inline override virtual
Set the total number of frames played until the current frame.
Parameters
frameCount The history of the current frame
Implements KODI::RETRO::IMemoryStream.
References m_currentFrameHistory.
SetMaxFrameCount()
void CLinearMemoryStream::SetMaxFrameCount (uint64_t maxFrameCount) override virtual
Update the max frame count.
Old frames may be deleted if the max frame count is reduced.
Implements KODI::RETRO::IMemoryStream.
References BufferSize(), CullPastFrames(), m_maxFrames, and Reset().
SubmitFrame()
void CLinearMemoryStream::SubmitFrame () override virtual
Indicate that a frame of size FrameSize() has been written to the location returned from BeginFrame()
Implements KODI::RETRO::IMemoryStream.
References m_bHasCurrentFrame, m_bHasNextFrame, and SubmitFrameInternal().
SubmitFrameInternal()
virtual void KODI::RETRO::CLinearMemoryStream::SubmitFrameInternal () protected pure virtual
Implemented in KODI::RETRO::CDeltaPairMemoryStream.
Referenced by SubmitFrame().
Member Data Documentation
m_bHasCurrentFrame
bool KODI::RETRO::CLinearMemoryStream::m_bHasCurrentFrame protected
Referenced by BeginFrame(), BufferSize(), CurrentFrame(), Reset(), and SubmitFrame().
m_bHasNextFrame
bool KODI::RETRO::CLinearMemoryStream::m_bHasNextFrame protected
Referenced by Reset(), SubmitFrame(), and KODI::RETRO::CDeltaPairMemoryStream::SubmitFrameInternal().
m_currentFrame
std::unique_ptr<uint32_t[]> KODI::RETRO::CLinearMemoryStream::m_currentFrame protected
Simple double-buffering. After XORing the two states, the next becomes the current, and the current becomes a buffer for the next call to CGameClient::Serialize().
Referenced by BeginFrame(), CurrentFrame(), Reset(), KODI::RETRO::CDeltaPairMemoryStream::RewindFrames(), and KODI::RETRO::CDeltaPairMemoryStream::SubmitFrameInternal().
m_currentFrameHistory
uint64_t KODI::RETRO::CLinearMemoryStream::m_currentFrameHistory protected
Referenced by GetFrameCounter(), Reset(), KODI::RETRO::CDeltaPairMemoryStream::RewindFrames(), SetFrameCounter(), and KODI::RETRO::CDeltaPairMemoryStream::SubmitFrameInternal().
m_frameSize
size_t KODI::RETRO::CLinearMemoryStream::m_frameSize private
Referenced by FrameSize(), Init(), and Reset().
m_maxFrames
uint64_t KODI::RETRO::CLinearMemoryStream::m_maxFrames protected
Referenced by Init(), MaxFrameCount(), Reset(), and SetMaxFrameCount().
m_nextFrame
std::unique_ptr<uint32_t[]> KODI::RETRO::CLinearMemoryStream::m_nextFrame protected
Referenced by BeginFrame(), Reset(), and KODI::RETRO::CDeltaPairMemoryStream::SubmitFrameInternal().
m_paddedFrameSize
size_t KODI::RETRO::CLinearMemoryStream::m_paddedFrameSize protected
Referenced by BeginFrame(), Init(), Reset(), and KODI::RETRO::CDeltaPairMemoryStream::SubmitFrameInternal().
The documentation for this class was generated from the following files:
LinearMemoryStream.h
LinearMemoryStream.cpp