Kodi Documentation: ADDON::Interface_General Struct Reference
ADDON::Interface_General Struct Reference
Global general Add-on to Kodi callback functions.
#include <General.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static char * unknown_to_utf8 (void *kodiBase, const char *source, bool *ret, bool failOnBadChar)
callback functions from add-on to kodi
static char * get_language (void *kodiBase, int format, bool region)
static bool queue_notification (void *kodiBase, int type, const char *header, const char *message, const char *imageFile, unsigned int displayTime, bool withSound, unsigned int messageTime)
static void get_md5 (void *kodiBase, const char *text, char *md5)
static char * get_region (void *kodiBase, const char *id)
static void get_free_mem (void *kodiInstance, long *free, long *total, bool as_bytes)
static int get_global_idle_time (void *kodiBase)
static bool is_addon_avilable (void *kodiBase, const char *id, char **version, bool *enabled)
static void kodi_version (void *kodiBase, char **compile_name, int *major, int *minor, char **revision, char **tag, char **tagversion)
static char * get_current_skin_id (void *kodiBase)
static bool change_keyboard_layout (void *kodiBase, char **layout_name)
static bool get_keyboard_layout (void *kodiBase, char **layout_name, int modifier_key, AddonKeyboardKeyTable *c_layout)
Detailed Description
Global general Add-on to Kodi callback functions.
To hold general functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/General.h"
Member Function Documentation
change_keyboard_layout()
bool ADDON::Interface_General::change_keyboard_layout (void * kodiBase, char ** layout_name) static
References CServiceBroker::GetKeyboardLayoutManager(), KODI::KEYBOARD::CKeyboardLayout::GetName(), CServiceBroker::GetSettingsComponent(), layouts, CLog::Log(), LOGERROR, CSettings::SETTING_LOCALE_ACTIVEKEYBOARDLAYOUT, and CSettings::SETTING_LOCALE_KEYBOARDLAYOUTS.
Referenced by Init().
DeInit()
void ADDON::Interface_General::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_Addon::kodi, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_Base::DeInitInterface().
get_current_skin_id()
char * ADDON::Interface_General::get_current_skin_id (void * kodiBase) static
References CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, and CSettings::SETTING_LOOKANDFEEL_SKIN.
Referenced by Init().
get_free_mem()
void ADDON::Interface_General::get_free_mem (void * kodiInstance, long * free, long * total, bool as_bytes) static
References KODI::MEMORY::MemoryStatus::availPhys, KODI::MEMORY::GetMemoryStatus(), CLog::Log(), LOGERROR, and KODI::MEMORY::MemoryStatus::totalPhys.
Referenced by Init().
get_global_idle_time()
int ADDON::Interface_General::get_global_idle_time (void * kodiBase) static
References CServiceBroker::GetAppComponents(), CApplicationPowerHandling::GlobalIdleTime(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_keyboard_layout()
bool ADDON::Interface_General::get_keyboard_layout (void * kodiBase, char ** layout_name, int modifier_key, AddonKeyboardKeyTable * c_layout) static
References KODI::KEYBOARD::CKeyboardLayout::GetCharAt(), CServiceBroker::GetKeyboardLayoutManager(), KODI::KEYBOARD::CKeyboardLayout::GetName(), CServiceBroker::GetSettingsComponent(), AddonKeyboardKeyTable::keys, label, CLog::Log(), LOGERROR, KODI::KEYBOARD::CKeyboardLayout::ModifierKeyNone, KODI::KEYBOARD::CKeyboardLayout::ModifierKeyShift, KODI::KEYBOARD::CKeyboardLayout::ModifierKeySymbol, CSettings::SETTING_LOCALE_ACTIVEKEYBOARDLAYOUT, STD_KB_BUTTONS_MAX_ROWS, STD_KB_BUTTONS_PER_ROW, STD_KB_MODIFIER_KEY_SHIFT, and STD_KB_MODIFIER_KEY_SYMBOL.
Referenced by Init().
get_language()
char * ADDON::Interface_General::get_language (void * kodiBase, int format, bool region) static
References CLangCodeExpander::ConvertToISO6391(), CLangCodeExpander::ConvertToISO6392B(), g_LangCodeExpander, g_langInfo, LANG_FMT_ENGLISH_NAME, LANG_FMT_ISO_639_1, LANG_FMT_ISO_639_2, CLog::Log(), and LOGERROR.
Referenced by Init().
get_md5()
void ADDON::Interface_General::get_md5 (void * kodiBase, const char * text, char * md5) static
References CLog::Log(), LOGERROR, and text.
Referenced by Init().
get_region()
char * ADDON::Interface_General::get_region (void * kodiBase, const char * id) static
References g_langInfo, CLog::Log(), LOGERROR, MeridiemSymbolAM, MeridiemSymbolPM, and ADDON::CAddon::Name().
Referenced by Init().
Init()
void ADDON::Interface_General::Init (AddonGlobalInterface * addonInterface) static
References change_keyboard_layout(), AddonToKodiFuncTable_kodi::change_keyboard_layout, get_current_skin_id(), AddonToKodiFuncTable_kodi::get_current_skin_id, get_free_mem(), AddonToKodiFuncTable_kodi::get_free_mem, get_global_idle_time(), AddonToKodiFuncTable_kodi::get_global_idle_time, get_keyboard_layout(), AddonToKodiFuncTable_kodi::get_keyboard_layout, get_language(), AddonToKodiFuncTable_kodi::get_language, get_md5(), AddonToKodiFuncTable_kodi::get_md5, get_region(), AddonToKodiFuncTable_kodi::get_region, is_addon_avilable(), AddonToKodiFuncTable_kodi::is_addon_avilable, AddonToKodiFuncTable_Addon::kodi, kodi_version(), AddonToKodiFuncTable_kodi::kodi_version, queue_notification(), AddonToKodiFuncTable_kodi::queue_notification, AddonGlobalInterface::toKodi, unknown_to_utf8(), and AddonToKodiFuncTable_kodi::unknown_to_utf8.
Referenced by ADDON::Interface_Base::InitInterface().
is_addon_avilable()
bool ADDON::Interface_General::is_addon_avilable (void * kodiBase, const char * id, char ** version, bool * enabled) static
References ADDON::CHOICE_NO, CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::IsAddonDisabled(), CLog::Log(), and LOGERROR.
Referenced by Init().
kodi_version()
void ADDON::Interface_General::kodi_version (void * kodiBase, char ** compile_name, int * major, int * minor, char ** revision, char ** tag, char ** tagversion) static
References CCompileInfo::GetAppName(), CCompileInfo::GetMajor(), CCompileInfo::GetMinor(), CCompileInfo::GetSCMID(), CCompileInfo::GetSuffix(), CLog::Log(), and LOGERROR.
Referenced by Init().
queue_notification()
bool ADDON::Interface_General::queue_notification (void * kodiBase, int type, const char * header, const char * message, const char * imageFile, unsigned int displayTime, bool withSound, unsigned int messageTime) static
References CGUIDialogKaiToast::Error, CGUIDialogKaiToast::Info, CLog::Log(), LOGDEBUG, LOGERROR, ADDON::CAddon::Name(), QUEUE_OWN_STYLE, CGUIDialogKaiToast::QueueNotification(), and CGUIDialogKaiToast::Warning.
Referenced by Init().
unknown_to_utf8()
char * ADDON::Interface_General::unknown_to_utf8 (void * kodiBase, const char * source, bool * ret, bool failOnBadChar) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References g_charsetConverter, CLog::Log(), and LOGERROR.
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/General.h
General.cpp