Kodi Documentation: KODI::GUILIB::GUIINFO::CPlayerGUIInfo Class Reference
KODI::GUILIB::GUIINFO::CPlayerGUIInfo Class Reference
#include <PlayerGUIInfo.h>
Public Member Functions
CPlayerGUIInfo ()
~CPlayerGUIInfo () override
CEventStream< PlayerShowInfoChangedEvent > & Events ()
bool InitCurrentItem (CFileItem *item) override
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) const override
Get a GUIInfoManager label string.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager integer value.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager bool value.
void SetShowTime (bool showtime)
void SetShowInfo (bool showinfo)
bool GetShowInfo () const
bool ToggleShowInfo ()
Public Member Functions inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
CGUIInfoProvider ()=default
~CGUIInfoProvider () override=default
bool GetFallbackLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) override
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo) override
Set new audio/video stream info data.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::IGUIInfoProvider
virtual ~IGUIInfoProvider ()=default
Private Member Functions
int GetTotalPlayTime () const
int GetPlayTime () const
int GetPlayTimeRemaining () const
float GetSeekPercent () const
std::string GetCurrentPlayTime (TIME_FORMAT format) const
std::string GetCurrentPlayTimeRemaining (TIME_FORMAT format) const
std::string GetDuration (TIME_FORMAT format) const
std::string GetCurrentSeekTime (TIME_FORMAT format) const
std::string GetSeekTime (TIME_FORMAT format) const
std::string GetContentRanges (int iInfo) const
std::vector< std::pair< float, float > > GetEditList (const CDataCacheCore &data, std::time_t duration) const
std::vector< std::pair< float, float > > GetCuts (const CDataCacheCore &data, std::time_t duration) const
std::vector< std::pair< float, float > > GetSceneMarkers (const CDataCacheCore &data, std::time_t duration) const
std::vector< std::pair< float, float > > GetChapters (const CDataCacheCore &data, std::time_t duration) const
Private Attributes
std::unique_ptr< CFileItem > m_currentItem
std::atomic_bool m_playerShowTime {false}
std::atomic_bool m_playerShowInfo {false}
const std::shared_ptr< CApplicationPlayer > m_appPlayer
const std::shared_ptr< CApplicationVolumeHandling > m_appVolume
CEventSource< PlayerShowInfoChangedEvent > m_events
Additional Inherited Members
Protected Attributes inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
VideoStreamInfo m_videoInfo
AudioStreamInfo m_audioInfo
SubtitleStreamInfo m_subtitleInfo
Constructor & Destructor Documentation
CPlayerGUIInfo()
CPlayerGUIInfo::CPlayerGUIInfo ()
~CPlayerGUIInfo()
CPlayerGUIInfo::~CPlayerGUIInfo () override default
Member Function Documentation
Events()
CEventStream< PlayerShowInfoChangedEvent > & KODI::GUILIB::GUIINFO::CPlayerGUIInfo::Events () inline
References m_events.
Referenced by PVR::CPVRGUIChannelNavigator::SubscribeToShowInfoEventStream().
GetBool()
bool CPlayerGUIInfo::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager bool value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References KODI::PLAYLIST::ALL, CVariant::asInteger(), CVariant::asInteger32(), g_application, KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CServiceBroker::GetDataCacheCore(), CFileItem::GetDynPath(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CServiceBroker::GetPlaylistPlayer(), CGUIListItem::GetProperty(), KODI::PLAYLIST::CPlayListPlayer::GetRepeat(), CDataCacheCore::GetSceneMarkers(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), CDataCacheCore::HasPerformedSeek(), CGUIListItem::HasProperty(), CResolutionUtils::HasWhitelist(), CGUIDialog::IsDialogRunning(), CGUIListItem::IsFileItem(), CDataCacheCore::IsFrameAdvance(), CGraphicContext::IsFullScreenRoot(), URIUtils::IsInternetStream(), CFileItem::IsPath(), KODI::PLAYLIST::CPlayListPlayer::IsShuffled(), CDataCacheCore::IsVideoHwDecoder(), LISTITEM_ISPLAYING, m_appPlayer, m_appVolume, m_currentItem, m_playerShowInfo, m_playerShowTime, KODI::PLAYLIST::ONE, PLAYER_CACHING, PLAYER_CAN_PAUSE, PLAYER_CAN_SEEK, PLAYER_FORWARDING, PLAYER_FORWARDING_16x, PLAYER_FORWARDING_2x, PLAYER_FORWARDING_32x, PLAYER_FORWARDING_4x, PLAYER_FORWARDING_8x, PLAYER_FRAMEADVANCE, PLAYER_HAS_AUDIO, PLAYER_HAS_GAME, PLAYER_HAS_MEDIA, PLAYER_HAS_PROGRAMS, PLAYER_HAS_RESOLUTIONS, PLAYER_HAS_SCENE_MARKERS, PLAYER_HAS_VIDEO, PLAYER_HASDURATION, PLAYER_HASPERFORMEDSEEK, PLAYER_IS_EXTERNAL, PLAYER_IS_REMOTE, PLAYER_IS_TEMPO, PLAYER_ISINTERNETSTREAM, PLAYER_MUTED, PLAYER_PASSTHROUGH, PLAYER_PAUSED, PLAYER_PLAYING, PLAYER_PROCESS_VIDEOHWDECODER, PLAYER_REWINDING, PLAYER_REWINDING_16x, PLAYER_REWINDING_2x, PLAYER_REWINDING_32x, PLAYER_REWINDING_4x, PLAYER_REWINDING_8x, PLAYER_SEEKBAR, PLAYER_SEEKING, PLAYER_SHOWINFO, PLAYER_SHOWTIME, PLAYER_SUPPORTS_TEMPO, PLAYLIST_ISRANDOM, PLAYLIST_ISREPEAT, PLAYLIST_ISREPEATONE, KODI::PLAYLIST::TYPE_NONE, value, CApplicationVolumeHandling::VOLUME_MINIMUM, and WINDOW_DIALOG_SEEK_BAR.
GetChapters()
std::vector< std::pair< float, float > > CPlayerGUIInfo::GetChapters (const CDataCacheCore & data, std::time_t duration) const private
References data().
Referenced by GetContentRanges().
GetContentRanges()
std::string CPlayerGUIInfo::GetContentRanges (int iInfo) const private
References data(), GetChapters(), GetCuts(), CServiceBroker::GetDataCacheCore(), GetEditList(), GetSceneMarkers(), int64_t(), CLog::Log(), LOGERROR, max, min, PLAYER_CHAPTERS, PLAYER_CUTS, PLAYER_EDITLIST, PLAYER_SCENE_MARKERS, and values.
Referenced by GetLabel().
GetCurrentPlayTime()
std::string CPlayerGUIInfo::GetCurrentPlayTime (TIME_FORMAT format) const private
References GetPlayTime(), GetTotalPlayTime(), TIME_FORMAT_GUESS, and TIME_FORMAT_HH_MM_SS.
Referenced by GetLabel().
GetCurrentPlayTimeRemaining()
std::string CPlayerGUIInfo::GetCurrentPlayTimeRemaining (TIME_FORMAT format) const private
References GetPlayTimeRemaining(), GetTotalPlayTime(), TIME_FORMAT_GUESS, and TIME_FORMAT_HH_MM_SS.
Referenced by GetLabel().
GetCurrentSeekTime()
std::string CPlayerGUIInfo::GetCurrentSeekTime (TIME_FORMAT format) const private
References g_application, GetTotalPlayTime(), m_appPlayer, TIME_FORMAT_GUESS, and TIME_FORMAT_HH_MM_SS.
Referenced by GetLabel().
GetCuts()
std::vector< std::pair< float, float > > CPlayerGUIInfo::GetCuts (const CDataCacheCore & data, std::time_t duration) const private
References data().
Referenced by GetContentRanges().
GetDuration()
std::string CPlayerGUIInfo::GetDuration (TIME_FORMAT format) const private
References GetTotalPlayTime(), TIME_FORMAT_GUESS, and TIME_FORMAT_HH_MM_SS.
Referenced by GetLabel().
GetEditList()
std::vector< std::pair< float, float > > CPlayerGUIInfo::GetEditList (const CDataCacheCore & data, std::time_t duration) const private
References data().
Referenced by GetContentRanges().
GetInt()
bool CPlayerGUIInfo::GetInt (int & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager integer value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References g_application, GetSeekPercent(), m_appPlayer, m_appVolume, PLAYER_AUDIO_DELAY, PLAYER_CACHELEVEL, PLAYER_CHAPTER, PLAYER_CHAPTERCOUNT, PLAYER_PROGRESS, PLAYER_PROGRESS_CACHE, PLAYER_SEEKBAR, PLAYER_SUBTITLE_DELAY, PLAYER_VOLUME, and value.
GetLabel()
bool CPlayerGUIInfo::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) const override virtual
Get a GUIInfoManager label string.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References g_application, CGUIListItem::GetArt(), CDataCacheCore::GetAudioChannels(), CDataCacheCore::GetAudioDecoderName(), GetContentRanges(), CDateTime::GetCurrentDateTime(), GetCurrentPlayTime(), GetCurrentPlayTimeRemaining(), GetCurrentSeekTime(), CServiceBroker::GetDataCacheCore(), GetDuration(), KODI::GUILIB::GUIINFO::GetFileInfoLabelValueFromPath(), CGUIListItem::GetLabel(), CFileItem::GetPath(), KODI::GUILIB::GUIINFO::GetPlaylistLabel(), GetPlayTimeRemaining(), CDataCacheCore::GetSeekOffSet(), GetSeekTime(), CUtil::GetTitleFromPath(), CDataCacheCore::GetVideoDecoderName(), CDataCacheCore::GetVideoDeintMethod(), CDataCacheCore::GetVideoPixelFormat(), CDataCacheCore::IsVideoInterlaced(), m_appPlayer, m_appVolume, CAEUtil::PercentToGain(), PLAYER_AUDIO_DELAY, PLAYER_CACHELEVEL, PLAYER_CHAPTER, PLAYER_CHAPTERCOUNT, PLAYER_CHAPTERNAME, PLAYER_CHAPTERS, PLAYER_CUTS, PLAYER_DURATION, PLAYER_EDITLIST, PLAYER_FILENAME, PLAYER_FILEPATH, PLAYER_FINISH_TIME, PLAYER_ICON, PLAYER_ITEM_ART, PLAYER_PATH, PLAYER_PLAYSPEED, PLAYER_PROCESS_AUDIOBITSPERSAMPLE, PLAYER_PROCESS_AUDIOCHANNELS, PLAYER_PROCESS_AUDIODECODER, PLAYER_PROCESS_AUDIOSAMPLERATE, PLAYER_PROCESS_DEINTMETHOD, PLAYER_PROCESS_PIXELFORMAT, PLAYER_PROCESS_VIDEODAR, PLAYER_PROCESS_VIDEODECODER, PLAYER_PROCESS_VIDEOFPS, PLAYER_PROCESS_VIDEOHEIGHT, PLAYER_PROCESS_VIDEOSCANTYPE, PLAYER_PROCESS_VIDEOWIDTH, PLAYER_PROGRESS, PLAYER_PROGRESS_CACHE, PLAYER_SCENE_MARKERS, PLAYER_SEEKNUMERIC, PLAYER_SEEKOFFSET, PLAYER_SEEKSTEPSIZE, PLAYER_SEEKTIME, PLAYER_START_TIME, PLAYER_SUBTITLE_DELAY, PLAYER_TIME, PLAYER_TIME_REMAINING, PLAYER_TIME_SPEED, PLAYER_TITLE, PLAYER_VOLUME, PLAYLIST_LENGTH, PLAYLIST_POSITION, PLAYLIST_RANDOM, PLAYLIST_REPEAT, TIME_FORMAT_GUESS, and value.
GetPlayTime()
int CPlayerGUIInfo::GetPlayTime () const private
References g_application.
Referenced by GetCurrentPlayTime(), and GetSeekPercent().
GetPlayTimeRemaining()
int CPlayerGUIInfo::GetPlayTimeRemaining () const private
References g_application, and GetTotalPlayTime().
Referenced by GetCurrentPlayTimeRemaining(), and GetLabel().
GetSceneMarkers()
std::vector< std::pair< float, float > > CPlayerGUIInfo::GetSceneMarkers (const CDataCacheCore & data, std::time_t duration) const private
References data().
Referenced by GetContentRanges().
GetSeekPercent()
float CPlayerGUIInfo::GetSeekPercent () const private
References GetPlayTime(), GetTotalPlayTime(), and m_appPlayer.
Referenced by GetInt().
GetSeekTime()
std::string CPlayerGUIInfo::GetSeekTime (TIME_FORMAT format) const private
References m_appPlayer, TIME_FORMAT_GUESS, and TIME_FORMAT_HH_MM_SS.
Referenced by GetLabel().
GetShowInfo()
bool KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetShowInfo () const inline
References m_playerShowInfo.
GetTotalPlayTime()
int CPlayerGUIInfo::GetTotalPlayTime () const private
References g_application.
Referenced by GetCurrentPlayTime(), GetCurrentPlayTimeRemaining(), GetCurrentSeekTime(), GetDuration(), GetPlayTimeRemaining(), and GetSeekPercent().
InitCurrentItem()
bool CPlayerGUIInfo::InitCurrentItem (CFileItem * item) override virtual
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by the provider, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References CFileItem::GetPath(), CLog::Log(), LOGDEBUG, m_appPlayer, and m_currentItem.
SetShowInfo()
void CPlayerGUIInfo::SetShowInfo (bool showinfo)
References m_events, and m_playerShowInfo.
Referenced by CGUIWindowVisualisation::FrameMove(), PVR::CPVRGUIChannelNavigator::HideInfo(), CGUIWindowVisualisation::OnAction(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), CGUIWindowVisualisation::OnMessage(), CGUIWindowFullScreen::OnMessage(), PVR::CPVRGUIChannelNavigator::ShowInfo(), and ToggleShowInfo().
SetShowTime()
void KODI::GUILIB::GUIINFO::CPlayerGUIInfo::SetShowTime (bool showtime) inline
References m_playerShowTime.
Referenced by CGUIWindowFullScreen::OnAction().
ToggleShowInfo()
bool CPlayerGUIInfo::ToggleShowInfo ()
References m_playerShowInfo, and SetShowInfo().
Referenced by CApplication::OnAction().
Member Data Documentation
m_appPlayer
const std::shared_ptr<CApplicationPlayer> KODI::GUILIB::GUIINFO::CPlayerGUIInfo::m_appPlayer private
Referenced by GetBool(), GetCurrentSeekTime(), GetInt(), GetLabel(), GetSeekPercent(), GetSeekTime(), and InitCurrentItem().
m_appVolume
const std::shared_ptr<CApplicationVolumeHandling> KODI::GUILIB::GUIINFO::CPlayerGUIInfo::m_appVolume private
Referenced by GetBool(), GetInt(), and GetLabel().
m_currentItem
std::unique_ptr<CFileItem> KODI::GUILIB::GUIINFO::CPlayerGUIInfo::m_currentItem private
Referenced by GetBool(), and InitCurrentItem().
m_events
CEventSource<PlayerShowInfoChangedEvent> KODI::GUILIB::GUIINFO::CPlayerGUIInfo::m_events private
Referenced by Events(), and SetShowInfo().
m_playerShowInfo
std::atomic_bool KODI::GUILIB::GUIINFO::CPlayerGUIInfo::m_playerShowInfo {false} private
Referenced by GetBool(), GetShowInfo(), SetShowInfo(), and ToggleShowInfo().
m_playerShowTime
std::atomic_bool KODI::GUILIB::GUIINFO::CPlayerGUIInfo::m_playerShowTime {false} private
Referenced by GetBool(), and SetShowTime().
The documentation for this class was generated from the following files:
PlayerGUIInfo.h
PlayerGUIInfo.cpp