Kodi Documentation: CSysfsPath Class Reference
CSysfsPath Class Reference
#include <SysfsPath.h>
Public Member Functions
CSysfsPath ()=default
CSysfsPath (const std::string &path)
~CSysfsPath ()=default
bool Exists ()
template<typename T >
std::optional< T > Get ()
template<>
std::optional< std::string > Get ()
Private Attributes
std::string m_path
Constructor & Destructor Documentation
CSysfsPath() [1/2]
CSysfsPath::CSysfsPath () default
CSysfsPath() [2/2]
CSysfsPath::CSysfsPath (const std::string & path) inline
~CSysfsPath()
CSysfsPath::~CSysfsPath () default
Member Function Documentation
Exists()
bool CSysfsPath::Exists ()
References m_path.
Referenced by TEST_F(), TEST_F(), and TEST_F().
Get() [1/2]
template<> std::optional< std::string > CSysfsPath::Get ()
References LOGERROR, m_path, and value.
Get() [2/2]
template<typename T > std::optional< T > CSysfsPath::Get () inline
References LOGERROR, m_path, and value.
Referenced by CCPUInfoLinux::CCPUInfoLinux(), CCPUInfoLinux::GetCPUFrequency(), CCPUInfoLinux::GetTemperature(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
m_path
std::string CSysfsPath::m_path private
Referenced by Exists(), and Get().
The documentation for this class was generated from the following files:
SysfsPath.h
SysfsPath.cpp