Kodi Documentation: KODI::WINDOWING::GBM Namespace Reference
KODI::WINDOWING::GBM Namespace Reference
Classes
class CDRMAtomic
class CDRMConnector
class CDRMCrtc
class CDRMEncoder
class CDRMLegacy
class CDRMObject
class CDRMPlane
class CDRMUtils
class CGBMUtils
A wrapper for gbm c classes to allow OOP and RAII.
class COffScreenModeSetting
class CVaapiProxy
class CVideoLayerBridge
class CWinSystemGbm
class CWinSystemGbmEGLContext
class CWinSystemGbmGLContext
class CWinSystemGbmGLESContext
struct drm_fb
Functions
CVaapiProxy * VaapiProxyCreate (int fd)
void VaapiProxyDelete (CVaapiProxy *proxy)
void VaapiProxyConfig (CVaapiProxy *proxy, void *eglDpy)
void VAAPIRegister (CVaapiProxy *winSystem, bool deepColor)
Function Documentation
VaapiProxyConfig()
void KODI::WINDOWING::GBM::VaapiProxyConfig (CVaapiProxy * proxy, void * eglDpy)
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem().
VaapiProxyCreate()
CVaapiProxy * KODI::WINDOWING::GBM::VaapiProxyCreate (int fd)
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem().
VaapiProxyDelete()
void KODI::WINDOWING::GBM::VaapiProxyDelete (CVaapiProxy * proxy)
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::delete_CVaapiProxy::operator()().
VAAPIRegister()
void KODI::WINDOWING::GBM::VAAPIRegister (CVaapiProxy * winSystem, bool deepColor)
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem().