Kodi Documentation: XBMCAddon::xbmcgui::InterceptorBase Class Reference
XBMCAddon::xbmcgui::InterceptorBase Class Reference abstract
#include <WindowInterceptor.h>
Public Member Functions
virtual ~InterceptorBase ()
virtual CGUIWindow * get ()=0
virtual void SetRenderOrder (int renderOrder)
virtual void setActive (bool active)
virtual bool isActive ()
Protected Member Functions
InterceptorBase ()
Static Protected Member Functions
static bool up ()
Protected Attributes
AddonClass::Ref< Window > window
Static Protected Attributes
static thread_local ref * upcallTls
Friends
class ref
Detailed Description
These two classes are closely associated with the Interceptor template below. For more detailed explanation, see that class.
Constructor & Destructor Documentation
InterceptorBase()
XBMCAddon::xbmcgui::InterceptorBase::InterceptorBase () inline protected
References upcallTls.
~InterceptorBase()
virtual XBMCAddon::xbmcgui::InterceptorBase::~InterceptorBase () inline virtual
References window.
Member Function Documentation
get()
virtual CGUIWindow * XBMCAddon::xbmcgui::InterceptorBase::get () pure virtual
Implemented in XBMCAddon::xbmcgui::ProxyExistingWindowInterceptor, XBMCAddon::xbmcgui::Interceptor< P >, and XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >.
Referenced by XBMCAddon::xbmcgui::WindowDialogMixin::close(), XBMCAddon::xbmcgui::ref::get(), XBMCAddon::xbmcgui::WindowDialogMixin::OnAction(), XBMCAddon::xbmcgui::Window::OnDeinitWindow(), XBMCAddon::xbmcgui::ref::operator->(), XBMCAddon::xbmcgui::Window::setWindow(), and XBMCAddon::xbmcgui::WindowDialogMixin::show().
isActive()
virtual bool XBMCAddon::xbmcgui::InterceptorBase::isActive () inline virtual
Reimplemented in XBMCAddon::xbmcgui::Interceptor< P >, and XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >.
Referenced by XBMCAddon::xbmcgui::WindowDialogMixin::IsDialogRunning().
setActive()
virtual void XBMCAddon::xbmcgui::InterceptorBase::setActive (bool active) inline virtual
Reimplemented in XBMCAddon::xbmcgui::Interceptor< P >, and XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >.
Referenced by XBMCAddon::xbmcgui::WindowDialogMixin::OnAction().
SetRenderOrder()
virtual void XBMCAddon::xbmcgui::InterceptorBase::SetRenderOrder (int renderOrder) inline virtual
Reimplemented in XBMCAddon::xbmcgui::Interceptor< P >, and XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >.
Referenced by XBMCAddon::xbmcgui::WindowXMLDialog::LoadXML(), and XBMCAddon::xbmcgui::WindowDialog::WindowDialog().
up()
static bool XBMCAddon::xbmcgui::InterceptorBase::up () inline static protected
Calling up ONCE resets the upcall to to false. The reason is that when a call is recursive we cannot assume the ref has cleared the flag. so ...
ref(window)->UpCall()
during the context of 'UpCall' it's possible that another call will be made back on the window from the xbmc core side (this happens in sometimes in OnMessage). In that case, if upcall is still 'true', than the call will wrongly proceed back to the xbmc core side rather than to the Addon API side.
References upcallTls.
Referenced by XBMCAddon::xbmcgui::Interceptor< P >::OnAction(), XBMCAddon::xbmcgui::Interceptor< P >::OnBack(), XBMCAddon::xbmcgui::Interceptor< P >::OnDeinitWindow(), and XBMCAddon::xbmcgui::Interceptor< P >::OnMessage().
Friends And Related Symbol Documentation
ref
friend class ref friend
Member Data Documentation
upcallTls
thread_local ref * XBMCAddon::xbmcgui::InterceptorBase::upcallTls static protected
Referenced by InterceptorBase(), XBMCAddon::xbmcgui::ref::ref(), up(), and XBMCAddon::xbmcgui::ref::~ref().
window
AddonClass::Ref<Window> XBMCAddon::xbmcgui::InterceptorBase::window protected
Referenced by XBMCAddon::xbmcgui::Interceptor< P >::Interceptor(), XBMCAddon::xbmcgui::Interceptor< P >::Interceptor(), and ~InterceptorBase().
The documentation for this class was generated from the following files:
WindowInterceptor.h
interfaces/legacy/Window.cpp