Kodi Documentation: anonymous_namespace{WindowDecorator.cpp} Namespace Reference
anonymous_namespace{WindowDecorator.cpp} Namespace Reference
Functions
CRectInt SurfaceGeometry (SurfaceIndex type, CSizeInt mainSurfaceSize)
CRectInt SurfaceOpaqueRegion (SurfaceIndex type, CSizeInt mainSurfaceSize)
CRectInt SurfaceWindowRegion (SurfaceIndex type, CSizeInt mainSurfaceSize)
CSizeInt DecorationSize ()
std::size_t MemoryBytesForSize (CSizeInt windowSurfaceSize, int scale)
std::size_t PositionInBuffer (CWindowDecorator::Buffer &buffer, CPointInt position)
void DrawHorizontalLine (CWindowDecorator::Buffer &buffer, std::uint32_t color, CPointInt position, int length)
void DrawLineWithStride (CWindowDecorator::Buffer &buffer, std::uint32_t color, CPointInt position, int length, int stride)
void DrawVerticalLine (CWindowDecorator::Buffer &buffer, std::uint32_t color, CPointInt position, int length)
void DrawRectangle (CWindowDecorator::Buffer &buffer, std::uint32_t color, CRectInt rect)
void FillRectangle (CWindowDecorator::Buffer &buffer, std::uint32_t color, CRectInt rect)
void DrawHorizontalLine (CWindowDecorator::Surface &surface, std::uint32_t color, CPointInt position, int length)
void DrawAngledLine (CWindowDecorator::Surface &surface, std::uint32_t color, CPointInt position, int length, int stride)
void DrawVerticalLine (CWindowDecorator::Surface &surface, std::uint32_t color, CPointInt position, int length)
void DrawRectangle (CWindowDecorator::Surface &surface, std::uint32_t color, CRectInt rect)
void FillRectangle (CWindowDecorator::Surface &surface, std::uint32_t color, CRectInt rect)
void DrawButton (CWindowDecorator::Surface &surface, std::uint32_t lineColor, CRectInt rect, bool hover)
wayland::shell_surface_resize ResizeEdgeForPosition (SurfaceIndex surface, CSizeInt surfaceSize, CPointInt position)
std::string CursorForResizeEdge (wayland::shell_surface_resize edge)
template<typename T , typename InstanceProviderT >
bool HandleCapabilityChange (const wayland::seat_capability &caps, const wayland::seat_capability &cap, T &proxy, InstanceProviderT instanceProvider)
Variables
constexpr int BYTES_PER_PIXEL {4}
Bytes per pixel in shm storage.
constexpr int VISIBLE_BORDER_WIDTH {5}
Width of the visible border around the whole window.
constexpr int RESIZE_BORDER_WIDTH {10}
Width of the invisible border around the whole window for easier resizing.
constexpr int BORDER_WIDTH {VISIBLE_BORDER_WIDTH + RESIZE_BORDER_WIDTH}
Total width of the border around the window.
constexpr int TOP_BAR_HEIGHT {33}
Height of the top bar.
constexpr int RESIZE_MAX_CORNER_DISTANCE {BORDER_WIDTH}
Maximum distance from the window corner to consider position valid for resize.
constexpr int BUTTONS_EDGE_DISTANCE {6}
Distance of buttons from edges of the top bar.
constexpr int BUTTON_INNER_SEPARATION {4}
Distance from button inner edge to button content.
constexpr int BUTTON_SIZE {21}
Button size.
constexpr std::uint32_t TRANSPARENT {0x00000000u}
constexpr std::uint32_t BORDER_COLOR {0xFF000000u}
constexpr std::uint32_t BUTTON_COLOR_ACTIVE {0xFFFFFFFFu}
constexpr std::uint32_t BUTTON_COLOR_INACTIVE {0xFF777777u}
constexpr std::uint32_t BUTTON_HOVER_COLOR {0xFF555555u}
Function Documentation
CursorForResizeEdge()
std::string anonymous_namespace{WindowDecorator.cpp}::CursorForResizeEdge (wayland::shell_surface_resize edge)
Get name for resize cursor according to xdg cursor-spec
References edge.
DecorationSize()
CSizeInt anonymous_namespace{WindowDecorator.cpp}::DecorationSize ()
Full size of decorations to be added to the main surface size
References TOP_BAR_HEIGHT, and VISIBLE_BORDER_WIDTH.
DrawAngledLine()
void anonymous_namespace{WindowDecorator.cpp}::DrawAngledLine (CWindowDecorator::Surface & surface, std::uint32_t color, CPointInt position, int length, int stride)
References KODI::WINDOWING::WAYLAND::CWindowDecorator::Surface::buffer, color, DrawLineWithStride(), KODI::WINDOWING::WAYLAND::CWindowDecorator::Surface::scale, KODI::WINDOWING::WAYLAND::CWindowDecorator::Buffer::size, and CSizeGen< T >::Width().
Referenced by DrawVerticalLine().
DrawButton()
void anonymous_namespace{WindowDecorator.cpp}::DrawButton (CWindowDecorator::Surface & surface, std::uint32_t lineColor, CRectInt rect, bool hover)
References BUTTON_HOVER_COLOR, DrawRectangle(), and FillRectangle().
DrawHorizontalLine() [1/2]
void anonymous_namespace{WindowDecorator.cpp}::DrawHorizontalLine (CWindowDecorator::Buffer & buffer, std::uint32_t color, CPointInt position, int length)
References color, Endian_SwapLE32, and PositionInBuffer().
Referenced by DrawHorizontalLine(), DrawRectangle(), and FillRectangle().
DrawHorizontalLine() [2/2]
void anonymous_namespace{WindowDecorator.cpp}::DrawHorizontalLine (CWindowDecorator::Surface & surface, std::uint32_t color, CPointInt position, int length)
References KODI::WINDOWING::WAYLAND::CWindowDecorator::Surface::buffer, color, DrawHorizontalLine(), and KODI::WINDOWING::WAYLAND::CWindowDecorator::Surface::scale.
DrawLineWithStride()
void anonymous_namespace{WindowDecorator.cpp}::DrawLineWithStride (CWindowDecorator::Buffer & buffer, std::uint32_t color, CPointInt position, int length, int stride)
References BYTES_PER_PIXEL, color, Endian_SwapLE32, and PositionInBuffer().
Referenced by DrawAngledLine(), and DrawVerticalLine().
DrawRectangle() [1/2]
void anonymous_namespace{WindowDecorator.cpp}::DrawRectangle (CWindowDecorator::Buffer & buffer, std::uint32_t color, CRectInt rect)
Draw rectangle inside the specified buffer coordinates
References color, DrawHorizontalLine(), DrawVerticalLine(), CRectGen< T >::Height(), CRectGen< T >::P1(), and CRectGen< T >::Width().
Referenced by DrawButton(), and DrawRectangle().
DrawRectangle() [2/2]
void anonymous_namespace{WindowDecorator.cpp}::DrawRectangle (CWindowDecorator::Surface & surface, std::uint32_t color, CRectInt rect)
Draw rectangle inside the specified surface coordinates
References KODI::WINDOWING::WAYLAND::CWindowDecorator::Surface::buffer, color, DrawRectangle(), CRectGen< T >::P2(), and KODI::WINDOWING::WAYLAND::CWindowDecorator::Surface::scale.
DrawVerticalLine() [1/2]
void anonymous_namespace{WindowDecorator.cpp}::DrawVerticalLine (CWindowDecorator::Buffer & buffer, std::uint32_t color, CPointInt position, int length)
References color, and DrawLineWithStride().
Referenced by DrawRectangle().
DrawVerticalLine() [2/2]
void anonymous_namespace{WindowDecorator.cpp}::DrawVerticalLine (CWindowDecorator::Surface & surface, std::uint32_t color, CPointInt position, int length)
References color, and DrawAngledLine().
FillRectangle() [1/2]
void anonymous_namespace{WindowDecorator.cpp}::FillRectangle (CWindowDecorator::Buffer & buffer, std::uint32_t color, CRectInt rect)
References color, DrawHorizontalLine(), CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by DrawButton(), and FillRectangle().
FillRectangle() [2/2]
void anonymous_namespace{WindowDecorator.cpp}::FillRectangle (CWindowDecorator::Surface & surface, std::uint32_t color, CRectInt rect)
References KODI::WINDOWING::WAYLAND::CWindowDecorator::Surface::buffer, color, FillRectangle(), and KODI::WINDOWING::WAYLAND::CWindowDecorator::Surface::scale.
HandleCapabilityChange()
template<typename T , typename InstanceProviderT > bool anonymous_namespace{WindowDecorator.cpp}::HandleCapabilityChange (const wayland::seat_capability & caps, const wayland::seat_capability & cap, T & proxy, InstanceProviderT instanceProvider)
MemoryBytesForSize()
std::size_t anonymous_namespace{WindowDecorator.cpp}::MemoryBytesForSize (CSizeInt windowSurfaceSize, int scale)
References CRectGen< T >::Area(), BYTES_PER_PIXEL, KODI::WINDOWING::WAYLAND::SURFACE_BOTTOM, KODI::WINDOWING::WAYLAND::SURFACE_LEFT, KODI::WINDOWING::WAYLAND::SURFACE_RIGHT, KODI::WINDOWING::WAYLAND::SURFACE_TOP, and SurfaceGeometry().
PositionInBuffer()
std::size_t anonymous_namespace{WindowDecorator.cpp}::PositionInBuffer (CWindowDecorator::Buffer & buffer, CPointInt position)
References BYTES_PER_PIXEL, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by DrawHorizontalLine(), and DrawLineWithStride().
ResizeEdgeForPosition()
wayland::shell_surface_resize anonymous_namespace{WindowDecorator.cpp}::ResizeEdgeForPosition (SurfaceIndex surface, CSizeInt surfaceSize, CPointInt position)
References CSizeGen< T >::Height(), RESIZE_MAX_CORNER_DISTANCE, KODI::WINDOWING::WAYLAND::SURFACE_BOTTOM, KODI::WINDOWING::WAYLAND::SURFACE_LEFT, KODI::WINDOWING::WAYLAND::SURFACE_RIGHT, KODI::WINDOWING::WAYLAND::SURFACE_TOP, CSizeGen< T >::Width(), CPointGen< T >::x, and CPointGen< T >::y.
SurfaceGeometry()
CRectInt anonymous_namespace{WindowDecorator.cpp}::SurfaceGeometry (SurfaceIndex type, CSizeInt mainSurfaceSize)
References BORDER_WIDTH, CSizeGen< T >::Height(), KODI::WINDOWING::WAYLAND::SURFACE_BOTTOM, KODI::WINDOWING::WAYLAND::SURFACE_LEFT, KODI::WINDOWING::WAYLAND::SURFACE_RIGHT, KODI::WINDOWING::WAYLAND::SURFACE_TOP, TOP_BAR_HEIGHT, and CSizeGen< T >::Width().
Referenced by MemoryBytesForSize(), and SurfaceOpaqueRegion().
SurfaceOpaqueRegion()
CRectInt anonymous_namespace{WindowDecorator.cpp}::SurfaceOpaqueRegion (SurfaceIndex type, CSizeInt mainSurfaceSize)
References RESIZE_BORDER_WIDTH, KODI::WINDOWING::WAYLAND::SURFACE_BOTTOM, KODI::WINDOWING::WAYLAND::SURFACE_LEFT, KODI::WINDOWING::WAYLAND::SURFACE_RIGHT, KODI::WINDOWING::WAYLAND::SURFACE_TOP, SurfaceGeometry(), and CRectGen< T >::ToSize().
Referenced by SurfaceWindowRegion().
SurfaceWindowRegion()
CRectInt anonymous_namespace{WindowDecorator.cpp}::SurfaceWindowRegion (SurfaceIndex type, CSizeInt mainSurfaceSize)
References SurfaceOpaqueRegion().
Variable Documentation
BORDER_COLOR
constexpr std::uint32_t anonymous_namespace{WindowDecorator.cpp}::BORDER_COLOR {0xFF000000u} constexpr
BORDER_WIDTH
constexpr int anonymous_namespace{WindowDecorator.cpp}::BORDER_WIDTH {VISIBLE_BORDER_WIDTH + RESIZE_BORDER_WIDTH} constexpr
Total width of the border around the window.
Referenced by SurfaceGeometry().
BUTTON_COLOR_ACTIVE
constexpr std::uint32_t anonymous_namespace{WindowDecorator.cpp}::BUTTON_COLOR_ACTIVE {0xFFFFFFFFu} constexpr
BUTTON_COLOR_INACTIVE
constexpr std::uint32_t anonymous_namespace{WindowDecorator.cpp}::BUTTON_COLOR_INACTIVE {0xFF777777u} constexpr
BUTTON_HOVER_COLOR
constexpr std::uint32_t anonymous_namespace{WindowDecorator.cpp}::BUTTON_HOVER_COLOR {0xFF555555u} constexpr
Referenced by DrawButton().
BUTTON_INNER_SEPARATION
constexpr int anonymous_namespace{WindowDecorator.cpp}::BUTTON_INNER_SEPARATION {4} constexpr
Distance from button inner edge to button content.
BUTTON_SIZE
constexpr int anonymous_namespace{WindowDecorator.cpp}::BUTTON_SIZE {21} constexpr
Button size.
BUTTONS_EDGE_DISTANCE
constexpr int anonymous_namespace{WindowDecorator.cpp}::BUTTONS_EDGE_DISTANCE {6} constexpr
Distance of buttons from edges of the top bar.
BYTES_PER_PIXEL
constexpr int anonymous_namespace{WindowDecorator.cpp}::BYTES_PER_PIXEL {4} constexpr
Bytes per pixel in shm storage.
Referenced by DrawLineWithStride(), MemoryBytesForSize(), and PositionInBuffer().
RESIZE_BORDER_WIDTH
constexpr int anonymous_namespace{WindowDecorator.cpp}::RESIZE_BORDER_WIDTH {10} constexpr
Width of the invisible border around the whole window for easier resizing.
Referenced by SurfaceOpaqueRegion().
RESIZE_MAX_CORNER_DISTANCE
constexpr int anonymous_namespace{WindowDecorator.cpp}::RESIZE_MAX_CORNER_DISTANCE {BORDER_WIDTH} constexpr
Maximum distance from the window corner to consider position valid for resize.
Referenced by ResizeEdgeForPosition().
TOP_BAR_HEIGHT
constexpr int anonymous_namespace{WindowDecorator.cpp}::TOP_BAR_HEIGHT {33} constexpr
Height of the top bar.
Referenced by DecorationSize(), and SurfaceGeometry().
TRANSPARENT
constexpr std::uint32_t anonymous_namespace{WindowDecorator.cpp}::TRANSPARENT {0x00000000u} constexpr
VISIBLE_BORDER_WIDTH
constexpr int anonymous_namespace{WindowDecorator.cpp}::VISIBLE_BORDER_WIDTH {5} constexpr
Width of the visible border around the whole window.
Referenced by DecorationSize().