Kodi Documentation: XFILE::COverrideFile Class Reference
XFILE::COverrideFile Class Reference abstract
#include <OverrideFile.h>
Public Member Functions
COverrideFile (bool writable)
~COverrideFile () override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int Stat (struct __stat64 *buffer) override
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
bool Delete (const CURL &url) override
bool Rename (const CURL &url, const CURL &urlnew) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
void Close () override
int64_t GetPosition () override
int64_t GetLength () override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool SetHidden (const CURL &url, bool hidden)
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Protected Member Functions
virtual std::string TranslatePath (const CURL &url)=0
Protected Attributes
CFile m_file
bool m_writable
Constructor & Destructor Documentation
COverrideFile()
COverrideFile::COverrideFile (bool writable) explicit
~COverrideFile()
COverrideFile::~COverrideFile () override
References Close().
Member Function Documentation
Close()
void COverrideFile::Close () override virtual
Implements XFILE::IFile.
References XFILE::CFile::Close(), and m_file.
Referenced by ~COverrideFile().
Delete()
bool COverrideFile::Delete (const CURL & url) override virtual
Reimplemented from XFILE::IFile.
Reimplemented in XFILE::CPluginFile.
References XFILE::CFile::Delete(), m_file, m_writable, and TranslatePath().
Exists()
bool COverrideFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
Reimplemented in XFILE::CPluginFile.
References XFILE::CFile::Exists(), m_file, and TranslatePath().
GetLength()
int64_t COverrideFile::GetLength () override virtual
Implements XFILE::IFile.
References XFILE::CFile::GetLength(), and m_file.
GetPosition()
int64_t COverrideFile::GetPosition () override virtual
Implements XFILE::IFile.
References XFILE::CFile::GetPosition(), and m_file.
Open()
bool COverrideFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
Reimplemented in XFILE::CPluginFile.
References m_file, XFILE::CFile::Open(), and TranslatePath().
OpenForWrite()
bool COverrideFile::OpenForWrite (const CURL & url, bool bOverWrite = false) override virtual
Reimplemented from XFILE::IFile.
Reimplemented in XFILE::CPluginFile.
References m_file, m_writable, XFILE::CFile::OpenForWrite(), and TranslatePath().
Read()
ssize_t COverrideFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References m_file, and XFILE::CFile::Read().
Rename()
bool COverrideFile::Rename (const CURL & url, const CURL & urlnew) override virtual
Reimplemented from XFILE::IFile.
Reimplemented in XFILE::CPluginFile.
References m_file, m_writable, XFILE::CFile::Rename(), and TranslatePath().
Seek()
int64_t COverrideFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
References m_file, and XFILE::CFile::Seek().
Stat() [1/2]
int COverrideFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
Reimplemented in XFILE::CPluginFile.
References m_file, XFILE::CFile::Stat(), and TranslatePath().
Stat() [2/2]
int COverrideFile::Stat (struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about currently open file For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Reimplemented from XFILE::IFile.
Reimplemented in XFILE::CPluginFile.
References m_file, and XFILE::CFile::Stat().
TranslatePath()
virtual std::string XFILE::COverrideFile::TranslatePath (const CURL & url) protected pure virtual
Implemented in XFILE::CBlurayFile, XFILE::CMultiPathFile, XFILE::CPluginFile, XFILE::CResourceFile, XFILE::CSpecialProtocolFile, and XFILE::CVideoDatabaseFile.
Referenced by Delete(), Exists(), Open(), OpenForWrite(), Rename(), and Stat().
Write()
ssize_t COverrideFile::Write (const void * bufPtr, size_t bufSize) override virtual
Attempt to write bufSize bytes from buffer bufPtr into currently opened file.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully written bytes if any bytes were written, zero if no bytes were written and no detectable error occur, -1 in case of any explicit error
Reimplemented from XFILE::IFile.
References m_file, m_writable, and XFILE::CFile::Write().
Member Data Documentation
m_file
CFile XFILE::COverrideFile::m_file protected
Referenced by Close(), Delete(), Exists(), GetLength(), GetPosition(), XFILE::CMultiPathFile::Open(), Open(), OpenForWrite(), Read(), Rename(), Seek(), Stat(), Stat(), and Write().
m_writable
bool XFILE::COverrideFile::m_writable protected
Referenced by Delete(), OpenForWrite(), Rename(), and Write().
The documentation for this class was generated from the following files:
OverrideFile.h
OverrideFile.cpp