Kodi Documentation: CPtsTracker Class Reference
CPtsTracker Class Reference
#include <PTSTracker.h>
Public Member Functions
CPtsTracker ()
void Add (double pts)
void Flush ()
void ResetVFRDetection (void)
int GetPatternLength ()
double GetFrameDuration ()
double GetMaxFrameDuration (void)
double GetMinFrameDuration (void)
bool HasFullBuffer ()
bool VFRDetection (void)
Private Member Functions
double GetDiff (int diffnr)
void GetPattern (std::vector< double > &pattern)
bool CheckPattern (std::vector< double > &pattern)
double CalcFrameDuration ()
std::string GetPatternStr ()
Static Private Member Functions
static bool MatchDiff (double diff1, double diff2)
static bool MatchDifftype (int diffs1[], int diffs2[], int nrdiffs)
Private Attributes
double m_prevpts
double m_diffring [DIFFRINGSIZE]
int m_ringpos
int m_ringfill
std::vector< double > m_pattern
std::vector< double > m_lastPattern
double m_frameduration
double m_maxframeduration
double m_minframeduration
bool m_haspattern
int m_patternlength
int m_VFRCounter
int m_patternCounter
Constructor & Destructor Documentation
CPtsTracker()
CPtsTracker::CPtsTracker ()
References Flush(), and ResetVFRDetection().
Member Function Documentation
Add()
void CPtsTracker::Add (double pts)
References CalcFrameDuration(), CheckPattern(), DIFFRINGSIZE, DVD_NOPTS_VALUE, Flush(), GetDiff(), GetPattern(), GetPatternStr(), CLog::Log(), LOGDEBUG, m_diffring, m_frameduration, m_haspattern, m_lastPattern, m_pattern, m_patternCounter, m_patternlength, m_prevpts, m_ringfill, m_ringpos, and m_VFRCounter.
Referenced by CVideoPlayerVideo::OutputPicture().
CalcFrameDuration()
double CPtsTracker::CalcFrameDuration () private
References DVD_NOPTS_VALUE, m_maxframeduration, m_minframeduration, m_pattern, and CDVDCodecUtils::NormalizeFrameduration().
Referenced by Add().
CheckPattern()
bool CPtsTracker::CheckPattern (std::vector< double > & pattern) private
References m_pattern, MatchDiff(), and MAXERR.
Referenced by Add().
Flush()
void CPtsTracker::Flush ()
References DVD_NOPTS_VALUE, m_diffring, m_frameduration, m_haspattern, m_pattern, m_patternlength, m_prevpts, m_ringfill, and m_ringpos.
Referenced by Add(), CPtsTracker(), CVideoPlayerVideo::Process(), and CVideoPlayerVideo::ProcessDecoderOutput().
GetDiff()
double CPtsTracker::GetDiff (int diffnr) inline private
References DIFFRINGSIZE, m_diffring, and m_ringpos.
Referenced by Add(), and GetPattern().
GetFrameDuration()
double CPtsTracker::GetFrameDuration () inline
References m_frameduration.
Referenced by CVideoPlayerVideo::CalcFrameRate().
GetMaxFrameDuration()
double CPtsTracker::GetMaxFrameDuration (void) inline
References m_maxframeduration.
GetMinFrameDuration()
double CPtsTracker::GetMinFrameDuration (void) inline
References m_minframeduration.
Referenced by CVideoPlayerVideo::CalcFrameRate().
GetPattern()
void CPtsTracker::GetPattern (std::vector< double > & pattern) private
References DIFFRINGSIZE, GetDiff(), m_pattern, m_ringfill, MatchDiff(), and MatchDifftype().
Referenced by Add().
GetPatternLength()
int CPtsTracker::GetPatternLength () inline
References m_patternlength.
Referenced by CVideoPlayerVideo::CalcFrameRate(), and CVideoPlayerVideo::GetPlayerInfo().
GetPatternStr()
std::string CPtsTracker::GetPatternStr () private
References m_pattern.
Referenced by Add().
HasFullBuffer()
bool CPtsTracker::HasFullBuffer () inline
References DIFFRINGSIZE, and m_ringfill.
Referenced by CVideoPlayerVideo::CalcFrameRate().
MatchDiff()
bool CPtsTracker::MatchDiff (double diff1, double diff2) inline static private
References MAXERR.
Referenced by CheckPattern(), and GetPattern().
MatchDifftype()
bool CPtsTracker::MatchDifftype (int diffs1[], int diffs2[], int nrdiffs) inline static private
Referenced by GetPattern().
ResetVFRDetection()
void CPtsTracker::ResetVFRDetection (void)
References DVD_NOPTS_VALUE, m_lastPattern, m_maxframeduration, m_minframeduration, m_patternCounter, and m_VFRCounter.
Referenced by CPtsTracker(), and CVideoPlayerVideo::OpenStream().
VFRDetection()
bool CPtsTracker::VFRDetection (void) inline
References m_patternCounter, m_VFRCounter, VFR_DETECTION_THRESHOLD, and VFR_PATTERN_THRESHOLD.
Referenced by CVideoPlayerVideo::CalcFrameRate().
Member Data Documentation
m_diffring
double CPtsTracker::m_diffring[DIFFRINGSIZE] private
Referenced by Add(), Flush(), and GetDiff().
m_frameduration
double CPtsTracker::m_frameduration private
Referenced by Add(), Flush(), and GetFrameDuration().
m_haspattern
bool CPtsTracker::m_haspattern private
Referenced by Add(), and Flush().
m_lastPattern
std::vector<double> CPtsTracker::m_lastPattern private
Referenced by Add(), and ResetVFRDetection().
m_maxframeduration
double CPtsTracker::m_maxframeduration private
Referenced by CalcFrameDuration(), GetMaxFrameDuration(), and ResetVFRDetection().
m_minframeduration
double CPtsTracker::m_minframeduration private
Referenced by CalcFrameDuration(), GetMinFrameDuration(), and ResetVFRDetection().
m_pattern
std::vector<double> CPtsTracker::m_pattern private
Referenced by Add(), CalcFrameDuration(), CheckPattern(), Flush(), GetPattern(), and GetPatternStr().
m_patternCounter
int CPtsTracker::m_patternCounter private
Referenced by Add(), ResetVFRDetection(), and VFRDetection().
m_patternlength
int CPtsTracker::m_patternlength private
Referenced by Add(), Flush(), and GetPatternLength().
m_prevpts
double CPtsTracker::m_prevpts private
Referenced by Add(), and Flush().
m_ringfill
int CPtsTracker::m_ringfill private
Referenced by Add(), Flush(), GetPattern(), and HasFullBuffer().
m_ringpos
int CPtsTracker::m_ringpos private
Referenced by Add(), Flush(), and GetDiff().
m_VFRCounter
int CPtsTracker::m_VFRCounter private
Referenced by Add(), ResetVFRDetection(), and VFRDetection().
The documentation for this class was generated from the following files:
PTSTracker.h
PTSTracker.cpp