Kodi Documentation: KODI::RETRO::CRenderBufferOpenGL Class Reference
KODI::RETRO::CRenderBufferOpenGL Class Reference
#include <RenderBufferOpenGL.h>
Public Member Functions
CRenderBufferOpenGL (GLuint pixeltype, GLuint internalformat, GLuint pixelformat, GLuint bpp)
~CRenderBufferOpenGL () override
bool UploadTexture () override
GLuint TextureID () const
Public Member Functions inherited from KODI::RETRO::CRenderBufferSysMem
CRenderBufferSysMem ()=default
~CRenderBufferSysMem () override=default
bool Allocate (AVPixelFormat format, unsigned int width, unsigned int height) override
size_t GetFrameSize () const override
uint8_t * GetMemory () override
Public Member Functions inherited from KODI::RETRO::CBaseRenderBuffer
CBaseRenderBuffer ()
~CBaseRenderBuffer () override=default
void Acquire () override
void Acquire (std::shared_ptr< IRenderBufferPool > pool) override
void Release () override
IRenderBufferPool * GetPool () override
DataAccess GetMemoryAccess () const override
DataAlignment GetMemoryAlignment () const override
Public Member Functions inherited from KODI::RETRO::IRenderBuffer
virtual ~IRenderBuffer ()=default
virtual void Update ()
virtual void ReleaseMemory ()
virtual void BindToUnit (unsigned int unit)
virtual void SetHeader (void *header)
AVPixelFormat GetFormat () const
unsigned int GetWidth () const
unsigned int GetHeight () const
bool IsLoaded () const
void SetLoaded (bool bLoaded)
bool IsRendered () const
void SetRendered (bool bRendered)
unsigned int GetRotation () const
void SetRotation (unsigned int rotationDegCCW)
Private Member Functions
void CreateTexture ()
void DeleteTexture ()
Private Attributes
const GLuint m_pixeltype
const GLuint m_internalformat
const GLuint m_pixelformat
const GLuint m_bpp
const GLenum m_textureTarget = GL_TEXTURE_2D
GLuint m_textureId = 0
Additional Inherited Members
Static Public Member Functions inherited from KODI::RETRO::CRenderBufferSysMem
static size_t GetBufferSize (AVPixelFormat format, unsigned int width, unsigned int height)
Protected Attributes inherited from KODI::RETRO::CRenderBufferSysMem
std::vector< uint8_t > m_data
Protected Attributes inherited from KODI::RETRO::CBaseRenderBuffer
std::atomic_int m_refCount
std::shared_ptr< IRenderBufferPool > m_pool
Protected Attributes inherited from KODI::RETRO::IRenderBuffer
AVPixelFormat m_format = AV_PIX_FMT_NONE
unsigned int m_width = 0
unsigned int m_height = 0
bool m_bLoaded = false
bool m_bRendered = false
unsigned int m_rotationDegCCW = 0
Constructor & Destructor Documentation
CRenderBufferOpenGL()
CRenderBufferOpenGL::CRenderBufferOpenGL (GLuint pixeltype, GLuint internalformat, GLuint pixelformat, GLuint bpp)
~CRenderBufferOpenGL()
CRenderBufferOpenGL::~CRenderBufferOpenGL () override
References DeleteTexture().
Member Function Documentation
CreateTexture()
void CRenderBufferOpenGL::CreateTexture () private
References KODI::RETRO::IRenderBuffer::m_height, m_internalformat, m_pixelformat, m_pixeltype, m_textureId, m_textureTarget, and KODI::RETRO::IRenderBuffer::m_width.
Referenced by UploadTexture().
DeleteTexture()
void CRenderBufferOpenGL::DeleteTexture () private
References m_textureId.
Referenced by ~CRenderBufferOpenGL().
TextureID()
GLuint KODI::RETRO::CRenderBufferOpenGL::TextureID () const inline
References m_textureId.
Referenced by KODI::RETRO::CRPRendererOpenGL::Render().
UploadTexture()
bool CRenderBufferOpenGL::UploadTexture () override virtual
Todo:
This is subject to change: We want to use PBO's instead of glTexSubImage2D! This code has been borrowed from OpenGL ES in order to remove GL dependencies on GLES.
Implements KODI::RETRO::IRenderBuffer.
References CreateTexture(), KODI::RETRO::CRenderBufferSysMem::GetFrameSize(), m_bpp, KODI::RETRO::CRenderBufferSysMem::m_data, KODI::RETRO::IRenderBuffer::m_height, m_pixelformat, m_pixeltype, m_textureId, m_textureTarget, and KODI::RETRO::IRenderBuffer::m_width.
Member Data Documentation
m_bpp
const GLuint KODI::RETRO::CRenderBufferOpenGL::m_bpp private
Referenced by UploadTexture().
m_internalformat
const GLuint KODI::RETRO::CRenderBufferOpenGL::m_internalformat private
Referenced by CreateTexture().
m_pixelformat
const GLuint KODI::RETRO::CRenderBufferOpenGL::m_pixelformat private
Referenced by CreateTexture(), and UploadTexture().
m_pixeltype
const GLuint KODI::RETRO::CRenderBufferOpenGL::m_pixeltype private
Referenced by CreateTexture(), and UploadTexture().
m_textureId
GLuint KODI::RETRO::CRenderBufferOpenGL::m_textureId = 0 private
Todo:
Referenced by CreateTexture(), DeleteTexture(), TextureID(), and UploadTexture().
m_textureTarget
const GLenum KODI::RETRO::CRenderBufferOpenGL::m_textureTarget = GL_TEXTURE_2D private
Referenced by CreateTexture(), and UploadTexture().
The documentation for this class was generated from the following files:
RenderBufferOpenGL.h
RenderBufferOpenGL.cpp