Kodi Documentation: AddonBuiltins.cpp File Reference
AddonBuiltins.cpp File Reference
#include "AddonBuiltins.h"
#include "FileItem.h"
#include "GUIPassword.h"
#include "GUIUserMessages.h"
#include "ServiceBroker.h"
#include "addons/AddonInstaller.h"
#include "addons/AddonManager.h"
#include "addons/AddonSystemSettings.h"
#include "addons/PluginSource.h"
#include "addons/RepositoryUpdater.h"
#include "addons/addoninfo/AddonInfo.h"
#include "addons/addoninfo/AddonType.h"
#include "addons/gui/GUIDialogAddonSettings.h"
#include "addons/gui/GUIWindowAddonBrowser.h"
#include "application/Application.h"
#include "filesystem/PluginDirectory.h"
#include "games/tags/GameInfoTag.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "interfaces/generic/ScriptInvocationManager.h"
#include "messaging/helpers/DialogHelper.h"
#include "playlists/PlayListTypes.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/log.h"
#include <memory>
Functions
static int InstallAddon (const std::vector< std::string > &params)
Install an addon.
static int EnableAddon (const std::vector< std::string > &params)
Enable an addon.
static int RunPlugin (const std::vector< std::string > &params)
Run a plugin.
static int RunAddon (const std::vector< std::string > &params)
Run a script, plugin or game add-on.
template<bool OnlyApple = false>
static int RunScript (const std::vector< std::string > &params)
Run a script add-on or an apple script.
static int OpenDefaultSettings (const std::vector< std::string > &params)
Open the settings for the default add-on of a given type.
static int SetDefaultAddon (const std::vector< std::string > &params)
Set the default add-on for a given type.
static int AddonSettings (const std::vector< std::string > &params)
Open the settings for a given add-on.
static int InstallFromZip (const std::vector< std::string > &params)
Open the settings for a given add-on.
static int StopScript (const std::vector< std::string > &params)
Stop a running script.
static int UpdateRepos (const std::vector< std::string > &params)
Check add-on repositories for updates.
static int UpdateLocals (const std::vector< std::string > &params)
Check local add-on directories for updates.
Function Documentation
AddonSettings()
static int AddonSettings (const std::vector< std::string > & params) static
Open the settings for a given add-on.
Parameters
params The parameters.
params[0] = The add-on ID.
References CServiceBroker::GetAddonMgr(), and CGUIDialogAddonSettings::ShowForAddon().
Referenced by CAddonBuiltins::GetOperations().
EnableAddon()
static int EnableAddon (const std::vector< std::string > & params) static
Enable an addon.
Parameters
params The parameters.
params[0] = add-on id.
References CGUIPassword::CheckMenuLock(), ADDON::CAddonMgr::EnableAddon(), g_passwordManager, CServiceBroker::GetAddonMgr(), KODI::MESSAGING::HELPERS::ShowYesNoDialogLines(), and WINDOW_ADDON_BROWSER.
Referenced by ADDON::CAddonInstaller::CheckDependencies(), and CAddonBuiltins::GetOperations().
InstallAddon()
static int InstallAddon (const std::vector< std::string > & params) static
Install an addon.
Parameters
params The parameters.
params[0] = add-on id.
References ADDON::CAddonInstaller::GetInstance(), and ADDON::CAddonInstaller::InstallModal().
Referenced by CAddonBuiltins::GetOperations().
InstallFromZip()
static int InstallFromZip (const std::vector< std::string > & params) static
Open the settings for a given add-on.
Parameters
params The parameters.
References CGUIWindowAddonBrowser::InstallFromZip().
Referenced by CAddonBuiltins::GetOperations().
OpenDefaultSettings()
static int OpenDefaultSettings (const std::vector< std::string > & params) static
Open the settings for the default add-on of a given type.
Parameters
params The parameters.
params[0] = The add-on type.
References CServiceBroker::GetGUI(), ADDON::CAddonSystemSettings::GetInstance(), CGUIComponent::GetWindowManager(), GUI_MSG_VISUALISATION_RELOAD, CGUIWindowManager::SendMessage(), CGUIDialogAddonSettings::ShowForAddon(), and ADDON::CAddonInfo::TranslateType().
Referenced by CAddonBuiltins::GetOperations().
RunAddon()
static int RunAddon (const std::vector< std::string > & params) static
Run a script, plugin or game add-on.
Parameters
params The parameters.
params[0] = add-on id. params[1] is blank for no add-on parameters or params[1] = add-on parameters in url format or params[1,...] = additional parameters in format param=value.
References ADDON::CPluginSource::AUDIO, ADDON::CPluginSource::EXECUTABLE, CBuiltins::Execute(), KODI::UTILS::StringUtils::Format(), g_application, ADDON::CPluginSource::GAME, CServiceBroker::GetAddonMgr(), CFileItem::GetGameInfoTag(), CBuiltins::GetInstance(), ADDON::CPluginSource::IMAGE, KODI::UTILS::StringUtils::Join(), CLog::Log(), LOGERROR, KODI::GAME::CGameInfoTag::SetGameClient(), KODI::UTILS::StringUtils::StartsWith(), and ADDON::CPluginSource::VIDEO.
Referenced by CAddonBuiltins::GetOperations().
RunPlugin()
static int RunPlugin (const std::vector< std::string > & params) static
Run a plugin.
Parameters
params The parameters.
params[0] = plugin:// URL to script.
References CFileItem::GetPath(), CLog::Log(), LOGERROR, CGUIListItem::m_bIsFolder, XFILE::CPluginDirectory::RunScriptWithParams(), and CFileItem::SetPath().
Referenced by CAddonBuiltins::GetOperations().
RunScript()
template<bool OnlyApple = false> static int RunScript (const std::vector< std::string > & params) static
Run a script add-on or an apple script.
Parameters
params The parameters.
params[0] is the URL to the apple script or params[0] is the addon-ID to the script add-on or params[0] is the URL to the python script.
Set the OnlyApple template parameter to true to only attempt execution of applescripts.
References Cocoa_DoAppleScriptFile(), CScriptInvocationManager::ExecuteAsync(), CServiceBroker::GetAddonMgr(), URIUtils::GetFileName(), CScriptInvocationManager::GetInstance(), URIUtils::HasExtension(), CLog::Log(), LOGERROR, LOGWARNING, and CSpecialProtocol::TranslatePath().
Referenced by CAddonBuiltins::GetOperations().
SetDefaultAddon()
static int SetDefaultAddon (const std::vector< std::string > & params) static
Set the default add-on for a given type.
Parameters
params The parameters.
params[0] = The add-on type
References CServiceBroker::GetGUI(), ADDON::CAddonSystemSettings::GetInstance(), CGUIComponent::GetWindowManager(), GUI_MSG_VISUALISATION_RELOAD, CGUIWindowAddonBrowser::SelectAddonID(), CGUIWindowManager::SendMessage(), ADDON::CAddonSystemSettings::SetActive(), and ADDON::CAddonInfo::TranslateType().
Referenced by CAddonBuiltins::GetOperations().
StopScript()
static int StopScript (const std::vector< std::string > & params) static
Stop a running script.
Parameters
params The parameters.
params[0] = The add-on ID of the script to stop or params[0] = The URL of the script to stop.
Todo:
FIXME: This does not work for addons with multiple extension points! Are there any use for this? TODO: Fix hack in CScreenSaver::Destroy() and deprecate.
References CServiceBroker::GetAddonMgr(), CScriptInvocationManager::GetInstance(), and CScriptInvocationManager::Stop().
Referenced by CAddonBuiltins::GetOperations().
UpdateLocals()
static int UpdateLocals (const std::vector< std::string > & params) static
Check local add-on directories for updates.
Parameters
params (ignored)
References ADDON::CAddonMgr::FindAddons(), and CServiceBroker::GetAddonMgr().
Referenced by CAddonBuiltins::GetOperations().
UpdateRepos()
static int UpdateRepos (const std::vector< std::string > & params) static
Check add-on repositories for updates.
Parameters
params (ignored)
References ADDON::CRepositoryUpdater::CheckForUpdates(), and CServiceBroker::GetRepositoryUpdater().
Referenced by CAddonBuiltins::GetOperations().