Kodi Documentation: CONTEXTMENU::CFavouritesTargetResume Class Reference
CONTEXTMENU::CFavouritesTargetResume Class Reference
#include <ContextMenus.h>
Public Member Functions
std::string GetLabel (const CFileItem &item) const override
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool IsGroup () const
virtual bool HasParent () const
Member Function Documentation
Execute()
bool CFavouritesTargetResume::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References FAVOURITES_UTILS::ExecuteAction().
GetLabel()
std::string CFavouritesTargetResume::GetLabel (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References KODI::VIDEO::UTILS::GetResumeString().
IsVisible()
bool CFavouritesTargetResume::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References KODI::VIDEO::UTILS::GetItemResumeInformation(), and KODI::VIDEO::UTILS::ResumeInformation::isResumable.
The documentation for this class was generated from the following files:
favourites/ContextMenus.h
favourites/ContextMenus.cpp