Kodi Documentation: anonymous_namespace{PVRTimerInfoTag.cpp} Namespace Reference
anonymous_namespace{PVRTimerInfoTag.cpp} Namespace Reference
Functions
void AppendDay (std::string &strReturn, unsigned int iId)
int days_from_0 (int year)
int days_from_1970 (int32_t year)
int days_from_1jan (int year, int month, int day)
time_t mytimegm (struct tm *time)
Detailed Description
Todo:
CDateTime class does not handle daylight saving timezone bias correctly (and cannot easily
Function Documentation
AppendDay()
void anonymous_namespace{PVRTimerInfoTag.cpp}::AppendDay (std::string & strReturn, unsigned int iId)
References AppendDay(), g_localizeStrings, and CLocalizeStrings::Get().
Referenced by AppendDay().
days_from_0()
int anonymous_namespace{PVRTimerInfoTag.cpp}::days_from_0 (int year)
References days_from_0().
Referenced by days_from_0(), and days_from_1970().
days_from_1970()
int anonymous_namespace{PVRTimerInfoTag.cpp}::days_from_1970 (int32_t year)
References days_from_0(), and days_from_1970().
Referenced by days_from_1970(), and mytimegm().
days_from_1jan()
int anonymous_namespace{PVRTimerInfoTag.cpp}::days_from_1jan (int year, int month, int day)
References day, days_from_1jan(), and IsLeapYear.
Referenced by days_from_1jan(), and mytimegm().
mytimegm()
time_t anonymous_namespace{PVRTimerInfoTag.cpp}::mytimegm (struct tm * time)
References days_from_1970(), days_from_1jan(), and mytimegm().
Referenced by mytimegm().