Kodi Documentation: CONTEXTMENU::CEnableAddon Struct Reference
CONTEXTMENU::CEnableAddon Struct Reference
#include <ContextMenus.h>
Public Member Functions
CEnableAddon ()
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Constructor & Destructor Documentation
CEnableAddon()
CONTEXTMENU::CEnableAddon::CEnableAddon () inline
Member Function Documentation
Execute()
bool CONTEXTMENU::CEnableAddon::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References ADDON::GUI::CHelpers::DialogAddonLifecycleUseAsk(), ADDON::CAddonMgr::EnableAddon(), and CServiceBroker::GetAddonMgr().
IsVisible()
bool CONTEXTMENU::CEnableAddon::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References ADDON::CAddonMgr::CanAddonBeEnabled(), CFileItem::GetAddonInfo(), CServiceBroker::GetAddonMgr(), CFileItem::HasAddonInfo(), and ADDON::CAddonMgr::IsAddonDisabled().
The documentation for this struct was generated from the following files:
addons/ContextMenus.h
addons/ContextMenus.cpp