Kodi Documentation: JSONRPC::CXBMCOperations Class Reference
JSONRPC::CXBMCOperations Class Reference
#include <XBMCOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetInfoLabels (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetInfoBooleans (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Member Function Documentation
GetInfoBooleans()
JSONRPC_STATUS CXBMCOperations::GetInfoBooleans (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), CPowerManager::CanHibernate(), CPowerManager::CanPowerdown(), CPowerManager::CanReboot(), CPowerManager::CanSuspend(), JSONRPC::ControlPower, CServiceBroker::GetAppMessenger(), JSONRPC::IClient::GetPermissionFlags(), CServiceBroker::GetPowerManager(), JSONRPC::OK, CVariant::push_back(), CVariant::size(), and TMSG_GUI_INFOBOOL.
GetInfoLabels()
JSONRPC_STATUS CXBMCOperations::GetInfoLabels (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), CServiceBroker::GetAppMessenger(), JSONRPC::OK, CVariant::size(), and TMSG_GUI_INFOLABEL.
The documentation for this class was generated from the following files:
XBMCOperations.h
XBMCOperations.cpp