Kodi Documentation: XBPython Class Reference
XBPython Class Reference
#include <XBPython.h>
Public Member Functions
XBPython ()
~XBPython () override
void OnPlayBackEnded () override
void OnPlayBackStarted (const CFileItem &file) override
void OnAVStarted (const CFileItem &file) override
void OnAVChange () override
void OnPlayBackPaused () override
void OnPlayBackResumed () override
void OnPlayBackStopped () override
void OnPlayBackError () override
void OnPlayBackSpeedChanged (int iSpeed) override
void OnPlayBackSeek (int64_t iTime, int64_t seekOffset) override
void OnPlayBackSeekChapter (int iChapter) override
void OnQueueNextItem () override
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
void RegisterPythonPlayerCallBack (IPlayerCallback *pCallback)
void UnregisterPythonPlayerCallBack (IPlayerCallback *pCallback)
void RegisterPythonMonitorCallBack (XBMCAddon::xbmc::Monitor *pCallback)
void UnregisterPythonMonitorCallBack (XBMCAddon::xbmc::Monitor *pCallback)
void OnSettingsChanged (const std::string &strings)
void OnScreensaverActivated ()
void OnScreensaverDeactivated ()
void OnDPMSActivated ()
void OnDPMSDeactivated ()
void OnScanStarted (const std::string &library)
void OnScanFinished (const std::string &library)
void OnCleanStarted (const std::string &library)
void OnCleanFinished (const std::string &library)
void OnNotification (const std::string &sender, const std::string &method, const std::string &data)
void Process () override
void PulseGlobalEvent () override
void Uninitialize () override
bool OnScriptInitialized (ILanguageInvoker *invoker) override
void OnScriptStarted (ILanguageInvoker *invoker) override
void NotifyScriptAborting (ILanguageInvoker *invoker) override
void OnExecutionEnded (ILanguageInvoker *invoker) override
void OnScriptFinalized (ILanguageInvoker *invoker) override
ILanguageInvoker * CreateInvoker () override
bool WaitForEvent (CEvent &hEvent, unsigned int milliseconds)
Public Member Functions inherited from IPlayerCallback
virtual ~IPlayerCallback ()=default
virtual void OnPlayerCloseFile (const CFileItem &file, const CBookmark &bookmark)
virtual void RequestVideoSettings (const CFileItem &fileItem)
virtual void StoreVideoSettings (const CFileItem &fileItem, const CVideoSettings &vs)
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Public Member Functions inherited from ILanguageInvocationHandler
ILanguageInvocationHandler ()=default
virtual ~ILanguageInvocationHandler ()=default
virtual bool Initialize ()
Private Attributes
CCriticalSection m_critSection
void * m_mainThreadState {nullptr}
int m_iDllScriptCounter {0}
PyList m_vecPyList
PlayerCallbackList m_vecPlayerCallbackList
MonitorCallbackList m_vecMonitorCallbackList
CEvent m_globalEvent
PythonExtensionLibraries m_extensions
Static Private Attributes
static bool m_bInitialized = false
Constructor & Destructor Documentation
XBPython()
XBPython::XBPython ()
References CServiceBroker::GetAnnouncementManager().
~XBPython()
XBPython::~XBPython () override
References CServiceBroker::GetAnnouncementManager(), and XBMC_TRACE.
Member Function Documentation
Announce()
void XBPython::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References ANNOUNCEMENT::AnnouncementFlagToString(), ANNOUNCEMENT::AudioLibrary, data(), CServiceBroker::GetSettingsComponent(), ANNOUNCEMENT::GUI, OnCleanFinished(), OnCleanStarted(), OnDPMSActivated(), OnDPMSDeactivated(), OnNotification(), OnScanFinished(), OnScanStarted(), OnScreensaverActivated(), OnScreensaverDeactivated(), ANNOUNCEMENT::VideoLibrary, and CJSONVariantWriter::Write().
CreateInvoker()
ILanguageInvoker * XBPython::CreateInvoker () override virtual
Implements ILanguageInvocationHandler.
NotifyScriptAborting()
void XBPython::NotifyScriptAborting (ILanguageInvoker * invoker) override virtual
Reimplemented from ILanguageInvocationHandler.
References CHECK_FOR_ENTRY, ILanguageInvoker::GetId(), LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
OnAVChange()
void XBPython::OnAVChange () override virtual
Reimplemented from IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnAVChange(), and XBMC_TRACE.
Referenced by OnAVChange(), and CApplication::OnMessage().
OnAVStarted()
void XBPython::OnAVStarted (const CFileItem & file) override virtual
Reimplemented from IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnAVStarted(), and XBMC_TRACE.
Referenced by OnAVStarted(), and CApplication::OnMessage().
OnCleanFinished()
void XBPython::OnCleanFinished (const std::string & library)
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by Announce().
OnCleanStarted()
void XBPython::OnCleanStarted (const std::string & library)
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by Announce().
OnDPMSActivated()
void XBPython::OnDPMSActivated ()
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by Announce().
OnDPMSDeactivated()
void XBPython::OnDPMSDeactivated ()
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by Announce().
OnExecutionEnded()
void XBPython::OnExecutionEnded (ILanguageInvoker * invoker) override virtual
Reimplemented from ILanguageInvocationHandler.
References ILanguageInvoker::GetId(), CLog::Log(), LOGDEBUG, and m_vecPyList.
OnNotification()
void XBPython::OnNotification (const std::string & sender, const std::string & method, const std::string & data)
References CHECK_FOR_ENTRY, data(), LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by Announce().
OnPlayBackEnded()
void XBPython::OnPlayBackEnded () override virtual
Implements IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnPlayBackEnded(), and XBMC_TRACE.
Referenced by CApplication::OnMessage(), and OnPlayBackEnded().
OnPlayBackError()
void XBPython::OnPlayBackError () override virtual
Implements IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnPlayBackError(), and XBMC_TRACE.
Referenced by OnPlayBackError().
OnPlayBackPaused()
void XBPython::OnPlayBackPaused () override virtual
Reimplemented from IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnPlayBackPaused(), and XBMC_TRACE.
Referenced by CApplicationPlayerCallback::OnPlayBackPaused(), and OnPlayBackPaused().
OnPlayBackResumed()
void XBPython::OnPlayBackResumed () override virtual
Reimplemented from IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnPlayBackResumed(), and XBMC_TRACE.
Referenced by CApplicationPlayerCallback::OnPlayBackResumed(), and OnPlayBackResumed().
OnPlayBackSeek()
void XBPython::OnPlayBackSeek (int64_t iTime, int64_t seekOffset) override virtual
Reimplemented from IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnPlayBackSeek(), and XBMC_TRACE.
Referenced by CApplicationPlayerCallback::OnPlayBackSeek(), and OnPlayBackSeek().
OnPlayBackSeekChapter()
void XBPython::OnPlayBackSeekChapter (int iChapter) override virtual
Reimplemented from IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnPlayBackSeekChapter(), and XBMC_TRACE.
Referenced by CApplicationPlayerCallback::OnPlayBackSeekChapter(), and OnPlayBackSeekChapter().
OnPlayBackSpeedChanged()
void XBPython::OnPlayBackSpeedChanged (int iSpeed) override virtual
Reimplemented from IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnPlayBackSpeedChanged(), and XBMC_TRACE.
Referenced by CApplicationPlayerCallback::OnPlayBackSpeedChanged(), and OnPlayBackSpeedChanged().
OnPlayBackStarted()
void XBPython::OnPlayBackStarted (const CFileItem & file) override virtual
Implements IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnPlayBackStarted(), and XBMC_TRACE.
Referenced by CApplication::OnMessage(), and OnPlayBackStarted().
OnPlayBackStopped()
void XBPython::OnPlayBackStopped () override virtual
Implements IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnPlayBackStopped(), and XBMC_TRACE.
Referenced by CApplication::OnMessage(), and OnPlayBackStopped().
OnQueueNextItem()
void XBPython::OnQueueNextItem () override virtual
Implements IPlayerCallback.
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecPlayerCallbackList, OnQueueNextItem(), and XBMC_TRACE.
Referenced by CApplicationPlayerCallback::OnQueueNextItem(), and OnQueueNextItem().
OnScanFinished()
void XBPython::OnScanFinished (const std::string & library)
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by Announce().
OnScanStarted()
void XBPython::OnScanStarted (const std::string & library)
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by Announce().
OnScreensaverActivated()
void XBPython::OnScreensaverActivated ()
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by Announce().
OnScreensaverDeactivated()
void XBPython::OnScreensaverDeactivated ()
References CHECK_FOR_ENTRY, LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by Announce().
OnScriptFinalized()
void XBPython::OnScriptFinalized (ILanguageInvoker * invoker) override virtual
Reimplemented from ILanguageInvocationHandler.
References CLog::Log(), LOGERROR, m_critSection, m_iDllScriptCounter, and XBMC_TRACE.
OnScriptInitialized()
bool XBPython::OnScriptInitialized (ILanguageInvoker * invoker) override virtual
Reimplemented from ILanguageInvocationHandler.
References CUtil::GetFrameworksPath(), CAddonPythonInvoker::GlobalInitializeModules(), CHTTPPythonWsgiInvoker::GlobalInitializeModules(), CLog::Log(), LOGDEBUG, LOGERROR, m_bInitialized, m_critSection, m_iDllScriptCounter, m_mainThreadState, CEnvironment::putenv(), savestate, CSpecialProtocol::TranslatePath(), CCharsetConverter::utf8ToW(), and XBMC_TRACE.
OnScriptStarted()
void XBPython::OnScriptStarted (ILanguageInvoker * invoker) override virtual
Reimplemented from ILanguageInvocationHandler.
References PyElem::bDone, ILanguageInvoker::GetId(), PyElem::id, m_bInitialized, m_vecPyList, and PyElem::pyThread.
OnSettingsChanged()
void XBPython::OnSettingsChanged (const std::string & strings)
References CHECK_FOR_ENTRY, ID, LOCK_AND_COPY, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by ADDON::CAddon::SaveSettings().
Process()
void XBPython::Process () override virtual
Reimplemented from ILanguageInvocationHandler.
References LockableType< T >::hadSomethingRemoved, m_bInitialized, and m_vecPyList.
PulseGlobalEvent()
void XBPython::PulseGlobalEvent () override virtual
Reimplemented from ILanguageInvocationHandler.
References m_globalEvent, and CEvent::Set().
RegisterPythonMonitorCallBack()
void XBPython::RegisterPythonMonitorCallBack (XBMCAddon::xbmc::Monitor * pCallback)
References m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by XBMCAddon::Python::PythonLanguageHook::RegisterMonitorCallback().
RegisterPythonPlayerCallBack()
void XBPython::RegisterPythonPlayerCallBack (IPlayerCallback * pCallback)
References m_vecPlayerCallbackList, and XBMC_TRACE.
Referenced by XBMCAddon::Python::PythonLanguageHook::RegisterPlayerCallback().
Uninitialize()
void XBPython::Uninitialize () override virtual
Reimplemented from ILanguageInvocationHandler.
References CServiceBroker::GetAnnouncementManager(), LockableType< T >::hadSomethingRemoved, LOCK_AND_COPY, and m_vecPyList.
UnregisterPythonMonitorCallBack()
void XBPython::UnregisterPythonMonitorCallBack (XBMCAddon::xbmc::Monitor * pCallback)
References LockableType< T >::hadSomethingRemoved, m_vecMonitorCallbackList, and XBMC_TRACE.
Referenced by XBMCAddon::Python::PythonLanguageHook::UnregisterMonitorCallback().
UnregisterPythonPlayerCallBack()
void XBPython::UnregisterPythonPlayerCallBack (IPlayerCallback * pCallback)
References LockableType< T >::hadSomethingRemoved, m_vecPlayerCallbackList, and XBMC_TRACE.
Referenced by XBMCAddon::Python::PythonLanguageHook::UnregisterPlayerCallback().
WaitForEvent()
bool XBPython::WaitForEvent (CEvent & hEvent, unsigned int milliseconds)
References m_globalEvent, and CEvent::Reset().
Referenced by XBMCAddon::Python::PythonLanguageHook::WaitForEvent().
Member Data Documentation
m_bInitialized
bool XBPython::m_bInitialized = false static private
Referenced by OnScriptInitialized(), OnScriptStarted(), and Process().
m_critSection
CCriticalSection XBPython::m_critSection private
Referenced by OnScriptFinalized(), and OnScriptInitialized().
m_extensions
PythonExtensionLibraries XBPython::m_extensions private
m_globalEvent
CEvent XBPython::m_globalEvent private
Referenced by PulseGlobalEvent(), and WaitForEvent().
m_iDllScriptCounter
int XBPython::m_iDllScriptCounter {0} private
Referenced by OnScriptFinalized(), and OnScriptInitialized().
m_mainThreadState
void* XBPython::m_mainThreadState {nullptr} private
Referenced by OnScriptInitialized().
m_vecMonitorCallbackList
MonitorCallbackList XBPython::m_vecMonitorCallbackList private
Referenced by NotifyScriptAborting(), OnCleanFinished(), OnCleanStarted(), OnDPMSActivated(), OnDPMSDeactivated(), OnNotification(), OnScanFinished(), OnScanStarted(), OnScreensaverActivated(), OnScreensaverDeactivated(), OnSettingsChanged(), RegisterPythonMonitorCallBack(), and UnregisterPythonMonitorCallBack().
m_vecPlayerCallbackList
PlayerCallbackList XBPython::m_vecPlayerCallbackList private
Referenced by OnAVChange(), OnAVStarted(), OnPlayBackEnded(), OnPlayBackError(), OnPlayBackPaused(), OnPlayBackResumed(), OnPlayBackSeek(), OnPlayBackSeekChapter(), OnPlayBackSpeedChanged(), OnPlayBackStarted(), OnPlayBackStopped(), OnQueueNextItem(), RegisterPythonPlayerCallBack(), and UnregisterPythonPlayerCallBack().
m_vecPyList
PyList XBPython::m_vecPyList private
Referenced by OnExecutionEnded(), OnScriptStarted(), Process(), and Uninitialize().
The documentation for this class was generated from the following files:
XBPython.h
XBPython.cpp