Kodi Documentation: IInputDeviceCallbacks Class Reference
IInputDeviceCallbacks Class Reference abstract
#include <IInputDeviceCallbacks.h>
Public Member Functions
virtual ~IInputDeviceCallbacks ()=default
virtual void OnInputDeviceAdded (int deviceId)=0
virtual void OnInputDeviceChanged (int deviceId)=0
virtual void OnInputDeviceRemoved (int deviceId)=0
Protected Member Functions
IInputDeviceCallbacks ()=default
Constructor & Destructor Documentation
~IInputDeviceCallbacks()
virtual IInputDeviceCallbacks::~IInputDeviceCallbacks () virtual default
IInputDeviceCallbacks()
IInputDeviceCallbacks::IInputDeviceCallbacks () protected default
Member Function Documentation
OnInputDeviceAdded()
virtual void IInputDeviceCallbacks::OnInputDeviceAdded (int deviceId) pure virtual
Implemented in PERIPHERALS::CPeripheralBusAndroid.
Referenced by CXBMCApp::onInputDeviceAdded().
OnInputDeviceChanged()
virtual void IInputDeviceCallbacks::OnInputDeviceChanged (int deviceId) pure virtual
Implemented in PERIPHERALS::CPeripheralBusAndroid.
Referenced by CXBMCApp::onInputDeviceChanged().
OnInputDeviceRemoved()
virtual void IInputDeviceCallbacks::OnInputDeviceRemoved (int deviceId) pure virtual
Implemented in PERIPHERALS::CPeripheralBusAndroid.
Referenced by CXBMCApp::onInputDeviceRemoved().
The documentation for this class was generated from the following file:
IInputDeviceCallbacks.h