Kodi Documentation: XBMCAddon::xbmcplugin Namespace Reference
XBMCAddon::xbmcplugin Namespace Reference
Functions
bool addDirectoryItem (int handle, const String &url, const xbmcgui::ListItem *listItem, bool isFolder, int totalItems)
bool addDirectoryItems (int handle, const std::vector< Tuple< String, const XBMCAddon::xbmcgui::ListItem *, bool > > &items, int totalItems)
void endOfDirectory (int handle, bool succeeded, bool updateListing, bool cacheToDisc)
void setResolvedUrl (int handle, bool succeeded, const xbmcgui::ListItem *listItem)
void addSortMethod (int handle, int sortMethod, const String &clabelMask, const String &clabel2Mask)
String getSetting (int handle, const char *id)
void setSetting (int handle, const String &id, const String &value)
void setContent (int handle, const char *content)
void setPluginCategory (int handle, const String &category)
void setPluginFanart (int handle, const char *image, const char *color1, const char *color2, const char *color3)
void setProperty (int handle, const char *key, const String &value)
Function Documentation
addDirectoryItem()
bool XBMCAddon::xbmcplugin::addDirectoryItem (int handle, const String & url, const xbmcgui::ListItem * listItem, bool isFolder, int totalItems)
References XFILE::CPluginDirectory::AddItem(), and XBMCAddon::AddonClass::Ref< T >::get().
addDirectoryItems()
bool XBMCAddon::xbmcplugin::addDirectoryItems (int handle, const std::vector< Tuple< String, const XBMCAddon::xbmcgui::ListItem *, bool > > & items, int totalItems)
References CFileItemList::Add(), and XFILE::CPluginDirectory::AddItems().
addSortMethod()
void XBMCAddon::xbmcplugin::addSortMethod (int handle, int sortMethod, const String & clabelMask, const String & clabel2Mask)
References XFILE::CPluginDirectory::AddSortMethod(), SORT_METHOD_EPISODE, SORT_METHOD_MAX, SORT_METHOD_NONE, SORT_METHOD_PRODUCTIONCODE, and SORT_METHOD_TRACKNUM.
endOfDirectory()
void XBMCAddon::xbmcplugin::endOfDirectory (int handle, bool succeeded, bool updateListing, bool cacheToDisc)
References XFILE::CPluginDirectory::EndOfDirectory().
getSetting()
String XBMCAddon::xbmcplugin::getSetting (int handle, const char * id)
References XFILE::CPluginDirectory::GetSetting().
setContent()
void XBMCAddon::xbmcplugin::setContent (int handle, const char * content)
References XFILE::CPluginDirectory::SetContent().
setPluginCategory()
void XBMCAddon::xbmcplugin::setPluginCategory (int handle, const String & category)
References XFILE::CPluginDirectory::SetProperty().
setPluginFanart()
void XBMCAddon::xbmcplugin::setPluginFanart (int handle, const char * image, const char * color1, const char * color2, const char * color3)
References XFILE::CPluginDirectory::SetProperty().
setProperty()
void XBMCAddon::xbmcplugin::setProperty (int handle, const char * key, const String & value)
References XFILE::CPluginDirectory::SetProperty(), and value.
setResolvedUrl()
void XBMCAddon::xbmcplugin::setResolvedUrl (int handle, bool succeeded, const xbmcgui::ListItem * listItem)
References XBMCAddon::AddonClass::Ref< T >::get(), and XFILE::CPluginDirectory::SetResolvedUrl().
setSetting()
void XBMCAddon::xbmcplugin::setSetting (int handle, const String & id, const String & value)
References XFILE::CPluginDirectory::SetSetting(), and value.