Kodi Documentation: ADDON::Interface_GUIListItem Struct Reference
ADDON::Interface_GUIListItem Struct Reference
Global gui Add-on to Kodi callback functions.
#include <ListItem.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static KODI_GUI_LISTITEM_HANDLE create (KODI_HANDLE kodiBase, const char *label, const char *label2, const char *path)
callback functions from add-on to kodi
static void destroy (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
static char * get_label (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
static void set_label (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *label)
static char * get_label2 (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
static void set_label2 (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *label)
static char * get_art (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *type)
static void set_art (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *type, const char *image)
static char * get_path (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
static void set_path (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *path)
static char * get_property (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *key)
static void set_property (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char *key, const char *value)
static void select (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, bool select)
static bool is_selected (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/ListItem.h"
Member Function Documentation
create()
KODI_GUI_LISTITEM_HANDLE ADDON::Interface_GUIListItem::create (KODI_HANDLE kodiBase, const char * label, const char * label2, const char * path) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References label, CLog::Log(), and LOGERROR.
Referenced by Init().
DeInit()
void ADDON::Interface_GUIListItem::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_Addon::kodi_gui, AddonToKodiFuncTable_kodi_gui::listItem, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
destroy()
void ADDON::Interface_GUIListItem::destroy (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
get_art()
char * ADDON::Interface_GUIListItem::get_art (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char * type) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
get_label()
char * ADDON::Interface_GUIListItem::get_label (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
get_label2()
char * ADDON::Interface_GUIListItem::get_label2 (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
get_path()
char * ADDON::Interface_GUIListItem::get_path (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
get_property()
char * ADDON::Interface_GUIListItem::get_property (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char * key) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
Init()
void ADDON::Interface_GUIListItem::Init (AddonGlobalInterface * addonInterface) static
References create(), destroy(), AddonToKodiFuncTable_kodi_gui_listItem::destroy, get_art(), AddonToKodiFuncTable_kodi_gui_listItem::get_art, get_label(), AddonToKodiFuncTable_kodi_gui_listItem::get_label, get_label2(), AddonToKodiFuncTable_kodi_gui_listItem::get_label2, get_path(), AddonToKodiFuncTable_kodi_gui_listItem::get_path, get_property(), AddonToKodiFuncTable_kodi_gui_listItem::get_property, is_selected(), AddonToKodiFuncTable_kodi_gui_listItem::is_selected, AddonToKodiFuncTable_Addon::kodi_gui, AddonToKodiFuncTable_kodi_gui::listItem, AddonToKodiFuncTable_kodi_gui_listItem::select, set_art(), AddonToKodiFuncTable_kodi_gui_listItem::set_art, set_label(), AddonToKodiFuncTable_kodi_gui_listItem::set_label, set_label2(), AddonToKodiFuncTable_kodi_gui_listItem::set_label2, set_path(), AddonToKodiFuncTable_kodi_gui_listItem::set_path, set_property(), AddonToKodiFuncTable_kodi_gui_listItem::set_property, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
is_selected()
bool ADDON::Interface_GUIListItem::is_selected (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
select()
void ADDON::Interface_GUIListItem::select (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, bool select) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
set_art()
void ADDON::Interface_GUIListItem::set_art (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char * type, const char * image) static
References ADDON::CAddon::ID(), label, ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_label()
void ADDON::Interface_GUIListItem::set_label (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char * label) static
References ADDON::CAddon::ID(), label, ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_label2()
void ADDON::Interface_GUIListItem::set_label2 (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char * label) static
References ADDON::CAddon::ID(), label, ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_path()
void ADDON::Interface_GUIListItem::set_path (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char * path) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, and ADDON::Interface_GUIGeneral::unlock().
Referenced by Init().
set_property()
void ADDON::Interface_GUIListItem::set_property (KODI_HANDLE kodiBase, KODI_GUI_LISTITEM_HANDLE handle, const char * key, const char * value) static
References ADDON::CAddon::ID(), ADDON::Interface_GUIGeneral::lock(), CLog::Log(), LOGERROR, ADDON::Interface_GUIGeneral::unlock(), and value.
Referenced by Init().
The documentation for this struct was generated from the following files:
addons/interfaces/gui/ListItem.h
addons/interfaces/gui/ListItem.cpp