Kodi Documentation: CGUIInfoManager::Property Class Reference
CGUIInfoManager::Property Class Reference
class for holding information on properties
Public Member Functions
Property (const std::string &property, const std::string &parameters)
const std::string & param (unsigned int n=0) const
unsigned int num_params () const
Public Attributes
std::string name
Private Attributes
std::vector< std::string > params
Detailed Description
class for holding information on properties
Constructor & Destructor Documentation
Property()
CGUIInfoManager::Property::Property (const std::string & property, const std::string & parameters)
References params, and CUtil::SplitParams().
Member Function Documentation
num_params()
unsigned int CGUIInfoManager::Property::num_params () const
Referenced by CGUIInfoManager::TranslateListItem(), and CGUIInfoManager::TranslateSingleString().
param()
const std::string & CGUIInfoManager::Property::param (unsigned int n = 0) const
Referenced by CGUIInfoManager::TranslateListItem(), and CGUIInfoManager::TranslateSingleString().
Member Data Documentation
name
std::string CGUIInfoManager::Property::name
Referenced by CGUIInfoManager::TranslateListItem(), and CGUIInfoManager::TranslateSingleString().
params
std::vector<std::string> CGUIInfoManager::Property::params private
Referenced by Property().
The documentation for this class was generated from the following files:
GUIInfoManager.h
GUIInfoManager.cpp