Kodi Documentation: CPlayerSelectionRule Class Reference
CPlayerSelectionRule Class Reference
#include <PlayerSelectionRule.h>
Public Member Functions
CPlayerSelectionRule (TiXmlElement *rule)
virtual ~CPlayerSelectionRule ()=default
void GetPlayers (const CFileItem &item, std::vector< std::string > &validPlayers, std::vector< std::string > &players)
Private Member Functions
void Initialize (TiXmlElement *pRule)
Static Private Member Functions
static int GetTristate (const char *szValue)
static bool CompileRegExp (const std::string &str, CRegExp &regExp)
static bool MatchesRegExp (const std::string &str, CRegExp &regExp)
Private Attributes
std::string m_name
int m_tAudio
int m_tVideo
int m_tGame
int m_tInternetStream
int m_tRemote
int m_tBD
int m_tDVD
int m_tDVDFile
int m_tDiscImage
std::string m_protocols
std::string m_fileTypes
std::string m_mimeTypes
std::string m_fileName
bool m_bStreamDetails
std::string m_audioCodec
std::string m_audioChannels
std::string m_videoCodec
std::string m_videoResolution
std::string m_videoAspect
std::string m_hdrType
std::string m_playerName
std::vector< std::unique_ptr< CPlayerSelectionRule > > vecSubRules
Constructor & Destructor Documentation
CPlayerSelectionRule()
CPlayerSelectionRule::CPlayerSelectionRule (TiXmlElement * rule) explicit
References Initialize().
~CPlayerSelectionRule()
virtual CPlayerSelectionRule::~CPlayerSelectionRule () virtual default
Member Function Documentation
CompileRegExp()
bool CPlayerSelectionRule::CompileRegExp (const std::string & str, CRegExp & regExp) static private
References CRegExp::RegComp().
Referenced by GetPlayers().
GetPlayers()
void CPlayerSelectionRule::GetPlayers (const CFileItem & item, std::vector< std::string > & validPlayers, std::vector< std::string > & players)
References CRegExp::autoUtf8, CompileRegExp(), CStreamDetails::GetAudioChannels(), CStreamDetails::GetAudioCodec(), CFileItem::GetDynPath(), CURL::GetFileType(), CFileItem::GetMimeType(), CURL::GetProtocol(), CStreamDetails::GetVideoAspect(), CStreamDetails::GetVideoCodec(), CStreamDetails::GetVideoHdrType(), CStreamDetails::GetVideoHeight(), CFileItem::GetVideoInfoTag(), CStreamDetails::GetVideoWidth(), CVideoInfoTag::HasStreamDetails(), CFileItem::HasVideoInfoTag(), KODI::MUSIC::IsAudio(), CFileItem::IsDiscImage(), CFileItem::IsDVD(), CFileItem::IsGame(), KODI::NETWORK::IsInternetStream(), CFileItem::IsOnDVD(), KODI::NETWORK::IsRemote(), CLog::Log(), LOGDEBUG, m_audioChannels, m_audioCodec, m_bStreamDetails, m_fileName, m_fileTypes, m_hdrType, m_mimeTypes, m_name, m_playerName, m_protocols, CVideoInfoTag::m_streamDetails, m_tAudio, m_tBD, m_tDiscImage, m_tDVD, m_tDVDFile, m_tGame, m_tInternetStream, m_tRemote, m_tVideo, m_videoAspect, m_videoCodec, m_videoResolution, MatchesRegExp(), vecSubRules, CStreamDetails::VideoAspectToAspectDescription(), and CStreamDetails::VideoDimsToResolutionDescription().
GetTristate()
int CPlayerSelectionRule::GetTristate (const char * szValue) static private
Referenced by Initialize().
Initialize()
void CPlayerSelectionRule::Initialize (TiXmlElement * pRule) private
References XMLUtils::GetAttribute(), CServiceBroker::GetSettingsComponent(), GetTristate(), CLog::Log(), LOGDEBUG, LOGWARNING, m_audioChannels, m_audioCodec, m_bStreamDetails, m_fileName, m_fileTypes, m_hdrType, m_mimeTypes, m_name, m_playerName, m_protocols, m_tAudio, m_tBD, m_tDiscImage, m_tDVD, m_tDVDFile, m_tGame, m_tInternetStream, m_tRemote, m_tVideo, m_videoAspect, m_videoCodec, m_videoResolution, CSettings::SETTING_MYVIDEOS_EXTRACTFLAGS, and vecSubRules.
Referenced by CPlayerSelectionRule().
MatchesRegExp()
bool CPlayerSelectionRule::MatchesRegExp (const std::string & str, CRegExp & regExp) static private
References CRegExp::RegFind().
Referenced by GetPlayers().
Member Data Documentation
m_audioChannels
std::string CPlayerSelectionRule::m_audioChannels private
Referenced by GetPlayers(), and Initialize().
m_audioCodec
std::string CPlayerSelectionRule::m_audioCodec private
Referenced by GetPlayers(), and Initialize().
m_bStreamDetails
bool CPlayerSelectionRule::m_bStreamDetails private
Referenced by GetPlayers(), and Initialize().
m_fileName
std::string CPlayerSelectionRule::m_fileName private
Referenced by GetPlayers(), and Initialize().
m_fileTypes
std::string CPlayerSelectionRule::m_fileTypes private
Referenced by GetPlayers(), and Initialize().
m_hdrType
std::string CPlayerSelectionRule::m_hdrType private
Referenced by GetPlayers(), and Initialize().
m_mimeTypes
std::string CPlayerSelectionRule::m_mimeTypes private
Referenced by GetPlayers(), and Initialize().
m_name
std::string CPlayerSelectionRule::m_name private
Referenced by GetPlayers(), and Initialize().
m_playerName
std::string CPlayerSelectionRule::m_playerName private
Referenced by GetPlayers(), and Initialize().
m_protocols
std::string CPlayerSelectionRule::m_protocols private
Referenced by GetPlayers(), and Initialize().
m_tAudio
int CPlayerSelectionRule::m_tAudio private
Referenced by GetPlayers(), and Initialize().
m_tBD
int CPlayerSelectionRule::m_tBD private
Referenced by GetPlayers(), and Initialize().
m_tDiscImage
int CPlayerSelectionRule::m_tDiscImage private
Referenced by GetPlayers(), and Initialize().
m_tDVD
int CPlayerSelectionRule::m_tDVD private
Referenced by GetPlayers(), and Initialize().
m_tDVDFile
int CPlayerSelectionRule::m_tDVDFile private
Referenced by GetPlayers(), and Initialize().
m_tGame
int CPlayerSelectionRule::m_tGame private
Referenced by GetPlayers(), and Initialize().
m_tInternetStream
int CPlayerSelectionRule::m_tInternetStream private
Referenced by GetPlayers(), and Initialize().
m_tRemote
int CPlayerSelectionRule::m_tRemote private
Referenced by GetPlayers(), and Initialize().
m_tVideo
int CPlayerSelectionRule::m_tVideo private
Referenced by GetPlayers(), and Initialize().
m_videoAspect
std::string CPlayerSelectionRule::m_videoAspect private
Referenced by GetPlayers(), and Initialize().
m_videoCodec
std::string CPlayerSelectionRule::m_videoCodec private
Referenced by GetPlayers(), and Initialize().
m_videoResolution
std::string CPlayerSelectionRule::m_videoResolution private
Referenced by GetPlayers(), and Initialize().
vecSubRules
std::vector<std::unique_ptr<CPlayerSelectionRule> > CPlayerSelectionRule::vecSubRules private
Referenced by GetPlayers(), and Initialize().
The documentation for this class was generated from the following files:
PlayerSelectionRule.h
PlayerSelectionRule.cpp