Kodi Documentation: SystemBuiltins.cpp File Reference
SystemBuiltins.cpp File Reference
#include "SystemBuiltins.h"
#include "ServiceBroker.h"
#include "messaging/ApplicationMessenger.h"
#include "utils/StringUtils.h"
Functions
template<int Wait = 0>
static int Exec (const std::vector< std::string > &params)
Execute a system executable.
static int Hibernate (const std::vector< std::string > &params)
Hibernate system.
static int InhibitIdle (const std::vector< std::string > &params)
Inhibit idle shutdown timer.
static int Minimize (const std::vector< std::string > &params)
Minimize application.
static int Powerdown (const std::vector< std::string > &params)
Powerdown system.
static int Quit (const std::vector< std::string > &params)
Quit application.
static int Reboot (const std::vector< std::string > &params)
Reboot system.
static int RestartApp (const std::vector< std::string > &params)
Restart application.
static int ActivateScreensaver (const std::vector< std::string > &params)
Activate screensaver.
static int ResetScreensaver (const std::vector< std::string > &params)
Reset screensaver.
static int InhibitScreenSaver (const std::vector< std::string > &params)
Inhibit screensaver.
static int Shutdown (const std::vector< std::string > &params)
Shutdown system.
static int Suspend (const std::vector< std::string > &params)
Suspend system.
Function Documentation
ActivateScreensaver()
static int ActivateScreensaver (const std::vector< std::string > & params) static
Activate screensaver.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_ACTIVATESCREENSAVER.
Referenced by CSystemBuiltins::GetOperations().
Exec()
template<int Wait = 0> static int Exec (const std::vector< std::string > & params) static
Execute a system executable.
Parameters
params The parameters.
params[0] = The path to the executable.
Set the template parameter Wait to true to wait for execution exit.
References CServiceBroker::GetAppMessenger(), TMSG_EXECUTE_OS, TMSG_MINIMIZE, and Wait().
Hibernate()
static int Hibernate (const std::vector< std::string > & params) static
Hibernate system.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_HIBERNATE.
Referenced by CSystemBuiltins::GetOperations().
InhibitIdle()
static int InhibitIdle (const std::vector< std::string > & params) static
Inhibit idle shutdown timer.
Parameters
params The parameters.
params[0] = "true" to inhibit shutdown timer (optional).
References KODI::UTILS::StringUtils::EqualsNoCase(), CServiceBroker::GetAppMessenger(), and TMSG_INHIBITIDLESHUTDOWN.
Referenced by CSystemBuiltins::GetOperations().
InhibitScreenSaver()
static int InhibitScreenSaver (const std::vector< std::string > & params) static
Inhibit screensaver.
Parameters
params The parameters.
params[0] = "true" to inhibit screensaver (optional).
References KODI::UTILS::StringUtils::EqualsNoCase(), CServiceBroker::GetAppMessenger(), and TMSG_INHIBITSCREENSAVER.
Referenced by CSystemBuiltins::GetOperations().
Minimize()
static int Minimize (const std::vector< std::string > & params) static
Minimize application.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_MINIMIZE.
Referenced by CSystemBuiltins::GetOperations().
Powerdown()
static int Powerdown (const std::vector< std::string > & params) static
Powerdown system.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_POWERDOWN.
Referenced by CSystemBuiltins::GetOperations().
Quit()
static int Quit (const std::vector< std::string > & params) static
Quit application.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_QUIT.
Referenced by CSystemBuiltins::GetOperations().
Reboot()
static int Reboot (const std::vector< std::string > & params) static
Reboot system.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_RESTART.
Referenced by CSystemBuiltins::GetOperations().
ResetScreensaver()
static int ResetScreensaver (const std::vector< std::string > & params) static
Reset screensaver.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_RESETSCREENSAVER.
Referenced by CSystemBuiltins::GetOperations().
RestartApp()
static int RestartApp (const std::vector< std::string > & params) static
Restart application.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_RESTARTAPP.
Referenced by CSystemBuiltins::GetOperations().
Shutdown()
static int Shutdown (const std::vector< std::string > & params) static
Shutdown system.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_SHUTDOWN.
Referenced by CSystemBuiltins::GetOperations().
Suspend()
static int Suspend (const std::vector< std::string > & params) static
Suspend system.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_SUSPEND.
Referenced by CSystemBuiltins::GetOperations().