Kodi Documentation: KODI::GAME::CGUIActivePortList Class Reference
KODI::GAME::CGUIActivePortList Class Reference
Games
#include <GUIActivePortList.h>
Public Member Functions
CGUIActivePortList (CGUIWindow &window, int controlId, bool showInputDisabled)
~CGUIActivePortList () override
bool Initialize (GameClientPtr gameClient) override
Initialize resources.
void Deinitialize () override
Deinitialize resources.
void Refresh () override
Refresh the contents of the list.
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
Public Member Functions inherited from KODI::GAME::IActivePortList
virtual ~IActivePortList ()=default
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Private Member Functions
void OnEvent (const ADDON::AddonEvent &event)
void InitializeGUI ()
void DeinitializeGUI ()
void AddInputDisabled ()
void AddItems (const PortVec &ports)
void AddItem (const ControllerPtr &controller, const std::string &controllerAddress)
void AddPadding ()
void CleanupItems ()
Private Attributes
CGUIWindow & m_guiWindow
const int m_controlId
const bool m_showInputDisabled
std::unique_ptr< CFileItemList > m_vecItems
uint32_t m_alignment {0}
GameClientPtr m_gameClient
Constructor & Destructor Documentation
CGUIActivePortList()
CGUIActivePortList::CGUIActivePortList (CGUIWindow & window, int controlId, bool showInputDisabled)
~CGUIActivePortList()
CGUIActivePortList::~CGUIActivePortList () override
References Deinitialize().
Member Function Documentation
AddInputDisabled()
void CGUIActivePortList::AddInputDisabled () private
References m_vecItems, and CGUIListItem::SetArt().
Referenced by Refresh().
AddItem()
void CGUIActivePortList::AddItem (const ControllerPtr & controller, const std::string & controllerAddress) private
References m_vecItems.
Referenced by AddItems().
AddItems()
void CGUIActivePortList::AddItems (const PortVec & ports) private
References AddItem(), and AddItems().
Referenced by AddItems(), and Refresh().
AddPadding()
void CGUIActivePortList::AddPadding () private
References m_showInputDisabled, m_vecItems, and MAX_PORT_COUNT.
Referenced by Refresh().
CleanupItems()
void CGUIActivePortList::CleanupItems () private
References m_vecItems.
Referenced by DeinitializeGUI(), and Refresh().
Deinitialize()
void CGUIActivePortList::Deinitialize () override virtual
Deinitialize resources.
Implements KODI::GAME::IActivePortList.
References DeinitializeGUI(), ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), and m_gameClient.
Referenced by ~CGUIActivePortList().
DeinitializeGUI()
void CGUIActivePortList::DeinitializeGUI () private
References CleanupItems(), KODI::GAME::CGUIGameControllerList::ClearGameClient(), CGUIControlLookup::GetControl(), m_controlId, and m_guiWindow.
Referenced by Deinitialize().
Initialize()
bool CGUIActivePortList::Initialize (GameClientPtr gameClient) override virtual
Initialize resources.
Parameters
gameClient The game client providing the ports
Returns
True if the resource is initialized and can be used, false if the resource failed to initialize and must not be used
Implements KODI::GAME::IActivePortList.
References ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), InitializeGUI(), m_gameClient, and OnEvent().
InitializeGUI()
void CGUIActivePortList::InitializeGUI () private
References KODI::GAME::CGUIGameControllerList::GetAlignment(), CGUIControlLookup::GetControl(), m_alignment, m_controlId, m_gameClient, m_guiWindow, Refresh(), and KODI::GAME::CGUIGameControllerList::SetGameClient().
Referenced by Initialize().
Notify()
void CGUIActivePortList::Notify (const Observable & obs, const ObservableMessage msg) override virtual
Process a message from an observable.
Parameters
obs The observable that sends the message.
msg The message.
Implements Observer.
References CServiceBroker::GetAppMessenger(), CGUIControl::GetID(), GUI_MSG_REFRESH_LIST, m_controlId, m_guiWindow, and ObservableMessageGamePortsChanged.
OnEvent()
void CGUIActivePortList::OnEvent (const ADDON::AddonEvent & event) private
References ADDON::AddonEvent::addonId, CServiceBroker::GetAppMessenger(), CGUIControl::GetID(), GUI_MSG_REFRESH_LIST, m_controlId, m_guiWindow, and CGUIMessage::SetStringParam().
Referenced by Initialize().
Refresh()
void CGUIActivePortList::Refresh () override virtual
Refresh the contents of the list.
Implements KODI::GAME::IActivePortList.
References AddInputDisabled(), AddItems(), AddPadding(), CleanupItems(), CGUIControl::GetID(), KODI::GAME::CControllerHub::GetPorts(), GUI_MSG_LABEL_BIND, m_alignment, m_controlId, m_gameClient, m_guiWindow, m_showInputDisabled, m_vecItems, CGUIWindow::OnMessage(), and XBFONT_RIGHT.
Referenced by InitializeGUI().
Member Data Documentation
m_alignment
uint32_t KODI::GAME::CGUIActivePortList::m_alignment {0} private
Referenced by InitializeGUI(), and Refresh().
m_controlId
const int KODI::GAME::CGUIActivePortList::m_controlId private
Referenced by DeinitializeGUI(), InitializeGUI(), Notify(), OnEvent(), and Refresh().
m_gameClient
GameClientPtr KODI::GAME::CGUIActivePortList::m_gameClient private
Referenced by Deinitialize(), Initialize(), InitializeGUI(), and Refresh().
m_guiWindow
CGUIWindow& KODI::GAME::CGUIActivePortList::m_guiWindow private
Referenced by DeinitializeGUI(), InitializeGUI(), Notify(), OnEvent(), and Refresh().
m_showInputDisabled
const bool KODI::GAME::CGUIActivePortList::m_showInputDisabled private
Referenced by AddPadding(), and Refresh().
m_vecItems
std::unique_ptr<CFileItemList> KODI::GAME::CGUIActivePortList::m_vecItems private
Referenced by AddInputDisabled(), AddItem(), AddPadding(), CleanupItems(), and Refresh().
The documentation for this class was generated from the following files:
GUIActivePortList.h
GUIActivePortList.cpp