Kodi Documentation: CMouseTranslator Class Reference
CMouseTranslator Class Reference
Input » Mouse
#include <MouseTranslator.h>
Static Public Member Functions
static uint32_t TranslateCommand (const tinyxml2::XMLElement *pButton)
Translate a keymap element to a key ID.
static bool TranslateEventID (unsigned int eventId, KODI::MOUSE::BUTTON_ID &buttonId)
Translate a mouse event ID to a mouse button index.
Member Function Documentation
TranslateCommand()
uint32_t CMouseTranslator::TranslateCommand (const tinyxml2::XMLElement * pButton) static
Translate a keymap element to a key ID.
References id, CLog::Log(), LOGERROR, and MOUSE_MAX_BUTTON.
Referenced by KODI::KEYMAP::CButtonTranslator::MapWindowActions().
TranslateEventID()
bool CMouseTranslator::TranslateEventID (unsigned int eventId, KODI::MOUSE::BUTTON_ID & buttonId) static
Translate a mouse event ID to a mouse button index.
Parameters
eventId The event ID from MouseStat.h
[out] buttonId The button ID from MouseTypes.h, or unmodified if unsuccessful
Returns
True if successful, false otherwise
References XBMC_BUTTON_LEFT, XBMC_BUTTON_MIDDLE, XBMC_BUTTON_RIGHT, XBMC_BUTTON_WHEELDOWN, XBMC_BUTTON_WHEELUP, XBMC_BUTTON_X1, XBMC_BUTTON_X2, XBMC_BUTTON_X3, and XBMC_BUTTON_X4.
Referenced by CInputManager::OnEvent().
The documentation for this class was generated from the following files:
MouseTranslator.h
MouseTranslator.cpp