Kodi Documentation: CDirectoryHistory Class Reference
CDirectoryHistory Class Reference
#include <DirectoryHistory.h>
Classes
class CHistoryItem
class CPathHistoryItem
Public Member Functions
CDirectoryHistory ()=default
virtual ~CDirectoryHistory ()
void SetSelectedItem (const std::string &strSelectedItem, const std::string &strDirectory, const int indexItem=-1)
Store the currently selected item for the navigation path.
const std::string & GetSelectedItem (const std::string &strDirectory) const
int GetSelectedItemIndex (const std::string &strDirectory) const
void RemoveSelectedItem (const std::string &strDirectory)
void AddPath (const std::string &strPath, const std::string &m_strFilterPath="")
void AddPathFront (const std::string &strPath, const std::string &m_strFilterPath="")
std::string GetParentPath (bool filter=false)
std::string RemoveParentPath (bool filter=false)
void ClearPathHistory ()
void ClearSearchHistory ()
void DumpPathHistory ()
bool IsInHistory (const std::string &path) const
Returns whether a path is in the history.
Private Types
typedef std::map< std::string, CHistoryItem > HistoryMap
Static Private Member Functions
static std::string preparePath (const std::string &strDirectory, bool tolower=true)
static bool IsMusicSearchUrl (CPathHistoryItem &i)
Private Attributes
HistoryMap m_vecHistory
std::vector< CPathHistoryItem > m_vecPathHistory
History of traversed directories.
Member Typedef Documentation
HistoryMap
typedef std::map<std::string, CHistoryItem> CDirectoryHistory::HistoryMap private
Constructor & Destructor Documentation
CDirectoryHistory()
CDirectoryHistory::CDirectoryHistory () default
~CDirectoryHistory()
CDirectoryHistory::~CDirectoryHistory () virtual
References m_vecHistory, and m_vecPathHistory.
Member Function Documentation
AddPath()
void CDirectoryHistory::AddPath (const std::string & strPath, const std::string & m_strFilterPath = "")
References CDirectoryHistory::CPathHistoryItem::m_strFilterPath, CDirectoryHistory::CPathHistoryItem::m_strPath, and m_vecPathHistory.
Referenced by CGUIMediaWindow::OnClick(), CGUIDialogFileBrowser::Update(), and CGUIMediaWindow::Update().
AddPathFront()
void CDirectoryHistory::AddPathFront (const std::string & strPath, const std::string & m_strFilterPath = "")
References CDirectoryHistory::CPathHistoryItem::m_strFilterPath, CDirectoryHistory::CPathHistoryItem::m_strPath, and m_vecPathHistory.
Referenced by CGUIMediaWindow::SetHistoryForPath().
ClearPathHistory()
void CDirectoryHistory::ClearPathHistory ()
References m_vecPathHistory.
Referenced by CGUIDialogFileBrowser::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIMediaWindow::SetHistoryForPath(), CGUIDialogFileBrowser::Update(), and CGUIMediaWindow::Update().
ClearSearchHistory()
void CDirectoryHistory::ClearSearchHistory ()
References IsMusicSearchUrl(), and m_vecPathHistory.
Referenced by CGUIWindowMusicNav::OnSearchUpdate().
DumpPathHistory()
void CDirectoryHistory::DumpPathHistory ()
References CLog::Log(), LOGDEBUG, and m_vecPathHistory.
GetParentPath()
std::string CDirectoryHistory::GetParentPath (bool filter = false)
References m_vecPathHistory.
Referenced by CGUIMediaWindow::GetDirectory(), CGUIWindowMusicNav::GetSongsFromPlayList(), CGUIMediaWindow::GoParentFolder(), CGUIMediaWindow::OnFilterItems(), RemoveParentPath(), and CGUIDialogFileBrowser::Update().
GetSelectedItem()
const std::string & CDirectoryHistory::GetSelectedItem (const std::string & strDirectory) const
References CDirectoryHistory::CHistoryItem::m_strItem, m_vecHistory, and preparePath().
Referenced by CGUIMediaWindow::RestoreSelectedItemFromHistory(), CGUIDialogFileBrowser::Update(), and CGUIWindowFileManager::Update().
GetSelectedItemIndex()
int CDirectoryHistory::GetSelectedItemIndex (const std::string & strDirectory) const
References m_vecHistory, and preparePath().
Referenced by CGUIMediaWindow::RestoreSelectedItemFromHistory().
IsInHistory()
bool CDirectoryHistory::IsInHistory (const std::string & path) const
Returns whether a path is in the history.
Parameters
path to test
Returns
true if the path is in the history, false otherwise.
References URIUtils::AddSlashAtEnd(), and m_vecPathHistory.
IsMusicSearchUrl()
bool CDirectoryHistory::IsMusicSearchUrl (CPathHistoryItem & i) static private
References CDirectoryHistory::CPathHistoryItem::GetPath().
Referenced by ClearSearchHistory().
preparePath()
std::string CDirectoryHistory::preparePath (const std::string & strDirectory, bool tolower = true) static private
References URIUtils::RemoveSlashAtEnd().
Referenced by GetSelectedItem(), GetSelectedItemIndex(), RemoveSelectedItem(), and SetSelectedItem().
RemoveParentPath()
std::string CDirectoryHistory::RemoveParentPath (bool filter = false)
References GetParentPath(), and m_vecPathHistory.
Referenced by CGUIMediaWindow::GetDirectory(), CGUIMediaWindow::GoParentFolder(), CGUIMediaWindow::OnClick(), CGUIDialogFileBrowser::Update(), and CGUIMediaWindow::Update().
RemoveSelectedItem()
void CDirectoryHistory::RemoveSelectedItem (const std::string & strDirectory)
References m_vecHistory, and preparePath().
SetSelectedItem()
void CDirectoryHistory::SetSelectedItem (const std::string & strSelectedItem, const std::string & strDirectory, const int indexItem = -1)
Store the currently selected item for the navigation path.
Parameters
strSelectedItem Selected item
strDirectory Path
indexItem Index of the selected item (in list, after filtering/sorting). -1 when the index information is not available.
References CDirectoryHistory::CHistoryItem::m_indexItem, CDirectoryHistory::CHistoryItem::m_strItem, m_vecHistory, and preparePath().
Referenced by CGUIWindowMusicPlayList::SavePlayList(), CGUIMediaWindow::SaveSelectedItemInHistory(), CGUIMediaWindow::SetHistoryForPath(), CGUIDialogFileBrowser::Update(), and CGUIWindowFileManager::Update().
Member Data Documentation
m_vecHistory
HistoryMap CDirectoryHistory::m_vecHistory private
Referenced by GetSelectedItem(), GetSelectedItemIndex(), RemoveSelectedItem(), SetSelectedItem(), and ~CDirectoryHistory().
m_vecPathHistory
std::vector<CPathHistoryItem> CDirectoryHistory::m_vecPathHistory private
History of traversed directories.
Referenced by AddPath(), AddPathFront(), ClearPathHistory(), ClearSearchHistory(), DumpPathHistory(), GetParentPath(), IsInHistory(), RemoveParentPath(), and ~CDirectoryHistory().
The documentation for this class was generated from the following files:
DirectoryHistory.h
DirectoryHistory.cpp