Kodi Documentation: JNIXBMCAudioManagerOnAudioFocusChangeListener.cpp File Reference
JNIXBMCAudioManagerOnAudioFocusChangeListener.cpp File Reference
#include "JNIXBMCAudioManagerOnAudioFocusChangeListener.h"
#include "CompileInfo.h"
#include "XBMCApp.h"
#include <androidjni/Context.h>
#include <androidjni/jutils-details.hpp>
Variables
static std::string s_className = std::string(CCompileInfo::GetClass()) + "/interfaces/XBMCAudioManagerOnAudioFocusChangeListener"
Variable Documentation
s_className
std::string s_className = std::string(CCompileInfo::GetClass()) + "/interfaces/XBMCAudioManagerOnAudioFocusChangeListener" static
Referenced by jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener::CJNIXBMCAudioManagerOnAudioFocusChangeListener(), jni::CJNIXBMCDisplayManagerDisplayListener::CJNIXBMCDisplayManagerDisplayListener(), jni::CJNIXBMCMediaSession::CJNIXBMCMediaSession(), jni::CJNIXBMCNsdManagerDiscoveryListener::CJNIXBMCNsdManagerDiscoveryListener(), jni::CJNIXBMCNsdManagerRegistrationListener::CJNIXBMCNsdManagerRegistrationListener(), jni::CJNIXBMCNsdManagerResolveListener::CJNIXBMCNsdManagerResolveListener(), jni::CJNIXBMCSpeechRecognitionListener::CJNIXBMCSpeechRecognitionListener(), jni::CJNIXBMCSurfaceTextureOnFrameAvailableListener::CJNIXBMCSurfaceTextureOnFrameAvailableListener(), jni::CJNIXBMCVideoView::createVideoView(), jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener::RegisterNatives(), jni::CJNIXBMCDisplayManagerDisplayListener::RegisterNatives(), jni::CJNIXBMCFile::RegisterNatives(), jni::CJNIXBMCJsonHandler::RegisterNatives(), jni::CJNIXBMCMainView::RegisterNatives(), jni::CJNIXBMCMediaSession::RegisterNatives(), jni::CJNIXBMCNsdManagerDiscoveryListener::RegisterNatives(), jni::CJNIXBMCNsdManagerRegistrationListener::RegisterNatives(), jni::CJNIXBMCNsdManagerResolveListener::RegisterNatives(), jni::CJNIXBMCSpeechRecognitionListener::RegisterNatives(), jni::CJNIXBMCSurfaceTextureOnFrameAvailableListener::RegisterNatives(), jni::CJNIXBMCTextureCache::RegisterNatives(), jni::CJNIXBMCURIUtils::RegisterNatives(), and jni::CJNIXBMCVideoView::RegisterNatives().