Kodi Documentation: IRenderMsg Class Reference
IRenderMsg Class Reference abstract
#include <RenderManager.h>
Public Member Functions
virtual ~IRenderMsg ()=default
Protected Member Functions
virtual void VideoParamsChange ()=0
virtual void GetDebugInfo (std::string &audio, std::string &video, std::string &general)=0
virtual void UpdateClockSync (bool enabled)=0
virtual void UpdateRenderInfo (CRenderInfo &info)=0
virtual void UpdateRenderBuffers (int queued, int discard, int free)=0
virtual void UpdateGuiRender (bool gui)=0
virtual void UpdateVideoRender (bool video)=0
virtual CVideoSettings GetVideoSettings () const =0
Private Attributes
friend CRenderManager
Constructor & Destructor Documentation
~IRenderMsg()
virtual IRenderMsg::~IRenderMsg () virtual default
Member Function Documentation
GetDebugInfo()
virtual void IRenderMsg::GetDebugInfo (std::string & audio, std::string & video, std::string & general) protected pure virtual
Implemented in CVideoPlayer.
Referenced by CRenderManager::Render().
GetVideoSettings()
virtual CVideoSettings IRenderMsg::GetVideoSettings () const protected pure virtual
Implemented in CVideoPlayer.
Referenced by CRenderManager::Configure().
UpdateClockSync()
virtual void IRenderMsg::UpdateClockSync (bool enabled) protected pure virtual
Implemented in CVideoPlayer.
Referenced by CRenderManager::CheckEnableClockSync().
UpdateGuiRender()
virtual void IRenderMsg::UpdateGuiRender (bool gui) protected pure virtual
Implemented in CVideoPlayer.
Referenced by CRenderManager::Configure(), and CRenderManager::FrameMove().
UpdateRenderBuffers()
virtual void IRenderMsg::UpdateRenderBuffers (int queued, int discard, int free) protected pure virtual
Implemented in CVideoPlayer.
Referenced by CRenderManager::AddVideoPicture(), CRenderManager::FrameMove(), and CRenderManager::PrepareNextRender().
UpdateRenderInfo()
virtual void IRenderMsg::UpdateRenderInfo (CRenderInfo & info) protected pure virtual
Implemented in CVideoPlayer.
Referenced by CRenderManager::Configure().
UpdateVideoRender()
virtual void IRenderMsg::UpdateVideoRender (bool video) protected pure virtual
Implemented in CVideoPlayer.
Referenced by CRenderManager::Configure().
VideoParamsChange()
virtual void IRenderMsg::VideoParamsChange () protected pure virtual
Implemented in CVideoPlayer.
Referenced by CRenderManager::Configure(), CRenderManager::SetViewMode(), and CRenderManager::UpdateResolution().
Member Data Documentation
CRenderManager
friend IRenderMsg::CRenderManager private
The documentation for this class was generated from the following file:
RenderManager.h