Kodi Documentation: CNetworkInterfaceLinux Class Reference
CNetworkInterfaceLinux Class Reference
#include <NetworkLinux.h>
Public Member Functions
CNetworkInterfaceLinux (CNetworkPosix *network, std::string interfaceName, char interfaceMacAddrRaw[6])
~CNetworkInterfaceLinux () override=default
std::string GetCurrentDefaultGateway () const override
bool GetHostMacAddress (unsigned long host, std::string &mac) const override
Public Member Functions inherited from CNetworkInterfacePosix
CNetworkInterfacePosix (CNetworkPosix *network, std::string interfaceName, char interfaceMacAddrRaw[6])
virtual ~CNetworkInterfacePosix () override=default
bool IsEnabled () const override
bool IsConnected () const override
std::string GetCurrentIPAddress () const override
std::string GetCurrentNetmask () const override
std::string GetMacAddress () const override
void GetMacAddressRaw (char rawMac[6]) const override
Public Member Functions inherited from CNetworkInterface
virtual ~CNetworkInterface ()=default
Additional Inherited Members
Protected Attributes inherited from CNetworkInterfacePosix
std::string m_interfaceName
CNetworkPosix * m_network
Constructor & Destructor Documentation
CNetworkInterfaceLinux()
CNetworkInterfaceLinux::CNetworkInterfaceLinux (CNetworkPosix * network, std::string interfaceName, char interfaceMacAddrRaw[6])
~CNetworkInterfaceLinux()
CNetworkInterfaceLinux::~CNetworkInterfaceLinux () override default
Member Function Documentation
GetCurrentDefaultGateway()
std::string CNetworkInterfaceLinux::GetCurrentDefaultGateway (void) const override virtual
Implements CNetworkInterface.
References fclose(), CNetworkInterfacePosix::m_interfaceName, and CNetworkBase::ParseHex().
GetHostMacAddress()
bool CNetworkInterfaceLinux::GetHostMacAddress (unsigned long host, std::string & mac) const override virtual
Implements CNetworkInterface.
References CNetworkPosix::GetSocket(), CNetworkInterfacePosix::m_interfaceName, and CNetworkInterfacePosix::m_network.
The documentation for this class was generated from the following files:
NetworkLinux.h
NetworkLinux.cpp