Kodi Documentation: CIrssMessage Class Reference
CIrssMessage Class Reference
#include <IrssMessage.h>
Public Member Functions
CIrssMessage ()
CIrssMessage (IRSS_MessageType type, uint32_t flags)
CIrssMessage (IRSS_MessageType type, uint32_t flags, char *data, int size)
CIrssMessage (IRSS_MessageType type, uint32_t flags, const std::string &data)
~CIrssMessage ()
void SetDataAsBytes (char *data, int size)
void SetDataAsString (const std::string &data)
char * ToBytes (int &size)
void SetType (IRSS_MessageType type)
void SetFlags (uint32_t flags)
IRSS_MessageType GetType ()
uint32_t GetFlags ()
char * GetData ()
uint32_t GetDataSize ()
Static Public Member Functions
static bool FromBytes (char *from, int size, CIrssMessage &message)
Private Member Functions
void FreeData ()
Private Attributes
IRSS_MessageType m_type
uint32_t m_flags
char * m_data
int m_dataSize
Constructor & Destructor Documentation
CIrssMessage() [1/4]
CIrssMessage::CIrssMessage ()
References IRSSMT_Unknown, m_data, m_dataSize, m_flags, and m_type.
CIrssMessage() [2/4]
CIrssMessage::CIrssMessage (IRSS_MessageType type, uint32_t flags)
References m_data, m_dataSize, m_flags, and m_type.
CIrssMessage() [3/4]
CIrssMessage::CIrssMessage (IRSS_MessageType type, uint32_t flags, char * data, int size)
References data(), m_flags, m_type, and SetDataAsBytes().
CIrssMessage() [4/4]
CIrssMessage::CIrssMessage (IRSS_MessageType type, uint32_t flags, const std::string & data)
References data(), m_flags, m_type, and SetDataAsString().
~CIrssMessage()
CIrssMessage::~CIrssMessage ()
References FreeData().
Member Function Documentation
FreeData()
void CIrssMessage::FreeData () private
References m_data, and m_dataSize.
Referenced by SetDataAsBytes(), SetDataAsString(), and ~CIrssMessage().
FromBytes()
bool CIrssMessage::FromBytes (char * from, int size, CIrssMessage & message) static
References SetDataAsBytes(), SetFlags(), and SetType().
Referenced by CIRServerSuite::ReadPacket().
GetData()
char * CIrssMessage::GetData () inline
References m_data.
Referenced by CIRServerSuite::HandleRemoteEvent(), and CIRServerSuite::ReadNext().
GetDataSize()
uint32_t CIrssMessage::GetDataSize () inline
References m_dataSize.
Referenced by CIRServerSuite::HandleRemoteEvent(), and CIRServerSuite::ReadNext().
GetFlags()
uint32_t CIrssMessage::GetFlags () inline
References m_flags.
Referenced by CIRServerSuite::ReadNext().
GetType()
IRSS_MessageType CIrssMessage::GetType () inline
References m_type.
Referenced by CIRServerSuite::ReadNext().
SetDataAsBytes()
void CIrssMessage::SetDataAsBytes (char * data, int size)
References data(), FreeData(), m_data, and m_dataSize.
Referenced by CIrssMessage(), and FromBytes().
SetDataAsString()
void CIrssMessage::SetDataAsString (const std::string & data)
References data(), FreeData(), m_data, and m_dataSize.
Referenced by CIrssMessage().
SetFlags()
void CIrssMessage::SetFlags (uint32_t flags)
References m_flags.
Referenced by FromBytes().
SetType()
void CIrssMessage::SetType (IRSS_MessageType type)
References m_type.
Referenced by FromBytes(), and CIRServerSuite::ReadNext().
ToBytes()
char * CIrssMessage::ToBytes (int & size)
References m_data, m_dataSize, m_flags, and m_type.
Referenced by CIRServerSuite::SendPacket().
Member Data Documentation
m_data
char* CIrssMessage::m_data private
Referenced by CIrssMessage(), CIrssMessage(), FreeData(), GetData(), SetDataAsBytes(), SetDataAsString(), and ToBytes().
m_dataSize
int CIrssMessage::m_dataSize private
Referenced by CIrssMessage(), CIrssMessage(), FreeData(), GetDataSize(), SetDataAsBytes(), SetDataAsString(), and ToBytes().
m_flags
uint32_t CIrssMessage::m_flags private
Referenced by CIrssMessage(), CIrssMessage(), CIrssMessage(), CIrssMessage(), GetFlags(), SetFlags(), and ToBytes().
m_type
IRSS_MessageType CIrssMessage::m_type private
Referenced by CIrssMessage(), CIrssMessage(), CIrssMessage(), CIrssMessage(), GetType(), SetType(), and ToBytes().
The documentation for this class was generated from the following files:
IrssMessage.h
IrssMessage.cpp