Kodi Documentation: CCharsetDetection Class Reference
CCharsetDetection Class Reference
#include <CharsetDetection.h>
Static Public Member Functions
static std::string GetBomEncoding (const char *const content, const size_t contentLength)
static std::string GetBomEncoding (const std::string &content)
static bool DetectXmlEncoding (const std::string &xmlContent, std::string &detectedEncoding)
static bool DetectXmlEncoding (const char *const xmlContent, const size_t contentLength, std::string &detectedEncoding)
static bool ConvertHtmlToUtf8 (const std::string &htmlContent, std::string &converted, const std::string &serverReportedCharset="")
static bool ConvertHtmlToUtf8 (const std::string &htmlContent, std::string &converted, const std::string &serverReportedCharset, std::string &usedHtmlCharset)
static bool ConvertPlainTextToUtf8 (const std::string &textContent, std::string &converted, const std::string &serverReportedCharset, std::string &usedCharset)
Static Private Member Functions
static bool GetXmlEncodingFromDeclaration (const char *const xmlContent, const size_t contentLength, std::string &declaredEncoding)
static bool GuessXmlEncoding (const char *const xmlContent, const size_t contentLength, std::string &supposedEncoding)
static std::string GetHtmlEncodingFromHead (const std::string &htmlContent)
static size_t GetHtmlAttribute (const std::string &htmlContent, size_t pos, std::string &atrName, std::string &strValue)
static std::string ExtractEncodingFromHtmlMeta (const std::string &metaContent, size_t pos=0)
static bool checkConversion (const std::string &srcCharset, const std::string &src, std::string &dst)
static void appendCharAsAsciiUpperCase (std::string &str, const char chr)
Static Private Attributes
static const size_t m_XmlDeclarationMaxLength = 250
static const size_t m_HtmlCharsetEndSearchPos = 1024
static const std::string m_HtmlWhitespaceChars
Member Function Documentation
appendCharAsAsciiUpperCase()
void CCharsetDetection::appendCharAsAsciiUpperCase (std::string & str, const char chr) inline static private
Referenced by GetHtmlAttribute().
checkConversion()
bool CCharsetDetection::checkConversion (const std::string & srcCharset, const std::string & src, std::string & dst) static private
References g_charsetConverter, and CUtf8Utils::isValidUtf8().
Referenced by ConvertHtmlToUtf8(), and ConvertPlainTextToUtf8().
ConvertHtmlToUtf8() [1/2]
bool CCharsetDetection::ConvertHtmlToUtf8 (const std::string & htmlContent, std::string & converted, const std::string & serverReportedCharset, std::string & usedHtmlCharset) static
Detect HTML charset and HTML convert to UTF-8
Parameters
htmlContent content of HTML file
converted receive result of conversion
serverReportedCharset charset from HTTP header or from other out-of-band source, empty if unknown or unset
usedHtmlCharset receive charset used for conversion
Returns
true if charset is properly detected and HTML is correctly converted, false if charset is only guessed
References checkConversion(), g_charsetConverter, g_langInfo, GetBomEncoding(), GetHtmlEncodingFromHead(), CLog::Log(), and LOGWARNING.
ConvertHtmlToUtf8() [2/2]
static bool CCharsetDetection::ConvertHtmlToUtf8 (const std::string & htmlContent, std::string & converted, const std::string & serverReportedCharset = "") inline static
Detect HTML charset and HTML convert to UTF-8
Parameters
htmlContent content of HTML file
converted receive result of conversion
serverReportedCharset charset from HTTP header or from other out-of-band source, empty if unknown or unset
Returns
true if charset is properly detected and HTML is correctly converted, false if charset is only guessed
References ConvertHtmlToUtf8().
Referenced by ConvertHtmlToUtf8(), and CScraperUrl::Get().
ConvertPlainTextToUtf8()
bool CCharsetDetection::ConvertPlainTextToUtf8 (const std::string & textContent, std::string & converted, const std::string & serverReportedCharset, std::string & usedCharset) static
Try to convert plain text to UTF-8 using best suitable charset
Parameters
textContent text to convert
converted receive result of conversion
serverReportedCharset charset from HTTP header or from other out-of-band source, empty if unknown or unset
usedCharset receive charset used for conversion
Returns
true if converted without errors, false otherwise
References checkConversion(), g_charsetConverter, g_langInfo, GetBomEncoding(), CLog::Log(), and LOGWARNING.
Referenced by CScraperUrl::Get().
DetectXmlEncoding() [1/2]
bool CCharsetDetection::DetectXmlEncoding (const char *const xmlContent, const size_t contentLength, std::string & detectedEncoding) static
References g_charsetConverter, GetBomEncoding(), GetXmlEncodingFromDeclaration(), GuessXmlEncoding(), and m_XmlDeclarationMaxLength.
DetectXmlEncoding() [2/2]
static bool CCharsetDetection::DetectXmlEncoding (const std::string & xmlContent, std::string & detectedEncoding) inline static
References DetectXmlEncoding().
Referenced by DetectXmlEncoding(), and CXBMCTinyXML::Parse().
ExtractEncodingFromHtmlMeta()
std::string CCharsetDetection::ExtractEncodingFromHtmlMeta (const std::string & metaContent, size_t pos = 0) static private
References m_HtmlWhitespaceChars.
Referenced by GetHtmlEncodingFromHead().
GetBomEncoding() [1/2]
std::string CCharsetDetection::GetBomEncoding (const char *const content, const size_t contentLength) static
Detect text encoding by Byte Order Mark Multibyte encodings (UTF-16/32) always ends with explicit endianness (LE/BE)
Parameters
content pointer to text to analyze
contentLength length of text
Returns
detected encoding or empty string if BOM not detected
Referenced by ConvertHtmlToUtf8(), ConvertPlainTextToUtf8(), DetectXmlEncoding(), GetBomEncoding(), and CDVDSubtitleStream::Open().
GetBomEncoding() [2/2]
static std::string CCharsetDetection::GetBomEncoding (const std::string & content) inline static
Detect text encoding by Byte Order Mark Multibyte encodings (UTF-16/32) always ends with explicit endianness (LE/BE)
Parameters
content the text to analyze
Returns
detected encoding or empty string if BOM not detected
References GetBomEncoding().
GetHtmlAttribute()
size_t CCharsetDetection::GetHtmlAttribute (const std::string & htmlContent, size_t pos, std::string & atrName, std::string & strValue) static private
References appendCharAsAsciiUpperCase(), and m_HtmlWhitespaceChars.
Referenced by GetHtmlEncodingFromHead().
GetHtmlEncodingFromHead()
std::string CCharsetDetection::GetHtmlEncodingFromHead (const std::string & htmlContent) static private
References ExtractEncodingFromHtmlMeta(), GetHtmlAttribute(), m_HtmlCharsetEndSearchPos, and m_HtmlWhitespaceChars.
Referenced by ConvertHtmlToUtf8().
GetXmlEncodingFromDeclaration()
bool CCharsetDetection::GetXmlEncodingFromDeclaration (const char *const xmlContent, const size_t contentLength, std::string & declaredEncoding) static private
References m_XmlDeclarationMaxLength.
Referenced by DetectXmlEncoding().
GuessXmlEncoding()
bool CCharsetDetection::GuessXmlEncoding (const char *const xmlContent, const size_t contentLength, std::string & supposedEncoding) static private
Try to guess text encoding by searching for '<?xml' mark in different encodings Multibyte encodings (UTF/UCS) always ends with explicit endianness (LE/BE)
Parameters
content pointer to text to analyze
contentLength length of text
detectedEncoding reference to variable that receive supposed encoding
Returns
true if any encoding supposed, false otherwise
Referenced by DetectXmlEncoding().
Member Data Documentation
m_HtmlCharsetEndSearchPos
const size_t CCharsetDetection::m_HtmlCharsetEndSearchPos = 1024 static private
Referenced by GetHtmlEncodingFromHead().
m_HtmlWhitespaceChars
const std::string CCharsetDetection::m_HtmlWhitespaceChars static private
Referenced by ExtractEncodingFromHtmlMeta(), GetHtmlAttribute(), and GetHtmlEncodingFromHead().
m_XmlDeclarationMaxLength
const size_t CCharsetDetection::m_XmlDeclarationMaxLength = 250 static private
Referenced by DetectXmlEncoding(), and GetXmlEncodingFromDeclaration().
The documentation for this class was generated from the following files:
CharsetDetection.h
CharsetDetection.cpp