Kodi Documentation: ADDON::Interface_Android Struct Reference
ADDON::Interface_Android Struct Reference
#include <System.h>
Static Public Member Functions
static void Register ()
static void * Get (const std::string &name, const std::string &version)
static void * get_jni_env ()
static int get_sdk_version ()
static const char * get_class_name ()
Member Function Documentation
Get()
void * ADDON::Interface_Android::Get (const std::string & name, const std::string & version) static
References function_table, INTERFACE_ANDROID_SYSTEM_NAME, INTERFACE_ANDROID_SYSTEM_VERSION, INTERFACE_ANDROID_SYSTEM_VERSION_MIN, and name.
Referenced by Register().
get_class_name()
const char * ADDON::Interface_Android::get_class_name () static
References CCompileInfo::GetClass().
Referenced by Register().
get_jni_env()
void * ADDON::Interface_Android::get_jni_env () static
Referenced by Register().
get_sdk_version()
int ADDON::Interface_Android::get_sdk_version () static
References CXBMCApp::Get().
Referenced by Register().
Register()
void ADDON::Interface_Android::Register () static
References function_table, Get(), get_class_name(), AddonToKodiFuncTable_android_system::get_class_name, get_jni_env(), AddonToKodiFuncTable_android_system::get_jni_env, get_sdk_version(), AddonToKodiFuncTable_android_system::get_sdk_version, and ADDON::Interface_Base::RegisterInterface().
Referenced by CWinSystemAndroid::InitWindowSystem().
The documentation for this struct was generated from the following files:
interfaces/platform/android/system.h
System.cpp