Kodi Documentation: CAndroidKey Class Reference
CAndroidKey Class Reference
#include <AndroidKey.h>
Public Member Functions
CAndroidKey ()=default
~CAndroidKey ()=default
bool onKeyboardEvent (AInputEvent *event)
Static Public Member Functions
static void SetHandleMediaKeys (bool enable)
static void SetHandleSearchKeys (bool enable)
static void XBMC_Key (uint8_t code, uint16_t key, uint16_t modifiers, uint16_t unicode, bool up)
Static Protected Attributes
static bool m_handleMediaKeys = true
static bool m_handleSearchKeys = false
Constructor & Destructor Documentation
CAndroidKey()
CAndroidKey::CAndroidKey () default
~CAndroidKey()
CAndroidKey::~CAndroidKey () default
Member Function Documentation
onKeyboardEvent()
bool CAndroidKey::onKeyboardEvent (AInputEvent * event)
Todo:
implement
References CXBMCApp::android_printf(), index(), keyMap, m_handleMediaKeys, m_handleSearchKeys, MediakeyMap, SearchkeyMap, PERIPHERALS::CAndroidJoystickTranslator::TranslateKeyCode(), XBMC_Key(), XBMCK_LAST, XBMCK_UNKNOWN, KeyMap::xbmcKey, XBMCKMOD_LALT, XBMCKMOD_LCTRL, XBMCKMOD_LSHIFT, XBMCKMOD_RALT, XBMCKMOD_RCTRL, and XBMCKMOD_RSHIFT.
Referenced by CEventLoop::processInput().
SetHandleMediaKeys()
static void CAndroidKey::SetHandleMediaKeys (bool enable) inline static
References m_handleMediaKeys.
Referenced by CXBMCApp::OnPlayBackStarted(), and CXBMCApp::OnPlayBackStopped().
SetHandleSearchKeys()
static void CAndroidKey::SetHandleSearchKeys (bool enable) inline static
References m_handleSearchKeys.
Referenced by CXBMCApp::Announce().
XBMC_Key()
void CAndroidKey::XBMC_Key (uint8_t code, uint16_t key, uint16_t modifiers, uint16_t unicode, bool up) static
References CServiceBroker::GetWinSystem(), XBMC_Event::key, XBMC_KeyboardEvent::keysym, CWinSystemAndroid::MessagePush(), XBMC_keysym::mod, XBMC_keysym::scancode, XBMC_keysym::sym, XBMC_Event::type, XBMC_keysym::unicode, XBMC_KEYDOWN, and XBMC_KEYUP.
Referenced by onKeyboardEvent(), and CXBMCApp::onReceive().
Member Data Documentation
m_handleMediaKeys
bool CAndroidKey::m_handleMediaKeys = true static protected
Referenced by onKeyboardEvent(), and SetHandleMediaKeys().
m_handleSearchKeys
bool CAndroidKey::m_handleSearchKeys = false static protected
Referenced by onKeyboardEvent(), and SetHandleSearchKeys().
The documentation for this class was generated from the following files:
AndroidKey.h
AndroidKey.cpp