Kodi Documentation: PVR::CPVRCachedImages Class Reference
PVR::CPVRCachedImages Class Reference
#include <PVRCachedImages.h>
Static Public Member Functions
static int Cleanup (const std::vector< PVRImagePattern > &urlPatterns, const std::vector< std::string > &urlsToCheck, bool clearTextureForPath=false)
Erase stale texture db entries and image files.
Member Function Documentation
Cleanup()
int CPVRCachedImages::Cleanup (const std::vector< PVRImagePattern > & urlPatterns, const std::vector< std::string > & urlsToCheck, bool clearTextureForPath = false) static
Erase stale texture db entries and image files.
Parameters
urlPatterns The URL patterns to fetch from texture database.
urlsToCheck The URLs to check for still being present in the texture db.
clearTextureForPath Whether to clear the path in texture database.
Returns
number of cleaned up images.
References CDatabase::Filter::AppendWhere(), CTextureDatabase::ClearTextureForPath(), IMAGE_FILES::CImageFileURL::GetTargetFile(), CServiceBroker::GetTextureCache(), CTextureDatabase::GetTextures(), LOGDEBUG, LOGERROR, LOGPVR, CTextureDatabase::Open(), and CVariant::size().
Referenced by PVR::CPVRChannelGroup::CleanupCachedImages(), PVR::CPVRChannelGroups::CleanupCachedImages(), PVR::CPVRProviders::CleanupCachedImages(), PVR::CPVRRecordings::CleanupCachedImages(), and PVR::CPVREpg::CleanupCachedImages().
The documentation for this class was generated from the following files:
PVRCachedImages.h
PVRCachedImages.cpp