Kodi Documentation: CWinEventsWin10 Class Reference
CWinEventsWin10 Class Reference
#include <WinEventsWin10.h>
Public Member Functions
CWinEventsWin10 ()
virtual ~CWinEventsWin10 ()
void MessagePush (XBMC_Event *newEvent)
bool MessagePump () override
virtual size_t GetQueueSize ()
void InitEventHandlers (const winrt::Windows::UI::Core::CoreWindow &)
void OnWindowSizeChanged (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::UI::Core::WindowSizeChangedEventArgs &)
void OnWindowResizeStarted (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::Foundation::IInspectable &)
void OnWindowResizeCompleted (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::Foundation::IInspectable &)
void OnWindowClosed (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::UI::Core::CoreWindowEventArgs &)
void OnPointerPressed (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::UI::Core::PointerEventArgs &)
void OnPointerMoved (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::UI::Core::PointerEventArgs &)
void OnPointerReleased (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::UI::Core::PointerEventArgs &)
void OnPointerExited (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::UI::Core::PointerEventArgs &)
void OnPointerWheelChanged (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::UI::Core::PointerEventArgs &)
void OnAcceleratorKeyActivated (const winrt::Windows::UI::Core::CoreDispatcher &, const winrt::Windows::UI::Core::AcceleratorKeyEventArgs &)
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
Public Member Functions inherited from IWinEvents
virtual ~IWinEvents ()=default
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Static Public Member Functions
static void InitOSKeymap (void)
static void OnWindowActivationChanged (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::UI::Core::WindowActivatedEventArgs &)
static void OnVisibilityChanged (const winrt::Windows::UI::Core::CoreWindow &, const winrt::Windows::UI::Core::VisibilityChangedEventArgs &)
static void OnDpiChanged (const winrt::Windows::Graphics::Display::DisplayInformation &, const winrt::Windows::Foundation::IInspectable &)
static void OnOrientationChanged (const winrt::Windows::Graphics::Display::DisplayInformation &, const winrt::Windows::Foundation::IInspectable &)
static void OnDisplayContentsInvalidated (const winrt::Windows::Graphics::Display::DisplayInformation &, const winrt::Windows::Foundation::IInspectable &)
static void OnBackRequested (const winrt::Windows::Foundation::IInspectable &, const winrt::Windows::UI::Core::BackRequestedEventArgs &)
static void OnSystemMediaButtonPressed (const winrt::Windows::Media::SystemMediaTransportControls &, const winrt::Windows::Media::SystemMediaTransportControlsButtonPressedEventArgs &)
Private Member Functions
void OnResize (float width, float height)
void UpdateWindowSize ()
void Kodi_KeyEvent (unsigned int vkey, unsigned scancode, unsigned keycode, bool isDown)
void HandleWindowSizeChanged ()
Private Attributes
Concurrency::concurrent_queue< XBMC_Event > m_events
winrt::Windows::Media::SystemMediaTransportControls m_smtc { nullptr }
bool m_bResized { false }
bool m_bMoved { false }
bool m_sizeChanging { false }
float m_logicalWidth { 0 }
float m_logicalHeight { 0 }
float m_logicalPosX { 0 }
float m_logicalPosY { 0 }
std::unique_ptr< CRemoteControlXbox > m_remote
Friends
class CWinSystemWin10
Constructor & Destructor Documentation
CWinEventsWin10()
CWinEventsWin10::CWinEventsWin10 () default
~CWinEventsWin10()
CWinEventsWin10::~CWinEventsWin10 () virtual default
Member Function Documentation
Announce()
void CWinEventsWin10::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References data(), and ANNOUNCEMENT::Player.
GetQueueSize()
size_t CWinEventsWin10::GetQueueSize () virtual
References m_events.
HandleWindowSizeChanged()
void CWinEventsWin10::HandleWindowSizeChanged () private
References CLog::Log(), LOGDEBUG, m_bMoved, m_bResized, m_logicalHeight, m_logicalWidth, and UpdateWindowSize().
Referenced by OnResize(), and OnWindowResizeCompleted().
InitEventHandlers()
void CWinEventsWin10::InitEventHandlers (const winrt::Windows::UI::Core::CoreWindow &)
References CServiceBroker::GetAnnouncementManager(), CSysInfo::GetWindowsDeviceFamily(), InitOSKeymap(), m_remote, m_smtc, OnAcceleratorKeyActivated(), OnBackRequested(), OnDisplayContentsInvalidated(), OnDpiChanged(), OnOrientationChanged(), OnPointerExited(), OnPointerMoved(), OnPointerPressed(), OnPointerReleased(), OnPointerWheelChanged(), OnSystemMediaButtonPressed(), OnVisibilityChanged(), OnWindowActivationChanged(), OnWindowClosed(), OnWindowResizeCompleted(), OnWindowResizeStarted(), OnWindowSizeChanged(), ANNOUNCEMENT::Player, and CSysInfo::Xbox.
Referenced by CWinSystemWin10::InitWindowSystem().
InitOSKeymap()
void CWinEventsWin10::InitOSKeymap (void) static
References KODI::WINDOWING::WINDOWS::DIB_InitOSKeymap().
Referenced by InitEventHandlers().
Kodi_KeyEvent()
void CWinEventsWin10::Kodi_KeyEvent (unsigned int vkey, unsigned scancode, unsigned keycode, bool isDown) private
References XBMC_Event::key, XBMC_KeyboardEvent::keysym, MessagePush(), XBMC_keysym::mod, XBMC_keysym::scancode, XBMC_keysym::sym, XBMC_Event::type, XBMC_keysym::unicode, KODI::WINDOWING::WINDOWS::VK_keymap, XBMC_KEYDOWN, XBMC_KEYUP, XBMCKMOD_LALT, XBMCKMOD_LCTRL, XBMCKMOD_LSHIFT, XBMCKMOD_LSUPER, XBMCKMOD_MODE, XBMCKMOD_NONE, XBMCKMOD_RALT, XBMCKMOD_RCTRL, and XBMCKMOD_RSHIFT.
Referenced by OnAcceleratorKeyActivated().
MessagePump()
bool CWinEventsWin10::MessagePump () override virtual
Implements IWinEvents.
References CServiceBroker::GetAppPort(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_UNFOCUS_ALL, m_events, CGUIWindowManager::SendMessage(), XBMC_Event::type, and XBMC_MOUSEBUTTONUP.
MessagePush()
void CWinEventsWin10::MessagePush (XBMC_Event * newEvent)
References CServiceBroker::GetAppPort(), m_events, XBMC_Event::type, XBMC_KEYDOWN, XBMC_KEYUP, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, XBMC_MOUSEMOTION, and XBMC_TOUCH.
Referenced by Kodi_KeyEvent(), OnPointerMoved(), OnPointerPressed(), OnPointerReleased(), OnPointerWheelChanged(), OnWindowClosed(), and UpdateWindowSize().
OnAcceleratorKeyActivated()
void CWinEventsWin10::OnAcceleratorKeyActivated (const winrt::Windows::UI::Core::CoreDispatcher & , const winrt::Windows::UI::Core::AcceleratorKeyEventArgs &)
References Kodi_KeyEvent(), and m_remote.
Referenced by InitEventHandlers().
OnBackRequested()
void CWinEventsWin10::OnBackRequested (const winrt::Windows::Foundation::IInspectable & , const winrt::Windows::UI::Core::BackRequestedEventArgs &) static
References ACTION_NAV_BACK, CServiceBroker::GetAppMessenger(), CSysInfo::GetWindowsDeviceFamily(), CSysInfo::Mobile, TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by InitEventHandlers().
OnDisplayContentsInvalidated()
void CWinEventsWin10::OnDisplayContentsInvalidated (const winrt::Windows::Graphics::Display::DisplayInformation & , const winrt::Windows::Foundation::IInspectable &) static
References DX::DeviceResources::Get(), CLog::Log(), and LOGDEBUG.
Referenced by InitEventHandlers().
OnDpiChanged()
void CWinEventsWin10::OnDpiChanged (const winrt::Windows::Graphics::Display::DisplayInformation & , const winrt::Windows::Foundation::IInspectable &) static
References DX::DisplayMetrics::Dpi100, CGenericTouchInputHandler::GetInstance(), and ITouchInputHandler::SetScreenDPI().
Referenced by InitEventHandlers().
OnOrientationChanged()
void CWinEventsWin10::OnOrientationChanged (const winrt::Windows::Graphics::Display::DisplayInformation & , const winrt::Windows::Foundation::IInspectable &) static
Referenced by InitEventHandlers().
OnPointerExited()
void CWinEventsWin10::OnPointerExited (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::UI::Core::PointerEventArgs &)
References CGenericTouchInputHandler::GetInstance(), GetScreenPoint(), CGenericTouchInputHandler::HandleTouchInput(), and TouchInputAbort.
Referenced by InitEventHandlers().
OnPointerMoved()
void CWinEventsWin10::OnPointerMoved (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::UI::Core::PointerEventArgs &)
References CGenericTouchInputHandler::GetInstance(), GetScreenPoint(), CGenericTouchInputHandler::HandleTouchInput(), MessagePush(), XBMC_Event::motion, TouchInputMove, XBMC_Event::type, CGenericTouchInputHandler::UpdateTouchPointer(), XBMC_MouseMotionEvent::x, XBMC_MOUSEMOTION, and XBMC_MouseMotionEvent::y.
Referenced by InitEventHandlers().
OnPointerPressed()
void CWinEventsWin10::OnPointerPressed (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::UI::Core::PointerEventArgs &)
References XBMC_MouseButtonEvent::button, XBMC_Event::button, CGenericTouchInputHandler::GetInstance(), GetScreenPoint(), CGenericTouchInputHandler::HandleTouchInput(), MessagePush(), TouchInputDown, XBMC_Event::type, XBMC_MouseButtonEvent::x, XBMC_BUTTON_LEFT, XBMC_BUTTON_MIDDLE, XBMC_BUTTON_RIGHT, XBMC_MOUSEBUTTONDOWN, and XBMC_MouseButtonEvent::y.
Referenced by InitEventHandlers().
OnPointerReleased()
void CWinEventsWin10::OnPointerReleased (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::UI::Core::PointerEventArgs &)
References XBMC_MouseButtonEvent::button, XBMC_Event::button, CGenericTouchInputHandler::GetInstance(), GetScreenPoint(), CGenericTouchInputHandler::HandleTouchInput(), MessagePush(), TouchInputUp, XBMC_Event::type, XBMC_MouseButtonEvent::x, XBMC_BUTTON_LEFT, XBMC_BUTTON_MIDDLE, XBMC_BUTTON_RIGHT, XBMC_MOUSEBUTTONUP, and XBMC_MouseButtonEvent::y.
Referenced by InitEventHandlers().
OnPointerWheelChanged()
void CWinEventsWin10::OnPointerWheelChanged (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::UI::Core::PointerEventArgs &)
References XBMC_MouseButtonEvent::button, XBMC_Event::button, MessagePush(), XBMC_Event::type, XBMC_MouseButtonEvent::x, XBMC_BUTTON_WHEELDOWN, XBMC_BUTTON_WHEELUP, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, and XBMC_MouseButtonEvent::y.
Referenced by InitEventHandlers().
OnResize()
void CWinEventsWin10::OnResize (float width, float height) private
References HandleWindowSizeChanged(), CLog::Log(), LOGDEBUG, m_bResized, m_logicalHeight, m_logicalWidth, and m_sizeChanging.
Referenced by CWinSystemWin10::ChangeResolution(), and OnWindowSizeChanged().
OnSystemMediaButtonPressed()
void CWinEventsWin10::OnSystemMediaButtonPressed (const winrt::Windows::Media::SystemMediaTransportControls & , const winrt::Windows::Media::SystemMediaTransportControlsButtonPressedEventArgs &) static
References ACTION_CHANNEL_DOWN, ACTION_CHANNEL_UP, ACTION_NEXT_ITEM, ACTION_NONE, ACTION_PLAYER_FORWARD, ACTION_PLAYER_PLAYPAUSE, ACTION_PLAYER_REWIND, ACTION_PREV_ITEM, ACTION_RECORD, ACTION_STOP, CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by InitEventHandlers().
OnVisibilityChanged()
void CWinEventsWin10::OnVisibilityChanged (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::UI::Core::VisibilityChangedEventArgs &) static
References g_application, CServiceBroker::GetAppPort(), CLog::Log(), and LOGDEBUG.
Referenced by InitEventHandlers().
OnWindowActivationChanged()
void CWinEventsWin10::OnWindowActivationChanged (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::UI::Core::WindowActivatedEventArgs &) static
References g_application, CServiceBroker::GetAppPort(), CServiceBroker::IsLoggingUp(), CLog::Log(), and LOGDEBUG.
Referenced by InitEventHandlers().
OnWindowClosed()
void CWinEventsWin10::OnWindowClosed (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::UI::Core::CoreWindowEventArgs &)
References g_application, MessagePush(), XBMC_Event::type, and XBMC_QUIT.
Referenced by InitEventHandlers().
OnWindowResizeCompleted()
void CWinEventsWin10::OnWindowResizeCompleted (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::Foundation::IInspectable &)
References HandleWindowSizeChanged(), CLog::Log(), LOGDEBUG, m_bMoved, m_logicalPosX, m_logicalPosY, and m_sizeChanging.
Referenced by InitEventHandlers().
OnWindowResizeStarted()
void CWinEventsWin10::OnWindowResizeStarted (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::Foundation::IInspectable &)
References CLog::Log(), LOGDEBUG, m_logicalPosX, m_logicalPosY, and m_sizeChanging.
Referenced by InitEventHandlers().
OnWindowSizeChanged()
void CWinEventsWin10::OnWindowSizeChanged (const winrt::Windows::UI::Core::CoreWindow & , const winrt::Windows::UI::Core::WindowSizeChangedEventArgs &)
References OnResize().
Referenced by InitEventHandlers().
UpdateWindowSize()
void CWinEventsWin10::UpdateWindowSize () private
References g_application, DX::DeviceResources::Get(), CServiceBroker::GetSettingsComponent(), XBMC_ResizeEvent::h, CLog::Log(), LOGDEBUG, MessagePush(), XBMC_Event::resize, XBMC_Event::type, XBMC_ResizeEvent::w, and XBMC_VIDEORESIZE.
Referenced by HandleWindowSizeChanged().
Friends And Related Symbol Documentation
CWinSystemWin10
friend class CWinSystemWin10 friend
Member Data Documentation
m_bMoved
bool CWinEventsWin10::m_bMoved { false } private
Referenced by HandleWindowSizeChanged(), and OnWindowResizeCompleted().
m_bResized
bool CWinEventsWin10::m_bResized { false } private
Referenced by HandleWindowSizeChanged(), and OnResize().
m_events
Concurrency::concurrent_queue<XBMC_Event> CWinEventsWin10::m_events private
Referenced by GetQueueSize(), MessagePump(), and MessagePush().
m_logicalHeight
float CWinEventsWin10::m_logicalHeight { 0 } private
Referenced by HandleWindowSizeChanged(), and OnResize().
m_logicalPosX
float CWinEventsWin10::m_logicalPosX { 0 } private
Referenced by OnWindowResizeCompleted(), and OnWindowResizeStarted().
m_logicalPosY
float CWinEventsWin10::m_logicalPosY { 0 } private
Referenced by OnWindowResizeCompleted(), and OnWindowResizeStarted().
m_logicalWidth
float CWinEventsWin10::m_logicalWidth { 0 } private
Referenced by HandleWindowSizeChanged(), and OnResize().
m_remote
std::unique_ptr<CRemoteControlXbox> CWinEventsWin10::m_remote private
Referenced by InitEventHandlers(), and OnAcceleratorKeyActivated().
m_sizeChanging
bool CWinEventsWin10::m_sizeChanging { false } private
Referenced by OnResize(), OnWindowResizeCompleted(), and OnWindowResizeStarted().
m_smtc
winrt::Windows::Media::SystemMediaTransportControls CWinEventsWin10::m_smtc { nullptr } private
Referenced by InitEventHandlers().
The documentation for this class was generated from the following files:
WinEventsWin10.h
WinEventsWin10.cpp