Kodi Documentation: JSONRPC::CSystemOperations Class Reference
JSONRPC::CSystemOperations Class Reference
#include <SystemOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetProperties (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS EjectOpticalDrive (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Shutdown (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Suspend (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Hibernate (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Reboot (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Static Private Member Functions
static JSONRPC_STATUS GetPropertyValue (int permissions, const std::string &property, CVariant &result)
Member Function Documentation
EjectOpticalDrive()
JSONRPC_STATUS CSystemOperations::EjectOpticalDrive (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CBuiltins::Execute(), JSONRPC::FailedToExecute, and CBuiltins::GetInstance().
GetProperties()
JSONRPC_STATUS CSystemOperations::GetProperties (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), JSONRPC::IClient::GetPermissionFlags(), GetPropertyValue(), index(), JSONRPC::OK, CVariant::size(), and CVariant::VariantTypeObject.
GetPropertyValue()
JSONRPC_STATUS CSystemOperations::GetPropertyValue (int permissions, const std::string & property, CVariant & result) static private
References CPowerManager::CanHibernate(), CPowerManager::CanPowerdown(), CPowerManager::CanReboot(), CPowerManager::CanSuspend(), JSONRPC::ControlPower, CServiceBroker::GetPowerManager(), JSONRPC::InvalidParams, and JSONRPC::OK.
Referenced by GetProperties().
Hibernate()
JSONRPC_STATUS CSystemOperations::Hibernate (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), CServiceBroker::GetPowerManager(), and TMSG_HIBERNATE.
Reboot()
JSONRPC_STATUS CSystemOperations::Reboot (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), CServiceBroker::GetPowerManager(), and TMSG_RESTART.
Shutdown()
JSONRPC_STATUS CSystemOperations::Shutdown (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), CServiceBroker::GetPowerManager(), and TMSG_POWERDOWN.
Suspend()
JSONRPC_STATUS CSystemOperations::Suspend (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::FailedToExecute, CServiceBroker::GetAppMessenger(), CServiceBroker::GetPowerManager(), and TMSG_SUSPEND.
The documentation for this class was generated from the following files:
SystemOperations.h
SystemOperations.cpp