Kodi Documentation: TestStringUtils.cpp File Reference
TestStringUtils.cpp File Reference
#include "utils/StringUtils.h"
#include <algorithm>
#include <gtest/gtest.h>
Namespaces
namespace test_enum
Enumerations
enum class ECG { A , B }
enum EG { C , D }
enum class test_enum::ECN { test_enum::A = 1 , test_enum::B }
enum test_enum::EN { test_enum::C = 1 , test_enum::D }
Functions
TEST (TestStringUtils, Format)
TEST (TestStringUtils, FormatEnum)
TEST (TestStringUtils, FormatEnumWidth)
TEST (TestStringUtils, ToUpper)
TEST (TestStringUtils, ToLower)
TEST (TestStringUtils, ToCapitalize)
TEST (TestStringUtils, EqualsNoCase)
TEST (TestStringUtils, Left)
TEST (TestStringUtils, Mid)
TEST (TestStringUtils, Right)
TEST (TestStringUtils, Trim)
TEST (TestStringUtils, TrimLeft)
TEST (TestStringUtils, TrimRight)
TEST (TestStringUtils, Replace)
TEST (TestStringUtils, StartsWith)
TEST (TestStringUtils, EndsWith)
TEST (TestStringUtils, Join)
TEST (TestStringUtils, Split)
TEST (TestStringUtils, FindNumber)
TEST (TestStringUtils, AlphaNumericCompare)
TEST (TestStringUtils, TimeStringToSeconds)
TEST (TestStringUtils, RemoveCRLF)
TEST (TestStringUtils, utf8_strlen)
TEST (TestStringUtils, SecondsToTimeString)
TEST (TestStringUtils, IsNaturalNumber)
TEST (TestStringUtils, IsInteger)
TEST (TestStringUtils, SizeToString)
TEST (TestStringUtils, EmptyString)
TEST (TestStringUtils, FindWords)
TEST (TestStringUtils, FindWords_NonAscii)
TEST (TestStringUtils, FindEndBracket)
TEST (TestStringUtils, DateStringToYYYYMMDD)
TEST (TestStringUtils, WordToDigits)
TEST (TestStringUtils, CreateUUID)
TEST (TestStringUtils, ValidateUUID)
TEST (TestStringUtils, CompareFuzzy)
TEST (TestStringUtils, FindBestMatch)
TEST (TestStringUtils, Paramify)
TEST (TestStringUtils, sortstringbyname)
TEST (TestStringUtils, FileSizeFormat)
TEST (TestStringUtils, ToHexadecimal)
Enumeration Type Documentation
ECG
enum class ECG strong
Enumerator
A
B
EG
enum EG
Enumerator
C
D
Function Documentation
TEST() [1/41]
TEST (TestStringUtils , AlphaNumericCompare)
References KODI::UTILS::StringUtils::AlphaNumericCompare(), and int64_t().
TEST() [2/41]
TEST (TestStringUtils , CompareFuzzy)
References KODI::UTILS::StringUtils::CompareFuzzy(), and EXPECT_EQ().
TEST() [3/41]
TEST (TestStringUtils , CreateUUID)
References KODI::UTILS::StringUtils::CreateUUID().
TEST() [4/41]
TEST (TestStringUtils , DateStringToYYYYMMDD)
References KODI::UTILS::StringUtils::DateStringToYYYYMMDD(), and EXPECT_EQ().
TEST() [5/41]
TEST (TestStringUtils , EmptyString)
References KODI::UTILS::StringUtils::Empty.
TEST() [6/41]
TEST (TestStringUtils , EndsWith)
References KODI::UTILS::StringUtils::EndsWith(), KODI::UTILS::StringUtils::EndsWithNoCase(), and EXPECT_TRUE().
TEST() [7/41]
TEST (TestStringUtils , EqualsNoCase)
References KODI::UTILS::StringUtils::EqualsNoCase(), and EXPECT_TRUE().
TEST() [8/41]
TEST (TestStringUtils , FileSizeFormat)
References KODI::UTILS::StringUtils::FormatFileSize().
TEST() [9/41]
TEST (TestStringUtils , FindBestMatch)
References EXPECT_EQ(), and KODI::UTILS::StringUtils::FindBestMatch().
TEST() [10/41]
TEST (TestStringUtils , FindEndBracket)
References EXPECT_EQ(), and KODI::UTILS::StringUtils::FindEndBracket().
TEST() [11/41]
TEST (TestStringUtils , FindNumber)
References EXPECT_EQ(), and KODI::UTILS::StringUtils::FindNumber().
TEST() [12/41]
TEST (TestStringUtils , FindWords)
References EXPECT_EQ(), and KODI::UTILS::StringUtils::FindWords().
TEST() [13/41]
TEST (TestStringUtils , FindWords_NonAscii)
References EXPECT_EQ(), and KODI::UTILS::StringUtils::FindWords().
TEST() [14/41]
TEST (TestStringUtils , Format)
References KODI::UTILS::StringUtils::Format().
TEST() [15/41]
TEST (TestStringUtils , FormatEnum)
References A, test_enum::A, C, test_enum::C, and KODI::UTILS::StringUtils::Format().
TEST() [16/41]
TEST (TestStringUtils , FormatEnumWidth)
References B, D, and KODI::UTILS::StringUtils::Format().
TEST() [17/41]
TEST (TestStringUtils , IsInteger)
References EXPECT_TRUE(), and KODI::UTILS::StringUtils::IsInteger().
TEST() [18/41]
TEST (TestStringUtils , IsNaturalNumber)
References EXPECT_TRUE(), and KODI::UTILS::StringUtils::IsNaturalNumber().
TEST() [19/41]
TEST (TestStringUtils , Join)
References KODI::UTILS::StringUtils::Join().
TEST() [20/41]
TEST (TestStringUtils , Left)
References KODI::UTILS::StringUtils::Left().
TEST() [21/41]
TEST (TestStringUtils , Mid)
References KODI::UTILS::StringUtils::Mid().
TEST() [22/41]
TEST (TestStringUtils , Paramify)
References KODI::UTILS::StringUtils::Paramify().
TEST() [23/41]
TEST (TestStringUtils , RemoveCRLF)
References KODI::UTILS::StringUtils::RemoveCRLF().
TEST() [24/41]
TEST (TestStringUtils , Replace)
References EXPECT_EQ(), and KODI::UTILS::StringUtils::Replace().
TEST() [25/41]
TEST (TestStringUtils , Right)
References KODI::UTILS::StringUtils::Right().
TEST() [26/41]
TEST (TestStringUtils , SecondsToTimeString)
References KODI::UTILS::StringUtils::SecondsToTimeString().
TEST() [27/41]
TEST (TestStringUtils , SizeToString)
References KODI::UTILS::StringUtils::SizeToString().
TEST() [28/41]
TEST (TestStringUtils , sortstringbyname)
TEST() [29/41]
TEST (TestStringUtils , Split)
References EXPECT_EQ(), EXPECT_TRUE(), and KODI::UTILS::StringUtils::Split().
TEST() [30/41]
TEST (TestStringUtils , StartsWith)
References EXPECT_TRUE(), KODI::UTILS::StringUtils::StartsWith(), and KODI::UTILS::StringUtils::StartsWithNoCase().
TEST() [31/41]
TEST (TestStringUtils , TimeStringToSeconds)
References EXPECT_EQ(), and KODI::UTILS::StringUtils::TimeStringToSeconds().
TEST() [32/41]
TEST (TestStringUtils , ToCapitalize)
References KODI::UTILS::StringUtils::ToCapitalize().
TEST() [33/41]
TEST (TestStringUtils , ToHexadecimal)
References KODI::UTILS::StringUtils::ToHexadecimal().
TEST() [34/41]
TEST (TestStringUtils , ToLower)
References KODI::UTILS::StringUtils::ToLower().
TEST() [35/41]
TEST (TestStringUtils , ToUpper)
References KODI::UTILS::StringUtils::ToUpper().
TEST() [36/41]
TEST (TestStringUtils , Trim)
References KODI::UTILS::StringUtils::Trim().
TEST() [37/41]
TEST (TestStringUtils , TrimLeft)
References KODI::UTILS::StringUtils::TrimLeft().
TEST() [38/41]
TEST (TestStringUtils , TrimRight)
References KODI::UTILS::StringUtils::TrimRight().
TEST() [39/41]
TEST (TestStringUtils , utf8_strlen)
References EXPECT_EQ(), and KODI::UTILS::StringUtils::utf8_strlen().
TEST() [40/41]
TEST (TestStringUtils , ValidateUUID)
References KODI::UTILS::StringUtils::CreateUUID(), EXPECT_TRUE(), and KODI::UTILS::StringUtils::ValidateUUID().
TEST() [41/41]
TEST (TestStringUtils , WordToDigits)
References KODI::UTILS::StringUtils::WordToDigits().