Kodi Documentation: CXBMCTestUtils Class Reference
CXBMCTestUtils Class Reference
#include <TestUtils.h>
Public Member Functions
std::string ReferenceFilePath (const std::string &path)
bool SetReferenceFileBasePath ()
XFILE::CFile * CreateTempFile (std::string const &suffix)
bool DeleteTempFile (XFILE::CFile *tempfile)
std::string TempFilePath (XFILE::CFile const *const tempfile)
std::string TempFileDirectory (XFILE::CFile const *const tempfile)
std::vector< std::string > & getTestFileFactoryReadUrls ()
std::vector< std::string > & getTestFileFactoryWriteUrls ()
std::string & getTestFileFactoryWriteInputFile ()
void setTestFileFactoryWriteInputFile (std::string const &file)
std::vector< std::string > & getAdvancedSettingsFiles ()
std::vector< std::string > & getGUISettingsFiles ()
XFILE::CFile * CreateCorruptedFile (std::string const &strFileName, std::string const &suffix)
void ParseArgs (int argc, char **argv)
std::string getNewLineCharacters () const
Static Public Member Functions
static CXBMCTestUtils & Instance ()
Private Member Functions
CXBMCTestUtils ()
CXBMCTestUtils (CXBMCTestUtils const &)=delete
CXBMCTestUtils & operator= (CXBMCTestUtils const &)=delete
Private Attributes
std::vector< std::string > TestFileFactoryReadUrls
std::vector< std::string > TestFileFactoryWriteUrls
std::string TestFileFactoryWriteInputFile
std::vector< std::string > AdvancedSettingsFiles
std::vector< std::string > GUISettingsFiles
double probability
Constructor & Destructor Documentation
CXBMCTestUtils() [1/2]
CXBMCTestUtils::CXBMCTestUtils () private
References probability.
CXBMCTestUtils() [2/2]
CXBMCTestUtils::CXBMCTestUtils (CXBMCTestUtils const &) private delete
Member Function Documentation
CreateCorruptedFile()
XFILE::CFile * CXBMCTestUtils::CreateCorruptedFile (std::string const & strFileName, std::string const & suffix)
References XFILE::CFile::Close(), CreateTempFile(), DeleteTempFile(), XFILE::CFile::Open(), probability, XFILE::CFile::Read(), and XFILE::CFile::Write().
CreateTempFile()
XFILE::CFile * CXBMCTestUtils::CreateTempFile (std::string const & suffix)
References f.
Referenced by CreateCorruptedFile(), and TEST().
DeleteTempFile()
bool CXBMCTestUtils::DeleteTempFile (XFILE::CFile * tempfile)
References CTempFile::Delete(), and f.
Referenced by CreateCorruptedFile(), and TEST().
getAdvancedSettingsFiles()
std::vector< std::string > & CXBMCTestUtils::getAdvancedSettingsFiles ()
References AdvancedSettingsFiles.
Referenced by TestFileFactory::TestFileFactory().
getGUISettingsFiles()
std::vector< std::string > & CXBMCTestUtils::getGUISettingsFiles ()
References GUISettingsFiles.
Referenced by TestFileFactory::TestFileFactory().
getNewLineCharacters()
std::string CXBMCTestUtils::getNewLineCharacters () const
Referenced by TEST().
getTestFileFactoryReadUrls()
std::vector< std::string > & CXBMCTestUtils::getTestFileFactoryReadUrls ()
References TestFileFactoryReadUrls.
Referenced by TEST_F().
getTestFileFactoryWriteInputFile()
std::string & CXBMCTestUtils::getTestFileFactoryWriteInputFile ()
References TestFileFactoryWriteInputFile.
Referenced by TEST_F().
getTestFileFactoryWriteUrls()
std::vector< std::string > & CXBMCTestUtils::getTestFileFactoryWriteUrls ()
References TestFileFactoryWriteUrls.
Referenced by TEST_F().
Instance()
CXBMCTestUtils & CXBMCTestUtils::Instance () static
Referenced by main(), TestBasicEnvironment::SetUp(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TestFileFactory::TestFileFactory().
operator=()
CXBMCTestUtils & CXBMCTestUtils::operator= (CXBMCTestUtils const &) private delete
ParseArgs()
void CXBMCTestUtils::ParseArgs (int argc, char ** argv)
References AdvancedSettingsFiles, GUISettingsFiles, probability, TestFileFactoryReadUrls, TestFileFactoryWriteInputFile, TestFileFactoryWriteUrls, and usage.
Referenced by main().
ReferenceFilePath()
std::string CXBMCTestUtils::ReferenceFilePath (const std::string & path)
References URIUtils::AddFileToFolder(), and CSpecialProtocol::TranslatePath().
SetReferenceFileBasePath()
bool CXBMCTestUtils::SetReferenceFileBasePath ()
References URIUtils::AddFileToFolder(), CUtil::GetHomePath(), CSpecialProtocol::SetHomePath(), CSpecialProtocol::SetXBMCBinPath(), and CSpecialProtocol::SetXBMCPath().
setTestFileFactoryWriteInputFile()
void CXBMCTestUtils::setTestFileFactoryWriteInputFile (std::string const & file)
References TestFileFactoryWriteInputFile.
Referenced by TestBasicEnvironment::SetUp().
TempFileDirectory()
std::string CXBMCTestUtils::TempFileDirectory (XFILE::CFile const *const tempfile)
References f, and CTempFile::getTempFileDirectory().
Referenced by TEST(), TEST(), and TEST().
TempFilePath()
std::string CXBMCTestUtils::TempFilePath (XFILE::CFile const *const tempfile)
References f, and CTempFile::getTempFilePath().
Member Data Documentation
AdvancedSettingsFiles
std::vector<std::string> CXBMCTestUtils::AdvancedSettingsFiles private
Referenced by getAdvancedSettingsFiles(), and ParseArgs().
GUISettingsFiles
std::vector<std::string> CXBMCTestUtils::GUISettingsFiles private
Referenced by getGUISettingsFiles(), and ParseArgs().
probability
double CXBMCTestUtils::probability private
Referenced by CreateCorruptedFile(), CXBMCTestUtils(), and ParseArgs().
TestFileFactoryReadUrls
std::vector<std::string> CXBMCTestUtils::TestFileFactoryReadUrls private
Referenced by getTestFileFactoryReadUrls(), and ParseArgs().
TestFileFactoryWriteInputFile
std::string CXBMCTestUtils::TestFileFactoryWriteInputFile private
Referenced by getTestFileFactoryWriteInputFile(), ParseArgs(), and setTestFileFactoryWriteInputFile().
TestFileFactoryWriteUrls
std::vector<std::string> CXBMCTestUtils::TestFileFactoryWriteUrls private
Referenced by getTestFileFactoryWriteUrls(), and ParseArgs().
The documentation for this class was generated from the following files:
TestUtils.h
TestUtils.cpp