Kodi Documentation: CEGLAttributesVec Class Reference
CEGLAttributesVec Class Reference
#include <EGLUtils.h>
Classes
struct EGLAttribute
Public Member Functions
void Add (std::initializer_list< EGLAttribute > const &attributes)
void Add (EGLAttribute const &attribute)
EGLint const * Get () const
Private Attributes
std::vector< EGLint > m_attributes {EGL_NONE}
Detailed Description
Convenience wrapper for heap-allocated EGL attribute arrays
The wrapper makes sure that the key/value pairs are always written in actual pairs and that the array is always terminated with EGL_NONE.
Member Function Documentation
Add() [1/2]
void CEGLAttributesVec::Add (EGLAttribute const & attribute) inline
Add one attribute
The array is automatically terminated with EGL_NONE
References Add().
Add() [2/2]
void CEGLAttributesVec::Add (std::initializer_list< EGLAttribute > const & attributes) inline
Add multiple attributes
The array is automatically terminated with EGL_NONE
References m_attributes.
Referenced by Add(), CEGLContextUtils::ChooseConfig(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::CreateContext(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::CreateContext(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::CreateContext(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::CreateContext(), CEGLContextUtils::CreateContext(), CEGLContextUtils::CreateSurface(), and CWinSystemAndroidGLESContext::InitWindowSystem().
Get()
EGLint const * CEGLAttributesVec::Get () const inline
References m_attributes.
Referenced by CEGLContextUtils::ChooseConfig(), CEGLContextUtils::CreateContext(), and CEGLContextUtils::CreateSurface().
Member Data Documentation
m_attributes
std::vector<EGLint> CEGLAttributesVec::m_attributes {EGL_NONE} private
Referenced by Add(), and Get().
The documentation for this class was generated from the following file:
EGLUtils.h