Kodi Documentation: CWebVTTISOHandler Class Reference
CWebVTTISOHandler Class Reference
#include <WebVTTISOHandler.h>
Public Member Functions
CWebVTTISOHandler ()
~CWebVTTISOHandler ()
void DecodeStream (const char *buffer, int bufferSize, double pts, std::vector< subtitleData > *subList, double &prevSubStopTime)
Decode a stream package of the WebVTT in MP4 encapsulated subtitles (ISO/IEC 14496-30:2014)
Public Member Functions inherited from CWebVTTHandler
CWebVTTHandler ()
~CWebVTTHandler ()
bool Initialize ()
Prepare the handler to the decoding.
void Reset ()
bool CheckSignature (const std::string &data)
Verify the validity of the WebVTT signature.
void DecodeLine (std::string line, std::vector< subtitleData > *subList)
Decode a line of the WebVTT text data.
bool IsForcedMargins () const
void SetPeriodStart (double pts)
Private Member Functions
bool ParseVTTCueBox (CCharArrayParser &sampleData, int remainingCueBoxChars, std::vector< subtitleData > *subList)
Additional Inherited Members
Protected Member Functions inherited from CWebVTTHandler
void CalculateTextPosition (std::string &subtitleText)
void ConvertSubtitle (std::string &text)
void GetCueSettings (std::string &cueSettings)
Protected Attributes inherited from CWebVTTHandler
subtitleData m_subtitleData
Constructor & Destructor Documentation
CWebVTTISOHandler()
CWebVTTISOHandler::CWebVTTISOHandler () inline
~CWebVTTISOHandler()
CWebVTTISOHandler::~CWebVTTISOHandler () inline
Member Function Documentation
DecodeStream()
void CWebVTTISOHandler::DecodeStream (const char * buffer, int bufferSize, double pts, std::vector< subtitleData > * subList, double & prevSubStopTime)
Decode a stream package of the WebVTT in MP4 encapsulated subtitles (ISO/IEC 14496-30:2014)
Parameters
buffer The data buffer
bufferSize The buffer size
subList The list to be filled with decoded subtitles
[out] prevSubStopTime Provide the stop time value (depends on box type)
References CCharArrayParser::CharsLeft(), CLog::Log(), LOGWARNING, CWebVTTHandler::m_subtitleData, MP4_BOX_HEADER_SIZE, ParseVTTCueBox(), CCharArrayParser::ReadNextUnsignedInt(), CCharArrayParser::Reset(), CCharArrayParser::SkipChars(), subtitleData::startTime, and subtitleData::stopTime.
Referenced by COverlayCodecWebVTT::Decode().
ParseVTTCueBox()
bool CWebVTTISOHandler::ParseVTTCueBox (CCharArrayParser & sampleData, int remainingCueBoxChars, std::vector< subtitleData > * subList) private
References CWebVTTHandler::CalculateTextPosition(), CWebVTTHandler::ConvertSubtitle(), subtitleData::cueSettings, CWebVTTHandler::GetCueSettings(), webvttCueSettings::id, CLog::Log(), LOGWARNING, CWebVTTHandler::m_subtitleData, MP4_BOX_HEADER_SIZE, CCharArrayParser::ReadNextString(), CCharArrayParser::ReadNextUnsignedInt(), and subtitleData::text.
Referenced by DecodeStream().
The documentation for this class was generated from the following files:
WebVTTISOHandler.h
WebVTTISOHandler.cpp