Kodi Documentation: KODI::TIME Namespace Reference
KODI::TIME Namespace Reference
Namespaces
namespace anonymous_namespace{XTimeUtils.cpp}
Classes
struct FileTime
struct SystemTime
struct TimeZoneInformation
Functions
uint32_t GetTimeZoneInformation (TimeZoneInformation *timeZoneInformation)
void GetLocalTime (SystemTime *systemTime)
int FileTimeToLocalFileTime (const FileTime *fileTime, FileTime *localFileTime)
int SystemTimeToFileTime (const SystemTime *systemTime, FileTime *fileTime)
long CompareFileTime (const FileTime *fileTime1, const FileTime *fileTime2)
int FileTimeToSystemTime (const FileTime *fileTime, SystemTime *systemTime)
int LocalFileTimeToFileTime (const FileTime *localFileTime, FileTime *fileTime)
int FileTimeToTimeT (const FileTime *localFileTime, time_t *pTimeT)
int TimeTToFileTime (time_t timeT, FileTime *localFileTime)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
Variables
constexpr int KODI_TIME_ZONE_ID_INVALID {-1}
constexpr int KODI_TIME_ZONE_ID_UNKNOWN {0}
constexpr int KODI_TIME_ZONE_ID_STANDARD {1}
constexpr int KODI_TIME_ZONE_ID_DAYLIGHT {2}
Function Documentation
CompareFileTime()
long KODI::TIME::CompareFileTime (const FileTime * fileTime1, const FileTime * fileTime2)
References KODI::TIME::FileTime::highDateTime, _ULARGE_INTEGER::HighPart, KODI::TIME::FileTime::lowDateTime, _ULARGE_INTEGER::LowPart, _ULARGE_INTEGER::QuadPart, and _ULARGE_INTEGER::u.
Referenced by CDateTimeSpan::operator<(), CDateTime::operator<(), CDateTimeSpan::operator==(), CDateTime::operator==(), CDateTimeSpan::operator>(), and CDateTime::operator>().
FileTimeToLocalFileTime()
int KODI::TIME::FileTimeToLocalFileTime (const FileTime * fileTime, FileTime * localFileTime)
References FileTimeToTimeT(), KODI::TIME::FileTime::highDateTime, _ULARGE_INTEGER::HighPart, KODI::TIME::FileTime::lowDateTime, _ULARGE_INTEGER::LowPart, _ULARGE_INTEGER::QuadPart, and _ULARGE_INTEGER::u.
Referenced by XFILE::CWin32SMBDirectory::GetDirectory(), XFILE::CNFSDirectory::GetDirectory(), XFILE::CTVOSDirectory::GetDirectory(), XFILE::CPosixDirectory::GetDirectory(), XFILE::CSMBDirectory::GetDirectory(), and XFILE::CWin32Directory::GetDirectory().
FileTimeToSystemTime()
int KODI::TIME::FileTimeToSystemTime (const FileTime * fileTime, SystemTime * systemTime)
References KODI::TIME::SystemTime::day, KODI::TIME::SystemTime::dayOfWeek, KODI::TIME::FileTime::highDateTime, KODI::TIME::SystemTime::hour, KODI::TIME::FileTime::lowDateTime, _LARGE_INTEGER::LowPart, KODI::TIME::SystemTime::milliseconds, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, KODI::TIME::SystemTime::second, _LARGE_INTEGER::u, WIN32_TIME_OFFSET, and KODI::TIME::SystemTime::year.
FileTimeToTimeT()
int KODI::TIME::FileTimeToTimeT (const FileTime * localFileTime, time_t * pTimeT)
References KODI::TIME::FileTime::highDateTime, _ULARGE_INTEGER::HighPart, KODI::TIME::FileTime::lowDateTime, _ULARGE_INTEGER::LowPart, _ULARGE_INTEGER::QuadPart, _ULARGE_INTEGER::u, and WIN32_TIME_OFFSET.
Referenced by FileTimeToLocalFileTime().
GetLocalTime()
void KODI::TIME::GetLocalTime (SystemTime * systemTime)
References KODI::TIME::SystemTime::day, KODI::TIME::SystemTime::dayOfWeek, KODI::TIME::SystemTime::hour, KODI::TIME::SystemTime::milliseconds, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, KODI::TIME::SystemTime::second, t, and KODI::TIME::SystemTime::year.
Referenced by CRssReader::CheckForUpdates(), CRssReader::Create(), CDateTime::GetCurrentDateTime(), XBMCAddon::xbmcgui::Dialog::input(), XBMCAddon::xbmcgui::Dialog::numeric(), win32_exception::write_minidump(), and win32_exception::write_stacktrace().
GetTimeZoneInformation()
uint32_t KODI::TIME::GetTimeZoneInformation (TimeZoneInformation * timeZoneInformation)
References KODI::TIME::TimeZoneInformation::bias, KODI::TIME::TimeZoneInformation::daylightName, KODI_TIME_ZONE_ID_INVALID, KODI_TIME_ZONE_ID_UNKNOWN, KODI::TIME::TimeZoneInformation::standardName, and t.
Referenced by CDateTime::GetTimezoneBias().
LocalFileTimeToFileTime()
int KODI::TIME::LocalFileTimeToFileTime (const FileTime * localFileTime, FileTime * fileTime)
References KODI::TIME::FileTime::highDateTime, _ULARGE_INTEGER::HighPart, KODI::TIME::FileTime::lowDateTime, _ULARGE_INTEGER::LowPart, _ULARGE_INTEGER::QuadPart, and _ULARGE_INTEGER::u.
Referenced by CDateTime::GetAsTimeStamp().
Sleep()
template<typename Rep , typename Period > void KODI::TIME::Sleep (std::chrono::duration< Rep, Period > duration)
Referenced by AddMatchingUPnPServers(), CAudioSinkAE::AddPackets(), CAESinkDirectSound::AddPackets(), dbiplus::busy_callback(), XFILE::CCurlFile::Cancel(), VAAPI::CDecoder::Check(), KODI::WINDOWING::GBM::CDRMConnector::CheckConnector(), dll_sleep(), anonymous_namespace{PVRGUIChannelNavigator.cpp}::CPVRChannelTimeoutJobBase::DoWork(), CWeatherJob::DoWork(), CAESinkWASAPI::Drain(), CPythonInvoker::execute(), CScriptInvocationManager::ExecuteSync(), XFILE::CCurlFile::CReadState::FillBuffer(), CApplication::FrameMove(), CAESinkALSA::HandleError(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), CGUIWindowSlideShow::OnDeinitWindow(), CGUIWindowPictures::OnPrepareFileItems(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), PingResponseWaiter::Ping(), CRenderSystemGL::PresentRender(), CRenderSystemGLES::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender(), CWinSystemWin10DX::PresentRenderImpl(), CWinSystemWin32DX::PresentRenderImpl(), CDVDInputStreamBluray::ProcessEvent(), CRenderManager::RemoveCaptures(), CApplication::Run(), CVideoSyncD3D::Run(), KODI::WINDOWING::X11::CVideoSyncGLX::Run(), CDVDDemuxFFmpeg::SeekTime(), ProgressDialogHelper::ShowAndWait(), XBMCAddon::xbmc::sleep(), CApplication::Stop(), CXRandR::TurnOnOutput(), and CNetworkBase::WaitForNet().
SystemTimeToFileTime()
int KODI::TIME::SystemTimeToFileTime (const SystemTime * systemTime, FileTime * fileTime)
References KODI::TIME::SystemTime::day, KODI::TIME::SystemTime::dayOfWeek, KODI::TIME::FileTime::highDateTime, _LARGE_INTEGER::HighPart, KODI::TIME::SystemTime::hour, IsLeapYear, KODI::TIME::FileTime::lowDateTime, _LARGE_INTEGER::LowPart, KODI::TIME::SystemTime::milliseconds, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, _LARGE_INTEGER::QuadPart, KODI::TIME::SystemTime::second, t, _LARGE_INTEGER::u, WIN32_TIME_OFFSET, and KODI::TIME::SystemTime::year.
Referenced by CDateTime::ToFileTime().
TimeTToFileTime()
int KODI::TIME::TimeTToFileTime (time_t timeT, FileTime * localFileTime)
References KODI::TIME::FileTime::highDateTime, _ULARGE_INTEGER::HighPart, KODI::TIME::FileTime::lowDateTime, _ULARGE_INTEGER::LowPart, _ULARGE_INTEGER::QuadPart, _ULARGE_INTEGER::u, and WIN32_TIME_OFFSET.
Referenced by XFILE::CTVOSDirectory::GetDirectory(), XFILE::CPosixDirectory::GetDirectory(), and XFILE::CSMBDirectory::GetDirectory().
Variable Documentation
KODI_TIME_ZONE_ID_DAYLIGHT
constexpr int KODI::TIME::KODI_TIME_ZONE_ID_DAYLIGHT {2} constexpr
Referenced by CDateTime::GetTimezoneBias().
KODI_TIME_ZONE_ID_INVALID
constexpr int KODI::TIME::KODI_TIME_ZONE_ID_INVALID {-1} constexpr
Referenced by GetTimeZoneInformation().
KODI_TIME_ZONE_ID_STANDARD
constexpr int KODI::TIME::KODI_TIME_ZONE_ID_STANDARD {1} constexpr
Referenced by CDateTime::GetTimezoneBias().
KODI_TIME_ZONE_ID_UNKNOWN
constexpr int KODI::TIME::KODI_TIME_ZONE_ID_UNKNOWN {0} constexpr
Referenced by CDateTime::GetTimezoneBias(), and GetTimeZoneInformation().