Kodi Documentation: ActiveAE::CAEResampleFactory Class Reference
ActiveAE::CAEResampleFactory Class Reference
#include <AEResampleFactory.h>
Static Public Member Functions
static std::unique_ptr< IAEResample > Create (uint32_t flags=0U)
Member Function Documentation
Create()
std::unique_ptr< IAEResample > ActiveAE::CAEResampleFactory::Create (uint32_t flags = 0U) static
Referenced by ActiveAE::CActiveAEBufferPoolResample::ChangeResampler(), ActiveAE::CActiveAESink::GenerateNoise(), VideoPlayerCodec::Init(), ActiveAE::CActiveAEStream::InitRemapper(), and ActiveAE::CActiveAE::ResampleSound().
The documentation for this class was generated from the following files:
AEResampleFactory.h
AEResampleFactory.cpp