Kodi Documentation: KODI::KEYBOARD::KeyTable Struct Reference
KODI::KEYBOARD::KeyTable Struct Reference
#include <XBMC_keytable.h>
Static Public Member Functions
static bool LookupName (std::string keyname, XBMCKEYTABLE *keytable)
static bool LookupSym (uint16_t sym, XBMCKEYTABLE *keytable)
static bool LookupUnicode (uint16_t unicode, XBMCKEYTABLE *keytable)
static bool LookupSymAndUnicode (uint16_t sym, uint16_t unicode, XBMCKEYTABLE *keytable)
static bool LookupVKeyName (uint32_t vkey, XBMCKEYTABLE *keytable)
Member Function Documentation
LookupName()
bool KeyTable::LookupName (std::string keyname, XBMCKEYTABLE * keytable) static
References KODI::KEYBOARD::XBMCKEYTABLE::keyname.
Referenced by KODI::KEYMAP::CKeyboardTranslator::TranslateString().
LookupSym()
bool KeyTable::LookupSym (uint16_t sym, XBMCKEYTABLE * keytable) static
Referenced by KODI::KEYBOARD::CKeyboardStat::TranslateKey().
LookupSymAndUnicode()
bool KeyTable::LookupSymAndUnicode (uint16_t sym, uint16_t unicode, XBMCKEYTABLE * keytable) static
Referenced by KODI::KEYBOARD::CKeyboardStat::TranslateKey().
LookupUnicode()
bool KeyTable::LookupUnicode (uint16_t unicode, XBMCKEYTABLE * keytable) static
Referenced by KODI::KEYBOARD::CKeyboardStat::TranslateKey().
LookupVKeyName()
bool KeyTable::LookupVKeyName (uint32_t vkey, XBMCKEYTABLE * keytable) static
Referenced by KODI::KEYBOARD::CKeyboardStat::GetKeyName().
The documentation for this struct was generated from the following files:
XBMC_keytable.h
XBMC_keytable.cpp