Kodi Documentation: ReplayGain Class Reference
ReplayGain Class Reference
#include <ReplayGain.h>
Classes
class Info
Public Types
enum Type { NONE = 0 , ALBUM , TRACK }
Public Member Functions
const Info & Get (Type aType) const
void Set (Type aType, const Info &aInfo)
void ParseGain (Type aType, const std::string &aStrGain)
void SetGain (Type aType, float aGain)
void ParsePeak (Type aType, const std::string &aStrPeak)
void SetPeak (Type aType, float aPeak)
std::string Get () const
void Set (const std::string &strReplayGain)
Private Attributes
Info m_data [TRACK]
Member Enumeration Documentation
Type
enum ReplayGain::Type
Enumerator
NONE
ALBUM
TRACK
Member Function Documentation
Get() [1/2]
std::string ReplayGain::Get () const
References ALBUM, Get(), and TRACK.
Referenced by Get().
Get() [2/2]
const ReplayGain::Info & ReplayGain::Get (Type aType) const
References index(), m_data, and TypeIsValid().
Referenced by CMusicDatabase::AddSong(), CAudioDecoder::Create(), CAudioDecoder::GetReplayGain(), MUSIC_INFO::CMusicInfoTag::SetSong(), and CMusicDatabase::UpdateSong().
ParseGain()
void ReplayGain::ParseGain (Type aType, const std::string & aStrGain)
References index(), m_data, ReplayGain::Info::SetGain(), and TypeIsValid().
Referenced by CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), and Set().
ParsePeak()
void ReplayGain::ParsePeak (Type aType, const std::string & aStrPeak)
References index(), m_data, ReplayGain::Info::SetPeak(), and TypeIsValid().
Referenced by CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), CTagLoaderTagLib::ParseTag(), and Set().
Set() [1/2]
void ReplayGain::Set (const std::string & strReplayGain)
References ALBUM, ParseGain(), ParsePeak(), TRACK, and values.
Set() [2/2]
void ReplayGain::Set (Type aType, const Info & aInfo)
References index(), m_data, and TypeIsValid().
Referenced by CAudioDecoder::Create(), CMusicDatabase::GetFileItemFromDataset(), CMusicDatabase::GetSongFromDataset(), CCueDocument::GetSongs(), and MUSIC_INFO::CMusicInfoTag::SetSong().
SetGain()
void ReplayGain::SetGain (Type aType, float aGain)
References index(), m_data, ReplayGain::Info::SetGain(), and TypeIsValid().
Referenced by ReplayGain::Info::SetGain().
SetPeak()
void ReplayGain::SetPeak (Type aType, float aPeak)
References index(), m_data, ReplayGain::Info::SetPeak(), and TypeIsValid().
Referenced by ReplayGain::Info::SetPeak().
Member Data Documentation
m_data
Info ReplayGain::m_data[TRACK] private
Referenced by Get(), ParseGain(), ParsePeak(), Set(), SetGain(), and SetPeak().
The documentation for this class was generated from the following files:
ReplayGain.h
ReplayGain.cpp