Kodi Documentation: KODI::ADDONS::CScreenSaver Class Reference
KODI::ADDONS::CScreenSaver Class Reference
#include <ScreenSaver.h>
Public Member Functions
CScreenSaver (const ADDON::AddonInfoPtr &addonInfo)
~CScreenSaver () override
bool Start ()
void Stop ()
void Render ()
void GetProperties (struct KODI_ADDON_SCREENSAVER_PROPS *props)
Public Member Functions inherited from ADDON::IAddonInstanceHandler
IAddonInstanceHandler (ADDON_TYPE type, const AddonInfoPtr &addonInfo, AddonInstanceId instanceId=ADDON_INSTANCE_ID_UNUSED, KODI_HANDLE parentInstance=nullptr, const std::string &uniqueWorkID="")
Class constructor for handling add-on instance processes, allowing an add-on to handle multiple work simultaneously and independently.
virtual ~IAddonInstanceHandler ()
ADDON_TYPE UsedType () const
AddonInstanceId InstanceId () const
const std::string & UniqueWorkID ()
std::string ID () const
AddonInstanceId InstanceID () const
std::string Name () const
std::string Author () const
std::string Icon () const
std::string Path () const
std::string Profile () const
CAddonVersion Version () const
ADDON_STATUS CreateInstance ()
void DestroyInstance ()
const AddonDllPtr & Addon () const
AddonInfoPtr GetAddonInfo () const
virtual void OnPreInstall ()
virtual void OnPostInstall (bool update, bool modal)
virtual void OnPreUnInstall ()
virtual void OnPostUnInstall ()
Additional Inherited Members
Protected Attributes inherited from ADDON::IAddonInstanceHandler
KODI_ADDON_INSTANCE_INFO m_info {}
KODI_ADDON_INSTANCE_STRUCT m_ifc {}
Constructor & Destructor Documentation
CScreenSaver()
CScreenSaver::CScreenSaver (const ADDON::AddonInfoPtr & addonInfo) explicit
References ADDON_STATUS_OK, ADDON::IAddonInstanceHandler::CreateInstance(), AddonToKodiFuncTable_Screensaver::get_properties, ADDON::IAddonInstanceHandler::ID(), CLog::Log(), LOGFATAL, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::screensaver, AddonInstance_Screensaver::toAddon, and AddonInstance_Screensaver::toKodi.
~CScreenSaver()
CScreenSaver::~CScreenSaver () override
References ADDON::IAddonInstanceHandler::DestroyInstance(), ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::screensaver, AddonInstance_Screensaver::toAddon, and AddonInstance_Screensaver::toKodi.
Member Function Documentation
GetProperties()
void CScreenSaver::GetProperties (struct KODI_ADDON_SCREENSAVER_PROPS * props)
References KODI_ADDON_SCREENSAVER_PROPS::device, CServiceBroker::GetWinSystem(), KODI_ADDON_SCREENSAVER_PROPS::height, KODI_ADDON_SCREENSAVER_PROPS::pixelRatio, KODI_ADDON_SCREENSAVER_PROPS::width, KODI_ADDON_SCREENSAVER_PROPS::x, and KODI_ADDON_SCREENSAVER_PROPS::y.
Render()
void CScreenSaver::Render ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, KodiToAddonFuncTable_Screensaver::render, KODI_ADDON_INSTANCE_STRUCT::screensaver, and AddonInstance_Screensaver::toAddon.
Start()
bool CScreenSaver::Start ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::screensaver, KodiToAddonFuncTable_Screensaver::start, and AddonInstance_Screensaver::toAddon.
Stop()
void CScreenSaver::Stop ()
References KODI_ADDON_INSTANCE_STRUCT::hdl, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_INSTANCE_STRUCT::screensaver, KodiToAddonFuncTable_Screensaver::stop, and AddonInstance_Screensaver::toAddon.
The documentation for this class was generated from the following files:
ScreenSaver.h
ScreenSaver.cpp