Kodi Documentation: CDirtyRegionTracker Class Reference
CDirtyRegionTracker Class Reference
#include <DirtyRegionTracker.h>
Public Member Functions
CDirtyRegionTracker (int buffering=DEFAULT_BUFFERING)
~CDirtyRegionTracker ()
void SelectAlgorithm ()
void MarkDirtyRegion (const CDirtyRegion &region)
const CDirtyRegionList & GetMarkedRegions () const
CDirtyRegionList GetDirtyRegions ()
void CleanMarkedRegions ()
Private Attributes
CDirtyRegionList m_markedRegions
int m_buffering
IDirtyRegionSolver * m_solver
Constructor & Destructor Documentation
CDirtyRegionTracker()
CDirtyRegionTracker::CDirtyRegionTracker (int buffering = DEFAULT_BUFFERING) explicit
References m_buffering, and m_solver.
~CDirtyRegionTracker()
CDirtyRegionTracker::~CDirtyRegionTracker ()
References m_solver.
Member Function Documentation
CleanMarkedRegions()
void CDirtyRegionTracker::CleanMarkedRegions ()
References CServiceBroker::GetSettingsComponent(), m_buffering, and m_markedRegions.
GetDirtyRegions()
CDirtyRegionList CDirtyRegionTracker::GetDirtyRegions ()
References m_markedRegions, m_solver, and IDirtyRegionSolver::Solve().
GetMarkedRegions()
const CDirtyRegionList & CDirtyRegionTracker::GetMarkedRegions () const
References m_markedRegions.
MarkDirtyRegion()
void CDirtyRegionTracker::MarkDirtyRegion (const CDirtyRegion & region)
References CRectGen< T >::IsEmpty(), and m_markedRegions.
SelectAlgorithm()
void CDirtyRegionTracker::SelectAlgorithm ()
References DIRTYREGION_SOLVER_COST_REDUCTION, DIRTYREGION_SOLVER_FILL_VIEWPORT_ALWAYS, DIRTYREGION_SOLVER_FILL_VIEWPORT_ON_CHANGE, DIRTYREGION_SOLVER_UNION, CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, and m_solver.
Member Data Documentation
m_buffering
int CDirtyRegionTracker::m_buffering private
Referenced by CDirtyRegionTracker(), and CleanMarkedRegions().
m_markedRegions
CDirtyRegionList CDirtyRegionTracker::m_markedRegions private
Referenced by CleanMarkedRegions(), GetDirtyRegions(), GetMarkedRegions(), and MarkDirtyRegion().
m_solver
IDirtyRegionSolver* CDirtyRegionTracker::m_solver private
Referenced by CDirtyRegionTracker(), GetDirtyRegions(), SelectAlgorithm(), and ~CDirtyRegionTracker().
The documentation for this class was generated from the following files:
DirtyRegionTracker.h
DirtyRegionTracker.cpp