Kodi Documentation: CPlatformWin10 Class Reference
CPlatformWin10 Class Reference
#include <PlatformWin10.h>
Public Member Functions
CPlatformWin10 ()=default
C'tor.
~CPlatformWin10 () override=default
D'tor.
bool InitStageOne () override
Called at an early stage of application startup.
void PlatformSyslog () override
Print platform specific info to log.
bool SupportsUserInstalledBinaryAddons () override
Flag whether this platform supports user installation of binary add-ons.
Public Member Functions inherited from CPlatform
CPlatform ()=default
C'tor.
virtual ~CPlatform ()=default
D'tor.
virtual bool InitStageTwo ()
Called at a middle stage of application startup.
virtual bool InitStageThree ()
Called at a late stage of application startup.
virtual void DeinitStageOne ()
Called at a late stage of application shutdown.
virtual void DeinitStageTwo ()
Called at a middle stage of application shutdown.
virtual void DeinitStageThree ()
Called at an early stage of application shutdown.
virtual bool IsConfigureAddonsAtStartupEnabled ()
Flag whether disabled add-ons - installed via packagemanager or manually - should be offered for configuration and activation on kodi startup for this platform.
template<class T >
std::shared_ptr< T > GetService ()
Get a platform service instance.
Public Member Functions inherited from CComponentContainer< IPlatformService >
std::shared_ptr< T > GetComponent ()
Obtain a component.
std::shared_ptr< const T > GetComponent () const
Obtain a component.
std::size_t size () const
Returns number of registered components.
Additional Inherited Members
Static Public Member Functions inherited from CPlatform
static CPlatform * CreateInstance ()
Creates the Platform object.
Protected Member Functions inherited from CComponentContainer< IPlatformService >
void RegisterComponent (const std::shared_ptr< IPlatformService > &component)
Register a new component instance.
void DeregisterComponent (const std::type_info &typeInfo)
Deregister a component.
Constructor & Destructor Documentation
CPlatformWin10()
CPlatformWin10::CPlatformWin10 () default
C'tor.
~CPlatformWin10()
CPlatformWin10::~CPlatformWin10 () override default
D'tor.
Member Function Documentation
InitStageOne()
bool CPlatformWin10::InitStageOne () override virtual
Called at an early stage of application startup.
This method can be used to do platform specific environment preparation or initialisation (like setting environment variables for example)
Reimplemented from CPlatform.
References CPlatform::InitStageOne(), CPowerSyscall::Register(), CWinSystemWin10DX::Register(), CEnvironment::setenv(), and CWIN32Util::SetThreadLocalLocale().
PlatformSyslog()
void CPlatformWin10::PlatformSyslog () override virtual
Print platform specific info to log.
Logs platform specific system info during application creation startup
Reimplemented from CPlatform.
References CWIN32Util::PlatformSyslog().
SupportsUserInstalledBinaryAddons()
bool CPlatformWin10::SupportsUserInstalledBinaryAddons () override virtual
Flag whether this platform supports user installation of binary add-ons.
Reimplemented from CPlatform.
The documentation for this class was generated from the following files:
PlatformWin10.h
PlatformWin10.cpp