Kodi Documentation: CDVDTeletextTools Class Reference
CDVDTeletextTools Class Reference
#include <TeletextDefines.h>
Static Public Member Functions
static void NextDec (int *i)
static void PrevDec (int *i)
static void Hex2Str (char *s, unsigned int n)
static signed int deh24 (unsigned char *p)
Member Function Documentation
deh24()
signed int CDVDTeletextTools::deh24 (unsigned char * p) static
References hamm24cor, hamm24err, hamm24par, and hamm24val.
Referenced by CDVDTeletextData::Decode_p2829(), CTeletextDecoder::DecodePage(), CTeletextDecoder::Eval_NumberedObject(), CTeletextDecoder::iTripletNumber2Data(), and CDVDTeletextData::Process().
Hex2Str()
void CDVDTeletextTools::Hex2Str (char * s, unsigned int n) static
References number2char.
Referenced by CTeletextDecoder::DecodePage(), CTeletextDecoder::RenderPage(), and CTeletextDecoder::Showlink().
NextDec()
void CDVDTeletextTools::NextDec (int * i) static
Referenced by CTeletextDecoder::Decode_BTT(), CTeletextDecoder::GetNextPageOne(), and CTeletextDecoder::TopText_GetNext().
PrevDec()
void CDVDTeletextTools::PrevDec (int * i) static
Referenced by CTeletextDecoder::GetNextPageOne(), and CTeletextDecoder::TopText_GetNext().
The documentation for this class was generated from the following files:
TeletextDefines.h
VideoPlayerTeletext.cpp