Kodi Documentation: CDecoderFilter Class Reference
CDecoderFilter Class Reference
Declaration of CDecoderFilter.
#include <DecoderFilterManager.h>
Public Types
enum : uint32_t { FLAG_GENERAL_ALLOWED = 1 , FLAG_STILLS_ALLOWED = 2 , FLAG_DVD_ALLOWED = 4 }
Flags to control decoder validity.
Public Member Functions
CDecoderFilter (const std::string &name)
constructs a CDecoderFilter
CDecoderFilter (const std::string &name, uint32_t flags, int minHeight)
virtual ~CDecoderFilter ()=default
bool operator< (const CDecoderFilter &other) const
used for sorting / replacing / find
virtual bool isValid (const CDVDStreamInfo &streamInfo) const
test if stream is allowed by filter.
virtual bool Load (const tinyxml2::XMLNode *node)
load all members from XML node
virtual bool Save (tinyxml2::XMLNode *node) const
store all members in XML node
Private Attributes
std::string m_name
uint32_t m_flags = 0
int m_minHeight = 0
Detailed Description
Declaration of CDecoderFilter.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint32_t
Flags to control decoder validity.
Enumerator
FLAG_GENERAL_ALLOWED
early false exit if set
FLAG_STILLS_ALLOWED
early false exit if set and stream is marked as "has stillframes"
FLAG_DVD_ALLOWED
early false exit if set and stream is marked as dvd
Constructor & Destructor Documentation
CDecoderFilter() [1/2]
CDecoderFilter::CDecoderFilter (const std::string & name) inline
constructs a CDecoderFilter
Parameters
name decodername
Returns
nothing.
CDecoderFilter() [2/2]
CDecoderFilter::CDecoderFilter (const std::string & name, uint32_t flags, int minHeight)
~CDecoderFilter()
virtual CDecoderFilter::~CDecoderFilter () virtual default
Member Function Documentation
isValid()
CDecoderFilter::isValid (const CDVDStreamInfo & streamInfo) const virtual
test if stream is allowed by filter.
Returns
true if valid, false otherwise
References CDVDStreamInfo::dvd, FLAG_DVD_ALLOWED, FLAG_GENERAL_ALLOWED, FLAG_STILLS_ALLOWED, CDVDStreamInfo::height, m_flags, m_minHeight, and CDVDStreamInfo::stills.
Load()
CDecoderFilter::Load (const tinyxml2::XMLNode * node) virtual
load all members from XML node
Parameters
node filter node from where to get the values
Returns
true if operation was successful, false on error
References FLAG_DVD_ALLOWED, FLAG_GENERAL_ALLOWED, FLAG_STILLS_ALLOWED, XMLUtils::GetBoolean(), XMLUtils::GetInt(), XMLUtils::GetString(), m_flags, m_minHeight, m_name, node, TAG_DVD, TAG_GENERAL, TAG_MINHEIGHT, TAG_NAME, and TAG_STILLS.
Referenced by CDecoderFilterManager::Load().
operator<()
CDecoderFilter::operator< (const CDecoderFilter & other) const inline
used for sorting / replacing / find
References m_name.
Save()
CDecoderFilter::Save (tinyxml2::XMLNode * node) const virtual
store all members in XML node
Parameters
node a ready to use filter setting node
Returns
true if operation was successful, false on error
References FLAG_DVD_ALLOWED, FLAG_GENERAL_ALLOWED, FLAG_STILLS_ALLOWED, m_flags, m_minHeight, m_name, node, XMLUtils::SetBoolean(), XMLUtils::SetInt(), XMLUtils::SetString(), TAG_DVD, TAG_GENERAL, TAG_MINHEIGHT, TAG_NAME, and TAG_STILLS.
Member Data Documentation
m_flags
uint32_t CDecoderFilter::m_flags = 0 private
Referenced by isValid(), Load(), and Save().
m_minHeight
int CDecoderFilter::m_minHeight = 0 private
Referenced by isValid(), Load(), and Save().
m_name
std::string CDecoderFilter::m_name private
Referenced by Load(), operator<(), and Save().
The documentation for this class was generated from the following files:
DecoderFilterManager.h
DecoderFilterManager.cpp