Kodi Documentation: PVR::CPVRDatabase Class Reference
PVR::CPVRDatabase Class Reference
#include <PVRDatabase.h>
Public Member Functions
CPVRDatabase ()=default
Create a new instance of the PVR database.
~CPVRDatabase () override=default
bool Open () override
Open the database.
void Close () override
Close the database.
void Lock ()
Lock the database.
void Unlock ()
Unlock the database.
int GetSchemaVersion () const override
Get the minimal database version that is required to operate correctly.
const char * GetBaseDBName () const override
Get the default sqlite database filename.
Channel methods
bool DeleteChannels ()
Remove all channels from the database.
int Get (bool bRadio, const std::vector< std::shared_ptr< CPVRClient > > &clients, std::map< std::pair< int, int >, std::shared_ptr< CPVRChannel > > &results) const
Get channels from the database.
bool Persist (CPVRChannel &channel, bool bCommit)
Add or update a channel entry in the database.
bool QueueDeleteQuery (const CPVRChannel &channel)
Remove a channel entry from the database.
Channel group member methods
bool QueueDeleteQuery (const CPVRChannelGroupMember &groupMember)
Remove a channel group member entry from the database.
Channel provider methods
bool DeleteProviders ()
Remove all providers from the database.
bool Persist (CPVRProvider &provider, bool updateRecord=false)
Add or update a provider entry in the database.
bool Delete (const CPVRProvider &provider)
Remove a provider entry from the database.
bool Get (CPVRProviders &results, const std::vector< std::shared_ptr< CPVRClient > > &clients) const
Get the list of providers from the database.
int GetMaxProviderId () const
Get the maximum provider id in the database.
Channel group methods
bool DeleteChannelGroups ()
Remove all channel groups from the database.
bool Delete (const CPVRChannelGroup &group)
Delete a channel group and all its members from the database.
int GetLocalGroups (CPVRChannelGroups &results) const
Get all local channel groups.
int Get (CPVRChannelGroups &results, const std::vector< std::shared_ptr< CPVRClient > > &clients) const
Get client-supplied channel groups.
std::vector< std::shared_ptr< CPVRChannelGroupMember > > Get (const CPVRChannelGroup &group, const std::vector< std::shared_ptr< CPVRClient > > &clients) const
Get the members of a channel group.
bool Persist (CPVRChannelGroup &group)
Add or update a channel group entry in the database.
bool ResetEPG ()
Reset all epg ids to 0.
Timer methods
std::vector< std::shared_ptr< CPVRTimerInfoTag > > GetTimers (CPVRTimers &timers, const std::vector< std::shared_ptr< CPVRClient > > &clients) const
Get the timers.
bool Persist (CPVRTimerInfoTag &timer)
Add or update a timer entry in the database.
bool Delete (const CPVRTimerInfoTag &timer)
Remove a timer from the database.
bool DeleteTimers ()
Remove all timer entries from the database.
Public Member Functions inherited from CDatabase
CDatabase ()
virtual ~CDatabase (void)
bool IsOpen ()
bool Compress (bool bForce=true)
void Interrupt ()
bool Open (const DatabaseSettings &db)
void BeginTransaction ()
virtual bool CommitTransaction ()
void RollbackTransaction ()
void CopyDB (const std::string &latestDb)
void DropAnalytics ()
std::string PrepareSQL (std::string strStmt,...) const
std::string GetSingleValue (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single value from a table.
std::string GetSingleValue (const std::string &query) const
std::string GetSingleValue (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single value from a query on a dataset.
int GetSingleValueInt (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single integer value from a table.
int GetSingleValueInt (const std::string &query) const
int GetSingleValueInt (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single integer value from a query on a dataset.
bool DeleteValues (const std::string &strTable, const Filter &filter=Filter())
Delete values from a table.
bool ExecuteQuery (const std::string &strQuery)
Execute a query that does not return any result. Note that if BeginMultipleExecute() has been called, the query will be queued until CommitMultipleExecute() is called.
bool ResultQuery (const std::string &strQuery) const
Execute a query that returns a result.
bool BeginMultipleExecute ()
Start a multiple execution queue. Any ExecuteQuery() function following this call will be queued rather than executed until CommitMultipleExecute() is performed. NOTE: Queries that rely on any queued execute query will not function as expected during this period!
bool CommitMultipleExecute ()
Commit the multiple execution queue to the database. Queries are performed within a transaction, and the transaction is rolled back should any one query fail.
bool QueueInsertQuery (const std::string &strQuery)
Put an INSERT or REPLACE query in the queue.
bool CommitInsertQueries ()
Commit all queries in the queue.
size_t GetInsertQueriesCount ()
Get the number of INSERT queries in the queue.
bool QueueDeleteQuery (const std::string &strQuery)
Put a DELETE query in the queue.
bool CommitDeleteQueries ()
Commit all queued DELETE queries.
size_t GetDeleteQueriesCount ()
Get the number of DELETE queries in the queue.
virtual bool GetFilter (CDbUrl &dbUrl, Filter &filter, SortDescription &sorting)
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl)
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl, SortDescription &sorting)
bool Connect (const std::string &dbName, const DatabaseSettings &db, bool create)
Client methods
CCriticalSection m_critSection
bool DeleteClients ()
Remove all client entries from the database.
bool Persist (const CPVRClient &client)
Add or update a client entry in the database.
bool Delete (const CPVRClient &client)
Remove a client entry from the database.
int GetPriority (const CPVRClient &client) const
Get the priority for a given client from the database.
CDateTime GetDateTimeFirstChannelsAdded (const CPVRClient &client) const
Get the date and time first channels were added for the given client.
int GetClientID (const std::string &addonID, unsigned int instanceID)
Get the numeric client ID for given addon ID and instance ID from the database.
bool UpdateLastWatched (const CPVRChannel &channel, int groupId)
Updates the last watched timestamp for the channel.
bool UpdateLastWatched (const CPVRChannelGroup &group)
Updates the last watched timestamp for the channel group.
bool UpdateLastOpened (const CPVRChannelGroup &group)
Updates the last opened timestamp for the channel group.
void CreateTables () override
Create the PVR database tables.
void CreateAnalytics () override
void UpdateTables (int version) override
Update an old version of the database.
int GetMinSchemaVersion () const override
int GetGroups (CPVRChannelGroups &results, const std::string &query) const
bool PersistGroupMembers (const CPVRChannelGroup &group)
bool PersistChannels (const CPVRChannelGroup &group)
bool RemoveChannelsFromGroup (const CPVRChannelGroup &group)
void FixupClientIDs ()
Additional Inherited Members
Protected Member Functions inherited from CDatabase
void Split (const std::string &strFileNameAndPath, std::string &strPath, std::string &strFileName)
bool CreateDatabase ()
Create database tables and analytics as needed. Calls CreateTables() and CreateAnalytics() on child classes.
int GetDBVersion ()
bool BuildSQL (const std::string &strQuery, const Filter &filter, std::string &strSQL) const
Protected Attributes inherited from CDatabase
bool m_sqlite
whether we use sqlite (defaults to true)
std::unique_ptr< dbiplus::Database > m_pDB
std::unique_ptr< dbiplus::Dataset > m_pDS
std::unique_ptr< dbiplus::Dataset > m_pDS2
const CProfileManager & m_profileManager
Constructor & Destructor Documentation
CPVRDatabase()
PVR::CPVRDatabase::CPVRDatabase () default
Create a new instance of the PVR database.
~CPVRDatabase()
PVR::CPVRDatabase::~CPVRDatabase () override default
Member Function Documentation
Close()
void CPVRDatabase::Close () override virtual
Close the database.
Reimplemented from CDatabase.
References CDatabase::Close(), and m_critSection.
CreateAnalytics()
void CPVRDatabase::CreateAnalytics () override private virtual
Implements CDatabase.
References LOGINFO, m_critSection, and CDatabase::m_pDS.
CreateTables()
void CPVRDatabase::CreateTables () override private virtual
Create the PVR database tables.
Todo:
use mapping table
Implements CDatabase.
References LOGDEBUG, LOGINFO, LOGPVR, m_critSection, and CDatabase::m_pDS.
Delete() [1/4]
bool CPVRDatabase::Delete (const CPVRChannelGroup & group)
Delete a channel group and all its members from the database.
Parameters
group The group to delete.
Returns
True if the group was deleted successfully, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::DeleteValues(), LOGERROR, m_critSection, CDatabase::PrepareSQL(), and RemoveChannelsFromGroup().
Delete() [2/4]
bool CPVRDatabase::Delete (const CPVRClient & client)
Remove a client entry from the database.
Parameters
client The client to remove.
Returns
True if the client was removed, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::DeleteValues(), PVR::CPVRClient::GetID(), LOGDEBUG, LOGPVR, m_critSection, CDatabase::PrepareSQL(), and PVR::PVR_CLIENT_INVALID_UID.
Delete() [3/4]
bool CPVRDatabase::Delete (const CPVRProvider & provider)
Remove a provider entry from the database.
Parameters
provider The provider to remove.
Returns
True if the provider was removed, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::DeleteValues(), PVR::CPVRProvider::GetDatabaseId(), PVR::CPVRProvider::GetName(), LOGDEBUG, LOGPVR, m_critSection, and CDatabase::PrepareSQL().
Delete() [4/4]
bool CPVRDatabase::Delete (const CPVRTimerInfoTag & timer)
Remove a timer from the database.
Parameters
timer The timer to remove.
Returns
True if the timer was removed, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::DeleteValues(), LOGDEBUG, LOGPVR, m_critSection, PVR::CPVRTimerInfoTag::m_iClientIndex, CDatabase::PrepareSQL(), and PVR_TIMER_NO_CLIENT_INDEX.
DeleteChannelGroups()
bool CPVRDatabase::DeleteChannelGroups ()
Remove all channel groups from the database.
Returns
True if all channel groups were removed.
References CDatabase::DeleteValues(), LOGDEBUG, LOGPVR, and m_critSection.
DeleteChannels()
bool CPVRDatabase::DeleteChannels ()
Remove all channels from the database.
Returns
True if all channels were removed, false otherwise.
References CDatabase::DeleteValues(), LOGDEBUG, LOGPVR, and m_critSection.
DeleteClients()
bool CPVRDatabase::DeleteClients ()
Remove all client entries from the database.
Returns
True if all client entries were removed, false otherwise.
References CDatabase::DeleteValues(), LOGDEBUG, LOGPVR, and m_critSection.
DeleteProviders()
bool CPVRDatabase::DeleteProviders ()
Remove all providers from the database.
Returns
True if all providers were removed, false otherwise.
References CDatabase::DeleteValues(), LOGDEBUG, LOGPVR, and m_critSection.
DeleteTimers()
bool CPVRDatabase::DeleteTimers ()
Remove all timer entries from the database.
Returns
True if all timer entries were removed, false otherwise.
References CDatabase::DeleteValues(), LOGDEBUG, LOGPVR, and m_critSection.
FixupClientIDs()
void CPVRDatabase::FixupClientIDs () private
References CDatabase::ExecuteQuery(), ADDON::CAddonMgr::GetAddonInfos(), CServiceBroker::GetAddonMgr(), PVR::CPVRClientUID::GetLegacyUID(), CDatabase::GetSingleValueInt(), CLog::Log(), LOGERROR, CDatabase::m_pDS, CDatabase::PrepareSQL(), ADDON::PVRDLL, and CDatabase::ResultQuery().
Referenced by UpdateTables().
Get() [1/4]
int CPVRDatabase::Get (bool bRadio, const std::vector< std::shared_ptr< CPVRClient > > & clients, std::map< std::pair< int, int >, std::shared_ptr< CPVRChannel > > & results) const
Get channels from the database.
Parameters
bRadio Whether to fetch radio or TV channels.
clients The PVR clients the channels should be loaded for. Leave empty for all clients.
results The container for the channels.
Returns
The number of channels loaded.
References CDateTime::FromDBDateTime(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
Get() [2/4]
std::vector< std::shared_ptr< CPVRChannelGroupMember > > CPVRDatabase::Get (const CPVRChannelGroup & group, const std::vector< std::shared_ptr< CPVRClient > > & clients) const
Get the members of a channel group.
Parameters
group The group to get the members for.
clients The PVR clients the group members should be loaded for. Leave empty for all clients.
Returns
The group members.
References LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
Get() [3/4]
int CPVRDatabase::Get (CPVRChannelGroups & results, const std::vector< std::shared_ptr< CPVRClient > > & clients) const
Get client-supplied channel groups.
Parameters
results The container to store the results in.
clients The PVR clients the groups should be loaded for. Leave empty for all clients.
Returns
The number of groups loaded.
References GetGroups(), PVR::CPVRChannelGroups::IsRadio(), m_critSection, and CDatabase::PrepareSQL().
Get() [4/4]
bool CPVRDatabase::Get (CPVRProviders & results, const std::vector< std::shared_ptr< CPVRClient > > & clients) const
Get the list of providers from the database.
Parameters
results The providers to store the results in.
clients The PVR clients the providers should be loaded for. Leave empty for all clients.
Returns
The amount of providers that were added.
References PVR::BY_DATABASE, PVR::CPVRProviders::CheckAndAddEntry(), LOGDEBUG, LOGERROR, LOGPVR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and CDatabase::ResultQuery().
GetBaseDBName()
const char * PVR::CPVRDatabase::GetBaseDBName () const inline override virtual
Get the default sqlite database filename.
Returns
The default filename.
Implements CDatabase.
GetClientID()
int CPVRDatabase::GetClientID (const std::string & addonID, unsigned int instanceID)
Get the numeric client ID for given addon ID and instance ID from the database.
Parameters
addonID The addon ID.
instanceID The instance ID.
Returns
The client ID on success, PVR_CLIENT_INVALID_UID otherwise.
References CDatabase::ExecuteQuery(), CDatabase::GetSingleValue(), m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and PVR::PVR_CLIENT_INVALID_UID.
Referenced by PVR::CPVRClientUID::GetUID().
GetDateTimeFirstChannelsAdded()
CDateTime CPVRDatabase::GetDateTimeFirstChannelsAdded (const CPVRClient & client) const
Get the date and time first channels were added for the given client.
Parameters
client The client.
Returns
The date and time first channels were added.
References CDateTime::FromDBDateTime(), PVR::CPVRClient::GetID(), CDatabase::GetSingleValue(), LOGDEBUG, LOGPVR, m_critSection, CDatabase::PrepareSQL(), PVR::PVR_CLIENT_INVALID_UID, and value.
GetGroups()
int CPVRDatabase::GetGroups (CPVRChannelGroups & results, const std::string & query) const private
References PVR::CPVRChannelGroups::GetGroupAll(), PVR::CPVRChannelGroups::GetGroupFactory(), LOGDEBUG, LOGERROR, LOGPVR, CDatabase::m_pDS, CDatabase::ResultQuery(), and PVR::CPVRChannelGroups::Update().
Referenced by Get(), and GetLocalGroups().
GetLocalGroups()
int CPVRDatabase::GetLocalGroups (CPVRChannelGroups & results) const
Get all local channel groups.
Parameters
results The container to store the results in.
Returns
The number of groups loaded.
References GetGroups(), PVR::CPVRChannelGroups::IsRadio(), m_critSection, and CDatabase::PrepareSQL().
GetMaxProviderId()
int CPVRDatabase::GetMaxProviderId () const
Get the maximum provider id in the database.
Returns
The maximum provider id in the database
References CDatabase::GetSingleValueInt(), m_critSection, and CDatabase::PrepareSQL().
GetMinSchemaVersion()
int PVR::CPVRDatabase::GetMinSchemaVersion () const inline override private virtual
Reimplemented from CDatabase.
GetPriority()
int CPVRDatabase::GetPriority (const CPVRClient & client) const
Get the priority for a given client from the database.
Parameters
client The client.
Returns
The priority.
References PVR::CPVRClient::GetID(), CDatabase::GetSingleValue(), LOGDEBUG, LOGPVR, m_critSection, CDatabase::PrepareSQL(), and PVR::PVR_CLIENT_INVALID_UID.
GetSchemaVersion()
int PVR::CPVRDatabase::GetSchemaVersion () const inline override virtual
Get the minimal database version that is required to operate correctly.
Returns
The minimal database version.
Implements CDatabase.
GetTimers()
std::vector< std::shared_ptr< CPVRTimerInfoTag > > CPVRDatabase::GetTimers (CPVRTimers & timers, const std::vector< std::shared_ptr< CPVRClient > > & clients) const
Get the timers.
Parameters
timers The container for the timers.
clients The PVR clients the timers should be loaded for. Leave empty for all clients.
Returns
The timers.
References PVR::CPVRTimerType::CreateFromIds(), CDateTime::FromDBDateTime(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), PVR::PVR_CLIENT_INVALID_UID, and CDatabase::ResultQuery().
Lock()
void CPVRDatabase::Lock ()
Lock the database.
References m_critSection.
Open()
bool CPVRDatabase::Open () override virtual
Open the database.
Returns
True if it was opened successfully, false otherwise.
Reimplemented from CDatabase.
References CServiceBroker::GetSettingsComponent(), m_critSection, and CDatabase::Open().
Referenced by PVR::CPVRClientUID::GetUID().
Persist() [1/5]
bool CPVRDatabase::Persist (const CPVRClient & client)
Add or update a client entry in the database.
Parameters
client The client to persist.
Returns
True when persisted, false otherwise.
References CDatabase::ExecuteQuery(), CDateTime::GetAsDBDateTime(), PVR::CPVRClient::GetDateTimeFirstChannelsAdded(), PVR::CPVRClient::GetID(), PVR::CPVRClient::GetPriority(), ADDON::IAddonInstanceHandler::ID(), ADDON::IAddonInstanceHandler::InstanceID(), LOGDEBUG, LOGPVR, m_critSection, CDatabase::PrepareSQL(), and PVR::PVR_CLIENT_INVALID_UID.
Referenced by PersistChannels().
Persist() [2/5]
bool CPVRDatabase::Persist (CPVRChannel & channel, bool bCommit)
Add or update a channel entry in the database.
Parameters
channel The channel to persist.
bCommit queue only or queue and commit
Returns
True when persisted or queued, false otherwise.
References PVR::CPVRChannel::ChannelName(), PVR::CPVRChannel::ClientIconPath(), PVR::CPVRChannel::ClientID(), PVR::CPVRChannel::ClientProviderUid(), CDatabase::CommitInsertQueries(), PVR::CPVRChannel::DateTimeAdded(), PVR::CPVRChannel::EPGEnabled(), PVR::CPVRChannel::EpgID(), PVR::CPVRChannel::EPGScraper(), CDateTime::GetAsDBDateTime(), CDatabase::GetSingleValue(), PVR::CPVRChannel::HasArchive(), PVR::CPVRChannel::IconPath(), PVR::CPVRChannel::IsHidden(), PVR::CPVRChannel::IsLocked(), PVR::CPVRChannel::IsRadio(), PVR::CPVRChannel::IsUserSetHidden(), PVR::CPVRChannel::IsUserSetIcon(), PVR::CPVRChannel::IsUserSetName(), CDateTime::IsValid(), PVR::CPVRChannel::LastWatched(), PVR::CPVRChannel::LastWatchedGroupId(), LOGERROR, m_critSection, CDatabase::PrepareSQL(), CDatabase::QueueInsertQuery(), and PVR::CPVRChannel::UniqueID().
Persist() [3/5]
bool CPVRDatabase::Persist (CPVRChannelGroup & group)
Add or update a channel group entry in the database.
Parameters
group The group to persist.
Returns
True if the group was persisted successfully, false otherwise.
References CDatabase::ExecuteQuery(), LOGERROR, m_critSection, CDatabase::m_pDS, PersistChannels(), PersistGroupMembers(), and CDatabase::PrepareSQL().
Persist() [4/5]
bool CPVRDatabase::Persist (CPVRProvider & provider, bool updateRecord = false)
Add or update a provider entry in the database.
Parameters
provider The provider to persist.
updateRecord True if record to be updated, false for insert
Returns
True when persisted, false otherwise.
References CDatabase::ExecuteQuery(), PVR::CPVRProvider::GetClientIconPath(), PVR::CPVRProvider::GetClientId(), PVR::CPVRProvider::GetCountriesDBString(), PVR::CPVRProvider::GetDatabaseId(), PVR::CPVRProvider::GetLanguagesDBString(), PVR::CPVRProvider::GetName(), PVR::CPVRProvider::GetType(), PVR::CPVRProvider::GetUniqueId(), LOGERROR, m_critSection, CDatabase::m_pDS, CDatabase::PrepareSQL(), and PVR::CPVRProvider::SetDatabaseId().
Persist() [5/5]
bool CPVRDatabase::Persist (CPVRTimerInfoTag & timer)
Add or update a timer entry in the database.
Parameters
channel The timer to persist.
Returns
True if persisted, false otherwise.
References PVR::CPVRTimerInfoTag::EndAsUTC(), CDatabase::ExecuteQuery(), PVR::CPVRTimerInfoTag::FirstDayAsUTC(), CDateTime::GetAsDBDateTime(), PVR::CPVRTimerInfoTag::GetTimerType(), PVR::CPVRTimerInfoTag::m_bEndAnyTime, PVR::CPVRTimerInfoTag::m_bFullTextEpgSearch, PVR::CPVRTimerInfoTag::m_bStartAnyTime, m_critSection, PVR::CPVRTimerInfoTag::m_iClientChannelUid, PVR::CPVRTimerInfoTag::m_iClientId, PVR::CPVRTimerInfoTag::m_iClientIndex, PVR::CPVRTimerInfoTag::m_iLifetime, PVR::CPVRTimerInfoTag::m_iMarginEnd, PVR::CPVRTimerInfoTag::m_iMarginStart, PVR::CPVRTimerInfoTag::m_iMaxRecordings, PVR::CPVRTimerInfoTag::m_iParentClientIndex, PVR::CPVRTimerInfoTag::m_iPreventDupEpisodes, PVR::CPVRTimerInfoTag::m_iPriority, PVR::CPVRTimerInfoTag::m_iRecordingGroup, PVR::CPVRTimerInfoTag::m_iWeekdays, CDatabase::m_pDS, PVR::CPVRTimerInfoTag::m_state, PVR::CPVRTimerInfoTag::m_strEpgSearchString, CDatabase::PrepareSQL(), PVR_TIMER_NO_CLIENT_INDEX, PVR::CPVRTimerInfoTag::SeriesLink(), PVR::CPVRTimerInfoTag::StartAsUTC(), PVR::CPVRTimerInfoTag::Title(), and PVR::CPVRTimerInfoTag::UniqueBroadcastID().
PersistChannels()
bool CPVRDatabase::PersistChannels (const CPVRChannelGroup & group) private
References CDatabase::CommitInsertQueries(), CDatabase::GetSingleValue(), LOGERROR, Persist(), and CDatabase::PrepareSQL().
Referenced by Persist().
PersistGroupMembers()
bool CPVRDatabase::PersistGroupMembers (const CPVRChannelGroup & group) private
References CDatabase::CommitInsertQueries(), CDatabase::GetSingleValue(), LOGERROR, CDatabase::PrepareSQL(), and CDatabase::QueueInsertQuery().
Referenced by Persist().
QueueDeleteQuery() [1/2]
bool CPVRDatabase::QueueDeleteQuery (const CPVRChannel & channel)
Remove a channel entry from the database.
Parameters
channel The channel to remove.
Returns
True if the channel was removed, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), PVR::CPVRChannel::ChannelID(), PVR::CPVRChannel::ChannelName(), LOGDEBUG, LOGERROR, LOGPVR, CDatabase::PrepareSQL(), and CDatabase::QueueDeleteQuery().
QueueDeleteQuery() [2/2]
bool CPVRDatabase::QueueDeleteQuery (const CPVRChannelGroupMember & groupMember)
Remove a channel group member entry from the database.
Parameters
groupMember The group member to remove.
Returns
True if the member was removed, false otherwise.
References CDatabase::Filter::AppendWhere(), CDatabase::BuildSQL(), PVR::CPVRChannelGroupMember::Channel(), PVR::CPVRChannelGroupMember::ChannelDatabaseID(), PVR::CPVRChannelGroupMember::GroupID(), LOGDEBUG, LOGPVR, CDatabase::PrepareSQL(), and CDatabase::QueueDeleteQuery().
RemoveChannelsFromGroup()
bool CPVRDatabase::RemoveChannelsFromGroup (const CPVRChannelGroup & group) private
References CDatabase::Filter::AppendWhere(), CDatabase::DeleteValues(), m_critSection, and CDatabase::PrepareSQL().
Referenced by Delete().
ResetEPG()
bool CPVRDatabase::ResetEPG ()
Reset all epg ids to 0.
Returns
True when reset, false otherwise.
References CDatabase::ExecuteQuery(), m_critSection, and CDatabase::PrepareSQL().
Unlock()
void CPVRDatabase::Unlock ()
Unlock the database.
References m_critSection.
UpdateLastOpened()
bool CPVRDatabase::UpdateLastOpened (const CPVRChannelGroup & group)
Updates the last opened timestamp for the channel group.
Parameters
group the group
Returns
whether the update was successful
References CDatabase::ExecuteQuery(), m_critSection, and CDatabase::PrepareSQL().
UpdateLastWatched() [1/2]
bool CPVRDatabase::UpdateLastWatched (const CPVRChannel & channel, int groupId)
Updates the last watched timestamp for the channel.
Parameters
channel the channel
groupId the id of the group used to watch the channel
Returns
whether the update was successful
References PVR::CPVRChannel::ChannelID(), CDatabase::ExecuteQuery(), PVR::CPVRChannel::LastWatched(), m_critSection, and CDatabase::PrepareSQL().
UpdateLastWatched() [2/2]
bool CPVRDatabase::UpdateLastWatched (const CPVRChannelGroup & group)
Updates the last watched timestamp for the channel group.
Parameters
group the group
Returns
whether the update was successful
References CDatabase::ExecuteQuery(), m_critSection, and CDatabase::PrepareSQL().
UpdateTables()
void CPVRDatabase::UpdateTables (int version) override private virtual
Update an old version of the database.
Parameters
version The version to update the database from.
Reimplemented from CDatabase.
References FixupClientIDs(), LOGERROR, LOGPVR, m_critSection, and CDatabase::m_pDS.
Member Data Documentation
m_critSection
CCriticalSection PVR::CPVRDatabase::m_critSection mutable private
Referenced by Close(), CreateAnalytics(), CreateTables(), Delete(), Delete(), Delete(), Delete(), DeleteChannelGroups(), DeleteChannels(), DeleteClients(), DeleteProviders(), DeleteTimers(), Get(), Get(), Get(), Get(), GetClientID(), GetDateTimeFirstChannelsAdded(), GetLocalGroups(), GetMaxProviderId(), GetPriority(), GetTimers(), Lock(), Open(), Persist(), Persist(), Persist(), Persist(), Persist(), RemoveChannelsFromGroup(), ResetEPG(), Unlock(), UpdateLastOpened(), UpdateLastWatched(), UpdateLastWatched(), and UpdateTables().
The documentation for this class was generated from the following files:
PVRDatabase.h
PVRDatabase.cpp