Kodi Documentation: XFILE::CDirectoryCache Class Reference
XFILE::CDirectoryCache Class Reference
#include <DirectoryCache.h>
Classes
class CDir
Public Member Functions
CDirectoryCache (void)
virtual ~CDirectoryCache (void)
bool GetDirectory (const std::string &strPath, CFileItemList &items, bool retrieveAll=false)
void SetDirectory (const std::string &strPath, const CFileItemList &items, DIR_CACHE_TYPE cacheType)
void ClearDirectory (const std::string &strPath)
void ClearFile (const std::string &strFile)
void ClearSubPaths (const std::string &strPath)
void Clear ()
void AddFile (const std::string &strFile)
bool FileExists (const std::string &strPath, bool &bInCache)
Protected Member Functions
void InitCache (const std::set< std::string > &dirs)
void ClearCache (std::set< std::string > &dirs)
void CheckIfFull ()
Protected Attributes
std::map< std::string, CDir > m_cache
CCriticalSection m_cs
unsigned int m_accessCounter
Constructor & Destructor Documentation
CDirectoryCache()
CDirectoryCache::CDirectoryCache (void)
References m_accessCounter.
~CDirectoryCache()
CDirectoryCache::~CDirectoryCache (void) virtual default
Member Function Documentation
AddFile()
void CDirectoryCache::AddFile (const std::string & strFile)
References URIUtils::GetDirectory(), m_accessCounter, m_cache, m_cs, XFILE::CDirectoryCache::CDir::m_Items, URIUtils::RemoveSlashAtEnd(), and XFILE::CDirectoryCache::CDir::SetLastAccess().
Referenced by XFILE::CFile::OpenForWrite(), and XFILE::CFile::Rename().
CheckIfFull()
void CDirectoryCache::CheckIfFull () protected
References XFILE::DIR_CACHE_ALWAYS, m_cache, m_cs, and MAX_CACHED_DIRS.
Referenced by SetDirectory().
Clear()
void CDirectoryCache::Clear ()
References m_cache, and m_cs.
Referenced by CApplication::Cleanup(), and CProfileManager::LoadProfile().
ClearCache()
void CDirectoryCache::ClearCache (std::set< std::string > & dirs) protected
References m_cache.
ClearDirectory()
void CDirectoryCache::ClearDirectory (const std::string & strPath)
References CURL::GetWithoutOptions(), m_cache, m_cs, and URIUtils::RemoveSlashAtEnd().
Referenced by ClearFile(), XFILE::CDirectory::GetDirectory(), SetDirectory(), and KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions().
ClearFile()
void CDirectoryCache::ClearFile (const std::string & strFile)
References ClearDirectory(), URIUtils::GetDirectory(), CURL::GetWithoutOptions(), and URIUtils::RemoveSlashAtEnd().
Referenced by XFILE::CFile::Delete(), XFILE::CDirectory::Remove(), XFILE::CDirectory::RemoveRecursive(), and XFILE::CFile::Rename().
ClearSubPaths()
void CDirectoryCache::ClearSubPaths (const std::string & strPath)
References CURL::GetWithoutOptions(), m_cache, m_cs, and URIUtils::PathHasParent().
Referenced by CApplicationSkinHandling::LoadSkin().
FileExists()
bool CDirectoryCache::FileExists (const std::string & strPath, bool & bInCache)
References URIUtils::GetDirectory(), CURL::GetWithoutOptions(), m_accessCounter, m_cache, m_cs, XFILE::CDirectoryCache::CDir::m_Items, URIUtils::PathEquals(), URIUtils::RemoveSlashAtEnd(), and XFILE::CDirectoryCache::CDir::SetLastAccess().
Referenced by XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), and XFILE::CFile::Open().
GetDirectory()
bool CDirectoryCache::GetDirectory (const std::string & strPath, CFileItemList & items, bool retrieveAll = false)
References CFileItemList::Copy(), XFILE::DIR_CACHE_ALWAYS, XFILE::DIR_CACHE_ONCE, CURL::GetWithoutOptions(), m_accessCounter, m_cache, XFILE::CDirectoryCache::CDir::m_cacheType, m_cs, XFILE::CDirectoryCache::CDir::m_Items, URIUtils::RemoveSlashAtEnd(), XFILE::CDirectoryCache::CDir::SetLastAccess(), and CFileItemList::Size().
Referenced by XFILE::CDirectory::GetDirectory().
InitCache()
void CDirectoryCache::InitCache (const std::set< std::string > & dirs) protected
References CFileItemList::Clear(), XFILE::DIR_FLAG_NO_FILE_DIRS, and XFILE::CDirectory::GetDirectory().
SetDirectory()
void CDirectoryCache::SetDirectory (const std::string & strPath, const CFileItemList & items, DIR_CACHE_TYPE cacheType)
References CheckIfFull(), ClearDirectory(), XFILE::DIR_CACHE_NEVER, CURL::GetWithoutOptions(), m_accessCounter, m_cache, m_cs, XFILE::CDirectoryCache::CDir::m_Items, URIUtils::RemoveSlashAtEnd(), and XFILE::CDirectoryCache::CDir::SetLastAccess().
Referenced by XFILE::CDirectory::GetDirectory().
Member Data Documentation
m_accessCounter
unsigned int XFILE::CDirectoryCache::m_accessCounter protected
Referenced by AddFile(), CDirectoryCache(), FileExists(), GetDirectory(), and SetDirectory().
m_cache
std::map<std::string, CDir> XFILE::CDirectoryCache::m_cache protected
Referenced by AddFile(), CheckIfFull(), Clear(), ClearCache(), ClearDirectory(), ClearSubPaths(), FileExists(), GetDirectory(), and SetDirectory().
m_cs
CCriticalSection XFILE::CDirectoryCache::m_cs mutable protected
Referenced by AddFile(), CheckIfFull(), Clear(), ClearDirectory(), ClearSubPaths(), FileExists(), GetDirectory(), and SetDirectory().
The documentation for this class was generated from the following files:
DirectoryCache.h
DirectoryCache.cpp