Kodi Documentation: TestAddonBuilder.cpp File Reference
TestAddonBuilder.cpp File Reference
#include "addons/AddonBuilder.h"
#include "addons/LanguageResource.h"
#include "addons/addoninfo/AddonInfo.h"
#include "addons/addoninfo/AddonInfoBuilder.h"
#include "addons/addoninfo/AddonType.h"
#include <gtest/gtest.h>
Classes
class TestAddonBuilder
Functions
TEST_F (TestAddonBuilder, ShouldFailWhenEmpty)
TEST_F (TestAddonBuilder, ShouldBuildDependencyAddons)
TEST_F (TestAddonBuilder, ShouldReturnDerivedType)
Function Documentation
TEST_F() [1/3]
TEST_F (TestAddonBuilder , ShouldBuildDependencyAddons)
References EXPECT_EQ(), ADDON::CAddonBuilder::Generate(), ADDON::CAddonInfoBuilderFromDB::get(), ADDON::CAddonInfoBuilderFromDB::SetDependencies(), ADDON::CAddonInfoBuilderFromDB::SetExtensions(), and ADDON::CAddonInfoBuilderFromDB::SetId().
TEST_F() [2/3]
TEST_F (TestAddonBuilder , ShouldFailWhenEmpty)
References EXPECT_EQ(), and ADDON::CAddonBuilder::Generate().
TEST_F() [3/3]
TEST_F (TestAddonBuilder , ShouldReturnDerivedType)
References EXPECT_NE(), ADDON::CAddonBuilder::Generate(), ADDON::CAddonInfoBuilderFromDB::get(), ADDON::CAddonInfoBuilderFromDB::SetExtensions(), and ADDON::CAddonInfoBuilderFromDB::SetId().