Kodi Documentation: OVERLAY Namespace Reference
OVERLAY Namespace Reference
Classes
class COverlay
class COverlayGlyphGL
class COverlayGlyphGLES
class COverlayImageDX
class COverlayQuadsDX
class COverlayTextureGL
class COverlayTextureGLES
class CRenderer
struct SQuad
struct SQuads
struct SRenderState
Functions
static uint32_t build_rgba (int a, int r, int g, int b, bool mergealpha)
static uint32_t build_rgba (const int yuv[3], int alpha, bool mergealpha)
void convert_rgba (const CDVDOverlayImage &o, bool mergealpha, std::vector< uint32_t > &rgba)
void convert_rgba (const CDVDOverlaySpu &o, bool mergealpha, int &min_x, int &max_x, int &min_y, int &max_y, std::vector< uint32_t > &rgba)
bool convert_quad (ASS_Image *images, SQuads &quads, int max_x)
int GetStereoscopicDepth ()
Function Documentation
build_rgba() [1/2]
static uint32_t OVERLAY::build_rgba (const int yuv[3], int alpha, bool mergealpha) static
References build_rgba(), and clamp.
build_rgba() [2/2]
static uint32_t OVERLAY::build_rgba (int a, int r, int g, int b, bool mergealpha) static
References PIXEL_ASHIFT, PIXEL_BSHIFT, PIXEL_GSHIFT, and PIXEL_RSHIFT.
Referenced by build_rgba(), convert_rgba(), and convert_rgba().
convert_quad()
bool OVERLAY::convert_quad (ASS_Image * images, SQuads & quads, int max_x)
References OVERLAY::SQuad::a, OVERLAY::SQuad::b, color, data(), OVERLAY::SQuad::g, OVERLAY::SQuad::h, OVERLAY::SQuads::quad, OVERLAY::SQuad::r, OVERLAY::SQuads::size_x, OVERLAY::SQuads::size_y, OVERLAY::SQuads::texture, OVERLAY::SQuad::u, OVERLAY::SQuad::v, OVERLAY::SQuad::w, OVERLAY::SQuad::x, and OVERLAY::SQuad::y.
Referenced by OVERLAY::COverlayGlyphGL::COverlayGlyphGL(), OVERLAY::COverlayGlyphGLES::COverlayGlyphGLES(), and OVERLAY::COverlayQuadsDX::COverlayQuadsDX().
convert_rgba() [1/2]
void OVERLAY::convert_rgba (const CDVDOverlayImage & o, bool mergealpha, std::vector< uint32_t > & rgba)
References build_rgba(), CDVDOverlayImage::height, CDVDOverlayImage::linesize, CDVDOverlayImage::palette, PIXEL_ASHIFT, PIXEL_BSHIFT, PIXEL_GSHIFT, PIXEL_RSHIFT, CDVDOverlayImage::pixels, and CDVDOverlayImage::width.
Referenced by OVERLAY::COverlayImageDX::COverlayImageDX(), OVERLAY::COverlayImageDX::COverlayImageDX(), OVERLAY::COverlayTextureGL::COverlayTextureGL(), OVERLAY::COverlayTextureGL::COverlayTextureGL(), OVERLAY::COverlayTextureGLES::COverlayTextureGLES(), and OVERLAY::COverlayTextureGLES::COverlayTextureGLES().
convert_rgba() [2/2]
void OVERLAY::convert_rgba (const CDVDOverlaySpu & o, bool mergealpha, int & min_x, int & max_x, int & min_y, int & max_y, std::vector< uint32_t > & rgba)
References CDVDOverlaySpu::alpha, CDVDOverlay::bForced, build_rgba(), color, CDVDOverlaySpu::color, CDVDOverlaySpu::crop_i_x_end, CDVDOverlaySpu::crop_i_x_start, CDVDOverlaySpu::crop_i_y_end, CDVDOverlaySpu::crop_i_y_start, CDVDOverlaySpu::height, CDVDOverlaySpu::highlight_alpha, CDVDOverlaySpu::highlight_color, CDVDOverlaySpu::result, CDVDOverlaySpu::width, CDVDOverlaySpu::x, and CDVDOverlaySpu::y.
GetStereoscopicDepth()
int OVERLAY::GetStereoscopicDepth ()
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetSettingsComponent(), CGraphicContext::GetStereoView(), CServiceBroker::GetWinSystem(), RENDER_STEREO_MODE_MONO, RENDER_STEREO_MODE_OFF, RENDER_STEREO_VIEW_LEFT, and CSettings::SETTING_SUBTITLES_STEREOSCOPICDEPTH.
Referenced by OVERLAY::CRenderer::Render().