Kodi Documentation: CRunningScriptsHandler< TScript > Class Template Reference
CRunningScriptsHandler< TScript > Class Template Reference
#include <RunningScriptsHandler.h>
Protected Types
using HandleType = int
Protected Member Functions
CRunningScriptsHandler ()=default
virtual ~CRunningScriptsHandler ()=default
bool RunScript (TScript *script, const ADDON::AddonPtr &addon, const std::string &path, bool resume)
ADDON::AddonPtr GetAddon () const
void SetDone ()
bool StartScript (const ADDON::AddonPtr &addon, const std::string &path)
Protected Member Functions inherited from CScriptRunner
CScriptRunner ()
virtual ~CScriptRunner ()=default
virtual bool IsSuccessful () const =0
virtual bool IsCancelled () const =0
ADDON::AddonPtr GetAddon () const
bool StartScript (const ADDON::AddonPtr &addon, const std::string &path)
bool RunScript (const ADDON::AddonPtr &addon, const std::string &path, int handle, bool resume)
void SetDone ()
Static Protected Member Functions
static HandleType GetNewScriptHandle (TScript *script)
static void ReuseScriptHandle (HandleType handle, TScript *script)
static void RemoveScriptHandle (HandleType handle)
static TScript * GetScriptFromHandle (HandleType handle)
static CCriticalSection & GetScriptsLock ()
static int ExecuteScript (const ADDON::AddonPtr &addon, const std::string &path, bool resume)
static int ExecuteScript (const ADDON::AddonPtr &addon, const std::string &path, int handle, bool resume)
Static Protected Member Functions inherited from CScriptRunner
static int ExecuteScript (const ADDON::AddonPtr &addon, const std::string &path, bool resume)
static int ExecuteScript (const ADDON::AddonPtr &addon, const std::string &path, int handle, bool resume)
Static Private Attributes
static std::map< HandleType, TScript * > s_scriptHandles
static CCriticalSection s_critical
static HandleType s_scriptHandleCounter = 0
Member Typedef Documentation
HandleType
template<class TScript > using CRunningScriptsHandler< TScript >::HandleType = int protected
Constructor & Destructor Documentation
CRunningScriptsHandler()
template<class TScript > CRunningScriptsHandler< TScript >::CRunningScriptsHandler () protected default
~CRunningScriptsHandler()
template<class TScript > virtual CRunningScriptsHandler< TScript >::~CRunningScriptsHandler () protected virtual default
Member Function Documentation
ExecuteScript() [1/2]
template<class TScript > int CScriptRunner::ExecuteScript (const ADDON::AddonPtr & addon, const std::string & path, bool resume) static protected
ExecuteScript() [2/2]
template<class TScript > int CScriptRunner::ExecuteScript (const ADDON::AddonPtr & addon, const std::string & path, int handle, bool resume) static protected
GetAddon()
template<class TScript > ADDON::AddonPtr CScriptRunner::GetAddon () const protected
Referenced by XFILE::CPluginDirectory::GetSetting(), and XFILE::CPluginDirectory::SetSetting().
GetNewScriptHandle()
template<class TScript > static HandleType CRunningScriptsHandler< TScript >::GetNewScriptHandle (TScript * script) inline static protected
References CRunningScriptsHandler< TScript >::s_critical, CRunningScriptsHandler< TScript >::s_scriptHandleCounter, and CRunningScriptsHandler< TScript >::s_scriptHandles.
Referenced by CRunningScriptsHandler< TScript >::RunScript().
GetScriptFromHandle()
template<class TScript > static TScript * CRunningScriptsHandler< TScript >::GetScriptFromHandle (HandleType handle) inline static protected
References CRunningScriptsHandler< TScript >::s_critical, and CRunningScriptsHandler< TScript >::s_scriptHandles.
GetScriptsLock()
template<class TScript > static CCriticalSection & CRunningScriptsHandler< TScript >::GetScriptsLock () inline static protected
References CRunningScriptsHandler< TScript >::s_critical.
RemoveScriptHandle()
template<class TScript > static void CRunningScriptsHandler< TScript >::RemoveScriptHandle (HandleType handle) inline static protected
References CRunningScriptsHandler< TScript >::s_critical, and CRunningScriptsHandler< TScript >::s_scriptHandles.
Referenced by CRunningScriptsHandler< TScript >::RunScript().
ReuseScriptHandle()
template<class TScript > static void CRunningScriptsHandler< TScript >::ReuseScriptHandle (HandleType handle, TScript * script) inline static protected
References CRunningScriptsHandler< TScript >::s_critical, and CRunningScriptsHandler< TScript >::s_scriptHandles.
Referenced by CRunningScriptsHandler< TScript >::RunScript().
RunScript()
template<class TScript > bool CRunningScriptsHandler< TScript >::RunScript (TScript * script, const ADDON::AddonPtr & addon, const std::string & path, bool resume) inline protected
References CScriptInvocationManager::GetInstance(), CRunningScriptsHandler< TScript >::GetNewScriptHandle(), CScriptInvocationManager::GetReusablePluginHandle(), CRunningScriptsHandler< TScript >::RemoveScriptHandle(), CRunningScriptsHandler< TScript >::ReuseScriptHandle(), and CScriptRunner::RunScript().
SetDone()
template<class TScript > void CScriptRunner::SetDone () protected
Referenced by XFILE::CPluginDirectory::EndOfDirectory(), and XFILE::CPluginDirectory::SetResolvedUrl().
StartScript()
template<class TScript > bool CScriptRunner::StartScript (const ADDON::AddonPtr & addon, const std::string & path) protected
Member Data Documentation
s_critical
template<class TScript > CCriticalSection CRunningScriptsHandler< TScript >::s_critical static private
Referenced by CRunningScriptsHandler< TScript >::GetNewScriptHandle(), CRunningScriptsHandler< TScript >::GetScriptFromHandle(), CRunningScriptsHandler< TScript >::GetScriptsLock(), CRunningScriptsHandler< TScript >::RemoveScriptHandle(), and CRunningScriptsHandler< TScript >::ReuseScriptHandle().
s_scriptHandleCounter
template<class TScript > CRunningScriptsHandler< TScript >::HandleType CRunningScriptsHandler< TScript >::s_scriptHandleCounter = 0 static private
Referenced by CRunningScriptsHandler< TScript >::GetNewScriptHandle().
s_scriptHandles
template<class TScript > std::map< typename CRunningScriptsHandler< TScript >::HandleType, TScript * > CRunningScriptsHandler< TScript >::s_scriptHandles static private
Referenced by CRunningScriptsHandler< TScript >::GetNewScriptHandle(), CRunningScriptsHandler< TScript >::GetScriptFromHandle(), CRunningScriptsHandler< TScript >::RemoveScriptHandle(), and CRunningScriptsHandler< TScript >::ReuseScriptHandle().
The documentation for this class was generated from the following file:
RunningScriptsHandler.h