Kodi Documentation: CGUIControlFactory Class Reference
CGUIControlFactory Class Reference
Guilib classes » Window Reference » Controls
#include <GUIControlFactory.h>
Public Member Functions
CGUIControlFactory (void)
virtual ~CGUIControlFactory (void)
CGUIControl * Create (int parentID, const CRect &rect, TiXmlElement *pControlNode, bool insideContainer=false)
Static Public Member Functions
static CGUIControl::GUICONTROLTYPES TranslateControlType (const std::string &type)
translate from control name to control type
static std::string TranslateControlType (CGUIControl::GUICONTROLTYPES type)
translate from control type to control name
static bool GetAspectRatio (const TiXmlNode *pRootNode, const char *strTag, CAspectRatio &aspectRatio)
static bool GetInfoTexture (const TiXmlNode *pRootNode, const char *strTag, CTextureInfo &image, KODI::GUILIB::GUIINFO::CGUIInfoLabel &info, int parentID)
static bool GetTexture (const TiXmlNode *pRootNode, const char *strTag, CTextureInfo &image)
static bool GetAlignment (const TiXmlNode *pRootNode, const char *strTag, uint32_t &dwAlignment)
static bool GetAlignmentY (const TiXmlNode *pRootNode, const char *strTag, uint32_t &dwAlignment)
static bool GetAnimations (TiXmlNode *control, const CRect &rect, int context, std::vector< CAnimation > &animation)
static float ParsePosition (const char *pos, const float parentSize)
Create an info label from an XML element Processes XML elements of the form <xmltag fallback="fallback_value">info_value</xmltag> where info_value may use $INFO[], $LOCALIZE[], $NUMBER[] etc. If either the fallback_value or info_value are natural numbers they are interpreted as ids for lookup in strings.po. The fallback attribute is optional.
static bool GetInfoLabelFromElement (const TiXmlElement *element, KODI::GUILIB::GUIINFO::CGUIInfoLabel &infoLabel, int parentID)
static void GetInfoLabel (const TiXmlNode *pControlNode, const std::string &labelTag, KODI::GUILIB::GUIINFO::CGUIInfoLabel &infoLabel, int parentID)
static void GetInfoLabels (const TiXmlNode *pControlNode, const std::string &labelTag, std::vector< KODI::GUILIB::GUIINFO::CGUIInfoLabel > &infoLabels, int parentID)
static bool GetColor (const TiXmlNode *pRootNode, const char *strTag, KODI::UTILS::COLOR::Color &value)
static bool GetInfoColor (const TiXmlNode *pRootNode, const char *strTag, KODI::GUILIB::GUIINFO::CGUIInfoColor &value, int parentID)
static std::string FilterLabel (const std::string &label)
static bool GetConditionalVisibility (const TiXmlNode *control, std::string &condition)
static bool GetActions (const TiXmlNode *pRootNode, const char *strTag, CGUIAction &actions)
static void GetRectFromString (const std::string &string, CRect &rect)
static bool GetHitRect (const TiXmlNode *pRootNode, CRect &rect, const CRect &parentRect)
static bool GetScroller (const TiXmlNode *pControlNode, const std::string &scrollerTag, CScroller &scroller)
Static Protected Member Functions
static std::string GetType (const TiXmlElement *pControlNode)
static bool GetMovingSpeedConfig (const TiXmlNode *pRootNode, const char *strTag, KODI::UTILS::MOVING_SPEED::MapEventConfig &movingSpeedCfg)
static bool GetConditionalVisibility (const TiXmlNode *control, std::string &condition, std::string &allowHiddenFocus)
static bool GetString (const TiXmlNode *pRootNode, const char *strTag, std::string &strString)
static bool GetFloatRange (const TiXmlNode *pRootNode, const char *strTag, float &iMinValue, float &iMaxValue, float &iIntervalValue)
static bool GetIntRange (const TiXmlNode *pRootNode, const char *strTag, int &iMinValue, int &iMaxValue, int &iIntervalValue)
static bool GetPosition (const TiXmlNode *node, const char *tag, const float parentSize, float &value)
Get the value of a position tag from XML Handles both absolute and relative values.
static bool GetDimension (const TiXmlNode *node, const char *strTag, const float parentSize, float &value, float &min)
grab a dimension out of the XML
static bool GetDimensions (const TiXmlNode *node, const char *leftTag, const char *rightTag, const char *centerLeftTag, const char *centerRightTag, const char *widthTag, const float parentSize, float &left, float &width, float &min_width)
Retrieve the dimensions for a control.
Constructor & Destructor Documentation
CGUIControlFactory()
CGUIControlFactory::CGUIControlFactory (void) default
~CGUIControlFactory()
CGUIControlFactory::~CGUIControlFactory (void) virtual default
Member Function Documentation
Create()
CGUIControl * CGUIControlFactory::Create (int parentID, const CRect & rect, TiXmlElement * pControlNode, bool insideContainer = false)
Todo:
Perhaps we should check here whether id is valid for focusable controls such as buttons etc. For labels/fadelabels/images it does not matter
References ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NAV_BACK, ACTION_NEXT_CONTROL, ACTION_PREV_CONTROL, ACTION_SHOW_INFO, actions, CLabelInfo::align, CGUIControl::ALWAYS, CLabelInfo::angle, INFO::DEFAULT_CONTEXT, CLabelInfo::disabledColor, CGUIAction::EnableSendThreadMessageMode(), end(), CTextureInfo::filename, FilterLabel(), CGUIControl::FOCUS, CLabelInfo::focusedColor, CLabelInfo::font, g_fontManager, g_localizeStrings, CLocalizeStrings::Get(), GetActions(), GetAlignment(), GetAlignmentY(), GetAnimations(), GetAspectRatio(), XMLUtils::GetBoolean(), GetConditionalVisibility(), GetDimensions(), XMLUtils::GetFloat(), GetFloatRange(), CGUIFont::GetFont(), CServiceBroker::GetGUI(), GetHitRect(), GetInfoColor(), GetInfoLabel(), GetInfoLabels(), CGUIComponent::GetInfoManager(), GetInfoTexture(), CRssManager::GetInstance(), XMLUtils::GetInt(), GetIntRange(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), GetMovingSpeedConfig(), GetPosition(), GetRectFromString(), GetScroller(), GetString(), XMLUtils::GetString(), GetTexture(), GetType(), XMLUtils::GetUInt(), CRssManager::GetUrls(), CGUIControl::GUICONTAINER_EPGGRID, CGUIControl::GUICONTAINER_FIXEDLIST, CGUIControl::GUICONTAINER_LIST, CGUIControl::GUICONTAINER_PANEL, CGUIControl::GUICONTAINER_WRAPLIST, CGUIControl::GUICONTROL_BUTTON, CGUIControl::GUICONTROL_COLORBUTTON, CGUIControl::GUICONTROL_EDIT, CGUIControl::GUICONTROL_FADELABEL, CGUIControl::GUICONTROL_GAME, CGUIControl::GUICONTROL_GAMECONTROLLER, CGUIControl::GUICONTROL_GAMECONTROLLERLIST, CGUIControl::GUICONTROL_GROUP, CGUIControl::GUICONTROL_GROUPLIST, CGUIControl::GUICONTROL_IMAGE, CGUIControl::GUICONTROL_LABEL, CGUIControl::GUICONTROL_MOVER, CGUIControl::GUICONTROL_MULTI_IMAGE, CGUIControl::GUICONTROL_PROGRESS, CGUIControl::GUICONTROL_RADIO, CGUIControl::GUICONTROL_RANGES, CGUIControl::GUICONTROL_RENDERADDON, CGUIControl::GUICONTROL_RESIZE, CGUIControl::GUICONTROL_RSS, CGUIControl::GUICONTROL_SCROLLBAR, CGUIControl::GUICONTROL_SETTINGS_SLIDER, CGUIControl::GUICONTROL_SLIDER, CGUIControl::GUICONTROL_SPIN, CGUIControl::GUICONTROL_SPINEX, CGUIControl::GUICONTROL_TEXTBOX, CGUIControl::GUICONTROL_TOGGLEBUTTON, CGUIControl::GUICONTROL_VIDEO, CGUIControl::GUICONTROL_VISUALISATION, CRectGen< T >::Height(), HORIZONTAL, CGUIEditControl::INPUT_TYPE_PASSWORD, CLabelInfo::invalidColor, label, CGUIBaseContainer::LoadLayout(), PVR::CGUIEPGGridContainer::LoadLayout(), CGUIBaseContainer::LoadListProvider(), CGUIControl::NEVER, CLabelInfo::offsetX, CLabelInfo::offsetY, ParsePosition(), CLabelInfo::scrollSpeed, CLabelInfo::scrollSuffix, CLabelInfo::selectedColor, CGUIControl::SetActions(), CGUIToggleButtonControl::SetAltClickActions(), CGUIToggleButtonControl::SetAltLabel(), CGUIControl::SetAnimations(), CGUIImage::SetAspectRatio(), CGUIBaseContainer::SetAutoScrolling(), CGUIControl::SetCamera(), CGUIBaseContainer::SetClickActions(), CGUIButtonControl::SetClickActions(), CGUIControl::SetColorDiffuse(), CGUIColorButtonControl::SetColorDimensions(), KODI::GAME::CGUIGameController::SetControllerAddress(), KODI::GAME::CGUIGameController::SetControllerDiffuse(), KODI::GAME::CGUIGameController::SetControllerID(), CGUIImage::SetCrossFade(), CGUIControl::SetEnableCondition(), CGUISpinControl::SetFloatInterval(), CGUISpinControl::SetFloatRange(), CGUIBaseContainer::SetFocusActions(), CGUIButtonControl::SetFocusActions(), CGUIControl::SetHitRect(), CGUIColorButtonControl::SetImageBoxColor(), CGUIImage::SetInfo(), CGUIButtonControl::SetLabel(), CGUIToggleButtonControl::SetLabel(), CGUIButtonControl::SetLabel2(), CGUIButtonControl::SetMinWidth(), CGUIToggleButtonControl::SetMinWidth(), CGUIBaseContainer::SetPageControl(), PVR::CGUIEPGGridContainer::SetPageControl(), CGUITextBox::SetPageControl(), KODI::GAME::CGUIGameController::SetPeripheralLocation(), KODI::GAME::CGUIGameController::SetPortAddress(), CGUIControl::SetPulseOnSelect(), CGUIRadioButtonControl::SetRadioDimensions(), CGUISpinControl::SetRange(), CRectGen< T >::SetRect(), CGUIBaseContainer::SetRenderOffset(), PVR::CGUIEPGGridContainer::SetRenderOffset(), CGUISpinControl::SetReverse(), CGUISpinControl::SetShowOnePage(), CGUISpinControl::SetShowRange(), CGUISpinControlEx::SetSpinPosition(), CGUIControl::SetStereoFactor(), CGUISpinControlEx::SetText(), CGUIRadioButtonControl::SetToggleSelect(), CGUIToggleButtonControl::SetToggleSelect(), IGUIContainer::SetType(), CGUIBaseContainer::SetUnFocusActions(), CGUIButtonControl::SetUnFocusActions(), CGUIControl::SetVisibleCondition(), CLabelInfo::shadowColor, SLIDER_CONTROL_TYPE_PERCENTAGE, SPIN_CONTROL_TYPE_FLOAT, SPIN_CONTROL_TYPE_INT, SPIN_CONTROL_TYPE_PAGE, SPIN_CONTROL_TYPE_TEXT, CLabelInfo::textColor, TranslateControlType(), CGUIInfoManager::TranslateString(), VERTICAL, VIEW_TYPE_BIG_ICON, VIEW_TYPE_BIG_INFO, VIEW_TYPE_BIG_LIST, VIEW_TYPE_BIG_WIDE, VIEW_TYPE_BIG_WRAP, VIEW_TYPE_ICON, VIEW_TYPE_INFO, VIEW_TYPE_LIST, VIEW_TYPE_NONE, VIEW_TYPE_WIDE, VIEW_TYPE_WRAP, CLabelInfo::width, CRectGen< T >::Width(), CPointGen< T >::x, XBFONT_RIGHT, XBFONT_TRUNCATED, and CPointGen< T >::y.
Referenced by CGUIListItemLayout::LoadControl(), and CGUIWindow::LoadControl().
FilterLabel()
std::string CGUIControlFactory::FilterLabel (const std::string & label) static
References g_charsetConverter, g_localizeStrings, CLocalizeStrings::Get(), and label.
Referenced by Create(), and XFILE::CLibraryDirectory::GetDirectory().
GetActions()
bool CGUIControlFactory::GetActions (const TiXmlNode * pRootNode, const char * strTag, CGUIAction & actions) static
References actions, and XMLUtils::GetAttribute().
Referenced by CGUIStaticItem::CGUIStaticItem(), Create(), CGUIWindow::Load(), and TEST_P().
GetAlignment()
bool CGUIControlFactory::GetAlignment (const TiXmlNode * pRootNode, const char * strTag, uint32_t & dwAlignment) static
References XBFONT_CENTER_X, XBFONT_JUSTIFIED, XBFONT_LEFT, and XBFONT_RIGHT.
Referenced by Create(), and TEST_P().
GetAlignmentY()
bool CGUIControlFactory::GetAlignmentY (const TiXmlNode * pRootNode, const char * strTag, uint32_t & dwAlignment) static
References XBFONT_CENTER_Y.
Referenced by Create(), and TEST_P().
GetAnimations()
bool CGUIControlFactory::GetAnimations (TiXmlNode * control, const CRect & rect, int context, std::vector< CAnimation > & animation) static
References CAnimation::Create(), end(), and node.
Referenced by Create(), and XBMCAddon::xbmcgui::Control::setAnimations().
GetAspectRatio()
bool CGUIControlFactory::GetAspectRatio (const TiXmlNode * pRootNode, const char * strTag, CAspectRatio & aspectRatio) static
References CAspectRatio::align, CAspectRatio::AR_CENTER, CAspectRatio::AR_KEEP, CAspectRatio::AR_SCALE, CAspectRatio::AR_STRETCH, ASPECT_ALIGN_CENTER, ASPECT_ALIGN_LEFT, ASPECT_ALIGN_MASK, ASPECT_ALIGN_RIGHT, ASPECT_ALIGNY_BOTTOM, ASPECT_ALIGNY_CENTER, ASPECT_ALIGNY_MASK, ASPECT_ALIGNY_TOP, node, CAspectRatio::ratio, and CAspectRatio::scaleDiffuse.
Referenced by Create(), and TEST_P().
GetColor()
bool CGUIControlFactory::GetColor (const TiXmlNode * pRootNode, const char * strTag, KODI::UTILS::COLOR::Color & value) static
References CGUIColorManager::GetColor(), CGUIComponent::GetColorManager(), CServiceBroker::GetGUI(), node, and value.
Referenced by GUIFontManager::LoadFonts(), and TEST_P().
GetConditionalVisibility() [1/2]
bool CGUIControlFactory::GetConditionalVisibility (const TiXmlNode * control, std::string & condition) static
References GetConditionalVisibility().
Referenced by CGUIStaticItem::CGUIStaticItem(), Create(), GetConditionalVisibility(), CGFTestable::GetConditionalVisibility(), and CGUIWindow::Load().
GetConditionalVisibility() [2/2]
bool CGUIControlFactory::GetConditionalVisibility (const TiXmlNode * control, std::string & condition, std::string & allowHiddenFocus) static protected
References node.
GetDimension()
bool CGUIControlFactory::GetDimension (const TiXmlNode * node, const char * strTag, const float parentSize, float & value, float & min) static protected
grab a dimension out of the XML
Supports plain reading of a number (or constant) and, in addition allows "auto" as the value for the dimension, whereby value is set to the max attribute (if it exists) and min is set the min attribute (if it exists) or 1. Auto values are thus detected by min != 0.
Parameters
node the <control> XML node to read
strTag tag within node to read
parentSize the size of the parent for relative sizing.
value value to set, or maximum value if using auto
min minimum value - set != 0 if auto is used.
Returns
true if we found and read the tag.
See also
GetPosition, GetDimensions, ParsePosition.
References min, ParsePosition(), and value.
Referenced by CGFTestable::GetDimension(), and GetDimensions().
GetDimensions()
bool CGUIControlFactory::GetDimensions (const TiXmlNode * node, const char * leftTag, const char * rightTag, const char * centerLeftTag, const char * centerRightTag, const char * widthTag, const float parentSize, float & left, float & width, float & min_width) static protected
Retrieve the dimensions for a control.
Handles positioning based on at least 2 of left/right/center/width.
Parameters
node the <control> node describing the control.
leftTag the tag that holds the left field.
rightTag the tag that holds the right field.
centerLeftTag the tag that holds the center left field.
centerRightTag the tag that holds the center right field.
widthTag the tag holding the width.
parentSize the size of the parent, for relative sizing.
pos [out] the discovered position.
width [out] the discovered width.
min_width [out] the discovered minimum width.
Returns
true if we can successfully derive the position and size, false otherwise.
See also
GetDimension, GetPosition, ParsePosition.
References center, GetDimension(), GetPosition(), left, node, and right.
Referenced by Create(), and CGFTestable::GetDimensions().
GetFloatRange()
bool CGUIControlFactory::GetFloatRange (const TiXmlNode * pRootNode, const char * strTag, float & iMinValue, float & iMaxValue, float & iIntervalValue) static protected
Referenced by Create(), and CGFTestable::GetFloatRange().
GetHitRect()
bool CGUIControlFactory::GetHitRect (const TiXmlNode * pRootNode, CRect & rect, const CRect & parentRect) static
References CRectGen< T >::Height(), node, ParsePosition(), CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by Create(), CGUIWindow::Load(), and TEST_P().
GetInfoColor()
bool CGUIControlFactory::GetInfoColor (const TiXmlNode * pRootNode, const char * strTag, KODI::GUILIB::GUIINFO::CGUIInfoColor & value, int parentID) static
References node, and value.
Referenced by Create(), and CGUIWindow::Load().
GetInfoLabel()
void CGUIControlFactory::GetInfoLabel (const TiXmlNode * pControlNode, const std::string & labelTag, KODI::GUILIB::GUIINFO::CGUIInfoLabel & infoLabel, int parentID) static
References GetInfoLabels().
Referenced by CGUIStaticItem::CGUIStaticItem(), Create(), and GetInfoTexture().
GetInfoLabelFromElement()
bool CGUIControlFactory::GetInfoLabelFromElement (const TiXmlElement * element, KODI::GUILIB::GUIINFO::CGUIInfoLabel & infoLabel, int parentID) static
References g_charsetConverter, g_localizeStrings, CLocalizeStrings::Get(), XMLUtils::GetAttribute(), label, and KODI::GUILIB::GUIINFO::CGUIInfoLabel::SetLabel().
Referenced by CGUIStaticItem::CGUIStaticItem(), GetInfoLabels(), and TEST_P().
GetInfoLabels()
void CGUIControlFactory::GetInfoLabels (const TiXmlNode * pControlNode, const std::string & labelTag, std::vector< KODI::GUILIB::GUIINFO::CGUIInfoLabel > & infoLabels, int parentID) static
References GetInfoLabelFromElement(), XMLUtils::GetInt(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), and label.
Referenced by Create(), GetInfoLabel(), and TEST_P().
GetInfoTexture()
bool CGUIControlFactory::GetInfoTexture (const TiXmlNode * pRootNode, const char * strTag, CTextureInfo & image, KODI::GUILIB::GUIINFO::CGUIInfoLabel & info, int parentID) static
References CTextureInfo::filename, GetInfoLabel(), and GetTexture().
Referenced by Create().
GetIntRange()
bool CGUIControlFactory::GetIntRange (const TiXmlNode * pRootNode, const char * strTag, int & iMinValue, int & iMaxValue, int & iIntervalValue) static protected
Referenced by Create(), and CGFTestable::GetIntRange().
GetMovingSpeedConfig()
bool CGUIControlFactory::GetMovingSpeedConfig (const TiXmlNode * pRootNode, const char * strTag, KODI::UTILS::MOVING_SPEED::MapEventConfig & movingSpeedCfg) static protected
References XMLUtils::GetAttribute(), LOGERROR, and KODI::UTILS::MOVING_SPEED::ParseEventType().
Referenced by Create(), and CGFTestable::GetMovingSpeedConfig().
GetPosition()
bool CGUIControlFactory::GetPosition (const TiXmlNode * node, const char * tag, const float parentSize, float & value) static protected
Get the value of a position tag from XML Handles both absolute and relative values.
Parameters
node the <control> XML node.
tag the XML node to parse.
parentSize the size of the parent, for relative positioning.
value [out] the returned value.
See also
ParsePosition, GetDimension, GetDimensions.
References node, ParsePosition(), and value.
Referenced by Create(), GetDimensions(), and CGFTestable::GetPosition().
GetRectFromString()
void CGUIControlFactory::GetRectFromString (const std::string & string, CRect & rect) static
References CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by Create(), and GetTexture().
GetScroller()
bool CGUIControlFactory::GetScroller (const TiXmlNode * pControlNode, const std::string & scrollerTag, CScroller & scroller) static
References CAnimEffect::GetTweener(), XMLUtils::GetUInt(), and node.
Referenced by Create(), and TEST_P().
GetString()
bool CGUIControlFactory::GetString (const TiXmlNode * pRootNode, const char * strTag, std::string & strString) static protected
References g_localizeStrings, CLocalizeStrings::Get(), XMLUtils::GetString(), and text.
Referenced by Create(), and CGFTestable::GetString().
GetTexture()
bool CGUIControlFactory::GetTexture (const TiXmlNode * pRootNode, const char * strTag, CTextureInfo & image) static
References CTextureInfo::border, CTextureInfo::diffuse, CTextureInfo::diffuseColor, CTextureInfo::filename, XMLUtils::GetAttribute(), GetRectFromString(), CTextureInfo::m_infill, CTextureInfo::orientation, KODI::GUILIB::GUIINFO::CGUIInfoColor::Parse(), and CTextureInfo::useLarge.
Referenced by Create(), GetInfoTexture(), and TEST_P().
GetType()
std::string CGUIControlFactory::GetType (const TiXmlElement * pControlNode) static protected
References XMLUtils::GetAttribute(), and XMLUtils::GetString().
Referenced by Create(), and CGFTestable::GetType().
ParsePosition()
float CGUIControlFactory::ParsePosition (const char * pos, const float parentSize) static
Create an info label from an XML element Processes XML elements of the form <xmltag fallback="fallback_value">info_value</xmltag> where info_value may use $INFO[], $LOCALIZE[], $NUMBER[] etc. If either the fallback_value or info_value are natural numbers they are interpreted as ids for lookup in strings.po. The fallback attribute is optional.
Parameters
element XML element to process
infoLabel Returned infoLabel
parentID The parent id
Returns
true if a valid info label was read, false otherwise
Parse a position string Handles strings of the form
number of pixels
r number of pixels measured from the right
% percentage of parent size
Parameters
pos the string to parse.
parentSize the size of the parent.
See also
GetPosition
References end(), and value.
Referenced by Create(), CZoomEffect::CZoomEffect(), GetDimension(), GetHitRect(), GetPosition(), and CGUIWindow::Load().
TranslateControlType() [1/2]
std::string CGUIControlFactory::TranslateControlType (CGUIControl::GUICONTROLTYPES type) static
translate from control type to control name
Parameters
type type of the control
Returns
name of control
References controls.
TranslateControlType() [2/2]
CGUIControl::GUICONTROLTYPES CGUIControlFactory::TranslateControlType (const std::string & type) static
translate from control name to control type
Parameters
type name of the control
Returns
type of control
References controls, CGUIControl::GUICONTROL_UNKNOWN, and ControlMapping::type.
Referenced by Create(), and CGUIWindowDebugInfo::Process().
The documentation for this class was generated from the following files:
GUIControlFactory.h
GUIControlFactory.cpp