Kodi Documentation: PVR::CPVRSettings Class Reference
PVR::CPVRSettings Class Reference
#include <PVRSettings.h>
Public Member Functions
CPVRSettings (const std::set< std::string > &settingNames)
~CPVRSettings () override
void RegisterCallback (ISettingCallback *callback)
void UnregisterCallback (ISettingCallback *callback)
void OnSettingsLoaded () override
Settings have been loaded.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
bool GetBoolValue (const std::string &settingName) const
int GetIntValue (const std::string &settingName) const
std::string GetStringValue (const std::string &settingName) const
Static Public Member Functions
static void MarginTimeFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static bool IsSettingVisible (const std::string &condition, const std::string &value, const std::shared_ptr< const CSetting > &setting, void *data)
static bool CheckParentalPin (const std::string &condition, const std::string &value, const std::shared_ptr< const CSetting > &setting, void *data)
Private Member Functions
CPVRSettings (const CPVRSettings &)=delete
CPVRSettings & operator= (CPVRSettings const &)=delete
void Init (const std::set< std::string > &settingNames)
Private Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsUnloaded ()
Setting values have been unloaded.
virtual void OnSettingsCleared ()
Settings have been cleared.
Private Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Private Attributes
CCriticalSection m_critSection
std::map< std::string, std::shared_ptr< CSetting > > m_settings
std::set< ISettingCallback * > m_callbacks
Static Private Attributes
static unsigned int m_iInstances = 0
Constructor & Destructor Documentation
CPVRSettings() [1/2]
CPVRSettings::CPVRSettings (const std::set< std::string > & settingNames) explicit
References CheckParentalPin(), CServiceBroker::GetSettingsComponent(), Init(), IsSettingVisible(), m_iInstances, and MarginTimeFiller().
~CPVRSettings()
CPVRSettings::~CPVRSettings () override
References CServiceBroker::GetSettingsComponent(), and m_iInstances.
CPVRSettings() [2/2]
PVR::CPVRSettings::CPVRSettings (const CPVRSettings &) private delete
Member Function Documentation
CheckParentalPin()
bool CPVRSettings::CheckParentalPin (const std::string & condition, const std::string & value, const std::shared_ptr< const CSetting > & setting, void * data) static
References PVR::CPVRManager::Get(), CServiceBroker::GetPVRManager(), and PVR::SUCCESS.
Referenced by CPVRSettings().
GetBoolValue()
bool CPVRSettings::GetBoolValue (const std::string & settingName) const
References Boolean, LOGERROR, m_critSection, and m_settings.
Referenced by PVR::CPVRGUIActionsParentalControl::CheckParentalPIN(), PVR::CPVRTimers::GetNextEventTime(), PVR::CPVRGUIActionsChannels::GetSelectedChannelPath(), PVR::CPVREpgContainer::InterruptUpdate(), PVR::CPVRManager::IsCurrentlyParentalLocked(), PVR::CPVRManager::SetWakeupCommand(), PVR::CPVRChannelGroups::SortGroups(), PVR::CGUIWindowPVRRecordingsBase::UpdateButtons(), PVR::CPVRTimers::UpdateEntries(), PVR::CPVRChannelGroupSettings::UpdateStartGroupChannelNumbersFromOne(), PVR::CPVRChannelGroupSettings::UpdateUseBackendChannelNumbers(), and PVR::CPVRChannelGroupSettings::UpdateUseBackendChannelOrder().
GetIntValue()
int CPVRSettings::GetIntValue (const std::string & settingName) const
References Integer, LOGERROR, m_critSection, and m_settings.
Referenced by PVR::CPVRGUIActionsTimers::AddTimer(), PVR::CPVREpgContainer::GetFutureDaysToDisplay(), PVR::CPVRTimers::GetNextEventTime(), PVR::CPVREpgContainer::GetPastDaysToDisplay(), PVR::CPVRManager::IsCurrentlyParentalLocked(), PVR::CPVRGUIActionsPowerManagement::IsNextEventWithinBackendIdleTime(), PVR::CPVRGUIActionsPlayback::PlayChannelOnStartup(), PVR::CPVRGUIActionsRecordings::ProcessDeleteAfterWatch(), PVR::CPVRGUIActionsPlayback::SwitchToChannel(), and PVR::CPVREpgContainer::UpdateEPG().
GetStringValue()
std::string CPVRSettings::GetStringValue (const std::string & settingName) const
References LOGERROR, m_critSection, m_settings, and String.
Referenced by PVR::CPVRGUIActionsPowerManagement::CanSystemPowerdown(), PVR::CPVRGUIActionsParentalControl::CheckParentalPIN(), PVR::CPVRTimers::GetNextEventTime(), and PVR::CPVRManager::SetWakeupCommand().
Init()
void CPVRSettings::Init (const std::set< std::string > & settingNames) private
References CServiceBroker::GetSettingsComponent(), LOGERROR, m_critSection, and m_settings.
Referenced by CPVRSettings(), and OnSettingsLoaded().
IsSettingVisible()
bool CPVRSettings::IsSettingVisible (const std::string & condition, const std::string & value, const std::shared_ptr< const CSetting > & setting, void * data) static
References PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), CSettings::SETTING_PVRMANAGER_CLIENTPRIORITIES, CSettings::SETTING_PVRMANAGER_USEBACKENDCHANNELNUMBERS, and CSettings::SETTING_PVRMANAGER_USEBACKENDCHANNELNUMBERSALWAYS.
Referenced by CPVRSettings().
MarginTimeFiller()
void CPVRSettings::MarginTimeFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CPVRSettings(), and PVR::CGUIDialogPVRTimerSettings::MarginTimeFiller().
OnSettingChanged()
void CPVRSettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References m_callbacks, m_critSection, and m_settings.
OnSettingsLoaded()
void CPVRSettings::OnSettingsLoaded () override virtual
Settings have been loaded.
This callback can be used to trigger loading other settings.
Reimplemented from ISettingsHandler.
References Init(), m_critSection, and m_settings.
operator=()
CPVRSettings & PVR::CPVRSettings::operator= (CPVRSettings const &) private delete
RegisterCallback()
void CPVRSettings::RegisterCallback (ISettingCallback * callback)
References m_callbacks, and m_critSection.
UnregisterCallback()
void CPVRSettings::UnregisterCallback (ISettingCallback * callback)
References m_callbacks, and m_critSection.
Referenced by PVR::CPVRChannelGroups::~CPVRChannelGroups(), and PVR::CPVRChannelGroupSettings::~CPVRChannelGroupSettings().
Member Data Documentation
m_callbacks
std::set<ISettingCallback*> PVR::CPVRSettings::m_callbacks private
Referenced by OnSettingChanged(), RegisterCallback(), and UnregisterCallback().
m_critSection
CCriticalSection PVR::CPVRSettings::m_critSection mutable private
Referenced by GetBoolValue(), GetIntValue(), GetStringValue(), Init(), OnSettingChanged(), OnSettingsLoaded(), RegisterCallback(), and UnregisterCallback().
m_iInstances
unsigned int CPVRSettings::m_iInstances = 0 static private
Referenced by CPVRSettings(), and ~CPVRSettings().
m_settings
std::map<std::string, std::shared_ptr<CSetting> > PVR::CPVRSettings::m_settings private
Referenced by GetBoolValue(), GetIntValue(), GetStringValue(), Init(), OnSettingChanged(), and OnSettingsLoaded().
The documentation for this class was generated from the following files:
PVRSettings.h
PVRSettings.cpp