Kodi Documentation: KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard Class Reference
KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard Class Reference final
#include <InputProcessorKeyboard.h>
Public Member Functions
CInputProcessorKeyboard (IInputHandlerKeyboard &handler)
void OnKeyboardKeymap (CSeat *seat, wayland::keyboard_keymap_format format, std::string const &keymap) override
void OnKeyboardEnter (CSeat *seat, std::uint32_t serial, const wayland::surface_t &surface, const wayland::array_t &keys) override
void OnKeyboardLeave (CSeat *seat, std::uint32_t serial, const wayland::surface_t &surface) override
void OnKeyboardKey (CSeat *seat, std::uint32_t serial, std::uint32_t time, std::uint32_t key, wayland::keyboard_key_state state) override
void OnKeyboardModifiers (CSeat *seat, std::uint32_t serial, std::uint32_t modsDepressed, std::uint32_t modsLatched, std::uint32_t modsLocked, std::uint32_t group) override
void OnKeyboardRepeatInfo (CSeat *seat, std::int32_t rate, std::int32_t delay) override
Private Member Functions
CInputProcessorKeyboard (CInputProcessorKeyboard const &other)=delete
CInputProcessorKeyboard & operator= (CInputProcessorKeyboard const &other)=delete
void ConvertAndSendKey (std::uint32_t scancode, bool pressed)
XBMC_Event SendKey (unsigned char scancode, XBMCKey key, std::uint16_t unicodeCodepoint, bool pressed)
void NotifyKeyComposingEvent (uint8_t eventType, std::uint16_t unicodeCodepoint)
void KeyRepeatTimeout ()
Private Attributes
IInputHandlerKeyboard & m_handler
std::unique_ptr< CXkbcommonContext > m_xkbContext
std::unique_ptr< CXkbcommonKeymap > m_keymap
std::atomic< int > m_keyRepeatDelay {1000}
std::atomic< int > m_keyRepeatInterval {50}
XBMC_Event m_keyToRepeat
CTimer m_keyRepeatTimer
Additional Inherited Members
Protected Member Functions inherited from KODI::WINDOWING::WAYLAND::IRawInputHandlerKeyboard
~IRawInputHandlerKeyboard ()=default
Constructor & Destructor Documentation
CInputProcessorKeyboard() [1/2]
CInputProcessorKeyboard::CInputProcessorKeyboard (IInputHandlerKeyboard & handler)
CInputProcessorKeyboard() [2/2]
KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::CInputProcessorKeyboard (CInputProcessorKeyboard const & other) private delete
Member Function Documentation
ConvertAndSendKey()
void CInputProcessorKeyboard::ConvertAndSendKey (std::uint32_t scancode, bool pressed) private
References KODI::WINDOWING::WAYLAND::CANCELLED, KODI::WINDOWING::WAYLAND::COMPOSING, KODI::WINDOWING::WAYLAND::FINISHED, KODI::WINDOWING::WAYLAND::KeyComposerStatus::keysym, CLog::Log(), LOGDEBUG, m_keymap, m_keyRepeatDelay, m_keyRepeatInterval, m_keyRepeatTimer, m_keyToRepeat, NotifyKeyComposingEvent(), SendKey(), CTimer::Start(), KODI::WINDOWING::WAYLAND::KeyComposerStatus::state, CTimer::Stop(), XBMC_KEYCOMPOSING_CANCELLED, XBMC_KEYCOMPOSING_COMPOSING, XBMC_KEYCOMPOSING_FINISHED, XBMCK_BACKSPACE, and XBMCK_UNKNOWN.
Referenced by OnKeyboardKey().
KeyRepeatTimeout()
void CInputProcessorKeyboard::KeyRepeatTimeout () private
References m_handler, m_keyRepeatInterval, m_keyRepeatTimer, m_keyToRepeat, KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard::OnKeyboardEvent(), CTimer::RestartAsync(), XBMC_Event::type, XBMC_KEYDOWN, and XBMC_KEYUP.
NotifyKeyComposingEvent()
void CInputProcessorKeyboard::NotifyKeyComposingEvent (uint8_t eventType, std::uint16_t unicodeCodepoint) private
Notify the outside world about key composing events
Parameters
eventType - the key composition event type
unicodeCodepoint - unicode codepoint of the pressed dead key
References m_handler, KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard::OnKeyboardEvent(), and XBMC_Event::type.
Referenced by ConvertAndSendKey().
OnKeyboardEnter()
void CInputProcessorKeyboard::OnKeyboardEnter (CSeat * seat, std::uint32_t serial, const wayland::surface_t & surface, const wayland::array_t & keys) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerKeyboard.
References m_handler, and KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard::OnKeyboardEnter().
OnKeyboardKey()
void CInputProcessorKeyboard::OnKeyboardKey (CSeat * seat, std::uint32_t serial, std::uint32_t time, std::uint32_t key, wayland::keyboard_key_state state) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerKeyboard.
References ConvertAndSendKey(), CLog::Log(), LOGWARNING, and m_keymap.
OnKeyboardKeymap()
void CInputProcessorKeyboard::OnKeyboardKeymap (CSeat * seat, wayland::keyboard_keymap_format format, std::string const & keymap) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerKeyboard.
References g_langInfo, CLog::Log(), LOGERROR, LOGWARNING, m_keymap, m_keyRepeatTimer, m_xkbContext, and CTimer::Stop().
OnKeyboardLeave()
void CInputProcessorKeyboard::OnKeyboardLeave (CSeat * seat, std::uint32_t serial, const wayland::surface_t & surface) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerKeyboard.
References m_handler, m_keyRepeatTimer, KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard::OnKeyboardLeave(), and CTimer::Stop().
OnKeyboardModifiers()
void CInputProcessorKeyboard::OnKeyboardModifiers (CSeat * seat, std::uint32_t serial, std::uint32_t modsDepressed, std::uint32_t modsLatched, std::uint32_t modsLocked, std::uint32_t group) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerKeyboard.
References CLog::Log(), LOGWARNING, m_keymap, m_keyRepeatTimer, and CTimer::Stop().
OnKeyboardRepeatInfo()
void CInputProcessorKeyboard::OnKeyboardRepeatInfo (CSeat * seat, std::int32_t rate, std::int32_t delay) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerKeyboard.
References CLog::Log(), LOGDEBUG, m_keyRepeatDelay, and m_keyRepeatInterval.
operator=()
CInputProcessorKeyboard & KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::operator= (CInputProcessorKeyboard const & other) private delete
SendKey()
XBMC_Event CInputProcessorKeyboard::SendKey (unsigned char scancode, XBMCKey key, std::uint16_t unicodeCodepoint, bool pressed) private
References m_handler, m_keymap, KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard::OnKeyboardEvent(), XBMC_Event::type, XBMC_KEYDOWN, and XBMC_KEYUP.
Referenced by ConvertAndSendKey().
Member Data Documentation
m_handler
IInputHandlerKeyboard& KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::m_handler private
Referenced by KeyRepeatTimeout(), NotifyKeyComposingEvent(), OnKeyboardEnter(), OnKeyboardLeave(), and SendKey().
m_keymap
std::unique_ptr<CXkbcommonKeymap> KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::m_keymap private
Referenced by ConvertAndSendKey(), OnKeyboardKey(), OnKeyboardKeymap(), OnKeyboardModifiers(), and SendKey().
m_keyRepeatDelay
std::atomic<int> KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::m_keyRepeatDelay {1000} private
Referenced by ConvertAndSendKey(), and OnKeyboardRepeatInfo().
m_keyRepeatInterval
std::atomic<int> KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::m_keyRepeatInterval {50} private
Referenced by ConvertAndSendKey(), KeyRepeatTimeout(), and OnKeyboardRepeatInfo().
m_keyRepeatTimer
CTimer KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::m_keyRepeatTimer private
Referenced by ConvertAndSendKey(), KeyRepeatTimeout(), OnKeyboardKeymap(), OnKeyboardLeave(), and OnKeyboardModifiers().
m_keyToRepeat
XBMC_Event KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::m_keyToRepeat private
Referenced by ConvertAndSendKey(), and KeyRepeatTimeout().
m_xkbContext
std::unique_ptr<CXkbcommonContext> KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::m_xkbContext private
Referenced by OnKeyboardKeymap().
The documentation for this class was generated from the following files:
InputProcessorKeyboard.h
InputProcessorKeyboard.cpp