Kodi Documentation: CLibInputPointer Class Reference
CLibInputPointer Class Reference
#include <LibInputPointer.h>
Public Member Functions
CLibInputPointer ()=default
~CLibInputPointer ()=default
void ProcessButton (libinput_event_pointer *e)
void ProcessMotion (libinput_event_pointer *e)
void ProcessMotionAbsolute (libinput_event_pointer *e)
void ProcessAxis (libinput_event_pointer *e)
Private Attributes
struct pos m_pos = { 0, 0 }
Constructor & Destructor Documentation
CLibInputPointer()
CLibInputPointer::CLibInputPointer () default
~CLibInputPointer()
CLibInputPointer::~CLibInputPointer () default
Member Function Documentation
ProcessAxis()
void CLibInputPointer::ProcessAxis (libinput_event_pointer * e)
References CServiceBroker::GetAppPort(), CLog::Log(), LOGDEBUG, m_pos, XBMC_Event::type, pos::X, XBMC_BUTTON_WHEELDOWN, XBMC_BUTTON_WHEELUP, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, and pos::Y.
ProcessButton()
void CLibInputPointer::ProcessButton (libinput_event_pointer * e)
References CServiceBroker::GetAppPort(), CLog::Log(), LOGDEBUG, m_pos, XBMC_Event::type, pos::X, XBMC_BUTTON_LEFT, XBMC_BUTTON_MIDDLE, XBMC_BUTTON_RIGHT, XBMC_BUTTON_X1, XBMC_BUTTON_X2, XBMC_BUTTON_X3, XBMC_BUTTON_X4, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, and pos::Y.
ProcessMotion()
void CLibInputPointer::ProcessMotion (libinput_event_pointer * e)
References CServiceBroker::GetAppPort(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, m_pos, XBMC_Event::type, pos::X, XBMC_MOUSEMOTION, and pos::Y.
ProcessMotionAbsolute()
void CLibInputPointer::ProcessMotionAbsolute (libinput_event_pointer * e)
References CServiceBroker::GetAppPort(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, m_pos, XBMC_Event::type, pos::X, XBMC_MOUSEMOTION, and pos::Y.
Member Data Documentation
m_pos
struct pos CLibInputPointer::m_pos = { 0, 0 } private
Referenced by ProcessAxis(), ProcessButton(), ProcessMotion(), and ProcessMotionAbsolute().
The documentation for this class was generated from the following files:
LibInputPointer.h
LibInputPointer.cpp