Kodi Documentation: anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector Class Reference
anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector Class Reference
Public Member Functions
CPVRGUIDatabaseResetComponentsSelector ()=default
virtual ~CPVRGUIDatabaseResetComponentsSelector ()=default
bool Select ()
bool IsResetChannelsSelected () const
bool IsResetGroupsSelected () const
bool IsResetGuideSelected () const
bool IsResetProvidersSelected () const
bool IsResetRemindersSelected () const
bool IsResetRecordingsSelected () const
bool IsResetClientsSelected () const
Private Attributes
bool m_bResetChannels = false
bool m_bResetGroups = false
bool m_bResetGuide = false
bool m_bResetProviders = false
bool m_bResetReminders = false
bool m_bResetRecordings = false
bool m_bResetClients = false
Constructor & Destructor Documentation
CPVRGUIDatabaseResetComponentsSelector()
anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::CPVRGUIDatabaseResetComponentsSelector () default
~CPVRGUIDatabaseResetComponentsSelector()
virtual anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::~CPVRGUIDatabaseResetComponentsSelector () virtual default
Member Function Documentation
IsResetChannelsSelected()
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::IsResetChannelsSelected () const inline
IsResetClientsSelected()
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::IsResetClientsSelected () const inline
IsResetGroupsSelected()
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::IsResetGroupsSelected () const inline
IsResetGuideSelected()
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::IsResetGuideSelected () const inline
IsResetProvidersSelected()
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::IsResetProvidersSelected () const inline
IsResetRecordingsSelected()
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::IsResetRecordingsSelected () const inline
IsResetRemindersSelected()
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::IsResetRemindersSelected () const inline
Select()
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::Select () inline
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedItems(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), LOGERROR, CGUIDialog::Open(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CGUIDialogSelect::SetMultiSelection(), and WINDOW_DIALOG_SELECT.
Member Data Documentation
m_bResetChannels
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::m_bResetChannels = false private
m_bResetClients
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::m_bResetClients = false private
m_bResetGroups
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::m_bResetGroups = false private
m_bResetGuide
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::m_bResetGuide = false private
m_bResetProviders
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::m_bResetProviders = false private
m_bResetRecordings
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::m_bResetRecordings = false private
m_bResetReminders
bool anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector::m_bResetReminders = false private
The documentation for this class was generated from the following file:
PVRGUIActionsDatabase.cpp