Kodi Documentation: CSettingUtils Class Reference
CSettingUtils Class Reference
#include <SettingUtils.h>
Static Public Member Functions
static std::vector< CVariant > GetList (const std::shared_ptr< const CSettingList > &settingList)
Gets the values of the given list setting.
static bool SetList (const std::shared_ptr< CSettingList > &settingList, const std::vector< CVariant > &value)
Sets the values of the given list setting.
static std::vector< CVariant > ListToValues (const std::shared_ptr< const CSettingList > &setting, const std::vector< std::shared_ptr< CSetting > > &values)
static bool ValuesToList (const std::shared_ptr< const CSettingList > &setting, const std::vector< CVariant > &values, std::vector< std::shared_ptr< CSetting > > &newValues)
static bool FindIntInList (const std::shared_ptr< const CSettingList > &settingList, int value)
Search in a list of Ints for a given value.
Member Function Documentation
FindIntInList()
bool CSettingUtils::FindIntInList (const std::shared_ptr< const CSettingList > & settingList, int value) static
Search in a list of Ints for a given value.
Parameters
settingList CSettingList instance
value value to search for
Returns
True if value was found in list, false otherwise
References Integer, value, and values.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CFileItem::GetThumbHideIfUnwatched(), KODI::VIDEO::UTILS::IsAutoPlayNextItem(), CDVDVideoCodecAndroidMediaCodec::Open(), CDVDVideoCodecStarfish::OpenInternal(), and CGUIDialogVideoInfo::Update().
GetList()
std::vector< CVariant > CSettingUtils::GetList (const std::shared_ptr< const CSettingList > & settingList) static
Gets the values of the given list setting.
Parameters
settingList List setting
Returns
List of values of the given list setting
References ListToValues().
Referenced by CGUIDialogLibExportSettings::GetExportItemsFromSetting(), GetIntegerOptions(), CSettingsBase::GetList(), GetStringOptions(), PVR::CGUIDialogPVRTimerSettings::GetWeekdaysFromSetting(), CGUIControlListSetting::OnClick(), CGUIDialogMediaFilter::OnSettingChanged(), CLog::OnSettingChanged(), and JSONRPC::CSettingsOperations::SerializeSettingList().
ListToValues()
std::vector< CVariant > CSettingUtils::ListToValues (const std::shared_ptr< const CSettingList > & setting, const std::vector< std::shared_ptr< CSetting > > & values) static
References Boolean, Integer, Number, String, value, and values.
Referenced by GetList(), and JSONRPC::CSettingsOperations::SerializeSettingList().
SetList()
bool CSettingUtils::SetList (const std::shared_ptr< CSettingList > & settingList, const std::vector< CVariant > & value) static
Sets the values of the given list setting.
Parameters
settingList List setting
value Values to set
Returns
True if setting the values was successful, false otherwise
References value, and ValuesToList().
Referenced by CGUIControlListSetting::OnClick(), CGUIControlRangeSetting::OnClick(), and CSettingsBase::SetList().
ValuesToList()
bool CSettingUtils::ValuesToList (const std::shared_ptr< const CSettingList > & setting, const std::vector< CVariant > & values, std::vector< std::shared_ptr< CSetting > > & newValues) static
References Boolean, index(), Integer, Number, String, value, and values.
Referenced by CGUIDialogSettingsManualBase::AddList(), CGUIDialogSettingsManualBase::AddList(), CGUIDialogSettingsManualBase::AddList(), CGUIDialogSettingsManualBase::AddList(), CGUIDialogSettingsManualBase::AddRange(), CGUIDialogSettingsManualBase::AddRange(), and SetList().
The documentation for this class was generated from the following files:
SettingUtils.h
SettingUtils.cpp