Kodi Documentation: AddonToKodiFuncTable_Game Struct Reference
AddonToKodiFuncTable_Game Struct Reference
Game callbacks.
#include <game.h>
Public Attributes
KODI_HANDLE kodiInstance
void(* CloseGame)(KODI_HANDLE kodiInstance)
KODI_GAME_STREAM_HANDLE(* OpenStream)(KODI_HANDLE, const struct game_stream_properties *)
bool(* GetStreamBuffer)(KODI_HANDLE, KODI_GAME_STREAM_HANDLE, unsigned int, unsigned int, struct game_stream_buffer *)
void(* AddStreamData)(KODI_HANDLE, KODI_GAME_STREAM_HANDLE, const struct game_stream_packet *)
void(* ReleaseStreamBuffer)(KODI_HANDLE, KODI_GAME_STREAM_HANDLE, struct game_stream_buffer *)
void(* CloseStream)(KODI_HANDLE, KODI_GAME_STREAM_HANDLE)
game_proc_address_t(* HwGetProcAddress)(KODI_HANDLE kodiInstance, const char *symbol)
bool(* InputEvent)(KODI_HANDLE kodiInstance, const struct game_input_event *event)
Detailed Description
Game callbacks.
Not to be used outside this header.
Member Data Documentation
AddStreamData
void(* AddonToKodiFuncTable_Game::AddStreamData) (KODI_HANDLE, KODI_GAME_STREAM_HANDLE, const struct game_stream_packet *)
Referenced by kodi::addon::CInstanceGame::CStream::AddData(), and KODI::GAME::CGameClient::Initialize().
CloseGame
void(* AddonToKodiFuncTable_Game::CloseGame) (KODI_HANDLE kodiInstance)
Referenced by KODI::GAME::CGameClient::Initialize().
CloseStream
void(* AddonToKodiFuncTable_Game::CloseStream) (KODI_HANDLE, KODI_GAME_STREAM_HANDLE)
Referenced by kodi::addon::CInstanceGame::CStream::Close(), and KODI::GAME::CGameClient::Initialize().
GetStreamBuffer
bool(* AddonToKodiFuncTable_Game::GetStreamBuffer) (KODI_HANDLE, KODI_GAME_STREAM_HANDLE, unsigned int, unsigned int, struct game_stream_buffer *)
Referenced by kodi::addon::CInstanceGame::CStream::GetBuffer(), and KODI::GAME::CGameClient::Initialize().
HwGetProcAddress
game_proc_address_t(* AddonToKodiFuncTable_Game::HwGetProcAddress) (KODI_HANDLE kodiInstance, const char *symbol)
Referenced by KODI::GAME::CGameClient::Initialize().
InputEvent
bool(* AddonToKodiFuncTable_Game::InputEvent) (KODI_HANDLE kodiInstance, const struct game_input_event *event)
Referenced by KODI::GAME::CGameClient::Initialize().
kodiInstance
KODI_HANDLE AddonToKodiFuncTable_Game::kodiInstance
Referenced by kodi::addon::CInstanceGame::CStream::AddData(), kodi::addon::CInstanceGame::CStream::Close(), kodi::addon::CInstanceGame::CStream::GetBuffer(), KODI::GAME::CGameClient::Initialize(), kodi::addon::CInstanceGame::CStream::Open(), and kodi::addon::CInstanceGame::CStream::ReleaseBuffer().
OpenStream
KODI_GAME_STREAM_HANDLE(* AddonToKodiFuncTable_Game::OpenStream) (KODI_HANDLE, const struct game_stream_properties *)
Referenced by KODI::GAME::CGameClient::Initialize(), and kodi::addon::CInstanceGame::CStream::Open().
ReleaseStreamBuffer
void(* AddonToKodiFuncTable_Game::ReleaseStreamBuffer) (KODI_HANDLE, KODI_GAME_STREAM_HANDLE, struct game_stream_buffer *)
Referenced by KODI::GAME::CGameClient::Initialize(), and kodi::addon::CInstanceGame::CStream::ReleaseBuffer().
The documentation for this struct was generated from the following file:
c-api/addon-instance/game.h