Kodi Documentation: XFILE::CResourceFile Class Reference
XFILE::CResourceFile Class Reference
#include <ResourceFile.h>
Public Member Functions
CResourceFile ()
~CResourceFile () override
Public Member Functions inherited from XFILE::COverrideFile
COverrideFile (bool writable)
~COverrideFile () override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int Stat (struct __stat64 *buffer) override
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
bool Delete (const CURL &url) override
bool Rename (const CURL &url, const CURL &urlnew) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
void Close () override
int64_t GetPosition () override
int64_t GetLength () override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool SetHidden (const CURL &url, bool hidden)
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Static Public Member Functions
static bool TranslatePath (const std::string &path, std::string &translatedPath)
static bool TranslatePath (const CURL &url, std::string &translatedPath)
Protected Member Functions
std::string TranslatePath (const CURL &url) override
Additional Inherited Members
Protected Attributes inherited from XFILE::COverrideFile
CFile m_file
bool m_writable
Constructor & Destructor Documentation
CResourceFile()
CResourceFile::CResourceFile ()
~CResourceFile()
CResourceFile::~CResourceFile () override default
Member Function Documentation
TranslatePath() [1/3]
std::string CResourceFile::TranslatePath (const CURL & url) override protected virtual
Implements XFILE::COverrideFile.
References TranslatePath().
TranslatePath() [2/3]
bool CResourceFile::TranslatePath (const CURL & url, std::string & translatedPath) static
References CURL::Get(), CServiceBroker::GetAddonMgr(), CURL::GetFileName(), CURL::GetShareName(), CURL::IsProtocol(), and CUtil::ValidatePath().
TranslatePath() [3/3]
bool CResourceFile::TranslatePath (const std::string & path, std::string & translatedPath) static
References TranslatePath().
Referenced by XFILE::CResourceDirectory::GetDirectory(), CTexture::LoadFromFileInternal(), XFILE::CResourceDirectory::TranslatePath(), TranslatePath(), and TranslatePath().
The documentation for this class was generated from the following files:
ResourceFile.h
ResourceFile.cpp