Kodi Documentation: CResolutionUtils Class Reference
CResolutionUtils Class Reference
#include <Resolution.h>
Static Public Member Functions
static RESOLUTION ChooseBestResolution (float fps, int width, int height, bool is3D)
static bool HasWhitelist ()
static void PrintWhitelist ()
static void GetMaxAllowedScreenResolution (unsigned int &width, unsigned int &height)
Get the max allowed screen resolution, if fullscreen.
Static Protected Member Functions
static void FindResolutionFromWhitelist (float fps, int width, int height, bool is3D, RESOLUTION &resolution)
static bool FindResolutionFromOverride (float fps, int width, bool is3D, RESOLUTION &resolution, float &weight, bool fallback)
static float RefreshWeight (float refresh, float fps)
Member Function Documentation
ChooseBestResolution()
RESOLUTION CResolutionUtils::ChooseBestResolution (float fps, int width, int height, bool is3D) static
References FindResolutionFromOverride(), FindResolutionFromWhitelist(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetVideoResolution(), CServiceBroker::GetWinSystem(), CLog::Log(), and LOGINFO.
Referenced by CRenderManager::GetResolution(), CVideoPlayer::OpenVideoStream(), CWinSystemWin10::SetFullScreen(), CWinSystemWin32::SetFullScreen(), and CRenderManager::UpdateResolution().
FindResolutionFromOverride()
bool CResolutionUtils::FindResolutionFromOverride (float fps, int width, bool is3D, RESOLUTION & resolution, float & weight, bool fallback) static protected
References D3DPRESENTFLAG_MODEMASK, RESOLUTION_INFO::dwFlags, CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CGraphicContext::GetResInfo(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, CLog::Log(), LOGDEBUG, RefreshWeight(), RES_DESKTOP, and CDisplaySettings::ResolutionInfoSize().
Referenced by ChooseBestResolution().
FindResolutionFromWhitelist()
void CResolutionUtils::FindResolutionFromWhitelist (float fps, int width, int height, bool is3D, RESOLUTION & resolution) static protected
References D3DPRESENTFLAG_MODEMASK, RESOLUTION_INFO::dwFlags, MathUtils::FloatEquals(), CGraphicContext::GetAllowedResolutions(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResFromString(), CGraphicContext::GetResInfo(), CServiceBroker::GetSettingsComponent(), CDisplaySettings::GetStringFromRes(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, CLog::Log(), LOGDEBUG, LOGINFO, and CSettings::SETTING_VIDEOSCREEN_WHITELIST.
Referenced by ChooseBestResolution().
GetMaxAllowedScreenResolution()
void CResolutionUtils::GetMaxAllowedScreenResolution (unsigned int & width, unsigned int & height) static
Get the max allowed screen resolution, if fullscreen.
Parameters
width [OUT] Max width resolution
height [OUT] Max height resolution
References CGraphicContext::GetAllowedResolutions(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResFromString(), CGraphicContext::GetResInfo(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), and CSettings::SETTING_VIDEOSCREEN_WHITELIST.
Referenced by CInputStreamAddon::DetectScreenResolution().
HasWhitelist()
bool CResolutionUtils::HasWhitelist () static
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOSCREEN_WHITELIST.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool().
PrintWhitelist()
void CResolutionUtils::PrintWhitelist () static
References CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResFromString(), CGraphicContext::GetResInfo(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, and CSettings::SETTING_VIDEOSCREEN_WHITELIST.
Referenced by CWinSystemBase::InitWindowSystem(), and CDisplaySettings::OnSettingChanged().
RefreshWeight()
float CResolutionUtils::RefreshWeight (float refresh, float fps) static protected
References MathUtils::round_int().
Referenced by FindResolutionFromOverride().
The documentation for this class was generated from the following files:
Resolution.h
Resolution.cpp