Kodi Documentation: MUSIC_INFO::CMusicInfoTagLoaderFactory Class Reference
MUSIC_INFO::CMusicInfoTagLoaderFactory Class Reference
#include <MusicInfoTagLoaderFactory.h>
Public Member Functions
CMusicInfoTagLoaderFactory (void)
virtual ~CMusicInfoTagLoaderFactory ()
Static Public Member Functions
static IMusicInfoTagLoader * CreateLoader (const CFileItem &item)
Constructor & Destructor Documentation
CMusicInfoTagLoaderFactory()
CMusicInfoTagLoaderFactory::CMusicInfoTagLoaderFactory (void) default
~CMusicInfoTagLoaderFactory()
CMusicInfoTagLoaderFactory::~CMusicInfoTagLoaderFactory () virtual default
Member Function Documentation
CreateLoader()
IMusicInfoTagLoader * CMusicInfoTagLoaderFactory::CreateLoader (const CFileItem & item) static
References ADDON::AUDIODECODER, URIUtils::GetExtension(), KODI::ADDONS::CExtsMimeSupportList::GetExtensionSupportedAddonInfos(), CServiceBroker::GetExtsMimeSupportList(), CFileItem::GetPath(), KODI::NETWORK::IsInternetStream(), and KODI::MUSIC::IsMusicDb().
Referenced by anonymous_namespace{MusicEmbeddedImageFileLoader.cpp}::GetEmbeddedThumb(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CFileItem::LoadMusicTag(), KODI::CDRIP::CCDDARipper::RipCD(), and MUSIC_INFO::CMusicInfoScanner::ScanTags().
The documentation for this class was generated from the following files:
MusicInfoTagLoaderFactory.h
MusicInfoTagLoaderFactory.cpp