Kodi Documentation: KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase Class Reference
KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase Class Reference abstract
#include <VideoPlayActionProcessor.h>
Public Member Functions
CVideoPlayActionProcessorBase (const std::shared_ptr< CFileItem > &item)
virtual ~CVideoPlayActionProcessorBase ()=default
bool ProcessDefaultAction ()
bool ProcessAction (Action action)
bool UserCancelled () const
Static Public Member Functions
static Action ChoosePlayOrResume (const CFileItem &item)
Protected Member Functions
virtual Action GetDefaultAction ()
virtual bool Process (Action action)
virtual bool OnResumeSelected ()=0
virtual bool OnPlaySelected ()=0
Protected Attributes
std::shared_ptr< CFileItem > m_item
bool m_userCancelled {false}
Private Member Functions
CVideoPlayActionProcessorBase ()=delete
Constructor & Destructor Documentation
CVideoPlayActionProcessorBase() [1/2]
KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::CVideoPlayActionProcessorBase (const std::shared_ptr< CFileItem > & item) inline explicit
~CVideoPlayActionProcessorBase()
virtual KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::~CVideoPlayActionProcessorBase () virtual default
CVideoPlayActionProcessorBase() [2/2]
KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::CVideoPlayActionProcessorBase () private delete
Member Function Documentation
ChoosePlayOrResume()
Action KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::ChoosePlayOrResume (const CFileItem & item) static
References KODI::VIDEO::GUILIB::ACTION_PLAY_FROM_BEGINNING, KODI::VIDEO::GUILIB::ACTION_RESUME, CContextButtons::Add(), KODI::VIDEO::UTILS::GetResumeString(), and CGUIDialogContextMenu::ShowAndGetChoice().
Referenced by CGUIWindowVideoBase::OnPlayStackPart(), and Process().
GetDefaultAction()
Action KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::GetDefaultAction () protected virtual
Reimplemented in KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_MYVIDEOS_PLAYACTION.
Referenced by KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::Process(), and ProcessDefaultAction().
OnPlaySelected()
virtual bool KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::OnPlaySelected () protected pure virtual
Implemented in anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor, anonymous_namespace{GUIWindowFavourites.cpp}::CVideoPlayActionProcessor, anonymous_namespace{DirectoryProvider.cpp}::CVideoSelectActionProcessor, anonymous_namespace{DirectoryProvider.cpp}::CVideoPlayActionProcessor, PVR::CGUIPVRRecordingsPlayActionProcessor, anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor, anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoPlayActionProcessor, CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoSelectActionProcessor, CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoPlayActionProcessor, anonymous_namespace{GUIDialogVideoInfo.cpp}::CVideoPlayActionProcessor, anonymous_namespace{GUIDialogVideoManager.cpp}::CVideoPlayActionProcessor, anonymous_namespace{GUIWindowVideoBase.cpp}::CVideoSelectActionProcessor, anonymous_namespace{GUIWindowVideoBase.cpp}::CVideoPlayActionProcessor, and anonymous_namespace{GUIWindowVideoPlaylist.cpp}::CVideoPlayActionProcessor.
Referenced by Process().
OnResumeSelected()
virtual bool KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::OnResumeSelected () protected pure virtual
Implemented in anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor, anonymous_namespace{GUIWindowFavourites.cpp}::CVideoPlayActionProcessor, anonymous_namespace{DirectoryProvider.cpp}::CVideoSelectActionProcessor, anonymous_namespace{DirectoryProvider.cpp}::CVideoPlayActionProcessor, PVR::CGUIPVRRecordingsPlayActionProcessor, anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor, anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoPlayActionProcessor, CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoSelectActionProcessor, CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoPlayActionProcessor, anonymous_namespace{GUIDialogVideoInfo.cpp}::CVideoPlayActionProcessor, anonymous_namespace{GUIDialogVideoManager.cpp}::CVideoPlayActionProcessor, anonymous_namespace{GUIWindowVideoBase.cpp}::CVideoSelectActionProcessor, anonymous_namespace{GUIWindowVideoBase.cpp}::CVideoPlayActionProcessor, and anonymous_namespace{GUIWindowVideoPlaylist.cpp}::CVideoPlayActionProcessor.
Referenced by Process().
Process()
bool KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::Process (Action action) protected virtual
Reimplemented in KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase.
References KODI::VIDEO::GUILIB::ACTION_PLAY_FROM_BEGINNING, KODI::VIDEO::GUILIB::ACTION_PLAY_OR_RESUME, KODI::VIDEO::GUILIB::ACTION_RESUME, ChoosePlayOrResume(), m_item, m_userCancelled, OnPlaySelected(), OnResumeSelected(), and Process().
Referenced by Process(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::Process(), and ProcessAction().
ProcessAction()
bool KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::ProcessAction (Action action)
References KODI::VIDEO::GUILIB::CVideoVersionHelper::ChooseVideoFromAssets(), m_item, m_userCancelled, and Process().
Referenced by ProcessDefaultAction(), and CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::SetPathAndPlay().
ProcessDefaultAction()
bool KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::ProcessDefaultAction ()
References GetDefaultAction(), and ProcessAction().
Referenced by PVR::CGUIDialogPVRGuideInfo::OnClickButtonPlay(), and PVR::CGUIDialogPVRRecordingInfo::OnClickButtonPlay().
UserCancelled()
bool KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::UserCancelled () const inline
References m_userCancelled.
Member Data Documentation
m_item
std::shared_ptr<CFileItem> KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::m_item protected
Referenced by KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::ChooseStackItemPartNumber(), PVR::CGUIPVRRecordingsPlayActionProcessor::OnResumeSelected(), PVR::CGUIPVRRecordingsPlayActionProcessor::Play(), Process(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::Process(), and ProcessAction().
m_userCancelled
bool KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::m_userCancelled {false} protected
Referenced by Process(), ProcessAction(), and UserCancelled().
The documentation for this class was generated from the following files:
VideoPlayActionProcessor.h
VideoPlayActionProcessor.cpp