Kodi Documentation: CFTPParse Class Reference
CFTPParse Class Reference
#include <FTPParse.h>
Public Member Functions
CFTPParse ()
int FTPParse (const std::string &str)
const std::string & getName () const
int getFlagtrycwd ()
int getFlagtryretr ()
uint64_t getSize ()
time_t getTime ()
Private Member Functions
void setTime (const std::string &str)
Private Attributes
std::string m_name
int m_flagtrycwd
int m_flagtryretr
uint64_t m_size
time_t m_time = 0
Constructor & Destructor Documentation
CFTPParse()
CFTPParse::CFTPParse ()
References m_flagtrycwd, m_flagtryretr, and m_size.
Member Function Documentation
FTPParse()
int CFTPParse::FTPParse (const std::string & str)
References m_flagtrycwd, m_flagtryretr, m_name, m_size, m_time, name, owner, and setTime().
Referenced by XFILE::CFTPDirectory::GetDirectory().
getFlagtrycwd()
int CFTPParse::getFlagtrycwd ()
References m_flagtrycwd.
Referenced by XFILE::CFTPDirectory::GetDirectory().
getFlagtryretr()
int CFTPParse::getFlagtryretr ()
References m_flagtryretr.
Referenced by XFILE::CFTPDirectory::GetDirectory().
getName()
const std::string & CFTPParse::getName () const inline
References m_name.
Referenced by XFILE::CFTPDirectory::GetDirectory().
getSize()
uint64_t CFTPParse::getSize ()
References m_size.
Referenced by XFILE::CFTPDirectory::GetDirectory().
getTime()
time_t CFTPParse::getTime ()
References m_time.
Referenced by XFILE::CFTPDirectory::GetDirectory().
setTime()
void CFTPParse::setTime (const std::string & str) private
References day, m_time, and t.
Referenced by FTPParse().
Member Data Documentation
m_flagtrycwd
int CFTPParse::m_flagtrycwd private
Referenced by CFTPParse(), FTPParse(), and getFlagtrycwd().
m_flagtryretr
int CFTPParse::m_flagtryretr private
Referenced by CFTPParse(), FTPParse(), and getFlagtryretr().
m_name
std::string CFTPParse::m_name private
Referenced by FTPParse(), and getName().
m_size
uint64_t CFTPParse::m_size private
Referenced by CFTPParse(), FTPParse(), and getSize().
m_time
time_t CFTPParse::m_time = 0 private
Referenced by FTPParse(), getTime(), and setTime().
The documentation for this class was generated from the following files:
FTPParse.h
FTPParse.cpp