Kodi Documentation: CAEStreamParser Class Reference
CAEStreamParser Class Reference
#include <AEStreamInfo.h>
Public Member Functions
CAEStreamParser ()
~CAEStreamParser ()=default
int AddData (uint8_t *data, unsigned int size, uint8_t **buffer=NULL, unsigned int *bufferSize=0)
void SetCoreOnly (bool value)
unsigned int IsValid () const
unsigned int GetSampleRate () const
unsigned int GetChannels () const
unsigned int GetFrameSize () const
unsigned int GetDTSPeriod () const
unsigned int GetEAC3BlocksDiv () const
enum CAEStreamInfo::DataType GetDataType () const
bool IsLittleEndian () const
unsigned int GetBufferSize () const
CAEStreamInfo & GetStreamInfo ()
void Reset ()
Private Types
typedef unsigned int(CAEStreamParser::* ParseFunc) (uint8_t *data, unsigned int size)
Private Member Functions
void GetPacket (uint8_t **buffer, unsigned int *bufferSize)
unsigned int DetectType (uint8_t *data, unsigned int size)
bool TrySyncAC3 (uint8_t *data, unsigned int size, bool resyncing, bool wantEAC3dependent)
unsigned int SyncAC3 (uint8_t *data, unsigned int size)
unsigned int SyncDTS (uint8_t *data, unsigned int size)
unsigned int SyncTrueHD (uint8_t *data, unsigned int size)
Static Private Member Functions
static unsigned int GetTrueHDChannels (const uint16_t chanmap)
Private Attributes
uint8_t m_buffer [MAX_IEC61937_PACKET]
unsigned int m_bufferSize = 0
unsigned int m_skipBytes = 0
CAEStreamInfo m_info
bool m_coreOnly = false
unsigned int m_needBytes = 0
ParseFunc m_syncFunc
bool m_hasSync = false
unsigned int m_coreSize = 0
unsigned int m_dtsBlocks = 0
unsigned int m_fsize = 0
int m_substreams = 0
AVCRC m_crcTrueHD [1024]
Member Typedef Documentation
ParseFunc
typedef unsigned int(CAEStreamParser::* CAEStreamParser::ParseFunc) (uint8_t *data, unsigned int size) private
Constructor & Destructor Documentation
CAEStreamParser()
CAEStreamParser::CAEStreamParser ()
References m_crcTrueHD.
~CAEStreamParser()
CAEStreamParser::~CAEStreamParser () default
Member Function Documentation
AddData()
int CAEStreamParser::AddData (uint8_t * data, unsigned int size, uint8_t ** buffer = NULL, unsigned int * bufferSize = 0)
References copy(), data(), DetectType(), GetPacket(), m_buffer, m_bufferSize, m_fsize, m_hasSync, m_info, m_needBytes, CAEStreamInfo::m_repeat, m_skipBytes, m_syncFunc, CAEStreamInfo::m_type, and CAEStreamInfo::STREAM_TYPE_NULL.
Referenced by CDVDAudioCodecPassthrough::AddData().
DetectType()
unsigned int CAEStreamParser::DetectType (uint8_t * data, unsigned int size) private
References data(), DTS_PREAMBLE_14BE, DTS_PREAMBLE_14LE, DTS_PREAMBLE_16BE, DTS_PREAMBLE_16LE, m_hasSync, m_needBytes, SyncAC3(), SyncDTS(), and SyncTrueHD().
Referenced by AddData().
GetBufferSize()
unsigned int CAEStreamParser::GetBufferSize () const inline
References m_bufferSize.
Referenced by CDVDAudioCodecPassthrough::GetBufferSize().
GetChannels()
unsigned int CAEStreamParser::GetChannels () const inline
References CAEStreamInfo::m_channels, and m_info.
Referenced by CDVDAudioCodecPassthrough::AddData().
GetDataType()
enum CAEStreamInfo::DataType CAEStreamParser::GetDataType () const inline
References m_info, and CAEStreamInfo::m_type.
GetDTSPeriod()
unsigned int CAEStreamParser::GetDTSPeriod () const inline
References CAEStreamInfo::m_dtsPeriod, and m_info.
GetEAC3BlocksDiv()
unsigned int CAEStreamParser::GetEAC3BlocksDiv () const inline
References m_info, and CAEStreamInfo::m_repeat.
GetFrameSize()
unsigned int CAEStreamParser::GetFrameSize () const inline
References m_fsize.
GetPacket()
void CAEStreamParser::GetPacket (uint8_t ** buffer, unsigned int * bufferSize) private
References m_buffer, m_bufferSize, m_coreSize, m_fsize, m_info, CAEStreamInfo::m_type, and CAEStreamInfo::STREAM_TYPE_DTSHD_CORE.
Referenced by AddData().
GetSampleRate()
unsigned int CAEStreamParser::GetSampleRate () const inline
References m_info, and CAEStreamInfo::m_sampleRate.
Referenced by CDVDAudioCodecPassthrough::AddData().
GetStreamInfo()
CAEStreamInfo & CAEStreamParser::GetStreamInfo () inline
References m_info.
Referenced by CDVDAudioCodecPassthrough::AddData().
GetTrueHDChannels()
unsigned int CAEStreamParser::GetTrueHDChannels (const uint16_t chanmap) inline static private
References THDChanMap.
Referenced by SyncTrueHD().
IsLittleEndian()
bool CAEStreamParser::IsLittleEndian () const inline
References CAEStreamInfo::m_dataIsLE, and m_info.
IsValid()
unsigned int CAEStreamParser::IsValid () const inline
References m_hasSync.
Reset()
void CAEStreamParser::Reset ()
References m_bufferSize, m_hasSync, m_needBytes, and m_skipBytes.
Referenced by CDVDAudioCodecPassthrough::Reset().
SetCoreOnly()
void CAEStreamParser::SetCoreOnly (bool value) inline
References m_coreOnly, and value.
Referenced by CDVDAudioCodecPassthrough::Open().
SyncAC3()
unsigned int CAEStreamParser::SyncAC3 (uint8_t * data, unsigned int size) private
References data(), CLog::Log(), LOGINFO, m_hasSync, and TrySyncAC3().
Referenced by DetectType(), and TrySyncAC3().
SyncDTS()
unsigned int CAEStreamParser::SyncDTS (uint8_t * data, unsigned int size) private
References data(), DTS_PREAMBLE_14BE, DTS_PREAMBLE_14LE, DTS_PREAMBLE_16BE, DTS_PREAMBLE_16LE, DTS_PREAMBLE_HD, DTS_PREAMBLE_LBR, DTS_PREAMBLE_X96K, DTS_PREAMBLE_XBR, DTS_PREAMBLE_XCH, DTS_PREAMBLE_XLL, DTS_PREAMBLE_XXCH, DTS_SFREQ_COUNT, DTSChannels, DTSSampleRates, CLog::Log(), LOGINFO, CAEStreamInfo::m_channels, m_coreOnly, m_coreSize, CAEStreamInfo::m_dataIsLE, m_dtsBlocks, CAEStreamInfo::m_dtsPeriod, CAEStreamInfo::m_frameSize, m_fsize, m_hasSync, m_info, m_needBytes, CAEStreamInfo::m_repeat, CAEStreamInfo::m_sampleRate, m_syncFunc, CAEStreamInfo::m_type, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_NULL, SyncDTS(), and UNKNOWN_DTS_EXTENSION.
Referenced by DetectType(), and SyncDTS().
SyncTrueHD()
unsigned int CAEStreamParser::SyncTrueHD (uint8_t * data, unsigned int size) private
References data(), GetTrueHDChannels(), left, CLog::Log(), LOGINFO, CAEStreamInfo::m_channels, m_crcTrueHD, CAEStreamInfo::m_frameSize, m_fsize, m_hasSync, m_info, CAEStreamInfo::m_repeat, CAEStreamInfo::m_sampleRate, m_substreams, m_syncFunc, CAEStreamInfo::m_type, CAEStreamInfo::STREAM_TYPE_TRUEHD, and SyncTrueHD().
Referenced by DetectType(), and SyncTrueHD().
TrySyncAC3()
bool CAEStreamParser::TrySyncAC3 (uint8_t * data, unsigned int size, bool resyncing, bool wantEAC3dependent) private
References AC3Bitrates, AC3BlkCod, AC3Channels, AC3FSCod, data(), CLog::Log(), LOGINFO, CAEStreamInfo::m_channels, CAEStreamInfo::m_frameSize, m_fsize, m_hasSync, m_info, m_needBytes, CAEStreamInfo::m_repeat, CAEStreamInfo::m_sampleRate, m_syncFunc, CAEStreamInfo::m_type, MAX_EAC3_BLOCKS, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_EAC3, SyncAC3(), and TrySyncAC3().
Referenced by SyncAC3(), and TrySyncAC3().
Member Data Documentation
m_buffer
uint8_t CAEStreamParser::m_buffer[MAX_IEC61937_PACKET] private
Referenced by AddData(), and GetPacket().
m_bufferSize
unsigned int CAEStreamParser::m_bufferSize = 0 private
Referenced by AddData(), GetBufferSize(), GetPacket(), and Reset().
m_coreOnly
bool CAEStreamParser::m_coreOnly = false private
Referenced by SetCoreOnly(), and SyncDTS().
m_coreSize
unsigned int CAEStreamParser::m_coreSize = 0 private
Referenced by GetPacket(), and SyncDTS().
m_crcTrueHD
AVCRC CAEStreamParser::m_crcTrueHD[1024] private
Referenced by CAEStreamParser(), and SyncTrueHD().
m_dtsBlocks
unsigned int CAEStreamParser::m_dtsBlocks = 0 private
Referenced by SyncDTS().
m_fsize
unsigned int CAEStreamParser::m_fsize = 0 private
Referenced by AddData(), GetFrameSize(), GetPacket(), SyncDTS(), SyncTrueHD(), and TrySyncAC3().
m_hasSync
bool CAEStreamParser::m_hasSync = false private
Referenced by AddData(), DetectType(), IsValid(), Reset(), SyncAC3(), SyncDTS(), SyncTrueHD(), and TrySyncAC3().
m_info
CAEStreamInfo CAEStreamParser::m_info private
Referenced by AddData(), GetChannels(), GetDataType(), GetDTSPeriod(), GetEAC3BlocksDiv(), GetPacket(), GetSampleRate(), GetStreamInfo(), IsLittleEndian(), SyncDTS(), SyncTrueHD(), and TrySyncAC3().
m_needBytes
unsigned int CAEStreamParser::m_needBytes = 0 private
Referenced by AddData(), DetectType(), Reset(), SyncDTS(), and TrySyncAC3().
m_skipBytes
unsigned int CAEStreamParser::m_skipBytes = 0 private
Referenced by AddData(), and Reset().
m_substreams
int CAEStreamParser::m_substreams = 0 private
Referenced by SyncTrueHD().
m_syncFunc
ParseFunc CAEStreamParser::m_syncFunc private
Referenced by AddData(), SyncDTS(), SyncTrueHD(), and TrySyncAC3().
The documentation for this class was generated from the following files:
AEStreamInfo.h
AEStreamInfo.cpp