Kodi Documentation: CDVDClock Class Reference
CDVDClock Class Reference
#include <DVDClock.h>
Public Member Functions
CDVDClock ()
~CDVDClock ()
double GetClock (bool interpolated=true)
double GetClock (double &absolute, bool interpolated=true)
double ErrorAdjust (double error, const char *log)
void Discontinuity (double clock, double absolute)
void Discontinuity (double clock=0LL)
void Reset ()
void SetSpeed (int iSpeed)
void SetSpeedAdjust (double adjust)
double GetSpeedAdjust ()
double GetClockSpeed ()
int UpdateFramerate (double fps, double *interval=NULL)
void SetMaxSpeedAdjust (double speed)
double GetAbsoluteClock (bool interpolated=true)
double GetFrequency ()
bool GetClockInfo (int &MissedVblanks, double &ClockSpeed, double &RefreshRate) const
void SetVsyncAdjust (double adjustment)
double GetVsyncAdjust ()
void Pause (bool pause)
void Advance (double time)
Protected Member Functions
double SystemToAbsolute (int64_t system)
int64_t AbsoluteToSystem (double absolute)
double SystemToPlaying (int64_t system)
Protected Attributes
CCriticalSection m_critSection
int64_t m_systemUsed
int64_t m_startClock
int64_t m_pauseClock
double m_iDisc
bool m_bReset
bool m_paused
int m_speedAfterPause
std::unique_ptr< CVideoReferenceClock > m_videoRefClock
int64_t m_systemFrequency
int64_t m_systemOffset
CCriticalSection m_systemsection
int64_t m_systemAdjust
int64_t m_lastSystemTime
double m_speedAdjust
double m_vSyncAdjust
double m_frameTime
double m_maxspeedadjust
CCriticalSection m_speedsection
Constructor & Destructor Documentation
CDVDClock()
CDVDClock::CDVDClock ()
References CurrentHostFrequency(), DVD_PLAYSPEED_PAUSE, DVD_TIME_BASE, m_bReset, m_frameTime, m_iDisc, m_lastSystemTime, m_maxspeedadjust, m_pauseClock, m_paused, m_speedAdjust, m_speedAfterPause, m_startClock, m_systemAdjust, m_systemFrequency, m_systemOffset, m_systemsection, m_systemUsed, m_videoRefClock, and m_vSyncAdjust.
~CDVDClock()
CDVDClock::~CDVDClock () default
Member Function Documentation
AbsoluteToSystem()
int64_t CDVDClock::AbsoluteToSystem (double absolute) protected
References DVD_TIME_BASE, int64_t(), m_systemFrequency, and m_systemOffset.
Referenced by Discontinuity().
Advance()
void CDVDClock::Advance (double time)
References DVD_TIME_BASE, m_critSection, m_pauseClock, and m_systemFrequency.
Referenced by CVideoPlayer::HandleMessages().
Discontinuity() [1/2]
void CDVDClock::Discontinuity (double clock, double absolute)
References AbsoluteToSystem(), m_bReset, m_critSection, m_iDisc, m_pauseClock, m_speedAdjust, m_startClock, and m_systemAdjust.
Referenced by Discontinuity(), ErrorAdjust(), CVideoPlayer::FlushBuffers(), CVideoPlayer::HandlePlaySpeed(), CVideoPlayer::Prepare(), and CVideoPlayer::Process().
Discontinuity() [2/2]
void CDVDClock::Discontinuity (double clock = 0LL) inline
References Discontinuity(), and GetAbsoluteClock().
ErrorAdjust()
double CDVDClock::ErrorAdjust (double error, const char * log)
References Discontinuity(), DVD_MSEC_TO_TIME(), DVD_TIME_BASE, GetClock(), log(), CLog::Log(), LOGDEBUG, m_critSection, m_frameTime, m_speedAdjust, and m_vSyncAdjust.
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
GetAbsoluteClock()
double CDVDClock::GetAbsoluteClock (bool interpolated = true)
References int64_t(), m_systemsection, m_videoRefClock, and SystemToAbsolute().
Referenced by CAudioSinkAE::AddPackets(), Discontinuity(), CAudioSinkAE::GetPlayingPts(), CVideoPlayer::HandleMessages(), CVideoPlayer::HandlePlaySpeed(), and CVideoPlayer::UpdatePlayState().
GetClock() [1/2]
double CDVDClock::GetClock (bool interpolated = true)
References int64_t(), m_critSection, m_lastSystemTime, m_speedAdjust, m_systemAdjust, m_videoRefClock, and SystemToPlaying().
Referenced by ErrorAdjust(), CAudioSinkAE::GetClock(), CVideoPlayer::HandleMessages(), CVideoPlayer::HandlePlaySpeed(), CVideoPlayerVideo::OutputPicture(), CRenderManager::PrepareNextRender(), CVideoPlayer::Process(), CVideoPlayer::UpdatePlayState(), and CRenderManager::WaitForBuffer().
GetClock() [2/2]
double CDVDClock::GetClock (double & absolute, bool interpolated = true)
References int64_t(), m_lastSystemTime, m_speedAdjust, m_systemAdjust, m_systemsection, m_videoRefClock, SystemToAbsolute(), and SystemToPlaying().
GetClockInfo()
bool CDVDClock::GetClockInfo (int & MissedVblanks, double & ClockSpeed, double & RefreshRate) const
References m_videoRefClock.
Referenced by CRenderManager::CheckEnableClockSync(), and CRenderManager::Render().
GetClockSpeed()
double CDVDClock::GetClockSpeed ()
get the current speed of the clock relative normal system time
References m_critSection, m_speedAdjust, m_systemFrequency, m_systemUsed, and m_videoRefClock.
Referenced by CAudioSinkAE::AddPackets(), CAudioSinkAE::GetClockSpeed(), and CRenderManager::PrepareNextRender().
GetFrequency()
double CDVDClock::GetFrequency () inline
References m_systemFrequency.
GetSpeedAdjust()
double CDVDClock::GetSpeedAdjust ()
References m_critSection, and m_speedAdjust.
Referenced by CVideoPlayer::HandlePlaySpeed().
GetVsyncAdjust()
double CDVDClock::GetVsyncAdjust ()
References m_critSection, and m_vSyncAdjust.
Referenced by CAudioSinkAE::GetClock().
Pause()
void CDVDClock::Pause (bool pause)
References DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, m_critSection, m_pauseClock, m_paused, m_speedAfterPause, m_systemFrequency, m_systemUsed, and SetSpeed().
Referenced by CVideoPlayer::OnLostDisplay(), and CVideoPlayer::OnResetDisplay().
Reset()
void CDVDClock::Reset () inline
References m_bReset.
Referenced by CVideoPlayer::OpenInputStream().
SetMaxSpeedAdjust()
void CDVDClock::SetMaxSpeedAdjust (double speed)
References m_maxspeedadjust, and m_speedsection.
Referenced by CVideoPlayerAudio::SetSyncType().
SetSpeed()
void CDVDClock::SetSpeed (int iSpeed)
References DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, int64_t(), m_critSection, m_pauseClock, m_paused, m_speedAfterPause, m_startClock, m_systemFrequency, m_systemUsed, and m_videoRefClock.
Referenced by CVideoPlayer::HandleMessages(), Pause(), and CVideoPlayer::SetCaching().
SetSpeedAdjust()
void CDVDClock::SetSpeedAdjust (double adjust)
References CLog::Log(), LOGDEBUG, m_critSection, and m_speedAdjust.
Referenced by CVideoPlayer::HandlePlaySpeed(), and CVideoPlayer::SetCaching().
SetVsyncAdjust()
void CDVDClock::SetVsyncAdjust (double adjustment)
References m_critSection, and m_vSyncAdjust.
Referenced by CRenderManager::CheckEnableClockSync(), CRenderManager::Configure(), CRenderManager::Configure(), and CRenderManager::PrepareNextRender().
SystemToAbsolute()
double CDVDClock::SystemToAbsolute (int64_t system) protected
References DVD_TIME_BASE, m_systemFrequency, and m_systemOffset.
Referenced by GetAbsoluteClock(), and GetClock().
SystemToPlaying()
double CDVDClock::SystemToPlaying (int64_t system) protected
References DVD_TIME_BASE, int64_t(), m_bReset, m_iDisc, m_pauseClock, m_speedAdjust, m_startClock, m_systemAdjust, m_systemFrequency, m_systemUsed, and m_vSyncAdjust.
Referenced by GetClock(), and GetClock().
UpdateFramerate()
int CDVDClock::UpdateFramerate (double fps, double * interval = NULL)
References DVD_TIME_BASE, m_frameTime, m_maxspeedadjust, m_speedsection, m_videoRefClock, and MathUtils::round_int().
Referenced by CVideoPlayerVideo::OutputPicture().
Member Data Documentation
m_bReset
bool CDVDClock::m_bReset protected
Referenced by CDVDClock(), Discontinuity(), Reset(), and SystemToPlaying().
m_critSection
CCriticalSection CDVDClock::m_critSection protected
Referenced by Advance(), Discontinuity(), ErrorAdjust(), GetClock(), GetClockSpeed(), GetSpeedAdjust(), GetVsyncAdjust(), Pause(), SetSpeed(), SetSpeedAdjust(), and SetVsyncAdjust().
m_frameTime
double CDVDClock::m_frameTime protected
Referenced by CDVDClock(), ErrorAdjust(), and UpdateFramerate().
m_iDisc
double CDVDClock::m_iDisc protected
Referenced by CDVDClock(), Discontinuity(), and SystemToPlaying().
m_lastSystemTime
int64_t CDVDClock::m_lastSystemTime protected
Referenced by CDVDClock(), GetClock(), and GetClock().
m_maxspeedadjust
double CDVDClock::m_maxspeedadjust protected
Referenced by CDVDClock(), SetMaxSpeedAdjust(), and UpdateFramerate().
m_pauseClock
int64_t CDVDClock::m_pauseClock protected
Referenced by Advance(), CDVDClock(), Discontinuity(), Pause(), SetSpeed(), and SystemToPlaying().
m_paused
bool CDVDClock::m_paused protected
Referenced by CDVDClock(), Pause(), and SetSpeed().
m_speedAdjust
double CDVDClock::m_speedAdjust protected
Referenced by CDVDClock(), Discontinuity(), ErrorAdjust(), GetClock(), GetClock(), GetClockSpeed(), GetSpeedAdjust(), SetSpeedAdjust(), and SystemToPlaying().
m_speedAfterPause
int CDVDClock::m_speedAfterPause protected
Referenced by CDVDClock(), Pause(), and SetSpeed().
m_speedsection
CCriticalSection CDVDClock::m_speedsection protected
Referenced by SetMaxSpeedAdjust(), and UpdateFramerate().
m_startClock
int64_t CDVDClock::m_startClock protected
Referenced by CDVDClock(), Discontinuity(), SetSpeed(), and SystemToPlaying().
m_systemAdjust
int64_t CDVDClock::m_systemAdjust protected
Referenced by CDVDClock(), Discontinuity(), GetClock(), GetClock(), and SystemToPlaying().
m_systemFrequency
int64_t CDVDClock::m_systemFrequency protected
Referenced by AbsoluteToSystem(), Advance(), CDVDClock(), GetClockSpeed(), GetFrequency(), Pause(), SetSpeed(), SystemToAbsolute(), and SystemToPlaying().
m_systemOffset
int64_t CDVDClock::m_systemOffset protected
Referenced by AbsoluteToSystem(), CDVDClock(), and SystemToAbsolute().
m_systemsection
CCriticalSection CDVDClock::m_systemsection protected
Referenced by CDVDClock(), GetAbsoluteClock(), and GetClock().
m_systemUsed
int64_t CDVDClock::m_systemUsed protected
Referenced by CDVDClock(), GetClockSpeed(), Pause(), SetSpeed(), and SystemToPlaying().
m_videoRefClock
std::unique_ptr<CVideoReferenceClock> CDVDClock::m_videoRefClock protected
Referenced by CDVDClock(), GetAbsoluteClock(), GetClock(), GetClock(), GetClockInfo(), GetClockSpeed(), SetSpeed(), and UpdateFramerate().
m_vSyncAdjust
double CDVDClock::m_vSyncAdjust protected
Referenced by CDVDClock(), ErrorAdjust(), GetVsyncAdjust(), SetVsyncAdjust(), and SystemToPlaying().
The documentation for this class was generated from the following files:
DVDClock.h
DVDClock.cpp