Kodi Documentation: VDPAU::COutput Class Reference
VDPAU::COutput Class Reference
#include <VDPAU.h>
Public Member Functions
COutput (CDecoder &decoder, CEvent *inMsgEvent)
~COutput () override
void Start ()
void Dispose ()
Public Attributes
COutputControlProtocol m_controlPort
COutputDataProtocol m_dataPort
Protected Member Functions
void OnStartup () override
void OnExit () override
void Process () override
void StateMachine (int signal, Actor::Protocol *port, Actor::Message *msg)
bool HasWork ()
CVdpauRenderPicture * ProcessMixerPicture ()
void QueueReturnPicture (CVdpauRenderPicture *pic)
void ProcessReturnPicture (CVdpauRenderPicture *pic)
void ProcessSyncPicture ()
bool Init ()
bool Uninit ()
void Flush ()
bool EnsureBufferPool ()
void ReleaseBufferPool ()
void PreCleanup ()
void InitMixer ()
bool CheckStatus (VdpStatus vdp_st, int line)
Protected Attributes
CEvent m_outMsgEvent
CEvent * m_inMsgEvent
int m_state
bool m_bStateMachineSelfTrigger
CDecoder & m_vdpau
int m_extTimeout
bool m_vdpError
CVdpauConfig m_config
std::shared_ptr< CVdpauBufferPool > m_bufferPool
CMixer m_mixer
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
COutput()
COutput::COutput (CDecoder & decoder, CEvent * inMsgEvent)
References m_inMsgEvent.
~COutput()
COutput::~COutput () override
References Dispose().
Member Function Documentation
CheckStatus()
bool COutput::CheckStatus (VdpStatus vdp_st, int line) protected
References VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetProcs(), CLog::Log(), LOGERROR, m_config, m_vdpError, and VDPAU::VDPAU_procs::vdp_get_error_string.
Referenced by EnsureBufferPool(), PreCleanup(), and ReleaseBufferPool().
Dispose()
void COutput::Dispose ()
References CServiceBroker::GetWinSystem(), CThread::m_bStop, m_controlPort, m_dataPort, m_outMsgEvent, Actor::Protocol::Purge(), CEvent::Set(), and CThread::StopThread().
Referenced by VDPAU::CDecoder::Close(), VDPAU::CDecoder::ConfigVDPAU(), VDPAU::CDecoder::FiniVDPAUOutput(), and ~COutput().
EnsureBufferPool()
bool COutput::EnsureBufferPool () protected
References VDPAU::CMixerDataProtocol::BUFFER, CheckStatus(), VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetDevice(), VDPAU::CVDPAUContext::GetProcs(), CLog::Log(), LOGINFO, m_bufferPool, m_config, VDPAU::CMixer::m_dataPort, m_mixer, VDPAU::CVdpauConfig::outHeight, VDPAU::CVdpauConfig::outWidth, Actor::Protocol::SendOutMessage(), and VDPAU::VDPAU_procs::vdp_output_surface_create.
Referenced by ProcessMixerPicture(), and StateMachine().
Flush()
void COutput::Flush () protected
References VDPAU::CMixerDataProtocol::BUFFER, VDPAU::CVideoSurfaces::ClearRender(), Actor::Message::data, VDPAU::CMixerControlProtocol::FLUSH, Actor::CPayloadWrap< Payload >::GetPlayload(), VDPAU::CMixer::IsActive(), VDPAU::CVdpauProcessedPicture::isYuv, CLog::Log(), LOGERROR, m_bufferPool, m_config, VDPAU::CMixer::m_controlPort, VDPAU::CMixer::m_dataPort, m_dataPort, m_mixer, VDPAU::CVideoSurfaces::MarkRender(), VDPAU::COutputDataProtocol::NEWFRAME, VDPAU::CVdpauProcessedPicture::outputSurface, Actor::Message::payloadObj, VDPAU::CMixerDataProtocol::PICTURE, VDPAU::COutputDataProtocol::PICTURE, QueueReturnPicture(), Actor::Protocol::ReceiveInMessage(), Actor::Protocol::ReceiveOutMessage(), CVideoBuffer::Release(), Actor::Message::Release(), VDPAU::COutputDataProtocol::RETURNPIC, Actor::Protocol::SendOutMessage(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, VDPAU::CVdpauDecodedPicture::videoSurface, VDPAU::CVdpauProcessedPicture::videoSurface, and VDPAU::CVdpauConfig::videoSurfaces.
Referenced by Process(), and StateMachine().
HasWork()
bool COutput::HasWork () protected
References m_bufferPool.
Referenced by StateMachine().
Init()
bool COutput::Init () protected
References m_mixer, m_vdpError, and VDPAU::CMixer::Start().
Referenced by StateMachine().
InitMixer()
void COutput::InitMixer () protected
References VDPAU::CMixerDataProtocol::BUFFER, m_bufferPool, VDPAU::CMixer::m_dataPort, m_mixer, and Actor::Protocol::SendOutMessage().
OnExit()
void COutput::OnExit () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
OnStartup()
void COutput::OnStartup () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
PreCleanup()
void COutput::PreCleanup () protected
References CheckStatus(), VDPAU::CVdpauConfig::context, VDPAU::CMixer::Dispose(), VDPAU::CVDPAUContext::GetProcs(), CLog::Log(), LOGDEBUG, LOGVIDEO, m_bufferPool, m_config, m_mixer, ProcessSyncPicture(), and VDPAU::VDPAU_procs::vdp_output_surface_destroy.
Referenced by StateMachine().
Process()
void COutput::Process (void) override protected virtual
Reimplemented from CThread.
References Flush(), Actor::Protocol::GetMessage(), m_bStateMachineSelfTrigger, CThread::m_bStop, m_controlPort, VDPAU::CMixer::m_dataPort, m_dataPort, m_extTimeout, m_mixer, m_outMsgEvent, m_state, O_TOP_UNCONFIGURED, Actor::Protocol::ReceiveInMessage(), Actor::Protocol::ReceiveOutMessage(), Actor::Message::Release(), Actor::Message::signal, StateMachine(), VDPAU::COutputControlProtocol::TIMEOUT, Uninit(), and CEvent::Wait().
ProcessMixerPicture()
CVdpauRenderPicture * COutput::ProcessMixerPicture () protected
References VDPAU::CVdpauConfig::context, VDPAU::CVdpauProcessedPicture::crop, VDPAU::CVdpauRenderPicture::crop, VDPAU::CVdpauRenderPicture::device, VDPAU::CVdpauProcessedPicture::DVDPic, VDPAU::CVdpauRenderPicture::DVDPic, EnsureBufferPool(), VDPAU::CVDPAUContext::GetDevice(), VDPAU::CVDPAUContext::GetProcs(), VDPAU::CVdpauRenderPicture::height, VDPAU::CVdpauProcessedPicture::id, VDPAU::CVdpauRenderPicture::ident, VDPAU::CVdpauProcessedPicture::isYuv, m_bufferPool, m_config, NUM_CROP_PIX, NUM_RENDER_PICS, VDPAU::CVdpauConfig::outHeight, VDPAU::CVdpauConfig::outWidth, VDPAU::CVdpauRenderPicture::procFunc, VDPAU::CVdpauRenderPicture::procPic, VDPAU::CVdpauConfig::resetCounter, VideoPicture::SetParams(), VDPAU::CVdpauConfig::surfaceHeight, VDPAU::CVdpauConfig::surfaceWidth, VDPAU::CVdpauConfig::timeOpened, VDPAU::CVdpauConfig::useInteropYuv, VDPAU::VDPAU_procs::vdp_get_proc_address, VDPAU::CVdpauConfig::vidHeight, VDPAU::CVdpauConfig::vidWidth, VDPAU::CVdpauRenderPicture::width, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by StateMachine().
ProcessReturnPicture()
void COutput::ProcessReturnPicture (CVdpauRenderPicture * pic) protected
References VDPAU::CMixerDataProtocol::BUFFER, VDPAU::CVideoSurfaces::ClearRender(), VDPAU::CVdpauProcessedPicture::id, VDPAU::CVdpauProcessedPicture::isYuv, m_bufferPool, m_config, VDPAU::CMixer::m_dataPort, m_mixer, VDPAU::CVdpauProcessedPicture::outputSurface, VDPAU::CVdpauRenderPicture::procPic, Actor::Protocol::SendOutMessage(), VDPAU::CVdpauProcessedPicture::videoSurface, and VDPAU::CVdpauConfig::videoSurfaces.
Referenced by ProcessSyncPicture().
ProcessSyncPicture()
void COutput::ProcessSyncPicture () protected
References m_bufferPool, and ProcessReturnPicture().
Referenced by PreCleanup(), QueueReturnPicture(), ReleaseBufferPool(), and Uninit().
QueueReturnPicture()
void COutput::QueueReturnPicture (CVdpauRenderPicture * pic) protected
References m_bufferPool, and ProcessSyncPicture().
Referenced by Flush(), and StateMachine().
ReleaseBufferPool()
void COutput::ReleaseBufferPool () protected
References CheckStatus(), VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetProcs(), m_bufferPool, m_config, ProcessSyncPicture(), and VDPAU::VDPAU_procs::vdp_output_surface_destroy.
Referenced by Uninit().
Start()
void COutput::Start ()
References CThread::Create().
Referenced by VDPAU::CDecoder::ConfigVDPAU().
StateMachine()
void COutput::StateMachine (int signal, Actor::Protocol * port, Actor::Message * msg) protected
References VDPAU::CMixerControlProtocol::ACC, VDPAU::COutputControlProtocol::ACC, Actor::Message::data, data(), VDPAU::CVdpauBufferStats::DecProcessed(), EnsureBufferPool(), VDPAU::COutputControlProtocol::ERROR, VDPAU::COutputControlProtocol::FLUSH, Flush(), VDPAU::CMixerDataProtocol::FRAME, HasWork(), VDPAU::CVdpauBufferStats::IncRender(), VDPAU::CMixerControlProtocol::INIT, VDPAU::COutputControlProtocol::INIT, Init(), CLog::Log(), LOGERROR, LOGWARNING, m_bufferPool, m_config, VDPAU::CMixer::m_controlPort, m_controlPort, VDPAU::CMixer::m_dataPort, m_dataPort, m_extTimeout, m_mixer, m_state, m_vdpError, VDPAU::COutputDataProtocol::NEWFRAME, O_TOP, O_TOP_CONFIGURED, O_TOP_CONFIGURED_IDLE, O_TOP_CONFIGURED_WORK, O_TOP_ERROR, O_TOP_UNCONFIGURED, Actor::Message::payloadObj, VDPAU::CMixerDataProtocol::PICTURE, VDPAU::COutputDataProtocol::PICTURE, Actor::Protocol::portName, VDPAU::COutputControlProtocol::PRECLEANUP, PreCleanup(), ProcessMixerPicture(), QueueReturnPicture(), Actor::Message::Release(), Actor::Message::Reply(), VDPAU::COutputDataProtocol::RETURNPIC, Actor::Protocol::SendInMessage(), Actor::Protocol::SendOutMessage(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, VDPAU::CVdpauConfig::stats, VDPAU::COutputControlProtocol::STATS, VDPAU::COutputControlProtocol::TIMEOUT, and VDPAU_OUTPUT_parentStates.
Referenced by Process().
Uninit()
bool COutput::Uninit () protected
References VDPAU::CMixer::Dispose(), m_mixer, ProcessSyncPicture(), and ReleaseBufferPool().
Referenced by Process().
Member Data Documentation
m_bStateMachineSelfTrigger
bool VDPAU::COutput::m_bStateMachineSelfTrigger protected
Referenced by Process().
m_bufferPool
std::shared_ptr<CVdpauBufferPool> VDPAU::COutput::m_bufferPool protected
Referenced by EnsureBufferPool(), Flush(), HasWork(), InitMixer(), PreCleanup(), ProcessMixerPicture(), ProcessReturnPicture(), ProcessSyncPicture(), QueueReturnPicture(), ReleaseBufferPool(), and StateMachine().
m_config
CVdpauConfig VDPAU::COutput::m_config protected
Referenced by CheckStatus(), EnsureBufferPool(), Flush(), PreCleanup(), ProcessMixerPicture(), ProcessReturnPicture(), ReleaseBufferPool(), and StateMachine().
m_controlPort
COutputControlProtocol VDPAU::COutput::m_controlPort
Referenced by VDPAU::CDecoder::ConfigVDPAU(), VDPAU::CDecoder::Decode(), Dispose(), Process(), VDPAU::CDecoder::Release(), VDPAU::CDecoder::Reset(), and StateMachine().
m_dataPort
COutputDataProtocol VDPAU::COutput::m_dataPort
Referenced by VDPAU::CDecoder::Decode(), Dispose(), Flush(), Process(), VDPAU::CDecoder::ReturnRenderPicture(), and StateMachine().
m_extTimeout
int VDPAU::COutput::m_extTimeout protected
Referenced by Process(), and StateMachine().
m_inMsgEvent
CEvent* VDPAU::COutput::m_inMsgEvent protected
Referenced by COutput().
m_mixer
CMixer VDPAU::COutput::m_mixer protected
Referenced by EnsureBufferPool(), Flush(), Init(), InitMixer(), PreCleanup(), Process(), ProcessReturnPicture(), StateMachine(), and Uninit().
m_outMsgEvent
CEvent VDPAU::COutput::m_outMsgEvent protected
Referenced by Dispose(), and Process().
m_state
int VDPAU::COutput::m_state protected
Referenced by Process(), and StateMachine().
m_vdpau
CDecoder& VDPAU::COutput::m_vdpau protected
m_vdpError
bool VDPAU::COutput::m_vdpError protected
Referenced by CheckStatus(), Init(), and StateMachine().
The documentation for this class was generated from the following files:
VDPAU.h
VDPAU.cpp