Kodi Documentation: KODI::CDRIP::CEncoderFFmpeg Class Reference
KODI::CDRIP::CEncoderFFmpeg Class Reference
#include <EncoderFFmpeg.h>
Public Member Functions
CEncoderFFmpeg ()=default
~CEncoderFFmpeg () override=default
bool Init () override
ssize_t Encode (uint8_t *pbtStream, size_t nNumBytesRead) override
bool Close () override
Public Member Functions inherited from KODI::CDRIP::CEncoder
CEncoder ()
virtual ~CEncoder ()
bool EncoderInit (const std::string &strFile, int iInChannels, int iInRate, int iInBits)
ssize_t EncoderEncode (uint8_t *pbtStream, size_t nNumBytesRead)
bool EncoderClose ()
void SetComment (const std::string &str)
void SetArtist (const std::string &str)
void SetTitle (const std::string &str)
void SetAlbum (const std::string &str)
void SetAlbumArtist (const std::string &str)
void SetGenre (const std::string &str)
void SetTrack (const std::string &str)
void SetTrackLength (int length)
void SetYear (const std::string &str)
Public Member Functions inherited from KODI::CDRIP::IEncoder
virtual ~IEncoder ()=default
Private Member Functions
void SetTag (const std::string &tag, const std::string &value)
bool WriteFrame ()
AVSampleFormat GetInputFormat (int inBitsPerSample)
Static Private Member Functions
static int avio_write_callback (void *opaque, uint8_t *buf, int buf_size)
static int64_t avio_seek_callback (void *opaque, int64_t offset, int whence)
Private Attributes
AVFormatContext * m_formatCtx {nullptr}
AVCodecContext * m_codecCtx {nullptr}
SwrContext * m_swrCtx {nullptr}
AVStream * m_stream {nullptr}
AVSampleFormat m_inFormat
AVSampleFormat m_outFormat
unsigned int m_neededFrames {0}
size_t m_neededBytes {0}
uint8_t * m_buffer {nullptr}
size_t m_bufferSize {0}
AVFrame * m_bufferFrame {nullptr}
uint8_t * m_resampledBuffer {nullptr}
size_t m_resampledBufferSize {0}
AVFrame * m_resampledFrame {nullptr}
bool m_needConversion {false}
int64_t m_samplesCount {0}
int64_t m_samplesCountMultiply {1000}
Static Private Attributes
static constexpr size_t BUFFER_SIZE = 4096
Additional Inherited Members
Public Attributes inherited from KODI::CDRIP::IEncoder
std::string m_strComment
std::string m_strArtist
std::string m_strAlbumArtist
std::string m_strTitle
std::string m_strAlbum
std::string m_strGenre
std::string m_strTrack
std::string m_strYear
std::string m_strFile
int m_iTrackLength = 0
int m_iInChannels = 0
int m_iInSampleRate = 0
int m_iInBitsPerSample = 0
Protected Member Functions inherited from KODI::CDRIP::CEncoder
virtual ssize_t Write (const uint8_t *pBuffer, size_t iBytes)
virtual ssize_t Seek (ssize_t iFilePosition, int iWhence)
Constructor & Destructor Documentation
CEncoderFFmpeg()
KODI::CDRIP::CEncoderFFmpeg::CEncoderFFmpeg () default
~CEncoderFFmpeg()
KODI::CDRIP::CEncoderFFmpeg::~CEncoderFFmpeg () override default
Member Function Documentation
avio_seek_callback()
int64_t CEncoderFFmpeg::avio_seek_callback (void * opaque, int64_t offset, int whence) static private
References KODI::CDRIP::CEncoder::Seek().
Referenced by Init().
avio_write_callback()
int CEncoderFFmpeg::avio_write_callback (void * opaque, uint8_t * buf, int buf_size) static private
References CLog::Log(), LOGERROR, and KODI::CDRIP::CEncoder::Write().
Referenced by Init().
Close()
bool CEncoderFFmpeg::Close () override virtual
Implements KODI::CDRIP::IEncoder.
References m_buffer, m_bufferFrame, m_bufferSize, m_codecCtx, m_formatCtx, m_needConversion, m_neededBytes, m_resampledBuffer, m_resampledFrame, m_swrCtx, and WriteFrame().
Encode()
ssize_t CEncoderFFmpeg::Encode (uint8_t * pbtStream, size_t nNumBytesRead) override virtual
Implements KODI::CDRIP::IEncoder.
References copy(), m_buffer, m_bufferSize, m_neededBytes, and WriteFrame().
GetInputFormat()
AVSampleFormat CEncoderFFmpeg::GetInputFormat (int inBitsPerSample) private
Referenced by Init().
Init()
bool CEncoderFFmpeg::Init () override virtual
Implements KODI::CDRIP::IEncoder.
References avio_seek_callback(), avio_write_callback(), BUFFER_SIZE, ADDON::CHOICE_YES, err(), ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), CSysInfo::GetAppName(), URIUtils::GetFileName(), GetInputFormat(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, LOGERROR, m_buffer, m_bufferFrame, m_bufferSize, m_codecCtx, m_formatCtx, KODI::CDRIP::IEncoder::m_iInBitsPerSample, KODI::CDRIP::IEncoder::m_iInChannels, KODI::CDRIP::IEncoder::m_iInSampleRate, m_inFormat, m_needConversion, m_neededBytes, m_neededFrames, m_outFormat, m_resampledBuffer, m_resampledBufferSize, m_resampledFrame, m_samplesCountMultiply, KODI::CDRIP::IEncoder::m_strAlbum, KODI::CDRIP::IEncoder::m_strArtist, m_stream, KODI::CDRIP::IEncoder::m_strFile, KODI::CDRIP::IEncoder::m_strGenre, KODI::CDRIP::IEncoder::m_strTitle, KODI::CDRIP::IEncoder::m_strTrack, m_swrCtx, SetTag(), CSettings::SETTING_AUDIOCDS_ENCODER, success, and FFMPEG_HELP_TOOLS::FFMpegException::what().
SetTag()
void CEncoderFFmpeg::SetTag (const std::string & tag, const std::string & value) private
References m_formatCtx, and value.
Referenced by Init().
WriteFrame()
bool CEncoderFFmpeg::WriteFrame () private
Bug:
libavresample isn't const correct
References err(), CLog::Log(), LOGERROR, m_bufferFrame, m_bufferSize, m_codecCtx, m_formatCtx, m_needConversion, m_neededFrames, m_resampledFrame, m_samplesCount, m_samplesCountMultiply, m_swrCtx, and FFMPEG_HELP_TOOLS::FFMpegException::what().
Referenced by Close(), and Encode().
Member Data Documentation
BUFFER_SIZE
constexpr size_t KODI::CDRIP::CEncoderFFmpeg::BUFFER_SIZE = 4096 static constexpr private
Referenced by Init().
m_buffer
uint8_t* KODI::CDRIP::CEncoderFFmpeg::m_buffer {nullptr} private
Referenced by Close(), Encode(), and Init().
m_bufferFrame
AVFrame* KODI::CDRIP::CEncoderFFmpeg::m_bufferFrame {nullptr} private
Referenced by Close(), Init(), and WriteFrame().
m_bufferSize
size_t KODI::CDRIP::CEncoderFFmpeg::m_bufferSize {0} private
Referenced by Close(), Encode(), Init(), and WriteFrame().
m_codecCtx
AVCodecContext* KODI::CDRIP::CEncoderFFmpeg::m_codecCtx {nullptr} private
Referenced by Close(), Init(), and WriteFrame().
m_formatCtx
AVFormatContext* KODI::CDRIP::CEncoderFFmpeg::m_formatCtx {nullptr} private
Referenced by Close(), Init(), SetTag(), and WriteFrame().
m_inFormat
AVSampleFormat KODI::CDRIP::CEncoderFFmpeg::m_inFormat private
Referenced by Init().
m_needConversion
bool KODI::CDRIP::CEncoderFFmpeg::m_needConversion {false} private
Referenced by Close(), Init(), and WriteFrame().
m_neededBytes
size_t KODI::CDRIP::CEncoderFFmpeg::m_neededBytes {0} private
Referenced by Close(), Encode(), and Init().
m_neededFrames
unsigned int KODI::CDRIP::CEncoderFFmpeg::m_neededFrames {0} private
Referenced by Init(), and WriteFrame().
m_outFormat
AVSampleFormat KODI::CDRIP::CEncoderFFmpeg::m_outFormat private
Referenced by Init().
m_resampledBuffer
uint8_t* KODI::CDRIP::CEncoderFFmpeg::m_resampledBuffer {nullptr} private
Referenced by Close(), and Init().
m_resampledBufferSize
size_t KODI::CDRIP::CEncoderFFmpeg::m_resampledBufferSize {0} private
Referenced by Init().
m_resampledFrame
AVFrame* KODI::CDRIP::CEncoderFFmpeg::m_resampledFrame {nullptr} private
Referenced by Close(), Init(), and WriteFrame().
m_samplesCount
int64_t KODI::CDRIP::CEncoderFFmpeg::m_samplesCount {0} private
Referenced by WriteFrame().
m_samplesCountMultiply
int64_t KODI::CDRIP::CEncoderFFmpeg::m_samplesCountMultiply {1000} private
Referenced by Init(), and WriteFrame().
m_stream
AVStream* KODI::CDRIP::CEncoderFFmpeg::m_stream {nullptr} private
Referenced by Init().
m_swrCtx
SwrContext* KODI::CDRIP::CEncoderFFmpeg::m_swrCtx {nullptr} private
Referenced by Close(), Init(), and WriteFrame().
The documentation for this class was generated from the following files:
EncoderFFmpeg.h
EncoderFFmpeg.cpp