Kodi Documentation: CAndroidUtils Class Reference
CAndroidUtils Class Reference
#include <AndroidUtils.h>
Public Member Functions
CAndroidUtils ()
~CAndroidUtils () override=default
bool GetNativeResolution (RESOLUTION_INFO *res) const
bool SetNativeResolution (const RESOLUTION_INFO &res)
bool ProbeResolutions (std::vector< RESOLUTION_INFO > &resolutions)
bool UpdateDisplayModes ()
bool IsHDRDisplay ()
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Static Public Member Functions
static bool SupportsMediaCodecMimeType (const std::string &mimeType)
static std::vector< int > GetDisplaySupportedHdrTypes ()
static CHDRCapabilities GetDisplayHDRCapabilities ()
static std::pair< bool, bool > GetDolbyVisionCapabilities ()
Static Public Attributes
static const std::string SETTING_LIMITGUI = "videoscreen.limitgui"
Protected Attributes
int m_width
int m_height
Static Private Member Functions
static void LogDisplaySupportedHdrTypes ()
Constructor & Destructor Documentation
CAndroidUtils()
CAndroidUtils::CAndroidUtils ()
References fetchDisplayModes(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, LogDisplaySupportedHdrTypes(), m_height, m_width, s_res_displayModes, and SETTING_LIMITGUI.
~CAndroidUtils()
CAndroidUtils::~CAndroidUtils () override default
Member Function Documentation
GetDisplayHDRCapabilities()
CHDRCapabilities CAndroidUtils::GetDisplayHDRCapabilities () static
References GetDisplaySupportedHdrTypes(), CHDRCapabilities::SetDolbyVision(), CHDRCapabilities::SetHDR10(), CHDRCapabilities::SetHDR10Plus(), CHDRCapabilities::SetHLG(), and types.
Referenced by CWinSystemAndroid::GetDisplayHDRCapabilities(), and GetDolbyVisionCapabilities().
GetDisplaySupportedHdrTypes()
std::vector< int > CAndroidUtils::GetDisplaySupportedHdrTypes () static
Referenced by GetDisplayHDRCapabilities(), and LogDisplaySupportedHdrTypes().
GetDolbyVisionCapabilities()
std::pair< bool, bool > CAndroidUtils::GetDolbyVisionCapabilities () static
References GetDisplayHDRCapabilities(), CLog::Log(), LOGDEBUG, CHDRCapabilities::SupportsDolbyVision(), and SupportsMediaCodecMimeType().
Referenced by CDVDVideoCodecAndroidMediaCodec::Open().
GetNativeResolution()
bool CAndroidUtils::GetNativeResolution (RESOLUTION_INFO * res) const
References D3DPRESENTFLAG_INTERLACED, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fRefreshRate, CXBMCApp::Get(), CXBMCApp::GetNativeWindow(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, CLog::Log(), LOGINFO, m_height, m_width, s_res_cur_displayMode, and RESOLUTION_INFO::strMode.
Referenced by ProbeResolutions(), and CWinSystemAndroid::UpdateResolutions().
IsHDRDisplay()
bool CAndroidUtils::IsHDRDisplay ()
References CLog::Log(), and LOGDEBUG.
Referenced by CWinSystemAndroid::IsHDRDisplay().
LogDisplaySupportedHdrTypes()
void CAndroidUtils::LogDisplaySupportedHdrTypes () static private
References GetDisplaySupportedHdrTypes(), CLog::Log(), LOGDEBUG, and text.
Referenced by CAndroidUtils().
OnSettingChanged()
void CAndroidUtils::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References CDisplaySettings::ClearCalibrations(), CDisplaySettings::GetInstance(), and SETTING_LIMITGUI.
ProbeResolutions()
bool CAndroidUtils::ProbeResolutions (std::vector< RESOLUTION_INFO > & resolutions)
References GetNativeResolution(), CLog::Log(), LOGDEBUG, m_height, m_width, and s_res_displayModes.
Referenced by CWinSystemAndroid::UpdateResolutions().
SetNativeResolution()
bool CAndroidUtils::SetNativeResolution (const RESOLUTION_INFO & res)
References RESOLUTION_INFO::fRefreshRate, CXBMCApp::Get(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iWidth, CLog::Log(), LOGINFO, s_res_cur_displayMode, CXBMCApp::SetBuffersGeometry(), CXBMCApp::SetDisplayMode(), and RESOLUTION_INFO::strId.
Referenced by CWinSystemAndroid::CreateNewWindow().
SupportsMediaCodecMimeType()
bool CAndroidUtils::SupportsMediaCodecMimeType (const std::string & mimeType) static
References types.
Referenced by GetDolbyVisionCapabilities().
UpdateDisplayModes()
bool CAndroidUtils::UpdateDisplayModes ()
References fetchDisplayModes().
Referenced by CWinSystemAndroid::UpdateDisplayModes().
Member Data Documentation
m_height
int CAndroidUtils::m_height mutable protected
Referenced by CAndroidUtils(), GetNativeResolution(), and ProbeResolutions().
m_width
int CAndroidUtils::m_width mutable protected
Referenced by CAndroidUtils(), GetNativeResolution(), and ProbeResolutions().
SETTING_LIMITGUI
const std::string CAndroidUtils::SETTING_LIMITGUI = "videoscreen.limitgui" static
Referenced by CAndroidUtils(), and OnSettingChanged().
The documentation for this class was generated from the following files:
AndroidUtils.h
AndroidUtils.cpp