Kodi Documentation: CHttpResponseRange Class Reference
CHttpResponseRange Class Reference
#include <HttpRangeUtils.h>
Public Member Functions
CHttpResponseRange ()
CHttpResponseRange (uint64_t firstPosition, uint64_t lastPosition)
CHttpResponseRange (const void *data, uint64_t firstPosition, uint64_t lastPosition)
CHttpResponseRange (const void *data, uint64_t length)
~CHttpResponseRange () override=default
bool operator== (const CHttpResponseRange &other) const
bool operator!= (const CHttpResponseRange &other) const
const void * GetData () const
void SetData (const void *data)
void SetData (const void *data, uint64_t length)
void SetData (const void *data, uint64_t firstPosition, uint64_t lastPosition)
bool IsValid () const override
Public Member Functions inherited from CHttpRange
CHttpRange ()=default
CHttpRange (uint64_t firstPosition, uint64_t lastPosition)
virtual ~CHttpRange ()=default
bool operator< (const CHttpRange &other) const
bool operator== (const CHttpRange &other) const
bool operator!= (const CHttpRange &other) const
virtual uint64_t GetFirstPosition () const
virtual void SetFirstPosition (uint64_t firstPosition)
virtual uint64_t GetLastPosition () const
virtual void SetLastPosition (uint64_t lastPosition)
virtual uint64_t GetLength () const
virtual void SetLength (uint64_t length)
Protected Attributes
const void * m_data
Protected Attributes inherited from CHttpRange
uint64_t m_first = 1
uint64_t m_last = 0
Constructor & Destructor Documentation
CHttpResponseRange() [1/4]
CHttpResponseRange::CHttpResponseRange ()
CHttpResponseRange() [2/4]
CHttpResponseRange::CHttpResponseRange (uint64_t firstPosition, uint64_t lastPosition)
CHttpResponseRange() [3/4]
CHttpResponseRange::CHttpResponseRange (const void * data, uint64_t firstPosition, uint64_t lastPosition)
CHttpResponseRange() [4/4]
CHttpResponseRange::CHttpResponseRange (const void * data, uint64_t length)
~CHttpResponseRange()
CHttpResponseRange::~CHttpResponseRange () override default
Member Function Documentation
GetData()
const void * CHttpResponseRange::GetData () const inline
References m_data.
Referenced by CWebServer::CreateMemoryDownloadResponse(), and TEST().
IsValid()
bool CHttpResponseRange::IsValid () const override virtual
Reimplemented from CHttpRange.
References CHttpRange::IsValid(), and m_data.
Referenced by CWebServer::CreateMemoryDownloadResponse(), and TEST().
operator!=()
bool CHttpResponseRange::operator!= (const CHttpResponseRange & other) const
operator==()
bool CHttpResponseRange::operator== (const CHttpResponseRange & other) const
References m_data.
SetData() [1/3]
void CHttpResponseRange::SetData (const void * data) inline
References data(), and m_data.
Referenced by CHTTPJsonRpcHandler::HandleRequest(), CHTTPWebinterfaceAddonsHandler::HandleRequest(), SetData(), SetData(), and TEST().
SetData() [2/3]
void CHttpResponseRange::SetData (const void * data, uint64_t firstPosition, uint64_t lastPosition)
References data(), SetData(), CHttpRange::SetFirstPosition(), and CHttpRange::SetLastPosition().
SetData() [3/3]
void CHttpResponseRange::SetData (const void * data, uint64_t length)
References data(), CHttpRange::m_first, SetData(), and CHttpRange::SetLength().
Member Data Documentation
m_data
const void* CHttpResponseRange::m_data protected
Referenced by GetData(), IsValid(), operator==(), and SetData().
The documentation for this class was generated from the following files:
HttpRangeUtils.h
HttpRangeUtils.cpp