Kodi Documentation: ADDON::SExtValue Struct Reference
ADDON::SExtValue Struct Reference
#include <AddonExtensions.h>
Public Member Functions
SExtValue (const std::string &strValue)
const std::string & asString () const
bool asBoolean () const
int asInteger () const
float asFloat () const
bool empty () const
Public Attributes
const std::string str
Constructor & Destructor Documentation
SExtValue()
ADDON::SExtValue::SExtValue (const std::string & strValue) inline explicit
Member Function Documentation
asBoolean()
bool SExtValue::asBoolean () const
References str.
Referenced by ADDON::CLanguageResource::CLanguageResource().
asFloat()
float ADDON::SExtValue::asFloat () const inline
References str.
asInteger()
int ADDON::SExtValue::asInteger () const inline
References str.
asString()
const std::string & ADDON::SExtValue::asString () const inline
References str.
Referenced by ADDON::CContextMenuAddon::CContextMenuAddon(), ADDON::CLanguageResource::CLanguageResource(), ADDON::CAddonDatabaseSerializer::DeserializeExtensions(), ADDON::CRepository::ParseDirConfiguration(), ADDON::CContextMenuAddon::ParseMenu(), ADDON::CAddonInfoBuilder::ParseXMLTypes(), and ADDON::CAddonInfoBuilderFromDB::SetExtensions().
empty()
bool ADDON::SExtValue::empty () const inline
References str.
Referenced by ADDON::CAddonInfoBuilder::ParseXMLTypes(), and ADDON::CAddonInfoBuilderFromDB::SetExtensions().
Member Data Documentation
str
const std::string ADDON::SExtValue::str
Referenced by asBoolean(), asFloat(), asInteger(), asString(), and empty().
The documentation for this struct was generated from the following files:
AddonExtensions.h
AddonExtensions.cpp