Kodi Documentation: CConvolutionShader Class Reference
CConvolutionShader Class Reference abstract
#include <WinVideoFilter.h>
Classes
struct Vertex
Public Member Functions
virtual ~CConvolutionShader ()=default
virtual bool Create (ESCALINGMETHOD method, const std::shared_ptr< COutputShader > &pOutShader=nullptr)=0
virtual void Render (CD3DTexture &sourceTexture, CD3DTexture &target, CRect sourceRect, CRect destRect, bool useLimitRange)=0
Protected Member Functions
CConvolutionShader ()=default
virtual bool ChooseKernelD3DFormat ()
virtual bool CreateHQKernel (ESCALINGMETHOD method)
virtual void SetShaderParameters (CD3DTexture &sourceTexture, float *texSteps, int texStepsCount, bool useLimitRange)=0
Protected Member Functions inherited from CWinShader
CWinShader ()=default
virtual ~CWinShader ()=default
virtual bool CreateVertexBuffer (unsigned int vertCount, unsigned int vertSize)
virtual bool LockVertexBuffer (void **data)
virtual bool UnlockVertexBuffer ()
virtual bool LoadEffect (const std::string &filename, DefinesMap *defines)
virtual bool Execute (const std::vector< CD3DTexture * > &targets, unsigned int vertexIndexStep)
virtual void SetStepParams (unsigned stepIndex)
virtual bool CreateInputLayout (D3D11_INPUT_ELEMENT_DESC *layout, unsigned numElements)
Protected Attributes
bool m_floattex = false
bool m_rgba = false
DXGI_FORMAT m_KernelFormat = DXGI_FORMAT_UNKNOWN
CD3DTexture m_HQKernelTexture
std::shared_ptr< COutputShader > m_pOutShader = nullptr
Protected Attributes inherited from CWinShader
CD3DEffect m_effect
CD3DTexture * m_target = nullptr
Constructor & Destructor Documentation
~CConvolutionShader()
virtual CConvolutionShader::~CConvolutionShader () virtual default
CConvolutionShader()
CConvolutionShader::CConvolutionShader () protected default
Member Function Documentation
ChooseKernelD3DFormat()
bool CConvolutionShader::ChooseKernelD3DFormat () protected virtual
References m_floattex, m_KernelFormat, and m_rgba.
Referenced by CConvolutionShader1Pass::Create(), and CConvolutionShaderSeparable::Create().
Create()
virtual bool CConvolutionShader::Create (ESCALINGMETHOD method, const std::shared_ptr< COutputShader > & pOutShader = nullptr) pure virtual
Implemented in CConvolutionShader1Pass, and CConvolutionShaderSeparable.
CreateHQKernel()
bool CConvolutionShader::CreateHQKernel (ESCALINGMETHOD method) protected virtual
References CD3DTexture::Create(), data(), CConvolutionKernel::GetFloatPixels(), CConvolutionKernel::GetSize(), CConvolutionKernel::GetUint8Pixels(), LOGERROR, m_floattex, m_HQKernelTexture, and m_KernelFormat.
Referenced by CConvolutionShader1Pass::Create(), and CConvolutionShaderSeparable::Create().
Render()
virtual void CConvolutionShader::Render (CD3DTexture & sourceTexture, CD3DTexture & target, CRect sourceRect, CRect destRect, bool useLimitRange) pure virtual
Implemented in CConvolutionShader1Pass, and CConvolutionShaderSeparable.
SetShaderParameters()
virtual void CConvolutionShader::SetShaderParameters (CD3DTexture & sourceTexture, float * texSteps, int texStepsCount, bool useLimitRange) protected pure virtual
Implemented in CConvolutionShader1Pass, and CConvolutionShaderSeparable.
Member Data Documentation
m_floattex
bool CConvolutionShader::m_floattex = false protected
Referenced by ChooseKernelD3DFormat(), CConvolutionShader1Pass::Create(), CConvolutionShaderSeparable::Create(), and CreateHQKernel().
m_HQKernelTexture
CD3DTexture CConvolutionShader::m_HQKernelTexture protected
Referenced by CreateHQKernel(), CConvolutionShader1Pass::SetShaderParameters(), and CConvolutionShaderSeparable::SetShaderParameters().
m_KernelFormat
DXGI_FORMAT CConvolutionShader::m_KernelFormat = DXGI_FORMAT_UNKNOWN protected
Referenced by ChooseKernelD3DFormat(), and CreateHQKernel().
m_pOutShader
std::shared_ptr<COutputShader> CConvolutionShader::m_pOutShader = nullptr protected
Referenced by CConvolutionShader1Pass::Create(), CConvolutionShaderSeparable::Create(), CConvolutionShader1Pass::SetShaderParameters(), and CConvolutionShaderSeparable::SetShaderParameters().
m_rgba
bool CConvolutionShader::m_rgba = false protected
Referenced by ChooseKernelD3DFormat(), CConvolutionShader1Pass::Create(), and CConvolutionShaderSeparable::Create().
The documentation for this class was generated from the following files:
WinVideoFilter.h
WinVideoFilter.cpp