Kodi Documentation: Variant.cpp File Reference
Variant.cpp File Reference
#include "Variant.h"
#include <charconv>
#include <cstdlib>
#include <cstring>
#include <string>
#include <utility>
#include <variant>
Classes
struct overloaded< Ts >
Macros
#define _LIBCPP_DISABLE_AVAILABILITY
#define strtoll(str, endptr, base) (int64_t)strtod(str, endptr)
#define strtoull(str, endptr, base) (uint64_t)strtod(str, endptr)
#define wcstoll(str, endptr, base) (int64_t)wcstod(str, endptr)
#define wcstoull(str, endptr, base) (uint64_t)wcstod(str, endptr)
Functions
template<class... Ts>
overloaded (Ts...) -> overloaded< Ts... >
std::string_view trim (std::string_view str)
std::wstring_view trim (std::wstring_view str)
int64_t str2int64 (std::string_view str, int64_t fallback)
int64_t str2int64 (std::wstring_view str, int64_t fallback)
uint64_t str2uint64 (std::string_view str, uint64_t fallback)
uint64_t str2uint64 (std::wstring_view str, uint64_t fallback)
double str2double (std::string_view str, double fallback)
double str2double (std::wstring_view str, double fallback)
Macro Definition Documentation
_LIBCPP_DISABLE_AVAILABILITY
#define _LIBCPP_DISABLE_AVAILABILITY
strtoll
#define strtoll (str, endptr, base) (int64_t)strtod(str, endptr)
strtoull
#define strtoull (str, endptr, base) (uint64_t)strtod(str, endptr)
wcstoll
#define wcstoll (str, endptr, base) (int64_t)wcstod(str, endptr)
wcstoull
#define wcstoull (str, endptr, base) (uint64_t)wcstod(str, endptr)
Function Documentation
overloaded()
template<class... Ts> overloaded (Ts...) -> overloaded< Ts... >
str2double() [1/2]
double str2double (std::string_view str, double fallback)
References end(), and trim().
str2double() [2/2]
double str2double (std::wstring_view str, double fallback)
References end(), and trim().
str2int64() [1/2]
int64_t str2int64 (std::string_view str, int64_t fallback)
References int64_t(), and trim().
Referenced by CVariant::asInteger().
str2int64() [2/2]
int64_t str2int64 (std::wstring_view str, int64_t fallback)
References end(), int64_t(), trim(), and wcstoll.
str2uint64() [1/2]
uint64_t str2uint64 (std::string_view str, uint64_t fallback)
References trim().
Referenced by CVariant::asDouble(), CVariant::asUnsignedInteger(), TestWebServer::CheckRangesTestFileResponse(), CVideoInfoTag::GetDurationFromMinuteString(), and CHttpRanges::Parse().
str2uint64() [2/2]
uint64_t str2uint64 (std::wstring_view str, uint64_t fallback)
References end(), trim(), and wcstoull.
trim() [1/2]
std::string_view trim (std::string_view str)
Referenced by str2double(), str2double(), str2int64(), str2int64(), str2uint64(), and str2uint64().
trim() [2/2]
std::wstring_view trim (std::wstring_view str)