Kodi Documentation: UPNP::CUPnPRenderer Class Reference
UPNP::CUPnPRenderer Class Reference
#include <UPnPRenderer.h>
Public Member Functions
CUPnPRenderer (const char *friendly_name, bool show_ip=false, const char *uuid=NULL, unsigned int port=0)
~CUPnPRenderer () override
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
void UpdateState ()
NPT_Result ProcessHttpGetRequest (NPT_HttpRequest &request, const NPT_HttpRequestContext &context, NPT_HttpResponse &response) override
NPT_Result OnNext (PLT_ActionReference &action) override
NPT_Result OnPause (PLT_ActionReference &action) override
NPT_Result OnPlay (PLT_ActionReference &action) override
NPT_Result OnPrevious (PLT_ActionReference &action) override
NPT_Result OnStop (PLT_ActionReference &action) override
NPT_Result OnSeek (PLT_ActionReference &action) override
NPT_Result OnSetAVTransportURI (PLT_ActionReference &action) override
NPT_Result OnSetNextAVTransportURI (PLT_ActionReference &action) override
NPT_Result OnSetVolume (PLT_ActionReference &action) override
NPT_Result OnSetMute (PLT_ActionReference &action) override
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Private Member Functions
NPT_Result SetupServices () override
NPT_Result SetupIcons () override
NPT_Result GetMetadata (NPT_String &meta)
NPT_Result PlayMedia (const NPT_String &uri, const NPT_String &meta, PLT_Action *action=NULL)
NPT_Result Reset (PLT_Service *avt)
NPT_String GetTransportState ()
Private Attributes
NPT_Mutex m_state
Constructor & Destructor Documentation
CUPnPRenderer()
UPNP::CUPnPRenderer::CUPnPRenderer (const char * friendly_name, bool show_ip = false, const char * uuid = NULL, unsigned int port = 0)
References ANNOUNCEMENT::Application, CServiceBroker::GetAnnouncementManager(), and ANNOUNCEMENT::Player.
~CUPnPRenderer()
UPNP::CUPnPRenderer::~CUPnPRenderer () override
References CServiceBroker::GetAnnouncementManager().
Member Function Documentation
Announce()
void UPNP::CUPnPRenderer::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References ANNOUNCEMENT::CAnnouncementManager::ANNOUNCEMENT_SENDER, ANNOUNCEMENT::Application, data(), g_application, GetMetadata(), int64_t(), m_state, ANNOUNCEMENT::Player, and Reset().
GetMetadata()
NPT_Result UPNP::CUPnPRenderer::GetMetadata (NPT_String & meta) private
References UPNP::BuildObject(), g_application, CGUIListItem::GetArt(), CNetworkInterface::GetCurrentIPAddress(), CNetworkBase::GetFirstConnectedInterface(), CServiceBroker::GetGUI(), CGUIInfoManager::GetImage(), CGUIComponent::GetInfoManager(), CServiceBroker::GetNetwork(), URIUtils::HasExtension(), MUSICPLAYER_COVER, UPNP::UPnPRenderer, IMAGE_FILES::URLFromFile(), and VIDEOPLAYER_COVER.
Referenced by Announce().
GetTransportState()
NPT_String UPNP::CUPnPRenderer::GetTransportState () private
References m_state.
Referenced by OnPause(), OnPlay(), OnSeek(), OnSetAVTransportURI(), and OnSetNextAVTransportURI().
OnNext()
NPT_Result UPNP::CUPnPRenderer::OnNext (PLT_ActionReference & action) override
References ACTION_NEXT_PICTURE, CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), TMSG_GUI_ACTION, TMSG_PLAYLISTPLAYER_NEXT, and WINDOW_SLIDESHOW.
OnPause()
NPT_Result UPNP::CUPnPRenderer::OnPause (PLT_ActionReference & action) override
References ACTION_NEXT_PICTURE, CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), GetTransportState(), TMSG_GUI_ACTION, TMSG_MEDIA_PAUSE, and WINDOW_SLIDESHOW.
OnPlay()
NPT_Result UPNP::CUPnPRenderer::OnPlay (PLT_ActionReference & action) override
References CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), GetTransportState(), PlayMedia(), TMSG_MEDIA_PAUSE, and WINDOW_SLIDESHOW.
OnPrevious()
NPT_Result UPNP::CUPnPRenderer::OnPrevious (PLT_ActionReference & action) override
References ACTION_PREV_PICTURE, CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), TMSG_GUI_ACTION, TMSG_PLAYLISTPLAYER_PREV, and WINDOW_SLIDESHOW.
OnSeek()
NPT_Result UPNP::CUPnPRenderer::OnSeek (PLT_ActionReference & action) override
References CServiceBroker::GetAppMessenger(), GetTransportState(), int64_t(), and TMSG_MEDIA_SEEK_TIME.
OnSetAVTransportURI()
NPT_Result UPNP::CUPnPRenderer::OnSetAVTransportURI (PLT_ActionReference & action) override
References CServiceBroker::GetGUI(), GetTransportState(), PlayMedia(), and WINDOW_SLIDESHOW.
OnSetMute()
NPT_Result UPNP::CUPnPRenderer::OnSetMute (PLT_ActionReference & action) override
References CServiceBroker::GetAppMessenger(), and TMSG_SET_MUTE.
OnSetNextAVTransportURI()
NPT_Result UPNP::CUPnPRenderer::OnSetNextAVTransportURI (PLT_ActionReference & action) override
Todo:
get rid of window checks (go via SlideshowDelegator)
References CServiceBroker::GetAppMessenger(), UPNP::GetFileItem(), CServiceBroker::GetGUI(), GetTransportState(), playlist, TMSG_PLAYLISTPLAYER_ADD, and WINDOW_SLIDESHOW.
OnSetVolume()
NPT_Result UPNP::CUPnPRenderer::OnSetVolume (PLT_ActionReference & action) override
References CServiceBroker::GetAppMessenger(), int64_t(), and TMSG_SET_VOLUME.
OnStop()
NPT_Result UPNP::CUPnPRenderer::OnStop (PLT_ActionReference & action) override
References ACTION_NEXT_PICTURE, CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), TMSG_GUI_ACTION, TMSG_MEDIA_STOP, and WINDOW_SLIDESHOW.
PlayMedia()
NPT_Result UPNP::CUPnPRenderer::PlayMedia (const NPT_String & uri, const NPT_String & meta, PLT_Action * action = NULL) private
References CFileItemList::Add(), CServiceBroker::GetAppMessenger(), UPNP::GetFileItem(), m_state, TMSG_MEDIA_PLAY, and TMSG_PICTURE_SHOW.
Referenced by OnPlay(), and OnSetAVTransportURI().
ProcessHttpGetRequest()
NPT_Result UPNP::CUPnPRenderer::ProcessHttpGetRequest (NPT_HttpRequest & request, const NPT_HttpRequestContext & context, NPT_HttpResponse & response) override
References UPNP::GetMimeType().
Reset()
NPT_Result UPNP::CUPnPRenderer::Reset (PLT_Service * avt) private
SetupIcons()
NPT_Result UPNP::CUPnPRenderer::SetupIcons () override private
References CSpecialProtocol::TranslatePath().
SetupServices()
NPT_Result UPNP::CUPnPRenderer::SetupServices () override private
UpdateState()
void UPNP::CUPnPRenderer::UpdateState ()
Todo:
: Remove dependency on GUI, go via slideshowdelegator
References CSlideShowDelegator::CurrentSlide(), INFO::DEFAULT_CONTEXT, g_application, CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetLabel(), CServiceBroker::GetSlideShowDelegator(), index(), m_state, CSlideShowDelegator::NumSlides(), Reset(), SLIDESHOW_FILE_PATH, TIME_FORMAT_HH_MM_SS, and WINDOW_SLIDESHOW.
Member Data Documentation
m_state
NPT_Mutex UPNP::CUPnPRenderer::m_state private
Referenced by Announce(), GetTransportState(), PlayMedia(), and UpdateState().
The documentation for this class was generated from the following files:
UPnPRenderer.h
UPnPRenderer.cpp