Kodi Documentation: KODI::ACTION::CActionTranslator Class Reference
KODI::ACTION::CActionTranslator Class Reference
#include <ActionTranslator.h>
Static Public Member Functions
static void GetActions (std::vector< std::string > &actionList)
static bool IsAnalog (unsigned int actionId)
static bool TranslateString (std::string strAction, unsigned int &actionId)
Member Function Documentation
GetActions()
void CActionTranslator::GetActions (std::vector< std::string > & actionList) static
Referenced by JSONRPC::CJSONRPC::Initialize().
IsAnalog()
bool CActionTranslator::IsAnalog (unsigned int actionId) static
References ACTION_ANALOG_FORWARD, ACTION_ANALOG_MOVE, ACTION_ANALOG_MOVE_X_LEFT, ACTION_ANALOG_MOVE_X_RIGHT, ACTION_ANALOG_MOVE_Y_DOWN, ACTION_ANALOG_MOVE_Y_UP, ACTION_ANALOG_REWIND, ACTION_ANALOG_SEEK_BACK, ACTION_ANALOG_SEEK_FORWARD, ACTION_CURSOR_LEFT, ACTION_CURSOR_RIGHT, ACTION_SCROLL_DOWN, ACTION_SCROLL_UP, ACTION_VOLUME_DOWN, ACTION_VOLUME_UP, ACTION_ZOOM_IN, and ACTION_ZOOM_OUT.
Referenced by CAction::IsAnalog(), KODI::KEYMAP::CKeyHandler::OnAnalogMotion(), and KODI::KEYMAP::CKeyHandler::ProcessAction().
TranslateString()
bool CActionTranslator::TranslateString (std::string strAction, unsigned int & actionId) static
References ACTION_BUILT_IN_FUNCTION, ACTION_NONE, CBuiltins::GetInstance(), CLog::Log(), and LOGERROR.
Referenced by anonymous_namespace{GUIBuiltins.cpp}::Action(), JSONRPC::CInputOperations::ExecuteAction(), EVENTSERVER::CEventServer::ExecuteNextAction(), CApplication::ExecuteXBMCAction(), CGUIAudioManager::Load(), KODI::KEYMAP::CButtonTranslator::MapAction(), KODI::KEYMAP::CJoystickMapper::MapActions(), KODI::KEYMAP::CCustomControllerTranslator::TranslateString(), and KODI::KEYMAP::CTouchTranslator::TranslateTouchCommand().
The documentation for this class was generated from the following files:
ActionTranslator.h
ActionTranslator.cpp