Kodi Documentation: UPNP::CUPnP Class Reference
UPNP::CUPnP Class Reference
#include <UPnP.h>
Public Member Functions
CUPnP ()
~CUPnP ()
bool StartServer ()
void StopServer ()
void StartClient ()
void StopClient ()
bool IsClientStarted ()
void StartController ()
void StopController ()
bool IsControllerStarted ()
bool StartRenderer ()
void StopRenderer ()
void UpdateState ()
Static Public Member Functions
static CUPnP * GetInstance ()
static CUPnPServer * GetServer ()
static void ReleaseInstance (bool bWait)
static bool IsInstantiated ()
static bool MarkWatched (const CFileItem &item, const bool watched)
static bool SaveFileState (const CFileItem &item, const CBookmark &bookmark, const bool updatePlayCount)
static bool UpdateItem (const std::string &path, const CFileItem &item)
static void RegisterUserdata (void *ptr)
static void UnregisterUserdata (void *ptr)
Public Attributes
PLT_SyncMediaBrowser * m_MediaBrowser
PLT_MediaController * m_MediaController
Private Member Functions
CUPnP (const CUPnP &)=delete
CUPnP & operator= (const CUPnP &)=delete
void CreateControlPoint ()
void DestroyControlPoint ()
CUPnPRenderer * CreateRenderer (int port=0)
CUPnPServer * CreateServer (int port=0)
Private Attributes
CCriticalSection m_lockMediaBrowser
std::string m_IP
PLT_UPnP * m_UPnP
NPT_LogHandler * m_LogHandler
CDeviceHostReferenceHolder * m_ServerHolder
CRendererReferenceHolder * m_RendererHolder
CCtrlPointReferenceHolder * m_CtrlPointHolder
Static Private Attributes
static CUPnP * upnp = NULL
Constructor & Destructor Documentation
CUPnP() [1/2]
UPNP::CUPnP::CUPnP ()
References CNetworkInterface::GetCurrentIPAddress(), CNetworkBase::GetFirstConnectedInterface(), CServiceBroker::GetNetwork(), m_IP, m_LogHandler, m_UPnP, and UPnPLogger().
Referenced by GetInstance().
~CUPnP()
UPNP::CUPnP::~CUPnP ()
References m_CtrlPointHolder, m_LogHandler, m_RendererHolder, m_ServerHolder, m_UPnP, StopClient(), StopController(), and StopServer().
CUPnP() [2/2]
UPNP::CUPnP::CUPnP (const CUPnP &) private delete
Member Function Documentation
CreateControlPoint()
void UPNP::CUPnP::CreateControlPoint () private
References UPNP::CCtrlPointReferenceHolder::m_CtrlPoint, m_CtrlPointHolder, and m_UPnP.
Referenced by StartClient(), and StartController().
CreateRenderer()
CUPnPRenderer * UPNP::CUPnP::CreateRenderer (int port = 0) private
References CSysInfo::GetDeviceName(), CUPnPSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CSysInfo::GetVersion(), m_IP, and CSettings::SETTING_SERVICES_WEBSERVERPORT.
Referenced by StartRenderer().
CreateServer()
CUPnPServer * UPNP::CUPnP::CreateServer (int port = 0) private
References CSysInfo::GetDeviceName(), CUPnPSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CSysInfo::GetVersion(), m_IP, and CSettings::SETTING_SERVICES_WEBSERVERPORT.
Referenced by StartServer().
DestroyControlPoint()
void UPNP::CUPnP::DestroyControlPoint () private
References UPNP::CCtrlPointReferenceHolder::m_CtrlPoint, m_CtrlPointHolder, and m_UPnP.
Referenced by StopClient(), and StopController().
GetInstance()
CUPnP * UPNP::CUPnP::GetInstance () static
References CUPnP(), and upnp.
Referenced by AddMatchingUPnPServers(), UPNP::CUPnPPlayer::CUPnPPlayer(), XFILE::CUPnPDirectory::GetDirectory(), XFILE::CUPnPDirectory::GetFriendlyName(), XFILE::CUPnPDirectory::GetResource(), LookupUPnPHost(), and CApplication::ProcessSlow().
GetServer()
CUPnPServer * UPNP::CUPnP::GetServer () static
References UPNP::CDeviceHostReferenceHolder::m_Device, m_ServerHolder, and upnp.
Referenced by UPNP::CUPnPPlayer::PlayFile(), and UPNP::CUPnPPlayer::QueueNextFile().
IsClientStarted()
bool UPNP::CUPnP::IsClientStarted () inline
References m_MediaBrowser.
Referenced by XFILE::FindDeviceWait(), LookupUPnPHost(), and StopController().
IsControllerStarted()
bool UPNP::CUPnP::IsControllerStarted () inline
References m_MediaController.
Referenced by StopClient().
IsInstantiated()
static bool UPNP::CUPnP::IsInstantiated () inline static
References upnp.
Referenced by CApplication::ProcessSlow().
MarkWatched()
bool UPNP::CUPnP::MarkWatched (const CFileItem & item, const bool watched) static
References m_MediaBrowser, UPNP::CMediaBrowser::MarkWatched(), and upnp.
Referenced by CVideoLibraryMarkWatchedJob::Work().
operator=()
CUPnP & UPNP::CUPnP::operator= (const CUPnP &) private delete
RegisterUserdata()
void UPNP::CUPnP::RegisterUserdata (void * ptr) static
References UPNP::g_UserData, and UPNP::g_UserDataLock.
Referenced by UPNP::CUPnPPlayer::CUPnPPlayer().
ReleaseInstance()
void UPNP::CUPnP::ReleaseInstance (bool bWait) static
References upnp.
SaveFileState()
bool UPNP::CUPnP::SaveFileState (const CFileItem & item, const CBookmark & bookmark, const bool updatePlayCount) static
References m_MediaBrowser, UPNP::CMediaBrowser::SaveFileState(), and upnp.
Referenced by CSaveFileState::DoWork(), and CVideoLibraryResetResumePointJob::Work().
StartClient()
void UPNP::CUPnP::StartClient ()
References CreateControlPoint(), UPNP::CCtrlPointReferenceHolder::m_CtrlPoint, m_CtrlPointHolder, m_lockMediaBrowser, and m_MediaBrowser.
Referenced by XFILE::FindDeviceWait(), XFILE::CUPnPDirectory::GetDirectory(), and LookupUPnPHost().
StartController()
void UPNP::CUPnP::StartController ()
References CreateControlPoint(), UPNP::CCtrlPointReferenceHolder::m_CtrlPoint, m_CtrlPointHolder, and m_MediaController.
StartRenderer()
bool UPNP::CUPnP::StartRenderer ()
References URIUtils::AddFileToFolder(), CreateRenderer(), CUPnPSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CUPnPSettings::Load(), UPNP::CRendererReferenceHolder::m_Device, m_RendererHolder, m_UPnP, CUPnPSettings::Save(), CUPnPSettings::SetRendererPort(), and CUPnPSettings::SetRendererUUID().
StartServer()
bool UPNP::CUPnP::StartServer ()
References URIUtils::AddFileToFolder(), CreateServer(), CUPnPSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CUPnPSettings::Load(), UPNP::CDeviceHostReferenceHolder::m_Device, UPNP::CUPnPServer::m_MaxReturnedItems, m_ServerHolder, m_UPnP, CUPnPSettings::Save(), CUPnPSettings::SetMaximumReturnedItems(), CUPnPSettings::SetServerPort(), CUPnPSettings::SetServerUUID(), UPNP_DEFAULT_MAX_RETURNED_ITEMS, and UPNP_DEFAULT_MIN_RETURNED_ITEMS.
StopClient()
void UPNP::CUPnP::StopClient ()
References DestroyControlPoint(), IsControllerStarted(), m_lockMediaBrowser, and m_MediaBrowser.
Referenced by ~CUPnP().
StopController()
void UPNP::CUPnP::StopController ()
References DestroyControlPoint(), IsClientStarted(), and m_MediaController.
Referenced by ~CUPnP().
StopRenderer()
void UPNP::CUPnP::StopRenderer ()
References UPNP::CRendererReferenceHolder::m_Device, m_RendererHolder, and m_UPnP.
StopServer()
void UPNP::CUPnP::StopServer ()
References UPNP::CDeviceHostReferenceHolder::m_Device, m_ServerHolder, and m_UPnP.
Referenced by ~CUPnP().
UnregisterUserdata()
void UPNP::CUPnP::UnregisterUserdata (void * ptr) static
References UPNP::g_UserData, and UPNP::g_UserDataLock.
Referenced by UPNP::CUPnPPlayer::~CUPnPPlayer().
UpdateItem()
bool UPNP::CUPnP::UpdateItem (const std::string & path, const CFileItem & item) static
References m_MediaBrowser, UPNP::CMediaBrowser::UpdateItem(), and upnp.
UpdateState()
void UPNP::CUPnP::UpdateState ()
References UPNP::CRendererReferenceHolder::m_Device, m_RendererHolder, and UpdateState().
Referenced by CApplication::ProcessSlow(), and UpdateState().
Member Data Documentation
m_CtrlPointHolder
CCtrlPointReferenceHolder* UPNP::CUPnP::m_CtrlPointHolder private
Referenced by CreateControlPoint(), DestroyControlPoint(), StartClient(), StartController(), and ~CUPnP().
m_IP
std::string UPNP::CUPnP::m_IP private
Referenced by CreateRenderer(), CreateServer(), and CUPnP().
m_lockMediaBrowser
CCriticalSection UPNP::CUPnP::m_lockMediaBrowser private
Referenced by StartClient(), and StopClient().
m_LogHandler
NPT_LogHandler* UPNP::CUPnP::m_LogHandler private
Referenced by CUPnP(), and ~CUPnP().
m_MediaBrowser
PLT_SyncMediaBrowser* UPNP::CUPnP::m_MediaBrowser
Referenced by AddMatchingUPnPServers(), XFILE::FindDeviceWait(), XFILE::CUPnPDirectory::GetDirectory(), XFILE::CUPnPDirectory::GetResource(), IsClientStarted(), LookupUPnPHost(), MarkWatched(), SaveFileState(), StartClient(), StopClient(), and UpdateItem().
m_MediaController
PLT_MediaController* UPNP::CUPnP::m_MediaController
Referenced by UPNP::CUPnPPlayer::CUPnPPlayer(), IsControllerStarted(), StartController(), and StopController().
m_RendererHolder
CRendererReferenceHolder* UPNP::CUPnP::m_RendererHolder private
Referenced by StartRenderer(), StopRenderer(), UpdateState(), and ~CUPnP().
m_ServerHolder
CDeviceHostReferenceHolder* UPNP::CUPnP::m_ServerHolder private
Referenced by GetServer(), StartServer(), StopServer(), and ~CUPnP().
m_UPnP
PLT_UPnP* UPNP::CUPnP::m_UPnP private
Referenced by CreateControlPoint(), CUPnP(), DestroyControlPoint(), StartRenderer(), StartServer(), StopRenderer(), StopServer(), and ~CUPnP().
upnp
CUPnP * UPNP::CUPnP::upnp = NULL static private
Referenced by GetInstance(), GetServer(), IsInstantiated(), MarkWatched(), ReleaseInstance(), SaveFileState(), and UpdateItem().
The documentation for this class was generated from the following files:
UPnP.h
UPnP.cpp