Kodi Documentation: CMatrixGL Class Reference
CMatrixGL Class Reference
#include <MatrixGL.h>
Public Member Functions
CMatrixGL ()=default
constexpr CMatrixGL (GLfloat x0, GLfloat x1, GLfloat x2, GLfloat x3, GLfloat x4, GLfloat x5, GLfloat x6, GLfloat x7, GLfloat x8, GLfloat x9, GLfloat x10, GLfloat x11, GLfloat x12, GLfloat x13, GLfloat x14, GLfloat x15)
CMatrixGL (const TransformMatrix &src) noexcept
operator const float * () const
void LoadIdentity ()
void Ortho (GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f)
void Ortho2D (GLfloat l, GLfloat r, GLfloat b, GLfloat t)
void Frustum (GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f)
void Translatef (GLfloat x, GLfloat y, GLfloat z)
void Scalef (GLfloat x, GLfloat y, GLfloat z)
void Rotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
void MultMatrixf (const CMatrixGL &matrix) noexcept
void LookAt (GLfloat eyex, GLfloat eyey, GLfloat eyez, GLfloat centerx, GLfloat centery, GLfloat centerz, GLfloat upx, GLfloat upy, GLfloat upz)
Static Public Member Functions
static bool Project (GLfloat objx, GLfloat objy, GLfloat objz, const GLfloat modelMatrix[16], const GLfloat projMatrix[16], const GLint viewport[4], GLfloat *winx, GLfloat *winy, GLfloat *winz)
Private Attributes
GLfloat m_pMatrix [16]
Constructor & Destructor Documentation
CMatrixGL() [1/3]
CMatrixGL::CMatrixGL () default
CMatrixGL() [2/3]
constexpr CMatrixGL::CMatrixGL (GLfloat x0, GLfloat x1, GLfloat x2, GLfloat x3, GLfloat x4, GLfloat x5, GLfloat x6, GLfloat x7, GLfloat x8, GLfloat x9, GLfloat x10, GLfloat x11, GLfloat x12, GLfloat x13, GLfloat x14, GLfloat x15) inline constexpr
CMatrixGL() [3/3]
CMatrixGL::CMatrixGL (const TransformMatrix & src) noexcept
Member Function Documentation
Frustum()
void CMatrixGL::Frustum (GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f)
References f, MultMatrixf(), and t.
Referenced by CRenderSystemGL::SetCameraPosition(), and CRenderSystemGLES::SetCameraPosition().
LoadIdentity()
void CMatrixGL::LoadIdentity ()
References m_pMatrix.
Referenced by CLinuxRendererGLES::RenderToFBO(), CLinuxRendererGL::RenderToFBO(), CRenderSystemGL::ResetRenderSystem(), CRenderSystemGLES::ResetRenderSystem(), CRenderSystemGL::SetCameraPosition(), and CRenderSystemGLES::SetCameraPosition().
LookAt()
void CMatrixGL::LookAt (GLfloat eyex, GLfloat eyey, GLfloat eyez, GLfloat centerx, GLfloat centery, GLfloat centerz, GLfloat upx, GLfloat upy, GLfloat upz)
References MultMatrixf(), and Translatef().
Referenced by CRenderSystemGL::SetCameraPosition(), and CRenderSystemGLES::SetCameraPosition().
MultMatrixf()
void CMatrixGL::MultMatrixf (const CMatrixGL & matrix) noexcept
References CPU_FEATURE_NEON, f, CServiceBroker::GetCPUInfo(), and Matrix4Mul().
Referenced by Frustum(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), LookAt(), Ortho(), Ortho2D(), OVERLAY::COverlayGlyphGL::Render(), OVERLAY::COverlayGlyphGLES::Render(), Rotatef(), Scalef(), and Translatef().
operator const float *()
CMatrixGL::operator const float * () const inline
References m_pMatrix.
Ortho()
void CMatrixGL::Ortho (GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f)
References f, MultMatrixf(), and t.
Referenced by CRenderSystemGL::ResetRenderSystem(), and CRenderSystemGLES::ResetRenderSystem().
Ortho2D()
void CMatrixGL::Ortho2D (GLfloat l, GLfloat r, GLfloat b, GLfloat t)
References MultMatrixf(), and t.
Referenced by CLinuxRendererGLES::RenderToFBO(), and CLinuxRendererGL::RenderToFBO().
Project()
bool CMatrixGL::Project (GLfloat objx, GLfloat objy, GLfloat objz, const GLfloat modelMatrix[16], const GLfloat projMatrix[16], const GLint viewport[4], GLfloat * winx, GLfloat * winy, GLfloat * winz) static
References __gluMultMatrixVecf().
Referenced by CRenderSystemGL::Project(), and CRenderSystemGLES::Project().
Rotatef()
void CMatrixGL::Rotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
References f, and MultMatrixf().
Scalef()
void CMatrixGL::Scalef (GLfloat x, GLfloat y, GLfloat z)
References MultMatrixf().
Referenced by CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), OVERLAY::COverlayGlyphGL::Render(), OVERLAY::COverlayGlyphGLES::Render(), CLinuxRendererGL::RenderCapture(), and CLinuxRendererGLES::RenderCapture().
Translatef()
void CMatrixGL::Translatef (GLfloat x, GLfloat y, GLfloat z)
References MultMatrixf().
Referenced by CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), LookAt(), OVERLAY::COverlayGlyphGL::Render(), OVERLAY::COverlayGlyphGLES::Render(), CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), CRenderSystemGL::SetCameraPosition(), and CRenderSystemGLES::SetCameraPosition().
Member Data Documentation
m_pMatrix
GLfloat CMatrixGL::m_pMatrix[16] private
Referenced by LoadIdentity(), and operator const float *().
The documentation for this class was generated from the following files:
MatrixGL.h
MatrixGL.cpp