Kodi Documentation: CPictureInfoTag Class Reference
CPictureInfoTag Class Reference
#include <PictureInfoTag.h>
Public Member Functions
CPictureInfoTag ()
virtual ~CPictureInfoTag ()=default
void Reset ()
void Archive (CArchive &ar) override
void Serialize (CVariant &value) const override
void ToSortable (SortItem &sortable, Field field) const override
const std::string GetInfo (int info) const
bool Loaded () const
bool Load (const std::string &path)
void SetInfo (const std::string &key, const std::string &value)
const CDateTime & GetDateTimeTaken () const
Private Member Functions
void ConvertDateTime ()
Static Private Member Functions
static int TranslateString (const std::string &info)
Private Attributes
ImageMetadata m_imageMetadata
bool m_isLoaded
bool m_isInfoSetExternally
CDateTime m_dateTimeTaken
Friends
class KODI::ADDONS::CImageDecoder
Additional Inherited Members
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Protected Member Functions inherited from ISortable
~ISortable ()=default
Constructor & Destructor Documentation
CPictureInfoTag()
CPictureInfoTag::CPictureInfoTag () inline
References Reset().
~CPictureInfoTag()
virtual CPictureInfoTag::~CPictureInfoTag () virtual default
Member Function Documentation
Archive()
void CPictureInfoTag::Archive (CArchive & ar) override virtual
Implements IArchivable.
References ExifInfo::ApertureFNumber, IPTCInfo::Author, IPTCInfo::Byline, IPTCInfo::BylineTitle, ExifInfo::CameraMake, ExifInfo::CameraModel, IPTCInfo::Caption, IPTCInfo::Category, ExifInfo::CCDWidth, IPTCInfo::City, ExifInfo::Comments, IPTCInfo::CopyrightNotice, IPTCInfo::Country, IPTCInfo::CountryCode, IPTCInfo::Credit, IPTCInfo::Date, ExifInfo::DateTime, ExifInfo::Description, ExifInfo::DigitalZoomRatio, ExifInfo::Distance, ImageMetadata::encodingProcess, ImageMetadata::exifInfo, ExifInfo::ExposureBias, ExifInfo::ExposureMode, ExifInfo::ExposureProgram, ExifInfo::ExposureTime, ExifInfo::FlashUsed, ExifInfo::FocalLength, ExifInfo::FocalLength35mmEquiv, ExifInfo::GpsAlt, ExifInfo::GpsInfoPresent, ExifInfo::GpsLat, ExifInfo::GpsLong, IPTCInfo::Headline, ImageMetadata::height, IPTCInfo::ImageType, ImageMetadata::iptcInfo, ImageMetadata::isColor, ExifInfo::ISOequivalent, CArchive::IsStoring(), IPTCInfo::Keywords, ExifInfo::LightSource, m_dateTimeTaken, m_imageMetadata, m_isInfoSetExternally, m_isLoaded, ExifInfo::MeteringMode, IPTCInfo::ObjectName, ExifInfo::Orientation, IPTCInfo::ReferenceService, IPTCInfo::Source, IPTCInfo::SpecialInstructions, IPTCInfo::State, IPTCInfo::SubLocation, IPTCInfo::SupplementalCategories, IPTCInfo::TimeCreated, IPTCInfo::TransmissionReference, IPTCInfo::Urgency, ExifInfo::Whitebalance, and ImageMetadata::width.
ConvertDateTime()
void CPictureInfoTag::ConvertDateTime () private
References ExifInfo::DateTime, day, ImageMetadata::exifInfo, m_dateTimeTaken, m_imageMetadata, min, and CDateTime::SetDateTime().
Referenced by Load(), and SetInfo().
GetDateTimeTaken()
const CDateTime & CPictureInfoTag::GetDateTimeTaken () const
GetDateTimeTaken() – Returns the EXIF DateTimeOriginal for current picture
The exif library returns DateTimeOriginal if available else the other DateTime tags.
References m_dateTimeTaken.
Referenced by CLabelFormatter::GetMaskContent().
GetInfo()
const std::string CPictureInfoTag::GetInfo (int info) const
References ExifInfo::ApertureFNumber, IPTCInfo::Author, IPTCInfo::Byline, IPTCInfo::BylineTitle, ExifInfo::CameraMake, ExifInfo::CameraModel, IPTCInfo::Caption, IPTCInfo::Category, ExifInfo::CCDWidth, IPTCInfo::City, ExifInfo::Comments, IPTCInfo::CopyrightNotice, IPTCInfo::Country, IPTCInfo::CountryCode, IPTCInfo::Credit, IPTCInfo::Date, ExifInfo::Description, ExifInfo::DigitalZoomRatio, ExifInfo::Distance, ImageMetadata::encodingProcess, ImageMetadata::exifInfo, ExifInfo::ExposureBias, ExifInfo::ExposureMode, ExifInfo::ExposureProgram, ExifInfo::ExposureTime, ImageMetadata::fileComment, ExifInfo::FlashUsed, ExifInfo::FocalLength, ExifInfo::FocalLength35mmEquiv, CDateTime::GetAsLocalizedDate(), CDateTime::GetAsLocalizedDateTime(), ExifInfo::GpsAlt, ExifInfo::GpsLat, ExifInfo::GpsLong, IPTCInfo::Headline, ImageMetadata::height, IPTCInfo::ImageType, ImageMetadata::iptcInfo, ImageMetadata::isColor, ExifInfo::ISOequivalent, CDateTime::IsValid(), IPTCInfo::Keywords, ExifInfo::LightSource, m_dateTimeTaken, m_imageMetadata, m_isInfoSetExternally, m_isLoaded, ExifInfo::MeteringMode, IPTCInfo::ObjectName, ExifInfo::Orientation, IPTCInfo::ReferenceService, SLIDESHOW_COLOUR, SLIDESHOW_COMMENT, SLIDESHOW_EXIF_APERTURE, SLIDESHOW_EXIF_CAMERA_MAKE, SLIDESHOW_EXIF_CAMERA_MODEL, SLIDESHOW_EXIF_CCD_WIDTH, SLIDESHOW_EXIF_COMMENT, SLIDESHOW_EXIF_DATE, SLIDESHOW_EXIF_DATE_TIME, SLIDESHOW_EXIF_DESCRIPTION, SLIDESHOW_EXIF_DIGITAL_ZOOM, SLIDESHOW_EXIF_EXPOSURE, SLIDESHOW_EXIF_EXPOSURE_BIAS, SLIDESHOW_EXIF_EXPOSURE_MODE, SLIDESHOW_EXIF_EXPOSURE_TIME, SLIDESHOW_EXIF_FLASH_USED, SLIDESHOW_EXIF_FOCAL_LENGTH, SLIDESHOW_EXIF_FOCUS_DIST, SLIDESHOW_EXIF_GPS_ALTITUDE, SLIDESHOW_EXIF_GPS_LATITUDE, SLIDESHOW_EXIF_GPS_LONGITUDE, SLIDESHOW_EXIF_ISO_EQUIV, SLIDESHOW_EXIF_LIGHT_SOURCE, SLIDESHOW_EXIF_LONG_DATE, SLIDESHOW_EXIF_LONG_DATE_TIME, SLIDESHOW_EXIF_METERING_MODE, SLIDESHOW_EXIF_ORIENTATION, SLIDESHOW_EXIF_WHITE_BALANCE, SLIDESHOW_EXIF_XPCOMMENT, SLIDESHOW_IPTC_AUTHOR, SLIDESHOW_IPTC_BYLINE, SLIDESHOW_IPTC_BYLINE_TITLE, SLIDESHOW_IPTC_CAPTION, SLIDESHOW_IPTC_CATEGORY, SLIDESHOW_IPTC_CITY, SLIDESHOW_IPTC_COPYRIGHT_NOTICE, SLIDESHOW_IPTC_COUNTRY, SLIDESHOW_IPTC_COUNTRY_CODE, SLIDESHOW_IPTC_CREDIT, SLIDESHOW_IPTC_DATE, SLIDESHOW_IPTC_HEADLINE, SLIDESHOW_IPTC_IMAGETYPE, SLIDESHOW_IPTC_KEYWORDS, SLIDESHOW_IPTC_OBJECT_NAME, SLIDESHOW_IPTC_REF_SERVICE, SLIDESHOW_IPTC_SOURCE, SLIDESHOW_IPTC_SPEC_INSTR, SLIDESHOW_IPTC_STATE, SLIDESHOW_IPTC_SUBLOCATION, SLIDESHOW_IPTC_SUP_CATEGORIES, SLIDESHOW_IPTC_TIMECREATED, SLIDESHOW_IPTC_TX_REFERENCE, SLIDESHOW_IPTC_URGENCY, SLIDESHOW_PROCESS, SLIDESHOW_RESOLUTION, IPTCInfo::Source, IPTCInfo::SpecialInstructions, IPTCInfo::State, IPTCInfo::SubLocation, IPTCInfo::SupplementalCategories, IPTCInfo::TimeCreated, IPTCInfo::TransmissionReference, IPTCInfo::Urgency, value, ExifInfo::Whitebalance, ImageMetadata::width, and ExifInfo::XPComment.
Referenced by KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), and XBMCAddon::xbmc::InfoTagPicture::getResolution().
Load()
bool CPictureInfoTag::Load (const std::string & path)
References ConvertDateTime(), CImageMetadataParser::ExtractMetadata(), URIUtils::GetExtension(), KODI::ADDONS::CExtsMimeSupportList::GetExtensionSupportedAddonInfos(), CServiceBroker::GetExtsMimeSupportList(), ADDON::IMAGEDECODER, CServiceBroker::IsAddonInterfaceUp(), m_imageMetadata, and m_isLoaded.
Referenced by JSONRPC::CPlaylistOperations::Add(), JSONRPC::CFileItemHandler::FillFileItemList(), CPictureInfoLoader::LoadItemLookup(), and KODI::GUILIB::GUIINFO::CPicturesGUIInfo::SetCurrentSlide().
Loaded()
bool CPictureInfoTag::Loaded () const inline
References m_isLoaded.
Reset()
void CPictureInfoTag::Reset ()
References m_dateTimeTaken, m_imageMetadata, m_isInfoSetExternally, m_isLoaded, and CDateTime::Reset().
Referenced by CPictureInfoTag().
Serialize()
void CPictureInfoTag::Serialize (CVariant & value) const override virtual
Implements ISerializable.
References ExifInfo::ApertureFNumber, IPTCInfo::Author, IPTCInfo::Byline, IPTCInfo::BylineTitle, ExifInfo::CameraMake, ExifInfo::CameraModel, IPTCInfo::Caption, IPTCInfo::Category, ExifInfo::CCDWidth, IPTCInfo::City, ExifInfo::Comments, IPTCInfo::CopyrightNotice, IPTCInfo::Country, IPTCInfo::CountryCode, IPTCInfo::Credit, IPTCInfo::Date, ExifInfo::DateTime, ExifInfo::Description, ExifInfo::DigitalZoomRatio, ExifInfo::Distance, ImageMetadata::encodingProcess, ImageMetadata::exifInfo, ExifInfo::ExposureBias, ExifInfo::ExposureMode, ExifInfo::ExposureProgram, ExifInfo::ExposureTime, ExifInfo::FlashUsed, ExifInfo::FocalLength, ExifInfo::FocalLength35mmEquiv, ExifInfo::GpsAlt, ExifInfo::GpsInfoPresent, ExifInfo::GpsLat, ExifInfo::GpsLong, IPTCInfo::Headline, ImageMetadata::height, IPTCInfo::ImageType, ImageMetadata::iptcInfo, ImageMetadata::isColor, ExifInfo::ISOequivalent, IPTCInfo::Keywords, ExifInfo::LightSource, m_imageMetadata, ExifInfo::MeteringMode, IPTCInfo::ObjectName, ExifInfo::Orientation, IPTCInfo::ReferenceService, IPTCInfo::Source, IPTCInfo::SpecialInstructions, IPTCInfo::State, IPTCInfo::SubLocation, IPTCInfo::SupplementalCategories, IPTCInfo::TimeCreated, IPTCInfo::TransmissionReference, IPTCInfo::Urgency, value, ExifInfo::Whitebalance, and ImageMetadata::width.
SetInfo()
void CPictureInfoTag::SetInfo (const std::string & key, const std::string & value)
References ConvertDateTime(), ExifInfo::DateTime, ImageMetadata::exifInfo, ImageMetadata::height, m_imageMetadata, m_isInfoSetExternally, SLIDESHOW_EXIF_DATE_TIME, SLIDESHOW_RESOLUTION, TranslateString(), value, and ImageMetadata::width.
Referenced by AudioClassifyTest::AudioClassifyTest(), XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw(), XBMCAddon::xbmc::InfoTagPicture::setResolutionRaw(), and VideoClassifyTest::VideoClassifyTest().
ToSortable()
void CPictureInfoTag::ToSortable (SortItem & sortable, Field field) const override virtual
Implements ISortable.
References FieldDateTaken, CDateTime::GetAsDBDateTime(), CDateTime::IsValid(), and m_dateTimeTaken.
Referenced by CFileItem::ToSortable().
TranslateString()
int CPictureInfoTag::TranslateString (const std::string & info) static private
References SLIDESHOW_COLOUR, SLIDESHOW_COMMENT, SLIDESHOW_EXIF_APERTURE, SLIDESHOW_EXIF_CAMERA_MAKE, SLIDESHOW_EXIF_CAMERA_MODEL, SLIDESHOW_EXIF_CCD_WIDTH, SLIDESHOW_EXIF_COMMENT, SLIDESHOW_EXIF_DATE, SLIDESHOW_EXIF_DATE_TIME, SLIDESHOW_EXIF_DESCRIPTION, SLIDESHOW_EXIF_DIGITAL_ZOOM, SLIDESHOW_EXIF_EXPOSURE, SLIDESHOW_EXIF_EXPOSURE_BIAS, SLIDESHOW_EXIF_EXPOSURE_MODE, SLIDESHOW_EXIF_EXPOSURE_TIME, SLIDESHOW_EXIF_FLASH_USED, SLIDESHOW_EXIF_FOCAL_LENGTH, SLIDESHOW_EXIF_FOCUS_DIST, SLIDESHOW_EXIF_GPS_ALTITUDE, SLIDESHOW_EXIF_GPS_LATITUDE, SLIDESHOW_EXIF_GPS_LONGITUDE, SLIDESHOW_EXIF_ISO_EQUIV, SLIDESHOW_EXIF_LIGHT_SOURCE, SLIDESHOW_EXIF_LONG_DATE, SLIDESHOW_EXIF_LONG_DATE_TIME, SLIDESHOW_EXIF_METERING_MODE, SLIDESHOW_EXIF_ORIENTATION, SLIDESHOW_EXIF_WHITE_BALANCE, SLIDESHOW_FILE_DATE, SLIDESHOW_FILE_NAME, SLIDESHOW_FILE_PATH, SLIDESHOW_FILE_SIZE, SLIDESHOW_INDEX, SLIDESHOW_IPTC_AUTHOR, SLIDESHOW_IPTC_BYLINE, SLIDESHOW_IPTC_BYLINE_TITLE, SLIDESHOW_IPTC_CAPTION, SLIDESHOW_IPTC_CATEGORY, SLIDESHOW_IPTC_CITY, SLIDESHOW_IPTC_COPYRIGHT_NOTICE, SLIDESHOW_IPTC_COUNTRY, SLIDESHOW_IPTC_COUNTRY_CODE, SLIDESHOW_IPTC_CREDIT, SLIDESHOW_IPTC_DATE, SLIDESHOW_IPTC_HEADLINE, SLIDESHOW_IPTC_IMAGETYPE, SLIDESHOW_IPTC_KEYWORDS, SLIDESHOW_IPTC_OBJECT_NAME, SLIDESHOW_IPTC_REF_SERVICE, SLIDESHOW_IPTC_SOURCE, SLIDESHOW_IPTC_SPEC_INSTR, SLIDESHOW_IPTC_STATE, SLIDESHOW_IPTC_SUBLOCATION, SLIDESHOW_IPTC_SUP_CATEGORIES, SLIDESHOW_IPTC_TIMECREATED, SLIDESHOW_IPTC_TX_REFERENCE, SLIDESHOW_IPTC_URGENCY, SLIDESHOW_PROCESS, and SLIDESHOW_RESOLUTION.
Referenced by SetInfo().
Friends And Related Symbol Documentation
KODI::ADDONS::CImageDecoder
friend class KODI::ADDONS::CImageDecoder friend
Member Data Documentation
m_dateTimeTaken
CDateTime CPictureInfoTag::m_dateTimeTaken private
Referenced by Archive(), ConvertDateTime(), GetDateTimeTaken(), GetInfo(), Reset(), and ToSortable().
m_imageMetadata
ImageMetadata CPictureInfoTag::m_imageMetadata private
Referenced by Archive(), ConvertDateTime(), GetInfo(), Load(), Reset(), Serialize(), and SetInfo().
m_isInfoSetExternally
bool CPictureInfoTag::m_isInfoSetExternally private
Referenced by Archive(), GetInfo(), Reset(), and SetInfo().
m_isLoaded
bool CPictureInfoTag::m_isLoaded private
Referenced by Archive(), GetInfo(), Load(), Loaded(), and Reset().
The documentation for this class was generated from the following files:
PictureInfoTag.h
PictureInfoTag.cpp