Kodi Documentation: VAAPI::CVAAPIContext Class Reference
VAAPI::CVAAPIContext Class Reference
#include <VAAPI.h>
Public Member Functions
void Release (CDecoder *decoder)
VADisplay GetDisplay ()
bool SupportsProfile (VAProfile profile)
VAConfigAttrib GetAttrib (VAProfile profile)
VAConfigID CreateConfig (VAProfile profile, VAConfigAttrib attrib)
Static Public Member Functions
static bool EnsureContext (CVAAPIContext **ctx, CDecoder *decoder)
static void FFReleaseBuffer (void *opaque, uint8_t *data)
Private Member Functions
CVAAPIContext ()
void Close ()
void SetVaDisplayForSystem ()
bool CreateContext ()
void DestroyContext ()
void QueryCaps ()
bool CheckSuccess (VAStatus status, const std::string &function)
bool IsValidDecoder (CDecoder *decoder)
void SetValidDRMVaDisplayFromRenderNode ()
Private Attributes
VADisplay m_display = NULL
int m_refCount
int m_profileCount
VAProfile * m_profiles
std::vector< CDecoder * > m_decoders
int m_renderNodeFD {-1}
Static Private Attributes
static CVAAPIContext * m_context = 0
static CCriticalSection m_section
Constructor & Destructor Documentation
CVAAPIContext()
CVAAPIContext::CVAAPIContext () private
References m_context, m_profiles, and m_refCount.
Referenced by EnsureContext().
Member Function Documentation
CheckSuccess()
bool CVAAPIContext::CheckSuccess (VAStatus status, const std::string & function) private
References CLog::Log(), and LOGERROR.
Referenced by CreateConfig(), CreateContext(), DestroyContext(), GetAttrib(), and QueryCaps().
Close()
void CVAAPIContext::Close () private
References DestroyContext(), CLog::Log(), LOGINFO, and m_renderNodeFD.
Referenced by Release().
CreateConfig()
VAConfigID CVAAPIContext::CreateConfig (VAProfile profile, VAConfigAttrib attrib)
References CheckSuccess(), m_display, and m_section.
Referenced by VAAPI::CDecoder::ConfigVAAPI().
CreateContext()
bool CVAAPIContext::CreateContext () private
References CheckSuccess(), CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, m_display, m_profileCount, QueryCaps(), SetVaDisplayForSystem(), VAAPI::VaErrorCallback(), and VAAPI::VaInfoCallback().
Referenced by EnsureContext().
DestroyContext()
void CVAAPIContext::DestroyContext () private
References CheckSuccess(), m_display, and m_profiles.
Referenced by Close().
EnsureContext()
bool CVAAPIContext::EnsureContext (CVAAPIContext ** ctx, CDecoder * decoder) static
References CreateContext(), CVAAPIContext(), CServiceBroker::GetWinSystem(), IsValidDecoder(), m_context, m_decoders, m_refCount, and m_section.
Referenced by VAAPI::CDecoder::Check(), VAAPI::CDecoder::Open(), and VAAPI::CDecoder::Register().
FFReleaseBuffer()
void CVAAPIContext::FFReleaseBuffer (void * opaque, uint8_t * data) static
References data(), VAAPI::CDecoder::FFReleaseBuffer(), IsValidDecoder(), and m_context.
Referenced by VAAPI::CDecoder::FFGetBuffer().
GetAttrib()
VAConfigAttrib CVAAPIContext::GetAttrib (VAProfile profile)
References CheckSuccess(), m_display, and m_section.
Referenced by VAAPI::CDecoder::ConfigVAAPI(), and VAAPI::CDecoder::Open().
GetDisplay()
VADisplay CVAAPIContext::GetDisplay ()
References m_display.
Referenced by VAAPI::CDecoder::ConfigVAAPI(), and VAAPI::CDecoder::Open().
IsValidDecoder()
bool CVAAPIContext::IsValidDecoder (CDecoder * decoder) private
References m_decoders.
Referenced by EnsureContext(), and FFReleaseBuffer().
QueryCaps()
void CVAAPIContext::QueryCaps () private
References CheckSuccess(), CLog::Log(), LOGDEBUG, LOGVIDEO, m_display, m_profileCount, and m_profiles.
Referenced by CreateContext().
Release()
void CVAAPIContext::Release (CDecoder * decoder)
References Close(), m_context, m_decoders, m_refCount, and m_section.
Referenced by VAAPI::CDecoder::Check(), VAAPI::CDecoder::Close(), and VAAPI::CDecoder::Register().
SetVaDisplayForSystem()
void CVAAPIContext::SetVaDisplayForSystem () private
References VAAPI::IVaapiWinSystem::GetVADisplay(), m_display, VAAPI::CDecoder::m_pWinSystem, and SetValidDRMVaDisplayFromRenderNode().
Referenced by CreateContext().
SetValidDRMVaDisplayFromRenderNode()
void CVAAPIContext::SetValidDRMVaDisplayFromRenderNode () private
References CLog::Log(), LOGERROR, m_display, m_renderNodeFD, and name.
Referenced by SetVaDisplayForSystem().
SupportsProfile()
bool CVAAPIContext::SupportsProfile (VAProfile profile)
References m_profileCount, m_profiles, and m_section.
Referenced by VAAPI::CDecoder::Open().
Member Data Documentation
m_context
CVAAPIContext * CVAAPIContext::m_context = 0 static private
Referenced by CVAAPIContext(), EnsureContext(), FFReleaseBuffer(), and Release().
m_decoders
std::vector<CDecoder*> VAAPI::CVAAPIContext::m_decoders private
Referenced by EnsureContext(), IsValidDecoder(), and Release().
m_display
VADisplay VAAPI::CVAAPIContext::m_display = NULL private
Referenced by CreateConfig(), CreateContext(), DestroyContext(), GetAttrib(), GetDisplay(), QueryCaps(), SetVaDisplayForSystem(), and SetValidDRMVaDisplayFromRenderNode().
m_profileCount
int VAAPI::CVAAPIContext::m_profileCount private
Referenced by CreateContext(), QueryCaps(), and SupportsProfile().
m_profiles
VAProfile* VAAPI::CVAAPIContext::m_profiles private
Referenced by CVAAPIContext(), DestroyContext(), QueryCaps(), and SupportsProfile().
m_refCount
int VAAPI::CVAAPIContext::m_refCount private
Referenced by CVAAPIContext(), EnsureContext(), and Release().
m_renderNodeFD
int VAAPI::CVAAPIContext::m_renderNodeFD {-1} private
Referenced by Close(), and SetValidDRMVaDisplayFromRenderNode().
m_section
CCriticalSection CVAAPIContext::m_section static private
Referenced by CreateConfig(), EnsureContext(), GetAttrib(), Release(), and SupportsProfile().
The documentation for this class was generated from the following files:
VAAPI.h
VAAPI.cpp