Kodi Documentation: AddonToKodiFuncTable_kodi_audioengine Struct Reference
AddonToKodiFuncTable_kodi_audioengine Struct Reference
#include <audio_engine.h>
Public Attributes
AEStreamHandle *(* make_stream)(void *kodiBase, struct AUDIO_ENGINE_FORMAT *format, unsigned int options)
void(* free_stream)(void *kodiBase, AEStreamHandle *stream)
bool(* get_current_sink_format)(void *kodiBase, struct AUDIO_ENGINE_FORMAT *sink_format)
unsigned int(* aestream_get_space)(void *kodiBase, AEStreamHandle *handle)
unsigned int(* aestream_add_data)(void *kodiBase, AEStreamHandle *handle, uint8_t *const *data, unsigned int offset, unsigned int frames, double pts, bool hasDownmix, double centerMixLevel)
double(* aestream_get_delay)(void *kodiBase, AEStreamHandle *handle)
bool(* aestream_is_buffering)(void *kodiBase, AEStreamHandle *handle)
double(* aestream_get_cache_time)(void *kodiBase, AEStreamHandle *handle)
double(* aestream_get_cache_total)(void *kodiBase, AEStreamHandle *handle)
void(* aestream_pause)(void *kodiBase, AEStreamHandle *handle)
void(* aestream_resume)(void *kodiBase, AEStreamHandle *handle)
void(* aestream_drain)(void *kodiBase, AEStreamHandle *handle, bool wait)
bool(* aestream_is_draining)(void *kodiBase, AEStreamHandle *handle)
bool(* aestream_is_drained)(void *kodiBase, AEStreamHandle *handle)
void(* aestream_flush)(void *kodiBase, AEStreamHandle *handle)
float(* aestream_get_volume)(void *kodiBase, AEStreamHandle *handle)
void(* aestream_set_volume)(void *kodiBase, AEStreamHandle *handle, float volume)
float(* aestream_get_amplification)(void *kodiBase, AEStreamHandle *handle)
void(* aestream_set_amplification)(void *kodiBase, AEStreamHandle *handle, float amplify)
unsigned int(* aestream_get_frame_size)(void *kodiBase, AEStreamHandle *handle)
unsigned int(* aestream_get_channel_count)(void *kodiBase, AEStreamHandle *handle)
unsigned int(* aestream_get_sample_rate)(void *kodiBase, AEStreamHandle *handle)
enum AudioEngineDataFormat(* aestream_get_data_format)(void *kodiBase, AEStreamHandle *handle)
double(* aestream_get_resample_ratio)(void *kodiBase, AEStreamHandle *handle)
void(* aestream_set_resample_ratio)(void *kodiBase, AEStreamHandle *handle, double ratio)
Member Data Documentation
aestream_add_data
unsigned int(* AddonToKodiFuncTable_kodi_audioengine::aestream_add_data) (void *kodiBase, AEStreamHandle *handle, uint8_t *const *data, unsigned int offset, unsigned int frames, double pts, bool hasDownmix, double centerMixLevel)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_drain
void(* AddonToKodiFuncTable_kodi_audioengine::aestream_drain) (void *kodiBase, AEStreamHandle *handle, bool wait)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_flush
void(* AddonToKodiFuncTable_kodi_audioengine::aestream_flush) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_amplification
float(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_amplification) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_cache_time
double(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_cache_time) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_cache_total
double(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_cache_total) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_channel_count
unsigned int(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_channel_count) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_data_format
enum AudioEngineDataFormat(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_data_format) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_delay
double(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_delay) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_frame_size
unsigned int(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_frame_size) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_resample_ratio
double(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_resample_ratio) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_sample_rate
unsigned int(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_sample_rate) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_space
unsigned int(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_space) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_get_volume
float(* AddonToKodiFuncTable_kodi_audioengine::aestream_get_volume) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_is_buffering
bool(* AddonToKodiFuncTable_kodi_audioengine::aestream_is_buffering) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_is_drained
bool(* AddonToKodiFuncTable_kodi_audioengine::aestream_is_drained) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_is_draining
bool(* AddonToKodiFuncTable_kodi_audioengine::aestream_is_draining) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_pause
void(* AddonToKodiFuncTable_kodi_audioengine::aestream_pause) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_resume
void(* AddonToKodiFuncTable_kodi_audioengine::aestream_resume) (void *kodiBase, AEStreamHandle *handle)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_set_amplification
void(* AddonToKodiFuncTable_kodi_audioengine::aestream_set_amplification) (void *kodiBase, AEStreamHandle *handle, float amplify)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_set_resample_ratio
void(* AddonToKodiFuncTable_kodi_audioengine::aestream_set_resample_ratio) (void *kodiBase, AEStreamHandle *handle, double ratio)
Referenced by ADDON::Interface_AudioEngine::Init().
aestream_set_volume
void(* AddonToKodiFuncTable_kodi_audioengine::aestream_set_volume) (void *kodiBase, AEStreamHandle *handle, float volume)
Referenced by ADDON::Interface_AudioEngine::Init().
free_stream
void(* AddonToKodiFuncTable_kodi_audioengine::free_stream) (void *kodiBase, AEStreamHandle *stream)
Referenced by ADDON::Interface_AudioEngine::Init().
get_current_sink_format
bool(* AddonToKodiFuncTable_kodi_audioengine::get_current_sink_format) (void *kodiBase, struct AUDIO_ENGINE_FORMAT *sink_format)
Referenced by ADDON::Interface_AudioEngine::Init().
make_stream
AEStreamHandle *(* AddonToKodiFuncTable_kodi_audioengine::make_stream) (void *kodiBase, struct AUDIO_ENGINE_FORMAT *format, unsigned int options)
Referenced by ADDON::Interface_AudioEngine::Init().
The documentation for this struct was generated from the following file:
audio_engine.h