Kodi Documentation: CONTEXTMENU::CDisableAddon Struct Reference
CONTEXTMENU::CDisableAddon Struct Reference
#include <ContextMenus.h>
Public Member Functions
CDisableAddon ()
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Constructor & Destructor Documentation
CDisableAddon()
CONTEXTMENU::CDisableAddon::CDisableAddon () inline
Member Function Documentation
Execute()
bool CONTEXTMENU::CDisableAddon::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References ADDON::CAddonMgr::DisableAddon(), CServiceBroker::GetAddonMgr(), and ADDON::USER.
IsVisible()
bool CONTEXTMENU::CDisableAddon::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References ADDON::CAddonMgr::CanAddonBeDisabled(), CFileItem::GetAddonInfo(), CServiceBroker::GetAddonMgr(), CFileItem::HasAddonInfo(), and ADDON::CAddonMgr::IsAddonDisabled().
The documentation for this struct was generated from the following files:
addons/ContextMenus.h
addons/ContextMenus.cpp