Kodi Documentation: KODI::WINDOWING::GBM::CDRMCrtc Class Reference
KODI::WINDOWING::GBM::CDRMCrtc Class Reference
#include <DRMCrtc.h>
Classes
struct DrmModeCrtcDeleter
Public Member Functions
CDRMCrtc (int fd, uint32_t crtc)
CDRMCrtc (const CDRMCrtc &)=delete
CDRMCrtc & operator= (const CDRMCrtc &)=delete
~CDRMCrtc ()=default
uint32_t GetCrtcId () const
uint32_t GetBufferId () const
uint32_t GetX () const
uint32_t GetY () const
drmModeModeInfoPtr GetMode () const
bool GetModeValid () const
Public Member Functions inherited from KODI::WINDOWING::GBM::CDRMObject
CDRMObject (const CDRMObject &)=delete
CDRMObject & operator= (const CDRMObject &)=delete
virtual ~CDRMObject ()=default
std::string GetTypeName () const
std::string GetPropertyName (uint32_t propertyId) const
uint32_t GetId () const
uint32_t GetPropertyId (const std::string &name) const
std::optional< uint64_t > GetPropertyValue (std::string_view name, std::string_view valueName) const
bool SetProperty (const std::string &name, uint64_t value)
bool SupportsProperty (const std::string &name)
Private Attributes
std::unique_ptr< drmModeCrtc, DrmModeCrtcDeleter > m_crtc
Additional Inherited Members
Protected Member Functions inherited from KODI::WINDOWING::GBM::CDRMObject
CDRMObject (int fd)
bool GetProperties (uint32_t id, uint32_t type)
Protected Attributes inherited from KODI::WINDOWING::GBM::CDRMObject
std::unique_ptr< drmModeObjectProperties, DrmModeObjectPropertiesDeleter > m_props
std::vector< std::unique_ptr< drmModePropertyRes, DrmModePropertyResDeleter > > m_propsInfo
int m_fd {-1}
Constructor & Destructor Documentation
CDRMCrtc() [1/2]
CDRMCrtc::CDRMCrtc (int fd, uint32_t crtc) explicit
References KODI::WINDOWING::GBM::CDRMObject::GetProperties(), and m_crtc.
CDRMCrtc() [2/2]
KODI::WINDOWING::GBM::CDRMCrtc::CDRMCrtc (const CDRMCrtc &) delete
~CDRMCrtc()
KODI::WINDOWING::GBM::CDRMCrtc::~CDRMCrtc () default
Member Function Documentation
GetBufferId()
uint32_t KODI::WINDOWING::GBM::CDRMCrtc::GetBufferId () const inline
References m_crtc.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::RestoreOriginalMode().
GetCrtcId()
uint32_t KODI::WINDOWING::GBM::CDRMCrtc::GetCrtcId () const inline
References m_crtc.
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit(), KODI::WINDOWING::GBM::CDRMLegacy::QueueFlip(), KODI::WINDOWING::GBM::CDRMUtils::RestoreOriginalMode(), and KODI::WINDOWING::GBM::CDRMLegacy::SetVideoMode().
GetMode()
drmModeModeInfoPtr KODI::WINDOWING::GBM::CDRMCrtc::GetMode () const inline
References m_crtc.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::FindCrtc(), and KODI::WINDOWING::GBM::CDRMUtils::RestoreOriginalMode().
GetModeValid()
bool KODI::WINDOWING::GBM::CDRMCrtc::GetModeValid () const inline
References m_crtc.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::FindCrtc().
GetX()
uint32_t KODI::WINDOWING::GBM::CDRMCrtc::GetX () const inline
References m_crtc.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::RestoreOriginalMode().
GetY()
uint32_t KODI::WINDOWING::GBM::CDRMCrtc::GetY () const inline
References m_crtc.
Referenced by KODI::WINDOWING::GBM::CDRMUtils::RestoreOriginalMode().
operator=()
CDRMCrtc & KODI::WINDOWING::GBM::CDRMCrtc::operator= (const CDRMCrtc &) delete
Member Data Documentation
m_crtc
std::unique_ptr<drmModeCrtc, DrmModeCrtcDeleter> KODI::WINDOWING::GBM::CDRMCrtc::m_crtc private
Referenced by CDRMCrtc(), GetBufferId(), GetCrtcId(), GetMode(), GetModeValid(), GetX(), and GetY().
The documentation for this class was generated from the following files:
DRMCrtc.h
DRMCrtc.cpp