Kodi Documentation: CUrlOptions Class Reference
CUrlOptions Class Reference
#include <UrlOptions.h>
Public Types
typedef std::map< std::string, CVariant > UrlOptions
Public Member Functions
CUrlOptions ()
CUrlOptions (const std::string &options, const char *strLead="")
virtual ~CUrlOptions ()
void Clear ()
const UrlOptions & GetOptions () const
std::string GetOptionsString (bool withLeadingSeparator=false) const
virtual void AddOption (const std::string &key, const char *value)
virtual void AddOption (const std::string &key, const std::string &value)
virtual void AddOption (const std::string &key, int value)
virtual void AddOption (const std::string &key, float value)
virtual void AddOption (const std::string &key, double value)
virtual void AddOption (const std::string &key, bool value)
virtual void AddOptions (const std::string &options)
virtual void AddOptions (const CUrlOptions &options)
virtual void RemoveOption (const std::string &key)
bool HasOption (const std::string &key) const
bool GetOption (const std::string &key, CVariant &value) const
Protected Attributes
UrlOptions m_options
std::string m_strLead
Member Typedef Documentation
UrlOptions
typedef std::map<std::string, CVariant> CUrlOptions::UrlOptions
Constructor & Destructor Documentation
CUrlOptions() [1/2]
CUrlOptions::CUrlOptions () default
CUrlOptions() [2/2]
CUrlOptions::CUrlOptions (const std::string & options, const char * strLead = "")
References AddOptions().
~CUrlOptions()
CUrlOptions::~CUrlOptions () virtual default
Member Function Documentation
AddOption() [1/6]
void CUrlOptions::AddOption (const std::string & key, bool value) virtual
Reimplemented in CDbUrl.
References m_options, and value.
AddOption() [2/6]
void CUrlOptions::AddOption (const std::string & key, const char * value) virtual
Reimplemented in CDbUrl.
References AddOption(), and value.
Referenced by CDbUrl::AddOption(), AddOption(), CDbUrl::AddOption(), CDbUrl::AddOption(), CDbUrl::AddOption(), CDbUrl::AddOption(), CDbUrl::AddOption(), AddOptions(), CURL::SetOption(), CURL::SetProtocolOption(), TEST(), TEST(), TEST(), TEST(), and TEST().
AddOption() [3/6]
void CUrlOptions::AddOption (const std::string & key, const std::string & value) virtual
Reimplemented in CDbUrl.
References m_options, and value.
AddOption() [4/6]
void CUrlOptions::AddOption (const std::string & key, double value) virtual
Reimplemented in CDbUrl.
References m_options, and value.
AddOption() [5/6]
void CUrlOptions::AddOption (const std::string & key, float value) virtual
Reimplemented in CDbUrl.
References m_options, and value.
AddOption() [6/6]
void CUrlOptions::AddOption (const std::string & key, int value) virtual
Reimplemented in CDbUrl.
References m_options, and value.
AddOptions() [1/2]
void CUrlOptions::AddOptions (const CUrlOptions & options) virtual
References m_options.
AddOptions() [2/2]
void CUrlOptions::AddOptions (const std::string & options) virtual
Reimplemented in CDbUrl.
References AddOption(), CLog::Log(), LOGWARNING, m_strLead, and value.
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::AddOptions(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::AddOptions(), CDbUrl::AddOptions(), CUrlOptions(), CURL::SetOptions(), CURL::SetProtocolOptions(), and TEST().
Clear()
void CUrlOptions::Clear () inline
References m_options, and m_strLead.
Referenced by CURL::Reset(), CURL::SetOptions(), CURL::SetProtocolOptions(), TEST(), and TEST().
GetOption()
bool CUrlOptions::GetOption (const std::string & key, CVariant & value) const
References m_options, and value.
Referenced by CURL::GetOption(), CURL::GetProtocolOption(), TEST(), and TEST().
GetOptions()
const UrlOptions & CUrlOptions::GetOptions () const inline
References m_options.
Referenced by XFILE::CShoutcastFile::ExtractTagInfo(), CURL::GetOptions(), CURL::GetProtocolOptions(), and TEST().
GetOptionsString()
std::string CUrlOptions::GetOptionsString (bool withLeadingSeparator = false) const
Referenced by XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::BuildPath(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::BuildPath(), CURL::RemoveOption(), CURL::RemoveProtocolOption(), CURL::SetOption(), CURL::SetProtocolOption(), and TEST().
HasOption()
bool CUrlOptions::HasOption (const std::string & key) const
References m_options.
Referenced by CURL::HasOption(), CURL::HasProtocolOption(), TEST(), TEST(), and TEST().
RemoveOption()
void CUrlOptions::RemoveOption (const std::string & key) virtual
Reimplemented in CDbUrl.
References m_options.
Referenced by CURL::RemoveOption(), CDbUrl::RemoveOption(), CURL::RemoveProtocolOption(), and TEST().
Member Data Documentation
m_options
UrlOptions CUrlOptions::m_options protected
Referenced by AddOption(), AddOption(), AddOption(), AddOption(), AddOption(), AddOptions(), Clear(), GetOption(), GetOptions(), HasOption(), RemoveOption(), and CDbUrl::Reset().
m_strLead
std::string CUrlOptions::m_strLead protected
Referenced by AddOptions(), and Clear().
The documentation for this class was generated from the following files:
UrlOptions.h
UrlOptions.cpp