Kodi Documentation: CPowerManager Class Reference
CPowerManager Class Reference
#include <PowerManager.h>
Public Member Functions
CPowerManager ()
~CPowerManager () override
void Initialize ()
void SetDefaults ()
bool Powerdown ()
bool Suspend ()
bool Hibernate ()
bool Reboot ()
bool CanPowerdown ()
bool CanSuspend ()
bool CanHibernate ()
bool CanReboot ()
int BatteryLevel ()
void ProcessEvents ()
IPowerSyscall * GetPowerSyscall () const
Public Member Functions inherited from IPowerEventsCallback
virtual ~IPowerEventsCallback ()=default
Static Public Member Functions
static void SettingOptionsShutdownStatesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Private Member Functions
void OnSleep () override
void OnWake () override
void OnLowBattery () override
void RestorePlayerState ()
void StorePlayerState ()
Private Attributes
std::shared_ptr< CSettings > m_settings
std::unique_ptr< IPowerSyscall > m_instance
std::unique_ptr< CFileItem > m_lastPlayedFileItem
std::string m_lastUsedPlayer
Constructor & Destructor Documentation
CPowerManager()
CPowerManager::CPowerManager ()
References m_settings, and SettingOptionsShutdownStatesFiller().
~CPowerManager()
CPowerManager::~CPowerManager () override default
Member Function Documentation
BatteryLevel()
int CPowerManager::BatteryLevel ()
References m_instance.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetInt().
CanHibernate()
bool CPowerManager::CanHibernate ()
References m_instance.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), JSONRPC::CXBMCOperations::GetInfoBooleans(), JSONRPC::CSystemOperations::GetPropertyValue(), Hibernate(), SetDefaults(), and SettingOptionsShutdownStatesFiller().
CanPowerdown()
bool CPowerManager::CanPowerdown ()
References m_instance.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), JSONRPC::CXBMCOperations::GetInfoBooleans(), JSONRPC::CSystemOperations::GetPropertyValue(), Powerdown(), SetDefaults(), and SettingOptionsShutdownStatesFiller().
CanReboot()
bool CPowerManager::CanReboot ()
References m_instance.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), JSONRPC::CXBMCOperations::GetInfoBooleans(), JSONRPC::CSystemOperations::GetPropertyValue(), and Reboot().
CanSuspend()
bool CPowerManager::CanSuspend ()
References m_instance.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), JSONRPC::CXBMCOperations::GetInfoBooleans(), JSONRPC::CSystemOperations::GetPropertyValue(), SetDefaults(), SettingOptionsShutdownStatesFiller(), and Suspend().
GetPowerSyscall()
IPowerSyscall * CPowerManager::GetPowerSyscall () const inline
References m_instance.
Referenced by CXBMCApp::OnSleep(), and CXBMCApp::OnWakeup().
Hibernate()
bool CPowerManager::Hibernate ()
References CanHibernate(), and m_instance.
Referenced by CApplication::OnApplicationMessage().
Initialize()
void CPowerManager::Initialize ()
References IPowerSyscall::CreateInstance(), and m_instance.
OnLowBattery()
void CPowerManager::OnLowBattery () override private virtual
Implements IPowerEventsCallback.
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAnnouncementManager(), CLog::Log(), LOGINFO, CGUIDialogKaiToast::QueueNotification(), ANNOUNCEMENT::System, and CGUIDialogKaiToast::Warning.
OnSleep()
void CPowerManager::OnSleep () override private virtual
Implements IPowerEventsCallback.
References g_application, CServiceBroker::GetActiveAE(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), CLog::Log(), LOGINFO, PVR::CPVRManager::OnSleep(), CGUIDialog::Open(), CApplicationPowerHandling::StopShutdownTimer(), StorePlayerState(), IAE::Suspend(), ANNOUNCEMENT::System, and WINDOW_DIALOG_BUSY_NOCANCEL.
OnWake()
void CPowerManager::OnWake () override private virtual
Implements IPowerEventsCallback.
References CGUIWindow::Close(), g_application, g_hWnd, CServiceBroker::GetActiveAE(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CServiceBroker::GetNetwork(), CServiceBroker::GetPVRManager(), CServiceBroker::GetWeatherManager(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), CWinSystemBase::IsFullScreen(), CLog::Log(), LOGINFO, PVR::CPVRManager::OnWake(), CInfoLoader::Refresh(), CApplicationPowerHandling::ResetShutdownTimers(), RestorePlayerState(), IAE::Resume(), ANNOUNCEMENT::System, CNetworkBase::WaitForNet(), and WINDOW_DIALOG_BUSY_NOCANCEL.
Powerdown()
bool CPowerManager::Powerdown ()
References CanPowerdown(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), m_instance, CGUIDialog::Open(), and WINDOW_DIALOG_BUSY_NOCANCEL.
Referenced by CApplication::OnApplicationMessage().
ProcessEvents()
void CPowerManager::ProcessEvents ()
References m_instance.
Referenced by CCocoaPowerSyscall::OSPowerCallBack(), and CApplication::ProcessSlow().
Reboot()
bool CPowerManager::Reboot ()
References CanReboot(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), m_instance, CGUIDialog::Open(), success, ANNOUNCEMENT::System, and WINDOW_DIALOG_BUSY_NOCANCEL.
Referenced by CApplication::OnApplicationMessage().
RestorePlayerState()
void CPowerManager::RestorePlayerState () private
References g_application, CLog::Log(), LOGDEBUG, m_lastPlayedFileItem, and m_lastUsedPlayer.
Referenced by OnWake().
SetDefaults()
void CPowerManager::SetDefaults ()
References CanHibernate(), CanPowerdown(), CanSuspend(), CServiceBroker::GetAppParams(), CServiceBroker::GetPowerManager(), CLog::Log(), LOGERROR, m_settings, POWERSTATE_HIBERNATE, POWERSTATE_MINIMIZE, POWERSTATE_QUIT, POWERSTATE_SHUTDOWN, POWERSTATE_SUSPEND, and CSettings::SETTING_POWERMANAGEMENT_SHUTDOWNSTATE.
SettingOptionsShutdownStatesFiller()
void CPowerManager::SettingOptionsShutdownStatesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References CanHibernate(), CanPowerdown(), CanSuspend(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAppParams(), CServiceBroker::GetPowerManager(), POWERSTATE_HIBERNATE, POWERSTATE_MINIMIZE, POWERSTATE_QUIT, POWERSTATE_SHUTDOWN, and POWERSTATE_SUSPEND.
Referenced by CPowerManager().
StorePlayerState()
void CPowerManager::StorePlayerState () private
References g_application, CServiceBroker::GetAppComponents(), CApplicationPlayer::GetCurrentPlayer(), CApplicationStackHelper::IsPlayingISOStack(), CLog::Log(), LOGDEBUG, m_lastPlayedFileItem, and m_lastUsedPlayer.
Referenced by OnSleep().
Suspend()
bool CPowerManager::Suspend ()
References CanSuspend(), and m_instance.
Referenced by CApplication::OnApplicationMessage().
Member Data Documentation
m_instance
std::unique_ptr<IPowerSyscall> CPowerManager::m_instance private
Referenced by BatteryLevel(), CanHibernate(), CanPowerdown(), CanReboot(), CanSuspend(), GetPowerSyscall(), Hibernate(), Initialize(), Powerdown(), ProcessEvents(), Reboot(), and Suspend().
m_lastPlayedFileItem
std::unique_ptr<CFileItem> CPowerManager::m_lastPlayedFileItem private
Referenced by RestorePlayerState(), and StorePlayerState().
m_lastUsedPlayer
std::string CPowerManager::m_lastUsedPlayer private
Referenced by RestorePlayerState(), and StorePlayerState().
m_settings
std::shared_ptr<CSettings> CPowerManager::m_settings private
Referenced by CPowerManager(), and SetDefaults().
The documentation for this class was generated from the following files:
PowerManager.h
PowerManager.cpp