Kodi Documentation: PVR::CPVRChannelGroupsContainer Class Reference
PVR::CPVRChannelGroupsContainer Class Reference
#include <PVRChannelGroupsContainer.h>
Public Member Functions
CPVRChannelGroupsContainer ()
Create a new container for all channel groups.
virtual ~CPVRChannelGroupsContainer ()
Destroy this container.
bool Update (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Update all channel groups and all channels from PVR database and from given clients.
bool UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > &clients, bool bChannelsOnly=false)
Update data with groups and channels from the given clients, sync with local data.
void Unload ()
Unload and destruct all channel groups and all channels in them.
std::shared_ptr< CPVRChannelGroups > GetTV () const
Get the TV channel groups.
std::shared_ptr< CPVRChannelGroups > GetRadio () const
Get the radio channel groups.
std::shared_ptr< CPVRChannelGroups > Get (bool bRadio) const
Get the radio or TV channel groups.
std::shared_ptr< CPVRChannelGroup > GetGroupAllTV () const
Get the group containing all TV channels.
std::shared_ptr< CPVRChannelGroup > GetGroupAllRadio () const
Get the group containing all radio channels.
std::shared_ptr< CPVRChannelGroup > GetGroupAll (bool bRadio) const
Get the group containing all TV or radio channels.
std::shared_ptr< CPVRChannelGroup > GetGroupByPath (const std::string &path) const
Get a group given its path.
std::shared_ptr< CPVRChannelGroup > GetByIdFromAll (int iGroupId) const
Get a group given its ID.
std::shared_ptr< CPVRChannel > GetChannelById (int iChannelId) const
Get a channel given its database ID.
std::shared_ptr< CPVRChannel > GetChannelForEpgTag (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
Get the channel for the given epg tag.
std::shared_ptr< CPVRChannel > GetByPath (const std::string &strPath) const
Get a channel given its path.
std::shared_ptr< CPVRChannelGroupMember > GetChannelGroupMemberByPath (const std::string &strPath) const
Get a channel group member given its path.
std::shared_ptr< CPVRChannel > GetByUniqueID (int iUniqueChannelId, int iClientID) const
Get a channel given its channel ID from all containers.
std::shared_ptr< CPVRChannelGroupMember > GetLastPlayedChannelGroupMember () const
Get the channel group member that was played last.
bool HasChannelForProvider (bool isRadio, int clientId, int providerId) const
Check whether at least one channel is offered by the given provider.
unsigned int GetChannelCountByProvider (bool isRadio, int clientId, int providerId) const
Get the total count of channels offered by the given provider.
int CleanupCachedImages ()
Erase stale texture db entries and image files.
Private Member Functions
CPVRChannelGroupsContainer & operator= (const CPVRChannelGroupsContainer &)=delete
CPVRChannelGroupsContainer (const CPVRChannelGroupsContainer &)=delete
bool LoadFromDatabase (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Load all channel groups and all channels from PVR database.
Private Attributes
std::shared_ptr< CPVRChannelGroups > m_groupsRadio
std::shared_ptr< CPVRChannelGroups > m_groupsTV
CCriticalSection m_critSection
bool m_bIsUpdating = false
Constructor & Destructor Documentation
CPVRChannelGroupsContainer() [1/2]
CPVRChannelGroupsContainer::CPVRChannelGroupsContainer ()
Create a new container for all channel groups.
~CPVRChannelGroupsContainer()
CPVRChannelGroupsContainer::~CPVRChannelGroupsContainer () virtual
Destroy this container.
References Unload().
CPVRChannelGroupsContainer() [2/2]
PVR::CPVRChannelGroupsContainer::CPVRChannelGroupsContainer (const CPVRChannelGroupsContainer &) private delete
Member Function Documentation
CleanupCachedImages()
int CPVRChannelGroupsContainer::CleanupCachedImages ()
Erase stale texture db entries and image files.
Returns
number of cleaned up images.
References m_groupsRadio, and m_groupsTV.
Get()
std::shared_ptr< CPVRChannelGroups > CPVRChannelGroupsContainer::Get (bool bRadio) const
Get the radio or TV channel groups.
Parameters
bRadio If true, get the radio channel groups. Get the TV channel groups otherwise.
Returns
The requested groups.
References m_groupsRadio, and m_groupsTV.
Referenced by GetChannelForEpgTag(), GetChannelGroupMemberByPath(), GetGroupAll(), GetGroupByPath(), GetRadio(), and GetTV().
GetByIdFromAll()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroupsContainer::GetByIdFromAll (int iGroupId) const
Get a group given its ID.
Parameters
iGroupId The ID of the group.
Returns
The requested group or NULL if it wasn't found.
References m_groupsRadio, and m_groupsTV.
GetByPath()
std::shared_ptr< CPVRChannel > CPVRChannelGroupsContainer::GetByPath (const std::string & strPath) const
Get a channel given its path.
Parameters
strPath The path.
Returns
The channel or nullptr if it wasn't found.
References GetChannelGroupMemberByPath().
GetByUniqueID()
std::shared_ptr< CPVRChannel > CPVRChannelGroupsContainer::GetByUniqueID (int iUniqueChannelId, int iClientID) const
Get a channel given its channel ID from all containers.
Parameters
iUniqueChannelId The unique channel id on the client.
iClientID The ID of the client.
Returns
The channel or NULL if it wasn't found.
References GetGroupAllRadio(), and GetGroupAllTV().
GetChannelById()
std::shared_ptr< CPVRChannel > CPVRChannelGroupsContainer::GetChannelById (int iChannelId) const
Get a channel given its database ID.
Parameters
iChannelId The ID of the channel.
Returns
The channel or NULL if it wasn't found.
References m_groupsRadio, and m_groupsTV.
GetChannelCountByProvider()
unsigned int CPVRChannelGroupsContainer::GetChannelCountByProvider (bool isRadio, int clientId, int providerId) const
Get the total count of channels offered by the given provider.
Parameters
isRadio Check radio or TV channels.
clientId The clientId of the provider.
providerId The providerId.
Returns
The total count of matching channels.
References m_groupsRadio, and m_groupsTV.
GetChannelForEpgTag()
std::shared_ptr< CPVRChannel > CPVRChannelGroupsContainer::GetChannelForEpgTag (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const
Get the channel for the given epg tag.
Parameters
epgTag The epg tag.
Returns
The channel.
References Get().
GetChannelGroupMemberByPath()
std::shared_ptr< CPVRChannelGroupMember > CPVRChannelGroupsContainer::GetChannelGroupMemberByPath (const std::string & strPath) const
Get a channel group member given its path.
Parameters
strPath The path.
Returns
The channel group member or nullptr if it wasn't found.
References Get(), PVR::CPVRChannelsPath::IsRadio(), and PVR::CPVRChannelsPath::IsValid().
Referenced by GetByPath().
GetGroupAll()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroupsContainer::GetGroupAll (bool bRadio) const
Get the group containing all TV or radio channels.
Parameters
bRadio If true, get the group containing all radio channels. Get the group containing all TV channels otherwise.
Returns
The requested group.
References Get().
Referenced by GetGroupAllRadio(), and GetGroupAllTV().
GetGroupAllRadio()
std::shared_ptr< CPVRChannelGroup > PVR::CPVRChannelGroupsContainer::GetGroupAllRadio () const inline
Get the group containing all radio channels.
Returns
The group containing all radio channels.
References GetGroupAll().
Referenced by GetByUniqueID().
GetGroupAllTV()
std::shared_ptr< CPVRChannelGroup > PVR::CPVRChannelGroupsContainer::GetGroupAllTV () const inline
Get the group containing all TV channels.
Returns
The group containing all TV channels.
References GetGroupAll().
Referenced by GetByUniqueID().
GetGroupByPath()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroupsContainer::GetGroupByPath (const std::string & path) const
Get a group given its path.
Parameters
path The path to the channel group.
Returns
The channel group, or nullptr if not found.
References Get(), LOGERROR, and LOGPVR.
GetLastPlayedChannelGroupMember()
std::shared_ptr< CPVRChannelGroupMember > CPVRChannelGroupsContainer::GetLastPlayedChannelGroupMember () const
Get the channel group member that was played last.
Returns
The requested channel group member or nullptr.
References m_groupsRadio, and m_groupsTV.
GetRadio()
std::shared_ptr< CPVRChannelGroups > PVR::CPVRChannelGroupsContainer::GetRadio () const inline
Get the radio channel groups.
Returns
The radio channel groups.
References Get().
GetTV()
std::shared_ptr< CPVRChannelGroups > PVR::CPVRChannelGroupsContainer::GetTV () const inline
Get the TV channel groups.
Returns
The TV channel groups.
References Get().
HasChannelForProvider()
bool CPVRChannelGroupsContainer::HasChannelForProvider (bool isRadio, int clientId, int providerId) const
Check whether at least one channel is offered by the given provider.
Parameters
isRadio Check radio or TV channels.
clientId The clientId to check.
providerId The providerId to check.
Returns
True, if at least one matching channel is offered by the provider, false otherwise.
References m_groupsRadio, and m_groupsTV.
LoadFromDatabase()
bool CPVRChannelGroupsContainer::LoadFromDatabase (const std::vector< std::shared_ptr< CPVRClient > > & clients) private
Load all channel groups and all channels from PVR database.
Parameters
clients The PVR clients data should be loaded for. Leave empty for all clients.
Returns
True on success, false otherwise.
References m_groupsRadio, and m_groupsTV.
Referenced by Update().
operator=()
CPVRChannelGroupsContainer & PVR::CPVRChannelGroupsContainer::operator= (const CPVRChannelGroupsContainer &) private delete
Unload()
void CPVRChannelGroupsContainer::Unload ()
Unload and destruct all channel groups and all channels in them.
References m_groupsRadio, and m_groupsTV.
Referenced by ~CPVRChannelGroupsContainer().
Update()
bool CPVRChannelGroupsContainer::Update (const std::vector< std::shared_ptr< CPVRClient > > & clients)
Update all channel groups and all channels from PVR database and from given clients.
Parameters
clients The PVR clients data should be loaded for. Leave empty for all clients.
Returns
True on success, false otherwise.
References LoadFromDatabase(), and UpdateFromClients().
UpdateFromClients()
bool CPVRChannelGroupsContainer::UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > & clients, bool bChannelsOnly = false)
Update data with groups and channels from the given clients, sync with local data.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
bChannelsOnly Set to true to only update channels, not the groups themselves.
Returns
True on success, false otherwise.
References LOGDEBUG, LOGPVR, m_bIsUpdating, m_critSection, m_groupsRadio, and m_groupsTV.
Referenced by Update().
Member Data Documentation
m_bIsUpdating
bool PVR::CPVRChannelGroupsContainer::m_bIsUpdating = false private
Referenced by UpdateFromClients().
m_critSection
CCriticalSection PVR::CPVRChannelGroupsContainer::m_critSection private
Referenced by UpdateFromClients().
m_groupsRadio
std::shared_ptr<CPVRChannelGroups> PVR::CPVRChannelGroupsContainer::m_groupsRadio private
all radio channel groups
Referenced by CleanupCachedImages(), Get(), GetByIdFromAll(), GetChannelById(), GetChannelCountByProvider(), GetLastPlayedChannelGroupMember(), HasChannelForProvider(), LoadFromDatabase(), Unload(), and UpdateFromClients().
m_groupsTV
std::shared_ptr<CPVRChannelGroups> PVR::CPVRChannelGroupsContainer::m_groupsTV private
all TV channel groups
Referenced by CleanupCachedImages(), Get(), GetByIdFromAll(), GetChannelById(), GetChannelCountByProvider(), GetLastPlayedChannelGroupMember(), HasChannelForProvider(), LoadFromDatabase(), Unload(), and UpdateFromClients().
The documentation for this class was generated from the following files:
PVRChannelGroupsContainer.h
PVRChannelGroupsContainer.cpp