Kodi Documentation: CSlideShowDelegator Class Reference
CSlideShowDelegator Class Reference
#include <SlideShowDelegator.h>
Public Member Functions
CSlideShowDelegator ()=default
~CSlideShowDelegator ()=default
void SetDelegate (ISlideShowDelegate *delegate)
void ResetDelegate ()
void Add (const CFileItem *picture) override
bool IsPlaying () const override
void Select (const std::string &picture) override
void GetSlideShowContents (CFileItemList &list) override
std::shared_ptr< const CFileItem > GetCurrentSlide () override
void StartSlideShow () override
void PlayPicture () override
bool InSlideShow () const override
int NumSlides () const override
int CurrentSlide () const override
bool IsPaused () const override
bool IsShuffled () const override
void Reset () override
void Shuffle () override
int GetDirection () const override
void RunSlideShow (const std::string &strPath, bool bRecursive=false, bool bRandom=false, bool bNotRandom=false, const std::string &beginSlidePath="", bool startSlideShow=true, SortBy method=SortByLabel, SortOrder order=SortOrderAscending, SortAttribute sortAttributes=SortAttributeNone, const std::string &strExtensions="") override
void AddFromPath (const std::string &strPath, bool bRecursive, SortBy method=SortByLabel, SortOrder order=SortOrderAscending, SortAttribute sortAttributes=SortAttributeNone, const std::string &strExtensions="") override
Public Member Functions inherited from ISlideShowDelegate
ISlideShowDelegate ()=default
virtual ~ISlideShowDelegate ()=default
Private Attributes
ISlideShowDelegate * m_delegate
Constructor & Destructor Documentation
CSlideShowDelegator()
CSlideShowDelegator::CSlideShowDelegator () default
~CSlideShowDelegator()
CSlideShowDelegator::~CSlideShowDelegator () default
Member Function Documentation
Add()
void CSlideShowDelegator::Add (const CFileItem * picture) override virtual
Implements ISlideShowDelegate.
References ISlideShowDelegate::Add(), and m_delegate.
Referenced by JSONRPC::CPlaylistOperations::Add(), CGUIWindowPictures::LoadPlayList(), CApplication::OnApplicationMessage(), CGUIWindowFileManager::OnStart(), JSONRPC::CPlayerOperations::Open(), and CGUIWindowPictures::ShowPicture().
AddFromPath()
void CSlideShowDelegator::AddFromPath (const std::string & strPath, bool bRecursive, SortBy method = SortByLabel, SortOrder order = SortOrderAscending, SortAttribute sortAttributes = SortAttributeNone, const std::string & strExtensions = "") override virtual
Todo:
refactor to use an options struct. Methods with so many arguments are a sign of a bad design...
Implements ISlideShowDelegate.
References ISlideShowDelegate::AddFromPath(), and m_delegate.
Referenced by CGUIWindowPictures::OnShowPictureRecursive().
CurrentSlide()
int CSlideShowDelegator::CurrentSlide () const override virtual
Implements ISlideShowDelegate.
References ISlideShowDelegate::CurrentSlide(), and m_delegate.
Referenced by JSONRPC::CPlayerOperations::GetItem(), JSONRPC::CPlayerOperations::GetPropertyValue(), and UPNP::CUPnPRenderer::UpdateState().
GetCurrentSlide()
std::shared_ptr< const CFileItem > CSlideShowDelegator::GetCurrentSlide () override virtual
Implements ISlideShowDelegate.
References ISlideShowDelegate::GetCurrentSlide(), and m_delegate.
Referenced by KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetBool(), and CGUIWindowPictures::OnInitWindow().
GetDirection()
int CSlideShowDelegator::GetDirection () const override virtual
Implements ISlideShowDelegate.
References ISlideShowDelegate::GetDirection(), and m_delegate.
Referenced by JSONRPC::CPlayerOperations::GetPropertyValue(), and JSONRPC::CPlayerOperations::PlayPause().
GetSlideShowContents()
void CSlideShowDelegator::GetSlideShowContents (CFileItemList & list) override virtual
Implements ISlideShowDelegate.
References ISlideShowDelegate::GetSlideShowContents(), and m_delegate.
Referenced by JSONRPC::CPlayerOperations::GetItem(), JSONRPC::CPlaylistOperations::GetItems(), and JSONRPC::CPlayerOperations::Open().
InSlideShow()
bool CSlideShowDelegator::InSlideShow () const override virtual
Implements ISlideShowDelegate.
References ISlideShowDelegate::InSlideShow(), and m_delegate.
Referenced by KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetBool(), and CApplication::OnAction().
IsPaused()
bool CSlideShowDelegator::IsPaused () const override virtual
Implements ISlideShowDelegate.
References ISlideShowDelegate::IsPaused(), and m_delegate.
Referenced by KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetBool(), JSONRPC::CPlayerOperations::GetPropertyValue(), CApplication::OnAction(), and JSONRPC::CPlayerOperations::PlayPause().
IsPlaying()
bool CSlideShowDelegator::IsPlaying () const override virtual
Implements ISlideShowDelegate.
References ISlideShowDelegate::IsPlaying(), and m_delegate.
Referenced by JSONRPC::CPlayerOperations::GetPropertyValue(), and JSONRPC::CPlayerOperations::PlayPause().
IsShuffled()
bool CSlideShowDelegator::IsShuffled () const override virtual
Implements ISlideShowDelegate.
References ISlideShowDelegate::IsShuffled(), and m_delegate.
Referenced by KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetBool(), JSONRPC::CPlayerOperations::GetPropertyValue(), and JSONRPC::CPlayerOperations::SetShuffle().
NumSlides()
int CSlideShowDelegator::NumSlides () const override virtual
Implements ISlideShowDelegate.
References m_delegate, and ISlideShowDelegate::NumSlides().
Referenced by JSONRPC::CPlaylistOperations::GetPropertyValue(), JSONRPC::CPlayerOperations::GetPropertyValue(), CGUIWindowPictures::LoadPlayList(), CGUIWindowPictures::OnShowPictureRecursive(), JSONRPC::CPlayerOperations::SetShuffle(), CGUIWindowPictures::ShowPicture(), and UPNP::CUPnPRenderer::UpdateState().
PlayPicture()
void CSlideShowDelegator::PlayPicture () override virtual
Implements ISlideShowDelegate.
References m_delegate, and ISlideShowDelegate::PlayPicture().
Referenced by CGUIWindowPictures::ShowPicture().
Reset()
void CSlideShowDelegator::Reset () override virtual
Implements ISlideShowDelegate.
References m_delegate, and ISlideShowDelegate::Reset().
Referenced by JSONRPC::CPlaylistOperations::Clear(), CGUIWindowPictures::LoadPlayList(), CApplication::OnApplicationMessage(), CGUIWindowFileManager::OnStart(), JSONRPC::CPlayerOperations::Open(), and CGUIWindowPictures::ShowPicture().
ResetDelegate()
void CSlideShowDelegator::ResetDelegate ()
References m_delegate.
Referenced by CGUIWindowSlideShow::~CGUIWindowSlideShow().
RunSlideShow()
void CSlideShowDelegator::RunSlideShow (const std::string & strPath, bool bRecursive = false, bool bRandom = false, bool bNotRandom = false, const std::string & beginSlidePath = "", bool startSlideShow = true, SortBy method = SortByLabel, SortOrder order = SortOrderAscending, SortAttribute sortAttributes = SortAttributeNone, const std::string & strExtensions = "") override virtual
Todo:
refactor to use an options struct. Methods with so many arguments are a sign of a bad design...
Implements ISlideShowDelegate.
References m_delegate, and ISlideShowDelegate::RunSlideShow().
Referenced by CGUIWindowPictures::OnSlideShow(), and CGUIWindowPictures::OnSlideShowRecursive().
Select()
void CSlideShowDelegator::Select (const std::string & picture) override virtual
Implements ISlideShowDelegate.
References m_delegate, and ISlideShowDelegate::Select().
Referenced by CApplication::OnApplicationMessage(), CGUIWindowFileManager::OnStart(), and CGUIWindowPictures::ShowPicture().
SetDelegate()
void CSlideShowDelegator::SetDelegate (ISlideShowDelegate * delegate)
References m_delegate.
Referenced by CGUIWindowSlideShow::CGUIWindowSlideShow().
Shuffle()
void CSlideShowDelegator::Shuffle () override virtual
Implements ISlideShowDelegate.
References m_delegate, and ISlideShowDelegate::Shuffle().
Referenced by JSONRPC::CPlayerOperations::SetShuffle().
StartSlideShow()
void CSlideShowDelegator::StartSlideShow () override virtual
Implements ISlideShowDelegate.
References m_delegate, and ISlideShowDelegate::StartSlideShow().
Referenced by CGUIWindowPictures::LoadPlayList(), CApplication::OnApplicationMessage(), and CGUIWindowPictures::ShowPicture().
Member Data Documentation
m_delegate
ISlideShowDelegate* CSlideShowDelegator::m_delegate private
Referenced by Add(), AddFromPath(), CurrentSlide(), GetCurrentSlide(), GetDirection(), GetSlideShowContents(), InSlideShow(), IsPaused(), IsPlaying(), IsShuffled(), NumSlides(), PlayPicture(), Reset(), ResetDelegate(), RunSlideShow(), Select(), SetDelegate(), Shuffle(), and StartSlideShow().
The documentation for this class was generated from the following files:
SlideShowDelegator.h
SlideShowDelegator.cpp