Kodi Documentation: CPreflightHandler Class Reference
CPreflightHandler Class Reference
#include <PreflightHandler.h>
Static Public Member Functions
static uint64_t NSUserDefaultsSize ()
static void NSUserDefaultsPurge (const char *prefix)
static void MigrateUserdataXMLToNSUserDefaults ()
static void CheckForRemovedCacheFolder ()
Member Function Documentation
CheckForRemovedCacheFolder()
void CPreflightHandler::CheckForRemovedCacheFolder () static
Todo:
: implement some sort of backup/restore if folder no longer exists?
MigrateUserdataXMLToNSUserDefaults()
void CPreflightHandler::MigrateUserdataXMLToNSUserDefaults () static
References XFILE::CTVOSFile::Close(), XFILE::CPosixFile::Close(), XFILE::CPosixFile::Delete(), CURL::Get(), CTVOSFileUtils::GetUserHomeDirectory(), LOG, NSUserDefaultsPurge(), NSUserDefaultsSize(), XFILE::CPosixFile::Open(), XFILE::CTVOSFile::OpenForWrite(), XFILE::CPosixFile::Read(), and XFILE::CTVOSFile::Write().
NSUserDefaultsPurge()
void CPreflightHandler::NSUserDefaultsPurge (const char * prefix) static
References LOG.
Referenced by MigrateUserdataXMLToNSUserDefaults().
NSUserDefaultsSize()
uint64_t CPreflightHandler::NSUserDefaultsSize () static
Referenced by MigrateUserdataXMLToNSUserDefaults().
The documentation for this class was generated from the following files:
PreflightHandler.h
PreflightHandler.mm