Kodi Documentation: KODI::RETRO::CRetroPlayerUtils Class Reference
KODI::RETRO::CRetroPlayerUtils Class Reference
#include <RetroPlayerUtils.h>
Static Public Member Functions
static const char * StretchModeToIdentifier (STRETCHMODE stretchMode)
Convert a stretch mode enum to a short string identifier.
static STRETCHMODE IdentifierToStretchMode (const std::string &stretchMode)
Convert a stretch mode identifier to an enum.
Member Function Documentation
IdentifierToStretchMode()
STRETCHMODE CRetroPlayerUtils::IdentifierToStretchMode (const std::string & stretchMode) static
Convert a stretch mode identifier to an enum.
Parameters
stretchMode The short string identifier, from GameSettings.h, representing the stretch mode
Returns
The stretch mode enum, or STRETCHMODE::Normal if the identifier is invalid
References KODI::RETRO::Fullscreen, KODI::RETRO::Normal, KODI::RETRO::Original, KODI::RETRO::Stretch4x3, KODI::RETRO::STRETCHMODE_FULLSCREEN_ID, KODI::RETRO::STRETCHMODE_NORMAL_ID, KODI::RETRO::STRETCHMODE_ORIGINAL_ID, KODI::RETRO::STRETCHMODE_STRETCH_4_3_ID, KODI::RETRO::STRETCHMODE_ZOOM_ID, and KODI::RETRO::Zoom.
Referenced by CMediaSettings::Load(), and KODI::RETRO::CGUIGameControl::UpdateInfo().
StretchModeToIdentifier()
const char * CRetroPlayerUtils::StretchModeToIdentifier (STRETCHMODE stretchMode) static
Convert a stretch mode enum to a short string identifier.
Parameters
stretchMode The stretch mode
Returns
A short string identifier specified by GameSettings.h, or an empty string if the stretch mode is invalid
References KODI::RETRO::Fullscreen, KODI::RETRO::Normal, KODI::RETRO::Original, KODI::RETRO::Stretch4x3, KODI::RETRO::STRETCHMODE_FULLSCREEN_ID, KODI::RETRO::STRETCHMODE_NORMAL_ID, KODI::RETRO::STRETCHMODE_ORIGINAL_ID, KODI::RETRO::STRETCHMODE_STRETCH_4_3_ID, KODI::RETRO::STRETCHMODE_ZOOM_ID, and KODI::RETRO::Zoom.
Referenced by KODI::GAME::CDialogGameStretchMode::GetItems(), KODI::GUILIB::GUIINFO::CGamesGUIInfo::GetLabel(), and CMediaSettings::Save().
The documentation for this class was generated from the following files:
RetroPlayerUtils.h
RetroPlayerUtils.cpp