Kodi Documentation: PVR::CPVRProviders Class Reference
PVR::CPVRProviders Class Reference
#include <PVRProviders.h>
Public Member Functions
CPVRProviders ()=default
~CPVRProviders ()=default
std::vector< std::shared_ptr< CPVRProvider > > GetProviders () const
std::size_t GetNumProviders () const
bool Update (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Update all providers from PVR database and from given clients.
void Unload ()
unload all providers.
bool UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Update data with providers from the given clients, sync with local data.
bool LoadFromDatabase (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Load all local providers from PVR database.
std::shared_ptr< CPVRProvider > CheckAndAddEntry (const std::shared_ptr< CPVRProvider > &newProvider, ProviderUpdateMode updateMode)
Check if the entry exists in the container, if it does update it otherwise add it.
std::shared_ptr< CPVRProvider > CheckAndPersistEntry (const std::shared_ptr< CPVRProvider > &newProvider, ProviderUpdateMode updateMode)
Check if the entry exists in the container, if it does update it and persist it in the DB otherwise add it and persist it in the DB.
bool PersistUserChanges (const std::vector< std::shared_ptr< CPVRProvider > > &providers)
Persist user changes to the current state of the providers in the DB.
std::shared_ptr< CPVRProvider > GetById (int iProviderId) const
Get a provider given it's database ID.
int CleanupCachedImages ()
Erase stale texture db entries and image files.
Public Member Functions inherited from PVR::CPVRProvidersContainer
bool UpdateFromClient (const std::shared_ptr< CPVRProvider > &provider)
Add a provider to this container or update the provider if already present in this container.
std::shared_ptr< CPVRProvider > GetByClient (int iClientId, int iUniqueId) const
Get the provider denoted by given client id and unique client provider id.
std::vector< std::shared_ptr< CPVRProvider > > GetProvidersList () const
Private Member Functions
void RemoveEntry (const std::shared_ptr< CPVRProvider > &provider)
bool UpdateDefaultEntries (const CPVRProvidersContainer &newProviders)
bool UpdateClientEntries (const CPVRProvidersContainer &newProviders, const std::vector< int > &failedClients, const std::vector< int > &disabledClients)
Private Attributes
bool m_bIsUpdating = false
Additional Inherited Members
Protected Member Functions inherited from PVR::CPVRProvidersContainer
void InsertEntry (const std::shared_ptr< CPVRProvider > &newProvider, ProviderUpdateMode updateMode)
Protected Attributes inherited from PVR::CPVRProvidersContainer
CCriticalSection m_critSection
int m_iLastId = 0
std::vector< std::shared_ptr< CPVRProvider > > m_providers
Constructor & Destructor Documentation
CPVRProviders()
PVR::CPVRProviders::CPVRProviders () default
~CPVRProviders()
PVR::CPVRProviders::~CPVRProviders () default
Member Function Documentation
CheckAndAddEntry()
std::shared_ptr< CPVRProvider > CPVRProviders::CheckAndAddEntry (const std::shared_ptr< CPVRProvider > & newProvider, ProviderUpdateMode updateMode)
Check if the entry exists in the container, if it does update it otherwise add it.
Parameters
newProvider The provider entry to update/add in/to the container
updateMode update as Client (respect User set values) or DB (update all values)
Returns
The provider if updated or added, otherwise an empty object (nullptr)
References PVR::CPVRProvidersContainer::GetByClient(), PVR::CPVRProvidersContainer::InsertEntry(), PVR::CPVRProvidersContainer::m_critSection, and PVR::CPVRProvidersContainer::m_iLastId.
Referenced by PVR::CPVRDatabase::Get(), LoadFromDatabase(), and UpdateFromClients().
CheckAndPersistEntry()
std::shared_ptr< CPVRProvider > CPVRProviders::CheckAndPersistEntry (const std::shared_ptr< CPVRProvider > & newProvider, ProviderUpdateMode updateMode)
Check if the entry exists in the container, if it does update it and persist it in the DB otherwise add it and persist it in the DB.
Parameters
newProvider The provider entry to update/add in/to the container and DB
updateMode update as Client (respect User set values) or DB (update all values)
Returns
The provider if updated or added, otherwise an empty object (nullptr)
References PVR::CPVRProvidersContainer::GetByClient(), PVR::CPVRProvidersContainer::InsertEntry(), LOGDEBUG, LOGPVR, PVR::CPVRProvidersContainer::m_critSection, and PVR::CPVRProvidersContainer::m_iLastId.
Referenced by UpdateClientEntries().
CleanupCachedImages()
int CPVRProviders::CleanupCachedImages ()
Erase stale texture db entries and image files.
Returns
number of cleaned up images.
References PVR::CPVRCachedImages::Cleanup(), PVR::CPVRProvider::IMAGE_OWNER_PATTERN, PVR::CPVRProvidersContainer::m_critSection, and PVR::CPVRProvidersContainer::m_providers.
GetById()
std::shared_ptr< CPVRProvider > CPVRProviders::GetById (int iProviderId) const
Get a provider given it's database ID.
Parameters
iProviderId The ID to find
Returns
The provider, or an empty one when not found
References PVR::CPVRProvidersContainer::m_critSection, and PVR::CPVRProvidersContainer::m_providers.
GetNumProviders()
std::size_t CPVRProviders::GetNumProviders () const
Get the number of enabled providers
Returns
The total number of enabled providers
References GetProviders(), and PVR::CPVRProvidersContainer::m_critSection.
GetProviders()
std::vector< std::shared_ptr< CPVRProvider > > CPVRProviders::GetProviders () const
Get all enabled providers
Returns
The list of all enabled providers
Todo:
optimize; get rid of iteration.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), PVR::CPVRProvidersContainer::m_critSection, and PVR::CPVRProvidersContainer::m_providers.
Referenced by GetNumProviders().
LoadFromDatabase()
bool CPVRProviders::LoadFromDatabase (const std::vector< std::shared_ptr< CPVRClient > > & clients)
Load all local providers from PVR database.
Parameters
clients The PVR clients data should be loaded for. Leave empty for all clients.
Returns
True on success, false otherwise.
References PVR::BY_DATABASE, CheckAndAddEntry(), PVR::CPVRProvidersContainer::GetProvidersList(), CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), and PVR::CPVRProvidersContainer::m_iLastId.
Referenced by Update().
PersistUserChanges()
bool CPVRProviders::PersistUserChanges (const std::vector< std::shared_ptr< CPVRProvider > > & providers)
Persist user changes to the current state of the providers in the DB.
References LOGDEBUG, and LOGPVR.
RemoveEntry()
void CPVRProviders::RemoveEntry (const std::shared_ptr< CPVRProvider > & provider) private
References PVR::CPVRProvidersContainer::m_critSection, and PVR::CPVRProvidersContainer::m_providers.
Unload()
void CPVRProviders::Unload ()
unload all providers.
References PVR::CPVRProvidersContainer::m_critSection, and PVR::CPVRProvidersContainer::m_providers.
Update()
bool CPVRProviders::Update (const std::vector< std::shared_ptr< CPVRClient > > & clients)
Update all providers from PVR database and from given clients.
Parameters
clients The PVR clients data should be loaded for. Leave empty for all clients.
Returns
True on success, false otherwise.
References LoadFromDatabase(), and UpdateFromClients().
UpdateClientEntries()
bool CPVRProviders::UpdateClientEntries (const CPVRProvidersContainer & newProviders, const std::vector< int > & failedClients, const std::vector< int > & disabledClients) private
References PVR::BY_CLIENT, CheckAndPersistEntry(), PVR::CPVRProvidersContainer::GetByClient(), PVR::CPVRProvidersContainer::GetProvidersList(), LOGDEBUG, LOGPVR, m_bIsUpdating, PVR::CPVRProvidersContainer::m_critSection, and PVR::CPVRProvidersContainer::m_providers.
Referenced by UpdateFromClients().
UpdateDefaultEntries()
bool CPVRProviders::UpdateDefaultEntries (const CPVRProvidersContainer & newProviders) private
References PVR::CPVRProvidersContainer::GetByClient(), PVR::CPVRProvidersContainer::GetProvidersList(), LOGDEBUG, LOGPVR, PVR::CPVRProvidersContainer::m_critSection, and PVR::CPVRProvidersContainer::m_providers.
Referenced by UpdateFromClients().
UpdateFromClients()
bool CPVRProviders::UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > & clients)
Update data with providers from the given clients, sync with local data.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
Returns
True on success, false otherwise.
References PVR::BY_CLIENT, CheckAndAddEntry(), PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), LOGDEBUG, LOGPVR, m_bIsUpdating, PVR::CPVRProvidersContainer::m_critSection, UpdateClientEntries(), and UpdateDefaultEntries().
Referenced by Update().
Member Data Documentation
m_bIsUpdating
bool PVR::CPVRProviders::m_bIsUpdating = false private
Referenced by UpdateClientEntries(), and UpdateFromClients().
The documentation for this class was generated from the following files:
PVRProviders.h
PVRProviders.cpp