Kodi Documentation: INFO::InfoExpression Class Reference
INFO::InfoExpression Class Reference
Class to wrap active boolean expressions.
#include <InfoExpression.h>
Classes
class InfoAssociativeGroup
class InfoLeaf
class InfoSubexpression
Public Member Functions
InfoExpression (const std::string &expression, int context, unsigned int &refreshCounter)
~InfoExpression () override=default
void Initialize (CGUIInfoManager *infoMgr) override
void Update (int contextWindow, const CGUIListItem *item) override
Update the value of this info bool This is called if and only if the info bool is dirty, allowing it to update it's current value.
Public Member Functions inherited from INFO::InfoBool
InfoBool (const std::string &expression, int context, unsigned int &refreshCounter)
virtual ~InfoBool ()=default
bool Get (int contextWindow, const CGUIListItem *item=nullptr)
Get the value of this info bool This is called to update (if dirty) and fetch the value of the info bool.
bool operator== (const InfoBool &right) const
bool operator< (const InfoBool &right) const
const std::string & GetExpression () const
bool ListItemDependent () const
Private Types
enum operator_t {
OPERATOR_NONE = 0 , OPERATOR_LB , OPERATOR_RB , OPERATOR_OR ,
OPERATOR_AND , OPERATOR_NOT
}
enum node_type_t { NODE_LEAF , NODE_AND , NODE_OR }
typedef std::shared_ptr< InfoSubexpression > InfoSubexpressionPtr
Private Member Functions
bool Parse (const std::string &expression)
Static Private Member Functions
static operator_t GetOperator (char ch)
static void OperatorPop (std::stack< operator_t> &operator_stack, bool &invert, std::stack< InfoSubexpressionPtr > &nodes)
Private Attributes
InfoSubexpressionPtr m_expression_tree
Additional Inherited Members
Protected Attributes inherited from INFO::InfoBool
bool m_value = false
current value
int m_context
contextual information to go with the condition
bool m_listItemDependent = false
do not cache if a listitem pointer is given
std::string m_expression
original expression
CGUIInfoManager * m_infoMgr
Detailed Description
Class to wrap active boolean expressions.
Member Typedef Documentation
InfoSubexpressionPtr
typedef std::shared_ptr<InfoSubexpression> INFO::InfoExpression::InfoSubexpressionPtr private
Member Enumeration Documentation
node_type_t
enum INFO::InfoExpression::node_type_t private
Enumerator
NODE_LEAF
NODE_AND
NODE_OR
operator_t
enum INFO::InfoExpression::operator_t private
Enumerator
OPERATOR_NONE
OPERATOR_LB
OPERATOR_RB
OPERATOR_OR
OPERATOR_AND
OPERATOR_NOT
Constructor & Destructor Documentation
InfoExpression()
INFO::InfoExpression::InfoExpression (const std::string & expression, int context, unsigned int & refreshCounter) inline
~InfoExpression()
INFO::InfoExpression::~InfoExpression () override default
Member Function Documentation
GetOperator()
InfoExpression::operator_t InfoExpression::GetOperator (char ch) static private
References OPERATOR_AND, OPERATOR_LB, OPERATOR_NONE, OPERATOR_NOT, OPERATOR_OR, and OPERATOR_RB.
Referenced by Parse().
Initialize()
void InfoExpression::Initialize (CGUIInfoManager * infoMgr) override virtual
Reimplemented from INFO::InfoBool.
References INFO::InfoBool::Initialize(), CLog::Log(), LOGERROR, INFO::InfoBool::m_expression, m_expression_tree, INFO::InfoBool::m_infoMgr, Parse(), and CGUIInfoManager::Register().
OperatorPop()
void InfoExpression::OperatorPop (std::stack< operator_t> & operator_stack, bool & invert, std::stack< InfoSubexpressionPtr > & nodes) static private
References left, NODE_AND, NODE_OR, OPERATOR_AND, OPERATOR_NOT, OPERATOR_OR, and right.
Referenced by Parse().
Parse()
bool InfoExpression::Parse (const std::string & expression) private
References GetOperator(), CLog::Log(), LOGERROR, INFO::InfoBool::m_context, m_expression_tree, INFO::InfoBool::m_infoMgr, INFO::InfoBool::m_listItemDependent, OPERATOR_LB, OPERATOR_NONE, OPERATOR_NOT, OPERATOR_RB, OperatorPop(), and CGUIInfoManager::Register().
Referenced by Initialize().
Update()
void InfoExpression::Update (int contextWindow, const CGUIListItem * item) override virtual
Update the value of this info bool This is called if and only if the info bool is dirty, allowing it to update it's current value.
Reimplemented from INFO::InfoBool.
References INFO::DEFAULT_CONTEXT, INFO::InfoBool::m_context, m_expression_tree, and INFO::InfoBool::m_value.
Member Data Documentation
m_expression_tree
InfoSubexpressionPtr INFO::InfoExpression::m_expression_tree private
Referenced by Initialize(), Parse(), and Update().
The documentation for this class was generated from the following files:
InfoExpression.h
InfoExpression.cpp