Kodi Documentation: KODI::KEYMAP::CKeymap Class Reference
KODI::KEYMAP::CKeymap Class Reference
#include <Keymap.h>
Public Member Functions
CKeymap (std::shared_ptr< const IWindowKeymap > keymap, const IKeymapEnvironment *environment)
std::string ControllerID () const override
The controller ID.
const IKeymapEnvironment * Environment () const override
Access properties of the keymapping environment.
const KeymapActionGroup & GetActions (const std::string &keyName) const override
Get the actions for a given key name.
Public Member Functions inherited from KODI::KEYMAP::IKeymap
virtual ~IKeymap ()=default
Private Attributes
const std::shared_ptr< const IWindowKeymap > m_keymap
const IKeymapEnvironment *const m_environment
Constructor & Destructor Documentation
CKeymap()
CKeymap::CKeymap (std::shared_ptr< const IWindowKeymap > keymap, const IKeymapEnvironment * environment)
Member Function Documentation
ControllerID()
std::string CKeymap::ControllerID () const override virtual
The controller ID.
This is required because key names are specific to each controller
Implements KODI::KEYMAP::IKeymap.
References m_keymap.
Environment()
const IKeymapEnvironment * KODI::KEYMAP::CKeymap::Environment () const inline override virtual
Access properties of the keymapping environment.
Implements KODI::KEYMAP::IKeymap.
References m_environment.
GetActions()
const KeymapActionGroup & CKeymap::GetActions (const std::string & keyName) const override virtual
Get the actions for a given key name.
Parameters
keyName The key name created by CJoystickUtils::MakeKeyName()
Returns
A list of actions associated with the given key
Implements KODI::KEYMAP::IKeymap.
References actions, KODI::KEYMAP::IKeymapEnvironment::GetFallthrough(), KODI::KEYMAP::IKeymapEnvironment::GetWindowID(), m_environment, m_keymap, and KODI::KEYMAP::IKeymapEnvironment::UseGlobalFallthrough().
Member Data Documentation
m_environment
const IKeymapEnvironment* const KODI::KEYMAP::CKeymap::m_environment private
Referenced by Environment(), and GetActions().
m_keymap
const std::shared_ptr<const IWindowKeymap> KODI::KEYMAP::CKeymap::m_keymap private
Referenced by ControllerID(), and GetActions().
The documentation for this class was generated from the following files:
Keymap.h
Keymap.cpp