Kodi Documentation: ADDON::CVFSURLWrapper Class Reference
ADDON::CVFSURLWrapper Class Reference
Public Member Functions
CVFSURLWrapper (const CURL &url2)
Public Attributes
VFSURL url
Protected Attributes
std::vector< std::string > m_strings
Constructor & Destructor Documentation
CVFSURLWrapper()
ADDON::CVFSURLWrapper::CVFSURLWrapper (const CURL & url2) inline explicit
References VFSURL::domain, VFSURL::filename, CURL::Get(), CURL::GetDomain(), CURL::GetFileName(), CURL::GetHostName(), CURL::GetOptions(), CURL::GetPassWord(), CURL::GetPort(), CURL::GetProtocol(), CURL::GetRedacted(), CURL::GetShareName(), CURL::GetUserName(), VFSURL::hostname, m_strings, VFSURL::options, VFSURL::password, VFSURL::port, VFSURL::protocol, VFSURL::redacted, VFSURL::sharename, VFSURL::url, url, and VFSURL::username.
Member Data Documentation
m_strings
std::vector<std::string> ADDON::CVFSURLWrapper::m_strings protected
Referenced by CVFSURLWrapper().
url
VFSURL ADDON::CVFSURLWrapper::url
Referenced by ADDON::CVFSEntry::ContainsFiles(), ADDON::CVFSEntry::CreateDirectory(), CVFSURLWrapper(), ADDON::CVFSEntry::Delete(), ADDON::CVFSEntry::DirectoryExists(), ADDON::CVFSEntry::Exists(), ADDON::CVFSEntry::GetDirectory(), ADDON::CVFSEntry::Open(), ADDON::CVFSEntry::OpenForWrite(), ADDON::CVFSEntry::RemoveDirectory(), ADDON::CVFSEntry::Rename(), and ADDON::CVFSEntry::Stat().
The documentation for this class was generated from the following file:
VFSEntry.cpp