Kodi Documentation: DXVA::CContext Class Reference
DXVA::CContext Class Reference
#include <DXVA.h>
Public Types
typedef std::shared_ptr< CContext > shared_ptr
typedef std::weak_ptr< CContext > weak_ptr
Public Member Functions
~CContext ()
bool GetFormatAndConfig (AVCodecContext *avctx, D3D11_VIDEO_DECODER_DESC &format, D3D11_VIDEO_DECODER_CONFIG &config) const
bool CreateSurfaces (const D3D11_VIDEO_DECODER_DESC &format, uint32_t count, uint32_t alignment, ID3D11VideoDecoderOutputView **surfaces, HANDLE *pHandle, bool trueShared) const
bool CreateDecoder (const D3D11_VIDEO_DECODER_DESC &format, const D3D11_VIDEO_DECODER_CONFIG &config, ID3D11VideoDecoder **decoder, ID3D11VideoContext **context)
void Release (CDecoder *decoder)
bool Check () const
bool Reset ()
bool IsContextShared () const
bool HasAMDWorkaround () const
Static Public Member Functions
static shared_ptr EnsureContext (CDecoder *decoder)
Private Member Functions
CContext ()=default
void Close ()
bool CreateContext ()
void DestroyContext ()
void QueryCaps ()
bool IsValidDecoder (CDecoder *decoder)
bool GetConfig (const D3D11_VIDEO_DECODER_DESC &format, D3D11_VIDEO_DECODER_CONFIG &config) const
Private Attributes
UINT m_input_count = 0
GUID * m_input_list = nullptr
bool m_atiWorkaround = false
bool m_sharingAllowed = false
Microsoft::WRL::ComPtr< ID3D11VideoContext > m_pD3D11Context
Microsoft::WRL::ComPtr< ID3D11VideoDevice > m_pD3D11Device
std::vector< CDecoder * > m_decoders
Static Private Attributes
static weak_ptr m_context
static CCriticalSection m_section
Member Typedef Documentation
shared_ptr
typedef std::shared_ptr<CContext> DXVA::CContext::shared_ptr
weak_ptr
typedef std::weak_ptr<CContext> DXVA::CContext::weak_ptr
Constructor & Destructor Documentation
~CContext()
CContext::~CContext ()
References Close().
CContext()
DXVA::CContext::CContext () explicit private default
Referenced by EnsureContext().
Member Function Documentation
Check()
bool CContext::Check () const
References m_pD3D11Context, and m_sharingAllowed.
Referenced by Reset().
Close()
void CContext::Close () private
References DestroyContext(), CLog::Log(), and LOGINFO.
Referenced by ~CContext().
CreateContext()
bool CContext::CreateContext () private
References FAILED, CWIN32Util::FormatHRESULT(), KODI::PLATFORM::WINDOWS::FromW(), DX::DeviceResources::Get(), GetCurrentProcess(), DX::GetFeatureLevelDescription(), CSysInfo::IsWindowsVersionAtLeast(), LOGDEBUG, LOGINFO, LOGWARNING, m_atiWorkaround, m_pD3D11Context, m_pD3D11Device, m_sharingAllowed, QueryCaps(), and CSysInfo::WindowsVersionWin10.
Referenced by Reset().
CreateDecoder()
bool CContext::CreateDecoder (const D3D11_VIDEO_DECODER_DESC & format, const D3D11_VIDEO_DECODER_CONFIG & config, ID3D11VideoDecoder ** decoder, ID3D11VideoContext ** context)
References FAILED, LOGERROR, LOGINFO, m_atiWorkaround, m_decoders, m_pD3D11Context, m_pD3D11Device, and m_section.
CreateSurfaces()
bool CContext::CreateSurfaces (const D3D11_VIDEO_DECODER_DESC & format, uint32_t count, uint32_t alignment, ID3D11VideoDecoderOutputView ** surfaces, HANDLE * pHandle, bool trueShared) const
References DX::DXGIFormatToString(), FAILED, CWIN32Util::FormatHRESULT(), INVALID_HANDLE_VALUE, CLog::Log(), LOGDEBUG, LOGERROR, m_pD3D11Context, and m_pD3D11Device.
DestroyContext()
void CContext::DestroyContext () private
References GetCurrentProcess(), m_input_list, m_pD3D11Context, and m_pD3D11Device.
Referenced by Close(), and Reset().
EnsureContext()
CContext::shared_ptr CContext::EnsureContext (CDecoder * decoder) static
References CContext(), EnsureContext(), m_context, and m_section.
Referenced by EnsureContext(), and DXVA::CDecoder::Open().
GetConfig()
bool CContext::GetConfig (const D3D11_VIDEO_DECODER_DESC & format, D3D11_VIDEO_DECODER_CONFIG & config) const private
References DX::DXGIFormatToString(), FAILED, CLog::Log(), LOGDEBUG, LOGINFO, and m_pD3D11Device.
Referenced by GetFormatAndConfig().
GetFormatAndConfig()
bool CContext::GetFormatAndConfig (AVCodecContext * avctx, D3D11_VIDEO_DECODER_DESC & format, D3D11_VIDEO_DECODER_CONFIG & config) const
References DX::DXGIFormatToString(), dxva2_modes, FAILED, GetConfig(), CLog::Log(), LOGDEBUG, LOGINFO, m_input_count, m_input_list, m_pD3D11Device, and render_targets_dxgi.
HasAMDWorkaround()
bool DXVA::CContext::HasAMDWorkaround () const inline
References m_atiWorkaround.
IsContextShared()
bool DXVA::CContext::IsContextShared () const inline
References m_sharingAllowed.
IsValidDecoder()
bool CContext::IsValidDecoder (CDecoder * decoder) private
References m_decoders.
QueryCaps()
void CContext::QueryCaps () private
References dxva2_find_mode(), FAILED, GUIDToString(), CLog::Log(), LOGDEBUG, LOGINFO, m_input_count, m_input_list, m_pD3D11Device, and dxva2_mode_t::name.
Referenced by CreateContext().
Release()
void CContext::Release (CDecoder * decoder)
References m_decoders, and m_section.
Reset()
bool CContext::Reset ()
References Check(), CreateContext(), DestroyContext(), DX::DeviceResources::Get(), and m_pD3D11Device.
Member Data Documentation
m_atiWorkaround
bool DXVA::CContext::m_atiWorkaround = false private
Referenced by CreateContext(), CreateDecoder(), and HasAMDWorkaround().
m_context
CContext::weak_ptr CContext::m_context static private
Referenced by EnsureContext().
m_decoders
std::vector<CDecoder*> DXVA::CContext::m_decoders private
Referenced by CreateDecoder(), IsValidDecoder(), and Release().
m_input_count
UINT DXVA::CContext::m_input_count = 0 private
Referenced by GetFormatAndConfig(), and QueryCaps().
m_input_list
GUID* DXVA::CContext::m_input_list = nullptr private
Referenced by DestroyContext(), GetFormatAndConfig(), and QueryCaps().
m_pD3D11Context
Microsoft::WRL::ComPtr<ID3D11VideoContext> DXVA::CContext::m_pD3D11Context private
Referenced by Check(), CreateContext(), CreateDecoder(), CreateSurfaces(), and DestroyContext().
m_pD3D11Device
Microsoft::WRL::ComPtr<ID3D11VideoDevice> DXVA::CContext::m_pD3D11Device private
Referenced by CreateContext(), CreateDecoder(), CreateSurfaces(), DestroyContext(), GetConfig(), GetFormatAndConfig(), QueryCaps(), and Reset().
m_section
CCriticalSection CContext::m_section static private
Referenced by CreateDecoder(), EnsureContext(), and Release().
m_sharingAllowed
bool DXVA::CContext::m_sharingAllowed = false private
Referenced by Check(), CreateContext(), and IsContextShared().
The documentation for this class was generated from the following files:
DXVA.h
DXVA.cpp