Kodi Documentation: PVR::CPVREpgSearchPath Class Reference
PVR::CPVREpgSearchPath Class Reference
#include <EpgSearchPath.h>
Public Member Functions
CPVREpgSearchPath (const std::string &strPath)
CPVREpgSearchPath (const CPVREpgSearchFilter &search)
bool IsValid () const
const std::string & GetPath () const
bool IsSearchRoot () const
bool IsRadio () const
bool IsSavedSearchesRoot () const
bool IsSavedSearch () const
int GetId () const
Static Public Attributes
static const std::string PATH_SEARCH_DIALOG = "pvr://search/search_dialog"
static const std::string PATH_TV_SEARCH = "pvr://search/tv/"
static const std::string PATH_TV_SAVEDSEARCHES = "pvr://search/tv/savedsearches/"
static const std::string PATH_RADIO_SEARCH = "pvr://search/radio/"
static const std::string PATH_RADIO_SAVEDSEARCHES = "pvr://search/radio/savedsearches/"
Private Member Functions
bool Init (const std::string &strPath)
Private Attributes
std::string m_path
bool m_bValid = false
bool m_bRoot = false
bool m_bRadio = false
bool m_bSavedSearchesRoot = false
bool m_bSavedSearch = false
int m_iId = -1
Constructor & Destructor Documentation
CPVREpgSearchPath() [1/2]
CPVREpgSearchPath::CPVREpgSearchPath (const std::string & strPath) explicit
References Init().
CPVREpgSearchPath() [2/2]
CPVREpgSearchPath::CPVREpgSearchPath (const CPVREpgSearchFilter & search) explicit
Member Function Documentation
GetId()
int PVR::CPVREpgSearchPath::GetId () const inline
References m_iId.
Referenced by PVR::CPVRGUIDirectory::GetDirectory(), and PVR::CGUIWindowPVRSearchBase::OnMessage().
GetPath()
const std::string & PVR::CPVREpgSearchPath::GetPath () const inline
References m_path.
Referenced by PVR::CPVREpgSearchFilter::GetPath().
Init()
bool CPVREpgSearchPath::Init (const std::string & strPath) private
References m_bRadio, m_bRoot, m_bSavedSearch, m_bSavedSearchesRoot, m_bValid, m_iId, m_path, URIUtils::RemoveSlashAtEnd(), and URIUtils::SplitPath().
Referenced by CPVREpgSearchPath().
IsRadio()
bool PVR::CPVREpgSearchPath::IsRadio () const inline
References m_bRadio.
Referenced by PVR::CPVRGUIDirectory::GetDirectory(), and PVR::CGUIWindowPVRSearchBase::OnMessage().
IsSavedSearch()
bool PVR::CPVREpgSearchPath::IsSavedSearch () const inline
References m_bSavedSearch.
Referenced by PVR::CPVRGUIDirectory::GetDirectory(), and PVR::CGUIWindowPVRSearchBase::OnMessage().
IsSavedSearchesRoot()
bool PVR::CPVREpgSearchPath::IsSavedSearchesRoot () const inline
References m_bSavedSearchesRoot.
Referenced by PVR::CGUIViewStateWindowPVRSearch::CGUIViewStateWindowPVRSearch(), PVR::CGUIWindowPVRSearchBase::ExecuteSearch(), PVR::CGUIWindowPVRSearchBase::GetContextButtons(), PVR::CPVRGUIDirectory::GetDirectory(), PVR::CGUIWindowPVRSearchBase::OnAction(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::Update(), and PVR::CGUIWindowPVRSearchBase::UpdateButtons().
IsSearchRoot()
bool PVR::CPVREpgSearchPath::IsSearchRoot () const inline
References m_bRoot.
Referenced by PVR::CGUIViewStateWindowPVRSearch::HideParentDirItems(), and PVR::CGUIWindowPVRSearchBase::OpenDialogSearch().
IsValid()
bool PVR::CPVREpgSearchPath::IsValid () const inline
References m_bValid.
Referenced by PVR::CGUIWindowPVRSearchBase::ExecuteSearch(), PVR::CGUIWindowPVRSearchBase::GetContextButtons(), PVR::CPVRGUIDirectory::GetDirectory(), PVR::CGUIWindowPVRSearchBase::OnAction(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), PVR::CGUIWindowPVRSearchBase::Update(), and PVR::CGUIWindowPVRSearchBase::UpdateButtons().
Member Data Documentation
m_bRadio
bool PVR::CPVREpgSearchPath::m_bRadio = false private
Referenced by Init(), and IsRadio().
m_bRoot
bool PVR::CPVREpgSearchPath::m_bRoot = false private
Referenced by Init(), and IsSearchRoot().
m_bSavedSearch
bool PVR::CPVREpgSearchPath::m_bSavedSearch = false private
Referenced by Init(), and IsSavedSearch().
m_bSavedSearchesRoot
bool PVR::CPVREpgSearchPath::m_bSavedSearchesRoot = false private
Referenced by Init(), and IsSavedSearchesRoot().
m_bValid
bool PVR::CPVREpgSearchPath::m_bValid = false private
Referenced by Init(), and IsValid().
m_iId
int PVR::CPVREpgSearchPath::m_iId = -1 private
Referenced by GetId(), and Init().
m_path
std::string PVR::CPVREpgSearchPath::m_path private
Referenced by GetPath(), and Init().
PATH_RADIO_SAVEDSEARCHES
const std::string CPVREpgSearchPath::PATH_RADIO_SAVEDSEARCHES = "pvr://search/radio/savedsearches/" static
Referenced by PVR::CGUIWindowPVRSearchBase::OnPrepareFileItems().
PATH_RADIO_SEARCH
const std::string CPVREpgSearchPath::PATH_RADIO_SEARCH = "pvr://search/radio/" static
Referenced by PVR::CGUIWindowPVRRadioSearch::GetDirectoryPath(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), PVR::CGUIWindowPVRRadioSearch::GetRootPath(), and PVR::CGUIWindowPVRRadioSearch::GetStartFolder().
PATH_SEARCH_DIALOG
const std::string CPVREpgSearchPath::PATH_SEARCH_DIALOG = "pvr://search/search_dialog" static
Referenced by PVR::CGUIWindowPVRSearchBase::OnMessage(), and PVR::CGUIWindowPVRSearchBase::OnPrepareFileItems().
PATH_TV_SAVEDSEARCHES
const std::string CPVREpgSearchPath::PATH_TV_SAVEDSEARCHES = "pvr://search/tv/savedsearches/" static
Referenced by PVR::CGUIWindowPVRSearchBase::OnPrepareFileItems().
PATH_TV_SEARCH
const std::string CPVREpgSearchPath::PATH_TV_SEARCH = "pvr://search/tv/" static
Referenced by PVR::CGUIWindowPVRTVSearch::GetDirectoryPath(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), PVR::CGUIWindowPVRTVSearch::GetRootPath(), and PVR::CGUIWindowPVRTVSearch::GetStartFolder().
The documentation for this class was generated from the following files:
EpgSearchPath.h
EpgSearchPath.cpp