Kodi Documentation: CRenderSystemGLES Class Reference
CRenderSystemGLES Class Reference abstract
#include <RenderSystemGLES.h>
Public Member Functions
CRenderSystemGLES ()
~CRenderSystemGLES () override=default
bool InitRenderSystem () override
bool DestroyRenderSystem () override
bool ResetRenderSystem (int width, int height) override
bool BeginRender () override
bool EndRender () override
void PresentRender (bool rendered, bool videoLayer) override
void InvalidateColorBuffer () override
bool ClearBuffers (KODI::UTILS::COLOR::Color color) override
bool IsExtSupported (const char *extension) const override
void SetVSync (bool vsync)
void ResetVSync ()
void SetViewPort (const CRect &viewPort) override
void GetViewPort (CRect &viewPort) override
bool ScissorsCanEffectClipping () override
CRect ClipRectToScissorRect (const CRect &rect) override
void SetScissors (const CRect &rect) override
void ResetScissors () override
void SetDepthCulling (DEPTH_CULLING culling) override
void CaptureStateBlock () override
void ApplyStateBlock () override
void SetCameraPosition (const CPoint &camera, int screenWidth, int screenHeight, float stereoFactor=0.0f) override
bool SupportsStereo (RENDER_STEREO_MODE mode) const override
void Project (float &x, float &y, float &z) override
std::string GetShaderPath (const std::string &filename) override
void InitialiseShaders ()
void ReleaseShaders ()
void EnableGUIShader (ShaderMethodGLES method)
void DisableGUIShader ()
GLint GUIShaderGetPos ()
GLint GUIShaderGetCol ()
GLint GUIShaderGetCoord0 ()
GLint GUIShaderGetCoord1 ()
GLint GUIShaderGetUniCol ()
GLint GUIShaderGetCoord0Matrix ()
GLint GUIShaderGetField ()
GLint GUIShaderGetStep ()
GLint GUIShaderGetContrast ()
GLint GUIShaderGetBrightness ()
GLint GUIShaderGetModel ()
GLint GUIShaderGetMatrix ()
GLint GUIShaderGetClip ()
GLint GUIShaderGetCoordStep ()
GLint GUIShaderGetDepth ()
Public Member Functions inherited from CRenderSystemBase
CRenderSystemBase ()
virtual ~CRenderSystemBase ()
virtual void RestoreViewPort ()
virtual void SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view)
void GetRenderVersion (unsigned int &major, unsigned int &minor) const
const std::string & GetRenderVendor () const
const std::string & GetRenderRenderer () const
const std::string & GetRenderVersionString () const
virtual bool SupportsNPOT (bool dxt) const
unsigned int GetMaxTextureSize () const
unsigned int GetMinDXTPitch () const
virtual void ShowSplash (const std::string &message)
Protected Member Functions
virtual void SetVSyncImpl (bool enable)=0
virtual void PresentRenderImpl (bool rendered)=0
void CalculateMaxTexturesize ()
Protected Attributes
bool m_bVsyncInit {false}
int m_width
int m_height
std::string m_RenderExtensions
std::map< ShaderMethodGLES, std::unique_ptr< CGLESShader > > m_pShader
ShaderMethodGLES m_method = ShaderMethodGLES::SM_DEFAULT
GLint m_viewPort [4]
Protected Attributes inherited from CRenderSystemBase
bool m_bRenderCreated
bool m_bVSync
unsigned int m_maxTextureSize
unsigned int m_minDXTPitch
std::string m_RenderRenderer
std::string m_RenderVendor
std::string m_RenderVersion
int m_RenderVersionMinor
int m_RenderVersionMajor
RENDER_STEREO_VIEW m_stereoView = RENDER_STEREO_VIEW_OFF
RENDER_STEREO_MODE m_stereoMode = RENDER_STEREO_MODE_OFF
bool m_limitedColorRange = false
bool m_transferPQ {false}
std::unique_ptr< CGUIImage > m_splashImage
std::unique_ptr< CGUITextLayout > m_splashMessageLayout
Constructor & Destructor Documentation
CRenderSystemGLES()
CRenderSystemGLES::CRenderSystemGLES ()
~CRenderSystemGLES()
CRenderSystemGLES::~CRenderSystemGLES () override default
Member Function Documentation
ApplyStateBlock()
void CRenderSystemGLES::ApplyStateBlock () override virtual
Implements CRenderSystemBase.
References glMatrixModview, glMatrixProject, glMatrixTexture, CRenderSystemBase::m_bRenderCreated, and CMatrixGLStack::PopLoad().
BeginRender()
bool CRenderSystemGLES::BeginRender () override virtual
Implements CRenderSystemBase.
Reimplemented in CWinSystemIOS, and CWinSystemTVOS.
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), InitialiseShaders(), CGraphicContext::IsTransferPQ(), CRenderSystemBase::m_bRenderCreated, CRenderSystemBase::m_limitedColorRange, CRenderSystemBase::m_transferPQ, ReleaseShaders(), and CWinSystemBase::UseLimitedColor().
Referenced by CWinSystemIOS::BeginRender(), and CWinSystemTVOS::BeginRender().
CalculateMaxTexturesize()
void CRenderSystemGLES::CalculateMaxTexturesize () protected
References CLog::Log(), LOGINFO, and CRenderSystemBase::m_maxTextureSize.
Referenced by ResetRenderSystem().
CaptureStateBlock()
void CRenderSystemGLES::CaptureStateBlock () override virtual
Todo:
NOTE: Only for Screensavers & Visualisations
Implements CRenderSystemBase.
References glMatrixModview, glMatrixProject, glMatrixTexture, CRenderSystemBase::m_bRenderCreated, and CMatrixGLStack::Push().
ClearBuffers()
bool CRenderSystemGLES::ClearBuffers (KODI::UTILS::COLOR::Color color) override virtual
Implements CRenderSystemBase.
References KODI::UTILS::GL::A, KODI::UTILS::GL::B, color, KODI::UTILS::GL::G, KODI::UTILS::GL::GetChannelFromARGB(), CServiceBroker::GetSettingsComponent(), CRenderSystemBase::m_bRenderCreated, and KODI::UTILS::GL::R.
Referenced by DestroyRenderSystem(), and InvalidateColorBuffer().
ClipRectToScissorRect()
CRect CRenderSystemGLES::ClipRectToScissorRect (const CRect & rect) override virtual
Reimplemented from CRenderSystemBase.
References m_method, m_pShader, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUIFontTTFGLES::LastEnd().
DestroyRenderSystem()
bool CRenderSystemGLES::DestroyRenderSystem () override virtual
Implements CRenderSystemBase.
References ClearBuffers(), CServiceBroker::GetWinSystem(), CRenderSystemBase::m_bRenderCreated, PresentRenderImpl(), ReleaseShaders(), and ResetScissors().
DisableGUIShader()
void CRenderSystemGLES::DisableGUIShader ()
References m_method, m_pShader, and SM_DEFAULT.
Referenced by CLinuxRendererGLES::ClearBackBufferQuad(), KODI::RETRO::CRenderContext::DisableGUIShader(), CRendererDRMPRIMEGLES::DrawBlackBars(), CLinuxRendererGLES::DrawBlackBars(), CGUITextureGLES::DrawQuad(), CGUITextureGLES::End(), CGUIFontTTFGLES::LastEnd(), CSlideShowPicGLES::Render(), OVERLAY::COverlayTextureGLES::Render(), OVERLAY::COverlayGlyphGLES::Render(), CRendererDRMPRIMEGLES::Render(), and CRendererMediaCodec::RenderHook().
EnableGUIShader()
void CRenderSystemGLES::EnableGUIShader (ShaderMethodGLES method)
References CLog::Log(), LOGERROR, m_method, and m_pShader.
Referenced by CGUITextureGLES::Begin(), CLinuxRendererGLES::ClearBackBufferQuad(), CRendererDRMPRIMEGLES::DrawBlackBars(), CLinuxRendererGLES::DrawBlackBars(), CGUITextureGLES::DrawQuad(), KODI::RETRO::CRenderContext::EnableGUIShader(), CGUIFontTTFGLES::FirstBegin(), CSlideShowPicGLES::Render(), OVERLAY::COverlayTextureGLES::Render(), OVERLAY::COverlayGlyphGLES::Render(), CRendererDRMPRIMEGLES::Render(), and CRendererMediaCodec::RenderHook().
EndRender()
bool CRenderSystemGLES::EndRender () override virtual
Implements CRenderSystemBase.
Reimplemented in CWinSystemIOS, and CWinSystemTVOS.
References CRenderSystemBase::m_bRenderCreated.
Referenced by CWinSystemIOS::EndRender(), and CWinSystemTVOS::EndRender().
GetShaderPath()
std::string CRenderSystemGLES::GetShaderPath (const std::string & filename) override virtual
Reimplemented from CRenderSystemBase.
References CFileUtils::Exists(), CURL::Get(), CRenderSystemBase::m_RenderVersionMajor, and CRenderSystemBase::m_RenderVersionMinor.
GetViewPort()
void CRenderSystemGLES::GetViewPort (CRect & viewPort) override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_height, m_viewPort, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CLinuxRendererGLES::RenderToFBO().
GUIShaderGetBrightness()
GLint CRenderSystemGLES::GUIShaderGetBrightness ()
References m_method, and m_pShader.
Referenced by CRendererMediaCodec::RenderHook().
GUIShaderGetClip()
GLint CRenderSystemGLES::GUIShaderGetClip ()
References m_method, and m_pShader.
Referenced by CGUIFontTTFGLES::LastEnd().
GUIShaderGetCol()
GLint CRenderSystemGLES::GUIShaderGetCol ()
References m_method, and m_pShader.
Referenced by CGUIFontTTFGLES::LastEnd(), OVERLAY::COverlayTextureGLES::Render(), and OVERLAY::COverlayGlyphGLES::Render().
GUIShaderGetContrast()
GLint CRenderSystemGLES::GUIShaderGetContrast ()
References m_method, and m_pShader.
Referenced by CRendererMediaCodec::RenderHook().
GUIShaderGetCoord0()
GLint CRenderSystemGLES::GUIShaderGetCoord0 ()
References m_method, and m_pShader.
Referenced by CGUITextureGLES::DrawQuad(), CGUITextureGLES::End(), KODI::RETRO::CRenderContext::GUIShaderGetCoord0(), CGUIFontTTFGLES::LastEnd(), CSlideShowPicGLES::Render(), OVERLAY::COverlayTextureGLES::Render(), OVERLAY::COverlayGlyphGLES::Render(), CRendererDRMPRIMEGLES::Render(), and CRendererMediaCodec::RenderHook().
GUIShaderGetCoord0Matrix()
GLint CRenderSystemGLES::GUIShaderGetCoord0Matrix ()
References m_method, and m_pShader.
Referenced by CRendererMediaCodec::RenderHook().
GUIShaderGetCoord1()
GLint CRenderSystemGLES::GUIShaderGetCoord1 ()
References m_method, and m_pShader.
Referenced by CGUITextureGLES::End().
GUIShaderGetCoordStep()
GLint CRenderSystemGLES::GUIShaderGetCoordStep ()
References m_method, and m_pShader.
Referenced by CGUIFontTTFGLES::LastEnd().
GUIShaderGetDepth()
GLint CRenderSystemGLES::GUIShaderGetDepth ()
References m_method, and m_pShader.
Referenced by CLinuxRendererGLES::ClearBackBufferQuad(), CRendererDRMPRIMEGLES::DrawBlackBars(), CLinuxRendererGLES::DrawBlackBars(), CGUITextureGLES::DrawQuad(), CGUITextureGLES::End(), KODI::RETRO::CRenderContext::GUIShaderGetDepth(), CGUIFontTTFGLES::LastEnd(), CSlideShowPicGLES::Render(), OVERLAY::COverlayTextureGLES::Render(), OVERLAY::COverlayGlyphGLES::Render(), CRendererDRMPRIMEGLES::Render(), and CRendererMediaCodec::RenderHook().
GUIShaderGetField()
GLint CRenderSystemGLES::GUIShaderGetField ()
References m_method, and m_pShader.
Referenced by CRendererMediaCodec::RenderHook().
GUIShaderGetMatrix()
GLint CRenderSystemGLES::GUIShaderGetMatrix ()
References m_method, and m_pShader.
Referenced by CGUIFontTTFGLES::LastEnd(), and OVERLAY::COverlayGlyphGLES::Render().
GUIShaderGetModel()
GLint CRenderSystemGLES::GUIShaderGetModel ()
References m_method, and m_pShader.
GUIShaderGetPos()
GLint CRenderSystemGLES::GUIShaderGetPos ()
References m_method, and m_pShader.
Referenced by CLinuxRendererGLES::ClearBackBufferQuad(), CRendererDRMPRIMEGLES::DrawBlackBars(), CLinuxRendererGLES::DrawBlackBars(), CGUITextureGLES::DrawQuad(), CGUITextureGLES::End(), KODI::RETRO::CRenderContext::GUIShaderGetPos(), CGUIFontTTFGLES::LastEnd(), CSlideShowPicGLES::Render(), OVERLAY::COverlayTextureGLES::Render(), OVERLAY::COverlayGlyphGLES::Render(), CRendererDRMPRIMEGLES::Render(), and CRendererMediaCodec::RenderHook().
GUIShaderGetStep()
GLint CRenderSystemGLES::GUIShaderGetStep ()
References m_method, and m_pShader.
Referenced by CRendererMediaCodec::RenderHook().
GUIShaderGetUniCol()
GLint CRenderSystemGLES::GUIShaderGetUniCol ()
References m_method, and m_pShader.
Referenced by CLinuxRendererGLES::ClearBackBufferQuad(), CRendererDRMPRIMEGLES::DrawBlackBars(), CLinuxRendererGLES::DrawBlackBars(), CGUITextureGLES::DrawQuad(), CGUITextureGLES::End(), KODI::RETRO::CRenderContext::GUIShaderGetUniCol(), CSlideShowPicGLES::Render(), and OVERLAY::COverlayTextureGLES::Render().
InitialiseShaders()
void CRenderSystemGLES::InitialiseShaders ()
References CServiceBroker::GetWinSystem(), IsExtSupported(), CLog::Log(), LOGERROR, CRenderSystemBase::m_limitedColorRange, m_pShader, CRenderSystemBase::m_transferPQ, SM_DEFAULT, SM_FONTS, SM_FONTS_SHADER_CLIP, SM_MULTI, SM_MULTI_BLENDCOLOR, SM_TEXTURE, SM_TEXTURE_NOALPHA, SM_TEXTURE_NOBLEND, SM_TEXTURE_RGBA, SM_TEXTURE_RGBA_BLENDCOLOR, SM_TEXTURE_RGBA_BOB, SM_TEXTURE_RGBA_BOB_OES, SM_TEXTURE_RGBA_OES, and CWinSystemBase::UseLimitedColor().
Referenced by BeginRender(), and InitRenderSystem().
InitRenderSystem()
bool CRenderSystemGLES::InitRenderSystem () override virtual
Implements CRenderSystemBase.
References CServiceBroker::GetSettingsComponent(), KODI::UTILS::GL::GlErrorCallback(), InitialiseShaders(), IsExtSupported(), CLog::Log(), LOGDEBUG, LOGFATAL, LogGraphicsInfo(), CRenderSystemBase::m_bRenderCreated, CRenderSystemBase::m_maxTextureSize, m_RenderExtensions, CRenderSystemBase::m_RenderRenderer, CRenderSystemBase::m_RenderVendor, CRenderSystemBase::m_RenderVersion, CRenderSystemBase::m_RenderVersionMajor, CRenderSystemBase::m_RenderVersionMinor, and CGUITextureGLES::Register().
InvalidateColorBuffer()
void CRenderSystemGLES::InvalidateColorBuffer () override virtual
Reimplemented from CRenderSystemBase.
References ClearBuffers(), CServiceBroker::GetSettingsComponent(), and CRenderSystemBase::m_bRenderCreated.
IsExtSupported()
bool CRenderSystemGLES::IsExtSupported (const char * extension) const override virtual
Implements CRenderSystemBase.
Reimplemented in CWinSystemIOS, CWinSystemTVOS, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
References m_RenderExtensions, and name.
Referenced by CLinuxRendererGLES::CLinuxRendererGLES(), InitialiseShaders(), InitRenderSystem(), CWinSystemIOS::IsExtSupported(), CWinSystemTVOS::IsExtSupported(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::IsExtSupported(), and LoadTexture().
PresentRender()
void CRenderSystemGLES::PresentRender (bool rendered, bool videoLayer) override virtual
Implements CRenderSystemBase.
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbmGLESContext.
References CRenderSystemBase::m_bRenderCreated, PresentRenderImpl(), SetVSync(), and KODI::TIME::Sleep().
PresentRenderImpl()
virtual void CRenderSystemGLES::PresentRenderImpl (bool rendered) protected pure virtual
Implemented in CWinSystemAndroidGLESContext, KODI::WINDOWING::GBM::CWinSystemGbmGLESContext, CWinSystemIOS, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
Referenced by DestroyRenderSystem(), and PresentRender().
Project()
void CRenderSystemGLES::Project (float & x, float & y, float & z) override virtual
Project (x,y,z) 3d scene coordinates to (x,y) 2d screen coordinates
Reimplemented from CRenderSystemBase.
References CMatrixGLStack::Get(), glMatrixModview, glMatrixProject, m_viewPort, and CMatrixGL::Project().
ReleaseShaders()
void CRenderSystemGLES::ReleaseShaders ()
References m_pShader, SM_DEFAULT, SM_FONTS, SM_FONTS_SHADER_CLIP, SM_MULTI, SM_MULTI_BLENDCOLOR, SM_TEXTURE, SM_TEXTURE_NOALPHA, SM_TEXTURE_NOBLEND, SM_TEXTURE_RGBA, SM_TEXTURE_RGBA_BLENDCOLOR, SM_TEXTURE_RGBA_BOB, SM_TEXTURE_RGBA_BOB_OES, and SM_TEXTURE_RGBA_OES.
Referenced by BeginRender(), and DestroyRenderSystem().
ResetRenderSystem()
bool CRenderSystemGLES::ResetRenderSystem (int width, int height) override virtual
Implements CRenderSystemBase.
References CalculateMaxTexturesize(), CMatrixGLStack::Clear(), glMatrixModview, glMatrixProject, glMatrixTexture, CMatrixGLStack::Load(), CMatrixGL::LoadIdentity(), m_height, m_width, CMatrixGL::Ortho(), and SetViewPort().
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLESContext::FinishWindowResize(), CWinSystemAndroidGLESContext::ResizeWindow(), CWinSystemIOS::ResizeWindow(), CWinSystemTVOS::ResizeWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::ResizeWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::SetContextSize(), CWinSystemAndroidGLESContext::SetFullScreen(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::SetFullScreen(), CWinSystemIOS::SetFullScreen(), CWinSystemTVOS::SetFullScreen(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetFullScreen().
ResetScissors()
void CRenderSystemGLES::ResetScissors () override virtual
Implements CRenderSystemBase.
References m_height, m_width, and SetScissors().
Referenced by DestroyRenderSystem(), CGUIFontTTFGLES::FirstBegin(), and CGUIFontTTFGLES::LastEnd().
ResetVSync()
void CRenderSystemGLES::ResetVSync () inline
References m_bVsyncInit.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow().
ScissorsCanEffectClipping()
bool CRenderSystemGLES::ScissorsCanEffectClipping () override virtual
Reimplemented from CRenderSystemBase.
References m_method, and m_pShader.
Referenced by CGUIFontTTFGLES::FirstBegin().
SetCameraPosition()
void CRenderSystemGLES::SetCameraPosition (const CPoint & camera, int screenWidth, int screenHeight, float stereoFactor = 0.0f) override virtual
Implements CRenderSystemBase.
References CMatrixGL::Frustum(), glMatrixModview, glMatrixProject, CMatrixGLStack::Load(), CMatrixGL::LoadIdentity(), CMatrixGL::LookAt(), CRenderSystemBase::m_bRenderCreated, m_viewPort, CMatrixGL::Translatef(), CPointGen< T >::x, and CPointGen< T >::y.
SetDepthCulling()
void CRenderSystemGLES::SetDepthCulling (DEPTH_CULLING culling) override virtual
Reimplemented from CRenderSystemBase.
References DEPTH_CULLING_BACK_TO_FRONT, DEPTH_CULLING_FRONT_TO_BACK, and DEPTH_CULLING_OFF.
SetScissors()
void CRenderSystemGLES::SetScissors (const CRect & rect) override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_height, MathUtils::round_int(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUIFontTTFGLES::LastEnd(), and ResetScissors().
SetViewPort()
void CRenderSystemGLES::SetViewPort (const CRect & viewPort) override virtual
Implements CRenderSystemBase.
References CRectGen< T >::Height(), CRenderSystemBase::m_bRenderCreated, m_height, m_viewPort, CRectGen< T >::Width(), CRectGen< T >::x1, and CRectGen< T >::y1.
Referenced by CLinuxRendererGLES::RenderToFBO(), and ResetRenderSystem().
SetVSync()
void CRenderSystemGLES::SetVSync (bool vsync)
References CLog::Log(), LOGINFO, CRenderSystemBase::m_bRenderCreated, m_bVsyncInit, and SetVSyncImpl().
Referenced by PresentRender().
SetVSyncImpl()
virtual void CRenderSystemGLES::SetVSyncImpl (bool enable) protected pure virtual
Implemented in CWinSystemAndroidGLESContext, KODI::WINDOWING::GBM::CWinSystemGbmGLESContext, CWinSystemIOS, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
Referenced by SetVSync().
SupportsStereo()
bool CRenderSystemGLES::SupportsStereo (RENDER_STEREO_MODE mode) const override virtual
Reimplemented from CRenderSystemBase.
References CRenderSystemBase::SupportsStereo().
Member Data Documentation
m_bVsyncInit
bool CRenderSystemGLES::m_bVsyncInit {false} protected
Referenced by ResetVSync(), and SetVSync().
m_height
int CRenderSystemGLES::m_height protected
Referenced by GetViewPort(), ResetRenderSystem(), ResetScissors(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::SetContextSize(), SetScissors(), and SetViewPort().
m_method
ShaderMethodGLES CRenderSystemGLES::m_method = ShaderMethodGLES::SM_DEFAULT protected
Referenced by ClipRectToScissorRect(), DisableGUIShader(), EnableGUIShader(), GUIShaderGetBrightness(), GUIShaderGetClip(), GUIShaderGetCol(), GUIShaderGetContrast(), GUIShaderGetCoord0(), GUIShaderGetCoord0Matrix(), GUIShaderGetCoord1(), GUIShaderGetCoordStep(), GUIShaderGetDepth(), GUIShaderGetField(), GUIShaderGetMatrix(), GUIShaderGetModel(), GUIShaderGetPos(), GUIShaderGetStep(), GUIShaderGetUniCol(), and ScissorsCanEffectClipping().
m_pShader
std::map<ShaderMethodGLES, std::unique_ptr<CGLESShader> > CRenderSystemGLES::m_pShader protected
Referenced by ClipRectToScissorRect(), DisableGUIShader(), EnableGUIShader(), GUIShaderGetBrightness(), GUIShaderGetClip(), GUIShaderGetCol(), GUIShaderGetContrast(), GUIShaderGetCoord0(), GUIShaderGetCoord0Matrix(), GUIShaderGetCoord1(), GUIShaderGetCoordStep(), GUIShaderGetDepth(), GUIShaderGetField(), GUIShaderGetMatrix(), GUIShaderGetModel(), GUIShaderGetPos(), GUIShaderGetStep(), GUIShaderGetUniCol(), InitialiseShaders(), ReleaseShaders(), and ScissorsCanEffectClipping().
m_RenderExtensions
std::string CRenderSystemGLES::m_RenderExtensions protected
Referenced by InitRenderSystem(), and IsExtSupported().
m_viewPort
GLint CRenderSystemGLES::m_viewPort[4] protected
Referenced by GetViewPort(), Project(), SetCameraPosition(), and SetViewPort().
m_width
int CRenderSystemGLES::m_width protected
Referenced by ResetRenderSystem(), ResetScissors(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::SetContextSize().
The documentation for this class was generated from the following files:
RenderSystemGLES.h
RenderSystemGLES.cpp