Kodi Documentation: KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop Class Reference
KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop Class Reference
#include <OSScreenSaverFreedesktop.h>
Public Member Functions
COSScreenSaverFreedesktop ()=default
void Inhibit () override
void Uninhibit () override
Public Member Functions inherited from KODI::WINDOWING::IOSScreenSaver
virtual ~IOSScreenSaver ()=default
Static Public Member Functions
static bool IsAvailable ()
Private Attributes
bool m_inhibited {false}
std::uint32_t m_cookie
Constructor & Destructor Documentation
COSScreenSaverFreedesktop()
KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::COSScreenSaverFreedesktop () default
Member Function Documentation
Inhibit()
void COSScreenSaverFreedesktop::Inhibit () override virtual
Do not allow the OS screen saver to become active
Calling this function multiple times without calling Unhibit MUST NOT produce any side-effects.
Implements KODI::WINDOWING::IOSScreenSaver.
References CDBusMessage::AppendArguments(), g_localizeStrings, CLocalizeStrings::Get(), CCompileInfo::GetAppName(), CDBusMessage::GetReplyArguments(), CLog::Log(), LOGERROR, m_cookie, m_inhibited, and CDBusMessage::SendSession().
IsAvailable()
bool COSScreenSaverFreedesktop::IsAvailable () static
References CDBusError::Name(), and CDBusMessage::SendSession().
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetOSScreenSaverImpl().
Uninhibit()
void COSScreenSaverFreedesktop::Uninhibit () override virtual
Allow the OS screen saver to become active again
Calling this function multiple times or at all without calling Inhibit MUST NOT produce any side-effects.
Implements KODI::WINDOWING::IOSScreenSaver.
References CDBusMessage::AppendArgument(), CLog::Log(), LOGERROR, m_cookie, m_inhibited, and CDBusMessage::SendSession().
Member Data Documentation
m_cookie
std::uint32_t KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::m_cookie private
Referenced by Inhibit(), and Uninhibit().
m_inhibited
bool KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::m_inhibited {false} private
Referenced by Inhibit(), and Uninhibit().
The documentation for this class was generated from the following files:
OSScreenSaverFreedesktop.h
OSScreenSaverFreedesktop.cpp