Kodi Documentation: KODI::VIDEO Namespace Reference
KODI::VIDEO Namespace Reference
Namespaces
namespace anonymous_namespace{VideoEmbeddedImageFileLoader.cpp}
namespace anonymous_namespace{VideoGeneratedImageFileLoader.cpp}
namespace anonymous_namespace{VideoItemArtworkHandler.cpp}
namespace GUILIB
namespace TAGS
namespace UTILS
Classes
class CVideoEmbeddedImageFileLoader
Generates a texture for an image embedded in a video file.
class CVideoGeneratedImageFileLoader
Generates a texture for a thumbnail of a video file, for a specific chapter or from a frame approx 1/3 into the video.
class CVideoInfoScanner
class CVideoInfoTagLoaderFactory
struct EPISODE
class IVideoInfoTagLoader
Base class for video tag loaders.
class IVideoItemArtworkHandler
class IVideoItemArtworkHandlerFactory
struct SScanSettings
Typedefs
typedef std::vector< EPISODE > EPISODELIST
typedef struct KODI::VIDEO::SScanSettings SScanSettings
Functions
bool IsBDFile (const CFileItem &item)
Check whether an item is a blu-ray file.
bool IsDiscStub (const CFileItem &item)
Check whether an item is a disc stub.
bool IsDVDFile (const CFileItem &item, bool bVobs=true, bool bIfos=true)
Check whether an item is a DVD file.
bool IsProtectedBlurayDisc (const CFileItem &item)
Checks whether item points to a protected blu-ray disc.
bool IsBlurayPlaylist (const CFileItem &item)
Checks whether item points to a blu-ray playlist (.mpls)
bool IsSubtitle (const CFileItem &item)
Check whether an item is a subtitle file.
bool IsVideo (const CFileItem &item)
Check whether an item is a video item.
bool IsVideoAssetFile (const CFileItem &item)
Is the item a video asset, excluding folders.
bool IsVideoDb (const CFileItem &item)
Check whether an item is a video database item.
bool IsVideoExtrasFolder (const CFileItem &item)
Check whether an item is a video extras folder item.
static void OnDirectoryScanned (const std::string &strDirectory)
std::string ContentToMediaType (CONTENT_TYPE content, bool folder)
VideoDbContentType ContentToVideoDbType (CONTENT_TYPE content)
Typedef Documentation
EPISODELIST
typedef std::vector<EPISODE> KODI::VIDEO::EPISODELIST
SScanSettings
typedef struct KODI::VIDEO::SScanSettings KODI::VIDEO::SScanSettings
Function Documentation
ContentToMediaType()
std::string KODI::VIDEO::ContentToMediaType (CONTENT_TYPE content, bool folder)
References ADDON::content, CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_TVSHOWS, ContentToMediaType(), MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, and MediaTypeTvShow.
Referenced by ContentToMediaType(), and KODI::VIDEO::CVideoInfoScanner::GetArtwork().
ContentToVideoDbType()
VideoDbContentType KODI::VIDEO::ContentToVideoDbType (CONTENT_TYPE content)
References ADDON::content, CONTENT_MOVIES, CONTENT_MUSICVIDEOS, CONTENT_TVSHOWS, ContentToVideoDbType(), EPISODES, MOVIES, MUSICVIDEOS, and UNKNOWN.
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideoExtras(), and ContentToVideoDbType().
IsBDFile()
bool KODI::VIDEO::IsBDFile (const CFileItem & item)
Check whether an item is a blu-ray file.
References CFileItem::GetDynPath(), and URIUtils::GetFileName().
IsBlurayPlaylist()
bool KODI::VIDEO::IsBlurayPlaylist (const CFileItem & item)
Checks whether item points to a blu-ray playlist (.mpls)
References CFileItem::GetDynPath(), and URIUtils::GetExtension().
Referenced by CSaveFileState::DoWork(), CVideoDatabase::GetPlayCount(), and CVideoDatabase::SetPlayCount().
IsDiscStub()
bool KODI::VIDEO::IsDiscStub (const CFileItem & item)
Check whether an item is a disc stub.
References CFileExtensionProvider::GetDiscStubExtensions(), CServiceBroker::GetFileExtensionProvider(), CFileItem::GetPath(), CFileItem::GetVideoInfoTag(), URIUtils::HasExtension(), CFileItem::HasVideoInfoTag(), IsDiscStub(), IsVideoDb(), CGUIListItem::m_bIsFolder, CVideoInfoTag::m_strFileNameAndPath, and CVideoInfoTag::m_strPath.
Referenced by IsDiscStub().
IsDVDFile()
bool KODI::VIDEO::IsDVDFile (const CFileItem & item, bool bVobs, bool bIfos)
Check whether an item is a DVD file.
References CFileItem::GetDynPath(), and URIUtils::GetFileName().
IsProtectedBlurayDisc()
bool KODI::VIDEO::IsProtectedBlurayDisc (const CFileItem & item)
Checks whether item points to a protected blu-ray disc.
References URIUtils::AddFileToFolder(), CFileUtils::Exists(), and CFileItem::GetPath().
IsSubtitle()
bool KODI::VIDEO::IsSubtitle (const CFileItem & item)
Check whether an item is a subtitle file.
References CServiceBroker::GetFileExtensionProvider(), CFileItem::GetPath(), CFileExtensionProvider::GetSubtitleExtensions(), and URIUtils::HasExtension().
IsVideo()
bool KODI::VIDEO::IsVideo (const CFileItem & item)
Check whether an item is a video item.
Note that this returns true for anything with a video info tag, so that may include eg. folders.
Todo:
If the file is a zip file, ask the game clients if any support this
References CServiceBroker::GetFileExtensionProvider(), CFileItem::GetMimeType(), CFileItem::GetPath(), CFileExtensionProvider::GetVideoExtensions(), URIUtils::HasExtension(), CFileItem::HasGameInfoTag(), CFileItem::HasMusicInfoTag(), CFileItem::HasPictureInfoTag(), CFileItem::HasVideoInfoTag(), URIUtils::IsDVD(), CFileItem::IsPVR(), URIUtils::IsPVRTVRecordingFileOrFolder(), and CGUIListItem::m_bIsFolder.
Referenced by CGUIWindowSlideShow::Add(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::AddItemPathToFileBrowserSources(), CSaveFileState::DoWork(), KODI::ART::FillInDefaultIcon(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetBool(), CGUIWindowSlideShow::GetDisplayEffect(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::VIDEO::CVideoInfoScanner::GetPathHash(), CGUIWindowSlideShow::GetPicturePath(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::InitCurrentItem(), KODI::VIDEO::UTILS::IsItemPlayable(), KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListASX::LoadAsxIniInfo(), CGUIWindowSlideShow::OnAction(), CGUIDialogVideoBookmarks::OnAddBookmark(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), KODI::PLAYLIST::CPlayListPlayer::Play(), CGUIWindowSlideShow::PlayVideo(), CGUIWindowSlideShow::Process(), CGUIWindowSlideShow::Render(), CGUIWindowSlideShow::RenderEx(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), and KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo().
IsVideoAssetFile()
bool KODI::VIDEO::IsVideoAssetFile (const CFileItem & item)
Is the item a video asset, excluding folders.
Parameters
[in] item the item
Returns
true if it is, false otherwise
References CURL, CFileItem::GetPath(), IsVideoDb(), and CGUIListItem::m_bIsFolder.
IsVideoDb()
bool KODI::VIDEO::IsVideoDb (const CFileItem & item)
Check whether an item is a video database item.
References CFileItem::GetPath(), and URIUtils::IsVideoDb().
Referenced by CVideoDatabase::AddFile(), CVideoFileItemListModifier::AddQueuingFolder(), CVideoFileItemListModifier::CanModify(), UPNP::CUPnPServer::DefaultSortItems(), CSaveFileState::DoWork(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), KODI::ART::GetLocalFanart(), IsDiscStub(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), IsVideoAssetFile(), UPNP::CUPnPServer::OnBrowseMetadata(), CXBMCApp::onNewIntent(), UPNP::CUPnPServer::OnUpdateObject(), KODI::PLAYLIST::CPlayListPlayer::Play(), KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::Process(), and KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions().
IsVideoExtrasFolder()
bool KODI::VIDEO::IsVideoExtrasFolder (const CFileItem & item)
Check whether an item is a video extras folder item.
References URIUtils::GetFileOrFolderName(), CFileItem::GetPath(), and CGUIListItem::m_bIsFolder.
Referenced by KODI::VIDEO::CVideoInfoScanner::DoScan().
OnDirectoryScanned()
static void KODI::VIDEO::OnDirectoryScanned (const std::string & strDirectory) static
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_DIRECTORY_SCANNED, and CGUIMessage::SetStringParam().
Referenced by KODI::VIDEO::CVideoInfoScanner::DoScan(), and KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder().