Kodi Documentation: KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation Class Reference
KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation Class Reference
#include <VideoSyncWpPresentation.h>
Public Member Functions
CVideoSyncWpPresentation (CVideoReferenceClock *clock, CWinSystemWayland &winSystem)
float GetFps () override
bool Setup () override
void Run (CEvent &stop) override
void Cleanup () override
Public Member Functions inherited from CVideoSync
CVideoSync (CVideoReferenceClock *clock)
virtual ~CVideoSync ()=default
virtual void RefreshChanged ()
Private Member Functions
void HandlePresentation (timespec tv, std::uint32_t refresh, std::uint32_t syncOutputID, float syncOutputRefreshRate, std::uint64_t msc)
Private Attributes
CEvent m_stopEvent
CSignalRegistration m_presentationHandler
std::uint64_t m_lastMsc {}
std::uint32_t m_syncOutputID {}
CWinSystemWayland & m_winSystem
Additional Inherited Members
Protected Attributes inherited from CVideoSync
float m_fps
CVideoReferenceClock * m_refClock
Constructor & Destructor Documentation
CVideoSyncWpPresentation()
CVideoSyncWpPresentation::CVideoSyncWpPresentation (CVideoReferenceClock * clock, CWinSystemWayland & winSystem) explicit
Member Function Documentation
Cleanup()
void CVideoSyncWpPresentation::Cleanup () override virtual
Implements CVideoSync.
GetFps()
float CVideoSyncWpPresentation::GetFps () override virtual
Implements CVideoSync.
References CVideoSync::m_fps.
HandlePresentation()
void CVideoSyncWpPresentation::HandlePresentation (timespec tv, std::uint32_t refresh, std::uint32_t syncOutputID, float syncOutputRefreshRate, std::uint64_t msc) private
References CurrentHostCounter(), CLog::Log(), LOGAVTIMING, LOGDEBUG, CVideoSync::m_fps, m_lastMsc, CVideoSync::m_refClock, m_stopEvent, m_syncOutputID, CEvent::Set(), and CVideoReferenceClock::UpdateClock().
Referenced by Run().
Run()
void CVideoSyncWpPresentation::Run (CEvent & stop) override virtual
Implements CVideoSync.
References _1, _2, _3, _4, _5, HandlePresentation(), m_presentationHandler, m_stopEvent, m_winSystem, KODI::WINDOWING::WAYLAND::CWinSystemWayland::RegisterOnPresentationFeedback(), and KODI::CSignalRegistration::Unregister().
Setup()
bool CVideoSyncWpPresentation::Setup () override virtual
Implements CVideoSync.
References KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetSyncOutputRefreshRate(), CVideoSync::m_fps, m_stopEvent, m_winSystem, and CEvent::Reset().
Member Data Documentation
m_lastMsc
std::uint64_t KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::m_lastMsc {} private
Referenced by HandlePresentation().
m_presentationHandler
CSignalRegistration KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::m_presentationHandler private
Referenced by Run().
m_stopEvent
CEvent KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::m_stopEvent private
Referenced by HandlePresentation(), Run(), and Setup().
m_syncOutputID
std::uint32_t KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::m_syncOutputID {} private
Referenced by HandlePresentation().
m_winSystem
CWinSystemWayland& KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::m_winSystem private
Referenced by Run(), and Setup().
The documentation for this class was generated from the following files:
VideoSyncWpPresentation.h
VideoSyncWpPresentation.cpp