Kodi Documentation: ADDON::Interface_GUIControlButton Struct Reference
ADDON::Interface_GUIControlButton Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Button.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
callback functions from add-on to kodi
static void set_enabled (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled)
static void set_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *label)
static char * get_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_label2 (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *label)
static char * get_label2 (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold general gui functions and initialize also all other gui related types not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/controls/Button.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIControlButton::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_button, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
get_label()
char * ADDON::Interface_GUIControlButton::get_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUIButtonControl::GetLabel(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_label2()
char * ADDON::Interface_GUIControlButton::get_label2 (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUIButtonControl::GetLabel2(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIControlButton::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_button, get_label(), AddonToKodiFuncTable_kodi_gui_control_button::get_label, get_label2(), AddonToKodiFuncTable_kodi_gui_control_button::get_label2, AddonToKodiFuncTable_Addon::kodi_gui, set_enabled(), AddonToKodiFuncTable_kodi_gui_control_button::set_enabled, set_label(), AddonToKodiFuncTable_kodi_gui_control_button::set_label, set_label2(), AddonToKodiFuncTable_kodi_gui_control_button::set_label2, set_visible(), AddonToKodiFuncTable_kodi_gui_control_button::set_visible, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
set_enabled()
void ADDON::Interface_GUIControlButton::set_enabled (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetEnabled().
Referenced by Init().
set_label()
void ADDON::Interface_GUIControlButton::set_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * label) static
References ADDON::CAddon::ID(), label, CLog::Log(), LOGERROR, and CGUIButtonControl::SetLabel().
Referenced by Init().
set_label2()
void ADDON::Interface_GUIControlButton::set_label2 (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * label) static
References ADDON::CAddon::ID(), label, CLog::Log(), LOGERROR, and CGUIButtonControl::SetLabel2().
Referenced by Init().
set_visible()
void ADDON::Interface_GUIControlButton::set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetVisible().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/controls/button.h
Button.cpp