Kodi Documentation: XBMCHelper Class Reference
XBMCHelper Class Reference
#include <XBMCHelper.h>
Public Member Functions
bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting is being changed.
void Start ()
void Stop ()
void Configure ()
bool IsRunning ()
bool IsAlwaysOn () const
int GetMode () const
bool ErrorStarting ()
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual void OnSettingChanged (const std::shared_ptr< const CSetting > &setting)
The value of the given setting has changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Static Public Member Functions
static XBMCHelper & GetInstance ()
Private Member Functions
XBMCHelper ()
XBMCHelper (XBMCHelper const &)=delete
XBMCHelper & operator= (XBMCHelper const &)=delete
void HandleLaunchAgent ()
void Install ()
void Uninstall ()
bool IsRemoteBuddyInstalled ()
bool IsSofaControlRunning ()
int GetProcessPid (const char *processName)
std::string ReadFile (const char *fileName)
void WriteFile (const char *fileName, const std::string &data)
Private Attributes
bool m_alwaysOn = false
int m_mode = APPLE_REMOTE_DISABLED
int m_sequenceDelay = 0
int m_port = 0
bool m_errorStarting = false
std::string m_configFile
std::string m_launchAgentLocalFile
std::string m_launchAgentInstallFile
std::string m_homepath
std::string m_helperFile
Static Private Attributes
static XBMCHelper * smp_instance = 0
Constructor & Destructor Documentation
XBMCHelper() [1/2]
XBMCHelper::XBMCHelper () private
References CCompileInfo::GetAppName(), CUtil::GetHomePath(), m_configFile, m_helperFile, m_homepath, m_launchAgentInstallFile, m_launchAgentLocalFile, XBMC_HELPER_PROGRAM, and XBMC_LAUNCH_PLIST.
Referenced by GetInstance().
XBMCHelper() [2/2]
XBMCHelper::XBMCHelper (XBMCHelper const &) private delete
Member Function Documentation
Configure()
void XBMCHelper::Configure ()
References APPLE_REMOTE_DISABLED, APPLE_REMOTE_MULTIREMOTE, APPLE_REMOTE_UNIVERSAL, GetProcessPid(), CServiceBroker::GetSettingsComponent(), HandleLaunchAgent(), IsRemoteBuddyInstalled(), IsSofaControlRunning(), m_configFile, m_errorStarting, m_homepath, m_mode, m_port, m_sequenceDelay, CSettings::SETTING_INPUT_APPLEREMOTEMODE, CSettings::SETTING_INPUT_APPLEREMOTESEQUENCETIME, CSettings::SETTING_SERVICES_ESPORT, Start(), Stop(), Uninstall(), WriteFile(), and XBMC_HELPER_PROGRAM.
Referenced by CPlatformDarwinOSX::InitStageTwo(), CNetworkServices::OnSettingChanging(), and OnSettingChanging().
ErrorStarting()
bool XBMCHelper::ErrorStarting () inline
References m_errorStarting.
Referenced by OnSettingChanging().
GetInstance()
XBMCHelper & XBMCHelper::GetInstance () static
References smp_instance, and XBMCHelper().
Referenced by CSettings::InitializeISettingCallbacks(), CPlatformDarwinOSX::InitStageTwo(), CNetworkServices::OnSettingChanging(), CApplication::Stop(), and CSettings::UninitializeISettingCallbacks().
GetMode()
int XBMCHelper::GetMode () const inline
References m_mode.
Referenced by OnSettingChanging().
GetProcessPid()
int XBMCHelper::GetProcessPid (const char * processName) private
References GetBSDProcessList().
Referenced by Configure(), Install(), IsRunning(), IsSofaControlRunning(), Start(), and Stop().
HandleLaunchAgent()
void XBMCHelper::HandleLaunchAgent () private
References CServiceBroker::GetSettingsComponent(), Install(), m_alwaysOn, CSettings::SETTING_INPUT_APPLEREMOTEALWAYSON, and Uninstall().
Referenced by Configure(), and OnSettingChanging().
Install()
void XBMCHelper::Install () private
References XFILE::CDirectory::Create(), GetProcessPid(), m_helperFile, m_launchAgentInstallFile, m_launchAgentLocalFile, ReadFile(), WriteFile(), and XBMC_HELPER_PROGRAM.
Referenced by HandleLaunchAgent().
IsAlwaysOn()
bool XBMCHelper::IsAlwaysOn () const inline
References m_alwaysOn.
Referenced by CApplication::Stop().
IsRemoteBuddyInstalled()
bool XBMCHelper::IsRemoteBuddyInstalled () private
Referenced by Configure().
IsRunning()
bool XBMCHelper::IsRunning ()
References GetProcessPid(), and XBMC_HELPER_PROGRAM.
Referenced by OnSettingChanging().
IsSofaControlRunning()
bool XBMCHelper::IsSofaControlRunning () private
References GetProcessPid(), and SOFA_CONTROL_PROGRAM.
Referenced by Configure().
OnSettingChanging()
bool XBMCHelper::OnSettingChanging (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting is being changed.
This callback is triggered whenever the value of a setting is being changed. The given CSetting already contains the new value and the handler of the callback has the possibility to allow or revert changing the value of the setting. In case of a revert OnSettingChanging() is called again to inform all listeners that the value change has been reverted.
Parameters
setting The setting whose value is being changed (already containing the changed value)
Returns
True if the new value is acceptable otherwise false
Reimplemented from ISettingCallback.
References APPLE_REMOTE_DISABLED, Configure(), ErrorStarting(), GetMode(), CServiceBroker::GetSettingsComponent(), HandleLaunchAgent(), IsRunning(), SetBool(), CSettings::SETTING_INPUT_APPLEREMOTEALWAYSON, CSettings::SETTING_INPUT_APPLEREMOTEMODE, CGUIDialogYesNo::ShowAndGetInput(), and CGUIDialogOK::ShowAndGetInput().
operator=()
XBMCHelper & XBMCHelper::operator= (XBMCHelper const &) private delete
ReadFile()
std::string XBMCHelper::ReadFile (const char * fileName) private
Referenced by Install().
Start()
void XBMCHelper::Start ()
References GetProcessPid(), m_helperFile, and XBMC_HELPER_PROGRAM.
Referenced by Configure(), and Uninstall().
Stop()
void XBMCHelper::Stop ()
References GetProcessPid(), CLog::Log(), LOGDEBUG, and XBMC_HELPER_PROGRAM.
Referenced by Configure(), and CApplication::Stop().
Uninstall()
void XBMCHelper::Uninstall () private
References APPLE_REMOTE_DISABLED, XFILE::CFile::Delete(), m_launchAgentInstallFile, m_mode, and Start().
Referenced by Configure(), and HandleLaunchAgent().
WriteFile()
void XBMCHelper::WriteFile (const char * fileName, const std::string & data) private
References data(), CLog::Log(), and LOGERROR.
Referenced by Configure(), and Install().
Member Data Documentation
m_alwaysOn
bool XBMCHelper::m_alwaysOn = false private
Referenced by HandleLaunchAgent(), and IsAlwaysOn().
m_configFile
std::string XBMCHelper::m_configFile private
Referenced by Configure(), and XBMCHelper().
m_errorStarting
bool XBMCHelper::m_errorStarting = false private
Referenced by Configure(), and ErrorStarting().
m_helperFile
std::string XBMCHelper::m_helperFile private
Referenced by Install(), Start(), and XBMCHelper().
m_homepath
std::string XBMCHelper::m_homepath private
Referenced by Configure(), and XBMCHelper().
m_launchAgentInstallFile
std::string XBMCHelper::m_launchAgentInstallFile private
Referenced by Install(), Uninstall(), and XBMCHelper().
m_launchAgentLocalFile
std::string XBMCHelper::m_launchAgentLocalFile private
Referenced by Install(), and XBMCHelper().
m_mode
int XBMCHelper::m_mode = APPLE_REMOTE_DISABLED private
Referenced by Configure(), GetMode(), and Uninstall().
m_port
int XBMCHelper::m_port = 0 private
Referenced by Configure().
m_sequenceDelay
int XBMCHelper::m_sequenceDelay = 0 private
Referenced by Configure().
smp_instance
XBMCHelper * XBMCHelper::smp_instance = 0 static private
Referenced by GetInstance().
The documentation for this class was generated from the following files:
XBMCHelper.h
XBMCHelper.cpp