Kodi Documentation: anonymous_namespace{PVRClient.cpp}::CAddonChannel Class Reference
anonymous_namespace{PVRClient.cpp}::CAddonChannel Class Reference
Public Member Functions
CAddonChannel (const CPVRChannel &channel, const std::string &newChannelName="")
virtual ~CAddonChannel ()=default
Private Attributes
const std::string m_channelName
const std::string m_mimeType
const std::string m_iconPath
Additional Inherited Members
Public Attributes inherited from PVR_CHANNEL
unsigned int iUniqueId
bool bIsRadio
unsigned int iChannelNumber
unsigned int iSubChannelNumber
const char * strChannelName
const char * strMimeType
unsigned int iEncryptionSystem
const char * strIconPath
bool bIsHidden
bool bHasArchive
int iOrder
int iClientProviderUid
Constructor & Destructor Documentation
CAddonChannel()
anonymous_namespace{PVRClient.cpp}::CAddonChannel::CAddonChannel (const CPVRChannel & channel, const std::string & newChannelName = "") inline explicit
References PVR::CPVRChannel::ClientChannelNumber(), PVR::CPVRChannel::ClientProviderUid(), PVR::CPVRChannel::EncryptionSystem(), PVR::CPVRChannelNumber::GetChannelNumber(), PVR::CPVRChannelNumber::GetSubChannelNumber(), PVR::CPVRChannel::HasArchive(), PVR::CPVRChannel::IsHidden(), PVR::CPVRChannel::IsRadio(), and PVR::CPVRChannel::UniqueID().
~CAddonChannel()
virtual anonymous_namespace{PVRClient.cpp}::CAddonChannel::~CAddonChannel () virtual default
Member Data Documentation
m_channelName
const std::string anonymous_namespace{PVRClient.cpp}::CAddonChannel::m_channelName private
m_iconPath
const std::string anonymous_namespace{PVRClient.cpp}::CAddonChannel::m_iconPath private
m_mimeType
const std::string anonymous_namespace{PVRClient.cpp}::CAddonChannel::m_mimeType private
The documentation for this class was generated from the following file:
PVRClient.cpp