Kodi Documentation: KODI::GAME::CDefaultMouseTranslator Class Reference
KODI::GAME::CDefaultMouseTranslator Class Reference
Games
#include <DefaultMouseTranslator.h>
Static Public Member Functions
static const char * TranslateMouseButton (MOUSE::BUTTON_ID button)
Translate a mouse button ID to a mouse button name.
static const char * TranslateMousePointer (MOUSE::POINTER_DIRECTION direction)
Translate a mouse pointer direction.
Member Function Documentation
TranslateMouseButton()
const char * CDefaultMouseTranslator::TranslateMouseButton (MOUSE::BUTTON_ID button) static
Translate a mouse button ID to a mouse button name.
Parameters
button The button ID
Returns
The mouse button's name, or empty if unknown
References KODI::MOUSE::BUTTON4, KODI::MOUSE::BUTTON5, KODI::MOUSE::HORIZ_WHEEL_LEFT, KODI::MOUSE::HORIZ_WHEEL_RIGHT, KODI::MOUSE::LEFT, KODI::MOUSE::MIDDLE, KODI::MOUSE::RIGHT, KODI::MOUSE::WHEEL_DOWN, and KODI::MOUSE::WHEEL_UP.
Referenced by anonymous_namespace{TestDefaultMouseTranslator.cpp}::GetButtonType(), and KODI::GAME::CDefaultButtonMap::GetFeature().
TranslateMousePointer()
const char * CDefaultMouseTranslator::TranslateMousePointer (MOUSE::POINTER_DIRECTION direction) static
Translate a mouse pointer direction.
Parameters
direction The relative pointer direction
Returns
The relative pointer direction, or empty if unknown
Referenced by KODI::GAME::CDefaultButtonMap::GetFeature(), and anonymous_namespace{TestDefaultMouseTranslator.cpp}::GetPointerType().
The documentation for this class was generated from the following files:
DefaultMouseTranslator.h
DefaultMouseTranslator.cpp