Kodi Documentation: PVR::CPVRChannelGroup Class Reference
PVR::CPVRChannelGroup Class Reference abstract
#include <PVRChannelGroup.h>
Public Member Functions
CPVRChannelGroup (const CPVRChannelsPath &path, const std::shared_ptr< const CPVRChannelGroup > &allChannelsGroup)
Create a new channel group instance.
~CPVRChannelGroup () override
bool operator== (const CPVRChannelGroup &right) const
bool operator!= (const CPVRChannelGroup &right) const
CEventStream< PVREvent > & Events ()
Query the events available for CEventStream.
bool LoadFromDatabase (const std::map< std::pair< int, int >, std::shared_ptr< CPVRChannel > > &channels, const std::vector< std::shared_ptr< CPVRClient > > &clients)
Load the channels from the database.
void Unload ()
Clear all data.
size_t Size () const
virtual bool UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > &clients)=0
Update data with channel group members from the given clients, sync with local data.
int GetClientID () const
Get the identifier of the client that serves this channel group.
void SetClientID (int clientID)
Set the identifier of the client that serves this channel group.
const CPVRChannelsPath & GetPath () const
Get the path of this group.
void SetPath (const CPVRChannelsPath &path)
Set the path of this group.
virtual bool RemoveFromGroup (const std::shared_ptr< const CPVRChannelGroupMember > &groupMember)
Remove a channel group member from this container.
virtual bool AppendToGroup (const std::shared_ptr< const CPVRChannelGroupMember > &groupMember)
Append a channel group member to this container.
virtual bool IsGroupMember (const std::shared_ptr< const CPVRChannelGroupMember > &groupMember) const
Check whether a channel group member is in this container.
bool SetGroupName (const std::string &strGroupName, bool isUserSetName=false)
Change the name of this group.
void SetClientGroupName (const std::string &groupName)
Set the name this group has on the client.
bool IsUserSetName () const
Check whether the group name was set by the user.
bool Persist ()
Persist changed or new data.
bool IsRadio () const
True if this group holds radio channels, false if it holds TV channels.
int GroupID () const
The database ID of this group.
void SetGroupID (int iGroupId)
Set the database ID of this group.
time_t LastWatched () const
void SetLastWatched (time_t iLastWatched)
Last time group has been watched.
uint64_t LastOpened () const
void SetLastOpened (uint64_t iLastOpened)
Set the time in milliseconds from epoch this group was last opened.
std::string GroupName () const
The name of this group.
std::string ClientGroupName () const
Get the name of this group on the client.
Public Member Functions inherited from PVR::IChannelGroupSettingsCallback
virtual ~IChannelGroupSettingsCallback ()=default
Static Public Attributes
static const int INVALID_GROUP_ID = -1
Friends
class CPVRDatabase
Sort methods
enum class Include { ALL , ONLY_HIDDEN , ONLY_VISIBLE }
enum class Origin { USER , SYSTEM , CLIENT }
int m_iGroupId = INVALID_GROUP_ID
bool m_bLoaded = false
bool m_bChanged
time_t m_iLastWatched = 0
uint64_t m_iLastOpened = 0
bool m_bHidden = false
int m_iPosition = 0
std::vector< std::shared_ptr< CPVRChannelGroupMember > > m_sortedMembers
std::map< std::pair< int, int >, std::shared_ptr< CPVRChannelGroupMember > > m_members
CCriticalSection m_critSection
std::vector< int > m_failedClients
CEventSource< PVREvent > m_events
std::shared_ptr< CPVRChannelGroupSettings > m_settings
static CCriticalSection m_settingsSingletonCritSection
static std::weak_ptr< CPVRChannelGroupSettings > m_settingsSingleton
std::shared_ptr< const CPVRChannelGroup > m_allChannelsGroup
CPVRChannelsPath m_path
bool m_bDeleted = false
std::optional< int > m_clientPriority
bool m_isUserSetName {false}
std::string m_clientGroupName
int m_iClientPosition {0}
void Sort ()
Sort the group.
bool SortAndRenumber ()
Sort the group and fix up channel numbers.
bool Renumber (RenumberMode mode=NORMAL)
Remove invalid channels and updates the channel numbers.
void UseBackendChannelOrderChanged () override
void UseBackendChannelNumbersChanged () override
void StartGroupChannelNumbersFromOneChanged () override
std::shared_ptr< CPVRChannelGroupMember > GetLastPlayedChannelGroupMember (int iCurrentChannel=-1) const
Get the channel group member that was played last.
GroupMemberPair GetLastAndPreviousToLastPlayedChannelGroupMember () const
Get the last and previous to last played channel group members.
std::shared_ptr< CPVRChannelGroupMember > GetByChannelNumber (const CPVRChannelNumber &channelNumber) const
Get a channel group member given it's active channel number.
CPVRChannelNumber GetChannelNumber (const std::shared_ptr< const CPVRChannel > &channel) const
Get the channel number in this group of the given channel.
CPVRChannelNumber GetClientChannelNumber (const std::shared_ptr< const CPVRChannel > &channel) const
Get the client channel number in this group of the given channel.
std::shared_ptr< CPVRChannelGroupMember > GetNextChannelGroupMember (const std::shared_ptr< const CPVRChannelGroupMember > &groupMember) const
Get the next channel group member in this group.
std::shared_ptr< CPVRChannelGroupMember > GetPreviousChannelGroupMember (const std::shared_ptr< const CPVRChannelGroupMember > &groupMember) const
Get the previous channel group member in this group.
std::shared_ptr< CPVRChannel > GetByChannelID (int iChannelID) const
Get a channel given it's channel ID.
std::vector< std::shared_ptr< CPVRChannelGroupMember > > GetMembers (Include eFilter=Include::ALL) const
Get the current members of this group.
void GetChannelNumbers (std::vector< std::string > &channelNumbers) const
Get the list of active channel numbers in a group.
bool HasChannels () const
Check whether this container has any channels.
bool HasNewChannels () const
Check whether this container has any new channels.
bool HasHiddenChannels () const
Check whether this container has any hidden channels.
bool HasChanges () const
bool IsNew () const
std::shared_ptr< CPVRChannel > GetByUniqueID (int iUniqueChannelId, int iClientID) const
Get a channel given the channel number on the client.
std::shared_ptr< CPVRChannelGroupMember > GetByUniqueID (const std::pair< int, int > &id) const
Get a channel group member given its storage id.
bool HasChannelForProvider (int clientId, int providerId) const
Check whether at least one channel of this group is offered by the given provider.
unsigned int GetChannelCountByProvider (int clientId, int providerId) const
Get the total count of channels of this group offered by the given provider.
bool SetHidden (bool bHidden)
Set the hidden state of this group.
bool IsHidden () const
Check whether this group is hidden.
int GetPosition () const
Get the local position of this group.
bool SetPosition (int iPosition)
Set the local position of this group.
int GetClientPosition () const
Get the position of this group as supplied by the PVR client.
void SetClientPosition (int iPosition)
Set the client-supplied position of this group.
bool HasValidDataForClient (int iClientId) const
Check, whether data for a given pvr client are currently valid. For instance, data can be invalid because the client's backend was offline when data was last queried.
bool HasValidDataForClients (const std::vector< std::shared_ptr< CPVRClient > > &clients) const
Check, whether data for given pvr clients are currently valid. For instance, data can be invalid because the client's backend was offline when data was last queried.
bool UpdateChannelNumbersFromAllChannelsGroup ()
Update the channel numbers according to the all channels group and publish event.
void Delete ()
Remove this group from database.
bool IsDeleted () const
Whether this group is deleted.
int CleanupCachedImages ()
Erase stale texture db entries and image files.
int GetClientPriority () const
Get the priority of the client that provides this group.
void UpdateClientPriorities ()
Update the client priority for this group and all members of this group.
virtual Origin GetOrigin () const =0
Get the group's origin.
virtual int GroupType () const =0
Return the type of this group.
virtual bool SupportsDelete () const =0
Check whether this group could be deleted by the user.
virtual bool SupportsMemberAdd () const =0
Check whether members could be added to this group by the user.
virtual bool SupportsMemberRemove () const =0
Check whether members could be removed from this group by the user.
virtual bool IsChannelsOwner () const =0
Check whether this group is owner of the channel instances it contains.
virtual bool ShouldBeIgnored (const std::vector< std::shared_ptr< CPVRChannelGroup > > &allChannelGroups) const
Check whether this group should be ignored, e.g. not presented to the user and API.
virtual bool UpdateGroupMembers (const std::shared_ptr< CPVRChannelGroup > &allChannelsGroup, const std::vector< std::shared_ptr< CPVRChannelGroup > > &allChannelGroups)
Update all group members.
virtual std::vector< std::shared_ptr< CPVRChannelGroupMember > > RemoveDeletedGroupMembers (const std::vector< std::shared_ptr< CPVRChannelGroupMember > > &groupMembers)
Remove deleted group members from this group.
bool UpdateGroupEntries (const std::vector< std::shared_ptr< CPVRChannelGroupMember > > &groupMembers)
Update the current channel group members with the given list.
void SortByClientChannelNumber ()
Sort the current channel list by client channel number.
void SortByChannelNumber ()
Sort the current channel list by channel number.
bool UpdateMembersClientPriority ()
Update the client priority for all members of this group.
std::shared_ptr< CPVRChannelGroupSettings > GetSettings () const
int LoadFromDatabase (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Load the channel group members stored in the database.
void DeleteGroupMembersFromDb (const std::vector< std::shared_ptr< CPVRChannelGroupMember > > &membersToDelete)
Delete channel group members from database.
bool UpdateFromClient (const std::shared_ptr< CPVRChannelGroupMember > &groupMember)
Update this group's data with a channel group member provided by a client.
bool AddAndUpdateGroupMembers (const std::vector< std::shared_ptr< CPVRChannelGroupMember > > &groupMembers)
Add new channel group members to this group; update data.
void OnSettingChanged ()
Member Enumeration Documentation
Include
enum class PVR::CPVRChannelGroup::Include strong
Enumerator
ALL
ONLY_HIDDEN
ONLY_VISIBLE
Origin
enum class PVR::CPVRChannelGroup::Origin strong
Enumerator
USER
SYSTEM
CLIENT
Constructor & Destructor Documentation
CPVRChannelGroup()
CPVRChannelGroup::CPVRChannelGroup (const CPVRChannelsPath & path, const std::shared_ptr< const CPVRChannelGroup > & allChannelsGroup)
Create a new channel group instance.
Parameters
path The channel group path.
allChannelsGroup The channel group containing all TV or radio channels.
References GetSettings().
~CPVRChannelGroup()
CPVRChannelGroup::~CPVRChannelGroup () override
References GetSettings().
Member Function Documentation
AddAndUpdateGroupMembers()
bool CPVRChannelGroup::AddAndUpdateGroupMembers (const std::vector< std::shared_ptr< CPVRChannelGroupMember > > & groupMembers) private
Add new channel group members to this group; update data.
Parameters
groupMembers The group members to use to update this list.
Returns
True if group member data were changed, false otherwise.
Referenced by UpdateGroupEntries().
AppendToGroup()
bool CPVRChannelGroup::AppendToGroup (const std::shared_ptr< const CPVRChannelGroupMember > & groupMember) virtual
Append a channel group member to this container.
Parameters
groupMember The channel group member to append.
Returns
True if the channel group member was appended, false otherwise.
Reimplemented in PVR::CPVRChannelGroupAllChannels.
References GetClientID(), GroupID(), GroupName(), IsGroupMember(), m_critSection, m_members, m_sortedMembers, and SortAndRenumber().
CleanupCachedImages()
int CPVRChannelGroup::CleanupCachedImages ()
Erase stale texture db entries and image files.
Returns
number of cleaned up images.
References PVR::CPVRCachedImages::Cleanup(), PVR::CPVRChannel::IMAGE_OWNER_PATTERN, IsRadio(), m_critSection, m_members, and owner.
ClientGroupName()
std::string CPVRChannelGroup::ClientGroupName () const
Get the name of this group on the client.
Returns
The group's name.
References m_clientGroupName, and m_critSection.
Referenced by PVR::CPVRChannelGroupMergedByName::ShouldBeIgnored(), and PVR::CPVRChannelGroupMergedByName::UpdateGroupMembers().
Delete()
void CPVRChannelGroup::Delete ()
Remove this group from database.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), LOGERROR, m_bDeleted, m_critSection, and m_iGroupId.
DeleteGroupMembersFromDb()
void CPVRChannelGroup::DeleteGroupMembersFromDb (const std::vector< std::shared_ptr< CPVRChannelGroupMember > > & membersToDelete) private
Delete channel group members from database.
Parameters
membersToDelete The channel group members.
References PVR::CHANNEL_COMMIT_QUERY_COUNT_LIMIT, CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), and LOGERROR.
Referenced by LoadFromDatabase(), RemoveDeletedGroupMembers(), and RemoveFromGroup().
Events()
CEventStream< PVREvent > & PVR::CPVRChannelGroup::Events () inline
Query the events available for CEventStream.
References m_events.
GetByChannelID()
std::shared_ptr< CPVRChannel > CPVRChannelGroup::GetByChannelID (int iChannelID) const
Get a channel given it's channel ID.
Parameters
iChannelID The channel ID.
Returns
The channel or NULL if it wasn't found.
References m_critSection, and m_members.
GetByChannelNumber()
std::shared_ptr< CPVRChannelGroupMember > CPVRChannelGroup::GetByChannelNumber (const CPVRChannelNumber & channelNumber) const
Get a channel group member given it's active channel number.
Parameters
channelNumber The channel number.
Returns
The channel group member or nullptr if it wasn't found.
References GetSettings(), m_critSection, and m_sortedMembers.
GetByUniqueID() [1/2]
std::shared_ptr< CPVRChannelGroupMember > CPVRChannelGroup::GetByUniqueID (const std::pair< int, int > & id) const
Get a channel group member given its storage id.
Parameters
id The storage id (a pair of client id and unique channel id).
Returns
The channel group member or nullptr if it wasn't found.
References m_critSection, and m_members.
GetByUniqueID() [2/2]
std::shared_ptr< CPVRChannel > CPVRChannelGroup::GetByUniqueID (int iUniqueChannelId, int iClientID) const
Get a channel given the channel number on the client.
Parameters
iUniqueChannelId The unique channel id on the client.
iClientID The ID of the client.
Returns
The channel or NULL if it wasn't found.
References GetByUniqueID().
Referenced by GetByUniqueID(), GetChannelNumber(), GetClientChannelNumber(), and UpdateFromClient().
GetChannelCountByProvider()
unsigned int CPVRChannelGroup::GetChannelCountByProvider (int clientId, int providerId) const
Get the total count of channels of this group offered by the given provider.
Parameters
clientId The clientId of the provider.
providerId The providerId.
Returns
The total count of matching channels.
References m_critSection, and m_members.
GetChannelNumber()
CPVRChannelNumber CPVRChannelGroup::GetChannelNumber (const std::shared_ptr< const CPVRChannel > & channel) const
Get the channel number in this group of the given channel.
Parameters
channel The channel to get the channel number for.
Returns
The channel number in this group.
References GetByUniqueID(), and m_critSection.
GetChannelNumbers()
void CPVRChannelGroup::GetChannelNumbers (std::vector< std::string > & channelNumbers) const
Get the list of active channel numbers in a group.
Parameters
channelNumbers The list to store the numbers in.
References PVR::CPVRChannelNumber::FormattedChannelNumber(), GetSettings(), m_critSection, and m_sortedMembers.
GetClientChannelNumber()
CPVRChannelNumber CPVRChannelGroup::GetClientChannelNumber (const std::shared_ptr< const CPVRChannel > & channel) const
Get the client channel number in this group of the given channel.
Parameters
channel The channel to get the channel number for.
Returns
The client channel number in this group.
References GetByUniqueID(), and m_critSection.
GetClientID()
int CPVRChannelGroup::GetClientID () const
Get the identifier of the client that serves this channel group.
Returns
The identifier or PVR_GROUP_CLIENT_ID_LOCAL for local groups.
References PVR::CPVRChannelsPath::GetGroupClientID(), m_critSection, and m_path.
Referenced by AppendToGroup(), GetClientPriority(), LoadFromDatabase(), RemoveDeletedGroupMembers(), PVR::CPVRChannelGroupFromClient::UpdateFromClients(), PVR::CPVRChannelGroupAllChannelsSingleClient::UpdateGroupMembers(), and PVR::CPVRChannelGroupMergedByName::UpdateGroupMembers().
GetClientPosition()
int CPVRChannelGroup::GetClientPosition () const
Get the position of this group as supplied by the PVR client.
Returns
The client-supplied group position.
References m_critSection, and m_iClientPosition.
GetClientPriority()
int CPVRChannelGroup::GetClientPriority () const
Get the priority of the client that provides this group.
Returns
the priority, as set by the user or 0. Always 0 for non-backend-supplied groups.
References PVR::CPVRManager::GetClient(), GetClientID(), CServiceBroker::GetPVRManager(), m_clientPriority, m_critSection, and PVR::PVR_GROUP_CLIENT_ID_UNKNOWN.
Referenced by UpdateClientPriorities().
GetLastAndPreviousToLastPlayedChannelGroupMember()
GroupMemberPair CPVRChannelGroup::GetLastAndPreviousToLastPlayedChannelGroupMember () const
Get the last and previous to last played channel group members.
Returns
The members. pair.first contains the last, pair.second the previous to last member.
References LastWatched(), m_critSection, and m_sortedMembers.
GetLastPlayedChannelGroupMember()
std::shared_ptr< CPVRChannelGroupMember > CPVRChannelGroup::GetLastPlayedChannelGroupMember (int iCurrentChannel = -1) const
Get the channel group member that was played last.
Parameters
iCurrentChannel The channelid of the current channel that is playing, or -1 if none
Returns
The requested channel group member or nullptr.
References PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), m_critSection, and m_members.
GetMembers()
std::vector< std::shared_ptr< CPVRChannelGroupMember > > CPVRChannelGroup::GetMembers (Include eFilter = Include::ALL) const
Get the current members of this group.
Parameters
eFilter A filter to apply.
Returns
The group members
References ALL, m_critSection, m_sortedMembers, ONLY_HIDDEN, and ONLY_VISIBLE.
GetNextChannelGroupMember()
std::shared_ptr< CPVRChannelGroupMember > CPVRChannelGroup::GetNextChannelGroupMember (const std::shared_ptr< const CPVRChannelGroupMember > & groupMember) const
Get the next channel group member in this group.
Parameters
groupMember The current channel group member.
Returns
The channel group member or nullptr if it wasn't found.
References m_critSection, and m_sortedMembers.
GetOrigin()
virtual Origin PVR::CPVRChannelGroup::GetOrigin () const pure virtual
Get the group's origin.
Returns
The origin.
Implemented in PVR::CPVRChannelGroupAllChannels, PVR::CPVRChannelGroupAllChannelsSingleClient, PVR::CPVRChannelGroupFromClient, PVR::CPVRChannelGroupFromUser, and PVR::CPVRChannelGroupMergedByName.
GetPath()
const CPVRChannelsPath & CPVRChannelGroup::GetPath () const
Get the path of this group.
Returns
the path.
References m_critSection, and m_path.
GetPosition()
int CPVRChannelGroup::GetPosition () const
Get the local position of this group.
Returns
The local group position.
References m_critSection, and m_iPosition.
GetPreviousChannelGroupMember()
std::shared_ptr< CPVRChannelGroupMember > CPVRChannelGroup::GetPreviousChannelGroupMember (const std::shared_ptr< const CPVRChannelGroupMember > & groupMember) const
Get the previous channel group member in this group.
Parameters
groupMember The current channel group member.
Returns
The channel group member or nullptr if it wasn't found.
References m_critSection, and m_sortedMembers.
GetSettings()
std::shared_ptr< CPVRChannelGroupSettings > CPVRChannelGroup::GetSettings () const protected
References m_critSection, m_settings, m_settingsSingleton, and m_settingsSingletonCritSection.
Referenced by CPVRChannelGroup(), GetByChannelNumber(), GetChannelNumbers(), Renumber(), Sort(), UpdateMembersClientPriority(), and ~CPVRChannelGroup().
GroupID()
int CPVRChannelGroup::GroupID () const
The database ID of this group.
Returns
The database ID of this group.
References m_iGroupId.
Referenced by AppendToGroup(), UpdateFromClient(), PVR::CPVRChannelGroupAllChannelsSingleClient::UpdateGroupMembers(), and PVR::CPVRChannelGroupMergedByName::UpdateGroupMembers().
GroupName()
std::string CPVRChannelGroup::GroupName () const
The name of this group.
Returns
The name of this group.
References PVR::CPVRChannelsPath::GetGroupName(), m_critSection, and m_path.
Referenced by AppendToGroup(), LoadFromDatabase(), LoadFromDatabase(), OnSettingChanged(), Persist(), RemoveDeletedGroupMembers(), PVR::CPVRChannelGroupMergedByName::ShouldBeIgnored(), UpdateFromClient(), PVR::CPVRChannelGroupFromClient::UpdateFromClients(), PVR::CPVRChannelGroupAllChannelsSingleClient::UpdateGroupMembers(), and PVR::CPVRChannelGroupMergedByName::UpdateGroupMembers().
GroupType()
virtual int PVR::CPVRChannelGroup::GroupType () const pure virtual
Return the type of this group.
Implemented in PVR::CPVRChannelGroupAllChannels, PVR::CPVRChannelGroupAllChannelsSingleClient, PVR::CPVRChannelGroupFromClient, PVR::CPVRChannelGroupFromUser, and PVR::CPVRChannelGroupMergedByName.
Referenced by operator==().
HasChanges()
bool CPVRChannelGroup::HasChanges () const
Returns
True if anything changed in this group that hasn't been persisted, false otherwise.
References m_bChanged, and m_critSection.
HasChannelForProvider()
bool CPVRChannelGroup::HasChannelForProvider (int clientId, int providerId) const
Check whether at least one channel of this group is offered by the given provider.
Parameters
clientId The clientId to check.
providerId The providerId to check.
Returns
True, if the group countains at least one channel offered by the provider, false otherwise.
References m_critSection, and m_members.
HasChannels()
bool CPVRChannelGroup::HasChannels () const
Check whether this container has any channels.
Returns
True if there is at least one channel in this container, otherwise false.
References m_critSection, and m_members.
HasHiddenChannels()
bool CPVRChannelGroup::HasHiddenChannels () const
Check whether this container has any hidden channels.
Returns
True if at least one hidden channel is present, false otherwise.
References m_critSection, and m_members.
HasNewChannels()
bool CPVRChannelGroup::HasNewChannels () const
Check whether this container has any new channels.
Returns
True if there is at least one new channel in this group that hasn't been persisted, false otherwise.
References m_critSection, and m_members.
Referenced by UpdateGroupEntries().
HasValidDataForClient()
bool CPVRChannelGroup::HasValidDataForClient (int iClientId) const
Check, whether data for a given pvr client are currently valid. For instance, data can be invalid because the client's backend was offline when data was last queried.
Parameters
iClientId The id of the client.
Returns
True, if data is currently valid, false otherwise.
References m_failedClients.
Referenced by RemoveDeletedGroupMembers().
HasValidDataForClients()
bool CPVRChannelGroup::HasValidDataForClients (const std::vector< std::shared_ptr< CPVRClient > > & clients) const
Check, whether data for given pvr clients are currently valid. For instance, data can be invalid because the client's backend was offline when data was last queried.
Parameters
clients The clients to check. Check all active clients if vector is empty.
Returns
True, if data is currently valid, false otherwise.
References m_failedClients.
IsChannelsOwner()
virtual bool PVR::CPVRChannelGroup::IsChannelsOwner () const pure virtual
Check whether this group is owner of the channel instances it contains.
Returns
True if owner, false otherwise.
Implemented in PVR::CPVRChannelGroupAllChannels, PVR::CPVRChannelGroupAllChannelsSingleClient, PVR::CPVRChannelGroupFromClient, PVR::CPVRChannelGroupFromUser, and PVR::CPVRChannelGroupMergedByName.
Referenced by Renumber(), UpdateChannelNumbersFromAllChannelsGroup(), and UpdateFromClient().
IsDeleted()
bool PVR::CPVRChannelGroup::IsDeleted () const inline
Whether this group is deleted.
Returns
True, if deleted, false otherwise.
References m_bDeleted.
IsGroupMember()
bool CPVRChannelGroup::IsGroupMember (const std::shared_ptr< const CPVRChannelGroupMember > & groupMember) const virtual
Check whether a channel group member is in this container.
Parameters
groupMember The channel group member to check.
Returns
True if the channel group member was found, false otherwise.
Reimplemented in PVR::CPVRChannelGroupAllChannels.
References m_critSection, and m_members.
Referenced by AppendToGroup().
IsHidden()
bool CPVRChannelGroup::IsHidden () const
Check whether this group is hidden.
Returns
True if group is hidden, false otherwise.
References m_bHidden, and m_critSection.
IsNew()
bool CPVRChannelGroup::IsNew () const
Returns
True if the group was never persisted, false otherwise.
References m_critSection, and m_iGroupId.
IsRadio()
bool CPVRChannelGroup::IsRadio () const
True if this group holds radio channels, false if it holds TV channels.
Returns
True if this group holds radio channels, false if it holds TV channels.
References PVR::CPVRChannelsPath::IsRadio(), m_critSection, and m_path.
Referenced by CleanupCachedImages(), LoadFromDatabase(), LoadFromDatabase(), RemoveDeletedGroupMembers(), UpdateFromClient(), and PVR::CPVRChannelGroupAllChannels::UpdateFromClients().
IsUserSetName()
bool PVR::CPVRChannelGroup::IsUserSetName () const inline
Check whether the group name was set by the user.
Returns
True if set by user, false otherwise;
References m_isUserSetName.
Referenced by PVR::CPVRChannelGroupAllChannels::CheckGroupName().
LastOpened()
uint64_t CPVRChannelGroup::LastOpened () const
Returns
Time in milliseconds from epoch this group was last opened.
References m_critSection, and m_iLastOpened.
LastWatched()
time_t CPVRChannelGroup::LastWatched () const
Returns
Time group has been watched last.
References m_critSection, and m_iLastWatched.
Referenced by GetLastAndPreviousToLastPlayedChannelGroupMember().
LoadFromDatabase() [1/2]
bool CPVRChannelGroup::LoadFromDatabase (const std::map< std::pair< int, int >, std::shared_ptr< CPVRChannel > > & channels, const std::vector< std::shared_ptr< CPVRClient > > & clients)
Load the channels from the database.
Parameters
channels All available channels.
clients The PVR clients data should be loaded for. Leave empty for all clients.
Returns
True when loaded successfully, false otherwise.
References GroupName(), IsRadio(), LoadFromDatabase(), CLog::Log(), LOGDEBUG, LOGERROR, LOGPVR, m_bLoaded, m_iGroupId, and m_members.
Referenced by LoadFromDatabase().
LoadFromDatabase() [2/2]
int CPVRChannelGroup::LoadFromDatabase (const std::vector< std::shared_ptr< CPVRClient > > & clients) private
Load the channel group members stored in the database.
Parameters
clients The PVR clients to load data for. Leave empty for all clients.
Returns
The amount of channel group members that were added.
References PVR::CPVRManager::Clients(), DeleteGroupMembersFromDb(), GetClientID(), CServiceBroker::GetPVRManager(), GroupName(), IsRadio(), LOGWARNING, m_critSection, m_members, m_sortedMembers, PVR::PVR_GROUP_CLIENT_ID_LOCAL, PVR::PVR_GROUP_CLIENT_ID_UNKNOWN, and SortByChannelNumber().
OnSettingChanged()
void CPVRChannelGroup::OnSettingChanged () private
Todo:
while pvr manager is starting up do accept setting changes.
References PVR::ChannelGroup, PVR::ChannelGroupInvalidated, CServiceBroker::GetPVRManager(), GroupName(), PVR::IGNORE_NUMBERING_FROM_ONE, CLog::Log(), LOGDEBUG, LOGPVR, LOGWARNING, m_critSection, m_events, Persist(), CEventSource< Event >::Publish(), Renumber(), and SortAndRenumber().
Referenced by StartGroupChannelNumbersFromOneChanged(), UseBackendChannelNumbersChanged(), and UseBackendChannelOrderChanged().
operator!=()
bool CPVRChannelGroup::operator!= (const CPVRChannelGroup & right) const
References right.
operator==()
bool CPVRChannelGroup::operator== (const CPVRChannelGroup & right) const
References GroupType(), m_clientGroupName, m_clientPriority, m_iClientPosition, m_iGroupId, m_iPosition, m_isUserSetName, m_path, PVR::CPVRChannelsPath::m_path, and right.
Persist()
bool CPVRChannelGroup::Persist ()
Persist changed or new data.
Returns
True if the channel was persisted, false otherwise.
References CServiceBroker::GetPVRManager(), GroupName(), INVALID_GROUP_ID, LOGDEBUG, LOGPVR, m_bChanged, m_bLoaded, m_critSection, m_iGroupId, and m_members.
Referenced by PVR::CPVRChannelGroupAllChannels::CheckGroupName(), OnSettingChanged(), SetClientGroupName(), SetClientID(), SetPath(), and UpdateGroupEntries().
RemoveDeletedGroupMembers()
std::vector< std::shared_ptr< CPVRChannelGroupMember > > CPVRChannelGroup::RemoveDeletedGroupMembers (const std::vector< std::shared_ptr< CPVRChannelGroupMember > > & groupMembers) protected virtual
Remove deleted group members from this group.
Parameters
groupMembers The group members to use to update this list.
Returns
The removed members .
Reimplemented in PVR::CPVRChannelGroupAllChannels.
References DeleteGroupMembersFromDb(), GetClientID(), GroupName(), HasValidDataForClient(), IsRadio(), LOGDEBUG, LOGPVR, m_critSection, m_members, and m_sortedMembers.
Referenced by PVR::CPVRChannelGroupAllChannels::RemoveDeletedGroupMembers(), and UpdateGroupEntries().
RemoveFromGroup()
bool CPVRChannelGroup::RemoveFromGroup (const std::shared_ptr< const CPVRChannelGroupMember > & groupMember) virtual
Remove a channel group member from this container.
Parameters
groupMember The channel group member to remove.
Returns
True if the channel group member was removed, false otherwise.
Reimplemented in PVR::CPVRChannelGroupAllChannels.
References DeleteGroupMembersFromDb(), m_critSection, m_members, m_sortedMembers, and Renumber().
Renumber()
bool CPVRChannelGroup::Renumber (RenumberMode mode = NORMAL)
Remove invalid channels and updates the channel numbers.
Parameters
mode the numbering mode to use
Returns
True if something changed, false otherwise.
References PVR::CPVRChannelNumber::GetChannelNumber(), GetSettings(), PVR::IGNORE_NUMBERING_FROM_ONE, IsChannelsOwner(), PVR::CPVRChannelNumber::IsValid(), m_allChannelsGroup, m_critSection, m_sortedMembers, and Sort().
Referenced by OnSettingChanged(), RemoveFromGroup(), SortAndRenumber(), and UpdateChannelNumbersFromAllChannelsGroup().
SetClientGroupName()
void CPVRChannelGroup::SetClientGroupName (const std::string & groupName)
Set the name this group has on the client.
Parameters
groupName The client group name.
Todo:
why must we persist immediately?
References m_bChanged, m_bLoaded, m_clientGroupName, m_critSection, and Persist().
Referenced by PVR::CPVRChannelGroupFromClient::CPVRChannelGroupFromClient().
SetClientID()
void CPVRChannelGroup::SetClientID (int clientID)
Set the identifier of the client that serves this channel group.
Parameters
clientID The identifier; must be PVR_GROUP_CLIENT_ID_LOCAL for local groups.
Todo:
why must we persist immediately?
References PVR::CPVRChannelsPath::GetGroupClientID(), PVR::CPVRChannelsPath::GetGroupName(), PVR::CPVRChannelsPath::IsRadio(), m_bChanged, m_bLoaded, m_critSection, m_path, and Persist().
SetClientPosition()
void CPVRChannelGroup::SetClientPosition (int iPosition)
Set the client-supplied position of this group.
Parameters
iPosition The new client-supplied group position.
References m_bChanged, m_bLoaded, m_critSection, and m_iClientPosition.
Referenced by PVR::CPVRChannelGroupFromClient::CPVRChannelGroupFromClient().
SetGroupID()
void CPVRChannelGroup::SetGroupID (int iGroupId)
Set the database ID of this group.
Parameters
iGroupId The new database ID.
References m_critSection, m_iGroupId, and m_members.
SetGroupName()
bool CPVRChannelGroup::SetGroupName (const std::string & strGroupName, bool isUserSetName = false)
Change the name of this group.
Parameters
strGroupName The new group name.
isUserSetName Whether the name was set by the user.
Returns
True if the group name was changed, false otherwise.
References PVR::CPVRChannelsPath::GetGroupClientID(), PVR::CPVRChannelsPath::GetGroupName(), PVR::CPVRChannelsPath::IsRadio(), m_bChanged, m_bLoaded, m_critSection, m_isUserSetName, m_path, and m_sortedMembers.
Referenced by PVR::CPVRChannelGroupAllChannels::CheckGroupName().
SetHidden()
bool CPVRChannelGroup::SetHidden (bool bHidden)
Set the hidden state of this group.
Parameters
bHidden True to set hidden state, false to unhide the group.
Returns
True if hidden state was changed, false otherwise.
References m_bChanged, m_bHidden, m_bLoaded, and m_critSection.
SetLastOpened()
void CPVRChannelGroup::SetLastOpened (uint64_t iLastOpened)
Set the time in milliseconds from epoch this group was last opened.
Parameters
iLastOpened The new value.
References CServiceBroker::GetPVRManager(), m_bLoaded, m_critSection, and m_iLastOpened.
SetLastWatched()
void CPVRChannelGroup::SetLastWatched (time_t iLastWatched)
Last time group has been watched.
Parameters
iLastWatched The new value.
References CServiceBroker::GetPVRManager(), m_bLoaded, m_critSection, and m_iLastWatched.
SetPath()
void CPVRChannelGroup::SetPath (const CPVRChannelsPath & path)
Set the path of this group.
Parameters
the path.
Todo:
why must we persist immediately?
References m_bChanged, m_bLoaded, m_critSection, m_path, and Persist().
SetPosition()
bool CPVRChannelGroup::SetPosition (int iPosition)
Set the local position of this group.
Parameters
iPosition The new local group position.
Returns
True if position has changed, false otherwise.
References m_bChanged, m_bLoaded, m_critSection, and m_iPosition.
ShouldBeIgnored()
bool CPVRChannelGroup::ShouldBeIgnored (const std::vector< std::shared_ptr< CPVRChannelGroup > > & allChannelGroups) const virtual
Check whether this group should be ignored, e.g. not presented to the user and API.
Parameters
allChannelGroups All available channel groups. This information might be needed by implementations to calculate the ignore state.
Returns
True if to be ignored, false otherwise.
Reimplemented in PVR::CPVRChannelGroupAllChannels, PVR::CPVRChannelGroupFromUser, and PVR::CPVRChannelGroupMergedByName.
References m_critSection, and m_members.
Size()
size_t CPVRChannelGroup::Size () const
Returns
The amount of group members
References m_critSection, and m_members.
Sort()
void CPVRChannelGroup::Sort ()
Sort the group.
References GetSettings(), SortByChannelNumber(), and SortByClientChannelNumber().
Referenced by Renumber(), and SortAndRenumber().
SortAndRenumber()
bool CPVRChannelGroup::SortAndRenumber ()
Sort the group and fix up channel numbers.
Returns
True when numbering changed, false otherwise
References m_critSection, Renumber(), and Sort().
Referenced by AppendToGroup(), PVR::CPVRChannelGroupAllChannels::AppendToGroup(), OnSettingChanged(), PVR::CPVRChannelGroupAllChannels::RemoveFromGroup(), UpdateChannelNumbersFromAllChannelsGroup(), UpdateClientPriorities(), and UpdateGroupEntries().
SortByChannelNumber()
void CPVRChannelGroup::SortByChannelNumber () protected
Sort the current channel list by channel number.
References m_critSection, and m_sortedMembers.
Referenced by LoadFromDatabase(), and Sort().
SortByClientChannelNumber()
void CPVRChannelGroup::SortByClientChannelNumber () protected
Sort the current channel list by client channel number.
References m_critSection, and m_sortedMembers.
Referenced by Sort().
StartGroupChannelNumbersFromOneChanged()
void CPVRChannelGroup::StartGroupChannelNumbersFromOneChanged () override virtual
Reimplemented from PVR::IChannelGroupSettingsCallback.
References OnSettingChanged().
SupportsDelete()
virtual bool PVR::CPVRChannelGroup::SupportsDelete () const pure virtual
Check whether this group could be deleted by the user.
Returns
True if the group could be deleted, false otherwise.
Implemented in PVR::CPVRChannelGroupAllChannels, PVR::CPVRChannelGroupAllChannelsSingleClient, PVR::CPVRChannelGroupFromClient, PVR::CPVRChannelGroupFromUser, and PVR::CPVRChannelGroupMergedByName.
SupportsMemberAdd()
virtual bool PVR::CPVRChannelGroup::SupportsMemberAdd () const pure virtual
Check whether members could be added to this group by the user.
Returns
True if members could be added, false otherwise.
Implemented in PVR::CPVRChannelGroupAllChannels, PVR::CPVRChannelGroupAllChannelsSingleClient, PVR::CPVRChannelGroupFromClient, PVR::CPVRChannelGroupFromUser, and PVR::CPVRChannelGroupMergedByName.
SupportsMemberRemove()
virtual bool PVR::CPVRChannelGroup::SupportsMemberRemove () const pure virtual
Check whether members could be removed from this group by the user.
Returns
True if members could be removed, false otherwise.
Implemented in PVR::CPVRChannelGroupAllChannels, PVR::CPVRChannelGroupAllChannelsSingleClient, PVR::CPVRChannelGroupFromClient, PVR::CPVRChannelGroupFromUser, and PVR::CPVRChannelGroupMergedByName.
Unload()
void CPVRChannelGroup::Unload ()
Clear all data.
References m_critSection, m_failedClients, m_members, and m_sortedMembers.
UpdateChannelNumbersFromAllChannelsGroup()
bool CPVRChannelGroup::UpdateChannelNumbersFromAllChannelsGroup ()
Update the channel numbers according to the all channels group and publish event.
Returns
True, if a channel number was changed, false otherwise.
References PVR::ChannelGroup, PVR::ChannelGroupInvalidated, PVR::IGNORE_NUMBERING_FROM_ONE, IsChannelsOwner(), m_critSection, m_events, CEventSource< Event >::Publish(), Renumber(), and SortAndRenumber().
UpdateClientPriorities()
void CPVRChannelGroup::UpdateClientPriorities ()
Update the client priority for this group and all members of this group.
References GetClientPriority(), m_clientPriority, m_critSection, SortAndRenumber(), and UpdateMembersClientPriority().
UpdateFromClient()
bool CPVRChannelGroup::UpdateFromClient (const std::shared_ptr< CPVRChannelGroupMember > & groupMember) private
Update this group's data with a channel group member provided by a client.
Parameters
groupMember The updated group member.
Returns
True if group member data were changed, false otherwise.
References GetByUniqueID(), CDateTime::GetUTCDateTime(), GroupID(), GroupName(), INVALID_GROUP_ID, IsChannelsOwner(), IsRadio(), LOGDEBUG, LOGPVR, m_critSection, m_members, and m_sortedMembers.
UpdateFromClients()
virtual bool PVR::CPVRChannelGroup::UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > & clients) pure virtual
Update data with channel group members from the given clients, sync with local data.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
Returns
True on success, false otherwise.
Implemented in PVR::CPVRChannelGroupAllChannels, PVR::CPVRChannelGroupAllChannelsSingleClient, PVR::CPVRChannelGroupFromClient, PVR::CPVRChannelGroupFromUser, and PVR::CPVRChannelGroupMergedByName.
UpdateGroupEntries()
bool CPVRChannelGroup::UpdateGroupEntries (const std::vector< std::shared_ptr< CPVRChannelGroupMember > > & groupMembers) protected
Update the current channel group members with the given list.
Parameters
groupMembers The group members to use to update this list.
Returns
True if everything went well, false otherwise.
References AddAndUpdateGroupMembers(), PVR::ChannelGroup, PVR::ChannelGroupInvalidated, HasNewChannels(), m_critSection, m_events, Persist(), CEventSource< Event >::Publish(), RemoveDeletedGroupMembers(), SortAndRenumber(), and UpdateMembersClientPriority().
Referenced by PVR::CPVRChannelGroupAllChannels::UpdateFromClients(), PVR::CPVRChannelGroupFromClient::UpdateFromClients(), PVR::CPVRChannelGroupAllChannelsSingleClient::UpdateGroupMembers(), and PVR::CPVRChannelGroupMergedByName::UpdateGroupMembers().
UpdateGroupMembers()
virtual bool PVR::CPVRChannelGroup::UpdateGroupMembers (const std::shared_ptr< CPVRChannelGroup > & allChannelsGroup, const std::vector< std::shared_ptr< CPVRChannelGroup > > & allChannelGroups) inline virtual
Update all group members.
Parameters
allChannelsGroup The all channels group.
allChannelGroups All available channel groups.
Returns
True on success, false otherwise.
Reimplemented in PVR::CPVRChannelGroupAllChannelsSingleClient, and PVR::CPVRChannelGroupMergedByName.
UpdateMembersClientPriority()
bool CPVRChannelGroup::UpdateMembersClientPriority () protected
Update the client priority for all members of this group.
References PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), GetSettings(), m_critSection, and m_sortedMembers.
Referenced by UpdateClientPriorities(), UpdateGroupEntries(), and UseBackendChannelOrderChanged().
UseBackendChannelNumbersChanged()
void CPVRChannelGroup::UseBackendChannelNumbersChanged () override virtual
Reimplemented from PVR::IChannelGroupSettingsCallback.
References OnSettingChanged().
UseBackendChannelOrderChanged()
void CPVRChannelGroup::UseBackendChannelOrderChanged () override virtual
Reimplemented from PVR::IChannelGroupSettingsCallback.
References m_critSection, OnSettingChanged(), and UpdateMembersClientPriority().
Friends And Related Symbol Documentation
CPVRDatabase
friend class CPVRDatabase friend
Member Data Documentation
INVALID_GROUP_ID
const int PVR::CPVRChannelGroup::INVALID_GROUP_ID = -1 static
Referenced by Persist(), and UpdateFromClient().
m_allChannelsGroup
std::shared_ptr<const CPVRChannelGroup> PVR::CPVRChannelGroup::m_allChannelsGroup private
Referenced by Renumber().
m_bChanged
bool PVR::CPVRChannelGroup::m_bChanged protected
Initial value:
=
      false
true if anything changed in this group that hasn't been persisted, false otherwise
Referenced by HasChanges(), Persist(), SetClientGroupName(), SetClientID(), SetClientPosition(), SetGroupName(), SetHidden(), SetPath(), and SetPosition().
m_bDeleted
bool PVR::CPVRChannelGroup::m_bDeleted = false private
Referenced by Delete(), and IsDeleted().
m_bHidden
bool PVR::CPVRChannelGroup::m_bHidden = false protected
true if this group is hidden, false otherwise
Referenced by IsHidden(), and SetHidden().
m_bLoaded
bool PVR::CPVRChannelGroup::m_bLoaded = false protected
True if this container is loaded, false otherwise
Referenced by LoadFromDatabase(), Persist(), SetClientGroupName(), SetClientID(), SetClientPosition(), SetGroupName(), SetHidden(), SetLastOpened(), SetLastWatched(), SetPath(), and SetPosition().
m_clientGroupName
std::string PVR::CPVRChannelGroup::m_clientGroupName private
Referenced by ClientGroupName(), operator==(), and SetClientGroupName().
m_clientPriority
std::optional<int> PVR::CPVRChannelGroup::m_clientPriority mutable private
Referenced by GetClientPriority(), operator==(), and UpdateClientPriorities().
m_critSection
CCriticalSection PVR::CPVRChannelGroup::m_critSection mutable protected
Referenced by AppendToGroup(), CleanupCachedImages(), ClientGroupName(), Delete(), GetByChannelID(), GetByChannelNumber(), GetByUniqueID(), GetChannelCountByProvider(), GetChannelNumber(), GetChannelNumbers(), GetClientChannelNumber(), GetClientID(), GetClientPosition(), GetClientPriority(), GetLastAndPreviousToLastPlayedChannelGroupMember(), GetLastPlayedChannelGroupMember(), GetMembers(), GetNextChannelGroupMember(), GetPath(), GetPosition(), GetPreviousChannelGroupMember(), GetSettings(), GroupName(), HasChanges(), HasChannelForProvider(), HasChannels(), HasHiddenChannels(), HasNewChannels(), IsGroupMember(), IsHidden(), IsNew(), IsRadio(), LastOpened(), LastWatched(), LoadFromDatabase(), OnSettingChanged(), Persist(), RemoveDeletedGroupMembers(), RemoveFromGroup(), Renumber(), SetClientGroupName(), SetClientID(), SetClientPosition(), SetGroupID(), SetGroupName(), SetHidden(), SetLastOpened(), SetLastWatched(), SetPath(), SetPosition(), ShouldBeIgnored(), PVR::CPVRChannelGroupMergedByName::ShouldBeIgnored(), Size(), SortAndRenumber(), SortByChannelNumber(), SortByClientChannelNumber(), Unload(), UpdateChannelNumbersFromAllChannelsGroup(), UpdateClientPriorities(), UpdateFromClient(), UpdateGroupEntries(), UpdateMembersClientPriority(), and UseBackendChannelOrderChanged().
m_events
CEventSource<PVREvent> PVR::CPVRChannelGroup::m_events protected
Referenced by Events(), OnSettingChanged(), UpdateChannelNumbersFromAllChannelsGroup(), and UpdateGroupEntries().
m_failedClients
std::vector<int> PVR::CPVRChannelGroup::m_failedClients protected
Referenced by HasValidDataForClient(), HasValidDataForClients(), Unload(), PVR::CPVRChannelGroupAllChannels::UpdateFromClients(), and PVR::CPVRChannelGroupFromClient::UpdateFromClients().
m_iClientPosition
int PVR::CPVRChannelGroup::m_iClientPosition {0} private
Referenced by GetClientPosition(), operator==(), and SetClientPosition().
m_iGroupId
int PVR::CPVRChannelGroup::m_iGroupId = INVALID_GROUP_ID protected
The ID of this group in the database
Referenced by Delete(), GroupID(), IsNew(), LoadFromDatabase(), operator==(), Persist(), and SetGroupID().
m_iLastOpened
uint64_t PVR::CPVRChannelGroup::m_iLastOpened = 0 protected
time in milliseconds from epoch this group was last opened
Referenced by LastOpened(), and SetLastOpened().
m_iLastWatched
time_t PVR::CPVRChannelGroup::m_iLastWatched = 0 protected
last time group has been watched
Referenced by LastWatched(), and SetLastWatched().
m_iPosition
int PVR::CPVRChannelGroup::m_iPosition = 0 protected
the local position of this group within the group list
Referenced by GetPosition(), operator==(), and SetPosition().
m_isUserSetName
bool PVR::CPVRChannelGroup::m_isUserSetName {false} private
Referenced by IsUserSetName(), operator==(), and SetGroupName().
m_members
std::map<std::pair<int, int>, std::shared_ptr<CPVRChannelGroupMember> > PVR::CPVRChannelGroup::m_members protected
members with key clientid+uniqueid
Referenced by AppendToGroup(), CleanupCachedImages(), GetByChannelID(), GetByUniqueID(), GetChannelCountByProvider(), GetLastPlayedChannelGroupMember(), HasChannelForProvider(), HasChannels(), HasHiddenChannels(), HasNewChannels(), IsGroupMember(), LoadFromDatabase(), LoadFromDatabase(), Persist(), RemoveDeletedGroupMembers(), RemoveFromGroup(), SetGroupID(), ShouldBeIgnored(), PVR::CPVRChannelGroupMergedByName::ShouldBeIgnored(), Size(), Unload(), and UpdateFromClient().
m_path
CPVRChannelsPath PVR::CPVRChannelGroup::m_path private
Referenced by GetClientID(), GetPath(), GroupName(), IsRadio(), operator==(), SetClientID(), SetGroupName(), and SetPath().
m_settings
std::shared_ptr<CPVRChannelGroupSettings> PVR::CPVRChannelGroup::m_settings mutable protected
Referenced by GetSettings().
m_settingsSingleton
std::weak_ptr< CPVRChannelGroupSettings > CPVRChannelGroup::m_settingsSingleton static protected
Referenced by GetSettings().
m_settingsSingletonCritSection
CCriticalSection CPVRChannelGroup::m_settingsSingletonCritSection static protected
Referenced by GetSettings().
m_sortedMembers
std::vector<std::shared_ptr<CPVRChannelGroupMember> > PVR::CPVRChannelGroup::m_sortedMembers protected
members sorted by channel number
Referenced by AppendToGroup(), GetByChannelNumber(), GetChannelNumbers(), GetLastAndPreviousToLastPlayedChannelGroupMember(), GetMembers(), GetNextChannelGroupMember(), GetPreviousChannelGroupMember(), LoadFromDatabase(), RemoveDeletedGroupMembers(), RemoveFromGroup(), Renumber(), SetGroupName(), SortByChannelNumber(), SortByClientChannelNumber(), Unload(), UpdateFromClient(), and UpdateMembersClientPriority().
The documentation for this class was generated from the following files:
PVRChannelGroup.h
PVRChannelGroup.cpp