Kodi Documentation: KODI::GUILIB::GUIINFO Namespace Reference
KODI::GUILIB::GUIINFO Namespace Reference
Namespaces
namespace anonymous_namespace{GUIInfoHelper.cpp}
Classes
class CAddonsGUIInfo
class CGamesGUIInfo
class CGUIControlsGUIInfo
class CGUIInfo
class CGUIInfoBool
class CGUIInfoColor
class CGUIInfoLabel
class CGUIInfoProvider
class CGUIInfoProviders
class CLibraryGUIInfo
class CMusicGUIInfo
class CPicturesGUIInfo
class CPlayerGUIInfo
class CSkinGUIInfo
class CSystemGUIInfo
class CVideoGUIInfo
class CVisualisationGUIInfo
class CWeatherGUIInfo
class IGUIInfoProvider
struct PlayerShowInfoChangedEvent
Functions
std::string GetPlaylistLabel (int item, PLAYLIST::Id playlistId)
CGUIWindow * GetWindow (int contextWindow)
CFileItemPtr GetCurrentListItemFromWindow (int contextWindow)
CGUIMediaWindow * GetMediaWindow (int contextWindow)
CGUIControl * GetActiveContainer (int containerId, int contextWindow)
std::shared_ptr< CGUIListItem > GetCurrentListItem (int contextWindow, int containerId, int itemOffset, unsigned int itemFlags)
std::string GetFileInfoLabelValueFromPath (int info, const std::string &filenameAndPath)
Variables
static const int WINDOW_CONDITION_HAS_LIST_ITEMS = 1
static const int WINDOW_CONDITION_IS_MEDIA_WINDOW = 2
Function Documentation
GetActiveContainer()
CGUIControl * KODI::GUILIB::GUIINFO::GetActiveContainer (int containerId, int contextWindow)
References CGUIControlLookup::GetControl(), CGUIControlGroup::GetFocusedControl(), GetWindow(), CGUIControl::IsContainer(), and CGUIWindow::IsMediaWindow().
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), and GetCurrentListItem().
GetCurrentListItem()
std::shared_ptr< CGUIListItem > KODI::GUILIB::GUIINFO::GetCurrentListItem (int contextWindow, int containerId, int itemOffset, unsigned int itemFlags)
References GetActiveContainer(), GetCurrentListItemFromWindow(), INFOFLAG_LISTITEM_ABSOLUTE, INFOFLAG_LISTITEM_CONTAINER, and INFOFLAG_LISTITEM_POSITION.
Referenced by CGUIInfoManager::GetBool(), CGUIInfoManager::GetImage(), CGUIInfoManager::GetInt(), CGUIInfoManager::GetLabel(), CGUIInfoManager::GetMultiInfoBool(), CGUIInfoManager::GetMultiInfoInt(), and CGUIInfoManager::GetMultiInfoLabel().
GetCurrentListItemFromWindow()
CFileItemPtr KODI::GUILIB::GUIINFO::GetCurrentListItemFromWindow (int contextWindow)
References CGUIWindow::GetCurrentListItem(), and WINDOW_CONDITION_HAS_LIST_ITEMS.
Referenced by GetCurrentListItem().
GetFileInfoLabelValueFromPath()
std::string KODI::GUILIB::GUIINFO::GetFileInfoLabelValueFromPath (int info, const std::string & filenameAndPath)
References URIUtils::GetFileName(), URIUtils::GetParentPath(), URIUtils::IsInArchive(), PLAYER_FILENAME, PLAYER_PATH, and value.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel(), and KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel().
GetMediaWindow()
CGUIMediaWindow * KODI::GUILIB::GUIINFO::GetMediaWindow (int contextWindow)
References WINDOW_CONDITION_IS_MEDIA_WINDOW.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), and KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel().
GetPlaylistLabel()
std::string KODI::GUILIB::GUIINFO::GetPlaylistLabel (int item, PLAYLIST::Id playlistId)
References KODI::PLAYLIST::ALL, g_localizeStrings, CLocalizeStrings::Get(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), KODI::PLAYLIST::CPlayListPlayer::GetRepeat(), KODI::PLAYLIST::CPlayListPlayer::IsShuffled(), KODI::PLAYLIST::ONE, PLAYLIST_LENGTH, PLAYLIST_POSITION, PLAYLIST_RANDOM, PLAYLIST_REPEAT, KODI::PLAYLIST::CPlayList::size(), and KODI::PLAYLIST::TYPE_NONE.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel(), and KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel().
GetWindow()
CGUIWindow * KODI::GUILIB::GUIINFO::GetWindow (int contextWindow)
Referenced by GetActiveContainer(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), and KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel().
Variable Documentation
WINDOW_CONDITION_HAS_LIST_ITEMS
const int KODI::GUILIB::GUIINFO::WINDOW_CONDITION_HAS_LIST_ITEMS = 1 static
Referenced by KODI::GUILIB::GUIINFO::anonymous_namespace{GUIInfoHelper.cpp}::CheckWindowCondition(), and GetCurrentListItemFromWindow().
WINDOW_CONDITION_IS_MEDIA_WINDOW
const int KODI::GUILIB::GUIINFO::WINDOW_CONDITION_IS_MEDIA_WINDOW = 2 static
Referenced by KODI::GUILIB::GUIINFO::anonymous_namespace{GUIInfoHelper.cpp}::CheckWindowCondition(), and GetMediaWindow().