Kodi Documentation: CDVDDemuxBXA Class Reference
CDVDDemuxBXA Class Reference
#include <DVDDemuxBXA.h>
Public Member Functions
CDVDDemuxBXA ()
~CDVDDemuxBXA () override
bool Open (const std::shared_ptr< CDVDInputStream > &pInput)
void Dispose ()
bool Reset () override
void Abort () override
void Flush () override
DemuxPacket * Read () override
bool SeekTime (double time, bool backwards=false, double *startpts=NULL) override
int GetStreamLength () override
CDemuxStream * GetStream (int iStreamId) const override
std::vector< CDemuxStream * > GetStreams () const override
int GetNrOfStreams () const override
std::string GetFileName () override
std::string GetStreamCodecName (int iStreamId) override
Public Member Functions inherited from CDVDDemux
CDVDDemux ()
virtual ~CDVDDemux ()=default
virtual bool SeekChapter (int chapter, double *startpts=NULL)
virtual int GetChapterCount ()
virtual int GetChapter ()
virtual void GetChapterName (std::string &strChapterName, int chapterIdx=-1)
virtual int64_t GetChapterPos (int chapterIdx=-1)
virtual void SetSpeed (int iSpeed)
virtual void FillBuffer (bool mode)
virtual CDemuxStream * GetStream (int64_t demuxerId, int iStreamId) const
virtual int GetPrograms (std::vector< ProgramInfo > &programs)
virtual void SetProgram (int progId)
int GetNrOfSubtitleStreams ()
virtual std::string GetStreamCodecName (int64_t demuxerId, int iStreamId)
virtual void EnableStream (int64_t demuxerId, int id, bool enable)
virtual void OpenStream (int64_t demuxerId, int id)
virtual void SetVideoResolution (unsigned int width, unsigned int height)
int64_t GetDemuxerId ()
Protected Attributes
std::shared_ptr< CDVDInputStream > m_pInput
int64_t m_bytes
CDemuxStreamAudioBXA * m_stream
Demux_BXA_FmtHeader m_header
Protected Attributes inherited from CDVDDemux
int64_t m_demuxerId
Friends
class CDemuxStreamAudioBXA
Additional Inherited Members
Protected Member Functions inherited from CDVDDemux
virtual void EnableStream (int id, bool enable)
virtual void OpenStream (int id)
int GetNrOfStreams (StreamType streamType)
Constructor & Destructor Documentation
CDVDDemuxBXA()
CDVDDemuxBXA::CDVDDemuxBXA ()
References m_bytes, m_header, and m_stream.
~CDVDDemuxBXA()
CDVDDemuxBXA::~CDVDDemuxBXA () override
References Dispose().
Member Function Documentation
Abort()
void CDVDDemuxBXA::Abort () override virtual
Reimplemented from CDVDDemux.
References m_pInput.
Referenced by Open().
Dispose()
void CDVDDemuxBXA::Dispose ()
References m_bytes, m_header, m_pInput, and m_stream.
Referenced by Open(), Reset(), and ~CDVDDemuxBXA().
Flush()
void CDVDDemuxBXA::Flush () override virtual
Implements CDVDDemux.
GetFileName()
std::string CDVDDemuxBXA::GetFileName () override virtual
Reimplemented from CDVDDemux.
References m_pInput.
GetNrOfStreams()
int CDVDDemuxBXA::GetNrOfStreams () const override virtual
Implements CDVDDemux.
References m_stream.
GetStream()
CDemuxStream * CDVDDemuxBXA::GetStream (int iStreamId) const override virtual
Implements CDVDDemux.
References m_stream.
GetStreamCodecName()
std::string CDVDDemuxBXA::GetStreamCodecName (int iStreamId) override virtual
Reimplemented from CDVDDemux.
References m_stream.
GetStreamLength()
int CDVDDemuxBXA::GetStreamLength () inline override virtual
Reimplemented from CDVDDemux.
References m_header.
GetStreams()
std::vector< CDemuxStream * > CDVDDemuxBXA::GetStreams () const override virtual
Implements CDVDDemux.
References m_stream.
Open()
bool CDVDDemuxBXA::Open (const std::shared_ptr< CDVDInputStream > & pInput)
References Abort(), BXA_PACKET_TYPE_FMT_DEMUX, CDemuxStreamAudioBXA, CDemuxStream::codec, Dispose(), DVDSTREAM_TYPE_FILE, CDemuxStreamAudio::iBitRate, CDemuxStreamAudio::iBitsPerSample, CDemuxStreamAudio::iChannels, CDemuxStreamAudio::iSampleRate, m_header, m_pInput, m_stream, STREAM_AUDIO, and CDemuxStream::type.
Referenced by Reset().
Read()
DemuxPacket * CDVDDemuxBXA::Read () override virtual
Implements CDVDDemux.
References CDVDDemuxUtils::AllocateDemuxPacket(), BXA_READ_SIZE, DEMUX_PACKET::dts, DVD_NOPTS_VALUE, DVD_TIME_BASE, DEMUX_PACKET::iSize, DEMUX_PACKET::iStreamId, m_bytes, m_header, m_pInput, DEMUX_PACKET::pData, and DEMUX_PACKET::pts.
Reset()
bool CDVDDemuxBXA::Reset () override virtual
Implements CDVDDemux.
References Dispose(), m_pInput, and Open().
SeekTime()
bool CDVDDemuxBXA::SeekTime (double time, bool backwards = false, double * startpts = NULL) inline override virtual
Implements CDVDDemux.
Friends And Related Symbol Documentation
CDemuxStreamAudioBXA
friend class CDemuxStreamAudioBXA friend
Referenced by Open().
Member Data Documentation
m_bytes
int64_t CDVDDemuxBXA::m_bytes protected
Referenced by CDVDDemuxBXA(), Dispose(), and Read().
m_header
Demux_BXA_FmtHeader CDVDDemuxBXA::m_header protected
Referenced by CDVDDemuxBXA(), Dispose(), GetStreamLength(), Open(), and Read().
m_pInput
std::shared_ptr<CDVDInputStream> CDVDDemuxBXA::m_pInput protected
Referenced by Abort(), Dispose(), GetFileName(), Open(), Read(), and Reset().
m_stream
CDemuxStreamAudioBXA* CDVDDemuxBXA::m_stream protected
Referenced by CDVDDemuxBXA(), Dispose(), GetNrOfStreams(), GetStream(), GetStreamCodecName(), GetStreams(), and Open().
The documentation for this class was generated from the following files:
DVDDemuxBXA.h
DVDDemuxBXA.cpp