Kodi Documentation: KODI::MOUSE::IMouseInputProvider Class Reference
KODI::MOUSE::IMouseInputProvider Class Reference abstract
Input » Mouse
Interface for classes that can provide mouse input.
#include <IMouseInputProvider.h>
Public Member Functions
virtual ~IMouseInputProvider ()=default
virtual void RegisterMouseHandler (IMouseInputHandler *handler, bool bPromiscuous, bool forceDefaultMap)=0
Registers a handler to be called on mouse input.
virtual void UnregisterMouseHandler (IMouseInputHandler *handler)=0
Unregisters handler from mouse input.
Detailed Description
Interface for classes that can provide mouse input.
Constructor & Destructor Documentation
~IMouseInputProvider()
virtual KODI::MOUSE::IMouseInputProvider::~IMouseInputProvider () virtual default
Member Function Documentation
RegisterMouseHandler()
virtual void KODI::MOUSE::IMouseInputProvider::RegisterMouseHandler (IMouseInputHandler * handler, bool bPromiscuous, bool forceDefaultMap) pure virtual
Registers a handler to be called on mouse input.
Parameters
handler The handler to receive mouse input provided by this class
bPromiscuous True to observe all events without affecting subsequent handlers
forceDefaultMap Always use the default keyboard buttonmap, avoiding buttonmaps provided by add-ons
Implemented in PERIPHERALS::CPeripheral.
Referenced by KODI::GAME::CGameClientMouse::CGameClientMouse(), and KODI::GAME::CAgentMouse::Initialize().
UnregisterMouseHandler()
virtual void KODI::MOUSE::IMouseInputProvider::UnregisterMouseHandler (IMouseInputHandler * handler) pure virtual
Unregisters handler from mouse input.
Parameters
handler The handler that was receiving mouse input
Implemented in PERIPHERALS::CPeripheral.
Referenced by KODI::GAME::CAgentMouse::Deinitialize(), and KODI::GAME::CGameClientMouse::~CGameClientMouse().
The documentation for this class was generated from the following file:
IMouseInputProvider.h