Kodi Documentation: XBMCAddon::xbmc::Monitor Class Reference
XBMCAddon::xbmc::Monitor Class Reference
Python » Library - xbmc » Monitor
#include <Monitor.h>
Public Member Functions
Monitor ()
void OnSettingsChanged ()
void OnScreensaverActivated ()
void OnScreensaverDeactivated ()
void OnDPMSActivated ()
void OnDPMSDeactivated ()
void OnScanStarted (const String &library)
void OnScanFinished (const String &library)
void OnCleanStarted (const String &library)
void OnCleanFinished (const String &library)
void OnNotification (const String &sender, const String &method, const String &data)
const String & GetId ()
long GetInvokerId ()
void AbortNotify ()
onSettingsChanged ()
Function: onSettingsChanged()
onSettingsChanged method.
onScreensaverActivated ()
Function: onScreensaverActivated()
onScreensaverActivated method.
onScreensaverDeactivated ()
Function: onScreensaverDeactivated()
onScreensaverDeactivated method.
onDPMSActivated ()
Function: onDPMSActivated()
onDPMSActivated method.
onDPMSDeactivated ()
Function: onDPMSDeactivated()
onDPMSDeactivated method.
onScanStarted (...)
Function: onScanStarted(library)
onScanStarted method.
onScanFinished (...)
Function: onScanFinished(library)
onScanFinished method.
onCleanStarted (...)
Function: onCleanStarted(library)
onCleanStarted method.
onCleanFinished (...)
Function: onCleanFinished(library)
onCleanFinished method.
onNotification (...)
Function: onNotification(sender, method, data)
onNotification method.
waitForAbort (...)
Function: waitForAbort([timeout])
Wait for Abort
abortRequested ()
Function: abortRequested()
Returns True if abort has been requested.
~Monitor () override
Public Member Functions inherited from XBMCAddon::AddonCallback
~AddonCallback () override
void setHandler (CallbackHandler *_handler)
void invokeCallback (Callback *callback)
Public Member Functions inherited from XBMCAddon::AddonClass
AddonClass ()
virtual ~AddonClass ()
const char * GetClassname () const
LanguageHook * GetLanguageHook ()
bool isDeallocating ()
void Release () const
void Acquire () const
Private Attributes
String Id
long invokerId
CEvent abortEvent
Additional Inherited Members
Static Public Member Functions inherited from XBMCAddon::AddonClass
static short getNumAddonClasses ()
Protected Member Functions inherited from XBMCAddon::AddonCallback
bool hasHandler ()
AddonCallback ()
Protected Member Functions inherited from XBMCAddon::AddonClass
virtual void deallocating ()
Static Protected Member Functions inherited from XBMCAddon::AddonClass
static short getNextClassIndex ()
Protected Attributes inherited from XBMCAddon::AddonCallback
AddonClass::Ref< CallbackHandler > handler
Protected Attributes inherited from XBMCAddon::AddonClass
LanguageHook * languageHook
Constructor & Destructor Documentation
Monitor()
XBMCAddon::xbmc::Monitor::Monitor ()
References XBMCAddon::LanguageHook::GetAddonId(), XBMCAddon::LanguageHook::GetInvokerId(), Id, invokerId, XBMCAddon::AddonClass::languageHook, XBMCAddon::LanguageHook::RegisterMonitorCallback(), and XBMC_TRACE.
~Monitor()
XBMCAddon::xbmc::Monitor::~Monitor () override
References XBMCAddon::AddonClass::deallocating(), XBMCAddon::AddonClass::languageHook, XBMCAddon::LanguageHook::UnregisterMonitorCallback(), and XBMC_TRACE.
Member Function Documentation
AbortNotify()
void XBMCAddon::xbmc::Monitor::AbortNotify ()
Called from XBPython to notify registered monitors that a script is aborting/ending.
References abortEvent, CEvent::Set(), and XBMC_TRACE.
GetId()
const String & XBMCAddon::xbmc::Monitor::GetId () inline
References Id.
GetInvokerId()
long XBMCAddon::xbmc::Monitor::GetInvokerId () inline
References invokerId.
OnCleanFinished()
void XBMCAddon::xbmc::Monitor::OnCleanFinished (const String & library) inline
References XBMCAddon::AddonCallback::invokeCallback(), onCleanFinished(), and XBMC_TRACE.
OnCleanStarted()
void XBMCAddon::xbmc::Monitor::OnCleanStarted (const String & library) inline
References XBMCAddon::AddonCallback::invokeCallback(), onCleanStarted(), and XBMC_TRACE.
OnDPMSActivated()
void XBMCAddon::xbmc::Monitor::OnDPMSActivated () inline
References XBMCAddon::AddonCallback::invokeCallback(), onDPMSActivated(), and XBMC_TRACE.
OnDPMSDeactivated()
void XBMCAddon::xbmc::Monitor::OnDPMSDeactivated () inline
References XBMCAddon::AddonCallback::invokeCallback(), onDPMSDeactivated(), and XBMC_TRACE.
OnNotification()
void XBMCAddon::xbmc::Monitor::OnNotification (const String & sender, const String & method, const String & data) inline
References data(), XBMCAddon::AddonCallback::invokeCallback(), onNotification(), and XBMC_TRACE.
OnScanFinished()
void XBMCAddon::xbmc::Monitor::OnScanFinished (const String & library) inline
References XBMCAddon::AddonCallback::invokeCallback(), onScanFinished(), and XBMC_TRACE.
OnScanStarted()
void XBMCAddon::xbmc::Monitor::OnScanStarted (const String & library) inline
References XBMCAddon::AddonCallback::invokeCallback(), onScanStarted(), and XBMC_TRACE.
OnScreensaverActivated()
void XBMCAddon::xbmc::Monitor::OnScreensaverActivated () inline
References XBMCAddon::AddonCallback::invokeCallback(), onScreensaverActivated(), and XBMC_TRACE.
OnScreensaverDeactivated()
void XBMCAddon::xbmc::Monitor::OnScreensaverDeactivated () inline
References XBMCAddon::AddonCallback::invokeCallback(), onScreensaverDeactivated(), and XBMC_TRACE.
OnSettingsChanged()
void XBMCAddon::xbmc::Monitor::OnSettingsChanged () inline
References XBMCAddon::AddonCallback::invokeCallback(), onSettingsChanged(), and XBMC_TRACE.
Member Data Documentation
abortEvent
CEvent XBMCAddon::xbmc::Monitor::abortEvent private
Referenced by AbortNotify(), abortRequested(), and waitForAbort().
Id
String XBMCAddon::xbmc::Monitor::Id private
Referenced by GetId(), and Monitor().
invokerId
long XBMCAddon::xbmc::Monitor::invokerId private
Referenced by GetInvokerId(), and Monitor().
The documentation for this class was generated from the following files:
Monitor.h
Monitor.cpp