Kodi Documentation: ActiveAE::CActiveAEBufferPool Class Reference
ActiveAE::CActiveAEBufferPool Class Reference
#include <ActiveAEBuffer.h>
Public Member Functions
CActiveAEBufferPool (const AEAudioFormat &format)
virtual ~CActiveAEBufferPool ()
virtual bool Create (unsigned int totaltime)
CSampleBuffer * GetFreeBuffer ()
void ReturnBuffer (CSampleBuffer *buffer)
Public Attributes
AEAudioFormat m_format
std::deque< CSampleBuffer * > m_allSamples
std::deque< CSampleBuffer * > m_freeSamples
Constructor & Destructor Documentation
CActiveAEBufferPool()
CActiveAEBufferPool::CActiveAEBufferPool (const AEAudioFormat & format) explicit
References AE_CH_FC, AE_FMT_RAW, AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, m_format, AEAudioFormat::m_frames, AEAudioFormat::m_frameSize, and CAEChannelInfo::Reset().
~CActiveAEBufferPool()
CActiveAEBufferPool::~CActiveAEBufferPool () virtual
References m_allSamples.
Member Function Documentation
Create()
bool CActiveAEBufferPool::Create (unsigned int totaltime) virtual
Reimplemented in ActiveAE::CActiveAEBufferPoolResample, and ActiveAE::CActiveAEBufferPoolAtempo.
References AE_FMT_RAW, SampleConfig::bits_per_sample, SampleConfig::channel_layout, SampleConfig::channels, CAEChannelInfo::Count(), CAEUtil::DataFormatToDitherBits(), CAEUtil::DataFormatToUsedBits(), SampleConfig::dither_bits, SampleConfig::fmt, CAEUtil::GetAVChannelLayout(), CAEUtil::GetAVSampleFormat(), CAEStreamInfo::GetDuration(), m_allSamples, AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, m_format, AEAudioFormat::m_frames, m_freeSamples, AEAudioFormat::m_sampleRate, AEAudioFormat::m_streamInfo, and SampleConfig::sample_rate.
Referenced by ActiveAE::CActiveAEBufferPoolAtempo::Create(), and ActiveAE::CActiveAEBufferPoolResample::Create().
GetFreeBuffer()
CSampleBuffer * CActiveAEBufferPool::GetFreeBuffer ()
References ActiveAE::CSampleBuffer::centerMixLevel, m_freeSamples, and ActiveAE::CSampleBuffer::refCount.
Referenced by ActiveAE::CActiveAEBufferPoolAtempo::ProcessBuffers(), and ActiveAE::CActiveAEBufferPoolResample::ResampleBuffers().
ReturnBuffer()
void CActiveAEBufferPool::ReturnBuffer (CSampleBuffer * buffer)
References m_freeSamples, and ActiveAE::CSampleBuffer::pkt.
Referenced by ActiveAE::CSampleBuffer::Return().
Member Data Documentation
m_allSamples
std::deque<CSampleBuffer*> ActiveAE::CActiveAEBufferPool::m_allSamples
Referenced by Create(), and ~CActiveAEBufferPool().
m_format
AEAudioFormat ActiveAE::CActiveAEBufferPool::m_format
Referenced by CActiveAEBufferPool(), ActiveAE::CActiveAEBufferPoolResample::CActiveAEBufferPoolResample(), ActiveAE::CActiveAEBufferPoolResample::ChangeResampler(), ActiveAE::CActiveAEBufferPoolResample::ConfigureResampler(), Create(), ActiveAE::CActiveAEBufferPoolAtempo::Create(), ActiveAE::CActiveAEBufferPoolResample::Create(), ActiveAE::CActiveAEBufferPoolResample::GetDelay(), ActiveAE::CActiveAEBufferPoolAtempo::GetDelay(), ActiveAE::CActiveAEBufferPoolAtempo::ProcessBuffers(), and ActiveAE::CActiveAEBufferPoolResample::ResampleBuffers().
m_freeSamples
std::deque<CSampleBuffer*> ActiveAE::CActiveAEBufferPool::m_freeSamples
Referenced by Create(), GetFreeBuffer(), ActiveAE::CActiveAEBufferPoolAtempo::ProcessBuffers(), ActiveAE::CActiveAEBufferPoolResample::ResampleBuffers(), and ReturnBuffer().
The documentation for this class was generated from the following files:
ActiveAEBuffer.h
ActiveAEBuffer.cpp