Kodi Documentation: KODI::JOYSTICK::CAnalogStick Class Reference
KODI::JOYSTICK::CAnalogStick Class Reference
Input » Joystick
#include <FeatureHandling.h>
Public Member Functions
CAnalogStick (const FeatureName &name, IInputHandler *handler, IButtonMap *buttonMap)
~CAnalogStick () override=default
bool OnDigitalMotion (const CDriverPrimitive &source, bool bPressed) override
A digital motion has occurred.
bool OnAnalogMotion (const CDriverPrimitive &source, float magnitude) override
An analog motion has occurred.
void ProcessMotions () override
Process the motions that have occurred since the last invocation.
Public Member Functions inherited from KODI::JOYSTICK::CJoystickFeature
CJoystickFeature (const FeatureName &name, IInputHandler *handler, IButtonMap *buttonMap)
virtual ~CJoystickFeature ()=default
bool AcceptsInput (bool bActivation)
Check if the input handler is accepting input.
Protected Attributes
CFeatureAxis m_vertAxis
CFeatureAxis m_horizAxis
float m_vertState = 0.0f
float m_horizState = 0.0f
Protected Attributes inherited from KODI::JOYSTICK::CJoystickFeature
const FeatureName m_name
IInputHandler *const m_handler
IButtonMap *const m_buttonMap
const bool m_bEnabled
Additional Inherited Members
Protected Member Functions inherited from KODI::JOYSTICK::CJoystickFeature
void ResetMotion ()
Reset motion timer.
void StartMotion ()
Start the motion timer.
bool InMotion () const
Check if the feature is in motion.
unsigned int MotionTimeMs () const
Get the time for which the feature has been in motion.
Constructor & Destructor Documentation
CAnalogStick()
CAnalogStick::CAnalogStick (const FeatureName & name, IInputHandler * handler, IButtonMap * buttonMap)
~CAnalogStick()
KODI::JOYSTICK::CAnalogStick::~CAnalogStick () override default
Member Function Documentation
OnAnalogMotion()
bool CAnalogStick::OnAnalogMotion (const CDriverPrimitive & source, float magnitude) override virtual
An analog motion has occurred.
Parameters
source The source of the motion. Must be a semiaxis
magnitude The magnitude of the press or motion in the interval [0.0, 1.0]
For semiaxes, the magnitude is the force or travel distance in the direction of the semiaxis. If the value is in the opposite direction, the magnitude is 0.0.
For example, if the analog stick goes left, the negative semiaxis will have a value of 1.0 and the positive semiaxis will have a value of 0.0.
Implements KODI::JOYSTICK::CJoystickFeature.
References KODI::JOYSTICK::CJoystickFeature::AcceptsInput(), KODI::JOYSTICK::IButtonMap::GetAnalogStick(), KODI::JOYSTICK::CJoystickFeature::m_buttonMap, m_horizAxis, KODI::JOYSTICK::CJoystickFeature::m_name, m_vertAxis, KODI::JOYSTICK::CFeatureAxis::Reset(), KODI::JOYSTICK::CFeatureAxis::SetNegativeDistance(), and KODI::JOYSTICK::CFeatureAxis::SetPositiveDistance().
Referenced by OnDigitalMotion().
OnDigitalMotion()
bool CAnalogStick::OnDigitalMotion (const CDriverPrimitive & source, bool bPressed) override virtual
A digital motion has occurred.
Parameters
source The source of the motion. Must be digital (button or hat)
bPressed True for press motion, false for release motion
Returns
true if the motion was handled, false otherwise
Implements KODI::JOYSTICK::CJoystickFeature.
References OnAnalogMotion().
ProcessMotions()
void CAnalogStick::ProcessMotions () override virtual
Process the motions that have occurred since the last invocation.
This allows features with motion on multiple driver primitives to call their handler once all driver primitives are accounted for.
Implements KODI::JOYSTICK::CJoystickFeature.
References KODI::JOYSTICK::IInputHandler::ControllerID(), KODI::JOYSTICK::CFeatureAxis::GetPosition(), KODI::JOYSTICK::CJoystickFeature::InMotion(), CLog::Log(), LOGDEBUG, KODI::JOYSTICK::CJoystickFeature::m_handler, m_horizAxis, m_horizState, KODI::JOYSTICK::CJoystickFeature::m_name, m_vertAxis, m_vertState, KODI::JOYSTICK::CJoystickFeature::MotionTimeMs(), KODI::JOYSTICK::IInputHandler::OnAnalogStickMotion(), KODI::JOYSTICK::CJoystickFeature::ResetMotion(), and KODI::JOYSTICK::CJoystickFeature::StartMotion().
Member Data Documentation
m_horizAxis
CFeatureAxis KODI::JOYSTICK::CAnalogStick::m_horizAxis protected
Referenced by OnAnalogMotion(), and ProcessMotions().
m_horizState
float KODI::JOYSTICK::CAnalogStick::m_horizState = 0.0f protected
Referenced by ProcessMotions().
m_vertAxis
CFeatureAxis KODI::JOYSTICK::CAnalogStick::m_vertAxis protected
Referenced by OnAnalogMotion(), and ProcessMotions().
m_vertState
float KODI::JOYSTICK::CAnalogStick::m_vertState = 0.0f protected
Referenced by ProcessMotions().
The documentation for this class was generated from the following files:
FeatureHandling.h
FeatureHandling.cpp