Kodi Documentation: CAESinkFactoryWin Class Reference
CAESinkFactoryWin Class Reference
#include <AESinkFactoryWin.h>
Static Public Member Functions
static std::vector< RendererDetail > GetRendererDetails ()
static std::vector< RendererDetail > GetRendererDetailsWinRT ()
static std::string GetDefaultDeviceId ()
static HRESULT ActivateWASAPIDevice (std::string &device, IAEWASAPIDevice **ppDevice)
static void AEChannelsFromSpeakerMask (CAEChannelInfo &channelLayout, DWORD speakers)
static DWORD SpeakerMaskFromAEChannels (const CAEChannelInfo &channels)
static DWORD ChLayoutToChMask (const enum AEChannel *layout, unsigned int *numberOfChannels=NULL)
static void BuildWaveFormatExtensible (AEAudioFormat &format, WAVEFORMATEXTENSIBLE &wfxex)
Member Function Documentation
ActivateWASAPIDevice()
HRESULT CAESinkFactoryWin::ActivateWASAPIDevice (std::string & device, IAEWASAPIDevice ** ppDevice) static
References IAEWASAPIDevice::deviceId.
Referenced by CAESinkWASAPI::EnumerateDevicesEx(), and CAESinkWASAPI::Initialize().
AEChannelsFromSpeakerMask()
void CAESinkFactoryWin::AEChannelsFromSpeakerMask (CAEChannelInfo & channelLayout, DWORD speakers) static
References AEChannelNames, CAEChannelInfo::Reset(), WASAPI_SPEAKER_COUNT, and WASAPIChannelOrder.
Referenced by CAESinkWASAPI::InitializeExclusive(), and CAESinkXAudio::InitializeInternal().
BuildWaveFormatExtensible()
void CAESinkFactoryWin::BuildWaveFormatExtensible (AEAudioFormat & format, WAVEFORMATEXTENSIBLE & wfxex) static
References AE_FMT_FLOAT, AE_FMT_RAW, AE_FMT_S24NE4MSB, bool(), CAEUtil::DataFormatToBits(), CLog::Log(), LOGERROR, SpeakerMaskFromAEChannels(), CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Referenced by CAESinkWASAPI::BuildWaveFormatExtensibleIEC61397(), CAESinkWASAPI::InitializeExclusive(), and CAESinkXAudio::InitializeInternal().
ChLayoutToChMask()
DWORD CAESinkFactoryWin::ChLayoutToChMask (const enum AEChannel * layout, unsigned int * numberOfChannels = NULL) static
References AE_CH_NULL, and WASAPIChannelOrder.
Referenced by CAESinkWASAPI::InitializeExclusive(), and CAESinkXAudio::InitializeInternal().
GetDefaultDeviceId()
std::string CAESinkFactoryWin::GetDefaultDeviceId () static
References KODI::PLATFORM::WINDOWS::FromW().
Referenced by CAESinkWASAPI::Initialize().
GetRendererDetails()
std::vector< RendererDetail > CAESinkFactoryWin::GetRendererDetails () static
References GetRendererDetailsWinRT().
Referenced by CAESinkWASAPI::EnumerateDevicesEx(), and CAESinkDirectSound::Initialize().
GetRendererDetailsWinRT()
std::vector< RendererDetail > CAESinkFactoryWin::GetRendererDetailsWinRT () static
References winEndpointsToAEDeviceType::aeDeviceType, RendererDetail::bDefault, RendererDetail::eDeviceType, KODI::PLATFORM::WINDOWS::FromW(), LOGERROR, RendererDetail::nChannels, PKEY_AudioEndpoint_FormFactor, PKEY_AudioEndpoint_GUID, PKEY_AudioEndpoint_PhysicalSpeakers, PKEY_AudioEngine_DeviceFormat, PKEY_Device_EnumeratorName, RendererDetail::strDescription, RendererDetail::strDeviceId, RendererDetail::strWinDevType, RendererDetail::uiChannelMask, Wait(), winEndpoints, and winEndpointsToAEDeviceType::winEndpointType.
Referenced by CAESinkXAudio::EnumerateDevicesEx(), and GetRendererDetails().
SpeakerMaskFromAEChannels()
DWORD CAESinkFactoryWin::SpeakerMaskFromAEChannels (const CAEChannelInfo & channels) static
References AEChannelNames, WASAPI_SPEAKER_COUNT, and WASAPIChannelOrder.
Referenced by BuildWaveFormatExtensible(), and CAESinkWASAPI::InitializeExclusive().
The documentation for this class was generated from the following files:
AESinkFactoryWin.h
AESinkFactoryWin.cpp
AESinkFactoryWin10.cpp
AESinkFactoryWin32.cpp
AESinkFactoryWinRT.cpp