Kodi Documentation: CSettingDependencyConditionCombination Class Reference
CSettingDependencyConditionCombination Class Reference
#include <SettingDependency.h>
Public Member Functions
CSettingDependencyConditionCombination (CSettingsManager *settingsManager=nullptr)
CSettingDependencyConditionCombination (BooleanLogicOperation op, CSettingsManager *settingsManager=nullptr)
~CSettingDependencyConditionCombination () override=default
bool Deserialize (const TiXmlNode *node) override
const std::set< std::string > & GetSettings () const
CSettingDependencyConditionCombination * Add (const CSettingDependencyConditionPtr &condition)
CSettingDependencyConditionCombination * Add (const CSettingDependencyConditionCombinationPtr &operation)
Public Member Functions inherited from CSettingConditionCombination
CSettingConditionCombination (CSettingsManager *settingsManager=nullptr)
~CSettingConditionCombination () override=default
bool Check () const override
Public Member Functions inherited from CBooleanLogicOperation
CBooleanLogicOperation (BooleanLogicOperation op=BooleanLogicOperationAnd)
~CBooleanLogicOperation () override=default
virtual BooleanLogicOperation GetOperation () const
virtual const CBooleanLogicOperations & GetOperations () const
virtual const CBooleanLogicValues & GetValues () const
virtual void SetOperation (BooleanLogicOperation op)
Public Member Functions inherited from IXmlDeserializable
virtual ~IXmlDeserializable ()=default
Public Member Functions inherited from ISettingCondition
ISettingCondition (CSettingsManager *settingsManager)
virtual ~ISettingCondition ()=default
Private Member Functions
CBooleanLogicOperation * newOperation () override
CBooleanLogicValue * newValue () override
Private Attributes
std::set< std::string > m_settings
Additional Inherited Members
Protected Attributes inherited from CBooleanLogicOperation
BooleanLogicOperation m_operation
CBooleanLogicOperations m_operations
CBooleanLogicValues m_values
Protected Attributes inherited from ISettingCondition
CSettingsManager * m_settingsManager
Constructor & Destructor Documentation
CSettingDependencyConditionCombination() [1/2]
CSettingDependencyConditionCombination::CSettingDependencyConditionCombination (CSettingsManager * settingsManager = nullptr) inline explicit
CSettingDependencyConditionCombination() [2/2]
CSettingDependencyConditionCombination::CSettingDependencyConditionCombination (BooleanLogicOperation op, CSettingsManager * settingsManager = nullptr) inline
References CBooleanLogicOperation::SetOperation().
~CSettingDependencyConditionCombination()
CSettingDependencyConditionCombination::~CSettingDependencyConditionCombination () override default
Member Function Documentation
Add() [1/2]
CSettingDependencyConditionCombination * CSettingDependencyConditionCombination::Add (const CSettingDependencyConditionCombinationPtr & operation)
References GetSettings(), CBooleanLogicOperation::m_operations, and m_settings.
Add() [2/2]
CSettingDependencyConditionCombination * CSettingDependencyConditionCombination::Add (const CSettingDependencyConditionPtr & condition)
References m_settings, and CBooleanLogicOperation::m_values.
Deserialize()
bool CSettingDependencyConditionCombination::Deserialize (const TiXmlNode * node) override virtual
Reimplemented from CBooleanLogicOperation.
References CBooleanLogicOperation::Deserialize(), CSettingDependencyCondition::GetSetting(), GetSettings(), CBooleanLogicOperation::m_operations, m_settings, CBooleanLogicOperation::m_values, and node.
GetSettings()
const std::set< std::string > & CSettingDependencyConditionCombination::GetSettings () const inline
References m_settings.
Referenced by Add(), and Deserialize().
newOperation()
CBooleanLogicOperation * CSettingDependencyConditionCombination::newOperation () inline override private virtual
Reimplemented from CSettingConditionCombination.
References ISettingCondition::m_settingsManager.
newValue()
CBooleanLogicValue * CSettingDependencyConditionCombination::newValue () inline override private virtual
Reimplemented from CSettingConditionCombination.
References ISettingCondition::m_settingsManager.
Member Data Documentation
m_settings
std::set<std::string> CSettingDependencyConditionCombination::m_settings private
Referenced by Add(), Add(), Deserialize(), and GetSettings().
The documentation for this class was generated from the following files:
SettingDependency.h
SettingDependency.cpp