Kodi Documentation: KODI::KEYMAP::IKeymap Class Reference
KODI::KEYMAP::IKeymap Class Reference abstract
Interface for mapping buttons to Kodi actions.
#include <IKeymap.h>
Public Member Functions
virtual ~IKeymap ()=default
virtual std::string ControllerID () const =0
The controller ID.
virtual const IKeymapEnvironment * Environment () const =0
Access properties of the keymapping environment.
virtual const KeymapActionGroup & GetActions (const std::string &keyName) const =0
Get the actions for a given key name.
Detailed Description
Interface for mapping buttons to Kodi actions.
See also
CJoystickUtils::MakeKeyName
Constructor & Destructor Documentation
~IKeymap()
virtual KODI::KEYMAP::IKeymap::~IKeymap () virtual default
Member Function Documentation
ControllerID()
virtual std::string KODI::KEYMAP::IKeymap::ControllerID () const pure virtual
The controller ID.
This is required because key names are specific to each controller
Implemented in KODI::KEYMAP::CKeymap.
Referenced by KODI::JOYSTICK::CButtonMapping::CButtonMapping(), KODI::KEYMAP::CKeymapHandler::ControllerID(), and KODI::GAME::CGUIDialogButtonCapture::MapPrimitive().
Environment()
virtual const IKeymapEnvironment * KODI::KEYMAP::IKeymap::Environment () const pure virtual
Access properties of the keymapping environment.
Implemented in KODI::KEYMAP::CKeymap.
Referenced by KODI::KEYMAP::CKeymapHandler::CKeymapHandler().
GetActions()
virtual const KeymapActionGroup & KODI::KEYMAP::IKeymap::GetActions (const std::string & keyName) const pure virtual
Get the actions for a given key name.
Parameters
keyName The key name created by CJoystickUtils::MakeKeyName()
Returns
A list of actions associated with the given key
Implemented in KODI::KEYMAP::CKeymap.
Referenced by KODI::JOYSTICK::CButtonMapping::CButtonMapping(), KODI::KEYMAP::CKeymapHandler::HasAction(), KODI::GAME::CGUIDialogButtonCapture::MapPrimitive(), KODI::GAME::CGUIConfigurationWizard::MapPrimitive(), and KODI::KEYMAP::CKeyHandler::OnAnalogMotion().
The documentation for this class was generated from the following file:
IKeymap.h