Kodi Documentation: KODI::PLAYLIST Namespace Reference
KODI::PLAYLIST Namespace Reference
Classes
class CPlayList
class CPlayListASX
class CPlayListB4S
class CPlayListFactory
class CPlayListM3U
class CPlayListPlayer
class CPlayListPLS
class CPlayListRAM
class CPlayListURL
class CPlayListWPL
class CPlayListXML
class CPlayListXSPF
class CSmartPlaylist
class CSmartPlaylistFileItemListModifier
class CSmartPlaylistRule
class CSmartPlaylistRuleCombination
struct group
struct SSortPlayListItem
struct translateField
Typedefs
typedef std::shared_ptr< CPlayList > CPlayListPtr
Enumerations
enum class Id : int { TYPE_NONE = -1 , TYPE_MUSIC = 0 , TYPE_VIDEO = 1 , TYPE_PICTURE = 2 }
enum class RepeatState { NONE , ONE , ALL }
Manages playlist playing.
Functions
bool IsPlayList (const CFileItem &item)
Check whether an item is a playlist.
bool IsSmartPlayList (const CFileItem &item)
Check whether an item is a smart playlist.
static std::string GetString (const tinyxml2::XMLElement *pRootElement, const char *tagName)
Variables
static const translateField fields []
static const group groups []
Typedef Documentation
CPlayListPtr
typedef std::shared_ptr<CPlayList> KODI::PLAYLIST::CPlayListPtr
Enumeration Type Documentation
Id
enum class KODI::PLAYLIST::Id : int strong
Enumerator
TYPE_NONE
TYPE_MUSIC
TYPE_VIDEO
TYPE_PICTURE
RepeatState
enum class KODI::PLAYLIST::RepeatState strong
Manages playlist playing.
Enumerator
NONE
ONE
ALL
Function Documentation
GetString()
static std::string KODI::PLAYLIST::GetString (const tinyxml2::XMLElement * pRootElement, const char * tagName) inline static
References XMLUtils::GetString().
Referenced by KODI::PLAYLIST::CPlayListXML::Load().
IsPlayList()
bool KODI::PLAYLIST::IsPlayList (const CFileItem & item)
Check whether an item is a playlist.
References KODI::PLAYLIST::CPlayListFactory::IsPlaylist().
Referenced by UPNP::CUPnPServer::Build(), UPNP::BuildObject(), CDVDFileInfo::CanExtract(), MUSIC_INFO::CMusicInfoScanner::CountFiles(), MUSIC_INFO::CMusicInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::DoScan(), JSONRPC::CFileOperations::FillFileItemList(), KODI::ART::FillInDefaultIcon(), CFileItemList::FilterCueItems(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), CGUIWindowMusicNav::GetDirectory(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), MUSIC_INFO::CMusicInfoScanner::GetPathHash(), KODI::VIDEO::CVideoInfoScanner::GetPathHash(), CGUIViewState::GetViewState(), CFileItem::IsFileFolder(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), XBMCAddon::xbmc::PlayList::load(), CPictureFolderImageFileLoader::Load(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), MUSIC_INFO::CMusicInfoLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CGUIWindowMusicNav::OnClick(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIMediaWindow::OnDeleteItem(), CGUIWindowVideoBase::OnItemInfo(), CApplication::OnMessage(), CGUIMediaWindow::OnPlayMedia(), CGUIWindowMusicBase::OnPlayMedia(), CGUIWindowFileManager::OnStart(), CExecString::Parse(), CApplication::PlayFile(), CGUIWindowVideoBase::PlayItem(), CGUIWindowMusicBase::PlayItem(), CApplication::PlayMedia(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CPictureThumbLoader::ProcessFoldersAndArchives(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), CGUIWindowMusicBase::RetrieveMusicInfo(), CUtil::ScanForExternalAudio(), CUtil::ScanForExternalSubtitles(), MUSIC_INFO::CMusicInfoScanner::ScanTags(), CFileItemList::StackFiles(), TEST_P(), CGUIWindowMusicNav::UpdateButtons(), CGUIWindowVideoNav::UpdateButtons(), and CGUIMediaWindow::UpdateFileList().
IsSmartPlayList()
bool KODI::PLAYLIST::IsSmartPlayList (const CFileItem & item)
Check whether an item is a smart playlist.
References CVariant::asBoolean(), CFileItem::GetPath(), CGUIListItem::GetProperty(), and URIUtils::HasExtension().
Referenced by CGUIWindowVideoNav::ApplyWatchedFilter(), UPNP::CUPnPServer::Build(), UPNP::BuildObject(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), JSONRPC::CFileOperations::FillFileItemList(), KODI::ART::FillInDefaultIcon(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowVideoBase::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), XFILE::CDirectory::GetDirectory(), CGUIWindowMusicNav::GetDirectory(), CFileItemList::GetDiscFileCache(), CGUIViewState::GetViewState(), CFileItem::IsFileFolder(), MUSIC_UTILS::anonymous_namespace{MusicUtils.cpp}::IsNonExistingUserPartyModePlaylist(), KODI::VIDEO::UTILS::anonymous_namespace{VideoGUIUtils.cpp}::IsNonExistingUserPartyModePlaylist(), MUSIC_INFO::CMusicInfoLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowVideoBase::OnContextButton(), CGUIWindowMusicBase::OnPrepareFileItems(), CExecString::Parse(), CGUIWindowMusicBase::PlayItem(), CApplication::PlayMedia(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), MUSIC_UTILS::QueueItem(), and TEST().
Variable Documentation
fields
const translateField KODI::PLAYLIST::fields[] static
Referenced by KODI::PLAYLIST::CSmartPlaylist::GetAvailableFields(), KODI::PLAYLIST::CSmartPlaylistRule::GetFields(), KODI::PLAYLIST::CSmartPlaylistRule::GetFieldType(), KODI::PLAYLIST::CSmartPlaylistRule::GetLocalizedField(), KODI::PLAYLIST::CSmartPlaylistRule::IsFieldBrowseable(), CFileItem::ToSortable(), KODI::PLAYLIST::CSmartPlaylistRule::TranslateField(), KODI::PLAYLIST::CSmartPlaylistRule::TranslateField(), and KODI::PLAYLIST::CSmartPlaylistRule::Validate().
groups
const group KODI::PLAYLIST::groups[] static
Initial value:
= { { "",               FieldUnknown,   false,    571 },
                                { "none",           FieldNone,      false,    231 },
                                { "sets",           FieldSet,       true,   20434 },
                                { "genres",         FieldGenre,     false,    135 },
                                { "years",          FieldYear,      false,    652 },
                                { "actors",         FieldActor,     false,    344 },
                                { "directors",      FieldDirector,  false,  20348 },
                                { "writers",        FieldWriter,    false,  20418 },
                                { "studios",        FieldStudio,    false,  20388 },
                                { "countries",      FieldCountry,   false,  20451 },
                                { "artists",        FieldArtist,    false,    133 },
                                { "albums",         FieldAlbum,     false,    132 },
                                { "tags",           FieldTag,       false,  20459 },
                                { "originalyears",  FieldOrigYear,  false,  38078 },
                              }
Referenced by KODI::PLAYLIST::CSmartPlaylistRule::CanGroupMix(), KODI::PLAYLIST::CSmartPlaylistRule::GetGroups(), KODI::PLAYLIST::CSmartPlaylistRule::GetLocalizedGroup(), KODI::PLAYLIST::CSmartPlaylistRule::TranslateGroup(), and KODI::PLAYLIST::CSmartPlaylistRule::TranslateGroup().