Kodi Documentation: CGUIDialogMediaFilter Class Reference
CGUIDialogMediaFilter Class Reference
#include <GUIDialogMediaFilter.h>
Classes
struct Filter
Public Member Functions
CGUIDialogMediaFilter ()
~CGUIDialogMediaFilter () override
bool OnMessage (CGUIMessage &message) override
Public Member Functions inherited from CGUIDialogSettingsManualBase
CGUIDialogSettingsManualBase (int windowId, const std::string &xmlFile)
~CGUIDialogSettingsManualBase () override
Public Member Functions inherited from CGUIDialogSettingsManagerBase
CGUIDialogSettingsManagerBase (int windowId, const std::string &xmlFile)
~CGUIDialogSettingsManagerBase () override
Public Member Functions inherited from CGUIDialogSettingsBase
CGUIDialogSettingsBase (int windowId, const std::string &xmlFile)
~CGUIDialogSettingsBase () override
bool OnMessage (CGUIMessage &message) override
bool OnAction (const CAction &action) override
bool OnBack (int actionID) override
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
virtual bool IsConfirmed () const
std::string Localize (std::uint32_t code) const override
Public Member Functions inherited from CGUIDialog
CGUIDialog (int id, const std::string &xmlFile, DialogModalityType modalityType=DialogModalityType::MODAL)
~CGUIDialog (void) override
void Render () override
void Open (const std::string &param="")
void Open (bool bProcessRenderLoop, const std::string &param="")
bool IsDialogRunning () const override
bool IsDialog () const override
bool IsModalDialog () const override
virtual DialogModalityType GetModalityType () const
void SetAutoClose (unsigned int timeoutMs)
void ResetAutoClose (void)
void CancelAutoClose (void)
bool IsAutoClosed (void) const
void SetSound (bool OnOff)
bool IsSoundEnabled () const override
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
bool OnAction (const CAction &action) override
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool OnMessage (CGUIMessage &message) override
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsMediaWindow () const
virtual bool HasListItems () const
virtual CFileItemPtr GetCurrentListItem (int offset=0)
virtual int GetViewContainerID () const
virtual int GetViewCount () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual CGUIControl * GetFirstFocusableControl (int id)
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Public Member Functions inherited from CSettingControlCreator
std::shared_ptr< ISettingControl > CreateControl (const std::string &controlType) const override
Creates a new setting control of the given custom setting control type.
Public Member Functions inherited from ISettingControlCreator
virtual ~ISettingControlCreator ()=default
Public Member Functions inherited from ILocalizer
virtual ~ILocalizer ()=default
Static Public Member Functions
static void ShowAndEditMediaFilter (const std::string &path, KODI::PLAYLIST::CSmartPlaylist &filter)
Protected Member Functions
void OnWindowLoaded () override
void OnInitWindow () override
Called on window open.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
bool AllowResettingSettings () const override
bool Save () override
std::chrono::milliseconds GetDelayMs () const override
void SetupView () override
void InitializeSettings () override
bool SetPath (const std::string &path)
void UpdateControls ()
void TriggerFilter () const
void Reset (bool filtersOnly=false)
int GetItems (const Filter &filter, std::vector< std::string > &items, bool countOnly=false)
void GetRange (const Filter &filter, int &min, int &interval, int &max)
void GetRange (const Filter &filter, float &min, float &interval, float &max)
bool GetMinMax (const std::string &table, const std::string &field, int &min, int &max, const CDatabase::Filter &filter=CDatabase::Filter())
KODI::PLAYLIST::CSmartPlaylistRule * AddRule (Field field, CDatabaseQueryRule::SEARCH_OPERATOR ruleOperator=CDatabaseQueryRule::OPERATOR_CONTAINS)
void DeleteRule (Field field)
Protected Member Functions inherited from CGUIDialogSettingsManualBase
std::shared_ptr< CSettingSection > GetSection () override
void SetupView () override
CSettingsManager * GetSettingsManager () const override
std::shared_ptr< CSettingCategory > AddCategory (const std::string &id, int label, int help=-1)
std::shared_ptr< CSettingGroup > AddGroup (const std::shared_ptr< CSettingCategory > &category, int label=-1, int help=-1, bool separatorBelowLabel=true, bool hideSeparator=false)
std::shared_ptr< CSettingBool > AddToggle (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, bool value, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddEdit (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, int minimum=0, int step=1, int maximum=0, bool verifyNewValue=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingNumber > AddEdit (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float value, float minimum=0.0f, float step=1.0f, float maximum=0.0f, bool verifyNewValue=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddEdit (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool allowEmpty=false, bool hidden=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddIp (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool allowEmpty=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddPasswordMd5 (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool allowEmpty=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingAction > AddButton (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &data="", bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddInfoLabelButton (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &info, bool visible=true, int help=-1)
std::shared_ptr< CSettingAddon > AddAddon (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, ADDON::AddonType addonType, bool allowEmpty=false, int heading=-1, bool hideValue=false, bool showInstalledAddons=true, bool showInstallableAddons=false, bool showMoreAddons=true, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingPath > AddPath (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool writable=true, const std::vector< std::string > &sources=std::vector< std::string >(), bool allowEmpty=false, int heading=-1, bool hideValue=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingDate > AddDate (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool allowEmpty=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingTime > AddTime (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, bool allowEmpty=false, int heading=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, StringSettingOptionsFiller filler, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, int minimum, int step, int maximum, int formatLabel=-1, int minimumLabel=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, int minimum, int step, int maximum, const std::string &formatString, int minimumLabel=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const TranslatableIntegerSettingOptions &entries, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const IntegerSettingOptions &entries, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, IntegerSettingOptionsFiller filler, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingNumber > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float value, float minimum, float step, float maximum, int formatLabel=-1, int minimumLabel=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingNumber > AddSpinner (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float value, float minimum, float step, float maximum, const std::string &formatString, int minimumLabel=-1, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingString > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, const std::string &value, StringSettingOptionsFiller filler, int heading, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingInt > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const TranslatableIntegerSettingOptions &entries, int heading, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingInt > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const IntegerSettingOptions &entries, int heading, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingInt > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, IntegerSettingOptionsFiller filler, int heading, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingList > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, std::vector< std::string > values, StringSettingOptionsFiller filler, int heading, int minimumItems=0, int maximumItems=-1, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingList > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, std::vector< int > values, const TranslatableIntegerSettingOptions &entries, int heading, int minimumItems=0, int maximumItems=-1, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingList > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, std::vector< int > values, const IntegerSettingOptions &entries, int heading, int minimumItems=0, int maximumItems=-1, bool visible=true, int help=-1, bool details=false)
std::shared_ptr< CSettingList > AddList (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, std::vector< int > values, IntegerSettingOptionsFiller filler, int heading, int minimumItems=0, int maximumItems=-1, bool visible=true, int help=-1, SettingControlListValueFormatter formatter=nullptr, bool details=false)
std::shared_ptr< CSettingInt > AddPercentageSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, int formatLabel, int step=1, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddPercentageSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const std::string &formatString, int step=1, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, int formatLabel, int minimum, int step, int maximum, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingInt > AddSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int value, const std::string &formatString, int minimum, int step, int maximum, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingNumber > AddSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float value, int formatLabel, float minimum, float step, float maximum, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingNumber > AddSlider (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float value, const std::string &formatString, float minimum, float step, float maximum, int heading=-1, bool usePopup=false, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddPercentageRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int valueFormatLabel, int step=1, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddPercentageRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, const std::string &valueFormatString="{:d} %", int step=1, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, int valueFormatLabel, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, const std::string &valueFormatString="{:d}", int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float valueLower, float valueUpper, float minimum, float step, float maximum, int valueFormatLabel, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, float valueLower, float valueUpper, float minimum, float step, float maximum, const std::string &valueFormatString="{:.1f}", int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddDateRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, int valueFormatLabel, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddDateRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, const std::string &valueFormatString="", int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddTimeRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, int valueFormatLabel, int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< CSettingList > AddTimeRange (const std::shared_ptr< CSettingGroup > &group, const std::string &id, int label, SettingLevel level, int valueLower, int valueUpper, int minimum, int step, int maximum, const std::string &valueFormatString="mm:ss", int formatLabel=21469, bool delayed=false, bool visible=true, int help=-1)
std::shared_ptr< ISettingControl > GetTitleControl (bool separatorBelowLabel=true, bool hideSeparator=false)
std::shared_ptr< ISettingControl > GetCheckmarkControl (bool delayed=false)
std::shared_ptr< ISettingControl > GetEditControl (const std::string &format, bool delayed=false, bool hidden=false, bool verifyNewValue=false, int heading=-1)
std::shared_ptr< ISettingControl > GetButtonControl (const std::string &format, bool delayed=false, int heading=-1, bool hideValue=false, bool showInstalledAddons=true, bool showInstallableAddons=false, bool showMoreAddons=true)
std::shared_ptr< ISettingControl > GetSpinnerControl (const std::string &format, bool delayed=false, int minimumLabel=-1, int formatLabel=-1, const std::string &formatString="")
std::shared_ptr< ISettingControl > GetListControl (const std::string &format, bool delayed=false, int heading=-1, bool multiselect=false, SettingControlListValueFormatter formatter=nullptr, bool details=false)
std::shared_ptr< ISettingControl > GetSliderControl (const std::string &format, bool delayed=false, int heading=-1, bool usePopup=false, int formatLabel=-1, const std::string &formatString="")
std::shared_ptr< ISettingControl > GetRangeControl (const std::string &format, bool delayed=false, int formatLabel=-1, int valueFormatLabel=-1, const std::string &valueFormatString="")
Protected Member Functions inherited from CGUIDialogSettingsManagerBase
std::shared_ptr< CSetting > GetSetting (const std::string &settingId) override
bool OnOkay () override
std::set< std::string > CreateSettings () override
void FreeSettingsControls () override
std::shared_ptr< ISettingControl > CreateControl (const std::string &controlType) const override
Creates a new setting control of the given custom setting control type.
Protected Member Functions inherited from CGUIDialogSettingsBase
void OnInitWindow () override
Called on window open.
void OnTimeout () override
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName) override
The given property of the given setting has changed.
virtual int GetSettingLevel () const
virtual std::string GetLocalizedString (uint32_t labelId) const
virtual void OnCancel ()
virtual void UpdateSettings ()
virtual std::string GetSettingsLabel (const std::shared_ptr< ISetting > &pSetting)
Get the name for the setting entry.
virtual CGUIControl * AddSetting (const std::shared_ptr< CSetting > &pSetting, float width, int &iControlID)
virtual CGUIControl * AddSettingControl (CGUIControl *pControl, BaseSettingControlPtr pSettingControl, float width, int &iControlID)
virtual void SetupControls (bool createSettings=true)
virtual void FreeControls ()
virtual void DeleteControls ()
virtual void SetHeading (const CVariant &label)
virtual void SetDescription (const CVariant &label)
virtual void OnResetSettings ()
virtual void OnClick (const BaseSettingControlPtr &pSettingControl)
A setting control has been interacted with by the user.
void UpdateSettingControl (const std::string &settingId, bool updateDisplayOnly=false)
void UpdateSettingControl (const BaseSettingControlPtr &pSettingControl, bool updateDisplayOnly=false)
void SetControlLabel (int controlId, const CVariant &label)
BaseSettingControlPtr GetSettingControl (const std::string &setting)
BaseSettingControlPtr GetSettingControl (int controlId)
CGUIControl * AddSeparator (float width, int &iControlID)
CGUIControl * AddGroupLabel (const std::shared_ptr< CSettingGroup > &group, float width, int &iControlID)
Protected Member Functions inherited from CGUIDialog
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
void SetDefaults () override
virtual void UpdateVisibility ()
virtual void Open_Internal (bool bProcessRenderLoop, const std::string &param="")
void OnDeinitWindow (int nextWindowID) override
void ProcessRenderLoop (bool renderOnly=false)
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void OnWindowUnload ()
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
virtual void SaveControlStates ()
virtual void RestoreControlStates ()
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Member Functions inherited from CSettingControlCreator
CSettingControlCreator ()=default
~CSettingControlCreator () override=default
Protected Member Functions inherited from ILocalizer
ILocalizer ()=default
Protected Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Protected Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
Static Protected Member Functions
static void GetStringListOptions (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
Protected Attributes
CDbUrl * m_dbUrl
std::string m_mediaType
KODI::PLAYLIST::CSmartPlaylist * m_filter
std::map< std::string, Filter > m_filters
Protected Attributes inherited from CGUIDialogSettingsBase
std::vector< std::shared_ptr< CSettingCategory > > m_categories
std::vector< BaseSettingControlPtr > m_settingControls
int m_iSetting = 0
int m_iCategory = 0
std::shared_ptr< CSettingAction > m_resetSetting
std::shared_ptr< CSettingCategory > m_dummyCategory
CGUISpinControlEx * m_pOriginalSpin
CGUISettingsSliderControl * m_pOriginalSlider
CGUIRadioButtonControl * m_pOriginalRadioButton
CGUIColorButtonControl * m_pOriginalColorButton = nullptr
CGUIButtonControl * m_pOriginalCategoryButton
CGUIButtonControl * m_pOriginalButton
CGUIEditControl * m_pOriginalEdit
CGUIImage * m_pOriginalImage
CGUILabelControl * m_pOriginalGroupTitle
bool m_newOriginalEdit = false
BaseSettingControlPtr m_delayedSetting
Current delayed setting.
CTimer m_delayedTimer
Delayed setting timer.
bool m_confirmed = false
int m_focusedControl = 0
int m_fadedControl = 0
Protected Attributes inherited from CGUIDialog
bool m_wasRunning
true if we were running during the last DoProcess()
bool m_autoClosing
bool m_enableSound
unsigned int m_showStartTime
unsigned int m_showDuration
bool m_bAutoClosed
DialogModalityType m_modalityType
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIDialogMediaFilter()
CGUIDialogMediaFilter::CGUIDialogMediaFilter ()
~CGUIDialogMediaFilter()
CGUIDialogMediaFilter::~CGUIDialogMediaFilter () override
References Reset().
Member Function Documentation
AddRule()
PLAYLIST::CSmartPlaylistRule * CGUIDialogMediaFilter::AddRule (Field field, CDatabaseQueryRule::SEARCH_OPERATOR ruleOperator = CDatabaseQueryRule::OPERATOR_CONTAINS) protected
References KODI::PLAYLIST::CSmartPlaylistRuleCombination::AddRule(), CDatabaseQueryRule::m_field, m_filter, CDatabaseQueryRule::m_operator, KODI::PLAYLIST::CSmartPlaylist::m_ruleCombination, and CDatabaseQueryRuleCombination::m_rules.
Referenced by OnSettingChanged().
AllowResettingSettings()
bool CGUIDialogMediaFilter::AllowResettingSettings () const inline override protected virtual
Reimplemented from CGUIDialogSettingsBase.
DeleteRule()
void CGUIDialogMediaFilter::DeleteRule (Field field) protected
References m_filter, KODI::PLAYLIST::CSmartPlaylist::m_ruleCombination, and CDatabaseQueryRuleCombination::m_rules.
Referenced by InitializeSettings(), and OnSettingChanged().
GetDelayMs()
std::chrono::milliseconds CGUIDialogMediaFilter::GetDelayMs () const inline override protected virtual
Reimplemented from CGUIDialogSettingsBase.
GetItems()
int CGUIDialogMediaFilter::GetItems (const Filter & filter, std::vector< std::string > & items, bool countOnly = false) protected
References EPISODES, CGUIDialogMediaFilter::Filter::field, FieldActor, FieldAlbum, FieldAlbumArtist, FieldAlbumType, FieldArtist, FieldDirector, FieldGenre, FieldMusicLabel, FieldSource, FieldStudio, FieldTag, CFileItemList::Get(), CVideoDatabase::GetActorsNav(), CMusicDatabase::GetAlbumsNav(), CMusicDatabase::GetAlbumTypesNav(), CMusicDatabase::GetArtistsNav(), CVideoDatabase::GetDirectorsNav(), CMusicDatabase::GetGenresNav(), CVideoDatabase::GetGenresNav(), CMusicDatabase::GetMusicLabelsNav(), CVideoDatabase::GetMusicVideoAlbumsNav(), CMusicDatabase::GetSourcesNav(), CVideoDatabase::GetStudiosNav(), CVideoDatabase::GetTagsNav(), KODI::PLAYLIST::CSmartPlaylist::GetWhereClause(), index(), m_dbUrl, m_filter, m_mediaType, KODI::PLAYLIST::CSmartPlaylist::m_ruleCombination, CDatabaseQueryRuleCombination::m_rules, MOVIES, MUSICVIDEOS, CMusicDatabase::Open(), CVideoDatabase::Open(), CFileItemList::Size(), CFileItemList::Sort(), SortByLabel, SortOrderAscending, CDbUrl::ToString(), TVSHOWS, and CDatabase::Filter::where.
Referenced by GetStringListOptions(), and UpdateControls().
GetMinMax()
bool CGUIDialogMediaFilter::GetMinMax (const std::string & table, const std::string & field, int & min, int & max, const CDatabase::Filter & filter = CDatabase::Filter()) protected
References CDatabase::BuildSQL(), CDatabase::Close(), CDatabase::GetSingleValue(), CDatabase::IsOpen(), m_dbUrl, m_mediaType, max, min, CMusicDatabase::Open(), CVideoDatabase::Open(), CDatabase::PrepareSQL(), table, and CDbUrl::ToString().
Referenced by GetRange().
GetRange() [1/2]
void CGUIDialogMediaFilter::GetRange (const Filter & filter, float & min, float & interval, float & max) protected
References CGUIDialogMediaFilter::Filter::field, FieldRating, m_mediaType, max, and min.
GetRange() [2/2]
void CGUIDialogMediaFilter::GetRange (const Filter & filter, int & min, int & interval, int & max) protected
References DatabaseQueryPartSelect, DatabaseQueryPartWhere, CGUIDialogMediaFilter::Filter::field, FieldAirDate, FieldPlaycount, FieldTime, FieldUserRating, FieldYear, CMediaTypes::FromString(), DatabaseUtils::GetField(), GetMinMax(), m_mediaType, max, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, min, table, VIDEODB_ID_EPISODE_AIRED, and CDatabase::Filter::where.
Referenced by InitializeSettings().
GetStringListOptions()
void CGUIDialogMediaFilter::GetStringListOptions (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static protected
References data(), GetItems(), and m_filters.
Referenced by InitializeSettings().
InitializeSettings()
void CGUIDialogMediaFilter::InitializeSettings () override protected virtual
Reimplemented from CGUIDialogSettingsManualBase.
References CGUIDialogSettingsManualBase::AddCategory(), CGUIDialogSettingsManualBase::AddDateRange(), CGUIDialogSettingsManualBase::AddEdit(), CGUIDialogSettingsManualBase::AddGroup(), CGUIDialogSettingsManualBase::AddList(), CGUIDialogSettingsManualBase::AddPercentageRange(), CGUIDialogSettingsManualBase::AddRange(), CGUIDialogSettingsManualBase::AddSpinner(), CGUIDialogSettingsManualBase::AddTimeRange(), CVariant::asFloat(), CVariant::asInteger(), Basic, CHECK_ALL, CHECK_LABEL_ALL, CHECK_LABEL_NO, CHECK_LABEL_YES, CHECK_NO, CHECK_YES, CGUIDialogMediaFilter::Filter::controlFormat, CGUIDialogMediaFilter::Filter::controlType, data(), DATABASEQUERY_RULE_VALUE_SEPARATOR, DeleteRule(), f, CGUIDialogMediaFilter::Filter::field, filterList, CDatabaseQueryRule::GetParameter(), GetRange(), GetStringListOptions(), CGUIDialogSettingsManualBase::InitializeSettings(), Integer, CVariant::isNull(), CGUIDialogMediaFilter::Filter::label, CLog::Log(), LOGERROR, LOGWARNING, m_filter, m_filters, m_mediaType, CDatabaseQueryRule::m_operator, CDatabaseQueryRule::m_parameter, KODI::PLAYLIST::CSmartPlaylist::m_ruleCombination, CDatabaseQueryRuleCombination::m_rules, max, CGUIDialogMediaFilter::Filter::mediaType, min, Number, CDatabaseQueryRule::OPERATOR_TRUE, Reset(), CGUIDialogMediaFilter::Filter::rule, CGUIDialogMediaFilter::Filter::setting, CGUIDialogMediaFilter::Filter::settingType, String, value, and values.
OnInitWindow()
void CGUIDialogMediaFilter::OnInitWindow (void) override protected virtual
Called on window open.
Restores the control state(s)
Sets initial visibility of controls
Queue WindowOpen animation
Set overlay state Override this function and do any window-specific initialisation such as filling control contents and setting control focus before calling the base method.
Reimplemented from CGUIWindow.
References CGUIWindow::OnInitWindow(), and UpdateControls().
OnMessage()
bool CGUIDialogMediaFilter::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIDialog.
References CONTROL_CLEAR_BUTTON, CGUIMessage::GetMessage(), CGUIMessage::GetSenderId(), GUI_MSG_CLICKED, GUI_MSG_REFRESH_LIST, GUI_MSG_WINDOW_DEINIT, m_filter, m_filters, m_mediaType, CGUIControl::OnMessage(), KODI::PLAYLIST::CSmartPlaylist::Reset(), Reset(), KODI::PLAYLIST::CSmartPlaylist::SetType(), TriggerFilter(), and UpdateControls().
OnSettingChanged()
void CGUIDialogMediaFilter::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override protected virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References AddRule(), CHECK_ALL, CHECK_YES, CGUIDialogMediaFilter::Filter::controlFormat, CGUIDialogMediaFilter::Filter::controlType, DeleteRule(), CGUIDialogMediaFilter::Filter::field, CDateTime::GetAsDBDate(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CSettingUtils::GetList(), CGUIComponent::GetWindowManager(), GUI_MSG_REFRESH_LIST, Integer, m_filters, CDatabaseQueryRule::m_operator, CDatabaseQueryRule::m_parameter, Number, CGUIDialogSettingsBase::OnSettingChanged(), CDatabaseQueryRule::OPERATOR_FALSE, CDatabaseQueryRule::OPERATOR_TRUE, CGUIDialogMediaFilter::Filter::rule, CGUIDialogMediaFilter::Filter::ruleOperator, value, values, and WINDOW_DIALOG_MEDIA_FILTER.
OnWindowLoaded()
void CGUIDialogMediaFilter::OnWindowLoaded () override protected virtual
Reimplemented from CGUIDialog.
References CONTROL_CANCEL_BUTTON, CGUIDialog::OnWindowLoaded(), and SET_CONTROL_HIDDEN.
Reset()
void CGUIDialogMediaFilter::Reset (bool filtersOnly = false) protected
References m_dbUrl, and m_filters.
Save()
bool CGUIDialogMediaFilter::Save () inline override protected virtual
Implements CGUIDialogSettingsManagerBase.
SetPath()
bool CGUIDialogMediaFilter::SetPath (const std::string & path) protected
References CDbUrl::FromString(), CDbUrl::GetType(), CDbUrl::HasOption(), CLog::Log(), LOGWARNING, m_dbUrl, m_filter, m_mediaType, CDbUrl::RemoveOption(), and KODI::PLAYLIST::CSmartPlaylist::SetType().
Referenced by ShowAndEditMediaFilter().
SetupView()
void CGUIDialogMediaFilter::SetupView () override protected virtual
Reimplemented from CGUIDialogSettingsBase.
References CONTROL_CLEAR_BUTTON, CONTROL_HEADING, CONTROL_OKAY_BUTTON, g_localizeStrings, CLocalizeStrings::Get(), m_mediaType, SET_CONTROL_LABEL, and CGUIDialogSettingsManualBase::SetupView().
ShowAndEditMediaFilter()
void CGUIDialogMediaFilter::ShowAndEditMediaFilter (const std::string & path, KODI::PLAYLIST::CSmartPlaylist & filter) static
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIWindow::Initialize(), m_filter, CGUIDialog::Open(), SetPath(), and WINDOW_DIALOG_MEDIA_FILTER.
Referenced by CGUIMediaWindow::Filter().
TriggerFilter()
void CGUIDialogMediaFilter::TriggerFilter () const protected
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), GUI_MSG_FILTER_ITEMS, GUI_MSG_NOTIFY_ALL, and m_filter.
Referenced by OnMessage().
UpdateControls()
void CGUIDialogMediaFilter::UpdateControls () protected
References CONTROL_DISABLE, CONTROL_ENABLE, FieldSet, FieldTag, g_localizeStrings, CLocalizeStrings::Get(), GetItems(), CGUIDialogSettingsBase::GetSettingControl(), label, m_filters, and SET_CONTROL_LABEL.
Referenced by OnInitWindow(), and OnMessage().
Member Data Documentation
m_dbUrl
CDbUrl* CGUIDialogMediaFilter::m_dbUrl protected
Referenced by GetItems(), GetMinMax(), Reset(), and SetPath().
m_filter
KODI::PLAYLIST::CSmartPlaylist* CGUIDialogMediaFilter::m_filter protected
Referenced by AddRule(), DeleteRule(), GetItems(), InitializeSettings(), OnMessage(), SetPath(), ShowAndEditMediaFilter(), and TriggerFilter().
m_filters
std::map<std::string, Filter> CGUIDialogMediaFilter::m_filters protected
Referenced by GetStringListOptions(), InitializeSettings(), OnMessage(), OnSettingChanged(), Reset(), and UpdateControls().
m_mediaType
std::string CGUIDialogMediaFilter::m_mediaType protected
Referenced by GetItems(), GetMinMax(), GetRange(), GetRange(), InitializeSettings(), OnMessage(), SetPath(), and SetupView().
The documentation for this class was generated from the following files:
GUIDialogMediaFilter.h
GUIDialogMediaFilter.cpp