Kodi Documentation: KODI::PLAYLIST::CPlayListFactory Class Reference
KODI::PLAYLIST::CPlayListFactory Class Reference
#include <PlayListFactory.h>
Static Public Member Functions
static CPlayList * Create (const CURL &url)
static CPlayList * Create (const std::string &filename)
static CPlayList * Create (const CFileItem &item)
static bool IsPlaylist (const CURL &url)
static bool IsPlaylist (const std::string &filename)
static bool IsPlaylist (const CFileItem &item)
Member Function Documentation
Create() [1/3]
CPlayList * KODI::PLAYLIST::CPlayListFactory::Create (const CFileItem & item) static
References CFileItem::GetDynPath(), URIUtils::GetExtension(), CFileItem::GetMimeType(), KODI::NETWORK::IsInternetStream(), and CFileItem::IsType().
Create() [2/3]
CPlayList * KODI::PLAYLIST::CPlayListFactory::Create (const CURL & url) static
References Create(), CURL::Get(), CURL::GetOption(), and CURL::HasOption().
Referenced by XFILE::CPlaylistFileDirectory::ContainsFiles(), Create(), Create(), KODI::PLAYLIST::CPlayList::Expand(), XFILE::CPlaylistFileDirectory::GetDirectory(), anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CGUIWindowMusicNav::GetSongsFromPlayList(), XBMCAddon::xbmc::PlayList::load(), KODI::PLAYLIST::CPlayListASX::LoadData(), CGUIWindowMusicBase::LoadPlayList(), CGUIWindowPictures::LoadPlayList(), CGUIWindowVideoBase::LoadPlayList(), CGUIWindowFileManager::OnStart(), anonymous_namespace{Application.cpp}::CCreateAndLoadPlayList::Run(), and TEST().
Create() [3/3]
CPlayList * KODI::PLAYLIST::CPlayListFactory::Create (const std::string & filename) static
References Create().
IsPlaylist() [1/3]
bool KODI::PLAYLIST::CPlayListFactory::IsPlaylist (const CFileItem & item) static
References CFileItem::GetDynPath(), CFileItem::GetMimeType(), KODI::NETWORK::IsInternetStream(), IsPlaylist(), and CFileItem::IsType().
IsPlaylist() [2/3]
bool KODI::PLAYLIST::CPlayListFactory::IsPlaylist (const CURL & url) static
References URIUtils::HasExtension().
Referenced by XFILE::CFileDirectoryFactory::Create(), IsPlaylist(), KODI::PLAYLIST::IsPlayList(), and TEST().
IsPlaylist() [3/3]
bool KODI::PLAYLIST::CPlayListFactory::IsPlaylist (const std::string & filename) static
References URIUtils::HasExtension().
The documentation for this class was generated from the following files:
PlayListFactory.h
PlayListFactory.cpp