Kodi Documentation: InfoTagPicture
InfoTagPicture
Python » Library - xbmc
Kodi's picture info tag class.
Classes
class XBMCAddon::xbmc::InfoTagPicture
Functions
XBMCAddon::xbmc::InfoTagPicture::InfoTagPicture (const CPictureInfoTag *tag)
XBMCAddon::xbmc::InfoTagPicture::InfoTagPicture (CPictureInfoTag *tag, bool offscreen=false)
XBMCAddon::xbmc::InfoTagPicture::InfoTagPicture (...)
Function: xbmc.InfoTagPicture([offscreen])
Create a picture info tag.
XBMCAddon::xbmc::InfoTagPicture::~InfoTagPicture () override
XBMCAddon::xbmc::InfoTagPicture::getResolution ()
Function: getResolution()
Get the resolution of the picture in the format "w x h".
XBMCAddon::xbmc::InfoTagPicture::getDirector ()
Function: getDateTimeTaken()
Get the date and time at which the picture was taken in W3C format.
XBMCAddon::xbmc::InfoTagPicture::setResolution (...)
Function: setResolution(width, height)
Sets the resolution of the picture.
XBMCAddon::xbmc::InfoTagPicture::setDateTimeTaken (...)
Function: setDateTimeTaken(datetimetaken)
Sets the date and time at which the picture was taken in W3C format. The following formats are supported:
static void XBMCAddon::xbmc::InfoTagPicture::setResolutionRaw (CPictureInfoTag *infoTag, const String &resolution)
static void XBMCAddon::xbmc::InfoTagPicture::setResolutionRaw (CPictureInfoTag *infoTag, int width, int height)
static void XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw (CPictureInfoTag *infoTag, String datetimetaken)
Variables
CPictureInfoTag * XBMCAddon::xbmc::InfoTagPicture::infoTag
bool XBMCAddon::xbmc::InfoTagPicture::offscreen
bool XBMCAddon::xbmc::InfoTagPicture::owned
Detailed Description
Kodi's picture info tag class.
Class: InfoTagPicture()
Access and / or modify the picture metadata of a ListItem.
v20 Python API changes:
New class added.
Example:
...
tag = item.getPictureInfoTag()
datetime_taken  = tag.getDateTimeTaken()
tag.setResolution(1920, 1080)
...
Function Documentation
getDirector()
XBMCAddon::xbmc::InfoTagPicture::getDirector ()
Function: getDateTimeTaken()
Get the date and time at which the picture was taken in W3C format.
Returns
[string] Date and time at which the picture was taken in W3C format.
v20 Python API changes:
New function added.
getResolution()
String XBMCAddon::xbmc::InfoTagPicture::getResolution ()
Function: getResolution()
Get the resolution of the picture in the format "w x h".
Returns
[string] Resolution of the picture in the format "w x h".
v20 Python API changes:
New function added.
References CPictureInfoTag::GetInfo(), XBMCAddon::xbmc::InfoTagPicture::infoTag, and SLIDESHOW_RESOLUTION.
InfoTagPicture() [1/3]
XBMCAddon::xbmc::InfoTagPicture::InfoTagPicture (...)
Function: xbmc.InfoTagPicture([offscreen])
Create a picture info tag.
Parameters
offscreen [opt] bool (default False) - if GUI based locks should be avoided. Most of the times listitems are created offscreen and added later to a container for display (e.g. plugins) or they are not even displayed (e.g. python scrapers). In such cases, there is no need to lock the GUI when creating the items (increasing your addon performance). Note however, that if you are creating listitems and managing the container itself (e.g using WindowXML or WindowXMLDialog classes) subsquent modifications to the item will require locking. Thus, in such cases, use the default value (False).
v20 Python API changes:
New function added.
Example:
...
pictureinfo = xbmc.InfoTagPicture(offscreen=False)
...
InfoTagPicture() [2/3]
XBMCAddon::xbmc::InfoTagPicture::InfoTagPicture (const CPictureInfoTag * tag) explicit
InfoTagPicture() [3/3]
XBMCAddon::xbmc::InfoTagPicture::InfoTagPicture (CPictureInfoTag * tag, bool offscreen = false) explicit
setDateTimeTaken()
void XBMCAddon::xbmc::InfoTagPicture::setDateTimeTaken (...)
Function: setDateTimeTaken(datetimetaken)
Sets the date and time at which the picture was taken in W3C format. The following formats are supported:
YYYY
YYYY-MM-DD
YYYY-MM-DDThh:mm[TZD]
YYYY-MM-DDThh:mm:ss[TZD] where the timezone (TZD) is always optional and can be in one of the following formats:
Z (for UTC)
+hh:mm
-hh:mm
Parameters
datetimetaken string - Date and time at which the picture was taken in W3C format.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagPicture::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagPicture::offscreen, and XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw().
setDateTimeTakenRaw()
void XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw (CPictureInfoTag * infoTag, String datetimetaken) static
References CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetSecond(), CDateTime::GetYear(), XBMCAddon::xbmc::InfoTagPicture::infoTag, CDateTime::SetFromW3CDateTime(), and CPictureInfoTag::SetInfo().
Referenced by XBMCAddon::xbmc::InfoTagPicture::setDateTimeTaken(), and XBMCAddon::xbmcgui::ListItem::setInfo().
setResolution()
void XBMCAddon::xbmc::InfoTagPicture::setResolution (...)
Function: setResolution(width, height)
Sets the resolution of the picture.
Parameters
width int - Width of the picture in pixels.
height int - Height of the picture in pixels.
v20 Python API changes:
New function added.
References XBMCAddon::xbmc::InfoTagPicture::infoTag, XBMCAddon::AddonClass::languageHook, XBMCAddon::xbmc::InfoTagPicture::offscreen, and XBMCAddon::xbmc::InfoTagPicture::setResolutionRaw().
setResolutionRaw() [1/2]
void XBMCAddon::xbmc::InfoTagPicture::setResolutionRaw (CPictureInfoTag * infoTag, const String & resolution) static
References XBMCAddon::xbmc::InfoTagPicture::infoTag, and CPictureInfoTag::SetInfo().
Referenced by XBMCAddon::xbmcgui::ListItem::setInfo(), XBMCAddon::xbmc::InfoTagPicture::setResolution(), and XBMCAddon::xbmc::InfoTagPicture::setResolutionRaw().
setResolutionRaw() [2/2]
void XBMCAddon::xbmc::InfoTagPicture::setResolutionRaw (CPictureInfoTag * infoTag, int width, int height) static
References XBMCAddon::xbmc::InfoTagPicture::infoTag, and XBMCAddon::xbmc::InfoTagPicture::setResolutionRaw().
~InfoTagPicture()
XBMCAddon::xbmc::InfoTagPicture::~InfoTagPicture () override
References XBMCAddon::xbmc::InfoTagPicture::infoTag, and XBMCAddon::xbmc::InfoTagPicture::owned.
Variable Documentation
infoTag
CPictureInfoTag* XBMCAddon::xbmc::InfoTagPicture::infoTag private
Referenced by XBMCAddon::xbmc::InfoTagPicture::getResolution(), XBMCAddon::xbmc::InfoTagPicture::setDateTimeTaken(), XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw(), XBMCAddon::xbmc::InfoTagPicture::setResolution(), XBMCAddon::xbmc::InfoTagPicture::setResolutionRaw(), XBMCAddon::xbmc::InfoTagPicture::setResolutionRaw(), and XBMCAddon::xbmc::InfoTagPicture::~InfoTagPicture().
offscreen
bool XBMCAddon::xbmc::InfoTagPicture::offscreen private
Referenced by XBMCAddon::xbmc::InfoTagPicture::setDateTimeTaken(), and XBMCAddon::xbmc::InfoTagPicture::setResolution().
owned
bool XBMCAddon::xbmc::InfoTagPicture::owned private
Referenced by XBMCAddon::xbmc::InfoTagPicture::~InfoTagPicture().