Kodi Documentation: AddonToKodiFuncTable_kodi_network Struct Reference
AddonToKodiFuncTable_kodi_network Struct Reference
#include <network.h>
Public Attributes
bool(* wake_on_lan)(void *kodiBase, const char *mac)
char *(* get_ip_address)(void *kodiBase)
char *(* dns_lookup)(void *kodiBase, const char *url, bool *ret)
char *(* url_encode)(void *kodiBase, const char *url)
char *(* get_hostname)(void *kodiBase)
bool(* is_local_host)(void *kodiBase, const char *hostname)
bool(* is_host_on_lan)(void *kodiBase, const char *hostname, bool offLineCheck)
char *(* get_user_agent)(void *kodiBase)
Member Data Documentation
dns_lookup
char *(* AddonToKodiFuncTable_kodi_network::dns_lookup) (void *kodiBase, const char *url, bool *ret)
Referenced by ADDON::Interface_Network::Init().
get_hostname
char *(* AddonToKodiFuncTable_kodi_network::get_hostname) (void *kodiBase)
Referenced by ADDON::Interface_Network::Init().
get_ip_address
char *(* AddonToKodiFuncTable_kodi_network::get_ip_address) (void *kodiBase)
Referenced by ADDON::Interface_Network::Init().
get_user_agent
char *(* AddonToKodiFuncTable_kodi_network::get_user_agent) (void *kodiBase)
Referenced by ADDON::Interface_Network::Init().
is_host_on_lan
bool(* AddonToKodiFuncTable_kodi_network::is_host_on_lan) (void *kodiBase, const char *hostname, bool offLineCheck)
Referenced by ADDON::Interface_Network::Init().
is_local_host
bool(* AddonToKodiFuncTable_kodi_network::is_local_host) (void *kodiBase, const char *hostname)
Referenced by ADDON::Interface_Network::Init().
url_encode
char *(* AddonToKodiFuncTable_kodi_network::url_encode) (void *kodiBase, const char *url)
Referenced by ADDON::Interface_Network::Init().
wake_on_lan
bool(* AddonToKodiFuncTable_kodi_network::wake_on_lan) (void *kodiBase, const char *mac)
Referenced by ADDON::Interface_Network::Init().
The documentation for this struct was generated from the following file:
addons/kodi-dev-kit/include/kodi/c-api/Network.h