Kodi Documentation: CFileOperationJob::CFileOperation Class Reference
CFileOperationJob::CFileOperation Class Reference
Public Member Functions
CFileOperation (FileAction action, const std::string &strFileA, const std::string &strFileB, int64_t time)
bool OnFileCallback (void *pContext, int ipercent, float avgSpeed) override
bool ExecuteOperation (CFileOperationJob *base, double &current, double opWeight)
Public Member Functions inherited from XFILE::IFileCallback
virtual ~IFileCallback ()=default
Private Attributes
FileAction m_action
std::string m_strFileA
std::string m_strFileB
int64_t m_time
Constructor & Destructor Documentation
CFileOperation()
CFileOperationJob::CFileOperation::CFileOperation (FileAction action, const std::string & strFileA, const std::string & strFileB, int64_t time)
Member Function Documentation
ExecuteOperation()
bool CFileOperationJob::CFileOperation::ExecuteOperation (CFileOperationJob * base, double & current, double opWeight)
References CFileOperationJob::ActionCopy, CFileOperationJob::ActionCreateFolder, CFileOperationJob::ActionDelete, CFileOperationJob::ActionDeleteFolder, CFileOperationJob::ActionMove, CFileOperationJob::ActionReplace, CFileOperationJob::CanBeRenamed(), XFILE::CFile::Copy(), XFILE::CDirectory::Create(), data(), XFILE::CFile::Delete(), CFileOperationJob::GetActionString(), CFileOperationJob::GetCurrentFile(), CURL::GetFileNameWithoutPath(), CLog::Log(), LOGERROR, CFileOperationJob::m_action, CFileOperationJob::m_currentFile, CFileOperationJob::m_currentOperation, XFILE::CDirectory::Remove(), XFILE::CFile::Rename(), CProgressJob::SetText(), and CProgressJob::ShouldCancel().
OnFileCallback()
bool CFileOperationJob::CFileOperation::OnFileCallback (void * pContext, int ipercent, float avgSpeed) override virtual
Implements XFILE::IFileCallback.
References DataHolder::current, and data().
Member Data Documentation
m_action
FileAction CFileOperationJob::CFileOperation::m_action private
m_strFileA
std::string CFileOperationJob::CFileOperation::m_strFileA private
m_strFileB
std::string CFileOperationJob::CFileOperation::m_strFileB private
m_time
int64_t CFileOperationJob::CFileOperation::m_time private
The documentation for this class was generated from the following files:
FileOperationJob.h
FileOperationJob.cpp