Kodi Documentation: CAnnounceReceiver Class Reference
CAnnounceReceiver Class Reference
#include <AnnounceReceiver.h>
Public Member Functions
void Initialize ()
void DeInitialize ()
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Static Public Member Functions
static CAnnounceReceiver * GetInstance ()
Private Member Functions
CAnnounceReceiver ()=default
Constructor & Destructor Documentation
CAnnounceReceiver()
CAnnounceReceiver::CAnnounceReceiver () private default
Member Function Documentation
Announce()
void CAnnounceReceiver::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References AnnounceBridge(), and data().
DeInitialize()
void CAnnounceReceiver::DeInitialize ()
References CServiceBroker::GetAnnouncementManager(), and GetInstance().
GetInstance()
CAnnounceReceiver * CAnnounceReceiver::GetInstance () static
Referenced by XBMCController::CallExit, DeInitialize(), and Initialize().
Initialize()
void CAnnounceReceiver::Initialize ()
References CServiceBroker::GetAnnouncementManager(), and GetInstance().
Referenced by XBMCController::CallExit.
The documentation for this class was generated from the following files:
AnnounceReceiver.h
AnnounceReceiver.mm