Kodi Documentation: dxerr.cpp File Reference
dxerr.cpp File Reference
#include "dxerr.h"
#include <cstdio>
#include <ddraw.h>
#include <mmsystem.h>
#include <dsound.h>
#include <d3d10_1.h>
#include <d3d11.h>
#include <wincodec.h>
#include <d2d1.h>
#include <dwrite.h>
#include <Audioclient.h>
Macros
#define XAUDIO2_E_INVALID_CALL 0x88960001
#define XAUDIO2_E_XMA_DECODER_ERROR 0x88960002
#define XAUDIO2_E_XAPO_CREATION_FAILED 0x88960003
#define XAUDIO2_E_DEVICE_INVALIDATED 0x88960004
#define XAPO_E_FORMAT_UNSUPPORTED MAKE_HRESULT(SEVERITY_ERROR, 0x897, 0x01)
#define DXUTERR_NODIRECT3D MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0901)
#define DXUTERR_NOCOMPATIBLEDEVICES MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0902)
#define DXUTERR_MEDIANOTFOUND MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0903)
#define DXUTERR_NONZEROREFCOUNT MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0904)
#define DXUTERR_CREATINGDEVICE MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0905)
#define DXUTERR_RESETTINGDEVICE MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0906)
#define DXUTERR_CREATINGDEVICEOBJECTS MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0907)
#define DXUTERR_RESETTINGDEVICEOBJECTS MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0908)
#define DXUTERR_INCORRECTVERSION MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0909)
#define DXUTERR_DEVICEREMOVED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x090A)
#define BUFFER_SIZE 3000
#define CHK_ERR(hrchk, strOut)
#define CHK_ERRA(hrchk)
#define HRESULT_FROM_WIN32b(x) ((HRESULT)(x) <= 0 ? ((HRESULT)(x)) : ((HRESULT) (((x) & 0x0000FFFF) | (FACILITY_WIN32 << 16) | 0x80000000)))
#define CHK_ERR_WIN32A(hrchk)
#define CHK_ERR_WIN32_ONLY(hrchk, strOut)
#define CHK_ERRA(hrchk)
#define CHK_ERR(hrchk, strOut)
Functions
const WCHAR *WINAPI DXGetErrorStringW (_In_ HRESULT hr)
void WINAPI DXGetErrorDescriptionW (_In_ HRESULT hr, _Out_cap_(count) WCHAR *desc, _In_ size_t count)
HRESULT WINAPI DXTraceW (_In_z_ const WCHAR *strFile, _In_ DWORD dwLine, _In_ HRESULT hr, _In_opt_ const WCHAR *strMsg, _In_ bool bPopMsgBox)
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 3000
CHK_ERR [1/2]
#define CHK_ERR (hrchk, strOut)
Value:
        case static_cast<HRESULT>(hrchk): \
             return L##strOut;
CHK_ERR [2/2]
#define CHK_ERR (hrchk, strOut)
Value:
        case static_cast<HRESULT>(hrchk): \
             wcscpy_s( desc, count, L##strOut ); break;
CHK_ERR_WIN32_ONLY
#define CHK_ERR_WIN32_ONLY (hrchk, strOut)
Value:
        case HRESULT_FROM_WIN32b(hrchk): \
             return L##strOut;
CHK_ERR_WIN32A
#define CHK_ERR_WIN32A (hrchk)
Value:
        case HRESULT_FROM_WIN32b(hrchk): \
        case hrchk: \
             return L## #hrchk;
CHK_ERRA [1/2]
#define CHK_ERRA (hrchk)
Value:
        case static_cast<HRESULT>(hrchk): \
             return L## #hrchk;
CHK_ERRA [2/2]
#define CHK_ERRA (hrchk)
Value:
        case static_cast<HRESULT>(hrchk): \
             wcscpy_s( desc, count, L## #hrchk ); break;
DXUTERR_CREATINGDEVICE
#define DXUTERR_CREATINGDEVICE MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0905)
DXUTERR_CREATINGDEVICEOBJECTS
#define DXUTERR_CREATINGDEVICEOBJECTS MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0907)
DXUTERR_DEVICEREMOVED
#define DXUTERR_DEVICEREMOVED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x090A)
DXUTERR_INCORRECTVERSION
#define DXUTERR_INCORRECTVERSION MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0909)
DXUTERR_MEDIANOTFOUND
#define DXUTERR_MEDIANOTFOUND MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0903)
DXUTERR_NOCOMPATIBLEDEVICES
#define DXUTERR_NOCOMPATIBLEDEVICES MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0902)
DXUTERR_NODIRECT3D
#define DXUTERR_NODIRECT3D MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0901)
DXUTERR_NONZEROREFCOUNT
#define DXUTERR_NONZEROREFCOUNT MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0904)
DXUTERR_RESETTINGDEVICE
#define DXUTERR_RESETTINGDEVICE MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0906)
DXUTERR_RESETTINGDEVICEOBJECTS
#define DXUTERR_RESETTINGDEVICEOBJECTS MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0x0908)
HRESULT_FROM_WIN32b
#define HRESULT_FROM_WIN32b (x) ((HRESULT)(x) <= 0 ? ((HRESULT)(x)) : ((HRESULT) (((x) & 0x0000FFFF) | (FACILITY_WIN32 << 16) | 0x80000000)))
XAPO_E_FORMAT_UNSUPPORTED
#define XAPO_E_FORMAT_UNSUPPORTED MAKE_HRESULT(SEVERITY_ERROR, 0x897, 0x01)
XAUDIO2_E_DEVICE_INVALIDATED
#define XAUDIO2_E_DEVICE_INVALIDATED 0x88960004
XAUDIO2_E_INVALID_CALL
#define XAUDIO2_E_INVALID_CALL 0x88960001
XAUDIO2_E_XAPO_CREATION_FAILED
#define XAUDIO2_E_XAPO_CREATION_FAILED 0x88960003
XAUDIO2_E_XMA_DECODER_ERROR
#define XAUDIO2_E_XMA_DECODER_ERROR 0x88960002
Function Documentation
DXGetErrorDescriptionW()
void WINAPI DXGetErrorDescriptionW (_In_ HRESULT hr, _Out_cap_(count) WCHAR * desc, _In_ size_t count)
References CHK_ERR, CHK_ERRA, DXUTERR_CREATINGDEVICE, DXUTERR_CREATINGDEVICEOBJECTS, DXUTERR_DEVICEREMOVED, DXUTERR_INCORRECTVERSION, DXUTERR_MEDIANOTFOUND, DXUTERR_NOCOMPATIBLEDEVICES, DXUTERR_NODIRECT3D, DXUTERR_NONZEROREFCOUNT, DXUTERR_RESETTINGDEVICE, DXUTERR_RESETTINGDEVICEOBJECTS, XAPO_E_FORMAT_UNSUPPORTED, XAUDIO2_E_DEVICE_INVALIDATED, XAUDIO2_E_INVALID_CALL, XAUDIO2_E_XAPO_CREATION_FAILED, and XAUDIO2_E_XMA_DECODER_ERROR.
Referenced by CWIN32Util::FormatHRESULT().
DXGetErrorStringW()
const WCHAR *WINAPI DXGetErrorStringW (_In_ HRESULT hr)
References CHK_ERR_WIN32_ONLY, CHK_ERR_WIN32A, CHK_ERRA, DXUTERR_CREATINGDEVICE, DXUTERR_CREATINGDEVICEOBJECTS, DXUTERR_DEVICEREMOVED, DXUTERR_INCORRECTVERSION, DXUTERR_MEDIANOTFOUND, DXUTERR_NOCOMPATIBLEDEVICES, DXUTERR_NODIRECT3D, DXUTERR_NONZEROREFCOUNT, DXUTERR_RESETTINGDEVICE, DXUTERR_RESETTINGDEVICEOBJECTS, WSAECONNRESET, XAPO_E_FORMAT_UNSUPPORTED, XAUDIO2_E_DEVICE_INVALIDATED, XAUDIO2_E_INVALID_CALL, XAUDIO2_E_XAPO_CREATION_FAILED, and XAUDIO2_E_XMA_DECODER_ERROR.
Referenced by DXTraceW(), and CWIN32Util::FormatHRESULT().
DXTraceW()
HRESULT WINAPI DXTraceW (_In_z_ const WCHAR * strFile, _In_ DWORD dwLine, _In_ HRESULT hr, _In_opt_ const WCHAR * strMsg, _In_ bool bPopMsgBox)
References BUFFER_SIZE, DXGetErrorStringW(), and MAX_PATH.