Kodi Documentation: CBaseRenderer Class Reference
CBaseRenderer Class Reference abstract
#include <BaseRenderer.h>
Public Member Functions
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool Configure (const VideoPicture &picture, float fps, unsigned int orientation)=0
virtual bool IsConfigured ()=0
virtual void AddVideoPicture (const VideoPicture &picture, int index)=0
virtual bool IsPictureHW (const VideoPicture &picture)
virtual void UnInit ()=0
virtual bool Flush (bool saveBuffers)
virtual void SetBufferSize (int numBuffers)
virtual void ReleaseBuffer (int idx)
virtual bool NeedBuffer (int idx)
virtual bool IsGuiLayer ()
virtual CRenderInfo GetRenderInfo ()
virtual void Update ()=0
virtual void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha)=0
virtual bool RenderCapture (int index, CRenderCapture *capture)=0
virtual bool ConfigChanged (const VideoPicture &picture)=0
virtual bool SupportsMultiPassRendering ()=0
virtual bool Supports (ERENDERFEATURE feature) const
virtual bool Supports (ESCALINGMETHOD method) const =0
virtual bool WantsDoublePass ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
virtual DEBUG_INFO_VIDEO GetDebugInfo (int idx)
virtual CRenderCapture * GetRenderCapture ()
Static Public Member Functions
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ManageRenderArea ()
virtual void ReorderDrawPoints ()
virtual EShaderFormat GetShaderFormat ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Protected Attributes
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Private Attributes
bool m_alwaysClip = false
Constructor & Destructor Documentation
CBaseRenderer()
CBaseRenderer::CBaseRenderer ()
References m_rotatedDestCoords, m_savedRotatedDestCoords, CPointGen< T >::x, and CPointGen< T >::y.
~CBaseRenderer()
CBaseRenderer::~CBaseRenderer () virtual default
Member Function Documentation
AddVideoPicture()
virtual void CBaseRenderer::AddVideoPicture (const VideoPicture & picture, int index) pure virtual
Implemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodec, CRendererMediaCodecSurface, CRendererStarfish, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::AddVideoPicture().
CalcDestRect()
void CBaseRenderer::CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect & destRect) protected
References RESOLUTION_INFO::fPixelRatio, CWinSystemBase::GetGfxContext(), CGraphicContext::GetResInfo(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), m_renderOrientation, MathUtils::round_int(), CRectGen< T >::SetRect(), CSettings::SETTING_VIDEOPLAYER_ERRORINASPECT, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CalcNormalRenderRect(), and CRendererDRMPRIME::ManageRenderArea().
CalcNormalRenderRect()
void CBaseRenderer::CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift) protected
References CalcDestRect(), CServiceBroker::GetWinSystem(), CRectGen< T >::Height(), CRectGen< T >::Intersect(), m_alwaysClip, m_destRect, m_sourceRect, ReorderDrawPoints(), CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by ManageRenderArea().
CalculateFrameAspectRatio()
void CBaseRenderer::CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height) protected
References m_sourceFrameRatio, m_sourceHeight, and m_sourceWidth.
Referenced by CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), and CWinRenderer::Configure().
ConfigChanged()
virtual bool CBaseRenderer::ConfigChanged (const VideoPicture & picture) pure virtual
Implemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodecSurface, CRendererStarfish, CRendererVAAPIGL, CRendererVAAPIGLES, CRendererVDPAU, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::Configure().
Configure()
virtual bool CBaseRenderer::Configure (const VideoPicture & picture, float fps, unsigned int orientation) pure virtual
Implemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodecSurface, CRendererStarfish, CRendererVAAPIGL, CRendererVAAPIGLES, CRendererVDPAU, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::Configure().
EnableAlwaysClip()
void CBaseRenderer::EnableAlwaysClip () protected
References m_alwaysClip.
Referenced by CRendererStarfish::Configure().
Flush()
virtual bool CBaseRenderer::Flush (bool saveBuffers) inline virtual
Reimplemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererVAAPIGL, CRendererVDPAU, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::Flush().
GetAspectRatio()
float CBaseRenderer::GetAspectRatio () const
References m_sourceFrameRatio.
Referenced by CRenderManager::GetAspectRatio(), ManageRenderArea(), CRendererDRMPRIME::ManageRenderArea(), and SetViewMode().
GetDebugInfo()
virtual DEBUG_INFO_VIDEO CBaseRenderer::GetDebugInfo (int idx) inline virtual
Reimplemented in CWinRenderer.
Referenced by CRenderManager::Render().
GetOrientation()
unsigned int CBaseRenderer::GetOrientation () const inline
References m_renderOrientation.
Referenced by CRenderManager::GetOrientation().
GetRenderCapture()
virtual CRenderCapture * CBaseRenderer::GetRenderCapture () inline virtual
Reimplemented in CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::AllocRenderCapture().
GetRenderInfo()
virtual CRenderInfo CBaseRenderer::GetRenderInfo () inline virtual
Reimplemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodec, CRendererMediaCodecSurface, CRendererStarfish, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::Configure().
GetShaderFormat()
EShaderFormat CBaseRenderer::GetShaderFormat () protected virtual
Reimplemented in CRendererVAAPIGL, CRendererVAAPIGLES, CRendererVDPAU, CRendererVTB, and CRendererVTB.
References CLog::Log(), LOGERROR, m_format, SHADER_NONE, SHADER_NV12, SHADER_UYVY, SHADER_YUY2, SHADER_YV12, SHADER_YV12_10, SHADER_YV12_12, SHADER_YV12_14, SHADER_YV12_16, and SHADER_YV12_9.
Referenced by CLinuxRendererGL::LoadShaders(), CLinuxRendererGLES::LoadShaders(), and CLinuxRendererGL::UpdateVideoFilter().
GetVideoRect()
void CBaseRenderer::GetVideoRect (CRect & source, CRect & dest, CRect & view) const
Get video rectangle and view window.
Parameters
source is original size of the video
dest is the target rendering area honoring aspect ratio of source
view is the entire target rendering area for the video (including black bars)
References m_destRect, m_sourceRect, and m_viewRect.
Referenced by CRenderManager::GetVideoRect(), CRenderManager::Render(), CLinuxRendererGL::UpdateVideoFilter(), and CLinuxRendererGLES::UpdateVideoFilter().
IsConfigured()
virtual bool CBaseRenderer::IsConfigured () pure virtual
Implemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodecSurface, CRendererStarfish, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
IsGuiLayer()
virtual bool CBaseRenderer::IsGuiLayer () inline virtual
Reimplemented in CRendererDRMPRIME, CRendererMediaCodecSurface, CRendererStarfish, and CLinuxRendererGLES.
Referenced by CRenderManager::Configure(), CRenderManager::IsGuiLayer(), CRenderManager::IsVideoLayer(), and CRenderManager::Render().
IsPictureHW()
virtual bool CBaseRenderer::IsPictureHW (const VideoPicture & picture) inline virtual
ManageRenderArea()
void CBaseRenderer::ManageRenderArea () protected virtual
Reimplemented in CRendererDRMPRIME, and CRendererStarfish.
References CalcNormalRenderRect(), CONF_FLAGS_STEREO_CADANCE_RIGHT_LEFT, CONF_FLAGS_STEREO_CADENCE, CONF_FLAGS_STEREO_MODE_MASK, CONF_FLAGS_STEREO_MODE_SBS, CONF_FLAGS_STEREO_MODE_TAB, GetAspectRatio(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CGraphicContext::GetStereoView(), CGraphicContext::GetViewWindow(), CServiceBroker::GetWinSystem(), CRectGen< T >::Height(), m_iFlags, m_sourceHeight, m_sourceRect, m_sourceWidth, m_viewRect, RENDER_STEREO_VIEW_LEFT, RENDER_STEREO_VIEW_RIGHT, CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CRendererDRMPRIMEGLES::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CWinRenderer::Configure(), CRendererDRMPRIME::ManageRenderArea(), CRendererStarfish::ManageRenderArea(), CRendererDRMPRIMEGLES::RenderUpdate(), CRendererMediaCodecSurface::RenderUpdate(), CLinuxRendererGL::RenderUpdate(), CLinuxRendererGLES::RenderUpdate(), CWinRenderer::RenderUpdate(), CRendererDRMPRIMEGLES::Update(), CLinuxRendererGL::Update(), CLinuxRendererGLES::Update(), and CWinRenderer::Update().
MarkDirty()
void CBaseRenderer::MarkDirty () protected
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), m_destRect, and CGUIWindowManager::MarkDirty().
Referenced by CLinuxRendererGL::RenderCapture(), and CLinuxRendererGLES::RenderCapture().
NeedBuffer()
virtual bool CBaseRenderer::NeedBuffer (int idx) inline virtual
Reimplemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererVAAPIGL, CRendererVAAPIGLES, CRendererVDPAU, CRendererVTB, CRendererVTB, and CWinRenderer.
Referenced by CRenderManager::FrameMove().
ReleaseBuffer()
virtual void CBaseRenderer::ReleaseBuffer (int idx) inline virtual
Reimplemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodec, CRendererMediaCodecSurface, CRendererStarfish, CRendererVAAPIGL, CRendererVAAPIGLES, CRendererVDPAU, CRendererVTB, CRendererVTB, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::FrameMove().
RenderCapture()
virtual bool CBaseRenderer::RenderCapture (int index, CRenderCapture * capture) pure virtual
Implemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodecSurface, CRendererStarfish, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::RenderCapture().
RenderUpdate()
virtual void CBaseRenderer::RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) pure virtual
Implemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodecSurface, CRendererStarfish, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::PresentBlend(), CRenderManager::PresentFields(), and CRenderManager::PresentSingle().
ReorderDrawPoints()
void CBaseRenderer::ReorderDrawPoints () inline protected virtual
Reimplemented in CRendererMediaCodecSurface.
References m_destRect, m_renderOrientation, m_rotatedDestCoords, RENDERFEATURE_ROTATION, Supports(), CPointGen< T >::x, CRectGen< T >::x1, CRectGen< T >::x2, CPointGen< T >::y, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CalcNormalRenderRect(), and CRendererMediaCodecSurface::ReorderDrawPoints().
restoreRotatedCoords()
void CBaseRenderer::restoreRotatedCoords () protected
References m_rotatedDestCoords, and m_savedRotatedDestCoords.
Referenced by CLinuxRendererGL::RenderCapture(), and CLinuxRendererGLES::RenderCapture().
saveRotatedCoords()
void CBaseRenderer::saveRotatedCoords () protected
References m_rotatedDestCoords, and m_savedRotatedDestCoords.
Referenced by CLinuxRendererGL::RenderCapture(), and CLinuxRendererGLES::RenderCapture().
SetBufferSize()
virtual void CBaseRenderer::SetBufferSize (int numBuffers) inline virtual
Reimplemented in CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::Configure().
SettingOptionsRenderMethodsFiller()
void CBaseRenderer::SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, CLocalizeStrings::Get(), RENDER_METHOD_AUTO, RENDER_METHOD_D3D_PS, RENDER_METHOD_DXVA, and RENDER_METHOD_SOFTWARE.
Referenced by CSettings::InitializeOptionFillers().
SetVideoSettings()
void CBaseRenderer::SetVideoSettings (const CVideoSettings & settings)
References m_videoSettings.
Referenced by CRenderManager::Configure(), and CRenderManager::SetVideoSettings().
SetViewMode()
void CBaseRenderer::SetViewMode (int viewMode)
References GetAspectRatio(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetPixelRatio(), CGraphicContext::GetResInfo(), CServiceBroker::GetSettingsComponent(), CDisplaySettings::GetVerticalShift(), CServiceBroker::GetWinSystem(), CDisplaySettings::GetZoomAmount(), CDisplaySettings::IsNonLinearStretched(), CVideoSettings::m_CustomNonLinStretch, CVideoSettings::m_CustomPixelRatio, CVideoSettings::m_CustomVerticalShift, CVideoSettings::m_CustomZoomAmount, m_sourceHeight, m_videoSettings, CVideoSettings::m_ViewMode, CDisplaySettings::SetNonLinearStretched(), CDisplaySettings::SetPixelRatio(), CSettings::SETTING_VIDEOPLAYER_STRETCH43, CDisplaySettings::SetVerticalShift(), CDisplaySettings::SetZoomAmount(), ViewModeCustom, ViewModeNormal, ViewModeOriginal, ViewModeStretch16x9, ViewModeStretch16x9Nonlin, ViewModeStretch4x3, ViewModeWideZoom, ViewModeZoom, ViewModeZoom110Width, and ViewModeZoom120Width.
Referenced by CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CWinRenderer::Configure(), and CRenderManager::SetViewMode().
Supports() [1/2]
virtual bool CBaseRenderer::Supports (ERENDERFEATURE feature) const inline virtual
Reimplemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodecSurface, CRendererStarfish, CRendererVAAPIGL, CRendererVDPAU, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by ReorderDrawPoints(), CRenderManager::Supports(), and CRenderManager::Supports().
Supports() [2/2]
virtual bool CBaseRenderer::Supports (ESCALINGMETHOD method) const pure virtual
Implemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodecSurface, CRendererStarfish, CRendererVAAPIGL, CRendererVDPAU, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
SupportsMultiPassRendering()
virtual bool CBaseRenderer::SupportsMultiPassRendering () pure virtual
Implemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodecSurface, CRendererStarfish, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
syncDestRectToRotatedPoints()
void CBaseRenderer::syncDestRectToRotatedPoints () protected
References m_destRect, m_rotatedDestCoords, CPointGen< T >::x, CRectGen< T >::x1, CRectGen< T >::x2, CPointGen< T >::y, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CLinuxRendererGL::RenderCapture(), and CLinuxRendererGLES::RenderCapture().
UnInit()
virtual void CBaseRenderer::UnInit () pure virtual
Implemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodecSurface, CRendererStarfish, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Update()
virtual void CBaseRenderer::Update () pure virtual
Implemented in CRendererDRMPRIME, CRendererDRMPRIMEGLES, CRendererMediaCodecSurface, CRendererStarfish, CLinuxRendererGL, CLinuxRendererGLES, and CWinRenderer.
Referenced by CRenderManager::Configure(), CRenderManager::Render(), and CRenderManager::UpdateResolution().
WantsDoublePass()
virtual bool CBaseRenderer::WantsDoublePass () inline virtual
Reimplemented in CWinRenderer.
Referenced by CRenderManager::AddVideoPicture().
Member Data Documentation
m_alwaysClip
bool CBaseRenderer::m_alwaysClip = false private
Referenced by CalcNormalRenderRect(), and EnableAlwaysClip().
m_destRect
CRect CBaseRenderer::m_destRect protected
Referenced by CalcNormalRenderRect(), CRendererDRMPRIMEGLES::DrawBlackBars(), CLinuxRendererGL::DrawBlackBars(), CLinuxRendererGLES::DrawBlackBars(), GetVideoRect(), CRendererDRMPRIME::ManageRenderArea(), CRendererStarfish::ManageRenderArea(), MarkDirty(), CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), CLinuxRendererGL::RenderProgressiveWeave(), CRendererMediaCodecSurface::RenderUpdate(), CWinRenderer::RenderUpdate(), ReorderDrawPoints(), CRendererVDPAU::Supports(), CLinuxRendererGL::Supports(), CLinuxRendererGLES::Supports(), and syncDestRectToRotatedPoints().
m_format
AVPixelFormat CBaseRenderer::m_format = AV_PIX_FMT_NONE protected
Referenced by CLinuxRendererGL::CLinuxRendererGL(), CLinuxRendererGLES::CLinuxRendererGLES(), CRendererDRMPRIME::ConfigChanged(), CRendererDRMPRIMEGLES::ConfigChanged(), CRendererStarfish::ConfigChanged(), CLinuxRendererGL::ConfigChanged(), CLinuxRendererGLES::ConfigChanged(), CWinRenderer::ConfigChanged(), CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CWinRenderer::Configure(), CLinuxRendererGL::CreateTexture(), CLinuxRendererGLES::CreateTexture(), CLinuxRendererGL::CreateYV12Texture(), CWinRenderer::CWinRenderer(), CLinuxRendererGL::DeleteTexture(), CLinuxRendererGLES::DeleteTexture(), GetShaderFormat(), CLinuxRendererGL::Supports(), CLinuxRendererGL::UploadTexture(), and CLinuxRendererGLES::UploadTexture().
m_fps
float CBaseRenderer::m_fps = 0.0f protected
Referenced by CLinuxRendererGL::Configure(), CWinRenderer::Configure(), and CLinuxRendererGL::UpdateVideoFilter().
m_iFlags
unsigned CBaseRenderer::m_iFlags = 0 protected
Referenced by CLinuxRendererGL::CLinuxRendererGL(), CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), CWinRenderer::Configure(), ManageRenderArea(), and CRendererMediaCodecSurface::RenderUpdate().
m_renderOrientation
unsigned int CBaseRenderer::m_renderOrientation = 0 protected
Referenced by CalcDestRect(), CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CWinRenderer::Configure(), GetOrientation(), ReorderDrawPoints(), and CRendererMediaCodecSurface::ReorderDrawPoints().
m_rotatedDestCoords
CPoint CBaseRenderer::m_rotatedDestCoords[4] protected
Referenced by CBaseRenderer(), CRendererDRMPRIMEGLES::Render(), CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGLES::RenderFromFBO(), CRendererMediaCodec::RenderHook(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGLES::RenderSinglePass(), CLinuxRendererGL::RenderSinglePass(), ReorderDrawPoints(), restoreRotatedCoords(), saveRotatedCoords(), and syncDestRectToRotatedPoints().
m_savedRotatedDestCoords
CPoint CBaseRenderer::m_savedRotatedDestCoords[4] protected
Referenced by CBaseRenderer(), restoreRotatedCoords(), and saveRotatedCoords().
m_sourceFrameRatio
float CBaseRenderer::m_sourceFrameRatio = 1.0f protected
Referenced by CalculateFrameAspectRatio(), and GetAspectRatio().
m_sourceHeight
unsigned int CBaseRenderer::m_sourceHeight = 480 protected
Referenced by CalculateFrameAspectRatio(), CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CWinRenderer::Configure(), CLinuxRendererGL::CreateNV12Texture(), CLinuxRendererGLES::CreateNV12Texture(), CRendererMediaCodec::CreateTexture(), CRendererVAAPIGL::CreateTexture(), CRendererVAAPIGLES::CreateTexture(), CRendererVTB::CreateTexture(), CRendererVDPAU::CreateVDPAUTexture(), CLinuxRendererGL::CreateYUV422PackedTexture(), CLinuxRendererGL::CreateYV12Texture(), CLinuxRendererGLES::CreateYV12Texture(), ManageRenderArea(), CRendererStarfish::ManageRenderArea(), CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGLES::RenderFromFBO(), CLinuxRendererGL::RenderProgressiveWeave(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGLES::RenderToFBO(), CLinuxRendererGL::RenderToFBO(), SetViewMode(), CRendererVDPAU::Supports(), CLinuxRendererGL::Supports(), CLinuxRendererGLES::Supports(), CLinuxRendererGL::UpdateVideoFilter(), and CLinuxRendererGLES::UpdateVideoFilter().
m_sourceRect
CRect CBaseRenderer::m_sourceRect protected
Referenced by CalcNormalRenderRect(), CLinuxRendererGL::CalculateTextureSourceRects(), CLinuxRendererGLES::CalculateTextureSourceRects(), GetVideoRect(), ManageRenderArea(), CRendererStarfish::ManageRenderArea(), CWinRenderer::RenderCapture(), CWinRenderer::RenderUpdate(), and CRendererVDPAU::UploadVDPAUTexture().
m_sourceWidth
unsigned int CBaseRenderer::m_sourceWidth = 720 protected
Referenced by CalculateFrameAspectRatio(), CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CWinRenderer::Configure(), CLinuxRendererGL::CreateNV12Texture(), CLinuxRendererGLES::CreateNV12Texture(), CRendererMediaCodec::CreateTexture(), CRendererVAAPIGL::CreateTexture(), CRendererVAAPIGLES::CreateTexture(), CRendererVTB::CreateTexture(), CRendererVDPAU::CreateVDPAUTexture(), CLinuxRendererGL::CreateYUV422PackedTexture(), CLinuxRendererGL::CreateYV12Texture(), CLinuxRendererGLES::CreateYV12Texture(), ManageRenderArea(), CRendererStarfish::ManageRenderArea(), CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGLES::RenderFromFBO(), CLinuxRendererGL::RenderProgressiveWeave(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGLES::RenderToFBO(), CLinuxRendererGL::RenderToFBO(), CRendererVDPAU::Supports(), CLinuxRendererGL::Supports(), CLinuxRendererGLES::Supports(), CLinuxRendererGL::UpdateVideoFilter(), and CLinuxRendererGLES::UpdateVideoFilter().
m_videoSettings
CVideoSettings CBaseRenderer::m_videoSettings protected
Referenced by CLinuxRendererGL::CheckVideoParameters(), CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CWinRenderer::Configure(), CLinuxRendererGL::LoadShaders(), CLinuxRendererGLES::LoadShaders(), CRendererMediaCodec::RenderHook(), CLinuxRendererGLES::RenderSinglePass(), CLinuxRendererGL::RenderSinglePass(), CLinuxRendererGLES::RenderToFBO(), CLinuxRendererGL::RenderToFBO(), CWinRenderer::SelectRenderer(), SetVideoSettings(), SetViewMode(), CLinuxRendererGL::UpdateVideoFilter(), and CLinuxRendererGLES::UpdateVideoFilter().
m_viewRect
CRect CBaseRenderer::m_viewRect protected
Referenced by GetVideoRect(), and ManageRenderArea().
The documentation for this class was generated from the following files:
BaseRenderer.h
BaseRenderer.cpp