Kodi Documentation: KODI::ADDONS::CImageDecoder Class Reference
KODI::ADDONS::CImageDecoder Class Reference
#include <ImageDecoder.h>
Public Member Functions
CImageDecoder (const ADDON::AddonInfoPtr &addonInfo, const std::string &mimetype)
~CImageDecoder () override
bool IsCreated () const
bool CreateThumbnailFromSurface (unsigned char *, unsigned int, unsigned int, unsigned int, unsigned int, const std::string &, unsigned char *&, unsigned int &) override
bool LoadImageFromMemory (unsigned char *buffer, unsigned int bufSize, unsigned int width, unsigned int height) override
Load an image from memory with the format m_strMimeType to determine it's size and orientation.
bool Decode (unsigned char *const pixels, unsigned int width, unsigned int height, unsigned int pitch, unsigned int format) override
Decodes the previously loaded image data to the output buffer in 32 bit raw bits.
bool LoadInfoTag (const std::string &fileName, CPictureInfoTag *tag)
bool SupportsFile (const std::string &filename) override
Public Member Functions inherited from ADDON::IAddonInstanceHandler
IAddonInstanceHandler (ADDON_TYPE type, const AddonInfoPtr &addonInfo, AddonInstanceId instanceId=ADDON_INSTANCE_ID_UNUSED, KODI_HANDLE parentInstance=nullptr, const std::string &uniqueWorkID="")
Class constructor for handling add-on instance processes, allowing an add-on to handle multiple work simultaneously and independently.
virtual ~IAddonInstanceHandler ()
ADDON_TYPE UsedType () const
AddonInstanceId InstanceId () const
const std::string & UniqueWorkID ()
std::string ID () const
AddonInstanceId InstanceID () const
std::string Name () const
std::string Author () const
std::string Icon () const
std::string Path () const
std::string Profile () const
CAddonVersion Version () const
ADDON_STATUS CreateInstance ()
void DestroyInstance ()
const AddonDllPtr & Addon () const
AddonInfoPtr GetAddonInfo () const
virtual void OnPreInstall ()
virtual void OnPostInstall (bool update, bool modal)
virtual void OnPreUnInstall ()
virtual void OnPostUnInstall ()
Public Member Functions inherited from KODI::ADDONS::IAddonSupportCheck
IAddonSupportCheck ()=default
virtual ~IAddonSupportCheck ()=default
Public Member Functions inherited from IImage
virtual ~IImage ()=default
virtual void ReleaseThumbnailBuffer ()
Frees the output buffer allocated by CreateThumbnailFromSurface.
unsigned int Width () const
unsigned int Height () const
unsigned int originalWidth () const
unsigned int originalHeight () const
unsigned int Orientation () const
bool hasAlpha () const
Private Attributes
const std::string m_mimetype
bool m_created {false}
Additional Inherited Members
Protected Attributes inherited from ADDON::IAddonInstanceHandler
KODI_ADDON_INSTANCE_INFO m_info {}
KODI_ADDON_INSTANCE_STRUCT m_ifc {}
Protected Attributes inherited from IImage
unsigned int m_width = 0
unsigned int m_height = 0
unsigned int m_originalWidth = 0
original image width before scaling or cropping
unsigned int m_originalHeight = 0
original image height before scaling or cropping
unsigned int m_orientation = 0
bool m_hasAlpha = false
Constructor & Destructor Documentation
CImageDecoder()
CImageDecoder::CImageDecoder (const ADDON::AddonInfoPtr & addonInfo, const std::string & mimetype) explicit
References ADDON_STATUS_OK, ADDON::IAddonInstanceHandler::CreateInstance(), KODI_ADDON_INSTANCE_STRUCT::imagedecoder, m_created, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_ImageDecoder::toAddon, and AddonInstance_ImageDecoder::toKodi.
~CImageDecoder()
CImageDecoder::~CImageDecoder () override
References ADDON::IAddonInstanceHandler::DestroyInstance(), KODI_ADDON_INSTANCE_STRUCT::imagedecoder, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_ImageDecoder::toAddon, and AddonInstance_ImageDecoder::toKodi.
Member Function Documentation
CreateThumbnailFromSurface()
bool KODI::ADDONS::CImageDecoder::CreateThumbnailFromSurface (unsigned char * , unsigned int , unsigned int , unsigned int , unsigned int , const std::string & , unsigned char *& , unsigned int &) inline override virtual
IImage related functions
Implements IImage.
Decode()
bool CImageDecoder::Decode (unsigned char *const pixels, unsigned int width, unsigned int height, unsigned int pitch, unsigned int format) override virtual
Decodes the previously loaded image data to the output buffer in 32 bit raw bits.
Parameters
pixels The output buffer
width The width of the image
height The height of the image
pitch The pitch of the output buffer
format The format of the output buffer (JpegIO only)
Returns
true if the image data could be decoded to the output buffer
Implements IImage.
References KodiToAddonFuncTable_ImageDecoder::decode, KODI_ADDON_INSTANCE_STRUCT::hdl, KODI_ADDON_INSTANCE_STRUCT::imagedecoder, m_created, IImage::m_height, ADDON::IAddonInstanceHandler::m_ifc, IImage::m_width, and AddonInstance_ImageDecoder::toAddon.
IsCreated()
bool KODI::ADDONS::CImageDecoder::IsCreated () const inline
References m_created.
LoadImageFromMemory()
bool CImageDecoder::LoadImageFromMemory (unsigned char * buffer, unsigned int bufSize, unsigned int width, unsigned int height) override virtual
Load an image from memory with the format m_strMimeType to determine it's size and orientation.
Parameters
buffer The memory location where the image data can be found
bufSize The size of the buffer
width The ideal width of the texture
height The ideal height of the texture
Returns
true if the image could be loaded
Implements IImage.
References KODI_ADDON_INSTANCE_STRUCT::hdl, KODI_ADDON_INSTANCE_STRUCT::imagedecoder, KodiToAddonFuncTable_ImageDecoder::load_image_from_memory, m_created, IImage::m_height, ADDON::IAddonInstanceHandler::m_ifc, m_mimetype, IImage::m_width, and AddonInstance_ImageDecoder::toAddon.
LoadInfoTag()
bool CImageDecoder::LoadInfoTag (const std::string & fileName, CPictureInfoTag * tag)
From CPictureInfoTag used function to get information from addon
List of values currently not used on addon interface.
struct ExifInfo:
int Process{};
float CCDWidth{};
int Whitebalance{};
int CommentsCharset{};
int XPCommentsCharset{};
std::string Comments;
std::string FileComment;
std::string XPComment;
struct IPTCInfo:
std::string RecordVersion;
std::string SupplementalCategories;
std::string Keywords;
std::string Caption;
std::string Headline;
std::string SpecialInstructions;
std::string Category;
std::string Byline;
std::string BylineTitle;
std::string Credit;
std::string Source;
std::string ObjectName;
std::string City;
std::string State;
std::string Country;
std::string TransmissionReference;
std::string Date;
std::string Urgency;
std::string ReferenceService;
std::string CountryCode;
std::string SubLocation;
std::string ImageType;
Todo:
Rework CPictureInfoTag to not limit on fixed structures ExifInfo & IPTCInfo.
References ADDON_IMG_COLOR_COLORED, KODI_ADDON_IMAGEDECODER_INFO_TAG::altitude, KODI_ADDON_IMAGEDECODER_INFO_TAG::altitude_ref, KODI_ADDON_IMAGEDECODER_INFO_TAG::aperture_f_number, KODI_ADDON_IMAGEDECODER_INFO_TAG::author, KODI_ADDON_IMAGEDECODER_INFO_TAG::camera_manufacturer, KODI_ADDON_IMAGEDECODER_INFO_TAG::camera_model, KODI_ADDON_IMAGEDECODER_INFO_TAG::color, KODI_ADDON_IMAGEDECODER_INFO_TAG::copyright, KODI_ADDON_IMAGEDECODER_INFO_TAG::description, KODI_ADDON_IMAGEDECODER_INFO_TAG::digital_zoom_ratio, KODI_ADDON_IMAGEDECODER_INFO_TAG::distance, KODI_ADDON_IMAGEDECODER_INFO_TAG::exposure_bias, KODI_ADDON_IMAGEDECODER_INFO_TAG::exposure_mode, KODI_ADDON_IMAGEDECODER_INFO_TAG::exposure_program, KODI_ADDON_IMAGEDECODER_INFO_TAG::exposure_time, KODI_ADDON_IMAGEDECODER_INFO_TAG::flash_used, KODI_ADDON_IMAGEDECODER_INFO_TAG::focal_length, KODI_ADDON_IMAGEDECODER_INFO_TAG::focal_length_in_35mm_format, CDateTime::GetAsLocalizedDateTime(), KODI_ADDON_IMAGEDECODER_INFO_TAG::gps_info_present, KODI_ADDON_INSTANCE_STRUCT::hdl, KODI_ADDON_IMAGEDECODER_INFO_TAG::height, KODI_ADDON_INSTANCE_STRUCT::imagedecoder, KODI_ADDON_IMAGEDECODER_INFO_TAG::iso_speed, KODI_ADDON_IMAGEDECODER_INFO_TAG::latitude, KODI_ADDON_IMAGEDECODER_INFO_TAG::latitude_ref, KODI_ADDON_IMAGEDECODER_INFO_TAG::light_source, KODI_ADDON_IMAGEDECODER_INFO_TAG::longitude, KODI_ADDON_IMAGEDECODER_INFO_TAG::longitude_ref, m_created, ADDON::IAddonInstanceHandler::m_ifc, KODI_ADDON_IMAGEDECODER_INFO_TAG::metering_mode, KODI_ADDON_IMAGEDECODER_INFO_TAG::orientation, KodiToAddonFuncTable_ImageDecoder::read_tag, CDateTime::SetFromUTCDateTime(), KODI_ADDON_IMAGEDECODER_INFO_TAG::time_created, AddonInstance_ImageDecoder::toAddon, and KODI_ADDON_IMAGEDECODER_INFO_TAG::width.
SupportsFile()
bool CImageDecoder::SupportsFile (const std::string & filename) override virtual
KODI::ADDONS::IAddonSupportCheck related function
Reimplemented from KODI::ADDONS::IAddonSupportCheck.
References KODI_ADDON_INSTANCE_STRUCT::hdl, KODI_ADDON_INSTANCE_STRUCT::imagedecoder, m_created, ADDON::IAddonInstanceHandler::m_ifc, KodiToAddonFuncTable_ImageDecoder::supports_file, and AddonInstance_ImageDecoder::toAddon.
Member Data Documentation
m_created
bool KODI::ADDONS::CImageDecoder::m_created {false} private
Referenced by CImageDecoder(), Decode(), IsCreated(), LoadImageFromMemory(), LoadInfoTag(), and SupportsFile().
m_mimetype
const std::string KODI::ADDONS::CImageDecoder::m_mimetype private
Note
m_mimetype not set in all cases, only available if LoadImageFromMemory is used.
Referenced by LoadImageFromMemory().
The documentation for this class was generated from the following files:
imagedecoder.h
ImageDecoder.cpp