Kodi Documentation: DialogProgress
DialogProgress
Python » Library - xbmcgui » Dialog
Kodi's progress dialog class (Duh!)
Modules
DialogProgressBG
Kodi's background progress dialog class
Classes
class XBMCAddon::xbmcgui::DialogProgress
Functions
XBMCAddon::xbmcgui::DialogProgress::create (...)
XBMCAddon::xbmcgui::DialogProgress::update (...)
XBMCAddon::xbmcgui::DialogProgress::close (...)
XBMCAddon::xbmcgui::DialogProgress::iscanceled (...)
Detailed Description
Kodi's progress dialog class (Duh!)
Function Documentation
close()
void XBMCAddon::xbmcgui::DialogProgress::close (...)
Function: xbmcgui.DialogProgress().close()
Close the progress dialog.
Example:
..
pDialog.close()
..
References CGUIWindow::Close(), XBMCAddon::xbmcgui::DialogProgress::dlg, XBMCAddon::AddonClass::languageHook, and XBMCAddon::xbmcgui::DialogProgress::open.
create()
void XBMCAddon::xbmcgui::DialogProgress::create (...)
Function: xbmcgui.DialogProgress().create(heading[, message])
Create and show a progress dialog.
Parameters
heading string or unicode - dialog heading.
message [opt] string or unicode - message text.
Note
Use update() to update lines and progressbar.
v19 Python API changes:
Renamed option line1 to message.
Removed option line2.
Removed option line3.
Example:
..
pDialog = xbmcgui.DialogProgress()
pDialog.create('Kodi', 'Initializing script...')
..
References XBMCAddon::xbmcgui::DialogProgress::dlg, CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), XBMCAddon::AddonClass::languageHook, CGUIDialogProgress::Open(), XBMCAddon::xbmcgui::DialogProgress::open, CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetText(), and WINDOW_DIALOG_PROGRESS.
iscanceled()
bool XBMCAddon::xbmcgui::DialogProgress::iscanceled (...)
Function: xbmcgui.DialogProgress().iscanceled()
Checks progress is canceled.
Returns
True if the user pressed cancel.
Example:
..
if (pDialog.iscanceled()): return
..
References XBMCAddon::xbmcgui::DialogProgress::dlg, and CGUIDialogProgress::IsCanceled().
update()
void XBMCAddon::xbmcgui::DialogProgress::update (...)
Function: xbmcgui.DialogProgress().update(percent[, message])
Updates the progress dialog.
Parameters
percent integer - percent complete. (0:100)
message [opt] string or unicode - message text.
v19 Python API changes:
Renamed option line1 to message.
Removed option line2.
Removed option line3.
Example:
..
pDialog.update(25, 'Importing modules...')
..
References XBMCAddon::xbmcgui::DialogProgress::dlg, XBMCAddon::AddonClass::languageHook, CGUIDialogProgress::SetPercentage(), CGUIDialogBoxBase::SetText(), and CGUIDialogProgress::ShowProgressBar().