Kodi Documentation: XBMCAddon::LanguageHook Class Reference
XBMCAddon::LanguageHook Class Reference abstract
#include <LanguageHook.h>
Public Member Functions
~LanguageHook () override
virtual void DelayedCallOpen ()
virtual void DelayedCallClose ()
virtual void MakePendingCalls ()
virtual CallbackHandler * GetCallbackHandler ()
virtual void Constructing (AddonClass *beingConstructed)
virtual void Destructing (AddonClass *beingDestructed)
virtual String GetAddonId ()
virtual String GetAddonVersion ()
virtual long GetInvokerId ()
virtual void RegisterPlayerCallback (IPlayerCallback *player)=0
virtual void UnregisterPlayerCallback (IPlayerCallback *player)=0
virtual void RegisterMonitorCallback (XBMCAddon::xbmc::Monitor *player)=0
virtual void UnregisterMonitorCallback (XBMCAddon::xbmc::Monitor *player)=0
virtual bool WaitForEvent (CEvent &hEvent, unsigned int milliseconds)=0
Public Member Functions inherited from XBMCAddon::AddonClass
AddonClass ()
virtual ~AddonClass ()
const char * GetClassname () const
LanguageHook * GetLanguageHook ()
bool isDeallocating ()
void Release () const
void Acquire () const
Static Public Member Functions
static void SetLanguageHook (LanguageHook *languageHook)
static LanguageHook * GetLanguageHook ()
static void ClearLanguageHook ()
Static Public Member Functions inherited from XBMCAddon::AddonClass
static short getNumAddonClasses ()
Protected Member Functions
LanguageHook ()=default
Protected Member Functions inherited from XBMCAddon::AddonClass
virtual void deallocating ()
Additional Inherited Members
Static Protected Member Functions inherited from XBMCAddon::AddonClass
static short getNextClassIndex ()
Protected Attributes inherited from XBMCAddon::AddonClass
LanguageHook * languageHook
Constructor & Destructor Documentation
LanguageHook()
XBMCAddon::LanguageHook::LanguageHook () inline protected default
~LanguageHook()
XBMCAddon::LanguageHook::~LanguageHook () override default
Member Function Documentation
ClearLanguageHook()
void XBMCAddon::LanguageHook::ClearLanguageHook () static
References XBMCAddon::addonLanguageHookTls, and XBMCAddon::AddonClass::Release().
Referenced by XBMCAddon::AddonClass::AddonClass(), XBMCAddon::DelayedCallGuard::~DelayedCallGuard(), and XBMCAddon::SetLanguageHookGuard::~SetLanguageHookGuard().
Constructing()
virtual void XBMCAddon::LanguageHook::Constructing (AddonClass * beingConstructed) inline virtual
This is a callback method that can be overridden to receive a callback when an AddonClass that has this language hook is on is being constructed. It is called from the constructor of AddonClass so the implementor cannot assume the subclasses have been built or that calling a virtual function on the AddonClass will work as expected.
DelayedCallClose()
virtual void XBMCAddon::LanguageHook::DelayedCallClose () inline virtual
If the scripting language needs special handling for calls that block or are delayed in any other means, this should be overloaded.
In Python when control is passed to a native method that blocks, you need to allow other threads in Python to run by using Py_BEGIN_ALLOW_THREADS. When that delayed method ends you need to restore the Python thread state using Py_END_ALLOW_THREADS. This is the place to put that functionality
Reimplemented in XBMCAddon::Python::PythonLanguageHook.
Referenced by XBMCAddon::DelayedCallGuard::~DelayedCallGuard(), and XBMCAddonUtils::GuiLock::~GuiLock().
DelayedCallOpen()
virtual void XBMCAddon::LanguageHook::DelayedCallOpen () inline virtual
If the scripting language needs special handling for calls that block or are delayed in any other means, this should be overloaded.
In Python when control is passed to a native method that blocks, you need to allow other threads in Python to run by using Py_BEGIN_ALLOW_THREADS. This is the place to put that functionality
Reimplemented in XBMCAddon::Python::PythonLanguageHook.
Referenced by XBMCAddon::DelayedCallGuard::DelayedCallGuard(), XBMCAddon::DelayedCallGuard::DelayedCallGuard(), and XBMCAddonUtils::GuiLock::GuiLock().
Destructing()
virtual void XBMCAddon::LanguageHook::Destructing (AddonClass * beingDestructed) inline virtual
This is a callback method that can be overridden to receive a callback when an AddonClass that has this language hook is on is being destructed. It is called from the destructor of AddonClass so the implementor should assume the subclasses have been torn down and that calling a virtual function on the AddonClass will not work as expected.
GetAddonId()
virtual String XBMCAddon::LanguageHook::GetAddonId () inline virtual
This method should be done a different way but since the only other way I can think to do it requires an InheritableThreadLocal C++ equivalent, I'm going to defer to this technique for now.
Currently (for python) the scripting language has the Addon id injected into it as a global variable. Therefore the only way to retrieve it is to use scripting language specific calls. So until I figure out a better way to do this, this is how I need to retrieve it.
Reimplemented in XBMCAddon::Python::PythonLanguageHook.
References XBMCAddon::emptyString.
Referenced by XBMCAddon::xbmcaddon::Addon::getDefaultId(), and XBMCAddon::xbmc::Monitor::Monitor().
GetAddonVersion()
virtual String XBMCAddon::LanguageHook::GetAddonVersion () inline virtual
Reimplemented in XBMCAddon::Python::PythonLanguageHook.
References XBMCAddon::emptyString.
Referenced by XBMCAddon::xbmcaddon::Addon::getAddonVersion().
GetCallbackHandler()
virtual CallbackHandler * XBMCAddon::LanguageHook::GetCallbackHandler () inline virtual
For scripting languages that need a global callback handler, this method should be overloaded to supply one.
Reimplemented in XBMCAddon::Python::PythonLanguageHook.
Referenced by XBMCAddon::AddonCallback::AddonCallback().
GetInvokerId()
virtual long XBMCAddon::LanguageHook::GetInvokerId () inline virtual
Reimplemented in XBMCAddon::Python::PythonLanguageHook.
Referenced by XBMCAddon::xbmc::Monitor::Monitor().
GetLanguageHook()
LanguageHook * XBMCAddon::LanguageHook::GetLanguageHook () static
References XBMCAddon::addonLanguageHookTls, and XBMCAddon::threadLocalInitialized.
Referenced by XBMCAddon::AddonClass::AddonClass(), and XBMCAddonUtils::GuiLock::GuiLock().
MakePendingCalls()
virtual void XBMCAddon::LanguageHook::MakePendingCalls () inline virtual
Reimplemented in XBMCAddon::Python::PythonLanguageHook.
Referenced by XBMCAddon::xbmcgui::Window::doModal(), XBMCAddon::xbmc::sleep(), and XBMCAddon::xbmc::Monitor::waitForAbort().
RegisterMonitorCallback()
virtual void XBMCAddon::LanguageHook::RegisterMonitorCallback (XBMCAddon::xbmc::Monitor * player) pure virtual
Implemented in XBMCAddon::Python::PythonLanguageHook.
Referenced by XBMCAddon::xbmc::Monitor::Monitor().
RegisterPlayerCallback()
virtual void XBMCAddon::LanguageHook::RegisterPlayerCallback (IPlayerCallback * player) pure virtual
Implemented in XBMCAddon::Python::PythonLanguageHook.
SetLanguageHook()
void XBMCAddon::LanguageHook::SetLanguageHook (LanguageHook * languageHook) static
References XBMCAddon::AddonClass::Acquire(), XBMCAddon::addonLanguageHookTls, XBMCAddon::AddonClass::languageHook, and XBMC_TRACE.
Referenced by XBMCAddon::SetLanguageHookGuard::SetLanguageHookGuard().
UnregisterMonitorCallback()
virtual void XBMCAddon::LanguageHook::UnregisterMonitorCallback (XBMCAddon::xbmc::Monitor * player) pure virtual
Implemented in XBMCAddon::Python::PythonLanguageHook.
Referenced by XBMCAddon::xbmc::Monitor::~Monitor().
UnregisterPlayerCallback()
virtual void XBMCAddon::LanguageHook::UnregisterPlayerCallback (IPlayerCallback * player) pure virtual
Implemented in XBMCAddon::Python::PythonLanguageHook.
WaitForEvent()
virtual bool XBMCAddon::LanguageHook::WaitForEvent (CEvent & hEvent, unsigned int milliseconds) pure virtual
Implemented in XBMCAddon::Python::PythonLanguageHook.
Referenced by XBMCAddon::xbmcgui::Window::WaitForActionEvent().
The documentation for this class was generated from the following files:
legacy/LanguageHook.h
legacy/LanguageHook.cpp