Kodi Documentation: CDDB::Xcddb Class Reference
CDDB::Xcddb Class Reference
#include <cddb.h>
Public Member Functions
Xcddb ()
virtual ~Xcddb ()
void setCDDBIpAddress (const std::string &ip_address)
void setCacheDir (const std::string &pCacheDir)
bool queryCDinfo (MEDIA_DETECT::CCdInfo *pInfo, int inexact_list_select)
bool queryCDinfo (MEDIA_DETECT::CCdInfo *pInfo)
int getLastError () const
const char * getLastErrorText () const
const std::string & getYear () const
const std::string & getGenre () const
const std::string & getTrackArtist (int track) const
const std::string & getTrackTitle (int track) const
void getDiskArtist (std::string &strdisk_artist) const
void getDiskTitle (std::string &strdisk_title) const
const std::string & getTrackExtended (int track) const
uint32_t calc_disc_id (int nr_of_tracks, toc cdtoc[])
const std::string & getInexactArtist (int select) const
const std::string & getInexactTitle (int select) const
bool queryCache (uint32_t discid)
bool writeCacheFile (const char *pBuffer, uint32_t discid)
bool isCDCached (int nr_of_tracks, toc cdtoc[])
bool isCDCached (MEDIA_DETECT::CCdInfo *pInfo)
Protected Types
using CAutoPtrSocket = KODI::UTILS::CScopeGuard< int, -1, decltype(close)>
Protected Member Functions
void addTitle (const char *buffer)
void addExtended (const char *buffer)
void parseData (const char *buffer)
bool Send (const void *buffer, int bytes)
bool Send (const char *buffer)
std::string Recv (bool wait4point)
bool openSocket ()
bool closeSocket ()
int cddb_sum (int n)
void addInexactList (const char *list)
void addInexactListLine (int line_cnt, const char *line, int len)
const std::string & getInexactCommand (int select) const
std::string GetCacheFile (uint32_t disc_id) const
std::string TrimToUTF8 (const std::string &untrimmed)
Trim and convert some text to UTF8.
Protected Attributes
std::string m_strNull
CAutoPtrSocket m_cddb_socket
int m_lastError
std::map< int, std::string > m_mapTitles
std::map< int, std::string > m_mapArtists
std::map< int, std::string > m_mapExtended_track
std::map< int, std::string > m_mapInexact_cddb_command_list
std::map< int, std::string > m_mapInexact_artist_list
std::map< int, std::string > m_mapInexact_title_list
std::string m_strDisk_artist
std::string m_strDisk_title
std::string m_strYear
std::string m_strGenre
struct toc cdtoc [100]
std::string m_cddb_ip_address
std::string cCacheDir
Static Protected Attributes
static const int recv_buffer = 4096
Member Typedef Documentation
CAutoPtrSocket
using CDDB::Xcddb::CAutoPtrSocket = KODI::UTILS::CScopeGuard<int, -1, decltype(close)> protected
Constructor & Destructor Documentation
Xcddb()
Xcddb::Xcddb ()
~Xcddb()
Xcddb::~Xcddb () virtual
References closeSocket().
Member Function Documentation
addExtended()
void Xcddb::addExtended (const char * buffer) protected
References g_charsetConverter, m_mapExtended_track, and value.
Referenced by parseData().
addInexactList()
void Xcddb::addInexactList (const char * list) protected
References addInexactListLine(), and end().
Referenced by queryCDinfo().
addInexactListLine()
void Xcddb::addInexactListLine (int line_cnt, const char * line, int len) protected
References g_charsetConverter, m_mapInexact_artist_list, m_mapInexact_cddb_command_list, and m_mapInexact_title_list.
Referenced by addInexactList().
addTitle()
void Xcddb::addTitle (const char * buffer) protected
References g_charsetConverter, m_mapArtists, m_mapTitles, value, and values.
Referenced by parseData().
calc_disc_id()
uint32_t Xcddb::calc_disc_id (int nr_of_tracks, toc cdtoc[])
References cddb_sum(), cdtoc, CDDB::toc::min, min, and t.
Referenced by isCDCached().
cddb_sum()
int Xcddb::cddb_sum (int n) protected
Referenced by calc_disc_id().
closeSocket()
bool Xcddb::closeSocket () protected
References m_cddb_socket, and KODI::UTILS::CScopeGuard< Handle, invalid, Deleter >::reset().
Referenced by queryCDinfo(), queryCDinfo(), and ~Xcddb().
GetCacheFile()
std::string Xcddb::GetCacheFile (uint32_t disc_id) const protected
References URIUtils::AddFileToFolder(), and cCacheDir.
Referenced by isCDCached(), isCDCached(), queryCache(), and writeCacheFile().
getDiskArtist()
void Xcddb::getDiskArtist (std::string & strdisk_artist) const
References m_strDisk_artist.
Referenced by CMusicDatabase::DeleteCDDBInfo(), and MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load().
getDiskTitle()
void Xcddb::getDiskTitle (std::string & strdisk_title) const
References m_strDisk_title.
Referenced by CMusicDatabase::DeleteCDDBInfo(), and MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load().
getGenre()
const std::string & Xcddb::getGenre () const
References m_strGenre.
Referenced by MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load().
getInexactArtist()
const std::string & Xcddb::getInexactArtist (int select) const
References m_mapInexact_artist_list, and m_strNull.
Referenced by CMusicDatabase::LookupCDDBInfo().
getInexactCommand()
const std::string & Xcddb::getInexactCommand (int select) const protected
References m_mapInexact_cddb_command_list, and m_strNull.
Referenced by queryCDinfo().
getInexactTitle()
const std::string & Xcddb::getInexactTitle (int select) const
References m_mapInexact_title_list, and m_strNull.
Referenced by CMusicDatabase::LookupCDDBInfo().
getLastError()
int Xcddb::getLastError () const
References m_lastError.
Referenced by getLastErrorText(), and CMusicDatabase::LookupCDDBInfo().
getLastErrorText()
const char * Xcddb::getLastErrorText () const
References E_NETWORK_ERROR_OPEN_SOCKET, E_NETWORK_ERROR_SEND, E_PARAMETER_WRONG, E_TOC_INCORRECT, E_WAIT_FOR_INPUT, and getLastError().
Referenced by CMusicDatabase::LookupCDDBInfo().
getTrackArtist()
const std::string & Xcddb::getTrackArtist (int track) const
References m_mapArtists, and m_strNull.
Referenced by MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load().
getTrackExtended()
const std::string & Xcddb::getTrackExtended (int track) const
References m_mapExtended_track, and m_strNull.
getTrackTitle()
const std::string & Xcddb::getTrackTitle (int track) const
References m_mapTitles, and m_strNull.
Referenced by MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load().
getYear()
const std::string & Xcddb::getYear () const
References m_strYear.
Referenced by MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load().
isCDCached() [1/2]
bool Xcddb::isCDCached (int nr_of_tracks, toc cdtoc[])
References calc_disc_id(), cCacheDir, cdtoc, XFILE::CFile::Exists(), and GetCacheFile().
Referenced by MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load(), and CMusicDatabase::LookupCDDBInfo().
isCDCached() [2/2]
bool Xcddb::isCDCached (MEDIA_DETECT::CCdInfo * pInfo)
References cCacheDir, XFILE::CFile::Exists(), GetCacheFile(), and MEDIA_DETECT::CCdInfo::GetCddbDiscId().
openSocket()
bool Xcddb::openSocket () protected
References KODI::UTILS::CScopeGuard< Handle, invalid, Deleter >::attach(), CDDB_PORT, closesocket, err(), g_charsetConverter, INVALID_SOCKET, CLog::Log(), LOGDEBUG, LOGERROR, m_cddb_ip_address, m_cddb_socket, and SOCKET_ERROR.
Referenced by queryCDinfo().
parseData()
void Xcddb::parseData (const char * buffer) protected
Todo:
STRING_CLEANUP
References addExtended(), addTitle(), g_charsetConverter, m_strDisk_artist, m_strDisk_title, m_strGenre, m_strYear, and TrimToUTF8().
Referenced by queryCache(), queryCDinfo(), and queryCDinfo().
queryCache()
bool Xcddb::queryCache (uint32_t discid)
References cCacheDir, GetCacheFile(), parseData(), and XFILE::CFile::Read().
Referenced by CMusicDatabase::DeleteCDDBInfo(), and queryCDinfo().
queryCDinfo() [1/2]
bool Xcddb::queryCDinfo (MEDIA_DETECT::CCdInfo * pInfo)
References addInexactList(), closeSocket(), E_NETWORK_ERROR_OPEN_SOCKET, E_NETWORK_ERROR_SEND, E_PARAMETER_WRONG, E_TOC_INCORRECT, E_WAIT_FOR_INPUT, CCompileInfo::GetAppName(), MEDIA_DETECT::CCdInfo::GetCddbDiscId(), MEDIA_DETECT::CCdInfo::GetDiscLength(), MEDIA_DETECT::CCdInfo::GetTrackCount(), MEDIA_DETECT::CCdInfo::GetTrackInformation(), CSysInfo::GetVersion(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_lastError, MEDIA_DETECT::TRACKINFO::nFrames, openSocket(), parseData(), queryCache(), Recv(), recv_buffer, Send(), and writeCacheFile().
queryCDinfo() [2/2]
bool Xcddb::queryCDinfo (MEDIA_DETECT::CCdInfo * pInfo, int inexact_list_select)
References closeSocket(), E_NETWORK_ERROR_SEND, E_PARAMETER_WRONG, MEDIA_DETECT::CCdInfo::GetCddbDiscId(), getInexactCommand(), CLog::Log(), LOGERROR, m_lastError, parseData(), Recv(), recv_buffer, Send(), and writeCacheFile().
Referenced by MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load(), and CMusicDatabase::LookupCDDBInfo().
Recv()
std::string Xcddb::Recv (bool wait4point) protected
References CLog::Log(), LOGDEBUG, LOGERROR, m_cddb_socket, SOCKET_ERROR, WSAECONNRESET, and WSAGetLastError.
Referenced by queryCDinfo(), and queryCDinfo().
Send() [1/2]
bool Xcddb::Send (const char * buffer) protected
References Send().
Send() [2/2]
bool Xcddb::Send (const void * buffer, int bytes) protected
References m_cddb_socket.
Referenced by queryCDinfo(), queryCDinfo(), and Send().
setCacheDir()
void Xcddb::setCacheDir (const std::string & pCacheDir)
References cCacheDir.
Referenced by CMusicDatabase::DeleteCDDBInfo(), MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load(), and CMusicDatabase::LookupCDDBInfo().
setCDDBIpAddress()
void Xcddb::setCDDBIpAddress (const std::string & ip_address)
References m_cddb_ip_address.
TrimToUTF8()
std::string Xcddb::TrimToUTF8 (const std::string & untrimmed) protected
Trim and convert some text to UTF8.
Parameters
untrimmedText original text to trim and convert
Returns
a utf8 version of the trimmed text
References g_charsetConverter, and text.
Referenced by parseData().
writeCacheFile()
bool Xcddb::writeCacheFile (const char * pBuffer, uint32_t discid)
References cCacheDir, XFILE::CFile::Close(), and GetCacheFile().
Referenced by queryCDinfo(), and queryCDinfo().
Member Data Documentation
cCacheDir
std::string CDDB::Xcddb::cCacheDir protected
Referenced by GetCacheFile(), isCDCached(), isCDCached(), queryCache(), setCacheDir(), and writeCacheFile().
cdtoc
struct toc CDDB::Xcddb::cdtoc[100] protected
Referenced by calc_disc_id(), and isCDCached().
m_cddb_ip_address
std::string CDDB::Xcddb::m_cddb_ip_address protected
Referenced by openSocket(), and setCDDBIpAddress().
m_cddb_socket
CAutoPtrSocket CDDB::Xcddb::m_cddb_socket protected
Referenced by closeSocket(), openSocket(), Recv(), and Send().
m_lastError
int CDDB::Xcddb::m_lastError protected
Referenced by getLastError(), queryCDinfo(), and queryCDinfo().
m_mapArtists
std::map<int, std::string> CDDB::Xcddb::m_mapArtists protected
Referenced by addTitle(), and getTrackArtist().
m_mapExtended_track
std::map<int, std::string> CDDB::Xcddb::m_mapExtended_track protected
Referenced by addExtended(), and getTrackExtended().
m_mapInexact_artist_list
std::map<int, std::string> CDDB::Xcddb::m_mapInexact_artist_list protected
Referenced by addInexactListLine(), and getInexactArtist().
m_mapInexact_cddb_command_list
std::map<int, std::string> CDDB::Xcddb::m_mapInexact_cddb_command_list protected
Referenced by addInexactListLine(), and getInexactCommand().
m_mapInexact_title_list
std::map<int, std::string> CDDB::Xcddb::m_mapInexact_title_list protected
Referenced by addInexactListLine(), and getInexactTitle().
m_mapTitles
std::map<int, std::string> CDDB::Xcddb::m_mapTitles protected
Referenced by addTitle(), and getTrackTitle().
m_strDisk_artist
std::string CDDB::Xcddb::m_strDisk_artist protected
Referenced by getDiskArtist(), and parseData().
m_strDisk_title
std::string CDDB::Xcddb::m_strDisk_title protected
Referenced by getDiskTitle(), and parseData().
m_strGenre
std::string CDDB::Xcddb::m_strGenre protected
Referenced by getGenre(), and parseData().
m_strNull
std::string CDDB::Xcddb::m_strNull protected
Referenced by getInexactArtist(), getInexactCommand(), getInexactTitle(), getTrackArtist(), getTrackExtended(), and getTrackTitle().
m_strYear
std::string CDDB::Xcddb::m_strYear protected
Referenced by getYear(), and parseData().
recv_buffer
const int CDDB::Xcddb::recv_buffer = 4096 static protected
Referenced by queryCDinfo(), and queryCDinfo().
The documentation for this class was generated from the following files:
cddb.h
cddb.cpp