Kodi Documentation: CDVDAudioCodecAndroidMediaCodec Class Reference
CDVDAudioCodecAndroidMediaCodec Class Reference
#include <DVDAudioCodecAndroidMediaCodec.h>
Public Member Functions
CDVDAudioCodecAndroidMediaCodec (CProcessInfo &processInfo)
~CDVDAudioCodecAndroidMediaCodec () override
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
void Dispose () override
bool AddData (const DemuxPacket &packet) override
void GetData (DVDAudioFrame &frame) override
void Reset () override
AEAudioFormat GetFormat () override
std::string GetName () override
Public Member Functions inherited from CDVDAudioCodec
CDVDAudioCodec (CProcessInfo &processInfo)
virtual ~CDVDAudioCodec ()=default
virtual int GetBitRate ()
virtual bool NeedPassthrough ()
virtual int GetBufferSize ()
virtual enum AVMatrixEncoding GetMatrixEncoding ()
virtual enum AVAudioServiceType GetAudioServiceType ()
virtual int GetProfile ()
Static Public Member Functions
static std::unique_ptr< CDVDAudioCodec > Create (CProcessInfo &processInfo)
static bool Register ()
Protected Member Functions
int GetData (uint8_t **dst)
int GetChannels ()
int GetEncodedChannels ()
CAEChannelInfo GetChannelMap ()
int GetSampleRate ()
int GetEncodedSampleRate ()
enum AEDataFormat GetDataFormat ()
bool ConfigureMediaCodec (void)
void ConfigureOutputFormat (CJNIMediaFormat *mediaformat)
Protected Attributes
CDVDStreamInfo m_hints
std::string m_mime
std::string m_codecname
std::string m_formatname
bool m_opened = false
bool m_codecIsFed = false
int m_samplerate = 0
int m_channels = 0
uint8_t * m_buffer
int m_bufferSize = 0
int m_bufferUsed = 0
AEAudioFormat m_format
double m_currentPts = DVD_NOPTS_VALUE
std::shared_ptr< CJNIMediaCodec > m_codec
CJNIMediaCrypto * m_crypto = nullptr
std::shared_ptr< CDVDAudioCodec > m_decryptCodec
Protected Attributes inherited from CDVDAudioCodec
CProcessInfo & m_processInfo
Constructor & Destructor Documentation
CDVDAudioCodecAndroidMediaCodec()
CDVDAudioCodecAndroidMediaCodec::CDVDAudioCodecAndroidMediaCodec (CProcessInfo & processInfo)
~CDVDAudioCodecAndroidMediaCodec()
CDVDAudioCodecAndroidMediaCodec::~CDVDAudioCodecAndroidMediaCodec () override
References Dispose().
Member Function Documentation
AddData()
bool CDVDAudioCodecAndroidMediaCodec::AddData (const DemuxPacket & packet) override virtual
Implements CDVDAudioCodec.
References DEMUX_CRYPTO_INFO::cipherBytes, DEMUX_CRYPTO_INFO::clearBytes, CDVDStreamInfo::codec, CAEChannelInfo::Count(), DEMUX_CRYPTO_INFO::cryptBlocks, DEMUX_PACKET::cryptoInfo, CAEUtil::DataFormatToBits(), DEMUX_PACKET::demuxerId, DEMUX_PACKET::dispTime, DEMUX_PACKET::dts, DEMUX_PACKET::duration, err(), GetChannelMap(), GetData(), GetDataFormat(), GetSampleRate(), DEMUX_PACKET::iGroupId, index(), int64_t(), DEMUX_PACKET::iSize, DEMUX_PACKET::iStreamId, DEMUX_CRYPTO_INFO::iv, DEMUX_CRYPTO_INFO::kid, CLog::Log(), LOGAUDIO, LOGDEBUG, LOGERROR, AEAudioFormat::m_channelLayout, m_codec, m_codecIsFed, m_crypto, m_currentPts, AEAudioFormat::m_dataFormat, m_decryptCodec, m_format, AEAudioFormat::m_frameSize, m_hints, AEAudioFormat::m_sampleRate, DEMUX_CRYPTO_INFO::mode, DEMUX_CRYPTO_INFO::numSubSamples, DEMUX_PACKET::pData, DEMUX_PACKET::pSideData, DEMUX_PACKET::pts, DEMUX_PACKET::recoveryPoint, and DEMUX_CRYPTO_INFO::skipBlocks.
ConfigureMediaCodec()
bool CDVDAudioCodecAndroidMediaCodec::ConfigureMediaCodec (void) protected
References CDVDStreamInfo::channels, CDVDStreamInfo::codec, ConfigureOutputFormat(), CDVDStreamInfo::extradata, FFmpegExtraData::GetData(), FFmpegExtraData::GetSize(), CLog::Log(), LOGERROR, m_codec, m_crypto, m_decryptCodec, m_hints, m_mime, and CDVDStreamInfo::samplerate.
Referenced by Open().
ConfigureOutputFormat()
void CDVDAudioCodecAndroidMediaCodec::ConfigureOutputFormat (CJNIMediaFormat * mediaformat) protected
References CLog::Log(), LOGDEBUG, m_channels, and m_samplerate.
Referenced by ConfigureMediaCodec(), and GetData().
Create()
std::unique_ptr< CDVDAudioCodec > CDVDAudioCodecAndroidMediaCodec::Create (CProcessInfo & processInfo) static
Referenced by Register().
Dispose()
void CDVDAudioCodecAndroidMediaCodec::Dispose () override virtual
Implements CDVDAudioCodec.
References m_codec, m_crypto, m_decryptCodec, and m_opened.
Referenced by ~CDVDAudioCodecAndroidMediaCodec().
GetChannelMap()
CAEChannelInfo CDVDAudioCodecAndroidMediaCodec::GetChannelMap () protected
References KnownChannels, and m_channels.
Referenced by AddData().
GetChannels()
int CDVDAudioCodecAndroidMediaCodec::GetChannels () inline protected
References m_channels.
GetData() [1/2]
void CDVDAudioCodecAndroidMediaCodec::GetData (DVDAudioFrame & frame) override virtual
Implements CDVDAudioCodec.
References AE_IS_PLANAR, stDVDAudioFrame::audio_service_type, stDVDAudioFrame::bits_per_sample, CLog::CanLogComponent(), CAEChannelInfo::Count(), stDVDAudioFrame::data, CAEUtil::DataFormatToBits(), stDVDAudioFrame::duration, DVD_NOPTS_VALUE, DVD_TIME_BASE, stDVDAudioFrame::format, stDVDAudioFrame::framesize, stDVDAudioFrame::framesOut, CDVDAudioCodec::GetAudioServiceType(), GetData(), CServiceBroker::GetLogging(), CDVDAudioCodec::GetMatrixEncoding(), CDVDAudioCodec::GetProfile(), CLog::Log(), LOGAUDIO, LOGDEBUG, AEAudioFormat::m_channelLayout, m_codecIsFed, m_currentPts, AEAudioFormat::m_dataFormat, m_decryptCodec, m_format, AEAudioFormat::m_sampleRate, stDVDAudioFrame::matrix_encoding, stDVDAudioFrame::nb_frames, stDVDAudioFrame::passthrough, stDVDAudioFrame::planes, stDVDAudioFrame::profile, and stDVDAudioFrame::pts.
Referenced by AddData(), and GetData().
GetData() [2/2]
int CDVDAudioCodecAndroidMediaCodec::GetData (uint8_t ** dst) protected
References ConfigureOutputFormat(), DVD_NOPTS_VALUE, err(), index(), int64_t(), CLog::Log(), LOGAUDIO, LOGDEBUG, LOGERROR, LOGWARNING, m_buffer, m_bufferSize, m_bufferUsed, m_codec, and m_currentPts.
GetDataFormat()
enum AEDataFormat CDVDAudioCodecAndroidMediaCodec::GetDataFormat () inline protected
References AE_FMT_S16NE.
Referenced by AddData().
GetEncodedChannels()
int CDVDAudioCodecAndroidMediaCodec::GetEncodedChannels () inline protected
References m_channels.
GetEncodedSampleRate()
int CDVDAudioCodecAndroidMediaCodec::GetEncodedSampleRate () inline protected
References m_samplerate.
GetFormat()
AEAudioFormat CDVDAudioCodecAndroidMediaCodec::GetFormat () override virtual
Implements CDVDAudioCodec.
References m_decryptCodec, and m_format.
GetName()
std::string CDVDAudioCodecAndroidMediaCodec::GetName () override virtual
Implements CDVDAudioCodec.
References m_decryptCodec, and m_formatname.
GetSampleRate()
int CDVDAudioCodecAndroidMediaCodec::GetSampleRate () inline protected
References m_samplerate.
Referenced by AddData().
Open()
bool CDVDAudioCodecAndroidMediaCodec::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Implements CDVDAudioCodec.
References CDVDStreamInfo::channels, CDVDStreamInfo::codec, CDVDStreamInfo::codec_tag, ConfigureMediaCodec(), CRYPTO_SESSION_SYSTEM_PLAYREADY, CRYPTO_SESSION_SYSTEM_WIDEVINE, CDVDStreamInfo::cryptoSession, DVD_NOPTS_VALUE, CDVDStreamInfo::extradata, CServiceBroker::GetActiveAE(), FFmpegExtraData::GetSize(), IAE::HasStereoAudioChannelCount(), IsDecoderWhitelisted(), IsDownmixDecoder(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_codec, m_codecIsFed, m_crypto, m_currentPts, m_decryptCodec, m_formatname, m_hints, m_mime, m_opened, CDVDAudioCodec::m_processInfo, CDVDStreamInfo::profile, and CAEStreamInfo::STREAM_TYPE_NULL.
Register()
bool CDVDAudioCodecAndroidMediaCodec::Register () static
References Create(), and CDVDFactoryCodec::RegisterHWAudioCodec().
Referenced by CWinSystemAndroid::InitWindowSystem().
Reset()
void CDVDAudioCodecAndroidMediaCodec::Reset () override virtual
Implements CDVDAudioCodec.
References DVD_NOPTS_VALUE, CLog::Log(), LOGERROR, m_codec, m_codecIsFed, m_currentPts, m_decryptCodec, and m_opened.
Member Data Documentation
m_buffer
uint8_t* CDVDAudioCodecAndroidMediaCodec::m_buffer protected
Referenced by GetData().
m_bufferSize
int CDVDAudioCodecAndroidMediaCodec::m_bufferSize = 0 protected
Referenced by GetData().
m_bufferUsed
int CDVDAudioCodecAndroidMediaCodec::m_bufferUsed = 0 protected
Referenced by GetData().
m_channels
int CDVDAudioCodecAndroidMediaCodec::m_channels = 0 protected
Referenced by ConfigureOutputFormat(), GetChannelMap(), GetChannels(), and GetEncodedChannels().
m_codec
std::shared_ptr<CJNIMediaCodec> CDVDAudioCodecAndroidMediaCodec::m_codec protected
Referenced by AddData(), ConfigureMediaCodec(), Dispose(), GetData(), Open(), and Reset().
m_codecIsFed
bool CDVDAudioCodecAndroidMediaCodec::m_codecIsFed = false protected
Referenced by AddData(), GetData(), Open(), and Reset().
m_codecname
std::string CDVDAudioCodecAndroidMediaCodec::m_codecname protected
m_crypto
CJNIMediaCrypto* CDVDAudioCodecAndroidMediaCodec::m_crypto = nullptr protected
Referenced by AddData(), ConfigureMediaCodec(), Dispose(), and Open().
m_currentPts
double CDVDAudioCodecAndroidMediaCodec::m_currentPts = DVD_NOPTS_VALUE protected
Referenced by AddData(), GetData(), GetData(), Open(), and Reset().
m_decryptCodec
std::shared_ptr<CDVDAudioCodec> CDVDAudioCodecAndroidMediaCodec::m_decryptCodec protected
Referenced by AddData(), ConfigureMediaCodec(), Dispose(), GetData(), GetFormat(), GetName(), Open(), and Reset().
m_format
AEAudioFormat CDVDAudioCodecAndroidMediaCodec::m_format protected
Referenced by AddData(), GetData(), and GetFormat().
m_formatname
std::string CDVDAudioCodecAndroidMediaCodec::m_formatname protected
Referenced by GetName(), and Open().
m_hints
CDVDStreamInfo CDVDAudioCodecAndroidMediaCodec::m_hints protected
Referenced by AddData(), ConfigureMediaCodec(), and Open().
m_mime
std::string CDVDAudioCodecAndroidMediaCodec::m_mime protected
Referenced by ConfigureMediaCodec(), and Open().
m_opened
bool CDVDAudioCodecAndroidMediaCodec::m_opened = false protected
Referenced by Dispose(), Open(), and Reset().
m_samplerate
int CDVDAudioCodecAndroidMediaCodec::m_samplerate = 0 protected
Referenced by ConfigureOutputFormat(), GetEncodedSampleRate(), and GetSampleRate().
The documentation for this class was generated from the following files:
DVDAudioCodecAndroidMediaCodec.h
DVDAudioCodecAndroidMediaCodec.cpp