Kodi Documentation: KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard Class Reference
KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard Class Reference abstract
#include <InputProcessorKeyboard.h>
Public Member Functions
virtual void OnKeyboardEnter ()
virtual void OnKeyboardLeave ()
virtual void OnKeyboardEvent (XBMC_Event &event)=0
virtual ~IInputHandlerKeyboard ()=default
Constructor & Destructor Documentation
~IInputHandlerKeyboard()
virtual KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard::~IInputHandlerKeyboard () virtual default
Member Function Documentation
OnKeyboardEnter()
virtual void KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard::OnKeyboardEnter () inline virtual
Reimplemented in KODI::WINDOWING::WAYLAND::CSeatInputProcessing.
Referenced by KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::OnKeyboardEnter().
OnKeyboardEvent()
virtual void KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard::OnKeyboardEvent (XBMC_Event & event) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CSeatInputProcessing.
Referenced by KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::KeyRepeatTimeout(), KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::NotifyKeyComposingEvent(), and KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::SendKey().
OnKeyboardLeave()
virtual void KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard::OnKeyboardLeave () inline virtual
Reimplemented in KODI::WINDOWING::WAYLAND::CSeatInputProcessing.
Referenced by KODI::WINDOWING::WAYLAND::CInputProcessorKeyboard::OnKeyboardLeave().
The documentation for this class was generated from the following file:
InputProcessorKeyboard.h