Kodi Documentation: CPictureScalingAlgorithm Class Reference
CPictureScalingAlgorithm Class Reference
#include <PictureScalingAlgorithm.h>
Classes
struct ScalingAlgorithm
Public Types
enum Algorithm {
NoAlgorithm , FastBilinear , Bilinear , Bicubic ,
Experimental , NearestNeighbor , AveragingArea , Bicublin ,
Gaussian , Sinc , Lanczos , BicubicSpline
}
typedef enum CPictureScalingAlgorithm::Algorithm Algorithm
Static Public Member Functions
static Algorithm FromString (const std::string &scalingAlgorithm)
static std::string ToString (Algorithm scalingAlgorithm)
static int ToSwscale (const std::string &scalingAlgorithm)
static int ToSwscale (Algorithm scalingAlgorithm)
Static Public Attributes
static Algorithm Default = CPictureScalingAlgorithm::Bicubic
Private Types
typedef struct CPictureScalingAlgorithm::ScalingAlgorithm ScalingAlgorithm
typedef std::map< CPictureScalingAlgorithm::Algorithm, CPictureScalingAlgorithm::ScalingAlgorithm > AlgorithmMap
Private Member Functions
CPictureScalingAlgorithm ()
Static Private Attributes
static AlgorithmMap m_algorithms
Member Typedef Documentation
Algorithm
typedef enum CPictureScalingAlgorithm::Algorithm CPictureScalingAlgorithm::Algorithm
AlgorithmMap
typedef std::map<CPictureScalingAlgorithm::Algorithm, CPictureScalingAlgorithm::ScalingAlgorithm> CPictureScalingAlgorithm::AlgorithmMap private
ScalingAlgorithm
typedef struct CPictureScalingAlgorithm::ScalingAlgorithm CPictureScalingAlgorithm::ScalingAlgorithm private
Member Enumeration Documentation
Algorithm
enum CPictureScalingAlgorithm::Algorithm
Enumerator
NoAlgorithm
FastBilinear
Bilinear
Bicubic
Experimental
NearestNeighbor
AveragingArea
Bicublin
Gaussian
Sinc
Lanczos
BicubicSpline
Constructor & Destructor Documentation
CPictureScalingAlgorithm()
CPictureScalingAlgorithm::CPictureScalingAlgorithm () private
Member Function Documentation
FromString()
CPictureScalingAlgorithm::Algorithm CPictureScalingAlgorithm::FromString (const std::string & scalingAlgorithm) static
References m_algorithms, and NoAlgorithm.
Referenced by CHTTPImageTransformationHandler::HandleRequest(), CAdvancedSettings::ParseSettingsFile(), and ToSwscale().
ToString()
std::string CPictureScalingAlgorithm::ToString (Algorithm scalingAlgorithm) static
References m_algorithms.
ToSwscale() [1/2]
int CPictureScalingAlgorithm::ToSwscale (Algorithm scalingAlgorithm) static
References Default, m_algorithms, and ToSwscale().
ToSwscale() [2/2]
int CPictureScalingAlgorithm::ToSwscale (const std::string & scalingAlgorithm) static
References FromString(), and ToSwscale().
Referenced by CPicture::ScaleImage(), ToSwscale(), and ToSwscale().
Member Data Documentation
Default
CPictureScalingAlgorithm::Algorithm CPictureScalingAlgorithm::Default = CPictureScalingAlgorithm::Bicubic static
Referenced by CAdvancedSettings::Initialize(), and ToSwscale().
m_algorithms
CPictureScalingAlgorithm::AlgorithmMap CPictureScalingAlgorithm::m_algorithms static private
Initial value:
= {
  { FastBilinear,     { "fast_bilinear",    SWS_FAST_BILINEAR } },
  { Bilinear,         { "bilinear",         SWS_BILINEAR } },
  { Bicubic,          { "bicubic",          SWS_BICUBIC } },
  { Experimental,     { "experimental",     SWS_X } },
  { NearestNeighbor,  { "nearest_neighbor", SWS_POINT } },
  { AveragingArea,    { "averaging_area",   SWS_AREA } },
  { Bicublin,         { "bicublin",         SWS_BICUBLIN } },
  { Gaussian,         { "gaussian",         SWS_GAUSS } },
  { Sinc,             { "sinc",             SWS_SINC } },
  { Lanczos,          { "lanczos",          SWS_LANCZOS } },
  { BicubicSpline,    { "bicubic_spline",   SWS_SPLINE } },
}
Referenced by FromString(), ToString(), and ToSwscale().
The documentation for this class was generated from the following files:
PictureScalingAlgorithm.h
PictureScalingAlgorithm.cpp