Kodi Documentation: DVDVideoCodecDRMPRIME.cpp File Reference
DVDVideoCodecDRMPRIME.cpp File Reference
#include "DVDVideoCodecDRMPRIME.h"
#include "ServiceBroker.h"
#include "cores/VideoPlayer/Buffers/VideoBufferDMA.h"
#include "cores/VideoPlayer/Buffers/VideoBufferDRMPRIME.h"
#include "cores/VideoPlayer/DVDCodecs/DVDCodecs.h"
#include "cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "settings/lib/Setting.h"
#include "threads/SingleLock.h"
#include "utils/CPUInfo.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include <libavcodec/avcodec.h>
#include <libavutil/error.h>
#include <libavutil/imgutils.h>
#include <libavutil/opt.h>
#include <libavutil/pixdesc.h>
Namespaces
namespace anonymous_namespace{DVDVideoCodecDRMPRIME.cpp}
Functions
static void anonymous_namespace{DVDVideoCodecDRMPRIME.cpp}::ReleaseBuffer (void *opaque, uint8_t *data)
static void anonymous_namespace{DVDVideoCodecDRMPRIME.cpp}::AlignedSize (AVCodecContext *avctx, int &width, int &height)
bool anonymous_namespace{DVDVideoCodecDRMPRIME.cpp}::SupportsDRM ()
static bool IsSupportedHwFormat (const enum AVPixelFormat fmt)
static bool IsSupportedSwFormat (const enum AVPixelFormat fmt)
static const AVCodecHWConfig * FindHWConfig (const AVCodec *codec)
static const AVCodec * FindDecoder (CDVDStreamInfo &hints)
Variables
constexpr const char * anonymous_namespace{DVDVideoCodecDRMPRIME.cpp}::SETTING_VIDEOPLAYER_USEPRIMEDECODERFORHW {"videoplayer.useprimedecoderforhw"}
Function Documentation
FindDecoder()
static const AVCodec * FindDecoder (CDVDStreamInfo & hints) static
References CDVDStreamInfo::codec, CODEC_FORCE_SOFTWARE, CDVDStreamInfo::codecOptions, and FindHWConfig().
Referenced by CDVDVideoCodecDRMPRIME::Open().
FindHWConfig()
static const AVCodecHWConfig * FindHWConfig (const AVCodec * codec) static
References CServiceBroker::GetSettingsComponent(), IsSupportedHwFormat(), and anonymous_namespace{DVDVideoCodecDRMPRIME.cpp}::SETTING_VIDEOPLAYER_USEPRIMEDECODERFORHW.
Referenced by FindDecoder(), and CDVDVideoCodecDRMPRIME::Open().
IsSupportedHwFormat()
static bool IsSupportedHwFormat (const enum AVPixelFormat fmt) static
References CServiceBroker::GetSettingsComponent(), and anonymous_namespace{DVDVideoCodecDRMPRIME.cpp}::SETTING_VIDEOPLAYER_USEPRIMEDECODERFORHW.
Referenced by FindHWConfig(), CDVDVideoCodecDRMPRIME::GetFormat(), CDVDVideoCodecDRMPRIME::GetPicture(), and CDVDVideoCodecDRMPRIME::UpdateProcessInfo().
IsSupportedSwFormat()
static bool IsSupportedSwFormat (const enum AVPixelFormat fmt) static
Referenced by CDVDVideoCodecDRMPRIME::GetBuffer(), and CDVDVideoCodecDRMPRIME::GetFormat().