Kodi Documentation: CDBusMessage Class Reference
CDBusMessage Class Reference
#include <DBusMessage.h>
Public Member Functions
CDBusMessage (const char *destination, const char *object, const char *interface, const char *method)
CDBusMessage (std::string const &destination, std::string const &object, std::string const &interface, std::string const &method)
void AppendObjectPath (const char *object)
template<typename T >
void AppendArgument (const T arg)
void AppendArgument (const char **arrayString, unsigned int length)
template<typename TFirst >
void AppendArguments (const TFirst first)
template<typename TFirst , typename... TArgs>
void AppendArguments (const TFirst first, const TArgs... args)
DBusMessageIter * GetArgumentIter ()
template<typename... TArgs>
bool GetReplyArguments (TArgs *... args)
DBusMessage * SendSystem ()
DBusMessage * SendSession ()
DBusMessage * SendSystem (CDBusError &error)
DBusMessage * SendSession (CDBusError &error)
bool SendAsyncSystem ()
bool SendAsyncSession ()
DBusMessage * Send (DBusBusType type)
DBusMessage * Send (DBusBusType type, CDBusError &error)
DBusMessage * Send (DBusConnection *con, CDBusError &error)
template<>
void AppendArgument (const bool arg)
template<>
void AppendArgument (const bool arg)
Private Member Functions
void AppendWithType (int type, const void *value)
bool SendAsync (DBusBusType type)
void PrepareArgument ()
bool InitializeReplyIter (DBusMessageIter *iter)
bool CheckTypeAndGetValue (DBusMessageIter *iter, int expectType, void *dest)
template<typename TFirst >
bool GetReplyArgumentsWithIter (DBusMessageIter *iter, TFirst *first)
template<typename TFirst , typename... TArgs>
bool GetReplyArgumentsWithIter (DBusMessageIter *iter, TFirst *first, TArgs *... args)
Private Attributes
DBusMessagePtr m_message
DBusMessagePtr m_reply = nullptr
DBusMessageIter m_args
bool m_haveArgs
Constructor & Destructor Documentation
CDBusMessage() [1/2]
CDBusMessage::CDBusMessage (const char * destination, const char * object, const char * interface, const char * method)
References CLog::Log(), LOGDBUS, LOGDEBUG, m_haveArgs, and m_message.
CDBusMessage() [2/2]
CDBusMessage::CDBusMessage (std::string const & destination, std::string const & object, std::string const & interface, std::string const & method)
Member Function Documentation
AppendArgument() [1/4]
template<> void CDBusMessage::AppendArgument (const bool arg)
References AppendWithType().
AppendArgument() [2/4]
template<> void CDBusMessage::AppendArgument (const bool arg)
AppendArgument() [3/4]
void CDBusMessage::AppendArgument (const char ** arrayString, unsigned int length)
References m_args, and PrepareArgument().
AppendArgument() [4/4]
template<typename T > void CDBusMessage::AppendArgument (const T arg) inline
References AppendWithType().
Referenced by AppendArguments(), AppendArguments(), CDBusUtil::GetAll(), CDBusUtil::GetVariant(), CLogindUPowerSyscall::InhibitDelayLock(), CLogindUPowerSyscall::LogindSetPowerState(), CUDiskDevice::Mount(), KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::Uninhibit(), and CUDiskDevice::UnMount().
AppendArguments() [1/2]
template<typename TFirst > void CDBusMessage::AppendArguments (const TFirst first) inline
References AppendArgument().
Referenced by AppendArguments(), and KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::Inhibit().
AppendArguments() [2/2]
template<typename TFirst , typename... TArgs> void CDBusMessage::AppendArguments (const TFirst first, const TArgs... args) inline
References AppendArgument(), and AppendArguments().
AppendObjectPath()
void CDBusMessage::AppendObjectPath (const char * object)
References AppendWithType().
AppendWithType()
void CDBusMessage::AppendWithType (int type, const void * value) private
References m_args, PrepareArgument(), and value.
Referenced by AppendArgument(), AppendArgument(), and AppendObjectPath().
CheckTypeAndGetValue()
bool CDBusMessage::CheckTypeAndGetValue (DBusMessageIter * iter, int expectType, void * dest) private
References CLog::Log(), and LOGDEBUG.
Referenced by GetReplyArgumentsWithIter(), and GetReplyArgumentsWithIter().
GetArgumentIter()
DBusMessageIter * CDBusMessage::GetArgumentIter ()
References m_args, and PrepareArgument().
Referenced by CUDisks2Provider::Filesystem::Mount(), and CUDisks2Provider::Filesystem::Unmount().
GetReplyArguments()
template<typename... TArgs> bool CDBusMessage::GetReplyArguments (TArgs *... args) inline
Retrieve simple arguments from DBus reply message
You MUST use the correct fixed-width integer typedefs (e.g. std::uint16_t) corresponding to the DBus types for the variables or you will get potentially differing behavior between architectures since the DBus argument type detection is based on the width of the type.
Complex arguments (arrays, structs) are not supported.
Returned pointers for strings are only valid until the instance of this class is deleted.
Exceptions
std::logic_error if the message has no reply
Returns
whether all arguments could be retrieved (false on argument type mismatch or when more arguments were to be retrieved than there are in the message)
References GetReplyArgumentsWithIter(), and InitializeReplyIter().
Referenced by KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::Inhibit().
GetReplyArgumentsWithIter() [1/2]
template<typename TFirst > bool CDBusMessage::GetReplyArgumentsWithIter (DBusMessageIter * iter, TFirst * first) inline private
References CheckTypeAndGetValue().
Referenced by GetReplyArguments(), and GetReplyArgumentsWithIter().
GetReplyArgumentsWithIter() [2/2]
template<typename TFirst , typename... TArgs> bool CDBusMessage::GetReplyArgumentsWithIter (DBusMessageIter * iter, TFirst * first, TArgs *... args) inline private
References CheckTypeAndGetValue(), and GetReplyArgumentsWithIter().
InitializeReplyIter()
bool CDBusMessage::InitializeReplyIter (DBusMessageIter * iter) private
References CLog::Log(), LOGWARNING, and m_reply.
Referenced by GetReplyArguments().
PrepareArgument()
void CDBusMessage::PrepareArgument () private
References m_args, m_haveArgs, and m_message.
Referenced by AppendArgument(), AppendWithType(), and GetArgumentIter().
Send() [1/3]
DBusMessage * CDBusMessage::Send (DBusBusType type)
References CDBusConnection::Connect(), CDBusError::Log(), and Send().
Referenced by Send(), Send(), SendSession(), SendSession(), SendSystem(), SendSystem(), and CDBusUtil::TryMethodCall().
Send() [2/3]
DBusMessage * CDBusMessage::Send (DBusBusType type, CDBusError & error)
References CDBusConnection::Connect(), and Send().
Send() [3/3]
DBusMessage * CDBusMessage::Send (DBusConnection * con, CDBusError & error)
References m_message, and m_reply.
SendAsync()
bool CDBusMessage::SendAsync (DBusBusType type) private
References CDBusConnection::Connect(), and m_message.
Referenced by SendAsyncSession(), and SendAsyncSystem().
SendAsyncSession()
bool CDBusMessage::SendAsyncSession ()
References SendAsync().
SendAsyncSystem()
bool CDBusMessage::SendAsyncSystem ()
References SendAsync().
Referenced by CUPowerSyscall::Hibernate(), and CUPowerSyscall::Suspend().
SendSession() [1/2]
DBusMessage * CDBusMessage::SendSession ()
References Send().
Referenced by KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::Inhibit(), KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::IsAvailable(), and KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::Uninhibit().
SendSession() [2/2]
DBusMessage * CDBusMessage::SendSession (CDBusError & error)
References Send().
SendSystem() [1/2]
DBusMessage * CDBusMessage::SendSystem ()
References Send().
Referenced by CLogindUPowerSyscall::CLogindUPowerSyscall(), CConsoleUPowerSyscall::ConsoleKitMethodCall(), CUDisksProvider::EnumerateDisks(), CUPowerSyscall::EnumeratePowerSources(), CDBusUtil::GetAll(), CDBusUtil::GetVariant(), CLogindUPowerSyscall::HasLogind(), CLogindUPowerSyscall::InhibitDelayLock(), CUDisks2Provider::Initialize(), CLogindUPowerSyscall::LogindCheckCapability(), CLogindUPowerSyscall::LogindSetPowerState(), CUDisks2Provider::Filesystem::Mount(), CUDiskDevice::Mount(), CConsoleUPowerSyscall::Powerdown(), CConsoleUPowerSyscall::Reboot(), CUDisks2Provider::Filesystem::Unmount(), CUDiskDevice::UnMount(), and CLogindUPowerSyscall::UpdateBatteryLevel().
SendSystem() [2/2]
DBusMessage * CDBusMessage::SendSystem (CDBusError & error)
References Send().
Member Data Documentation
m_args
DBusMessageIter CDBusMessage::m_args private
Referenced by AppendArgument(), AppendWithType(), GetArgumentIter(), and PrepareArgument().
m_haveArgs
bool CDBusMessage::m_haveArgs private
Referenced by CDBusMessage(), and PrepareArgument().
m_message
DBusMessagePtr CDBusMessage::m_message private
Referenced by CDBusMessage(), PrepareArgument(), Send(), and SendAsync().
m_reply
DBusMessagePtr CDBusMessage::m_reply = nullptr private
Referenced by InitializeReplyIter(), and Send().
The documentation for this class was generated from the following files:
DBusMessage.h
DBusMessage.cpp