Kodi Documentation: CDBusUtil Class Reference
CDBusUtil Class Reference
#include <DBusUtil.h>
Static Public Member Functions
static CVariant GetAll (const char *destination, const char *object, const char *interface)
static CVariant GetVariant (const char *destination, const char *object, const char *interface, const char *property)
static bool TryMethodCall (DBusBusType bus, const char *destination, const char *object, const char *interface, const char *method)
static bool TryMethodCall (DBusBusType bus, std::string const &destination, std::string const &object, std::string const &interface, std::string const &method)
Static Private Member Functions
static CVariant ParseType (DBusMessageIter *itr)
static CVariant ParseVariant (DBusMessageIter *itr)
Member Function Documentation
GetAll()
CVariant CDBusUtil::GetAll (const char * destination, const char * object, const char * interface) static
References CDBusMessage::AppendArgument(), CLog::Log(), LOGERROR, ParseVariant(), CDBusMessage::SendSystem(), and value.
Referenced by CUPowerSource::CUPowerSource(), CUPowerSource::Update(), CUDiskDevice::Update(), and CLogindUPowerSyscall::UpdateBatteryLevel().
GetVariant()
CVariant CDBusUtil::GetVariant (const char * destination, const char * object, const char * interface, const char * property) static
References CDBusMessage::AppendArgument(), CLog::Log(), LOGERROR, ParseVariant(), and CDBusMessage::SendSystem().
Referenced by CUDisks2Provider::Initialize(), CUDisksProvider::Initialize(), CUDiskDevice::Update(), CLogindUPowerSyscall::UpdateBatteryLevel(), and CUPowerSyscall::UpdateCapabilities().
ParseType()
CVariant CDBusUtil::ParseType (DBusMessageIter * itr) static private
References bool(), int64_t(), CVariant::isNull(), ParseType(), value, and CVariant::VariantTypeArray.
Referenced by ParseType(), and ParseVariant().
ParseVariant()
CVariant CDBusUtil::ParseVariant (DBusMessageIter * itr) static private
References ParseType().
Referenced by GetAll(), and GetVariant().
TryMethodCall() [1/2]
bool CDBusUtil::TryMethodCall (DBusBusType bus, const char * destination, const char * object, const char * interface, const char * method) static
Try to call a DBus method and return whether the call succeeded
References CDBusError::Log(), LOGDEBUG, and CDBusMessage::Send().
Referenced by CConsoleUPowerSyscall::HasConsoleKitAndUPower(), CUDisksProvider::HasUDisks(), CUDisks2Provider::HasUDisks2(), CUPowerSyscall::HasUPower(), and TryMethodCall().
TryMethodCall() [2/2]
bool CDBusUtil::TryMethodCall (DBusBusType bus, std::string const & destination, std::string const & object, std::string const & interface, std::string const & method) static
Try to call a DBus method and return whether the call succeeded
References TryMethodCall().
The documentation for this class was generated from the following files:
DBusUtil.h
DBusUtil.cpp