Kodi Documentation: PVR::CPVRGUIActionsPlayback Class Reference
PVR::CPVRGUIActionsPlayback Class Reference
#include <PVRGUIActionsPlayback.h>
Public Member Functions
CPVRGUIActionsPlayback ()
~CPVRGUIActionsPlayback () override=default
bool ResumePlayRecording (const CFileItem &item, bool bFallbackToPlay) const
Resume a previously not completely played recording.
bool PlayRecording (const CFileItem &item, bool bCheckResume) const
Play recording.
bool PlayRecordingFolder (const CFileItem &item, bool bCheckResume) const
Play a recording folder.
bool PlayEpgTag (const CFileItem &item, ContentUtils::PlayMode mode=ContentUtils::PlayMode::CHECK_AUTO_PLAY_NEXT_ITEM) const
Play EPG tag.
bool SwitchToChannel (const CFileItem &item, bool bCheckResume) const
Switch channel.
bool PlayMedia (const CFileItem &item) const
Playback the given file item.
bool SwitchToChannel (PlaybackType type) const
Start playback of the last played channel, and if there is none, play first channel in the current channelgroup.
bool PlayChannelOnStartup () const
Plays the last played channel or the first channel of TV or Radio on startup.
void SeekForward ()
Seek to the start of the next epg event in timeshift buffer, relative to the currently playing event. If there is no next event, seek to the end of the currently playing event (to the 'live' position).
void SeekBackward (unsigned int iThreshold)
Seek to the start of the previous epg event in timeshift buffer, relative to the currently playing event or if there is no previous event or if playback time is greater than given threshold, seek to the start of the playing event.
Public Member Functions inherited from PVR::IPVRComponent
virtual ~IPVRComponent ()=default
Private Member Functions
CPVRGUIActionsPlayback (const CPVRGUIActionsPlayback &)=delete
CPVRGUIActionsPlayback const & operator= (CPVRGUIActionsPlayback const &)=delete
bool CheckResumeRecording (const CFileItem &item) const
Check whether resume play is possible for a given item, display "resume from ..."/"play from start" context menu in case.
void CheckAndSwitchToFullscreen (bool bFullscreen) const
Check "play minimized" settings value and switch to fullscreen if not set.
Private Attributes
CPVRSettings m_settings
Constructor & Destructor Documentation
CPVRGUIActionsPlayback() [1/2]
CPVRGUIActionsPlayback::CPVRGUIActionsPlayback ()
References CSettings::SETTING_LOOKANDFEEL_STARTUPACTION, and CSettings::SETTING_PVRPLAYBACK_SWITCHTOFULLSCREENCHANNELTYPES.
~CPVRGUIActionsPlayback()
PVR::CPVRGUIActionsPlayback::~CPVRGUIActionsPlayback () override default
CPVRGUIActionsPlayback() [2/2]
PVR::CPVRGUIActionsPlayback::CPVRGUIActionsPlayback (const CPVRGUIActionsPlayback &) private delete
Member Function Documentation
CheckAndSwitchToFullscreen()
void CPVRGUIActionsPlayback::CheckAndSwitchToFullscreen (bool bFullscreen) const private
Check "play minimized" settings value and switch to fullscreen if not set.
Parameters
bFullscreen switch to fullscreen or set windowed playback.
References CServiceBroker::GetGUI(), CMediaSettings::GetInstance(), CGUIComponent::GetWindowManager(), GUI_MSG_FULLSCREEN, CGUIWindowManager::SendMessage(), and CMediaSettings::SetMediaStartWindowed().
Referenced by PlayEpgTag(), PlayRecording(), PlayRecordingFolder(), and SwitchToChannel().
CheckResumeRecording()
bool CPVRGUIActionsPlayback::CheckResumeRecording (const CFileItem & item) const private
Check whether resume play is possible for a given item, display "resume from ..."/"play from start" context menu in case.
Parameters
item containing a recording or an epg tag.
Returns
true, to play/resume the item, false otherwise.
References KODI::VIDEO::GUILIB::ACTION_PLAY_FROM_BEGINNING, KODI::VIDEO::GUILIB::ACTION_RESUME, and STARTOFFSET_RESUME.
Referenced by PlayRecording(), and PlayRecordingFolder().
operator=()
CPVRGUIActionsPlayback const & PVR::CPVRGUIActionsPlayback::operator= (CPVRGUIActionsPlayback const &) private delete
PlayChannelOnStartup()
bool CPVRGUIActionsPlayback::PlayChannelOnStartup () const
Plays the last played channel or the first channel of TV or Radio on startup.
Returns
True if playback was started, false otherwise.
References PVR::CPVRManager::ChannelGroups(), PVR::CPVRSettings::GetIntValue(), CServiceBroker::GetPVRManager(), CLog::Log(), LOGINFO, m_settings, PVR::CPVRManager::PlaybackState(), CSettings::SETTING_LOOKANDFEEL_STARTUPACTION, STARTUP_ACTION_PLAY_RADIO, STARTUP_ACTION_PLAY_TV, and SwitchToChannel().
PlayEpgTag()
bool CPVRGUIActionsPlayback::PlayEpgTag (const CFileItem & item, ContentUtils::PlayMode mode = ContentUtils::PlayMode::CHECK_AUTO_PLAY_NEXT_ITEM) const
Play EPG tag.
Parameters
item containing an epg tag.
mode playback mode.
Returns
true on success, false otherwise.
References CheckAndSwitchToFullscreen(), DEFAULT, PVR::CPVRStreamProperties::EPGPlaybackAsLive(), PVR::CPVRManager::Get(), PVR::CPVRManager::GetClient(), CServiceBroker::GetGUI(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), GUI_MSG_FULLSCREEN, LOGERROR, LOGPVR, PVR::CPVRManager::PlaybackState(), PVR_ERROR_NO_ERROR, PVR_SOURCE_EPG_AS_LIVE, CGUIWindowManager::SendMessage(), and PVR::CPVRClient::ToString().
PlayMedia()
bool CPVRGUIActionsPlayback::PlayMedia (const CFileItem & item) const
Playback the given file item.
Parameters
item containing a channel or a recording.
Returns
True if the item could be played, false otherwise.
References CVariant::asBoolean(), PVR::CPVRManager::ChannelGroups(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CServiceBroker::GetPVRManager(), CFileItem::GetStartOffset(), CGUIListItem::HasProperty(), CFileItem::HasPVRChannelInfoTag(), CFileItem::HasPVRRecordingInfoTag(), URIUtils::IsPVRChannel(), URIUtils::IsPVRRecording(), PlayRecording(), PVR::CPVRManager::Recordings(), and SwitchToChannel().
PlayRecording()
bool CPVRGUIActionsPlayback::PlayRecording (const CFileItem & item, bool bCheckResume) const
Play recording.
Parameters
item containing a recording or an epg tag.
bCheckResume controls resume check.
Returns
true on success, false otherwise.
References CVariant::asString(), ContentUtils::CHECK_AUTO_PLAY_NEXT_ITEM, CheckAndSwitchToFullscreen(), CheckResumeRecording(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), KODI::VIDEO::UTILS::GetItemsForPlayList(), URIUtils::GetParentPath(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CServiceBroker::GetPVRManager(), CFileItem::GetStartOffset(), CGUIComponent::GetWindowManager(), GUI_MSG_FULLSCREEN, KODI::VIDEO::UTILS::IsAutoPlayNextItem(), LOGERROR, CGUIListItem::m_bIsFolder, PVR::CPVRManager::PlaybackState(), CGUIWindowManager::SendMessage(), STARTOFFSET_RESUME, and TMSG_MEDIA_PLAY.
Referenced by PlayMedia(), ResumePlayRecording(), and SwitchToChannel().
PlayRecordingFolder()
bool CPVRGUIActionsPlayback::PlayRecordingFolder (const CFileItem & item, bool bCheckResume) const
Play a recording folder.
Parameters
item containing a recording folder.
bCheckResume controls resume check.
Returns
true on success, false otherwise.
References CheckAndSwitchToFullscreen(), CheckResumeRecording(), CServiceBroker::GetAppMessenger(), KODI::VIDEO::UTILS::GetItemsForPlayList(), CGUIListItem::m_bIsFolder, and TMSG_MEDIA_PLAY.
ResumePlayRecording()
bool CPVRGUIActionsPlayback::ResumePlayRecording (const CFileItem & item, bool bFallbackToPlay) const
Resume a previously not completely played recording.
Parameters
item containing a recording or an epg tag.
bFallbackToPlay controls whether playback of the recording should be started at the beginning ig no resume data are available.
Returns
true on success, false otherwise.
References KODI::VIDEO::UTILS::GetItemResumeInformation(), PlayRecording(), and STARTOFFSET_RESUME.
SeekBackward()
void CPVRGUIActionsPlayback::SeekBackward (unsigned int iThreshold)
Seek to the start of the previous epg event in timeshift buffer, relative to the currently playing event or if there is no previous event or if playback time is greater than given threshold, seek to the start of the playing event.
Parameters
iThreshold the value in seconds to trigger seek to start of current event instead of start of previous event.
References CServiceBroker::GetAppMessenger(), CServiceBroker::GetDataCacheCore(), CDataCacheCore::GetMinTime(), CDataCacheCore::GetPlayTime(), CServiceBroker::GetPVRManager(), CDataCacheCore::GetStartTime(), int64_t(), PVR::CPVRManager::PlaybackState(), and TMSG_MEDIA_SEEK_TIME.
SeekForward()
void CPVRGUIActionsPlayback::SeekForward ()
Seek to the start of the next epg event in timeshift buffer, relative to the currently playing event. If there is no next event, seek to the end of the currently playing event (to the 'live' position).
References CServiceBroker::GetAppMessenger(), CServiceBroker::GetDataCacheCore(), CDataCacheCore::GetMaxTime(), CServiceBroker::GetPVRManager(), CDataCacheCore::GetStartTime(), int64_t(), PVR::CPVRManager::PlaybackState(), and TMSG_MEDIA_SEEK_TIME.
SwitchToChannel() [1/2]
bool CPVRGUIActionsPlayback::SwitchToChannel (const CFileItem & item, bool bCheckResume) const
Switch channel.
Parameters
item containing a channel or an epg tag.
bCheckResume controls resume check in case a recording for the current epg event is present.
Returns
true on success, false otherwise.
References ContentUtils::CHECK_AUTO_PLAY_NEXT_ITEM, CheckAndSwitchToFullscreen(), CGUIDialogKaiToast::Error, PVR::FAILED, g_localizeStrings, PVR::CPVRManager::Get(), CLocalizeStrings::Get(), CServiceBroker::GetGUI(), PVR::CPVRSettings::GetIntValue(), CServiceBroker::GetPVRManager(), CGUIComponent::GetWindowManager(), GUI_MSG_FULLSCREEN, CGUIListItem::m_bIsFolder, m_settings, PVR::CPVRManager::PlaybackState(), PlayRecording(), CGUIDialogKaiToast::QueueNotification(), PVR::CPVRManager::Recordings(), CGUIWindowManager::SendMessage(), CSettings::SETTING_PVRPLAYBACK_SWITCHTOFULLSCREENCHANNELTYPES, CGUIDialogYesNo::ShowAndGetInput(), and PVR::SUCCESS.
Referenced by PlayChannelOnStartup(), PlayMedia(), and SwitchToChannel().
SwitchToChannel() [2/2]
bool CPVRGUIActionsPlayback::SwitchToChannel (PlaybackType type) const
Start playback of the last played channel, and if there is none, play first channel in the current channelgroup.
Parameters
type The type of playback to be started (any, radio, tv). See PlaybackType enum
Returns
True if playback was started, false otherwise.
References PVR::CPVRManager::ChannelGroups(), CGUIDialogKaiToast::Error, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetPVRManager(), LOGERROR, PVR::CPVRManager::PlaybackState(), PVR::PlaybackTypeRadio, PVR::PlaybackTypeTV, CGUIDialogKaiToast::QueueNotification(), and SwitchToChannel().
Member Data Documentation
m_settings
CPVRSettings PVR::CPVRGUIActionsPlayback::m_settings private
Referenced by PlayChannelOnStartup(), and SwitchToChannel().
The documentation for this class was generated from the following files:
PVRGUIActionsPlayback.h
PVRGUIActionsPlayback.cpp