Kodi Documentation: ADDON::CAddonInstaller Class Reference
ADDON::CAddonInstaller Class Reference
#include <AddonInstaller.h>
Classes
class CDownloadJob
Public Types
typedef std::map< std::string, CDownloadJob > JobMap
Public Member Functions
bool IsDownloading () const
void GetInstallList (ADDON::VECADDONS &addons) const
bool GetProgress (const std::string &addonID, unsigned int &percent, bool &downloadFinshed) const
bool Cancel (const std::string &addonID)
bool InstallModal (const std::string &addonID, ADDON::AddonPtr &addon, InstallModalPrompt promptForInstall)
Installs the addon while showing a modal progress dialog.
bool InstallOrUpdate (const std::string &addonID, BackgroundJob background, ModalJob modal)
Install an addon if it is available in a repository.
bool InstallOrUpdateDependency (const ADDON::AddonPtr &dependsId, const ADDON::RepositoryPtr &repo)
Install a dependency from a specific repository.
bool RemoveDependency (const std::shared_ptr< IAddon > &dependsId) const
Remove a single dependency from the system.
std::vector< std::string > RemoveOrphanedDepsRecursively () const
Removes all orphaned add-ons recursively. Removal may orphan further add-ons/dependencies, so loop until no orphaned is left on the system.
void InstallAddons (const ADDON::VECADDONS &addons, bool wait, AllowCheckForUpdates allowCheckForUpdates)
Installs a vector of addons.
bool InstallFromZip (const std::string &path)
Install an addon from the given zip path.
bool Install (const std::string &addonId, const ADDON::CAddonVersion &version, const std::string &repoId)
bool UnInstall (const ADDON::AddonPtr &addon, bool removeData)
bool CheckDependencies (const ADDON::AddonPtr &addon, CAddonDatabase *database=nullptr)
Check whether dependencies of an addon exist or are installable. Iterates through the addon's dependencies, checking they're installed or installable. Each dependency must also satisfies CheckDependencies in turn.
bool CheckDependencies (const ADDON::AddonPtr &addon, std::pair< std::string, std::string > &failedDep, CAddonDatabase *database=nullptr)
Check whether dependencies of an addon exist or are installable. Iterates through the addon's dependencies, checking they're installed or installable. Each dependency must also satisfies CheckDependencies in turn.
bool HasJob (const std::string &ID) const
Check if an installation job for a given add-on is already queued up.
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job) override
An optional callback function that a job may call while processing.
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
Static Public Member Functions
static CAddonInstaller & GetInstance ()
Private Member Functions
CAddonInstaller ()
CAddonInstaller (const CAddonInstaller &)=delete
CAddonInstaller const & operator= (CAddonInstaller const &)=delete
~CAddonInstaller () override
bool DoInstall (const ADDON::AddonPtr &addon, const ADDON::RepositoryPtr &repo, BackgroundJob background, ModalJob modal, AutoUpdateJob autoUpdate, DependencyJob dependsInstall, AllowCheckForUpdates allowCheckForUpdates)
Install an addon from a repository or zip.
bool CheckDependencies (const ADDON::AddonPtr &addon, std::vector< std::string > &preDeps, CAddonDatabase &database, std::pair< std::string, std::string > &failedDep)
Check whether dependencies of an addon exist or are installable. Iterates through the addon's dependencies, checking they're installed or installable. Each dependency must also satisfies CheckDependencies in turn.
void PrunePackageCache ()
int64_t EnumeratePackageFolder (std::map< std::string, std::unique_ptr< CFileItemList > > &result)
Private Attributes
CCriticalSection m_critSection
JobMap m_downloadJobs
CEvent m_idle
Member Typedef Documentation
JobMap
typedef std::map<std::string, CDownloadJob> ADDON::CAddonInstaller::JobMap
Constructor & Destructor Documentation
CAddonInstaller() [1/2]
CAddonInstaller::CAddonInstaller () private
CAddonInstaller() [2/2]
ADDON::CAddonInstaller::CAddonInstaller (const CAddonInstaller &) private delete
~CAddonInstaller()
CAddonInstaller::~CAddonInstaller () override private default
Member Function Documentation
Cancel()
bool CAddonInstaller::Cancel (const std::string & addonID)
References CServiceBroker::GetJobManager(), m_critSection, m_downloadJobs, m_idle, and CEvent::Set().
CheckDependencies() [1/3]
bool CAddonInstaller::CheckDependencies (const ADDON::AddonPtr & addon, CAddonDatabase * database = nullptr)
Check whether dependencies of an addon exist or are installable. Iterates through the addon's dependencies, checking they're installed or installable. Each dependency must also satisfies CheckDependencies in turn.
Parameters
addon the addon to check
database the database instance to update. Defaults to NULL.
Returns
true if dependencies are available, false otherwise.
References CheckDependencies().
Referenced by CheckDependencies(), CheckDependencies(), and CheckDependencies().
CheckDependencies() [2/3]
bool CAddonInstaller::CheckDependencies (const ADDON::AddonPtr & addon, std::pair< std::string, std::string > & failedDep, CAddonDatabase * database = nullptr)
Check whether dependencies of an addon exist or are installable. Iterates through the addon's dependencies, checking they're installed or installable. Each dependency must also satisfies CheckDependencies in turn.
Parameters
addon the addon to check
failedDep Dependency addon that isn't available
database the database instance to update. Defaults to NULL.
Returns
true if dependencies are available, false otherwise.
References CheckDependencies().
CheckDependencies() [3/3]
bool CAddonInstaller::CheckDependencies (const ADDON::AddonPtr & addon, std::vector< std::string > & preDeps, CAddonDatabase & database, std::pair< std::string, std::string > & failedDep) private
Check whether dependencies of an addon exist or are installable. Iterates through the addon's dependencies, checking they're installed or installable. Each dependency must also satisfies CheckDependencies in turn.
Parameters
addon the addon to check
preDeps previous dependencies encountered during recursion. aids in avoiding infinite recursion
database database instance to update
failedDep Dependency addon that isn't available
Returns
true if dependencies are available, false otherwise.
Todo:
should we assume that installed deps are OK?
References ADDON::CAddonVersion::asString(), CheckDependencies(), ADDON::CHOICE_NO, CDatabase::Close(), EnableAddon(), ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), CLog::Log(), and LOGDEBUG.
DoInstall()
bool CAddonInstaller::DoInstall (const ADDON::AddonPtr & addon, const ADDON::RepositoryPtr & repo, BackgroundJob background, ModalJob modal, AutoUpdateJob autoUpdate, DependencyJob dependsInstall, AllowCheckForUpdates allowCheckForUpdates) private
Install an addon from a repository or zip.
Parameters
addon the AddonPtr describing the addon
repo the repository to install addon from
background whether to install in the background or not.
modal whether to install in modal mode or not.
autoUpdate whether the addon is installed in auto update mode. (i.e. no notification)
dependsInstall whether this is the installation of a dependency addon
allowCheckForUpdates whether content update check after installation of a repository addon is allowed
Returns
true on successful install, false on failure.
References ADDON::CHOICE_YES, CServiceBroker::GetJobManager(), m_critSection, m_downloadJobs, m_idle, CJob::PRIORITY_DEDICATED, CEvent::Reset(), and CEvent::Set().
Referenced by Install(), InstallAddons(), InstallFromZip(), InstallOrUpdate(), and InstallOrUpdateDependency().
EnumeratePackageFolder()
int64_t CAddonInstaller::EnumeratePackageFolder (std::map< std::string, std::unique_ptr< CFileItemList > > & result) private
References XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::GetDirectory(), int64_t(), CFileItem::m_dwSize, CFileItemList::Size(), and ADDON::CAddonVersion::SplitFileName().
Referenced by PrunePackageCache().
GetInstallList()
void CAddonInstaller::GetInstallList (ADDON::VECADDONS & addons) const
References addons, CServiceBroker::GetAddonMgr(), m_critSection, and m_downloadJobs.
Referenced by XFILE::CAddonsDirectory::GetDirectory().
GetInstance()
CAddonInstaller & CAddonInstaller::GetInstance () static
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::DoWork(), XFILE::CAddonsDirectory::GetDirectory(), KODI::GAME::CGameUtils::Install(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), InstallAddon(), ADDON::CAddonMgr::InstallAddonUpdates(), KODI::GAME::CGameClientProperties::InstallDependencies(), CGUIWindowAddonBrowser::InstallFromZip(), PERIPHERALS::CPeripheralJoystick::InstallSync(), CGUIWindowAddonBrowser::OnClick(), CGUIDialogAddonInfo::OnInstall(), CGUIDialogAddonInfo::OnSelectVersion(), CRssManager::OnSettingAction(), CGUIDialogAddonInfo::OnUninstall(), CGUIDialogAddonInfo::OnUpdate(), KODI::GAME::CControllerInstaller::Process(), XFILE::RootDirectory(), UpdateAddons::Run(), UpdateAllowedAddons::Run(), XFILE::CPluginDirectory::RunScriptWithParams(), CGUIWindowAddonBrowser::SelectAddonID(), XFILE::CPluginDirectory::StartScript(), and CGUIWindowAddonBrowser::UpdateStatus().
GetProgress()
bool CAddonInstaller::GetProgress (const std::string & addonID, unsigned int & percent, bool & downloadFinshed) const
References m_critSection, and m_downloadJobs.
HasJob()
bool CAddonInstaller::HasJob (const std::string & ID) const
Check if an installation job for a given add-on is already queued up.
Parameters
ID The ID of the add-on
Returns
true if a job exists, false otherwise
References ID, m_critSection, and m_downloadJobs.
Install()
bool CAddonInstaller::Install (const std::string & addonId, const ADDON::CAddonVersion & version, const std::string & repoId)
Install an addon with a specific version and repository
References ADDON::CAddonVersion::asString(), ADDON::CHOICE_NO, ADDON::CHOICE_YES, DoInstall(), ADDON::CAddonDatabase::GetAddon(), CServiceBroker::GetAddonMgr(), CLog::Log(), LOGDEBUG, ADDON::CAddonDatabase::Open(), and ADDON::REPOSITORY.
Referenced by CGUIDialogAddonInfo::OnInstall(), CGUIDialogAddonInfo::OnSelectVersion(), and CGUIDialogAddonInfo::OnUpdate().
InstallAddons()
void CAddonInstaller::InstallAddons (const ADDON::VECADDONS & addons, bool wait, AllowCheckForUpdates allowCheckForUpdates)
Installs a vector of addons.
Parameters
addons the list of addons to install
wait if the method should wait for all the DoInstall jobs to finish or if it should return right away
allowCheckForUpdates indicates if content update checks are allowed after installation of a repository addon from the vector
See also
DoInstall
References addons, ADDON::CHOICE_NO, ADDON::CHOICE_YES, DoInstall(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::GetAddon(), m_critSection, m_downloadJobs, m_idle, CEvent::Reset(), and CEvent::Wait().
Referenced by ADDON::CAddonMgr::InstallAddonUpdates().
InstallFromZip()
bool CAddonInstaller::InstallFromZip (const std::string & path)
Install an addon from the given zip path.
Parameters
path the zip file to install from
Returns
true if successful, false otherwise
See also
DoInstall
Bug:
some zip files return a single item (root folder) that we think is stored, so we don't use the zip:// protocol
References CGUIPassword::CheckMenuLock(), ADDON::CHOICE_NO, ADDON::CHOICE_YES, URIUtils::CreateArchivePath(), XFILE::DIR_FLAG_DEFAULTS, DoInstall(), Error, g_localizeStrings, g_passwordManager, CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetEventLog(), CLog::Log(), LOGDEBUG, LOGERROR, CGUIListItem::m_bIsFolder, CFileItemList::Size(), and WINDOW_ADDON_BROWSER.
Referenced by CGUIWindowAddonBrowser::InstallFromZip(), and CGUIDialogAddonInfo::OnSelectVersion().
InstallModal()
bool CAddonInstaller::InstallModal (const std::string & addonID, ADDON::AddonPtr & addon, InstallModalPrompt promptForInstall)
Installs the addon while showing a modal progress dialog.
Parameters
addonID the addon ID of the item to install.
addon [out] the installed addon for later use.
promptForInstall Whether or not to prompt the user before installing the addon.
Returns
true on successful install, false otherwise.
See also
Install
References CGUIPassword::CheckMenuLock(), ADDON::CHOICE_NO, ADDON::CHOICE_YES, g_passwordManager, ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), InstallOrUpdate(), KODI::MESSAGING::HELPERS::ShowYesNoDialogLines(), and WINDOW_ADDON_BROWSER.
Referenced by KODI::GAME::CGameUtils::Install(), InstallAddon(), PERIPHERALS::CPeripheralJoystick::InstallSync(), XFILE::CPluginDirectory::RunScriptWithParams(), CGUIWindowAddonBrowser::SelectAddonID(), and XFILE::CPluginDirectory::StartScript().
InstallOrUpdate()
bool CAddonInstaller::InstallOrUpdate (const std::string & addonID, BackgroundJob background, ModalJob modal)
Install an addon if it is available in a repository.
Parameters
addonID the addon ID of the item to install
background whether to install in the background or not.
modal whether to show a modal dialog when not installing in background
Returns
true on successful install, false on failure.
See also
DoInstall
References ADDON::CHOICE_NO, ADDON::CHOICE_YES, DoInstall(), and anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::GetAddon().
Referenced by KODI::GAME::CGameClientProperties::InstallDependencies(), InstallModal(), KODI::GAME::CControllerInstaller::Process(), UpdateAddons::Run(), and UpdateAllowedAddons::Run().
InstallOrUpdateDependency()
bool CAddonInstaller::InstallOrUpdateDependency (const ADDON::AddonPtr & dependsId, const ADDON::RepositoryPtr & repo)
Install a dependency from a specific repository.
Parameters
dependsId the dependency to install
repo the repository to install the addon from
Returns
true on successful install, false on failure.
See also
DoInstall
References ADDON::CHOICE_NO, ADDON::CHOICE_YES, and DoInstall().
IsDownloading()
bool CAddonInstaller::IsDownloading () const
References m_critSection, and m_downloadJobs.
OnJobComplete()
void CAddonInstaller::OnJobComplete (unsigned int jobID, bool success, CJob * job) override virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE, m_critSection, m_downloadJobs, m_idle, PrunePackageCache(), and CEvent::Set().
OnJobProgress()
void CAddonInstaller::OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob * job) override virtual
An optional callback function that a job may call while processing.
OnJobProgress may be called periodically by a job during it's DoWork() function. It is used by the job to report on progress.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
progress the current progress of the job, out of total.
total the total amount of work to be processed.
job the job that has been processed.
See also
CJobManager and CJob
Reimplemented from IJobCallback.
References CServiceBroker::GetGUI(), CJob::GetType(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_ITEM, m_critSection, m_downloadJobs, CGUIMessage::SetStringParam(), and anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::TYPE_INSTALL.
operator=()
CAddonInstaller const & ADDON::CAddonInstaller::operator= (CAddonInstaller const &) private delete
PrunePackageCache()
void CAddonInstaller::PrunePackageCache () private
References CFileItemList::Add(), CFileItemList::Clear(), CFileUtils::DeleteItem(), EnumeratePackageFolder(), CServiceBroker::GetSettingsComponent(), int64_t(), CFileItem::m_dwSize, ADDON::CAddonDatabase::Open(), ADDON::CAddonDatabase::RemovePackage(), CFileItemList::Size(), CFileItemList::Sort(), SortByDate, SortByLabel, SortBySize, SortOrderAscending, and SortOrderDescending.
Referenced by OnJobComplete().
RemoveDependency()
bool CAddonInstaller::RemoveDependency (const std::shared_ptr< IAddon > & dependsId) const
Remove a single dependency from the system.
Parameters
dependsId the dependency to remove
Returns
true on successful uninstall, false on failure.
References ADDON::CHOICE_NO, and XFILE::CDirectory::Exists().
Referenced by RemoveOrphanedDepsRecursively().
RemoveOrphanedDepsRecursively()
std::vector< std::string > CAddonInstaller::RemoveOrphanedDepsRecursively () const
Removes all orphaned add-ons recursively. Removal may orphan further add-ons/dependencies, so loop until no orphaned is left on the system.
Returns
Names of add-ons that have effectively been removed
References CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetOrphanedDependencies(), CLog::Log(), LOGERROR, and RemoveDependency().
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::DoWork().
UnInstall()
bool CAddonInstaller::UnInstall (const ADDON::AddonPtr & addon, bool removeData)
Uninstall an addon, remove addon data if requested
References CServiceBroker::GetJobManager().
Referenced by CGUIDialogAddonInfo::OnUninstall().
Member Data Documentation
m_critSection
CCriticalSection ADDON::CAddonInstaller::m_critSection mutable private
Referenced by Cancel(), DoInstall(), GetInstallList(), GetProgress(), HasJob(), InstallAddons(), IsDownloading(), OnJobComplete(), and OnJobProgress().
m_downloadJobs
JobMap ADDON::CAddonInstaller::m_downloadJobs private
Referenced by Cancel(), DoInstall(), GetInstallList(), GetProgress(), HasJob(), InstallAddons(), IsDownloading(), OnJobComplete(), and OnJobProgress().
m_idle
CEvent ADDON::CAddonInstaller::m_idle private
Referenced by Cancel(), DoInstall(), InstallAddons(), and OnJobComplete().
The documentation for this class was generated from the following files:
AddonInstaller.h
AddonInstaller.cpp