Kodi Documentation: XBMCAddon::xbmc Namespace Reference
XBMCAddon::xbmc Namespace Reference
Classes
class Actor
class AudioStreamDetail
class InfoTagGame
class InfoTagMusic
class InfoTagPicture
class InfoTagRadioRDS
class InfoTagVideo
class Keyboard
class Monitor
class Player
class PlayList
class RenderCapture
class SubtitleStreamDetail
class VideoStreamDetail
Typedefs
typedef Alternative< String, const PlayList * > PlayParameter
Functions
XBMCCOMMONS_STANDARD_EXCEPTION (KeyboardException)
void log (const char *msg, int level)
void shutdown ()
void restart ()
void executescript (const char *script)
void executebuiltin (const char *function, bool wait)
String executeJSONRPC (const char *jsonrpccommand)
void sleep (long timemillis)
String getLocalizedString (int id)
String getSkinDir ()
String getLanguage (int format, bool region)
String getIPAddress ()
long getDVDState ()
long getFreeMem ()
String getInfoLabel (const char *cLine)
String getInfoImage (const char *infotag)
void playSFX (const char *filename, bool useCached)
void stopSFX ()
void enableNavSounds (bool yesNo)
bool getCondVisibility (const char *condition)
int getGlobalIdleTime ()
String getCacheThumbName (const String &path)
Tuple< String, String > getCleanMovieTitle (const String &path, bool usefoldername)
String getRegion (const char *id)
String getSupportedMedia (const char *mediaType)
bool skinHasImage (const char *image)
bool startServer (int iTyp, bool bStart)
void audioSuspend ()
void audioResume ()
String convertLanguage (const char *language, int format)
String getUserAgent ()
int getSERVER_WEBSERVER ()
int getSERVER_AIRPLAYSERVER ()
int getSERVER_UPNPSERVER ()
int getSERVER_UPNPRENDERER ()
int getSERVER_EVENTSERVER ()
int getSERVER_JSONRPCSERVER ()
int getSERVER_ZEROCONF ()
int getPLAYLIST_MUSIC ()
int getPLAYLIST_VIDEO ()
int getTRAY_OPEN ()
int getDRIVE_NOT_READY ()
int getTRAY_CLOSED_NO_MEDIA ()
int getTRAY_CLOSED_MEDIA_PRESENT ()
int getLOGDEBUG ()
int getLOGINFO ()
int getLOGWARNING ()
int getLOGERROR ()
int getLOGFATAL ()
int getLOGNONE ()
int getISO_639_1 ()
int getISO_639_2 ()
int getENGLISH_NAME ()
XBMCCOMMONS_STANDARD_EXCEPTION (PlayerException)
XBMCCOMMONS_STANDARD_EXCEPTION (PlayListException)
XBMCCOMMONS_STANDARD_EXCEPTION (RenderCaptureException)
Variables
const int lLOGDEBUG = LOGDEBUG
Typedef Documentation
PlayParameter
typedef Alternative<String, const PlayList* > XBMCAddon::xbmc::PlayParameter
Function Documentation
audioResume()
void XBMCAddon::xbmc::audioResume ()
References CServiceBroker::GetActiveAE(), and IAE::Resume().
audioSuspend()
void XBMCAddon::xbmc::audioSuspend ()
References CServiceBroker::GetActiveAE(), and IAE::Suspend().
convertLanguage()
String XBMCAddon::xbmc::convertLanguage (const char * language, int format)
References CLangCodeExpander::ConvertToISO6391(), CLangCodeExpander::ConvertToISO6392B(), CLangCodeExpander::ENGLISH_NAME, g_LangCodeExpander, CLangCodeExpander::ISO_639_1, CLangCodeExpander::ISO_639_2, and CLangCodeExpander::Lookup().
enableNavSounds()
void XBMCAddon::xbmc::enableNavSounds (bool yesNo)
References CGUIAudioManager::Enable(), CGUIComponent::GetAudioManager(), CServiceBroker::GetGUI(), and XBMC_TRACE.
executebuiltin()
void XBMCAddon::xbmc::executebuiltin (const char * function, bool wait)
References CServiceBroker::GetAppMessenger(), CExecString::GetFunction(), CExecString::GetParams(), CExecString::IsValid(), CLog::Log(), LOGWARNING, TMSG_EXECUTE_BUILT_IN, CWindowTranslator::TranslateWindow(), WINDOW_DIALOG_BUSY, and XBMC_TRACE.
executeJSONRPC()
String XBMCAddon::xbmc::executeJSONRPC (const char * jsonrpccommand)
References JSONRPC::CJSONRPC::MethodCall(), and XBMC_TRACE.
executescript()
void XBMCAddon::xbmc::executescript (const char * script)
References CServiceBroker::GetAppMessenger(), TMSG_EXECUTE_SCRIPT, and XBMC_TRACE.
getCacheThumbName()
String XBMCAddon::xbmc::getCacheThumbName (const String & path)
References Crc32::ComputeFromLowerCase(), and XBMC_TRACE.
getCleanMovieTitle()
Tuple< String, String > XBMCAddon::xbmc::getCleanMovieTitle (const String & path, bool usefoldername)
References CUtil::CleanString(), CFileItem::GetMovieName(), and XBMC_TRACE.
getCondVisibility()
bool XBMCAddon::xbmc::getCondVisibility (const char * condition)
References CGUIInfoManager::EvaluateBool(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIComponent::GetWindowManager(), WINDOW_INVALID, and XBMC_TRACE.
getDRIVE_NOT_READY()
int XBMCAddon::xbmc::getDRIVE_NOT_READY ()
References NOT_READY.
getDVDState()
long XBMCAddon::xbmc::getDVDState ()
References CMediaManager::GetDriveStatus(), CServiceBroker::GetMediaManager(), and XBMC_TRACE.
getENGLISH_NAME()
int XBMCAddon::xbmc::getENGLISH_NAME ()
References CLangCodeExpander::ENGLISH_NAME.
getFreeMem()
long XBMCAddon::xbmc::getFreeMem ()
References KODI::MEMORY::MemoryStatus::availPhys, KODI::MEMORY::GetMemoryStatus(), and XBMC_TRACE.
getGlobalIdleTime()
int XBMCAddon::xbmc::getGlobalIdleTime ()
References CServiceBroker::GetAppComponents(), CApplicationPowerHandling::GlobalIdleTime(), and XBMC_TRACE.
getInfoImage()
String XBMCAddon::xbmc::getInfoImage (const char * infotag)
References CServiceBroker::GetGUI(), CGUIInfoManager::GetImage(), CGUIComponent::GetInfoManager(), CGUIInfoManager::TranslateString(), WINDOW_INVALID, and XBMC_TRACE.
getInfoLabel()
String XBMCAddon::xbmc::getInfoLabel (const char * cLine)
References INFO::DEFAULT_CONTEXT, CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), CGUIInfoManager::GetLabel(), CGUIInfoManager::TranslateString(), and XBMC_TRACE.
getIPAddress()
String XBMCAddon::xbmc::getIPAddress ()
References CNetworkInterface::GetCurrentIPAddress(), CNetworkBase::GetFirstConnectedInterface(), CServiceBroker::GetNetwork(), and XBMC_TRACE.
getISO_639_1()
int XBMCAddon::xbmc::getISO_639_1 ()
References CLangCodeExpander::ISO_639_1.
getISO_639_2()
int XBMCAddon::xbmc::getISO_639_2 ()
References CLangCodeExpander::ISO_639_2.
getLanguage()
String XBMCAddon::xbmc::getLanguage (int format, bool region)
References CLangCodeExpander::ConvertToISO6391(), CLangCodeExpander::ConvertToISO6392B(), CLangCodeExpander::ENGLISH_NAME, g_LangCodeExpander, g_langInfo, CLangCodeExpander::ISO_639_1, CLangCodeExpander::ISO_639_2, and XBMC_TRACE.
getLocalizedString()
String XBMCAddon::xbmc::getLocalizedString (int id)
References g_localizeStrings, g_localizeStringsTemp, CLocalizeStrings::Get(), label, and XBMC_TRACE.
getLOGDEBUG()
int XBMCAddon::xbmc::getLOGDEBUG ()
References LOGDEBUG.
getLOGERROR()
int XBMCAddon::xbmc::getLOGERROR ()
References LOGERROR.
getLOGFATAL()
int XBMCAddon::xbmc::getLOGFATAL ()
References LOGFATAL.
getLOGINFO()
int XBMCAddon::xbmc::getLOGINFO ()
References LOGINFO.
getLOGNONE()
int XBMCAddon::xbmc::getLOGNONE ()
References LOGNONE.
getLOGWARNING()
int XBMCAddon::xbmc::getLOGWARNING ()
References LOGWARNING.
getPLAYLIST_MUSIC()
int XBMCAddon::xbmc::getPLAYLIST_MUSIC ()
getPLAYLIST_VIDEO()
int XBMCAddon::xbmc::getPLAYLIST_VIDEO ()
getRegion()
String XBMCAddon::xbmc::getRegion (const char * id)
References CDateTime::CHOICE_YES, g_langInfo, CDateTime::GetAsLocalizedDate(), CDateTime::GetCurrentDateTime(), MeridiemSymbolAM, MeridiemSymbolPM, and XBMC_TRACE.
Referenced by TEST_F().
getSERVER_AIRPLAYSERVER()
int XBMCAddon::xbmc::getSERVER_AIRPLAYSERVER ()
References CNetworkServices::ES_AIRPLAYSERVER.
getSERVER_EVENTSERVER()
int XBMCAddon::xbmc::getSERVER_EVENTSERVER ()
References CNetworkServices::ES_EVENTSERVER.
getSERVER_JSONRPCSERVER()
int XBMCAddon::xbmc::getSERVER_JSONRPCSERVER ()
References CNetworkServices::ES_JSONRPCSERVER.
getSERVER_UPNPRENDERER()
int XBMCAddon::xbmc::getSERVER_UPNPRENDERER ()
References CNetworkServices::ES_UPNPRENDERER.
getSERVER_UPNPSERVER()
int XBMCAddon::xbmc::getSERVER_UPNPSERVER ()
References CNetworkServices::ES_UPNPSERVER.
getSERVER_WEBSERVER()
int XBMCAddon::xbmc::getSERVER_WEBSERVER ()
References CNetworkServices::ES_WEBSERVER.
getSERVER_ZEROCONF()
int XBMCAddon::xbmc::getSERVER_ZEROCONF ()
References CNetworkServices::ES_ZEROCONF.
getSkinDir()
String XBMCAddon::xbmc::getSkinDir ()
References CServiceBroker::GetSettingsComponent(), CSettings::SETTING_LOOKANDFEEL_SKIN, and XBMC_TRACE.
getSupportedMedia()
String XBMCAddon::xbmc::getSupportedMedia (const char * mediaType)
Todo:
Add a mediaType enum
Todo:
implement
References CServiceBroker::GetFileExtensionProvider(), CFileExtensionProvider::GetMusicExtensions(), CFileExtensionProvider::GetPictureExtensions(), CFileExtensionProvider::GetVideoExtensions(), and XBMC_TRACE.
getTRAY_CLOSED_MEDIA_PRESENT()
int XBMCAddon::xbmc::getTRAY_CLOSED_MEDIA_PRESENT ()
References CLOSED_MEDIA_PRESENT.
getTRAY_CLOSED_NO_MEDIA()
int XBMCAddon::xbmc::getTRAY_CLOSED_NO_MEDIA ()
References CLOSED_NO_MEDIA.
getTRAY_OPEN()
int XBMCAddon::xbmc::getTRAY_OPEN ()
References OPEN.
getUserAgent()
String XBMCAddon::xbmc::getUserAgent ()
References CSysInfo::GetUserAgent().
log()
void XBMCAddon::xbmc::log (const char * msg, int level)
References CLog::Log(), LOGDEBUG, and LOGNONE.
playSFX()
void XBMCAddon::xbmc::playSFX (const char * filename, bool useCached)
References CFileUtils::Exists(), CGUIComponent::GetAudioManager(), CServiceBroker::GetGUI(), CGUIAudioManager::PlayPythonSound(), and XBMC_TRACE.
restart()
void XBMCAddon::xbmc::restart ()
References CServiceBroker::GetAppMessenger(), TMSG_RESTART, and XBMC_TRACE.
shutdown()
void XBMCAddon::xbmc::shutdown ()
References CServiceBroker::GetAppMessenger(), TMSG_SHUTDOWN, and XBMC_TRACE.
skinHasImage()
bool XBMCAddon::xbmc::skinHasImage (const char * image)
References CServiceBroker::GetGUI(), CGUIComponent::GetTextureManager(), CGUITextureManager::HasTexture(), and XBMC_TRACE.
sleep()
void XBMCAddon::xbmc::sleep (long timemillis)
References XBMCAddon::DelayedCallGuard::getLanguageHook(), XBMCAddon::LanguageHook::MakePendingCalls(), KODI::TIME::Sleep(), and XBMC_TRACE.
startServer()
bool XBMCAddon::xbmc::startServer (int iTyp, bool bStart)
References CServiceBroker::GetNetwork(), CNetworkBase::GetServices(), CNetworkServices::StartServer(), and XBMC_TRACE.
stopSFX()
void XBMCAddon::xbmc::stopSFX ()
References CGUIComponent::GetAudioManager(), CServiceBroker::GetGUI(), CGUIAudioManager::Stop(), and XBMC_TRACE.
XBMCCOMMONS_STANDARD_EXCEPTION() [1/4]
XBMCAddon::xbmc::XBMCCOMMONS_STANDARD_EXCEPTION (KeyboardException)
XBMCCOMMONS_STANDARD_EXCEPTION() [2/4]
XBMCAddon::xbmc::XBMCCOMMONS_STANDARD_EXCEPTION (PlayerException)
XBMCCOMMONS_STANDARD_EXCEPTION() [3/4]
XBMCAddon::xbmc::XBMCCOMMONS_STANDARD_EXCEPTION (PlayListException)
XBMCCOMMONS_STANDARD_EXCEPTION() [4/4]
XBMCAddon::xbmc::XBMCCOMMONS_STANDARD_EXCEPTION (RenderCaptureException)
Variable Documentation
lLOGDEBUG
const int XBMCAddon::xbmc::lLOGDEBUG = LOGDEBUG