Kodi Documentation: TestAlarmClock.cpp File Reference
TestAlarmClock.cpp File Reference
#include "utils/AlarmClock.h"
#include <gtest/gtest.h>
Functions
TEST (TestAlarmClock, General)
Function Documentation
TEST()
TEST (TestAlarmClock , General)
References EXPECT_EQ(), EXPECT_NE(), EXPECT_TRUE(), CAlarmClock::GetRemaining(), CAlarmClock::HasAlarm(), CAlarmClock::IsRunning(), CAlarmClock::Start(), and CAlarmClock::Stop().