Kodi Documentation: CRendererVAAPIGLES Class Reference
CRendererVAAPIGLES Class Reference
#include <RendererVAAPIGLES.h>
Public Member Functions
CRendererVAAPIGLES ()
~CRendererVAAPIGLES () override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
bool ConfigChanged (const VideoPicture &picture) override
void ReleaseBuffer (int idx) override
bool NeedBuffer (int idx) override
Public Member Functions inherited from CLinuxRendererGLES
CLinuxRendererGLES ()
~CLinuxRendererGLES () override
bool IsConfigured () override
void AddVideoPicture (const VideoPicture &picture, int index) override
void UnInit () override
bool Flush (bool saveBuffers) override
void SetBufferSize (int numBuffers) override
bool IsGuiLayer () override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
void Update () override
bool RenderCapture (int index, CRenderCapture *capture) override
CRenderInfo GetRenderInfo () override
bool SupportsMultiPassRendering () override
bool Supports (ERENDERFEATURE feature) const override
bool Supports (ESCALINGMETHOD method) const override
CRenderCapture * GetRenderCapture () override
Public Member Functions inherited from CBaseRenderer
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool IsPictureHW (const VideoPicture &picture)
virtual bool WantsDoublePass ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
virtual DEBUG_INFO_VIDEO GetDebugInfo (int idx)
Static Public Member Functions
static CBaseRenderer * Create (CVideoBuffer *buffer)
static void Register (VAAPI::IVaapiWinSystem *winSystem, VADisplay vaDpy, EGLDisplay eglDisplay, bool &general, bool &deepColor)
Static Public Member Functions inherited from CLinuxRendererGLES
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Static Public Member Functions inherited from CBaseRenderer
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
bool LoadShadersHook () override
bool RenderHook (int idx) override
void AfterRenderHook (int idx) override
bool UploadTexture (int index) override
void DeleteTexture (int index) override
bool CreateTexture (int index) override
EShaderFormat GetShaderFormat () override
Protected Member Functions inherited from CLinuxRendererGLES
virtual bool Render (unsigned int flags, int index)
virtual void RenderUpdateVideo (bool clear, unsigned int flags=0, unsigned int alpha=255)
int NextYV12Texture ()
virtual bool ValidateRenderTarget ()
virtual void LoadShaders (int field=FIELD_FULL)
virtual void ReleaseShaders ()
void SetTextureFilter (GLenum method)
void UpdateVideoFilter ()
AVColorPrimaries GetSrcPrimaries (AVColorPrimaries srcPrimaries, unsigned int width, unsigned int height)
bool UploadYV12Texture (int index)
void DeleteYV12Texture (int index)
bool CreateYV12Texture (int index)
virtual bool SkipUploadYV12 (int index)
bool UploadNV12Texture (int index)
void DeleteNV12Texture (int index)
bool CreateNV12Texture (int index)
void CalculateTextureSourceRects (int source, int num_planes)
void RenderToFBO (int index, int field)
void RenderFromFBO ()
void RenderSinglePass (int index, int field)
void LoadPlane (CYuvPlane &plane, int type, unsigned width, unsigned height, int stride, int bpp, void *data)
Protected Member Functions inherited from CBaseRenderer
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ManageRenderArea ()
virtual void ReorderDrawPoints ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Protected Attributes
bool m_isVAAPIBuffer = true
std::unique_ptr< VAAPI::CVaapiTexture > m_vaapiTextures [NUM_BUFFERS]
std::array< std::unique_ptr< KODI::UTILS::EGL::CEGLFence >, NUM_BUFFERS > m_fences
Protected Attributes inherited from CLinuxRendererGLES
struct {
CFrameBufferObject fbo
float width {0.0}
float height {0.0}
} m_fbo
int m_iYV12RenderBuffer {0}
int m_NumYV12Buffers {0}
bool m_bConfigured {false}
bool m_bValidated {false}
GLenum m_textureTarget = GL_TEXTURE_2D
int m_renderMethod {RENDER_GLSL}
RenderQuality m_renderQuality {RQ_SINGLEPASS}
int m_currentField {FIELD_FULL}
int m_reloadShaders {0}
CRenderSystemGLES * m_renderSystem {nullptr}
GLenum m_pixelStoreKey {0}
CPictureBuffer m_buffers [NUM_BUFFERS]
Shaders::GLES::BaseYUV2RGBGLSLShader * m_pYUVProgShader {nullptr}
Shaders::GLES::BaseYUV2RGBGLSLShader * m_pYUVBobShader {nullptr}
Shaders::GLES::BaseVideoFilterShader * m_pVideoFilterShader {nullptr}
ESCALINGMETHOD m_scalingMethod {VS_SCALINGMETHOD_LINEAR}
ESCALINGMETHOD m_scalingMethodGui {VS_SCALINGMETHOD_MAX}
bool m_fullRange
AVColorPrimaries m_srcPrimaries
bool m_toneMap = false
ETONEMAPMETHOD m_toneMapMethod = VS_TONEMAPMETHOD_OFF
bool m_passthroughHDR = false
unsigned char * m_planeBuffer = nullptr
size_t m_planeBufferSize = 0
float m_clearColour {0.0f}
CRect m_viewRect
Protected Attributes inherited from CBaseRenderer
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Static Protected Attributes
static VAAPI::IVaapiWinSystem * m_pWinSystem = nullptr
Static Protected Attributes inherited from CLinuxRendererGLES
static const int FIELD_FULL {0}
static const int FIELD_TOP {1}
static const int FIELD_BOT {2}
Constructor & Destructor Documentation
CRendererVAAPIGLES()
CRendererVAAPIGLES::CRendererVAAPIGLES () default
Referenced by Create().
~CRendererVAAPIGLES()
CRendererVAAPIGLES::~CRendererVAAPIGLES () override
References DeleteTexture(), and NUM_BUFFERS.
Member Function Documentation
AfterRenderHook()
void CRendererVAAPIGLES::AfterRenderHook (int idx) override protected virtual
Reimplemented from CLinuxRendererGLES.
References index(), and m_fences.
ConfigChanged()
bool CRendererVAAPIGLES::ConfigChanged (const VideoPicture & picture) override virtual
Reimplemented from CLinuxRendererGLES.
References m_isVAAPIBuffer, VAAPI::CVaapiRenderPicture::procPic, VideoPicture::videoBuffer, and VAAPI::CVaapiProcessedPicture::videoSurface.
Configure()
bool CRendererVAAPIGLES::Configure (const VideoPicture & picture, float fps, unsigned int orientation) override virtual
Reimplemented from CLinuxRendererGLES.
References CLinuxRendererGLES::Configure(), VAAPI::InteropInfo::eglCreateImageKHR, VAAPI::InteropInfo::eglDestroyImageKHR, VAAPI::InteropInfo::eglDisplay, VAAPI::IVaapiWinSystem::GetEGLDisplay(), VAAPI::InteropInfo::glEGLImageTargetTexture2DOES, m_fences, m_isVAAPIBuffer, m_pWinSystem, m_vaapiTextures, VAAPI::CVaapiRenderPicture::procPic, VAAPI::CVaapi2Texture::TestInteropGeneral(), VAAPI::InteropInfo::textureTarget, VAAPI::CVaapiRenderPicture::vadsp, VideoPicture::videoBuffer, and VAAPI::CVaapiProcessedPicture::videoSurface.
Create()
CBaseRenderer * CRendererVAAPIGLES::Create (CVideoBuffer * buffer) static
References CRendererVAAPIGLES().
Referenced by Register().
CreateTexture()
bool CRendererVAAPIGLES::CreateTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGLES.
References CLinuxRendererGLES::CreateNV12Texture(), YuvImage::cshift_x, YuvImage::cshift_y, DeleteTexture(), CLinuxRendererGLES::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGLES::CPictureBuffer::image, index(), CLinuxRendererGLES::m_buffers, m_isVAAPIBuffer, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, YuvImage::MAX_PLANES, and YuvImage::width.
DeleteTexture()
void CRendererVAAPIGLES::DeleteTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGLES.
References CLinuxRendererGLES::DeleteNV12Texture(), CLinuxRendererGLES::FIELD_FULL, CLinuxRendererGLES::CPictureBuffer::fields, CLinuxRendererGLES::CYuvPlane::id, index(), CLinuxRendererGLES::m_buffers, m_isVAAPIBuffer, and ReleaseBuffer().
Referenced by CreateTexture(), and ~CRendererVAAPIGLES().
GetShaderFormat()
EShaderFormat CRendererVAAPIGLES::GetShaderFormat () override protected virtual
Reimplemented from CBaseRenderer.
References m_isVAAPIBuffer, SHADER_NONE, SHADER_NV12, and SHADER_NV12_RRG.
LoadShadersHook()
bool CRendererVAAPIGLES::LoadShadersHook () override protected virtual
Reimplemented from CLinuxRendererGLES.
NeedBuffer()
bool CRendererVAAPIGLES::NeedBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References index(), and m_fences.
Register()
void CRendererVAAPIGLES::Register (VAAPI::IVaapiWinSystem * winSystem, VADisplay vaDpy, EGLDisplay eglDisplay, bool & general, bool & deepColor) static
References Create(), CLog::Log(), LOGDEBUG, m_pWinSystem, VIDEOPLAYER::CRendererFactory::RegisterRenderer(), VAAPI::CVaapi1Texture::TestInterop(), and VAAPI::CVaapi2Texture::TestInterop().
ReleaseBuffer()
void CRendererVAAPIGLES::ReleaseBuffer (int idx) override virtual
Reimplemented from CLinuxRendererGLES.
References index(), m_fences, m_isVAAPIBuffer, m_vaapiTextures, and CLinuxRendererGLES::ReleaseBuffer().
Referenced by DeleteTexture().
RenderHook()
bool CRendererVAAPIGLES::RenderHook (int idx) override protected virtual
Reimplemented from CLinuxRendererGLES.
UploadTexture()
bool CRendererVAAPIGLES::UploadTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGLES.
References CLinuxRendererGLES::CalculateTextureSourceRects(), YuvImage::cshift_x, YuvImage::cshift_y, CLinuxRendererGLES::CPictureBuffer::fields, CLinuxRendererGLES::CPictureBuffer::image, index(), CLinuxRendererGLES::m_buffers, m_isVAAPIBuffer, CLinuxRendererGLES::m_textureTarget, m_vaapiTextures, CLinuxRendererGLES::CYuvPlane::texwidth, CLinuxRendererGLES::UploadNV12Texture(), VAAPI::CVaapiRenderPicture::valid, VerifyGLState, and CLinuxRendererGLES::CPictureBuffer::videoBuffer.
Member Data Documentation
m_fences
std::array<std::unique_ptr<KODI::UTILS::EGL::CEGLFence>, NUM_BUFFERS> CRendererVAAPIGLES::m_fences protected
Referenced by AfterRenderHook(), Configure(), NeedBuffer(), and ReleaseBuffer().
m_isVAAPIBuffer
bool CRendererVAAPIGLES::m_isVAAPIBuffer = true protected
Referenced by ConfigChanged(), Configure(), CreateTexture(), DeleteTexture(), GetShaderFormat(), ReleaseBuffer(), and UploadTexture().
m_pWinSystem
IVaapiWinSystem * CRendererVAAPIGLES::m_pWinSystem = nullptr static protected
Referenced by Configure(), and Register().
m_vaapiTextures
std::unique_ptr<VAAPI::CVaapiTexture> CRendererVAAPIGLES::m_vaapiTextures[NUM_BUFFERS] protected
Referenced by Configure(), ReleaseBuffer(), and UploadTexture().
The documentation for this class was generated from the following files:
RendererVAAPIGLES.h
RendererVAAPIGLES.cpp