Kodi Documentation: KODI::KEYMAP::CJoystickMapper Class Reference
KODI::KEYMAP::CJoystickMapper Class Reference
#include <JoystickMapper.h>
Public Member Functions
CJoystickMapper ()=default
~CJoystickMapper () override=default
void MapActions (int windowID, const tinyxml2::XMLNode *pDevice) override
void Clear () override
std::vector< std::shared_ptr< const KEYMAP::IWindowKeymap > > GetJoystickKeymaps () const
Public Member Functions inherited from KODI::KEYMAP::IKeyMapper
virtual ~IKeyMapper ()=default
Private Types
using ControllerID = std::string
Private Member Functions
void DeserializeJoystickNode (const tinyxml2::XMLNode *pDevice, std::string &controllerId)
bool DeserializeButton (const tinyxml2::XMLElement *pButton, std::string &feature, KODI::JOYSTICK::ANALOG_STICK_DIRECTION &dir, unsigned int &holdtimeMs, std::set< std::string > &hotkeys, std::string &actionStr)
Private Attributes
std::map< ControllerID, std::shared_ptr< IWindowKeymap > > m_joystickKeymaps
std::vector< std::string > m_controllerIds
Member Typedef Documentation
ControllerID
using KODI::KEYMAP::CJoystickMapper::ControllerID = std::string private
Constructor & Destructor Documentation
CJoystickMapper()
KODI::KEYMAP::CJoystickMapper::CJoystickMapper () default
~CJoystickMapper()
KODI::KEYMAP::CJoystickMapper::~CJoystickMapper () override default
Member Function Documentation
Clear()
void CJoystickMapper::Clear () override virtual
Implements KODI::KEYMAP::IKeyMapper.
References m_controllerIds, and m_joystickKeymaps.
DeserializeButton()
bool CJoystickMapper::DeserializeButton (const tinyxml2::XMLElement * pButton, std::string & feature, KODI::JOYSTICK::ANALOG_STICK_DIRECTION & dir, unsigned int & holdtimeMs, std::set< std::string > & hotkeys, std::string & actionStr) private
References JOYSTICK_XML_ATTR_DIRECTION, JOYSTICK_XML_ATTR_HOLDTIME, JOYSTICK_XML_ATTR_HOTKEY, and KODI::JOYSTICK::CJoystickTranslator::TranslateAnalogStickDirection().
Referenced by MapActions().
DeserializeJoystickNode()
void CJoystickMapper::DeserializeJoystickNode (const tinyxml2::XMLNode * pDevice, std::string & controllerId) private
References JOYSTICK_XML_NODE_PROFILE.
Referenced by MapActions().
GetJoystickKeymaps()
std::vector< std::shared_ptr< const IWindowKeymap > > CJoystickMapper::GetJoystickKeymaps () const
References m_controllerIds, and m_joystickKeymaps.
MapActions()
void CJoystickMapper::MapActions (int windowID, const tinyxml2::XMLNode * pDevice) override virtual
Implements KODI::KEYMAP::IKeyMapper.
References ACTION_NONE, DeserializeButton(), DeserializeJoystickNode(), m_controllerIds, m_joystickKeymaps, KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and KODI::ACTION::CActionTranslator::TranslateString().
Member Data Documentation
m_controllerIds
std::vector<std::string> KODI::KEYMAP::CJoystickMapper::m_controllerIds private
Referenced by Clear(), GetJoystickKeymaps(), and MapActions().
m_joystickKeymaps
std::map<ControllerID, std::shared_ptr<IWindowKeymap> > KODI::KEYMAP::CJoystickMapper::m_joystickKeymaps private
Referenced by Clear(), GetJoystickKeymaps(), and MapActions().
The documentation for this class was generated from the following files:
JoystickMapper.h
JoystickMapper.cpp