Kodi Documentation: KODI::GAME::CGameClientStreamVideo Class Reference
KODI::GAME::CGameClientStreamVideo Class Reference
Games
#include <GameClientStreamVideo.h>
Public Member Functions
CGameClientStreamVideo ()=default
~CGameClientStreamVideo () override
bool OpenStream (RETRO::IRetroPlayerStream *stream, const game_stream_properties &properties) override
Open the stream.
void CloseStream () override
Release the RetroPlayer stream resource.
void AddData (const game_stream_packet &packet) override
Add a data packet to a stream.
Public Member Functions inherited from KODI::GAME::IGameClientStream
virtual ~IGameClientStream ()=default
virtual bool GetBuffer (unsigned int width, unsigned int height, game_stream_buffer &buffer)
Get a buffer for zero-copy stream data.
virtual void ReleaseBuffer (game_stream_buffer &buffer)
Free an allocated buffer.
Protected Attributes
RETRO::IRetroPlayerStream * m_stream = nullptr
Static Private Member Functions
static RETRO::VideoStreamProperties * TranslateProperties (const game_stream_video_properties &properties)
Constructor & Destructor Documentation
CGameClientStreamVideo()
KODI::GAME::CGameClientStreamVideo::CGameClientStreamVideo () default
~CGameClientStreamVideo()
KODI::GAME::CGameClientStreamVideo::~CGameClientStreamVideo () inline override
References CloseStream().
Member Function Documentation
AddData()
void CGameClientStreamVideo::AddData (const game_stream_packet & packet) override virtual
Add a data packet to a stream.
Parameters
packet The data packet
Implements KODI::GAME::IGameClientStream.
References KODI::RETRO::IRetroPlayerStream::AddStreamData(), game_stream_video_packet::data, GAME_STREAM_SW_FRAMEBUFFER, GAME_STREAM_VIDEO, game_stream_video_packet::height, m_stream, game_stream_video_packet::rotation, game_stream_video_packet::size, KODI::GAME::CGameClientTranslator::TranslateRotation(), game_stream_packet::type, game_stream_packet::video, and game_stream_video_packet::width.
CloseStream()
void CGameClientStreamVideo::CloseStream () override virtual
Release the RetroPlayer stream resource.
Implements KODI::GAME::IGameClientStream.
References KODI::RETRO::IRetroPlayerStream::CloseStream(), and m_stream.
Referenced by ~CGameClientStreamVideo().
OpenStream()
bool CGameClientStreamVideo::OpenStream (RETRO::IRetroPlayerStream * stream, const game_stream_properties & properties) override virtual
Open the stream.
Parameters
stream The RetroPlayer resource to take ownership of
Returns
True if the stream was opened, false otherwise
Implements KODI::GAME::IGameClientStream.
References CLog::Log(), LOGERROR, m_stream, KODI::RETRO::CRetroPlayerVideo::OpenStream(), TranslateProperties(), and game_stream_properties::video.
TranslateProperties()
RETRO::VideoStreamProperties * CGameClientStreamVideo::TranslateProperties (const game_stream_video_properties & properties) static private
References game_stream_video_properties::aspect_ratio, game_stream_video_properties::format, CLog::Log(), LOGERROR, game_stream_video_properties::max_height, game_stream_video_properties::max_width, game_stream_video_properties::nominal_height, game_stream_video_properties::nominal_width, and KODI::GAME::CGameClientTranslator::TranslatePixelFormat().
Referenced by OpenStream().
Member Data Documentation
m_stream
RETRO::IRetroPlayerStream* KODI::GAME::CGameClientStreamVideo::m_stream = nullptr protected
Referenced by AddData(), CloseStream(), KODI::GAME::CGameClientStreamSwFramebuffer::GetBuffer(), and OpenStream().
The documentation for this class was generated from the following files:
GameClientStreamVideo.h
GameClientStreamVideo.cpp