Kodi Documentation: TestSystemInfo.cpp File Reference
TestSystemInfo.cpp File Reference
#include "GUIInfoManager.h"
#include "ServiceBroker.h"
#include "settings/Settings.h"
#include "utils/CPUInfo.h"
#include "utils/SystemInfo.h"
#include <gtest/gtest.h>
#include "PlatformDefs.h"
Classes
class TestSystemInfo
Functions
TEST_F (TestSystemInfo, Print_System_Info)
TEST_F (TestSystemInfo, GetKernelName)
TEST_F (TestSystemInfo, GetKernelVersionFull)
TEST_F (TestSystemInfo, GetKernelVersion)
TEST_F (TestSystemInfo, GetOsName)
TEST_F (TestSystemInfo, DISABLED_GetOsVersion)
TEST_F (TestSystemInfo, GetOsPrettyNameWithVersion)
TEST_F (TestSystemInfo, GetManufacturerName)
TEST_F (TestSystemInfo, GetModelName)
TEST_F (TestSystemInfo, IsAeroDisabled)
TEST_F (TestSystemInfo, IsWindowsVersion)
TEST_F (TestSystemInfo, IsWindowsVersionAtLeast)
TEST_F (TestSystemInfo, GetWindowsVersion)
TEST_F (TestSystemInfo, GetKernelBitness)
TEST_F (TestSystemInfo, GetKernelCpuFamily)
TEST_F (TestSystemInfo, GetXbmcBitness)
TEST_F (TestSystemInfo, GetUserAgent)
TEST_F (TestSystemInfo, GetBuildTargetPlatformName)
TEST_F (TestSystemInfo, GetBuildTargetPlatformVersion)
TEST_F (TestSystemInfo, GetBuildTargetPlatformVersionDecoded)
TEST_F (TestSystemInfo, GetBuildTargetCpuFamily)
TEST_F (TestSystemInfo, GetUsedCompilerNameAndVer)
TEST_F (TestSystemInfo, GetDiskSpace)
Function Documentation
TEST_F() [1/23]
TEST_F (TestSystemInfo , DISABLED_GetOsVersion)
References EXPECT_EQ(), g_sysinfo, and CSysInfo::GetOsVersion().
TEST_F() [2/23]
TEST_F (TestSystemInfo , GetBuildTargetCpuFamily)
References EXPECT_EQ(), g_sysinfo, CSysInfo::GetBuildTargetCpuFamily(), and CSysInfo::GetKernelCpuFamily().
TEST_F() [3/23]
TEST_F (TestSystemInfo , GetBuildTargetPlatformName)
References EXPECT_EQ(), g_sysinfo, and CSysInfo::GetBuildTargetPlatformName().
TEST_F() [4/23]
TEST_F (TestSystemInfo , GetBuildTargetPlatformVersion)
References EXPECT_EQ(), g_sysinfo, and CSysInfo::GetBuildTargetPlatformVersion().
TEST_F() [5/23]
TEST_F (TestSystemInfo , GetBuildTargetPlatformVersionDecoded)
References EXPECT_EQ(), g_sysinfo, CSysInfo::GetBuildTargetPlatformVersion(), and CSysInfo::GetBuildTargetPlatformVersionDecoded().
TEST_F() [6/23]
TEST_F (TestSystemInfo , GetDiskSpace)
References EXPECT_EQ(), EXPECT_NE(), EXPECT_TRUE(), KODI::PLATFORM::WINDOWS::FromW(), g_sysinfo, and CSysInfo::GetDiskSpace().
TEST_F() [7/23]
TEST_F (TestSystemInfo , GetKernelBitness)
References EXPECT_TRUE(), g_sysinfo, CSysInfo::GetKernelBitness(), and CSysInfo::GetXbmcBitness().
TEST_F() [8/23]
TEST_F (TestSystemInfo , GetKernelCpuFamily)
References EXPECT_EQ(), g_sysinfo, CSysInfo::GetBuildTargetCpuFamily(), and CSysInfo::GetKernelCpuFamily().
TEST_F() [9/23]
TEST_F (TestSystemInfo , GetKernelName)
References EXPECT_EQ(), EXPECT_NE(), g_sysinfo, CSysInfo::GetBuildTargetPlatformName(), and CSysInfo::GetKernelName().
TEST_F() [10/23]
TEST_F (TestSystemInfo , GetKernelVersion)
References EXPECT_EQ(), g_sysinfo, and CSysInfo::GetKernelVersion().
TEST_F() [11/23]
TEST_F (TestSystemInfo , GetKernelVersionFull)
References EXPECT_EQ(), g_sysinfo, and CSysInfo::GetKernelVersionFull().
TEST_F() [12/23]
TEST_F (TestSystemInfo , GetManufacturerName)
References g_sysinfo, and CSysInfo::GetManufacturerName().
TEST_F() [13/23]
TEST_F (TestSystemInfo , GetModelName)
References g_sysinfo, and CSysInfo::GetModelName().
TEST_F() [14/23]
TEST_F (TestSystemInfo , GetOsName)
References EXPECT_EQ(), EXPECT_NE(), g_sysinfo, CSysInfo::GetBuildTargetPlatformName(), and CSysInfo::GetOsName().
TEST_F() [15/23]
TEST_F (TestSystemInfo , GetOsPrettyNameWithVersion)
References EXPECT_EQ(), EXPECT_NE(), g_sysinfo, CSysInfo::GetOsPrettyNameWithVersion(), and CSysInfo::GetOsVersion().
TEST_F() [16/23]
TEST_F (TestSystemInfo , GetUsedCompilerNameAndVer)
References g_sysinfo, and CSysInfo::GetUsedCompilerNameAndVer().
TEST_F() [17/23]
TEST_F (TestSystemInfo , GetUserAgent)
References EXPECT_EQ(), EXPECT_NE(), EXPECT_TRUE(), g_sysinfo, CSysInfo::GetAppName(), and CSysInfo::GetUserAgent().
TEST_F() [18/23]
TEST_F (TestSystemInfo , GetWindowsVersion)
References EXPECT_EQ(), EXPECT_NE(), g_sysinfo, CSysInfo::GetWindowsVersion(), CSysInfo::WindowsVersionFuture, and CSysInfo::WindowsVersionUnknown.
TEST_F() [19/23]
TEST_F (TestSystemInfo , GetXbmcBitness)
References EXPECT_TRUE(), g_sysinfo, CSysInfo::GetKernelBitness(), and CSysInfo::GetXbmcBitness().
TEST_F() [20/23]
TEST_F (TestSystemInfo , IsAeroDisabled)
References g_sysinfo, and CSysInfo::IsAeroDisabled().
TEST_F() [21/23]
TEST_F (TestSystemInfo , IsWindowsVersion)
References g_sysinfo, CSysInfo::IsWindowsVersion(), CSysInfo::WindowsVersionUnknown, and CSysInfo::WindowsVersionWin8_1.
TEST_F() [22/23]
TEST_F (TestSystemInfo , IsWindowsVersionAtLeast)
References g_sysinfo, CSysInfo::IsWindowsVersion(), CSysInfo::IsWindowsVersionAtLeast(), CSysInfo::WindowsVersionFuture, CSysInfo::WindowsVersionUnknown, and CSysInfo::WindowsVersionWin8_1.
TEST_F() [23/23]
TEST_F (TestSystemInfo , Print_System_Info)
References g_sysinfo, CSysInfo::GetBuildTargetCpuFamily(), CSysInfo::GetBuildTargetPlatformName(), CSysInfo::GetBuildTargetPlatformVersion(), CSysInfo::GetBuildTargetPlatformVersionDecoded(), CSysInfo::GetKernelBitness(), CSysInfo::GetKernelCpuFamily(), CSysInfo::GetKernelName(), CSysInfo::GetKernelVersion(), CSysInfo::GetKernelVersionFull(), CSysInfo::GetManufacturerName(), CSysInfo::GetModelName(), CSysInfo::GetOsName(), CSysInfo::GetOsPrettyNameWithVersion(), CSysInfo::GetOsVersion(), CSysInfo::GetUsedCompilerNameAndVer(), CSysInfo::GetUserAgent(), and CSysInfo::GetXbmcBitness().