Kodi Documentation: VideoPlayerCodec Class Reference
VideoPlayerCodec Class Reference
#include <VideoPlayerCodec.h>
Public Member Functions
VideoPlayerCodec ()
~VideoPlayerCodec () override
bool Init (const CFileItem &file, unsigned int filecache) override
bool Seek (int64_t iSeekTime) override
int ReadPCM (uint8_t *pBuffer, size_t size, size_t *actualsize) override
int ReadRaw (uint8_t **pBuffer, int *bufferSize) override
bool CanInit () override
bool CanSeek () override
void DeInit ()
AEAudioFormat GetFormat ()
void SetContentType (const std::string &strContent)
bool NeedConvert (AEDataFormat fmt)
void SetPassthroughStreamType (CAEStreamInfo::DataType streamType)
Public Member Functions inherited from ICodec
ICodec ()
virtual ~ICodec ()=default
virtual void SetTotalTime (int64_t totaltime)
virtual bool IsCaching () const
virtual int GetCacheLevel () const
Private Member Functions
CAEStreamInfo::DataType GetPassthroughStreamType (AVCodecID codecId, int samplerate, int profile)
Private Attributes
CDVDDemux * m_pDemuxer {nullptr}
std::shared_ptr< CDVDInputStream > m_pInputStream
std::unique_ptr< CDVDAudioCodec > m_pAudioCodec
std::string m_strContentType
std::string m_strFileName
int m_nAudioStream {-1}
size_t m_nDecodedLen {0}
bool m_bInited {false}
bool m_bCanSeek {false}
std::unique_ptr< ActiveAE::IAEResample > m_pResampler
DVDAudioFrame m_audioFrame {}
int m_planes {0}
bool m_needConvert {false}
AEAudioFormat m_srcFormat {}
int m_channels {0}
std::unique_ptr< CProcessInfo > m_processInfo
Additional Inherited Members
Public Attributes inherited from ICodec
int64_t m_TotalTime
int m_bitRate
int m_bitsPerSample
int m_bitsPerCodedSample
std::string m_CodecName
MUSIC_INFO::CMusicInfoTag m_tag
XFILE::CFile m_file
AEAudioFormat m_format
Constructor & Destructor Documentation
VideoPlayerCodec()
VideoPlayerCodec::VideoPlayerCodec ()
References ICodec::m_CodecName.
~VideoPlayerCodec()
VideoPlayerCodec::~VideoPlayerCodec () override
References DeInit().
Member Function Documentation
CanInit()
bool VideoPlayerCodec::CanInit () override virtual
Implements ICodec.
CanSeek()
bool VideoPlayerCodec::CanSeek () override virtual
Reimplemented from ICodec.
References m_bCanSeek.
DeInit()
void VideoPlayerCodec::DeInit ()
References AE_FMT_INVALID, m_bInited, ICodec::m_bitRate, ICodec::m_bitsPerSample, m_channels, AEAudioFormat::m_dataFormat, ICodec::m_format, m_nDecodedLen, m_pAudioCodec, m_pDemuxer, m_pInputStream, m_pResampler, m_strFileName, and ICodec::m_TotalTime.
Referenced by Init(), and ~VideoPlayerCodec().
GetFormat()
AEAudioFormat VideoPlayerCodec::GetFormat ()
References m_pAudioCodec.
GetPassthroughStreamType()
CAEStreamInfo::DataType VideoPlayerCodec::GetPassthroughStreamType (AVCodecID codecId, int samplerate, int profile) private
References AE_FMT_RAW, CServiceBroker::GetActiveAE(), AEAudioFormat::m_dataFormat, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, CAEStreamInfo::STREAM_TYPE_NULL, CAEStreamInfo::STREAM_TYPE_TRUEHD, IAE::SupportsRaw(), and IAE::UsesDtsCoreFallback().
Referenced by Init().
Init()
bool VideoPlayerCodec::Init (const CFileItem & file, unsigned int filecache) override virtual
Todo:
convey CFileItem::ContentLookup() into Open()
Implements ICodec.
References AE_CH_LAYOUT_2_0, AE_FMT_FLOAT, AE_IS_PLANAR, AE_QUALITY_UNKNOWN, SampleConfig::bits_per_sample, SampleConfig::channel_layout, SampleConfig::channels, CDVDStreamInfo::codec, CAEChannelInfo::Count(), ActiveAE::CAEResampleFactory::Create(), CDVDFactoryCodec::CreateAudioCodec(), CDVDFactoryDemuxer::CreateDemuxer(), CDVDFactoryInputStream::CreateInputStream(), CAEUtil::DataFormatToBits(), CAEUtil::DataFormatToDitherBits(), CAEUtil::DataFormatToUsedBits(), DeInit(), SampleConfig::dither_bits, SampleConfig::fmt, CAEUtil::GetAVChannelLayout(), CAEUtil::GetAVSampleFormat(), GetPassthroughStreamType(), CDVDDemux::GetStreamCodecName(), CDVDDemux::GetStreamLength(), CDVDDemux::GetStreams(), int64_t(), CTagLoaderTagLib::Load(), CLog::Log(), LOGDEBUG, LOGERROR, m_bCanSeek, m_bInited, ICodec::m_bitRate, ICodec::m_bitsPerCodedSample, ICodec::m_bitsPerSample, AEAudioFormat::m_channelLayout, m_channels, ICodec::m_CodecName, AEAudioFormat::m_dataFormat, ICodec::m_format, AEAudioFormat::m_frameSize, m_nAudioStream, m_nDecodedLen, m_needConvert, m_pAudioCodec, m_pDemuxer, m_pInputStream, m_planes, m_pResampler, m_processInfo, AEAudioFormat::m_sampleRate, m_srcFormat, m_strContentType, m_strFileName, ICodec::m_tag, ICodec::m_TotalTime, NeedConvert(), CDVDStreamInfo::profile, READ_ERROR, ReadPCM(), CDVDDemux::Reset(), SampleConfig::sample_rate, CDVDStreamInfo::samplerate, Seek(), SEEK_POSSIBLE, CFileItem::SetMimeType(), CFileItem::SetMimeTypeForInternetFile(), STREAM_AUDIO, and CDemuxStream::uniqueId.
Referenced by CodecFactory::CreateCodecDemux().
NeedConvert()
bool VideoPlayerCodec::NeedConvert (AEDataFormat fmt)
References AE_FMT_DOUBLE, AE_FMT_FLOAT, AE_FMT_RAW, AE_FMT_S16NE, AE_FMT_S32NE, and AE_FMT_U8.
Referenced by Init().
ReadPCM()
int VideoPlayerCodec::ReadPCM (uint8_t * pBuffer, size_t size, size_t * actualsize) override virtual
Implements ICodec.
References stDVDAudioFrame::data, DEMUX_PACKET::dts, DVD_NOPTS_VALUE, stDVDAudioFrame::framesize, CDVDDemuxUtils::FreeDemuxPacket(), DEMUX_PACKET::iStreamId, m_audioFrame, ICodec::m_bitsPerSample, m_channels, AEAudioFormat::m_frameSize, m_nAudioStream, m_nDecodedLen, m_needConvert, m_pAudioCodec, m_pDemuxer, m_planes, m_pResampler, m_srcFormat, stDVDAudioFrame::nb_frames, DEMUX_PACKET::pts, CDVDDemux::Read(), READ_EOF, READ_ERROR, and READ_SUCCESS.
Referenced by Init().
ReadRaw()
int VideoPlayerCodec::ReadRaw (uint8_t ** pBuffer, int * bufferSize) override virtual
Reimplemented from ICodec.
References stDVDAudioFrame::data, DEMUX_PACKET::dts, DVD_NOPTS_VALUE, CDVDDemuxUtils::FreeDemuxPacket(), DEMUX_PACKET::iStreamId, m_nAudioStream, m_nDecodedLen, m_pAudioCodec, m_pDemuxer, stDVDAudioFrame::nb_frames, DEMUX_PACKET::pts, CDVDDemux::Read(), READ_EOF, READ_ERROR, and READ_SUCCESS.
Seek()
bool VideoPlayerCodec::Seek (int64_t iSeekTime) override virtual
Implements ICodec.
References m_nDecodedLen, m_pAudioCodec, m_pDemuxer, and CDVDDemux::SeekTime().
Referenced by Init().
SetContentType()
void VideoPlayerCodec::SetContentType (const std::string & strContent)
References m_strContentType.
Referenced by CodecFactory::CreateCodecDemux().
SetPassthroughStreamType()
void VideoPlayerCodec::SetPassthroughStreamType (CAEStreamInfo::DataType streamType)
References m_srcFormat, AEAudioFormat::m_streamInfo, and CAEStreamInfo::m_type.
Member Data Documentation
m_audioFrame
DVDAudioFrame VideoPlayerCodec::m_audioFrame {} private
Referenced by ReadPCM().
m_bCanSeek
bool VideoPlayerCodec::m_bCanSeek {false} private
Referenced by CanSeek(), and Init().
m_bInited
bool VideoPlayerCodec::m_bInited {false} private
Referenced by DeInit(), and Init().
m_channels
int VideoPlayerCodec::m_channels {0} private
Referenced by DeInit(), Init(), and ReadPCM().
m_nAudioStream
int VideoPlayerCodec::m_nAudioStream {-1} private
Referenced by Init(), ReadPCM(), and ReadRaw().
m_nDecodedLen
size_t VideoPlayerCodec::m_nDecodedLen {0} private
Referenced by DeInit(), Init(), ReadPCM(), ReadRaw(), and Seek().
m_needConvert
bool VideoPlayerCodec::m_needConvert {false} private
Referenced by Init(), and ReadPCM().
m_pAudioCodec
std::unique_ptr<CDVDAudioCodec> VideoPlayerCodec::m_pAudioCodec private
Referenced by DeInit(), GetFormat(), Init(), ReadPCM(), ReadRaw(), and Seek().
m_pDemuxer
CDVDDemux* VideoPlayerCodec::m_pDemuxer {nullptr} private
Referenced by DeInit(), Init(), ReadPCM(), ReadRaw(), and Seek().
m_pInputStream
std::shared_ptr<CDVDInputStream> VideoPlayerCodec::m_pInputStream private
Referenced by DeInit(), and Init().
m_planes
int VideoPlayerCodec::m_planes {0} private
Referenced by Init(), and ReadPCM().
m_pResampler
std::unique_ptr<ActiveAE::IAEResample> VideoPlayerCodec::m_pResampler private
Referenced by DeInit(), Init(), and ReadPCM().
m_processInfo
std::unique_ptr<CProcessInfo> VideoPlayerCodec::m_processInfo private
Referenced by Init().
m_srcFormat
AEAudioFormat VideoPlayerCodec::m_srcFormat {} private
Referenced by Init(), ReadPCM(), and SetPassthroughStreamType().
m_strContentType
std::string VideoPlayerCodec::m_strContentType private
Referenced by Init(), and SetContentType().
m_strFileName
std::string VideoPlayerCodec::m_strFileName private
Referenced by DeInit(), and Init().
The documentation for this class was generated from the following files:
VideoPlayerCodec.h
VideoPlayerCodec.cpp