Kodi Documentation: CDVDSubtitleParserText Class Reference
CDVDSubtitleParserText Class Reference
#include <DVDSubtitleParser.h>
Public Member Functions
CDVDSubtitleParserText (std::unique_ptr< CDVDSubtitleStream > &&stream, const std::string &filename, const char *name)
~CDVDSubtitleParserText () override=default
const std::string & GetName () const override
Public Member Functions inherited from CDVDSubtitleParserCollection
CDVDSubtitleParserCollection (const std::string &strFile)
~CDVDSubtitleParserCollection () override=default
std::shared_ptr< CDVDOverlay > Parse (double iPts) override
void Reset () override
Public Member Functions inherited from CDVDSubtitleParser
virtual ~CDVDSubtitleParser ()=default
virtual bool Open (CDVDStreamInfo &hints)=0
Protected Member Functions
bool Open ()
Protected Attributes
std::unique_ptr< CDVDSubtitleStream > m_pStream
std::string m_parserName
Protected Attributes inherited from CDVDSubtitleParserCollection
CDVDSubtitleLineCollection m_collection
std::string m_filename
Constructor & Destructor Documentation
CDVDSubtitleParserText()
CDVDSubtitleParserText::CDVDSubtitleParserText (std::unique_ptr< CDVDSubtitleStream > && stream, const std::string & filename, const char * name) inline
~CDVDSubtitleParserText()
CDVDSubtitleParserText::~CDVDSubtitleParserText () override default
Member Function Documentation
GetName()
const std::string & CDVDSubtitleParserText::GetName () const inline override virtual
Implements CDVDSubtitleParser.
References m_parserName.
Open()
bool CDVDSubtitleParserText::Open () inline protected
References CDVDSubtitleParserCollection::m_filename, and m_pStream.
Referenced by CDVDSubtitleParserMicroDVD::Open(), CDVDSubtitleParserMPL2::Open(), CDVDSubtitleParserSami::Open(), CDVDSubtitleParserSSA::Open(), CDVDSubtitleParserSubrip::Open(), CDVDSubtitleParserVplayer::Open(), and CSubtitleParserWebVTT::Open().
Member Data Documentation
m_parserName
std::string CDVDSubtitleParserText::m_parserName protected
Referenced by GetName().
m_pStream
std::unique_ptr<CDVDSubtitleStream> CDVDSubtitleParserText::m_pStream protected
Referenced by Open(), CDVDSubtitleParserMicroDVD::Open(), CDVDSubtitleParserMPL2::Open(), CDVDSubtitleParserSami::Open(), CDVDSubtitleParserSSA::Open(), CDVDSubtitleParserSubrip::Open(), CDVDSubtitleParserVplayer::Open(), and CSubtitleParserWebVTT::Open().
The documentation for this class was generated from the following file:
DVDSubtitleParser.h