Kodi Documentation: CGUIWindow Class Reference
CGUIWindow Class Reference
Guilib classes » Window Reference » Windows and Messages
#include <GUIWindow.h>
Classes
struct icompare
Public Types
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Public Member Functions
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
bool OnAction (const CAction &action) override
virtual bool OnBack (int actionID)
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool OnMessage (CGUIMessage &message) override
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsDialog () const
virtual bool IsDialogRunning () const
virtual bool IsModalDialog () const
virtual bool IsMediaWindow () const
virtual bool HasListItems () const
virtual bool IsSoundEnabled () const
virtual CFileItemPtr GetCurrentListItem (int offset=0)
virtual int GetViewContainerID () const
virtual int GetViewCount () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
virtual void OnDeinitWindow (int nextWindowID)
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual CGUIControl * GetFirstFocusableControl (int id)
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual bool Load (TiXmlElement *pRootElement)
Loads the window from the given XML element.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void SetDefaults ()
virtual void OnWindowUnload ()
virtual void OnWindowLoaded ()
virtual void OnInitWindow ()
Called on window open.
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
virtual void SaveControlStates ()
virtual void RestoreControlStates ()
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Private Attributes
std::map< std::string, CVariant, icompare > m_mapProperties
std::map< INFO::InfoPtr, bool > m_xmlIncludeConditions
used to store conditions used to resolve includes for this window
Additional Inherited Members
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Enumeration Documentation
LOAD_TYPE
enum CGUIWindow::LOAD_TYPE
Enumerator
LOAD_EVERY_TIME
LOAD_ON_GUI_INIT
KEEP_IN_MEMORY
Constructor & Destructor Documentation
CGUIWindow()
CGUIWindow::CGUIWindow (int id, const std::string & xmlFile)
References LOAD_EVERY_TIME, m_active, m_animationsEnabled, m_clearBackground, m_closing, m_custom, m_dynamicResourceAlloc, m_exclusiveMouseControl, m_lastControlID, m_loadType, m_manualRunActions, m_menuControlID, m_menuLastFocusedControlID, m_needsScaling, m_previousWindow, m_renderOrder, m_windowLoaded, RENDER_ORDER_WINDOW, SetID(), SetProperty(), and WINDOW_INVALID.
~CGUIWindow()
CGUIWindow::~CGUIWindow (void) override
Member Function Documentation
AfterRender()
void CGUIWindow::AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
References ANIM_TYPE_WINDOW_CLOSE, Close(), CGUIControlGroup::IsAnimating(), and m_closing.
Referenced by CGUIWindowManager::AfterRender().
AllocResources() [1/2]
void CGUIControlGroup::AllocResources () override virtual
Reimplemented from CGUIControlGroup.
References CGUIControlGroup::m_children, CGUIControlGroup::m_defaultAlways, CGUIControlGroup::m_defaultControl, and CGUIControlGroup::m_renderFocusedLast.
Referenced by CGUIWindowSettingsScreenCalibration::AllocResources(), Initialize(), and OnMessage().
AllocResources() [2/2]
void CGUIWindow::AllocResources (bool forceLoad = false) virtual
Reimplemented in ADDON::CGUIAddonWindow, and CGUIWindowSettingsScreenCalibration.
References CGUIControlGroup::AllocResources(), CVariant::asString(), end(), FreeResources(), GetProperty(), CServiceBroker::GetWinSystem(), Load(), LOAD_EVERY_TIME, CLog::Log(), LOGDEBUG, CGUIControl::m_bAllocated, m_loadType, m_windowLoaded, and NeedLoad().
Referenced by XBMCAddon::xbmcgui::WindowXML::AllocResources().
Animate()
bool CGUIWindow::Animate (unsigned int currentTime) override protected virtual
Reimplemented from CGUIControl.
References CGUIControl::Animate(), m_animationsEnabled, CGUIControl::m_transform, and TransformMatrix::Reset().
CanBeActivated()
virtual bool CGUIWindow::CanBeActivated () const inline virtual
Reimplemented in PVR::CGUIDialogPVRTimerSettings, and PVR::CGUIWindowPVRBase.
CenterWindow()
void CGUIWindow::CenterWindow ()
References CGUIControl::GetHeight(), CGUIControl::GetWidth(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, m_coordsRes, CGUIControl::m_posX, and CGUIControl::m_posY.
Referenced by CGUIDialogContextMenu::PositionAtCurrentFocus().
CheckAnimation()
bool CGUIWindow::CheckAnimation (ANIMATION_TYPE animType) override protected virtual
Reimplemented from CGUIControl.
References ANIM_TYPE_WINDOW_CLOSE, CGUIControl::HasProcessed(), CGUIControl::m_bAllocated, CGUIControlGroup::m_children, and CGUIControl::UpdateVisibility().
ClearAll()
void CGUIWindow::ClearAll () override virtual
Reimplemented from CGUIControlGroup.
References CGUIControlGroup::ClearAll(), m_dynamicResourceAlloc, CGUIControl::m_visibleCondition, m_windowLoaded, and OnWindowUnload().
Referenced by FreeResources().
ClearBackground()
void CGUIWindow::ClearBackground () virtual
Clear the background (if necessary) prior to rendering the window.
Reimplemented in KODI::RETRO::CGameWindowFullScreen, and CGUIWindowFullScreen.
References CGraphicContext::Clear(), color, CWinSystemBase::GetGfxContext(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), m_clearBackground, and KODI::GUILIB::GUIINFO::CGUIInfoColor::Update().
Referenced by KODI::RETRO::CGameWindowFullScreen::ClearBackground().
ClearProperties()
void CGUIWindow::ClearProperties ()
Clear a all the window's properties.
See also
SetProperty, HasProperty, GetProperty
References m_mapProperties.
Referenced by ADDON::Interface_GUIWindow::clear_properties(), XBMCAddon::xbmcgui::Window::clearProperties(), and ADDON::Interface_GUIWindow::destroy().
Close()
void CGUIWindow::Close (bool forceClose = false, int nextWindowID = 0, bool enableSound = true, bool bWait = true)
References Close_Internal(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetWinSystem(), and TMSG_GUI_WINDOW_CLOSE.
Referenced by PVR::CPVRGUIActionsTimers::AnnounceReminder(), CTextureCache::CleanAllUnusedImagesJob(), CVideoDatabase::CleanDatabase(), CMusicDatabase::Cleanup(), XBMCAddon::xbmcgui::DialogProgress::close(), CGUIDialogVideoManager::CloseAll(), CExternalPlayer::CloseFile(), XBMCAddon::xbmcgui::DialogProgress::deallocating(), XBMCAddon::xbmcgui::DialogProgressBG::deallocating(), CPartyModeManager::Enable(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), PVR::CPVRGUIActionsEPG::FindSimilar(), XFILE::CMultiPathDirectory::GetDirectory(), CVideoDatabase::ImportFromXML(), CMusicDatabase::ImportFromXML(), KODI::GAME::CGameClientProperties::InstallDependencies(), CMusicDatabase::LookupCDDBInfo(), CProgressJob::MarkFinished(), XBMCAddon::xbmcgui::WindowDialogMixin::OnAction(), CGUIWindowManager::OnApplicationMessage(), PVR::CGUIWindowPVRGuideBase::OnDeinitWindow(), CGUIDialogVideoOSD::OnMessage(), ADDON::CSkinInfo::OnPostInstall(), CGUIWindowPictures::OnPrepareFileItems(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), CGUIWindowVideoBase::OnSearch(), CGUIDialogVideoInfo::OnSearch(), CPowerManager::OnWake(), CGUIDialogMusicInfo::RefreshInfo(), CVideoDatabase::RemoveContentForPath(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), CGUIDialogAddonSettings::SaveAndClose(), PVR::CGUIDialogPVRChannelManager::SaveList(), CGUIDialogKeyboardGeneric::ShowAndGetInput(), CGUIWindowManager::SwitchToFullScreen(), CGUIWindowFullScreen::ToggleOSD(), CGUIMediaWindow::WaitForNetwork(), CGUIDialogBusy::WaitOnEvent(), and CGUIDialogCache::~CGUIDialogCache().
Close_Internal()
void CGUIWindow::Close_Internal (bool forceClose = false, int nextWindowID = 0, bool enableSound = true) protected
References ANIM_TYPE_WINDOW_CLOSE, CGUIComponent::GetAudioManager(), CServiceBroker::GetGUI(), CGUIControl::GetID(), CServiceBroker::GetWinSystem(), GUI_MSG_WINDOW_DEINIT, CGUIControlGroup::HasAnimation(), IsSoundEnabled(), m_active, m_closing, OnMessage(), CGUIAudioManager::PlayWindowSound(), CGUIControlGroup::QueueAnimation(), SOUND_DEINIT, WINDOW_FULLSCREEN_GAME, and WINDOW_FULLSCREEN_VIDEO.
Referenced by Close().
ControlGroupHasFocus()
bool CGUIWindow::ControlGroupHasFocus (int groupID, int controlID)
References CGUIControlLookup::GetControl(), CGUIControlGroup::GetFirstFocusableControl(), CGUIControl::GetID(), CGUIMessage::GetParam1(), and GUI_MSG_ITEM_SELECTED.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool().
DisableAnimations()
void CGUIWindow::DisableAnimations ()
References m_animationsEnabled.
DoProcess()
void CGUIWindow::DoProcess (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIWindowSettingsScreenCalibration.
References CGraphicContext::AddGUITransform(), CGUIControl::CanFocus(), CGUIControl::DoProcess(), CGUIControlGroup::GetFocusedControl(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), CGUIControl::IsControlDirty(), m_coordsRes, CGUIControlGroup::m_defaultControl, m_needsScaling, CGraphicContext::RemoveTransform(), SET_CONTROL_FOCUS, and CGraphicContext::SetRenderingResolution().
Referenced by CGUIDialog::DoProcess(), CGUIWindowSettingsScreenCalibration::DoProcess(), and CGUIWindowManager::Process().
DoRender()
void CGUIWindow::DoRender () override virtual
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
See also
FrameMove
Reimplemented from CGUIControl.
Reimplemented in CGUIWindowSettingsScreenCalibration.
References CGraphicContext::AddGUITransform(), CGUIControl::DoRender(), CGUIControlProfiler::EndFrame(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CGUIControlProfiler::Instance(), CGUIControlProfiler::IsRunning(), CGUIControl::m_bAllocated, m_coordsRes, m_needsScaling, CGraphicContext::RemoveTransform(), and CGraphicContext::SetRenderingResolution().
Referenced by CGUIWindowSettingsScreenCalibration::DoRender().
DynamicResourceAlloc()
void CGUIWindow::DynamicResourceAlloc (bool bOnOff) override virtual
Reimplemented from CGUIControlGroup.
References CGUIControlGroup::DynamicResourceAlloc(), and m_dynamicResourceAlloc.
Referenced by OnWindowLoaded(), and CGUIWindowPointer::OnWindowLoaded().
FrameMove()
virtual void CGUIWindow::FrameMove () inline virtual
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
Reimplemented in KODI::RETRO::CGameWindowFullScreen, CGUIDialogButtonMenu, CGUIDialogFileBrowser, CGUIDialogKaiToast, CGUIDialogNumeric, CGUIDialogPlayEject, CGUIDialogSeekBar, KODI::GAME::CGUIAgentWindow, KODI::GAME::CDialogGameSaves, KODI::GAME::CDialogGameVideoSelect, KODI::GAME::CGUIPortWindow, CGUIDialogMusicOSD, CGUIWindowMusicNav, CGUIWindowVisualisation, CGUIDialogPictureInfo, CGUIWindowSettingsScreenCalibration, CGUIDialogAudioSettings, CGUIDialogSubtitleSettings, CGUIDialogVideoOSD, CGUIWindowFullScreen, CGUIWindowWeather, CGUIWindowLoginScreen, and CGUIWindowSystemInfo.
Referenced by CGUIWindowManager::FrameMove(), KODI::RETRO::CGameWindowFullScreen::FrameMove(), CGUIDialogButtonMenu::FrameMove(), CGUIDialogFileBrowser::FrameMove(), CGUIDialogKaiToast::FrameMove(), CGUIDialogNumeric::FrameMove(), CGUIDialogPlayEject::FrameMove(), CGUIDialogSeekBar::FrameMove(), KODI::GAME::CGUIAgentWindow::FrameMove(), KODI::GAME::CDialogGameSaves::FrameMove(), KODI::GAME::CDialogGameVideoSelect::FrameMove(), KODI::GAME::CGUIPortWindow::FrameMove(), CGUIDialogMusicOSD::FrameMove(), CGUIWindowMusicNav::FrameMove(), CGUIWindowVisualisation::FrameMove(), CGUIDialogPictureInfo::FrameMove(), CGUIWindowSettingsScreenCalibration::FrameMove(), CGUIDialogAudioSettings::FrameMove(), CGUIDialogSubtitleSettings::FrameMove(), CGUIDialogVideoOSD::FrameMove(), CGUIWindowWeather::FrameMove(), CGUIWindowLoginScreen::FrameMove(), and CGUIWindowSystemInfo::FrameMove().
FreeResources()
void CGUIWindow::FreeResources (bool forceUnLoad = false) override virtual
Reimplemented from CGUIControlGroup.
Reimplemented in CGUIWindowSettingsScreenCalibration.
References ClearAll(), CGUIControlGroup::FreeResources(), LOAD_EVERY_TIME, CGUIControl::m_bAllocated, m_loadType, m_windowXMLRootElement, and m_xmlIncludeConditions.
Referenced by AllocResources(), ADDON::Interface_GUIWindow::destroy(), CGUIWindowManager::DestroyWindow(), CGUIWindowManager::FrameMove(), XBMCAddon::xbmcgui::WindowXML::FreeResources(), CGUIWindowSettingsScreenCalibration::FreeResources(), and OnMessage().
GetCoordsRes()
const RESOLUTION_INFO & CGUIWindow::GetCoordsRes () const inline
References m_coordsRes.
Referenced by XBMCAddon::xbmcgui::Window::getHeight(), XBMCAddon::xbmcgui::Window::getWidth(), CGUIWindowDebugInfo::Process(), and KODI::RETRO::CGUIRenderFullScreen::Render().
GetCurrentListItem()
virtual CFileItemPtr CGUIWindow::GetCurrentListItem (int offset = 0) inline virtual
Reimplemented in CGUIDialogAddonInfo, CGUIDialogFileBrowser, CGUIDialogMusicInfo, CGUIDialogSongInfo, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRGuideInfo, PVR::CGUIDialogPVRRecordingInfo, PVR::CGUIWindowPVRGuideBase, CGUIDialogVideoInfo, CGUIMediaWindow, and CGUIWindowLoginScreen.
Referenced by KODI::GUILIB::GUIINFO::GetCurrentListItemFromWindow().
GetIDRange()
const std::vector< int > & CGUIWindow::GetIDRange () const inline
References m_idRange.
Referenced by CGUIWindowManager::Add().
GetLoadType()
LOAD_TYPE CGUIWindow::GetLoadType () inline
References m_loadType.
GetPosition()
CPoint CGUIWindow::GetPosition () const override protected virtual
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Returns
the window's origin in skin coordinates
Reimplemented from CGUIControl.
References INFO::DEFAULT_CONTEXT, CGUIControl::GetPosition(), and m_origins.
Referenced by GetScaledBounds().
GetPreviousWindow()
int CGUIWindow::GetPreviousWindow () inline
References m_previousWindow.
Referenced by CGUIWindowManager::PreviousWindow().
GetProperty()
CVariant CGUIWindow::GetProperty (const std::string & key) const
Retrieve a property.
Parameters
key name of the property to retrieve
Returns
value of the property, empty if it doesn't exist
References m_mapProperties, and CVariant::VariantTypeNull.
Referenced by CGUIWindowMusicNav::AddSearchFolder(), AllocResources(), ADDON::CGUIAddonWindow::AllocResources(), CGUIMediaWindow::Filter(), ADDON::Interface_GUIWindow::get_property(), ADDON::Interface_GUIWindow::get_property_bool(), ADDON::Interface_GUIWindow::get_property_double(), ADDON::Interface_GUIWindow::get_property_int(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), CGUIWindowAddonBrowser::GetDirectory(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), CWeatherManager::GetLocation(), XBMCAddon::xbmcgui::Window::getProperty(), CGUIDialogSettingsManualBase::InitializeSettings(), CGUIMediaWindow::IsFiltered(), LoadXML(), CGUIWindowMusicNav::OnClick(), OnMessage(), CGUIWindowMusicNav::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowMusicNav::OnSearchUpdate(), CGUIWindowMusicNav::OnWindowLoaded(), CGUIWindowDebugInfo::Process(), CWeatherJob::SetFromProperties(), CGUIMediaWindow::Update(), CGUIMediaWindow::UpdateButtons(), and CGUIWindowWeather::UpdateLocations().
GetRenderOrder()
int CGUIWindow::GetRenderOrder () inline
References m_renderOrder.
Referenced by CGUIDialogTeletext::Render(), and CGUIWindowFullScreen::Render().
GetScaledBounds()
CRect CGUIWindow::GetScaledBounds () const
References CWinSystemBase::GetGfxContext(), GetPosition(), CServiceBroker::GetWinSystem(), m_coordsRes, CGUIControl::m_height, m_needsScaling, CGUIControl::m_width, CGraphicContext::ScaleFinalCoords(), CGraphicContext::SetScalingResolution(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
GetViewContainerID()
virtual int CGUIWindow::GetViewContainerID () const inline virtual
Reimplemented in CGUIDialogFileBrowser, CGUIMediaWindow, and CGUIWindowLoginScreen.
Referenced by anonymous_namespace{ContextMenus.cpp}::SelectNextItem(), and CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::SelectNextItem().
GetViewCount()
virtual int CGUIWindow::GetViewCount () const inline virtual
Reimplemented in CGUIMediaWindow.
HasID()
bool CGUIWindow::HasID (int controlID) const virtual
References m_idRange.
Referenced by OnMessage(), and CGUIDialogSettingsBase::OnMessage().
HasListItems()
virtual bool CGUIWindow::HasListItems () const inline virtual
Reimplemented in CGUIDialogAddonInfo, CGUIDialogFileBrowser, CGUIDialogInfoProviderSettings, CGUIDialogMusicInfo, CGUIDialogSongInfo, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRGuideInfo, PVR::CGUIDialogPVRRecordingInfo, CGUIDialogContentSettings, CGUIDialogLibExportSettings, CGUIDialogVideoInfo, CGUIMediaWindow, and CGUIWindowLoginScreen.
Referenced by KODI::GUILIB::GUIINFO::anonymous_namespace{GUIInfoHelper.cpp}::CheckWindowCondition().
HasSaveLastControl()
bool CGUIWindow::HasSaveLastControl () const inline
References CGUIControlGroup::m_defaultAlways.
Referenced by CApplicationSkinHandling::LoadSkin().
HasVisibleControls()
virtual bool CGUIWindow::HasVisibleControls () inline virtual
Reimplemented in KODI::RETRO::CGameWindowFullScreen, and CGUIWindowFullScreen.
Initialize()
bool CGUIWindow::Initialize ()
References AllocResources(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), CGUIControl::GetID(), GUI_MSG_WINDOW_LOAD, m_windowLoaded, and NeedLoad().
Referenced by CGUIDialogSlider::Display(), CGUIDialogKaiToast::DoWork(), CGUIDialogSmartPlaylistEditor::EditPlaylist(), ADDON::CGUIAddonWindow::GetAddonControl(), CGUIDialogSmartPlaylistEditor::NewPlaylist(), OnMessage(), CGUIDialogFileBrowser::SetHeading(), CGUIDialogNumeric::SetHeading(), CGUIDialogMediaSource::ShowAndAddMediaSource(), CGUIDialogMediaFilter::ShowAndEditMediaFilter(), CGUIDialogMediaSource::ShowAndEditMediaSource(), CGUIDialogContextMenu::ShowAndGetChoice(), CGUIDialogKeyboardGeneric::ShowAndGetInput(), CGUIDialogKeyboardTouch::ShowAndGetInput(), CGUIDialogSlider::ShowAndGetInput(), and CGUIDialogNetworkSetup::ShowAndGetNetworkAddress().
IsActive()
bool CGUIWindow::IsActive () const virtual
References CServiceBroker::GetGUI(), CGUIControl::GetID(), and CGUIComponent::GetWindowManager().
Referenced by CExternalPlayer::CloseFile(), PVR::CGUIWindowPVRSearchBase::ExecuteSearch(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), CGUIWindowEventLog::OnEventAdded(), CGUIWindowEventLog::OnEventRemoved(), CGUIWindowFileManager::OnJobComplete(), CGUIWindowAddonBrowser::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowVisualisation::OnMessage(), PVR::CGUIDialogPVRChannelsOSD::OnMessage(), PVR::CGUIWindowPVRBase::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIWindowSettingsCategory::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIWindowHome::OnMessage(), CGUIDialogAddonSettings::SaveAndClose(), FAVOURITES_UTILS::ShouldEnableMoveItems(), CGUIWindowVideoBase::ShowInfo(), CGUIWindowVideoBase::ShowInfoAndRefresh(), and CGUIWindowWeather::UpdateLocations().
IsAnimating()
bool CGUIWindow::IsAnimating (ANIMATION_TYPE animType) override virtual
Reimplemented from CGUIControlGroup.
References ANIM_TYPE_WINDOW_CLOSE, CGUIControlGroup::IsAnimating(), m_animationsEnabled, and m_closing.
Referenced by CGUIDialogKaiToast::FrameMove(), CGUIDialogProgress::Open(), CGUIDialog::Open_Internal(), CGUIWindowScreensaverDim::Process(), and CGUIWindowSlideShow::Process().
IsCustom()
bool CGUIWindow::IsCustom () const inline
Return if the window is a custom window.
Returns
true if the window is an custom window otherwise false
References m_custom.
IsDialog()
virtual bool CGUIWindow::IsDialog () const inline virtual
Reimplemented in ADDON::CGUIAddonWindowDialog, CGUIDialog, XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, and CGUIWindowSettingsCategory.
Referenced by ADDON::Interface_GUIWindow::close(), anonymous_namespace{GUIBuiltins.cpp}::CloseDialog(), ADDON::Interface_GUIWindow::do_modal(), CGUIWindowManager::Process(), and ADDON::Interface_GUIWindow::show().
IsDialogRunning()
virtual bool CGUIWindow::IsDialogRunning () const inline virtual
Reimplemented in ADDON::CGUIAddonWindowDialog, CGUIDialog, and XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >.
Referenced by CGUIWindowManager::AfterRender(), CGUIWindowManager::MarkDirty(), and CGUIWindowManager::Process().
IsMediaWindow()
virtual bool CGUIWindow::IsMediaWindow () const inline virtual
Reimplemented in ADDON::CGUIAddonWindow, XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, and CGUIMediaWindow.
Referenced by anonymous_namespace{GUIBuiltins.cpp}::ActivateWindow(), KODI::GUILIB::GUIINFO::anonymous_namespace{GUIInfoHelper.cpp}::CheckWindowCondition(), KODI::GUILIB::GUIINFO::GetActiveContainer(), and KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool().
IsModalDialog()
virtual bool CGUIWindow::IsModalDialog () const inline virtual
Reimplemented in ADDON::CGUIAddonWindowDialog, CGUIDialog, and XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >.
Referenced by CGUIWindowManager::SendMessage().
IsSoundEnabled()
virtual bool CGUIWindow::IsSoundEnabled () const inline virtual
Reimplemented in CGUIDialog.
Referenced by Close_Internal(), and OnInitWindow().
IsVisible()
bool CGUIWindow::IsVisible () const inline override virtual
Reimplemented from CGUIControl.
Load() [1/2]
bool CGUIWindow::Load (const std::string & strFileName, bool bContainsPath = false)
References end(), g_SkinInfo, KEEP_IN_MEMORY, LOAD_EVERY_TIME, LOAD_ON_GUI_INIT, LoadXML(), CLog::Log(), LOGDEBUG, LOGINFO, m_coordsRes, m_loadType, m_windowLoaded, and OnWindowLoaded().
Referenced by AllocResources(), CGUIDialog::Load(), CGUIMediaWindow::Load(), and LoadXML().
Load() [2/2]
bool CGUIWindow::Load (TiXmlElement * pRootElement) protected virtual
Loads the window from the given XML element.
Parameters
pRootElement the XML element
Returns
true if the window is loaded from the given XML otherwise false.
Reimplemented in CGUIDialog, and CGUIMediaWindow.
References COrigin::condition, CAnimation::Create(), CGUIControlFactory::GetActions(), CGUIControlFactory::GetConditionalVisibility(), XMLUtils::GetFloat(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CGUIControlFactory::GetHitRect(), CGUIControl::GetID(), CGUIControlFactory::GetInfoColor(), CGUIComponent::GetInfoManager(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, LoadControl(), CGUIControl::m_animations, CGUIControl::m_camera, m_clearBackground, m_coordsRes, CGUIControlGroup::m_defaultAlways, CGUIControlGroup::m_defaultControl, CGUIControl::m_hasCamera, CGUIControl::m_hitRect, m_loadActions, m_menuControlID, m_needsScaling, m_origins, CGUIControl::m_posX, CGUIControl::m_posY, m_previousWindow, m_renderOrder, CGUIControl::m_stereo, m_unloadActions, CGUIControl::m_visibleCondition, CGUIControlFactory::ParsePosition(), CGUIInfoManager::Register(), SetDefaults(), CGraphicContext::SetScalingResolution(), CWindowTranslator::TranslateWindow(), COrigin::x, CPointGen< T >::x, COrigin::y, and CPointGen< T >::y.
LoadControl()
void CGUIWindow::LoadControl (TiXmlElement * pControl, CGUIControlGroup * pGroup, const CRect & rect) protected
References CGUIControlGroup::AddControl(), CGUIControlFactory::Create(), CGUIControl::GetHeight(), CGUIControl::GetID(), CGUIControl::GetWidth(), CGUIControl::GetXPosition(), CGUIControl::GetYPosition(), CGUIControl::IsGroup(), LoadControl(), CGUIControl::m_height, and CGUIControl::m_width.
Referenced by Load(), and LoadControl().
LoadXML()
bool CGUIWindow::LoadXML (const std::string & strPath, const std::string & strLowerPath) protected virtual
Load the window XML from the given path.
Parameters
strPath the path to the window XML
strLowerPath a lowered path to the window XML
References GetProperty(), Load(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGDEBUG, LOGERROR, m_windowXMLRootElement, Prepare(), SetID(), and WINDOW_INVALID.
Referenced by Load(), XBMCAddon::xbmcgui::WindowXMLInterceptor::LoadXML(), and XBMCAddon::xbmcgui::WindowXML::LoadXML().
NeedLoad()
bool CGUIWindow::NeedLoad () const protected
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
References CGUIInfoManager::ConditionsChangedValues(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), m_windowLoaded, and m_xmlIncludeConditions.
Referenced by AllocResources(), and Initialize().
OnAction()
bool CGUIWindow::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControlGroup.
Reimplemented in CGUIWindowFavourites, XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, CGUIWindowMusicBase, CGUIWindowMusicNav, CGUIWindowMusicPlayList, CGUIWindowMusicPlaylistEditor, CGUIWindowVisualisation, CGUIWindowSlideShow, PVR::CGUIWindowPVRBase, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRProvidersBase, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, PVR::CGUIWindowPVRTimersBase, CGUIWindowSettingsCategory, CGUIWindowSettingsScreenCalibration, CGUIWindowFullScreen, CGUIWindowVideoBase, CGUIWindowVideoNav, CGUIWindowVideoPlaylist, CGUIWindowFileManager, CGUIWindowHome, CGUIWindowLoginScreen, CGUIWindowScreensaver, CGUIWindowSplash, and CGUIWindowStartup.
References ACTION_MENU, ACTION_NAV_BACK, ACTION_PREVIOUS_MENU, ACTION_SHOW_INFO, EVENT_RESULT_UNHANDLED, CGUIControlLookup::GetControl(), CGUIControlGroup::GetFocusedControl(), CGUIControlGroup::GetFocusedControlID(), CGUIControl::GetID(), CGUIControl::GetParentControl(), GUI_MSG_SETFOCUS, CGUIControl::HasFocus(), CGUIControlGroup::m_defaultControl, m_menuControlID, m_menuLastFocusedControlID, CGUIControl::OnAction(), CGUIControl::OnBack(), CGUIControl::OnInfo(), OnMessage(), and OnMouseAction().
Referenced by XBMCAddon::xbmcgui::Window::OnAction(), ADDON::CGUIAddonWindow::OnAction(), KODI::RETRO::CGameWindowFullScreen::OnAction(), CGUIDialog::OnAction(), XBMCAddon::xbmcgui::WindowXMLInterceptor::OnAction(), XBMCAddon::xbmcgui::WindowXML::OnAction(), CGUIWindowMusicPlaylistEditor::OnAction(), CGUIWindowVisualisation::OnAction(), CGUIDialogPictureInfo::OnAction(), CGUIWindowSettingsScreenCalibration::OnAction(), CGUIWindowFullScreen::OnAction(), CGUIMediaWindow::OnAction(), CGUIWindowFileManager::OnAction(), CGUIWindowHome::OnAction(), CGUIWindowLoginScreen::OnAction(), CGUIWindowStartup::OnAction(), CGUIWindowManager::OnApplicationMessage(), and OnMouseEvent().
OnBack()
bool CGUIWindow::OnBack (int actionID) virtual
Reimplemented in CGUIDialogBusy, CGUIDialogColorPicker, CGUIDialogFileBrowser, CGUIDialogMediaSource, CGUIDialogNumeric, CGUIDialogProgress, CGUIDialogSelect, CGUIDialogSmartPlaylistEditor, CGUIDialogSmartPlaylistRule, CGUIDialogYesNo, CGUIDialog, XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, CGUIDialogSongInfo, CGUIWindowMusicBase, CGUIWindowMusicPlayList, CGUIWindowMusicPlaylistEditor, CGUIDialogNetworkSetup, CGUIDialogSettingsBase, CGUIWindowSettingsCategory, CGUIDialogCMSSettings, CGUIDialogTeletext, CGUIWindowVideoPlaylist, CGUIMediaWindow, CGUIWindowFileManager, and CGUIWindowLoginScreen.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and CGUIWindowManager::PreviousWindow().
OnDeinitWindow()
void CGUIWindow::OnDeinitWindow (int nextWindowID) virtual
Reimplemented in KODI::RETRO::CGameWindowFullScreen, CGUIDialogBoxBase, CGUIDialogColorPicker, CGUIDialogContextMenu, CGUIDialogKeyboardGeneric, CGUIDialogMediaSource, CGUIDialogNumeric, CGUIDialogSelect, CGUIDialogSmartPlaylistEditor, CGUIDialogSmartPlaylistRule, CGUIDialogTextViewer, KODI::GAME::CGUIAgentWindow, KODI::GAME::CGUIControllerWindow, KODI::GAME::CDialogGameOSD, KODI::GAME::CDialogGameSaves, KODI::GAME::CDialogGameVideoSelect, KODI::GAME::CDialogGameVolume, KODI::GAME::CGUIPortWindow, CGUIDialog, XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, CGUIDialogVisualisationPresetList, CGUIDialogNetworkSetup, CGUIDialogPictureInfo, CGUIWindowSlideShow, PVR::CGUIDialogPVRChannelGuide, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRChannelsOSD, PVR::CGUIDialogPVRGroupManager, PVR::CGUIDialogPVRItemsViewBase, PVR::CGUIWindowPVRBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRRecordingsBase, CGUIDialogTeletext, CGUIDialogVideoManager, and CGUIWindowStartup.
References m_active, m_manualRunActions, RunUnloadActions(), and SaveControlStates().
Referenced by XBMCAddon::xbmcgui::Window::OnDeinitWindow(), KODI::RETRO::CGameWindowFullScreen::OnDeinitWindow(), CGUIDialog::OnDeinitWindow(), PVR::CGUIWindowPVRBase::OnDeinitWindow(), CGUIWindowStartup::OnDeinitWindow(), and OnMessage().
OnEditChanged()
void CGUIWindow::OnEditChanged (int id, std::string & text) protected
References CGUIControl::GetID(), CGUIMessage::GetLabel(), GUI_MSG_ITEM_SELECTED, OnMessage(), and text.
Referenced by CGUIDialogMediaSource::OnMessage(), and CGUIDialogSmartPlaylistRule::OnMessage().
OnInfo()
virtual bool CGUIWindow::OnInfo (int actionID) inline virtual
Reimplemented in PVR::CGUIDialogPVRGuideInfo, and PVR::CGUIDialogPVRRecordingInfo.
OnInitWindow()
void CGUIWindow::OnInitWindow (void) protected virtual
Called on window open.
Restores the control state(s)
Sets initial visibility of controls
Queue WindowOpen animation
Set overlay state Override this function and do any window-specific initialisation such as filling control contents and setting control focus before calling the base method.
Reimplemented in CGUIDialogAddonInfo, KODI::RETRO::CGameWindowFullScreen, CGUIDialogBoxBase, CGUIDialogColorPicker, CGUIDialogContextMenu, CGUIDialogGamepad, CGUIDialogKeyboardGeneric, CGUIDialogKeyboardTouch, CGUIDialogMediaFilter, CGUIDialogNumeric, CGUIDialogOK, CGUIDialogPlayEject, CGUIDialogProgress, CGUIDialogSelect, CGUIDialogSmartPlaylistEditor, CGUIDialogSmartPlaylistRule, CGUIDialogYesNo, KODI::GAME::CGUIAgentWindow, KODI::GAME::CGUIControllerWindow, KODI::GAME::CDialogGameOSD, KODI::GAME::CDialogGameSaves, KODI::GAME::CDialogGameVideoSelect, KODI::GAME::CDialogGameVolume, KODI::GAME::CGUIPortWindow, CGUIDialogInfoProviderSettings, CGUIDialogMusicInfo, CGUIDialogSongInfo, CGUIDialogVisualisationPresetList, CGUIWindowMusicBase, CGUIDialogNetworkSetup, PERIPHERALS::CGUIDialogPeripherals, CGUIDialogPictureInfo, CGUIWindowPictures, CGUIWindowSettingsProfile, PVR::CGUIDialogPVRChannelGuide, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRChannelsOSD, PVR::CGUIDialogPVRGroupManager, PVR::CGUIDialogPVRGuideInfo, PVR::CGUIDialogPVRGuideSearch, PVR::CGUIDialogPVRItemsViewBase, PVR::CGUIDialogPVRRadioRDSInfo, PVR::CGUIWindowPVRBase, PVR::CGUIWindowPVRGuideBase, CGUIDialogContentSettings, CGUIDialogLibExportSettings, CGUIDialogSettingsBase, CGUIDialogSubtitles, CGUIDialogTeletext, CGUIDialogVideoInfo, CGUIDialogVideoManager, CGUIWindowWeather, CGUIMediaWindow, CGUIWindowFileManager, CGUIWindowHome, CGUIWindowLoginScreen, CGUIWindowScreensaver, and CGUIWindowSplash.
References ANIM_TYPE_WINDOW_OPEN, CGUIComponent::GetAudioManager(), CServiceBroker::GetGUI(), CGUIControl::GetID(), IsSoundEnabled(), m_active, m_closing, CGUIControl::m_hasProcessed, m_manualRunActions, CGUIAudioManager::PlayWindowSound(), CGUIControlGroup::QueueAnimation(), CGUIControlGroup::ResetAnimations(), RestoreControlStates(), RunLoadActions(), SetInitialVisibility(), and SOUND_INIT.
Referenced by CGUIDialogAddonInfo::OnInitWindow(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), CGUIDialogBoxBase::OnInitWindow(), CGUIDialogContextMenu::OnInitWindow(), CGUIDialogKeyboardGeneric::OnInitWindow(), CGUIDialogKeyboardTouch::OnInitWindow(), CGUIDialogMediaFilter::OnInitWindow(), CGUIDialogNumeric::OnInitWindow(), CGUIDialogSmartPlaylistEditor::OnInitWindow(), CGUIDialogSmartPlaylistRule::OnInitWindow(), KODI::GAME::CGUIAgentWindow::OnInitWindow(), KODI::GAME::CGUIControllerWindow::OnInitWindow(), KODI::GAME::CDialogGameOSD::OnInitWindow(), KODI::GAME::CDialogGameSaves::OnInitWindow(), KODI::GAME::CDialogGameVideoSelect::OnInitWindow(), KODI::GAME::CDialogGameVolume::OnInitWindow(), KODI::GAME::CGUIPortWindow::OnInitWindow(), CGUIDialogInfoProviderSettings::OnInitWindow(), CGUIDialogMusicInfo::OnInitWindow(), CGUIDialogSongInfo::OnInitWindow(), CGUIDialogNetworkSetup::OnInitWindow(), CGUIDialogPictureInfo::OnInitWindow(), CGUIWindowSettingsProfile::OnInitWindow(), PVR::CGUIDialogPVRChannelManager::OnInitWindow(), PVR::CGUIDialogPVRGroupManager::OnInitWindow(), PVR::CGUIDialogPVRGuideInfo::OnInitWindow(), PVR::CGUIDialogPVRGuideSearch::OnInitWindow(), PVR::CGUIDialogPVRItemsViewBase::OnInitWindow(), PVR::CGUIDialogPVRRadioRDSInfo::OnInitWindow(), PVR::CGUIWindowPVRBase::OnInitWindow(), CGUIDialogContentSettings::OnInitWindow(), CGUIDialogLibExportSettings::OnInitWindow(), CGUIDialogSettingsBase::OnInitWindow(), CGUIDialogSubtitles::OnInitWindow(), CGUIDialogTeletext::OnInitWindow(), CGUIDialogVideoInfo::OnInitWindow(), CGUIDialogVideoManager::OnInitWindow(), CGUIWindowWeather::OnInitWindow(), CGUIMediaWindow::OnInitWindow(), CGUIWindowFileManager::OnInitWindow(), CGUIWindowHome::OnInitWindow(), CGUIWindowLoginScreen::OnInitWindow(), CGUIWindowScreensaver::OnInitWindow(), and OnMessage().
OnMessage()
bool CGUIWindow::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControlGroup.
Reimplemented in CGUIWindowAddonBrowser, CGUIWindowEventLog, CGUIWindowFavourites, KODI::GAME::CGUIWindowGames, XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, CGUIWindowMusicBase, CGUIWindowMusicNav, CGUIWindowMusicPlayList, CGUIWindowMusicPlaylistEditor, CGUIWindowVisualisation, CGUIWindowPictures, CGUIWindowSlideShow, CGUIWindowSettingsProfile, CGUIWindowPrograms, PVR::CGUIWindowPVRBase, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRProvidersBase, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, PVR::CGUIWindowPVRTimersBase, CGUIWindowSettingsCategory, CGUIWindowSettingsScreenCalibration, CGUIWindowFullScreen, CGUIWindowVideoBase, CGUIWindowVideoNav, CGUIWindowVideoPlaylist, CGUIWindowWeather, CGUIWindowDebugInfo, CGUIWindowFileManager, CGUIWindowHome, CGUIWindowLoginScreen, CGUIWindowScreensaver, and CGUIWindowSystemInfo.
References ACTION_GESTURE_NOTIFY, CGUIControlGroup::AddControl(), CGUIControl::AllocResources(), AllocResources(), CGUIControl::DIRTY_STATE_CHILD, EVENT_RESULT_UNHANDLED, FreeResources(), CGUIControl::FreeResources(), CGUIControlLookup::GetControl(), CGUIMessage::GetControlId(), CGUIControlGroup::GetFirstFocusableControl(), CGUIControlGroup::GetFocusedControl(), CGUIControl::GetID(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIMessage::GetParam2(), CGUIMessage::GetPointer(), GetProperty(), CGUIMessage::GetSenderId(), GUI_MSG_ADD_CONTROL, GUI_MSG_EXCLUSIVE_MOUSE, GUI_MSG_FOCUSED, GUI_MSG_GESTURE_NOTIFY, GUI_MSG_LOSTFOCUS, GUI_MSG_MOVE, GUI_MSG_NOTIFY_ALL, GUI_MSG_PAGE_CHANGE, GUI_MSG_REFRESH_LIST, GUI_MSG_REFRESH_THUMBS, GUI_MSG_REMOVE_CONTROL, GUI_MSG_SETFOCUS, GUI_MSG_STATE_CHANGED, GUI_MSG_UNFOCUS_ALL, GUI_MSG_WINDOW_DEINIT, GUI_MSG_WINDOW_INIT, GUI_MSG_WINDOW_LOAD, GUI_MSG_WINDOW_RESIZE, HasID(), Initialize(), CLog::Log(), LOGDEBUG, CGUIControl::m_bAllocated, CGUIControlGroup::m_children, m_dynamicResourceAlloc, m_exclusiveMouseControl, CGUIControlGroup::m_focusedControl, CGUIControl::MarkDirtyRegion(), OnDeinitWindow(), OnInitWindow(), CGUIControl::OnMessage(), CGUIControlGroup::OnMessage(), OnMouseAction(), OnMove(), CGUIControlGroup::RemoveControl(), and CGUIMessage::SetPointer().
Referenced by Close_Internal(), CApplicationSkinHandling::LoadSkin(), OnAction(), OnEditChanged(), KODI::GAME::CGUIControllerList::OnFocus(), KODI::RETRO::CGameWindowFullScreenText::OnMessage(), XBMCAddon::xbmcgui::Window::OnMessage(), KODI::RETRO::CGameWindowFullScreen::OnMessage(), CGUIDialog::OnMessage(), XBMCAddon::xbmcgui::WindowDialog::OnMessage(), XBMCAddon::xbmcgui::WindowXML::OnMessage(), XBMCAddon::xbmcgui::WindowXMLDialog::OnMessage(), CGUIWindowVisualisation::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowWeather::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIWindowHome::OnMessage(), CGUIWindowLoginScreen::OnMessage(), CGUIWindowScreensaver::OnMessage(), CGUIWindowSystemInfo::OnMessage(), CGUIWindowManager::PreviousWindow(), KODI::GAME::CGUIActivePortList::Refresh(), KODI::GAME::CGUIControllerList::Refresh(), RestoreControlStates(), CGUIWindowManager::SendMessage(), CGUIWindowManager::SendMessage(), SendMessage(), CGUIControl::SendWindowMessage(), Show(), Slideshow(), and CApplicationPowerHandling::WakeUpScreenSaver().
OnMouseAction()
EVENT_RESULT CGUIWindow::OnMouseAction (const CAction & action) protected
References CGUIControlLookup::GetControl(), CWinSystemBase::GetGfxContext(), CGUIControl::GetRenderPosition(), CServiceBroker::GetWinSystem(), CGUIControl::GetXPosition(), CGUIControl::GetYPosition(), CGraphicContext::InvertFinalCoords(), m_coordsRes, m_exclusiveMouseControl, m_needsScaling, CGUIControl::OnMouseEvent(), CGUIControlGroup::SendMouseEvent(), CGraphicContext::SetScalingResolution(), CGUIControlGroup::UnfocusFromPoint(), CPointGen< T >::x, and CPointGen< T >::y.
Referenced by OnAction(), and OnMessage().
OnMouseEvent()
EVENT_RESULT CGUIWindow::OnMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) override protected virtual
Perform a mouse action.
Mouse actions are sent from the window to all controls, and each control can react based on the event and location of the actions.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
SendMouseEvent, HitTest, CanFocusFromPoint, CMouseEvent
Reimplemented from CGUIControl.
Reimplemented in CGUIWindowVisualisation, CGUIWindowSlideShow, and CGUIWindowFullScreen.
References ACTION_MOUSE_RIGHT_CLICK, ACTION_PREVIOUS_MENU, EVENT_RESULT_HANDLED, EVENT_RESULT_UNHANDLED, KODI::MOUSE::CMouseEvent::m_id, and OnAction().
OnMove()
bool CGUIWindow::OnMove (int fromControl, int moveAction)
References CGUIControl::GetAction(), CGUIControlLookup::GetControl(), CGUIControlGroup::GetFirstFocusableControl(), CGUIControl::GetID(), CGUIControl::GetParentID(), CLog::Log(), LOGERROR, and SET_CONTROL_FOCUS.
Referenced by OnMessage().
OnWindowLoaded()
void CGUIWindow::OnWindowLoaded () protected virtual
Reimplemented in KODI::RETRO::CGameWindowFullScreen, CGUIDialogColorPicker, CGUIDialogContextMenu, CGUIDialogFileBrowser, CGUIDialogKeyboardGeneric, CGUIDialogMediaFilter, CGUIDialogProgress, CGUIDialogSelect, CGUIDialogSlider, KODI::GAME::CGUIAgentWindow, KODI::GAME::CDialogGameSaves, KODI::GAME::CDialogGameVideoSelect, KODI::GAME::CGUIPortWindow, CGUIDialog, CGUIWindowMusicNav, CGUIDialogProfileSettings, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRGroupManager, PVR::CGUIDialogPVRGuideSearch, PVR::CGUIDialogPVRItemsViewBase, PVR::CGUIWindowPVRRecordingsBase, CGUIWindowSettingsCategory, CGUIDialogVideoBookmarks, CGUIWindowFullScreen, CGUIMediaWindow, CGUIWindowLoginScreen, and CGUIWindowPointer.
References DynamicResourceAlloc().
Referenced by Load(), KODI::RETRO::CGameWindowFullScreen::OnWindowLoaded(), CGUIDialog::OnWindowLoaded(), CGUIWindowMusicNav::OnWindowLoaded(), CGUIWindowFullScreen::OnWindowLoaded(), CGUIMediaWindow::OnWindowLoaded(), CGUIWindowLoginScreen::OnWindowLoaded(), and CGUIWindowPointer::OnWindowLoaded().
OnWindowUnload()
virtual void CGUIWindow::OnWindowUnload () inline protected virtual
Reimplemented in CGUIDialogColorPicker, CGUIDialogFileBrowser, CGUIDialogSelect, KODI::GAME::CGUIAgentWindow, KODI::GAME::CDialogGameSaves, KODI::GAME::CDialogGameVideoSelect, KODI::GAME::CGUIPortWindow, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRGroupManager, PVR::CGUIDialogPVRItemsViewBase, CGUIDialogVideoBookmarks, CGUIMediaWindow, and CGUIWindowLoginScreen.
Referenced by ClearAll(), CGUIDialogColorPicker::OnWindowUnload(), CGUIDialogFileBrowser::OnWindowUnload(), CGUIDialogSelect::OnWindowUnload(), KODI::GAME::CGUIAgentWindow::OnWindowUnload(), KODI::GAME::CDialogGameSaves::OnWindowUnload(), KODI::GAME::CDialogGameVideoSelect::OnWindowUnload(), KODI::GAME::CGUIPortWindow::OnWindowUnload(), PVR::CGUIDialogPVRChannelManager::OnWindowUnload(), PVR::CGUIDialogPVRGroupManager::OnWindowUnload(), PVR::CGUIDialogPVRItemsViewBase::OnWindowUnload(), CGUIDialogVideoBookmarks::OnWindowUnload(), CGUIMediaWindow::OnWindowUnload(), and CGUIWindowLoginScreen::OnWindowUnload().
Prepare()
std::unique_ptr< TiXmlElement > CGUIWindow::Prepare (const std::unique_ptr< TiXmlElement > & rootElement) protected virtual
Prepare the XML for load.
Parameters
rootElement the original XML element
Returns
the prepared XML (resolved includes, constants and expression)
References g_SkinInfo, and m_xmlIncludeConditions.
Referenced by LoadXML().
ResetControlStates()
void CGUIWindow::ResetControlStates () virtual
References m_controlStates, CGUIControlGroup::m_focusedControl, and m_lastControlID.
Referenced by CProfileManager::LoadProfile(), CGUIDialogSettingsBase::OnMessage(), and SaveControlStates().
RestoreControlStates()
void CGUIWindow::RestoreControlStates () protected virtual
Reimplemented in PVR::CGUIDialogPVRChannelsOSD, and CGUIMediaWindow.
References CGUIControl::GetID(), GUI_MSG_ITEM_SELECT, m_controlStates, CGUIControlGroup::m_defaultAlways, CGUIControlGroup::m_defaultControl, m_lastControlID, OnMessage(), and SET_CONTROL_FOCUS.
Referenced by OnInitWindow(), PVR::CGUIDialogPVRChannelsOSD::RestoreControlStates(), and CGUIMediaWindow::RestoreControlStates().
RunLoadActions()
void CGUIWindow::RunLoadActions () const
References CGUIAction::ExecuteActions(), CGUIControl::GetID(), CGUIControl::GetParentID(), and m_loadActions.
Referenced by OnInitWindow().
RunUnloadActions()
void CGUIWindow::RunUnloadActions () const
References CGUIAction::ExecuteActions(), CGUIControl::GetID(), CGUIControl::GetParentID(), and m_unloadActions.
Referenced by OnDeinitWindow().
SaveControlStates()
void CGUIWindow::SaveControlStates () protected virtual
Reimplemented in PVR::CGUIDialogPVRChannelsOSD, and CGUIMediaWindow.
References CGUIControlGroup::GetFocusedControlID(), CGUIControlGroup::m_children, m_controlStates, CGUIControlGroup::m_defaultAlways, m_lastControlID, and ResetControlStates().
Referenced by OnDeinitWindow(), PVR::CGUIDialogPVRChannelsOSD::SaveControlStates(), and CGUIMediaWindow::SaveControlStates().
SendMessage()
bool CGUIWindow::SendMessage (int message, int id, int param1 = 0, int param2 = 0) protected
References CGUIControl::GetID(), and OnMessage().
Referenced by CGUIDialogSmartPlaylistEditor::OnDeinitWindow(), CGUIDialogSmartPlaylistRule::OnDeinitWindow(), CGUIWindowMusicNav::OnWindowLoaded(), CGUIMediaWindow::OnWindowLoaded(), CGUIDialogMediaSource::UpdateButtons(), CGUIDialogSmartPlaylistEditor::UpdateButtons(), and CGUIDialogSmartPlaylistRule::UpdateButtons().
SetCoordsRes()
void CGUIWindow::SetCoordsRes (const RESOLUTION_INFO & res) inline
References m_coordsRes.
Referenced by ADDON::Interface_GUIWindow::create().
SetCustom()
void CGUIWindow::SetCustom (bool custom) inline
Mark this window as custom window.
Parameters
custom true if this window is a custom window, false if not
References m_custom.
Referenced by CApplicationSkinHandling::LoadCustomWindows().
SetDefaults()
void CGUIWindow::SetDefaults () protected virtual
Reimplemented in CGUIDialog.
References RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, CGUIControl::m_animations, m_animationsEnabled, m_clearBackground, m_coordsRes, CGUIControlGroup::m_defaultAlways, CGUIControlGroup::m_defaultControl, CGUIControl::m_hasCamera, CGUIControl::m_height, CGUIControl::m_hitRect, m_menuControlID, m_menuLastFocusedControlID, m_origins, CGUIControl::m_posX, CGUIControl::m_posY, m_previousWindow, m_renderOrder, CGUIControl::m_stereo, CGUIControl::m_width, RENDER_ORDER_WINDOW, CRectGen< T >::SetRect(), and WINDOW_INVALID.
Referenced by Load(), and CGUIDialog::SetDefaults().
SetID()
void CGUIWindow::SetID (int id) override virtual
Reimplemented from CGUIControl.
References m_idRange, and CGUIControl::SetID().
Referenced by CGUIWindowManager::AddUniqueInstance(), KODI::GAME::CDialogGameVolume::CDialogGameVolume(), PERIPHERALS::CGUIDialogPeripherals::CGUIDialogPeripherals(), CGUIWindow(), and LoadXML().
SetInitialVisibility()
void CGUIWindow::SetInitialVisibility () override virtual
Reimplemented from CGUIControlGroup.
References CServiceBroker::GetGUI(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetGUIControlsInfoProvider(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CGUIInfoManager::ResetCache(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::ResetContainerMovingCache(), and CGUIControlGroup::SetInitialVisibility().
Referenced by OnInitWindow(), CGUIMediaWindow::OnMessage(), and CGUIDialogContextMenu::ShowAndGetChoice().
SetLoadType()
void CGUIWindow::SetLoadType (LOAD_TYPE loadType) inline
References m_loadType.
Referenced by CApplicationSkinHandling::LoadCustomWindows().
SetProperty()
void CGUIWindow::SetProperty (const std::string & key, const CVariant & value)
Set a property Sets the value of a property referenced by a key.
Parameters
key name of the property to set
value value to set, may be a string, integer, boolean or double.
See also
GetProperty
References m_mapProperties, and value.
Referenced by CGUIWindow(), ADDON::Interface_GUIWindow::clear_property(), CGUIWindowWeather::ClearProperties(), XBMCAddon::xbmcgui::Window::clearProperty(), anonymous_namespace{GUIBuiltins.cpp}::ClearProperty(), CGUIMediaWindow::Filter(), CGUIMediaWindow::GetDirectory(), CGUIWindowMusicNav::OnClick(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRadioTV(), CGUIMediaWindow::OnFilterItems(), PVR::CGUIWindowPVRBase::OnInitWindow(), CGUIWindowMusicNav::OnMessage(), CGUIWindowVideoNav::OnMessage(), CWeatherManager::OnSettingChanged(), ADDON::Interface_GUIWindow::set_property(), ADDON::Interface_GUIWindow::set_property_bool(), ADDON::Interface_GUIWindow::set_property_double(), ADDON::Interface_GUIWindow::set_property_int(), CWeatherJob::SetFromProperties(), CGUIWindowAddonBrowser::SetProperties(), CGUIWindowWeather::SetProperties(), XBMCAddon::xbmcgui::Window::setProperty(), anonymous_namespace{GUIBuiltins.cpp}::SetProperty(), PVR::CGUIDialogPVRChannelManager::SetRadio(), PVR::CGUIDialogPVRGroupManager::SetRadio(), CGUIDialogAddonSettings::SetupView(), PERIPHERALS::CGUIDialogPeripherals::Show(), KODI::GAME::CGUIAgentControllerList::ShowControllerDialog(), and CGUIWindowVideoBase::UpdateVideoVersionItemsLabel().
SetRunActionsManually()
void CGUIWindow::SetRunActionsManually ()
References m_manualRunActions.
UpdateControlStats()
void CGUIWindow::UpdateControlStats () inline override virtual
Reimplemented from CGUIControl.
Member Data Documentation
m_active
bool CGUIWindow::m_active protected
Referenced by CGUIDialogProgress::Abort(), CGUIWindow(), Close_Internal(), CGUIDialog::DoProcess(), CGUIDialog::IsDialogRunning(), KODI::GAME::CDialogGameVolume::IsShown(), PVR::CGUIWindowPVRBase::NotifyEvent(), OnDeinitWindow(), CGUIDialog::OnDeinitWindow(), OnInitWindow(), CGUIDialogProgress::Open(), CGUIDialog::Open_Internal(), CGUIDialogExtendedProgressBar::Process(), CGUIDialogProgress::Progress(), CGUIDialog::Render(), CGUIDialog::ResetAutoClose(), and CGUIDialogProgress::Wait().
m_animationsEnabled
bool CGUIWindow::m_animationsEnabled protected
Referenced by Animate(), CGUIWindow(), DisableAnimations(), IsAnimating(), and SetDefaults().
m_clearBackground
KODI::GUILIB::GUIINFO::CGUIInfoColor CGUIWindow::m_clearBackground protected
Referenced by CGUIWindow(), ClearBackground(), Load(), KODI::RETRO::CGameWindowFullScreen::OnWindowLoaded(), CGUIWindowFullScreen::OnWindowLoaded(), and SetDefaults().
m_closing
bool CGUIWindow::m_closing protected
Referenced by AfterRender(), CGUIWindow(), Close_Internal(), IsAnimating(), OnInitWindow(), CGUIDialog::Open_Internal(), and CGUIDialog::UpdateVisibility().
m_controlStates
std::vector<CControlState> CGUIWindow::m_controlStates protected
Referenced by ResetControlStates(), RestoreControlStates(), and SaveControlStates().
m_coordsRes
RESOLUTION_INFO CGUIWindow::m_coordsRes protected
Referenced by CenterWindow(), DoProcess(), DoRender(), GetCoordsRes(), GetScaledBounds(), Load(), Load(), OnMouseAction(), CGUIWindowSlideShow::Render(), CGUIWindowFullScreen::Render(), CGUIWindowFullScreen::RenderEx(), CGUIDialogTeletext::SetCoordinates(), SetCoordsRes(), SetDefaults(), CGUIDialogContextMenu::SetPosition(), and CGUIDialogKeyboardGeneric::ShowWordList().
m_custom
bool CGUIWindow::m_custom protected
Referenced by CGUIWindow(), IsCustom(), and SetCustom().
m_dynamicResourceAlloc
bool CGUIWindow::m_dynamicResourceAlloc protected
Referenced by CGUIWindow(), ClearAll(), DynamicResourceAlloc(), and OnMessage().
m_exclusiveMouseControl
int CGUIWindow::m_exclusiveMouseControl protected
id of child control that wishes to receive all mouse events
See also
GUI_MSG_EXCLUSIVE_MOUSE
Referenced by CGUIWindow(), OnMessage(), and OnMouseAction().
m_idRange
std::vector<int> CGUIWindow::m_idRange protected
Referenced by CGUIWindowSettingsCategory::CGUIWindowSettingsCategory(), GetIDRange(), HasID(), and SetID().
m_lastControlID
int CGUIWindow::m_lastControlID protected
Referenced by CGUIWindow(), CGUIDialogSettingsBase::OnBack(), CGUIDialogBoxBase::OnInitWindow(), CGUIDialogContextMenu::OnInitWindow(), ResetControlStates(), RestoreControlStates(), and SaveControlStates().
m_loadActions
CGUIAction CGUIWindow::m_loadActions protected
Referenced by Load(), and RunLoadActions().
m_loadType
LOAD_TYPE CGUIWindow::m_loadType protected
Referenced by AllocResources(), KODI::GAME::CDialogGameOSD::CDialogGameOSD(), KODI::GAME::CDialogGameVideoSelect::CDialogGameVideoSelect(), KODI::GAME::CDialogGameVolume::CDialogGameVolume(), KODI::RETRO::CGameWindowFullScreen::CGameWindowFullScreen(), ADDON::CGUIAddonWindow::CGUIAddonWindow(), KODI::GAME::CGUIAgentWindow::CGUIAgentWindow(), KODI::GAME::CGUIControllerWindow::CGUIControllerWindow(), CGUIDialogAddonInfo::CGUIDialogAddonInfo(), CGUIDialogBoxBase::CGUIDialogBoxBase(), CGUIDialogBusy::CGUIDialogBusy(), CGUIDialogBusyNoCancel::CGUIDialogBusyNoCancel(), CGUIDialogButtonMenu::CGUIDialogButtonMenu(), CGUIDialogColorPicker::CGUIDialogColorPicker(), CGUIDialogContextMenu::CGUIDialogContextMenu(), CGUIDialogExtendedProgressBar::CGUIDialogExtendedProgressBar(), CGUIDialogFileBrowser::CGUIDialogFileBrowser(), CGUIDialogFullScreenInfo::CGUIDialogFullScreenInfo(), CGUIDialogKaiToast::CGUIDialogKaiToast(), CGUIDialogKeyboardGeneric::CGUIDialogKeyboardGeneric(), CGUIDialogMediaSource::CGUIDialogMediaSource(), CGUIDialogMusicInfo::CGUIDialogMusicInfo(), CGUIDialogMusicOSD::CGUIDialogMusicOSD(), CGUIDialogNetworkSetup::CGUIDialogNetworkSetup(), CGUIDialogNumeric::CGUIDialogNumeric(), CGUIDialogPictureInfo::CGUIDialogPictureInfo(), CGUIDialogPlayerControls::CGUIDialogPlayerControls(), CGUIDialogPlayerProcessInfo::CGUIDialogPlayerProcessInfo(), PVR::CGUIDialogPVRClientPriorities::CGUIDialogPVRClientPriorities(), PVR::CGUIDialogPVRGuideControls::CGUIDialogPVRGuideControls(), PVR::CGUIDialogPVRRecordingSettings::CGUIDialogPVRRecordingSettings(), PVR::CGUIDialogPVRTimerSettings::CGUIDialogPVRTimerSettings(), CGUIDialogSeekBar::CGUIDialogSeekBar(), CGUIDialogSelect::CGUIDialogSelect(), CGUIDialogSettingsBase::CGUIDialogSettingsBase(), CGUIDialogSlider::CGUIDialogSlider(), CGUIDialogSmartPlaylistEditor::CGUIDialogSmartPlaylistEditor(), CGUIDialogSmartPlaylistRule::CGUIDialogSmartPlaylistRule(), CGUIDialogSongInfo::CGUIDialogSongInfo(), CGUIDialogSubtitles::CGUIDialogSubtitles(), CGUIDialogTextViewer::CGUIDialogTextViewer(), CGUIDialogVideoBookmarks::CGUIDialogVideoBookmarks(), CGUIDialogVideoInfo::CGUIDialogVideoInfo(), CGUIDialogVideoManager::CGUIDialogVideoManager(), CGUIDialogVideoOSD::CGUIDialogVideoOSD(), CGUIDialogVisualisationPresetList::CGUIDialogVisualisationPresetList(), CGUIDialogVolumeBar::CGUIDialogVolumeBar(), CGUIMediaWindow::CGUIMediaWindow(), KODI::GAME::CGUIPortWindow::CGUIPortWindow(), CGUIWindow(), CGUIWindowFavourites::CGUIWindowFavourites(), CGUIWindowFileManager::CGUIWindowFileManager(), CGUIWindowFullScreen::CGUIWindowFullScreen(), CGUIWindowHome::CGUIWindowHome(), CGUIWindowLoginScreen::CGUIWindowLoginScreen(), CGUIWindowPointer::CGUIWindowPointer(), CGUIWindowSettings::CGUIWindowSettings(), CGUIWindowSettingsProfile::CGUIWindowSettingsProfile(), CGUIWindowSlideShow::CGUIWindowSlideShow(), CGUIWindowSplash::CGUIWindowSplash(), CGUIWindowSystemInfo::CGUIWindowSystemInfo(), CGUIWindowVisualisation::CGUIWindowVisualisation(), CGUIWindowWeather::CGUIWindowWeather(), FreeResources(), GetLoadType(), Load(), and SetLoadType().
m_manualRunActions
bool CGUIWindow::m_manualRunActions protected
Referenced by CGUIWindow(), OnDeinitWindow(), OnInitWindow(), and SetRunActionsManually().
m_mapProperties
std::map<std::string, CVariant, icompare> CGUIWindow::m_mapProperties private
Referenced by ClearProperties(), GetProperty(), and SetProperty().
m_menuControlID
int CGUIWindow::m_menuControlID protected
Referenced by CGUIWindow(), Load(), OnAction(), and SetDefaults().
m_menuLastFocusedControlID
int CGUIWindow::m_menuLastFocusedControlID protected
Referenced by CGUIWindow(), OnAction(), and SetDefaults().
m_needsScaling
bool CGUIWindow::m_needsScaling protected
Referenced by CGUIWindow(), CGUIWindowDebugInfo::CGUIWindowDebugInfo(), CGUIWindowPointer::CGUIWindowPointer(), CGUIWindowScreensaverDim::CGUIWindowScreensaverDim(), CGUIWindowSettingsScreenCalibration::CGUIWindowSettingsScreenCalibration(), DoProcess(), CGUIWindowSettingsScreenCalibration::DoProcess(), DoRender(), CGUIWindowSettingsScreenCalibration::DoRender(), GetScaledBounds(), Load(), OnMouseAction(), CGUIWindowSlideShow::Render(), CGUIWindowFullScreen::Render(), CGUIWindowFullScreen::RenderEx(), and CGUIDialogTeletext::SetCoordinates().
m_origins
std::vector<COrigin> CGUIWindow::m_origins protected
Referenced by GetPosition(), Load(), and SetDefaults().
m_previousWindow
int CGUIWindow::m_previousWindow protected
Referenced by CGUIWindow(), GetPreviousWindow(), Load(), and SetDefaults().
m_renderOrder
int CGUIWindow::m_renderOrder protected
Referenced by CGUIDialog::CGUIDialog(), CGUIDialogTeletext::CGUIDialogTeletext(), CGUIWindow(), CGUIWindowDebugInfo::CGUIWindowDebugInfo(), CGUIWindowPointer::CGUIWindowPointer(), CGUIWindowScreensaver::CGUIWindowScreensaver(), CGUIWindowScreensaverDim::CGUIWindowScreensaverDim(), GetRenderOrder(), Load(), CGUIWindowPointer::OnWindowLoaded(), SetDefaults(), CGUIDialog::SetDefaults(), and ADDON::CGUIAddonWindowDialog::Show_Internal().
m_unloadActions
CGUIAction CGUIWindow::m_unloadActions protected
Referenced by Load(), and RunUnloadActions().
m_windowLoaded
bool CGUIWindow::m_windowLoaded protected
Referenced by AllocResources(), CGUIWindow(), ClearAll(), ADDON::CGUIAddonWindow::GetAddonControl(), Initialize(), Load(), NeedLoad(), CGUIDialogTeletext::OnDeinitWindow(), CGUIDialogKeyboardTouch::OnInitWindow(), CGUIDialogTeletext::OnInitWindow(), and CGUIDialog::Open_Internal().
m_windowXMLRootElement
std::unique_ptr<TiXmlElement> CGUIWindow::m_windowXMLRootElement protected
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
Referenced by FreeResources(), and LoadXML().
m_xmlIncludeConditions
std::map<INFO::InfoPtr, bool> CGUIWindow::m_xmlIncludeConditions private
used to store conditions used to resolve includes for this window
Referenced by FreeResources(), NeedLoad(), and Prepare().
The documentation for this class was generated from the following files:
GUIWindow.h
GUIWindow.cpp