Kodi Documentation: NPT_XbmcFileInputStream Class Reference
NPT_XbmcFileInputStream Class Reference
Public Member Functions
NPT_XbmcFileInputStream (NPT_XbmcFileReference &file)
NPT_Result Read (void *buffer, NPT_Size bytes_to_read, NPT_Size *bytes_read) override
NPT_Result Seek (NPT_Position offset) override
NPT_Result Tell (NPT_Position &offset) override
NPT_Result GetSize (NPT_LargeSize &size) override
NPT_Result GetAvailable (NPT_LargeSize &available) override
Additional Inherited Members
Private Member Functions inherited from NPT_XbmcFileStream
NPT_XbmcFileStream (const NPT_XbmcFileReference &file)
NPT_Result Seek (NPT_Position offset)
NPT_Result Tell (NPT_Position &offset)
NPT_Result Flush ()
virtual ~NPT_XbmcFileStream ()=default
Private Attributes inherited from NPT_XbmcFileStream
NPT_XbmcFileReference m_FileReference
Constructor & Destructor Documentation
NPT_XbmcFileInputStream()
NPT_XbmcFileInputStream::NPT_XbmcFileInputStream (NPT_XbmcFileReference & file) inline explicit
Member Function Documentation
GetAvailable()
NPT_Result NPT_XbmcFileInputStream::GetAvailable (NPT_LargeSize & available) override
References GetSize(), int64_t(), and NPT_XbmcFileStream::m_FileReference.
GetSize()
NPT_Result NPT_XbmcFileInputStream::GetSize (NPT_LargeSize & size) override
References NPT_XbmcFileStream::m_FileReference.
Referenced by GetAvailable().
Read()
NPT_Result NPT_XbmcFileInputStream::Read (void * buffer, NPT_Size bytes_to_read, NPT_Size * bytes_read) override
References NPT_XbmcFileStream::m_FileReference.
Seek()
NPT_Result NPT_XbmcFileInputStream::Seek (NPT_Position offset) inline override
References NPT_XbmcFileStream::Seek().
Tell()
NPT_Result NPT_XbmcFileInputStream::Tell (NPT_Position & offset) inline override
References NPT_XbmcFileStream::Tell().
The documentation for this class was generated from the following file:
NptXbmcFile.cpp