Kodi Documentation: TestRssReader.cpp File Reference
TestRssReader.cpp File Reference
#include "test/TestUtils.h"
#include "utils/RssReader.h"
#include <cstring>
#include <fstream>
#include <iosfwd>
#include <string>
#include <vector>
#include <gtest/gtest.h>
Classes
class TestRssReader
Functions
TEST (TestRssReader, ParseCorrectRss)
TEST (TestRssReader, ParseCorruptRss)
Function Documentation
TEST() [1/2]
TEST (TestRssReader , ParseCorrectRss)
References CRssReader::Create(), EXPECT_TRUE(), CRssReader::Parse(), and XBMC_REF_FILE_PATH.
TEST() [2/2]
TEST (TestRssReader , ParseCorruptRss)
References CRssReader::Create(), CRssReader::Parse(), and XBMC_REF_FILE_PATH.