Kodi Documentation: TestDateTime.cpp File Reference
TestDateTime.cpp File Reference
#include "LangInfo.h"
#include "XBDateTime.h"
#include "guilib/LocalizeStrings.h"
#include "interfaces/legacy/ModuleXbmc.h"
#include <array>
#include <iostream>
#include <gtest/gtest.h>
Classes
class TestDateTime
Functions
TEST_F (TestDateTime, DateTimeOperators)
TEST_F (TestDateTime, FileTimeOperators)
TEST_F (TestDateTime, SystemTimeOperators)
TEST_F (TestDateTime, TimeTOperators)
TEST_F (TestDateTime, TmOperators)
TEST_F (TestDateTime, GetCurrentDateTime)
TEST_F (TestDateTime, GetUTCDateTime)
TEST_F (TestDateTime, MonthStringToMonthNum)
TEST_F (TestDateTime, DISABLED_SetFromDateString)
TEST_F (TestDateTime, SetFromDBDate)
EXPECT_TRUE (dateTime1.SetFromDBTime("12:34"))
EXPECT_EQ (dateTime1.GetHour(), 12)
EXPECT_EQ (dateTime1.GetMinute(), 34)
EXPECT_EQ (dateTime1.GetSecond(), 0)
EXPECT_TRUE (dateTime2.SetFromDBTime("12:34:56"))
EXPECT_EQ (dateTime2.GetHour(), 12)
EXPECT_EQ (dateTime2.GetMinute(), 34)
EXPECT_EQ (dateTime2.GetSecond(), 56)
TEST_F (TestDateTime, SetFromDBDateTime)
TEST_F (TestDateTime, SetFromW3CDate)
TEST_F (TestDateTime, SetFromW3CDateTime)
TEST_F (TestDateTime, SetFromUTCDateTime)
TEST_F (TestDateTime, SetFromRFC1123DateTime)
TEST_F (TestDateTime, SetDateTime)
TEST_F (TestDateTime, GetAsStrings)
TEST_F (TestDateTime, DISABLED_GetAsStringsWithBias)
TEST_F (TestDateTime, GetAsLocalized)
TEST_F (TestDateTime, GetAsSystemTime)
TEST_F (TestDateTime, GetAsTime)
TEST_F (TestDateTime, GetAsTm)
TEST_F (TestDateTime, DISABLED_GetAsTimeStamp)
TEST_F (TestDateTime, GetAsUTCDateTime)
dateTime SetDateTime (1991, 05, 14, 12, 34, 56)
dateTime Reset ()
EXPECT_EQ (dateTime.GetYear(), 1601)
EXPECT_EQ (dateTime.GetMonth(), 1)
EXPECT_EQ (dateTime.GetHour(), 0)
Variables
CDateTime dateTime2
Function Documentation
EXPECT_EQ() [1/9]
EXPECT_EQ (dateTime. GetHour(), 0)
EXPECT_EQ() [2/9]
EXPECT_EQ (dateTime. GetMonth(), 1)
EXPECT_EQ() [3/9]
EXPECT_EQ (dateTime. GetYear(), 1601)
EXPECT_EQ() [4/9]
EXPECT_EQ (dateTime1. GetHour(), 12)
Referenced by TestWebServer::CheckRangesTestFileResponse(), anonymous_namespace{TestEndTime.cpp}::CommonTests(), anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetController(), anonymous_namespace{TestDefaultMouseTranslator.cpp}::GetController(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), anonymous_namespace{TestImageFileURL.cpp}::TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TYPED_TEST(), and TYPED_TEST().
EXPECT_EQ() [5/9]
EXPECT_EQ (dateTime1. GetMinute(), 34)
EXPECT_EQ() [6/9]
EXPECT_EQ (dateTime1. GetSecond(), 0)
EXPECT_EQ() [7/9]
EXPECT_EQ (dateTime2. GetHour(), 12)
EXPECT_EQ() [8/9]
EXPECT_EQ (dateTime2. GetMinute(), 34)
EXPECT_EQ() [9/9]
EXPECT_EQ (dateTime2. GetSecond(), 56)
EXPECT_TRUE() [1/2]
EXPECT_TRUE (dateTime1. SetFromDBTime"12:34")
Referenced by TestWebServer::CheckHtmlTestFileResponse(), TestWebServer::CheckRangesTestFileResponse(), TestWebServer::CheckRangesTestFileResponse(), anonymous_namespace{TestEndTime.cpp}::CommonTests(), anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetController(), anonymous_namespace{TestDefaultMouseTranslator.cpp}::GetController(), RunMassEventTest(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_P(), TEST_P(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), and TestArchive::~TestArchive().
EXPECT_TRUE() [2/2]
EXPECT_TRUE (dateTime2. SetFromDBTime"12:34:56")
Reset()
dateTime Reset ()
Referenced by kodi::addon::CInstanceGame::ADDON_Reset(), kodi::addon::CInstanceVideoCodec::ADDON_Reset(), UPNP::CUPnPRenderer::Announce(), CGUIDialogMediaFilter::InitializeSettings(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), CGUIDialogMediaFilter::OnMessage(), CURL::Parse(), KODI::WINDOWING::WAYLAND::CWindowDecorator::SetState(), UPNP::CUPnPRenderer::UpdateState(), CDBusError::~CDBusError(), CGUIControlProfilerItem::~CGUIControlProfilerItem(), and CGUIDialogMediaFilter::~CGUIDialogMediaFilter().
SetDateTime()
dateTime SetDateTime (1991 , 05 , 14 , 12 , 34 , 56)
TEST_F() [1/24]
TEST_F (TestDateTime , DateTimeOperators)
References dateTime2, and EXPECT_TRUE().
TEST_F() [2/24]
TEST_F (TestDateTime , DISABLED_GetAsStringsWithBias)
References EXPECT_EQ(), CDateTime::GetAsRFC1123DateTime(), CDateTime::GetAsW3CDateTime(), CDateTime::GetTimezoneBias(), and CDateTime::SetDateTime().
TEST_F() [3/24]
TEST_F (TestDateTime , DISABLED_GetAsTimeStamp)
References EXPECT_TRUE(), CDateTime::GetAsTimeStamp(), CDateTime::GetTimezoneBias(), and CDateTime::SetDateTime().
TEST_F() [4/24]
TEST_F (TestDateTime , DISABLED_SetFromDateString)
References EXPECT_EQ(), EXPECT_TRUE(), CDateTime::GetDay(), CDateTime::GetMonth(), CDateTime::GetYear(), and CDateTime::SetFromDateString().
TEST_F() [5/24]
TEST_F (TestDateTime , FileTimeOperators)
References dateTime2, EXPECT_TRUE(), and CDateTime::GetAsTimeStamp().
TEST_F() [6/24]
TEST_F (TestDateTime , GetAsLocalized)
References CDateTime::CHOICE_YES, dateTime2, EXPECT_EQ(), g_langInfo, g_localizeStrings, CDateTime::GetAsLocalizedDate(), CDateTime::GetAsLocalizedDateTime(), CDateTime::GetAsLocalizedTime(), XBMCAddon::xbmc::getRegion(), CLocalizeStrings::Load(), and CDateTime::SetDateTime().
TEST_F() [7/24]
TEST_F (TestDateTime , GetAsStrings)
References EXPECT_EQ(), CDateTime::GetAsDBDate(), CDateTime::GetAsDBDateTime(), CDateTime::GetAsDBTime(), CDateTime::GetAsSaveString(), CDateTime::GetAsW3CDate(), and CDateTime::SetDateTime().
TEST_F() [8/24]
TEST_F (TestDateTime , GetAsSystemTime)
References EXPECT_TRUE(), CDateTime::GetAsSystemTime(), and CDateTime::SetDateTime().
TEST_F() [9/24]
TEST_F (TestDateTime , GetAsTime)
References EXPECT_TRUE(), CDateTime::GetAsTime(), and CDateTime::SetDateTime().
TEST_F() [10/24]
TEST_F (TestDateTime , GetAsTm)
References EXPECT_TRUE(), CDateTime::GetAsTm(), and CDateTime::SetDateTime().
TEST_F() [11/24]
TEST_F (TestDateTime , GetAsUTCDateTime)
References dateTime2, EXPECT_EQ(), CDateTime::GetAsUTCDateTime(), CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetSecond(), CDateTime::GetTimezoneBias(), CDateTime::GetYear(), and CDateTime::SetDateTime().
TEST_F() [12/24]
TEST_F (TestDateTime , GetCurrentDateTime)
References CDateTime::GetCurrentDateTime().
TEST_F() [13/24]
TEST_F (TestDateTime , GetUTCDateTime)
References CDateTime::GetUTCDateTime().
TEST_F() [14/24]
TEST_F (TestDateTime , MonthStringToMonthNum)
References EXPECT_EQ(), and CDateTime::MonthStringToMonthNum().
TEST_F() [15/24]
TEST_F (TestDateTime , SetDateTime)
References dateTime2, EXPECT_EQ(), EXPECT_TRUE(), CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetSecond(), CDateTime::GetYear(), CDateTime::SetDate(), CDateTime::SetDateTime(), and CDateTime::SetTime().
TEST_F() [16/24]
TEST_F (TestDateTime , SetFromDBDate)
References EXPECT_EQ(), EXPECT_TRUE(), CDateTime::GetDay(), CDateTime::GetMonth(), CDateTime::GetYear(), CDateTime::Reset(), and CDateTime::SetFromDBDate().
TEST_F() [17/24]
TEST_F (TestDateTime , SetFromDBDateTime)
References EXPECT_EQ(), EXPECT_TRUE(), CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetSecond(), CDateTime::GetYear(), and CDateTime::SetFromDBDateTime().
TEST_F() [18/24]
TEST_F (TestDateTime , SetFromRFC1123DateTime)
References dateTime2, EXPECT_EQ(), EXPECT_TRUE(), CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetSecond(), CDateTime::GetYear(), and CDateTime::SetFromRFC1123DateTime().
TEST_F() [19/24]
TEST_F (TestDateTime , SetFromUTCDateTime)
References dateTime2, EXPECT_EQ(), EXPECT_TRUE(), CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetSecond(), CDateTimeSpan::GetSecondsTotal(), CDateTime::GetTimezoneBias(), CDateTime::GetYear(), CDateTime::SetFromDBDateTime(), and CDateTime::SetFromUTCDateTime().
TEST_F() [20/24]
TEST_F (TestDateTime , SetFromW3CDate)
References EXPECT_EQ(), EXPECT_TRUE(), CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetSecond(), CDateTime::GetYear(), and CDateTime::SetFromW3CDate().
TEST_F() [21/24]
TEST_F (TestDateTime , SetFromW3CDateTime)
References dateTime2, EXPECT_EQ(), EXPECT_TRUE(), CDateTime::GetAsDBDate(), CDateTime::GetAsDBTime(), CDateTime::GetDay(), CDateTime::GetHour(), CDateTime::GetMinute(), CDateTime::GetMonth(), CDateTime::GetSecond(), CDateTime::GetTimezoneBias(), CDateTime::GetYear(), CDateTime::SetFromDBDateTime(), and CDateTime::SetFromW3CDateTime().
TEST_F() [22/24]
TEST_F (TestDateTime , SystemTimeOperators)
References dateTime2, EXPECT_TRUE(), and CDateTime::GetAsSystemTime().
TEST_F() [23/24]
TEST_F (TestDateTime , TimeTOperators)
References dateTime2, EXPECT_TRUE(), and CDateTime::GetAsTime().
TEST_F() [24/24]
TEST_F (TestDateTime , TmOperators)
References dateTime2, EXPECT_TRUE(), and CDateTime::GetAsTm().
Variable Documentation
dateTime2
CDateTime dateTime2
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().