Kodi Documentation: ProgressDialogHelper Class Reference
ProgressDialogHelper Class Reference
Public Types
enum wait_result { TimedOut , Canceled , Success }
Public Member Functions
ProgressDialogHelper (const std::string &heading)
~ProgressDialogHelper ()
bool HasDialog () const
wait_result ShowAndWait (const WaitCondition &waitObj, unsigned timeOutSec, const std::string &line1)
Private Attributes
CGUIDialogProgress * m_dialog = 0
Member Enumeration Documentation
wait_result
enum ProgressDialogHelper::wait_result
Enumerator
TimedOut
Canceled
Success
Constructor & Destructor Documentation
ProgressDialogHelper()
ProgressDialogHelper::ProgressDialogHelper (const std::string & heading) inline explicit
References CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::SetHeading(), and WINDOW_DIALOG_PROGRESS.
~ProgressDialogHelper()
ProgressDialogHelper::~ProgressDialogHelper () inline
Member Function Documentation
HasDialog()
bool ProgressDialogHelper::HasDialog () const inline
Referenced by CWakeOnAccess::WakeUpHost().
ShowAndWait()
wait_result ProgressDialogHelper::ShowAndWait (const WaitCondition & waitObj, unsigned timeOutSec, const std::string & line1) inline
References KODI::TIME::Sleep(), and WaitCondition::SuccessWaiting().
Referenced by CWakeOnAccess::WakeUpHost().
Member Data Documentation
m_dialog
CGUIDialogProgress* ProgressDialogHelper::m_dialog = 0 private
The documentation for this class was generated from the following file:
WakeOnAccess.cpp