Kodi Documentation: KODI::GAME::CGUICardinalFeatureButton Class Reference
KODI::GAME::CGUICardinalFeatureButton Class Reference
Games
#include <GUICardinalFeatureButton.h>
Public Member Functions
CGUICardinalFeatureButton (const CGUIButtonControl &buttonTemplate, IConfigurationWizard *wizard, const CPhysicalFeature &feature, unsigned int index)
~CGUICardinalFeatureButton () override=default
bool PromptForInput (CEvent &waitEvent) override
Prompt the user for a single input element.
bool IsFinished () const override
Check if the button supports further calls to PromptForInput()
INPUT::CARDINAL_DIRECTION GetCardinalDirection () const override
Get the direction of the next analog stick or relative pointer prompt.
void Reset () override
Reset button after prompting for input has finished.
Public Member Functions inherited from KODI::GAME::CGUIFeatureButton
CGUIFeatureButton (const CGUIButtonControl &buttonTemplate, IConfigurationWizard *wizard, const CPhysicalFeature &feature, unsigned int index)
~CGUIFeatureButton () override=default
void OnUnFocus () override
const CPhysicalFeature & Feature () const override
Get the feature represented by this button.
INPUT::CARDINAL_DIRECTION GetCardinalDirection () const override
Get the direction of the next analog stick or relative pointer prompt.
JOYSTICK::WHEEL_DIRECTION GetWheelDirection () const override
Get the direction of the next wheel prompt.
JOYSTICK::THROTTLE_DIRECTION GetThrottleDirection () const override
Get the direction of the next throttle prompt.
Public Member Functions inherited from CGUIButtonControl
CGUIButtonControl (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo &textureFocus, const CTextureInfo &textureNoFocus, const CLabelInfo &label, bool wrapMultiline=false)
CGUIButtonControl (const CGUIButtonControl &control)
~CGUIButtonControl () override=default
CGUIButtonControl * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
bool OnAction (const CAction &action) override
bool OnMessage (CGUIMessage &message) override
void AllocResources () override
void FreeResources (bool immediately=false) override
void DynamicResourceAlloc (bool bOnOff) override
void SetInvalid () override
void SetPosition (float posX, float posY) override
virtual void SetLabel (const std::string &aLabel)
virtual void SetLabel2 (const std::string &aLabel2)
void SetClickActions (const CGUIAction &clickActions)
const CGUIAction & GetClickActions () const
void SetFocusActions (const CGUIAction &focusActions)
void SetUnFocusActions (const CGUIAction &unfocusActions)
const CLabelInfo & GetLabelInfo () const
virtual std::string GetLabel () const
virtual std::string GetLabel2 () const
void SetSelected (bool bSelected)
std::string GetDescription () const override
float GetWidth () const override
virtual void SetMinWidth (float minWidth)
void SetAlpha (unsigned char alpha)
void PythonSetLabel (const std::string &strFont, const std::string &strText, KODI::UTILS::COLOR::Color textColor, KODI::UTILS::COLOR::Color shadowColor, KODI::UTILS::COLOR::Color focusedColor)
void PythonSetDisabledColor (KODI::UTILS::COLOR::Color disabledColor)
virtual void OnClick ()
bool HasClickActions () const
bool UpdateColors (const CGUIListItem *item) override
CRect CalcRenderRegion () const override
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual bool IsDynamicallyAllocated ()
virtual bool CanFocus () const
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetHeight () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Public Member Functions inherited from KODI::GAME::IFeatureButton
virtual ~IFeatureButton ()=default
virtual bool AllowWizard () const
Allow the wizard to include this feature in a list of buttons to map.
virtual bool NeedsKey () const
True if the button is waiting for a key press.
virtual void SetKey (const CPhysicalFeature &key)
Set the pressed key that the user will be prompted to map.
Private Types
enum class STATE {
CARDINAL_DIRECTION_UP , CARDINAL_DIRECTION_RIGHT , CARDINAL_DIRECTION_DOWN , CARDINAL_DIRECTION_LEFT ,
FINISHED
}
Private Attributes
STATE m_state
Additional Inherited Members
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Member Functions inherited from KODI::GAME::CGUIFeatureButton
bool DoPrompt (const std::string &strPrompt, const std::string &strWarn, const std::string &strFeature, CEvent &waitEvent)
template<typename T >
T GetNextState (T state)
Protected Member Functions inherited from CGUIButtonControl
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
void OnFocus () override
virtual void ProcessText (unsigned int currentTime)
virtual void RenderText ()
virtual CGUILabel::COLOR GetTextColor () const
void SetMaxWidth (float labelMaxWidth)
Set the maximum width for the left label.
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes inherited from KODI::GAME::CGUIFeatureButton
const CPhysicalFeature m_feature
Protected Attributes inherited from CGUIButtonControl
std::unique_ptr< CGUITexture > m_imgFocus
std::unique_ptr< CGUITexture > m_imgNoFocus
unsigned int m_focusCounter
unsigned char m_alpha
float m_minWidth
float m_maxWidth
float m_labelMaxWidth {0}
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_info
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_info2
CGUILabel m_label
CGUILabel m_label2
CGUIAction m_clickActions
CGUIAction m_focusActions
CGUIAction m_unfocusActions
bool m_bSelected
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Enumeration Documentation
STATE
enum class KODI::GAME::CGUICardinalFeatureButton::STATE strong private
Enumerator
CARDINAL_DIRECTION_UP
CARDINAL_DIRECTION_RIGHT
CARDINAL_DIRECTION_DOWN
CARDINAL_DIRECTION_LEFT
FINISHED
Constructor & Destructor Documentation
CGUICardinalFeatureButton()
CGUICardinalFeatureButton::CGUICardinalFeatureButton (const CGUIButtonControl & buttonTemplate, IConfigurationWizard * wizard, const CPhysicalFeature & feature, unsigned int index)
References Reset().
~CGUICardinalFeatureButton()
KODI::GAME::CGUICardinalFeatureButton::~CGUICardinalFeatureButton () override default
Member Function Documentation
GetCardinalDirection()
KODI::INPUT::CARDINAL_DIRECTION CGUICardinalFeatureButton::GetCardinalDirection () const override virtual
Get the direction of the next analog stick or relative pointer prompt.
Returns
The next direction to be prompted, or UNKNOWN if this isn't a cardinal feature or the prompt is finished
Implements KODI::GAME::IFeatureButton.
References CARDINAL_DIRECTION_DOWN, CARDINAL_DIRECTION_LEFT, CARDINAL_DIRECTION_RIGHT, CARDINAL_DIRECTION_UP, and m_state.
IsFinished()
bool CGUICardinalFeatureButton::IsFinished () const override virtual
Check if the button supports further calls to PromptForInput()
Returns
true if the button requires no more input elements from the user
Implements KODI::GAME::IFeatureButton.
References FINISHED, and m_state.
PromptForInput()
bool CGUICardinalFeatureButton::PromptForInput (CEvent & waitEvent) override virtual
Prompt the user for a single input element.
Parameters
waitEvent The event to block on while prompting for input
Returns
true if input was received (event fired), false if the prompt timed out
After the button has finished prompting the user for all the input elements it requires, this will return false until Reset() is called.
Implements KODI::GAME::IFeatureButton.
References CARDINAL_DIRECTION_DOWN, CARDINAL_DIRECTION_LEFT, CARDINAL_DIRECTION_RIGHT, CARDINAL_DIRECTION_UP, KODI::GAME::CGUIFeatureButton::DoPrompt(), FINISHED, g_localizeStrings, CLocalizeStrings::Get(), KODI::GAME::CGUIFeatureButton::GetNextState(), KODI::GAME::CPhysicalFeature::Label(), KODI::GAME::CGUIFeatureButton::m_feature, and m_state.
Reset()
void CGUICardinalFeatureButton::Reset () override virtual
Reset button after prompting for input has finished.
Implements KODI::GAME::IFeatureButton.
References CARDINAL_DIRECTION_UP, and m_state.
Referenced by CGUICardinalFeatureButton().
Member Data Documentation
m_state
STATE KODI::GAME::CGUICardinalFeatureButton::m_state private
Referenced by GetCardinalDirection(), IsFinished(), PromptForInput(), and Reset().
The documentation for this class was generated from the following files:
GUICardinalFeatureButton.h
GUICardinalFeatureButton.cpp