Kodi Documentation: XBMCAddon::xbmcgui::WindowXMLInterceptor Class Reference
XBMCAddon::xbmcgui::WindowXMLInterceptor Class Reference
Public Member Functions
WindowXMLInterceptor (WindowXML *_window, int windowid, const char *xmlfile)
void AllocResources (bool forceLoad=false) override
void FreeResources (bool forceUnLoad=false) override
bool OnClick (int iItem, const std::string &player="") override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
bool OnAction (const CAction &action) override
Public Member Functions inherited from XBMCAddon::xbmcgui::InterceptorDialog< CGUIMediaWindow >
InterceptorDialog (const char *specializedName, Window *_window, int windowid)
InterceptorDialog (const char *specializedName, Window *_window, int windowid, const char *xmlfile)
Public Member Functions inherited from XBMCAddon::xbmcgui::Interceptor< P >
Interceptor (const char *specializedName, Window *_window, int windowid)
Interceptor (const char *specializedName, Window *_window, int windowid, const char *xmlfile)
~Interceptor () override=default
bool OnMessage (CGUIMessage &message) override
bool OnAction (const CAction &action) override
bool OnBack (int actionId) override
void OnDeinitWindow (int nextWindowID) override
bool IsModalDialog () const override
bool IsDialogRunning () const override
bool IsDialog () const override
bool IsMediaWindow () const override
void SetRenderOrder (int renderOrder) override
void setActive (bool active) override
bool isActive () override
Public Member Functions inherited from XBMCAddon::xbmcgui::InterceptorBase
virtual ~InterceptorBase ()
Protected Member Functions
bool LoadXML (const std::string &strPath, const std::string &strPathLower) override
void GetContextButtons (int itemNumber, CContextButtons &buttons) override
bool Update (const std::string &strPath, bool) override
void SetupShares () override
Protected Member Functions inherited from XBMCAddon::xbmcgui::Interceptor< P >
CGUIWindow * get () override
Protected Member Functions inherited from XBMCAddon::xbmcgui::InterceptorBase
InterceptorBase ()
Private Attributes
WindowXML * xwin
Friends
class WindowXML
class WindowXMLDialog
Additional Inherited Members
Static Protected Member Functions inherited from XBMCAddon::xbmcgui::InterceptorBase
static bool up ()
Protected Attributes inherited from XBMCAddon::xbmcgui::InterceptorBase
AddonClass::Ref< Window > window
Static Protected Attributes inherited from XBMCAddon::xbmcgui::InterceptorBase
static thread_local ref * upcallTls
Detailed Description
Todo:
This should be done with template specialization
Constructor & Destructor Documentation
WindowXMLInterceptor()
XBMCAddon::xbmcgui::WindowXMLInterceptor::WindowXMLInterceptor (WindowXML * _window, int windowid, const char * xmlfile) inline
Member Function Documentation
AllocResources()
void XBMCAddon::xbmcgui::WindowXMLInterceptor::AllocResources (bool forceLoad = false) inline override
References CGUIControl::AllocResources(), checkedv, and XBMC_TRACE.
FreeResources()
void XBMCAddon::xbmcgui::WindowXMLInterceptor::FreeResources (bool forceUnLoad = false) inline override
References checkedv, CGUIControl::FreeResources(), and XBMC_TRACE.
GetContextButtons()
void XBMCAddon::xbmcgui::WindowXMLInterceptor::GetContextButtons (int itemNumber, CContextButtons & buttons) inline override protected
References XBMCAddon::xbmcgui::WindowXML::GetContextButtons(), CGUIMediaWindow::GetContextButtons(), and XBMC_TRACE.
LoadXML()
bool XBMCAddon::xbmcgui::WindowXMLInterceptor::LoadXML (const std::string & strPath, const std::string & strPathLower) inline override protected
References CGUIWindow::LoadXML(), XBMCAddon::xbmcgui::WindowXML::LoadXML(), and XBMC_TRACE.
OnAction()
bool XBMCAddon::xbmcgui::WindowXMLInterceptor::OnAction (const CAction & action) inline override
References checkedb, CGUIWindow::OnAction(), and XBMC_TRACE.
OnClick()
bool XBMCAddon::xbmcgui::WindowXMLInterceptor::OnClick (int iItem, const std::string & player = "") inline override
References checkedb, CGUIMediaWindow::OnClick(), OnClick(), and XBMC_TRACE.
Referenced by OnClick().
Process()
void XBMCAddon::xbmcgui::WindowXMLInterceptor::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) inline override
References checkedv, CGUIControl::Process(), and XBMC_TRACE.
SetupShares()
void XBMCAddon::xbmcgui::WindowXMLInterceptor::SetupShares () inline override protected
References checkedv, CGUIMediaWindow::SetupShares(), SetupShares(), and XBMC_TRACE.
Referenced by SetupShares().
Update()
bool XBMCAddon::xbmcgui::WindowXMLInterceptor::Update (const std::string & strPath, bool) inline override protected
References CGUIMediaWindow::Update(), XBMCAddon::xbmcgui::WindowXML::Update(), and XBMC_TRACE.
Friends And Related Symbol Documentation
WindowXML
friend class WindowXML friend
WindowXMLDialog
friend class WindowXMLDialog friend
Member Data Documentation
xwin
WindowXML* XBMCAddon::xbmcgui::WindowXMLInterceptor::xwin private
The documentation for this class was generated from the following file:
WindowXML.cpp