Kodi Documentation: Shaders::CGLSLShaderProgram Class Reference
Shaders::CGLSLShaderProgram Class Reference
#include <Shader.h>
Public Member Functions
CGLSLShaderProgram ()
CGLSLShaderProgram (const std::string &vert, const std::string &frag)
~CGLSLShaderProgram () override
bool Enable () override
void Disable () override
bool CompileAndLink () override
Public Member Functions inherited from Shaders::CShaderProgram
CShaderProgram ()=default
virtual ~CShaderProgram ()
bool OK () const
CVertexShader * VertexShader ()
CPixelShader * PixelShader ()
virtual void OnCompiledAndLinked ()
virtual bool OnEnabled ()
virtual void OnDisabled ()
virtual GLuint ProgramHandle ()
Protected Member Functions
void Free ()
Protected Attributes
GLint m_lastProgram
bool m_validated = false
Protected Attributes inherited from Shaders::CShaderProgram
CVertexShader * m_pVP = nullptr
CPixelShader * m_pFP = nullptr
GLuint m_shaderProgram = 0
bool m_ok = false
Constructor & Destructor Documentation
CGLSLShaderProgram() [1/2]
CGLSLShaderProgram::CGLSLShaderProgram ()
References Shaders::CShaderProgram::m_pFP, and Shaders::CShaderProgram::m_pVP.
CGLSLShaderProgram() [2/2]
CGLSLShaderProgram::CGLSLShaderProgram (const std::string & vert, const std::string & frag)
References Shaders::CShader::LoadSource(), Shaders::CShaderProgram::m_pFP, and Shaders::CShaderProgram::m_pVP.
~CGLSLShaderProgram()
CGLSLShaderProgram::~CGLSLShaderProgram () override
References Free().
Member Function Documentation
CompileAndLink()
bool CGLSLShaderProgram::CompileAndLink () override virtual
Implements Shaders::CShaderProgram.
References Shaders::CShader::Compile(), Free(), Shaders::CVertexShader::Free(), Shaders::CShader::GetName(), Shaders::CShader::GetSourceWithLineNumbers(), GLchar, Shaders::CVertexShader::Handle(), Shaders::CPixelShader::Handle(), log(), CLog::Log(), LOG_SIZE, LOGDEBUG, LOGERROR, Shaders::CShaderProgram::m_ok, Shaders::CShaderProgram::m_pFP, Shaders::CShaderProgram::m_pVP, Shaders::CShaderProgram::m_shaderProgram, m_validated, Shaders::CShaderProgram::OnCompiledAndLinked(), and VerifyGLState.
Referenced by CLinuxRendererGL::LoadShaders(), CLinuxRendererGLES::LoadShaders(), CLinuxRendererGL::UpdateVideoFilter(), and CLinuxRendererGLES::UpdateVideoFilter().
Disable()
void CGLSLShaderProgram::Disable () override virtual
Implements Shaders::CShaderProgram.
References Shaders::CShaderProgram::OK(), and Shaders::CShaderProgram::OnDisabled().
Referenced by CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGLES::RenderFromFBO(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGLES::RenderSinglePass(), CLinuxRendererGL::RenderSinglePass(), CLinuxRendererGLES::RenderToFBO(), and CLinuxRendererGL::RenderToFBO().
Enable()
bool CGLSLShaderProgram::Enable () override virtual
Implements Shaders::CShaderProgram.
References GLchar, log(), CLog::Log(), LOG_SIZE, LOGERROR, Shaders::CShaderProgram::m_shaderProgram, m_validated, Shaders::CShaderProgram::OK(), Shaders::CShaderProgram::OnEnabled(), and VerifyGLState.
Referenced by CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGLES::RenderFromFBO(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGLES::RenderSinglePass(), CLinuxRendererGL::RenderSinglePass(), CLinuxRendererGLES::RenderToFBO(), and CLinuxRendererGL::RenderToFBO().
Free()
void CGLSLShaderProgram::Free () protected
References Shaders::CVertexShader::Free(), Shaders::CPixelShader::Free(), m_lastProgram, Shaders::CShaderProgram::m_ok, Shaders::CShaderProgram::m_pFP, Shaders::CShaderProgram::m_pVP, Shaders::CShaderProgram::m_shaderProgram, and VerifyGLState.
Referenced by CompileAndLink(), Shaders::GL::ConvolutionFilterShader::Free(), Shaders::GLES::ConvolutionFilterShader::Free(), CGLShader::Free(), CGLESShader::Free(), Shaders::GL::BaseVideoFilterShader::~BaseVideoFilterShader(), and ~CGLSLShaderProgram().
Member Data Documentation
m_lastProgram
GLint Shaders::CGLSLShaderProgram::m_lastProgram protected
Referenced by Free().
m_validated
bool Shaders::CGLSLShaderProgram::m_validated = false protected
Referenced by CompileAndLink(), and Enable().
The documentation for this class was generated from the following files:
guilib/Shader.h
Shader.cpp