Kodi Documentation: KODI::MOUSE::CMouseInputHandling Class Reference
KODI::MOUSE::CMouseInputHandling Class Reference
Input » Mouse
Class to translate input from driver info to higher-level features.
#include <MouseInputHandling.h>
Public Member Functions
CMouseInputHandling (IMouseInputHandler *handler, JOYSTICK::IButtonMap *buttonMap)
~CMouseInputHandling (void) override=default
bool OnPosition (int x, int y) override
Handle mouse position updates.
bool OnButtonPress (BUTTON_ID button) override
A mouse button has been pressed.
void OnButtonRelease (BUTTON_ID button) override
A mouse button has been released.
Public Member Functions inherited from KODI::MOUSE::IMouseDriverHandler
virtual ~IMouseDriverHandler (void)=default
Static Private Member Functions
static POINTER_DIRECTION GetPointerDirection (int x, int y)
static POINTER_DIRECTION GetOrthogonalDirectionCCW (POINTER_DIRECTION direction)
static void GetRotation (POINTER_DIRECTION source, POINTER_DIRECTION target, int(&rotation)[2][2])
static void GetRotation (int deg, int(&rotation)[2][2])
static void GetReflectionCCW (POINTER_DIRECTION source, POINTER_DIRECTION target, int(&reflection)[2][2])
static void GetReflection (int deg, int(&reflection)[2][2])
Private Attributes
IMouseInputHandler *const m_handler
JOYSTICK::IButtonMap *const m_buttonMap
bool m_bHasPosition = false
int m_x = 0
int m_y = 0
Detailed Description
Class to translate input from driver info to higher-level features.
Constructor & Destructor Documentation
CMouseInputHandling()
CMouseInputHandling::CMouseInputHandling (IMouseInputHandler * handler, JOYSTICK::IButtonMap * buttonMap)
~CMouseInputHandling()
KODI::MOUSE::CMouseInputHandling::~CMouseInputHandling (void) override default
Member Function Documentation
GetOrthogonalDirectionCCW()
POINTER_DIRECTION CMouseInputHandling::GetOrthogonalDirectionCCW (POINTER_DIRECTION direction) static private
Referenced by OnPosition().
GetPointerDirection()
POINTER_DIRECTION CMouseInputHandling::GetPointerDirection (int x, int y) static private
Referenced by OnPosition().
GetReflection()
void CMouseInputHandling::GetReflection (int deg, int(&) reflection[2][2]) static private
Referenced by GetReflectionCCW().
GetReflectionCCW()
void CMouseInputHandling::GetReflectionCCW (POINTER_DIRECTION source, POINTER_DIRECTION target, int(&) reflection[2][2]) static private
References GetReflection().
Referenced by OnPosition().
GetRotation() [1/2]
void CMouseInputHandling::GetRotation (int deg, int(&) rotation[2][2]) static private
GetRotation() [2/2]
void CMouseInputHandling::GetRotation (POINTER_DIRECTION source, POINTER_DIRECTION target, int(&) rotation[2][2]) static private
References GetRotation().
Referenced by GetRotation(), and OnPosition().
OnButtonPress()
bool CMouseInputHandling::OnButtonPress (BUTTON_ID button) override virtual
A mouse button has been pressed.
Parameters
button The index of the pressed button
Returns
True if the event was handled, otherwise false
Implements KODI::MOUSE::IMouseDriverHandler.
References KODI::JOYSTICK::IButtonMap::GetFeature(), m_buttonMap, m_handler, KODI::MOUSE::IMouseInputHandler::OnButtonPress(), and KODI::MOUSE::IMouseInputHandler::OnInputFrame().
OnButtonRelease()
void CMouseInputHandling::OnButtonRelease (BUTTON_ID button) override virtual
A mouse button has been released.
Parameters
button The index of the released button
Implements KODI::MOUSE::IMouseDriverHandler.
References KODI::JOYSTICK::IButtonMap::GetFeature(), m_buttonMap, m_handler, KODI::MOUSE::IMouseInputHandler::OnButtonRelease(), and KODI::MOUSE::IMouseInputHandler::OnInputFrame().
OnPosition()
bool CMouseInputHandling::OnPosition (int x, int y) override virtual
Handle mouse position updates.
Parameters
x The new x coordinate of the pointer
y The new y coordinate of the pointer
The mouse uses a left-handed (graphics) cartesian coordinate system. Positive X is right, positive Y is down.
Returns
True if the event was handled, false otherwise
Implements KODI::MOUSE::IMouseDriverHandler.
References KODI::JOYSTICK::IButtonMap::GetFeature(), GetOrthogonalDirectionCCW(), GetPointerDirection(), GetReflectionCCW(), KODI::JOYSTICK::IButtonMap::GetRelativePointer(), GetRotation(), m_bHasPosition, m_buttonMap, m_handler, m_x, m_y, KODI::MOUSE::IMouseInputHandler::OnInputFrame(), and KODI::MOUSE::IMouseInputHandler::OnMotion().
Member Data Documentation
m_bHasPosition
bool KODI::MOUSE::CMouseInputHandling::m_bHasPosition = false private
Referenced by OnPosition().
m_buttonMap
JOYSTICK::IButtonMap* const KODI::MOUSE::CMouseInputHandling::m_buttonMap private
Referenced by OnButtonPress(), OnButtonRelease(), and OnPosition().
m_handler
IMouseInputHandler* const KODI::MOUSE::CMouseInputHandling::m_handler private
Referenced by OnButtonPress(), OnButtonRelease(), and OnPosition().
m_x
int KODI::MOUSE::CMouseInputHandling::m_x = 0 private
Referenced by OnPosition().
m_y
int KODI::MOUSE::CMouseInputHandling::m_y = 0 private
Referenced by OnPosition().
The documentation for this class was generated from the following files:
MouseInputHandling.h
MouseInputHandling.cpp