Kodi Documentation: IPlayerCallback Class Reference
IPlayerCallback Class Reference abstract
#include <IPlayerCallback.h>
Public Member Functions
virtual ~IPlayerCallback ()=default
virtual void OnPlayBackEnded ()=0
virtual void OnPlayBackStarted (const CFileItem &file)=0
virtual void OnPlayerCloseFile (const CFileItem &file, const CBookmark &bookmark)
virtual void OnPlayBackPaused ()
virtual void OnPlayBackResumed ()
virtual void OnPlayBackStopped ()=0
virtual void OnPlayBackError ()=0
virtual void OnQueueNextItem ()=0
virtual void OnPlayBackSeek (int64_t iTime, int64_t seekOffset)
virtual void OnPlayBackSeekChapter (int iChapter)
virtual void OnPlayBackSpeedChanged (int iSpeed)
virtual void OnAVChange ()
virtual void OnAVStarted (const CFileItem &file)
virtual void RequestVideoSettings (const CFileItem &fileItem)
virtual void StoreVideoSettings (const CFileItem &fileItem, const CVideoSettings &vs)
Constructor & Destructor Documentation
~IPlayerCallback()
virtual IPlayerCallback::~IPlayerCallback () virtual default
Member Function Documentation
OnAVChange()
virtual void IPlayerCallback::OnAVChange () inline virtual
Reimplemented in CApplicationPlayerCallback, and XBPython.
Referenced by CVideoPlayer::HandleMessages().
OnAVStarted()
virtual void IPlayerCallback::OnAVStarted (const CFileItem & file) inline virtual
Reimplemented in CApplicationPlayerCallback, and XBPython.
Referenced by PAPlayer::AdvancePlaylistOnError(), CVideoPlayer::HandlePlaySpeed(), KODI::RETRO::CRetroPlayer::OpenFile(), UPNP::CUPnPPlayer::OpenFile(), CExternalPlayer::Process(), and PAPlayer::ProcessStream().
OnPlayBackEnded()
virtual void IPlayerCallback::OnPlayBackEnded () pure virtual
Implemented in CApplicationPlayerCallback, and XBPython.
Referenced by KODI::RETRO::CRetroPlayer::CloseFile(), PAPlayer::OnExit(), CVideoPlayer::OnExit(), UPNP::CUPnPPlayer::OnExit(), CExternalPlayer::Process(), and UPNP::CUPnPPlayer::Process().
OnPlayBackError()
virtual void IPlayerCallback::OnPlayBackError () pure virtual
Implemented in CApplicationPlayerCallback, and XBPython.
Referenced by CVideoPlayer::OnExit().
OnPlayBackPaused()
virtual void IPlayerCallback::OnPlayBackPaused () inline virtual
Reimplemented in CApplicationPlayerCallback, and XBPython.
Referenced by UPNP::CUPnPPlayer::Pause(), UPNP::CUPnPPlayer::Process(), KODI::RETRO::CRetroPlayer::SetSpeed(), CVideoPlayer::SetSpeed(), and PAPlayer::SetSpeed().
OnPlayBackResumed()
virtual void IPlayerCallback::OnPlayBackResumed () inline virtual
Reimplemented in CApplicationPlayerCallback, and XBPython.
Referenced by CVideoPlayer::OnAction(), UPNP::CUPnPPlayer::Pause(), UPNP::CUPnPPlayer::Process(), KODI::RETRO::CRetroPlayer::SetSpeed(), CVideoPlayer::SetSpeed(), PAPlayer::SetSpeed(), and UPNP::CUPnPPlayer::SetSpeed().
OnPlayBackSeek()
virtual void IPlayerCallback::OnPlayBackSeek (int64_t iTime, int64_t seekOffset) inline virtual
Reimplemented in CApplicationPlayerCallback, and XBPython.
Referenced by CVideoPlayer::Seek(), CVideoPlayer::SeekTime(), PAPlayer::SeekTime(), and CVideoPlayer::SeekTimeRelative().
OnPlayBackSeekChapter()
virtual void IPlayerCallback::OnPlayBackSeekChapter (int iChapter) inline virtual
Reimplemented in CApplicationPlayerCallback, and XBPython.
Referenced by CVideoPlayer::HandleMessages().
OnPlayBackSpeedChanged()
virtual void IPlayerCallback::OnPlayBackSpeedChanged (int iSpeed) inline virtual
Reimplemented in CApplicationPlayerCallback, and XBPython.
Referenced by CVideoPlayer::HandleMessages(), and PAPlayer::Process().
OnPlayBackStarted()
virtual void IPlayerCallback::OnPlayBackStarted (const CFileItem & file) pure virtual
Implemented in CApplicationPlayerCallback, and XBPython.
Referenced by PAPlayer::AdvancePlaylistOnError(), CVideoPlayer::HandleMessages(), PAPlayer::OpenFile(), KODI::RETRO::CRetroPlayer::OpenFile(), CVideoPlayer::OpenFile(), UPNP::CUPnPPlayer::OpenFile(), CExternalPlayer::Process(), and PAPlayer::ProcessStream().
OnPlayBackStopped()
virtual void IPlayerCallback::OnPlayBackStopped () pure virtual
Implemented in CApplicationPlayerCallback, and XBPython.
Referenced by UPNP::CUPnPPlayer::CloseFile(), PAPlayer::OnExit(), CVideoPlayer::OnExit(), and CExternalPlayer::Process().
OnPlayerCloseFile()
virtual void IPlayerCallback::OnPlayerCloseFile (const CFileItem & file, const CBookmark & bookmark) inline virtual
Reimplemented in CApplicationPlayerCallback.
Referenced by PAPlayer::CloseFileCB(), CVideoPlayer::HandleMessages(), CVideoPlayer::OnExit(), and CExternalPlayer::Process().
OnQueueNextItem()
virtual void IPlayerCallback::OnQueueNextItem () pure virtual
Implemented in CApplicationPlayerCallback, and XBPython.
Referenced by PAPlayer::ProcessStreams(), and PAPlayer::QueueNextFileEx().
RequestVideoSettings()
virtual void IPlayerCallback::RequestVideoSettings (const CFileItem & fileItem) inline virtual
Reimplemented in CApplicationPlayerCallback.
Referenced by CVideoPlayer::Prepare().
StoreVideoSettings()
virtual void IPlayerCallback::StoreVideoSettings (const CFileItem & fileItem, const CVideoSettings & vs) inline virtual
Reimplemented in CApplicationPlayerCallback.
Referenced by CVideoPlayer::HandleMessages(), and CVideoPlayer::OnExit().
The documentation for this class was generated from the following file:
IPlayerCallback.h