Kodi Documentation: CAddonVideoCodec Class Reference
CAddonVideoCodec Class Reference
#include <AddonVideoCodec.h>
Public Member Functions
CAddonVideoCodec (CProcessInfo &processInfo, ADDON::AddonInfoPtr &addonInfo, KODI_HANDLE parentInstance)
~CAddonVideoCodec () override
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
bool Reconfigure (CDVDStreamInfo &hints) override
bool AddData (const DemuxPacket &packet) override
void Reset () override
VCReturn GetPicture (VideoPicture *pVideoPicture) override
const char * GetName () override
void SetCodecControl (int flags) override
Public Member Functions inherited from CDVDVideoCodec
CDVDVideoCodec (CProcessInfo &processInfo)
virtual ~CDVDVideoCodec ()=default
virtual void SetSpeed (int iSpeed)
virtual unsigned GetConvergeCount ()
virtual unsigned GetAllowedReferences ()
virtual bool GetCodecStats (double &pts, int &droppedFrames, int &skippedPics)
virtual void Reopen ()
Public Member Functions inherited from ADDON::IAddonInstanceHandler
IAddonInstanceHandler (ADDON_TYPE type, const AddonInfoPtr &addonInfo, AddonInstanceId instanceId=ADDON_INSTANCE_ID_UNUSED, KODI_HANDLE parentInstance=nullptr, const std::string &uniqueWorkID="")
Class constructor for handling add-on instance processes, allowing an add-on to handle multiple work simultaneously and independently.
virtual ~IAddonInstanceHandler ()
ADDON_TYPE UsedType () const
AddonInstanceId InstanceId () const
const std::string & UniqueWorkID ()
std::string ID () const
AddonInstanceId InstanceID () const
std::string Name () const
std::string Author () const
std::string Icon () const
std::string Path () const
std::string Profile () const
CAddonVersion Version () const
ADDON_STATUS CreateInstance ()
void DestroyInstance ()
const AddonDllPtr & Addon () const
AddonInfoPtr GetAddonInfo () const
virtual void OnPreInstall ()
virtual void OnPostInstall (bool update, bool modal)
virtual void OnPreUnInstall ()
virtual void OnPostUnInstall ()
Private Member Functions
bool CopyToInitData (VIDEOCODEC_INITDATA &initData, CDVDStreamInfo &hints)
bool GetFrameBuffer (VIDEOCODEC_PICTURE &picture)
All picture members can be expected to be set correctly except decodedData and pts. GetFrameBuffer has to set decodedData to a valid memory address and return true. In case buffer allocation fails, return false.
void ReleaseFrameBuffer (KODI_HANDLE videoBufferHandle)
Static Private Member Functions
static bool get_frame_buffer (void *kodiInstance, VIDEOCODEC_PICTURE *picture)
static void release_frame_buffer (void *kodiInstance, KODI_HANDLE videoBufferHandle)
Private Attributes
int m_codecFlags = 0
VIDEOCODEC_FORMAT m_formats [VIDEOCODEC_FORMAT_MAXFORMATS+1]
float m_displayAspect = 0.0f
unsigned int m_width
unsigned int m_height
Additional Inherited Members
Public Types inherited from CDVDVideoCodec
enum VCReturn {
VC_NONE = 0 , VC_ERROR , VC_FATAL , VC_BUFFER ,
VC_PICTURE , VC_FLUSHED , VC_NOBUFFER , VC_REOPEN ,
VC_EOF
}
Protected Attributes inherited from CDVDVideoCodec
CProcessInfo & m_processInfo
Protected Attributes inherited from ADDON::IAddonInstanceHandler
KODI_ADDON_INSTANCE_INFO m_info {}
KODI_ADDON_INSTANCE_STRUCT m_ifc {}
Constructor & Destructor Documentation
CAddonVideoCodec()
CAddonVideoCodec::CAddonVideoCodec (CProcessInfo & processInfo, ADDON::AddonInfoPtr & addonInfo, KODI_HANDLE parentInstance)
References ADDON_STATUS_OK, ADDON::IAddonInstanceHandler::CreateInstance(), get_frame_buffer(), AddonToKodiFuncTable_VideoCodec::get_frame_buffer, AddonToKodiFuncTable_VideoCodec::kodiInstance, CLog::Log(), LOGERROR, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VideoCodec::props, release_frame_buffer(), AddonToKodiFuncTable_VideoCodec::release_frame_buffer, AddonInstance_VideoCodec::toAddon, AddonInstance_VideoCodec::toKodi, and KODI_ADDON_INSTANCE_STRUCT::videocodec.
~CAddonVideoCodec()
CAddonVideoCodec::~CAddonVideoCodec () override
References ADDON::IAddonInstanceHandler::DestroyInstance(), ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VideoCodec::props, Reset(), AddonInstance_VideoCodec::toAddon, AddonInstance_VideoCodec::toKodi, and KODI_ADDON_INSTANCE_STRUCT::videocodec.
Member Function Documentation
AddData()
bool CAddonVideoCodec::AddData (const DemuxPacket & packet) override virtual
add data, decoder has to consume the entire packet returns true if the packet was consumed or if resubmitting it is useless
Implements CDVDVideoCodec.
References ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VideoCodec::toAddon, and KODI_ADDON_INSTANCE_STRUCT::videocodec.
CopyToInitData()
bool CAddonVideoCodec::CopyToInitData (VIDEOCODEC_INITDATA & initData, CDVDStreamInfo & hints) private
References CDVDStreamInfo::aspect, AV1CodecProfileHigh, AV1CodecProfileMain, AV1CodecProfileProfessional, VIDEOCODEC_INITDATA::codec, CDVDStreamInfo::codec, VIDEOCODEC_INITDATA::codecProfile, CodecProfileNotNeeded, CodecProfileUnknown, CRYPTO_SESSION_SYSTEM_CLEARKEY, CRYPTO_SESSION_SYSTEM_NONE, CRYPTO_SESSION_SYSTEM_PLAYREADY, CRYPTO_SESSION_SYSTEM_WIDEVINE, CRYPTO_SESSION_SYSTEM_WISEPLAY, VIDEOCODEC_INITDATA::cryptoSession, CDVDStreamInfo::cryptoSession, VIDEOCODEC_INITDATA::extraData, CDVDStreamInfo::extradata, VIDEOCODEC_INITDATA::extraDataSize, CDVDStreamInfo::forced_aspect, CDVDStreamInfo::fpsrate, CDVDStreamInfo::fpsscale, FFmpegExtraData::GetData(), FFmpegExtraData::GetSize(), H264CodecProfileBaseline, H264CodecProfileExtended, H264CodecProfileHigh, H264CodecProfileHigh10, H264CodecProfileHigh422, H264CodecProfileHigh444Predictive, H264CodecProfileMain, VIDEOCODEC_INITDATA::height, CDVDStreamInfo::height, STREAM_CRYPTO_SESSION::keySystem, m_displayAspect, m_formats, m_height, CDVDVideoCodec::m_processInfo, m_width, CDVDStreamInfo::profile, STREAM_CRYPTO_SESSION::sessionId, CProcessInfo::SetVideoDAR(), CProcessInfo::SetVideoDimensions(), CProcessInfo::SetVideoFps(), STREAM_CRYPTO_KEY_SYSTEM_CLEARKEY, STREAM_CRYPTO_KEY_SYSTEM_NONE, STREAM_CRYPTO_KEY_SYSTEM_PLAYREADY, STREAM_CRYPTO_KEY_SYSTEM_WIDEVINE, STREAM_CRYPTO_KEY_SYSTEM_WISEPLAY, VIDEOCODEC_AV1, VIDEOCODEC_H264, VIDEOCODEC_VP8, VIDEOCODEC_VP9, VIDEOCODEC_INITDATA::videoFormats, VP9CodecProfile0, VP9CodecProfile1, VP9CodecProfile2, VP9CodecProfile3, VIDEOCODEC_INITDATA::width, and CDVDStreamInfo::width.
Referenced by Open(), and Reconfigure().
get_frame_buffer()
bool CAddonVideoCodec::get_frame_buffer (void * kodiInstance, VIDEOCODEC_PICTURE * picture) static private
References GetFrameBuffer().
Referenced by CAddonVideoCodec().
GetFrameBuffer()
bool CAddonVideoCodec::GetFrameBuffer (VIDEOCODEC_PICTURE & picture) private
All picture members can be expected to be set correctly except decodedData and pts. GetFrameBuffer has to set decodedData to a valid memory address and return true. In case buffer allocation fails, return false.
References VIDEOCODEC_PICTURE::decodedData, VIDEOCODEC_PICTURE::decodedDataSize, CVideoBufferManager::Get(), CVideoBuffer::GetMemPtr(), CProcessInfo::GetVideoBufferManager(), CLog::Log(), LOGERROR, CDVDVideoCodec::m_processInfo, and VIDEOCODEC_PICTURE::videoBufferHandle.
Referenced by get_frame_buffer().
GetName()
const char * CAddonVideoCodec::GetName () override virtual
should return codecs name
Implements CDVDVideoCodec.
References KodiToAddonFuncTable_VideoCodec::get_name(), ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VideoCodec::toAddon, and KODI_ADDON_INSTANCE_STRUCT::videocodec.
Referenced by Open().
GetPicture()
CDVDVideoCodec::VCReturn CAddonVideoCodec::GetPicture (VideoPicture * pVideoPicture) override virtual
GetPicture controls decoding. Player calls it on every cycle it can signal a picture, request a buffer, or return none, if nothing applies the data is valid until the next GetPicture return VC_PICTURE
Implements CDVDVideoCodec.
References VideoPicture::chroma_position, VideoPicture::color_primaries, VideoPicture::color_range, VideoPicture::color_space, VideoPicture::color_transfer, VideoPicture::colorBits, VIDEOCODEC_PICTURE::decodedData, VIDEOCODEC_PICTURE::decodedDataSize, VideoPicture::dts, DVD_CODEC_CTRL_DRAIN, DVD_CODEC_CTRL_DROP, DVD_NOPTS_VALUE, DVP_FLAG_DROPPED, VIDEOCODEC_PICTURE::flags, VideoPicture::hasDisplayMetadata, VideoPicture::hasLightMetadata, VIDEOCODEC_PICTURE::height, VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iDuration, VideoPicture::iFlags, VideoPicture::iFrameType, VideoPicture::iHeight, VideoPicture::iRepeatPicture, VideoPicture::iWidth, CLog::Log(), LOGDEBUG, LOGINFO, LOGVIDEO, m_codecFlags, m_displayAspect, m_height, ADDON::IAddonInstanceHandler::m_ifc, CDVDVideoCodec::m_processInfo, m_width, YuvImage::MAX_PLANES, VideoPicture::pict_type, VIDEOCODEC_PICTURE::planeOffsets, VIDEOCODEC_PICTURE::pts, VideoPicture::pts, VideoPicture::qp_table, VideoPicture::qscale_type, VideoPicture::qstride, CVideoBuffer::Release(), CVideoBuffer::SetDimensions(), CVideoBuffer::SetPixelFormat(), CProcessInfo::SetVideoDimensions(), VideoPicture::stereoMode, VIDEOCODEC_PICTURE::stride, AddonInstance_VideoCodec::toAddon, VC_BUFFER, CDVDVideoCodec::VC_BUFFER, VC_EOF, CDVDVideoCodec::VC_EOF, VC_ERROR, CDVDVideoCodec::VC_ERROR, VC_NONE, CDVDVideoCodec::VC_NONE, VC_PICTURE, CDVDVideoCodec::VC_PICTURE, VideoPicture::videoBuffer, VIDEOCODEC_PICTURE::videoBufferHandle, KODI_ADDON_INSTANCE_STRUCT::videocodec, VIDEOCODEC_PICTURE_FLAG_DRAIN, VIDEOCODEC_PICTURE_FLAG_DROP, VIDEOCODEC_PICTURE::videoFormat, and VIDEOCODEC_PICTURE::width.
Open()
bool CAddonVideoCodec::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Open the decoder, returns true on success Decoders not capable of running multiple instances should return false in case there is already a instance open
Implements CDVDVideoCodec.
References CopyToInitData(), GetName(), m_formats, ADDON::IAddonInstanceHandler::m_ifc, CDVDVideoCodec::m_processInfo, CProcessInfo::SetVideoDecoderName(), AddonInstance_VideoCodec::toAddon, KODI_ADDON_INSTANCE_STRUCT::videocodec, VIDEOCODEC_FORMAT_UNKNOWN, and VIDEOCODEC_FORMAT_YV12.
Reconfigure()
bool CAddonVideoCodec::Reconfigure (CDVDStreamInfo & hints) override virtual
Reconfigure the decoder, returns true on success Decoders not capable of running multiple instances may be capable of reconfiguring the running instance. If Reconfigure returns false, player will close / open the decoder
Reimplemented from CDVDVideoCodec.
References CopyToInitData(), ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_VideoCodec::toAddon, and KODI_ADDON_INSTANCE_STRUCT::videocodec.
release_frame_buffer()
void CAddonVideoCodec::release_frame_buffer (void * kodiInstance, KODI_HANDLE videoBufferHandle) static private
References ReleaseFrameBuffer().
Referenced by CAddonVideoCodec().
ReleaseFrameBuffer()
void CAddonVideoCodec::ReleaseFrameBuffer (KODI_HANDLE videoBufferHandle) private
Referenced by release_frame_buffer().
Reset()
void CAddonVideoCodec::Reset () override virtual
Reset the decoder. Should be the same as calling Dispose and Open after each other
Implements CDVDVideoCodec.
References VIDEOCODEC_PICTURE::flags, CLog::Log(), LOGDEBUG, ADDON::IAddonInstanceHandler::m_ifc, CVideoBuffer::Release(), AddonInstance_VideoCodec::toAddon, VC_EOF, VC_PICTURE, VIDEOCODEC_PICTURE::videoBufferHandle, KODI_ADDON_INSTANCE_STRUCT::videocodec, and VIDEOCODEC_PICTURE_FLAG_DRAIN.
Referenced by ~CAddonVideoCodec().
SetCodecControl()
void CAddonVideoCodec::SetCodecControl (int flags) inline override virtual
Codec can be informed by player with the following flags:
DVD_CODEC_CTRL_NO_POSTPROC : if speed is not normal the codec can switch off postprocessing and de-interlacing
DVD_CODEC_CTRL_HURRY : codecs may do postprocessing and de-interlacing. If video buffers in RenderManager are about to run dry, this is signaled to codec. Codec can wait for post-proc to be finished instead of returning empty and getting another packet.
DVD_CODEC_CTRL_DRAIN : instruct decoder to deliver last pictures without requesting new packets
DVD_CODEC_CTRL_DROP : this packet is going to be dropped. decoder is free to use it for decoding
Reimplemented from CDVDVideoCodec.
References m_codecFlags.
Member Data Documentation
m_codecFlags
int CAddonVideoCodec::m_codecFlags = 0 private
Referenced by GetPicture(), and SetCodecControl().
m_displayAspect
float CAddonVideoCodec::m_displayAspect = 0.0f private
Referenced by CopyToInitData(), and GetPicture().
m_formats
VIDEOCODEC_FORMAT CAddonVideoCodec::m_formats[VIDEOCODEC_FORMAT_MAXFORMATS+1] private
Referenced by CopyToInitData(), and Open().
m_height
unsigned int CAddonVideoCodec::m_height private
Referenced by CopyToInitData(), and GetPicture().
m_width
unsigned int CAddonVideoCodec::m_width private
Referenced by CopyToInitData(), and GetPicture().
The documentation for this class was generated from the following files:
AddonVideoCodec.h
AddonVideoCodec.cpp