Kodi Documentation: KODI::GAME::CGUIDialogAxisDetection Class Reference
KODI::GAME::CGUIDialogAxisDetection Class Reference
Games
#include <GUIDialogAxisDetection.h>
Public Member Functions
CGUIDialogAxisDetection ()=default
~CGUIDialogAxisDetection () override=default
bool AcceptsPrimitive (JOYSTICK::PRIMITIVE_TYPE type) const override
Return true if the button mapper accepts primitives of the given type.
void OnLateAxis (const JOYSTICK::IButtonMap *buttonMap, unsigned int axisIndex) override
Called when an axis has been detected after mapping began.
Public Member Functions inherited from KODI::GAME::CGUIDialogButtonCapture
CGUIDialogButtonCapture ()
~CGUIDialogButtonCapture () override=default
std::string ControllerID () const override
The add-on ID of the game controller associated with this button mapper.
bool NeedsCooldown () const override
Return true if the button mapper wants a cooldown between button mapping commands.
bool MapPrimitive (JOYSTICK::IButtonMap *buttonMap, KEYMAP::IKeymap *keymap, const JOYSTICK::CDriverPrimitive &primitive) override
Handle button/hat press or axis threshold.
void OnEventFrame (const JOYSTICK::IButtonMap *buttonMap, bool bMotion) override
Called once per event frame to notify the implementation of motion status.
void OnLateAxis (const JOYSTICK::IButtonMap *buttonMap, unsigned int axisIndex) override
Called when an axis has been detected after mapping began.
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
void Show ()
Show the dialog.
Public Member Functions inherited from KODI::JOYSTICK::IButtonMapper
IButtonMapper ()=default
virtual ~IButtonMapper ()=default
void SetButtonMapCallback (const std::string &deviceLocation, IButtonMapCallback *callback)
void ResetButtonMapCallbacks (void)
std::map< std::string, IButtonMapCallback * > & ButtonMapCallbacks (void)
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Protected Member Functions
std::string GetDialogText () override
std::string GetDialogHeader () override
bool MapPrimitiveInternal (JOYSTICK::IButtonMap *buttonMap, KEYMAP::IKeymap *keymap, const JOYSTICK::CDriverPrimitive &primitive) override
void OnClose (bool bAccepted) override
Protected Member Functions inherited from KODI::GAME::CGUIDialogButtonCapture
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Types
using DeviceName = std::string
using AxisIndex = unsigned int
using AxisEntry = std::pair< DeviceName, AxisIndex >
using AxisVector = std::vector< AxisEntry >
Private Member Functions
void AddAxis (const std::string &deviceLocation, unsigned int axisIndex)
Private Attributes
AxisVector m_detectedAxes
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Attributes inherited from KODI::GAME::CGUIDialogButtonCapture
CEvent m_captureEvent
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Member Typedef Documentation
AxisEntry
using KODI::GAME::CGUIDialogAxisDetection::AxisEntry = std::pair<DeviceName, AxisIndex> private
AxisIndex
using KODI::GAME::CGUIDialogAxisDetection::AxisIndex = unsigned int private
AxisVector
using KODI::GAME::CGUIDialogAxisDetection::AxisVector = std::vector<AxisEntry> private
DeviceName
using KODI::GAME::CGUIDialogAxisDetection::DeviceName = std::string private
Constructor & Destructor Documentation
CGUIDialogAxisDetection()
KODI::GAME::CGUIDialogAxisDetection::CGUIDialogAxisDetection () default
~CGUIDialogAxisDetection()
KODI::GAME::CGUIDialogAxisDetection::~CGUIDialogAxisDetection () override default
Member Function Documentation
AcceptsPrimitive()
bool CGUIDialogAxisDetection::AcceptsPrimitive (JOYSTICK::PRIMITIVE_TYPE type) const override virtual
Return true if the button mapper accepts primitives of the given type.
Parameters
type The primitive type
Returns
True if the button mapper can map the primitive type, false otherwise
Implements KODI::JOYSTICK::IButtonMapper.
References KODI::JOYSTICK::SEMIAXIS.
AddAxis()
void CGUIDialogAxisDetection::AddAxis (const std::string & deviceLocation, unsigned int axisIndex) private
References KODI::GAME::CGUIDialogButtonCapture::m_captureEvent, m_detectedAxes, and CEvent::Set().
Referenced by MapPrimitiveInternal(), and OnLateAxis().
GetDialogHeader()
std::string CGUIDialogAxisDetection::GetDialogHeader () override protected virtual
Implements KODI::GAME::CGUIDialogButtonCapture.
References g_localizeStrings, and CLocalizeStrings::Get().
GetDialogText()
std::string CGUIDialogAxisDetection::GetDialogText () override protected virtual
Implements KODI::GAME::CGUIDialogButtonCapture.
References g_localizeStrings, CLocalizeStrings::Get(), KODI::JOYSTICK::CJoystickTranslator::GetPrimitiveName(), m_detectedAxes, and KODI::JOYSTICK::POSITIVE.
MapPrimitiveInternal()
bool CGUIDialogAxisDetection::MapPrimitiveInternal (JOYSTICK::IButtonMap * buttonMap, KEYMAP::IKeymap * keymap, const JOYSTICK::CDriverPrimitive & primitive) override protected virtual
Implements KODI::GAME::CGUIDialogButtonCapture.
References AddAxis(), KODI::JOYSTICK::CDriverPrimitive::Index(), KODI::JOYSTICK::IButtonMap::Location(), KODI::JOYSTICK::SEMIAXIS, and KODI::JOYSTICK::CDriverPrimitive::Type().
OnClose()
void KODI::GAME::CGUIDialogAxisDetection::OnClose (bool bAccepted) inline override protected virtual
Implements KODI::GAME::CGUIDialogButtonCapture.
OnLateAxis()
void CGUIDialogAxisDetection::OnLateAxis (const JOYSTICK::IButtonMap * buttonMap, unsigned int axisIndex) override virtual
Called when an axis has been detected after mapping began.
Parameters
axisIndex The index of the axis being discovered
Some joystick drivers don't report an initial value for analog axes.
Called in the same thread as IButtonMapper::MapPrimitive.
Implements KODI::JOYSTICK::IButtonMapper.
References AddAxis(), and KODI::JOYSTICK::IButtonMap::Location().
Member Data Documentation
m_detectedAxes
AxisVector KODI::GAME::CGUIDialogAxisDetection::m_detectedAxes private
Referenced by AddAxis(), and GetDialogText().
The documentation for this class was generated from the following files:
GUIDialogAxisDetection.h
GUIDialogAxisDetection.cpp