Kodi Documentation: ADDON::CAddonRepos Class Reference
ADDON::CAddonRepos Class Reference
#include <AddonRepos.h>
Public Member Functions
CAddonRepos ()
CAddonRepos (const std::string &addonId)
CAddonRepos (const std::shared_ptr< IAddon > &repoAddon)
void BuildUpdateOrOutdatedList (const std::vector< std::shared_ptr< IAddon > > &installed, std::vector< std::shared_ptr< IAddon > > &result, AddonCheckType addonCheckType) const
Build the list of addons to be updated depending on defined rules or the list of outdated addons.
void BuildAddonsWithUpdateList (const std::vector< std::shared_ptr< IAddon > > &installed, std::map< std::string, AddonWithUpdate > &addonsWithUpdate) const
Build the list of outdated addons and their available updates.
bool DoAddonUpdateCheck (const std::shared_ptr< IAddon > &addon, std::shared_ptr< IAddon > &update) const
Check if an update is available for a single addon.
bool GetLatestAddonVersionFromAllRepos (const std::string &addonId, std::shared_ptr< IAddon > &addon) const
Retrieves the latest version of an addon from all installed repositories follows addon origin restriction rules.
void GetLatestAddonVersions (std::vector< std::shared_ptr< IAddon > > &addonList) const
Retrieves the latest official versions of addons to vector. Private versions are added obeying updateMode. (either OFFICIAL_ONLY or ANY_REPOSITORY)
void GetLatestAddonVersionsFromAllRepos (std::vector< std::shared_ptr< IAddon > > &addonList) const
Retrieves the latest official versions of addons to vector. Private versions (latest per repository) are added obeying updateMode. (either OFFICIAL_ONLY or ANY_REPOSITORY)
bool FindDependency (const std::string &dependsId, const std::string &parentRepoId, std::shared_ptr< IAddon > &dependencyToInstall, std::shared_ptr< CRepository > &repoForDep) const
Find a dependency to install during an addon install or update If the dependency cannot be found in official versions we look in the installing/updating addon's (the parent's) origin repository.
bool FindDependencyByParentRepo (const std::string &dependsId, const std::string &parentRepoId, std::shared_ptr< IAddon > &dependencyToInstall) const
Find a dependency addon in the repository of its parent.
void BuildCompatibleVersionsList (std::vector< std::shared_ptr< IAddon > > &compatibleVersions) const
Build compatible versions list based on the contents of m_allAddons.
bool IsValid () const
Return whether add-ons repo/version information was properly loaded after construction.
Static Public Member Functions
static bool IsFromOfficialRepo (const std::shared_ptr< IAddon > &addon, CheckAddonPath checkAddonPath)
Checks if the origin-repository of a given addon is defined as official repo and can also verify if the origin-path (e.g. https://mirrors.kodi.tv ...) is matching.
static bool IsOfficialRepo (const std::string &repoId)
Checks if the passed in repository is defined as official repo which includes ORIGIN_SYSTEM.
Private Member Functions
bool LoadAddonsFromDatabase (const std::string &addonId, const std::shared_ptr< IAddon > &repoAddon)
Load and configure add-on maps.
bool FindAddonAndCheckForUpdate (const std::shared_ptr< IAddon > &addonToCheck, const std::map< std::string, std::shared_ptr< IAddon > > &map, std::shared_ptr< IAddon > &update) const
Looks up an addon in a given repository map and checks if an update is available.
void AddAddonIfLatest (const std::shared_ptr< IAddon > &addonToAdd, std::map< std::string, std::shared_ptr< IAddon > > &map) const
Adds the latest version of an addon to the desired map.
void AddAddonIfLatest (const std::string &repoId, const std::shared_ptr< IAddon > &addonToAdd, std::map< std::string, std::map< std::string, std::shared_ptr< IAddon > > > &map) const
Adds the latest version of an addon to the desired map per repository used to populate 'latestVersionsByRepo'.
bool GetLatestVersionByMap (const std::string &addonId, const std::map< std::string, std::shared_ptr< IAddon > > &map, std::shared_ptr< IAddon > &addon) const
Looks up an addon entry in a specific map.
Private Attributes
const CAddonMgr & m_addonMgr
CAddonDatabase m_addonDb
bool m_valid {false}
std::vector< std::shared_ptr< IAddon > > m_allAddons
std::map< std::string, std::shared_ptr< IAddon > > m_latestOfficialVersions
std::map< std::string, std::shared_ptr< IAddon > > m_latestPrivateVersions
std::map< std::string, std::map< std::string, std::shared_ptr< IAddon > > > m_latestVersionsByRepo
std::map< std::string, std::multimap< std::string, std::shared_ptr< IAddon > > > m_addonsByRepoMap
Detailed Description
Class - CAddonRepos Reads information about installed official/third party repos and their contained add-ons from the database. Used to check for updates for installed add-ons and dependencies while obeying permission rules. Note that this class is not responsible for refreshing the repo data stored in the database.
Constructor & Destructor Documentation
CAddonRepos() [1/3]
CAddonRepos::CAddonRepos ()
References LoadAddonsFromDatabase(), m_addonDb, m_valid, and ADDON::CAddonDatabase::Open().
CAddonRepos() [2/3]
CAddonRepos::CAddonRepos (const std::string & addonId) explicit
References LoadAddonsFromDatabase(), m_addonDb, m_valid, and ADDON::CAddonDatabase::Open().
CAddonRepos() [3/3]
CAddonRepos::CAddonRepos (const std::shared_ptr< IAddon > & repoAddon) explicit
References LoadAddonsFromDatabase(), m_addonDb, m_valid, and ADDON::CAddonDatabase::Open().
Member Function Documentation
AddAddonIfLatest() [1/2]
void CAddonRepos::AddAddonIfLatest (const std::shared_ptr< IAddon > & addonToAdd, std::map< std::string, std::shared_ptr< IAddon > > & map) const private
Adds the latest version of an addon to the desired map.
Parameters
addonToAdd the addon whose latest version should be added
map target map, e.g. latestOfficialVersions or latestPrivateVersions
Referenced by LoadAddonsFromDatabase().
AddAddonIfLatest() [2/2]
void CAddonRepos::AddAddonIfLatest (const std::string & repoId, const std::shared_ptr< IAddon > & addonToAdd, std::map< std::string, std::map< std::string, std::shared_ptr< IAddon > > > & map) const private
Adds the latest version of an addon to the desired map per repository used to populate 'latestVersionsByRepo'.
Parameters
repoId the repository that addon comes from
addonToAdd the addon whose latest version should be added
map target map, latestVersionsByRepo
BuildAddonsWithUpdateList()
void CAddonRepos::BuildAddonsWithUpdateList (const std::vector< std::shared_ptr< IAddon > > & installed, std::map< std::string, AddonWithUpdate > & addonsWithUpdate) const
Build the list of outdated addons and their available updates.
Parameters
installed vector of all addons installed on the system that are checked for an update
[out] addonsWithUpdate target map
References DoAddonUpdateCheck(), LOGADDONS, and LOGDEBUG.
Referenced by ADDON::CAddonMgr::GetAddonsWithAvailableUpdate().
BuildCompatibleVersionsList()
void CAddonRepos::BuildCompatibleVersionsList (std::vector< std::shared_ptr< IAddon > > & compatibleVersions) const
Build compatible versions list based on the contents of m_allAddons.
Note
content of m_allAddons depends on the preceding call to LoadAddonsFromDatabase()
Parameters
[out] compatibleVersions target vector to be filled
References ADDON::CHOICE_YES, ADDON::CAddonMgr::IsCompatible(), IsFromOfficialRepo(), m_addonMgr, and m_allAddons.
Referenced by ADDON::CAddonMgr::GetCompatibleVersions().
BuildUpdateOrOutdatedList()
void CAddonRepos::BuildUpdateOrOutdatedList (const std::vector< std::shared_ptr< IAddon > > & installed, std::vector< std::shared_ptr< IAddon > > & result, AddonCheckType addonCheckType) const
Build the list of addons to be updated depending on defined rules or the list of outdated addons.
Parameters
installed vector of all addons installed on the system that are checked for an update
[in] addonCheckType build list of OUTDATED or UPDATES
[out] result list of addon versions that are going to be installed or are outdated
References DoAddonUpdateCheck(), LOGADDONS, LOGDEBUG, and ADDON::OUTDATED_ADDONS.
Referenced by ADDON::CAddonMgr::GetAvailableUpdatesOrOutdatedAddons().
DoAddonUpdateCheck()
bool CAddonRepos::DoAddonUpdateCheck (const std::shared_ptr< IAddon > & addon, std::shared_ptr< IAddon > & update) const
Check if an update is available for a single addon.
Parameters
addon that is checked for an update
[out] update pointer to the found update
Returns
true if an installable update was found, false otherwise
References ADDON::ANY_REPOSITORY, ADDON::CHOICE_NO, FindAddonAndCheckForUpdate(), ADDON::CAddonSystemSettings::GetAddonRepoUpdateMode(), ADDON::CAddonSystemSettings::GetInstance(), IsFromOfficialRepo(), LOGADDONS, LOGDEBUG, m_latestOfficialVersions, m_latestPrivateVersions, m_latestVersionsByRepo, and ADDON::ORIGIN_SYSTEM.
Referenced by BuildAddonsWithUpdateList(), BuildUpdateOrOutdatedList(), and ADDON::CAddonMgr::FindInstallableById().
FindAddonAndCheckForUpdate()
bool CAddonRepos::FindAddonAndCheckForUpdate (const std::shared_ptr< IAddon > & addonToCheck, const std::map< std::string, std::shared_ptr< IAddon > > & map, std::shared_ptr< IAddon > & update) const private
Looks up an addon in a given repository map and checks if an update is available.
Parameters
addonToCheck the addon we want to find and version check
map the repository map we want to check against
[out] pointer to the found update. if the addon is up-to-date on our system, this param will return 'nullptr'
Returns
true if the addon was found in the desired map and its version is newer than our local version. false if the addon does NOT exist in the map or it is up to date.
References ADDON::INCOMPATIBLE, ADDON::CAddonMgr::IsAddonDisabledWithReason(), and m_addonMgr.
Referenced by DoAddonUpdateCheck().
FindDependency()
bool CAddonRepos::FindDependency (const std::string & dependsId, const std::string & parentRepoId, std::shared_ptr< IAddon > & dependencyToInstall, std::shared_ptr< CRepository > & repoForDep) const
Find a dependency to install during an addon install or update If the dependency cannot be found in official versions we look in the installing/updating addon's (the parent's) origin repository.
Parameters
dependsId addon id of the dependency we're looking for
parentRepoId origin repository of the dependee
[out] dependencyToInstall pointer to the found dependency, only use if function returns true
[out] repoForDep the repository that dependency will install from finally
Returns
true if the dependency was found, false otherwise
References ADDON::ANY_REPOSITORY, ADDON::CHOICE_YES, FindDependencyByParentRepo(), ADDON::CAddonMgr::GetAddon(), ADDON::CAddonSystemSettings::GetAddonRepoUpdateMode(), ADDON::CAddonSystemSettings::GetInstance(), GetLatestVersionByMap(), LOGADDONS, LOGDEBUG, m_addonMgr, m_latestOfficialVersions, m_latestPrivateVersions, and ADDON::REPOSITORY.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install().
FindDependencyByParentRepo()
bool CAddonRepos::FindDependencyByParentRepo (const std::string & dependsId, const std::string & parentRepoId, std::shared_ptr< IAddon > & dependencyToInstall) const
Find a dependency addon in the repository of its parent.
Parameters
dependsId addon id of the dependency we're looking for
parentRepoId origin repository of the dependee
[out] dependencyToInstall pointer to the found dependency, only use if function returns true
Returns
true if the dependency was found, false otherwise
References GetLatestVersionByMap(), and m_latestVersionsByRepo.
Referenced by FindDependency().
GetLatestAddonVersionFromAllRepos()
bool CAddonRepos::GetLatestAddonVersionFromAllRepos (const std::string & addonId, std::shared_ptr< IAddon > & addon) const
Retrieves the latest version of an addon from all installed repositories follows addon origin restriction rules.
Parameters
addonId addon id we're looking the latest version for
[out] addon pointer to the found addon
Returns
true if a version was found, false otherwise
References ADDON::ANY_REPOSITORY, ADDON::CAddonSystemSettings::GetAddonRepoUpdateMode(), ADDON::CAddonSystemSettings::GetInstance(), GetLatestVersionByMap(), m_latestOfficialVersions, and m_latestPrivateVersions.
Referenced by ADDON::CAddonMgr::FindInstallableById().
GetLatestAddonVersions()
void CAddonRepos::GetLatestAddonVersions (std::vector< std::shared_ptr< IAddon > > & addonList) const
Retrieves the latest official versions of addons to vector. Private versions are added obeying updateMode. (either OFFICIAL_ONLY or ANY_REPOSITORY)
Parameters
[out] addonList retrieved addon list in a vector
References ADDON::ANY_REPOSITORY, ADDON::CAddonSystemSettings::GetAddonRepoUpdateMode(), ADDON::CAddonSystemSettings::GetInstance(), m_latestOfficialVersions, and m_latestPrivateVersions.
Referenced by XFILE::Browse(), and ADDON::CAddonMgr::GetInstallableAddons().
GetLatestAddonVersionsFromAllRepos()
void CAddonRepos::GetLatestAddonVersionsFromAllRepos (std::vector< std::shared_ptr< IAddon > > & addonList) const
Retrieves the latest official versions of addons to vector. Private versions (latest per repository) are added obeying updateMode. (either OFFICIAL_ONLY or ANY_REPOSITORY)
Parameters
[out] addonList retrieved addon list in a vector
References ADDON::ANY_REPOSITORY, ADDON::CAddonSystemSettings::GetAddonRepoUpdateMode(), ADDON::CAddonSystemSettings::GetInstance(), m_latestOfficialVersions, m_latestVersionsByRepo, and officialRepoInfos.
Referenced by XFILE::Browse().
GetLatestVersionByMap()
bool CAddonRepos::GetLatestVersionByMap (const std::string & addonId, const std::map< std::string, std::shared_ptr< IAddon > > & map, std::shared_ptr< IAddon > & addon) const private
Looks up an addon entry in a specific map.
Parameters
addonId addon we want to retrieve
map the map we're looking into for the wanted addon
[out] addon pointer to the found addon, only use when function returns true
Returns
true if the addon was found in the map, false otherwise
Referenced by FindDependency(), FindDependencyByParentRepo(), and GetLatestAddonVersionFromAllRepos().
IsFromOfficialRepo()
bool CAddonRepos::IsFromOfficialRepo (const std::shared_ptr< IAddon > & addon, CheckAddonPath checkAddonPath) static
Checks if the origin-repository of a given addon is defined as official repo and can also verify if the origin-path (e.g. https://mirrors.kodi.tv ...) is matching.
Note
if this function is called on locally installed add-ons, for instance when populating 'My add-ons', the local installation path is returned as origin. thus parameter CheckAddonPath::CHOICE_NO needs to be passed in such cases
Parameters
addon pointer to addon to be checked
checkAddonPath also check origin path
Returns
true if the repository id of a given addon is defined as official and the addons origin matches the defined official origin of the repo id
References ADDON::CHOICE_YES, officialRepoInfos, and ADDON::ORIGIN_SYSTEM.
Referenced by BuildCompatibleVersionsList(), CGUIDialogAddonInfo::BuildDependencyList(), DoAddonUpdateCheck(), XFILE::CAddonsDirectory::GenerateAddonListing(), LoadAddonsFromDatabase(), and CGUIDialogAddonInfo::ShowDependencyList().
IsOfficialRepo()
bool CAddonRepos::IsOfficialRepo (const std::string & repoId) static
Checks if the passed in repository is defined as official repo which includes ORIGIN_SYSTEM.
Parameters
repoId repository id to check
Returns
true if the repository id is defined as official, false otherwise
References officialRepoInfos, and ADDON::ORIGIN_SYSTEM.
Referenced by ADDON::CAddonMgr::IsAddonInstalled(), and ADDON::CAddonMgr::IsAddonInstalled().
IsValid()
bool ADDON::CAddonRepos::IsValid () const inline
Return whether add-ons repo/version information was properly loaded after construction.
Returns
true on success, false otherwise
References m_valid.
Referenced by XFILE::Browse(), ADDON::CAddonMgr::FindInstallableById(), ADDON::CAddonMgr::GetAddonsWithAvailableUpdate(), ADDON::CAddonMgr::GetAvailableUpdatesOrOutdatedAddons(), ADDON::CAddonMgr::GetCompatibleVersions(), ADDON::CAddonMgr::GetInstallableAddons(), and anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install().
LoadAddonsFromDatabase()
bool CAddonRepos::LoadAddonsFromDatabase (const std::string & addonId, const std::shared_ptr< IAddon > & repoAddon) private
Load and configure add-on maps.
Returns
true on success, false otherwise
References AddAddonIfLatest(), ADDON::CRepositoryUpdater::Await(), ADDON::CRepositoryUpdater::CheckForUpdates(), ADDON::CHOICE_YES, ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonDatabase::GetRepositoryContent(), CServiceBroker::GetRepositoryUpdater(), ADDON::CAddonMgr::IsCompatible(), IsFromOfficialRepo(), LOGADDONS, LOGDEBUG, m_addonDb, m_addonMgr, m_addonsByRepoMap, m_allAddons, m_latestOfficialVersions, m_latestPrivateVersions, m_latestVersionsByRepo, and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by CAddonRepos(), CAddonRepos(), and CAddonRepos().
Member Data Documentation
m_addonDb
CAddonDatabase ADDON::CAddonRepos::m_addonDb private
Referenced by CAddonRepos(), CAddonRepos(), CAddonRepos(), and LoadAddonsFromDatabase().
m_addonMgr
const CAddonMgr& ADDON::CAddonRepos::m_addonMgr private
Referenced by BuildCompatibleVersionsList(), FindAddonAndCheckForUpdate(), FindDependency(), and LoadAddonsFromDatabase().
m_addonsByRepoMap
std::map<std::string, std::multimap<std::string, std::shared_ptr<IAddon> > > ADDON::CAddonRepos::m_addonsByRepoMap private
Referenced by LoadAddonsFromDatabase().
m_allAddons
std::vector<std::shared_ptr<IAddon> > ADDON::CAddonRepos::m_allAddons private
Referenced by BuildCompatibleVersionsList(), and LoadAddonsFromDatabase().
m_latestOfficialVersions
std::map<std::string, std::shared_ptr<IAddon> > ADDON::CAddonRepos::m_latestOfficialVersions private
Referenced by DoAddonUpdateCheck(), FindDependency(), GetLatestAddonVersionFromAllRepos(), GetLatestAddonVersions(), GetLatestAddonVersionsFromAllRepos(), and LoadAddonsFromDatabase().
m_latestPrivateVersions
std::map<std::string, std::shared_ptr<IAddon> > ADDON::CAddonRepos::m_latestPrivateVersions private
Referenced by DoAddonUpdateCheck(), FindDependency(), GetLatestAddonVersionFromAllRepos(), GetLatestAddonVersions(), and LoadAddonsFromDatabase().
m_latestVersionsByRepo
std::map<std::string, std::map<std::string, std::shared_ptr<IAddon> > > ADDON::CAddonRepos::m_latestVersionsByRepo private
Referenced by DoAddonUpdateCheck(), FindDependencyByParentRepo(), GetLatestAddonVersionsFromAllRepos(), and LoadAddonsFromDatabase().
m_valid
bool ADDON::CAddonRepos::m_valid {false} private
Referenced by CAddonRepos(), CAddonRepos(), CAddonRepos(), and IsValid().
The documentation for this class was generated from the following files:
AddonRepos.h
AddonRepos.cpp