Kodi Documentation: CInputCodingTableKorean Class Reference
CInputCodingTableKorean Class Reference
#include <InputCodingTableKorean.h>
Public Member Functions
CInputCodingTableKorean ()
~CInputCodingTableKorean () override=default
bool GetWordListPage (const std::string &strCode, bool isFirstPage) override
std::vector< std::wstring > GetResponse (int) override
void SetTextPrev (const std::string &strTextPrev) override
std::string ConvertString (const std::string &strCode) override
int GetType () override
Public Member Functions inherited from IInputCodingTable
virtual ~IInputCodingTable ()=default
virtual void Initialize ()
Called for the active keyboard layout when it's loaded, stick any initialization here.
virtual void Deinitialize ()
Called for the active keyboard layout when it's unloaded, stick any cleanup here.
virtual bool IsInitialized () const
Can be overridden if initialization is expensive to avoid calling initialize more than needed.
const std::string & GetCodeChars () const
Protected Member Functions
int MergeCode (int choseong, int jungseong, int jongseong)
std::wstring InputToKorean (const std::wstring &input)
Private Attributes
std::vector< std::wstring > m_words
std::string m_strTextPrev
Additional Inherited Members
Public Types inherited from IInputCodingTable
enum { TYPE_WORD_LIST , TYPE_CONVERT_STRING }
Protected Attributes inherited from IInputCodingTable
std::string m_codechars
Constructor & Destructor Documentation
CInputCodingTableKorean()
CInputCodingTableKorean::CInputCodingTableKorean () default
~CInputCodingTableKorean()
CInputCodingTableKorean::~CInputCodingTableKorean () override default
Member Function Documentation
ConvertString()
std::string CInputCodingTableKorean::ConvertString (const std::string & strCode) override virtual
Reimplemented from IInputCodingTable.
References g_charsetConverter, InputToKorean(), and m_strTextPrev.
GetResponse()
std::vector< std::wstring > CInputCodingTableKorean::GetResponse (int) override virtual
Implements IInputCodingTable.
References m_words.
GetType()
int CInputCodingTableKorean::GetType () inline override virtual
Reimplemented from IInputCodingTable.
References IInputCodingTable::TYPE_CONVERT_STRING.
GetWordListPage()
bool CInputCodingTableKorean::GetWordListPage (const std::string & strCode, bool isFirstPage) override virtual
Implements IInputCodingTable.
InputToKorean()
std::wstring CInputCodingTableKorean::InputToKorean (const std::wstring & input) protected
References MergeCode().
Referenced by ConvertString().
MergeCode()
int CInputCodingTableKorean::MergeCode (int choseong, int jungseong, int jongseong) protected
Referenced by InputToKorean().
SetTextPrev()
void CInputCodingTableKorean::SetTextPrev (const std::string & strTextPrev) override virtual
Reimplemented from IInputCodingTable.
References m_strTextPrev.
Member Data Documentation
m_strTextPrev
std::string CInputCodingTableKorean::m_strTextPrev private
Referenced by ConvertString(), and SetTextPrev().
m_words
std::vector<std::wstring> CInputCodingTableKorean::m_words private
Referenced by GetResponse().
The documentation for this class was generated from the following files:
InputCodingTableKorean.h
InputCodingTableKorean.cpp