Kodi Documentation: CWinSystemWin32 Class Reference
CWinSystemWin32 Class Reference abstract
#include <WinSystemWin32.h>
Public Member Functions
CWinSystemWin32 ()
virtual ~CWinSystemWin32 ()
bool InitWindowSystem () override
bool DestroyWindowSystem () override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
void FinishWindowResize (int newWidth, int newHeight) override
void ForceFullScreen (const RESOLUTION_INFO &resInfo) override
Forces the window to fullscreen provided the window resolution.
void UpdateResolutions () override
bool CenterWindow () override
virtual void NotifyAppFocusChange (bool bGaining) override
void ShowOSMouse (bool show) override
bool HasInertialGestures () override
bool Minimize () override
bool Restore () override
bool Hide () override
bool Show (bool raise=true) override
std::string GetClipboardText () override
bool UseLimitedColor () override
float GetGuiSdrPeakLuminance () const override
Max luminance for GUI SDR content in HDR mode.
bool HasSystemSdrPeakLuminance () override
Test support of the OS for a SDR max luminance in HDR mode setting.
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
std::vector< std::string > GetConnectedOutputs () override
HWND GetHwnd () const
bool IsAlteringWindow () const
void SetAlteringWindow (bool altering)
bool IsTogglingHDR () const
void SetTogglingHDR (bool toggling)
virtual bool DPIChanged (WORD dpi, RECT windowRect) const
bool IsMinimized () const
void SetMinimized (bool minimized)
void CacheSystemSdrPeakLuminance ()
Cache the system HDR/SDR balance for use during rendering, instead of querying the API for each frame.
void SetSizeMoveMode (bool mode)
bool IsInSizeMoveMode () const
bool MessagePump () override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual CRenderSystemBase * GetRenderSystem ()
virtual const std::string GetName ()
virtual bool DestroyWindow ()
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual bool IsCreated ()
virtual void NotifyAppActiveChange (bool bActivated)
virtual bool HasCursor ()
virtual int NoOfBuffers ()
virtual float GetDisplayLatency ()
Get average display latency.
virtual float GetFrameLatencyAdjustment ()
Get time that should be subtracted from the display latency for this frame in milliseconds.
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
virtual bool CanDoWindowed ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual bool SetHDR (const VideoPicture *videoPicture)
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
virtual bool IsHDRDisplay ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual CHDRCapabilities GetDisplayHDRCapabilities () const
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
virtual bool BindTextureUploadContext ()
Binds a shared context to the current thread, in order to upload textures asynchronously.
virtual bool UnbindTextureUploadContext ()
Unbinds the shared context.
virtual bool HasContext ()
Checks if a graphics context is already bound to the current thread.
Protected Member Functions
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override=0
virtual void UpdateStates (bool fullScreen)
WINDOW_STATE GetState (bool fullScreen) const
virtual void SetDeviceFullScreen (bool fullScreen, RESOLUTION_INFO &res)=0
virtual void ReleaseBackBuffer ()=0
virtual void CreateBackBuffer ()=0
virtual void ResizeDeviceBuffers ()=0
virtual bool IsStereoEnabled ()=0
virtual void OnScreenChange (HMONITOR monitor)=0
virtual void AdjustWindow (bool forceResize=false)
void CenterCursor () const
virtual void Register (IDispResource *resource)
virtual void Unregister (IDispResource *resource)
virtual bool ChangeResolution (const RESOLUTION_INFO &res, bool forceChange=false)
virtual bool CreateBlankWindows ()
virtual bool BlankNonActiveMonitors (bool bBlank)
MONITOR_DETAILS * GetDisplayDetails (const std::string &name)
MONITOR_DETAILS * GetDisplayDetails (HMONITOR handle)
void RestoreDesktopResolution (MONITOR_DETAILS *details)
RECT ScreenRect (HMONITOR handle)
void GetConnectedDisplays (std::vector< MONITOR_DETAILS > &outputs)
void OnDisplayLost ()
void OnDisplayReset ()
void OnDisplayBack ()
void ResolutionChanged ()
RECT GetScreenWorkArea (HMONITOR handle) const
RECT GetNcAreaOffsets (DWORD dwStyle, BOOL bMenu, DWORD dwExStyle) const
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
virtual std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl ()
Static Protected Member Functions
static bool AddResolution (const RESOLUTION_INFO &res)
Adds a resolution to the list of resolutions if we don't already have it.
static void SetForegroundWindowInternal (HWND hWnd)
static RECT GetVirtualScreenRect ()
Protected Attributes
HWND m_hWnd
HMONITOR m_hMonitor
std::vector< HWND > m_hBlankWindows
HINSTANCE m_hInstance
HICON m_hIcon
bool m_ValidWindowedPosition
bool m_IsAlteringWindow
bool m_IsTogglingHDR {false}
CCriticalSection m_resourceSection
std::vector< IDispResource * > m_resources
bool m_delayDispReset
XbmcThreads::EndTime m_dispResetTimer
WINDOW_STATE m_state
WINDOW_FULLSCREEN_STATE m_fullscreenState
WINDOW_WINDOW_STATE m_windowState
DWORD m_windowStyle
DWORD m_windowExStyle
bool m_inFocus
bool m_bMinimized
bool m_bSizeMoveEnabled = false
bool m_bFirstResChange = true
std::unique_ptr< CIRServerSuite > m_irss
std::vector< MONITOR_DETAILS > m_displays
NOTIFYICONDATA m_trayIcon = {}
bool m_validSystemSdrPeakLuminance {false}
float m_systemSdrPeakLuminance {.0f}
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Static Protected Attributes
static const char * SETTING_WINDOW_TOP = "window.top"
static const char * SETTING_WINDOW_LEFT = "window.left"
Additional Inherited Members
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Constructor & Destructor Documentation
CWinSystemWin32()
CWinSystemWin32::CWinSystemWin32 ()
References AE::CAESinkFactory::ClearSinks(), XFILE::CFile::Exists(), CEnvironment::getenv(), CServiceBroker::GetSettingsComponent(), CWinSystemBase::m_dpms, m_irss, CWinSystemBase::m_winEvents, CAESinkDirectSound::Register(), CAESinkWASAPI::Register(), CAESinkXAudio::Register(), CScreenshotSurfaceWindows::Register(), CEnvironment::setenv(), and CSpecialProtocol::TranslatePath().
~CWinSystemWin32()
CWinSystemWin32::~CWinSystemWin32 () virtual
References m_hIcon.
Member Function Documentation
AddResolution()
bool CWinSystemWin32::AddResolution (const RESOLUTION_INFO & res) static protected
Adds a resolution to the list of resolutions if we don't already have it.
Parameters
res resolution to add.
References CDisplaySettings::AddResolutionInfo(), RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fRefreshRate, CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iWidth, RES_CUSTOM, and CDisplaySettings::ResolutionInfoSize().
Referenced by UpdateResolutions().
AdjustWindow()
void CWinSystemWin32::AdjustWindow (bool forceResize = false) protected virtual
References GetLastError(), GetNcAreaOffsets(), GetScreenWorkArea(), CServiceBroker::GetSettingsComponent(), GetVirtualScreenRect(), left, LOGDEBUG, LOGERROR, m_hMonitor, m_hWnd, CWinSystemBase::m_nHeight, CWinSystemBase::m_nLeft, CWinSystemBase::m_nTop, CWinSystemBase::m_nWidth, m_state, m_ValidWindowedPosition, m_windowExStyle, m_windowStyle, ScreenRect(), SetLastError(), SETTING_WINDOW_LEFT, SETTING_WINDOW_TOP, CWinSystemBase::SetWindowResolution(), WINDOW_STATE_FULLSCREEN, and WINDOW_STATE_FULLSCREEN_WINDOW.
Referenced by CreateNewWindow(), ResizeWindow(), and SetFullScreen().
BlankNonActiveMonitors()
bool CWinSystemWin32::BlankNonActiveMonitors (bool bBlank) protected virtual
References MONITOR_DETAILS::hMonitor, m_displays, m_hBlankWindows, m_hMonitor, m_hWnd, and ScreenRect().
Referenced by SetFullScreen().
CacheSystemSdrPeakLuminance()
void CWinSystemWin32::CacheSystemSdrPeakLuminance ()
Cache the system HDR/SDR balance for use during rendering, instead of querying the API for each frame.
References MONITOR_DETAILS::DeviceNameW, GetDisplayDetails(), CWIN32Util::GetSystemSdrWhiteLevel(), m_hMonitor, m_systemSdrPeakLuminance, and m_validSystemSdrPeakLuminance.
CenterCursor()
void CWinSystemWin32::CenterCursor () const protected
References m_hWnd.
Referenced by SetFullScreen().
CenterWindow()
bool CWinSystemWin32::CenterWindow () override virtual
Reimplemented from CWinSystemBase.
References CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, m_hWnd, CWinSystemBase::m_nHeight, CWinSystemBase::m_nLeft, CWinSystemBase::m_nTop, CWinSystemBase::m_nWidth, and RES_DESKTOP.
ChangeResolution()
bool CWinSystemWin32::ChangeResolution (const RESOLUTION_INFO & res, bool forceChange = false) protected virtual
Reimplemented in CWinSystemWin32DX.
References D3DPRESENTFLAG_INTERLACED, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fRefreshRate, RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, LOGDEBUG, LOGERROR, ResolutionChanged(), RESOLUTION_INFO::strOutput, and KODI::PLATFORM::WINDOWS::ToW().
Referenced by CWinSystemWin32DX::ChangeResolution(), RestoreDesktopResolution(), and SetFullScreen().
CreateBackBuffer()
virtual void CWinSystemWin32::CreateBackBuffer () protected pure virtual
Implemented in CWinSystemWin32DX.
Referenced by NotifyAppFocusChange(), and SetFullScreen().
CreateBlankWindows()
bool CWinSystemWin32::CreateBlankWindows () protected virtual
References GetLastError(), LOGERROR, m_displays, and m_hBlankWindows.
Referenced by CreateNewWindow().
CreateNewWindow()
bool CWinSystemWin32::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) override protected pure virtual
Implements CWinSystemBase.
Implemented in CWinSystemWin32DX.
References AdjustWindow(), CreateBlankWindows(), RESOLUTION_INFO::fRefreshRate, GetLastError(), GetNcAreaOffsets(), GetScreenWorkArea(), CServiceBroker::GetSettingsComponent(), GetState(), GetVirtualScreenRect(), IDI_MAIN_ICON, RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, left, LOGDEBUG, LOGERROR, CWinSystemBase::m_bFullScreen, CWinSystemBase::m_bWindowCreated, CWinSystemBase::m_fRefreshRate, m_hIcon, m_hInstance, m_hMonitor, m_hWnd, m_inFocus, CWinSystemBase::m_nHeight, CWinSystemBase::m_nLeft, CWinSystemBase::m_nTop, CWinSystemBase::m_nWidth, m_state, m_trayIcon, m_ValidWindowedPosition, m_windowExStyle, m_windowStyle, name, ScreenRect(), SETTING_WINDOW_LEFT, SETTING_WINDOW_TOP, CWinSystemBase::SetWindowResolution(), KODI::PLATFORM::WINDOWS::ToW(), TRAY_ICON_NOTIFY, UpdateStates(), WINDOW_STATE_WINDOWED, and CWinEventsWin32::WndProc().
Referenced by CWinSystemWin32DX::CreateNewWindow().
DestroyWindowSystem()
bool CWinSystemWin32::DestroyWindowSystem () override virtual
Reimplemented from CWinSystemBase.
References GetDisplayDetails(), m_hMonitor, and RestoreDesktopResolution().
DPIChanged()
bool CWinSystemWin32::DPIChanged (WORD dpi, RECT windowRect) const virtual
Reimplemented in CWinSystemWin32DX.
References m_hWnd, m_state, void(), WINDOW_STATE_FULLSCREEN, and WINDOW_STATE_FULLSCREEN_WINDOW.
FinishWindowResize()
void CWinSystemWin32::FinishWindowResize (int newWidth, int newHeight) override virtual
Reimplemented from CWinSystemBase.
References CWinSystemBase::m_nHeight, and CWinSystemBase::m_nWidth.
ForceFullScreen()
void CWinSystemWin32::ForceFullScreen (const RESOLUTION_INFO & resInfo) override virtual
Forces the window to fullscreen provided the window resolution.
Parameters
resInfo - the resolution info
Reimplemented from CWinSystemBase.
References RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, and ResizeWindow().
GetClipboardText()
std::string CWinSystemWin32::GetClipboardText (void) override virtual
Reimplemented from CWinSystemBase.
References KODI::PLATFORM::WINDOWS::FromW().
GetConnectedDisplays()
void CWinSystemWin32::GetConnectedDisplays (std::vector< MONITOR_DETAILS > & outputs) protected
References MONITOR_DETAILS::Bpp, MONITOR_DETAILS::CardNameW, MONITOR_DETAILS::DeviceNameW, MONITOR_DETAILS::DeviceStringW, KODI::PLATFORM::WINDOWS::FromW(), CWIN32Util::GetDisplayFriendlyName(), MONITOR_DETAILS::hMonitor, MONITOR_DETAILS::Interlaced, MONITOR_DETAILS::IsPrimary, MONITOR_DETAILS::MonitorNameW, MONITOR_DETAILS::RefreshRate, MONITOR_DETAILS::ScreenHeight, and MONITOR_DETAILS::ScreenWidth.
Referenced by UpdateResolutions().
GetConnectedOutputs()
std::vector< std::string > CWinSystemWin32::GetConnectedOutputs () override virtual
Reimplemented from CWinSystemBase.
References KODI::PLATFORM::WINDOWS::FromW(), and m_displays.
GetDisplayDetails() [1/2]
MONITOR_DETAILS * CWinSystemWin32::GetDisplayDetails (const std::string & name) protected
References m_displays, name, and KODI::PLATFORM::WINDOWS::ToW().
Referenced by CacheSystemSdrPeakLuminance(), CWinSystemWin32DX::CreateNewWindow(), DestroyWindowSystem(), HasSystemSdrPeakLuminance(), CWinSystemWin32DX::OnMove(), ScreenRect(), SetFullScreen(), and UpdateResolutions().
GetDisplayDetails() [2/2]
MONITOR_DETAILS * CWinSystemWin32::GetDisplayDetails (HMONITOR handle) protected
References m_displays.
GetGuiSdrPeakLuminance()
float CWinSystemWin32::GetGuiSdrPeakLuminance () const override virtual
Max luminance for GUI SDR content in HDR mode.
Returns
Max luminance in nits, lower than 10000.
Reimplemented from CWinSystemBase.
References CServiceBroker::GetSettingsComponent(), m_systemSdrPeakLuminance, m_validSystemSdrPeakLuminance, CSettings::SETTING_VIDEOSCREEN_GUISDRPEAKLUMINANCE, and CSettings::SETTING_VIDEOSCREEN_USESYSTEMSDRPEAKLUMINANCE.
GetHwnd()
HWND CWinSystemWin32::GetHwnd () const inline
References m_hWnd.
GetNcAreaOffsets()
RECT CWinSystemWin32::GetNcAreaOffsets (DWORD dwStyle, BOOL bMenu, DWORD dwExStyle) const protected
Retrieve size of the title bar and borders Add to coordinates to convert client coordinates to window coordinates Substract from coordinates to convert from window coordinates to client coordinates
References GetLastError(), and LOGERROR.
Referenced by AdjustWindow(), and CreateNewWindow().
GetScreenWorkArea()
RECT CWinSystemWin32::GetScreenWorkArea (HMONITOR handle) const protected
Retrieve the work area of the screen (exclude task bar and other occlusions)
References GetLastError(), and LOGERROR.
Referenced by AdjustWindow(), and CreateNewWindow().
GetState()
WINDOW_STATE CWinSystemWin32::GetState (bool fullScreen) const protected
References m_fullscreenState, and m_windowState.
Referenced by CreateNewWindow(), and SetFullScreen().
GetVideoSync()
std::unique_ptr< CVideoSync > CWinSystemWin32::GetVideoSync (CVideoReferenceClock * clock) override virtual
Reimplemented from CWinSystemBase.
GetVirtualScreenRect()
RECT CWinSystemWin32::GetVirtualScreenRect () static protected
Referenced by AdjustWindow(), and CreateNewWindow().
HasInertialGestures()
bool CWinSystemWin32::HasInertialGestures () inline override virtual
Reimplemented from CWinSystemBase.
HasSystemSdrPeakLuminance()
bool CWinSystemWin32::HasSystemSdrPeakLuminance () override virtual
Test support of the OS for a SDR max luminance in HDR mode setting.
Returns
true when the OS supports that setting, false otherwise
Reimplemented from CWinSystemBase.
References MONITOR_DETAILS::DeviceNameW, GetDisplayDetails(), CWIN32Util::GetSystemSdrWhiteLevel(), and m_hMonitor.
Hide()
bool CWinSystemWin32::Hide () override virtual
Reimplemented from CWinSystemBase.
References m_hWnd.
InitWindowSystem()
bool CWinSystemWin32::InitWindowSystem () override virtual
Reimplemented from CWinSystemBase.
References CWinSystemBase::InitWindowSystem().
IsAlteringWindow()
bool CWinSystemWin32::IsAlteringWindow () const inline
References m_IsAlteringWindow.
Referenced by CWinSystemWin32DX::DPIChanged().
IsInSizeMoveMode()
bool CWinSystemWin32::IsInSizeMoveMode () const inline
References m_bSizeMoveEnabled.
IsMinimized()
bool CWinSystemWin32::IsMinimized () const inline
References m_bMinimized.
IsStereoEnabled()
virtual bool CWinSystemWin32::IsStereoEnabled () protected pure virtual
Implemented in CWinSystemWin32DX.
Referenced by SetFullScreen().
IsTogglingHDR()
bool CWinSystemWin32::IsTogglingHDR () const inline
References m_IsTogglingHDR.
MessagePump()
bool CWinSystemWin32::MessagePump () override virtual
Reimplemented from CWinSystemBase.
References CWinSystemBase::m_winEvents.
Minimize()
bool CWinSystemWin32::Minimize () override virtual
Reimplemented from CWinSystemBase.
References m_hWnd.
NotifyAppFocusChange()
void CWinSystemWin32::NotifyAppFocusChange (bool bGaining) override virtual
Reimplemented from CWinSystemBase.
References CreateBackBuffer(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CGraphicContext::GetVideoResolution(), CServiceBroker::GetWinSystem(), m_hWnd, m_inFocus, m_IsAlteringWindow, m_state, ReleaseBackBuffer(), RES_INVALID, SetDeviceFullScreen(), and WINDOW_STATE_FULLSCREEN.
OnDisplayBack()
void CWinSystemWin32::OnDisplayBack () protected
References CServiceBroker::GetSettingsComponent(), m_delayDispReset, m_dispResetTimer, and OnDisplayReset().
Referenced by ResolutionChanged().
OnDisplayLost()
void CWinSystemWin32::OnDisplayLost () protected
References LOGDEBUG, m_resources, and m_resourceSection.
Referenced by ResolutionChanged().
OnDisplayReset()
void CWinSystemWin32::OnDisplayReset () protected
References LOGDEBUG, m_delayDispReset, m_resources, and m_resourceSection.
Referenced by OnDisplayBack(), and CWinSystemWin32DX::PresentRenderImpl().
OnScreenChange()
virtual void CWinSystemWin32::OnScreenChange (HMONITOR monitor) protected pure virtual
Implemented in CWinSystemWin32DX.
Referenced by SetFullScreen().
Register()
void CWinSystemWin32::Register (IDispResource * resource) protected virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemWin32DX.
References m_resources, and m_resourceSection.
Referenced by CWinSystemWin32DX::Register().
ReleaseBackBuffer()
virtual void CWinSystemWin32::ReleaseBackBuffer () protected pure virtual
Implemented in CWinSystemWin32DX.
Referenced by NotifyAppFocusChange(), and SetFullScreen().
ResizeDeviceBuffers()
virtual void CWinSystemWin32::ResizeDeviceBuffers () protected pure virtual
Implemented in CWinSystemWin32DX.
ResizeWindow()
bool CWinSystemWin32::ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemWin32DX.
References AdjustWindow(), CWinSystemBase::m_nHeight, CWinSystemBase::m_nLeft, CWinSystemBase::m_nTop, and CWinSystemBase::m_nWidth.
Referenced by ForceFullScreen(), and CWinSystemWin32DX::ResizeWindow().
ResolutionChanged()
void CWinSystemWin32::ResolutionChanged () protected
References OnDisplayBack(), and OnDisplayLost().
Referenced by ChangeResolution(), and CWinSystemWin32DX::SetDeviceFullScreen().
Restore()
bool CWinSystemWin32::Restore () override virtual
Reimplemented from CWinSystemBase.
References m_hWnd.
RestoreDesktopResolution()
void CWinSystemWin32::RestoreDesktopResolution (MONITOR_DETAILS * details) protected
References ChangeResolution(), D3DPRESENTFLAG_INTERLACED, MONITOR_DETAILS::DeviceNameW, KODI::PLATFORM::WINDOWS::FromW(), MONITOR_DETAILS::Interlaced, RESOLUTION_INFO::iWidth, LOGDEBUG, MONITOR_DETAILS::MonitorNameW, MONITOR_DETAILS::RefreshRate, MONITOR_DETAILS::ScreenHeight, and MONITOR_DETAILS::ScreenWidth.
Referenced by DestroyWindowSystem(), and SetFullScreen().
ScreenRect()
RECT CWinSystemWin32::ScreenRect (HMONITOR handle) protected
References MONITOR_DETAILS::DeviceNameW, GetDisplayDetails(), GetLastError(), and LOGERROR.
Referenced by AdjustWindow(), BlankNonActiveMonitors(), and CreateNewWindow().
SetAlteringWindow()
void CWinSystemWin32::SetAlteringWindow (bool altering) inline
References m_IsAlteringWindow.
SetDeviceFullScreen()
virtual void CWinSystemWin32::SetDeviceFullScreen (bool fullScreen, RESOLUTION_INFO & res) protected pure virtual
Implemented in CWinSystemWin32DX.
Referenced by NotifyAppFocusChange(), and SetFullScreen().
SetForegroundWindowInternal()
void CWinSystemWin32::SetForegroundWindowInternal (HWND hWnd) static protected
Referenced by SetFullScreen().
SetFullScreen()
bool CWinSystemWin32::SetFullScreen (bool fullScreen, RESOLUTION_INFO & res, bool blankOtherDisplays) override virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemWin32DX.
References AdjustWindow(), BlankNonActiveMonitors(), CenterCursor(), ChangeResolution(), CResolutionUtils::ChooseBestResolution(), CreateBackBuffer(), D3DPRESENTFLAG_INTERLACED, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fRefreshRate, GetDisplayDetails(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), GetState(), CGraphicContext::GetStereoMode(), CServiceBroker::GetWinSystem(), MONITOR_DETAILS::hMonitor, RESOLUTION_INFO::iHeight, IsStereoEnabled(), RESOLUTION_INFO::iWidth, LOGDEBUG, CWinSystemBase::m_bBlankOtherDisplay, m_bFirstResChange, CWinSystemBase::m_bFullScreen, CWinSystemBase::m_fRefreshRate, m_hMonitor, m_hWnd, m_IsAlteringWindow, CWinSystemBase::m_nHeight, CWinSystemBase::m_nLeft, CWinSystemBase::m_nTop, CWinSystemBase::m_nWidth, m_state, m_ValidWindowedPosition, OnScreenChange(), ReleaseBackBuffer(), RENDER_STEREO_MODE_HARDWAREBASED, RestoreDesktopResolution(), SetDeviceFullScreen(), SetForegroundWindowInternal(), RESOLUTION_INFO::strOutput, UpdateStates(), WINDOW_STATE_FULLSCREEN, WINDOW_STATE_FULLSCREEN_WINDOW, window_state_names, and WINDOW_STATE_WINDOWED.
Referenced by CWinSystemWin32DX::SetFullScreen().
SetMinimized()
void CWinSystemWin32::SetMinimized (bool minimized)
References CServiceBroker::GetSettingsComponent(), m_bMinimized, m_hWnd, and m_trayIcon.
SetSizeMoveMode()
void CWinSystemWin32::SetSizeMoveMode (bool mode) inline
References m_bSizeMoveEnabled.
SetTogglingHDR()
void CWinSystemWin32::SetTogglingHDR (bool toggling)
References ID_TIMER_HDR, m_hWnd, and m_IsTogglingHDR.
Show()
bool CWinSystemWin32::Show (bool raise = true) override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetSettingsComponent(), CWinSystemBase::m_bFullScreen, m_hWnd, and SetFocus().
ShowOSMouse()
void CWinSystemWin32::ShowOSMouse (bool show) override virtual
Reimplemented from CWinSystemBase.
Unregister()
void CWinSystemWin32::Unregister (IDispResource * resource) protected virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemWin32DX.
References m_resources, and m_resourceSection.
Referenced by CWinSystemWin32DX::Unregister().
UpdateResolutions()
void CWinSystemWin32::UpdateResolutions () override virtual
Reimplemented from CWinSystemBase.
References AddResolution(), CDisplaySettings::ApplyCalibrations(), RESOLUTION_INFO::bFullScreen, CDisplaySettings::ClearCustomResolutions(), D3DPRESENTFLAG_INTERLACED, MONITOR_DETAILS::DeviceNameW, MONITOR_DETAILS::DeviceStringW, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fPixelRatio, RESOLUTION_INFO::fRefreshRate, KODI::PLATFORM::WINDOWS::FromW(), GetConnectedDisplays(), GetDisplayDetails(), CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetSettingsComponent(), RESOLUTION_INFO::iHeight, MONITOR_DETAILS::Interlaced, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, CLog::Log(), LOGINFO, m_displays, MONITOR_DETAILS::MonitorNameW, MONITOR_DETAILS::RefreshRate, RES_DESKTOP, CGraphicContext::ResetOverscan(), MONITOR_DETAILS::ScreenHeight, MONITOR_DETAILS::ScreenWidth, CDisplaySettings::SetMonitor(), CSettings::SETTING_VIDEOSCREEN_MONITOR, RESOLUTION_INFO::strMode, RESOLUTION_INFO::strOutput, CWinSystemBase::UpdateDesktopResolution(), and CWinSystemBase::UpdateResolutions().
UpdateStates()
void CWinSystemWin32::UpdateStates (bool fullScreen) protected virtual
References FULLSCREEN_WINDOW_EX_STYLE, FULLSCREEN_WINDOW_STYLE, CServiceBroker::GetSettingsComponent(), m_fullscreenState, m_windowExStyle, m_windowState, m_windowStyle, CSettings::SETTING_VIDEOSCREEN_FAKEFULLSCREEN, WINDOW_FULLSCREEN_STATE_FULLSCREEN, WINDOW_FULLSCREEN_STATE_FULLSCREEN_WINDOW, WINDOW_WINDOW_STATE_WINDOWED, WINDOWED_EX_STYLE, and WINDOWED_STYLE.
Referenced by CreateNewWindow(), and SetFullScreen().
UseLimitedColor()
bool CWinSystemWin32::UseLimitedColor () override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOSCREEN_LIMITEDRANGE.
Member Data Documentation
m_bFirstResChange
bool CWinSystemWin32::m_bFirstResChange = true protected
Referenced by SetFullScreen().
m_bMinimized
bool CWinSystemWin32::m_bMinimized protected
Referenced by IsMinimized(), and SetMinimized().
m_bSizeMoveEnabled
bool CWinSystemWin32::m_bSizeMoveEnabled = false protected
Referenced by IsInSizeMoveMode(), and SetSizeMoveMode().
m_delayDispReset
bool CWinSystemWin32::m_delayDispReset protected
Referenced by OnDisplayBack(), OnDisplayReset(), and CWinSystemWin32DX::PresentRenderImpl().
m_displays
std::vector<MONITOR_DETAILS> CWinSystemWin32::m_displays protected
Referenced by BlankNonActiveMonitors(), CreateBlankWindows(), GetConnectedOutputs(), GetDisplayDetails(), GetDisplayDetails(), and UpdateResolutions().
m_dispResetTimer
XbmcThreads::EndTime CWinSystemWin32::m_dispResetTimer protected
Referenced by OnDisplayBack(), and CWinSystemWin32DX::PresentRenderImpl().
m_fullscreenState
WINDOW_FULLSCREEN_STATE CWinSystemWin32::m_fullscreenState protected
Referenced by GetState(), and UpdateStates().
m_hBlankWindows
std::vector<HWND> CWinSystemWin32::m_hBlankWindows protected
Referenced by BlankNonActiveMonitors(), and CreateBlankWindows().
m_hIcon
HICON CWinSystemWin32::m_hIcon protected
Referenced by CreateNewWindow(), and ~CWinSystemWin32().
m_hInstance
HINSTANCE CWinSystemWin32::m_hInstance protected
Referenced by CreateNewWindow().
m_hMonitor
HMONITOR CWinSystemWin32::m_hMonitor protected
Referenced by AdjustWindow(), BlankNonActiveMonitors(), CacheSystemSdrPeakLuminance(), CWinSystemWin32DX::CreateNewWindow(), CreateNewWindow(), DestroyWindowSystem(), HasSystemSdrPeakLuminance(), CWinSystemWin32DX::OnMove(), and SetFullScreen().
m_hWnd
HWND CWinSystemWin32::m_hWnd protected
Referenced by AdjustWindow(), BlankNonActiveMonitors(), CenterCursor(), CenterWindow(), CreateNewWindow(), DPIChanged(), GetHwnd(), Hide(), Minimize(), NotifyAppFocusChange(), CWinSystemWin32DX::OnMove(), Restore(), SetFullScreen(), SetMinimized(), SetTogglingHDR(), and Show().
m_inFocus
bool CWinSystemWin32::m_inFocus protected
Referenced by CreateNewWindow(), and NotifyAppFocusChange().
m_irss
std::unique_ptr<CIRServerSuite> CWinSystemWin32::m_irss protected
Referenced by CWinSystemWin32().
m_IsAlteringWindow
bool CWinSystemWin32::m_IsAlteringWindow protected
Referenced by IsAlteringWindow(), NotifyAppFocusChange(), CWinSystemWin32DX::OnResize(), SetAlteringWindow(), and SetFullScreen().
m_IsTogglingHDR
bool CWinSystemWin32::m_IsTogglingHDR {false} protected
Referenced by IsTogglingHDR(), and SetTogglingHDR().
m_resources
std::vector<IDispResource*> CWinSystemWin32::m_resources protected
Referenced by OnDisplayLost(), OnDisplayReset(), Register(), and Unregister().
m_resourceSection
CCriticalSection CWinSystemWin32::m_resourceSection protected
Referenced by OnDisplayLost(), OnDisplayReset(), Register(), and Unregister().
m_state
WINDOW_STATE CWinSystemWin32::m_state protected
Referenced by AdjustWindow(), CreateNewWindow(), DPIChanged(), NotifyAppFocusChange(), and SetFullScreen().
m_systemSdrPeakLuminance
float CWinSystemWin32::m_systemSdrPeakLuminance {.0f} protected
Referenced by CacheSystemSdrPeakLuminance(), and GetGuiSdrPeakLuminance().
m_trayIcon
NOTIFYICONDATA CWinSystemWin32::m_trayIcon = {} protected
Referenced by CreateNewWindow(), and SetMinimized().
m_validSystemSdrPeakLuminance
bool CWinSystemWin32::m_validSystemSdrPeakLuminance {false} protected
Referenced by CacheSystemSdrPeakLuminance(), and GetGuiSdrPeakLuminance().
m_ValidWindowedPosition
bool CWinSystemWin32::m_ValidWindowedPosition protected
Referenced by AdjustWindow(), CreateNewWindow(), and SetFullScreen().
m_windowExStyle
DWORD CWinSystemWin32::m_windowExStyle protected
Referenced by AdjustWindow(), CreateNewWindow(), and UpdateStates().
m_windowState
WINDOW_WINDOW_STATE CWinSystemWin32::m_windowState protected
Referenced by GetState(), and UpdateStates().
m_windowStyle
DWORD CWinSystemWin32::m_windowStyle protected
Referenced by AdjustWindow(), CreateNewWindow(), and UpdateStates().
SETTING_WINDOW_LEFT
const char * CWinSystemWin32::SETTING_WINDOW_LEFT = "window.left" static protected
Referenced by AdjustWindow(), CreateNewWindow(), and CWinSystemWin32DX::OnMove().
SETTING_WINDOW_TOP
const char * CWinSystemWin32::SETTING_WINDOW_TOP = "window.top" static protected
Referenced by AdjustWindow(), CreateNewWindow(), and CWinSystemWin32DX::OnMove().
The documentation for this class was generated from the following files:
WinSystemWin32.h
WinSystemWin32.cpp