Kodi Documentation: CTextureCache Class Reference
CTextureCache Class Reference
Guilib classes » Graphics and Screen » Textures and Fonts
Texture cache class for handling the caching of images.
#include <TextureCache.h>
Public Member Functions
CTextureCache ()
~CTextureCache () override
void Initialize ()
Initialize the texture cache.
void Deinitialize ()
Deinitialize the texture cache.
std::string CheckCachedImage (const std::string &image, bool &needsRecaching)
Check whether we already have this image cached.
void BackgroundCacheImage (const std::string &image)
Cache image (if required) using a background job.
bool StartCacheImage (const std::string &image)
Updates the in-process list.
std::string CacheImage (const std::string &image, std::unique_ptr< CTexture > *texture=nullptr, CTextureDetails *details=nullptr)
Cache an image to image cache, optionally return the texture.
bool CacheImage (const std::string &image, CTextureDetails &details)
Cache an image to image cache if not already cached, returning the image details.
bool HasCachedImage (const std::string &image)
Check whether an image is in the cache Note: If the image url won't normally be cached (eg a skin image) this function will return false.
void ClearCachedImage (const std::string &image, bool deleteSource=false)
clear the cached version of the given image
bool ClearCachedImage (int textureID)
clear the cached version of the image with given id
bool AddCachedTexture (const std::string &image, const CTextureDetails &details)
Add this image to the database Thread-safe wrapper of CTextureDatabase::AddCachedTexture.
bool Export (const std::string &image, const std::string &destination, bool overwrite)
Export a (possibly) cached image to a file.
bool Export (const std::string &image, const std::string &destination)
bool CleanAllUnusedImages ()
Public Member Functions inherited from CJobQueue
CJobQueue (bool lifo=false, unsigned int jobsAtOnce=1, CJob::PRIORITY priority=CJob::PRIORITY_LOW)
CJobQueue constructor.
~CJobQueue () override
CJobQueue destructor Cancels any in-process jobs, and destroys the job queue.
bool AddJob (CJob *job)
Add a job to the queue On completion of the job, destruction of the job queue or in case the job could not be added successfully, the CJob object will be destroyed.
template<typename F >
void Submit (F &&f)
Add a function f to this job queue.
void CancelJob (const CJob *job)
Cancel a job in the queue Cancels a job in the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed. If the job is only queued then it will be removed from the queue and deleted.
void CancelJobs ()
Cancel all jobs in the queue Removes all jobs from the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed.
bool IsProcessing () const
Check whether the queue is processing a job.
void OnJobAbort (unsigned int jobID, CJob *job) override
The callback used when a job will be aborted.
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Static Public Member Functions
static std::string GetCacheFile (const std::string &url)
retrieve a cache file (relative to the cache path) to associate with the given image, excluding extension Use GetCachedPath(GetCacheFile(url)+extension) for the full path to the file.
static std::string GetCachedPath (const std::string &file)
retrieve the full path of the given cached file
Private Member Functions
CTextureCache (const CTextureCache &)=delete
CTextureCache const & operator= (CTextureCache const &)=delete
bool IsCachedImage (const std::string &image) const
Check if the given image is a cached image.
std::string GetCachedImage (const std::string &image, CTextureDetails &details, bool trackUsage=false)
retrieve the cached version of the given image (if it exists)
bool GetCachedTexture (const std::string &url, CTextureDetails &details)
Get an image from the database Thread-safe wrapper of CTextureDatabase::GetCachedTexture.
bool ClearCachedTexture (const std::string &url, std::string &cacheFile)
Clear an image from the database Thread-safe wrapper of CTextureDatabase::ClearCachedTexture.
bool ClearCachedTexture (int textureID, std::string &cacheFile)
void IncrementUseCount (const CTextureDetails &details)
Increment the use count of a texture Stores locally before calling CTextureDatabase::IncrementUseCount via a CUseCountJob.
bool SetCachedTextureValid (const std::string &url, bool updateable)
Set a previously cached texture as valid in the database Thread-safe wrapper of CTextureDatabase::SetCachedTextureValid.
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
void OnCachingComplete (bool success, CTextureCacheJob *job)
Called when a caching job has completed. Removes the job from our processing list, updates the database and fires a DDS job if appropriate.
void CleanTimer ()
std::chrono::milliseconds ScanOldestCache ()
bool CleanAllUnusedImagesJob (CGUIDialogProgress *progress)
Private Attributes
std::atomic_flag m_cleaningInProgress
CTimer m_cleanTimer
CCriticalSection m_databaseSection
CTextureDatabase m_database
std::set< std::string > m_processinglist
currently processing list to avoid 2 jobs being processed at once
CCriticalSection m_processingSection
CEvent m_completeEvent
Set whenever a job has finished.
std::vector< CTextureDetails > m_useCounts
Use count tracking.
CCriticalSection m_useCountSection
Additional Inherited Members
Protected Member Functions inherited from CJobQueue
bool QueueEmpty () const
Returns if we still have jobs waiting to be processed NOTE: This function does not take into account the jobs that are currently processing.
Detailed Description
Texture cache class for handling the caching of images.
Manages the caching of images for use as control textures. Images are cached both as originals (direct copies) and as .dds textures for fast loading. Images may be periodically checked for updates and may be purged from the cache if unused for a set period of time.
Constructor & Destructor Documentation
CTextureCache() [1/2]
CTextureCache::CTextureCache ()
References CleanTimer().
~CTextureCache()
CTextureCache::~CTextureCache () override default
CTextureCache() [2/2]
CTextureCache::CTextureCache (const CTextureCache &) private delete
Member Function Documentation
AddCachedTexture()
bool CTextureCache::AddCachedTexture (const std::string & image, const CTextureDetails & details)
Add this image to the database Thread-safe wrapper of CTextureDatabase::AddCachedTexture.
Parameters
image url of the original image
details the texture details to add
Returns
true if we successfully added to the database, false otherwise.
References CTextureDatabase::AddCachedTexture(), m_database, and m_databaseSection.
Referenced by OnCachingComplete().
BackgroundCacheImage()
void CTextureCache::BackgroundCacheImage (const std::string & image)
Cache image (if required) using a background job.
Checks firstly whether an image is already cached, and return URL if so [see CheckCacheImage] If the image is not yet in the database, a background job is started to cache the image and add to the database [see CTextureCacheJob]
Parameters
image url of the image to cache
See also
CacheImage
References CJobQueue::AddJob(), GetCachedImage(), CTextureDetails::hash, and IMAGE_FILES::ToCacheKey().
CacheImage() [1/2]
bool CTextureCache::CacheImage (const std::string & image, CTextureDetails & details)
Cache an image to image cache if not already cached, returning the image details.
Parameters
image url of the image to cache.
details [out] the image details.
Returns
true if the image is in the cache, false otherwise.
See also
CTextureCacheJob::CacheTexture
References CacheImage(), and GetCachedImage().
CacheImage() [2/2]
std::string CTextureCache::CacheImage (const std::string & image, std::unique_ptr< CTexture > * texture = nullptr, CTextureDetails * details = nullptr)
Cache an image to image cache, optionally return the texture.
Caches the given image, returning the texture if the caller wants it.
Parameters
image url of the image to cache
texture [out] the loaded image
details [out] details of the cached image
Returns
cached url of this image
See also
CTextureCacheJob::CacheTexture
References CTextureCacheJob::CacheTexture(), CTextureDetails::file, GetCachedImage(), GetCachedPath(), CTexture::LoadFromFile(), CLog::Log(), LOGDEBUG, m_completeEvent, CTextureCacheJob::m_details, m_processinglist, m_processingSection, OnCachingComplete(), success, IMAGE_FILES::ToCacheKey(), and CEvent::Wait().
Referenced by CacheImage().
CheckCachedImage()
std::string CTextureCache::CheckCachedImage (const std::string & image, bool & needsRecaching)
Check whether we already have this image cached.
Check and return URL to cached image if it exists; If not, return empty string. If the image is cached, return URL (for original image or .dds version if requested)
Parameters
image url of the image to check
needsRecaching [out] whether the image needs recaching.
Returns
cached url of this image
See also
GetCachedImage
References GetCachedImage(), and CTextureDetails::hash.
CleanAllUnusedImages()
bool CTextureCache::CleanAllUnusedImages ()
Todo:
BACKWARD COMPATIBILITY FOR MUSIC THUMBS
References CleanAllUnusedImagesJob(), CServiceBroker::GetGUI(), CServiceBroker::GetJobManager(), CGUIComponent::GetWindowManager(), m_cleaningInProgress, CGUIDialogBoxBase::SetHeading(), and WINDOW_DIALOG_PROGRESS.
CleanAllUnusedImagesJob()
bool CTextureCache::CleanAllUnusedImagesJob (CGUIDialogProgress * progress) private
References ClearCachedImage(), CGUIWindow::Close(), IMAGE_FILES::CImageCacheCleaner::Create(), CGUIDialogProgress::GetPercentage(), CGUIDialogProgress::IsCanceled(), CGUIDialogProgress::Progress(), and CGUIDialogProgress::SetPercentage().
Referenced by CleanAllUnusedImages().
CleanTimer()
void CTextureCache::CleanTimer () private
References CServiceBroker::GetJobManager(), m_cleaningInProgress, m_cleanTimer, CJob::PRIORITY_LOW_PAUSABLE, ScanOldestCache(), and CTimer::Start().
Referenced by CTextureCache().
ClearCachedImage() [1/2]
void CTextureCache::ClearCachedImage (const std::string & image, bool deleteSource = false)
clear the cached version of the given image
Parameters
image url of the image
See also
GetCachedImage
Todo:
This can be removed when the texture cache covers everything.
References ClearCachedTexture(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), GetCachedPath(), URIUtils::ReplaceExtension(), and IMAGE_FILES::ToCacheKey().
Referenced by CleanAllUnusedImagesJob(), and ScanOldestCache().
ClearCachedImage() [2/2]
bool CTextureCache::ClearCachedImage (int textureID)
clear the cached version of the image with given id
Parameters
database id of the image
See also
GetCachedImage
References ClearCachedTexture(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), GetCachedPath(), and URIUtils::ReplaceExtension().
ClearCachedTexture() [1/2]
bool CTextureCache::ClearCachedTexture (const std::string & url, std::string & cacheFile) private
Clear an image from the database Thread-safe wrapper of CTextureDatabase::ClearCachedTexture.
Parameters
image url of the original image
cacheFile [out] url of the cached original (if available)
Returns
true if we had a cached version of this image, false otherwise.
References CTextureDatabase::ClearCachedTexture(), m_database, and m_databaseSection.
Referenced by ClearCachedImage(), and ClearCachedImage().
ClearCachedTexture() [2/2]
bool CTextureCache::ClearCachedTexture (int textureID, std::string & cacheFile) private
References CTextureDatabase::ClearCachedTexture(), m_database, and m_databaseSection.
Deinitialize()
void CTextureCache::Deinitialize ()
Deinitialize the texture cache.
References CJobQueue::CancelJobs(), CDatabase::Close(), m_database, and m_databaseSection.
Export() [1/2]
bool CTextureCache::Export (const std::string & image, const std::string & destination)
References XFILE::CFile::Copy(), GetCachedImage(), CLog::Log(), and LOGERROR.
Export() [2/2]
bool CTextureCache::Export (const std::string & image, const std::string & destination, bool overwrite)
Export a (possibly) cached image to a file.
Parameters
image url of the original image
destination url of the destination image, excluding extension.
overwrite whether to overwrite the destination if it exists (TODO: Defaults to false)
Returns
true if we successfully exported the file, false otherwise.
References XFILE::CFile::Copy(), XFILE::CFile::Exists(), GetCachedImage(), URIUtils::GetExtension(), CLog::Log(), and LOGERROR.
GetCachedImage()
std::string CTextureCache::GetCachedImage (const std::string & image, CTextureDetails & details, bool trackUsage = false) private
retrieve the cached version of the given image (if it exists)
Parameters
image url of the image
details [out] the details of the texture.
trackUsage whether this call should track usage of the image (defaults to false)
Returns
cached url of this image, empty if none exists
See also
ClearCachedImage, CTextureDetails
References CTextureDetails::file, GetCachedPath(), GetCachedTexture(), IncrementUseCount(), IsCachedImage(), and IMAGE_FILES::ToCacheKey().
Referenced by BackgroundCacheImage(), CacheImage(), CacheImage(), CheckCachedImage(), Export(), Export(), and HasCachedImage().
GetCachedPath()
std::string CTextureCache::GetCachedPath (const std::string & file) static
retrieve the full path of the given cached file
Parameters
file name of the file
Returns
full path of the cached file
References URIUtils::AddFileToFolder(), and CServiceBroker::GetSettingsComponent().
Referenced by CacheImage(), CTextureCacheJob::CacheTexture(), ClearCachedImage(), ClearCachedImage(), and GetCachedImage().
GetCachedTexture()
bool CTextureCache::GetCachedTexture (const std::string & url, CTextureDetails & details) private
Get an image from the database Thread-safe wrapper of CTextureDatabase::GetCachedTexture.
Parameters
image url of the original image
details [out] texture details from the database (if available)
Returns
true if we have a cached version of this image, false otherwise.
References CTextureDatabase::GetCachedTexture(), m_database, and m_databaseSection.
Referenced by GetCachedImage().
GetCacheFile()
std::string CTextureCache::GetCacheFile (const std::string & url) static
retrieve a cache file (relative to the cache path) to associate with the given image, excluding extension Use GetCachedPath(GetCacheFile(url)+extension) for the full path to the file.
Parameters
url location of the image
Returns
a "unique" filename for the associated cache file, excluding extension
References Crc32::ComputeFromLowerCase().
HasCachedImage()
bool CTextureCache::HasCachedImage (const std::string & image)
Check whether an image is in the cache Note: If the image url won't normally be cached (eg a skin image) this function will return false.
Parameters
image url of the image
Returns
true if the image is cached, false otherwise
See also
ClearCachedImage
References GetCachedImage().
IncrementUseCount()
void CTextureCache::IncrementUseCount (const CTextureDetails & details) private
Increment the use count of a texture Stores locally before calling CTextureDatabase::IncrementUseCount via a CUseCountJob.
See also
CUseCountJob, CTextureDatabase::IncrementUseCount
References CJobQueue::AddJob(), m_useCounts, and m_useCountSection.
Referenced by GetCachedImage().
Initialize()
void CTextureCache::Initialize ()
Initialize the texture cache.
References CDatabase::IsOpen(), m_cleanTimer, m_database, m_databaseSection, CTextureDatabase::Open(), and CTimer::Start().
IsCachedImage()
bool CTextureCache::IsCachedImage (const std::string & image) const private
Check if the given image is a cached image.
Parameters
image url of the image
Returns
true if this is a cached image, false otherwise.
References CServiceBroker::GetSettingsComponent(), and URIUtils::PathHasParent().
Referenced by GetCachedImage().
OnCachingComplete()
void CTextureCache::OnCachingComplete (bool success, CTextureCacheJob * job) private
Called when a caching job has completed. Removes the job from our processing list, updates the database and fires a DDS job if appropriate.
Parameters
success whether the job was successful.
job the caching job.
References AddCachedTexture(), CTextureDetails::hashRevalidated, m_completeEvent, CTextureCacheJob::m_details, m_processinglist, m_processingSection, CTextureCacheJob::m_url, CEvent::Set(), SetCachedTextureValid(), success, and CTextureDetails::updateable.
Referenced by CacheImage(), and OnJobComplete().
OnJobComplete()
void CTextureCache::OnJobComplete (unsigned int jobID, bool success, CJob * job) override private virtual
The callback used when a job completes.
CJobQueue implementation will cleanup the internal processing queue and then queue the next job at the job manager, if any.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed.
See also
CJobManager, IJobCallback and CJob
Reimplemented from CJobQueue.
References CJob::GetType(), kJobTypeCacheImage, OnCachingComplete(), CJobQueue::OnJobComplete(), and success.
operator=()
CTextureCache const & CTextureCache::operator= (CTextureCache const &) private delete
ScanOldestCache()
std::chrono::milliseconds CTextureCache::ScanOldestCache () private
References ClearCachedImage(), IMAGE_FILES::CImageCacheCleaner::Create(), and LOGDEBUG.
Referenced by CleanTimer().
SetCachedTextureValid()
bool CTextureCache::SetCachedTextureValid (const std::string & url, bool updateable) private
Set a previously cached texture as valid in the database Thread-safe wrapper of CTextureDatabase::SetCachedTextureValid.
Parameters
image url of the original image
updateable whether this image should be checked for updates
Returns
true if successful, false otherwise.
References m_database, m_databaseSection, and CTextureDatabase::SetCachedTextureValid().
Referenced by OnCachingComplete().
StartCacheImage()
bool CTextureCache::StartCacheImage (const std::string & image)
Updates the in-process list.
Inserts the image url into the currently processing list to avoid 2 jobs being processed at once
Parameters
image url of the image to start processing
Returns
true if list updated, false otherwise
See also
CacheImage
References m_processinglist, and m_processingSection.
Member Data Documentation
m_cleaningInProgress
std::atomic_flag CTextureCache::m_cleaningInProgress private
Referenced by CleanAllUnusedImages(), and CleanTimer().
m_cleanTimer
CTimer CTextureCache::m_cleanTimer private
Referenced by CleanTimer(), and Initialize().
m_completeEvent
CEvent CTextureCache::m_completeEvent private
Set whenever a job has finished.
Referenced by CacheImage(), and OnCachingComplete().
m_database
CTextureDatabase CTextureCache::m_database private
Referenced by AddCachedTexture(), ClearCachedTexture(), ClearCachedTexture(), Deinitialize(), GetCachedTexture(), Initialize(), and SetCachedTextureValid().
m_databaseSection
CCriticalSection CTextureCache::m_databaseSection private
Referenced by AddCachedTexture(), ClearCachedTexture(), ClearCachedTexture(), Deinitialize(), GetCachedTexture(), Initialize(), and SetCachedTextureValid().
m_processinglist
std::set<std::string> CTextureCache::m_processinglist private
currently processing list to avoid 2 jobs being processed at once
Referenced by CacheImage(), OnCachingComplete(), and StartCacheImage().
m_processingSection
CCriticalSection CTextureCache::m_processingSection private
Referenced by CacheImage(), OnCachingComplete(), and StartCacheImage().
m_useCounts
std::vector<CTextureDetails> CTextureCache::m_useCounts private
Use count tracking.
Referenced by IncrementUseCount().
m_useCountSection
CCriticalSection CTextureCache::m_useCountSection private
Referenced by IncrementUseCount().
The documentation for this class was generated from the following files:
TextureCache.h
TextureCache.cpp