Kodi Documentation: AnnounceReceiver.mm File Reference
AnnounceReceiver.mm File Reference
import "platform/darwin/ios-common/AnnounceReceiver.h"
#include "FileItem.h"
#include "PlayListPlayer.h"
#include "ServiceBroker.h"
#include "TextureCache.h"
#include "application/Application.h"
#include "filesystem/SpecialProtocol.h"
#include "music/MusicDatabase.h"
#include "music/tags/MusicInfoTag.h"
#include "playlists/PlayList.h"
#include "pvr/channels/PVRChannel.h"
#include "pvr/epg/EpgInfoTag.h"
#include "utils/Variant.h"
import "platform/darwin/ios-common/DarwinEmbedNowPlayingInfoManager.h"
import <UIKit/UIKit.h>
Functions
id objectFromVariant (const CVariant &data)
NSArray * arrayFromVariantArray (const CVariant &data)
NSDictionary * dictionaryFromVariantMap (const CVariant &data)
void AnnounceBridge (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data)
Function Documentation
AnnounceBridge()
void AnnounceBridge (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data)
References CVariant::asInteger(), CVariant::asString(), data(), dictionaryFromVariantMap(), g_application, g_xbmcController, CSong::GetArtist(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentItemIdx(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), CMusicDatabase::GetSong(), CServiceBroker::GetTextureCache(), CSong::iTrack, MediaTypeSong, XBMCController::MPNPInfoManager, CMusicDatabase::Open(), KODI::PLAYLIST::CPlayList::size(), CSong::strAlbum, CSong::strTitle, and CSpecialProtocol::TranslatePath().
Referenced by CAnnounceReceiver::Announce().
arrayFromVariantArray()
NSArray * arrayFromVariantArray (const CVariant & data)
References data(), and objectFromVariant().
Referenced by objectFromVariant().
dictionaryFromVariantMap()
NSDictionary * dictionaryFromVariantMap (const CVariant & data)
References data(), and objectFromVariant().
Referenced by AnnounceBridge(), and objectFromVariant().
objectFromVariant()
id objectFromVariant (const CVariant & data)
References arrayFromVariantArray(), data(), and dictionaryFromVariantMap().
Referenced by arrayFromVariantArray(), and dictionaryFromVariantMap().