Kodi Documentation: CWinEventsIOS Class Reference
CWinEventsIOS Class Reference
#include <WinEventsIOS.h>
Public Member Functions
bool MessagePump () override
Public Member Functions inherited from IWinEvents
virtual ~IWinEvents ()=default
Private Member Functions
size_t GetQueueSize ()
Member Function Documentation
GetQueueSize()
size_t CWinEventsIOS::GetQueueSize () private
References events, and g_inputCond.
Referenced by MessagePump().
MessagePump()
bool CWinEventsIOS::MessagePump () override virtual
Implements IWinEvents.
References events, g_inputCond, CServiceBroker::GetAppPort(), and GetQueueSize().
The documentation for this class was generated from the following files:
WinEventsIOS.h
WinEventsIOS.mm