Kodi Documentation: VAAPI::CVaapi2Texture Class Reference
VAAPI::CVaapi2Texture Class Reference
#include <VaapiEGL.h>
Classes
struct MappedTexture
Public Member Functions
bool Map (CVaapiRenderPicture *pic) override
void Unmap () override
void Init (InteropInfo &interop) override
GLuint GetTextureY () override
GLuint GetTextureVU () override
CSizeInt GetTextureSize () override
Public Member Functions inherited from VAAPI::CVaapiTexture
CVaapiTexture ()=default
virtual ~CVaapiTexture ()=default
Static Public Member Functions
static void TestInterop (VADisplay vaDpy, EGLDisplay eglDisplay, bool &general, bool &deepColor)
static bool TestInteropGeneral (VADisplay vaDpy, EGLDisplay eglDisplay)
Static Private Member Functions
static bool TestEsh (VADisplay vaDpy, EGLDisplay eglDisplay, std::uint32_t rtFormat, std::int32_t pixelFormat)
Private Attributes
InteropInfo m_interop
CVaapiRenderPicture * m_vaapiPic {}
bool m_hasPlaneModifiers {false}
std::array< KODI::UTILS::POSIX::CFileHandle, 4 > m_drmFDs
MappedTexture m_y
MappedTexture m_vu
CSizeInt m_textureSize
Member Function Documentation
GetTextureSize()
CSizeInt CVaapi2Texture::GetTextureSize () override virtual
Implements VAAPI::CVaapiTexture.
References m_textureSize.
GetTextureVU()
GLuint CVaapi2Texture::GetTextureVU () override virtual
Implements VAAPI::CVaapiTexture.
References VAAPI::CVaapi2Texture::MappedTexture::glTexture, and m_vu.
GetTextureY()
GLuint CVaapi2Texture::GetTextureY () override virtual
Implements VAAPI::CVaapiTexture.
References VAAPI::CVaapi2Texture::MappedTexture::glTexture, and m_y.
Init()
void CVaapi2Texture::Init (InteropInfo & interop) override virtual
Implements VAAPI::CVaapiTexture.
References VAAPI::InteropInfo::eglDisplay, CEGLUtils::HasExtension(), m_hasPlaneModifiers, and m_interop.
Map()
bool CVaapi2Texture::Map (CVaapiRenderPicture * pic) override virtual
Implements VAAPI::CVaapiTexture.
References CVideoBuffer::Acquire(), CEGLAttributes< AttributeCount >::Add(), VAAPI::CVaapiRenderPicture::DVDPic, VAAPI::InteropInfo::eglCreateImageKHR, VAAPI::InteropInfo::eglDisplay, CEGLAttributes< AttributeCount >::Get(), VAAPI::InteropInfo::glEGLImageTargetTexture2DOES, CSizeGen< T >::Height(), VideoPicture::iHeight, VideoPicture::iWidth, CLog::Log(), CEGLUtils::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_drmFDs, m_hasPlaneModifiers, m_interop, m_textureSize, m_vaapiPic, m_vu, m_y, VAAPI::CVaapiRenderPicture::procPic, CSizeGen< T >::Set(), VAAPI::InteropInfo::textureTarget, VAAPI::CVaapiRenderPicture::vadsp, VAAPI::CVaapiProcessedPicture::videoSurface, and CSizeGen< T >::Width().
TestEsh()
bool CVaapi2Texture::TestEsh (VADisplay vaDpy, EGLDisplay eglDisplay, std::uint32_t rtFormat, std::int32_t pixelFormat) static private
Referenced by TestInterop(), and TestInteropGeneral().
TestInterop()
void CVaapi2Texture::TestInterop (VADisplay vaDpy, EGLDisplay eglDisplay, bool & general, bool & deepColor) static
References TestEsh(), and TestInteropGeneral().
Referenced by CRendererVAAPIGL::Register(), and CRendererVAAPIGLES::Register().
TestInteropGeneral()
bool CVaapi2Texture::TestInteropGeneral (VADisplay vaDpy, EGLDisplay eglDisplay) static
References TestEsh().
Referenced by CRendererVAAPIGL::Configure(), CRendererVAAPIGLES::Configure(), and TestInterop().
Unmap()
void CVaapi2Texture::Unmap () override virtual
Implements VAAPI::CVaapiTexture.
References VAAPI::InteropInfo::eglDestroyImageKHR, VAAPI::InteropInfo::eglDisplay, m_drmFDs, m_interop, m_vaapiPic, m_vu, m_y, and CVideoBuffer::Release().
Member Data Documentation
m_drmFDs
std::array<KODI::UTILS::POSIX::CFileHandle, 4> VAAPI::CVaapi2Texture::m_drmFDs private
Referenced by Map(), and Unmap().
m_hasPlaneModifiers
bool VAAPI::CVaapi2Texture::m_hasPlaneModifiers {false} private
Referenced by Init(), and Map().
m_interop
InteropInfo VAAPI::CVaapi2Texture::m_interop private
Referenced by Init(), Map(), and Unmap().
m_textureSize
CSizeInt VAAPI::CVaapi2Texture::m_textureSize private
Referenced by GetTextureSize(), and Map().
m_vaapiPic
CVaapiRenderPicture* VAAPI::CVaapi2Texture::m_vaapiPic {} private
Referenced by Map(), and Unmap().
m_vu
MappedTexture VAAPI::CVaapi2Texture::m_vu private
Referenced by GetTextureVU(), Map(), and Unmap().
m_y
MappedTexture VAAPI::CVaapi2Texture::m_y private
Referenced by GetTextureY(), Map(), and Unmap().
The documentation for this class was generated from the following files:
VaapiEGL.h
VaapiEGL.cpp