Kodi Documentation: PERIPHERALS::CAndroidJoystickState Class Reference
PERIPHERALS::CAndroidJoystickState Class Reference
#include <AndroidJoystickState.h>
Classes
struct JoystickAxis
Public Member Functions
CAndroidJoystickState ()=default
CAndroidJoystickState (CAndroidJoystickState &&other) noexcept
virtual ~CAndroidJoystickState ()
int GetDeviceId () const
unsigned int GetButtonCount () const
unsigned int GetAxisCount () const
bool Initialize (const CJNIViewInputDevice &inputDevice)
Initialize the joystick object.
bool InitializeButtonMap (KODI::JOYSTICK::IButtonMap &buttonMap) const
Initialize a joystick buttonmap, if possible.
void Deinitialize ()
Deinitialize the joystick object.
bool ProcessEvent (const AInputEvent *event)
Processes the given input event.
void GetEvents (std::vector< kodi::addon::PeripheralEvent > &events)
Get events that have occurred since the last call to GetEvents()
Private Types
using JoystickAxes = std::vector< JoystickAxis >
Private Member Functions
bool SetButtonValue (int axisId, JOYSTICK_STATE_BUTTON buttonValue)
bool SetAxisValue (const std::vector< int > &axisIds, JOYSTICK_STATE_AXIS axisValue)
void GetButtonEvents (std::vector< kodi::addon::PeripheralEvent > &events)
void GetAxisEvents (std::vector< kodi::addon::PeripheralEvent > &events) const
bool MapButton (KODI::JOYSTICK::IButtonMap &buttonMap, int buttonKeycode) const
bool MapTrigger (KODI::JOYSTICK::IButtonMap &buttonMap, int axisId, const std::string &triggerName) const
bool MapDpad (KODI::JOYSTICK::IButtonMap &buttonMap, int horizAxisId, int vertAxisId) const
bool MapAnalogStick (KODI::JOYSTICK::IButtonMap &buttonMap, int horizAxisId, int vertAxisId, const std::string &analogStickName) const
Static Private Member Functions
static float Contain (float value, float min, float max)
static float Scale (float value, float max, float scaledMax)
static float Deadzone (float value, float deadzone)
static JoystickAxes::const_iterator GetAxis (const std::vector< int > &axisIds, const JoystickAxes &axes)
static bool ContainsAxis (int axisId, const JoystickAxes &axes)
static bool GetAxesIndex (const std::vector< int > &axisIds, const JoystickAxes &axes, size_t &axesIndex)
Private Attributes
int m_deviceId = -1
JoystickAxes m_buttons
JoystickAxes m_axes
std::vector< JOYSTICK_STATE_AXIS > m_analogState
CCriticalSection m_eventMutex
std::vector< kodi::addon::PeripheralEvent > m_digitalEvents
Member Typedef Documentation
JoystickAxes
using PERIPHERALS::CAndroidJoystickState::JoystickAxes = std::vector<JoystickAxis> private
Constructor & Destructor Documentation
CAndroidJoystickState() [1/2]
PERIPHERALS::CAndroidJoystickState::CAndroidJoystickState () default
CAndroidJoystickState() [2/2]
CAndroidJoystickState::CAndroidJoystickState (CAndroidJoystickState && other) noexcept
~CAndroidJoystickState()
CAndroidJoystickState::~CAndroidJoystickState () virtual
References Deinitialize().
Member Function Documentation
Contain()
float CAndroidJoystickState::Contain (float value, float min, float max) static private
References max, min, and value.
Referenced by SetAxisValue().
ContainsAxis()
bool CAndroidJoystickState::ContainsAxis (int axisId, const JoystickAxes & axes) static private
References GetAxis().
Referenced by Initialize().
Deadzone()
float CAndroidJoystickState::Deadzone (float value, float deadzone) static private
References value.
Referenced by SetAxisValue().
Deinitialize()
void CAndroidJoystickState::Deinitialize (void)
Deinitialize the joystick object.
GetEvents() will not be called after deinitialization.
References m_analogState, m_axes, m_buttons, and m_digitalEvents.
Referenced by ~CAndroidJoystickState().
GetAxesIndex()
bool CAndroidJoystickState::GetAxesIndex (const std::vector< int > & axisIds, const JoystickAxes & axes, size_t & axesIndex) static private
References GetAxis().
Referenced by InitializeButtonMap(), MapAnalogStick(), MapButton(), MapDpad(), MapTrigger(), SetAxisValue(), and SetButtonValue().
GetAxis()
CAndroidJoystickState::JoystickAxes::const_iterator CAndroidJoystickState::GetAxis (const std::vector< int > & axisIds, const JoystickAxes & axes) static private
Referenced by ContainsAxis(), and GetAxesIndex().
GetAxisCount()
unsigned int PERIPHERALS::CAndroidJoystickState::GetAxisCount () const inline
References m_axes.
Referenced by Initialize(), PERIPHERALS::CPeripheralBusAndroid::InitializeButtonMap(), PERIPHERALS::CPeripheralBusAndroid::InitializeProperties(), and SetAxisValue().
GetAxisEvents()
void CAndroidJoystickState::GetAxisEvents (std::vector< kodi::addon::PeripheralEvent > & events) const private
References events, m_analogState, and m_deviceId.
Referenced by GetEvents().
GetButtonCount()
unsigned int PERIPHERALS::CAndroidJoystickState::GetButtonCount () const inline
References m_buttons.
Referenced by Initialize(), PERIPHERALS::CPeripheralBusAndroid::InitializeButtonMap(), PERIPHERALS::CPeripheralBusAndroid::InitializeProperties(), and SetButtonValue().
GetButtonEvents()
void CAndroidJoystickState::GetButtonEvents (std::vector< kodi::addon::PeripheralEvent > & events) private
References events, m_digitalEvents, m_eventMutex, and PERIPHERAL_EVENT_TYPE_DRIVER_BUTTON.
Referenced by GetEvents().
GetDeviceId()
int PERIPHERALS::CAndroidJoystickState::GetDeviceId () const inline
References m_deviceId.
GetEvents()
void CAndroidJoystickState::GetEvents (std::vector< kodi::addon::PeripheralEvent > & events)
Get events that have occurred since the last call to GetEvents()
References events, GetAxisEvents(), and GetButtonEvents().
Initialize()
bool CAndroidJoystickState::Initialize (const CJNIViewInputDevice & inputDevice)
Initialize the joystick object.
Joystick will be initialized before the first call to GetEvents().
References ContainsAxis(), GetAxisCount(), GetButtonCount(), index(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_analogState, m_axes, m_buttons, m_deviceId, PERIPHERALS::CAndroidJoystickTranslator::TranslateAxis(), and PERIPHERALS::CAndroidJoystickTranslator::TranslateKeyCode().
Referenced by PERIPHERALS::CPeripheralBusAndroid::InitializeProperties().
InitializeButtonMap()
bool CAndroidJoystickState::InitializeButtonMap (KODI::JOYSTICK::IButtonMap & buttonMap) const
Initialize a joystick buttonmap, if possible.
Android has a large database of buttonmaps, which it uses to provide mapped button keycodes such as AKEYCODE_BUTTON_A. We can take advantage of this to initialize a default buttonmap based on these mappings.
If Android can't map the buttons, it will use generic button keycodes such as AKEYCODE_BUTTON_1, in which case we can't initialize the buttonmap.
References KODI::GAME::CONTROLLER_ID_PLAYSTATION, KODI::JOYSTICK::IButtonMap::ControllerID(), DEFAULT_CONTROLLER_ID, KODI::GAME::CDefaultController::FEATURE_LEFT_STICK, KODI::GAME::CDefaultController::FEATURE_LEFT_TRIGGER, KODI::GAME::CDefaultController::FEATURE_RIGHT_STICK, KODI::GAME::CDefaultController::FEATURE_RIGHT_TRIGGER, GetAxesIndex(), CLog::Log(), LOGDEBUG, m_axes, m_buttons, MapAnalogStick(), MapButton(), MapDpad(), MapTrigger(), KODI::JOYSTICK::IButtonMap::SaveButtonMap(), KODI::JOYSTICK::IButtonMap::SetAppearance(), KODI::JOYSTICK::IButtonMap::SetIgnoredPrimitives(), and success.
Referenced by PERIPHERALS::CPeripheralBusAndroid::InitializeButtonMap().
MapAnalogStick()
bool CAndroidJoystickState::MapAnalogStick (KODI::JOYSTICK::IButtonMap & buttonMap, int horizAxisId, int vertAxisId, const std::string & analogStickName) const private
References KODI::JOYSTICK::IButtonMap::AddAnalogStick(), GetAxesIndex(), KODI::JOYSTICK::IButtonMap::GetFeature(), CLog::Log(), LOGDEBUG, and m_axes.
Referenced by InitializeButtonMap().
MapButton()
bool CAndroidJoystickState::MapButton (KODI::JOYSTICK::IButtonMap & buttonMap, int buttonKeycode) const private
References KODI::JOYSTICK::IButtonMap::AddScalar(), GetAxesIndex(), KODI::JOYSTICK::IButtonMap::GetFeature(), KODI::JOYSTICK::IButtonMap::GetFeatureType(), CLog::Log(), LOGDEBUG, m_buttons, and PERIPHERALS::CAndroidJoystickTranslator::TranslateJoystickButton().
Referenced by InitializeButtonMap().
MapDpad()
bool CAndroidJoystickState::MapDpad (KODI::JOYSTICK::IButtonMap & buttonMap, int horizAxisId, int vertAxisId) const private
References KODI::JOYSTICK::IButtonMap::AddScalar(), KODI::GAME::CDefaultController::FEATURE_DOWN, KODI::GAME::CDefaultController::FEATURE_LEFT, KODI::GAME::CDefaultController::FEATURE_RIGHT, KODI::GAME::CDefaultController::FEATURE_UP, GetAxesIndex(), KODI::JOYSTICK::IButtonMap::GetFeature(), CLog::Log(), LOGDEBUG, m_axes, and success.
Referenced by InitializeButtonMap().
MapTrigger()
bool CAndroidJoystickState::MapTrigger (KODI::JOYSTICK::IButtonMap & buttonMap, int axisId, const std::string & triggerName) const private
References KODI::JOYSTICK::IButtonMap::AddScalar(), GetAxesIndex(), KODI::JOYSTICK::IButtonMap::GetFeature(), CLog::Log(), LOGDEBUG, and m_axes.
Referenced by InitializeButtonMap().
ProcessEvent()
bool CAndroidJoystickState::ProcessEvent (const AInputEvent * event)
Processes the given input event.
References JOYSTICK_STATE_BUTTON_PRESSED, JOYSTICK_STATE_BUTTON_UNPRESSED, CLog::Log(), LOGDEBUG, LOGWARNING, m_axes, m_deviceId, SetAxisValue(), SetButtonValue(), success, PERIPHERALS::CAndroidJoystickTranslator::TranslateKeyCode(), value, and values.
Scale()
float CAndroidJoystickState::Scale (float value, float max, float scaledMax) static private
References max, and value.
Referenced by SetAxisValue().
SetAxisValue()
bool CAndroidJoystickState::SetAxisValue (const std::vector< int > & axisIds, JOYSTICK_STATE_AXIS axisValue) private
References Contain(), Deadzone(), PERIPHERALS::CAndroidJoystickState::JoystickAxis::flat, GetAxesIndex(), GetAxisCount(), m_analogState, m_axes, PERIPHERALS::CAndroidJoystickState::JoystickAxis::max, PERIPHERALS::CAndroidJoystickState::JoystickAxis::min, and Scale().
Referenced by ProcessEvent().
SetButtonValue()
bool CAndroidJoystickState::SetButtonValue (int axisId, JOYSTICK_STATE_BUTTON buttonValue) private
References GetAxesIndex(), GetButtonCount(), m_buttons, m_deviceId, m_digitalEvents, and m_eventMutex.
Referenced by ProcessEvent().
Member Data Documentation
m_analogState
std::vector<JOYSTICK_STATE_AXIS> PERIPHERALS::CAndroidJoystickState::m_analogState private
Referenced by Deinitialize(), GetAxisEvents(), Initialize(), and SetAxisValue().
m_axes
JoystickAxes PERIPHERALS::CAndroidJoystickState::m_axes private
Referenced by Deinitialize(), GetAxisCount(), Initialize(), InitializeButtonMap(), MapAnalogStick(), MapDpad(), MapTrigger(), ProcessEvent(), and SetAxisValue().
m_buttons
JoystickAxes PERIPHERALS::CAndroidJoystickState::m_buttons private
Referenced by Deinitialize(), GetButtonCount(), Initialize(), InitializeButtonMap(), MapButton(), and SetButtonValue().
m_deviceId
int PERIPHERALS::CAndroidJoystickState::m_deviceId = -1 private
Referenced by GetAxisEvents(), GetDeviceId(), Initialize(), ProcessEvent(), and SetButtonValue().
m_digitalEvents
std::vector<kodi::addon::PeripheralEvent> PERIPHERALS::CAndroidJoystickState::m_digitalEvents private
Referenced by Deinitialize(), GetButtonEvents(), and SetButtonValue().
m_eventMutex
CCriticalSection PERIPHERALS::CAndroidJoystickState::m_eventMutex private
Referenced by GetButtonEvents(), and SetButtonValue().
The documentation for this class was generated from the following files:
AndroidJoystickState.h
AndroidJoystickState.cpp