Kodi Documentation: CGUIListItemLayout Class Reference
CGUIListItemLayout Class Reference final
#include <GUIListItemLayout.h>
Public Member Functions
CGUIListItemLayout ()
CGUIListItemLayout (const CGUIListItemLayout &from)
CGUIListItemLayout (const CGUIListItemLayout &from, CGUIControl *control)
void LoadLayout (TiXmlElement *layout, int context, bool focused, float maxWidth, float maxHeight)
void Process (CGUIListItem *item, int parentID, unsigned int currentTime, CDirtyRegionList &dirtyregions)
void Render (CGUIListItem *item, int parentID)
float Size (ORIENTATION orientation) const
unsigned int GetFocusedItem () const
void SetFocusedItem (unsigned int focus)
bool IsAnimating (ANIMATION_TYPE animType)
void ResetAnimation (ANIMATION_TYPE animType)
void SetInvalid ()
void FreeResources (bool immediately=false)
void SetParentControl (CGUIControl *control)
void AssignDepth ()
void CreateListControlLayouts (float width, float height, bool focused, const CLabelInfo &labelInfo, const CLabelInfo &labelInfo2, const CTextureInfo &texture, const CTextureInfo &textureFocus, float texHeight, float iconWidth, float iconHeight, const std::string &nofocusCondition, const std::string &focusCondition)
void SetWidth (float width)
void SetHeight (float height)
void SelectItemFromPoint (const CPoint &point)
bool MoveLeft ()
bool MoveRight ()
bool CheckCondition ()
Protected Member Functions
void LoadControl (TiXmlElement *child, CGUIControlGroup *group)
Protected Attributes
CGUIListGroup m_group
float m_width {0}
float m_height {0}
bool m_focused {false}
bool m_invalidated {true}
INFO::InfoPtr m_condition
KODI::GUILIB::GUIINFO::CGUIInfoBool m_isPlaying
std::chrono::milliseconds m_infoUpdateMillis
XbmcThreads::EndTime m_infoUpdateTimeout
Constructor & Destructor Documentation
CGUIListItemLayout() [1/3]
CGUIListItemLayout::CGUIListItemLayout ()
References m_group, and CGUIControl::SetPushUpdates().
CGUIListItemLayout() [2/3]
CGUIListItemLayout::CGUIListItemLayout (const CGUIListItemLayout & from) explicit
CGUIListItemLayout() [3/3]
CGUIListItemLayout::CGUIListItemLayout (const CGUIListItemLayout & from, CGUIControl * control) explicit
References CGUIControlGroup::AllocResources(), m_group, m_infoUpdateMillis, m_infoUpdateTimeout, and CGUIControl::SetParentControl().
Member Function Documentation
AssignDepth()
void CGUIListItemLayout::AssignDepth ()
References CGUIControlGroup::AssignDepth(), and m_group.
Referenced by PVR::CGUIEPGGridContainer::AssignItemDepth().
CheckCondition()
bool CGUIListItemLayout::CheckCondition ()
References INFO::DEFAULT_CONTEXT, and m_condition.
Referenced by CGUIBaseContainer::UpdateVisibility().
CreateListControlLayouts()
void CGUIListItemLayout::CreateListControlLayouts (float width, float height, bool focused, const CLabelInfo & labelInfo, const CLabelInfo & labelInfo2, const CTextureInfo & texture, const CTextureInfo & textureFocus, float texHeight, float iconWidth, float iconHeight, const std::string & nofocusCondition, const std::string & focusCondition)
References CGUIListGroup::AddControl(), CAspectRatio::AR_KEEP, CGUIControl::FOCUS, CGUIControl::GetParentID(), label, m_focused, m_group, m_height, m_isPlaying, m_width, CLabelInfo::offsetX, CLabelInfo::offsetY, KODI::GUILIB::GUIINFO::CGUIInfoBool::Parse(), CGUIImage::SetAspectRatio(), CGUIImage::SetInfo(), and CGUIControl::SetVisibleCondition().
FreeResources()
void CGUIListItemLayout::FreeResources (bool immediately = false)
References CGUIControlGroup::FreeResources(), and m_group.
GetFocusedItem()
unsigned int CGUIListItemLayout::GetFocusedItem () const
References CGUIListGroup::GetFocusedItem(), and m_group.
Referenced by CGUIBaseContainer::GetCondition(), CGUIBaseContainer::OnClick(), and PVR::CGUIEPGGridContainer::OnClick().
IsAnimating()
bool CGUIListItemLayout::IsAnimating (ANIMATION_TYPE animType)
References CGUIControlGroup::IsAnimating(), and m_group.
Referenced by PVR::CGUIEPGGridContainer::AssignItemDepth(), CGUIBaseContainer::RenderItem(), and PVR::CGUIEPGGridContainer::RenderItem().
LoadControl()
void CGUIListItemLayout::LoadControl (TiXmlElement * child, CGUIControlGroup * group) protected
References CGUIControlFactory::Create(), CGUIControl::IsGroup(), and LoadControl().
Referenced by LoadControl(), and LoadLayout().
LoadLayout()
void CGUIListItemLayout::LoadLayout (TiXmlElement * layout, int context, bool focused, float maxWidth, float maxHeight)
References CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), LoadControl(), m_condition, m_focused, m_group, m_height, m_infoUpdateMillis, m_infoUpdateTimeout, m_isPlaying, m_width, KODI::GUILIB::GUIINFO::CGUIInfoBool::Parse(), CGUIInfoManager::Register(), CGUIControl::SetHeight(), and CGUIControl::SetWidth().
MoveLeft()
bool CGUIListItemLayout::MoveLeft ()
References m_group, and CGUIListGroup::MoveLeft().
Referenced by CGUIBaseContainer::OnLeft().
MoveRight()
bool CGUIListItemLayout::MoveRight ()
References m_group, and CGUIListGroup::MoveRight().
Referenced by CGUIBaseContainer::OnRight().
Process()
void CGUIListItemLayout::Process (CGUIListItem * item, int parentID, unsigned int currentTime, CDirtyRegionList & dirtyregions)
References INFO::DEFAULT_CONTEXT, CGUIControl::DoProcess(), CGUIListItem::IsFileItem(), CGUIListItem::IsSelected(), m_focused, m_group, m_infoUpdateMillis, m_infoUpdateTimeout, m_invalidated, m_isPlaying, CGUIListGroup::SetInvalid(), CGUIListGroup::SetState(), KODI::GUILIB::GUIINFO::CGUIInfoBool::Update(), CGUIListGroup::UpdateInfo(), and CGUIListGroup::UpdateVisibility().
Render()
void CGUIListItemLayout::Render (CGUIListItem * item, int parentID)
References CGUIControl::DoRender(), and m_group.
Referenced by CGUIBaseContainer::RenderItem(), and PVR::CGUIEPGGridContainer::RenderItem().
ResetAnimation()
void CGUIListItemLayout::ResetAnimation (ANIMATION_TYPE animType)
References m_group, and CGUIListGroup::ResetAnimation().
SelectItemFromPoint()
void CGUIListItemLayout::SelectItemFromPoint (const CPoint & point)
References m_group, and CGUIListGroup::SelectItemFromPoint().
Referenced by CGUIListContainer::SelectItemFromPoint().
SetFocusedItem()
void CGUIListItemLayout::SetFocusedItem (unsigned int focus)
References m_group, and CGUIListGroup::SetFocusedItem().
SetHeight()
void CGUIListItemLayout::SetHeight (float height)
References CGUIListGroup::EnlargeHeight(), m_group, m_height, and SetInvalid().
Referenced by PVR::CGUIEPGGridContainer::UpdateLayout().
SetInvalid()
void CGUIListItemLayout::SetInvalid () inline
References m_invalidated.
Referenced by SetHeight(), CGUIListItem::SetInvalid(), and SetWidth().
SetParentControl()
void CGUIListItemLayout::SetParentControl (CGUIControl * control) inline
References m_group, and CGUIControl::SetParentControl().
SetWidth()
void CGUIListItemLayout::SetWidth (float width)
References CGUIListGroup::EnlargeWidth(), m_group, m_width, and SetInvalid().
Referenced by PVR::CGUIEPGGridContainer::UpdateLayout().
Size()
float CGUIListItemLayout::Size (ORIENTATION orientation) const
References HORIZONTAL, m_height, and m_width.
Referenced by CGUIBaseContainer::CalculateLayout(), CGUIPanelContainer::CalculateLayout(), PVR::CGUIEPGGridContainer::GetChannelScrollOffset(), PVR::CGUIEPGGridContainer::GetChannelScrollOffsetPos(), CGUIFixedListContainer::GetCursorFromPoint(), CGUIListContainer::GetCursorFromPoint(), CGUIPanelContainer::GetCursorFromPoint(), CGUIBaseContainer::GetListItem(), PVR::CGUIEPGGridContainer::HandleChannels(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), PVR::CGUIEPGGridContainer::HandleRuler(), CGUIBaseContainer::InsideLayout(), CGUIBaseContainer::OnMouseEvent(), PVR::CGUIEPGGridContainer::OnMouseEvent(), CGUIBaseContainer::Process(), CGUIPanelContainer::Process(), CGUIBaseContainer::Render(), CGUIPanelContainer::Render(), PVR::CGUIEPGGridContainer::ScrollToChannelOffset(), CGUIBaseContainer::ScrollToOffset(), CGUIFixedListContainer::SelectItemFromPoint(), CGUIWrappingListContainer::SelectItemFromPoint(), PVR::CGUIEPGGridContainer::UpdateLayout(), PVR::CGUIEPGGridContainer::UpdateScrollOffset(), CGUIFixedListContainer::ValidateOffset(), CGUIListContainer::ValidateOffset(), and CGUIPanelContainer::ValidateOffset().
Member Data Documentation
m_condition
INFO::InfoPtr CGUIListItemLayout::m_condition protected
Referenced by CheckCondition(), and LoadLayout().
m_focused
bool CGUIListItemLayout::m_focused {false} protected
Referenced by CreateListControlLayouts(), LoadLayout(), and Process().
m_group
CGUIListGroup CGUIListItemLayout::m_group protected
Referenced by AssignDepth(), CGUIListItemLayout(), CGUIListItemLayout(), CreateListControlLayouts(), FreeResources(), GetFocusedItem(), IsAnimating(), LoadLayout(), MoveLeft(), MoveRight(), Process(), Render(), ResetAnimation(), SelectItemFromPoint(), SetFocusedItem(), SetHeight(), SetParentControl(), and SetWidth().
m_height
float CGUIListItemLayout::m_height {0} protected
Referenced by CreateListControlLayouts(), LoadLayout(), SetHeight(), and Size().
m_infoUpdateMillis
std::chrono::milliseconds CGUIListItemLayout::m_infoUpdateMillis protected
Initial value:
=
      XbmcThreads::EndTime<decltype(m_infoUpdateMillis)>::Max()
Referenced by CGUIListItemLayout(), LoadLayout(), and Process().
m_infoUpdateTimeout
XbmcThreads::EndTime CGUIListItemLayout::m_infoUpdateTimeout protected
Referenced by CGUIListItemLayout(), LoadLayout(), and Process().
m_invalidated
bool CGUIListItemLayout::m_invalidated {true} protected
Referenced by Process(), and SetInvalid().
m_isPlaying
KODI::GUILIB::GUIINFO::CGUIInfoBool CGUIListItemLayout::m_isPlaying protected
Referenced by CreateListControlLayouts(), LoadLayout(), and Process().
m_width
float CGUIListItemLayout::m_width {0} protected
Referenced by CreateListControlLayouts(), LoadLayout(), SetWidth(), and Size().
The documentation for this class was generated from the following files:
GUIListItemLayout.h
GUIListItemLayout.cpp