Kodi Documentation: CBaseEvent Class Reference
CBaseEvent Class Reference
#include <BaseEvent.h>
Public Member Functions
~CBaseEvent () override=default
std::string GetIdentifier () const override
EventLevel GetLevel () const override
std::string GetLabel () const override
std::string GetIcon () const override
std::string GetDescription () const override
std::string GetDetails () const override
std::string GetExecutionLabel () const override
CDateTime GetDateTime () const override
bool CanExecute () const override
void ToSortable (SortItem &sortable, Field field) const override
Public Member Functions inherited from IEvent
virtual ~IEvent ()=default
virtual const char * GetType () const =0
virtual bool Execute () const =0
Protected Member Functions
CBaseEvent (const std::string &identifier, const CVariant &label, const CVariant &description, EventLevel level=EventLevel::Information)
CBaseEvent (const std::string &identifier, const CVariant &label, const CVariant &description, const std::string &icon, EventLevel level=EventLevel::Information)
CBaseEvent (const std::string &identifier, const CVariant &label, const CVariant &description, const std::string &icon, const CVariant &details, EventLevel level=EventLevel::Information)
CBaseEvent (const std::string &identifier, const CVariant &label, const CVariant &description, const std::string &icon, const CVariant &details, const CVariant &executionLabel, EventLevel level=EventLevel::Information)
Protected Member Functions inherited from ISortable
~ISortable ()=default
Protected Attributes
EventLevel m_level
std::string m_identifier
std::string m_icon
CVariant m_label
CVariant m_description
CVariant m_details
CVariant m_executionLabel
Static Private Member Functions
static std::string VariantToLocalizedString (const CVariant &variant)
static uint64_t GetInternalTimestamp ()
Private Attributes
uint64_t m_timestamp
CDateTime m_dateTime
Constructor & Destructor Documentation
~CBaseEvent()
CBaseEvent::~CBaseEvent () override default
CBaseEvent() [1/4]
CBaseEvent::CBaseEvent (const std::string & identifier, const CVariant & label, const CVariant & description, EventLevel level = EventLevel::Information) protected
CBaseEvent() [2/4]
CBaseEvent::CBaseEvent (const std::string & identifier, const CVariant & label, const CVariant & description, const std::string & icon, EventLevel level = EventLevel::Information) protected
CBaseEvent() [3/4]
CBaseEvent::CBaseEvent (const std::string & identifier, const CVariant & label, const CVariant & description, const std::string & icon, const CVariant & details, EventLevel level = EventLevel::Information) protected
CBaseEvent() [4/4]
CBaseEvent::CBaseEvent (const std::string & identifier, const CVariant & label, const CVariant & description, const std::string & icon, const CVariant & details, const CVariant & executionLabel, EventLevel level = EventLevel::Information) protected
Member Function Documentation
CanExecute()
bool CBaseEvent::CanExecute () const inline override virtual
Implements IEvent.
Reimplemented in CMediaLibraryEvent, and CNotificationEvent.
References GetExecutionLabel().
GetDateTime()
CDateTime CBaseEvent::GetDateTime () const inline override virtual
Implements IEvent.
References m_dateTime.
GetDescription()
std::string CBaseEvent::GetDescription () const override virtual
Implements IEvent.
References m_description, and VariantToLocalizedString().
GetDetails()
std::string CBaseEvent::GetDetails () const override virtual
Implements IEvent.
References m_details, and VariantToLocalizedString().
GetExecutionLabel()
std::string CBaseEvent::GetExecutionLabel () const override virtual
Implements IEvent.
Reimplemented in CMediaLibraryEvent.
References m_executionLabel, and VariantToLocalizedString().
Referenced by CanExecute(), CAddonManagementEvent::GetExecutionLabel(), and CMediaLibraryEvent::GetExecutionLabel().
GetIcon()
std::string CBaseEvent::GetIcon () const inline override virtual
Implements IEvent.
References m_icon.
GetIdentifier()
std::string CBaseEvent::GetIdentifier () const inline override virtual
Implements IEvent.
References m_identifier.
GetInternalTimestamp()
uint64_t CBaseEvent::GetInternalTimestamp () static private
GetLabel()
std::string CBaseEvent::GetLabel () const override virtual
Implements IEvent.
References m_label, and VariantToLocalizedString().
GetLevel()
EventLevel CBaseEvent::GetLevel () const inline override virtual
Implements IEvent.
References m_level.
ToSortable()
void CBaseEvent::ToSortable (SortItem & sortable, Field field) const override virtual
Implements IEvent.
References FieldDate, and m_timestamp.
VariantToLocalizedString()
std::string CBaseEvent::VariantToLocalizedString (const CVariant & variant) static private
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by GetDescription(), GetDetails(), GetExecutionLabel(), and GetLabel().
Member Data Documentation
m_dateTime
CDateTime CBaseEvent::m_dateTime private
Referenced by GetDateTime().
m_description
CVariant CBaseEvent::m_description protected
Referenced by GetDescription().
m_details
CVariant CBaseEvent::m_details protected
Referenced by GetDetails().
m_executionLabel
CVariant CBaseEvent::m_executionLabel protected
Referenced by GetExecutionLabel().
m_icon
std::string CBaseEvent::m_icon protected
Referenced by GetIcon().
m_identifier
std::string CBaseEvent::m_identifier protected
Referenced by GetIdentifier().
m_label
CVariant CBaseEvent::m_label protected
Referenced by GetLabel().
m_level
EventLevel CBaseEvent::m_level protected
Referenced by GetLevel().
m_timestamp
uint64_t CBaseEvent::m_timestamp private
Referenced by ToSortable().
The documentation for this class was generated from the following files:
BaseEvent.h
BaseEvent.cpp