Kodi Documentation: CGUIPlayerAnnouncementHandler Class Reference
CGUIPlayerAnnouncementHandler Class Reference
Handler for announcements of type player.
#include <GUIPlayerAnnouncementHandler.h>
Public Member Functions
CGUIPlayerAnnouncementHandler ()
~CGUIPlayerAnnouncementHandler ()
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Detailed Description
Handler for announcements of type player.
Constructor & Destructor Documentation
CGUIPlayerAnnouncementHandler()
CGUIPlayerAnnouncementHandler::CGUIPlayerAnnouncementHandler ()
References CServiceBroker::GetAnnouncementManager(), and ANNOUNCEMENT::Player.
~CGUIPlayerAnnouncementHandler()
CGUIPlayerAnnouncementHandler::~CGUIPlayerAnnouncementHandler ()
References CServiceBroker::GetAnnouncementManager().
Member Function Documentation
Announce()
void CGUIPlayerAnnouncementHandler::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References CGUIWindowManager::ActivateWindow(), data(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), GUI_MSG_VIDEO_MENU_STARTED, CGUIDialogKaiToast::QueueNotification(), and WINDOW_DIALOG_PLAYER_PROCESS_INFO.
The documentation for this class was generated from the following files:
GUIPlayerAnnouncementHandler.h
GUIPlayerAnnouncementHandler.cpp