Kodi Documentation: NetworkStartWaiter Class Reference
NetworkStartWaiter Class Reference
Public Member Functions
NetworkStartWaiter (unsigned settle_time_ms, const std::string &host)
bool SuccessWaiting () const override
Public Member Functions inherited from WaitCondition
virtual ~WaitCondition ()=default
Private Attributes
XbmcThreads::EndTime m_end
unsigned m_settle_time_ms
const std::string m_host
Constructor & Destructor Documentation
NetworkStartWaiter()
NetworkStartWaiter::NetworkStartWaiter (unsigned settle_time_ms, const std::string & host) inline
Member Function Documentation
SuccessWaiting()
bool NetworkStartWaiter::SuccessWaiting () const inline override virtual
Reimplemented from WaitCondition.
References CServiceBroker::GetNetwork(), CNetworkBase::HasInterfaceForIP(), and HostToIP().
Member Data Documentation
m_end
XbmcThreads::EndTime NetworkStartWaiter::m_end mutable private
m_host
const std::string NetworkStartWaiter::m_host private
m_settle_time_ms
unsigned NetworkStartWaiter::m_settle_time_ms private
The documentation for this class was generated from the following file:
WakeOnAccess.cpp