Kodi Documentation: WebServer.cpp File Reference
WebServer.cpp File Reference
#include "WebServer.h"
#include "CompileInfo.h"
#include "ServiceBroker.h"
#include "XBDateTime.h"
#include "filesystem/File.h"
#include "network/httprequesthandler/HTTPRequestHandlerUtils.h"
#include "network/httprequesthandler/IHTTPRequestHandler.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/FileUtils.h"
#include "utils/Mime.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/Variant.h"
#include "utils/log.h"
#include <algorithm>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <utility>
#include <inttypes.h>
Classes
struct HttpFileDownloadContext
Macros
#define MAX_POST_BUFFER_SIZE 2048
#define PAGE_FILE_NOT_FOUND "<html><head><title>File not found</title></head><body>File not found</body></html>"
#define NOT_SUPPORTED
#define HEADER_VALUE_NO_CACHE "no-cache"
#define HEADER_NEWLINE "\r\n"
Functions
static MHD_Response * create_response (size_t size, const void *data, int free, int copy)
static Logger GetMhdLogger ()
static void panicHandlerForMHD (void *unused, const char *file, unsigned int line, const char *reason)
static void logFromMHD (void *unused, const char *fmt, va_list ap)
Macro Definition Documentation
HEADER_NEWLINE
#define HEADER_NEWLINE "\r\n"
HEADER_VALUE_NO_CACHE
#define HEADER_VALUE_NO_CACHE "no-cache"
MAX_POST_BUFFER_SIZE
#define MAX_POST_BUFFER_SIZE 2048
NOT_SUPPORTED
#define NOT_SUPPORTED
Value:
  "<html><head><title>Not Supported</title></head><body>The method you are trying to use is not " \
  "supported by this server</body></html>"
PAGE_FILE_NOT_FOUND
#define PAGE_FILE_NOT_FOUND "<html><head><title>File not found</title></head><body>File not found</body></html>"
Function Documentation
create_response()
static MHD_Response * create_response (size_t size, const void * data, int free, int copy) static
Bug:
libmicrohttpd isn't const correct
References copy(), and data().
Referenced by CWebServer::AskForAuthentication(), CWebServer::CreateErrorResponse(), CWebServer::CreateMemoryDownloadResponse(), CWebServer::CreateRedirect(), and CWebServer::HandlePartialRequest().
GetMhdLogger()
static Logger GetMhdLogger () static
References CLog::GetLogger(), and CServiceBroker::GetLogging().
Referenced by logFromMHD(), and panicHandlerForMHD().
logFromMHD()
static void logFromMHD (void * unused, const char * fmt, va_list ap) static
References KODI::UTILS::StringUtils::FormatV(), and GetMhdLogger().
Referenced by CWebServer::StartMHD().
panicHandlerForMHD()
static void panicHandlerForMHD (void * unused, const char * file, unsigned int line, const char * reason) static
References GetMhdLogger().
Referenced by CWebServer::StartMHD().