Kodi Documentation: ADDON::Interface_GUIDialogKeyboard Struct Reference
ADDON::Interface_GUIDialogKeyboard Struct Reference
Global gui Add-on to Kodi callback functions.
#include <Keyboard.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static bool show_and_get_input_with_head (KODI_HANDLE kodiBase, const char *text_in, char **text_out, const char *heading, bool allow_empty_result, bool hidden_input, unsigned int auto_close_ms)
callback functions from add-on to kodi
static bool show_and_get_input (KODI_HANDLE kodiBase, const char *text_in, char **text_out, bool allow_empty_result, unsigned int auto_close_ms)
static bool show_and_get_new_password_with_head (KODI_HANDLE kodiBase, const char *password_in, char **password_out, const char *heading, bool allow_empty_result, unsigned int auto_close_ms)
static bool show_and_get_new_password (KODI_HANDLE kodiBase, const char *password_in, char **password_out, unsigned int auto_close_ms)
static bool show_and_verify_new_password_with_head (KODI_HANDLE kodiBase, char **password_out, const char *heading, bool allowEmpty, unsigned int auto_close_ms)
static bool show_and_verify_new_password (KODI_HANDLE kodiBase, char **password_out, unsigned int auto_close_ms)
static int show_and_verify_password (KODI_HANDLE kodiBase, const char *password_in, char **password_out, const char *heading, int retries, unsigned int auto_close_ms)
static bool show_and_get_filter (KODI_HANDLE kodiBase, const char *text_in, char **text_out, bool searching, unsigned int auto_close_ms)
static bool send_text_to_active_keyboard (KODI_HANDLE kodiBase, const char *text, bool close_keyboard)
static bool is_keyboard_activated (KODI_HANDLE kodiBase)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/dialogs/Keyboard.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIDialogKeyboard::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogKeyboard, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
Init()
void ADDON::Interface_GUIDialogKeyboard::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogKeyboard, is_keyboard_activated(), AddonToKodiFuncTable_kodi_gui_dialogKeyboard::is_keyboard_activated, AddonToKodiFuncTable_Addon::kodi_gui, send_text_to_active_keyboard(), AddonToKodiFuncTable_kodi_gui_dialogKeyboard::send_text_to_active_keyboard, show_and_get_filter(), AddonToKodiFuncTable_kodi_gui_dialogKeyboard::show_and_get_filter, show_and_get_input(), AddonToKodiFuncTable_kodi_gui_dialogKeyboard::show_and_get_input, show_and_get_input_with_head(), AddonToKodiFuncTable_kodi_gui_dialogKeyboard::show_and_get_input_with_head, show_and_get_new_password(), AddonToKodiFuncTable_kodi_gui_dialogKeyboard::show_and_get_new_password, show_and_get_new_password_with_head(), AddonToKodiFuncTable_kodi_gui_dialogKeyboard::show_and_get_new_password_with_head, show_and_verify_new_password(), AddonToKodiFuncTable_kodi_gui_dialogKeyboard::show_and_verify_new_password, show_and_verify_new_password_with_head(), AddonToKodiFuncTable_kodi_gui_dialogKeyboard::show_and_verify_new_password_with_head, show_and_verify_password(), AddonToKodiFuncTable_kodi_gui_dialogKeyboard::show_and_verify_password, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
is_keyboard_activated()
bool ADDON::Interface_GUIDialogKeyboard::is_keyboard_activated (KODI_HANDLE kodiBase) static
References CGUIKeyboardFactory::isKeyboardActivated(), CLog::Log(), and LOGERROR.
Referenced by Init().
send_text_to_active_keyboard()
bool ADDON::Interface_GUIDialogKeyboard::send_text_to_active_keyboard (KODI_HANDLE kodiBase, const char * text, bool close_keyboard) static
References CLog::Log(), LOGERROR, CGUIKeyboardFactory::SendTextToActiveKeyboard(), and text.
Referenced by Init().
show_and_get_filter()
bool ADDON::Interface_GUIDialogKeyboard::show_and_get_filter (KODI_HANDLE kodiBase, const char * text_in, char ** text_out, bool searching, unsigned int auto_close_ms) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIKeyboardFactory::ShowAndGetFilter().
Referenced by Init().
show_and_get_input()
bool ADDON::Interface_GUIDialogKeyboard::show_and_get_input (KODI_HANDLE kodiBase, const char * text_in, char ** text_out, bool allow_empty_result, unsigned int auto_close_ms) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIKeyboardFactory::ShowAndGetInput().
Referenced by Init().
show_and_get_input_with_head()
bool ADDON::Interface_GUIDialogKeyboard::show_and_get_input_with_head (KODI_HANDLE kodiBase, const char * text_in, char ** text_out, const char * heading, bool allow_empty_result, bool hidden_input, unsigned int auto_close_ms) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIKeyboardFactory::ShowAndGetInput().
Referenced by Init().
show_and_get_new_password()
bool ADDON::Interface_GUIDialogKeyboard::show_and_get_new_password (KODI_HANDLE kodiBase, const char * password_in, char ** password_out, unsigned int auto_close_ms) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIKeyboardFactory::ShowAndGetNewPassword().
Referenced by Init().
show_and_get_new_password_with_head()
bool ADDON::Interface_GUIDialogKeyboard::show_and_get_new_password_with_head (KODI_HANDLE kodiBase, const char * password_in, char ** password_out, const char * heading, bool allow_empty_result, unsigned int auto_close_ms) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIKeyboardFactory::ShowAndGetNewPassword().
Referenced by Init().
show_and_verify_new_password()
bool ADDON::Interface_GUIDialogKeyboard::show_and_verify_new_password (KODI_HANDLE kodiBase, char ** password_out, unsigned int auto_close_ms) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIKeyboardFactory::ShowAndVerifyNewPassword().
Referenced by Init().
show_and_verify_new_password_with_head()
bool ADDON::Interface_GUIDialogKeyboard::show_and_verify_new_password_with_head (KODI_HANDLE kodiBase, char ** password_out, const char * heading, bool allowEmpty, unsigned int auto_close_ms) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIKeyboardFactory::ShowAndVerifyNewPassword().
Referenced by Init().
show_and_verify_password()
int ADDON::Interface_GUIDialogKeyboard::show_and_verify_password (KODI_HANDLE kodiBase, const char * password_in, char ** password_out, const char * heading, int retries, unsigned int auto_close_ms) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIKeyboardFactory::ShowAndVerifyPassword().
Referenced by Init().
The documentation for this struct was generated from the following files:
addons/interfaces/gui/dialogs/Keyboard.h
addons/interfaces/gui/dialogs/Keyboard.cpp