Kodi Documentation: TestEdl.cpp File Reference
TestEdl.cpp File Reference
#include "FileItem.h"
#include "ServiceBroker.h"
#include "cores/VideoPlayer/Edl.h"
#include "settings/AdvancedSettings.h"
#include "settings/SettingsComponent.h"
#include "test/TestUtils.h"
#include <chrono>
#include <cmath>
#include <gtest/gtest.h>
Classes
class TestEdl
Functions
TEST_F (TestEdl, TestParsingMplayerTimeBasedEDL)
TEST_F (TestEdl, TestParsingMplayerTimeBasedInterleavedCutsEDL)
TEST_F (TestEdl, TestParsingMplayerFrameBasedEDL)
TEST_F (TestEdl, TestParsingMplayerTimeBasedMixedEDL)
TEST_F (TestEdl, TestParsingVideoRedoEDL)
TEST_F (TestEdl, TestSnapStreamEDL)
TEST_F (TestEdl, TestComSkipVersion1EDL)
TEST_F (TestEdl, TestComSkipVersion2EDL)
TEST_F (TestEdl, TestRuntimeSetEDL)
TEST_F (TestEdl, TestCommBreakAdvancedSettings)
TEST_F (TestEdl, TestCommBreakAdvancedSettingsRemoveSmallCommbreaks)
TEST_F (TestEdl, TestMergeSmallCommbreaks)
TEST_F (TestEdl, TestMergeSmallCommbreaksAdvanced)
Function Documentation
TEST_F() [1/13]
TEST_F (TestEdl , TestCommBreakAdvancedSettings)
References CEdl::Clear(), EXPECT_EQ(), CEdl::GetEditList(), CServiceBroker::GetSettingsComponent(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [2/13]
TEST_F (TestEdl , TestCommBreakAdvancedSettingsRemoveSmallCommbreaks)
References EXPECT_EQ(), CEdl::GetEditList(), CServiceBroker::GetSettingsComponent(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [3/13]
TEST_F (TestEdl , TestComSkipVersion1EDL)
References EXPECT_EQ(), CEdl::GetCutMarkers(), CEdl::GetEditList(), CEdl::GetSceneMarkers(), CEdl::HasEdits(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [4/13]
TEST_F (TestEdl , TestComSkipVersion2EDL)
References EXPECT_EQ(), CEdl::GetCutMarkers(), CEdl::GetEditList(), CEdl::GetSceneMarkers(), CEdl::HasEdits(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [5/13]
TEST_F (TestEdl , TestMergeSmallCommbreaks)
References EXPECT_EQ(), CEdl::GetEditList(), CServiceBroker::GetSettingsComponent(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [6/13]
TEST_F (TestEdl , TestMergeSmallCommbreaksAdvanced)
References EXPECT_EQ(), CEdl::GetEditList(), CServiceBroker::GetSettingsComponent(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [7/13]
TEST_F (TestEdl , TestParsingMplayerFrameBasedEDL)
References EXPECT_EQ(), CEdl::GetEditList(), CEdl::GetSceneMarkers(), CEdl::GetTotalCutTime(), CEdl::HasCuts(), CEdl::HasEdits(), CEdl::HasSceneMarker(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [8/13]
TEST_F (TestEdl , TestParsingMplayerTimeBasedEDL)
References BACKWARD, EXPECT_EQ(), EXPECT_NE(), FORWARD, CEdl::GetCutMarkers(), CEdl::GetEditList(), CEdl::GetNextSceneMarker(), CEdl::GetRawEditList(), CEdl::GetSceneMarkers(), CEdl::GetTimeAfterRestoringCuts(), CEdl::GetTimeWithoutCuts(), CEdl::GetTotalCutTime(), CEdl::HasCuts(), CEdl::HasEdits(), CEdl::HasSceneMarker(), CEdl::InEdit(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [9/13]
TEST_F (TestEdl , TestParsingMplayerTimeBasedInterleavedCutsEDL)
References EXPECT_EQ(), CEdl::GetCutMarkers(), CEdl::GetEditList(), CEdl::GetRawEditList(), CEdl::GetTimeWithoutCuts(), CEdl::GetTotalCutTime(), CEdl::HasCuts(), CEdl::HasEdits(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [10/13]
TEST_F (TestEdl , TestParsingMplayerTimeBasedMixedEDL)
References EXPECT_EQ(), CEdl::GetEditList(), CEdl::GetSceneMarkers(), CEdl::GetTotalCutTime(), CEdl::HasCuts(), CEdl::HasEdits(), CEdl::HasSceneMarker(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [11/13]
TEST_F (TestEdl , TestParsingVideoRedoEDL)
References EXPECT_EQ(), CEdl::GetCutMarkers(), CEdl::GetEditList(), CEdl::GetRawEditList(), CEdl::GetSceneMarkers(), CEdl::HasCuts(), CEdl::HasEdits(), CEdl::HasSceneMarker(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.
TEST_F() [12/13]
TEST_F (TestEdl , TestRuntimeSetEDL)
References EXPECT_EQ(), CEdl::GetLastEditActionType(), CEdl::GetLastEditTime(), CEdl::SetLastEditActionType(), and CEdl::SetLastEditTime().
TEST_F() [13/13]
TEST_F (TestEdl , TestSnapStreamEDL)
References EXPECT_EQ(), CEdl::GetCutMarkers(), CEdl::GetEditList(), CEdl::GetSceneMarkers(), CEdl::HasEdits(), CEdl::ReadEditDecisionLists(), CFileItem::SetPath(), and XBMC_REF_FILE_PATH.