Kodi Documentation: KODI::KEYMAP::CKeyboardTranslator Class Reference
KODI::KEYMAP::CKeyboardTranslator Class Reference
#include <KeyboardTranslator.h>
Static Public Member Functions
static uint32_t TranslateButton (const tinyxml2::XMLElement *pButton)
static uint32_t TranslateString (const std::string &szButton)
Member Function Documentation
TranslateButton()
uint32_t CKeyboardTranslator::TranslateButton (const tinyxml2::XMLElement * pButton) static
References CLog::Log(), LOGDEBUG, LOGERROR, CKey::MODIFIER_ALT, CKey::MODIFIER_CTRL, CKey::MODIFIER_LONG, CKey::MODIFIER_META, CKey::MODIFIER_SHIFT, CKey::MODIFIER_SUPER, and TranslateString().
Referenced by KODI::KEYMAP::CButtonTranslator::MapWindowActions().
TranslateString()
uint32_t CKeyboardTranslator::TranslateString (const std::string & szButton) static
References KEY_VKEY, CLog::Log(), LOGERROR, KODI::KEYBOARD::KeyTable::LookupName(), and KODI::KEYBOARD::XBMCKEYTABLE::vkey.
Referenced by TranslateButton(), and KODI::KEYMAP::CButtonTranslator::TranslateString().
The documentation for this class was generated from the following files:
keymaps/keyboard/KeyboardTranslator.h
keymaps/keyboard/KeyboardTranslator.cpp