Kodi Documentation: ADDON::CAddon Class Reference
ADDON::CAddon Class Reference
#include <Addon.h>
Classes
struct CSettingsData
Public Member Functions
CAddon (const AddonInfoPtr &addonInfo, AddonType addonType)
~CAddon () override=default
AddonType MainType () const override
To get the main type of this addon.
AddonType Type () const override
To get the on this CAddon class processed addon type.
bool HasType (AddonType type) const override
To check complete addon (not only this) contains a type.
bool HasMainType (AddonType type) const override
To check complete addon (not only this) has a specific type defined in its first extension point including the provided subcontent e.g. video or audio.
const CAddonType * Type (AddonType type) const
The get for given addon type information and extension data.
std::string ID () const override
std::string Name () const override
bool IsInUse () const override
bool IsBinary () const override
CAddonVersion Version () const override
CAddonVersion MinVersion () const override
std::string Summary () const override
std::string Description () const override
std::string Path () const override
std::string Profile () const override
std::string LibPath () const override
std::string Author () const override
std::string ChangeLog () const override
std::string Icon () const override
ArtMap Art () const override
std::vector< std::string > Screenshots () const override
std::string Disclaimer () const override
AddonLifecycleState LifecycleState () const override
std::string LifecycleStateDescription () const override
CDateTime InstallDate () const override
CDateTime LastUpdated () const override
CDateTime LastUsed () const override
std::string Origin () const override
std::string OriginName () const override
uint64_t PackageSize () const override
const InfoMap & ExtraInfo () const override
const std::vector< DependencyInfo > & GetDependencies () const override
std::string FanArt () const override
bool SupportsMultipleInstances () const override
Check add-on for support from independent work instances.
AddonInstanceSupport InstanceUseType () const override
Return the used instance path type of the add-on type.
std::vector< AddonInstanceId > GetKnownInstanceIds () const override
Gives active, independently working instance identifiers for this add-on.
bool SupportsInstanceSettings () const override
Check whether the add-on supports individual settings per add-on instance.
bool DeleteInstanceSettings (AddonInstanceId instance) override
Delete selected instance settings from storage.
bool CanHaveAddonOrInstanceSettings () override
Check whether this add-on can be configured by the user.
bool HasSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Check whether this add-on can be configured by the user.
bool HasUserSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Check whether the user has configured this add-on or not.
bool SaveSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Save any user configured settings.
void UpdateSetting (const std::string &key, const std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new value.
bool UpdateSettingBool (const std::string &key, bool value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new boolean value.
bool UpdateSettingInt (const std::string &key, int value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new integer value.
bool UpdateSettingNumber (const std::string &key, double value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new number value.
bool UpdateSettingString (const std::string &key, const std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new string value.
std::string GetSetting (const std::string &key, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value.
bool GetSettingBool (const std::string &key, bool &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as boolean.
bool GetSettingInt (const std::string &key, int &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as integer.
bool GetSettingNumber (const std::string &key, double &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as number.
bool GetSettingString (const std::string &key, std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as string.
std::shared_ptr< CAddonSettings > GetSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
CAddonVersion GetDependencyVersion (const std::string &dependencyID) const override
get the required version of a dependency.
bool MeetsVersion (const CAddonVersion &versionMin, const CAddonVersion &version) const override
return whether or not this addon satisfies the given version requirements
bool ReloadSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
void ResetSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
AddonPtr GetRunningInstance () const override
retrieve the running instance of an add-on if it persists while running.
void OnPreInstall () override
void OnPostInstall (bool update, bool modal) override
void OnPreUnInstall () override
void OnPostUnInstall () override
Public Member Functions inherited from ADDON::IAddon
virtual ~IAddon ()=default
Protected Member Functions
virtual bool SettingsInitialized (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether or not the settings have been initialized.
virtual bool SettingsLoaded (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether or not the settings have been loaded.
bool LoadSettings (bool bForce, bool loadUserSettings, AddonInstanceId id=ADDON_SETTINGS_ID)
Load the default settings and override these with any previously configured user settings.
virtual bool LoadUserSettings (AddonInstanceId id=ADDON_SETTINGS_ID)
Load the user settings.
virtual bool HasSettingsToSave (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether there are settings to be saved.
virtual bool SettingsFromXML (const CXBMCTinyXML &doc, bool loadDefaults, AddonInstanceId id=ADDON_SETTINGS_ID)
Parse settings from an XML document.
virtual bool SettingsToXML (CXBMCTinyXML &doc, AddonInstanceId id=ADDON_SETTINGS_ID) const
Write settings into an XML document.
Protected Attributes
const AddonInfoPtr m_addonInfo
Private Member Functions
bool InitSettings (AddonInstanceId id)
std::shared_ptr< CAddonSettings > FindInstanceSettings (AddonInstanceId id) const
Private Attributes
std::unordered_map< AddonInstanceId, CSettingsData > m_settings
const AddonType m_type
Constructor & Destructor Documentation
CAddon()
ADDON::CAddon::CAddon (const AddonInfoPtr & addonInfo, AddonType addonType) explicit
~CAddon()
ADDON::CAddon::~CAddon () override default
Member Function Documentation
Art()
ArtMap ADDON::CAddon::Art () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Author()
std::string ADDON::CAddon::Author () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by ADDON::Interface_GUIWindow::create(), ADDON::Interface_Base::get_addon_info(), and KODI::GAME::CGameClient::LogException().
CanHaveAddonOrInstanceSettings()
bool ADDON::CAddon::CanHaveAddonOrInstanceSettings () override virtual
Check whether this add-on can be configured by the user.
Returns
true if the add-on has settings, false otherwise
Implements ADDON::IAddon.
Reimplemented in KODI::GAME::CController.
References ADDON::ADDON_SETTINGS_ID, HasSettings(), and SupportsInstanceSettings().
ChangeLog()
std::string ADDON::CAddon::ChangeLog () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by ADDON::Interface_Base::get_addon_info().
DeleteInstanceSettings()
bool ADDON::CAddon::DeleteInstanceSettings (AddonInstanceId instance) override virtual
Delete selected instance settings from storage.
The related instance-settings-[0-9...].xml file will be deleted by this method.
Parameters
[in] instance Instance identifier to use.
Returns
true on success, false otherwise.
Implements ADDON::IAddon.
References ADDON::ADDON_SETTINGS_ID, m_settings, and ResetSettings().
Description()
std::string ADDON::CAddon::Description () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by ADDON::Interface_Base::get_addon_info().
Disclaimer()
std::string ADDON::CAddon::Disclaimer () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by ADDON::Interface_Base::get_addon_info().
ExtraInfo()
const InfoMap & ADDON::CAddon::ExtraInfo () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
FanArt()
std::string ADDON::CAddon::FanArt () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by ADDON::Interface_Base::get_addon_info().
FindInstanceSettings()
std::shared_ptr< CAddonSettings > ADDON::CAddon::FindInstanceSettings (AddonInstanceId id) const private
References m_settings.
Referenced by InitSettings(), SettingsInitialized(), and SettingsLoaded().
GetDependencies()
const std::vector< DependencyInfo > & ADDON::CAddon::GetDependencies () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by KODI::GAME::CGameClientInput::GetControllers(), KODI::GAME::CGameClient::GetMissingResource(), KODI::GAME::CGameClientProperties::GetProxyAddons(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), and ADDON::CScraper::Load().
GetDependencyVersion()
CAddonVersion ADDON::CAddon::GetDependencyVersion (const std::string & dependencyID) const override virtual
get the required version of a dependency.
Parameters
dependencyID the addon ID of the dependency.
Returns
the version this addon requires.
Implements ADDON::IAddon.
References m_addonInfo.
GetKnownInstanceIds()
std::vector< AddonInstanceId > ADDON::CAddon::GetKnownInstanceIds () const override virtual
Gives active, independently working instance identifiers for this add-on.
This function is supported if add-on type has defined AddonInstanceUse::BY_SETTINGS and the associated settings are available.
Returns
List of active instance identifiers.
Settings Handling
Implements ADDON::IAddon.
References m_addonInfo.
GetRunningInstance()
AddonPtr ADDON::CAddon::GetRunningInstance () const inline override virtual
retrieve the running instance of an add-on if it persists while running.
Implements ADDON::IAddon.
Reimplemented in ADDON::CAddonDll, and KODI::GAME::CGameClient.
GetSetting()
std::string ADDON::CAddon::GetSetting (const std::string & key, AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Retrieve a particular settings value.
If a previously configured user setting is available, we return it's value, else we return the default (if available).
Parameters
[in] key the id of the setting to retrieve
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
the current value of the setting, or the default if the setting has yet to be configured.
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, UpdateSetting
Implements ADDON::IAddon.
References id, LoadSettings(), and m_settings.
Referenced by CScraperParser::ParseNext(), and CScraperParser::ReplaceBuffers().
GetSettingBool()
bool ADDON::CAddon::GetSettingBool (const std::string & key, bool & value, AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Retrieve a particular settings value as boolean.
If a previously configured user setting is available, we return it's value, else we return the default (if available).
Parameters
[in] key the id of the setting to retrieve
[out] value the current value of the setting, or the default if the setting has yet to be configured
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if the setting's value was retrieved, false otherwise.
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, UpdateSetting
Implements ADDON::IAddon.
References value.
GetSettingInt()
bool ADDON::CAddon::GetSettingInt (const std::string & key, int & value, AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Retrieve a particular settings value as integer.
If a previously configured user setting is available, we return it's value, else we return the default (if available)
Parameters
[in] key the id of the setting to retrieve
[out] value the current value of the setting, or the default if the setting has yet to be configured
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if the setting's value was retrieved, false otherwise.
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, UpdateSetting
Implements ADDON::IAddon.
References value.
GetSettingNumber()
bool ADDON::CAddon::GetSettingNumber (const std::string & key, double & value, AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Retrieve a particular settings value as number.
If a previously configured user setting is available, we return it's value, else we return the default (if available)
Parameters
[in] key the id of the setting to retrieve
[out] value the current value of the setting, or the default if the setting has yet to be configured
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if the setting's value was retrieved, false otherwise.
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, UpdateSetting
Implements ADDON::IAddon.
References value.
GetSettings()
std::shared_ptr< CAddonSettings > ADDON::CAddon::GetSettings (AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Implements ADDON::IAddon.
References id, InitSettings(), LoadSettings(), and m_settings.
Referenced by ADDON::Interface_Base::get_setting_bool(), ADDON::Interface_Base::get_setting_float(), ADDON::Interface_Base::get_setting_int(), ADDON::Interface_Base::get_setting_string(), ADDON::CScraper::GetPathSettingsAsJSON(), ADDON::GetSettingValue(), ADDON::Interface_Base::is_setting_using_default(), ADDON::CLanguageResource::IsInUse(), LoadSettings(), LoadUserSettings(), ADDON::CFontResource::OnPostInstall(), SettingsFromXML(), ADDON::CAddonDll::TransferSettings(), and ADDON::UpdateSettingValue().
GetSettingString()
bool ADDON::CAddon::GetSettingString (const std::string & key, std::string & value, AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Retrieve a particular settings value as string.
If a previously configured user setting is available, we return it's value, else we return the default (if available)
Parameters
[in] key the id of the setting to retrieve
[out] value the current value of the setting, or the default if the setting has yet to be configured
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if the setting's value was retrieved, false otherwise.
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, UpdateSetting
Implements ADDON::IAddon.
References value.
HasMainType()
bool ADDON::CAddon::HasMainType (AddonType type) const override virtual
To check complete addon (not only this) has a specific type defined in its first extension point including the provided subcontent e.g. video or audio.
Parameters
[in] type Type identifier to be checked
Returns
true in case the wanted type is the main type, false if not
Implements ADDON::IAddon.
References m_addonInfo.
HasSettings()
bool ADDON::CAddon::HasSettings (AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Check whether this add-on can be configured by the user.
Parameters
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if the add-on has settings, false otherwise
See also
LoadSettings, LoadUserSettings, SaveSettings, HasUserSettings, GetSetting, UpdateSetting
Implements ADDON::IAddon.
Reimplemented in ADDON::CSkinInfo.
References id, LoadSettings(), and m_settings.
Referenced by CanHaveAddonOrInstanceSettings(), ADDON::Interface_Base::get_setting_bool(), ADDON::Interface_Base::get_setting_float(), ADDON::Interface_Base::get_setting_int(), ADDON::Interface_Base::get_setting_string(), ADDON::GetSettingValue(), ADDON::Interface_Base::is_setting_using_default(), CScraperParser::ParseNext(), and ADDON::UpdateSettingValue().
HasSettingsToSave()
bool ADDON::CAddon::HasSettingsToSave (AddonInstanceId id = ADDON_SETTINGS_ID) const protected virtual
Whether there are settings to be saved.
Parameters
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if settings has to save
See also
SaveSettings
References SettingsLoaded().
Referenced by SaveSettings().
HasType()
bool ADDON::CAddon::HasType (AddonType type) const override virtual
To check complete addon (not only this) contains a type.
Note
This can be overridden by a child e.g. plugin to check for subtype e.g. video or music.
Parameters
[in] type The to checked type identifier
Returns
true in case the wanted type is supported, false if not
Implements ADDON::IAddon.
Reimplemented in ADDON::CPluginSource.
References m_addonInfo.
HasUserSettings()
bool ADDON::CAddon::HasUserSettings (AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Check whether the user has configured this add-on or not.
Parameters
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if previously saved settings are found, false otherwise
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, GetSetting, UpdateSetting
Implements ADDON::IAddon.
Reimplemented in ADDON::CSkinInfo.
References id, LoadSettings(), m_settings, and SettingsLoaded().
Icon()
std::string ADDON::CAddon::Icon () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by KODI::GAME::CControllerLayout::Deserialize(), and ADDON::Interface_Base::get_addon_info().
ID()
std::string ADDON::CAddon::ID () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by ADDON::Interface_GUIDialogProgress::abort(), ADDON::Interface_GUIControlSpin::add_int_label(), ADDON::Interface_GUIControlFadeLabel::add_label(), ADDON::Interface_GUIWindow::add_list_item(), ADDON::Interface_GUIControlSpin::add_string_label(), ADDON::Interface_Base::addon_log_msg(), KODI::GAME::CPhysicalFeature::CategoryLabel(), ADDON::CContextMenuAddon::CContextMenuAddon(), ADDON::Interface_GUIDialogFileBrowser::clear_file_list(), ADDON::Interface_GUIWindow::clear_item_list(), ADDON::Interface_GUIWindow::clear_properties(), ADDON::Interface_GUIWindow::clear_property(), ADDON::CScraper::ClearCache(), ADDON::Interface_GUIWindow::close(), KODI::RETRO::CReversiblePlayback::CommitSavestate(), ADDON::CPluginSource::CPluginSource(), ADDON::CAddonDll::Create(), ADDON::Interface_GUIWindow::create(), ADDON::CRepository::CRepository(), ADDON::CWebinterface::CWebinterface(), ADDON::Interface_GUIDialogExtendedProgress::delete_dialog(), ADDON::Interface_GUIDialogProgress::delete_dialog(), ADDON::Interface_GUIControlAddonRendering::destroy(), ADDON::Interface_GUIWindow::destroy(), ADDON::Interface_GUIWindow::do_modal(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), ADDON::CScraper::FindMovie(), ADDON::Interface_Base::get_addon_info(), ADDON::Interface_GUIListItem::get_art(), ADDON::Interface_GUIWindow::get_current_container_id(), ADDON::Interface_GUIWindow::get_current_list_position(), ADDON::Interface_GUIControlEdit::get_cursor_position(), ADDON::Interface_GUIControlSlider::get_description(), ADDON::Interface_GUIControlSettingsSlider::get_float_value(), ADDON::Interface_GUIControlSlider::get_float_value(), ADDON::Interface_GUIControlSpin::get_float_value(), ADDON::Interface_GUIWindow::get_focus_id(), ADDON::Interface_GUIControlSettingsSlider::get_int_value(), ADDON::Interface_GUIControlSlider::get_int_value(), ADDON::Interface_GUIControlSpin::get_int_value(), ADDON::Interface_GUIControlButton::get_label(), ADDON::Interface_GUIControlEdit::get_label(), ADDON::Interface_GUIControlFadeLabel::get_label(), ADDON::Interface_GUIControlLabel::get_label(), ADDON::Interface_GUIControlRadioButton::get_label(), ADDON::Interface_GUIListItem::get_label(), ADDON::Interface_GUIControlButton::get_label2(), ADDON::Interface_GUIListItem::get_label2(), ADDON::Interface_Base::get_lib_path(), ADDON::Interface_GUIWindow::get_list_item(), ADDON::Interface_GUIWindow::get_list_size(), ADDON::Interface_Base::get_localized_string(), ADDON::Interface_GUIListItem::get_path(), ADDON::Interface_GUIControlProgress::get_percentage(), ADDON::Interface_GUIControlSettingsSlider::get_percentage(), ADDON::Interface_GUIControlSlider::get_percentage(), ADDON::Interface_GUIDialogExtendedProgress::get_percentage(), ADDON::Interface_GUIDialogProgress::get_percentage(), ADDON::Interface_GUIListItem::get_property(), ADDON::Interface_GUIWindow::get_property(), ADDON::Interface_GUIWindow::get_property_bool(), ADDON::Interface_GUIWindow::get_property_double(), ADDON::Interface_GUIWindow::get_property_int(), ADDON::Interface_GUIControlSpin::get_string_value(), ADDON::Interface_Base::get_temp_path(), ADDON::Interface_GUIControlEdit::get_text(), ADDON::Interface_GUIControlTextBox::get_text(), ADDON::Interface_GUIDialogExtendedProgress::get_text(), ADDON::Interface_GUIDialogExtendedProgress::get_title(), ADDON::CScraper::GetAlbumDetails(), ADDON::CScraper::GetArtistDetails(), ADDON::CScraper::GetArtwork(), ADDON::CWebinterface::GetBaseLocation(), ADDON::Interface_GUIWindow::GetControl(), ADDON::CScraper::GetEpisodeList(), KODI::GAME::CGameClientInGameSaves::GetPath(), ADDON::CAddonDll::GetRunningInstance(), KODI::GAME::CGameClient::GetRunningInstance(), ADDON::CScraper::GetVideoDetails(), KODI::GAME::CGameClientInput::HasFeature(), KODI::GAME::CGameClient::Initialize(), KODI::GAME::CGameClientInput::InputEvent(), ADDON::CScraper::InternalRun(), ADDON::Interface_GUIDialogProgress::is_canceled(), ADDON::Interface_GUIDialogExtendedProgress::is_finished(), ADDON::Interface_GUIControlRadioButton::is_selected(), ADDON::Interface_GUIListItem::is_selected(), ADDON::CAddonDll::IsInUse(), ADDON::CLanguageResource::IsInUse(), ADDON::CScraper::IsInUse(), ADDON::CSkinInfo::IsInUse(), ADDON::CUISoundsResource::IsInUse(), KODI::GAME::CControllerLayout::Label(), KODI::GAME::CPhysicalFeature::Label(), KODI::GAME::CGameClientInGameSaves::Load(), LoadSettings(), LoadUserSettings(), KODI::GAME::CGameClient::LogAddonProperties(), KODI::GAME::CGameClient::LogError(), KODI::GAME::CGameClient::LogException(), ADDON::Interface_GUIWindow::mark_dirty_region(), ADDON::Interface_GUIDialogExtendedProgress::mark_finished(), ADDON::Interface_GUIDialogProgress::new_dialog(), ADDON::Interface_GUIDialogExtendedProgress::new_dialog(), ADDON::CScraper::NfoUrl(), ADDON::CFontResource::OnPostInstall(), ADDON::CLanguageResource::OnPostInstall(), ADDON::CSkinInfo::OnPostInstall(), KODI::GAME::CGameClientHardware::OnResetButton(), ADDON::Interface_GUIDialogContextMenu::open(), ADDON::Interface_GUIDialogSelect::open(), ADDON::Interface_GUIDialogTextViewer::open(), ADDON::Interface_GUIDialogProgress::open(), ADDON::Interface_GUIDialogSelect::open_multi_select(), ADDON::Interface_Base::open_settings_dialog(), KODI::GAME::CGameClientInput::OpenKeyboard(), KODI::GAME::CGameClientInput::OpenMouse(), KODI::GAME::CGameClient::OpenStandalone(), ADDON::CContextMenuAddon::ParseMenu(), ADDON::Interface_GUIWindow::remove_list_item(), ADDON::Interface_GUIWindow::remove_list_item_from_position(), CScraperParser::ReplaceBuffers(), ADDON::Interface_GUIControlFadeLabel::reset(), ADDON::Interface_GUIControlSettingsSlider::reset(), ADDON::Interface_GUIControlSlider::reset(), ADDON::Interface_GUIControlSpin::reset(), ADDON::Interface_GUIControlTextBox::reset(), ADDON::CScraper::ResolveIDToUrl(), KODI::GAME::CGameClientInGameSaves::Save(), SaveSettings(), ADDON::Interface_GUIControlTextBox::scroll(), ADDON::Interface_GUIListItem::select(), ADDON::Interface_GUIListItem::set_art(), ADDON::Interface_GUIControlTextBox::set_auto_scrolling(), ADDON::Interface_GUIControlAddonRendering::set_callbacks(), ADDON::Interface_GUIWindow::set_callbacks(), ADDON::Interface_GUIDialogProgress::set_can_cancel(), ADDON::Interface_GUIControlImage::set_color_diffuse(), ADDON::Interface_GUIWindow::set_container_content(), ADDON::Interface_GUIWindow::set_container_property(), ADDON::Interface_GUIWindow::set_control_label(), ADDON::Interface_GUIWindow::set_control_selected(), ADDON::Interface_GUIWindow::set_control_visible(), ADDON::Interface_GUIWindow::set_current_list_position(), ADDON::Interface_GUIControlEdit::set_cursor_position(), ADDON::Interface_GUIControlButton::set_enabled(), ADDON::Interface_GUIControlEdit::set_enabled(), ADDON::Interface_GUIControlRadioButton::set_enabled(), ADDON::Interface_GUIControlSettingsSlider::set_enabled(), ADDON::Interface_GUIControlSlider::set_enabled(), ADDON::Interface_GUIControlSpin::set_enabled(), ADDON::Interface_GUIControlImage::set_filename(), ADDON::Interface_GUIControlSettingsSlider::set_float_interval(), ADDON::Interface_GUIControlSlider::set_float_interval(), ADDON::Interface_GUIControlSpin::set_float_interval(), ADDON::Interface_GUIControlSettingsSlider::set_float_range(), ADDON::Interface_GUIControlSlider::set_float_range(), ADDON::Interface_GUIControlSpin::set_float_range(), ADDON::Interface_GUIControlSettingsSlider::set_float_value(), ADDON::Interface_GUIControlSlider::set_float_value(), ADDON::Interface_GUIControlSpin::set_float_value(), ADDON::Interface_GUIWindow::set_focus_id(), ADDON::Interface_GUIDialogProgress::set_heading(), ADDON::Interface_GUIControlEdit::set_input_type(), ADDON::Interface_GUIControlSettingsSlider::set_int_interval(), ADDON::Interface_GUIControlSlider::set_int_interval(), ADDON::Interface_GUIControlSettingsSlider::set_int_range(), ADDON::Interface_GUIControlSlider::set_int_range(), ADDON::Interface_GUIControlSpin::set_int_range(), ADDON::Interface_GUIControlSettingsSlider::set_int_value(), ADDON::Interface_GUIControlSlider::set_int_value(), ADDON::Interface_GUIControlSpin::set_int_value(), ADDON::Interface_GUIControlButton::set_label(), ADDON::Interface_GUIControlEdit::set_label(), ADDON::Interface_GUIControlLabel::set_label(), ADDON::Interface_GUIControlRadioButton::set_label(), ADDON::Interface_GUIListItem::set_label(), ADDON::Interface_GUIControlButton::set_label2(), ADDON::Interface_GUIListItem::set_label2(), ADDON::Interface_GUIDialogProgress::set_line(), ADDON::Interface_GUIListItem::set_path(), ADDON::Interface_GUIControlProgress::set_percentage(), ADDON::Interface_GUIControlSettingsSlider::set_percentage(), ADDON::Interface_GUIControlSlider::set_percentage(), ADDON::Interface_GUIDialogExtendedProgress::set_percentage(), ADDON::Interface_GUIDialogProgress::set_percentage(), ADDON::Interface_GUIDialogExtendedProgress::set_progress(), ADDON::Interface_GUIDialogProgress::set_progress_advance(), ADDON::Interface_GUIDialogProgress::set_progress_max(), ADDON::Interface_GUIListItem::set_property(), ADDON::Interface_GUIWindow::set_property(), ADDON::Interface_GUIWindow::set_property_bool(), ADDON::Interface_GUIWindow::set_property_double(), ADDON::Interface_GUIWindow::set_property_int(), ADDON::Interface_GUIControlFadeLabel::set_scrolling(), ADDON::Interface_GUIControlRadioButton::set_selected(), ADDON::Interface_GUIControlSpin::set_string_value(), ADDON::Interface_GUIControlEdit::set_text(), ADDON::Interface_GUIControlSettingsSlider::set_text(), ADDON::Interface_GUIControlSpin::set_text(), ADDON::Interface_GUIControlTextBox::set_text(), ADDON::Interface_GUIDialogExtendedProgress::set_text(), ADDON::Interface_GUIDialogExtendedProgress::set_title(), ADDON::Interface_GUIControlSpin::set_type(), ADDON::Interface_GUIControlButton::set_visible(), ADDON::Interface_GUIControlEdit::set_visible(), ADDON::Interface_GUIControlFadeLabel::set_visible(), ADDON::Interface_GUIControlImage::set_visible(), ADDON::Interface_GUIControlLabel::set_visible(), ADDON::Interface_GUIControlProgress::set_visible(), ADDON::Interface_GUIControlRadioButton::set_visible(), ADDON::Interface_GUIControlSettingsSlider::set_visible(), ADDON::Interface_GUIControlSlider::set_visible(), ADDON::Interface_GUIControlSpin::set_visible(), ADDON::Interface_GUIControlTextBox::set_visible(), SettingsFromXML(), SettingsToXML(), ADDON::Interface_GUIWindow::show(), ADDON::Interface_GUIDialogNumeric::show_and_get_date(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_directory(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_file(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_file_from_dir(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_file_list(), ADDON::Interface_GUIDialogKeyboard::show_and_get_filter(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_image(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_image_list(), ADDON::Interface_GUIDialogKeyboard::show_and_get_input(), ADDON::Interface_GUIDialogYesNo::show_and_get_input_line_button_text(), ADDON::Interface_GUIDialogYesNo::show_and_get_input_line_text(), ADDON::Interface_GUIDialogYesNo::show_and_get_input_single_text(), ADDON::Interface_GUIDialogKeyboard::show_and_get_input_with_head(), ADDON::Interface_GUIDialogNumeric::show_and_get_ip_address(), ADDON::Interface_GUIDialogKeyboard::show_and_get_new_password(), ADDON::Interface_GUIDialogKeyboard::show_and_get_new_password_with_head(), ADDON::Interface_GUIDialogNumeric::show_and_get_number(), ADDON::Interface_GUIDialogNumeric::show_and_get_seconds(), ADDON::Interface_GUIDialogFileBrowser::show_and_get_source(), ADDON::Interface_GUIDialogNumeric::show_and_get_time(), ADDON::Interface_GUIDialogNumeric::show_and_verify_input(), ADDON::Interface_GUIDialogKeyboard::show_and_verify_new_password(), ADDON::Interface_GUIDialogKeyboard::show_and_verify_new_password_with_head(), ADDON::Interface_GUIDialogNumeric::show_and_verify_password(), ADDON::Interface_GUIDialogKeyboard::show_and_verify_password(), ADDON::Interface_GUIDialogProgress::show_progress_bar(), ADDON::CAddonDll::TransferSettings(), UpdateSetting(), ADDON::Interface_Base::UpdateSettingInActiveDialog(), and ADDON::UpdateSettingValue().
InitSettings()
bool ADDON::CAddon::InitSettings (AddonInstanceId id) private
References URIUtils::AddFileToFolder(), ADDON::ADDON_SETTINGS_ID, data(), FindInstanceSettings(), id, m_addonInfo, ADDON::CAddon::CSettingsData::m_addonSettings, m_settings, and Profile().
Referenced by GetSettings(), LoadSettings(), and LoadUserSettings().
InstallDate()
CDateTime ADDON::CAddon::InstallDate () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
InstanceUseType()
AddonInstanceSupport ADDON::CAddon::InstanceUseType () const override virtual
Return the used instance path type of the add-on type.
Returns
The route used to instance handling, AddonInstanceUse::NONE if not supported.
Implements ADDON::IAddon.
References m_addonInfo.
IsBinary()
bool ADDON::CAddon::IsBinary () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
IsInUse()
bool ADDON::CAddon::IsInUse () const inline override virtual
Implements ADDON::IAddon.
Reimplemented in ADDON::CAddonDll, ADDON::CLanguageResource, ADDON::CScraper, ADDON::CSkinInfo, and ADDON::CUISoundsResource.
LastUpdated()
CDateTime ADDON::CAddon::LastUpdated () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
LastUsed()
CDateTime ADDON::CAddon::LastUsed () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
LibPath()
std::string ADDON::CAddon::LibPath () const override virtual
Implements ADDON::IAddon.
Reimplemented in ADDON::CAddonDll, and KODI::GAME::CGameClient.
References URIUtils::AddFileToFolder(), m_addonInfo, and m_type.
Referenced by ADDON::CWebinterface::GetEntryPoint(), KODI::GAME::CControllerLayout::ImagePath(), ADDON::CAddonDll::LibPath(), ADDON::CScraper::Load(), and KODI::GAME::CController::LoadLayout().
LifecycleState()
AddonLifecycleState ADDON::CAddon::LifecycleState () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
LifecycleStateDescription()
std::string ADDON::CAddon::LifecycleStateDescription () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
LoadSettings()
bool ADDON::CAddon::LoadSettings (bool bForce, bool loadUserSettings, AddonInstanceId id = ADDON_SETTINGS_ID) protected
Load the default settings and override these with any previously configured user settings.
Parameters
[in] bForce force the load of settings even if they are already loaded (reload)
[in] loadUserSettings whether or not to load user settings
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if settings exist, false otherwise
See also
LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, GetSetting, UpdateSetting
References GetSettings(), ID(), id, InitSettings(), CXBMCTinyXML::LoadFile(), LoadUserSettings(), CLog::Log(), LOGERROR, m_settings, and SettingsInitialized().
Referenced by ADDON::CScraper::GetPathSettings(), ADDON::CScraper::GetPathSettingsAsJSON(), GetSetting(), GetSettings(), HasSettings(), HasUserSettings(), ReloadSettings(), ADDON::CScraper::SetPathSettings(), ADDON::CAddonDll::TransferSettings(), and UpdateSetting().
LoadUserSettings()
bool ADDON::CAddon::LoadUserSettings (AddonInstanceId id = ADDON_SETTINGS_ID) protected virtual
Load the user settings.
Parameters
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if user settings exist, false otherwise
See also
LoadSettings, SaveSettings, HasSettings, HasUserSettings, GetSetting, UpdateSetting
References data(), GetSettings(), ID(), id, InitSettings(), CXBMCTinyXML::LoadFile(), CLog::Log(), LOGERROR, ADDON::CAddon::CSettingsData::m_hasUserSettings, m_settings, SettingsFromXML(), and SettingsInitialized().
Referenced by LoadSettings(), and ADDON::CSkinInfo::Start().
MainType()
AddonType ADDON::CAddon::MainType () const override virtual
To get the main type of this addon.
This is the first type defined in addon.xml and can be different to the on Type() defined type.
Returns
The used main type of addon
Implements ADDON::IAddon.
References m_addonInfo.
MeetsVersion()
bool ADDON::CAddon::MeetsVersion (const CAddonVersion & versionMin, const CAddonVersion & version) const override virtual
return whether or not this addon satisfies the given version requirements
Parameters
version the version to meet.
Returns
true if min_version <= version <= current_version, false otherwise.
Implements ADDON::IAddon.
References m_addonInfo.
MinVersion()
CAddonVersion ADDON::CAddon::MinVersion () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Name()
std::string ADDON::CAddon::Name () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by KODI::GAME::CGameClient::CGameClient(), ADDON::CAddonDll::CheckAPIVersion(), ADDON::CAddonDll::Create(), ADDON::Interface_GUIWindow::create(), ADDON::CAddonDll::Destroy(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), ADDON::CScraper::FindMovie(), ADDON::Interface_Base::get_addon_info(), ADDON::Interface_GUIWindow::get_focus_id(), ADDON::Interface_GUIWindow::get_list_item(), ADDON::Interface_General::get_region(), ADDON::Interface_Base::get_setting_bool(), ADDON::Interface_Base::get_setting_float(), ADDON::Interface_Base::get_setting_int(), ADDON::Interface_Base::get_setting_string(), ADDON::CGUIAddonWindow::GetAddonControl(), ADDON::CScraper::GetAlbumDetails(), ADDON::CScraper::GetArtistDetails(), ADDON::CScraper::GetArtwork(), ADDON::CScraper::GetEpisodeList(), ADDON::CScraper::GetVideoDetails(), ADDON::Interface_Base::is_setting_using_default(), ADDON::CAddonDll::LoadDll(), KODI::GAME::CGameClient::LogAddonProperties(), KODI::GAME::CGameClient::NotifyError(), ADDON::CLanguageResource::OnPostInstall(), ADDON::CSkinInfo::OnPostInstall(), ADDON::Interface_General::queue_notification(), ADDON::Interface_GUIWindow::set_focus_id(), and ADDON::CAddonDll::TransferSettings().
OnPostInstall()
void ADDON::CAddon::OnPostInstall (bool update, bool modal) inline override virtual
Implements ADDON::IAddon.
Reimplemented in ADDON::CAddonDll, ADDON::CFontResource, ADDON::CLanguageResource, ADDON::CSkinInfo, and ADDON::CUISoundsResource.
OnPostUnInstall()
void ADDON::CAddon::OnPostUnInstall () inline override virtual
Implements ADDON::IAddon.
Reimplemented in ADDON::CAddonDll.
OnPreInstall()
void ADDON::CAddon::OnPreInstall () inline override virtual
Implements ADDON::IAddon.
Reimplemented in ADDON::CAddonDll, and ADDON::CSkinInfo.
OnPreUnInstall()
void ADDON::CAddon::OnPreUnInstall () inline override virtual
Implements ADDON::IAddon.
Reimplemented in ADDON::CAddonDll, and ADDON::CImageResource.
Origin()
std::string ADDON::CAddon::Origin () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
OriginName()
std::string ADDON::CAddon::OriginName () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
PackageSize()
uint64_t ADDON::CAddon::PackageSize () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Path()
std::string ADDON::CAddon::Path () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by ADDON::CContextMenuAddon::CContextMenuAddon(), ADDON::Interface_GUIWindow::create(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), ADDON::CScraper::FindMovie(), ADDON::Interface_Base::get_addon_info(), ADDON::Interface_Base::get_addon_path(), ADDON::CScraper::GetAlbumDetails(), ADDON::CScraper::GetArtistDetails(), ADDON::CScraper::GetArtwork(), ADDON::CScraper::GetEpisodeList(), ADDON::CFontResource::GetFont(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), ADDON::CResource::GetResourcePath(), ADDON::CSkinInfo::GetSkinPath(), ADDON::CSkinInfo::GetSkinPaths(), ADDON::CScraper::GetVideoDetails(), ADDON::CContextMenuAddon::ParseMenu(), and ADDON::CSkinInfo::Start().
Profile()
std::string ADDON::CAddon::Profile () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by ADDON::Interface_Base::get_addon_info(), ADDON::Interface_Base::get_user_path(), KODI::GAME::CGameClientProperties::GetProfileDirectory(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), KODI::GAME::CGameClientInput::Initialize(), KODI::GAME::CGameClient::Initialize(), and InitSettings().
ReloadSettings()
bool ADDON::CAddon::ReloadSettings (AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Implements ADDON::IAddon.
References LoadSettings().
ResetSettings()
void ADDON::CAddon::ResetSettings (AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Implements ADDON::IAddon.
References m_settings.
Referenced by DeleteInstanceSettings(), and ADDON::CAddonDll::Destroy().
SaveSettings()
bool ADDON::CAddon::SaveSettings (AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Save any user configured settings.
Parameters
[in] instance Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if the operation was successful, false otherwise
See also
LoadSettings, LoadUserSettings, HasSettings, HasUserSettings, GetSetting, UpdateSetting
Implements ADDON::IAddon.
Reimplemented in ADDON::CAddonDll.
References data(), CServiceBroker::GetAddonMgr(), URIUtils::GetDirectory(), CServiceBroker::GetXBPython(), HasSettingsToSave(), ID(), id, m_settings, XBPython::OnSettingsChanged(), ADDON::CAddonMgr::ReloadSettings(), CXBMCTinyXML::SaveFile(), SettingsToXML(), and success.
Referenced by ADDON::CSkinSettingUpdateHandler::OnTimeout(), and ADDON::CAddonDll::SaveSettings().
Screenshots()
std::vector< std::string > ADDON::CAddon::Screenshots () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
SettingsFromXML()
bool ADDON::CAddon::SettingsFromXML (const CXBMCTinyXML & doc, bool loadDefaults, AddonInstanceId id = ADDON_SETTINGS_ID) protected virtual
Parse settings from an XML document.
Parameters
[in] doc XML document to parse for settings
[in] loadDefaults if true, the default attribute is used and settings are reset prior to parsing, else the value attribute is used.
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if settings are loaded, false otherwise
See also
SettingsToXML
Reimplemented in ADDON::CSkinInfo.
References GetSettings(), ID(), id, CLog::Log(), LOGERROR, m_settings, and SettingsInitialized().
Referenced by LoadUserSettings(), and ADDON::CScraper::SetPathSettings().
SettingsInitialized()
bool ADDON::CAddon::SettingsInitialized (AddonInstanceId id = ADDON_SETTINGS_ID) const protected virtual
Whether or not the settings have been initialized.
Parameters
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if settings initialize was successfull
References FindInstanceSettings().
Referenced by LoadSettings(), LoadUserSettings(), SettingsFromXML(), and SettingsToXML().
SettingsLoaded()
bool ADDON::CAddon::SettingsLoaded (AddonInstanceId id = ADDON_SETTINGS_ID) const protected virtual
Whether or not the settings have been loaded.
Parameters
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if settings are loaded correct
Reimplemented in ADDON::CSkinInfo.
References FindInstanceSettings().
Referenced by HasSettingsToSave(), and HasUserSettings().
SettingsToXML()
bool ADDON::CAddon::SettingsToXML (CXBMCTinyXML & doc, AddonInstanceId id = ADDON_SETTINGS_ID) const protected virtual
Write settings into an XML document.
Parameters
[out] doc XML document to receive the settings
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
Returns
true if settings are saved, false otherwise
See also
SettingsFromXML
Reimplemented in ADDON::CSkinInfo.
References ID(), CLog::Log(), LOGERROR, m_settings, and SettingsInitialized().
Referenced by ADDON::CScraper::GetPathSettings(), and SaveSettings().
Summary()
std::string ADDON::CAddon::Summary () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by ADDON::Interface_Base::get_addon_info().
SupportsInstanceSettings()
bool ADDON::CAddon::SupportsInstanceSettings () const override virtual
Check whether the add-on supports individual settings per add-on instance.
This function is supported if add-on type has defined AddonInstanceUse::BY_SETTINGS
Returns
true if the add-on supports individual settings per add-on instance, false otherwise
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by CanHaveAddonOrInstanceSettings().
SupportsMultipleInstances()
bool ADDON::CAddon::SupportsMultipleInstances () const override virtual
Check add-on for support from independent work instances.
Returns
true if the add-on supports individual add-on instances, false otherwise
Implements ADDON::IAddon.
References m_addonInfo.
Type() [1/2]
AddonType ADDON::CAddon::Type () const inline override virtual
To get the on this CAddon class processed addon type.
Returns
For this class used addon type
Implements ADDON::IAddon.
References m_type.
Referenced by ADDON::CContextMenuAddon::CContextMenuAddon(), KODI::GAME::CGameClient::CGameClient(), ADDON::CLanguageResource::CLanguageResource(), ADDON::CPluginSource::CPluginSource(), ADDON::CAddonDll::Create(), ADDON::Interface_GUIWindow::create(), ADDON::CRepository::CRepository(), ADDON::CScraper::CScraper(), ADDON::CSkinInfo::CSkinInfo(), ADDON::CWebinterface::CWebinterface(), ADDON::Interface_Base::get_addon_info(), KODI::GAME::CGameClient::GetRunningInstance(), ADDON::CPluginSource::HasType(), ADDON::CAddonDll::LoadDll(), ADDON::CPluginSource::SetProvides(), and ADDON::CScraper::Supports().
Type() [2/2]
const CAddonType * ADDON::CAddon::Type (AddonType type) const
The get for given addon type information and extension data.
Parameters
[in] type The wanted type data
Returns
addon type class with CAddonExtensions as information
Note
This function return never a "nullptr", in case the wanted type is not supported, becomes a dummy of CAddonType given.
Example:
// To get e.g. <extension ... name="blablabla" /> from addon.xml
std::string name = Type(ADDON_...)->GetValue("@name").asString();
References m_addonInfo, and ADDON::CAddonType::Type().
UpdateSetting()
void ADDON::CAddon::UpdateSetting (const std::string & key, const std::string & value, AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Update a user-configured setting with a new value.
Parameters
[in] key the id of the setting to update
[in] value the value that the setting should take
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, GetSetting
Implements ADDON::IAddon.
References ID(), id, LoadSettings(), CLog::Log(), LOGERROR, m_settings, and value.
UpdateSettingBool()
bool ADDON::CAddon::UpdateSettingBool (const std::string & key, bool value, AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Update a user-configured setting with a new boolean value.
Parameters
[in] key the id of the setting to update
[in] value the value that the setting should take
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, GetSetting
Implements ADDON::IAddon.
References value.
Referenced by ADDON::Interface_Base::set_setting_bool().
UpdateSettingInt()
bool ADDON::CAddon::UpdateSettingInt (const std::string & key, int value, AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Update a user-configured setting with a new integer value.
Parameters
[in] key the id of the setting to update
[in] value the value that the setting should take
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, GetSetting
Implements ADDON::IAddon.
References value.
Referenced by ADDON::Interface_Base::set_setting_int().
UpdateSettingNumber()
bool ADDON::CAddon::UpdateSettingNumber (const std::string & key, double value, AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Update a user-configured setting with a new number value.
Parameters
[in] key the id of the setting to update
[in] value the value that the setting should take
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, GetSetting
Implements ADDON::IAddon.
References value.
Referenced by ADDON::Interface_Base::set_setting_float().
UpdateSettingString()
bool ADDON::CAddon::UpdateSettingString (const std::string & key, const std::string & value, AddonInstanceId id = ADDON_SETTINGS_ID) override virtual
Update a user-configured setting with a new string value.
Parameters
[in] key the id of the setting to update
[in] value the value that the setting should take
[in] id Instance identifier to use, use ADDON_SETTINGS_ID to denote global add-on settings from settings.xml.
See also
LoadSettings, LoadUserSettings, SaveSettings, HasSettings, HasUserSettings, GetSetting
Implements ADDON::IAddon.
References value.
Referenced by ADDON::Interface_Base::set_setting_string().
Version()
CAddonVersion ADDON::CAddon::Version () const override virtual
Implements ADDON::IAddon.
References m_addonInfo.
Referenced by KODI::RETRO::CReversiblePlayback::CommitSavestate(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), ADDON::CScraper::FindMovie(), ADDON::Interface_Base::get_addon_info(), ADDON::CScraper::GetAlbumDetails(), ADDON::CScraper::GetArtistDetails(), ADDON::CScraper::GetArtwork(), ADDON::CScraper::GetEpisodeList(), ADDON::CScraper::GetVideoDetails(), and KODI::GAME::CGameClient::LogAddonProperties().
Member Data Documentation
m_addonInfo
const AddonInfoPtr ADDON::CAddon::m_addonInfo protected
Referenced by Art(), Author(), ChangeLog(), Description(), Disclaimer(), ExtraInfo(), FanArt(), GetDependencies(), GetDependencyVersion(), GetKnownInstanceIds(), HasMainType(), HasType(), Icon(), ID(), InitSettings(), InstallDate(), InstanceUseType(), IsBinary(), LastUpdated(), LastUsed(), LibPath(), LifecycleState(), LifecycleStateDescription(), MainType(), MeetsVersion(), MinVersion(), Name(), Origin(), OriginName(), PackageSize(), Path(), Profile(), Screenshots(), Summary(), SupportsInstanceSettings(), SupportsMultipleInstances(), Type(), and Version().
m_settings
std::unordered_map<AddonInstanceId, CSettingsData> ADDON::CAddon::m_settings mutable private
Referenced by DeleteInstanceSettings(), FindInstanceSettings(), GetSetting(), GetSettings(), HasSettings(), HasUserSettings(), InitSettings(), LoadSettings(), LoadUserSettings(), ResetSettings(), SaveSettings(), SettingsFromXML(), SettingsToXML(), and UpdateSetting().
m_type
const AddonType ADDON::CAddon::m_type private
Referenced by LibPath(), and Type().
The documentation for this class was generated from the following files:
addons/Addon.h
addons/Addon.cpp