Kodi Documentation: KODI::RETRO::CCheevos Class Reference
KODI::RETRO::CCheevos Class Reference
#include <Cheevos.h>
Public Member Functions
CCheevos (GAME::CGameClient *gameClient, const std::string &userName, const std::string &loginToken)
void ResetRuntime ()
void EnableRichPresence ()
std::string GetRichPresenceEvaluation ()
Private Member Functions
bool LoadData ()
RConsoleID ConsoleID ()
Private Attributes
GAME::CGameClient *const m_gameClient
std::string m_userName
std::string m_loginToken
std::string m_romHash
std::string m_richPresenceScript
uint32_t m_gameID {}
RConsoleID m_consoleID = RConsoleID::RC_INVALID_ID
bool m_richPresenceLoaded {}
const std::map< std::string, RConsoleID > m_extensionToConsole
Constructor & Destructor Documentation
CCheevos()
CCheevos::CCheevos (GAME::CGameClient * gameClient, const std::string & userName, const std::string & loginToken)
Member Function Documentation
ConsoleID()
RConsoleID CCheevos::ConsoleID () private
References URIUtils::GetExtension(), KODI::GAME::CGameClient::GetGamePath(), m_extensionToConsole, m_gameClient, and KODI::RETRO::RC_INVALID_ID.
Referenced by LoadData().
EnableRichPresence()
void CCheevos::EnableRichPresence ()
References KODI::GAME::CGameClient::Cheevos(), LoadData(), CLog::Log(), LOGERROR, m_gameClient, m_richPresenceLoaded, m_richPresenceScript, and KODI::GAME::CGameClientCheevos::RCEnableRichPresence().
GetRichPresenceEvaluation()
std::string CCheevos::GetRichPresenceEvaluation ()
References KODI::GAME::CGameClient::Cheevos(), CLog::Log(), LOGERROR, m_consoleID, m_gameClient, m_gameID, m_loginToken, m_richPresenceLoaded, m_userName, XFILE::CCurlFile::Post(), KODI::GAME::CGameClientCheevos::RCGetRichPresenceEvaluation(), and KODI::GAME::CGameClientCheevos::RCPostRichPresenceUrl().
Referenced by KODI::RETRO::CReversiblePlayback::CommitSavestate().
LoadData()
bool CCheevos::LoadData () private
References KODI::GAME::CGameClient::Cheevos(), XFILE::CFile::Close(), ConsoleID(), XFILE::CFile::CURLCreate(), XFILE::CFile::CURLOpen(), data(), CServiceBroker::GetAppMessenger(), KODI::GAME::CGameClient::GetGamePath(), XFILE::CFile::LoadFile(), m_consoleID, m_gameClient, m_gameID, m_loginToken, m_richPresenceLoaded, m_richPresenceScript, m_romHash, m_userName, CJSONVariantParser::Parse(), KODI::RETRO::RC_INVALID_ID, KODI::GAME::CGameClientCheevos::RCGenerateHashFromFile(), KODI::GAME::CGameClientCheevos::RCGetGameIDUrl(), KODI::GAME::CGameClientCheevos::RCGetPatchFileUrl(), XFILE::CFile::ReadString(), KODI::GAME::CGameInfoTag::SetTitle(), SUCCESS, TMSG_UPDATE_PLAYER_ITEM, and CVariant::VariantTypeObject.
Referenced by EnableRichPresence().
ResetRuntime()
void CCheevos::ResetRuntime ()
References KODI::GAME::CGameClient::Cheevos(), m_gameClient, and KODI::GAME::CGameClientCheevos::RCResetRuntime().
Referenced by KODI::RETRO::CReversiblePlayback::LoadSavestate().
Member Data Documentation
m_consoleID
RConsoleID KODI::RETRO::CCheevos::m_consoleID = RConsoleID::RC_INVALID_ID private
Referenced by GetRichPresenceEvaluation(), and LoadData().
m_extensionToConsole
const std::map<std::string, RConsoleID> KODI::RETRO::CCheevos::m_extensionToConsole private
Referenced by ConsoleID().
m_gameClient
GAME::CGameClient* const KODI::RETRO::CCheevos::m_gameClient private
Referenced by ConsoleID(), EnableRichPresence(), GetRichPresenceEvaluation(), LoadData(), and ResetRuntime().
m_gameID
uint32_t KODI::RETRO::CCheevos::m_gameID {} private
Referenced by GetRichPresenceEvaluation(), and LoadData().
m_loginToken
std::string KODI::RETRO::CCheevos::m_loginToken private
Referenced by GetRichPresenceEvaluation(), and LoadData().
m_richPresenceLoaded
bool KODI::RETRO::CCheevos::m_richPresenceLoaded {} private
Referenced by EnableRichPresence(), GetRichPresenceEvaluation(), and LoadData().
m_richPresenceScript
std::string KODI::RETRO::CCheevos::m_richPresenceScript private
Referenced by EnableRichPresence(), and LoadData().
m_romHash
std::string KODI::RETRO::CCheevos::m_romHash private
Referenced by LoadData().
m_userName
std::string KODI::RETRO::CCheevos::m_userName private
Referenced by GetRichPresenceEvaluation(), and LoadData().
The documentation for this class was generated from the following files:
Cheevos.h
Cheevos.cpp