Kodi Documentation: CONTEXTMENU::CAddRemoveFavourite Struct Reference
CONTEXTMENU::CAddRemoveFavourite Struct Reference
#include <ContextMenus.h>
Public Member Functions
CAddRemoveFavourite ()=default
std::string GetLabel (const CFileItem &item) const override
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool IsGroup () const
virtual bool HasParent () const
Constructor & Destructor Documentation
CAddRemoveFavourite()
CONTEXTMENU::CAddRemoveFavourite::CAddRemoveFavourite () default
Member Function Documentation
Execute()
bool CONTEXTMENU::CAddRemoveFavourite::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References CFavouritesService::AddOrRemove(), and CServiceBroker::GetFavouritesService().
GetLabel()
std::string CONTEXTMENU::CAddRemoveFavourite::GetLabel (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References g_localizeStrings, CLocalizeStrings::Get(), and CServiceBroker::GetFavouritesService().
IsVisible()
bool CONTEXTMENU::CAddRemoveFavourite::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References CVariant::asBoolean(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CFileItem::IsParentFolder(), CFileItem::IsPath(), and URIUtils::IsProtocol().
The documentation for this struct was generated from the following files:
ContextMenus.h
ContextMenus.cpp