Kodi Documentation: CApplicationPowerHandling Class Reference
CApplicationPowerHandling Class Reference
Class handling application support for screensavers, dpms and shutdown timers.
#include <ApplicationPowerHandling.h>
Public Member Functions
bool IsInScreenSaver () const
bool IsScreenSaverInhibited () const
void ResetScreenSaver ()
void SetScreenSaverLockFailed ()
void SetScreenSaverUnlocked ()
void StopScreenSaverTimer ()
const std::string & ScreensaverIdInUse () const
bool GetRenderGUI () const
void SetRenderGUI (bool renderGUI)
int GlobalIdleTime ()
void ResetSystemIdleTimer ()
bool IsIdleShutdownInhibited () const
void ResetShutdownTimers ()
void StopShutdownTimer ()
void ResetNavigationTimer ()
bool IsDPMSActive () const
bool ToggleDPMS (bool manual)
bool WakeUpScreenSaverAndDPMS (bool bPowerOffKeyPressed=false)
bool OnSettingChanged (const CSetting &setting)
bool OnSettingAction (const CSetting &setting)
Public Member Functions inherited from IApplicationComponent
virtual ~IApplicationComponent ()=default
Protected Member Functions
void ActivateScreenSaver (bool forceType=false)
void CheckOSScreenSaverInhibitionSetting ()
void CheckScreenSaverAndDPMS ()
void InhibitScreenSaver (bool inhibit)
void ResetScreenSaverTimer ()
bool WakeUpScreenSaver (bool bPowerOffKeyPressed=false)
void InhibitIdleShutdown (bool inhibit)
void HandleShutdownMessage ()
Helper method to determine how to handle TMSG_SHUTDOWN.
void CheckShutdown ()
float NavigationIdleTime ()
Protected Attributes
bool m_renderGUI {false}
bool m_bInhibitScreenSaver = false
bool m_bResetScreenSaver = false
ADDON::AddonPtr m_pythonScreenSaver
bool m_screensaverActive = false
int m_iScreenSaveLock = 0
std::string m_screensaverIdInUse
bool m_dpmsIsActive = false
bool m_dpmsIsManual = false
bool m_bInhibitIdleShutdown = false
CStopWatch m_navigationTimer
CStopWatch m_shutdownTimer
CStopWatch m_idleTimer
CStopWatch m_screenSaverTimer
KODI::WINDOWING::COSScreenSaverInhibitor m_globalScreensaverInhibitor
KODI::WINDOWING::COSScreenSaverInhibitor m_screensaverInhibitor
Friends
class CApplication
Detailed Description
Class handling application support for screensavers, dpms and shutdown timers.
Member Function Documentation
ActivateScreenSaver()
void CApplicationPowerHandling::ActivateScreenSaver (bool forceType = false) protected
References CGUIWindowManager::ActivateWindow(), ADDON::CHOICE_YES, CScriptInvocationManager::ExecuteAsync(), g_alarmClock, CServiceBroker::GetAddonMgr(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CScriptInvocationManager::GetInstance(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), ANNOUNCEMENT::GUI, CLog::Log(), LOGDEBUG, m_iScreenSaveLock, m_pythonScreenSaver, m_screensaverActive, m_screensaverIdInUse, ADDON::SCREENSAVER, SCRIPT_ALARM, CSettings::SETTING_SCREENSAVER_MODE, CSettings::SETTING_SCREENSAVER_USEDIMONPAUSE, CAlarmClock::Stop(), WINDOW_LOGIN_SCREEN, and WINDOW_SCREENSAVER.
Referenced by CheckScreenSaverAndDPMS(), and OnSettingAction().
CheckOSScreenSaverInhibitionSetting()
void CApplicationPowerHandling::CheckOSScreenSaverInhibitionSetting () protected
References KODI::WINDOWING::COSScreenSaverManager::CreateInhibitor(), CWinSystemBase::GetOSScreenSaver(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), m_dpmsIsActive, m_globalScreensaverInhibitor, KODI::WINDOWING::COSScreenSaverInhibitor::Release(), and CSettings::SETTING_SCREENSAVER_MODE.
Referenced by OnSettingChanged(), and ToggleDPMS().
CheckScreenSaverAndDPMS()
void CApplicationPowerHandling::CheckScreenSaverAndDPMS () protected
References ActivateScreenSaver(), KODI::WINDOWING::COSScreenSaverManager::CreateInhibitor(), CServiceBroker::GetAppComponents(), CStopWatch::GetElapsedSeconds(), CServiceBroker::GetGUI(), CWinSystemBase::GetOSScreenSaver(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), CStopWatch::IsRunning(), m_bInhibitScreenSaver, m_bResetScreenSaver, m_dpmsIsActive, m_screensaverActive, m_screensaverInhibitor, m_screenSaverTimer, KODI::WINDOWING::COSScreenSaverInhibitor::Release(), ResetScreenSaverTimer(), CSettings::SETTING_POWERMANAGEMENT_DISPLAYSOFF, CSettings::SETTING_SCREENSAVER_DISABLEFORAUDIO, CSettings::SETTING_SCREENSAVER_MODE, CSettings::SETTING_SCREENSAVER_TIME, ToggleDPMS(), WakeUpScreenSaver(), WakeUpScreenSaverAndDPMS(), and WINDOW_SCREENSAVER.
CheckShutdown()
void CApplicationPowerHandling::CheckShutdown () protected
References PVR::CPVRManager::Get(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CStopWatch::GetElapsedSeconds(), CServiceBroker::GetGUI(), CMusicLibraryQueue::GetInstance(), CVideoLibraryQueue::GetInstance(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CMusicLibraryQueue::IsRunning(), CStopWatch::IsRunning(), CVideoLibraryQueue::IsRunning(), LOGDEBUG, m_bInhibitIdleShutdown, m_shutdownTimer, CSettings::SETTING_POWERMANAGEMENT_SHUTDOWNSTATE, CSettings::SETTING_POWERMANAGEMENT_SHUTDOWNTIME, CStopWatch::StartZero(), CStopWatch::Stop(), TMSG_SHUTDOWN, and WINDOW_DIALOG_PROGRESS.
GetRenderGUI()
bool CApplicationPowerHandling::GetRenderGUI () const inline
References m_renderGUI.
Referenced by CWinEventsWin32::WndProc().
GlobalIdleTime()
int CApplicationPowerHandling::GlobalIdleTime ()
References CStopWatch::GetElapsedSeconds(), CStopWatch::IsRunning(), m_idleTimer, and CStopWatch::StartZero().
Referenced by ADDON::Interface_General::get_global_idle_time(), and XBMCAddon::xbmc::getGlobalIdleTime().
HandleShutdownMessage()
void CApplicationPowerHandling::HandleShutdownMessage () protected
Helper method to determine how to handle TMSG_SHUTDOWN.
References CServiceBroker::GetAppMessenger(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, POWERSTATE_HIBERNATE, POWERSTATE_MINIMIZE, POWERSTATE_QUIT, POWERSTATE_SHUTDOWN, POWERSTATE_SUSPEND, CSettings::SETTING_POWERMANAGEMENT_SHUTDOWNSTATE, TMSG_HIBERNATE, TMSG_MINIMIZE, TMSG_POWERDOWN, TMSG_QUIT, and TMSG_SUSPEND.
InhibitIdleShutdown()
void CApplicationPowerHandling::InhibitIdleShutdown (bool inhibit) protected
References m_bInhibitIdleShutdown.
InhibitScreenSaver()
void CApplicationPowerHandling::InhibitScreenSaver (bool inhibit) protected
References m_bInhibitScreenSaver.
IsDPMSActive()
bool CApplicationPowerHandling::IsDPMSActive () const inline
References m_dpmsIsActive.
IsIdleShutdownInhibited()
bool CApplicationPowerHandling::IsIdleShutdownInhibited () const
References m_bInhibitIdleShutdown.
IsInScreenSaver()
bool CApplicationPowerHandling::IsInScreenSaver () const inline
References m_screensaverActive.
Referenced by KODI::JOYSTICK::CJoystickMonitor::AcceptsInput(), and KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool().
IsScreenSaverInhibited()
bool CApplicationPowerHandling::IsScreenSaverInhibited () const
References m_bInhibitScreenSaver.
NavigationIdleTime()
float CApplicationPowerHandling::NavigationIdleTime () protected
References CStopWatch::GetElapsedSeconds(), CStopWatch::IsRunning(), m_navigationTimer, and CStopWatch::StartZero().
OnSettingAction()
bool CApplicationPowerHandling::OnSettingAction (const CSetting & setting)
References ActivateScreenSaver(), ADDON::CHOICE_YES, CServiceBroker::GetAddonMgr(), ISetting::GetId(), CServiceBroker::GetSettingsComponent(), ADDON::SCREENSAVER, CSettings::SETTING_SCREENSAVER_MODE, CSettings::SETTING_SCREENSAVER_PREVIEW, CSettings::SETTING_SCREENSAVER_SETTINGS, and CGUIDialogAddonSettings::ShowForAddon().
OnSettingChanged()
bool CApplicationPowerHandling::OnSettingChanged (const CSetting & setting)
References CheckOSScreenSaverInhibitionSetting(), ISetting::GetId(), and CSettings::SETTING_SCREENSAVER_MODE.
ResetNavigationTimer()
void CApplicationPowerHandling::ResetNavigationTimer ()
References m_navigationTimer, and CStopWatch::StartZero().
ResetScreenSaver()
void CApplicationPowerHandling::ResetScreenSaver ()
References m_dpmsIsActive, m_iScreenSaveLock, m_screensaverActive, m_shutdownTimer, ResetScreenSaverTimer(), and CStopWatch::StartZero().
Referenced by CInertialScrollingHandler::CheckForInertialScrolling(), XFILE::CFile::Copy(), CAppInboundProtocol::HandleEvents(), JSONRPC::CInputOperations::handleScreenSaver(), KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), PlayerControl(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CExternalPlayer::Process(), CGUIWindowSlideShow::Process(), CGUIVideoControl::Render(), JSONRPC::CPlayerOperations::StartSlideshow(), and CWinEventsWin32::WndProc().
ResetScreenSaverTimer()
void CApplicationPowerHandling::ResetScreenSaverTimer () protected
References m_screenSaverTimer, and CStopWatch::StartZero().
Referenced by CheckScreenSaverAndDPMS(), ResetScreenSaver(), WakeUpScreenSaver(), and WakeUpScreenSaverAndDPMS().
ResetShutdownTimers()
void CApplicationPowerHandling::ResetShutdownTimers ()
References g_alarmClock, CAlarmClock::HasAlarm(), m_shutdownTimer, CStopWatch::StartZero(), and CAlarmClock::Stop().
Referenced by CXBMCApp::onResume(), and CPowerManager::OnWake().
ResetSystemIdleTimer()
void CApplicationPowerHandling::ResetSystemIdleTimer ()
References m_idleTimer, and CStopWatch::StartZero().
Referenced by CInputManager::HandleKey(), TVOSLibInputHandler::init, CInputManager::ProcessEventServer(), CInputManager::ProcessMouse(), KODI::JOYSTICK::CJoystickMonitor::ResetTimers(), and JSONRPC::CInputOperations::SendAction().
ScreensaverIdInUse()
const std::string & CApplicationPowerHandling::ScreensaverIdInUse () const inline
References m_screensaverIdInUse.
Referenced by CGUIWindowScreensaverDim::UpdateVisibility().
SetRenderGUI()
void CApplicationPowerHandling::SetRenderGUI (bool renderGUI)
References m_renderGUI.
Referenced by CAppInboundProtocol::SetRenderGUI(), CXBMCApp::surfaceCreated(), CXBMCApp::surfaceDestroyed(), ToggleDPMS(), and CWinEventsWin32::WndProc().
SetScreenSaverLockFailed()
void CApplicationPowerHandling::SetScreenSaverLockFailed () inline
References m_iScreenSaveLock.
Referenced by CGUIWindowScreensaver::OnMessage().
SetScreenSaverUnlocked()
void CApplicationPowerHandling::SetScreenSaverUnlocked () inline
References m_iScreenSaveLock.
StopScreenSaverTimer()
void CApplicationPowerHandling::StopScreenSaverTimer ()
References m_screenSaverTimer, and CStopWatch::Stop().
StopShutdownTimer()
void CApplicationPowerHandling::StopShutdownTimer ()
References m_shutdownTimer, and CStopWatch::Stop().
Referenced by CPowerManager::OnSleep().
ToggleDPMS()
bool CApplicationPowerHandling::ToggleDPMS (bool manual)
References CheckOSScreenSaverInhibitionSetting(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetWinSystem(), ANNOUNCEMENT::GUI, m_dpmsIsActive, m_dpmsIsManual, and SetRenderGUI().
Referenced by CheckScreenSaverAndDPMS(), ToggleDPMS(), and WakeUpScreenSaverAndDPMS().
WakeUpScreenSaver()
bool CApplicationPowerHandling::WakeUpScreenSaver (bool bPowerOffKeyPressed = false) protected
References ACTION_STOP, g_alarmClock, CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), GUI_MSG_CHECK_LOCK, LOCK_MODE_EVERYONE, m_iScreenSaveLock, m_pythonScreenSaver, m_screensaverActive, m_screensaverIdInUse, CGUIWindow::OnMessage(), CGUIWindowManager::PreviousWindow(), ResetScreenSaverTimer(), SCRIPT_ALARM, SCRIPT_TIMEOUT, CSettings::SETTING_MASTERLOCK_STARTUPLOCK, CAlarmClock::Start(), TMSG_GUI_ACTION, WINDOW_SCREENSAVER, and WINDOW_SLIDESHOW.
Referenced by CheckScreenSaverAndDPMS(), and WakeUpScreenSaverAndDPMS().
WakeUpScreenSaverAndDPMS()
bool CApplicationPowerHandling::WakeUpScreenSaverAndDPMS (bool bPowerOffKeyPressed = false)
Todo:
if screensaver lock is specified but screensaver is not active (DPMS came first), activate screensaver now.
References data(), CServiceBroker::GetAnnouncementManager(), ANNOUNCEMENT::GUI, m_dpmsIsActive, m_dpmsIsManual, m_screensaverActive, ResetScreenSaverTimer(), ToggleDPMS(), CVariant::VariantTypeObject, and WakeUpScreenSaver().
Referenced by anonymous_namespace{GUIBuiltins.cpp}::ActivateAndFocus(), anonymous_namespace{GUIBuiltins.cpp}::ActivateWindow(), CheckScreenSaverAndDPMS(), CAutorunMediaJob::DoWork(), CProfileManager::LogOff(), CXBMCApp::onGainFocus(), CXBMCApp::onReceive(), and CXBMCApp::OnWakeup().
Friends And Related Symbol Documentation
CApplication
friend class CApplication friend
Member Data Documentation
m_bInhibitIdleShutdown
bool CApplicationPowerHandling::m_bInhibitIdleShutdown = false protected
Referenced by CheckShutdown(), InhibitIdleShutdown(), and IsIdleShutdownInhibited().
m_bInhibitScreenSaver
bool CApplicationPowerHandling::m_bInhibitScreenSaver = false protected
Referenced by CheckScreenSaverAndDPMS(), InhibitScreenSaver(), and IsScreenSaverInhibited().
m_bResetScreenSaver
bool CApplicationPowerHandling::m_bResetScreenSaver = false protected
Referenced by CheckScreenSaverAndDPMS().
m_dpmsIsActive
bool CApplicationPowerHandling::m_dpmsIsActive = false protected
Referenced by CheckOSScreenSaverInhibitionSetting(), CheckScreenSaverAndDPMS(), IsDPMSActive(), ResetScreenSaver(), ToggleDPMS(), and WakeUpScreenSaverAndDPMS().
m_dpmsIsManual
bool CApplicationPowerHandling::m_dpmsIsManual = false protected
Referenced by ToggleDPMS(), and WakeUpScreenSaverAndDPMS().
m_globalScreensaverInhibitor
KODI::WINDOWING::COSScreenSaverInhibitor CApplicationPowerHandling::m_globalScreensaverInhibitor protected
Referenced by CheckOSScreenSaverInhibitionSetting().
m_idleTimer
CStopWatch CApplicationPowerHandling::m_idleTimer protected
Referenced by GlobalIdleTime(), and ResetSystemIdleTimer().
m_iScreenSaveLock
int CApplicationPowerHandling::m_iScreenSaveLock = 0 protected
Referenced by ActivateScreenSaver(), ResetScreenSaver(), SetScreenSaverLockFailed(), SetScreenSaverUnlocked(), and WakeUpScreenSaver().
m_navigationTimer
CStopWatch CApplicationPowerHandling::m_navigationTimer protected
Referenced by NavigationIdleTime(), and ResetNavigationTimer().
m_pythonScreenSaver
ADDON::AddonPtr CApplicationPowerHandling::m_pythonScreenSaver protected
Referenced by ActivateScreenSaver(), and WakeUpScreenSaver().
m_renderGUI
bool CApplicationPowerHandling::m_renderGUI {false} protected
Referenced by GetRenderGUI(), and SetRenderGUI().
m_screensaverActive
bool CApplicationPowerHandling::m_screensaverActive = false protected
Referenced by ActivateScreenSaver(), CheckScreenSaverAndDPMS(), IsInScreenSaver(), ResetScreenSaver(), WakeUpScreenSaver(), and WakeUpScreenSaverAndDPMS().
m_screensaverIdInUse
std::string CApplicationPowerHandling::m_screensaverIdInUse protected
Referenced by ActivateScreenSaver(), ScreensaverIdInUse(), and WakeUpScreenSaver().
m_screensaverInhibitor
KODI::WINDOWING::COSScreenSaverInhibitor CApplicationPowerHandling::m_screensaverInhibitor protected
Referenced by CheckScreenSaverAndDPMS().
m_screenSaverTimer
CStopWatch CApplicationPowerHandling::m_screenSaverTimer protected
Referenced by CheckScreenSaverAndDPMS(), ResetScreenSaverTimer(), and StopScreenSaverTimer().
m_shutdownTimer
CStopWatch CApplicationPowerHandling::m_shutdownTimer protected
Referenced by CheckShutdown(), ResetScreenSaver(), ResetShutdownTimers(), and StopShutdownTimer().
The documentation for this class was generated from the following files:
ApplicationPowerHandling.h
ApplicationPowerHandling.cpp