Kodi Documentation: CZeroconfDarwin Class Reference
CZeroconfDarwin Class Reference
#include <ZeroconfDarwin.h>
Public Member Functions
CZeroconfDarwin ()
~CZeroconfDarwin () override
Public Member Functions inherited from CZeroconf
bool PublishService (const std::string &fcr_identifier, const std::string &fcr_type, const std::string &fcr_name, unsigned int f_port, std::vector< std::pair< std::string, std::string > > txt)
bool ForceReAnnounceService (const std::string &fcr_identifier)
bool RemoveService (const std::string &fcr_identifier)
bool HasService (const std::string &fcr_identifier) const
returns true if fcr_identifier exists
bool Start ()
void Stop ()
virtual void ProcessResults ()
bool IsStarted ()
Protected Member Functions
bool doPublishService (const std::string &fcr_identifier, const std::string &fcr_type, const std::string &fcr_name, unsigned int f_port, const std::vector< std::pair< std::string, std::string > > &txt) override
bool doForceReAnnounceService (const std::string &fcr_identifier) override
bool doRemoveService (const std::string &fcr_ident) override
void doStop () override
Protected Member Functions inherited from CZeroconf
virtual bool IsZCdaemonRunning ()
CZeroconf ()
CZeroconf (const CZeroconf &)
virtual ~CZeroconf ()
Private Types
typedef std::map< std::string, CFNetServiceRef > tServiceMap
Private Member Functions
void cancelRegistration (CFNetServiceRef theService)
Static Private Member Functions
static void registerCallback (CFNetServiceRef theService, CFStreamError *error, void *info)
Private Attributes
CFRunLoopRef m_runloop = nullptr
CCriticalSection m_data_guard
tServiceMap m_services
Additional Inherited Members
Static Public Member Functions inherited from CZeroconf
static CZeroconf * GetInstance ()
static void ReleaseInstance ()
static bool IsInstantiated ()
Member Typedef Documentation
tServiceMap
typedef std::map<std::string, CFNetServiceRef> CZeroconfDarwin::tServiceMap private
Constructor & Destructor Documentation
CZeroconfDarwin()
CZeroconfDarwin::CZeroconfDarwin ()
References m_runloop.
~CZeroconfDarwin()
CZeroconfDarwin::~CZeroconfDarwin () override
References doStop().
Member Function Documentation
cancelRegistration()
void CZeroconfDarwin::cancelRegistration (CFNetServiceRef theService) private
References m_runloop.
Referenced by doRemoveService(), doStop(), and registerCallback().
doForceReAnnounceService()
bool CZeroconfDarwin::doForceReAnnounceService (const std::string & fcr_identifier) override protected virtual
Implements CZeroconf.
References m_data_guard, and m_services.
doPublishService()
bool CZeroconfDarwin::doPublishService (const std::string & fcr_identifier, const std::string & fcr_type, const std::string & fcr_name, unsigned int f_port, const std::vector< std::pair< std::string, std::string > > & txt) override protected virtual
Implements CZeroconf.
References Boolean, CFHashNullVersion(), int64_t(), CLog::Log(), LOGDEBUG, LOGERROR, m_data_guard, m_runloop, m_services, name, registerCallback(), and value.
doRemoveService()
bool CZeroconfDarwin::doRemoveService (const std::string & fcr_ident) override protected virtual
Implements CZeroconf.
References cancelRegistration(), m_data_guard, and m_services.
doStop()
void CZeroconfDarwin::doStop () override protected virtual
Implements CZeroconf.
References cancelRegistration(), m_data_guard, and m_services.
Referenced by ~CZeroconfDarwin().
registerCallback()
void CZeroconfDarwin::registerCallback (CFNetServiceRef theService, CFStreamError * error, void * info) static private
References cancelRegistration(), int64_t(), CLog::Log(), LOGERROR, m_data_guard, and m_services.
Referenced by doPublishService().
Member Data Documentation
m_data_guard
CCriticalSection CZeroconfDarwin::m_data_guard private
Referenced by doForceReAnnounceService(), doPublishService(), doRemoveService(), doStop(), and registerCallback().
m_runloop
CFRunLoopRef CZeroconfDarwin::m_runloop = nullptr private
Referenced by cancelRegistration(), CZeroconfDarwin(), and doPublishService().
m_services
tServiceMap CZeroconfDarwin::m_services private
Referenced by doForceReAnnounceService(), doPublishService(), doRemoveService(), doStop(), and registerCallback().
The documentation for this class was generated from the following files:
ZeroconfDarwin.h
ZeroconfDarwin.cpp