Kodi Documentation: CDatabase::DatasetLayout Class Reference
CDatabase::DatasetLayout Class Reference
#include <Database.h>
Public Member Functions
DatasetLayout (size_t totalfields)
void SetField (int fieldNo, const std::string &strField, bool bOutput=false)
void AdjustRecordNumbers (int offset)
bool GetFetch (int fieldno)
void SetFetch (int fieldno, bool bFetch=true)
bool GetOutput (int fieldno)
int GetRecNo (int fieldno)
const std::string GetFields ()
bool HasFilterFields ()
Private Attributes
std::vector< DatasetFieldInfo > m_fields
Constructor & Destructor Documentation
DatasetLayout()
CDatabase::DatasetLayout::DatasetLayout (size_t totalfields)
Member Function Documentation
AdjustRecordNumbers()
void CDatabase::DatasetLayout::AdjustRecordNumbers (int offset)
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), and CMusicDatabase::GetSongsByWhereJSON().
GetFetch()
bool CDatabase::DatasetLayout::GetFetch (int fieldno)
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), and CMusicDatabase::GetSongsByWhereJSON().
GetFields()
const std::string CDatabase::DatasetLayout::GetFields ()
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), and CMusicDatabase::GetSongsByWhereJSON().
GetOutput()
bool CDatabase::DatasetLayout::GetOutput (int fieldno)
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), and CMusicDatabase::GetSongsByWhereJSON().
GetRecNo()
int CDatabase::DatasetLayout::GetRecNo (int fieldno)
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), and CMusicDatabase::GetSongsByWhereJSON().
HasFilterFields()
bool CDatabase::DatasetLayout::HasFilterFields ()
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), and CMusicDatabase::GetSongsByWhereJSON().
SetFetch()
void CDatabase::DatasetLayout::SetFetch (int fieldno, bool bFetch = true)
Referenced by CMusicDatabase::GetArtistsByWhereJSON().
SetField()
void CDatabase::DatasetLayout::SetField (int fieldNo, const std::string & strField, bool bOutput = false)
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), and CMusicDatabase::GetSongsByWhereJSON().
Member Data Documentation
m_fields
std::vector<DatasetFieldInfo> CDatabase::DatasetLayout::m_fields private
The documentation for this class was generated from the following files:
Database.h
Database.cpp