Kodi Documentation: PVR::CPVRCustomTimerSettings Class Reference
PVR::CPVRCustomTimerSettings Class Reference
#include <PVRCustomTimerSettings.h>
Public Member Functions
CPVRCustomTimerSettings (const CPVRTimerType &timerType, const CPVRTimerInfoTag::CustomPropsMap &customProps, const std::map< int, std::shared_ptr< CPVRTimerType > > &typeEntries)
virtual ~CPVRCustomTimerSettings ()=default
void SetTimerType (const CPVRTimerType &timerType)
void AddSettings (IPVRSettingsContainer &settingsContainer, const std::shared_ptr< CSettingGroup > &group)
bool IsCustomSetting (const std::string &settingId) const
bool IsCustomIntSetting (const std::string &settingId) const
bool IsCustomStringSetting (const std::string &settingId) const
const CPVRTimerInfoTag::CustomPropsMap & GetProperties () const
bool UpdateIntProperty (const std::shared_ptr< const CSetting > &setting)
bool UpdateStringProperty (const std::shared_ptr< const CSetting > &setting)
std::string GetSettingsLabel (const std::string &settingId) const
bool IntSettingDefinitionsFiller (const std::string &settingId, std::vector< IntegerSettingOption > &list, int &current)
bool StringSettingDefinitionsFiller (const std::string &settingId, std::vector< StringSettingOption > &list, std::string &current)
bool IsSettingReadonlyForTimerState (const std::string &settingId, PVR_TIMER_STATE timerState) const
bool IsSettingSupportedForTimerType (const std::string &setting, const CPVRTimerType &timerType) const
Private Types
using CustomSettingDefinitionsMap = std::map< std::string, std::shared_ptr< const CPVRTimerSettingDefinition > >
Private Member Functions
std::shared_ptr< const CPVRTimerSettingDefinition > GetSettingDefintion (const std::string &settingId) const
Private Attributes
CustomSettingDefinitionsMap m_customSettingDefs
CPVRTimerInfoTag::CustomPropsMap m_customProps
Member Typedef Documentation
CustomSettingDefinitionsMap
using PVR::CPVRCustomTimerSettings::CustomSettingDefinitionsMap = std::map<std::string, std::shared_ptr<const CPVRTimerSettingDefinition> > private
Constructor & Destructor Documentation
CPVRCustomTimerSettings()
PVR::CPVRCustomTimerSettings::CPVRCustomTimerSettings (const CPVRTimerType & timerType, const CPVRTimerInfoTag::CustomPropsMap & customProps, const std::map< int, std::shared_ptr< CPVRTimerType > > & typeEntries)
References LOGERROR, m_customSettingDefs, SetTimerType(), PVR::SETTING_TMR_CUSTOM_INT, and PVR::SETTING_TMR_CUSTOM_STRING.
~CPVRCustomTimerSettings()
virtual PVR::CPVRCustomTimerSettings::~CPVRCustomTimerSettings () virtual default
Member Function Documentation
AddSettings()
void PVR::CPVRCustomTimerSettings::AddSettings (IPVRSettingsContainer & settingsContainer, const std::shared_ptr< CSettingGroup > & group)
References PVR::IPVRSettingsContainer::AddMultiIntSetting(), PVR::IPVRSettingsContainer::AddMultiStringSetting(), PVR::IPVRSettingsContainer::AddSingleIntSetting(), and PVR::IPVRSettingsContainer::AddSingleStringSetting().
GetProperties()
const CPVRTimerInfoTag::CustomPropsMap & PVR::CPVRCustomTimerSettings::GetProperties () const inline
References m_customProps.
GetSettingDefintion()
std::shared_ptr< const CPVRTimerSettingDefinition > PVR::CPVRCustomTimerSettings::GetSettingDefintion (const std::string & settingId) const private
GetSettingsLabel()
std::string PVR::CPVRCustomTimerSettings::GetSettingsLabel (const std::string & settingId) const
IntSettingDefinitionsFiller()
bool PVR::CPVRCustomTimerSettings::IntSettingDefinitionsFiller (const std::string & settingId, std::vector< IntegerSettingOption > & list, int & current)
References LOGERROR, value, and values.
IsCustomIntSetting()
bool PVR::CPVRCustomTimerSettings::IsCustomIntSetting (const std::string & settingId) const
References PVR::SETTING_TMR_CUSTOM_INT.
IsCustomSetting()
bool PVR::CPVRCustomTimerSettings::IsCustomSetting (const std::string & settingId) const
IsCustomStringSetting()
bool PVR::CPVRCustomTimerSettings::IsCustomStringSetting (const std::string & settingId) const
References PVR::SETTING_TMR_CUSTOM_STRING.
IsSettingReadonlyForTimerState()
bool PVR::CPVRCustomTimerSettings::IsSettingReadonlyForTimerState (const std::string & settingId, PVR_TIMER_STATE timerState) const
References LOGERROR.
IsSettingSupportedForTimerType()
bool PVR::CPVRCustomTimerSettings::IsSettingSupportedForTimerType (const std::string & setting, const CPVRTimerType & timerType) const
References PVR::CPVRTimerType::GetClientId(), PVR::CPVRTimerType::GetTypeId(), and LOGERROR.
SetTimerType()
void PVR::CPVRCustomTimerSettings::SetTimerType (const CPVRTimerType & timerType)
References PVR::CPVRTimerType::GetClientId(), PVR::CPVRTimerType::GetTypeId(), m_customProps, and m_customSettingDefs.
Referenced by CPVRCustomTimerSettings().
StringSettingDefinitionsFiller()
bool PVR::CPVRCustomTimerSettings::StringSettingDefinitionsFiller (const std::string & settingId, std::vector< StringSettingOption > & list, std::string & current)
References LOGERROR, value, and values.
UpdateIntProperty()
bool PVR::CPVRCustomTimerSettings::UpdateIntProperty (const std::shared_ptr< const CSetting > & setting)
References LOGERROR.
UpdateStringProperty()
bool PVR::CPVRCustomTimerSettings::UpdateStringProperty (const std::shared_ptr< const CSetting > & setting)
References LOGERROR.
Member Data Documentation
m_customProps
CPVRTimerInfoTag::CustomPropsMap PVR::CPVRCustomTimerSettings::m_customProps private
Referenced by GetProperties(), and SetTimerType().
m_customSettingDefs
CustomSettingDefinitionsMap PVR::CPVRCustomTimerSettings::m_customSettingDefs private
Referenced by CPVRCustomTimerSettings(), and SetTimerType().
The documentation for this class was generated from the following files:
PVRCustomTimerSettings.h
PVRCustomTimerSettings.cpp