Kodi Documentation: CTextSearch Class Reference
CTextSearch Class Reference final
#include <TextSearch.h>
Public Member Functions
CTextSearch (const std::string &strSearchTerms, bool bCaseSensitive=false, TextSearchDefault defaultSearchMode=SEARCH_DEFAULT_OR)
bool Search (const std::string &strHaystack) const
bool IsValid (void) const
Private Member Functions
void ExtractSearchTerms (const std::string &strSearchTerm, TextSearchDefault defaultSearchMode)
Static Private Member Functions
static void GetAndCutNextTerm (std::string &strSearchTerm, std::string &strNextTerm)
Private Attributes
bool m_bCaseSensitive
std::vector< std::string > m_AND
std::vector< std::string > m_OR
std::vector< std::string > m_NOT
Constructor & Destructor Documentation
CTextSearch()
CTextSearch::CTextSearch (const std::string & strSearchTerms, bool bCaseSensitive = false, TextSearchDefault defaultSearchMode = SEARCH_DEFAULT_OR)
References ExtractSearchTerms(), and m_bCaseSensitive.
Member Function Documentation
ExtractSearchTerms()
void CTextSearch::ExtractSearchTerms (const std::string & strSearchTerm, TextSearchDefault defaultSearchMode) private
References GetAndCutNextTerm(), m_AND, m_bCaseSensitive, m_NOT, m_OR, SEARCH_DEFAULT_AND, SEARCH_DEFAULT_NOT, and SEARCH_DEFAULT_OR.
Referenced by CTextSearch().
GetAndCutNextTerm()
void CTextSearch::GetAndCutNextTerm (std::string & strSearchTerm, std::string & strNextTerm) static private
Referenced by ExtractSearchTerms().
IsValid()
bool CTextSearch::IsValid (void) const
References m_AND, m_NOT, and m_OR.
Referenced by Search().
Search()
bool CTextSearch::Search (const std::string & strHaystack) const
References IsValid(), m_AND, m_bCaseSensitive, m_NOT, and m_OR.
Referenced by PVR::CPVREpgSearchFilter::MatchSearchTerm().
Member Data Documentation
m_AND
std::vector<std::string> CTextSearch::m_AND private
Referenced by ExtractSearchTerms(), IsValid(), and Search().
m_bCaseSensitive
bool CTextSearch::m_bCaseSensitive private
Referenced by CTextSearch(), ExtractSearchTerms(), and Search().
m_NOT
std::vector<std::string> CTextSearch::m_NOT private
Referenced by ExtractSearchTerms(), IsValid(), and Search().
m_OR
std::vector<std::string> CTextSearch::m_OR private
Referenced by ExtractSearchTerms(), IsValid(), and Search().
The documentation for this class was generated from the following files:
TextSearch.h
TextSearch.cpp