Kodi Documentation: ADDON::CRepositoryUpdateJob Class Reference
ADDON::CRepositoryUpdateJob Class Reference
Public Member Functions
CRepositoryUpdateJob (const RepositoryPtr &repo)
~CRepositoryUpdateJob () override=default
bool DoWork () override
Main workhorse function of CJob instances.
const RepositoryPtr & GetAddon () const
Public Member Functions inherited from CProgressJob
~CProgressJob () override
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
bool ShouldCancel (unsigned int progress, unsigned int total) const override
Function for longer jobs to report progress and check whether they have been cancelled.
bool DoModal ()
Executes the job showing a modal progress dialog.
void SetProgressIndicators (CGUIDialogProgressBarHandle *progressBar, CGUIDialogProgress *progressDialog, bool updateProgress=true, bool updateInformation=true)
Sets the given progress indicators to be used during execution of the job.
bool HasProgressIndicator () const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
Private Attributes
const RepositoryPtr m_repo
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Protected Member Functions inherited from CProgressJob
CProgressJob ()
CProgressJob (CGUIDialogProgressBarHandle *progressBar)
bool IsModal () const
Whether the job is being run modally or in the background.
CGUIDialogProgressBarHandle * GetProgressBar () const
Returns the progress bar indicating the progress of the job.
void SetProgressBar (CGUIDialogProgressBarHandle *progress)
Sets the progress bar indicating the progress of the job.
CGUIDialogProgress * GetProgressDialog () const
Returns the progress dialog indicating the progress of the job.
void SetProgressDialog (CGUIDialogProgress *progressDialog)
Sets the progress bar indicating the progress of the job.
bool GetAutoClose ()
Whether to automatically close the progress indicator in MarkFinished().
void SetAutoClose (bool autoClose)
Set whether to automatically close the progress indicator in MarkFinished().
bool GetUpdateProgress ()
Whether to update the progress bar or not.
void SetUpdateProgress (bool updateProgress)
Set whether to update the progress bar or not.
bool GetUpdateInformation ()
Whether to update the progress information or not.
void SetUpdateInformation (bool updateInformation)
Set whether to update the progress information or not.
void ShowProgressDialog () const
Makes sure that the modal dialog is being shown.
void SetTitle (const std::string &title)
Sets the given title as the title of the progress bar.
void SetText (const std::string &text)
Sets the given text as the description of the progress bar.
void SetProgress (float percentage) const
Sets the progress of the progress bar to the given value in percentage.
void SetProgress (int currentStep, int totalSteps) const
Sets the progress of the progress bar to the given value.
void MarkFinished ()
Marks the progress as finished by setting it to 100%.
bool IsCancelled () const
Checks if the progress dialog has been cancelled.
Constructor & Destructor Documentation
CRepositoryUpdateJob()
ADDON::CRepositoryUpdateJob::CRepositoryUpdateJob (const RepositoryPtr & repo) inline explicit
~CRepositoryUpdateJob()
ADDON::CRepositoryUpdateJob::~CRepositoryUpdateJob () override default
Member Function Documentation
DoWork()
bool ADDON::CRepositoryUpdateJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References addons, CDatabase::BeginMultipleExecute(), CDatabase::CommitMultipleExecute(), ADDON::CAddonMgr::FindInstallableById(), CServiceBroker::GetAddonMgr(), CDateTime::GetCurrentDateTime(), ADDON::CAddonDatabase::GetRepoChecksum(), ADDON::CAddonDatabase::GetRepoUpdateData(), CTextureDatabase::InvalidateCachedTexture(), CLog::Log(), LOGDEBUG, m_repo, CProgressJob::MarkFinished(), ADDON::CAddonDatabase::Open(), CTextureDatabase::Open(), ADDON::CAddonDatabase::SetRepoUpdateData(), ADDON::CRepository::STATUS_ERROR, ADDON::CRepository::STATUS_NOT_MODIFIED, and ADDON::CAddonDatabase::UpdateRepositoryContent().
GetAddon()
const RepositoryPtr & ADDON::CRepositoryUpdateJob::GetAddon () const inline
References m_repo.
Member Data Documentation
m_repo
const RepositoryPtr ADDON::CRepositoryUpdateJob::m_repo private
Referenced by DoWork(), and GetAddon().
The documentation for this class was generated from the following file:
RepositoryUpdater.cpp