Kodi Documentation: WinRtUtil.cpp File Reference
WinRtUtil.cpp File Reference
#include "WinRtUtil.h"
#include "utils/SystemInfo.h"
#include "utils/log.h"
#include "platform/win32/WIN32Util.h"
#include <winrt/Windows.Devices.Display.Core.h>
#include <winrt/Windows.Graphics.Display.h>
Functions
static constexpr std::string_view AdvancedColorKindToString (AdvancedColorKind kind)
static void LogAdvancedColorInfo (AdvancedColorInfo colorInfo)
Function Documentation
AdvancedColorKindToString()
static constexpr std::string_view AdvancedColorKindToString (AdvancedColorKind kind) static constexpr
Referenced by LogAdvancedColorInfo().
LogAdvancedColorInfo()
static void LogAdvancedColorInfo (AdvancedColorInfo colorInfo) static
References AdvancedColorKindToString(), and LOGDEBUG.
Referenced by CWinRtUtil::GetWindowsHDRStatus().