Kodi Documentation: KODI::GAME::IGameClientStream Class Reference
KODI::GAME::IGameClientStream Class Reference abstract
Games
#include <IGameClientStream.h>
Public Member Functions
virtual ~IGameClientStream ()=default
virtual bool OpenStream (RETRO::IRetroPlayerStream *stream, const game_stream_properties &properties)=0
Open the stream.
virtual void CloseStream ()=0
Release the RetroPlayer stream resource.
virtual bool GetBuffer (unsigned int width, unsigned int height, game_stream_buffer &buffer)
Get a buffer for zero-copy stream data.
virtual void ReleaseBuffer (game_stream_buffer &buffer)
Free an allocated buffer.
virtual void AddData (const game_stream_packet &packet)=0
Add a data packet to a stream.
Constructor & Destructor Documentation
~IGameClientStream()
virtual KODI::GAME::IGameClientStream::~IGameClientStream () virtual default
Member Function Documentation
AddData()
virtual void KODI::GAME::IGameClientStream::AddData (const game_stream_packet & packet) pure virtual
Add a data packet to a stream.
Parameters
packet The data packet
Implemented in KODI::GAME::CGameClientStreamAudio, and KODI::GAME::CGameClientStreamVideo.
Referenced by KODI::GAME::CGameClient::cb_add_stream_data().
CloseStream()
virtual void KODI::GAME::IGameClientStream::CloseStream () pure virtual
Release the RetroPlayer stream resource.
Implemented in KODI::GAME::CGameClientStreamAudio, and KODI::GAME::CGameClientStreamVideo.
GetBuffer()
virtual bool KODI::GAME::IGameClientStream::GetBuffer (unsigned int width, unsigned int height, game_stream_buffer & buffer) inline virtual
Get a buffer for zero-copy stream data.
Parameters
width The framebuffer width, or 0 for no width specified
height The framebuffer height, or 0 for no height specified
[out] buffer The buffer, or unmodified if false is returned
If this returns true, buffer must be freed using ReleaseBuffer().
Returns
True if buffer was set, false otherwise
Reimplemented in KODI::GAME::CGameClientStreamSwFramebuffer.
Referenced by KODI::GAME::CGameClient::cb_get_stream_buffer().
OpenStream()
virtual bool KODI::GAME::IGameClientStream::OpenStream (RETRO::IRetroPlayerStream * stream, const game_stream_properties & properties) pure virtual
Open the stream.
Parameters
stream The RetroPlayer resource to take ownership of
Returns
True if the stream was opened, false otherwise
Implemented in KODI::GAME::CGameClientStreamAudio, and KODI::GAME::CGameClientStreamVideo.
ReleaseBuffer()
virtual void KODI::GAME::IGameClientStream::ReleaseBuffer (game_stream_buffer & buffer) inline virtual
Free an allocated buffer.
Parameters
buffer The buffer returned from GetBuffer()
Referenced by KODI::GAME::CGameClient::cb_release_stream_buffer().
The documentation for this class was generated from the following file:
IGameClientStream.h