Kodi Documentation: CDVDOverlayContainer Class Reference
CDVDOverlayContainer Class Reference
#include <DVDOverlayContainer.h>
Public Member Functions
virtual ~CDVDOverlayContainer ()
void ProcessAndAddOverlayIfValid (const std::shared_ptr< CDVDOverlay > &pPicture)
Adds an overlay into the container by processing the existing overlay collection first.
VecOverlays * GetOverlays ()
bool ContainsOverlayType (DVDOverlayType type)
void Clear ()
void Flush ()
void CleanUp (double pts)
size_t GetSize ()
void UpdateOverlayInfo (const std::shared_ptr< CDVDInputStreamNavigator > &pStream, CDVDDemuxSPU *pSpu, int iAction)
Private Member Functions
VecOverlays::iterator Remove (VecOverlays::iterator itOverlay)
Private Attributes
VecOverlays m_overlays
Constructor & Destructor Documentation
~CDVDOverlayContainer()
CDVDOverlayContainer::~CDVDOverlayContainer () virtual
References Clear().
Member Function Documentation
CleanUp()
void CDVDOverlayContainer::CleanUp (double pts)
References m_overlays, and Remove().
Referenced by CVideoPlayerVideo::ProcessOverlays().
Clear()
void CDVDOverlayContainer::Clear ()
References m_overlays.
Referenced by CVideoPlayerSubtitle::CloseStream(), CVideoPlayer::OnDiscNavResult(), CVideoPlayerSubtitle::Process(), and ~CDVDOverlayContainer().
ContainsOverlayType()
bool CDVDOverlayContainer::ContainsOverlayType (DVDOverlayType type)
References m_overlays.
Flush()
void CDVDOverlayContainer::Flush ()
References m_overlays.
Referenced by CVideoPlayerSubtitle::SendMessage().
GetOverlays()
VecOverlays * CDVDOverlayContainer::GetOverlays ()
References m_overlays.
Referenced by CVideoPlayerVideo::ProcessOverlays().
GetSize()
size_t CDVDOverlayContainer::GetSize ()
References m_overlays.
Referenced by CVideoPlayerSubtitle::AcceptsData(), CVideoPlayerSubtitle::IsStalled(), and CVideoPlayerSubtitle::Process().
ProcessAndAddOverlayIfValid()
void CDVDOverlayContainer::ProcessAndAddOverlayIfValid (const std::shared_ptr< CDVDOverlay > & pPicture)
Adds an overlay into the container by processing the existing overlay collection first.
Processes the overlay collection whenever a new overlay is added. Useful to change the overlay's PTS values of previously added overlays if the collection itself is sequential. This is, for example, the case of ASS subtitles in which a single call to ass_render_frame generates all the subtitle images on a single call even if two subtitles exist at the same time frame. Other cases might exist where an overlay shouldn't be added to the collection if completely contained in another overlay.
Parameters
pPicture pointer to the overlay to be evaluated and possibly added to the collection
References m_overlays.
Referenced by CVideoPlayer::OnDiscNavResult(), CVideoPlayerSubtitle::Process(), and CVideoPlayerSubtitle::SendMessage().
Remove()
VecOverlays::iterator CDVDOverlayContainer::Remove (VecOverlays::iterator itOverlay) private
References m_overlays.
Referenced by CleanUp().
UpdateOverlayInfo()
void CDVDOverlayContainer::UpdateOverlayInfo (const std::shared_ptr< CDVDInputStreamNavigator > & pStream, CDVDDemuxSPU * pSpu, int iAction)
References DVDOVERLAY_TYPE_SPU, and m_overlays.
Referenced by CVideoPlayerSubtitle::UpdateOverlayInfo().
Member Data Documentation
m_overlays
VecOverlays CDVDOverlayContainer::m_overlays private
Referenced by CleanUp(), Clear(), ContainsOverlayType(), Flush(), GetOverlays(), GetSize(), ProcessAndAddOverlayIfValid(), Remove(), and UpdateOverlayInfo().
The documentation for this class was generated from the following files:
DVDOverlayContainer.h
DVDOverlayContainer.cpp