Kodi Documentation: CVideoPlayerAudio Class Reference
CVideoPlayerAudio Class Reference
#include <VideoPlayerAudio.h>
Classes
struct SInfo
Public Member Functions
CVideoPlayerAudio (CDVDClock *pClock, CDVDMessageQueue &parent, CProcessInfo &processInfo, double messageQueueTimeSize)
~CVideoPlayerAudio () override
bool OpenStream (CDVDStreamInfo hints) override
void CloseStream (bool bWaitForBuffers) override
void SetSpeed (int speed) override
void Flush (bool sync) override
bool AcceptsData () const override
bool HasData () const override
int GetLevel () const override
bool IsInited () const override
void SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority=0) override
void FlushMessages () override
void SetDynamicRangeCompression (long drc) override
float GetDynamicRangeAmplification () const override
std::string GetPlayerInfo () override
int GetAudioChannels () override
double GetCurrentPts () override
bool IsStalled () const override
bool IsPassthrough () const override
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Public Member Functions inherited from IDVDStreamPlayerAudio
IDVDStreamPlayerAudio (CProcessInfo &processInfo)
~IDVDStreamPlayerAudio () override=default
virtual void SetVolume (float fVolume)
virtual void SetMute (bool bOnOff)
virtual bool IsEOS ()
Public Member Functions inherited from IDVDStreamPlayer
IDVDStreamPlayer (CProcessInfo &processInfo)
virtual ~IDVDStreamPlayer ()=default
Protected Member Functions
void OnStartup () override
void OnExit () override
void Process () override
bool ProcessDecoderOutput (DVDAudioFrame &audioframe)
void UpdatePlayerInfo ()
void OpenStream (CDVDStreamInfo &hints, std::unique_ptr< CDVDAudioCodec > codec)
bool SwitchCodecIfNeeded ()
void SetSyncType (bool passthrough)
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes
CDVDMessageQueue m_messageQueue
CDVDMessageQueue & m_messageParent
CDVDStreamInfo m_streaminfo
double m_audioClock
CAudioSinkAE m_audioSink
CDVDClock * m_pClock
std::unique_ptr< CDVDAudioCodec > m_pAudioCodec
BitstreamStats m_audioStats
int m_speed
bool m_stalled
bool m_paused
IDVDStreamPlayer::ESyncState m_syncState
XbmcThreads::EndTime m_syncTimer
int m_synctype
int m_prevsynctype
bool m_prevskipped
double m_maxspeedadjust
CCriticalSection m_info_section
SInfo m_info
bool m_displayReset = false
unsigned int m_disconAdjustTimeMs = 50
int m_disconAdjustCounter = 0
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Protected Attributes inherited from IDVDStreamPlayer
CProcessInfo & m_processInfo
Additional Inherited Members
Public Types inherited from IDVDStreamPlayer
enum ESyncState { SYNC_STARTING , SYNC_WAITSYNC , SYNC_INSYNC }
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Constructor & Destructor Documentation
CVideoPlayerAudio()
CVideoPlayerAudio::CVideoPlayerAudio (CDVDClock * pClock, CDVDMessageQueue & parent, CProcessInfo & processInfo, double messageQueueTimeSize)
References DVD_PLAYSPEED_NORMAL, CProcessInfo::GetMaxPassthroughOffSyncDuration(), m_audioClock, m_disconAdjustTimeMs, m_maxspeedadjust, m_messageQueue, m_paused, m_pClock, m_prevskipped, m_prevsynctype, m_speed, m_stalled, m_syncState, m_synctype, CDVDMessageQueue::SetMaxDataSize(), CDVDMessageQueue::SetMaxTimeSize(), SYNC_DISCON, and IDVDStreamPlayer::SYNC_STARTING.
~CVideoPlayerAudio()
CVideoPlayerAudio::~CVideoPlayerAudio () override
References CThread::StopThread().
Member Function Documentation
AcceptsData()
bool CVideoPlayerAudio::AcceptsData () const override virtual
Implements IDVDStreamPlayerAudio.
References full, CDVDMessageQueue::IsFull(), and m_messageQueue.
CloseStream()
void CVideoPlayerAudio::CloseStream (bool bWaitForBuffers) override virtual
Implements IDVDStreamPlayerAudio.
References CDVDMessageQueue::Abort(), CAudioSinkAE::Destroy(), CAudioSinkAE::Drain(), CDVDMessageQueue::End(), CAudioSinkAE::Flush(), CServiceBroker::GetActiveAE(), IAE::IsSuspended(), CLog::Log(), LOGINFO, m_audioSink, CThread::m_bStop, m_messageQueue, m_pAudioCodec, m_speed, CThread::StopThread(), and CDVDMessageQueue::WaitUntilEmpty().
Flush()
void CVideoPlayerAudio::Flush (bool sync) override virtual
Implements IDVDStreamPlayerAudio.
References CAudioSinkAE::AbortAddPackets(), CDVDMessageQueue::Flush(), CDVDMsg::GENERAL_FLUSH, m_audioSink, m_messageQueue, and CDVDMessageQueue::Put().
FlushMessages()
void CVideoPlayerAudio::FlushMessages () inline override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::Flush(), and m_messageQueue.
GetAudioChannels()
int CVideoPlayerAudio::GetAudioChannels () override virtual
Implements IDVDStreamPlayerAudio.
References CDVDStreamInfo::channels, and m_streaminfo.
GetCurrentPts()
double CVideoPlayerAudio::GetCurrentPts () inline override virtual
Implements IDVDStreamPlayerAudio.
References m_info, m_info_section, and CVideoPlayerAudio::SInfo::pts.
GetDynamicRangeAmplification()
float CVideoPlayerAudio::GetDynamicRangeAmplification () const inline override virtual
Implements IDVDStreamPlayerAudio.
GetLevel()
int CVideoPlayerAudio::GetLevel () const inline override virtual
Implements IDVDStreamPlayerAudio.
References CDVDMessageQueue::GetLevel(), and m_messageQueue.
GetPlayerInfo()
std::string CVideoPlayerAudio::GetPlayerInfo () override virtual
Implements IDVDStreamPlayerAudio.
References CVideoPlayerAudio::SInfo::info, m_info, and m_info_section.
HasData()
bool CVideoPlayerAudio::HasData () const inline override virtual
Implements IDVDStreamPlayerAudio.
References CDVDMessageQueue::GetDataSize(), and m_messageQueue.
IsInited()
bool CVideoPlayerAudio::IsInited () const inline override virtual
Implements IDVDStreamPlayerAudio.
References CDVDMessageQueue::IsInited(), and m_messageQueue.
IsPassthrough()
bool CVideoPlayerAudio::IsPassthrough () const override virtual
Implements IDVDStreamPlayerAudio.
References m_info, m_info_section, and CVideoPlayerAudio::SInfo::passthrough.
IsStalled()
bool CVideoPlayerAudio::IsStalled () const inline override virtual
Implements IDVDStreamPlayerAudio.
References m_stalled.
OnExit()
void CVideoPlayerAudio::OnExit () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
OnStartup()
void CVideoPlayerAudio::OnStartup () override protected virtual
Reimplemented from CThread.
OpenStream() [1/2]
void CVideoPlayerAudio::OpenStream (CDVDStreamInfo & hints, std::unique_ptr< CDVDAudioCodec > codec) protected
References CDVDStreamInfo::channels, CDVDMsg::DEMUXER_PACKET, CDVDMessageQueue::GetPacketCount(), CServiceBroker::GetSettingsComponent(), CProcessInfo::IsRealtimeStream(), LOGINFO, m_audioClock, m_disconAdjustTimeMs, m_maxspeedadjust, m_messageParent, m_messageQueue, m_pAudioCodec, m_prevskipped, m_prevsynctype, IDVDStreamPlayer::m_processInfo, m_stalled, m_streaminfo, m_syncState, m_synctype, CDVDMsg::PLAYER_AVCHANGE, CDVDMessageQueue::Put(), CProcessInfo::ResetAudioCodecInfo(), CDVDStreamInfo::samplerate, CSettings::SETTING_VIDEOPLAYER_USEDISPLAYASCLOCK, SwitchCodecIfNeeded(), SYNC_DISCON, SYNC_RESAMPLE, and IDVDStreamPlayer::SYNC_STARTING.
OpenStream() [2/2]
bool CVideoPlayerAudio::OpenStream (CDVDStreamInfo hints) override virtual
Implements IDVDStreamPlayerAudio.
References CProcessInfo::AllowDTSHDDecode(), CDVDStreamInfo::codec, CThread::Create(), CDVDFactoryCodec::CreateAudioCodec(), CAudioSinkAE::GetPassthroughStreamType(), CServiceBroker::GetSettingsComponent(), CDVDMessageQueue::Init(), CDVDMessageQueue::IsInited(), CProcessInfo::IsRealtimeStream(), CLog::Log(), LOGERROR, LOGINFO, m_audioSink, m_messageQueue, IDVDStreamPlayer::m_processInfo, OpenStream(), CDVDStreamInfo::profile, CDVDMessageQueue::Put(), CDVDStreamInfo::samplerate, and CSettings::SETTING_VIDEOPLAYER_USEDISPLAYASCLOCK.
Referenced by OpenStream(), and Process().
Process()
void CVideoPlayerAudio::Process (void) override protected virtual
Reimplemented from CThread.
References BitstreamStats::AddSampleBytes(), CDVDMsg::DEMUXER_PACKET, CAudioSinkAE::Drain(), DVD_PLAYSPEED_NORMAL, DVD_PLAYSPEED_PAUSE, DVD_TIME_BASE, CAudioSinkAE::Flush(), stDVDAudioFrame::framesOut, CDVDMsg::GENERAL_EOF, CDVDMsg::GENERAL_FLUSH, CDVDMsg::GENERAL_PAUSE, CDVDMsg::GENERAL_RESET, CDVDMsg::GENERAL_RESYNC, CDVDMsg::GENERAL_STREAMCHANGE, CDVDMsg::GENERAL_SYNCHRONIZE, CDVDMessageQueue::Get(), CAudioSinkAE::GetCacheTime(), CAudioSinkAE::GetDelay(), CDVDMessageQueue::GetLevel(), DEMUX_PACKET::iSize, CProcessInfo::IsTempoAllowed(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_audioClock, m_audioSink, m_audioStats, CThread::m_bStop, m_disconAdjustCounter, m_displayReset, m_messageParent, m_messageQueue, m_pAudioCodec, m_paused, IDVDStreamPlayer::m_processInfo, m_speed, m_stalled, m_syncState, m_syncTimer, MSGQ_IS_ERROR, MSGQ_TIMEOUT, stDVDAudioFrame::nb_frames, OpenStream(), CAudioSinkAE::Pause(), SStateMsg::player, CDVDMsg::PLAYER_DISPLAY_RESET, CDVDMsg::PLAYER_REPORT_STATE, CDVDMsg::PLAYER_REQUEST_STATE, CDVDMsg::PLAYER_SETSPEED, ProcessDecoderOutput(), CDVDMessageQueue::Put(), CDVDMessageQueue::PutBack(), CDVDMessageQueue::ReceivedAbortRequest(), CAudioSinkAE::Resume(), CThread::Sleep(), BitstreamStats::Start(), IDVDStreamPlayer::SYNC_INSYNC, IDVDStreamPlayer::SYNC_STARTING, IDVDStreamPlayer::SYNC_WAITSYNC, SYNCSOURCE_AUDIO, SStateMsg::syncState, UpdatePlayerInfo(), VideoPlayer_AUDIO, and Wait().
ProcessDecoderOutput()
bool CVideoPlayerAudio::ProcessDecoderOutput (DVDAudioFrame & audioframe) protected
References CAudioSinkAE::AddPackets(), stDVDAudioFrame::bits_per_sample, SStartMsg::cachetime, SStartMsg::cachetotal, stDVDAudioFrame::centerMixLevel, CDVDStreamInfo::channellayout, CDVDStreamInfo::channels, CDVDStreamInfo::codec, CAEChannelInfo::Count(), CAudioSinkAE::Create(), CAudioSinkAE::Destroy(), CAudioSinkAE::Drain(), stDVDAudioFrame::duration, DVD_MSEC_TO_TIME(), DVD_NOPTS_VALUE, DVD_TIME_BASE, CDVDClock::ErrorAdjust(), stDVDAudioFrame::format, stDVDAudioFrame::framesOut, CAEUtil::GetAEChannelLayout(), CAudioSinkAE::GetCacheTime(), CAudioSinkAE::GetCacheTotal(), CAudioSinkAE::GetDelay(), CAudioSinkAE::GetMaxDelay(), CAudioSinkAE::GetSyncError(), CProcessInfo::GetVideoSettings(), stDVDAudioFrame::hasDownmix, stDVDAudioFrame::hasTimestamp, CProcessInfo::IsRealtimeStream(), CAudioSinkAE::IsValidFormat(), CLog::Log(), LOGERROR, m_audioClock, m_audioSink, CVideoSettings::m_CenterMixLevel, AEAudioFormat::m_channelLayout, m_disconAdjustCounter, m_disconAdjustTimeMs, m_displayReset, m_messageParent, m_pAudioCodec, m_pClock, m_prevsynctype, IDVDStreamPlayer::m_processInfo, AEAudioFormat::m_sampleRate, m_speed, m_stalled, m_streaminfo, m_syncState, m_synctype, CVideoSettings::m_VolumeAmplification, stDVDAudioFrame::nb_frames, stDVDAudioFrame::passthrough, SStartMsg::player, CDVDMsg::PLAYER_AVCHANGE, CDVDMsg::PLAYER_STARTED, stDVDAudioFrame::pts, CDVDMessageQueue::Put(), CAudioSinkAE::Resume(), CDVDStreamInfo::samplerate, CProcessInfo::SetAudioBitsPerSample(), CProcessInfo::SetAudioChannels(), CProcessInfo::SetAudioDecoderName(), CProcessInfo::SetAudioSampleRate(), CAudioSinkAE::SetDynamicRangeCompression(), CAudioSinkAE::SetSyncErrorCorrection(), SetSyncType(), SwitchCodecIfNeeded(), SYNC_DISCON, IDVDStreamPlayer::SYNC_INSYNC, SYNC_RESAMPLE, IDVDStreamPlayer::SYNC_STARTING, IDVDStreamPlayer::SYNC_WAITSYNC, SStartMsg::timestamp, and VideoPlayer_AUDIO.
Referenced by Process().
SendMessage()
void CVideoPlayerAudio::SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority = 0) inline override virtual
Implements IDVDStreamPlayerAudio.
References m_messageQueue, and CDVDMessageQueue::Put().
SetDynamicRangeCompression()
void CVideoPlayerAudio::SetDynamicRangeCompression (long drc) inline override virtual
Implements IDVDStreamPlayerAudio.
References m_audioSink, and CAudioSinkAE::SetDynamicRangeCompression().
SetSpeed()
void CVideoPlayerAudio::SetSpeed (int speed) override virtual
Implements IDVDStreamPlayerAudio.
References CDVDMessageQueue::IsInited(), m_messageQueue, m_speed, CDVDMsg::PLAYER_SETSPEED, and CDVDMessageQueue::Put().
SetSyncType()
void CVideoPlayerAudio::SetSyncType (bool passthrough) protected
References CLog::Log(), LOGDEBUG, m_audioSink, m_maxspeedadjust, m_pClock, m_prevsynctype, m_synctype, CDVDClock::SetMaxSpeedAdjust(), CAudioSinkAE::SetResampleMode(), SYNC_DISCON, and SYNC_RESAMPLE.
Referenced by ProcessDecoderOutput().
SwitchCodecIfNeeded()
bool CVideoPlayerAudio::SwitchCodecIfNeeded () protected
Switch codec if needed. Called when the sample rate gotten from the codec changes, in which case we may want to switch passthrough on/off.
References CProcessInfo::AllowDTSHDDecode(), CDVDStreamInfo::codec, CDVDFactoryCodec::CreateAudioCodec(), CAudioSinkAE::GetPassthroughStreamType(), CServiceBroker::GetSettingsComponent(), CProcessInfo::IsRealtimeStream(), CLog::Log(), LOGDEBUG, LOGINFO, m_audioSink, m_displayReset, m_pAudioCodec, IDVDStreamPlayer::m_processInfo, m_streaminfo, m_synctype, CDVDStreamInfo::profile, CDVDStreamInfo::samplerate, CSettings::SETTING_VIDEOPLAYER_USEDISPLAYASCLOCK, and SYNC_RESAMPLE.
Referenced by OpenStream(), and ProcessDecoderOutput().
UpdatePlayerInfo()
void CVideoPlayerAudio::UpdatePlayerInfo () protected
References BitstreamStats::GetBitrate(), CDVDMessageQueue::GetLevel(), CAudioSinkAE::GetPlayingPts(), CAudioSinkAE::GetResampleRatio(), CDVDMessageQueue::GetTimeSize(), CVideoPlayerAudio::SInfo::info, m_audioSink, m_audioStats, m_disconAdjustCounter, m_disconAdjustTimeMs, m_info, m_info_section, m_messageQueue, m_pAudioCodec, m_synctype, SYNC_DISCON, and SYNC_RESAMPLE.
Referenced by Process().
Member Data Documentation
m_audioClock
double CVideoPlayerAudio::m_audioClock protected
Referenced by CVideoPlayerAudio(), OpenStream(), Process(), and ProcessDecoderOutput().
m_audioSink
CAudioSinkAE CVideoPlayerAudio::m_audioSink protected
Referenced by CloseStream(), Flush(), OpenStream(), Process(), ProcessDecoderOutput(), SetDynamicRangeCompression(), SetSyncType(), SwitchCodecIfNeeded(), and UpdatePlayerInfo().
m_audioStats
BitstreamStats CVideoPlayerAudio::m_audioStats protected
Referenced by Process(), and UpdatePlayerInfo().
m_disconAdjustCounter
int CVideoPlayerAudio::m_disconAdjustCounter = 0 protected
Referenced by Process(), ProcessDecoderOutput(), and UpdatePlayerInfo().
m_disconAdjustTimeMs
unsigned int CVideoPlayerAudio::m_disconAdjustTimeMs = 50 protected
Referenced by CVideoPlayerAudio(), OpenStream(), ProcessDecoderOutput(), and UpdatePlayerInfo().
m_displayReset
bool CVideoPlayerAudio::m_displayReset = false protected
Referenced by Process(), ProcessDecoderOutput(), and SwitchCodecIfNeeded().
m_info
SInfo CVideoPlayerAudio::m_info protected
Referenced by GetCurrentPts(), GetPlayerInfo(), IsPassthrough(), and UpdatePlayerInfo().
m_info_section
CCriticalSection CVideoPlayerAudio::m_info_section mutable protected
Referenced by GetCurrentPts(), GetPlayerInfo(), IsPassthrough(), and UpdatePlayerInfo().
m_maxspeedadjust
double CVideoPlayerAudio::m_maxspeedadjust protected
Referenced by CVideoPlayerAudio(), OpenStream(), and SetSyncType().
m_messageParent
CDVDMessageQueue& CVideoPlayerAudio::m_messageParent protected
Referenced by OpenStream(), Process(), and ProcessDecoderOutput().
m_messageQueue
CDVDMessageQueue CVideoPlayerAudio::m_messageQueue protected
Referenced by AcceptsData(), CloseStream(), CVideoPlayerAudio(), Flush(), FlushMessages(), GetLevel(), HasData(), IsInited(), OpenStream(), OpenStream(), Process(), SendMessage(), SetSpeed(), and UpdatePlayerInfo().
m_pAudioCodec
std::unique_ptr<CDVDAudioCodec> CVideoPlayerAudio::m_pAudioCodec protected
Referenced by CloseStream(), OpenStream(), Process(), ProcessDecoderOutput(), SwitchCodecIfNeeded(), and UpdatePlayerInfo().
m_paused
bool CVideoPlayerAudio::m_paused protected
Referenced by CVideoPlayerAudio(), and Process().
m_pClock
CDVDClock* CVideoPlayerAudio::m_pClock protected
Referenced by CVideoPlayerAudio(), ProcessDecoderOutput(), and SetSyncType().
m_prevskipped
bool CVideoPlayerAudio::m_prevskipped protected
Referenced by CVideoPlayerAudio(), and OpenStream().
m_prevsynctype
int CVideoPlayerAudio::m_prevsynctype protected
Referenced by CVideoPlayerAudio(), OpenStream(), ProcessDecoderOutput(), and SetSyncType().
m_speed
int CVideoPlayerAudio::m_speed protected
Referenced by CloseStream(), CVideoPlayerAudio(), Process(), ProcessDecoderOutput(), and SetSpeed().
m_stalled
bool CVideoPlayerAudio::m_stalled protected
Referenced by CVideoPlayerAudio(), IsStalled(), OpenStream(), Process(), and ProcessDecoderOutput().
m_streaminfo
CDVDStreamInfo CVideoPlayerAudio::m_streaminfo protected
Referenced by GetAudioChannels(), OpenStream(), ProcessDecoderOutput(), and SwitchCodecIfNeeded().
m_syncState
IDVDStreamPlayer::ESyncState CVideoPlayerAudio::m_syncState protected
Referenced by CVideoPlayerAudio(), OpenStream(), Process(), and ProcessDecoderOutput().
m_syncTimer
XbmcThreads::EndTime CVideoPlayerAudio::m_syncTimer protected
Referenced by Process().
m_synctype
int CVideoPlayerAudio::m_synctype protected
Referenced by CVideoPlayerAudio(), OpenStream(), ProcessDecoderOutput(), SetSyncType(), SwitchCodecIfNeeded(), and UpdatePlayerInfo().
The documentation for this class was generated from the following files:
VideoPlayerAudio.h
VideoPlayerAudio.cpp