Kodi Documentation: kodi::addon::PVRIntSettingDefinition Class Reference
kodi::addon::PVRIntSettingDefinition Class Reference
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General » class PVRIntSettingDefinition
#include <General.h>
Public Member Functions
PVRIntSettingDefinition (const std::vector< PVRTypeIntValue > &settingValues, int defaultValue, int minValue, int step, int maxValue)
Class constructor with integrated values.
void SetValues (const std::vector< PVRTypeIntValue > &values, int defaultValue=-1)
optional
value definitions.
std::vector< PVRTypeIntValue > GetValues () const
To get with SetValues changed values.
void SetDefaultValue (int defaultValue)
optional
The default value for this setting.
int GetDefaultValue () const
To get with SetDefaultValue changed values.
void SetMinValue (int minValue)
optional
The minimum value for this setting.
int GetMinValue () const
To get with SetMinValue changed values.
void SetStep (int step)
optional
The amount for increasing the values for this setting from min to max.
int GetStep () const
To get with SetStep changed values.
void SetMaxValue (int maxValue)
optional
The maximum value for this setting.
int GetMaxValue () const
To get with SetMaxValue changed values.
Public Member Functions inherited from kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >
DynamicCStructHdl ()
DynamicCStructHdl (const DynamicCStructHdl &cppClass)
DynamicCStructHdl (const PVR_INT_SETTING_DEFINITION *cStructure)
DynamicCStructHdl (PVR_INT_SETTING_DEFINITION *cStructure)
const DynamicCStructHdl & operator= (const DynamicCStructHdl &right)
const DynamicCStructHdl & operator= (const PVR_INT_SETTING_DEFINITION &right)
virtual ~DynamicCStructHdl ()
operator PVR_INT_SETTING_DEFINITION * ()
operator const PVR_INT_SETTING_DEFINITION * () const
const PVR_INT_SETTING_DEFINITION * GetCStructure () const
PVR_INT_SETTING_DEFINITION * release ()
Static Public Member Functions
static PVR_INT_SETTING_DEFINITION * AllocAndCopyData (const PVRIntSettingDefinition &source)
static PVR_INT_SETTING_DEFINITION * AllocAndCopyData (PVR_INT_SETTING_DEFINITION *source)
static void AllocResources (const PVR_INT_SETTING_DEFINITION *source, PVR_INT_SETTING_DEFINITION *target)
static void FreeResources (PVR_INT_SETTING_DEFINITION *target)
static void ReallocAndCopyData (PVR_INT_SETTING_DEFINITION **source, const PVRIntSettingDefinition &def)
Private Member Functions
PVRIntSettingDefinition (const PVR_INT_SETTING_DEFINITION *def)
PVRIntSettingDefinition (PVR_INT_SETTING_DEFINITION *def)
Friends
class CInstancePVRClient
Additional Inherited Members
Protected Attributes inherited from kodi::addon::DynamicCStructHdl< PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION >
PVR_INT_SETTING_DEFINITION * m_cStructure
Constructor & Destructor Documentation
PVRIntSettingDefinition() [1/2]
kodi::addon::PVRIntSettingDefinition::PVRIntSettingDefinition (const PVR_INT_SETTING_DEFINITION * def) inline private
PVRIntSettingDefinition() [2/2]
kodi::addon::PVRIntSettingDefinition::PVRIntSettingDefinition (PVR_INT_SETTING_DEFINITION * def) inline private
Member Function Documentation
AllocAndCopyData() [1/2]
static PVR_INT_SETTING_DEFINITION * kodi::addon::PVRIntSettingDefinition::AllocAndCopyData (const PVRIntSettingDefinition & source) inline static
References AllocResources(), kodi::addon::DynamicCStructHdl< CPP_CLASS, C_STRUCT >::GetCStructure(), PVR_INT_SETTING_DEFINITION::iDefaultValue, PVR_INT_SETTING_DEFINITION::iMaxValue, PVR_INT_SETTING_DEFINITION::iMinValue, and PVR_INT_SETTING_DEFINITION::iStep.
Referenced by kodi::addon::PVRSettingDefinition::AllocResources(), and ReallocAndCopyData().
AllocAndCopyData() [2/2]
static PVR_INT_SETTING_DEFINITION * kodi::addon::PVRIntSettingDefinition::AllocAndCopyData (PVR_INT_SETTING_DEFINITION * source) inline static
References AllocResources(), PVR_INT_SETTING_DEFINITION::iDefaultValue, PVR_INT_SETTING_DEFINITION::iMaxValue, PVR_INT_SETTING_DEFINITION::iMinValue, and PVR_INT_SETTING_DEFINITION::iStep.
AllocResources()
static void kodi::addon::PVRIntSettingDefinition::AllocResources (const PVR_INT_SETTING_DEFINITION * source, PVR_INT_SETTING_DEFINITION * target) inline static
References kodi::addon::PVRTypeIntValue::AllocAndCopyData(), PVR_INT_SETTING_DEFINITION::iValuesSize, and PVR_INT_SETTING_DEFINITION::values.
Referenced by AllocAndCopyData(), and AllocAndCopyData().
FreeResources()
static void kodi::addon::PVRIntSettingDefinition::FreeResources (PVR_INT_SETTING_DEFINITION * target) inline static
References kodi::addon::PVRTypeIntValue::FreeResources(), PVR_INT_SETTING_DEFINITION::iValuesSize, and PVR_INT_SETTING_DEFINITION::values.
Referenced by kodi::addon::PVRSettingDefinition::FreeResources(), and ReallocAndCopyData().
ReallocAndCopyData()
static void kodi::addon::PVRIntSettingDefinition::ReallocAndCopyData (PVR_INT_SETTING_DEFINITION ** source, const PVRIntSettingDefinition & def) inline static
References AllocAndCopyData(), and FreeResources().
Referenced by kodi::addon::PVRSettingDefinition::SetIntDefinition().
Friends And Related Symbol Documentation
CInstancePVRClient
friend class CInstancePVRClient friend
The documentation for this class was generated from the following file:
kodi-dev-kit/include/kodi/addon-instance/pvr/General.h