Kodi Documentation: KODI::RETRO::CRetroPlayer Class Reference
KODI::RETRO::CRetroPlayer Class Reference
#include <RetroPlayer.h>
Public Member Functions
CRetroPlayer (IPlayerCallback &callback)
~CRetroPlayer () override
bool OpenFile (const CFileItem &file, const CPlayerOptions &options) override
bool CloseFile (bool reopen=false) override
bool IsPlaying () const override
bool CanPause () const override
void Pause () override
bool HasVideo () const override
bool HasAudio () const override
bool HasGame () const override
bool CanSeek () const override
void Seek (bool bPlus=true, bool bLargeStep=false, bool bChapterOverride=false) override
void SeekPercentage (float fPercent=0) override
float GetCachePercentage () const override
void SetMute (bool bOnOff) override
void SeekTime (int64_t iTime=0) override
bool SeekTimeRelative (int64_t iTime) override
void SetSpeed (float speed) override
bool OnAction (const CAction &action) override
std::string GetPlayerState () override
bool SetPlayerState (const std::string &state) override
void FrameMove () override
void Render (bool clear, uint32_t alpha=255, bool gui=true) override
hook into render loop of render thread
bool IsRenderingVideo () const override
bool HasGameAgent () const override
Check if any players are playing a game.
std::string GameClientID () const override
Get the game client being used to play the game.
std::string GetPlayingGame () const override
Get the game that is being played.
std::string CreateSavestate (bool autosave) override
Creates a savestate.
bool UpdateSavestate (const std::string &savestatePath) override
Updates a savestate with the current game being played.
bool LoadSavestate (const std::string &savestatePath) override
Loads a savestate.
void FreeSavestateResources (const std::string &savestatePath) override
Frees resources allocated to the savestate, such as its video thumbnail.
void CloseOSDCallback () override
Closes the OSD.
void SetPlaybackSpeed (double speed) override
Set the playback speed.
void EnableInput (bool bEnable) override
Enable/disable game input.
bool IsAutoSaveEnabled () const override
std::string CreateAutosave () override
Public Member Functions inherited from IPlayer
IPlayer (IPlayerCallback &callback)
virtual ~IPlayer ()=default
virtual bool Initialize (TiXmlElement *pConfig)
virtual bool QueueNextFile (const CFileItem &file)
virtual void OnNothingToQueueNotify ()
virtual bool HasRDS () const
virtual bool HasID3 () const
virtual bool IsPassthrough () const
virtual bool SeekScene (Direction seekDirection)
virtual void SetVolume (float volume)
virtual void SetDynamicRangeCompression (long drc)
virtual void SetAVDelay (float fValue=0.0f)
virtual float GetAVDelay ()
virtual void SetSubTitleDelay (float fValue=0.0f)
virtual float GetSubTitleDelay ()
virtual int GetSubtitleCount () const
virtual int GetSubtitle ()
virtual void GetSubtitleStreamInfo (int index, SubtitleStreamInfo &info) const
virtual void SetSubtitle (int iStream)
virtual bool GetSubtitleVisible () const
virtual void SetSubtitleVisible (bool bVisible)
virtual void SetSubtitleVerticalPosition (int value, bool save)
Set the subtitle vertical position, it depends on current screen resolution.
virtual void AddSubtitle (const std::string &strSubPath)
Adds the subtitle(s) provided by the given file to the available player streams and actives the first of the added stream(s). E.g., vob subs can contain multiple streams.
virtual int GetAudioStreamCount () const
virtual int GetAudioStream ()
virtual void SetAudioStream (int iStream)
virtual void GetAudioStreamInfo (int index, AudioStreamInfo &info) const
virtual int GetVideoStream () const
virtual int GetVideoStreamCount () const
virtual void GetVideoStreamInfo (int streamId, VideoStreamInfo &info) const
virtual void SetVideoStream (int iStream)
virtual int GetPrograms (std::vector< ProgramInfo > &programs)
virtual void SetProgram (int progId)
virtual int GetProgramsCount () const
virtual bool HasTeletextCache () const
virtual std::shared_ptr< TextCacheStruct_t > GetTeletextCache ()
virtual void LoadPage (int p, int sp, unsigned char *buffer)
virtual int GetChapterCount () const
virtual int GetChapter () const
virtual void GetChapterName (std::string &strChapterName, int chapterIdx=-1) const
virtual int64_t GetChapterPos (int chapterIdx=-1) const
virtual int SeekChapter (int iChapter)
virtual void SetTime (int64_t time)
Sets the current time. This can be used for injecting the current time. This is not to be confused with a seek. It just can be used if endless streams contain multiple tracks in reality (like with airtunes)
virtual void SetTotalTime (int64_t time)
Set the total time in milliseconds this can be used for injecting the duration in case its not available in the underlaying decoder (airtunes for example)
virtual void SetTempo (float tempo)
virtual bool SupportsTempo () const
virtual void FrameAdvance (int frames)
virtual bool IsCaching () const
virtual int GetCacheLevel () const
virtual bool IsInMenu () const
virtual MenuType GetSupportedMenuType () const
Get the supported menu type.
virtual void GetAudioCapabilities (std::vector< IPlayerAudioCaps > &caps) const
Define the audio capabilities of the player.
virtual void GetSubtitleCapabilities (std::vector< IPlayerSubtitleCaps > &caps) const
Define the subtitle capabilities of the player.
virtual void FlushRenderer ()
virtual void SetRenderViewMode (int mode, float zoom, float par, float shift, bool stretch)
virtual float GetRenderAspectRatio () const
virtual void TriggerUpdateResolution ()
virtual void GetRects (CRect &source, CRect &dest, CRect &view) const
virtual unsigned int GetOrientation () const
virtual bool Supports (EINTERLACEMETHOD method) const
virtual EINTERLACEMETHOD GetDeinterlacingMethodDefault () const
virtual bool Supports (ESCALINGMETHOD method) const
virtual bool Supports (ERENDERFEATURE feature) const
virtual unsigned int RenderCaptureAlloc ()
virtual void RenderCaptureRelease (unsigned int captureId)
virtual void RenderCapture (unsigned int captureId, unsigned int width, unsigned int height, int flags)
virtual bool RenderCaptureGetPixels (unsigned int captureId, unsigned int millis, uint8_t *buffer, unsigned int size)
virtual CVideoSettings GetVideoSettings () const
virtual void SetVideoSettings (CVideoSettings &settings)
Public Member Functions inherited from IRenderLoop
virtual ~IRenderLoop ()=default
Public Member Functions inherited from KODI::RETRO::IGameCallback
virtual ~IGameCallback ()=default
Public Member Functions inherited from KODI::RETRO::IPlaybackCallback
virtual ~IPlaybackCallback ()=default
Public Member Functions inherited from KODI::RETRO::IAutoSaveCallback
virtual ~IAutoSaveCallback ()=default
Private Member Functions
void SetSpeedInternal (double speed)
void OnSpeedChange (double newSpeed)
Called when the speed changes.
void CreatePlayback (const std::string &savestatePath)
void ResetPlayback ()
void OpenOSD ()
Opens the OSD.
void CloseOSD ()
Closes the OSD and shows the FullscreenGame window.
void RegisterWindowCallbacks ()
void UnregisterWindowCallbacks ()
void PrintGameInfo (const CFileItem &file) const
Dump game information (if any) to the debug log.
uint64_t GetTime ()
uint64_t GetTotalTime ()
Private Attributes
GAME::CGameServices & m_gameServices
std::unique_ptr< CRPProcessInfo > m_processInfo
std::unique_ptr< CGUIGameMessenger > m_guiMessenger
std::unique_ptr< CRPRenderManager > m_renderManager
std::unique_ptr< CRPStreamManager > m_streamManager
std::unique_ptr< CRetroPlayerInput > m_input
std::unique_ptr< IPlayback > m_playback
std::unique_ptr< IPlaybackControl > m_playbackControl
std::unique_ptr< CRetroPlayerAutoSave > m_autoSave
std::shared_ptr< CCheevos > m_cheevos
GAME::GameClientPtr m_gameClient
CCriticalSection m_mutex
Additional Inherited Members
Public Attributes inherited from IPlayer
std::string m_name
std::string m_type
Protected Attributes inherited from IPlayer
IPlayerCallback & m_callback
Constructor & Destructor Documentation
CRetroPlayer()
CRetroPlayer::CRetroPlayer (IPlayerCallback & callback) explicit
References CServiceBroker::GetWinSystem(), CWinSystemBase::RegisterRenderLoop(), and ResetPlayback().
~CRetroPlayer()
CRetroPlayer::~CRetroPlayer () override
References CloseFile(), CServiceBroker::GetWinSystem(), and CWinSystemBase::UnregisterRenderLoop().
Member Function Documentation
CanPause()
bool CRetroPlayer::CanPause () const override virtual
Reimplemented from IPlayer.
References m_playback.
Referenced by Pause().
CanSeek()
bool CRetroPlayer::CanSeek () const override virtual
Reimplemented from IPlayer.
References m_playback.
Referenced by Seek(), SeekPercentage(), SeekTime(), and SeekTimeRelative().
CloseFile()
bool CRetroPlayer::CloseFile (bool reopen = false) override virtual
Implements IPlayer.
References KODI::GAME::CGameSettings::AutosaveEnabled(), KODI::GAME::CGameServices::GameSettings(), CLog::Log(), LOGDEBUG, m_autoSave, IPlayer::m_callback, m_cheevos, m_gameClient, m_gameServices, m_input, m_mutex, m_playback, m_playbackControl, m_processInfo, m_renderManager, m_streamManager, IPlayerCallback::OnPlayBackEnded(), and UnregisterWindowCallbacks().
Referenced by OpenFile(), and ~CRetroPlayer().
CloseOSD()
void CRetroPlayer::CloseOSD () private
Closes the OSD and shows the FullscreenGame window.
References CGUIWindowManager::CloseDialogs(), CServiceBroker::GetGUI(), and CGUIComponent::GetWindowManager().
Referenced by CloseOSDCallback(), OnAction(), and SetSpeed().
CloseOSDCallback()
void CRetroPlayer::CloseOSDCallback () override virtual
Closes the OSD.
Implements KODI::RETRO::IGameCallback.
References CloseOSD().
CreateAutosave()
std::string CRetroPlayer::CreateAutosave () override virtual
Implements KODI::RETRO::IAutoSaveCallback.
References m_playback.
CreatePlayback()
void CRetroPlayer::CreatePlayback (const std::string & savestatePath) private
References CLog::Log(), LOGDEBUG, LOGERROR, m_cheevos, m_gameClient, m_guiMessenger, m_playback, m_renderManager, ResetPlayback(), and SetPlayerState().
Referenced by OpenFile().
CreateSavestate()
std::string CRetroPlayer::CreateSavestate (bool autosave) override virtual
Creates a savestate.
Parameters
autosave Whether the save type is auto
Returns
The path to the created savestate, or empty on error
Implements KODI::RETRO::IGameCallback.
References m_playback.
EnableInput()
void CRetroPlayer::EnableInput (bool bEnable) override virtual
Enable/disable game input.
Parameters
bEnable True to enable input, false to disable input
Implements KODI::RETRO::IPlaybackCallback.
References m_input.
FrameMove()
void CRetroPlayer::FrameMove () override virtual
Implements IRenderLoop.
References GetTime(), GetTotalTime(), m_playbackControl, m_processInfo, and m_renderManager.
FreeSavestateResources()
void CRetroPlayer::FreeSavestateResources (const std::string & savestatePath) override virtual
Frees resources allocated to the savestate, such as its video thumbnail.
Parameters
savestatePath The path to the savestate
Implements KODI::RETRO::IGameCallback.
References m_renderManager.
GameClientID()
std::string CRetroPlayer::GameClientID () const override virtual
Get the game client being used to play the game.
Returns
The game client's ID, or empty if no game is being played
Implements KODI::RETRO::IGameCallback.
References m_gameClient.
GetCachePercentage()
float CRetroPlayer::GetCachePercentage () const override virtual
Reimplemented from IPlayer.
References m_playback.
GetPlayerState()
std::string CRetroPlayer::GetPlayerState () override virtual
Reimplemented from IPlayer.
References CLog::Log(), LOGDEBUG, m_autoSave, and m_playback.
GetPlayingGame()
std::string CRetroPlayer::GetPlayingGame () const override virtual
Get the game that is being played.
Returns
The path to the game, or empty if no game is being played
Implements KODI::RETRO::IGameCallback.
References m_gameClient.
GetTime()
uint64_t CRetroPlayer::GetTime () private
References m_playback.
Referenced by FrameMove(), and SeekTimeRelative().
GetTotalTime()
uint64_t CRetroPlayer::GetTotalTime () private
References m_playback.
Referenced by FrameMove(), and SeekPercentage().
HasAudio()
bool KODI::RETRO::CRetroPlayer::HasAudio () const inline override virtual
Implements IPlayer.
HasGame()
bool KODI::RETRO::CRetroPlayer::HasGame () const inline override virtual
Reimplemented from IPlayer.
HasGameAgent()
bool CRetroPlayer::HasGameAgent () const override virtual
Check if any players are playing a game.
Returns
True if at least one player has an input device attached to the game, false otherwise
Reimplemented from IPlayer.
References m_gameClient.
HasVideo()
bool KODI::RETRO::CRetroPlayer::HasVideo () const inline override virtual
Implements IPlayer.
IsAutoSaveEnabled()
bool CRetroPlayer::IsAutoSaveEnabled () const override virtual
Implements KODI::RETRO::IAutoSaveCallback.
References m_playback.
IsPlaying()
bool CRetroPlayer::IsPlaying () const override virtual
Reimplemented from IPlayer.
References m_gameClient.
Referenced by OpenFile().
IsRenderingVideo()
bool CRetroPlayer::IsRenderingVideo () const override virtual
Reimplemented from IPlayer.
LoadSavestate()
bool CRetroPlayer::LoadSavestate (const std::string & savestatePath) override virtual
Loads a savestate.
Parameters
savestatePath The path to the savestate
Returns
True if the savestate was loaded, false on error
Implements KODI::RETRO::IGameCallback.
References m_playback.
OnAction()
bool CRetroPlayer::OnAction (const CAction & action) override virtual
Reimplemented from IPlayer.
References ACTION_PLAYER_RESET, ACTION_SHOW_OSD, CloseOSD(), CLog::Log(), LOGDEBUG, m_cheevos, m_gameClient, m_playback, and SetSpeed().
OnSpeedChange()
void CRetroPlayer::OnSpeedChange (double newSpeed) private
Called when the speed changes.
Parameters
newSpeed The new speed, possibly equal to the previous speed
References m_input, m_processInfo, m_renderManager, and m_streamManager.
Referenced by SetSpeedInternal().
OpenFile()
bool CRetroPlayer::OpenFile (const CFileItem & file, const CPlayerOptions & options) override virtual
Reimplemented from IPlayer.
References KODI::RETRO::CSavestateDatabase::AllocateSavestate(), ADDON::CHOICE_YES, CloseFile(), KODI::RETRO::CRPProcessInfo::CreateInstance(), CreatePlayback(), KODI::GAME::CGameUtils::FillInGameClient(), g_localizeStrings, ADDON::GAMEDLL, KODI::GAME::CGameServices::GameSettings(), CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetDataCacheCore(), KODI::GAME::CGameInfoTag::GetGameClient(), CFileItem::GetGameInfoTag(), CFileItem::GetPath(), CServiceBroker::GetPeripherals(), KODI::GAME::CGameSettings::GetRAToken(), KODI::GAME::CGameSettings::GetRAUsername(), KODI::RETRO::CSavestateDatabase::GetSavestate(), IsPlaying(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_autoSave, IPlayer::m_callback, m_cheevos, m_gameClient, m_gameServices, m_guiMessenger, m_input, m_mutex, m_playbackControl, m_processInfo, m_renderManager, m_streamManager, IPlayerCallback::OnAVStarted(), IPlayerCallback::OnPlayBackStarted(), PrintGameInfo(), RegisterWindowCallbacks(), CGUIDialogYesNo::ShowAndGetInput(), and TMSG_SWITCHTOFULLSCREEN.
OpenOSD()
void CRetroPlayer::OpenOSD () private
Opens the OSD.
References CGUIWindowManager::ActivateWindow(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and WINDOW_DIALOG_GAME_OSD.
Referenced by SetSpeed().
Pause()
void CRetroPlayer::Pause () override virtual
Implements IPlayer.
References CanPause(), m_playback, and SetSpeed().
PrintGameInfo()
void CRetroPlayer::PrintGameInfo (const CFileItem & file) const private
Dump game information (if any) to the debug log.
References CLog::Log(), and LOGDEBUG.
Referenced by OpenFile().
RegisterWindowCallbacks()
void CRetroPlayer::RegisterWindowCallbacks () private
References KODI::GAME::CGameServices::GameRenderManager(), m_gameServices, m_renderManager, and KODI::RETRO::CGUIGameRenderManager::RegisterPlayer().
Referenced by OpenFile().
Render()
void CRetroPlayer::Render (bool clear, uint32_t alpha = 255, bool gui = true) override virtual
hook into render loop of render thread
Reimplemented from IPlayer.
ResetPlayback()
void CRetroPlayer::ResetPlayback () private
References m_playback.
Referenced by CreatePlayback(), and CRetroPlayer().
Seek()
void CRetroPlayer::Seek (bool bPlus = true, bool bLargeStep = false, bool bChapterOverride = false) override virtual
Todo:
Implements IPlayer.
References CanSeek(), and m_gameClient.
SeekPercentage()
void CRetroPlayer::SeekPercentage (float fPercent = 0) override virtual
Reimplemented from IPlayer.
References CanSeek(), GetTotalTime(), int64_t(), and SeekTime().
SeekTime()
void CRetroPlayer::SeekTime (int64_t iTime = 0) override virtual
Reimplemented from IPlayer.
References CanSeek(), and m_playback.
Referenced by SeekPercentage(), and SeekTimeRelative().
SeekTimeRelative()
bool CRetroPlayer::SeekTimeRelative (int64_t iTime) override virtual
Reimplemented from IPlayer.
References CanSeek(), GetTime(), and SeekTime().
SetMute()
void CRetroPlayer::SetMute (bool bOnOff) override virtual
Reimplemented from IPlayer.
References m_streamManager.
SetPlaybackSpeed()
void CRetroPlayer::SetPlaybackSpeed (double speed) override virtual
Set the playback speed.
Parameters
speed The new speed
Implements KODI::RETRO::IPlaybackCallback.
References CServiceBroker::GetJobManager(), IPlayer::m_callback, m_playback, CJob::PRIORITY_NORMAL, and SetSpeedInternal().
SetPlayerState()
bool CRetroPlayer::SetPlayerState (const std::string & state) override virtual
Reimplemented from IPlayer.
References m_playback.
Referenced by CreatePlayback().
SetSpeed()
void CRetroPlayer::SetSpeed (float speed) override virtual
Implements IPlayer.
References CloseOSD(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CLog::Log(), LOGDEBUG, IPlayer::m_callback, m_playback, IPlayerCallback::OnPlayBackPaused(), IPlayerCallback::OnPlayBackResumed(), OpenOSD(), SetSpeedInternal(), and WINDOW_FULLSCREEN_GAME.
Referenced by OnAction(), and Pause().
SetSpeedInternal()
void CRetroPlayer::SetSpeedInternal (double speed) private
References m_playback, and OnSpeedChange().
Referenced by SetPlaybackSpeed(), and SetSpeed().
UnregisterWindowCallbacks()
void CRetroPlayer::UnregisterWindowCallbacks () private
References KODI::GAME::CGameServices::GameRenderManager(), m_gameServices, and KODI::RETRO::CGUIGameRenderManager::UnregisterPlayer().
Referenced by CloseFile().
UpdateSavestate()
bool CRetroPlayer::UpdateSavestate (const std::string & savestatePath) override virtual
Updates a savestate with the current game being played.
Parameters
savestatePath The path to the savestate
Returns
True if the savestate was updated, false on error
Implements KODI::RETRO::IGameCallback.
References m_playback.
Member Data Documentation
m_autoSave
std::unique_ptr<CRetroPlayerAutoSave> KODI::RETRO::CRetroPlayer::m_autoSave private
Referenced by CloseFile(), GetPlayerState(), and OpenFile().
m_cheevos
std::shared_ptr<CCheevos> KODI::RETRO::CRetroPlayer::m_cheevos private
Referenced by CloseFile(), CreatePlayback(), OnAction(), and OpenFile().
m_gameClient
GAME::GameClientPtr KODI::RETRO::CRetroPlayer::m_gameClient private
Referenced by CloseFile(), CreatePlayback(), GameClientID(), GetPlayingGame(), HasGameAgent(), IsPlaying(), OnAction(), OpenFile(), and Seek().
m_gameServices
GAME::CGameServices& KODI::RETRO::CRetroPlayer::m_gameServices private
Referenced by CloseFile(), OpenFile(), RegisterWindowCallbacks(), and UnregisterWindowCallbacks().
m_guiMessenger
std::unique_ptr<CGUIGameMessenger> KODI::RETRO::CRetroPlayer::m_guiMessenger private
Referenced by CreatePlayback(), and OpenFile().
m_input
std::unique_ptr<CRetroPlayerInput> KODI::RETRO::CRetroPlayer::m_input private
Referenced by CloseFile(), EnableInput(), OnSpeedChange(), and OpenFile().
m_mutex
CCriticalSection KODI::RETRO::CRetroPlayer::m_mutex private
Referenced by CloseFile(), and OpenFile().
m_playback
std::unique_ptr<IPlayback> KODI::RETRO::CRetroPlayer::m_playback private
Referenced by CanPause(), CanSeek(), CloseFile(), CreateAutosave(), CreatePlayback(), CreateSavestate(), GetCachePercentage(), GetPlayerState(), GetTime(), GetTotalTime(), IsAutoSaveEnabled(), LoadSavestate(), OnAction(), Pause(), ResetPlayback(), SeekTime(), SetPlaybackSpeed(), SetPlayerState(), SetSpeed(), SetSpeedInternal(), and UpdateSavestate().
m_playbackControl
std::unique_ptr<IPlaybackControl> KODI::RETRO::CRetroPlayer::m_playbackControl private
Referenced by CloseFile(), FrameMove(), and OpenFile().
m_processInfo
std::unique_ptr<CRPProcessInfo> KODI::RETRO::CRetroPlayer::m_processInfo private
Referenced by CloseFile(), FrameMove(), OnSpeedChange(), and OpenFile().
m_renderManager
std::unique_ptr<CRPRenderManager> KODI::RETRO::CRetroPlayer::m_renderManager private
Referenced by CloseFile(), CreatePlayback(), FrameMove(), FreeSavestateResources(), OnSpeedChange(), OpenFile(), and RegisterWindowCallbacks().
m_streamManager
std::unique_ptr<CRPStreamManager> KODI::RETRO::CRetroPlayer::m_streamManager private
Referenced by CloseFile(), OnSpeedChange(), OpenFile(), and SetMute().
The documentation for this class was generated from the following files:
RetroPlayer.h
RetroPlayer.cpp