Kodi Documentation: jni::CJNIXBMCConnectivityManagerNetworkCallback Class Reference
jni::CJNIXBMCConnectivityManagerNetworkCallback Class Reference abstract
#include <JNIXBMCConnectivityManagerNetworkCallback.h>
Public Member Functions
CJNIXBMCConnectivityManagerNetworkCallback ()
~CJNIXBMCConnectivityManagerNetworkCallback () override
virtual void onAvailable (const CJNINetwork network)=0
virtual void onLost (const CJNINetwork network)=0
Static Public Member Functions
static void RegisterNatives (JNIEnv *env)
Static Protected Member Functions
static void _onAvailable (JNIEnv *env, jobject thiz, jobject network)
static void _onLost (JNIEnv *env, jobject thiz, jobject network)
Constructor & Destructor Documentation
CJNIXBMCConnectivityManagerNetworkCallback()
CJNIXBMCConnectivityManagerNetworkCallback::CJNIXBMCConnectivityManagerNetworkCallback ()
~CJNIXBMCConnectivityManagerNetworkCallback()
CJNIXBMCConnectivityManagerNetworkCallback::~CJNIXBMCConnectivityManagerNetworkCallback () override
Member Function Documentation
_onAvailable()
void CJNIXBMCConnectivityManagerNetworkCallback::_onAvailable (JNIEnv * env, jobject thiz, jobject network) static protected
References onAvailable().
Referenced by RegisterNatives().
_onLost()
void CJNIXBMCConnectivityManagerNetworkCallback::_onLost (JNIEnv * env, jobject thiz, jobject network) static protected
References onLost().
Referenced by RegisterNatives().
onAvailable()
virtual void jni::CJNIXBMCConnectivityManagerNetworkCallback::onAvailable (const CJNINetwork network) pure virtual
Implemented in CNetworkAndroid.
Referenced by _onAvailable().
onLost()
virtual void jni::CJNIXBMCConnectivityManagerNetworkCallback::onLost (const CJNINetwork network) pure virtual
Implemented in CNetworkAndroid.
Referenced by _onLost().
RegisterNatives()
void CJNIXBMCConnectivityManagerNetworkCallback::RegisterNatives (JNIEnv * env) static
References _onAvailable(), and _onLost().
Referenced by JNI_OnLoad().
The documentation for this class was generated from the following files:
JNIXBMCConnectivityManagerNetworkCallback.h
JNIXBMCConnectivityManagerNetworkCallback.cpp