Kodi Documentation: CPasswordManager Class Reference
CPasswordManager Class Reference
Filesystem
Password Manager class for saving authentication details.
#include <PasswordManager.h>
Public Member Functions
bool AuthenticateURL (CURL &url)
Authenticate a URL by looking the URL up in the temporary and permanent caches First looks up based on host and share name. If that fails, it will try a match purely on the host name (eg different shares on the same host with the same credentials)
bool PromptToAuthenticateURL (CURL &url)
Prompt for a username and password for the particular URL.
void SaveAuthenticatedURL (const CURL &url, bool saveToProfile=true)
Save an authenticated URL.
bool IsURLSupported (const CURL &url)
Is an URL is supported (by the manager)
void Clear ()
Clear any previously cached passwords.
Static Public Member Functions
static CPasswordManager & GetInstance ()
The only way through which the global instance of the CPasswordManager should be accessed.
Private Member Functions
CPasswordManager ()
CPasswordManager (const CPasswordManager &)=delete
CPasswordManager & operator= (CPasswordManager const &)=delete
~CPasswordManager ()=default
void Load ()
void Save () const
std::string GetLookupPath (const CURL &url) const
std::string GetServerLookup (const std::string &path) const
Private Attributes
std::map< std::string, std::string > m_temporaryCache
std::map< std::string, std::string > m_permanentCache
bool m_loaded
CCriticalSection m_critSection
Detailed Description
Password Manager class for saving authentication details.
Handles access to previously saved passwords for paths, translating normal URLs into authenticated URLs if the user has details about the username and password for a path previously saved. Should be accessed via CPasswordManager::GetInstance()
Constructor & Destructor Documentation
CPasswordManager() [1/2]
CPasswordManager::CPasswordManager () private
References m_loaded.
CPasswordManager() [2/2]
CPasswordManager::CPasswordManager (const CPasswordManager &) private delete
~CPasswordManager()
CPasswordManager::~CPasswordManager () private default
Member Function Documentation
AuthenticateURL()
bool CPasswordManager::AuthenticateURL (CURL & url)
Authenticate a URL by looking the URL up in the temporary and permanent caches First looks up based on host and share name. If that fails, it will try a match purely on the host name (eg different shares on the same host with the same credentials)
Parameters
url a CURL to authenticate
Returns
true if we have details in the cache, false otherwise.
See also
CURL
References CURL::GetDomain(), GetLookupPath(), CURL::GetPassWord(), GetServerLookup(), CURL::GetUserName(), Load(), m_critSection, m_loaded, m_temporaryCache, CURL::SetDomain(), CURL::SetPassword(), and CURL::SetUserName().
Referenced by XFILE::CWin32SMBDirectory::ConnectAndAuthenticate(), XFILE::CDirectory::Create(), XFILE::CSMBDirectory::Create(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), XFILE::CSMBDirectory::Exists(), XFILE::CDirectory::Exists(), XFILE::CSMBFile::GetAuthenticatedPath(), XFILE::CDirectory::GetDirectory(), XFILE::CFile::Open(), XFILE::CFileStream::Open(), NPT_XbmcFile::Open(), XFILE::CSMBDirectory::OpenDir(), XFILE::CFile::OpenForWrite(), XFILE::CDirectory::Remove(), XFILE::CSMBDirectory::Remove(), XFILE::CDirectory::RemoveRecursive(), XFILE::CFile::Rename(), XFILE::CFile::SetHidden(), and XFILE::CFile::Stat().
Clear()
void CPasswordManager::Clear ()
Clear any previously cached passwords.
References m_loaded, m_permanentCache, and m_temporaryCache.
Referenced by Load(), and CProfileManager::LoadProfile().
GetInstance()
CPasswordManager & CPasswordManager::GetInstance () static
The only way through which the global instance of the CPasswordManager should be accessed.
Returns
the global instance.
Referenced by XFILE::CWin32SMBDirectory::ConnectAndAuthenticate(), XFILE::CDirectory::Create(), XFILE::CSMBDirectory::Create(), XFILE::CFile::Delete(), XFILE::CFile::Exists(), XFILE::CSMBDirectory::Exists(), XFILE::CDirectory::Exists(), XFILE::CSMBFile::GetAuthenticatedPath(), XFILE::CDirectory::GetDirectory(), CGUIDialogMediaSource::GetPaths(), CProfileManager::LoadProfile(), XFILE::CFile::Open(), XFILE::CFileStream::Open(), NPT_XbmcFile::Open(), XFILE::CSMBDirectory::OpenDir(), XFILE::CFile::OpenForWrite(), XFILE::IDirectory::ProcessRequirements(), XFILE::CDirectory::Remove(), XFILE::CSMBDirectory::Remove(), XFILE::CDirectory::RemoveRecursive(), XFILE::CFile::Rename(), XFILE::CFile::SetHidden(), and XFILE::CFile::Stat().
GetLookupPath()
std::string CPasswordManager::GetLookupPath (const CURL & url) const private
References CURL::Get(), CURL::GetHostName(), CURL::GetProtocol(), GetServerLookup(), CURL::GetShareName(), and CURL::IsProtocol().
Referenced by AuthenticateURL(), and SaveAuthenticatedURL().
GetServerLookup()
std::string CPasswordManager::GetServerLookup (const std::string & path) const private
References CURL::GetHostName(), and CURL::GetProtocol().
Referenced by AuthenticateURL(), GetLookupPath(), Load(), and SaveAuthenticatedURL().
IsURLSupported()
bool CPasswordManager::IsURLSupported (const CURL & url)
Is an URL is supported (by the manager)
This routine checks that an URL is supported by the manager
Parameters
url the URL to check.
Returns
true if the URL is supported
See also
CURL, IsURLSupported
References CURL::IsProtocol().
Load()
void CPasswordManager::Load () private
References Clear(), CFileUtils::Exists(), XMLUtils::GetPath(), GetServerLookup(), CServiceBroker::GetSettingsComponent(), CXBMCTinyXML2::LoadFile(), LOGERROR, m_loaded, m_permanentCache, m_temporaryCache, and root.
Referenced by AuthenticateURL(), and SaveAuthenticatedURL().
operator=()
CPasswordManager & CPasswordManager::operator= (CPasswordManager const &) private delete
PromptToAuthenticateURL()
bool CPasswordManager::PromptToAuthenticateURL (CURL & url)
Prompt for a username and password for the particular URL.
This routine pops up a dialog, requesting the user enter a username and password to access the given URL. The user may optionally save these details. If saved we write the details into the users profile. If not saved, the details are temporarily stored so that further access no longer requires prompting for authentication.
Parameters
url the URL to authenticate.
Returns
true if the user entered details, false if the user cancelled the dialog.
See also
CURL, SaveAuthenticatedURL
References CURL::GetDomain(), CURL::GetUserName(), CURL::GetWithoutUserDetails(), CURL::IsProtocol(), m_critSection, name, SaveAuthenticatedURL(), CURL::SetDomain(), CURL::SetPassword(), CURL::SetUserName(), and CGUIDialogLockSettings::ShowAndGetUserAndPassword().
Save()
void CPasswordManager::Save () const private
References CServiceBroker::GetSettingsComponent(), m_permanentCache, root, CXBMCTinyXML2::SaveFile(), and XMLUtils::SetPath().
Referenced by SaveAuthenticatedURL().
SaveAuthenticatedURL()
void CPasswordManager::SaveAuthenticatedURL (const CURL & url, bool saveToProfile = true)
Save an authenticated URL.
This routine stores an authenticated URL in the temporary cache, and optionally saves these details into the users profile.
Parameters
url the URL to authenticate.
saveToProfile whether to save in the users profile, defaults to true.
See also
CURL, PromptToAuthenticateURL
References CURL::Get(), GetLookupPath(), GetServerLookup(), CURL::GetUserName(), Load(), m_critSection, m_loaded, m_permanentCache, m_temporaryCache, and Save().
Referenced by CGUIDialogMediaSource::GetPaths(), and PromptToAuthenticateURL().
Member Data Documentation
m_critSection
CCriticalSection CPasswordManager::m_critSection private
Referenced by AuthenticateURL(), PromptToAuthenticateURL(), and SaveAuthenticatedURL().
m_loaded
bool CPasswordManager::m_loaded private
Referenced by AuthenticateURL(), Clear(), CPasswordManager(), Load(), and SaveAuthenticatedURL().
m_permanentCache
std::map<std::string, std::string> CPasswordManager::m_permanentCache private
Referenced by Clear(), Load(), Save(), and SaveAuthenticatedURL().
m_temporaryCache
std::map<std::string, std::string> CPasswordManager::m_temporaryCache private
Referenced by AuthenticateURL(), Clear(), Load(), and SaveAuthenticatedURL().
The documentation for this class was generated from the following files:
PasswordManager.h
PasswordManager.cpp