Kodi Documentation: PVR::CPVRTimers Class Reference
PVR::CPVRTimers Class Reference
#include <PVRTimers.h>
Public Member Functions
CPVRTimers ()
~CPVRTimers () override=default
void Start ()
start the timer update thread.
void Stop ()
stop the timer update thread.
bool Update (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Update all timers from PVR database and from given clients.
void Unload ()
unload all timers.
bool UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Update data with recordings from the given clients, sync with local data.
std::shared_ptr< CPVRTimerInfoTag > GetNextActiveTimer (bool bIgnoreReminders=true) const
std::shared_ptr< CPVRTimerInfoTag > GetNextActiveTVTimer () const
std::shared_ptr< CPVRTimerInfoTag > GetNextActiveRadioTimer () const
std::vector< std::shared_ptr< CPVRTimerInfoTag > > GetActiveTimers () const
std::shared_ptr< CPVRTimerInfoTag > GetNextReminderToAnnnounce ()
std::vector< std::shared_ptr< CPVRTimerInfoTag > > GetAll () const
int AmountActiveTimers () const
int AmountActiveTVTimers () const
int AmountActiveRadioTimers () const
std::vector< std::shared_ptr< CPVRTimerInfoTag > > GetActiveRecordings () const
std::vector< std::shared_ptr< CPVRTimerInfoTag > > GetActiveTVRecordings () const
std::vector< std::shared_ptr< CPVRTimerInfoTag > > GetActiveRadioRecordings () const
bool IsRecording () const
bool IsRecordingOnChannel (const CPVRChannel &channel) const
Check if a recording is running on the given channel.
std::shared_ptr< CPVRTimerInfoTag > GetActiveTimerForChannel (const std::shared_ptr< const CPVRChannel > &channel) const
Obtain the active timer for a given channel.
int AmountActiveRecordings () const
int AmountActiveTVRecordings () const
int AmountActiveRadioRecordings () const
bool DeleteTimersOnChannel (const std::shared_ptr< CPVRChannel > &channel, bool bDeleteTimerRules=true, bool bCurrentlyActiveOnly=false)
Delete all timers on a channel.
CDateTime GetNextEventTime () const
bool AddTimer (const std::shared_ptr< CPVRTimerInfoTag > &tag)
Add a timer to the client. Doesn't add the timer to the container. The backend will do this.
TimerOperationResult DeleteTimer (const std::shared_ptr< CPVRTimerInfoTag > &tag, bool bForce=false, bool bDeleteRule=false)
Delete a timer on the client. Doesn't delete the timer from the container. The backend will do this.
bool UpdateTimer (const std::shared_ptr< CPVRTimerInfoTag > &tag)
Update the timer on the client. Doesn't update the timer in the container. The backend will do this.
std::shared_ptr< CPVRTimerInfoTag > GetTimerForEpgTag (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
Get the timer tag that matches the given epg tag.
std::shared_ptr< CPVRTimerInfoTag > GetTimerRule (const std::shared_ptr< const CPVRTimerInfoTag > &timer) const
Get the timer rule for a given timer tag.
void UpdateChannels ()
Update the channel pointers.
void Notify (const PVREvent &event)
CEventStream callback for PVR events.
std::shared_ptr< CPVRTimerInfoTag > GetById (unsigned int iTimerId) const
Get a timer tag given it's unique ID.
Public Member Functions inherited from PVR::CPVRTimersContainer
bool UpdateFromClient (const std::shared_ptr< CPVRTimerInfoTag > &timer)
Add a timer tag to this container or update the tag if already present in this container.
std::shared_ptr< CPVRTimerInfoTag > GetByClient (int iClientId, int iClientIndex) const
Get the timer tag denoted by given client id and timer id.
const MapTags & GetTags () const
Get the timertags map.
Private Types
enum TimerKind { TimerKindAny = 0 , TimerKindTV , TimerKindRadio }
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions
void Process () override
bool LoadFromDatabase (const std::vector< std::shared_ptr< CPVRClient > > &clients)
Load all timers from PVR database.
void RemoveEntry (const std::shared_ptr< const CPVRTimerInfoTag > &tag)
bool UpdateEntries (const CPVRTimersContainer &timers, const std::vector< int > &failedClients)
bool UpdateEntries (int iMaxNotificationDelay)
std::shared_ptr< CPVRTimerInfoTag > UpdateEntry (const std::shared_ptr< const CPVRTimerInfoTag > &timer)
bool AddLocalTimer (const std::shared_ptr< CPVRTimerInfoTag > &tag, bool bNotify)
bool DeleteLocalTimer (const std::shared_ptr< CPVRTimerInfoTag > &tag, bool bNotify)
bool UpdateLocalTimer (const std::shared_ptr< CPVRTimerInfoTag > &tag)
std::shared_ptr< CPVRTimerInfoTag > PersistAndUpdateLocalTimer (const std::shared_ptr< CPVRTimerInfoTag > &timer, const std::shared_ptr< CPVRTimerInfoTag > &parentTimer)
void NotifyTimersEvent (bool bAddedOrDeleted=true)
bool KindMatchesTag (const TimerKind &eKind, const std::shared_ptr< const CPVRTimerInfoTag > &tag) const
std::shared_ptr< CPVRTimerInfoTag > GetNextActiveTimer (const TimerKind &eKind, bool bIgnoreReminders) const
int AmountActiveTimers (const TimerKind &eKind) const
std::vector< std::shared_ptr< CPVRTimerInfoTag > > GetActiveRecordings (const TimerKind &eKind) const
int AmountActiveRecordings (const TimerKind &eKind) const
bool CheckAndAppendTimerNotification (std::vector< std::pair< int, std::string > > &timerNotifications, const std::shared_ptr< const CPVRTimerInfoTag > &tag, bool bDeleted) const
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Attributes
bool m_bIsUpdating = false
CPVRSettings m_settings
std::queue< std::shared_ptr< CPVRTimerInfoTag > > m_remindersToAnnounce
bool m_bReminderRulesUpdatePending = false
bool m_bFirstUpdate = true
std::vector< int > m_failedClients
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Public Types inherited from PVR::CPVRTimersContainer
typedef std::vector< std::shared_ptr< CPVRTimerInfoTag > > VecTimerInfoTag
typedef std::map< CDateTime, VecTimerInfoTag > MapTags
Protected Member Functions inherited from PVR::CPVRTimersContainer
void InsertEntry (const std::shared_ptr< CPVRTimerInfoTag > &newTimer)
Protected Attributes inherited from PVR::CPVRTimersContainer
CCriticalSection m_critSection
unsigned int m_iLastId = 0
MapTags m_tags
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Member Enumeration Documentation
TimerKind
enum PVR::CPVRTimers::TimerKind private
Enumerator
TimerKindAny
TimerKindTV
TimerKindRadio
Constructor & Destructor Documentation
CPVRTimers()
CPVRTimers::CPVRTimers ()
References CSettings::SETTING_PVRPOWERMANAGEMENT_BACKENDIDLETIME, CSettings::SETTING_PVRPOWERMANAGEMENT_DAILYWAKEUP, CSettings::SETTING_PVRPOWERMANAGEMENT_DAILYWAKEUPTIME, CSettings::SETTING_PVRPOWERMANAGEMENT_PREWAKEUP, and CSettings::SETTING_PVRRECORD_TIMERNOTIFICATIONS.
~CPVRTimers()
PVR::CPVRTimers::~CPVRTimers () override default
Member Function Documentation
AddLocalTimer()
bool CPVRTimers::AddLocalTimer (const std::shared_ptr< CPVRTimerInfoTag > & tag, bool bNotify) private
References PVR::CPVRTimerInfoTag::CreateReminderFromDate(), PVR::CPVRTimerInfoTag::CreateReminderFromEpg(), PVR::CPVRTimerRuleMatcher::GetNextTimerStart(), CDateTimeSpan::GetSecondsTotal(), CDateTime::GetUTCDateTime(), CDateTime::IsValid(), PVR::CPVRTimersContainer::m_critSection, NotifyTimersEvent(), and PersistAndUpdateLocalTimer().
Referenced by AddTimer(), and UpdateLocalTimer().
AddTimer()
bool CPVRTimers::AddTimer (const std::shared_ptr< CPVRTimerInfoTag > & tag)
Add a timer to the client. Doesn't add the timer to the container. The backend will do this.
Parameters
tag The timer to add.
Returns
True if timer add request was sent correctly, false if not.
References AddLocalTimer().
AmountActiveRadioRecordings()
int CPVRTimers::AmountActiveRadioRecordings () const
Returns
The amount of radio timers that are currently recording
References AmountActiveRecordings(), and TimerKindRadio.
AmountActiveRadioTimers()
int CPVRTimers::AmountActiveRadioTimers () const
Returns
The amount of radio timers that are active (states scheduled or recording)
References AmountActiveTimers(), and TimerKindRadio.
AmountActiveRecordings() [1/2]
int CPVRTimers::AmountActiveRecordings () const
Returns
The amount of tv and radio timers that are currently recording
References AmountActiveRecordings(), and TimerKindAny.
Referenced by AmountActiveRadioRecordings(), AmountActiveRecordings(), and AmountActiveTVRecordings().
AmountActiveRecordings() [2/2]
int CPVRTimers::AmountActiveRecordings (const TimerKind & eKind) const private
References PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
AmountActiveTimers() [1/2]
int CPVRTimers::AmountActiveTimers () const
Returns
The amount of tv and radio timers that are active (states scheduled or recording)
References AmountActiveTimers(), and TimerKindAny.
Referenced by AmountActiveRadioTimers(), AmountActiveTimers(), and AmountActiveTVTimers().
AmountActiveTimers() [2/2]
int CPVRTimers::AmountActiveTimers (const TimerKind & eKind) const private
References PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
AmountActiveTVRecordings()
int CPVRTimers::AmountActiveTVRecordings () const
Returns
The amount of tv timers that are currently recording
References AmountActiveRecordings(), and TimerKindTV.
AmountActiveTVTimers()
int CPVRTimers::AmountActiveTVTimers () const
Returns
The amount of tv timers that are active (states scheduled or recording)
References AmountActiveTimers(), and TimerKindTV.
CheckAndAppendTimerNotification()
bool CPVRTimers::CheckAndAppendTimerNotification (std::vector< std::pair< int, std::string > > & timerNotifications, const std::shared_ptr< const CPVRTimerInfoTag > & tag, bool bDeleted) const private
References m_bFirstUpdate, and m_failedClients.
Referenced by UpdateEntries().
DeleteLocalTimer()
bool CPVRTimers::DeleteLocalTimer (const std::shared_ptr< CPVRTimerInfoTag > & tag, bool bNotify) private
References PVR::CPVRTimersContainer::m_critSection, PVR::CPVRTimersContainer::m_tags, NotifyTimersEvent(), and RemoveEntry().
Referenced by DeleteTimer(), and UpdateLocalTimer().
DeleteTimer()
TimerOperationResult CPVRTimers::DeleteTimer (const std::shared_ptr< CPVRTimerInfoTag > & tag, bool bForce = false, bool bDeleteRule = false)
Delete a timer on the client. Doesn't delete the timer from the container. The backend will do this.
Parameters
tag The timer to delete.
bForce Control what to do in case the timer is currently recording. True to force to delete the timer, false to return TimerDeleteResult::RECORDING.
bDeleteRule Also delete the timer rule that scheduled the timer instead of single timer only.
Returns
The result.
References DeleteLocalTimer(), PVR::FAILED, GetTimerRule(), LOGERROR, and PVR::OK.
DeleteTimersOnChannel()
bool CPVRTimers::DeleteTimersOnChannel (const std::shared_ptr< CPVRChannel > & channel, bool bDeleteTimerRules = true, bool bCurrentlyActiveOnly = false)
Delete all timers on a channel.
Parameters
channel The channel to delete the timers for.
bDeleteTimerRules True to delete timer rules too, false otherwise.
bCurrentlyActiveOnly True to delete timers that are currently running only.
Returns
True if timers any were deleted, false otherwise.
References LOGDEBUG, LOGPVR, PVR::CPVRTimersContainer::m_critSection, PVR::CPVRTimersContainer::m_tags, NotifyTimersEvent(), and PVR::OK.
GetActiveRadioRecordings()
std::vector< std::shared_ptr< CPVRTimerInfoTag > > CPVRTimers::GetActiveRadioRecordings () const
Returns
All radio timers that are recording
References GetActiveRecordings(), and TimerKindRadio.
GetActiveRecordings() [1/2]
std::vector< std::shared_ptr< CPVRTimerInfoTag > > CPVRTimers::GetActiveRecordings () const
Returns
All tv and radio timers that are recording
References GetActiveRecordings(), and TimerKindAny.
Referenced by GetActiveRadioRecordings(), GetActiveRecordings(), and GetActiveTVRecordings().
GetActiveRecordings() [2/2]
std::vector< std::shared_ptr< CPVRTimerInfoTag > > CPVRTimers::GetActiveRecordings (const TimerKind & eKind) const private
References PVR::CPVRTimersContainer::m_critSection, PVR::CPVRTimersContainer::m_tags, and tags.
GetActiveTimerForChannel()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::GetActiveTimerForChannel (const std::shared_ptr< const CPVRChannel > & channel) const
Obtain the active timer for a given channel.
Parameters
channel The channel to check.
Returns
the timer, null otherwise.
References PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
GetActiveTimers()
std::vector< std::shared_ptr< CPVRTimerInfoTag > > CPVRTimers::GetActiveTimers () const
Returns
All timers that are active (states scheduled or recording)
References PVR::CPVRTimersContainer::m_critSection, PVR::CPVRTimersContainer::m_tags, and tags.
GetActiveTVRecordings()
std::vector< std::shared_ptr< CPVRTimerInfoTag > > CPVRTimers::GetActiveTVRecordings () const
Returns
All tv timers that are recording
References GetActiveRecordings(), and TimerKindTV.
GetAll()
std::vector< std::shared_ptr< CPVRTimerInfoTag > > CPVRTimers::GetAll () const
Get all timers
Returns
The list of all timers
References PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
GetById()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::GetById (unsigned int iTimerId) const
Get a timer tag given it's unique ID.
Parameters
iTimerId The ID to find
Returns
The tag, or an empty one when not found
References PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
GetNextActiveRadioTimer()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::GetNextActiveRadioTimer () const
Returns
The radio timer that will be active next (state scheduled), or nullptr if none.
References GetNextActiveTimer(), and TimerKindRadio.
GetNextActiveTimer() [1/2]
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::GetNextActiveTimer (bool bIgnoreReminders = true) const
Parameters
bIgnoreReminders include or ignore reminders
Returns
The tv or radio timer that will be active next (state scheduled), or nullptr if none.
References GetNextActiveTimer(), and TimerKindAny.
Referenced by GetNextActiveRadioTimer(), GetNextActiveTimer(), GetNextActiveTVTimer(), and GetNextEventTime().
GetNextActiveTimer() [2/2]
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::GetNextActiveTimer (const TimerKind & eKind, bool bIgnoreReminders) const private
References KindMatchesTag(), PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
GetNextActiveTVTimer()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::GetNextActiveTVTimer () const
Returns
The tv timer that will be active next (state scheduled), or nullptr if none.
References GetNextActiveTimer(), and TimerKindTV.
GetNextEventTime()
CDateTime CPVRTimers::GetNextEventTime () const
Returns
Next event time (timer or daily wake up)
References CDateTime::GetAsUTCDateTime(), PVR::CPVRSettings::GetBoolValue(), CDateTime::GetDay(), CDateTime::GetHour(), PVR::CPVRSettings::GetIntValue(), CDateTime::GetMinute(), CDateTime::GetMonth(), GetNextActiveTimer(), CDateTime::GetSecond(), PVR::CPVRSettings::GetStringValue(), CDateTime::GetUTCDateTime(), CDateTime::GetYear(), CDateTime::IsValid(), m_settings, CDateTime::SetDateTime(), CDateTime::SetFromDBTime(), CSettings::SETTING_PVRPOWERMANAGEMENT_BACKENDIDLETIME, CSettings::SETTING_PVRPOWERMANAGEMENT_DAILYWAKEUP, CSettings::SETTING_PVRPOWERMANAGEMENT_DAILYWAKEUPTIME, and CSettings::SETTING_PVRPOWERMANAGEMENT_PREWAKEUP.
GetNextReminderToAnnnounce()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::GetNextReminderToAnnnounce ()
Returns
Next due reminder, if any. Removes it from the queue of due reminders.
References PVR::CPVRTimersContainer::m_critSection, and m_remindersToAnnounce.
GetTimerForEpgTag()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::GetTimerForEpgTag (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const
Get the timer tag that matches the given epg tag.
Parameters
epgTag The epg tag.
Returns
The requested timer tag, or nullptr if none was found.
References EPG_TAG_INVALID_UID, PVR::CPVRTimersContainer::m_critSection, PVR::CPVRTimersContainer::m_tags, and PVR_CHANNEL_INVALID_UID.
Referenced by UpdateEntries().
GetTimerRule()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::GetTimerRule (const std::shared_ptr< const CPVRTimerInfoTag > & timer) const
Get the timer rule for a given timer tag.
Parameters
timer The timer to query the timer rule for
Returns
The timer rule, or nullptr if none was found.
References PVR::CPVRTimersContainer::m_critSection, PVR::CPVRTimersContainer::m_tags, and PVR_TIMER_NO_PARENT.
Referenced by DeleteTimer(), UpdateEntries(), and UpdateEntries().
IsRecording()
bool CPVRTimers::IsRecording () const
Returns
True when recording, false otherwise.
References PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
IsRecordingOnChannel()
bool CPVRTimers::IsRecordingOnChannel (const CPVRChannel & channel) const
Check if a recording is running on the given channel.
Parameters
channel The channel to check.
Returns
True when recording, false otherwise.
References PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
KindMatchesTag()
bool CPVRTimers::KindMatchesTag (const TimerKind & eKind, const std::shared_ptr< const CPVRTimerInfoTag > & tag) const private
References TimerKindAny, TimerKindRadio, and TimerKindTV.
Referenced by GetNextActiveTimer().
LoadFromDatabase()
bool CPVRTimers::LoadFromDatabase (const std::vector< std::shared_ptr< CPVRClient > > & clients) private
Load all timers from PVR database.
Parameters
clients The PVR clients data should be loaded for. Leave empty for all clients.
Returns
True on success, false otherwise.
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::GetTVDatabase(), NotifyTimersEvent(), and UpdateChannels().
Referenced by Update().
Notify()
void CPVRTimers::Notify (const PVREvent & event)
CEventStream callback for PVR events.
Parameters
event The event.
References PVR::Epg, PVR::EpgContainer, PVR::EpgItemUpdate, CServiceBroker::GetPVRManager(), m_bReminderRulesUpdatePending, PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRManager::TriggerTimersUpdate().
Referenced by Start().
NotifyTimersEvent()
void CPVRTimers::NotifyTimersEvent (bool bAddedOrDeleted = true) private
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::PublishEvent(), PVR::Timers, and PVR::TimersInvalidated.
Referenced by AddLocalTimer(), DeleteLocalTimer(), DeleteTimersOnChannel(), LoadFromDatabase(), UpdateEntries(), UpdateEntries(), and UpdateLocalTimer().
PersistAndUpdateLocalTimer()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::PersistAndUpdateLocalTimer (const std::shared_ptr< CPVRTimerInfoTag > & timer, const std::shared_ptr< CPVRTimerInfoTag > & parentTimer) private
References UpdateEntry().
Referenced by AddLocalTimer(), and UpdateEntries().
Process()
void CPVRTimers::Process (void) override private virtual
Reimplemented from CThread.
References CThread::m_bStop, CThread::Sleep(), and UpdateEntries().
RemoveEntry()
void CPVRTimers::RemoveEntry (const std::shared_ptr< const CPVRTimerInfoTag > & tag) private
References PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
Referenced by DeleteLocalTimer(), and UpdateEntry().
Start()
void CPVRTimers::Start ()
start the timer update thread.
References CThread::Create(), PVR::CPVRManager::Events(), CServiceBroker::GetPVRManager(), Notify(), Stop(), and CEventStream< Event >::Subscribe().
Stop()
void CPVRTimers::Stop ()
stop the timer update thread.
References PVR::CPVRManager::Events(), CServiceBroker::GetPVRManager(), CThread::StopThread(), and CEventStream< Event >::Unsubscribe().
Referenced by Start().
Unload()
void CPVRTimers::Unload ()
unload all timers.
References PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
Update()
bool CPVRTimers::Update (const std::vector< std::shared_ptr< CPVRClient > > & clients)
Update all timers from PVR database and from given clients.
Parameters
clients The PVR clients data should be loaded for. Leave empty for all clients.
Returns
True on success, false otherwise.
References LoadFromDatabase(), and UpdateFromClients().
UpdateChannels()
void CPVRTimers::UpdateChannels ()
Update the channel pointers.
References PVR::CPVRTimersContainer::m_critSection, and PVR::CPVRTimersContainer::m_tags.
Referenced by LoadFromDatabase(), and UpdateEntries().
UpdateEntries() [1/2]
bool CPVRTimers::UpdateEntries (const CPVRTimersContainer & timers, const std::vector< int > & failedClients) private
References PVR::CPVREventLogJob::AddEvent(), CheckAndAppendTimerNotification(), PVR::CPVRSettings::GetBoolValue(), PVR::CPVRTimersContainer::GetByClient(), PVR::CPVRManager::GetClient(), CServiceBroker::GetJobManager(), CServiceBroker::GetPVRManager(), PVR::CPVRTimersContainer::GetTags(), GetTimerRule(), Information, PVR::CPVRTimersContainer::InsertEntry(), LOGDEBUG, LOGPVR, m_bFirstUpdate, m_bIsUpdating, PVR::CPVRTimersContainer::m_critSection, m_failedClients, PVR::CPVRTimersContainer::m_iLastId, m_settings, PVR::CPVRTimersContainer::m_tags, NotifyTimersEvent(), CSettings::SETTING_PVRRECORD_TIMERNOTIFICATIONS, and UpdateChannels().
Referenced by Process(), and UpdateFromClients().
UpdateEntries() [2/2]
bool CPVRTimers::UpdateEntries (int iMaxNotificationDelay) private
References PVR::AnnounceReminder, PVR::CPVRTimerInfoTag::CreateReminderFromDate(), PVR::CPVRTimerInfoTag::CreateReminderFromEpg(), PVR::CPVRManager::EpgContainer(), PVR::CPVREpgContainer::GetByChannelUid(), PVR::CPVRTimerRuleMatcher::GetNextTimerStart(), CServiceBroker::GetPVRManager(), CDateTimeSpan::GetSecondsTotal(), GetTimerForEpgTag(), GetTimerRule(), CDateTime::GetUTCDateTime(), PVR::CPVRTimersContainer::InsertEntry(), CDateTime::IsValid(), m_bReminderRulesUpdatePending, PVR::CPVRTimersContainer::m_critSection, m_remindersToAnnounce, PVR::CPVRTimersContainer::m_tags, NotifyTimersEvent(), PersistAndUpdateLocalTimer(), PVR::CPVRManager::PublishEvent(), and PVR_TIMER_STATE_DISABLED.
UpdateEntry()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimers::UpdateEntry (const std::shared_ptr< const CPVRTimerInfoTag > & timer) private
References PVR::CPVRTimersContainer::GetByClient(), PVR::CPVRTimersContainer::InsertEntry(), PVR::CPVRTimersContainer::m_critSection, PVR::CPVRTimersContainer::m_iLastId, and RemoveEntry().
Referenced by PersistAndUpdateLocalTimer().
UpdateFromClients()
bool CPVRTimers::UpdateFromClients (const std::vector< std::shared_ptr< CPVRClient > > & clients)
Update data with recordings from the given clients, sync with local data.
Parameters
clients The clients to fetch data from. Leave empty to fetch data from all created clients.
Returns
True on success, false otherwise.
References PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), LOGDEBUG, LOGPVR, m_bIsUpdating, PVR::CPVRTimersContainer::m_critSection, and UpdateEntries().
Referenced by Update().
UpdateLocalTimer()
bool CPVRTimers::UpdateLocalTimer (const std::shared_ptr< CPVRTimerInfoTag > & tag) private
References AddLocalTimer(), DeleteLocalTimer(), and NotifyTimersEvent().
Referenced by UpdateTimer().
UpdateTimer()
bool CPVRTimers::UpdateTimer (const std::shared_ptr< CPVRTimerInfoTag > & tag)
Update the timer on the client. Doesn't update the timer in the container. The backend will do this.
Parameters
tag The timer to update.
Returns
True if timer update request was sent correctly, false if not.
References UpdateLocalTimer().
Member Data Documentation
m_bFirstUpdate
bool PVR::CPVRTimers::m_bFirstUpdate = true private
Referenced by CheckAndAppendTimerNotification(), and UpdateEntries().
m_bIsUpdating
bool PVR::CPVRTimers::m_bIsUpdating = false private
Referenced by UpdateEntries(), and UpdateFromClients().
m_bReminderRulesUpdatePending
bool PVR::CPVRTimers::m_bReminderRulesUpdatePending = false private
Referenced by Notify(), and UpdateEntries().
m_failedClients
std::vector<int> PVR::CPVRTimers::m_failedClients private
Referenced by CheckAndAppendTimerNotification(), and UpdateEntries().
m_remindersToAnnounce
std::queue<std::shared_ptr<CPVRTimerInfoTag> > PVR::CPVRTimers::m_remindersToAnnounce private
Referenced by GetNextReminderToAnnnounce(), and UpdateEntries().
m_settings
CPVRSettings PVR::CPVRTimers::m_settings private
Referenced by GetNextEventTime(), and UpdateEntries().
The documentation for this class was generated from the following files:
PVRTimers.h
PVRTimers.cpp