Kodi Documentation: CDisplaySettings Class Reference
CDisplaySettings Class Reference
#include <DisplaySettings.h>
Public Member Functions
bool Load (const TiXmlNode *settings) override
Load settings from the given XML node.
bool Save (TiXmlNode *settings) const override
Save settings to the given XML node.
void Clear () override
Clear any loaded setting values.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting is being changed.
bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode) override
The given setting needs to be updated.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
RESOLUTION GetCurrentResolution () const
Returns the currently active resolution.
void SetCurrentResolution (RESOLUTION resolution, bool save=false)
RESOLUTION GetDisplayResolution () const
Returns the best-matching resolution of the videoscreen.screenmode setting value.
const RESOLUTION_INFO & GetResolutionInfo (size_t index) const
const RESOLUTION_INFO & GetResolutionInfo (RESOLUTION resolution) const
RESOLUTION_INFO & GetResolutionInfo (size_t index)
RESOLUTION_INFO & GetResolutionInfo (RESOLUTION resolution)
size_t ResolutionInfoSize () const
void AddResolutionInfo (const RESOLUTION_INFO &resolution)
const RESOLUTION_INFO & GetCurrentResolutionInfo () const
RESOLUTION_INFO & GetCurrentResolutionInfo ()
RESOLUTION GetResFromString (const std::string &strResolution)
std::string GetStringFromRes (const RESOLUTION resolution, float refreshrate=0.0f)
void ApplyCalibrations ()
void UpdateCalibrations ()
void ClearCalibrations ()
void ClearCustomResolutions ()
float GetZoomAmount () const
void SetZoomAmount (float zoomAmount)
float GetPixelRatio () const
void SetPixelRatio (float pixelRatio)
float GetVerticalShift () const
void SetVerticalShift (float verticalShift)
bool IsNonLinearStretched () const
void SetNonLinearStretched (bool nonLinearStretch)
void SetMonitor (const std::string &monitor)
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from ISubSettings
virtual ~ISubSettings ()=default
Public Member Functions inherited from Observable
Observable ()=default
virtual ~Observable ()=default
Observable & operator= (const Observable &observable)
virtual void RegisterObserver (Observer *obs)
Register an observer.
virtual void UnregisterObserver (Observer *obs)
Unregister an observer.
virtual void NotifyObservers (const ObservableMessage message=ObservableMessageNone)
Send a message to all observers when m_bObservableChanged is true.
virtual void SetChanged (bool bSetTo=true)
Mark an observable changed.
virtual bool IsObserving (const Observer &obs) const
Check whether this observable is being observed by an observer.
Static Public Member Functions
static CDisplaySettings & GetInstance ()
static void SettingOptionsModesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsRefreshChangeDelaysFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsRefreshRatesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsResolutionsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsDispModeFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsStereoscopicModesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsPreferredStereoscopicViewModesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsMonitorsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsCmsModesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsCmsWhitepointsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsCmsPrimariesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsCmsGammaModesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
CDisplaySettings ()
CDisplaySettings (const CDisplaySettings &)=delete
CDisplaySettings & operator= (CDisplaySettings const &)=delete
~CDisplaySettings () override
DisplayMode GetCurrentDisplayMode () const
Protected Member Functions inherited from Observable
void SendMessage (const ObservableMessage message)
Send a message to all observer when m_bObservableChanged is true.
Static Protected Member Functions
static RESOLUTION GetResolutionFromString (const std::string &strResolution)
static std::string GetStringFromResolution (RESOLUTION resolution, float refreshrate=0.0f)
static RESOLUTION GetResolutionForScreen ()
static RESOLUTION FindBestMatchingResolution (const std::map< RESOLUTION, RESOLUTION_INFO > &resolutionInfos, int width, int height, float refreshrate, unsigned int flags)
Private Types
typedef std::vector< RESOLUTION_INFO > ResolutionInfos
Private Attributes
RESOLUTION m_currentResolution
ResolutionInfos m_resolutions
ResolutionInfos m_calibrations
float m_zoomAmount
float m_pixelRatio
float m_verticalShift
bool m_nonLinearStretched
bool m_resolutionChangeAborted
CCriticalSection m_critical
Additional Inherited Members
Protected Attributes inherited from Observable
std::atomic< bool > m_bObservableChanged {false}
std::vector< Observer * > m_observers
CCriticalSection m_obsCritSection
Member Typedef Documentation
ResolutionInfos
typedef std::vector<RESOLUTION_INFO> CDisplaySettings::ResolutionInfos private
Constructor & Destructor Documentation
CDisplaySettings() [1/2]
CDisplaySettings::CDisplaySettings () protected
References m_nonLinearStretched, m_pixelRatio, m_resolutionChangeAborted, m_resolutions, m_verticalShift, m_zoomAmount, and RES_CUSTOM.
CDisplaySettings() [2/2]
CDisplaySettings::CDisplaySettings (const CDisplaySettings &) protected delete
~CDisplaySettings()
CDisplaySettings::~CDisplaySettings () override protected default
Member Function Documentation
AddResolutionInfo()
void CDisplaySettings::AddResolutionInfo (const RESOLUTION_INFO & resolution)
References D3DPRESENTFLAG_MODE3DTB, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::iBlanking, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, m_critical, and m_resolutions.
Referenced by CWinSystemWin10::AddResolution(), CWinSystemWin32::AddResolution(), CWinSystemOSX::FillInVideoModes(), CWinSystemIOS::FillInVideoModes(), CWinSystemTVOS::FillInVideoModes(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetResolutionInternal(), KODI::WINDOWING::GBM::CWinSystemGbm::UpdateResolutions(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), and CWinSystemAndroid::UpdateResolutions().
ApplyCalibrations()
void CDisplaySettings::ApplyCalibrations ()
References m_calibrations, m_critical, m_resolutions, and RES_DESKTOP.
Referenced by CWinSystemBase::InitWindowSystem(), Load(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetResolutionInternal(), KODI::WINDOWING::GBM::CWinSystemGbm::UpdateResolutions(), CWinSystemOSX::UpdateResolutions(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateResolutions(), CWinSystemWin10::UpdateResolutions(), CWinSystemWin32::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), and CWinSystemAndroid::UpdateResolutions().
Clear()
void CDisplaySettings::Clear () override virtual
Clear any loaded setting values.
Reimplemented from ISubSettings.
References m_calibrations, m_critical, m_nonLinearStretched, m_pixelRatio, m_resolutions, m_verticalShift, m_zoomAmount, and RES_CUSTOM.
ClearCalibrations()
void CDisplaySettings::ClearCalibrations ()
References m_calibrations, and m_critical.
Referenced by CAndroidUtils::OnSettingChanged().
ClearCustomResolutions()
void CDisplaySettings::ClearCustomResolutions ()
References m_resolutions, and RES_CUSTOM.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbm::UpdateResolutions(), CWinSystemIOS::UpdateResolutions(), CWinSystemOSX::UpdateResolutions(), CWinSystemTVOS::UpdateResolutions(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateResolutions(), CWinSystemWin10::UpdateResolutions(), CWinSystemWin32::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), and CWinSystemAndroid::UpdateResolutions().
FindBestMatchingResolution()
RESOLUTION CDisplaySettings::FindBestMatchingResolution (const std::map< RESOLUTION, RESOLUTION_INFO > & resolutionInfos, int width, int height, float refreshrate, unsigned int flags) static protected
References D3DPRESENTFLAG_MODEMASK, RES_DESKTOP, and square_error().
Referenced by GetResolutionFromString(), and SettingOptionsResolutionsFiller().
GetCurrentDisplayMode()
DisplayMode CDisplaySettings::GetCurrentDisplayMode () const protected
References DM_FULLSCREEN, DM_WINDOWED, GetCurrentResolution(), and RES_WINDOW.
Referenced by OnSettingChanging(), and SetCurrentResolution().
GetCurrentResolution()
RESOLUTION CDisplaySettings::GetCurrentResolution () const inline
Returns the currently active resolution.
This resolution might differ from the display resolution which is based on the user's settings.
See also
SetCurrentResolution
GetResolutionInfo
GetDisplayResolution
References m_currentResolution.
Referenced by GetCurrentDisplayMode(), CApplication::InitWindow(), OnSettingChanging(), CGraphicContext::SetFullScreenVideo(), and CGraphicContext::ToggleFullScreen().
GetCurrentResolutionInfo() [1/2]
RESOLUTION_INFO & CDisplaySettings::GetCurrentResolutionInfo () inline
References GetResolutionInfo(), and m_currentResolution.
GetCurrentResolutionInfo() [2/2]
const RESOLUTION_INFO & CDisplaySettings::GetCurrentResolutionInfo () const inline
References GetResolutionInfo(), and m_currentResolution.
GetDisplayResolution()
RESOLUTION CDisplaySettings::GetDisplayResolution () const
Returns the best-matching resolution of the videoscreen.screenmode setting value.
This resolution might differ from the current resolution which is based on the properties of the operating system and the attached displays.
See also
GetCurrentResolution
References GetResolutionFromString(), CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOSCREEN_SCREENMODE.
Referenced by SettingOptionsRefreshRatesFiller(), and SettingOptionsResolutionsFiller().
GetInstance()
CDisplaySettings & CDisplaySettings::GetInstance () static
Referenced by AddRefreshRate(), CWinSystemWin10::AddResolution(), CWinSystemWin32::AddResolution(), AddResolution(), CGraphicContext::ApplyVideoResolution(), CWinSystemWin32::CenterWindow(), CheckAndUpdateCurrentMonitor(), CApplication::CreateGUI(), CWinSystemOSX::CreateNewWindow(), CWinSystemBase::DefaultRefreshRate(), KODI::WINDOWING::X11::CWinSystemX11::DestroyWindowSystem(), CWinSystemOSX::FillInVideoModes(), CWinSystemIOS::FillInVideoModes(), CWinSystemTVOS::FillInVideoModes(), anonymous_namespace{WinSystemWayland.cpp}::FindMatchingCustomResolution(), CResolutionUtils::FindResolutionFromOverride(), CResolutionUtils::FindResolutionFromWhitelist(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::FinishModeChange(), CGUIWindowFullScreen::FrameMove(), CGraphicContext::GetAllowedResolutions(), CResolutionUtils::GetMaxAllowedScreenResolution(), CGraphicContext::GetResInfo(), GetResolutionFromString(), GetStringFromResolution(), JSONRPC::CPlayerOperations::GetViewMode(), CAppInboundProtocol::HandleEvents(), CSettings::InitializeISettingCallbacks(), CSettings::InitializeISubSettings(), CApplication::InitWindow(), CWinSystemBase::InitWindowSystem(), CGraphicContext::IsValidResolution(), CBaseRenderer::ManageRenderArea(), CRendererDRMPRIME::ManageRenderArea(), CXBMCApp::MapRenderToDroid(), CWinSystemIOS::MoveToTouchscreen(), CWinSystemWin32::NotifyAppFocusChange(), CPlayerController::OnAction(), CGUIWindowSlideShow::OnDeinitWindow(), CGUIWindowSettingsCategory::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CWinSystemWin32DX::OnMove(), CAndroidUtils::OnSettingChanged(), CResolutionUtils::PrintWhitelist(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::ProcessMessages(), KODI::WINDOWING::X11::CWinSystemX11::RecreateWindow(), CWinSystemBase::RefreshRates(), CLinuxRendererGL::RenderFromFBO(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGL::RenderSinglePass(), CGraphicContext::ResetScreenParameters(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::ResizeWindow(), CWinSystemWin10::RestoreDesktopResolution(), CWinSystemBase::ScreenResolutions(), CWinSystemWin10::SetFullScreen(), CWinSystemWin32::SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11::SetFullScreen(), CGraphicContext::SetFullScreenVideo(), CGraphicContext::SetResInfo(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetResolutionInternal(), SettingOptionsModesFiller(), SettingOptionsRefreshRatesFiller(), SettingOptionsResolutionsFiller(), CGraphicContext::SetVideoResolutionInternal(), CBaseRenderer::SetViewMode(), CWinSystemBase::SetWindowResolution(), CGraphicContext::ToggleFullScreen(), OVERLAY::CRenderer::UnInit(), CSettings::UninitializeISettingCallbacks(), CSettings::UninitializeISubSettings(), CWinSystemBase::UpdateResolutions(), KODI::WINDOWING::GBM::CWinSystemGbm::UpdateResolutions(), CWinSystemIOS::UpdateResolutions(), CWinSystemOSX::UpdateResolutions(), CWinSystemTVOS::UpdateResolutions(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateResolutions(), CWinSystemWin10::UpdateResolutions(), CWinSystemWin32::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), CWinSystemAndroid::UpdateResolutions(), and CLinuxRendererGL::UpdateVideoFilter().
GetPixelRatio()
float CDisplaySettings::GetPixelRatio () const inline
References m_pixelRatio.
Referenced by CGUIWindowFullScreen::FrameMove(), JSONRPC::CPlayerOperations::GetViewMode(), CBaseRenderer::SetViewMode(), and CLinuxRendererGL::UpdateVideoFilter().
GetResFromString()
RESOLUTION CDisplaySettings::GetResFromString (const std::string & strResolution) inline
References GetResolutionFromString().
Referenced by CResolutionUtils::FindResolutionFromWhitelist(), CResolutionUtils::GetMaxAllowedScreenResolution(), CPlayerController::OnAction(), and CResolutionUtils::PrintWhitelist().
GetResolutionForScreen()
RESOLUTION CDisplaySettings::GetResolutionForScreen () static protected
References DM_WINDOWED, CServiceBroker::GetSettingsComponent(), RES_DESKTOP, RES_WINDOW, and CSettings::SETTING_VIDEOSCREEN_SCREEN.
Referenced by OnSettingChanging().
GetResolutionFromString()
RESOLUTION CDisplaySettings::GetResolutionFromString (const std::string & strResolution) static protected
References D3DPRESENTFLAG_INTERLACED, D3DPRESENTFLAG_MODE3DSBS, D3DPRESENTFLAG_MODE3DTB, FindBestMatchingResolution(), GetInstance(), GetResolutionInfo(), RES_DESKTOP, RES_WINDOW, and ResolutionInfoSize().
Referenced by GetDisplayResolution(), GetResFromString(), and OnSettingChanging().
GetResolutionInfo() [1/4]
RESOLUTION_INFO & CDisplaySettings::GetResolutionInfo (RESOLUTION resolution)
References EmptyModifiableResolution, GetResolutionInfo(), and RES_INVALID.
GetResolutionInfo() [2/4]
const RESOLUTION_INFO & CDisplaySettings::GetResolutionInfo (RESOLUTION resolution) const
References EmptyResolution, GetResolutionInfo(), and RES_INVALID.
GetResolutionInfo() [3/4]
RESOLUTION_INFO & CDisplaySettings::GetResolutionInfo (size_t index)
References EmptyModifiableResolution, index(), m_critical, and m_resolutions.
GetResolutionInfo() [4/4]
const RESOLUTION_INFO & CDisplaySettings::GetResolutionInfo (size_t index) const
References EmptyResolution, index(), m_critical, and m_resolutions.
Referenced by AddRefreshRate(), CWinSystemWin10::AddResolution(), CWinSystemWin32::AddResolution(), AddResolution(), CGraphicContext::ApplyVideoResolution(), CWinSystemWin32::CenterWindow(), CWinSystemOSX::CreateNewWindow(), CWinSystemBase::DefaultRefreshRate(), KODI::WINDOWING::X11::CWinSystemX11::DestroyWindowSystem(), anonymous_namespace{WinSystemWayland.cpp}::FindMatchingCustomResolution(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::FinishModeChange(), GetCurrentResolutionInfo(), GetCurrentResolutionInfo(), CGraphicContext::GetResInfo(), GetResolutionFromString(), KODI::RETRO::CRenderContext::GetResolutionInfo(), GetResolutionInfo(), GetResolutionInfo(), GetStringFromResolution(), CAppInboundProtocol::HandleEvents(), CXBMCApp::MapRenderToDroid(), CWinSystemWin32::NotifyAppFocusChange(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::ProcessMessages(), KODI::WINDOWING::X11::CWinSystemX11::RecreateWindow(), CWinSystemBase::RefreshRates(), CGraphicContext::ResetScreenParameters(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::ResizeWindow(), CWinSystemBase::ScreenResolutions(), CWinSystemWin10::SetFullScreen(), CWinSystemWin32::SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11::SetFullScreen(), CGraphicContext::SetResInfo(), SettingOptionsModesFiller(), SettingOptionsRefreshRatesFiller(), SettingOptionsResolutionsFiller(), CGraphicContext::SetVideoResolutionInternal(), CWinSystemBase::SetWindowResolution(), CWinSystemBase::UpdateResolutions(), KODI::WINDOWING::GBM::CWinSystemGbm::UpdateResolutions(), CWinSystemOSX::UpdateResolutions(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateResolutions(), CWinSystemWin10::UpdateResolutions(), CWinSystemWin32::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), and CWinSystemAndroid::UpdateResolutions().
GetStringFromRes()
std::string CDisplaySettings::GetStringFromRes (const RESOLUTION resolution, float refreshrate = 0.0f) inline
References GetStringFromResolution().
Referenced by CResolutionUtils::FindResolutionFromWhitelist().
GetStringFromResolution()
std::string CDisplaySettings::GetStringFromResolution (RESOLUTION resolution, float refreshrate = 0.0f) static protected
References GetInstance(), GetResolutionInfo(), ModeFlagsToString(), RES_DESKTOP, RES_WINDOW, and ResolutionInfoSize().
Referenced by GetStringFromRes(), OnSettingChanging(), SetCurrentResolution(), SettingOptionsModesFiller(), and SettingOptionsRefreshRatesFiller().
GetVerticalShift()
float CDisplaySettings::GetVerticalShift () const inline
References m_verticalShift.
Referenced by CGUIWindowFullScreen::FrameMove(), JSONRPC::CPlayerOperations::GetViewMode(), and CBaseRenderer::SetViewMode().
GetZoomAmount()
float CDisplaySettings::GetZoomAmount () const inline
References m_zoomAmount.
Referenced by CGUIWindowFullScreen::FrameMove(), JSONRPC::CPlayerOperations::GetViewMode(), and CBaseRenderer::SetViewMode().
IsNonLinearStretched()
bool CDisplaySettings::IsNonLinearStretched () const inline
References m_nonLinearStretched.
Referenced by JSONRPC::CPlayerOperations::GetViewMode(), CBaseRenderer::SetViewMode(), and CLinuxRendererGL::UpdateVideoFilter().
Load()
bool CDisplaySettings::Load (const TiXmlNode * settings) override virtual
Load settings from the given XML node.
Parameters
settings XML node containing setting values
Returns
True if loading the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References ApplyCalibrations(), OVERSCAN::bottom, RESOLUTION_INFO::fPixelRatio, RESOLUTION_INFO::fRefreshRate, XMLUtils::GetFloat(), XMLUtils::GetInt(), XMLUtils::GetString(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, OVERSCAN::left, CLog::Log(), LOGERROR, m_calibrations, m_critical, RESOLUTION_INFO::Overscan, OVERSCAN::right, RESOLUTION_INFO::strId, RESOLUTION_INFO::strMode, RESOLUTION_INFO::strOutput, and OVERSCAN::top.
OnSettingAction()
void CDisplaySettings::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References g_localizeStrings, CLocalizeStrings::Get(), CMediaManager::GetLocalDrives(), CServiceBroker::GetMediaManager(), and CGUIDialogFileBrowser::ShowAndGetFile().
OnSettingChanged()
void CDisplaySettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References CResolutionUtils::PrintWhitelist(), and CSettings::SETTING_VIDEOSCREEN_WHITELIST.
OnSettingChanging()
bool CDisplaySettings::OnSettingChanging (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting is being changed.
This callback is triggered whenever the value of a setting is being changed. The given CSetting already contains the new value and the handler of the callback has the possibility to allow or revert changing the value of the setting. In case of a revert OnSettingChanging() is called again to inform all listeners that the value change has been reverted.
Parameters
setting The setting whose value is being changed (already containing the changed value)
Returns
True if the new value is acceptable otherwise false
Reimplemented from ISettingCallback.
References DX::DeviceResources::Get(), GetCurrentDisplayMode(), GetCurrentResolution(), CWinSystemBase::GetGfxContext(), GetResolutionForScreen(), GetResolutionFromString(), CServiceBroker::GetSettingsComponent(), GetStringFromResolution(), GetValue(), CGraphicContext::GetVideoResolution(), CServiceBroker::GetWinSystem(), m_resolutionChangeAborted, RES_DESKTOP, RES_WINDOW, SetCurrentResolution(), SetString(), CSettings::SETTING_VIDEOSCREEN_10BITSURFACES, CSettings::SETTING_VIDEOSCREEN_BLANKDISPLAYS, CSettings::SETTING_VIDEOSCREEN_MONITOR, CSettings::SETTING_VIDEOSCREEN_RESOLUTION, CSettings::SETTING_VIDEOSCREEN_SCREEN, CSettings::SETTING_VIDEOSCREEN_SCREENMODE, CGraphicContext::SetVideoResolution(), and KODI::MESSAGING::HELPERS::ShowYesNoDialogText().
OnSettingUpdate()
bool CDisplaySettings::OnSettingUpdate (const std::shared_ptr< CSetting > & setting, const char * oldSettingId, const TiXmlNode * oldSettingNode) override virtual
The given setting needs to be updated.
This callback is triggered when a setting needs to be updated because its value is outdated. This only happens when initially loading the value of a setting and will not be triggered afterwards.
Parameters
setting The setting which needs to be updated.
oldSettingId The id of the previous setting.
oldSettingNode The old setting node
Returns
True if the setting has been successfully updated otherwise false
Reimplemented from ISettingCallback.
References CServiceBroker::GetSettingsComponent(), RENDER_STEREO_MODE_AUTO, RENDER_STEREO_MODE_MONO, RENDER_STEREO_MODE_OFF, CSettings::SETTING_VIDEOPLAYER_STEREOSCOPICPLAYBACKMODE, CSettings::SETTING_VIDEOSCREEN_PREFEREDSTEREOSCOPICMODE, CSettings::SETTING_VIDEOSCREEN_SCREENMODE, STEREOSCOPIC_PLAYBACK_MODE_IGNORE, STEREOSCOPIC_PLAYBACK_MODE_MONO, and STEREOSCOPIC_PLAYBACK_MODE_PREFERRED.
operator=()
CDisplaySettings & CDisplaySettings::operator= (CDisplaySettings const &) protected delete
ResolutionInfoSize()
size_t CDisplaySettings::ResolutionInfoSize () const inline
References m_resolutions.
Referenced by CWinSystemWin10::AddResolution(), CWinSystemWin32::AddResolution(), anonymous_namespace{WinSystemWayland.cpp}::FindMatchingCustomResolution(), CResolutionUtils::FindResolutionFromOverride(), CGraphicContext::GetAllowedResolutions(), GetResolutionFromString(), GetStringFromResolution(), KODI::WINDOWING::X11::CWinSystemX11::RecreateWindow(), CWinSystemBase::RefreshRates(), CWinSystemBase::ScreenResolutions(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetResolutionInternal(), and SettingOptionsModesFiller().
Save()
bool CDisplaySettings::Save (TiXmlNode * settings) const override virtual
Save settings to the given XML node.
Parameters
settings XML node in which the settings will be saved
Returns
True if saving the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References m_calibrations, m_critical, XMLUtils::SetFloat(), XMLUtils::SetInt(), and XMLUtils::SetString().
SetCurrentResolution()
void CDisplaySettings::SetCurrentResolution (RESOLUTION resolution, bool save = false)
References GetCurrentDisplayMode(), CServiceBroker::GetSettingsComponent(), GetStringFromResolution(), CServiceBroker::GetWinSystem(), m_currentResolution, RES_DESKTOP, RES_WINDOW, Observable::SetChanged(), CSettings::SETTING_VIDEOSCREEN_SCREEN, and CSettings::SETTING_VIDEOSCREEN_SCREENMODE.
Referenced by CApplication::CreateGUI(), CGUIWindowSettingsCategory::OnMessage(), OnSettingChanging(), and CGraphicContext::ToggleFullScreen().
SetMonitor()
void CDisplaySettings::SetMonitor (const std::string & monitor)
References CServiceBroker::GetSettingsComponent(), m_resolutionChangeAborted, and CSettings::SETTING_VIDEOSCREEN_MONITOR.
Referenced by CheckAndUpdateCurrentMonitor(), CWinSystemIOS::MoveToTouchscreen(), CWinSystemWin32DX::OnMove(), and CWinSystemWin32::UpdateResolutions().
SetNonLinearStretched()
void CDisplaySettings::SetNonLinearStretched (bool nonLinearStretch) inline
References m_nonLinearStretched.
Referenced by CBaseRenderer::SetViewMode().
SetPixelRatio()
void CDisplaySettings::SetPixelRatio (float pixelRatio) inline
References m_pixelRatio.
Referenced by CBaseRenderer::SetViewMode().
SettingOptionsCmsGammaModesFiller()
void CDisplaySettings::SettingOptionsCmsGammaModesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References CMS_TRC_ABSOLUTE, CMS_TRC_BT1886, CMS_TRC_INPUT_OFFSET, CMS_TRC_OUTPUT_OFFSET, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsCmsModesFiller()
void CDisplaySettings::SettingOptionsCmsModesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References CMS_MODE_3DLUT, CMS_MODE_PROFILE, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsCmsPrimariesFiller()
void CDisplaySettings::SettingOptionsCmsPrimariesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References CMS_PRIMARIES_170M, CMS_PRIMARIES_240M, CMS_PRIMARIES_AUTO, CMS_PRIMARIES_BT2020, CMS_PRIMARIES_BT470BG, CMS_PRIMARIES_BT470M, CMS_PRIMARIES_BT709, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsCmsWhitepointsFiller()
void CDisplaySettings::SettingOptionsCmsWhitepointsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References CMS_WHITEPOINT_D65, CMS_WHITEPOINT_D93, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsDispModeFiller()
void CDisplaySettings::SettingOptionsDispModeFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References DM_FULLSCREEN, DM_WINDOWED, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetSettingsComponent(), and CServiceBroker::GetWinSystem().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsModesFiller()
void CDisplaySettings::SettingOptionsModesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References D3DPRESENTFLAG_INTERLACED, GetInstance(), GetResolutionInfo(), GetStringFromResolution(), index(), ModeFlagsToString(), ModeSort(), RES_CUSTOM, and ResolutionInfoSize().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsMonitorsFiller()
void CDisplaySettings::SettingOptionsMonitorsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), and CSettings::SETTING_VIDEOSCREEN_MONITOR.
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsPreferredStereoscopicViewModesFiller()
void CDisplaySettings::SettingOptionsPreferredStereoscopicViewModesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References CServiceBroker::GetGUI(), CStereoscopicsManager::GetLabelForStereoMode(), CServiceBroker::GetRenderSystem(), CGUIComponent::GetStereoscopicsManager(), RENDER_STEREO_MODE_AUTO, RENDER_STEREO_MODE_COUNT, RENDER_STEREO_MODE_MONO, RENDER_STEREO_MODE_OFF, and CRenderSystemBase::SupportsStereo().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsRefreshChangeDelaysFiller()
void CDisplaySettings::SettingOptionsRefreshChangeDelaysFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, CLocalizeStrings::Get(), and MAX_REFRESH_CHANGE_DELAY.
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsRefreshRatesFiller()
void CDisplaySettings::SettingOptionsRefreshRatesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References RESOLUTION_INFO::dwFlags, g_localizeStrings, CLocalizeStrings::Get(), GetDisplayResolution(), GetInstance(), GetResolutionInfo(), GetStringFromResolution(), GetValue(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, CWinSystemBase::RefreshRates(), and RES_WINDOW.
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsResolutionsFiller()
void CDisplaySettings::SettingOptionsResolutionsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References FindBestMatchingResolution(), g_localizeStrings, CLocalizeStrings::Get(), GetDisplayResolution(), GetInstance(), GetResolutionInfo(), CServiceBroker::GetWinSystem(), ModeFlagsToString(), RES_WINDOW, and CWinSystemBase::ScreenResolutions().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsStereoscopicModesFiller()
void CDisplaySettings::SettingOptionsStereoscopicModesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References CServiceBroker::GetGUI(), CStereoscopicsManager::GetLabelForStereoMode(), CServiceBroker::GetRenderSystem(), CGUIComponent::GetStereoscopicsManager(), RENDER_STEREO_MODE_COUNT, RENDER_STEREO_MODE_OFF, and CRenderSystemBase::SupportsStereo().
Referenced by CSettings::InitializeOptionFillers().
SetVerticalShift()
void CDisplaySettings::SetVerticalShift (float verticalShift) inline
References m_verticalShift.
Referenced by CBaseRenderer::SetViewMode().
SetZoomAmount()
void CDisplaySettings::SetZoomAmount (float zoomAmount) inline
References m_zoomAmount.
Referenced by CBaseRenderer::SetViewMode().
UpdateCalibrations()
void CDisplaySettings::UpdateCalibrations ()
Todo:
erase calibrations with default values
References m_calibrations, m_critical, m_resolutions, RES_CUSTOM, and RES_DESKTOP.
Referenced by CGUIWindowSettingsScreenCalibration::OnMessage(), and OVERLAY::CRenderer::UnInit().
Member Data Documentation
m_calibrations
ResolutionInfos CDisplaySettings::m_calibrations private
Referenced by ApplyCalibrations(), Clear(), ClearCalibrations(), Load(), Save(), and UpdateCalibrations().
m_critical
CCriticalSection CDisplaySettings::m_critical mutable private
Referenced by AddResolutionInfo(), ApplyCalibrations(), Clear(), ClearCalibrations(), GetResolutionInfo(), GetResolutionInfo(), Load(), Save(), and UpdateCalibrations().
m_currentResolution
RESOLUTION CDisplaySettings::m_currentResolution private
Referenced by GetCurrentResolution(), GetCurrentResolutionInfo(), GetCurrentResolutionInfo(), and SetCurrentResolution().
m_nonLinearStretched
bool CDisplaySettings::m_nonLinearStretched private
Referenced by CDisplaySettings(), Clear(), IsNonLinearStretched(), and SetNonLinearStretched().
m_pixelRatio
float CDisplaySettings::m_pixelRatio private
Referenced by CDisplaySettings(), Clear(), GetPixelRatio(), and SetPixelRatio().
m_resolutionChangeAborted
bool CDisplaySettings::m_resolutionChangeAborted private
Referenced by CDisplaySettings(), OnSettingChanging(), and SetMonitor().
m_resolutions
ResolutionInfos CDisplaySettings::m_resolutions private
Referenced by AddResolutionInfo(), ApplyCalibrations(), CDisplaySettings(), Clear(), ClearCustomResolutions(), GetResolutionInfo(), GetResolutionInfo(), ResolutionInfoSize(), and UpdateCalibrations().
m_verticalShift
float CDisplaySettings::m_verticalShift private
Referenced by CDisplaySettings(), Clear(), GetVerticalShift(), and SetVerticalShift().
m_zoomAmount
float CDisplaySettings::m_zoomAmount private
Referenced by CDisplaySettings(), Clear(), GetZoomAmount(), and SetZoomAmount().
The documentation for this class was generated from the following files:
DisplaySettings.h
DisplaySettings.cpp