Kodi Documentation: CDVDOverlayCodec Class Reference
CDVDOverlayCodec Class Reference abstract
#include <DVDOverlayCodec.h>
Classes
struct SubtitlePacketExtraData
Public Member Functions
CDVDOverlayCodec (const char *name)
virtual ~CDVDOverlayCodec ()=default
virtual bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options)=0
virtual OverlayMessage Decode (DemuxPacket *pPacket)=0
virtual void Reset ()=0
virtual void Flush ()=0
virtual std::shared_ptr< CDVDOverlay > GetOverlay ()=0
const std::string & GetName () const
Static Protected Member Functions
static void GetAbsoluteTimes (double &starttime, double &stoptime, DemuxPacket *pkt)
Private Attributes
std::string m_codecName
Constructor & Destructor Documentation
CDVDOverlayCodec()
CDVDOverlayCodec::CDVDOverlayCodec (const char * name) inline explicit
~CDVDOverlayCodec()
virtual CDVDOverlayCodec::~CDVDOverlayCodec () virtual default
Member Function Documentation
Decode()
virtual OverlayMessage CDVDOverlayCodec::Decode (DemuxPacket * pPacket) pure virtual
Implemented in CDVDOverlayCodecCCText, CDVDOverlayCodecFFmpeg, CDVDOverlayCodecSSA, CDVDOverlayCodecText, CDVDOverlayCodecTX3G, and COverlayCodecWebVTT.
Flush()
virtual void CDVDOverlayCodec::Flush () pure virtual
Implemented in CDVDOverlayCodecCCText, CDVDOverlayCodecFFmpeg, CDVDOverlayCodecSSA, CDVDOverlayCodecText, CDVDOverlayCodecTX3G, and COverlayCodecWebVTT.
GetAbsoluteTimes()
void CDVDOverlayCodec::GetAbsoluteTimes (double & starttime, double & stoptime, DemuxPacket * pkt) static protected
References DEMUX_PACKET::dts, DEMUX_PACKET::duration, DVD_NOPTS_VALUE, and DEMUX_PACKET::pts.
Referenced by CDVDOverlayCodecCCText::Decode(), CDVDOverlayCodecFFmpeg::Decode(), CDVDOverlayCodecText::Decode(), and CDVDOverlayCodecTX3G::Decode().
GetName()
const std::string & CDVDOverlayCodec::GetName () const inline
References m_codecName.
GetOverlay()
virtual std::shared_ptr< CDVDOverlay > CDVDOverlayCodec::GetOverlay () pure virtual
Implemented in CDVDOverlayCodecCCText, CDVDOverlayCodecFFmpeg, CDVDOverlayCodecSSA, CDVDOverlayCodecText, CDVDOverlayCodecTX3G, and COverlayCodecWebVTT.
Open()
virtual bool CDVDOverlayCodec::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) pure virtual
Implemented in CDVDOverlayCodecCCText, CDVDOverlayCodecFFmpeg, CDVDOverlayCodecSSA, CDVDOverlayCodecText, CDVDOverlayCodecTX3G, and COverlayCodecWebVTT.
Reset()
virtual void CDVDOverlayCodec::Reset () pure virtual
Implemented in CDVDOverlayCodecCCText, CDVDOverlayCodecFFmpeg, CDVDOverlayCodecSSA, CDVDOverlayCodecText, CDVDOverlayCodecTX3G, and COverlayCodecWebVTT.
Member Data Documentation
m_codecName
std::string CDVDOverlayCodec::m_codecName private
Referenced by GetName().
The documentation for this class was generated from the following files:
DVDOverlayCodec.h
DVDOverlayCodec.cpp