var namespaceanonymous__namespace_02_test_network_file_item_classify_8cpp_03 =
[
    [ "SimpleDefinition", "d6/dbe/structanonymous__namespace_02_test_network_file_item_classify_8cpp_03_1_1_simple_definition.html", "d6/dbe/structanonymous__namespace_02_test_network_file_item_classify_8cpp_03_1_1_simple_definition" ]
];