Kodi Documentation: CSlideShowPicGLES Class Reference
CSlideShowPicGLES Class Reference
#include <SlideShowPictureGLES.h>
Public Member Functions
CSlideShowPicGLES ()=default
~CSlideShowPicGLES () override=default
Public Member Functions inherited from CSlideShowPic
CSlideShowPic ()
virtual ~CSlideShowPic ()
void SetTexture (int iSlideNumber, std::unique_ptr< CTexture > pTexture, DISPLAY_EFFECT dispEffect=EFFECT_RANDOM, TRANSITION_EFFECT transEffect=FADEIN_FADEOUT)
void UpdateTexture (std::unique_ptr< CTexture > pTexture)
bool IsLoaded () const
void UnLoad ()
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions)
void Render ()
void Close ()
void Reset (DISPLAY_EFFECT dispEffect=EFFECT_RANDOM, TRANSITION_EFFECT transEffect=FADEIN_FADEOUT)
DISPLAY_EFFECT DisplayEffect () const
bool DisplayEffectNeedChange (DISPLAY_EFFECT newDispEffect) const
bool IsStarted () const
bool IsFinished () const
bool IsAnimating () const
bool DrawNextImage () const
int GetWidth () const
int GetHeight () const
void Keep ()
bool StartTransition ()
int GetTransitionTime (int iType) const
void SetTransitionTime (int iType, int iTime)
int SlideNumber () const
void Zoom (float fZoomAmount, bool immediate=false)
void Rotate (float fRotateAngle, bool immediate=false)
void UpdateAlpha ()
void Pause (bool bPause)
void SetInSlideshow (bool slideshow)
void SetOriginalSize (int iOriginalWidth, int iOriginalHeight, bool bFullSize)
bool FullSize () const
int GetOriginalWidth ()
int GetOriginalHeight ()
void Move (float dX, float dY)
float GetZoom () const
Protected Member Functions
void Render (float *x, float *y, CTexture *pTexture, KODI::UTILS::COLOR::Color color) override
Additional Inherited Members
Public Types inherited from CSlideShowPic
enum DISPLAY_EFFECT {
EFFECT_NONE = 0 , EFFECT_FLOAT , EFFECT_ZOOM , EFFECT_RANDOM ,
EFFECT_PANORAMA , EFFECT_NO_TIMEOUT
}
enum TRANSITION_EFFECT {
TRANSITION_NONE = 0 , FADEIN_FADEOUT , CROSSFADE , TRANSITION_ZOOM ,
TRANSITION_ROTATE
}
Static Public Member Functions inherited from CSlideShowPic
static std::unique_ptr< CSlideShowPic > CreateSlideShowPicture ()
Public Attributes inherited from CSlideShowPic
bool m_bIsComic
bool m_bCanMoveHorizontally
bool m_bCanMoveVertically
Constructor & Destructor Documentation
CSlideShowPicGLES()
CSlideShowPicGLES::CSlideShowPicGLES () default
~CSlideShowPicGLES()
CSlideShowPicGLES::~CSlideShowPicGLES () override default
Member Function Documentation
Render()
void CSlideShowPicGLES::Render (float * x, float * y, CTexture * pTexture, KODI::UTILS::COLOR::Color color) override protected virtual
Implements CSlideShowPic.
References KODI::UTILS::GL::A, KODI::UTILS::GL::B, CTexture::BindToUnit(), color, CRenderSystemGLES::DisableGUIShader(), CRenderSystemGLES::EnableGUIShader(), KODI::UTILS::GL::G, KODI::UTILS::GL::GetChannelFromARGB(), CTextureBase::GetHeight(), CServiceBroker::GetRenderSystem(), CTextureBase::GetTextureHeight(), CTextureBase::GetTextureWidth(), CTextureBase::GetWidth(), CServiceBroker::GetWinSystem(), CRenderSystemGLES::GUIShaderGetCoord0(), CRenderSystemGLES::GUIShaderGetDepth(), CRenderSystemGLES::GUIShaderGetPos(), CRenderSystemGLES::GUIShaderGetUniCol(), CTexture::LoadToGPU(), KODI::UTILS::GL::R, SM_DEFAULT, and SM_TEXTURE.
The documentation for this class was generated from the following files:
SlideShowPictureGLES.h
SlideShowPictureGLES.cpp