Kodi Documentation: CLinuxRendererGLES Class Reference
CLinuxRendererGLES Class Reference
#include <LinuxRendererGLES.h>
Classes
struct CPictureBuffer
struct CYuvPlane
Public Member Functions
CLinuxRendererGLES ()
~CLinuxRendererGLES () override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
bool IsConfigured () override
void AddVideoPicture (const VideoPicture &picture, int index) override
void UnInit () override
bool Flush (bool saveBuffers) override
void SetBufferSize (int numBuffers) override
bool IsGuiLayer () override
void ReleaseBuffer (int idx) override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
void Update () override
bool RenderCapture (int index, CRenderCapture *capture) override
CRenderInfo GetRenderInfo () override
bool ConfigChanged (const VideoPicture &picture) override
bool SupportsMultiPassRendering () override
bool Supports (ERENDERFEATURE feature) const override
bool Supports (ESCALINGMETHOD method) const override
CRenderCapture * GetRenderCapture () override
Public Member Functions inherited from CBaseRenderer
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool IsPictureHW (const VideoPicture &picture)
virtual bool NeedBuffer (int idx)
virtual bool WantsDoublePass ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
virtual DEBUG_INFO_VIDEO GetDebugInfo (int idx)
Static Public Member Functions
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Static Public Member Functions inherited from CBaseRenderer
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
virtual bool Render (unsigned int flags, int index)
virtual void RenderUpdateVideo (bool clear, unsigned int flags=0, unsigned int alpha=255)
int NextYV12Texture ()
virtual bool ValidateRenderTarget ()
virtual void LoadShaders (int field=FIELD_FULL)
virtual void ReleaseShaders ()
void SetTextureFilter (GLenum method)
void UpdateVideoFilter ()
AVColorPrimaries GetSrcPrimaries (AVColorPrimaries srcPrimaries, unsigned int width, unsigned int height)
virtual bool UploadTexture (int index)
virtual void DeleteTexture (int index)
virtual bool CreateTexture (int index)
bool UploadYV12Texture (int index)
void DeleteYV12Texture (int index)
bool CreateYV12Texture (int index)
virtual bool SkipUploadYV12 (int index)
bool UploadNV12Texture (int index)
void DeleteNV12Texture (int index)
bool CreateNV12Texture (int index)
void CalculateTextureSourceRects (int source, int num_planes)
void RenderToFBO (int index, int field)
void RenderFromFBO ()
void RenderSinglePass (int index, int field)
virtual bool LoadShadersHook ()
virtual bool RenderHook (int idx)
virtual void AfterRenderHook (int idx)
void LoadPlane (CYuvPlane &plane, int type, unsigned width, unsigned height, int stride, int bpp, void *data)
Protected Member Functions inherited from CBaseRenderer
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ManageRenderArea ()
virtual void ReorderDrawPoints ()
virtual EShaderFormat GetShaderFormat ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Protected Attributes
struct {
CFrameBufferObject fbo
float width {0.0}
float height {0.0}
} m_fbo
int m_iYV12RenderBuffer {0}
int m_NumYV12Buffers {0}
bool m_bConfigured {false}
bool m_bValidated {false}
GLenum m_textureTarget = GL_TEXTURE_2D
int m_renderMethod {RENDER_GLSL}
RenderQuality m_renderQuality {RQ_SINGLEPASS}
int m_currentField {FIELD_FULL}
int m_reloadShaders {0}
CRenderSystemGLES * m_renderSystem {nullptr}
GLenum m_pixelStoreKey {0}
CPictureBuffer m_buffers [NUM_BUFFERS]
Shaders::GLES::BaseYUV2RGBGLSLShader * m_pYUVProgShader {nullptr}
Shaders::GLES::BaseYUV2RGBGLSLShader * m_pYUVBobShader {nullptr}
Shaders::GLES::BaseVideoFilterShader * m_pVideoFilterShader {nullptr}
ESCALINGMETHOD m_scalingMethod {VS_SCALINGMETHOD_LINEAR}
ESCALINGMETHOD m_scalingMethodGui {VS_SCALINGMETHOD_MAX}
bool m_fullRange
AVColorPrimaries m_srcPrimaries
bool m_toneMap = false
ETONEMAPMETHOD m_toneMapMethod = VS_TONEMAPMETHOD_OFF
bool m_passthroughHDR = false
unsigned char * m_planeBuffer = nullptr
size_t m_planeBufferSize = 0
float m_clearColour {0.0f}
CRect m_viewRect
Protected Attributes inherited from CBaseRenderer
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Static Protected Attributes
static const int FIELD_FULL {0}
static const int FIELD_TOP {1}
static const int FIELD_BOT {2}
Private Member Functions
void ClearBackBuffer ()
void ClearBackBufferQuad ()
void DrawBlackBars ()
Constructor & Destructor Documentation
CLinuxRendererGLES()
CLinuxRendererGLES::CLinuxRendererGLES ()
References CServiceBroker::GetRenderSystem(), CServiceBroker::GetWinSystem(), CRenderSystemGLES::IsExtSupported(), CBaseRenderer::m_format, m_fullRange, m_pixelStoreKey, m_renderSystem, and CWinSystemBase::UseLimitedColor().
Referenced by Create().
~CLinuxRendererGLES()
CLinuxRendererGLES::~CLinuxRendererGLES () override
References m_planeBuffer, ReleaseShaders(), and UnInit().
Member Function Documentation
AddVideoPicture()
void CLinuxRendererGLES::AddVideoPicture (const VideoPicture & picture, int index) override virtual
Implements CBaseRenderer.
Reimplemented in CRendererMediaCodec.
References CVideoBuffer::Acquire(), VideoPicture::color_primaries, VideoPicture::color_range, VideoPicture::color_space, VideoPicture::colorBits, VideoPicture::displayMetadata, CLinuxRendererGLES::CPictureBuffer::displayMetadata, VideoPicture::hasDisplayMetadata, CLinuxRendererGLES::CPictureBuffer::hasDisplayMetadata, VideoPicture::hasLightMetadata, CLinuxRendererGLES::CPictureBuffer::hasLightMetadata, index(), VideoPicture::lightMetadata, CLinuxRendererGLES::CPictureBuffer::lightMetadata, CLinuxRendererGLES::CPictureBuffer::loaded, LOGERROR, m_buffers, CLinuxRendererGLES::CPictureBuffer::m_srcBits, CLinuxRendererGLES::CPictureBuffer::m_srcColSpace, CLinuxRendererGLES::CPictureBuffer::m_srcFullRange, CLinuxRendererGLES::CPictureBuffer::m_srcPrimaries, CVideoBuffer::Release(), VideoPicture::videoBuffer, and CLinuxRendererGLES::CPictureBuffer::videoBuffer.
AfterRenderHook()
virtual void CLinuxRendererGLES::AfterRenderHook (int idx) inline protected virtual
Reimplemented in CRendererVAAPIGLES, CRendererVTB, and CRendererVTB.
Referenced by Render().
CalculateTextureSourceRects()
void CLinuxRendererGLES::CalculateTextureSourceRects (int source, int num_planes) protected
References YuvImage::cshift_x, YuvImage::cshift_y, FIELD_BOT, FIELD_FULL, CLinuxRendererGLES::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGLES::CYuvPlane::height, CLinuxRendererGLES::CPictureBuffer::image, m_buffers, CBaseRenderer::m_sourceRect, m_textureTarget, CLinuxRendererGLES::CYuvPlane::pixpertex_x, CLinuxRendererGLES::CYuvPlane::pixpertex_y, CLinuxRendererGLES::CYuvPlane::rect, CLinuxRendererGLES::CYuvPlane::texheight, CLinuxRendererGLES::CYuvPlane::texwidth, YuvImage::width, CLinuxRendererGLES::CYuvPlane::width, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by UploadNV12Texture(), CRendererMediaCodec::UploadTexture(), CRendererVAAPIGLES::UploadTexture(), and UploadYV12Texture().
ClearBackBuffer()
void CLinuxRendererGLES::ClearBackBuffer () private
References CGraphicContext::Clear(), ClearBackBufferQuad(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), and RENDER_ORDER_ALL_BACK_TO_FRONT.
Referenced by RenderUpdate().
ClearBackBufferQuad()
void CLinuxRendererGLES::ClearBackBufferQuad () private
References CRenderSystemGLES::DisableGUIShader(), CRenderSystemGLES::EnableGUIShader(), CServiceBroker::GetWinSystem(), CRenderSystemGLES::GUIShaderGetDepth(), CRenderSystemGLES::GUIShaderGetPos(), CRenderSystemGLES::GUIShaderGetUniCol(), m_clearColour, m_renderSystem, SM_DEFAULT, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by ClearBackBuffer().
ConfigChanged()
bool CLinuxRendererGLES::ConfigChanged (const VideoPicture & picture) override virtual
Implements CBaseRenderer.
Reimplemented in CRendererVAAPIGLES.
References CVideoBuffer::GetFormat(), CBaseRenderer::m_format, and VideoPicture::videoBuffer.
Configure()
bool CLinuxRendererGLES::Configure (const VideoPicture & picture, float fps, unsigned int orientation) override virtual
Implements CBaseRenderer.
Reimplemented in CRendererVAAPIGLES.
References CBaseRenderer::CalculateFrameAspectRatio(), VideoPicture::color_primaries, CVideoBuffer::GetFormat(), CServiceBroker::GetWinSystem(), VideoPicture::hasDisplayMetadata, VideoPicture::hasLightMetadata, VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iHeight, VideoPicture::iWidth, CLog::Log(), LOGDEBUG, m_bConfigured, m_bValidated, m_clearColour, CBaseRenderer::m_format, m_passthroughHDR, CBaseRenderer::m_renderOrientation, m_scalingMethodGui, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, m_srcPrimaries, m_toneMap, CBaseRenderer::m_videoSettings, CVideoSettings::m_ViewMode, CBaseRenderer::ManageRenderArea(), CWinSystemBase::SetHDR(), CBaseRenderer::SetViewMode(), CWinSystemBase::UseLimitedColor(), and VideoPicture::videoBuffer.
Referenced by CRendererVAAPIGLES::Configure().
Create()
CBaseRenderer * CLinuxRendererGLES::Create (CVideoBuffer * buffer) static
References CLinuxRendererGLES().
Referenced by Register().
CreateNV12Texture()
bool CLinuxRendererGLES::CreateNV12Texture (int index) protected
References YuvImage::bpp, YuvImage::cshift_x, YuvImage::cshift_y, DeleteNV12Texture(), f, FIELD_BOT, FIELD_FULL, CLinuxRendererGLES::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGLES::CYuvPlane::id, CLinuxRendererGLES::CPictureBuffer::image, index(), m_buffers, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, m_textureTarget, MAX_FIELDS, YuvImage::MAX_PLANES, YuvImage::plane, YuvImage::planesize, YuvImage::stride, CLinuxRendererGLES::CYuvPlane::texheight, CLinuxRendererGLES::CYuvPlane::texwidth, VerifyGLState, and YuvImage::width.
Referenced by CreateTexture(), and CRendererVAAPIGLES::CreateTexture().
CreateTexture()
bool CLinuxRendererGLES::CreateTexture (int index) protected virtual
Reimplemented in CRendererMediaCodec, CRendererVAAPIGLES, CRendererVTB, and CRendererVTB.
References CreateNV12Texture(), CreateYV12Texture(), index(), and CBaseRenderer::m_format.
Referenced by ValidateRenderTarget().
CreateYV12Texture()
bool CLinuxRendererGLES::CreateYV12Texture (int index) protected
References YuvImage::bpp, YuvImage::cshift_x, YuvImage::cshift_y, DeleteYV12Texture(), f, FIELD_BOT, FIELD_FULL, fields, CLinuxRendererGLES::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGLES::CYuvPlane::id, CLinuxRendererGLES::CPictureBuffer::image, index(), m_buffers, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, m_textureTarget, MAX_FIELDS, YuvImage::MAX_PLANES, YuvImage::plane, YuvImage::planesize, YuvImage::stride, CLinuxRendererGLES::CYuvPlane::texheight, CLinuxRendererGLES::CYuvPlane::texwidth, VerifyGLState, and YuvImage::width.
Referenced by CreateTexture().
DeleteNV12Texture()
void CLinuxRendererGLES::DeleteNV12Texture (int index) protected
References f, FIELD_FULL, CLinuxRendererGLES::CPictureBuffer::fields, CLinuxRendererGLES::CYuvPlane::id, CLinuxRendererGLES::CPictureBuffer::image, index(), m_buffers, MAX_FIELDS, and YuvImage::plane.
Referenced by CreateNV12Texture(), DeleteTexture(), and CRendererVAAPIGLES::DeleteTexture().
DeleteTexture()
void CLinuxRendererGLES::DeleteTexture (int index) protected virtual
Reimplemented in CRendererMediaCodec, CRendererVAAPIGLES, CRendererVTB, and CRendererVTB.
References DeleteNV12Texture(), DeleteYV12Texture(), index(), CBaseRenderer::m_format, and ReleaseBuffer().
Referenced by Flush(), UnInit(), and ValidateRenderTarget().
DeleteYV12Texture()
void CLinuxRendererGLES::DeleteYV12Texture (int index) protected
References f, FIELD_FULL, fields, CLinuxRendererGLES::CPictureBuffer::fields, CLinuxRendererGLES::CYuvPlane::id, CLinuxRendererGLES::CPictureBuffer::image, index(), m_buffers, MAX_FIELDS, YuvImage::MAX_PLANES, and YuvImage::plane.
Referenced by CreateYV12Texture(), and DeleteTexture().
DrawBlackBars()
void CLinuxRendererGLES::DrawBlackBars () private
References CRenderSystemGLES::DisableGUIShader(), CRenderSystemGLES::EnableGUIShader(), CServiceBroker::GetRenderSystem(), CServiceBroker::GetWinSystem(), CRenderSystemGLES::GUIShaderGetDepth(), CRenderSystemGLES::GUIShaderGetPos(), CRenderSystemGLES::GUIShaderGetUniCol(), m_clearColour, CBaseRenderer::m_destRect, m_renderSystem, SM_DEFAULT, and CRectGen< T >::SubtractRect().
Referenced by RenderUpdate().
Flush()
bool CLinuxRendererGLES::Flush (bool saveBuffers) override virtual
Reimplemented from CBaseRenderer.
References DeleteTexture(), m_bValidated, m_fbo, m_iYV12RenderBuffer, and m_NumYV12Buffers.
GetRenderCapture()
CRenderCapture * CLinuxRendererGLES::GetRenderCapture () override virtual
Reimplemented from CBaseRenderer.
GetRenderInfo()
CRenderInfo CLinuxRendererGLES::GetRenderInfo () override virtual
Reimplemented from CBaseRenderer.
Reimplemented in CRendererMediaCodec.
References CRenderInfo::max_buffer_size, and NUM_BUFFERS.
GetSrcPrimaries()
AVColorPrimaries CLinuxRendererGLES::GetSrcPrimaries (AVColorPrimaries srcPrimaries, unsigned int width, unsigned int height) protected
IsConfigured()
bool CLinuxRendererGLES::IsConfigured () inline override virtual
Implements CBaseRenderer.
References m_bConfigured.
IsGuiLayer()
bool CLinuxRendererGLES::IsGuiLayer () override virtual
Reimplemented from CBaseRenderer.
Referenced by RenderUpdate(), and RenderUpdateVideo().
LoadPlane()
void CLinuxRendererGLES::LoadPlane (CYuvPlane & plane, int type, unsigned width, unsigned height, int stride, int bpp, void * data) protected
References data(), KODI::UTILS::GL::glFormatElementByteCount(), height, CLinuxRendererGLES::CYuvPlane::id, m_pixelStoreKey, m_planeBuffer, m_planeBufferSize, m_textureTarget, CLinuxRendererGLES::CYuvPlane::texheight, and CLinuxRendererGLES::CYuvPlane::texwidth.
Referenced by UploadNV12Texture(), and UploadYV12Texture().
LoadShaders()
void CLinuxRendererGLES::LoadShaders (int field = FIELD_FULL) protected virtual
References Shaders::CGLSLShaderProgram::CompileAndLink(), CServiceBroker::GetSettingsComponent(), CBaseRenderer::GetShaderFormat(), LoadShadersHook(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_fullRange, m_passthroughHDR, m_pYUVBobShader, m_pYUVProgShader, m_reloadShaders, m_renderMethod, m_scalingMethod, m_srcPrimaries, m_toneMap, m_toneMapMethod, CVideoSettings::m_ToneMapMethod, CBaseRenderer::m_videoSettings, ReleaseShaders(), RENDER_GLSL, RENDER_METHOD_AUTO, RENDER_METHOD_GLSL, Shaders::GLES::BaseYUV2RGBGLSLShader::SetConvertFullColorRange(), CSettings::SETTING_VIDEOPLAYER_RENDERMETHOD, UpdateVideoFilter(), VS_SCALINGMETHOD_LANCZOS3_FAST, and VS_SCALINGMETHOD_SPLINE36_FAST.
Referenced by RenderSinglePass(), RenderToFBO(), and ValidateRenderTarget().
LoadShadersHook()
virtual bool CLinuxRendererGLES::LoadShadersHook () inline protected virtual
Reimplemented in CRendererMediaCodec, CRendererVAAPIGLES, CRendererVTB, and CRendererVTB.
Referenced by LoadShaders().
NextYV12Texture()
int CLinuxRendererGLES::NextYV12Texture () protected
References m_iYV12RenderBuffer, and m_NumYV12Buffers.
Register()
bool CLinuxRendererGLES::Register () static
References Create(), and VIDEOPLAYER::CRendererFactory::RegisterRenderer().
Referenced by CWinSystemIOS::CreateNewWindow(), CWinSystemTVOS::CreateNewWindow(), CWinSystemAndroid::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::InitWindowSystem(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::RefreshGLContext().
ReleaseBuffer()
void CLinuxRendererGLES::ReleaseBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
Reimplemented in CRendererMediaCodec, CRendererVAAPIGLES, CRendererVTB, and CRendererVTB.
References m_buffers, CVideoBuffer::Release(), and CLinuxRendererGLES::CPictureBuffer::videoBuffer.
Referenced by DeleteTexture(), and CRendererVAAPIGLES::ReleaseBuffer().
ReleaseShaders()
void CLinuxRendererGLES::ReleaseShaders () protected virtual
References m_pYUVBobShader, and m_pYUVProgShader.
Referenced by LoadShaders(), and ~CLinuxRendererGLES().
Render()
bool CLinuxRendererGLES::Render (unsigned int flags, int index) protected virtual
References AfterRenderHook(), FIELD_BOT, FIELD_FULL, FIELD_TOP, index(), m_currentField, m_renderMethod, m_renderQuality, RENDER_FLAG_BOT, RENDER_FLAG_TOP, RENDER_GLSL, RenderFromFBO(), RenderHook(), RenderSinglePass(), RenderToFBO(), RQ_LOW, RQ_MULTIPASS, RQ_SINGLEPASS, UpdateVideoFilter(), UploadTexture(), and VerifyGLState.
Referenced by RenderCapture(), and RenderUpdate().
RenderCapture()
bool CLinuxRendererGLES::RenderCapture (int index, CRenderCapture * capture) override virtual
Implements CBaseRenderer.
References CRenderCapture::BeginRender(), CRenderCapture::EndRender(), CRenderCapture::GetHeight(), CRenderCapture::GetRenderBuffer(), CRenderCapture::GetWidth(), CServiceBroker::GetWinSystem(), glMatrixModview, index(), CMatrixGLStack::Load(), m_bValidated, CBaseRenderer::m_destRect, CBaseRenderer::MarkDirty(), CMatrixGLStack::PopLoad(), CMatrixGLStack::Push(), Render(), RENDER_FLAG_NOOSD, CBaseRenderer::restoreRotatedCoords(), CBaseRenderer::saveRotatedCoords(), CMatrixGL::Scalef(), CRectGen< T >::SetRect(), CBaseRenderer::syncDestRectToRotatedPoints(), and CMatrixGL::Translatef().
RenderFromFBO()
void CLinuxRendererGLES::RenderFromFBO () protected
References Shaders::CGLSLShaderProgram::Disable(), Shaders::CGLSLShaderProgram::Enable(), CMatrixGLStack::Get(), Shaders::GLES::BaseVideoFilterShader::GetcoordLoc(), Shaders::GLES::BaseVideoFilterShader::GetTextureFilter(), Shaders::GLES::BaseVideoFilterShader::GetVertexLoc(), glMatrixModview, glMatrixProject, m_fbo, m_pVideoFilterShader, CBaseRenderer::m_rotatedDestCoords, m_scalingMethod, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, Shaders::GLES::BaseVideoFilterShader::SetAlpha(), Shaders::GLES::BaseVideoFilterShader::SetHeight(), Shaders::GLES::BaseVideoFilterShader::SetMatrices(), Shaders::GLES::BaseVideoFilterShader::SetSourceTexture(), Shaders::GLES::BaseVideoFilterShader::SetWidth(), VerifyGLState, VS_SCALINGMETHOD_NEAREST, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by Render().
RenderHook()
virtual bool CLinuxRendererGLES::RenderHook (int idx) inline protected virtual
Reimplemented in CRendererVAAPIGLES, and CRendererMediaCodec.
Referenced by Render().
RenderSinglePass()
void CLinuxRendererGLES::RenderSinglePass (int index, int field) protected
References Shaders::CGLSLShaderProgram::Disable(), CLinuxRendererGLES::CPictureBuffer::displayMetadata, Shaders::CGLSLShaderProgram::Enable(), FIELD_BOT, FIELD_FULL, FIELD_TOP, CLinuxRendererGLES::CPictureBuffer::fields, CMatrixGLStack::Get(), Shaders::GLES::BaseYUV2RGBGLSLShader::GetUcoordLoc(), Shaders::GLES::BaseYUV2RGBGLSLShader::GetVcoordLoc(), Shaders::GLES::BaseYUV2RGBGLSLShader::GetVertexLoc(), Shaders::GLES::BaseYUV2RGBGLSLShader::GetYcoordLoc(), glMatrixModview, glMatrixProject, CLinuxRendererGLES::CPictureBuffer::hasDisplayMetadata, CLinuxRendererGLES::CPictureBuffer::hasLightMetadata, index(), CLinuxRendererGLES::CPictureBuffer::lightMetadata, LoadShaders(), CVideoSettings::m_Brightness, m_buffers, CVideoSettings::m_Contrast, m_passthroughHDR, m_pYUVBobShader, m_pYUVProgShader, m_reloadShaders, CBaseRenderer::m_rotatedDestCoords, CLinuxRendererGLES::CPictureBuffer::m_srcBits, CLinuxRendererGLES::CPictureBuffer::m_srcColSpace, CLinuxRendererGLES::CPictureBuffer::m_srcFullRange, CLinuxRendererGLES::CPictureBuffer::m_srcPrimaries, m_srcPrimaries, CLinuxRendererGLES::CPictureBuffer::m_srcTextureBits, m_textureTarget, m_toneMap, m_toneMapMethod, CVideoSettings::m_ToneMapMethod, CVideoSettings::m_ToneMapParam, CBaseRenderer::m_videoSettings, YuvImage::MAX_PLANES, Shaders::GLES::BaseYUV2RGBGLSLShader::SetBlack(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetColParams(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetContrast(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetDisplayMetadata(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetField(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetHeight(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetMatrices(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetToneMapParam(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetWidth(), VerifyGLState, VS_TONEMAPMETHOD_OFF, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by Render().
RenderToFBO()
void CLinuxRendererGLES::RenderToFBO (int index, int field) protected
References Shaders::CGLSLShaderProgram::Disable(), CLinuxRendererGLES::CPictureBuffer::displayMetadata, Shaders::CGLSLShaderProgram::Enable(), FIELD_BOT, FIELD_TOP, CLinuxRendererGLES::CPictureBuffer::fields, CMatrixGLStack::Get(), Shaders::GLES::BaseYUV2RGBGLSLShader::GetUcoordLoc(), Shaders::GLES::BaseYUV2RGBGLSLShader::GetVcoordLoc(), Shaders::GLES::BaseYUV2RGBGLSLShader::GetVertexLoc(), CRenderSystemGLES::GetViewPort(), Shaders::GLES::BaseYUV2RGBGLSLShader::GetYcoordLoc(), glMatrixModview, glMatrixProject, CLinuxRendererGLES::CPictureBuffer::hasDisplayMetadata, CLinuxRendererGLES::CPictureBuffer::hasLightMetadata, index(), CLinuxRendererGLES::CPictureBuffer::lightMetadata, CMatrixGLStack::Load(), CMatrixGL::LoadIdentity(), LoadShaders(), CLog::Log(), LOGERROR, CVideoSettings::m_Brightness, m_buffers, CVideoSettings::m_Contrast, m_currentField, m_fbo, m_pYUVProgShader, m_reloadShaders, m_renderSystem, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, CLinuxRendererGLES::CPictureBuffer::m_srcBits, CLinuxRendererGLES::CPictureBuffer::m_srcColSpace, CLinuxRendererGLES::CPictureBuffer::m_srcFullRange, CLinuxRendererGLES::CPictureBuffer::m_srcPrimaries, m_srcPrimaries, CLinuxRendererGLES::CPictureBuffer::m_srcTextureBits, m_textureTarget, m_toneMap, m_toneMapMethod, CVideoSettings::m_ToneMapMethod, CVideoSettings::m_ToneMapParam, CBaseRenderer::m_videoSettings, YuvImage::MAX_PLANES, Shaders::CShaderProgram::OK(), CMatrixGL::Ortho2D(), CMatrixGLStack::PopLoad(), CMatrixGLStack::Push(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetBlack(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetColParams(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetContrast(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetDisplayMetadata(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetField(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetHeight(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetMatrices(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetToneMapParam(), CRenderSystemGLES::SetViewPort(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetWidth(), VerifyGLState, and VS_TONEMAPMETHOD_OFF.
Referenced by Render().
RenderUpdate()
void CLinuxRendererGLES::RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override virtual
Implements CBaseRenderer.
References ClearBackBuffer(), DrawBlackBars(), FIELD_FULL, CLinuxRendererGLES::CPictureBuffer::fields, CLinuxRendererGLES::CYuvPlane::id, index(), IsGuiLayer(), m_bConfigured, m_buffers, m_iYV12RenderBuffer, m_pYUVBobShader, m_pYUVProgShader, CBaseRenderer::ManageRenderArea(), Render(), RenderUpdateVideo(), Shaders::GLES::BaseYUV2RGBGLSLShader::SetAlpha(), ValidateRenderTarget(), and VerifyGLState.
RenderUpdateVideo()
void CLinuxRendererGLES::RenderUpdateVideo (bool clear, unsigned int flags = 0, unsigned int alpha = 255) protected virtual
References IsGuiLayer(), and m_bConfigured.
Referenced by RenderUpdate().
SetBufferSize()
void CLinuxRendererGLES::SetBufferSize (int numBuffers) inline override virtual
Reimplemented from CBaseRenderer.
References m_NumYV12Buffers.
SetTextureFilter()
void CLinuxRendererGLES::SetTextureFilter (GLenum method) protected
References f, FIELD_BOT, FIELD_FULL, CLinuxRendererGLES::CPictureBuffer::fields, CLinuxRendererGLES::CYuvPlane::id, m_buffers, m_NumYV12Buffers, m_textureTarget, and VerifyGLState.
Referenced by UpdateVideoFilter().
SkipUploadYV12()
virtual bool CLinuxRendererGLES::SkipUploadYV12 (int index) inline protected virtual
Supports() [1/2]
bool CLinuxRendererGLES::Supports (ERENDERFEATURE feature) const override virtual
Reimplemented from CBaseRenderer.
References RENDERFEATURE_BRIGHTNESS, RENDERFEATURE_CONTRAST, RENDERFEATURE_GAMMA, RENDERFEATURE_NOISE, RENDERFEATURE_NONLINSTRETCH, RENDERFEATURE_PIXEL_RATIO, RENDERFEATURE_POSTPROCESS, RENDERFEATURE_ROTATION, RENDERFEATURE_SHARPNESS, RENDERFEATURE_STRETCH, RENDERFEATURE_TONEMAP, RENDERFEATURE_VERTICAL_SHIFT, and RENDERFEATURE_ZOOM.
Referenced by UpdateVideoFilter().
Supports() [2/2]
bool CLinuxRendererGLES::Supports (ESCALINGMETHOD method) const override virtual
Implements CBaseRenderer.
References CRenderSystemBase::GetRenderVersion(), CServiceBroker::GetSettingsComponent(), CRectGen< T >::Height(), CBaseRenderer::m_destRect, m_renderMethod, m_renderSystem, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, RENDER_GLSL, CSettings::SETTING_VIDEOPLAYER_HQSCALERS, VS_SCALINGMETHOD_CUBIC_0_075, VS_SCALINGMETHOD_CUBIC_0_1, VS_SCALINGMETHOD_CUBIC_B_SPLINE, VS_SCALINGMETHOD_CUBIC_CATMULL, VS_SCALINGMETHOD_CUBIC_MITCHELL, VS_SCALINGMETHOD_LANCZOS2, VS_SCALINGMETHOD_LANCZOS3, VS_SCALINGMETHOD_LANCZOS3_FAST, VS_SCALINGMETHOD_LINEAR, VS_SCALINGMETHOD_NEAREST, VS_SCALINGMETHOD_SPLINE36, VS_SCALINGMETHOD_SPLINE36_FAST, and CRectGen< T >::Width().
SupportsMultiPassRendering()
bool CLinuxRendererGLES::SupportsMultiPassRendering () override virtual
Implements CBaseRenderer.
UnInit()
void CLinuxRendererGLES::UnInit () override virtual
Implements CBaseRenderer.
References DeleteTexture(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, m_bConfigured, m_bValidated, m_fbo, m_passthroughHDR, NUM_BUFFERS, and CWinSystemBase::SetHDR().
Referenced by ~CLinuxRendererGLES().
Update()
void CLinuxRendererGLES::Update () override virtual
Implements CBaseRenderer.
References m_bConfigured, CBaseRenderer::ManageRenderArea(), and ValidateRenderTarget().
UpdateVideoFilter()
void CLinuxRendererGLES::UpdateVideoFilter () protected
References Shaders::CGLSLShaderProgram::CompileAndLink(), CBaseRenderer::GetVideoRect(), CRectGen< T >::Height(), CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, m_fbo, m_pVideoFilterShader, m_reloadShaders, m_renderMethod, m_renderQuality, m_scalingMethod, CVideoSettings::m_ScalingMethod, m_scalingMethodGui, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, CBaseRenderer::m_videoSettings, m_viewRect, RENDER_GLSL, RQ_MULTIPASS, RQ_SINGLEPASS, SetTextureFilter(), Supports(), VerifyGLState, VS_SCALINGMETHOD_BICUBIC_SOFTWARE, VS_SCALINGMETHOD_CUBIC_0_075, VS_SCALINGMETHOD_CUBIC_0_1, VS_SCALINGMETHOD_CUBIC_B_SPLINE, VS_SCALINGMETHOD_CUBIC_CATMULL, VS_SCALINGMETHOD_CUBIC_MITCHELL, VS_SCALINGMETHOD_LANCZOS2, VS_SCALINGMETHOD_LANCZOS3, VS_SCALINGMETHOD_LANCZOS3_FAST, VS_SCALINGMETHOD_LANCZOS_SOFTWARE, VS_SCALINGMETHOD_LINEAR, VS_SCALINGMETHOD_NEAREST, VS_SCALINGMETHOD_SINC8, VS_SCALINGMETHOD_SINC_SOFTWARE, VS_SCALINGMETHOD_SPLINE36, VS_SCALINGMETHOD_SPLINE36_FAST, and CRectGen< T >::Width().
Referenced by LoadShaders(), Render(), and ValidateRenderTarget().
UploadNV12Texture()
bool CLinuxRendererGLES::UploadNV12Texture (int index) protected
References YuvImage::bpp, CalculateTextureSourceRects(), YuvImage::cshift_x, YuvImage::cshift_y, FIELD_BOT, FIELD_FULL, FIELD_TOP, fields, CLinuxRendererGLES::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGLES::CPictureBuffer::image, LoadPlane(), m_buffers, m_currentField, YuvImage::plane, YuvImage::stride, VerifyGLState, and YuvImage::width.
Referenced by UploadTexture(), and CRendererVAAPIGLES::UploadTexture().
UploadTexture()
bool CLinuxRendererGLES::UploadTexture (int index) protected virtual
Reimplemented in CRendererMediaCodec, CRendererVAAPIGLES, CRendererVTB, and CRendererVTB.
References CVideoBuffer::GetPlanes(), CVideoBuffer::GetStrides(), CLinuxRendererGLES::CPictureBuffer::image, index(), CLinuxRendererGLES::CPictureBuffer::loaded, m_buffers, CBaseRenderer::m_format, YuvImage::plane, YuvImage::stride, UploadNV12Texture(), UploadYV12Texture(), and CLinuxRendererGLES::CPictureBuffer::videoBuffer.
Referenced by Render().
UploadYV12Texture()
bool CLinuxRendererGLES::UploadYV12Texture (int index) protected
References YuvImage::bpp, CalculateTextureSourceRects(), YuvImage::cshift_x, YuvImage::cshift_y, FIELD_FULL, CLinuxRendererGLES::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGLES::CPictureBuffer::image, LoadPlane(), m_buffers, YuvImage::plane, YuvImage::stride, VerifyGLState, and YuvImage::width.
Referenced by UploadTexture().
ValidateRenderTarget()
bool CLinuxRendererGLES::ValidateRenderTarget () protected virtual
References CreateTexture(), DeleteTexture(), LoadShaders(), m_bValidated, m_NumYV12Buffers, m_renderMethod, NUM_BUFFERS, and UpdateVideoFilter().
Referenced by RenderUpdate(), and Update().
Member Data Documentation
fbo
CFrameBufferObject CLinuxRendererGLES::fbo
FIELD_BOT
const int CLinuxRendererGLES::FIELD_BOT {2} static protected
Referenced by CalculateTextureSourceRects(), CreateNV12Texture(), CreateYV12Texture(), Render(), CRendererMediaCodec::RenderHook(), RenderSinglePass(), RenderToFBO(), SetTextureFilter(), and UploadNV12Texture().
FIELD_FULL
const int CLinuxRendererGLES::FIELD_FULL {0} static protected
Referenced by CalculateTextureSourceRects(), CreateNV12Texture(), CreateYV12Texture(), DeleteNV12Texture(), CRendererVAAPIGLES::DeleteTexture(), DeleteYV12Texture(), Render(), CRendererMediaCodec::RenderHook(), RenderSinglePass(), RenderUpdate(), SetTextureFilter(), UploadNV12Texture(), and UploadYV12Texture().
FIELD_TOP
const int CLinuxRendererGLES::FIELD_TOP {1} static protected
Referenced by Render(), CRendererMediaCodec::RenderHook(), RenderSinglePass(), RenderToFBO(), and UploadNV12Texture().
height
float CLinuxRendererGLES::height {0.0}
Referenced by LoadPlane().
m_bConfigured
bool CLinuxRendererGLES::m_bConfigured {false} protected
Referenced by Configure(), IsConfigured(), RenderUpdate(), RenderUpdateVideo(), UnInit(), and Update().
m_buffers
CPictureBuffer CLinuxRendererGLES::m_buffers[NUM_BUFFERS] protected
Referenced by CRendererMediaCodec::AddVideoPicture(), AddVideoPicture(), CalculateTextureSourceRects(), CreateNV12Texture(), CRendererMediaCodec::CreateTexture(), CRendererVAAPIGLES::CreateTexture(), CreateYV12Texture(), DeleteNV12Texture(), CRendererVAAPIGLES::DeleteTexture(), DeleteYV12Texture(), CRendererMediaCodec::ReleaseBuffer(), ReleaseBuffer(), CRendererMediaCodec::RenderHook(), RenderSinglePass(), RenderToFBO(), RenderUpdate(), SetTextureFilter(), UploadNV12Texture(), UploadTexture(), CRendererVAAPIGLES::UploadTexture(), and UploadYV12Texture().
m_bValidated
bool CLinuxRendererGLES::m_bValidated {false} protected
Referenced by Configure(), Flush(), RenderCapture(), UnInit(), and ValidateRenderTarget().
m_clearColour
float CLinuxRendererGLES::m_clearColour {0.0f} protected
Referenced by ClearBackBufferQuad(), Configure(), and DrawBlackBars().
m_currentField
int CLinuxRendererGLES::m_currentField {FIELD_FULL} protected
Referenced by Render(), CRendererMediaCodec::RenderHook(), RenderToFBO(), and UploadNV12Texture().
[struct]
struct { ... } CLinuxRendererGLES::m_fbo
Referenced by Flush(), RenderFromFBO(), RenderToFBO(), UnInit(), and UpdateVideoFilter().
m_fullRange
bool CLinuxRendererGLES::m_fullRange protected
Referenced by CLinuxRendererGLES(), and LoadShaders().
m_iYV12RenderBuffer
int CLinuxRendererGLES::m_iYV12RenderBuffer {0} protected
Referenced by Flush(), NextYV12Texture(), and RenderUpdate().
m_NumYV12Buffers
int CLinuxRendererGLES::m_NumYV12Buffers {0} protected
Referenced by Flush(), NextYV12Texture(), SetBufferSize(), SetTextureFilter(), and ValidateRenderTarget().
m_passthroughHDR
bool CLinuxRendererGLES::m_passthroughHDR = false protected
Referenced by Configure(), LoadShaders(), RenderSinglePass(), and UnInit().
m_pixelStoreKey
GLenum CLinuxRendererGLES::m_pixelStoreKey {0} protected
Referenced by CLinuxRendererGLES(), and LoadPlane().
m_planeBuffer
unsigned char* CLinuxRendererGLES::m_planeBuffer = nullptr protected
Referenced by LoadPlane(), and ~CLinuxRendererGLES().
m_planeBufferSize
size_t CLinuxRendererGLES::m_planeBufferSize = 0 protected
Referenced by LoadPlane().
m_pVideoFilterShader
Shaders::GLES::BaseVideoFilterShader* CLinuxRendererGLES::m_pVideoFilterShader {nullptr} protected
Referenced by RenderFromFBO(), and UpdateVideoFilter().
m_pYUVBobShader
Shaders::GLES::BaseYUV2RGBGLSLShader* CLinuxRendererGLES::m_pYUVBobShader {nullptr} protected
Referenced by LoadShaders(), ReleaseShaders(), RenderSinglePass(), and RenderUpdate().
m_pYUVProgShader
Shaders::GLES::BaseYUV2RGBGLSLShader* CLinuxRendererGLES::m_pYUVProgShader {nullptr} protected
Referenced by LoadShaders(), ReleaseShaders(), RenderSinglePass(), RenderToFBO(), and RenderUpdate().
m_reloadShaders
int CLinuxRendererGLES::m_reloadShaders {0} protected
Referenced by LoadShaders(), RenderSinglePass(), RenderToFBO(), and UpdateVideoFilter().
m_renderMethod
int CLinuxRendererGLES::m_renderMethod {RENDER_GLSL} protected
Referenced by LoadShaders(), CRendererMediaCodec::LoadShadersHook(), Render(), Supports(), UpdateVideoFilter(), and ValidateRenderTarget().
m_renderQuality
RenderQuality CLinuxRendererGLES::m_renderQuality {RQ_SINGLEPASS} protected
Referenced by Render(), and UpdateVideoFilter().
m_renderSystem
CRenderSystemGLES* CLinuxRendererGLES::m_renderSystem {nullptr} protected
Referenced by ClearBackBufferQuad(), CLinuxRendererGLES(), DrawBlackBars(), RenderToFBO(), and Supports().
m_scalingMethod
ESCALINGMETHOD CLinuxRendererGLES::m_scalingMethod {VS_SCALINGMETHOD_LINEAR} protected
Referenced by LoadShaders(), RenderFromFBO(), and UpdateVideoFilter().
m_scalingMethodGui
ESCALINGMETHOD CLinuxRendererGLES::m_scalingMethodGui {VS_SCALINGMETHOD_MAX} protected
Referenced by Configure(), and UpdateVideoFilter().
m_srcPrimaries
AVColorPrimaries CLinuxRendererGLES::m_srcPrimaries protected
Referenced by Configure(), LoadShaders(), RenderSinglePass(), and RenderToFBO().
m_textureTarget
GLenum CLinuxRendererGLES::m_textureTarget = GL_TEXTURE_2D protected
Referenced by CalculateTextureSourceRects(), CreateNV12Texture(), CreateYV12Texture(), LoadPlane(), CRendererMediaCodec::LoadShadersHook(), RenderSinglePass(), RenderToFBO(), SetTextureFilter(), and CRendererVAAPIGLES::UploadTexture().
m_toneMap
bool CLinuxRendererGLES::m_toneMap = false protected
Referenced by Configure(), LoadShaders(), RenderSinglePass(), and RenderToFBO().
m_toneMapMethod
ETONEMAPMETHOD CLinuxRendererGLES::m_toneMapMethod = VS_TONEMAPMETHOD_OFF protected
Referenced by LoadShaders(), RenderSinglePass(), and RenderToFBO().
m_viewRect
CRect CLinuxRendererGLES::m_viewRect protected
Referenced by UpdateVideoFilter().
width
float CLinuxRendererGLES::width {0.0}
The documentation for this class was generated from the following files:
LinuxRendererGLES.h
LinuxRendererGLES.cpp