Kodi Documentation: UPNP::CUPnPPlayer Class Reference
UPNP::CUPnPPlayer Class Reference
#include <UPnPPlayer.h>
Public Member Functions
CUPnPPlayer (IPlayerCallback &callback, const char *uuid)
~CUPnPPlayer () override
bool OpenFile (const CFileItem &file, const CPlayerOptions &options) override
bool QueueNextFile (const CFileItem &file) override
bool CloseFile (bool reopen=false) override
bool IsPlaying () const override
void Pause () override
bool HasVideo () const override
bool HasAudio () const override
void Seek (bool bPlus, bool bLargeStep, bool bChapterOverride) override
void SeekPercentage (float fPercent=0) override
void SetVolume (float volume) override
int SeekChapter (int iChapter) override
void SeekTime (int64_t iTime=0) override
void SetSpeed (float speed=0) override
bool IsCaching () const override
int GetCacheLevel () const override
bool OnAction (const CAction &action) override
int PlayFile (const CFileItem &file, const CPlayerOptions &options, XbmcThreads::EndTime<> &timeout)
Public Member Functions inherited from IPlayer
IPlayer (IPlayerCallback &callback)
virtual ~IPlayer ()=default
virtual bool Initialize (TiXmlElement *pConfig)
virtual void OnNothingToQueueNotify ()
virtual bool CanPause () const
virtual bool HasGame () const
virtual bool HasRDS () const
virtual bool HasID3 () const
virtual bool IsPassthrough () const
virtual bool CanSeek () const
virtual bool SeekScene (Direction seekDirection)
virtual float GetCachePercentage () const
virtual void SetMute (bool bOnOff)
virtual void SetDynamicRangeCompression (long drc)
virtual void SetAVDelay (float fValue=0.0f)
virtual float GetAVDelay ()
virtual void SetSubTitleDelay (float fValue=0.0f)
virtual float GetSubTitleDelay ()
virtual int GetSubtitleCount () const
virtual int GetSubtitle ()
virtual void GetSubtitleStreamInfo (int index, SubtitleStreamInfo &info) const
virtual void SetSubtitle (int iStream)
virtual bool GetSubtitleVisible () const
virtual void SetSubtitleVisible (bool bVisible)
virtual void SetSubtitleVerticalPosition (int value, bool save)
Set the subtitle vertical position, it depends on current screen resolution.
virtual void AddSubtitle (const std::string &strSubPath)
Adds the subtitle(s) provided by the given file to the available player streams and actives the first of the added stream(s). E.g., vob subs can contain multiple streams.
virtual int GetAudioStreamCount () const
virtual int GetAudioStream ()
virtual void SetAudioStream (int iStream)
virtual void GetAudioStreamInfo (int index, AudioStreamInfo &info) const
virtual int GetVideoStream () const
virtual int GetVideoStreamCount () const
virtual void GetVideoStreamInfo (int streamId, VideoStreamInfo &info) const
virtual void SetVideoStream (int iStream)
virtual int GetPrograms (std::vector< ProgramInfo > &programs)
virtual void SetProgram (int progId)
virtual int GetProgramsCount () const
virtual bool HasTeletextCache () const
virtual std::shared_ptr< TextCacheStruct_t > GetTeletextCache ()
virtual void LoadPage (int p, int sp, unsigned char *buffer)
virtual int GetChapterCount () const
virtual int GetChapter () const
virtual void GetChapterName (std::string &strChapterName, int chapterIdx=-1) const
virtual int64_t GetChapterPos (int chapterIdx=-1) const
virtual bool SeekTimeRelative (int64_t iTime)
virtual void SetTime (int64_t time)
Sets the current time. This can be used for injecting the current time. This is not to be confused with a seek. It just can be used if endless streams contain multiple tracks in reality (like with airtunes)
virtual void SetTotalTime (int64_t time)
Set the total time in milliseconds this can be used for injecting the duration in case its not available in the underlaying decoder (airtunes for example)
virtual void SetTempo (float tempo)
virtual bool SupportsTempo () const
virtual void FrameAdvance (int frames)
virtual bool IsInMenu () const
virtual MenuType GetSupportedMenuType () const
Get the supported menu type.
virtual std::string GetPlayerState ()
virtual bool SetPlayerState (const std::string &state)
virtual void GetAudioCapabilities (std::vector< IPlayerAudioCaps > &caps) const
Define the audio capabilities of the player.
virtual void GetSubtitleCapabilities (std::vector< IPlayerSubtitleCaps > &caps) const
Define the subtitle capabilities of the player.
virtual void Render (bool clear, uint32_t alpha=255, bool gui=true)
hook into render loop of render thread
virtual void FlushRenderer ()
virtual void SetRenderViewMode (int mode, float zoom, float par, float shift, bool stretch)
virtual float GetRenderAspectRatio () const
virtual void TriggerUpdateResolution ()
virtual bool IsRenderingVideo () const
virtual void GetRects (CRect &source, CRect &dest, CRect &view) const
virtual unsigned int GetOrientation () const
virtual bool Supports (EINTERLACEMETHOD method) const
virtual EINTERLACEMETHOD GetDeinterlacingMethodDefault () const
virtual bool Supports (ESCALINGMETHOD method) const
virtual bool Supports (ERENDERFEATURE feature) const
virtual unsigned int RenderCaptureAlloc ()
virtual void RenderCaptureRelease (unsigned int captureId)
virtual void RenderCapture (unsigned int captureId, unsigned int width, unsigned int height, int flags)
virtual bool RenderCaptureGetPixels (unsigned int captureId, unsigned int millis, uint8_t *buffer, unsigned int size)
virtual CVideoSettings GetVideoSettings () const
virtual void SetVideoSettings (CVideoSettings &settings)
virtual bool HasGameAgent () const
Check if any players are playing a game.
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Member Functions
bool IsPaused () const
int64_t GetTime ()
int64_t GetTotalTime ()
float GetPercentage ()
void Process () override
void OnExit () override
Private Attributes
PLT_MediaController * m_control = nullptr
std::unique_ptr< CUPnPPlayerController > m_delegate
std::string m_current_uri
std::string m_current_meta
bool m_started = false
bool m_stopremote = false
bool m_hasVideo {false}
bool m_hasAudio {false}
XbmcThreads::EndTime m_updateTimer
Logger m_logger
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Public Attributes inherited from IPlayer
std::string m_name
std::string m_type
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from IPlayer
IPlayerCallback & m_callback
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CUPnPPlayer()
UPNP::CUPnPPlayer::CUPnPPlayer (IPlayerCallback & callback, const char * uuid)
References UPNP::CUPnP::GetInstance(), m_control, m_delegate, m_logger, UPNP::CUPnP::m_MediaController, and UPNP::CUPnP::RegisterUserdata().
~CUPnPPlayer()
UPNP::CUPnPPlayer::~CUPnPPlayer () override
References CloseFile(), m_delegate, and UPNP::CUPnP::UnregisterUserdata().
Member Function Documentation
CloseFile()
bool UPNP::CUPnPPlayer::CloseFile (bool reopen = false) override virtual
Implements IPlayer.
References CServiceBroker::GetDataCacheCore(), IPlayer::m_callback, m_control, m_delegate, m_logger, m_started, m_stopremote, IPlayerCallback::OnPlayBackStopped(), CDataCacheCore::Reset(), and CThread::StopThread().
Referenced by Process(), and ~CUPnPPlayer().
GetCacheLevel()
int UPNP::CUPnPPlayer::GetCacheLevel () const inline override virtual
Reimplemented from IPlayer.
GetPercentage()
float UPNP::CUPnPPlayer::GetPercentage () private
References GetTime(), GetTotalTime(), and int64_t().
GetTime()
int64_t UPNP::CUPnPPlayer::GetTime () private
References m_delegate.
Referenced by GetPercentage(), and Process().
GetTotalTime()
int64_t UPNP::CUPnPPlayer::GetTotalTime () private
References m_delegate.
Referenced by GetPercentage(), Process(), and SeekPercentage().
HasAudio()
bool UPNP::CUPnPPlayer::HasAudio () const inline override virtual
Implements IPlayer.
References m_hasAudio.
HasVideo()
bool UPNP::CUPnPPlayer::HasVideo () const inline override virtual
Implements IPlayer.
References m_hasVideo.
IsCaching()
bool UPNP::CUPnPPlayer::IsCaching () const inline override virtual
Reimplemented from IPlayer.
IsPaused()
bool UPNP::CUPnPPlayer::IsPaused () const private
References m_delegate.
Referenced by Pause(), Process(), and SetSpeed().
IsPlaying()
bool UPNP::CUPnPPlayer::IsPlaying () const override virtual
Reimplemented from IPlayer.
References m_delegate.
Referenced by OnAction().
OnAction()
bool UPNP::CUPnPPlayer::OnAction (const CAction & action) override virtual
Reimplemented from IPlayer.
References ACTION_STOP, IsPlaying(), m_stopremote, and KODI::MESSAGING::HELPERS::ShowYesNoDialogText().
OnExit()
void UPNP::CUPnPPlayer::OnExit () override private virtual
Reimplemented from CThread.
References IPlayer::m_callback, m_started, and IPlayerCallback::OnPlayBackEnded().
OpenFile()
bool UPNP::CUPnPPlayer::OpenFile (const CFileItem & file, const CPlayerOptions & options) override virtual
Reimplemented from IPlayer.
References CThread::Create(), KODI::MUSIC::IsAudio(), CThread::IsRunning(), IPlayer::m_callback, m_control, m_delegate, m_hasAudio, m_hasVideo, m_logger, m_started, m_stopremote, m_updateTimer, IPlayerCallback::OnAVStarted(), IPlayerCallback::OnPlayBackStarted(), PlayFile(), and UPNP::WaitOnEvent().
Pause()
void UPNP::CUPnPPlayer::Pause () override virtual
Implements IPlayer.
References CDataCacheCore::GetInstance(), IsPaused(), IPlayer::m_callback, m_control, m_delegate, m_logger, IPlayerCallback::OnPlayBackPaused(), IPlayerCallback::OnPlayBackResumed(), and CDataCacheCore::SetSpeed().
PlayFile()
int UPNP::CUPnPPlayer::PlayFile (const CFileItem & file, const CPlayerOptions & options, XbmcThreads::EndTime<> & timeout)
References UPNP::BuildObject(), UPNP::EMEDIACONTROLLERQUIRKS_NONE, UPNP::EMEDIACONTROLLERQUIRKS_X_MKV, UPNP::GetMediaControllerQuirks(), UPNP::CUPnP::GetServer(), KODI::MUSIC::IsMusicDb(), m_control, m_delegate, m_logger, UPNP::UPnPPlayer, and UPNP::WaitOnEvent().
Referenced by OpenFile().
Process()
void UPNP::CUPnPPlayer::Process (void) override private virtual
Reimplemented from CThread.
References CloseFile(), CDataCacheCore::GetInstance(), CDataCacheCore::GetSpeed(), GetTime(), GetTotalTime(), IsPaused(), CThread::m_bStop, IPlayer::m_callback, m_delegate, m_logger, m_started, m_updateTimer, IPlayerCallback::OnPlayBackEnded(), IPlayerCallback::OnPlayBackPaused(), IPlayerCallback::OnPlayBackResumed(), CDataCacheCore::SetPlayTimes(), and CDataCacheCore::SetSpeed().
QueueNextFile()
bool UPNP::CUPnPPlayer::QueueNextFile (const CFileItem & file) override virtual
Reimplemented from IPlayer.
References UPNP::BuildObject(), UPNP::CUPnP::GetServer(), KODI::MUSIC::IsMusicDb(), m_control, m_delegate, m_logger, and UPNP::UPnPPlayer.
Seek()
void UPNP::CUPnPPlayer::Seek (bool bPlus, bool bLargeStep, bool bChapterOverride) override virtual
Implements IPlayer.
SeekChapter()
int UPNP::CUPnPPlayer::SeekChapter (int iChapter) inline override virtual
Reimplemented from IPlayer.
SeekPercentage()
void UPNP::CUPnPPlayer::SeekPercentage (float fPercent = 0) override virtual
Reimplemented from IPlayer.
References GetTotalTime(), int64_t(), and SeekTime().
SeekTime()
void UPNP::CUPnPPlayer::SeekTime (int64_t iTime = 0) override virtual
Reimplemented from IPlayer.
References CDataCacheCore::GetInstance(), m_control, m_delegate, m_logger, and CDataCacheCore::SeekFinished().
Referenced by SeekPercentage().
SetSpeed()
void UPNP::CUPnPPlayer::SetSpeed (float speed = 0) override virtual
Implements IPlayer.
References CDataCacheCore::GetInstance(), IsPaused(), IPlayer::m_callback, m_control, m_delegate, m_logger, IPlayerCallback::OnPlayBackResumed(), and CDataCacheCore::SetSpeed().
SetVolume()
void UPNP::CUPnPPlayer::SetVolume (float volume) override virtual
Reimplemented from IPlayer.
References CServiceBroker::GetSettingsComponent(), m_control, m_delegate, m_logger, and CSettings::SETTING_SERVICES_UPNPPLAYERVOLUMESYNC.
Member Data Documentation
m_control
PLT_MediaController* UPNP::CUPnPPlayer::m_control = nullptr private
Referenced by CloseFile(), CUPnPPlayer(), OpenFile(), Pause(), PlayFile(), QueueNextFile(), SeekTime(), SetSpeed(), and SetVolume().
m_current_meta
std::string UPNP::CUPnPPlayer::m_current_meta private
m_current_uri
std::string UPNP::CUPnPPlayer::m_current_uri private
m_delegate
std::unique_ptr<CUPnPPlayerController> UPNP::CUPnPPlayer::m_delegate private
Referenced by CloseFile(), CUPnPPlayer(), GetTime(), GetTotalTime(), IsPaused(), IsPlaying(), OpenFile(), Pause(), PlayFile(), Process(), QueueNextFile(), SeekTime(), SetSpeed(), SetVolume(), and ~CUPnPPlayer().
m_hasAudio
bool UPNP::CUPnPPlayer::m_hasAudio {false} private
Referenced by HasAudio(), and OpenFile().
m_hasVideo
bool UPNP::CUPnPPlayer::m_hasVideo {false} private
Referenced by HasVideo(), and OpenFile().
m_logger
Logger UPNP::CUPnPPlayer::m_logger private
Referenced by CloseFile(), CUPnPPlayer(), OpenFile(), Pause(), PlayFile(), Process(), QueueNextFile(), SeekTime(), SetSpeed(), and SetVolume().
m_started
bool UPNP::CUPnPPlayer::m_started = false private
Referenced by CloseFile(), OnExit(), OpenFile(), and Process().
m_stopremote
bool UPNP::CUPnPPlayer::m_stopremote = false private
Referenced by CloseFile(), OnAction(), and OpenFile().
m_updateTimer
XbmcThreads::EndTime UPNP::CUPnPPlayer::m_updateTimer private
Referenced by OpenFile(), and Process().
The documentation for this class was generated from the following files:
UPnPPlayer.h
UPnPPlayer.cpp