Kodi Documentation: CVideoSyncD3D Class Reference
CVideoSyncD3D Class Reference
#include <VideoSyncD3D.h>
Public Member Functions
CVideoSyncD3D (CVideoReferenceClock *clock)
bool Setup () override
void Run (CEvent &stopEvent) override
void Cleanup () override
float GetFps () override
void RefreshChanged () override
void OnLostDisplay () override
void OnResetDisplay () override
Public Member Functions inherited from CVideoSync
CVideoSync (CVideoReferenceClock *clock)
virtual ~CVideoSync ()=default
Private Attributes
volatile bool m_displayLost
volatile bool m_displayReset
CEvent m_lostEvent
DXGI_OUTPUT_DESC m_outputDesc {}
Microsoft::WRL::ComPtr< IDXGIFactory2 > m_factory
Additional Inherited Members
Protected Attributes inherited from CVideoSync
float m_fps
CVideoReferenceClock * m_refClock
Private Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
virtual void OnAppFocusChange (bool focus)
Constructor & Destructor Documentation
CVideoSyncD3D()
CVideoSyncD3D::CVideoSyncD3D (CVideoReferenceClock * clock) inline
Member Function Documentation
Cleanup()
void CVideoSyncD3D::Cleanup () override virtual
Implements CVideoSync.
References CLog::Log(), LOGDEBUG, m_lostEvent, and CEvent::Set().
GetFps()
float CVideoSyncD3D::GetFps () override virtual
Implements CVideoSync.
References CVideoSync::m_fps, and m_outputDesc.
Referenced by Run().
OnLostDisplay()
void CVideoSyncD3D::OnLostDisplay () override virtual
Reimplemented from IDispResource.
References m_displayLost, m_lostEvent, and CEvent::Wait().
OnResetDisplay()
void CVideoSyncD3D::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References m_displayReset.
RefreshChanged()
void CVideoSyncD3D::RefreshChanged () override virtual
Reimplemented from CVideoSync.
References m_displayReset.
Run()
void CVideoSyncD3D::Run (CEvent & stopEvent) override virtual
Implements CVideoSync.
References CurrentHostCounter(), CurrentHostFrequency(), CWIN32Util::FormatHRESULT(), DX::DeviceResources::Get(), GetFps(), int64_t(), LOGERROR, LOGWARNING, m_displayLost, m_displayReset, m_factory, CVideoSync::m_fps, m_lostEvent, m_outputDesc, CVideoSync::m_refClock, MathUtils::round_int(), CEvent::Set(), CEvent::Signaled(), KODI::TIME::Sleep(), and CVideoReferenceClock::UpdateClock().
Setup()
bool CVideoSyncD3D::Setup () override virtual
Implements CVideoSync.
References DX::DeviceResources::Get(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, m_displayLost, m_displayReset, m_factory, m_lostEvent, m_outputDesc, and CEvent::Reset().
Member Data Documentation
m_displayLost
volatile bool CVideoSyncD3D::m_displayLost private
Referenced by OnLostDisplay(), Run(), and Setup().
m_displayReset
volatile bool CVideoSyncD3D::m_displayReset private
Referenced by OnResetDisplay(), RefreshChanged(), Run(), and Setup().
m_factory
Microsoft::WRL::ComPtr<IDXGIFactory2> CVideoSyncD3D::m_factory private
Referenced by Run(), and Setup().
m_lostEvent
CEvent CVideoSyncD3D::m_lostEvent private
Referenced by Cleanup(), OnLostDisplay(), Run(), and Setup().
m_outputDesc
DXGI_OUTPUT_DESC CVideoSyncD3D::m_outputDesc {} private
Referenced by GetFps(), Run(), and Setup().
The documentation for this class was generated from the following files:
VideoSyncD3D.h
VideoSyncD3D.cpp