Kodi Documentation: xbmc.h File Reference
xbmc.h File Reference
#include <memory>
Functions
int XBMC_Run (bool renderGUI)
Function Documentation
XBMC_Run()
int XBMC_Run (bool renderGUI)
References CLSID_MMDeviceEnumerator, CXBMCApp::Deinitialize(), CMessagePrinter::DisplayError(), EXITCODE_QUIT, g_application, CXBMCApp::Get(), IID_IMMDeviceEnumerator, and CXBMCApp::Initialize().
Referenced by main(), CXBMCApp::run(), KODI::PLATFORM::WINDOWS10::App::Run(), and WinMain().