Kodi Documentation: CUDiskDevice Class Reference
CUDiskDevice Class Reference
#include <UDisksProvider.h>
Public Member Functions
CUDiskDevice (const char *DeviceKitUDI)
~CUDiskDevice ()=default
void Update ()
bool Mount ()
bool UnMount ()
bool IsApproved () const
Check if the device is approved/whitelisted.
MEDIA_DETECT::STORAGE::Type GetStorageType () const
Get the storage type of this device.
bool IsOptical () const
Check if the device is optical.
bool IsMounted () const
Check if the device is mounted.
bool IsSystemInternal () const
Check if the device is internal to the system.
const std::string & GetDisplayName () const
Get the device display name/label.
const std::string & GetMountPoint () const
Get the device mount point.
std::string ToString () const
Get a representation of the device as a readable string.
CMediaSource ToMediaShare () const
Get a representation of the device as a media share.
MEDIA_DETECT::STORAGE::StorageDevice ToStorageDevice () const
Get a representation of the device as a storage device abstraction.
Private Attributes
std::string m_UDI
std::string m_DeviceKitUDI
std::string m_MountPath
std::string m_FileSystem
std::string m_Label
bool m_isMounted
bool m_isMountedByUs
bool m_isRemovable
bool m_isPartition
bool m_isFileSystem
bool m_isSystemInternal
bool m_isOptical
int64_t m_PartitionSize
Constructor & Destructor Documentation
CUDiskDevice()
CUDiskDevice::CUDiskDevice (const char * DeviceKitUDI)
References m_isFileSystem, m_isMounted, m_isMountedByUs, m_isOptical, m_isPartition, m_isRemovable, m_isSystemInternal, m_PartitionSize, and Update().
~CUDiskDevice()
CUDiskDevice::~CUDiskDevice () default
Member Function Documentation
GetDisplayName()
const std::string & CUDiskDevice::GetDisplayName () const inline
Get the device display name/label.
Returns
the device display name/label
References m_Label.
Referenced by ToStorageDevice().
GetMountPoint()
const std::string & CUDiskDevice::GetMountPoint () const inline
Get the device mount point.
Returns
the device mount point
References m_MountPath.
Referenced by CUDisksProvider::DeviceAdded(), CUDisksProvider::Eject(), and ToStorageDevice().
GetStorageType()
MEDIA_DETECT::STORAGE::Type CUDiskDevice::GetStorageType () const
Get the storage type of this device.
Returns
the storage type (e.g. OPTICAL) or UNKNOWN if the type couldn't be detected
References IsOptical(), MEDIA_DETECT::STORAGE::OPTICAL, and MEDIA_DETECT::STORAGE::UNKNOWN.
Referenced by ToStorageDevice().
IsApproved()
bool CUDiskDevice::IsApproved () const
Check if the device is approved/whitelisted.
Returns
true if the device is approved/whitelisted, false otherwise
References m_FileSystem, m_isFileSystem, m_isMounted, m_isOptical, m_MountPath, and m_UDI.
Referenced by CUDisksProvider::DeviceAdded(), and CUDisksProvider::GetDisks().
IsMounted()
bool CUDiskDevice::IsMounted () const
Check if the device is mounted.
Returns
true if the device is mounted, false otherwise
References m_isMounted.
Referenced by CUDisksProvider::DeviceAdded(), CUDisksProvider::DeviceChanged(), and CUDisksProvider::DeviceRemoved().
IsOptical()
bool CUDiskDevice::IsOptical () const
Check if the device is optical.
Returns
true if the device is optical, false otherwise
References m_isOptical.
Referenced by CUDisksProvider::DeviceAdded(), CUDisksProvider::DeviceChanged(), and GetStorageType().
IsSystemInternal()
bool CUDiskDevice::IsSystemInternal () const
Check if the device is internal to the system.
Returns
true if the device is internal to the system, false otherwise
References m_isSystemInternal.
Referenced by CUDisksProvider::GetDisks().
Mount()
bool CUDiskDevice::Mount ()
References CDBusMessage::AppendArgument(), CLog::Log(), LOGDEBUG, m_DeviceKitUDI, m_isFileSystem, m_isMounted, m_isMountedByUs, m_isSystemInternal, m_MountPath, CDBusMessage::SendSystem(), and ToString().
Referenced by CUDisksProvider::DeviceAdded(), and CUDisksProvider::DeviceChanged().
ToMediaShare()
CMediaSource CUDiskDevice::ToMediaShare () const
Get a representation of the device as a media share.
Returns
the media share
References g_localizeStrings, CLocalizeStrings::Get(), CMediaSource::m_iDriveType, CMediaSource::m_ignore, m_isOptical, m_isSystemInternal, m_Label, m_MountPath, m_PartitionSize, CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::SOURCE_TYPE_OPTICAL_DISC, CMediaSource::SOURCE_TYPE_REMOVABLE, CMediaSource::strName, and CMediaSource::strPath.
Referenced by CUDisksProvider::GetDisks().
ToStorageDevice()
MEDIA_DETECT::STORAGE::StorageDevice CUDiskDevice::ToStorageDevice () const
Get a representation of the device as a storage device abstraction.
Returns
the storage device abstraction of the device
References GetDisplayName(), GetMountPoint(), GetStorageType(), MEDIA_DETECT::STORAGE::StorageDevice::label, MEDIA_DETECT::STORAGE::StorageDevice::path, and MEDIA_DETECT::STORAGE::StorageDevice::type.
Referenced by CUDisksProvider::DeviceAdded(), CUDisksProvider::DeviceChanged(), and CUDisksProvider::DeviceRemoved().
ToString()
std::string CUDiskDevice::ToString () const
Get a representation of the device as a readable string.
Returns
device as a string
References BOOL2SZ, m_DeviceKitUDI, m_FileSystem, m_isFileSystem, m_isMounted, m_isOptical, m_isPartition, m_isRemovable, and m_isSystemInternal.
Referenced by CUDisksProvider::DeviceAdded(), CUDisksProvider::DeviceChanged(), Mount(), and UnMount().
UnMount()
bool CUDiskDevice::UnMount ()
References CDBusMessage::AppendArgument(), CLog::Log(), LOGDEBUG, m_DeviceKitUDI, m_isFileSystem, m_isMounted, m_isMountedByUs, m_isSystemInternal, CDBusMessage::SendSystem(), and ToString().
Referenced by CUDisksProvider::Eject().
Update()
void CUDiskDevice::Update ()
References CVariant::asBoolean(), CVariant::asString(), CVariant::asUnsignedInteger(), CDBusUtil::GetAll(), CDBusUtil::GetVariant(), CVariant::isNull(), m_DeviceKitUDI, m_FileSystem, m_isFileSystem, m_isMounted, m_isOptical, m_isPartition, m_isRemovable, m_isSystemInternal, m_Label, m_MountPath, m_PartitionSize, and m_UDI.
Referenced by CUDiskDevice(), and CUDisksProvider::DeviceChanged().
Member Data Documentation
m_DeviceKitUDI
std::string CUDiskDevice::m_DeviceKitUDI private
Referenced by Mount(), ToString(), UnMount(), and Update().
m_FileSystem
std::string CUDiskDevice::m_FileSystem private
Referenced by IsApproved(), ToString(), and Update().
m_isFileSystem
bool CUDiskDevice::m_isFileSystem private
Referenced by CUDiskDevice(), IsApproved(), Mount(), ToString(), UnMount(), and Update().
m_isMounted
bool CUDiskDevice::m_isMounted private
Referenced by CUDiskDevice(), IsApproved(), IsMounted(), Mount(), ToString(), UnMount(), and Update().
m_isMountedByUs
bool CUDiskDevice::m_isMountedByUs private
Referenced by CUDiskDevice(), Mount(), and UnMount().
m_isOptical
bool CUDiskDevice::m_isOptical private
Referenced by CUDiskDevice(), IsApproved(), IsOptical(), ToMediaShare(), ToString(), and Update().
m_isPartition
bool CUDiskDevice::m_isPartition private
Referenced by CUDiskDevice(), ToString(), and Update().
m_isRemovable
bool CUDiskDevice::m_isRemovable private
Referenced by CUDiskDevice(), ToString(), and Update().
m_isSystemInternal
bool CUDiskDevice::m_isSystemInternal private
Referenced by CUDiskDevice(), IsSystemInternal(), Mount(), ToMediaShare(), ToString(), UnMount(), and Update().
m_Label
std::string CUDiskDevice::m_Label private
Referenced by GetDisplayName(), ToMediaShare(), and Update().
m_MountPath
std::string CUDiskDevice::m_MountPath private
Referenced by GetMountPoint(), IsApproved(), Mount(), ToMediaShare(), and Update().
m_PartitionSize
int64_t CUDiskDevice::m_PartitionSize private
Referenced by CUDiskDevice(), ToMediaShare(), and Update().
m_UDI
std::string CUDiskDevice::m_UDI private
Referenced by IsApproved(), and Update().
The documentation for this class was generated from the following files:
UDisksProvider.h
UDisksProvider.cpp