Kodi Documentation: DX::DeviceResources Class Reference
DX::DeviceResources Class Reference
#include <DeviceResources.h>
Classes
class CBackBuffer
Public Member Functions
DeviceResources ()
virtual ~DeviceResources ()
void Release ()
void ValidateDevice ()
void HandleDeviceLost (bool removed)
bool Begin ()
void Present ()
winrt::Windows::Foundation::Size GetOutputSize () const
winrt::Windows::Foundation::Size GetLogicalSize () const
void SetLogicalSize (float width, float height)
float GetDpi () const
void SetDpi (float dpi)
bool HasValidDevice () const
ID3D11Device1 * GetD3DDevice () const
ID3D11DeviceContext1 * GetD3DContext () const
ID3D11DeviceContext1 * GetImmediateContext () const
IDXGISwapChain1 * GetSwapChain () const
IDXGIFactory2 * GetIDXGIFactory2 () const
IDXGIAdapter1 * GetAdapter () const
ID3D11DepthStencilView * GetDSV () const
D3D_FEATURE_LEVEL GetDeviceFeatureLevel () const
CD3DTexture & GetBackBuffer ()
void GetOutput (IDXGIOutput **ppOutput) const
void GetCachedOutputAndDesc (IDXGIOutput **output, DXGI_OUTPUT_DESC *outputDesc) const
Retrieve current output and output description. Use cached data first to avoid delays due to dxgi internal multithreading synchronization.
DXGI_ADAPTER_DESC GetAdapterDesc () const
void GetDisplayMode (DXGI_MODE_DESC *mode) const
D3D11_VIEWPORT GetScreenViewport () const
void SetViewPort (D3D11_VIEWPORT &viewPort) const
void ReleaseBackBuffer ()
void CreateBackBuffer ()
void ResizeBuffers ()
bool SetFullScreen (bool fullscreen, RESOLUTION_INFO &res)
void ApplyDisplaySettings ()
HDR_STATUS ToggleHDR ()
void SetHdrMetaData (DXGI_HDR_METADATA_HDR10 &hdr10) const
void SetHdrColorSpace (const DXGI_COLOR_SPACE_TYPE colorSpace)
bool IsHDROutput () const
bool IsTransferPQ () const
void Register (ID3DResource *resource)
void Unregister (ID3DResource *resource)
void FinishCommandList (bool bExecute=true) const
void ClearDepthStencil () const
void ClearRenderTarget (ID3D11RenderTargetView *pRTView, float color[4]) const
void RegisterDeviceNotify (IDeviceNotify *deviceNotify)
bool IsStereoAvailable () const
bool IsStereoEnabled () const
void SetStereoIdx (byte idx)
void SetMonitor (HMONITOR monitor)
HMONITOR GetMonitor () const
bool IsNV12SharedTexturesSupported () const
bool IsDXVA2SharedDecoderSurfaces () const
bool IsSuperResolutionSupported () const
bool UseFence () const
DEBUG_INFO_RENDER GetDebugInfo () const
std::vector< DXGI_COLOR_SPACE_TYPE > GetSwapChainColorSpaces () const
bool SetMultithreadProtected (bool enabled) const
bool IsGCNOrOlder () const
Static Public Member Functions
static std::shared_ptr< DX::DeviceResources > Get ()
Private Member Functions
HRESULT CreateSwapChain (DXGI_SWAP_CHAIN_DESC1 &desc, DXGI_SWAP_CHAIN_FULLSCREEN_DESC &fsDesc, IDXGISwapChain1 **ppSwapChain) const
void DestroySwapChain ()
void CreateDeviceIndependentResources ()
void CreateDeviceResources ()
void CreateWindowSizeDependentResources ()
void UpdateRenderTargetSize ()
void OnDeviceLost (bool removed)
void OnDeviceRestored ()
void HandleOutputChange (const std::function< bool(DXGI_OUTPUT_DESC)> &cmpFunc)
bool CreateFactory ()
void CheckNV12SharedTexturesSupport ()
VideoDriverInfo GetVideoDriverVersion () const
void CheckDXVA2SharedDecoderSurfaces ()
Private Attributes
HWND m_window { nullptr }
Microsoft::WRL::ComPtr< IDXGIFactory2 > m_dxgiFactory
Microsoft::WRL::ComPtr< IDXGIAdapter1 > m_adapter
Microsoft::WRL::ComPtr< IDXGIOutput1 > m_output
DXGI_OUTPUT_DESC m_outputDesc {}
Microsoft::WRL::ComPtr< ID3D11Device1 > m_d3dDevice
Microsoft::WRL::ComPtr< ID3D11DeviceContext1 > m_d3dContext
Microsoft::WRL::ComPtr< ID3D11DeviceContext1 > m_deferrContext
Microsoft::WRL::ComPtr< IDXGISwapChain1 > m_swapChain
CBackBuffer m_backBufferTex
Microsoft::WRL::ComPtr< ID3D11DepthStencilView > m_d3dDepthStencilView
D3D11_VIEWPORT m_screenViewport
D3D_FEATURE_LEVEL m_d3dFeatureLevel
winrt::Windows::Foundation::Size m_outputSize
winrt::Windows::Foundation::Size m_logicalSize
float m_dpi
float m_effectiveDpi
IDeviceNotify * m_deviceNotify
Concurrency::critical_section m_criticalSection
Concurrency::critical_section m_resourceSection
std::vector< ID3DResource * > m_resources
bool m_stereoEnabled
bool m_bDeviceCreated
bool m_IsHDROutput
bool m_IsTransferPQ
bool m_NV12SharedTexturesSupport {false}
bool m_DXVA2SharedDecoderSurfaces {false}
bool m_DXVASuperResolutionSupport {false}
bool m_DXVA2UseFence {false}
Constructor & Destructor Documentation
DeviceResources()
DX::DeviceResources::DeviceResources ()
~DeviceResources()
DX::DeviceResources::~DeviceResources () virtual default
Member Function Documentation
ApplyDisplaySettings()
void DX::DeviceResources::ApplyDisplaySettings ()
References LOGDEBUG.
Begin()
bool DX::DeviceResources::Begin ()
CheckDXVA2SharedDecoderSurfaces()
void DX::DeviceResources::CheckDXVA2SharedDecoderSurfaces () private
References CSysInfo::Desktop, CSysInfo::GetWindowsDeviceFamily(), CSysInfo::IsWindowsVersionAtLeast(), VideoDriverInfo::Log(), LOGINFO, VideoDriverInfo::majorVersion, PCIV_AMD, PCIV_Intel, PCIV_NVIDIA, VideoDriverInfo::valid, and CSysInfo::WindowsVersionWin10_1703.
CheckNV12SharedTexturesSupport()
void DX::DeviceResources::CheckNV12SharedTexturesSupport () private
References CSysInfo::Desktop, CSysInfo::GetWindowsDeviceFamily(), and LOGINFO.
ClearDepthStencil()
void DX::DeviceResources::ClearDepthStencil () const
ClearRenderTarget()
void DX::DeviceResources::ClearRenderTarget (ID3D11RenderTargetView * pRTView, float color[4]) const
References color.
CreateBackBuffer()
void DX::DeviceResources::CreateBackBuffer ()
References CHECK_ERR, LOGDEBUG, and LOGERROR.
CreateDeviceIndependentResources()
void DX::DeviceResources::CreateDeviceIndependentResources () private
CreateDeviceResources()
void DX::DeviceResources::CreateDeviceResources () private
References CHECK_ERR, FAILED, CWIN32Util::FormatHRESULT(), KODI::PLATFORM::WINDOWS::FromW(), DX::GetFeatureLevelDescription(), CSysInfo::IsWindowsVersionAtLeast(), LOGDEBUG, LOGERROR, LOGFATAL, LOGINFO, and CSysInfo::WindowsVersionWin10.
CreateFactory()
bool DX::DeviceResources::CreateFactory () private
References RETURN_ERR.
CreateSwapChain()
HRESULT DX::DeviceResources::CreateSwapChain (DXGI_SWAP_CHAIN_DESC1 & desc, DXGI_SWAP_CHAIN_FULLSCREEN_DESC & fsDesc, IDXGISwapChain1 ** ppSwapChain) const private
References RETURN_ERR.
CreateWindowSizeDependentResources()
void DX::DeviceResources::CreateWindowSizeDependentResources () private
DestroySwapChain()
void DX::DeviceResources::DestroySwapChain () private
FinishCommandList()
void DX::DeviceResources::FinishCommandList (bool bExecute = true) const
References FAILED, and LOGERROR.
Get()
std::shared_ptr< DX::DeviceResources > DX::DeviceResources::Get () static
Referenced by CWinSystemWin10::AdjustWindow(), CGUIShaderDX::ApplyChanges(), CGUIShaderDX::ApplyStateBlock(), CD3DEffect::BeginPass(), CRenderCaptureDX::BeginRender(), CD3DVertexShader::BindShader(), CD3DPixelShader::BindShader(), CScreenshotSurfaceWindows::Capture(), CWinSystemWin10::ChangeResolution(), CConvolutionShaderSeparable::ClearIntermediateRenderTarget(), CRendererSoftware::Configure(), CGUIFontTTFDX::CopyCharToTexture(), CD3DVertexShader::Create(), CD3DPixelShader::Create(), CD3DPixelShader::Create(), CD3DVertexShader::Create(), CD3DBuffer::CreateBuffer(), CGUIShaderDX::CreateBuffers(), DXVA::CContext::CreateContext(), COutputShader::CreateDitherView(), CD3DEffect::CreateEffect(), CWinShader::CreateInputLayout(), CD3DVertexShader::CreateInternal(), CD3DPixelShader::CreateInternal(), CD3DTexture::CreateInternal(), COutputShader::CreateLUTView(), CWinSystemWin10DX::CreateNewWindow(), CWinSystemWin32DX::CreateNewWindow(), CGUIShaderDX::CreateSamplers(), CGUIFontTTFDX::CreateStaticIndexBuffer(), CGUIShaderDX::Draw(), CGUIShaderDX::DrawIndexed(), CGUIShaderDX::DrawQuad(), CRenderCaptureDX::EndRender(), CWinShader::Execute(), CRendererHQ::FinalOutput(), CWinSystemWin10::FinishWindowResize(), CGUIFontTTFDX::FirstBegin(), CD3DTexture::GenerateMipmaps(), CD3DTexture::GetRenderTargetInternal(), DXVA::CVideoBufferShared::GetResource(), GetScreenPoint(), CD3DTexture::GetShaderResource(), CRendererShaders::CRenderBufferImpl::GetView(), CRendererDXVA::GetWeight(), HasAMDH264SDiBug(), HasATIMP2Bug(), HasVP3WidthBug(), CGUIRenderingControl::InitCallback(), DXVA::CVideoBufferShared::Initialize(), DXVA::CProcessorHD::InitProcessor(), CRendererShaders::IsHWPicSupported(), IsL41LimitedATI(), CGUIFontTTFDX::LastEnd(), CD3DTexture::LockRect(), DXVA::CEnumeratorHD::LogAndListConversions(), DXVA::CEnumeratorHD::LogSupportedConversions(), CD3DBuffer::Map(), CD3DBuffer::OnDestroyDevice(), CWinEventsWin10::OnDisplayContentsInvalidated(), CDisplaySettings::OnSettingChanging(), DXVA::CDecoder::Open(), DXVA::CDecoder::OpenDecoder(), DXVA::CEnumeratorHD::OpenEnumerator(), DXVA::CProcessorHD::OpenProcessor(), CRenderBuffer::QueueCopyFromGPU(), CRenderCaptureDX::ReadOut(), CGUIFontTTFDX::ReallocTexture(), CRendererSoftware::CRenderBufferImpl::ReleasePicture(), CSlideShowPicDX::Render(), OVERLAY::COverlayQuadsDX::Render(), OVERLAY::COverlayImageDX::Render(), CRendererShaders::RenderImpl(), DXVA::CContext::Reset(), CGUIShaderDX::RestoreBuffers(), CVideoSyncD3D::Run(), CD3DTexture::SaveTexture(), CConvolutionShader1Pass::SetShaderParameters(), COutputShader::SetShaderParameters(), CYUV2RGBShader::SetShaderParameters(), CGUIShaderDX::SetShaderViews(), CConvolutionShaderSeparable::SetStepParams(), CWinShader::SetTarget(), CVideoSyncD3D::Setup(), CRendererHQ::Supports(), DXVA::CProcessorHD::TryEnableVideoSuperResolution(), CD3DVertexShader::UnbindShader(), CD3DPixelShader::UnbindShader(), CD3DTexture::UnlockRect(), CD3DBuffer::Unmap(), CGUIFontTTFDX::UpdateDynamicVertexBuffer(), CSlideShowPicDX::UpdateVertexBuffer(), CWinEventsWin10::UpdateWindowSize(), CRendererSoftware::CRenderBufferImpl::UploadBuffer(), CRendererShaders::CRenderBufferImpl::UploadFromGPU(), and CRendererSoftware::~CRendererSoftware().
GetAdapter()
IDXGIAdapter1 * DX::DeviceResources::GetAdapter () const inline
References m_adapter.
GetAdapterDesc()
DXGI_ADAPTER_DESC DX::DeviceResources::GetAdapterDesc () const
References CSysInfo::GetWindowsDeviceFamily(), PCIV_AMD, and CSysInfo::Xbox.
GetBackBuffer()
CD3DTexture & DX::DeviceResources::GetBackBuffer () inline
References m_backBufferTex.
GetCachedOutputAndDesc()
void DX::DeviceResources::GetCachedOutputAndDesc (IDXGIOutput ** output, DXGI_OUTPUT_DESC * outputDesc) const
Retrieve current output and output description. Use cached data first to avoid delays due to dxgi internal multithreading synchronization.
Parameters
output The output
outputDesc The output description
References LOGWARNING.
GetD3DContext()
ID3D11DeviceContext1 * DX::DeviceResources::GetD3DContext () const inline
References m_deferrContext.
GetD3DDevice()
ID3D11Device1 * DX::DeviceResources::GetD3DDevice () const inline
References m_d3dDevice.
GetDebugInfo()
DEBUG_INFO_RENDER DX::DeviceResources::GetDebugInfo () const
References DX::DXGIFormatToShortString(), max, and DEBUG_INFO_RENDER::renderFlags.
GetDeviceFeatureLevel()
D3D_FEATURE_LEVEL DX::DeviceResources::GetDeviceFeatureLevel () const inline
References m_d3dFeatureLevel.
GetDisplayMode()
void DX::DeviceResources::GetDisplayMode (DXGI_MODE_DESC * mode) const
References DX::ConvertDipsToPixels().
GetDpi()
float DX::DeviceResources::GetDpi () const inline
References m_effectiveDpi.
GetDSV()
ID3D11DepthStencilView * DX::DeviceResources::GetDSV () const inline
References m_d3dDepthStencilView.
GetIDXGIFactory2()
IDXGIFactory2 * DX::DeviceResources::GetIDXGIFactory2 () const inline
References m_dxgiFactory.
GetImmediateContext()
ID3D11DeviceContext1 * DX::DeviceResources::GetImmediateContext () const inline
References m_d3dContext.
GetLogicalSize()
winrt::Windows::Foundation::Size DX::DeviceResources::GetLogicalSize () const inline
References m_logicalSize.
GetMonitor()
HMONITOR DX::DeviceResources::GetMonitor () const
GetOutput()
void DX::DeviceResources::GetOutput (IDXGIOutput ** ppOutput) const
References FAILED.
GetOutputSize()
winrt::Windows::Foundation::Size DX::DeviceResources::GetOutputSize () const inline
References m_outputSize.
GetScreenViewport()
D3D11_VIEWPORT DX::DeviceResources::GetScreenViewport () const inline
References m_screenViewport.
GetSwapChain()
IDXGISwapChain1 * DX::DeviceResources::GetSwapChain () const inline
References m_swapChain.
GetSwapChainColorSpaces()
std::vector< DXGI_COLOR_SPACE_TYPE > DX::DeviceResources::GetSwapChainColorSpaces () const
References CWIN32Util::FormatHRESULT(), and LOGDEBUG.
GetVideoDriverVersion()
VideoDriverInfo DX::DeviceResources::GetVideoDriverVersion () const private
References CWIN32Util::FormatVideoDriverInfo(), CWIN32Util::GetVideoDriverInfo(), and CWIN32Util::GetVideoDriverInfoDX().
HandleDeviceLost()
void DX::DeviceResources::HandleDeviceLost (bool removed)
References CServiceBroker::GetAppMessenger(), and TMSG_EXECUTE_BUILT_IN.
HandleOutputChange()
void DX::DeviceResources::HandleOutputChange (const std::function< bool(DXGI_OUTPUT_DESC)> & cmpFunc) private
References KODI::PLATFORM::WINDOWS::FromW(), and LOGDEBUG.
HasValidDevice()
bool DX::DeviceResources::HasValidDevice () const inline
References m_bDeviceCreated.
IsDXVA2SharedDecoderSurfaces()
bool DX::DeviceResources::IsDXVA2SharedDecoderSurfaces () const inline
References m_DXVA2SharedDecoderSurfaces.
IsGCNOrOlder()
bool DX::DeviceResources::IsGCNOrOlder () const
References CSysInfo::GetWindowsDeviceFamily(), CWIN32Util::IsDriverVersionAtLeast(), PCIV_AMD, VideoDriverInfo::valid, VideoDriverInfo::vendorId, VideoDriverInfo::version, and CSysInfo::Xbox.
IsHDROutput()
bool DX::DeviceResources::IsHDROutput () const inline
References m_IsHDROutput.
IsNV12SharedTexturesSupported()
bool DX::DeviceResources::IsNV12SharedTexturesSupported () const inline
References m_NV12SharedTexturesSupport.
IsStereoAvailable()
bool DX::DeviceResources::IsStereoAvailable () const
IsStereoEnabled()
bool DX::DeviceResources::IsStereoEnabled () const inline
References m_stereoEnabled.
IsSuperResolutionSupported()
bool DX::DeviceResources::IsSuperResolutionSupported () const inline
References m_DXVASuperResolutionSupport.
IsTransferPQ()
bool DX::DeviceResources::IsTransferPQ () const inline
References m_IsTransferPQ.
OnDeviceLost()
void DX::DeviceResources::OnDeviceLost (bool removed) private
References CServiceBroker::GetGUI(), GUI_MSG_NOTIFY_ALL, and GUI_MSG_RENDERER_LOST.
OnDeviceRestored()
void DX::DeviceResources::OnDeviceRestored () private
References CServiceBroker::GetGUI(), GUI_MSG_NOTIFY_ALL, and GUI_MSG_RENDERER_RESET.
Present()
void DX::DeviceResources::Present ()
Register()
void DX::DeviceResources::Register (ID3DResource * resource)
RegisterDeviceNotify()
void DX::DeviceResources::RegisterDeviceNotify (IDeviceNotify * deviceNotify)
Release()
void DX::DeviceResources::Release ()
ReleaseBackBuffer()
void DX::DeviceResources::ReleaseBackBuffer ()
References LOGDEBUG.
ResizeBuffers()
void DX::DeviceResources::ResizeBuffers ()
References CHECK_ERR, DX::DXGIColorSpaceTypeToString(), DX::DXGIFormatToString(), FAILED, CWinSystemBase::GetGfxContext(), CServiceBroker::GetLogging(), CServiceBroker::GetSettingsComponent(), CGraphicContext::GetStereoMode(), CWIN32Util::GetWindowsHDRStatus(), CServiceBroker::GetWinSystem(), HDR_ON, HDR_UNSUPPORTED, CSysInfo::IsWindowsVersionAtLeast(), LOGDEBUG, LOGERROR, LOGINFO, LOGVIDEO, LOGWARNING, PCIV_AMD, RENDER_STEREO_MODE_HARDWAREBASED, RENDER_STEREO_MODE_SPLIT_HORIZONTAL, CGraphicContext::SetStereoMode(), CSettings::SETTING_VIDEOSCREEN_10BITSURFACES, and CSysInfo::WindowsVersionWin10.
SetDpi()
void DX::DeviceResources::SetDpi (float dpi)
References DX::DisplayMetrics::Dpi100.
SetFullScreen()
bool DX::DeviceResources::SetFullScreen (bool fullscreen, RESOLUTION_INFO & res)
References D3DPRESENTFLAG_INTERLACED, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fRefreshRate, CWinSystemBase::GetGfxContext(), CGraphicContext::GetStereoMode(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, CLog::Log(), LOGDEBUG, DX::RationalToFloat(), and RENDER_STEREO_MODE_HARDWAREBASED.
SetHdrColorSpace()
void DX::DeviceResources::SetHdrColorSpace (const DXGI_COLOR_SPACE_TYPE colorSpace)
References DX::DXGIColorSpaceTypeToString(), LOGDEBUG, and LOGERROR.
SetHdrMetaData()
void DX::DeviceResources::SetHdrMetaData (DXGI_HDR_METADATA_HDR10 & hdr10) const
References LOGDEBUG, LOGERROR, and LOGINFO.
SetLogicalSize()
void DX::DeviceResources::SetLogicalSize (float width, float height)
References LOGDEBUG.
SetMonitor()
void DX::DeviceResources::SetMonitor (HMONITOR monitor)
SetMultithreadProtected()
bool DX::DeviceResources::SetMultithreadProtected (bool enabled) const
SetStereoIdx()
void DX::DeviceResources::SetStereoIdx (byte idx) inline
References m_backBufferTex, and DX::DeviceResources::CBackBuffer::SetViewIdx().
SetViewPort()
void DX::DeviceResources::SetViewPort (D3D11_VIEWPORT & viewPort) const
ToggleHDR()
HDR_STATUS DX::DeviceResources::ToggleHDR ()
References CSysInfo::GetWindowsDeviceFamily(), HDR_ON, HDR_TOGGLE_FAILED, LOGDEBUG, CWIN32Util::ToggleWindowsHDR(), and CSysInfo::Xbox.
Unregister()
void DX::DeviceResources::Unregister (ID3DResource * resource)
UpdateRenderTargetSize()
void DX::DeviceResources::UpdateRenderTargetSize () private
References DX::ConvertDipsToPixels(), DX::DisplayMetrics::DpiThreshold, DX::DisplayMetrics::HeightThreshold, DX::DisplayMetrics::SupportHighResolutions, and DX::DisplayMetrics::WidthThreshold.
UseFence()
bool DX::DeviceResources::UseFence () const inline
References m_DXVA2UseFence.
ValidateDevice()
void DX::DeviceResources::ValidateDevice ()
References FAILED.
Member Data Documentation
m_adapter
Microsoft::WRL::ComPtr<IDXGIAdapter1> DX::DeviceResources::m_adapter private
Referenced by GetAdapter().
m_backBufferTex
CBackBuffer DX::DeviceResources::m_backBufferTex private
Referenced by GetBackBuffer(), and SetStereoIdx().
m_bDeviceCreated
bool DX::DeviceResources::m_bDeviceCreated private
Referenced by HasValidDevice().
m_criticalSection
Concurrency::critical_section DX::DeviceResources::m_criticalSection private
m_d3dContext
Microsoft::WRL::ComPtr<ID3D11DeviceContext1> DX::DeviceResources::m_d3dContext private
Referenced by GetImmediateContext().
m_d3dDepthStencilView
Microsoft::WRL::ComPtr<ID3D11DepthStencilView> DX::DeviceResources::m_d3dDepthStencilView private
Referenced by GetDSV().
m_d3dDevice
Microsoft::WRL::ComPtr<ID3D11Device1> DX::DeviceResources::m_d3dDevice private
Referenced by GetD3DDevice().
m_d3dFeatureLevel
D3D_FEATURE_LEVEL DX::DeviceResources::m_d3dFeatureLevel private
Referenced by GetDeviceFeatureLevel().
m_deferrContext
Microsoft::WRL::ComPtr<ID3D11DeviceContext1> DX::DeviceResources::m_deferrContext private
Referenced by GetD3DContext().
m_deviceNotify
IDeviceNotify* DX::DeviceResources::m_deviceNotify private
m_dpi
float DX::DeviceResources::m_dpi private
m_dxgiFactory
Microsoft::WRL::ComPtr<IDXGIFactory2> DX::DeviceResources::m_dxgiFactory private
Referenced by GetIDXGIFactory2().
m_DXVA2SharedDecoderSurfaces
bool DX::DeviceResources::m_DXVA2SharedDecoderSurfaces {false} private
Referenced by IsDXVA2SharedDecoderSurfaces().
m_DXVA2UseFence
bool DX::DeviceResources::m_DXVA2UseFence {false} private
Referenced by UseFence().
m_DXVASuperResolutionSupport
bool DX::DeviceResources::m_DXVASuperResolutionSupport {false} private
Referenced by IsSuperResolutionSupported().
m_effectiveDpi
float DX::DeviceResources::m_effectiveDpi private
Referenced by GetDpi().
m_IsHDROutput
bool DX::DeviceResources::m_IsHDROutput private
Referenced by IsHDROutput().
m_IsTransferPQ
bool DX::DeviceResources::m_IsTransferPQ private
Referenced by IsTransferPQ().
m_logicalSize
winrt::Windows::Foundation::Size DX::DeviceResources::m_logicalSize private
Referenced by GetLogicalSize().
m_NV12SharedTexturesSupport
bool DX::DeviceResources::m_NV12SharedTexturesSupport {false} private
Referenced by IsNV12SharedTexturesSupported().
m_output
Microsoft::WRL::ComPtr<IDXGIOutput1> DX::DeviceResources::m_output private
m_outputDesc
DXGI_OUTPUT_DESC DX::DeviceResources::m_outputDesc {} private
m_outputSize
winrt::Windows::Foundation::Size DX::DeviceResources::m_outputSize private
Referenced by GetOutputSize().
m_resources
std::vector<ID3DResource*> DX::DeviceResources::m_resources private
m_resourceSection
Concurrency::critical_section DX::DeviceResources::m_resourceSection private
m_screenViewport
D3D11_VIEWPORT DX::DeviceResources::m_screenViewport private
Referenced by GetScreenViewport().
m_stereoEnabled
bool DX::DeviceResources::m_stereoEnabled private
Referenced by IsStereoEnabled().
m_swapChain
Microsoft::WRL::ComPtr<IDXGISwapChain1> DX::DeviceResources::m_swapChain private
Referenced by GetSwapChain().
m_window
HWND DX::DeviceResources::m_window { nullptr } private
The documentation for this class was generated from the following files:
DeviceResources.h
DeviceResources.cpp