Kodi Documentation: anonymous_namespace{PluginDirectory.cpp} Namespace Reference
anonymous_namespace{PluginDirectory.cpp} Namespace Reference
Functions
std::string GetOriginalPluginPath (const CFileItem &item)
Get the plugin path from a CFileItem.
Variables
const unsigned int maxPluginResolutions = 5
Function Documentation
GetOriginalPluginPath()
std::string anonymous_namespace{PluginDirectory.cpp}::GetOriginalPluginPath (const CFileItem & item)
Get the plugin path from a CFileItem.
Parameters
item CFileItem where to get the path.
Returns
The plugin path if found otherwise an empty string.
References CFileItem::GetDynPath(), CFileItem::GetPath(), and URIUtils::IsPlugin().
Variable Documentation
maxPluginResolutions
const unsigned int anonymous_namespace{PluginDirectory.cpp}::maxPluginResolutions = 5