Kodi Documentation: CNetworkServices Class Reference
CNetworkServices Class Reference
#include <NetworkServices.h>
Public Types
enum ESERVERS {
ES_WEBSERVER = 1 , ES_AIRPLAYSERVER , ES_JSONRPCSERVER , ES_UPNPRENDERER ,
ES_UPNPSERVER , ES_EVENTSERVER , ES_ZEROCONF , ES_WSDISCOVERY
}
Public Member Functions
CNetworkServices ()
~CNetworkServices () override
bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting is being changed.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode) override
The given setting needs to be updated.
void Start ()
void Stop (bool bWait)
bool StartServer (enum ESERVERS server, bool start)
bool StartWebserver ()
bool IsWebserverRunning ()
bool StopWebserver ()
bool StartAirPlayServer ()
bool IsAirPlayServerRunning ()
bool StopAirPlayServer (bool bWait)
bool StartAirTunesServer ()
bool IsAirTunesServerRunning ()
bool StopAirTunesServer (bool bWait)
bool StartJSONRPCServer ()
bool IsJSONRPCServerRunning ()
bool StopJSONRPCServer (bool bWait)
bool StartEventServer ()
bool IsEventServerRunning ()
bool StopEventServer (bool bWait, bool promptuser)
bool RefreshEventServer ()
bool StartUPnP ()
bool StopUPnP (bool bWait)
bool StartUPnPClient ()
bool IsUPnPClientRunning ()
bool StopUPnPClient ()
bool StartUPnPController ()
bool IsUPnPControllerRunning ()
bool StopUPnPController ()
bool StartUPnPRenderer ()
bool IsUPnPRendererRunning ()
bool StopUPnPRenderer ()
bool StartUPnPServer ()
bool IsUPnPServerRunning ()
bool StopUPnPServer ()
bool StartRss ()
bool IsRssRunning ()
bool StopRss ()
bool StartZeroconf ()
bool IsZeroconfRunning ()
bool StopZeroconf ()
bool StartWSDiscovery ()
bool IsWSDiscoveryRunning ()
bool StopWSDiscovery ()
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Private Member Functions
CNetworkServices (const CNetworkServices &)
CNetworkServices const & operator= (CNetworkServices const &)
bool ValidatePort (int port)
Private Attributes
std::shared_ptr< CSettings > m_settings
Member Enumeration Documentation
ESERVERS
enum CNetworkServices::ESERVERS
Enumerator
ES_WEBSERVER
ES_AIRPLAYSERVER
ES_JSONRPCSERVER
ES_UPNPRENDERER
ES_UPNPSERVER
ES_EVENTSERVER
ES_ZEROCONF
ES_WSDISCOVERY
Constructor & Destructor Documentation
CNetworkServices() [1/2]
CNetworkServices::CNetworkServices ()
References CServiceBroker::GetSettingsComponent(), CSettings::SETTING_SERVICES_AIRPLAY, CSettings::SETTING_SERVICES_AIRPLAYPASSWORD, CSettings::SETTING_SERVICES_AIRPLAYVIDEOSUPPORT, CSettings::SETTING_SERVICES_AIRPLAYVOLUMECONTROL, CSettings::SETTING_SERVICES_ESALLINTERFACES, CSettings::SETTING_SERVICES_ESCONTINUOUSDELAY, CSettings::SETTING_SERVICES_ESENABLED, CSettings::SETTING_SERVICES_ESINITIALDELAY, CSettings::SETTING_SERVICES_ESPORT, CSettings::SETTING_SERVICES_UPNP, CSettings::SETTING_SERVICES_UPNPCONTROLLER, CSettings::SETTING_SERVICES_UPNPRENDERER, CSettings::SETTING_SERVICES_UPNPSERVER, CSettings::SETTING_SERVICES_USEAIRPLAYPASSWORD, CSettings::SETTING_SERVICES_WEBSERVER, CSettings::SETTING_SERVICES_WEBSERVERAUTHENTICATION, CSettings::SETTING_SERVICES_WEBSERVERPASSWORD, CSettings::SETTING_SERVICES_WEBSERVERPORT, CSettings::SETTING_SERVICES_WEBSERVERSSL, CSettings::SETTING_SERVICES_WEBSERVERUSERNAME, CSettings::SETTING_SERVICES_WSDISCOVERY, CSettings::SETTING_SERVICES_ZEROCONF, CSettings::SETTING_SMB_LEGACYSECURITY, CSettings::SETTING_SMB_MAXPROTOCOL, CSettings::SETTING_SMB_MINPROTOCOL, CSettings::SETTING_SMB_WINSSERVER, and CSettings::SETTING_SMB_WORKGROUP.
~CNetworkServices()
CNetworkServices::~CNetworkServices () override
References JSONRPC::CJSONRPC::Cleanup(), and m_settings.
CNetworkServices() [2/2]
CNetworkServices::CNetworkServices (const CNetworkServices &) private
Member Function Documentation
IsAirPlayServerRunning()
bool CNetworkServices::IsAirPlayServerRunning ()
References CAirPlayServer::IsRunning().
Referenced by OnSettingChanging(), StartAirPlayServer(), and StopAirPlayServer().
IsAirTunesServerRunning()
bool CNetworkServices::IsAirTunesServerRunning ()
References CAirTunesServer::IsRunning().
Referenced by OnSettingChanging(), StartAirTunesServer(), and StopAirTunesServer().
IsEventServerRunning()
bool CNetworkServices::IsEventServerRunning ()
References EVENTSERVER::CEventServer::GetInstance(), and EVENTSERVER::CEventServer::Running().
Referenced by RefreshEventServer(), StartEventServer(), and StopEventServer().
IsJSONRPCServerRunning()
bool CNetworkServices::IsJSONRPCServerRunning ()
References JSONRPC::CTCPServer::IsRunning().
Referenced by StartJSONRPCServer(), and StopJSONRPCServer().
IsRssRunning()
bool CNetworkServices::IsRssRunning ()
References CRssManager::GetInstance(), and CRssManager::IsActive().
Referenced by StartRss(), and StopRss().
IsUPnPClientRunning()
bool CNetworkServices::IsUPnPClientRunning ()
Referenced by StartUPnPClient(), and StopUPnPClient().
IsUPnPControllerRunning()
bool CNetworkServices::IsUPnPControllerRunning ()
Referenced by StartUPnPController(), and StopUPnPController().
IsUPnPRendererRunning()
bool CNetworkServices::IsUPnPRendererRunning ()
Referenced by StopUPnPRenderer().
IsUPnPServerRunning()
bool CNetworkServices::IsUPnPServerRunning ()
Referenced by StopUPnPServer().
IsWebserverRunning()
bool CNetworkServices::IsWebserverRunning ()
Referenced by OnSettingChanging(), StartWebserver(), and StopWebserver().
IsWSDiscoveryRunning()
bool CNetworkServices::IsWSDiscoveryRunning ()
References CServiceBroker::GetWSDiscovery(), and WSDiscovery::IWSDiscovery::IsRunning().
Referenced by StartWSDiscovery(), and StopWSDiscovery().
IsZeroconfRunning()
bool CNetworkServices::IsZeroconfRunning ()
References CZeroconf::GetInstance(), and CZeroconf::IsStarted().
Referenced by StartZeroconf(), and StopZeroconf().
OnSettingChanged()
void CNetworkServices::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Todo:
General way of handling setting changes that require restart
Reimplemented from ISettingCallback.
References CServiceBroker::GetAppMessenger(), m_settings, CSettings::SETTING_SMB_LEGACYSECURITY, CSettings::SETTING_SMB_MAXPROTOCOL, CSettings::SETTING_SMB_MINPROTOCOL, CSettings::SETTING_SMB_WINSSERVER, CSettings::SETTING_SMB_WORKGROUP, KODI::MESSAGING::HELPERS::ShowYesNoDialogText(), and TMSG_RESTARTAPP.
OnSettingChanging()
bool CNetworkServices::OnSettingChanging (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting is being changed.
This callback is triggered whenever the value of a setting is being changed. The given CSetting already contains the new value and the handler of the callback has the possibility to allow or revert changing the value of the setting. In case of a revert OnSettingChanging() is called again to inform all listeners that the value change has been reverted.
Parameters
setting The setting whose value is being changed (already containing the changed value)
Returns
True if the new value is acceptable otherwise false
Reimplemented from ISettingCallback.
References XBMCHelper::Configure(), XBMCHelper::GetInstance(), GetValue(), IsAirPlayServerRunning(), IsAirTunesServerRunning(), IsWebserverRunning(), m_settings, RefreshEventServer(), CAirPlayServer::SetCredentials(), CSettings::SETTING_SERVICES_AIRPLAY, CSettings::SETTING_SERVICES_AIRPLAYPASSWORD, CSettings::SETTING_SERVICES_AIRPLAYVIDEOSUPPORT, CSettings::SETTING_SERVICES_ESALLINTERFACES, CSettings::SETTING_SERVICES_ESCONTINUOUSDELAY, CSettings::SETTING_SERVICES_ESENABLED, CSettings::SETTING_SERVICES_ESINITIALDELAY, CSettings::SETTING_SERVICES_ESPORT, CSettings::SETTING_SERVICES_UPNP, CSettings::SETTING_SERVICES_UPNPCONTROLLER, CSettings::SETTING_SERVICES_UPNPRENDERER, CSettings::SETTING_SERVICES_UPNPSERVER, CSettings::SETTING_SERVICES_USEAIRPLAYPASSWORD, CSettings::SETTING_SERVICES_WEBSERVER, CSettings::SETTING_SERVICES_WEBSERVERAUTHENTICATION, CSettings::SETTING_SERVICES_WEBSERVERPASSWORD, CSettings::SETTING_SERVICES_WEBSERVERPORT, CSettings::SETTING_SERVICES_WEBSERVERSSL, CSettings::SETTING_SERVICES_WEBSERVERUSERNAME, CSettings::SETTING_SERVICES_WSDISCOVERY, CSettings::SETTING_SERVICES_ZEROCONF, KODI::MESSAGING::HELPERS::ShowOKDialogText(), KODI::MESSAGING::HELPERS::ShowYesNoDialogText(), StartAirPlayServer(), StartAirTunesServer(), StartEventServer(), StartJSONRPCServer(), StartUPnPClient(), StartUPnPController(), StartUPnPRenderer(), StartUPnPServer(), StartWebserver(), StartWSDiscovery(), StartZeroconf(), StopAirPlayServer(), StopAirTunesServer(), StopEventServer(), StopJSONRPCServer(), StopUPnPClient(), StopUPnPController(), StopUPnPRenderer(), StopUPnPServer(), StopWebserver(), StopWSDiscovery(), StopZeroconf(), and ValidatePort().
OnSettingUpdate()
bool CNetworkServices::OnSettingUpdate (const std::shared_ptr< CSetting > & setting, const char * oldSettingId, const TiXmlNode * oldSettingNode) override virtual
The given setting needs to be updated.
This callback is triggered when a setting needs to be updated because its value is outdated. This only happens when initially loading the value of a setting and will not be triggered afterwards.
Parameters
setting The setting which needs to be updated.
oldSettingId The id of the previous setting.
oldSettingNode The old setting node
Returns
True if the setting has been successfully updated otherwise false
Reimplemented from ISettingCallback.
References m_settings, CSettings::SETTING_SERVICES_WEBSERVER, CSettings::SETTING_SERVICES_WEBSERVERPASSWORD, CSettings::SETTING_SERVICES_WEBSERVERPORT, and CSettings::SETTING_SERVICES_WEBSERVERUSERNAME.
operator=()
CNetworkServices const & CNetworkServices::operator= (CNetworkServices const &) private
RefreshEventServer()
bool CNetworkServices::RefreshEventServer ()
References EVENTSERVER::CEventServer::GetInstance(), IsEventServerRunning(), m_settings, EVENTSERVER::CEventServer::RefreshSettings(), and CSettings::SETTING_SERVICES_ESENABLED.
Referenced by OnSettingChanging().
Start()
void CNetworkServices::Start ()
References CGUIWindowManager::ActivateWindow(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), m_settings, CGUIDialogKaiToast::QueueNotification(), CSettings::SETTING_SERVICES_ESENABLED, CSettings::SETTING_SERVICES_UPNP, CSettings::SETTING_SERVICES_WEBSERVER, CSettings::SETTING_SERVICES_WEBSERVERAUTHENTICATION, CSettings::SETTING_SERVICES_WEBSERVERPASSWORD, KODI::MESSAGING::HELPERS::ShowOKDialogText(), StartAirPlayServer(), StartAirTunesServer(), StartEventServer(), StartJSONRPCServer(), StartRss(), StartUPnP(), StartWebserver(), StartWSDiscovery(), StartZeroconf(), CGUIDialogKaiToast::Warning, and WINDOW_SETTINGS_SERVICE.
StartAirPlayServer()
bool CNetworkServices::StartAirPlayServer ()
References AIRPLAY_SERVER_VERSION_STR, CSysInfo::GetDeviceName(), CNetworkBase::GetFirstConnectedInterface(), CZeroconf::GetInstance(), CNetworkInterface::GetMacAddress(), CServiceBroker::GetNetwork(), CServiceBroker::GetSettingsComponent(), IsAirPlayServerRunning(), m_settings, CZeroconf::PublishService(), CAirPlayServer::SetCredentials(), CSettings::SETTING_SERVICES_AIRPLAY, CSettings::SETTING_SERVICES_AIRPLAYPASSWORD, CSettings::SETTING_SERVICES_AIRPLAYVIDEOSUPPORT, CSettings::SETTING_SERVICES_USEAIRPLAYPASSWORD, and CAirPlayServer::StartServer().
Referenced by OnSettingChanging(), and Start().
StartAirTunesServer()
bool CNetworkServices::StartAirTunesServer ()
References CServiceBroker::GetNetwork(), CServiceBroker::GetSettingsComponent(), IsAirTunesServerRunning(), CLog::Log(), LOGERROR, m_settings, CSettings::SETTING_SERVICES_AIRPLAY, CSettings::SETTING_SERVICES_AIRPLAYPASSWORD, CSettings::SETTING_SERVICES_USEAIRPLAYPASSWORD, and CAirTunesServer::StartServer().
Referenced by OnSettingChanging(), and Start().
StartEventServer()
bool CNetworkServices::StartEventServer ()
References EVENTSERVER::CEventServer::GetInstance(), IsEventServerRunning(), CLog::Log(), LOGERROR, m_settings, CSettings::SETTING_SERVICES_ESENABLED, and EVENTSERVER::CEventServer::StartServer().
Referenced by OnSettingChanging(), and Start().
StartJSONRPCServer()
bool CNetworkServices::StartJSONRPCServer ()
References CSysInfo::GetDeviceName(), CZeroconf::GetInstance(), CServiceBroker::GetSettingsComponent(), IsJSONRPCServerRunning(), m_settings, CZeroconf::PublishService(), CSettings::SETTING_SERVICES_DEVICEUUID, CSettings::SETTING_SERVICES_ESALLINTERFACES, CSettings::SETTING_SERVICES_ESENABLED, and JSONRPC::CTCPServer::StartServer().
Referenced by OnSettingChanging(), and Start().
StartRss()
bool CNetworkServices::StartRss ()
References CRssManager::GetInstance(), IsRssRunning(), and CRssManager::Start().
Referenced by Start().
StartServer()
bool CNetworkServices::StartServer (enum ESERVERS server, bool start)
References ES_AIRPLAYSERVER, ES_EVENTSERVER, ES_JSONRPCSERVER, ES_UPNPRENDERER, ES_UPNPSERVER, ES_WEBSERVER, ES_WSDISCOVERY, ES_ZEROCONF, CServiceBroker::GetSettingsComponent(), CSettings::SETTING_SERVICES_AIRPLAY, CSettings::SETTING_SERVICES_ESENABLED, CSettings::SETTING_SERVICES_UPNPRENDERER, CSettings::SETTING_SERVICES_UPNPSERVER, CSettings::SETTING_SERVICES_WEBSERVER, CSettings::SETTING_SERVICES_WSDISCOVERY, and CSettings::SETTING_SERVICES_ZEROCONF.
Referenced by XBMCAddon::xbmc::startServer().
StartUPnP()
bool CNetworkServices::StartUPnP ()
References m_settings, CSettings::SETTING_SERVICES_UPNPCONTROLLER, CSettings::SETTING_SERVICES_UPNPRENDERER, CSettings::SETTING_SERVICES_UPNPSERVER, StartUPnPClient(), StartUPnPController(), StartUPnPRenderer(), and StartUPnPServer().
Referenced by Start().
StartUPnPClient()
bool CNetworkServices::StartUPnPClient ()
References IsUPnPClientRunning(), CLog::Log(), LOGINFO, m_settings, and CSettings::SETTING_SERVICES_UPNP.
Referenced by OnSettingChanging(), and StartUPnP().
StartUPnPController()
bool CNetworkServices::StartUPnPController ()
References IsUPnPControllerRunning(), CLog::Log(), LOGINFO, m_settings, CSettings::SETTING_SERVICES_UPNP, CSettings::SETTING_SERVICES_UPNPCONTROLLER, and CSettings::SETTING_SERVICES_UPNPSERVER.
Referenced by OnSettingChanging(), and StartUPnP().
StartUPnPRenderer()
bool CNetworkServices::StartUPnPRenderer ()
References CLog::Log(), LOGINFO, m_settings, CSettings::SETTING_SERVICES_UPNP, and CSettings::SETTING_SERVICES_UPNPRENDERER.
Referenced by OnSettingChanging(), and StartUPnP().
StartUPnPServer()
bool CNetworkServices::StartUPnPServer ()
References CLog::Log(), LOGINFO, m_settings, CSettings::SETTING_SERVICES_UPNP, and CSettings::SETTING_SERVICES_UPNPSERVER.
Referenced by OnSettingChanging(), and StartUPnP().
StartWebserver()
bool CNetworkServices::StartWebserver ()
References CSysInfo::GetDeviceName(), CZeroconf::GetInstance(), CServiceBroker::GetNetwork(), CServiceBroker::GetSettingsComponent(), IsWebserverRunning(), CLog::Log(), LOGERROR, m_settings, CZeroconf::PublishService(), CSettings::SETTING_SERVICES_DEVICEUUID, CSettings::SETTING_SERVICES_WEBSERVER, CSettings::SETTING_SERVICES_WEBSERVERAUTHENTICATION, CSettings::SETTING_SERVICES_WEBSERVERPASSWORD, CSettings::SETTING_SERVICES_WEBSERVERPORT, CSettings::SETTING_SERVICES_WEBSERVERUSERNAME, and ValidatePort().
Referenced by OnSettingChanging(), and Start().
StartWSDiscovery()
bool CNetworkServices::StartWSDiscovery ()
References CServiceBroker::GetWSDiscovery(), IsWSDiscoveryRunning(), m_settings, CSettings::SETTING_SERVICES_WSDISCOVERY, and WSDiscovery::IWSDiscovery::StartServices().
Referenced by OnSettingChanging(), and Start().
StartZeroconf()
bool CNetworkServices::StartZeroconf ()
References CZeroconf::GetInstance(), IsZeroconfRunning(), CLog::Log(), LOGINFO, m_settings, CSettings::SETTING_SERVICES_ZEROCONF, and CZeroconf::Start().
Referenced by OnSettingChanging(), and Start().
Stop()
void CNetworkServices::Stop (bool bWait)
References StopAirPlayServer(), StopAirTunesServer(), StopEventServer(), StopJSONRPCServer(), StopRss(), StopUPnP(), StopWebserver(), StopWSDiscovery(), and StopZeroconf().
StopAirPlayServer()
bool CNetworkServices::StopAirPlayServer (bool bWait)
References CZeroconf::GetInstance(), IsAirPlayServerRunning(), CZeroconf::RemoveService(), and CAirPlayServer::StopServer().
Referenced by OnSettingChanging(), and Stop().
StopAirTunesServer()
bool CNetworkServices::StopAirTunesServer (bool bWait)
References IsAirTunesServerRunning(), and CAirTunesServer::StopServer().
Referenced by OnSettingChanging(), and Stop().
StopEventServer()
bool CNetworkServices::StopEventServer (bool bWait, bool promptuser)
References EVENTSERVER::CEventServer::GetInstance(), EVENTSERVER::CEventServer::GetNumberOfClients(), IsEventServerRunning(), CLog::Log(), LOGERROR, LOGINFO, KODI::MESSAGING::HELPERS::ShowYesNoDialogText(), and EVENTSERVER::CEventServer::StopServer().
Referenced by OnSettingChanging(), and Stop().
StopJSONRPCServer()
bool CNetworkServices::StopJSONRPCServer (bool bWait)
References CZeroconf::GetInstance(), IsJSONRPCServerRunning(), CZeroconf::RemoveService(), and JSONRPC::CTCPServer::StopServer().
Referenced by OnSettingChanging(), and Stop().
StopRss()
bool CNetworkServices::StopRss ()
References CRssManager::GetInstance(), IsRssRunning(), and CRssManager::Stop().
Referenced by Stop().
StopUPnP()
bool CNetworkServices::StopUPnP (bool bWait)
References CLog::Log(), and LOGINFO.
Referenced by Stop().
StopUPnPClient()
bool CNetworkServices::StopUPnPClient ()
References IsUPnPClientRunning(), CLog::Log(), and LOGINFO.
Referenced by OnSettingChanging().
StopUPnPController()
bool CNetworkServices::StopUPnPController ()
References IsUPnPControllerRunning(), CLog::Log(), and LOGINFO.
Referenced by OnSettingChanging(), and StopUPnPServer().
StopUPnPRenderer()
bool CNetworkServices::StopUPnPRenderer ()
References IsUPnPRendererRunning(), CLog::Log(), and LOGINFO.
Referenced by OnSettingChanging().
StopUPnPServer()
bool CNetworkServices::StopUPnPServer ()
References IsUPnPServerRunning(), CLog::Log(), LOGINFO, and StopUPnPController().
Referenced by OnSettingChanging().
StopWebserver()
bool CNetworkServices::StopWebserver ()
References CZeroconf::GetInstance(), IsWebserverRunning(), CLog::Log(), LOGWARNING, and CZeroconf::RemoveService().
Referenced by OnSettingChanging(), and Stop().
StopWSDiscovery()
bool CNetworkServices::StopWSDiscovery ()
References CServiceBroker::GetWSDiscovery(), IsWSDiscoveryRunning(), and WSDiscovery::IWSDiscovery::StopServices().
Referenced by OnSettingChanging(), and Stop().
StopZeroconf()
bool CNetworkServices::StopZeroconf ()
References CZeroconf::GetInstance(), IsZeroconfRunning(), CLog::Log(), LOGINFO, and CZeroconf::Stop().
Referenced by OnSettingChanging(), and Stop().
ValidatePort()
bool CNetworkServices::ValidatePort (int port) private
References CUtil::CanBindPrivileged().
Referenced by OnSettingChanging(), and StartWebserver().
Member Data Documentation
m_settings
std::shared_ptr<CSettings> CNetworkServices::m_settings private
Referenced by OnSettingChanged(), OnSettingChanging(), OnSettingUpdate(), RefreshEventServer(), Start(), StartAirPlayServer(), StartAirTunesServer(), StartEventServer(), StartJSONRPCServer(), StartUPnP(), StartUPnPClient(), StartUPnPController(), StartUPnPRenderer(), StartUPnPServer(), StartWebserver(), StartWSDiscovery(), StartZeroconf(), and ~CNetworkServices().
The documentation for this class was generated from the following files:
NetworkServices.h
NetworkServices.cpp