Kodi Documentation: CBitstreamConverter Class Reference
CBitstreamConverter Class Reference
#include <BitstreamConverter.h>
Classes
struct omx_bitstream_ctx
Public Member Functions
CBitstreamConverter ()
~CBitstreamConverter ()
bool Open (enum AVCodecID codec, uint8_t *in_extradata, int in_extrasize, bool to_annexb)
void Close (void)
bool NeedConvert (void) const
bool Convert (uint8_t *pData, int iSize)
uint8_t * GetConvertBuffer (void) const
int GetConvertSize () const
uint8_t * GetExtraData ()
const uint8_t * GetExtraData () const
int GetExtraSize () const
void ResetStartDecode (void)
bool CanStartDecode () const
void SetConvertDovi (bool value)
void SetRemoveDovi (bool value)
void SetRemoveHdr10Plus (bool value)
Static Public Member Functions
static bool mpeg2_sequence_header (const uint8_t *data, const uint32_t size, mpeg2_sequence *sequence)
Protected Types
typedef struct CBitstreamConverter::omx_bitstream_ctx omx_bitstream_ctx
Protected Member Functions
int isom_write_avcc (AVIOContext *pb, const uint8_t *data, int len)
bool IsIDR (uint8_t unit_type)
bool IsSlice (uint8_t unit_type)
bool BitstreamConvertInitAVC (void *in_extradata, int in_extrasize)
bool BitstreamConvertInitHEVC (void *in_extradata, int in_extrasize)
bool BitstreamConvert (uint8_t *pData, int iSize, uint8_t **poutbuf, int *poutbuf_size)
Static Protected Member Functions
static int avc_parse_nal_units (AVIOContext *pb, const uint8_t *buf_in, int size)
static int avc_parse_nal_units_buf (const uint8_t *buf_in, uint8_t **buf, int *size)
static void BitstreamAllocAndCopy (uint8_t **poutbuf, int *poutbuf_size, const uint8_t *sps_pps, uint32_t sps_pps_size, const uint8_t *in, uint32_t in_size, uint8_t nal_type)
Protected Attributes
uint8_t * m_convertBuffer
int m_convertSize
uint8_t * m_inputBuffer
int m_inputSize
uint32_t m_sps_pps_size
omx_bitstream_ctx m_sps_pps_context
bool m_convert_bitstream
bool m_to_annexb
FFmpegExtraData m_extraData
bool m_convert_3byteTo4byteNALSize
bool m_convert_bytestream
AVCodecID m_codec
bool m_start_decode
bool m_convert_dovi
bool m_removeDovi
bool m_removeHdr10Plus
Member Typedef Documentation
omx_bitstream_ctx
typedef struct CBitstreamConverter::omx_bitstream_ctx CBitstreamConverter::omx_bitstream_ctx protected
Constructor & Destructor Documentation
CBitstreamConverter()
CBitstreamConverter::CBitstreamConverter ()
References m_convert_3byteTo4byteNALSize, m_convert_bitstream, m_convert_bytestream, m_convert_dovi, m_convertBuffer, m_convertSize, m_inputBuffer, m_inputSize, m_removeDovi, m_removeHdr10Plus, m_sps_pps_context, m_start_decode, m_to_annexb, and CBitstreamConverter::omx_bitstream_ctx::sps_pps_data.
~CBitstreamConverter()
CBitstreamConverter::~CBitstreamConverter ()
References Close().
Member Function Documentation
avc_parse_nal_units()
int CBitstreamConverter::avc_parse_nal_units (AVIOContext * pb, const uint8_t * buf_in, int size) static protected
References avc_find_startcode(), and end().
Referenced by avc_parse_nal_units_buf(), and Convert().
avc_parse_nal_units_buf()
int CBitstreamConverter::avc_parse_nal_units_buf (const uint8_t * buf_in, uint8_t ** buf, int * size) static protected
References avc_parse_nal_units().
Referenced by isom_write_avcc().
BitstreamAllocAndCopy()
void CBitstreamConverter::BitstreamAllocAndCopy (uint8_t ** poutbuf, int * poutbuf_size, const uint8_t * sps_pps, uint32_t sps_pps_size, const uint8_t * in, uint32_t in_size, uint8_t nal_type) static protected
References HEVC_NAL_UNSPEC62.
Referenced by BitstreamConvert().
BitstreamConvert()
bool CBitstreamConverter::BitstreamConvert (uint8_t * pData, int iSize, uint8_t ** poutbuf, int * poutbuf_size) protected
References AVC_NAL_PPS, AVC_NAL_SEI, AVC_NAL_SPS, BitstreamAllocAndCopy(), CBitstreamConverter::omx_bitstream_ctx::first_idr, has_sei_recovery_point(), HEVC_NAL_PPS, HEVC_NAL_SEI_PREFIX, HEVC_NAL_SPS, HEVC_NAL_UNSPEC62, HEVC_NAL_UNSPEC63, CBitstreamConverter::omx_bitstream_ctx::idr_sps_pps_seen, IsIDR(), IsSlice(), CBitstreamConverter::omx_bitstream_ctx::length_size, m_codec, m_convert_dovi, m_removeDovi, m_removeHdr10Plus, m_sps_pps_context, m_start_decode, CHevcSei::RemoveHdr10PlusFromSeiNalu(), CBitstreamConverter::omx_bitstream_ctx::size, and CBitstreamConverter::omx_bitstream_ctx::sps_pps_data.
Referenced by Convert().
BitstreamConvertInitAVC()
bool CBitstreamConverter::BitstreamConvertInitAVC (void * in_extradata, int in_extrasize) protected
References CBitstreamConverter::omx_bitstream_ctx::first_idr, CBitstreamConverter::omx_bitstream_ctx::idr_sps_pps_seen, CBitstreamConverter::omx_bitstream_ctx::length_size, CLog::Log(), LOGDEBUG, m_sps_pps_context, m_sps_pps_size, CBitstreamConverter::omx_bitstream_ctx::size, and CBitstreamConverter::omx_bitstream_ctx::sps_pps_data.
Referenced by Open().
BitstreamConvertInitHEVC()
bool CBitstreamConverter::BitstreamConvertInitHEVC (void * in_extradata, int in_extrasize) protected
References CBitstreamConverter::omx_bitstream_ctx::first_idr, HEVC_NAL_PPS, HEVC_NAL_SPS, HEVC_NAL_VPS, CBitstreamConverter::omx_bitstream_ctx::idr_sps_pps_seen, CBitstreamConverter::omx_bitstream_ctx::length_size, CLog::Log(), LOGDEBUG, m_sps_pps_context, m_sps_pps_size, CBitstreamConverter::omx_bitstream_ctx::size, and CBitstreamConverter::omx_bitstream_ctx::sps_pps_data.
Referenced by Open().
CanStartDecode()
bool CBitstreamConverter::CanStartDecode () const
References m_start_decode.
Close()
void CBitstreamConverter::Close (void)
References m_convert_3byteTo4byteNALSize, m_convert_bitstream, m_convert_bytestream, m_convertBuffer, m_convertSize, m_extraData, m_inputBuffer, m_inputSize, m_sps_pps_context, and CBitstreamConverter::omx_bitstream_ctx::sps_pps_data.
Referenced by ~CBitstreamConverter().
Convert()
bool CBitstreamConverter::Convert (uint8_t * pData, int iSize)
References avc_parse_nal_units(), BitstreamConvert(), end(), CLog::Log(), LOGERROR, m_codec, m_convert_3byteTo4byteNALSize, m_convert_bitstream, m_convert_bytestream, m_convertBuffer, m_convertSize, m_inputBuffer, m_inputSize, and m_to_annexb.
GetConvertBuffer()
uint8_t * CBitstreamConverter::GetConvertBuffer (void) const
References m_convert_3byteTo4byteNALSize, m_convert_bitstream, m_convert_bytestream, m_convertBuffer, and m_inputBuffer.
GetConvertSize()
int CBitstreamConverter::GetConvertSize () const
References m_convert_3byteTo4byteNALSize, m_convert_bitstream, m_convert_bytestream, m_convertBuffer, m_convertSize, and m_inputSize.
GetExtraData() [1/2]
uint8_t * CBitstreamConverter::GetExtraData ()
References FFmpegExtraData::GetData(), m_convert_bitstream, m_extraData, m_sps_pps_context, and CBitstreamConverter::omx_bitstream_ctx::sps_pps_data.
GetExtraData() [2/2]
const uint8_t * CBitstreamConverter::GetExtraData () const
References FFmpegExtraData::GetData(), m_convert_bitstream, m_extraData, m_sps_pps_context, and CBitstreamConverter::omx_bitstream_ctx::sps_pps_data.
GetExtraSize()
int CBitstreamConverter::GetExtraSize () const
References FFmpegExtraData::GetSize(), m_convert_bitstream, m_extraData, m_sps_pps_context, and CBitstreamConverter::omx_bitstream_ctx::size.
IsIDR()
bool CBitstreamConverter::IsIDR (uint8_t unit_type) protected
References AVC_NAL_IDR_SLICE, HEVC_NAL_CRA_NUT, HEVC_NAL_IDR_N_LP, HEVC_NAL_IDR_W_RADL, and m_codec.
Referenced by BitstreamConvert().
isom_write_avcc()
int CBitstreamConverter::isom_write_avcc (AVIOContext * pb, const uint8_t * data, int len) protected
References avc_parse_nal_units_buf(), data(), end(), and UINT16_MAX.
Referenced by Open().
IsSlice()
bool CBitstreamConverter::IsSlice (uint8_t unit_type) protected
References AVC_NAL_SLICE, HEVC_NAL_BLA_N_LP, HEVC_NAL_BLA_W_LP, HEVC_NAL_BLA_W_RADL, HEVC_NAL_CRA_NUT, HEVC_NAL_RADL_N, HEVC_NAL_RADL_R, HEVC_NAL_RASL_N, HEVC_NAL_RASL_R, HEVC_NAL_STSA_N, HEVC_NAL_STSA_R, HEVC_NAL_TRAIL_N, HEVC_NAL_TRAIL_R, HEVC_NAL_TSA_N, HEVC_NAL_TSA_R, and m_codec.
Referenced by BitstreamConvert().
mpeg2_sequence_header()
bool CBitstreamConverter::mpeg2_sequence_header (const uint8_t * data, const uint32_t size, mpeg2_sequence * sequence) static
References avc_find_startcode(), data(), end(), mpeg2_sequence::fps_rate, mpeg2_sequence::fps_scale, mpeg2_sequence::height, nal_bs_init(), nal_bs_read(), mpeg2_sequence::ratio, mpeg2_sequence::ratio_info, and mpeg2_sequence::width.
Referenced by CDVDVideoCodecAndroidMediaCodec::AddData().
NeedConvert()
bool CBitstreamConverter::NeedConvert (void) const inline
References m_convert_bitstream.
Open()
bool CBitstreamConverter::Open (enum AVCodecID codec, uint8_t * in_extradata, int in_extrasize, bool to_annexb)
It seems the extradata is encoded as hvcC format. Temporarily, we support configurationVersion==0 until 14496-15 3rd is finalized. When finalized, configurationVersion will be 1 and we can recognize hvcC by checking if extradata[0]==1 or not.
Todo:
convert annexb to bitstream format
References BitstreamConvertInitAVC(), BitstreamConvertInitHEVC(), FFmpegExtraData::GetData(), FFmpegExtraData::GetSize(), isom_write_avcc(), CLog::Log(), LOGERROR, LOGINFO, m_codec, m_convert_3byteTo4byteNALSize, m_convert_bitstream, m_convert_bytestream, m_extraData, and m_to_annexb.
ResetStartDecode()
void CBitstreamConverter::ResetStartDecode (void)
References m_start_decode.
SetConvertDovi()
void CBitstreamConverter::SetConvertDovi (bool value) inline
References m_convert_dovi, and value.
SetRemoveDovi()
void CBitstreamConverter::SetRemoveDovi (bool value) inline
References m_removeDovi, and value.
SetRemoveHdr10Plus()
void CBitstreamConverter::SetRemoveHdr10Plus (bool value) inline
References m_removeHdr10Plus, and value.
Member Data Documentation
m_codec
AVCodecID CBitstreamConverter::m_codec protected
Referenced by BitstreamConvert(), Convert(), IsIDR(), IsSlice(), and Open().
m_convert_3byteTo4byteNALSize
bool CBitstreamConverter::m_convert_3byteTo4byteNALSize protected
Referenced by CBitstreamConverter(), Close(), Convert(), GetConvertBuffer(), GetConvertSize(), and Open().
m_convert_bitstream
bool CBitstreamConverter::m_convert_bitstream protected
Referenced by CBitstreamConverter(), Close(), Convert(), GetConvertBuffer(), GetConvertSize(), GetExtraData(), GetExtraData(), GetExtraSize(), NeedConvert(), and Open().
m_convert_bytestream
bool CBitstreamConverter::m_convert_bytestream protected
Referenced by CBitstreamConverter(), Close(), Convert(), GetConvertBuffer(), GetConvertSize(), and Open().
m_convert_dovi
bool CBitstreamConverter::m_convert_dovi protected
Referenced by BitstreamConvert(), CBitstreamConverter(), and SetConvertDovi().
m_convertBuffer
uint8_t* CBitstreamConverter::m_convertBuffer protected
Referenced by CBitstreamConverter(), Close(), Convert(), GetConvertBuffer(), and GetConvertSize().
m_convertSize
int CBitstreamConverter::m_convertSize protected
Referenced by CBitstreamConverter(), Close(), Convert(), and GetConvertSize().
m_extraData
FFmpegExtraData CBitstreamConverter::m_extraData protected
Referenced by Close(), GetExtraData(), GetExtraData(), GetExtraSize(), and Open().
m_inputBuffer
uint8_t* CBitstreamConverter::m_inputBuffer protected
Referenced by CBitstreamConverter(), Close(), Convert(), and GetConvertBuffer().
m_inputSize
int CBitstreamConverter::m_inputSize protected
Referenced by CBitstreamConverter(), Close(), Convert(), and GetConvertSize().
m_removeDovi
bool CBitstreamConverter::m_removeDovi protected
Referenced by BitstreamConvert(), CBitstreamConverter(), and SetRemoveDovi().
m_removeHdr10Plus
bool CBitstreamConverter::m_removeHdr10Plus protected
Referenced by BitstreamConvert(), CBitstreamConverter(), and SetRemoveHdr10Plus().
m_sps_pps_context
omx_bitstream_ctx CBitstreamConverter::m_sps_pps_context protected
Referenced by BitstreamConvert(), BitstreamConvertInitAVC(), BitstreamConvertInitHEVC(), CBitstreamConverter(), Close(), GetExtraData(), GetExtraData(), and GetExtraSize().
m_sps_pps_size
uint32_t CBitstreamConverter::m_sps_pps_size protected
Referenced by BitstreamConvertInitAVC(), and BitstreamConvertInitHEVC().
m_start_decode
bool CBitstreamConverter::m_start_decode protected
Referenced by BitstreamConvert(), CanStartDecode(), CBitstreamConverter(), and ResetStartDecode().
m_to_annexb
bool CBitstreamConverter::m_to_annexb protected
Referenced by CBitstreamConverter(), Convert(), and Open().
The documentation for this class was generated from the following files:
BitstreamConverter.h
BitstreamConverter.cpp