Kodi Documentation: CDBusConnection Class Reference
CDBusConnection Class Reference
#include <DBusUtil.h>
Classes
struct DBusConnectionDeleter
Public Member Functions
CDBusConnection ()
bool Connect (DBusBusType bus, bool openPrivate=false)
bool Connect (DBusBusType bus, CDBusError &error, bool openPrivate=false)
void Destroy ()
operator DBusConnection * ()
Private Member Functions
CDBusConnection (CDBusConnection const &other)=delete
CDBusConnection & operator= (CDBusConnection const &other)=delete
Private Attributes
std::unique_ptr< DBusConnection, DBusConnectionDeleter > m_connection
Constructor & Destructor Documentation
CDBusConnection() [1/2]
CDBusConnection::CDBusConnection () default
CDBusConnection() [2/2]
CDBusConnection::CDBusConnection (CDBusConnection const & other) private delete
Member Function Documentation
Connect() [1/2]
bool CDBusConnection::Connect (DBusBusType bus, bool openPrivate = false)
References Connect(), CDBusError::Log(), and LOGWARNING.
Referenced by CLogindUPowerSyscall::CLogindUPowerSyscall(), Connect(), CUDisks2Provider::CUDisks2Provider(), CUDisksProvider::CUDisksProvider(), CUPowerSyscall::CUPowerSyscall(), CDBusMessage::Send(), CDBusMessage::Send(), and CDBusMessage::SendAsync().
Connect() [2/2]
bool CDBusConnection::Connect (DBusBusType bus, CDBusError & error, bool openPrivate = false)
References m_connection.
Destroy()
void CDBusConnection::Destroy ()
References m_connection.
Referenced by CLogindUPowerSyscall::CLogindUPowerSyscall(), CUDisks2Provider::CUDisks2Provider(), CUDisksProvider::CUDisksProvider(), and CUPowerSyscall::CUPowerSyscall().
operator DBusConnection *()
CDBusConnection::operator DBusConnection * ()
operator=()
CDBusConnection & CDBusConnection::operator= (CDBusConnection const & other) private delete
Member Data Documentation
m_connection
std::unique_ptr<DBusConnection, DBusConnectionDeleter> CDBusConnection::m_connection private
Referenced by Connect(), and Destroy().
The documentation for this class was generated from the following files:
DBusUtil.h
DBusUtil.cpp