Kodi Documentation: CXBTFFrame Class Reference
CXBTFFrame Class Reference
#include <XBTF.h>
Public Member Functions
CXBTFFrame ()
uint32_t GetWidth () const
void SetWidth (uint32_t width)
XB_FMT GetFormat (bool raw=false) const
void SetFormat (uint32_t format)
uint32_t GetHeight () const
void SetHeight (uint32_t height)
uint64_t GetUnpackedSize () const
void SetUnpackedSize (uint64_t size)
uint64_t GetPackedSize () const
void SetPackedSize (uint64_t size)
uint64_t GetOffset () const
void SetOffset (uint64_t offset)
uint64_t GetHeaderSize () const
uint32_t GetDuration () const
void SetDuration (uint32_t duration)
bool IsPacked () const
bool HasAlpha () const
KD_TEX_FMT GetKDFormat () const
KD_TEX_FMT GetKDFormatType () const
KD_TEX_ALPHA GetKDAlpha () const
KD_TEX_SWIZ GetKDSwizzle () const
Private Attributes
uint32_t m_width
uint32_t m_height
uint32_t m_format
uint64_t m_packedSize
uint64_t m_unpackedSize
uint64_t m_offset
uint32_t m_duration
Constructor & Destructor Documentation
CXBTFFrame()
CXBTFFrame::CXBTFFrame ()
References m_duration, m_format, m_height, m_offset, m_packedSize, m_unpackedSize, m_width, and XB_FMT_UNKNOWN.
Member Function Documentation
GetDuration()
uint32_t CXBTFFrame::GetDuration () const
References m_duration.
Referenced by CTextureBundleXBT::LoadAnim().
GetFormat()
XB_FMT CXBTFFrame::GetFormat (bool raw = false) const
References m_format, and XB_FMT_MASK.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), and XFILE::CXbtFile::GetImageFormat().
GetHeaderSize()
uint64_t CXBTFFrame::GetHeaderSize () const
References m_duration, m_format, m_height, m_offset, m_packedSize, m_unpackedSize, and m_width.
GetHeight()
uint32_t CXBTFFrame::GetHeight () const
References m_height.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), XFILE::CXbtFile::GetImageHeight(), and CTextureBundleXBT::LoadTexture().
GetKDAlpha()
KD_TEX_ALPHA CXBTFFrame::GetKDAlpha () const
References KD_TEX_ALPHA_MASK, and m_format.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), and XFILE::CXbtFile::GetKDAlpha().
GetKDFormat()
KD_TEX_FMT CXBTFFrame::GetKDFormat () const
References KD_TEX_FMT_MASK, and m_format.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), and XFILE::CXbtFile::GetKDFormat().
GetKDFormatType()
KD_TEX_FMT CXBTFFrame::GetKDFormatType () const
References KD_TEX_FMT_TYPE_MASK, and m_format.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), and XFILE::CXbtFile::GetKDFormatType().
GetKDSwizzle()
KD_TEX_SWIZ CXBTFFrame::GetKDSwizzle () const
References KD_TEX_SWIZ_MASK, and m_format.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), and XFILE::CXbtFile::GetKDSwizzle().
GetOffset()
uint64_t CXBTFFrame::GetOffset () const
References m_offset.
Referenced by CXBTFReader::Load().
GetPackedSize()
uint64_t CXBTFFrame::GetPackedSize () const
References m_packedSize.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), CXBTFReader::Load(), and CTextureBundleXBT::UnpackFrame().
GetUnpackedSize()
uint64_t CXBTFFrame::GetUnpackedSize () const
References m_unpackedSize.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), XFILE::CXbtFile::Read(), XFILE::CXbtFile::Seek(), and CTextureBundleXBT::UnpackFrame().
GetWidth()
uint32_t CXBTFFrame::GetWidth () const
References m_width.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), XFILE::CXbtFile::GetImageWidth(), and CTextureBundleXBT::LoadTexture().
HasAlpha()
bool CXBTFFrame::HasAlpha () const
References m_format, and XB_FMT_OPAQUE.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), and XFILE::CXbtFile::HasImageAlpha().
IsPacked()
bool CXBTFFrame::IsPacked () const
References m_packedSize, and m_unpackedSize.
Referenced by CTextureBundleXBT::ConvertFrameToTexture(), and CTextureBundleXBT::UnpackFrame().
SetDuration()
void CXBTFFrame::SetDuration (uint32_t duration)
References m_duration.
Referenced by CXBTFReader::Open().
SetFormat()
void CXBTFFrame::SetFormat (uint32_t format)
References m_format.
Referenced by CXBTFReader::Open().
SetHeight()
void CXBTFFrame::SetHeight (uint32_t height)
References m_height.
Referenced by CXBTFReader::Open().
SetOffset()
void CXBTFFrame::SetOffset (uint64_t offset)
References m_offset.
Referenced by CXBTFReader::Open().
SetPackedSize()
void CXBTFFrame::SetPackedSize (uint64_t size)
References m_packedSize.
Referenced by CXBTFReader::Open().
SetUnpackedSize()
void CXBTFFrame::SetUnpackedSize (uint64_t size)
References m_unpackedSize.
Referenced by CXBTFReader::Open().
SetWidth()
void CXBTFFrame::SetWidth (uint32_t width)
References m_width.
Referenced by CXBTFReader::Open().
Member Data Documentation
m_duration
uint32_t CXBTFFrame::m_duration private
Referenced by CXBTFFrame(), GetDuration(), GetHeaderSize(), and SetDuration().
m_format
uint32_t CXBTFFrame::m_format private
Referenced by CXBTFFrame(), GetFormat(), GetHeaderSize(), GetKDAlpha(), GetKDFormat(), GetKDFormatType(), GetKDSwizzle(), HasAlpha(), and SetFormat().
m_height
uint32_t CXBTFFrame::m_height private
Referenced by CXBTFFrame(), GetHeaderSize(), GetHeight(), and SetHeight().
m_offset
uint64_t CXBTFFrame::m_offset private
Referenced by CXBTFFrame(), GetHeaderSize(), GetOffset(), and SetOffset().
m_packedSize
uint64_t CXBTFFrame::m_packedSize private
Referenced by CXBTFFrame(), GetHeaderSize(), GetPackedSize(), IsPacked(), and SetPackedSize().
m_unpackedSize
uint64_t CXBTFFrame::m_unpackedSize private
Referenced by CXBTFFrame(), GetHeaderSize(), GetUnpackedSize(), IsPacked(), and SetUnpackedSize().
m_width
uint32_t CXBTFFrame::m_width private
Referenced by CXBTFFrame(), GetHeaderSize(), GetWidth(), and SetWidth().
The documentation for this class was generated from the following files:
XBTF.h
XBTF.cpp