Kodi Documentation: KODI::GAME::CGameClientKeyboard Class Reference
KODI::GAME::CGameClientKeyboard Class Reference
Games
Handles keyboard events for games.
#include <GameClientKeyboard.h>
Public Member Functions
CGameClientKeyboard (CGameClient &gameClient, std::string controllerId, KEYBOARD::IKeyboardInputProvider *inputProvider)
Constructor registers for keyboard events at CInputManager.
~CGameClientKeyboard () override
Destructor unregisters from keyboard events from CInputManager.
std::string ControllerID () const override
The add-on ID of the keyboard's controller profile.
bool HasKey (const KEYBOARD::KeyName &key) const override
Return true if the input handler accepts the given key.
bool OnKeyPress (const KEYBOARD::KeyName &key, KEYBOARD::Modifier mod, uint32_t unicode) override
A key has been pressed.
void OnKeyRelease (const KEYBOARD::KeyName &key, KEYBOARD::Modifier mod, uint32_t unicode) override
A key has been released.
const std::string & GetControllerID () const
const PERIPHERALS::PeripheralPtr & GetSource () const
float GetActivation () const
void SetSource (PERIPHERALS::PeripheralPtr sourcePeripheral)
void ClearSource ()
Public Member Functions inherited from KODI::KEYBOARD::IKeyboardInputHandler
virtual ~IKeyboardInputHandler ()=default
Private Attributes
CGameClient & m_gameClient
const std::string m_controllerId
KEYBOARD::IKeyboardInputProvider *const m_inputProvider
PERIPHERALS::PeripheralPtr m_sourcePeripheral
std::unique_ptr< CControllerActivity > m_keyboardActivity
Detailed Description
Handles keyboard events for games.
Listens to keyboard events and forwards them to the games (as game_input_event).
Constructor & Destructor Documentation
CGameClientKeyboard()
CGameClientKeyboard::CGameClientKeyboard (CGameClient & gameClient, std::string controllerId, KEYBOARD::IKeyboardInputProvider * inputProvider)
Constructor registers for keyboard events at CInputManager.
Parameters
gameClient The game client implementation.
controllerId The controller profile used for input
dllStruct The emulator or game to which the events are sent.
inputProvider The interface providing us with keyboard input.
References m_inputProvider, and KODI::KEYBOARD::IKeyboardInputProvider::RegisterKeyboardHandler().
~CGameClientKeyboard()
CGameClientKeyboard::~CGameClientKeyboard () override
Destructor unregisters from keyboard events from CInputManager.
References m_inputProvider, and KODI::KEYBOARD::IKeyboardInputProvider::UnregisterKeyboardHandler().
Member Function Documentation
ClearSource()
void CGameClientKeyboard::ClearSource ()
References m_sourcePeripheral.
ControllerID()
std::string CGameClientKeyboard::ControllerID () const override virtual
The add-on ID of the keyboard's controller profile.
Returns
The ID of the controller profile add-on
Implements KODI::KEYBOARD::IKeyboardInputHandler.
References m_controllerId.
Referenced by HasKey().
GetActivation()
float CGameClientKeyboard::GetActivation () const
References m_keyboardActivity.
GetControllerID()
const std::string & KODI::GAME::CGameClientKeyboard::GetControllerID () const inline
References m_controllerId.
GetSource()
const PERIPHERALS::PeripheralPtr & KODI::GAME::CGameClientKeyboard::GetSource () const inline
References m_sourcePeripheral.
HasKey()
bool CGameClientKeyboard::HasKey (const KEYBOARD::KeyName & key) const override virtual
Return true if the input handler accepts the given key.
Parameters
key A key belonging to the controller specified by ControllerID()
Returns
True if the key is used for input, false otherwise
Implements KODI::KEYBOARD::IKeyboardInputHandler.
References ControllerID(), KODI::GAME::CGameClientInput::HasFeature(), KODI::GAME::CGameClient::Input(), and m_gameClient.
OnKeyPress()
bool CGameClientKeyboard::OnKeyPress (const KEYBOARD::KeyName & key, KEYBOARD::Modifier mod, uint32_t unicode) override virtual
A key has been pressed.
Parameters
key A key belonging to the controller specified by ControllerID()
mod A combination of modifiers
unicode The unicode value associated with the key, or 0 if unknown
Returns
True if the event was handled, false otherwise
Implements KODI::KEYBOARD::IKeyboardInputHandler.
References KODI::GAME::CGameClientInput::AcceptsInput(), GAME_INPUT_EVENT_KEY, GAME_PORT_KEYBOARD, KODI::GAME::CGameClientTranslator::GetModifiers(), KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), KEYBOARD_PORT_ADDRESS, CLog::Log(), LOGDEBUG, m_controllerId, m_gameClient, m_keyboardActivity, and game_input_event::type.
OnKeyRelease()
void CGameClientKeyboard::OnKeyRelease (const KEYBOARD::KeyName & key, KEYBOARD::Modifier mod, uint32_t unicode) override virtual
A key has been released.
Parameters
key A key belonging to the controller specified by ControllerID()
mod A combination of modifiers
unicode The unicode value associated with the key, or 0 if unknown
Implements KODI::KEYBOARD::IKeyboardInputHandler.
References GAME_INPUT_EVENT_KEY, GAME_PORT_KEYBOARD, KODI::GAME::CGameClientTranslator::GetModifiers(), KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), KEYBOARD_PORT_ADDRESS, m_controllerId, m_gameClient, m_keyboardActivity, and game_input_event::type.
SetSource()
void CGameClientKeyboard::SetSource (PERIPHERALS::PeripheralPtr sourcePeripheral)
References m_sourcePeripheral.
Member Data Documentation
m_controllerId
const std::string KODI::GAME::CGameClientKeyboard::m_controllerId private
Referenced by ControllerID(), GetControllerID(), OnKeyPress(), and OnKeyRelease().
m_gameClient
CGameClient& KODI::GAME::CGameClientKeyboard::m_gameClient private
Referenced by HasKey(), OnKeyPress(), and OnKeyRelease().
m_inputProvider
KEYBOARD::IKeyboardInputProvider* const KODI::GAME::CGameClientKeyboard::m_inputProvider private
Referenced by CGameClientKeyboard(), and ~CGameClientKeyboard().
m_keyboardActivity
std::unique_ptr<CControllerActivity> KODI::GAME::CGameClientKeyboard::m_keyboardActivity private
Referenced by GetActivation(), OnKeyPress(), and OnKeyRelease().
m_sourcePeripheral
PERIPHERALS::PeripheralPtr KODI::GAME::CGameClientKeyboard::m_sourcePeripheral private
Referenced by ClearSource(), GetSource(), and SetSource().
The documentation for this class was generated from the following files:
GameClientKeyboard.h
GameClientKeyboard.cpp