Kodi Documentation: Win32DllLoader.cpp File Reference
Win32DllLoader.cpp File Reference
#include "Win32DllLoader.h"
#include "DllLoaderContainer.h"
#include "exports/emu_msvcrt.h"
#include "filesystem/SpecialProtocol.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include "platform/win32/CharsetConverter.h"
#include <limits>
#include <string_view>
Classes
struct Export
Functions
FARPROC WINAPI dllWin32GetProcAddress (HMODULE hModule, LPCSTR function)
HMODULE WINAPI dllLoadLibraryA (LPCSTR libname)
BOOL WINAPI dllFreeLibrary (HINSTANCE hLibModule)
bool FunctionNeedsWrapping (const char *functionName, void **fixup)
Variables
Export win32_exports []
Function Documentation
dllFreeLibrary()
BOOL WINAPI dllFreeLibrary (HINSTANCE hLibModule)
References DllLoaderContainer::GetModule(), LibraryLoader::IsSystemDll(), CLog::Log(), LOGERROR, and DllLoaderContainer::ReleaseModule().
Referenced by Win32DllLoader::RestoreImports().
dllLoadLibraryA()
HMODULE WINAPI dllLoadLibraryA (LPCSTR libname)
dllWin32GetProcAddress()
FARPROC __stdcall dllWin32GetProcAddress (HMODULE hModule, LPCSTR function)
References FunctionNeedsWrapping().
FunctionNeedsWrapping()
bool FunctionNeedsWrapping (const char * functionName, void ** fixup)
References win32_exports.
Referenced by dllWin32GetProcAddress(), and Win32DllLoader::ResolveImport().
Variable Documentation
win32_exports
Export win32_exports[]
Referenced by FunctionNeedsWrapping(), and Win32DllLoader::ResolveOrdinal().