Kodi Documentation: dll.cpp File Reference
dll.cpp File Reference
#include "dll.h"
#include "DllLoaderContainer.h"
#include "filesystem/SpecialProtocol.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include <climits>
Macros
#define DEFAULT_DLLPATH "special://xbmc/system/players/mplayer/codecs/"
#define HIGH_WORD(a) ((uintptr_t)(a) >> 16)
#define LOW_WORD(a) ((unsigned short)(((uintptr_t)(a)) & MAXWORD))
#define DONT_RESOLVE_DLL_REFERENCES 0x00000001
#define LOAD_LIBRARY_AS_DATAFILE 0x00000002
#define LOAD_WITH_ALTERED_SEARCH_PATH 0x00000008
#define LOAD_IGNORE_CODE_AUTHZ_LEVEL 0x00000010
Functions
char * getpath (char *buf, const char *full)
HMODULE __stdcall dllLoadLibraryExtended (const char *lib_file, const char *sourcedll)
HMODULE __stdcall dllLoadLibraryA (const char *file)
HMODULE __stdcall dllLoadLibraryExExtended (const char *lpLibFileName, HANDLE hFile, DWORD dwFlags, const char *sourcedll)
HMODULE __stdcall dllLoadLibraryExA (const char *lpLibFileName, HANDLE hFile, DWORD dwFlags)
int __stdcall dllFreeLibrary (HINSTANCE hLibModule)
HMODULE WINAPI dllGetModuleHandleA (const char *lpModuleName)
Macro Definition Documentation
DEFAULT_DLLPATH
#define DEFAULT_DLLPATH "special://xbmc/system/players/mplayer/codecs/"
DONT_RESOLVE_DLL_REFERENCES
#define DONT_RESOLVE_DLL_REFERENCES 0x00000001
HIGH_WORD
#define HIGH_WORD (a) ((uintptr_t)(a) >> 16)
LOAD_IGNORE_CODE_AUTHZ_LEVEL
#define LOAD_IGNORE_CODE_AUTHZ_LEVEL 0x00000010
LOAD_LIBRARY_AS_DATAFILE
#define LOAD_LIBRARY_AS_DATAFILE 0x00000002
LOAD_WITH_ALTERED_SEARCH_PATH
#define LOAD_WITH_ALTERED_SEARCH_PATH 0x00000008
LOW_WORD
#define LOW_WORD (a) ((unsigned short)(((uintptr_t)(a)) & MAXWORD))
Function Documentation
dllFreeLibrary()
int __stdcall dllFreeLibrary (HINSTANCE hLibModule)
References DllLoaderContainer::GetModule(), LibraryLoader::IsSystemDll(), CLog::Log(), LOGERROR, and DllLoaderContainer::ReleaseModule().
Referenced by Win32DllLoader::RestoreImports().
dllGetModuleHandleA()
HMODULE WINAPI dllGetModuleHandleA (const char * lpModuleName)
References LibraryLoader::GetHModule(), DllLoaderContainer::GetModule(), CLog::Log(), and LOGDEBUG.
dllLoadLibraryA()
HMODULE __stdcall dllLoadLibraryA (const char * file)
References dllLoadLibraryExtended().
Referenced by Win32DllLoader::OverrideImports().
dllLoadLibraryExA()
HMODULE __stdcall dllLoadLibraryExA (const char * lpLibFileName, HANDLE hFile, DWORD dwFlags)
References dllLoadLibraryExExtended().
dllLoadLibraryExExtended()
HMODULE __stdcall dllLoadLibraryExExtended (const char * lpLibFileName, HANDLE hFile, DWORD dwFlags, const char * sourcedll)
References dllLoadLibraryExtended(), DONT_RESOLVE_DLL_REFERENCES, LOAD_IGNORE_CODE_AUTHZ_LEVEL, LOAD_LIBRARY_AS_DATAFILE, LOAD_WITH_ALTERED_SEARCH_PATH, CLog::Log(), and LOGDEBUG.
Referenced by dllLoadLibraryExA().
dllLoadLibraryExtended()
HMODULE __stdcall dllLoadLibraryExtended (const char * lib_file, const char * sourcedll)
References DEFAULT_DLLPATH, LibraryLoader::GetHModule(), getpath(), DllLoaderContainer::LoadModule(), CLog::Log(), LOGERROR, MAX_PATH, and PATH_SEPARATOR_CHAR.
Referenced by dllLoadLibraryA(), and dllLoadLibraryExExtended().
getpath()
char * getpath (char * buf, const char * full)
References full, and PATH_SEPARATOR_CHAR.
Referenced by dllLoadLibraryExtended().