Kodi Documentation: CSettingSection Class Reference
CSettingSection Class Reference
Settings
Section of setting categories.
#include <SettingSection.h>
Public Member Functions
CSettingSection (const std::string &id, CSettingsManager *settingsManager=nullptr)
Creates a new setting section with the given identifier.
~CSettingSection () override=default
bool Deserialize (const TiXmlNode *node, bool update=false) override
Deserializes the given XML node into the properties of the setting object.
const SettingCategoryList & GetCategories () const
Gets the full list of setting categories belonging to the setting section.
SettingCategoryList GetCategories (SettingLevel level) const
Gets the list of setting categories belonging to the setting section that contain settings assigned to the given setting level (or below) and that meet the requirements and visibility conditions.
void AddCategory (const SettingCategoryPtr &category)
void AddCategories (const SettingCategoryList &categories)
Public Member Functions inherited from ISetting
ISetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
Creates a new setting object with the given identifier.
virtual ~ISetting ()=default
const std::string & GetId () const
Gets the identifier of the setting object.
virtual bool IsVisible () const
Whether the setting object is visible or hidden.
virtual void SetVisible (bool visible)
Sets the visibility state of the setting object.
int GetLabel () const
Gets the localizeable label ID of the setting group.
void SetLabel (int label)
Sets the localizeable label ID of the setting group.
int GetHelp () const
Gets the localizeable help ID of the setting group.
void SetHelp (int help)
Sets the localizeable help ID of the setting group.
virtual bool MeetsRequirements () const
Whether the setting object meets all necessary requirements.
virtual void CheckRequirements ()
Checks if the setting object meets all necessary requirements.
virtual void SetRequirementsMet (bool requirementsMet)
Sets whether the setting object meets all necessary requirements.
Private Attributes
SettingCategoryList m_categories
Static Private Attributes
static Logger s_logger
Additional Inherited Members
Static Public Member Functions inherited from ISetting
static bool DeserializeIdentification (const TiXmlNode *node, std::string &identification)
Deserializes the given XML node to retrieve a setting object's identifier.
Static Protected Member Functions inherited from ISetting
static bool DeserializeIdentificationFromAttribute (const TiXmlNode *node, const std::string &attribute, std::string &identification)
Deserializes the given XML node to retrieve a setting object's identifier from the given attribute.
Protected Attributes inherited from ISetting
std::string m_id
CSettingsManager * m_settingsManager
Static Protected Attributes inherited from ISetting
static constexpr int DefaultLabel = -1
Detailed Description
Section of setting categories.
See also
CSettings
CSettingCategory
Constructor & Destructor Documentation
CSettingSection()
CSettingSection::CSettingSection (const std::string & id, CSettingsManager * settingsManager = nullptr)
Creates a new setting section with the given identifier.
Parameters
id Identifier of the setting section
settingsManager Reference to the settings manager
References CLog::GetLogger(), CServiceBroker::GetLogging(), and s_logger.
~CSettingSection()
CSettingSection::~CSettingSection () override default
Member Function Documentation
AddCategories()
void CSettingSection::AddCategories (const SettingCategoryList & categories)
References addISetting(), and m_categories.
AddCategory()
void CSettingSection::AddCategory (const SettingCategoryPtr & category)
References addISetting(), and m_categories.
Deserialize()
bool CSettingSection::Deserialize (const TiXmlNode * node, bool update = false) override virtual
Deserializes the given XML node into the properties of the setting object.
If the update parameter is true, the checks for mandatory properties are skipped and values are only updated.
Parameters
node XML node containing the properties of the setting object
update Whether to perform checks for mandatory properties or not
Returns
True if deserialization was successful, false otherwise
Reimplemented from ISetting.
References addISetting(), ISetting::Deserialize(), ISetting::DeserializeIdentification(), m_categories, ISetting::m_settingsManager, node, s_logger, and SETTING_XML_ELM_CATEGORY.
GetCategories() [1/2]
const SettingCategoryList & CSettingSection::GetCategories () const inline
Gets the full list of setting categories belonging to the setting section.
Returns
Full list of setting categories belonging to the setting section
References m_categories.
GetCategories() [2/2]
SettingCategoryList CSettingSection::GetCategories (SettingLevel level) const
Gets the list of setting categories belonging to the setting section that contain settings assigned to the given setting level (or below) and that meet the requirements and visibility conditions.
Parameters
level Level the settings should be assigned to
Returns
List of setting categories belonging to the setting section
References m_categories.
Member Data Documentation
m_categories
SettingCategoryList CSettingSection::m_categories private
Referenced by AddCategories(), AddCategory(), Deserialize(), GetCategories(), and GetCategories().
s_logger
Logger CSettingSection::s_logger static private
Referenced by CSettingSection(), and Deserialize().
The documentation for this class was generated from the following files:
SettingSection.h
SettingSection.cpp