Kodi Documentation: CSlideShowPicDX Class Reference
CSlideShowPicDX Class Reference
#include <SlideShowPictureDX.h>
Public Member Functions
CSlideShowPicDX ()=default
~CSlideShowPicDX () override=default
Public Member Functions inherited from CSlideShowPic
CSlideShowPic ()
virtual ~CSlideShowPic ()
void SetTexture (int iSlideNumber, std::unique_ptr< CTexture > pTexture, DISPLAY_EFFECT dispEffect=EFFECT_RANDOM, TRANSITION_EFFECT transEffect=FADEIN_FADEOUT)
void UpdateTexture (std::unique_ptr< CTexture > pTexture)
bool IsLoaded () const
void UnLoad ()
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions)
void Render ()
void Close ()
void Reset (DISPLAY_EFFECT dispEffect=EFFECT_RANDOM, TRANSITION_EFFECT transEffect=FADEIN_FADEOUT)
DISPLAY_EFFECT DisplayEffect () const
bool DisplayEffectNeedChange (DISPLAY_EFFECT newDispEffect) const
bool IsStarted () const
bool IsFinished () const
bool IsAnimating () const
bool DrawNextImage () const
int GetWidth () const
int GetHeight () const
void Keep ()
bool StartTransition ()
int GetTransitionTime (int iType) const
void SetTransitionTime (int iType, int iTime)
int SlideNumber () const
void Zoom (float fZoomAmount, bool immediate=false)
void Rotate (float fRotateAngle, bool immediate=false)
void UpdateAlpha ()
void Pause (bool bPause)
void SetInSlideshow (bool slideshow)
void SetOriginalSize (int iOriginalWidth, int iOriginalHeight, bool bFullSize)
bool FullSize () const
int GetOriginalWidth ()
int GetOriginalHeight ()
void Move (float dX, float dY)
float GetZoom () const
Protected Member Functions
void Render (float *x, float *y, CTexture *pTexture, KODI::UTILS::COLOR::Color color) override
Private Member Functions
bool UpdateVertexBuffer (Vertex *vertices)
Private Attributes
Microsoft::WRL::ComPtr< ID3D11Buffer > m_vb
Additional Inherited Members
Public Types inherited from CSlideShowPic
enum DISPLAY_EFFECT {
EFFECT_NONE = 0 , EFFECT_FLOAT , EFFECT_ZOOM , EFFECT_RANDOM ,
EFFECT_PANORAMA , EFFECT_NO_TIMEOUT
}
enum TRANSITION_EFFECT {
TRANSITION_NONE = 0 , FADEIN_FADEOUT , CROSSFADE , TRANSITION_ZOOM ,
TRANSITION_ROTATE
}
Static Public Member Functions inherited from CSlideShowPic
static std::unique_ptr< CSlideShowPic > CreateSlideShowPicture ()
Public Attributes inherited from CSlideShowPic
bool m_bIsComic
bool m_bCanMoveHorizontally
bool m_bCanMoveVertically
Constructor & Destructor Documentation
CSlideShowPicDX()
CSlideShowPicDX::CSlideShowPicDX () default
~CSlideShowPicDX()
CSlideShowPicDX::~CSlideShowPicDX () override default
Member Function Documentation
Render()
void CSlideShowPicDX::Render (float * x, float * y, CTexture * pTexture, KODI::UTILS::COLOR::Color color) override protected virtual
Implements CSlideShowPic.
References CGUIShaderDX::Begin(), color, CGUIShaderDX::Draw(), CGUIShaderDX::DrawQuad(), DX::DeviceResources::Get(), CTextureBase::GetHeight(), CDXTexture::GetShaderResource(), CTextureBase::GetTextureHeight(), CTextureBase::GetTextureWidth(), CTextureBase::GetWidth(), CTexture::LoadToGPU(), m_vb, Vertex::pos, CGUIShaderDX::RestoreBuffers(), CGUIShaderDX::SetShaderViews(), SHADER_METHOD_RENDER_TEXTURE_BLEND, Vertex::texCoord, Vertex::texCoord2, UpdateVertexBuffer(), and CD3DHelper::XMStoreColor().
UpdateVertexBuffer()
bool CSlideShowPicDX::UpdateVertexBuffer (Vertex * vertices) private
References DX::DeviceResources::Get(), and m_vb.
Referenced by Render().
Member Data Documentation
m_vb
Microsoft::WRL::ComPtr<ID3D11Buffer> CSlideShowPicDX::m_vb private
Referenced by Render(), and UpdateVertexBuffer().
The documentation for this class was generated from the following files:
SlideShowPictureDX.h
SlideShowPictureDX.cpp