Kodi Documentation: CLunaPowerManagement Class Reference
CLunaPowerManagement Class Reference
#include <LunaPowerManagement.h>
Public Member Functions
bool CanPowerdown () override
bool CanSuspend () override
bool CanHibernate () override
bool CanReboot () override
bool Powerdown () override
bool Reboot () override
bool Suspend () override
bool Hibernate () override
int BatteryLevel () override
Public Member Functions inherited from CPowerSyscallWithoutEvents
CPowerSyscallWithoutEvents ()
bool Suspend () override
bool Hibernate () override
bool PumpPowerEvents (IPowerEventsCallback *callback) override
Pump power related events back to xbmc.
Public Member Functions inherited from CAbstractPowerSyscall
int CountPowerFeatures () override
Public Member Functions inherited from IPowerSyscall
virtual ~IPowerSyscall ()=default
Static Public Member Functions
static IPowerSyscall * CreateInstance ()
static void Register ()
Static Public Member Functions inherited from IPowerSyscall
static IPowerSyscall * CreateInstance ()
Called by power manager to create platform power system adapter.
static void RegisterPowerSyscall (CreatePowerSyscallFunc createFunc)
Additional Inherited Members
Static Public Attributes inherited from IPowerSyscall
static const int MAX_COUNT_POWER_FEATURES = 4
Member Function Documentation
BatteryLevel()
int CLunaPowerManagement::BatteryLevel (void) inline override virtual
Implements IPowerSyscall.
CanHibernate()
bool CLunaPowerManagement::CanHibernate (void) inline override virtual
Implements IPowerSyscall.
CanPowerdown()
bool CLunaPowerManagement::CanPowerdown (void) inline override virtual
Implements IPowerSyscall.
CanReboot()
bool CLunaPowerManagement::CanReboot (void) inline override virtual
Implements IPowerSyscall.
CanSuspend()
bool CLunaPowerManagement::CanSuspend (void) inline override virtual
Implements IPowerSyscall.
CreateInstance()
IPowerSyscall * CLunaPowerManagement::CreateInstance () static
Referenced by Register().
Hibernate()
bool CLunaPowerManagement::Hibernate (void) inline override virtual
Implements IPowerSyscall.
Powerdown()
bool CLunaPowerManagement::Powerdown (void) override virtual
Implements IPowerSyscall.
References shutdown(), and CJSONVariantWriter::Write().
Reboot()
bool CLunaPowerManagement::Reboot (void) override virtual
Implements IPowerSyscall.
References CJSONVariantWriter::Write().
Register()
void CLunaPowerManagement::Register () static
References CreateInstance(), and IPowerSyscall::RegisterPowerSyscall().
Referenced by CPlatformWebOS::RegisterPowerManagement().
Suspend()
bool CLunaPowerManagement::Suspend (void) inline override virtual
Implements IPowerSyscall.
The documentation for this class was generated from the following files:
LunaPowerManagement.h
LunaPowerManagement.cpp