Kodi Documentation: PVR::CPVRTimerInfoTag Class Reference
PVR::CPVRTimerInfoTag Class Reference final
#include <PVRTimerInfoTag.h>
Classes
struct CustomPropDetails
custom property detail: type, value
Public Types
using CustomPropsMap = std::map< unsigned int, CustomPropDetails >
custom properties map: <prop id, details>
Public Member Functions
CPVRTimerInfoTag (bool bRadio=false)
CPVRTimerInfoTag (const PVR_TIMER &timer, const std::shared_ptr< CPVRChannel > &channel, unsigned int iClientId)
bool operator== (const CPVRTimerInfoTag &right) const
bool operator!= (const CPVRTimerInfoTag &right) const
void Serialize (CVariant &value) const override
void SetEpgInfoTag (const std::shared_ptr< CPVREpgInfoTag > &tag)
Associate the given epg tag with this timer.
std::shared_ptr< CPVREpgInfoTag > GetEpgInfoTag (bool bCreate=true) const
get the epg info tag associated with this timer, if any
bool UpdateEntry (const std::shared_ptr< const CPVRTimerInfoTag > &tag)
updates this timer excluding the state of any children.
bool UpdateChildState (const std::shared_ptr< const CPVRTimerInfoTag > &childTimer, bool bAdd)
merge in the state of this child timer.
void ResetChildState ()
reset the state of children related to this timer.
bool IsActive () const
Whether this timer is active.
bool IsBroken () const
Whether this timer is broken.
bool HasConflict () const
Whether this timer has a conflict.
bool IsRecording () const
Whether this timer is currently recording.
bool IsDisabled () const
Whether this timer is disabled, for example by the user.
const std::shared_ptr< CPVRTimerType > GetTimerType () const
Gets the type of this timer.
void SetTimerType (const std::shared_ptr< CPVRTimerType > &type)
Sets the type of this timer.
bool IsTimerRule () const
Checks whether this is a timer rule (vs. one time timer).
bool IsReminder () const
Checks whether this is a reminder timer (vs. recording timer).
bool IsManual () const
Checks whether this is a manual (vs. epg-based) timer.
bool IsEpgBased () const
Checks whether this is an epg-based (vs. manual) timer.
int ClientID () const
The ID of the client for this timer.
bool IsOwnedByClient () const
Check, whether this timer is owned by a pvr client or by Kodi.
bool IsRadio () const
Whether this timer is for Radio or TV.
const std::string & Path () const
The path that identifies this timer.
int ClientIndex () const
The index for this timer, as given by the client.
int ParentClientIndex () const
The index for the parent of this timer, as given by the client. Timers scheduled by a timer rule will have a parant index != PVR_TIMER_NO_PARENT.
bool HasParent () const
Whether this timer has a parent.
unsigned int TimerID () const
The local ID for this timer, as given by Kodi.
void SetTimerID (unsigned int id)
Set the local ID for this timer.
int ClientChannelUID () const
The UID of the channel for this timer.
PVR_TIMER_STATE State () const
The state for this timer.
void SetState (PVR_TIMER_STATE state)
Set the state for this timer.
const std::string & Title () const
The title for this timer.
bool HasChannel () const
Check whether this timer has an associated channel.
std::shared_ptr< CPVRChannel > Channel () const
Get the channel associated with this timer, if any.
void UpdateChannel ()
Update the channel associated with this timer, based on current client ID and channel UID.
std::string ChannelName () const
The name of the channel associated with this timer, if any.
std::string ChannelIcon () const
The path for the channel icon associated with this timer, if any.
CDateTime StartAsUTC () const
The start date and time for this timer, as UTC.
CDateTime StartAsLocalTime () const
The start date and time for this timer, as local time.
void SetStartFromUTC (const CDateTime &start)
Set the start date and time from a CDateTime instance carrying the data as UTC.
void SetStartFromLocalTime (const CDateTime &start)
Set the start date and time from a CDateTime instance carrying the data as local time.
CDateTime EndAsUTC () const
The end date and time for this timer, as UTC.
CDateTime EndAsLocalTime () const
The end date and time for this timer, as local time.
void SetEndFromUTC (const CDateTime &end)
Set the end date and time from a CDateTime instance carrying the data as UTC.
void SetEndFromLocalTime (const CDateTime &end)
Set the end date and time from a CDateTime instance carrying the data as local time.
CDateTime FirstDayAsUTC () const
The first day for this timer, as UTC.
CDateTime FirstDayAsLocalTime () const
The first day for this timer, as local time.
void SetFirstDayFromUTC (const CDateTime &firstDay)
Set the first dday from a CDateTime instance carrying the data as UTC.
void SetFirstDayFromLocalTime (const CDateTime &firstDay)
Set the first dday from a CDateTime instance carrying the data as local time.
int GetDuration () const
Get the duration of this timer in seconds, excluding padding times.
unsigned int MarginStart () const
Get time in minutes to start the recording before the start time of the programme.
unsigned int MarginEnd () const
Get time in minutes to end the recording after the end time of the programme.
unsigned int WeekDays () const
For timer rules, the days of week this timer rule is scheduled for.
bool IsStartAnyTime () const
For timer rules, whether start time is "any time", not a particular time.
bool IsEndAnyTime () const
For timer rules, whether end time is "any time", not a particular time.
bool IsFullTextEpgSearch () const
For timer rules, whether only the EPG programme title shall be searched or also other data like the programme's plot, if available.
const std::string & EpgSearchString () const
For timer rules, the epg data match string for searches. Format is backend-dependent, for example regexp.
const std::string & SeriesLink () const
The series link for this timer.
const std::string & Directory () const
The directory for the recordings for this timer.
int Priority () const
The priority for this timer.
int Lifetime () const
The life time for this timer.
int MaxRecordings () const
The maximum number of recordings for this timer.
int PreventDupEpisodesPolicy () const
The policy to be used to prevent duplicate episodes for this timer.
int RecordingGroup () const
The recording group for this timer.
const CustomPropsMap & GetCustomProperties () const
Get custom properties for this tag.
unsigned int UniqueBroadcastID () const
Get the UID of the epg event associated with this timer tag, if any.
bool AddToClient () const
Add this timer to the backend, transferring all local data of this timer to the backend.
TimerOperationResult DeleteFromClient (bool bForce=false) const
Delete this timer on the backend.
bool UpdateOnClient ()
Update this timer on the backend, transferring all local data of this timer to the backend.
bool Persist ()
Persist this timer in the local database.
bool DeleteFromDatabase ()
Delete this timer from the local database.
std::string GetNotificationText () const
GUI support: Get the text for the timer GUI notification.
std::string GetDeletedNotificationText () const
GUI support: Get the text for the timer GUI notification when a timer has been deleted.
const std::string & Summary () const
GUI support: Get the summary text for this timer, reflecting the timer schedule in a human readable form.
void UpdateSummary ()
GUI support: Update the summary text for this timer.
std::string GetStatus (bool bRadio) const
GUI support: Get the status text for this timer, reflecting its current state in a human readable form.
std::string GetTypeAsString () const
GUI support: Get the timer string in a human readable form.
Static Public Member Functions
static std::shared_ptr< CPVRTimerInfoTag > CreateInstantTimerTag (const std::shared_ptr< CPVRChannel > &channel, int iDuration=DEFAULT_PVRRECORD_INSTANTRECORDTIME)
create a tag for an instant timer for a given channel
static std::shared_ptr< CPVRTimerInfoTag > CreateTimerTag (const std::shared_ptr< CPVRChannel > &channel, const CDateTime &start, int iDuration)
create a tag for a timer for a given channel at given time for given duration
static std::shared_ptr< CPVRTimerInfoTag > CreateFromEpg (const std::shared_ptr< CPVREpgInfoTag > &tag, bool bCreateRule, bool bCreateReminder, bool bReadOnly=false)
create a recording or reminder timer or timer rule for the given epg info tag.
static std::shared_ptr< CPVRTimerInfoTag > CreateFromEpg (const std::shared_ptr< CPVREpgInfoTag > &tag, bool bCreateRule=false)
create a timer or timer rule for the given epg info tag.
static std::shared_ptr< CPVRTimerInfoTag > CreateReminderFromDate (const CDateTime &start, int iDuration, const std::shared_ptr< CPVRTimerInfoTag > &parent=std::shared_ptr< CPVRTimerInfoTag >())
create a reminder timer for the given start date.
static std::shared_ptr< CPVRTimerInfoTag > CreateReminderFromEpg (const std::shared_ptr< CPVREpgInfoTag > &tag, const std::shared_ptr< CPVRTimerInfoTag > &parent=std::shared_ptr< CPVRTimerInfoTag >())
create a reminder timer for the given epg info tag.
static CDateTime ConvertUTCToLocalTime (const CDateTime &utc)
Helper function to convert a given CDateTime containing data as UTC to local time.
static CDateTime ConvertLocalTimeToUTC (const CDateTime &local)
Helper function to convert a given CDateTime containing data as local time to UTC.
static std::string GetWeekdaysString (unsigned int iWeekdays, bool bEpgBased, bool bLongMultiDaysFormat)
GUI support: Return string representation for any possible combination of weekdays.
Static Public Attributes
static constexpr int DEFAULT_PVRRECORD_INSTANTRECORDTIME = -1
Private Member Functions
CPVRTimerInfoTag (const CPVRTimerInfoTag &tag)=delete
CPVRTimerInfoTag & operator= (const CPVRTimerInfoTag &orig)=delete
std::string GetWeekdaysString () const
void UpdateEpgInfoTag ()
Static Private Member Functions
static std::shared_ptr< CPVRTimerInfoTag > CreateFromDate (const std::shared_ptr< CPVRChannel > &channel, const CDateTime &start, int iDuration, bool bCreateReminder, bool bReadOnly)
Private Attributes
CCriticalSection m_critSection
std::string m_strTitle
name of this timer
std::string m_strEpgSearchString
a epg data match string for epg-based timer rules. Format is backend-dependent, for example regexp
bool m_bFullTextEpgSearch
indicates whether only epg episode title can be matched by the pvr backend or "more" (backend-dependent") data.
std::string m_strDirectory
directory where the recording must be stored
std::string m_strSummary
summary string with the time to show inside a GUI list
PVR_TIMER_STATE m_state = PVR_TIMER_STATE_SCHEDULED
the state of this timer
int m_iClientId
ID of the backend.
int m_iClientIndex
index number of the tag, given by the backend, PVR_TIMER_NO_CLIENT_INDEX for new
int m_iParentClientIndex
for timers scheduled by a timer rule, the index number of the parent, given by the backend, PVR_TIMER_NO_PARENT for no parent
int m_iClientChannelUid
channel uid
bool m_bStartAnyTime
Ignore start date and time clock. Record at 'Any Time'.
bool m_bEndAnyTime = false
Ignore end date and time clock. Record at 'Any Time'.
int m_iPriority
priority of the timer
int m_iLifetime
lifetime of the timer in days
int m_iMaxRecordings
(optional) backend setting for maximum number of recordings to keep
unsigned int m_iWeekdays
bit based store of weekdays for timer rules
unsigned int m_iPreventDupEpisodes
only record new episodes for epg-based timer rules
unsigned int m_iRecordingGroup
(optional) if set, the addon/backend stores the recording to a group (sub-folder)
std::string m_strFileNameAndPath
file name is only for reference
bool m_bIsRadio
is radio channel if set
unsigned int m_iTimerId = 0
id that won't change as long as Kodi is running
unsigned int m_iMarginStart
(optional) if set, the backend starts the recording iMarginStart minutes before startTime.
unsigned int m_iMarginEnd
(optional) if set, the backend ends the recording iMarginEnd minutes after endTime.
unsigned int m_iEpgUid
std::string m_strSeriesLink
CustomPropsMap m_customProps
CDateTime m_StartTime
CDateTime m_StopTime
CDateTime m_FirstDay
std::shared_ptr< CPVRTimerType > m_timerType
unsigned int m_iTVChildTimersActive = 0
unsigned int m_iTVChildTimersConflictNOK = 0
unsigned int m_iTVChildTimersRecording = 0
unsigned int m_iTVChildTimersErrors = 0
unsigned int m_iRadioChildTimersActive = 0
unsigned int m_iRadioChildTimersConflictNOK = 0
unsigned int m_iRadioChildTimersRecording = 0
unsigned int m_iRadioChildTimersErrors = 0
std::shared_ptr< CPVREpgInfoTag > m_epgTag
std::shared_ptr< CPVRChannel > m_channel
bool m_bProbedEpgTag = false
Friends
class CGUIDialogPVRTimerSettings
class CPVRDatabase
Additional Inherited Members
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Member Typedef Documentation
CustomPropsMap
using PVR::CPVRTimerInfoTag::CustomPropsMap = std::map<unsigned int, CustomPropDetails>
custom properties map: <prop id, details>
Constructor & Destructor Documentation
CPVRTimerInfoTag() [1/3]
CPVRTimerInfoTag::CPVRTimerInfoTag (bool bRadio = false) explicit
References PVR::CPVRTimerType::CreateFromAttributes(), PVR::CPVRManager::GetClient(), PVR::CPVRTimerType::GetFirstAvailableType(), CServiceBroker::GetPVRManager(), LOGERROR, m_iClientId, m_iWeekdays, m_timerType, PVR_TIMER_TYPE_FORBIDS_NEW_INSTANCES, PVR_TIMER_TYPE_IS_MANUAL, PVR_TIMER_TYPE_IS_REMINDER, PVR_TIMER_TYPE_IS_REPEATING, PVR_WEEKDAY_ALLDAYS, PVR_WEEKDAY_NONE, SetTimerType(), and UpdateSummary().
CPVRTimerInfoTag() [2/3]
CPVRTimerInfoTag::CPVRTimerInfoTag (const PVR_TIMER & timer, const std::shared_ptr< CPVRChannel > & channel, unsigned int iClientId)
References PVR::CPVRTimerType::CreateFromAttributes(), PVR::CPVRTimerType::CreateFromIds(), PVR_TIMER::customProps, EPG_TAG_INVALID_UID, PVR_TIMER::firstDay, PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), CDateTime::GetUTCDateTime(), PVR_TIMER::iCustomPropsSize, PVR_TIMER::iEpgUid, PVR_TIMER::iTimerType, PVR_TIMER::iWeekdays, LOGERROR, m_customProps, m_FirstDay, m_iClientId, m_iClientIndex, m_iEpgUid, m_timerType, PVR_TIMER_NO_CLIENT_INDEX, PVR_TIMER_NO_EPG_UID, PVR_TIMER_TYPE_ATTRIBUTE_NONE, PVR_TIMER_TYPE_FORBIDS_NEW_INSTANCES, PVR_TIMER_TYPE_IS_MANUAL, PVR_TIMER_TYPE_IS_REPEATING, PVR_TIMER_TYPE_NONE, PVR_WEEKDAY_NONE, SetTimerType(), UpdateEpgInfoTag(), and UpdateSummary().
CPVRTimerInfoTag() [3/3]
PVR::CPVRTimerInfoTag::CPVRTimerInfoTag (const CPVRTimerInfoTag & tag) private delete
Member Function Documentation
AddToClient()
bool CPVRTimerInfoTag::AddToClient () const
Add this timer to the backend, transferring all local data of this timer to the backend.
Returns
True on success, false otherwise.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_iClientId, and PVR_ERROR_NO_ERROR.
Channel()
std::shared_ptr< CPVRChannel > CPVRTimerInfoTag::Channel () const
Get the channel associated with this timer, if any.
Returns
the channel or null if non is associated with this timer.
References m_channel.
Referenced by ChannelIcon(), and ChannelName().
ChannelIcon()
std::string CPVRTimerInfoTag::ChannelIcon () const
The path for the channel icon associated with this timer, if any.
Returns
The channel icon path.
References Channel().
ChannelName()
std::string CPVRTimerInfoTag::ChannelName () const
The name of the channel associated with this timer, if any.
Returns
The channel name.
References Channel(), g_localizeStrings, CLocalizeStrings::Get(), and m_timerType.
ClientChannelUID()
int PVR::CPVRTimerInfoTag::ClientChannelUID () const inline
The UID of the channel for this timer.
Returns
The channel UID or PVR_CHANNEL_INVALID_UID if not available.
References m_iClientChannelUid.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
ClientID()
int PVR::CPVRTimerInfoTag::ClientID () const inline
The ID of the client for this timer.
Returns
The client ID or PVR_CLIENT_INVALID_UID if this is a local timer.
References m_iClientId.
ClientIndex()
int PVR::CPVRTimerInfoTag::ClientIndex () const inline
The index for this timer, as given by the client.
Returns
The client index or PVR_TIMER_NO_CLIENT_INDEX if the timer was just created locally by Kodi and was not yet added by the client.
References m_iClientIndex.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
ConvertLocalTimeToUTC()
CDateTime CPVRTimerInfoTag::ConvertLocalTimeToUTC (const CDateTime & local) static
Helper function to convert a given CDateTime containing data as local time to UTC.
Parameters
local A CDateTime instance carrying data as local time.
Returns
A CDateTime instance carrying data as UTC.
References CDateTime::GetAsTime(), and LOGWARNING.
Referenced by SetEndFromLocalTime(), SetFirstDayFromLocalTime(), and SetStartFromLocalTime().
ConvertUTCToLocalTime()
CDateTime CPVRTimerInfoTag::ConvertUTCToLocalTime (const CDateTime & utc) static
Helper function to convert a given CDateTime containing data as UTC to local time.
Parameters
utc A CDateTime instance carrying data as UTC.
Returns
A CDateTime instance carrying data as local time.
References CDateTime::GetAsTime(), and LOGWARNING.
Referenced by EndAsLocalTime(), FirstDayAsLocalTime(), PVR::CPVRTimerRuleMatcher::MatchDayOfWeek(), PVR::CPVRTimerRuleMatcher::MatchEnd(), PVR::CPVRTimerRuleMatcher::Matches(), PVR::CPVRTimerRuleMatcher::MatchStart(), and StartAsLocalTime().
CreateFromDate()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimerInfoTag::CreateFromDate (const std::shared_ptr< CPVRChannel > & channel, const CDateTime & start, int iDuration, bool bCreateReminder, bool bReadOnly) static private
References PVR::CPVRTimerType::CreateFromAttributes(), CreateFromEpg(), DEFAULT_PVRRECORD_INSTANTRECORDTIME, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetSettingsComponent(), CDateTime::GetUTCDateTime(), INSTANT_TIMER_START, LOGERROR, PVR::CPVRTimersPath::PATH_NEW, PVR_TIMER_NO_CLIENT_INDEX, PVR_TIMER_NO_PARENT, PVR_TIMER_TYPE_FORBIDS_NEW_INSTANCES, PVR_TIMER_TYPE_IS_MANUAL, PVR_TIMER_TYPE_IS_READONLY, PVR_TIMER_TYPE_IS_REMINDER, PVR_TIMER_TYPE_IS_REPEATING, and CSettings::SETTING_PVRRECORD_INSTANTRECORDTIME.
Referenced by CreateInstantTimerTag(), CreateReminderFromDate(), and CreateTimerTag().
CreateFromEpg() [1/2]
std::shared_ptr< CPVRTimerInfoTag > CPVRTimerInfoTag::CreateFromEpg (const std::shared_ptr< CPVREpgInfoTag > & tag, bool bCreateRule, bool bCreateReminder, bool bReadOnly = false) static
create a recording or reminder timer or timer rule for the given epg info tag.
Parameters
tag the epg info tag
bCreateRule if true, create a timer rule, create a one shot timer otherwise
bCreateReminder if true, create a reminder timer or rule, create a recording timer or rule otherwise
bReadOnly whether the timer/rule is read only
Returns
the timer or null if timer could not be created
References PVR::CPVRManager::ChannelGroups(), PVR::CPVRTimerType::CreateFromAttributes(), CServiceBroker::GetPVRManager(), LOGERROR, PVR::CPVRTimersPath::PATH_NEW, PVR_TIMER_NO_CLIENT_INDEX, PVR_TIMER_NO_PARENT, PVR_TIMER_TYPE_ATTRIBUTE_NONE, PVR_TIMER_TYPE_FORBIDS_EPG_TAG_ON_CREATE, PVR_TIMER_TYPE_FORBIDS_NEW_INSTANCES, PVR_TIMER_TYPE_IS_MANUAL, PVR_TIMER_TYPE_IS_READONLY, PVR_TIMER_TYPE_IS_REMINDER, PVR_TIMER_TYPE_IS_REPEATING, PVR_TIMER_TYPE_REQUIRES_EPG_SERIESLINK_ON_CREATE, and PVR_WEEKDAY_ALLDAYS.
Referenced by PVR::CPVRGUIActionsTimers::AddTimer(), JSONRPC::CPVROperations::AddTimer(), PVR::CPVRGUIActionsTimers::AnnounceReminder(), CreateFromDate(), CreateFromEpg(), CreateReminderFromEpg(), PVR::CPVRGUIActionsTimers::SetRecordingOnChannel(), and JSONRPC::CPVROperations::ToggleTimer().
CreateFromEpg() [2/2]
std::shared_ptr< CPVRTimerInfoTag > CPVRTimerInfoTag::CreateFromEpg (const std::shared_ptr< CPVREpgInfoTag > & tag, bool bCreateRule = false) static
create a timer or timer rule for the given epg info tag.
Parameters
tag the epg info tag
bCreateRule if true, create a timer rule, create a one shot timer otherwise
Returns
the timer or null if timer could not be created
References CreateFromEpg().
CreateInstantTimerTag()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimerInfoTag::CreateInstantTimerTag (const std::shared_ptr< CPVRChannel > & channel, int iDuration = DEFAULT_PVRRECORD_INSTANTRECORDTIME) static
create a tag for an instant timer for a given channel
Parameters
channel is the channel the instant timer is to be created for
iDuration is the duration for the instant timer, DEFAULT_PVRRECORD_INSTANTRECORDTIME denotes system default (setting value)
Returns
the timer or null if timer could not be created
References CreateFromDate(), and INSTANT_TIMER_START.
Referenced by PVR::CPVRGUIActionsTimers::AddTimer(), and PVR::CPVRGUIActionsTimers::SetRecordingOnChannel().
CreateReminderFromDate()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimerInfoTag::CreateReminderFromDate (const CDateTime & start, int iDuration, const std::shared_ptr< CPVRTimerInfoTag > & parent = std::shared_ptr<CPVRTimerInfoTag>()) static
create a reminder timer for the given start date.
Parameters
start the start date
iDuration the duration the reminder is valid
parent If non-zero, the new timer will be made a child of the given timer rule
Returns
the timer or null if timer could not be created
References CreateFromDate().
Referenced by PVR::CPVRTimers::AddLocalTimer(), and PVR::CPVRTimers::UpdateEntries().
CreateReminderFromEpg()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimerInfoTag::CreateReminderFromEpg (const std::shared_ptr< CPVREpgInfoTag > & tag, const std::shared_ptr< CPVRTimerInfoTag > & parent = std::shared_ptr<CPVRTimerInfoTag>()) static
create a reminder timer for the given epg info tag.
Parameters
tag the epg info tag
parent If non-zero, the new timer will be made a child of the given timer rule
Returns
the timer or null if timer could not be created
References CreateFromEpg().
Referenced by PVR::CPVRTimers::AddLocalTimer(), PVR::CPVRGUIActionsTimers::AddReminder(), and PVR::CPVRTimers::UpdateEntries().
CreateTimerTag()
std::shared_ptr< CPVRTimerInfoTag > CPVRTimerInfoTag::CreateTimerTag (const std::shared_ptr< CPVRChannel > & channel, const CDateTime & start, int iDuration) static
create a tag for a timer for a given channel at given time for given duration
Parameters
channel is the channel the timer is to be created for
start is the start time for the recording
iDuration is the duration of the recording
Returns
the timer or null if timer could not be created
References CreateFromDate().
Referenced by PVR::CPVRGUIActionsTimers::AddTimer(), and PVR::CPVRGUIActionsTimers::AnnounceReminder().
DeleteFromClient()
TimerOperationResult CPVRTimerInfoTag::DeleteFromClient (bool bForce = false) const
Delete this timer on the backend.
Parameters
bForce Control what to do in case the timer is currently recording. True to force to delete the timer, false to return TimerDeleteResult::RECORDING.
Returns
The result.
References PVR::FAILED, PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_iClientId, PVR::OK, PVR_ERROR_NO_ERROR, PVR_ERROR_RECORDING_RUNNING, PVR_ERROR_UNKNOWN, and PVR::RECORDING.
DeleteFromDatabase()
bool CPVRTimerInfoTag::DeleteFromDatabase ()
Delete this timer from the local database.
Returns
True on success, false otherwise.
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::GetTVDatabase().
Directory()
const std::string & PVR::CPVRTimerInfoTag::Directory () const inline
The directory for the recordings for this timer.
Returns
The directory.
References m_strDirectory.
EndAsLocalTime()
CDateTime CPVRTimerInfoTag::EndAsLocalTime () const
The end date and time for this timer, as local time.
Returns
The start date and time.
References ConvertUTCToLocalTime(), and m_StopTime.
Referenced by UpdateSummary().
EndAsUTC()
CDateTime CPVRTimerInfoTag::EndAsUTC () const
The end date and time for this timer, as UTC.
Returns
The start date and time.
References m_StopTime.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer(), GetEpgInfoTag(), and PVR::CPVRDatabase::Persist().
EpgSearchString()
const std::string & PVR::CPVRTimerInfoTag::EpgSearchString () const inline
For timer rules, the epg data match string for searches. Format is backend-dependent, for example regexp.
Returns
The search string
References m_strEpgSearchString.
FirstDayAsLocalTime()
CDateTime CPVRTimerInfoTag::FirstDayAsLocalTime () const
The first day for this timer, as local time.
Returns
The first day.
References ConvertUTCToLocalTime(), and m_FirstDay.
FirstDayAsUTC()
CDateTime CPVRTimerInfoTag::FirstDayAsUTC () const
The first day for this timer, as UTC.
Returns
The first day.
References m_FirstDay.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer(), and PVR::CPVRDatabase::Persist().
GetCustomProperties()
const CustomPropsMap & PVR::CPVRTimerInfoTag::GetCustomProperties () const inline
Get custom properties for this tag.
Returns
The list of properties or an empty list if none present.
References m_customProps.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
GetDeletedNotificationText()
std::string CPVRTimerInfoTag::GetDeletedNotificationText () const
GUI support: Get the text for the timer GUI notification when a timer has been deleted.
Returns
The notification text.
References g_localizeStrings, CLocalizeStrings::Get(), IsTimerRule(), m_critSection, m_state, m_strTitle, PVR_TIMER_STATE_RECORDING, and PVR_TIMER_STATE_SCHEDULED.
GetDuration()
int CPVRTimerInfoTag::GetDuration () const
Get the duration of this timer in seconds, excluding padding times.
Returns
The duration.
References end(), CDateTime::GetAsTime(), m_StartTime, and m_StopTime.
GetEpgInfoTag()
std::shared_ptr< CPVREpgInfoTag > CPVRTimerInfoTag::GetEpgInfoTag (bool bCreate = true) const
get the epg info tag associated with this timer, if any
Parameters
bCreate if true, try to find the epg tag if not yet set (lazy evaluation)
Returns
the epg info tag associated with this timer or null if there is no tag
References PVR::CPVRManager::ChannelGroups(), EndAsUTC(), EPG_TAG_INVALID_UID, CDateTime::GetAsTime(), CServiceBroker::GetPVRManager(), IsOwnedByClient(), IsTimerRule(), m_bIsRadio, m_bProbedEpgTag, m_channel, m_critSection, m_epgTag, m_iClientChannelUid, m_iClientId, m_iEpgUid, and StartAsUTC().
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer(), and UpdateEpgInfoTag().
GetNotificationText()
std::string CPVRTimerInfoTag::GetNotificationText () const
GUI support: Get the text for the timer GUI notification.
Returns
The notification text.
References g_localizeStrings, CLocalizeStrings::Get(), IsTimerRule(), m_critSection, m_state, m_strTitle, PVR_TIMER_STATE_ABORTED, PVR_TIMER_STATE_CANCELLED, PVR_TIMER_STATE_COMPLETED, PVR_TIMER_STATE_CONFLICT_NOK, PVR_TIMER_STATE_CONFLICT_OK, PVR_TIMER_STATE_DISABLED, PVR_TIMER_STATE_ERROR, PVR_TIMER_STATE_RECORDING, and PVR_TIMER_STATE_SCHEDULED.
GetStatus()
std::string CPVRTimerInfoTag::GetStatus (bool bRadio) const
GUI support: Get the status text for this timer, reflecting its current state in a human readable form.
Returns
The status string.
References g_localizeStrings, CLocalizeStrings::Get(), m_critSection, m_iRadioChildTimersActive, m_iRadioChildTimersConflictNOK, m_iRadioChildTimersErrors, m_iRadioChildTimersRecording, m_iTVChildTimersActive, m_iTVChildTimersConflictNOK, m_iTVChildTimersErrors, m_iTVChildTimersRecording, m_state, m_strFileNameAndPath, PVR::CPVRTimersPath::PATH_ADDTIMER, URIUtils::PathEquals(), PVR_TIMER_STATE_ABORTED, PVR_TIMER_STATE_CANCELLED, PVR_TIMER_STATE_COMPLETED, PVR_TIMER_STATE_CONFLICT_NOK, PVR_TIMER_STATE_CONFLICT_OK, PVR_TIMER_STATE_DISABLED, PVR_TIMER_STATE_ERROR, PVR_TIMER_STATE_NEW, PVR_TIMER_STATE_RECORDING, and PVR_TIMER_STATE_SCHEDULED.
GetTimerType()
const std::shared_ptr< CPVRTimerType > PVR::CPVRTimerInfoTag::GetTimerType () const inline
Gets the type of this timer.
Returns
the timer type or NULL if this tag has no timer type.
References m_timerType.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer(), and PVR::CPVRDatabase::Persist().
GetTypeAsString()
std::string CPVRTimerInfoTag::GetTypeAsString () const
GUI support: Get the timer string in a human readable form.
Returns
The type string.
Get the type string of this timer
References m_critSection, and m_timerType.
GetWeekdaysString() [1/2]
std::string CPVRTimerInfoTag::GetWeekdaysString () const private
References GetWeekdaysString(), m_critSection, m_iWeekdays, and m_timerType.
Referenced by GetWeekdaysString(), UpdateSummary(), and PVR::CGUIDialogPVRTimerSettings::WeekdaysValueFormatter().
GetWeekdaysString() [2/2]
std::string CPVRTimerInfoTag::GetWeekdaysString (unsigned int iWeekdays, bool bEpgBased, bool bLongMultiDaysFormat) static
GUI support: Return string representation for any possible combination of weekdays.
Parameters
iWeekdays weekdays as bit mask (0x01 = Mo, 0x02 = Tu, ...)
bEpgBased context is an epg-based timer
bLongMultiDaysFormat use long format. ("Mo-__-We-__-Fr-Sa-__" vs. "Mo-We-Fr-Sa")
Returns
The weekdays string representation.
References g_localizeStrings, CLocalizeStrings::Get(), PVR_WEEKDAY_ALLDAYS, PVR_WEEKDAY_FRIDAY, PVR_WEEKDAY_MONDAY, PVR_WEEKDAY_NONE, PVR_WEEKDAY_SATURDAY, PVR_WEEKDAY_SUNDAY, PVR_WEEKDAY_THURSDAY, PVR_WEEKDAY_TUESDAY, and PVR_WEEKDAY_WEDNESDAY.
HasChannel()
bool CPVRTimerInfoTag::HasChannel () const
Check whether this timer has an associated channel.
Returns
True if this timer has a channel set, false otherwise.
References m_channel.
HasConflict()
bool PVR::CPVRTimerInfoTag::HasConflict () const inline
Whether this timer has a conflict.
Returns
True if this timer won't result in a recording because it is in conflict with another timer or live stream, false otherwise.
References m_state, and PVR_TIMER_STATE_CONFLICT_NOK.
HasParent()
bool PVR::CPVRTimerInfoTag::HasParent () const inline
Whether this timer has a parent.
Returns
True if timer has a parent, false otherwise.
References m_iParentClientIndex, and PVR_TIMER_NO_PARENT.
IsActive()
bool PVR::CPVRTimerInfoTag::IsActive () const inline
Whether this timer is active.
Returns
True if this timer is active, false otherwise.
References m_state, PVR_TIMER_STATE_CONFLICT_NOK, PVR_TIMER_STATE_CONFLICT_OK, PVR_TIMER_STATE_ERROR, PVR_TIMER_STATE_RECORDING, and PVR_TIMER_STATE_SCHEDULED.
IsBroken()
bool PVR::CPVRTimerInfoTag::IsBroken () const inline
Whether this timer is broken.
Returns
True if this timer won't result in a recording because it is broken for some reason, false otherwise
References m_state, PVR_TIMER_STATE_CONFLICT_NOK, and PVR_TIMER_STATE_ERROR.
IsDisabled()
bool PVR::CPVRTimerInfoTag::IsDisabled () const inline
Whether this timer is disabled, for example by the user.
Returns
True if disabled, false otherwise.
References m_state, and PVR_TIMER_STATE_DISABLED.
IsEndAnyTime()
bool PVR::CPVRTimerInfoTag::IsEndAnyTime () const inline
For timer rules, whether end time is "any time", not a particular time.
Returns
True, if timer end is "any time", false otherwise.
References m_bEndAnyTime.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
IsEpgBased()
bool PVR::CPVRTimerInfoTag::IsEpgBased () const inline
Checks whether this is an epg-based (vs. manual) timer.
Returns
True if this is an epg-Based timer, false otherwise.
References IsManual().
IsFullTextEpgSearch()
bool PVR::CPVRTimerInfoTag::IsFullTextEpgSearch () const inline
For timer rules, whether only the EPG programme title shall be searched or also other data like the programme's plot, if available.
Returns
True, if not only the programme's title shall be included in EPG search, false otherwise.
References m_bFullTextEpgSearch.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
IsManual()
bool PVR::CPVRTimerInfoTag::IsManual () const inline
Checks whether this is a manual (vs. epg-based) timer.
Returns
True if this is a manual timer, false otherwise.
References m_timerType.
Referenced by IsEpgBased().
IsOwnedByClient()
bool CPVRTimerInfoTag::IsOwnedByClient () const
Check, whether this timer is owned by a pvr client or by Kodi.
Returns
True, if owned by a pvr client, false otherwise.
References m_timerType, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by GetEpgInfoTag().
IsRadio()
bool PVR::CPVRTimerInfoTag::IsRadio () const inline
Whether this timer is for Radio or TV.
Returns
True if Radio, false otherwise.
References m_bIsRadio.
IsRecording()
bool PVR::CPVRTimerInfoTag::IsRecording () const inline
Whether this timer is currently recording.
Returns
True if recording, false otherwise.
References m_state, and PVR_TIMER_STATE_RECORDING.
IsReminder()
bool PVR::CPVRTimerInfoTag::IsReminder () const inline
Checks whether this is a reminder timer (vs. recording timer).
Returns
True if this is a reminder timer, false otherwise.
References m_timerType.
IsStartAnyTime()
bool PVR::CPVRTimerInfoTag::IsStartAnyTime () const inline
For timer rules, whether start time is "any time", not a particular time.
Returns
True, if timer start is "any time", false otherwise.
References m_bStartAnyTime.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
IsTimerRule()
bool PVR::CPVRTimerInfoTag::IsTimerRule () const inline
Checks whether this is a timer rule (vs. one time timer).
Returns
True if this is a timer rule, false otherwise.
References m_timerType.
Referenced by GetDeletedNotificationText(), GetEpgInfoTag(), and GetNotificationText().
Lifetime()
int PVR::CPVRTimerInfoTag::Lifetime () const inline
The life time for this timer.
Returns
The life time.
References m_iLifetime.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
MarginEnd()
unsigned int PVR::CPVRTimerInfoTag::MarginEnd () const inline
Get time in minutes to end the recording after the end time of the programme.
Returns
The end padding time.
References m_iMarginEnd.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
MarginStart()
unsigned int PVR::CPVRTimerInfoTag::MarginStart () const inline
Get time in minutes to start the recording before the start time of the programme.
Returns
The start padding time.
References m_iMarginStart.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
MaxRecordings()
int PVR::CPVRTimerInfoTag::MaxRecordings () const inline
The maximum number of recordings for this timer.
Returns
The number of maximum recordings.
References m_iMaxRecordings.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
operator!=()
bool CPVRTimerInfoTag::operator!= (const CPVRTimerInfoTag & right) const
References right.
operator=()
CPVRTimerInfoTag & PVR::CPVRTimerInfoTag::operator= (const CPVRTimerInfoTag & orig) private delete
operator==()
bool CPVRTimerInfoTag::operator== (const CPVRTimerInfoTag & right) const
References m_bEndAnyTime, m_bFullTextEpgSearch, m_bIsRadio, m_bStartAnyTime, m_channel, m_customProps, m_FirstDay, m_iClientChannelUid, m_iClientId, m_iClientIndex, m_iEpgUid, m_iLifetime, m_iMarginEnd, m_iMarginStart, m_iMaxRecordings, m_iParentClientIndex, m_iPreventDupEpisodes, m_iPriority, m_iRadioChildTimersActive, m_iRadioChildTimersConflictNOK, m_iRadioChildTimersErrors, m_iRadioChildTimersRecording, m_iRecordingGroup, m_iTimerId, m_iTVChildTimersActive, m_iTVChildTimersConflictNOK, m_iTVChildTimersErrors, m_iTVChildTimersRecording, m_iWeekdays, m_StartTime, m_state, CDateTime::m_state, m_StopTime, m_strDirectory, m_strEpgSearchString, m_strFileNameAndPath, m_strSeriesLink, m_strSummary, m_strTitle, m_timerType, and right.
ParentClientIndex()
int PVR::CPVRTimerInfoTag::ParentClientIndex () const inline
The index for the parent of this timer, as given by the client. Timers scheduled by a timer rule will have a parant index != PVR_TIMER_NO_PARENT.
Returns
The client index or PVR_TIMER_NO_PARENT if the timer has no parent.
References m_iParentClientIndex.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
Path()
const std::string & CPVRTimerInfoTag::Path () const
The path that identifies this timer.
Returns
The path.
References m_strFileNameAndPath.
Persist()
bool CPVRTimerInfoTag::Persist ()
Persist this timer in the local database.
Returns
True on success, false otherwise.
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::GetTVDatabase().
PreventDupEpisodesPolicy()
int PVR::CPVRTimerInfoTag::PreventDupEpisodesPolicy () const inline
The policy to be used to prevent duplicate episodes for this timer.
Returns
The policy for preventing duplicate episodes.
References m_iPreventDupEpisodes.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
Priority()
int PVR::CPVRTimerInfoTag::Priority () const inline
The priority for this timer.
Returns
The priority.
References m_iPriority.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
RecordingGroup()
int PVR::CPVRTimerInfoTag::RecordingGroup () const inline
The recording group for this timer.
Returns
The recording group.
References m_iRecordingGroup.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
ResetChildState()
void CPVRTimerInfoTag::ResetChildState ()
reset the state of children related to this timer.
References m_iRadioChildTimersActive, m_iRadioChildTimersConflictNOK, m_iRadioChildTimersErrors, m_iRadioChildTimersRecording, m_iTVChildTimersActive, m_iTVChildTimersConflictNOK, m_iTVChildTimersErrors, and m_iTVChildTimersRecording.
Serialize()
void CPVRTimerInfoTag::Serialize (CVariant & value) const override virtual
Implements ISerializable.
References CDateTime::GetAsDBDate(), CDateTime::GetAsDBDateTime(), CDateTime::IsValid(), m_bEndAnyTime, m_bFullTextEpgSearch, m_bIsRadio, m_bStartAnyTime, m_channel, m_epgTag, m_FirstDay, m_iClientId, m_iEpgUid, m_iLifetime, m_iMarginEnd, m_iMarginStart, m_iMaxRecordings, m_iPreventDupEpisodes, m_iPriority, m_iRecordingGroup, m_iTimerId, m_iWeekdays, m_StartTime, m_state, m_StopTime, m_strDirectory, m_strEpgSearchString, m_strSeriesLink, m_strSummary, m_strTitle, m_timerType, CVariant::push_back(), PVR_TIMER_STATE_ABORTED, PVR_TIMER_STATE_CANCELLED, PVR_TIMER_STATE_COMPLETED, PVR_TIMER_STATE_CONFLICT_NOK, PVR_TIMER_STATE_CONFLICT_OK, PVR_TIMER_STATE_DISABLED, PVR_TIMER_STATE_ERROR, PVR_TIMER_STATE_NEW, PVR_TIMER_STATE_RECORDING, PVR_TIMER_STATE_SCHEDULED, PVR_WEEKDAY_FRIDAY, PVR_WEEKDAY_MONDAY, PVR_WEEKDAY_SATURDAY, PVR_WEEKDAY_SUNDAY, PVR_WEEKDAY_THURSDAY, PVR_WEEKDAY_TUESDAY, PVR_WEEKDAY_WEDNESDAY, value, and CVariant::VariantTypeArray.
SeriesLink()
const std::string & CPVRTimerInfoTag::SeriesLink () const
The series link for this timer.
Returns
The series link or empty string, if not available.
References m_strSeriesLink.
Referenced by PVR::CPVRDatabase::Persist().
SetEndFromLocalTime()
void CPVRTimerInfoTag::SetEndFromLocalTime (const CDateTime & end)
Set the end date and time from a CDateTime instance carrying the data as local time.
Parameters
start The end date and time as local time.
References ConvertLocalTimeToUTC(), end(), and m_StopTime.
SetEndFromUTC()
void CPVRTimerInfoTag::SetEndFromUTC (const CDateTime & end)
Set the end date and time from a CDateTime instance carrying the data as UTC.
Parameters
start The end date and time as UTC.
References end(), and m_StopTime.
SetEpgInfoTag()
void CPVRTimerInfoTag::SetEpgInfoTag (const std::shared_ptr< CPVREpgInfoTag > & tag)
Associate the given epg tag with this timer.
Parameters
tag The epg tag to assign.
References m_bProbedEpgTag, m_critSection, and m_epgTag.
SetFirstDayFromLocalTime()
void CPVRTimerInfoTag::SetFirstDayFromLocalTime (const CDateTime & firstDay)
Set the first dday from a CDateTime instance carrying the data as local time.
Parameters
start The first day as local time.
References ConvertLocalTimeToUTC(), and m_FirstDay.
SetFirstDayFromUTC()
void CPVRTimerInfoTag::SetFirstDayFromUTC (const CDateTime & firstDay)
Set the first dday from a CDateTime instance carrying the data as UTC.
Parameters
start The first day as UTC.
References m_FirstDay.
SetStartFromLocalTime()
void CPVRTimerInfoTag::SetStartFromLocalTime (const CDateTime & start)
Set the start date and time from a CDateTime instance carrying the data as local time.
Parameters
start The start date and time as local time.
References ConvertLocalTimeToUTC(), and m_StartTime.
SetStartFromUTC()
void CPVRTimerInfoTag::SetStartFromUTC (const CDateTime & start)
Set the start date and time from a CDateTime instance carrying the data as UTC.
Parameters
start The start date and time as UTC.
References m_StartTime.
SetState()
void PVR::CPVRTimerInfoTag::SetState (PVR_TIMER_STATE state) inline
Set the state for this timer.
Parameters
state The state to set.
References m_state.
SetTimerID()
void PVR::CPVRTimerInfoTag::SetTimerID (unsigned int id) inline
Set the local ID for this timer.
Parameters
id The ID to set.
References id, and m_iTimerId.
SetTimerType()
void CPVRTimerInfoTag::SetTimerType (const std::shared_ptr< CPVRTimerType > & type)
Sets the type of this timer.
Parameters
the new timer type.
References m_critSection, m_iClientIndex, m_iLifetime, m_iMaxRecordings, m_iPreventDupEpisodes, m_iPriority, m_iRecordingGroup, m_iWeekdays, m_timerType, PVR_TIMER_NO_CLIENT_INDEX, and PVR_WEEKDAY_NONE.
Referenced by CPVRTimerInfoTag(), CPVRTimerInfoTag(), and UpdateEntry().
StartAsLocalTime()
CDateTime CPVRTimerInfoTag::StartAsLocalTime () const
The start date and time for this timer, as local time.
Returns
The start date and time.
References ConvertUTCToLocalTime(), and m_StartTime.
Referenced by UpdateSummary().
StartAsUTC()
CDateTime CPVRTimerInfoTag::StartAsUTC () const
The start date and time for this timer, as UTC.
Returns
The start date and time.
References m_StartTime.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer(), GetEpgInfoTag(), and PVR::CPVRDatabase::Persist().
State()
PVR_TIMER_STATE PVR::CPVRTimerInfoTag::State () const inline
The state for this timer.
Returns
The state.
References m_state.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
Summary()
const std::string & CPVRTimerInfoTag::Summary () const
GUI support: Get the summary text for this timer, reflecting the timer schedule in a human readable form.
Returns
The summary string.
References m_strSummary.
TimerID()
unsigned int PVR::CPVRTimerInfoTag::TimerID () const inline
The local ID for this timer, as given by Kodi.
Returns
The ID or 0 if not yet set.
References m_iTimerId.
Title()
const std::string & CPVRTimerInfoTag::Title () const
The title for this timer.
Returns
The title.
References m_strTitle.
Referenced by PVR::CPVRDatabase::Persist().
UniqueBroadcastID()
unsigned int PVR::CPVRTimerInfoTag::UniqueBroadcastID () const inline
Get the UID of the epg event associated with this timer tag, if any.
Returns
The UID or EPG_TAG_INVALID_UID.
References m_iEpgUid.
Referenced by PVR::CPVRDatabase::Persist().
UpdateChannel()
void CPVRTimerInfoTag::UpdateChannel ()
Update the channel associated with this timer, based on current client ID and channel UID.
References CServiceBroker::GetPVRManager(), m_bIsRadio, m_channel, m_critSection, m_iClientChannelUid, and m_iClientId.
UpdateChildState()
bool CPVRTimerInfoTag::UpdateChildState (const std::shared_ptr< const CPVRTimerInfoTag > & childTimer, bool bAdd)
merge in the state of this child timer.
Parameters
childTimer The child timer
bAdd If true, add child's data to parent's state, otherwise subtract.
Returns
true if the child timer's state was merged successfully
References m_iClientIndex, m_iRadioChildTimersActive, m_iRadioChildTimersConflictNOK, m_iRadioChildTimersErrors, m_iRadioChildTimersRecording, m_iTVChildTimersActive, m_iTVChildTimersConflictNOK, m_iTVChildTimersErrors, m_iTVChildTimersRecording, PVR_TIMER_STATE_ABORTED, PVR_TIMER_STATE_CANCELLED, PVR_TIMER_STATE_COMPLETED, PVR_TIMER_STATE_CONFLICT_NOK, PVR_TIMER_STATE_CONFLICT_OK, PVR_TIMER_STATE_DISABLED, PVR_TIMER_STATE_ERROR, PVR_TIMER_STATE_NEW, PVR_TIMER_STATE_RECORDING, and PVR_TIMER_STATE_SCHEDULED.
UpdateEntry()
bool CPVRTimerInfoTag::UpdateEntry (const std::shared_ptr< const CPVRTimerInfoTag > & tag)
updates this timer excluding the state of any children.
Parameters
tag A timer containing the data that shall be merged into this timer's data.
Returns
true if the timer was updated successfully
References m_bEndAnyTime, m_bFullTextEpgSearch, m_bIsRadio, m_bProbedEpgTag, m_bStartAnyTime, m_channel, m_critSection, m_customProps, m_epgTag, m_FirstDay, m_iClientChannelUid, m_iClientId, m_iClientIndex, m_iEpgUid, m_iLifetime, m_iMarginEnd, m_iMarginStart, m_iMaxRecordings, m_iParentClientIndex, m_iPreventDupEpisodes, m_iPriority, m_iRadioChildTimersActive, m_iRadioChildTimersConflictNOK, m_iRadioChildTimersErrors, m_iRadioChildTimersRecording, m_iRecordingGroup, m_iTVChildTimersActive, m_iTVChildTimersConflictNOK, m_iTVChildTimersErrors, m_iTVChildTimersRecording, m_iWeekdays, m_StartTime, m_state, CDateTime::m_state, m_StopTime, m_strDirectory, m_strEpgSearchString, m_strSeriesLink, m_strSummary, m_strTitle, SetTimerType(), UpdateEpgInfoTag(), and UpdateSummary().
UpdateEpgInfoTag()
void CPVRTimerInfoTag::UpdateEpgInfoTag () private
References GetEpgInfoTag(), m_bProbedEpgTag, m_critSection, and m_epgTag.
Referenced by CPVRTimerInfoTag(), and UpdateEntry().
UpdateOnClient()
bool CPVRTimerInfoTag::UpdateOnClient ()
Update this timer on the backend, transferring all local data of this timer to the backend.
Returns
True on success, false otherwise.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_iClientId, and PVR_ERROR_NO_ERROR.
UpdateSummary()
void CPVRTimerInfoTag::UpdateSummary ()
GUI support: Update the summary text for this timer.
References EndAsLocalTime(), g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetAsLocalizedTime(), GetWeekdaysString(), m_bEndAnyTime, m_bStartAnyTime, m_critSection, m_iWeekdays, m_strSummary, m_timerType, PVR_WEEKDAY_NONE, and StartAsLocalTime().
Referenced by CPVRTimerInfoTag(), CPVRTimerInfoTag(), and UpdateEntry().
WeekDays()
unsigned int PVR::CPVRTimerInfoTag::WeekDays () const inline
For timer rules, the days of week this timer rule is scheduled for.
Returns
The days of week.
References m_iWeekdays.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer().
Friends And Related Symbol Documentation
CGUIDialogPVRTimerSettings
friend class CGUIDialogPVRTimerSettings friend
CPVRDatabase
friend class CPVRDatabase friend
Member Data Documentation
DEFAULT_PVRRECORD_INSTANTRECORDTIME
constexpr int PVR::CPVRTimerInfoTag::DEFAULT_PVRRECORD_INSTANTRECORDTIME = -1 static constexpr
Referenced by PVR::CPVRGUIActionsTimers::AddTimer(), and CreateFromDate().
m_bEndAnyTime
bool PVR::CPVRTimerInfoTag::m_bEndAnyTime = false private
Ignore end date and time clock. Record at 'Any Time'.
Referenced by IsEndAnyTime(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), UpdateEntry(), and UpdateSummary().
m_bFullTextEpgSearch
bool PVR::CPVRTimerInfoTag::m_bFullTextEpgSearch private
Initial value:
=
      false
indicates whether only epg episode title can be matched by the pvr backend or "more" (backend-dependent") data.
Referenced by IsFullTextEpgSearch(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), and UpdateEntry().
m_bIsRadio
bool PVR::CPVRTimerInfoTag::m_bIsRadio private
is radio channel if set
Referenced by GetEpgInfoTag(), IsRadio(), operator==(), Serialize(), UpdateChannel(), and UpdateEntry().
m_bProbedEpgTag
bool PVR::CPVRTimerInfoTag::m_bProbedEpgTag = false mutable private
Referenced by GetEpgInfoTag(), SetEpgInfoTag(), UpdateEntry(), and UpdateEpgInfoTag().
m_bStartAnyTime
bool PVR::CPVRTimerInfoTag::m_bStartAnyTime private
Initial value:
=
      false
Ignore start date and time clock. Record at 'Any Time'.
Referenced by IsStartAnyTime(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), UpdateEntry(), and UpdateSummary().
m_channel
std::shared_ptr<CPVRChannel> PVR::CPVRTimerInfoTag::m_channel mutable private
Referenced by Channel(), GetEpgInfoTag(), HasChannel(), operator==(), Serialize(), UpdateChannel(), and UpdateEntry().
m_critSection
CCriticalSection PVR::CPVRTimerInfoTag::m_critSection mutable private
Referenced by GetDeletedNotificationText(), GetEpgInfoTag(), GetNotificationText(), GetStatus(), GetTypeAsString(), GetWeekdaysString(), SetEpgInfoTag(), SetTimerType(), UpdateChannel(), UpdateEntry(), UpdateEpgInfoTag(), and UpdateSummary().
m_customProps
CustomPropsMap PVR::CPVRTimerInfoTag::m_customProps private
the map with custom properties supplied by the client.
Referenced by CPVRTimerInfoTag(), GetCustomProperties(), operator==(), and UpdateEntry().
m_epgTag
std::shared_ptr<CPVREpgInfoTag> PVR::CPVRTimerInfoTag::m_epgTag mutable private
epg info tag matching m_iEpgUid.
Referenced by GetEpgInfoTag(), Serialize(), SetEpgInfoTag(), UpdateEntry(), and UpdateEpgInfoTag().
m_FirstDay
CDateTime PVR::CPVRTimerInfoTag::m_FirstDay private
if it is a manual timer rule the first date it starts
Referenced by CPVRTimerInfoTag(), FirstDayAsLocalTime(), FirstDayAsUTC(), operator==(), Serialize(), SetFirstDayFromLocalTime(), SetFirstDayFromUTC(), and UpdateEntry().
m_iClientChannelUid
int PVR::CPVRTimerInfoTag::m_iClientChannelUid private
channel uid
Referenced by ClientChannelUID(), GetEpgInfoTag(), operator==(), PVR::CPVRDatabase::Persist(), UpdateChannel(), and UpdateEntry().
m_iClientId
int PVR::CPVRTimerInfoTag::m_iClientId private
ID of the backend.
Referenced by AddToClient(), ClientID(), CPVRTimerInfoTag(), CPVRTimerInfoTag(), DeleteFromClient(), GetEpgInfoTag(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), UpdateChannel(), UpdateEntry(), and UpdateOnClient().
m_iClientIndex
int PVR::CPVRTimerInfoTag::m_iClientIndex private
index number of the tag, given by the backend, PVR_TIMER_NO_CLIENT_INDEX for new
Referenced by ClientIndex(), CPVRTimerInfoTag(), PVR::CPVRDatabase::Delete(), operator==(), PVR::CPVRDatabase::Persist(), SetTimerType(), UpdateChildState(), and UpdateEntry().
m_iEpgUid
unsigned int PVR::CPVRTimerInfoTag::m_iEpgUid mutable private
id of epg event associated with this timer, EPG_TAG_INVALID_UID if none.
Referenced by CPVRTimerInfoTag(), GetEpgInfoTag(), operator==(), Serialize(), UniqueBroadcastID(), and UpdateEntry().
m_iLifetime
int PVR::CPVRTimerInfoTag::m_iLifetime private
lifetime of the timer in days
Referenced by Lifetime(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), SetTimerType(), and UpdateEntry().
m_iMarginEnd
unsigned int PVR::CPVRTimerInfoTag::m_iMarginEnd private
(optional) if set, the backend ends the recording iMarginEnd minutes after endTime.
Referenced by MarginEnd(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), and UpdateEntry().
m_iMarginStart
unsigned int PVR::CPVRTimerInfoTag::m_iMarginStart private
(optional) if set, the backend starts the recording iMarginStart minutes before startTime.
Referenced by MarginStart(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), and UpdateEntry().
m_iMaxRecordings
int PVR::CPVRTimerInfoTag::m_iMaxRecordings private
Initial value:
=
      0
(optional) backend setting for maximum number of recordings to keep
Referenced by MaxRecordings(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), SetTimerType(), and UpdateEntry().
m_iParentClientIndex
int PVR::CPVRTimerInfoTag::m_iParentClientIndex private
for timers scheduled by a timer rule, the index number of the parent, given by the backend, PVR_TIMER_NO_PARENT for no parent
Referenced by HasParent(), operator==(), ParentClientIndex(), PVR::CPVRDatabase::Persist(), and UpdateEntry().
m_iPreventDupEpisodes
unsigned int PVR::CPVRTimerInfoTag::m_iPreventDupEpisodes private
only record new episodes for epg-based timer rules
Referenced by operator==(), PVR::CPVRDatabase::Persist(), PreventDupEpisodesPolicy(), Serialize(), SetTimerType(), and UpdateEntry().
m_iPriority
int PVR::CPVRTimerInfoTag::m_iPriority private
priority of the timer
Referenced by operator==(), PVR::CPVRDatabase::Persist(), Priority(), Serialize(), SetTimerType(), and UpdateEntry().
m_iRadioChildTimersActive
unsigned int PVR::CPVRTimerInfoTag::m_iRadioChildTimersActive = 0 private
Referenced by GetStatus(), operator==(), ResetChildState(), UpdateChildState(), and UpdateEntry().
m_iRadioChildTimersConflictNOK
unsigned int PVR::CPVRTimerInfoTag::m_iRadioChildTimersConflictNOK = 0 private
Referenced by GetStatus(), operator==(), ResetChildState(), UpdateChildState(), and UpdateEntry().
m_iRadioChildTimersErrors
unsigned int PVR::CPVRTimerInfoTag::m_iRadioChildTimersErrors = 0 private
Referenced by GetStatus(), operator==(), ResetChildState(), UpdateChildState(), and UpdateEntry().
m_iRadioChildTimersRecording
unsigned int PVR::CPVRTimerInfoTag::m_iRadioChildTimersRecording = 0 private
Referenced by GetStatus(), operator==(), ResetChildState(), UpdateChildState(), and UpdateEntry().
m_iRecordingGroup
unsigned int PVR::CPVRTimerInfoTag::m_iRecordingGroup private
Initial value:
=
      0
(optional) if set, the addon/backend stores the recording to a group (sub-folder)
Referenced by operator==(), PVR::CPVRDatabase::Persist(), RecordingGroup(), Serialize(), SetTimerType(), and UpdateEntry().
m_iTimerId
unsigned int PVR::CPVRTimerInfoTag::m_iTimerId = 0 private
id that won't change as long as Kodi is running
Referenced by operator==(), Serialize(), SetTimerID(), and TimerID().
m_iTVChildTimersActive
unsigned int PVR::CPVRTimerInfoTag::m_iTVChildTimersActive = 0 private
Referenced by GetStatus(), operator==(), ResetChildState(), UpdateChildState(), and UpdateEntry().
m_iTVChildTimersConflictNOK
unsigned int PVR::CPVRTimerInfoTag::m_iTVChildTimersConflictNOK = 0 private
Referenced by GetStatus(), operator==(), ResetChildState(), UpdateChildState(), and UpdateEntry().
m_iTVChildTimersErrors
unsigned int PVR::CPVRTimerInfoTag::m_iTVChildTimersErrors = 0 private
Referenced by GetStatus(), operator==(), ResetChildState(), UpdateChildState(), and UpdateEntry().
m_iTVChildTimersRecording
unsigned int PVR::CPVRTimerInfoTag::m_iTVChildTimersRecording = 0 private
Referenced by GetStatus(), operator==(), ResetChildState(), UpdateChildState(), and UpdateEntry().
m_iWeekdays
unsigned int PVR::CPVRTimerInfoTag::m_iWeekdays private
bit based store of weekdays for timer rules
Referenced by CPVRTimerInfoTag(), GetWeekdaysString(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), SetTimerType(), UpdateEntry(), UpdateSummary(), and WeekDays().
m_StartTime
CDateTime PVR::CPVRTimerInfoTag::m_StartTime private
start time
Referenced by GetDuration(), operator==(), Serialize(), SetStartFromLocalTime(), SetStartFromUTC(), StartAsLocalTime(), StartAsUTC(), and UpdateEntry().
m_state
PVR_TIMER_STATE PVR::CPVRTimerInfoTag::m_state = PVR_TIMER_STATE_SCHEDULED private
the state of this timer
Referenced by GetDeletedNotificationText(), GetNotificationText(), GetStatus(), HasConflict(), IsActive(), IsBroken(), IsDisabled(), IsRecording(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), SetState(), State(), and UpdateEntry().
m_StopTime
CDateTime PVR::CPVRTimerInfoTag::m_StopTime private
stop time
Referenced by EndAsLocalTime(), EndAsUTC(), GetDuration(), operator==(), Serialize(), SetEndFromLocalTime(), SetEndFromUTC(), and UpdateEntry().
m_strDirectory
std::string PVR::CPVRTimerInfoTag::m_strDirectory private
directory where the recording must be stored
Referenced by Directory(), operator==(), Serialize(), and UpdateEntry().
m_strEpgSearchString
std::string PVR::CPVRTimerInfoTag::m_strEpgSearchString private
a epg data match string for epg-based timer rules. Format is backend-dependent, for example regexp
Referenced by EpgSearchString(), operator==(), PVR::CPVRDatabase::Persist(), Serialize(), and UpdateEntry().
m_strFileNameAndPath
std::string PVR::CPVRTimerInfoTag::m_strFileNameAndPath private
file name is only for reference
Referenced by GetStatus(), operator==(), and Path().
m_strSeriesLink
std::string PVR::CPVRTimerInfoTag::m_strSeriesLink private
series link
Referenced by operator==(), Serialize(), SeriesLink(), and UpdateEntry().
m_strSummary
std::string PVR::CPVRTimerInfoTag::m_strSummary private
summary string with the time to show inside a GUI list
Referenced by operator==(), Serialize(), Summary(), UpdateEntry(), and UpdateSummary().
m_strTitle
std::string PVR::CPVRTimerInfoTag::m_strTitle private
name of this timer
Referenced by GetDeletedNotificationText(), GetNotificationText(), operator==(), Serialize(), Title(), and UpdateEntry().
m_timerType
std::shared_ptr<CPVRTimerType> PVR::CPVRTimerInfoTag::m_timerType private
the type of this timer
Referenced by ChannelName(), CPVRTimerInfoTag(), CPVRTimerInfoTag(), GetTimerType(), GetTypeAsString(), GetWeekdaysString(), IsManual(), IsOwnedByClient(), IsReminder(), IsTimerRule(), operator==(), Serialize(), SetTimerType(), and UpdateSummary().
The documentation for this class was generated from the following files:
PVRTimerInfoTag.h
PVRTimerInfoTag.cpp