Kodi Documentation: XFILE::CVideoDatabaseFile Class Reference
XFILE::CVideoDatabaseFile Class Reference
#include <VideoDatabaseFile.h>
Public Member Functions
CVideoDatabaseFile (void)
~CVideoDatabaseFile (void) override
Public Member Functions inherited from XFILE::COverrideFile
COverrideFile (bool writable)
~COverrideFile () override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int Stat (struct __stat64 *buffer) override
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
bool Delete (const CURL &url) override
bool Rename (const CURL &url, const CURL &urlnew) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
void Close () override
int64_t GetPosition () override
int64_t GetLength () override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool SetHidden (const CURL &url, bool hidden)
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Static Public Member Functions
static CVideoInfoTag GetVideoTag (const CURL &url)
Protected Member Functions
std::string TranslatePath (const CURL &url) override
Static Protected Member Functions
static VideoDbContentType GetType (const CURL &url)
Additional Inherited Members
Protected Attributes inherited from XFILE::COverrideFile
CFile m_file
bool m_writable
Constructor & Destructor Documentation
CVideoDatabaseFile()
CVideoDatabaseFile::CVideoDatabaseFile (void)
~CVideoDatabaseFile()
CVideoDatabaseFile::~CVideoDatabaseFile (void) override default
Member Function Documentation
GetType()
VideoDbContentType CVideoDatabaseFile::GetType (const CURL & url) static protected
References EPISODES, CURL::Get(), URIUtils::GetDirectory(), MOVIES, MUSICVIDEOS, and UNKNOWN.
Referenced by GetVideoTag(), and TranslatePath().
GetVideoTag()
CVideoInfoTag CVideoDatabaseFile::GetVideoTag (const CURL & url) static
References CURL::Get(), CVideoDatabase::GetDetailsByTypeAndId(), URIUtils::GetFileName(), GetType(), CVideoDatabase::Open(), URIUtils::RemoveExtension(), and UNKNOWN.
Referenced by CGUIWindowVideoNav::OnMessage(), CXBMCApp::onNewIntent(), and KODI::PLAYLIST::CPlayListPlayer::Play().
TranslatePath()
std::string CVideoDatabaseFile::TranslatePath (const CURL & url) override protected virtual
Implements XFILE::COverrideFile.
References CURL::Get(), URIUtils::GetFileName(), CVideoDatabase::GetFilePathById(), GetType(), CVideoDatabase::Open(), URIUtils::RemoveExtension(), and UNKNOWN.
The documentation for this class was generated from the following files:
VideoDatabaseFile.h
VideoDatabaseFile.cpp