Kodi Documentation: IMAGE_FILES::CImageFileURL Class Reference
IMAGE_FILES::CImageFileURL Class Reference
A mostly-typed representation of a URL to any image, whether a simple path to an image file, embedded in another file, or generated in some way.
#include <ImageFileURL.h>
Public Member Functions
CImageFileURL (const std::string &imageFileURL)
Create an ImageFileURL from a string representation.
void AddOption (std::string key, std::string value)
std::string GetOption (const std::string &key) const
std::string ToString () const
Build a complete string representation of this ImageFileURL.
std::string ToCacheKey () const
Build a cache key for this ImageFileURL.
const std::string & GetTargetFile () const
bool IsSpecialImage () const
const std::string & GetSpecialType () const
Static Public Member Functions
static CImageFileURL FromFile (const std::string &filePath, std::string specialType="")
Create an ImageFileURL pointing to a specific file.
Public Attributes
bool flipped {false}
Private Member Functions
CImageFileURL ()
Private Attributes
std::string m_filePath
std::string m_specialType
std::map< std::string, std::string > m_options {}
Detailed Description
A mostly-typed representation of a URL to any image, whether a simple path to an image file, embedded in another file, or generated in some way.
A URL string is good to pass between most classes, store, and transmit, but use this if you need to create or modify a special image path, or are working on the details of such image files.
URL string format is image://[type@]<url_encoded_path>?options
Constructor & Destructor Documentation
CImageFileURL() [1/2]
IMAGE_FILES::CImageFileURL::CImageFileURL (const std::string & imageFileURL)
Create an ImageFileURL from a string representation.
References flipped, CURL::GetHostName(), URIUtils::IsProtocol(), m_filePath, m_options, and m_specialType.
CImageFileURL() [2/2]
IMAGE_FILES::CImageFileURL::CImageFileURL () private
Referenced by FromFile().
Member Function Documentation
AddOption()
void IMAGE_FILES::CImageFileURL::AddOption (std::string key, std::string value)
References m_options, and value.
FromFile()
CImageFileURL IMAGE_FILES::CImageFileURL::FromFile (const std::string & filePath, std::string specialType = "") static
Create an ImageFileURL pointing to a specific file.
Provide a 'specialType' parameter to specify a special image loader.
Parameters
specialType set a special image type - an implementation of ISpecialImageFileLoader
References CImageFileURL(), URIUtils::IsProtocol(), m_filePath, and m_specialType.
Referenced by CGUIDialogVideoInfo::ManageVideoItemArtwork(), CGUIDialogVideoBookmarks::OnRefreshList(), and IMAGE_FILES::URLFromFile().
GetOption()
std::string IMAGE_FILES::CImageFileURL::GetOption (const std::string & key) const
References m_options, and value.
Referenced by KODI::VIDEO::CVideoGeneratedImageFileLoader::Load().
GetSpecialType()
const std::string & IMAGE_FILES::CImageFileURL::GetSpecialType () const inline
References m_specialType.
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), IMAGE_FILES::CSpecialImageLoaderFactory::Load(), and KODI::VIDEO::CVideoEmbeddedImageFileLoader::Load().
GetTargetFile()
const std::string & IMAGE_FILES::CImageFileURL::GetTargetFile () const inline
References m_filePath.
Referenced by CTextureCacheJob::CacheTexture(), CFileUtils::CheckFileAccessAllowed(), PVR::CPVRCachedImages::Cleanup(), MUSIC_INFO::CMusicEmbeddedImageFileLoader::Load(), CPictureFolderImageFileLoader::Load(), PVR::CPVRChannelGroupImageFileLoader::Load(), KODI::VIDEO::CVideoEmbeddedImageFileLoader::Load(), KODI::VIDEO::CVideoGeneratedImageFileLoader::Load(), CTextureCacheJob::LoadImage(), and CTextureCacheJob::ResizeTexture().
IsSpecialImage()
bool IMAGE_FILES::CImageFileURL::IsSpecialImage () const inline
References m_specialType.
Referenced by IMAGE_FILES::CSpecialImageLoaderFactory::Load(), and CTextureCacheJob::LoadImage().
ToCacheKey()
std::string IMAGE_FILES::CImageFileURL::ToCacheKey () const
Build a cache key for this ImageFileURL.
Return base filePath if not special and multiple options are in a stable order, otherwise return a complete string representation.
References flipped, m_filePath, m_options, m_specialType, and ToString().
Referenced by IMAGE_FILES::ToCacheKey().
ToString()
std::string IMAGE_FILES::CImageFileURL::ToString () const
Build a complete string representation of this ImageFileURL.
References flipped, CURL::Get(), m_filePath, m_options, m_specialType, CURL::SetHostName(), CURL::SetOption(), CURL::SetProtocol(), and CURL::SetUserName().
Referenced by ToCacheKey(), and IMAGE_FILES::URLFromFile().
Member Data Documentation
flipped
bool IMAGE_FILES::CImageFileURL::flipped {false}
Referenced by CImageFileURL(), CTextureCacheJob::LoadImage(), ToCacheKey(), and ToString().
m_filePath
std::string IMAGE_FILES::CImageFileURL::m_filePath private
Referenced by CImageFileURL(), FromFile(), GetTargetFile(), ToCacheKey(), and ToString().
m_options
std::map<std::string, std::string> IMAGE_FILES::CImageFileURL::m_options {} private
Referenced by AddOption(), CImageFileURL(), GetOption(), ToCacheKey(), and ToString().
m_specialType
std::string IMAGE_FILES::CImageFileURL::m_specialType private
Referenced by CImageFileURL(), FromFile(), GetSpecialType(), IsSpecialImage(), ToCacheKey(), and ToString().
The documentation for this class was generated from the following files:
ImageFileURL.h
ImageFileURL.cpp