Kodi Documentation: anonymous_namespace{PVRGUIDirectory.cpp} Namespace Reference
anonymous_namespace{PVRGUIDirectory.cpp} Namespace Reference
Classes
class CByClientAndProviderFilter
Functions
bool GetRootDirectory (bool bRadio, CFileItemList &results)
std::string TrimSlashes (const std::string &strOrig)
bool IsDirectoryMember (const std::string &strDirectory, const std::string &strEntryDirectory, bool bGrouped)
template<typename T >
void GetGetRecordingsSubDirectories (const CPVRRecordingsPath &recParentPath, const std::vector< std::shared_ptr< CPVRRecording > > &recordings, const CByClientAndProviderFilter< T > &byClientAndProviderFilter, CFileItemList &results)
std::shared_ptr< CPVRChannelGroupMember > GetLastWatchedChannelGroupMember (const std::shared_ptr< CPVRChannel > &channel)
std::shared_ptr< CPVRChannelGroupMember > GetFirstMatchingGroupMember (const std::shared_ptr< CPVRChannel > &channel)
std::vector< std::shared_ptr< CPVRChannelGroupMember > > GetChannelGroupMembers (const CPVRChannelsPath &path)
bool GetTimersRootDirectory (const CPVRTimersPath &path, bool bHideDisabled, const std::vector< std::shared_ptr< CPVRTimerInfoTag > > &timers, CFileItemList &results)
bool GetTimersSubDirectory (const CPVRTimersPath &path, bool bHideDisabled, const std::vector< std::shared_ptr< CPVRTimerInfoTag > > &timers, CFileItemList &results)
Function Documentation
GetChannelGroupMembers()
std::vector< std::shared_ptr< CPVRChannelGroupMember > > anonymous_namespace{PVRGUIDirectory.cpp}::GetChannelGroupMembers (const CPVRChannelsPath & path) private
References PVR::CPVRChannelGroup::ALL, PVR::CPVRManager::ChannelGroups(), GetChannelGroupMembers(), GetFirstMatchingGroupMember(), PVR::CPVRChannelsPath::GetGroupClientID(), PVR::CPVRChannelsPath::GetGroupName(), GetLastWatchedChannelGroupMember(), CServiceBroker::GetPVRManager(), PVR::CPVRChannelsPath::IsHiddenChannelGroup(), PVR::CPVRChannelsPath::IsRadio(), LOGERROR, and PVR::CPVRChannelGroup::ONLY_VISIBLE.
Referenced by GetChannelGroupMembers().
GetFirstMatchingGroupMember()
std::shared_ptr< CPVRChannelGroupMember > anonymous_namespace{PVRGUIDirectory.cpp}::GetFirstMatchingGroupMember (const std::shared_ptr< CPVRChannel > & channel) private
References PVR::CPVRManager::ChannelGroups(), GetFirstMatchingGroupMember(), and CServiceBroker::GetPVRManager().
Referenced by GetChannelGroupMembers(), and GetFirstMatchingGroupMember().
GetGetRecordingsSubDirectories()
template<typename T > void anonymous_namespace{PVRGUIDirectory.cpp}::GetGetRecordingsSubDirectories (const CPVRRecordingsPath & recParentPath, const std::vector< std::shared_ptr< CPVRRecording > > & recordings, const CByClientAndProviderFilter< T > & byClientAndProviderFilter, CFileItemList & results)
References CFileItemList::Add(), PVR::CPVRRecordingsPath::AppendSegment(), CFileItemList::Contains(), anonymous_namespace{PVRGUIDirectory.cpp}::CByClientAndProviderFilter< T >::Filter(), CFileItemList::Get(), GetGetRecordingsSubDirectories(), CFileItemList::GetList(), PVR::CPVRRecordingsPath::GetUnescapedSubDirectoryPath(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, int64_t(), and PVR::CPVRRecordingsPath::IsRadio().
Referenced by GetGetRecordingsSubDirectories().
GetLastWatchedChannelGroupMember()
std::shared_ptr< CPVRChannelGroupMember > anonymous_namespace{PVRGUIDirectory.cpp}::GetLastWatchedChannelGroupMember (const std::shared_ptr< CPVRChannel > & channel) private
References PVR::CPVRManager::ChannelGroups(), GetLastWatchedChannelGroupMember(), CServiceBroker::GetPVRManager(), and PVR::PVR_GROUP_ID_UNNKOWN.
Referenced by GetChannelGroupMembers(), and GetLastWatchedChannelGroupMember().
GetRootDirectory()
bool anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory (bool bRadio, CFileItemList & results)
References CFileItemList::Add(), PVR::CPVRManager::Clients(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetPVRManager(), GetRootDirectory(), PVR::CPVRRecordingsPath::PATH_ACTIVE_RADIO_RECORDINGS, PVR::CPVRRecordingsPath::PATH_ACTIVE_TV_RECORDINGS, PVR::CPVRChannelsPath::PATH_RADIO_CHANNELS, PVR::CPVRProvidersPath::PATH_RADIO_PROVIDERS, PVR::CPVREpgSearchPath::PATH_RADIO_SEARCH, PVR::CPVRTimersPath::PATH_RADIO_TIMER_RULES, PVR::CPVRTimersPath::PATH_RADIO_TIMERS, PVR::CPVRChannelsPath::PATH_TV_CHANNELS, PVR::CPVRProvidersPath::PATH_TV_PROVIDERS, PVR::CPVREpgSearchPath::PATH_TV_SEARCH, PVR::CPVRTimersPath::PATH_TV_TIMER_RULES, PVR::CPVRTimersPath::PATH_TV_TIMERS, PVR::CPVRManager::Providers(), CWindowTranslator::TranslateWindow(), WINDOW_RADIO_CHANNELS, WINDOW_RADIO_GUIDE, WINDOW_RADIO_PROVIDERS, WINDOW_RADIO_RECORDINGS, WINDOW_RADIO_SEARCH, WINDOW_RADIO_TIMER_RULES, WINDOW_RADIO_TIMERS, WINDOW_TV_CHANNELS, WINDOW_TV_GUIDE, WINDOW_TV_PROVIDERS, WINDOW_TV_RECORDINGS, WINDOW_TV_SEARCH, WINDOW_TV_TIMER_RULES, and WINDOW_TV_TIMERS.
Referenced by GetRootDirectory().
GetTimersRootDirectory()
bool anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersRootDirectory (const CPVRTimersPath & path, bool bHideDisabled, const std::vector< std::shared_ptr< CPVRTimerInfoTag > > & timers, CFileItemList & results) private
References CFileItemList::Add(), PVR::CPVRTimersPath::GetPath(), GetTimersRootDirectory(), PVR::CPVRTimersPath::IsRadio(), PVR::CPVRTimersPath::IsRules(), and PVR_TIMER_ANY_CHANNEL.
Referenced by GetTimersRootDirectory().
GetTimersSubDirectory()
bool anonymous_namespace{PVRGUIDirectory.cpp}::GetTimersSubDirectory (const CPVRTimersPath & path, bool bHideDisabled, const std::vector< std::shared_ptr< CPVRTimerInfoTag > > & timers, CFileItemList & results) private
References CFileItemList::Add(), PVR::CPVRTimersPath::GetClientId(), PVR::CPVRTimersPath::GetParentId(), PVR::CPVRTimersPath::GetPath(), GetTimersSubDirectory(), PVR::CPVRTimersPath::IsRadio(), and PVR::PVR_CLIENT_INVALID_UID.
Referenced by GetTimersSubDirectory().
IsDirectoryMember()
bool anonymous_namespace{PVRGUIDirectory.cpp}::IsDirectoryMember (const std::string & strDirectory, const std::string & strEntryDirectory, bool bGrouped)
References IsDirectoryMember(), and TrimSlashes().
Referenced by IsDirectoryMember().
TrimSlashes()
std::string anonymous_namespace{PVRGUIDirectory.cpp}::TrimSlashes (const std::string & strOrig)
References URIUtils::RemoveSlashAtEnd(), and TrimSlashes().
Referenced by IsDirectoryMember(), and TrimSlashes().