Kodi Documentation: KODI::GAME::CDefaultButtonMap Class Reference
KODI::GAME::CDefaultButtonMap Class Reference
Games
A fallback buttonmap to be used with the default keyboard profile.
#include <DefaultButtonMap.h>
Public Member Functions
CDefaultButtonMap (PERIPHERALS::CPeripheral *device, std::string strControllerId)
~CDefaultButtonMap () override
std::string ControllerID () const override
The add-on ID of the game controller associated with this button map.
std::string Location () const override
The Location of the peripheral associated with this button map.
bool Load () override
Load the button map into memory.
void Reset () override
Reset the button map to its defaults, or clear button map if no defaults.
bool IsEmpty () const override
Check if the button map is empty.
std::string GetAppearance () const override
Get the ID of the controller profile that best represents the appearance of the peripheral.
bool SetAppearance (const std::string &controllerId) const override
Set the ID of the controller that best represents the appearance of the peripheral.
bool GetFeature (const JOYSTICK::CDriverPrimitive &primitive, JOYSTICK::FeatureName &feature) override
Get the feature associated with a driver primitive.
JOYSTICK::FEATURE_TYPE GetFeatureType (const JOYSTICK::FeatureName &feature) override
Get the type of the feature for the given name.
bool GetScalar (const JOYSTICK::FeatureName &feature, JOYSTICK::CDriverPrimitive &primitive) override
Get the driver primitive for a scalar feature.
void AddScalar (const JOYSTICK::FeatureName &feature, const JOYSTICK::CDriverPrimitive &primitive) override
Add or update a scalar feature.
bool GetAnalogStick (const JOYSTICK::FeatureName &feature, JOYSTICK::ANALOG_STICK_DIRECTION direction, JOYSTICK::CDriverPrimitive &primitive) override
Get an analog stick direction from the button map.
void AddAnalogStick (const JOYSTICK::FeatureName &feature, JOYSTICK::ANALOG_STICK_DIRECTION direction, const JOYSTICK::CDriverPrimitive &primitive) override
Add or update an analog stick direction.
bool GetRelativePointer (const JOYSTICK::FeatureName &feature, JOYSTICK::RELATIVE_POINTER_DIRECTION direction, JOYSTICK::CDriverPrimitive &primitive) override
Get a relative pointer direction from the button map.
void AddRelativePointer (const JOYSTICK::FeatureName &feature, JOYSTICK::RELATIVE_POINTER_DIRECTION direction, const JOYSTICK::CDriverPrimitive &primitive) override
Add or update a relative pointer direction.
bool GetAccelerometer (const JOYSTICK::FeatureName &feature, JOYSTICK::CDriverPrimitive &positiveX, JOYSTICK::CDriverPrimitive &positiveY, JOYSTICK::CDriverPrimitive &positiveZ) override
Get an accelerometer from the button map.
void AddAccelerometer (const JOYSTICK::FeatureName &feature, const JOYSTICK::CDriverPrimitive &positiveX, const JOYSTICK::CDriverPrimitive &positiveY, const JOYSTICK::CDriverPrimitive &positiveZ) override
Get or update an accelerometer.
bool GetWheel (const JOYSTICK::FeatureName &feature, JOYSTICK::WHEEL_DIRECTION direction, JOYSTICK::CDriverPrimitive &primitive) override
Get a wheel direction from the button map.
void AddWheel (const JOYSTICK::FeatureName &feature, JOYSTICK::WHEEL_DIRECTION direction, const JOYSTICK::CDriverPrimitive &primitive) override
Add or update a wheel direction.
bool GetThrottle (const JOYSTICK::FeatureName &feature, JOYSTICK::THROTTLE_DIRECTION direction, JOYSTICK::CDriverPrimitive &primitive) override
Get a throttle direction from the button map.
void AddThrottle (const JOYSTICK::FeatureName &feature, JOYSTICK::THROTTLE_DIRECTION direction, const JOYSTICK::CDriverPrimitive &primitive) override
Add or update a throttle direction.
bool GetKey (const JOYSTICK::FeatureName &feature, JOYSTICK::CDriverPrimitive &primitive) override
Get the driver primitive for a keyboard key.
void AddKey (const JOYSTICK::FeatureName &feature, const JOYSTICK::CDriverPrimitive &primitive) override
Add or update a key.
void SetIgnoredPrimitives (const std::vector< JOYSTICK::CDriverPrimitive > &primitives) override
Set a list of driver primitives to be ignored.
bool IsIgnored (const JOYSTICK::CDriverPrimitive &primitive) override
Check if a primitive is in the list of primitives to be ignored.
bool GetAxisProperties (unsigned int axisIndex, int &center, unsigned int &range) override
Get the properties of an axis.
void SaveButtonMap () override
Save the button map.
void RevertButtonMap () override
Revert changes to the button map since the last time it was loaded or committed to disk.
Public Member Functions inherited from KODI::JOYSTICK::IButtonMap
virtual ~IButtonMap ()=default
Private Attributes
PERIPHERALS::CPeripheral *const m_device
const std::string m_strControllerId
Detailed Description
A fallback buttonmap to be used with the default keyboard profile.
Constructor & Destructor Documentation
CDefaultButtonMap()
CDefaultButtonMap::CDefaultButtonMap (PERIPHERALS::CPeripheral * device, std::string strControllerId)
~CDefaultButtonMap()
CDefaultButtonMap::~CDefaultButtonMap () override default
Member Function Documentation
AddAccelerometer()
void KODI::GAME::CDefaultButtonMap::AddAccelerometer (const JOYSTICK::FeatureName & feature, const JOYSTICK::CDriverPrimitive & positiveX, const JOYSTICK::CDriverPrimitive & positiveY, const JOYSTICK::CDriverPrimitive & positiveZ) inline override virtual
Get or update an accelerometer.
Parameters
feature Must be an accelerometer or this will return false
positiveX The semiaxis corresponding to the positive X direction
positiveY The semiaxis corresponding to the positive Y direction
positiveZ The semiaxis corresponding to the positive Z direction
The driver primitives must be mapped to a semiaxis or this function will fail.
Returns
True if the accelerometer was updated, false if unchanged or failure occurred
Implements KODI::JOYSTICK::IButtonMap.
AddAnalogStick()
void KODI::GAME::CDefaultButtonMap::AddAnalogStick (const JOYSTICK::FeatureName & feature, JOYSTICK::ANALOG_STICK_DIRECTION direction, const JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Add or update an analog stick direction.
Parameters
feature Must be an analog stick or this will return false
direction The direction being mapped
primitive The driver primitive for the specified analog stick and direction
Returns
True if the analog stick was updated, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
AddKey()
void KODI::GAME::CDefaultButtonMap::AddKey (const JOYSTICK::FeatureName & feature, const JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Add or update a key.
Parameters
feature Must be a key
primitive The feature's driver primitive
Returns
True if the feature was updated, false if the feature is unchanged or failure occurs
Implements KODI::JOYSTICK::IButtonMap.
AddRelativePointer()
void KODI::GAME::CDefaultButtonMap::AddRelativePointer (const JOYSTICK::FeatureName & feature, JOYSTICK::RELATIVE_POINTER_DIRECTION direction, const JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Add or update a relative pointer direction.
Parameters
feature Must be a relative pointer or this will return false
direction The direction being mapped
primitive The driver primitive for the specified analog stick and direction
Returns
True if the analog stick was updated, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
AddScalar()
void KODI::GAME::CDefaultButtonMap::AddScalar (const JOYSTICK::FeatureName & feature, const JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Add or update a scalar feature.
Parameters
feature Must be a scalar feature
primitive The feature's driver primitive
Returns
True if the feature was updated, false if the feature is unchanged or failure occurs
Implements KODI::JOYSTICK::IButtonMap.
AddThrottle()
void KODI::GAME::CDefaultButtonMap::AddThrottle (const JOYSTICK::FeatureName & feature, JOYSTICK::THROTTLE_DIRECTION direction, const JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Add or update a throttle direction.
Parameters
feature Must be a throttle or this will return false
direction The direction being mapped
primitive The driver primitive for the specified analog stick and direction
Returns
True if the analog stick was updated, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
AddWheel()
void KODI::GAME::CDefaultButtonMap::AddWheel (const JOYSTICK::FeatureName & feature, JOYSTICK::WHEEL_DIRECTION direction, const JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Add or update a wheel direction.
Parameters
feature Must be a wheel or this will return false
direction The direction being mapped
primitive The driver primitive for the specified analog stick and direction
Returns
True if the analog stick was updated, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
ControllerID()
std::string KODI::GAME::CDefaultButtonMap::ControllerID () const inline override virtual
The add-on ID of the game controller associated with this button map.
The controller ID provided by the implementation serves as the context for the feature names below.
Returns
The ID of this button map's game controller add-on
Implements KODI::JOYSTICK::IButtonMap.
References m_strControllerId.
GetAccelerometer()
bool KODI::GAME::CDefaultButtonMap::GetAccelerometer (const JOYSTICK::FeatureName & feature, JOYSTICK::CDriverPrimitive & positiveX, JOYSTICK::CDriverPrimitive & positiveY, JOYSTICK::CDriverPrimitive & positiveZ) inline override virtual
Get an accelerometer from the button map.
Parameters
feature Must be an accelerometer or this will return false
positiveX The semiaxis mapped to the positive X direction (possibly unknown)
positiveY The semiaxis mapped to the positive Y direction (possibly unknown)
positiveZ The semiaxis mapped to the positive Z direction (possibly unknown)
Returns
True if the feature resolved to an accelerometer with at least 1 known axis
Implements KODI::JOYSTICK::IButtonMap.
GetAnalogStick()
bool KODI::GAME::CDefaultButtonMap::GetAnalogStick (const JOYSTICK::FeatureName & feature, JOYSTICK::ANALOG_STICK_DIRECTION direction, JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Get an analog stick direction from the button map.
Parameters
feature Must be an analog stick or this will return false
direction The direction whose primitive is to be retrieved
[out] primitive The primitive mapped to the specified direction
Returns
True if the feature and direction resolved to a driver primitive
Implements KODI::JOYSTICK::IButtonMap.
GetAppearance()
std::string CDefaultButtonMap::GetAppearance () const override virtual
Get the ID of the controller profile that best represents the appearance of the peripheral.
Returns
The controller ID, or empty if the appearance is unknown
Implements KODI::JOYSTICK::IButtonMap.
References PERIPHERALS::CPeripheral::ControllerProfile(), m_device, and m_strControllerId.
GetAxisProperties()
bool KODI::GAME::CDefaultButtonMap::GetAxisProperties (unsigned int axisIndex, int & center, unsigned int & range) inline override virtual
Get the properties of an axis.
Parameters
axisIndex The index of the axis to check
center[out] The center, if known
range[out] The range, if known
Returns
True if the properties are known, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
GetFeature()
bool CDefaultButtonMap::GetFeature (const JOYSTICK::CDriverPrimitive & primitive, JOYSTICK::FeatureName & feature) override virtual
Get the feature associated with a driver primitive.
Multiple primitives can be mapped to the same feature. For example, analog sticks use one primitive for each direction.
Parameters
primitive The driver primitive
feature The name of the resolved joystick feature, or invalid if false is returned
Returns
True if the driver primitive is associated with a feature, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
References KODI::JOYSTICK::KEY, KODI::JOYSTICK::CDriverPrimitive::Keycode(), KODI::JOYSTICK::MOUSE_BUTTON, KODI::JOYSTICK::CDriverPrimitive::MouseButton(), KODI::JOYSTICK::CDriverPrimitive::PointerDirection(), KODI::JOYSTICK::RELATIVE_POINTER, KODI::GAME::CDefaultKeyboardTranslator::TranslateKeycode(), KODI::GAME::CDefaultMouseTranslator::TranslateMouseButton(), KODI::GAME::CDefaultMouseTranslator::TranslateMousePointer(), and KODI::JOYSTICK::CDriverPrimitive::Type().
GetFeatureType()
JOYSTICK::FEATURE_TYPE KODI::GAME::CDefaultButtonMap::GetFeatureType (const JOYSTICK::FeatureName & feature) inline override virtual
Get the type of the feature for the given name.
Parameters
feature The feature to look up
Returns
The feature's type
Implements KODI::JOYSTICK::IButtonMap.
References KODI::JOYSTICK::UNKNOWN.
GetKey()
bool KODI::GAME::CDefaultButtonMap::GetKey (const JOYSTICK::FeatureName & feature, JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Get the driver primitive for a keyboard key.
Parameters
feature Must be a key
primitive The resolved driver primitive
Returns
True if the feature resolved to a driver primitive, false if the feature didn't resolve or isn't a scalar feature
Implements KODI::JOYSTICK::IButtonMap.
GetRelativePointer()
bool KODI::GAME::CDefaultButtonMap::GetRelativePointer (const JOYSTICK::FeatureName & feature, JOYSTICK::RELATIVE_POINTER_DIRECTION direction, JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Get a relative pointer direction from the button map.
Parameters
feature Must be a relative pointer stick or this will return false
direction The direction whose primitive is to be retrieved
[out] primitive The primitive mapped to the specified direction
Returns
True if the feature and direction resolved to a driver primitive
Implements KODI::JOYSTICK::IButtonMap.
GetScalar()
bool KODI::GAME::CDefaultButtonMap::GetScalar (const JOYSTICK::FeatureName & feature, JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Get the driver primitive for a scalar feature.
When a feature can be represented by a single driver primitive, it is called a scalar feature.
This includes buttons and triggers, because they can be mapped to a single button/hat/semiaxis
This does not include analog sticks, because they require two axes and four driver primitives (one for each semiaxis)
Parameters
feature Must be a scalar feature (a feature that only requires a single driver primitive)
primitive The resolved driver primitive
Returns
True if the feature resolved to a driver primitive, false if the feature didn't resolve or isn't a scalar feature
Implements KODI::JOYSTICK::IButtonMap.
GetThrottle()
bool KODI::GAME::CDefaultButtonMap::GetThrottle (const JOYSTICK::FeatureName & feature, JOYSTICK::THROTTLE_DIRECTION direction, JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Get a throttle direction from the button map.
Parameters
feature Must be a throttle or this will return false
direction The direction whose primitive is to be retrieved
[out] primitive The primitive mapped to the specified direction
Returns
True if the feature and direction resolved to a driver primitive
Implements KODI::JOYSTICK::IButtonMap.
GetWheel()
bool KODI::GAME::CDefaultButtonMap::GetWheel (const JOYSTICK::FeatureName & feature, JOYSTICK::WHEEL_DIRECTION direction, JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Get a wheel direction from the button map.
Parameters
feature Must be a wheel or this will return false
direction The direction whose primitive is to be retrieved
[out] primitive The primitive mapped to the specified direction
Returns
True if the feature and direction resolved to a driver primitive
Implements KODI::JOYSTICK::IButtonMap.
IsEmpty()
bool KODI::GAME::CDefaultButtonMap::IsEmpty () const inline override virtual
Check if the button map is empty.
Returns
True if the button map is empty, false if it has features
Implements KODI::JOYSTICK::IButtonMap.
IsIgnored()
bool KODI::GAME::CDefaultButtonMap::IsIgnored (const JOYSTICK::CDriverPrimitive & primitive) inline override virtual
Check if a primitive is in the list of primitives to be ignored.
Parameters
primitive The primitive to check
Returns
True if the primitive should be ignored in the mapping process
Implements KODI::JOYSTICK::IButtonMap.
Load()
bool CDefaultButtonMap::Load () override virtual
Load the button map into memory.
Returns
True if button map is ready to start translating buttons, false otherwise
Implements KODI::JOYSTICK::IButtonMap.
References DEFAULT_KEYBOARD_ID, DEFAULT_MOUSE_ID, PERIPHERALS::CPeripheral::Location(), CLog::Log(), LOGDEBUG, m_device, m_strControllerId, PERIPHERALS::PERIPHERAL_KEYBOARD, PERIPHERALS::PERIPHERAL_MOUSE, and PERIPHERALS::CPeripheral::Type().
Location()
std::string CDefaultButtonMap::Location () const override virtual
The Location of the peripheral associated with this button map.
Returns
The peripheral's location
Implements KODI::JOYSTICK::IButtonMap.
References PERIPHERALS::CPeripheral::Location(), and m_device.
Reset()
void KODI::GAME::CDefaultButtonMap::Reset () inline override virtual
Reset the button map to its defaults, or clear button map if no defaults.
Implements KODI::JOYSTICK::IButtonMap.
RevertButtonMap()
void KODI::GAME::CDefaultButtonMap::RevertButtonMap () inline override virtual
Revert changes to the button map since the last time it was loaded or committed to disk.
Implements KODI::JOYSTICK::IButtonMap.
SaveButtonMap()
void KODI::GAME::CDefaultButtonMap::SaveButtonMap () inline override virtual
Save the button map.
Implements KODI::JOYSTICK::IButtonMap.
SetAppearance()
bool KODI::GAME::CDefaultButtonMap::SetAppearance (const std::string & controllerId) const inline override virtual
Set the ID of the controller that best represents the appearance of the peripheral.
Parameters
controllerId The controller ID, or empty to unset the appearance
Returns
True if the appearance was set, false on error
Implements KODI::JOYSTICK::IButtonMap.
SetIgnoredPrimitives()
void KODI::GAME::CDefaultButtonMap::SetIgnoredPrimitives (const std::vector< JOYSTICK::CDriverPrimitive > & primitives) inline override virtual
Set a list of driver primitives to be ignored.
This is necessary to prevent features from interfering with the button mapping process. This includes accelerometers, as well as PS4 triggers which send both a button press and an analog value.
Parameters
primitives The driver primitives to be ignored
Implements KODI::JOYSTICK::IButtonMap.
Member Data Documentation
m_device
PERIPHERALS::CPeripheral* const KODI::GAME::CDefaultButtonMap::m_device private
Referenced by GetAppearance(), Load(), and Location().
m_strControllerId
const std::string KODI::GAME::CDefaultButtonMap::m_strControllerId private
Referenced by ControllerID(), GetAppearance(), and Load().
The documentation for this class was generated from the following files:
DefaultButtonMap.h
DefaultButtonMap.cpp