Kodi Documentation: CAudioDecoder Class Reference
CAudioDecoder Class Reference
#include <AudioDecoder.h>
Public Member Functions
CAudioDecoder ()
~CAudioDecoder ()
bool Create (const CFileItem &file, int64_t seekOffset)
void Destroy ()
int ReadSamples (int numsamples)
bool CanSeek ()
int64_t Seek (int64_t time)
int64_t TotalTime ()
void SetTotalTime (int64_t time)
void Start ()
int GetStatus ()
void SetStatus (int status)
AEAudioFormat GetFormat ()
unsigned int GetChannels ()
unsigned int GetDataSize (bool checkPktSize)
void * GetData (unsigned int samples)
uint8_t * GetRawData (int &size)
ICodec * GetCodec () const
float GetReplayGain (float &peakVal)
Private Attributes
CRingBuffer m_pcmBuffer
float m_outputBuffer [OUTPUT_SAMPLES]
uint8_t m_pcmInputBuffer [INPUT_SIZE]
float m_inputBuffer [INPUT_SAMPLES]
uint8_t * m_rawBuffer
int m_rawBufferSize
bool m_eof
int m_status
bool m_canPlay
ICodec * m_codec
CCriticalSection m_critSection
Constructor & Destructor Documentation
CAudioDecoder()
CAudioDecoder::CAudioDecoder ()
References INPUT_SAMPLES, INPUT_SIZE, m_canPlay, m_codec, m_eof, m_inputBuffer, m_outputBuffer, m_pcmInputBuffer, m_rawBuffer, m_rawBufferSize, m_status, OUTPUT_SAMPLES, and STATUS_NO_FILE.
~CAudioDecoder()
CAudioDecoder::~CAudioDecoder ()
References Destroy().
Member Function Documentation
CanSeek()
bool CAudioDecoder::CanSeek ()
References ICodec::CanSeek(), and m_codec.
Referenced by PAPlayer::UpdateGUIData().
Create()
bool CAudioDecoder::Create (const CFileItem & file, int64_t seekOffset)
References ReplayGain::ALBUM, CAEChannelInfo::Count(), CRingBuffer::Create(), CodecFactory::CreateCodecDemux(), Destroy(), ReplayGain::Get(), GetFormat(), MUSIC_INFO::CMusicInfoTag::GetReplayGain(), CServiceBroker::GetSettingsComponent(), ICodec::Init(), URIUtils::IsOnLAN(), CLog::Log(), LOGERROR, ICodec::m_bitsPerSample, AEAudioFormat::m_channelLayout, m_codec, m_critSection, m_eof, ICodec::m_format, m_pcmBuffer, m_rawBufferSize, AEAudioFormat::m_sampleRate, m_status, ICodec::m_tag, ICodec::Seek(), ReplayGain::Set(), MUSIC_INFO::CMusicInfoTag::SetReplayGain(), CSettings::SETTING_CACHE_HARDDISK, CSettings::SETTING_CACHEAUDIO_DVDROM, CSettings::SETTING_CACHEAUDIO_INTERNET, CSettings::SETTING_CACHEAUDIO_LAN, ICodec::SetTotalTime(), STATUS_QUEUING, ReplayGain::TRACK, and ReplayGain::Info::Valid().
Referenced by PAPlayer::QueueNextFileEx().
Destroy()
void CAudioDecoder::Destroy ()
References CRingBuffer::Destroy(), m_canPlay, m_codec, m_critSection, m_pcmBuffer, m_status, and STATUS_NO_FILE.
Referenced by PAPlayer::CloseAllStreams(), Create(), PAPlayer::ProcessStreams(), PAPlayer::QueueNextFileEx(), and ~CAudioDecoder().
GetChannels()
unsigned int CAudioDecoder::GetChannels ()
References CAEChannelInfo::Count(), GetFormat(), and AEAudioFormat::m_channelLayout.
GetCodec()
ICodec * CAudioDecoder::GetCodec () const inline
References m_codec.
Referenced by PAPlayer::QueueData(), and PAPlayer::UpdateGUIData().
GetData()
void * CAudioDecoder::GetData (unsigned int samples)
References CRingBuffer::getMaxReadSize(), CLog::Log(), LOGERROR, LOGWARNING, ICodec::m_bitsPerSample, m_codec, m_outputBuffer, m_pcmBuffer, m_status, CRingBuffer::ReadData(), STATUS_ENDED, and STATUS_ENDING.
Referenced by PAPlayer::QueueData().
GetDataSize()
unsigned int CAudioDecoder::GetDataSize (bool checkPktSize)
References AE_FMT_RAW, CRingBuffer::getMaxReadSize(), ICodec::m_bitsPerSample, m_codec, AEAudioFormat::m_dataFormat, ICodec::m_format, m_pcmBuffer, m_rawBufferSize, m_status, OUTPUT_SAMPLES, PACKET_SIZE, STATUS_ENDED, STATUS_ENDING, STATUS_NO_FILE, and STATUS_QUEUING.
Referenced by PAPlayer::QueueData(), and PAPlayer::QueueNextFileEx().
GetFormat()
AEAudioFormat CAudioDecoder::GetFormat ()
References m_codec, and ICodec::m_format.
Referenced by Create(), GetChannels(), PAPlayer::QueueNextFileEx(), and ReadSamples().
GetRawData()
uint8_t * CAudioDecoder::GetRawData (int & size)
References m_rawBuffer, m_rawBufferSize, m_status, STATUS_ENDED, and STATUS_ENDING.
Referenced by PAPlayer::QueueData().
GetReplayGain()
float CAudioDecoder::GetReplayGain (float & peakVal)
References ReplayGain::ALBUM, ReplayGain::Info::Gain(), ReplayGain::Get(), CServiceBroker::GetAppComponents(), MUSIC_INFO::CMusicInfoTag::GetReplayGain(), CApplicationVolumeHandling::GetReplayGainSettings(), ReplayGain::Info::HasGain(), ReplayGain::Info::HasPeak(), CLog::Log(), LOGDEBUG, m_codec, ICodec::m_tag, ReplayGain::NONE, ReplayGain::Info::Peak(), REPLAY_GAIN_DEFAULT_LEVEL, and ReplayGain::TRACK.
Referenced by PAPlayer::PrepareStream().
GetStatus()
int CAudioDecoder::GetStatus () inline
References m_status.
Referenced by PAPlayer::PrepareStream(), PAPlayer::ProcessStream(), and PAPlayer::QueueNextFileEx().
ReadSamples()
int CAudioDecoder::ReadSamples (int numsamples)
Todo:
trash this useless ringbuffer
References AE_FMT_RAW, CAEChannelInfo::Count(), GetFormat(), CRingBuffer::getMaxReadSize(), CRingBuffer::getMaxWriteSize(), CRingBuffer::getSize(), INPUT_SAMPLES, CLog::Log(), LOGERROR, LOGINFO, ICodec::m_bitsPerSample, m_canPlay, AEAudioFormat::m_channelLayout, m_codec, m_critSection, AEAudioFormat::m_dataFormat, m_eof, ICodec::m_format, m_pcmBuffer, m_pcmInputBuffer, m_rawBuffer, m_rawBufferSize, m_status, READ_EOF, READ_ERROR, READ_SUCCESS, ICodec::ReadPCM(), ICodec::ReadRaw(), RET_ERROR, RET_SLEEP, RET_SUCCESS, STATUS_ENDED, STATUS_ENDING, STATUS_NO_FILE, STATUS_PLAYING, STATUS_QUEUED, STATUS_QUEUING, and CRingBuffer::WriteData().
Referenced by PAPlayer::PrepareStream(), PAPlayer::ProcessStream(), and PAPlayer::QueueNextFileEx().
Seek()
int64_t CAudioDecoder::Seek (int64_t time)
References CRingBuffer::Clear(), m_codec, m_pcmBuffer, m_rawBufferSize, ICodec::m_TotalTime, and ICodec::Seek().
Referenced by PAPlayer::ProcessStream().
SetStatus()
void CAudioDecoder::SetStatus (int status) inline
References m_status.
SetTotalTime()
void CAudioDecoder::SetTotalTime (int64_t time)
References m_codec, and ICodec::m_TotalTime.
Referenced by PAPlayer::SetTotalTimeInternal().
Start()
void CAudioDecoder::Start () inline
References m_canPlay.
Referenced by PAPlayer::QueueNextFileEx().
TotalTime()
int64_t CAudioDecoder::TotalTime ()
References m_codec, and ICodec::m_TotalTime.
Referenced by PAPlayer::GetTotalTime64(), PAPlayer::ProcessStream(), PAPlayer::QueueNextFileEx(), PAPlayer::UpdateGUIData(), and PAPlayer::UpdateStreamInfoPlayNextAtFrame().
Member Data Documentation
m_canPlay
bool CAudioDecoder::m_canPlay private
Referenced by CAudioDecoder(), Destroy(), ReadSamples(), and Start().
m_codec
ICodec* CAudioDecoder::m_codec private
Referenced by CanSeek(), CAudioDecoder(), Create(), Destroy(), GetCodec(), GetData(), GetDataSize(), GetFormat(), GetReplayGain(), ReadSamples(), Seek(), SetTotalTime(), and TotalTime().
m_critSection
CCriticalSection CAudioDecoder::m_critSection private
Referenced by Create(), Destroy(), and ReadSamples().
m_eof
bool CAudioDecoder::m_eof private
Referenced by CAudioDecoder(), Create(), and ReadSamples().
m_inputBuffer
float CAudioDecoder::m_inputBuffer[INPUT_SAMPLES] private
Referenced by CAudioDecoder().
m_outputBuffer
float CAudioDecoder::m_outputBuffer[OUTPUT_SAMPLES] private
Referenced by CAudioDecoder(), and GetData().
m_pcmBuffer
CRingBuffer CAudioDecoder::m_pcmBuffer private
Referenced by Create(), Destroy(), GetData(), GetDataSize(), ReadSamples(), and Seek().
m_pcmInputBuffer
uint8_t CAudioDecoder::m_pcmInputBuffer[INPUT_SIZE] private
Referenced by CAudioDecoder(), and ReadSamples().
m_rawBuffer
uint8_t* CAudioDecoder::m_rawBuffer private
Referenced by CAudioDecoder(), GetRawData(), and ReadSamples().
m_rawBufferSize
int CAudioDecoder::m_rawBufferSize private
Referenced by CAudioDecoder(), Create(), GetDataSize(), GetRawData(), ReadSamples(), and Seek().
m_status
int CAudioDecoder::m_status private
Referenced by CAudioDecoder(), Create(), Destroy(), GetData(), GetDataSize(), GetRawData(), GetStatus(), ReadSamples(), and SetStatus().
The documentation for this class was generated from the following files:
cores/paplayer/AudioDecoder.h
cores/paplayer/AudioDecoder.cpp