Kodi Documentation: jni::CJNIXBMCNsdManagerResolveListener Class Reference
jni::CJNIXBMCNsdManagerResolveListener Class Reference abstract
#include <JNIXBMCNsdManagerResolveListener.h>
Public Member Functions
CJNIXBMCNsdManagerResolveListener ()
CJNIXBMCNsdManagerResolveListener (const CJNIXBMCNsdManagerResolveListener &other)
CJNIXBMCNsdManagerResolveListener (const jni::jhobject &object)
~CJNIXBMCNsdManagerResolveListener () override
void onResolveFailed (const CJNINsdServiceInfo &serviceInfo, int errorCode) override=0
void onServiceResolved (const CJNINsdServiceInfo &serviceInfo) override=0
Static Public Member Functions
static void RegisterNatives (JNIEnv *env)
Static Protected Member Functions
static void _onResolveFailed (JNIEnv *env, jobject thiz, jobject serviceInfo, jint errorCode)
static void _onServiceResolved (JNIEnv *env, jobject thiz, jobject serviceInfo)
Constructor & Destructor Documentation
CJNIXBMCNsdManagerResolveListener() [1/3]
CJNIXBMCNsdManagerResolveListener::CJNIXBMCNsdManagerResolveListener ()
References s_className.
CJNIXBMCNsdManagerResolveListener() [2/3]
CJNIXBMCNsdManagerResolveListener::CJNIXBMCNsdManagerResolveListener (const CJNIXBMCNsdManagerResolveListener & other)
CJNIXBMCNsdManagerResolveListener() [3/3]
jni::CJNIXBMCNsdManagerResolveListener::CJNIXBMCNsdManagerResolveListener (const jni::jhobject & object) inline explicit
~CJNIXBMCNsdManagerResolveListener()
CJNIXBMCNsdManagerResolveListener::~CJNIXBMCNsdManagerResolveListener () override
Member Function Documentation
_onResolveFailed()
void CJNIXBMCNsdManagerResolveListener::_onResolveFailed (JNIEnv * env, jobject thiz, jobject serviceInfo, jint errorCode) static protected
References onResolveFailed().
Referenced by RegisterNatives().
_onServiceResolved()
void CJNIXBMCNsdManagerResolveListener::_onServiceResolved (JNIEnv * env, jobject thiz, jobject serviceInfo) static protected
References onServiceResolved().
Referenced by RegisterNatives().
onResolveFailed()
void jni::CJNIXBMCNsdManagerResolveListener::onResolveFailed (const CJNINsdServiceInfo & serviceInfo, int errorCode) override pure virtual
Referenced by _onResolveFailed().
onServiceResolved()
void jni::CJNIXBMCNsdManagerResolveListener::onServiceResolved (const CJNINsdServiceInfo & serviceInfo) override pure virtual
Referenced by _onServiceResolved().
RegisterNatives()
void CJNIXBMCNsdManagerResolveListener::RegisterNatives (JNIEnv * env) static
References _onResolveFailed(), _onServiceResolved(), and s_className.
Referenced by JNI_OnLoad().
The documentation for this class was generated from the following files:
JNIXBMCNsdManagerResolveListener.h
JNIXBMCNsdManagerResolveListener.cpp