Kodi Documentation: GUIControlBuiltins.cpp File Reference
GUIControlBuiltins.cpp File Reference
#include "GUIControlBuiltins.h"
#include "ServiceBroker.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "input/WindowTranslator.h"
#include "utils/StringUtils.h"
Functions
static int ControlMove (const std::vector< std::string > &params)
Send a move event to a GUI control.
static int SendClick (const std::vector< std::string > &params)
Send a click event to a GUI control.
static int SendMessage (const std::vector< std::string > &params)
Send a message to a control.
static int SetFocus (const std::vector< std::string > &params)
Give a control focus.
static int SetVisible (const std::vector< std::string > &params)
Set a control to visible.
static int SetHidden (const std::vector< std::string > &params)
Set a control to hidden.
template<int Message>
static int ShiftPage (const std::vector< std::string > &params)
Shift page in a control.
Function Documentation
ControlMove()
static int ControlMove (const std::vector< std::string > & params) static
Send a move event to a GUI control.
Parameters
params The parameters.
params[0] = ID of control. params[1] = Offset of move.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_MOVE_OFFSET, and CGUIWindowManager::SendMessage().
Referenced by CGUIControlBuiltins::GetOperations().
SendClick()
static int SendClick (const std::vector< std::string > & params) static
Send a click event to a GUI control.
Parameters
params The parameters.
params[0] = ID of control. params[1] = ID for window with control (optional).
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_CLICKED, CGUIWindowManager::SendMessage(), and CWindowTranslator::TranslateWindow().
Referenced by CGUIControlBuiltins::GetOperations().
SendMessage()
static int SendMessage (const std::vector< std::string > & params) static
Send a message to a control.
Parameters
params The parameters.
params[0] = ID of control. params[1] = Action name. \params[2] = ID of window with control (optional).
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_CLICKED, GUI_MSG_MOVE_OFFSET, GUI_MSG_PAGE_DOWN, GUI_MSG_PAGE_UP, CGUIWindowManager::SendMessage(), and CWindowTranslator::TranslateWindow().
Referenced by CInertialScrollingHandler::CheckForInertialScrolling(), CWin32DPMSSupport::DisablePowerSaving(), CWin32DPMSSupport::EnablePowerSaving(), CGUIControlBuiltins::GetOperations(), CVideoPlayer::OpenAudioStream(), CVideoPlayer::OpenVideoStream(), CGenericTouchActionHandler::QuerySupportedGestures(), and CGUIDialogNetworkSetup::UpdateButtons().
SetFocus()
static int SetFocus (const std::vector< std::string > & params) static
Give a control focus.
Parameters
params The parameters.
params[0] = ID of control. params[1] = ID of subitem of control (optional). params[2] = "absolute" to focus the absolute position instead of the relative one (optional).
References KODI::UTILS::StringUtils::EqualsNoCase(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_SETFOCUS, and CGUIWindowManager::SendMessage().
Referenced by CGUIControlBuiltins::GetOperations(), and CWinSystemWin32::Show().
SetHidden()
static int SetHidden (const std::vector< std::string > & params) static
Set a control to hidden.
Parameters
params The parameters.
params[0] = ID of control.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_HIDDEN, and CGUIWindowManager::SendMessage().
Referenced by CGUIControlBuiltins::GetOperations().
SetVisible()
static int SetVisible (const std::vector< std::string > & params) static
Set a control to visible.
Parameters
params The parameters.
params[0] = ID of control.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_VISIBLE, and CGUIWindowManager::SendMessage().
Referenced by CGUIControlBuiltins::GetOperations().
ShiftPage()
template<int Message> static int ShiftPage (const std::vector< std::string > & params) static
Shift page in a control.
Parameters
params The parameters.
params[0] = ID of control
Set Message template parameter to GUI_MSG_PAGE_DOWN/GUI_MSG_PAGE_UP.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and CGUIWindowManager::SendMessage().