Kodi Documentation: VDPAU::CMixer Class Reference
VDPAU::CMixer Class Reference
#include <VDPAU.h>
Public Member Functions
CMixer (CEvent *inMsgEvent)
~CMixer () override
void Start ()
void Dispose ()
bool IsActive ()
Public Attributes
CMixerControlProtocol m_controlPort
CMixerDataProtocol m_dataPort
Protected Member Functions
void OnStartup () override
void OnExit () override
void Process () override
void StateMachine (int signal, Actor::Protocol *port, Actor::Message *msg)
void Init ()
void Uninit ()
void Flush ()
void CreateVdpauMixer ()
void ProcessPicture ()
void InitCycle ()
void FiniCycle ()
void CheckFeatures ()
void SetPostProcFeatures (bool postProcEnabled)
void PostProcOff ()
void InitCSCMatrix (int Width)
bool GenerateStudioCSCMatrix (VdpColorStandard colorStandard, VdpCSCMatrix &studioCSCMatrix)
void SetColor ()
void SetNoiseReduction ()
void SetSharpness ()
void SetDeintSkipChroma ()
void SetDeinterlacing ()
void SetHWUpscaling ()
void DisableHQScaling ()
std::string GetDeintStrFromInterlaceMethod (EINTERLACEMETHOD method)
bool CheckStatus (VdpStatus vdp_st, int line)
Protected Attributes
CEvent m_outMsgEvent
CEvent * m_inMsgEvent
int m_state
bool m_bStateMachineSelfTrigger
int m_extTimeout
bool m_vdpError
CVdpauConfig m_config
VdpVideoMixer m_videoMixer
VdpProcamp m_Procamp
VdpCSCMatrix m_CSCMatrix
bool m_PostProc
float m_Brightness
float m_Contrast
float m_NoiseReduction
float m_Sharpness
int m_Deint
int m_Upscale
bool m_SeenInterlaceFlag
unsigned int m_ColorMatrix: 4
VdpVideoMixerPictureStructure m_mixerfield
int m_mixerstep
int m_mixersteps
CVdpauProcessedPicture m_processPicture
std::queue< VdpOutputSurface > m_outputSurfaces
std::queue< CVdpauDecodedPicture > m_decodedPics
std::deque< CVdpauDecodedPicture > m_mixerInput
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Detailed Description
Embeds the vdpau video mixer Embedded by COutput class, gets decoded frames from COutput, processes them in mixer ands sends processed frames back to COutput
Constructor & Destructor Documentation
CMixer()
CMixer::CMixer (CEvent * inMsgEvent) explicit
References m_inMsgEvent.
~CMixer()
CMixer::~CMixer () override
References Dispose().
Member Function Documentation
CheckFeatures()
void CMixer::CheckFeatures () protected
References CProcessInfo::GetVideoSettings(), m_Brightness, CVideoSettings::m_Brightness, m_ColorMatrix, m_config, m_Contrast, CVideoSettings::m_Contrast, m_Deint, CVideoSettings::m_InterlaceMethod, m_mixerInput, m_NoiseReduction, CVideoSettings::m_NoiseReduction, m_Sharpness, CVideoSettings::m_Sharpness, m_Upscale, VDPAU::CVdpauConfig::processInfo, SetColor(), SetDeinterlacing(), SetHWUpscaling(), SetNoiseReduction(), SetSharpness(), and VDPAU::CVdpauConfig::upscale.
Referenced by InitCycle().
CheckStatus()
bool CMixer::CheckStatus (VdpStatus vdp_st, int line) protected
References VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetProcs(), CLog::Log(), LOGERROR, m_config, m_vdpError, and VDPAU::VDPAU_procs::vdp_get_error_string.
Referenced by CreateVdpauMixer(), DisableHQScaling(), PostProcOff(), ProcessPicture(), SetColor(), SetDeinterlacing(), SetDeintSkipChroma(), SetHWUpscaling(), SetNoiseReduction(), and SetSharpness().
CreateVdpauMixer()
void CMixer::CreateVdpauMixer () protected
References ARSIZE, CheckStatus(), VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetDevice(), VDPAU::CVDPAUContext::GetFeatureCount(), VDPAU::CVDPAUContext::GetFeatures(), VDPAU::CVDPAUContext::GetProcs(), InitCSCMatrix(), CLog::Log(), LOGINFO, m_config, m_videoMixer, VDPAU::CVdpauConfig::surfaceHeight, VDPAU::CVdpauConfig::surfaceWidth, VDPAU::VDPAU_procs::vdp_video_mixer_create, VDPAU::CVdpauConfig::vdpChromaType, and VDPAU::CVdpauConfig::vidWidth.
Referenced by Init().
DisableHQScaling()
void CMixer::DisableHQScaling () protected
References ARSIZE, CheckStatus(), VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetProcs(), m_config, m_videoMixer, VDPAU::CDecoder::Supports(), VDPAU::VDPAU_procs::vdp_video_mixer_set_feature_enables, and VDPAU::CVdpauConfig::vdpau.
Referenced by PostProcOff(), and SetHWUpscaling().
Dispose()
void CMixer::Dispose ()
References CThread::m_bStop, m_controlPort, m_dataPort, m_outMsgEvent, Actor::Protocol::Purge(), CEvent::Set(), and CThread::StopThread().
Referenced by VDPAU::COutput::PreCleanup(), VDPAU::COutput::Uninit(), and ~CMixer().
FiniCycle()
void CMixer::FiniCycle () protected
References VDPAU::CVideoSurfaces::ClearRender(), VDPAU::CVdpauProcessedPicture::isYuv, m_config, m_mixerInput, m_processPicture, VDPAU::CVdpauDecodedPicture::videoSurface, and VDPAU::CVdpauConfig::videoSurfaces.
Referenced by StateMachine().
Flush()
void CMixer::Flush () protected
References VDPAU::CMixerDataProtocol::BUFFER, VDPAU::CVideoSurfaces::ClearRender(), Actor::Message::data, VDPAU::CMixerDataProtocol::FRAME, Actor::CPayloadWrap< Payload >::GetPlayload(), m_config, m_dataPort, m_decodedPics, m_mixerInput, m_outputSurfaces, Actor::Message::payloadObj, Actor::Protocol::ReceiveOutMessage(), Actor::Message::Release(), Actor::Message::signal, VDPAU::CVdpauDecodedPicture::videoSurface, and VDPAU::CVdpauConfig::videoSurfaces.
Referenced by StateMachine(), and Uninit().
GenerateStudioCSCMatrix()
bool CMixer::GenerateStudioCSCMatrix (VdpColorStandard colorStandard, VdpCSCMatrix & studioCSCMatrix) protected
References B, C, studioCSCKCoeffs601, studioCSCKCoeffs709, and Y.
Referenced by SetColor().
GetDeintStrFromInterlaceMethod()
std::string CMixer::GetDeintStrFromInterlaceMethod (EINTERLACEMETHOD method) protected
References VS_INTERLACEMETHOD_NONE, VS_INTERLACEMETHOD_RENDER_BOB, VS_INTERLACEMETHOD_VDPAU_BOB, VS_INTERLACEMETHOD_VDPAU_TEMPORAL, VS_INTERLACEMETHOD_VDPAU_TEMPORAL_HALF, VS_INTERLACEMETHOD_VDPAU_TEMPORAL_SPATIAL, and VS_INTERLACEMETHOD_VDPAU_TEMPORAL_SPATIAL_HALF.
Referenced by SetDeinterlacing().
Init()
void CMixer::Init () protected
References CreateVdpauMixer(), g_interlace_mapping, CServiceBroker::GetSettingsComponent(), m_Brightness, m_ColorMatrix, m_config, m_Contrast, m_Deint, m_NoiseReduction, m_PostProc, m_SeenInterlaceFlag, m_Sharpness, m_Upscale, m_vdpError, SInterlaceMapping::method, VDPAU::CVdpauConfig::processInfo, CProcessInfo::SetDeinterlacingMethodDefault(), CSettings::SETTING_VIDEOPLAYER_USEVDPAUMIXER, VDPAU::CDecoder::Supports(), CProcessInfo::UpdateDeinterlacingMethods(), VDPAU::CVdpauConfig::upscale, VDPAU::CVdpauConfig::useInteropYuv, VDPAU::CVdpauConfig::vdpau, VS_INTERLACEMETHOD_NONE, VS_INTERLACEMETHOD_RENDER_BOB, VS_INTERLACEMETHOD_VDPAU_BOB, VS_INTERLACEMETHOD_VDPAU_INVERSE_TELECINE, and VS_INTERLACEMETHOD_VDPAU_TEMPORAL.
Referenced by StateMachine().
InitCSCMatrix()
void CMixer::InitCSCMatrix (int Width) protected
References m_Procamp.
Referenced by CreateVdpauMixer().
InitCycle()
void CMixer::InitCycle () protected
References CheckFeatures(), VDPAU::CVdpauProcessedPicture::crop, DVD_CODEC_CTRL_NO_POSTPROC, DVD_CODEC_CTRL_SKIPDEINT, VDPAU::CVdpauProcessedPicture::DVDPic, DVP_FLAG_INTERLACED, DVP_FLAG_REPEAT_TOP_FIELD, DVP_FLAG_TOP_FIELD_FIRST, VDPAU::CVdpauBufferStats::GetParams(), CProcessInfo::GetVideoSettings(), CServiceBroker::GetWinSystem(), VDPAU::CVdpauProcessedPicture::isYuv, m_config, CVideoSettings::m_InterlaceMethod, m_mixerfield, m_mixerInput, m_mixerstep, m_mixersteps, m_outputSurfaces, m_processPicture, m_SeenInterlaceFlag, NUM_CROP_PIX, VDPAU::CVdpauConfig::outHeight, VDPAU::CVdpauProcessedPicture::outputSurface, VDPAU::CVdpauConfig::outWidth, VDPAU::CVdpauConfig::processInfo, VDPAU::CVdpauBufferStats::SetCanSkipDeint(), VideoPicture::SetParams(), SetPostProcFeatures(), VDPAU::CVdpauConfig::stats, CProcessInfo::Supports(), VDPAU::CVdpauConfig::useInteropYuv, VDPAU::CVdpauProcessedPicture::videoSurface, VDPAU::CVdpauConfig::vidHeight, VDPAU::CVdpauConfig::vidWidth, VS_INTERLACEMETHOD_NONE, VS_INTERLACEMETHOD_RENDER_BOB, VS_INTERLACEMETHOD_VDPAU_BOB, VS_INTERLACEMETHOD_VDPAU_TEMPORAL, VS_INTERLACEMETHOD_VDPAU_TEMPORAL_HALF, VS_INTERLACEMETHOD_VDPAU_TEMPORAL_SPATIAL, and VS_INTERLACEMETHOD_VDPAU_TEMPORAL_SPATIAL_HALF.
Referenced by StateMachine().
IsActive()
bool CMixer::IsActive ()
References CThread::IsRunning().
Referenced by VDPAU::COutput::Flush().
OnExit()
void CMixer::OnExit () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
OnStartup()
void CMixer::OnStartup () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
PostProcOff()
void CMixer::PostProcOff () protected
References ARSIZE, CheckStatus(), VDPAU::CVdpauConfig::context, DisableHQScaling(), VDPAU::CVDPAUContext::GetProcs(), m_config, m_videoMixer, VDPAU::CDecoder::Supports(), VDPAU::VDPAU_procs::vdp_video_mixer_set_feature_enables, and VDPAU::CVdpauConfig::vdpau.
Referenced by SetPostProcFeatures().
Process()
void CMixer::Process (void) override protected virtual
Reimplemented from CThread.
References Actor::Protocol::GetMessage(), m_bStateMachineSelfTrigger, CThread::m_bStop, m_controlPort, m_dataPort, m_extTimeout, m_outMsgEvent, m_state, M_TOP_UNCONFIGURED, Actor::Protocol::ReceiveOutMessage(), Actor::Message::Release(), Actor::Message::signal, StateMachine(), VDPAU::CMixerControlProtocol::TIMEOUT, Uninit(), and CEvent::Wait().
ProcessPicture()
void CMixer::ProcessPicture () protected
References CheckStatus(), VDPAU::CVdpauConfig::context, VideoPicture::dts, DVD_NOPTS_VALUE, VDPAU::CVdpauProcessedPicture::DVDPic, VDPAU::CVDPAUContext::GetProcs(), VideoPicture::iRepeatPicture, VDPAU::CVdpauProcessedPicture::isYuv, m_config, m_mixerfield, m_mixerInput, m_mixerstep, m_processPicture, m_videoMixer, VDPAU::CVdpauConfig::outHeight, VDPAU::CVdpauProcessedPicture::outputSurface, VDPAU::CVdpauConfig::outWidth, VideoPicture::pts, VDPAU::VDPAU_procs::vdp_video_mixer_render, VDPAU::CVdpauConfig::vidHeight, and VDPAU::CVdpauConfig::vidWidth.
Referenced by StateMachine().
SetColor()
void CMixer::SetColor () protected
References ARSIZE, CheckStatus(), VDPAU::CVdpauConfig::context, GenerateStudioCSCMatrix(), VDPAU::CVDPAUContext::GetProcs(), CServiceBroker::GetSettingsComponent(), CProcessInfo::GetVideoSettings(), m_Brightness, CVideoSettings::m_Brightness, m_config, m_Contrast, CVideoSettings::m_Contrast, m_CSCMatrix, m_mixerInput, m_Procamp, m_videoMixer, VDPAU::CVdpauConfig::processInfo, CSettings::SETTING_VIDEOSCREEN_LIMITEDRANGE, VDPAU::CVdpauConfig::surfaceWidth, VDPAU::VDPAU_procs::vdp_generate_csc_matrix, and VDPAU::VDPAU_procs::vdp_video_mixer_set_attribute_values.
Referenced by CheckFeatures().
SetDeinterlacing()
void CMixer::SetDeinterlacing () protected
References ARSIZE, CheckStatus(), VDPAU::CVdpauConfig::context, GetDeintStrFromInterlaceMethod(), VDPAU::CVDPAUContext::GetProcs(), CServiceBroker::GetSettingsComponent(), CProcessInfo::GetVideoSettings(), m_config, m_Deint, CVideoSettings::m_InterlaceMethod, m_videoMixer, VDPAU::CVdpauConfig::processInfo, SetDeintSkipChroma(), CSettings::SETTING_VIDEOPLAYER_USEVDPAUMIXER, CProcessInfo::SetVideoDeintMethod(), CProcessInfo::Supports(), VDPAU::CVdpauConfig::useInteropYuv, VDPAU::VDPAU_procs::vdp_video_mixer_set_feature_enables, VS_INTERLACEMETHOD_NONE, VS_INTERLACEMETHOD_VDPAU_TEMPORAL, VS_INTERLACEMETHOD_VDPAU_TEMPORAL_HALF, VS_INTERLACEMETHOD_VDPAU_TEMPORAL_SPATIAL, and VS_INTERLACEMETHOD_VDPAU_TEMPORAL_SPATIAL_HALF.
Referenced by CheckFeatures(), and SetPostProcFeatures().
SetDeintSkipChroma()
void CMixer::SetDeintSkipChroma () protected
References ARSIZE, CheckStatus(), VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetProcs(), CServiceBroker::GetSettingsComponent(), m_config, m_videoMixer, VDPAU::CVdpauConfig::outHeight, values, and VDPAU::VDPAU_procs::vdp_video_mixer_set_attribute_values.
Referenced by SetDeinterlacing().
SetHWUpscaling()
void CMixer::SetHWUpscaling () protected
References ARSIZE, CheckStatus(), VDPAU::CVdpauConfig::context, DisableHQScaling(), VDPAU::CVDPAUContext::GetProcs(), m_config, m_videoMixer, VDPAU::CDecoder::Supports(), VDPAU::CVdpauConfig::upscale, VDPAU::VDPAU_procs::vdp_video_mixer_set_feature_enables, and VDPAU::CVdpauConfig::vdpau.
Referenced by CheckFeatures(), and SetPostProcFeatures().
SetNoiseReduction()
void CMixer::SetNoiseReduction () protected
References ARSIZE, CheckStatus(), VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetProcs(), CProcessInfo::GetVideoSettings(), CLog::Log(), LOGINFO, m_config, CVideoSettings::m_NoiseReduction, m_videoMixer, VDPAU::CVdpauConfig::processInfo, VDPAU::CDecoder::Supports(), VDPAU::VDPAU_procs::vdp_video_mixer_set_attribute_values, VDPAU::VDPAU_procs::vdp_video_mixer_set_feature_enables, and VDPAU::CVdpauConfig::vdpau.
Referenced by CheckFeatures(), and SetPostProcFeatures().
SetPostProcFeatures()
void CMixer::SetPostProcFeatures (bool postProcEnabled) protected
References m_PostProc, PostProcOff(), SetDeinterlacing(), SetHWUpscaling(), SetNoiseReduction(), and SetSharpness().
Referenced by InitCycle().
SetSharpness()
void CMixer::SetSharpness () protected
References ARSIZE, CheckStatus(), VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetProcs(), CProcessInfo::GetVideoSettings(), CLog::Log(), LOGINFO, m_config, CVideoSettings::m_Sharpness, m_videoMixer, VDPAU::CVdpauConfig::processInfo, VDPAU::CDecoder::Supports(), VDPAU::VDPAU_procs::vdp_video_mixer_set_attribute_values, VDPAU::VDPAU_procs::vdp_video_mixer_set_feature_enables, and VDPAU::CVdpauConfig::vdpau.
Referenced by CheckFeatures(), and SetPostProcFeatures().
Start()
void CMixer::Start ()
References CThread::Create().
Referenced by VDPAU::COutput::Init().
StateMachine()
void CMixer::StateMachine (int signal, Actor::Protocol * port, Actor::Message * msg) protected
References VDPAU::CMixerControlProtocol::ACC, VDPAU::CMixerDataProtocol::BUFFER, Actor::Message::data, data(), VDPAU::CVdpauBufferStats::DecDecoded(), VDPAU::CVdpauDecodedPicture::DVDPic, VDPAU::CMixerControlProtocol::ERROR, FiniCycle(), VDPAU::CMixerControlProtocol::FLUSH, Flush(), VDPAU::CMixerDataProtocol::FRAME, Actor::CPayloadWrap< Payload >::GetPlayload(), VDPAU::CVdpauBufferStats::IncProcessed(), VDPAU::CMixerControlProtocol::INIT, Init(), InitCycle(), VDPAU::CVdpauBufferStats::IsDraining(), VDPAU::CVdpauProcessedPicture::isYuv, CLog::Log(), LOGERROR, LOGWARNING, m_bStateMachineSelfTrigger, m_config, m_controlPort, m_dataPort, m_decodedPics, m_extTimeout, m_mixerInput, m_mixerstep, m_mixersteps, m_outputSurfaces, m_processPicture, m_state, M_TOP, M_TOP_CONFIGURED, M_TOP_CONFIGURED_STEP1, M_TOP_CONFIGURED_STEP2, M_TOP_CONFIGURED_WAIT1, M_TOP_CONFIGURED_WAIT2, M_TOP_ERROR, M_TOP_UNCONFIGURED, m_vdpError, MIXER_parentStates, VDPAU::CVdpauProcessedPicture::outputSurface, Actor::Message::payloadObj, VDPAU::CMixerDataProtocol::PICTURE, Actor::Protocol::portName, ProcessPicture(), Actor::Message::Reply(), Actor::Protocol::SendInMessage(), VideoPicture::SetParams(), VDPAU::CVdpauConfig::stats, VDPAU::CMixerControlProtocol::TIMEOUT, and VDPAU::CVdpauDecodedPicture::videoSurface.
Referenced by Process().
Uninit()
void CMixer::Uninit () protected
References VDPAU::CVdpauConfig::context, Flush(), VDPAU::CVDPAUContext::GetProcs(), m_config, m_outputSurfaces, m_videoMixer, and VDPAU::VDPAU_procs::vdp_video_mixer_destroy.
Referenced by Process().
Member Data Documentation
m_Brightness
float VDPAU::CMixer::m_Brightness protected
Referenced by CheckFeatures(), Init(), and SetColor().
m_bStateMachineSelfTrigger
bool VDPAU::CMixer::m_bStateMachineSelfTrigger protected
Referenced by Process(), and StateMachine().
m_ColorMatrix
unsigned int VDPAU::CMixer::m_ColorMatrix protected
Referenced by CheckFeatures(), and Init().
m_config
CVdpauConfig VDPAU::CMixer::m_config protected
Referenced by CheckFeatures(), CheckStatus(), CreateVdpauMixer(), DisableHQScaling(), FiniCycle(), Flush(), Init(), InitCycle(), PostProcOff(), ProcessPicture(), SetColor(), SetDeinterlacing(), SetDeintSkipChroma(), SetHWUpscaling(), SetNoiseReduction(), SetSharpness(), StateMachine(), and Uninit().
m_Contrast
float VDPAU::CMixer::m_Contrast protected
Referenced by CheckFeatures(), Init(), and SetColor().
m_controlPort
CMixerControlProtocol VDPAU::CMixer::m_controlPort
Referenced by Dispose(), VDPAU::COutput::Flush(), Process(), StateMachine(), and VDPAU::COutput::StateMachine().
m_CSCMatrix
VdpCSCMatrix VDPAU::CMixer::m_CSCMatrix protected
Referenced by SetColor().
m_dataPort
CMixerDataProtocol VDPAU::CMixer::m_dataPort
Referenced by Dispose(), VDPAU::COutput::EnsureBufferPool(), Flush(), VDPAU::COutput::Flush(), VDPAU::COutput::InitMixer(), Process(), VDPAU::COutput::Process(), VDPAU::COutput::ProcessReturnPicture(), StateMachine(), and VDPAU::COutput::StateMachine().
m_decodedPics
std::queue<CVdpauDecodedPicture> VDPAU::CMixer::m_decodedPics protected
Referenced by Flush(), and StateMachine().
m_Deint
int VDPAU::CMixer::m_Deint protected
Referenced by CheckFeatures(), Init(), and SetDeinterlacing().
m_extTimeout
int VDPAU::CMixer::m_extTimeout protected
Referenced by Process(), and StateMachine().
m_inMsgEvent
CEvent* VDPAU::CMixer::m_inMsgEvent protected
Referenced by CMixer().
m_mixerfield
VdpVideoMixerPictureStructure VDPAU::CMixer::m_mixerfield protected
Referenced by InitCycle(), and ProcessPicture().
m_mixerInput
std::deque<CVdpauDecodedPicture> VDPAU::CMixer::m_mixerInput protected
Referenced by CheckFeatures(), FiniCycle(), Flush(), InitCycle(), ProcessPicture(), SetColor(), and StateMachine().
m_mixerstep
int VDPAU::CMixer::m_mixerstep protected
Referenced by InitCycle(), ProcessPicture(), and StateMachine().
m_mixersteps
int VDPAU::CMixer::m_mixersteps protected
Referenced by InitCycle(), and StateMachine().
m_NoiseReduction
float VDPAU::CMixer::m_NoiseReduction protected
Referenced by CheckFeatures(), and Init().
m_outMsgEvent
CEvent VDPAU::CMixer::m_outMsgEvent protected
Referenced by Dispose(), and Process().
m_outputSurfaces
std::queue<VdpOutputSurface> VDPAU::CMixer::m_outputSurfaces protected
Referenced by Flush(), InitCycle(), StateMachine(), and Uninit().
m_PostProc
bool VDPAU::CMixer::m_PostProc protected
Referenced by Init(), and SetPostProcFeatures().
m_Procamp
VdpProcamp VDPAU::CMixer::m_Procamp protected
Referenced by InitCSCMatrix(), and SetColor().
m_processPicture
CVdpauProcessedPicture VDPAU::CMixer::m_processPicture protected
Referenced by FiniCycle(), InitCycle(), ProcessPicture(), and StateMachine().
m_SeenInterlaceFlag
bool VDPAU::CMixer::m_SeenInterlaceFlag protected
Referenced by Init(), and InitCycle().
m_Sharpness
float VDPAU::CMixer::m_Sharpness protected
Referenced by CheckFeatures(), and Init().
m_state
int VDPAU::CMixer::m_state protected
Referenced by Process(), and StateMachine().
m_Upscale
int VDPAU::CMixer::m_Upscale protected
Referenced by CheckFeatures(), and Init().
m_vdpError
bool VDPAU::CMixer::m_vdpError protected
Referenced by CheckStatus(), Init(), and StateMachine().
m_videoMixer
VdpVideoMixer VDPAU::CMixer::m_videoMixer protected
Referenced by CreateVdpauMixer(), DisableHQScaling(), PostProcOff(), ProcessPicture(), SetColor(), SetDeinterlacing(), SetDeintSkipChroma(), SetHWUpscaling(), SetNoiseReduction(), SetSharpness(), and Uninit().
The documentation for this class was generated from the following files:
VDPAU.h
VDPAU.cpp