Kodi Documentation: DRM::CMediaDrmCryptoSession Class Reference
DRM::CMediaDrmCryptoSession Class Reference
#include <MediaDrmCryptoSession.h>
Public Member Functions
CMediaDrmCryptoSession (const std::string &UUID, const std::string &cipherAlgo, const std::string &macAlgo)
~CMediaDrmCryptoSession () override
XbmcCommons::Buffer GetKeyRequest (const XbmcCommons::Buffer &init, const std::string &mimeType, bool offlineKey, const std::map< std::string, std::string > &parameters) override
std::string GetPropertyString (const std::string &name) override
std::string ProvideKeyResponse (const XbmcCommons::Buffer &response) override
void RemoveKeys () override
void RestoreKeys (const std::string &keySetId) override
void SetPropertyString (const std::string &name, const std::string &value) override
XbmcCommons::Buffer Decrypt (const XbmcCommons::Buffer &cipherKeyId, const XbmcCommons::Buffer &input, const XbmcCommons::Buffer &iv) override
XbmcCommons::Buffer Encrypt (const XbmcCommons::Buffer &cipherKeyId, const XbmcCommons::Buffer &input, const XbmcCommons::Buffer &iv) override
XbmcCommons::Buffer Sign (const XbmcCommons::Buffer &macKeyId, const XbmcCommons::Buffer &message) override
bool Verify (const XbmcCommons::Buffer &macKeyId, const XbmcCommons::Buffer &message, const XbmcCommons::Buffer &signature) override
Public Member Functions inherited from DRM::CCryptoSession
virtual ~CCryptoSession ()=default
Static Public Member Functions
static void Register ()
Static Public Member Functions inherited from DRM::CCryptoSession
static CCryptoSession * GetCryptoSession (const std::string &UUID, const std::string &cipherAlgo, const std::string &macAlgo)
Private Member Functions
bool OpenSession ()
void CloseSession ()
bool ProvisionRequest ()
Static Private Member Functions
static CCryptoSession * Create (const std::string &UUID, const std::string &cipherAlgo, const std::string &hmacAlgo)
Private Attributes
CJNIMediaDrm * m_mediaDrm = nullptr
CJNIMediaDrmCryptoSession * m_cryptoSession = nullptr
std::string m_cipherAlgo
std::string m_macAlgo
std::string m_keySetId
bool m_hasKeys = false
CharVecBuffer * m_sessionId = nullptr
Additional Inherited Members
Static Protected Member Functions inherited from DRM::CCryptoSession
static void RegisterInterface (GET_CRYPTO_SESSION_INTERFACE_FN fn)
Constructor & Destructor Documentation
CMediaDrmCryptoSession()
CMediaDrmCryptoSession::CMediaDrmCryptoSession (const std::string & UUID, const std::string & cipherAlgo, const std::string & macAlgo)
References int64_t(), CLog::Log(), LOGERROR, m_mediaDrm, and OpenSession().
~CMediaDrmCryptoSession()
CMediaDrmCryptoSession::~CMediaDrmCryptoSession () override
References CloseSession(), and m_mediaDrm.
Member Function Documentation
CloseSession()
void CMediaDrmCryptoSession::CloseSession () private
References XbmcCommons::Buffer::clear(), m_cryptoSession, m_hasKeys, m_keySetId, m_mediaDrm, and m_sessionId.
Referenced by RemoveKeys(), and ~CMediaDrmCryptoSession().
Create()
CCryptoSession * CMediaDrmCryptoSession::Create (const std::string & UUID, const std::string & cipherAlgo, const std::string & hmacAlgo) static private
Referenced by Register().
Decrypt()
Buffer CMediaDrmCryptoSession::Decrypt (const XbmcCommons::Buffer & cipherKeyId, const XbmcCommons::Buffer & input, const XbmcCommons::Buffer & iv) override virtual
Implements DRM::CCryptoSession.
References CLog::Log(), LOGDEBUG, LOGERROR, and m_cryptoSession.
Encrypt()
Buffer CMediaDrmCryptoSession::Encrypt (const XbmcCommons::Buffer & cipherKeyId, const XbmcCommons::Buffer & input, const XbmcCommons::Buffer & iv) override virtual
Implements DRM::CCryptoSession.
References CLog::Log(), LOGDEBUG, LOGERROR, and m_cryptoSession.
GetKeyRequest()
Buffer CMediaDrmCryptoSession::GetKeyRequest (const XbmcCommons::Buffer & init, const std::string & mimeType, bool offlineKey, const std::map< std::string, std::string > & parameters) override virtual
Implements DRM::CCryptoSession.
References data(), CLog::Log(), LOGDEBUG, LOGERROR, m_mediaDrm, and m_sessionId.
GetPropertyString()
std::string CMediaDrmCryptoSession::GetPropertyString (const std::string & name) override virtual
Implements DRM::CCryptoSession.
References m_mediaDrm, and name.
OpenSession()
bool CMediaDrmCryptoSession::OpenSession () private
References CLog::Log(), LOGDEBUG, LOGERROR, m_cipherAlgo, m_cryptoSession, m_macAlgo, m_mediaDrm, m_sessionId, and ProvisionRequest().
Referenced by CMediaDrmCryptoSession(), and RemoveKeys().
ProvideKeyResponse()
std::string CMediaDrmCryptoSession::ProvideKeyResponse (const XbmcCommons::Buffer & response) override virtual
Implements DRM::CCryptoSession.
References CLog::Log(), LOGDEBUG, LOGERROR, m_hasKeys, m_mediaDrm, and m_sessionId.
ProvisionRequest()
bool CMediaDrmCryptoSession::ProvisionRequest () private
References XFILE::CURL_OPTION_PROTOCOL, Base64::Encode(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, and m_mediaDrm.
Referenced by OpenSession().
Register()
void CMediaDrmCryptoSession::Register () static
References Create(), and DRM::CCryptoSession::RegisterInterface().
Referenced by CWinSystemAndroid::InitWindowSystem().
RemoveKeys()
void CMediaDrmCryptoSession::RemoveKeys () override virtual
Implements DRM::CCryptoSession.
References CloseSession(), CLog::Log(), LOGDEBUG, m_hasKeys, m_mediaDrm, m_sessionId, and OpenSession().
RestoreKeys()
void CMediaDrmCryptoSession::RestoreKeys (const std::string & keySetId) override virtual
Implements DRM::CCryptoSession.
References CLog::Log(), LOGDEBUG, LOGERROR, m_hasKeys, m_keySetId, m_mediaDrm, and m_sessionId.
SetPropertyString()
void CMediaDrmCryptoSession::SetPropertyString (const std::string & name, const std::string & value) override virtual
Implements DRM::CCryptoSession.
References m_mediaDrm, name, and value.
Sign()
Buffer CMediaDrmCryptoSession::Sign (const XbmcCommons::Buffer & macKeyId, const XbmcCommons::Buffer & message) override virtual
Implements DRM::CCryptoSession.
References CLog::Log(), LOGDEBUG, LOGERROR, and m_cryptoSession.
Verify()
bool CMediaDrmCryptoSession::Verify (const XbmcCommons::Buffer & macKeyId, const XbmcCommons::Buffer & message, const XbmcCommons::Buffer & signature) override virtual
Implements DRM::CCryptoSession.
References CLog::Log(), LOGDEBUG, LOGERROR, and m_cryptoSession.
Member Data Documentation
m_cipherAlgo
std::string DRM::CMediaDrmCryptoSession::m_cipherAlgo private
Referenced by OpenSession().
m_cryptoSession
CJNIMediaDrmCryptoSession* DRM::CMediaDrmCryptoSession::m_cryptoSession = nullptr private
Referenced by CloseSession(), Decrypt(), Encrypt(), OpenSession(), Sign(), and Verify().
m_hasKeys
bool DRM::CMediaDrmCryptoSession::m_hasKeys = false private
Referenced by CloseSession(), ProvideKeyResponse(), RemoveKeys(), and RestoreKeys().
m_keySetId
std::string DRM::CMediaDrmCryptoSession::m_keySetId private
Referenced by CloseSession(), and RestoreKeys().
m_macAlgo
std::string DRM::CMediaDrmCryptoSession::m_macAlgo private
Referenced by OpenSession().
m_mediaDrm
CJNIMediaDrm* DRM::CMediaDrmCryptoSession::m_mediaDrm = nullptr private
Referenced by CloseSession(), CMediaDrmCryptoSession(), GetKeyRequest(), GetPropertyString(), OpenSession(), ProvideKeyResponse(), ProvisionRequest(), RemoveKeys(), RestoreKeys(), SetPropertyString(), and ~CMediaDrmCryptoSession().
m_sessionId
CharVecBuffer* DRM::CMediaDrmCryptoSession::m_sessionId = nullptr private
Referenced by CloseSession(), GetKeyRequest(), OpenSession(), ProvideKeyResponse(), RemoveKeys(), and RestoreKeys().
The documentation for this class was generated from the following files:
MediaDrmCryptoSession.h
MediaDrmCryptoSession.cpp