Kodi Documentation: CONTEXTMENU::CVideoInfo Class Reference
CONTEXTMENU::CVideoInfo Class Reference
#include <ContextMenus.h>
Public Member Functions
CVideoInfo (MediaType mediaType)
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Private Attributes
const MediaType m_mediaType
Constructor & Destructor Documentation
CVideoInfo()
CONTEXTMENU::CVideoInfo::CVideoInfo (MediaType mediaType) explicit
Member Function Documentation
Execute()
bool CONTEXTMENU::CVideoInfo::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References CGUIDialogVideoInfo::ShowFor().
IsVisible()
bool CONTEXTMENU::CVideoInfo::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CFileItem::IsPVRRecording(), m_mediaType, and CVideoInfoTag::m_type.
Member Data Documentation
m_mediaType
const MediaType CONTEXTMENU::CVideoInfo::m_mediaType private
Referenced by IsVisible().
The documentation for this class was generated from the following files:
video/ContextMenus.h
video/ContextMenus.cpp