Kodi Documentation: XHandlePublic.h File Reference
XHandlePublic.h File Reference
Macros
#define DUPLICATE_CLOSE_SOURCE 0x00000001
#define DUPLICATE_SAME_ACCESS 0x00000002
Typedefs
typedef CXHandle * HANDLE
typedef HANDLE * LPHANDLE
Functions
bool CloseHandle (HANDLE hObject)
Macro Definition Documentation
DUPLICATE_CLOSE_SOURCE
#define DUPLICATE_CLOSE_SOURCE 0x00000001
DUPLICATE_SAME_ACCESS
#define DUPLICATE_SAME_ACCESS 0x00000002
Typedef Documentation
HANDLE
typedef CXHandle* HANDLE
LPHANDLE
typedef HANDLE* LPHANDLE
Function Documentation
CloseHandle()
bool CloseHandle (HANDLE hObject)
References INVALID_HANDLE_VALUE, CXHandle::m_internalLock, and CXHandle::m_nRefCount.
Referenced by XFILE::CWin32File::Close(), XFILE::CCircularCache::Close(), CAESinkWASAPI::Deinitialize(), CWin32StorageProvider::Eject(), CWin32StorageProvider::GetDrivesDevInstByDiskNumber(), CWIN32Util::GetDriveStatus(), CAESinkWASAPI::Initialize(), CWHelper::OnExit(), CWin32PowerStateWorker::PowerManagement(), XFILE::CWin32File::Stat(), CWIN32Util::ToggleTray(), WinMain(), win32_exception::write_minidump(), win32_exception::write_stacktrace(), DXVA::CVideoBufferShared::~CVideoBufferShared(), CWHelper::~CWHelper(), XFILE::CWin32File::~CWin32File(), and CAESinkXAudio::VoiceCallback::~VoiceCallback().