Kodi Documentation: CTeletextDecoder Class Reference
CTeletextDecoder Class Reference
#include <Teletext.h>
Public Member Functions
CTeletextDecoder ()
virtual ~CTeletextDecoder (void)
bool NeedRendering ()
void RenderingDone ()
KODI::UTILS::COLOR::Color * GetTextureBuffer ()
int GetHeight ()
int GetWidth ()
bool Changed ()
Checks if the data in the decoder has changed.
bool InitDecoder ()
void EndDecoder ()
void RenderPage ()
bool HandleAction (const CAction &action)
Private Member Functions
void PageInput (int Number)
void GetNextPageOne (bool up)
void GetNextSubPage (int offset)
bool IsSubtitlePage (int pageNumber) const
void SwitchZoomMode ()
void SwitchTranspMode ()
void SwitchHintMode ()
void ColorKey (int target)
void StartPageCatching ()
void StopPageCatching ()
void CatchNextPage (int firstlineinc, int inc)
void RenderCatchedPage ()
void DoFlashing (int startrow)
void DoRenderPage (int startrow, int national_subset_bak)
void Decode_BTT ()
void Decode_ADIP ()
int TopText_GetNext (int startpage, int up, int findgroup)
void Showlink (int column, int linkpage)
void CreateLine25 ()
void RenderCharFB (int Char, TextPageAttr_t *Attribute)
void RenderCharBB (int Char, TextPageAttr_t *Attribute)
void CopyBB2FB ()
void SetFontWidth (int newWidth)
int GetCurFontWidth ()
void SetPosX (int column)
void ClearBB (KODI::UTILS::COLOR::Color Color)
void ClearFB (KODI::UTILS::COLOR::Color Color)
void FillBorder (KODI::UTILS::COLOR::Color Color)
void FillRect (KODI::UTILS::COLOR::Color *buffer, int xres, int x, int y, int w, int h, KODI::UTILS::COLOR::Color Color)
void DrawVLine (KODI::UTILS::COLOR::Color *lfb, int xres, int x, int y, int l, KODI::UTILS::COLOR::Color color)
void DrawHLine (KODI::UTILS::COLOR::Color *lfb, int xres, int x, int y, int l, KODI::UTILS::COLOR::Color color)
void FillRectMosaicSeparated (KODI::UTILS::COLOR::Color *lfb, int xres, int x, int y, int w, int h, KODI::UTILS::COLOR::Color fgcolor, KODI::UTILS::COLOR::Color bgcolor, int set)
void FillTrapez (KODI::UTILS::COLOR::Color *lfb, int xres, int x0, int y0, int l0, int xoffset1, int h, int l1, KODI::UTILS::COLOR::Color color)
void FlipHorz (KODI::UTILS::COLOR::Color *lfb, int xres, int x, int y, int w, int h)
void FlipVert (KODI::UTILS::COLOR::Color *lfb, int xres, int x, int y, int w, int h)
int ShapeCoord (int param, int curfontwidth, int curfontheight)
void DrawShape (KODI::UTILS::COLOR::Color *lfb, int xres, int x, int y, int shapenumber, int curfontwidth, int fontheight, int curfontheight, KODI::UTILS::COLOR::Color fgcolor, KODI::UTILS::COLOR::Color bgcolor, bool clear)
void RenderDRCS (int xres, unsigned char *s, KODI::UTILS::COLOR::Color *d, unsigned char *ax, KODI::UTILS::COLOR::Color fgcolor, KODI::UTILS::COLOR::Color bgcolor)
void RenderCharIntern (TextRenderInfo_t *RenderInfo, int Char, TextPageAttr_t *Attribute, int zoom, int yoffset)
int RenderChar (KODI::UTILS::COLOR::Color *buffer, int xres, int Char, int *pPosX, int PosY, TextPageAttr_t *Attribute, bool zoom, int curfontwidth, int curfontwidth2, int fontheight, bool transpmode, unsigned char *axdrcs, int Ascender)
TextPageinfo_t * DecodePage (bool showl25, unsigned char *PageChar, TextPageAttr_t *PageAtrb, bool HintMode, bool showflof)
void Eval_l25 (unsigned char *page_char, TextPageAttr_t *PageAtrb, bool HintMode)
void Eval_Object (int iONr, TextCachedPage_t *pstCachedPage, unsigned char *pAPx, unsigned char *pAPy, unsigned char *pAPx0, unsigned char *pAPy0, tObjType ObjType, unsigned char *pagedata, unsigned char *page_char, TextPageAttr_t *PageAtrb)
void Eval_NumberedObject (int p, int s, int packet, int triplet, int high, unsigned char *pAPx, unsigned char *pAPy, unsigned char *pAPx0, unsigned char *pAPy0, unsigned char *page_char, TextPageAttr_t *PageAtrb)
int Eval_Triplet (int iOData, TextCachedPage_t *pstCachedPage, unsigned char *pAPx, unsigned char *pAPy, unsigned char *pAPx0, unsigned char *pAPy0, unsigned char *drcssubp, unsigned char *gdrcssubp, signed char *endcol, TextPageAttr_t *attrPassive, unsigned char *pagedata, unsigned char *page_char, TextPageAttr_t *PageAtrb)
int iTripletNumber2Data (int iONr, TextCachedPage_t *pstCachedPage, unsigned char *pagedata)
int SetNational (unsigned char sec)
int NextHex (int i)
void SetColors (const unsigned short *pcolormap, int offset, int number)
KODI::UTILS::COLOR::Color GetColorRGB (enumTeletextColor ttc)
Static Private Member Functions
static FT_Error MyFaceRequester (FTC_FaceID face_id, FT_Library library, FT_Pointer request_data, FT_Face *aface)
Private Attributes
std::string m_teletextFont
int m_YOffset
KODI::UTILS::COLOR::Color * m_TextureBuffer
bool m_updateTexture
char prevHeaderPage
char prevTimeSec
int m_CatchRow
int m_CatchCol
int m_CatchedPage
int m_PCOldRow
int m_PCOldCol
FT_Library m_Library
FTC_Manager m_Manager
FTC_SBitCache m_Cache
FTC_SBit m_sBit
FT_Face m_Face
FTC_Node m_anode {nullptr}
FTC_ImageTypeRec m_TypeTTF
int m_Ascender
int m_TempPage
int m_LastPage
std::shared_ptr< TextCacheStruct_t > m_txtCache
TextRenderInfo_t m_RenderInfo
Constructor & Destructor Documentation
CTeletextDecoder()
CTeletextDecoder::CTeletextDecoder ()
References TextRenderInfo_t::bl0, TextRenderInfo_t::gn0, TextRenderInfo_t::InputCounter, m_Ascender, m_CatchCol, m_CatchedPage, m_CatchRow, m_LastPage, m_Library, m_Manager, m_PCOldCol, m_PCOldRow, m_RenderInfo, m_teletextFont, m_TempPage, m_TextureBuffer, m_txtCache, m_updateTexture, m_YOffset, TextRenderInfo_t::Next_10, TextRenderInfo_t::Next_100, TextRenderInfo_t::Prev_10, TextRenderInfo_t::Prev_100, prevHeaderPage, prevTimeSec, TextRenderInfo_t::rd0, TextRenderInfo_t::Show39, TextRenderInfo_t::ShowFlof, TextRenderInfo_t::Showl25, TeletextFont, TextRenderInfo_t::tr0, CSpecialProtocol::TranslatePath(), and TXT_Color_SIZECOLTABLE.
~CTeletextDecoder()
CTeletextDecoder::~CTeletextDecoder (void) virtual default
Member Function Documentation
CatchNextPage()
void CTeletextDecoder::CatchNextPage (int firstlineinc, int inc) private
References TextPageAttr_t::bg, C_G1C, C_G1S, TextPageAttr_t::charset, TextPageAttr_t::fg, m_CatchCol, m_CatchedPage, m_CatchRow, m_RenderInfo, TextRenderInfo_t::PageAtrb, TextRenderInfo_t::PageChar, and RenderCatchedPage().
Referenced by HandleAction(), and StartPageCatching().
Changed()
bool CTeletextDecoder::Changed ()
Checks if the data in the decoder has changed.
Returns
true if the data in the decoder has changed, false otherwise
References IsSubtitlePage(), m_txtCache, m_updateTexture, and prevTimeSec.
Referenced by CGUIDialogTeletext::Process().
ClearBB()
void CTeletextDecoder::ClearBB (KODI::UTILS::COLOR::Color Color) private
References TextRenderInfo_t::Height, m_RenderInfo, m_TextureBuffer, m_YOffset, SDL_memset4(), and TextRenderInfo_t::Width.
Referenced by DoRenderPage(), InitDecoder(), and SwitchTranspMode().
ClearFB()
void CTeletextDecoder::ClearFB (KODI::UTILS::COLOR::Color Color) private
References TextRenderInfo_t::Height, m_RenderInfo, m_TextureBuffer, m_YOffset, SDL_memset4(), and TextRenderInfo_t::Width.
Referenced by InitDecoder().
ColorKey()
void CTeletextDecoder::ColorKey (int target) private
References TextRenderInfo_t::HintMode, TextRenderInfo_t::InputCounter, m_LastPage, m_RenderInfo, m_txtCache, and TextRenderInfo_t::ZoomMode.
Referenced by HandleAction().
CopyBB2FB()
void CTeletextDecoder::CopyBB2FB () private
References TextRenderInfo_t::ClearBBColor, CreateLine25(), TextRenderInfo_t::FontHeight, GetColorRGB(), TextRenderInfo_t::Height, m_RenderInfo, m_TextureBuffer, m_txtCache, m_YOffset, TextRenderInfo_t::PageCatching, SDL_memcpy4, SDL_memset4(), TextRenderInfo_t::TranspMode, TXT_ColorTransp, TextRenderInfo_t::Width, and TextRenderInfo_t::ZoomMode.
Referenced by DoRenderPage(), PageInput(), and RenderCatchedPage().
CreateLine25()
void CTeletextDecoder::CreateLine25 () private
References Decode_ADIP(), Decode_BTT(), TextRenderInfo_t::FontHeight, m_RenderInfo, m_txtCache, TextRenderInfo_t::Next_10, TextRenderInfo_t::Next_100, NextHex(), TextRenderInfo_t::nofirst, TextRenderInfo_t::PageAtrb, TextRenderInfo_t::PageChar, TextRenderInfo_t::PosX, TextRenderInfo_t::PosY, TextRenderInfo_t::Prev_10, TextRenderInfo_t::Prev_100, RenderCharBB(), TextRenderInfo_t::ShowFlof, TextRenderInfo_t::ShowHex, Showlink(), and TopText_GetNext().
Referenced by CopyBB2FB().
Decode_ADIP()
void CTeletextDecoder::Decode_ADIP () private
References dehamming, deparity, CServiceBroker::GetAppComponents(), CApplicationPlayer::LoadPage(), CLog::Log(), LOGERROR, and m_txtCache.
Referenced by CreateLine25().
Decode_BTT()
void CTeletextDecoder::Decode_BTT () private
References dehamming, CServiceBroker::GetAppComponents(), CApplicationPlayer::LoadPage(), CLog::Log(), LOGERROR, m_txtCache, and CDVDTeletextTools::NextDec().
Referenced by CreateLine25().
DecodePage()
TextPageinfo_t * CTeletextDecoder::DecodePage (bool showl25, unsigned char * PageChar, TextPageAttr_t * PageAtrb, bool HintMode, bool showflof) private
References alpha_black, alpha_blue, alpha_cyan, alpha_green, alpha_magenta, alpha_red, alpha_white, alpha_yellow, TextPageAttr_t::bg, black_background, TextPageinfo_t::boxed, TextPageAttr_t::boxwin, C_G0P, C_G0S, C_G1C, C_G1S, TextPageAttr_t::charset, conceal, TextPageAttr_t::concealed, contiguous_mosaic, CDVDTeletextTools::deh24(), dehamming, deparity, TextPageAttr_t::diacrit, double_height, double_size, double_width, TextPageAttr_t::doubleh, TextPageAttr_t::doublew, end_box, esc, Eval_l25(), TextPageAttr_t::fg, flash, TextPageAttr_t::flashing, FUNC_DRCS, FUNC_GDRCS, FUNC_GPOP, FUNC_MOT, FUNC_POP, TextPageinfo_t::function, CServiceBroker::GetAppComponents(), CDVDTeletextTools::Hex2Str(), hold_mosaic, TextPageAttr_t::IgnoreAtBlackBgSubst, index(), TextPageAttr_t::inverted, IsDec(), CApplicationPlayer::LoadPage(), m_txtCache, mosaic_black, mosaic_blue, mosaic_cyan, mosaic_green, mosaic_magenta, mosaic_red, mosaic_white, mosaic_yellow, new_background, normal_size, number2char, TextCachedPage_t::p0, TextPageinfo_t::p24, TextCachedPage_t::pageinfo, release_mosaic, separated_mosaic, TextPageAttr_t::setG0G2, TextPageAttr_t::setX26, start_box, steady, TELETEXT_PAGE_SIZE, TXT_ColorBlack, TXT_ColorTransp, TXT_ColorWhite, and TextPageAttr_t::underline.
Referenced by RenderPage().
DoFlashing()
void CTeletextDecoder::DoFlashing (int startrow) private
References TextPageAttr_t::bg, CountryConversionTable, TextPageAttr_t::doubleh, TextPageAttr_t::doublew, TextPageAttr_t::fg, TextPageAttr_t::flashing, TextRenderInfo_t::FontHeight, index(), m_RenderInfo, m_txtCache, m_updateTexture, NAT_MAX_FROM_HEADER, TextPageinfo_t::national, TextPageinfo_t::nationalvalid, TextRenderInfo_t::nofirst, TextRenderInfo_t::PageAtrb, TextRenderInfo_t::PageChar, TextCachedPage_t::pageinfo, TextRenderInfo_t::PageInfo, TextRenderInfo_t::PosX, TextRenderInfo_t::PosY, RenderCharFB(), SetPosX(), and TextRenderInfo_t::ZoomMode.
Referenced by DoRenderPage(), and RenderPage().
DoRenderPage()
void CTeletextDecoder::DoRenderPage (int startrow, int national_subset_bak) private
References ATR_WB, TextPageAttr_t::bg, TextRenderInfo_t::Boxed, ClearBB(), TextRenderInfo_t::ClearBBColor, CopyBB2FB(), CountryConversionTable, DoFlashing(), TextPageAttr_t::doubleh, TextPageAttr_t::doublew, DRCSCOLS, DRCSROWS, DRCSXSPC, DRCSYSPC, DRCSZOOMX, DRCSZOOMY, TextPageAttr_t::fg, FillBorder(), TextRenderInfo_t::FontHeight, TextRenderInfo_t::FontWidth_Normal, FUNC_DRCS, FUNC_GDRCS, TextPageinfo_t::function, GetColorRGB(), TextRenderInfo_t::Height, index(), m_RenderInfo, m_TextureBuffer, m_txtCache, NAT_MAX_FROM_HEADER, TextPageinfo_t::national, TextPageinfo_t::nationalvalid, TextRenderInfo_t::nofirst, TextRenderInfo_t::PageAtrb, TextRenderInfo_t::PageChar, TextRenderInfo_t::PageInfo, TextRenderInfo_t::PosX, TextRenderInfo_t::PosY, RenderCharBB(), RenderDRCS(), SetFontWidth(), TextRenderInfo_t::Show39, Text_AtrTable, TextRenderInfo_t::TranspMode, TXT_ColorBlack, TXT_ColorTransp, TXT_ColorWhite, and TextRenderInfo_t::Width.
Referenced by RenderPage().
DrawHLine()
void CTeletextDecoder::DrawHLine (KODI::UTILS::COLOR::Color * lfb, int xres, int x, int y, int l, KODI::UTILS::COLOR::Color color) private
References color, and SDL_memset4().
Referenced by DrawShape(), and RenderChar().
DrawShape()
void CTeletextDecoder::DrawShape (KODI::UTILS::COLOR::Color * lfb, int xres, int x, int y, int shapenumber, int curfontwidth, int fontheight, int curfontheight, KODI::UTILS::COLOR::Color fgcolor, KODI::UTILS::COLOR::Color bgcolor, bool clear) private
References aShapes, bgcolor, DrawHLine(), DrawShape(), DrawVLine(), FillRect(), FillTrapez(), FlipHorz(), FlipVert(), S_BOX, S_BTR, S_END, S_FHL, S_FLH, S_FLV, S_FVL, S_INV, S_LNK, S_TRA, ShapeCoord(), and t.
Referenced by DrawShape(), and RenderChar().
DrawVLine()
void CTeletextDecoder::DrawVLine (KODI::UTILS::COLOR::Color * lfb, int xres, int x, int y, int l, KODI::UTILS::COLOR::Color color) private
References color.
Referenced by DrawShape(), and RenderChar().
EndDecoder()
void CTeletextDecoder::EndDecoder ()
References CLog::Log(), LOGDEBUG, LOGINFO, m_anode, m_Library, m_Manager, m_RenderInfo, m_TextureBuffer, m_txtCache, and TextRenderInfo_t::SubtitleCache.
Referenced by CGUIDialogTeletext::OnDeinitWindow().
Eval_l25()
void CTeletextDecoder::Eval_l25 (unsigned char * page_char, TextPageAttr_t * PageAtrb, bool HintMode) private
References TextPageAttr_t::bg, TextExtData_t::bgr, TextExtData_t::BlackBgSubst, TextExtData_t::ColorTableRemapping, TextExtData_t::DefaultCharset, TextExtData_t::DefRowColor, TextExtData_t::DefScreenColor, Eval_NumberedObject(), Eval_Object(), TextPageinfo_t::ext, TextPageAttr_t::fg, FUNC_DRCS, FUNC_GDRCS, FUNC_GPOP, FUNC_POP, CServiceBroker::GetAppComponents(), IsDec(), CApplicationPlayer::LoadPage(), m_txtCache, MapTblBG, MapTblFG, OBJ_ACTIVE, TextExtData_t::p26, TextExtData_t::p27, TextExtData_t::p28Received, Textp27_t::page, TextExtData_t::SecondCharset, SetNational(), and TXT_ColorBlack.
Referenced by DecodePage().
Eval_NumberedObject()
void CTeletextDecoder::Eval_NumberedObject (int p, int s, int packet, int triplet, int high, unsigned char * pAPx, unsigned char * pAPy, unsigned char * pAPx0, unsigned char * pAPy0, unsigned char * page_char, TextPageAttr_t * PageAtrb) private
References CDVDTeletextTools::deh24(), Eval_Object(), CServiceBroker::GetAppComponents(), CApplicationPlayer::LoadPage(), and m_txtCache.
Referenced by Eval_l25(), and Eval_Triplet().
Eval_Object()
void CTeletextDecoder::Eval_Object (int iONr, TextCachedPage_t * pstCachedPage, unsigned char * pAPx, unsigned char * pAPy, unsigned char * pAPx0, unsigned char * pAPy0, tObjType ObjType, unsigned char * pagedata, unsigned char * page_char, TextPageAttr_t * PageAtrb) private
References C_G0P, Eval_Triplet(), iTripletNumber2Data(), OBJ_ACTIVE, OBJ_ADAPTIVE, TXT_ColorBlack, and TXT_ColorWhite.
Referenced by Eval_l25(), Eval_NumberedObject(), and Eval_Triplet().
Eval_Triplet()
int CTeletextDecoder::Eval_Triplet (int iOData, TextCachedPage_t * pstCachedPage, unsigned char * pAPx, unsigned char * pAPy, unsigned char * pAPx0, unsigned char * pAPy0, unsigned char * drcssubp, unsigned char * gdrcssubp, signed char * endcol, TextPageAttr_t * attrPassive, unsigned char * pagedata, unsigned char * page_char, TextPageAttr_t * PageAtrb) private
References TextPageAttr_t::bg, TextPageAttr_t::boxwin, C_G0P, C_G1C, C_G1S, C_G2, C_G3, C_OFFSET_DRCS, TextPageAttr_t::charset, color, TextPageAttr_t::concealed, TextPageAttr_t::diacrit, TextPageAttr_t::doubleh, TextPageAttr_t::doublew, Eval_NumberedObject(), Eval_Object(), TextPageAttr_t::fg, TextPageAttr_t::flashing, TextPageAttr_t::IgnoreAtBlackBgSubst, TextPageAttr_t::inverted, m_txtCache, RowAddress2Row, TextPageAttr_t::setG0G2, TextPageAttr_t::setX26, TXT_ColorBlack, and TextPageAttr_t::underline.
Referenced by Eval_Object().
FillBorder()
void CTeletextDecoder::FillBorder (KODI::UTILS::COLOR::Color Color) private
References FillRect(), TextRenderInfo_t::FontHeight, TextRenderInfo_t::Height, m_RenderInfo, m_TextureBuffer, m_YOffset, and TextRenderInfo_t::Width.
Referenced by DoRenderPage(), and RenderPage().
FillRect()
void CTeletextDecoder::FillRect (KODI::UTILS::COLOR::Color * buffer, int xres, int x, int y, int w, int h, KODI::UTILS::COLOR::Color Color) private
References color, and SDL_memset4().
Referenced by DrawShape(), FillBorder(), FillRectMosaicSeparated(), RenderChar(), RenderCharIntern(), and Showlink().
FillRectMosaicSeparated()
void CTeletextDecoder::FillRectMosaicSeparated (KODI::UTILS::COLOR::Color * lfb, int xres, int x, int y, int w, int h, KODI::UTILS::COLOR::Color fgcolor, KODI::UTILS::COLOR::Color bgcolor, int set) private
References bgcolor, and FillRect().
Referenced by RenderChar().
FillTrapez()
void CTeletextDecoder::FillTrapez (KODI::UTILS::COLOR::Color * lfb, int xres, int x0, int y0, int l0, int xoffset1, int h, int l1, KODI::UTILS::COLOR::Color color) private
References color, and SDL_memset4().
Referenced by DrawShape().
FlipHorz()
void CTeletextDecoder::FlipHorz (KODI::UTILS::COLOR::Color * lfb, int xres, int x, int y, int w, int h) private
References SDL_memcpy4.
Referenced by DrawShape().
FlipVert()
void CTeletextDecoder::FlipVert (KODI::UTILS::COLOR::Color * lfb, int xres, int x, int y, int w, int h) private
References SDL_memcpy4.
Referenced by DrawShape().
GetColorRGB()
Color CTeletextDecoder::GetColorRGB (enumTeletextColor ttc) private
References TextRenderInfo_t::bl0, color, TextRenderInfo_t::gn0, index(), m_RenderInfo, TextRenderInfo_t::rd0, TextRenderInfo_t::tr0, TXT_ColorBlack, TXT_ColorBlue, TXT_ColorCyan, TXT_ColorGreen, TXT_ColorMagenta, TXT_ColorRed, TXT_ColorTransp, TXT_ColorWhite, and TXT_ColorYellow.
Referenced by CopyBB2FB(), DoRenderPage(), InitDecoder(), RenderChar(), RenderCharIntern(), RenderPage(), and Showlink().
GetCurFontWidth()
int CTeletextDecoder::GetCurFontWidth () private
References TextRenderInfo_t::FontWidth, m_RenderInfo, TextRenderInfo_t::nofirst, TextRenderInfo_t::PosX, and TextRenderInfo_t::Width.
Referenced by RenderCharIntern(), and SetPosX().
GetHeight()
int CTeletextDecoder::GetHeight () inline
References TextRenderInfo_t::Height, and m_RenderInfo.
Referenced by CGUIDialogTeletext::OnInitWindow(), and CGUIDialogTeletext::Render().
GetNextPageOne()
void CTeletextDecoder::GetNextPageOne (bool up) private
References TextRenderInfo_t::HintMode, TextRenderInfo_t::InputCounter, m_LastPage, m_RenderInfo, m_txtCache, CDVDTeletextTools::NextDec(), CDVDTeletextTools::PrevDec(), and TextRenderInfo_t::ZoomMode.
Referenced by HandleAction().
GetNextSubPage()
void CTeletextDecoder::GetNextSubPage (int offset) private
References TextRenderInfo_t::HintMode, TextRenderInfo_t::InputCounter, m_RenderInfo, m_txtCache, and TextRenderInfo_t::ZoomMode.
Referenced by HandleAction().
GetTextureBuffer()
KODI::UTILS::COLOR::Color * CTeletextDecoder::GetTextureBuffer () inline
References m_RenderInfo, m_TextureBuffer, m_YOffset, and TextRenderInfo_t::Width.
Referenced by CGUIDialogTeletext::Render().
GetWidth()
int CTeletextDecoder::GetWidth () inline
References m_RenderInfo, and TextRenderInfo_t::Width.
Referenced by CGUIDialogTeletext::OnInitWindow(), and CGUIDialogTeletext::Render().
HandleAction()
bool CTeletextDecoder::HandleAction (const CAction & action)
References ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_PAGE_DOWN, ACTION_PAGE_UP, ACTION_SELECT_ITEM, ACTION_SHOW_INFO, ACTION_TELETEXT_BLUE, ACTION_TELETEXT_GREEN, ACTION_TELETEXT_RED, ACTION_TELETEXT_YELLOW, ATR_WB, TextRenderInfo_t::Boxed, CatchNextPage(), ColorKey(), GetNextPageOne(), GetNextSubPage(), KEY_UNICODE, CLog::Log(), LOGERROR, m_RenderInfo, m_txtCache, TextRenderInfo_t::Next_10, TextRenderInfo_t::Next_100, TextRenderInfo_t::PageCatching, PageInput(), TextRenderInfo_t::PosY, TextRenderInfo_t::Prev_10, TextRenderInfo_t::Prev_100, REMOTE_0, REMOTE_9, RenderCharFB(), SetPosX(), StartPageCatching(), StopPageCatching(), TextRenderInfo_t::SubtitleDelay, SwitchHintMode(), SwitchTranspMode(), SwitchZoomMode(), and Text_AtrTable.
Referenced by CGUIDialogTeletext::OnAction().
InitDecoder()
bool CTeletextDecoder::InitDecoder ()
References TextRenderInfo_t::axdrcs, TextPageAttr_t::bg, C_G0P, TextPageAttr_t::charset, ClearBB(), ClearFB(), DefaultColors, TextPageAttr_t::doubleh, TextPageAttr_t::doublew, TextPageAttr_t::fg, TextRenderInfo_t::FontHeight, TextRenderInfo_t::FontWidth_Normal, CServiceBroker::GetAppComponents(), GetColorRGB(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetGUIScaleX(), CGraphicContext::GetGUIScaleY(), CGraphicContext::GetHeight(), CApplicationPlayer::GetTeletextCache(), CGraphicContext::GetWidth(), CServiceBroker::GetWinSystem(), TextRenderInfo_t::Height, TextPageAttr_t::IgnoreAtBlackBgSubst, CLog::Log(), LOGERROR, m_Ascender, m_Cache, m_Face, m_LastPage, m_Library, m_Manager, m_RenderInfo, m_teletextFont, m_TextureBuffer, m_txtCache, m_TypeTTF, m_YOffset, MyFaceRequester(), TextRenderInfo_t::PageAtrb, TextRenderInfo_t::PageChar, SetColors(), SetFontWidth(), TextRenderInfo_t::Show39, TextRenderInfo_t::TranspMode, TXT_Color_SIZECOLTABLE, TXT_ColorTransp, and TextRenderInfo_t::Width.
Referenced by CGUIDialogTeletext::OnInitWindow().
IsSubtitlePage()
bool CTeletextDecoder::IsSubtitlePage (int pageNumber) const private
References m_txtCache.
Referenced by Changed().
iTripletNumber2Data()
int CTeletextDecoder::iTripletNumber2Data (int iONr, TextCachedPage_t * pstCachedPage, unsigned char * pagedata) private
References CDVDTeletextTools::deh24(), TextPageinfo_t::ext, TextPageinfo_t::p24, TextExtData_t::p26, and TextCachedPage_t::pageinfo.
Referenced by Eval_Object().
MyFaceRequester()
FT_Error CTeletextDecoder::MyFaceRequester (FTC_FaceID face_id, FT_Library library, FT_Pointer request_data, FT_Face * aface) static private
References CLog::Log(), LOGERROR, and LOGINFO.
Referenced by InitDecoder().
NeedRendering()
bool CTeletextDecoder::NeedRendering () inline
References m_updateTexture.
Referenced by CGUIDialogTeletext::Render().
NextHex()
int CTeletextDecoder::NextHex (int i) private
References IsDec(), and m_txtCache.
Referenced by CreateLine25().
PageInput()
void CTeletextDecoder::PageInput (int Number) private
References ATR_WB, CopyBB2FB(), TextRenderInfo_t::HintMode, TextRenderInfo_t::InputCounter, m_LastPage, m_RenderInfo, m_TempPage, m_txtCache, m_updateTexture, Number, TextRenderInfo_t::PosY, RenderCharFB(), SetPosX(), Text_AtrTable, and TextRenderInfo_t::ZoomMode.
Referenced by HandleAction().
RenderCatchedPage()
void CTeletextDecoder::RenderCatchedPage () private
References TextPageAttr_t::bg, CopyBB2FB(), TextPageAttr_t::fg, TextRenderInfo_t::FontHeight, m_CatchCol, m_CatchRow, m_PCOldCol, m_PCOldRow, m_RenderInfo, m_updateTexture, TextRenderInfo_t::PageAtrb, TextRenderInfo_t::PageChar, TextRenderInfo_t::PosY, RenderCharFB(), SetPosX(), t, and TextRenderInfo_t::ZoomMode.
Referenced by CatchNextPage().
RenderChar()
int CTeletextDecoder::RenderChar (KODI::UTILS::COLOR::Color * buffer, int xres, int Char, int * pPosX, int PosY, TextPageAttr_t * Attribute, bool zoom, int curfontwidth, int curfontwidth2, int fontheight, bool transpmode, unsigned char * axdrcs, int Ascender) private
References arrowtable, aShapes, TextPageAttr_t::bg, bgcolor, C_G0S, C_G1C, C_G1S, C_G2, C_G3, C_OFFSET_DRCS, TextPageAttr_t::charset, CountryConversionTable, TextPageAttr_t::doubleh, TextPageAttr_t::doublew, DrawHLine(), DrawShape(), DrawVLine(), f, TextPageAttr_t::fg, FillRect(), FillRectMosaicSeparated(), G0table, G2table, CServiceBroker::GetAppComponents(), GetColorRGB(), TextPageAttr_t::inverted, CApplicationPlayer::LoadPage(), m_txtCache, NAT_AR, NAT_GR, NAT_HB, NAT_RB, NAT_SC, NAT_UA, nationaltable23, nationaltable40, nationaltable5b, nationaltable7b, TextPageinfo_t::p24, TextCachedPage_t::pageinfo, RenderDRCS(), S_ADT, S_CHR, TextPageAttr_t::setG0G2, TextPageAttr_t::setX26, t, and TXT_ColorTransp.
Referenced by RenderCharIntern().
RenderCharBB()
void CTeletextDecoder::RenderCharBB (int Char, TextPageAttr_t * Attribute) private
References TextRenderInfo_t::Height, m_RenderInfo, m_YOffset, and RenderCharIntern().
Referenced by CreateLine25(), DoRenderPage(), and Showlink().
RenderCharFB()
void CTeletextDecoder::RenderCharFB (int Char, TextPageAttr_t * Attribute) private
References m_RenderInfo, m_YOffset, RenderCharIntern(), and TextRenderInfo_t::ZoomMode.
Referenced by DoFlashing(), HandleAction(), PageInput(), RenderCatchedPage(), and RenderPage().
RenderCharIntern()
void CTeletextDecoder::RenderCharIntern (TextRenderInfo_t * RenderInfo, int Char, TextPageAttr_t * Attribute, int zoom, int yoffset) private
References TextRenderInfo_t::axdrcs, TextPageAttr_t::bg, bgcolor, color, TextPageAttr_t::diacrit, TextPageAttr_t::doubleh, TextPageAttr_t::doublew, f, TextPageAttr_t::fg, FillRect(), TextRenderInfo_t::FontHeight, G2table, GetColorRGB(), GetCurFontWidth(), CLog::Log(), LOGERROR, m_anode, m_Ascender, m_Cache, m_Face, m_RenderInfo, m_sBit, m_TextureBuffer, m_txtCache, m_TypeTTF, NAT_AR, NAT_GR, NAT_HB, NAT_RB, NAT_SC, NAT_UA, TextRenderInfo_t::PosX, TextRenderInfo_t::PosY, RenderChar(), t, TextRenderInfo_t::TranspMode, TextRenderInfo_t::TTFShiftX, TextRenderInfo_t::TTFShiftY, TXT_ColorTransp, TextPageAttr_t::underline, and TextRenderInfo_t::Width.
Referenced by RenderCharBB(), and RenderCharFB().
RenderDRCS()
void CTeletextDecoder::RenderDRCS (int xres, unsigned char * s, KODI::UTILS::COLOR::Color * d, unsigned char * ax, KODI::UTILS::COLOR::Color fgcolor, KODI::UTILS::COLOR::Color bgcolor) private
References bgcolor, deparity, and SDL_memset4().
Referenced by DoRenderPage(), and RenderChar().
RenderingDone()
void CTeletextDecoder::RenderingDone () inline
References m_updateTexture.
Referenced by CGUIDialogTeletext::Render().
RenderPage()
void CTeletextDecoder::RenderPage ()
References TextPageAttr_t::bg, TextPageinfo_t::boxed, TextRenderInfo_t::Boxed, DecodePage(), TextRenderInfo_t::DelayStarted, DoFlashing(), DoRenderPage(), TextPageAttr_t::fg, FillBorder(), TextPageAttr_t::flashing, GetColorRGB(), CDVDTeletextTools::Hex2Str(), TextRenderInfo_t::HintMode, TextRenderInfo_t::InputCounter, IsDec(), m_RenderInfo, m_txtCache, m_updateTexture, TextRenderInfo_t::nofirst, TextCachedPage_t::p0, TextRenderInfo_t::PageAtrb, TextSubtitleCache_t::PageAtrb, TextRenderInfo_t::PageChar, TextSubtitleCache_t::PageChar, TextRenderInfo_t::PageInfo, TextRenderInfo_t::PosX, TextRenderInfo_t::PosY, prevHeaderPage, RenderCharFB(), SetColors(), SetPosX(), TextRenderInfo_t::ShowFlof, TextRenderInfo_t::Showl25, SUBTITLE_CACHESIZE, TextRenderInfo_t::SubtitleCache, TextRenderInfo_t::SubtitleDelay, TextSubtitleCache_t::Timestamp, TextRenderInfo_t::TranspMode, TXT_ColorMenu1, TXT_ColorRed, TXT_ColorTransp, TXT_ColorWhite, TXT_ColorYellow, TextSubtitleCache_t::Valid, and TextRenderInfo_t::ZoomMode.
Referenced by CGUIDialogTeletext::Render().
SetColors()
void CTeletextDecoder::SetColors (const unsigned short * pcolormap, int offset, int number) private
References TextRenderInfo_t::bl0, TextRenderInfo_t::gn0, m_RenderInfo, and TextRenderInfo_t::rd0.
Referenced by InitDecoder(), and RenderPage().
SetFontWidth()
void CTeletextDecoder::SetFontWidth (int newWidth) private
References TextRenderInfo_t::axdrcs, TextRenderInfo_t::FontWidth, m_RenderInfo, and m_TypeTTF.
Referenced by DoRenderPage(), InitDecoder(), and Showlink().
SetNational()
int CTeletextDecoder::SetNational (unsigned char sec) private
References CountryConversionTable, m_txtCache, NAT_AR, NAT_ET, NAT_GR, NAT_HB, NAT_LV, NAT_PL, NAT_RB, NAT_SC, NAT_SR, NAT_TR, and NAT_UA.
Referenced by Eval_l25().
SetPosX()
void CTeletextDecoder::SetPosX (int column) private
References GetCurFontWidth(), m_RenderInfo, TextRenderInfo_t::nofirst, and TextRenderInfo_t::PosX.
Referenced by DoFlashing(), HandleAction(), PageInput(), RenderCatchedPage(), and RenderPage().
ShapeCoord()
int CTeletextDecoder::ShapeCoord (int param, int curfontwidth, int curfontheight) private
References S_H11, S_H12, S_H13, S_H23, S_W11, S_W12, S_W13, S_W23, and S_WM3.
Referenced by DrawShape().
Showlink()
void CTeletextDecoder::Showlink (int column, int linkpage) private
References ATR_L250, TextRenderInfo_t::Boxed, FillRect(), TextRenderInfo_t::FontHeight, TextRenderInfo_t::FontWidth, GetColorRGB(), TextRenderInfo_t::Height, CDVDTeletextTools::Hex2Str(), m_RenderInfo, m_TextureBuffer, m_txtCache, m_YOffset, TextRenderInfo_t::nofirst, TextRenderInfo_t::PosX, TextRenderInfo_t::PosY, RenderCharBB(), SetFontWidth(), Text_AtrTable, TXT_ColorTransp, and TextRenderInfo_t::Width.
Referenced by CreateLine25().
StartPageCatching()
void CTeletextDecoder::StartPageCatching () private
References CatchNextPage(), TextRenderInfo_t::FontHeight, TextRenderInfo_t::InputCounter, m_CatchCol, m_CatchedPage, m_CatchRow, m_PCOldCol, m_PCOldRow, m_RenderInfo, m_txtCache, TextRenderInfo_t::PageCatching, TextRenderInfo_t::PosX, TextRenderInfo_t::PosY, and TextRenderInfo_t::ZoomMode.
Referenced by HandleAction().
StopPageCatching()
void CTeletextDecoder::StopPageCatching () private
References TextRenderInfo_t::HintMode, m_CatchedPage, m_LastPage, m_RenderInfo, m_txtCache, TextRenderInfo_t::PageCatching, and TextRenderInfo_t::ZoomMode.
Referenced by HandleAction().
SwitchHintMode()
void CTeletextDecoder::SwitchHintMode () private
References TextRenderInfo_t::HintMode, m_RenderInfo, m_txtCache, and TextRenderInfo_t::Showl25.
Referenced by HandleAction().
SwitchTranspMode()
void CTeletextDecoder::SwitchTranspMode () private
References ClearBB(), m_RenderInfo, m_txtCache, TextRenderInfo_t::TranspMode, and TXT_ColorTransp.
Referenced by HandleAction().
SwitchZoomMode()
void CTeletextDecoder::SwitchZoomMode () private
References m_RenderInfo, m_txtCache, and TextRenderInfo_t::ZoomMode.
Referenced by HandleAction().
TopText_GetNext()
int CTeletextDecoder::TopText_GetNext (int startpage, int up, int findgroup) private
References IsDec(), m_txtCache, CDVDTeletextTools::NextDec(), and CDVDTeletextTools::PrevDec().
Referenced by CreateLine25().
Member Data Documentation
m_anode
FTC_Node CTeletextDecoder::m_anode {nullptr} private
An opaque handle to a cache node object. Each cache node is reference-counted.
Referenced by EndDecoder(), and RenderCharIntern().
m_Ascender
int CTeletextDecoder::m_Ascender private
Referenced by CTeletextDecoder(), InitDecoder(), and RenderCharIntern().
m_Cache
FTC_SBitCache CTeletextDecoder::m_Cache private
Referenced by InitDecoder(), and RenderCharIntern().
m_CatchCol
int CTeletextDecoder::m_CatchCol private
Referenced by CatchNextPage(), CTeletextDecoder(), RenderCatchedPage(), and StartPageCatching().
m_CatchedPage
int CTeletextDecoder::m_CatchedPage private
Referenced by CatchNextPage(), CTeletextDecoder(), StartPageCatching(), and StopPageCatching().
m_CatchRow
int CTeletextDecoder::m_CatchRow private
Referenced by CatchNextPage(), CTeletextDecoder(), RenderCatchedPage(), and StartPageCatching().
m_Face
FT_Face CTeletextDecoder::m_Face private
Referenced by InitDecoder(), and RenderCharIntern().
m_LastPage
int CTeletextDecoder::m_LastPage private
Referenced by ColorKey(), CTeletextDecoder(), GetNextPageOne(), InitDecoder(), PageInput(), and StopPageCatching().
m_Library
FT_Library CTeletextDecoder::m_Library private
Referenced by CTeletextDecoder(), EndDecoder(), and InitDecoder().
m_Manager
FTC_Manager CTeletextDecoder::m_Manager private
Referenced by CTeletextDecoder(), EndDecoder(), and InitDecoder().
m_PCOldCol
int CTeletextDecoder::m_PCOldCol private
Referenced by CTeletextDecoder(), RenderCatchedPage(), and StartPageCatching().
m_PCOldRow
int CTeletextDecoder::m_PCOldRow private
Referenced by CTeletextDecoder(), RenderCatchedPage(), and StartPageCatching().
m_RenderInfo
TextRenderInfo_t CTeletextDecoder::m_RenderInfo private
Referenced by CatchNextPage(), ClearBB(), ClearFB(), ColorKey(), CopyBB2FB(), CreateLine25(), CTeletextDecoder(), DoFlashing(), DoRenderPage(), EndDecoder(), FillBorder(), GetColorRGB(), GetCurFontWidth(), GetHeight(), GetNextPageOne(), GetNextSubPage(), GetTextureBuffer(), GetWidth(), HandleAction(), InitDecoder(), PageInput(), RenderCatchedPage(), RenderCharBB(), RenderCharFB(), RenderCharIntern(), RenderPage(), SetColors(), SetFontWidth(), SetPosX(), Showlink(), StartPageCatching(), StopPageCatching(), SwitchHintMode(), SwitchTranspMode(), and SwitchZoomMode().
m_sBit
FTC_SBit CTeletextDecoder::m_sBit private
Referenced by RenderCharIntern().
m_teletextFont
std::string CTeletextDecoder::m_teletextFont private
Referenced by CTeletextDecoder(), and InitDecoder().
m_TempPage
int CTeletextDecoder::m_TempPage private
Referenced by CTeletextDecoder(), and PageInput().
m_TextureBuffer
KODI::UTILS::COLOR::Color* CTeletextDecoder::m_TextureBuffer private
Referenced by ClearBB(), ClearFB(), CopyBB2FB(), CTeletextDecoder(), DoRenderPage(), EndDecoder(), FillBorder(), GetTextureBuffer(), InitDecoder(), RenderCharIntern(), and Showlink().
m_txtCache
std::shared_ptr<TextCacheStruct_t> CTeletextDecoder::m_txtCache private
Referenced by Changed(), ColorKey(), CopyBB2FB(), CreateLine25(), CTeletextDecoder(), Decode_ADIP(), Decode_BTT(), DecodePage(), DoFlashing(), DoRenderPage(), EndDecoder(), Eval_l25(), Eval_NumberedObject(), Eval_Triplet(), GetNextPageOne(), GetNextSubPage(), HandleAction(), InitDecoder(), IsSubtitlePage(), NextHex(), PageInput(), RenderChar(), RenderCharIntern(), RenderPage(), SetNational(), Showlink(), StartPageCatching(), StopPageCatching(), SwitchHintMode(), SwitchTranspMode(), SwitchZoomMode(), and TopText_GetNext().
m_TypeTTF
FTC_ImageTypeRec CTeletextDecoder::m_TypeTTF private
Referenced by InitDecoder(), RenderCharIntern(), and SetFontWidth().
m_updateTexture
bool CTeletextDecoder::m_updateTexture private
Referenced by Changed(), CTeletextDecoder(), DoFlashing(), NeedRendering(), PageInput(), RenderCatchedPage(), RenderingDone(), and RenderPage().
m_YOffset
int CTeletextDecoder::m_YOffset private
Referenced by ClearBB(), ClearFB(), CopyBB2FB(), CTeletextDecoder(), FillBorder(), GetTextureBuffer(), InitDecoder(), RenderCharBB(), RenderCharFB(), and Showlink().
prevHeaderPage
char CTeletextDecoder::prevHeaderPage private
Referenced by CTeletextDecoder(), and RenderPage().
prevTimeSec
char CTeletextDecoder::prevTimeSec private
Referenced by Changed(), and CTeletextDecoder().
The documentation for this class was generated from the following files:
Teletext.h
Teletext.cpp