Kodi Documentation: CHTTPPythonHandler Class Reference
CHTTPPythonHandler Class Reference
#include <HTTPPythonHandler.h>
Public Member Functions
CHTTPPythonHandler ()
~CHTTPPythonHandler () override=default
IHTTPRequestHandler * Create (const HTTPRequest &request) const override
Creates a new HTTP request handler for the given request.
bool CanHandleRequest (const HTTPRequest &request) const override
Checks if the HTTP request handler can handle the given request.
bool CanHandleRanges () const override
Whether the HTTP response could also be provided in ranges.
bool CanBeCached () const override
Whether the HTTP response can be cached.
bool GetLastModifiedDate (CDateTime &lastModified) const override
Returns the last modification date of the response data.
MHD_RESULT HandleRequest () override
Handles the HTTP request.
HttpResponseRanges GetResponseData () const override
Returns the ranges with raw data belonging to the response.
std::string GetRedirectUrl () const override
Returns the URL to which the request should be redirected.
int GetPriority () const override
Returns the priority of the HTTP request handler.
Public Member Functions inherited from IHTTPRequestHandler
virtual ~IHTTPRequestHandler ()=default
virtual int GetMaximumAgeForCaching () const
Returns the maximum age (in seconds) for which the response can be cached.
virtual std::string GetResponseFile () const
Returns the path to the file that should be returned as the response.
const HTTPRequest & GetRequest () const
Returns the HTTP request handled by the HTTP request handler.
bool IsRequestRanged () const
Returns true if the HTTP request is ranged, otherwise false.
void SetRequestRanged (bool ranged)
Sets whether the HTTP request contains ranges or not.
void SetResponseStatus (int status)
Sets the response status of the HTTP response.
bool HasResponseHeader (const std::string &field) const
Checks if the given HTTP header field is part of the response details.
bool AddResponseHeader (const std::string &field, const std::string &value, bool allowMultiple=false)
Adds the given HTTP header field and value to the response details.
const HTTPResponseDetails & GetResponseDetails () const
Returns the HTTP response header details.
void AddPostField (const std::string &key, const std::string &value)
Adds the given key-value pair extracted from the HTTP POST data.
bool AddPostData (const char *data, size_t size)
Adds the given raw HTTP POST data.
Protected Member Functions
CHTTPPythonHandler (const HTTPRequest &request)
bool appendPostData (const char *data, size_t size) override
Protected Member Functions inherited from IHTTPRequestHandler
IHTTPRequestHandler ()
IHTTPRequestHandler (const HTTPRequest &request)
bool GetRequestedRanges (uint64_t totalLength)
bool GetHostnameAndPort (std::string &hostname, uint16_t &port)
Private Attributes
std::string m_scriptPath
ADDON::AddonPtr m_addon
CDateTime m_lastModified
std::string m_requestData
std::string m_responseData
HttpResponseRanges m_responseRanges
std::string m_redirectUrl
Additional Inherited Members
Protected Attributes inherited from IHTTPRequestHandler
HTTPRequest m_request
HTTPResponseDetails m_response
std::map< std::string, std::string > m_postFields
Constructor & Destructor Documentation
CHTTPPythonHandler() [1/2]
CHTTPPythonHandler::CHTTPPythonHandler ()
Referenced by Create().
~CHTTPPythonHandler()
CHTTPPythonHandler::~CHTTPPythonHandler () override default
CHTTPPythonHandler() [2/2]
CHTTPPythonHandler::CHTTPPythonHandler (const HTTPRequest & request) explicit protected
References __stat64, HTTPError, HTTPMemoryDownloadNoFreeCopy, HTTPRedirect, m_addon, m_lastModified, m_redirectUrl, IHTTPRequestHandler::m_request, IHTTPRequestHandler::m_response, m_scriptPath, URIUtils::PathHasParent(), HTTPRequest::pathUrl, CHTTPWebinterfaceHandler::ResolveUrl(), XFILE::CFile::Stat(), HTTPResponseDetails::status, HTTPResponseDetails::type, ADDON::WEB_INTERFACE, and ADDON::WebinterfaceTypeStatic.
Member Function Documentation
appendPostData()
bool CHTTPPythonHandler::appendPostData (const char * data, size_t size) override protected virtual
Reimplemented from IHTTPRequestHandler.
References data(), CLog::GetLogger(), CServiceBroker::GetLogging(), m_requestData, and MAX_STRING_POST_SIZE.
CanBeCached()
bool CHTTPPythonHandler::CanBeCached () const inline override virtual
Whether the HTTP response can be cached.
Reimplemented from IHTTPRequestHandler.
CanHandleRanges()
bool CHTTPPythonHandler::CanHandleRanges () const inline override virtual
Whether the HTTP response could also be provided in ranges.
Reimplemented from IHTTPRequestHandler.
CanHandleRequest()
bool CHTTPPythonHandler::CanHandleRequest (const HTTPRequest & request) const override virtual
Checks if the HTTP request handler can handle the given request.
Parameters
request HTTP request to be handled
Returns
True if the given HTTP request can be handled otherwise false.
Implements IHTTPRequestHandler.
References ADDON::CWebinterface::GetType(), HTTPRequest::pathUrl, CHTTPWebinterfaceHandler::ResolveAddon(), ADDON::WEB_INTERFACE, and ADDON::WebinterfaceTypeWsgi.
Create()
IHTTPRequestHandler * CHTTPPythonHandler::Create (const HTTPRequest & request) const inline override virtual
Creates a new HTTP request handler for the given request.
This call is responsible for doing some preparation work like - depending on the supported features - determining whether the requested entity supports ranges, whether it can be cached and what it's last modified date is.
Parameters
request HTTP request to be handled
Implements IHTTPRequestHandler.
References CHTTPPythonHandler().
GetLastModifiedDate()
bool CHTTPPythonHandler::GetLastModifiedDate (CDateTime & lastModified) const override virtual
Returns the last modification date of the response data.
This is only used if the response can be cached.
Reimplemented from IHTTPRequestHandler.
References CDateTime::IsValid(), and m_lastModified.
GetPriority()
int CHTTPPythonHandler::GetPriority () const inline override virtual
Returns the priority of the HTTP request handler.
The higher the priority the more important is the HTTP request handler.
Reimplemented from IHTTPRequestHandler.
GetRedirectUrl()
std::string CHTTPPythonHandler::GetRedirectUrl () const inline override virtual
Returns the URL to which the request should be redirected.
This is only used if the response type is HTTPRedirect.
Reimplemented from IHTTPRequestHandler.
References m_redirectUrl.
GetResponseData()
HttpResponseRanges CHTTPPythonHandler::GetResponseData () const inline override virtual
Returns the ranges with raw data belonging to the response.
This is only used if the response type is one of the HTTPMemoryDownload types.
Reimplemented from IHTTPRequestHandler.
References m_responseRanges.
HandleRequest()
MHD_RESULT CHTTPPythonHandler::HandleRequest () override virtual
Handles the HTTP request.
Returns
MHD_NO if a severe error has occurred otherwise MHD_YES.
Implements IHTTPRequestHandler.
References HTTPRequest::connection, HTTPPythonRequest::connection, HTTPResponseDetails::contentType, CScriptInvocationManager::ExecuteSync(), HTTPPythonRequest::file, CDateTime::GetCurrentDateTime(), URIUtils::GetFileName(), IHTTPRequestHandler::GetHostnameAndPort(), CScriptInvocationManager::GetInstance(), CHTTPPythonInvoker::GetRequest(), HTTPRequestHandlerUtils::GetRequestHeaderValues(), HTTPPythonRequest::getValues, CServiceBroker::GetXBPython(), HTTPResponseDetails::headers, HTTPPythonRequest::headerValues, HTTPPythonRequest::hostname, HTTPError, HTTPMemoryDownloadNoFreeCopy, HTTPNone, HTTPRedirect, CDateTime::IsValid(), HTTPPythonRequest::lastModifiedTime, m_addon, m_lastModified, IHTTPRequestHandler::m_postFields, IHTTPRequestHandler::m_request, m_requestData, IHTTPRequestHandler::m_response, m_responseData, m_responseRanges, m_scriptPath, HTTPRequest::method, HTTPPythonRequest::method, HTTPPythonRequest::path, HTTPRequest::pathUrl, HTTPRequest::pathUrlFull, HTTPPythonRequest::port, HTTPPythonRequest::postValues, HTTPPythonRequest::requestContent, HTTPPythonRequest::requestTime, HTTPPythonRequest::responseContentType, HTTPPythonRequest::responseData, HTTPPythonRequest::responseHeaders, HTTPPythonRequest::responseHeadersError, HTTPPythonRequest::responseLength, HTTPPythonRequest::responseStatus, HTTPPythonRequest::responseType, HTTPResponseDetails::status, HTTPResponseDetails::totalLength, HTTPResponseDetails::type, HTTPPythonRequest::url, HTTPRequest::version, and HTTPPythonRequest::version.
Member Data Documentation
m_addon
ADDON::AddonPtr CHTTPPythonHandler::m_addon private
Referenced by CHTTPPythonHandler(), and HandleRequest().
m_lastModified
CDateTime CHTTPPythonHandler::m_lastModified private
Referenced by CHTTPPythonHandler(), GetLastModifiedDate(), and HandleRequest().
m_redirectUrl
std::string CHTTPPythonHandler::m_redirectUrl private
Referenced by CHTTPPythonHandler(), and GetRedirectUrl().
m_requestData
std::string CHTTPPythonHandler::m_requestData private
Referenced by appendPostData(), and HandleRequest().
m_responseData
std::string CHTTPPythonHandler::m_responseData private
Referenced by HandleRequest().
m_responseRanges
HttpResponseRanges CHTTPPythonHandler::m_responseRanges private
Referenced by GetResponseData(), and HandleRequest().
m_scriptPath
std::string CHTTPPythonHandler::m_scriptPath private
Referenced by CHTTPPythonHandler(), and HandleRequest().
The documentation for this class was generated from the following files:
HTTPPythonHandler.h
HTTPPythonHandler.cpp