Kodi Documentation: ADDON::Interface_GUIControlTextBox Struct Reference
ADDON::Interface_GUIControlTextBox Struct Reference
Global gui Add-on to Kodi callback functions.
#include <TextBox.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
callback functions from add-on to kodi
static void reset (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *text)
static char * get_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void scroll (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, unsigned int position)
static void set_auto_scrolling (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int delay, int time, int repeat)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold general gui functions and initialize also all other gui related types not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/controls/TextBox.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIControlTextBox::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_text_box, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
get_text()
char * ADDON::Interface_GUIControlTextBox::get_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUITextBox::GetDescription(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIControlTextBox::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_text_box, get_text(), AddonToKodiFuncTable_kodi_gui_control_text_box::get_text, AddonToKodiFuncTable_Addon::kodi_gui, reset(), AddonToKodiFuncTable_kodi_gui_control_text_box::reset, scroll(), AddonToKodiFuncTable_kodi_gui_control_text_box::scroll, set_auto_scrolling(), AddonToKodiFuncTable_kodi_gui_control_text_box::set_auto_scrolling, set_text(), AddonToKodiFuncTable_kodi_gui_control_text_box::set_text, set_visible(), AddonToKodiFuncTable_kodi_gui_control_text_box::set_visible, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
reset()
void ADDON::Interface_GUIControlTextBox::reset (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIControl::GetParentID(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_RESET, ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
scroll()
void ADDON::Interface_GUIControlTextBox::scroll (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, unsigned int position) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUITextBox::Scroll().
Referenced by Init().
set_auto_scrolling()
void ADDON::Interface_GUIControlTextBox::set_auto_scrolling (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, int delay, int time, int repeat) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUITextBox::SetAutoScrolling().
Referenced by Init().
set_text()
void ADDON::Interface_GUIControlTextBox::set_text (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * text) static
References CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIControl::GetParentID(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_SET, ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUIMessage::SetLabel(), and text.
Referenced by Init().
set_visible()
void ADDON::Interface_GUIControlTextBox::set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetVisible().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/controls/TextBox.h
TextBox.cpp