Kodi Documentation: CRendererVTB Class Reference
CRendererVTB Class Reference
#include <RendererVTBGLES.h>
Classes
struct CRenderBuffer
Public Member Functions
CRendererVTB ()=default
~CRendererVTB () override
void ReleaseBuffer (int idx) override
bool NeedBuffer (int idx) override
CRendererVTB ()
~CRendererVTB () override
void ReleaseBuffer (int idx) override
bool NeedBuffer (int idx) override
Public Member Functions inherited from CLinuxRendererGL
CLinuxRendererGL ()
~CLinuxRendererGL () override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
bool IsConfigured () override
void AddVideoPicture (const VideoPicture &picture, int index) override
void UnInit () override
bool Flush (bool saveBuffers) override
void SetBufferSize (int numBuffers) override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
void Update () override
bool RenderCapture (int index, CRenderCapture *capture) override
CRenderInfo GetRenderInfo () override
bool ConfigChanged (const VideoPicture &picture) override
bool SupportsMultiPassRendering () override
bool Supports (ERENDERFEATURE feature) const override
bool Supports (ESCALINGMETHOD method) const override
CRenderCapture * GetRenderCapture () override
Public Member Functions inherited from CBaseRenderer
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool IsPictureHW (const VideoPicture &picture)
virtual bool WantsDoublePass ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
virtual DEBUG_INFO_VIDEO GetDebugInfo (int idx)
Public Member Functions inherited from CLinuxRendererGLES
CLinuxRendererGLES ()
~CLinuxRendererGLES () override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
bool IsConfigured () override
void AddVideoPicture (const VideoPicture &picture, int index) override
void UnInit () override
bool Flush (bool saveBuffers) override
void SetBufferSize (int numBuffers) override
bool IsGuiLayer () override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
void Update () override
bool RenderCapture (int index, CRenderCapture *capture) override
CRenderInfo GetRenderInfo () override
bool ConfigChanged (const VideoPicture &picture) override
bool SupportsMultiPassRendering () override
bool Supports (ERENDERFEATURE feature) const override
bool Supports (ESCALINGMETHOD method) const override
CRenderCapture * GetRenderCapture () override
Static Public Member Functions
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Static Public Member Functions inherited from CLinuxRendererGL
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Static Public Member Functions inherited from CBaseRenderer
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Static Public Member Functions inherited from CLinuxRendererGLES
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Protected Member Functions
bool LoadShadersHook () override
void AfterRenderHook (int idx) override
EShaderFormat GetShaderFormat () override
bool UploadTexture (int index) override
void DeleteTexture (int index) override
bool CreateTexture (int index) override
bool LoadShadersHook () override
void AfterRenderHook (int idx) override
EShaderFormat GetShaderFormat () override
bool UploadTexture (int index) override
void DeleteTexture (int index) override
bool CreateTexture (int index) override
Protected Member Functions inherited from CLinuxRendererGL
bool Render (unsigned int flags, int renderBuffer)
void ClearBackBuffer ()
void ClearBackBufferQuad ()
void DrawBlackBars ()
bool ValidateRenderer ()
virtual bool ValidateRenderTarget ()
virtual void LoadShaders (int field=FIELD_FULL)
void SetTextureFilter (GLenum method)
void UpdateVideoFilter ()
void CheckVideoParameters (int index)
AVColorPrimaries GetSrcPrimaries (AVColorPrimaries srcPrimaries, unsigned int width, unsigned int height)
bool UploadYV12Texture (int index)
void DeleteYV12Texture (int index)
bool CreateYV12Texture (int index)
bool UploadNV12Texture (int index)
void DeleteNV12Texture (int index)
bool CreateNV12Texture (int index)
bool UploadYUV422PackedTexture (int index)
void DeleteYUV422PackedTexture (int index)
bool CreateYUV422PackedTexture (int index)
void CalculateTextureSourceRects (int source, int num_planes)
void RenderToFBO (int renderBuffer, int field, bool weave=false)
void RenderFromFBO ()
void RenderSinglePass (int renderBuffer, int field)
void RenderRGB (int renderBuffer, int field)
void RenderProgressiveWeave (int renderBuffer, int field)
void BindPbo (CPictureBuffer &buff)
void UnBindPbo (CPictureBuffer &buff)
void LoadPlane (CYuvPlane &plane, int type, unsigned width, unsigned height, int stride, int bpp, void *data)
void GetPlaneTextureSize (CYuvPlane &plane)
GLint GetInternalFormat (GLint format, int bpp)
virtual bool RenderHook (int idx)
virtual bool CanSaveBuffers ()
bool LoadCLUT ()
void DeleteCLUT ()
Protected Member Functions inherited from CBaseRenderer
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ManageRenderArea ()
virtual void ReorderDrawPoints ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Protected Member Functions inherited from CLinuxRendererGLES
virtual bool Render (unsigned int flags, int index)
virtual void RenderUpdateVideo (bool clear, unsigned int flags=0, unsigned int alpha=255)
int NextYV12Texture ()
virtual bool ValidateRenderTarget ()
virtual void LoadShaders (int field=FIELD_FULL)
virtual void ReleaseShaders ()
void SetTextureFilter (GLenum method)
void UpdateVideoFilter ()
AVColorPrimaries GetSrcPrimaries (AVColorPrimaries srcPrimaries, unsigned int width, unsigned int height)
bool UploadYV12Texture (int index)
void DeleteYV12Texture (int index)
bool CreateYV12Texture (int index)
virtual bool SkipUploadYV12 (int index)
bool UploadNV12Texture (int index)
void DeleteNV12Texture (int index)
bool CreateNV12Texture (int index)
void CalculateTextureSourceRects (int source, int num_planes)
void RenderToFBO (int index, int field)
void RenderFromFBO ()
void RenderSinglePass (int index, int field)
virtual bool RenderHook (int idx)
void LoadPlane (CYuvPlane &plane, int type, unsigned width, unsigned height, int stride, int bpp, void *data)
Protected Attributes
CVOpenGLESTextureCacheRef m_textureCache = nullptr
CRenderBuffer m_vtbBuffers [NUM_BUFFERS]
CVEAGLContext m_glContext
Protected Attributes inherited from CLinuxRendererGL
struct {
CFrameBufferObject fbo
float width
float height
} m_fbo
GLint m_intermediateFormat {GL_RGBA8}
GLint m_intermediateType {GL_UNSIGNED_BYTE}
bool m_intermediateGammaCorrection {false}
int m_iYV12RenderBuffer = 0
int m_NumYV12Buffers = 0
bool m_bConfigured = false
bool m_bValidated = false
GLenum m_textureTarget = GL_TEXTURE_2D
int m_renderMethod = RENDER_GLSL
RenderQuality m_renderQuality = RQ_SINGLEPASS
CRenderSystemGL * m_renderSystem = nullptr
int m_currentField = FIELD_FULL
int m_reloadShaders = 0
CPictureBuffer m_buffers [NUM_BUFFERS]
Shaders::GL::BaseYUV2RGBGLSLShader * m_pYUVShader = nullptr
Shaders::GL::BaseVideoFilterShader * m_pVideoFilterShader = nullptr
ESCALINGMETHOD m_scalingMethod = VS_SCALINGMETHOD_LINEAR
ESCALINGMETHOD m_scalingMethodGui = VS_SCALINGMETHOD_MAX
bool m_useDithering
unsigned int m_ditherDepth
bool m_fullRange
AVColorPrimaries m_srcPrimaries
bool m_toneMap = false
ETONEMAPMETHOD m_toneMapMethod = VS_TONEMAPMETHOD_OFF
float m_clearColour = 0.0f
bool m_pboSupported = true
bool m_pboUsed = false
bool m_nonLinStretch = false
bool m_nonLinStretchGui = false
float m_pixelRatio = 0.0f
CRect m_viewRect
std::unique_ptr< CColorManager > m_ColorManager
GLuint m_tCLUTTex
uint16_t * m_CLUT
int m_CLUTsize
int m_cmsToken
bool m_cmsOn
Protected Attributes inherited from CBaseRenderer
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Protected Attributes inherited from CLinuxRendererGLES
struct {
CFrameBufferObject fbo
float width {0.0}
float height {0.0}
} m_fbo
int m_iYV12RenderBuffer {0}
int m_NumYV12Buffers {0}
bool m_bConfigured {false}
bool m_bValidated {false}
GLenum m_textureTarget = GL_TEXTURE_2D
int m_renderMethod {RENDER_GLSL}
RenderQuality m_renderQuality {RQ_SINGLEPASS}
int m_currentField {FIELD_FULL}
int m_reloadShaders {0}
CRenderSystemGLES * m_renderSystem {nullptr}
GLenum m_pixelStoreKey {0}
CPictureBuffer m_buffers [NUM_BUFFERS]
Shaders::GLES::BaseYUV2RGBGLSLShader * m_pYUVProgShader {nullptr}
Shaders::GLES::BaseYUV2RGBGLSLShader * m_pYUVBobShader {nullptr}
Shaders::GLES::BaseVideoFilterShader * m_pVideoFilterShader {nullptr}
ESCALINGMETHOD m_scalingMethod {VS_SCALINGMETHOD_LINEAR}
ESCALINGMETHOD m_scalingMethodGui {VS_SCALINGMETHOD_MAX}
bool m_fullRange
AVColorPrimaries m_srcPrimaries
bool m_toneMap = false
ETONEMAPMETHOD m_toneMapMethod = VS_TONEMAPMETHOD_OFF
bool m_passthroughHDR = false
unsigned char * m_planeBuffer = nullptr
size_t m_planeBufferSize = 0
float m_clearColour {0.0f}
CRect m_viewRect
Additional Inherited Members
Static Protected Attributes inherited from CLinuxRendererGLES
static const int FIELD_FULL {0}
static const int FIELD_TOP {1}
static const int FIELD_BOT {2}
Constructor & Destructor Documentation
CRendererVTB() [1/2]
CRendererVTB::CRendererVTB () default
References CServiceBroker::GetWinSystem(), CLog::Log(), LOGERROR, m_glContext, m_textureCache, and m_vtbBuffers.
Referenced by Create().
~CRendererVTB() [1/2]
CRendererVTB::~CRendererVTB () override
References DeleteTexture(), NUM_BUFFERS, and ReleaseBuffer().
CRendererVTB() [2/2]
CRendererVTB::CRendererVTB ()
~CRendererVTB() [2/2]
CRendererVTB::~CRendererVTB () override
Member Function Documentation
AfterRenderHook() [1/2]
void CRendererVTB::AfterRenderHook (int idx) override protected virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::m_buffers, VTB::CVideoBufferVTB::m_fence, and CLinuxRendererGL::CPictureBuffer::videoBuffer.
AfterRenderHook() [2/2]
void CRendererVTB::AfterRenderHook (int idx) override protected virtual
Reimplemented from CLinuxRendererGL.
Create() [1/2]
CBaseRenderer * CRendererVTB::Create (CVideoBuffer * buffer) static
References CRendererVTB().
Referenced by Register().
Create() [2/2]
static CBaseRenderer * CRendererVTB::Create (CVideoBuffer * buffer) static
CreateTexture() [1/2]
bool CRendererVTB::CreateTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
References YuvImage::bpp, YuvImage::cshift_x, YuvImage::cshift_y, DeleteTexture(), CLinuxRendererGL::CPictureBuffer::fields, YuvImage::height, CLinuxRendererGL::CPictureBuffer::image, index(), CLinuxRendererGL::m_buffers, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, YuvImage::MAX_PLANES, ReleaseBuffer(), and YuvImage::width.
CreateTexture() [2/2]
bool CRendererVTB::CreateTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
DeleteTexture() [1/2]
void CRendererVTB::DeleteTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::CPictureBuffer::fields, index(), CLinuxRendererGL::CPictureBuffer::loaded, CLinuxRendererGL::m_buffers, and YuvImage::MAX_PLANES.
Referenced by CreateTexture(), and ~CRendererVTB().
DeleteTexture() [2/2]
void CRendererVTB::DeleteTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
GetShaderFormat() [1/2]
EShaderFormat CRendererVTB::GetShaderFormat () override protected virtual
Reimplemented from CBaseRenderer.
References SHADER_NV12.
GetShaderFormat() [2/2]
EShaderFormat CRendererVTB::GetShaderFormat () override protected virtual
Reimplemented from CBaseRenderer.
LoadShadersHook() [1/2]
bool CRendererVTB::LoadShadersHook () override protected virtual
Reimplemented from CLinuxRendererGL.
References CLog::Log(), LOGINFO, and CLinuxRendererGL::m_textureTarget.
LoadShadersHook() [2/2]
bool CRendererVTB::LoadShadersHook () override protected virtual
Reimplemented from CLinuxRendererGL.
NeedBuffer() [1/2]
bool CRendererVTB::NeedBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References CLinuxRendererGL::m_buffers, VTB::CVideoBufferVTB::m_fence, and CLinuxRendererGL::CPictureBuffer::videoBuffer.
NeedBuffer() [2/2]
bool CRendererVTB::NeedBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
Register() [1/2]
bool CRendererVTB::Register () static
References Create(), and VIDEOPLAYER::CRendererFactory::RegisterRenderer().
Referenced by CWinSystemIOS::CreateNewWindow(), CWinSystemOSX::CreateNewWindow(), and CWinSystemTVOS::CreateNewWindow().
Register() [2/2]
static bool CRendererVTB::Register () static
ReleaseBuffer() [1/2]
void CRendererVTB::ReleaseBuffer (int idx) override virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::m_buffers, VTB::CVideoBufferVTB::m_fence, CVideoBuffer::Release(), and CLinuxRendererGL::CPictureBuffer::videoBuffer.
Referenced by CreateTexture(), and ~CRendererVTB().
ReleaseBuffer() [2/2]
void CRendererVTB::ReleaseBuffer (int idx) override virtual
Reimplemented from CLinuxRendererGL.
UploadTexture() [1/2]
bool CRendererVTB::UploadTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
References CLinuxRendererGL::CalculateTextureSourceRects(), CLinuxRendererGL::CPictureBuffer::fields, CWinSystemOSX::GetCGLContextObj(), VTB::CVideoBufferVTB::GetPB(), CServiceBroker::GetWinSystem(), index(), CLinuxRendererGL::m_buffers, CLinuxRendererGL::m_textureTarget, YuvImage::MAX_PLANES, and CLinuxRendererGL::CPictureBuffer::videoBuffer.
UploadTexture() [2/2]
bool CRendererVTB::UploadTexture (int index) override protected virtual
Reimplemented from CLinuxRendererGL.
Member Data Documentation
m_glContext
CVEAGLContext CRendererVTB::m_glContext protected
Referenced by CRendererVTB().
m_textureCache
CVOpenGLESTextureCacheRef CRendererVTB::m_textureCache = nullptr protected
Referenced by CRendererVTB().
m_vtbBuffers
CRenderBuffer CRendererVTB::m_vtbBuffers[NUM_BUFFERS] protected
Referenced by CRendererVTB().
The documentation for this class was generated from the following files:
RendererVTBGL.h
RendererVTBGLES.h
RendererVTBGL.cpp
RendererVTBGLES.cpp