Kodi Documentation: XbmcCommons::Exception Class Reference
XbmcCommons::Exception Class Reference
#include <Exception.h>
Public Member Functions
virtual ~Exception ()
virtual void LogThrowMessage (const char *prefix=NULL) const
virtual const char * GetExMessage () const
Protected Member Functions
Exception (const char *classname_)
Exception (const char *classname_, const char *message_)
Exception (const Exception &other)=default
void Set (const char *fmt, va_list &argList)
void SetMessage (const char *fmt,...) XBMCCOMMONS_ATTRIB_EXCEPTION_FORMAT
void setClassname (const char *cn)
Private Attributes
std::string classname
std::string message
Detailed Description
This class a superclass for exceptions that want to utilize some utility functionality including autologging with the specific exception name.
Constructor & Destructor Documentation
Exception() [1/3]
XbmcCommons::Exception::Exception (const char * classname_) inline explicit protected
Exception() [2/3]
XbmcCommons::Exception::Exception (const char * classname_, const char * message_) inline protected
Exception() [3/3]
XbmcCommons::Exception::Exception (const Exception & other) inline protected default
~Exception()
XbmcCommons::Exception::~Exception () virtual default
Member Function Documentation
GetExMessage()
virtual const char * XbmcCommons::Exception::GetExMessage () const inline virtual
References message.
LogThrowMessage()
void XbmcCommons::Exception::LogThrowMessage (const char * prefix = NULL) const virtual
References classname, CLog::Log(), LOGERROR, and message.
Referenced by CPythonInvoker::execute(), and XBMCAddon::RetardedAsyncCallbackHandler::makePendingCalls().
Set()
void XbmcCommons::Exception::Set (const char * fmt, va_list & argList) inline protected
This method is called from the constructor of subclasses. It will set the message from varargs as well as call log message
References message.
setClassname()
void XbmcCommons::Exception::setClassname (const char * cn) inline protected
References classname.
SetMessage()
void XbmcCommons::Exception::SetMessage (const char * fmt, ...) inline protected
This message can be called from the constructor of subclasses. It will set the message and log the throwing.
References XBMCCOMMONS_COPYVARARGS.
Referenced by XBMCAddon::UnimplementedException::UnimplementedException().
Member Data Documentation
classname
std::string XbmcCommons::Exception::classname private
Referenced by LogThrowMessage(), setClassname(), and XBMCAddon::UnimplementedException::UnimplementedException().
message
std::string XbmcCommons::Exception::message private
Referenced by GetExMessage(), LogThrowMessage(), and Set().
The documentation for this class was generated from the following files:
commons/Exception.h
Exception.cpp