Kodi Documentation: AESinkPULSE.cpp File Reference
AESinkPULSE.cpp File Reference
#include "AESinkPULSE.h"
#include "ServiceBroker.h"
#include "application/ApplicationComponents.h"
#include "application/ApplicationVolumeHandling.h"
#include "cores/AudioEngine/AESinkFactory.h"
#include "threads/SingleLock.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include <array>
#include <memory>
#include <mutex>
#include <pulse/context.h>
#include <pulse/introspect.h>
Classes
class CDriverMonitor
struct ServerInfoStruct
struct SinkInfoStruct
struct ModuleInfoStruct
Namespaces
namespace anonymous_namespace{AESinkPULSE.cpp}
Functions
static const char * ContextStateToString (pa_context_state s)
static const char * StreamStateToString (pa_stream_state s)
static pa_sample_format AEStreamFormatToPulseFormat (CAEStreamInfo::DataType type)
static pa_sample_format AEFormatToPulseFormat (AEDataFormat format)
static pa_encoding AEStreamFormatToPulseEncoding (CAEStreamInfo::DataType type)
static pa_encoding AEFormatToPulseEncoding (AEDataFormat format)
static void ContextStateCallback (pa_context *c, void *userdata)
static void StreamStateCallback (pa_stream *s, void *userdata)
static void StreamRequestCallback (pa_stream *s, size_t length, void *userdata)
static void StreamLatencyUpdateCallback (pa_stream *s, void *userdata)
static void SinkInputInfoCallback (pa_context *c, const pa_sink_input_info *i, int eol, void *userdata)
static void SinkCallback (pa_context *c, pa_subscription_event_type_t t, uint32_t idx, void *userdata)
static void SinkChangedCallback (pa_context *c, pa_subscription_event_type_t t, uint32_t idx, void *userdata)
static void ServerInfoCallback (pa_context *c, const pa_server_info *i, void *userdata)
static void SinkInfoCallback (pa_context *c, const pa_sink_info *i, int eol, void *userdata)
static AEChannel PAChannelToAEChannel (pa_channel_position_t channel)
static pa_channel_position_t AEChannelToPAChannel (AEChannel ae_channel)
static pa_channel_map AEChannelMapToPAChannel (const CAEChannelInfo &info)
static CAEChannelInfo PAChannelToAEChannelMap (const pa_channel_map &channels)
static void ModuleInfoCallback (pa_context *c, const pa_module_info *i, int eol, void *userdata)
static void SinkInfoRequestCallback (pa_context *c, const pa_sink_info *i, int eol, void *userdata)
static bool SetupContext (const char *host, const char *appname, pa_context **context, pa_threaded_mainloop **mainloop)
Variables
constexpr std::array< AEDataFormat, 6 > anonymous_namespace{AESinkPULSE.cpp}::defaultDataFormats
constexpr std::array< unsigned int, 14 > anonymous_namespace{AESinkPULSE.cpp}::defaultSampleRates
Function Documentation
AEChannelMapToPAChannel()
static pa_channel_map AEChannelMapToPAChannel (const CAEChannelInfo & info) static
References AEChannelToPAChannel().
Referenced by CAESinkPULSE::Initialize().
AEChannelToPAChannel()
static pa_channel_position_t AEChannelToPAChannel (AEChannel ae_channel) static
References AE_CH_BC, AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_CH_TBC, AE_CH_TBL, AE_CH_TBR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, and AE_CH_TFR.
Referenced by AEChannelMapToPAChannel().
AEFormatToPulseEncoding()
static pa_encoding AEFormatToPulseEncoding (AEDataFormat format) static
References AE_FMT_RAW.
Referenced by CAESinkPULSE::Initialize().
AEFormatToPulseFormat()
static pa_sample_format AEFormatToPulseFormat (AEDataFormat format) static
References AE_FMT_FLOAT, AE_FMT_S16NE, AE_FMT_S24NE3, AE_FMT_S24NE4, AE_FMT_S32NE, and AE_FMT_U8.
Referenced by CAESinkPULSE::Initialize().
AEStreamFormatToPulseEncoding()
static pa_encoding AEStreamFormatToPulseEncoding (CAEStreamInfo::DataType type) static
References CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, and CAEStreamInfo::STREAM_TYPE_EAC3.
Referenced by CAESinkPULSE::Initialize().
AEStreamFormatToPulseFormat()
static pa_sample_format AEStreamFormatToPulseFormat (CAEStreamInfo::DataType type) static
References CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, and CAEStreamInfo::STREAM_TYPE_EAC3.
Referenced by CAESinkPULSE::Initialize().
ContextStateCallback()
static void ContextStateCallback (pa_context * c, void * userdata) static
Referenced by SetupContext().
ContextStateToString()
static const char * ContextStateToString (pa_context_state s) static
Referenced by SetupContext().
ModuleInfoCallback()
static void ModuleInfoCallback (pa_context * c, const pa_module_info * i, int eol, void * userdata) static
References ModuleInfoStruct::hasAllowPT, and ModuleInfoStruct::mainloop.
Referenced by CAESinkPULSE::EnumerateDevicesEx().
PAChannelToAEChannel()
static AEChannel PAChannelToAEChannel (pa_channel_position_t channel) static
References AE_CH_BC, AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_NULL, AE_CH_SL, AE_CH_SR, AE_CH_TBC, AE_CH_TBL, AE_CH_TBR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, and AE_CH_TFR.
Referenced by PAChannelToAEChannelMap().
PAChannelToAEChannelMap()
static CAEChannelInfo PAChannelToAEChannelMap (const pa_channel_map & channels) static
References AE_CH_NULL, PAChannelToAEChannel(), and CAEChannelInfo::Reset().
Referenced by CAESinkPULSE::Initialize(), and SinkInfoRequestCallback().
ServerInfoCallback()
static void ServerInfoCallback (pa_context * c, const pa_server_info * i, void * userdata) static
References ServerInfoStruct::m_serverName.
Referenced by CDriverMonitor::Start().
SetupContext()
static bool SetupContext (const char * host, const char * appname, pa_context ** context, pa_threaded_mainloop ** mainloop) static
References ContextStateCallback(), ContextStateToString(), CLog::Log(), LOGDEBUG, and LOGERROR.
Referenced by CAESinkPULSE::EnumerateDevicesEx(), CAESinkPULSE::Initialize(), and CDriverMonitor::Start().
SinkCallback()
static void SinkCallback (pa_context * c, pa_subscription_event_type_t t, uint32_t idx, void * userdata) static
References IAE::DeviceCountChange(), CServiceBroker::GetActiveAE(), CDriverMonitor::IsInitialized(), CLog::Log(), LOGDEBUG, CDriverMonitor::m_sec, and t.
Referenced by CDriverMonitor::Start().
SinkChangedCallback()
static void SinkChangedCallback (pa_context * c, pa_subscription_event_type_t t, uint32_t idx, void * userdata) static
References CAESinkPULSE::GetInternalStream(), CAESinkPULSE::IsInitialized(), CLog::Log(), LOGDEBUG, LOGERROR, CAESinkPULSE::m_sec, SinkInputInfoCallback(), and t.
Referenced by CAESinkPULSE::Initialize().
SinkInfoCallback()
static void SinkInfoCallback (pa_context * c, const pa_sink_info * i, int eol, void * userdata) static
References SinkInfoStruct::device_found, KODI::UTILS::StringUtils::EndsWithNoCase(), SinkInfoStruct::isBTDevice, SinkInfoStruct::isHWDevice, SinkInfoStruct::isNWDevice, CLog::Log(), LOGINFO, SinkInfoStruct::mainloop, SinkInfoStruct::map, and SinkInfoStruct::samplerate.
Referenced by CAESinkPULSE::Initialize().
SinkInfoRequestCallback()
static void SinkInfoRequestCallback (pa_context * c, const pa_sink_info * i, int eol, void * userdata) static
References AE_CH_LAYOUT_2_0, AE_DEVTYPE_IEC958, AE_DEVTYPE_PCM, AE_FMT_RAW, CAEChannelInfo::Count(), anonymous_namespace{AESinkPULSE.cpp}::defaultDataFormats, anonymous_namespace{AESinkPULSE.cpp}::defaultSampleRates, SinkInfoStruct::list, CLog::Log(), LOGDEBUG, CAEDeviceInfo::m_channels, CAEDeviceInfo::m_dataFormats, CAEDeviceInfo::m_deviceName, CAEDeviceInfo::m_deviceType, CAEDeviceInfo::m_displayName, CAEDeviceInfo::m_displayNameExtra, CAEDeviceInfo::m_sampleRates, CAEDeviceInfo::m_streamTypes, CAEDeviceInfo::m_wantsIECPassthrough, SinkInfoStruct::mainloop, PAChannelToAEChannelMap(), CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, and CAEStreamInfo::STREAM_TYPE_EAC3.
Referenced by CAESinkPULSE::EnumerateDevicesEx().
SinkInputInfoCallback()
static void SinkInputInfoCallback (pa_context * c, const pa_sink_input_info * i, int eol, void * userdata) static
References CAESinkPULSE::IsInitialized(), and CAESinkPULSE::UpdateInternalVolume().
Referenced by SinkChangedCallback().
StreamLatencyUpdateCallback()
static void StreamLatencyUpdateCallback (pa_stream * s, void * userdata) static
Referenced by CAESinkPULSE::Initialize().
StreamRequestCallback()
static void StreamRequestCallback (pa_stream * s, size_t length, void * userdata) static
References CAESinkPULSE::GetInternalMainLoop(), and CAESinkPULSE::m_requestedBytes.
Referenced by CAESinkPULSE::Initialize().
StreamStateCallback()
static void StreamStateCallback (pa_stream * s, void * userdata) static
Referenced by CAESinkPULSE::Initialize().
StreamStateToString()
static const char * StreamStateToString (pa_stream_state s) static
Referenced by CAESinkPULSE::Initialize().