Kodi Documentation: PlayerBuiltins.cpp File Reference
PlayerBuiltins.cpp File Reference
#include "PlayerBuiltins.h"
#include "FileItem.h"
#include "FileItemList.h"
#include "GUIPassword.h"
#include "GUIUserMessages.h"
#include "PartyModeManager.h"
#include "PlayListPlayer.h"
#include "SeekHandler.h"
#include "ServiceBroker.h"
#include "Util.h"
#include "application/Application.h"
#include "application/ApplicationPlayer.h"
#include "application/ApplicationPowerHandling.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "input/actions/Action.h"
#include "input/actions/ActionIDs.h"
#include "music/MusicFileItemClassify.h"
#include "music/MusicUtils.h"
#include "playlists/PlayList.h"
#include "playlists/PlayListFileItemClassify.h"
#include "pvr/PVRManager.h"
#include "pvr/channels/PVRChannel.h"
#include "pvr/guilib/PVRGUIActionsChannels.h"
#include "pvr/recordings/PVRRecording.h"
#include "settings/MediaSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "storage/MediaManager.h"
#include "utils/PlayerUtils.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/log.h"
#include "video/PlayerController.h"
#include "video/VideoFileItemClassify.h"
#include "video/VideoUtils.h"
#include "video/guilib/VideoGUIUtils.h"
#include "video/guilib/VideoSelectActionProcessor.h"
#include <math.h>
Namespaces
namespace anonymous_namespace{PlayerBuiltins.cpp}
Functions
static int ClearPlaylist (const std::vector< std::string > &params)
Clear current playlist.
static int PlayOffset (const std::vector< std::string > &params)
Start a playlist from a given offset.
static int PlayerControl (const std::vector< std::string > &params)
Control player.
static int PlayDVD (const std::vector< std::string > &params)
Play currently inserted DVD.
void anonymous_namespace{PlayerBuiltins.cpp}::GetItemsForPlayList (const std::shared_ptr< CFileItem > &item, CFileItemList &queuedItems)
PLAYLIST::Id anonymous_namespace{PlayerBuiltins.cpp}::GetPlayListId (const CFileItem &item)
int anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia (const std::vector< std::string > &params, bool forcePlay)
int anonymous_namespace{PlayerBuiltins.cpp}::PlayMedia (const std::vector< std::string > &params)
Start playback of media.
int anonymous_namespace{PlayerBuiltins.cpp}::QueueMedia (const std::vector< std::string > &params)
Queue media in the video or music playlist, according to type of media items. If both audio and video items are contained, queue to video playlist. Start playback at requested position if player is not playing.
static int PlayWith (const std::vector< std::string > &params)
Start playback with a given playback core.
static int Seek (const std::vector< std::string > &params)
Seek in currently playing media.
static int SubtitleShiftUp (const std::vector< std::string > &params)
static int SubtitleShiftDown (const std::vector< std::string > &params)
Function Documentation
ClearPlaylist()
static int ClearPlaylist (const std::vector< std::string > & params) static
Clear current playlist.
Parameters
params (ignored)
References KODI::PLAYLIST::CPlayListPlayer::Clear(), and CServiceBroker::GetPlaylistPlayer().
Referenced by CPlayerBuiltins::GetOperations(), and KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage().
PlayDVD()
static int PlayDVD (const std::vector< std::string > & params) static
Play currently inserted DVD.
Parameters
params The parameters.
params[0] = "restart" to restart from resume point (optional).
References KODI::UTILS::StringUtils::EqualsNoCase(), CServiceBroker::GetMediaManager(), and restart().
Referenced by CPlayerBuiltins::GetOperations().
PlayerControl()
static int PlayerControl (const std::vector< std::string > & params) static
Control player.
Parameters
params The parameters
params[0] = Control to execute. params[1] = "notify" to notify user (optional, certain controls).
References ACTION_NEXT_ITEM, ACTION_PLAYER_RESET, ACTION_PREV_ITEM, ACTION_SHOW_VIDEOMENU, CPlayerUtils::AdvanceTempoStep(), DECREASE, CPartyModeManager::Disable(), CPartyModeManager::Enable(), KODI::UTILS::StringUtils::EndsWithNoCase(), KODI::UTILS::StringUtils::EqualsNoCase(), g_application, g_partyModeManager, PVR::CPVRManager::Get(), CServiceBroker::GetAppComponents(), KODI::PLAYLIST::CPlayListPlayer::GetCurrentPlaylist(), CServiceBroker::GetGUI(), CMediaSettings::GetInstance(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetPVRManager(), CFileItem::GetPVRRecordingInfoTag(), KODI::PLAYLIST::CPlayListPlayer::GetRepeat(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYLISTPLAYER_RANDOM, GUI_MSG_PLAYLISTPLAYER_REPEAT, CFileItem::HasPVRRecordingInfoTag(), INCREASE, CPartyModeManager::IsEnabled(), KODI::PLAYLIST::CPlayListPlayer::IsShuffled(), CLog::Log(), LOGERROR, PARTYMODECONTEXT_MUSIC, PARTYMODECONTEXT_UNKNOWN, PARTYMODECONTEXT_VIDEO, CApplicationPowerHandling::ResetScreenSaver(), CMediaSettings::SetMusicPlaylistRepeat(), CMediaSettings::SetMusicPlaylistShuffled(), CApplicationPlayer::SetPlaySpeed(), KODI::PLAYLIST::CPlayListPlayer::SetRepeat(), KODI::PLAYLIST::CPlayListPlayer::SetShuffle(), CMediaSettings::SetVideoPlaylistRepeat(), CMediaSettings::SetVideoPlaylistShuffled(), KODI::UTILS::StringUtils::StartsWithNoCase(), KODI::UTILS::StringUtils::ToLower(), and KODI::UTILS::StringUtils::TrimRight().
Referenced by CPlayerBuiltins::GetOperations().
PlayOffset()
static int PlayOffset (const std::vector< std::string > & params) static
Start a playlist from a given offset.
Parameters
params The parameters.
params[0] = Position in playlist or playlist type. params[1] = Position in playlist if params[0] is playlist type (optional).
References g_application, CServiceBroker::GetAppComponents(), CServiceBroker::GetPlaylistPlayer(), CLog::Log(), LOGERROR, KODI::PLAYLIST::CPlayListPlayer::Play(), KODI::PLAYLIST::CPlayListPlayer::PlayNext(), KODI::PLAYLIST::CPlayListPlayer::Reset(), KODI::PLAYLIST::CPlayListPlayer::SetCurrentPlaylist(), and KODI::UTILS::StringUtils::ToLower().
Referenced by CPlayerBuiltins::GetOperations().
PlayWith()
static int PlayWith (const std::vector< std::string > & params) static
Start playback with a given playback core.
Parameters
params The parameters.
params[0] = Name of playback core.
References ACTION_PLAYER_PLAY, and g_application.
Referenced by CPlayerBuiltins::GetOperations().
Seek()
static int Seek (const std::vector< std::string > & params) static
Seek in currently playing media.
Parameters
params The parameters.
params[0] = Number of seconds to seek.
References CServiceBroker::GetAppComponents(), CApplicationPlayer::GetSeekHandler(), and CSeekHandler::SeekSeconds().
Referenced by kodi::addon::CInstanceVFS::ADDON_Seek(), kodi::addon::CInstanceAudioDecoder::ADDON_seek(), CBlurayCallback::file_seek(), CPlayerBuiltins::GetOperations(), and ADDON::Interface_Filesystem::seek_file().
SubtitleShiftDown()
static int SubtitleShiftDown (const std::vector< std::string > & params) static
References ACTION_SUBTITLE_VSHIFT_DOWN, CPlayerController::GetInstance(), and CPlayerController::OnAction().
Referenced by CPlayerBuiltins::GetOperations().
SubtitleShiftUp()
static int SubtitleShiftUp (const std::vector< std::string > & params) static
References ACTION_SUBTITLE_VSHIFT_UP, CPlayerController::GetInstance(), and CPlayerController::OnAction().
Referenced by CPlayerBuiltins::GetOperations().