Kodi Documentation: CRecentlyAddedJob Class Reference
CRecentlyAddedJob Class Reference
#include <RecentlyAddedJob.h>
Public Member Functions
CRecentlyAddedJob (int flag)
bool DoWork () override
Main workhorse function of CJob instances.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual const char * GetType () const
Function that returns the type of job.
virtual bool operator== (const CJob *job) const
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Static Public Member Functions
static bool UpdateVideo ()
static bool UpdateMusic ()
static bool UpdateTotal ()
Private Attributes
int m_flag
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Constructor & Destructor Documentation
CRecentlyAddedJob()
CRecentlyAddedJob::CRecentlyAddedJob (int flag) explicit
References m_flag.
Member Function Documentation
DoWork()
bool CRecentlyAddedJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References Audio, m_flag, Totals, UpdateMusic(), UpdateTotal(), UpdateVideo(), and Video.
UpdateMusic()
bool CRecentlyAddedJob::UpdateMusic () static
References CDatabase::Close(), CFileItemList::Get(), CMusicDatabase::GetArtForItem(), CServiceBroker::GetGUI(), CMusicDatabase::GetRecentlyAddedAlbums(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), CGUIComponent::GetWindowManager(), CMusicThumbLoader::LoadItem(), CLog::Log(), LOGDEBUG, MediaTypeAlbum, MediaTypeArtist, NUM_ITEMS, CMusicThumbLoader::OnLoaderStart(), CMusicDatabase::Open(), CFileItemList::Size(), value, and WINDOW_HOME.
Referenced by DoWork().
UpdateTotal()
bool CRecentlyAddedJob::UpdateTotal () static
References CDbUrl::AddOption(), CDatabase::Close(), CDbUrl::FromString(), CFileItemList::Get(), CMusicDatabase::GetArtistsByWhere(), CServiceBroker::GetGUI(), CServiceBroker::GetSettingsComponent(), CDatabase::GetSingleValue(), CGUIComponent::GetWindowManager(), CLog::Log(), LOGDEBUG, CMusicDatabase::Open(), CVideoDatabase::Open(), CSettings::SETTING_MUSICLIBRARY_SHOWCOMPILATIONARTISTS, CFileItemList::Size(), CDbUrl::ToString(), and WINDOW_HOME.
Referenced by DoWork().
UpdateVideo()
bool CRecentlyAddedJob::UpdateVideo () static
References CDatabase::Close(), CFileItemList::Get(), CVideoDatabase::GetArtForItem(), CServiceBroker::GetGUI(), CTVOSTopShelf::GetInstance(), CVideoDatabase::GetRecentlyAddedEpisodesNav(), CVideoDatabase::GetRecentlyAddedMoviesNav(), CVideoDatabase::GetRecentlyAddedMusicVideosNav(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CVideoThumbLoader::LoadItem(), CLog::Log(), LOGDEBUG, MediaTypeSeason, MOVIES, NUM_ITEMS, CVideoThumbLoader::OnLoaderStart(), CVideoDatabase::Open(), CTVOSTopShelf::SetTopShelfItems(), CFileItemList::Size(), TV_SHOWS, value, and WINDOW_HOME.
Referenced by DoWork().
Member Data Documentation
m_flag
int CRecentlyAddedJob::m_flag private
Referenced by CRecentlyAddedJob(), and DoWork().
The documentation for this class was generated from the following files:
RecentlyAddedJob.h
RecentlyAddedJob.cpp