Kodi Documentation: CONTEXTMENU::CVideoPlayAndQueue Struct Reference
CONTEXTMENU::CVideoPlayAndQueue Struct Reference
#include <ContextMenus.h>
Public Member Functions
std::string GetLabel (const CFileItem &item) const override
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool IsGroup () const
virtual bool HasParent () const
Member Function Documentation
Execute()
bool CONTEXTMENU::CVideoPlayAndQueue::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Todo:
implement
Implements IContextMenuItem.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), KODI::VIDEO::UTILS::IsAutoPlayNextItem(), ContentUtils::PLAY_FROM_HERE, ContentUtils::PLAY_ONLY_THIS, KODI::VIDEO::UTILS::PlayItem(), WINDOW_RADIO_RECORDINGS, and WINDOW_TV_RECORDINGS.
GetLabel()
std::string CONTEXTMENU::CVideoPlayAndQueue::GetLabel (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References g_localizeStrings, CLocalizeStrings::Get(), and KODI::VIDEO::UTILS::IsAutoPlayNextItem().
IsVisible()
bool CONTEXTMENU::CVideoPlayAndQueue::IsVisible (const CFileItem & item) const override virtual
Todo:
implement
Implements IContextMenuItem.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CFileItem::IsUsablePVRRecording(), WINDOW_RADIO_RECORDINGS, and WINDOW_TV_RECORDINGS.
The documentation for this struct was generated from the following files:
video/ContextMenus.h
video/ContextMenus.cpp