Kodi Documentation: CAESinkPULSE Class Reference
CAESinkPULSE Class Reference
#include <AESinkPULSE.h>
Public Member Functions
const char * GetName () override
CAESinkPULSE ()
~CAESinkPULSE () override
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
virtual double GetDelay ()
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
double GetCacheTotal () override
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void Drain () override
bool HasVolume () override
void SetVolume (float volume) override
bool IsInitialized ()
void UpdateInternalVolume (const pa_cvolume *nVol)
pa_stream * GetInternalStream ()
pa_threaded_mainloop * GetInternalMainLoop ()
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual double GetLatency ()
virtual void AddPause (unsigned int millis)
instruct the sink to add a pause
Static Public Member Functions
static bool Register (bool allowPipeWireCompatServer)
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
static void EnumerateDevicesEx (AEDeviceInfoList &list, bool force=false)
static void Cleanup ()
Public Attributes
CCriticalSection m_sec
std::atomic< int > m_requestedBytes = 0
Private Member Functions
void Pause (bool pause)
Static Private Member Functions
static bool WaitForOperation (pa_operation *op, pa_threaded_mainloop *mainloop, const char *LogEntry)
Private Attributes
bool m_IsAllocated
bool m_passthrough
bool m_IsStreamPaused
AEAudioFormat m_format
unsigned int m_BytesPerSecond
unsigned int m_BufferSize
unsigned int m_Channels
double m_maxLatency
pa_stream * m_Stream
pa_cvolume m_Volume
bool m_volume_needs_update
uint32_t m_periodSize
pa_context * m_Context
pa_threaded_mainloop * m_MainLoop
Static Private Attributes
static std::unique_ptr< CDriverMonitor > m_pMonitor
Constructor & Destructor Documentation
CAESinkPULSE()
CAESinkPULSE::CAESinkPULSE ()
References m_BufferSize, m_BytesPerSecond, m_Channels, m_Context, m_IsAllocated, m_IsStreamPaused, m_MainLoop, m_maxLatency, m_passthrough, m_periodSize, m_Stream, m_Volume, and m_volume_needs_update.
~CAESinkPULSE()
CAESinkPULSE::~CAESinkPULSE () override
References Deinitialize().
Member Function Documentation
AddPackets()
unsigned int CAESinkPULSE::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References data(), CLog::Log(), LOGERROR, m_BufferSize, m_BytesPerSecond, m_format, AEAudioFormat::m_frameSize, m_IsAllocated, m_IsStreamPaused, m_MainLoop, m_periodSize, m_requestedBytes, m_Stream, and Pause().
Cleanup()
void CAESinkPULSE::Cleanup () static
References m_pMonitor.
Referenced by Register().
Create()
std::unique_ptr< IAESink > CAESinkPULSE::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
Deinitialize()
void CAESinkPULSE::Deinitialize () override virtual
Implements IAESink.
References m_Context, m_IsAllocated, m_IsStreamPaused, m_MainLoop, m_maxLatency, m_passthrough, m_periodSize, m_requestedBytes, m_sec, m_Stream, and WaitForOperation().
Referenced by Initialize(), and ~CAESinkPULSE().
Drain()
void CAESinkPULSE::Drain () override virtual
Reimplemented from IAESink.
References m_IsAllocated, m_IsStreamPaused, m_MainLoop, m_Stream, and WaitForOperation().
EnumerateDevicesEx()
void CAESinkPULSE::EnumerateDevicesEx (AEDeviceInfoList & list, bool force = false) static
References ModuleInfoStruct::hasAllowPT, SinkInfoStruct::list, CLog::Log(), LOGINFO, LOGWARNING, SinkInfoStruct::mainloop, ModuleInfoStruct::mainloop, ModuleInfoCallback(), SetupContext(), SinkInfoRequestCallback(), and WaitForOperation().
Referenced by Register().
GetCacheTotal()
double CAESinkPULSE::GetCacheTotal () override virtual
Implements IAESink.
References m_maxLatency.
GetDelay() [1/2]
virtual double CAESinkPULSE::GetDelay () inline virtual
GetDelay() [2/2]
void CAESinkPULSE::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References m_IsAllocated, m_MainLoop, m_maxLatency, m_Stream, and AEDelayStatus::SetDelay().
GetInternalMainLoop()
pa_threaded_mainloop * CAESinkPULSE::GetInternalMainLoop ()
References m_MainLoop.
Referenced by StreamRequestCallback().
GetInternalStream()
pa_stream * CAESinkPULSE::GetInternalStream ()
References m_Stream.
Referenced by SinkChangedCallback().
GetName()
const char * CAESinkPULSE::GetName () inline override virtual
Implements IAESink.
HasVolume()
bool CAESinkPULSE::HasVolume () inline override virtual
Reimplemented from IAESink.
Initialize()
bool CAESinkPULSE::Initialize (AEAudioFormat & format, std::string & device) override virtual
Implements IAESink.
References AE_CH_LAYOUT_2_0, AE_FMT_FLOAT, AE_FMT_RAW, AE_FMT_S16NE, AEChannelMapToPAChannel(), AEFormatToPulseEncoding(), AEFormatToPulseFormat(), AEStreamFormatToPulseEncoding(), AEStreamFormatToPulseFormat(), CAEUtil::DataFormatToStr(), Deinitialize(), SinkInfoStruct::device_found, SinkInfoStruct::isBTDevice, SinkInfoStruct::isHWDevice, SinkInfoStruct::isNWDevice, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_BufferSize, m_BytesPerSecond, m_Channels, m_Context, AEAudioFormat::m_dataFormat, m_format, m_IsAllocated, m_MainLoop, m_maxLatency, m_passthrough, m_periodSize, m_sec, m_Stream, SinkInfoStruct::mainloop, PAChannelToAEChannelMap(), Pause(), SetupContext(), SinkChangedCallback(), SinkInfoCallback(), StreamLatencyUpdateCallback(), StreamRequestCallback(), StreamStateCallback(), StreamStateToString(), and WaitForOperation().
IsInitialized()
bool CAESinkPULSE::IsInitialized ()
References m_IsAllocated, and m_sec.
Referenced by SinkChangedCallback(), and SinkInputInfoCallback().
Pause()
void CAESinkPULSE::Pause (bool pause) private
References m_IsStreamPaused, m_MainLoop, m_Stream, and WaitForOperation().
Referenced by AddPackets(), and Initialize().
Register()
bool CAESinkPULSE::Register (bool allowPipeWireCompatServer) static
References Cleanup(), AE::AESinkRegEntry::cleanupFunc, Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, CLog::Log(), LOGINFO, m_pMonitor, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
SetVolume()
void CAESinkPULSE::SetVolume (float volume) override virtual
Reimplemented from IAESink.
References CServiceBroker::GetAppComponents(), CLog::Log(), LOGERROR, m_Channels, m_Context, m_IsAllocated, m_MainLoop, m_passthrough, m_Stream, m_Volume, m_volume_needs_update, and CApplicationVolumeHandling::SetVolume().
UpdateInternalVolume()
void CAESinkPULSE::UpdateInternalVolume (const pa_cvolume * nVol)
References m_Channels, m_Volume, and m_volume_needs_update.
Referenced by SinkInputInfoCallback().
WaitForOperation()
bool CAESinkPULSE::WaitForOperation (pa_operation * op, pa_threaded_mainloop * mainloop, const char * LogEntry = "") inline static private
References CLog::Log(), LOGERROR, and success.
Referenced by Deinitialize(), Drain(), EnumerateDevicesEx(), Initialize(), and Pause().
Member Data Documentation
m_BufferSize
unsigned int CAESinkPULSE::m_BufferSize private
Referenced by AddPackets(), CAESinkPULSE(), and Initialize().
m_BytesPerSecond
unsigned int CAESinkPULSE::m_BytesPerSecond private
Referenced by AddPackets(), CAESinkPULSE(), and Initialize().
m_Channels
unsigned int CAESinkPULSE::m_Channels private
Referenced by CAESinkPULSE(), Initialize(), SetVolume(), and UpdateInternalVolume().
m_Context
pa_context* CAESinkPULSE::m_Context private
Referenced by CAESinkPULSE(), Deinitialize(), Initialize(), and SetVolume().
m_format
AEAudioFormat CAESinkPULSE::m_format private
Referenced by AddPackets(), and Initialize().
m_IsAllocated
bool CAESinkPULSE::m_IsAllocated private
Referenced by AddPackets(), CAESinkPULSE(), Deinitialize(), Drain(), GetDelay(), Initialize(), IsInitialized(), and SetVolume().
m_IsStreamPaused
bool CAESinkPULSE::m_IsStreamPaused private
Referenced by AddPackets(), CAESinkPULSE(), Deinitialize(), Drain(), and Pause().
m_MainLoop
pa_threaded_mainloop* CAESinkPULSE::m_MainLoop private
Referenced by AddPackets(), CAESinkPULSE(), Deinitialize(), Drain(), GetDelay(), GetInternalMainLoop(), Initialize(), Pause(), and SetVolume().
m_maxLatency
double CAESinkPULSE::m_maxLatency private
Referenced by CAESinkPULSE(), Deinitialize(), GetCacheTotal(), GetDelay(), and Initialize().
m_passthrough
bool CAESinkPULSE::m_passthrough private
Referenced by CAESinkPULSE(), Deinitialize(), Initialize(), and SetVolume().
m_periodSize
uint32_t CAESinkPULSE::m_periodSize private
Referenced by AddPackets(), CAESinkPULSE(), Deinitialize(), and Initialize().
m_pMonitor
std::unique_ptr< CDriverMonitor > CAESinkPULSE::m_pMonitor static private
Referenced by Cleanup(), and Register().
m_requestedBytes
std::atomic<int> CAESinkPULSE::m_requestedBytes = 0
Referenced by AddPackets(), Deinitialize(), and StreamRequestCallback().
m_sec
CCriticalSection CAESinkPULSE::m_sec
Referenced by Deinitialize(), Initialize(), IsInitialized(), and SinkChangedCallback().
m_Stream
pa_stream* CAESinkPULSE::m_Stream private
Referenced by AddPackets(), CAESinkPULSE(), Deinitialize(), Drain(), GetDelay(), GetInternalStream(), Initialize(), Pause(), and SetVolume().
m_Volume
pa_cvolume CAESinkPULSE::m_Volume private
Referenced by CAESinkPULSE(), SetVolume(), and UpdateInternalVolume().
m_volume_needs_update
bool CAESinkPULSE::m_volume_needs_update private
Referenced by CAESinkPULSE(), SetVolume(), and UpdateInternalVolume().
The documentation for this class was generated from the following files:
AESinkPULSE.h
AESinkPULSE.cpp