Kodi Documentation: TestFileFactory Class Reference
TestFileFactory Class Reference
Protected Member Functions
TestFileFactory ()
~TestFileFactory () override
Constructor & Destructor Documentation
TestFileFactory()
TestFileFactory::TestFileFactory () inline protected
References CXBMCTestUtils::getAdvancedSettingsFiles(), CXBMCTestUtils::getGUISettingsFiles(), CServiceBroker::GetSettingsComponent(), and CXBMCTestUtils::Instance().
~TestFileFactory()
TestFileFactory::~TestFileFactory () inline override protected
References CServiceBroker::GetSettingsComponent().
The documentation for this class was generated from the following file:
TestFileFactory.cpp