Kodi Documentation: CSkinTimer Class Reference
CSkinTimer Class Reference
Skin timers are skin objects that dependent on time and can be fully controlled from skins either using boolean conditions or builtin functions. This class represents the Skin Timer object.
#include <SkinTimer.h>
Public Member Functions
CSkinTimer (const std::string &name, const INFO::InfoPtr &startCondition, const INFO::InfoPtr &resetCondition, const INFO::InfoPtr &stopCondition, const CGUIAction &startActions, const CGUIAction &stopActions, bool resetOnStart)
Skin timer constructor.
virtual ~CSkinTimer ()=default
Default skin timer destructor.
void Start ()
Start the skin timer.
void Reset ()
Resets the skin timer so that the elapsed time of the timer is 0.
void Stop ()
stops the skin timer
const std::string & GetName () const
Getter for the timer name.
INFO::InfoPtr GetStartCondition () const
Getter for the timer start boolean condition/expression.
INFO::InfoPtr GetResetCondition () const
Getter for the timer reset boolean condition/expression.
INFO::InfoPtr GetStopCondition () const
Getter for the timer start boolean condition/expression.
bool ResetsOnStart () const
Checks if a given timer is configured to reset every time it starts.
const CGUIAction & GetStartActions () const
Gets the start actions of this skin timer.
const CGUIAction & GetStopActions () const
Gets the stop actions of this skin timer.
bool VerifyStartCondition () const
Evaluates the timer start boolean info expression returning the respective result.
bool VerifyResetCondition () const
Evaluates the timer reset boolean info expression returning the respective result.
bool VerifyStopCondition () const
Evaluates the timer stop boolean info expression returning the respective result.
Public Member Functions inherited from CStopWatch
CStopWatch ()=default
~CStopWatch ()=default
bool IsRunning () const
Retrieve the running state of the stopwatch.
void StartZero ()
Record start time and change state to running.
void Start ()
Record start time and change state to running, only if the stopwatch is stopped.
void Stop ()
Record stop time and change state to not running.
void Reset ()
Set the start time such that time elapsed is now zero.
float GetElapsedSeconds () const
Retrieve time elapsed between the last call to Start(), StartZero() or Reset() and; if running, now; if stopped, the last call to Stop().
float GetElapsedMilliseconds () const
Retrieve time elapsed between the last call to Start(), StartZero() or Reset() and; if running, now; if stopped, the last call to Stop().
Private Member Functions
void OnStart ()
Called when this timer is started.
void OnStop ()
Called when this timer is stopped.
Private Attributes
std::string m_name
INFO::InfoPtr m_startCondition
INFO::InfoPtr m_resetCondition
INFO::InfoPtr m_stopCondition
CGUIAction m_startActions
CGUIAction m_stopActions
bool m_resetOnStart {false}
Detailed Description
Skin timers are skin objects that dependent on time and can be fully controlled from skins either using boolean conditions or builtin functions. This class represents the Skin Timer object.
See also
Skin_Timers
Constructor & Destructor Documentation
CSkinTimer()
CSkinTimer::CSkinTimer (const std::string & name, const INFO::InfoPtr & startCondition, const INFO::InfoPtr & resetCondition, const INFO::InfoPtr & stopCondition, const CGUIAction & startActions, const CGUIAction & stopActions, bool resetOnStart)
Skin timer constructor.
Parameters
name - the name of the timer
startCondition - the boolean info expression to start the timer (may be null)
resetCondition - the boolean info expression to reset the timer (may be null)
stopCondition - the boolean info expression to stop the timer (may be null)
startActions - the builtin functions to execute on timer start (actions may be empty)
stopActions - the builtin functions to execute on timer stop (actions may be empty)
resetOnStart - if the timer should be reset when started (i.e. start from zero if true or resumed if false)
~CSkinTimer()
virtual CSkinTimer::~CSkinTimer () virtual default
Default skin timer destructor.
Member Function Documentation
GetName()
const std::string & CSkinTimer::GetName () const
Getter for the timer name.
Returns
the timer name
References m_name.
GetResetCondition()
INFO::InfoPtr CSkinTimer::GetResetCondition () const
Getter for the timer reset boolean condition/expression.
Returns
the reset boolean condition/expression (may be null)
References m_resetCondition.
GetStartActions()
const CGUIAction & CSkinTimer::GetStartActions () const
Gets the start actions of this skin timer.
Returns
the actions configured to start when the timer is started
References m_startActions.
GetStartCondition()
INFO::InfoPtr CSkinTimer::GetStartCondition () const
Getter for the timer start boolean condition/expression.
Returns
the start boolean condition/expression (may be null)
References m_startCondition.
GetStopActions()
const CGUIAction & CSkinTimer::GetStopActions () const
Gets the stop actions of this skin timer.
Returns
the actions configured to start when the timer is stopped
References m_stopActions.
GetStopCondition()
INFO::InfoPtr CSkinTimer::GetStopCondition () const
Getter for the timer start boolean condition/expression.
Returns
the start boolean condition/expression (may be null)
References m_stopCondition.
OnStart()
void CSkinTimer::OnStart () private
Called when this timer is started.
References CGUIAction::ExecuteActions(), CGUIAction::HasAnyActions(), and m_startActions.
Referenced by Start().
OnStop()
void CSkinTimer::OnStop () private
Called when this timer is stopped.
References CGUIAction::ExecuteActions(), CGUIAction::HasAnyActions(), and m_stopActions.
Referenced by Stop().
Reset()
void CSkinTimer::Reset ()
Resets the skin timer so that the elapsed time of the timer is 0.
References CStopWatch::Reset().
ResetsOnStart()
bool CSkinTimer::ResetsOnStart () const
Checks if a given timer is configured to reset every time it starts.
Returns
true if the timer is configured to reset on start, false otherwise
References m_resetOnStart.
Start()
void CSkinTimer::Start ()
Start the skin timer.
References m_resetOnStart, OnStart(), CStopWatch::Start(), and CStopWatch::StartZero().
Stop()
void CSkinTimer::Stop ()
stops the skin timer
References OnStop(), and CStopWatch::Stop().
VerifyResetCondition()
bool CSkinTimer::VerifyResetCondition () const
Evaluates the timer reset boolean info expression returning the respective result.
Called from the skin timer manager to check if the timer should be reset to 0
Returns
true if the condition is true, false otherwise
References INFO::DEFAULT_CONTEXT, and m_resetCondition.
VerifyStartCondition()
bool CSkinTimer::VerifyStartCondition () const
Evaluates the timer start boolean info expression returning the respective result.
Called from the skin timer manager to check if the timer should be started
Returns
true if the condition is true, false otherwise
References INFO::DEFAULT_CONTEXT, and m_startCondition.
VerifyStopCondition()
bool CSkinTimer::VerifyStopCondition () const
Evaluates the timer stop boolean info expression returning the respective result.
Called from the skin timer manager to check if the timer should be stopped
Returns
true if the condition is true, false otherwise
References INFO::DEFAULT_CONTEXT, and m_stopCondition.
Member Data Documentation
m_name
std::string CSkinTimer::m_name private
The name of the skin timer
Referenced by GetName().
m_resetCondition
INFO::InfoPtr CSkinTimer::m_resetCondition private
The info boolean expression that automatically resets the timer if evaluated true
Referenced by GetResetCondition(), and VerifyResetCondition().
m_resetOnStart
bool CSkinTimer::m_resetOnStart {false} private
if the timer should be reset on start (or just resumed)
Referenced by ResetsOnStart(), and Start().
m_startActions
CGUIAction CSkinTimer::m_startActions private
The builtin functions to be executed when the timer is started
Referenced by GetStartActions(), and OnStart().
m_startCondition
INFO::InfoPtr CSkinTimer::m_startCondition private
The info boolean expression that automatically starts the timer if evaluated true
Referenced by GetStartCondition(), and VerifyStartCondition().
m_stopActions
CGUIAction CSkinTimer::m_stopActions private
The builtin functions to be executed when the timer is stopped
Referenced by GetStopActions(), and OnStop().
m_stopCondition
INFO::InfoPtr CSkinTimer::m_stopCondition private
The info boolean expression that automatically stops the timer if evaluated true
Referenced by GetStopCondition(), and VerifyStopCondition().
The documentation for this class was generated from the following files:
SkinTimer.h
SkinTimer.cpp