Kodi Documentation: CSettingConditions Class Reference
CSettingConditions Class Reference
#include <SettingConditions.h>
Static Public Member Functions
static void Initialize ()
static void Deinitialize ()
static const CProfile & GetCurrentProfile ()
static const std::set< std::string > & GetSimpleConditions ()
static const std::map< std::string, SettingConditionCheck > & GetComplexConditions ()
static bool Check (const std::string &condition, const std::string &value="", const std::shared_ptr< const CSetting > &setting=NULL)
Static Private Attributes
static const CProfileManager * m_profileManager = nullptr
static std::set< std::string > m_simpleConditions
static std::map< std::string, SettingConditionCheck > m_complexConditions
Member Function Documentation
Check()
bool CSettingConditions::Check (const std::string & condition, const std::string & value = "", const std::shared_ptr< const CSetting > & setting = NULL) static
References Check(), m_complexConditions, m_simpleConditions, and value.
Referenced by Check().
Deinitialize()
void CSettingConditions::Deinitialize () static
References m_profileManager.
Referenced by CSettings::UninitializeConditions().
GetComplexConditions()
static const std::map< std::string, SettingConditionCheck > & CSettingConditions::GetComplexConditions () inline static
References m_complexConditions.
Referenced by CSettings::InitializeConditions().
GetCurrentProfile()
const CProfile & CSettingConditions::GetCurrentProfile () static
References CProfileManager::GetCurrentProfile(), CServiceBroker::GetSettingsComponent(), and m_profileManager.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileCanWriteDatabase(), anonymous_namespace{SettingConditions.cpp}::ProfileCanWriteSources(), anonymous_namespace{SettingConditions.cpp}::ProfileHasAddonManagerLocked(), anonymous_namespace{SettingConditions.cpp}::ProfileHasAddons(), anonymous_namespace{SettingConditions.cpp}::ProfileHasDatabase(), anonymous_namespace{SettingConditions.cpp}::ProfileHasFilesLocked(), anonymous_namespace{SettingConditions.cpp}::ProfileHasMusicLocked(), anonymous_namespace{SettingConditions.cpp}::ProfileHasPicturesLocked(), anonymous_namespace{SettingConditions.cpp}::ProfileHasProgramsLocked(), anonymous_namespace{SettingConditions.cpp}::ProfileHasSettingsLocked(), anonymous_namespace{SettingConditions.cpp}::ProfileHasSources(), anonymous_namespace{SettingConditions.cpp}::ProfileHasVideosLocked(), and anonymous_namespace{SettingConditions.cpp}::ProfileLockMode().
GetSimpleConditions()
static const std::set< std::string > & CSettingConditions::GetSimpleConditions () inline static
References m_simpleConditions.
Referenced by ADDON::CAddonSettings::InitializeConditions(), and CSettings::InitializeConditions().
Initialize()
void CSettingConditions::Initialize () static
References CServiceBroker::GetAppParams(), GreaterThan, ActiveAE::CActiveAESettings::IsSettingVisible(), LessThan, m_complexConditions, m_simpleConditions, and CWebServer::WebServerSupportsSSL().
Referenced by ADDON::CAddonSettings::InitializeConditions(), and CSettings::InitializeConditions().
Member Data Documentation
m_complexConditions
std::map< std::string, SettingConditionCheck > CSettingConditions::m_complexConditions static private
Referenced by Check(), GetComplexConditions(), and Initialize().
m_profileManager
const CProfileManager * CSettingConditions::m_profileManager = nullptr static private
Referenced by Deinitialize(), and GetCurrentProfile().
m_simpleConditions
std::set< std::string > CSettingConditions::m_simpleConditions static private
Referenced by Check(), GetSimpleConditions(), and Initialize().
The documentation for this class was generated from the following files:
SettingConditions.h
SettingConditions.cpp