Kodi Documentation: jni::CJNIXBMCVideoView Class Reference
jni::CJNIXBMCVideoView Class Reference
#include <JNIXBMCVideoView.h>
Public Member Functions
CJNIXBMCVideoView (const jni::jhobject &object)
~CJNIXBMCVideoView () override=default
void surfaceChanged (CJNISurfaceHolder holder, int format, int width, int height) override
void surfaceCreated (CJNISurfaceHolder holder) override
void surfaceDestroyed (CJNISurfaceHolder holder) override
bool waitForSurface (unsigned int millis)
bool isActive ()
CJNISurface getSurface ()
const CRect & getSurfaceRect ()
void setSurfaceRect (const CRect &rect)
void add ()
void release ()
int ID () const
bool isCreated () const
Static Public Member Functions
static void RegisterNatives (JNIEnv *env)
static CJNIXBMCVideoView * createVideoView (CJNISurfaceHolderCallback *callback)
static void _surfaceChanged (JNIEnv *env, jobject thiz, jobject holder, jint format, jint width, jint height)
static void _surfaceCreated (JNIEnv *env, jobject thiz, jobject holder)
static void _surfaceDestroyed (JNIEnv *env, jobject thiz, jobject holder)
Protected Attributes
CJNISurfaceHolderCallback * m_callback = nullptr
CEvent m_surfaceCreated
CRect m_surfaceRect
Private Member Functions
CJNIXBMCVideoView ()=default
Constructor & Destructor Documentation
CJNIXBMCVideoView() [1/2]
CJNIXBMCVideoView::CJNIXBMCVideoView (const jni::jhobject & object)
~CJNIXBMCVideoView()
jni::CJNIXBMCVideoView::~CJNIXBMCVideoView () override default
CJNIXBMCVideoView() [2/2]
jni::CJNIXBMCVideoView::CJNIXBMCVideoView () private default
Referenced by createVideoView().
Member Function Documentation
_surfaceChanged()
void CJNIXBMCVideoView::_surfaceChanged (JNIEnv * env, jobject thiz, jobject holder, jint format, jint width, jint height) static
References surfaceChanged(), and void().
Referenced by RegisterNatives().
_surfaceCreated()
void CJNIXBMCVideoView::_surfaceCreated (JNIEnv * env, jobject thiz, jobject holder) static
References surfaceCreated(), and void().
Referenced by RegisterNatives().
_surfaceDestroyed()
void CJNIXBMCVideoView::_surfaceDestroyed (JNIEnv * env, jobject thiz, jobject holder) static
References surfaceDestroyed(), and void().
Referenced by RegisterNatives().
add()
void CJNIXBMCVideoView::add ()
Referenced by createVideoView().
createVideoView()
CJNIXBMCVideoView * CJNIXBMCVideoView::createVideoView (CJNISurfaceHolderCallback * callback) static
References add(), CJNIXBMCVideoView(), isCreated(), CLog::Log(), LOGERROR, m_callback, m_surfaceCreated, s_className, and CEvent::Set().
Referenced by CDVDVideoCodecAndroidMediaCodec::Open().
getSurface()
CJNISurface CJNIXBMCVideoView::getSurface ()
getSurfaceRect()
const CRect & CJNIXBMCVideoView::getSurfaceRect ()
References m_surfaceRect.
ID()
int jni::CJNIXBMCVideoView::ID () const
isActive()
bool jni::CJNIXBMCVideoView::isActive () inline
References m_surfaceCreated, and CEvent::Signaled().
isCreated()
bool CJNIXBMCVideoView::isCreated () const
Referenced by createVideoView().
RegisterNatives()
void CJNIXBMCVideoView::RegisterNatives (JNIEnv * env) static
References _surfaceChanged(), _surfaceCreated(), _surfaceDestroyed(), and s_className.
Referenced by JNI_OnLoad().
release()
void CJNIXBMCVideoView::release ()
setSurfaceRect()
void CJNIXBMCVideoView::setSurfaceRect (const CRect & rect)
References m_surfaceRect, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
surfaceChanged()
void CJNIXBMCVideoView::surfaceChanged (CJNISurfaceHolder holder, int format, int width, int height) override
References m_callback.
Referenced by _surfaceChanged().
surfaceCreated()
void CJNIXBMCVideoView::surfaceCreated (CJNISurfaceHolder holder) override
References m_callback, m_surfaceCreated, and CEvent::Set().
Referenced by _surfaceCreated().
surfaceDestroyed()
void CJNIXBMCVideoView::surfaceDestroyed (CJNISurfaceHolder holder) override
References m_callback, m_surfaceCreated, and CEvent::Reset().
Referenced by _surfaceDestroyed().
waitForSurface()
bool CJNIXBMCVideoView::waitForSurface (unsigned int millis)
References m_surfaceCreated, and CEvent::Wait().
Member Data Documentation
m_callback
CJNISurfaceHolderCallback* jni::CJNIXBMCVideoView::m_callback = nullptr protected
Referenced by createVideoView(), surfaceChanged(), surfaceCreated(), and surfaceDestroyed().
m_surfaceCreated
CEvent jni::CJNIXBMCVideoView::m_surfaceCreated protected
Referenced by createVideoView(), isActive(), surfaceCreated(), surfaceDestroyed(), and waitForSurface().
m_surfaceRect
CRect jni::CJNIXBMCVideoView::m_surfaceRect protected
Referenced by getSurfaceRect(), and setSurfaceRect().
The documentation for this class was generated from the following files:
JNIXBMCVideoView.h
JNIXBMCVideoView.cpp