Kodi Documentation: CGUIKeyboard Class Reference
CGUIKeyboard Class Reference abstract
#include <GUIKeyboard.h>
Public Member Functions
CGUIKeyboard ()
~CGUIKeyboard () override=default
virtual bool ShowAndGetInput (char_callback_t pCallback, const std::string &initialString, std::string &typedString, const std::string &heading, bool bHiddenInput=false)=0
each native keyboard needs to implement this function with the following behaviour:
virtual void Cancel ()=0
This call should cancel a currently shown keyboard dialog. The implementation should return false from the modal ShowAndGetInput once anyone calls this method.
virtual int GetWindowId () const
void OnTimeout () override
void startAutoCloseTimer (unsigned int autoCloseMs)
void resetAutoCloseTimer ()
virtual bool SetTextToKeyboard (const std::string &text, bool closeKeyboard=false)
Public Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Private Attributes
CTimer m_idleTimer
Constructor & Destructor Documentation
CGUIKeyboard()
CGUIKeyboard::CGUIKeyboard () inline
~CGUIKeyboard()
CGUIKeyboard::~CGUIKeyboard () override default
Member Function Documentation
Cancel()
virtual void CGUIKeyboard::Cancel () pure virtual
This call should cancel a currently shown keyboard dialog. The implementation should return false from the modal ShowAndGetInput once anyone calls this method.
Implemented in CGUIDialogKeyboardGeneric, CGUIDialogKeyboardTouch, and CDarwinEmbedKeyboard.
Referenced by OnTimeout().
GetWindowId()
virtual int CGUIKeyboard::GetWindowId () const inline virtual
Reimplemented in CGUIDialogKeyboardGeneric, and CGUIDialogKeyboardTouch.
Referenced by CGUIKeyboardFactory::keyTypedCB().
OnTimeout()
void CGUIKeyboard::OnTimeout () inline override virtual
Implements ITimerCallback.
References Cancel().
resetAutoCloseTimer()
void CGUIKeyboard::resetAutoCloseTimer () inline
References CTimer::IsRunning(), m_idleTimer, and CTimer::Restart().
Referenced by CGUIKeyboardFactory::keyTypedCB().
SetTextToKeyboard()
virtual bool CGUIKeyboard::SetTextToKeyboard (const std::string & text, bool closeKeyboard = false) inline virtual
Reimplemented in CGUIDialogKeyboardTouch, and CDarwinEmbedKeyboard.
Referenced by CGUIKeyboardFactory::SendTextToActiveKeyboard().
ShowAndGetInput()
virtual bool CGUIKeyboard::ShowAndGetInput (char_callback_t pCallback, const std::string & initialString, std::string & typedString, const std::string & heading, bool bHiddenInput = false) pure virtual
each native keyboard needs to implement this function with the following behaviour:
Parameters
pCallback implementation should call this on each keypress with the current whole string
initialString implementation should show that initialstring
typedstring returns the typed string after close if return is true
heading implementation should show a heading (e.x. "search for a movie")
bHiddenInput if true the implementation should obfuscate the user input (e.x. by printing "*" for each char)
Returns
- true if typedstring is valid and user has confirmed input - false if typedstring is undefined and user canceled the input
Implemented in CGUIDialogKeyboardGeneric, CGUIDialogKeyboardTouch, and CDarwinEmbedKeyboard.
Referenced by CGUIKeyboardFactory::ShowAndGetInput().
startAutoCloseTimer()
void CGUIKeyboard::startAutoCloseTimer (unsigned int autoCloseMs) inline
References m_idleTimer, and CTimer::Start().
Referenced by CGUIKeyboardFactory::ShowAndGetInput().
Member Data Documentation
m_idleTimer
CTimer CGUIKeyboard::m_idleTimer private
Referenced by resetAutoCloseTimer(), and startAutoCloseTimer().
The documentation for this class was generated from the following file:
GUIKeyboard.h