Kodi Documentation: KODI::RETRO::CRenderBufferManager Class Reference
KODI::RETRO::CRenderBufferManager Class Reference
#include <RenderBufferManager.h>
Classes
struct RenderBufferPools
Public Member Functions
CRenderBufferManager ()=default
~CRenderBufferManager ()
void RegisterPools (IRendererFactory *factory, RenderBufferPoolVector pools)
RenderBufferPoolVector GetPools (IRendererFactory *factory)
std::vector< IRenderBufferPool * > GetBufferPools ()
void FlushPools ()
std::string GetRenderSystemName (IRenderBufferPool *renderBufferPool) const
bool HasScalingMethod (SCALINGMETHOD scalingMethod) const
Protected Attributes
std::vector< RenderBufferPools > m_pools
CCriticalSection m_critSection
Constructor & Destructor Documentation
CRenderBufferManager()
KODI::RETRO::CRenderBufferManager::CRenderBufferManager () default
~CRenderBufferManager()
CRenderBufferManager::~CRenderBufferManager ()
References FlushPools().
Member Function Documentation
FlushPools()
void CRenderBufferManager::FlushPools ()
References m_critSection, and m_pools.
Referenced by KODI::RETRO::CRPRenderManager::CheckFlush(), and ~CRenderBufferManager().
GetBufferPools()
std::vector< IRenderBufferPool * > CRenderBufferManager::GetBufferPools ()
References m_critSection, and m_pools.
Referenced by KODI::RETRO::CRPRenderManager::AddFrame(), KODI::RETRO::CRPRenderManager::GetRendererForSettings(), KODI::RETRO::CRPRenderManager::GetVideoBuffer(), KODI::RETRO::CRPRenderManager::LoadVideoFrameSync(), and KODI::RETRO::CRPRenderManager::SupportsScalingMethod().
GetPools()
RenderBufferPoolVector CRenderBufferManager::GetPools (IRendererFactory * factory)
References m_critSection, and m_pools.
GetRenderSystemName()
std::string CRenderBufferManager::GetRenderSystemName (IRenderBufferPool * renderBufferPool) const
References m_critSection, and m_pools.
HasScalingMethod()
bool CRenderBufferManager::HasScalingMethod (SCALINGMETHOD scalingMethod) const
References m_pools, and KODI::RETRO::CRenderVideoSettings::SetScalingMethod().
RegisterPools()
void CRenderBufferManager::RegisterPools (IRendererFactory * factory, RenderBufferPoolVector pools)
References m_critSection, and m_pools.
Member Data Documentation
m_critSection
CCriticalSection KODI::RETRO::CRenderBufferManager::m_critSection mutable protected
Referenced by FlushPools(), GetBufferPools(), GetPools(), GetRenderSystemName(), and RegisterPools().
m_pools
std::vector<RenderBufferPools> KODI::RETRO::CRenderBufferManager::m_pools protected
Referenced by FlushPools(), GetBufferPools(), GetPools(), GetRenderSystemName(), HasScalingMethod(), and RegisterPools().
The documentation for this class was generated from the following files:
RenderBufferManager.h
RenderBufferManager.cpp