Kodi Documentation: TestArtUtils.cpp File Reference
TestArtUtils.cpp File Reference
#include "FileItem.h"
#include "ServiceBroker.h"
#include "URL.h"
#include "filesystem/Directory.h"
#include "platform/Filesystem.h"
#include "settings/AdvancedSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "settings/lib/SettingsManager.h"
#include "utils/ArtUtils.h"
#include "utils/FileUtils.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "video/VideoInfoTag.h"
#include <array>
#include <fstream>
#include <random>
#include <fmt/format.h>
#include <gtest/gtest.h>
Classes
class anonymous_namespace{TestArtUtils.cpp}::AdvancedSettingsResetBase
struct anonymous_namespace{TestArtUtils.cpp}::ArtFilenameTest
class anonymous_namespace{TestArtUtils.cpp}::GetLocalArtBaseFilenameTest
struct anonymous_namespace{TestArtUtils.cpp}::FanartTest
class anonymous_namespace{TestArtUtils.cpp}::GetLocalFanartTest
struct anonymous_namespace{TestArtUtils.cpp}::IconTest
class anonymous_namespace{TestArtUtils.cpp}::FillInDefaultIconTest
struct anonymous_namespace{TestArtUtils.cpp}::TbnTest
class anonymous_namespace{TestArtUtils.cpp}::GetTbnTest
struct anonymous_namespace{TestArtUtils.cpp}::FolderTest
class anonymous_namespace{TestArtUtils.cpp}::FolderThumbTest
struct anonymous_namespace{TestArtUtils.cpp}::LocalArtTest
class anonymous_namespace{TestArtUtils.cpp}::TestLocalArt
Namespaces
namespace anonymous_namespace{TestArtUtils.cpp}
Functions
std::string anonymous_namespace{TestArtUtils.cpp}::unique_path (const std::string &input)
TEST_P (FillInDefaultIconTest, FillInDefaultIcon)
INSTANTIATE_TEST_SUITE_P (TestArtUtils, FillInDefaultIconTest, testing::ValuesIn(icon_tests))
TEST_P (FolderThumbTest, GetFolderThumb)
INSTANTIATE_TEST_SUITE_P (TestArtUtils, FolderThumbTest, testing::ValuesIn(folder_thumb_tests))
TEST_P (TestLocalArt, GetLocalArt)
INSTANTIATE_TEST_SUITE_P (TestArtUtils, TestLocalArt, testing::ValuesIn(local_art_tests))
TEST_P (GetLocalArtBaseFilenameTest, GetLocalArtBaseFilename)
INSTANTIATE_TEST_SUITE_P (TestArtUtils, GetLocalArtBaseFilenameTest, testing::ValuesIn(local_art_filename_tests))
TEST_P (GetLocalFanartTest, GetLocalFanart)
INSTANTIATE_TEST_SUITE_P (TestArtUtils, GetLocalFanartTest, testing::ValuesIn(local_fanart_tests))
TEST_P (GetTbnTest, TbnTest)
INSTANTIATE_TEST_SUITE_P (TestArtUtils, GetTbnTest, testing::ValuesIn(tbn_tests))
TEST (TestArtUtils, GetTbnStack)
Variables
const auto anonymous_namespace{TestArtUtils.cpp}::local_art_filename_tests
const auto anonymous_namespace{TestArtUtils.cpp}::local_fanart_tests
const auto anonymous_namespace{TestArtUtils.cpp}::icon_tests
const auto anonymous_namespace{TestArtUtils.cpp}::folder_thumb_tests
const auto anonymous_namespace{TestArtUtils.cpp}::local_art_tests
const auto tbn_tests
Function Documentation
INSTANTIATE_TEST_SUITE_P() [1/6]
INSTANTIATE_TEST_SUITE_P (TestArtUtils , FillInDefaultIconTest , testing::ValuesIn(icon_tests))
INSTANTIATE_TEST_SUITE_P() [2/6]
INSTANTIATE_TEST_SUITE_P (TestArtUtils , FolderThumbTest , testing::ValuesIn(folder_thumb_tests))
INSTANTIATE_TEST_SUITE_P() [3/6]
INSTANTIATE_TEST_SUITE_P (TestArtUtils , GetLocalArtBaseFilenameTest , testing::ValuesIn(local_art_filename_tests))
INSTANTIATE_TEST_SUITE_P() [4/6]
INSTANTIATE_TEST_SUITE_P (TestArtUtils , GetLocalFanartTest , testing::ValuesIn(local_fanart_tests))
INSTANTIATE_TEST_SUITE_P() [5/6]
INSTANTIATE_TEST_SUITE_P (TestArtUtils , GetTbnTest , testing::ValuesIn(tbn_tests))
INSTANTIATE_TEST_SUITE_P() [6/6]
INSTANTIATE_TEST_SUITE_P (TestArtUtils , TestLocalArt , testing::ValuesIn(local_art_tests))
TEST()
TEST (TestArtUtils , GetTbnStack)
References URIUtils::AddFileToFolder(), CFileUtils::DeleteItem(), EXPECT_EQ(), KODI::ART::GetTBNFile(), and KODI::PLATFORM::FILESYSTEM::temp_directory_path().
TEST_P() [1/6]
TEST_P (FillInDefaultIconTest , FillInDefaultIcon)
References EXPECT_EQ(), KODI::ART::FillInDefaultIcon(), CGUIListItem::GetArt(), CGUIListItem::GetOverlayImage(), CGUIListItem::SetArt(), CFileItem::SetLabel(), and CGUIListItem::SetProperty().
TEST_P() [2/6]
TEST_P (FolderThumbTest , GetFolderThumb)
References EXPECT_EQ(), and KODI::ART::GetFolderThumb().
TEST_P() [3/6]
TEST_P (GetLocalArtBaseFilenameTest , GetLocalArtBaseFilename)
References EXPECT_EQ(), and KODI::ART::GetLocalArtBaseFilename().
TEST_P() [4/6]
TEST_P (GetLocalFanartTest , GetLocalFanart)
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), XFILE::CDirectory::Create(), EXPECT_EQ(), URIUtils::GetFileName(), KODI::ART::GetLocalFanart(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::m_strFileNameAndPath, XFILE::CDirectory::RemoveRecursive(), KODI::UTILS::StringUtils::Replace(), KODI::PLATFORM::FILESYSTEM::temp_directory_path(), and anonymous_namespace{TestArtUtils.cpp}::unique_path().
TEST_P() [5/6]
TEST_P (GetTbnTest , TbnTest)
References EXPECT_EQ(), and KODI::ART::GetTBNFile().
TEST_P() [6/6]
TEST_P (TestLocalArt , GetLocalArt)
References EXPECT_EQ(), CURL::Get(), KODI::ART::GetLocalArt(), and CFileItem::SetPath().
Variable Documentation
tbn_tests
const auto tbn_tests
Initial value:
= std::array{
    TbnTest{"/home/user/video.avi", "/home/user/video.tbn"},
    TbnTest{"/home/user/video/", "/home/user/video.tbn", true},
    TbnTest{"/home/user/bar.xbt", "/home/user/bar.tbn", true},
    TbnTest{"zip://%2fhome%2fuser%2fbar.zip/foo.avi", "/home/user/foo.tbn"},
    TbnTest{"stack:///home/user/foo-cd1.avi , /home/user/foo-cd2.avi", "/home/user/foo.tbn"}}