Kodi Documentation: PVR::CPVREpgInfoTag Class Reference
PVR::CPVREpgInfoTag Class Reference final
#include <EpgInfoTag.h>
Public Member Functions
CPVREpgInfoTag (const EPG_TAG &data, int iClientId, const std::shared_ptr< CPVREpgChannelData > &channelData, int iEpgID)
Create a new EPG infotag.
CPVREpgInfoTag (const std::shared_ptr< CPVREpgChannelData > &channelData, int iEpgID, const CDateTime &start, const CDateTime &end, bool bIsGapTag)
Create a new EPG infotag.
void SetChannelData (const std::shared_ptr< CPVREpgChannelData > &data)
Set data for the channel linked to this EPG infotag.
bool operator== (const CPVREpgInfoTag &right) const
bool operator!= (const CPVREpgInfoTag &right) const
void Serialize (CVariant &value) const override
int ClientID () const
Get the identifier of the client that serves this event.
bool IsActive () const
Check if this event is currently active.
bool WasActive () const
Check if this event is in the past.
bool IsUpcoming () const
Check if this event is in the future.
float ProgressPercentage () const
Get the progress of this tag in percent.
unsigned int Progress () const
Get the progress of this tag in seconds.
int EpgID () const
Get EPG ID of this tag.
void SetEpgID (int iEpgID)
Sets the EPG id for this event.
void SetUniqueBroadcastID (unsigned int iUniqueBroadcastID)
Change the unique broadcast ID of this event.
unsigned int UniqueBroadcastID () const
Get the unique broadcast ID.
int DatabaseID () const
Get the event's database ID.
int UniqueChannelID () const
Get the unique ID of the channel associated with this event.
std::string ChannelIconPath () const
Get the path for the icon of the channel associated with this event.
CDateTime StartAsUTC () const
Get the event's start time.
CDateTime StartAsLocalTime () const
Get the event's start time.
CDateTime EndAsUTC () const
Get the event's end time.
CDateTime EndAsLocalTime () const
Get the event's end time.
void SetEndFromUTC (const CDateTime &end)
Change the event's end time.
unsigned int GetDuration () const
Get the duration of this event in seconds.
const std::string & Title () const
Get the title of this event.
const std::string & TitleExtraInfo () const
Get the title extra information of this event.
const std::string & PlotOutline () const
Get the plot outline of this event.
const std::string & Plot () const
Get the plot of this event.
const std::string & OriginalTitle () const
Get the original title of this event.
const std::vector< std::string > & Cast () const
Get the cast of this event.
const std::vector< std::string > & Directors () const
Get the director(s) of this event.
const std::vector< std::string > & Writers () const
Get the writer(s) of this event.
const std::string GetCastLabel () const
Get the cast of this event as formatted string.
const std::string GetDirectorsLabel () const
Get the director(s) of this event as formatted string.
const std::string GetWritersLabel () const
Get the writer(s) of this event as formatted string.
const std::string GetGenresLabel () const
Get the genre(s) of this event as formatted string.
int Year () const
Get the year of this event.
const std::string & IMDBNumber () const
Get the imdbnumber of this event.
int GenreType () const
Get the genre type ID of this event.
int GenreSubType () const
Get the genre subtype ID of this event.
const std::string & GenreDescription () const
Get the genre description of this event.
const std::vector< std::string > Genre () const
Get the genre as human readable string.
CDateTime FirstAired () const
Get the first air date of this event.
unsigned int ParentalRating () const
Get the parental rating of this event.
const std::string & ParentalRatingCode () const
Get the parental rating code of this event.
const std::string & ParentalRatingIcon () const
Get the parental rating icon path of this event.
std::string ClientParentalRatingIconPath () const
Get the parental rating icon path of this event as given by the client.
const std::string & ParentalRatingSource () const
Get the parental rating source of this event.
int StarRating () const
Get the star rating of this event.
int SeriesNumber () const
The series number of this event.
const std::string & SeriesLink () const
The series link for this event.
int EpisodeNumber () const
The episode number of this event.
int EpisodePart () const
The episode part number of this event.
const std::string & EpisodeName () const
The episode name of this event.
std::string IconPath () const
Get the path to the icon for this event used by Kodi.
std::string ClientIconPath () const
Get the path to the icon for this event as given by the client.
std::string Path () const
The path to this event.
bool IsRecordable () const
Check if this event can be recorded.
bool IsPlayable () const
Check if this event can be played.
bool QueuePersistQuery (const std::shared_ptr< CPVREpgDatabase > &database)
Write query to persist this tag in the query queue of the given database.
bool Update (const CPVREpgInfoTag &tag, bool bUpdateBroadcastId=true)
Update the information in this tag with the info in the given tag.
std::vector< EDL::Edit > GetEdl () const
Retrieve the edit decision list (EDL) of an EPG tag.
bool IsSeries () const
Check whether this tag has any series attributes.
bool IsRadio () const
Check whether this tag is associated with a radion or TV channel.
bool IsParentalLocked () const
Check whether this event is parental locked.
bool IsGapTag () const
Check whether this event is a real event or a gap in the EPG timeline.
bool IsNew () const
Check whether this tag will be flagged as new.
bool IsPremiere () const
Check whether this tag will be flagged as a premiere.
bool IsFinale () const
Check whether this tag will be flagged as a finale.
bool IsLive () const
Check whether this tag will be flagged as live.
unsigned int Flags () const
Return the flags (EPG_TAG_FLAG_*) of this event as a bitfield.
Static Public Member Functions
static const std::vector< std::string > Tokenize (const std::string &str)
Split the given string into tokens. Interprets occurrences of EPG_STRING_TOKEN_SEPARATOR in the string as separator.
static const std::string DeTokenize (const std::vector< std::string > &tokens)
Combine the given strings to a single string. Inserts EPG_STRING_TOKEN_SEPARATOR as separator.
Static Public Attributes
static const std::string IMAGE_OWNER_PATTERN = "epgtag_{}"
Private Member Functions
CPVREpgInfoTag (int iEpgID, const std::string &iconPath, const std::string &parentalRatingIconPath)
CPVREpgInfoTag ()=delete
CPVREpgInfoTag (const CPVREpgInfoTag &tag)=delete
CPVREpgInfoTag & operator= (const CPVREpgInfoTag &other)=delete
CDateTime GetCurrentPlayingTime () const
Get current time, taking timeshifting into account.
Private Attributes
int m_iDatabaseID = -1
int m_iGenreType = 0
int m_iGenreSubType = 0
std::string m_strGenreDescription
unsigned int m_parentalRating = 0
std::string m_parentalRatingCode
CPVRCachedImage m_parentalRatingIcon
std::string m_parentalRatingSource
int m_iStarRating = 0
int m_iSeriesNumber = -1
int m_iEpisodeNumber = -1
int m_iEpisodePart = -1
unsigned int m_iUniqueBroadcastID = 0
std::string m_strTitle
std::string m_titleExtraInfo
std::string m_strPlotOutline
std::string m_strPlot
std::string m_strOriginalTitle
std::vector< std::string > m_cast
std::vector< std::string > m_directors
std::vector< std::string > m_writers
int m_iYear = 0
std::string m_strIMDBNumber
std::vector< std::string > m_genre
std::string m_strEpisodeName
CPVRCachedImage m_iconPath
CDateTime m_startTime
CDateTime m_endTime
CDateTime m_firstAired
unsigned int m_iFlags = 0
std::string m_strSeriesLink
bool m_bIsGapTag = false
CCriticalSection m_critSection
std::shared_ptr< CPVREpgChannelData > m_channelData
int m_iEpgID = -1
Friends
class CPVREpgDatabase
Additional Inherited Members
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Constructor & Destructor Documentation
CPVREpgInfoTag() [1/5]
CPVREpgInfoTag::CPVREpgInfoTag (const EPG_TAG & data, int iClientId, const std::shared_ptr< CPVREpgChannelData > & channelData, int iEpgID)
Create a new EPG infotag.
Parameters
data The tag's data.
iClientId The client id.
channelData The channel data.
iEpgId The id of the EPG this tag belongs to.
References data(), LOGERROR, m_cast, m_channelData, m_directors, m_firstAired, m_parentalRatingCode, m_parentalRatingSource, m_strEpisodeName, m_strGenreDescription, m_strIMDBNumber, m_strOriginalTitle, m_strPlot, m_strPlotOutline, m_strSeriesLink, m_strTitle, m_titleExtraInfo, m_writers, CDateTime::SetFromW3CDate(), and Tokenize().
CPVREpgInfoTag() [2/5]
CPVREpgInfoTag::CPVREpgInfoTag (const std::shared_ptr< CPVREpgChannelData > & channelData, int iEpgID, const CDateTime & start, const CDateTime & end, bool bIsGapTag)
Create a new EPG infotag.
Parameters
channelData The channel data.
iEpgId The id of the EPG this tag belongs to.
start The start time of the event
end The end time of the event
bIsGapTagTrue if this is a "gap" tag, false if this is a real EPG event
References end(), CServiceBroker::GetSettingsComponent(), m_channelData, m_endTime, and m_startTime.
CPVREpgInfoTag() [3/5]
CPVREpgInfoTag::CPVREpgInfoTag (int iEpgID, const std::string & iconPath, const std::string & parentalRatingIconPath) private
CPVREpgInfoTag() [4/5]
PVR::CPVREpgInfoTag::CPVREpgInfoTag () private delete
CPVREpgInfoTag() [5/5]
PVR::CPVREpgInfoTag::CPVREpgInfoTag (const CPVREpgInfoTag & tag) private delete
Member Function Documentation
Cast()
const std::vector< std::string > & PVR::CPVREpgInfoTag::Cast () const inline
Get the cast of this event.
Returns
The cast.
References m_cast.
ChannelIconPath()
std::string CPVREpgInfoTag::ChannelIconPath () const
Get the path for the icon of the channel associated with this event.
Returns
The channel icon path.
References m_channelData, and m_critSection.
ClientIconPath()
std::string CPVREpgInfoTag::ClientIconPath () const
Get the path to the icon for this event as given by the client.
Returns
The path to the icon
References PVR::CPVRCachedImage::GetClientImage(), and m_iconPath.
Referenced by Serialize().
ClientID()
int CPVREpgInfoTag::ClientID () const
Get the identifier of the client that serves this event.
Returns
The identifier.
References m_channelData, and m_critSection.
Referenced by GetCurrentPlayingTime().
ClientParentalRatingIconPath()
std::string PVR::CPVREpgInfoTag::ClientParentalRatingIconPath () const inline
Get the parental rating icon path of this event as given by the client.
Returns
The path to the icon
References PVR::CPVRCachedImage::GetClientImage(), and m_parentalRatingIcon.
Referenced by Serialize().
DatabaseID()
int CPVREpgInfoTag::DatabaseID () const
Get the event's database ID.
Returns
The database ID.
References m_iDatabaseID.
DeTokenize()
const std::string CPVREpgInfoTag::DeTokenize (const std::vector< std::string > & tokens) static
Combine the given strings to a single string. Inserts EPG_STRING_TOKEN_SEPARATOR as separator.
Parameters
tokens The tokens.
Returns
the combined string.
References EPG_STRING_TOKEN_SEPARATOR.
Referenced by Serialize().
Directors()
const std::vector< std::string > & PVR::CPVREpgInfoTag::Directors () const inline
Get the director(s) of this event.
Returns
The director(s).
References m_directors.
EndAsLocalTime()
CDateTime CPVREpgInfoTag::EndAsLocalTime () const
Get the event's end time.
Returns
The end time as local time.
References m_endTime, and CDateTime::SetFromUTCDateTime().
Referenced by IsRecordable().
EndAsUTC()
CDateTime CPVREpgInfoTag::EndAsUTC () const
Get the event's end time.
Returns
The end time in UTC.
References m_endTime.
EpgID()
int CPVREpgInfoTag::EpgID () const
Get EPG ID of this tag.
Returns
The epg ID.
References m_iEpgID.
Referenced by Path().
EpisodeName()
const std::string & PVR::CPVREpgInfoTag::EpisodeName () const inline
The episode name of this event.
Returns
The episode name.
References m_strEpisodeName.
EpisodeNumber()
int CPVREpgInfoTag::EpisodeNumber () const
The episode number of this event.
Returns
The episode number.
References m_iEpisodeNumber.
Referenced by IsSeries().
EpisodePart()
int CPVREpgInfoTag::EpisodePart () const
The episode part number of this event.
Returns
The episode part number.
References m_iEpisodePart.
Referenced by IsSeries().
FirstAired()
CDateTime CPVREpgInfoTag::FirstAired () const
Get the first air date of this event.
Returns
The first air date.
References m_firstAired.
Flags()
unsigned int PVR::CPVREpgInfoTag::Flags () const inline
Return the flags (EPG_TAG_FLAG_*) of this event as a bitfield.
Returns
the flags.
References m_iFlags.
Genre()
const std::vector< std::string > CPVREpgInfoTag::Genre () const
Get the genre as human readable string.
Returns
The genre.
References PVR::CPVREpg::ConvertGenreIdToString(), EPG_GENRE_USE_STRING, m_genre, m_iGenreSubType, m_iGenreType, m_strGenreDescription, and Tokenize().
Referenced by GetGenresLabel(), and Serialize().
GenreDescription()
const std::string & PVR::CPVREpgInfoTag::GenreDescription () const inline
Get the genre description of this event.
Returns
The genre.
References m_strGenreDescription.
GenreSubType()
int CPVREpgInfoTag::GenreSubType () const
Get the genre subtype ID of this event.
Returns
The genre subtype ID.
References m_iGenreSubType.
GenreType()
int CPVREpgInfoTag::GenreType () const
Get the genre type ID of this event.
Returns
The genre type ID.
References m_iGenreType.
GetCastLabel()
const std::string CPVREpgInfoTag::GetCastLabel () const
Get the cast of this event as formatted string.
Returns
The cast label.
References m_cast.
GetCurrentPlayingTime()
CDateTime CPVREpgInfoTag::GetCurrentPlayingTime () const private
Get current time, taking timeshifting into account.
Returns
The playing time.
References ClientID(), CServiceBroker::GetPVRManager(), PVR::CPVRManager::PlaybackState(), and UniqueChannelID().
Referenced by IsActive(), IsUpcoming(), and WasActive().
GetDirectorsLabel()
const std::string CPVREpgInfoTag::GetDirectorsLabel () const
Get the director(s) of this event as formatted string.
Returns
The directors label.
References CServiceBroker::GetSettingsComponent(), and m_directors.
GetDuration()
unsigned int CPVREpgInfoTag::GetDuration () const
Get the duration of this event in seconds.
Returns
The duration.
References end(), CDateTime::GetAsTime(), m_endTime, and m_startTime.
Referenced by Serialize().
GetEdl()
std::vector< EDL::Edit > CPVREpgInfoTag::GetEdl () const
Retrieve the edit decision list (EDL) of an EPG tag.
Returns
The edit decision list (empty on error)
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_channelData, and m_critSection.
GetGenresLabel()
const std::string CPVREpgInfoTag::GetGenresLabel () const
Get the genre(s) of this event as formatted string.
Returns
The genres label.
References Genre(), and CServiceBroker::GetSettingsComponent().
GetWritersLabel()
const std::string CPVREpgInfoTag::GetWritersLabel () const
Get the writer(s) of this event as formatted string.
Returns
The writers label.
References CServiceBroker::GetSettingsComponent(), and m_writers.
IconPath()
std::string CPVREpgInfoTag::IconPath () const
Get the path to the icon for this event used by Kodi.
Returns
The path to the icon
References PVR::CPVRCachedImage::GetLocalImage(), and m_iconPath.
IMDBNumber()
const std::string & PVR::CPVREpgInfoTag::IMDBNumber () const inline
Get the imdbnumber of this event.
Returns
The imdbnumber.
References m_strIMDBNumber.
IsActive()
bool CPVREpgInfoTag::IsActive () const
Check if this event is currently active.
Returns
True if it's active, false otherwise.
References GetCurrentPlayingTime().
Referenced by Serialize().
IsFinale()
bool CPVREpgInfoTag::IsFinale () const
Check whether this tag will be flagged as a finale.
Returns
True if this tag will be flagged as a finale, false otherwise
References EPG_TAG_FLAG_IS_FINALE, and m_iFlags.
IsGapTag()
bool CPVREpgInfoTag::IsGapTag () const
Check whether this event is a real event or a gap in the EPG timeline.
Returns
True if this event is a gap, false otherwise.
References m_bIsGapTag, and m_critSection.
IsLive()
bool CPVREpgInfoTag::IsLive () const
Check whether this tag will be flagged as live.
Returns
True if this tag will be flagged as live, false otherwise
References EPG_TAG_FLAG_IS_LIVE, and m_iFlags.
IsNew()
bool CPVREpgInfoTag::IsNew () const
Check whether this tag will be flagged as new.
Returns
True if this tag will be flagged as new, false otherwise
References EPG_TAG_FLAG_IS_NEW, and m_iFlags.
IsParentalLocked()
bool CPVREpgInfoTag::IsParentalLocked () const
Check whether this event is parental locked.
Returns
True if whether this event is parental locked, false otherwise.
References m_channelData, and m_critSection.
IsPlayable()
bool CPVREpgInfoTag::IsPlayable () const
Check if this event can be played.
Returns
True if it can be played, false otherwise.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_channelData, m_critSection, and PVR_ERROR_NO_ERROR.
IsPremiere()
bool CPVREpgInfoTag::IsPremiere () const
Check whether this tag will be flagged as a premiere.
Returns
True if this tag will be flagged as a premiere, false otherwise
References EPG_TAG_FLAG_IS_PREMIERE, and m_iFlags.
IsRadio()
bool CPVREpgInfoTag::IsRadio () const
Check whether this tag is associated with a radion or TV channel.
Returns
True if this tag is associated with a radio channel, false otherwise.
References m_channelData, and m_critSection.
IsRecordable()
bool CPVREpgInfoTag::IsRecordable () const
Check if this event can be recorded.
Returns
True if it can be recorded, false otherwise.
References EndAsLocalTime(), PVR::CPVRManager::GetClient(), CDateTime::GetCurrentDateTime(), CServiceBroker::GetPVRManager(), m_channelData, m_critSection, and PVR_ERROR_NO_ERROR.
IsSeries()
bool CPVREpgInfoTag::IsSeries () const
Check whether this tag has any series attributes.
Returns
True if this tag has any series attributes, false otherwise
References EPG_TAG_FLAG_IS_SERIES, EpisodeNumber(), EpisodePart(), m_iFlags, and SeriesNumber().
Referenced by Serialize().
IsUpcoming()
bool CPVREpgInfoTag::IsUpcoming () const
Check if this event is in the future.
Returns
True when this event is an upcoming event, false otherwise.
References GetCurrentPlayingTime(), and m_startTime.
operator!=()
bool CPVREpgInfoTag::operator!= (const CPVREpgInfoTag & right) const
References right.
operator=()
CPVREpgInfoTag & PVR::CPVREpgInfoTag::operator= (const CPVREpgInfoTag & other) private delete
operator==()
bool CPVREpgInfoTag::operator== (const CPVREpgInfoTag & right) const
References m_channelData, m_critSection, m_iUniqueBroadcastID, and right.
OriginalTitle()
const std::string & PVR::CPVREpgInfoTag::OriginalTitle () const inline
Get the original title of this event.
Returns
The original title.
References m_strOriginalTitle.
ParentalRating()
unsigned int CPVREpgInfoTag::ParentalRating () const
Get the parental rating of this event.
Returns
The parental rating.
References m_parentalRating.
ParentalRatingCode()
const std::string & PVR::CPVREpgInfoTag::ParentalRatingCode () const inline
Get the parental rating code of this event.
Returns
The parental rating code.
References m_parentalRatingCode.
ParentalRatingIcon()
const std::string & PVR::CPVREpgInfoTag::ParentalRatingIcon () const inline
Get the parental rating icon path of this event.
Returns
Path to the parental rating icon.
References PVR::CPVRCachedImage::GetLocalImage(), and m_parentalRatingIcon.
ParentalRatingSource()
const std::string & PVR::CPVREpgInfoTag::ParentalRatingSource () const inline
Get the parental rating source of this event.
Returns
The parental rating source.
References m_parentalRatingSource.
Path()
std::string CPVREpgInfoTag::Path () const
The path to this event.
Returns
The path.
References EpgID(), CDateTime::GetAsDBDateTime(), and m_startTime.
Referenced by Serialize().
Plot()
const std::string & PVR::CPVREpgInfoTag::Plot () const inline
Get the plot of this event.
Returns
The plot.
References m_strPlot.
PlotOutline()
const std::string & PVR::CPVREpgInfoTag::PlotOutline () const inline
Get the plot outline of this event.
Returns
The plot outline.
References m_strPlotOutline.
Progress()
unsigned int CPVREpgInfoTag::Progress () const
Get the progress of this tag in seconds.
Returns
The current progress of this tag in seconds.
References CDateTime::GetAsTime(), CDateTime::GetAsUTCDateTime(), CDateTime::GetCurrentDateTime(), and m_startTime.
Referenced by Serialize().
ProgressPercentage()
float CPVREpgInfoTag::ProgressPercentage () const
Get the progress of this tag in percent.
Returns
The current progress of this tag.
References CDateTime::GetAsTime(), CDateTime::GetAsUTCDateTime(), CDateTime::GetCurrentDateTime(), m_endTime, and m_startTime.
Referenced by Serialize().
QueuePersistQuery()
bool CPVREpgInfoTag::QueuePersistQuery (const std::shared_ptr< CPVREpgDatabase > & database)
Write query to persist this tag in the query queue of the given database.
Parameters
database The database.
Returns
True on success, false otherwise.
References LOGERROR.
Serialize()
void CPVREpgInfoTag::Serialize (CVariant & value) const override virtual
Implements ISerializable.
References ClientIconPath(), ClientParentalRatingIconPath(), DeTokenize(), Genre(), CDateTime::GetAsDBDate(), CDateTime::GetAsDBDateTime(), GetDuration(), IsActive(), IsSeries(), CDateTime::IsValid(), m_cast, m_channelData, m_critSection, m_directors, m_endTime, m_firstAired, m_iDatabaseID, m_iEpisodeNumber, m_iEpisodePart, m_iSeriesNumber, m_iStarRating, m_iYear, m_parentalRating, m_parentalRatingCode, m_parentalRatingSource, m_startTime, m_strEpisodeName, m_strIMDBNumber, m_strOriginalTitle, m_strPlot, m_strPlotOutline, m_strSeriesLink, m_strTitle, m_titleExtraInfo, m_writers, Path(), Progress(), ProgressPercentage(), value, and WasActive().
SeriesLink()
const std::string & PVR::CPVREpgInfoTag::SeriesLink () const inline
The series link for this event.
Returns
The series link or empty string, if not available.
References m_strSeriesLink.
SeriesNumber()
int CPVREpgInfoTag::SeriesNumber () const
The series number of this event.
Returns
The series number.
References m_iSeriesNumber.
Referenced by IsSeries().
SetChannelData()
void CPVREpgInfoTag::SetChannelData (const std::shared_ptr< CPVREpgChannelData > & data)
Set data for the channel linked to this EPG infotag.
Parameters
data The channel data.
References data(), m_channelData, and m_critSection.
SetEndFromUTC()
void CPVREpgInfoTag::SetEndFromUTC (const CDateTime & end)
Change the event's end time.
Parameters
end The new end time.
References end(), and m_endTime.
SetEpgID()
void CPVREpgInfoTag::SetEpgID (int iEpgID)
Sets the EPG id for this event.
Parameters
iEpgID The EPG id.
References IMAGE_OWNER_PATTERN, m_iconPath, m_iEpgID, and PVR::CPVRCachedImage::SetOwner().
SetUniqueBroadcastID()
void CPVREpgInfoTag::SetUniqueBroadcastID (unsigned int iUniqueBroadcastID)
Change the unique broadcast ID of this event.
Parameters
iUniqueBroadcastId The new unique broadcast ID.
References m_iUniqueBroadcastID.
StarRating()
int CPVREpgInfoTag::StarRating () const
Get the star rating of this event.
Returns
The star rating.
References m_iStarRating.
StartAsLocalTime()
CDateTime CPVREpgInfoTag::StartAsLocalTime () const
Get the event's start time.
Returns
The start time as local time.
References m_startTime, and CDateTime::SetFromUTCDateTime().
StartAsUTC()
CDateTime CPVREpgInfoTag::StartAsUTC () const
Get the event's start time.
Returns
The start time in UTC.
References m_startTime.
Title()
const std::string & PVR::CPVREpgInfoTag::Title () const inline
Get the title of this event.
Returns
The title.
References m_strTitle.
TitleExtraInfo()
const std::string & PVR::CPVREpgInfoTag::TitleExtraInfo () const inline
Get the title extra information of this event.
Returns
The title extra info.
References m_titleExtraInfo.
Tokenize()
const std::vector< std::string > CPVREpgInfoTag::Tokenize (const std::string & str) static
Split the given string into tokens. Interprets occurrences of EPG_STRING_TOKEN_SEPARATOR in the string as separator.
Parameters
str The string to tokenize.
Returns
the tokens.
References EPG_STRING_TOKEN_SEPARATOR.
Referenced by CPVREpgInfoTag(), and Genre().
UniqueBroadcastID()
unsigned int CPVREpgInfoTag::UniqueBroadcastID () const
Get the unique broadcast ID.
Returns
The unique broadcast ID.
References m_iUniqueBroadcastID.
UniqueChannelID()
int CPVREpgInfoTag::UniqueChannelID () const
Get the unique ID of the channel associated with this event.
Returns
The unique channel ID.
References m_channelData, and m_critSection.
Referenced by GetCurrentPlayingTime().
Update()
bool CPVREpgInfoTag::Update (const CPVREpgInfoTag & tag, bool bUpdateBroadcastId = true)
Update the information in this tag with the info in the given tag.
Parameters
tag The new info.
bUpdateBroadcastId If set to false, the tag BroadcastId (locally unique) will not be checked/updated
Returns
True if something changed, false otherwise.
References m_cast, m_channelData, m_critSection, m_directors, m_endTime, m_firstAired, m_genre, m_iconPath, m_iDatabaseID, m_iEpgID, m_iEpisodeNumber, m_iEpisodePart, m_iFlags, m_iGenreSubType, m_iGenreType, m_iSeriesNumber, m_iStarRating, m_iUniqueBroadcastID, m_iYear, m_parentalRating, m_parentalRatingCode, m_parentalRatingIcon, m_parentalRatingSource, m_startTime, m_strEpisodeName, m_strGenreDescription, m_strIMDBNumber, m_strOriginalTitle, m_strPlot, m_strPlotOutline, m_strSeriesLink, m_strTitle, m_titleExtraInfo, and m_writers.
WasActive()
bool CPVREpgInfoTag::WasActive () const
Check if this event is in the past.
Returns
True when this event has already passed, false otherwise.
References GetCurrentPlayingTime(), and m_endTime.
Referenced by Serialize().
Writers()
const std::vector< std::string > & PVR::CPVREpgInfoTag::Writers () const inline
Get the writer(s) of this event.
Returns
The writer(s).
References m_writers.
Year()
int CPVREpgInfoTag::Year () const
Get the year of this event.
Returns
The year.
References m_iYear.
Friends And Related Symbol Documentation
CPVREpgDatabase
friend class CPVREpgDatabase friend
Member Data Documentation
IMAGE_OWNER_PATTERN
const std::string CPVREpgInfoTag::IMAGE_OWNER_PATTERN = "epgtag_{}" static
Referenced by PVR::CPVREpg::CleanupCachedImages(), and SetEpgID().
m_bIsGapTag
bool PVR::CPVREpgInfoTag::m_bIsGapTag = false private
Referenced by IsGapTag().
m_cast
std::vector<std::string> PVR::CPVREpgInfoTag::m_cast private
cast
Referenced by Cast(), CPVREpgInfoTag(), GetCastLabel(), Serialize(), and Update().
m_channelData
std::shared_ptr<CPVREpgChannelData> PVR::CPVREpgInfoTag::m_channelData private
Referenced by ChannelIconPath(), ClientID(), CPVREpgInfoTag(), CPVREpgInfoTag(), GetEdl(), IsParentalLocked(), IsPlayable(), IsRadio(), IsRecordable(), operator==(), Serialize(), SetChannelData(), UniqueChannelID(), and Update().
m_critSection
CCriticalSection PVR::CPVREpgInfoTag::m_critSection mutable private
Referenced by ChannelIconPath(), ClientID(), GetEdl(), IsGapTag(), IsParentalLocked(), IsPlayable(), IsRadio(), IsRecordable(), operator==(), Serialize(), SetChannelData(), UniqueChannelID(), and Update().
m_directors
std::vector<std::string> PVR::CPVREpgInfoTag::m_directors private
director(s)
Referenced by CPVREpgInfoTag(), Directors(), GetDirectorsLabel(), Serialize(), and Update().
m_endTime
CDateTime PVR::CPVREpgInfoTag::m_endTime private
event end time
Referenced by CPVREpgInfoTag(), EndAsLocalTime(), EndAsUTC(), GetDuration(), ProgressPercentage(), Serialize(), SetEndFromUTC(), Update(), and WasActive().
m_firstAired
CDateTime PVR::CPVREpgInfoTag::m_firstAired private
first airdate
Referenced by CPVREpgInfoTag(), FirstAired(), Serialize(), and Update().
m_genre
std::vector<std::string> PVR::CPVREpgInfoTag::m_genre mutable private
genre
Referenced by Genre(), and Update().
m_iconPath
CPVRCachedImage PVR::CPVREpgInfoTag::m_iconPath private
the path to the icon
Referenced by ClientIconPath(), IconPath(), SetEpgID(), and Update().
m_iDatabaseID
int PVR::CPVREpgInfoTag::m_iDatabaseID = -1 private
database ID
Referenced by DatabaseID(), Serialize(), and Update().
m_iEpgID
int PVR::CPVREpgInfoTag::m_iEpgID = -1 private
Referenced by EpgID(), SetEpgID(), and Update().
m_iEpisodeNumber
int PVR::CPVREpgInfoTag::m_iEpisodeNumber = -1 private
episode number
Referenced by EpisodeNumber(), Serialize(), and Update().
m_iEpisodePart
int PVR::CPVREpgInfoTag::m_iEpisodePart = -1 private
episode part number
Referenced by EpisodePart(), Serialize(), and Update().
m_iFlags
unsigned int PVR::CPVREpgInfoTag::m_iFlags = 0 private
the flags applicable to this EPG entry
Referenced by Flags(), IsFinale(), IsLive(), IsNew(), IsPremiere(), IsSeries(), and Update().
m_iGenreSubType
int PVR::CPVREpgInfoTag::m_iGenreSubType = 0 private
genre subtype
Referenced by Genre(), GenreSubType(), and Update().
m_iGenreType
int PVR::CPVREpgInfoTag::m_iGenreType = 0 private
genre type
Referenced by Genre(), GenreType(), and Update().
m_iSeriesNumber
int PVR::CPVREpgInfoTag::m_iSeriesNumber = -1 private
series number
Referenced by Serialize(), SeriesNumber(), and Update().
m_iStarRating
int PVR::CPVREpgInfoTag::m_iStarRating = 0 private
star rating
Referenced by Serialize(), StarRating(), and Update().
m_iUniqueBroadcastID
unsigned int PVR::CPVREpgInfoTag::m_iUniqueBroadcastID = 0 private
unique broadcast ID
Referenced by operator==(), SetUniqueBroadcastID(), UniqueBroadcastID(), and Update().
m_iYear
int PVR::CPVREpgInfoTag::m_iYear = 0 private
year
Referenced by Serialize(), Update(), and Year().
m_parentalRating
unsigned int PVR::CPVREpgInfoTag::m_parentalRating = 0 private
parental rating
Referenced by ParentalRating(), Serialize(), and Update().
m_parentalRatingCode
std::string PVR::CPVREpgInfoTag::m_parentalRatingCode private
Parental rating code
Referenced by CPVREpgInfoTag(), ParentalRatingCode(), Serialize(), and Update().
m_parentalRatingIcon
CPVRCachedImage PVR::CPVREpgInfoTag::m_parentalRatingIcon private
parental rating icon path
Referenced by ClientParentalRatingIconPath(), ParentalRatingIcon(), and Update().
m_parentalRatingSource
std::string PVR::CPVREpgInfoTag::m_parentalRatingSource private
parental rating source
Referenced by CPVREpgInfoTag(), ParentalRatingSource(), Serialize(), and Update().
m_startTime
CDateTime PVR::CPVREpgInfoTag::m_startTime private
event start time
Referenced by CPVREpgInfoTag(), GetDuration(), IsUpcoming(), Path(), Progress(), ProgressPercentage(), Serialize(), StartAsLocalTime(), StartAsUTC(), and Update().
m_strEpisodeName
std::string PVR::CPVREpgInfoTag::m_strEpisodeName private
episode name
Referenced by CPVREpgInfoTag(), EpisodeName(), Serialize(), and Update().
m_strGenreDescription
std::string PVR::CPVREpgInfoTag::m_strGenreDescription private
genre description
Referenced by CPVREpgInfoTag(), Genre(), GenreDescription(), and Update().
m_strIMDBNumber
std::string PVR::CPVREpgInfoTag::m_strIMDBNumber private
imdb number
Referenced by CPVREpgInfoTag(), IMDBNumber(), Serialize(), and Update().
m_strOriginalTitle
std::string PVR::CPVREpgInfoTag::m_strOriginalTitle private
original title
Referenced by CPVREpgInfoTag(), OriginalTitle(), Serialize(), and Update().
m_strPlot
std::string PVR::CPVREpgInfoTag::m_strPlot private
plot
Referenced by CPVREpgInfoTag(), Plot(), Serialize(), and Update().
m_strPlotOutline
std::string PVR::CPVREpgInfoTag::m_strPlotOutline private
plot outline
Referenced by CPVREpgInfoTag(), PlotOutline(), Serialize(), and Update().
m_strSeriesLink
std::string PVR::CPVREpgInfoTag::m_strSeriesLink private
series link
Referenced by CPVREpgInfoTag(), Serialize(), SeriesLink(), and Update().
m_strTitle
std::string PVR::CPVREpgInfoTag::m_strTitle private
title
Referenced by CPVREpgInfoTag(), Serialize(), Title(), and Update().
m_titleExtraInfo
std::string PVR::CPVREpgInfoTag::m_titleExtraInfo private
title extra info
Referenced by CPVREpgInfoTag(), Serialize(), TitleExtraInfo(), and Update().
m_writers
std::vector<std::string> PVR::CPVREpgInfoTag::m_writers private
writer(s)
Referenced by CPVREpgInfoTag(), GetWritersLabel(), Serialize(), Update(), and Writers().
The documentation for this class was generated from the following files:
EpgInfoTag.h
EpgInfoTag.cpp