Kodi Documentation: CRenderCapture Class Reference
CRenderCapture Class Reference abstract
#include <RenderCapture.h>
Public Member Functions
CRenderCapture ()=default
virtual ~CRenderCapture ()=default
virtual void BeginRender ()=0
virtual void EndRender ()=0
virtual void ReadOut ()
virtual void * GetRenderBuffer ()
void SetState (ECAPTURESTATE state)
ECAPTURESTATE GetState ()
void SetUserState (ECAPTURESTATE state)
ECAPTURESTATE GetUserState ()
CEvent & GetEvent ()
void SetFlags (int flags)
int GetFlags ()
void SetWidth (unsigned int width)
void SetHeight (unsigned int height)
unsigned int GetWidth ()
unsigned int GetHeight ()
uint8_t * GetPixels () const
bool IsAsync ()
Protected Member Functions
bool UseOcclusionQuery ()
Protected Attributes
ECAPTURESTATE m_state {CAPTURESTATE_FAILED}
ECAPTURESTATE m_userState {CAPTURESTATE_FAILED}
int m_flags {0}
CEvent m_event
uint8_t * m_pixels {nullptr}
unsigned int m_width {0}
unsigned int m_height {0}
unsigned int m_bufferSize {0}
bool m_asyncSupported {false}
bool m_asyncChecked {false}
Constructor & Destructor Documentation
CRenderCapture()
CRenderCapture::CRenderCapture () default
~CRenderCapture()
virtual CRenderCapture::~CRenderCapture () virtual default
Member Function Documentation
BeginRender()
virtual void CRenderCapture::BeginRender () pure virtual
Implemented in CRenderCaptureDX, CRenderCaptureGL, and CRenderCaptureGLES.
Referenced by CRendererDRMPRIME::RenderCapture(), CRendererDRMPRIMEGLES::RenderCapture(), CRendererMediaCodecSurface::RenderCapture(), CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), and CWinRenderer::RenderCapture().
EndRender()
virtual void CRenderCapture::EndRender () pure virtual
Implemented in CRenderCaptureDX, CRenderCaptureGL, and CRenderCaptureGLES.
Referenced by CRendererDRMPRIME::RenderCapture(), CRendererDRMPRIMEGLES::RenderCapture(), CRendererMediaCodecSurface::RenderCapture(), CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), and CWinRenderer::RenderCapture().
GetEvent()
CEvent & CRenderCapture::GetEvent () inline
References m_event.
Referenced by CRenderManager::ManageCaptures(), and CRenderManager::StartRenderCapture().
GetFlags()
int CRenderCapture::GetFlags () inline
References m_flags.
Referenced by CRenderManager::ManageCaptures().
GetHeight()
unsigned int CRenderCapture::GetHeight () inline
References m_height.
Referenced by CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), and CWinRenderer::RenderCapture().
GetPixels()
uint8_t * CRenderCapture::GetPixels () const inline
References m_pixels.
GetRenderBuffer()
virtual void * CRenderCapture::GetRenderBuffer () inline virtual
Reimplemented in CRenderCaptureGL.
References m_pixels.
Referenced by CLinuxRendererGL::RenderCapture(), and CLinuxRendererGLES::RenderCapture().
GetState()
ECAPTURESTATE CRenderCapture::GetState () inline
References m_state.
Referenced by CRenderManager::ManageCaptures(), CWinRenderer::RenderCapture(), and CRenderManager::StartRenderCapture().
GetUserState()
ECAPTURESTATE CRenderCapture::GetUserState () inline
References m_userState.
GetWidth()
unsigned int CRenderCapture::GetWidth () inline
References m_width.
Referenced by CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), and CWinRenderer::RenderCapture().
IsAsync()
bool CRenderCapture::IsAsync () inline
References m_asyncSupported.
Referenced by CRenderManager::ManageCaptures().
ReadOut()
virtual void CRenderCapture::ReadOut () inline virtual
Reimplemented in CRenderCaptureDX, and CRenderCaptureGL.
Referenced by CRenderManager::ManageCaptures().
SetFlags()
void CRenderCapture::SetFlags (int flags) inline
References m_flags.
Referenced by CRenderManager::StartRenderCapture().
SetHeight()
void CRenderCapture::SetHeight (unsigned int height) inline
References m_height.
Referenced by CRenderManager::StartRenderCapture().
SetState()
void CRenderCapture::SetState (ECAPTURESTATE state) inline
References m_state.
Referenced by CRenderCaptureDX::BeginRender(), CRenderCaptureDX::EndRender(), CRenderCaptureGL::EndRender(), CRenderCaptureGLES::EndRender(), CRenderManager::ManageCaptures(), CRenderCaptureDX::OnDestroyDevice(), CRenderCaptureGL::PboToBuffer(), CRenderManager::RenderCapture(), CRenderManager::StartRenderCapture(), and CRenderCaptureDX::SurfaceToBuffer().
SetUserState()
void CRenderCapture::SetUserState (ECAPTURESTATE state) inline
References m_userState.
Referenced by CRenderManager::ManageCaptures(), and CRenderManager::StartRenderCapture().
SetWidth()
void CRenderCapture::SetWidth (unsigned int width) inline
References m_width.
Referenced by CRenderManager::StartRenderCapture().
UseOcclusionQuery()
bool CRenderCapture::UseOcclusionQuery () protected
References CAPTUREFLAG_IMMEDIATELY, CServiceBroker::GetSettingsComponent(), and m_flags.
Referenced by CRenderCaptureDX::BeginRender(), and CRenderCaptureGL::BeginRender().
Member Data Documentation
m_asyncChecked
bool CRenderCapture::m_asyncChecked {false} protected
Referenced by CRenderCaptureDX::BeginRender(), and CRenderCaptureGL::BeginRender().
m_asyncSupported
bool CRenderCapture::m_asyncSupported {false} protected
Referenced by CRenderCaptureDX::BeginRender(), CRenderCaptureGL::BeginRender(), CRenderCaptureGL::EndRender(), CRenderCaptureGL::GetRenderBuffer(), IsAsync(), CRenderCaptureGL::ReadOut(), and CRenderCaptureGL::~CRenderCaptureGL().
m_bufferSize
unsigned int CRenderCapture::m_bufferSize {0} protected
Referenced by CRenderCaptureDX::BeginRender(), CRenderCaptureGL::BeginRender(), CRenderCaptureGLES::BeginRender(), and CRenderCaptureGL::PboToBuffer().
m_event
CEvent CRenderCapture::m_event protected
Referenced by GetEvent().
m_flags
int CRenderCapture::m_flags {0} protected
Referenced by CRenderCaptureDX::BeginRender(), CRenderCaptureGL::BeginRender(), CRenderCaptureDX::EndRender(), CRenderCaptureGL::EndRender(), GetFlags(), SetFlags(), and UseOcclusionQuery().
m_height
unsigned int CRenderCapture::m_height {0} protected
Referenced by CRenderCaptureDX::BeginRender(), CRenderCaptureGL::BeginRender(), CRenderCaptureGLES::BeginRender(), GetHeight(), SetHeight(), and CRenderCaptureDX::SurfaceToBuffer().
m_pixels
uint8_t* CRenderCapture::m_pixels {nullptr} protected
Referenced by CRenderCaptureDX::BeginRender(), CRenderCaptureGL::BeginRender(), CRenderCaptureGLES::BeginRender(), GetPixels(), GetRenderBuffer(), CRenderCaptureGL::GetRenderBuffer(), CRenderCaptureGL::PboToBuffer(), CRenderCaptureDX::SurfaceToBuffer(), CRenderCaptureDX::~CRenderCaptureDX(), CRenderCaptureGL::~CRenderCaptureGL(), and CRenderCaptureGLES::~CRenderCaptureGLES().
m_state
ECAPTURESTATE CRenderCapture::m_state {CAPTURESTATE_FAILED} protected
Referenced by GetState(), and SetState().
m_userState
ECAPTURESTATE CRenderCapture::m_userState {CAPTURESTATE_FAILED} protected
Referenced by GetUserState(), and SetUserState().
m_width
unsigned int CRenderCapture::m_width {0} protected
Referenced by CRenderCaptureDX::BeginRender(), CRenderCaptureGL::BeginRender(), CRenderCaptureGLES::BeginRender(), GetWidth(), SetWidth(), and CRenderCaptureDX::SurfaceToBuffer().
The documentation for this class was generated from the following files:
cores/VideoPlayer/VideoRenderers/RenderCapture.h
RenderCapture.cpp