Kodi Documentation: KODI::GAME::CGUIFeatureList Class Reference
KODI::GAME::CGUIFeatureList Class Reference
Games
#include <GUIFeatureList.h>
Classes
struct FeatureGroup
Public Member Functions
CGUIFeatureList (CGUIWindow *window, GameClientPtr gameClient)
~CGUIFeatureList () override
bool Initialize () override
Initialize the resource.
void Deinitialize () override
Deinitialize the resource.
bool HasButton (JOYSTICK::FEATURE_TYPE type) const override
Check if the feature type has any buttons in the GUI.
void Load (const ControllerPtr &controller) override
Load the features for the specified controller.
void OnFocus (unsigned int buttonIndex) override
Focus has been set to the specified GUI button.
void OnSelect (unsigned int buttonIndex) override
The specified GUI button has been selected.
Public Member Functions inherited from KODI::GAME::IFeatureList
virtual ~IFeatureList ()=default
Private Member Functions
IFeatureButton * GetButtonControl (unsigned int buttonIndex)
void CleanupButtons (void)
std::vector< FeatureGroup > GetFeatureGroups (const std::vector< CPhysicalFeature > &features) const
std::vector< CGUIButtonControl * > GetButtons (const std::vector< CPhysicalFeature > &features, unsigned int startIndex)
CGUIButtonControl * GetSelectKeyButton (const std::vector< CPhysicalFeature > &features, unsigned int buttonIndex)
Private Attributes
CGUIWindow *const m_window
unsigned int m_buttonCount = 0
CGUIControlGroupList * m_guiList = nullptr
CGUIButtonControl * m_guiButtonTemplate = nullptr
CGUILabelControl * m_guiGroupTitle = nullptr
CGUIImage * m_guiFeatureSeparator = nullptr
GameClientPtr m_gameClient
ControllerPtr m_controller
IConfigurationWizard * m_wizard
Constructor & Destructor Documentation
CGUIFeatureList()
CGUIFeatureList::CGUIFeatureList (CGUIWindow * window, GameClientPtr gameClient)
~CGUIFeatureList()
CGUIFeatureList::~CGUIFeatureList (void) override
References Deinitialize(), and m_wizard.
Member Function Documentation
CleanupButtons()
void CGUIFeatureList::CleanupButtons (void) private
References KODI::GAME::IConfigurationWizard::Abort(), CGUIControlGroupList::ClearAll(), m_buttonCount, m_guiList, m_wizard, and KODI::GAME::IConfigurationWizard::UnregisterKeys().
Referenced by Deinitialize(), and Load().
Deinitialize()
void CGUIFeatureList::Deinitialize () override virtual
Deinitialize the resource.
Remarks
This must be called if Initialize() returned true
Implements KODI::GAME::IFeatureList.
References CleanupButtons(), m_guiButtonTemplate, m_guiFeatureSeparator, m_guiGroupTitle, and m_guiList.
Referenced by ~CGUIFeatureList().
GetButtonControl()
IFeatureButton * CGUIFeatureList::GetButtonControl (unsigned int buttonIndex) private
References CONTROL_FEATURE_BUTTONS_START, CGUIControlLookup::GetControl(), and m_guiList.
Referenced by OnSelect().
GetButtons()
std::vector< CGUIButtonControl * > CGUIFeatureList::GetButtons (const std::vector< CPhysicalFeature > & features, unsigned int startIndex) private
References KODI::GAME::CGUIFeatureFactory::CreateButton(), KODI::GAME::CGUIFeatureTranslator::GetButtonType(), m_guiButtonTemplate, and m_wizard.
Referenced by Load().
GetFeatureGroups()
std::vector< CGUIFeatureList::FeatureGroup > CGUIFeatureList::GetFeatureGroups (const std::vector< CPhysicalFeature > & features) const private
References KODI::GAME::CGUIFeatureList::FeatureGroup::bIsVirtualKey, KODI::GAME::CGUIFeatureList::FeatureGroup::features, g_localizeStrings, CLocalizeStrings::Get(), KODI::GAME::CGUIFeatureList::FeatureGroup::groupName, KODI::JOYSTICK::KEY, m_controller, and m_gameClient.
Referenced by Load().
GetSelectKeyButton()
CGUIButtonControl * CGUIFeatureList::GetSelectKeyButton (const std::vector< CPhysicalFeature > & features, unsigned int buttonIndex) private
References KODI::GAME::CGUIFeatureFactory::CreateButton(), KODI::JOYSTICK::KEY, m_guiButtonTemplate, m_wizard, KODI::GAME::IConfigurationWizard::RegisterKey(), and KODI::GAME::SELECT_KEY.
Referenced by Load().
HasButton()
bool CGUIFeatureList::HasButton (JOYSTICK::FEATURE_TYPE type) const override virtual
Check if the feature type has any buttons in the GUI.
Parameters
The type of the feature being added to the GUI
Returns
True if the type is support, false otherwise
Implements KODI::GAME::IFeatureList.
References KODI::GAME::CGUIFeatureTranslator::GetButtonType(), and KODI::GAME::UNKNOWN.
Initialize()
bool CGUIFeatureList::Initialize () override virtual
Initialize the resource.
Returns
true if the resource is initialized and can be used false if the resource failed to initialize and must not be used
Implements KODI::GAME::IFeatureList.
References CONTROL_FEATURE_BUTTON_TEMPLATE, CONTROL_FEATURE_GROUP_TITLE, CONTROL_FEATURE_LIST, CONTROL_FEATURE_SEPARATOR, CGUIControlLookup::GetControl(), m_guiButtonTemplate, m_guiFeatureSeparator, m_guiGroupTitle, m_guiList, m_window, and CGUIControl::SetVisible().
Load()
void CGUIFeatureList::Load (const ControllerPtr & controller) override virtual
Load the features for the specified controller.
Parameters
controller The controller to load
Implements KODI::GAME::IFeatureList.
References CGUIControlGroupList::AddControl(), CleanupButtons(), GetButtons(), GetFeatureGroups(), GetSelectKeyButton(), CGUIControlGroupList::GetTotalSize(), m_buttonCount, m_controller, m_guiFeatureSeparator, m_guiGroupTitle, m_guiList, and MAX_FEATURE_COUNT.
OnFocus()
void KODI::GAME::CGUIFeatureList::OnFocus (unsigned int buttonIndex) inline override virtual
Focus has been set to the specified GUI button.
Parameters
buttonIndex The index of the button being focused
Implements KODI::GAME::IFeatureList.
OnSelect()
void CGUIFeatureList::OnSelect (unsigned int buttonIndex) override virtual
The specified GUI button has been selected.
Parameters
buttonIndex The index of the button being selected
Implements KODI::GAME::IFeatureList.
References KODI::GAME::IFeatureButton::AllowWizard(), GetButtonControl(), m_buttonCount, m_controller, m_wizard, and KODI::GAME::IConfigurationWizard::Run().
Member Data Documentation
m_buttonCount
unsigned int KODI::GAME::CGUIFeatureList::m_buttonCount = 0 private
Referenced by CleanupButtons(), Load(), and OnSelect().
m_controller
ControllerPtr KODI::GAME::CGUIFeatureList::m_controller private
Referenced by GetFeatureGroups(), Load(), and OnSelect().
m_gameClient
GameClientPtr KODI::GAME::CGUIFeatureList::m_gameClient private
Referenced by GetFeatureGroups().
m_guiButtonTemplate
CGUIButtonControl* KODI::GAME::CGUIFeatureList::m_guiButtonTemplate = nullptr private
Referenced by Deinitialize(), GetButtons(), GetSelectKeyButton(), and Initialize().
m_guiFeatureSeparator
CGUIImage* KODI::GAME::CGUIFeatureList::m_guiFeatureSeparator = nullptr private
Referenced by Deinitialize(), Initialize(), and Load().
m_guiGroupTitle
CGUILabelControl* KODI::GAME::CGUIFeatureList::m_guiGroupTitle = nullptr private
Referenced by Deinitialize(), Initialize(), and Load().
m_guiList
CGUIControlGroupList* KODI::GAME::CGUIFeatureList::m_guiList = nullptr private
Referenced by CleanupButtons(), Deinitialize(), GetButtonControl(), Initialize(), and Load().
m_window
CGUIWindow* const KODI::GAME::CGUIFeatureList::m_window private
Referenced by Initialize().
m_wizard
IConfigurationWizard* KODI::GAME::CGUIFeatureList::m_wizard private
Referenced by CleanupButtons(), GetButtons(), GetSelectKeyButton(), OnSelect(), and ~CGUIFeatureList().
The documentation for this class was generated from the following files:
GUIFeatureList.h
GUIFeatureList.cpp