Kodi Documentation: CDVDSubtitleTagSami Class Reference
CDVDSubtitleTagSami Class Reference
#include <DVDSubtitleTagSami.h>
Classes
struct SLangclass
Public Member Functions
CDVDSubtitleTagSami ()
virtual ~CDVDSubtitleTagSami ()
bool Init ()
void ConvertLine (std::string &strUTF8, const char *langClassID=NULL)
Convert a subtitle text line.
void CloseTag (std::string &text)
void LoadHead (CDVDSubtitleStream *samiStream)
Public Attributes
std::vector< SLangclass > m_Langclass
Private Attributes
CRegExp * m_tags
CRegExp * m_tagOptions
bool m_flag [6]
Constructor & Destructor Documentation
CDVDSubtitleTagSami()
CDVDSubtitleTagSami::CDVDSubtitleTagSami () inline
References FLAG_BOLD, FLAG_COLOR, FLAG_ITALIC, FLAG_LANGUAGE, FLAG_STRIKETHROUGH, FLAG_UNDERLINE, m_flag, m_tagOptions, and m_tags.
~CDVDSubtitleTagSami()
CDVDSubtitleTagSami::~CDVDSubtitleTagSami () virtual
References m_tagOptions, and m_tags.
Member Function Documentation
CloseTag()
void CDVDSubtitleTagSami::CloseTag (std::string & text)
References FLAG_BOLD, FLAG_COLOR, FLAG_ITALIC, FLAG_LANGUAGE, FLAG_STRIKETHROUGH, FLAG_UNDERLINE, m_flag, and text.
Referenced by CDVDOverlayCodecCCText::Decode(), CDVDOverlayCodecText::Decode(), CDVDSubtitleParserSami::Open(), and CDVDSubtitleParserSubrip::Open().
ConvertLine()
void CDVDSubtitleTagSami::ConvertLine (std::string & strUTF8, const char * langClassID = NULL)
Convert a subtitle text line.
Parameters
line The text line
len The line length
langClassID The SAMI Class ID language (keep the language lines with this ID and ignore all others)
References HTML::CHTMLUtil::ConvertHTMLToW(), FLAG_BOLD, FLAG_COLOR, FLAG_ITALIC, FLAG_LANGUAGE, FLAG_STRIKETHROUGH, FLAG_UNDERLINE, g_charsetConverter, CRegExp::GetMatch(), m_flag, m_tagOptions, m_tags, and CRegExp::RegFind().
Referenced by CDVDOverlayCodecCCText::Decode(), CDVDOverlayCodecText::Decode(), CDVDSubtitleParserSami::Open(), and CDVDSubtitleParserSubrip::Open().
Init()
bool CDVDSubtitleTagSami::Init ()
References m_tagOptions, m_tags, and CRegExp::RegComp().
Referenced by CDVDOverlayCodecCCText::Decode(), CDVDOverlayCodecText::Decode(), CDVDSubtitleParserSami::Open(), and CDVDSubtitleParserSubrip::Open().
LoadHead()
void CDVDSubtitleTagSami::LoadHead (CDVDSubtitleStream * samiStream)
References CRegExp::GetMatch(), CDVDSubtitleTagSami::SLangclass::ID, CDVDSubtitleTagSami::SLangclass::Lang, m_Langclass, CDVDSubtitleTagSami::SLangclass::Name, CDVDSubtitleStream::ReadLine(), CRegExp::RegComp(), CRegExp::RegFind(), and CDVDSubtitleTagSami::SLangclass::SAMIType.
Referenced by CDVDSubtitleParserSami::Open(), and CUtil::ScanForExternalSubtitles().
Member Data Documentation
m_flag
bool CDVDSubtitleTagSami::m_flag[6] private
Referenced by CDVDSubtitleTagSami(), CloseTag(), and ConvertLine().
m_Langclass
std::vector<SLangclass> CDVDSubtitleTagSami::m_Langclass
Referenced by LoadHead(), CDVDSubtitleParserSami::Open(), and CUtil::ScanForExternalSubtitles().
m_tagOptions
CRegExp* CDVDSubtitleTagSami::m_tagOptions private
Referenced by CDVDSubtitleTagSami(), ConvertLine(), Init(), and ~CDVDSubtitleTagSami().
m_tags
CRegExp* CDVDSubtitleTagSami::m_tags private
Referenced by CDVDSubtitleTagSami(), ConvertLine(), Init(), and ~CDVDSubtitleTagSami().
The documentation for this class was generated from the following files:
DVDSubtitleTagSami.h
DVDSubtitleTagSami.cpp