Kodi Documentation: CAudioSinkAE Class Reference
CAudioSinkAE Class Reference
#include <AudioSinkAE.h>
Public Member Functions
CAudioSinkAE (CDVDClock *clock)
~CAudioSinkAE () override
void SetVolume (float fVolume)
void SetDynamicRangeCompression (long drc)
void Pause ()
void Resume ()
bool Create (const DVDAudioFrame &audioframe, AVCodecID codec, bool needresampler)
bool IsValidFormat (const DVDAudioFrame &audioframe)
void Destroy (bool finish)
unsigned int AddPackets (const DVDAudioFrame &audioframe)
double GetPlayingPts ()
double GetCacheTime ()
double GetCacheTotal ()
double GetMaxDelay ()
double GetDelay ()
double GetSyncError ()
void SetSyncErrorCorrection (double correction)
double GetResampleRatio ()
Returns the resample ratio, or 0.0 if unknown/invalid.
void SetResampleMode (int mode)
void Flush ()
void Drain ()
void AbortAddPackets ()
double GetClock () override
double GetClockSpeed () override
CAEStreamInfo::DataType GetPassthroughStreamType (AVCodecID codecId, int samplerate, int profile)
Protected Attributes
IAE::StreamPtr m_pAudioStream
double m_playingPts
double m_timeOfPts
double m_syncError
unsigned int m_syncErrorTime
double m_resampleRatio = 0.0
CCriticalSection m_critSection
AEDataFormat m_dataFormat
unsigned int m_sampleRate
int m_iBitsPerSample
bool m_bPassthrough
CAEChannelInfo m_channelLayout
CAEStreamInfo::DataType m_dataType
bool m_bPaused
std::atomic_bool m_bAbort
CDVDClock * m_pClock
Additional Inherited Members
Private Member Functions inherited from IAEClockCallback
virtual ~IAEClockCallback ()=default
Constructor & Destructor Documentation
CAudioSinkAE()
CAudioSinkAE::CAudioSinkAE (CDVDClock * clock) explicit
References DVD_NOPTS_VALUE, m_bPassthrough, m_bPaused, m_iBitsPerSample, m_playingPts, m_sampleRate, m_syncError, m_syncErrorTime, and m_timeOfPts.
~CAudioSinkAE()
CAudioSinkAE::~CAudioSinkAE () override
References m_critSection.
Member Function Documentation
AbortAddPackets()
void CAudioSinkAE::AbortAddPackets ()
References m_bAbort.
Referenced by CVideoPlayerAudio::Flush().
AddPackets()
unsigned int CAudioSinkAE::AddPackets (const DVDAudioFrame & audioframe)
References IAEStream::ExtData::centerMixLevel, stDVDAudioFrame::centerMixLevel, stDVDAudioFrame::data, stDVDAudioFrame::duration, DVD_SEC_TO_TIME(), DVD_TIME_BASE, CAESyncInfo::errortime, stDVDAudioFrame::framesOut, CDVDClock::GetAbsoluteClock(), CDVDClock::GetClockSpeed(), GetDelay(), IAEStream::ExtData::hasDownmix, stDVDAudioFrame::hasDownmix, CLog::Log(), LOGERROR, m_bAbort, m_critSection, m_pAudioStream, m_pClock, m_playingPts, m_resampleRatio, m_syncError, m_syncErrorTime, m_timeOfPts, stDVDAudioFrame::nb_frames, IAEStream::ExtData::pts, stDVDAudioFrame::pts, KODI::TIME::Sleep(), and CAESyncInfo::SYNC_INSYNC.
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
Create()
bool CAudioSinkAE::Create (const DVDAudioFrame & audioframe, AVCodecID codec, bool needresampler)
References AESTREAM_FORCE_RESAMPLE, AESTREAM_PAUSED, stDVDAudioFrame::bits_per_sample, CAEChannelInfo::Count(), stDVDAudioFrame::format, CServiceBroker::GetActiveAE(), CLog::Log(), LOGINFO, m_bPassthrough, AEAudioFormat::m_channelLayout, m_channelLayout, m_critSection, AEAudioFormat::m_dataFormat, m_dataFormat, m_dataType, m_iBitsPerSample, m_pAudioStream, AEAudioFormat::m_sampleRate, m_sampleRate, AEAudioFormat::m_streamInfo, CAEStreamInfo::m_type, IAE::MakeStream(), and stDVDAudioFrame::passthrough.
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
Destroy()
void CAudioSinkAE::Destroy (bool finish)
References DVD_NOPTS_VALUE, m_bPassthrough, m_bPaused, m_critSection, m_iBitsPerSample, m_pAudioStream, m_playingPts, and m_sampleRate.
Referenced by CVideoPlayerAudio::CloseStream(), and CVideoPlayerAudio::ProcessDecoderOutput().
Drain()
void CAudioSinkAE::Drain ()
References m_critSection, and m_pAudioStream.
Referenced by CVideoPlayerAudio::CloseStream(), CVideoPlayerAudio::Process(), and CVideoPlayerAudio::ProcessDecoderOutput().
Flush()
void CAudioSinkAE::Flush ()
References DVD_NOPTS_VALUE, CLog::Log(), LOGDEBUG, m_bAbort, m_critSection, m_pAudioStream, m_playingPts, m_syncError, and m_syncErrorTime.
Referenced by CVideoPlayerAudio::CloseStream(), and CVideoPlayerAudio::Process().
GetCacheTime()
double CAudioSinkAE::GetCacheTime ()
References m_critSection, and m_pAudioStream.
Referenced by GetPlayingPts(), CVideoPlayerAudio::Process(), and CVideoPlayerAudio::ProcessDecoderOutput().
GetCacheTotal()
double CAudioSinkAE::GetCacheTotal ()
References m_critSection, and m_pAudioStream.
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
GetClock()
double CAudioSinkAE::GetClock () override virtual
Implements IAEClockCallback.
References DVD_TIME_BASE, CDVDClock::GetClock(), CDVDClock::GetVsyncAdjust(), and m_pClock.
GetClockSpeed()
double CAudioSinkAE::GetClockSpeed () override virtual
Reimplemented from IAEClockCallback.
References CDVDClock::GetClockSpeed(), and m_pClock.
GetDelay()
double CAudioSinkAE::GetDelay ()
References DVD_TIME_BASE, m_critSection, and m_pAudioStream.
Referenced by AddPackets(), CVideoPlayerAudio::Process(), and CVideoPlayerAudio::ProcessDecoderOutput().
GetMaxDelay()
double CAudioSinkAE::GetMaxDelay ()
References m_critSection, and m_pAudioStream.
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
GetPassthroughStreamType()
CAEStreamInfo::DataType CAudioSinkAE::GetPassthroughStreamType (AVCodecID codecId, int samplerate, int profile)
References AE_FMT_RAW, CServiceBroker::GetActiveAE(), AEAudioFormat::m_dataFormat, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, CAEStreamInfo::STREAM_TYPE_NULL, CAEStreamInfo::STREAM_TYPE_TRUEHD, IAE::SupportsRaw(), and IAE::UsesDtsCoreFallback().
Referenced by CVideoPlayerAudio::OpenStream(), and CVideoPlayerAudio::SwitchCodecIfNeeded().
GetPlayingPts()
double CAudioSinkAE::GetPlayingPts ()
References DVD_NOPTS_VALUE, CDVDClock::GetAbsoluteClock(), GetCacheTime(), m_pClock, m_playingPts, and m_timeOfPts.
Referenced by CVideoPlayerAudio::UpdatePlayerInfo().
GetResampleRatio()
double CAudioSinkAE::GetResampleRatio ()
Returns the resample ratio, or 0.0 if unknown/invalid.
References m_resampleRatio.
Referenced by CVideoPlayerAudio::UpdatePlayerInfo().
GetSyncError()
double CAudioSinkAE::GetSyncError ()
References m_syncError.
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
IsValidFormat()
bool CAudioSinkAE::IsValidFormat (const DVDAudioFrame & audioframe)
References stDVDAudioFrame::bits_per_sample, stDVDAudioFrame::format, m_bPassthrough, AEAudioFormat::m_channelLayout, m_channelLayout, AEAudioFormat::m_dataFormat, m_dataFormat, m_dataType, m_iBitsPerSample, m_pAudioStream, AEAudioFormat::m_sampleRate, m_sampleRate, AEAudioFormat::m_streamInfo, CAEStreamInfo::m_type, and stDVDAudioFrame::passthrough.
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
Pause()
void CAudioSinkAE::Pause ()
References DVD_NOPTS_VALUE, CLog::Log(), LOGDEBUG, m_critSection, m_pAudioStream, and m_playingPts.
Referenced by CVideoPlayerAudio::Process().
Resume()
void CAudioSinkAE::Resume ()
References CLog::Log(), LOGDEBUG, m_critSection, and m_pAudioStream.
Referenced by CVideoPlayerAudio::Process(), and CVideoPlayerAudio::ProcessDecoderOutput().
SetDynamicRangeCompression()
void CAudioSinkAE::SetDynamicRangeCompression (long drc)
References m_critSection, and m_pAudioStream.
Referenced by CVideoPlayerAudio::ProcessDecoderOutput(), and CVideoPlayerAudio::SetDynamicRangeCompression().
SetResampleMode()
void CAudioSinkAE::SetResampleMode (int mode)
References m_critSection, and m_pAudioStream.
Referenced by CVideoPlayerAudio::SetSyncType().
SetSyncErrorCorrection()
void CAudioSinkAE::SetSyncErrorCorrection (double correction)
References m_syncError.
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
SetVolume()
void CAudioSinkAE::SetVolume (float fVolume)
References m_critSection, and m_pAudioStream.
Member Data Documentation
m_bAbort
std::atomic_bool CAudioSinkAE::m_bAbort protected
Referenced by AbortAddPackets(), AddPackets(), and Flush().
m_bPassthrough
bool CAudioSinkAE::m_bPassthrough protected
Referenced by CAudioSinkAE(), Create(), Destroy(), and IsValidFormat().
m_bPaused
bool CAudioSinkAE::m_bPaused protected
Referenced by CAudioSinkAE(), and Destroy().
m_channelLayout
CAEChannelInfo CAudioSinkAE::m_channelLayout protected
Referenced by Create(), and IsValidFormat().
m_critSection
CCriticalSection CAudioSinkAE::m_critSection protected
Referenced by AddPackets(), Create(), Destroy(), Drain(), Flush(), GetCacheTime(), GetCacheTotal(), GetDelay(), GetMaxDelay(), Pause(), Resume(), SetDynamicRangeCompression(), SetResampleMode(), SetVolume(), and ~CAudioSinkAE().
m_dataFormat
AEDataFormat CAudioSinkAE::m_dataFormat protected
Referenced by Create(), and IsValidFormat().
m_dataType
CAEStreamInfo::DataType CAudioSinkAE::m_dataType protected
Referenced by Create(), and IsValidFormat().
m_iBitsPerSample
int CAudioSinkAE::m_iBitsPerSample protected
Referenced by CAudioSinkAE(), Create(), Destroy(), and IsValidFormat().
m_pAudioStream
IAE::StreamPtr CAudioSinkAE::m_pAudioStream protected
Referenced by AddPackets(), Create(), Destroy(), Drain(), Flush(), GetCacheTime(), GetCacheTotal(), GetDelay(), GetMaxDelay(), IsValidFormat(), Pause(), Resume(), SetDynamicRangeCompression(), SetResampleMode(), and SetVolume().
m_pClock
CDVDClock* CAudioSinkAE::m_pClock protected
Referenced by AddPackets(), GetClock(), GetClockSpeed(), and GetPlayingPts().
m_playingPts
double CAudioSinkAE::m_playingPts protected
Referenced by AddPackets(), CAudioSinkAE(), Destroy(), Flush(), GetPlayingPts(), and Pause().
m_resampleRatio
double CAudioSinkAE::m_resampleRatio = 0.0 protected
Referenced by AddPackets(), and GetResampleRatio().
m_sampleRate
unsigned int CAudioSinkAE::m_sampleRate protected
Referenced by CAudioSinkAE(), Create(), Destroy(), and IsValidFormat().
m_syncError
double CAudioSinkAE::m_syncError protected
Referenced by AddPackets(), CAudioSinkAE(), Flush(), GetSyncError(), and SetSyncErrorCorrection().
m_syncErrorTime
unsigned int CAudioSinkAE::m_syncErrorTime protected
Referenced by AddPackets(), CAudioSinkAE(), and Flush().
m_timeOfPts
double CAudioSinkAE::m_timeOfPts protected
Referenced by AddPackets(), CAudioSinkAE(), and GetPlayingPts().
The documentation for this class was generated from the following files:
AudioSinkAE.h
AudioSinkAE.cpp