Kodi Documentation: AddonToKodiFuncTable_Peripheral Struct Reference
AddonToKodiFuncTable_Peripheral Struct Reference
#include <peripheral.h>
Public Attributes
KODI_HANDLE kodiInstance
void(* trigger_scan)(void *kodiInstance)
void(* refresh_button_maps)(void *kodiInstance, const char *device_name, const char *controller_id)
unsigned int(* feature_count)(void *kodiInstance, const char *controller_id, JOYSTICK_FEATURE_TYPE type)
void * kodiInstance
void const char * controller_id
void const char const char * feature_name
Member Data Documentation
controller_id
void const char* AddonToKodiFuncTable_Peripheral::controller_id
feature_count
unsigned int(* AddonToKodiFuncTable_Peripheral::feature_count) (void *kodiInstance, const char *controller_id, JOYSTICK_FEATURE_TYPE type)
Referenced by PERIPHERALS::CPeripheralAddon::ResetProperties().
feature_name
void const char const char* AddonToKodiFuncTable_Peripheral::feature_name
kodiInstance [1/2]
KODI_HANDLE AddonToKodiFuncTable_Peripheral::kodiInstance
Referenced by PERIPHERALS::CPeripheralAddon::ResetProperties().
kodiInstance [2/2]
void* AddonToKodiFuncTable_Peripheral::kodiInstance
refresh_button_maps
void(* AddonToKodiFuncTable_Peripheral::refresh_button_maps) (void *kodiInstance, const char *device_name, const char *controller_id)
Referenced by PERIPHERALS::CPeripheralAddon::ResetProperties().
trigger_scan
void(* AddonToKodiFuncTable_Peripheral::trigger_scan) (void *kodiInstance)
Referenced by PERIPHERALS::CPeripheralAddon::ResetProperties().
The documentation for this struct was generated from the following file:
addons/kodi-dev-kit/include/kodi/c-api/addon-instance/Peripheral.h