Kodi Documentation: XFILE::CUDFFile Class Reference
XFILE::CUDFFile Class Reference
#include <UDFFile.h>
Public Member Functions
CUDFFile ()
~CUDFFile () override=default
bool Open (const CURL &url) override
void Close () override
int Stat (const CURL &url, struct __stat64 *buffer) override
ssize_t Read (void *buffer, size_t size) override
int64_t Seek (int64_t filePosition, int whence) override
int64_t GetLength () override
int64_t GetPosition () override
bool Exists (const CURL &url) override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool OpenForWrite (const CURL &url, bool bOverWrite=false)
virtual bool ReOpen (const CURL &url)
virtual int Stat (struct __stat64 *buffer)
virtual ssize_t Write (const void *bufPtr, size_t bufSize)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool Delete (const CURL &url)
virtual bool Rename (const CURL &url, const CURL &urlnew)
virtual bool SetHidden (const CURL &url, bool hidden)
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Private Attributes
std::unique_ptr< CUDFBlockInput > m_bi {nullptr}
udfread * m_udf {nullptr}
UDFFILE * m_file {nullptr}
Constructor & Destructor Documentation
CUDFFile()
CUDFFile::CUDFFile ()
~CUDFFile()
XFILE::CUDFFile::~CUDFFile () override default
Member Function Documentation
Close()
void CUDFFile::Close () override virtual
Implements XFILE::IFile.
References m_file, and m_udf.
Referenced by Open().
Exists()
bool CUDFFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References Open().
GetLength()
int64_t CUDFFile::GetLength () override virtual
Implements XFILE::IFile.
References m_file.
Referenced by Stat().
GetPosition()
int64_t CUDFFile::GetPosition () override virtual
Implements XFILE::IFile.
References m_file.
Open()
bool CUDFFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References Close(), CURL::GetFileName(), CURL::GetHostName(), m_bi, m_file, and m_udf.
Referenced by Exists().
Read()
ssize_t CUDFFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References m_file.
Seek()
int64_t CUDFFile::Seek (int64_t filePosition, int whence) override virtual
Implements XFILE::IFile.
References m_file.
Stat()
int CUDFFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References GetLength(), m_file, and m_udf.
Member Data Documentation
m_bi
std::unique_ptr<CUDFBlockInput> XFILE::CUDFFile::m_bi {nullptr} private
Referenced by Open().
m_file
UDFFILE* XFILE::CUDFFile::m_file {nullptr} private
Referenced by Close(), GetLength(), GetPosition(), Open(), Read(), Seek(), and Stat().
m_udf
udfread* XFILE::CUDFFile::m_udf {nullptr} private
Referenced by Close(), Open(), and Stat().
The documentation for this class was generated from the following files:
UDFFile.h
UDFFile.cpp