Kodi Documentation: CTVOSPowerSyscall Class Reference
CTVOSPowerSyscall Class Reference
#include <TVOSPowerSyscall.h>
Public Member Functions
CTVOSPowerSyscall ()=default
~CTVOSPowerSyscall () override=default
bool Powerdown () override
bool Suspend () override
bool Hibernate () override
bool Reboot () override
bool CanPowerdown () override
bool CanSuspend () override
bool CanHibernate () override
bool CanReboot () override
int BatteryLevel () override
bool PumpPowerEvents (IPowerEventsCallback *callback) override
Pump power related events back to xbmc.
void SetOnPause ()
void SetOnResume ()
Public Member Functions inherited from CPowerSyscallWithoutEvents
CPowerSyscallWithoutEvents ()
Public Member Functions inherited from CAbstractPowerSyscall
int CountPowerFeatures () override
Public Member Functions inherited from IPowerSyscall
virtual ~IPowerSyscall ()=default
Static Public Member Functions
static IPowerSyscall * CreateInstance ()
static void Register ()
Static Public Member Functions inherited from IPowerSyscall
static IPowerSyscall * CreateInstance ()
Called by power manager to create platform power system adapter.
static void RegisterPowerSyscall (CreatePowerSyscallFunc createFunc)
Private Types
enum STATE : unsigned int { REPORTED = 0 , SUSPENDED = 1 , RESUMED = 2 }
Private Attributes
STATE m_state = REPORTED
Additional Inherited Members
Static Public Attributes inherited from IPowerSyscall
static const int MAX_COUNT_POWER_FEATURES = 4
Member Enumeration Documentation
STATE
enum CTVOSPowerSyscall::STATE : unsigned int private
Enumerator
REPORTED
SUSPENDED
RESUMED
Constructor & Destructor Documentation
CTVOSPowerSyscall()
CTVOSPowerSyscall::CTVOSPowerSyscall () default
Referenced by CreateInstance().
~CTVOSPowerSyscall()
CTVOSPowerSyscall::~CTVOSPowerSyscall () override default
Member Function Documentation
BatteryLevel()
int CTVOSPowerSyscall::BatteryLevel (void) override virtual
Implements IPowerSyscall.
CanHibernate()
bool CTVOSPowerSyscall::CanHibernate (void) override virtual
Implements IPowerSyscall.
CanPowerdown()
bool CTVOSPowerSyscall::CanPowerdown (void) override virtual
Implements IPowerSyscall.
CanReboot()
bool CTVOSPowerSyscall::CanReboot (void) override virtual
Implements IPowerSyscall.
CanSuspend()
bool CTVOSPowerSyscall::CanSuspend (void) override virtual
Implements IPowerSyscall.
CreateInstance()
IPowerSyscall * CTVOSPowerSyscall::CreateInstance () static
References CTVOSPowerSyscall().
Referenced by Register().
Hibernate()
bool CTVOSPowerSyscall::Hibernate (void) override virtual
Reimplemented from CPowerSyscallWithoutEvents.
Powerdown()
bool CTVOSPowerSyscall::Powerdown (void) override virtual
Implements IPowerSyscall.
PumpPowerEvents()
bool CTVOSPowerSyscall::PumpPowerEvents (IPowerEventsCallback * callback) override virtual
Pump power related events back to xbmc.
PumpPowerEvents is called from Application Thread and the platform implementation may signal power related events back to xbmc through the callback.
return true if an event occurred and false if not.
Parameters
callback the callback to signal to
Reimplemented from CPowerSyscallWithoutEvents.
References CLog::Log(), LOGDEBUG, m_state, REPORTED, RESUMED, and SUSPENDED.
Reboot()
bool CTVOSPowerSyscall::Reboot (void) override virtual
Implements IPowerSyscall.
Register()
void CTVOSPowerSyscall::Register () static
References CreateInstance(), and IPowerSyscall::RegisterPowerSyscall().
Referenced by CPlatformDarwinEmbedded::InitStageOne().
SetOnPause()
void CTVOSPowerSyscall::SetOnPause ()
References m_state, and SUSPENDED.
SetOnResume()
void CTVOSPowerSyscall::SetOnResume ()
References m_state, and RESUMED.
Suspend()
bool CTVOSPowerSyscall::Suspend (void) override virtual
Reimplemented from CPowerSyscallWithoutEvents.
Member Data Documentation
m_state
STATE CTVOSPowerSyscall::m_state = REPORTED private
Referenced by PumpPowerEvents(), SetOnPause(), and SetOnResume().
The documentation for this class was generated from the following files:
TVOSPowerSyscall.h
TVOSPowerSyscall.cpp