Kodi Documentation: CHevcSei Class Reference
CHevcSei Class Reference
Parses HEVC SEI messages for supplemental video information.
#include <HevcSei.h>
Public Member Functions
CHevcSei ()=default
~CHevcSei ()=default
Static Public Member Functions
static std::vector< CHevcSei > ParseSeiRbsp (const uint8_t *buf, const size_t len)
static std::vector< CHevcSei > ParseSeiRbspUnclearedEmulation (const uint8_t *inData, const size_t inDataLen, std::vector< uint8_t > &buf)
static std::optional< const CHevcSei * > FindHdr10PlusSeiMessage (const std::vector< uint8_t > &buf, const std::vector< CHevcSei > &messages)
static std::pair< bool, const std::vector< uint8_t > > RemoveHdr10PlusFromSeiNalu (const uint8_t *inData, const size_t inDataLen)
Public Attributes
uint8_t m_payloadType {0}
size_t m_payloadSize {0}
size_t m_msgOffset {0}
size_t m_payloadOffset {0}
Static Private Member Functions
static int ParseSeiMessage (CBitstreamReader &br, std::vector< CHevcSei > &messages)
static std::vector< CHevcSei > ParseSeiRbspInternal (const uint8_t *buf, const size_t len)
Detailed Description
Parses HEVC SEI messages for supplemental video information.
The CHevcSei class is used to interpret and handle Supplemental Enhancement Information (SEI) messages found in High Efficiency Video Coding (HEVC) bitstreams. It is particularly useful for extracting HDR10+ metadata and other types of supplemental data from HEVC encoded video streams.
Note
This class deals with SEI messages in HEVC streams and does not process the video content itself.
Constructor & Destructor Documentation
CHevcSei()
CHevcSei::CHevcSei () default
~CHevcSei()
CHevcSei::~CHevcSei () default
Member Function Documentation
FindHdr10PlusSeiMessage()
std::optional< const CHevcSei * > CHevcSei::FindHdr10PlusSeiMessage (const std::vector< uint8_t > & buf, const std::vector< CHevcSei > & messages) static
References CBitstreamReader::ReadBits().
Referenced by RemoveHdr10PlusFromSeiNalu().
ParseSeiMessage()
int CHevcSei::ParseSeiMessage (CBitstreamReader & br, std::vector< CHevcSei > & messages) static private
References CBitstreamReader::AvailableBits(), m_msgOffset, m_payloadOffset, m_payloadSize, m_payloadType, CBitstreamReader::Position(), CBitstreamReader::ReadBits(), and CBitstreamReader::SkipBits().
Referenced by ParseSeiRbspInternal().
ParseSeiRbsp()
std::vector< CHevcSei > CHevcSei::ParseSeiRbsp (const uint8_t * buf, const size_t len) static
References ParseSeiRbspInternal().
Referenced by ParseSeiRbspUnclearedEmulation().
ParseSeiRbspInternal()
std::vector< CHevcSei > CHevcSei::ParseSeiRbspInternal (const uint8_t * buf, const size_t len) static private
References CBitstreamReader::AvailableBits(), ParseSeiMessage(), and CBitstreamReader::SkipBits().
Referenced by ParseSeiRbsp().
ParseSeiRbspUnclearedEmulation()
std::vector< CHevcSei > CHevcSei::ParseSeiRbspUnclearedEmulation (const uint8_t * inData, const size_t inDataLen, std::vector< uint8_t > & buf) static
References HevcClearStartCodeEmulationPrevention3Byte(), and ParseSeiRbsp().
Referenced by RemoveHdr10PlusFromSeiNalu().
RemoveHdr10PlusFromSeiNalu()
std::pair< bool, const std::vector< uint8_t > > CHevcSei::RemoveHdr10PlusFromSeiNalu (const uint8_t * inData, const size_t inDataLen) static
References FindHdr10PlusSeiMessage(), HevcAddStartCodeEmulationPrevention3Byte(), and ParseSeiRbspUnclearedEmulation().
Referenced by CBitstreamConverter::BitstreamConvert().
Member Data Documentation
m_msgOffset
size_t CHevcSei::m_msgOffset {0}
Referenced by ParseSeiMessage().
m_payloadOffset
size_t CHevcSei::m_payloadOffset {0}
Referenced by ParseSeiMessage().
m_payloadSize
size_t CHevcSei::m_payloadSize {0}
Referenced by ParseSeiMessage().
m_payloadType
uint8_t CHevcSei::m_payloadType {0}
Referenced by ParseSeiMessage().
The documentation for this class was generated from the following files:
HevcSei.h
HevcSei.cpp