Kodi Documentation: AESinkDARWINOSX.cpp File Reference
AESinkDARWINOSX.cpp File Reference
#include "cores/AudioEngine/Sinks/AESinkDARWINOSX.h"
#include "ServiceBroker.h"
#include "cores/AudioEngine/AESinkFactory.h"
#include "cores/AudioEngine/Sinks/darwin/CoreAudioHelpers.h"
#include "cores/AudioEngine/Sinks/osx/AEDeviceEnumerationOSX.h"
#include "cores/AudioEngine/Sinks/osx/CoreAudioHardware.h"
#include "cores/AudioEngine/Utils/AERingBuffer.h"
#include "threads/SystemClock.h"
#include "utils/MemUtils.h"
#include "utils/StringUtils.h"
#include "utils/TimeUtils.h"
#include "utils/log.h"
#include <mutex>
Functions
static void EnumerateDevices (CADeviceList &list)
static void EnumerateDevices ()
static CADeviceList GetDevices ()
OSStatus deviceChangedCB (AudioObjectID inObjectID, UInt32 inNumberAddresses, const AudioObjectPropertyAddress inAddresses[], void *inClientData)
void LogLevel (unsigned int got, unsigned int wanted)
Variables
static CADeviceList s_devices
static CCriticalSection s_devicesLock
CCriticalSection mutex
XbmcThreads::ConditionVariable condVar
Function Documentation
deviceChangedCB()
OSStatus deviceChangedCB (AudioObjectID inObjectID, UInt32 inNumberAddresses, const AudioObjectPropertyAddress inAddresses[], void * inClientData)
References IAE::DeviceChange(), CServiceBroker::GetActiveAE(), CCoreAudioHardware::GetDefaultOutputDevice(), CLog::Log(), and LOGDEBUG.
Referenced by CAESinkDARWINOSX::CAESinkDARWINOSX(), and CAESinkDARWINOSX::~CAESinkDARWINOSX().
EnumerateDevices() [1/2]
static void EnumerateDevices () static
References EnumerateDevices(), s_devices, and s_devicesLock.
Referenced by EnumerateDevices(), CAESinkDARWINIOS::EnumerateDevicesEx(), CAESinkDARWINOSX::EnumerateDevicesEx(), and CAESinkDARWINTVOS::EnumerateDevicesEx().
EnumerateDevices() [2/2]
static void EnumerateDevices (CADeviceList & list) static
References CADeviceInstance::audioDeviceId, CCoreAudioHardware::GetDefaultOutputDevice(), AEDeviceEnumerationOSX::GetDeviceInfoList(), AEDeviceEnumerationOSX::GetMasterDeviceName(), CCoreAudioHardware::GetOutputDeviceName(), CCoreAudioHardware::GetOutputDevices(), CAEDeviceInfo::m_deviceName, CAEDeviceInfo::m_displayName, CAEDeviceInfo::m_displayNameExtra, CADeviceInstance::sourceId, and CADeviceInstance::streamIndex.
GetDevices()
static CADeviceList GetDevices () static
References s_devices, and s_devicesLock.
Referenced by CAESinkDARWINOSX::Initialize().
LogLevel()
void LogLevel (unsigned int got, unsigned int wanted) inline
References CLog::Log(), and LOGWARNING.
Variable Documentation
condVar
XbmcThreads::ConditionVariable condVar
mutex
CCriticalSection mutex
s_devices
CADeviceList s_devices static
Referenced by EnumerateDevices(), CAESinkDARWINOSX::EnumerateDevicesEx(), and GetDevices().
s_devicesLock
CCriticalSection s_devicesLock static
Referenced by EnumerateDevices(), and GetDevices().