Kodi Documentation: EVENTSERVER::CEventServer Class Reference
EVENTSERVER::CEventServer Class Reference
#include <EventServer.h>
Public Member Functions
CEventServer ()
~CEventServer () override=default
void Process () override
bool Running ()
void RefreshSettings ()
void StartServer ()
void StopServer (bool bWait)
unsigned int GetButtonCode (std::string &strMapName, bool &isAxis, float &amount, bool &isJoystick)
bool ExecuteNextAction ()
bool GetMousePos (float &x, float &y)
int GetNumberOfClients ()
Static Public Member Functions
static void RemoveInstance ()
static CEventServer * GetInstance ()
Protected Member Functions
void Cleanup ()
void Run ()
void ProcessPacket (SOCKETS::CAddress &addr, int packetSize)
void ProcessEvents ()
void RefreshClients ()
Protected Attributes
std::map< unsigned long, std::unique_ptr< EVENTCLIENT::CEventClient > > m_clients
std::unique_ptr< SOCKETS::CUDPSocket > m_pSocket
int m_iPort
int m_iListenTimeout
int m_iMaxClients
std::vector< uint8_t > m_pPacketBuffer
std::atomic< bool > m_bRunning = false
CCriticalSection m_critSection
bool m_bRefreshSettings
Static Protected Attributes
static std::unique_ptr< CEventServer > m_pInstance
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CEventServer()
CEventServer::CEventServer ()
References m_bRefreshSettings, CThread::m_bStop, and m_iListenTimeout.
~CEventServer()
EVENTSERVER::CEventServer::~CEventServer () override default
Member Function Documentation
Cleanup()
void CEventServer::Cleanup () protected
References m_clients, m_critSection, and m_pSocket.
Referenced by Run().
ExecuteNextAction()
bool CEventServer::ExecuteNextAction ()
References EVENTCLIENT::CEventAction::actionName, EVENTCLIENT::CEventAction::actionType, EVENTPACKET::AT_BUTTON, EVENTPACKET::AT_EXEC_BUILTIN, CBuiltins::Execute(), g_application, CGUIComponent::GetAudioManager(), CServiceBroker::GetGUI(), CBuiltins::GetInstance(), m_clients, m_critSection, CGUIAudioManager::PlayActionSound(), and KODI::ACTION::CActionTranslator::TranslateString().
Referenced by CInputManager::ProcessEventServer().
GetButtonCode()
unsigned int CEventServer::GetButtonCode (std::string & strMapName, bool & isAxis, float & amount, bool & isJoystick)
References m_clients, and m_critSection.
Referenced by CInputManager::ProcessEventServer().
GetInstance()
CEventServer * CEventServer::GetInstance () static
References m_pInstance.
Referenced by CNetworkServices::IsEventServerRunning(), CNetworkServices::RefreshEventServer(), CNetworkServices::StartEventServer(), and CNetworkServices::StopEventServer().
GetMousePos()
bool CEventServer::GetMousePos (float & x, float & y)
References m_clients, and m_critSection.
Referenced by CInputManager::ProcessEventServer().
GetNumberOfClients()
int CEventServer::GetNumberOfClients ()
References m_clients, and m_critSection.
Referenced by CInputManager::ProcessEventServer(), and CNetworkServices::StopEventServer().
Process()
void CEventServer::Process (void) override virtual
Reimplemented from CThread.
References CThread::m_bStop, Run(), and CThread::Sleep().
ProcessEvents()
void CEventServer::ProcessEvents () protected
References m_clients, and m_critSection.
Referenced by Run().
ProcessPacket()
void CEventServer::ProcessPacket (SOCKETS::CAddress & addr, int packetSize) protected
References CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_clients, m_critSection, m_iMaxClients, m_pPacketBuffer, and SOCKETS::CAddress::ULong().
Referenced by Run().
RefreshClients()
void CEventServer::RefreshClients () protected
References CLog::Log(), LOGINFO, m_bRefreshSettings, m_clients, and m_critSection.
Referenced by Run().
RefreshSettings()
void EVENTSERVER::CEventServer::RefreshSettings () inline
References m_bRefreshSettings, and m_critSection.
Referenced by CNetworkServices::RefreshEventServer().
RemoveInstance()
void CEventServer::RemoveInstance () static
References m_pInstance.
Referenced by CApplication::Cleanup().
Run()
void CEventServer::Run () protected
References Cleanup(), SOCKETS::CSocketFactory::CreateUDPSocket(), CSysInfo::GetDeviceName(), CZeroconf::GetInstance(), CServiceBroker::GetSettingsComponent(), listener, CLog::Log(), LOGERROR, LOGINFO, m_bRunning, CThread::m_bStop, m_iListenTimeout, m_iPort, m_pPacketBuffer, m_pSocket, PACKET_SIZE, ProcessEvents(), ProcessPacket(), CZeroconf::PublishService(), RefreshClients(), CSettings::SETTING_SERVICES_ESALLINTERFACES, and CSettings::SETTING_SERVICES_ESPORTRANGE.
Referenced by Process().
Running()
bool EVENTSERVER::CEventServer::Running () inline
References m_bRunning.
Referenced by CNetworkServices::IsEventServerRunning(), and CInputManager::ProcessEventServer().
StartServer()
void CEventServer::StartServer ()
References CThread::Create(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, m_bRunning, m_critSection, m_iMaxClients, m_iPort, CSettings::SETTING_SERVICES_ESMAXCLIENTS, and CSettings::SETTING_SERVICES_ESPORT.
Referenced by CNetworkServices::StartEventServer().
StopServer()
void CEventServer::StopServer (bool bWait)
References CZeroconf::GetInstance(), CZeroconf::RemoveService(), and CThread::StopThread().
Referenced by CNetworkServices::StopEventServer().
Member Data Documentation
m_bRefreshSettings
bool EVENTSERVER::CEventServer::m_bRefreshSettings protected
Referenced by CEventServer(), RefreshClients(), and RefreshSettings().
m_bRunning
std::atomic<bool> EVENTSERVER::CEventServer::m_bRunning = false protected
Referenced by Run(), Running(), and StartServer().
m_clients
std::map<unsigned long, std::unique_ptr<EVENTCLIENT::CEventClient> > EVENTSERVER::CEventServer::m_clients protected
Referenced by Cleanup(), ExecuteNextAction(), GetButtonCode(), GetMousePos(), GetNumberOfClients(), ProcessEvents(), ProcessPacket(), and RefreshClients().
m_critSection
CCriticalSection EVENTSERVER::CEventServer::m_critSection protected
Referenced by Cleanup(), ExecuteNextAction(), GetButtonCode(), GetMousePos(), GetNumberOfClients(), ProcessEvents(), ProcessPacket(), RefreshClients(), RefreshSettings(), and StartServer().
m_iListenTimeout
int EVENTSERVER::CEventServer::m_iListenTimeout protected
Referenced by CEventServer(), and Run().
m_iMaxClients
int EVENTSERVER::CEventServer::m_iMaxClients protected
Referenced by ProcessPacket(), and StartServer().
m_iPort
int EVENTSERVER::CEventServer::m_iPort protected
Referenced by Run(), and StartServer().
m_pInstance
std::unique_ptr< CEventServer > CEventServer::m_pInstance static protected
Referenced by GetInstance(), and RemoveInstance().
m_pPacketBuffer
std::vector<uint8_t> EVENTSERVER::CEventServer::m_pPacketBuffer protected
Referenced by ProcessPacket(), and Run().
m_pSocket
std::unique_ptr<SOCKETS::CUDPSocket> EVENTSERVER::CEventServer::m_pSocket protected
Referenced by Cleanup(), and Run().
The documentation for this class was generated from the following files:
EventServer.h
EventServer.cpp