Kodi Documentation: KODI::WINDOWING::WAYLAND::IShellSurface Class Reference
KODI::WINDOWING::WAYLAND::IShellSurface Class Reference abstract
#include <ShellSurface.h>
Public Types
enum State {
STATE_MAXIMIZED = 0 , STATE_FULLSCREEN , STATE_RESIZING , STATE_ACTIVATED ,
STATE_COUNT
}
using StateBitset = std::bitset< STATE_COUNT >
Public Member Functions
virtual void Initialize ()=0
virtual void SetFullScreen (wayland::output_t const &output, float refreshRate)=0
virtual void SetWindowed ()=0
virtual void SetMaximized ()=0
virtual void UnsetMaximized ()=0
virtual void SetMinimized ()=0
virtual void SetWindowGeometry (CRectInt geometry)=0
virtual void AckConfigure (std::uint32_t serial)=0
virtual void StartMove (wayland::seat_t const &seat, std::uint32_t serial)=0
virtual void StartResize (wayland::seat_t const &seat, std::uint32_t serial, wayland::shell_surface_resize edge)=0
virtual void ShowShellContextMenu (wayland::seat_t const &seat, std::uint32_t serial, CPointInt position)=0
virtual ~IShellSurface ()=default
Static Public Member Functions
static std::string StateToString (StateBitset state)
Protected Member Functions
IShellSurface () noexcept=default
Private Member Functions
IShellSurface (IShellSurface const &other)=delete
IShellSurface & operator= (IShellSurface const &other)=delete
Detailed Description
Abstraction for shell surfaces to support multiple protocols such as wl_shell (for compatibility) and xdg_shell (for features)
The interface itself is modeled after xdg_shell, so see there for the meaning of e.g. the surface states
Member Typedef Documentation
StateBitset
using KODI::WINDOWING::WAYLAND::IShellSurface::StateBitset = std::bitset<STATE_COUNT>
Member Enumeration Documentation
State
enum KODI::WINDOWING::WAYLAND::IShellSurface::State
Enumerator
STATE_MAXIMIZED
STATE_FULLSCREEN
STATE_RESIZING
STATE_ACTIVATED
STATE_COUNT
Constructor & Destructor Documentation
~IShellSurface()
virtual KODI::WINDOWING::WAYLAND::IShellSurface::~IShellSurface () virtual default
IShellSurface() [1/2]
KODI::WINDOWING::WAYLAND::IShellSurface::IShellSurface () protected default noexcept
IShellSurface() [2/2]
KODI::WINDOWING::WAYLAND::IShellSurface::IShellSurface (IShellSurface const & other) private delete
Member Function Documentation
AckConfigure()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::AckConfigure (std::uint32_t serial) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
Initialize()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::Initialize () pure virtual
Initialize shell surface
The event loop thread MUST NOT be running when this function is called. The difference to the constructor is that in this function callbacks may already be called.
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
operator=()
IShellSurface & KODI::WINDOWING::WAYLAND::IShellSurface::operator= (IShellSurface const & other) private delete
SetFullScreen()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::SetFullScreen (wayland::output_t const & output, float refreshRate) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::OnAppLifecycleEvent().
SetMaximized()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::SetMaximized () pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
SetMinimized()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::SetMinimized () pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
SetWindowed()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::SetWindowed () pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
SetWindowGeometry()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::SetWindowGeometry (CRectInt geometry) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
ShowShellContextMenu()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::ShowShellContextMenu (wayland::seat_t const & seat, std::uint32_t serial, CPointInt position) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
StartMove()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::StartMove (wayland::seat_t const & seat, std::uint32_t serial) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
StartResize()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::StartResize (wayland::seat_t const & seat, std::uint32_t serial, wayland::shell_surface_resize edge) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
StateToString()
std::string IShellSurface::StateToString (StateBitset state) static
References STATE_ACTIVATED, STATE_FULLSCREEN, STATE_MAXIMIZED, and STATE_RESIZING.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWayland::ApplyNextState(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnConfigure(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::ProcessMessages(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetResolutionInternal(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateSizeVariables().
UnsetMaximized()
virtual void KODI::WINDOWING::WAYLAND::IShellSurface::UnsetMaximized () pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell, KODI::WINDOWING::WAYLAND::CShellSurfaceWlShell, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell, and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6.
The documentation for this class was generated from the following files:
ShellSurface.h
ShellSurface.cpp