Kodi Documentation: CGUIDialogProgressBarHandle Class Reference
CGUIDialogProgressBarHandle Class Reference
#include <GUIDialogExtendedProgressBar.h>
Public Member Functions
CGUIDialogProgressBarHandle (const std::string &strTitle)
virtual ~CGUIDialogProgressBarHandle (void)=default
const std::string & Title (void)
void SetTitle (const std::string &strTitle)
std::string Text (void) const
void SetText (const std::string &strText)
bool IsFinished (void) const
void MarkFinished (void)
float Percentage (void) const
void SetPercentage (float fPercentage)
void SetProgress (int currentItem, int itemCount)
Private Attributes
CCriticalSection m_critSection
float m_fPercentage = 0
std::string m_strTitle
std::string m_strText
bool m_bFinished = false
Constructor & Destructor Documentation
CGUIDialogProgressBarHandle()
CGUIDialogProgressBarHandle::CGUIDialogProgressBarHandle (const std::string & strTitle) inline explicit
~CGUIDialogProgressBarHandle()
virtual CGUIDialogProgressBarHandle::~CGUIDialogProgressBarHandle (void) virtual default
Member Function Documentation
IsFinished()
bool CGUIDialogProgressBarHandle::IsFinished (void) const inline
References m_bFinished.
Referenced by XBMCAddon::xbmcgui::DialogProgressBG::isFinished().
MarkFinished()
void CGUIDialogProgressBarHandle::MarkFinished (void) inline
References m_bFinished.
Referenced by XBMCAddon::xbmcgui::DialogProgressBG::close(), PVR::CGUIWindowPVRBase::HideProgressDialog(), CProgressJob::MarkFinished(), MUSIC_INFO::CMusicInfoScanner::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), and PVR::CPVRGUIProgressHandler::Process().
Percentage()
float CGUIDialogProgressBarHandle::Percentage (void) const inline
References m_fPercentage.
Referenced by CGUIDialogExtendedProgressBar::UpdateState().
SetPercentage()
void CGUIDialogProgressBarHandle::SetPercentage (float fPercentage) inline
References m_fPercentage.
Referenced by CVideoDatabase::CleanDatabase(), MUSIC_INFO::CMusicInfoScanner::DoScan(), MUSIC_INFO::CMusicInfoScanner::Process(), PVR::CPVRGUIProgressHandler::Process(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), MUSIC_INFO::CMusicInfoScanner::ScanTags(), CProgressJob::SetProgress(), PVR::CGUIWindowPVRBase::ShowProgressDialog(), and XBMCAddon::xbmcgui::DialogProgressBG::update().
SetProgress()
void CGUIDialogProgressBarHandle::SetProgress (int currentItem, int itemCount)
References m_fPercentage.
Referenced by CProgressJob::SetProgress().
SetText()
void CGUIDialogProgressBarHandle::SetText (const std::string & strText)
References m_critSection, and m_strText.
Referenced by CVideoDatabase::CleanDatabase(), XBMCAddon::xbmcgui::DialogProgressBG::create(), MUSIC_INFO::CMusicInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::DoScan(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), MUSIC_INFO::CMusicInfoScanner::Process(), PVR::CPVRGUIProgressHandler::Process(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), CProgressJob::SetText(), PVR::CGUIWindowPVRBase::ShowProgressDialog(), and XBMCAddon::xbmcgui::DialogProgressBG::update().
SetTitle()
void CGUIDialogProgressBarHandle::SetTitle (const std::string & strTitle)
References m_critSection, and m_strTitle.
Referenced by CVideoDatabase::CleanDatabase(), XBMCAddon::xbmcgui::DialogProgressBG::create(), MUSIC_INFO::CMusicInfoScanner::DoScan(), KODI::VIDEO::CVideoInfoScanner::DoScan(), MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), MUSIC_INFO::CMusicInfoScanner::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), CProgressJob::SetTitle(), and XBMCAddon::xbmcgui::DialogProgressBG::update().
Text()
std::string CGUIDialogProgressBarHandle::Text (void) const
References m_critSection, and m_strText.
Referenced by CGUIDialogExtendedProgressBar::UpdateState().
Title()
const std::string & CGUIDialogProgressBarHandle::Title (void) inline
References m_strTitle.
Referenced by CGUIDialogExtendedProgressBar::UpdateState().
Member Data Documentation
m_bFinished
bool CGUIDialogProgressBarHandle::m_bFinished = false private
Referenced by IsFinished(), and MarkFinished().
m_critSection
CCriticalSection CGUIDialogProgressBarHandle::m_critSection mutable private
Referenced by SetText(), SetTitle(), and Text().
m_fPercentage
float CGUIDialogProgressBarHandle::m_fPercentage = 0 private
Referenced by Percentage(), SetPercentage(), and SetProgress().
m_strText
std::string CGUIDialogProgressBarHandle::m_strText private
Referenced by SetText(), and Text().
m_strTitle
std::string CGUIDialogProgressBarHandle::m_strTitle private
Referenced by SetTitle(), and Title().
The documentation for this class was generated from the following files:
GUIDialogExtendedProgressBar.h
GUIDialogExtendedProgressBar.cpp