Kodi Documentation: PAPlayer Class Reference
PAPlayer Class Reference
#include <PAPlayer.h>
Classes
struct StreamInfo
Public Member Functions
PAPlayer (IPlayerCallback &callback)
~PAPlayer () override
bool OpenFile (const CFileItem &file, const CPlayerOptions &options) override
bool QueueNextFile (const CFileItem &file) override
void OnNothingToQueueNotify () override
bool CloseFile (bool reopen=false) override
bool IsPlaying () const override
void Pause () override
bool HasVideo () const override
bool HasAudio () const override
bool CanSeek () const override
void Seek (bool bPlus=true, bool bLargeStep=false, bool bChapterOverride=false) override
void SeekPercentage (float fPercent=0.0f) override
void SetVolume (float volume) override
void SetDynamicRangeCompression (long drc) override
void SetSpeed (float speed=0) override
int GetCacheLevel () const override
void SetTotalTime (int64_t time) override
Set the total time in milliseconds this can be used for injecting the duration in case its not available in the underlaying decoder (airtunes for example)
void GetAudioStreamInfo (int index, AudioStreamInfo &info) const override
void SetTime (int64_t time) override
Sets the current time. This can be used for injecting the current time. This is not to be confused with a seek. It just can be used if endless streams contain multiple tracks in reality (like with airtunes)
void SeekTime (int64_t iTime=0) override
void GetAudioCapabilities (std::vector< IPlayerAudioCaps > &caps) const override
Define the audio capabilities of the player.
int GetAudioStreamCount () const override
int GetAudioStream () override
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
Public Member Functions inherited from IPlayer
IPlayer (IPlayerCallback &callback)
virtual ~IPlayer ()=default
virtual bool Initialize (TiXmlElement *pConfig)
virtual bool CanPause () const
virtual bool HasGame () const
virtual bool HasRDS () const
virtual bool HasID3 () const
virtual bool IsPassthrough () const
virtual bool SeekScene (Direction seekDirection)
virtual float GetCachePercentage () const
virtual void SetMute (bool bOnOff)
virtual void SetAVDelay (float fValue=0.0f)
virtual float GetAVDelay ()
virtual void SetSubTitleDelay (float fValue=0.0f)
virtual float GetSubTitleDelay ()
virtual int GetSubtitleCount () const
virtual int GetSubtitle ()
virtual void GetSubtitleStreamInfo (int index, SubtitleStreamInfo &info) const
virtual void SetSubtitle (int iStream)
virtual bool GetSubtitleVisible () const
virtual void SetSubtitleVisible (bool bVisible)
virtual void SetSubtitleVerticalPosition (int value, bool save)
Set the subtitle vertical position, it depends on current screen resolution.
virtual void AddSubtitle (const std::string &strSubPath)
Adds the subtitle(s) provided by the given file to the available player streams and actives the first of the added stream(s). E.g., vob subs can contain multiple streams.
virtual void SetAudioStream (int iStream)
virtual int GetVideoStream () const
virtual int GetVideoStreamCount () const
virtual void GetVideoStreamInfo (int streamId, VideoStreamInfo &info) const
virtual void SetVideoStream (int iStream)
virtual int GetPrograms (std::vector< ProgramInfo > &programs)
virtual void SetProgram (int progId)
virtual int GetProgramsCount () const
virtual bool HasTeletextCache () const
virtual std::shared_ptr< TextCacheStruct_t > GetTeletextCache ()
virtual void LoadPage (int p, int sp, unsigned char *buffer)
virtual int GetChapterCount () const
virtual int GetChapter () const
virtual void GetChapterName (std::string &strChapterName, int chapterIdx=-1) const
virtual int64_t GetChapterPos (int chapterIdx=-1) const
virtual int SeekChapter (int iChapter)
virtual bool SeekTimeRelative (int64_t iTime)
virtual void SetTempo (float tempo)
virtual bool SupportsTempo () const
virtual void FrameAdvance (int frames)
virtual bool IsCaching () const
virtual bool IsInMenu () const
virtual MenuType GetSupportedMenuType () const
Get the supported menu type.
virtual bool OnAction (const CAction &action)
virtual std::string GetPlayerState ()
virtual bool SetPlayerState (const std::string &state)
virtual void GetSubtitleCapabilities (std::vector< IPlayerSubtitleCaps > &caps) const
Define the subtitle capabilities of the player.
virtual void Render (bool clear, uint32_t alpha=255, bool gui=true)
hook into render loop of render thread
virtual void FlushRenderer ()
virtual void SetRenderViewMode (int mode, float zoom, float par, float shift, bool stretch)
virtual float GetRenderAspectRatio () const
virtual void TriggerUpdateResolution ()
virtual bool IsRenderingVideo () const
virtual void GetRects (CRect &source, CRect &dest, CRect &view) const
virtual unsigned int GetOrientation () const
virtual bool Supports (EINTERLACEMETHOD method) const
virtual EINTERLACEMETHOD GetDeinterlacingMethodDefault () const
virtual bool Supports (ESCALINGMETHOD method) const
virtual bool Supports (ERENDERFEATURE feature) const
virtual unsigned int RenderCaptureAlloc ()
virtual void RenderCaptureRelease (unsigned int captureId)
virtual void RenderCapture (unsigned int captureId, unsigned int width, unsigned int height, int flags)
virtual bool RenderCaptureGetPixels (unsigned int captureId, unsigned int millis, uint8_t *buffer, unsigned int size)
virtual CVideoSettings GetVideoSettings () const
virtual void SetVideoSettings (CVideoSettings &settings)
virtual bool HasGameAgent () const
Check if any players are playing a game.
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Public Attributes
struct {
char m_codec [21]
int64_t m_time
int64_t m_totalTime
int m_channelCount
int m_bitsPerSample
int m_sampleRate
int m_audioBitrate
int m_cacheLevel
bool m_canSeek
} m_playerGUIData
Public Attributes inherited from IPlayer
std::string m_name
std::string m_type
Protected Member Functions
void OnStartup () override
void Process () override
void OnExit () override
float GetPercentage ()
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Types
typedef std::list< StreamInfo * > StreamList
Private Member Functions
bool QueueNextFileEx (const CFileItem &file, bool fadeIn)
void SoftStart (bool wait=false)
void SoftStop (bool wait=false, bool close=true)
void CloseAllStreams (bool fade=true)
void ProcessStreams (double &freeBufferTime)
bool PrepareStream (StreamInfo *si)
bool ProcessStream (StreamInfo *si, double &freeBufferTime)
bool QueueData (StreamInfo *si)
int64_t GetTotalTime64 ()
void UpdateCrossfadeTime (const CFileItem &file)
void UpdateStreamInfoPlayNextAtFrame (StreamInfo *si, unsigned int crossFadingTime)
void UpdateGUIData (StreamInfo *si)
int64_t GetTimeInternal ()
bool SetTimeInternal (int64_t time)
bool SetTotalTimeInternal (int64_t time)
void CloseFileCB (StreamInfo &si)
void AdvancePlaylistOnError (CFileItem &fileItem)
Private Attributes
bool m_signalSpeedChange = false
bool m_signalStarted = true
std::atomic_int m_playbackSpeed
bool m_isPlaying = false
bool m_isPaused = false
bool m_isFinished = false
bool m_fullScreen
unsigned int m_defaultCrossfadeMS = 0
unsigned int m_upcomingCrossfadeMS = 0
CEvent m_startEvent
StreamInfo * m_currentStream = nullptr
IAudioCallback * m_audioCallback
CCriticalSection m_streamsLock
StreamList m_streams
StreamList m_finishing
int m_jobCounter = 0
CEvent m_jobEvent
int64_t m_newForcedPlayerTime = -1
int64_t m_newForcedTotalTime = -1
std::unique_ptr< CProcessInfo > m_processInfo
Friends
class CQueueNextFileJob
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Attributes inherited from IPlayer
IPlayerCallback & m_callback
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Member Typedef Documentation
StreamList
typedef std::list<StreamInfo*> PAPlayer::StreamList private
Constructor & Destructor Documentation
PAPlayer()
PAPlayer::PAPlayer (IPlayerCallback & callback) explicit
References CProcessInfo::CreateInstance(), CServiceBroker::GetDataCacheCore(), m_playerGUIData, and m_processInfo.
~PAPlayer()
PAPlayer::~PAPlayer () override
References CloseFile().
Member Function Documentation
AdvancePlaylistOnError()
void PAPlayer::AdvancePlaylistOnError (CFileItem & fileItem) private
References IPlayer::m_callback, m_signalStarted, IPlayerCallback::OnAVStarted(), and IPlayerCallback::OnPlayBackStarted().
Referenced by QueueNextFileEx().
CanSeek()
bool PAPlayer::CanSeek () const override virtual
Reimplemented from IPlayer.
References m_playerGUIData.
Referenced by Seek(), and SeekTime().
CloseAllStreams()
void PAPlayer::CloseAllStreams (bool fade = true) private
References CloseFileCB(), CAudioDecoder::Destroy(), fade, m_currentStream, PAPlayer::StreamInfo::m_decoder, m_finishing, PAPlayer::StreamInfo::m_stream, m_streams, m_streamsLock, and SoftStop().
Referenced by CloseFile(), and OpenFile().
CloseFile()
bool PAPlayer::CloseFile (bool reopen = false) override virtual
Implements IPlayer.
References CloseAllStreams(), CServiceBroker::GetActiveAE(), CServiceBroker::GetDataCacheCore(), IAE::KeepConfiguration(), m_isPaused, m_jobCounter, m_jobEvent, m_streamsLock, CDataCacheCore::Reset(), SoftStop(), CThread::StopThread(), and CEvent::Wait().
Referenced by ~PAPlayer().
CloseFileCB()
void PAPlayer::CloseFileCB (StreamInfo & si) private
References CServiceBroker::GetJobManager(), IPlayer::GetPlayerState(), PAPlayer::StreamInfo::m_audioFormat, IPlayer::m_callback, PAPlayer::StreamInfo::m_decoderTotal, PAPlayer::StreamInfo::m_endOffset, PAPlayer::StreamInfo::m_fileItem, PAPlayer::StreamInfo::m_framesSent, IPlayer::m_name, AEAudioFormat::m_sampleRate, PAPlayer::StreamInfo::m_startOffset, PAPlayer::StreamInfo::m_stream, IPlayerCallback::OnPlayerCloseFile(), CBookmark::player, CBookmark::playerState, CJob::PRIORITY_NORMAL, CBookmark::timeInSeconds, and CBookmark::totalTimeInSeconds.
Referenced by CloseAllStreams(), ProcessStream(), and ProcessStreams().
GetAudioCapabilities()
void PAPlayer::GetAudioCapabilities (std::vector< IPlayerAudioCaps > & caps) const inline override virtual
Define the audio capabilities of the player.
Reimplemented from IPlayer.
GetAudioStream()
int PAPlayer::GetAudioStream () inline override virtual
Reimplemented from IPlayer.
GetAudioStreamCount()
int PAPlayer::GetAudioStreamCount () const inline override virtual
Reimplemented from IPlayer.
GetAudioStreamInfo()
void PAPlayer::GetAudioStreamInfo (int index, AudioStreamInfo & info) const override virtual
Reimplemented from IPlayer.
References m_playerGUIData.
GetCacheLevel()
int PAPlayer::GetCacheLevel () const override virtual
Reimplemented from IPlayer.
References m_playerGUIData.
GetPercentage()
float PAPlayer::GetPercentage () protected
References m_playerGUIData.
Referenced by Seek().
GetTimeInternal()
int64_t PAPlayer::GetTimeInternal () private
References CDataCacheCore::GetInstance(), int64_t(), PAPlayer::StreamInfo::m_audioFormat, m_currentStream, PAPlayer::StreamInfo::m_framesSent, m_playerGUIData, AEAudioFormat::m_sampleRate, PAPlayer::StreamInfo::m_stream, m_streamsLock, and CDataCacheCore::SetPlayTimes().
Referenced by Process(), and SeekTime().
GetTotalTime64()
int64_t PAPlayer::GetTotalTime64 () private
References int64_t(), m_currentStream, PAPlayer::StreamInfo::m_decoder, PAPlayer::StreamInfo::m_endOffset, PAPlayer::StreamInfo::m_startOffset, m_streamsLock, and CAudioDecoder::TotalTime().
Referenced by Seek(), and SeekPercentage().
HasAudio()
bool PAPlayer::HasAudio () const inline override virtual
Implements IPlayer.
HasVideo()
bool PAPlayer::HasVideo () const inline override virtual
Implements IPlayer.
IsPlaying()
bool PAPlayer::IsPlaying () const override virtual
Reimplemented from IPlayer.
References m_isPlaying.
OnExit()
void PAPlayer::OnExit () override protected virtual
Reimplemented from CThread.
References CThread::m_bStop, IPlayer::m_callback, m_isFinished, IPlayerCallback::OnPlayBackEnded(), and IPlayerCallback::OnPlayBackStopped().
OnJobComplete()
void PAPlayer::OnJobComplete (unsigned int jobID, bool success, CJob * job) override virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
References m_jobCounter, m_jobEvent, m_streamsLock, and CEvent::Set().
OnNothingToQueueNotify()
void PAPlayer::OnNothingToQueueNotify () override virtual
Reimplemented from IPlayer.
References m_isFinished.
OnStartup()
void PAPlayer::OnStartup () inline override protected virtual
Reimplemented from CThread.
OpenFile()
bool PAPlayer::OpenFile (const CFileItem & file, const CPlayerOptions & options) override virtual
Reimplemented from IPlayer.
References CloseAllStreams(), CThread::Create(), CServiceBroker::GetJobManager(), CServiceBroker::GetSettingsComponent(), CThread::IsRunning(), IPlayer::m_callback, m_defaultCrossfadeMS, PAPlayer::StreamInfo::m_framesSent, m_fullScreen, m_isPaused, m_isPlaying, m_jobCounter, PAPlayer::StreamInfo::m_playNextAtFrame, PAPlayer::StreamInfo::m_prepareTriggered, m_signalStarted, m_startEvent, m_streams, m_streamsLock, m_upcomingCrossfadeMS, MAX_SKIP_XFADE_TIME, IPlayerCallback::OnPlayBackStarted(), CJob::PRIORITY_NORMAL, QueueNextFileEx(), CEvent::Set(), CSettings::SETTING_MUSICPLAYER_CROSSFADE, and CThread::StopThread().
Pause()
void PAPlayer::Pause () override virtual
Implements IPlayer.
References m_isPaused, and SetSpeed().
PrepareStream()
bool PAPlayer::PrepareStream (StreamInfo * si) inline private
References AESTREAM_PAUSED, CServiceBroker::GetActiveAE(), CAudioDecoder::GetReplayGain(), CServiceBroker::GetSettingsComponent(), CAudioDecoder::GetStatus(), CLog::Log(), LOGDEBUG, LOGINFO, PAPlayer::StreamInfo::m_audioFormat, m_currentStream, PAPlayer::StreamInfo::m_decoder, PAPlayer::StreamInfo::m_isSlaved, PAPlayer::StreamInfo::m_stream, m_upcomingCrossfadeMS, PAPlayer::StreamInfo::m_volume, IAE::MakeStream(), PACKET_SIZE, QueueData(), CAudioDecoder::ReadSamples(), RET_ERROR, CSettings::SETTING_MUSICPLAYER_REPLAYGAINAVOIDCLIPPING, CThread::Sleep(), STATUS_ENDED, and STATUS_NO_FILE.
Referenced by QueueNextFileEx().
Process()
void PAPlayer::Process (void) override protected virtual
Reimplemented from CThread.
References GetTimeInternal(), CLog::Log(), LOGDEBUG, CThread::m_bStop, IPlayer::m_callback, m_isPlaying, m_newForcedPlayerTime, m_newForcedTotalTime, m_playbackSpeed, m_signalSpeedChange, m_startEvent, IPlayerCallback::OnPlayBackSpeedChanged(), ProcessStreams(), SetTimeInternal(), SetTotalTimeInternal(), CThread::Sleep(), and CEvent::Wait().
ProcessStream()
bool PAPlayer::ProcessStream (StreamInfo * si, double & freeBufferTime) inline private
References AE_FMT_RAW, CloseFileCB(), CServiceBroker::GetAppMessenger(), CAEStreamInfo::GetDuration(), CDataCacheCore::GetInstance(), CAudioDecoder::GetStatus(), int64_t(), CLog::Log(), LOGINFO, m_audioCallback, PAPlayer::StreamInfo::m_audioFormat, PAPlayer::StreamInfo::m_bytesPerSample, IPlayer::m_callback, m_currentStream, AEAudioFormat::m_dataFormat, PAPlayer::StreamInfo::m_decoder, m_defaultCrossfadeMS, PAPlayer::StreamInfo::m_endOffset, PAPlayer::StreamInfo::m_fileItem, PAPlayer::StreamInfo::m_framesSent, m_fullScreen, PAPlayer::StreamInfo::m_isSlaved, PAPlayer::StreamInfo::m_nextFileItem, m_playbackSpeed, m_playerGUIData, PAPlayer::StreamInfo::m_playNextAtFrame, PAPlayer::StreamInfo::m_playNextTriggered, PAPlayer::StreamInfo::m_prepareNextAtFrame, PAPlayer::StreamInfo::m_prepareTriggered, AEAudioFormat::m_sampleRate, PAPlayer::StreamInfo::m_seekFrame, PAPlayer::StreamInfo::m_seekNextAtFrame, m_signalStarted, PAPlayer::StreamInfo::m_started, PAPlayer::StreamInfo::m_startOffset, PAPlayer::StreamInfo::m_stream, AEAudioFormat::m_streamInfo, m_upcomingCrossfadeMS, IPlayerCallback::OnAVStarted(), IPlayerCallback::OnPlayBackStarted(), PACKET_SIZE, QueueData(), CAudioDecoder::ReadSamples(), RET_ERROR, CAudioDecoder::Seek(), CDataCacheCore::SetPlayTimes(), SetSpeed(), STATUS_ENDED, STATUS_NO_FILE, TIME_TO_CACHE_NEXT_FILE, TMSG_SWITCHTOFULLSCREEN, CAudioDecoder::TotalTime(), UpdateGUIData(), and UpdateStreamInfoPlayNextAtFrame().
Referenced by ProcessStreams().
ProcessStreams()
void PAPlayer::ProcessStreams (double & freeBufferTime) inline private
References CloseFileCB(), CAudioDecoder::Destroy(), CLog::Log(), LOGDEBUG, IPlayer::m_callback, m_currentStream, PAPlayer::StreamInfo::m_decoder, PAPlayer::StreamInfo::m_fadeOutTriggered, m_finishing, PAPlayer::StreamInfo::m_framesSent, m_isFinished, m_isPlaying, PAPlayer::StreamInfo::m_nextFileItem, PAPlayer::StreamInfo::m_playNextAtFrame, PAPlayer::StreamInfo::m_playNextTriggered, PAPlayer::StreamInfo::m_prepareNextAtFrame, PAPlayer::StreamInfo::m_prepareTriggered, PAPlayer::StreamInfo::m_started, PAPlayer::StreamInfo::m_stream, m_streams, m_streamsLock, m_upcomingCrossfadeMS, PAPlayer::StreamInfo::m_waitOnDrain, IPlayerCallback::OnQueueNextItem(), ProcessStream(), and UpdateGUIData().
Referenced by Process().
QueueData()
bool PAPlayer::QueueData (StreamInfo * si) private
References AE_FMT_RAW, CAEChannelInfo::Count(), data(), ICodec::GetCacheLevel(), CAudioDecoder::GetCodec(), CAudioDecoder::GetData(), CAudioDecoder::GetDataSize(), CAEStreamInfo::GetDuration(), CAudioDecoder::GetRawData(), CLog::Log(), LOGERROR, PAPlayer::StreamInfo::m_audioFormat, PAPlayer::StreamInfo::m_bytesPerSample, AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, PAPlayer::StreamInfo::m_decoder, PAPlayer::StreamInfo::m_framesSent, m_playerGUIData, CAEStreamInfo::m_sampleRate, PAPlayer::StreamInfo::m_stream, and AEAudioFormat::m_streamInfo.
Referenced by PrepareStream(), and ProcessStream().
QueueNextFile()
bool PAPlayer::QueueNextFile (const CFileItem & file) override virtual
Reimplemented from IPlayer.
References CServiceBroker::GetJobManager(), m_jobCounter, m_streamsLock, CJob::PRIORITY_NORMAL, and QueueNextFileEx().
QueueNextFileEx()
bool PAPlayer::QueueNextFileEx (const CFileItem & file, bool fadeIn) private
References AdvancePlaylistOnError(), AE_FMT_RAW, CUtil::ConvertMilliSecsToSecs(), CAEChannelInfo::Count(), CAudioDecoder::Create(), CAEUtil::DataFormatToBits(), CAudioDecoder::Destroy(), CAudioDecoder::GetDataSize(), CAudioDecoder::GetFormat(), CAudioDecoder::GetStatus(), int64_t(), KODI::MUSIC::IsCDDA(), CLog::Log(), LOGINFO, LOGWARNING, PAPlayer::StreamInfo::m_audioFormat, PAPlayer::StreamInfo::m_bytesPerFrame, PAPlayer::StreamInfo::m_bytesPerSample, IPlayer::m_callback, AEAudioFormat::m_channelLayout, m_currentStream, AEAudioFormat::m_dataFormat, PAPlayer::StreamInfo::m_decoder, PAPlayer::StreamInfo::m_decoderTotal, m_defaultCrossfadeMS, PAPlayer::StreamInfo::m_endOffset, PAPlayer::StreamInfo::m_fadeOutTriggered, PAPlayer::StreamInfo::m_fileItem, PAPlayer::StreamInfo::m_finishing, PAPlayer::StreamInfo::m_framesSent, PAPlayer::StreamInfo::m_isSlaved, PAPlayer::StreamInfo::m_nextFileItem, PAPlayer::StreamInfo::m_playNextAtFrame, PAPlayer::StreamInfo::m_playNextTriggered, PAPlayer::StreamInfo::m_prepareNextAtFrame, PAPlayer::StreamInfo::m_prepareTriggered, AEAudioFormat::m_sampleRate, PAPlayer::StreamInfo::m_seekFrame, PAPlayer::StreamInfo::m_seekNextAtFrame, PAPlayer::StreamInfo::m_started, PAPlayer::StreamInfo::m_startOffset, PAPlayer::StreamInfo::m_stream, m_streams, m_streamsLock, m_upcomingCrossfadeMS, PAPlayer::StreamInfo::m_volume, PAPlayer::StreamInfo::m_waitOnDrain, IPlayerCallback::OnQueueNextItem(), PACKET_SIZE, PrepareStream(), CAudioDecoder::ReadSamples(), RET_ERROR, CThread::Sleep(), CAudioDecoder::Start(), STATUS_ENDED, STATUS_NO_FILE, TIME_TO_CACHE_NEXT_FILE, CAudioDecoder::TotalTime(), UpdateCrossfadeTime(), and UpdateStreamInfoPlayNextAtFrame().
Referenced by OpenFile(), and QueueNextFile().
Seek()
void PAPlayer::Seek (bool bPlus = true, bool bLargeStep = false, bool bChapterOverride = false) override virtual
Implements IPlayer.
References CanSeek(), GetPercentage(), CServiceBroker::GetSettingsComponent(), GetTotalTime64(), m_playerGUIData, and SeekTime().
SeekPercentage()
void PAPlayer::SeekPercentage (float fPercent = 0.0f) override virtual
Reimplemented from IPlayer.
References GetTotalTime64(), int64_t(), and SeekTime().
SeekTime()
void PAPlayer::SeekTime (int64_t iTime = 0) override virtual
Reimplemented from IPlayer.
References CanSeek(), GetTimeInternal(), int64_t(), PAPlayer::StreamInfo::m_audioFormat, IPlayer::m_callback, m_currentStream, m_playbackSpeed, AEAudioFormat::m_sampleRate, PAPlayer::StreamInfo::m_seekFrame, PAPlayer::StreamInfo::m_startOffset, m_streamsLock, IPlayerCallback::OnPlayBackSeek(), and SetSpeed().
Referenced by Seek(), and SeekPercentage().
SetDynamicRangeCompression()
void PAPlayer::SetDynamicRangeCompression (long drc) override virtual
Reimplemented from IPlayer.
SetSpeed()
void PAPlayer::SetSpeed (float speed = 0) override virtual
Implements IPlayer.
References CDataCacheCore::GetInstance(), IPlayer::m_callback, m_isPaused, m_playbackSpeed, m_signalSpeedChange, IPlayerCallback::OnPlayBackPaused(), IPlayerCallback::OnPlayBackResumed(), CDataCacheCore::SetSpeed(), SoftStart(), and SoftStop().
Referenced by Pause(), ProcessStream(), and SeekTime().
SetTime()
void PAPlayer::SetTime (int64_t time) override virtual
Sets the current time. This can be used for injecting the current time. This is not to be confused with a seek. It just can be used if endless streams contain multiple tracks in reality (like with airtunes)
Reimplemented from IPlayer.
References m_newForcedPlayerTime.
SetTimeInternal()
bool PAPlayer::SetTimeInternal (int64_t time) private
References PAPlayer::StreamInfo::m_audioFormat, m_currentStream, PAPlayer::StreamInfo::m_framesSent, AEAudioFormat::m_sampleRate, PAPlayer::StreamInfo::m_stream, and m_streamsLock.
Referenced by Process().
SetTotalTime()
void PAPlayer::SetTotalTime (int64_t time) override virtual
Set the total time in milliseconds this can be used for injecting the duration in case its not available in the underlaying decoder (airtunes for example)
Reimplemented from IPlayer.
References m_newForcedTotalTime.
SetTotalTimeInternal()
bool PAPlayer::SetTotalTimeInternal (int64_t time) private
References m_currentStream, PAPlayer::StreamInfo::m_decoder, m_streamsLock, CAudioDecoder::SetTotalTime(), and UpdateGUIData().
Referenced by Process().
SetVolume()
void PAPlayer::SetVolume (float volume) override virtual
Reimplemented from IPlayer.
SoftStart()
void PAPlayer::SoftStart (bool wait = false) private
References FAST_XFADE_TIME, PAPlayer::StreamInfo::m_fadeOutTriggered, PAPlayer::StreamInfo::m_stream, m_streams, m_streamsLock, and CThread::Sleep().
Referenced by SetSpeed().
SoftStop()
void PAPlayer::SoftStop (bool wait = false, bool close = true) private
References FAST_XFADE_TIME, CServiceBroker::GetActiveAE(), PAPlayer::StreamInfo::m_fadeOutTriggered, PAPlayer::StreamInfo::m_playNextTriggered, PAPlayer::StreamInfo::m_prepareTriggered, PAPlayer::StreamInfo::m_stream, m_streams, m_streamsLock, and CThread::Sleep().
Referenced by CloseAllStreams(), CloseFile(), and SetSpeed().
UpdateCrossfadeTime()
void PAPlayer::UpdateCrossfadeTime (const CFileItem & file) private
References CServiceBroker::GetSettingsComponent(), KODI::MUSIC::IsCDDA(), m_currentStream, m_defaultCrossfadeMS, PAPlayer::StreamInfo::m_fileItem, m_upcomingCrossfadeMS, CSettings::SETTING_MUSICPLAYER_CROSSFADE, and CSettings::SETTING_MUSICPLAYER_CROSSFADEALBUMTRACKS.
Referenced by QueueNextFileEx().
UpdateGUIData()
void PAPlayer::UpdateGUIData (StreamInfo * si) private
References CAudioDecoder::CanSeek(), CAEChannelInfo::Count(), ICodec::GetCacheLevel(), CAudioDecoder::GetCodec(), CServiceBroker::GetDataCacheCore(), int64_t(), PAPlayer::StreamInfo::m_audioFormat, ICodec::m_bitRate, ICodec::m_bitsPerCodedSample, PAPlayer::StreamInfo::m_bytesPerSample, AEAudioFormat::m_channelLayout, ICodec::m_CodecName, m_currentStream, PAPlayer::StreamInfo::m_decoder, PAPlayer::StreamInfo::m_endOffset, m_playerGUIData, AEAudioFormat::m_sampleRate, PAPlayer::StreamInfo::m_startOffset, m_streamsLock, CDataCacheCore::SignalAudioInfoChange(), and CAudioDecoder::TotalTime().
Referenced by ProcessStream(), ProcessStreams(), and SetTotalTimeInternal().
UpdateStreamInfoPlayNextAtFrame()
void PAPlayer::UpdateStreamInfoPlayNextAtFrame (StreamInfo * si, unsigned int crossFadingTime) private
References int64_t(), PAPlayer::StreamInfo::m_audioFormat, PAPlayer::StreamInfo::m_decoder, PAPlayer::StreamInfo::m_endOffset, PAPlayer::StreamInfo::m_playNextAtFrame, AEAudioFormat::m_sampleRate, PAPlayer::StreamInfo::m_startOffset, and CAudioDecoder::TotalTime().
Referenced by ProcessStream(), and QueueNextFileEx().
Friends And Related Symbol Documentation
CQueueNextFileJob
friend class CQueueNextFileJob friend
Member Data Documentation
m_audioBitrate
int PAPlayer::m_audioBitrate
m_audioCallback
IAudioCallback* PAPlayer::m_audioCallback private
Referenced by ProcessStream().
m_bitsPerSample
int PAPlayer::m_bitsPerSample
m_cacheLevel
int PAPlayer::m_cacheLevel
m_canSeek
bool PAPlayer::m_canSeek
m_channelCount
int PAPlayer::m_channelCount
m_codec
char PAPlayer::m_codec[21]
m_currentStream
StreamInfo* PAPlayer::m_currentStream = nullptr private
Referenced by CloseAllStreams(), GetTimeInternal(), GetTotalTime64(), PrepareStream(), ProcessStream(), ProcessStreams(), QueueNextFileEx(), SeekTime(), SetTimeInternal(), SetTotalTimeInternal(), UpdateCrossfadeTime(), and UpdateGUIData().
m_defaultCrossfadeMS
unsigned int PAPlayer::m_defaultCrossfadeMS = 0 private
Referenced by OpenFile(), ProcessStream(), QueueNextFileEx(), and UpdateCrossfadeTime().
m_finishing
StreamList PAPlayer::m_finishing private
Referenced by CloseAllStreams(), and ProcessStreams().
m_fullScreen
bool PAPlayer::m_fullScreen private
Referenced by OpenFile(), and ProcessStream().
m_isFinished
bool PAPlayer::m_isFinished = false private
Referenced by OnExit(), OnNothingToQueueNotify(), and ProcessStreams().
m_isPaused
bool PAPlayer::m_isPaused = false private
Referenced by CloseFile(), OpenFile(), Pause(), and SetSpeed().
m_isPlaying
bool PAPlayer::m_isPlaying = false private
Referenced by IsPlaying(), OpenFile(), Process(), and ProcessStreams().
m_jobCounter
int PAPlayer::m_jobCounter = 0 private
Referenced by CloseFile(), OnJobComplete(), OpenFile(), and QueueNextFile().
m_jobEvent
CEvent PAPlayer::m_jobEvent private
Referenced by CloseFile(), and OnJobComplete().
m_newForcedPlayerTime
int64_t PAPlayer::m_newForcedPlayerTime = -1 private
Referenced by Process(), and SetTime().
m_newForcedTotalTime
int64_t PAPlayer::m_newForcedTotalTime = -1 private
Referenced by Process(), and SetTotalTime().
m_playbackSpeed
std::atomic_int PAPlayer::m_playbackSpeed private
Referenced by Process(), ProcessStream(), SeekTime(), and SetSpeed().
[struct]
struct { ... } PAPlayer::m_playerGUIData
Referenced by CanSeek(), GetAudioStreamInfo(), GetCacheLevel(), GetPercentage(), GetTimeInternal(), PAPlayer(), ProcessStream(), QueueData(), Seek(), and UpdateGUIData().
m_processInfo
std::unique_ptr<CProcessInfo> PAPlayer::m_processInfo private
Referenced by PAPlayer().
m_sampleRate
int PAPlayer::m_sampleRate
m_signalSpeedChange
bool PAPlayer::m_signalSpeedChange = false private
Referenced by Process(), and SetSpeed().
m_signalStarted
bool PAPlayer::m_signalStarted = true private
Referenced by AdvancePlaylistOnError(), OpenFile(), and ProcessStream().
m_startEvent
CEvent PAPlayer::m_startEvent private
Referenced by OpenFile(), and Process().
m_streams
StreamList PAPlayer::m_streams private
Referenced by CloseAllStreams(), OpenFile(), ProcessStreams(), QueueNextFileEx(), SoftStart(), and SoftStop().
m_streamsLock
CCriticalSection PAPlayer::m_streamsLock private
Referenced by CloseAllStreams(), CloseFile(), GetTimeInternal(), GetTotalTime64(), OnJobComplete(), OpenFile(), ProcessStreams(), QueueNextFile(), QueueNextFileEx(), SeekTime(), SetTimeInternal(), SetTotalTimeInternal(), SoftStart(), SoftStop(), and UpdateGUIData().
m_time
int64_t PAPlayer::m_time
m_totalTime
int64_t PAPlayer::m_totalTime
m_upcomingCrossfadeMS
unsigned int PAPlayer::m_upcomingCrossfadeMS = 0 private
Referenced by OpenFile(), PrepareStream(), ProcessStream(), ProcessStreams(), QueueNextFileEx(), and UpdateCrossfadeTime().
The documentation for this class was generated from the following files:
PAPlayer.h
PAPlayer.cpp