Kodi Documentation: XFILE::CSMBFile Class Reference
XFILE::CSMBFile Class Reference
Public Member Functions
CSMBFile ()
int OpenFile (const CURL &url, std::string &strAuth)
Checks authentication against SAMBA share. Reads password cache created in CSMBDirectory::OpenDir().
~CSMBFile () override
void Close () override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int Stat (struct __stat64 *buffer) override
int Truncate (int64_t size) override
int64_t GetLength () override
int64_t GetPosition () override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
bool Delete (const CURL &url) override
bool Rename (const CURL &url, const CURL &urlnew) override
int GetChunkSize () override
int IoControl (EIoControl request, void *param) override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual double GetDownloadSpeed ()
virtual bool SetHidden (const CURL &url, bool hidden)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Protected Member Functions
bool IsValidFile (const std::string &strFileName)
std::string GetAuthenticatedPath (const CURL &url)
Protected Attributes
CURL m_url
int64_t m_fileSize
int m_fd
bool m_allowRetry
Constructor & Destructor Documentation
CSMBFile()
CSMBFile::CSMBFile ()
References CSMB::AddActiveConnection(), CSMB::Init(), m_allowRetry, m_fd, and smb.
~CSMBFile()
CSMBFile::~CSMBFile () override
References CSMB::AddIdleConnection(), Close(), and smb.
Member Function Documentation
Close()
void CSMBFile::Close () override virtual
Implements XFILE::IFile.
References CSMB::IsSmbValid(), CLog::Log(), LOGDEBUG, m_fd, and smb.
Referenced by Open(), OpenForWrite(), and ~CSMBFile().
Delete()
bool CSMBFile::Delete (const CURL & url) override virtual
Reimplemented from XFILE::IFile.
References GetAuthenticatedPath(), CSMB::GetResolvedUrl(), CSMB::Init(), CSMB::IsSmbValid(), CLog::Log(), LOGERROR, and smb.
Exists()
bool CSMBFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References GetAuthenticatedPath(), CURL::GetFileName(), CSMB::GetResolvedUrl(), CSMB::Init(), CSMB::IsSmbValid(), IsValidFile(), and smb.
GetAuthenticatedPath()
std::string CSMBFile::GetAuthenticatedPath (const CURL & url) protected
References CPasswordManager::AuthenticateURL(), CPasswordManager::GetInstance(), CSMB::GetResolvedUrl(), smb, and CSMB::URLEncode().
Referenced by Delete(), Exists(), OpenFile(), OpenForWrite(), Rename(), and Stat().
GetChunkSize()
int CSMBFile::GetChunkSize () override virtual
Reimplemented from XFILE::IFile.
References CServiceBroker::GetSettingsComponent(), CSettings::SETTING_SMB_CHUNKSIZE, CSettings::SETTING_SMB_MAXPROTOCOL, and CSettings::SETTING_SMB_MINPROTOCOL.
GetLength()
int64_t CSMBFile::GetLength () override virtual
Implements XFILE::IFile.
References m_fd, and m_fileSize.
GetPosition()
int64_t CSMBFile::GetPosition () override virtual
Implements XFILE::IFile.
References CSMB::IsSmbValid(), m_fd, and smb.
IoControl()
int CSMBFile::IoControl (EIoControl request, void * param) override virtual
Reimplemented from XFILE::IFile.
References XFILE::IOCTRL_SEEK_POSSIBLE, XFILE::IOCTRL_SET_RETRY, and m_allowRetry.
IsValidFile()
bool CSMBFile::IsValidFile (const std::string & strFileName) protected
Referenced by Exists(), Open(), and OpenForWrite().
Open()
bool CSMBFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References Close(), CURL::GetFileName(), CURL::GetRedacted(), int64_t(), CSMB::IsSmbValid(), IsValidFile(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_fd, m_fileSize, m_url, OpenFile(), and smb.
OpenFile()
int CSMBFile::OpenFile (const CURL & url, std::string & strAuth)
Checks authentication against SAMBA share. Reads password cache created in CSMBDirectory::OpenDir().
Parameters
strAuth The SMB style path
Returns
SMB file descriptor
References GetAuthenticatedPath(), CSMB::GetResolvedUrl(), CSMB::Init(), CSMB::IsSmbValid(), and smb.
Referenced by Open().
OpenForWrite()
bool CSMBFile::OpenForWrite (const CURL & url, bool bOverWrite = false) override virtual
Reimplemented from XFILE::IFile.
References Close(), GetAuthenticatedPath(), CURL::GetFileName(), CSMB::GetResolvedUrl(), CSMB::IsSmbValid(), IsValidFile(), CLog::Log(), LOGERROR, LOGWARNING, m_fd, m_fileSize, and smb.
Read()
ssize_t CSMBFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References CSMB::IsSmbValid(), CLog::Log(), LOGERROR, m_allowRetry, m_fd, CSMB::SetActivityTime(), smb, and SSIZE_MAX.
Rename()
bool CSMBFile::Rename (const CURL & url, const CURL & urlnew) override virtual
Reimplemented from XFILE::IFile.
References GetAuthenticatedPath(), CSMB::GetResolvedUrl(), CSMB::Init(), CSMB::IsSmbValid(), CLog::Log(), LOGERROR, and smb.
Seek()
int64_t CSMBFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
References int64_t(), CSMB::IsSmbValid(), CLog::Log(), LOGERROR, m_fd, CSMB::SetActivityTime(), and smb.
Stat() [1/2]
int CSMBFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References GetAuthenticatedPath(), CSMB::GetResolvedUrl(), CSMB::Init(), CSMB::IsSmbValid(), smb, and CUtil::StatToStat64().
Stat() [2/2]
int CSMBFile::Stat (struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about currently open file For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Reimplemented from XFILE::IFile.
References CSMB::IsSmbValid(), m_fd, smb, and CUtil::StatToStat64().
Truncate()
int CSMBFile::Truncate (int64_t size) override virtual
Reimplemented from XFILE::IFile.
References CLog::Log(), LOGWARNING, and m_fd.
Write()
ssize_t CSMBFile::Write (const void * bufPtr, size_t bufSize) override virtual
Attempt to write bufSize bytes from buffer bufPtr into currently opened file.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully written bytes if any bytes were written, zero if no bytes were written and no detectable error occur, -1 in case of any explicit error
Reimplemented from XFILE::IFile.
References CSMB::IsSmbValid(), m_fd, and smb.
Member Data Documentation
m_allowRetry
bool XFILE::CSMBFile::m_allowRetry protected
Referenced by CSMBFile(), IoControl(), and Read().
m_fd
int XFILE::CSMBFile::m_fd protected
Referenced by Close(), CSMBFile(), GetLength(), GetPosition(), Open(), OpenForWrite(), Read(), Seek(), Stat(), Truncate(), and Write().
m_fileSize
int64_t XFILE::CSMBFile::m_fileSize protected
Referenced by GetLength(), Open(), and OpenForWrite().
m_url
CURL XFILE::CSMBFile::m_url protected
Referenced by Open().
The documentation for this class was generated from the following files:
SMBFile.h
SMBFile.cpp