Kodi Documentation: CNetworkInterfaceWin32 Class Reference
CNetworkInterfaceWin32 Class Reference
#include <NetworkWin32.h>
Public Member Functions
CNetworkInterfaceWin32 (const IP_ADAPTER_ADDRESSES &adapter)
~CNetworkInterfaceWin32 (void) override
bool IsEnabled (void) const override
bool IsConnected (void) const override
std::string GetMacAddress (void) const override
void GetMacAddressRaw (char rawMac[6]) const override
bool GetHostMacAddress (unsigned long host, std::string &mac) const override
bool GetHostMacAddress (struct sockaddr *host, std::string &mac) const
std::string GetCurrentIPAddress () const override
std::string GetCurrentNetmask () const override
std::string GetCurrentDefaultGateway (void) const override
Public Member Functions inherited from CNetworkInterface
virtual ~CNetworkInterface ()=default
Private Attributes
IP_ADAPTER_ADDRESSES m_adapter
Constructor & Destructor Documentation
CNetworkInterfaceWin32()
CNetworkInterfaceWin32::CNetworkInterfaceWin32 (const IP_ADAPTER_ADDRESSES & adapter)
References m_adapter.
~CNetworkInterfaceWin32()
CNetworkInterfaceWin32::~CNetworkInterfaceWin32 (void) override
Member Function Documentation
GetCurrentDefaultGateway()
std::string CNetworkInterfaceWin32::GetCurrentDefaultGateway (void) const override virtual
Implements CNetworkInterface.
References CNetworkBase::GetIpStr(), and m_adapter.
GetCurrentIPAddress()
std::string CNetworkInterfaceWin32::GetCurrentIPAddress (void) const override virtual
Implements CNetworkInterface.
References CNetworkBase::GetIpStr(), and m_adapter.
GetCurrentNetmask()
std::string CNetworkInterfaceWin32::GetCurrentNetmask (void) const override virtual
Implements CNetworkInterface.
References CNetworkBase::GetMaskByPrefixLength(), and m_adapter.
GetHostMacAddress() [1/2]
bool CNetworkInterfaceWin32::GetHostMacAddress (struct sockaddr * host, std::string & mac) const
References LOGDEBUG, and LOGERROR.
GetHostMacAddress() [2/2]
bool CNetworkInterfaceWin32::GetHostMacAddress (unsigned long host, std::string & mac) const override virtual
Implements CNetworkInterface.
References GetHostMacAddress().
Referenced by GetHostMacAddress().
GetMacAddress()
std::string CNetworkInterfaceWin32::GetMacAddress (void) const override virtual
Implements CNetworkInterface.
References LOGERROR, and m_adapter.
GetMacAddressRaw()
void CNetworkInterfaceWin32::GetMacAddressRaw (char rawMac[6]) const override virtual
Implements CNetworkInterface.
References m_adapter.
IsConnected()
bool CNetworkInterfaceWin32::IsConnected (void) const override virtual
Implements CNetworkInterface.
References m_adapter.
IsEnabled()
bool CNetworkInterfaceWin32::IsEnabled (void) const override virtual
Implements CNetworkInterface.
Member Data Documentation
m_adapter
IP_ADAPTER_ADDRESSES CNetworkInterfaceWin32::m_adapter private
Referenced by CNetworkInterfaceWin32(), GetCurrentDefaultGateway(), GetCurrentIPAddress(), GetCurrentNetmask(), GetMacAddress(), GetMacAddressRaw(), and IsConnected().
The documentation for this class was generated from the following files:
NetworkWin32.h
NetworkWin32.cpp