Kodi Documentation: IStorageProvider Class Reference
IStorageProvider Class Reference abstract
#include <IStorageProvider.h>
Public Member Functions
virtual ~IStorageProvider ()=default
virtual void Initialize ()=0
virtual void Stop ()=0
virtual void GetLocalDrives (std::vector< CMediaSource > &localDrives)=0
virtual void GetRemovableDrives (std::vector< CMediaSource > &removableDrives)=0
virtual std::string GetFirstOpticalDeviceFileName ()
virtual bool Eject (const std::string &mountpath)=0
virtual std::vector< std::string > GetDiskUsage ()=0
virtual bool PumpDriveChangeEvents (IStorageEventsCallback *callback)=0
Static Public Member Functions
static std::unique_ptr< IStorageProvider > CreateInstance ()
Called by media manager to create platform storage provider.
Constructor & Destructor Documentation
~IStorageProvider()
virtual IStorageProvider::~IStorageProvider () virtual default
Member Function Documentation
CreateInstance()
std::unique_ptr< IStorageProvider > IStorageProvider::CreateInstance () static
Called by media manager to create platform storage provider.
This method used to create platform specified storage provider
Referenced by CMediaManager::Initialize().
Eject()
virtual bool IStorageProvider::Eject (const std::string & mountpath) pure virtual
Implemented in CWin32StorageProvider, CAndroidStorageProvider, CIOSStorageProvider, COSXStorageProvider, CLinuxStorageProvider, CUDevProvider, CUDisks2Provider, CUDisksProvider, CPosixMountProvider, and CStorageProvider.
Referenced by CLinuxStorageProvider::Eject().
GetDiskUsage()
virtual std::vector< std::string > IStorageProvider::GetDiskUsage () pure virtual
Implemented in CWin32StorageProvider, CAndroidStorageProvider, COSXStorageProvider, CLinuxStorageProvider, CUDevProvider, CUDisks2Provider, CUDisksProvider, CPosixMountProvider, CStorageProvider, and CIOSStorageProvider.
Referenced by CLinuxStorageProvider::GetDiskUsage().
GetFirstOpticalDeviceFileName()
virtual std::string IStorageProvider::GetFirstOpticalDeviceFileName () inline virtual
Reimplemented in CWin32StorageProvider, and CStorageProvider.
References MEDIA_DETECT::CLibcdio::GetInstance().
GetLocalDrives()
virtual void IStorageProvider::GetLocalDrives (std::vector< CMediaSource > & localDrives) pure virtual
Implemented in CWin32StorageProvider, CAndroidStorageProvider, CIOSStorageProvider, COSXStorageProvider, CLinuxStorageProvider, CUDevProvider, CUDisks2Provider, CUDisksProvider, CPosixMountProvider, and CStorageProvider.
Referenced by CLinuxStorageProvider::GetLocalDrives().
GetRemovableDrives()
virtual void IStorageProvider::GetRemovableDrives (std::vector< CMediaSource > & removableDrives) pure virtual
Implemented in CWin32StorageProvider, CAndroidStorageProvider, CIOSStorageProvider, COSXStorageProvider, CLinuxStorageProvider, CUDevProvider, CUDisks2Provider, CUDisksProvider, CPosixMountProvider, and CStorageProvider.
Referenced by CLinuxStorageProvider::GetRemovableDrives().
Initialize()
virtual void IStorageProvider::Initialize () pure virtual
Implemented in CWin32StorageProvider, CAndroidStorageProvider, CIOSStorageProvider, COSXStorageProvider, CLinuxStorageProvider, CUDevProvider, CUDisks2Provider, CUDisksProvider, CPosixMountProvider, and CStorageProvider.
Referenced by CLinuxStorageProvider::Initialize().
PumpDriveChangeEvents()
virtual bool IStorageProvider::PumpDriveChangeEvents (IStorageEventsCallback * callback) pure virtual
Implemented in CWin32StorageProvider, CAndroidStorageProvider, CIOSStorageProvider, COSXStorageProvider, CLinuxStorageProvider, CUDevProvider, CUDisks2Provider, CUDisksProvider, CPosixMountProvider, and CStorageProvider.
Referenced by CLinuxStorageProvider::PumpDriveChangeEvents().
Stop()
virtual void IStorageProvider::Stop () pure virtual
Implemented in CWin32StorageProvider, CAndroidStorageProvider, CIOSStorageProvider, COSXStorageProvider, CLinuxStorageProvider, CUDevProvider, CUDisks2Provider, CUDisksProvider, CPosixMountProvider, and CStorageProvider.
Referenced by CLinuxStorageProvider::Stop().
The documentation for this class was generated from the following files:
IStorageProvider.h
AndroidStorageProvider.cpp
IOSStorageProvider.mm
OSXStorageProvider.cpp
LinuxStorageProvider.cpp
Win10StorageProvider.cpp
Win32StorageProvider.cpp