Kodi Documentation: CAirTunesServer::AudioOutputFunctions Class Reference
CAirTunesServer::AudioOutputFunctions Class Reference
Static Public Member Functions
static void * audio_init (void *cls, int bits, int channels, int samplerate)
static void audio_set_volume (void *cls, void *session, float volume)
static void audio_set_metadata (void *cls, void *session, const void *buffer, int buflen)
static void audio_set_coverart (void *cls, void *session, const void *buffer, int buflen)
static void audio_process (void *cls, void *session, const void *buffer, int buflen)
static void audio_destroy (void *cls, void *session)
static void audio_remote_control_id (void *cls, const char *identifier, const char *active_remote_header)
static void audio_set_progress (void *cls, void *session, unsigned int start, unsigned int curr, unsigned int end)
Member Function Documentation
audio_destroy()
void CAirTunesServer::AudioOutputFunctions::audio_destroy (void * cls, void * session) static
References XFILE::CPipeFile::Close(), CAirTunesServer::EnableActionProcessing(), CAirTunesServer::FreeDACPRemote(), CServiceBroker::GetAppMessenger(), CZeroconfBrowser::GetInstance(), CAirPlayServer::IsPlaying(), CLog::Log(), LOGDEBUG, CAirTunesServer::m_active_remote_header, CAirTunesServer::m_dacp_id, CAirTunesServer::m_streamStarted, CZeroconfBrowser::RemoveServiceType(), XFILE::CPipeFile::SetEof(), CZeroconfBrowser::Stop(), TMSG_MEDIA_STOP, and ZEROCONF_DACP_SERVICE.
Referenced by CAirTunesServer::Initialize().
audio_init()
void * CAirTunesServer::AudioOutputFunctions::audio_init (void * cls, int bits, int channels, int samplerate) static
References CZeroconfBrowser::AddServiceType(), BXA_PACKET_TYPE_FMT_DEMUX, CAirTunesServer::EnableActionProcessing(), CServiceBroker::GetAppMessenger(), XFILE::PipesManager::GetInstance(), CZeroconfBrowser::GetInstance(), XFILE::CPipeFile::GetName(), CAirTunesServer::m_sampleRate, CAirTunesServer::m_streamStarted, XFILE::CPipeFile::OpenForWrite(), CAirTunesServer::ResetMetadata(), session, CFileItem::SetMimeType(), XFILE::CPipeFile::SetOpenThreshold(), CFileItem::SetPath(), CZeroconfBrowser::Start(), TMSG_MEDIA_PLAY, TMSG_MEDIA_STOP, XFILE::CPipeFile::Write(), and ZEROCONF_DACP_SERVICE.
Referenced by CAirTunesServer::Initialize().
audio_process()
void CAirTunesServer::AudioOutputFunctions::audio_process (void * cls, void * session, const void * buffer, int buflen) static
References CAirTunesServer::InformPlayerAboutPlayTimes(), and XFILE::CPipeFile::Write().
Referenced by CAirTunesServer::Initialize().
audio_remote_control_id()
void CAirTunesServer::AudioOutputFunctions::audio_remote_control_id (void * cls, const char * identifier, const char * active_remote_header) static
References CAirTunesServer::m_active_remote_header, and CAirTunesServer::m_dacp_id.
Referenced by CAirTunesServer::Initialize().
audio_set_coverart()
void CAirTunesServer::AudioOutputFunctions::audio_set_coverart (void * cls, void * session, const void * buffer, int buflen) static
References CAirTunesServer::SetCoverArtFromBuffer().
Referenced by CAirTunesServer::Initialize().
audio_set_metadata()
void CAirTunesServer::AudioOutputFunctions::audio_set_metadata (void * cls, void * session, const void * buffer, int buflen) static
References CAirTunesServer::SetMetadataFromBuffer().
Referenced by CAirTunesServer::Initialize().
audio_set_progress()
void CAirTunesServer::AudioOutputFunctions::audio_set_progress (void * cls, void * session, unsigned int start, unsigned int curr, unsigned int end) static
References end(), CServiceBroker::GetAppComponents(), CAirTunesServer::InformPlayerAboutPlayTimes(), CAirTunesServer::m_cachedCurrentTime, CAirTunesServer::m_cachedEndTime, and CAirTunesServer::m_cachedStartTime.
Referenced by CAirTunesServer::Initialize().
audio_set_volume()
void CAirTunesServer::AudioOutputFunctions::audio_set_volume (void * cls, void * session, float volume) static
References CAirPlayServer::backupVolume(), CServiceBroker::GetAppComponents(), CServiceBroker::GetSettingsComponent(), CSettings::SETTING_SERVICES_AIRPLAYVOLUMECONTROL, and CApplicationVolumeHandling::SetVolume().
Referenced by CAirTunesServer::Initialize().
The documentation for this class was generated from the following files:
AirTunesServer.h
AirTunesServer.cpp