Kodi Documentation: AERingBuffer Class Reference
AERingBuffer Class Reference
#include <AERingBuffer.h>
Public Member Functions
AERingBuffer ()=default
AERingBuffer (unsigned int size, unsigned int planes=1)
~AERingBuffer ()
bool Create (int size, unsigned int planes=1)
void Reset ()
int Write (unsigned char *src, unsigned int size, unsigned int plane=0)
int Read (unsigned char *dest, unsigned int size, unsigned int plane=0)
void Dump ()
unsigned int GetWriteSize ()
unsigned int GetReadSize ()
unsigned int GetMaxSize ()
unsigned int NumPlanes () const
Private Member Functions
void WriteFinished (unsigned int size)
void ReadFinished (unsigned int size)
Private Attributes
unsigned int m_iReadPos = 0
unsigned int m_iWritePos = 0
unsigned int m_iRead = 0
unsigned int m_iWritten = 0
unsigned int m_iSize = 0
unsigned int m_planes = 0
unsigned char ** m_Buffer = nullptr
Detailed Description
This buffer can be used by one read and one write thread at any one time without the risk of data corruption. If you intend to call the Reset() method, please use Locks. All other operations are thread-safe.
Constructor & Destructor Documentation
AERingBuffer() [1/2]
AERingBuffer::AERingBuffer () default
AERingBuffer() [2/2]
AERingBuffer::AERingBuffer (unsigned int size, unsigned int planes = 1) inline
References Create().
~AERingBuffer()
AERingBuffer::~AERingBuffer () inline
References KODI::MEMORY::AlignedFree(), CLog::Log(), LOGDEBUG, m_Buffer, and m_planes.
Member Function Documentation
Create()
bool AERingBuffer::Create (int size, unsigned int planes = 1) inline
Allocates space for buffer, and sets it's contents to 0.
Returns
true on success, false otherwise
References KODI::MEMORY::AlignedMalloc(), m_Buffer, m_iSize, and m_planes.
Referenced by AERingBuffer().
Dump()
void AERingBuffer::Dump () inline
Dumps the buffer.
References KODI::MEMORY::AlignedFree(), KODI::MEMORY::AlignedMalloc(), LOGDEBUG, m_Buffer, m_iReadPos, m_iSize, m_iWritePos, and m_planes.
GetMaxSize()
unsigned int AERingBuffer::GetMaxSize () inline
Returns the buffer size.
References m_iSize.
Referenced by CAAudioUnitSink::buffertime(), CAAudioUnitSink::cacheSize(), CAESinkDARWINOSX::GetCacheTotal(), and CAESinkDARWINOSX::Initialize().
GetReadSize()
unsigned int AERingBuffer::GetReadSize () inline
Returns available space for reading from buffer. Attempt to read more bytes than available results in AE_RING_BUFFER_EMPTY.
References m_iRead, and m_iWritten.
Referenced by CAAudioUnitSink::drain(), CAESinkDARWINOSX::Drain(), CAAudioUnitSink::getDelay(), CAESinkDARWINOSX::GetDelay(), Read(), CAESinkDARWINOSX::renderCallback(), CAAudioUnitSink::renderCallback(), and CAAudioUnitSink::updatedelay().
GetWriteSize()
unsigned int AERingBuffer::GetWriteSize () inline
Returns available space for writing to buffer. Attempt to write more bytes than available results in AE_RING_BUFFER_FULL.
References m_iRead, m_iSize, and m_iWritten.
Referenced by CAESinkDARWINOSX::AddPackets(), CAAudioUnitSink::write(), CAAudioUnitSink::write(), and Write().
NumPlanes()
unsigned int AERingBuffer::NumPlanes () const inline
Returns the number of planes
References m_planes.
Referenced by CAESinkDARWINOSX::AddPackets(), and CAESinkDARWINOSX::renderCallback().
Read()
int AERingBuffer::Read (unsigned char * dest, unsigned int size, unsigned int plane = 0) inline
Reads data from buffer. Attempt to read more bytes than available results in RING_BUFFER_NOTAVAILABLE. Reading from empty buffer returns AE_RING_BUFFER_EMPTY
Returns
AE_RING_BUFFER_OK on success, otherwise an error code
References AE_RING_BUFFER_EMPTY, AE_RING_BUFFER_NOTAVAILABLE, AE_RING_BUFFER_OK, GetReadSize(), CLog::Log(), LOGDEBUG, m_Buffer, m_iReadPos, m_iSize, m_iWritePos, m_planes, and ReadFinished().
Referenced by CAESinkDARWINOSX::renderCallback(), and CAAudioUnitSink::renderCallback().
ReadFinished()
void AERingBuffer::ReadFinished (unsigned int size) inline private
Increments the read pointer. Called at the end of reading to all planes.
References m_iRead, m_iReadPos, and m_iSize.
Referenced by Read().
Reset()
void AERingBuffer::Reset () inline
Fills the buffer with zeros and resets the pointers. This method is not thread-safe, so before using this method please acquire a Lock()
References CLog::Log(), LOGDEBUG, m_iRead, m_iReadPos, m_iWritePos, and m_iWritten.
Write()
int AERingBuffer::Write (unsigned char * src, unsigned int size, unsigned int plane = 0) inline
Writes data to buffer. Attempt to write more bytes than available results in AE_RING_BUFFER_FULL.
Returns
AE_RING_BUFFER_OK on success, otherwise an error code
References AE_RING_BUFFER_FULL, AE_RING_BUFFER_OK, GetWriteSize(), CLog::Log(), LOGDEBUG, m_Buffer, m_iSize, m_iWritePos, m_planes, and WriteFinished().
Referenced by CAESinkDARWINOSX::AddPackets(), CAAudioUnitSink::write(), and CAAudioUnitSink::write().
WriteFinished()
void AERingBuffer::WriteFinished (unsigned int size) inline private
Increments the write pointer. Called at the end of writing to all planes.
References m_iSize, m_iWritePos, and m_iWritten.
Referenced by Write().
Member Data Documentation
m_Buffer
unsigned char** AERingBuffer::m_Buffer = nullptr private
Referenced by Create(), Dump(), Read(), Write(), and ~AERingBuffer().
m_iRead
unsigned int AERingBuffer::m_iRead = 0 private
Referenced by GetReadSize(), GetWriteSize(), ReadFinished(), and Reset().
m_iReadPos
unsigned int AERingBuffer::m_iReadPos = 0 private
Referenced by Dump(), Read(), ReadFinished(), and Reset().
m_iSize
unsigned int AERingBuffer::m_iSize = 0 private
Referenced by Create(), Dump(), GetMaxSize(), GetWriteSize(), Read(), ReadFinished(), Write(), and WriteFinished().
m_iWritePos
unsigned int AERingBuffer::m_iWritePos = 0 private
Referenced by Dump(), Read(), Reset(), Write(), and WriteFinished().
m_iWritten
unsigned int AERingBuffer::m_iWritten = 0 private
Referenced by GetReadSize(), GetWriteSize(), Reset(), and WriteFinished().
m_planes
unsigned int AERingBuffer::m_planes = 0 private
Referenced by Create(), Dump(), NumPlanes(), Read(), Write(), and ~AERingBuffer().
The documentation for this class was generated from the following file:
AERingBuffer.h