Kodi Documentation: CCueDocument Class Reference
CCueDocument Class Reference
#include <CueDocument.h>
Classes
class CCueTrack
Public Member Functions
~CCueDocument (void)
bool ParseFile (const std::string &strFilePath)
bool ParseTag (const std::string &strContent)
void GetSongs (VECSONGS &songs)
std::string GetMediaPath ()
const std::string & GetMediaTitle () const
void GetMediaFiles (std::vector< std::string > &mediaFiles)
void UpdateMediaFile (const std::string &oldMediaFile, const std::string &mediaFile)
bool IsOneFilePerTrack () const
bool IsLoaded () const
bool LoadTracks (CFileItemList &scannedItems, const CFileItem &item)
Private Types
typedef std::vector< CCueTrack > Tracks
Private Member Functions
void Clear ()
bool Parse (CueReader &reader, const std::string &strFile=std::string())
std::string ExtractInfo (const std::string &line)
int ExtractTimeFromIndex (const std::string &index)
int ExtractNumericInfo (const std::string &info)
bool ResolvePath (std::string &strPath, const std::string &strBase)
Private Attributes
std::string m_strArtist
std::string m_strAlbum
std::string m_strGenre
int m_iYear = 0
int m_iTrack = 0
int m_iDiscNumber = 0
ReplayGain::Info m_albumReplayGain
bool m_bOneFilePerTrack = false
Tracks m_tracks
Member Typedef Documentation
Tracks
typedef std::vector<CCueTrack> CCueDocument::Tracks private
Constructor & Destructor Documentation
~CCueDocument()
CCueDocument::~CCueDocument (void) default
Member Function Documentation
Clear()
void CCueDocument::Clear () private
References m_albumReplayGain, m_iDiscNumber, m_iTrack, m_iYear, m_strAlbum, m_strArtist, m_strGenre, and m_tracks.
Referenced by Parse().
ExtractInfo()
std::string CCueDocument::ExtractInfo (const std::string & line) private
References g_charsetConverter, left, right, and text.
Referenced by Parse().
ExtractNumericInfo()
int CCueDocument::ExtractNumericInfo (const std::string & info) private
Referenced by Parse().
ExtractTimeFromIndex()
int CCueDocument::ExtractTimeFromIndex (const std::string & index) private
References CUtil::ConvertSecsToMilliSecs(), and index().
Referenced by Parse().
GetMediaFiles()
void CCueDocument::GetMediaFiles (std::vector< std::string > & mediaFiles)
References m_tracks.
GetMediaPath()
std::string CCueDocument::GetMediaPath ()
GetMediaTitle()
const std::string & CCueDocument::GetMediaTitle () const inline
References m_strAlbum.
GetSongs()
void CCueDocument::GetSongs (VECSONGS & songs)
References ReplayGain::ALBUM, CUtil::ConvertMilliSecsToSecsIntRounded(), CSong::genre, CServiceBroker::GetSettingsComponent(), CSong::iDuration, CSong::iEndOffset, CSong::iStartOffset, CSong::iTrack, m_albumReplayGain, m_iDiscNumber, m_iYear, m_strAlbum, m_strArtist, m_strGenre, m_tracks, CSong::replayGain, ReplayGain::Set(), CSong::SetAlbumArtist(), CSong::strAlbum, CSong::strArtistDesc, CSong::strFileName, CSong::strReleaseDate, CSong::strTitle, ReplayGain::TRACK, and ReplayGain::Info::Valid().
Referenced by LoadTracks().
IsLoaded()
bool CCueDocument::IsLoaded () const
References m_tracks.
IsOneFilePerTrack()
bool CCueDocument::IsOneFilePerTrack () const
References m_bOneFilePerTrack.
Referenced by LoadTracks().
LoadTracks()
bool CCueDocument::LoadTracks (CFileItemList & scannedItems, const CFileItem & item)
References CFileItemList::Add(), CUtil::ConvertMilliSecsToSecsIntRounded(), CUtil::ConvertSecsToMilliSecs(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), GetSongs(), and IsOneFilePerTrack().
Referenced by TEST().
Parse()
bool CCueDocument::Parse (CueReader & reader, const std::string & strFile = std::string()) private
References Clear(), ExtractInfo(), ExtractNumericInfo(), ExtractTimeFromIndex(), CLog::Log(), LOGERROR, m_albumReplayGain, m_bOneFilePerTrack, m_iDiscNumber, m_iTrack, m_iYear, m_strAlbum, m_strArtist, m_strGenre, m_tracks, CueReader::ReadLine(), CueReader::ready(), ResolvePath(), ReplayGain::Info::SetGain(), and ReplayGain::Info::SetPeak().
Referenced by ParseFile(), and ParseTag().
ParseFile()
bool CCueDocument::ParseFile (const std::string & strFilePath)
References Parse().
ParseTag()
bool CCueDocument::ParseTag (const std::string & strContent)
References Parse().
Referenced by TEST().
ResolvePath()
bool CCueDocument::ResolvePath (std::string & strPath, const std::string & strBase) private
References URIUtils::AddFileToFolder(), XFILE::DIR_FLAG_DEFAULTS, XFILE::CFile::Exists(), XFILE::CDirectory::GetDirectory(), URIUtils::GetDirectory(), URIUtils::GetFileName(), CFileItem::GetPath(), CLog::Log(), LOGERROR, and CFileItemList::Size().
Referenced by Parse().
UpdateMediaFile()
void CCueDocument::UpdateMediaFile (const std::string & oldMediaFile, const std::string & mediaFile)
References m_tracks.
Member Data Documentation
m_albumReplayGain
ReplayGain::Info CCueDocument::m_albumReplayGain private
Referenced by Clear(), GetSongs(), and Parse().
m_bOneFilePerTrack
bool CCueDocument::m_bOneFilePerTrack = false private
Referenced by IsOneFilePerTrack(), and Parse().
m_iDiscNumber
int CCueDocument::m_iDiscNumber = 0 private
Referenced by Clear(), GetSongs(), and Parse().
m_iTrack
int CCueDocument::m_iTrack = 0 private
Referenced by Clear(), and Parse().
m_iYear
int CCueDocument::m_iYear = 0 private
Referenced by Clear(), GetSongs(), and Parse().
m_strAlbum
std::string CCueDocument::m_strAlbum private
Referenced by Clear(), GetMediaTitle(), GetSongs(), and Parse().
m_strArtist
std::string CCueDocument::m_strArtist private
Referenced by Clear(), GetSongs(), and Parse().
m_strGenre
std::string CCueDocument::m_strGenre private
Referenced by Clear(), GetSongs(), and Parse().
m_tracks
Tracks CCueDocument::m_tracks private
Referenced by Clear(), GetMediaFiles(), GetSongs(), IsLoaded(), Parse(), and UpdateMediaFile().
The documentation for this class was generated from the following files:
CueDocument.h
CueDocument.cpp