Kodi Documentation: CApplicationActionListeners Class Reference
CApplicationActionListeners Class Reference
Class handling application support for action listeners.
#include <ApplicationActionListeners.h>
Public Member Functions
CApplicationActionListeners (CCriticalSection &sect)
void RegisterActionListener (KODI::ACTION::IActionListener *listener)
Register an action listener.
void UnregisterActionListener (KODI::ACTION::IActionListener *listener)
Unregister an action listener.
Public Member Functions inherited from IApplicationComponent
virtual ~IApplicationComponent ()=default
Protected Member Functions
bool NotifyActionListeners (const CAction &action) const
Delegates the action to all registered action handlers.
Protected Attributes
std::vector< KODI::ACTION::IActionListener * > m_actionListeners
CCriticalSection & m_critSection
Friends
class CApplication
Detailed Description
Class handling application support for action listeners.
Constructor & Destructor Documentation
CApplicationActionListeners()
CApplicationActionListeners::CApplicationActionListeners (CCriticalSection & sect)
Member Function Documentation
NotifyActionListeners()
bool CApplicationActionListeners::NotifyActionListeners (const CAction & action) const protected
Delegates the action to all registered action handlers.
Parameters
action The action
Returns
true, if the action was taken by one of the action listener.
References listener, m_actionListeners, and m_critSection.
RegisterActionListener()
void CApplicationActionListeners::RegisterActionListener (KODI::ACTION::IActionListener * listener)
Register an action listener.
Parameters
listener The listener to register
References listener, m_actionListeners, and m_critSection.
Referenced by PVR::CPVRGUIActionListener::CPVRGUIActionListener(), and CAirTunesServer::RegisterActionListener().
UnregisterActionListener()
void CApplicationActionListeners::UnregisterActionListener (KODI::ACTION::IActionListener * listener)
Unregister an action listener.
Parameters
listener The listener to unregister
References listener, m_actionListeners, and m_critSection.
Referenced by PVR::CPVRGUIActionListener::~CPVRGUIActionListener().
Friends And Related Symbol Documentation
CApplication
friend class CApplication friend
Member Data Documentation
m_actionListeners
std::vector<KODI::ACTION::IActionListener*> CApplicationActionListeners::m_actionListeners protected
Referenced by NotifyActionListeners(), RegisterActionListener(), and UnregisterActionListener().
m_critSection
CCriticalSection& CApplicationActionListeners::m_critSection protected
Referenced by NotifyActionListeners(), RegisterActionListener(), and UnregisterActionListener().
The documentation for this class was generated from the following files:
ApplicationActionListeners.h
ApplicationActionListeners.cpp