Kodi Documentation: dirent.h File Reference
dirent.h File Reference
#include <stdio.h>
#include <stdarg.h>
#include <windef.h>
#include <winbase.h>
#include <wchar.h>
#include <string.h>
#include <stdlib.h>
#include <malloc.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
Classes
struct _wdirent
struct _WDIR
struct dirent
struct DIR
Macros
#define _DIRENT_HAVE_D_TYPE
#define _DIRENT_HAVE_D_NAMLEN
#define FILE_ATTRIBUTE_DEVICE 0x40
#define S_IFMT _S_IFMT /* File type mask */
#define S_IFDIR _S_IFDIR /* Directory */
#define S_IFCHR _S_IFCHR /* Character device */
#define S_IFFIFO _S_IFFIFO /* Pipe */
#define S_IFREG _S_IFREG /* Regular file */
#define S_IREAD _S_IREAD /* Read permission */
#define S_IWRITE _S_IWRITE /* Write permission */
#define S_IEXEC _S_IEXEC /* Execute permission */
#define S_IFIFO _S_IFIFO /* Pipe */
#define S_IFBLK 0 /* Block device */
#define S_IFLNK 0 /* Link */
#define S_IFSOCK 0 /* Socket */
#define PATH_MAX MAX_PATH
#define FILENAME_MAX MAX_PATH
#define NAME_MAX FILENAME_MAX
#define DT_UNKNOWN 0
#define DT_REG S_IFREG
#define DT_DIR S_IFDIR
#define DT_FIFO S_IFIFO
#define DT_SOCK S_IFSOCK
#define DT_CHR S_IFCHR
#define DT_BLK S_IFBLK
#define IFTODT(mode) ((mode) & S_IFMT)
#define DTTOIF(type) (type)
#define S_ISFIFO(mode) (((mode) & S_IFMT) == S_IFIFO)
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#define S_ISREG(mode) (((mode) & S_IFMT) == S_IFREG)
#define S_ISLNK(mode) (((mode) & S_IFMT) == S_IFLNK)
#define S_ISSOCK(mode) (((mode) & S_IFMT) == S_IFSOCK)
#define S_ISCHR(mode) (((mode) & S_IFMT) == S_IFCHR)
#define S_ISBLK(mode) (((mode) & S_IFMT) == S_IFBLK)
#define _D_EXACT_NAMLEN(p) ((p)->d_namlen)
#define _D_ALLOC_NAMLEN(p) (PATH_MAX + 1)
#define wdirent _wdirent
#define WDIR _WDIR
#define wopendir _wopendir
#define wreaddir _wreaddir
#define wclosedir _wclosedir
#define wrewinddir _wrewinddir
Typedefs
typedef struct _wdirent _wdirent
typedef struct _WDIR _WDIR
typedef struct dirent dirent
typedef struct DIR DIR
Functions
static _WDIR * _wopendir (const wchar_t *dirname)
static struct _wdirent * _wreaddir (_WDIR *dirp)
static int _wclosedir (_WDIR *dirp)
static void _wrewinddir (_WDIR *dirp)
static DIR * opendir (const char *dirname)
static struct dirent * readdir (DIR *dirp)
static int closedir (DIR *dirp)
static void rewinddir (DIR *dirp)
static WIN32_FIND_DATAW * dirent_first (_WDIR *dirp)
static WIN32_FIND_DATAW * dirent_next (_WDIR *dirp)
static int dirent_mbstowcs_s (size_t *pReturnValue, wchar_t *wcstr, size_t sizeInWords, const char *mbstr, size_t count)
static int dirent_wcstombs_s (size_t *pReturnValue, char *mbstr, size_t sizeInBytes, const wchar_t *wcstr, size_t count)
static void dirent_set_errno (int error)
Macro Definition Documentation
_D_ALLOC_NAMLEN
#define _D_ALLOC_NAMLEN (p) (PATH_MAX + 1)
_D_EXACT_NAMLEN
#define _D_EXACT_NAMLEN (p) ((p)->d_namlen)
_DIRENT_HAVE_D_NAMLEN
#define _DIRENT_HAVE_D_NAMLEN
_DIRENT_HAVE_D_TYPE
#define _DIRENT_HAVE_D_TYPE
DT_BLK
#define DT_BLK S_IFBLK
DT_CHR
#define DT_CHR S_IFCHR
DT_DIR
#define DT_DIR S_IFDIR
DT_FIFO
#define DT_FIFO S_IFIFO
DT_REG
#define DT_REG S_IFREG
DT_SOCK
#define DT_SOCK S_IFSOCK
DT_UNKNOWN
#define DT_UNKNOWN 0
DTTOIF
#define DTTOIF (type) (type)
FILE_ATTRIBUTE_DEVICE
#define FILE_ATTRIBUTE_DEVICE 0x40
FILENAME_MAX
#define FILENAME_MAX MAX_PATH
IFTODT
#define IFTODT (mode) ((mode) & S_IFMT)
NAME_MAX
#define NAME_MAX FILENAME_MAX
PATH_MAX
#define PATH_MAX MAX_PATH
S_IEXEC
#define S_IEXEC _S_IEXEC /* Execute permission */
S_IFBLK
#define S_IFBLK 0 /* Block device */
S_IFCHR
#define S_IFCHR _S_IFCHR /* Character device */
S_IFDIR
#define S_IFDIR _S_IFDIR /* Directory */
S_IFFIFO
#define S_IFFIFO _S_IFFIFO /* Pipe */
S_IFIFO
#define S_IFIFO _S_IFIFO /* Pipe */
S_IFLNK
#define S_IFLNK 0 /* Link */
S_IFMT
#define S_IFMT _S_IFMT /* File type mask */
S_IFREG
#define S_IFREG _S_IFREG /* Regular file */
S_IFSOCK
#define S_IFSOCK 0 /* Socket */
S_IREAD
#define S_IREAD _S_IREAD /* Read permission */
S_ISBLK
#define S_ISBLK (mode) (((mode) & S_IFMT) == S_IFBLK)
S_ISCHR
#define S_ISCHR (mode) (((mode) & S_IFMT) == S_IFCHR)
S_ISDIR
#define S_ISDIR (mode) (((mode) & S_IFMT) == S_IFDIR)
S_ISFIFO
#define S_ISFIFO (mode) (((mode) & S_IFMT) == S_IFIFO)
S_ISLNK
#define S_ISLNK (mode) (((mode) & S_IFMT) == S_IFLNK)
S_ISREG
#define S_ISREG (mode) (((mode) & S_IFMT) == S_IFREG)
S_ISSOCK
#define S_ISSOCK (mode) (((mode) & S_IFMT) == S_IFSOCK)
S_IWRITE
#define S_IWRITE _S_IWRITE /* Write permission */
wclosedir
#define wclosedir _wclosedir
WDIR
#define WDIR _WDIR
wdirent
#define wdirent _wdirent
wopendir
#define wopendir _wopendir
wreaddir
#define wreaddir _wreaddir
wrewinddir
#define wrewinddir _wrewinddir
Typedef Documentation
_WDIR
typedef struct _WDIR _WDIR
_wdirent
typedef struct _wdirent _wdirent
DIR
typedef struct DIR DIR
dirent
typedef struct dirent dirent
Function Documentation
_wclosedir()
static int _wclosedir (_WDIR * dirp) static
References dirent_set_errno(), _WDIR::handle, INVALID_HANDLE_VALUE, and _WDIR::patt.
Referenced by _wopendir(), and closedir().
_wopendir()
static _WDIR * _wopendir (const wchar_t * dirname) static
References _wclosedir(), _WDIR::cached, dirent_first(), dirent_set_errno(), _WDIR::handle, INVALID_HANDLE_VALUE, and _WDIR::patt.
Referenced by opendir().
_wreaddir()
static struct _wdirent * _wreaddir (_WDIR * dirp) static
References _wdirent::d_ino, _wdirent::d_name, _wdirent::d_namlen, _wdirent::d_reclen, _wdirent::d_type, dirent_next(), DT_CHR, DT_DIR, DT_REG, _WDIR::ent, and FILE_ATTRIBUTE_DEVICE.
_wrewinddir()
static void _wrewinddir (_WDIR * dirp) static
References dirent_first(), _WDIR::handle, and INVALID_HANDLE_VALUE.
Referenced by rewinddir().
closedir()
static int closedir (DIR * dirp) static
References _wclosedir(), dirent_set_errno(), and DIR::wdirp.
Referenced by dll_closedir(), XFILE::CPosixDirectory::GetDirectory(), XFILE::CPosixDirectory::RemoveRecursive(), and CSpecialProtocol::TranslatePathConvertCase().
dirent_first()
static WIN32_FIND_DATAW * dirent_first (_WDIR * dirp) static
References _WDIR::cached, _WDIR::data, _WDIR::handle, INVALID_HANDLE_VALUE, and _WDIR::patt.
Referenced by _wopendir(), and _wrewinddir().
dirent_mbstowcs_s()
static int dirent_mbstowcs_s (size_t * pReturnValue, wchar_t * wcstr, size_t sizeInWords, const char * mbstr, size_t count) static
Referenced by opendir().
dirent_next()
static WIN32_FIND_DATAW * dirent_next (_WDIR * dirp) static
References _WDIR::cached, _WDIR::data, _WDIR::handle, and INVALID_HANDLE_VALUE.
Referenced by _wreaddir(), and readdir().
dirent_set_errno()
static void dirent_set_errno (int error) static
Referenced by _wclosedir(), _wopendir(), closedir(), and opendir().
dirent_wcstombs_s()
static int dirent_wcstombs_s (size_t * pReturnValue, char * mbstr, size_t sizeInBytes, const wchar_t * wcstr, size_t count) static
Referenced by readdir().
opendir()
static DIR * opendir (const char * dirname) static
References _wopendir(), dirent_mbstowcs_s(), dirent_set_errno(), PATH_MAX, and DIR::wdirp.
Referenced by dll_opendir(), XFILE::CPosixDirectory::GetDirectory(), XFILE::CPosixDirectory::RemoveRecursive(), and CSpecialProtocol::TranslatePathConvertCase().
readdir()
static struct dirent * readdir (DIR * dirp) static
References dirent::d_ino, dirent::d_name, dirent::d_namlen, dirent::d_reclen, dirent::d_type, dirent_next(), dirent_wcstombs_s(), DT_CHR, DT_DIR, DT_REG, DT_UNKNOWN, DIR::ent, FILE_ATTRIBUTE_DEVICE, MAX_PATH, and DIR::wdirp.
Referenced by dll_readdir(), XFILE::CPosixDirectory::GetDirectory(), XFILE::CPosixDirectory::RemoveRecursive(), and CSpecialProtocol::TranslatePathConvertCase().
rewinddir()
static void rewinddir (DIR * dirp) static
References _wrewinddir(), and DIR::wdirp.
Referenced by dll_rewinddir().