Kodi Documentation: KODI::GUILIB::GUIINFO::CGUIInfoColor Class Reference
KODI::GUILIB::GUIINFO::CGUIInfoColor Class Reference
#include <GUIInfoColor.h>
Public Member Functions
constexpr CGUIInfoColor (UTILS::COLOR::Color color=0)
constexpr CGUIInfoColor (UTILS::COLOR::Color color, int info)
constexpr operator KODI::UTILS::COLOR::Color () const
bool Update (const CGUIListItem *item=nullptr)
void Parse (const std::string &label, int context)
bool HasInfo () const
Check if the infocolor has an info condition bound to its color definition (or otherwise, if it's constant color)
Private Attributes
int m_info = 0
KODI::UTILS::COLOR::Color m_color
Constructor & Destructor Documentation
CGUIInfoColor() [1/2]
constexpr KODI::GUILIB::GUIINFO::CGUIInfoColor::CGUIInfoColor (UTILS::COLOR::Color color = 0) inline constexpr
CGUIInfoColor() [2/2]
constexpr KODI::GUILIB::GUIINFO::CGUIInfoColor::CGUIInfoColor (UTILS::COLOR::Color color, int info) inline constexpr
Member Function Documentation
HasInfo()
bool KODI::GUILIB::GUIINFO::CGUIInfoColor::HasInfo () const inline
Check if the infocolor has an info condition bound to its color definition (or otherwise, if it's constant color)
Returns
true if the color depends on an info condition, false otherwise
References m_info.
operator KODI::UTILS::COLOR::Color()
constexpr KODI::GUILIB::GUIINFO::CGUIInfoColor::operator KODI::UTILS::COLOR::Color () const inline constexpr
References m_color.
Parse()
void CGUIInfoColor::Parse (const std::string & label, int context)
References g_SkinInfo, CGUIColorManager::GetColor(), CGUIComponent::GetColorManager(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), label, m_color, m_info, CGUIInfoManager::RegisterSkinVariableString(), CGUIInfoManager::TranslateSkinVariableString(), and CGUIInfoManager::TranslateString().
Referenced by CGUIControlFactory::GetTexture().
Update()
bool CGUIInfoColor::Update (const CGUIListItem * item = nullptr)
References color, INFO::DEFAULT_CONTEXT, CGUIColorManager::GetColor(), CGUIComponent::GetColorManager(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetItemLabel(), CGUIInfoManager::GetLabel(), CGUIListItem::IsFileItem(), m_color, and m_info.
Referenced by CGUIWindow::ClearBackground(), CGUITexture::SetDiffuseColor(), CLabelInfo::UpdateColors(), CGUIControl::UpdateColors(), CGUIColorButtonControl::UpdateColors(), and CGUIRSSControl::UpdateColors().
Member Data Documentation
m_color
KODI::UTILS::COLOR::Color KODI::GUILIB::GUIINFO::CGUIInfoColor::m_color private
Referenced by operator KODI::UTILS::COLOR::Color(), Parse(), and Update().
m_info
int KODI::GUILIB::GUIINFO::CGUIInfoColor::m_info = 0 private
Referenced by HasInfo(), Parse(), and Update().
The documentation for this class was generated from the following files:
GUIInfoColor.h
GUIInfoColor.cpp