Kodi Documentation: KODI::WINDOWING::COSScreenSaverInhibitor Class Reference
KODI::WINDOWING::COSScreenSaverInhibitor Class Reference
#include <OSScreenSaver.h>
Public Member Functions
COSScreenSaverInhibitor () noexcept
COSScreenSaverInhibitor (COSScreenSaverInhibitor &&other) noexcept
COSScreenSaverInhibitor & operator= (COSScreenSaverInhibitor &&other) noexcept
~COSScreenSaverInhibitor () noexcept
void Release ()
bool IsActive () const
operator bool () const
Private Member Functions
COSScreenSaverInhibitor (COSScreenSaverManager *manager)
COSScreenSaverInhibitor (COSScreenSaverInhibitor const &other)=delete
COSScreenSaverInhibitor & operator= (COSScreenSaverInhibitor const &other)=delete
Private Attributes
bool m_active
COSScreenSaverManager * m_manager
Friends
class COSScreenSaverManager
Detailed Description
Inhibit the OS screen saver as long as this object is alive
Destroy or call Release to stop this inhibitor from being active. The OS screen saver may still be inhibited as long as other inhibitors are active though.
Note
Make sure to release or destroy the inhibitor before the COSScreenSaverManager is destroyed
Constructor & Destructor Documentation
COSScreenSaverInhibitor() [1/4]
COSScreenSaverInhibitor::COSScreenSaverInhibitor () noexcept
COSScreenSaverInhibitor() [2/4]
COSScreenSaverInhibitor::COSScreenSaverInhibitor (COSScreenSaverInhibitor && other) noexcept
~COSScreenSaverInhibitor()
COSScreenSaverInhibitor::~COSScreenSaverInhibitor () noexcept
References Release().
COSScreenSaverInhibitor() [3/4]
COSScreenSaverInhibitor::COSScreenSaverInhibitor (COSScreenSaverManager * manager) explicit private
COSScreenSaverInhibitor() [4/4]
KODI::WINDOWING::COSScreenSaverInhibitor::COSScreenSaverInhibitor (COSScreenSaverInhibitor const & other) private delete
Member Function Documentation
IsActive()
bool COSScreenSaverInhibitor::IsActive () const
References m_active.
operator bool()
COSScreenSaverInhibitor::operator bool () const
operator=() [1/2]
COSScreenSaverInhibitor & COSScreenSaverInhibitor::operator= (COSScreenSaverInhibitor && other) noexcept
operator=() [2/2]
COSScreenSaverInhibitor & KODI::WINDOWING::COSScreenSaverInhibitor::operator= (COSScreenSaverInhibitor const & other) private delete
Release()
void COSScreenSaverInhibitor::Release ()
References m_active, m_manager, and KODI::WINDOWING::COSScreenSaverManager::RemoveInhibitor().
Referenced by CApplicationPowerHandling::CheckOSScreenSaverInhibitionSetting(), CApplicationPowerHandling::CheckScreenSaverAndDPMS(), and ~COSScreenSaverInhibitor().
Friends And Related Symbol Documentation
COSScreenSaverManager
friend class COSScreenSaverManager friend
Member Data Documentation
m_active
bool KODI::WINDOWING::COSScreenSaverInhibitor::m_active private
Referenced by IsActive(), and Release().
m_manager
COSScreenSaverManager* KODI::WINDOWING::COSScreenSaverInhibitor::m_manager private
Referenced by Release().
The documentation for this class was generated from the following files:
OSScreenSaver.h
OSScreenSaver.cpp