Kodi Documentation: doxygen-header-class-list-creator Namespace Reference
doxygen-header-class-list-creator Namespace Reference
Functions
read_file (name, normalize=True)
write_file (name, data)
auto_check_header (file)
parse_header (file, group, new_path='')
print_error (msg)
Variables
str disc
parser = OptionParser(description=disc)
dest
metavar
help
options
args
str docs = ''
list groups_to_check = []
headers = glob.glob("../include/kodi/**/*.h", recursive=True)
group = auto_check_header(header)
Function Documentation
auto_check_header()
doxygen-header-class-list-creator.auto_check_header (file)
References read_file().
parse_header()
doxygen-header-class-list-creator.parse_header (file, group, new_path = '')
References read_file().
print_error()
doxygen-header-class-list-creator.print_error (msg)
read_file()
doxygen-header-class-list-creator.read_file (name, normalize = True)
 Read a file.
Referenced by auto_check_header(), and parse_header().
write_file()
doxygen-header-class-list-creator.write_file (name, data)
 Write a file.
Variable Documentation
args
doxygen-header-class-list-creator.args
dest
doxygen-header-class-list-creator.dest
disc
str doxygen-header-class-list-creator.disc
Initial value:
=  """
This utility generate group list about addon header sources to add inside doxygen.
"""
docs
str doxygen-header-class-list-creator.docs = ''
group
doxygen-header-class-list-creator.group = auto_check_header(header)
groups_to_check
list doxygen-header-class-list-creator.groups_to_check = []
headers
doxygen-header-class-list-creator.headers = glob.glob("../include/kodi/**/*.h", recursive=True)
help
doxygen-header-class-list-creator.help
metavar
doxygen-header-class-list-creator.metavar
options
doxygen-header-class-list-creator.options
parser
doxygen-header-class-list-creator.parser = OptionParser(description=disc)