Kodi Documentation: TestEndianSwap.cpp File Reference
TestEndianSwap.cpp File Reference
#include "utils/EndianSwap.h"
#include <gtest/gtest.h>
Functions
TEST (TestEndianSwap, Endian_Swap16)
TEST (TestEndianSwap, Endian_Swap32)
TEST (TestEndianSwap, Endian_Swap64)
TEST (TestEndianSwap, Endian_SwapLE16)
TEST (TestEndianSwap, Endian_SwapLE32)
TEST (TestEndianSwap, Endian_SwapLE64)
TEST (TestEndianSwap, Endian_SwapBE16)
TEST (TestEndianSwap, Endian_SwapBE32)
TEST (TestEndianSwap, Endian_SwapBE64)
Function Documentation
TEST() [1/9]
TEST (TestEndianSwap , Endian_Swap16)
References Endian_Swap16(), and EXPECT_EQ().
TEST() [2/9]
TEST (TestEndianSwap , Endian_Swap32)
References Endian_Swap32(), and EXPECT_EQ().
TEST() [3/9]
TEST (TestEndianSwap , Endian_Swap64)
References Endian_Swap64(), and EXPECT_EQ().
TEST() [4/9]
TEST (TestEndianSwap , Endian_SwapBE16)
References Endian_SwapBE16, and EXPECT_EQ().
TEST() [5/9]
TEST (TestEndianSwap , Endian_SwapBE32)
References Endian_SwapBE32, and EXPECT_EQ().
TEST() [6/9]
TEST (TestEndianSwap , Endian_SwapBE64)
References Endian_SwapBE64, and EXPECT_EQ().
TEST() [7/9]
TEST (TestEndianSwap , Endian_SwapLE16)
References Endian_SwapLE16, and EXPECT_EQ().
TEST() [8/9]
TEST (TestEndianSwap , Endian_SwapLE32)
References Endian_SwapLE32, and EXPECT_EQ().
TEST() [9/9]
TEST (TestEndianSwap , Endian_SwapLE64)
References Endian_SwapLE64, and EXPECT_EQ().