Kodi Documentation: CTextureBundleXBT Class Reference
CTextureBundleXBT Class Reference
#include <TextureBundleXBT.h>
Classes
struct Animation
struct Texture
Public Member Functions
CTextureBundleXBT ()
CTextureBundleXBT (bool themeBundle)
~CTextureBundleXBT ()
void SetThemeBundle (bool themeBundle)
bool HasFile (const std::string &Filename)
std::vector< std::string > GetTexturesFromPath (const std::string &path)
std::optional< Texture > LoadTexture (const std::string &filename)
See CTextureBundle::LoadTexture.
std::optional< Animation > LoadAnim (const std::string &filename)
See CTextureBundle::LoadAnim.
void CloseBundle ()
Static Public Member Functions
static std::string Normalize (std::string name)
static std::vector< uint8_t > UnpackFrame (const CXBTFReader &reader, const CXBTFFrame &frame)
Private Member Functions
bool OpenBundle ()
std::unique_ptr< CTexture > ConvertFrameToTexture (const std::string &name, const CXBTFFrame &frame)
Private Attributes
time_t m_TimeStamp
bool m_themeBundle
std::string m_path
std::shared_ptr< CXBTFReader > m_XBTFReader
Constructor & Destructor Documentation
CTextureBundleXBT() [1/2]
CTextureBundleXBT::CTextureBundleXBT ()
CTextureBundleXBT() [2/2]
CTextureBundleXBT::CTextureBundleXBT (bool themeBundle) explicit
~CTextureBundleXBT()
CTextureBundleXBT::~CTextureBundleXBT (void)
References CloseBundle().
Member Function Documentation
CloseBundle()
void CTextureBundleXBT::CloseBundle ()
References CURL, XFILE::CXbtManager::GetInstance(), CLog::Log(), LOGDEBUG, m_path, m_themeBundle, m_XBTFReader, and XFILE::CXbtManager::Release().
Referenced by CTextureBundle::Close(), and ~CTextureBundleXBT().
ConvertFrameToTexture()
std::unique_ptr< CTexture > CTextureBundleXBT::ConvertFrameToTexture (const std::string & name, const CXBTFFrame & frame) private
References CTexture::CreateTexture(), CXBTFFrame::GetFormat(), CXBTFFrame::GetHeight(), CXBTFFrame::GetKDAlpha(), CXBTFFrame::GetKDFormat(), CXBTFFrame::GetKDFormatType(), CXBTFFrame::GetKDSwizzle(), CXBTFFrame::GetPackedSize(), CXBTFFrame::GetUnpackedSize(), CXBTFFrame::GetWidth(), CXBTFFrame::HasAlpha(), CXBTFFrame::IsPacked(), KD_TEX_ALPHA_OPAQUE, KD_TEX_ALPHA_STRAIGHT, KD_TEX_FMT_SDR_BGRA8, KD_TEX_SWIZ_RGBA, CLog::Log(), LOGERROR, m_XBTFReader, name, and XB_FMT_A8R8G8B8.
Referenced by LoadAnim(), and LoadTexture().
GetTexturesFromPath()
std::vector< std::string > CTextureBundleXBT::GetTexturesFromPath (const std::string & path)
References URIUtils::AddSlashAtEnd(), m_XBTFReader, Normalize(), and OpenBundle().
Referenced by CTextureBundle::GetTexturesFromPath().
HasFile()
bool CTextureBundleXBT::HasFile (const std::string & Filename)
References CLog::Log(), LOGINFO, m_TimeStamp, m_XBTFReader, name, Normalize(), and OpenBundle().
Referenced by CTextureBundle::HasFile().
LoadAnim()
std::optional< CTextureBundleXBT::Animation > CTextureBundleXBT::LoadAnim (const std::string & filename)
See CTextureBundle::LoadAnim.
References ConvertFrameToTexture(), CXBTFFrame::GetDuration(), CXBTFFile::GetFrames(), CTextureBundleXBT::Animation::height, CTextureBundleXBT::Animation::loops, m_XBTFReader, name, Normalize(), CTextureBundleXBT::Animation::textures, and CTextureBundleXBT::Animation::width.
Referenced by CTextureBundle::LoadAnim().
LoadTexture()
std::optional< CTextureBundleXBT::Texture > CTextureBundleXBT::LoadTexture (const std::string & filename)
See CTextureBundle::LoadTexture.
References ConvertFrameToTexture(), CXBTFFrame::GetHeight(), CXBTFFrame::GetWidth(), CTextureBundleXBT::Texture::height, m_XBTFReader, name, Normalize(), CTextureBundleXBT::Texture::texture, and CTextureBundleXBT::Texture::width.
Referenced by CTextureBundle::LoadTexture().
Normalize()
std::string CTextureBundleXBT::Normalize (std::string name) static
References name.
Referenced by GetTexturesFromPath(), HasFile(), LoadAnim(), LoadTexture(), and CTextureBundle::Normalize().
OpenBundle()
bool CTextureBundleXBT::OpenBundle () private
References URIUtils::AddFileToFolder(), CURL, XFILE::CXbtManager::GetInstance(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, m_path, m_themeBundle, m_TimeStamp, m_XBTFReader, URIUtils::ReplaceExtension(), CSettings::SETTING_LOOKANDFEEL_SKINTHEME, and CSpecialProtocol::TranslatePathConvertCase().
Referenced by GetTexturesFromPath(), and HasFile().
SetThemeBundle()
void CTextureBundleXBT::SetThemeBundle (bool themeBundle)
References m_themeBundle.
Referenced by CTextureBundle::SetThemeBundle().
UnpackFrame()
std::vector< uint8_t > CTextureBundleXBT::UnpackFrame (const CXBTFReader & reader, const CXBTFFrame & frame) static
Todo:
Change return to std::optional<std::vector<uint8_t>>> when c++17 is allowed
References CXBTFFrame::GetPackedSize(), CXBTFFrame::GetUnpackedSize(), CXBTFFrame::IsPacked(), CXBTFReader::Load(), CLog::Log(), and LOGERROR.
Referenced by XFILE::CXbtFile::Read(), and XFILE::CXbtFile::Seek().
Member Data Documentation
m_path
std::string CTextureBundleXBT::m_path private
Referenced by CloseBundle(), and OpenBundle().
m_themeBundle
bool CTextureBundleXBT::m_themeBundle private
Referenced by CloseBundle(), OpenBundle(), and SetThemeBundle().
m_TimeStamp
time_t CTextureBundleXBT::m_TimeStamp private
Referenced by HasFile(), and OpenBundle().
m_XBTFReader
std::shared_ptr<CXBTFReader> CTextureBundleXBT::m_XBTFReader private
Referenced by CloseBundle(), ConvertFrameToTexture(), GetTexturesFromPath(), HasFile(), LoadAnim(), LoadTexture(), and OpenBundle().
The documentation for this class was generated from the following files:
TextureBundleXBT.h
TextureBundleXBT.cpp