Kodi Documentation: kodi::addon::CInstanceImageDecoder Class Reference
kodi::addon::CInstanceImageDecoder Class Reference abstract
#include <ImageDecoder.h>
Public Member Functions
CInstanceImageDecoder (const IInstanceInfo &instance)
Class constructor.
~CInstanceImageDecoder () override=default
virtual bool SupportsFile (const std::string &filename)
Checks addon support given file path.
virtual bool ReadTag (const std::string &file, kodi::addon::ImageDecoderInfoTag &tag)
Read tag of a file.
virtual bool LoadImageFromMemory (const std::string &mimetype, const uint8_t *buffer, size_t bufSize, unsigned int &width, unsigned int &height)=0
Initialize an encoder.
virtual bool Decode (uint8_t *pixels, unsigned int width, unsigned int height, unsigned int pitch, ADDON_IMG_FMT format)=0
Decode previously loaded image.
Public Member Functions inherited from kodi::addon::IAddonInstance
IAddonInstance (const kodi::addon::IInstanceInfo &instance)
virtual ~IAddonInstance ()=default
virtual ADDON_STATUS CreateInstance (const kodi::addon::IInstanceInfo &instance, KODI_ADDON_INSTANCE_HDL &hdl)
std::string GetInstanceAPIVersion () const
virtual ADDON_STATUS SetInstanceSetting (const std::string &settingName, const kodi::addon::CSettingValue &settingValue)
bool IsInstanceSettingUsingDefault (const std::string &settingName)
std::string GetInstanceUserPath (const std::string &append="")
bool CheckInstanceSettingString (const std::string &settingName, std::string &settingValue)
std::string GetInstanceSettingString (const std::string &settingName, const std::string &defaultValue="")
void SetInstanceSettingString (const std::string &settingName, const std::string &settingValue)
bool CheckInstanceSettingInt (const std::string &settingName, int &settingValue)
int GetInstanceSettingInt (const std::string &settingName, int defaultValue=0)
void SetInstanceSettingInt (const std::string &settingName, int settingValue)
bool CheckInstanceSettingBoolean (const std::string &settingName, bool &settingValue)
bool GetInstanceSettingBoolean (const std::string &settingName, bool defaultValue=false)
void SetInstanceSettingBoolean (const std::string &settingName, bool settingValue)
bool CheckInstanceSettingFloat (const std::string &settingName, float &settingValue)
float GetInstanceSettingFloat (const std::string &settingName, float defaultValue=0.0f)
void SetInstanceSettingFloat (const std::string &settingName, float settingValue)
template<typename enumType >
bool CheckInstanceSettingEnum (const std::string &settingName, enumType &settingValue)
template<typename enumType >
enumType GetInstanceSettingEnum (const std::string &settingName, enumType defaultValue=static_cast< enumType >(0))
template<typename enumType >
void SetInstanceSettingEnum (const std::string &settingName, enumType settingValue)
Private Member Functions
void SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT *instance)
Static Private Member Functions
static bool ADDON_supports_file (const KODI_ADDON_IMAGEDECODER_HDL hdl, const char *file)
static bool ADDON_read_tag (const KODI_ADDON_IMAGEDECODER_HDL hdl, const char *file, struct KODI_ADDON_IMAGEDECODER_INFO_TAG *tag)
static bool ADDON_load_image_from_memory (const KODI_ADDON_IMAGEDECODER_HDL hdl, const char *mimetype, const uint8_t *buffer, size_t bufSize, unsigned int *width, unsigned int *height)
static bool ADDON_decode (const KODI_ADDON_IMAGEDECODER_HDL hdl, uint8_t *pixels, size_t pixels_size, unsigned int width, unsigned int height, unsigned int pitch, enum ADDON_IMG_FMT format)
Constructor & Destructor Documentation
~CInstanceImageDecoder()
kodi::addon::CInstanceImageDecoder::~CInstanceImageDecoder () override default
Member Function Documentation
ADDON_decode()
static bool kodi::addon::CInstanceImageDecoder::ADDON_decode (const KODI_ADDON_IMAGEDECODER_HDL hdl, uint8_t * pixels, size_t pixels_size, unsigned int width, unsigned int height, unsigned int pitch, enum ADDON_IMG_FMT format) inline static private
ADDON_load_image_from_memory()
static bool kodi::addon::CInstanceImageDecoder::ADDON_load_image_from_memory (const KODI_ADDON_IMAGEDECODER_HDL hdl, const char * mimetype, const uint8_t * buffer, size_t bufSize, unsigned int * width, unsigned int * height) inline static private
ADDON_read_tag()
static bool kodi::addon::CInstanceImageDecoder::ADDON_read_tag (const KODI_ADDON_IMAGEDECODER_HDL hdl, const char * file, struct KODI_ADDON_IMAGEDECODER_INFO_TAG * tag) inline static private
References kodi::addon::ImageDecoderInfoTag::GetApertureFNumber(), kodi::addon::ImageDecoderInfoTag::GetAuthor(), kodi::addon::ImageDecoderInfoTag::GetCameraManufacturer(), kodi::addon::ImageDecoderInfoTag::GetCameraModel(), kodi::addon::ImageDecoderInfoTag::GetColor(), kodi::addon::ImageDecoderInfoTag::GetCopyright(), kodi::addon::ImageDecoderInfoTag::GetDescription(), kodi::addon::ImageDecoderInfoTag::GetDigitalZoomRatio(), kodi::addon::ImageDecoderInfoTag::GetDistance(), kodi::addon::ImageDecoderInfoTag::GetExposureBias(), kodi::addon::ImageDecoderInfoTag::GetExposureMode(), kodi::addon::ImageDecoderInfoTag::GetExposureProgram(), kodi::addon::ImageDecoderInfoTag::GetExposureTime(), kodi::addon::ImageDecoderInfoTag::GetFlashUsed(), kodi::addon::ImageDecoderInfoTag::GetFocalLength(), kodi::addon::ImageDecoderInfoTag::GetFocalLengthIn35mmFormat(), kodi::addon::ImageDecoderInfoTag::GetGPSInfo(), kodi::addon::ImageDecoderInfoTag::GetHeight(), kodi::addon::ImageDecoderInfoTag::GetISOSpeed(), kodi::addon::ImageDecoderInfoTag::GetLightSource(), kodi::addon::ImageDecoderInfoTag::GetMeteringMode(), kodi::addon::ImageDecoderInfoTag::GetOrientation(), kodi::addon::ImageDecoderInfoTag::GetTimeCreated(), and kodi::addon::ImageDecoderInfoTag::GetWidth().
ADDON_supports_file()
static bool kodi::addon::CInstanceImageDecoder::ADDON_supports_file (const KODI_ADDON_IMAGEDECODER_HDL hdl, const char * file) inline static private
SetAddonStruct()
void kodi::addon::CInstanceImageDecoder::SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT * instance) inline private
References KodiToAddonFuncTable_ImageDecoder::decode, KODI_ADDON_INSTANCE_STRUCT::hdl, KODI_ADDON_INSTANCE_STRUCT::imagedecoder, KodiToAddonFuncTable_ImageDecoder::load_image_from_memory, KodiToAddonFuncTable_ImageDecoder::read_tag, KodiToAddonFuncTable_ImageDecoder::supports_file, and AddonInstance_ImageDecoder::toAddon.
The documentation for this class was generated from the following file:
kodi-dev-kit/include/kodi/addon-instance/imagedecoder.h