Kodi Documentation: KODI::JOYSTICK::CPrimitiveDetector Class Reference
KODI::JOYSTICK::CPrimitiveDetector Class Reference
Input » Joystick
Detects and dispatches mapping events.
#include <ButtonMapping.h>
Protected Member Functions
CPrimitiveDetector (CButtonMapping *buttonMapping)
bool MapPrimitive (const CDriverPrimitive &primitive)
Dispatch a mapping event.
Private Attributes
CButtonMapping *const m_buttonMapping
Detailed Description
Detects and dispatches mapping events.
A mapping event usually occurs when a driver primitive is pressed or exceeds a certain threshold.
Detection can be quite complicated due to driver bugs, so each type of driver primitive is given its own detector class inheriting from this one.
Constructor & Destructor Documentation
CPrimitiveDetector()
CPrimitiveDetector::CPrimitiveDetector (CButtonMapping * buttonMapping) protected
Member Function Documentation
MapPrimitive()
bool CPrimitiveDetector::MapPrimitive (const CDriverPrimitive & primitive) protected
Dispatch a mapping event.
Returns
True if the primitive was mapped, false otherwise
References KODI::JOYSTICK::CDriverPrimitive::IsValid(), m_buttonMapping, and KODI::JOYSTICK::CButtonMapping::MapPrimitive().
Referenced by KODI::JOYSTICK::CButtonDetector::OnMotion(), KODI::JOYSTICK::CKeyDetector::OnMotion(), KODI::JOYSTICK::CMouseButtonDetector::OnMotion(), KODI::JOYSTICK::CHatDetector::OnMotion(), KODI::JOYSTICK::CPointerDetector::OnMotion(), and KODI::JOYSTICK::CAxisDetector::ProcessMotion().
Member Data Documentation
m_buttonMapping
CButtonMapping* const KODI::JOYSTICK::CPrimitiveDetector::m_buttonMapping private
Referenced by MapPrimitive().
The documentation for this class was generated from the following files:
ButtonMapping.h
ButtonMapping.cpp