Kodi Documentation: CDatabase Class Reference
CDatabase Class Reference abstract
#include <Database.h>
Classes
struct DatasetFieldInfo
class DatasetLayout
class ExistsSubQuery
class Filter
Public Member Functions
CDatabase ()
virtual ~CDatabase (void)
bool IsOpen ()
virtual void Close ()
bool Compress (bool bForce=true)
void Interrupt ()
bool Open (const DatabaseSettings &db)
void BeginTransaction ()
virtual bool CommitTransaction ()
void RollbackTransaction ()
void CopyDB (const std::string &latestDb)
void DropAnalytics ()
std::string PrepareSQL (std::string strStmt,...) const
std::string GetSingleValue (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single value from a table.
std::string GetSingleValue (const std::string &query) const
std::string GetSingleValue (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single value from a query on a dataset.
int GetSingleValueInt (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single integer value from a table.
int GetSingleValueInt (const std::string &query) const
int GetSingleValueInt (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single integer value from a query on a dataset.
bool DeleteValues (const std::string &strTable, const Filter &filter=Filter())
Delete values from a table.
bool ExecuteQuery (const std::string &strQuery)
Execute a query that does not return any result. Note that if BeginMultipleExecute() has been called, the query will be queued until CommitMultipleExecute() is called.
bool ResultQuery (const std::string &strQuery) const
Execute a query that returns a result.
bool BeginMultipleExecute ()
Start a multiple execution queue. Any ExecuteQuery() function following this call will be queued rather than executed until CommitMultipleExecute() is performed. NOTE: Queries that rely on any queued execute query will not function as expected during this period!
bool CommitMultipleExecute ()
Commit the multiple execution queue to the database. Queries are performed within a transaction, and the transaction is rolled back should any one query fail.
bool QueueInsertQuery (const std::string &strQuery)
Put an INSERT or REPLACE query in the queue.
bool CommitInsertQueries ()
Commit all queries in the queue.
size_t GetInsertQueriesCount ()
Get the number of INSERT queries in the queue.
bool QueueDeleteQuery (const std::string &strQuery)
Put a DELETE query in the queue.
bool CommitDeleteQueries ()
Commit all queued DELETE queries.
size_t GetDeleteQueriesCount ()
Get the number of DELETE queries in the queue.
virtual bool GetFilter (CDbUrl &dbUrl, Filter &filter, SortDescription &sorting)
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl)
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl, SortDescription &sorting)
bool Connect (const std::string &dbName, const DatabaseSettings &db, bool create)
Protected Member Functions
void Split (const std::string &strFileNameAndPath, std::string &strPath, std::string &strFileName)
virtual bool Open ()
bool CreateDatabase ()
Create database tables and analytics as needed. Calls CreateTables() and CreateAnalytics() on child classes.
virtual void CreateTables ()=0
virtual void CreateAnalytics ()=0
virtual void UpdateTables (int version)
virtual int GetMinSchemaVersion () const
virtual int GetSchemaVersion () const =0
virtual const char * GetBaseDBName () const =0
int GetDBVersion ()
bool BuildSQL (const std::string &strQuery, const Filter &filter, std::string &strSQL) const
Protected Attributes
bool m_sqlite
whether we use sqlite (defaults to true)
std::unique_ptr< dbiplus::Database > m_pDB
std::unique_ptr< dbiplus::Dataset > m_pDS
std::unique_ptr< dbiplus::Dataset > m_pDS2
const CProfileManager & m_profileManager
Private Member Functions
void InitSettings (DatabaseSettings &dbSettings)
void UpdateVersionNumber ()
Private Attributes
bool m_bMultiInsert
bool m_bMultiDelete
unsigned int m_openCount
bool m_multipleExecute
std::vector< std::string > m_multipleQueries
Friends
class CDatabaseManager
Constructor & Destructor Documentation
CDatabase()
CDatabase::CDatabase ()
References m_multipleExecute, m_openCount, and m_sqlite.
~CDatabase()
CDatabase::~CDatabase (void) virtual
References Close().
Member Function Documentation
BeginMultipleExecute()
bool CDatabase::BeginMultipleExecute ()
Start a multiple execution queue. Any ExecuteQuery() function following this call will be queued rather than executed until CommitMultipleExecute() is performed. NOTE: Queries that rely on any queued execute query will not function as expected during this period!
Returns
true if we could start a multiple execution queue, false otherwise.
See also
CommitMultipleExecute, ExecuteQuery
References m_multipleExecute, and m_multipleQueries.
Referenced by ADDON::CRepositoryUpdateJob::DoWork(), and CMusicDatabase::UpdateArtistSortNames().
BeginTransaction()
void CDatabase::BeginTransaction ()
References CLog::Log(), LOGERROR, and m_pDB.
Referenced by CMusicDatabase::AddAlbum(), CTextureDatabase::AddCachedTexture(), CMusicDatabase::AddSource(), CVideoDatabase::AddVideoAsset(), CVideoDatabase::CleanDatabase(), CommitMultipleExecute(), CVideoDatabase::ConvertVideoToVersion(), CreateDatabase(), CVideoDatabase::DeleteMovie(), CVideoDatabase::DeleteMusicVideo(), CVideoDatabase::DeleteSeason(), CVideoDatabase::DeleteTvShow(), CVideoDatabase::DeleteVideoAsset(), CTextureUseCountJob::DoWork(), CSaveFileState::DoWork(), CMusicDatabase::ImportFromXML(), CMusicDatabase::ImportSongHistory(), CVideoThumbLoader::LoadItemLookup(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMovieSet(), CVideoDatabase::SetDetailsForMusicVideo(), CVideoDatabase::SetDetailsForSeason(), CMusicDatabase::SetScraper(), CMusicDatabase::SetScraperAll(), ADDON::CAddonDatabase::SyncInstalled(), CMusicDatabase::UpdateAlbum(), CVideoDatabase::UpdateDetailsForMovie(), CVideoDatabase::UpdateDetailsForTvShow(), CDatabaseManager::UpdateVersion(), CVideoDatabase::UpdateVideoVersionTypeTable(), CVideoLibraryMarkWatchedJob::Work(), and CVideoLibraryResetResumePointJob::Work().
BuildSQL() [1/3]
bool CDatabase::BuildSQL (const std::string & strBaseDir, const std::string & strQuery, Filter & filter, std::string & strSQL, CDbUrl & dbUrl) virtual
References BuildSQL().
Referenced by CMusicDatabase::AddSource(), BuildSQL(), BuildSQL(), DeleteValues(), CMusicDatabase::ExportToXML(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetCommonNav(), CMusicDatabase::GetDiscsByWhere(), PVR::CPVREpgDatabase::GetEpgTags(), CVideoDatabase::GetEpisodesByWhere(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetGenresNav(), CGUIDialogMediaFilter::GetMinMax(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), CMusicDatabase::GetRandomSongIDs(), CMusicDatabase::GetRolesNav(), CVideoDatabase::GetSeasonsByWhere(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsCount(), CMusicDatabase::GetSongsFullByWhere(), CMusicDatabase::GetSourcesNav(), CTextureDatabase::GetTextures(), CVideoDatabase::GetTvShowsByWhere(), CMusicDatabase::GetYearsNav(), CVideoDatabase::GetYearsNav(), PVR::CPVREpgDatabase::QueueDeleteEpgQuery(), PVR::CPVREpgDatabase::QueueDeleteEpgTags(), PVR::CPVREpgDatabase::QueueDeleteEpgTagsByMinEndMaxStartTimeQuery(), PVR::CPVREpgDatabase::QueueDeleteLastEpgScanTimeQuery(), PVR::CPVRDatabase::QueueDeleteQuery(), PVR::CPVRDatabase::QueueDeleteQuery(), PVR::CPVREpgDatabase::QueueDeleteTagQuery(), and CMusicDatabase::SetScraperAll().
BuildSQL() [2/3]
bool CDatabase::BuildSQL (const std::string & strBaseDir, const std::string & strQuery, Filter & filter, std::string & strSQL, CDbUrl & dbUrl, SortDescription & sorting) virtual
References BuildSQL(), CDbUrl::FromString(), GetFilter(), and CDbUrl::Reset().
BuildSQL() [3/3]
bool CDatabase::BuildSQL (const std::string & strQuery, const Filter & filter, std::string & strSQL) const protected
References CDatabase::Filter::group, CDatabase::Filter::join, CDatabase::Filter::limit, CDatabase::Filter::order, and CDatabase::Filter::where.
Close()
void CDatabase::Close () virtual
Reimplemented in PVR::CPVREpgDatabase, and PVR::CPVRDatabase.
References m_multipleExecute, m_openCount, m_pDB, m_pDS, and m_pDS2.
Referenced by CGUIDialogVideoBookmarks::AddBookmark(), CGUIDialogVideoBookmarks::AddEpisodeBookmark(), CVideoFileItemListModifier::AddQueuingFolder(), CPartyModeManager::AddRandomSongs(), ADDON::CAddonInstaller::CheckDependencies(), CMusicDatabase::Clean(), CGUIDialogVideoBookmarks::ClearBookmarks(), PVR::CPVRThumbLoader::ClearCachedImage(), PVR::CPVREpgDatabase::Close(), PVR::CPVRDatabase::Close(), Connect(), CTextureCache::Deinitialize(), CGUIDialogVideoBookmarks::Delete(), CVideoThumbLoader::DetectAndAddMissingItemData(), ANNOUNCEMENT::CAnnouncementManager::DoAnnounce(), CGUIDialogVideoInfo::DoSearch(), CGetInfoJob::DoWork(), CRefreshInfoJob::DoWork(), CGetSongInfoJob::DoWork(), CSaveFileState::DoWork(), CSetUserratingJob::DoWork(), MUSIC_UTILS::CSetArtJob::DoWork(), MUSIC_UTILS::CSetSongRatingJob::DoWork(), CPartyModeManager::Enable(), ExportLibrary(), ExportLibrary2(), MUSIC_INFO::CMusicInfoScanner::FetchAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::FetchArtistInfo(), MUSIC_UTILS::FillArtTypesList(), CMusicThumbLoader::FillLibraryArt(), CVideoThumbLoader::FillLibraryArt(), anonymous_namespace{GUIDialogVideoInfo.cpp}::GetArtTypesList(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), CThumbLoader::GetCachedImage(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbum::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAddedSong::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayed::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyPlayedSong::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumTop100Song::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeArtist::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSingles::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSong::GetContent(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeSongTop100::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeInProgressTvShows::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeRecentlyAddedMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CMusicSearchDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), JSONRPC::CPlayerOperations::GetItem(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeDiscs::GetLocalizedName(), CGUIDialogMediaFilter::GetMinMax(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), MUSIC_INFO::CMusicInfoTagLoaderDatabase::Load(), CPictureThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), CFileItem::LoadMusicTag(), CGUIDialogVideoInfo::ManageVideoItem(), CApplication::OnAction(), CGUIDialogVideoBookmarks::OnAddEpisodeBookmark(), CGUIWindowMusicBase::OnAssignContent(), CGUIDialogVideoManager::OnDeinitWindow(), CGUIWindowVideoBase::OnItemInfo(), KODI::CDRIP::CCDDARipper::OnJobComplete(), MUSIC_INFO::CMusicInfoLoader::OnLoaderFinish(), CMusicThumbLoader::OnLoaderFinish(), CThumbLoader::OnLoaderFinish(), CVideoThumbLoader::OnLoaderFinish(), CGUIWindowMusicBase::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIWindowVideoBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnPrepareFileItems(), CGUIDialogVideoBookmarks::OnRefreshList(), CGUIWindowMusicBase::OnRemoveSource(), CGUIDialogVideoInfo::OnSearchItemFound(), CMediaSettings::OnSettingAction(), CGUIWindowVideoBase::OnUnAssignContent(), CApplication::PlayFile(), MUSIC_INFO::CMusicInfoScanner::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), CApplicationPlayerCallback::RequestVideoSettings(), PVR::CPVRGUIActionsDatabase::ResetDatabase(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), CGUIDialogAudioSettings::Save(), CGUIDialogSubtitleSettings::Save(), CGUIDialogVideoSettings::Save(), CGUIViewState::SaveViewToDb(), CThumbLoader::SetCachedImage(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), CGUIDialogVideoInfo::SetMovie(), JSONRPC::CVideoLibrary::SetMovieSetDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), JSONRPC::CVideoLibrary::SetSeasonDetails(), CGUIWindowVideoBase::ShowInfo(), KODI::VIDEO::CVideoInfoScanner::Start(), MUSIC_INFO::CMusicInfoScanner::Start(), CApplicationPlayerCallback::StoreVideoSettings(), AddonDatabaseTest::TearDown(), CGUIDialogVideoBookmarks::Update(), CDatabaseManager::Update(), MUSIC_INFO::CMusicInfoScanner::UpdateAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::UpdateArtistInfo(), CRecentlyAddedJob::UpdateMusic(), CRecentlyAddedJob::UpdateTotal(), CRecentlyAddedJob::UpdateVideo(), CVideoLibraryMarkWatchedJob::Work(), CVideoLibraryRefreshingJob::Work(), CVideoLibraryResetResumePointJob::Work(), and ~CDatabase().
CommitDeleteQueries()
bool CDatabase::CommitDeleteQueries ()
Commit all queued DELETE queries.
Returns
True if all queries were executed successfully, false otherwise.
References CLog::Log(), LOGERROR, m_bMultiDelete, and m_pDS.
CommitInsertQueries()
bool CDatabase::CommitInsertQueries ()
Commit all queries in the queue.
Returns
True if all queries were executed successfully, false otherwise.
References CLog::Log(), LOGERROR, m_bMultiInsert, and m_pDS2.
Referenced by PVR::CPVRDatabase::Persist(), PVR::CPVRDatabase::PersistChannels(), and PVR::CPVRDatabase::PersistGroupMembers().
CommitMultipleExecute()
bool CDatabase::CommitMultipleExecute ()
Commit the multiple execution queue to the database. Queries are performed within a transaction, and the transaction is rolled back should any one query fail.
Returns
True if the queries were executed successfully, false otherwise.
See also
BeginMultipleExecute, ExecuteQuery
References BeginTransaction(), CommitTransaction(), ExecuteQuery(), m_multipleExecute, m_multipleQueries, and RollbackTransaction().
Referenced by ADDON::CRepositoryUpdateJob::DoWork(), and CMusicDatabase::UpdateArtistSortNames().
CommitTransaction()
bool CDatabase::CommitTransaction () virtual
Reimplemented in CMusicDatabase, and CVideoDatabase.
References CLog::Log(), LOGERROR, and m_pDB.
Referenced by CTextureDatabase::AddCachedTexture(), CommitMultipleExecute(), CMusicDatabase::CommitTransaction(), CVideoDatabase::CommitTransaction(), CreateDatabase(), CTextureUseCountJob::DoWork(), ADDON::CAddonDatabase::SyncInstalled(), and CDatabaseManager::UpdateVersion().
Compress()
bool CDatabase::Compress (bool bForce = true)
References CLog::Log(), LOGERROR, m_pDB, m_pDS, m_sqlite, MAX_COMPRESS_COUNT, and PrepareSQL().
Referenced by CVideoDatabase::CleanDatabase(), CMusicDatabase::Cleanup(), CMusicDatabase::ImportSongHistory(), MUSIC_INFO::CMusicInfoScanner::Process(), and KODI::VIDEO::CVideoInfoScanner::Process().
Connect()
bool CDatabase::Connect (const std::string & dbName, const DatabaseSettings & db, bool create)
References DatabaseSettings::ca, DatabaseSettings::capath, DatabaseSettings::cert, DatabaseSettings::ciphers, Close(), DatabaseSettings::compression, CreateDatabase(), DB_CONNECTION_OK, dbiplus::DbErrors::getMsg(), DatabaseSettings::host, DatabaseSettings::key, CLog::Log(), LOGERROR, m_openCount, m_pDB, m_pDS, m_pDS2, DatabaseSettings::pass, DatabaseSettings::port, DatabaseSettings::type, and DatabaseSettings::user.
Referenced by Open(), AddonDatabaseTest::SetUp(), and CDatabaseManager::Update().
CopyDB()
void CDatabase::CopyDB (const std::string & latestDb)
References m_pDB.
Referenced by CDatabaseManager::Update().
CreateAnalytics()
virtual void CDatabase::CreateAnalytics () protected pure virtual
Implemented in ADDON::CAddonDatabase, CMusicDatabase, PVR::CPVREpgDatabase, PVR::CPVRDatabase, CTextureDatabase, CVideoDatabase, and CViewDatabase.
Referenced by CreateDatabase(), and CDatabaseManager::UpdateVersion().
CreateDatabase()
bool CDatabase::CreateDatabase () protected
Create database tables and analytics as needed. Calls CreateTables() and CreateAnalytics() on child classes.
References BeginTransaction(), CommitTransaction(), CreateAnalytics(), CreateTables(), GetLastError(), GetSchemaVersion(), CLog::Log(), LOGERROR, LOGINFO, m_pDS, PrepareSQL(), and RollbackTransaction().
Referenced by Connect().
CreateTables()
virtual void CDatabase::CreateTables () protected pure virtual
Implemented in ADDON::CAddonDatabase, CMusicDatabase, PVR::CPVREpgDatabase, PVR::CPVRDatabase, CTextureDatabase, CVideoDatabase, and CViewDatabase.
Referenced by CreateDatabase().
DeleteValues()
bool CDatabase::DeleteValues (const std::string & strTable, const Filter & filter = Filter())
Delete values from a table.
Parameters
strTable The table to delete the values from.
filter The Filter to apply to this query.
Returns
True if the query was executed successfully, false otherwise.
References BuildSQL(), ExecuteQuery(), and PrepareSQL().
Referenced by PVR::CPVRDatabase::Delete(), PVR::CPVRDatabase::Delete(), PVR::CPVREpgDatabase::Delete(), PVR::CPVRDatabase::Delete(), PVR::CPVRDatabase::Delete(), PVR::CPVRDatabase::DeleteChannelGroups(), PVR::CPVRDatabase::DeleteChannels(), PVR::CPVRDatabase::DeleteClients(), PVR::CPVREpgDatabase::DeleteEpg(), PVR::CPVREpgDatabase::DeleteEpgTags(), PVR::CPVREpgDatabase::DeleteEpgTags(), PVR::CPVRDatabase::DeleteProviders(), PVR::CPVREpgDatabase::DeleteSavedSearches(), PVR::CPVRDatabase::DeleteTimers(), and PVR::CPVRDatabase::RemoveChannelsFromGroup().
DropAnalytics()
void CDatabase::DropAnalytics ()
References m_pDB.
Referenced by CDatabaseManager::UpdateVersion().
ExecuteQuery()
bool CDatabase::ExecuteQuery (const std::string & strQuery)
Execute a query that does not return any result. Note that if BeginMultipleExecute() has been called, the query will be queued until CommitMultipleExecute() is called.
Parameters
strQuery The query to execute.
Returns
True if the query was executed successfully, false otherwise.
See also
BeginMultipleExecute, CommitMultipleExecute
References CLog::Log(), LOGERROR, m_multipleExecute, m_multipleQueries, m_pDB, and m_pDS.
Referenced by CMusicDatabase::AddAlbumArtist(), CMusicDatabase::AddAlbumSource(), CMusicDatabase::AddArtistDiscography(), CMusicDatabase::AddAudioBook(), CVideoDatabase::AddLinkToActor(), ADDON::CAddonDatabase::AddPackage(), CVideoDatabase::AddPathToTvShow(), CVideoDatabase::AddSeason(), CMusicDatabase::AddSongArtist(), CMusicDatabase::AddSongGenres(), CVideoDatabase::AddToLinkTable(), CVideoDatabase::AddTvShow(), CMusicDatabase::ClearAlbumLastScrapedTime(), CMusicDatabase::ClearArtistLastScrapedTime(), CommitMultipleExecute(), CVideoDatabase::ConvertVideoToVersion(), CMusicDatabase::DeleteAlbumArtistsByAlbum(), CMusicDatabase::DeleteAlbumSources(), CMusicDatabase::DeleteArtistDiscography(), CMusicDatabase::DeleteArtistVideoLinks(), CVideoDatabase::DeleteSeason(), CMusicDatabase::DeleteSongArtistsBySong(), DeleteValues(), PVR::CPVRDatabase::FixupClientIDs(), PVR::CPVRDatabase::GetClientID(), CTextureDatabase::IncrementUseCount(), CTextureDatabase::InvalidateCachedTexture(), PVR::CPVRDatabase::Persist(), PVR::CPVREpgDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVREpgDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVRDatabase::Persist(), CMusicDatabase::RemoveArtForItem(), CVideoDatabase::RemoveArtForItem(), CVideoDatabase::RemoveFromLinkTable(), ADDON::CAddonDatabase::RemovePackage(), CMusicDatabase::RemoveSource(), PVR::CPVRDatabase::ResetEPG(), CTextureDatabase::SetCachedTextureValid(), CTextureDatabase::SetKeepCachedImages(), CVideoDatabase::SetMovieSet(), CMusicDatabase::SetResumeBookmarkForAudioBook(), CMusicDatabase::UpdateAlbum(), CMusicDatabase::UpdateAlbum(), CMusicDatabase::UpdateArtist(), CMusicDatabase::UpdateArtistScrapedMBID(), CMusicDatabase::UpdateArtistSortNames(), CVideoDatabase::UpdateAssetsOwner(), CVideoDatabase::UpdateDetailsForTvShow(), PVR::CPVRDatabase::UpdateLastOpened(), PVR::CPVRDatabase::UpdateLastWatched(), PVR::CPVRDatabase::UpdateLastWatched(), PVR::CPVREpgDatabase::UpdateSavedSearchLastExecuted(), CMusicDatabase::UpdateSong(), CMusicDatabase::UpdateSources(), and CMusicDatabase::UpdateTables().
GetBaseDBName()
virtual const char * CDatabase::GetBaseDBName () const protected pure virtual
Implemented in ADDON::CAddonDatabase, CMusicDatabase, PVR::CPVREpgDatabase, PVR::CPVRDatabase, CTextureDatabase, CVideoDatabase, and CViewDatabase.
Referenced by InitSettings(), Open(), and CDatabaseManager::UpdateDatabase().
GetDBVersion()
int CDatabase::GetDBVersion () protected
References m_pDS.
Referenced by CDatabaseManager::UpdateVersion().
GetDeleteQueriesCount()
size_t CDatabase::GetDeleteQueriesCount ()
Get the number of DELETE queries in the queue.
Returns
The number of queries.
References m_pDS.
GetFilter()
virtual bool CDatabase::GetFilter (CDbUrl & dbUrl, Filter & filter, SortDescription & sorting) inline virtual
Reimplemented in CMusicDatabase, and CVideoDatabase.
Referenced by BuildSQL().
GetInsertQueriesCount()
size_t CDatabase::GetInsertQueriesCount ()
Get the number of INSERT queries in the queue.
Returns
The number of queries.
References m_pDS2.
GetMinSchemaVersion()
virtual int CDatabase::GetMinSchemaVersion () const inline protected virtual
Reimplemented in ADDON::CAddonDatabase, CMusicDatabase, PVR::CPVREpgDatabase, PVR::CPVRDatabase, and CVideoDatabase.
Referenced by CDatabaseManager::Update(), and CDatabaseManager::UpdateVersion().
GetSchemaVersion()
virtual int CDatabase::GetSchemaVersion () const protected pure virtual
Implemented in ADDON::CAddonDatabase, CMusicDatabase, PVR::CPVREpgDatabase, PVR::CPVRDatabase, CTextureDatabase, CVideoDatabase, and CViewDatabase.
Referenced by CreateDatabase(), Open(), CDatabaseManager::Update(), CDatabaseManager::UpdateVersion(), and UpdateVersionNumber().
GetSingleValue() [1/3]
std::string CDatabase::GetSingleValue (const std::string & query) const
References GetSingleValue(), and m_pDS.
GetSingleValue() [2/3]
std::string CDatabase::GetSingleValue (const std::string & query, const std::unique_ptr< dbiplus::Dataset > & ds) const
Get a single value from a query on a dataset.
Parameters
query the query in question.
ds the dataset to use for the query.
Returns
the value from the query, empty on failure.
References CLog::Log(), LOGERROR, and m_pDB.
GetSingleValue() [3/3]
std::string CDatabase::GetSingleValue (const std::string & strTable, const std::string & strColumn, const std::string & strWhereClause = std::string(), const std::string & strOrderBy = std::string()) const
Get a single value from a table.
Remarks
The values of the strWhereClause and strOrderBy parameters have to be FormatSQL'ed when used.
Parameters
strTable The table to get the value from.
strColumn The column to get.
strWhereClause If set, use this WHERE clause.
strOrderBy If set, use this ORDER BY clause.
Returns
The requested value or an empty string if it wasn't found.
References GetSingleValue(), m_pDS, and PrepareSQL().
Referenced by CMusicDatabase::AddAlbum(), CVideoDatabase::AddLinkToActor(), CVideoDatabase::AddToLinkTable(), CMusicDatabase::CheckSources(), CTextureDatabase::ClearCachedTexture(), CVideoDatabase::DeleteEpisode(), CVideoDatabase::DeleteMovie(), CVideoDatabase::DeleteMusicVideo(), CVideoDatabase::DeleteTvShow(), CVideoDatabase::DeleteVideoAsset(), CMusicDatabase::GetAlbumById(), CMusicDatabase::GetAlbumDiscTitle(), CMusicDatabase::GetAlbumFolder(), CMusicDatabase::GetAlbumsLastAdded(), CMusicDatabase::GetAlbumsLastModified(), CVideoDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtistById(), CMusicDatabase::GetArtistFolderName(), CMusicDatabase::GetArtistLinksUpdated(), CMusicDatabase::GetArtistsLastAdded(), CMusicDatabase::GetArtistsLastModified(), PVR::CPVRDatabase::GetClientID(), CVideoDatabase::GetCountryById(), PVR::CPVRDatabase::GetDateTimeFirstChannelsAdded(), CVideoDatabase::GetDbId(), CVideoDatabase::GetEpisodesByWhere(), PVR::CPVREpgDatabase::GetFirstAndLastEPGDate(), CMusicDatabase::GetGenreById(), CVideoDatabase::GetGenreById(), CMusicDatabase::GetGenresLastAdded(), CMusicDatabase::GetLastArtist(), PVR::CPVREpgDatabase::GetLastEndTime(), PVR::CPVREpgDatabase::GetLastEPGId(), PVR::CPVREpgDatabase::GetLastEpgScanTime(), CMusicDatabase::GetLibraryLastCleaned(), CMusicDatabase::GetLibraryLastUpdated(), PVR::CPVREpgDatabase::GetMaxEndTime(), CGUIDialogMediaFilter::GetMinMax(), PVR::CPVREpgDatabase::GetMinStartTime(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumById(), CVideoDatabase::GetMusicVideosByWhere(), CMusicDatabase::GetOldArtistPath(), ADDON::CAddonDatabase::GetPackageHash(), CVideoDatabase::GetPersonById(), PVR::CPVRDatabase::GetPriority(), CMusicDatabase::GetRoleById(), CVideoDatabase::GetSeasonForEpisode(), CVideoDatabase::GetSeasonId(), CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetSetById(), CVideoDatabase::GetSetByNameLike(), GetSingleValue(), GetSingleValue(), GetSingleValueInt(), CMusicDatabase::GetSongsLastAdded(), CMusicDatabase::GetSongsLastModified(), CMusicDatabase::GetSourceById(), CVideoDatabase::GetStudioById(), CVideoDatabase::GetTagById(), CVideoDatabase::GetTvShowNamedSeasonById(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowTitleById(), CVideoDatabase::GetVideoVersionById(), CMusicDatabase::HasAlbumBeenScraped(), CMusicDatabase::HasArtistBeenScraped(), PVR::CPVREpgDatabase::HasTags(), CMusicDatabase::InsideScannedPath(), CMusicDatabase::IsSongAlbumArtist(), CMusicDatabase::IsSongArtist(), CGUIWindowVideoNav::OnClick(), PVR::CPVRDatabase::Persist(), PVR::CPVRDatabase::PersistChannels(), PVR::CPVRDatabase::PersistGroupMembers(), CMusicDatabase::UpdateAlbum(), CVideoDatabase::UpdateTables(), and CRecentlyAddedJob::UpdateTotal().
GetSingleValueInt() [1/3]
int CDatabase::GetSingleValueInt (const std::string & query) const
References GetSingleValueInt(), and m_pDS.
GetSingleValueInt() [2/3]
int CDatabase::GetSingleValueInt (const std::string & query, const std::unique_ptr< dbiplus::Dataset > & ds) const
Get a single integer value from a query on a dataset.
Parameters
query the query in question.
ds the dataset to use for the query.
Returns
the value from the query, 0 on failure.
References CLog::Log(), LOGERROR, and m_pDB.
GetSingleValueInt() [3/3]
int CDatabase::GetSingleValueInt (const std::string & strTable, const std::string & strColumn, const std::string & strWhereClause = std::string(), const std::string & strOrderBy = std::string()) const
Get a single integer value from a table.
Remarks
The values of the strWhereClause and strOrderBy parameters have to be FormatSQL'ed when used.
Parameters
strTable The table to get the value from.
strColumn The column to get.
strWhereClause If set, use this WHERE clause.
strOrderBy If set, use this ORDER BY clause.
Returns
The requested value or 0 if it wasn't found.
References GetSingleValue().
Referenced by CMusicDatabase::AddAlbum(), CMusicDatabase::CheckArtistLinksChanged(), CMusicDatabase::CheckSources(), CMusicDatabase::CleanupSongs(), PVR::CPVRDatabase::FixupClientIDs(), CMusicDatabase::GetAlbumDiscsCount(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistCountForRole(), CMusicDatabase::GetArtistCountForRole(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetBoxsetsCount(), CMusicDatabase::GetCompilationAlbumsCount(), CMusicDatabase::GetDiscsByWhere(), CMusicDatabase::GetIsAlbumArtist(), PVR::CPVRDatabase::GetMaxProviderId(), GetSingleValueInt(), CMusicDatabase::GetSongByFileName(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsFullByWhere(), CMusicDatabase::ImportSongHistory(), CMusicDatabase::IsAlbumBoxset(), CMusicDatabase::UpdateAlbum(), and CMusicDatabase::UpdateTables().
InitSettings()
void CDatabase::InitSettings (DatabaseSettings & dbSettings) private
References GetBaseDBName(), CProfileManager::GetDatabaseFolder(), DatabaseSettings::host, CLog::Log(), LOGERROR, LOGINFO, m_profileManager, m_sqlite, DatabaseSettings::name, DatabaseSettings::pass, CSpecialProtocol::TranslatePath(), DatabaseSettings::type, and DatabaseSettings::user.
Referenced by Open(), and CDatabaseManager::Update().
Interrupt()
void CDatabase::Interrupt ()
References m_pDS.
Referenced by MUSIC_INFO::CMusicInfoScanner::Stop(), and KODI::VIDEO::CVideoInfoScanner::Stop().
IsOpen()
bool CDatabase::IsOpen ()
References m_openCount.
Referenced by PVR::CPVRRecordings::ChangeRecordingsPlayCount(), PVR::CPVRRecordings::DeleteRecording(), CGUIDialogMediaFilter::GetMinMax(), CTextureCache::Initialize(), CGUIDialogVideoManager::OnInitWindow(), Open(), CGUIDialogVideoManager::Refresh(), PVR::CPVRRecordings::ResetResumePoint(), and PVR::CPVRRecording::UpdateMetadata().
Open() [1/2]
bool CDatabase::Open () protected virtual
Reimplemented in ADDON::CAddonDatabase, CMusicDatabase, PVR::CPVREpgDatabase, PVR::CPVRDatabase, CTextureDatabase, CVideoDatabase, and CViewDatabase.
References Open().
Referenced by Open(), ADDON::CAddonDatabase::Open(), CMusicDatabase::Open(), PVR::CPVREpgDatabase::Open(), PVR::CPVRDatabase::Open(), CTextureDatabase::Open(), CVideoDatabase::Open(), and CViewDatabase::Open().
Open() [2/2]
bool CDatabase::Open (const DatabaseSettings & db)
References Connect(), GetBaseDBName(), CServiceBroker::GetDatabaseManager(), GetSchemaVersion(), InitSettings(), IsOpen(), m_openCount, and DatabaseSettings::name.
PrepareSQL()
std::string CDatabase::PrepareSQL (std::string strStmt, ...) const
References m_pDB.
Referenced by CVideoDatabase::AddActor(), CMusicDatabase::AddAlbum(), CMusicDatabase::AddAlbum(), CMusicDatabase::AddAlbumArtist(), CMusicDatabase::AddAlbumSource(), CMusicDatabase::AddAlbumSources(), CMusicDatabase::AddArtist(), CMusicDatabase::AddArtist(), CMusicDatabase::AddArtistDiscography(), CMusicDatabase::AddArtistVideoLinks(), CMusicDatabase::AddAudioBook(), CVideoDatabase::AddBookMarkForEpisode(), CVideoDatabase::AddBookMarkToFile(), CTextureDatabase::AddCachedTexture(), CVideoDatabase::AddFile(), CMusicDatabase::AddGenre(), ADDON::CAddonDatabase::AddInstalledAddon(), CVideoDatabase::AddLinkToActor(), CVideoDatabase::AddNewEpisode(), CVideoDatabase::AddNewMovie(), CVideoDatabase::AddNewMusicVideo(), ADDON::CAddonDatabase::AddPackage(), CMusicDatabase::AddPath(), CVideoDatabase::AddPath(), CVideoDatabase::AddPathToTvShow(), CVideoDatabase::AddRatings(), CMusicDatabase::AddRole(), CVideoDatabase::AddSeason(), CVideoDatabase::AddSet(), CMusicDatabase::AddSong(), CMusicDatabase::AddSongArtist(), CMusicDatabase::AddSongContributor(), CMusicDatabase::AddSongGenres(), CMusicDatabase::AddSource(), CVideoDatabase::AddToLinkTable(), CVideoDatabase::AddToTable(), CVideoDatabase::AddUniqueIDs(), ADDON::CAddonDatabase::AddUpdateRuleForAddon(), CVideoDatabase::AddVideoAsset(), CVideoDatabase::AddVideoVersionType(), CMusicDatabase::AlphanumericSortSQL(), CVideoDatabase::AppendIdLinkFilter(), CVideoDatabase::AppendLinkFilter(), CMusicDatabase::CheckSources(), CVideoDatabase::CleanDatabase(), CVideoDatabase::CleanMediaType(), CMusicDatabase::CleanupArtists(), CMusicDatabase::CleanupPaths(), CMusicDatabase::CleanupSongs(), CMusicDatabase::CleanupSongsByIds(), CMusicDatabase::ClearAlbumLastScrapedTime(), CMusicDatabase::ClearArtistLastScrapedTime(), CVideoDatabase::ClearBookMarkOfFile(), CVideoDatabase::ClearBookMarksOfFile(), CTextureDatabase::ClearCachedTexture(), CTextureDatabase::ClearCachedTexture(), CTextureDatabase::ClearTextureForPath(), CViewDatabase::ClearViewStates(), Compress(), CVideoDatabase::ConvertVideoToVersion(), CVideoDatabase::CreateAnalytics(), CreateDatabase(), CVideoDatabase::CreateForeignLinkIndex(), CVideoDatabase::CreateLinkIndex(), CMusicDatabase::CreateTables(), CVideoDatabase::CreateViews(), PVR::CPVRDatabase::Delete(), PVR::CPVRDatabase::Delete(), PVR::CPVREpgDatabase::Delete(), PVR::CPVRDatabase::Delete(), PVR::CPVRDatabase::Delete(), CMusicDatabase::DeleteAlbumArtistsByAlbum(), CMusicDatabase::DeleteAlbumSources(), CMusicDatabase::DeleteArtistDiscography(), CMusicDatabase::DeleteArtistVideoLinks(), CVideoDatabase::DeleteBookMarkForEpisode(), CVideoDatabase::DeleteDetailsForTvShow(), PVR::CPVREpgDatabase::DeleteEpgTags(), PVR::CPVREpgDatabase::DeleteEpgTags(), CVideoDatabase::DeleteEpisode(), CVideoDatabase::DeleteMovie(), CVideoDatabase::DeleteMusicVideo(), ADDON::CAddonDatabase::DeleteRepository(), ADDON::CAddonDatabase::DeleteRepositoryContents(), CVideoDatabase::DeleteResumeBookMark(), CVideoDatabase::DeleteSeason(), CVideoDatabase::DeleteSet(), CMusicDatabase::DeleteSongArtistsBySong(), CVideoDatabase::DeleteStreamDetails(), CVideoDatabase::DeleteTag(), CVideoDatabase::DeleteTvShow(), DeleteValues(), CVideoDatabase::DeleteVideoAsset(), ADDON::CAddonDatabase::DisableAddon(), CVideoDatabase::DumpToDummyFiles(), ADDON::CAddonDatabase::EnableAddon(), CVideoDatabase::EraseAllForFile(), CVideoDatabase::EraseAllForPath(), CVideoDatabase::EraseAllVideoSettings(), CVideoDatabase::EraseVideoSettings(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), ADDON::CAddonDatabase::FindByAddonId(), PVR::CPVRDatabase::FixupClientIDs(), CDatabaseQueryRule::FormatParameter(), KODI::PLAYLIST::CSmartPlaylistRule::FormatParameter(), KODI::PLAYLIST::CSmartPlaylistRule::FormatWhereClause(), PVR::CPVRDatabase::Get(), PVR::CPVRDatabase::Get(), PVR::CPVRDatabase::Get(), PVR::CPVRDatabase::Get(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetAddonUpdateRules(), CMusicDatabase::GetAlbum(), CMusicDatabase::GetAlbumById(), CMusicDatabase::GetAlbumByMatch(), CMusicDatabase::GetAlbumByName(), CMusicDatabase::GetAlbumDiscsCount(), CMusicDatabase::GetAlbumDiscTitle(), CMusicDatabase::GetAlbumFolder(), CMusicDatabase::GetAlbumFromSong(), CMusicDatabase::GetAlbumIdByPath(), CMusicDatabase::GetAlbumPaths(), CMusicDatabase::GetAlbumsByArtist(), CMusicDatabase::GetAlbumsByWhereJSON(), PVR::CPVREpgDatabase::GetAll(), PVR::CPVREpgDatabase::GetAllEpgTags(), PVR::CPVREpgDatabase::GetAllIconPaths(), PVR::CPVREpgDatabase::GetAllParentalRatingIconPaths(), CVideoDatabase::GetArtForAsset(), CVideoDatabase::GetArtForItem(), CVideoDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtist(), CMusicDatabase::GetArtistById(), CMusicDatabase::GetArtistByMatch(), CMusicDatabase::GetArtistByName(), CMusicDatabase::GetArtistCountForRole(), CMusicDatabase::GetArtistCountForRole(), CMusicDatabase::GetArtistDiscography(), CMusicDatabase::GetArtistExists(), CMusicDatabase::GetArtistFolderName(), CMusicDatabase::GetArtistFromMBID(), CMusicDatabase::GetArtistFromSong(), CMusicDatabase::GetArtistsByAlbum(), CMusicDatabase::GetArtistsByAlbum(), CMusicDatabase::GetArtistsBySong(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetArtTypes(), CVideoDatabase::GetArtTypes(), CVideoDatabase::GetAssetsForVideo(), CVideoDatabase::GetBookMarkForEpisode(), CVideoDatabase::GetBookMarksForFile(), CTextureDatabase::GetCachedTexture(), CVideoDatabase::GetCast(), PVR::CPVRDatabase::GetClientID(), CMusicDatabase::GetCommonNav(), CVideoDatabase::GetContentForPath(), CVideoDatabase::GetCountryById(), PVR::CPVRDatabase::GetDateTimeFirstChannelsAdded(), CVideoDatabase::GetDefaultVersionForVideo(), CVideoDatabase::GetDefaultVideoVersion(), CVideoDatabase::GetDetailsForMovie(), ADDON::CAddonDatabase::GetDisabled(), CMusicDatabase::GetDiscnumberForPathID(), CMusicDatabase::GetDiscsByWhere(), PVR::CPVREpgDatabase::GetEpgTagByDatabaseID(), PVR::CPVREpgDatabase::GetEpgTagByMaxEndTime(), PVR::CPVREpgDatabase::GetEpgTagByMinStartTime(), PVR::CPVREpgDatabase::GetEpgTagByStartTime(), PVR::CPVREpgDatabase::GetEpgTagByUniqueBroadcastID(), PVR::CPVREpgDatabase::GetEpgTags(), PVR::CPVREpgDatabase::GetEpgTagsByMinEndMaxStartTime(), PVR::CPVREpgDatabase::GetEpgTagsByMinStartMaxEndTime(), CVideoDatabase::GetEpisodeBasicInfo(), CVideoDatabase::GetEpisodeId(), CVideoDatabase::GetEpisodeInfo(), CVideoDatabase::GetEpisodesByActor(), CVideoDatabase::GetEpisodesByFile(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetEpisodesNav(), CVideoDatabase::GetFileBasePathById(), CVideoDatabase::GetFileId(), CVideoDatabase::GetFileIdByMovie(), CVideoDatabase::GetFileInfo(), CVideoDatabase::GetFilePathById(), CMusicDatabase::GetFilter(), CVideoDatabase::GetFilter(), PVR::CPVREpgDatabase::GetFirstAndLastEPGDate(), CMusicDatabase::GetGenreById(), CVideoDatabase::GetGenreById(), CMusicDatabase::GetGenreByName(), CMusicDatabase::GetGenresByAlbum(), CMusicDatabase::GetGenresByArtist(), CMusicDatabase::GetGenresBySong(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetGenresNav(), CMusicDatabase::GetIgnoreArticleSQL(), CVideoDatabase::GetInProgressTvShowsNav(), ADDON::CAddonDatabase::GetInstallData(), CMusicDatabase::GetIsAlbumArtist(), CVideoDatabase::GetItemsForPath(), CGUIDialogVideoInfo::GetItemsForTag(), PVR::CPVREpgDatabase::GetLastEndTime(), PVR::CPVREpgDatabase::GetLastEPGId(), PVR::CPVREpgDatabase::GetLastEpgScanTime(), CVideoDatabase::GetLastPlayed(), CVideoDatabase::GetLinksToTvShow(), PVR::CPVRDatabase::GetLocalGroups(), CVideoDatabase::GetMatchingMusicVideo(), CMusicDatabase::GetMatchingMusicVideoAlbum(), CVideoDatabase::GetMatchingTvShow(), PVR::CPVREpgDatabase::GetMaxEndTime(), PVR::CPVRDatabase::GetMaxProviderId(), CGUIDialogMediaFilter::GetMinMax(), PVR::CPVREpgDatabase::GetMinStartTime(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMovieId(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMoviesByActor(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMovieTitle(), CVideoDatabase::GetMusicVideoAlbumById(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideoId(), CVideoDatabase::GetMusicVideoInfo(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByArtist(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CMusicDatabase::GetOldArtistPath(), CTextureDatabase::GetOldestCachedImages(), CMusicDatabase::GetOrderFilter(), ADDON::CAddonDatabase::GetPackageHash(), CMusicDatabase::GetPathHash(), CVideoDatabase::GetPathHash(), CVideoDatabase::GetPathId(), CVideoDatabase::GetPathsForTvShow(), CVideoDatabase::GetPathsLinkedToTvShow(), CVideoDatabase::GetPeopleNav(), CVideoDatabase::GetPersonById(), CVideoDatabase::GetPlayCount(), CVideoDatabase::GetPlayCounts(), PVR::CPVRDatabase::GetPriority(), CVideoDatabase::GetRandomMusicVideoIDs(), CMusicDatabase::GetRandomSongIDs(), CVideoDatabase::GetRatings(), CMusicDatabase::GetRecentlyAddedAlbums(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), CVideoDatabase::GetRecentlyAddedEpisodesNav(), CVideoDatabase::GetRecentlyAddedMoviesNav(), CVideoDatabase::GetRecentlyAddedMusicVideosNav(), CMusicDatabase::GetRecentlyPlayedAlbums(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), ADDON::CAddonDatabase::GetRepoChecksum(), ADDON::CAddonDatabase::GetRepositoryContent(), ADDON::CAddonDatabase::GetRepositoryId(), ADDON::CAddonDatabase::GetRepoUpdateData(), CMusicDatabase::GetResumeBookmarkForAudioBook(), CVideoDatabase::GetResumePoint(), CMusicDatabase::GetRoleById(), CMusicDatabase::GetRoleByName(), CMusicDatabase::GetRolesByArtist(), CVideoDatabase::GetSameVideoItems(), PVR::CPVREpgDatabase::GetSavedSearchById(), PVR::CPVREpgDatabase::GetSavedSearches(), CMusicDatabase::GetScraper(), CVideoDatabase::GetScraperForPath(), CVideoDatabase::GetSeasonForEpisode(), CVideoDatabase::GetSeasonId(), CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetSeasonsNav(), CVideoDatabase::GetSetById(), CVideoDatabase::GetSetByNameLike(), CVideoDatabase::GetSetInfo(), CMusicDatabase::GetSinglesCount(), GetSingleValue(), CMusicDatabase::GetSong(), CMusicDatabase::GetSongByArtistAndAlbumAndTitle(), CMusicDatabase::GetSongByFileName(), CMusicDatabase::GetSongIDFromPath(), CMusicDatabase::GetSongsByArtist(), CMusicDatabase::GetSongsByPath(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSourceById(), CMusicDatabase::GetSourceByName(), CMusicDatabase::GetSourceFromPath(), CVideoDatabase::GetSourcePath(), CMusicDatabase::GetSourcesByAlbum(), CMusicDatabase::GetSourcesByArtist(), CMusicDatabase::GetSourcesBySong(), CMusicDatabase::GetSourcesNav(), CVideoDatabase::GetStackTimes(), CVideoDatabase::GetStreamDetails(), CVideoDatabase::GetStudioById(), CVideoDatabase::GetSubPaths(), CVideoDatabase::GetTagById(), CVideoDatabase::GetTags(), CTextureDatabase::GetTextureForPath(), CTextureDatabase::GetTextures(), PVR::CPVRDatabase::GetTimers(), CVideoDatabase::GetTvShowForEpisode(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowId(), CVideoDatabase::GetTvShowInfo(), CVideoDatabase::GetTvShowNamedSeasonById(), CVideoDatabase::GetTvShowNamedSeasons(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByActor(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), CVideoDatabase::GetTvShowSeasons(), CVideoDatabase::GetTvShowTitleById(), CVideoDatabase::GetUniqueIDs(), CVideoDatabase::GetUseAllExternalAudioForVideo(), CVideoDatabase::GetUsedImages(), CMusicDatabase::GetUsedImages(), CVideoDatabase::GetValueString(), CVideoDatabase::GetVideoSettings(), CVideoDatabase::GetVideoVersionById(), CVideoDatabase::GetVideoVersionInfo(), CVideoDatabase::GetVideoVersions(), CVideoDatabase::GetVideoVersionsNav(), CVideoDatabase::GetVideoVersionTypes(), CViewDatabase::GetViewState(), CDatabaseQueryRule::GetWhereClause(), CVideoDatabase::GetYearsNav(), CMusicDatabase::HasAlbumBeenScraped(), CVideoDatabase::HasArtForItem(), CMusicDatabase::HasArtistBeenScraped(), PVR::CPVREpgDatabase::HasTags(), CMusicDatabase::ImportSongHistory(), CMusicDatabase::IncrementPlayCount(), CTextureDatabase::IncrementUseCount(), CVideoDatabase::InitializeVideoVersionTypeTable(), CMusicDatabase::InsideScannedPath(), CTextureDatabase::InvalidateCachedTexture(), CMusicDatabase::IsAlbumBoxset(), CVideoDatabase::IsDefaultVideoVersion(), CVideoDatabase::IsLinkedToTvshow(), CMusicDatabase::IsSongAlbumArtist(), CMusicDatabase::IsSongArtist(), CVideoDatabase::LinkMovieToTvshow(), CMusicDatabase::MigrateSources(), CGUIWindowVideoNav::OnClick(), ADDON::CAddonDatabase::OnPostUnInstall(), PVR::CPVRDatabase::Persist(), PVR::CPVREpgDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVREpgDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVRDatabase::PersistChannels(), PVR::CPVRDatabase::PersistGroupMembers(), PVR::CPVREpgDatabase::QueueDeleteEpgQuery(), PVR::CPVREpgDatabase::QueueDeleteEpgTags(), PVR::CPVREpgDatabase::QueueDeleteEpgTagsByMinEndMaxStartTimeQuery(), PVR::CPVREpgDatabase::QueueDeleteLastEpgScanTimeQuery(), PVR::CPVRDatabase::QueueDeleteQuery(), PVR::CPVRDatabase::QueueDeleteQuery(), PVR::CPVREpgDatabase::QueueDeleteTagQuery(), PVR::CPVREpgDatabase::QueuePersistLastEpgScanTimeQuery(), PVR::CPVREpgDatabase::QueuePersistQuery(), CMusicDatabase::RemoveArtForItem(), CVideoDatabase::RemoveArtForItem(), PVR::CPVRDatabase::RemoveChannelsFromGroup(), CVideoDatabase::RemoveContentForPath(), CVideoDatabase::RemoveFromLinkTable(), ADDON::CAddonDatabase::RemovePackage(), CMusicDatabase::RemoveSongsFromPath(), CMusicDatabase::RemoveSource(), CVideoDatabase::RemoveTagsFromItem(), ADDON::CAddonDatabase::RemoveUpdateRuleForAddon(), PVR::CPVRDatabase::ResetEPG(), ResultQuery(), CMusicDatabase::ScraperInUse(), CVideoDatabase::ScraperInUse(), ADDON::CAddonDatabase::Search(), CMusicDatabase::SearchAlbums(), CMusicDatabase::SearchAlbumsByArtistName(), CMusicDatabase::SearchArtists(), CMusicDatabase::SearchSongs(), CMusicDatabase::SetAlbumUserrating(), CVideoDatabase::SetArtForItem(), CMusicDatabase::SetArtForItem(), CMusicDatabase::SetArtistLinksUpdated(), CTextureDatabase::SetCachedTextureValid(), CVideoDatabase::SetDefaultVideoVersion(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMovieSet(), CVideoDatabase::SetDetailsForMusicVideo(), CVideoDatabase::SetDetailsForSeason(), CVideoDatabase::SetFileForEpisode(), CVideoDatabase::SetFileForMovie(), CMusicDatabase::SetItemUpdated(), CTextureDatabase::SetKeepCachedImages(), ADDON::CAddonDatabase::SetLastUpdated(), ADDON::CAddonDatabase::SetLastUsed(), CMusicDatabase::SetLibraryLastCleaned(), CMusicDatabase::SetLibraryLastUpdated(), CVideoDatabase::SetMovieSet(), CMusicDatabase::SetMusicNeedsTagScan(), CMusicDatabase::SetMusicTagScanVersion(), ADDON::CAddonDatabase::SetOrigin(), CMusicDatabase::SetPathHash(), CVideoDatabase::SetPathHash(), CVideoDatabase::SetPlayCount(), ADDON::CAddonDatabase::SetRepoUpdateData(), CMusicDatabase::SetResumeBookmarkForAudioBook(), CMusicDatabase::SetScraper(), CMusicDatabase::SetScraperAll(), CVideoDatabase::SetScraperForPath(), CVideoDatabase::SetSingleValue(), CMusicDatabase::SetSongUserrating(), CMusicDatabase::SetSongVotes(), CVideoDatabase::SetStackTimes(), CVideoDatabase::SetStreamDetailsForFileId(), CTextureDatabase::SetTextureForPath(), CVideoDatabase::SetVideoSettings(), CVideoDatabase::SetVideoUserRating(), CVideoDatabase::SetVideoVersion(), CViewDatabase::SetViewState(), CMusicDatabase::SortnameBuildSQL(), ADDON::CAddonDatabase::SyncInstalled(), CVideoDatabase::UpdateActorLinksToItem(), CMusicDatabase::UpdateAlbum(), CMusicDatabase::UpdateAlbum(), CMusicDatabase::UpdateArtist(), CMusicDatabase::UpdateArtistScrapedMBID(), CMusicDatabase::UpdateArtistSortNames(), CVideoDatabase::UpdateAssetsOwner(), CVideoDatabase::UpdateDetailsForMovie(), CVideoDatabase::UpdateDetailsForTvShow(), CVideoDatabase::UpdateFanart(), CVideoDatabase::UpdateFileDateAdded(), PVR::CPVRDatabase::UpdateLastOpened(), PVR::CPVRDatabase::UpdateLastWatched(), PVR::CPVRDatabase::UpdateLastWatched(), CVideoDatabase::UpdateLinksToItem(), CVideoDatabase::UpdateMovieTitle(), CVideoDatabase::UpdateRatings(), ADDON::CAddonDatabase::UpdateRepositoryContent(), PVR::CPVREpgDatabase::UpdateSavedSearchLastExecuted(), CMusicDatabase::UpdateSong(), CMusicDatabase::UpdateSource(), ADDON::CAddonDatabase::UpdateTables(), CMusicDatabase::UpdateTables(), CTextureDatabase::UpdateTables(), CVideoDatabase::UpdateTables(), CViewDatabase::UpdateTables(), CVideoDatabase::UpdateUniqueIDs(), UpdateVersionNumber(), and CVideoDatabase::UpdateVideoVersionTypeTable().
QueueDeleteQuery()
bool CDatabase::QueueDeleteQuery (const std::string & strQuery)
Put a DELETE query in the queue.
Parameters
strQuery The query to queue.
Returns
True if the query was added successfully, false otherwise.
References m_bMultiDelete, m_pDB, and m_pDS.
Referenced by PVR::CPVREpgDatabase::QueueDeleteEpgQuery(), PVR::CPVREpgDatabase::QueueDeleteEpgTags(), PVR::CPVREpgDatabase::QueueDeleteEpgTagsByMinEndMaxStartTimeQuery(), PVR::CPVREpgDatabase::QueueDeleteLastEpgScanTimeQuery(), PVR::CPVRDatabase::QueueDeleteQuery(), PVR::CPVRDatabase::QueueDeleteQuery(), and PVR::CPVREpgDatabase::QueueDeleteTagQuery().
QueueInsertQuery()
bool CDatabase::QueueInsertQuery (const std::string & strQuery)
Put an INSERT or REPLACE query in the queue.
Parameters
strQuery The query to queue.
Returns
True if the query was added successfully, false otherwise.
References m_bMultiInsert, m_pDB, and m_pDS2.
Referenced by PVR::CPVREpgDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVRDatabase::PersistGroupMembers(), PVR::CPVREpgDatabase::QueuePersistLastEpgScanTimeQuery(), and PVR::CPVREpgDatabase::QueuePersistQuery().
ResultQuery()
bool CDatabase::ResultQuery (const std::string & strQuery) const
Execute a query that returns a result.
Remarks
Call m_pDS->close(); to clean up the dataset when done.
Parameters
strQuery The query to execute.
Returns
True if the query was executed successfully, false otherwise.
References CLog::Log(), LOGERROR, m_pDB, m_pDS, and PrepareSQL().
Referenced by PVR::CPVRDatabase::FixupClientIDs(), PVR::CPVRDatabase::Get(), PVR::CPVRDatabase::Get(), PVR::CPVRDatabase::Get(), PVR::CPVREpgDatabase::GetAll(), PVR::CPVREpgDatabase::GetAllEpgTags(), PVR::CPVREpgDatabase::GetAllIconPaths(), PVR::CPVREpgDatabase::GetAllParentalRatingIconPaths(), PVR::CPVREpgDatabase::GetEpgTagByDatabaseID(), PVR::CPVREpgDatabase::GetEpgTagByMaxEndTime(), PVR::CPVREpgDatabase::GetEpgTagByMinStartTime(), PVR::CPVREpgDatabase::GetEpgTagByStartTime(), PVR::CPVREpgDatabase::GetEpgTagByUniqueBroadcastID(), PVR::CPVREpgDatabase::GetEpgTagsByMinEndMaxStartTime(), PVR::CPVREpgDatabase::GetEpgTagsByMinStartMaxEndTime(), PVR::CPVRDatabase::GetGroups(), PVR::CPVREpgDatabase::GetSavedSearchById(), PVR::CPVREpgDatabase::GetSavedSearches(), and PVR::CPVRDatabase::GetTimers().
RollbackTransaction()
void CDatabase::RollbackTransaction ()
References CLog::Log(), LOGERROR, and m_pDB.
Referenced by CTextureDatabase::AddCachedTexture(), CMusicDatabase::AddSource(), CVideoDatabase::AddVideoAsset(), CVideoDatabase::CleanDatabase(), CMusicDatabase::Cleanup(), CommitMultipleExecute(), CreateDatabase(), CVideoDatabase::DeleteMovie(), CVideoDatabase::DeleteMusicVideo(), CVideoDatabase::DeleteSeason(), CVideoDatabase::DeleteTvShow(), CVideoDatabase::DeleteVideoAsset(), CSaveFileState::DoWork(), CMusicDatabase::ImportFromXML(), CMusicDatabase::ImportSongHistory(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMovieSet(), CVideoDatabase::SetDetailsForMusicVideo(), CVideoDatabase::SetDetailsForSeason(), CMusicDatabase::SetScraper(), CMusicDatabase::SetScraperAll(), ADDON::CAddonDatabase::SyncInstalled(), CVideoDatabase::UpdateDetailsForMovie(), CVideoDatabase::UpdateDetailsForTvShow(), ADDON::CAddonDatabase::UpdateRepositoryContent(), CMusicDatabase::UpdateSource(), CDatabaseManager::UpdateVersion(), and CVideoDatabase::UpdateVideoVersionTypeTable().
Split()
void CDatabase::Split (const std::string & strFileNameAndPath, std::string & strPath, std::string & strFileName) protected
UpdateTables()
virtual void CDatabase::UpdateTables (int version) inline protected virtual
Reimplemented in ADDON::CAddonDatabase, CMusicDatabase, PVR::CPVREpgDatabase, PVR::CPVRDatabase, CTextureDatabase, CVideoDatabase, and CViewDatabase.
Referenced by CDatabaseManager::UpdateVersion().
UpdateVersionNumber()
void CDatabase::UpdateVersionNumber () private
References GetSchemaVersion(), m_pDS, and PrepareSQL().
Referenced by CDatabaseManager::UpdateVersion().
Friends And Related Symbol Documentation
CDatabaseManager
friend class CDatabaseManager friend
Member Data Documentation
m_bMultiDelete
bool CDatabase::m_bMultiDelete private
Initial value:
=
      false
True if there are any queries in the delete queue, false otherwise
Referenced by CommitDeleteQueries(), and QueueDeleteQuery().
m_bMultiInsert
bool CDatabase::m_bMultiInsert private
Initial value:
=
      false
True if there are any queries in the insert queue, false otherwise
Referenced by CommitInsertQueries(), and QueueInsertQuery().
m_multipleExecute
bool CDatabase::m_multipleExecute private
Referenced by BeginMultipleExecute(), CDatabase(), Close(), CommitMultipleExecute(), and ExecuteQuery().
m_multipleQueries
std::vector<std::string> CDatabase::m_multipleQueries private
Referenced by BeginMultipleExecute(), CommitMultipleExecute(), and ExecuteQuery().
m_openCount
unsigned int CDatabase::m_openCount private
Referenced by CDatabase(), Close(), Connect(), IsOpen(), and Open().
m_pDB
std::unique_ptr<dbiplus::Database> CDatabase::m_pDB protected
Referenced by CVideoDatabase::AddActor(), CMusicDatabase::AddAlbum(), CMusicDatabase::AddAlbumSources(), CMusicDatabase::AddArtist(), CMusicDatabase::AddArtist(), CMusicDatabase::AddArtistVideoLinks(), CVideoDatabase::AddBookMarkToFile(), CTextureDatabase::AddCachedTexture(), CVideoDatabase::AddFile(), CMusicDatabase::AddGenre(), ADDON::CAddonDatabase::AddInstalledAddon(), CVideoDatabase::AddNewEpisode(), CVideoDatabase::AddNewMovie(), CVideoDatabase::AddNewMusicVideo(), CMusicDatabase::AddPath(), CVideoDatabase::AddPath(), CVideoDatabase::AddRatings(), CMusicDatabase::AddRole(), CVideoDatabase::AddSet(), CMusicDatabase::AddSong(), CMusicDatabase::AddSongContributor(), CMusicDatabase::AddSource(), CVideoDatabase::AddToTable(), CVideoDatabase::AddUniqueIDs(), ADDON::CAddonDatabase::AddUpdateRuleForAddon(), CVideoDatabase::AddVideoAsset(), CVideoDatabase::AddVideoVersionType(), BeginTransaction(), CMusicDatabase::CheckSources(), CVideoDatabase::CleanDatabase(), CMusicDatabase::Cleanup(), CMusicDatabase::CleanupOrphanedItems(), CMusicDatabase::CleanupSongsByIds(), CVideoDatabase::ClearBookMarkOfFile(), CVideoDatabase::ClearBookMarksOfFile(), CTextureDatabase::ClearCachedTexture(), CTextureDatabase::ClearTextureForPath(), CViewDatabase::ClearViewStates(), Close(), CommitTransaction(), Compress(), Connect(), CopyDB(), CVideoDatabase::DeleteDetailsForTvShow(), CVideoDatabase::DeleteEpisode(), CVideoDatabase::DeleteMovie(), CVideoDatabase::DeleteMusicVideo(), ADDON::CAddonDatabase::DeleteRepository(), ADDON::CAddonDatabase::DeleteRepositoryContents(), CVideoDatabase::DeleteResumeBookMark(), CVideoDatabase::DeleteSeason(), CVideoDatabase::DeleteSet(), CVideoDatabase::DeleteTag(), CVideoDatabase::DeleteTvShow(), CVideoDatabase::DeleteVideoAsset(), ADDON::CAddonDatabase::DisableAddon(), DropAnalytics(), ADDON::CAddonDatabase::EnableAddon(), ExecuteQuery(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetAddonUpdateRules(), CMusicDatabase::GetAlbum(), CMusicDatabase::GetAlbumByMatch(), CMusicDatabase::GetAlbumByName(), CMusicDatabase::GetAlbumFromSong(), CMusicDatabase::GetAlbumIdByPath(), CMusicDatabase::GetAlbumPaths(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), CVideoDatabase::GetArtForAsset(), CVideoDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtist(), CMusicDatabase::GetArtistByMatch(), CMusicDatabase::GetArtistByName(), CMusicDatabase::GetArtistDiscography(), CMusicDatabase::GetArtistExists(), CMusicDatabase::GetArtistFromMBID(), CMusicDatabase::GetArtistFromSong(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetArtistsNav(), CMusicDatabase::GetArtTypes(), CVideoDatabase::GetArtTypes(), CVideoDatabase::GetAssetsForVideo(), CVideoDatabase::GetBookMarksForFile(), CTextureDatabase::GetCachedTexture(), CVideoDatabase::GetCast(), CMusicDatabase::GetCommonNav(), CVideoDatabase::GetDefaultVersionForVideo(), CVideoDatabase::GetDefaultVideoVersion(), ADDON::CAddonDatabase::GetDisabled(), CMusicDatabase::GetDiscnumberForPathID(), CMusicDatabase::GetDiscsByWhere(), CVideoDatabase::GetEpisodeId(), CVideoDatabase::GetEpisodeInfo(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetFileBasePathById(), CVideoDatabase::GetFileId(), CVideoDatabase::GetFileIdByMovie(), CVideoDatabase::GetFilePathById(), CMusicDatabase::GetGenreByName(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetGenresNav(), ADDON::CAddonDatabase::GetInstallData(), CVideoDatabase::GetLastPlayed(), CVideoDatabase::GetLinksToTvShow(), CVideoDatabase::GetMatchingMusicVideo(), CMusicDatabase::GetMatchingMusicVideoAlbum(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMovieId(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMovieTitle(), CMusicDatabase::GetMusicNeedsTagScan(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideoId(), CVideoDatabase::GetMusicVideoInfo(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByArtist(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CMusicDatabase::GetOldArtistPath(), CTextureDatabase::GetOldestCachedImages(), CMusicDatabase::GetPathHash(), CVideoDatabase::GetPathHash(), CVideoDatabase::GetPathId(), CMusicDatabase::GetPaths(), CVideoDatabase::GetPaths(), CVideoDatabase::GetPathsForTvShow(), CVideoDatabase::GetPeopleNav(), CVideoDatabase::GetPlayCount(), CVideoDatabase::GetPlayCounts(), CVideoDatabase::GetRandomMusicVideoIDs(), CMusicDatabase::GetRandomSongIDs(), CVideoDatabase::GetRatings(), CMusicDatabase::GetRecentlyAddedAlbums(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), CMusicDatabase::GetRecentlyPlayedAlbums(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), ADDON::CAddonDatabase::GetRepoChecksum(), ADDON::CAddonDatabase::GetRepositoryContent(), ADDON::CAddonDatabase::GetRepositoryId(), ADDON::CAddonDatabase::GetRepoUpdateData(), CMusicDatabase::GetRoleByName(), CMusicDatabase::GetRolesNav(), CVideoDatabase::GetSameVideoItems(), CMusicDatabase::GetScraper(), CVideoDatabase::GetScraperForPath(), CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetSetsByWhere(), GetSingleValue(), GetSingleValueInt(), CMusicDatabase::GetSong(), CMusicDatabase::GetSongByFileName(), CMusicDatabase::GetSongIDFromPath(), CMusicDatabase::GetSongsByPath(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsCount(), CMusicDatabase::GetSongsFullByWhere(), CVideoDatabase::GetSortedVideos(), CMusicDatabase::GetSourceByName(), CMusicDatabase::GetSourceFromPath(), CVideoDatabase::GetSourcePath(), CMusicDatabase::GetSources(), CMusicDatabase::GetSourcesByAlbum(), CMusicDatabase::GetSourcesByArtist(), CMusicDatabase::GetSourcesBySong(), CMusicDatabase::GetSourcesNav(), CVideoDatabase::GetStackTimes(), CVideoDatabase::GetStreamDetails(), CVideoDatabase::GetSubPaths(), CVideoDatabase::GetTags(), CTextureDatabase::GetTextureForPath(), CTextureDatabase::GetTextures(), CMusicDatabase::GetTop100(), CMusicDatabase::GetTop100Albums(), CMusicDatabase::GetTop100AlbumSongs(), CVideoDatabase::GetTvShowForEpisode(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowId(), CVideoDatabase::GetTvShowInfo(), CVideoDatabase::GetTvShowNamedSeasons(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), CVideoDatabase::GetTvShowSeasonArt(), CVideoDatabase::GetTvShowSeasons(), CVideoDatabase::GetUniqueIDs(), CVideoDatabase::GetUsedImages(), CMusicDatabase::GetUsedImages(), CVideoDatabase::GetVideoSettings(), CVideoDatabase::GetVideoVersionInfo(), CVideoDatabase::GetVideoVersions(), CVideoDatabase::GetVideoVersionsNav(), CVideoDatabase::GetVideoVersionTypes(), CViewDatabase::GetViewState(), CMusicDatabase::GetYearsNav(), CVideoDatabase::GetYearsNav(), CVideoDatabase::HasArtForItem(), CVideoDatabase::HasContent(), CVideoDatabase::HasEpisodeInfo(), CVideoDatabase::HasMovieInfo(), CVideoDatabase::HasMusicVideoInfo(), CVideoDatabase::HasSets(), CVideoDatabase::HasTvShowInfo(), CVideoDatabase::ImportFromXML(), CMusicDatabase::ImportFromXML(), CMusicDatabase::IncrementPlayCount(), CVideoDatabase::InitializeVideoVersionTypeTable(), CVideoDatabase::IsDefaultVideoVersion(), CVideoDatabase::IsLinkedToTvshow(), CVideoDatabase::LinkMovieToTvshow(), ADDON::CAddonDatabase::OnPostUnInstall(), PrepareSQL(), QueueDeleteQuery(), QueueInsertQuery(), CVideoDatabase::RemoveContentForPath(), CMusicDatabase::RemoveSongsFromPath(), ADDON::CAddonDatabase::RemoveUpdateRuleForAddon(), ResultQuery(), RollbackTransaction(), CMusicDatabase::ScraperInUse(), CVideoDatabase::ScraperInUse(), ADDON::CAddonDatabase::Search(), CMusicDatabase::SearchAlbums(), CMusicDatabase::SearchAlbumsByArtistName(), CMusicDatabase::SearchArtists(), CMusicDatabase::SearchSongs(), CMusicDatabase::SetAlbumUserrating(), CVideoDatabase::SetArtForItem(), CMusicDatabase::SetArtForItem(), CVideoDatabase::SetDefaultVideoVersion(), CVideoDatabase::SetFileForMovie(), CMusicDatabase::SetItemUpdated(), ADDON::CAddonDatabase::SetLastUpdated(), ADDON::CAddonDatabase::SetLastUsed(), ADDON::CAddonDatabase::SetOrigin(), CMusicDatabase::SetPathHash(), CVideoDatabase::SetPathHash(), CVideoDatabase::SetPlayCount(), ADDON::CAddonDatabase::SetRepoUpdateData(), CMusicDatabase::SetScraper(), CMusicDatabase::SetScraperAll(), CVideoDatabase::SetScraperForPath(), CVideoDatabase::SetSingleValue(), CVideoDatabase::SetSingleValue(), CMusicDatabase::SetSongUserrating(), CMusicDatabase::SetSongUserrating(), CMusicDatabase::SetSongVotes(), CVideoDatabase::SetStackTimes(), CTextureDatabase::SetTextureForPath(), CVideoDatabase::SetVideoSettings(), CVideoDatabase::SetVideoUserRating(), CVideoDatabase::SetVideoVersion(), CViewDatabase::SetViewState(), ADDON::CAddonDatabase::SyncInstalled(), CVideoDatabase::UpdateFanart(), CVideoDatabase::UpdateFileDateAdded(), CVideoDatabase::UpdateMovieTitle(), CVideoDatabase::UpdateRatings(), ADDON::CAddonDatabase::UpdateRepositoryContent(), CMusicDatabase::UpdateSource(), CVideoDatabase::UpdateTables(), CVideoDatabase::UpdateUniqueIDs(), and CVideoDatabase::UpdateVideoSortTitle().
m_pDS
std::unique_ptr<dbiplus::Dataset> CDatabase::m_pDS protected
Referenced by CVideoDatabase::AddActor(), CMusicDatabase::AddAlbum(), CMusicDatabase::AddAlbum(), CMusicDatabase::AddAlbumSources(), CMusicDatabase::AddArtist(), CMusicDatabase::AddArtist(), CMusicDatabase::AddArtistVideoLinks(), CVideoDatabase::AddBookMarkForEpisode(), CVideoDatabase::AddBookMarkToFile(), CTextureDatabase::AddCachedTexture(), CVideoDatabase::AddFile(), CMusicDatabase::AddGenre(), ADDON::CAddonDatabase::AddInstalledAddon(), CVideoDatabase::AddNewEpisode(), CVideoDatabase::AddNewMovie(), CVideoDatabase::AddNewMusicVideo(), CMusicDatabase::AddPath(), CVideoDatabase::AddPath(), CVideoDatabase::AddRatings(), CMusicDatabase::AddRole(), CVideoDatabase::AddSeason(), CVideoDatabase::AddSet(), CMusicDatabase::AddSong(), CMusicDatabase::AddSongContributor(), CMusicDatabase::AddSource(), CVideoDatabase::AddToTable(), CVideoDatabase::AddTvShow(), CVideoDatabase::AddUniqueIDs(), ADDON::CAddonDatabase::AddUpdateRuleForAddon(), CVideoDatabase::AddVideoAsset(), CVideoDatabase::AddVideoVersionType(), CMusicDatabase::CheckArtistLinksChanged(), CMusicDatabase::CheckSources(), CVideoDatabase::CleanDatabase(), CMusicDatabase::Cleanup(), CMusicDatabase::CleanupAlbums(), CMusicDatabase::CleanupArtists(), CMusicDatabase::CleanupGenres(), CMusicDatabase::CleanupInfoSettings(), CMusicDatabase::CleanupOrphanedItems(), CMusicDatabase::CleanupPaths(), CMusicDatabase::CleanupRoles(), CMusicDatabase::CleanupSongs(), CMusicDatabase::CleanupSongsByIds(), CVideoDatabase::ClearBookMarkOfFile(), CVideoDatabase::ClearBookMarksOfFile(), CTextureDatabase::ClearCachedTexture(), CTextureDatabase::ClearTextureForPath(), CViewDatabase::ClearViewStates(), Close(), CommitDeleteQueries(), Compress(), Connect(), ADDON::CAddonDatabase::CreateAnalytics(), CMusicDatabase::CreateAnalytics(), PVR::CPVREpgDatabase::CreateAnalytics(), PVR::CPVRDatabase::CreateAnalytics(), CTextureDatabase::CreateAnalytics(), CVideoDatabase::CreateAnalytics(), CViewDatabase::CreateAnalytics(), CreateDatabase(), PVR::CPVREpgDatabase::CreateEpgSearchFilter(), PVR::CPVREpgDatabase::CreateEpgTag(), CVideoDatabase::CreateForeignLinkIndex(), CVideoDatabase::CreateLinkIndex(), CMusicDatabase::CreateNativeDBFunctions(), CMusicDatabase::CreateRemovedLinkTriggers(), ADDON::CAddonDatabase::CreateTables(), CMusicDatabase::CreateTables(), PVR::CPVREpgDatabase::CreateTables(), PVR::CPVRDatabase::CreateTables(), CTextureDatabase::CreateTables(), CVideoDatabase::CreateTables(), CViewDatabase::CreateTables(), CMusicDatabase::CreateViews(), CVideoDatabase::CreateViews(), CVideoDatabase::DeleteBookMarkForEpisode(), CVideoDatabase::DeleteDetailsForTvShow(), CVideoDatabase::DeleteEpisode(), CVideoDatabase::DeleteMovie(), CVideoDatabase::DeleteMusicVideo(), CMusicDatabase::DeleteRemovedLinks(), ADDON::CAddonDatabase::DeleteRepository(), ADDON::CAddonDatabase::DeleteRepositoryContents(), CVideoDatabase::DeleteResumeBookMark(), CVideoDatabase::DeleteSeason(), CVideoDatabase::DeleteSet(), CVideoDatabase::DeleteStreamDetails(), CVideoDatabase::DeleteTag(), CVideoDatabase::DeleteTvShow(), CVideoDatabase::DeleteVideoAsset(), ADDON::CAddonDatabase::DisableAddon(), ADDON::CAddonDatabase::EnableAddon(), CVideoDatabase::EraseAllForFile(), CVideoDatabase::EraseAllForPath(), CVideoDatabase::EraseAllVideoSettings(), CVideoDatabase::EraseAllVideoSettings(), CVideoDatabase::EraseVideoSettings(), ExecuteQuery(), CMusicDatabase::ExportSongHistory(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), ADDON::CAddonDatabase::FindByAddonId(), PVR::CPVRDatabase::FixupClientIDs(), PVR::CPVRDatabase::Get(), PVR::CPVRDatabase::Get(), PVR::CPVRDatabase::Get(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetAddonUpdateRules(), CMusicDatabase::GetAlbum(), CMusicDatabase::GetAlbumByMatch(), CMusicDatabase::GetAlbumByName(), CMusicDatabase::GetAlbumFromSong(), CMusicDatabase::GetAlbumIdByPath(), CMusicDatabase::GetAlbumsByArtist(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetAlbumsByWhereJSON(), PVR::CPVREpgDatabase::GetAll(), PVR::CPVREpgDatabase::GetAllEpgTags(), PVR::CPVREpgDatabase::GetAllIconPaths(), PVR::CPVREpgDatabase::GetAllParentalRatingIconPaths(), CMusicDatabase::GetArtist(), CMusicDatabase::GetArtistByMatch(), CMusicDatabase::GetArtistByName(), CMusicDatabase::GetArtistDiscography(), CMusicDatabase::GetArtistExists(), CMusicDatabase::GetArtistFromSong(), CMusicDatabase::GetArtistsByAlbum(), CMusicDatabase::GetArtistsByAlbum(), CMusicDatabase::GetArtistsBySong(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetArtistsNav(), CMusicDatabase::GetArtTypes(), CVideoDatabase::GetArtTypes(), CVideoDatabase::GetAssetsForVideo(), CVideoDatabase::GetBookMarksForFile(), CTextureDatabase::GetCachedTexture(), PVR::CPVRDatabase::GetClientID(), CMusicDatabase::GetCommonNav(), CVideoDatabase::GetContentForPath(), GetDBVersion(), CVideoDatabase::GetDefaultVersionForVideo(), CVideoDatabase::GetDefaultVideoVersion(), GetDeleteQueriesCount(), ADDON::CAddonDatabase::GetDisabled(), CMusicDatabase::GetDiscsByWhere(), PVR::CPVREpgDatabase::GetEpgTagByDatabaseID(), PVR::CPVREpgDatabase::GetEpgTagByMaxEndTime(), PVR::CPVREpgDatabase::GetEpgTagByMinStartTime(), PVR::CPVREpgDatabase::GetEpgTagByStartTime(), PVR::CPVREpgDatabase::GetEpgTagByUniqueBroadcastID(), PVR::CPVREpgDatabase::GetEpgTags(), PVR::CPVREpgDatabase::GetEpgTagsByMinEndMaxStartTime(), PVR::CPVREpgDatabase::GetEpgTagsByMinStartMaxEndTime(), CVideoDatabase::GetEpisodeBasicInfo(), CVideoDatabase::GetEpisodeId(), CVideoDatabase::GetEpisodeInfo(), CVideoDatabase::GetEpisodesByFile(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetFileBasePathById(), CVideoDatabase::GetFileId(), CVideoDatabase::GetFileIdByMovie(), CVideoDatabase::GetFileInfo(), CMusicDatabase::GetFileItemFromDataset(), CVideoDatabase::GetFilePathById(), CMusicDatabase::GetGenreByName(), CMusicDatabase::GetGenresByAlbum(), CMusicDatabase::GetGenresByArtist(), CMusicDatabase::GetGenresBySong(), CMusicDatabase::GetGenresJSON(), CMusicDatabase::GetGenresNav(), PVR::CPVRDatabase::GetGroups(), ADDON::CAddonDatabase::GetInstallData(), CVideoDatabase::GetLastPlayed(), CVideoDatabase::GetLinksToTvShow(), CVideoDatabase::GetMatchingMusicVideo(), CMusicDatabase::GetMatchingMusicVideoAlbum(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMovieId(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMovieTitle(), CMusicDatabase::GetMusicNeedsTagScan(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideoId(), CVideoDatabase::GetMusicVideoInfo(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByArtist(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CTextureDatabase::GetOldestCachedImages(), CMusicDatabase::GetPathHash(), CVideoDatabase::GetPathHash(), CVideoDatabase::GetPathId(), CMusicDatabase::GetPaths(), CVideoDatabase::GetPaths(), CVideoDatabase::GetPathsForTvShow(), CVideoDatabase::GetPathsLinkedToTvShow(), CVideoDatabase::GetPeopleNav(), CVideoDatabase::GetPlayCount(), CVideoDatabase::GetPlayCounts(), CVideoDatabase::GetRandomMusicVideoIDs(), CMusicDatabase::GetRandomSongIDs(), CMusicDatabase::GetRecentlyAddedAlbums(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), CMusicDatabase::GetRecentlyPlayedAlbums(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), ADDON::CAddonDatabase::GetRepoChecksum(), ADDON::CAddonDatabase::GetRepositoryContent(), ADDON::CAddonDatabase::GetRepositoryId(), ADDON::CAddonDatabase::GetRepoUpdateData(), CMusicDatabase::GetResumeBookmarkForAudioBook(), CMusicDatabase::GetRoleByName(), CMusicDatabase::GetRolesByArtist(), CMusicDatabase::GetRolesNav(), CVideoDatabase::GetSameVideoItems(), PVR::CPVREpgDatabase::GetSavedSearchById(), PVR::CPVREpgDatabase::GetSavedSearches(), CMusicDatabase::GetScraper(), CVideoDatabase::GetScraperForPath(), CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetSetsByWhere(), GetSingleValue(), GetSingleValue(), GetSingleValueInt(), CMusicDatabase::GetSong(), CMusicDatabase::GetSongByArtistAndAlbumAndTitle(), CMusicDatabase::GetSongByFileName(), CMusicDatabase::GetSongFromDataset(), CMusicDatabase::GetSongIDFromPath(), CMusicDatabase::GetSongsByArtist(), CMusicDatabase::GetSongsByPath(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CMusicDatabase::GetSongsCount(), CMusicDatabase::GetSongsFullByWhere(), CVideoDatabase::GetSortedVideos(), CMusicDatabase::GetSourceByName(), CMusicDatabase::GetSourceFromPath(), CVideoDatabase::GetSourcePath(), CMusicDatabase::GetSources(), CMusicDatabase::GetSourcesByAlbum(), CMusicDatabase::GetSourcesByArtist(), CMusicDatabase::GetSourcesBySong(), CMusicDatabase::GetSourcesNav(), CVideoDatabase::GetStackTimes(), CVideoDatabase::GetSubPaths(), CTextureDatabase::GetTextureForPath(), CTextureDatabase::GetTextures(), PVR::CPVRDatabase::GetTimers(), CMusicDatabase::GetTop100(), CMusicDatabase::GetTop100Albums(), CMusicDatabase::GetTop100AlbumSongs(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowId(), CVideoDatabase::GetTvShowInfo(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), CVideoDatabase::GetUseAllExternalAudioForVideo(), CVideoDatabase::GetUsedImages(), CMusicDatabase::GetUsedImages(), CVideoDatabase::GetVideoSettings(), CVideoDatabase::GetVideoVersionInfo(), CVideoDatabase::GetVideoVersionsNav(), CVideoDatabase::GetVideoVersionTypes(), CViewDatabase::GetViewState(), CMusicDatabase::GetYearsNav(), CVideoDatabase::GetYearsNav(), CVideoDatabase::HasContent(), CVideoDatabase::HasEpisodeInfo(), CVideoDatabase::HasMovieInfo(), CVideoDatabase::HasMusicVideoInfo(), CVideoDatabase::HasSets(), CVideoDatabase::HasTvShowInfo(), CVideoDatabase::ImportFromXML(), CMusicDatabase::ImportFromXML(), CMusicDatabase::ImportSongHistory(), CMusicDatabase::IncrementPlayCount(), CVideoDatabase::InitializeVideoVersionTypeTable(), Interrupt(), CVideoDatabase::IsDefaultVideoVersion(), CVideoDatabase::IsLinkedToTvshow(), CVideoDatabase::LinkMovieToTvshow(), CMusicDatabase::MigrateSources(), ADDON::CAddonDatabase::OnPostUnInstall(), PVR::CPVREpgDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVREpgDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVRDatabase::Persist(), QueueDeleteQuery(), CVideoDatabase::RemoveContentForPath(), CMusicDatabase::RemoveSongsFromPath(), ADDON::CAddonDatabase::RemoveUpdateRuleForAddon(), ResultQuery(), CVideoDatabase::RunQuery(), CMusicDatabase::ScraperInUse(), CVideoDatabase::ScraperInUse(), ADDON::CAddonDatabase::Search(), CMusicDatabase::SearchAlbums(), CMusicDatabase::SearchAlbumsByArtistName(), CMusicDatabase::SearchArtists(), CMusicDatabase::SearchSongs(), CMusicDatabase::SetAlbumUserrating(), CVideoDatabase::SetArtForItem(), CMusicDatabase::SetArtForItem(), CMusicDatabase::SetArtistLinksUpdated(), CVideoDatabase::SetDefaultVideoVersion(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMovieSet(), CVideoDatabase::SetDetailsForMusicVideo(), CVideoDatabase::SetDetailsForSeason(), CVideoDatabase::SetFileForEpisode(), CVideoDatabase::SetFileForMovie(), CMusicDatabase::SetItemUpdated(), ADDON::CAddonDatabase::SetLastUpdated(), ADDON::CAddonDatabase::SetLastUsed(), CMusicDatabase::SetLibraryLastCleaned(), CMusicDatabase::SetLibraryLastUpdated(), CMusicDatabase::SetMusicNeedsTagScan(), CMusicDatabase::SetMusicTagScanVersion(), ADDON::CAddonDatabase::SetOrigin(), CMusicDatabase::SetPathHash(), CVideoDatabase::SetPathHash(), CVideoDatabase::SetPlayCount(), ADDON::CAddonDatabase::SetRepoUpdateData(), CMusicDatabase::SetResumeBookmarkForAudioBook(), CMusicDatabase::SetScraper(), CMusicDatabase::SetScraperAll(), CVideoDatabase::SetScraperForPath(), CVideoDatabase::SetSingleValue(), CVideoDatabase::SetSingleValue(), CMusicDatabase::SetSongUserrating(), CMusicDatabase::SetSongUserrating(), CMusicDatabase::SetSongVotes(), CVideoDatabase::SetStackTimes(), CVideoDatabase::SetStreamDetailsForFileId(), CTextureDatabase::SetTextureForPath(), CVideoDatabase::SetVideoSettings(), CVideoDatabase::SetVideoUserRating(), CVideoDatabase::SetVideoVersion(), CViewDatabase::SetViewState(), ADDON::CAddonDatabase::SyncInstalled(), CVideoDatabase::UpdateActorLinksToItem(), CMusicDatabase::UpdateAlbum(), CVideoDatabase::UpdateDetailsForMovie(), CVideoDatabase::UpdateFanart(), CVideoDatabase::UpdateFileDateAdded(), CVideoDatabase::UpdateLinksToItem(), CVideoDatabase::UpdateMovieTitle(), CVideoDatabase::UpdateRatings(), ADDON::CAddonDatabase::UpdateRepositoryContent(), CMusicDatabase::UpdateSource(), ADDON::CAddonDatabase::UpdateTables(), CMusicDatabase::UpdateTables(), PVR::CPVREpgDatabase::UpdateTables(), PVR::CPVRDatabase::UpdateTables(), CTextureDatabase::UpdateTables(), CVideoDatabase::UpdateTables(), CViewDatabase::UpdateTables(), CVideoDatabase::UpdateUniqueIDs(), UpdateVersionNumber(), CVideoDatabase::UpdateVideoSortTitle(), and CVideoDatabase::UpdateVideoVersionTypeTable().
m_pDS2
std::unique_ptr<dbiplus::Dataset> CDatabase::m_pDS2 protected
Referenced by CMusicDatabase::AddAlbumSources(), CMusicDatabase::AddArtistVideoLinks(), CVideoDatabase::CleanDatabase(), CVideoDatabase::CleanMediaType(), CMusicDatabase::CleanupPaths(), Close(), CommitInsertQueries(), Connect(), CVideoDatabase::DeleteSeason(), CVideoDatabase::DeleteTvShow(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), ADDON::CAddonDatabase::GetAddon(), CMusicDatabase::GetAlbumFolder(), CMusicDatabase::GetAlbumPaths(), CVideoDatabase::GetArtForAsset(), CVideoDatabase::GetArtForItem(), CVideoDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtist(), CMusicDatabase::GetArtistFolderName(), CMusicDatabase::GetArtistFromMBID(), CVideoDatabase::GetBookMarkForEpisode(), CVideoDatabase::GetBookMarksForFile(), CVideoDatabase::GetCast(), CVideoDatabase::GetDetailsForMovie(), CMusicDatabase::GetDiscnumberForPathID(), GetInsertQueriesCount(), CVideoDatabase::GetLinksToTvShow(), CVideoDatabase::GetMusicVideoAlbumsNav(), CMusicDatabase::GetOldArtistPath(), CVideoDatabase::GetRatings(), CVideoDatabase::GetResumePoint(), CMusicDatabase::GetSourcesByAlbum(), CVideoDatabase::GetTags(), CVideoDatabase::GetTvShowForEpisode(), CVideoDatabase::GetTvShowNamedSeasons(), CVideoDatabase::GetTvShowSeasonArt(), CVideoDatabase::GetTvShowSeasons(), CVideoDatabase::GetUniqueIDs(), CVideoDatabase::GetVideoVersionById(), CVideoDatabase::GetVideoVersions(), CVideoDatabase::HasArtForItem(), QueueInsertQuery(), CVideoDatabase::RemoveContentForPath(), CVideoDatabase::RemoveTagsFromItem(), CMusicDatabase::UpdateTables(), CTextureDatabase::UpdateTables(), CVideoDatabase::UpdateTables(), and CViewDatabase::UpdateTables().
m_profileManager
const CProfileManager& CDatabase::m_profileManager protected
Referenced by CMusicDatabase::DeleteCDDBInfo(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetMatchingMusicVideo(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), CVideoDatabase::GetYearsNav(), InitSettings(), and CMusicDatabase::LookupCDDBInfo().
m_sqlite
bool CDatabase::m_sqlite protected
whether we use sqlite (defaults to true)
Referenced by CDatabase(), Compress(), and InitSettings().
The documentation for this class was generated from the following files:
Database.h
Database.cpp