Kodi Documentation: MusicInfoScanner.cpp File Reference
MusicInfoScanner.cpp File Reference
#include "MusicInfoScanner.h"
#include "FileItem.h"
#include "FileItemList.h"
#include "GUIInfoManager.h"
#include "GUIUserMessages.h"
#include "MusicAlbumInfo.h"
#include "MusicInfoScraper.h"
#include "NfoFile.h"
#include "ServiceBroker.h"
#include "TextureCache.h"
#include "URL.h"
#include "Util.h"
#include "addons/AddonSystemSettings.h"
#include "addons/Scraper.h"
#include "addons/addoninfo/AddonType.h"
#include "dialogs/GUIDialogExtendedProgressBar.h"
#include "dialogs/GUIDialogProgress.h"
#include "dialogs/GUIDialogSelect.h"
#include "dialogs/GUIDialogYesNo.h"
#include "events/EventLog.h"
#include "events/MediaLibraryEvent.h"
#include "filesystem/Directory.h"
#include "filesystem/MusicDatabaseDirectory.h"
#include "filesystem/MusicDatabaseDirectory/DirectoryNode.h"
#include "filesystem/SmartPlaylistDirectory.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIKeyboardFactory.h"
#include "guilib/GUIWindowManager.h"
#include "guilib/LocalizeStrings.h"
#include "imagefiles/ImageFileURL.h"
#include "interfaces/AnnouncementManager.h"
#include "music/MusicFileItemClassify.h"
#include "music/MusicLibraryQueue.h"
#include "music/MusicThumbLoader.h"
#include "music/MusicUtils.h"
#include "music/tags/MusicInfoTag.h"
#include "music/tags/MusicInfoTagLoaderFactory.h"
#include "playlists/PlayListFileItemClassify.h"
#include "settings/AdvancedSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/Digest.h"
#include "utils/FileExtensionProvider.h"
#include "utils/FileUtils.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/Variant.h"
#include "utils/log.h"
#include <algorithm>
#include <utility>
Macros
#define THRESHOLD .95f
Functions
static void OnDirectoryScanned (const std::string &strDirectory)
static std::string Prettify (const std::string &strDirectory)
static bool SortSongsByTrack (const CSong &song, const CSong &song2)
Macro Definition Documentation
THRESHOLD
#define THRESHOLD .95f
Function Documentation
OnDirectoryScanned()
static void OnDirectoryScanned (const std::string & strDirectory) static
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_DIRECTORY_SCANNED, and CGUIMessage::SetStringParam().
Referenced by MUSIC_INFO::CMusicInfoScanner::DoScan().
Prettify()
static std::string Prettify (const std::string & strDirectory) static
References CURL::GetWithoutUserDetails().
Referenced by MUSIC_INFO::CMusicInfoScanner::DoScan().
SortSongsByTrack()
static bool SortSongsByTrack (const CSong & song, const CSong & song2) static
References CSong::iTrack.
Referenced by MUSIC_INFO::CMusicInfoScanner::FileItemsToAlbums().