Kodi Documentation: anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector Class Reference
anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector Class Reference
Public Member Functions
InstantRecordingActionSelector (int iInstantRecordTime)
virtual ~InstantRecordingActionSelector ()=default
void AddAction (PVRRECORD_INSTANTRECORDACTION eAction, const std::string &title)
void PreSelectAction (PVRRECORD_INSTANTRECORDACTION eAction)
PVRRECORD_INSTANTRECORDACTION Select ()
Private Attributes
int m_iInstantRecordTime
CGUIDialogSelect * m_pDlgSelect
std::map< PVRRECORD_INSTANTRECORDACTION, int > m_actions
Constructor & Destructor Documentation
InstantRecordingActionSelector()
anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::InstantRecordingActionSelector (int iInstantRecordTime) explicit
References LOGERROR, m_pDlgSelect, CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), and CGUIDialogSelect::SetMultiSelection().
~InstantRecordingActionSelector()
virtual anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::~InstantRecordingActionSelector () virtual default
Member Function Documentation
AddAction()
void anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::AddAction (PVRRECORD_INSTANTRECORDACTION eAction, const std::string & title)
References CGUIDialogSelect::Add(), anonymous_namespace{PVRGUIActionsTimers.cpp}::ASK, g_localizeStrings, CLocalizeStrings::Get(), m_actions, m_iInstantRecordTime, m_pDlgSelect, anonymous_namespace{PVRGUIActionsTimers.cpp}::NONE, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_120_MINUTES, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_30_MINUTES, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_60_MINUTES, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_CURRENT_SHOW, anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_INSTANTRECORDTIME, and anonymous_namespace{PVRGUIActionsTimers.cpp}::RECORD_NEXT_SHOW.
PreSelectAction()
void anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::PreSelectAction (PVRRECORD_INSTANTRECORDACTION eAction)
References m_actions, m_pDlgSelect, and CGUIDialogSelect::SetSelected().
Select()
PVRRECORD_INSTANTRECORDACTION anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::Select ()
References CGUIDialogSelect::GetSelectedItem(), CGUIDialogBoxBase::IsConfirmed(), m_actions, m_pDlgSelect, anonymous_namespace{PVRGUIActionsTimers.cpp}::NONE, and CGUIDialog::Open().
Member Data Documentation
m_actions
std::map<PVRRECORD_INSTANTRECORDACTION, int> anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::m_actions private
Referenced by AddAction(), PreSelectAction(), and Select().
m_iInstantRecordTime
int anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::m_iInstantRecordTime private
Referenced by AddAction().
m_pDlgSelect
CGUIDialogSelect* anonymous_namespace{PVRGUIActionsTimers.cpp}::InstantRecordingActionSelector::m_pDlgSelect private
Referenced by AddAction(), InstantRecordingActionSelector(), PreSelectAction(), and Select().
The documentation for this class was generated from the following file:
PVRGUIActionsTimers.cpp