Kodi Documentation: CTVOSInputSettings Class Reference
CTVOSInputSettings Class Reference
#include <TVOSSettingsHandler.h>
Public Member Functions
void Initialize ()
virtual void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Static Public Member Functions
static CTVOSInputSettings & GetInstance ()
Private Member Functions
CTVOSInputSettings ()=default
CTVOSInputSettings (CTVOSInputSettings const &)
CTVOSInputSettings & operator= (CTVOSInputSettings const &)
Static Private Attributes
static CTVOSInputSettings * m_instance = nullptr
Constructor & Destructor Documentation
CTVOSInputSettings() [1/2]
CTVOSInputSettings::CTVOSInputSettings () private default
Referenced by GetInstance().
CTVOSInputSettings() [2/2]
CTVOSInputSettings::CTVOSInputSettings (CTVOSInputSettings const &) private
Member Function Documentation
GetInstance()
CTVOSInputSettings & CTVOSInputSettings::GetInstance () static
References CTVOSInputSettings(), and m_instance.
Referenced by CSettings::InitializeISettingCallbacks(), and CPlatformDarwinEmbedded::InitStageTwo().
Initialize()
void CTVOSInputSettings::Initialize ()
References g_xbmcController, CServiceBroker::GetSettingsComponent(), XBMCController::inputHandler, TVOSLibInputHandler::inputSettings, CSettings::SETTING_INPUT_SIRIREMOTEHORIZONTALSENSITIVITY, CSettings::SETTING_INPUT_SIRIREMOTEIDLETIME, CSettings::SETTING_INPUT_SIRIREMOTEIDLETIMERENABLED, CSettings::SETTING_INPUT_SIRIREMOTEVERTICALSENSITIVITY, TVOSLibInputSettings::siriRemoteHorizontalSensitivity, and TVOSLibInputSettings::siriRemoteVerticalSensitivity.
Referenced by CPlatformDarwinEmbedded::InitStageTwo().
OnSettingChanged()
void CTVOSInputSettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References g_xbmcController, XBMCController::inputHandler, TVOSLibInputHandler::inputSettings, CSettings::SETTING_INPUT_SIRIREMOTEHORIZONTALSENSITIVITY, CSettings::SETTING_INPUT_SIRIREMOTEIDLETIME, CSettings::SETTING_INPUT_SIRIREMOTEIDLETIMERENABLED, CSettings::SETTING_INPUT_SIRIREMOTEVERTICALSENSITIVITY, TVOSLibInputSettings::siriRemoteHorizontalSensitivity, and TVOSLibInputSettings::siriRemoteVerticalSensitivity.
operator=()
CTVOSInputSettings & CTVOSInputSettings::operator= (CTVOSInputSettings const &) private
Member Data Documentation
m_instance
CTVOSInputSettings * CTVOSInputSettings::m_instance = nullptr static private
Referenced by GetInstance().
The documentation for this class was generated from the following files:
TVOSSettingsHandler.h
TVOSSettingsHandler.mm