Kodi Documentation: CVideoFileItemListModifier Class Reference
CVideoFileItemListModifier Class Reference
#include <VideoFileItemListModifier.h>
Public Member Functions
CVideoFileItemListModifier ()=default
~CVideoFileItemListModifier () override=default
bool CanModify (const CFileItemList &items) const override
bool Modify (CFileItemList &items) const override
Public Member Functions inherited from IFileItemListModifier
IFileItemListModifier ()=default
virtual ~IFileItemListModifier ()=default
Static Private Member Functions
static void AddQueuingFolder (CFileItemList &items)
Constructor & Destructor Documentation
CVideoFileItemListModifier()
CVideoFileItemListModifier::CVideoFileItemListModifier () default
~CVideoFileItemListModifier()
CVideoFileItemListModifier::~CVideoFileItemListModifier () override default
Member Function Documentation
AddQueuingFolder()
void CVideoFileItemListModifier::AddQueuingFolder (CFileItemList & items) static private
References CFileItemList::Add(), CDbUrl::AppendPath(), CDatabase::Close(), CDbUrl::FromString(), g_localizeStrings, CLocalizeStrings::Get(), CFileItemList::GetObjectCount(), CFileItem::GetPath(), CVideoDatabase::GetSeasonId(), CServiceBroker::GetSettingsComponent(), CFileItem::GetVideoInfoTag(), KODI::VIDEO::IsVideoDb(), CVideoInfoTag::m_iSeason, CVideoInfoTag::m_type, MediaTypeSeason, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_ALBUM, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SEASONS, CVideoDatabase::Open(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::ParseURL(), CGUIListItem::SetProperty(), CSettings::SETTING_VIDEOLIBRARY_SHOWALLITEMS, CFileItemList::Size(), SortSpecialOnBottom, SortSpecialOnTop, and CDbUrl::ToString().
Referenced by Modify().
CanModify()
bool CVideoFileItemListModifier::CanModify (const CFileItemList & items) const override virtual
Implements IFileItemListModifier.
References KODI::VIDEO::IsVideoDb().
Modify()
bool CVideoFileItemListModifier::Modify (CFileItemList & items) const override virtual
Implements IFileItemListModifier.
References AddQueuingFolder().
The documentation for this class was generated from the following files:
VideoFileItemListModifier.h
VideoFileItemListModifier.cpp