Kodi Documentation: PVR::CPVRChannelNumberInputHandler Class Reference
PVR::CPVRChannelNumberInputHandler Class Reference abstract
#include <PVRChannelNumberInputHandler.h>
Public Member Functions
CPVRChannelNumberInputHandler ()
CPVRChannelNumberInputHandler (int iDelay, int iMaxDigits=CHANNEL_NUMBER_INPUT_MAX_DIGITS)
ctor.
~CPVRChannelNumberInputHandler () override=default
CEventStream< PVRChannelNumberInputChangedEvent > & Events ()
Get the events available for CEventStream.
void OnTimeout () override
virtual void GetChannelNumbers (std::vector< std::string > &channelNumbers)=0
Get the currently available channel numbers.
virtual void OnInputDone ()=0
This method gets called after the channel number input timer has expired.
virtual void AppendChannelNumberCharacter (char cCharacter)
Appends a channel number character.
bool HasChannelNumber () const
Check whether a channel number was entered.
std::string GetChannelNumberLabel () const
Get the currently entered channel number as a formatted string.
bool CheckInputAndExecuteAction ()
If a number was entered, execute the associated action.
Static Public Attributes
static const int CHANNEL_NUMBER_INPUT_MAX_DIGITS = 5
Protected Member Functions
CPVRChannelNumber GetChannelNumber () const
Get the currently entered channel number.
size_t GetCurrentDigitCount () const
Get the currently entered number of digits.
Protected Attributes
CCriticalSection m_mutex
Private Member Functions
void ExecuteAction ()
void SetLabel (const std::string &label)
Private Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Private Attributes
std::vector< std::string > m_sortedChannelNumbers
const int m_iDelay
const int m_iMaxDigits
std::string m_inputBuffer
std::string m_label
CTimer m_timer
CEventSource< PVRChannelNumberInputChangedEvent > m_events
Constructor & Destructor Documentation
CPVRChannelNumberInputHandler() [1/2]
CPVRChannelNumberInputHandler::CPVRChannelNumberInputHandler ()
CPVRChannelNumberInputHandler() [2/2]
CPVRChannelNumberInputHandler::CPVRChannelNumberInputHandler (int iDelay, int iMaxDigits = CHANNEL_NUMBER_INPUT_MAX_DIGITS)
ctor.
Parameters
iDelay timer delay in millisecods.
iMaxDigits maximum number of display digits to use.
~CPVRChannelNumberInputHandler()
PVR::CPVRChannelNumberInputHandler::~CPVRChannelNumberInputHandler () override default
Member Function Documentation
AppendChannelNumberCharacter()
void CPVRChannelNumberInputHandler::AppendChannelNumberCharacter (char cCharacter) virtual
Appends a channel number character.
Parameters
cCharacter The character to append. value must be CPVRChannelNumber::SEPARATOR ('.') or any char in the range from '0' to '9'.
Reimplemented in PVR::CPVRChannelSwitchingInputHandler.
References ExecuteAction(), GetChannelNumbers(), CTimer::IsRunning(), m_iDelay, m_iMaxDigits, m_inputBuffer, m_mutex, m_sortedChannelNumbers, m_timer, CTimer::Restart(), PVR::CPVRChannelNumber::SEPARATOR, SetLabel(), and CTimer::Start().
Referenced by PVR::CPVRChannelSwitchingInputHandler::AppendChannelNumberCharacter(), PVR::CGUIDialogPVRChannelsOSD::OnAction(), PVR::CGUIWindowPVRChannelsBase::OnAction(), and PVR::CGUIWindowPVRGuideBase::OnAction().
CheckInputAndExecuteAction()
bool CPVRChannelNumberInputHandler::CheckInputAndExecuteAction ()
If a number was entered, execute the associated action.
Returns
True, if the action was executed, false otherwise.
References ExecuteAction(), GetChannelNumber(), and PVR::CPVRChannelNumber::IsValid().
Referenced by PVR::CGUIDialogPVRChannelsOSD::OnAction(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), and PVR::CGUIWindowPVRGuideBase::OnMessage().
Events()
CEventStream< PVRChannelNumberInputChangedEvent > & PVR::CPVRChannelNumberInputHandler::Events () inline
Get the events available for CEventStream.
Returns
The events.
References m_events.
Referenced by PVR::CPVRGUIActionsChannels::DeregisterChannelNumberInputHandler(), and PVR::CPVRGUIActionsChannels::RegisterChannelNumberInputHandler().
ExecuteAction()
void CPVRChannelNumberInputHandler::ExecuteAction () private
References m_timer, OnTimeout(), and CTimer::Stop().
Referenced by AppendChannelNumberCharacter(), and CheckInputAndExecuteAction().
GetChannelNumber()
CPVRChannelNumber CPVRChannelNumberInputHandler::GetChannelNumber () const protected
Get the currently entered channel number.
Returns
the channel number.
References m_inputBuffer, m_mutex, and PVR::CPVRChannelNumber::SEPARATOR.
Referenced by CheckInputAndExecuteAction(), PVR::CGUIDialogPVRChannelsOSD::OnInputDone(), PVR::CPVRChannelSwitchingInputHandler::OnInputDone(), PVR::CGUIWindowPVRChannelsBase::OnInputDone(), and PVR::CGUIWindowPVRGuideBase::OnInputDone().
GetChannelNumberLabel()
std::string CPVRChannelNumberInputHandler::GetChannelNumberLabel () const
Get the currently entered channel number as a formatted string.
Returns
the channel number string.
References m_label, and m_mutex.
GetChannelNumbers()
virtual void PVR::CPVRChannelNumberInputHandler::GetChannelNumbers (std::vector< std::string > & channelNumbers) pure virtual
Get the currently available channel numbers.
Parameters
channelNumbers The list to fill with the channel numbers.
Implemented in PVR::CGUIDialogPVRChannelsOSD, PVR::CPVRChannelSwitchingInputHandler, PVR::CGUIWindowPVRChannelsBase, and PVR::CGUIWindowPVRGuideBase.
Referenced by AppendChannelNumberCharacter().
GetCurrentDigitCount()
size_t PVR::CPVRChannelNumberInputHandler::GetCurrentDigitCount () const inline protected
Get the currently entered number of digits.
Returns
the number of digits.
References m_inputBuffer.
Referenced by PVR::CPVRChannelSwitchingInputHandler::AppendChannelNumberCharacter(), and PVR::CGUIWindowPVRGuideBase::OnAction().
HasChannelNumber()
bool CPVRChannelNumberInputHandler::HasChannelNumber () const
Check whether a channel number was entered.
Returns
True if the handler currently holds a channel number, false otherwise.
References m_inputBuffer.
OnInputDone()
virtual void PVR::CPVRChannelNumberInputHandler::OnInputDone () pure virtual
This method gets called after the channel number input timer has expired.
Implemented in PVR::CGUIDialogPVRChannelsOSD, PVR::CPVRChannelSwitchingInputHandler, PVR::CGUIWindowPVRChannelsBase, and PVR::CGUIWindowPVRGuideBase.
Referenced by OnTimeout().
OnTimeout()
void CPVRChannelNumberInputHandler::OnTimeout () override virtual
Implements ITimerCallback.
References CTimer::IsRunning(), m_inputBuffer, m_mutex, m_timer, OnInputDone(), SetLabel(), and CTimer::Start().
Referenced by ExecuteAction().
SetLabel()
void CPVRChannelNumberInputHandler::SetLabel (const std::string & label) private
References label, m_events, m_label, and m_mutex.
Referenced by AppendChannelNumberCharacter(), and OnTimeout().
Member Data Documentation
CHANNEL_NUMBER_INPUT_MAX_DIGITS
const int PVR::CPVRChannelNumberInputHandler::CHANNEL_NUMBER_INPUT_MAX_DIGITS = 5 static
m_events
CEventSource<PVRChannelNumberInputChangedEvent> PVR::CPVRChannelNumberInputHandler::m_events private
Referenced by Events(), and SetLabel().
m_iDelay
const int PVR::CPVRChannelNumberInputHandler::m_iDelay private
Referenced by AppendChannelNumberCharacter().
m_iMaxDigits
const int PVR::CPVRChannelNumberInputHandler::m_iMaxDigits private
Referenced by AppendChannelNumberCharacter().
m_inputBuffer
std::string PVR::CPVRChannelNumberInputHandler::m_inputBuffer private
Referenced by AppendChannelNumberCharacter(), GetChannelNumber(), GetCurrentDigitCount(), HasChannelNumber(), and OnTimeout().
m_label
std::string PVR::CPVRChannelNumberInputHandler::m_label private
Referenced by GetChannelNumberLabel(), and SetLabel().
m_mutex
CCriticalSection PVR::CPVRChannelNumberInputHandler::m_mutex mutable protected
Referenced by AppendChannelNumberCharacter(), GetChannelNumber(), GetChannelNumberLabel(), OnTimeout(), and SetLabel().
m_sortedChannelNumbers
std::vector<std::string> PVR::CPVRChannelNumberInputHandler::m_sortedChannelNumbers private
Referenced by AppendChannelNumberCharacter().
m_timer
CTimer PVR::CPVRChannelNumberInputHandler::m_timer private
Referenced by AppendChannelNumberCharacter(), ExecuteAction(), and OnTimeout().
The documentation for this class was generated from the following files:
PVRChannelNumberInputHandler.h
PVRChannelNumberInputHandler.cpp