Kodi Documentation: KODI::JOYSTICK::CJoystickUtils Class Reference
KODI::JOYSTICK::CJoystickUtils Class Reference
#include <JoystickUtils.h>
Static Public Member Functions
static std::string MakeKeyName (const FeatureName &feature)
Create a key name used to index an action in the keymap.
static std::string MakeKeyName (const FeatureName &feature, ANALOG_STICK_DIRECTION dir)
Create a key name used to index an action in the keymap.
static std::string MakeKeyName (const FeatureName &feature, WHEEL_DIRECTION dir)
Create a key name used to index an action in the keymap.
static std::string MakeKeyName (const FeatureName &feature, THROTTLE_DIRECTION dir)
Create a key name used to index an action in the keymap.
static const std::vector< ANALOG_STICK_DIRECTION > & GetAnalogStickDirections ()
Return a vector of the four cardinal directions.
static const std::vector< WHEEL_DIRECTION > & GetWheelDirections ()
Return a vector of the two wheel directions.
static const std::vector< THROTTLE_DIRECTION > & GetThrottleDirections ()
Return a vector of the two throttle directions.
Member Function Documentation
GetAnalogStickDirections()
const std::vector< ANALOG_STICK_DIRECTION > & CJoystickUtils::GetAnalogStickDirections () static
Return a vector of the four cardinal directions.
Referenced by KODI::KEYMAP::CKeymapHandler::AcceptsInput(), and KODI::KEYMAP::CKeymapHandler::OnAnalogStickMotion().
GetThrottleDirections()
const std::vector< THROTTLE_DIRECTION > & CJoystickUtils::GetThrottleDirections () static
Return a vector of the two throttle directions.
References KODI::JOYSTICK::DOWN, and KODI::JOYSTICK::UP.
Referenced by KODI::KEYMAP::CKeymapHandler::OnThrottleMotion().
GetWheelDirections()
const std::vector< WHEEL_DIRECTION > & CJoystickUtils::GetWheelDirections () static
Return a vector of the two wheel directions.
References KODI::JOYSTICK::LEFT, and KODI::JOYSTICK::RIGHT.
Referenced by KODI::KEYMAP::CKeymapHandler::OnWheelMotion().
MakeKeyName() [1/4]
std::string CJoystickUtils::MakeKeyName (const FeatureName & feature) static
Create a key name used to index an action in the keymap.
Parameters
feature The feature name
Returns
A valid name for a key in the joystick keymap
Referenced by KODI::KEYMAP::CKeymapHandler::AcceptsInput(), KODI::KEYMAP::CKeymapHandler::ActivateDirection(), KODI::KEYMAP::CKeymapHandler::ActivateDirection(), KODI::KEYMAP::CKeymapHandler::ActivateDirection(), KODI::JOYSTICK::CButtonMapping::CButtonMapping(), KODI::KEYMAP::CKeymapHandler::DeactivateDirection(), KODI::KEYMAP::CKeymapHandler::DeactivateDirection(), KODI::KEYMAP::CKeymapHandler::DeactivateDirection(), MakeKeyName(), MakeKeyName(), KODI::KEYMAP::CJoystickMapper::MapActions(), KODI::GAME::CGUIDialogButtonCapture::MapPrimitive(), KODI::KEYMAP::CKeymapHandler::OnButtonHold(), KODI::KEYMAP::CKeymapHandler::OnButtonMotion(), and KODI::KEYMAP::CKeymapHandler::OnButtonPress().
MakeKeyName() [2/4]
std::string CJoystickUtils::MakeKeyName (const FeatureName & feature, ANALOG_STICK_DIRECTION dir) static
Create a key name used to index an action in the keymap.
Parameters
feature The feature name
dir The direction for analog sticks
Returns
A valid name for a key in the joystick keymap
References KODI::JOYSTICK::CJoystickTranslator::TranslateAnalogStickDirection().
MakeKeyName() [3/4]
std::string CJoystickUtils::MakeKeyName (const FeatureName & feature, THROTTLE_DIRECTION dir) static
Create a key name used to index an action in the keymap.
Parameters
feature The feature name
dir The direction for a throttle to move
Returns
A valid name for a key in the joystick keymap
References KODI::JOYSTICK::DOWN, MakeKeyName(), and KODI::JOYSTICK::UP.
MakeKeyName() [4/4]
std::string CJoystickUtils::MakeKeyName (const FeatureName & feature, WHEEL_DIRECTION dir) static
Create a key name used to index an action in the keymap.
Parameters
feature The feature name
dir The direction for a wheel to turn
Returns
A valid name for a key in the joystick keymap
References KODI::JOYSTICK::LEFT, MakeKeyName(), and KODI::JOYSTICK::RIGHT.
The documentation for this class was generated from the following files:
JoystickUtils.h
JoystickUtils.cpp