Kodi Documentation: KODI::RETRO::CGameLoop Class Reference
KODI::RETRO::CGameLoop Class Reference
#include <GameLoop.h>
Public Member Functions
CGameLoop (IGameLoopCallback *callback, double fps)
~CGameLoop () override
void Start ()
void Stop ()
double FPS () const
double GetSpeed () const
void SetSpeed (double speedFactor)
void PauseAsync ()
Protected Member Functions
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Member Functions
double FrameTimeMs () const
double SleepTimeMs () const
double NowMs () const
Private Attributes
IGameLoopCallback *const m_callback
const double m_fps
std::atomic< double > m_speedFactor
double m_lastFrameMs = 0.0
double m_adjustTime = 0.0
CEvent m_sleepEvent
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CGameLoop()
CGameLoop::CGameLoop (IGameLoopCallback * callback, double fps)
~CGameLoop()
CGameLoop::~CGameLoop () override
References Stop().
Member Function Documentation
FPS()
double KODI::RETRO::CGameLoop::FPS () const inline
References m_fps.
Referenced by KODI::RETRO::CReversiblePlayback::SeekTimeMs(), KODI::RETRO::CReversiblePlayback::UpdateMemoryStream(), and KODI::RETRO::CReversiblePlayback::UpdatePlaybackStats().
FrameTimeMs()
double CGameLoop::FrameTimeMs () const private
References m_fps, and m_speedFactor.
Referenced by Process(), and SleepTimeMs().
GetSpeed()
double KODI::RETRO::CGameLoop::GetSpeed () const inline
References m_speedFactor.
Referenced by KODI::RETRO::CReversiblePlayback::GetSpeed().
NowMs()
double CGameLoop::NowMs () const private
Referenced by Process(), and SleepTimeMs().
PauseAsync()
void CGameLoop::PauseAsync ()
References SetSpeed().
Referenced by KODI::RETRO::CReversiblePlayback::PauseAsync().
Process()
void CGameLoop::Process (void) override protected virtual
Reimplemented from CThread.
References KODI::RETRO::IGameLoopCallback::FrameEvent(), FrameTimeMs(), m_adjustTime, CThread::m_bStop, m_callback, m_lastFrameMs, m_sleepEvent, m_speedFactor, NowMs(), KODI::RETRO::IGameLoopCallback::RewindEvent(), SleepTimeMs(), and CEvent::Wait().
SetSpeed()
void CGameLoop::SetSpeed (double speedFactor)
References m_sleepEvent, m_speedFactor, and CEvent::Set().
Referenced by PauseAsync(), KODI::RETRO::CReversiblePlayback::SeekTimeMs(), and KODI::RETRO::CReversiblePlayback::SetSpeed().
SleepTimeMs()
double CGameLoop::SleepTimeMs () const private
References FrameTimeMs(), m_adjustTime, m_lastFrameMs, and NowMs().
Referenced by Process().
Start()
void CGameLoop::Start ()
References CThread::Create().
Referenced by KODI::RETRO::CReversiblePlayback::Initialize().
Stop()
void CGameLoop::Stop ()
References m_sleepEvent, CEvent::Set(), and CThread::StopThread().
Referenced by KODI::RETRO::CReversiblePlayback::Deinitialize(), and ~CGameLoop().
Member Data Documentation
m_adjustTime
double KODI::RETRO::CGameLoop::m_adjustTime = 0.0 mutable private
Referenced by Process(), and SleepTimeMs().
m_callback
IGameLoopCallback* const KODI::RETRO::CGameLoop::m_callback private
Referenced by Process().
m_fps
const double KODI::RETRO::CGameLoop::m_fps private
Referenced by FPS(), and FrameTimeMs().
m_lastFrameMs
double KODI::RETRO::CGameLoop::m_lastFrameMs = 0.0 private
Referenced by Process(), and SleepTimeMs().
m_sleepEvent
CEvent KODI::RETRO::CGameLoop::m_sleepEvent private
Referenced by Process(), SetSpeed(), and Stop().
m_speedFactor
std::atomic<double> KODI::RETRO::CGameLoop::m_speedFactor private
Referenced by FrameTimeMs(), GetSpeed(), Process(), and SetSpeed().
The documentation for this class was generated from the following files:
GameLoop.h
GameLoop.cpp