Kodi Documentation: CGUIBaseContainer Class Reference
CGUIBaseContainer Class Reference
#include <GUIBaseContainer.h>
Classes
struct RENDERITEM
Public Member Functions
CGUIBaseContainer (int parentID, int controlID, float posX, float posY, float width, float height, ORIENTATION orientation, const CScroller &scroller, int preloadItems)
CGUIBaseContainer (const CGUIBaseContainer &other)
~CGUIBaseContainer (void) override
bool OnAction (const CAction &action) override
void OnDown () override
void OnUp () override
void OnLeft () override
void OnRight () override
bool OnMouseOver (const CPoint &point) override
Called when the mouse is over the control. Default implementation selects the control.
bool CanFocus () const override
bool OnMessage (CGUIMessage &message) override
void SetFocus (bool bOnOff) override
void AllocResources () override
void FreeResources (bool immediately=false) override
void UpdateVisibility (const CGUIListItem *item=NULL) override
void AssignDepth () override
virtual unsigned int GetRows () const
virtual bool HasNextPage () const
virtual bool HasPreviousPage () const
void SetPageControl (int id)
std::string GetDescription () const override
void SaveStates (std::vector< CControlState > &states) override
virtual int GetSelectedItem () const
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void LoadLayout (TiXmlElement *layout)
void LoadListProvider (TiXmlElement *content, int defaultItem, bool defaultAlways)
std::shared_ptr< CGUIListItem > GetListItem (int offset, unsigned int flag=0) const override
bool GetCondition (int condition, int data) const override
std::string GetLabel (int info) const override
void SetListProvider (std::unique_ptr< IListProvider > provider)
Set the list provider for this container (for python).
void SetRenderOffset (const CPoint &offset)
Set the offset of the first item in the container from the container's position Useful for lists/panels where the focused item may be larger than the non-focused items and thus normally cut off from the clipping window defined by the container's position + size.
void SetClickActions (const CGUIAction &clickActions)
void SetFocusActions (const CGUIAction &focusActions)
void SetUnFocusActions (const CGUIAction &unfocusActions)
void SetAutoScrolling (const TiXmlNode *node)
void ResetAutoScrolling ()
void UpdateAutoScrolling (unsigned int currentTime)
Public Member Functions inherited from IGUIContainer
IGUIContainer (int parentID, int controlID, float posX, float posY, float width, float height)
bool IsContainer () const override
VIEW_TYPE GetType () const
const std::string & GetLabel () const
void SetType (VIEW_TYPE type, const std::string &label)
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual CGUIControl * Clone () const =0
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual void DynamicResourceAlloc (bool bOnOff)
virtual bool IsDynamicallyAllocated ()
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Types
typedef std::vector< std::shared_ptr< CGUIListItem > >::iterator iItems
Protected Member Functions
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
bool OnClick (int actionID)
virtual void ProcessItem (float posX, float posY, std::shared_ptr< CGUIListItem > &item, bool focused, unsigned int currentTime, CDirtyRegionList &dirtyregions)
void Render () override
virtual void RenderItem (float posX, float posY, CGUIListItem *item, bool focused)
virtual void Scroll (int amount)
virtual bool MoveDown (bool wrapAround)
virtual bool MoveUp (bool wrapAround)
virtual bool GetOffsetRange (int &minOffset, int &maxOffset) const
virtual void ValidateOffset ()
virtual int CorrectOffset (int offset, int cursor) const
virtual void UpdateLayout (bool refreshAllItems=false)
virtual void SetPageControlRange ()
virtual void UpdatePageControl (int offset)
virtual void CalculateLayout ()
virtual void SelectItem (int item)
virtual bool SelectItemFromPoint (const CPoint &point)
virtual int GetCursorFromPoint (const CPoint &point, CPoint *itemPoint=NULL) const
virtual void Reset ()
virtual size_t GetNumItems () const
virtual int GetCurrentPage () const
bool InsideLayout (const CGUIListItemLayout *layout, const CPoint &point) const
void OnFocus () override
void OnUnFocus () override
void UpdateListProvider (bool forceRefresh=false)
int ScrollCorrectionRange () const
float Size () const
void FreeMemory (int keepStart, int keepEnd)
void GetCurrentLayouts ()
CGUIListItemLayout * GetFocusedLayout () const
virtual void ScrollToOffset (int offset)
void SetContainerMoving (int direction)
void UpdateScrollOffset (unsigned int currentTime)
void UpdateScrollByLetter ()
void GetCacheOffsets (int &cacheBefore, int &cacheAfter) const
int GetCacheCount () const
bool ScrollingDown () const
bool ScrollingUp () const
void OnNextLetter ()
void OnPrevLetter ()
void OnJumpLetter (const std::string &letter, bool skip=false)
void OnJumpSMS (int letter)
virtual void SetCursor (int cursor)
Set the cursor position Should be used by all base classes rather than directly setting it, as this also marks the control as dirty (if needed)
int GetCursor () const
void SetOffset (int offset)
Set the container offset Should be used by all base classes rather than directly setting it, as this also marks the control as dirty (if needed)
int GetOffset () const
Returns the index of the first visible row returns the first row. This may be outside of the range of available items. Use GetItemOffset() to retrieve the first visible item in the list.
int GetItemOffset () const
Returns the index of the first visible item returns the first visible item. This will always be in the range of available items. Use GetOffset() to retrieve the first visible row in the list.
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
CPoint m_renderOffset
render offset of the first item in the list
float m_analogScrollCount
unsigned int m_lastHoldTime
ORIENTATION m_orientation
int m_itemsPerPage
std::vector< std::shared_ptr< CGUIListItem > > m_items
std::shared_ptr< CGUIListItem > m_lastItem
int m_pageControl
std::list< CGUIListItemLayout > m_layouts
std::list< CGUIListItemLayout > m_focusedLayouts
CGUIListItemLayout * m_layout {nullptr}
CGUIListItemLayout * m_focusedLayout {nullptr}
bool m_layoutCondition = false
bool m_focusedLayoutCondition = false
CScroller m_scroller
std::unique_ptr< IListProvider > m_listProvider
bool m_wasReset
std::vector< std::pair< int, std::string > > m_letterOffsets
INFO::InfoPtr m_autoScrollCondition
int m_autoScrollMoveTime
unsigned int m_autoScrollDelayTime
bool m_autoScrollIsReversed
unsigned int m_lastRenderTime
Protected Attributes inherited from IGUIContainer
VIEW_TYPE m_type = VIEW_TYPE_NONE
std::string m_label
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Private Member Functions
bool OnContextMenu ()
Private Attributes
int m_cursor
int m_offset
int m_cacheItems
CStopWatch m_scrollTimer
CStopWatch m_lastScrollStartTimer
CStopWatch m_pageChangeTimer
CGUIAction m_clickActions
CGUIAction m_focusActions
CGUIAction m_unfocusActions
CStopWatch m_matchTimer
std::string m_match
float m_scrollItemsPerFrame
bool m_gestureActive = false
bool m_waitForScrollEnd = false
float m_lastScrollValue = 0.0f
Static Private Attributes
static const int letter_match_timeout = 1000
Additional Inherited Members
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Typedef Documentation
iItems
typedef std::vector<std::shared_ptr<CGUIListItem>>::iterator CGUIBaseContainer::iItems protected
Constructor & Destructor Documentation
CGUIBaseContainer() [1/2]
CGUIBaseContainer::CGUIBaseContainer (int parentID, int controlID, float posX, float posY, float width, float height, ORIENTATION orientation, const CScroller & scroller, int preloadItems)
References m_analogScrollCount, m_autoScrollDelayTime, m_autoScrollIsReversed, m_autoScrollMoveTime, m_cacheItems, m_cursor, m_focusedLayout, m_itemsPerPage, m_lastHoldTime, m_lastRenderTime, m_layout, m_offset, m_orientation, m_pageControl, m_scrollItemsPerFrame, IGUIContainer::m_type, m_wasReset, and VIEW_TYPE_NONE.
CGUIBaseContainer() [2/2]
CGUIBaseContainer::CGUIBaseContainer (const CGUIBaseContainer & other) explicit
References CGUIControl::m_bInvalidated, m_focusedLayouts, m_items, and m_layouts.
~CGUIBaseContainer()
CGUIBaseContainer::~CGUIBaseContainer (void) override
References m_items.
Member Function Documentation
AllocResources()
void CGUIBaseContainer::AllocResources () override virtual
Reimplemented from CGUIControl.
References CGUIControl::AllocResources(), CalculateLayout(), m_listProvider, and UpdateListProvider().
AssignDepth()
void CGUIBaseContainer::AssignDepth () override virtual
Reimplemented from CGUIControl.
References GetCursor(), GetOffset(), and m_items.
CalculateLayout()
void CGUIBaseContainer::CalculateLayout () protected virtual
Reimplemented in CGUIPanelContainer.
References GetCurrentLayouts(), GetOffset(), m_focusedLayout, m_itemsPerPage, m_layout, m_orientation, m_scroller, CScroller::SetValue(), Size(), and CGUIListItemLayout::Size().
Referenced by AllocResources(), and UpdateLayout().
CanFocus()
bool CGUIBaseContainer::CanFocus () const override virtual
Reimplemented from CGUIControl.
References CGUIControl::CanFocus(), m_items, and m_listProvider.
CorrectOffset()
int CGUIBaseContainer::CorrectOffset (int offset, int cursor) const protected virtual
Reimplemented in CGUIPanelContainer, and CGUIWrappingListContainer.
Referenced by CGUIFixedListContainer::GetCurrentPage(), GetItemOffset(), GetListItem(), GetSelectedItem(), OnJumpLetter(), OnJumpSMS(), OnMouseEvent(), OnNextLetter(), OnPrevLetter(), Process(), and Render().
DoProcess()
void CGUIBaseContainer::DoProcess (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
References CGUIControl::DoProcess(), CStopWatch::GetElapsedMilliseconds(), CStopWatch::IsRunning(), CGUIControl::IsVisible(), m_autoScrollMoveTime, m_pageChangeTimer, m_wasReset, ResetAutoScrolling(), and CStopWatch::Stop().
FreeMemory()
void CGUIBaseContainer::FreeMemory (int keepStart, int keepEnd) protected
References FreeMemory(), and m_items.
Referenced by FreeMemory(), Process(), and CGUIPanelContainer::Process().
FreeResources()
void CGUIBaseContainer::FreeResources (bool immediately = false) override virtual
Reimplemented from CGUIControl.
References CGUIControl::FreeResources(), m_listProvider, m_scroller, Reset(), and CScroller::Stop().
GetCacheCount()
int CGUIBaseContainer::GetCacheCount () const inline protected
References m_cacheItems.
Referenced by CGUIWrappingListContainer::ValidateOffset().
GetCacheOffsets()
void CGUIBaseContainer::GetCacheOffsets (int & cacheBefore, int & cacheAfter) const protected
References CScroller::IsScrollingDown(), CScroller::IsScrollingUp(), m_cacheItems, and m_scroller.
Referenced by Process(), CGUIPanelContainer::Process(), Render(), and CGUIPanelContainer::Render().
GetCondition()
bool CGUIBaseContainer::GetCondition (int condition, int data) const override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIPanelContainer.
References CONTAINER_COLUMN, CONTAINER_HAS_NEXT, CONTAINER_HAS_PARENT_ITEM, CONTAINER_HAS_PREVIOUS, CONTAINER_ISUPDATING, CONTAINER_POSITION, CONTAINER_ROW, CONTAINER_SCROLLING, CONTAINER_SUBITEM, data(), GetCursor(), CScroller::GetDuration(), CStopWatch::GetElapsedMilliseconds(), CGUIListItemLayout::GetFocusedItem(), GetFocusedLayout(), HasNextPage(), HasPreviousPage(), HORIZONTAL, CStopWatch::IsRunning(), m_items, m_listProvider, m_orientation, m_pageChangeTimer, m_scroller, m_scrollTimer, SCROLLING_THRESHOLD, and VERTICAL.
Referenced by CGUIPanelContainer::GetCondition().
GetCurrentLayouts()
void CGUIBaseContainer::GetCurrentLayouts () protected
References m_focusedLayout, m_focusedLayouts, m_layout, and m_layouts.
Referenced by CalculateLayout(), and CGUIPanelContainer::CalculateLayout().
GetCurrentPage()
int CGUIBaseContainer::GetCurrentPage () const protected virtual
Reimplemented in CGUIFixedListContainer, and CGUIWrappingListContainer.
References GetOffset(), GetRows(), and m_itemsPerPage.
Referenced by GetLabel().
GetCursor()
int CGUIBaseContainer::GetCursor () const inline protected
References m_cursor.
Referenced by AssignDepth(), GetCondition(), CGUIPanelContainer::GetCurrentColumn(), CGUIFixedListContainer::GetCurrentPage(), CGUIWrappingListContainer::GetCurrentPage(), CGUIPanelContainer::GetCurrentRow(), CGUIFixedListContainer::GetCursorFromPoint(), CGUIListContainer::GetCursorFromPoint(), GetLabel(), GetSelectedItem(), CGUIWrappingListContainer::GetSelectedItem(), CGUIListContainer::MoveDown(), CGUIPanelContainer::MoveDown(), CGUIPanelContainer::MoveLeft(), CGUIPanelContainer::MoveRight(), CGUIListContainer::MoveUp(), CGUIPanelContainer::MoveUp(), CGUIListContainer::OnAction(), CGUIPanelContainer::OnAction(), OnJumpLetter(), OnJumpSMS(), CGUIWrappingListContainer::OnMessage(), OnMouseEvent(), OnNextLetter(), OnPrevLetter(), Process(), CGUIPanelContainer::Process(), Render(), CGUIPanelContainer::Render(), CGUIFixedListContainer::Scroll(), CGUIPanelContainer::ScrollToOffset(), CGUIFixedListContainer::SelectItem(), CGUIListContainer::SelectItem(), CGUIPanelContainer::SelectItem(), CGUIWrappingListContainer::SelectItem(), CGUIWrappingListContainer::SelectItemFromPoint(), CGUIListContainer::SetCursor(), CGUIPanelContainer::SetCursor(), CGUIWrappingListContainer::UpdatePageControl(), UpdateScrollOffset(), and CGUIFixedListContainer::ValidateOffset().
GetCursorFromPoint()
virtual int CGUIBaseContainer::GetCursorFromPoint (const CPoint & point, CPoint * itemPoint = NULL) const inline protected virtual
Reimplemented in CGUIFixedListContainer, CGUIListContainer, and CGUIPanelContainer.
GetDescription()
std::string CGUIBaseContainer::GetDescription (void) const override virtual
Reimplemented from CGUIControl.
References GetSelectedItem(), and m_items.
GetFocusedLayout()
CGUIListItemLayout * CGUIBaseContainer::GetFocusedLayout () const protected
References GetListItem().
Referenced by GetCondition(), OnClick(), OnLeft(), OnRight(), and CGUIListContainer::SelectItemFromPoint().
GetItemOffset()
int CGUIBaseContainer::GetItemOffset () const inline protected
Returns the index of the first visible item returns the first visible item. This will always be in the range of available items. Use GetOffset() to retrieve the first visible row in the list.
See also
GetOffset
References CorrectOffset(), and GetOffset().
GetLabel()
std::string CGUIBaseContainer::GetLabel (int info) const override virtual
Implements IGUIContainer.
Reimplemented in CGUIPanelContainer.
References CONTAINER_CURRENT_ITEM, CONTAINER_CURRENT_PAGE, CONTAINER_NUM_ALL_ITEMS, CONTAINER_NUM_ITEMS, CONTAINER_NUM_NONFOLDER_ITEMS, CONTAINER_NUM_PAGES, CONTAINER_POSITION, GetCurrentPage(), GetCursor(), GetNumItems(), GetRows(), GetSelectedItem(), label, m_items, and m_itemsPerPage.
GetListItem()
std::shared_ptr< CGUIListItem > CGUIBaseContainer::GetListItem (int offset, unsigned int flag = 0) const override virtual
Implements IGUIContainer.
References CorrectOffset(), GetSelectedItem(), CScroller::GetValue(), INFOFLAG_LISTITEM_ABSOLUTE, INFOFLAG_LISTITEM_POSITION, INFOFLAG_LISTITEM_WRAP, m_items, m_layout, m_orientation, m_scroller, and CGUIListItemLayout::Size().
Referenced by GetFocusedLayout().
GetNumItems()
virtual size_t CGUIBaseContainer::GetNumItems () const inline protected virtual
Reimplemented in CGUIWrappingListContainer.
References m_items.
Referenced by GetLabel().
GetOffset()
int CGUIBaseContainer::GetOffset () const inline protected
Returns the index of the first visible row returns the first row. This may be outside of the range of available items. Use GetItemOffset() to retrieve the first visible item in the list.
See also
GetItemOffset
References m_offset.
Referenced by AssignDepth(), CalculateLayout(), CGUIPanelContainer::CalculateLayout(), GetCurrentPage(), CGUIFixedListContainer::GetCurrentPage(), CGUIWrappingListContainer::GetCurrentPage(), CGUIListContainer::GetCursorFromPoint(), CGUIPanelContainer::GetCursorFromPoint(), GetItemOffset(), GetSelectedItem(), CGUIWrappingListContainer::GetSelectedItem(), CGUIFixedListContainer::HasNextPage(), CGUIListContainer::HasNextPage(), CGUIPanelContainer::HasNextPage(), CGUIFixedListContainer::HasPreviousPage(), CGUIListContainer::HasPreviousPage(), CGUIPanelContainer::HasPreviousPage(), CGUIListContainer::MoveDown(), CGUIPanelContainer::MoveDown(), CGUIPanelContainer::MoveLeft(), CGUIPanelContainer::MoveRight(), CGUIListContainer::MoveUp(), CGUIPanelContainer::MoveUp(), CGUIListContainer::OnAction(), CGUIPanelContainer::OnAction(), OnJumpLetter(), OnJumpSMS(), OnMessage(), OnMouseEvent(), OnNextLetter(), OnPrevLetter(), Process(), CGUIPanelContainer::Process(), Render(), CGUIPanelContainer::Render(), Scroll(), CGUIFixedListContainer::Scroll(), CGUIListContainer::Scroll(), CGUIPanelContainer::Scroll(), CGUIWrappingListContainer::Scroll(), ScrollToOffset(), CGUIListContainer::SelectItem(), CGUIPanelContainer::SelectItem(), CGUIFixedListContainer::SelectItemFromPoint(), CGUIPanelContainer::SetCursor(), CGUIFixedListContainer::ValidateOffset(), CGUIListContainer::ValidateOffset(), and CGUIPanelContainer::ValidateOffset().
GetOffsetRange()
bool CGUIBaseContainer::GetOffsetRange (int & minOffset, int & maxOffset) const protected virtual
Reimplemented in CGUIFixedListContainer, and CGUIWrappingListContainer.
References GetRows(), and m_itemsPerPage.
Referenced by ScrollToOffset(), and CGUIListContainer::ValidateOffset().
GetRows()
unsigned int CGUIBaseContainer::GetRows () const virtual
Reimplemented in CGUIPanelContainer.
References m_items.
Referenced by GetCurrentPage(), CGUIFixedListContainer::GetCurrentPage(), CGUIWrappingListContainer::GetCurrentPage(), GetLabel(), GetOffsetRange(), OnAction(), and SetPageControlRange().
GetSelectedItem()
int CGUIBaseContainer::GetSelectedItem () const virtual
Reimplemented in CGUIWrappingListContainer.
References CorrectOffset(), GetCursor(), and GetOffset().
Referenced by KODI::GAME::CGUIAgentControllerList::FrameMove(), KODI::GAME::CDialogGameVideoSelect::FrameMove(), GetDescription(), GetLabel(), GetListItem(), CGUIFixedListContainer::MoveDown(), CGUIFixedListContainer::MoveUp(), OnAction(), OnClick(), OnContextMenu(), OnMessage(), OnMouseEvent(), SaveStates(), UpdateListProvider(), and UpdateVisibility().
HasNextPage()
bool CGUIBaseContainer::HasNextPage () const virtual
Reimplemented in CGUIFixedListContainer, CGUIListContainer, and CGUIPanelContainer.
Referenced by GetCondition().
HasPreviousPage()
bool CGUIBaseContainer::HasPreviousPage () const virtual
Reimplemented in CGUIFixedListContainer, CGUIListContainer, and CGUIPanelContainer.
Referenced by GetCondition().
InsideLayout()
bool CGUIBaseContainer::InsideLayout (const CGUIListItemLayout * layout, const CPoint & point) const protected
References HORIZONTAL, m_orientation, CGUIListItemLayout::Size(), VERTICAL, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by CGUIFixedListContainer::GetCursorFromPoint(), CGUIListContainer::GetCursorFromPoint(), CGUIFixedListContainer::SelectItemFromPoint(), and CGUIWrappingListContainer::SelectItemFromPoint().
LoadLayout()
void CGUIBaseContainer::LoadLayout (TiXmlElement * layout)
References CGUIControl::GetParentID(), m_focusedLayouts, CGUIControl::m_height, m_layouts, and CGUIControl::m_width.
Referenced by CGUIControlFactory::Create().
LoadListProvider()
void CGUIBaseContainer::LoadListProvider (TiXmlElement * content, int defaultItem, bool defaultAlways)
References IListProvider::Create(), CGUIControl::GetParentID(), and m_listProvider.
Referenced by CGUIControlFactory::Create().
MoveDown()
bool CGUIBaseContainer::MoveDown (bool wrapAround) protected virtual
Reimplemented in CGUIFixedListContainer, CGUIListContainer, CGUIPanelContainer, and CGUIWrappingListContainer.
Referenced by OnAction(), OnDown(), OnMessage(), OnRight(), and UpdateAutoScrolling().
MoveUp()
bool CGUIBaseContainer::MoveUp (bool wrapAround) protected virtual
Reimplemented in CGUIFixedListContainer, CGUIListContainer, CGUIPanelContainer, and CGUIWrappingListContainer.
Referenced by OnAction(), OnLeft(), OnMessage(), OnUp(), and UpdateAutoScrolling().
OnAction()
bool CGUIBaseContainer::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIFixedListContainer, CGUIListContainer, CGUIPanelContainer, and CGUIWrappingListContainer.
References ACTION_CONTEXT_MENU, ACTION_FIRST_PAGE, ACTION_JUMP_SMS2, ACTION_JUMP_SMS3, ACTION_JUMP_SMS4, ACTION_JUMP_SMS5, ACTION_JUMP_SMS6, ACTION_JUMP_SMS7, ACTION_JUMP_SMS8, ACTION_JUMP_SMS9, ACTION_LAST_PAGE, ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NAV_BACK, ACTION_NEXT_LETTER, ACTION_PLAYER_PLAY, ACTION_PREV_LETTER, ACTION_PREVIOUS_MENU, ACTION_SHOW_INFO, g_charsetConverter, CTimeUtils::GetFrameTime(), GetRows(), GetSelectedItem(), CGUIControl::HasFocus(), HOLD_TIME_END, HOLD_TIME_START, HORIZONTAL, KEY_UNICODE, m_items, m_lastHoldTime, m_listProvider, m_matchTimer, m_orientation, m_scrollItemsPerFrame, MoveDown(), MoveUp(), CGUIControl::OnAction(), OnClick(), OnContextMenu(), CGUIControl::OnInfo(), OnJumpLetter(), OnJumpSMS(), OnNextLetter(), OnPrevLetter(), SelectItem(), CStopWatch::Stop(), and VERTICAL.
Referenced by CGUIFixedListContainer::OnAction(), CGUIListContainer::OnAction(), CGUIPanelContainer::OnAction(), and CGUIWrappingListContainer::OnAction().
OnClick()
bool CGUIBaseContainer::OnClick (int actionID) protected
References ACTION_MOUSE_LEFT_CLICK, ACTION_MOUSE_RIGHT_CLICK, ACTION_SELECT_ITEM, CGUIAction::ExecuteActions(), CGUIListItemLayout::GetFocusedItem(), GetFocusedLayout(), CGUIControl::GetID(), CGUIControl::GetParentID(), GetSelectedItem(), GUI_MSG_CLICKED, CGUIAction::HasActionsMeetingCondition(), m_clickActions, m_items, m_listProvider, OnContextMenu(), and CGUIControl::SendWindowMessage().
Referenced by OnAction(), and OnMouseEvent().
OnContextMenu()
bool CGUIBaseContainer::OnContextMenu () private
References GetSelectedItem(), m_items, and m_listProvider.
Referenced by OnAction(), and OnClick().
OnDown()
void CGUIBaseContainer::OnDown () override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIPanelContainer.
References ACTION_MOVE_DOWN, CGUIControl::GetAction(), CGUIControl::GetID(), m_orientation, MoveDown(), CGUIControl::OnDown(), and VERTICAL.
OnFocus()
void CGUIBaseContainer::OnFocus () override protected virtual
Reimplemented from CGUIControl.
References CGUIAction::ExecuteActions(), CGUIControl::GetID(), CGUIControl::GetParentID(), CGUIAction::HasAnyActions(), m_focusActions, m_listProvider, CGUIControl::OnFocus(), and SelectItem().
OnJumpLetter()
void CGUIBaseContainer::OnJumpLetter (const std::string & letter, bool skip = false) protected
References CorrectOffset(), g_charsetConverter, GetCursor(), CStopWatch::GetElapsedMilliseconds(), GetOffset(), CServiceBroker::GetSettingsComponent(), label, letter_match_timeout, m_items, m_letterOffsets, m_match, m_matchTimer, OnJumpLetter(), SortUtils::RemoveArticles(), SelectItem(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, and CStopWatch::StartZero().
Referenced by OnAction(), and OnJumpLetter().
OnJumpSMS()
void CGUIBaseContainer::OnJumpSMS (int letter) protected
References CorrectOffset(), GetCursor(), GetOffset(), m_letterOffsets, and SelectItem().
Referenced by OnAction().
OnLeft()
void CGUIBaseContainer::OnLeft () override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIPanelContainer.
References ACTION_MOVE_LEFT, CGUIControl::GetAction(), GetFocusedLayout(), CGUIControl::GetID(), HORIZONTAL, m_orientation, CGUIListItemLayout::MoveLeft(), MoveUp(), CGUIControl::OnLeft(), and VERTICAL.
OnMessage()
bool CGUIBaseContainer::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIListContainer, CGUIPanelContainer, and CGUIWrappingListContainer.
References CFileItemList::Get(), CGUIMessage::GetControlId(), CGUIControl::GetID(), CGUIMessage::GetMessage(), GetOffset(), CGUIMessage::GetParam1(), CGUIMessage::GetParam2(), CGUIMessage::GetPointer(), GetSelectedItem(), CGUIMessage::GetSenderId(), GUI_MSG_ITEM_SELECT, GUI_MSG_ITEM_SELECTED, GUI_MSG_LABEL_BIND, GUI_MSG_LABEL_RESET, GUI_MSG_MOVE_OFFSET, GUI_MSG_PAGE_CHANGE, GUI_MSG_REFRESH_LIST, GUI_MSG_REFRESH_THUMBS, GUI_MSG_SETFOCUS, CGUIControl::IsVisible(), m_items, m_listProvider, m_pageChangeTimer, m_pageControl, MoveDown(), MoveUp(), CGUIControl::OnMessage(), Reset(), ScrollToOffset(), SelectItem(), CGUIControl::SetInvalid(), SetPageControlRange(), CGUIMessage::SetParam1(), CFileItemList::Size(), CStopWatch::StartZero(), UpdateLayout(), and UpdateScrollByLetter().
Referenced by CGUIListContainer::OnMessage(), CGUIPanelContainer::OnMessage(), and CGUIWrappingListContainer::OnMessage().
OnMouseEvent()
EVENT_RESULT CGUIBaseContainer::OnMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) override protected virtual
Perform a mouse action.
Mouse actions are sent from the window to all controls, and each control can react based on the event and location of the actions.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
SendMouseEvent, HitTest, CanFocusFromPoint, CMouseEvent
Reimplemented from CGUIControl.
References ACTION_GESTURE_ABORT, ACTION_GESTURE_BEGIN, ACTION_GESTURE_END, ACTION_GESTURE_NOTIFY, ACTION_GESTURE_PAN, ACTION_MOUSE_DOUBLE_CLICK, ACTION_MOUSE_LEFT_CLICK, ACTION_MOUSE_RIGHT_CLICK, ACTION_MOUSE_WHEEL_DOWN, ACTION_MOUSE_WHEEL_UP, CorrectOffset(), EVENT_RESULT_HANDLED, EVENT_RESULT_PAN_HORIZONTAL, EVENT_RESULT_PAN_VERTICAL, EVENT_RESULT_UNHANDLED, GetCursor(), CGUIControl::GetID(), GetOffset(), CGUIControl::GetParentID(), GetSelectedItem(), CScroller::GetValue(), GUI_MSG_EXCLUSIVE_MOUSE, HORIZONTAL, m_gestureActive, KODI::MOUSE::CMouseEvent::m_id, m_lastScrollStartTimer, m_lastScrollValue, m_layout, KODI::MOUSE::CMouseEvent::m_offsetX, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, m_scroller, m_scrollTimer, m_waitForScrollEnd, OnClick(), MathUtils::round_int(), Scroll(), ScrollToOffset(), SelectItemFromPoint(), CGUIControl::SendWindowMessage(), SetCursor(), SetFocus(), SetOffset(), CScroller::SetValue(), CGUIListItemLayout::Size(), CStopWatch::Start(), CStopWatch::Stop(), and ValidateOffset().
OnMouseOver()
bool CGUIBaseContainer::OnMouseOver (const CPoint & point) override virtual
Called when the mouse is over the control. Default implementation selects the control.
Parameters
point location of the mouse in transformed skin coordinates
Returns
true if handled, false otherwise.
Reimplemented from CGUIControl.
References CGUIControl::m_posX, CGUIControl::m_posY, m_waitForScrollEnd, CGUIControl::OnMouseOver(), and SelectItemFromPoint().
OnNextLetter()
void CGUIBaseContainer::OnNextLetter () protected
References CorrectOffset(), GetCursor(), GetOffset(), m_letterOffsets, and SelectItem().
Referenced by OnAction().
OnPrevLetter()
void CGUIBaseContainer::OnPrevLetter () protected
References CorrectOffset(), GetCursor(), GetOffset(), m_letterOffsets, and SelectItem().
Referenced by OnAction().
OnRight()
void CGUIBaseContainer::OnRight () override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIPanelContainer.
References ACTION_MOVE_RIGHT, CGUIControl::GetAction(), GetFocusedLayout(), CGUIControl::GetID(), HORIZONTAL, m_orientation, MoveDown(), CGUIListItemLayout::MoveRight(), CGUIControl::OnRight(), and VERTICAL.
OnUnFocus()
void CGUIBaseContainer::OnUnFocus (void) override protected virtual
Reimplemented from CGUIControl.
References CGUIAction::ExecuteActions(), CGUIControl::GetID(), CGUIControl::GetParentID(), CGUIAction::HasAnyActions(), m_unfocusActions, and CGUIControl::OnUnFocus().
OnUp()
void CGUIBaseContainer::OnUp () override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIPanelContainer.
References ACTION_MOVE_UP, CGUIControl::GetAction(), CGUIControl::GetID(), m_orientation, MoveUp(), CGUIControl::OnUp(), and VERTICAL.
Process()
void CGUIBaseContainer::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIPanelContainer.
References CorrectOffset(), end(), FreeMemory(), GetCacheOffsets(), GetCursor(), GetOffset(), CScroller::GetValue(), CScroller::IsScrolling(), CScroller::IsScrollingDown(), CGUIControl::m_bInvalidated, m_focusedLayout, m_gestureActive, CGUIControl::m_height, m_items, m_itemsPerPage, m_lastRenderTime, m_layout, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, m_renderOffset, m_scroller, m_waitForScrollEnd, CGUIControl::m_width, CGUIControl::MarkDirtyRegion(), CGUIControl::Process(), ProcessItem(), CGUIListItemLayout::Size(), UpdateAutoScrolling(), UpdateLayout(), UpdatePageControl(), UpdateScrollOffset(), ValidateOffset(), VERTICAL, CPointGen< T >::x, and CPointGen< T >::y.
ProcessItem()
void CGUIBaseContainer::ProcessItem (float posX, float posY, std::shared_ptr< CGUIListItem > & item, bool focused, unsigned int currentTime, CDirtyRegionList & dirtyregions) protected virtual
References ANIM_TYPE_UNFOCUS, CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CGUIControl::HasFocus(), CGUIControl::m_bInvalidated, m_focusedLayout, m_lastItem, m_layout, CGUIControl::m_parentID, CGraphicContext::RestoreOrigin(), and CGraphicContext::SetOrigin().
Referenced by Process(), and CGUIPanelContainer::Process().
Render()
void CGUIBaseContainer::Render () override protected virtual
Reimplemented from CGUIControl.
Reimplemented in CGUIPanelContainer.
References CorrectOffset(), end(), GetCacheOffsets(), GetCursor(), CWinSystemBase::GetGfxContext(), GetOffset(), CGraphicContext::GetRenderOrder(), CScroller::GetValue(), CServiceBroker::GetWinSystem(), m_focusedLayout, CGUIControl::m_height, m_items, m_layout, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, m_renderOffset, m_scroller, CGUIControl::m_width, CGUIControl::Render(), RENDER_ORDER_FRONT_TO_BACK, RenderItem(), CGraphicContext::RestoreClipRegion(), CGUIListItemLayout::Size(), VERTICAL, CPointGen< T >::x, and CPointGen< T >::y.
RenderItem()
void CGUIBaseContainer::RenderItem (float posX, float posY, CGUIListItem * item, bool focused) protected virtual
References ANIM_TYPE_UNFOCUS, CGUIListItem::GetFocusedLayout(), CWinSystemBase::GetGfxContext(), CGUIListItem::GetLayout(), CServiceBroker::GetWinSystem(), CGUIListItemLayout::IsAnimating(), m_focusedLayout, m_layout, CGUIControl::m_parentID, CGUIListItemLayout::Render(), CGraphicContext::RestoreOrigin(), and CGraphicContext::SetOrigin().
Referenced by Render(), and CGUIPanelContainer::Render().
Reset()
void CGUIBaseContainer::Reset () protected virtual
Reimplemented in CGUIWrappingListContainer.
References m_items, m_lastItem, m_wasReset, and ResetAutoScrolling().
Referenced by FreeResources(), OnMessage(), CGUIWrappingListContainer::Reset(), and UpdateListProvider().
ResetAutoScrolling()
void CGUIBaseContainer::ResetAutoScrolling ()
References m_autoScrollDelayTime.
Referenced by DoProcess(), Reset(), Scroll(), and UpdateAutoScrolling().
SaveStates()
void CGUIBaseContainer::SaveStates (std::vector< CControlState > & states) override virtual
Reimplemented from CGUIControl.
References CGUIControl::GetID(), GetSelectedItem(), and m_listProvider.
Scroll()
void CGUIBaseContainer::Scroll (int amount) protected virtual
Reimplemented in CGUIFixedListContainer, CGUIListContainer, CGUIPanelContainer, and CGUIWrappingListContainer.
References GetOffset(), ResetAutoScrolling(), and ScrollToOffset().
Referenced by OnMouseEvent().
ScrollCorrectionRange()
int CGUIBaseContainer::ScrollCorrectionRange () const protected
References m_itemsPerPage.
Referenced by ScrollToOffset(), and CGUIWrappingListContainer::ValidateOffset().
ScrollingDown()
bool CGUIBaseContainer::ScrollingDown () const inline protected
References CScroller::IsScrollingDown(), and m_scroller.
ScrollingUp()
bool CGUIBaseContainer::ScrollingUp () const inline protected
References CScroller::IsScrollingUp(), and m_scroller.
ScrollToOffset()
void CGUIBaseContainer::ScrollToOffset (int offset) protected virtual
Reimplemented in CGUIPanelContainer.
References GetOffset(), GetOffsetRange(), CScroller::GetValue(), CScroller::IsScrolling(), m_lastScrollStartTimer, m_layout, m_orientation, m_scroller, m_scrollTimer, m_wasReset, ScrollCorrectionRange(), CScroller::ScrollTo(), SetContainerMoving(), SetOffset(), CScroller::SetValue(), CGUIListItemLayout::Size(), CStopWatch::Start(), CStopWatch::StartZero(), CStopWatch::Stop(), and CScroller::Update().
Referenced by CGUIListContainer::MoveDown(), CGUIListContainer::MoveUp(), OnMessage(), OnMouseEvent(), Scroll(), CGUIFixedListContainer::Scroll(), CGUIListContainer::Scroll(), CGUIWrappingListContainer::Scroll(), CGUIPanelContainer::ScrollToOffset(), CGUIFixedListContainer::SelectItem(), CGUIListContainer::SelectItem(), CGUIWrappingListContainer::SelectItem(), and CGUIFixedListContainer::SelectItemFromPoint().
SelectItem()
virtual void CGUIBaseContainer::SelectItem (int item) inline protected virtual
Reimplemented in CGUIFixedListContainer, CGUIListContainer, CGUIPanelContainer, and CGUIWrappingListContainer.
Referenced by OnAction(), OnFocus(), OnJumpLetter(), OnJumpSMS(), OnMessage(), OnNextLetter(), OnPrevLetter(), UpdateListProvider(), and UpdateVisibility().
SelectItemFromPoint()
virtual bool CGUIBaseContainer::SelectItemFromPoint (const CPoint & point) inline protected virtual
Reimplemented in CGUIFixedListContainer, CGUIListContainer, CGUIPanelContainer, and CGUIWrappingListContainer.
Referenced by OnMouseEvent(), and OnMouseOver().
SetAutoScrolling()
void CGUIBaseContainer::SetAutoScrolling (const TiXmlNode * node)
References CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIControl::GetParentID(), m_autoScrollCondition, m_autoScrollIsReversed, m_autoScrollMoveTime, node, and CGUIInfoManager::Register().
Referenced by CGUIControlFactory::Create().
SetClickActions()
void CGUIBaseContainer::SetClickActions (const CGUIAction & clickActions) inline
References m_clickActions.
Referenced by CGUIControlFactory::Create().
SetContainerMoving()
void CGUIBaseContainer::SetContainerMoving (int direction) protected
References CServiceBroker::GetGUI(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetGUIControlsInfoProvider(), CGUIControl::GetID(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CScroller::IsScrolling(), m_scroller, and KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::SetContainerMoving().
Referenced by CGUIFixedListContainer::MoveDown(), CGUIListContainer::MoveDown(), CGUIPanelContainer::MoveDown(), CGUIFixedListContainer::MoveUp(), CGUIListContainer::MoveUp(), CGUIPanelContainer::MoveUp(), ScrollToOffset(), CGUIFixedListContainer::SelectItem(), CGUIListContainer::SetCursor(), and CGUIPanelContainer::SetCursor().
SetCursor()
void CGUIBaseContainer::SetCursor (int cursor) protected virtual
Set the cursor position Should be used by all base classes rather than directly setting it, as this also marks the control as dirty (if needed)
Reimplemented in CGUIListContainer, and CGUIPanelContainer.
References m_cursor, and CGUIControl::MarkDirtyRegion().
Referenced by CGUIFixedListContainer::CGUIFixedListContainer(), CGUIWrappingListContainer::CGUIWrappingListContainer(), OnMouseEvent(), CGUIFixedListContainer::Scroll(), CGUIFixedListContainer::SelectItem(), CGUIFixedListContainer::SelectItemFromPoint(), CGUIListContainer::SetCursor(), CGUIPanelContainer::SetCursor(), UpdateScrollOffset(), and CGUIFixedListContainer::ValidateOffset().
SetFocus()
void CGUIBaseContainer::SetFocus (bool bOnOff) override virtual
Reimplemented from CGUIControl.
References CGUIControl::HasFocus(), m_lastItem, CGUIControl::SetFocus(), and CGUIControl::SetInvalid().
Referenced by OnMouseEvent().
SetFocusActions()
void CGUIBaseContainer::SetFocusActions (const CGUIAction & focusActions) inline
References m_focusActions.
Referenced by CGUIControlFactory::Create().
SetListProvider()
void CGUIBaseContainer::SetListProvider (std::unique_ptr< IListProvider > provider)
Set the list provider for this container (for python).
Parameters
provider the list provider to use for this container.
References m_listProvider, and UpdateListProvider().
SetOffset()
void CGUIBaseContainer::SetOffset (int offset) protected
Set the container offset Should be used by all base classes rather than directly setting it, as this also marks the control as dirty (if needed)
References m_offset, and CGUIControl::MarkDirtyRegion().
Referenced by CGUIListContainer::OnMessage(), OnMouseEvent(), ScrollToOffset(), CGUIFixedListContainer::ValidateOffset(), CGUIListContainer::ValidateOffset(), and CGUIPanelContainer::ValidateOffset().
SetPageControl()
void CGUIBaseContainer::SetPageControl (int id)
References id, and m_pageControl.
Referenced by CGUIControlFactory::Create().
SetPageControlRange()
void CGUIBaseContainer::SetPageControlRange () protected virtual
Reimplemented in CGUIWrappingListContainer.
References CGUIControl::GetID(), GetRows(), GUI_MSG_LABEL_RESET, m_itemsPerPage, m_pageControl, and CGUIControl::SendWindowMessage().
Referenced by OnMessage(), UpdateLayout(), and UpdateListProvider().
SetRenderOffset()
void CGUIBaseContainer::SetRenderOffset (const CPoint & offset)
Set the offset of the first item in the container from the container's position Useful for lists/panels where the focused item may be larger than the non-focused items and thus normally cut off from the clipping window defined by the container's position + size.
Parameters
offset CPoint holding the offset in skin coordinates.
References m_renderOffset.
Referenced by CGUIControlFactory::Create().
SetUnFocusActions()
void CGUIBaseContainer::SetUnFocusActions (const CGUIAction & unfocusActions) inline
References m_unfocusActions.
Referenced by CGUIControlFactory::Create().
Size()
float CGUIBaseContainer::Size () const inline protected
References HORIZONTAL, CGUIControl::m_height, m_orientation, and CGUIControl::m_width.
Referenced by CalculateLayout(), CGUIFixedListContainer::GetCursorFromPoint(), and CGUIListContainer::GetCursorFromPoint().
UpdateAutoScrolling()
void CGUIBaseContainer::UpdateAutoScrolling (unsigned int currentTime)
References INFO::DEFAULT_CONTEXT, CScroller::IsScrolling(), m_autoScrollCondition, m_autoScrollDelayTime, m_autoScrollIsReversed, m_autoScrollMoveTime, m_lastRenderTime, m_scroller, MoveDown(), MoveUp(), and ResetAutoScrolling().
Referenced by Process().
UpdateLayout()
void CGUIBaseContainer::UpdateLayout (bool refreshAllItems = false) protected virtual
References CalculateLayout(), m_items, CGUIControl::MarkDirtyRegion(), and SetPageControlRange().
Referenced by OnMessage(), Process(), CGUIPanelContainer::Process(), and UpdateVisibility().
UpdateListProvider()
void CGUIBaseContainer::UpdateListProvider (bool forceRefresh = false) protected
References CFileItem::GetPath(), GetSelectedItem(), CGUIListItem::IsFileItem(), m_items, m_listProvider, Reset(), SelectItem(), CGUIControl::SetInvalid(), SetPageControlRange(), and UpdateScrollByLetter().
Referenced by AllocResources(), SetListProvider(), KODI::GAME::CGUIGameControllerList::UpdateInfo(), and UpdateVisibility().
UpdatePageControl()
void CGUIBaseContainer::UpdatePageControl (int offset) protected virtual
Reimplemented in CGUIWrappingListContainer.
References CGUIControl::GetID(), GUI_MSG_ITEM_SELECT, m_pageControl, and CGUIControl::SendWindowMessage().
Referenced by Process(), and CGUIPanelContainer::Process().
UpdateScrollByLetter()
void CGUIBaseContainer::UpdateScrollByLetter () protected
References g_charsetConverter, m_items, and m_letterOffsets.
Referenced by OnMessage(), and UpdateListProvider().
UpdateScrollOffset()
void CGUIBaseContainer::UpdateScrollOffset (unsigned int currentTime) protected
References GetCursor(), CStopWatch::GetElapsedMilliseconds(), CStopWatch::IsRunning(), m_lastScrollStartTimer, m_scroller, m_scrollTimer, CGUIControl::MarkDirtyRegion(), SCROLLING_GAP, SetCursor(), CStopWatch::Stop(), and CScroller::Update().
Referenced by Process(), and CGUIPanelContainer::Process().
UpdateVisibility()
void CGUIBaseContainer::UpdateVisibility (const CGUIListItem * item = NULL) override virtual
Reimplemented from CGUIControl.
References CGUIControl::CanFocus(), CGUIListItemLayout::CheckCondition(), GetSelectedItem(), CGUIControl::IsVisible(), m_focusedLayout, m_focusedLayoutCondition, m_layout, m_layoutCondition, SelectItem(), UpdateLayout(), UpdateListProvider(), and CGUIControl::UpdateVisibility().
ValidateOffset()
void CGUIBaseContainer::ValidateOffset () protected virtual
Reimplemented in CGUIFixedListContainer, CGUIListContainer, CGUIPanelContainer, and CGUIWrappingListContainer.
Referenced by OnMouseEvent(), and Process().
Member Data Documentation
letter_match_timeout
const int CGUIBaseContainer::letter_match_timeout = 1000 static private
Referenced by OnJumpLetter().
m_analogScrollCount
float CGUIBaseContainer::m_analogScrollCount protected
Referenced by CGUIBaseContainer(), CGUIFixedListContainer::OnAction(), CGUIListContainer::OnAction(), CGUIPanelContainer::OnAction(), CGUIWrappingListContainer::OnAction(), CGUIFixedListContainer::SelectItemFromPoint(), and CGUIWrappingListContainer::SelectItemFromPoint().
m_autoScrollCondition
INFO::InfoPtr CGUIBaseContainer::m_autoScrollCondition protected
Referenced by SetAutoScrolling(), and UpdateAutoScrolling().
m_autoScrollDelayTime
unsigned int CGUIBaseContainer::m_autoScrollDelayTime protected
Referenced by CGUIBaseContainer(), ResetAutoScrolling(), and UpdateAutoScrolling().
m_autoScrollIsReversed
bool CGUIBaseContainer::m_autoScrollIsReversed protected
Referenced by CGUIBaseContainer(), SetAutoScrolling(), and UpdateAutoScrolling().
m_autoScrollMoveTime
int CGUIBaseContainer::m_autoScrollMoveTime protected
Referenced by CGUIBaseContainer(), DoProcess(), SetAutoScrolling(), and UpdateAutoScrolling().
m_cacheItems
int CGUIBaseContainer::m_cacheItems private
Referenced by CGUIBaseContainer(), GetCacheCount(), and GetCacheOffsets().
m_clickActions
CGUIAction CGUIBaseContainer::m_clickActions private
Referenced by OnClick(), and SetClickActions().
m_cursor
int CGUIBaseContainer::m_cursor private
Referenced by CGUIBaseContainer(), GetCursor(), and SetCursor().
m_focusActions
CGUIAction CGUIBaseContainer::m_focusActions private
Referenced by OnFocus(), and SetFocusActions().
m_focusedLayout
CGUIListItemLayout* CGUIBaseContainer::m_focusedLayout {nullptr} protected
Referenced by CalculateLayout(), CGUIPanelContainer::CalculateLayout(), CGUIBaseContainer(), GetCurrentLayouts(), CGUIFixedListContainer::GetCursorFromPoint(), CGUIListContainer::GetCursorFromPoint(), Process(), CGUIPanelContainer::Process(), ProcessItem(), Render(), CGUIPanelContainer::Render(), RenderItem(), CGUIFixedListContainer::SelectItemFromPoint(), CGUIWrappingListContainer::SelectItemFromPoint(), and UpdateVisibility().
m_focusedLayoutCondition
bool CGUIBaseContainer::m_focusedLayoutCondition = false protected
Referenced by UpdateVisibility().
m_focusedLayouts
std::list<CGUIListItemLayout> CGUIBaseContainer::m_focusedLayouts protected
Referenced by CGUIBaseContainer(), CGUIListContainer::CGUIListContainer(), GetCurrentLayouts(), and LoadLayout().
m_gestureActive
bool CGUIBaseContainer::m_gestureActive = false private
Referenced by OnMouseEvent(), and Process().
m_items
std::vector<std::shared_ptr<CGUIListItem> > CGUIBaseContainer::m_items protected
Referenced by AssignDepth(), CanFocus(), CGUIBaseContainer(), CGUIWrappingListContainer::CorrectOffset(), FreeMemory(), GetCondition(), CGUIListContainer::GetCursorFromPoint(), CGUIPanelContainer::GetCursorFromPoint(), CGUIFixedListContainer::GetCursorRange(), GetDescription(), GetLabel(), GetListItem(), GetNumItems(), CGUIWrappingListContainer::GetNumItems(), CGUIFixedListContainer::GetOffsetRange(), GetRows(), CGUIPanelContainer::GetRows(), CGUIWrappingListContainer::GetSelectedItem(), CGUIFixedListContainer::HasNextPage(), CGUIListContainer::HasNextPage(), CGUIFixedListContainer::MoveDown(), CGUIListContainer::MoveDown(), CGUIPanelContainer::MoveDown(), CGUIPanelContainer::MoveLeft(), CGUIPanelContainer::MoveRight(), CGUIFixedListContainer::MoveUp(), CGUIListContainer::MoveUp(), CGUIPanelContainer::MoveUp(), OnAction(), CGUIListContainer::OnAction(), CGUIPanelContainer::OnAction(), OnClick(), OnContextMenu(), OnJumpLetter(), OnMessage(), Process(), CGUIPanelContainer::Process(), Render(), CGUIPanelContainer::Render(), Reset(), CGUIWrappingListContainer::ResetExtraItems(), CGUIFixedListContainer::Scroll(), CGUIListContainer::Scroll(), CGUIFixedListContainer::SelectItem(), CGUIListContainer::SelectItem(), CGUIPanelContainer::SelectItem(), CGUIWrappingListContainer::SelectItem(), CGUIFixedListContainer::SelectItemFromPoint(), CGUIPanelContainer::SetCursor(), UpdateLayout(), UpdateListProvider(), UpdateScrollByLetter(), CGUIWrappingListContainer::ValidateOffset(), and ~CGUIBaseContainer().
m_itemsPerPage
int CGUIBaseContainer::m_itemsPerPage protected
Referenced by CGUIPanelContainer::AnalogScrollSpeed(), CalculateLayout(), CGUIPanelContainer::CalculateLayout(), CGUIBaseContainer(), GetCurrentPage(), CGUIFixedListContainer::GetCurrentPage(), CGUIWrappingListContainer::GetCurrentPage(), CGUIListContainer::GetCursorFromPoint(), CGUIPanelContainer::GetCursorFromPoint(), CGUIFixedListContainer::GetCursorRange(), GetLabel(), GetOffsetRange(), CGUIFixedListContainer::HasNextPage(), CGUIListContainer::HasNextPage(), CGUIPanelContainer::HasNextPage(), CGUIListContainer::MoveDown(), CGUIPanelContainer::MoveDown(), CGUIListContainer::MoveUp(), CGUIPanelContainer::MoveUp(), CGUIFixedListContainer::OnAction(), CGUIListContainer::OnAction(), CGUIPanelContainer::OnAction(), CGUIWrappingListContainer::OnAction(), Process(), CGUIPanelContainer::Process(), CGUIListContainer::Scroll(), CGUIPanelContainer::Scroll(), ScrollCorrectionRange(), CGUIListContainer::SelectItem(), CGUIPanelContainer::SelectItem(), CGUIListContainer::SetCursor(), CGUIPanelContainer::SetCursor(), SetPageControlRange(), CGUIWrappingListContainer::SetPageControlRange(), CGUIFixedListContainer::ValidateOffset(), CGUIPanelContainer::ValidateOffset(), and CGUIWrappingListContainer::ValidateOffset().
m_lastHoldTime
unsigned int CGUIBaseContainer::m_lastHoldTime protected
Referenced by CGUIBaseContainer(), and OnAction().
m_lastItem
std::shared_ptr<CGUIListItem> CGUIBaseContainer::m_lastItem protected
Referenced by ProcessItem(), Reset(), and SetFocus().
m_lastRenderTime
unsigned int CGUIBaseContainer::m_lastRenderTime protected
Referenced by CGUIBaseContainer(), Process(), and UpdateAutoScrolling().
m_lastScrollStartTimer
CStopWatch CGUIBaseContainer::m_lastScrollStartTimer private
Referenced by OnMouseEvent(), ScrollToOffset(), and UpdateScrollOffset().
m_lastScrollValue
float CGUIBaseContainer::m_lastScrollValue = 0.0f private
Referenced by OnMouseEvent().
m_layout
CGUIListItemLayout* CGUIBaseContainer::m_layout {nullptr} protected
Referenced by CalculateLayout(), CGUIPanelContainer::CalculateLayout(), CGUIBaseContainer(), GetCurrentLayouts(), CGUIFixedListContainer::GetCursorFromPoint(), CGUIListContainer::GetCursorFromPoint(), CGUIPanelContainer::GetCursorFromPoint(), GetListItem(), OnMouseEvent(), Process(), CGUIPanelContainer::Process(), ProcessItem(), Render(), CGUIPanelContainer::Render(), RenderItem(), ScrollToOffset(), CGUIFixedListContainer::SelectItemFromPoint(), CGUIWrappingListContainer::SelectItemFromPoint(), UpdateVisibility(), CGUIFixedListContainer::ValidateOffset(), CGUIListContainer::ValidateOffset(), and CGUIPanelContainer::ValidateOffset().
m_layoutCondition
bool CGUIBaseContainer::m_layoutCondition = false protected
Referenced by UpdateVisibility().
m_layouts
std::list<CGUIListItemLayout> CGUIBaseContainer::m_layouts protected
Referenced by CGUIBaseContainer(), CGUIListContainer::CGUIListContainer(), GetCurrentLayouts(), and LoadLayout().
m_letterOffsets
std::vector< std::pair<int, std::string> > CGUIBaseContainer::m_letterOffsets protected
Referenced by OnJumpLetter(), OnJumpSMS(), OnNextLetter(), OnPrevLetter(), and UpdateScrollByLetter().
m_listProvider
std::unique_ptr<IListProvider> CGUIBaseContainer::m_listProvider protected
Referenced by AllocResources(), CanFocus(), FreeResources(), GetCondition(), LoadListProvider(), OnAction(), OnClick(), OnContextMenu(), OnFocus(), OnMessage(), SaveStates(), SetListProvider(), KODI::GAME::CGUIGameControllerList::UpdateInfo(), and UpdateListProvider().
m_match
std::string CGUIBaseContainer::m_match private
Referenced by OnJumpLetter().
m_matchTimer
CStopWatch CGUIBaseContainer::m_matchTimer private
Referenced by OnAction(), and OnJumpLetter().
m_offset
int CGUIBaseContainer::m_offset private
Referenced by CGUIBaseContainer(), GetOffset(), and SetOffset().
m_orientation
ORIENTATION CGUIBaseContainer::m_orientation protected
Referenced by CalculateLayout(), CGUIPanelContainer::CalculateLayout(), CGUIBaseContainer(), GetCondition(), CGUIPanelContainer::GetCondition(), CGUIFixedListContainer::GetCursorFromPoint(), CGUIListContainer::GetCursorFromPoint(), CGUIPanelContainer::GetCursorFromPoint(), CGUIPanelContainer::GetLabel(), GetListItem(), InsideLayout(), OnAction(), OnDown(), CGUIPanelContainer::OnDown(), OnLeft(), CGUIPanelContainer::OnLeft(), OnMouseEvent(), OnRight(), CGUIPanelContainer::OnRight(), OnUp(), CGUIPanelContainer::OnUp(), Process(), CGUIPanelContainer::Process(), Render(), CGUIPanelContainer::Render(), ScrollToOffset(), CGUIFixedListContainer::SelectItemFromPoint(), CGUIWrappingListContainer::SelectItemFromPoint(), Size(), CGUIFixedListContainer::ValidateOffset(), CGUIListContainer::ValidateOffset(), and CGUIPanelContainer::ValidateOffset().
m_pageChangeTimer
CStopWatch CGUIBaseContainer::m_pageChangeTimer private
Referenced by DoProcess(), GetCondition(), and OnMessage().
m_pageControl
int CGUIBaseContainer::m_pageControl protected
Referenced by CGUIBaseContainer(), OnMessage(), CGUIWrappingListContainer::OnMessage(), SetPageControl(), SetPageControlRange(), CGUIWrappingListContainer::SetPageControlRange(), UpdatePageControl(), and CGUIWrappingListContainer::UpdatePageControl().
m_renderOffset
CPoint CGUIBaseContainer::m_renderOffset protected
render offset of the first item in the list
See also
SetRenderOffset
Referenced by Process(), CGUIPanelContainer::Process(), Render(), CGUIPanelContainer::Render(), and SetRenderOffset().
m_scroller
CScroller CGUIBaseContainer::m_scroller protected
Referenced by CalculateLayout(), CGUIPanelContainer::CalculateLayout(), FreeResources(), GetCacheOffsets(), GetCondition(), GetListItem(), CGUIListContainer::OnMessage(), OnMouseEvent(), Process(), CGUIPanelContainer::Process(), Render(), CGUIPanelContainer::Render(), ScrollingDown(), ScrollingUp(), ScrollToOffset(), SetContainerMoving(), UpdateAutoScrolling(), UpdateScrollOffset(), CGUIFixedListContainer::ValidateOffset(), CGUIListContainer::ValidateOffset(), and CGUIPanelContainer::ValidateOffset().
m_scrollItemsPerFrame
float CGUIBaseContainer::m_scrollItemsPerFrame private
Referenced by CGUIBaseContainer(), and OnAction().
m_scrollTimer
CStopWatch CGUIBaseContainer::m_scrollTimer private
Referenced by GetCondition(), OnMouseEvent(), ScrollToOffset(), and UpdateScrollOffset().
m_unfocusActions
CGUIAction CGUIBaseContainer::m_unfocusActions private
Referenced by OnUnFocus(), and SetUnFocusActions().
m_waitForScrollEnd
bool CGUIBaseContainer::m_waitForScrollEnd = false private
Referenced by OnMouseEvent(), OnMouseOver(), and Process().
m_wasReset
bool CGUIBaseContainer::m_wasReset protected
Referenced by CGUIBaseContainer(), DoProcess(), Reset(), ScrollToOffset(), CGUIListContainer::SetCursor(), and CGUIPanelContainer::SetCursor().
The documentation for this class was generated from the following files:
GUIBaseContainer.h
GUIBaseContainer.cpp