Kodi Documentation: KODI::GAME::CGameClientCheevos Class Reference
KODI::GAME::CGameClientCheevos Class Reference
Games
#include <GameClientCheevos.h>
Public Member Functions
CGameClientCheevos (CGameClient &gameClient, AddonInstance_Game &addonStruct)
bool RCGenerateHashFromFile (std::string &hash, RETRO::RConsoleID consoleID, const std::string &filePath)
bool RCGetGameIDUrl (std::string &url, const std::string &hash)
bool RCGetPatchFileUrl (std::string &url, const std::string &username, const std::string &token, unsigned int gameID)
bool RCPostRichPresenceUrl (std::string &url, std::string &postData, const std::string &username, const std::string &token, unsigned gameID, const std::string &richPresence)
void RCEnableRichPresence (const std::string &script)
void RCGetRichPresenceEvaluation (std::string &evaluation, RETRO::RConsoleID consoleID)
void RCResetRuntime ()
Private Attributes
CGameClient & m_gameClient
AddonInstance_Game & m_struct
Constructor & Destructor Documentation
CGameClientCheevos()
CGameClientCheevos::CGameClientCheevos (CGameClient & gameClient, AddonInstance_Game & addonStruct)
Member Function Documentation
RCEnableRichPresence()
void CGameClientCheevos::RCEnableRichPresence (const std::string & script)
References GAME_ERROR_NO_ERROR, KODI::GAME::CGameClient::LogError(), KODI::GAME::CGameClient::LogException(), m_gameClient, m_struct, and AddonInstance_Game::toAddon.
Referenced by KODI::RETRO::CCheevos::EnableRichPresence().
RCGenerateHashFromFile()
bool CGameClientCheevos::RCGenerateHashFromFile (std::string & hash, RETRO::RConsoleID consoleID, const std::string & filePath)
References GAME_ERROR_NO_ERROR, KODI::GAME::CGameClient::LogError(), KODI::GAME::CGameClient::LogException(), m_gameClient, m_struct, and AddonInstance_Game::toAddon.
Referenced by KODI::RETRO::CCheevos::LoadData().
RCGetGameIDUrl()
bool CGameClientCheevos::RCGetGameIDUrl (std::string & url, const std::string & hash)
References GAME_ERROR_NO_ERROR, KODI::GAME::CGameClient::LogError(), KODI::GAME::CGameClient::LogException(), m_gameClient, m_struct, and AddonInstance_Game::toAddon.
Referenced by KODI::RETRO::CCheevos::LoadData().
RCGetPatchFileUrl()
bool CGameClientCheevos::RCGetPatchFileUrl (std::string & url, const std::string & username, const std::string & token, unsigned int gameID)
References GAME_ERROR_NO_ERROR, KODI::GAME::CGameClient::LogError(), KODI::GAME::CGameClient::LogException(), m_gameClient, m_struct, and AddonInstance_Game::toAddon.
Referenced by KODI::RETRO::CCheevos::LoadData().
RCGetRichPresenceEvaluation()
void CGameClientCheevos::RCGetRichPresenceEvaluation (std::string & evaluation, RETRO::RConsoleID consoleID)
References GAME_ERROR_NO_ERROR, KODI::GAME::CGameClient::LogError(), KODI::GAME::CGameClient::LogException(), m_gameClient, m_struct, and AddonInstance_Game::toAddon.
Referenced by KODI::RETRO::CCheevos::GetRichPresenceEvaluation().
RCPostRichPresenceUrl()
bool CGameClientCheevos::RCPostRichPresenceUrl (std::string & url, std::string & postData, const std::string & username, const std::string & token, unsigned gameID, const std::string & richPresence)
References GAME_ERROR_NO_ERROR, KODI::GAME::CGameClient::LogError(), KODI::GAME::CGameClient::LogException(), m_gameClient, m_struct, and AddonInstance_Game::toAddon.
Referenced by KODI::RETRO::CCheevos::GetRichPresenceEvaluation().
RCResetRuntime()
void CGameClientCheevos::RCResetRuntime ()
References GAME_ERROR_NO_ERROR, KODI::GAME::CGameClient::LogError(), KODI::GAME::CGameClient::LogException(), m_gameClient, m_struct, and AddonInstance_Game::toAddon.
Referenced by KODI::RETRO::CCheevos::ResetRuntime().
Member Data Documentation
m_gameClient
CGameClient& KODI::GAME::CGameClientCheevos::m_gameClient private
Referenced by RCEnableRichPresence(), RCGenerateHashFromFile(), RCGetGameIDUrl(), RCGetPatchFileUrl(), RCGetRichPresenceEvaluation(), RCPostRichPresenceUrl(), and RCResetRuntime().
m_struct
AddonInstance_Game& KODI::GAME::CGameClientCheevos::m_struct private
Referenced by RCEnableRichPresence(), RCGenerateHashFromFile(), RCGetGameIDUrl(), RCGetPatchFileUrl(), RCGetRichPresenceEvaluation(), RCPostRichPresenceUrl(), and RCResetRuntime().
The documentation for this class was generated from the following files:
GameClientCheevos.h
GameClientCheevos.cpp