Kodi Documentation: KODI::GAME::CGUIAgentControllerList Class Reference
KODI::GAME::CGUIAgentControllerList Class Reference
Games
#include <GUIAgentControllerList.h>
Public Member Functions
CGUIAgentControllerList (CGUIWindow &window)
~CGUIAgentControllerList () override
void OnWindowLoaded () override
Callback when the GUI window is loaded.
void OnWindowUnload () override
Callback when the GUI window is unloaded.
bool Initialize (GameClientPtr gameClient) override
Initialize resources.
void Deinitialize () override
Deinitialize resources.
bool HasControl (int controlId) const override
Query if a control with the given ID belongs to this list.
int GetCurrentControl () const override
Query the ID of the current control in this list.
void FrameMove () override
Called once per frame.
void Refresh () override
Refresh the contents of the list.
void SetFocused () override
The agent list has been focused in the GUI.
void OnSelect () override
The agent list has been selected in the GUI.
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
Public Member Functions inherited from KODI::GAME::IAgentControllerList
virtual ~IAgentControllerList ()=default
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Private Member Functions
void OnEvent (const ADDON::AddonEvent &event)
void AddItem (const CAgentController &agentController)
void CleanupItems ()
void OnItemFocus (unsigned int itemIndex)
void OnControllerFocus (const std::string &focusedAgent)
void OnItemSelect (unsigned int itemIndex)
void OnControllerSelect (const CFileItem &selectedAgentItem)
void ShowControllerDialog (const CAgentController &agentController)
Private Attributes
CGUIWindow & m_guiWindow
std::unique_ptr< CGUIViewControl > m_viewControl
std::unique_ptr< CFileItemList > m_vecItems
unsigned int m_currentItem {0}
std::string m_currentAgent
GameClientPtr m_gameClient
Constructor & Destructor Documentation
CGUIAgentControllerList()
CGUIAgentControllerList::CGUIAgentControllerList (CGUIWindow & window)
~CGUIAgentControllerList()
CGUIAgentControllerList::~CGUIAgentControllerList () override
References Deinitialize().
Member Function Documentation
AddItem()
void CGUIAgentControllerList::AddItem (const CAgentController & agentController) private
References KODI::GAME::CAgentController::GetController(), KODI::GAME::CAgentController::GetPeripheralLocation(), KODI::GAME::CAgentController::GetPeripheralName(), label, and m_vecItems.
Referenced by Refresh().
CleanupItems()
void CGUIAgentControllerList::CleanupItems () private
References m_vecItems.
Referenced by Deinitialize(), and Refresh().
Deinitialize()
void CGUIAgentControllerList::Deinitialize () override virtual
Deinitialize resources.
Implements KODI::GAME::IAgentControllerList.
References KODI::GAME::CGameServices::AgentInput(), CleanupItems(), ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), CServiceBroker::GetGameServices(), CServiceBroker::IsServiceManagerUp(), m_gameClient, and Observable::UnregisterObserver().
Referenced by ~CGUIAgentControllerList().
FrameMove()
void CGUIAgentControllerList::FrameMove () override virtual
Called once per frame.
This allows the list to update its currently focused item.
Implements KODI::GAME::IAgentControllerList.
References CONTROL_AGENT_CONTROLLER_LIST, CGUIControlLookup::GetControl(), CGUIBaseContainer::GetSelectedItem(), m_currentItem, m_guiWindow, and OnItemFocus().
GetCurrentControl()
int CGUIAgentControllerList::GetCurrentControl () const override virtual
Query the ID of the current control in this list.
Implements KODI::GAME::IAgentControllerList.
References m_viewControl.
HasControl()
bool CGUIAgentControllerList::HasControl (int controlId) const override virtual
Query if a control with the given ID belongs to this list.
Implements KODI::GAME::IAgentControllerList.
References m_viewControl.
Initialize()
bool CGUIAgentControllerList::Initialize (GameClientPtr gameClient) override virtual
Initialize resources.
Parameters
gameClient The active game client, an empty pointer if no game client is active
Returns
True if the resource is initialized and can be used, false if the resource failed to initialize and must not be used
Implements KODI::GAME::IAgentControllerList.
References KODI::GAME::CGameServices::AgentInput(), DEFAULT_VIEW_LIST, ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), CServiceBroker::GetGameServices(), CServiceBroker::IsServiceManagerUp(), m_gameClient, m_viewControl, OnEvent(), Refresh(), and Observable::RegisterObserver().
Notify()
void CGUIAgentControllerList::Notify (const Observable & obs, const ObservableMessage msg) override virtual
Process a message from an observable.
Parameters
obs The observable that sends the message.
msg The message.
Implements Observer.
References CONTROL_AGENT_CONTROLLER_LIST, CServiceBroker::GetAppMessenger(), CGUIControl::GetID(), GUI_MSG_REFRESH_LIST, m_guiWindow, ObservableMessageAgentControllersChanged, and ObservableMessageGamePortsChanged.
OnControllerFocus()
void CGUIAgentControllerList::OnControllerFocus (const std::string & focusedAgent) private
References m_currentAgent.
Referenced by OnItemFocus().
OnControllerSelect()
void CGUIAgentControllerList::OnControllerSelect (const CFileItem & selectedAgentItem) private
References KODI::GAME::CGameServices::AgentInput(), KODI::GAME::CAgentInput::GetControllers(), CServiceBroker::GetGameServices(), CFileItem::GetPath(), CLog::Log(), LOGERROR, ShowControllerDialog(), and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by OnItemSelect().
OnEvent()
void CGUIAgentControllerList::OnEvent (const ADDON::AddonEvent & event) private
References ADDON::AddonEvent::addonId, CONTROL_AGENT_CONTROLLER_LIST, CServiceBroker::GetAppMessenger(), CGUIControl::GetID(), GUI_MSG_REFRESH_LIST, m_guiWindow, and CGUIMessage::SetStringParam().
Referenced by Initialize().
OnItemFocus()
void CGUIAgentControllerList::OnItemFocus (unsigned int itemIndex) private
References m_currentItem, m_vecItems, and OnControllerFocus().
Referenced by FrameMove().
OnItemSelect()
void CGUIAgentControllerList::OnItemSelect (unsigned int itemIndex) private
References m_vecItems, and OnControllerSelect().
Referenced by OnSelect().
OnSelect()
void CGUIAgentControllerList::OnSelect () override virtual
The agent list has been selected in the GUI.
Implements KODI::GAME::IAgentControllerList.
References m_viewControl, and OnItemSelect().
OnWindowLoaded()
void CGUIAgentControllerList::OnWindowLoaded () override virtual
Callback when the GUI window is loaded.
Implements KODI::GAME::IAgentControllerList.
References CONTROL_AGENT_CONTROLLER_LIST, CGUIControlLookup::GetControl(), CGUIControl::GetID(), m_guiWindow, and m_viewControl.
OnWindowUnload()
void CGUIAgentControllerList::OnWindowUnload () override virtual
Callback when the GUI window is unloaded.
Implements KODI::GAME::IAgentControllerList.
References m_viewControl.
Refresh()
void CGUIAgentControllerList::Refresh () override virtual
Refresh the contents of the list.
Implements KODI::GAME::IAgentControllerList.
References AddItem(), KODI::GAME::CGameServices::AgentInput(), CleanupItems(), g_localizeStrings, CLocalizeStrings::Get(), KODI::GAME::CAgentInput::GetControllers(), CServiceBroker::GetGameServices(), m_currentAgent, m_vecItems, and m_viewControl.
Referenced by Initialize().
SetFocused()
void CGUIAgentControllerList::SetFocused () override virtual
The agent list has been focused in the GUI.
Implements KODI::GAME::IAgentControllerList.
References m_viewControl.
ShowControllerDialog()
void CGUIAgentControllerList::ShowControllerDialog (const CAgentController & agentController) private
References PERIPHERALS::CPeripherals::GetDirectory(), CServiceBroker::GetGUI(), KODI::GAME::CAgentController::GetPeripheral(), CServiceBroker::GetPeripherals(), CGUIComponent::GetWindowManager(), CFileItemList::IsEmpty(), CLog::Log(), LOGERROR, Observable::NotifyObservers(), ObservableMessagePeripheralsChanged, CGUIDialog::Open(), PERIPHERALS::CGUIDialogPeripheralSettings::RegisterPeripheralManager(), Observable::SetChanged(), PERIPHERALS::CGUIDialogPeripheralSettings::SetFileItem(), CGUIWindow::SetProperty(), CFileItemList::Size(), PERIPHERALS::CGUIDialogPeripheralSettings::UnregisterPeripheralManager(), and WINDOW_DIALOG_PERIPHERAL_SETTINGS.
Referenced by OnControllerSelect().
Member Data Documentation
m_currentAgent
std::string KODI::GAME::CGUIAgentControllerList::m_currentAgent private
Referenced by OnControllerFocus(), and Refresh().
m_currentItem
unsigned int KODI::GAME::CGUIAgentControllerList::m_currentItem {0} private
Referenced by FrameMove(), and OnItemFocus().
m_gameClient
GameClientPtr KODI::GAME::CGUIAgentControllerList::m_gameClient private
Referenced by Deinitialize(), and Initialize().
m_guiWindow
CGUIWindow& KODI::GAME::CGUIAgentControllerList::m_guiWindow private
Referenced by FrameMove(), Notify(), OnEvent(), and OnWindowLoaded().
m_vecItems
std::unique_ptr<CFileItemList> KODI::GAME::CGUIAgentControllerList::m_vecItems private
Referenced by AddItem(), CleanupItems(), OnItemFocus(), OnItemSelect(), and Refresh().
m_viewControl
std::unique_ptr<CGUIViewControl> KODI::GAME::CGUIAgentControllerList::m_viewControl private
Referenced by GetCurrentControl(), HasControl(), Initialize(), OnSelect(), OnWindowLoaded(), OnWindowUnload(), Refresh(), and SetFocused().
The documentation for this class was generated from the following files:
GUIAgentControllerList.h
GUIAgentControllerList.cpp