Kodi Documentation: PVR::CPVREpgSearch Class Reference
PVR::CPVREpgSearch Class Reference
#include <EpgSearch.h>
Public Member Functions
CPVREpgSearch ()=delete
CPVREpgSearch (CPVREpgSearchFilter &filter)
ctor.
void Execute ()
Execute the search.
const std::vector< std::shared_ptr< CPVREpgInfoTag > > & GetResults () const
Get the last search results.
Private Attributes
CCriticalSection m_critSection
CPVREpgSearchFilter & m_filter
std::vector< std::shared_ptr< CPVREpgInfoTag > > m_results
Constructor & Destructor Documentation
CPVREpgSearch() [1/2]
PVR::CPVREpgSearch::CPVREpgSearch () delete
CPVREpgSearch() [2/2]
PVR::CPVREpgSearch::CPVREpgSearch (CPVREpgSearchFilter & filter) inline explicit
ctor.
Parameters
filter The filter defining the search criteria.
Member Function Documentation
Execute()
void CPVREpgSearch::Execute ()
Execute the search.
References PVR::CPVRManager::EpgContainer(), PVR::CPVREpgSearchFilter::GetEpgSearchData(), CServiceBroker::GetPVRManager(), PVR::CPVREpgContainer::GetTags(), CDateTime::GetUTCDateTime(), m_critSection, m_filter, m_results, PVR::CPVREpgSearchFilter::RemoveDuplicates(), PVR::CPVREpgSearchFilter::SetEpgSearchDataFiltered(), PVR::CPVREpgSearchFilter::SetLastExecutedDateTime(), PVR::CPVREpgSearchFilter::ShouldRemoveDuplicates(), and tags.
Referenced by PVR::CPVRGUIDirectory::GetSavedSearchResults(), and anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction::Run().
GetResults()
const std::vector< std::shared_ptr< CPVREpgInfoTag > > & CPVREpgSearch::GetResults () const
Get the last search results.
Returns
the results.
References m_critSection, and m_results.
Referenced by PVR::CPVRGUIDirectory::GetSavedSearchResults(), and anonymous_namespace{GUIWindowPVRSearch.cpp}::AsyncSearchAction::Run().
Member Data Documentation
m_critSection
CCriticalSection PVR::CPVREpgSearch::m_critSection mutable private
Referenced by Execute(), and GetResults().
m_filter
CPVREpgSearchFilter& PVR::CPVREpgSearch::m_filter private
Referenced by Execute().
m_results
std::vector<std::shared_ptr<CPVREpgInfoTag> > PVR::CPVREpgSearch::m_results private
Referenced by Execute(), and GetResults().
The documentation for this class was generated from the following files:
EpgSearch.h
EpgSearch.cpp