Kodi Documentation: CGUIWindowFileManager Class Reference
CGUIWindowFileManager Class Reference
#include <GUIWindowFileManager.h>
Classes
class CUpdateGuard
Public Member Functions
CGUIWindowFileManager (void)
~CGUIWindowFileManager (void) override
bool OnMessage (CGUIMessage &message) override
bool OnAction (const CAction &action) override
bool OnBack (int actionID) override
const CFileItem & CurrentDirectory (int indx) const
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsDialog () const
virtual bool IsDialogRunning () const
virtual bool IsModalDialog () const
virtual bool IsMediaWindow () const
virtual bool HasListItems () const
virtual bool IsSoundEnabled () const
virtual CFileItemPtr GetCurrentListItem (int offset=0)
virtual int GetViewContainerID () const
virtual int GetViewCount () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
virtual void OnDeinitWindow (int nextWindowID)
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual CGUIControl * GetFirstFocusableControl (int id)
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Public Member Functions inherited from CJobQueue
CJobQueue (bool lifo=false, unsigned int jobsAtOnce=1, CJob::PRIORITY priority=CJob::PRIORITY_LOW)
CJobQueue constructor.
~CJobQueue () override
CJobQueue destructor Cancels any in-process jobs, and destroys the job queue.
bool AddJob (CJob *job)
Add a job to the queue On completion of the job, destruction of the job queue or in case the job could not be added successfully, the CJob object will be destroyed.
template<typename F >
void Submit (F &&f)
Add a function f to this job queue.
void CancelJob (const CJob *job)
Cancel a job in the queue Cancels a job in the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed. If the job is only queued then it will be removed from the queue and deleted.
void CancelJobs ()
Cancel all jobs in the queue Removes all jobs from the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed.
bool IsProcessing () const
Check whether the queue is processing a job.
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
void OnJobAbort (unsigned int jobID, CJob *job) override
The callback used when a job will be aborted.
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Static Public Member Functions
static int64_t CalculateFolderSize (const std::string &strDirectory, CGUIDialogProgress *pProgress=NULL)
Protected Types
typedef std::vector< CFileItem * >::iterator ivecItems
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Protected Member Functions
void OnInitWindow () override
Called on window open.
void SetInitialPath (const std::string &path)
void GoParentFolder (int iList)
void UpdateControl (int iList, int item)
bool Update (int iList, const std::string &strDirectory)
void OnStart (CFileItem *pItem, const std::string &player)
bool SelectItem (int iList, int &item)
void ClearFileItems (int iList)
void OnClick (int iList, int iItem)
void OnMark (int iList, int iItem)
void OnSort (int iList)
void UpdateButtons ()
void OnCopy (int iList)
void OnMove (int iList)
void OnDelete (int iList)
void OnRename (int iList)
void OnSelectAll (int iList)
void OnNewFolder (int iList)
void Refresh ()
void Refresh (int iList)
int GetSelectedItem (int iList)
bool HaveDiscOrConnection (std::string &strPath, int iDriveType)
void GetDirectoryHistoryString (const CFileItem *pItem, std::string &strHistoryString)
Build a directory history string.
bool GetDirectory (int iList, const std::string &strDirectory, CFileItemList &items)
int NumSelected (int iList)
int GetFocusedList () const
bool CanRename (int iList)
bool CanCopy (int iList)
bool CanMove (int iList)
bool CanDelete (int iList)
bool CanNewFolder (int iList)
void OnPopupMenu (int iList, int iItem, bool bContextDriven=true)
void ShowShareErrorMessage (CFileItem *pItem)
void UpdateItemCounts ()
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual bool Load (TiXmlElement *pRootElement)
Loads the window from the given XML element.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void SetDefaults ()
virtual void OnWindowUnload ()
virtual void OnWindowLoaded ()
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
virtual void SaveControlStates ()
virtual void RestoreControlStates ()
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Member Functions inherited from CJobQueue
bool QueueEmpty () const
Returns if we still have jobs waiting to be processed NOTE: This function does not take into account the jobs that are currently processing.
Protected Attributes
bool bCheckShareConnectivity
std::string strCheckSharePath
XFILE::CVirtualDirectory m_rootDir
CFileItemList * m_vecItems [2]
CFileItem * m_Directory [2]
std::string m_strParentPath [2]
CDirectoryHistory m_history [2]
int m_errorHeading
int m_errorLine
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Private Attributes
std::atomic_bool m_updating = {false}
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Typedef Documentation
ivecItems
typedef std::vector<CFileItem*>::iterator CGUIWindowFileManager::ivecItems protected
Constructor & Destructor Documentation
CGUIWindowFileManager()
CGUIWindowFileManager::CGUIWindowFileManager (void)
References bCheckShareConnectivity, CGUIWindow::KEEP_IN_MEMORY, CGUIListItem::m_bIsFolder, m_Directory, CGUIWindow::m_loadType, m_vecItems, and CFileItem::SetPath().
~CGUIWindowFileManager()
CGUIWindowFileManager::~CGUIWindowFileManager (void) override
References m_Directory, and m_vecItems.
Member Function Documentation
CalculateFolderSize()
int64_t CGUIWindowFileManager::CalculateFolderSize (const std::string & strDirectory, CGUIDialogProgress * pProgress = NULL) static
References CalculateFolderSize(), XFILE::CVirtualDirectory::GetDirectory(), CMediaSourceSettings::GetInstance(), int64_t(), CGUIDialogProgress::IsCanceled(), CFileItem::m_dwSize, CGUIDialogProgress::Progress(), CGUIDialogBoxBase::SetLine(), XFILE::CVirtualDirectory::SetSources(), and CFileItemList::Size().
Referenced by CalculateFolderSize(), and OnPopupMenu().
CanCopy()
bool CGUIWindowFileManager::CanCopy (int iList) protected
Todo:
Perhaps if the source is removeable media (DVD/CD etc.) we could put ripping/backup in here.
References m_Directory, and CUtil::SupportsReadFileOperations().
Referenced by OnAction(), and OnPopupMenu().
CanDelete()
bool CGUIWindowFileManager::CanDelete (int iList) protected
References m_Directory.
Referenced by OnAction(), and OnPopupMenu().
CanMove()
bool CGUIWindowFileManager::CanMove (int iList) protected
References m_Directory.
Referenced by OnAction(), and OnPopupMenu().
CanNewFolder()
bool CGUIWindowFileManager::CanNewFolder (int iList) protected
References m_Directory.
Referenced by OnPopupMenu().
CanRename()
bool CGUIWindowFileManager::CanRename (int iList) protected
Todo:
Renaming of shares (requires writing to sources.xml) this might be able to be done via the webserver code stuff...
References m_Directory.
Referenced by OnAction(), and OnPopupMenu().
ClearFileItems()
void CGUIWindowFileManager::ClearFileItems (int iList) protected
References CFileItemList::Clear(), CONTROL_LEFT_LIST, CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_RESET, m_vecItems, and CGUIWindowManager::SendMessage().
Referenced by OnMessage(), and Update().
CurrentDirectory()
const CFileItem & CGUIWindowFileManager::CurrentDirectory (int indx) const
References m_Directory.
GetDirectory()
bool CGUIWindowFileManager::GetDirectory (int iList, const std::string & strDirectory, CFileItemList & items) protected
References m_rootDir, and CGUIDialogBusy::Wait().
Referenced by Update().
GetDirectoryHistoryString()
void CGUIWindowFileManager::GetDirectoryHistoryString (const CFileItem * pItem, std::string & strHistoryString) protected
Build a directory history string.
Parameters
pItem Item to build the history string from
strHistoryString History string build as return value
References CGUIListItem::GetLabel(), CFileItem::GetPath(), CFileItem::m_bIsShareOrDrive, CFileItem::m_iDriveType, URIUtils::RemoveSlashAtEnd(), and CMediaSource::SOURCE_TYPE_OPTICAL_DISC.
Referenced by Update().
GetFocusedList()
int CGUIWindowFileManager::GetFocusedList () const protected
References CONTROL_LEFT_LIST, and CGUIControlGroup::GetFocusedControlID().
Referenced by HaveDiscOrConnection(), OnAction(), OnBack(), and Refresh().
GetSelectedItem()
int CGUIWindowFileManager::GetSelectedItem (int iList) protected
References CONTROL_LEFT_LIST, CGUIControl::GetID(), CGUIMessage::GetParam1(), GUI_MSG_ITEM_SELECTED, m_vecItems, and OnMessage().
Referenced by HaveDiscOrConnection(), OnAction(), OnMessage(), Refresh(), Refresh(), SelectItem(), and Update().
GoParentFolder()
void CGUIWindowFileManager::GoParentFolder (int iList) protected
References g_ZipManager, CURL::GetFileName(), CURL::IsProtocol(), m_Directory, m_strParentPath, CZipManager::release(), and Update.
Referenced by OnAction(), and OnBack().
HaveDiscOrConnection()
bool CGUIWindowFileManager::HaveDiscOrConnection (std::string & strPath, int iDriveType) protected
Todo:
Handle not connected to a remote share
References CONTROL_LEFT_LIST, CONTROL_SELECT_ITEM, GetFocusedList(), CServiceBroker::GetMediaManager(), CServiceBroker::GetNetwork(), GetSelectedItem(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), CMediaSource::SOURCE_TYPE_OPTICAL_DISC, CMediaSource::SOURCE_TYPE_REMOTE, and Update.
Referenced by OnClick().
NumSelected()
int CGUIWindowFileManager::NumSelected (int iList) protected
References m_vecItems, and CFileItemList::Size().
Referenced by OnPopupMenu(), and SelectItem().
OnAction()
bool CGUIWindowFileManager::OnAction (const CAction & action) override virtual
Reimplemented from CGUIWindow.
References ACTION_CONTEXT_MENU, ACTION_COPY_ITEM, ACTION_DELETE_ITEM, ACTION_MOVE_ITEM, ACTION_PARENT_DIR, ACTION_PLAYER_PLAY, ACTION_RENAME_ITEM, CanCopy(), CanDelete(), CanMove(), CanRename(), CFileItemList::Get(), GetFocusedList(), GetSelectedItem(), GoParentFolder(), m_vecItems, CGUIWindow::OnAction(), OnCopy(), OnDelete(), OnMove(), OnPopupMenu(), OnRename(), SelectItem(), and CFileItemList::Size().
OnBack()
bool CGUIWindowFileManager::OnBack (int actionID) override virtual
Reimplemented from CGUIWindow.
References ACTION_NAV_BACK, GetFocusedList(), GoParentFolder(), m_vecItems, and CGUIControl::OnBack().
OnClick()
void CGUIWindowFileManager::OnClick (int iList, int iItem) protected
References XFILE::CFileDirectoryFactory::Create(), URIUtils::CreateArchivePath(), EFILEFOLDER_MASK_ALL, g_localizeStrings, g_passwordManager, CURL::Get(), CFileItemList::Get(), CLocalizeStrings::Get(), CMediaSourceSettings::GetInstance(), HaveDiscOrConnection(), CGUIPassword::IsItemUnlocked(), m_Directory, m_rootDir, m_vecItems, OnStart(), Refresh(), XFILE::CVirtualDirectory::SetSources(), CGUIDialogMediaSource::ShowAndAddMediaSource(), ShowShareErrorMessage(), and Update.
Referenced by OnMessage().
OnCopy()
void CGUIWindowFileManager::OnCopy (int iList) protected
References CFileOperationJob::ActionCopy, CJobQueue::AddJob(), m_Directory, m_vecItems, and CGUIDialogYesNo::ShowAndGetInput().
Referenced by OnAction(), and OnPopupMenu().
OnDelete()
void CGUIWindowFileManager::OnDelete (int iList) protected
References CFileOperationJob::ActionDelete, CJobQueue::AddJob(), m_Directory, m_vecItems, and CGUIDialogYesNo::ShowAndGetInput().
Referenced by OnAction(), and OnPopupMenu().
OnInitWindow()
void CGUIWindowFileManager::OnInitWindow (void) override protected virtual
Called on window open.
Restores the control state(s)
Sets initial visibility of controls
Queue WindowOpen animation
Set overlay state Override this function and do any window-specific initialisation such as filling control contents and setting control focus before calling the base method.
Reimplemented from CGUIWindow.
References bCheckShareConnectivity, m_Directory, CGUIWindow::OnInitWindow(), ShowShareErrorMessage(), strCheckSharePath, and Update.
OnJobComplete()
void CGUIWindowFileManager::OnJobComplete (unsigned int jobID, bool success, CJob * job) override virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
References CServiceBroker::GetAppMessenger(), CFileOperationJob::GetHeading(), CGUIControl::GetID(), CFileOperationJob::GetLine(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE, CGUIWindow::IsActive(), CJobQueue::OnJobComplete(), KODI::MESSAGING::HELPERS::ShowOKDialogLines(), and success.
OnMark()
void CGUIWindowFileManager::OnMark (int iList, int iItem) protected
References CFileItemList::Get(), m_vecItems, and UpdateItemCounts().
Referenced by OnMessage().
OnMessage()
bool CGUIWindowFileManager::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIWindow.
References ACTION_CONTEXT_MENU, ACTION_HIGHLIGHT_ITEM, ACTION_MOUSE_DOUBLE_CLICK, ACTION_MOUSE_LEFT_CLICK, ACTION_MOUSE_RIGHT_CLICK, ACTION_SELECT_ITEM, ClearFileItems(), CONTROL_LEFT_LIST, CONTROL_RIGHT_LIST, CONTROL_SELECT_ITEM, CServiceBroker::GetGUI(), CGUIControl::GetID(), CServiceBroker::GetInputManager(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CFileItem::GetPath(), GetSelectedItem(), CGUIMessage::GetSenderId(), CGUIMessage::GetStringParam(), CGUIComponent::GetWindowManager(), GUI_MSG_CLICKED, GUI_MSG_GESTURE_NOTIFY, GUI_MSG_ITEM_SELECT, GUI_MSG_NOTIFY_ALL, GUI_MSG_PLAYBACK_ENDED, GUI_MSG_PLAYBACK_STARTED, GUI_MSG_PLAYBACK_STOPPED, GUI_MSG_PLAYLIST_CHANGED, GUI_MSG_PLAYLISTPLAYER_CHANGED, GUI_MSG_PLAYLISTPLAYER_STARTED, GUI_MSG_PLAYLISTPLAYER_STOPPED, GUI_MSG_REFRESH_LIST, GUI_MSG_REMOVED_MEDIA, GUI_MSG_UNFOCUS_ALL, GUI_MSG_UPDATE, GUI_MSG_UPDATE_SOURCES, GUI_MSG_WINDOW_DEINIT, GUI_MSG_WINDOW_INIT, GUI_MSG_WINDOW_RESET, CGUIWindow::IsActive(), XFILE::CVirtualDirectory::IsInSource(), CGUIListItem::m_bIsFolder, m_Directory, m_rootDir, OnClick(), OnMark(), CGUIWindow::OnMessage(), OnMessage(), OnPopupMenu(), Refresh(), CGUIWindowManager::SendMessage(), SetInitialPath(), CFileItem::SetPath(), CGUIMessage::SetStringParam(), and Update.
Referenced by GetSelectedItem(), and OnMessage().
OnMove()
void CGUIWindowFileManager::OnMove (int iList) protected
References CFileOperationJob::ActionMove, CJobQueue::AddJob(), m_Directory, m_vecItems, and CGUIDialogYesNo::ShowAndGetInput().
Referenced by OnAction(), and OnPopupMenu().
OnNewFolder()
void CGUIWindowFileManager::OnNewFolder (int iList) protected
References URIUtils::AddSlashAtEnd(), CONTROL_LEFT_LIST, CONTROL_SELECT_ITEM, XFILE::CDirectory::Create(), g_localizeStrings, CFileItemList::Get(), CLocalizeStrings::Get(), CFileItem::GetPath(), m_Directory, m_vecItems, Refresh(), URIUtils::RemoveSlashAtEnd(), CGUIKeyboardFactory::ShowAndGetInput(), and CFileItemList::Size().
Referenced by OnPopupMenu().
OnPopupMenu()
void CGUIWindowFileManager::OnPopupMenu (int iList, int iItem, bool bContextDriven = true) protected
Todo:
We should add the option here for shares to be added if there aren't any
References CContextButtons::Add(), CFavouritesService::AddOrRemove(), CalculateFolderSize(), CanCopy(), CanDelete(), CanMove(), CanNewFolder(), CanRename(), CONTROL_BTNCALCSIZE, CONTROL_BTNCANCELJOB, CONTROL_BTNCOPY, CONTROL_BTNDELETE, CONTROL_BTNFAVOURITES, CONTROL_BTNMOVE, CONTROL_BTNNEWFOLDER, CONTROL_BTNPLAYWITH, CONTROL_BTNRENAME, CONTROL_BTNSELECTALL, CONTROL_BTNSWITCHMEDIA, CONTROL_BTNVIEW, CONTROL_LEFT_LIST, CFileItemList::Get(), CGUIControlLookup::GetControl(), CServiceBroker::GetFavouritesService(), CServiceBroker::GetGUI(), CGUIControl::GetHeight(), CGUIControl::GetID(), CMediaSourceSettings::GetInstance(), CServiceBroker::GetJobManager(), CServiceBroker::GetPlayerCoreFactory(), CPlayerCoreFactory::GetPlayers(), CFileItemList::GetSelectedCount(), CServiceBroker::GetSettingsComponent(), CGUIControl::GetWidth(), CGUIComponent::GetWindowManager(), CGUIControl::GetXPosition(), CGUIControl::GetYPosition(), int64_t(), m_Directory, m_rootDir, m_vecItems, NumSelected(), OnCopy(), OnDelete(), OnMove(), OnNewFolder(), OnRename(), OnSelectAll(), OnStart(), CGUIDialogProgress::Open(), Refresh(), SelectItem(), CPlayerCoreFactory::SelectPlayerDialog(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), XFILE::CVirtualDirectory::SetSources(), CSettings::SETTING_FILELISTS_SHOWPARENTDIRITEMS, CGUIDialogContextMenu::ShowAndGetChoice(), CFileItemList::Size(), CGUIDialogContextMenu::SourcesMenu(), and WINDOW_DIALOG_PROGRESS.
Referenced by OnAction(), and OnMessage().
OnRename()
void CGUIWindowFileManager::OnRename (int iList) protected
References CFileItemList::Get(), m_vecItems, Refresh(), CFileUtils::RenameFile(), and CFileItemList::Size().
Referenced by OnAction(), and OnPopupMenu().
OnSelectAll()
void CGUIWindowFileManager::OnSelectAll (int iList) protected
References CFileItemList::Get(), m_vecItems, and CFileItemList::Size().
Referenced by OnPopupMenu().
OnSort()
void CGUIWindowFileManager::OnSort (int iList) protected
References CFileItemList::Get(), CServiceBroker::GetMediaManager(), CMediaManager::IsDiscInDrive(), m_vecItems, CFileItemList::Size(), CFileItemList::Sort(), SortByLabel, and SortOrderAscending.
Referenced by Update().
OnStart()
void CGUIWindowFileManager::OnStart (CFileItem * pItem, const std::string & player) protected
Todo:
2.0: Can this be removed, or should we run without the "special" file directories while
References CGUIWindowManager::ActivateWindow(), CSlideShowDelegator::Add(), KODI::PLAYLIST::CPlayListFactory::Create(), CScriptInvocationManager::ExecuteAsync(), g_application, CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CScriptInvocationManager::GetInstance(), CFileItem::GetPath(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetSlideShowDelegator(), CGUIComponent::GetWindowManager(), KODI::MUSIC::IsAudio(), CFileItem::IsGame(), CFileItem::IsPicture(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsPythonScript(), CFileItem::IsType(), KODI::PLAYLIST::CPlayListPlayer::Play(), CSlideShowDelegator::Reset(), CSlideShowDelegator::Select(), CGUIDialogTextViewer::ShowForFile(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and WINDOW_SLIDESHOW.
Referenced by OnClick(), and OnPopupMenu().
Refresh() [1/2]
void CGUIWindowFileManager::Refresh () protected
References CONTROL_LEFT_LIST, CONTROL_SELECT_ITEM, GetFocusedList(), GetSelectedItem(), m_Directory, m_vecItems, and Update.
Referenced by OnClick(), OnMessage(), OnNewFolder(), OnPopupMenu(), and OnRename().
Refresh() [2/2]
void CGUIWindowFileManager::Refresh (int iList) protected
References CONTROL_LEFT_LIST, CONTROL_SELECT_ITEM, GetSelectedItem(), m_Directory, m_vecItems, and Update.
SelectItem()
bool CGUIWindowFileManager::SelectItem (int iList, int & item) protected
References CFileItemList::Get(), GetSelectedItem(), m_vecItems, and NumSelected().
Referenced by OnAction(), and OnPopupMenu().
SetInitialPath()
void CGUIWindowFileManager::SetInitialPath (const std::string & path) protected
References bCheckShareConnectivity, CMediaSourceSettings::GetInstance(), CUtil::GetMatchingSource(), CFileItem::GetPath(), XFILE::CVirtualDirectory::GetSources(), CLog::Log(), LOGERROR, LOGINFO, m_Directory, m_rootDir, URIUtils::PathHasParent(), URIUtils::RemoveSlashAtEnd(), CFileItem::SetPath(), XFILE::CVirtualDirectory::SetSources(), strCheckSharePath, and Update.
Referenced by OnMessage().
ShowShareErrorMessage()
void CGUIWindowFileManager::ShowShareErrorMessage (CFileItem * pItem) protected
References CURL::GetHostName(), CFileItem::GetPath(), CURL::IsProtocol(), URIUtils::IsRemote(), CFileItem::m_iDriveType, KODI::MESSAGING::HELPERS::ShowOKDialogText(), and CMediaSource::SOURCE_TYPE_REMOTE.
Referenced by OnClick(), and OnInitWindow().
Update()
bool CGUIWindowFileManager::Update (int iList, const std::string & strDirectory) protected
References CFileItemList::Add(), CFileItemList::AddFront(), CFileItemList::Append(), ClearFileItems(), CFileItemList::FillInDefaultIcons(), g_localizeStrings, CFileItemList::Get(), CLocalizeStrings::Get(), GetDirectory(), GetDirectoryHistoryString(), URIUtils::GetParentPath(), CFileItem::GetPath(), CDirectoryHistory::GetSelectedItem(), GetSelectedItem(), CServiceBroker::GetSettingsComponent(), URIUtils::HasExtension(), CFileItemList::IsEmpty(), XFILE::CVirtualDirectory::IsSource(), CLog::Log(), LOGWARNING, m_Directory, m_history, m_rootDir, m_strParentPath, m_updating, m_vecItems, OnSort(), CFileItem::SetPath(), CDirectoryHistory::SetSelectedItem(), CSettings::SETTING_FILELISTS_SHOWADDSOURCEBUTTONS, CSettings::SETTING_FILELISTS_SHOWPARENTDIRITEMS, CFileItemList::Size(), SortSpecialOnBottom, Update, UpdateButtons(), and UpdateControl().
UpdateButtons()
void CGUIWindowFileManager::UpdateButtons () protected
References CONTROL_CURRENTDIRLABEL_LEFT, CONTROL_CURRENTDIRLABEL_RIGHT, g_localizeStrings, CLocalizeStrings::Get(), CURL::GetWithoutUserDetails(), m_Directory, SET_CONTROL_LABEL, and UpdateItemCounts().
Referenced by Update().
UpdateControl()
void CGUIWindowFileManager::UpdateControl (int iList, int item) protected
References CONTROL_LEFT_LIST, CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIComponent::GetWindowManager(), GUI_MSG_LABEL_BIND, m_vecItems, and CGUIWindowManager::SendMessage().
Referenced by Update().
UpdateItemCounts()
void CGUIWindowFileManager::UpdateItemCounts () protected
References CONTROL_NUMFILES_LEFT, g_localizeStrings, CFileItemList::Get(), CLocalizeStrings::Get(), int64_t(), m_vecItems, SET_CONTROL_LABEL, and CFileItemList::Size().
Referenced by OnMark(), and UpdateButtons().
Member Data Documentation
bCheckShareConnectivity
bool CGUIWindowFileManager::bCheckShareConnectivity protected
Referenced by CGUIWindowFileManager(), OnInitWindow(), and SetInitialPath().
m_Directory
CFileItem* CGUIWindowFileManager::m_Directory[2] protected
Referenced by CanCopy(), CanDelete(), CanMove(), CanNewFolder(), CanRename(), CGUIWindowFileManager(), CurrentDirectory(), GoParentFolder(), OnClick(), OnCopy(), OnDelete(), OnInitWindow(), OnMessage(), OnMove(), OnNewFolder(), OnPopupMenu(), Refresh(), Refresh(), SetInitialPath(), Update(), UpdateButtons(), and ~CGUIWindowFileManager().
m_errorHeading
int CGUIWindowFileManager::m_errorHeading protected
m_errorLine
int CGUIWindowFileManager::m_errorLine protected
m_history
CDirectoryHistory CGUIWindowFileManager::m_history[2] protected
Referenced by Update().
m_rootDir
XFILE::CVirtualDirectory CGUIWindowFileManager::m_rootDir protected
Referenced by GetDirectory(), OnClick(), OnMessage(), OnPopupMenu(), SetInitialPath(), and Update().
m_strParentPath
std::string CGUIWindowFileManager::m_strParentPath[2] protected
Referenced by GoParentFolder(), and Update().
m_updating
std::atomic_bool CGUIWindowFileManager::m_updating = {false} private
Referenced by Update().
m_vecItems
CFileItemList* CGUIWindowFileManager::m_vecItems[2] protected
Referenced by CGUIWindowFileManager(), ClearFileItems(), GetSelectedItem(), NumSelected(), OnAction(), OnBack(), OnClick(), OnCopy(), OnDelete(), OnMark(), OnMove(), OnNewFolder(), OnPopupMenu(), OnRename(), OnSelectAll(), OnSort(), Refresh(), Refresh(), SelectItem(), Update(), UpdateControl(), UpdateItemCounts(), and ~CGUIWindowFileManager().
strCheckSharePath
std::string CGUIWindowFileManager::strCheckSharePath protected
Referenced by OnInitWindow(), and SetInitialPath().
The documentation for this class was generated from the following files:
GUIWindowFileManager.h
GUIWindowFileManager.cpp