Kodi Documentation: ADDON::CGUIAddonRenderingControl Class Reference
ADDON::CGUIAddonRenderingControl Class Reference
#include <Rendering.h>
Public Member Functions
CGUIAddonRenderingControl (CGUIRenderingControl *pControl)
~CGUIAddonRenderingControl () override=default
bool Create (int x, int y, int w, int h, void *device) override
void Render () override
void Stop () override
bool IsDirty () override
virtual void Delete ()
Public Member Functions inherited from IRenderingCallback
virtual ~IRenderingCallback ()=default
Protected Attributes
bool(* CBCreate)(KODI_GUI_CLIENT_HANDLE cbhdl, int x, int y, int w, int h, void *device)
void(* CBRender)(KODI_GUI_CLIENT_HANDLE cbhdl) = nullptr
void(* CBStop)(KODI_GUI_CLIENT_HANDLE cbhdl) = nullptr
bool(* CBDirty)(KODI_GUI_CLIENT_HANDLE cbhdl) = nullptr
KODI_GUI_CLIENT_HANDLE m_clientHandle = nullptr
CAddonDll * m_addon = nullptr
CGUIRenderingControl * m_control
int m_refCount = 1
Friends
struct Interface_GUIControlAddonRendering
Constructor & Destructor Documentation
CGUIAddonRenderingControl()
ADDON::CGUIAddonRenderingControl::CGUIAddonRenderingControl (CGUIRenderingControl * pControl) explicit
~CGUIAddonRenderingControl()
ADDON::CGUIAddonRenderingControl::~CGUIAddonRenderingControl () override default
Member Function Documentation
Create()
bool ADDON::CGUIAddonRenderingControl::Create (int x, int y, int w, int h, void * device) override virtual
Implements IRenderingCallback.
References CBCreate, m_clientHandle, and m_refCount.
Delete()
void ADDON::CGUIAddonRenderingControl::Delete () virtual
References m_refCount.
IsDirty()
bool ADDON::CGUIAddonRenderingControl::IsDirty () override virtual
Reimplemented from IRenderingCallback.
References CBDirty, and m_clientHandle.
Render()
void ADDON::CGUIAddonRenderingControl::Render () override virtual
Implements IRenderingCallback.
References CBRender, and m_clientHandle.
Stop()
void ADDON::CGUIAddonRenderingControl::Stop () override virtual
Implements IRenderingCallback.
References CBStop, m_clientHandle, and m_refCount.
Friends And Related Symbol Documentation
Interface_GUIControlAddonRendering
friend struct Interface_GUIControlAddonRendering friend
Member Data Documentation
CBCreate
bool(* ADDON::CGUIAddonRenderingControl::CBCreate) (KODI_GUI_CLIENT_HANDLE cbhdl, int x, int y, int w, int h, void *device) protected
Initial value:
=
        nullptr
Referenced by Create(), and ADDON::Interface_GUIControlAddonRendering::set_callbacks().
CBDirty
bool(* ADDON::CGUIAddonRenderingControl::CBDirty) (KODI_GUI_CLIENT_HANDLE cbhdl) = nullptr protected
Referenced by IsDirty(), and ADDON::Interface_GUIControlAddonRendering::set_callbacks().
CBRender
void(* ADDON::CGUIAddonRenderingControl::CBRender) (KODI_GUI_CLIENT_HANDLE cbhdl) = nullptr protected
Referenced by Render(), and ADDON::Interface_GUIControlAddonRendering::set_callbacks().
CBStop
void(* ADDON::CGUIAddonRenderingControl::CBStop) (KODI_GUI_CLIENT_HANDLE cbhdl) = nullptr protected
Referenced by ADDON::Interface_GUIControlAddonRendering::set_callbacks(), and Stop().
m_addon
CAddonDll* ADDON::CGUIAddonRenderingControl::m_addon = nullptr protected
Referenced by ADDON::Interface_GUIControlAddonRendering::set_callbacks().
m_clientHandle
KODI_GUI_CLIENT_HANDLE ADDON::CGUIAddonRenderingControl::m_clientHandle = nullptr protected
Referenced by Create(), IsDirty(), Render(), ADDON::Interface_GUIControlAddonRendering::set_callbacks(), and Stop().
m_control
CGUIRenderingControl* ADDON::CGUIAddonRenderingControl::m_control protected
Referenced by ADDON::Interface_GUIControlAddonRendering::set_callbacks().
m_refCount
int ADDON::CGUIAddonRenderingControl::m_refCount = 1 protected
Referenced by Create(), Delete(), and Stop().
The documentation for this class was generated from the following files:
interfaces/gui/controls/rendering.h
Rendering.cpp