Kodi Documentation: CDVDStateSerializer Class Reference
CDVDStateSerializer Class Reference
Auxiliar class to serialize/deserialize the dvd state (into/from XML)
#include <DVDStateSerializer.h>
Public Member Functions
CDVDStateSerializer ()=default
Default constructor.
~CDVDStateSerializer ()=default
Default destructor.
bool XMLToDVDState (DVDState &state, const std::string &xmlstate)
Provided the state in xml format, fills a DVDState struct representing the DVD state and returns the success status of the operation.
bool DVDStateToXML (std::string &xmlstate, const DVDState &state)
Provided the DVDState struct of the current playing dvd, serializes the struct to XML.
Private Member Functions
void AddXMLElement (tinyxml2::XMLElement &root, const std::string &name, const std::string &value)
Appends a new element with the given name and value to a provided root XML element.
Detailed Description
Auxiliar class to serialize/deserialize the dvd state (into/from XML)
Constructor & Destructor Documentation
CDVDStateSerializer()
CDVDStateSerializer::CDVDStateSerializer () default
Default constructor.
~CDVDStateSerializer()
CDVDStateSerializer::~CDVDStateSerializer () default
Default destructor.
Member Function Documentation
AddXMLElement()
void CDVDStateSerializer::AddXMLElement (tinyxml2::XMLElement & root, const std::string & name, const std::string & value) private
Appends a new element with the given name and value to a provided root XML element.
Parameters
[in,out] root the root xml element to append the new element
name the new element name
value the new element value
References name, root, and value.
Referenced by DVDStateToXML().
DVDStateToXML()
bool CDVDStateSerializer::DVDStateToXML (std::string & xmlstate, const DVDState & state)
Provided the DVDState struct of the current playing dvd, serializes the struct to XML.
Parameters
[in,out] xmlstate a string describing the dvd state (XML)
state the DVD state struct
Returns
true if it was possible to serialize the struct into XML, false otherwise
References AddXMLElement(), DVDState::audio_num, DVDState::current_angle, DVDState::pgcn, DVDState::pgn, DVDState::sub_enabled, DVDState::subp_num, and DVDState::title.
Referenced by CDVDInputStreamNavigator::GetState().
XMLToDVDState()
bool CDVDStateSerializer::XMLToDVDState (DVDState & state, const std::string & xmlstate)
Provided the state in xml format, fills a DVDState struct representing the DVD state and returns the success status of the operation.
Parameters
[in,out] state the DVD state struct to be filled
xmlstate a string describing the dvd state (XML)
Returns
true if it was possible to fill the state struct based on the XML content, false otherwise
References DVDState::audio_num, DVDState::current_angle, LOGERROR, LOGWARNING, CXBMCTinyXML2::Parse(), DVDState::pgcn, DVDState::pgn, DVDState::sub_enabled, DVDState::subp_num, and DVDState::title.
Referenced by CDVDInputStreamNavigator::SetState().
The documentation for this class was generated from the following files:
DVDStateSerializer.h
DVDStateSerializer.cpp