Kodi Documentation: ADDON::CAddonBuilder Class Reference
ADDON::CAddonBuilder Class Reference
#include <AddonBuilder.h>
Static Public Member Functions
static AddonPtr Generate (const AddonInfoPtr &info, AddonType type)
Member Function Documentation
Generate()
AddonPtr ADDON::CAddonBuilder::Generate (const AddonInfoPtr & info, AddonType type) static
References ADDON::AUDIODECODER, ADDON::AUDIOENCODER, ADDON::CONTEXTMENU_ITEM, ADDON::GAME_CONTROLLER, ADDON::GAMEDLL, URIUtils::HasExtension(), ADDON::IMAGEDECODER, ADDON::INPUTSTREAM, ADDON::PERIPHERALDLL, ADDON::PLUGIN, ADDON::PVRDLL, ADDON::REPOSITORY, ADDON::RESOURCE_FONT, ADDON::RESOURCE_GAMES, ADDON::RESOURCE_IMAGES, ADDON::RESOURCE_LANGUAGE, ADDON::RESOURCE_UISOUNDS, ADDON::SCRAPER_ALBUMS, ADDON::SCRAPER_ARTISTS, ADDON::SCRAPER_LIBRARY, ADDON::SCRAPER_MOVIES, ADDON::SCRAPER_MUSICVIDEOS, ADDON::SCRAPER_TVSHOWS, ADDON::SCREENSAVER, ADDON::SCRIPT, ADDON::SCRIPT_LIBRARY, ADDON::SCRIPT_LYRICS, ADDON::SCRIPT_MODULE, ADDON::SCRIPT_WEATHER, ADDON::SERVICE, ADDON::SKIN, ADDON::SUBTITLE_MODULE, ADDON::UNKNOWN, ADDON::VFS, ADDON::VISUALIZATION, and ADDON::WEB_INTERFACE.
Referenced by ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonMgr::GetAddon(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonMgr::GetAddonsInternal(), ADDON::CAddonDatabase::GetRepositoryContent(), ADDON::CAddonMgr::LoadAddonDescription(), TEST_F(), TEST_F(), and TEST_F().
The documentation for this class was generated from the following files:
AddonBuilder.h
AddonBuilder.cpp