Kodi Documentation: CAESinkStarfish Class Reference
CAESinkStarfish Class Reference
#include <AESinkStarfish.h>
Public Member Functions
const char * GetName () override
CAESinkStarfish ()
~CAESinkStarfish () override
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
double GetCacheTotal () override
double GetLatency () override
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void AddPause (unsigned int millis) override
instruct the sink to add a pause
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
void Drain () override
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual bool HasVolume ()
virtual void SetVolume (float volume)
Static Public Member Functions
static void Register ()
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
static void EnumerateDevicesEx (AEDeviceInfoList &list, bool force=false)
Private Member Functions
void PlayerCallback (const int32_t type, const int64_t numValue, const char *strValue)
Static Private Member Functions
static void PlayerCallback (const int32_t type, const int64_t numValue, const char *strValue, void *data)
Private Attributes
std::unique_ptr< StarfishMediaAPIs > m_starfishMediaAPI
AEAudioFormat m_format
std::chrono::nanoseconds m_pts {0}
int64_t m_bufferSize {0}
bool m_firstFeed {true}
Constructor & Destructor Documentation
CAESinkStarfish()
CAESinkStarfish::CAESinkStarfish ()
~CAESinkStarfish()
CAESinkStarfish::~CAESinkStarfish () override default
Member Function Documentation
AddPackets()
unsigned int CAESinkStarfish::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References data(), CAEStreamInfo::GetDuration(), LOGWARNING, m_firstFeed, m_format, AEAudioFormat::m_frameSize, m_pts, m_starfishMediaAPI, AEAudioFormat::m_streamInfo, and CJSONVariantWriter::Write().
AddPause()
void CAESinkStarfish::AddPause (unsigned int millis) override virtual
instruct the sink to add a pause
Parameters
millis ms to pause
Reimplemented from IAESink.
References m_starfishMediaAPI.
Create()
std::unique_ptr< IAESink > CAESinkStarfish::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
Deinitialize()
void CAESinkStarfish::Deinitialize () override virtual
Implements IAESink.
References m_starfishMediaAPI.
Drain()
void CAESinkStarfish::Drain () override virtual
Reimplemented from IAESink.
References m_starfishMediaAPI.
EnumerateDevicesEx()
void CAESinkStarfish::EnumerateDevicesEx (AEDeviceInfoList & list, bool force = false) static
References AE_CH_LAYOUT_2_0, AE_DEVTYPE_IEC958, AE_FMT_RAW, CAEDeviceInfo::m_deviceName, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, and CAEStreamInfo::STREAM_TYPE_EAC3.
Referenced by Register().
GetCacheTotal()
double CAESinkStarfish::GetCacheTotal () override virtual
Implements IAESink.
References AE_FMT_RAW, CAEStreamInfo::GetDuration(), AEAudioFormat::m_dataFormat, m_format, and AEAudioFormat::m_streamInfo.
GetDelay()
void CAESinkStarfish::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References m_pts, m_starfishMediaAPI, and AEDelayStatus::SetDelay().
GetLatency()
double CAESinkStarfish::GetLatency () override virtual
Reimplemented from IAESink.
GetName()
const char * CAESinkStarfish::GetName () inline override virtual
Implements IAESink.
Initialize()
bool CAESinkStarfish::Initialize (AEAudioFormat & format, std::string & device) override virtual
Implements IAESink.
References AE_FMT_RAW, CCompileInfo::GetPackage(), LOGAUDIO, LOGDEBUG, LOGERROR, m_bufferSize, CAEStreamInfo::m_channels, AEAudioFormat::m_dataFormat, m_format, AEAudioFormat::m_frames, AEAudioFormat::m_frameSize, CAEStreamInfo::m_frameSize, m_pts, CAEStreamInfo::m_sampleRate, m_starfishMediaAPI, AEAudioFormat::m_streamInfo, CAEStreamInfo::m_type, PlayerCallback(), CVariant::push_back(), CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, CVariant::VariantTypeArray, and CJSONVariantWriter::Write().
PlayerCallback() [1/2]
void CAESinkStarfish::PlayerCallback (const int32_t type, const int64_t numValue, const char * strValue) private
References LOGDEBUG, and m_starfishMediaAPI.
Referenced by Initialize(), and PlayerCallback().
PlayerCallback() [2/2]
void CAESinkStarfish::PlayerCallback (const int32_t type, const int64_t numValue, const char * strValue, void * data) static private
References data(), and PlayerCallback().
Register()
void CAESinkStarfish::Register () static
References Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::InitWindowSystem().
Member Data Documentation
m_bufferSize
int64_t CAESinkStarfish::m_bufferSize {0} private
Referenced by Initialize().
m_firstFeed
bool CAESinkStarfish::m_firstFeed {true} private
Referenced by AddPackets().
m_format
AEAudioFormat CAESinkStarfish::m_format private
Referenced by AddPackets(), GetCacheTotal(), and Initialize().
m_pts
std::chrono::nanoseconds CAESinkStarfish::m_pts {0} private
Referenced by AddPackets(), GetDelay(), and Initialize().
m_starfishMediaAPI
std::unique_ptr<StarfishMediaAPIs> CAESinkStarfish::m_starfishMediaAPI private
Referenced by AddPackets(), AddPause(), Deinitialize(), Drain(), GetDelay(), Initialize(), and PlayerCallback().
The documentation for this class was generated from the following files:
AESinkStarfish.h
AESinkStarfish.cpp