Kodi Documentation: KODI::CDRIP::CCDDARipJob Class Reference
KODI::CDRIP::CCDDARipJob Class Reference
#include <CDDARipJob.h>
Public Member Functions
CCDDARipJob (const std::string &input, const std::string &output, const MUSIC_INFO::CMusicInfoTag &tag, int encoder, bool eject=false, unsigned int rate=44100, unsigned int channels=2, unsigned int bps=16)
Construct a ripper job.
~CCDDARipJob () override
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
bool DoWork () override
Main workhorse function of CJob instances.
const std::string & GetOutput () const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Protected Member Functions
std::unique_ptr< CEncoder > SetupEncoder (XFILE::CFile &reader)
Setup the audio encoder.
std::string SetupTempFile ()
Helper used if output is a remote url.
int RipChunk (XFILE::CFile &reader, const std::unique_ptr< CEncoder > &encoder, int &percent)
Rip a chunk of audio.
Protected Attributes
unsigned int m_rate
unsigned int m_channels
unsigned int m_bps
MUSIC_INFO::CMusicInfoTag m_tag
std::string m_input
std::string m_output
bool m_eject
int m_encoder
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Constructor & Destructor Documentation
CCDDARipJob()
CCDDARipJob::CCDDARipJob (const std::string & input, const std::string & output, const MUSIC_INFO::CMusicInfoTag & tag, int encoder, bool eject = false, unsigned int rate = 44100, unsigned int channels = 2, unsigned int bps = 16)
Construct a ripper job.
Parameters
[in] input The input file url
[in] output The output file url
[in] tag The music tag to attach to track
[in] encoder The encoder to use. See Encoder.h
[in] eject Should we eject tray on finish?
[in] rate The sample rate of the input
[in] channels Number of audio channels in input
[in] bps The bits per sample for input
~CCDDARipJob()
CCDDARipJob::~CCDDARipJob () override default
Member Function Documentation
DoWork()
bool CCDDARipJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References XFILE::CFile::Close(), XFILE::CFile::Copy(), XFILE::CFile::Delete(), CMediaManager::EjectTray(), g_localizeStrings, CLocalizeStrings::Get(), MUSIC_INFO::CMusicInfoTag::GetArtistString(), CServiceBroker::GetGUI(), CGUIDialogExtendedProgressBar::GetHandle(), CServiceBroker::GetMediaManager(), MUSIC_INFO::CMusicInfoTag::GetTitle(), CGUIComponent::GetWindowManager(), KODI::NETWORK::IsRemote(), CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, m_eject, m_input, m_output, m_tag, XFILE::CFile::Open(), XFILE::READ_CACHED, RipChunk(), SetupEncoder(), SetupTempFile(), CJob::ShouldCancel(), and WINDOW_DIALOG_EXT_PROGRESS.
GetOutput()
const std::string & KODI::CDRIP::CCDDARipJob::GetOutput () const inline
References m_output.
GetType()
const char * KODI::CDRIP::CCDDARipJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CJob.
Referenced by operator==().
operator==()
bool CCDDARipJob::operator== (const CJob * job) const override virtual
Reimplemented from CJob.
References CJob::GetType(), GetType(), m_input, and m_output.
RipChunk()
int CCDDARipJob::RipChunk (XFILE::CFile & reader, const std::unique_ptr< CEncoder > & encoder, int & percent) protected
Rip a chunk of audio.
Parameters
[in] reader The input reader
[in] encoder The audio encoder
[out] percent The percentage completed on return
Returns
0 (CDDARIP_OK) if everything went okay, or a positive error code from the reader, or -1 if the encoder failed
See also
CCDDARipper::GetData, CEncoder::Encode
References XFILE::CFile::GetLength(), XFILE::CFile::GetPosition(), and XFILE::CFile::Read().
Referenced by DoWork().
SetupEncoder()
std::unique_ptr< CEncoder > CCDDARipJob::SetupEncoder (XFILE::CFile & reader) protected
Setup the audio encoder.
References ADDON::CAddonMgr::GetAddonInfo(), CServiceBroker::GetAddonMgr(), MUSIC_INFO::CMusicInfoTag::GetAlbum(), MUSIC_INFO::CMusicInfoTag::GetAlbumArtist(), CSysInfo::GetAppName(), MUSIC_INFO::CMusicInfoTag::GetArtist(), MUSIC_INFO::CMusicInfoTag::GetGenre(), XFILE::CFile::GetLength(), CServiceBroker::GetSettingsComponent(), MUSIC_INFO::CMusicInfoTag::GetTitle(), MUSIC_INFO::CMusicInfoTag::GetYearString(), m_bps, m_channels, m_input, m_output, m_rate, m_tag, and CSettings::SETTING_AUDIOCDS_ENCODER.
Referenced by DoWork().
SetupTempFile()
std::string CCDDARipJob::SetupTempFile () protected
Helper used if output is a remote url.
References MAX_PATH, and CSpecialProtocol::TranslatePath().
Referenced by DoWork().
Member Data Documentation
m_bps
unsigned int KODI::CDRIP::CCDDARipJob::m_bps protected
Referenced by SetupEncoder().
m_channels
unsigned int KODI::CDRIP::CCDDARipJob::m_channels protected
Referenced by SetupEncoder().
m_eject
bool KODI::CDRIP::CCDDARipJob::m_eject protected
Referenced by DoWork().
m_encoder
int KODI::CDRIP::CCDDARipJob::m_encoder protected
m_input
std::string KODI::CDRIP::CCDDARipJob::m_input protected
Referenced by DoWork(), operator==(), and SetupEncoder().
m_output
std::string KODI::CDRIP::CCDDARipJob::m_output protected
Referenced by DoWork(), GetOutput(), operator==(), and SetupEncoder().
m_rate
unsigned int KODI::CDRIP::CCDDARipJob::m_rate protected
Referenced by SetupEncoder().
m_tag
MUSIC_INFO::CMusicInfoTag KODI::CDRIP::CCDDARipJob::m_tag protected
Referenced by DoWork(), and SetupEncoder().
The documentation for this class was generated from the following files:
CDDARipJob.h
CDDARipJob.cpp