Kodi Documentation: CWinSystemAndroid Class Reference
CWinSystemAndroid Class Reference
#include <WinSystemAndroid.h>
Public Member Functions
CWinSystemAndroid ()
~CWinSystemAndroid () override
bool InitWindowSystem () override
bool DestroyWindowSystem () override
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override
bool DestroyWindow () override
void UpdateResolutions () override
void InitiateModeChange ()
bool IsHdmiModeTriggered () const
void SetHdmiState (bool connected)
void UpdateDisplayModes ()
bool HasCursor () override
bool Minimize () override
bool Hide () override
bool Show (bool raise=true) override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
void MessagePush (XBMC_Event *newEvent)
bool MessagePump () override
bool IsHDRDisplay () override
CHDRCapabilities GetDisplayHDRCapabilities () const override
float GetGuiSdrPeakLuminance () const override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual CRenderSystemBase * GetRenderSystem ()
virtual const std::string GetName ()
virtual bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop)=0
virtual bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays)=0
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual void FinishWindowResize (int newWidth, int newHeight)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppFocusChange (bool bGaining)
virtual void NotifyAppActiveChange (bool bActivated)
virtual void ShowOSMouse (bool show)
virtual bool HasInertialGestures ()
virtual bool UseLimitedColor ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual float GetDisplayLatency ()
Get average display latency.
virtual float GetFrameLatencyAdjustment ()
Get time that should be subtracted from the display latency for this frame in milliseconds.
virtual bool Restore ()
virtual std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock)
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
virtual bool CanDoWindowed ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
virtual std::string GetClipboardText (void)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual bool SetHDR (const VideoPicture *videoPicture)
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
virtual std::vector< std::string > GetConnectedOutputs ()
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
virtual bool BindTextureUploadContext ()
Binds a shared context to the current thread, in order to upload textures asynchronously.
virtual bool UnbindTextureUploadContext ()
Unbinds the shared context.
virtual bool HasContext ()
Checks if a graphics context is already bound to the current thread.
Public Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Protected Member Functions
std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl () override
void OnTimeout () override
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
Protected Attributes
CAndroidUtils * m_android
EGLDisplay m_nativeDisplay = EGL_NO_DISPLAY
std::shared_ptr< CNativeWindow > m_nativeWindow
int m_displayWidth
int m_displayHeight
RENDER_STEREO_MODE m_stereo_mode
CTimer * m_dispResetTimer
CCriticalSection m_resourceSection
std::vector< IDispResource * > m_resources
CDecoderFilterManager * m_decoderFilterManager
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Private Member Functions
void UpdateResolutions (bool bUpdateDesktopRes)
Private Attributes
bool m_HdmiModeTriggered = false
Additional Inherited Members
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Constructor & Destructor Documentation
CWinSystemAndroid()
CWinSystemAndroid::CWinSystemAndroid ()
References m_android, m_displayHeight, m_displayWidth, m_dispResetTimer, m_stereo_mode, CWinSystemBase::m_winEvents, and RENDER_STEREO_MODE_OFF.
~CWinSystemAndroid()
CWinSystemAndroid::~CWinSystemAndroid () override
References m_dispResetTimer.
Member Function Documentation
CreateNewWindow()
bool CWinSystemAndroid::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) override virtual
Implements CWinSystemBase.
Reimplemented in CWinSystemAndroidGLESContext.
References RESOLUTION_INFO::fRefreshRate, CXBMCApp::Get(), CWinSystemBase::GetGfxContext(), CXBMCApp::GetNativeWindow(), CGraphicContext::GetStereoMode(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iWidth, CLog::Log(), LOGERROR, m_android, CWinSystemBase::m_bFullScreen, CWinSystemBase::m_bWindowCreated, m_displayHeight, m_displayWidth, m_dispResetTimer, CWinSystemBase::m_fRefreshRate, m_HdmiModeTriggered, m_nativeWindow, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, m_stereo_mode, CAndroidUtils::SetNativeResolution(), and CTimer::Stop().
Referenced by CWinSystemAndroidGLESContext::CreateNewWindow().
DestroyWindow()
bool CWinSystemAndroid::DestroyWindow () override virtual
Reimplemented from CWinSystemBase.
References CLog::Log(), LOGINFO, CWinSystemBase::m_bWindowCreated, and m_nativeWindow.
DestroyWindowSystem()
bool CWinSystemAndroid::DestroyWindowSystem () override virtual
Reimplemented from CWinSystemBase.
References CLog::Log(), LOGINFO, m_android, m_decoderFilterManager, and CServiceBroker::RegisterDecoderFilterManager().
GetDisplayHDRCapabilities()
CHDRCapabilities CWinSystemAndroid::GetDisplayHDRCapabilities () const override virtual
Reimplemented from CWinSystemBase.
References CAndroidUtils::GetDisplayHDRCapabilities().
GetGuiSdrPeakLuminance()
float CWinSystemAndroid::GetGuiSdrPeakLuminance () const override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOSCREEN_GUISDRPEAKLUMINANCE.
GetOSScreenSaverImpl()
std::unique_ptr< WINDOWING::IOSScreenSaver > CWinSystemAndroid::GetOSScreenSaverImpl () override protected virtual
Reimplemented from CWinSystemBase.
HasCursor()
bool CWinSystemAndroid::HasCursor () inline override virtual
Reimplemented from CWinSystemBase.
Hide()
bool CWinSystemAndroid::Hide () override virtual
Reimplemented from CWinSystemBase.
InitiateModeChange()
void CWinSystemAndroid::InitiateModeChange ()
References CServiceBroker::GetSettingsComponent(), m_dispResetTimer, SetHdmiState(), CTimer::Start(), and CTimer::Stop().
InitWindowSystem()
bool CWinSystemAndroid::InitWindowSystem () override virtual
Reimplemented from CWinSystemBase.
Reimplemented in CWinSystemAndroidGLESContext.
References CWinSystemBase::InitWindowSystem(), m_android, m_decoderFilterManager, m_nativeDisplay, ADDON::Interface_Android::Register(), KODI::RETRO::CRPProcessInfoAndroid::Register(), CDVDAudioCodecAndroidMediaCodec::Register(), CDVDVideoCodecAndroidMediaCodec::Register(), VIDEOPLAYER::CProcessInfoAndroid::Register(), CRendererMediaCodec::Register(), CRendererMediaCodecSurface::Register(), CLinuxRendererGLES::Register(), DRM::CMediaDrmCryptoSession::Register(), CScreenshotSurfaceGLES::Register(), and CServiceBroker::RegisterDecoderFilterManager().
Referenced by CWinSystemAndroidGLESContext::InitWindowSystem().
IsHdmiModeTriggered()
bool CWinSystemAndroid::IsHdmiModeTriggered () const inline
References m_HdmiModeTriggered.
Referenced by CWinSystemAndroidGLESContext::PresentRenderImpl().
IsHDRDisplay()
bool CWinSystemAndroid::IsHDRDisplay () override virtual
Reimplemented from CWinSystemBase.
Reimplemented in CWinSystemAndroidGLESContext.
References CAndroidUtils::IsHDRDisplay(), and m_android.
Referenced by CWinSystemAndroidGLESContext::IsHDRDisplay().
MessagePump()
bool CWinSystemAndroid::MessagePump () override virtual
Reimplemented from CWinSystemBase.
References CWinSystemBase::m_winEvents.
MessagePush()
void CWinSystemAndroid::MessagePush (XBMC_Event * newEvent)
References CWinEventsAndroid::MessagePush().
Referenced by CAndroidKey::XBMC_Key().
Minimize()
bool CWinSystemAndroid::Minimize () override virtual
Reimplemented from CWinSystemBase.
References CXBMCApp::Get().
OnTimeout()
void CWinSystemAndroid::OnTimeout () override protected virtual
Implements ITimerCallback.
References m_HdmiModeTriggered.
Register()
void CWinSystemAndroid::Register (IDispResource * resource) override virtual
Implements CWinSystemBase.
References m_resources, and m_resourceSection.
SetHdmiState()
void CWinSystemAndroid::SetHdmiState (bool connected)
References CTimer::GetElapsedMilliseconds(), CServiceBroker::GetSettingsComponent(), CTimer::IsRunning(), CLog::Log(), LOGDEBUG, m_dispResetTimer, m_HdmiModeTriggered, m_resources, m_resourceSection, and CTimer::Stop().
Referenced by InitiateModeChange(), and CWinSystemAndroidGLESContext::PresentRenderImpl().
Show()
bool CWinSystemAndroid::Show (bool raise = true) override virtual
Reimplemented from CWinSystemBase.
Unregister()
void CWinSystemAndroid::Unregister (IDispResource * resource) override virtual
Implements CWinSystemBase.
References m_resources, and m_resourceSection.
UpdateDisplayModes()
void CWinSystemAndroid::UpdateDisplayModes ()
References m_android, m_nativeWindow, CAndroidUtils::UpdateDisplayModes(), and UpdateResolutions().
Referenced by CXBMCApp::onDisplayChanged().
UpdateResolutions() [1/2]
void CWinSystemAndroid::UpdateResolutions () override virtual
Reimplemented from CWinSystemBase.
References UpdateResolutions().
Referenced by UpdateDisplayModes(), and UpdateResolutions().
UpdateResolutions() [2/2]
void CWinSystemAndroid::UpdateResolutions (bool bUpdateDesktopRes) private
References CDisplaySettings::AddResolutionInfo(), CDisplaySettings::ApplyCalibrations(), CDisplaySettings::ClearCustomResolutions(), D3DPRESENTFLAG_MODEMASK, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fRefreshRate, CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CAndroidUtils::GetNativeResolution(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, CLog::Log(), LOGWARNING, m_android, CAndroidUtils::ProbeResolutions(), RES_DESKTOP, RES_WINDOW, CGraphicContext::ResetOverscan(), and CWinSystemBase::UpdateResolutions().
Member Data Documentation
m_android
CAndroidUtils* CWinSystemAndroid::m_android protected
Referenced by CreateNewWindow(), CWinSystemAndroid(), DestroyWindowSystem(), InitWindowSystem(), IsHDRDisplay(), UpdateDisplayModes(), and UpdateResolutions().
m_decoderFilterManager
CDecoderFilterManager* CWinSystemAndroid::m_decoderFilterManager protected
Referenced by DestroyWindowSystem(), and InitWindowSystem().
m_displayHeight
int CWinSystemAndroid::m_displayHeight protected
Referenced by CreateNewWindow(), and CWinSystemAndroid().
m_displayWidth
int CWinSystemAndroid::m_displayWidth protected
Referenced by CreateNewWindow(), and CWinSystemAndroid().
m_dispResetTimer
CTimer* CWinSystemAndroid::m_dispResetTimer protected
Referenced by CreateNewWindow(), CWinSystemAndroid(), InitiateModeChange(), SetHdmiState(), and ~CWinSystemAndroid().
m_HdmiModeTriggered
bool CWinSystemAndroid::m_HdmiModeTriggered = false private
Referenced by CreateNewWindow(), IsHdmiModeTriggered(), OnTimeout(), and SetHdmiState().
m_nativeDisplay
EGLDisplay CWinSystemAndroid::m_nativeDisplay = EGL_NO_DISPLAY protected
Referenced by InitWindowSystem(), and CWinSystemAndroidGLESContext::InitWindowSystem().
m_nativeWindow
std::shared_ptr<CNativeWindow> CWinSystemAndroid::m_nativeWindow protected
Referenced by CreateNewWindow(), CWinSystemAndroidGLESContext::CreateSurface(), DestroyWindow(), CWinSystemAndroidGLESContext::PresentRenderImpl(), and UpdateDisplayModes().
m_resources
std::vector<IDispResource*> CWinSystemAndroid::m_resources protected
Referenced by Register(), SetHdmiState(), and Unregister().
m_resourceSection
CCriticalSection CWinSystemAndroid::m_resourceSection protected
Referenced by Register(), SetHdmiState(), and Unregister().
m_stereo_mode
RENDER_STEREO_MODE CWinSystemAndroid::m_stereo_mode protected
Referenced by CreateNewWindow(), and CWinSystemAndroid().
The documentation for this class was generated from the following files:
WinSystemAndroid.h
WinSystemAndroid.cpp